LLVM: lib/Target/AArch64/AArch64CallLowering.cpp File Reference
AArch64CallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "AArch64CallLowering.h"
#include "AArch64ISelLowering.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/LowLevelType.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/MachineValueType.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iterator>
Macros
#define DEBUG_TYPE "aarch64-call-lowering"
Functions
static bool doesCalleeRestoreStack (CallingConv::ID CallConv, bool TailCallOpt)
static void handleMustTailForwardedRegisters (MachineIRBuilder &MIRBuilder, CCAssignFn *AssignFn)
Helper function to compute forwarded registers for musttail calls.
static bool canGuaranteeTCO (CallingConv::ID CC)
Return true if the calling convention is one that we can guarantee TCO for.
static bool mayTailCallThisCC (CallingConv::ID CC)
Return true if we might ever do TCO for calls with this calling convention.
static std::pair< CCAssignFn *, CCAssignFn * > getAssignFnsForCC (CallingConv::ID CC, const AArch64TargetLowering &TLI)
Returns a pair containing the fixed CCAssignFn and the vararg CCAssignFn for CC.
static unsigned getCallOpcode (const Function &CallerF, bool IsIndirect, bool IsTailCall)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file AArch64CallLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-call-lowering"
Definition at line 47 of file AArch64CallLowering.cpp.
Function Documentation
canGuaranteeTCO()
static bool canGuaranteeTCO (CallingConv::ID CC) static
Return true if the calling convention is one that we can guarantee TCO for.
Definition at line 498 of file AArch64CallLowering.cpp.
References llvm::CallingConv::Fast.
Referenced by llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), and mayTailCallThisCC().
doesCalleeRestoreStack()
static bool doesCalleeRestoreStack (CallingConv::ID CallConv, bool TailCallOpt) static
Definition at line 215 of file AArch64CallLowering.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::ComputeValueVTs(), llvm::numbers::e, llvm::SmallVectorImpl< T >::emplace_back(), llvm::CallingConv::Fast, llvm::AArch64TargetLowering::functionArgumentNeedsConsecutiveRegisters(), MRI, and llvm::SmallVectorBase::size().
Referenced by llvm::AArch64CallLowering::lowerCall(), and llvm::AArch64CallLowering::lowerFormalArguments().
getAssignFnsForCC()
static std::pair<CCAssignFn *, CCAssignFn *> getAssignFnsForCC (CallingConv::ID CC, const AArch64TargetLowering & TLI) static
Returns a pair containing the fixed CCAssignFn and the vararg CCAssignFn for CC.
Definition at line 517 of file AArch64CallLowering.cpp.
References llvm::CallLowering::analyzeArgInfo(), llvm::AArch64TargetLowering::CCAssignFnForCall(), llvm::MachineOperand::clobbersPhysReg(), llvm::dbgs(), llvm::SmallVectorBase::empty(), llvm::AArch64FunctionInfo::getBytesInStackArgArea(), llvm::Function::getCallingConv(), llvm::Function::getContext(), llvm::getDefIgnoringCopies(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::AArch64Subtarget::hasCustomCallingConv(), Info, LLVM_DEBUG, Reg, llvm::CallLowering::resultsCompatible(), llvm::SmallVectorBase::size(), and TRI.
Referenced by getCallOpcode(), and llvm::AArch64CallLowering::lowerCall().
getCallOpcode()
static unsigned getCallOpcode (const Function & CallerF, bool IsIndirect, bool IsTailCall) static
Definition at line 762 of file AArch64CallLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::alignTo(), llvm::CallLowering::analyzeArgInfo(), llvm::any_of(), assert(), llvm::ARCISD::BL, llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::constrainOperandRegClass(), llvm::dbgs(), F(), getAssignFnsForCC(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::TargetSubtargetInfo::getRegBankInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::CallLowering::handleAssignments(), llvm::AArch64Subtarget::hasCustomCallingConv(), llvm::Function::hasFnAttribute(), llvm::RegState::Implicit, Info, llvm::MachineIRBuilder::insertInstr(), LLVM_DEBUG, llvm::BitmaskEnumDetail::Mask(), llvm::TargetMachine::Options, Register, llvm::MachineFrameInfo::setHasTailCall(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setReg(), and TRI.
Referenced by llvm::ARMCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), and llvm::ARMCallLowering::lowerFormalArguments().
handleMustTailForwardedRegisters()
static void handleMustTailForwardedRegisters (MachineIRBuilder & MIRBuilder, CCAssignFn * AssignFn) static
Helper function to compute forwarded registers for musttail calls.
Computes the forwarded registers, sets MBB liveness, and emits COPY instructions that can be used to save + restore registers later.
Definition at line 376 of file AArch64CallLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::addLiveIn(), assert(), llvm::MachineIRBuilder::buildCopy(), F(), llvm::MVT::f128, llvm::MachineFunction::getContext(), llvm::AArch64FunctionInfo::getForwardedMustTailRegParms(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMBB(), llvm::MachineIRBuilder::getMF(), llvm::MachineFrameInfo::hasMustTailInVarArgFunc(), llvm::MVT::i64, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), and Register.
Referenced by llvm::AArch64CallLowering::lowerFormalArguments().
mayTailCallThisCC()
static bool mayTailCallThisCC (CallingConv::ID CC) static
Return true if we might ever do TCO for calls with this calling convention.
Definition at line 503 of file AArch64CallLowering.cpp.
References llvm::CallingConv::C, canGuaranteeTCO(), llvm::CallingConv::PreserveMost, and llvm::CallingConv::Swift.
Referenced by llvm::AArch64CallLowering::isEligibleForTailCallOptimization().