LLVM: lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp File Reference
AArch64ExpandPseudoInsts.cpp File Reference
#include "AArch64ExpandImm.h"
#include "AArch64InstrInfo.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64Subtarget.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "Utils/AArch64BaseInfo.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Triple.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Pass.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <limits>
#include <utility>
Macros
#define AARCH64_EXPAND_PSEUDO_NAME "AArch64 pseudo instruction expansion pass"
Functions
INITIALIZE_PASS (AArch64ExpandPseudo, "aarch64-expand-pseudo", AARCH64_EXPAND_PSEUDO_NAME, false, false) static void transferImpOps(MachineInstr &OldMI
Transfer implicit operands on the pseudo instruction to the instructions created from the expansion.
for (unsigned i=Desc.getNumOperands(), e=OldMI.getNumOperands();i !=e;++i)
Variables
MachineInstrBuilder & UseMI
MachineInstrBuilder MachineInstrBuilder & DefMI
Macro Definition Documentation
AARCH64_EXPAND_PSEUDO_NAME
#define AARCH64_EXPAND_PSEUDO_NAME "AArch64 pseudo instruction expansion pass"
Definition at line 46 of file AArch64ExpandPseudoInsts.cpp.
Function Documentation
for()
for (unsigned i = Desc.getNumOperands(), e = OldMI.getNumOperands(); i != e; ++i)
Definition at line 95 of file AArch64ExpandPseudoInsts.cpp.
References llvm::abs(), add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineInstrBuilder::addUse(), llvm::AArch64ISD::ADRP, assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::computeAndAddLiveIns(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::RegState::Define, E, llvm::emitFrameOffset(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::AArch64CC::EQ, llvm::MachineInstr::eraseFromParent(), llvm::AArch64_IMM::expandMOVImm(), llvm::AArch64_AM::getArithExtendImm(), llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetMachine::getCodeModel(), llvm::getDeadRegState(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getFlags(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::getKillRegState(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::AArch64_AM::getShifterImm(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getSymbolName(), llvm::AArch64FunctionInfo::getTaggedBasePointerOffset(), llvm::MachineFunction::getTarget(), llvm::MachineOperand::getTargetFlags(), llvm::TargetMachine::getTargetTriple(), I, llvm::RegState::Implicit, llvm::MachineFunction::insert(), llvm::MachineOperand::isCPI(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isGlobal(), llvm::Triple::isOSFuchsia(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRenamable(), llvm::MachineOperand::isSymbol(), llvm::AArch64Subtarget::isTargetILP32(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::CodeModel::Kernel, llvm::RegState::Kill, llvm_unreachable, llvm::AArch64ISD::LOADgot, llvm::AArch64_AM::LSL, MI, llvm::AArch64II::MO_G3, llvm::AArch64II::MO_NC, llvm::AArch64II::MO_PAGE, llvm::AArch64II::MO_PAGEOFF, llvm::AArch64II::MO_PREL, llvm::AArch64II::MO_TAGGED, Modified, llvm::AArch64CC::NE, llvm::RegState::Renamable, llvm::ARCISD::RET, llvm::MachineInstrBuilder::setMIFlags(), llvm::SmallVectorBase::size(), llvm::Tag, TII, llvm::CodeModel::Tiny, TRI, llvm::RegState::Undef, llvm::AArch64Subtarget::useEL1ForTP(), llvm::AArch64Subtarget::useEL2ForTP(), llvm::AArch64Subtarget::useEL3ForTP(), UseMI, llvm::AArch64_AM::UXTB, and llvm::AArch64_AM::UXTH.
Referenced by analyzeGlobalAux(), llvm::DwarfDebug::beginModule(), CalcNodeSethiUllmanNumber(), checkDyldCommand(), checkDylibCommand(), checkRpathCommand(), checkSubCommand(), collectBitParts(), llvm::AppleAcceleratorTable::dump(), llvm::BitTracker::RegisterCell::extract(), firstch(), freeset(), freezeset(), getLayoutSuccessorProbThreshold(), llvm::TargetLowering::getMultipleConstraintMatchWeight(), llvm::SelectionDAGBuilder::handleDebugValue(), INITIALIZE_PASS(), llvm::InsertPointAnalysis::InsertPointAnalysis(), isLoadConditional(), isProfitableChain(), IsSafeToMove(), mayUsePostIncMode(), nch(), llvm::BitVector::operator &=(), llvm::operator<<(), llvm::UnrollLoop(), and writeContent().
INITIALIZE_PASS()
INITIALIZE_PASS (AArch64ExpandPseudo , "aarch64-expand-pseudo" , AARCH64_EXPAND_PSEUDO_NAME , false , false) &
Transfer implicit operands on the pseudo instruction to the instructions created from the expansion.
Variable Documentation
DefMI
MachineInstrBuilder MachineInstrBuilder& DefMI
Initial value:
{
  const MCInstrDesc &Desc = OldMI.getDesc()
Definition at line 93 of file AArch64ExpandPseudoInsts.cpp.
Referenced by addSegmentsWithValNo(), allPhiOperandsUndefined(), llvm::CombinerHelper::applyCombineShuffleVector(), canFoldIntoCSel(), llvm::LiveRangeEdit::checkRematerializable(), llvm::SIInstrInfo::commuteOpcode(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::LiveRangeEdit::create(), llvm::createSIWholeQuadModePass(), CriticalPathStep(), definesFullReg(), llvm::SplitEditor::dump(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::getDefIgnoringCopies(), llvm::PPCInstrInfo::getDefMIPostRA(), getDepthOfOptCmov(), llvm::ARMHazardRecognizer::getHazardType(), getInsertVecEltOpInfo(), llvm::MachineTraceMetrics::Trace::getInstrCycles(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::getOpcodeDef(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::getRegSubRegPair(), llvm::TargetSchedModel::getResourceBufferSize(), getSingleDef(), getUnderlyingObjects(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), isAmbiguous(), isCrossCopy(), isFullCopyOf(), isKilled(), llvm::isKnownNeverNaN(), llvm::ARMBaseInstrInfo::isProfitableToDupForIfCvt(), llvm::X86InstrInfo::isSafeToClobberEFLAGS(), isVirtualRegisterOperand(), llvm::TargetInstrInfo::isZeroCost(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), pushDepHeight(), regIsPICBase(), removeCopies(), scavengeVReg(), swapMIOperands(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), llvm::LegalizationArtifactCombiner::tryFoldImplicitDef(), tryFoldInst(), updatePHIs(), updatePhysDepsDownwards(), usedAsAddr(), and llvm::MachineTraceMetrics::Ensemble::verify().
UseMI
MachineInstrBuilder& UseMI
Definition at line 92 of file AArch64ExpandPseudoInsts.cpp.
Referenced by addSegmentsWithValNo(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::SIInstrInfo::commuteOpcode(), computeBranchTargetAndInversion(), CriticalPathStep(), llvm::CombinerHelper::dominates(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::ModuloScheduleExpander::expand(), findOnlyInterestingUse(), llvm::ARMBaseInstrInfo::FoldImmediate(), for(), llvm::Localizer::getAnalysisUsage(), llvm::MachineTraceMetrics::Trace::getInstrCycles(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::RegScavenger::getRegsAvailable(), llvm::getRegSubRegPair(), llvm::TargetSchedModel::getResourceBufferSize(), getUnderlyingObjects(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), isAmbiguous(), isCallerPreservedOrConstPhysReg(), isCoalescable(), isCopyFeedingInvariantStore(), isCrossCopy(), isDefLiveOut(), isEFLAGSLive(), isFullCopyOf(), llvm::CombinerHelper::isPredecessor(), llvm::ARMBaseInstrInfo::isProfitableToDupForIfCvt(), llvm::X86InstrInfo::isSafeToClobberEFLAGS(), llvm::PPCInstrInfo::isSameClassPhysRegCopy(), isVirtualRegisterOperand(), llvm::TargetInstrInfo::isZeroCost(), llvm::MachineRegisterInfo::markUsesInDebugValueAsUndef(), llvm::CombinerHelper::matchCombineExtendingLoads(), llvm::SIInstrInfo::moveToVALU(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), regOverlapsSet(), llvm::MachineSSAUpdater::RewriteUse(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::RegScavenger::scavengeRegister(), llvm::RegScavenger::scavengeRegisterBackwards(), llvm::LiveIntervals::shrinkToUses(), llvm::TailDuplicator::tailDuplicateAndUpdate(), tryChangeVGPRtoSGPRinCopy(), tryToFoldACImm(), llvm::MachineTraceMetrics::Ensemble::updateDepth(), updatePhysDepsDownwards(), usedAsAddr(), and verifyCFIntrinsic().