LLVM: lib/Target/AArch64/AArch64StorePairSuppress.cpp File Reference
AArch64StorePairSuppress.cpp File Reference
#include "AArch64InstrInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineTraceMetrics.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "aarch64-stp-suppress"
#define STPSUPPRESS_PASS_NAME "AArch64 Store Pair Suppression"
Functions
INITIALIZE_PASS (AArch64StorePairSuppress, "aarch64-stp-suppress", STPSUPPRESS_PASS_NAME, false, false) FunctionPass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-stp-suppress"
Definition at line 25 of file AArch64StorePairSuppress.cpp.
STPSUPPRESS_PASS_NAME
#define STPSUPPRESS_PASS_NAME "AArch64 Store Pair Suppression"
Definition at line 27 of file AArch64StorePairSuppress.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (AArch64StorePairSuppress , "aarch64-stp-suppress" , STPSUPPRESS_PASS_NAME , false , false)
Definition at line 63 of file AArch64StorePairSuppress.cpp.
References llvm::dbgs(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::HexagonInstrInfo::getMemOperandWithOffset(), llvm::MachineFunction::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineTraceMetrics::Trace::getResourceLength(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isReg(), llvm::MCSchedClassDesc::isValid(), llvm::MCSchedClassDesc::isVariant(), LLVM_DEBUG, MI, MRI, llvm::None, llvm::ARM_MB::ST, TII, TRI, and llvm::MachineTraceMetrics::TS_MinInstrCount.