LLVM: lib/Target/AArch64/AArch64DeadRegisterDefinitionsPass.cpp File Reference
AArch64DeadRegisterDefinitionsPass.cpp File Reference
#include "AArch64.h"
#include "AArch64RegisterInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "aarch64-dead-defs"
#define AARCH64_DEAD_REG_DEF_NAME "AArch64 Dead register definitions"
Functions
STATISTIC (NumDeadDefsReplaced, "Number of dead definitions replaced")
INITIALIZE_PASS (AArch64DeadRegisterDefinitions, "aarch64-dead-defs", AARCH64_DEAD_REG_DEF_NAME, false, false) static bool usesFrameIndex(const MachineInstr &MI)
static bool atomicReadDroppedOnZero (unsigned Opcode)
Macro Definition Documentation
AARCH64_DEAD_REG_DEF_NAME
#define AARCH64_DEAD_REG_DEF_NAME "AArch64 Dead register definitions"
Definition at line 32 of file AArch64DeadRegisterDefinitionsPass.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-dead-defs"
Definition at line 28 of file AArch64DeadRegisterDefinitionsPass.cpp.
Function Documentation
atomicReadDroppedOnZero()
static bool atomicReadDroppedOnZero (unsigned Opcode) static
Definition at line 77 of file AArch64DeadRegisterDefinitionsPass.cpp.
References assert(), llvm::atomicBarrierDroppedOnZero(), llvm::TargetRegisterClass::contains(), llvm::dbgs(), E, llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MCInstrDesc::getNumDefs(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MI, MRI, llvm::Pass::print(), Reg, llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setReg(), TII, and TRI.
INITIALIZE_PASS()
INITIALIZE_PASS (AArch64DeadRegisterDefinitions , "aarch64-dead-defs" , AARCH64_DEAD_REG_DEF_NAME , false , false) const &
Definition at line 61 of file AArch64DeadRegisterDefinitionsPass.cpp.
STATISTIC()
STATISTIC (NumDeadDefsReplaced , "Number of dead definitions replaced")