LLVM: lib/Target/AArch64/AArch64CompressJumpTables.cpp File Reference
AArch64CompressJumpTables.cpp File Reference
#include "AArch64.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "aarch64-jump-tables"
Functions
STATISTIC (NumJT8, "Number of jump-tables with 1-byte entries")
STATISTIC (NumJT16, "Number of jump-tables with 2-byte entries")
STATISTIC (NumJT32, "Number of jump-tables with 4-byte entries")
INITIALIZE_PASS (AArch64CompressJumpTables, DEBUG_TYPE, "AArch64 compress jump tables pass", false, false) int AArch64CompressJumpTables
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-jump-tables"
Definition at line 28 of file AArch64CompressJumpTables.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (AArch64CompressJumpTables , DEBUG_TYPE , "AArch64 compress jump tables pass" , false , false)
Definition at line 64 of file AArch64CompressJumpTables.cpp.
References llvm::alignTo(), assert(), llvm::SmallVectorImpl< T >::clear(), llvm::MCInstrInfo::get(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::TargetInstrInfo::getInstSizeInBytes(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineFunction::getNumBlockIDs(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::getSymbol(), llvm::Function::hasMinSize(), llvm::isUInt< 16 >(), llvm::isUInt< 8 >(), llvm::HexagonISD::JT, llvm::max(), llvm::MachineJumpTableEntry::MBBs, MI, llvm::Align::None(), llvm::SmallVectorImpl< T >::resize(), llvm::MachineInstr::setDesc(), llvm::AArch64FunctionInfo::setJumpTableEntryInfo(), Size, and llvm::ARM_MB::ST.
STATISTIC() [1/3]
STATISTIC (NumJT8 , "Number of jump-tables with 1-byte entries")
STATISTIC() [2/3]
STATISTIC (NumJT16 , "Number of jump-tables with 2-byte entries")
STATISTIC() [3/3]
STATISTIC (NumJT32 , "Number of jump-tables with 4-byte entries")