LLVM: lib/Target/AArch64/AArch64FrameLowering.cpp File Reference
AArch64FrameLowering.cpp File Reference
#include "AArch64FrameLowering.h"
#include "AArch64InstrInfo.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64RegisterInfo.h"
#include "AArch64StackOffset.h"
#include "AArch64Subtarget.h"
#include "AArch64TargetMachine.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <vector>
Macros
#define DEBUG_TYPE "frame-info"
Functions
STATISTIC (NumRedZoneFunctions, "Number of functions using red zone")
static unsigned estimateRSStackSizeLimit (MachineFunction &MF)
Look at each instruction that references stack frames and return the stack size limit beyond which some of these instructions will require a scratch register during their expansion later.
static StackOffset getSVEStackSize (const MachineFunction &MF)
Returns the size of the entire SVE stackframe (calleesaves + spills).
static bool ShouldSignReturnAddress (MachineFunction &MF)
static unsigned findScratchNonCalleeSaveRegister (MachineBasicBlock *MBB)
static bool windowsRequiresStackProbe (MachineFunction &MF, uint64_t StackSizeInBytes)
static MachineBasicBlock::iterator InsertSEH (MachineBasicBlock::iterator MBBI, const TargetInstrInfo &TII, MachineInstr::MIFlag Flag)
static void fixupSEHOpcode (MachineBasicBlock::iterator MBBI, unsigned LocalStackSize)
static MachineBasicBlock::iterator convertCalleeSaveRestoreToSPPrePostIncDec (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, const TargetInstrInfo *TII, int CSStackSizeInc, bool NeedsWinCFI, bool *HasWinCFI, bool InProlog=true)
static void fixupCalleeSaveRestoreStackOffset (MachineInstr &MI, uint64_t LocalStackSize, bool NeedsWinCFI, bool *HasWinCFI)
static void adaptForLdStOpt (MachineBasicBlock &MBB, MachineBasicBlock::iterator FirstSPPopI, MachineBasicBlock::iterator LastPopI)
static bool ShouldSignWithAKey (MachineFunction &MF)
static bool needsWinCFI (const MachineFunction &MF)
static bool isTargetDarwin (const MachineFunction &MF)
static bool isTargetWindows (const MachineFunction &MF)
static bool IsSVECalleeSave (MachineBasicBlock::iterator I)
static void InsertReturnAddressAuth (MachineFunction &MF, MachineBasicBlock &MBB)
static bool isFuncletReturnInstr (const MachineInstr &MI)
static StackOffset getFPOffset (const MachineFunction &MF, int64_t ObjectOffset)
static StackOffset getStackOffset (const MachineFunction &MF, int64_t ObjectOffset)
static unsigned getPrologueDeath (MachineFunction &MF, unsigned Reg)
static bool produceCompactUnwindFrame (MachineFunction &MF)
static bool invalidateWindowsRegisterPairing (unsigned Reg1, unsigned Reg2, bool NeedsWinCFI)
static bool invalidateRegisterPairing (unsigned Reg1, unsigned Reg2, bool UsesWinAAPCS, bool NeedsWinCFI, bool NeedsFrameRecord)
Returns true if Reg1 and Reg2 cannot be paired using a ldp/stp instruction.
static void computeCalleeSaveRegisterPairs (MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI, SmallVectorImpl< RegPairInfo > &RegPairs, bool &NeedShadowCallStackProlog, bool NeedsFrameRecord)
static bool getSVECalleeSaveSlotRange (const MachineFrameInfo &MFI, int &Min, int &Max)
returns true if there are any SVE callee saves.
static int64_t determineSVEStackObjectOffsets (MachineFrameInfo &MFI, int &MinCSFrameIndex, int &MaxCSFrameIndex, bool AssignOffsets)
Variables
static cl::opt< bool > EnableRedZone ("aarch64-redzone", cl::desc("enable use of redzone on AArch64"), cl::init(false), cl::Hidden)
static cl::opt< bool > ReverseCSRRestoreSeq ("reverse-csr-restore-seq", cl::desc("reverse the CSR restore sequence"), cl::init(false), cl::Hidden)
static const unsigned DefaultSafeSPDisplacement = 255
This is the biggest offset to the stack pointer we can encode in aarch64 instructions (without using a separate calculation and a temp register).
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "frame-info"
Definition at line 162 of file AArch64FrameLowering.cpp.
Function Documentation
adaptForLdStOpt()
static void adaptForLdStOpt (MachineBasicBlock & MBB, MachineBasicBlock::iterator FirstSPPopI, MachineBasicBlock::iterator LastPopI) static
Definition at line 786 of file AArch64FrameLowering.cpp.
References ReverseCSRRestoreSeq, and llvm::MachineBasicBlock::splice().
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
computeCalleeSaveRegisterPairs()
static void computeCalleeSaveRegisterPairs (MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI, SmallVectorImpl< RegPairInfo > & RegPairs, bool & NeedShadowCallStackProlog, bool NeedsFrameRecord) static
Definition at line 1935 of file AArch64FrameLowering.cpp.
References assert(), contains(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::AArch64FunctionInfo::getSVECalleeSavedStackSize(), llvm::GPR, llvm::AArch64FunctionInfo::hasCalleeSaveStackFreeSpace(), llvm::Function::hasFnAttribute(), invalidateRegisterPairing(), invalidateWindowsRegisterPairing(), isTargetWindows(), llvm::AArch64Subtarget::isXRegisterReserved(), llvm_unreachable, needsWinCFI(), llvm::CallingConv::PreserveMost, produceCompactUnwindFrame(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), and llvm::NVPTX::PTXCvtMode::RPI.
Referenced by llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
convertCalleeSaveRestoreToSPPrePostIncDec()
static MachineBasicBlock::iterator convertCalleeSaveRestoreToSPPrePostIncDec (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, const TargetInstrInfo * TII, int CSStackSizeInc, bool NeedsWinCFI, bool * HasWinCFI, bool InProlog = true) static
Definition at line 627 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::RegState::Define, llvm::MachineBasicBlock::erase(), llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, llvm::MCInstrInfo::get(), InsertSEH(), llvm::AArch64InstrInfo::isSEHInstruction(), llvm_unreachable, llvm::MachineInstrBuilder::setMemRefs(), and llvm::MachineInstrBuilder::setMIFlags().
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::emitPrologue().
determineSVEStackObjectOffsets()
static int64_t determineSVEStackObjectOffsets (MachineFrameInfo & MFI, int & MinCSFrameIndex, int & MaxCSFrameIndex, bool AssignOffsets) static
Definition at line 2531 of file AArch64FrameLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::alignTo(), llvm::dbgs(), E, llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getStackID(), getSVECalleeSaveSlotRange(), I, llvm::MachineFrameInfo::isDeadObjectIndex(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::MachineFrameInfo::setObjectOffset(), and llvm::TargetStackID::SVEVector.
estimateRSStackSizeLimit()
static unsigned estimateRSStackSizeLimit (MachineFunction & MF) static
Look at each instruction that references stack frames and return the stack size limit beyond which some of these instructions will require a scratch register during their expansion later.
Definition at line 184 of file AArch64FrameLowering.cpp.
References llvm::AArch64FrameOffsetCannotUpdate, DefaultSafeSPDisplacement, llvm::isAArch64FrameOffsetLegal(), and MI.
Referenced by llvm::AArch64FrameLowering::determineCalleeSaves().
findScratchNonCalleeSaveRegister()
static unsigned findScratchNonCalleeSaveRegister (MachineBasicBlock * MBB) static
Definition at line 387 of file AArch64FrameLowering.cpp.
References llvm::LivePhysRegs::addLiveIns(), llvm::LivePhysRegs::addReg(), llvm::LivePhysRegs::available(), llvm::MachineFunction::front(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), MRI, Reg, and TRI.
Referenced by llvm::AArch64FrameLowering::canUseAsPrologue().
fixupCalleeSaveRestoreStackOffset()
static void fixupCalleeSaveRestoreStackOffset (MachineInstr & MI, uint64_t LocalStackSize, bool NeedsWinCFI, bool * HasWinCFI) static
Definition at line 727 of file AArch64FrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::end(), fixupSEHOpcode(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::AArch64InstrInfo::isSEHInstruction(), and llvm_unreachable.
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
fixupSEHOpcode()
static void fixupSEHOpcode (MachineBasicBlock::iterator MBBI, unsigned LocalStackSize) static
Definition at line 605 of file AArch64FrameLowering.cpp.
References llvm::MachineOperand::getImm(), llvm_unreachable, and llvm::MachineOperand::setImm().
Referenced by fixupCalleeSaveRestoreStackOffset().
getFPOffset()
static StackOffset getFPOffset (const MachineFunction & MF, int64_t ObjectOffset) static
Definition at line 1677 of file AArch64FrameLowering.cpp.
References llvm::alignTo(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::MVT::i8, and isTargetDarwin().
Referenced by llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getPrologueDeath()
static unsigned getPrologueDeath (MachineFunction & MF, unsigned Reg) static
Definition at line 1849 of file AArch64FrameLowering.cpp.
References llvm::getKillRegState(), llvm::MachineFunction::getRegInfo(), and llvm::MachineRegisterInfo::isLiveIn().
Referenced by llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
getStackOffset()
static StackOffset getStackOffset (const MachineFunction & MF, int64_t ObjectOffset) static
Definition at line 1688 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), and llvm::MVT::i8.
Referenced by llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getSVECalleeSaveSlotRange()
static bool getSVECalleeSaveSlotRange (const MachineFrameInfo & MFI, int & Min, int & Max) static
returns true if there are any SVE callee saves.
Definition at line 2503 of file AArch64FrameLowering.cpp.
References assert(), contains(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFrameInfo::isCalleeSavedInfoValid(), and llvm::max().
Referenced by determineSVEStackObjectOffsets().
getSVEStackSize()
static StackOffset getSVEStackSize (const MachineFunction & MF) static
Returns the size of the entire SVE stackframe (calleesaves + spills).
Definition at line 215 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::getStackSizeSVE(), and llvm::MVT::nxv1i8.
Referenced by llvm::AArch64FrameLowering::canUseRedZone(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), and windowsRequiresStackProbe().
InsertReturnAddressAuth()
static void InsertReturnAddressAuth (MachineFunction & MF, MachineBasicBlock & MBB) static
Definition at line 1330 of file AArch64FrameLowering.cpp.
References llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::FrameDestroy, llvm::MDNode::get(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::AArch64Subtarget::getInstrInfo(), llvm::MachineFunction::getSubtarget(), llvm::AArch64Subtarget::hasV8_3aOps(), ShouldSignReturnAddress(), ShouldSignWithAKey(), and TII.
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
InsertSEH()
static MachineBasicBlock::iterator InsertSEH (MachineBasicBlock::iterator MBBI, const TargetInstrInfo & TII, MachineInstr::MIFlag Flag) static
Definition at line 485 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getParent(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineBasicBlock::insertAfter(), LLVM_FALLTHROUGH, llvm_unreachable, Reg, and llvm::MachineInstrBuilder::setMIFlag().
Referenced by convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
invalidateRegisterPairing()
static bool invalidateRegisterPairing (unsigned Reg1, unsigned Reg2, bool UsesWinAAPCS, bool NeedsWinCFI, bool NeedsFrameRecord) static
Returns true if Reg1 and Reg2 cannot be paired using a ldp/stp instruction.
WindowsCFI requires that only consecutive registers can be paired. LR and FP need to be allocated together when the frame needs to save the frame-record. This means any other register pairing with LR is invalid.
Definition at line 1890 of file AArch64FrameLowering.cpp.
References llvm::GPR, invalidateWindowsRegisterPairing(), and llvm_unreachable.
Referenced by computeCalleeSaveRegisterPairs().
invalidateWindowsRegisterPairing()
static bool invalidateWindowsRegisterPairing (unsigned Reg1, unsigned Reg2, bool NeedsWinCFI) static
Definition at line 1867 of file AArch64FrameLowering.cpp.
Referenced by computeCalleeSaveRegisterPairs(), and invalidateRegisterPairing().
isFuncletReturnInstr()
static bool isFuncletReturnInstr (const MachineInstr & MI) static
Definition at line 1360 of file AArch64FrameLowering.cpp.
References llvm::ISD::CATCHRET, llvm::ISD::CLEANUPRET, and llvm::MachineInstr::getOpcode().
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
IsSVECalleeSave()
static bool IsSVECalleeSave (MachineBasicBlock::iterator I) static
Definition at line 844 of file AArch64FrameLowering.cpp.
References llvm::MachineInstr::FrameDestroy, and llvm::MachineInstr::FrameSetup.
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
isTargetDarwin()
static bool isTargetDarwin (const MachineFunction & MF) static
Definition at line 835 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getSubtarget().
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and getFPOffset().
isTargetWindows()
static bool isTargetWindows (const MachineFunction & MF) static
Definition at line 839 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getSubtarget().
Referenced by computeCalleeSaveRegisterPairs().
needsWinCFI()
static bool needsWinCFI (const MachineFunction & MF) static
Definition at line 829 of file AArch64FrameLowering.cpp.
References F(), llvm::MachineFunction::getFunction(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getTarget(), llvm::Function::needsUnwindTableEntry(), and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by computeCalleeSaveRegisterPairs(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
produceCompactUnwindFrame()
static bool produceCompactUnwindFrame (MachineFunction & MF) static
Definition at line 1859 of file AArch64FrameLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::AArch64Subtarget::getTargetLowering(), llvm::AArch64Subtarget::isTargetMachO(), and llvm::AArch64TargetLowering::supportSwiftError().
Referenced by computeCalleeSaveRegisterPairs(), and llvm::AArch64FrameLowering::determineCalleeSaves().
ShouldSignReturnAddress()
static bool ShouldSignReturnAddress (MachineFunction & MF) static
Definition at line 324 of file AArch64FrameLowering.cpp.
References assert(), llvm::StringRef::equals(), F(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::Attribute::getValueAsString(), llvm::Function::hasFnAttribute(), and Info.
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and InsertReturnAddressAuth().
ShouldSignWithAKey()
static bool ShouldSignWithAKey (MachineFunction & MF) static
Definition at line 818 of file AArch64FrameLowering.cpp.
References assert(), llvm::StringRef::equals_lower(), F(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), llvm::Attribute::getValueAsString(), and llvm::Function::hasFnAttribute().
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and InsertReturnAddressAuth().
STATISTIC()
STATISTIC (NumRedZoneFunctions , "Number of functions using red zone")
windowsRequiresStackProbe()
static bool windowsRequiresStackProbe (MachineFunction & MF, uint64_t StackSizeInBytes) static
Definition at line 431 of file AArch64FrameLowering.cpp.
References llvm::AArch64FrameLowering::canUseRedZone(), F(), llvm::StringRef::getAsInteger(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), getSVEStackSize(), llvm::Attribute::getValueAsString(), llvm::Function::hasFnAttribute(), and llvm::AArch64Subtarget::isTargetWindows().
Referenced by llvm::AArch64FrameLowering::determineCalleeSaves(), and llvm::AArch64FrameLowering::emitPrologue().
Variable Documentation
DefaultSafeSPDisplacement
const unsigned DefaultSafeSPDisplacement = 255 static
This is the biggest offset to the stack pointer we can encode in aarch64 instructions (without using a separate calculation and a temp register).
Note that the exception here are vector stores/loads which cannot encode any displacements (see estimateRSStackSizeLimit(), isAArch64FrameOffsetLegal()).
Definition at line 179 of file AArch64FrameLowering.cpp.
Referenced by estimateRSStackSizeLimit(), and llvm::AArch64FrameLowering::hasFP().
EnableRedZone
cl::opt<bool> EnableRedZone("aarch64-redzone", cl::desc("enable use of redzone on AArch64"), cl::init(false), cl::Hidden) static
Referenced by llvm::AArch64FrameLowering::canUseRedZone().
ReverseCSRRestoreSeq
cl::opt<bool> ReverseCSRRestoreSeq("reverse-csr-restore-seq", cl::desc("reverse the CSR restore sequence"), cl::init(false), cl::Hidden) static
Referenced by adaptForLdStOpt(), and llvm::AArch64FrameLowering::restoreCalleeSavedRegisters().