LLVM: lib/Target/AArch64/AArch64BranchTargets.cpp File Reference
AArch64BranchTargets.cpp File Reference
#include "AArch64Subtarget.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "aarch64-branch-targets"
#define AARCH64_BRANCH_TARGETS_NAME "AArch64 Branch Targets"
Functions
INITIALIZE_PASS (AArch64BranchTargets, "aarch64-branch-targets", AARCH64_BRANCH_TARGETS_NAME, false, false) void AArch64BranchTargets
Macro Definition Documentation
AARCH64_BRANCH_TARGETS_NAME
#define AARCH64_BRANCH_TARGETS_NAME "AArch64 Branch Targets"
Definition at line 29 of file AArch64BranchTargets.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-branch-targets"
Definition at line 28 of file AArch64BranchTargets.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (AArch64BranchTargets , "aarch64-branch-targets" , AARCH64_BRANCH_TARGETS_NAME , false , false)
Definition at line 47 of file AArch64BranchTargets.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::createAArch64BranchTargetsPass(), llvm::dbgs(), llvm::MachineBasicBlock::end(), F(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MDNode::get(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineBasicBlock::getName(), llvm::MachineFunction::getName(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasAddressTaken(), llvm::Function::hasFnAttribute(), llvm::GlobalValue::hasLocalLinkage(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, and TII.