LLVM: lib/Target/AArch64/AArch64ConditionOptimizer.cpp File Reference
AArch64ConditionOptimizer.cpp File Reference
#include "AArch64.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "Utils/AArch64BaseInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdlib>
#include <tuple>
Macros
#define DEBUG_TYPE "aarch64-condopt"
Functions
STATISTIC (NumConditionsAdjusted, "Number of conditions adjusted")
INITIALIZE_PASS_BEGIN (AArch64ConditionOptimizer, "aarch64-condopt", "AArch64 CondOpt Pass", false, false) INITIALIZE_PASS_END(AArch64ConditionOptimizer
static int getComplementOpc (int Opc)
static AArch64CC::CondCode getAdjustedCmp (AArch64CC::CondCode Cmp)
static bool parseCond (ArrayRef< MachineOperand > Cond, AArch64CC::CondCode &CC)
Variables
aarch64 condopt
aarch64 AArch64 CondOpt Pass
aarch64 AArch64 CondOpt false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-condopt"
Definition at line 88 of file AArch64ConditionOptimizer.cpp.
Function Documentation
getAdjustedCmp()
static AArch64CC::CondCode getAdjustedCmp (AArch64CC::CondCode Cmp) static
Definition at line 229 of file AArch64ConditionOptimizer.cpp.
References llvm::abs(), add(), llvm::MachineInstrBuilder::add(), llvm::BuildMI(), llvm::MachineInstr::eraseFromParent(), llvm::AArch64CC::GE, getComplementOpc(), llvm::MachineInstr::getDebugLoc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::AArch64CC::GT, Info, llvm::AArch64CC::LE, llvm_unreachable, llvm::AArch64CC::LT, TII, and llvm::MachineBasicBlock::updateTerminator().
getComplementOpc()
static int getComplementOpc (int Opc) static
Definition at line 217 of file AArch64ConditionOptimizer.cpp.
References llvm_unreachable.
Referenced by getAdjustedCmp().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AArch64ConditionOptimizer , "aarch64-condopt" , "AArch64 CondOpt Pass" , false , false)
parseCond()
static bool parseCond (ArrayRef< MachineOperand > Cond, AArch64CC::CondCode & CC) static
Definition at line 305 of file AArch64ConditionOptimizer.cpp.
STATISTIC()
STATISTIC (NumConditionsAdjusted , "Number of conditions adjusted")
Variable Documentation
condopt
aarch64 condopt
Definition at line 130 of file AArch64ConditionOptimizer.cpp.
false
aarch64 AArch64 CondOpt false
Definition at line 130 of file AArch64ConditionOptimizer.cpp.
Pass
aarch64 AArch64 CondOpt Pass
Definition at line 130 of file AArch64ConditionOptimizer.cpp.