LLVM: lib/Target/AMDGPU/AMDGPUAnnotateKernelFeatures.cpp File Reference
AMDGPUAnnotateKernelFeatures.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "amdgpu-annotate-kernel-features"
Functions
INITIALIZE_PASS (AMDGPUAnnotateKernelFeatures, DEBUG_TYPE, "Add AMDGPU function attributes", false, false) static bool castRequiresQueuePtr(unsigned SrcAS)
static bool castRequiresQueuePtr (const AddrSpaceCastInst *ASC)
static StringRef intrinsicToAttrName (Intrinsic::ID ID, bool &NonKernelOnly, bool &IsQueuePtr)
static bool handleAttr (Function &Parent, const Function &Callee, StringRef Name)
static void copyFeaturesToFunction (Function &Parent, const Function &Callee, bool &NeedQueuePtr)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-annotate-kernel-features"
Definition at line 39 of file AMDGPUAnnotateKernelFeatures.cpp.
Function Documentation
castRequiresQueuePtr()
static bool castRequiresQueuePtr (const AddrSpaceCastInst * ASC) static
Definition at line 92 of file AMDGPUAnnotateKernelFeatures.cpp.
References C, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::Type::getPointerAddressSpace(), llvm::AddrSpaceCastInst::getSrcAddressSpace(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T >::push_back().
copyFeaturesToFunction()
static void copyFeaturesToFunction (Function & Parent, const Function & Callee, bool & NeedQueuePtr) static
Definition at line 197 of file AMDGPUAnnotateKernelFeatures.cpp.
References handleAttr().
handleAttr()
static bool handleAttr (Function & Parent, const Function & Callee, StringRef Name) static
Definition at line 188 of file AMDGPUAnnotateKernelFeatures.cpp.
References llvm::Function::addFnAttr(), and llvm::Function::hasFnAttribute().
Referenced by copyFeaturesToFunction().
INITIALIZE_PASS()
INITIALIZE_PASS (AMDGPUAnnotateKernelFeatures , DEBUG_TYPE , "Add AMDGPU function attributes" , false , false)
Definition at line 83 of file AMDGPUAnnotateKernelFeatures.cpp.
References AMDGPUAS::LOCAL_ADDRESS, and AMDGPUAS::PRIVATE_ADDRESS.
intrinsicToAttrName()
static StringRef intrinsicToAttrName (Intrinsic::ID ID, bool & NonKernelOnly, bool & IsQueuePtr) static
Definition at line 145 of file AMDGPUAnnotateKernelFeatures.cpp.