LLVM: lib/Target/AMDGPU/AMDGPULegalizerInfo.cpp File Reference
AMDGPULegalizerInfo.cpp File Reference
This file implements the targeting of the Machinelegalizer class for AMDGPU.
#include "AMDGPU.h"
#include "AMDGPULegalizerInfo.h"
#include "AMDGPUTargetMachine.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "amdgpu-legalinfo"
Functions
static LegalityPredicate isMultiple32 (unsigned TypeIdx, unsigned MaxSize=1024)
static LegalityPredicate sizeIs (unsigned TypeIdx, unsigned Size)
static LegalityPredicate isSmallOddVector (unsigned TypeIdx)
static LegalityPredicate isWideVec16 (unsigned TypeIdx)
static LegalizeMutation oneMoreElement (unsigned TypeIdx)
static LegalizeMutation fewerEltsToSize64Vector (unsigned TypeIdx)
static LegalizeMutation moreEltsToNext32Bit (unsigned TypeIdx)
static LegalityPredicate vectorSmallerThan (unsigned TypeIdx, unsigned Size)
static LegalityPredicate vectorWiderThan (unsigned TypeIdx, unsigned Size)
static LegalityPredicate numElementsNotEven (unsigned TypeIdx)
static LegalityPredicate isRegisterType (unsigned TypeIdx)
static LegalityPredicate elementTypeIs (unsigned TypeIdx, LLT Type)
static LegalityPredicate isWideScalarTruncStore (unsigned TypeIdx)
static MachineInstrBuilder extractF64Exponent (unsigned Hi, MachineIRBuilder &B)
static MachineInstr * verifyCFIntrinsic (MachineInstr &MI, MachineRegisterInfo &MRI, MachineInstr *&Br)
static void toggleSPDenormMode (bool Enable, MachineIRBuilder &B, const GCNSubtarget &ST, AMDGPU::SIModeRegisterDefaults Mode)
Detailed Description
This file implements the targeting of the Machinelegalizer class for AMDGPU.
Todo:
This should be generated by TableGen.
Definition in file AMDGPULegalizerInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-legalinfo"
Definition at line 34 of file AMDGPULegalizerInfo.cpp.
Function Documentation
elementTypeIs()
static LegalityPredicate elementTypeIs (unsigned TypeIdx, LLT Type) static
Definition at line 149 of file AMDGPULegalizerInfo.cpp.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
extractF64Exponent()
static MachineInstrBuilder extractF64Exponent (unsigned Hi, MachineIRBuilder & B) static
Definition at line 1412 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineIRBuilder::buildSub(), and llvm::LLT::scalar().
Referenced by llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc().
fewerEltsToSize64Vector()
static LegalizeMutation fewerEltsToSize64Vector (unsigned TypeIdx) static
Definition at line 83 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::LLT::scalarOrVector(), and Size.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
isMultiple32()
static LegalityPredicate isMultiple32 (unsigned TypeIdx, unsigned MaxSize = 1024) static
Definition at line 42 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getScalarType(), and llvm::LLT::getSizeInBits().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
isRegisterType()
static LegalityPredicate isRegisterType (unsigned TypeIdx) static
Definition at line 135 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), and llvm::LLT::isVector().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
isSmallOddVector()
static LegalityPredicate isSmallOddVector (unsigned TypeIdx) static
Definition at line 57 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), and llvm::LLT::isVector().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
isWideScalarTruncStore()
static LegalityPredicate isWideScalarTruncStore (unsigned TypeIdx) static
Definition at line 155 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getSizeInBits(), and llvm::LLT::isVector().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
isWideVec16()
static LegalityPredicate isWideVec16 (unsigned TypeIdx) static
Definition at line 67 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getNumElements(), llvm::LLT::getScalarType(), and llvm::LLT::getSizeInBits().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
moreEltsToNext32Bit()
static LegalizeMutation moreEltsToNext32Bit (unsigned TypeIdx) static
Definition at line 96 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), Size, and llvm::LLT::vector().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
numElementsNotEven()
static LegalityPredicate numElementsNotEven (unsigned TypeIdx) static
Definition at line 126 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getNumElements(), and llvm::LLT::isVector().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
oneMoreElement()
static LegalizeMutation oneMoreElement (unsigned TypeIdx) static
Definition at line 75 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getNumElements(), and llvm::LLT::vector().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
sizeIs()
static LegalityPredicate sizeIs (unsigned TypeIdx, unsigned Size) static
Definition at line 51 of file AMDGPULegalizerInfo.cpp.
References Size.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
toggleSPDenormMode()
static void toggleSPDenormMode (bool Enable, MachineIRBuilder & B, const GCNSubtarget & ST, AMDGPU::SIModeRegisterDefaults Mode) static
Definition at line 2032 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineIRBuilder::buildInstr(), FP_DENORM_FLUSH_IN_FLUSH_OUT, FP_DENORM_FLUSH_NONE, llvm::GCNSubtarget::hasDenormModeInst(), llvm::AMDGPU::Hwreg::ID_MODE, llvm::AMDGPU::Hwreg::OFFSET_SHIFT_, and llvm::AMDGPU::Hwreg::WIDTH_M1_SHIFT_.
Referenced by llvm::AMDGPULegalizerInfo::legalizeFDIV32().
vectorSmallerThan()
static LegalityPredicate vectorSmallerThan (unsigned TypeIdx, unsigned Size) static
Definition at line 112 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), and Size.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
vectorWiderThan()
static LegalityPredicate vectorWiderThan (unsigned TypeIdx, unsigned Size) static
Definition at line 119 of file AMDGPULegalizerInfo.cpp.
References llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), and Size.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
verifyCFIntrinsic()
static MachineInstr* verifyCFIntrinsic (MachineInstr & MI, MachineRegisterInfo & MRI, MachineInstr *& Br) static
Definition at line 1807 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineBasicBlock::end(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MachineRegisterInfo::use_instr_nodbg_begin(), and UseMI.
Referenced by llvm::AMDGPULegalizerInfo::legalizeIntrinsic().