LLVM: lib/Target/AMDGPU/AMDGPULibFunc.cpp File Reference
AMDGPULibFunc.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPULibFunc.h"
#include <llvm/ADT/SmallString.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringSwitch.h>
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueSymbolTable.h"
#include <llvm/Support/raw_ostream.h>
#include <string>
Enumerations
enum EManglingParam
Functions
static int parseVecSize (StringRef &mangledName)
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef &mangledName)
static const char * getItaniumTypeName (AMDGPULibFunc::EType T)
static Type * getIntrinsicParamType (LLVMContext &C, const AMDGPULibFunc::Param &P, bool useAddrSpace)
Enumeration Type Documentation
EManglingParam
enum EManglingParam
Definition at line 30 of file AMDGPULibFunc.cpp.
Function Documentation
getIntrinsicParamType()
static Type* getIntrinsicParamType (LLVMContext & C, const AMDGPULibFunc::Param & P, bool useAddrSpace) static
Definition at line 872 of file AMDGPULibFunc.cpp.
References llvm::AMDGPULibFuncBase::ADDR_SPACE, llvm::AMDGPULibFuncBase::BYVALUE, llvm::StructType::create(), llvm::AMDGPULibFuncBase::EVENT, llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, llvm::VectorType::get(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getHalfTy(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::Type::getPointerTo(), llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, llvm::AMDGPULibFuncBase::IMG1D, llvm::AMDGPULibFuncBase::IMG1DA, llvm::AMDGPULibFuncBase::IMG1DB, llvm::AMDGPULibFuncBase::IMG2D, llvm::AMDGPULibFuncBase::IMG2DA, llvm::AMDGPULibFuncBase::IMG3D, llvm_unreachable, llvm::AMDGPULibFuncBase::SAMPLER, llvm::T, llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, and llvm::AMDGPULibFuncBase::U8.
Referenced by llvm::AMDGPUMangledLibFunc::getFunctionType().
getItaniumTypeName()
static const char* getItaniumTypeName (AMDGPULibFunc::EType T) static
Definition at line 727 of file AMDGPULibFunc.cpp.
References llvm::AMDGPULibFuncBase::CONST, llvm::AMDGPULibFuncBase::EVENT, llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, FuncId, llvm::AMDGPULibFuncBase::getAddrSpaceFromEPtrKind(), I, llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, llvm::AMDGPULibFuncBase::IMG1D, llvm::AMDGPULibFuncBase::IMG1DA, llvm::AMDGPULibFuncBase::IMG1DB, llvm::AMDGPULibFuncBase::IMG2D, llvm::AMDGPULibFuncBase::IMG2DA, llvm::AMDGPULibFuncBase::IMG3D, llvm_unreachable, Name, P, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::AMDGPULibFuncBase::SAMPLER, llvm::SmallVectorBase::size(), llvm::StringRef::size(), llvm::raw_svector_ostream::str(), llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, llvm::AMDGPULibFuncBase::U8, and llvm::AMDGPULibFuncBase::VOLATILE.
parseNamePrefix()
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef & mangledName) static
Definition at line 540 of file AMDGPULibFunc.cpp.
References llvm::array_lengthof(), llvm::AMDGPULibFuncBase::BYVALUE, llvm::StringSwitch< T, R >::Case(), llvm::AMDGPULibFuncBase::CONST, llvm::StringSwitch< T, R >::Default(), llvm::AMDGPULibFuncBase::DUMMY, llvm::StringRef::empty(), llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, llvm::StringRef::front(), FuncId, llvm::AMDGPULibFuncBase::getEPtrKindFromAddrSpace(), llvm::AMDGPULibFuncBase::HALF, llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, if(), llvm::AMDGPULibFuncBase::IMG1D, llvm::AMDGPULibFuncBase::IMG1DA, llvm::AMDGPULibFuncBase::IMG1DB, llvm::AMDGPULibFuncBase::IMG2D, llvm::AMDGPULibFuncBase::IMG2DA, llvm::AMDGPULibFuncBase::IMG3D, llvm::StringMap< ValueTy, AllocatorTy >::insert(), llvm::isDigit(), llvm::StringMap< ValueTy, AllocatorTy >::lookup(), llvm::AMDGPULibFuncBase::NATIVE, llvm::AMDGPULibFuncBase::NOPFX, P, parseVecSize(), llvm::StringRef::split(), llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, llvm::AMDGPULibFuncBase::U8, and llvm::AMDGPULibFuncBase::VOLATILE.
Referenced by llvm::AMDGPUMangledLibFunc::parseFuncName().
parseVecSize()
static int parseVecSize (StringRef & mangledName) static
Definition at line 529 of file AMDGPULibFunc.cpp.
Referenced by parseNamePrefix().