LLVM: lib/Target/AMDGPU/AMDGPUAnnotateUniformValues.cpp File Reference
AMDGPUAnnotateUniformValues.cpp File Reference
This pass adds amdgpu.uniform metadata to IR values so this information can be used during instruction selection.
#include "AMDGPU.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryDependenceAnalysis.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "amdgpu-annotate-uniform"
Functions
INITIALIZE_PASS_BEGIN (AMDGPUAnnotateUniformValues, DEBUG_TYPE, "Add AMDGPU uniform metadata", false, false) INITIALIZE_PASS_END(AMDGPUAnnotateUniformValues
static void setUniformMetadata (Instruction *I)
static void setNoClobberMetadata (Instruction *I)
static void DFS (BasicBlock *Root, SetVector< BasicBlock *> &Set)
Variables
DEBUG_TYPE
Add AMDGPU uniform metadata
Add AMDGPU uniform false
Detailed Description
This pass adds amdgpu.uniform metadata to IR values so this information can be used during instruction selection.
Definition in file AMDGPUAnnotateUniformValues.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-annotate-uniform"
Definition at line 26 of file AMDGPUAnnotateUniformValues.cpp.
Function Documentation
DFS()
static void DFS (BasicBlock * Root, SetVector< BasicBlock *> & Set) static
Definition at line 80 of file AMDGPUAnnotateUniformValues.cpp.
References I, llvm::SetVector< T, Vector, Set >::insert(), llvm::SPII::Load, and llvm::predecessors().
Referenced by llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::LoopInfoBase< BasicBlock, Loop >::analyze(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::SchedDFSResult::compute(), llvm::DataDependenceGraph::DataDependenceGraph(), llvm::Loop::dumpVerbose(), GetGlobalTypeString(), getInnermostLoopFor(), llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeAttributes(), llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeLabel(), INITIALIZE_PASS(), llvm::ScheduleDAGTopologicalSort::IsReachable(), llvm::possiblyDemandedEltsInMask(), llvm::VPRecipeBuilder::tryToCreateRecipe(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUAnnotateUniformValues , DEBUG_TYPE , "Add AMDGPU uniform metadata" , false , false)
setNoClobberMetadata()
static void setNoClobberMetadata (Instruction * I) static
Definition at line 76 of file AMDGPUAnnotateUniformValues.cpp.
References llvm::MDNode::get(), llvm::Value::getContext(), and llvm::Instruction::setMetadata().
setUniformMetadata()
static void setUniformMetadata (Instruction * I) static
Definition at line 73 of file AMDGPUAnnotateUniformValues.cpp.
References llvm::MDNode::get(), and I.
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 68 of file AMDGPUAnnotateUniformValues.cpp.
false
Add AMDGPU uniform false
Definition at line 68 of file AMDGPUAnnotateUniformValues.cpp.
metadata
Add AMDGPU uniform metadata
Definition at line 68 of file AMDGPUAnnotateUniformValues.cpp.