LLVM: lib/Target/AMDGPU/Utils/AMDGPUPALMetadata.cpp File Reference
AMDGPUPALMetadata.cpp File Reference
This class has methods called by AMDGPUAsmPrinter to accumulate and print the PAL metadata.
#include "AMDGPUPALMetadata.h"
#include "AMDGPU.h"
#include "AMDGPUAsmPrinter.h"
#include "MCTargetDesc/AMDGPUTargetStreamer.h"
#include "SIDefines.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/AMDGPUMetadata.h"
#include "llvm/Support/EndianStream.h"
Functions
static unsigned getRsrc1Reg (CallingConv::ID CC)
static unsigned getScratchSizeKey (CallingConv::ID CC)
static const char * getRegisterName (unsigned RegNum)
static const char * getStageName (CallingConv::ID CC)
Detailed Description
This class has methods called by AMDGPUAsmPrinter to accumulate and print the PAL metadata.
Definition in file AMDGPUPALMetadata.cpp.
Function Documentation
getRegisterName()
static const char* getRegisterName (unsigned RegNum) static
Definition at line 263 of file AMDGPUPALMetadata.cpp.
References Name, llvm::AMDGPU::PALMD::R_2C0A_SPI_SHADER_PGM_RSRC1_PS, llvm::AMDGPU::PALMD::R_2C4A_SPI_SHADER_PGM_RSRC1_VS, llvm::AMDGPU::PALMD::R_2C8A_SPI_SHADER_PGM_RSRC1_GS, llvm::AMDGPU::PALMD::R_2CCA_SPI_SHADER_PGM_RSRC1_ES, llvm::AMDGPU::PALMD::R_2D0A_SPI_SHADER_PGM_RSRC1_HS, llvm::AMDGPU::PALMD::R_2D4A_SPI_SHADER_PGM_RSRC1_LS, llvm::AMDGPU::PALMD::R_2E00_COMPUTE_DISPATCH_INITIATOR, llvm::AMDGPU::PALMD::R_2E12_COMPUTE_PGM_RSRC1, llvm::AMDGPU::PALMD::R_A1B3_SPI_PS_INPUT_ENA, llvm::AMDGPU::PALMD::R_A1B4_SPI_PS_INPUT_ADDR, llvm::AMDGPU::PALMD::R_A1B6_SPI_PS_IN_CONTROL, and llvm::AMDGPU::PALMD::R_A2D5_VGT_SHADER_STAGES_EN.
Referenced by llvm::AMDGPUPALMetadata::toString().
getRsrc1Reg()
static unsigned getRsrc1Reg (CallingConv::ID CC) static
Definition at line 94 of file AMDGPUPALMetadata.cpp.
References llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::AMDGPU::PALMD::R_2C0A_SPI_SHADER_PGM_RSRC1_PS, llvm::AMDGPU::PALMD::R_2C4A_SPI_SHADER_PGM_RSRC1_VS, llvm::AMDGPU::PALMD::R_2C8A_SPI_SHADER_PGM_RSRC1_GS, llvm::AMDGPU::PALMD::R_2CCA_SPI_SHADER_PGM_RSRC1_ES, llvm::AMDGPU::PALMD::R_2D0A_SPI_SHADER_PGM_RSRC1_HS, llvm::AMDGPU::PALMD::R_2D4A_SPI_SHADER_PGM_RSRC1_LS, and llvm::AMDGPU::PALMD::R_2E12_COMPUTE_PGM_RSRC1.
Referenced by llvm::AMDGPUPALMetadata::setRsrc1(), and llvm::AMDGPUPALMetadata::setRsrc2().
getScratchSizeKey()
static unsigned getScratchSizeKey (CallingConv::ID CC) static
Definition at line 116 of file AMDGPUPALMetadata.cpp.
References llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::AMDGPU::PALMD::CS_SCRATCH_SIZE, llvm::AMDGPU::PALMD::ES_SCRATCH_SIZE, llvm::AMDGPU::PALMD::GS_SCRATCH_SIZE, llvm::AMDGPU::PALMD::HS_SCRATCH_SIZE, llvm::AMDGPU::PALMD::LS_SCRATCH_SIZE, llvm::AMDGPU::PALMD::PS_SCRATCH_SIZE, and llvm::AMDGPU::PALMD::VS_SCRATCH_SIZE.
Referenced by llvm::AMDGPUPALMetadata::setNumUsedSgprs(), llvm::AMDGPUPALMetadata::setNumUsedVgprs(), and llvm::AMDGPUPALMetadata::setScratchSize().
getStageName()
static const char* getStageName (CallingConv::ID CC) static
Definition at line 672 of file AMDGPUPALMetadata.cpp.
References llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::msgpack::DocNode::getArray(), and llvm::msgpack::DocNode::getMap().