LLVM: lib/Target/AMDGPU/MCTargetDesc/AMDGPUAsmBackend.cpp File Reference
AMDGPUAsmBackend.cpp File Reference
#include "MCTargetDesc/AMDGPUFixupKinds.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/TargetRegistry.h"
#include "Utils/AMDGPUBaseInfo.h"
Functions
static unsigned getFixupKindNumBytes (unsigned Kind)
static uint64_t adjustFixupValue (const MCFixup &Fixup, uint64_t Value, MCContext *Ctx)
Function Documentation
adjustFixupValue()
static uint64_t adjustFixupValue (const MCFixup & Fixup, uint64_t Value, MCContext * Ctx) static
Definition at line 108 of file AMDGPUAsmBackend.cpp.
References llvm::Triple::amdgcn, llvm::Triple::AMDHSA, llvm::Triple::AMDPAL, llvm::HexStyle::Asm, assert(), llvm::createAMDGPUELFObjectWriter(), llvm::Data, llvm::ELF::ELFOSABI_AMDGPU_HSA, llvm::ELF::ELFOSABI_AMDGPU_MESA3D, llvm::ELF::ELFOSABI_AMDGPU_PAL, llvm::ELF::ELFOSABI_NONE, llvm::FirstTargetFixupKind, llvm::AMDGPU::fixup_si_sopp_br, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_PCRel_4, llvm::FK_SecRel_4, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::Triple::getArch(), llvm::MCAssembler::getContext(), llvm::MCAsmBackend::getFixupKindInfo(), getFixupKindNumBytes(), llvm::MCFixup::getKind(), llvm::MCFixup::getLoc(), llvm::MCFixup::getOffset(), llvm::Triple::getOS(), llvm::MCFixup::getTargetKind(), I, Info, llvm::isInt< 16 >(), llvm_unreachable, llvm::Triple::Mesa3D, llvm::AMDGPU::NumTargetFixupKinds, llvm::MCContext::reportError(), llvm::ArrayRef< T >::size(), llvm::MCFixupKindInfo::TargetOffset, llvm::TT, and llvm::raw_ostream::write_zeros().
getFixupKindNumBytes()
static unsigned getFixupKindNumBytes (unsigned Kind) static
Definition at line 86 of file AMDGPUAsmBackend.cpp.
References llvm::AMDGPU::fixup_si_sopp_br, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_PCRel_4, llvm::FK_SecRel_1, llvm::FK_SecRel_2, llvm::FK_SecRel_4, llvm::FK_SecRel_8, and llvm_unreachable.
Referenced by adjustFixupValue().