LLVM: lib/Target/AMDGPU/AMDGPUISelDAGToDAG.cpp File Reference
AMDGPUISelDAGToDAG.cpp File Reference
Defines an instruction selector for the AMDGPU target.
#include "AMDGPU.h"
#include "AMDGPUArgumentUsageInfo.h"
#include "AMDGPUISelLowering.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPUPerfHintAnalysis.h"
#include "AMDGPURegisterInfo.h"
#include "AMDGPUSubtarget.h"
#include "AMDGPUTargetMachine.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "SIISelLowering.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/InitializePasses.h"
#include "llvm/IR/Instruction.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include <cassert>
#include <cstdint>
#include <new>
#include <vector>
#include "AMDGPUGenDAGISel.inc"
#include "R600GenDAGISel.inc"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "isel"
Functions
INITIALIZE_PASS_BEGIN (AMDGPUDAGToDAGISel, "amdgpu-isel", "AMDGPU DAG->DAG Pattern Instruction Selection", false, false) INITIALIZE_PASS_END(AMDGPUDAGToDAGISel
static unsigned selectSGPRVectorRegClassID (unsigned NumVectorElts)
static bool isStackPtrRelative (const MachinePointerInfo &PtrInfo)
static MemSDNode * findMemSDNode (SDNode *N)
static unsigned gwsIntrinToOpcode (unsigned IntrID)
Variables
amdgpu isel
amdgpu AMDGPU DAG DAG Pattern Instruction Selection
amdgpu AMDGPU DAG DAG Pattern Instruction false
Detailed Description
Defines an instruction selector for the AMDGPU target.
Definition in file AMDGPUISelDAGToDAG.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "isel"
Definition at line 58 of file AMDGPUISelDAGToDAG.cpp.
Function Documentation
findMemSDNode()
static MemSDNode* findMemSDNode (SDNode * N) static
Definition at line 1637 of file AMDGPUISelDAGToDAG.cpp.
References llvm::MCID::Add, llvm::ISD::AND, assert(), B, llvm::ISD::BRCOND, C, llvm::countPopulation(), llvm::dyn_cast(), AMDGPUAS::FLAT_ADDRESS, llvm::SIMachineFunctionInfo::get32BitAddressHighBits(), llvm::MemSDNode::getAddressSpace(), llvm::SDNode::getFlags(), llvm::MachineFunction::getInfo(), llvm::SDValue::getNode(), llvm::SIInstrInfo::getNumFlatOffsetBits(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::AMDGPU::getSMRDEncodedOffset(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNodeFlags::hasNoUnsignedWrap(), llvm::SDNode::hasOneUse(), llvm::Hi_32(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, Info, llvm::SIInstrInfo::isLegalFLATOffset(), llvm::AMDGPU::isLegalSMRDImmOffset(), llvm::isMask_32(), llvm::isUInt< 32 >(), llvm_unreachable, llvm::Lo_32(), llvm::BitmaskEnumDetail::Mask(), N, llvm::SDNode::op_values(), llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, Signed, llvm::SignExtend64(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::AMDGPUTargetLowering::stripBitcast(), and TII.
gwsIntrinToOpcode()
static unsigned gwsIntrinToOpcode (unsigned IntrID) static
Definition at line 2253 of file AMDGPUISelDAGToDAG.cpp.
References llvm::SISrcMods::ABS, llvm::Triple::amdgcn, assert(), llvm::ISD::BUILD_VECTOR, C, llvm::TargetInstrInfo::CommuteAnyOperandIndex, AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, E, llvm::MVT::f16, llvm::MVT::f32, llvm::ISD::FABS, llvm::SIInstrInfo::findCommutedOpIndices(), llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::SDValue::getConstantOperandVal(), llvm::SDNode::getMachineOpcode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::MCInstrDesc::getNumDefs(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDNode::getVTList(), AMDGPUAS::GLOBAL_ADDRESS, llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i32, llvm::tgtok::In, llvm::MCInstrDesc::isCommutable(), llvm::SDNode::isDivergent(), llvm::SDNode::isMachineOpcode(), llvm::SDValue::isUndef(), llvm_unreachable, llvm::MipsISD::Lo, Lowering, N, llvm::SISrcMods::NEG, llvm::SISrcMods::NEG_HI, llvm::SISrcMods::OP_SEL_0, llvm::SISrcMods::OP_SEL_1, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), and llvm::SIInstrFlags::WQM.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUDAGToDAGISel , "amdgpu-isel" , "AMDGPU DAG->DAG Pattern Instruction Selection" , false , false)
isStackPtrRelative()
static bool isStackPtrRelative (const MachinePointerInfo & PtrInfo) static
Definition at line 1472 of file AMDGPUISelDAGToDAG.cpp.
References llvm::SITargetLowering::buildRSRC(), llvm::PointerUnion< PTs >::dyn_cast(), llvm::dyn_cast(), llvm::APInt::getAllOnesValue(), llvm::SIInstrInfo::getDefaultRsrcDataFormat(), llvm::MachineFunction::getInfo(), llvm::SDValue::getOperand(), llvm::SIMachineFunctionInfo::getScratchRSrcReg(), llvm::SIMachineFunctionInfo::getScratchWaveOffsetReg(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::ConstantSDNode::getZExtValue(), llvm::APInt::getZExtValue(), llvm::MVT::i16, llvm::MVT::i32, Info, llvm::SIInstrInfo::isLegalMUBUFImmOffset(), llvm::PseudoSourceValue::isStack(), Lowering, TII, llvm::MachinePointerInfo::V, and llvm::MVT::v4i32.
selectSGPRVectorRegClassID()
static unsigned selectSGPRVectorRegClassID (unsigned NumVectorElts) static
Definition at line 658 of file AMDGPUISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDCARRY, llvm::ISD::ADDE, llvm::ISD::AND, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::AMDGPUISD::ATOMIC_CMP_SWAP, llvm::AMDGPUISD::ATOMIC_DEC, llvm::AMDGPUISD::ATOMIC_INC, llvm::ISD::ATOMIC_LOAD_FADD, llvm::AMDGPUISD::ATOMIC_LOAD_FMAX, llvm::AMDGPUISD::ATOMIC_LOAD_FMIN, llvm::AMDGPUISD::BFE_I32, llvm::AMDGPUISD::BFE_U32, llvm::EVT::bitsEq(), llvm::ISD::BRCOND, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, C, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::CopyToReg, llvm::AMDGPUISD::CVT_PK_I16_I32, llvm::AMDGPUISD::CVT_PK_U16_U32, llvm::AMDGPUISD::CVT_PKNORM_I16_F32, llvm::AMDGPUISD::CVT_PKNORM_U16_F32, llvm::AMDGPUISD::CVT_PKRTZ_F16_F32, llvm::AMDGPUISD::DIV_FMAS, llvm::AMDGPUISD::DIV_SCALE, llvm::AMDGPUISD::DWORDADDR, llvm::dyn_cast(), llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FMA, llvm::AMDGPUISD::FMA_W_CHAIN, llvm::ISD::FMAD, llvm::AMDGPUISD::FMUL_W_CHAIN, llvm::Instruction::getMetadata(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::GCNSubtarget::getRegisterInfo(), llvm::EVT::getScalarSizeInBits(), llvm::ConstantSDNode::getSExtValue(), llvm::EVT::getSizeInBits(), llvm::AMDGPURegisterInfo::getSubRegFromChannel(), llvm::BasicBlock::getTerminator(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SIRegisterInfo::getVCC(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SDNode::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::SDNode::isDivergent(), llvm::SIInstrInfo::isLegalMUBUFImmOffset(), llvm::SDNode::isMachineOpcode(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::isUInt< 8 >(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm_unreachable, llvm::ISD::LOAD, Lowering, llvm::AMDGPUISD::MAD_I64_I32, llvm::AMDGPUISD::MAD_U64_U32, N, llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MCID::RegSequence, llvm::ISD::SCALAR_TO_VECTOR, llvm::MCID::Select, llvm::SDNode::setNodeId(), llvm::ISD::SIGN_EXTEND_INREG, Signed, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBCARRY, llvm::ISD::SUBE, TRI, llvm::ISD::UADDO, llvm::ISD::USUBO, llvm::MVT::v2f16, llvm::MVT::v2i16, llvm::MVT::v2i32, and llvm::SITargetLowering::wrapAddr64Rsrc().
Variable Documentation
false
amdgpu AMDGPU DAG DAG Pattern Instruction false
Definition at line 386 of file AMDGPUISelDAGToDAG.cpp.
isel
amdgpu isel
Definition at line 386 of file AMDGPUISelDAGToDAG.cpp.
Selection
amdgpu AMDGPU DAG DAG Pattern Instruction Selection
Definition at line 386 of file AMDGPUISelDAGToDAG.cpp.
Referenced by llvm::MCContext::getCOFFSection(), llvm::MCContext::getELFSection(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::MCSectionCOFF::getSelection(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().