LLVM: lib/Target/AMDGPU/AMDGPULowerIntrinsics.cpp File Reference
AMDGPULowerIntrinsics.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/LowerMemIntrinsics.h"
Macros
#define DEBUG_TYPE "amdgpu-lower-intrinsics"
Functions
INITIALIZE_PASS (AMDGPULowerIntrinsics, DEBUG_TYPE, "Lower intrinsics", false, false) static bool shouldExpandOperationWithSize(Value *Size)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-lower-intrinsics"
Definition at line 19 of file AMDGPULowerIntrinsics.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (AMDGPULowerIntrinsics , DEBUG_TYPE , "Lower intrinsics" , false , false)
Definition at line 53 of file AMDGPULowerIntrinsics.cpp.
References llvm::dyn_cast(), E, llvm::expandMemCpyAsLoop(), llvm::expandMemMoveAsLoop(), llvm::expandMemSetAsLoop(), F(), llvm::AMDGPUSubtarget::get(), llvm::Function::getIntrinsicID(), llvm::GlobalValue::getParent(), llvm::ConstantInt::getZExtValue(), I, llvm::GlobalValue::isDeclaration(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), Size, llvm::SystemZISD::TM, llvm::Value::user_begin(), llvm::Value::user_end(), and llvm::Value::users().