LLVM: lib/Target/AMDGPU/AMDGPUCodeGenPrepare.cpp File Reference
AMDGPUCodeGenPrepare.cpp File Reference
This pass does misc.
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "AMDGPUTargetMachine.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include <cassert>
#include <iterator>
Macros
#define DEBUG_TYPE "amdgpu-codegenprepare"
Functions
static bool promotedOpIsNSW (const Instruction &I)
static bool promotedOpIsNUW (const Instruction &I)
static void extractValues (IRBuilder<> &Builder, SmallVectorImpl< Value *> &Values, Value *V)
static Value * insertValues (IRBuilder<> &Builder, Type *Ty, SmallVectorImpl< Value *> &Values)
static bool shouldKeepFDivF32 (Value *Num, bool UnsafeDiv, bool HasDenormals)
static bool hasUnsafeFPMath (const Function &F)
static std::pair< Value *, Value * > getMul64 (IRBuilder<> &Builder, Value *LHS, Value *RHS)
static Value * getMulHu (IRBuilder<> &Builder, Value *LHS, Value *RHS)
INITIALIZE_PASS_BEGIN (AMDGPUCodeGenPrepare, DEBUG_TYPE, "AMDGPU IR optimizations", false, false) INITIALIZE_PASS_END(AMDGPUCodeGenPrepare
Variables
DEBUG_TYPE
AMDGPU IR optimizations
AMDGPU IR false
Detailed Description
This pass does misc.
AMDGPU optimizations on IR before instruction selection.
Definition in file AMDGPUCodeGenPrepare.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-codegenprepare"
Definition at line 47 of file AMDGPUCodeGenPrepare.cpp.
Referenced by getMulHu().
Function Documentation
extractValues()
static void extractValues (IRBuilder<> & Builder, SmallVectorImpl< Value *> & Values, Value * V) static
Definition at line 437 of file AMDGPUCodeGenPrepare.cpp.
References llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::dyn_cast(), E, llvm::SequentialType::getNumElements(), llvm::Value::getType(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by insertValues().
getMul64()
static std::pair<Value*, Value*> getMul64 (IRBuilder<> & Builder, Value * LHS, Value * RHS) static
Definition at line 616 of file AMDGPUCodeGenPrepare.cpp.
References llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt64Ty(), llvm::MipsISD::Hi, and llvm::MipsISD::Lo.
Referenced by getMulHu().
getMulHu()
static Value* getMulHu (IRBuilder<> & Builder, Value * LHS, Value * RHS) static
Definition at line 630 of file AMDGPUCodeGenPrepare.cpp.
References assert(), llvm::BitsToFloat(), llvm::ComputeNumSignBits(), AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::Instruction::copyFastMathFlags(), llvm::Instruction::copyMetadata(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateFCmpOGE(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFNeg(), llvm::IRBuilder< T, Inserter >::CreateFPToSI(), llvm::IRBuilder< T, Inserter >::CreateFPToUI(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpUGE(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::IRBuilder< T, Inserter >::CreateSIToFP(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::IRBuilder< T, Inserter >::CreateUIToFP(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::IRBuilder< T, Inserter >::CreateZExt(), DEBUG_TYPE, E, llvm::Instruction::eraseFromParent(), F(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::ConstantAsMetadata::get(), llvm::PointerType::get(), llvm::MDNode::get(), llvm::UndefValue::get(), llvm::Instruction::getDebugLoc(), llvm::IRBuilderBase::getFastMathFlags(), llvm::IRBuilderBase::getFloatTy(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getIntNTy(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getMetadata(), getMul64(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::LoadInst::getPointerAddressSpace(), llvm::LoadInst::getPointerOperand(), llvm::Type::getScalarSizeInBits(), llvm::TargetMachine::getSubtarget(), llvm::Value::getType(), llvm::ConstantInt::getValue(), hasUnsafeFPMath(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::Type::isIntegerTy(), llvm::APInt::isNullValue(), LowAndHigh, llvm::Lower, llvm::Mod, N, llvm::AMDGPUISD::RCP, llvm::Value::replaceAllUsesWith(), runOnFunction(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::FastMathFlags::setFast(), llvm::IRBuilderBase::setFastMathFlags(), llvm::Instruction::setMetadata(), llvm::ARM_MB::ST, llvm::SystemZISD::TM, and llvm::APInt::zext().
hasUnsafeFPMath()
static bool hasUnsafeFPMath (const Function & F) static
Definition at line 611 of file AMDGPUCodeGenPrepare.cpp.
References llvm::Function::getFnAttribute(), and llvm::Attribute::getValueAsString().
Referenced by getMulHu().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUCodeGenPrepare , DEBUG_TYPE , "AMDGPU IR optimizations" , false , false)
Referenced by getMulHu().
insertValues()
static Value* insertValues (IRBuilder<> & Builder, Type * Ty, SmallVectorImpl< Value *> & Values) static
Definition at line 449 of file AMDGPUCodeGenPrepare.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), E, llvm::Instruction::eraseFromParent(), extractValues(), llvm::UndefValue::get(), llvm::Instruction::getDebugLoc(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getInt32Ty(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), I, isI24(), isU24(), llvm::Mod, llvm::Intrinsic::not_intrinsic, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::IRBuilderBase::SetCurrentDebugLocation(), Size, llvm::SmallVectorBase::size(), llvm::ARM_MB::ST, and llvm::Value::takeName().
promotedOpIsNSW()
static bool promotedOpIsNSW (const Instruction & I) static
Definition at line 248 of file AMDGPUCodeGenPrepare.cpp.
References llvm::MCID::Add, llvm::Instruction::getOpcode(), and llvm::Instruction::hasNoUnsignedWrap().
Referenced by promotedOpIsNUW().
promotedOpIsNUW()
static bool promotedOpIsNUW (const Instruction & I) static
Definition at line 262 of file AMDGPUCodeGenPrepare.cpp.
References llvm::MCID::Add, assert(), llvm::computeKnownBits(), llvm::ComputeNumSignBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::Instruction::eraseFromParent(), llvm::DataLayout::getABITypeAlignment(), llvm::LoadInst::getAlignment(), llvm::Instruction::getDebugLoc(), llvm::Intrinsic::getDeclaration(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getOpcode(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::Instruction::hasNoUnsignedWrap(), isI24(), llvm::CmpInst::isSigned(), llvm::LoadInst::isSimple(), isU24(), llvm::Mod, promotedOpIsNSW(), llvm::Value::replaceAllUsesWith(), and llvm::IRBuilderBase::SetCurrentDebugLocation().
shouldKeepFDivF32()
static bool shouldKeepFDivF32 (Value * Num, bool UnsafeDiv, bool HasDenormals) static
Definition at line 528 of file AMDGPUCodeGenPrepare.cpp.
References llvm::FastMathFlags::allowReciprocal(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::dyn_cast(), E, llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::Instruction::getDebugLoc(), llvm::Intrinsic::getDeclaration(), llvm::FPMathOperator::getFastMathFlags(), llvm::FPMathOperator::getFPAccuracy(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getMetadata(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Type::getScalarType(), llvm::Value::getType(), I, llvm::ConstantFP::isExactlyValue(), llvm::FastMathFlags::isFast(), llvm::Type::isFloatTy(), llvm::Mod, llvm::Value::replaceAllUsesWith(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::setFastMathFlags(), and llvm::Value::takeName().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 1056 of file AMDGPUCodeGenPrepare.cpp.
false
AMDGPU IR false
Definition at line 1056 of file AMDGPUCodeGenPrepare.cpp.
optimizations
AMDGPU IR optimizations
Definition at line 1056 of file AMDGPUCodeGenPrepare.cpp.