LLVM: lib/Target/AMDGPU/AMDGPUUnifyDivergentExitNodes.cpp File Reference
AMDGPUUnifyDivergentExitNodes.cpp File Reference
#include "AMDGPU.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/Analysis/PostDominators.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "amdgpu-unify-divergent-exit-nodes"
Functions
INITIALIZE_PASS_BEGIN (AMDGPUUnifyDivergentExitNodes, DEBUG_TYPE, "Unify divergent function exit nodes", false, false) INITIALIZE_PASS_END(AMDGPUUnifyDivergentExitNodes
static bool isUniformlyReached (const LegacyDivergenceAnalysis &DA, BasicBlock &BB)
static void removeDoneExport (Function &F)
static BasicBlock * unifyReturnBlockSet (Function &F, ArrayRef< BasicBlock *> ReturningBlocks, bool InsertExport, const TargetTransformInfo &TTI, StringRef Name)
Variables
DEBUG_TYPE
Unify divergent function exit nodes
Unify divergent function exit false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-unify-divergent-exit-nodes"
Definition at line 48 of file AMDGPUUnifyDivergentExitNodes.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUUnifyDivergentExitNodes , DEBUG_TYPE , "Unify divergent function exit nodes" , false , false)
isUniformlyReached()
static bool isUniformlyReached (const LegacyDivergenceAnalysis & DA, BasicBlock & BB) static
Returns
true if BB is reachable through only uniform branches. XXX - Is there a more efficient way to find this?
Definition at line 99 of file AMDGPUUnifyDivergentExitNodes.cpp.
References llvm::SmallVectorBase::empty(), llvm::BasicBlock::getTerminator(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::LegacyDivergenceAnalysis::isUniform(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by unifyReturnBlockSet().
removeDoneExport()
static void removeDoneExport (Function & F) static
Definition at line 121 of file AMDGPUUnifyDivergentExitNodes.cpp.
References llvm::Function::getContext(), llvm::ConstantInt::getFalse(), and I.
Referenced by unifyReturnBlockSet().
unifyReturnBlockSet()
static BasicBlock* unifyReturnBlockSet (Function & F, ArrayRef< BasicBlock *> ReturningBlocks, bool InsertExport, const TargetTransformInfo & TTI, StringRef Name) static
Definition at line 136 of file AMDGPUUnifyDivergentExitNodes.cpp.
References llvm::PHINode::addIncoming(), llvm::CallingConv::AMDGPU_PS, assert(), B, llvm::BasicBlock::Create(), llvm::CallInst::Create(), llvm::ReturnInst::Create(), llvm::BranchInst::Create(), llvm::SmallVectorBase::empty(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::eraseFromParent(), F(), llvm::SmallVectorTemplateCommon< T >::front(), llvm::UndefValue::get(), llvm::Function::getCallingConv(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::GlobalValue::getParent(), llvm::Function::getReturnType(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), isUniformlyReached(), llvm::Type::isVoidTy(), Name, llvm::SmallVectorTemplateBase< T >::push_back(), removeDoneExport(), runOnFunction(), llvm::simplifyCFG(), llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::BasicBlock::splitBasicBlock(), and llvm::RegState::Undef.
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 75 of file AMDGPUUnifyDivergentExitNodes.cpp.
false
Unify divergent function exit false
Definition at line 75 of file AMDGPUUnifyDivergentExitNodes.cpp.
nodes
Unify divergent function exit nodes
Definition at line 75 of file AMDGPUUnifyDivergentExitNodes.cpp.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), llvm::SpillPlacement::addPrefSpill(), llvm::SpillPlacement::finish(), llvm::SpillPlacement::Node::getDissentingNeighbors(), llvm::SpillPlacement::iterate(), and llvm::SpillPlacement::scanActiveBundles().