LLVM: lib/Target/AMDGPU/AMDGPUCallLowering.cpp File Reference
AMDGPUCallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "AMDGPUCallLowering.h"
#include "AMDGPU.h"
#include "AMDGPUISelLowering.h"
#include "AMDGPUSubtarget.h"
#include "SIISelLowering.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/Support/LowLevelTypeImpl.h"
Functions
static LLT getMultipleType (LLT OrigTy, int Factor)
static void unpackRegsToOrigType (MachineIRBuilder &B, ArrayRef< Register > DstRegs, Register SrcReg, LLT SrcTy, LLT PartTy)
static void allocateHSAUserSGPRs (CCState &CCInfo, MachineIRBuilder &B, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info)
static void packSplitRegsToOrigType (MachineIRBuilder &B, ArrayRef< Register > OrigRegs, ArrayRef< Register > Regs, LLT LLTy, LLT PartLLT)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file AMDGPUCallLowering.cpp.
Function Documentation
allocateHSAUserSGPRs()
static void allocateHSAUserSGPRs (CCState & CCInfo, MachineIRBuilder & B, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) static
Definition at line 385 of file AMDGPUCallLowering.cpp.
References llvm::SIMachineFunctionInfo::addDispatchID(), llvm::SIMachineFunctionInfo::addDispatchPtr(), llvm::SIMachineFunctionInfo::addFlatScratchInit(), llvm::SIMachineFunctionInfo::addKernargSegmentPtr(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::addLiveIn(), llvm::MachineRegisterInfo::addLiveIn(), llvm::SIMachineFunctionInfo::addPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::addQueuePtr(), llvm::CCState::AllocateReg(), llvm::MachineIRBuilder::buildCopy(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineIRBuilder::getMBB(), llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::hasDispatchID(), llvm::SIMachineFunctionInfo::hasDispatchPtr(), llvm::SIMachineFunctionInfo::hasFlatScratchInit(), llvm::SIMachineFunctionInfo::hasKernargSegmentPtr(), llvm::SIMachineFunctionInfo::hasPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::hasQueuePtr(), and llvm::LLT::pointer().
Referenced by llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
getMultipleType()
static LLT getMultipleType (LLT OrigTy, int Factor) static
Definition at line 208 of file AMDGPUCallLowering.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), llvm::LLT::scalar(), and llvm::LLT::vector().
Referenced by unpackRegsToOrigType().
packSplitRegsToOrigType()
static void packSplitRegsToOrigType (MachineIRBuilder & B, ArrayRef< Register > OrigRegs, ArrayRef< Register > Regs, LLT LLTy, LLT PartLLT) static
Definition at line 489 of file AMDGPUCallLowering.cpp.
References assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildTrunc(), llvm::ArrayRef< T >::drop_front(), llvm::LLT::getElementType(), llvm::MachineIRBuilder::getMRI(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), I, llvm::LLT::isPointer(), llvm::LLT::isVector(), Merge, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::MachineRegisterInfo::setType(), llvm::ArrayRef< T >::take_front(), and llvm::LLT::vector().
Referenced by llvm::AMDGPUCallLowering::lowerFormalArguments().
unpackRegsToOrigType()
static void unpackRegsToOrigType (MachineIRBuilder & B, ArrayRef< Register > DstRegs, Register SrcReg, LLT SrcTy, LLT PartTy) static
Definition at line 218 of file AMDGPUCallLowering.cpp.
References assert(), B, llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineIRBuilder::buildUnmerge(), llvm::AMDGPUTargetLowering::CCAssignFnForReturn(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::numbers::e, F(), llvm::LLT::getElementType(), llvm::MachineIRBuilder::getMF(), getMultipleType(), getReg(), llvm::LLT::getSizeInBits(), llvm::Value::getType(), llvm::CallLowering::handleAssignments(), llvm::LLT::isVector(), llvm::MipsISD::Ret, llvm::AttributeList::ReturnIndex, llvm::CallLowering::setArgFlags(), and llvm::ArrayRef< T >::size().