LLVM: lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp File Reference
AMDGPUDisassembler.cpp File Reference
This file contains definition for AMDGPU ISA disassembler.
#include "Disassembler/AMDGPUDisassembler.h"
#include "AMDGPU.h"
#include "AMDGPURegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm-c/Disassembler.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <tuple>
#include <vector>
#include "AMDGPUGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "amdgpu-disassembler"
#define SGPR_MAX
#define DECODE_OPERAND(StaticDecoderName, DecoderName)
#define DECODE_OPERAND_REG(RegClass) DECODE_OPERAND(Decode##RegClass##RegisterClass, decodeOperand_##RegClass)
#define DECODE_SDWA(DecName) DECODE_OPERAND(decodeSDWA##DecName, decodeSDWA##DecName)
Typedefs
using DecodeStatus = llvm::MCDisassembler::DecodeStatus
Functions
static MCDisassembler::DecodeStatus addOperand (MCInst &Inst, const MCOperand &Opnd)
static int insertNamedMCOperand (MCInst &MI, const MCOperand &Op, uint16_t NameIdx)
static DecodeStatus decodeSoppBrTarget (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeBoolReg (MCInst &Inst, unsigned Val, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_VSrc16 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_VSrcV216 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_VS_16 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_VS_32 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_AReg_128 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_AReg_512 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_AReg_1024 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_SReg_32 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
static DecodeStatus decodeOperand_VGPR_32 (MCInst &Inst, unsigned Imm, uint64_t Addr, const void *Decoder)
template<typename T >
static T eatBytes (ArrayRef< uint8_t > &Bytes)
static bool isValidDPP8 (const MCInst &MI)
static int64_t getInlineImmVal32 (unsigned Imm)
static int64_t getInlineImmVal64 (unsigned Imm)
static int64_t getInlineImmVal16 (unsigned Imm)
static MCSymbolizer * createAMDGPUSymbolizer (const Triple &, LLVMOpInfoCallback, LLVMSymbolLookupCallback, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
static MCDisassembler * createAMDGPUDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUDisassembler ()
Detailed Description
This file contains definition for AMDGPU ISA disassembler.
Definition in file AMDGPUDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-disassembler"
Definition at line 53 of file AMDGPUDisassembler.cpp.
DECODE_OPERAND
#define DECODE_OPERAND (StaticDecoderName, DecoderName)
Value:
static DecodeStatus StaticDecoderName(MCInst &Inst, \
                                       unsigned Imm, \
                                       uint64_t /*Addr*/, \
                                       const void *Decoder) { \
  auto DAsm = static_cast<const AMDGPUDisassembler*>(Decoder); \
  return addOperand(Inst, DAsm->DecoderName(Imm)); \
}
Definition at line 110 of file AMDGPUDisassembler.cpp.
DECODE_OPERAND_REG
#define DECODE_OPERAND_REG (RegClass) DECODE_OPERAND(Decode##RegClass##RegisterClass, decodeOperand_##RegClass)
Definition at line 119 of file AMDGPUDisassembler.cpp.
DECODE_SDWA
#define DECODE_SDWA (DecName) DECODE_OPERAND(decodeSDWA##DecName, decodeSDWA##DecName)
Definition at line 221 of file AMDGPUDisassembler.cpp.
SGPR_MAX
#define SGPR_MAX
Value:
(isGFX10() ? AMDGPU::EncValues::SGPR_MAX_GFX10 \
                            : AMDGPU::EncValues::SGPR_MAX_SI)
Definition at line 55 of file AMDGPUDisassembler.cpp.
Referenced by llvm::AMDGPUDisassembler::decodeDstOp(), llvm::AMDGPUDisassembler::decodeSDWAVopcDst(), and llvm::AMDGPUDisassembler::decodeSrcOp().
Typedef Documentation
DecodeStatus
using DecodeStatus = llvm::MCDisassembler::DecodeStatus
Definition at line 58 of file AMDGPUDisassembler.cpp.
Function Documentation
addOperand()
static MCDisassembler::DecodeStatus addOperand (MCInst & Inst, const MCOperand & Opnd) inline static
Definition at line 72 of file AMDGPUDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCDisassembler::Fail, llvm::MCOperand::isValid(), and llvm::MCDisassembler::Success.
Referenced by NoAutoPaddingScope::changeAndComment(), decodeBoolReg(), decodeOperand_AReg_1024(), decodeOperand_AReg_128(), decodeOperand_AReg_512(), decodeOperand_SReg_32(), decodeOperand_VGPR_32(), decodeOperand_VS_16(), decodeOperand_VS_32(), decodeOperand_VSrc16(), decodeOperand_VSrcV216(), decodeSoppBrTarget(), llvm::NamedMDNode::getParent(), matchRegisterNameHelper(), and llvm::VPUser::VPUser().
createAMDGPUDisassembler()
static MCDisassembler* createAMDGPUDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 1249 of file AMDGPUDisassembler.cpp.
References llvm::AMDGPUDisassembler::AMDGPUDisassembler(), and llvm::Target::createMCInstrInfo().
Referenced by LLVMInitializeAMDGPUDisassembler().
createAMDGPUSymbolizer()
static MCSymbolizer* createAMDGPUSymbolizer (const Triple & , LLVMOpInfoCallback , LLVMSymbolLookupCallback , void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) static
Definition at line 1240 of file AMDGPUDisassembler.cpp.
Referenced by LLVMInitializeAMDGPUDisassembler().
decodeBoolReg()
static DecodeStatus decodeBoolReg (MCInst & Inst, unsigned Val, uint64_t Addr, const void * Decoder) static
Definition at line 104 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeOperand_AReg_1024()
static DecodeStatus decodeOperand_AReg_1024 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 197 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::AMDGPUDisassembler::OPW1024.
decodeOperand_AReg_128()
static DecodeStatus decodeOperand_AReg_128 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 181 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::AMDGPUDisassembler::OPW128.
decodeOperand_AReg_512()
static DecodeStatus decodeOperand_AReg_512 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 189 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::AMDGPUDisassembler::OPW512.
decodeOperand_SReg_32()
static DecodeStatus decodeOperand_SReg_32 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 205 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeOperand_VGPR_32()
static DecodeStatus decodeOperand_VGPR_32 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 213 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::AMDGPUDisassembler::OPW32.
decodeOperand_VS_16()
static DecodeStatus decodeOperand_VS_16 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 165 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeOperand_VS_32()
static DecodeStatus decodeOperand_VS_32 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 173 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeOperand_VSrc16()
static DecodeStatus decodeOperand_VSrc16 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 149 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeOperand_VSrcV216()
static DecodeStatus decodeOperand_VSrcV216 (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 157 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeSoppBrTarget()
static DecodeStatus decodeSoppBrTarget (MCInst & Inst, unsigned Imm, uint64_t Addr, const void * Decoder) static
Definition at line 90 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::MCOperand::createImm(), llvm::APInt::sext(), and llvm::MCDisassembler::Success.
eatBytes()
template<typename T > static T eatBytes (ArrayRef< uint8_t > & Bytes) inline static
Definition at line 234 of file AMDGPUDisassembler.cpp.
References assert(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), and llvm::T.
getInlineImmVal16()
static int64_t getInlineImmVal16 (unsigned Imm) static
Definition at line 861 of file AMDGPUDisassembler.cpp.
References llvm_unreachable.
Referenced by llvm::AMDGPUDisassembler::decodeFPImmed().
getInlineImmVal32()
static int64_t getInlineImmVal32 (unsigned Imm) static
Definition at line 811 of file AMDGPUDisassembler.cpp.
References llvm::FloatToBits(), and llvm_unreachable.
Referenced by llvm::AMDGPUDisassembler::decodeFPImmed().
getInlineImmVal64()
static int64_t getInlineImmVal64 (unsigned Imm) static
Definition at line 836 of file AMDGPUDisassembler.cpp.
References llvm::DoubleToBits(), and llvm_unreachable.
Referenced by llvm::AMDGPUDisassembler::decodeFPImmed().
insertNamedMCOperand()
static int insertNamedMCOperand (MCInst & MI, const MCOperand & Op, uint16_t NameIdx) static
Definition at line 79 of file AMDGPUDisassembler.cpp.
References llvm::MCInst::begin(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInst::getOpcode(), I, and llvm::MCInst::insert().
Referenced by llvm::AMDGPUDisassembler::convertDPP8Inst(), llvm::AMDGPUDisassembler::convertSDWAInst(), and llvm::AMDGPUDisassembler::getInstruction().
isValidDPP8()
static bool isValidDPP8 (const MCInst & MI) static
Definition at line 258 of file AMDGPUDisassembler.cpp.
References assert(), llvm::AMDGPU::DPP::DPP8_FI_0, llvm::AMDGPU::DPP::DPP8_FI_1, llvm::MCOperand::getImm(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), and llvm::MCInst::getOperand().
Referenced by llvm::AMDGPUDisassembler::convertDPP8Inst().
LLVMInitializeAMDGPUDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUDisassembler ()
Definition at line 1255 of file AMDGPUDisassembler.cpp.
References createAMDGPUDisassembler(), createAMDGPUSymbolizer(), llvm::getTheGCNTarget(), llvm::TargetRegistry::RegisterMCDisassembler(), and llvm::TargetRegistry::RegisterMCSymbolizer().