LLVM: lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp File Reference
AMDGPUInstructionSelector.cpp File Reference
This file implements the targeting of the InstructionSelector class for AMDGPU.
#include "AMDGPUInstructionSelector.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPUGlobalISelUtils.h"
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPURegisterInfo.h"
#include "AMDGPUSubtarget.h"
#include "AMDGPUTargetMachine.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelector.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelectorImpl.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "AMDGPUGenGlobalISel.inc"
Macros
#define DEBUG_TYPE "amdgpu-isel"
#define GET_GLOBALISEL_IMPL
#define AMDGPUSubtarget GCNSubtarget
#define GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Functions
static unsigned getLogicalBitOpcode (unsigned Opc, bool Is64)
static int getV_CMPOpcode (CmpInst::Predicate P, unsigned Size)
static MachineInstr * buildEXP (const TargetInstrInfo &TII, MachineInstr *Insert, unsigned Tgt, unsigned Reg0, unsigned Reg1, unsigned Reg2, unsigned Reg3, unsigned VM, bool Compr, unsigned Enabled, bool Done)
static bool isZero (Register Reg, MachineRegisterInfo &MRI)
static unsigned extractGLC (unsigned AuxiliaryData)
static unsigned extractSLC (unsigned AuxiliaryData)
static unsigned extractDLC (unsigned AuxiliaryData)
static unsigned extractSWZ (unsigned AuxiliaryData)
static unsigned getBufferStoreOpcode (LLT Ty, const unsigned MemSize, const bool Offen)
static unsigned getBufferStoreFormatOpcode (LLT Ty, const unsigned MemSize, const bool Offen)
static unsigned getDSShaderTypeValue (const MachineFunction &MF)
static int sizeToSubRegIndex (unsigned Size)
static bool shouldUseAndMask (unsigned Size, unsigned &Mask)
static bool isConstant (const MachineInstr &MI)
static bool isStackPtrRelative (const MachinePointerInfo &PtrInfo)
Detailed Description
This file implements the targeting of the InstructionSelector class for AMDGPU.
Todo:
This should be generated by TableGen.
Definition in file AMDGPUInstructionSelector.cpp.
Macro Definition Documentation
AMDGPUSubtarget
#define AMDGPUSubtarget GCNSubtarget
Definition at line 44 of file AMDGPUInstructionSelector.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-isel"
Definition at line 38 of file AMDGPUInstructionSelector.cpp.
Referenced by llvm::AMDGPUInstructionSelector::AMDGPUInstructionSelector().
GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_IMPL
Definition at line 43 of file AMDGPUInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_PREDICATES_INIT
GET_GLOBALISEL_TEMPORARIES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Function Documentation
buildEXP()
static MachineInstr* buildEXP (const TargetInstrInfo & TII, MachineInstr * Insert, unsigned Tgt, unsigned Reg0, unsigned Reg1, unsigned Reg2, unsigned Reg3, unsigned VM, bool Compr, unsigned Enabled, bool Done) static
Definition at line 783 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SIInstrFlags::EXP, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), and llvm::MachineInstr::getParent().
Referenced by getDSShaderTypeValue().
extractDLC()
static unsigned extractDLC (unsigned AuxiliaryData) static
Definition at line 817 of file AMDGPUInstructionSelector.cpp.
Referenced by getBufferStoreFormatOpcode().
extractGLC()
static unsigned extractGLC (unsigned AuxiliaryData) static
Definition at line 809 of file AMDGPUInstructionSelector.cpp.
Referenced by getBufferStoreFormatOpcode().
extractSLC()
static unsigned extractSLC (unsigned AuxiliaryData) static
Definition at line 813 of file AMDGPUInstructionSelector.cpp.
Referenced by getBufferStoreFormatOpcode().
extractSWZ()
static unsigned extractSWZ (unsigned AuxiliaryData) static
Definition at line 821 of file AMDGPUInstructionSelector.cpp.
Referenced by getBufferStoreFormatOpcode().
getBufferStoreFormatOpcode()
static unsigned getBufferStoreFormatOpcode (LLT Ty, const unsigned MemSize, const bool Offen) static
Definition at line 845 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addUse(), B, llvm::MachineIRBuilder::buildInstr(), llvm::constrainSelectedInstRegOperands(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::eraseFromParent(), extractDLC(), extractGLC(), extractSLC(), extractSWZ(), llvm::SIInstrInfo::getAddNoCarry(), llvm::AMDGPU::getBaseWithConstantOffset(), getBufferStoreOpcode(), llvm::MachineIRBuilder::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineIRBuilder::getInsertPt(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMBB(), llvm::MachineIRBuilder::getMF(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineMemOperand::getSize(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), isZero(), llvm::RegState::Kill, llvm_unreachable, llvm::MachineInstr::memoperands_begin(), llvm::InstructionSelector::MF, llvm::MachineIRBuilder::setInsertPt(), and llvm::MachineIRBuilder::setInstr().
getBufferStoreOpcode()
static unsigned getBufferStoreOpcode (LLT Ty, const unsigned MemSize, const bool Offen) static
Definition at line 825 of file AMDGPUInstructionSelector.cpp.
References llvm::AMDGPU::getMUBUFOpcode(), and llvm::LLT::getSizeInBits().
Referenced by getBufferStoreFormatOpcode().
getDSShaderTypeValue()
static unsigned getDSShaderTypeValue (const MachineFunction & MF) static
Definition at line 1025 of file AMDGPUInstructionSelector.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, assert(), buildEXP(), llvm::BuildMI(), llvm::CallingConv::C, llvm::MachineInstrBuilder::cloneMemRefs(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::constrainSelectedInstRegOperands(), llvm::InstructionSelector::CoverageInfo, llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SIInstrFlags::DS, llvm::AMDGPUISD::DS_ORDERED_COUNT, Enabled, llvm::MachineInstr::eraseFromParent(), llvm::CallingConv::Fast, llvm::Function::getCallingConv(), llvm::SIRegisterInfo::getConstrainedRegClassForOperand(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::GCNSubtarget::getGeneration(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getIntrinsicID(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::SIRegisterInfo::getWaveMaskRegClass(), llvm::AMDGPUSubtarget::GFX10, llvm::InstructionSelector::MF, llvm::report_fatal_error(), llvm::MipsISD::Ret, llvm::MCID::Select, llvm::MachineRegisterInfo::setRegClass(), and llvm::RegState::Undef.
getLogicalBitOpcode()
static unsigned getLogicalBitOpcode (unsigned Opc, bool Is64) static
Definition at line 238 of file AMDGPUInstructionSelector.cpp.
References llvm::MCID::Add, add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::constrainSelectedInstRegOperands(), llvm::InstructionSelector::CoverageInfo, llvm::MachineOperand::CreateImm(), llvm::MachineOperand::CreateReg(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Dead, E, llvm::MachineInstr::eraseFromParent(), llvm::SIRegisterInfo::getBoolRC(), llvm::SIRegisterInfo::getConstrainedRegClassForOperand(), llvm::MachineInstr::getDebugLoc(), llvm::RegisterBank::getID(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getIntrinsicID(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::MachineRegisterInfo::getRegBankOrNull(), llvm::SIRegisterInfo::getRegClassForSizeOnBank(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::SIRegisterInfo::getRegSplitParts(), llvm::LLT::getSizeInBits(), llvm::AMDGPURegisterInfo::getSubRegFromChannel(), llvm::MachineRegisterInfo::getType(), llvm::getUndefRegState(), llvm::SIRegisterInfo::getWaveMaskRegClass(), llvm::GCNSubtarget::hasAddNoCarry(), I, llvm::MachineOperand::isUndef(), llvm::RegState::Kill, llvm_unreachable, llvm::InstructionSelector::MF, MI, llvm::MachineInstr::operands(), llvm::MachineInstr::setDesc(), llvm::MachineRegisterInfo::setRegClass(), Size, and SubReg.
getV_CMPOpcode()
static int getV_CMPOpcode (CmpInst::Predicate P, unsigned Size) static
Definition at line 667 of file AMDGPUInstructionSelector.cpp.
References add(), llvm::BuildMI(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::constrainSelectedInstRegOperands(), llvm::MachineInstr::eraseFromParent(), llvm::SIRegisterInfo::getBoolRC(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::GCNSubtarget::hasScalarCompareEq64(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, P, llvm::MipsISD::Ret, and Size.
isConstant()
static bool isConstant (const MachineInstr & MI) static
Definition at line 1490 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::BuildMI(), AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::RegisterBankInfo::constrainGenericRegister(), llvm::InstructionSelector::CoverageInfo, llvm::MachineOperand::CreateReg(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dyn_cast(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getAddressSpace(), llvm::MachineMemOperand::getAddrSpace(), llvm::MachineOperand::getCImm(), llvm::MachineInstr::getDebugLoc(), llvm::RegisterBank::getID(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::Instruction::getMetadata(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::ConstantInt::getSExtValue(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineMemOperand::getValue(), llvm::MachineInstr::hasOneMemOperand(), llvm::RegState::Implicit, llvm::GCNSubtarget::ldsRequiresM0Init(), llvm::SPII::Load, AMDGPUAS::LOCAL_ADDRESS, llvm::BitmaskEnumDetail::Mask(), llvm::MachineInstr::memoperands_begin(), llvm::InstructionSelector::MF, llvm::SmallVectorTemplateBase< T >::push_back(), AMDGPUAS::REGION_ADDRESS, llvm::LLT::scalar(), llvm::MachineInstr::setDesc(), llvm::MachineRegisterInfo::setRegClass(), llvm::AMDGPU::VGPRIndexMode::SRC0_ENABLE, SubReg, llvm::RegState::Undef, and llvm::GCNSubtarget::useVGPRIndexMode().
Referenced by ConstantBuildVector(), llvm::MDBuilder::createAnonymousAliasScope(), ExpandBVWithShuffles(), llvm::HexagonInstrInfo::expandPostRAPseudo(), foldBitcastedFPLogic(), llvm::DIExpression::getElement(), inferDSOLocal(), INITIALIZE_PASS(), isDebug(), isRegOtherThanSPAndFP(), LLVMIsGlobalConstant(), and LowerBUILD_VECTOR_i1().
isStackPtrRelative()
static bool isStackPtrRelative (const MachinePointerInfo & PtrInfo) static
Definition at line 2089 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), assert(), llvm::APFloat::bitcastToAPInt(), llvm::BuildMI(), llvm::APInt::countPopulation(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::PointerUnion< PTs >::dyn_cast(), llvm::MachineOperand::getCImm(), llvm::getConstantVRegVal(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineMemOperand::getPointerInfo(), llvm::MachineOperand::getReg(), llvm::SIMachineFunctionInfo::getScratchRSrcReg(), llvm::SIMachineFunctionInfo::getScratchWaveOffsetReg(), llvm::ConstantInt::getSExtValue(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::ConstantInt::getValue(), llvm::Optional< T >::getValue(), llvm::ConstantFP::getValueAPF(), llvm::MachineRegisterInfo::getVRegDef(), llvm::APInt::getZExtValue(), llvm::AMDGPUSubtarget::hasInv2PiInlineImm(), llvm::GCNSubtarget::hasUsableDSOffset(), llvm::Optional< T >::hasValue(), Info, llvm::InstructionSelector::isBaseWithConstantOffset(), llvm::AMDGPU::isInlinableLiteral16(), llvm::AMDGPU::isInlinableLiteral32(), llvm::AMDGPU::isInlinableLiteral64(), llvm::SIInstrInfo::isInlineConstant(), llvm::SIInstrInfo::isLegalMUBUFImmOffset(), llvm::PseudoSourceValue::isStack(), llvm::isUInt< 16 >(), llvm::isUInt< 8 >(), llvm::MIPatternMatch::m_ICst(), llvm::MachineInstr::memoperands_begin(), llvm::InstructionSelector::MF, llvm::MIPatternMatch::mi_match(), llvm::GCNSubtarget::privateMemoryResourceIsRangeChecked(), llvm::GCNSubtarget::unsafeDSOffsetFoldingEnabled(), and llvm::MachinePointerInfo::V.
isZero()
static bool isZero (Register Reg, MachineRegisterInfo & MRI) static
Definition at line 800 of file AMDGPUInstructionSelector.cpp.
References C, llvm::MIPatternMatch::m_Copy(), llvm::MIPatternMatch::m_ICst(), and llvm::MIPatternMatch::mi_match().
Referenced by getBufferStoreFormatOpcode().
shouldUseAndMask()
static bool shouldUseAndMask (unsigned Size, unsigned & Mask) static
Returns
true if a bitmask for Size bits will be an inline immediate.
Definition at line 1300 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addImplicitDefUseOperands(), llvm::MachineInstrBuilder::addReg(), llvm::APFloat::bitcastToAPInt(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::constrainSelectedInstRegOperands(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::PointerUnion< PTs >::dyn_cast(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getCImm(), llvm::TargetRegisterInfo::getConstrainedRegClassForOperand(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getFPImm(), llvm::RegisterBank::getID(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::AMDGPURegisterBankInfo::getRegBankFromRegClass(), llvm::MachineRegisterInfo::getRegBankOrNull(), llvm::MachineRegisterInfo::getRegClassOrRegBank(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::ConstantFP::getValueAPF(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), llvm::MachineOperand::isCImm(), llvm::MachineOperand::isFPImm(), llvm::SIInstrInfo::isInlineConstant(), llvm::LLT::isScalar(), llvm::BitmaskEnumDetail::Mask(), llvm::InstructionSelector::MF, llvm::MachineInstr::setDesc(), Signed, and Size.
sizeToSubRegIndex()
static int sizeToSubRegIndex (unsigned Size) static
Definition at line 1224 of file AMDGPUInstructionSelector.cpp.
References llvm::RegisterBankInfo::constrainGenericRegister(), llvm::dbgs(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::SIRegisterInfo::getRegClassForSizeOnBank(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isScalar(), LLVM_DEBUG, llvm::PowerOf2Ceil(), llvm::LLT::scalar(), llvm::MachineInstr::setDesc(), and llvm::MachineOperand::setSubReg().