LLVM: lib/Target/ARC/ARCBranchFinalize.cpp File Reference
ARCBranchFinalize.cpp File Reference
#include "ARCInstrInfo.h"
#include "ARCTargetMachine.h"
#include "MCTargetDesc/ARCInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include <vector>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "arc-branch-finalize"
Functions
void llvm::initializeARCBranchFinalizePass (PassRegistry &Registry)
FunctionPass * llvm::createARCBranchFinalizePass ()
INITIALIZE_PASS_BEGIN (ARCBranchFinalize, "arc-branch-finalize", "ARC finalize branches", false, false) INITIALIZE_PASS_END(ARCBranchFinalize
arc branch ARC finalize static false unsigned getCCForBRcc (unsigned CC)
static bool isBRccPseudo (MachineInstr *MI)
static unsigned getBRccForPseudo (MachineInstr *MI)
static unsigned getCmpForPseudo (MachineInstr *MI)
Variables
arc branch finalize
arc branch ARC finalize branches
arc branch ARC finalize false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-branch-finalize"
Definition at line 13 of file ARCBranchFinalize.cpp.
Function Documentation
getBRccForPseudo()
static unsigned getBRccForPseudo (MachineInstr * MI) static
Definition at line 100 of file ARCBranchFinalize.cpp.
References assert(), llvm::MachineInstr::getOpcode(), and isBRccPseudo().
Referenced by getCmpForPseudo().
getCCForBRcc()
arc branch ARC finalize static false unsigned getCCForBRcc (unsigned CC) static
Definition at line 76 of file ARCBranchFinalize.cpp.
References llvm::ARCCC::EQ, llvm::ARCCC::GE, llvm::ARCCC::HS, llvm::ARCCC::LO, llvm::ARCCC::LT, and llvm::ARCCC::NE.
Referenced by getCmpForPseudo().
getCmpForPseudo()
static unsigned getCmpForPseudo (MachineInstr * MI) static
Definition at line 107 of file ARCBranchFinalize.cpp.
References add(), assert(), llvm::BuildMI(), llvm::dbgs(), llvm::MachineInstr::eraseFromParent(), getBRccForPseudo(), getCCForBRcc(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineFunction::getName(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::isBranch(), isBRccPseudo(), LLVM_DEBUG, MI, P, Size, and TII.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ARCBranchFinalize , "arc-branch-finalize" , "ARC finalize branches" , false , false)
isBRccPseudo()
static bool isBRccPseudo (MachineInstr * MI) static
Definition at line 95 of file ARCBranchFinalize.cpp.
References llvm::MachineInstr::getOpcode().
Referenced by getBRccForPseudo(), and getCmpForPseudo().
Variable Documentation
branches
arc branch ARC finalize branches
Definition at line 65 of file ARCBranchFinalize.cpp.
false
arc branch ARC finalize false
Definition at line 65 of file ARCBranchFinalize.cpp.
finalize
arc branch finalize
Definition at line 65 of file ARCBranchFinalize.cpp.
Referenced by llvm::AccelTableBase::AccelTableBase(), llvm::pdb::DbiStreamBuilder::addSectionContrib(), llvm::DwarfExpression::DwarfExpression(), llvm::pdb::DbiModuleDescriptorBuilder::getNextSymbolOffset(), llvm::pdb::TpiStreamBuilder::getRecordCount(), llvm::pdb::InfoStreamBuilder::getSignature(), and llvm::DebugLocEntry::sortUniqueValues().