LLVM: lib/Target/ARC/ARCExpandPseudos.cpp File Reference
ARCExpandPseudos.cpp File Reference
#include "ARC.h"
#include "ARCInstrInfo.h"
#include "ARCRegisterInfo.h"
#include "ARCSubtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
Macros
#define DEBUG_TYPE "arc-expand-pseudos"
Functions
static unsigned getMappedOp (unsigned PseudoOp)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-expand-pseudos"
Definition at line 23 of file ARCExpandPseudos.cpp.
Function Documentation
getMappedOp()
static unsigned getMappedOp (unsigned PseudoOp) static
Definition at line 46 of file ARCExpandPseudos.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), E, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::ARCSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm_unreachable, SI, and TII.
Referenced by wrapConstantAsMetadata().