LLVM: lib/Target/ARC/MCTargetDesc/ARCInstPrinter.cpp File Reference
ARCInstPrinter.cpp File Reference
#include "ARCInstPrinter.h"
#include "MCTargetDesc/ARCInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "ARCGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
template<class T >
static const char * BadConditionCode (T cc)
static const char * ARCBRCondCodeToString (ARCCC::BRCondCode BRCC)
static const char * ARCCondCodeToString (ARCCC::CondCode CC)
static void printExpr (const MCExpr *Expr, const MCAsmInfo *MAI, raw_ostream &OS)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 26 of file ARCInstPrinter.cpp.
Function Documentation
ARCBRCondCodeToString()
static const char* ARCBRCondCodeToString (ARCCC::BRCondCode BRCC) static
Definition at line 36 of file ARCInstPrinter.cpp.
References BadConditionCode(), llvm::ARCCC::BREQ, llvm::ARCCC::BRGE, llvm::ARCCC::BRHS, llvm::ARCCC::BRLO, llvm::ARCCC::BRLT, and llvm::ARCCC::BRNE.
Referenced by printExpr().
ARCCondCodeToString()
static const char* ARCCondCodeToString (ARCCC::CondCode CC) static
Definition at line 54 of file ARCInstPrinter.cpp.
References llvm::ARCCC::AL, BadConditionCode(), llvm::ARCCC::EQ, llvm::ARCCC::GE, llvm::ARCCC::GT, llvm::ARCCC::HI, llvm::ARCCC::HS, llvm::ARCCC::LE, llvm::ARCCC::LO, llvm::ARCCC::LS, llvm::ARCCC::LT, llvm::ARCCC::N, llvm::ARCCC::NE, llvm::ARCCC::NZ, llvm::ARCCC::P, llvm::ARCCC::PNZ, llvm::ARCCC::VC, llvm::ARCCC::VS, and llvm::ARCCC::Z.
Referenced by printExpr().
BadConditionCode()
template<class T > static const char* BadConditionCode (T cc) static
Definition at line 31 of file ARCInstPrinter.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Referenced by ARCBRCondCodeToString(), and ARCCondCodeToString().
printExpr()
static void printExpr (const MCExpr * Expr, const MCAsmInfo * MAI, raw_ostream & OS) static
Definition at line 107 of file ARCInstPrinter.cpp.
References ARCBRCondCodeToString(), ARCCondCodeToString(), assert(), llvm::dyn_cast(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCSymbolRefExpr::getKind(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, MI, llvm::RISCVFenceField::O, llvm::MCSymbol::print(), llvm::ARCInstPrinter::printRegName(), llvm::MCSymbolRefExpr::VK_None, and llvm::raw_ostream::write_hex().