LLVM: lib/Target/ARC/ARCRegisterInfo.cpp File Reference
ARCRegisterInfo.cpp File Reference
#include "ARCRegisterInfo.h"
#include "ARC.h"
#include "ARCInstrInfo.h"
#include "ARCMachineFunctionInfo.h"
#include "ARCSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "ARCGenRegisterInfo.inc"
Macros
#define DEBUG_TYPE "arc-reg-info"
#define GET_REGINFO_TARGET_DESC
Functions
static void ReplaceFrameIndex (MachineBasicBlock::iterator II, const ARCInstrInfo &TII, unsigned Reg, unsigned FrameReg, int Offset, int StackSize, int ObjSize, RegScavenger *RS, int SPAdj)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-reg-info"
Definition at line 33 of file ARCRegisterInfo.cpp.
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 35 of file ARCRegisterInfo.cpp.
Function Documentation
ReplaceFrameIndex()
static void ReplaceFrameIndex (MachineBasicBlock::iterator II, const ARCInstrInfo & TII, unsigned Reg, unsigned FrameReg, int Offset, int StackSize, int ObjSize, RegScavenger * RS, int SPAdj) static
Definition at line 38 of file ARCRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::dbgs(), llvm::RegState::Define, llvm::MachineBasicBlock::erase(), llvm::RegScavenger::FindUnusedReg(), llvm::MachineInstr::getDebugLoc(), llvm::getKillRegState(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isKill(), llvm::RegState::Kill, LLVM_DEBUG, LLVM_FALLTHROUGH, llvm_unreachable, llvm::MachineInstr::memoperands_begin(), MI, llvm::printReg(), Reg, llvm::RegScavenger::scavengeRegister(), llvm::RegScavenger::setRegUsed(), and TRI.
Referenced by llvm::ARCRegisterInfo::eliminateFrameIndex().