LLVM: lib/Target/ARM/ARMCallLowering.cpp File Reference
ARMCallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "ARMCallLowering.h"
#include "ARMBaseInstrInfo.h"
#include "ARMISelLowering.h"
#include "ARMSubtarget.h"
#include "Utils/ARMBaseInfo.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/LowLevelType.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/LowLevelTypeImpl.h"
#include "llvm/Support/MachineValueType.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <utility>
Functions
static bool isSupportedType (const DataLayout &DL, const ARMTargetLowering &TLI, Type *T)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file ARMCallLowering.cpp.
Function Documentation
isSupportedType()
static bool isSupportedType (const DataLayout & DL, const ARMTargetLowering & TLI, Type * T) static
Definition at line 55 of file ARMCallLowering.cpp.
References llvm::MachineInstrBuilder::addUse(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, Arg, assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildStore(), llvm::MachineIRBuilder::buildUnmerge(), llvm::ComputeValueVTs(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::numbers::e, llvm::SmallVectorImpl< T >::emplace_back(), F(), llvm::MVT::f64, llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::DataLayout::getABITypeAlignment(), llvm::Type::getArrayElementType(), llvm::Function::getCallingConv(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::CCState::getNextStackOffset(), llvm::MachineFunction::getRegInfo(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::MachinePointerInfo::getStack(), llvm::MVT::getStoreSize(), llvm::MachineFunction::getSubtarget(), llvm::Value::getType(), llvm::EVT::getTypeForEVT(), llvm::TargetLoweringBase::getValueType(), llvm::CCValAssign::getValVT(), llvm::CallLowering::handleAssignments(), llvm::RegState::Implicit, Info, llvm::Type::isArrayTy(), llvm::CCValAssign::isRegLoc(), llvm::Type::isStructTy(), llvm::Function::isVarArg(), llvm::max(), llvm::MachineMemOperand::MOStore, MRI, llvm::LLT::pointer(), Register, llvm::CallLowering::ArgInfo::Regs, llvm::MipsISD::Ret, llvm::AttributeList::ReturnIndex, llvm::LLT::scalar(), llvm::CallLowering::setArgFlags(), Size, llvm::SmallVectorBase::size(), std::swap(), and llvm::T.
Referenced by isPromotedResultSafe(), llvm::ARMCallLowering::lowerCall(), and llvm::ARMCallLowering::lowerFormalArguments().