LLVM: lib/Target/ARM/Disassembler/ARMDisassembler.cpp File Reference
ARMDisassembler.cpp File Reference
#include "ARMBaseInstrInfo.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "MCTargetDesc/ARMMCTargetDesc.h"
#include "TargetInfo/ARMTargetInfo.h"
#include "Utils/ARMBaseInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <vector>
#include "ARMGenDisassemblerTables.inc"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "arm-disassembler"
Typedefs
using DecodeStatus = MCDisassembler::DecodeStatus
typedef DecodeStatus OperandDecoder(MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
Functions
static bool Check (DecodeStatus &Out, DecodeStatus In)
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCLRMGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodetGPROddRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodetGPREvenRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRnopcRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRwithAPSRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRwithZRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRwithZRnospRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodetGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodetcGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecoderGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRPairRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRspRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeHPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDPR_8RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSPR_8RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDPR_VFP2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeQQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeQQQQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDPairRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDPairSpacedRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodePredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCCOutOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRegListOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSPRRegListOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDPRRegListOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBitfieldMaskOperand (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCopMemInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddrMode2IdxInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSORegMemOperand (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddrMode3Instruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSORegImmOperand (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSORegRegOperand (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMemMultipleWritebackInstruction (MCInst &Inst, unsigned Insn, uint64_t Adddress, const void *Decoder)
static DecodeStatus DecodeT2MOVTWInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeArmMOVTWInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSMLAInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeHINTInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCPSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeTSTInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSETPANInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2CPSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddrModeImm12Operand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddrMode5Operand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddrMode5FP16Operand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddrMode7Operand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2BInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBranchImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddrMode6Operand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLDST1Instruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLDST2Instruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLDST3Instruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLDST4Instruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLDInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVSTInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD1DupInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD2DupInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD3DupInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD4DupInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVMOVModImmInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMVEModImmInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMVEVADCInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVSHLMaxInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeShiftRight8Imm (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeShiftRight16Imm (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeShiftRight32Imm (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeShiftRight64Imm (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeTBLInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodePostIdxReg (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMveAddrModeRQ (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
template<int shift>
static DecodeStatus DecodeMveAddrModeQ (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCoprocessor (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMemBarrierOption (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeInstSyncBarrierOption (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMSRMask (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBankedReg (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDoubleRegLoad (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDoubleRegStore (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLDRPreImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLDRPreReg (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSTRPreImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSTRPreReg (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD1LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD2LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD3LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVLD4LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVST1LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVST2LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVST3LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVST4LN (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVMOVSRR (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVMOVRRS (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSwap (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVCVTD (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVCVTQ (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVCVTImmOperand (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeNEONComplexLane64Instruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbAddSpecialReg (MCInst &Inst, uint16_t Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbBROperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2BROperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbCmpBROperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbAddrModeRR (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbAddrModeIS (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbAddrModePC (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbAddrModeSP (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2AddrModeSOReg (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2LoadShift (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2LoadImm8 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2LoadImm12 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2LoadT (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2LoadLabel (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2Imm8S4 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2Imm7S4 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2AddrModeImm8s4 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2AddrModeImm7s4 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2AddrModeImm0_1020s4 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2Imm8 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<int shift>
static DecodeStatus DecodeT2Imm7 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2AddrModeImm8 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<int shift>
static DecodeStatus DecodeTAddrModeImm7 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<int shift, int WriteBack>
static DecodeStatus DecodeT2AddrModeImm7 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbAddSPImm (MCInst &Inst, uint16_t Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbAddSPReg (MCInst &Inst, uint16_t Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbCPS (MCInst &Inst, uint16_t Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeQADDInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbBLXOffset (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2AddrModeImm12 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbTableBranch (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumb2BCCInstruction (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2SOImm (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbBCCTargetOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeThumbBLTargetOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeIT (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2LDRDPreInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2STRDPreInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2Adr (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2LdStPre (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2ShifterImmOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLDR (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecoderForMRRC2AndMCRR2 (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeForVMRSandVMSR (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<bool isSigned, bool isNeg, bool zeroPermitted, int size>
static DecodeStatus DecodeBFLabelOperand (MCInst &Inst, unsigned val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBFAfterTargetOperand (MCInst &Inst, unsigned val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodePredNoALOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLOLoop (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLongShiftOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVSCCLRM (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVPTMaskOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVpredROperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRestrictedIPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRestrictedSPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRestrictedUPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRestrictedFPPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<bool Writeback>
static DecodeStatus DecodeVSTRVLDR_SYSREG (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
template<int shift>
static DecodeStatus DecodeMVE_MEM_1_pre (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<int shift>
static DecodeStatus DecodeMVE_MEM_2_pre (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<int shift>
static DecodeStatus DecodeMVE_MEM_3_pre (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<unsigned MinLog, unsigned MaxLog>
static DecodeStatus DecodePowerTwoOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<int shift>
static DecodeStatus DecodeExpandedImmOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
template<unsigned start>
static DecodeStatus DecodeMVEPairVectorIndexOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMVEVMOVQtoDReg (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMVEVMOVDRegtoQ (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMVEVCVTt1fp (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
template<bool scalar, OperandDecoder predicate_decoder>
static DecodeStatus DecodeMVEVCMP (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMveVCTP (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMVEVPNOT (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMVEOverlappingLongShift (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2AddSubSPImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static MCDisassembler * createARMDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static DecodeStatus checkDecodedInstruction (MCInst &MI, uint64_t &Size, uint64_t Address, raw_ostream &CS, uint32_t Insn, DecodeStatus Result)
static bool tryAddingSymbolicOperand (uint64_t Address, int32_t Value, bool isBranch, uint64_t InstSize, MCInst &MI, const void *Decoder)
tryAddingSymbolicOperand - trys to add a symbolic operand in place of the immediate Value in the MCInst.
static void tryAddingPcLoadReferenceComment (uint64_t Address, int Value, const void *Decoder)
tryAddingPcLoadReferenceComment - trys to add a comment as to what is being referenced by a load instruction with the base register that is the Pc.
static void AddThumb1SBit (MCInst &MI, bool InITBlock)
static bool isVectorPredicable (unsigned Opcode)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMDisassembler ()
static DecodeStatus DecodeRFEInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2Adr (MCInst &Inst, uint32_t Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeT2ShifterImmOperand (MCInst &Inst, uint32_t Val, uint64_t Address, const void *Decoder)
static unsigned FixedRegForVSTRVLDR_SYSREG (unsigned Opcode)
static DecodeStatus DecodeMVE_MEM_pre (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder, unsigned Rn, OperandDecoder RnDecoder, OperandDecoder AddrDecoder)
Variables
static const uint16_t GPRDecoderTable []
static const uint16_t CLRMGPRDecoderTable []
static const uint16_t GPRPairDecoderTable []
static const uint16_t SPRDecoderTable []
static const uint16_t DPRDecoderTable []
static const uint16_t QPRDecoderTable []
static const uint16_t DPairDecoderTable []
static const uint16_t DPairSpacedDecoderTable []
static const uint16_t QQPRDecoderTable []
static const uint16_t QQQQPRDecoderTable []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-disassembler"
Definition at line 34 of file ARMDisassembler.cpp.
Typedef Documentation
DecodeStatus
using DecodeStatus = MCDisassembler::DecodeStatus
Definition at line 36 of file ARMDisassembler.cpp.
OperandDecoder
typedef DecodeStatus OperandDecoder(MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
Definition at line 557 of file ARMDisassembler.cpp.
Function Documentation
AddThumb1SBit()
static void AddThumb1SBit (MCInst & MI, bool InITBlock) static
Definition at line 730 of file ARMDisassembler.cpp.
References llvm::ARMInsts, llvm::MCInst::begin(), llvm::MCOperand::createReg(), llvm::MCInst::end(), llvm::MCInst::getOpcode(), I, llvm::MCInst::insert(), llvm::MCInstrDesc::NumOperands, llvm::MCInstrDesc::OpInfo, and llvm::MCOperandInfo::RegClass.
Referenced by isVectorPredicable().
Check()
static bool Check (DecodeStatus & Out, DecodeStatus In) static
Definition at line 160 of file ARMDisassembler.cpp.
References llvm::Address, DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddrMode5FP16Operand(), DecodeAddrMode5Operand(), DecodeAddrMode6Operand(), DecodeAddrMode7Operand(), DecodeAddrModeImm12Operand(), DecodeArmMOVTWInstruction(), DecodeBankedReg(), DecodeBFAfterTargetOperand(), DecodeBFLabelOperand(), DecodeBitfieldMaskOperand(), DecodeBranchImmInstruction(), DecodeCCOutOperand(), DecodeCLRMGPRRegisterClass(), DecodeCopMemInstruction(), DecodeCoprocessor(), DecodeCPSInstruction(), DecodeDoubleRegLoad(), DecodeDoubleRegStore(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPR_8RegisterClass(), DecodeDPR_VFP2RegisterClass(), DecodeDPRRegisterClass(), DecodeDPRRegListOperand(), DecodeExpandedImmOperand(), DecodeForVMRSandVMSR(), DecodeGPRnopcRegisterClass(), DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodeGPRspRegisterClass(), DecodeGPRwithAPSRRegisterClass(), DecodeGPRwithZRnospRegisterClass(), DecodeGPRwithZRRegisterClass(), DecodeHINTInstruction(), DecodeHPRRegisterClass(), DecodeInstSyncBarrierOption(), DecodeIT(), DecodeLDR(), DecodeLDRPreImm(), DecodeLDRPreReg(), DecodeLOLoop(), DecodeLongShiftOperand(), DecodeMemBarrierOption(), DecodeMemMultipleWritebackInstruction(), DecodeMQPRRegisterClass(), DecodeMSRMask(), DecodeMVE_MEM_1_pre(), DecodeMVE_MEM_2_pre(), DecodeMVE_MEM_3_pre(), DecodeMveAddrModeQ(), DecodeMveAddrModeRQ(), DecodeMVEModImmInstruction(), DecodeMVEPairVectorIndexOperand(), DecodeMVEVADCInstruction(), DecodeMVEVCVTt1fp(), DecodeMVEVMOVDRegtoQ(), DecodeMVEVMOVQtoDReg(), DecodeNEONComplexLane64Instruction(), DecodePostIdxReg(), DecodePowerTwoOperand(), DecodePredicateOperand(), DecodePredNoALOperand(), DecodeQADDInstruction(), DecodeQPRRegisterClass(), DecodeQQPRRegisterClass(), DecodeQQQQPRRegisterClass(), DecodeRegListOperand(), DecodeRestrictedFPPredicateOperand(), DecodeRestrictedIPredicateOperand(), DecodeRestrictedSPredicateOperand(), DecodeRestrictedUPredicateOperand(), DecoderForMRRC2AndMCRR2(), DecoderGPRRegisterClass(), DecodeSETPANInstruction(), DecodeShiftRight16Imm(), DecodeShiftRight32Imm(), DecodeShiftRight64Imm(), DecodeShiftRight8Imm(), DecodeSMLAInstruction(), DecodeSORegImmOperand(), DecodeSORegMemOperand(), DecodeSORegRegOperand(), DecodeSPR_8RegisterClass(), DecodeSPRRegisterClass(), DecodeSPRRegListOperand(), DecodeSTRPreImm(), DecodeSTRPreReg(), DecodeSwap(), DecodeT2AddrModeImm0_1020s4(), DecodeT2AddrModeImm12(), DecodeT2AddrModeImm7(), DecodeT2AddrModeImm7s4(), DecodeT2AddrModeImm8(), DecodeT2AddrModeImm8s4(), DecodeT2AddrModeSOReg(), DecodeT2Adr(), DecodeT2BInstruction(), DecodeT2BROperand(), DecodeT2CPSInstruction(), DecodeT2Imm7(), DecodeT2Imm7S4(), DecodeT2Imm8(), DecodeT2Imm8S4(), DecodeT2LDRDPreInstruction(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeT2ShifterImmOperand(), DecodeT2SOImm(), DecodeT2STRDPreInstruction(), DecodeTAddrModeImm7(), DecodeTBLInstruction(), DecodetcGPRRegisterClass(), DecodetGPREvenRegisterClass(), DecodetGPROddRegisterClass(), DecodetGPRRegisterClass(), DecodeThumb2BCCInstruction(), DecodeThumbAddrModeIS(), DecodeThumbAddrModePC(), DecodeThumbAddrModeRR(), DecodeThumbAddrModeSP(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPImm(), DecodeThumbAddSPReg(), DecodeThumbBCCTargetOperand(), DecodeThumbBLTargetOperand(), DecodeThumbBLXOffset(), DecodeThumbBROperand(), DecodeThumbCmpBROperand(), DecodeThumbCPS(), DecodeThumbTableBranch(), DecodeTSTInstruction(), DecodeVCVTD(), DecodeVCVTImmOperand(), DecodeVCVTQ(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVLDST1Instruction(), DecodeVLDST2Instruction(), DecodeVLDST3Instruction(), DecodeVLDST4Instruction(), DecodeVMOVModImmInstruction(), DecodeVMOVRRS(), DecodeVMOVSRR(), DecodeVpredROperand(), DecodeVPTMaskOperand(), DecodeVSCCLRM(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), DecodeVSTInstruction(), DecodeVSTRVLDR_SYSREG(), llvm::MCDisassembler::Fail, llvm::tgtok::In, llvm_unreachable, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddrMode5FP16Operand(), DecodeAddrMode5Operand(), DecodeAddrMode6Operand(), DecodeAddrModeImm12Operand(), DecodeArmMOVTWInstruction(), DecodeBitfieldMaskOperand(), DecodeBranchImmInstruction(), DecodeCopMemInstruction(), DecodeDoubleRegLoad(), DecodeDoubleRegStore(), DecodeDPRRegListOperand(), DecodeForVMRSandVMSR(), DecodeGPRnopcRegisterClass(), DecodeGPRwithAPSRRegisterClass(), DecodeGPRwithZRnospRegisterClass(), DecodeGPRwithZRRegisterClass(), DecodeHINTInstruction(), DecodeLDRPreImm(), DecodeLDRPreReg(), DecodeLOLoop(), DecodeMemMultipleWritebackInstruction(), DecodeMVE_MEM_pre(), DecodeMveAddrModeQ(), DecodeMveAddrModeRQ(), DecodeMVEModImmInstruction(), DecodeMVEOverlappingLongShift(), DecodeMVEVADCInstruction(), DecodeMVEVCMP(), DecodeMveVCTP(), DecodeMVEVCVTt1fp(), DecodeMVEVMOVDRegtoQ(), DecodeMVEVMOVQtoDReg(), DecodeNEONComplexLane64Instruction(), DecodePostIdxReg(), DecodePredicateOperand(), DecodeQADDInstruction(), DecodeRegListOperand(), DecodeRFEInstruction(), DecoderForMRRC2AndMCRR2(), DecoderGPRRegisterClass(), DecodeSMLAInstruction(), DecodeSORegImmOperand(), DecodeSORegMemOperand(), DecodeSORegRegOperand(), DecodeSPRRegListOperand(), DecodeSTRPreImm(), DecodeSTRPreReg(), DecodeSwap(), DecodeT2AddrModeImm0_1020s4(), DecodeT2AddrModeImm12(), DecodeT2AddrModeImm7(), DecodeT2AddrModeImm7s4(), DecodeT2AddrModeImm8(), DecodeT2AddrModeImm8s4(), DecodeT2AddrModeSOReg(), DecodeT2AddSubSPImm(), DecodeT2LDRDPreInstruction(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeT2STRDPreInstruction(), DecodeTAddrModeImm7(), DecodeTBLInstruction(), DecodeThumb2BCCInstruction(), DecodeThumbAddrModeIS(), DecodeThumbAddrModeRR(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPReg(), DecodeThumbTableBranch(), DecodeTSTInstruction(), DecodeVCVTD(), DecodeVCVTQ(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVMOVModImmInstruction(), DecodeVMOVRRS(), DecodeVMOVSRR(), DecodeVSCCLRM(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), DecodeVSTInstruction(), DecodeVSTRVLDR_SYSREG(), and isVectorPredicable().
checkDecodedInstruction()
static DecodeStatus checkDecodedInstruction (MCInst & MI, uint64_t & Size, uint64_t Address, raw_ostream & CS, uint32_t Insn, DecodeStatus Result) static
Definition at line 581 of file ARMDisassembler.cpp.
References llvm::MCInst::getOpcode().
Referenced by isVectorPredicable().
createARMDisassembler()
static MCDisassembler* createARMDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 574 of file ARMDisassembler.cpp.
Referenced by LLVMInitializeARMDisassembler().
DecodeAddrMode2IdxInstruction()
static DecodeStatus DecodeAddrMode2IdxInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1823 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRnopcRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::ARM_AM::getAM2Opc(), llvm::MCInst::getOpcode(), llvm::ARMII::IndexModePost, llvm::ARMII::IndexModePre, llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, P, pred, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, llvm::MCDisassembler::SoftFail, llvm::ARM_AM::sub, llvm::MCDisassembler::Success, and llvm::RISCVFenceField::W.
Referenced by Check().
DecodeAddrMode3Instruction()
static DecodeStatus DecodeAddrMode3Instruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1972 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::ARMII::IndexModePost, llvm::ARMII::IndexModePre, P, pred, llvm::MCDisassembler::SoftFail, llvm::MCDisassembler::Success, and llvm::RISCVFenceField::W.
Referenced by Check().
DecodeAddrMode5FP16Operand()
static DecodeStatus DecodeAddrMode5FP16Operand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2586 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::ARM_AM::getAM5FP16Opc(), llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeAddrMode5Operand()
static DecodeStatus DecodeAddrMode5Operand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2566 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::ARM_AM::getAM5Opc(), llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeAddrMode6Operand()
static DecodeStatus DecodeAddrMode6Operand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2664 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeVLDInstruction(), and DecodeVSTInstruction().
DecodeAddrMode7Operand()
static DecodeStatus DecodeAddrMode7Operand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2606 of file ARMDisassembler.cpp.
References DecodeGPRRegisterClass().
Referenced by Check().
DecodeAddrModeImm12Operand()
static DecodeStatus DecodeAddrModeImm12Operand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2546 of file ARMDisassembler.cpp.
References add(), llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::Success, and tryAddingPcLoadReferenceComment().
Referenced by Check(), DecodeLDRPreImm(), and DecodeSTRPreImm().
DecodeArmMOVTWInstruction()
static DecodeStatus DecodeArmMOVTWInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2442 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), pred, llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeBankedReg()
static DecodeStatus DecodeBankedReg (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4732 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeBFAfterTargetOperand()
static DecodeStatus DecodeBFAfterTargetOperand (MCInst & Inst, unsigned val, uint64_t Address, const void * Decoder) static
Definition at line 5955 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeBFLabelOperand()
template<bool isSigned, bool isNeg, bool zeroPermitted, int size> static DecodeStatus DecodeBFLabelOperand (MCInst & Inst, unsigned val, uint64_t Address, const void * Decoder) static
Definition at line 5936 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeBitfieldMaskOperand()
static DecodeStatus DecodeBitfieldMaskOperand (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1617 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeBranchImmInstruction()
static DecodeStatus DecodeBranchImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2639 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCInst::setOpcode(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeCCOutOperand()
static DecodeStatus DecodeCCOutOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 1440 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2AddSubSPImm().
DecodeCLRMGPRRegisterClass()
static DecodeStatus DecodeCLRMGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1137 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeRegListOperand().
DecodeCopMemInstruction()
static DecodeStatus DecodeCopMemInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1644 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::ARM_AM::getAM5Opc(), llvm::MCInst::getOpcode(), LLVM_FALLTHROUGH, pred, llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeCoprocessor()
static DecodeStatus DecodeCoprocessor (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4494 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::isValidCoprocessorNumber(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeCPSInstruction()
static DecodeStatus DecodeCPSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2329 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, mode, llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeQADDInstruction(), DecodeSMLAInstruction(), and DecodeSwap().
DecodeDoubleRegLoad()
static DecodeStatus DecodeDoubleRegLoad (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4747 of file ARMDisassembler.cpp.
References Check(), DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeDoubleRegStore()
static DecodeStatus DecodeDoubleRegStore (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4768 of file ARMDisassembler.cpp.
References Check(), DecodeGPRnopcRegisterClass(), DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeDPairRegisterClass()
static DecodeStatus DecodeDPairRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1390 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeTBLInstruction(), DecodeVLD1DupInstruction(), DecodeVLD2DupInstruction(), DecodeVLDInstruction(), and DecodeVSTInstruction().
DecodeDPairSpacedRegisterClass()
static DecodeStatus DecodeDPairSpacedRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1411 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeVLD2DupInstruction(), DecodeVLDInstruction(), and DecodeVSTInstruction().
DecodeDPR_8RegisterClass()
static DecodeStatus DecodeDPR_8RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1341 of file ARMDisassembler.cpp.
References DecodeDPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by Check().
DecodeDPR_VFP2RegisterClass()
static DecodeStatus DecodeDPR_VFP2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1356 of file ARMDisassembler.cpp.
References DecodeDPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by Check().
DecodeDPRRegisterClass()
static DecodeStatus DecodeDPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1326 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeDPR_8RegisterClass(), DecodeDPR_VFP2RegisterClass(), DecodeDPRRegListOperand(), DecodeNEONComplexLane64Instruction(), DecodeTBLInstruction(), DecodeVCVTD(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVMOVModImmInstruction(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), and DecodeVSTInstruction().
DecodeDPRRegListOperand()
static DecodeStatus DecodeDPRRegListOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 1592 of file ARMDisassembler.cpp.
References Check(), DecodeDPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::max(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeVSCCLRM().
DecodeExpandedImmOperand()
template<int shift> static DecodeStatus DecodeExpandedImmOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6399 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeForVMRSandVMSR()
static DecodeStatus DecodeForVMRSandVMSR (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 5884 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRnopcRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::ARMISD::FMSTAT, llvm::MCInst::getOpcode(), pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeGPRnopcRegisterClass()
static DecodeStatus DecodeGPRnopcRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1152 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeAddrMode2IdxInstruction(), DecodeArmMOVTWInstruction(), DecodeDoubleRegStore(), DecodeForVMRSandVMSR(), DecodeMveAddrModeRQ(), DecodePostIdxReg(), DecodeQADDInstruction(), DecoderForMRRC2AndMCRR2(), DecodeSMLAInstruction(), DecodeSORegRegOperand(), DecodeSwap(), DecodeT2AddrModeImm0_1020s4(), DecodeT2AddrModeImm7(), DecodeT2AddrModeImm7s4(), and DecodeVSTRVLDR_SYSREG().
DecodeGPRPairRegisterClass()
static DecodeStatus DecodeGPRPairRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1219 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeDoubleRegLoad(), and DecodeDoubleRegStore().
DecodeGPRRegisterClass()
static DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1127 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddrMode5FP16Operand(), DecodeAddrMode5Operand(), DecodeAddrMode6Operand(), DecodeAddrMode7Operand(), DecodeAddrModeImm12Operand(), DecodeCopMemInstruction(), DecodeDoubleRegLoad(), DecodeDoubleRegStore(), DecodeForVMRSandVMSR(), DecodeGPRnopcRegisterClass(), DecodeGPRwithAPSRRegisterClass(), DecodeGPRwithZRRegisterClass(), DecodeLDRPreImm(), DecodeLDRPreReg(), DecodeMemMultipleWritebackInstruction(), DecodeMVEVMOVDRegtoQ(), DecodeMVEVMOVQtoDReg(), DecodeRegListOperand(), DecodeRFEInstruction(), DecoderGPRRegisterClass(), DecodeSORegMemOperand(), DecodeSTRPreImm(), DecodeSTRPreReg(), DecodeT2AddrModeImm12(), DecodeT2AddrModeImm8(), DecodeT2AddrModeImm8s4(), DecodeT2AddrModeSOReg(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodetGPRRegisterClass(), DecodeThumbAddSPReg(), DecodeThumbTableBranch(), DecodeTSTInstruction(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVMOVRRS(), DecodeVMOVSRR(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), and DecodeVSTInstruction().
DecodeGPRspRegisterClass()
static DecodeStatus DecodeGPRspRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1234 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2AddSubSPImm().
DecodeGPRwithAPSRRegisterClass()
static DecodeStatus DecodeGPRwithAPSRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1165 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeGPRwithZRnospRegisterClass()
static DecodeStatus DecodeGPRwithZRnospRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1198 of file ARMDisassembler.cpp.
References Check(), DecodeGPRwithZRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeGPRwithZRRegisterClass()
static DecodeStatus DecodeGPRwithZRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1180 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeGPRwithZRnospRegisterClass(), and DecodeMVEVCMP().
DecodeHINTInstruction()
static DecodeStatus DecodeHINTInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2307 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeHPRRegisterClass()
static DecodeStatus DecodeHPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1310 of file ARMDisassembler.cpp.
References DecodeSPRRegisterClass().
Referenced by Check().
DecodeInstSyncBarrierOption()
static DecodeStatus DecodeInstSyncBarrierOption (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4641 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeIT()
static DecodeStatus DecodeIT (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 5496 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeLDR()
static DecodeStatus DecodeLDR (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 5812 of file ARMDisassembler.cpp.
References llvm::MCDisassembler::Success.
Referenced by Check().
DecodeLDRPreImm()
static DecodeStatus DecodeLDRPreImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4794 of file ARMDisassembler.cpp.
References Check(), DecodeAddrModeImm12Operand(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeLDRPreReg()
static DecodeStatus DecodeLDRPreReg (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4819 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSORegMemOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeLOLoop()
static DecodeStatus DecodeLOLoop (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5976 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createReg(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), LLVM_FALLTHROUGH, llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeLongShiftOperand()
static DecodeStatus DecodeLongShiftOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6038 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMemBarrierOption()
static DecodeStatus DecodeMemBarrierOption (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4632 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeThumb2BCCInstruction().
DecodeMemMultipleWritebackInstruction()
static DecodeStatus DecodeMemMultipleWritebackInstruction (MCInst & Inst, unsigned Insn, uint64_t Adddress, const void * Decoder) static
Definition at line 2215 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeRegListOperand(), DecodeRFEInstruction(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), pred, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMQPRRegisterClass()
static DecodeStatus DecodeMQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 6097 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeMVE_MEM_3_pre(), DecodeMVE_MEM_pre(), DecodeMveAddrModeQ(), DecodeMveAddrModeRQ(), DecodeMVEModImmInstruction(), DecodeMVEVADCInstruction(), DecodeMVEVCMP(), DecodeMVEVCVTt1fp(), DecodeMVEVMOVDRegtoQ(), and DecodeMVEVMOVQtoDReg().
DecodeMSRMask()
static DecodeStatus DecodeMSRMask (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4650 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), LLVM_FALLTHROUGH, llvm::BitmaskEnumDetail::Mask(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVE_MEM_1_pre()
template<int shift> static DecodeStatus DecodeMVE_MEM_1_pre (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6359 of file ARMDisassembler.cpp.
References DecodeMVE_MEM_pre(), and DecodetGPRRegisterClass().
Referenced by Check().
DecodeMVE_MEM_2_pre()
template<int shift> static DecodeStatus DecodeMVE_MEM_2_pre (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6368 of file ARMDisassembler.cpp.
References DecodeMVE_MEM_pre(), and DecoderGPRRegisterClass().
Referenced by Check().
DecodeMVE_MEM_3_pre()
template<int shift> static DecodeStatus DecodeMVE_MEM_3_pre (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6377 of file ARMDisassembler.cpp.
References DecodeMQPRRegisterClass(), and DecodeMVE_MEM_pre().
Referenced by Check().
DecodeMVE_MEM_pre()
static DecodeStatus DecodeMVE_MEM_pre (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder, unsigned Rn, OperandDecoder RnDecoder, OperandDecoder AddrDecoder) inline static
Definition at line 6339 of file ARMDisassembler.cpp.
References Check(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by DecodeMVE_MEM_1_pre(), DecodeMVE_MEM_2_pre(), and DecodeMVE_MEM_3_pre().
DecodeMveAddrModeQ()
template<int shift> static DecodeStatus DecodeMveAddrModeQ (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4448 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMveAddrModeRQ()
static DecodeStatus DecodeMveAddrModeRQ (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4433 of file ARMDisassembler.cpp.
References Check(), DecodeGPRnopcRegisterClass(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVEModImmInstruction()
static DecodeStatus DecodeMVEModImmInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3507 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::ARMVCC::None, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVEOverlappingLongShift()
static DecodeStatus DecodeMVEOverlappingLongShift (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6467 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecoderGPRRegisterClass(), DecodetGPREvenRegisterClass(), DecodetGPROddRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm_unreachable, llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeMVEPairVectorIndexOperand()
template<unsigned start> static DecodeStatus DecodeMVEPairVectorIndexOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6409 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVEVADCInstruction()
static DecodeStatus DecodeMVEVADCInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 3535 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVEVCMP()
template<bool scalar, OperandDecoder predicate_decoder> static DecodeStatus DecodeMVEVCMP (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6566 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRwithZRRegisterClass(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::ARMVCC::None, and llvm::MCDisassembler::Success.
DecodeMveVCTP()
static DecodeStatus DecodeMveVCTP (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6603 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createReg(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeMVEVCVTt1fp()
static DecodeStatus DecodeMVEVCVTt1fp (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6546 of file ARMDisassembler.cpp.
References Check(), DecodeMQPRRegisterClass(), DecodeVCVTImmOperand(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVEVMOVDRegtoQ()
static DecodeStatus DecodeMVEVMOVDRegtoQ (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6442 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVEVMOVQtoDReg()
static DecodeStatus DecodeMVEVMOVQtoDReg (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6419 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeMVEVPNOT()
static DecodeStatus DecodeMVEVPNOT (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6613 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
DecodeNEONComplexLane64Instruction()
static DecodeStatus DecodeNEONComplexLane64Instruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 5779 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodeQPRRegisterClass(), llvm::MCDisassembler::Fail, rotate, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodePostIdxReg()
static DecodeStatus DecodePostIdxReg (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4420 of file ARMDisassembler.cpp.
References add(), llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodePowerTwoOperand()
template<unsigned MinLog, unsigned MaxLog> static DecodeStatus DecodePowerTwoOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6386 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodePredicateOperand()
static DecodeStatus DecodePredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 1423 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, llvm::ARMInsts, Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInstrDesc::isPredicable(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeArmMOVTWInstruction(), DecodeBranchImmInstruction(), DecodeCopMemInstruction(), DecodeDoubleRegLoad(), DecodeDoubleRegStore(), DecodeForVMRSandVMSR(), DecodeHINTInstruction(), DecodeLDRPreImm(), DecodeLDRPreReg(), DecodeMemMultipleWritebackInstruction(), DecodeQADDInstruction(), DecodeSMLAInstruction(), DecodeSTRPreImm(), DecodeSTRPreReg(), DecodeSwap(), DecodeThumb2BCCInstruction(), DecodeTSTInstruction(), DecodeVMOVRRS(), and DecodeVMOVSRR().
DecodePredNoALOperand()
static DecodeStatus DecodePredNoALOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 5967 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeQADDInstruction()
static DecodeStatus DecodeQADDInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2192 of file ARMDisassembler.cpp.
References Check(), DecodeCPSInstruction(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeQPRRegisterClass()
static DecodeStatus DecodeQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1370 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeNEONComplexLane64Instruction(), DecodeVCVTQ(), DecodeVMOVModImmInstruction(), and DecodeVSHLMaxInstruction().
DecodeQQPRRegisterClass()
static DecodeStatus DecodeQQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 6113 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeQQQQPRRegisterClass()
static DecodeStatus DecodeQQQQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 6129 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeRegListOperand()
static DecodeStatus DecodeRegListOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 1521 of file ARMDisassembler.cpp.
References Check(), DecodeCLRMGPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCInst::end(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeMemMultipleWritebackInstruction().
DecodeRestrictedFPPredicateOperand()
static DecodeStatus DecodeRestrictedFPPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6222 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::EQ, llvm::MCDisassembler::Fail, llvm::ARMCC::GE, llvm::ARMCC::GT, llvm::ARMCC::LE, llvm::ARMCC::LT, llvm::ARMCC::NE, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeRestrictedIPredicateOperand()
static DecodeStatus DecodeRestrictedIPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6183 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::EQ, llvm::ARMCC::NE, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeRestrictedSPredicateOperand()
static DecodeStatus DecodeRestrictedSPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6191 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::GE, llvm::ARMCC::GT, llvm::ARMCC::LE, llvm::ARMCC::LT, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeRestrictedUPredicateOperand()
static DecodeStatus DecodeRestrictedUPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6214 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::HI, llvm::ARMCC::HS, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeRFEInstruction()
static DecodeStatus DecodeRFEInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2163 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::ARM_AM::da, llvm::ARM_AM::db, DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::ARM_AM::ia, llvm::ARM_AM::ib, mode, and llvm::MCDisassembler::Success.
Referenced by DecodeMemMultipleWritebackInstruction().
DecoderForMRRC2AndMCRR2()
static DecodeStatus DecoderForMRRC2AndMCRR2 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 5839 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecoderGPRRegisterClass()
static DecodeStatus DecoderGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1275 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeLOLoop(), DecodeMVE_MEM_2_pre(), DecodeMVEOverlappingLongShift(), DecodeMveVCTP(), DecodeSORegImmOperand(), DecodeT2AddrModeImm7(), DecodeT2AddrModeSOReg(), DecodeT2Adr(), DecodeT2LDRDPreInstruction(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeT2STRDPreInstruction(), and DecodeThumbTableBranch().
DecodeSETPANInstruction()
static DecodeStatus DecodeSETPANInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2518 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeTSTInstruction().
DecodeShiftRight16Imm()
static DecodeStatus DecodeShiftRight16Imm (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3585 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeShiftRight32Imm()
static DecodeStatus DecodeShiftRight32Imm (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3591 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeShiftRight64Imm()
static DecodeStatus DecodeShiftRight64Imm (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3597 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeShiftRight8Imm()
static DecodeStatus DecodeShiftRight8Imm (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3579 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeSMLAInstruction()
static DecodeStatus DecodeSMLAInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2469 of file ARMDisassembler.cpp.
References Check(), DecodeCPSInstruction(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeSORegImmOperand()
static DecodeStatus DecodeSORegImmOperand (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1449 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check(), llvm::MCOperand::createImm(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeSORegMemOperand()
static DecodeStatus DecodeSORegMemOperand (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1928 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::ARM_AM::getAM2Opc(), llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeLDRPreReg(), and DecodeSTRPreReg().
DecodeSORegRegOperand()
static DecodeStatus DecodeSORegRegOperand (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1486 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check(), llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARM_AM::ror, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeSPR_8RegisterClass()
static DecodeStatus DecodeSPR_8RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1348 of file ARMDisassembler.cpp.
References DecodeSPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by Check().
DecodeSPRRegisterClass()
static DecodeStatus DecodeSPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1300 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeHPRRegisterClass(), DecodeSPR_8RegisterClass(), DecodeSPRRegListOperand(), DecodeVMOVRRS(), and DecodeVMOVSRR().
DecodeSPRRegListOperand()
static DecodeStatus DecodeSPRRegListOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 1568 of file ARMDisassembler.cpp.
References Check(), DecodeSPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::max(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeVSCCLRM().
DecodeSTRPreImm()
static DecodeStatus DecodeSTRPreImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4846 of file ARMDisassembler.cpp.
References Check(), DecodeAddrModeImm12Operand(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeSTRPreReg()
static DecodeStatus DecodeSTRPreReg (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4871 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSORegMemOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeSwap()
static DecodeStatus DecodeSwap (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5634 of file ARMDisassembler.cpp.
References Check(), DecodeCPSInstruction(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2AddrModeImm0_1020s4()
static DecodeStatus DecodeT2AddrModeImm0_1020s4 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4162 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2AddrModeImm12()
static DecodeStatus DecodeT2AddrModeImm12 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4347 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2LoadImm12().
DecodeT2AddrModeImm7()
template<int shift, int WriteBack> static DecodeStatus DecodeT2AddrModeImm7 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4268 of file ARMDisassembler.cpp.
References Check(), DecodeGPRnopcRegisterClass(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2AddrModeImm7s4()
static DecodeStatus DecodeT2AddrModeImm7s4 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4146 of file ARMDisassembler.cpp.
References Check(), DecodeGPRnopcRegisterClass(), DecodeT2Imm7S4(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeVSTRVLDR_SYSREG().
DecodeT2AddrModeImm8()
static DecodeStatus DecodeT2AddrModeImm8 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4204 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodeT2Imm8(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeT2LdStPre(), DecodeT2LoadImm8(), and DecodeT2LoadT().
DecodeT2AddrModeImm8s4()
static DecodeStatus DecodeT2AddrModeImm8s4 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4131 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodeT2Imm8S4(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeT2LDRDPreInstruction(), and DecodeT2STRDPreInstruction().
DecodeT2AddrModeSOReg()
static DecodeStatus DecodeT2AddrModeSOReg (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3734 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2LoadShift().
DecodeT2AddSubSPImm()
static DecodeStatus DecodeT2AddSubSPImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6621 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeCCOutOperand(), DecodeGPRspRegisterClass(), DecodeT2SOImm(), llvm::SIInstrFlags::DS, llvm::MCDisassembler::Fail, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2Adr() [1/2]
static DecodeStatus DecodeT2Adr (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Referenced by Check().
DecodeT2Adr() [2/2]
static DecodeStatus DecodeT2Adr (MCInst & Inst, uint32_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 5597 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getNumOperands(), and llvm::MCInst::setOpcode().
DecodeT2BInstruction()
static DecodeStatus DecodeT2BInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2612 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeT2BROperand()
static DecodeStatus DecodeT2BROperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3671 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check(), and DecodeThumb2BCCInstruction().
DecodeT2CPSInstruction()
static DecodeStatus DecodeT2CPSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2376 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, mode, llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2Imm7()
template<int shift> static DecodeStatus DecodeT2Imm7 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4190 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2Imm7S4()
static DecodeStatus DecodeT2Imm7S4 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4116 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2AddrModeImm7s4().
DecodeT2Imm8()
static DecodeStatus DecodeT2Imm8 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4177 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2AddrModeImm8().
DecodeT2Imm8S4()
static DecodeStatus DecodeT2Imm8S4 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4102 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2AddrModeImm8s4().
DecodeT2LDRDPreInstruction()
static DecodeStatus DecodeT2LDRDPreInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5526 of file ARMDisassembler.cpp.
References Check(), DecoderGPRRegisterClass(), DecodeT2AddrModeImm8s4(), llvm::MCDisassembler::Fail, P, llvm::MCDisassembler::SoftFail, llvm::MCDisassembler::Success, and llvm::RISCVFenceField::W.
Referenced by Check().
DecodeT2LdStPre()
static DecodeStatus DecodeT2LdStPre (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4286 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodeT2AddrModeImm8(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2LoadImm12()
static DecodeStatus DecodeT2LoadImm12 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 3930 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodeT2AddrModeImm12(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2LoadImm8()
static DecodeStatus DecodeT2LoadImm8 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 3846 of file ARMDisassembler.cpp.
References add(), Check(), DecodeGPRRegisterClass(), DecodeT2AddrModeImm8(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2LoadLabel()
static DecodeStatus DecodeT2LoadLabel (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4049 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadShift(), and DecodeT2LoadT().
DecodeT2LoadShift()
static DecodeStatus DecodeT2LoadShift (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3763 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodeT2AddrModeSOReg(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2LoadT()
static DecodeStatus DecodeT2LoadT (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4010 of file ARMDisassembler.cpp.
References Check(), DecoderGPRRegisterClass(), DecodeT2AddrModeImm8(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeT2MOVTWInstruction()
static DecodeStatus DecodeT2MOVTWInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2418 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeT2ShifterImmOperand() [1/2]
static DecodeStatus DecodeT2ShifterImmOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Referenced by Check().
DecodeT2ShifterImmOperand() [2/2]
static DecodeStatus DecodeT2ShifterImmOperand (MCInst & Inst, uint32_t Val, uint64_t Address, const void * Decoder) static
Definition at line 5623 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeT2SOImm()
static DecodeStatus DecodeT2SOImm (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4568 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeT2AddSubSPImm().
DecodeT2STRDPreInstruction()
static DecodeStatus DecodeT2STRDPreInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5563 of file ARMDisassembler.cpp.
References Check(), DecoderGPRRegisterClass(), DecodeT2AddrModeImm8s4(), llvm::MCDisassembler::Fail, P, llvm::MCDisassembler::SoftFail, llvm::MCDisassembler::Success, and llvm::RISCVFenceField::W.
Referenced by Check().
DecodeTAddrModeImm7()
template<int shift> static DecodeStatus DecodeTAddrModeImm7 (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4251 of file ARMDisassembler.cpp.
References Check(), DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeTBLInstruction()
static DecodeStatus DecodeTBLInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 3603 of file ARMDisassembler.cpp.
References Check(), DecodeDPairRegisterClass(), DecodeDPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), op, llvm::MCDisassembler::Success, and llvm::ARMISD::VTBL2.
Referenced by Check().
DecodetcGPRRegisterClass()
static DecodeStatus DecodetcGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1245 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, R2, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodetGPREvenRegisterClass()
static DecodeStatus DecodetGPREvenRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 6061 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeMVEOverlappingLongShift().
DecodetGPROddRegisterClass()
static DecodeStatus DecodetGPROddRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 6051 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeMVEOverlappingLongShift().
DecodetGPRRegisterClass()
static DecodeStatus DecodetGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1207 of file ARMDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by Check(), DecodeMVE_MEM_1_pre(), DecodeTAddrModeImm7(), DecodeThumbAddrModeIS(), DecodeThumbAddrModeRR(), and DecodeThumbAddSpecialReg().
DecodeThumb2BCCInstruction()
static DecodeStatus DecodeThumb2BCCInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4526 of file ARMDisassembler.cpp.
References Check(), DecodeMemBarrierOption(), DecodePredicateOperand(), DecodeT2BROperand(), llvm::MCDisassembler::Fail, pred, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbAddrModeIS()
static DecodeStatus DecodeThumbAddrModeIS (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3702 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbAddrModePC()
static DecodeStatus DecodeThumbAddrModePC (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3716 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingPcLoadReferenceComment().
Referenced by Check().
DecodeThumbAddrModeRR()
static DecodeStatus DecodeThumbAddrModeRR (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3687 of file ARMDisassembler.cpp.
References Check(), DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbAddrModeSP()
static DecodeStatus DecodeThumbAddrModeSP (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3726 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbAddSpecialReg()
static DecodeStatus DecodeThumbAddSpecialReg (MCInst & Inst, uint16_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 3639 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbAddSPImm()
static DecodeStatus DecodeThumbAddSPImm (MCInst & Inst, uint16_t Val, uint64_t Address, const void * Decoder) static
Definition at line 4373 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbAddSPReg()
static DecodeStatus DecodeThumbAddSPReg (MCInst & Inst, uint16_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 4384 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbBCCTargetOperand()
static DecodeStatus DecodeThumbBCCTargetOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4600 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeThumbBLTargetOperand()
static DecodeStatus DecodeThumbBLTargetOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4608 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeThumbBLXOffset()
static DecodeStatus DecodeThumbBLXOffset (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4470 of file ARMDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeThumbBROperand()
static DecodeStatus DecodeThumbBROperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3663 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeThumbCmpBROperand()
static DecodeStatus DecodeThumbCmpBROperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3679 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by Check().
DecodeThumbCPS()
static DecodeStatus DecodeThumbCPS (MCInst & Inst, uint16_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 4409 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeThumbTableBranch()
static DecodeStatus DecodeThumbTableBranch (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 4510 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeTSTInstruction()
static DecodeStatus DecodeTSTInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 2497 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSETPANInstruction(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVCVTD()
static DecodeStatus DecodeVCVTD (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5661 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodeVMOVModImmInstruction(), llvm::MCDisassembler::Fail, op, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVCVTImmOperand()
static DecodeStatus DecodeVCVTImmOperand (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6253 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check(), and DecodeMVEVCVTt1fp().
DecodeVCVTQ()
static DecodeStatus DecodeVCVTQ (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5720 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeQPRRegisterClass(), DecodeVMOVModImmInstruction(), llvm::MCDisassembler::Fail, op, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD1DupInstruction()
static DecodeStatus DecodeVLD1DupInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3278 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeDPairRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD1LN()
static DecodeStatus DecodeVLD1LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4896 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD2DupInstruction()
static DecodeStatus DecodeVLD2DupInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3325 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD2LN()
static DecodeStatus DecodeVLD2LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5028 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD3DupInstruction()
static DecodeStatus DecodeVLD3DupInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3373 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD3LN()
static DecodeStatus DecodeVLD3LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5158 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD4DupInstruction()
static DecodeStatus DecodeVLD4DupInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3408 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLD4LN()
static DecodeStatus DecodeVLD4LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5291 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVLDInstruction()
static DecodeStatus DecodeVLDInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2681 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeAddrMode6Operand(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), LLVM_FALLTHROUGH, and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeVLDST1Instruction(), DecodeVLDST2Instruction(), DecodeVLDST3Instruction(), and DecodeVLDST4Instruction().
DecodeVLDST1Instruction()
static DecodeStatus DecodeVLDST1Instruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2957 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), and llvm::MCDisassembler::Fail.
Referenced by Check().
DecodeVLDST2Instruction()
static DecodeStatus DecodeVLDST2Instruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2970 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), llvm::MCDisassembler::Fail, and llvm::size().
Referenced by Check().
DecodeVLDST3Instruction()
static DecodeStatus DecodeVLDST3Instruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2985 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), llvm::MCDisassembler::Fail, and llvm::size().
Referenced by Check().
DecodeVLDST4Instruction()
static DecodeStatus DecodeVLDST4Instruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 2998 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), llvm::MCDisassembler::Fail, and llvm::size().
Referenced by Check().
DecodeVMOVModImmInstruction()
static DecodeStatus DecodeVMOVModImmInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3461 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodeQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeVCVTD(), and DecodeVCVTQ().
DecodeVMOVRRS()
static DecodeStatus DecodeVMOVRRS (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5470 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSPRRegisterClass(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVMOVSRR()
static DecodeStatus DecodeVMOVSRR (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5444 of file ARMDisassembler.cpp.
References Check(), DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSPRRegisterClass(), llvm::MCDisassembler::Fail, pred, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVpredROperand()
static DecodeStatus DecodeVpredROperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6171 of file ARMDisassembler.cpp.
References llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVPTMaskOperand()
static DecodeStatus DecodeVPTMaskOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 6140 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVSCCLRM()
static DecodeStatus DecodeVSCCLRM (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6071 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegListOperand(), DecodeSPRRegListOperand(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVSHLMaxInstruction()
static DecodeStatus DecodeVSHLMaxInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3560 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodeQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVST1LN()
static DecodeStatus DecodeVST1LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 4963 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVST2LN()
static DecodeStatus DecodeVST2LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5095 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVST3LN()
static DecodeStatus DecodeVST3LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5228 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVST4LN()
static DecodeStatus DecodeVST4LN (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 5372 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::size(), and llvm::MCDisassembler::Success.
Referenced by Check().
DecodeVSTInstruction()
static DecodeStatus DecodeVSTInstruction (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 3008 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeAddrMode6Operand(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check(), DecodeVLDST1Instruction(), DecodeVLDST2Instruction(), DecodeVLDST3Instruction(), and DecodeVLDST4Instruction().
DecodeVSTRVLDR_SYSREG()
template<bool Writeback> static DecodeStatus DecodeVSTRVLDR_SYSREG (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 6296 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, Check(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRnopcRegisterClass(), DecodeT2AddrModeImm7s4(), llvm::MCDisassembler::Fail, FixedRegForVSTRVLDR_SYSREG(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by Check().
FixedRegForVSTRVLDR_SYSREG()
static unsigned FixedRegForVSTRVLDR_SYSREG (unsigned Opcode) static
Definition at line 6281 of file ARMDisassembler.cpp.
Referenced by DecodeVSTRVLDR_SYSREG().
isVectorPredicable()
static bool isVectorPredicable (unsigned Opcode) static
Definition at line 746 of file ARMDisassembler.cpp.
References llvm::Address, AddThumb1SBit(), llvm::ARMCC::AL, llvm::ARMInsts, assert(), llvm::MCInst::begin(), Check(), checkDecodedInstruction(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCInst::end(), llvm::MCDisassembler::Fail, llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), I, llvm::MCInst::insert(), llvm::isPowerOf2_32(), llvm::MCInstrDesc::isPredicable(), llvm::ARM::isVpred(), llvm::isVPTOpcode(), llvm::BitmaskEnumDetail::Mask(), llvm::ARMVCC::None, llvm::MCInstrDesc::NumOperands, llvm::ARM::OPERAND_VPRED_R, llvm::MCInstrDesc::OpInfo, Size, llvm::ArrayRef< T >::size(), llvm::MCDisassembler::SoftFail, SoftFail, Success, and llvm::MCOI::TIED_TO.
LLVMInitializeARMDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMDisassembler ()
Definition at line 1102 of file ARMDisassembler.cpp.
References createARMDisassembler(), llvm::getTheARMBETarget(), llvm::getTheARMLETarget(), llvm::getTheThumbBETarget(), llvm::getTheThumbLETarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
tryAddingPcLoadReferenceComment()
static void tryAddingPcLoadReferenceComment (uint64_t Address, int Value, const void * Decoder) static
tryAddingPcLoadReferenceComment - trys to add a comment as to what is being referenced by a load instruction with the base register that is the Pc.
These can often be values in a literal pool near the Address of the instruction. The Address of the instruction and its immediate Value are used as a possible literal pool entry. The SymbolLookUp call back will return the name of a symbol referenced by the literal pool's entry if the referenced address is that of a symbol. Or it will return a pointer to a literal 'C' string if the referenced address of the literal pool's entry is an address into a section with 'C' string literals.
Definition at line 720 of file ARMDisassembler.cpp.
References llvm::MCDisassembler::tryAddingPcLoadReferenceComment().
Referenced by DecodeAddrModeImm12Operand(), and DecodeThumbAddrModePC().
tryAddingSymbolicOperand()
static bool tryAddingSymbolicOperand (uint64_t Address, int32_t Value, bool isBranch, uint64_t InstSize, MCInst & MI, const void * Decoder) static
tryAddingSymbolicOperand - trys to add a symbolic operand in place of the immediate Value in the MCInst.
The immediate Value has had any PC adjustment made by the caller. If the instruction is a branch instruction then isBranch is true, else false. If the getOpInfo() function was set as part of the setupForSymbolicDisassembly() call then that function is called to get any symbolic information at the Address for this instruction. If that returns non-zero then the symbolic information it returns is used to create an MCExpr and that is added as an operand to the MCInst. If getOpInfo() returns zero and isBranch is true then a symbol look up for Value is done and if a symbol is found an MCExpr is created with that, else an MCExpr with Value is created. This function returns true if it adds an operand to the MCInst and false otherwise.
Definition at line 702 of file ARMDisassembler.cpp.
References llvm::MCDisassembler::tryAddingSymbolicOperand().
Referenced by DecodeArmMOVTWInstruction(), DecodeBFAfterTargetOperand(), DecodeBFLabelOperand(), DecodeBranchImmInstruction(), DecodeT2BInstruction(), DecodeT2BROperand(), DecodeT2MOVTWInstruction(), DecodeThumbBCCTargetOperand(), DecodeThumbBLTargetOperand(), DecodeThumbBLXOffset(), DecodeThumbBROperand(), and DecodeThumbCmpBROperand().
Variable Documentation
CLRMGPRDecoderTable
const uint16_t CLRMGPRDecoderTable[] static
Initial value:
= {
  ARM::R0, ARM::R1, ARM::R2, ARM::R3,
  ARM::R4, ARM::R5, ARM::R6, ARM::R7,
  ARM::R8, ARM::R9, ARM::R10, ARM::R11,
  ARM::R12, 0, ARM::LR, ARM::APSR
}
Definition at line 1120 of file ARMDisassembler.cpp.
DPairDecoderTable
const uint16_t DPairDecoderTable[] static
Initial value:
= {
  ARM::Q0,  ARM::D1_D2,   ARM::Q1,  ARM::D3_D4,   ARM::Q2,  ARM::D5_D6,
  ARM::Q3,  ARM::D7_D8,   ARM::Q4,  ARM::D9_D10,  ARM::Q5,  ARM::D11_D12,
  ARM::Q6,  ARM::D13_D14, ARM::Q7,  ARM::D15_D16, ARM::Q8,  ARM::D17_D18,
  ARM::Q9,  ARM::D19_D20, ARM::Q10, ARM::D21_D22, ARM::Q11, ARM::D23_D24,
  ARM::Q12, ARM::D25_D26, ARM::Q13, ARM::D27_D28, ARM::Q14, ARM::D29_D30,
  ARM::Q15
}
Definition at line 1381 of file ARMDisassembler.cpp.
DPairSpacedDecoderTable
const uint16_t DPairSpacedDecoderTable[] static
Initial value:
= {
  ARM::D0_D2,   ARM::D1_D3,   ARM::D2_D4,   ARM::D3_D5,
  ARM::D4_D6,   ARM::D5_D7,   ARM::D6_D8,   ARM::D7_D9,
  ARM::D8_D10,  ARM::D9_D11,  ARM::D10_D12, ARM::D11_D13,
  ARM::D12_D14, ARM::D13_D15, ARM::D14_D16, ARM::D15_D17,
  ARM::D16_D18, ARM::D17_D19, ARM::D18_D20, ARM::D19_D21,
  ARM::D20_D22, ARM::D21_D23, ARM::D22_D24, ARM::D23_D25,
  ARM::D24_D26, ARM::D25_D27, ARM::D26_D28, ARM::D27_D29,
  ARM::D28_D30, ARM::D29_D31
}
Definition at line 1400 of file ARMDisassembler.cpp.
DPRDecoderTable
const uint16_t DPRDecoderTable[] static
Initial value:
= {
     ARM::D0,  ARM::D1,  ARM::D2,  ARM::D3,
     ARM::D4,  ARM::D5,  ARM::D6,  ARM::D7,
     ARM::D8,  ARM::D9, ARM::D10, ARM::D11,
    ARM::D12, ARM::D13, ARM::D14, ARM::D15,
    ARM::D16, ARM::D17, ARM::D18, ARM::D19,
    ARM::D20, ARM::D21, ARM::D22, ARM::D23,
    ARM::D24, ARM::D25, ARM::D26, ARM::D27,
    ARM::D28, ARM::D29, ARM::D30, ARM::D31
}
Definition at line 1315 of file ARMDisassembler.cpp.
GPRDecoderTable
const uint16_t GPRDecoderTable[] static
Initial value:
= {
  ARM::R0, ARM::R1, ARM::R2, ARM::R3,
  ARM::R4, ARM::R5, ARM::R6, ARM::R7,
  ARM::R8, ARM::R9, ARM::R10, ARM::R11,
  ARM::R12, ARM::SP, ARM::LR, ARM::PC
}
Definition at line 1113 of file ARMDisassembler.cpp.
GPRPairDecoderTable
const uint16_t GPRPairDecoderTable[] static
Initial value:
= {
  ARM::R0_R1, ARM::R2_R3,   ARM::R4_R5,  ARM::R6_R7,
  ARM::R8_R9, ARM::R10_R11, ARM::R12_SP
}
Definition at line 1214 of file ARMDisassembler.cpp.
QPRDecoderTable
const uint16_t QPRDecoderTable[] static
Initial value:
= {
     ARM::Q0,  ARM::Q1,  ARM::Q2,  ARM::Q3,
     ARM::Q4,  ARM::Q5,  ARM::Q6,  ARM::Q7,
     ARM::Q8,  ARM::Q9, ARM::Q10, ARM::Q11,
    ARM::Q12, ARM::Q13, ARM::Q14, ARM::Q15
}
Definition at line 1363 of file ARMDisassembler.cpp.
QQPRDecoderTable
const uint16_t QQPRDecoderTable[] static
Initial value:
= {
     ARM::Q0_Q1,  ARM::Q1_Q2,  ARM::Q2_Q3,  ARM::Q3_Q4,
     ARM::Q4_Q5,  ARM::Q5_Q6,  ARM::Q6_Q7
}
Definition at line 6108 of file ARMDisassembler.cpp.
QQQQPRDecoderTable
const uint16_t QQQQPRDecoderTable[] static
Initial value:
= {
     ARM::Q0_Q1_Q2_Q3,  ARM::Q1_Q2_Q3_Q4,  ARM::Q2_Q3_Q4_Q5,
     ARM::Q3_Q4_Q5_Q6,  ARM::Q4_Q5_Q6_Q7
}
Definition at line 6124 of file ARMDisassembler.cpp.
SPRDecoderTable
const uint16_t SPRDecoderTable[] static
Initial value:
= {
     ARM::S0,  ARM::S1,  ARM::S2,  ARM::S3,
     ARM::S4,  ARM::S5,  ARM::S6,  ARM::S7,
     ARM::S8,  ARM::S9, ARM::S10, ARM::S11,
    ARM::S12, ARM::S13, ARM::S14, ARM::S15,
    ARM::S16, ARM::S17, ARM::S18, ARM::S19,
    ARM::S20, ARM::S21, ARM::S22, ARM::S23,
    ARM::S24, ARM::S25, ARM::S26, ARM::S27,
    ARM::S28, ARM::S29, ARM::S30, ARM::S31
}
Definition at line 1289 of file ARMDisassembler.cpp.