LLVM: lib/Target/ARM/MCTargetDesc/ARMELFStreamer.cpp File Reference
ARMELFStreamer.cpp File Reference
#include "ARMRegisterInfo.h"
#include "ARMUnwindOpAsm.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Support/ARMBuildAttributes.h"
#include "llvm/Support/ARMEHABI.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <climits>
#include <cstddef>
#include <cstdint>
#include <string>
Namespaces
llvm
This class represents lattice values for constants.
Functions
static std::string GetAEABIUnwindPersonalityName (unsigned Index)
MCTargetStreamer * llvm::createARMTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
MCTargetStreamer * llvm::createARMNullTargetStreamer (MCStreamer &S)
MCTargetStreamer * llvm::createARMObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
MCELFStreamer * llvm::createARMELFStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter, bool RelaxAll, bool IsThumb, bool IsAndroid)
Function Documentation
GetAEABIUnwindPersonalityName()
static std::string GetAEABIUnwindPersonalityName (unsigned Index) static
Definition at line 61 of file ARMELFStreamer.cpp.
References llvm::ARMBuildAttrs::Advanced_SIMD_arch, llvm::ARM::EHABI::AEABI_UNWIND_CPP_PR0, llvm::ARMBuildAttrs::Allowed, llvm::ARMBuildAttrs::AllowFPARMv8A, llvm::ARMBuildAttrs::AllowFPARMv8B, llvm::ARMBuildAttrs::AllowFPv2, llvm::ARMBuildAttrs::AllowFPv3A, llvm::ARMBuildAttrs::AllowFPv3B, llvm::ARMBuildAttrs::AllowFPv4A, llvm::ARMBuildAttrs::AllowFPv4B, llvm::ARMBuildAttrs::AllowHPFP, llvm::ARMBuildAttrs::AllowNeon, llvm::ARMBuildAttrs::AllowNeon2, llvm::ARMBuildAttrs::AllowThumb32, llvm::ARMBuildAttrs::AllowThumbDerived, llvm::ARMBuildAttrs::AllowTZ, llvm::ARMBuildAttrs::AllowTZVirtualization, llvm::ARMBuildAttrs::AllowWMMXv1, llvm::ARMBuildAttrs::AllowWMMXv2, llvm::ARMBuildAttrs::ApplicationProfile, llvm::ARMBuildAttrs::ARM_ISA_use, assert(), llvm::Attribute, llvm::ARMBuildAttrs::AttrTypeAsString(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::tgtok::Bit, llvm::MCELFStreamer::ChangeSection(), llvm::SmallVectorImpl< T >::clear(), llvm::ARMBuildAttrs::compatibility, llvm::ARMBuildAttrs::conformance, Context, llvm::ARMBuildAttrs::CPU_arch, llvm::ARMBuildAttrs::CPU_arch_profile, llvm::ARMBuildAttrs::CPU_name, llvm::MCFixup::create(), llvm::MCSymbolRefExpr::create(), llvm::Data, DF, llvm::numbers::e, llvm::ELF::EF_ARM_EABI_VER5, llvm::MCELFStreamer::EmitAssemblerFlag(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCObjectStreamer::emitFill(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MCELFStreamer::EmitValueImpl(), llvm::StringRef::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ARM::EHABI::EXIDX_CANTUNWIND, F(), llvm::ARMBuildAttrs::File, llvm::ARMTargetStreamer::finishAttributeSection(), llvm::MCELFStreamer::FinishImpl(), llvm::FK_Data_4, llvm::FK_NONE, llvm::ARMBuildAttrs::FP_arch, llvm::ARMBuildAttrs::FP_HP_extension, llvm::ARM::getArchAttr(), llvm::ARM::getArchExtName(), llvm::ARM::getArchName(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::ARM::getCPUAttr(), llvm::SectionKind::getData(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), llvm::ARM::getFPUName(), llvm::MCSectionELF::getGroup(), llvm::MCFixup::getKindForSize(), llvm::MCSymbol::getName(), llvm::MCSymbol::getSection(), llvm::MCSectionELF::getSectionName(), llvm::MCSymbolRefExpr::getSymbol(), getType(), llvm::getULEB128Size(), llvm::MCSectionELF::getUniqueID(), I, llvm::ARM_PROC::IE, llvm::ARM::INVALID, llvm::MCSymbol::isDefined(), llvm::LegalityPredicates::isVector(), llvm_unreachable, llvm::StringRef::lower(), llvm::BitmaskEnumDetail::Mask(), llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, llvm::MCAF_SyntaxUnified, llvm::MCSA_ELF_TypeFunction, llvm::ARMBuildAttrs::MicroControllerProfile, llvm::ARMBuildAttrs::MPextension_use, MRI, Name, llvm::ARM::EHABI::NUM_PERSONALITY_INDEX, llvm::RISCVFenceField::O, llvm::cl::Prefix, llvm::MCExpr::print(), llvm::MCSymbol::print(), llvm::MCInstPrinter::printRegName(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ARMBuildAttrs::RealTimeProfile, Reg, llvm::report_fatal_error(), llvm::MCELFStreamer::reset(), llvm::ARMTargetStreamer::reset(), llvm::ARMBuildAttrs::Section, llvm::MCSymbol::setExternal(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHT_ARM_ATTRIBUTES, llvm::ELF::SHT_ARM_EXIDX, llvm::ELF::SHT_PROGBITS, Size, llvm::SmallVectorBase::size(), llvm::sort(), llvm::ELF::STB_LOCAL, llvm::String, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ARMBuildAttrs::Symbol, llvm::Tag, llvm::ARMBuildAttrs::THUMB_ISA_use, llvm::Twine::utohexstr(), llvm::ARMBuildAttrs::Virtualization_use, llvm::MCSymbolRefExpr::VK_ARM_NONE, llvm::MCSymbolRefExpr::VK_ARM_PREL31, llvm::MCSymbolRefExpr::VK_ARM_SBREL, and llvm::ARMBuildAttrs::WMMX_arch.