LLVM: lib/Target/ARM/ARMHazardRecognizer.cpp File Reference
ARMHazardRecognizer.cpp File Reference
#include "ARMHazardRecognizer.h"
#include "ARMBaseInstrInfo.h"
#include "ARMBaseRegisterInfo.h"
#include "ARMSubtarget.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
Functions
static bool hasRAWHazard (MachineInstr *DefMI, MachineInstr *MI, const TargetRegisterInfo &TRI)
Function Documentation
hasRAWHazard()
static bool hasRAWHazard (MachineInstr * DefMI, MachineInstr * MI, const TargetRegisterInfo & TRI) static
Definition at line 18 of file ARMHazardRecognizer.cpp.
References llvm::ARMII::DomainMask, llvm::ARMII::DomainNEON, llvm::ARMII::DomainVFP, llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::mayStore(), llvm::MachineInstr::readsRegister(), TRI, llvm::MCInstrDesc::TSFlags, and llvm::ARMISD::VMOVRRD.
Referenced by llvm::ARMHazardRecognizer::getHazardType(), and isFpMulInstruction().