LLVM: lib/Target/ARM/ARMISelLowering.cpp File Reference
ARMISelLowering.cpp File Reference
#include "ARMISelLowering.h"
#include "ARMBaseInstrInfo.h"
#include "ARMBaseRegisterInfo.h"
#include "ARMCallingConv.h"
#include "ARMConstantPoolValue.h"
#include "ARMMachineFunctionInfo.h"
#include "ARMPerfectShuffle.h"
#include "ARMRegisterInfo.h"
#include "ARMSelectionDAGInfo.h"
#include "ARMSubtarget.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "Utils/ARMBaseInfo.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/IntrinsicLowering.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSchedule.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <limits>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "arm-isel"
Typedefs
using RCPair = std::pair< unsigned, const TargetRegisterClass * >
Enumerations
enum ShuffleOpCodes {
OP_COPY = 0, OP_VREV, OP_VDUP0, OP_VDUP1,
OP_VDUP2, OP_VDUP3, OP_VEXT1, OP_VEXT2,
OP_VEXT3, OP_VUZPL, OP_VUZPR, OP_VZIPL,
OP_VZIPR, OP_VTRNL, OP_VTRNR
}
enum HABaseType {
HA_UNKNOWN = 0, HA_FLOAT, HA_DOUBLE, HA_VECT64,
HA_VECT128
}
Functions
STATISTIC (NumTailCalls, "Number of tail calls")
STATISTIC (NumMovwMovt, "Number of GAs materialized with movw + movt")
STATISTIC (NumLoopByVals, "Number of loops generated for byval arguments")
STATISTIC (NumConstpoolPromoted, "Number of constants with their storage promoted into constant pools")
static bool isSRL16 (const SDValue &Op)
static bool isSRA16 (const SDValue &Op)
static bool isSHL16 (const SDValue &Op)
static bool isS16 (const SDValue &Op, SelectionDAG &DAG)
static ARMCC::CondCodes IntCCToARMCC (ISD::CondCode CC)
IntCCToARMCC - Convert a DAG integer condition code to an ARM CC.
static void FPCCToARMCC (ISD::CondCode CC, ARMCC::CondCodes &CondCode, ARMCC::CondCodes &CondCode2)
FPCCToARMCC - Convert a DAG fp condition code to an ARM CC.
static bool MatchingStackOffset (SDValue Arg, unsigned Offset, ISD::ArgFlagsTy Flags, MachineFrameInfo &MFI, const MachineRegisterInfo *MRI, const TargetInstrInfo *TII)
MatchingStackOffset - Return true if the given stack call argument is already available in the same position (relatively) of the caller's incoming argument stack.
static SDValue LowerInterruptReturn (SmallVectorImpl< SDValue > &RetOps, const SDLoc &DL, SelectionDAG &DAG)
static SDValue LowerWRITE_REGISTER (SDValue Op, SelectionDAG &DAG)
static bool allUsersAreInFunction (const Value *V, const Function *F)
Return true if all users of V are within function F, looking through ConstantExprs.
static SDValue promoteToConstantPool (const ARMTargetLowering *TLI, const GlobalValue *GV, SelectionDAG &DAG, EVT PtrVT, const SDLoc &dl)
static SDValue LowerATOMIC_FENCE (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
static SDValue LowerPREFETCH (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
static SDValue LowerVASTART (SDValue Op, SelectionDAG &DAG)
static bool isFloatingPointZero (SDValue Op)
isFloatingPointZero - Return true if this is +0.0.
static SDValue ConvertBooleanCarryToCarryFlag (SDValue BoolCarry, SelectionDAG &DAG)
static SDValue ConvertCarryFlagToBooleanCarry (SDValue Flags, EVT VT, SelectionDAG &DAG)
static SDValue LowerSADDSUBSAT (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
static void checkVSELConstraints (ISD::CondCode CC, ARMCC::CondCodes &CondCode, bool &swpCmpOps, bool &swpVselOps)
static bool isGTorGE (ISD::CondCode CC)
static bool isLTorLE (ISD::CondCode CC)
static bool isLowerSaturate (const SDValue LHS, const SDValue RHS, const SDValue TrueVal, const SDValue FalseVal, const ISD::CondCode CC, const SDValue K)
static bool isUpperSaturate (const SDValue LHS, const SDValue RHS, const SDValue TrueVal, const SDValue FalseVal, const ISD::CondCode CC, const SDValue K)
static bool isSaturatingConditional (const SDValue &Op, SDValue &V, uint64_t &K, bool &usat)
static bool isLowerSaturatingConditional (const SDValue &Op, SDValue &V, SDValue &SatK)
static bool canChangeToInt (SDValue Op, bool &SeenZero, const ARMSubtarget *Subtarget)
canChangeToInt - Given the fp compare operand, return true if it is suitable to morph to an integer compare sequence.
static SDValue bitcastf32Toi32 (SDValue Op, SelectionDAG &DAG)
static void expandf64Toi32 (SDValue Op, SelectionDAG &DAG, SDValue &RetVal1, SDValue &RetVal2)
static SDValue LowerVectorFP_TO_INT (SDValue Op, SelectionDAG &DAG)
static SDValue LowerVectorINT_TO_FP (SDValue Op, SelectionDAG &DAG)
static void ExpandREAD_REGISTER (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG)
static SDValue CombineVMOVDRRCandidateWithVecOp (const SDNode *BC, SelectionDAG &DAG)
BC is a bitcast that is about to be turned into a VMOVDRR.
static SDValue ExpandBITCAST (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
ExpandBITCAST - If the target supports VFP, this function is called to expand a bit convert where either the source or destination type is i64 to use a VMOVDRR or VMOVRRD node.
static SDValue getZeroVector (EVT VT, SelectionDAG &DAG, const SDLoc &dl)
getZeroVector - Returns a vector of specified type with all zero elements.
static SDValue LowerCTTZ (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerCTPOP (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *ST)
static bool getVShiftImm (SDValue Op, unsigned ElementBits, int64_t &Cnt)
Getvshiftimm - Check if this is a valid build_vector for the immediate operand of a vector shift operation, where all the elements of the build_vector must have the same constant integer value.
static bool isVShiftLImm (SDValue Op, EVT VT, bool isLong, int64_t &Cnt)
isVShiftLImm - Check if this is a valid build_vector for the immediate operand of a vector shift left operation.
static bool isVShiftRImm (SDValue Op, EVT VT, bool isNarrow, bool isIntrinsic, int64_t &Cnt)
isVShiftRImm - Check if this is a valid build_vector for the immediate operand of a vector shift right operation.
static SDValue LowerShift (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue Expand64BitShift (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerVSETCC (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerSETCCCARRY (SDValue Op, SelectionDAG &DAG)
static SDValue isVMOVModifiedImm (uint64_t SplatBits, uint64_t SplatUndef, unsigned SplatBitSize, SelectionDAG &DAG, const SDLoc &dl, EVT &VT, bool is128Bits, VMOVModImmType type)
isVMOVModifiedImm - Check if the specified splat value corresponds to a valid vector constant for a NEON or MVE instruction with a "modified immediate" operand (e.g., VMOV).
static bool isSingletonVEXTMask (ArrayRef< int > M, EVT VT, unsigned &Imm)
static bool isVEXTMask (ArrayRef< int > M, EVT VT, bool &ReverseVEXT, unsigned &Imm)
static bool isVREVMask (ArrayRef< int > M, EVT VT, unsigned BlockSize)
isVREVMask - Check if a vector shuffle corresponds to a VREV instruction with the specified blocksize.
static bool isVTBLMask (ArrayRef< int > M, EVT VT)
static unsigned SelectPairHalf (unsigned Elements, ArrayRef< int > Mask, unsigned Index)
static bool isVTRNMask (ArrayRef< int > M, EVT VT, unsigned &WhichResult)
static bool isVTRN_v_undef_Mask (ArrayRef< int > M, EVT VT, unsigned &WhichResult)
isVTRN_v_undef_Mask - Special case of isVTRNMask for canonical form of "vector_shuffle v, v", i.e., "vector_shuffle v, undef".
static bool isVUZPMask (ArrayRef< int > M, EVT VT, unsigned &WhichResult)
static bool isVUZP_v_undef_Mask (ArrayRef< int > M, EVT VT, unsigned &WhichResult)
isVUZP_v_undef_Mask - Special case of isVUZPMask for canonical form of "vector_shuffle v, v", i.e., "vector_shuffle v, undef".
static bool isVZIPMask (ArrayRef< int > M, EVT VT, unsigned &WhichResult)
static bool isVZIP_v_undef_Mask (ArrayRef< int > M, EVT VT, unsigned &WhichResult)
isVZIP_v_undef_Mask - Special case of isVZIPMask for canonical form of "vector_shuffle v, v", i.e., "vector_shuffle v, undef".
static unsigned isNEONTwoResultShuffleMask (ArrayRef< int > ShuffleMask, EVT VT, unsigned &WhichResult, bool &isV_UNDEF)
Check if ShuffleMask is a NEON two-result shuffle (VZIP, VUZP, VTRN), and return the corresponding ARMISD opcode if it is, or 0 if it isn't.
static bool isReverseMask (ArrayRef< int > M, EVT VT)
static bool isVMOVNMask (ArrayRef< int > M, EVT VT, bool Top)
static SDValue IsSingleInstrConstant (SDValue N, SelectionDAG &DAG, const ARMSubtarget *ST, const SDLoc &dl)
static SDValue LowerBUILD_VECTOR_i1 (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static bool isLegalMVEShuffleOp (unsigned PFEntry)
static SDValue GeneratePerfectShuffle (unsigned PFEntry, SDValue LHS, SDValue RHS, SelectionDAG &DAG, const SDLoc &dl)
GeneratePerfectShuffle - Given an entry in the perfect-shuffle table, emit the specified operations to build the shuffle.
static SDValue LowerVECTOR_SHUFFLEv8i8 (SDValue Op, ArrayRef< int > ShuffleMask, SelectionDAG &DAG)
static SDValue LowerReverse_VECTOR_SHUFFLEv16i8_v8i16 (SDValue Op, SelectionDAG &DAG)
static EVT getVectorTyFromPredicateVector (EVT VT)
static SDValue PromoteMVEPredVector (SDLoc dl, SDValue Pred, EVT VT, SelectionDAG &DAG)
static SDValue LowerVECTOR_SHUFFLE_i1 (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerVECTOR_SHUFFLEUsingMovs (SDValue Op, ArrayRef< int > ShuffleMask, SelectionDAG &DAG)
static SDValue LowerVECTOR_SHUFFLE (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerINSERT_VECTOR_ELT_i1 (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerEXTRACT_VECTOR_ELT_i1 (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerEXTRACT_VECTOR_ELT (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerCONCAT_VECTORS_i1 (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static bool isExtendedBUILD_VECTOR (SDNode *N, SelectionDAG &DAG, bool isSigned)
isExtendedBUILD_VECTOR - Check if N is a constant BUILD_VECTOR where each element has been zero/sign-extended, depending on the isSigned parameter, from an integer type half its size.
static bool isSignExtended (SDNode *N, SelectionDAG &DAG)
isSignExtended - Check if a node is a vector value that is sign-extended or a constant BUILD_VECTOR with sign-extended elements.
static bool isZeroExtended (SDNode *N, SelectionDAG &DAG)
isZeroExtended - Check if a node is a vector value that is zero-extended or a constant BUILD_VECTOR with zero-extended elements.
static EVT getExtensionTo64Bits (const EVT &OrigVT)
static SDValue AddRequiredExtensionForVMULL (SDValue N, SelectionDAG &DAG, const EVT &OrigTy, const EVT &ExtTy, unsigned ExtOpcode)
AddRequiredExtensionForVMULL - Add a sign/zero extension to extend the total value size to 64 bits.
static SDValue SkipLoadExtensionForVMULL (LoadSDNode *LD, SelectionDAG &DAG)
SkipLoadExtensionForVMULL - return a load of the original vector size that does not do any sign/zero extension.
static SDValue SkipExtensionForVMULL (SDNode *N, SelectionDAG &DAG)
SkipExtensionForVMULL - For a node that is a SIGN_EXTEND, ZERO_EXTEND, extending load, or BUILD_VECTOR with extended elements, return the unextended value.
static bool isAddSubSExt (SDNode *N, SelectionDAG &DAG)
static bool isAddSubZExt (SDNode *N, SelectionDAG &DAG)
static SDValue LowerMUL (SDValue Op, SelectionDAG &DAG)
static SDValue LowerSDIV_v4i8 (SDValue X, SDValue Y, const SDLoc &dl, SelectionDAG &DAG)
static SDValue LowerSDIV_v4i16 (SDValue N0, SDValue N1, const SDLoc &dl, SelectionDAG &DAG)
static SDValue LowerSDIV (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerUDIV (SDValue Op, SelectionDAG &DAG, const ARMSubtarget *ST)
static SDValue LowerADDSUBCARRY (SDValue Op, SelectionDAG &DAG)
static SDValue WinDBZCheckDenominator (SelectionDAG &DAG, SDNode *N, SDValue InChain)
static SDValue LowerPredicateLoad (SDValue Op, SelectionDAG &DAG)
static SDValue LowerPredicateStore (SDValue Op, SelectionDAG &DAG)
static bool isZeroVector (SDValue N)
static SDValue LowerMLOAD (SDValue Op, SelectionDAG &DAG)
static SDValue LowerAtomicLoadStore (SDValue Op, SelectionDAG &DAG)
static void ReplaceREADCYCLECOUNTER (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
static SDValue createGPRPairNode (SelectionDAG &DAG, SDValue V)
static void ReplaceCMP_SWAP_64Results (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG)
static void ReplaceLongIntrinsic (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG)
static MachineBasicBlock * OtherSucc (MachineBasicBlock *MBB, MachineBasicBlock *Succ)
static unsigned getLdOpcode (unsigned LdSize, bool IsThumb1, bool IsThumb2)
Return the load opcode for a given load size.
static unsigned getStOpcode (unsigned StSize, bool IsThumb1, bool IsThumb2)
Return the store opcode for a given store size.
static void emitPostLd (MachineBasicBlock *BB, MachineBasicBlock::iterator Pos, const TargetInstrInfo *TII, const DebugLoc &dl, unsigned LdSize, unsigned Data, unsigned AddrIn, unsigned AddrOut, bool IsThumb1, bool IsThumb2)
Emit a post-increment load operation with given size.
static void emitPostSt (MachineBasicBlock *BB, MachineBasicBlock::iterator Pos, const TargetInstrInfo *TII, const DebugLoc &dl, unsigned StSize, unsigned Data, unsigned AddrIn, unsigned AddrOut, bool IsThumb1, bool IsThumb2)
Emit a post-increment store operation with given size.
static bool checkAndUpdateCPSRKill (MachineBasicBlock::iterator SelectItr, MachineBasicBlock *BB, const TargetRegisterInfo *TRI)
static void attachMEMCPYScratchRegs (const ARMSubtarget *Subtarget, MachineInstr &MI, const SDNode *Node)
Attaches vregs to MEMCPY that it will use as scratch registers when it is expanded into LDM/STM.
static bool isZeroOrAllOnes (SDValue N, bool AllOnes)
static bool isConditionalZeroOrAllOnes (SDNode *N, bool AllOnes, SDValue &CC, bool &Invert, SDValue &OtherOp, SelectionDAG &DAG)
static SDValue combineSelectAndUse (SDNode *N, SDValue Slct, SDValue OtherOp, TargetLowering::DAGCombinerInfo &DCI, bool AllOnes=false)
static SDValue combineSelectAndUseCommutative (SDNode *N, bool AllOnes, TargetLowering::DAGCombinerInfo &DCI)
static bool IsVUZPShuffleNode (SDNode *N)
static SDValue AddCombineToVPADD (SDNode *N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue AddCombineVUZPToVPADDL (SDNode *N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue AddCombineBUILD_VECTORToVPADDL (SDNode *N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue findMUL_LOHI (SDValue V)
static SDValue AddCombineTo64BitSMLAL16 (SDNode *AddcNode, SDNode *AddeNode, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue AddCombineTo64bitMLAL (SDNode *AddeSubeNode, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue AddCombineTo64bitUMAAL (SDNode *AddeNode, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformUMLALCombine (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
static SDValue PerformAddcSubcCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformAddeSubeCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformABSCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformADDECombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformADDECombine - Target-specific dag combine transform from ARMISD::ADDC, ARMISD::ADDE, and ISD::MUL_LOHI to MLAL or ARMISD::ADDC, ARMISD::ADDE and ARMISD::UMLAL to ARMISD::UMAAL.
static SDValue PerformADDCombineWithOperands (SDNode *N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformADDCombineWithOperands - Try DAG combinations for an ADD with operands N0 and N1.
static SDValue PerformSHLSimplify (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *ST)
static SDValue PerformADDCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformADDCombine - Target-specific dag combine xforms for ISD::ADD.
static SDValue PerformSUBCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformSUBCombine - Target-specific dag combine xforms for ISD::SUB.
static SDValue PerformVMULCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformVMULCombine Distribute (A + B) * C to (A * C) + (B * C) to take advantage of the special multiplier accumulator forwarding.
static SDValue PerformMULCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue CombineANDShift (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformANDCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformORCombineToSMULWBT (SDNode *OR, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformORCombineToBFI (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static bool isValidMVECond (unsigned CC, bool IsFloat)
static SDValue PerformORCombine_i1 (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformORCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformORCombine - Target-specific dag combine xforms for ISD::OR.
static SDValue PerformXORCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue ParseBFI (SDNode *N, APInt &ToMask, APInt &FromMask)
static bool BitsProperlyConcatenate (const APInt &A, const APInt &B)
static SDValue FindBFIToCombineWith (SDNode *N)
static SDValue PerformBFICombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
static SDValue PerformVMOVRRDCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformVMOVRRDCombine - Target-specific dag combine xforms for ARMISD::VMOVRRD.
static SDValue PerformVMOVDRRCombine (SDNode *N, SelectionDAG &DAG)
PerformVMOVDRRCombine - Target-specific dag combine xforms for ARMISD::VMOVDRR.
static bool hasNormalLoadOperand (SDNode *N)
hasNormalLoadOperand - Check if any of the operands of a BUILD_VECTOR node are normal, non-volatile loads.
static SDValue PerformBUILD_VECTORCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformBUILD_VECTORCombine - Target-specific dag combine xforms for ISD::BUILD_VECTOR.
static SDValue PerformARMBUILD_VECTORCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
Target-specific dag combine xforms for ARMISD::BUILD_VECTOR.
static SDValue PerformPREDICATE_CASTCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
static SDValue PerformVCMPCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
static SDValue PerformInsertEltCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
PerformInsertEltCombine - Target-specific dag combine xforms for ISD::INSERT_VECTOR_ELT.
static SDValue PerformVECTOR_SHUFFLECombine (SDNode *N, SelectionDAG &DAG)
PerformVECTOR_SHUFFLECombine - Target-specific dag combine xforms for ISD::VECTOR_SHUFFLE.
static SDValue CombineBaseUpdate (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
CombineBaseUpdate - Target-specific DAG combine function for VLDDUP, NEON load/store intrinsics, and generic vector load/stores, to merge base address updates.
static SDValue PerformVLDCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
static bool CombineVLDDUP (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
CombineVLDDUP - For a VDUPLANE node N, check if its source operand is a vldN-lane (N > 1) intrinsic, and if all the other uses of that intrinsic are also VDUPLANEs.
static SDValue PerformVDUPLANECombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
PerformVDUPLANECombine - Target-specific dag combine xforms for ARMISD::VDUPLANE.
static SDValue PerformVDUPCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformVDUPCombine - Target-specific dag combine xforms for ARMISD::VDUP.
static SDValue PerformLOADCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
static SDValue PerformTruncatingStoreCombine (StoreSDNode *St, SelectionDAG &DAG)
static SDValue PerformSplittingToNarrowingStores (StoreSDNode *St, SelectionDAG &DAG)
static SDValue PerformSTORECombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *Subtarget)
PerformSTORECombine - Target-specific dag combine xforms for ISD::STORE.
static SDValue PerformVCVTCombine (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
PerformVCVTCombine - VCVT (floating-point to fixed-point, Advanced SIMD) can replace combinations of VMUL and VCVT (floating-point to integer) when the VMUL has a constant operand that is a power of 2.
static SDValue PerformVDIVCombine (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *Subtarget)
PerformVDIVCombine - VCVT (fixed-point to floating-point, Advanced SIMD) can replace combinations of VCVT (integer to floating-point) and VDIV when the VDIV has a constant operand that is a power of 2.
static SDValue PerformIntrinsicCombine (SDNode *N, SelectionDAG &DAG)
PerformIntrinsicCombine - ARM-specific DAG combining for intrinsics.
static SDValue PerformShiftCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *ST)
PerformShiftCombine - Checks for immediate versions of vector shifts and lowers them.
static SDValue PerformSplittingToWideningLoad (SDNode *N, SelectionDAG &DAG)
static SDValue PerformExtendCombine (SDNode *N, SelectionDAG &DAG, const ARMSubtarget *ST)
PerformExtendCombine - Target-specific DAG combining for ISD::SIGN_EXTEND, ISD::ZERO_EXTEND, and ISD::ANY_EXTEND.
static const APInt * isPowerOf2Constant (SDValue V)
static SDValue SearchLoopIntrinsic (SDValue N, ISD::CondCode &CC, int &Imm, bool &Negate)
static SDValue PerformHWLoopCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI, const ARMSubtarget *ST)
static bool memOpAlign (unsigned DstAlign, unsigned SrcAlign, unsigned AlignCheck)
static bool areExtractExts (Value *Ext1, Value *Ext2)
Check if Ext1 and Ext2 are extends of the same type, doubling the bitwidth of the vector elements.
static bool isLegalT1AddressImmediate (int64_t V, EVT VT)
static bool isLegalT2AddressImmediate (int64_t V, EVT VT, const ARMSubtarget *Subtarget)
static bool isLegalAddressImmediate (int64_t V, EVT VT, const ARMSubtarget *Subtarget)
isLegalAddressImmediate - Return true if the integer value can be used as the offset of the target addressing mode for load / store of the given type.
static bool getARMIndexedAddressParts (SDNode *Ptr, EVT VT, bool isSEXTLoad, SDValue &Base, SDValue &Offset, bool &isInc, SelectionDAG &DAG)
static bool getT2IndexedAddressParts (SDNode *Ptr, EVT VT, bool isSEXTLoad, SDValue &Base, SDValue &Offset, bool &isInc, SelectionDAG &DAG)
static bool getMVEIndexedAddressParts (SDNode *Ptr, EVT VT, unsigned Align, bool isSEXTLoad, bool IsMasked, bool isLE, SDValue &Base, SDValue &Offset, bool &isInc, SelectionDAG &DAG)
static RTLIB::Libcall getDivRemLibcall (const SDNode *N, MVT::SimpleValueType SVT)
static TargetLowering::ArgListTy getDivRemArgList (const SDNode *N, LLVMContext *Context, const ARMSubtarget *Subtarget)
static bool isHomogeneousAggregate (Type *Ty, HABaseType &Base, uint64_t &Members)
Variables
static cl::opt< bool > ARMInterworking ("arm-interworking", cl::Hidden, cl::desc("Enable / disable ARM interworking (for debugging only)"), cl::init(true))
static cl::opt< bool > EnableConstpoolPromotion ("arm-promote-constant", cl::Hidden, cl::desc("Enable / disable promotion of unnamed_addr constants into " "constant pools"), cl::init(false))
static cl::opt< unsigned > ConstpoolPromotionMaxSize ("arm-promote-constant-max-size", cl::Hidden, cl::desc("Maximum size of constant to promote into a constant pool"), cl::init(64))
static cl::opt< unsigned > ConstpoolPromotionMaxTotal ("arm-promote-constant-max-total", cl::Hidden, cl::desc("Maximum size of ALL constants to promote into a constant pool"), cl::init(128))
static cl::opt< unsigned > MVEMaxSupportedInterleaveFactor ("mve-max-interleave-factor", cl::Hidden, cl::desc("Maximum interleave factor for MVE VLDn to generate."), cl::init(2))
static const MCPhysReg GPRArgRegs []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-isel"
Definition at line 119 of file ARMISelLowering.cpp.
Typedef Documentation
RCPair
using RCPair = std::pair<unsigned, const TargetRegisterClass *>
Definition at line 15947 of file ARMISelLowering.cpp.
Enumeration Type Documentation
HABaseType
enum HABaseType
Enumerator
HA_UNKNOWN
HA_FLOAT
HA_DOUBLE
HA_VECT64
HA_VECT128
Definition at line 17337 of file ARMISelLowering.cpp.
ShuffleOpCodes
enum ShuffleOpCodes
Enumerator
OP_COPY
OP_VREV
OP_VDUP0
OP_VDUP1
OP_VDUP2
OP_VDUP3
OP_VEXT1
OP_VEXT2
OP_VEXT3
OP_VUZPL
OP_VUZPR
OP_VZIPL
OP_VZIPR
OP_VTRNL
OP_VTRNR
Definition at line 7585 of file ARMISelLowering.cpp.
Function Documentation
AddCombineBUILD_VECTORToVPADDL()
static SDValue AddCombineBUILD_VECTORToVPADDL (SDNode * N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11185 of file ARMISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::EVT::bitsGT(), llvm::ISD::BUILD_VECTOR, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::ConstantSDNode::getZExtValue(), llvm::ARMSubtarget::hasNEON(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::EVT::isInteger(), llvm_unreachable, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MVT::SimpleTy, and llvm::ISD::TRUNCATE.
Referenced by PerformADDCombineWithOperands().
AddCombineTo64bitMLAL()
static SDValue AddCombineTo64bitMLAL (SDNode * AddeSubeNode, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11366 of file ARMISelLowering.cpp.
References llvm::ARMISD::ADDC, AddCombineTo64BitSMLAL16(), llvm::ARMISD::ADDE, assert(), llvm::ISD::Constant, llvm::TargetLowering::DAGCombinerInfo::DAG, findMUL_LOHI(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::hasAnyUseOfValue(), llvm::ARMSubtarget::hasDSP(), llvm::ARMSubtarget::hasV6Ops(), llvm::MVT::i32, llvm::SDNode::isPredecessorOf(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ARMISD::SMLAL, llvm::ARMISD::SMMLAR, llvm::ARMISD::SMMLSR, llvm::ISD::SMUL_LOHI, llvm::ARMISD::SUBC, llvm::ARMISD::SUBE, llvm::ARMISD::UMLAL, llvm::ISD::UMUL_LOHI, and llvm::ARMSubtarget::useMulOps().
Referenced by AddCombineTo64bitUMAAL(), and PerformAddeSubeCombine().
AddCombineTo64BitSMLAL16()
static SDValue AddCombineTo64BitSMLAL16 (SDNode * AddcNode, SDNode * AddeNode, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11289 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getVTList(), llvm::ARMSubtarget::hasBaseDSP(), llvm::MipsISD::Hi, llvm::MVT::i32, isS16(), isSRA16(), llvm::MipsISD::Lo, llvm::ISD::MUL, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ARMISD::SMLAL, llvm::ARMISD::SMLALBB, llvm::ARMISD::SMLALBT, llvm::ARMISD::SMLALTB, llvm::ARMISD::SMLALTT, and llvm::ISD::SRA.
Referenced by AddCombineTo64bitMLAL().
AddCombineTo64bitUMAAL()
static SDValue AddCombineTo64bitUMAAL (SDNode * AddeNode, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11532 of file ARMISelLowering.cpp.
References llvm::ARMISD::ADDC, AddCombineTo64bitMLAL(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getVTList(), llvm::ARMSubtarget::hasDSP(), llvm::ARMSubtarget::hasV6Ops(), llvm::MVT::i32, llvm::isNullConstant(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ARMISD::UMAAL, and llvm::ARMISD::UMLAL.
Referenced by PerformADDECombine().
AddCombineToVPADD()
static SDValue AddCombineToVPADD (SDNode * N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11104 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::is64BitVector(), IsVUZPShuffleNode(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by PerformADDCombineWithOperands().
AddCombineVUZPToVPADDL()
static SDValue AddCombineVUZPToVPADDL (SDNode * N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11132 of file ARMISelLowering.cpp.
References Concat, llvm::ISD::CONCAT_VECTORS, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::is128BitVector(), llvm::EVT::is64BitVector(), IsVUZPShuffleNode(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
Referenced by PerformADDCombineWithOperands().
AddRequiredExtensionForVMULL()
static SDValue AddRequiredExtensionForVMULL (SDValue N, SelectionDAG & DAG, const EVT & OrigTy, const EVT & ExtTy, unsigned ExtOpcode) static
AddRequiredExtensionForVMULL - Add a sign/zero extension to extend the total value size to 64 bits.
We need a 64-bit D register as an operand to VMULL. We insert the required extension here to get the vector to fill a D register.
Definition at line 8451 of file ARMISelLowering.cpp.
References assert(), getExtensionTo64Bits(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), and llvm::EVT::is128BitVector().
Referenced by SkipExtensionForVMULL().
allUsersAreInFunction()
static bool allUsersAreInFunction (const Value * V, const Function * F) static
Return true if all users of V are within function F, looking through ConstantExprs.
Definition at line 3332 of file ARMISelLowering.cpp.
References llvm::dyn_cast(), llvm::SmallVectorBase::empty(), F(), I, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::Value::users().
Referenced by promoteToConstantPool().
areExtractExts()
static bool areExtractExts (Value * Ext1, Value * Ext2) static
Check if Ext1 and Ext2 are extends of the same type, doubling the bitwidth of the vector elements.
Definition at line 14936 of file ARMISelLowering.cpp.
References llvm::MipsISD::Ext, llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExtOrSExt(), and llvm::PatternMatch::match().
Referenced by llvm::ARMTargetLowering::shouldSinkOperands().
attachMEMCPYScratchRegs()
static void attachMEMCPYScratchRegs (const ARMSubtarget * Subtarget, MachineInstr & MI, const SDNode * Node) static
Attaches vregs to MEMCPY that it will use as scratch registers when it is expanded into LDM/STM.
This is done as a post-isel lowering instead of as a custom inserter because we need the use list from the SDNode.
Definition at line 10835 of file ARMISelLowering.cpp.
bitcastf32Toi32()
static SDValue bitcastf32Toi32 (SDValue Op, SelectionDAG & DAG) static
Definition at line 5115 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getLoad(), llvm::MVT::i32, isFloatingPointZero(), and llvm_unreachable.
Referenced by expandf64Toi32().
BitsProperlyConcatenate()
static bool BitsProperlyConcatenate (const APInt & A, const APInt & B) static
Definition at line 12630 of file ARMISelLowering.cpp.
References llvm::APInt::countLeadingZeros(), llvm::APInt::countTrailingZeros(), and llvm::APInt::getBitWidth().
Referenced by FindBFIToCombineWith().
canChangeToInt()
static bool canChangeToInt (SDValue Op, bool & SeenZero, const ARMSubtarget * Subtarget) static
canChangeToInt - Given the fp compare operand, return true if it is suitable to morph to an integer compare sequence.
Definition at line 5094 of file ARMISelLowering.cpp.
References llvm::MVT::f32, llvm::SDValue::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getValueType(), llvm::SDNode::hasOneUse(), isFloatingPointZero(), llvm::ARMSubtarget::isFPBrccSlow(), and llvm::ISD::isNormalLoad().
Referenced by expandf64Toi32().
checkAndUpdateCPSRKill()
static bool checkAndUpdateCPSRKill (MachineBasicBlock::iterator SelectItr, MachineBasicBlock * BB, const TargetRegisterInfo * TRI) static
Definition at line 10511 of file ARMISelLowering.cpp.
References llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineInstr::readsRegister(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
Referenced by llvm::ARMTargetLowering::EmitInstrWithCustomInserter().
checkVSELConstraints()
static void checkVSELConstraints (ISD::CondCode CC, ARMCC::CondCodes & CondCode, bool & swpCmpOps, bool & swpVselOps) static
Definition at line 4647 of file ARMISelLowering.cpp.
References llvm::ARMISD::CMOV, llvm::ARMCC::EQ, llvm::MVT::f64, llvm::ARMCC::GE, llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::ARMCC::GT, llvm::ARMSubtarget::hasFP64(), High, llvm::MVT::i32, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ARMISD::VMOVDRR, llvm::ARMISD::VMOVRRD, and llvm::ARMCC::VS.
Referenced by isLowerSaturatingConditional().
CombineANDShift()
static SDValue CombineANDShift (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 12072 of file ARMISelLowering.cpp.
References llvm::countLeadingZeros(), llvm::countTrailingZeros(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer(), llvm::isMask_32(), llvm::isShiftedMask_32(), llvm::ISD::SHL, and llvm::ISD::SRL.
Referenced by PerformANDCombine().
CombineBaseUpdate()
static SDValue CombineBaseUpdate (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
CombineBaseUpdate - Target-specific DAG combine function for VLDDUP, NEON load/store intrinsics, and generic vector load/stores, to merge base address updates.
For generic load/stores, the memory type is assumed to be a vector. The caller is assumed to have checked legality.
Definition at line 13072 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::MemSDNode::getAlignment(), llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasPredecessorHelper(), llvm::MVT::i32, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, isStore(), llvm_unreachable, llvm::ISD::LOAD, llvm::makeArrayRef(), N, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), llvm::ISD::STORE, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::ARMISD::VLD1_UPD, llvm::ARMISD::VLD1DUP, llvm::ARMISD::VLD1DUP_UPD, llvm::ARMISD::VLD2_UPD, llvm::ARMISD::VLD2DUP, llvm::ARMISD::VLD2DUP_UPD, llvm::ARMISD::VLD2LN_UPD, llvm::ARMISD::VLD3_UPD, llvm::ARMISD::VLD3DUP, llvm::ARMISD::VLD3DUP_UPD, llvm::ARMISD::VLD3LN_UPD, llvm::ARMISD::VLD4_UPD, llvm::ARMISD::VLD4DUP, llvm::ARMISD::VLD4DUP_UPD, llvm::ARMISD::VLD4LN_UPD, llvm::ARMISD::VST1_UPD, llvm::ARMISD::VST2_UPD, llvm::ARMISD::VST2LN_UPD, llvm::ARMISD::VST3_UPD, llvm::ARMISD::VST3LN_UPD, llvm::ARMISD::VST4_UPD, and llvm::ARMISD::VST4LN_UPD.
Referenced by PerformLOADCombine(), PerformSTORECombine(), and PerformVLDCombine().
combineSelectAndUse()
static SDValue combineSelectAndUse (SDNode * N, SDValue Slct, SDValue OtherOp, TargetLowering::DAGCombinerInfo & DCI, bool AllOnes = false) static
Definition at line 11053 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), isConditionalZeroOrAllOnes(), llvm::ISD::SELECT, and std::swap().
Referenced by combineSelectAndUseCommutative(), PerformADDCombineWithOperands(), and PerformSUBCombine().
combineSelectAndUseCommutative()
static SDValue combineSelectAndUseCommutative (SDNode * N, bool AllOnes, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 11079 of file ARMISelLowering.cpp.
References combineSelectAndUse(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), and llvm::SDNode::hasOneUse().
Referenced by PerformANDCombine(), PerformORCombine(), and PerformXORCombine().
CombineVLDDUP()
static bool CombineVLDDUP (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
CombineVLDDUP - For a VDUPLANE node N, check if its source operand is a vldN-lane (N > 1) intrinsic, and if all the other uses of that intrinsic are also VDUPLANEs.
If so, combine them to a vldN-dup operation and return true.
Definition at line 13300 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::EVT::is64BitVector(), llvm::makeArrayRef(), llvm::MVT::Other, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::ARMISD::VDUPLANE, llvm::ARMISD::VLD2DUP, llvm::ARMISD::VLD3DUP, and llvm::ARMISD::VLD4DUP.
Referenced by PerformVDUPLANECombine().
CombineVMOVDRRCandidateWithVecOp()
static SDValue CombineVMOVDRRCandidateWithVecOp (const SDNode * BC, SelectionDAG & DAG) static
BC is a bitcast that is about to be turned into a VMOVDRR.
When DstVT, the destination type of BC, is on the vector register bank and the source of bitcast, Op, operates on the same bank, it might be possible to combine them, such that everything stays on the vector register bank. return The node that would replace BT, if the combine is possible.
Definition at line 5664 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitWidth(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, and llvm::EVT::isVector().
Referenced by ExpandBITCAST().
ConvertBooleanCarryToCarryFlag()
static SDValue ConvertBooleanCarryToCarryFlag (SDValue BoolCarry, SelectionDAG & DAG) static
Definition at line 4488 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, and llvm::ARMISD::SUBC.
Referenced by LowerADDSUBCARRY().
ConvertCarryFlagToBooleanCarry()
static SDValue ConvertCarryFlagToBooleanCarry (SDValue Flags, EVT VT, SelectionDAG & DAG) static
Definition at line 4501 of file ARMISelLowering.cpp.
References llvm::ARMISD::ADDC, llvm::ARMISD::ADDE, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::TargetLoweringBase::isTypeLegal(), llvm_unreachable, llvm::ISD::MERGE_VALUES, llvm::ISD::SUB, llvm::ARMISD::SUBC, llvm::ISD::UADDO, and llvm::ISD::USUBO.
Referenced by LowerADDSUBCARRY().
createGPRPairNode()
static SDValue createGPRPairNode (SelectionDAG & DAG, SDValue V) static
Definition at line 9198 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::MVT::i64, llvm::DataLayout::isBigEndian(), isBigEndian(), llvm::ISD::SRL, std::swap(), and llvm::MVT::Untyped.
Referenced by ReplaceCMP_SWAP_64Results().
emitPostLd()
static void emitPostLd (MachineBasicBlock * BB, MachineBasicBlock::iterator Pos, const TargetInstrInfo * TII, const DebugLoc & dl, unsigned LdSize, unsigned Data, unsigned AddrIn, unsigned AddrOut, bool IsThumb1, bool IsThumb2) static
Emit a post-increment load operation with given size.
The instructions will be added to BB at Pos.
Definition at line 10071 of file ARMISelLowering.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, assert(), llvm::BuildMI(), llvm::Data, llvm::RegState::Define, llvm::MCInstrInfo::get(), getLdOpcode(), llvm::predOps(), and llvm::t1CondCodeOp().
Referenced by emitPostSt().
emitPostSt()
static void emitPostSt (MachineBasicBlock * BB, MachineBasicBlock::iterator Pos, const TargetInstrInfo * TII, const DebugLoc & dl, unsigned StSize, unsigned Data, unsigned AddrIn, unsigned AddrOut, bool IsThumb1, bool IsThumb2) static
Emit a post-increment store operation with given size.
The instructions will be added to BB at Pos.
Definition at line 10112 of file ARMISelLowering.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::ARMCC::AL, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), C, llvm::condCodeOp(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Dead, llvm::RegState::Define, emitPostLd(), llvm::MachineBasicBlock::end(), llvm::ARMCC::EQ, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::FrameSetup, llvm::MCInstrInfo::get(), llvm::ConstantInt::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetMachine::getCodeModel(), llvm::MachinePointerInfo::getConstantPool(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::Function::getContext(), llvm::MachineFunction::getDataLayout(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::ARMSubtarget::getInstrInfo(), llvm::Type::getInt32Ty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::DataLayout::getPrefTypeAlignment(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getStOpcode(), llvm::TargetLoweringBase::getTargetMachine(), llvm::DataLayout::getTypeAllocSize(), llvm::Function::hasFnAttribute(), llvm::ARMSubtarget::hasNEON(), llvm::RegState::Implicit, llvm::MachineFunction::insert(), Int32Ty, llvm::ARMSubtarget::isTargetWindows(), llvm::ARMSubtarget::isThumb(), llvm::ARMSubtarget::isThumb1Only(), llvm::ARMSubtarget::isThumb2(), llvm::CodeModel::Kernel, llvm::RegState::Kill, llvm::CodeModel::Large, llvm_unreachable, llvm::CodeModel::Medium, llvm::MachineMemOperand::MOLoad, MRI, llvm::ARMCC::NE, llvm::predOps(), llvm::MachineFunction::push_back(), R4, Reg, llvm::MachineOperand::setIsDef(), llvm::MachineInstrBuilder::setMIFlags(), llvm::MachineOperand::setReg(), llvm::CodeModel::Small, llvm::MachineBasicBlock::splice(), llvm::t1CondCodeOp(), TII, llvm::CodeModel::Tiny, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), and llvm::ARMSubtarget::useMovt().
Expand64BitShift()
static SDValue Expand64BitShift (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 6130 of file ARMISelLowering.cpp.
References llvm::ARMISD::ASRL, assert(), llvm::ISD::BUILD_PAIR, llvm::dyn_cast(), llvm::ISD::EXTRACT_ELEMENT, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::isOneConstant(), llvm::ARMSubtarget::isThumb1Only(), llvm::MipsISD::Lo, llvm::ARMISD::LSLL, llvm::ARMISD::LSRL, llvm::ARMISD::RRX, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ARMISD::SRA_FLAG, llvm::ISD::SRL, llvm::ARMISD::SRL_FLAG, and llvm::ISD::SUB.
Referenced by llvm::ARMTargetLowering::ReplaceNodeResults().
ExpandBITCAST()
static SDValue ExpandBITCAST (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
ExpandBITCAST - If the target supports VFP, this function is called to expand a bit convert where either the source or destination type is i64 to use a VMOVDRR or VMOVRRD node.
This should not be done when the non-i64 operand type is illegal (e.g., v2f32 for a target that doesn't support vectors), since the legalizer won't know what to do with that.
Definition at line 5712 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_PAIR, CombineVMOVDRRCandidateWithVecOp(), llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::ISD::EXTRACT_ELEMENT, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), llvm::ARMSubtarget::hasFullFP16(), llvm::MipsISD::Hi, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::DataLayout::isBigEndian(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MipsISD::Lo, llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ARMISD::RET_FLAG, llvm::SDNode::use_begin(), llvm::SDNode::use_size(), llvm::ARMISD::VMOVDRR, llvm::ARMISD::VMOVhr, llvm::ARMISD::VMOVrh, llvm::ARMISD::VMOVRRD, llvm::ARMISD::VREV64, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::ARMTargetLowering::LowerOperation(), and llvm::ARMTargetLowering::ReplaceNodeResults().
expandf64Toi32()
static void expandf64Toi32 (SDValue Op, SelectionDAG & DAG, SDValue & RetVal1, SDValue & RetVal2) static
Definition at line 5127 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ARMISD::BCC_i64, bitcastf32Toi32(), llvm::ARMISD::BRCOND, canChangeToInt(), llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SDNode::getFlags(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MVT::i32, IntCCToARMCC(), isFloatingPointZero(), llvm_unreachable, llvm::BitmaskEnumDetail::Mask(), llvm::MinAlign(), llvm::MVT::Other, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SETOEQ, and llvm::ISD::SETUNE.
ExpandREAD_REGISTER()
static void ExpandREAD_REGISTER (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) static
Definition at line 5639 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::BUILD_PAIR, llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::ISD::READ_REGISTER.
Referenced by llvm::ARMTargetLowering::ReplaceNodeResults().
FindBFIToCombineWith()
static SDValue FindBFIToCombineWith (SDNode * N) static
Definition at line 12636 of file ARMISelLowering.cpp.
References llvm::ARMISD::BFI, BitsProperlyConcatenate(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), and ParseBFI().
Referenced by PerformBFICombine().
findMUL_LOHI()
static SDValue findMUL_LOHI (SDValue V) static
Definition at line 11282 of file ARMISelLowering.cpp.
References llvm::SDNode::getOpcode(), llvm::ISD::SMUL_LOHI, and llvm::ISD::UMUL_LOHI.
Referenced by AddCombineTo64bitMLAL().
FPCCToARMCC()
static void FPCCToARMCC (ISD::CondCode CC, ARMCC::CondCodes & CondCode, ARMCC::CondCodes & CondCode2) static
FPCCToARMCC - Convert a DAG fp condition code to an ARM CC.
Definition at line 1849 of file ARMISelLowering.cpp.
References llvm::ARMCC::AL, llvm::CallingConv::ARM_AAPCS, llvm::CallingConv::ARM_AAPCS_VFP, llvm::CallingConv::ARM_APCS, llvm::CallingConv::C, llvm::CallingConv::CFGuard_Check, llvm::CallingConv::CXX_FAST_TLS, llvm::ARMCC::EQ, llvm::CallingConv::Fast, llvm::TargetOptions::FloatABIType, llvm::ARMCC::GE, llvm::TargetLoweringBase::getTargetMachine(), llvm::CallingConv::GHC, llvm::ARMCC::GT, llvm::FloatABI::Hard, llvm::ARMSubtarget::hasVFP2Base(), llvm::ARMCC::HI, llvm::ARMSubtarget::isAAPCS_ABI(), llvm::ARMSubtarget::isThumb1Only(), llvm::ARMCC::LE, llvm_unreachable, llvm::ARMCC::LS, llvm::ARMCC::LT, llvm::ARMCC::MI, llvm::ARMCC::NE, llvm::TargetMachine::Options, llvm::ARMCC::PL, llvm::CallingConv::PreserveMost, llvm::report_fatal_error(), llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::CallingConv::Swift, llvm::ARMCC::VC, and llvm::ARMCC::VS.
Referenced by isLowerSaturatingConditional(), and ReplaceCMP_SWAP_64Results().
GeneratePerfectShuffle()
static SDValue GeneratePerfectShuffle (unsigned PFEntry, SDValue LHS, SDValue RHS, SelectionDAG & DAG, const SDLoc & dl) static
GeneratePerfectShuffle - Given an entry in the perfect-shuffle table, emit the specified operations to build the shuffle.
Definition at line 7670 of file ARMISelLowering.cpp.
References assert(), llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm_unreachable, OP_COPY, OP_VDUP0, OP_VDUP1, OP_VDUP2, OP_VDUP3, OP_VEXT1, OP_VEXT2, OP_VEXT3, OP_VREV, OP_VTRNL, OP_VTRNR, OP_VUZPL, OP_VUZPR, OP_VZIPL, OP_VZIPR, PerfectShuffleTable, llvm::ARMISD::VDUPLANE, llvm::ARMISD::VEXT, llvm::ARMISD::VREV16, llvm::ARMISD::VREV32, llvm::ARMISD::VREV64, llvm::ARMISD::VTRN, llvm::ARMISD::VUZP, and llvm::ARMISD::VZIP.
Referenced by LowerVECTOR_SHUFFLE().
getARMIndexedAddressParts()
static bool getARMIndexedAddressParts (SDNode * Ptr, EVT VT, bool isSEXTLoad, SDValue & Base, SDValue & Offset, bool & isInc, SelectionDAG & DAG) static
Definition at line 15364 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ARM_AM::getShiftOpcForNode(), llvm::SDNode::getValueType(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::ARM_AM::no_shift, and llvm::ISD::SUB.
Referenced by llvm::ARMTargetLowering::getPostIndexedAddressParts(), and llvm::ARMTargetLowering::getPreIndexedAddressParts().
getDivRemArgList()
static TargetLowering::ArgListTy getDivRemArgList (const SDNode * N, LLVMContext * Context, const ARMSubtarget * Subtarget) static
Definition at line 16208 of file ARMISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::SDNode::getOpcode(), llvm::ISD::SDIVREM, llvm::ISD::SREM, llvm::ISD::UDIVREM, and llvm::ISD::UREM.
getDivRemLibcall()
static RTLIB::Libcall getDivRemLibcall (const SDNode * N, MVT::SimpleValueType SVT) static
Definition at line 16190 of file ARMISelLowering.cpp.
References assert(), llvm::SDNode::getOpcode(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm_unreachable, llvm::ISD::SDIVREM, llvm::ISD::SREM, llvm::ISD::UDIVREM, and llvm::ISD::UREM.
getExtensionTo64Bits()
static EVT getExtensionTo64Bits (const EVT & OrigVT) static
Definition at line 8431 of file ARMISelLowering.cpp.
References assert(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::EVT::isSimple(), llvm_unreachable, llvm::MVT::SimpleTy, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i8, llvm::MVT::v4i16, and llvm::MVT::v4i8.
Referenced by AddRequiredExtensionForVMULL(), and SkipLoadExtensionForVMULL().
getLdOpcode()
static unsigned getLdOpcode (unsigned LdSize, bool IsThumb1, bool IsThumb2) static
Return the load opcode for a given load size.
If load size >= 8, neon opcode will be returned.
Definition at line 10033 of file ARMISelLowering.cpp.
Referenced by emitPostLd().
getMVEIndexedAddressParts()
static bool getMVEIndexedAddressParts (SDNode * Ptr, EVT VT, unsigned Align, bool isSEXTLoad, bool IsMasked, bool isLE, SDValue & Base, SDValue & Offset, bool & isInc, SelectionDAG & DAG) static
Definition at line 15448 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), IsMasked(), llvm::ISD::SUB, llvm::MVT::v16i8, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i8, llvm::MVT::v8f16, llvm::MVT::v8i16, and llvm::MVT::v8i8.
Referenced by llvm::ARMTargetLowering::getPostIndexedAddressParts(), and llvm::ARMTargetLowering::getPreIndexedAddressParts().
getStOpcode()
static unsigned getStOpcode (unsigned StSize, bool IsThumb1, bool IsThumb2) static
Return the store opcode for a given store size.
If store size >= 8, neon opcode will be returned.
Definition at line 10052 of file ARMISelLowering.cpp.
Referenced by emitPostSt().
getT2IndexedAddressParts()
static bool getT2IndexedAddressParts (SDNode * Ptr, EVT VT, bool isSEXTLoad, SDValue & Base, SDValue & Offset, bool & isInc, SelectionDAG & DAG) static
Definition at line 15423 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), and llvm::ISD::SUB.
Referenced by llvm::ARMTargetLowering::getPostIndexedAddressParts(), and llvm::ARMTargetLowering::getPreIndexedAddressParts().
getVectorTyFromPredicateVector()
static EVT getVectorTyFromPredicateVector (EVT VT) static
Definition at line 7766 of file ARMISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm_unreachable, llvm::MVT::SimpleTy, llvm::MVT::v16i1, llvm::MVT::v16i8, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v8i1, and llvm::MVT::v8i16.
Referenced by LowerCONCAT_VECTORS_i1(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_VECTOR_ELT_i1(), LowerINSERT_VECTOR_ELT_i1(), and PromoteMVEPredVector().
getVShiftImm()
static bool getVShiftImm (SDValue Op, unsigned ElementBits, int64_t & Cnt) static
Getvshiftimm - Check if this is a valid build_vector for the immediate operand of a vector shift operation, where all the elements of the build_vector must have the same constant integer value.
Definition at line 6037 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::APInt::getSExtValue(), and llvm::BuildVectorSDNode::isConstantSplat().
Referenced by isVShiftLImm(), and isVShiftRImm().
getZeroVector()
static SDValue getZeroVector (EVT VT, SelectionDAG & DAG, const SDLoc & dl) static
getZeroVector - Returns a vector of specified type with all zero elements.
Zero vectors are used to represent vector negation and in those cases will be implemented with the NEON VNEG instruction. However, VNEG does not support i64 elements, so sometimes the zero vectors will need to be explicitly constructed. Regardless, use a canonical VMOV to create the zero vector.
Definition at line 5834 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::ARMISD::CMOV, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getEntryNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::ISD::INTRINSIC_W_CHAIN, llvm::EVT::is128BitVector(), llvm::EVT::isVector(), llvm::MipsISD::Lo, llvm::ISD::OR, llvm::ISD::SETGE, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SUB, llvm::MVT::v2i32, llvm::MVT::v4i32, and llvm::ARMISD::VMOVIMM.
Referenced by LowerCTTZ(), and LowerShift().
hasNormalLoadOperand()
static bool hasNormalLoadOperand (SDNode * N) static
hasNormalLoadOperand - Check if any of the operands of a BUILD_VECTOR node are normal, non-volatile loads.
If so, it is profitable to bitcast an i64 vector to have f64 elements, since the value can then be loaded directly into a VFP register.
Definition at line 12803 of file ARMISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::isNormalLoad(), and isVolatile().
Referenced by PerformBUILD_VECTORCombine().
IntCCToARMCC()
static ARMCC::CondCodes IntCCToARMCC (ISD::CondCode CC) static
IntCCToARMCC - Convert a DAG integer condition code to an ARM CC.
Definition at line 1832 of file ARMISelLowering.cpp.
References llvm::ARMCC::EQ, llvm::ARMCC::GE, llvm::ARMCC::GT, llvm::ARMCC::HI, llvm::ARMCC::HS, llvm::ARMCC::LE, llvm_unreachable, llvm::ARMCC::LO, llvm::ARMCC::LS, llvm::ARMCC::LT, llvm::ARMCC::NE, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
Referenced by expandf64Toi32(), isFloatingPointZero(), and isLowerSaturatingConditional().
isAddSubSExt()
static bool isAddSubSExt (SDNode * N, SelectionDAG & DAG) static
Definition at line 8547 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::hasOneUse(), isSignExtended(), and llvm::ISD::SUB.
Referenced by LowerMUL().
isAddSubZExt()
static bool isAddSubZExt (SDNode * N, SelectionDAG & DAG) static
Definition at line 8558 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::hasOneUse(), isZeroExtended(), and llvm::ISD::SUB.
Referenced by LowerMUL().
isConditionalZeroOrAllOnes()
static bool isConditionalZeroOrAllOnes (SDNode * N, bool AllOnes, SDValue & CC, bool & Invert, SDValue & OtherOp, SelectionDAG & DAG) static
Definition at line 10979 of file ARMISelLowering.cpp.
References llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::i1, isZeroOrAllOnes(), LLVM_FALLTHROUGH, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSelectAndUse().
isExtendedBUILD_VECTOR()
static bool isExtendedBUILD_VECTOR (SDNode * N, SelectionDAG & DAG, bool isSigned) static
isExtendedBUILD_VECTOR - Check if N is a constant BUILD_VECTOR where each element has been zero/sign-extended, depending on the isSigned parameter, from an integer type half its size.
Definition at line 8360 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, C, llvm::dyn_cast(), llvm::numbers::e, llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::ConstantSDNode::getSExtValue(), llvm::SDNode::getValueType(), llvm::DataLayout::isBigEndian(), llvm::isIntN(), llvm::isUIntN(), llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by isSignExtended(), and isZeroExtended().
isFloatingPointZero()
static bool isFloatingPointZero (SDValue Op) static
isFloatingPointZero - Return true if this is +0.0.
Definition at line 4190 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::ARMISD::ADDC, llvm::ISD::AND, assert(), llvm::ISD::BITCAST, C, llvm::ARMISD::CMOV, llvm::ARMISD::CMP, llvm::ARMISD::CMPFP, llvm::ARMISD::CMPFPE, llvm::ARMISD::CMPFPEw0, llvm::ARMISD::CMPFPw0, llvm::ARMISD::CMPZ, llvm::countLeadingZeros(), llvm::HexagonISD::CP, llvm::ARMCC::EQ, llvm::MVT::f64, llvm::ARMISD::FMSTAT, llvm::ARMCC::GE, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getRegister(), llvm::ISD::getSetCCSwappedOperands(), llvm::ARM_AM::getShiftOpcForNode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::ARMSubtarget::hasFP64(), llvm::SDNode::hasOneUse(), llvm::ARMCC::HI, llvm::ARMCC::HS, llvm::MVT::i32, IntCCToARMCC(), llvm::ISD::isEXTLoad(), llvm::ARMTargetLowering::isLegalICmpImmediate(), llvm::isMask_32(), llvm::ISD::isNON_EXTLoad(), llvm::isNullConstant(), llvm::ISD::isSignedIntSetCC(), llvm::ARMSubtarget::isThumb1Only(), llvm::TargetLoweringBase::isTypeLegal(), llvm_unreachable, llvm::ARMISD::LSLS, llvm::ARMCC::LT, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::MERGE_VALUES, llvm::ARMCC::MI, llvm::ARMCC::NE, llvm::ARM_AM::no_shift, llvm::ARMCC::PL, llvm::ISD::SADDO, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SHL, llvm::ISD::SMUL_LOHI, llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SSUBO, llvm::ISD::SUB, std::swap(), llvm::ISD::UADDO, llvm::ISD::UMUL_LOHI, llvm::ISD::UMULO, llvm::ISD::USUBO, llvm::ARMCC::VC, llvm::ARMISD::VMOVIMM, and llvm::ARMISD::Wrapper.
Referenced by bitcastf32Toi32(), canChangeToInt(), expandf64Toi32(), and isLowerSaturatingConditional().
isGTorGE()
static bool isGTorGE (ISD::CondCode CC) static
Definition at line 4723 of file ARMISelLowering.cpp.
References llvm::ISD::SETGE, and llvm::ISD::SETGT.
Referenced by isLowerSaturate(), and isUpperSaturate().
isHomogeneousAggregate()
static bool isHomogeneousAggregate (Type * Ty, HABaseType & Base, uint64_t & Members) static
Definition at line 17345 of file ARMISelLowering.cpp.
References HA_DOUBLE, HA_FLOAT, HA_UNKNOWN, HA_VECT128, HA_VECT64, llvm::Type::isDoubleTy(), and llvm::Type::isFloatTy().
Referenced by llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters().
isLegalAddressImmediate()
static bool isLegalAddressImmediate (int64_t V, EVT VT, const ARMSubtarget * Subtarget) static
isLegalAddressImmediate - Return true if the integer value can be used as the offset of the target addressing mode for load / store of the given type.
Definition at line 15182 of file ARMISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getSimpleVT(), llvm::ARMSubtarget::hasVFP2Base(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, isLegalT1AddressImmediate(), isLegalT2AddressImmediate(), llvm::EVT::isSimple(), llvm::ARMSubtarget::isThumb1Only(), llvm::ARMSubtarget::isThumb2(), llvm::isUInt< 8 >(), and llvm::MVT::SimpleTy.
Referenced by llvm::ARMTargetLowering::isLegalAddressingMode().
isLegalMVEShuffleOp()
static bool isLegalMVEShuffleOp (unsigned PFEntry) static
Definition at line 7603 of file ARMISelLowering.cpp.
References OP_COPY, OP_VDUP0, OP_VDUP1, OP_VDUP2, OP_VDUP3, and OP_VREV.
Referenced by llvm::ARMTargetLowering::isShuffleMaskLegal(), and LowerVECTOR_SHUFFLE().
isLegalT1AddressImmediate()
static bool isLegalT1AddressImmediate (int64_t V, EVT VT) static
Definition at line 15102 of file ARMISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i8, and llvm::MVT::SimpleTy.
Referenced by isLegalAddressImmediate().
isLegalT2AddressImmediate()
static bool isLegalT2AddressImmediate (int64_t V, EVT VT, const ARMSubtarget * Subtarget) static
Definition at line 15128 of file ARMISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::ARMSubtarget::hasFPRegs16(), llvm::ARMSubtarget::hasMVEFloatOps(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ARMSubtarget::hasNEON(), llvm::ARMSubtarget::hasVFP2Base(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::isUInt< 8 >(), llvm::EVT::isVector(), llvm::max(), and llvm::MVT::SimpleTy.
Referenced by isLegalAddressImmediate().
isLowerSaturate()
static bool isLowerSaturate (const SDValue LHS, const SDValue RHS, const SDValue TrueVal, const SDValue FalseVal, const ISD::CondCode CC, const SDValue K) static
Definition at line 4737 of file ARMISelLowering.cpp.
References isGTorGE(), and isLTorLE().
Referenced by isLowerSaturatingConditional(), and isSaturatingConditional().
isLowerSaturatingConditional()
static bool isLowerSaturatingConditional (const SDValue & Op, SDValue & V, SDValue & SatK) static
Definition at line 4872 of file ARMISelLowering.cpp.
References llvm::ARMCC::AL, llvm::ISD::AND, checkVSELConstraints(), llvm::countTrailingOnes(), llvm::ARMISD::CSINC, llvm::ARMISD::CSINV, llvm::ARMISD::CSNEG, llvm::dyn_cast(), llvm::ARMCC::EQ, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, FPCCToARMCC(), llvm::ARMCC::GE, llvm::SelectionDAG::getAllOnesConstant(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::ISD::getSetCCInverse(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::ARMCC::GT, llvm::ARMSubtarget::hasFP64(), llvm::ARMSubtarget::hasFPARMv8Base(), llvm::ARMSubtarget::hasFullFP16(), llvm::HasLowerConstantMaterializationCost(), llvm::ARMSubtarget::hasV6Ops(), llvm::ARMSubtarget::hasV8_1MMainlineOps(), llvm::ARMSubtarget::hasVFP2Base(), llvm::MVT::i32, IntCCToARMCC(), llvm::isAllOnesConstant(), isFloatingPointZero(), isLowerSaturate(), llvm::isNullConstant(), isSaturatingConditional(), llvm::ARMSubtarget::isThumb(), llvm::ARMSubtarget::isThumb2(), llvm::ARMCC::LE, llvm::ARMCC::LT, llvm::ARMCC::NE, llvm::ISD::OR, llvm::ARMCC::PL, llvm::ISD::SETNE, llvm::TargetLowering::softenSetCCOperands(), llvm::ISD::SRA, llvm::ARMISD::SSAT, std::swap(), llvm::ARMISD::USAT, llvm::ARMCC::VC, llvm::ARMCC::VS, and llvm::ISD::XOR.
isLTorLE()
static bool isLTorLE (ISD::CondCode CC) static
Definition at line 4727 of file ARMISelLowering.cpp.
References llvm::ISD::SETLE, and llvm::ISD::SETLT.
Referenced by isLowerSaturate(), and isUpperSaturate().
isNEONTwoResultShuffleMask()
static unsigned isNEONTwoResultShuffleMask (ArrayRef< int > ShuffleMask, EVT VT, unsigned & WhichResult, bool & isV_UNDEF) static
Check if ShuffleMask is a NEON two-result shuffle (VZIP, VUZP, VTRN), and return the corresponding ARMISD opcode if it is, or 0 if it isn't.
Definition at line 7007 of file ARMISelLowering.cpp.
References isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), llvm::ARMISD::VTRN, llvm::ARMISD::VUZP, and llvm::ARMISD::VZIP.
Referenced by llvm::ARMTargetLowering::isShuffleMaskLegal(), and LowerVECTOR_SHUFFLE().
isPowerOf2Constant()
static const APInt* isPowerOf2Constant (SDValue V) static
Definition at line 14136 of file ARMISelLowering.cpp.
References C, llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), and llvm::APInt::isPowerOf2().
Referenced by llvm::ARMTargetLowering::PerformCMOVCombine(), and llvm::ARMTargetLowering::PerformCMOVToBFICombine().
isReverseMask()
static bool isReverseMask (ArrayRef< int > M, EVT VT) static
Returns
true if this is a reverse operation on an vector.
Definition at line 7030 of file ARMISelLowering.cpp.
References llvm::EVT::getVectorNumElements(), and llvm::ArrayRef< T >::size().
Referenced by llvm::ShuffleVectorInst::isReverse(), llvm::ShuffleVectorInst::isReverseMask(), llvm::ShuffleVectorInst::isSelect(), llvm::ARMTargetLowering::isShuffleMaskLegal(), LowerVECTOR_SHUFFLE(), and LowerVECTOR_SHUFFLE_i1().
isS16()
static bool isS16 (const SDValue & Op, SelectionDAG & DAG) static
Definition at line 1825 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::ComputeNumSignBits(), llvm::SDValue::getOperand(), isSHL16(), and isSRA16().
Referenced by AddCombineTo64BitSMLAL16(), and PerformORCombineToSMULWBT().
isSaturatingConditional()
static bool isSaturatingConditional (const SDValue & Op, SDValue & V, uint64_t & K, bool & usat) static
Definition at line 4773 of file ARMISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), isLowerSaturate(), llvm::isPowerOf2_64(), isUpperSaturate(), llvm::max(), llvm::ISD::SELECT_CC, llvm::ISD::SIGN_EXTEND_INREG, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by isLowerSaturatingConditional().
isSHL16()
static bool isSHL16 (const SDValue & Op) static
Definition at line 1813 of file ARMISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and llvm::ISD::SHL.
Referenced by isS16(), and PerformORCombineToSMULWBT().
isSignExtended()
static bool isSignExtended (SDNode * N, SelectionDAG & DAG) static
isSignExtended - Check if a node is a vector value that is sign-extended or a constant BUILD_VECTOR with sign-extended elements.
Definition at line 8413 of file ARMISelLowering.cpp.
References llvm::SDNode::getOpcode(), isExtendedBUILD_VECTOR(), llvm::ISD::isSEXTLoad(), and llvm::ISD::SIGN_EXTEND.
Referenced by isAddSubSExt(), and LowerMUL().
IsSingleInstrConstant()
static SDValue IsSingleInstrConstant (SDValue N, SelectionDAG & DAG, const ARMSubtarget * ST, const SDLoc & dl) static
Definition at line 7070 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::ARM_AM::getSOImmVal(), llvm::MVT::i32, llvm::ARMSubtarget::isThumb1Only(), and N.
Referenced by LowerBUILD_VECTOR_i1().
isSingletonVEXTMask()
static bool isSingletonVEXTMask (ArrayRef< int > M, EVT VT, unsigned & Imm) static
Definition at line 6679 of file ARMISelLowering.cpp.
References llvm::EVT::getVectorNumElements().
Referenced by LowerVECTOR_SHUFFLE().
isSRA16()
static bool isSRA16 (const SDValue & Op) static
Definition at line 1805 of file ARMISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and llvm::ISD::SRA.
Referenced by AddCombineTo64BitSMLAL16(), isS16(), and PerformORCombineToSMULWBT().
isSRL16()
static bool isSRL16 (const SDValue & Op) static
Definition at line 1797 of file ARMISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and llvm::ISD::SRL.
Referenced by PerformORCombineToSMULWBT().
isUpperSaturate()
static bool isUpperSaturate (const SDValue LHS, const SDValue RHS, const SDValue TrueVal, const SDValue FalseVal, const ISD::CondCode CC, const SDValue K) static
Definition at line 4747 of file ARMISelLowering.cpp.
References isGTorGE(), and isLTorLE().
Referenced by isSaturatingConditional().
isValidMVECond()
static bool isValidMVECond (unsigned CC, bool IsFloat) static
Definition at line 12411 of file ARMISelLowering.cpp.
References llvm::ARMCC::EQ, llvm::ARMCC::GE, llvm::ARMCC::GT, llvm::ARMCC::HI, llvm::ARMCC::HS, llvm::ARMCC::LE, llvm::ARMCC::LT, and llvm::ARMCC::NE.
Referenced by PerformORCombine_i1().
isVEXTMask()
static bool isVEXTMask (ArrayRef< int > M, EVT VT, bool & ReverseVEXT, unsigned & Imm) static
Definition at line 6707 of file ARMISelLowering.cpp.
References llvm::EVT::getVectorNumElements().
Referenced by llvm::ARMTargetLowering::isShuffleMaskLegal(), and LowerVECTOR_SHUFFLE().
isVMOVModifiedImm()
static SDValue isVMOVModifiedImm (uint64_t SplatBits, uint64_t SplatUndef, unsigned SplatBitSize, SelectionDAG & DAG, const SDLoc & dl, EVT & VT, bool is128Bits, VMOVModImmType type) static
isVMOVModifiedImm - Check if the specified splat value corresponds to a valid vector constant for a NEON or MVE instruction with a "modified immediate" operand (e.g., VMOV).
If so, return the encoded value.
Definition at line 6425 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ARM_AM::createVMOVModImm(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ARMSubtarget::genExecuteOnly(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::ARM_AM::getFP32Imm(), llvm::ARM_AM::getFP64Imm(), llvm::SelectionDAG::getNode(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTargetConstant(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::ARMSubtarget::hasFP64(), llvm::ARMSubtarget::hasNEON(), llvm::ARMSubtarget::hasVFP3Base(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::X86II::ImmMask, llvm::DataLayout::isBigEndian(), llvm::ARMTargetLowering::isFPImmLegal(), llvm::ARMSubtarget::isLittle(), llvm_unreachable, llvm::MipsISD::Lo, llvm::APInt::lshr(), llvm::MVEVMVNModImm, llvm::OtherModImm, llvm::MVT::SimpleTy, llvm::ARM_MB::ST, std::swap(), llvm::APInt::trunc(), llvm::ARMSubtarget::useNEONForSinglePrecisionFP(), llvm::MVT::v16i8, llvm::MVT::v1i64, llvm::MVT::v2f32, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::MVT::v8i8, llvm::ARMISD::VMOVDRR, llvm::ARMISD::VMOVFPIMM, llvm::ARMISD::VMOVIMM, llvm::VMOVModImm, llvm::ARMISD::VMOVSR, llvm::ARMISD::VMVNIMM, and llvm::VMVNModImm.
Referenced by LowerBUILD_VECTOR_i1(), PerformANDCombine(), and PerformORCombine().
isVMOVNMask()
static bool isVMOVNMask (ArrayRef< int > M, EVT VT, bool Top) static
Definition at line 7044 of file ARMISelLowering.cpp.
References llvm::EVT::getVectorNumElements(), llvm::ArrayRef< T >::size(), llvm::MVT::v16i8, and llvm::MVT::v8i16.
Referenced by llvm::ARMTargetLowering::isShuffleMaskLegal(), and LowerVECTOR_SHUFFLE().
isVREVMask()
static bool isVREVMask (ArrayRef< int > M, EVT VT, unsigned BlockSize) static
isVREVMask - Check if a vector shuffle corresponds to a VREV instruction with the specified blocksize.
(The order of the elements within each block of the vector is reversed.)
Definition at line 6746 of file ARMISelLowering.cpp.
References assert(), llvm::EVT::getScalarSizeInBits(), and llvm::EVT::getVectorNumElements().
Referenced by llvm::ARMTargetLowering::isShuffleMaskLegal(), and LowerVECTOR_SHUFFLE().
isVShiftLImm()
static bool isVShiftLImm (SDValue Op, EVT VT, bool isLong, int64_t & Cnt) static
isVShiftLImm - Check if this is a valid build_vector for the immediate operand of a vector shift left operation.
That value must be in the range: 0 <= Value < ElementBits for a left shift; or 0 <= Value <= ElementBits for a long left shift.
Definition at line 6058 of file ARMISelLowering.cpp.
References assert(), llvm::EVT::getScalarSizeInBits(), getVShiftImm(), and llvm::EVT::isVector().
Referenced by LowerShift(), PerformIntrinsicCombine(), and PerformShiftCombine().
isVShiftRImm()
static bool isVShiftRImm (SDValue Op, EVT VT, bool isNarrow, bool isIntrinsic, int64_t & Cnt) static
isVShiftRImm - Check if this is a valid build_vector for the immediate operand of a vector shift right operation.
For a shift opcode, the value is positive, but for an intrinsic the value count must be negative. The absolute value must be in the range: 1 <= |Value| <= ElementBits for a right shift; or 1 <= |Value| <= ElementBits/2 for a narrow right shift.
Definition at line 6072 of file ARMISelLowering.cpp.
References assert(), llvm::EVT::getScalarSizeInBits(), getVShiftImm(), and llvm::EVT::isVector().
Referenced by LowerShift(), PerformIntrinsicCombine(), and PerformShiftCombine().
isVTBLMask()
static bool isVTBLMask (ArrayRef< int > M, EVT VT) static
Definition at line 6772 of file ARMISelLowering.cpp.
References llvm::ArrayRef< T >::size(), and llvm::MVT::v8i8.
Referenced by llvm::ARMTargetLowering::isShuffleMaskLegal().
isVTRN_v_undef_Mask()
static bool isVTRN_v_undef_Mask (ArrayRef< int > M, EVT VT, unsigned & WhichResult) static
isVTRN_v_undef_Mask - Special case of isVTRNMask for canonical form of "vector_shuffle v, v", i.e., "vector_shuffle v, undef".
Mask is e.g., <0, 0, 2, 2> instead of <0, 4, 2, 6>.
Definition at line 6839 of file ARMISelLowering.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorNumElements(), SelectPairHalf(), and llvm::ArrayRef< T >::size().
Referenced by isNEONTwoResultShuffleMask().
isVTRNMask()
static bool isVTRNMask (ArrayRef< int > M, EVT VT, unsigned & WhichResult) static
Definition at line 6807 of file ARMISelLowering.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorNumElements(), SelectPairHalf(), and llvm::ArrayRef< T >::size().
Referenced by isNEONTwoResultShuffleMask().
isVUZP_v_undef_Mask()
static bool isVUZP_v_undef_Mask (ArrayRef< int > M, EVT VT, unsigned & WhichResult) static
isVUZP_v_undef_Mask - Special case of isVUZPMask for canonical form of "vector_shuffle v, v", i.e., "vector_shuffle v, undef".
Mask is e.g., <0, 2, 0, 2> instead of <0, 2, 4, 6>,
Definition at line 6901 of file ARMISelLowering.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::EVT::is64BitVector(), SelectPairHalf(), and llvm::ArrayRef< T >::size().
Referenced by isNEONTwoResultShuffleMask().
isVUZPMask()
static bool isVUZPMask (ArrayRef< int > M, EVT VT, unsigned & WhichResult) static
Definition at line 6871 of file ARMISelLowering.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::EVT::is64BitVector(), SelectPairHalf(), and llvm::ArrayRef< T >::size().
Referenced by isNEONTwoResultShuffleMask().
IsVUZPShuffleNode()
static bool IsVUZPShuffleNode (SDNode * N) static
Definition at line 11092 of file ARMISelLowering.cpp.
References llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), llvm::MVT::v2i32, llvm::ARMISD::VTRN, and llvm::ARMISD::VUZP.
Referenced by AddCombineToVPADD(), and AddCombineVUZPToVPADDL().
isVZIP_v_undef_Mask()
static bool isVZIP_v_undef_Mask (ArrayRef< int > M, EVT VT, unsigned & WhichResult) static
isVZIP_v_undef_Mask - Special case of isVZIPMask for canonical form of "vector_shuffle v, v", i.e., "vector_shuffle v, undef".
Mask is e.g., <0, 0, 1, 1> instead of <0, 4, 1, 5>.
Definition at line 6975 of file ARMISelLowering.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::EVT::is64BitVector(), SelectPairHalf(), and llvm::ArrayRef< T >::size().
Referenced by isNEONTwoResultShuffleMask().
isVZIPMask()
static bool isVZIPMask (ArrayRef< int > M, EVT VT, unsigned & WhichResult) static
Definition at line 6942 of file ARMISelLowering.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::EVT::is64BitVector(), SelectPairHalf(), and llvm::ArrayRef< T >::size().
Referenced by isNEONTwoResultShuffleMask().
isZeroExtended()
static bool isZeroExtended (SDNode * N, SelectionDAG & DAG) static
isZeroExtended - Check if a node is a vector value that is zero-extended or a constant BUILD_VECTOR with zero-extended elements.
Definition at line 8423 of file ARMISelLowering.cpp.
References llvm::SDNode::getOpcode(), isExtendedBUILD_VECTOR(), llvm::ISD::isZEXTLoad(), and llvm::ISD::ZERO_EXTEND.
Referenced by isAddSubZExt(), and LowerMUL().
isZeroOrAllOnes()
static bool isZeroOrAllOnes (SDValue N, bool AllOnes) inline static
Definition at line 10963 of file ARMISelLowering.cpp.
References llvm::isAllOnesConstant(), and llvm::isNullConstant().
Referenced by isConditionalZeroOrAllOnes().
isZeroVector()
static bool isZeroVector (SDValue N) static
Definition at line 9133 of file ARMISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ISD::isBuildVectorAllZeros(), llvm::isNullConstant(), and llvm::ARMISD::VMOVIMM.
Referenced by LowerMLOAD(), and PerformSUBCombine().
LowerADDSUBCARRY()
static SDValue LowerADDSUBCARRY (SDValue Op, SelectionDAG & DAG) static
Definition at line 8827 of file ARMISelLowering.cpp.
References llvm::ISD::ADDCARRY, llvm::ARMISD::ADDE, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), llvm::StructType::get(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::MVT::i32, llvm::ARMSubtarget::isAPCS_ABI(), llvm::ARMSubtarget::isTargetDarwin(), llvm::ISD::MERGE_VALUES, llvm::ISD::SUB, and llvm::ARMISD::SUBE.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerATOMIC_FENCE()
static SDValue LowerATOMIC_FENCE (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
Definition at line 3788 of file ARMISelLowering.cpp.
References assert(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::ConstantSDNode::getZExtValue(), llvm::ARMSubtarget::hasDataBarrier(), llvm::ARMSubtarget::hasV6Ops(), llvm::MVT::i32, llvm::ISD::INTRINSIC_VOID, llvm::ARM_MB::ISH, llvm::ARM_MB::ISHST, llvm::ARMSubtarget::isMClass(), llvm::ARMSubtarget::isThumb(), llvm::ARMISD::MEMBARRIER_MCR, llvm::MVT::Other, llvm::ARMSubtarget::preferISHSTBarriers(), llvm::Release, llvm::SyncScope::SingleThread, and llvm::ARM_MB::SY.
Referenced by llvm::XCoreTargetLowering::getExceptionSelectorRegister(), llvm::HexagonTargetLowering::isCtlzFast(), and llvm::ARMTargetLowering::LowerOperation().
LowerAtomicLoadStore()
static SDValue LowerAtomicLoadStore (SDValue Op, SelectionDAG & DAG) static
Definition at line 9165 of file ARMISelLowering.cpp.
References llvm::isStrongerThanMonotonic().
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerBUILD_VECTOR_i1()
static SDValue LowerBUILD_VECTOR_i1 (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 7087 of file ARMISelLowering.cpp.
References llvm::all_of(), assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::ISD::BITCAST, llvm::EVT::bitsLT(), llvm::ARMISD::BUILD_VECTOR, llvm::ISD::BUILD_VECTOR, llvm::TargetLowering::buildLegalVectorShuffle(), llvm::ISD::CONCAT_VECTORS, llvm::dyn_cast(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MipsISD::Ext, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f16, llvm::MVT::f32, false, llvm::find(), llvm::SDUse::get(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getFloatingPointVT(), llvm::ARM_AM::getFP32Imm(), llvm::APInt::getLimitedValue(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::APInt::getZExtValue(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ARMSubtarget::hasNEON(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::ISD::INSERT_VECTOR_ELT, llvm::EVT::is128BitVector(), llvm::APInt::isAllOnesValue(), isConstant(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::EVT::isFloatingPoint(), llvm::ISD::isNormalLoad(), IsSingleInstrConstant(), llvm::SDValue::isUndef(), isVMOVModifiedImm(), LLVM_DEBUG, llvm::Lower, llvm::makeArrayRef(), llvm::BitmaskEnumDetail::Mask(), llvm::max(), llvm::MVEVMVNModImm, N, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::operator==(), llvm::ARMISD::PREDICATE_CAST, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SIGN_EXTEND_INREG, llvm::SmallVectorBase::size(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::Sched::Source, llvm::Upper, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::ARMISD::VDUP, llvm::ARMISD::VDUPLANE, llvm::ARMISD::VEXT, llvm::ARMISD::VMOVFPIMM, llvm::ARMISD::VMOVIMM, llvm::VMOVModImm, llvm::ARMISD::VMVNIMM, and llvm::VMVNModImm.
LowerCONCAT_VECTORS()
static SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8295 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::MVT::f64, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ISD::INSERT_VECTOR_ELT, llvm::EVT::is128BitVector(), llvm::SDValue::isUndef(), LowerCONCAT_VECTORS_i1(), and llvm::MVT::v2f64.
Referenced by llvm::NVPTXTargetLowering::isCheapToSpeculateCtlz(), llvm::HexagonTargetLowering::isCtlzFast(), llvm::ARMTargetLowering::LowerOperation(), LowerSDIV(), LowerUDIV(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerCONCAT_VECTORS_i1()
static SDValue LowerCONCAT_VECTORS_i1 (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8243 of file ARMISelLowering.cpp.
References assert(), llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVectorTyFromPredicateVector(), llvm::MVT::getVectorVT(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::ARMCC::NE, PromoteMVEPredVector(), llvm::ISD::UNDEF, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::ARMISD::VCMPZ.
Referenced by LowerCONCAT_VECTORS().
LowerCTPOP()
static SDValue LowerCTPOP (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 6001 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::CTPOP, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::MVT::getVectorVT(), llvm::ARMSubtarget::hasNEON(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::is64BitVector(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MVT::v16i8, llvm::MVT::v1i64, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::MVT::v8i8.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerCTTZ()
static SDValue LowerCTTZ (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 5945 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::BITREVERSE, llvm::tgtok::Bits, llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), getZeroVector(), llvm::ARMSubtarget::hasNEON(), llvm::ARMSubtarget::hasV6T2Ops(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::EVT::isVector(), llvm::ISD::SUB, llvm::ARMISD::VMOVIMM, and X.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerEXTRACT_SUBVECTOR()
static SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8320 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVectorTyFromPredicateVector(), llvm::MVT::getVectorVT(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::ARMCC::NE, PromoteMVEPredVector(), llvm::ISD::UNDEF, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::ARMISD::VCMPZ.
Referenced by llvm::HexagonTargetLowering::isCtlzFast(), llvm::ARMTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerEXTRACT_VECTOR_ELT()
static SDValue LowerEXTRACT_VECTOR_ELT (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8222 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getValueType(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::MVT::i32, LowerEXTRACT_VECTOR_ELT_i1(), and llvm::ARMISD::VGETLANEu.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), llvm::NVPTXTargetLowering::isCheapToSpeculateCtlz(), llvm::HexagonTargetLowering::isCtlzFast(), llvm::ARMTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerEXTRACT_VECTOR_ELT_i1()
static SDValue LowerEXTRACT_VECTOR_ELT_i1 (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8204 of file ARMISelLowering.cpp.
References assert(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), getVectorTyFromPredicateVector(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::MVT::i32, llvm::ARMISD::PREDICATE_CAST, and llvm::ISD::SRL.
Referenced by LowerEXTRACT_VECTOR_ELT().
LowerINSERT_VECTOR_ELT_i1()
static SDValue LowerINSERT_VECTOR_ELT_i1 (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8141 of file ARMISelLowering.cpp.
References assert(), llvm::ARMISD::BFI, llvm::AMDGPUISD::BFI, llvm::ISD::BITCAST, llvm::MipsISD::Ext, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::TargetLoweringBase::getTypeAction(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::EVT::getVectorNumElements(), getVectorTyFromPredicateVector(), llvm::EVT::getVectorVT(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::MVT::i1, llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::BitmaskEnumDetail::Mask(), llvm::ARMISD::PREDICATE_CAST, llvm::ISD::SIGN_EXTEND_INREG, and llvm::TargetLoweringBase::TypePromoteFloat.
LowerInterruptReturn()
static SDValue LowerInterruptReturn (SmallVectorImpl< SDValue > & RetOps, const SDLoc & DL, SelectionDAG & DAG) static
Definition at line 2722 of file ARMISelLowering.cpp.
References llvm::CCState::AnalyzeReturn(), Arg, assert(), llvm::CCValAssign::BCvt, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ISD::BITCAST, llvm::ARMTargetLowering::CCAssignFnForReturn(), contains(), Copies, llvm::ISD::CopyToReg, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::ISD::EXTRACT_VECTOR_ELT, F(), llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::Full, llvm::ARMBaseRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::MVT::getFloatingPointVT(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getRegister(), llvm::ARMSubtarget::getRegisterInfo(), llvm::SDValue::getValue(), llvm::Attribute::getValueAsString(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::Function::hasFnAttribute(), llvm::ARMSubtarget::hasFullFP16(), llvm::SDNode::hasNUsesOfValue(), llvm::SDNode::hasOneUse(), I, llvm::MVT::i16, llvm::MVT::i32, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::ARMISD::INTRET_FLAG, llvm::ARMSubtarget::isLittle(), llvm::ARMSubtarget::isMClass(), llvm::CCValAssign::isRegLoc(), llvm::CallInst::isTailCall(), llvm::ARMSubtarget::isTargetHardFloat(), llvm::ARMSubtarget::isThumb1Only(), llvm_unreachable, N, llvm::CCValAssign::needsCustom(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), llvm::ARMISD::RET_FLAG, llvm::ARMFunctionInfo::setReturnRegsCount(), llvm::SmallVectorBase::size(), llvm::SmallPtrSetImplBase::size(), llvm::ARMSubtarget::supportsTailCall(), TRI, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::MVT::v2f64, llvm::ARMISD::VMOVRRD, and llvm::ISD::ZERO_EXTEND.
LowerMLOAD()
static SDValue LowerMLOAD (SDValue Op, SelectionDAG & DAG) static
Definition at line 9139 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::MaskedLoadStoreSDNode::getAddressingMode(), llvm::MaskedLoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MaskedLoadSDNode::getExtensionType(), llvm::MaskedLoadSDNode::getMask(), llvm::SelectionDAG::getMaskedLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MaskedLoadSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::MaskedLoadSDNode::getPassThru(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), llvm::MVT::i32, llvm::MaskedLoadSDNode::isExpandingLoad(), llvm::SDValue::isUndef(), isZeroVector(), llvm::BitmaskEnumDetail::Mask(), llvm::ARMISD::VMOVIMM, and llvm::ISD::VSELECT.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerMUL()
static SDValue LowerMUL (SDValue Op, SelectionDAG & DAG) static
Definition at line 8569 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::is128BitVector(), llvm::EVT::is64BitVector(), isAddSubSExt(), isAddSubZExt(), llvm::EVT::isInteger(), isSignExtended(), isZeroExtended(), SkipExtensionForVMULL(), std::swap(), llvm::MVT::v2i64, llvm::ARMISD::VMULLs, and llvm::ARMISD::VMULLu.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerPredicateLoad()
static SDValue LowerPredicateLoad (SDValue Op, SelectionDAG & DAG) static
Definition at line 9074 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::EVT::getIntegerVT(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::LSBaseSDNode::isUnindexed(), llvm::ARM_MB::LD, llvm::SPII::Load, llvm::ISD::NON_EXTLOAD, llvm::ARMISD::PREDICATE_CAST, llvm::MVT::v16i1, llvm::MVT::v4i1, and llvm::MVT::v8i1.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerPredicateStore()
static SDValue LowerPredicateStore (SDValue Op, SelectionDAG & DAG) static
Definition at line 9104 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getUNDEF(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), I, llvm::MVT::i32, llvm::StoreSDNode::isTruncatingStore(), llvm::LSBaseSDNode::isUnindexed(), llvm::ARMISD::PREDICATE_CAST, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MVT::v16i1, llvm::MVT::v4i1, and llvm::MVT::v8i1.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerPREFETCH()
static SDValue LowerPREFETCH (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
Definition at line 3825 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::ARMSubtarget::hasMPExtension(), llvm::ARMSubtarget::hasV5TEOps(), llvm::ARMSubtarget::hasV7Ops(), llvm::MVT::i32, llvm::ARMSubtarget::isThumb(), llvm::ARMSubtarget::isThumb1Only(), llvm::ARMSubtarget::isThumb2(), llvm::MVT::Other, and llvm::ARMISD::PRELOAD.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerReverse_VECTOR_SHUFFLEv16i8_v8i16()
static SDValue LowerReverse_VECTOR_SHUFFLEv16i8_v8i16 (SDValue Op, SelectionDAG & DAG) static
Definition at line 7749 of file ARMISelLowering.cpp.
References assert(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::v16i8, llvm::MVT::v8i16, llvm::ARMISD::VEXT, and llvm::ARMISD::VREV64.
Referenced by LowerVECTOR_SHUFFLE().
LowerSADDSUBSAT()
static SDValue LowerSADDSUBSAT (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
Definition at line 4549 of file ARMISelLowering.cpp.
References llvm::MCID::Add, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getSimpleVT(), llvm::SDValue::getValueType(), llvm::ARMSubtarget::hasDSP(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::EVT::isSimple(), llvm::ARMISD::QADD16b, llvm::ARMISD::QADD8b, llvm::ARMISD::QSUB16b, llvm::ARMISD::QSUB8b, llvm::ISD::SADDSAT, llvm::MVT::SimpleTy, and llvm::ISD::TRUNCATE.
Referenced by llvm::ARMTargetLowering::LowerOperation(), and llvm::ARMTargetLowering::ReplaceNodeResults().
LowerSDIV()
static SDValue LowerSDIV (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8714 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), LowerCONCAT_VECTORS(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::ISD::SIGN_EXTEND, llvm::ISD::TRUNCATE, llvm::MVT::v4i16, llvm::MVT::v8i16, and llvm::MVT::v8i8.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerSDIV_v4i16()
static SDValue LowerSDIV_v4i16 (SDValue N0, SDValue N1, const SDLoc & dl, SelectionDAG & DAG) static
Definition at line 8675 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::TRUNCATE, llvm::MVT::v4f32, llvm::MVT::v4i16, and llvm::MVT::v4i32.
Referenced by LowerSDIV(), and LowerUDIV().
LowerSDIV_v4i8()
static SDValue LowerSDIV_v4i8 (SDValue X, SDValue Y, const SDLoc & dl, SelectionDAG & DAG) static
Definition at line 8644 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::TRUNCATE, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, X, and Y.
Referenced by LowerSDIV().
LowerSETCCCARRY()
static SDValue LowerSETCCCARRY (SDValue Op, SelectionDAG & DAG) static
Definition at line 6392 of file ARMISelLowering.cpp.
References llvm::SDValue::getOperand().
Referenced by llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), and llvm::ARMTargetLowering::LowerOperation().
LowerShift()
static SDValue LowerShift (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 6087 of file ARMISelLowering.cpp.
References assert(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), getZeroVector(), llvm::MVT::i32, llvm::EVT::isVector(), isVShiftLImm(), isVShiftRImm(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ARMISD::VSHLIMM, llvm::ARMISD::VSHLs, llvm::ARMISD::VSHLu, llvm::ARMISD::VSHRsIMM, and llvm::ARMISD::VSHRuIMM.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerUDIV()
static SDValue LowerUDIV (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 8750 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, LowerCONCAT_VECTORS(), LowerSDIV_v4i16(), llvm::ISD::SINT_TO_FP, llvm::ISD::TRUNCATE, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::MVT::v8i8, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerVASTART()
static SDValue LowerVASTART (SDValue Op, SelectionDAG & DAG) static
Definition at line 3852 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::CCState::AnalyzeFormalArguments(), llvm::Function::arg_begin(), llvm::array_lengthof(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::ARMTargetLowering::CCAssignFnForCall(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::numbers::e, llvm::SmallVectorBase::empty(), llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FrameIndex, llvm::CCValAssign::Full, llvm::ISD::ArgFlagsTy::getByValSize(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::CCState::getFirstUnallocated(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::CCState::getInRegsParamInfo(), llvm::CCState::getInRegsParamsCount(), llvm::CCState::getInRegsParamsProcessed(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::CCValAssign::getValNo(), llvm::SDValue::getValue(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::ARMFunctionInfo::getVarArgsFrameIndex(), llvm::MachineFrameInfo::hasVAStart(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::ArgFlagsTy::isByVal(), llvm::ARMSubtarget::isLittle(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::ARMFunctionInfo::isThumb1OnlyFunction(), llvm_unreachable, llvm::max(), llvm::CCValAssign::needsCustom(), llvm::CCState::nextInRegsParam(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), R4, Reg, llvm::CCState::rewindByValRegsInfo(), llvm::ARMFunctionInfo::setArgRegsSaveSize(), llvm::ARMFunctionInfo::setArgumentStackSize(), llvm::ARMFunctionInfo::setPreservesR0(), llvm::ARMFunctionInfo::setVarArgsFrameIndex(), llvm::CCValAssign::SExt, llvm::SPII::Store, std::swap(), llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::ISD::UNDEF, llvm::MVT::v2f64, llvm::MVT::v4f16, llvm::MVT::v8f16, llvm::ARMISD::VMOVDRR, and llvm::CCValAssign::ZExt.
Referenced by llvm::ARMTargetLowering::LowerOperation().
LowerVECTOR_SHUFFLE()
static SDValue LowerVECTOR_SHUFFLE (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 7940 of file ARMISelLowering.cpp.
References llvm::all_of(), assert(), llvm::ISD::BITCAST, llvm::ARMISD::BUILD_VECTOR, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, GeneratePerfectShuffle(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getFloatingPointVT(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ARMSubtarget::hasNEON(), llvm::MVT::i32, isLegalMVEShuffleOp(), isNEONTwoResultShuffleMask(), isReverseMask(), isSingletonVEXTMask(), llvm::ShuffleVectorSDNode::isSplat(), llvm::SDValue::isUndef(), llvm::SDNode::isUndef(), isVEXTMask(), isVMOVNMask(), isVREVMask(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerVECTOR_SHUFFLE_i1(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVECTOR_SHUFFLEv8i8(), PerfectShuffleTable, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, std::swap(), llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v8i16, llvm::MVT::v8i8, llvm::ARMISD::VDUP, llvm::ARMISD::VDUPLANE, llvm::ARMISD::VEXT, llvm::ARMISD::VMOVN, llvm::ARMISD::VREV16, llvm::ARMISD::VREV32, and llvm::ARMISD::VREV64.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::HexagonTargetLowering::isCtlzFast(), llvm::ARMTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerVECTOR_SHUFFLE_i1()
static SDValue LowerVECTOR_SHUFFLE_i1 (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 7814 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::BITREVERSE, llvm::cast(), llvm::SelectionDAG::getConstant(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::MVT::i32, isReverseMask(), llvm::ARMCC::NE, llvm::ARMISD::PREDICATE_CAST, PromoteMVEPredVector(), llvm::ISD::SRL, and llvm::ARMISD::VCMPZ.
Referenced by LowerVECTOR_SHUFFLE().
LowerVECTOR_SHUFFLEUsingMovs()
static SDValue LowerVECTOR_SHUFFLEUsingMovs (SDValue Op, ArrayRef< int > ShuffleMask, SelectionDAG & DAG) static
Definition at line 7854 of file ARMISelLowering.cpp.
References assert(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::v16i8, llvm::MVT::v8f16, and llvm::MVT::v8i16.
Referenced by LowerVECTOR_SHUFFLE().
LowerVECTOR_SHUFFLEv8i8()
static SDValue LowerVECTOR_SHUFFLEv8i8 (SDValue Op, ArrayRef< int > ShuffleMask, SelectionDAG & DAG) static
Definition at line 7728 of file ARMISelLowering.cpp.
References llvm::ArrayRef< T >::begin(), E, llvm::ArrayRef< T >::end(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), I, llvm::MVT::i32, llvm::SDNode::isUndef(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v8i8, llvm::ARMISD::VTBL1, and llvm::ARMISD::VTBL2.
Referenced by LowerVECTOR_SHUFFLE().
LowerVectorFP_TO_INT()
static SDValue LowerVectorFP_TO_INT (SDValue Op, SelectionDAG & DAG) static
Definition at line 5365 of file ARMISelLowering.cpp.
References llvm::MVT::f32, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::RTLIB::getFPTOSINT(), llvm::RTLIB::getFPTOUINT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSubtarget(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::i32, llvm::SDNode::isStrictFPOpcode(), llvm::EVT::isVector(), llvm_unreachable, llvm::TargetLowering::makeLibCall(), llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::TRUNCATE, llvm::SelectionDAG::UnrollVectorOp(), llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8f16, and llvm::MVT::v8i16.
Referenced by llvm::AArch64TargetLowering::supportSwiftError().
LowerVectorINT_TO_FP()
static SDValue LowerVectorINT_TO_FP (SDValue Op, SelectionDAG & DAG) static
Definition at line 5435 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::ARM_AM::createVMOVModImm(), llvm::StringSwitch< T, R >::Default(), llvm::Depth, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, first, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ARMTargetLowering::getRegClassFor(), llvm::RTLIB::getSINTTOFP(), llvm::SelectionDAG::getSubtarget(), llvm::SelectionDAG::getTargetConstant(), llvm::RTLIB::getUINTTOFP(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVTList(), llvm::ARMSubtarget::hasNEON(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::EVT::isVector(), llvm_unreachable, llvm::MipsISD::Lo, llvm::TargetLowering::makeLibCall(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::OR, Reg, llvm::report_fatal_error(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MachineFrameInfo::setFrameAddressIsTaken(), llvm::MachineFrameInfo::setReturnAddressIsTaken(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::SelectionDAG::UnrollVectorOp(), llvm::MVT::v1i64, llvm::MVT::v2f32, llvm::MVT::v2i32, llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8f16, llvm::MVT::v8i16, llvm::MVT::v8i8, llvm::TargetLowering::verifyReturnAddressArgumentIsConstant(), llvm::ARMISD::VMOVDRR, llvm::ARMISD::VMOVIMM, llvm::ARMISD::VMOVRRD, llvm::ARMISD::VSHLIMM, llvm::ARMISD::VSHRuIMM, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
LowerVSETCC()
static SDValue LowerVSETCC (SDValue Op, SelectionDAG & DAG, const ARMSubtarget * ST) static
Definition at line 6212 of file ARMISelLowering.cpp.
References llvm::ARMCC::AL, llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::EVT::changeVectorElementTypeToInteger(), llvm::ARMCC::EQ, llvm::ARMCC::GE, llvm::SelectionDAG::getCondCode(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ARMCC::GT, llvm::ARMSubtarget::hasMVEFloatOps(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ARMSubtarget::hasNEON(), llvm::ARMCC::HI, llvm::ARMCC::HS, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::isBuildVectorAllZeros(), llvm::EVT::isFloatingPoint(), llvm::ARMCC::LE, LLVM_FALLTHROUGH, llvm_unreachable, llvm::ARMCC::LT, llvm::ARMCC::NE, llvm::ISD::OR, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, std::swap(), llvm::ARMISD::VCMP, llvm::ARMISD::VCMPZ, llvm::ARMISD::VREV64, and llvm::ARMISD::VTST.
Referenced by llvm::ARMTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerWRITE_REGISTER()
static SDValue LowerWRITE_REGISTER (SDValue Op, SelectionDAG & DAG) static
Definition at line 2991 of file ARMISelLowering.cpp.
References assert(), C, llvm::HexagonISD::CP, llvm::ISD::EXTRACT_ELEMENT, llvm::ARMSubtarget::genExecuteOnly(), llvm::ConstantPoolSDNode::getAlignment(), llvm::SelectionDAG::getConstant(), llvm::ConstantPoolSDNode::getConstVal(), llvm::SelectionDAG::getDataLayout(), getFunction(), llvm::MachineFunction::getFunctionNumber(), llvm::MachineFunction::getInfo(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::ConstantPoolSDNode::getType(), llvm::SDValue::getValueType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::GlobalValue::InternalLinkage, llvm::ConstantPoolSDNode::isMachineConstantPoolEntry(), llvm::MipsISD::Lo, llvm::MVT::Other, llvm::ARMISD::Wrapper, and llvm::ISD::WRITE_REGISTER.
Referenced by llvm::ARMTargetLowering::LowerOperation().
MatchingStackOffset()
static bool MatchingStackOffset (SDValue Arg, unsigned Offset, ISD::ArgFlagsTy Flags, MachineFrameInfo & MFI, const MachineRegisterInfo * MRI, const TargetInstrInfo * TII) static
MatchingStackOffset - Return true if the given stack call argument is already available in the same position (relatively) of the caller's incoming argument stack.
Definition at line 2544 of file ARMISelLowering.cpp.
References llvm::CCState::AnalyzeCallOperands(), assert(), C, Callee, llvm::ARMTargetLowering::CCAssignFnForCall(), llvm::ARMTargetLowering::CCAssignFnForReturn(), llvm::CCState::CheckReturn(), Context, llvm::ISD::CopyFromReg, llvm::tgtok::Def, llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorBase::empty(), G, llvm::ARMFunctionInfo::getArgRegsSaveSize(), llvm::Function::getCallingConv(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::FrameIndexSDNode::getIndex(), llvm::MachineFunction::getInfo(), llvm::ARMSubtarget::getInstrInfo(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::SDValue::getNode(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getReg(), llvm::MachineFunction::getRegInfo(), llvm::ARMSubtarget::getRegisterInfo(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetMachine::getTargetTriple(), llvm::SDValue::getValueSizeInBits(), llvm::MachineRegisterInfo::getVRegDef(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::Function::hasFnAttribute(), llvm::CCValAssign::Indirect, llvm::ISD::ArgFlagsTy::isByVal(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::TargetInstrInfo::isLoadFromStackSlot(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSWindows(), llvm::CCValAssign::isRegLoc(), llvm::ARMSubtarget::isThumb1Only(), llvm::Register::isVirtualRegister(), llvm::max(), MRI, llvm::CCValAssign::needsCustom(), llvm::TargetLowering::parametersInCSRMatch(), llvm::CCState::resultsCompatible(), llvm::SmallVectorBase::size(), llvm::ARMSubtarget::supportsTailCall(), TII, TRI, llvm::TT, and llvm::MVT::v2f64.
memOpAlign()
static bool memOpAlign (unsigned DstAlign, unsigned SrcAlign, unsigned AlignCheck) static
Definition at line 14842 of file ARMISelLowering.cpp.
Referenced by llvm::ARMTargetLowering::getOptimalMemOpType().
OtherSucc()
static MachineBasicBlock* OtherSucc (MachineBasicBlock * MBB, MachineBasicBlock * Succ) static
Definition at line 10023 of file ARMISelLowering.cpp.
References E, I, llvm_unreachable, llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
Referenced by llvm::ARMTargetLowering::EmitInstrWithCustomInserter().
ParseBFI()
static SDValue ParseBFI (SDNode * N, APInt & ToMask, APInt & FromMask) static
Definition at line 12607 of file ARMISelLowering.cpp.
References assert(), llvm::ARMISD::BFI, llvm::APInt::countPopulation(), From, llvm::APInt::getBitWidth(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), and llvm::ISD::SRL.
Referenced by FindBFIToCombineWith(), and PerformBFICombine().
PerformABSCombine()
static SDValue PerformABSCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11670 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::TargetLowering::expandABS(), llvm::SDNode::getOpcode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), and llvm::TargetLoweringBase::isOperationLegal().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformADDCombine()
static SDValue PerformADDCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformADDCombine - Target-specific dag combine xforms for ISD::ADD.
Definition at line 11888 of file ARMISelLowering.cpp.
References llvm::SDNode::getOperand(), PerformADDCombineWithOperands(), and PerformSHLSimplify().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformADDCombineWithOperands()
static SDValue PerformADDCombineWithOperands (SDNode * N, SDValue N0, SDValue N1, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformADDCombineWithOperands - Try DAG combinations for an ADD with operands N0 and N1.
This is a helper for PerformADDCombine that is called with the default operands, and if that fails, with commuted operands.
Definition at line 11706 of file ARMISelLowering.cpp.
References AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), combineSelectAndUse(), llvm::SDValue::getNode(), and llvm::SDNode::hasOneUse().
Referenced by PerformADDCombine().
PerformAddcSubcCombine()
static SDValue PerformAddcSubcCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11609 of file ARMISelLowering.cpp.
References llvm::ARMISD::ADDC, llvm::ARMISD::ADDE, C, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getVTList(), llvm::MVT::i32, llvm::isNullConstant(), llvm::isOneConstant(), llvm::ARMSubtarget::isThumb1Only(), and llvm::ARMISD::SUBC.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformADDECombine()
static SDValue PerformADDECombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformADDECombine - Target-specific dag combine transform from ARMISD::ADDC, ARMISD::ADDE, and ISD::MUL_LOHI to MLAL or ARMISD::ADDC, ARMISD::ADDE and ARMISD::UMLAL to ARMISD::UMAAL.
Definition at line 11689 of file ARMISelLowering.cpp.
References AddCombineTo64bitUMAAL(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::ARMSubtarget::isThumb1Only(), and PerformAddeSubeCombine().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformAddeSubeCombine()
static SDValue PerformAddeSubeCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11642 of file ARMISelLowering.cpp.
References AddCombineTo64bitMLAL(), llvm::ARMISD::ADDE, C, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getVTList(), llvm::MVT::i32, llvm::ARMSubtarget::isThumb1Only(), llvm::ISD::SMUL_LOHI, and llvm::ARMISD::SUBE.
Referenced by PerformADDECombine(), and llvm::ARMTargetLowering::PerformDAGCombine().
PerformANDCombine()
static SDValue PerformANDCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 12176 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, CombineANDShift(), combineSelectAndUseCommutative(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::APInt::getZExtValue(), llvm::ARMSubtarget::hasNEON(), llvm::EVT::is128BitVector(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::ARMSubtarget::isThumb1Only(), llvm::TargetLoweringBase::isTypeLegal(), isVMOVModifiedImm(), llvm::OtherModImm, PerformSHLSimplify(), and llvm::ARMISD::VBICIMM.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformARMBUILD_VECTORCombine()
static SDValue PerformARMBUILD_VECTORCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Target-specific dag combine xforms for ARMISD::BUILD_VECTOR.
Definition at line 12848 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), assert(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::EVT::isFloatingPoint(), llvm::SDValue::isUndef(), and llvm::SDNode::use_begin().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformBFICombine()
static SDValue PerformBFICombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 12680 of file ARMISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ARMISD::BFI, llvm::countLeadingZeros(), llvm::countTrailingZeros(), llvm::APInt::countTrailingZeros(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), FindBFIToCombineWith(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::BitmaskEnumDetail::Mask(), ParseBFI(), llvm::SelectionDAG::ReplaceAllUsesWith(), and llvm::ISD::SRL.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformBUILD_VECTORCombine()
static SDValue PerformBUILD_VECTORCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformBUILD_VECTORCombine - Target-specific dag combine xforms for ISD::BUILD_VECTOR.
Definition at line 12815 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MVT::f64, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), hasNormalLoadOperand(), llvm::MVT::i64, PerformVMOVDRRCombine(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformExtendCombine()
static SDValue PerformExtendCombine (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * ST) static
PerformExtendCombine - Target-specific DAG combining for ISD::SIGN_EXTEND, ISD::ZERO_EXTEND, and ISD::ANY_EXTEND.
Definition at line 14093 of file ARMISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ARMSubtarget::hasNEON(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::TargetLoweringBase::isTypeLegal(), llvm_unreachable, PerformSplittingToWideningLoad(), llvm::ISD::SIGN_EXTEND, llvm::ARMISD::VGETLANEs, llvm::ARMISD::VGETLANEu, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformHWLoopCombine()
static SDValue PerformHWLoopCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * ST) static
Definition at line 14277 of file ARMISelLowering.cpp.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformInsertEltCombine()
static SDValue PerformInsertEltCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
PerformInsertEltCombine - Target-specific dag combine xforms for ISD::INSERT_VECTOR_ELT.
Definition at line 12991 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MVT::f64, llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i64, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::isNormalLoad(), and isVolatile().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformIntrinsicCombine()
static SDValue PerformIntrinsicCombine (SDNode * N, SelectionDAG & DAG) static
PerformIntrinsicCombine - ARM-specific DAG combining for intrinsics.
Definition at line 13782 of file ARMISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::i32, isVShiftLImm(), isVShiftRImm(), llvm_unreachable, llvm::ARMISD::VQRSHRNsIMM, llvm::ARMISD::VQRSHRNsuIMM, llvm::ARMISD::VQRSHRNuIMM, llvm::ARMISD::VQSHLsIMM, llvm::ARMISD::VQSHLsuIMM, llvm::ARMISD::VQSHLuIMM, llvm::ARMISD::VQSHRNsIMM, llvm::ARMISD::VQSHRNsuIMM, llvm::ARMISD::VQSHRNuIMM, llvm::ARMISD::VRSHRNIMM, llvm::ARMISD::VRSHRsIMM, llvm::ARMISD::VRSHRuIMM, llvm::ARMISD::VSHLIMM, llvm::ARMISD::VSHRsIMM, llvm::ARMISD::VSHRuIMM, llvm::ARMISD::VSLIIMM, and llvm::ARMISD::VSRIIMM.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformLOADCombine()
static SDValue PerformLOADCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 13438 of file ARMISelLowering.cpp.
References CombineBaseUpdate(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::ISD::isNormalLoad(), llvm::TargetLoweringBase::isTypeLegal(), and llvm::EVT::isVector().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformMULCombine()
static SDValue PerformMULCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 11989 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, C, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::SDNode::getValueType(), llvm::MVT::i32, llvm::EVT::is128BitVector(), llvm::EVT::is64BitVector(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer(), llvm::isPowerOf2_32(), llvm::ARMSubtarget::isThumb1Only(), llvm::Log2_32(), PerformVMULCombine(), llvm::ISD::SHL, and llvm::ISD::SUB.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformORCombine()
static SDValue PerformORCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformORCombine - Target-specific dag combine xforms for ISD::OR.
Definition at line 12483 of file ARMISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, combineSelectAndUseCommutative(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::APInt::getBitWidth(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::APInt::getZExtValue(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ARMSubtarget::hasNEON(), llvm::SDValue::hasOneUse(), llvm::EVT::is128BitVector(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::ARMSubtarget::isThumb1Only(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), isVMOVModifiedImm(), llvm::OtherModImm, PerformORCombine_i1(), PerformORCombineToBFI(), PerformORCombineToSMULWBT(), PerformSHLSimplify(), llvm::MVT::v16i1, llvm::MVT::v2i32, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v8i1, llvm::ARMISD::VBSL, and llvm::ARMISD::VORRIMM.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformORCombine_i1()
static SDValue PerformORCombine_i1 (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 12428 of file ARMISelLowering.cpp.
References llvm::ARMCC::AL, llvm::ISD::AND, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getAllOnesConstant(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ARMCC::getOppositeCondition(), llvm::SDNode::getValueType(), llvm::MVT::i32, llvm::EVT::isFloatingPoint(), isValidMVECond(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ARMISD::VCMP, llvm::ARMISD::VCMPZ, and llvm::ISD::XOR.
Referenced by PerformORCombine().
PerformORCombineToBFI()
static SDValue PerformORCombineToBFI (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 12285 of file ARMISelLowering.cpp.
References llvm::ISD::AND, llvm::ARMISD::BFI, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::countTrailingZeros(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::ARMSubtarget::hasDSP(), llvm::ARMSubtarget::hasV6T2Ops(), llvm::MVT::i32, llvm::ARM::isBitFieldInvertedMask(), llvm::ARMSubtarget::isThumb1Only(), llvm::BitmaskEnumDetail::Mask(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::SHL, and llvm::ISD::SRL.
Referenced by PerformORCombine().
PerformORCombineToSMULWBT()
static SDValue PerformORCombineToSMULWBT (SDNode * OR, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 12225 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::ARMSubtarget::hasDSP(), llvm::ARMSubtarget::hasThumb2(), llvm::ARMSubtarget::hasV6Ops(), llvm::MVT::i32, isS16(), isSHL16(), isSRA16(), isSRL16(), llvm::ARMSubtarget::isThumb(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SHL, llvm::ISD::SMUL_LOHI, llvm::ARMISD::SMULWB, llvm::ARMISD::SMULWT, and llvm::ISD::SRL.
Referenced by PerformORCombine().
PerformPREDICATE_CASTCombine()
static SDValue PerformPREDICATE_CASTCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 12939 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), and llvm::ARMISD::PREDICATE_CAST.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformShiftCombine()
static SDValue PerformShiftCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * ST) static
PerformShiftCombine - Checks for immediate versions of vector shifts and lowers them.
As with the vector shift intrinsics, this is done during DAG combining instead of DAG legalizing because the build_vectors for 64-bit vector element shift counts are generally not legal, and it is hard to see their values after they get legalized to loads from a constant pool.
Definition at line 13941 of file ARMISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BSWAP, C, llvm::countLeadingZeros(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::SDNode::hasOneUse(), llvm::ARMSubtarget::hasV6Ops(), llvm::MVT::i32, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer(), llvm::isMask_32(), llvm::ARMSubtarget::isThumb1Only(), llvm::TargetLoweringBase::isTypeLegal(), isVShiftLImm(), isVShiftRImm(), llvm_unreachable, llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::ROTR, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::MVT::v2i64, llvm::ARMISD::VSHLIMM, llvm::ARMISD::VSHRsIMM, and llvm::ARMISD::VSHRuIMM.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformSHLSimplify()
static SDValue PerformSHLSimplify (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * ST) static
Definition at line 11783 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ARMISD::CMP, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dbgs(), llvm::SDValue::dump(), llvm::SDNode::dump(), llvm::dyn_cast(), llvm::APInt::getBitWidth(), llvm::SelectionDAG::getConstant(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::i32, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::ARMSubtarget::isThumb(), llvm::ARMSubtarget::isThumb1Only(), LLVM_DEBUG, llvm::APInt::lshrInPlace(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::OR, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SUB, llvm::SDNode::uses(), X, and llvm::ISD::XOR.
Referenced by PerformADDCombine(), PerformANDCombine(), PerformORCombine(), and PerformXORCombine().
PerformSplittingToNarrowingStores()
static SDValue PerformSplittingToNarrowingStores (StoreSDNode * St, SelectionDAG & DAG) static
Definition at line 13538 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::MemSDNode::getAAInfo(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getObjectPtrOffset(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getOriginalAlignment(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getTruncStore(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MachinePointerInfo::getWithOffset(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MemSDNode::isSimple(), llvm::StoreSDNode::isTruncatingStore(), llvm::LSBaseSDNode::isUnindexed(), llvm::EVT::isVector(), llvm::MVT::Other, llvm::SPII::Store, llvm::ISD::TokenFactor, and llvm::ISD::TRUNCATE.
Referenced by PerformSTORECombine().
PerformSplittingToWideningLoad()
static SDValue PerformSplittingToWideningLoad (SDNode * N, SelectionDAG & DAG) static
Definition at line 14029 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::MemSDNode::getAAInfo(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getContext(), llvm::LoadSDNode::getExtensionType(), llvm::MachineMemOperand::getFlags(), llvm::EVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getObjectPtrOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MemSDNode::getOriginalAlignment(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MachinePointerInfo::getWithOffset(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::LSBaseSDNode::isIndexed(), llvm::isPowerOf2_32(), llvm::MemSDNode::isSimple(), llvm::EVT::isVector(), llvm::ARM_MB::LD, llvm::ISD::LOAD, llvm::ISD::NON_EXTLOAD, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SEXTLOAD, llvm::ISD::SIGN_EXTEND, llvm::ISD::TokenFactor, llvm::ISD::UNINDEXED, and llvm::ISD::ZEXTLOAD.
Referenced by PerformExtendCombine().
PerformSTORECombine()
static SDValue PerformSTORECombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformSTORECombine - Target-specific dag combine xforms for ISD::STORE.
Definition at line 13591 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::BITCAST, CombineBaseUpdate(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::MemSDNode::getAAInfo(), llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::ARMSubtarget::hasNEON(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::MVT::i64, llvm::DataLayout::isBigEndian(), isBigEndian(), llvm::ISD::isNormalStore(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), N, PerformSplittingToNarrowingStores(), PerformTruncatingStoreCombine(), llvm::SPII::Store, and llvm::ARMISD::VMOVDRR.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformSUBCombine()
static SDValue PerformSUBCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformSUBCombine - Target-specific dag combine xforms for ISD::SUB.
Definition at line 11908 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, combineSelectAndUse(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ARMSubtarget::hasMVEIntegerOps(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::EVT::isVector(), isZeroVector(), llvm::ISD::SUB, llvm::ARMISD::VDUP, and llvm::ARMISD::VMOVIMM.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformTruncatingStoreCombine()
static SDValue PerformTruncatingStoreCombine (StoreSDNode * St, SelectionDAG & DAG) static
Definition at line 13453 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, E, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getIntPtrConstant(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), I, llvm::MVT::i8, llvm::MVT::integer_valuetypes(), llvm::DataLayout::isBigEndian(), llvm::isPowerOf2_32(), llvm::StoreSDNode::isTruncatingStore(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::ISD::TokenFactor.
Referenced by PerformSTORECombine().
PerformUMLALCombine()
static SDValue PerformUMLALCombine (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
Definition at line 11587 of file ARMISelLowering.cpp.
References llvm::ARMISD::ADDC, llvm::ARMISD::ADDE, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getVTList(), llvm::ARMSubtarget::hasDSP(), llvm::ARMSubtarget::hasV6Ops(), llvm::MVT::i32, llvm::isNullConstant(), and llvm::ARMISD::UMAAL.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVCMPCombine()
static SDValue PerformVCMPCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 12956 of file ARMISelLowering.cpp.
References llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), and llvm::ARMSubtarget::hasMVEIntegerOps().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVCVTCombine()
static SDValue PerformVCVTCombine (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
PerformVCVTCombine - VCVT (floating-point to fixed-point, Advanced SIMD) can replace combinations of VMUL and VCVT (floating-point to integer) when the VMUL has a constant operand that is a power of 2.
Example (assume d17 = <float 8.000000e+00, float 8.000000e+00>): vmul.f32 d16, d17, d16 vcvt.s32.f32 d16, d16 becomes: vcvt.s32.f32 d16, d16, #3
Definition at line 13674 of file ARMISelLowering.cpp.
References C, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::SelectionDAG::getConstant(), llvm::BuildVectorSDNode::getConstantFPSplatPow2ToLog2Int(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::ARMSubtarget::hasNEON(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::ISD::TRUNCATE, llvm::MVT::v2i32, and llvm::MVT::v4i32.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVDIVCombine()
static SDValue PerformVDIVCombine (SDNode * N, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
PerformVDIVCombine - VCVT (fixed-point to floating-point, Advanced SIMD) can replace combinations of VCVT (integer to floating-point) and VDIV when the VDIV has a constant operand that is a power of 2.
Example (assume d17 = <float 8.000000e+00, float 8.000000e+00>): vcvt.f32.s32 d16, d16 vdiv.f32 d16, d17, d16 becomes: vcvt.f32.s32 d16, d16, #3
Definition at line 13731 of file ARMISelLowering.cpp.
References C, llvm::SelectionDAG::getConstant(), llvm::BuildVectorSDNode::getConstantFPSplatPow2ToLog2Int(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::ARMSubtarget::hasNEON(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::MVT::v2i32, llvm::MVT::v4i32, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVDUPCombine()
static SDValue PerformVDUPCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformVDUPCombine - Target-specific dag combine xforms for ARMISD::VDUP.
Definition at line 13410 of file ARMISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::MemSDNode::getAlignment(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVTList(), llvm::ARMSubtarget::hasNEON(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::LSBaseSDNode::isUnindexed(), llvm::ARM_MB::LD, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and llvm::ARMISD::VLD1DUP.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVDUPLANECombine()
static SDValue PerformVDUPLANECombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
PerformVDUPLANECombine - Target-specific dag combine xforms for ARMISD::VDUPLANE.
Definition at line 13379 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, CombineVLDDUP(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::ARM_AM::decodeVMOVModImm(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDNode::getValueType(), llvm::ARMISD::VMOVIMM, and llvm::ARMISD::VMVNIMM.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVECTOR_SHUFFLECombine()
static SDValue PerformVECTOR_SHUFFLECombine (SDNode * N, SelectionDAG & DAG) static
PerformVECTOR_SHUFFLECombine - Target-specific dag combine xforms for ISD::VECTOR_SHUFFLE.
Definition at line 13017 of file ARMISelLowering.cpp.
References llvm::ISD::CONCAT_VECTORS, llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SDValue::isUndef(), N, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVLDCombine()
static SDValue PerformVLDCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 13288 of file ARMISelLowering.cpp.
References CombineBaseUpdate(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), and llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVMOVDRRCombine()
static SDValue PerformVMOVDRRCombine (SDNode * N, SelectionDAG & DAG) static
PerformVMOVDRRCombine - Target-specific dag combine xforms for ARMISD::VMOVDRR.
This is also used for BUILD_VECTORs with 2 operands.
Definition at line 12783 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDNode::getValueType(), and llvm::ARMISD::VMOVRRD.
Referenced by PerformBUILD_VECTORCombine(), and llvm::ARMTargetLowering::PerformDAGCombine().
PerformVMOVRRDCombine()
static SDValue PerformVMOVRRDCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformVMOVRRDCombine - Target-specific dag combine xforms for ARMISD::VMOVRRD.
Definition at line 12739 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MVT::f64, llvm::ISD::FrameIndex, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getDataLayout(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::MachinePointerInfo::getWithOffset(), llvm::ARMSubtarget::hasFP64(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::DataLayout::isBigEndian(), llvm::ISD::isNormalLoad(), isVolatile(), llvm::ARM_MB::LD, std::swap(), and llvm::ARMISD::VMOVDRR.
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PerformVMULCombine()
static SDValue PerformVMULCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
PerformVMULCombine Distribute (A + B) * C to (A * C) + (B * C) to take advantage of the special multiplier accumulator forwarding.
vmul d3, d0, d2 vmla d3, d1, d2 is faster than vadd d3, d0, d1 vmul d3, d3, d2
Definition at line 11958 of file ARMISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::ISD::FADD, llvm::ISD::FSUB, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ARMSubtarget::hasVMLxForwarding(), llvm::ISD::MUL, llvm::ISD::SUB, and std::swap().
Referenced by PerformMULCombine().
PerformXORCombine()
static SDValue PerformXORCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI, const ARMSubtarget * Subtarget) static
Definition at line 12583 of file ARMISelLowering.cpp.
References combineSelectAndUseCommutative(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::ARMSubtarget::isThumb1Only(), llvm::TargetLoweringBase::isTypeLegal(), and PerformSHLSimplify().
Referenced by llvm::ARMTargetLowering::PerformDAGCombine().
PromoteMVEPredVector()
static SDValue PromoteMVEPredVector (SDLoc dl, SDValue Pred, EVT VT, SelectionDAG & DAG) static
Definition at line 7779 of file ARMISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ARM_AM::createVMOVModImm(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), getVectorTyFromPredicateVector(), llvm::MVT::i32, llvm::ARMISD::PREDICATE_CAST, llvm::MVT::v16i1, llvm::MVT::v16i8, llvm::ARMISD::VMOVIMM, and llvm::ISD::VSELECT.
Referenced by LowerCONCAT_VECTORS_i1(), LowerEXTRACT_SUBVECTOR(), and LowerVECTOR_SHUFFLE_i1().
promoteToConstantPool()
static SDValue promoteToConstantPool (const ARMTargetLowering * TLI, const GlobalValue * GV, SelectionDAG & DAG, EVT PtrVT, const SDLoc & dl) static
Definition at line 3351 of file ARMISelLowering.cpp.
References allUsersAreInFunction(), llvm::StringRef::bytes_begin(), llvm::StringRef::bytes_end(), ConstpoolPromotionMaxSize, ConstpoolPromotionMaxTotal, llvm::copy(), llvm::ARMConstantPoolConstant::Create(), llvm::dyn_cast(), EnableConstpoolPromotion, llvm::TargetOptions::EnableFastISel, F(), llvm::ConstantDataArray::get(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::ARMFunctionInfo::getGlobalsPromotedToConstantPool(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::DataLayout::getPreferredAlignment(), llvm::ARMFunctionInfo::getPromotedConstpoolIncrease(), llvm::ARMTargetLowering::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::SelectionDAG::getTargetConstantPool(), llvm::DataLayout::getTypeAllocSize(), llvm::MVT::i32, llvm::TargetLowering::isPositionIndependent(), llvm::ARMSubtarget::isROPI(), llvm::ARMFunctionInfo::markGlobalAsPromotedToConstantPool(), llvm::TargetMachine::Options, llvm::ARMFunctionInfo::setPromotedConstpoolIncrease(), llvm::StringRef::size(), and llvm::ARMISD::Wrapper.
Referenced by llvm::ARMTargetLowering::isReadOnly().
ReplaceCMP_SWAP_64Results()
static void ReplaceCMP_SWAP_64Results (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) static
Definition at line 9216 of file ARMISelLowering.cpp.
References llvm::ARMCC::AL, assert(), createGPRPairNode(), FPCCToARMCC(), llvm::SelectionDAG::getCondCode(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i64, llvm::DataLayout::isBigEndian(), isBigEndian(), N, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SETCC, llvm::ISD::SETNE, llvm::SelectionDAG::setNodeMemRefs(), llvm::TargetLowering::softenSetCCOperands(), llvm::ISD::STRICT_FSETCCS, and llvm::MVT::Untyped.
Referenced by llvm::ARMTargetLowering::ReplaceNodeResults().
ReplaceLongIntrinsic()
static void ReplaceLongIntrinsic (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) static
Definition at line 9387 of file ARMISelLowering.cpp.
References llvm::ISD::EXTRACT_ELEMENT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MipsISD::Lo, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ARMISD::SMLALD, llvm::ARMISD::SMLALDX, llvm::ARMISD::SMLSLD, and llvm::ARMISD::SMLSLDX.
Referenced by llvm::ARMTargetLowering::ReplaceNodeResults().
ReplaceREADCYCLECOUNTER()
static void ReplaceREADCYCLECOUNTER (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG, const ARMSubtarget * Subtarget) static
Definition at line 9175 of file ARMISelLowering.cpp.
References llvm::ISD::BUILD_PAIR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_W_CHAIN, llvm::MVT::Other, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::ARMTargetLowering::ReplaceNodeResults().
SearchLoopIntrinsic()
static SDValue SearchLoopIntrinsic (SDValue N, ISD::CondCode & CC, int & Imm, bool & Negate) static
Definition at line 14240 of file ARMISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::ISD::INTRINSIC_W_CHAIN, N, llvm::ISD::SETCC, and llvm::ISD::XOR.
SelectPairHalf()
static unsigned SelectPairHalf (unsigned Elements, ArrayRef< int > Mask, unsigned Index) static
Definition at line 6779 of file ARMISelLowering.cpp.
References llvm::ArrayRef< T >::size().
Referenced by isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), and isVZIPMask().
SkipExtensionForVMULL()
static SDValue SkipExtensionForVMULL (SDNode * N, SelectionDAG & DAG) static
SkipExtensionForVMULL - For a node that is a SIGN_EXTEND, ZERO_EXTEND, extending load, or BUILD_VECTOR with extended elements, return the unextended value.
The unextended vector should be 64 bits so that it can be used as an operand to a VMULL instruction. If the original vector size before extension is less than 64 bits we add a an extension to resize the vector to 64 bits.
Definition at line 8497 of file ARMISelLowering.cpp.
References AddRequiredExtensionForVMULL(), assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, C, llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::MVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::MVT::getVectorVT(), llvm::MVT::i32, llvm::DataLayout::isBigEndian(), llvm::ISD::isSEXTLoad(), llvm::ISD::isZEXTLoad(), llvm::ARM_MB::LD, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SIGN_EXTEND, SkipLoadExtensionForVMULL(), llvm::MVT::v2i32, llvm::MVT::v4i32, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerMUL().
SkipLoadExtensionForVMULL()
static SDValue SkipLoadExtensionForVMULL (LoadSDNode * LD, SelectionDAG & DAG) static
SkipLoadExtensionForVMULL - return a load of the original vector size that does not do any sign/zero extension.
If the original vector is less than 64 bits, an appropriate extension will be added after the load to reach a total size of 64 bits. We have to add the extension separately because ARM does not have a sign/zero extending load for vectors.
Definition at line 8473 of file ARMISelLowering.cpp.
References llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), getExtensionTo64Bits(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), and llvm::MemSDNode::getPointerInfo().
Referenced by SkipExtensionForVMULL().
STATISTIC() [1/4]
STATISTIC (NumTailCalls , "Number of tail calls")
STATISTIC() [2/4]
STATISTIC (NumMovwMovt , "Number of GAs materialized with movw + movt")
STATISTIC() [3/4]
STATISTIC (NumLoopByVals , "Number of loops generated for byval arguments")
STATISTIC() [4/4]
STATISTIC (NumConstpoolPromoted , "Number of constants with their storage promoted into constant pools")
WinDBZCheckDenominator()
static SDValue WinDBZCheckDenominator (SelectionDAG & DAG, SDNode * N, SDValue InChain) static
Definition at line 9038 of file ARMISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_ELEMENT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::MipsISD::Lo, llvm::Lower, llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), Results, llvm::ISD::SRL, llvm::ISD::TRUNCATE, llvm::Upper, and llvm::ARMISD::WIN__DBZCHK.
Variable Documentation
ARMInterworking
cl::opt<bool> ARMInterworking("arm-interworking", cl::Hidden, cl::desc("Enable / disable ARM interworking (for debugging only)"), cl::init(true)) static
Referenced by llvm::ARMTargetLowering::CCAssignFnForReturn().
ConstpoolPromotionMaxSize
cl::opt<unsigned> ConstpoolPromotionMaxSize("arm-promote-constant-max-size", cl::Hidden, cl::desc("Maximum size of constant to promote into a constant pool"), cl::init(64)) static
Referenced by promoteToConstantPool().
ConstpoolPromotionMaxTotal
cl::opt<unsigned> ConstpoolPromotionMaxTotal("arm-promote-constant-max-total", cl::Hidden, cl::desc("Maximum size of ALL constants to promote into a constant pool"), cl::init(128)) static
Referenced by promoteToConstantPool().
EnableConstpoolPromotion
cl::opt<bool> EnableConstpoolPromotion("arm-promote-constant", cl::Hidden, cl::desc("Enable / disable promotion of unnamed_addr constants into " "constant pools"), cl::init(false)) static
Referenced by promoteToConstantPool().
GPRArgRegs
const MCPhysReg GPRArgRegs[] static
Initial value:
= {
  ARM::R0, ARM::R1, ARM::R2, ARM::R3
}
Definition at line 152 of file ARMISelLowering.cpp.
Referenced by llvm::AArch64TargetLowering::CCAssignFnForReturn(), and f64AssignAAPCS().
MVEMaxSupportedInterleaveFactor
cl::opt<unsigned> MVEMaxSupportedInterleaveFactor("mve-max-interleave-factor", cl::Hidden, cl::desc("Maximum interleave factor for MVE VLDn to generate."), cl::init(2)) static
Referenced by llvm::ARMTargetLowering::getMaxSupportedInterleaveFactor().