LLVM: lib/Target/ARM/ARMOptimizeBarriersPass.cpp File Reference
ARMOptimizeBarriersPass.cpp File Reference
#include "ARM.h"
#include "ARMInstrInfo.h"
#include "ARMMachineFunctionInfo.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
Macros
#define DEBUG_TYPE "double barriers"
Functions
STATISTIC (NumDMBsRemoved, "Number of DMBs removed")
static bool CanMovePastDMB (const MachineInstr *MI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "double barriers"
Definition at line 17 of file ARMOptimizeBarriersPass.cpp.
Function Documentation
CanMovePastDMB()
static bool CanMovePastDMB (const MachineInstr * MI) static
Definition at line 42 of file ARMOptimizeBarriersPass.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isReturn(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), and MI.
STATISTIC()
STATISTIC (NumDMBsRemoved , "Number of DMBs removed")