LLVM: lib/Target/ARM/ARMParallelDSP.cpp File Reference
ARMParallelDSP.cpp File Reference
Armv6 introduced instructions to perform 32-bit SIMD operations.
#include "ARM.h"
#include "ARMSubtarget.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/LoopAccessAnalysis.h"
#include "llvm/Analysis/OrderedBasicBlock.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/NoFolder.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Pass.h"
#include "llvm/PassRegistry.h"
#include "llvm/PassSupport.h"
#include "llvm/Support/Debug.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "arm-parallel-dsp"
Functions
STATISTIC (NumSMLAD, "Number of smlad instructions generated")
template<typename MemInst >
static bool AreSequentialAccesses (MemInst *MemOp0, MemInst *MemOp1, const DataLayout &DL, ScalarEvolution &SE)
INITIALIZE_PASS_BEGIN (ARMParallelDSP, "arm-parallel-dsp", "Transform functions to use DSP intrinsics", false, false) INITIALIZE_PASS_END(ARMParallelDSP
Variables
static cl::opt< bool > DisableParallelDSP ("disable-arm-parallel-dsp", cl::Hidden, cl::init(false), cl::desc("Disable the ARM Parallel DSP pass"))
static cl::opt< unsigned > NumLoadLimit ("arm-parallel-dsp-load-limit", cl::Hidden, cl::init(16), cl::desc("Limit the number of loads analysed"))
arm parallel dsp
arm parallel Transform functions to use DSP intrinsics
arm parallel Transform functions to use DSP false
Detailed Description
Armv6 introduced instructions to perform 32-bit SIMD operations.
The purpose of this pass is do some IR pattern matching to create ACLE DSP intrinsics, which map on these 32-bit SIMD operations. This pass runs only when unaligned accesses is supported/enabled.
Definition in file ARMParallelDSP.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-parallel-dsp"
Definition at line 39 of file ARMParallelDSP.cpp.
Function Documentation
AreSequentialAccesses()
template<typename MemInst > static bool AreSequentialAccesses (MemInst * MemOp0, MemInst * MemOp1, const DataLayout & DL, ScalarEvolution & SE) static
Definition at line 303 of file ARMParallelDSP.cpp.
References llvm::MCID::Add, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), B, llvm::SmallVectorImpl< T >::clear(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::OrderedBasicBlock::dominates(), llvm::DominatorTree::dominates(), llvm::Value::dump(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::IntegerType::getBitWidth(), llvm::Intrinsic::getDeclaration(), llvm::AAResults::getModRefInfo(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::LoadInst::getPointerAddressSpace(), llvm::Type::getPointerTo(), llvm::Value::getType(), llvm::GlobalValue::getType(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::intersectModRef(), llvm::isConsecutiveAccess(), llvm::Type::isIntegerTy(), llvm::isModOrRefSet(), LLVM_DEBUG, llvm::Instruction::mayWriteToMemory(), llvm::ModRef, NumLoadLimit, llvm::SmallVectorTemplateBase< T >::push_back(), Reduction, llvm::Value::replaceAllUsesWith(), llvm::reverse(), llvm::cl::Sink, Size, llvm::SmallVectorBase::size(), llvm::sort(), llvm::Sched::Source, llvm::LocationSize::unknown(), and llvm::Instruction::user_back().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ARMParallelDSP , "arm-parallel-dsp" , "Transform functions to use DSP intrinsics" , false , false)
Referenced by llvm::createARMParallelDSPPass().
STATISTIC()
STATISTIC (NumSMLAD , "Number of smlad instructions generated")
Variable Documentation
DisableParallelDSP
cl::opt<bool> DisableParallelDSP("disable-arm-parallel-dsp", cl::Hidden, cl::init(false), cl::desc("Disable the ARM Parallel DSP pass")) static
dsp
arm parallel dsp
Definition at line 818 of file ARMParallelDSP.cpp.
false
arm parallel Transform functions to use DSP false
Definition at line 818 of file ARMParallelDSP.cpp.
intrinsics
arm parallel Transform functions to use DSP intrinsics
Definition at line 818 of file ARMParallelDSP.cpp.
NumLoadLimit
cl::opt<unsigned> NumLoadLimit("arm-parallel-dsp-load-limit", cl::Hidden, cl::init(16), cl::desc("Limit the number of loads analysed")) static
Referenced by AreSequentialAccesses().