LLVM: lib/Target/ARM/ARMSubtarget.cpp File Reference
ARMSubtarget.cpp File Reference
#include "ARM.h"
#include "ARMCallLowering.h"
#include "ARMLegalizerInfo.h"
#include "ARMRegisterBankInfo.h"
#include "ARMSubtarget.h"
#include "ARMFrameLowering.h"
#include "ARMInstrInfo.h"
#include "ARMTargetMachine.h"
#include "MCTargetDesc/ARMMCTargetDesc.h"
#include "Thumb1FrameLowering.h"
#include "Thumb1InstrInfo.h"
#include "Thumb2InstrInfo.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Target/TargetOptions.h"
#include "ARMGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "arm-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Enumerations
enum ITMode { DefaultIT, RestrictedIT, NoRestrictedIT }
Variables
static cl::opt< bool > UseFusedMulOps ("arm-use-mulops", cl::init(true), cl::Hidden)
static cl::opt< ITMode > IT (cl::desc("IT block support"), cl::Hidden, cl::init(DefaultIT), cl::ZeroOrMore, cl::values(clEnumValN(DefaultIT, "arm-default-it", "Generate IT block based on arch"), clEnumValN(RestrictedIT, "arm-restrict-it", "Disallow deprecated IT based on ARMv8"), clEnumValN(NoRestrictedIT, "arm-no-restrict-it", "Allow IT blocks based on ARMv7")))
static cl::opt< bool > ForceFastISel ("arm-force-fast-isel", cl::init(false), cl::Hidden)
ForceFastISel - Use the fast-isel, even for subtargets where it is not currently supported (for testing only).
static cl::opt< bool > EnableSubRegLiveness ("arm-enable-subreg-liveness", cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-subtarget"
Definition at line 43 of file ARMSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 46 of file ARMSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 45 of file ARMSubtarget.cpp.
Enumeration Type Documentation
ITMode
enum ITMode
Enumerator
DefaultIT
RestrictedIT
NoRestrictedIT
Definition at line 53 of file ARMSubtarget.cpp.
Variable Documentation
EnableSubRegLiveness
cl::opt<bool> EnableSubRegLiveness("arm-enable-subreg-liveness", cl::init(false), cl::Hidden) static
Referenced by llvm::ARMSubtarget::enableSubRegLiveness().
ForceFastISel
cl::opt<bool> ForceFastISel("arm-force-fast-isel", cl::init(false), cl::Hidden) static
ForceFastISel - Use the fast-isel, even for subtargets where it is not currently supported (for testing only).
Referenced by llvm::ARMSubtarget::useFastISel().
IT
cl::opt<ITMode> IT(cl::desc("IT block support"), cl::Hidden, cl::init(DefaultIT), cl::ZeroOrMore, cl::values(clEnumValN(DefaultIT, "arm-default-it", "Generate IT block based on arch"), clEnumValN(RestrictedIT, "arm-restrict-it", "Disallow deprecated IT based on ARMv8"), clEnumValN(NoRestrictedIT, "arm-no-restrict-it", "Allow IT blocks based on ARMv7"))) static
Referenced by computeImportForFunction(), llvm::gsym::FunctionInfo::decode(), findInitTrampoline(), foldCtpop(), foldCttzCtlz(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), getComparePred(), llvm::safestack::StackColoring::getLiveRange(), llvm::CacheCost::getLoopCost(), llvm::haveNoCommonBitsSet(), hoistValue(), llvm::ConstantDataSequential::isElementTypeCompatible(), isInSymtab(), llvm::ARMSubtarget::isXRaySupported(), llvm::gsym::FunctionInfo::lookup(), mapBinOpcode(), moveUp(), llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::NormalizedTBD_V4(), postDominates(), llvm::safestack::StackLayout::print(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::remove(), llvm::safestack::StackColoring::removeAllMarkers(), llvm::DirectedGraph< NodeType, EdgeType >::removeNode(), and TypeSizeToSizeIndex().
UseFusedMulOps
cl::opt<bool> UseFusedMulOps("arm-use-mulops", cl::init(true), cl::Hidden) static