LLVM: lib/Target/ARM/ARMTargetObjectFile.cpp File Reference
ARMTargetObjectFile.cpp File Reference
#include "ARMTargetObjectFile.h"
#include "ARMSubtarget.h"
#include "ARMTargetMachine.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
Functions
static bool isExecuteOnlyFunction (const GlobalObject *GO, SectionKind SK, const TargetMachine &TM)
Function Documentation
isExecuteOnlyFunction()
static bool isExecuteOnlyFunction (const GlobalObject * GO, SectionKind SK, const TargetMachine & TM) static
Definition at line 75 of file ARMTargetObjectFile.cpp.
References F(), llvm::ARMSubtarget::genExecuteOnly(), llvm::TargetMachine::getSubtarget(), and llvm::SectionKind::isText().
Referenced by llvm::ARMElfTargetObjectFile::getExplicitSectionGlobal(), and llvm::ARMElfTargetObjectFile::SelectSectionForGlobal().