LLVM: lib/MC/MCParser/AsmLexer.cpp File Reference
AsmLexer.cpp File Reference
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SaveAndRestore.h"
#include <cassert>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <string>
#include <tuple>
#include <utility>
Functions
static bool IsIdentifierChar (char c, bool AllowAt)
LexIdentifier: [a-zA-Z_.][a-zA-Z0-9_$.@?]*.
static void SkipIgnoredIntegerSuffix (const char *&CurPtr)
static unsigned doHexLookAhead (const char *&CurPtr, unsigned DefaultRadix, bool LexHex)
static AsmToken intToken (StringRef Ref, APInt &Value)
Function Documentation
doHexLookAhead()
static unsigned doHexLookAhead (const char *& CurPtr, unsigned DefaultRadix, bool LexHex) static
Definition at line 247 of file AsmLexer.cpp.
References llvm::isDigit(), and llvm::isHexDigit().
Referenced by intToken().
intToken()
static AsmToken intToken (StringRef Ref, APInt & Value) static
Definition at line 272 of file AsmLexer.cpp.
References llvm::AsmToken::BigNum, doHexLookAhead(), llvm::StringRef::drop_back(), llvm::StringRef::getAsInteger(), llvm::AsmToken::Integer, llvm::isDigit(), llvm::isHexDigit(), llvm::APInt::isIntN(), llvm::MCAsmLexer::LexMasmIntegers, SkipIgnoredIntegerSuffix(), llvm::StringRef::startswith(), llvm::AsmToken::String, llvm::StringRef::substr(), and llvm::MCAsmLexer::TokStart.
IsIdentifierChar()
static bool IsIdentifierChar (char c, bool AllowAt) static
LexIdentifier: [a-zA-Z_.][a-zA-Z0-9_$.@?]*.
Definition at line 138 of file AsmLexer.cpp.
References llvm::MCAsmLexer::AllowAtInIdentifier, llvm::AsmToken::Comment, llvm::MCAsmLexer::CommentConsumer, llvm::AsmToken::Dot, llvm::StringRef::end(), llvm::AsmToken::EndOfStatement, llvm::SMLoc::getFromPointer(), llvm::AsmCommentConsumer::HandleComment(), llvm::AsmToken::Identifier, llvm::isAlnum(), llvm::isDigit(), llvm::AsmToken::Slash, and llvm::MCAsmLexer::TokStart.
SkipIgnoredIntegerSuffix()
static void SkipIgnoredIntegerSuffix (const char *& CurPtr) static
Definition at line 235 of file AsmLexer.cpp.
Referenced by intToken().