LLVM: lib/IR/AsmWriter.cpp File Reference
AsmWriter.cpp File Reference
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/AssemblyAnnotationWriter.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalIndirectSymbol.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/TypeFinder.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/UseListOrder.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <memory>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "llvm/IR/Metadata.def"
Classes
class llvm::SlotTracker
This class provides computation of slot numbers for LLVM Assembly writing.
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define ST_DEBUG(X)
#define HANDLE_MDNODE_LEAF(CLASS)
Enumerations
enum PrefixType {
GlobalPrefix, ComdatPrefix, LabelPrefix, LocalPrefix,
NoPrefix
}
Functions
static void orderValue (const Value *V, OrderMap &OM)
static OrderMap orderModule (const Module *M)
static void predictValueUseListOrderImpl (const Value *V, const Function *F, unsigned ID, const OrderMap &OM, UseListOrderStack &Stack)
static void predictValueUseListOrder (const Value *V, const Function *F, OrderMap &OM, UseListOrderStack &Stack)
static UseListOrderStack predictUseListOrder (const Module *M)
static const Module * getModuleFromVal (const Value *V)
static void PrintCallingConv (unsigned cc, raw_ostream &Out)
static void PrintLLVMName (raw_ostream &OS, StringRef Name, PrefixType Prefix)
Turn the specified name into an 'LLVM name', which is either prefixed with % (if the string only contains simple characters) or is surrounded with ""'s (if it has special chars in it).
static void PrintLLVMName (raw_ostream &OS, const Value *V)
Turn the specified name into an 'LLVM name', which is either prefixed with % (if the string only contains simple characters) or is surrounded with ""'s (if it has special chars in it).
static SlotTracker * createSlotTracker (const Value *V)
static void WriteAsOperandInternal (raw_ostream &Out, const Value *V, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void WriteAsOperandInternal (raw_ostream &Out, const Metadata *MD, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context, bool FromValue=false)
static void WriteOptimizationInfo (raw_ostream &Out, const User *U)
static void WriteConstantInternal (raw_ostream &Out, const Constant *CV, TypePrinting &TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeMDTuple (raw_ostream &Out, const MDTuple *Node, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeMetadataAsOperand (raw_ostream &Out, const Metadata *MD, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeGenericDINode (raw_ostream &Out, const GenericDINode *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDILocation (raw_ostream &Out, const DILocation *DL, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDISubrange (raw_ostream &Out, const DISubrange *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIEnumerator (raw_ostream &Out, const DIEnumerator *N, TypePrinting *, SlotTracker *, const Module *)
static void writeDIBasicType (raw_ostream &Out, const DIBasicType *N, TypePrinting *, SlotTracker *, const Module *)
static void writeDIDerivedType (raw_ostream &Out, const DIDerivedType *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDICompositeType (raw_ostream &Out, const DICompositeType *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDISubroutineType (raw_ostream &Out, const DISubroutineType *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIFile (raw_ostream &Out, const DIFile *N, TypePrinting *, SlotTracker *, const Module *)
static void writeDICompileUnit (raw_ostream &Out, const DICompileUnit *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDISubprogram (raw_ostream &Out, const DISubprogram *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDILexicalBlock (raw_ostream &Out, const DILexicalBlock *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDILexicalBlockFile (raw_ostream &Out, const DILexicalBlockFile *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDINamespace (raw_ostream &Out, const DINamespace *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDICommonBlock (raw_ostream &Out, const DICommonBlock *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIMacro (raw_ostream &Out, const DIMacro *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIMacroFile (raw_ostream &Out, const DIMacroFile *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIModule (raw_ostream &Out, const DIModule *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDITemplateTypeParameter (raw_ostream &Out, const DITemplateTypeParameter *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDITemplateValueParameter (raw_ostream &Out, const DITemplateValueParameter *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIGlobalVariable (raw_ostream &Out, const DIGlobalVariable *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDILocalVariable (raw_ostream &Out, const DILocalVariable *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDILabel (raw_ostream &Out, const DILabel *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIExpression (raw_ostream &Out, const DIExpression *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIGlobalVariableExpression (raw_ostream &Out, const DIGlobalVariableExpression *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIObjCProperty (raw_ostream &Out, const DIObjCProperty *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void writeDIImportedEntity (raw_ostream &Out, const DIImportedEntity *N, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void WriteMDNodeBodyInternal (raw_ostream &Out, const MDNode *Node, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static const char * getWholeProgDevirtResKindName (WholeProgramDevirtResolution::Kind K)
static const char * getWholeProgDevirtResByArgKindName (WholeProgramDevirtResolution::ByArg::Kind K)
static const char * getTTResKindName (TypeTestResolution::Kind K)
static const char * getSummaryKindName (GlobalValueSummary::SummaryKind SK)
static std::string getLinkageName (GlobalValue::LinkageTypes LT)
static std::string getLinkageNameWithSpace (GlobalValue::LinkageTypes LT)
static void printMetadataIdentifier (StringRef Name, formatted_raw_ostream &Out)
static void PrintVisibility (GlobalValue::VisibilityTypes Vis, formatted_raw_ostream &Out)
static void PrintDSOLocation (const GlobalValue &GV, formatted_raw_ostream &Out)
static void PrintDLLStorageClass (GlobalValue::DLLStorageClassTypes SCT, formatted_raw_ostream &Out)
static void PrintThreadLocalModel (GlobalVariable::ThreadLocalMode TLM, formatted_raw_ostream &Out)
static StringRef getUnnamedAddrEncoding (GlobalVariable::UnnamedAddr UA)
static void maybePrintComdat (formatted_raw_ostream &Out, const GlobalObject &GO)
static void maybePrintCallAddrSpace (const Value *Operand, const Instruction *I, raw_ostream &Out)
static bool isReferencingMDNode (const Instruction &I)
static bool printWithoutType (const Value &V, raw_ostream &O, SlotTracker *Machine, const Module *M)
Print without a type, skipping the TypePrinting object.
static void printAsOperandImpl (const Value &V, raw_ostream &O, bool PrintType, ModuleSlotTracker &MST)
static void printMetadataImpl (raw_ostream &ROS, const Metadata &MD, ModuleSlotTracker &MST, const Module *M, bool OnlyAsOperand)
Macro Definition Documentation
HANDLE_MDNODE_LEAF
#define HANDLE_MDNODE_LEAF (CLASS)
Value:
case Metadata::CLASS##Kind:                                                  \
    write##CLASS(Out, cast<CLASS>(Node), TypePrinter, Machine, Context);       \
    break;
ST_DEBUG
#define ST_DEBUG (X)
Definition at line 896 of file AsmWriter.cpp.
Referenced by llvm::SlotTracker::initializeIndexIfNeeded(), and llvm::SlotTracker::purgeFunction().
Enumeration Type Documentation
PrefixType
enum PrefixType
Enumerator
GlobalPrefix
ComdatPrefix
LabelPrefix
LocalPrefix
NoPrefix
Definition at line 394 of file AsmWriter.cpp.
Function Documentation
createSlotTracker()
static SlotTracker* createSlotTracker (const Value * V) static
Definition at line 867 of file AsmWriter.cpp.
Referenced by WriteAsOperandInternal().
getLinkageName()
static std::string getLinkageName (GlobalValue::LinkageTypes LT) static
Definition at line 2922 of file AsmWriter.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by getLinkageNameWithSpace(), llvm::DISubprogram::splitFlags(), and llvm::DISubprogram::toSPFlags().
getLinkageNameWithSpace()
static std::string getLinkageNameWithSpace (GlobalValue::LinkageTypes LT) static
Definition at line 2953 of file AsmWriter.cpp.
References llvm::GlobalValueSummary::AliasKind, llvm::FunctionSummary::FFlags::AlwaysInline, assert(), llvm::FunctionSummary::calls(), llvm::GlobalValueSummary::GVFlags::CanAutoHide, llvm::GlobalValueSummary::GVFlags::DSOLocal, llvm::StringRef::empty(), llvm::GlobalValue::ExternalLinkage, llvm::FunctionSummary::fflags(), llvm::GlobalValueSummary::flags(), llvm::X86AS::FS, llvm::GlobalValueSummary::FunctionKind, llvm::ValueInfo::getGUID(), llvm::getHotnessName(), getLinkageName(), llvm::GlobalValueSummary::getSummaryKind(), getSummaryKindName(), llvm::ValueInfo::getSummaryList(), llvm::FunctionSummary::getTypeIdInfo(), llvm::FunctionSummary::VFuncId::GUID, llvm::FunctionSummary::instCount(), llvm::GlobalValueSummary::GVFlags::Linkage, llvm::GlobalValueSummary::GVFlags::Live, llvm::AArch64CC::LT, llvm::GlobalValueSummary::modulePath(), llvm::ValueInfo::name(), llvm::FunctionSummary::FFlags::NoInline, llvm::FunctionSummary::FFlags::NoRecurse, llvm::GlobalValueSummary::GVFlags::NotEligibleToImport, llvm::FunctionSummary::VFuncId::Offset, llvm::FunctionSummary::FFlags::ReadNone, llvm::FunctionSummary::FFlags::ReadOnly, llvm::Ref, llvm::GlobalValueSummary::refs(), llvm::FunctionSummary::FFlags::ReturnDoesNotAlias, llvm::Tag, llvm::FunctionSummary::TypeIdInfo::TypeCheckedLoadConstVCalls, llvm::FunctionSummary::TypeIdInfo::TypeCheckedLoadVCalls, llvm::FunctionSummary::TypeIdInfo::TypeTestAssumeConstVCalls, llvm::FunctionSummary::TypeIdInfo::TypeTestAssumeVCalls, llvm::FunctionSummary::TypeIdInfo::TypeTests, llvm::CalleeInfo::Unknown, and VI.
Referenced by maybePrintComdat().
getModuleFromVal()
static const Module* getModuleFromVal (const Value * V) static
Definition at line 318 of file AsmWriter.cpp.
References llvm::GlobalValue::getParent(), I, and llvm::Value::users().
Referenced by maybePrintCallAddrSpace(), llvm::Value::print(), and llvm::Value::printAsOperand().
getSummaryKindName()
static const char* getSummaryKindName (GlobalValueSummary::SummaryKind SK) static
Definition at line 2881 of file AsmWriter.cpp.
References llvm::GlobalValueSummary::AliasKind, llvm::X86AS::FS, llvm::GlobalValueSummary::FunctionKind, llvm::AliasSummary::getAliasee(), llvm::GlobalValueSummary::GlobalVarKind, llvm::X86AS::GS, llvm::AliasSummary::hasAliasee(), llvm_unreachable, llvm::GlobalVarSummary::GVarFlags::MaybeReadOnly, llvm::GlobalVarSummary::GVarFlags::MaybeWriteOnly, P, llvm::GlobalVarSummary::VarFlags, and llvm::GlobalVarSummary::vTableFuncs().
Referenced by getLinkageNameWithSpace().
getTTResKindName()
static const char* getTTResKindName (TypeTestResolution::Kind K) static
Definition at line 2772 of file AsmWriter.cpp.
References llvm::TypeTestResolution::AlignLog2, llvm::TypeTestResolution::AllOnes, llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::TypeTestResolution::BitMask, llvm::TypeTestResolution::ByteArray, llvm::X86AS::FS, getWholeProgDevirtResByArgKindName(), getWholeProgDevirtResKindName(), if(), llvm::TypeTestResolution::Inline, llvm::TypeTestResolution::InlineBits, llvm_unreachable, P, llvm::WholeProgramDevirtResolution::ResByArg, llvm::TypeTestResolution::Single, llvm::WholeProgramDevirtResolution::SingleImpl, llvm::WholeProgramDevirtResolution::SingleImplName, llvm::TypeTestResolution::SizeM1, llvm::TypeTestResolution::SizeM1BitWidth, llvm::TypeTestResolution::TheKind, llvm::WholeProgramDevirtResolution::TheKind, llvm::TypeIdSummary::TTRes, llvm::WholeProgramDevirtResolution::ByArg::UniformRetVal, llvm::WholeProgramDevirtResolution::ByArg::UniqueRetVal, llvm::TypeTestResolution::Unsat, and llvm::TypeIdSummary::WPDRes.
getUnnamedAddrEncoding()
static StringRef getUnnamedAddrEncoding (GlobalVariable::UnnamedAddr UA) static
Definition at line 3242 of file AsmWriter.cpp.
References llvm::GlobalValue::Global, llvm_unreachable, llvm::GlobalValue::Local, and llvm::GlobalValue::None.
Referenced by maybePrintComdat().
getWholeProgDevirtResByArgKindName()
static const char* getWholeProgDevirtResByArgKindName (WholeProgramDevirtResolution::ByArg::Kind K) static
Definition at line 2757 of file AsmWriter.cpp.
References llvm::WholeProgramDevirtResolution::ByArg::Indir, llvm_unreachable, llvm::WholeProgramDevirtResolution::ByArg::UniformRetVal, llvm::WholeProgramDevirtResolution::ByArg::UniqueRetVal, and llvm::WholeProgramDevirtResolution::ByArg::VirtualConstProp.
Referenced by getTTResKindName().
getWholeProgDevirtResKindName()
static const char* getWholeProgDevirtResKindName (WholeProgramDevirtResolution::Kind K) static
Definition at line 2745 of file AsmWriter.cpp.
References llvm::WholeProgramDevirtResolution::BranchFunnel, llvm::WholeProgramDevirtResolution::Indir, llvm_unreachable, and llvm::WholeProgramDevirtResolution::SingleImpl.
Referenced by getTTResKindName().
isReferencingMDNode()
static bool isReferencingMDNode (const Instruction & I) static
Definition at line 4305 of file AsmWriter.cpp.
References llvm::Function::isIntrinsic(), and llvm::User::operands().
Referenced by llvm::Value::print().
maybePrintCallAddrSpace()
static void maybePrintCallAddrSpace (const Value * Operand, const Instruction * I, raw_ostream & Out) static
Definition at line 3649 of file AsmWriter.cpp.
References llvm::CallingConv::C, llvm::SwitchInst::cases(), llvm::numbers::e, E, llvm::AttributeList::FunctionIndex, GEP, llvm::Instruction::getAllMetadata(), llvm::AttributeList::getAsString(), llvm::AttributeList::getAttributes(), llvm::BranchInst::getCondition(), llvm::SwitchInst::getCondition(), llvm::Module::getDataLayout(), llvm::SwitchInst::getDefaultDest(), llvm::AttributeList::getFnAttributes(), getModuleFromVal(), llvm::User::getNumOperands(), llvm::Instruction::getOpcodeName(), llvm::User::getOperand(), llvm::AtomicRMWInst::getOperationName(), llvm::AttributeList::getParamAttributes(), llvm::Type::getPointerAddressSpace(), llvm::CmpInst::getPredicateName(), llvm::DataLayout::getProgramAddressSpace(), llvm::FunctionType::getReturnType(), llvm::BranchInst::getSuccessor(), llvm::Value::getType(), llvm::AttributeList::hasAttributes(), llvm::Value::hasName(), isAtomic(), llvm::FunctionType::isVarArg(), llvm::Type::isVoidTy(), isVolatile(), llvm::Mod, op, PrintCallingConv(), PrintLLVMName(), printMetadataIdentifier(), llvm::AttributeList::ReturnIndex, second, SI, WriteAsOperandInternal(), and WriteOptimizationInfo().
maybePrintComdat()
static void maybePrintComdat (formatted_raw_ostream & Out, const GlobalObject & GO) static
Definition at line 3254 of file AsmWriter.cpp.
References Arg, llvm::Function::args(), assert(), llvm::CallingConv::C, C, ComdatPrefix, E, llvm::StringRef::empty(), llvm::AttributeList::FunctionIndex, llvm::GlobalValue::getAddressSpace(), llvm::PointerType::getAddressSpace(), llvm::GlobalObject::getAlignment(), llvm::GlobalObject::getAllMetadata(), llvm::AttributeSet::getAsString(), llvm::AttributeList::getAsString(), llvm::GlobalVariable::getAttributes(), llvm::Function::getAttributes(), llvm::GCRelocateInst::getBasePtr(), llvm::Function::getCallingConv(), llvm::GlobalObject::getComdat(), llvm::Module::getDataLayout(), llvm::GCRelocateInst::getDerivedPtr(), llvm::GlobalValue::getDLLStorageClass(), llvm::Function::getEntryBlock(), llvm::AttributeList::getFnAttributes(), llvm::Function::getFunctionType(), llvm::Function::getGC(), llvm::GlobalIndirectSymbol::getIndirectSymbol(), llvm::GlobalVariable::getInitializer(), llvm::GlobalValue::getLinkage(), getLinkageNameWithSpace(), getName(), llvm::Comdat::getName(), llvm::Value::getName(), llvm::FunctionType::getNumParams(), llvm::AttributeList::getParamAttributes(), llvm::FunctionType::getParamType(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::GlobalValue::getPartition(), llvm::Function::getPersonalityFn(), llvm::Function::getPrefixData(), llvm::DataLayout::getProgramAddressSpace(), llvm::Function::getPrologueData(), llvm::Function::getReturnType(), llvm::GlobalObject::getSection(), llvm::GlobalValue::getThreadLocalMode(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::GlobalValue::getUnnamedAddr(), getUnnamedAddrEncoding(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::getVisibility(), llvm::AttributeSet::hasAttributes(), llvm::AttributeList::hasAttributes(), llvm::GlobalValue::hasExternalLinkage(), llvm::Function::hasGC(), llvm::GlobalVariable::hasInitializer(), llvm::Value::hasName(), llvm::GlobalValue::hasPartition(), llvm::Function::hasPersonalityFn(), llvm::Function::hasPrefixData(), llvm::Function::hasPrologueData(), llvm::GlobalObject::hasSection(), I, llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDeclaration(), llvm::GlobalVariable::isExternallyInitialized(), llvm::Function::isMaterializable(), llvm::GlobalValue::isMaterializable(), llvm::FunctionType::isVarArg(), LabelPrefix, llvm_unreachable, LocalPrefix, llvm::Mod, llvm::pred_begin(), llvm::pred_end(), llvm::Comdat::print(), PrintCallingConv(), PrintDLLStorageClass(), PrintDSOLocation(), llvm::printEscapedString(), PrintLLVMName(), PrintThreadLocalModel(), PrintVisibility(), llvm::AttributeList::ReturnIndex, and WriteAsOperandInternal().
orderModule()
static OrderMap orderModule (const Module * M) static
Definition at line 134 of file AsmWriter.cpp.
References llvm::Module::aliases(), F(), G, llvm::Module::globals(), I, llvm::Module::ifuncs(), and orderValue().
Referenced by predictUseListOrder().
orderValue()
static void orderValue (const Value * V, OrderMap & OM) static
Definition at line 119 of file AsmWriter.cpp.
References C, llvm::User::getNumOperands(), and llvm::User::operands().
Referenced by orderModule().
predictUseListOrder()
static UseListOrderStack predictUseListOrder (const Module * M) static
Definition at line 265 of file AsmWriter.cpp.
References F(), G, llvm::Module::globals(), I, llvm::make_range(), orderModule(), predictValueUseListOrder(), llvm::Module::rbegin(), and llvm::Module::rend().
predictValueUseListOrder()
static void predictValueUseListOrder (const Value * V, const Function * F, OrderMap & OM, UseListOrderStack & Stack) static
Definition at line 244 of file AsmWriter.cpp.
References assert(), C, llvm::User::getNumOperands(), llvm::User::operands(), predictValueUseListOrderImpl(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by predictUseListOrder().
predictValueUseListOrderImpl()
static void predictValueUseListOrderImpl (const Value * V, const Function * F, unsigned ID, const OrderMap & OM, UseListOrderStack & Stack) static
Definition at line 181 of file AsmWriter.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::begin(), E, llvm::SmallVectorTemplateCommon< T >::end(), first, I, List, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), llvm::sort(), and llvm::Value::uses().
Referenced by predictValueUseListOrder().
printAsOperandImpl()
static void printAsOperandImpl (const Value & V, raw_ostream & O, bool PrintType, ModuleSlotTracker & MST) static
Definition at line 4381 of file AsmWriter.cpp.
References llvm::ModuleSlotTracker::getMachine(), llvm::ModuleSlotTracker::getModule(), llvm::Value::getType(), llvm::RISCVFenceField::O, and WriteAsOperandInternal().
Referenced by llvm::Value::printAsOperand().
PrintCallingConv()
static void PrintCallingConv (unsigned cc, raw_ostream & Out) static
Definition at line 344 of file AsmWriter.cpp.
References llvm::CallingConv::AArch64_SVE_VectorCall, llvm::CallingConv::AArch64_VectorCall, llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::CallingConv::AnyReg, llvm::CallingConv::ARM_AAPCS, llvm::CallingConv::ARM_AAPCS_VFP, llvm::CallingConv::ARM_APCS, llvm::CallingConv::AVR_INTR, llvm::CallingConv::AVR_SIGNAL, llvm::CallingConv::CFGuard_Check, llvm::CallingConv::Cold, llvm::CallingConv::CXX_FAST_TLS, llvm::CallingConv::Fast, llvm::CallingConv::GHC, llvm::CallingConv::HHVM, llvm::CallingConv::HHVM_C, llvm::CallingConv::Intel_OCL_BI, llvm::CallingConv::MSP430_INTR, llvm::CallingConv::PreserveAll, llvm::CallingConv::PreserveMost, llvm::CallingConv::PTX_Device, llvm::CallingConv::PTX_Kernel, llvm::CallingConv::SPIR_FUNC, llvm::CallingConv::SPIR_KERNEL, llvm::CallingConv::Swift, llvm::CallingConv::Tail, llvm::CallingConv::WebKit_JS, llvm::CallingConv::Win64, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_INTR, llvm::CallingConv::X86_RegCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::CallingConv::X86_VectorCall.
Referenced by maybePrintCallAddrSpace(), and maybePrintComdat().
PrintDLLStorageClass()
static void PrintDLLStorageClass (GlobalValue::DLLStorageClassTypes SCT, formatted_raw_ostream & Out) static
Definition at line 3213 of file AsmWriter.cpp.
References llvm::GlobalValue::DefaultStorageClass, llvm::GlobalValue::DLLExportStorageClass, and llvm::GlobalValue::DLLImportStorageClass.
Referenced by maybePrintComdat().
PrintDSOLocation()
static void PrintDSOLocation (const GlobalValue & GV, formatted_raw_ostream & Out) static
Definition at line 3203 of file AsmWriter.cpp.
References llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::RegState::Implicit, and llvm::GlobalValue::isDSOLocal().
Referenced by maybePrintComdat().
PrintLLVMName() [1/2]
static void PrintLLVMName (raw_ostream & OS, StringRef Name, PrefixType Prefix) static
Turn the specified name into an 'LLVM name', which is either prefixed with % (if the string only contains simple characters) or is surrounded with ""'s (if it has special chars in it).
Print it out.
Definition at line 438 of file AsmWriter.cpp.
References ComdatPrefix, GlobalPrefix, LabelPrefix, LocalPrefix, NoPrefix, and llvm::printLLVMNameWithoutPrefix().
Referenced by maybePrintCallAddrSpace(), maybePrintComdat(), llvm::Comdat::print(), and PrintLLVMName().
PrintLLVMName() [2/2]
static void PrintLLVMName (raw_ostream & OS, const Value * V) static
Turn the specified name into an 'LLVM name', which is either prefixed with % (if the string only contains simple characters) or is surrounded with ""'s (if it has special chars in it).
Print it out.
Definition at line 460 of file AsmWriter.cpp.
References llvm::Type::ArrayTyID, assert(), llvm::Type::DoubleTyID, E, llvm::StringRef::empty(), llvm::empty(), llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::Type::FunctionTyID, llvm::PointerType::getAddressSpace(), getBitWidth(), llvm::SequentialType::getElementType(), llvm::PointerType::getElementType(), llvm::Value::getName(), llvm::StructType::getName(), llvm::SequentialType::getNumElements(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getReturnType(), llvm::Type::getTypeID(), GlobalPrefix, llvm::Type::HalfTyID, I, llvm::Type::IntegerTyID, llvm::StructType::isLiteral(), llvm::VectorType::isScalable(), llvm::FunctionType::isVarArg(), llvm::Type::LabelTyID, LocalPrefix, llvm::Type::MetadataTyID, P, llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::Type::PointerTyID, llvm::Type::PPC_FP128TyID, print(), PrintLLVMName(), llvm::Type::StructTyID, llvm::Type::TokenTyID, llvm::Type::VectorTyID, llvm::Type::VoidTyID, llvm::Type::X86_FP80TyID, and llvm::Type::X86_MMXTyID.
printMetadataIdentifier()
static void printMetadataIdentifier (StringRef Name, formatted_raw_ostream & Out) static
Definition at line 3148 of file AsmWriter.cpp.
References C, llvm::numbers::e, llvm::StringRef::empty(), llvm::NamedMDNode::getName(), llvm::NamedMDNode::getNumOperands(), llvm::NamedMDNode::getOperand(), llvm::hexdigit(), llvm::StringRef::size(), and writeDIExpression().
Referenced by maybePrintCallAddrSpace().
printMetadataImpl()
static void printMetadataImpl (raw_ostream & ROS, const Metadata & MD, ModuleSlotTracker & MST, const Module * M, bool OnlyAsOperand) static
Definition at line 4417 of file AsmWriter.cpp.
References llvm::dyn_cast(), llvm::ModuleSlotTracker::getMachine(), WriteAsOperandInternal(), and WriteMDNodeBodyInternal().
Referenced by llvm::Metadata::print(), and llvm::Metadata::printAsOperand().
PrintThreadLocalModel()
static void PrintThreadLocalModel (GlobalVariable::ThreadLocalMode TLM, formatted_raw_ostream & Out) static
Definition at line 3222 of file AsmWriter.cpp.
References llvm::GlobalValue::GeneralDynamicTLSModel, llvm::GlobalValue::InitialExecTLSModel, llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, and llvm::GlobalValue::NotThreadLocal.
Referenced by maybePrintComdat().
PrintVisibility()
static void PrintVisibility (GlobalValue::VisibilityTypes Vis, formatted_raw_ostream & Out) static
Definition at line 3194 of file AsmWriter.cpp.
References llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::HiddenVisibility, and llvm::GlobalValue::ProtectedVisibility.
Referenced by maybePrintComdat().
printWithoutType()
static bool printWithoutType (const Value & V, raw_ostream & O, SlotTracker * Machine, const Module * M) static
Print without a type, skipping the TypePrinting object.
Returns
true iff printing was successful.
Definition at line 4371 of file AsmWriter.cpp.
References llvm::Value::hasName(), and WriteAsOperandInternal().
Referenced by llvm::Value::printAsOperand().
WriteAsOperandInternal() [1/2]
static void WriteAsOperandInternal (raw_ostream & Out, const Value * V, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2228 of file AsmWriter.cpp.
References Context, createSlotTracker(), Machine, and llvm::cl::Prefix.
Referenced by maybePrintCallAddrSpace(), maybePrintComdat(), printAsOperandImpl(), printMetadataImpl(), printWithoutType(), WriteAsOperandInternal(), and WriteConstantInternal().
WriteAsOperandInternal() [2/2]
static void WriteAsOperandInternal (raw_ostream & Out, const Metadata * MD, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context, bool FromValue = false) static
Definition at line 2306 of file AsmWriter.cpp.
References assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, Context, llvm::SlotTracker::getMetadataSlot(), llvm::Value::getType(), Machine, llvm::printEscapedString(), WriteAsOperandInternal(), writeDIExpression(), and writeDILocation().
WriteConstantInternal()
static void WriteConstantInternal (raw_ostream & Out, const Constant * CV, TypePrinting & TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1292 of file AsmWriter.cpp.
References llvm::lltok::APFloat, assert(), llvm::APFloat::bitcastToAPInt(), Context, llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::APFloat::convertToFloat(), llvm::numbers::e, llvm::format_hex(), llvm::format_hex_no_prefix(), llvm::Constant::getAggregateElement(), llvm::APInt::getHiBits(), llvm::APInt::getLoBits(), llvm::MDNode::getNumOperands(), llvm::APFloat::getSemantics(), llvm::Value::getType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::APInt::getZExtValue(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm::APFloat::isInfinity(), llvm::APFloat::isNaN(), llvm_unreachable, Machine, N, llvm::APFloatBase::PPCDoubleDouble(), llvm::printEscapedString(), llvm::APFloatBase::rmNearestTiesToEven, llvm::tgtok::StrVal, llvm::APFloat::toString(), WriteAsOperandInternal(), and llvm::APFloatBase::x87DoubleExtended().
Referenced by llvm::Value::print().
writeDIBasicType()
static void writeDIBasicType (raw_ostream & Out, const DIBasicType * N, TypePrinting * , SlotTracker * , const Module *) static
Definition at line 1831 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDICommonBlock()
static void writeDICommonBlock (raw_ostream & Out, const DICommonBlock * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2015 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDICompileUnit()
static void writeDICompileUnit (raw_ostream & Out, const DICompileUnit * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1922 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDICompositeType()
static void writeDICompositeType (raw_ostream & Out, const DICompositeType * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1869 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIDerivedType()
static void writeDIDerivedType (raw_ostream & Out, const DIDerivedType * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1846 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIEnumerator()
static void writeDIEnumerator (raw_ostream & Out, const DIEnumerator * N, TypePrinting * , SlotTracker * , const Module *) static
Definition at line 1816 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIExpression()
static void writeDIExpression (raw_ostream & Out, const DIExpression * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2139 of file AsmWriter.cpp.
Referenced by printMetadataIdentifier(), rotateSign(), and WriteAsOperandInternal().
writeDIFile()
static void writeDIFile (raw_ostream & Out, const DIFile * N, TypePrinting * , SlotTracker * , const Module *) static
Definition at line 1906 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIGlobalVariable()
static void writeDIGlobalVariable (raw_ostream & Out, const DIGlobalVariable * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2092 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIGlobalVariableExpression()
static void writeDIGlobalVariableExpression (raw_ostream & Out, const DIGlobalVariableExpression * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2165 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIImportedEntity()
static void writeDIImportedEntity (raw_ostream & Out, const DIImportedEntity * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2192 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDILabel()
static void writeDILabel (raw_ostream & Out, const DILabel * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2127 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDILexicalBlock()
static void writeDILexicalBlock (raw_ostream & Out, const DILexicalBlock * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1978 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDILexicalBlockFile()
static void writeDILexicalBlockFile (raw_ostream & Out, const DILexicalBlockFile * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1990 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDILocalVariable()
static void writeDILocalVariable (raw_ostream & Out, const DILocalVariable * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2111 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDILocation()
static void writeDILocation (raw_ostream & Out, const DILocation * DL, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1787 of file AsmWriter.cpp.
Referenced by getOptimizationFlags(), and WriteAsOperandInternal().
writeDIMacro()
static void writeDIMacro (raw_ostream & Out, const DIMacro * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2028 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIMacroFile()
static void writeDIMacroFile (raw_ostream & Out, const DIMacroFile * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2040 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIModule()
static void writeDIModule (raw_ostream & Out, const DIModule * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2051 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDINamespace()
static void writeDINamespace (raw_ostream & Out, const DINamespace * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2004 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDIObjCProperty()
static void writeDIObjCProperty (raw_ostream & Out, const DIObjCProperty * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2177 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDISubprogram()
static void writeDISubprogram (raw_ostream & Out, const DISubprogram * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1951 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDISubrange()
static void writeDISubrange (raw_ostream & Out, const DISubrange * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1802 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDISubroutineType()
static void writeDISubroutineType (raw_ostream & Out, const DISubroutineType * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1894 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDITemplateTypeParameter()
static void writeDITemplateTypeParameter (raw_ostream & Out, const DITemplateTypeParameter * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2065 of file AsmWriter.cpp.
Referenced by rotateSign().
writeDITemplateValueParameter()
static void writeDITemplateValueParameter (raw_ostream & Out, const DITemplateValueParameter * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2077 of file AsmWriter.cpp.
Referenced by rotateSign().
writeGenericDINode()
static void writeGenericDINode (raw_ostream & Out, const GenericDINode * N, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1768 of file AsmWriter.cpp.
Referenced by getOptimizationFlags().
WriteMDNodeBodyInternal()
static void WriteMDNodeBodyInternal (raw_ostream & Out, const MDNode * Node, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 2206 of file AsmWriter.cpp.
Referenced by printMetadataImpl().
writeMDTuple()
static void writeMDTuple (raw_ostream & Out, const MDTuple * Node, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1555 of file AsmWriter.cpp.
Referenced by getOptimizationFlags().
writeMetadataAsOperand()
static void writeMetadataAsOperand (raw_ostream & Out, const Metadata * MD, TypePrinting * TypePrinter, SlotTracker * Machine, const Module * Context) static
Definition at line 1664 of file AsmWriter.cpp.
WriteOptimizationInfo()
static void WriteOptimizationInfo (raw_ostream & Out, const User * U) static
Definition at line 1253 of file AsmWriter.cpp.
References GEP.
Referenced by maybePrintCallAddrSpace().