LLVM: lib/IR/AutoUpgrade.cpp File Reference
AutoUpgrade.cpp File Reference
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Regex.h"
#include <cstring>
Functions
static void rename (GlobalValue *GV)
static bool UpgradePTESTIntrinsic (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool UpgradeX86IntrinsicsWith8BitMask (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool ShouldUpgradeX86Intrinsic (Function *F, StringRef Name)
static bool UpgradeX86IntrinsicFunction (Function *F, StringRef Name, Function *&NewFn)
static bool UpgradeIntrinsicFunction1 (Function *F, Function *&NewFn)
static Value * UpgradeX86PSLLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * UpgradeX86PSRLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * getX86MaskVec (IRBuilder<> &Builder, Value *Mask, unsigned NumElts)
static Value * EmitX86Select (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * EmitX86ScalarSelect (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * UpgradeX86ALIGNIntrinsics (IRBuilder<> &Builder, Value *Op0, Value *Op1, Value *Shift, Value *Passthru, Value *Mask, bool IsVALIGN)
static Value * UpgradeX86VPERMT2Intrinsics (IRBuilder<> &Builder, CallInst &CI, bool ZeroMask, bool IndexForm)
static Value * UpgradeX86AddSubSatIntrinsics (IRBuilder<> &Builder, CallInst &CI, bool IsSigned, bool IsAddition)
static Value * upgradeX86Rotate (IRBuilder<> &Builder, CallInst &CI, bool IsRotateRight)
static Value * upgradeX86vpcom (IRBuilder<> &Builder, CallInst &CI, unsigned Imm, bool IsSigned)
static Value * upgradeX86ConcatShift (IRBuilder<> &Builder, CallInst &CI, bool IsShiftRight, bool ZeroMask)
static Value * UpgradeMaskedStore (IRBuilder<> &Builder, Value *Ptr, Value *Data, Value *Mask, bool Aligned)
static Value * UpgradeMaskedLoad (IRBuilder<> &Builder, Value *Ptr, Value *Passthru, Value *Mask, bool Aligned)
static Value * upgradeAbs (IRBuilder<> &Builder, CallInst &CI)
static Value * upgradeIntMinMax (IRBuilder<> &Builder, CallInst &CI, ICmpInst::Predicate Pred)
static Value * upgradePMULDQ (IRBuilder<> &Builder, CallInst &CI, bool IsSigned)
static Value * ApplyX86MaskOn1BitsVec (IRBuilder<> &Builder, Value *Vec, Value *Mask)
static Value * upgradeMaskedCompare (IRBuilder<> &Builder, CallInst &CI, unsigned CC, bool Signed)
static Value * UpgradeX86MaskedShift (IRBuilder<> &Builder, CallInst &CI, Intrinsic::ID IID)
static Value * upgradeMaskedMove (IRBuilder<> &Builder, CallInst &CI)
static Value * UpgradeMaskToInt (IRBuilder<> &Builder, CallInst &CI)
static bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> &Builder, CallInst &CI, Value *&Rep)
static bool UpgradeRetainReleaseMarker (Module &M)
This checks for objc retain release marker which should be upgraded.
static bool isOldLoopArgument (Metadata *MD)
static MDString * upgradeLoopTag (LLVMContext &C, StringRef OldTag)
static Metadata * upgradeLoopArgument (Metadata *MD)
Function Documentation
ApplyX86MaskOn1BitsVec()
static Value* ApplyX86MaskOn1BitsVec (IRBuilder<> & Builder, Value * Vec, Value * Mask) static
Definition at line 1331 of file AutoUpgrade.cpp.
References C, llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::dyn_cast(), llvm::IRBuilderBase::getIntNTy(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), getX86MaskVec(), llvm::BitmaskEnumDetail::Mask(), and llvm::max().
Referenced by upgradeMaskedCompare().
EmitX86ScalarSelect()
static Value* EmitX86ScalarSelect (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 989 of file AutoUpgrade.cpp.
References C, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::VectorType::get(), llvm::IRBuilderBase::getInt1Ty(), llvm::Type::getIntegerBitWidth(), and llvm::Value::getType().
EmitX86Select()
static Value* EmitX86Select (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 978 of file AutoUpgrade.cpp.
References C, llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and getX86MaskVec().
Referenced by upgradeAbs(), upgradeAVX512MaskToSelect(), upgradeIntMinMax(), upgradePMULDQ(), UpgradeX86AddSubSatIntrinsics(), UpgradeX86ALIGNIntrinsics(), upgradeX86ConcatShift(), UpgradeX86MaskedShift(), upgradeX86Rotate(), and UpgradeX86VPERMT2Intrinsics().
getX86MaskVec()
static Value* getX86MaskVec (IRBuilder<> & Builder, Value * Mask, unsigned NumElts) static
Definition at line 958 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::VectorType::get(), getBitWidth(), llvm::IRBuilderBase::getInt1Ty(), llvm::Value::getType(), llvm::makeArrayRef(), and llvm::BitmaskEnumDetail::Mask().
Referenced by ApplyX86MaskOn1BitsVec(), EmitX86Select(), UpgradeMaskedLoad(), UpgradeMaskedStore(), and UpgradeMaskToInt().
isOldLoopArgument()
static bool isOldLoopArgument (Metadata * MD) static
Definition at line 4098 of file AutoUpgrade.cpp.
Referenced by llvm::upgradeInstructionLoopAttachment().
rename()
static void rename (GlobalValue * GV) static
Definition at line 36 of file AutoUpgrade.cpp.
References llvm::Value::getName(), and llvm::Value::setName().
Referenced by llvm::sys::fs::TempFile::keep(), UpgradeIntrinsicFunction1(), UpgradePTESTIntrinsic(), UpgradeX86IntrinsicFunction(), and UpgradeX86IntrinsicsWith8BitMask().
ShouldUpgradeX86Intrinsic()
static bool ShouldUpgradeX86Intrinsic (Function * F, StringRef Name) static
Definition at line 70 of file AutoUpgrade.cpp.
References llvm::StringRef::startswith().
Referenced by UpgradeX86IntrinsicFunction().
upgradeAbs()
static Value* upgradeAbs (IRBuilder<> & Builder, CallInst & CI) static
Definition at line 1274 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateSelect(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::CallBase::getNumArgOperands(), llvm::Value::getType(), and llvm::CmpInst::ICMP_SGT.
upgradeAVX512MaskToSelect()
static bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> & Builder, CallInst & CI, Value *& Rep) static
Definition at line 1415 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_operands(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isFPOrFPVectorTy(), llvm_unreachable, llvm::StringRef::startswith(), and llvm::StringRef::substr().
upgradeIntMinMax()
static Value* upgradeIntMinMax (IRBuilder<> & Builder, CallInst & CI, ICmpInst::Predicate Pred) static
Definition at line 1288 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateSelect(), EmitX86Select(), llvm::CallBase::getArgOperand(), and llvm::CallBase::getNumArgOperands().
UpgradeIntrinsicFunction1()
static bool UpgradeIntrinsicFunction1 (Function * F, Function *& NewFn) static
Definition at line 493 of file AutoUpgrade.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_size(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), llvm::Function::Create(), llvm::StringSwitch< T, R >::Default(), llvm::dyn_cast(), llvm::StringRef::find(), llvm::FunctionType::get(), llvm::GlobalValue::getAddressSpace(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::Function::getFunctionType(), llvm::Type::getInt1Ty(), llvm::GlobalValue::getLinkage(), llvm::Intrinsic::getName(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::FunctionType::getReturnType(), llvm::Function::getReturnType(), llvm::Value::getType(), Groups, llvm::Type::isFloatingPointTy(), llvm::Regex::match(), Name, llvm::None, llvm::Intrinsic::not_intrinsic, llvm::StringRef::npos, llvm::FunctionType::params(), prefetch, llvm::RISCVFenceField::R, llvm::Intrinsic::remangleIntrinsicFunction(), rename(), llvm::StringRef::size(), llvm::StringSwitch< T, R >::StartsWith(), llvm::StringRef::startswith(), llvm::StringRef::substr(), and UpgradeX86IntrinsicFunction().
Referenced by llvm::UpgradeIntrinsicFunction().
upgradeLoopArgument()
static Metadata* upgradeLoopArgument (Metadata * MD) static
Definition at line 4122 of file AutoUpgrade.cpp.
References E, llvm::MDTuple::get(), I, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and upgradeLoopTag().
Referenced by llvm::upgradeInstructionLoopAttachment().
upgradeLoopTag()
static MDString* upgradeLoopTag (LLVMContext & C, StringRef OldTag) static
Definition at line 4110 of file AutoUpgrade.cpp.
References assert(), llvm::StringRef::drop_front(), llvm::MDString::get(), llvm::StringRef::size(), and llvm::StringRef::startswith().
Referenced by upgradeLoopArgument().
upgradeMaskedCompare()
static Value* upgradeMaskedCompare (IRBuilder<> & Builder, CallInst & CI, unsigned CC, bool Signed) static
Definition at line 1353 of file AutoUpgrade.cpp.
References ApplyX86MaskOn1BitsVec(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::VectorType::get(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::IRBuilderBase::getInt1Ty(), llvm::Constant::getNullValue(), llvm::CallBase::getNumArgOperands(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, and llvm::BitmaskEnumDetail::Mask().
UpgradeMaskedLoad()
static Value* UpgradeMaskedLoad (IRBuilder<> & Builder, Value * Ptr, Value * Passthru, Value * Mask, bool Aligned) static
Definition at line 1254 of file AutoUpgrade.cpp.
References C, llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedLoad(), getBitWidth(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVectorNumElements(), and getX86MaskVec().
upgradeMaskedMove()
static Value* upgradeMaskedMove (IRBuilder<> & Builder, CallInst & CI) static
Definition at line 1391 of file AutoUpgrade.cpp.
References A, B, llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateIsNotNull(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::CallBase::getArgOperand(), llvm::BitmaskEnumDetail::Mask(), and llvm::MCID::Select.
UpgradeMaskedStore()
static Value* UpgradeMaskedStore (IRBuilder<> & Builder, Value * Ptr, Value * Data, Value * Mask, bool Aligned) static
Definition at line 1234 of file AutoUpgrade.cpp.
References C, llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedStore(), getBitWidth(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVectorNumElements(), and getX86MaskVec().
UpgradeMaskToInt()
static Value* UpgradeMaskToInt (IRBuilder<> & Builder, CallInst & CI) static
Definition at line 1406 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), getX86MaskVec(), and llvm::BitmaskEnumDetail::Mask().
upgradePMULDQ()
static Value* upgradePMULDQ (IRBuilder<> & Builder, CallInst & CI, bool IsSigned) static
Definition at line 1301 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateShl(), EmitX86Select(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getNumArgOperands(), llvm::Value::getType(), and llvm::BitmaskEnumDetail::Mask().
UpgradePTESTIntrinsic()
static bool UpgradePTESTIntrinsic (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 40 of file AutoUpgrade.cpp.
References llvm::VectorType::get(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getFloatTy(), llvm::Function::getFunctionType(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), and rename().
Referenced by UpgradeX86IntrinsicFunction().
UpgradeRetainReleaseMarker()
static bool UpgradeRetainReleaseMarker (Module & M) static
This checks for objc retain release marker which should be upgraded.
It returns true if module is modified.
Definition at line 3857 of file AutoUpgrade.cpp.
References llvm::Module::addModuleFlag(), llvm::Module::eraseNamedMetadata(), llvm::Module::Error, llvm::MDString::get(), llvm::Module::getContext(), llvm::Module::getNamedMetadata(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::MDString::getString(), llvm::SmallVectorBase::size(), and llvm::StringRef::split().
Referenced by llvm::UpgradeARCRuntime().
UpgradeX86AddSubSatIntrinsics()
static Value* UpgradeX86AddSubSatIntrinsics (IRBuilder<> & Builder, CallInst & CI, bool IsSigned, bool IsAddition) static
Definition at line 1114 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::BitmaskEnumDetail::Mask().
UpgradeX86ALIGNIntrinsics()
static Value* UpgradeX86ALIGNIntrinsics (IRBuilder<> & Builder, Value * Op0, Value * Op1, Value * Shift, Value * Passthru, Value * Mask, bool IsVALIGN) static
Definition at line 1007 of file AutoUpgrade.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), EmitX86Select(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::isPowerOf2_32(), and llvm::makeArrayRef().
upgradeX86ConcatShift()
static Value* upgradeX86ConcatShift (IRBuilder<> & Builder, CallInst & CI, bool IsShiftRight, bool ZeroMask) static
Definition at line 1200 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), EmitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::BitmaskEnumDetail::Mask(), and std::swap().
UpgradeX86IntrinsicFunction()
static bool UpgradeX86IntrinsicFunction (Function * F, StringRef Name, Function *& NewFn) static
Definition at line 397 of file AutoUpgrade.cpp.
References llvm::Function::arg_size(), llvm::Intrinsic::getDeclaration(), llvm::Function::getFunctionType(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), rename(), ShouldUpgradeX86Intrinsic(), llvm::StringRef::startswith(), llvm::StringRef::substr(), UpgradePTESTIntrinsic(), and UpgradeX86IntrinsicsWith8BitMask().
Referenced by UpgradeIntrinsicFunction1().
UpgradeX86IntrinsicsWith8BitMask()
static bool UpgradeX86IntrinsicsWith8BitMask (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 56 of file AutoUpgrade.cpp.
References llvm::Intrinsic::getDeclaration(), llvm::Function::getFunctionType(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), llvm::Type::isIntegerTy(), and rename().
Referenced by UpgradeX86IntrinsicFunction().
UpgradeX86MaskedShift()
static Value* UpgradeX86MaskedShift (IRBuilder<> & Builder, CallInst & CI, Intrinsic::ID IID) static
Definition at line 1383 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), and llvm::Instruction::getModule().
UpgradeX86PSLLDQIntrinsics()
static Value* UpgradeX86PSLLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 892 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::VectorType::get(), llvm::IRBuilderBase::getInt8Ty(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and llvm::makeArrayRef().
UpgradeX86PSRLDQIntrinsics()
static Value* UpgradeX86PSRLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 926 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::VectorType::get(), llvm::IRBuilderBase::getInt8Ty(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and llvm::makeArrayRef().
upgradeX86Rotate()
static Value* upgradeX86Rotate (IRBuilder<> & Builder, CallInst & CI, bool IsRotateRight) static
Definition at line 1134 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and llvm::BitmaskEnumDetail::Mask().
upgradeX86vpcom()
static Value* upgradeX86vpcom (IRBuilder<> & Builder, CallInst & CI, unsigned Imm, bool IsSigned) static
Definition at line 1161 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::MipsISD::Ext, llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
UpgradeX86VPERMT2Intrinsics()
static Value* UpgradeX86VPERMT2Intrinsics (IRBuilder<> & Builder, CallInst & CI, bool ZeroMask, bool IndexForm) static
Definition at line 1053 of file AutoUpgrade.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isFPOrFPVectorTy(), llvm_unreachable, and std::swap().