LLVM: lib/Target/AVR/Disassembler/AVRDisassembler.cpp File Reference
AVRDisassembler.cpp File Reference
#include "AVR.h"
#include "AVRRegisterInfo.h"
#include "AVRSubtarget.h"
#include "MCTargetDesc/AVRMCTargetDesc.h"
#include "TargetInfo/AVRTargetInfo.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Support/TargetRegistry.h"
#include "AVRGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "avr-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
typedef DecodeStatus(* DecodeFunc) (MCInst &MI, unsigned insn, uint64_t Address, const void *Decoder)
Functions
static MCDisassembler * createAVRDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAVRDisassembler ()
static DecodeStatus DecodeGPR8RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLD8RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodePTRREGSRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
static const uint8_t * getDecoderTable (uint64_t Size)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "avr-disassembler"
Definition at line 28 of file AVRDisassembler.cpp.
Typedef Documentation
DecodeFunc
typedef DecodeStatus(* DecodeFunc) (MCInst &MI, unsigned insn, uint64_t Address, const void *Decoder)
Definition at line 152 of file AVRDisassembler.cpp.
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 30 of file AVRDisassembler.cpp.
Function Documentation
createAVRDisassembler()
static MCDisassembler* createAVRDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 47 of file AVRDisassembler.cpp.
Referenced by LLVMInitializeAVRDisassembler().
DecodeGPR8RegisterClass()
static DecodeStatus DecodeGPR8RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 60 of file AVRDisassembler.cpp.
References llvm::MCDisassembler::Success.
DecodeLD8RegisterClass()
static DecodeStatus DecodeLD8RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 65 of file AVRDisassembler.cpp.
References llvm::MCDisassembler::Success.
DecodePTRREGSRegisterClass()
static DecodeStatus DecodePTRREGSRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 70 of file AVRDisassembler.cpp.
References llvm::MCDisassembler::Success.
getDecoderTable()
static const uint8_t* getDecoderTable (uint64_t Size) static
Definition at line 104 of file AVRDisassembler.cpp.
References llvm::Address, llvm::MCDisassembler::Fail, llvm_unreachable, readInstruction16(), readInstruction32(), and Size.
LLVMInitializeAVRDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAVRDisassembler ()
Definition at line 54 of file AVRDisassembler.cpp.
References createAVRDisassembler(), llvm::getTheAVRTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction16()
static DecodeStatus readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 77 of file AVRDisassembler.cpp.
References llvm::MCDisassembler::Fail, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.
Referenced by getDecoderTable().
readInstruction32()
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 90 of file AVRDisassembler.cpp.
References llvm::MCDisassembler::Fail, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.
Referenced by getDecoderTable().