LLVM: lib/Remarks/BitstreamRemarkParser.cpp File Reference
BitstreamRemarkParser.cpp File Reference
#include "llvm/Remarks/BitstreamRemarkParser.h"
#include "BitstreamRemarkParser.h"
#include "llvm/Remarks/BitstreamRemarkContainer.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
Functions
static Error unknownRecord (const char *BlockName, unsigned RecordID)
static Error malformedRecord (const char *BlockName, const char *RecordName)
static Error parseRecord (BitstreamMetaParserHelper &Parser, unsigned Code)
Parse a record and fill in the fields in the parser.
static Error parseRecord (BitstreamRemarkParserHelper &Parser, unsigned Code)
Parse a record and fill in the fields in the parser.
template<typename T >
static Error parseBlock (T &ParserHelper, unsigned BlockID, const char *BlockName)
static Expected< bool > isBlock (BitstreamCursor &Stream, unsigned BlockID)
static Error validateMagicNumber (StringRef MagicNumber)
static Error advanceToMetaBlock (BitstreamParserHelper &Helper)
static Error processStrTab (BitstreamRemarkParser &P, Optional< StringRef > StrTabBuf)
static Error processRemarkVersion (BitstreamRemarkParser &P, Optional< uint64_t > RemarkVersion)
Function Documentation
advanceToMetaBlock()
static Error advanceToMetaBlock (BitstreamParserHelper & Helper) static
Definition at line 289 of file BitstreamRemarkParser.cpp.
References llvm::createStringError(), E, llvm::remarks::BitstreamParserHelper::isMetaBlock(), llvm::make_error_code(), llvm::remarks::BitstreamParserHelper::parseBlockInfoBlock(), llvm::remarks::BitstreamParserHelper::parseMagic(), llvm::Error::success(), llvm::Expected< T >::takeError(), and validateMagicNumber().
Referenced by llvm::remarks::BitstreamRemarkParser::parseMeta(), and processRemarkVersion().
isBlock()
static Expected<bool> isBlock (BitstreamCursor & Stream, unsigned BlockID) static
Definition at line 249 of file BitstreamRemarkParser.cpp.
References llvm::BitstreamCursor::advance(), llvm::createStringError(), E, llvm::BitstreamEntry::Error, llvm::SimpleBitstreamCursor::GetCurrentBitNo(), llvm::SimpleBitstreamCursor::JumpToBit(), llvm::make_error_code(), llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::remarks::BitstreamParserHelper::isMetaBlock(), and llvm::remarks::BitstreamParserHelper::isRemarkBlock().
malformedRecord()
static Error malformedRecord (const char * BlockName, const char * RecordName) static
Definition at line 30 of file BitstreamRemarkParser.cpp.
References llvm::createStringError(), and llvm::make_error_code().
Referenced by parseRecord().
parseBlock()
template<typename T > static Error parseBlock (T & ParserHelper, unsigned BlockID, const char * BlockName) static
Definition at line 158 of file BitstreamRemarkParser.cpp.
References llvm::BitstreamCursor::advance(), llvm::SimpleBitstreamCursor::AtEndOfStream(), llvm::createStringError(), E, llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, llvm::make_error_code(), parseRecord(), llvm::BitstreamEntry::Record, llvm::remarks::BitstreamRemarkParserHelper::Stream, llvm::BitstreamEntry::SubBlock, llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by llvm::remarks::BitstreamMetaParserHelper::parse(), and llvm::remarks::BitstreamRemarkParserHelper::parse().
parseRecord() [1/2]
static Error parseRecord (BitstreamMetaParserHelper & Parser, unsigned Code) static
Parse a record and fill in the fields in the parser.
Definition at line 42 of file BitstreamRemarkParser.cpp.
References llvm::remarks::BitstreamMetaParserHelper::ContainerType, llvm::remarks::BitstreamMetaParserHelper::ContainerVersion, llvm::remarks::BitstreamMetaParserHelper::ExternalFilePath, malformedRecord(), llvm::BitstreamCursor::readRecord(), llvm::remarks::RECORD_META_CONTAINER_INFO, llvm::remarks::RECORD_META_EXTERNAL_FILE, llvm::remarks::RECORD_META_REMARK_VERSION, llvm::remarks::RECORD_META_STRTAB, llvm::remarks::BitstreamMetaParserHelper::RemarkVersion, llvm::SmallVectorBase::size(), llvm::remarks::BitstreamMetaParserHelper::Stream, llvm::remarks::BitstreamMetaParserHelper::StrTabBuf, llvm::Error::success(), llvm::Expected< T >::takeError(), and unknownRecord().
Referenced by parseBlock().
parseRecord() [2/2]
static Error parseRecord (BitstreamRemarkParserHelper & Parser, unsigned Code) static
Parse a record and fill in the fields in the parser.
Definition at line 89 of file BitstreamRemarkParser.cpp.
References llvm::remarks::BitstreamRemarkParserHelper::Args, llvm::remarks::BitstreamRemarkParserHelper::FunctionNameIdx, llvm::remarks::BitstreamRemarkParserHelper::Hotness, malformedRecord(), llvm::remarks::BitstreamRemarkParserHelper::PassNameIdx, llvm::BitstreamCursor::readRecord(), llvm::remarks::RECORD_REMARK_ARG_WITH_DEBUGLOC, llvm::remarks::RECORD_REMARK_ARG_WITHOUT_DEBUGLOC, llvm::remarks::RECORD_REMARK_DEBUG_LOC, llvm::remarks::RECORD_REMARK_HEADER, llvm::remarks::RECORD_REMARK_HOTNESS, llvm::remarks::BitstreamRemarkParserHelper::RemarkNameIdx, llvm::SmallVectorBase::size(), llvm::remarks::BitstreamRemarkParserHelper::SourceColumn, llvm::remarks::BitstreamRemarkParserHelper::SourceFileNameIdx, llvm::remarks::BitstreamRemarkParserHelper::SourceLine, llvm::remarks::BitstreamRemarkParserHelper::Stream, llvm::Error::success(), llvm::Expected< T >::takeError(), llvm::remarks::BitstreamRemarkParserHelper::TmpArgs, llvm::remarks::BitstreamRemarkParserHelper::Type, and unknownRecord().
processRemarkVersion()
static Error processRemarkVersion (BitstreamRemarkParser & P, Optional< uint64_t > RemarkVersion) static
Definition at line 404 of file BitstreamRemarkParser.cpp.
References advanceToMetaBlock(), llvm::sys::path::append(), llvm::remarks::BitstreamParserHelper::BitstreamParserHelper(), llvm::createFileError(), llvm::createStringError(), E, llvm::remarks::BitstreamMetaParserHelper::ExternalFilePath, llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), llvm::make_error_code(), llvm::remarks::BitstreamMetaParserHelper::parse(), processStrTab(), llvm::remarks::BitstreamRemarkParser::RemarkVersion, llvm::remarks::BitstreamMetaParserHelper::RemarkVersion, llvm::remarks::SeparateRemarksFile, llvm::remarks::BitstreamMetaParserHelper::StrTabBuf, and llvm::Error::success().
processStrTab()
static Error processStrTab (BitstreamRemarkParser & P, Optional< StringRef > StrTabBuf) static
Definition at line 393 of file BitstreamRemarkParser.cpp.
References llvm::createStringError(), llvm::make_error_code(), llvm::remarks::BitstreamRemarkParser::StrTab, and llvm::Error::success().
Referenced by processRemarkVersion().
unknownRecord()
static Error unknownRecord (const char * BlockName, unsigned RecordID) static
Definition at line 23 of file BitstreamRemarkParser.cpp.
References llvm::createStringError(), and llvm::make_error_code().
Referenced by parseRecord().
validateMagicNumber()
static Error validateMagicNumber (StringRef MagicNumber) static
Definition at line 281 of file BitstreamRemarkParser.cpp.
References llvm::remarks::ContainerMagic(), llvm::createStringError(), llvm::StringRef::data(), llvm::make_error_code(), and llvm::Error::success().
Referenced by advanceToMetaBlock(), and llvm::remarks::createBitstreamParserFromMeta().