LLVM: lib/Remarks/BitstreamRemarkSerializer.cpp File Reference
BitstreamRemarkSerializer.cpp File Reference
#include "llvm/Remarks/BitstreamRemarkSerializer.h"
Functions
static void push (SmallVectorImpl< uint64_t > &R, StringRef Str)
static void setRecordName (unsigned RecordID, BitstreamWriter &Bitstream, SmallVectorImpl< uint64_t > &R, StringRef Str)
static void initBlock (unsigned BlockID, BitstreamWriter &Bitstream, SmallVectorImpl< uint64_t > &R, StringRef Str)
Function Documentation
initBlock()
static void initBlock (unsigned BlockID, BitstreamWriter & Bitstream, SmallVectorImpl< uint64_t > & R, StringRef Str) static
Definition at line 36 of file BitstreamRemarkSerializer.cpp.
References llvm::bitc::BLOCKINFO_CODE_BLOCKNAME, llvm::bitc::BLOCKINFO_CODE_SETBID, llvm::SmallVectorImpl< T >::clear(), llvm::BitstreamWriter::EmitRecord(), push(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaBlockInfo(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
push()
static void push (SmallVectorImpl< uint64_t > & R, StringRef Str) static
Definition at line 23 of file BitstreamRemarkSerializer.cpp.
References C, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::LatencyPriorityQueue::empty(), llvm::ResourcePriorityQueue::empty(), llvm::IntervalMapImpl::Path::fillLeft(), initBlock(), isOpcodeHandled(), llvm::SchedulingPriorityQueue::isReady(), llvm::ValueEnumerator::print(), llvm::SchedulingPriorityQueue::push_all(), llvm::rdf::DataFlowGraph::pushAllDefs(), llvm::LatencyPriorityQueue::scheduledNode(), setRecordName(), llvm::PMStack::top(), llvm::BitTracker::trace(), and llvm::SCEVTraversal< SV >::visitAll().
setRecordName()
static void setRecordName (unsigned RecordID, BitstreamWriter & Bitstream, SmallVectorImpl< uint64_t > & R, StringRef Str) static
Definition at line 28 of file BitstreamRemarkSerializer.cpp.
References llvm::bitc::BLOCKINFO_CODE_SETRECORDNAME, llvm::SmallVectorImpl< T >::clear(), llvm::BitstreamWriter::EmitRecord(), push(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaBlockInfo(), llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaExternalFile(), llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaRemarkVersion(), llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaStrTab(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().