LLVM: lib/Target/BPF/BPFISelLowering.cpp File Reference
BPFISelLowering.cpp File Reference
#include "BPFISelLowering.h"
#include "BPF.h"
#include "BPFSubtarget.h"
#include "BPFTargetMachine.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "BPFGenCallingConv.inc"
Macros
#define DEBUG_TYPE "bpf-lower"
#define SET_NEWCC(X, Y)
Functions
static void fail (const SDLoc &DL, SelectionDAG &DAG, const Twine &Msg)
static void fail (const SDLoc &DL, SelectionDAG &DAG, const char *Msg, SDValue Val)
static void NegateCC (SDValue &LHS, SDValue &RHS, ISD::CondCode &CC)
Variables
static cl::opt< bool > BPFExpandMemcpyInOrder ("bpf-expand-memcpy-in-order", cl::Hidden, cl::init(false), cl::desc("Expand memcpy into load/store pairs in order"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bpf-lower"
Definition at line 33 of file BPFISelLowering.cpp.
SET_NEWCC
#define SET_NEWCC (X, Y)
Value:
case ISD::X: \
    if (is32BitCmp && HasJmp32) \
      NewCC = isSelectRROp ? BPF::Y##_rr_32 : BPF::Y##_ri_32; \
    else \
      NewCC = isSelectRROp ? BPF::Y##_rr : BPF::Y##_ri; \
    break
Referenced by llvm::BPFTargetLowering::EmitInstrWithCustomInserter().
Function Documentation
fail() [1/2]
static void fail (const SDLoc & DL, SelectionDAG & DAG, const Twine & Msg) static
Definition at line 39 of file BPFISelLowering.cpp.
References llvm::LLVMContext::diagnose(), llvm::SelectionDAG::getContext(), llvm::SDLoc::getDebugLoc(), llvm::MachineFunction::getFunction(), and llvm::SelectionDAG::getMachineFunction().
Referenced by llvm::BPFTargetLowering::LowerOperation().
fail() [2/2]
static void fail (const SDLoc & DL, SelectionDAG & DAG, const char * Msg, SDValue Val) static
Definition at line 45 of file BPFISelLowering.cpp.
References llvm::LLVMContext::diagnose(), llvm::raw_ostream::flush(), llvm::SelectionDAG::getContext(), llvm::SDLoc::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), and llvm::SDNode::print().
NegateCC()
static void NegateCC (SDValue & LHS, SDValue & RHS, ISD::CondCode & CC) static
Definition at line 484 of file BPFISelLowering.cpp.
References llvm::BPFISD::BR_CC, llvm::SelectionDAG::getConstant(), llvm::BPFTargetLowering::getHasJmpExt(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::ISD::getSetCCSwappedOperands(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::BPFISD::SELECT_CC, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETULE, llvm::ISD::SETULT, and std::swap().
Variable Documentation
BPFExpandMemcpyInOrder
cl::opt<bool> BPFExpandMemcpyInOrder("bpf-expand-memcpy-in-order", cl::Hidden, cl::init(false), cl::desc("Expand memcpy into load/store pairs in order")) static
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().