LLVM: lib/Target/BPF/MCTargetDesc/BPFMCCodeEmitter.cpp File Reference
BPFMCCodeEmitter.cpp File Reference
#include "MCTargetDesc/BPFMCTargetDesc.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/EndianStream.h"
#include <cassert>
#include <cstdint>
#include "BPFGenMCCodeEmitter.inc"
Macros
#define DEBUG_TYPE "mccodeemitter"
#define ENABLE_INSTR_PREDICATE_VERIFIER
Functions
static uint8_t SwapBits (uint8_t Val)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mccodeemitter"
Definition at line 28 of file BPFMCCodeEmitter.cpp.
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 172 of file BPFMCCodeEmitter.cpp.
Function Documentation
SwapBits()
static uint8_t SwapBits (uint8_t Val) static
Definition at line 113 of file BPFMCCodeEmitter.cpp.
References assert(), llvm::support::big, llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::support::little, MRI, and llvm::support::endian::Writer::write().