LLVM: lib/Target/BPF/BPFRegisterInfo.cpp File Reference
BPFRegisterInfo.cpp File Reference
#include "BPFRegisterInfo.h"
#include "BPF.h"
#include "BPFSubtarget.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "BPFGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
Functions
static void WarnSize (int Offset, MachineFunction &MF, DebugLoc &DL)
Macro Definition Documentation
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 25 of file BPFRegisterInfo.cpp.
Function Documentation
WarnSize()
static void WarnSize (int Offset, MachineFunction & MF, DebugLoc & DL) static
Definition at line 44 of file BPFRegisterInfo.cpp.
References llvm::LLVMContext::diagnose(), F(), llvm::Function::getContext(), and llvm::MachineFunction::getFunction().
Referenced by llvm::BPFRegisterInfo::eliminateFrameIndex().