LLVM: lib/Transforms/Utils/BuildLibCalls.cpp File Reference
BuildLibCalls.cpp File Reference
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Analysis/MemoryBuiltins.h"
Macros
#define DEBUG_TYPE "build-libcalls"
Functions
STATISTIC (NumReadNone, "Number of functions inferred as readnone")
STATISTIC (NumReadOnly, "Number of functions inferred as readonly")
STATISTIC (NumArgMemOnly, "Number of functions inferred as argmemonly")
STATISTIC (NumNoUnwind, "Number of functions inferred as nounwind")
STATISTIC (NumNoCapture, "Number of arguments inferred as nocapture")
STATISTIC (NumReadOnlyArg, "Number of arguments inferred as readonly")
STATISTIC (NumNoAlias, "Number of function returns inferred as noalias")
STATISTIC (NumNonNull, "Number of function returns inferred as nonnull returns")
STATISTIC (NumReturnedArg, "Number of arguments inferred as returned")
static bool setDoesNotAccessMemory (Function &F)
static bool setOnlyReadsMemory (Function &F)
static bool setOnlyAccessesArgMemory (Function &F)
static bool setDoesNotThrow (Function &F)
static bool setRetDoesNotAlias (Function &F)
static bool setDoesNotCapture (Function &F, unsigned ArgNo)
static bool setDoesNotAlias (Function &F, unsigned ArgNo)
static bool setOnlyReadsMemory (Function &F, unsigned ArgNo)
static bool setRetNonNull (Function &F)
static bool setReturnedArg (Function &F, unsigned ArgNo)
static bool setNonLazyBind (Function &F)
static bool setDoesNotFreeMemory (Function &F)
static Value * emitLibCall (LibFunc TheLibFunc, Type *ReturnType, ArrayRef< Type *> ParamTypes, ArrayRef< Value *> Operands, IRBuilder<> &B, const TargetLibraryInfo *TLI, bool IsVaArgs=false)
static void appendTypeSuffix (Value *Op, StringRef &Name, SmallString< 20 > &NameBuffer)
Append a suffix to the function name according to the type of 'Op'.
static Value * emitUnaryFloatFnCallHelper (Value *Op, StringRef Name, IRBuilder<> &B, const AttributeList &Attrs)
static Value * emitBinaryFloatFnCallHelper (Value *Op1, Value *Op2, StringRef Name, IRBuilder<> &B, const AttributeList &Attrs)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "build-libcalls"
Definition at line 29 of file BuildLibCalls.cpp.
Function Documentation
appendTypeSuffix()
static void appendTypeSuffix (Value * Op, StringRef & Name, SmallString< 20 > & NameBuffer) static
Append a suffix to the function name according to the type of 'Op'.
Definition at line 1028 of file BuildLibCalls.cpp.
References llvm::Value::getType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and Name.
Referenced by llvm::emitBinaryFloatFnCall(), and llvm::emitUnaryFloatFnCall().
emitBinaryFloatFnCallHelper()
static Value* emitBinaryFloatFnCallHelper (Value * Op1, Value * Op2, StringRef Name, IRBuilder<> & B, const AttributeList & Attrs) static
Definition at line 1084 of file BuildLibCalls.cpp.
References assert(), Callee, llvm::IRBuilder< T, Inserter >::CreateCall(), F(), llvm::AttributeList::FunctionIndex, llvm::FunctionCallee::getCallee(), llvm::IRBuilderBase::getContext(), llvm::IRBuilderBase::GetInsertBlock(), llvm::BasicBlock::getModule(), llvm::Module::getOrInsertFunction(), llvm::Value::getType(), Name, llvm::AttributeList::removeAttribute(), llvm::CallBase::setAttributes(), llvm::CallBase::setCallingConv(), and llvm::Value::stripPointerCasts().
Referenced by llvm::emitBinaryFloatFnCall().
emitLibCall()
static Value* emitLibCall (LibFunc TheLibFunc, Type * ReturnType, ArrayRef< Type *> ParamTypes, ArrayRef< Value *> Operands, IRBuilder<> & B, const TargetLibraryInfo * TLI, bool IsVaArgs = false) static
Definition at line 827 of file BuildLibCalls.cpp.
References Callee, llvm::IRBuilder< T, Inserter >::CreateCall(), F(), llvm::FunctionType::get(), llvm::FunctionCallee::getCallee(), llvm::IRBuilderBase::GetInsertBlock(), llvm::BasicBlock::getModule(), llvm::TargetLibraryInfo::getName(), llvm::Module::getOrInsertFunction(), llvm::TargetLibraryInfo::has(), llvm::inferLibFuncAttributes(), llvm::CallBase::setCallingConv(), and llvm::Value::stripPointerCasts().
Referenced by llvm::emitBCmp(), llvm::emitMemCCpy(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::emitStpCpy(), llvm::emitStpNCpy(), llvm::emitStrCat(), llvm::emitStrChr(), llvm::emitStrCpy(), llvm::emitStrDup(), llvm::emitStrLCat(), llvm::emitStrLCpy(), llvm::emitStrLen(), llvm::emitStrNCat(), llvm::emitStrNCmp(), llvm::emitStrNCpy(), llvm::emitVSNPrintf(), and llvm::emitVSPrintf().
emitUnaryFloatFnCallHelper()
static Value* emitUnaryFloatFnCallHelper (Value * Op, StringRef Name, IRBuilder<> & B, const AttributeList & Attrs) static
Definition at line 1042 of file BuildLibCalls.cpp.
References assert(), Callee, llvm::IRBuilder< T, Inserter >::CreateCall(), F(), llvm::AttributeList::FunctionIndex, llvm::FunctionCallee::getCallee(), llvm::IRBuilderBase::getContext(), llvm::IRBuilderBase::GetInsertBlock(), llvm::BasicBlock::getModule(), llvm::Module::getOrInsertFunction(), llvm::Value::getType(), llvm::AttributeList::removeAttribute(), llvm::CallBase::setAttributes(), llvm::CallBase::setCallingConv(), and llvm::Value::stripPointerCasts().
Referenced by llvm::emitUnaryFloatFnCall().
setDoesNotAccessMemory()
static bool setDoesNotAccessMemory (Function & F) static
Definition at line 43 of file BuildLibCalls.cpp.
References llvm::Function::doesNotAccessMemory(), and llvm::Function::setDoesNotAccessMemory().
Referenced by llvm::inferLibFuncAttributes(), and llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::setDoesNotAccessMemory().
setDoesNotAlias()
static bool setDoesNotAlias (Function & F, unsigned ArgNo) static
Definition at line 91 of file BuildLibCalls.cpp.
References llvm::Function::addParamAttr(), llvm::Function::hasParamAttribute(), and llvm::NoAlias.
Referenced by llvm::inferLibFuncAttributes().
setDoesNotCapture()
static bool setDoesNotCapture (Function & F, unsigned ArgNo) static
Definition at line 83 of file BuildLibCalls.cpp.
References llvm::Function::addParamAttr(), and llvm::Function::hasParamAttribute().
Referenced by llvm::inferLibFuncAttributes().
setDoesNotFreeMemory()
static bool setDoesNotFreeMemory (Function & F) static
Definition at line 132 of file BuildLibCalls.cpp.
References llvm::Function::addFnAttr(), and llvm::Function::hasFnAttribute().
Referenced by llvm::inferLibFuncAttributes().
setDoesNotThrow()
static bool setDoesNotThrow (Function & F) static
Definition at line 67 of file BuildLibCalls.cpp.
References llvm::Function::doesNotThrow(), and llvm::Function::setDoesNotThrow().
Referenced by llvm::createObjCARCOptPass(), llvm::inferLibFuncAttributes(), and llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::setDoesNotThrow().
setNonLazyBind()
static bool setNonLazyBind (Function & F) static
Definition at line 125 of file BuildLibCalls.cpp.
References llvm::Function::addFnAttr(), and llvm::Function::hasFnAttribute().
Referenced by llvm::inferLibFuncAttributes(), and lowerObjCCall().
setOnlyAccessesArgMemory()
static bool setOnlyAccessesArgMemory (Function & F) static
Definition at line 59 of file BuildLibCalls.cpp.
References llvm::Function::onlyAccessesArgMemory(), and llvm::Function::setOnlyAccessesArgMemory().
Referenced by llvm::inferLibFuncAttributes(), and llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::setOnlyAccessesArgMemory().
setOnlyReadsMemory() [1/2]
static bool setOnlyReadsMemory (Function & F) static
Definition at line 51 of file BuildLibCalls.cpp.
References llvm::Function::onlyReadsMemory(), and llvm::Function::setOnlyReadsMemory().
Referenced by llvm::inferLibFuncAttributes(), and llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::setOnlyReadsMemory().
setOnlyReadsMemory() [2/2]
static bool setOnlyReadsMemory (Function & F, unsigned ArgNo) static
Definition at line 99 of file BuildLibCalls.cpp.
References llvm::Function::addParamAttr(), and llvm::Function::hasParamAttribute().
setRetDoesNotAlias()
static bool setRetDoesNotAlias (Function & F) static
Definition at line 75 of file BuildLibCalls.cpp.
References llvm::Function::addAttribute(), llvm::Function::hasAttribute(), llvm::NoAlias, and llvm::AttributeList::ReturnIndex.
Referenced by llvm::inferLibFuncAttributes().
setRetNonNull()
static bool setRetNonNull (Function & F) static
Definition at line 107 of file BuildLibCalls.cpp.
References llvm::Function::addAttribute(), assert(), llvm::Function::getReturnType(), llvm::Function::hasAttribute(), llvm::Type::isPointerTy(), and llvm::AttributeList::ReturnIndex.
Referenced by llvm::inferLibFuncAttributes().
setReturnedArg()
static bool setReturnedArg (Function & F, unsigned ArgNo) static
Definition at line 117 of file BuildLibCalls.cpp.
References llvm::Function::addParamAttr(), and llvm::Function::hasParamAttribute().
Referenced by llvm::inferLibFuncAttributes().
STATISTIC() [1/9]
STATISTIC (NumReadNone , "Number of functions inferred as readnone")
STATISTIC() [2/9]
STATISTIC (NumReadOnly , "Number of functions inferred as readonly")
STATISTIC() [3/9]
STATISTIC (NumArgMemOnly , "Number of functions inferred as argmemonly")
STATISTIC() [4/9]
STATISTIC (NumNoUnwind , "Number of functions inferred as nounwind")
STATISTIC() [5/9]
STATISTIC (NumNoCapture , "Number of arguments inferred as nocapture")
STATISTIC() [6/9]
STATISTIC (NumReadOnlyArg , "Number of arguments inferred as readonly")
STATISTIC() [7/9]
STATISTIC (NumNoAlias , "Number of function returns inferred as noalias")
STATISTIC() [8/9]
STATISTIC (NumNonNull , "Number of function returns inferred as nonnull returns")
STATISTIC() [9/9]
STATISTIC (NumReturnedArg , "Number of arguments inferred as returned")