LLVM: include/llvm-c/Comdat.h File Reference
Comdat.h File Reference
#include "llvm-c/ExternC.h"
#include "llvm-c/Types.h"
Enumerations
enum LLVMComdatSelectionKind {
LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDuplicatesComdatSelectionKind,
LLVMSameSizeComdatSelectionKind
}
Functions
LLVMComdatRef LLVMGetOrInsertComdat (LLVMModuleRef M, const char *Name)
Return the Comdat in the module with the specified name.
LLVMComdatRef LLVMGetComdat (LLVMValueRef V)
Get the Comdat assigned to the given global object.
void LLVMSetComdat (LLVMValueRef V, LLVMComdatRef C)
Assign the Comdat to the given global object.
LLVMComdatSelectionKind LLVMGetComdatSelectionKind (LLVMComdatRef C)
void LLVMSetComdatSelectionKind (LLVMComdatRef C, LLVMComdatSelectionKind Kind)
Enumeration Type Documentation
LLVMComdatSelectionKind
enum LLVMComdatSelectionKind
Enumerator
LLVMAnyComdatSelectionKind
The linker may choose any COMDAT.
LLVMExactMatchComdatSelectionKind
The data referenced by the COMDAT must be the same.
LLVMLargestComdatSelectionKind
The linker will choose the largest COMDAT.
LLVMNoDuplicatesComdatSelectionKind
No other Module may specify this COMDAT.
LLVMSameSizeComdatSelectionKind
The data referenced by the COMDAT must be the same size.
Definition at line 22 of file Comdat.h.
Function Documentation
LLVMGetComdat()
LLVMComdatRef LLVMGetComdat (LLVMValueRef V)
Get the Comdat assigned to the given global object.
See also
llvm::GlobalObject::getComdat()
Definition at line 32 of file Comdat.cpp.
References G, llvm::GlobalObject::getComdat(), and llvm::wrap().
LLVMGetComdatSelectionKind()
LLVMComdatSelectionKind LLVMGetComdatSelectionKind (LLVMComdatRef C)
Definition at line 42 of file Comdat.cpp.
References llvm::Comdat::Any, llvm::Comdat::ExactMatch, llvm::Comdat::getSelectionKind(), llvm::Comdat::Largest, llvm_unreachable, LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDuplicatesComdatSelectionKind, LLVMSameSizeComdatSelectionKind, llvm::Comdat::NoDuplicates, llvm::Comdat::SameSize, and llvm::unwrap().
LLVMGetOrInsertComdat()
LLVMComdatRef LLVMGetOrInsertComdat (LLVMModuleRef M, const char * Name)
Return the Comdat in the module with the specified name.
It is created if it didn't already exist.
See also
llvm::Module::getOrInsertComdat()
Definition at line 28 of file Comdat.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMSetComdat()
void LLVMSetComdat (LLVMValueRef V, LLVMComdatRef C)
Assign the Comdat to the given global object.
See also
llvm::GlobalObject::setComdat()
Definition at line 37 of file Comdat.cpp.
References G, llvm::GlobalObject::setComdat(), and llvm::unwrap().
LLVMSetComdatSelectionKind()
void LLVMSetComdatSelectionKind (LLVMComdatRef C, LLVMComdatSelectionKind Kind)
Definition at line 58 of file Comdat.cpp.
References llvm::Comdat::Any, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDuplicatesComdatSelectionKind, LLVMSameSizeComdatSelectionKind, llvm::Comdat::NoDuplicates, llvm::Comdat::SameSize, llvm::Comdat::setSelectionKind(), and llvm::unwrap().