LLVM: include/llvm-c/ErrorHandling.h File Reference
ErrorHandling.h File Reference
#include "llvm-c/ExternC.h"
Functions
void LLVMInstallFatalErrorHandler (LLVMFatalErrorHandler Handler)
Install a fatal error handler.
void LLVMResetFatalErrorHandler (void)
Reset the fatal error handler.
void LLVMEnablePrettyStackTrace (void)
Enable LLVM's built-in stack trace code.
Variables
LLVM_C_EXTERN_C_BEGIN typedef void(* LLVMFatalErrorHandler)(const char *Reason)
Function Documentation
LLVMEnablePrettyStackTrace()
void LLVMEnablePrettyStackTrace (void)
Enable LLVM's built-in stack trace code.
This intercepts the OS's crash signals and prints which component of LLVM you were in at the time if the crash.
Definition at line 298 of file PrettyStackTrace.cpp.
References llvm::EnablePrettyStackTrace().
LLVMInstallFatalErrorHandler()
void LLVMInstallFatalErrorHandler (LLVMFatalErrorHandler Handler)
Install a fatal error handler.
By default, if LLVM detects a fatal error, it will call exit(1). This may not be appropriate in many contexts. For example, doing exit(1) will bypass many crash reporting/tracing system tools. This function allows you to install a callback that will be invoked prior to the call to exit(1).
Definition at line 225 of file ErrorHandling.cpp.
References bindingsErrorHandler(), llvm::install_fatal_error_handler(), and LLVM_EXTENSION.
LLVMResetFatalErrorHandler()
void LLVMResetFatalErrorHandler (void)
Reset the fatal error handler.
This resets LLVM's fatal error handling behavior to the default.
Definition at line 230 of file ErrorHandling.cpp.
References llvm::bad_address, llvm::bad_file_descriptor, llvm::device_or_resource_busy, llvm::directory_not_empty, llvm::file_exists, llvm::filename_too_long, llvm::function_not_supported, llvm::interrupted, llvm::invalid_argument, llvm::io_error, llvm::mapWindowsError(), llvm::no_lock_available, llvm::no_space_on_device, llvm::no_such_device, llvm::no_such_file_or_directory, llvm::not_enough_memory, llvm::permission_denied, llvm::remove_fatal_error_handler(), llvm::resource_unavailable_try_again, and llvm::too_many_files_open.
Variable Documentation
LLVMFatalErrorHandler
LLVM_C_EXTERN_C_BEGIN typedef void(* LLVMFatalErrorHandler) (const char *Reason)
Definition at line 21 of file ErrorHandling.h.
Referenced by bindingsErrorHandler().