LLVM: include/llvm-c/IRReader.h File Reference
IRReader.h File Reference
#include "llvm-c/ExternC.h"
#include "llvm-c/Types.h"
Functions
LLVM_C_EXTERN_C_BEGIN LLVMBool LLVMParseIRInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
Read LLVM IR from a memory buffer and convert it into an in-memory Module object.
Function Documentation
LLVMParseIRInContext()
LLVM_C_EXTERN_C_BEGIN LLVMBool LLVMParseIRInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Read LLVM IR from a memory buffer and convert it into an in-memory Module object.
Returns 0 on success. Optionally returns a human-readable description of any errors that occurred during parsing IR. OutMessage must be disposed with LLVMDisposeMessage.
See also
llvm::ParseIR()
Definition at line 115 of file IRReader.cpp.
References llvm::raw_ostream::flush(), llvm::parseIR(), llvm::SMDiagnostic::print(), llvm::release, llvm::unwrap(), and llvm::wrap().