LLVM: include/llvm-c/TargetMachine.h File Reference
TargetMachine.h File Reference
#include "llvm-c/ExternC.h"
#include "llvm-c/Target.h"
#include "llvm-c/Types.h"
Typedefs
typedef typedefLLVM_C_EXTERN_C_BEGIN struct LLVMOpaqueTargetMachine * LLVMTargetMachineRef
typedef struct LLVMTarget * LLVMTargetRef
Enumerations
enum LLVMCodeGenOptLevel { LLVMCodeGenLevelNone, LLVMCodeGenLevelLess, LLVMCodeGenLevelDefault, LLVMCodeGenLevelAggressive }
enum LLVMRelocMode {
LLVMRelocDefault, LLVMRelocStatic, LLVMRelocPIC, LLVMRelocDynamicNoPic,
LLVMRelocROPI, LLVMRelocRWPI, LLVMRelocROPI_RWPI
}
enum LLVMCodeModel {
LLVMCodeModelDefault, LLVMCodeModelJITDefault, LLVMCodeModelTiny, LLVMCodeModelSmall,
LLVMCodeModelKernel, LLVMCodeModelMedium, LLVMCodeModelLarge
}
enum LLVMCodeGenFileType { LLVMAssemblyFile, LLVMObjectFile }
Functions
LLVMTargetRef LLVMGetFirstTarget (void)
Returns the first llvm::Target in the registered targets list.
LLVMTargetRef LLVMGetNextTarget (LLVMTargetRef T)
Returns the next llvm::Target given a previous one (or null if there's none)
LLVMTargetRef LLVMGetTargetFromName (const char *Name)
Finds the target corresponding to the given name and stores it in T.
LLVMBool LLVMGetTargetFromTriple (const char *Triple, LLVMTargetRef *T, char **ErrorMessage)
Finds the target corresponding to the given triple and stores it in T.
const char * LLVMGetTargetName (LLVMTargetRef T)
Returns the name of a target.
const char * LLVMGetTargetDescription (LLVMTargetRef T)
Returns the description of a target.
LLVMBool LLVMTargetHasJIT (LLVMTargetRef T)
Returns if the target has a JIT.
LLVMBool LLVMTargetHasTargetMachine (LLVMTargetRef T)
Returns if the target has a TargetMachine associated.
LLVMBool LLVMTargetHasAsmBackend (LLVMTargetRef T)
Returns if the target as an ASM backend (required for emitting output)
LLVMTargetMachineRef LLVMCreateTargetMachine (LLVMTargetRef T, const char *Triple, const char *CPU, const char *Features, LLVMCodeGenOptLevel Level, LLVMRelocMode Reloc, LLVMCodeModel CodeModel)
Creates a new llvm::TargetMachine.
void LLVMDisposeTargetMachine (LLVMTargetMachineRef T)
Dispose the LLVMTargetMachineRef instance generated by LLVMCreateTargetMachine.
LLVMTargetRef LLVMGetTargetMachineTarget (LLVMTargetMachineRef T)
Returns the Target used in a TargetMachine.
char * LLVMGetTargetMachineTriple (LLVMTargetMachineRef T)
Returns the triple used creating this target machine.
char * LLVMGetTargetMachineCPU (LLVMTargetMachineRef T)
Returns the cpu used creating this target machine.
char * LLVMGetTargetMachineFeatureString (LLVMTargetMachineRef T)
Returns the feature string used creating this target machine.
LLVMTargetDataRef LLVMCreateTargetDataLayout (LLVMTargetMachineRef T)
Create a DataLayout based on the targetMachine.
void LLVMSetTargetMachineAsmVerbosity (LLVMTargetMachineRef T, LLVMBool VerboseAsm)
Set the target machine's ASM verbosity.
LLVMBool LLVMTargetMachineEmitToFile (LLVMTargetMachineRef T, LLVMModuleRef M, char *Filename, LLVMCodeGenFileType codegen, char **ErrorMessage)
Emits an asm or object file for the given module to the filename.
LLVMBool LLVMTargetMachineEmitToMemoryBuffer (LLVMTargetMachineRef T, LLVMModuleRef M, LLVMCodeGenFileType codegen, char **ErrorMessage, LLVMMemoryBufferRef *OutMemBuf)
Compile the LLVM IR stored in M and store the result in OutMemBuf.
char * LLVMGetDefaultTargetTriple (void)
Get a triple for the host machine as a string.
char * LLVMNormalizeTargetTriple (const char *triple)
Normalize a target triple.
char * LLVMGetHostCPUName (void)
Get the host CPU as a string.
char * LLVMGetHostCPUFeatures (void)
Get the host CPU's features as a string.
void LLVMAddAnalysisPasses (LLVMTargetMachineRef T, LLVMPassManagerRef PM)
Adds the target-specific analysis passes to the pass manager.
Typedef Documentation
LLVMTargetMachineRef
typedef typedefLLVM_C_EXTERN_C_BEGIN struct LLVMOpaqueTargetMachine* LLVMTargetMachineRef
Definition at line 28 of file TargetMachine.h.
LLVMTargetRef
typedef struct LLVMTarget* LLVMTargetRef
Definition at line 29 of file TargetMachine.h.
Enumeration Type Documentation
LLVMCodeGenFileType
enum LLVMCodeGenFileType
Enumerator
LLVMAssemblyFile
LLVMObjectFile
Definition at line 58 of file TargetMachine.h.
LLVMCodeGenOptLevel
enum LLVMCodeGenOptLevel
Enumerator
LLVMCodeGenLevelNone
LLVMCodeGenLevelLess
LLVMCodeGenLevelDefault
LLVMCodeGenLevelAggressive
Definition at line 31 of file TargetMachine.h.
LLVMCodeModel
enum LLVMCodeModel
Enumerator
LLVMCodeModelDefault
LLVMCodeModelJITDefault
LLVMCodeModelTiny
LLVMCodeModelSmall
LLVMCodeModelKernel
LLVMCodeModelMedium
LLVMCodeModelLarge
Definition at line 48 of file TargetMachine.h.
LLVMRelocMode
enum LLVMRelocMode
Enumerator
LLVMRelocDefault
LLVMRelocStatic
LLVMRelocPIC
LLVMRelocDynamicNoPic
LLVMRelocROPI
LLVMRelocRWPI
LLVMRelocROPI_RWPI
Definition at line 38 of file TargetMachine.h.
Function Documentation
LLVMAddAnalysisPasses()
void LLVMAddAnalysisPasses (LLVMTargetMachineRef T, LLVMPassManagerRef PM)
Adds the target-specific analysis passes to the pass manager.
Definition at line 268 of file TargetMachineC.cpp.
References llvm::createTargetTransformInfoWrapperPass(), and llvm::unwrap().
LLVMCreateTargetDataLayout()
LLVMTargetDataRef LLVMCreateTargetDataLayout (LLVMTargetMachineRef T)
Create a DataLayout based on the targetMachine.
Definition at line 181 of file TargetMachineC.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMCreateTargetMachine()
LLVMTargetMachineRef LLVMCreateTargetMachine (LLVMTargetRef T, const char * Triple, const char * CPU, const char * Features, LLVMCodeGenOptLevel Level, LLVMRelocMode Reloc, LLVMCodeModel CodeModel)
Creates a new llvm::TargetMachine.
See llvm::Target::createTargetMachine
Definition at line 102 of file TargetMachineC.cpp.
References llvm::CodeGenOpt::Aggressive, llvm::CodeGenOpt::Default, llvm::Reloc::DynamicNoPIC, llvm::EngineKind::JIT, llvm::CodeGenOpt::Less, LLVMCodeGenLevelAggressive, LLVMCodeGenLevelLess, LLVMCodeGenLevelNone, LLVMRelocDynamicNoPic, LLVMRelocPIC, LLVMRelocROPI, LLVMRelocROPI_RWPI, LLVMRelocRWPI, LLVMRelocStatic, llvm::CodeGenOpt::None, opt, llvm::Reloc::PIC_, llvm::NVPTX::PTXCvtMode::RM, llvm::Reloc::ROPI, llvm::Reloc::ROPI_RWPI, llvm::Reloc::RWPI, llvm::Reloc::Static, llvm::unwrap(), and llvm::wrap().
LLVMDisposeTargetMachine()
void LLVMDisposeTargetMachine (LLVMTargetMachineRef T)
Dispose the LLVMTargetMachineRef instance generated by LLVMCreateTargetMachine.
Definition at line 154 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMGetDefaultTargetTriple()
char* LLVMGetDefaultTargetTriple (void)
Get a triple for the host machine as a string.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 245 of file TargetMachineC.cpp.
References llvm::c_str(), and llvm::sys::getDefaultTargetTriple().
LLVMGetFirstTarget()
LLVMTargetRef LLVMGetFirstTarget (void)
Returns the first llvm::Target in the registered targets list.
Definition at line 47 of file TargetMachineC.cpp.
References llvm::sys::path::begin(), llvm::sys::path::end(), llvm::TargetRegistry::targets(), and llvm::wrap().
LLVMGetHostCPUFeatures()
char* LLVMGetHostCPUFeatures (void)
Get the host CPU's features as a string.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 257 of file TargetMachineC.cpp.
References llvm::SubtargetFeatures::AddFeature(), F(), llvm::sys::getHostCPUFeatures(), and llvm::SubtargetFeatures::getString().
LLVMGetHostCPUName()
char* LLVMGetHostCPUName (void)
Get the host CPU as a string.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 253 of file TargetMachineC.cpp.
References llvm::sys::getHostCPUName().
LLVMGetNextTarget()
LLVMTargetRef LLVMGetNextTarget (LLVMTargetRef T)
Returns the next llvm::Target given a previous one (or null if there's none)
Definition at line 55 of file TargetMachineC.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetTargetDescription()
const char* LLVMGetTargetDescription (LLVMTargetRef T)
Returns the description of a target.
See llvm::Target::getDescription
Definition at line 86 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMGetTargetFromName()
LLVMTargetRef LLVMGetTargetFromName (const char * Name)
Finds the target corresponding to the given name and stores it in T.
Returns 0 on success.
Definition at line 59 of file TargetMachineC.cpp.
References llvm::find_if(), llvm::Target::getName(), I, Name, llvm::TargetRegistry::targets(), and llvm::wrap().
LLVMGetTargetFromTriple()
LLVMBool LLVMGetTargetFromTriple (const char * Triple, LLVMTargetRef * T, char ** ErrorMessage)
Finds the target corresponding to the given triple and stores it in T.
Returns 0 on success. Optionally returns any error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.
Definition at line 66 of file TargetMachineC.cpp.
References llvm::TargetRegistry::lookupTarget(), and llvm::wrap().
LLVMGetTargetMachineCPU()
char* LLVMGetTargetMachineCPU (LLVMTargetMachineRef T)
Returns the cpu used creating this target machine.
See llvm::TargetMachine::getCPU. The result needs to be disposed with LLVMDisposeMessage.
Definition at line 166 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMGetTargetMachineFeatureString()
char* LLVMGetTargetMachineFeatureString (LLVMTargetMachineRef T)
Returns the feature string used creating this target machine.
See llvm::TargetMachine::getFeatureString. The result needs to be disposed with LLVMDisposeMessage.
Definition at line 171 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMGetTargetMachineTarget()
LLVMTargetRef LLVMGetTargetMachineTarget (LLVMTargetMachineRef T)
Returns the Target used in a TargetMachine.
Definition at line 156 of file TargetMachineC.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetTargetMachineTriple()
char* LLVMGetTargetMachineTriple (LLVMTargetMachineRef T)
Returns the triple used creating this target machine.
See llvm::TargetMachine::getTriple. The result needs to be disposed with LLVMDisposeMessage.
Definition at line 161 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMGetTargetName()
const char* LLVMGetTargetName (LLVMTargetRef T)
Returns the name of a target.
See llvm::Target::getName
Definition at line 82 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMNormalizeTargetTriple()
char* LLVMNormalizeTargetTriple (const char * triple)
Normalize a target triple.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 249 of file TargetMachineC.cpp.
References llvm::c_str(), and llvm::Triple::normalize().
LLVMSetTargetMachineAsmVerbosity()
void LLVMSetTargetMachineAsmVerbosity (LLVMTargetMachineRef T, LLVMBool VerboseAsm)
Set the target machine's ASM verbosity.
Definition at line 176 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMTargetHasAsmBackend()
LLVMBool LLVMTargetHasAsmBackend (LLVMTargetRef T)
Returns if the target as an ASM backend (required for emitting output)
Definition at line 98 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMTargetHasJIT()
LLVMBool LLVMTargetHasJIT (LLVMTargetRef T)
Returns if the target has a JIT.
Definition at line 90 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMTargetHasTargetMachine()
LLVMBool LLVMTargetHasTargetMachine (LLVMTargetRef T)
Returns if the target has a TargetMachine associated.
Definition at line 94 of file TargetMachineC.cpp.
References llvm::unwrap().
LLVMTargetMachineEmitToFile()
LLVMBool LLVMTargetMachineEmitToFile (LLVMTargetMachineRef T, LLVMModuleRef M, char * Filename, LLVMCodeGenFileType codegen, char ** ErrorMessage)
Emits an asm or object file for the given module to the filename.
This wraps several c++ only classes (among them a file stream). Returns any error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.
Definition at line 219 of file TargetMachineC.cpp.
References llvm::raw_ostream::flush(), LLVMTargetMachineEmit(), and llvm::sys::fs::OF_None.
LLVMTargetMachineEmitToMemoryBuffer()
LLVMBool LLVMTargetMachineEmitToMemoryBuffer (LLVMTargetMachineRef T, LLVMModuleRef M, LLVMCodeGenFileType codegen, char ** ErrorMessage, LLVMMemoryBufferRef * OutMemBuf)
Compile the LLVM IR stored in M and store the result in OutMemBuf.
Definition at line 232 of file TargetMachineC.cpp.
References llvm::Data, llvm::StringRef::data(), LLVMCreateMemoryBufferWithMemoryRangeCopy(), LLVMTargetMachineEmit(), llvm::StringRef::size(), and llvm::raw_svector_ostream::str().