LLVM: lib/Analysis/CallGraphSCCPass.cpp File Reference
CallGraphSCCPass.cpp File Reference
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManagers.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/OptBisect.h"
#include "llvm/IR/PassTimingInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <string>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "cgscc-passmgr"
Functions
STATISTIC (MaxSCCIterations, "Maximum CGSCCPassMgr iterations on one SCC")
static std::string getDescription (const CallGraphSCC &SCC)
Variables
static cl::opt< unsigned > MaxIterations ("max-cg-scc-iterations", cl::ReallyHidden, cl::init(4))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "cgscc-passmgr"
Definition at line 42 of file CallGraphSCCPass.cpp.
Function Documentation
getDescription()
static std::string getDescription (const CallGraphSCC & SCC) static
Definition at line 684 of file CallGraphSCCPass.cpp.
References llvm::CallGraphNode::getFunction(), and llvm::Value::getName().
Referenced by llvm::Check::FileCheckType::getCount(), llvm::cl::generic_parser_base::getOptionWidth(), llvm::cl::generic_parser_base::printOptionInfo(), and llvm::CallGraphSCCPass::skipSCC().
STATISTIC()
STATISTIC (MaxSCCIterations , "Maximum CGSCCPassMgr iterations on one SCC")
Variable Documentation
MaxIterations
cl::opt<unsigned> MaxIterations("max-cg-scc-iterations", cl::ReallyHidden, cl::init(4)) static
Referenced by llvm::createDevirtSCCRepeatedPass(), getOtherIncomingValue(), and llvm::DevirtSCCRepeatedPass< PassT >::run().