LLVM: lib/Transforms/IPO/CalledValuePropagation.cpp File Reference
CalledValuePropagation.cpp File Reference
#include "llvm/Transforms/IPO/CalledValuePropagation.h"
#include "llvm/Analysis/SparsePropagation.h"
#include "llvm/Analysis/ValueLatticeUtils.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/IPO.h"
Classes
struct llvm::LatticeKeyInfo< CVPLatticeKey >
A specialization of LatticeKeyInfo for CVPLatticeKeys.
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "called-value-propagation"
Enumerations
enum IPOGrouping
To enable interprocedural analysis, we assign LLVM values to the following groups.
Functions
static bool runCVP (Module &M)
INITIALIZE_PASS (CalledValuePropagationLegacyPass, "called-value-propagation", "Called Value Propagation", false, false) ModulePass *llvm
Variables
static cl::opt< unsigned > MaxFunctionsPerValue ("cvp-max-functions-per-value", cl::Hidden, cl::init(4), cl::desc("The maximum number of functions to track per lattice value"))
The maximum number of functions to track per lattice value.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "called-value-propagation"
Definition at line 29 of file CalledValuePropagation.cpp.
Enumeration Type Documentation
IPOGrouping
enum IPOGrouping strong
To enable interprocedural analysis, we assign LLVM values to the following groups.
The register group represents SSA registers, the return group represents the return values of functions, and the memory group represents in-memory values. An LLVM Value can technically be in more than one group. It's necessary to distinguish these groups so we can, for example, track a global variable separately from the value stored at its location.
Definition at line 49 of file CalledValuePropagation.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (CalledValuePropagationLegacyPass , "called-value-propagation" , "Called Value Propagation" , false , false)
Definition at line 434 of file CalledValuePropagation.cpp.
runCVP()
static bool runCVP (Module & M) static
Definition at line 372 of file CalledValuePropagation.cpp.
References C, llvm::canTrackArgumentsInterprocedurally(), F(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledValue(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::getExistingValueState(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::MarkBlockExecutable(), Register, llvm::Instruction::setMetadata(), and llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::Solve().
Referenced by llvm::CalledValuePropagationPass::run().
Variable Documentation
MaxFunctionsPerValue
cl::opt<unsigned> MaxFunctionsPerValue("cvp-max-functions-per-value", cl::Hidden, cl::init(4), cl::desc("The maximum number of functions to track per lattice value")) static
The maximum number of functions to track per lattice value.
Once the number of functions a call site can possibly target exceeds this threshold, it's lattice value becomes overdefined. The number of possible lattice values is bounded by Ch(F, M), where F is the number of functions in the module and M is MaxFunctionsPerValue. As such, this value should be kept very small. We likely can't do anything useful for call sites with a large number of possible targets, anyway.