LLVM: lib/CodeGen/CFIInstrInserter.cpp File Reference
CFIInstrInserter.cpp File Reference
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Target/TargetMachine.h"
Functions
INITIALIZE_PASS (CFIInstrInserter, "cfi-instr-inserter", "Check CFA info and insert CFI instructions if needed", false, false) FunctionPass *llvm
Variables
static cl::opt< bool > VerifyCFI ("verify-cfiinstrs", cl::desc("Verify Call Frame Information instructions"), cl::init(false), cl::Hidden)
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (CFIInstrInserter , "cfi-instr-inserter" , "Check CFA info and insert CFI instructions if needed" , false , false)
Definition at line 121 of file CFIInstrInserter.cpp.
References llvm::BuildMI(), llvm::MCCFIInstruction::createDefCfa(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::depth_first(), llvm::SmallVectorBase::empty(), llvm::errs(), llvm::MachineFunction::front(), llvm::MCInstrInfo::get(), llvm::MachineOperand::getCFIIndex(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetFrameLowering::getInitialCFAOffset(), llvm::TargetFrameLowering::getInitialCFARegister(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getNumber(), llvm::MCCFIInstruction::getOffset(), llvm::MachineInstr::getOperand(), llvm::MCCFIInstruction::getOperation(), llvm::MCCFIInstruction::getRegister(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::isCFIInstruction(), MI, llvm::MCCFIInstruction::OpAdjustCfaOffset, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaOffset, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpEscape, llvm::MCCFIInstruction::OpGnuArgsSize, llvm::MCCFIInstruction::OpNegateRAState, llvm::MCCFIInstruction::OpOffset, llvm::MCCFIInstruction::OpRegister, llvm::MCCFIInstruction::OpRelOffset, llvm::MCCFIInstruction::OpRememberState, llvm::MCCFIInstruction::OpRestore, llvm::MCCFIInstruction::OpRestoreState, llvm::MCCFIInstruction::OpSameValue, llvm::MCCFIInstruction::OpUndefined, llvm::MCCFIInstruction::OpWindowSave, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), TII, and verify.
Variable Documentation
VerifyCFI
cl::opt<bool> VerifyCFI("verify-cfiinstrs", cl::desc("Verify Call Frame Information instructions"), cl::init(false), cl::Hidden) static