LLVM: llvm::AVRInstPrinter Class Reference
llvm::AVRInstPrinter Class Reference
Prints AVR instructions to a textual stream.
#include "Target/AVR/MCTargetDesc/AVRInstPrinter.h"
Public Member Functions
AVRInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getPrettyRegisterName (unsigned RegNo, MCRegisterInfo const &MRI)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Prints AVR instructions to a textual stream.
Definition at line 23 of file AVRInstPrinter.h.
Constructor & Destructor Documentation
AVRInstPrinter()
llvm::AVRInstPrinter::AVRInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 25 of file AVRInstPrinter.h.
References llvm::Address, getPrettyRegisterName(), MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, and printInst().
Member Function Documentation
getPrettyRegisterName()
const char * llvm::AVRInstPrinter::getPrettyRegisterName (unsigned RegNo, MCRegisterInfo const & MRI) static
Definition at line 89 of file AVRInstPrinter.cpp.
References assert(), llvm::MCInstrInfo::get(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCRegisterInfo::getNumSubRegIndices(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getSubReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, MI, llvm::MCInstPrinter::MII, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, and llvm::MCOperandInfo::RegClass.
Referenced by AVRInstPrinter(), llvm::AVRAsmPrinter::PrintAsmOperand(), and llvm::AVRAsmPrinter::printOperand().
printInst()
void llvm::AVRInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 35 of file AVRInstPrinter.cpp.
References llvm::MCInst::getOpcode(), and llvm::MCInstPrinter::printAnnotation().
Referenced by AVRInstPrinter().
The documentation for this class was generated from the following files:
lib/Target/AVR/MCTargetDesc/AVRInstPrinter.h
lib/Target/AVR/MCTargetDesc/AVRInstPrinter.cpp