LLVM: llvm::OptPassGate Class Reference
llvm::OptPassGate Class Reference
Extensions to this class implement mechanisms to disable passes and individual optimizations at compile time.
#include "llvm/IR/OptBisect.h"
Public Member Functions
virtual ~OptPassGate ()=default
virtual bool shouldRunPass (const Pass *P, StringRef IRDescription)
IRDescription is a textual description of the IR unit the pass is running over.
virtual bool isEnabled () const
isEnabled should return true before calling shouldRunPass
Detailed Description
Extensions to this class implement mechanisms to disable passes and individual optimizations at compile time.
Definition at line 25 of file OptBisect.h.
Constructor & Destructor Documentation
~OptPassGate()
virtual llvm::OptPassGate::~OptPassGate () virtual default
Member Function Documentation
isEnabled()
virtual bool llvm::OptPassGate::isEnabled () const inline virtual
isEnabled should return true before calling shouldRunPass
Reimplemented in llvm::OptBisect.
Definition at line 36 of file OptBisect.h.
Referenced by llvm::FunctionPass::skipFunction(), llvm::LoopPass::skipLoop(), llvm::ModulePass::skipModule(), llvm::RegionPass::skipRegion(), and llvm::CallGraphSCCPass::skipSCC().
shouldRunPass()
virtual bool llvm::OptPassGate::shouldRunPass (const Pass * P, StringRef IRDescription) inline virtual
IRDescription is a textual description of the IR unit the pass is running over.
Reimplemented in llvm::OptBisect.
Definition at line 31 of file OptBisect.h.
Referenced by llvm::FunctionPass::skipFunction(), llvm::LoopPass::skipLoop(), llvm::ModulePass::skipModule(), llvm::RegionPass::skipRegion(), and llvm::CallGraphSCCPass::skipSCC().
The documentation for this class was generated from the following file:
include/llvm/IR/OptBisect.h