LLVM: llvm::RegAllocBase Class Reference
llvm::RegAllocBase Class Reference abstract
RegAllocBase provides the register allocation driver and interface that can be extended to add interesting heuristics.
#include "CodeGen/RegAllocBase.h"
Static Public Attributes
static bool VerifyEnabled = false
VerifyEnabled - True when -verify-regalloc is given.
Protected Member Functions
RegAllocBase ()=default
virtual ~RegAllocBase ()=default
void init (VirtRegMap &vrm, LiveIntervals &lis, LiveRegMatrix &mat)
void allocatePhysRegs ()
virtual void postOptimization ()
virtual Spiller & spiller ()=0
virtual void enqueue (LiveInterval *LI)=0
enqueue - Add VirtReg to the priority queue of unassigned registers.
virtual LiveInterval * dequeue ()=0
dequeue - Return the next unassigned register, or NULL.
virtual unsigned selectOrSplit (LiveInterval &VirtReg, SmallVectorImpl< unsigned > &splitLVRs)=0
virtual void aboutToRemoveInterval (LiveInterval &LI)
Method called when the allocator is about to remove a LiveInterval.
Protected Attributes
const TargetRegisterInfo * TRI = nullptr
MachineRegisterInfo * MRI = nullptr
VirtRegMap * VRM = nullptr
LiveIntervals * LIS = nullptr
LiveRegMatrix * Matrix = nullptr
RegisterClassInfo RegClassInfo
SmallPtrSet< MachineInstr *, 32 > DeadRemats
Inst which is a def of an original reg and whose defs are already all dead after remat is saved in DeadRemats.
Static Protected Attributes
static const char TimerGroupName [] = "regalloc"
static const char TimerGroupDescription [] = "Register Allocation"
Detailed Description
RegAllocBase provides the register allocation driver and interface that can be extended to add interesting heuristics.
Register allocators must override the selectOrSplit() method to implement live range splitting. They must also override enqueue/dequeue to provide an assignment order.
Definition at line 60 of file RegAllocBase.h.
Constructor & Destructor Documentation
RegAllocBase()
llvm::RegAllocBase::RegAllocBase () protected default
~RegAllocBase()
virtual llvm::RegAllocBase::~RegAllocBase () protected virtual default
Member Function Documentation
aboutToRemoveInterval()
virtual void llvm::RegAllocBase::aboutToRemoveInterval (LiveInterval & LI) inline protected virtual
Method called when the allocator is about to remove a LiveInterval.
Definition at line 112 of file RegAllocBase.h.
Referenced by allocatePhysRegs().
allocatePhysRegs()
void RegAllocBase::allocatePhysRegs () protected
Definition at line 85 of file RegAllocBase.cpp.
References aboutToRemoveInterval(), assert(), llvm::LiveRegMatrix::assign(), llvm::VirtRegMap::assignVirt2Phys(), Context, llvm::dbgs(), dequeue(), E, llvm::LLVMContext::emitError(), llvm::MachineInstr::emitError(), enqueue(), llvm::Module::getContext(), llvm::LiveIntervals::getInterval(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::getModule(), llvm::RegisterClassInfo::getOrder(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), llvm::LiveIntervals::hasInterval(), llvm::VirtRegMap::hasPhys(), I, llvm::LiveRegMatrix::invalidateVirtRegs(), llvm::MachineInstr::isInlineAsm(), llvm::Register::isVirtualRegister(), LIS, LLVM_DEBUG, Matrix, MI, MRI, Reg, llvm::MachineRegisterInfo::reg_instr_begin(), llvm::MachineRegisterInfo::reg_instr_end(), llvm::MachineRegisterInfo::reg_nodbg_empty(), RegClassInfo, llvm::LiveIntervals::removeInterval(), llvm::report_fatal_error(), selectOrSplit(), TRI, and VRM.
dequeue()
virtual LiveInterval* llvm::RegAllocBase::dequeue () protected pure virtual
dequeue - Return the next unassigned register, or NULL.
Referenced by allocatePhysRegs().
enqueue()
virtual void llvm::RegAllocBase::enqueue (LiveInterval * LI) protected pure virtual
enqueue - Add VirtReg to the priority queue of unassigned registers.
Referenced by allocatePhysRegs(), and init().
init()
void RegAllocBase::init (VirtRegMap & vrm, LiveIntervals & lis, LiveRegMatrix & mat) protected
Definition at line 57 of file RegAllocBase.cpp.
References llvm::numbers::e, enqueue(), llvm::MachineRegisterInfo::freezeReservedRegs(), llvm::LiveIntervals::getInterval(), llvm::VirtRegMap::getMachineFunction(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::VirtRegMap::getRegInfo(), llvm::VirtRegMap::getTargetRegInfo(), llvm::Register::index2VirtReg(), LIS, Matrix, MRI, Reg, llvm::MachineRegisterInfo::reg_nodbg_empty(), RegClassInfo, llvm::RegisterClassInfo::runOnMachineFunction(), llvm::T, llvm::TimePassesIsEnabled, TimerGroupDescription, TimerGroupName, TRI, and VRM.
postOptimization()
void RegAllocBase::postOptimization () protected virtual
Definition at line 165 of file RegAllocBase.cpp.
References DeadRemats, LIS, llvm::Spiller::postOptimization(), llvm::LiveIntervals::RemoveMachineInstrFromMaps(), and spiller().
selectOrSplit()
virtual unsigned llvm::RegAllocBase::selectOrSplit (LiveInterval & VirtReg, SmallVectorImpl< unsigned > & splitLVRs) protected pure virtual
Referenced by allocatePhysRegs().
spiller()
virtual Spiller& llvm::RegAllocBase::spiller () protected pure virtual
Referenced by postOptimization().
Member Data Documentation
DeadRemats
SmallPtrSet<MachineInstr *, 32> llvm::RegAllocBase::DeadRemats protected
Inst which is a def of an original reg and whose defs are already all dead after remat is saved in DeadRemats.
The deletion of such inst is postponed till all the allocations are done, so its remat expr is always available for the remat of all the siblings of the original reg.
Definition at line 75 of file RegAllocBase.h.
Referenced by postOptimization().
LIS
LiveIntervals* llvm::RegAllocBase::LIS = nullptr protected
Definition at line 67 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), init(), and postOptimization().
Matrix
LiveRegMatrix* llvm::RegAllocBase::Matrix = nullptr protected
Definition at line 68 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), and init().
MRI
MachineRegisterInfo* llvm::RegAllocBase::MRI = nullptr protected
Definition at line 65 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), and init().
RegClassInfo
RegisterClassInfo llvm::RegAllocBase::RegClassInfo protected
Definition at line 69 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), and init().
TimerGroupDescription
const char RegAllocBase::TimerGroupDescription = "Register Allocation" static protected
Definition at line 109 of file RegAllocBase.h.
Referenced by init().
TimerGroupName
const char RegAllocBase::TimerGroupName = "regalloc" static protected
Definition at line 108 of file RegAllocBase.h.
Referenced by init().
TRI
const TargetRegisterInfo* llvm::RegAllocBase::TRI = nullptr protected
Definition at line 64 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), and init().
VerifyEnabled
bool RegAllocBase::VerifyEnabled = false static
VerifyEnabled - True when -verify-regalloc is given.
Definition at line 116 of file RegAllocBase.h.
VRM
VirtRegMap* llvm::RegAllocBase::VRM = nullptr protected
Definition at line 66 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), and init().
The documentation for this class was generated from the following files:
lib/CodeGen/RegAllocBase.h
lib/CodeGen/RegAllocBase.cpp