LLVM: llvm::InsertPointAnalysis Class Reference
llvm::InsertPointAnalysis Class Reference
Determines the latest safe point in a block in which we can insert a split, spill or other instruction related with CurLI.
#include "CodeGen/SplitKit.h"
Public Member Functions
InsertPointAnalysis (const LiveIntervals &lis, unsigned BBNum)
SlotIndex getLastInsertPoint (const LiveInterval &CurLI, const MachineBasicBlock &MBB)
Return the base index of the last valid insert point for in .
MachineBasicBlock::iterator getLastInsertPointIter (const LiveInterval &CurLI, MachineBasicBlock &MBB)
Returns the last insert point as an iterator for in .
SlotIndex getFirstInsertPoint (MachineBasicBlock &MBB)
Return the base index of the first insert point in .
Detailed Description
Determines the latest safe point in a block in which we can insert a split, spill or other instruction related with CurLI.
Definition at line 49 of file SplitKit.h.
Constructor & Destructor Documentation
InsertPointAnalysis()
InsertPointAnalysis::InsertPointAnalysis (const LiveIntervals & lis, unsigned BBNum)
Definition at line 71 of file SplitKit.cpp.
References llvm::MachineBasicBlock::begin(), llvm::VNInfo::def, E, llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), for(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getMBBEndIdx(), llvm::MachineBasicBlock::getNumber(), llvm::LiveRange::getVNInfoBefore(), I, llvm::SlotIndex::isEarlierInstr(), llvm::LiveIntervals::isLiveInToMBB(), llvm::none_of(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::MachineBasicBlock::successors().
Member Function Documentation
getFirstInsertPoint()
SlotIndex llvm::InsertPointAnalysis::getFirstInsertPoint (MachineBasicBlock & MBB) inline
Return the base index of the first insert point in .
Definition at line 81 of file SplitKit.h.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getMBBStartIdx(), and llvm::MachineBasicBlock::SkipPHIsLabelsAndDebug().
Referenced by llvm::SplitAnalysis::getFirstSplitPoint().
getLastInsertPoint()
SlotIndex llvm::InsertPointAnalysis::getLastInsertPoint (const LiveInterval & CurLI, const MachineBasicBlock & MBB) inline
Return the base index of the last valid insert point for in .
Definition at line 66 of file SplitKit.h.
References first, and llvm::MachineBasicBlock::getNumber().
Referenced by getLastInsertPointIter(), and llvm::SplitAnalysis::getLastSplitPoint().
getLastInsertPointIter()
MachineBasicBlock::iterator InsertPointAnalysis::getLastInsertPointIter (const LiveInterval & CurLI, MachineBasicBlock & MBB)
Returns the last insert point as an iterator for in .
Definition at line 139 of file SplitKit.cpp.
References llvm::MachineBasicBlock::end(), llvm::LiveIntervals::getInstructionFromIndex(), getLastInsertPoint(), and llvm::LiveIntervals::getMBBEndIdx().
Referenced by llvm::SplitAnalysis::getLastSplitPointIter().
The documentation for this class was generated from the following files:
lib/CodeGen/SplitKit.h
lib/CodeGen/SplitKit.cpp