LLVM: llvm::vfs::directory_iterator Class Reference
llvm::vfs::directory_iterator Class Reference
An input iterator over the entries in a virtual path, similar to llvm::sys::fs::directory_iterator.
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
directory_iterator (std::shared_ptr< detail::DirIterImpl > I)
directory_iterator ()=default
Construct an 'end' iterator.
directory_iterator & increment (std::error_code &EC)
Equivalent to operator++, with an error code.
const directory_entry & operator* () const
const directory_entry * operator-> () const
bool operator== (const directory_iterator &RHS) const
bool operator!= (const directory_iterator &RHS) const
Detailed Description
An input iterator over the entries in a virtual path, similar to llvm::sys::fs::directory_iterator.
Definition at line 158 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
directory_iterator() [1/2]
llvm::vfs::directory_iterator::directory_iterator (std::shared_ptr< detail::DirIterImpl > I) inline
Definition at line 162 of file VirtualFileSystem.h.
References assert().
directory_iterator() [2/2]
llvm::vfs::directory_iterator::directory_iterator () default
Construct an 'end' iterator.
Member Function Documentation
increment()
directory_iterator& llvm::vfs::directory_iterator::increment (std::error_code & EC) inline
Equivalent to operator++, with an error code.
Definition at line 173 of file VirtualFileSystem.h.
References assert().
Referenced by llvm::vfs::OverlayFileSystem::getRealPath(), and llvm::vfs::VFSFromYamlDirIterImpl::increment().
operator!=()
bool llvm::vfs::directory_iterator::operator!= (const directory_iterator & RHS) const inline
Definition at line 189 of file VirtualFileSystem.h.
operator*()
const directory_entry& llvm::vfs::directory_iterator::operator* () const inline
Definition at line 181 of file VirtualFileSystem.h.
operator->()
const directory_entry* llvm::vfs::directory_iterator::operator-> () const inline
Definition at line 182 of file VirtualFileSystem.h.
operator==()
bool llvm::vfs::directory_iterator::operator== (const directory_iterator & RHS) const inline
Definition at line 184 of file VirtualFileSystem.h.
The documentation for this class was generated from the following file:
include/llvm/Support/VirtualFileSystem.h