LLVM: llvm::VLIWResourceModel Class Reference
llvm::VLIWResourceModel Class Reference
#include "Target/Hexagon/HexagonMachineScheduler.h"
Public Member Functions
VLIWResourceModel (const TargetSubtargetInfo &STI, const TargetSchedModel *SM)
~VLIWResourceModel ()
void resetPacketState ()
void resetDFA ()
void reset ()
bool isResourceAvailable (SUnit *SU, bool IsTop)
Check if scheduling of this SU is possible in the current packet.
bool reserveResources (SUnit *SU, bool IsTop)
Keep track of available resources.
unsigned getTotalPackets () const
bool isInPacket (SUnit *SU) const
Detailed Description
Definition at line 35 of file HexagonMachineScheduler.h.
Constructor & Destructor Documentation
VLIWResourceModel()
llvm::VLIWResourceModel::VLIWResourceModel (const TargetSubtargetInfo & STI, const TargetSchedModel * SM) inline
Definition at line 51 of file HexagonMachineScheduler.h.
References assert(), llvm::DFAPacketizer::clearResources(), llvm::TargetInstrInfo::CreateTargetScheduleState(), llvm::TargetSubtargetInfo::getInstrInfo(), and llvm::TargetSchedModel::getIssueWidth().
Referenced by llvm::ConvergingVLIWScheduler::initialize().
~VLIWResourceModel()
llvm::VLIWResourceModel::~VLIWResourceModel () inline
Definition at line 64 of file HexagonMachineScheduler.h.
Member Function Documentation
getTotalPackets()
unsigned llvm::VLIWResourceModel::getTotalPackets () const inline
Definition at line 83 of file HexagonMachineScheduler.h.
isInPacket()
bool llvm::VLIWResourceModel::isInPacket (SUnit * SU) const inline
Definition at line 84 of file HexagonMachineScheduler.h.
References llvm::is_contained().
isResourceAvailable()
bool VLIWResourceModel::isResourceAvailable (SUnit * SU, bool IsTop)
Check if scheduling of this SU is possible in the current packet.
It is not precise (statefull), it is more like another heuristic. Many corner cases are figured empirically.
Definition at line 97 of file HexagonMachineScheduler.cpp.
References llvm::DFAPacketizer::canReserveResources(), llvm::numbers::e, llvm::SUnit::getInstr(), llvm::HexagonSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getSubtarget(), hasDependence(), llvm::ISD::INLINEASM, and llvm::ISD::INLINEASM_BR.
Referenced by reserveResources(), and reset().
reserveResources()
bool VLIWResourceModel::reserveResources (SUnit * SU, bool IsTop)
Keep track of available resources.
Definition at line 138 of file HexagonMachineScheduler.cpp.
References llvm::DFAPacketizer::clearResources(), llvm::dbgs(), llvm::dump(), llvm::numbers::e, llvm::ISD::EH_LABEL, llvm::SUnit::getInstr(), llvm::TargetSchedModel::getIssueWidth(), llvm::MachineInstr::getOpcode(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, isResourceAvailable(), llvm::AMDGPUISD::KILL, LLVM_DEBUG, and llvm::DFAPacketizer::reserveResources().
Referenced by reset().
reset()
void llvm::VLIWResourceModel::reset () inline
Definition at line 76 of file HexagonMachineScheduler.h.
References llvm::DFAPacketizer::clearResources(), isResourceAvailable(), and reserveResources().
resetDFA()
void llvm::VLIWResourceModel::resetDFA () inline
Definition at line 72 of file HexagonMachineScheduler.h.
References llvm::DFAPacketizer::clearResources().
resetPacketState()
void llvm::VLIWResourceModel::resetPacketState () inline
Definition at line 68 of file HexagonMachineScheduler.h.
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonMachineScheduler.h
lib/Target/Hexagon/HexagonMachineScheduler.cpp