LLVM: llvm::MachO::TextAPIReader Class Reference
llvm::MachO::TextAPIReader Class Reference
#include "llvm/TextAPI/MachO/TextAPIReader.h"
Public Member Functions
TextAPIReader ()=delete
Static Public Member Functions
static Expected< std::unique_ptr< InterfaceFile > > get (MemoryBufferRef InputBuffer)
Detailed Description
Definition at line 20 of file TextAPIReader.h.
Constructor & Destructor Documentation
TextAPIReader()
llvm::MachO::TextAPIReader::TextAPIReader () delete
Member Function Documentation
get()
Expected< std::unique_ptr< InterfaceFile > > llvm::MachO::TextAPIReader::get (MemoryBufferRef InputBuffer) static
Definition at line 1108 of file TextStub.cpp.
References llvm::MachO::DiagHandler(), llvm::MachO::TextAPIContext::ErrorMessage, File, llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferIdentifier(), and llvm::MachO::TextAPIContext::Path.
The documentation for this class was generated from the following files:
include/llvm/TextAPI/MachO/TextAPIReader.h
lib/TextAPI/MachO/TextStub.cpp