LLVM: llvm::GCNIterativeScheduler::OverrideLegacyStrategy Class Reference
llvm::GCNIterativeScheduler::OverrideLegacyStrategy Class Reference
Public Member Functions
OverrideLegacyStrategy (Region &R, MachineSchedStrategy &OverrideStrategy, GCNIterativeScheduler &_Sch)
~OverrideLegacyStrategy ()
void schedule ()
void restoreOrder ()
Detailed Description
Definition at line 174 of file GCNIterativeScheduler.cpp.
Constructor & Destructor Documentation
OverrideLegacyStrategy()
llvm::GCNIterativeScheduler::OverrideLegacyStrategy::OverrideLegacyStrategy (Region & R, MachineSchedStrategy & OverrideStrategy, GCNIterativeScheduler & _Sch) inline
Definition at line 181 of file GCNIterativeScheduler.cpp.
References llvm::ScheduleDAGInstrs::BB, llvm::GCNIterativeScheduler::Region::Begin, llvm::GCNIterativeScheduler::Region::End, llvm::GCNIterativeScheduler::Region::NumRegionInstrs, and llvm::ScheduleDAGMI::SchedImpl.
~OverrideLegacyStrategy()
llvm::GCNIterativeScheduler::OverrideLegacyStrategy::~OverrideLegacyStrategy () inline
Definition at line 194 of file GCNIterativeScheduler.cpp.
References llvm::ScheduleDAGMI::SchedImpl.
Member Function Documentation
restoreOrder()
void llvm::GCNIterativeScheduler::OverrideLegacyStrategy::restoreOrder () inline
Definition at line 214 of file GCNIterativeScheduler.cpp.
References assert(), llvm::GCNIterativeScheduler::Region::Begin, llvm::GCNIterativeScheduler::Region::End, initialize(), llvm::ScheduleDAGInstrs::RegionBegin, llvm::ScheduleDAGInstrs::RegionEnd, llvm::GCNIterativeScheduler::scheduleRegion(), and llvm::ScheduleDAG::SUnits.
Referenced by llvm::GCNIterativeScheduler::scheduleLegacyMaxOccupancy().
schedule()
void llvm::GCNIterativeScheduler::OverrideLegacyStrategy::schedule () inline
Definition at line 201 of file GCNIterativeScheduler.cpp.
References assert(), llvm::GCNIterativeScheduler::Region::Begin, llvm::GCNRegPressure::clear(), llvm::dbgs(), llvm::GCNIterativeScheduler::Region::End, llvm::ScheduleDAGMI::LIS, LLVM_DEBUG, llvm::GCNIterativeScheduler::Region::MaxPressure, printRegion(), llvm::ScheduleDAGInstrs::RegionBegin, and llvm::ScheduleDAGInstrs::RegionEnd.
Referenced by llvm::GCNIterativeScheduler::scheduleLegacyMaxOccupancy().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/GCNIterativeScheduler.cpp