LLVM: llvm::SITargetLowering Class Reference
llvm::SITargetLowering Class Reference final
#include "Target/AMDGPU/SIISelLowering.h"
Public Member Functions
MVT getRegisterTypeForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const override
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
unsigned getNumRegistersForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const override
Certain targets require unusual breakdowns of certain types.
unsigned getVectorTypeBreakdownForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const override
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
bool shouldEmitFixup (const GlobalValue *GV) const
bool shouldEmitGOTReloc (const GlobalValue *GV) const
bool shouldEmitPCReloc (const GlobalValue *GV) const
SITargetLowering (const TargetMachine &tm, const GCNSubtarget &STI)
const GCNSubtarget * getSubtarget () const
bool isFPExtFoldable (const SelectionDAG &DAG, unsigned Opcode, EVT DestVT, EVT SrcVT) const override
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
bool isShuffleMaskLegal (ArrayRef< int >, EVT) const override
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, MachineFunction &MF, unsigned IntrinsicID) const override
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
bool getAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value *> &, Type *&) const override
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
bool isLegalGlobalAddressingMode (const AddrMode &AM) const
bool isLegalAddressingMode (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AS, Instruction *I=nullptr) const override
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool canMergeStoresTo (unsigned AS, EVT MemVT, const SelectionDAG &DAG) const override
Returns if it's reasonable to merge stores to MemVT size.
bool allowsMisalignedMemoryAccessesImpl (unsigned Size, unsigned AS, unsigned Align, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *IsFast=nullptr) const
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AS, unsigned Align, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *IsFast=nullptr) const override
Determine if the target supports unaligned memory accesses.
EVT getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, const AttributeList &FuncAttributes) const override
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
bool isMemOpUniform (const SDNode *N) const
bool isMemOpHasNoClobberedMemOperand (const SDNode *N) const
bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast between SrcAS and DestAS is a noop.
bool isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (MVT VT) const override
Return the preferred vector type legalization action.
bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const override
Return true if it is beneficial to convert a load of a constant to just the constant itself.
bool isTypeDesirableForOp (unsigned Op, EVT VT) const override
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const override
Return true if folding a constant offset with the given GlobalAddress is legal.
bool supportSplitCSR (MachineFunction *MF) const override
Return true if the target supports that a subset of CSRs for the given machine function is handled explicitly via copies.
void initializeSplitCSR (MachineBasicBlock *Entry) const override
Perform necessary initialization to handle a subset of CSRs explicitly via copies.
void insertCopiesSplitCSR (MachineBasicBlock *Entry, const SmallVectorImpl< MachineBasicBlock *> &Exits) const override
Insert explicit copies in entry and exit blocks.
SDValue LowerFormalArguments (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, const SDLoc &DL, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
bool CanLowerReturn (CallingConv::ID CallConv, MachineFunction &MF, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, LLVMContext &Context) const override
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers.
SDValue LowerReturn (SDValue Chain, CallingConv::ID CallConv, bool IsVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SDLoc &DL, SelectionDAG &DAG) const override
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
void passSpecialInputs (CallLoweringInfo &CLI, CCState &CCInfo, const SIMachineFunctionInfo &Info, SmallVectorImpl< std::pair< unsigned, SDValue >> &RegsToPass, SmallVectorImpl< SDValue > &MemOpChains, SDValue Chain) const
SDValue LowerCallResult (SDValue Chain, SDValue InFlag, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, const SDLoc &DL, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals, bool isThisReturn, SDValue ThisVal) const
bool mayBeEmittedAsTailCall (const CallInst *) const override
Return true if the target may be able emit the call instruction as a tail call.
bool isEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SmallVectorImpl< ISD::InputArg > &Ins, SelectionDAG &DAG) const
SDValue LowerCall (CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower calls into the specified DAG.
Register getRegisterByName (const char *RegName, LLT VT, const MachineFunction &MF) const override
Return the register ID of the name passed in.
MachineBasicBlock * splitKillBlock (MachineInstr &MI, MachineBasicBlock *BB) const
void bundleInstWithWaitcnt (MachineInstr &MI) const
Insert MI into a BUNDLE with an S_WAITCNT 0 immediately following it.
MachineBasicBlock * emitGWSMemViolTestLoop (MachineInstr &MI, MachineBasicBlock *BB) const
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr &MI, MachineBasicBlock *BB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
bool hasBitPreservingFPLogic (EVT VT) const override
Return true if it is safe to transform an integer-domain bitwise operation into the equivalent floating-point operation.
bool enableAggressiveFMAFusion (EVT VT) const override
Return true if target always beneficiates from combining into FMA for a given value type.
EVT getSetCCResultType (const DataLayout &DL, LLVMContext &Context, EVT VT) const override
Return the ValueType of the result of SETCC operations.
MVT getScalarShiftAmountTy (const DataLayout &, EVT) const override
EVT is not used in-tree, but is used by out-of-tree target.
bool isFMAFasterThanFMulAndFAdd (const MachineFunction &MF, EVT VT) const override
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
bool isFMADLegalForFAddFSub (const SelectionDAG &DAG, const SDNode *N) const override
Returns true if the FADD or FSUB node passed could legally be combined with an fmul to form an ISD::FMAD.
SDValue splitUnaryVectorOp (SDValue Op, SelectionDAG &DAG) const
SDValue splitBinaryVectorOp (SDValue Op, SelectionDAG &DAG) const
SDValue splitTernaryVectorOp (SDValue Op, SelectionDAG &DAG) const
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
SDNode * PostISelFolding (MachineSDNode *N, SelectionDAG &DAG) const override
Fold the instructions after selecting them.
void AdjustInstrPostInstrSelection (MachineInstr &MI, SDNode *Node) const override
Assign the register class depending on the number of bits set in the writemask.
SDNode * legalizeTargetIndependentNode (SDNode *Node, SelectionDAG &DAG) const
Legalize target independent instructions (e.g.
MachineSDNode * wrapAddr64Rsrc (SelectionDAG &DAG, const SDLoc &DL, SDValue Ptr) const
MachineSDNode * buildRSRC (SelectionDAG &DAG, const SDLoc &DL, SDValue Ptr, uint32_t RsrcDword1, uint64_t RsrcDword2And3) const
Return a resource descriptor with the 'Add TID' bit enabled The TID (Thread ID) is multiplied by the stride value (bits [61:48] of the resource descriptor) to create an offset, which is added to the resource pointer.
std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, StringRef Constraint, MVT VT) const override
Given a physical register constraint (e.g.
ConstraintType getConstraintType (StringRef Constraint) const override
Given a constraint, return the type of constraint it is for this target.
SDValue copyToM0 (SelectionDAG &DAG, SDValue Chain, const SDLoc &DL, SDValue V) const
void finalizeLowering (MachineFunction &MF) const override
Execute target specific actions to finalize target lowering.
void computeKnownBitsForFrameIndex (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const override
Determine which of the bits of FrameIndex FIOp are known to be 0.
bool isSDNodeSourceOfDivergence (const SDNode *N, FunctionLoweringInfo *FLI, LegacyDivergenceAnalysis *DA) const override
bool isCanonicalized (SelectionDAG &DAG, SDValue Op, unsigned MaxDepth=5) const
bool denormalsEnabledForType (const SelectionDAG &DAG, EVT VT) const
bool isKnownNeverNaNForTargetNode (SDValue Op, const SelectionDAG &DAG, bool SNaN=false, unsigned Depth=0) const override
If SNaN is false,.
AtomicExpansionKind shouldExpandAtomicRMWInIR (AtomicRMWInst *) const override
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
virtual const TargetRegisterClass * getRegClassFor (MVT VT, bool isDivergent) const override
Return the register class that should be used for the specified value type.
virtual bool requiresUniformRegister (MachineFunction &MF, const Value *V) const override
Allows target to decide about the register class of the specific value that is live outside the defining block.
Align getPrefLoopAlignment (MachineLoop *ML) const override
Return the preferred loop alignment.
void allocateHSAUserSGPRs (CCState &CCInfo, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info) const
void allocateSystemSGPRs (CCState &CCInfo, MachineFunction &MF, SIMachineFunctionInfo &Info, CallingConv::ID CallConv, bool IsShader) const
void allocateSpecialEntryInputVGPRs (CCState &CCInfo, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info) const
void allocateSpecialInputSGPRs (CCState &CCInfo, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info) const
void allocateSpecialInputVGPRs (CCState &CCInfo, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info) const
Public Member Functions inherited from llvm::AMDGPUTargetLowering
AMDGPUTargetLowering (const TargetMachine &TM, const AMDGPUSubtarget &STI)
bool mayIgnoreSignedZero (SDValue Op) const
bool isFAbsFree (EVT VT) const override
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
bool isFNegFree (EVT VT) const override
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
bool isTruncateFree (EVT Src, EVT Dest) const override
bool isTruncateFree (Type *Src, Type *Dest) const override
Return true if it's free to truncate a value of type FromTy to type ToTy.
bool isZExtFree (Type *Src, Type *Dest) const override
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
bool isZExtFree (EVT Src, EVT Dest) const override
bool isZExtFree (SDValue Val, EVT VT2) const override
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
bool isNarrowingProfitable (EVT VT1, EVT VT2) const override
Return true if it's profitable to narrow operations of type VT1 to VT2.
MVT getVectorIdxTy (const DataLayout &) const override
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
bool isSelectSupported (SelectSupportKind) const override
bool isFPImmLegal (const APFloat &Imm, EVT VT, bool ForCodeSize) const override
Returns true if the target can instruction select the specified FP immediate natively.
bool ShouldShrinkFPConstant (EVT VT) const override
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtType, EVT ExtVT) const override
Return true if it is profitable to reduce a load to a smaller type.
bool isLoadBitCastBeneficial (EVT, EVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const final
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
bool storeOfVectorConstantIsCheap (EVT MemVT, unsigned NumElem, unsigned AS) const override
Return true if it is expected to be cheaper to do a store of a non-zero vector constant with the given size and type for the address space than to store the individual scalar element constants.
bool aggressivelyPreferBuildVectorSources (EVT VecVT) const override
bool isCheapToSpeculateCttz () const override
Return true if it is cheap to speculate a call to intrinsic cttz.
bool isCheapToSpeculateCtlz () const override
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool isSDNodeAlwaysUniform (const SDNode *N) const override
SDValue addTokenForArgument (SDValue Chain, SelectionDAG &DAG, MachineFrameInfo &MFI, int ClobberedFI) const
SDValue lowerUnhandledCall (CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals, StringRef Reason) const
SDValue LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG &DAG) const
SDValue combineFMinMaxLegacy (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, SDValue True, SDValue False, SDValue CC, DAGCombinerInfo &DCI) const
Generate Min/Max node.
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
bool mergeStoresAfterLegalization (EVT) const override
Allow store merging for the specified type after legalization in addition to before legalization.
bool isFsqrtCheap (SDValue Operand, SelectionDAG &DAG) const override
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
SDValue getSqrtEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps, bool &UseOneConstNR, bool Reciprocal) const override
Hooks for building estimates in place of slower divisions and square roots.
SDValue getRecipEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps) const override
Return a reciprocal estimate value for the input operand.
void computeKnownBitsForTargetNode (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const override
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero and KnownOne bitsets.
unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const override
This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
SDValue CreateLiveInRegister (SelectionDAG &DAG, const TargetRegisterClass *RC, unsigned Reg, EVT VT, const SDLoc &SL, bool RawReg=false) const
Helper function that adds Reg to the LiveIn list of the DAG's MachineFunction.
SDValue CreateLiveInRegister (SelectionDAG &DAG, const TargetRegisterClass *RC, unsigned Reg, EVT VT) const
SDValue CreateLiveInRegisterRaw (SelectionDAG &DAG, const TargetRegisterClass *RC, unsigned Reg, EVT VT) const
SDValue loadStackInputValue (SelectionDAG &DAG, EVT VT, const SDLoc &SL, int64_t Offset) const
Similar to CreateLiveInRegister, except value maybe loaded from a stack slot rather than passed in a register.
SDValue storeStackInputValue (SelectionDAG &DAG, const SDLoc &SL, SDValue Chain, SDValue ArgVal, int64_t Offset) const
SDValue loadInputValue (SelectionDAG &DAG, const TargetRegisterClass *RC, EVT VT, const SDLoc &SL, const ArgDescriptor &Arg) const
uint32_t getImplicitParameterOffset (const MachineFunction &MF, const ImplicitParameter Param) const
Helper function that returns the byte offset of the given type of implicit parameter.
MVT getFenceOperandTy (const DataLayout &DL) const override
Return the type for operands of fence.
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetLowering &)=delete
TargetLowering & operator= (const TargetLowering &)=delete
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
bool isPositionIndependent () const
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
virtual bool isIndexingLegal (MachineInstr &MI, Register Base, Register Offset, bool IsPre, MachineRegisterInfo &MRI) const
Returns true if the specified base+offset is a legal indexed addressing mode for this target.
virtual unsigned getJumpTableEncoding () const
Return the entry encoding for a jump table in the current function.
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
Check whether a given call node is in tail position within its function.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS) const
Soften the operands of a comparison.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS, SDValue &Chain, bool IsSignaling=false) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, ArrayRef< SDValue > Ops, MakeLibCallOptions CallOptions, const SDLoc &dl, SDValue Chain=SDValue()) const
Returns a pair of (return value, chain).
bool parametersInCSRMatch (const MachineRegisterInfo &MRI, const uint32_t *CallerPreservedMask, const SmallVectorImpl< CCValAssign > &ArgLocs, const SmallVectorImpl< SDValue > &OutVals) const
Check whether parameters to a call that are passed in callee saved registers are the same as from the calling function.
bool findOptimalMemOpLowering (std::vector< EVT > &MemOps, unsigned Limit, uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, bool AllowOverlap, unsigned DstAS, unsigned SrcAS, const AttributeList &FuncAttributes) const
Determines the optimal series of memory ops to replace the memset / memcpy.
bool ShrinkDemandedConstant (SDValue Op, const APInt &Demanded, TargetLoweringOpt &TLO) const
Check to see if the specified operand of the specified instruction is a constant integer.
virtual bool targetShrinkDemandedConstant (SDValue Op, const APInt &Demanded, TargetLoweringOpt &TLO) const
bool ShrinkDemandedOp (SDValue Op, unsigned BitWidth, const APInt &Demanded, TargetLoweringOpt &TLO) const
Convert x+y to (VT)((SmallVT)x+(SmallVT)y) if the casts are free.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Op.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Helper wrapper around SimplifyDemandedBits, demanding all elements.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedMask, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedBits.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedEltMask, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Vector Op.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedVectorElts.
virtual void computeKnownBitsForTargetInstr (GISelKnownBits &Analysis, Register R, KnownBits &Known, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
virtual bool SimplifyDemandedVectorEltsForTargetNode (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded vector elements, returning true on success.
virtual bool SimplifyDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded bits/elts, returning true on success.
virtual SDValue SimplifyMultipleUseDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
SDValue buildLegalVectorShuffle (EVT VT, const SDLoc &DL, SDValue N0, SDValue N1, MutableArrayRef< int > Mask, SelectionDAG &DAG) const
Tries to build a legal vector shuffle using the provided parameters or equivalent variations.
virtual const Constant * getTargetConstantFromLoad (LoadSDNode *LD) const
This method returns the constant pool value that will be loaded by LD.
bool isConstTrueVal (const SDNode *N) const
Return if the N is a constant or constant vector equal to the true value from getBooleanContents().
bool isConstFalseVal (const SDNode *N) const
Return if the N is a constant or constant vector equal to the false value from getBooleanContents().
bool isExtendedTrueVal (const ConstantSDNode *N, EVT VT, bool SExt) const
Return if N is a True value when extended to VT.
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, const SDLoc &dl) const
Try to simplify a setcc built with the specified operands and cc.
virtual SDValue unwrapAddress (SDValue N) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
virtual bool isDesirableToCommuteWithShift (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to move this shift by a constant amount though its operand, adjusting any immediate operands as necessary to preserve semantics.
virtual bool isDesirableToCombineBuildVectorToShuffleTruncate (ArrayRef< int > ShuffleMask, EVT SrcVT, EVT TruncVT) const
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
Return true if it is profitable for dag combiner to transform a floating point op of specified opcode to a equivalent op of an integer type.
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
This method query the target whether it is beneficial for dag combiner to promote the specified node.
virtual bool supportSwiftError () const
Return true if the target supports swifterror attribute.
virtual char isNegatibleForFree (SDValue Op, SelectionDAG &DAG, bool LegalOperations, bool ForCodeSize, unsigned Depth=0) const
Return 1 if we can compute the negated form of the specified expression for the same cost as the expression itself, or 2 if we can compute the negated form more cheaply than the expression itself.
virtual SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOperations, bool ForCodeSize, unsigned Depth=0) const
If isNegatibleForFree returns true, return the newly negated expression.
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
This function lowers an abstract call to a function into an actual call.
virtual void HandleByVal (CCState *, unsigned &, unsigned) const
Target-specific cleanup for formal ByVal parameters.
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
Return true if result of the specified node is used by a return node only.
virtual const char * getClearCacheBuiltinName () const
Return the builtin name for the __builtin___clear_cache intrinsic Default is to invoke the clear cache library call.
virtual EVT getTypeForExtReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
Return the type that should be used to zero or sign extend a zeroext/signext integer return value.
virtual bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg) const
For some targets, an LLVM struct type must be broken down into multiple simple types, but the calling convention specifies that the entire struct must be passed in a block of consecutive registers.
virtual bool shouldSplitFunctionArgumentsAsLittleEndian (const DataLayout &DL) const
For most targets, an LLVM type must be broken down into multiple smaller types.
virtual const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const
Returns a 0 terminated array of registers that can be safely used as scratch registers.
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, const SDLoc &DL, SelectionDAG &DAG) const
This callback is used to prepare for a volatile or atomic load.
virtual MachineMemOperand::Flags getMMOFlags (const Instruction &I) const
This callback is used to inspect load/store instructions and add target-specific MachineMemOperand flags to them.
virtual bool lowerAtomicStoreAsStoreSDNode (const StoreInst &SI) const
Should SelectionDAG lower an atomic store of the given kind as a normal StoreSDNode (as opposed to an AtomicSDNode)? NOTE: The intention is to eventually migrate all targets to the using StoreSDNodes, but porting is being done target at a time.
virtual bool lowerAtomicLoadAsLoadSDNode (const LoadInst &LI) const
Should SelectionDAG lower an atomic load of the given kind as a normal LoadSDNode (as opposed to an AtomicSDNode)? NOTE: The intention is to eventually migrate all targets to the using LoadSDNodes, but porting is being done target at a time.
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types.
virtual FastISel * createFastISel (FunctionLoweringInfo &, const TargetLibraryInfo *) const
This method returns a target specific FastISel object, or null if the target does not support "fast" ISel.
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to.
virtual AsmOperandInfoVector ParseConstraints (const DataLayout &DL, const TargetRegisterInfo *TRI, ImmutableCallSite CS) const
Split up the constraint string from the inline assembly value into the specific constraints and their prefixes, and also tie in the associated operand values.
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
Examine constraint type and operand type and determine a weight value.
virtual ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const
Examine constraint string and operand type and determine a weight value.
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
Determines the constraint code and constraint type to use for the specific AsmOperandInfo, setting OpInfo.ConstraintCode and OpInfo.ConstraintType.
virtual unsigned getInlineAsmMemConstraint (StringRef ConstraintCode) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
virtual void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const
Lower the specified operand into the Ops vector.
virtual SDValue LowerAsmOutputForConstraint (SDValue &Chain, SDValue &Flag, SDLoc DL, const AsmOperandInfo &OpInfo, SelectionDAG &DAG) const
SDValue BuildSDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode *> &Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
SDValue BuildUDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode *> &Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
virtual SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode *> &Created) const
Targets may override this function to provide custom SDIV lowering for power-of-2 denominators.
virtual unsigned combineRepeatedFPDivisors () const
Indicate whether this target prefers to combine FDIVs with the same divisor.
bool expandMUL_LOHI (unsigned Opcode, EVT VT, SDLoc dl, SDValue LHS, SDValue RHS, SmallVectorImpl< SDValue > &Result, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL or [US]MUL_LOHI of n-bit values into two or four nodes, respectively, each computing an n/2-bit part of the result.
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL into two nodes.
bool expandFunnelShift (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand funnel shift.
bool expandROT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand rotations.
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand float(f32) to SINT(i64) conversion.
bool expandFP_TO_UINT (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand float to UINT conversion.
bool expandUINT_TO_FP (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand UINT(i64) to double(f64) conversion.
SDValue expandFMINNUM_FMAXNUM (SDNode *N, SelectionDAG &DAG) const
Expand fminnum/fmaxnum into fminnum_ieee/fmaxnum_ieee with quieted inputs.
bool expandCTPOP (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTPOP nodes.
bool expandCTLZ (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTLZ/CTLZ_ZERO_UNDEF nodes.
bool expandCTTZ (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTTZ/CTTZ_ZERO_UNDEF nodes.
bool expandABS (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand ABS nodes.
std::pair< SDValue, SDValue > scalarizeVectorLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Turn load of vector type into a load of the individual elements.
SDValue scalarizeVectorStore (StoreSDNode *ST, SelectionDAG &DAG) const
std::pair< SDValue, SDValue > expandUnalignedLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Expands an unaligned load to 2 half-size loads for an integer, and possibly more for vectors.
SDValue expandUnalignedStore (StoreSDNode *ST, SelectionDAG &DAG) const
Expands an unaligned store to 2 half-size stores for integer values, and possibly more for vectors.
SDValue IncrementMemoryAddress (SDValue Addr, SDValue Mask, const SDLoc &DL, EVT DataVT, SelectionDAG &DAG, bool IsCompressedMemory) const
Increments memory address Addr according to the type of the value DataVT that should be stored.
SDValue getVectorElementPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, SDValue Index) const
Get a pointer to vector element Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue expandAddSubSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][ADD|SUB]SAT.
SDValue expandFixedPointMul (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[U|S]MULFIX[SAT].
SDValue expandFixedPointDiv (unsigned Opcode, const SDLoc &dl, SDValue LHS, SDValue RHS, unsigned Scale, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]DIVFIX.
void expandUADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::U(ADD|SUB)O.
void expandSADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::S(ADD|SUB)O.
bool expandMULO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]MULO.
SDValue expandVecReduce (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_* into an explicit calculation.
virtual bool useLoadStackGuardNode () const
If this function returns true, SelectionDAGBuilder emits a LOAD_STACK_GUARD node when it is lowering Intrinsic::stackprotector.
virtual SDValue emitStackGuardXorFP (SelectionDAG &DAG, SDValue Val, const SDLoc &DL) const
virtual SDValue LowerToTLSEmulatedModel (const GlobalAddressSDNode *GA, SelectionDAG &DAG) const
Lower TLS global address SDNode for target independent emulated TLS model.
virtual SDValue expandIndirectJTBranch (const SDLoc &dl, SDValue Value, SDValue Addr, SelectionDAG &DAG) const
Expands target specific indirect branch for the case of JumpTable expanasion.
SDValue lowerCmpEqZeroToCtlzSrl (SDValue Op, SelectionDAG &DAG) const
Public Member Functions inherited from llvm::TargetLoweringBase
virtual void markLibCallAttributes (MachineFunction *MF, unsigned CC, ArgListTy &Args) const
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
TargetLoweringBase (const TargetLoweringBase &)=delete
TargetLoweringBase & operator= (const TargetLoweringBase &)=delete
virtual ~TargetLoweringBase ()=default
bool isStrictFPEnabled () const
Return true if the target support strict float operation.
const TargetMachine & getTargetMachine () const
virtual bool useSoftFloat () const
virtual MVT getPointerTy (const DataLayout &DL, uint32_t AS=0) const
Return the pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getPointerMemTy (const DataLayout &DL, uint32_t AS=0) const
Return the in-memory pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getFrameIndexTy (const DataLayout &DL) const
Return the type for frame index, which is determined by the alloca address space specified through the data layout.
EVT getShiftAmountTy (EVT LHSTy, const DataLayout &DL, bool LegalTypes=true) const
virtual bool reduceSelectOfFPConstantLoads (EVT CmpOpVT) const
Return true if it is profitable to convert a select of FP constants into a constant pool load whose address depends on the select condition.
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
virtual bool isIntDivCheap (EVT VT, AttributeList Attr) const
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
virtual bool hasStandaloneRem (EVT VT) const
Return true if the target can handle a standalone remainder operation.
int getRecipEstimateSqrtEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a square root of the given type based on the function's attributes.
int getRecipEstimateDivEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a division of the given type based on the function's attributes.
int getSqrtRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a square root of the given type based on the function's attributes.
int getDivRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a division of the given type based on the function's attributes.
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
Returns map of slow types for division or remainder with corresponding fast types.
bool isJumpExpensive () const
Return true if Flow Control is an expensive operation that should be avoided.
bool isPredictableSelectExpensive () const
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
virtual BranchProbability getPredictableBranchThreshold () const
If a branch or a select condition is skewed in one direction by more than this factor, it is very likely to be predicted correctly.
virtual bool isStoreBitCastBeneficial (EVT StoreVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: (store (y (conv x)), y*)) -> (store x, (x*))
virtual bool isCtlzFast () const
Return true if ctlz instruction is fast.
virtual bool isEqualityCmpFoldedWithSignedCmp () const
Return true if instruction generated for equality comparison is folded with instruction generated for signed comparison.
virtual bool isMultiStoresCheaperThanBitsMerge (EVT LTy, EVT HTy) const
Return true if it is cheaper to split the store of a merged int val from a pair of smaller values into multiple stores.
virtual bool isMaskAndCmp0FoldingBeneficial (const Instruction &AndI) const
Return if the target supports combining a chain like:
virtual bool convertSetCCLogicToBitwiseLogic (EVT VT) const
Use bitwise logic to make pairs of compares more efficient.
virtual MVT hasFastEqualityCompare (unsigned NumBits) const
Return the preferred operand type if the target has a quick way to compare integer values of the given size.
virtual bool hasAndNotCompare (SDValue Y) const
Return true if the target should transform: (X & Y) == Y —> (~X & Y) == 0 (X & Y) != Y —> (~X & Y) != 0.
virtual bool hasAndNot (SDValue X) const
Return true if the target has a bitwise and-not operation: X = ~A & B This can be used to simplify select or other instructions.
virtual bool hasBitTest (SDValue X, SDValue Y) const
Return true if the target has a bit-test instruction: (X & (1 << Y)) ==/!= 0 This knowledge can be used to prevent breaking the pattern, or creating it if it could be recognized.
virtual bool shouldFoldMaskToVariableShiftPair (SDValue X) const
There are two ways to clear extreme bits (either low or high): Mask: x & (-1 << y) (the instcombine canonical form) Shifts: x >> y << y Return true if the variant with 2 variable shifts is preferred.
virtual bool shouldFoldConstantShiftPairToMask (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to fold a pair of shifts into a mask.
virtual bool shouldTransformSignedTruncationCheck (EVT XVT, unsigned KeptBits) const
Should we tranform the IR-optimal check for whether given truncation down into KeptBits would be truncating or not: (add x, (1 << (KeptBits-1))) srccond (1 << KeptBits) Into it's more traditional form: ((x << C) a>> C) dstcond x Return true if we should transform.
virtual bool shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd (SDValue X, ConstantSDNode *XC, ConstantSDNode *CC, SDValue Y, unsigned OldShiftOpcode, unsigned NewShiftOpcode, SelectionDAG &DAG) const
Given the pattern (X & (C l>>/<< Y)) ==/!= 0 return true if it should be transformed into: ((X <</l>> Y) & C) ==/!= 0 WARNING: if 'X' is a constant, the fold may deadlock! FIXME: we could avoid passing XC, but we can't use isConstOrConstSplat() here because it can end up being not linked in.
virtual bool preferIncOfAddToSubOfNot (EVT VT) const
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
Return true if the target can combine store(extractelement VectorTy, Idx).
virtual bool shouldSplatInsEltVarIndex (EVT) const
Return true if inserting a scalar into a variable element of an undef vector is more efficiently handled by splatting the scalar instead.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
Return the ValueType for comparison libcalls.
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
Some scheduler, e.g.
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
Return the 'representative' register class for the specified value type.
virtual uint8_t getRepRegClassCostFor (MVT VT) const
Return the cost of the 'representative' register class for the specified value type.
virtual bool shouldExpandShift (SelectionDAG &DAG, SDNode *N) const
Return true if SHIFT instructions should be expanded to SHIFT_PARTS instructions, and false if a library call is preferred (e.g for code-size reasons).
bool isTypeLegal (EVT VT) const
Return true if the target has native support for the specified value type.
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand').
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Vector types are broken down into some number of legal first class types.
virtual bool canOpTrap (unsigned Op, EVT VT) const
Returns true if the operation can trap for the value type.
virtual bool isVectorClearMaskLegal (ArrayRef< int >, EVT) const
Similar to isShuffleMaskLegal.
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
virtual bool isSupportedFixedPointOperation (unsigned Op, EVT VT, unsigned Scale) const
Custom method defined by each target to indicate if an operation which may require a scale is supported natively by the target.
LegalizeAction getFixedPointOperationAction (unsigned Op, EVT VT, unsigned Scale) const
Some fixed point operations may be natively supported by the target but only for specific scales.
LegalizeAction getStrictFPOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering.
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal using promotion.
bool isOperationLegalOrCustomOrPromote (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering or using promotion.
bool isOperationCustom (unsigned Op, EVT VT) const
Return true if the operation uses custom lowering, regardless of whether the type is legal or not.
virtual bool areJTsAllowed (const Function *Fn) const
Return true if lowering to a jump table is allowed.
bool rangeFitsInWord (const APInt &Low, const APInt &High, const DataLayout &DL) const
Check whether the range [Low,High] fits in a machine word.
virtual bool isSuitableForJumpTable (const SwitchInst *SI, uint64_t NumCases, uint64_t Range, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
Return true if lowering to a jump table is suitable for a set of case clusters which may contain NumCases cases, Range range of values.
bool isSuitableForBitTests (unsigned NumDests, unsigned NumCmps, const APInt &Low, const APInt &High, const DataLayout &DL) const
Return true if lowering to a bit test is suitable for a set of case clusters which contains NumDests unique destinations, Low and High as its lowest and highest case values, and expects NumCmps case value comparisons.
bool isOperationExpand (unsigned Op, EVT VT) const
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering.
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
bool isLoadExtLegalOrCustom (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal or custom on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation is legal on this target.
bool isTruncStoreLegalOrCustom (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation has solution on this target.
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
bool isCondCodeLegalOrCustom (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal or custom on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
If the action for this operation is to promote, this method returns the ValueType to promote to.
EVT getValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the EVT corresponding to this LLVM type.
EVT getMemValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty, const DataLayout &DL) const
Return the desired alignment for ByVal or InAlloca aggregate function arguments in the caller parameter area.
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
Return the number of registers that this ValueType will eventually require.
virtual Align getABIAlignmentForCallingConv (Type *ArgTy, DataLayout DL) const
Certain targets have context senstive alignment requirements, where one type has the alignment requirement of another type.
bool hasBigEndianPartOrdering (EVT VT, const DataLayout &DL) const
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
bool hasTargetDAGCombine (ISD::NodeType NT) const
If true, the target has custom DAG combine transformations that it can perform for the specified node.
unsigned getGatherAllAliasesMaxDepth () const
virtual unsigned getVaListSizeInBits (const DataLayout &DL) const
Returns the size of the platform's va_list object.
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
virtual unsigned getMaxGluedStoresPerMemcpy () const
Get maximum # of store operations to be glued together.
unsigned getMaxExpandSizeMemcmp (bool OptSize) const
Get maximum # of load operations permitted for memcmp.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (LLT, unsigned AddrSpace=0, unsigned Align=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *=nullptr) const
LLT handling variant.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, unsigned Alignment=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *Fast=nullptr) const
This function returns true if the memory access is aligned or if the target allows this specific unaligned memory access.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, bool *Fast=nullptr) const
Return true if the memory access of this type is aligned or if the target allows this specific unaligned access for the given MachineMemOperand.
virtual bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, unsigned Alignment=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given address space and alignment.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given MachineMemOperand.
virtual LLT getOptimalMemOpLLT (uint64_t, unsigned, unsigned, bool, bool, bool, const AttributeList &) const
LLT returning variant.
virtual bool isSafeMemOpType (MVT) const
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
virtual unsigned getMinimumJumpTableEntries () const
Return lower limit for number of blocks in a jump table.
unsigned getMinimumJumpTableDensity (bool OptForSize) const
Return lower limit of the density in a jump table.
unsigned getMaximumJumpTableSize () const
Return upper limit for number of entries in a jump table.
virtual bool isJumpTableRelative () const
unsigned getStackPointerRegisterToSaveRestore () const
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
virtual unsigned getExceptionPointerRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
virtual unsigned getExceptionSelectorRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
virtual bool needsFixedCatchObjects () const
Align getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
Align getMinFunctionAlignment () const
Return the minimum function alignment.
Align getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual bool alignLoopsWithOptSize () const
Should loops be aligned even when the function is marked OptSize (but not MinSize).
virtual Value * getIRStackGuard (IRBuilder<> &IRB) const
If the target has a standard location for the stack protector guard, returns the address of that location.
virtual void insertSSPDeclarations (Module &M) const
Inserts necessary declarations for SSP (stack protection) purpose.
virtual Value * getSDagStackGuard (const Module &M) const
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
virtual bool useStackGuardXorFP () const
If this function returns true, stack protection checks should XOR the frame pointer (or whichever pointer is used to address locals) into the stack guard value before checking it.
virtual Function * getSSPStackGuardCheck (const Module &M) const
If the target has a standard stack protection check function that performs validation and error handling, returns the function.
virtual Value * getSafeStackPointerLocation (IRBuilder<> &IRB) const
Returns the target-specific address of the unsafe stack pointer.
virtual StringRef getStackProbeSymbolName (MachineFunction &MF) const
Returns the name of the symbol used to emit stack probes or the empty string if not applicable.
virtual bool shouldAlignPointerArgs (CallInst *, unsigned &, unsigned &) const
Return true if the pointer arguments to CI should be aligned by aligning the object whose address is being passed.
virtual void emitAtomicCmpXchgNoStoreLLBalance (IRBuilder<> &Builder) const
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
Returns true if the given (atomic) store should be expanded by the IR-level AtomicExpand pass into an "atomic xchg" which ignores its input.
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
virtual bool shouldExtendTypeInLibCall (EVT Type) const
Returns true if arguments should be extended in lib calls.
virtual AtomicExpansionKind shouldExpandAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst *AI) const
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load.
virtual ISD::NodeType getExtendForAtomicOps () const
Returns how the platform's atomic operations are extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual bool shouldNormalizeToSelectSequence (LLVMContext &Context, EVT VT) const
Returns true if we should normalize select(N0&N1, X, Y) => select(N0, select(N1, X, Y), Y) and select(N0|N1, X, Y) => select(N0, select(N1, X, Y, Y)) if it is likely that it saves us from materializing N0 and N1 in an integer register.
virtual bool isProfitableToCombineMinNumMaxNum (EVT VT) const
virtual bool convertSelectOfConstantsToMath (EVT VT) const
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
virtual bool decomposeMulByConstant (LLVMContext &Context, EVT VT, SDValue C) const
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
virtual bool shouldUseStrictFP_TO_INT (EVT FpVT, EVT IntVT, bool IsSigned) const
Return true if it is more correct/profitable to use strict FP_TO_INT conversion operations - canonicalizing the FP source value instead of converting all cases and then selecting based on value.
virtual int getScalingFactorCost (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AS=0) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
virtual bool isLegalAddImmediate (int64_t) const
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
virtual bool isLegalStoreImmediate (int64_t Value) const
Return true if the specified immediate is legal for the value input of a store instruction.
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
virtual bool isCommutativeBinOp (unsigned Opcode) const
Returns true if the opcode is a commutative binary operation.
virtual bool isBinOp (unsigned Opcode) const
Return true if the node is a math/logic binary operator.
virtual bool allowTruncateForTailCall (Type *FromTy, Type *ToTy) const
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
virtual bool isProfitableToHoist (Instruction *I) const
bool isExtFree (const Instruction *I) const
Return true if the extension represented by I is free.
bool isExtLoad (const LoadInst *Load, const Instruction *Ext, const DataLayout &DL) const
Return true if Load and Ext can form an ExtLoad.
virtual bool isSExtCheaperThanZExt (EVT FromTy, EVT ToTy) const
Return true if sign-extension from FromTy to ToTy is cheaper than zero-extension.
virtual bool shouldSinkOperands (Instruction *I, SmallVectorImpl< Use *> &Ops) const
Return true if sinking I's operands to the same basic block as I is profitable, e.g.
virtual bool hasPairedLoad (EVT, unsigned &) const
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory.
virtual bool hasVectorBlend () const
Return true if the target has a vector blend instruction.
virtual unsigned getMaxSupportedInterleaveFactor () const
Get the maximum supported factor for interleaved memory accesses.
virtual bool lowerInterleavedLoad (LoadInst *LI, ArrayRef< ShuffleVectorInst *> Shuffles, ArrayRef< unsigned > Indices, unsigned Factor) const
Lower an interleaved load to target specific intrinsics.
virtual bool lowerInterleavedStore (StoreInst *SI, ShuffleVectorInst *SVI, unsigned Factor) const
Lower an interleaved store to target specific intrinsics.
virtual bool isFPExtFree (EVT DestVT, EVT SrcVT) const
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
virtual bool isVectorLoadExtDesirable (SDValue ExtVal) const
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
virtual bool isFMAFasterThanFMulAndFAdd (const Function &F, Type *) const
IR version.
virtual bool isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
virtual bool shouldScalarizeBinop (SDValue VecOp) const
Try to convert an extract element of a vector binary operation into an extract element followed by a scalar operation.
virtual bool isExtractVecEltCheap (EVT VT, unsigned Index) const
Return true if extraction of a scalar element from the given vector type at the given index is cheap.
virtual bool shouldFormOverflowOp (unsigned Opcode, EVT VT) const
Try to convert math with an overflow comparison into the corresponding DAG node operation.
virtual bool shouldConsiderGEPOffsetSplit () const
virtual bool shouldAvoidTransformToShift (EVT VT, unsigned Amount) const
Return true if creating a shift of the type by the given amount is not profitable.
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
Override the default CondCode to be used to test the result of the comparison libcall against zero.
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< int, MVT > getTypeLegalizationCost (const DataLayout &DL, Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
unsigned getMaxAtomicSizeInBitsSupported () const
Returns the maximum atomic operation size (in bits) supported by the backend.
unsigned getMinCmpXchgSizeInBits () const
Returns the size of the smallest cmpxchg or ll/sc instruction the backend supports.
bool supportsUnalignedAtomics () const
Whether the target supports unaligned atomic operations.
virtual bool shouldInsertFencesForAtomic (const Instruction *I) const
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
Perform a store-conditional operation to Addr.
virtual Value * emitMaskedAtomicRMWIntrinsic (IRBuilder<> &Builder, AtomicRMWInst *AI, Value *AlignedAddr, Value *Incr, Value *Mask, Value *ShiftAmt, AtomicOrdering Ord) const
Perform a masked atomicrmw using a target-specific intrinsic.
virtual Value * emitMaskedAtomicCmpXchgIntrinsic (IRBuilder<> &Builder, AtomicCmpXchgInst *CI, Value *AlignedAddr, Value *CmpVal, Value *NewVal, Value *Mask, AtomicOrdering Ord) const
Perform a masked cmpxchg using a target-specific intrinsic.
virtual Instruction * emitLeadingFence (IRBuilder<> &Builder, Instruction *Inst, AtomicOrdering Ord) const
Inserts in the IR a target-specific intrinsic specifying a fence.
virtual Instruction * emitTrailingFence (IRBuilder<> &Builder, Instruction *Inst, AtomicOrdering Ord) const
Static Public Member Functions
static bool isFlatGlobalAddrSpace (unsigned AS)
Static Public Member Functions inherited from llvm::AMDGPUTargetLowering
static unsigned numBitsUnsigned (SDValue Op, SelectionDAG &DAG)
static unsigned numBitsSigned (SDValue Op, SelectionDAG &DAG)
static bool hasDefinedInitializer (const GlobalValue *GV)
static SDValue stripBitcast (SDValue Val)
static bool allUsesHaveSourceMods (const SDNode *N, unsigned CostThreshold=4)
static CCAssignFn * CCAssignFnForCall (CallingConv::ID CC, bool IsVarArg)
Selects the correct CCAssignFn for a given CallingConvention value.
static CCAssignFn * CCAssignFnForReturn (CallingConv::ID CC, bool IsVarArg)
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Additional Inherited Members
Public Types inherited from llvm::AMDGPUTargetLowering
enum ImplicitParameter { FIRST_IMPLICIT, GRID_DIM = FIRST_IMPLICIT, GRID_OFFSET }
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register, C_RegisterClass, C_Memory, C_Immediate,
C_Other, C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1, CW_Okay = 0, CW_Good = 1, CW_Better = 2,
CW_Best = 3, CW_SpecificReg = CW_Okay, CW_Register = CW_Good, CW_Memory = CW_Better,
CW_Constant = CW_Best, CW_Default = CW_Okay
}
using AsmOperandInfoVector = std::vector< AsmOperandInfo >
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction : uint8_t {
Legal, Promote, Expand, LibCall,
Custom
}
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
enum LegalizeTypeAction : uint8_t {
TypeLegal, TypePromoteInteger, TypeExpandInteger, TypeSoftenFloat,
TypeExpandFloat, TypeScalarizeVector, TypeSplitVector, TypeWidenVector,
TypePromoteFloat
}
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
enum BooleanContent { UndefinedBooleanContent, ZeroOrOneBooleanContent, ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect, ScalarCondVectorVal, VectorMaskSelect }
Enum that describes what type of support for selects the target has.
enum AtomicExpansionKind {
AtomicExpansionKind::None, AtomicExpansionKind::LLSC, AtomicExpansionKind::LLOnly, AtomicExpansionKind::CmpXChg,
AtomicExpansionKind::MaskedIntrinsic
}
Enum that specifies what an atomic load/AtomicRMWInst is expanded to, if at all.
enum MulExpansionKind { MulExpansionKind::Always, MulExpansionKind::OnlyLegalOrCustom }
Enum that specifies when a multiplication should be expanded.
enum ReciprocalEstimate : int { Unspecified = -1, Disabled = 0, Enabled = 1 }
Reciprocal estimate status values used by the functions below.
using LegalizeKind = std::pair< LegalizeTypeAction, EVT >
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
using ArgListTy = std::vector< ArgListEntry >
Protected Member Functions inherited from llvm::AMDGPUTargetLowering
SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFREM (SDValue Op, SelectionDAG &DAG) const
Split a vector store into multiple scalar stores.
SDValue LowerFCEIL (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFTRUNC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFRINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFNEARBYINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFROUND_LegalFTRUNC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFROUND64 (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFROUND (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFFLOOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFLOG (SDValue Op, SelectionDAG &DAG, double Log2BaseInverted) const
SDValue lowerFEXP (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCTLZ_CTTZ (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINT_TO_FP32 (SDValue Op, SelectionDAG &DAG, bool Signed) const
SDValue LowerINT_TO_FP64 (SDValue Op, SelectionDAG &DAG, bool Signed) const
SDValue LowerUINT_TO_FP (SDValue Op, SelectionDAG &DAG) const
SDValue LowerSINT_TO_FP (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFP64_TO_INT (SDValue Op, SelectionDAG &DAG, bool Signed) const
SDValue LowerFP_TO_FP16 (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFP_TO_UINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFP_TO_SINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerSIGN_EXTEND_INREG (SDValue Op, SelectionDAG &DAG) const
bool shouldCombineMemoryType (EVT VT) const
SDValue performLoadCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performStoreCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performAssertSZExtCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performIntrinsicWOChainCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue splitBinaryBitConstantOpImpl (DAGCombinerInfo &DCI, const SDLoc &SL, unsigned Opc, SDValue LHS, uint32_t ValLo, uint32_t ValHi) const
Split the 64-bit value LHS into two 32-bit components, and perform the binary operation Opc to it with the corresponding constant operands.
SDValue performShlCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performSraCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performSrlCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performTruncateCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulhsCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulhuCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulLoHi24Combine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performCtlz_CttzCombine (const SDLoc &SL, SDValue Cond, SDValue LHS, SDValue RHS, DAGCombinerInfo &DCI) const
SDValue performSelectCombine (SDNode *N, DAGCombinerInfo &DCI) const
bool isConstantCostlierToNegate (SDValue N) const
SDValue performFNegCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performFAbsCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performRcpCombine (SDNode *N, DAGCombinerInfo &DCI) const
std::pair< SDValue, SDValue > split64BitValue (SDValue Op, SelectionDAG &DAG) const
Return 64-bit value Op as two 32-bit integers.
SDValue getLoHalf64 (SDValue Op, SelectionDAG &DAG) const
SDValue getHiHalf64 (SDValue Op, SelectionDAG &DAG) const
std::pair< EVT, EVT > getSplitDestVTs (const EVT &VT, SelectionDAG &DAG) const
Split a vector type into two parts.
std::pair< SDValue, SDValue > splitVector (const SDValue &N, const SDLoc &DL, const EVT &LoVT, const EVT &HighVT, SelectionDAG &DAG) const
Split a vector value into two parts of types LoVT and HiVT.
SDValue SplitVectorLoad (SDValue Op, SelectionDAG &DAG) const
Split a vector load into 2 loads of half the vector.
SDValue WidenVectorLoad (SDValue Op, SelectionDAG &DAG) const
Widen a vector load from vec3 to vec4.
SDValue SplitVectorStore (SDValue Op, SelectionDAG &DAG) const
Split a vector store into 2 stores of half the vector.
SDValue LowerSTORE (SDValue Op, SelectionDAG &DAG) const
SDValue LowerSDIVREM (SDValue Op, SelectionDAG &DAG) const
SDValue LowerUDIVREM (SDValue Op, SelectionDAG &DAG) const
SDValue LowerDIVREM24 (SDValue Op, SelectionDAG &DAG, bool sign) const
void LowerUDIVREM64 (SDValue Op, SelectionDAG &DAG, SmallVectorImpl< SDValue > &Results) const
void analyzeFormalArgumentsCompute (CCState &State, const SmallVectorImpl< ISD::InputArg > &Ins) const
The SelectionDAGBuilder will automatically promote function arguments with illegal types.
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
Value * getDefaultSafeStackPointerLocation (IRBuilder<> &IRB, bool UseTLS) const
void setBooleanContents (BooleanContent Ty)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanVectorContents (BooleanContent Ty)
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type.
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setMinimumJumpTableEntries (unsigned Val)
Indicate the minimum number of blocks to generate jump tables.
void setMaximumJumpTableSize (unsigned)
Indicate the maximum number of entries in jump tables.
void setStackPointerRegisterToSaveRestore (unsigned R)
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches.
void setHasExtractBitsInsn (bool hasExtractInsn=true)
Tells the code generator that the target has BitExtract instructions.
void setJumpIsExpensive (bool isExpensive=true)
Tells the code generator not to expand logic operations on comparison predicates into separate sequences that increase the amount of flow control.
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
Add the specified register class as an available regclass for the specified value type.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (const TargetRegisterInfo *TRI, MVT VT) const
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
void computeRegisterProperties (const TargetRegisterInfo *TRI)
Once all of the register classes are added, this allows us to compute derived properties we expose.
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked load does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked store does or does not work with the specified type and indicate what to do about it.
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works.
void setOperationPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
Convenience method to set an operation to Promote and specify the type in a single call.
void setTargetDAGCombine (ISD::NodeType NT)
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
void setMinFunctionAlignment (Align Alignment)
Set the target's minimum function alignment.
void setPrefFunctionAlignment (Align Alignment)
Set the target's preferred function alignment.
void setPrefLoopAlignment (Align Alignment)
Set the target's preferred loop alignment.
void setMinStackArgumentAlignment (Align Alignment)
Set the minimum stack alignment of an argument.
void setMaxAtomicSizeInBitsSupported (unsigned SizeInBits)
Set the maximum atomic operation size supported by the backend.
void setMinCmpXchgSizeInBits (unsigned SizeInBits)
Sets the minimum cmpxchg or ll/sc size supported by the backend.
void setSupportsUnalignedAtomics (bool UnalignedSupported)
Sets whether unaligned atomic operations are supported.
virtual bool isExtFreeImpl (const Instruction *I) const
Return true if the extension represented by I is free.
bool isLegalRC (const TargetRegisterInfo &TRI, const TargetRegisterClass &RC) const
Return true if the value types that can be represented by the specified register class are all legal.
MachineBasicBlock * emitPatchPoint (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
MachineBasicBlock * emitXRayCustomEvent (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify the XRay custom event operands with target-dependent details.
MachineBasicBlock * emitXRayTypedEvent (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify the XRay typed event operands with target-dependent details.
Static Protected Member Functions inherited from llvm::AMDGPUTargetLowering
static EVT getEquivalentMemType (LLVMContext &Context, EVT VT)
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned GatherAllAliasesMaxDepth
Depth that GatherAllAliases should should continue looking for chain dependencies when trying to find a more preferable chain.
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemcpy
Specify maximum number of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxGluedStoresPerMemcpy = 0
Specify max number of store instructions to glue in inlined memcpy.
unsigned MaxLoadsPerMemcmp
Specify maximum number of load instructions per memcmp call.
unsigned MaxLoadsPerMemcmpOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemmove
Specify maximum number of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
Likewise for functions with the OptSize attribute.
bool PredictableSelectIsExpensive
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
bool EnableExtLdPromotion
bool IsStrictFPEnabled
Detailed Description
Definition at line 23 of file SIISelLowering.h.
Constructor & Destructor Documentation
SITargetLowering()
SITargetLowering::SITargetLowering (const TargetMachine & tm, const GCNSubtarget & STI)
Definition at line 118 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDCARRY, llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::ADDRSPACECAST, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_FADD, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::ISD::BR_CC, llvm::ISD::BRCOND, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::ISD::DEBUGTRAP, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FPOW, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::GCNSubtarget::getRegisterInfo(), llvm::ISD::GlobalAddress, llvm::AMDGPUSubtarget::has16BitInsts(), llvm::GCNSubtarget::hasBCNT(), llvm::GCNSubtarget::hasBFE(), llvm::GCNSubtarget::hasBFI(), llvm::GCNSubtarget::hasFFBH(), llvm::GCNSubtarget::hasFFBL(), llvm::GCNSubtarget::hasFlatAddressSpace(), llvm::GCNSubtarget::hasMadF16(), llvm::GCNSubtarget::hasMAIInsts(), llvm::AMDGPUSubtarget::hasVOP3PInsts(), llvm::GCNSubtarget::haveRoundOpsF64(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::ISD::MUL, llvm::ISD::OR, llvm::MVT::Other, llvm::TargetLoweringBase::Promote, llvm::ISD::READCYCLECOUNTER, llvm::Sched::RegPressure, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setHasExtractBitsInsn(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::SUBCARRY, llvm::ISD::TRAP, llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UNDEF, llvm::ISD::UREM, llvm::ISD::USUBO, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f16, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32f32, llvm::MVT::v32i16, llvm::MVT::v32i32, llvm::MVT::v32i8, llvm::MVT::v3f32, llvm::MVT::v3i16, llvm::MVT::v3i32, llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i8, llvm::MVT::v5f32, llvm::MVT::v5i32, llvm::MVT::v8f16, llvm::MVT::v8f32, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i8, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
Member Function Documentation
AdjustInstrPostInstrSelection()
void SITargetLowering::AdjustInstrPostInstrSelection (MachineInstr & MI, SDNode * Node) const override virtual
Assign the register class depending on the number of bits set in the writemask.
Reimplemented from llvm::TargetLowering.
Definition at line 10436 of file SIISelLowering.cpp.
References llvm::BuildMI(), llvm::tgtok::Def, llvm::AMDGPU::getAtomicNoRetOp(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::GCNSubtarget::getInstrInfo(), llvm::SDNode::getMachineOpcode(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::SIRegisterInfo::getRegClassForReg(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), getSubtarget(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDNode::hasNUsesOfValue(), I, llvm::SIRegisterInfo::isAGPR(), llvm::SDNode::isMachineOpcode(), llvm::SIRegisterInfo::isSGPRReg(), llvm::Register::isVirtualRegister(), llvm::SIInstrInfo::isVOP3(), llvm::SIInstrInfo::legalizeOperandsVOP3(), MI, MRI, llvm::MCInstrDesc::OpInfo, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineRegisterInfo::setRegClass(), TII, TRI, and llvm::SDNode::use_begin().
Referenced by isFlatGlobalAddrSpace().
allocateHSAUserSGPRs()
void SITargetLowering::allocateHSAUserSGPRs (CCState & CCInfo, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) const
Definition at line 1767 of file SIISelLowering.cpp.
References llvm::SIMachineFunctionInfo::addDispatchID(), llvm::SIMachineFunctionInfo::addDispatchPtr(), llvm::SIMachineFunctionInfo::addFlatScratchInit(), llvm::SIMachineFunctionInfo::addImplicitBufferPtr(), llvm::SIMachineFunctionInfo::addKernargSegmentPtr(), llvm::MachineFunction::addLiveIn(), llvm::SIMachineFunctionInfo::addPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::addQueuePtr(), llvm::CCState::AllocateReg(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::hasDispatchID(), llvm::SIMachineFunctionInfo::hasDispatchPtr(), llvm::SIMachineFunctionInfo::hasFlatScratchInit(), llvm::SIMachineFunctionInfo::hasImplicitBufferPtr(), llvm::SIMachineFunctionInfo::hasKernargSegmentPtr(), llvm::SIMachineFunctionInfo::hasPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::hasQueuePtr(), MRI, llvm::LLT::pointer(), and llvm::MachineRegisterInfo::setType().
Referenced by isFlatGlobalAddrSpace(), and LowerFormalArguments().
allocateSpecialEntryInputVGPRs()
void SITargetLowering::allocateSpecialEntryInputVGPRs (CCState & CCInfo, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) const
Definition at line 1623 of file SIISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), llvm::ArgDescriptor::createRegister(), llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::hasWorkItemIDX(), llvm::SIMachineFunctionInfo::hasWorkItemIDY(), llvm::SIMachineFunctionInfo::hasWorkItemIDZ(), MRI, Reg, llvm::LLT::scalar(), llvm::MachineRegisterInfo::setType(), llvm::SIMachineFunctionInfo::setWorkItemIDX(), llvm::SIMachineFunctionInfo::setWorkItemIDY(), and llvm::SIMachineFunctionInfo::setWorkItemIDZ().
Referenced by isFlatGlobalAddrSpace(), LowerFormalArguments(), and llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
allocateSpecialInputSGPRs()
void SITargetLowering::allocateSpecialInputSGPRs (CCState & CCInfo, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) const
Definition at line 1730 of file SIISelLowering.cpp.
References allocateSGPR32Input(), allocateSGPR64Input(), llvm::AMDGPUFunctionArgInfo::DispatchPtr, llvm::SIMachineFunctionInfo::getArgInfo(), llvm::SIMachineFunctionInfo::hasDispatchID(), llvm::SIMachineFunctionInfo::hasDispatchPtr(), llvm::SIMachineFunctionInfo::hasImplicitArgPtr(), llvm::SIMachineFunctionInfo::hasKernargSegmentPtr(), llvm::SIMachineFunctionInfo::hasQueuePtr(), llvm::SIMachineFunctionInfo::hasWorkGroupIDX(), llvm::SIMachineFunctionInfo::hasWorkGroupIDY(), and llvm::SIMachineFunctionInfo::hasWorkGroupIDZ().
Referenced by isFlatGlobalAddrSpace(), llvm::AMDGPUCallLowering::lowerFormalArguments(), and LowerFormalArguments().
allocateSpecialInputVGPRs()
void SITargetLowering::allocateSpecialInputVGPRs (CCState & CCInfo, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) const
Definition at line 1709 of file SIISelLowering.cpp.
References allocateVGPR32Input(), Arg, llvm::SIMachineFunctionInfo::hasWorkItemIDX(), llvm::SIMachineFunctionInfo::hasWorkItemIDY(), llvm::SIMachineFunctionInfo::hasWorkItemIDZ(), llvm::BitmaskEnumDetail::Mask(), llvm::SIMachineFunctionInfo::setWorkItemIDX(), llvm::SIMachineFunctionInfo::setWorkItemIDY(), and llvm::SIMachineFunctionInfo::setWorkItemIDZ().
Referenced by isFlatGlobalAddrSpace(), llvm::AMDGPUCallLowering::lowerFormalArguments(), and LowerFormalArguments().
allocateSystemSGPRs()
void SITargetLowering::allocateSystemSGPRs (CCState & CCInfo, MachineFunction & MF, SIMachineFunctionInfo & Info, CallingConv::ID CallConv, bool IsShader) const
Definition at line 1822 of file SIISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::SIMachineFunctionInfo::addPrivateSegmentWaveByteOffset(), llvm::SIMachineFunctionInfo::addWorkGroupIDX(), llvm::SIMachineFunctionInfo::addWorkGroupIDY(), llvm::SIMachineFunctionInfo::addWorkGroupIDZ(), llvm::SIMachineFunctionInfo::addWorkGroupInfo(), llvm::CCState::AllocateReg(), findFirstFreeSGPR(), llvm::SIMachineFunctionInfo::getPrivateSegmentWaveByteOffsetSystemSGPR(), llvm::SIMachineFunctionInfo::hasPrivateSegmentWaveByteOffset(), llvm::SIMachineFunctionInfo::hasWorkGroupIDX(), llvm::SIMachineFunctionInfo::hasWorkGroupIDY(), llvm::SIMachineFunctionInfo::hasWorkGroupIDZ(), llvm::SIMachineFunctionInfo::hasWorkGroupInfo(), Reg, and llvm::SIMachineFunctionInfo::setPrivateSegmentWaveByteOffset().
Referenced by isFlatGlobalAddrSpace(), llvm::AMDGPUCallLowering::lowerFormalArguments(), LowerFormalArguments(), and llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
allowsMisalignedMemoryAccesses()
bool SITargetLowering::allowsMisalignedMemoryAccesses (EVT , unsigned AddrSpace, unsigned Align, MachineMemOperand::Flags Flags = MachineMemOperand::MONone, bool * = nullptr) const override virtual
Determine if the target supports unaligned memory accesses.
This function returns true if the target allows unaligned memory accesses of the specified type in the given address space. If true, it also returns whether the unaligned memory access is "fast" in the last argument by reference. This is used, for example, in situations where an array copy/move/set is converted to a sequence of store operations. Its use helps to ensure that such replacements don't generate code that causes an alignment error (trap) on the target machine.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1303 of file SIISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, allowsMisalignedMemoryAccessesImpl(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSize(), and llvm::MVT::Other.
allowsMisalignedMemoryAccessesImpl()
bool SITargetLowering::allowsMisalignedMemoryAccessesImpl (unsigned Size, unsigned AS, unsigned Align, MachineMemOperand::Flags Flags = MachineMemOperand::MONone, bool * IsFast = nullptr) const
Definition at line 1247 of file SIISelLowering.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, AMDGPUAS::FLAT_ADDRESS, llvm::GCNSubtarget::hasUnalignedBufferAccess(), llvm::GCNSubtarget::hasUnalignedScratchAccess(), AMDGPUAS::LOCAL_ADDRESS, AMDGPUAS::PRIVATE_ADDRESS, and AMDGPUAS::REGION_ADDRESS.
Referenced by allowsMisalignedMemoryAccesses(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
buildRSRC()
MachineSDNode * SITargetLowering::buildRSRC (SelectionDAG & DAG, const SDLoc & DL, SDValue Ptr, uint32_t RsrcDword1, uint64_t RsrcDword2And3) const
Return a resource descriptor with the 'Add TID' bit enabled The TID (Thread ID) is multiplied by the stride value (bits [61:48] of the resource descriptor) to create an offset, which is added to the resource pointer.
Definition at line 10555 of file SIISelLowering.cpp.
References buildSMovImm32(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::MVT::i32, and llvm::MVT::v4i32.
Referenced by isFlatGlobalAddrSpace(), and isStackPtrRelative().
bundleInstWithWaitcnt()
void SITargetLowering::bundleInstWithWaitcnt (MachineInstr & MI) const
Insert MI into a BUNDLE with an S_WAITCNT 0 immediately following it.
Definition at line 3107 of file SIISelLowering.cpp.
References llvm::MIBundleBuilder::begin(), llvm::BuildMI(), E, llvm::finalizeBundle(), llvm::MachineInstr::getDebugLoc(), llvm::GCNSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getParent(), getSubtarget(), I, and TII.
Referenced by emitGWSMemViolTestLoop(), EmitInstrWithCustomInserter(), and isFlatGlobalAddrSpace().
CanLowerReturn()
bool SITargetLowering::CanLowerReturn (CallingConv::ID , MachineFunction & , bool , const SmallVectorImpl< ISD::OutputArg > & , LLVMContext &) const override virtual
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers.
If false is returned, an sret-demotion is performed.
Reimplemented from llvm::TargetLowering.
Definition at line 2252 of file SIISelLowering.cpp.
References llvm::AMDGPUTargetLowering::CCAssignFnForReturn(), llvm::CCState::CheckReturn(), and llvm::AMDGPU::isEntryFunctionCC().
Referenced by isFlatGlobalAddrSpace().
canMergeStoresTo()
bool SITargetLowering::canMergeStoresTo (unsigned AS, EVT MemVT, const SelectionDAG & DAG) const override virtual
Returns if it's reasonable to merge stores to MemVT size.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1234 of file SIISelLowering.cpp.
References AMDGPUAS::FLAT_ADDRESS, llvm::GCNSubtarget::getMaxPrivateElementSize(), llvm::EVT::getSizeInBits(), getSubtarget(), AMDGPUAS::GLOBAL_ADDRESS, AMDGPUAS::LOCAL_ADDRESS, AMDGPUAS::PRIVATE_ADDRESS, and AMDGPUAS::REGION_ADDRESS.
computeKnownBitsForFrameIndex()
void SITargetLowering::computeKnownBitsForFrameIndex (const SDValue FIOp, KnownBits & Known, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth = 0) const override virtual
Determine which of the bits of FrameIndex FIOp are known to be 0.
Default implementation computes low bits based on alignment information. This should preserve known bits passed into it.
Reimplemented from llvm::TargetLowering.
Definition at line 10777 of file SIISelLowering.cpp.
References llvm::TargetLowering::computeKnownBitsForFrameIndex(), getSubtarget(), llvm::APInt::setHighBits(), and llvm::KnownBits::Zero.
Referenced by isFlatGlobalAddrSpace().
copyToM0()
SDValue SITargetLowering::copyToM0 (SelectionDAG & DAG, SDValue Chain, const SDLoc & DL, SDValue V) const
Definition at line 5126 of file SIISelLowering.cpp.
References llvm::ISD::AssertZext, llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getValueType(), llvm::MVT::Glue, llvm::MVT::i32, and llvm::MVT::Other.
Referenced by llvm::createR600ISelDag(), getBufferOffsetForMMO(), and isFlatGlobalAddrSpace().
denormalsEnabledForType()
bool SITargetLowering::denormalsEnabledForType (const SelectionDAG & DAG, EVT VT) const
Definition at line 10930 of file SIISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getMachineFunction(), llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), hasFP32Denormals(), hasFP64FP16Denormals(), and llvm::MVT::SimpleTy.
Referenced by isCanonicalized(), and isFlatGlobalAddrSpace().
emitGWSMemViolTestLoop()
MachineBasicBlock * SITargetLowering::emitGWSMemViolTestLoop (MachineInstr & MI, MachineBasicBlock * BB) const
Definition at line 3121 of file SIISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), bundleInstWithWaitcnt(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::AMDGPU::Hwreg::encodeHwreg(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::GCNSubtarget::getInstrInfo(), llvm::SIInstrInfo::getNamedOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getSubtarget(), I, llvm::AMDGPU::Hwreg::ID_TRAPSTS, llvm::RegState::Kill, MRI, llvm::AMDGPU::Hwreg::OFFSET_MEM_VIOL, Reg, splitBlockForLoop(), and TII.
Referenced by EmitInstrWithCustomInserter(), and isFlatGlobalAddrSpace().
EmitInstrWithCustomInserter()
MachineBasicBlock * SITargetLowering::EmitInstrWithCustomInserter (MachineInstr & MI, MachineBasicBlock * MBB) const override virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
Definition at line 3586 of file SIISelLowering.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::Triple::AMDHSA, llvm::Triple::AMDPAL, assert(), llvm::MachineBasicBlock::begin(), llvm::SIInstrInfo::buildExtractSubRegOrImm(), llvm::BuildMI(), bundleInstWithWaitcnt(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Define, E, emitGWSMemViolTestLoop(), emitIndirectDst(), emitIndirectSrc(), llvm::TargetLowering::EmitInstrWithCustomInserter(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::AMDGPUMachineFunction::getLDSSize(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SIInstrInfo::getRegisterInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIRegisterInfo::getReturnAddressReg(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), getSubtarget(), llvm::MachineFunction::getSubtarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::AMDGPU::getVOPe64(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::AMDGPU::IsaInfo::getWavefrontSize(), I, llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, Info, llvm::MachineBasicBlock::insert(), llvm::SIInstrInfo::isMIMG(), llvm::SIInstrInfo::isVOP3(), llvm::GCNSubtarget::isWave32(), llvm::RegState::Kill, llvm::SIInstrInfo::legalizeOperands(), llvm::BitmaskEnumDetail::Mask(), llvm::MachineInstr::mayLoadOrStore(), llvm::MachineInstr::memoperands_empty(), MI, MRI, llvm::SIInstrInfo::pseudoToMCOpcode(), llvm::report_fatal_error(), llvm::MachineOperand::setIsUndef(), splitKillBlock(), llvm::ARM_MB::ST, TII, and TRI.
Referenced by isFlatGlobalAddrSpace().
enableAggressiveFMAFusion()
bool SITargetLowering::enableAggressiveFMAFusion (EVT VT) const override virtual
Return true if target always beneficiates from combining into FMA for a given value type.
This must typically return false on targets where FMA takes more cycles to execute than FADD.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3882 of file SIISelLowering.cpp.
Referenced by isFlatGlobalAddrSpace().
finalizeLowering()
void SITargetLowering::finalizeLowering (MachineFunction & MF) const override virtual
Execute target specific actions to finalize target lowering.
This is used to set extra flags in MachineFrameInformation and freezing the set of reserved registers. The default implementation just freezes the set of reserved registers.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 10724 of file SIISelLowering.cpp.
References assert(), llvm::BuildMI(), llvm::MachineFunction::empty(), llvm::TargetLoweringBase::finalizeLowering(), llvm::SIInstrInfo::fixImplicitOperands(), llvm::MachineFunction::front(), llvm::MachineBasicBlock::getFirstNonDebugInstr(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIMachineFunctionInfo::getScratchRSrcReg(), llvm::SIMachineFunctionInfo::getScratchWaveOffsetReg(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFunction::getSubtarget(), llvm::TargetLoweringBase::getTargetMachine(), I, Info, llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::SIMachineFunctionInfo::limitOccupancy(), MI, MRI, llvm::MachineRegisterInfo::replaceRegWith(), reservePrivateMemoryRegs(), llvm::ARM_MB::ST, TII, and TRI.
Referenced by isFlatGlobalAddrSpace().
getAddrModeArguments()
bool SITargetLowering::getAddrModeArguments (IntrinsicInst * , SmallVectorImpl< Value *> & , Type *&) const override virtual
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
This allows as much computation as possible to be done in the address mode for that operand. This hook lets targets also pass back when this should be done on intrinsics which load/store.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1061 of file SIISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseOffs, AMDGPUAS::FLAT_ADDRESS, llvm::CallBase::getArgOperand(), llvm::GCNSubtarget::getInstrInfo(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Value::getType(), llvm::GCNSubtarget::hasFlatInstOffsets(), llvm::SIInstrInfo::isLegalFLATOffset(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::TargetLoweringBase::AddrMode::Scale.
getConstraintType()
SITargetLowering::ConstraintType SITargetLowering::getConstraintType (StringRef Constraint) const override virtual
Given a constraint, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
Definition at line 10708 of file SIISelLowering.cpp.
References llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::getConstraintType(), and llvm::StringRef::size().
Referenced by isFlatGlobalAddrSpace().
getNumRegistersForCallingConv()
unsigned SITargetLowering::getNumRegistersForCallingConv (LLVMContext & Context, CallingConv::ID CC, EVT VT) const override virtual
Certain targets require unusual breakdowns of certain types.
For MIPS, this occurs when a vector type is used, as vector are passed through the integer register set.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 818 of file SIISelLowering.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, llvm::TargetLoweringBase::getNumRegistersForCallingConv(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::EVT::isVector(), and Size.
Referenced by llvm::AMDGPUCallLowering::AMDGPUCallLowering().
getOptimalMemOpType()
EVT SITargetLowering::getOptimalMemOpType (uint64_t , unsigned , unsigned , bool , bool , bool , const AttributeList &) const override virtual
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1322 of file SIISelLowering.cpp.
References llvm::MVT::Other, llvm::MVT::v2i32, and llvm::MVT::v4i32.
getPreferredVectorAction()
TargetLoweringBase::LegalizeTypeAction SITargetLowering::getPreferredVectorAction (MVT VT) const override virtual
Return the preferred vector type legalization action.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1370 of file SIISelLowering.cpp.
References llvm::MVT::bitsLE(), llvm::TargetLoweringBase::getPreferredVectorAction(), llvm::MVT::getScalarType(), llvm::MVT::getVectorNumElements(), llvm::MVT::i16, llvm::MVT::isPow2VectorType(), llvm::TargetLoweringBase::TypeSplitVector, and llvm::TargetLoweringBase::TypeWidenVector.
Referenced by isFlatGlobalAddrSpace().
getPrefLoopAlignment()
Align SITargetLowering::getPrefLoopAlignment (MachineLoop * ML) const override virtual
Return the preferred loop alignment.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 10791 of file SIISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::BuildMI(), DisableLoopAlignment, llvm::MachineBasicBlock::getAlignment(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::MachineBasicBlock::getFirstNonDebugInstr(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::GCNSubtarget::getInstrInfo(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::TargetLoweringBase::getPrefLoopAlignment(), getSubtarget(), llvm::AMDGPUSubtarget::GFX10, I, LLVM_ATTRIBUTE_UNUSED, MI, P, and TII.
Referenced by isFlatGlobalAddrSpace().
getRegClassFor()
const TargetRegisterClass * SITargetLowering::getRegClassFor (MVT VT, bool isDivergent) const override virtual
Return the register class that should be used for the specified value type.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 10993 of file SIISelLowering.cpp.
References llvm::SIRegisterInfo::getEquivalentSGPRClass(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::GCNSubtarget::getRegisterInfo(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::SIRegisterInfo::isSGPRClass(), and TRI.
Referenced by isFlatGlobalAddrSpace(), and shouldEmitPCReloc().
getRegForInlineAsmConstraint()
std::pair< unsigned, const TargetRegisterClass * > SITargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, StringRef Constraint, MVT VT) const override virtual
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 10590 of file SIISelLowering.cpp.
References llvm::MVT::f16, llvm::Failed(), llvm::StringRef::getAsInteger(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::TargetRegisterClass::getRegister(), llvm::MVT::getSizeInBits(), llvm::GCNSubtarget::hasMAIInsts(), llvm::MVT::i128, llvm::MVT::i16, llvm::TargetLoweringBase::isTypeLegal(), llvm::MVT::SimpleTy, llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by isFlatGlobalAddrSpace(), and requiresUniformRegister().
getRegisterByName()
Register SITargetLowering::getRegisterByName (const char * RegName, LLT Ty, const MachineFunction & MF) const override virtual
Return the register ID of the name passed in.
Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented from llvm::TargetLowering.
Definition at line 2988 of file SIISelLowering.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::GCNSubtarget::getRegisterInfo(), llvm::LLT::getSizeInBits(), llvm::GCNSubtarget::hasFlatScrRegister(), llvm_unreachable, Reg, Register, and llvm::report_fatal_error().
Referenced by isFlatGlobalAddrSpace().
getRegisterTypeForCallingConv()
MVT SITargetLowering::getRegisterTypeForCallingConv (LLVMContext & Context, CallingConv::ID CC, EVT VT) const override virtual
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
For MIPS all vector types must be passed through the integer register set.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 795 of file SIISelLowering.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::MVT::i32, llvm::EVT::isInteger(), llvm::EVT::isVector(), Size, llvm::MVT::v2f16, and llvm::MVT::v2i16.
Referenced by llvm::AMDGPUCallLowering::AMDGPUCallLowering().
getScalarShiftAmountTy()
MVT SITargetLowering::getScalarShiftAmountTy (const DataLayout & DL, EVT) const override virtual
EVT is not used in-tree, but is used by out-of-tree target.
A documentation for this function would be nice...
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3901 of file SIISelLowering.cpp.
References llvm::MVT::i16, and llvm::MVT::i32.
Referenced by isFlatGlobalAddrSpace().
getSetCCResultType()
EVT SITargetLowering::getSetCCResultType (const DataLayout & DL, LLVMContext & Context, EVT VT) const override virtual
Return the ValueType of the result of SETCC operations.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3893 of file SIISelLowering.cpp.
References llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i1, and llvm::EVT::isVector().
Referenced by getFPTernOp(), and isFlatGlobalAddrSpace().
getSubtarget()
const GCNSubtarget * SITargetLowering::getSubtarget () const
Definition at line 768 of file SIISelLowering.cpp.
Referenced by AdjustInstrPostInstrSelection(), bitOpWithConstantIsReducible(), bundleInstWithWaitcnt(), canMergeStoresTo(), computeKnownBitsForFrameIndex(), emitGWSMemViolTestLoop(), EmitInstrWithCustomInserter(), getPermuteMask(), getPrefLoopAlignment(), getSplatConstantFP(), insertCopiesSplitCSR(), isClampZeroToOne(), isEligibleForTailCallOptimization(), LowerCall(), lowerFCMPIntrinsic(), LowerFormalArguments(), lowerICMPIntrinsic(), LowerReturn(), parseTexFail(), PostISelFolding(), shouldEmitPCReloc(), splitKillBlock(), and wrapAddr64Rsrc().
getTgtMemIntrinsic()
bool SITargetLowering::getTgtMemIntrinsic (IntrinsicInfo & , const CallInst & , MachineFunction & , unsigned) const override virtual
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
If this is the case, it returns true and store the intrinsic information into the IntrinsicInfo that was passed to the function.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 921 of file SIISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::TargetLoweringBase::IntrinsicInfo::align, llvm::dyn_cast(), llvm::TargetLoweringBase::IntrinsicInfo::flags, llvm::CallBase::getArgOperand(), llvm::Intrinsic::getAttributes(), llvm::SIMachineFunctionInfo::getBufferPSV(), llvm::Value::getContext(), llvm::SIMachineFunctionInfo::getGWSPSV(), llvm::SIMachineFunctionInfo::getImagePSV(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::User::getOperand(), llvm::Type::getPointerElementType(), llvm::MachineFunction::getSubtarget(), llvm::Value::getType(), llvm::MVT::getVT(), llvm::AttributeList::hasFnAttribute(), llvm::MVT::i32, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ConstantInt::isZero(), llvm::AMDGPU::lookupRsrcIntrinsic(), llvm::TargetLoweringBase::IntrinsicInfo::memVT, memVTFromAggregate(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MachineMemOperand::MOVolatile, llvm::TargetLoweringBase::IntrinsicInfo::opc, llvm::MVT::Other, llvm::TargetLoweringBase::IntrinsicInfo::ptrVal, llvm::Optional< T >::reset(), and llvm::TargetLoweringBase::IntrinsicInfo::size.
getVectorTypeBreakdownForCallingConv()
unsigned SITargetLowering::getVectorTypeBreakdownForCallingConv (LLVMContext & Context, CallingConv::ID CC, EVT VT, EVT & IntermediateVT, unsigned & NumIntermediates, MVT & RegisterVT) const override virtual
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
This occurs even if the vector type is legal.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 843 of file SIISelLowering.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::TargetLoweringBase::getVectorTypeBreakdownForCallingConv(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::MVT::i32, llvm::EVT::isInteger(), llvm::EVT::isVector(), Size, llvm::MVT::v2f16, and llvm::MVT::v2i16.
hasBitPreservingFPLogic()
bool SITargetLowering::hasBitPreservingFPLogic (EVT VT) const override virtual
Return true if it is safe to transform an integer-domain bitwise operation into the equivalent floating-point operation.
This should be set to true if the target has IEEE-754-compliant fabs/fneg operations for the input type.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3878 of file SIISelLowering.cpp.
References llvm::EVT::getScalarType(), and llvm::TargetLoweringBase::isTypeLegal().
Referenced by isFlatGlobalAddrSpace().
initializeSplitCSR()
void SITargetLowering::initializeSplitCSR (MachineBasicBlock * Entry) const override virtual
Perform necessary initialization to handle a subset of CSRs explicitly via copies.
This function is called at the beginning of instruction selection.
Reimplemented from llvm::TargetLowering.
Definition at line 1988 of file SIISelLowering.cpp.
Referenced by isFlatGlobalAddrSpace().
insertCopiesSplitCSR()
void SITargetLowering::insertCopiesSplitCSR (MachineBasicBlock * Entry, const SmallVectorImpl< MachineBasicBlock *> & Exits) const override virtual
Insert explicit copies in entry and exit blocks.
We copy a subset of CSRs to virtual registers in the entry block, and copy them back to physical registers in the exit blocks. This function is called at the end of instruction selection.
Reimplemented from llvm::TargetLowering.
Definition at line 1992 of file SIISelLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), contains(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MCInstrInfo::get(), llvm::SIRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::GCNSubtarget::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), getSubtarget(), I, llvm_unreachable, MRI, TII, and TRI.
Referenced by isFlatGlobalAddrSpace().
isCanonicalized()
bool SITargetLowering::isCanonicalized (SelectionDAG & DAG, SDValue Op, unsigned MaxDepth = 5) const
Definition at line 8741 of file SIISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::APFloat::bitcastToAPInt(), llvm::ISD::BUILD_VECTOR, C, llvm::AMDGPUISD::CLAMP, llvm::AMDGPUISD::CVT_F32_UBYTE0, llvm::AMDGPUISD::CVT_F32_UBYTE1, llvm::AMDGPUISD::CVT_F32_UBYTE2, llvm::AMDGPUISD::CVT_F32_UBYTE3, llvm::AMDGPUISD::CVT_PKRTZ_F16_F32, denormalsEnabledForType(), llvm::AMDGPUISD::DIV_FIXUP, llvm::AMDGPUISD::DIV_FMAS, llvm::AMDGPUISD::DIV_SCALE, llvm::numbers::e, E, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, F(), llvm::MVT::f16, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FFLOOR, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::AMDGPUISD::FMAD_FTZ, llvm::AMDGPUISD::FMAX3, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN3, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::AMDGPUISD::FMUL_LEGACY, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::AMDGPUISD::FRACT, llvm::ISD::FREM, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::SelectionDAG::getConstantFP(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::APFloat::getQNaN(), llvm::EVT::getScalarType(), llvm::APFloat::getSemantics(), llvm::SDValue::getValueType(), I, llvm::MVT::i16, llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::APFloat::isDenormal(), llvm::SelectionDAG::isKnownNeverSNaN(), llvm::APFloat::isNaN(), llvm::APFloat::isSignaling(), llvm::AMDGPUISD::LDEXP, LLVM_FALLTHROUGH, llvm_unreachable, llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_IFLAG, llvm::AMDGPUISD::RCP_LEGACY, llvm::AMDGPUISD::RSQ, llvm::AMDGPUISD::RSQ_CLAMP, llvm::AMDGPUISD::RSQ_LEGACY, llvm::ISD::SELECT, llvm::GCNSubtarget::supportsMinMaxDenormModes(), llvm::AMDGPUISD::TRIG_PREOP, llvm::ISD::TRUNCATE, llvm::ISD::UNDEF, and llvm::MVT::v2f16.
Referenced by isFlatGlobalAddrSpace(), and vectorEltWillFoldAway().
isEligibleForTailCallOptimization()
bool SITargetLowering::isEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > & Outs, const SmallVectorImpl< SDValue > & OutVals, const SmallVectorImpl< ISD::InputArg > & Ins, SelectionDAG & DAG) const
Definition at line 2594 of file SIISelLowering.cpp.
References llvm::CCState::AnalyzeCallOperands(), llvm::Function::args(), canGuaranteeTCO(), llvm::AMDGPUTargetLowering::CCAssignFnForCall(), llvm::SmallVectorBase::empty(), llvm::SIMachineFunctionInfo::getBytesInStackArgArea(), llvm::Function::getCallingConv(), llvm::SIRegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, mayTailCallThisCC(), MRI, llvm::TargetMachine::Options, llvm::TargetLowering::parametersInCSRMatch(), llvm::CCState::resultsCompatible(), and TRI.
Referenced by isFlatGlobalAddrSpace(), and LowerCall().
isFlatGlobalAddrSpace()
static bool llvm::SITargetLowering::isFlatGlobalAddrSpace (unsigned AS) inline static
Definition at line 265 of file SIISelLowering.h.
References AdjustInstrPostInstrSelection(), allocateHSAUserSGPRs(), allocateSpecialEntryInputVGPRs(), allocateSpecialInputSGPRs(), allocateSpecialInputVGPRs(), allocateSystemSGPRs(), buildRSRC(), bundleInstWithWaitcnt(), Callee, CanLowerReturn(), computeKnownBitsForFrameIndex(), AMDGPUAS::CONSTANT_ADDRESS, copyToM0(), denormalsEnabledForType(), llvm::Depth, emitGWSMemViolTestLoop(), EmitInstrWithCustomInserter(), enableAggressiveFMAFusion(), finalizeLowering(), AMDGPUAS::FLAT_ADDRESS, getConstraintType(), getPreferredVectorAction(), getPrefLoopAlignment(), getRegClassFor(), getRegForInlineAsmConstraint(), getRegisterByName(), getScalarShiftAmountTy(), getSetCCResultType(), AMDGPUAS::GLOBAL_ADDRESS, hasBitPreservingFPLogic(), Info, initializeSplitCSR(), llvm::MipsISD::Ins, insertCopiesSplitCSR(), isCanonicalized(), isEligibleForTailCallOptimization(), isFMADLegalForFAddFSub(), isFMAFasterThanFMulAndFAdd(), isFreeAddrSpaceCast(), isKnownNeverNaNForTargetNode(), isNoopAddrSpaceCast(), isOffsetFoldingLegal(), isSDNodeSourceOfDivergence(), isTypeDesirableForOp(), legalizeTargetIndependentNode(), LowerCall(), LowerCallResult(), LowerFormalArguments(), LowerOperation(), LowerReturn(), AMDGPUAS::MAX_AMDGPU_ADDRESS, MaxDepth, mayBeEmittedAsTailCall(), MI, passSpecialInputs(), PerformDAGCombine(), PostISelFolding(), ReplaceNodeResults(), requiresUniformRegister(), Results, shouldConvertConstantLoadToIntImm(), shouldExpandAtomicRMWInIR(), splitBinaryVectorOp(), splitKillBlock(), splitTernaryVectorOp(), splitUnaryVectorOp(), supportSplitCSR(), TRI, and wrapAddr64Rsrc().
Referenced by getSPDenormModeValue(), isNoopAddrSpaceCast(), and llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg().
isFMADLegalForFAddFSub()
bool SITargetLowering::isFMADLegalForFAddFSub (const SelectionDAG & DAG, const SDNode * N) const override virtual
Returns true if the FADD or FSUB node passed could legally be combined with an fmul to form an ISD::FMAD.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3949 of file SIISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::SelectionDAG::getMachineFunction(), llvm::SDNode::getValueType(), hasFP32Denormals(), hasFP64FP16Denormals(), and llvm::GCNSubtarget::hasMadF16().
Referenced by isFlatGlobalAddrSpace().
isFMAFasterThanFMulAndFAdd()
bool SITargetLowering::isFMAFasterThanFMulAndFAdd (const MachineFunction & MF, EVT) const override virtual
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
NOTE: This may be called before legalization on types for which FMAs are not legal, but should return true if those types will eventually legalize to types that support FMAs. After legalization, it will only be called on types that support FMAs (via Legal or Custom actions)
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3922 of file SIISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::GCNSubtarget::hasDLInsts(), llvm::GCNSubtarget::hasFastFMAF32(), hasFP32Denormals(), hasFP64FP16Denormals(), and llvm::MVT::SimpleTy.
Referenced by isClampZeroToOne(), and isFlatGlobalAddrSpace().
isFPExtFoldable()
bool SITargetLowering::isFPExtFoldable (const SelectionDAG & DAG, unsigned Opcode, EVT DestVT, EVT SrcVT) const override virtual
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 780 of file SIISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::SelectionDAG::getMachineFunction(), llvm::EVT::getScalarType(), llvm::GCNSubtarget::hasFmaMixInsts(), hasFP32Denormals(), and llvm::AMDGPUSubtarget::hasMadMixInsts().
isFreeAddrSpaceCast()
bool SITargetLowering::isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override virtual
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
we are happy to sink it into basic blocks. A cast may be free, but not necessarily a no-op. e.g. a free truncate from a 64-bit to 32-bit pointer.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1353 of file SIISelLowering.cpp.
References AMDGPUAS::FLAT_ADDRESS, and isNoopAddrSpaceCast().
Referenced by isFlatGlobalAddrSpace().
isKnownNeverNaNForTargetNode()
bool SITargetLowering::isKnownNeverNaNForTargetNode (SDValue Op, const SelectionDAG & DAG, bool SNaN = false, unsigned Depth = 0) const override virtual
If SNaN is false,.
Returns
true if Op is known to never be any NaN. If sNaN is true, returns if Op is known to never be a signaling NaN.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 10943 of file SIISelLowering.cpp.
References llvm::AMDGPUISD::CLAMP, llvm::AMDGPU::SIModeRegisterDefaults::DX10Clamp, llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::AMDGPUMachineFunction::getMode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), Info, llvm::SelectionDAG::isKnownNeverNaN(), and llvm::AMDGPUTargetLowering::isKnownNeverNaNForTargetNode().
Referenced by isFlatGlobalAddrSpace().
isLegalAddressingMode()
bool SITargetLowering::isLegalAddressingMode (const DataLayout & DL, const AddrMode & AM, Type * Ty, unsigned AS, Instruction * I = nullptr) const override virtual
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
If the address space cannot be determined, it will be -1.
TODO: Remove default argument
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1153 of file SIISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, AMDGPUAS::BUFFER_FAT_POINTER, AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, AMDGPUAS::FLAT_ADDRESS, llvm::GCNSubtarget::getGeneration(), llvm::DataLayout::getTypeStoreSize(), AMDGPUAS::GLOBAL_ADDRESS, llvm::TargetLoweringBase::AddrMode::HasBaseReg, isLegalGlobalAddressingMode(), llvm::Type::isSized(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::isUInt< 8 >(), llvm_unreachable, AMDGPUAS::LOCAL_ADDRESS, AMDGPUAS::PRIVATE_ADDRESS, AMDGPUAS::REGION_ADDRESS, llvm::TargetLoweringBase::AddrMode::Scale, llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, AMDGPUAS::UNKNOWN_ADDRESS_SPACE, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
Referenced by getSPDenormModeValue().
isLegalGlobalAddressingMode()
bool SITargetLowering::isLegalGlobalAddressingMode (const AddrMode & AM) const
Definition at line 1095 of file SIISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::GCNSubtarget::getInstrInfo(), AMDGPUAS::GLOBAL_ADDRESS, llvm::GCNSubtarget::hasAddr64(), llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::GCNSubtarget::hasFlatGlobalInsts(), llvm::SIInstrInfo::isLegalFLATOffset(), llvm::TargetLoweringBase::AddrMode::Scale, and llvm::GCNSubtarget::useFlatForGlobal().
Referenced by getBufferFormatWithCompCount(), and isLegalAddressingMode().
isMemOpHasNoClobberedMemOperand()
bool SITargetLowering::isMemOpHasNoClobberedMemOperand (const SDNode * N) const
Definition at line 1346 of file SIISelLowering.cpp.
References llvm::MemSDNode::getMemOperand(), llvm::Instruction::getMetadata(), llvm::MachineMemOperand::getValue(), I, and N.
Referenced by getLoadExtOrTrunc().
isMemOpUniform()
bool SITargetLowering::isMemOpUniform (const SDNode * N) const
Definition at line 1363 of file SIISelLowering.cpp.
References llvm::MemSDNode::getMemOperand(), llvm::AMDGPUInstrInfo::isUniformMMO(), and N.
isNoopAddrSpaceCast()
bool SITargetLowering::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1341 of file SIISelLowering.cpp.
References isFlatGlobalAddrSpace().
Referenced by isFlatGlobalAddrSpace(), isFreeAddrSpaceCast(), and llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast().
isOffsetFoldingLegal()
bool SITargetLowering::isOffsetFoldingLegal (const GlobalAddressSDNode * GA) const override virtual
Return true if folding a constant offset with the given GlobalAddress is legal.
It is frequently not legal in PIC relocation models.
Reimplemented from llvm::TargetLowering.
Definition at line 5029 of file SIISelLowering.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::GlobalAddressSDNode::getAddressSpace(), llvm::GlobalAddressSDNode::getGlobal(), AMDGPUAS::GLOBAL_ADDRESS, and shouldEmitGOTReloc().
Referenced by isFlatGlobalAddrSpace().
isSDNodeSourceOfDivergence()
bool SITargetLowering::isSDNodeSourceOfDivergence (const SDNode * N, FunctionLoweringInfo * FLI, LegacyDivergenceAnalysis * DA) const override virtual
Reimplemented from llvm::TargetLowering.
Definition at line 10875 of file SIISelLowering.cpp.
References assert(), llvm::ISD::CALLSEQ_END, llvm::ISD::CopyFromReg, llvm::FunctionLoweringInfo::DemoteRegister, AMDGPUAS::FLAT_ADDRESS, llvm::FunctionLoweringInfo::Fn, llvm::MemSDNode::getAddressSpace(), llvm::Function::getCallingConv(), llvm::GCNSubtarget::getInstrInfo(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::RegisterSDNode::getReg(), llvm::SIInstrInfo::getRegisterInfo(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, isCopyFromRegOfInlineAsm(), llvm::LegacyDivergenceAnalysis::isDivergent(), llvm::AMDGPU::isEntryFunctionCC(), llvm::AMDGPU::isIntrinsicSourceOfDivergence(), llvm::Register::isPhysicalRegister(), llvm::SIRegisterInfo::isSGPRReg(), llvm::ISD::LOAD, llvm::FunctionLoweringInfo::MF, MRI, N, AMDGPUAS::PRIVATE_ADDRESS, Reg, llvm::ARM_MB::ST, and TRI.
Referenced by isFlatGlobalAddrSpace().
isShuffleMaskLegal()
bool SITargetLowering::isShuffleMaskLegal (ArrayRef< int > , EVT) const override virtual
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
By default, if a target supports the VECTOR_SHUFFLE node, all mask values are assumed to be legal.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 789 of file SIISelLowering.cpp.
isTypeDesirableForOp()
bool SITargetLowering::isTypeDesirableForOp (unsigned , EVT VT) const override virtual
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
e.g. On x86 i16 is legal, but undesirable since i16 instruction encodings are longer and some i16 instructions are slow.
Reimplemented from llvm::TargetLowering.
Definition at line 1383 of file SIISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::alignDown(), llvm::ISD::AND, Arg, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::EVT::bitsLT(), llvm::EVT::changeTypeToInteger(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineFrameInfo::CreateFixedObject(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::AMDGPUTargetLowering::FIRST_IMPLICIT, llvm::ISD::InputArg::Flags, llvm::ISD::ArgFlagsTy::getByValSize(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExtLoad(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::AMDGPUTargetLowering::getImplicitParameterOffset(), llvm::MachineFunction::getInfo(), llvm::MachineRegisterInfo::getLiveInVirtReg(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getObjectPtrOffset(), llvm::TargetLoweringBase::getPointerTy(), llvm::SIMachineFunctionInfo::getPreloadedValue(), llvm::MachineFunction::getRegInfo(), llvm::ArgDescriptor::getRegister(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::SDValue::getValue(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, Info, llvm::ISD::ArgFlagsTy::isByVal(), llvm::EVT::isFloatingPoint(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::TargetLowering::isTypeDesirableForOp(), llvm::EVT::isVector(), llvm::ISD::ArgFlagsTy::isZExt(), llvm::AMDGPUFunctionArgInfo::KERNARG_SEGMENT_PTR, llvm::SPII::Load, llvm::ISD::LOAD, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, MRI, llvm::ISD::NON_EXTLOAD, llvm::ISD::OR, Reg, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::CCValAssign::SExt, llvm::ISD::SEXTLOAD, Signed, Size, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::TRUNCATE, llvm::ISD::XOR, llvm::CCValAssign::ZExt, and llvm::ISD::ZEXTLOAD.
Referenced by isFlatGlobalAddrSpace().
legalizeTargetIndependentNode()
SDNode * SITargetLowering::legalizeTargetIndependentNode (SDNode * Node, SelectionDAG & DAG) const
Legalize target independent instructions (e.g.
INSERT_SUBREG) with frame index operands. LLVM assumes that inputs are to these instructions are registers.
Definition at line 10297 of file SIISelLowering.cpp.
References llvm::ISD::CopyToReg, llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SelectionDAG::getCopyToReg(), llvm::SDNode::getGluedNode(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::RegisterSDNode::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MVT::i1, isFrameIndexOp(), llvm::Register::isPhysicalRegister(), MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAG::ReplaceAllUsesWith(), and llvm::SelectionDAG::UpdateNodeOperands().
Referenced by isFlatGlobalAddrSpace(), PostISelFolding(), and selectSGPRVectorRegClassID().
LowerCall()
SDValue SITargetLowering::LowerCall (CallLoweringInfo & , SmallVectorImpl< SDValue > &) const override virtual
This hook must be implemented to lower calls into the specified DAG.
The outgoing arguments to the call are described by the Outs array, and the values to be returned by the call are described by the Ins array. The implementation should fill in the InVals array with legal-type return values from the call, and return the resulting token chain value.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 2676 of file SIISelLowering.cpp.
References llvm::AMDGPUTargetLowering::addTokenForArgument(), llvm::CCValAssign::AExt, llvm::CCState::AnalyzeCallOperands(), llvm::ISD::ANY_EXTEND, Arg, assert(), llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::AMDGPUISD::CALL, llvm::TargetLowering::CallLoweringInfo::CallConv, Callee, llvm::TargetLowering::CallLoweringInfo::Callee, llvm::AMDGPUTargetLowering::CCAssignFnForCall(), llvm::TargetLowering::CallLoweringInfo::Chain, llvm::commonAlignment(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::TargetLowering::CallLoweringInfo::CS, llvm::TargetLowering::CallLoweringInfo::DAG, llvm::TargetLowering::CallLoweringInfo::DL, llvm::numbers::e, E, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), llvm::ISD::FP_EXTEND, llvm::CCValAssign::FPExt, llvm::CCValAssign::Full, llvm::ISD::ArgFlagsTy::getByValAlign(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), llvm::Function::getCallingConv(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachineFunction::getInfo(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemcpy(), llvm::CCState::getNextStackOffset(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::SIRegisterInfo::getReturnAddressReg(), llvm::SIMachineFunctionInfo::getScratchRSrcReg(), llvm::MachinePointerInfo::getStack(), llvm::GCNSubtarget::getStackAlignment(), llvm::SelectionDAG::getStore(), llvm::MVT::getStoreSize(), getSubtarget(), llvm::MachineFunction::getTarget(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SelectionDAG::getTokenFactor(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::CCValAssign::getValVT(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::TargetOptions::GuaranteedTailCallOpt, I, llvm::MVT::i32, llvm::MVT::i64, Info, llvm::MipsISD::Ins, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::ISD::ArgFlagsTy::isByVal(), isEligibleForTailCallOptimization(), llvm::CCValAssign::isMemLoc(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isMustTailCall(), llvm::isNullConstant(), llvm::CCValAssign::isRegLoc(), llvm::AMDGPU::isShader(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::SDValue::isUndef(), llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm_unreachable, LowerCallResult(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::BitmaskEnumDetail::Mask(), llvm::TargetMachine::Options, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, passSpecialInputs(), AMDGPUAS::PRIVATE_ADDRESS, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), llvm::MachineFrameInfo::setHasTailCall(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SPII::Store, llvm::AMDGPUISD::TC_RETURN, llvm::ISD::TokenFactor, TRI, llvm::MVT::v4i32, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by isFlatGlobalAddrSpace().
LowerCallResult()
SDValue SITargetLowering::LowerCallResult (SDValue Chain, SDValue InFlag, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > & Ins, const SDLoc & DL, SelectionDAG & DAG, SmallVectorImpl< SDValue > & InVals, bool isThisReturn, SDValue ThisVal) const
Definition at line 2378 of file SIISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::CCState::AnalyzeCallResult(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::AMDGPUTargetLowering::CCAssignFnForReturn(), llvm::CCValAssign::Full, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm_unreachable, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), llvm::CCValAssign::SExt, llvm::SmallVectorBase::size(), llvm::ISD::TRUNCATE, and llvm::CCValAssign::ZExt.
Referenced by isFlatGlobalAddrSpace(), and LowerCall().
LowerFormalArguments()
SDValue SITargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , const SDLoc & , SelectionDAG & , SmallVectorImpl< SDValue > &) const override virtual
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 2027 of file SIISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCValAssign::AExt, allocateHSAUserSGPRs(), llvm::CCState::AllocateReg(), allocateSpecialEntryInputVGPRs(), allocateSpecialInputSGPRs(), allocateSpecialInputVGPRs(), allocateSystemSGPRs(), llvm::CallingConv::AMDGPU_PS, llvm::CCState::AnalyzeFormalArguments(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::SmallVectorImpl< T >::append(), Arg, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::BCvt, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ISD::BITCAST, llvm::AMDGPUTargetLowering::CCAssignFnForCall(), llvm::countTrailingZeros(), llvm::LLVMContext::diagnose(), llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ISD::InputArg::Flags, llvm::CCValAssign::Full, llvm::Pass::getAnalysis(), llvm::SIMachineFunctionInfo::getArgInfo(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SDLoc::getDebugLoc(), llvm::SelectionDAG::getEntryNode(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getFunction(), llvm::Function::getFunctionType(), llvm::GCNSubtarget::getGeneration(), llvm::MachineFunction::getInfo(), llvm::EVT::getIntegerVT(), llvm::GCNSubtarget::getKnownHighZeroBitsForFrameIndex(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::SelectionDAG::getNode(), llvm::ISD::InputArg::getOrigArgIndex(), llvm::FunctionType::getParamType(), llvm::SelectionDAG::getPass(), llvm::SIMachineFunctionInfo::getPSInputAddr(), llvm::SIMachineFunctionInfo::getPSInputEnable(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIMachineFunctionInfo::getScratchRSrcReg(), llvm::SIMachineFunctionInfo::getScratchWaveOffsetReg(), getSubtarget(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::SIMachineFunctionInfo::hasDispatchPtr(), llvm::SIMachineFunctionInfo::hasFlatScratchInit(), llvm::SIMachineFunctionInfo::hasKernargSegmentPtr(), llvm::SIMachineFunctionInfo::hasWorkGroupIDX(), llvm::SIMachineFunctionInfo::hasWorkGroupIDY(), llvm::SIMachineFunctionInfo::hasWorkGroupIDZ(), llvm::SIMachineFunctionInfo::hasWorkGroupInfo(), llvm::SIMachineFunctionInfo::hasWorkItemIDX(), llvm::SIMachineFunctionInfo::hasWorkItemIDY(), llvm::SIMachineFunctionInfo::hasWorkItemIDZ(), llvm::MVT::i16, Info, llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::AMDGPUSubtarget::isAmdPalOS(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::AMDGPU::isEntryFunctionCC(), llvm::AMDGPU::isKernel(), llvm::CCValAssign::isMemLoc(), llvm::ISD::InputArg::isOrigArg(), llvm::SIMachineFunctionInfo::isPSInputAllocated(), llvm::CCValAssign::isRegLoc(), llvm::AMDGPU::isShader(), llvm::ISD::ArgFlagsTy::isSRet(), llvm_unreachable, AMDGPUAS::LOCAL_ADDRESS, llvm::SIMachineFunctionInfo::markPSInputAllocated(), llvm::SIMachineFunctionInfo::markPSInputEnabled(), llvm::MinAlign(), llvm::MVT::Other, processShaderInputArgs(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, AMDGPUAS::REGION_ADDRESS, llvm::SIMachineFunctionInfo::setBytesInStackArgArea(), llvm::AMDGPUArgumentUsageInfo::setFuncArgInfo(), llvm::CCValAssign::SExt, llvm::SmallVectorBase::size(), llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, llvm::ISD::TokenFactor, TRI, llvm::ISD::TRUNCATE, llvm::ISD::InputArg::VT, llvm::ZB_Undefined, and llvm::CCValAssign::ZExt.
Referenced by isFlatGlobalAddrSpace().
LowerOperation()
SDValue SITargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 4035 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDRSPACECAST, assert(), llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::BRCOND, llvm::ISD::BUILD_VECTOR, llvm::ISD::DEBUGTRAP, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FMA, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP_ROUND, llvm::ISD::FSIN, llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::LOAD, llvm::AMDGPUTargetLowering::LowerOperation(), llvm::ISD::MUL, llvm::ISD::RETURNADDR, llvm::ISD::SELECT, llvm::ISD::SHL, llvm::ISD::SMAX, llvm::ISD::SMIN, splitBinaryVectorOp(), splitTernaryVectorOp(), splitUnaryVectorOp(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::TRAP, llvm::ISD::UMAX, llvm::ISD::UMIN, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by isFlatGlobalAddrSpace().
LowerReturn()
SDValue SITargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , const SDLoc & , SelectionDAG &) const override virtual
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
The implementation should return the resulting token chain value.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 2269 of file SIISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::CCState::AnalyzeReturn(), llvm::ISD::ANY_EXTEND, Arg, assert(), llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::AMDGPUTargetLowering::CCAssignFnForReturn(), contains(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), E, llvm::SmallVectorBase::empty(), llvm::AMDGPUISD::ENDPGM, llvm::CCValAssign::Full, llvm::SIRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::MachineFunction::getInfo(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIRegisterInfo::getReturnAddressReg(), getSubtarget(), llvm::SDValue::getValue(), I, llvm::MVT::i32, llvm::MVT::i64, Info, llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::AMDGPU::isKernel(), llvm::CCValAssign::isRegLoc(), llvm::AMDGPU::isShader(), llvm_unreachable, llvm::AMDGPUTargetLowering::LowerReturn(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::AMDGPUISD::RET_FLAG, llvm::AMDGPUISD::RETURN_TO_EPILOG, llvm::SIMachineFunctionInfo::returnsVoid(), llvm::SIMachineFunctionInfo::setIfReturnsVoid(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase::size(), TRI, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by isFlatGlobalAddrSpace().
mayBeEmittedAsTailCall()
bool SITargetLowering::mayBeEmittedAsTailCall (const CallInst *) const override virtual
Return true if the target may be able emit the call instruction as a tail call.
This is used by optimization passes to determine if it's profitable to duplicate return instructions to enable tailcall optimization.
Reimplemented from llvm::TargetLowering.
Definition at line 2665 of file SIISelLowering.cpp.
References llvm::Function::getCallingConv(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::AMDGPU::isEntryFunctionCC(), and llvm::CallInst::isTailCall().
Referenced by isFlatGlobalAddrSpace().
passSpecialInputs()
void SITargetLowering::passSpecialInputs (CallLoweringInfo & CLI, CCState & CCInfo, const SIMachineFunctionInfo & Info, SmallVectorImpl< std::pair< unsigned, SDValue >> & RegsToPass, SmallVectorImpl< SDValue > & MemOpChains, SDValue Chain) const
Definition at line 2436 of file SIISelLowering.cpp.
References llvm::CCState::AllocateStack(), assert(), llvm::ArgDescriptor::createArg(), llvm::TargetLowering::CallLoweringInfo::CS, llvm::TargetLowering::CallLoweringInfo::DAG, llvm::AMDGPUFunctionArgInfo::DISPATCH_ID, llvm::AMDGPUFunctionArgInfo::DISPATCH_PTR, llvm::TargetLowering::CallLoweringInfo::DL, llvm::Pass::getAnalysis(), llvm::SIMachineFunctionInfo::getArgInfo(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getPass(), llvm::AMDGPUFunctionArgInfo::getPreloadedValue(), llvm::ArgDescriptor::getRegister(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SelectionDAG::getShiftAmountConstant(), llvm::EVT::getStoreSize(), llvm::MVT::i32, llvm::MVT::i64, llvm::AMDGPUFunctionArgInfo::IMPLICIT_ARG_PTR, llvm::ArgDescriptor::isMasked(), llvm::ArgDescriptor::isRegister(), llvm::AMDGPUFunctionArgInfo::KERNARG_SEGMENT_PTR, llvm::AMDGPUTargetLowering::loadInputValue(), llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::AMDGPUFunctionArgInfo::QUEUE_PTR, llvm::ISD::SHL, llvm::AMDGPUTargetLowering::storeStackInputValue(), TRI, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_X, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Y, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Z, llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_X, llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_Y, llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_Z, Y, and llvm::Z.
Referenced by isFlatGlobalAddrSpace(), and LowerCall().
PerformDAGCombine()
SDValue SITargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const override virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 9983 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDCARRY, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::AMDGPUISD::ATOMIC_DEC, llvm::AMDGPUISD::ATOMIC_INC, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_FADD, llvm::AMDGPUISD::ATOMIC_LOAD_FMAX, llvm::AMDGPUISD::ATOMIC_LOAD_FMIN, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::AMDGPUISD::CLAMP, llvm::AMDGPUISD::CVT_F32_UBYTE0, llvm::AMDGPUISD::CVT_F32_UBYTE1, llvm::AMDGPUISD::CVT_F32_UBYTE2, llvm::AMDGPUISD::CVT_F32_UBYTE3, llvm::AMDGPUISD::CVT_PKRTZ_F16_F32, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MipsISD::Ext, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f16, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FMA, llvm::AMDGPUISD::FMAX_LEGACY, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN_LEGACY, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::AMDGPUISD::FP_CLASS, llvm::AMDGPUISD::FRACT, llvm::ISD::FSUB, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::i16, llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::SDValue::isUndef(), llvm::AMDGPUISD::LDEXP, LLVM_FALLTHROUGH, llvm::ISD::LOAD, llvm::CodeGenOpt::None, llvm::ISD::OR, llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_IFLAG, llvm::AMDGPUISD::RCP_LEGACY, llvm::AMDGPUISD::RSQ, llvm::AMDGPUISD::RSQ_CLAMP, llvm::AMDGPUISD::RSQ_LEGACY, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SETCC, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::SUBCARRY, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::MVT::v2f16, llvm::MVT::v2i16, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by isFlatGlobalAddrSpace().
PostISelFolding()
SDNode * SITargetLowering::PostISelFolding (MachineSDNode * Node, SelectionDAG & DAG) const override virtual
Fold the instructions after selecting them.
Returns null if users were already updated.
Implements llvm::AMDGPUTargetLowering.
Definition at line 10343 of file SIISelLowering.cpp.
References llvm::GCNSubtarget::getInstrInfo(), llvm::SDNode::getMachineOpcode(), getSubtarget(), llvm::SIInstrInfo::isGather4(), llvm::SIInstrInfo::isMIMG(), legalizeTargetIndependentNode(), and TII.
Referenced by isFlatGlobalAddrSpace().
ReplaceNodeResults()
void SITargetLowering::ReplaceNodeResults (SDNode * , SmallVectorImpl< SDValue > & , SelectionDAG &) const override virtual
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all.
If the target has no operations that require custom lowering, it need not implement this. The default implementation aborts.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 4271 of file SIISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::EVT::bitsLT(), llvm::AMDGPUISD::CVT_PK_I16_I32, llvm::AMDGPUISD::CVT_PK_U16_U32, llvm::AMDGPUISD::CVT_PKNORM_I16_F32, llvm::AMDGPUISD::CVT_PKNORM_U16_F32, llvm::AMDGPUISD::CVT_PKRTZ_F16_F32, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FNEG, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLoweringBase::isTypeLegal(), llvm::ISD::MERGE_VALUES, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SELECT, llvm::ISD::TRUNCATE, llvm::MVT::v2f16, llvm::MVT::v2i16, and llvm::ISD::XOR.
Referenced by isFlatGlobalAddrSpace().
requiresUniformRegister()
bool SITargetLowering::requiresUniformRegister (MachineFunction & MF, const Value *) const override virtual
Allows target to decide about the register class of the specific value that is live outside the defining block.
Returns true if the value needs uniform register class.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11047 of file SIISelLowering.cpp.
References llvm::TargetLowering::ComputeConstraintToUse(), llvm::MachineFunction::getDataLayout(), getRegForInlineAsmConstraint(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), hasCFUser(), llvm::InlineAsm::isOutput, llvm::SIRegisterInfo::isSGPRClass(), llvm::SIRegisterInfo::isSGPRReg(), MRI, llvm::TargetLowering::ParseConstraints(), and llvm::ArrayRef< T >::size().
Referenced by isFlatGlobalAddrSpace().
shouldConvertConstantLoadToIntImm()
bool SITargetLowering::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const override virtual
Return true if it is beneficial to convert a load of a constant to just the constant itself.
On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1377 of file SIISelLowering.cpp.
Referenced by isFlatGlobalAddrSpace().
shouldEmitFixup()
bool SITargetLowering::shouldEmitFixup (const GlobalValue * GV) const
Returns
True if fixup needs to be emitted for given global value GV, false otherwise.
Definition at line 4432 of file SIISelLowering.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::GlobalValue::getAddressSpace(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetMachine::getTargetTriple(), llvm::AMDGPU::shouldEmitConstantsToTextSection(), and llvm::TT.
Referenced by buildPCRelGlobalAddress(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), shouldEmitGOTReloc(), and shouldEmitPCReloc().
shouldEmitGOTReloc()
bool SITargetLowering::shouldEmitGOTReloc (const GlobalValue * GV) const
Returns
True if GOT relocation needs to be emitted for given global value GV, false otherwise.
Definition at line 4439 of file SIISelLowering.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::GlobalValue::getAddressSpace(), llvm::GlobalValue::getParent(), llvm::TargetLoweringBase::getTargetMachine(), llvm::GlobalValue::getValueType(), AMDGPUAS::GLOBAL_ADDRESS, llvm::Type::isFunctionTy(), llvm::TargetMachine::shouldAssumeDSOLocal(), and shouldEmitFixup().
Referenced by isOffsetFoldingLegal(), and shouldEmitPCReloc().
shouldEmitPCReloc()
bool SITargetLowering::shouldEmitPCReloc (const GlobalValue * GV) const
Returns
True if PC-relative relocation needs to be emitted for given global value GV, false otherwise.
Definition at line 4450 of file SIISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::AfterLegalizeVectorOps, llvm::ISD::AND, llvm::SmallVectorImpl< T >::append(), assert(), llvm::AMDGPUISD::BFI, llvm::AMDGPUISD::BFM, llvm::ISD::BITCAST, llvm::EVT::bitsLE(), llvm::ISD::BR, llvm::ISD::BRCOND, llvm::ISD::BUILD_VECTOR, Concat, AMDGPUAS::CONSTANT_ADDRESS, llvm::ISD::CopyToReg, llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::LLVMContext::diagnose(), llvm::DS_Warning, llvm::dyn_cast(), llvm::numbers::e, llvm::AMDGPUISD::ENDPGM, llvm::TargetLowering::expandFMINNUM_FMAXNUM(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f16, llvm::MVT::f64, findUser(), AMDGPUAS::FLAT_ADDRESS, llvm::ISD::FP_EXTEND, llvm::ISD::FP_TO_FP16, llvm::ISD::FTRUNC, llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), llvm::Function::getContext(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SDValue::getDebugLoc(), llvm::SDLoc::getDebugLoc(), llvm::AddrSpaceCastSDNode::getDestAddressSpace(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMergeValues(), llvm::AMDGPUMachineFunction::getMode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::AMDGPUTargetMachine::getNullPointerValue(), llvm::SDNode::getNumValues(), llvm::SelectionDAG::getObjectPtrOffset(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SIMachineFunctionInfo::getQueuePtrUserSGPR(), getRegClassFor(), llvm::SelectionDAG::getRegister(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIRegisterInfo::getReturnAddressReg(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getSplatBuildVector(), llvm::AddrSpaceCastSDNode::getSrcAddressSpace(), getSubtarget(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTargetMachine(), llvm::GCNSubtarget::getTrapHandlerAbi(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::GCNSubtarget::hasApertureRegs(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::AMDGPU::Hwreg::ID_MEM_BASES, llvm::AMDGPU::Hwreg::ID_SHIFT_, llvm::AMDGPU::SIModeRegisterDefaults::IEEE, Info, llvm::MipsISD::Ins, llvm::ISD::INSERT_VECTOR_ELT, Intr, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::SDNode::isDivergent(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::isPowerOf2_32(), llvm::GCNSubtarget::isTrapHandlerEnabled(), AMDGPUAS::LOCAL_ADDRESS, llvm::Log2_32(), llvm::MinAlign(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::AMDGPU::Hwreg::OFFSET_SHIFT_, llvm::AMDGPU::Hwreg::OFFSET_SRC_PRIVATE_BASE, llvm::AMDGPU::Hwreg::OFFSET_SRC_SHARED_BASE, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::ISD::OR, llvm::MVT::Other, AMDGPUAS::PRIVATE_ADDRESS, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SETNE, llvm::MachineFrameInfo::setReturnAddressIsTaken(), llvm::ISD::SHL, shouldEmitFixup(), shouldEmitGOTReloc(), splitBinaryVectorOp(), llvm::ISD::SRL, llvm::AMDGPUISD::TRAP, llvm::GCNSubtarget::TrapHandlerAbiHsa, llvm::GCNSubtarget::TrapIDLLVMDebugTrap, llvm::GCNSubtarget::TrapIDLLVMTrap, TRI, llvm::ISD::TRUNCATE, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v4f16, llvm::SDNode::value_begin(), llvm::SDNode::value_end(), llvm::AMDGPU::Hwreg::WIDTH_M1_SHIFT_, llvm::AMDGPU::Hwreg::WIDTH_M1_SRC_PRIVATE_BASE, and llvm::AMDGPU::Hwreg::WIDTH_M1_SRC_SHARED_BASE.
Referenced by buildPCRelGlobalAddress(), and llvm::AMDGPULegalizerInfo::legalizeGlobalValue().
shouldExpandAtomicRMWInIR()
TargetLowering::AtomicExpansionKind SITargetLowering::shouldExpandAtomicRMWInIR (AtomicRMWInst * RMW) const override virtual
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Default is to never expand.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 10961 of file SIISelLowering.cpp.
References llvm::TargetLoweringBase::CmpXChg, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::getOperation(), llvm::AtomicRMWInst::getPointerAddressSpace(), llvm::Value::getType(), AMDGPUAS::GLOBAL_ADDRESS, llvm::GCNSubtarget::hasAtomicFaddInsts(), llvm::GCNSubtarget::hasLDSFPAtomics(), llvm::Type::isFloatTy(), llvm::Type::isHalfTy(), AMDGPUAS::LOCAL_ADDRESS, llvm::TargetLoweringBase::None, llvm::AMDGPUTargetLowering::shouldExpandAtomicRMWInIR(), and llvm::Value::use_empty().
Referenced by isFlatGlobalAddrSpace().
splitBinaryVectorOp()
SDValue SITargetLowering::splitBinaryVectorOp (SDValue Op, SelectionDAG & DAG) const
Definition at line 3990 of file SIISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::SDNode::getFlags(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getValueType(), llvm::SelectionDAG::SplitVectorOperand(), llvm::MVT::v4f16, and llvm::MVT::v4i16.
Referenced by isFlatGlobalAddrSpace(), LowerOperation(), and shouldEmitPCReloc().
splitKillBlock()
MachineBasicBlock * SITargetLowering::splitKillBlock (MachineInstr & MI, MachineBasicBlock * BB) const
Definition at line 3036 of file SIISelLowering.cpp.
References llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), llvm::GCNSubtarget::getInstrInfo(), llvm::SIInstrInfo::getKillTerminatorFromPseudo(), llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), getSubtarget(), llvm::MachineFunction::insert(), llvm::MachineInstr::setDesc(), llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter(), and isFlatGlobalAddrSpace().
splitTernaryVectorOp()
SDValue SITargetLowering::splitTernaryVectorOp (SDValue Op, SelectionDAG & DAG) const
Definition at line 4011 of file SIISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::SDNode::getFlags(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getValueType(), llvm::SelectionDAG::SplitVectorOperand(), llvm::MVT::v4f16, and llvm::MVT::v4i16.
Referenced by isFlatGlobalAddrSpace(), and LowerOperation().
splitUnaryVectorOp()
SDValue SITargetLowering::splitUnaryVectorOp (SDValue Op, SelectionDAG & DAG) const
Definition at line 3970 of file SIISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::SDNode::getFlags(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getValueType(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, llvm::SelectionDAG::SplitVectorOperand(), and llvm::MVT::v4f16.
Referenced by isFlatGlobalAddrSpace(), and LowerOperation().
supportSplitCSR()
bool SITargetLowering::supportSplitCSR (MachineFunction * MF) const override virtual
Return true if the target supports that a subset of CSRs for the given machine function is handled explicitly via copies.
Reimplemented from llvm::TargetLowering.
Definition at line 1983 of file SIISelLowering.cpp.
References llvm::MachineFunction::getInfo(), Info, and llvm::AMDGPUMachineFunction::isEntryFunction().
Referenced by isFlatGlobalAddrSpace().
wrapAddr64Rsrc()
MachineSDNode * SITargetLowering::wrapAddr64Rsrc (SelectionDAG & DAG, const SDLoc & DL, SDValue Ptr) const
Definition at line 10520 of file SIISelLowering.cpp.
References buildSMovImm32(), llvm::SIInstrInfo::getDefaultRsrcDataFormat(), llvm::GCNSubtarget::getInstrInfo(), llvm::SelectionDAG::getMachineNode(), getSubtarget(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, TII, llvm::MVT::v2i32, and llvm::MVT::v4i32.
Referenced by isFlatGlobalAddrSpace(), and selectSGPRVectorRegClassID().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIISelLowering.h
lib/Target/AMDGPU/SIISelLowering.cpp