LLVM: llvm::MCLabel Class Reference
llvm::MCLabel Class Reference
Instances of this class represent a label name in the MC file, and MCLabel are created and uniqued by the MCContext class.
#include "llvm/MC/MCLabel.h"
Public Member Functions
MCLabel (const MCLabel &)=delete
MCLabel & operator= (const MCLabel &)=delete
unsigned getInstance () const
Get the current instance of this Directional Local Label.
unsigned incInstance ()
Increment the current instance of this Directional Local Label.
void print (raw_ostream &OS) const
Print the value to the stream OS.
void dump () const
Print the value to stderr.
Friends
class MCContext
Detailed Description
Instances of this class represent a label name in the MC file, and MCLabel are created and uniqued by the MCContext class.
MCLabel should only be constructed for valid instances in the object file.
Definition at line 23 of file MCLabel.h.
Constructor & Destructor Documentation
MCLabel()
llvm::MCLabel::MCLabel (const MCLabel &) delete
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MCLabel::dump () const
Print the value to stderr.
Definition at line 22 of file MCLabel.cpp.
References llvm::dbgs(), and print().
Referenced by incInstance().
getInstance()
unsigned llvm::MCLabel::getInstance () const inline
Get the current instance of this Directional Local Label.
Definition at line 37 of file MCLabel.h.
Referenced by llvm::MCContext::createTempSymbol(), and print().
incInstance()
unsigned llvm::MCLabel::incInstance () inline
Increment the current instance of this Directional Local Label.
Definition at line 40 of file MCLabel.h.
References dump(), and print().
Referenced by llvm::MCContext::createTempSymbol().
operator=()
MCLabel& llvm::MCLabel::operator= (const MCLabel &) delete
print()
void MCLabel::print (raw_ostream & OS) const
Print the value to the stream OS.
Definition at line 17 of file MCLabel.cpp.
References getInstance().
Referenced by dump(), incInstance(), and llvm::operator<<().
Friends And Related Function Documentation
MCContext
friend class MCContext friend
Definition at line 28 of file MCLabel.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCLabel.h
lib/MC/MCLabel.cpp