LLVM: llvm::pdb::IPDBSession Class Reference
llvm::pdb::IPDBSession Class Reference abstract
IPDBSession defines an interface used to provide a context for querying debug information from a debug data source (for example, a PDB).
#include "llvm/DebugInfo/PDB/IPDBSession.h"
Public Member Functions
virtual ~IPDBSession ()
virtual uint64_t getLoadAddress () const =0
virtual bool setLoadAddress (uint64_t Address)=0
virtual std::unique_ptr< PDBSymbolExe > getGlobalScope ()=0
virtual std::unique_ptr< PDBSymbol > getSymbolById (SymIndexId SymbolId) const =0
virtual bool addressForVA (uint64_t VA, uint32_t &Section, uint32_t &Offset) const =0
virtual bool addressForRVA (uint32_t RVA, uint32_t &Section, uint32_t &Offset) const =0
template<typename T >
std::unique_ptr< T > getConcreteSymbolById (SymIndexId SymbolId) const
virtual std::unique_ptr< PDBSymbol > findSymbolByAddress (uint64_t Address, PDB_SymType Type) const =0
virtual std::unique_ptr< PDBSymbol > findSymbolByRVA (uint32_t RVA, PDB_SymType Type) const =0
virtual std::unique_ptr< PDBSymbol > findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbers (const PDBSymbolCompiland &Compiland, const IPDBSourceFile &File) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByAddress (uint64_t Address, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > findSourceFiles (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBSourceFile > findOneSourceFile (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< PDBSymbolCompiland > findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > getAllSourceFiles () const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > getSourceFilesForCompiland (const PDBSymbolCompiland &Compiland) const =0
virtual std::unique_ptr< IPDBSourceFile > getSourceFileById (uint32_t FileId) const =0
virtual std::unique_ptr< IPDBEnumDataStreams > getDebugStreams () const =0
virtual std::unique_ptr< IPDBEnumTables > getEnumTables () const =0
virtual std::unique_ptr< IPDBEnumInjectedSources > getInjectedSources () const =0
virtual std::unique_ptr< IPDBEnumSectionContribs > getSectionContribs () const =0
virtual std::unique_ptr< IPDBEnumFrameData > getFrameData () const =0
Detailed Description
IPDBSession defines an interface used to provide a context for querying debug information from a debug data source (for example, a PDB).
Definition at line 25 of file IPDBSession.h.
Constructor & Destructor Documentation
~IPDBSession()
IPDBSession::~IPDBSession () virtual default
Member Function Documentation
addressForRVA()
virtual bool llvm::pdb::IPDBSession::addressForRVA (uint32_t RVA, uint32_t & Section, uint32_t & Offset) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by llvm::pdb::PDBSymbolData::getCompilandId().
addressForVA()
virtual bool llvm::pdb::IPDBSession::addressForVA (uint64_t VA, uint32_t & Section, uint32_t & Offset) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
findCompilandsForSourceFile()
virtual std::unique_ptr<IPDBEnumChildren<PDBSymbolCompiland> > llvm::pdb::IPDBSession::findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
findLineNumbers()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBSession::findLineNumbers (const PDBSymbolCompiland & Compiland, const IPDBSourceFile & File) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
findLineNumbersByAddress()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBSession::findLineNumbersByAddress (uint64_t Address, uint32_t Length) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
findLineNumbersByRVA()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBSession::findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById(), and llvm::pdb::PDBSymbolData::getLineNumbers().
findLineNumbersBySectOffset()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBSession::findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById(), and llvm::pdb::PDBSymbolData::getLineNumbers().
findOneCompilandForSourceFile()
virtual std::unique_ptr<PDBSymbolCompiland> llvm::pdb::IPDBSession::findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
findOneSourceFile()
virtual std::unique_ptr<IPDBSourceFile> llvm::pdb::IPDBSession::findOneSourceFile (const PDBSymbolCompiland * Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById(), and llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath().
findSourceFiles()
virtual std::unique_ptr<IPDBEnumSourceFiles> llvm::pdb::IPDBSession::findSourceFiles (const PDBSymbolCompiland * Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
findSymbolByAddress()
virtual std::unique_ptr<PDBSymbol> llvm::pdb::IPDBSession::findSymbolByAddress (uint64_t Address, PDB_SymType Type) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
findSymbolByRVA()
virtual std::unique_ptr<PDBSymbol> llvm::pdb::IPDBSession::findSymbolByRVA (uint32_t RVA, PDB_SymType Type) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
findSymbolBySectOffset()
virtual std::unique_ptr<PDBSymbol> llvm::pdb::IPDBSession::findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
getAllSourceFiles()
virtual std::unique_ptr<IPDBEnumSourceFiles> llvm::pdb::IPDBSession::getAllSourceFiles () const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
getConcreteSymbolById()
template<typename T > std::unique_ptr<T> llvm::pdb::IPDBSession::getConcreteSymbolById (SymIndexId SymbolId) const inline
Definition at line 41 of file IPDBSession.h.
References llvm::pdb::Compiland, File, findCompilandsForSourceFile(), findLineNumbers(), findLineNumbersByAddress(), findLineNumbersByRVA(), findLineNumbersBySectOffset(), findOneCompilandForSourceFile(), findOneSourceFile(), findSourceFiles(), findSymbolByAddress(), findSymbolByRVA(), findSymbolBySectOffset(), getAllSourceFiles(), getDebugStreams(), getEnumTables(), getFrameData(), getInjectedSources(), getSectionContribs(), getSourceFileById(), getSourceFilesForCompiland(), and getSymbolById().
Referenced by llvm::pdb::NativeTypeEnum::getLength(), and llvm::pdb::SymbolCache::getOrCreateCompiland().
getDebugStreams()
virtual std::unique_ptr<IPDBEnumDataStreams> llvm::pdb::IPDBSession::getDebugStreams () const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
getEnumTables()
virtual std::unique_ptr<IPDBEnumTables> llvm::pdb::IPDBSession::getEnumTables () const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
getFrameData()
virtual std::unique_ptr<IPDBEnumFrameData> llvm::pdb::IPDBSession::getFrameData () const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
getGlobalScope()
virtual std::unique_ptr<PDBSymbolExe> llvm::pdb::IPDBSession::getGlobalScope () pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
getInjectedSources()
virtual std::unique_ptr<IPDBEnumInjectedSources> llvm::pdb::IPDBSession::getInjectedSources () const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
getLoadAddress()
virtual uint64_t llvm::pdb::IPDBSession::getLoadAddress () const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
getSectionContribs()
virtual std::unique_ptr<IPDBEnumSectionContribs> llvm::pdb::IPDBSession::getSectionContribs () const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by llvm::pdb::PDBSymbolData::getCompilandId(), and getConcreteSymbolById().
getSourceFileById()
virtual std::unique_ptr<IPDBSourceFile> llvm::pdb::IPDBSession::getSourceFileById (uint32_t FileId) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById().
getSourceFilesForCompiland()
virtual std::unique_ptr<IPDBEnumSourceFiles> llvm::pdb::IPDBSession::getSourceFilesForCompiland (const PDBSymbolCompiland & Compiland) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by getConcreteSymbolById(), and llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath().
getSymbolById()
virtual std::unique_ptr<PDBSymbol> llvm::pdb::IPDBSession::getSymbolById (SymIndexId SymbolId) const pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
Referenced by llvm::pdb::dumpSymbolIdField(), llvm::pdb::PDBSymbolData::getCompilandId(), getConcreteSymbolById(), llvm::pdb::PDBSymbol::getSymbolByIdHelper(), and getSymbolType().
setLoadAddress()
virtual bool llvm::pdb::IPDBSession::setLoadAddress (uint64_t Address) pure virtual
Implemented in llvm::pdb::NativeSession, and llvm::pdb::DIASession.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/IPDBSession.h
lib/DebugInfo/PDB/PDBInterfaceAnchors.cpp