LLVM: llvm::MCGenDwarfLabelEntry Class Reference
llvm::MCGenDwarfLabelEntry Class Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
MCGenDwarfLabelEntry (StringRef name, unsigned fileNumber, unsigned lineNumber, MCSymbol *label)
StringRef getName () const
unsigned getFileNumber () const
unsigned getLineNumber () const
MCSymbol * getLabel () const
Static Public Member Functions
static void Make (MCSymbol *Symbol, MCStreamer *MCOS, SourceMgr &SrcMgr, SMLoc &Loc)
Detailed Description
Definition at line 407 of file MCDwarf.h.
Constructor & Destructor Documentation
MCGenDwarfLabelEntry()
llvm::MCGenDwarfLabelEntry::MCGenDwarfLabelEntry (StringRef name, unsigned fileNumber, unsigned lineNumber, MCSymbol * label) inline
Definition at line 419 of file MCDwarf.h.
Member Function Documentation
getFileNumber()
unsigned llvm::MCGenDwarfLabelEntry::getFileNumber () const inline
Definition at line 425 of file MCDwarf.h.
getLabel()
MCSymbol* llvm::MCGenDwarfLabelEntry::getLabel () const inline
Definition at line 427 of file MCDwarf.h.
References llvm::SrcMgr, and llvm::ARMBuildAttrs::Symbol.
getLineNumber()
unsigned llvm::MCGenDwarfLabelEntry::getLineNumber () const inline
Definition at line 426 of file MCDwarf.h.
getName()
StringRef llvm::MCGenDwarfLabelEntry::getName () const inline
Definition at line 424 of file MCDwarf.h.
References llvm::MCDwarfFile::Name.
Make()
void MCGenDwarfLabelEntry::Make (MCSymbol * Symbol, MCStreamer * MCOS, SourceMgr & SrcMgr, SMLoc & Loc) static
Definition at line 1207 of file MCDwarf.cpp.
References llvm::MCContext::addMCGenDwarfLabelEntry(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::SourceMgr::FindBufferContainingLoc(), llvm::SourceMgr::FindLineNumber(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCContext::getGenDwarfFileNumber(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCSymbol::getName(), llvm::MCSymbol::isTemporary(), Name, llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by getGNUBinOpPrecedence().
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp