LLVM: llvm::pdb::IPDBRawSymbol Class Reference
llvm::pdb::IPDBRawSymbol Class Reference abstract
IPDBRawSymbol defines an interface used to represent an arbitrary symbol.
#include "llvm/DebugInfo/PDB/IPDBRawSymbol.h"
Public Member Functions
virtual ~IPDBRawSymbol ()
virtual void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByVA (uint64_t VA) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLines () const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByVA (uint64_t VA, uint32_t Length) const =0
virtual void getDataBytes (llvm::SmallVector< uint8_t, 32 > &bytes) const =0
virtual void getBackEndVersion (VersionInfo &Version) const =0
virtual PDB_MemberAccess getAccess () const =0
virtual uint32_t getAddressOffset () const =0
virtual uint32_t getAddressSection () const =0
virtual uint32_t getAge () const =0
virtual SymIndexId getArrayIndexTypeId () const =0
virtual uint32_t getBaseDataOffset () const =0
virtual uint32_t getBaseDataSlot () const =0
virtual SymIndexId getBaseSymbolId () const =0
virtual PDB_BuiltinType getBuiltinType () const =0
virtual uint32_t getBitPosition () const =0
virtual PDB_CallingConv getCallingConvention () const =0
virtual SymIndexId getClassParentId () const =0
virtual std::string getCompilerName () const =0
virtual uint32_t getCount () const =0
virtual uint32_t getCountLiveRanges () const =0
virtual void getFrontEndVersion (VersionInfo &Version) const =0
virtual PDB_Lang getLanguage () const =0
virtual SymIndexId getLexicalParentId () const =0
virtual std::string getLibraryName () const =0
virtual uint32_t getLiveRangeStartAddressOffset () const =0
virtual uint32_t getLiveRangeStartAddressSection () const =0
virtual uint32_t getLiveRangeStartRelativeVirtualAddress () const =0
virtual codeview::RegisterId getLocalBasePointerRegisterId () const =0
virtual SymIndexId getLowerBoundId () const =0
virtual uint32_t getMemorySpaceKind () const =0
virtual std::string getName () const =0
virtual uint32_t getNumberOfAcceleratorPointerTags () const =0
virtual uint32_t getNumberOfColumns () const =0
virtual uint32_t getNumberOfModifiers () const =0
virtual uint32_t getNumberOfRegisterIndices () const =0
virtual uint32_t getNumberOfRows () const =0
virtual std::string getObjectFileName () const =0
virtual uint32_t getOemId () const =0
virtual SymIndexId getOemSymbolId () const =0
virtual uint32_t getOffsetInUdt () const =0
virtual PDB_Cpu getPlatform () const =0
virtual uint32_t getRank () const =0
virtual codeview::RegisterId getRegisterId () const =0
virtual uint32_t getRegisterType () const =0
virtual uint32_t getRelativeVirtualAddress () const =0
virtual uint32_t getSamplerSlot () const =0
virtual uint32_t getSignature () const =0
virtual uint32_t getSizeInUdt () const =0
virtual uint32_t getSlot () const =0
virtual std::string getSourceFileName () const =0
virtual std::unique_ptr< IPDBLineNumber > getSrcLineOnTypeDefn () const =0
virtual uint32_t getStride () const =0
virtual SymIndexId getSubTypeId () const =0
virtual std::string getSymbolsFileName () const =0
virtual SymIndexId getSymIndexId () const =0
virtual uint32_t getTargetOffset () const =0
virtual uint32_t getTargetRelativeVirtualAddress () const =0
virtual uint64_t getTargetVirtualAddress () const =0
virtual uint32_t getTargetSection () const =0
virtual uint32_t getTextureSlot () const =0
virtual uint32_t getTimeStamp () const =0
virtual uint32_t getToken () const =0
virtual SymIndexId getTypeId () const =0
virtual uint32_t getUavSlot () const =0
virtual std::string getUndecoratedName () const =0
virtual std::string getUndecoratedNameEx (PDB_UndnameFlags Flags) const =0
virtual SymIndexId getUnmodifiedTypeId () const =0
virtual SymIndexId getUpperBoundId () const =0
virtual Variant getValue () const =0
virtual uint32_t getVirtualBaseDispIndex () const =0
virtual uint32_t getVirtualBaseOffset () const =0
virtual std::unique_ptr< PDBSymbolTypeBuiltin > getVirtualBaseTableType () const =0
virtual SymIndexId getVirtualTableShapeId () const =0
virtual PDB_DataKind getDataKind () const =0
virtual PDB_SymType getSymTag () const =0
virtual codeview::GUID getGuid () const =0
virtual int32_t getOffset () const =0
virtual int32_t getThisAdjust () const =0
virtual int32_t getVirtualBasePointerOffset () const =0
virtual PDB_LocType getLocationType () const =0
virtual PDB_Machine getMachineType () const =0
virtual codeview::ThunkOrdinal getThunkOrdinal () const =0
virtual uint64_t getLength () const =0
virtual uint64_t getLiveRangeLength () const =0
virtual uint64_t getVirtualAddress () const =0
virtual PDB_UdtType getUdtKind () const =0
virtual bool hasConstructor () const =0
virtual bool hasCustomCallingConvention () const =0
virtual bool hasFarReturn () const =0
virtual bool isCode () const =0
virtual bool isCompilerGenerated () const =0
virtual bool isConstType () const =0
virtual bool isEditAndContinueEnabled () const =0
virtual bool isFunction () const =0
virtual bool getAddressTaken () const =0
virtual bool getNoStackOrdering () const =0
virtual bool hasAlloca () const =0
virtual bool hasAssignmentOperator () const =0
virtual bool hasCTypes () const =0
virtual bool hasCastOperator () const =0
virtual bool hasDebugInfo () const =0
virtual bool hasEH () const =0
virtual bool hasEHa () const =0
virtual bool hasFramePointer () const =0
virtual bool hasInlAsm () const =0
virtual bool hasInlineAttribute () const =0
virtual bool hasInterruptReturn () const =0
virtual bool hasLongJump () const =0
virtual bool hasManagedCode () const =0
virtual bool hasNestedTypes () const =0
virtual bool hasNoInlineAttribute () const =0
virtual bool hasNoReturnAttribute () const =0
virtual bool hasOptimizedCodeDebugInfo () const =0
virtual bool hasOverloadedOperator () const =0
virtual bool hasSEH () const =0
virtual bool hasSecurityChecks () const =0
virtual bool hasSetJump () const =0
virtual bool hasStrictGSCheck () const =0
virtual bool isAcceleratorGroupSharedLocal () const =0
virtual bool isAcceleratorPointerTagLiveRange () const =0
virtual bool isAcceleratorStubFunction () const =0
virtual bool isAggregated () const =0
virtual bool isIntroVirtualFunction () const =0
virtual bool isCVTCIL () const =0
virtual bool isConstructorVirtualBase () const =0
virtual bool isCxxReturnUdt () const =0
virtual bool isDataAligned () const =0
virtual bool isHLSLData () const =0
virtual bool isHotpatchable () const =0
virtual bool isIndirectVirtualBaseClass () const =0
virtual bool isInterfaceUdt () const =0
virtual bool isIntrinsic () const =0
virtual bool isLTCG () const =0
virtual bool isLocationControlFlowDependent () const =0
virtual bool isMSILNetmodule () const =0
virtual bool isMatrixRowMajor () const =0
virtual bool isManagedCode () const =0
virtual bool isMSILCode () const =0
virtual bool isMultipleInheritance () const =0
virtual bool isNaked () const =0
virtual bool isNested () const =0
virtual bool isOptimizedAway () const =0
virtual bool isPacked () const =0
virtual bool isPointerBasedOnSymbolValue () const =0
virtual bool isPointerToDataMember () const =0
virtual bool isPointerToMemberFunction () const =0
virtual bool isPureVirtual () const =0
virtual bool isRValueReference () const =0
virtual bool isRefUdt () const =0
virtual bool isReference () const =0
virtual bool isRestrictedType () const =0
virtual bool isReturnValue () const =0
virtual bool isSafeBuffers () const =0
virtual bool isScoped () const =0
virtual bool isSdl () const =0
virtual bool isSingleInheritance () const =0
virtual bool isSplitted () const =0
virtual bool isStatic () const =0
virtual bool hasPrivateSymbols () const =0
virtual bool isUnalignedType () const =0
virtual bool isUnreached () const =0
virtual bool isValueUdt () const =0
virtual bool isVirtual () const =0
virtual bool isVirtualBaseClass () const =0
virtual bool isVirtualInheritance () const =0
virtual bool isVolatileType () const =0
virtual bool wasInlined () const =0
virtual std::string getUnused () const =0
Detailed Description
IPDBRawSymbol defines an interface used to represent an arbitrary symbol.
It exposes a monolithic interface consisting of accessors for the union of all properties that are valid for any symbol type. This interface is then wrapped by a concrete class which exposes only those set of methods valid for this particular symbol type. See PDBSymbol.h for more details.
Definition at line 49 of file IPDBRawSymbol.h.
Constructor & Destructor Documentation
~IPDBRawSymbol()
IPDBRawSymbol::~IPDBRawSymbol () virtual default
Member Function Documentation
dump()
virtual void llvm::pdb::IPDBRawSymbol::dump (raw_ostream & OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const pure virtual
Implemented in llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypePointer, llvm::pdb::NativeRawSymbol, llvm::pdb::NativeTypeVTShape, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypeArray, llvm::pdb::NativeTypeBuiltin, llvm::pdb::NativeTypeTypedef, llvm::pdb::NativeCompilandSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbol::defaultDump().
findChildren() [1/2]
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findChildren (PDB_SymType Type) const pure virtual
Implemented in llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeExeSymbol.
Referenced by llvm::pdb::PDBSymbol::findAllChildren(), and llvm::pdb::PDBSymbol::findChildren().
findChildren() [2/2]
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findChildrenByAddr()
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findChildrenByRVA()
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbol::findChildrenByRVA().
findChildrenByVA()
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findInlineeLines()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBRawSymbol::findInlineeLines () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findInlineeLinesByAddr()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBRawSymbol::findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findInlineeLinesByRVA()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBRawSymbol::findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findInlineeLinesByVA()
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::pdb::IPDBRawSymbol::findInlineeLinesByVA (uint64_t VA, uint32_t Length) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findInlineFramesByAddr()
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
findInlineFramesByRVA()
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findInlineFramesByRVA (uint32_t RVA) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbol::findInlineFramesByRVA().
findInlineFramesByVA()
virtual std::unique_ptr<IPDBEnumSymbols> llvm::pdb::IPDBRawSymbol::findInlineFramesByVA (uint64_t VA) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getAccess()
virtual PDB_MemberAccess llvm::pdb::IPDBRawSymbol::getAccess () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getAddressOffset()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getAddressOffset () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbolData::getCompilandId(), and llvm::pdb::PDBSymbolData::getLineNumbers().
getAddressSection()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getAddressSection () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbolData::getCompilandId(), and llvm::pdb::PDBSymbolData::getLineNumbers().
getAddressTaken()
virtual bool llvm::pdb::IPDBRawSymbol::getAddressTaken () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getAge()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getAge () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeExeSymbol.
getArrayIndexTypeId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getArrayIndexTypeId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypeArray.
getBackEndVersion()
virtual void llvm::pdb::IPDBRawSymbol::getBackEndVersion (VersionInfo & Version) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbolCompilandDetails::getBackEndVersion().
getBaseDataOffset()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getBaseDataOffset () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getBaseDataSlot()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getBaseDataSlot () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getBaseSymbolId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getBaseSymbolId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getBitPosition()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getBitPosition () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getBuiltinType()
virtual PDB_BuiltinType llvm::pdb::IPDBRawSymbol::getBuiltinType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeBuiltin.
getCallingConvention()
virtual PDB_CallingConv llvm::pdb::IPDBRawSymbol::getCallingConvention () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypeFunctionSig.
getClassParentId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getClassParentId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypePointer, and llvm::pdb::NativeSymbolEnumerator.
getCompilerName()
virtual std::string llvm::pdb::IPDBRawSymbol::getCompilerName () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getCount()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getCount () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
getCountLiveRanges()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getCountLiveRanges () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getDataBytes()
virtual void llvm::pdb::IPDBRawSymbol::getDataBytes (llvm::SmallVector< uint8_t, 32 > & bytes) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbolCustom::getDataBytes().
getDataKind()
virtual PDB_DataKind llvm::pdb::IPDBRawSymbol::getDataKind () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeSymbolEnumerator.
getFrontEndVersion()
virtual void llvm::pdb::IPDBRawSymbol::getFrontEndVersion (VersionInfo & Version) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbolCompilandDetails::getFrontEndVersion().
getGuid()
virtual codeview::GUID llvm::pdb::IPDBRawSymbol::getGuid () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeExeSymbol.
getLanguage()
virtual PDB_Lang llvm::pdb::IPDBRawSymbol::getLanguage () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getLength()
virtual uint64_t llvm::pdb::IPDBRawSymbol::getLength () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeArray, llvm::pdb::NativeTypePointer, and llvm::pdb::NativeTypeBuiltin.
Referenced by llvm::pdb::PDBSymbolData::getLineNumbers(), and getTypeLength().
getLexicalParentId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getLexicalParentId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeSymbolEnumerator, and llvm::pdb::NativeCompilandSymbol.
Referenced by llvm::pdb::PDBSymbolData::getCompilandId().
getLibraryName()
virtual std::string llvm::pdb::IPDBRawSymbol::getLibraryName () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeCompilandSymbol.
getLiveRangeLength()
virtual uint64_t llvm::pdb::IPDBRawSymbol::getLiveRangeLength () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getLiveRangeStartAddressOffset()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getLiveRangeStartAddressOffset () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getLiveRangeStartAddressSection()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getLiveRangeStartAddressSection () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getLiveRangeStartRelativeVirtualAddress()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getLiveRangeStartRelativeVirtualAddress () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getLocalBasePointerRegisterId()
virtual codeview::RegisterId llvm::pdb::IPDBRawSymbol::getLocalBasePointerRegisterId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getLocationType()
virtual PDB_LocType llvm::pdb::IPDBRawSymbol::getLocationType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeSymbolEnumerator.
getLowerBoundId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getLowerBoundId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getMachineType()
virtual PDB_Machine llvm::pdb::IPDBRawSymbol::getMachineType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getMemorySpaceKind()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getMemorySpaceKind () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getName()
virtual std::string llvm::pdb::IPDBRawSymbol::getName () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypeTypedef, and llvm::pdb::NativeCompilandSymbol.
getNoStackOrdering()
virtual bool llvm::pdb::IPDBRawSymbol::getNoStackOrdering () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getNumberOfAcceleratorPointerTags()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getNumberOfAcceleratorPointerTags () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getNumberOfColumns()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getNumberOfColumns () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getNumberOfModifiers()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getNumberOfModifiers () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getNumberOfRegisterIndices()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getNumberOfRegisterIndices () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getNumberOfRows()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getNumberOfRows () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getObjectFileName()
virtual std::string llvm::pdb::IPDBRawSymbol::getObjectFileName () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getOemId()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getOemId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getOemSymbolId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getOemSymbolId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getOffset()
virtual int32_t llvm::pdb::IPDBRawSymbol::getOffset () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getOffsetInUdt()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getOffsetInUdt () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getPlatform()
virtual PDB_Cpu llvm::pdb::IPDBRawSymbol::getPlatform () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getRank()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getRank () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getRegisterId()
virtual codeview::RegisterId llvm::pdb::IPDBRawSymbol::getRegisterId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getRegisterType()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getRegisterType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getRelativeVirtualAddress()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getRelativeVirtualAddress () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbolData::getCompilandId(), and llvm::pdb::PDBSymbolData::getLineNumbers().
getSamplerSlot()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getSamplerSlot () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getSignature()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getSignature () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getSizeInUdt()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getSizeInUdt () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getSlot()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getSlot () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getSourceFileName()
virtual std::string llvm::pdb::IPDBRawSymbol::getSourceFileName () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath().
getSrcLineOnTypeDefn()
virtual std::unique_ptr<IPDBLineNumber> llvm::pdb::IPDBRawSymbol::getSrcLineOnTypeDefn () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getStride()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getStride () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getSubTypeId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getSubTypeId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getSymbolsFileName()
virtual std::string llvm::pdb::IPDBRawSymbol::getSymbolsFileName () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeExeSymbol.
getSymIndexId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getSymIndexId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
Referenced by llvm::pdb::PDBSymbol::getSymIndexId().
getSymTag()
virtual PDB_SymType llvm::pdb::IPDBRawSymbol::getSymTag () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeBuiltin, and llvm::pdb::NativeCompilandSymbol.
Referenced by llvm::pdb::PDBSymbol::create(), and llvm::pdb::PDBSymbol::getSymTag().
getTargetOffset()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getTargetOffset () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getTargetRelativeVirtualAddress()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getTargetRelativeVirtualAddress () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getTargetSection()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getTargetSection () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getTargetVirtualAddress()
virtual uint64_t llvm::pdb::IPDBRawSymbol::getTargetVirtualAddress () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getTextureSlot()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getTextureSlot () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getThisAdjust()
virtual int32_t llvm::pdb::IPDBRawSymbol::getThisAdjust () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypeFunctionSig.
getThunkOrdinal()
virtual codeview::ThunkOrdinal llvm::pdb::IPDBRawSymbol::getThunkOrdinal () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getTimeStamp()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getTimeStamp () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getToken()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getToken () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getTypeId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getTypeId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypePointer, llvm::pdb::NativeTypeArray, llvm::pdb::NativeSymbolEnumerator, and llvm::pdb::NativeTypeTypedef.
Referenced by getSymbolType().
getUavSlot()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getUavSlot () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getUdtKind()
virtual PDB_UdtType llvm::pdb::IPDBRawSymbol::getUdtKind () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypeUDT.
getUndecoratedName()
virtual std::string llvm::pdb::IPDBRawSymbol::getUndecoratedName () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getUndecoratedNameEx()
virtual std::string llvm::pdb::IPDBRawSymbol::getUndecoratedNameEx (PDB_UndnameFlags Flags) const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getUnmodifiedTypeId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getUnmodifiedTypeId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
getUnused()
virtual std::string llvm::pdb::IPDBRawSymbol::getUnused () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getUpperBoundId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getUpperBoundId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getValue()
virtual Variant llvm::pdb::IPDBRawSymbol::getValue () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeSymbolEnumerator.
Referenced by llvm::pdb::PDBSymbolCompilandEnv::getValue().
getVirtualAddress()
virtual uint64_t llvm::pdb::IPDBRawSymbol::getVirtualAddress () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getVirtualBaseDispIndex()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getVirtualBaseDispIndex () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getVirtualBaseOffset()
virtual uint32_t llvm::pdb::IPDBRawSymbol::getVirtualBaseOffset () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getVirtualBasePointerOffset()
virtual int32_t llvm::pdb::IPDBRawSymbol::getVirtualBasePointerOffset () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getVirtualBaseTableType()
virtual std::unique_ptr<PDBSymbolTypeBuiltin> llvm::pdb::IPDBRawSymbol::getVirtualBaseTableType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
getVirtualTableShapeId()
virtual SymIndexId llvm::pdb::IPDBRawSymbol::getVirtualTableShapeId () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypeUDT.
hasAlloca()
virtual bool llvm::pdb::IPDBRawSymbol::hasAlloca () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasAssignmentOperator()
virtual bool llvm::pdb::IPDBRawSymbol::hasAssignmentOperator () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
hasCastOperator()
virtual bool llvm::pdb::IPDBRawSymbol::hasCastOperator () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
hasConstructor()
virtual bool llvm::pdb::IPDBRawSymbol::hasConstructor () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
hasCTypes()
virtual bool llvm::pdb::IPDBRawSymbol::hasCTypes () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeExeSymbol.
hasCustomCallingConvention()
virtual bool llvm::pdb::IPDBRawSymbol::hasCustomCallingConvention () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasDebugInfo()
virtual bool llvm::pdb::IPDBRawSymbol::hasDebugInfo () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasEH()
virtual bool llvm::pdb::IPDBRawSymbol::hasEH () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasEHa()
virtual bool llvm::pdb::IPDBRawSymbol::hasEHa () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasFarReturn()
virtual bool llvm::pdb::IPDBRawSymbol::hasFarReturn () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasFramePointer()
virtual bool llvm::pdb::IPDBRawSymbol::hasFramePointer () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasInlAsm()
virtual bool llvm::pdb::IPDBRawSymbol::hasInlAsm () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasInlineAttribute()
virtual bool llvm::pdb::IPDBRawSymbol::hasInlineAttribute () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasInterruptReturn()
virtual bool llvm::pdb::IPDBRawSymbol::hasInterruptReturn () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasLongJump()
virtual bool llvm::pdb::IPDBRawSymbol::hasLongJump () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasManagedCode()
virtual bool llvm::pdb::IPDBRawSymbol::hasManagedCode () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasNestedTypes()
virtual bool llvm::pdb::IPDBRawSymbol::hasNestedTypes () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
hasNoInlineAttribute()
virtual bool llvm::pdb::IPDBRawSymbol::hasNoInlineAttribute () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasNoReturnAttribute()
virtual bool llvm::pdb::IPDBRawSymbol::hasNoReturnAttribute () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasOptimizedCodeDebugInfo()
virtual bool llvm::pdb::IPDBRawSymbol::hasOptimizedCodeDebugInfo () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasOverloadedOperator()
virtual bool llvm::pdb::IPDBRawSymbol::hasOverloadedOperator () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
hasPrivateSymbols()
virtual bool llvm::pdb::IPDBRawSymbol::hasPrivateSymbols () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeExeSymbol.
hasSecurityChecks()
virtual bool llvm::pdb::IPDBRawSymbol::hasSecurityChecks () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasSEH()
virtual bool llvm::pdb::IPDBRawSymbol::hasSEH () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasSetJump()
virtual bool llvm::pdb::IPDBRawSymbol::hasSetJump () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
hasStrictGSCheck()
virtual bool llvm::pdb::IPDBRawSymbol::hasStrictGSCheck () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isAcceleratorGroupSharedLocal()
virtual bool llvm::pdb::IPDBRawSymbol::isAcceleratorGroupSharedLocal () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isAcceleratorPointerTagLiveRange()
virtual bool llvm::pdb::IPDBRawSymbol::isAcceleratorPointerTagLiveRange () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isAcceleratorStubFunction()
virtual bool llvm::pdb::IPDBRawSymbol::isAcceleratorStubFunction () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isAggregated()
virtual bool llvm::pdb::IPDBRawSymbol::isAggregated () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isCode()
virtual bool llvm::pdb::IPDBRawSymbol::isCode () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isCompilerGenerated()
virtual bool llvm::pdb::IPDBRawSymbol::isCompilerGenerated () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isConstructorVirtualBase()
virtual bool llvm::pdb::IPDBRawSymbol::isConstructorVirtualBase () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypeFunctionSig.
isConstType()
virtual bool llvm::pdb::IPDBRawSymbol::isConstType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypePointer, llvm::pdb::NativeTypeBuiltin, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
isCVTCIL()
virtual bool llvm::pdb::IPDBRawSymbol::isCVTCIL () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isCxxReturnUdt()
virtual bool llvm::pdb::IPDBRawSymbol::isCxxReturnUdt () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypeFunctionSig.
isDataAligned()
virtual bool llvm::pdb::IPDBRawSymbol::isDataAligned () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isEditAndContinueEnabled()
virtual bool llvm::pdb::IPDBRawSymbol::isEditAndContinueEnabled () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeCompilandSymbol.
isFunction()
virtual bool llvm::pdb::IPDBRawSymbol::isFunction () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isHLSLData()
virtual bool llvm::pdb::IPDBRawSymbol::isHLSLData () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isHotpatchable()
virtual bool llvm::pdb::IPDBRawSymbol::isHotpatchable () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isIndirectVirtualBaseClass()
virtual bool llvm::pdb::IPDBRawSymbol::isIndirectVirtualBaseClass () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isInterfaceUdt()
virtual bool llvm::pdb::IPDBRawSymbol::isInterfaceUdt () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
isIntrinsic()
virtual bool llvm::pdb::IPDBRawSymbol::isIntrinsic () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
isIntroVirtualFunction()
virtual bool llvm::pdb::IPDBRawSymbol::isIntroVirtualFunction () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isLocationControlFlowDependent()
virtual bool llvm::pdb::IPDBRawSymbol::isLocationControlFlowDependent () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isLTCG()
virtual bool llvm::pdb::IPDBRawSymbol::isLTCG () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isManagedCode()
virtual bool llvm::pdb::IPDBRawSymbol::isManagedCode () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isMatrixRowMajor()
virtual bool llvm::pdb::IPDBRawSymbol::isMatrixRowMajor () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isMSILCode()
virtual bool llvm::pdb::IPDBRawSymbol::isMSILCode () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isMSILNetmodule()
virtual bool llvm::pdb::IPDBRawSymbol::isMSILNetmodule () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isMultipleInheritance()
virtual bool llvm::pdb::IPDBRawSymbol::isMultipleInheritance () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isNaked()
virtual bool llvm::pdb::IPDBRawSymbol::isNaked () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isNested()
virtual bool llvm::pdb::IPDBRawSymbol::isNested () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
isOptimizedAway()
virtual bool llvm::pdb::IPDBRawSymbol::isOptimizedAway () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isPacked()
virtual bool llvm::pdb::IPDBRawSymbol::isPacked () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
isPointerBasedOnSymbolValue()
virtual bool llvm::pdb::IPDBRawSymbol::isPointerBasedOnSymbolValue () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isPointerToDataMember()
virtual bool llvm::pdb::IPDBRawSymbol::isPointerToDataMember () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isPointerToMemberFunction()
virtual bool llvm::pdb::IPDBRawSymbol::isPointerToMemberFunction () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isPureVirtual()
virtual bool llvm::pdb::IPDBRawSymbol::isPureVirtual () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isReference()
virtual bool llvm::pdb::IPDBRawSymbol::isReference () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isRefUdt()
virtual bool llvm::pdb::IPDBRawSymbol::isRefUdt () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
isRestrictedType()
virtual bool llvm::pdb::IPDBRawSymbol::isRestrictedType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isReturnValue()
virtual bool llvm::pdb::IPDBRawSymbol::isReturnValue () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isRValueReference()
virtual bool llvm::pdb::IPDBRawSymbol::isRValueReference () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isSafeBuffers()
virtual bool llvm::pdb::IPDBRawSymbol::isSafeBuffers () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isScoped()
virtual bool llvm::pdb::IPDBRawSymbol::isScoped () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
isSdl()
virtual bool llvm::pdb::IPDBRawSymbol::isSdl () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isSingleInheritance()
virtual bool llvm::pdb::IPDBRawSymbol::isSingleInheritance () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isSplitted()
virtual bool llvm::pdb::IPDBRawSymbol::isSplitted () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isStatic()
virtual bool llvm::pdb::IPDBRawSymbol::isStatic () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isUnalignedType()
virtual bool llvm::pdb::IPDBRawSymbol::isUnalignedType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypePointer, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypeBuiltin, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
isUnreached()
virtual bool llvm::pdb::IPDBRawSymbol::isUnreached () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isValueUdt()
virtual bool llvm::pdb::IPDBRawSymbol::isValueUdt () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
isVirtual()
virtual bool llvm::pdb::IPDBRawSymbol::isVirtual () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isVirtualBaseClass()
virtual bool llvm::pdb::IPDBRawSymbol::isVirtualBaseClass () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
isVirtualInheritance()
virtual bool llvm::pdb::IPDBRawSymbol::isVirtualInheritance () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, and llvm::pdb::NativeTypePointer.
isVolatileType()
virtual bool llvm::pdb::IPDBRawSymbol::isVolatileType () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, llvm::pdb::DIARawSymbol, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypePointer, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypeBuiltin, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
wasInlined()
virtual bool llvm::pdb::IPDBRawSymbol::wasInlined () const pure virtual
Implemented in llvm::pdb::NativeRawSymbol, and llvm::pdb::DIARawSymbol.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/IPDBRawSymbol.h
lib/DebugInfo/PDB/PDBInterfaceAnchors.cpp