LLVM: llvm::LanaiInstPrinter Class Reference
llvm::LanaiInstPrinter Class Reference
#include "Target/Lanai/MCTargetDesc/LanaiInstPrinter.h"
Public Member Functions
LanaiInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printPredicateOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMemRiOperand (const MCInst *MI, int OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printMemRrOperand (const MCInst *MI, int OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printMemSplsOperand (const MCInst *MI, int OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printCCOperand (const MCInst *MI, int OpNo, raw_ostream &O)
void printAluOperand (const MCInst *MI, int OpNo, raw_ostream &O)
void printHi16ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printHi16AndImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLo16AndImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, raw_ostream &OS)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 21 of file LanaiInstPrinter.h.
Constructor & Destructor Documentation
LanaiInstPrinter()
llvm::LanaiInstPrinter::LanaiInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 23 of file LanaiInstPrinter.h.
References llvm::Address, getRegisterName(), MI, llvm::RISCVFenceField::O, printAliasInstr(), printAluOperand(), printCCOperand(), printCustomAliasOperand(), printHi16AndImmOperand(), printHi16ImmOperand(), printInst(), printInstruction(), printLo16AndImmOperand(), printMemImmOperand(), printMemRiOperand(), printMemRrOperand(), printMemSplsOperand(), printOperand(), printPredicateOperand(), and printRegName().
Member Function Documentation
getRegisterName()
static const char* llvm::LanaiInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by decIncOperator(), LanaiInstPrinter(), printMemoryBaseRegister(), printMemRrOperand(), printOperand(), and printRegName().
printAliasInstr()
bool llvm::LanaiInstPrinter::printAliasInstr (const MCInst * MI, raw_ostream & OS)
Referenced by LanaiInstPrinter(), and printInst().
printAluOperand()
void llvm::LanaiInstPrinter::printAluOperand (const MCInst * MI, int OpNo, raw_ostream & O)
Referenced by LanaiInstPrinter().
printCCOperand()
void LanaiInstPrinter::printCCOperand (const MCInst * MI, int OpNo, raw_ostream & O)
Definition at line 288 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::LPCC::lanaiCondCodeToString(), and llvm::LPCC::UNKNOWN.
Referenced by LanaiInstPrinter().
printCustomAliasOperand()
void llvm::LanaiInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O)
Referenced by LanaiInstPrinter().
printHi16AndImmOperand()
void LanaiInstPrinter::printHi16AndImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 189 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by LanaiInstPrinter().
printHi16ImmOperand()
void LanaiInstPrinter::printHi16ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 177 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by LanaiInstPrinter().
printInst()
void LanaiInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 140 of file LanaiInstPrinter.cpp.
References printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
Referenced by LanaiInstPrinter(), and printRegName().
printInstruction()
void llvm::LanaiInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by LanaiInstPrinter(), and printInst().
printLo16AndImmOperand()
void LanaiInstPrinter::printLo16AndImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 201 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by LanaiInstPrinter().
printMemImmOperand()
void LanaiInstPrinter::printMemImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 163 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by LanaiInstPrinter().
printMemRiOperand()
void LanaiInstPrinter::printMemRiOperand (const MCInst * MI, int OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 237 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCInstPrinter::MAI, and printMemoryBaseRegister().
Referenced by LanaiInstPrinter().
printMemRrOperand()
void LanaiInstPrinter::printMemRrOperand (const MCInst * MI, int OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 252 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::LPAC::isPostOp(), llvm::LPAC::isPreOp(), llvm::MCOperand::isReg(), and llvm::LPAC::lanaiAluCodeToString().
Referenced by LanaiInstPrinter().
printMemSplsOperand()
void LanaiInstPrinter::printMemSplsOperand (const MCInst * MI, int OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 273 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCInstPrinter::MAI, and printMemoryBaseRegister().
Referenced by LanaiInstPrinter().
printOperand()
void LanaiInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 149 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by LanaiInstPrinter(), and printRegName().
printPredicateOperand()
void LanaiInstPrinter::printPredicateOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 299 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::LPCC::ICC_T, llvm::LPCC::lanaiCondCodeToString(), and llvm::LPCC::UNKNOWN.
Referenced by LanaiInstPrinter().
printRegName()
void LanaiInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 34 of file LanaiInstPrinter.cpp.
References getRegisterName(), llvm::StringRef::lower(), MI, printInst(), and printOperand().
Referenced by LanaiInstPrinter().
The documentation for this class was generated from the following files:
lib/Target/Lanai/MCTargetDesc/LanaiInstPrinter.h
lib/Target/Lanai/MCTargetDesc/LanaiInstPrinter.cpp