LLVM: llvm::ScopedPrinter Class Reference
llvm::ScopedPrinter Class Reference
#include "llvm/Support/ScopedPrinter.h"
Public Member Functions
ScopedPrinter (raw_ostream &OS)
void flush ()
void indent (int Levels=1)
void unindent (int Levels=1)
void resetIndent ()
int getIndentLevel ()
void setPrefix (StringRef P)
void printIndent ()
template<typename T >
HexNumber hex (T Value)
template<typename T , typename TEnum >
void printEnum (StringRef Label, T Value, ArrayRef< EnumEntry< TEnum >> EnumValues)
template<typename T , typename TFlag >
void printFlags (StringRef Label, T Value, ArrayRef< EnumEntry< TFlag >> Flags, TFlag EnumMask1={}, TFlag EnumMask2={}, TFlag EnumMask3={})
template<typename T >
void printFlags (StringRef Label, T Value)
void printNumber (StringRef Label, uint64_t Value)
void printNumber (StringRef Label, uint32_t Value)
void printNumber (StringRef Label, uint16_t Value)
void printNumber (StringRef Label, uint8_t Value)
void printNumber (StringRef Label, int64_t Value)
void printNumber (StringRef Label, int32_t Value)
void printNumber (StringRef Label, int16_t Value)
void printNumber (StringRef Label, int8_t Value)
void printNumber (StringRef Label, const APSInt &Value)
void printBoolean (StringRef Label, bool Value)
template<typename... T>
void printVersion (StringRef Label, T... Version)
template<typename T >
void printList (StringRef Label, const T &List)
template<typename T , typename U >
void printList (StringRef Label, const T &List, const U &Printer)
template<typename T >
void printHexList (StringRef Label, const T &List)
template<typename T >
void printHex (StringRef Label, T Value)
template<typename T >
void printHex (StringRef Label, StringRef Str, T Value)
template<typename T >
void printSymbolOffset (StringRef Label, StringRef Symbol, T Value)
void printString (StringRef Value)
void printString (StringRef Label, StringRef Value)
void printString (StringRef Label, const std::string &Value)
void printString (StringRef Label, const char *Value)
template<typename T >
void printNumber (StringRef Label, StringRef Str, T Value)
void printBinary (StringRef Label, StringRef Str, ArrayRef< uint8_t > Value)
void printBinary (StringRef Label, StringRef Str, ArrayRef< char > Value)
void printBinary (StringRef Label, ArrayRef< uint8_t > Value)
void printBinary (StringRef Label, ArrayRef< char > Value)
void printBinary (StringRef Label, StringRef Value)
void printBinaryBlock (StringRef Label, ArrayRef< uint8_t > Value, uint32_t StartOffset)
void printBinaryBlock (StringRef Label, ArrayRef< uint8_t > Value)
void printBinaryBlock (StringRef Label, StringRef Value)
template<typename T >
void printObject (StringRef Label, const T &Value)
raw_ostream & startLine ()
raw_ostream & getOStream ()
Detailed Description
Definition at line 68 of file ScopedPrinter.h.
Constructor & Destructor Documentation
ScopedPrinter()
llvm::ScopedPrinter::ScopedPrinter (raw_ostream & OS) inline
Definition at line 70 of file ScopedPrinter.h.
Member Function Documentation
flush()
void llvm::ScopedPrinter::flush () inline
Definition at line 72 of file ScopedPrinter.h.
getIndentLevel()
int llvm::ScopedPrinter::getIndentLevel () inline
Definition at line 82 of file ScopedPrinter.h.
getOStream()
raw_ostream& llvm::ScopedPrinter::getOStream () inline
Definition at line 327 of file ScopedPrinter.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::EnumEntry< T >::Name, llvm::cl::Prefix, llvm::T, and llvm::EnumEntry< T >::Value.
Referenced by llvm::DelimitedScope< Open, Close >::DelimitedScope(), llvm::DWARFDebugNames::Entry::dump(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), llvm::AppleAcceleratorTable::readAtoms(), llvm::codeview::TypeDumpVisitor::visitMemberBegin(), and llvm::codeview::TypeDumpVisitor::visitTypeBegin().
hex()
template<typename T > HexNumber llvm::ScopedPrinter::hex (T Value) inline
Definition at line 92 of file ScopedPrinter.h.
indent()
void llvm::ScopedPrinter::indent (int Levels = 1) inline
Definition at line 74 of file ScopedPrinter.h.
Referenced by llvm::DelimitedScope< Open, Close >::DelimitedScope(), llvm::codeview::TypeDumpVisitor::visitMemberBegin(), and llvm::codeview::TypeDumpVisitor::visitTypeBegin().
printBinary() [1/5]
void llvm::ScopedPrinter::printBinary (StringRef Label, StringRef Str, ArrayRef< uint8_t > Value) inline
Definition at line 277 of file ScopedPrinter.h.
printBinary() [2/5]
void llvm::ScopedPrinter::printBinary (StringRef Label, StringRef Str, ArrayRef< char > Value) inline
Definition at line 281 of file ScopedPrinter.h.
References llvm::ArrayRef< T >::data(), llvm::makeArrayRef(), and llvm::ArrayRef< T >::size().
printBinary() [3/5]
void llvm::ScopedPrinter::printBinary (StringRef Label, ArrayRef< uint8_t > Value) inline
Definition at line 287 of file ScopedPrinter.h.
printBinary() [4/5]
void llvm::ScopedPrinter::printBinary (StringRef Label, ArrayRef< char > Value) inline
Definition at line 291 of file ScopedPrinter.h.
References llvm::ArrayRef< T >::data(), llvm::makeArrayRef(), and llvm::ArrayRef< T >::size().
printBinary() [5/5]
void llvm::ScopedPrinter::printBinary (StringRef Label, StringRef Value) inline
Definition at line 297 of file ScopedPrinter.h.
References llvm::StringRef::data(), llvm::makeArrayRef(), and llvm::StringRef::size().
printBinaryBlock() [1/3]
void llvm::ScopedPrinter::printBinaryBlock (StringRef Label, ArrayRef< uint8_t > Value, uint32_t StartOffset) inline
Definition at line 303 of file ScopedPrinter.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitTypeEnd().
printBinaryBlock() [2/3]
void llvm::ScopedPrinter::printBinaryBlock (StringRef Label, ArrayRef< uint8_t > Value) inline
Definition at line 308 of file ScopedPrinter.h.
printBinaryBlock() [3/3]
void llvm::ScopedPrinter::printBinaryBlock (StringRef Label, StringRef Value) inline
Definition at line 312 of file ScopedPrinter.h.
References llvm::StringRef::data(), llvm::makeArrayRef(), and llvm::StringRef::size().
printBoolean()
void llvm::ScopedPrinter::printBoolean (StringRef Label, bool Value) inline
Definition at line 198 of file ScopedPrinter.h.
printEnum()
template<typename T , typename TEnum > void llvm::ScopedPrinter::printEnum (StringRef Label, T Value, ArrayRef< EnumEntry< TEnum >> EnumValues) inline
Definition at line 95 of file ScopedPrinter.h.
References llvm::EnumEntry< T >::Name.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberBegin(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), llvm::codeview::TypeDumpVisitor::visitTypeBegin(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
printFlags() [1/2]
template<typename T , typename TFlag > void llvm::ScopedPrinter::printFlags (StringRef Label, T Value, ArrayRef< EnumEntry< TFlag >> Flags, TFlag EnumMask1 = {}, TFlag EnumMask2 = {}, TFlag EnumMask3 = {}) inline
Definition at line 115 of file ScopedPrinter.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sort().
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
printFlags() [2/2]
template<typename T > void llvm::ScopedPrinter::printFlags (StringRef Label, T Value) inline
Definition at line 149 of file ScopedPrinter.h.
References llvm::EnumEntry< T >::Value.
printHex() [1/2]
template<typename T > void llvm::ScopedPrinter::printHex (StringRef Label, T Value) inline
Definition at line 245 of file ScopedPrinter.h.
Referenced by llvm::DWARFDebugNames::Header::dump(), llvm::DWARFDebugNames::Entry::dump(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), llvm::codeview::printTypeIndex(), llvm::AppleAcceleratorTable::readAtoms(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), llvm::codeview::TypeDumpVisitor::visitUnknownMember(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
printHex() [2/2]
template<typename T > void llvm::ScopedPrinter::printHex (StringRef Label, StringRef Str, T Value) inline
Definition at line 249 of file ScopedPrinter.h.
printHexList()
template<typename T > void llvm::ScopedPrinter::printHexList (StringRef Label, const T & List) inline
Definition at line 233 of file ScopedPrinter.h.
printIndent()
void llvm::ScopedPrinter::printIndent () inline
Definition at line 86 of file ScopedPrinter.h.
References llvm::cl::Prefix.
printList() [1/2]
template<typename T > void llvm::ScopedPrinter::printList (StringRef Label, const T & List) inline
Definition at line 208 of file ScopedPrinter.h.
printList() [2/2]
template<typename T , typename U > void llvm::ScopedPrinter::printList (StringRef Label, const T & List, const U & Printer) inline
Definition at line 221 of file ScopedPrinter.h.
References Printer.
printNumber() [1/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, uint64_t Value) inline
Definition at line 162 of file ScopedPrinter.h.
Referenced by llvm::AppleAcceleratorTable::dump(), llvm::DWARFDebugNames::Header::dump(), llvm::AppleAcceleratorTable::readAtoms(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
printNumber() [2/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, uint32_t Value) inline
Definition at line 166 of file ScopedPrinter.h.
printNumber() [3/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, uint16_t Value) inline
Definition at line 170 of file ScopedPrinter.h.
printNumber() [4/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, uint8_t Value) inline
Definition at line 174 of file ScopedPrinter.h.
printNumber() [5/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, int64_t Value) inline
Definition at line 178 of file ScopedPrinter.h.
printNumber() [6/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, int32_t Value) inline
Definition at line 182 of file ScopedPrinter.h.
printNumber() [7/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, int16_t Value) inline
Definition at line 186 of file ScopedPrinter.h.
printNumber() [8/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, int8_t Value) inline
Definition at line 190 of file ScopedPrinter.h.
printNumber() [9/10]
void llvm::ScopedPrinter::printNumber (StringRef Label, const APSInt & Value) inline
Definition at line 194 of file ScopedPrinter.h.
printNumber() [10/10]
template<typename T > void llvm::ScopedPrinter::printNumber (StringRef Label, StringRef Str, T Value) inline
Definition at line 273 of file ScopedPrinter.h.
printObject()
template<typename T > void llvm::ScopedPrinter::printObject (StringRef Label, const T & Value) inline
Definition at line 318 of file ScopedPrinter.h.
printString() [1/4]
void llvm::ScopedPrinter::printString (StringRef Value) inline
Definition at line 258 of file ScopedPrinter.h.
Referenced by llvm::AppleAcceleratorTable::dump(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), llvm::AppleAcceleratorTable::readAtoms(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
printString() [2/4]
void llvm::ScopedPrinter::printString (StringRef Label, StringRef Value) inline
Definition at line 260 of file ScopedPrinter.h.
printString() [3/4]
void llvm::ScopedPrinter::printString (StringRef Label, const std::string & Value) inline
Definition at line 264 of file ScopedPrinter.h.
printString() [4/4]
void llvm::ScopedPrinter::printString (StringRef Label, const char * Value) inline
Definition at line 268 of file ScopedPrinter.h.
printSymbolOffset()
template<typename T > void llvm::ScopedPrinter::printSymbolOffset (StringRef Label, StringRef Symbol, T Value) inline
Definition at line 254 of file ScopedPrinter.h.
printVersion()
template<typename... T> void llvm::ScopedPrinter::printVersion (StringRef Label, T... Version) inline
Definition at line 202 of file ScopedPrinter.h.
References llvm::IndexedInstrProf::Version.
resetIndent()
void llvm::ScopedPrinter::resetIndent () inline
Definition at line 80 of file ScopedPrinter.h.
setPrefix()
void llvm::ScopedPrinter::setPrefix (StringRef P) inline
Definition at line 84 of file ScopedPrinter.h.
References P, and llvm::cl::Prefix.
startLine()
raw_ostream& llvm::ScopedPrinter::startLine () inline
Definition at line 322 of file ScopedPrinter.h.
Referenced by llvm::DelimitedScope< Open, Close >::DelimitedScope(), llvm::AppleAcceleratorTable::dump(), llvm::DWARFDebugNames::Header::dump(), llvm::DWARFDebugNames::Abbrev::dump(), llvm::DWARFDebugNames::Entry::dump(), llvm::DWARFDebugNames::NameIndex::dump(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), llvm::AppleAcceleratorTable::readAtoms(), llvm::codeview::TypeDumpVisitor::visitMemberBegin(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), llvm::codeview::TypeDumpVisitor::visitTypeBegin(), and llvm::codeview::TypeDumpVisitor::visitTypeEnd().
unindent()
void llvm::ScopedPrinter::unindent (int Levels = 1) inline
Definition at line 76 of file ScopedPrinter.h.
References llvm::max().
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitTypeEnd().
The documentation for this class was generated from the following files:
include/llvm/Support/ScopedPrinter.h
lib/Support/ScopedPrinter.cpp