LLVM: llvm::pdb::GSIStreamBuilder Class Reference
llvm::pdb::GSIStreamBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h"
Public Member Functions
GSIStreamBuilder (msf::MSFBuilder &Msf)
~GSIStreamBuilder ()
GSIStreamBuilder (const GSIStreamBuilder &)=delete
GSIStreamBuilder & operator= (const GSIStreamBuilder &)=delete
Error finalizeMsfLayout ()
Error commit (const msf::MSFLayout &Layout, WritableBinaryStreamRef Buffer)
uint32_t getPublicsStreamIndex () const
uint32_t getGlobalsStreamIndex () const
uint32_t getRecordStreamIdx () const
void addPublicSymbol (const codeview::PublicSym32 &Pub)
void addGlobalSymbol (const codeview::ProcRefSym &Sym)
void addGlobalSymbol (const codeview::DataSym &Sym)
void addGlobalSymbol (const codeview::ConstantSym &Sym)
void addGlobalSymbol (const codeview::CVSymbol &Sym)
Detailed Description
Definition at line 41 of file GSIStreamBuilder.h.
Constructor & Destructor Documentation
GSIStreamBuilder() [1/2]
GSIStreamBuilder::GSIStreamBuilder (msf::MSFBuilder & Msf) explicit
Definition at line 185 of file GSIStreamBuilder.cpp.
~GSIStreamBuilder()
GSIStreamBuilder::~GSIStreamBuilder ()
Definition at line 189 of file GSIStreamBuilder.cpp.
References Size.
GSIStreamBuilder() [2/2]
llvm::pdb::GSIStreamBuilder::GSIStreamBuilder (const GSIStreamBuilder &) delete
Member Function Documentation
addGlobalSymbol() [1/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::ProcRefSym & Sym)
Definition at line 290 of file GSIStreamBuilder.cpp.
addGlobalSymbol() [2/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::DataSym & Sym)
Definition at line 294 of file GSIStreamBuilder.cpp.
addGlobalSymbol() [3/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::ConstantSym & Sym)
Definition at line 298 of file GSIStreamBuilder.cpp.
addGlobalSymbol() [4/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::CVSymbol & Sym)
Definition at line 302 of file GSIStreamBuilder.cpp.
addPublicSymbol()
void GSIStreamBuilder::addPublicSymbol (const codeview::PublicSym32 & Pub)
Definition at line 286 of file GSIStreamBuilder.cpp.
commit()
Error GSIStreamBuilder::commit (const msf::MSFLayout & Layout, WritableBinaryStreamRef Buffer)
Definition at line 362 of file GSIStreamBuilder.cpp.
References llvm::codeview::EC, llvm::msf::MSFBuilder::getAllocator(), getGlobalsStreamIndex(), getPublicsStreamIndex(), getRecordStreamIdx(), llvm::X86AS::GS, and llvm::Error::success().
finalizeMsfLayout()
Error GSIStreamBuilder::finalizeMsfLayout ()
Definition at line 205 of file GSIStreamBuilder.cpp.
References llvm::msf::MSFBuilder::addStream(), llvm::Error::success(), and llvm::Expected< T >::takeError().
getGlobalsStreamIndex()
uint32_t GSIStreamBuilder::getGlobalsStreamIndex () const
Definition at line 282 of file GSIStreamBuilder.cpp.
Referenced by commit().
getPublicsStreamIndex()
uint32_t GSIStreamBuilder::getPublicsStreamIndex () const
Definition at line 278 of file GSIStreamBuilder.cpp.
Referenced by commit().
getRecordStreamIdx()
uint32_t llvm::pdb::GSIStreamBuilder::getRecordStreamIdx () const inline
Definition at line 56 of file GSIStreamBuilder.h.
References llvm::pdb::kInvalidStreamIndex.
Referenced by commit().
operator=()
GSIStreamBuilder& llvm::pdb::GSIStreamBuilder::operator= (const GSIStreamBuilder &) delete
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h
lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp