LLVM: llvm::AMDGPUInstPrinter Class Reference
llvm::AMDGPUInstPrinter Class Reference
#include "Target/AMDGPU/MCTargetDesc/AMDGPUInstPrinter.h"
Public Member Functions
AMDGPUInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
static void printRegOperand (unsigned RegNo, raw_ostream &O, const MCRegisterInfo &MRI)
static void printIfSet (const MCInst *MI, unsigned OpNo, raw_ostream &O, StringRef Asm, StringRef Default="")
static void printIfSet (const MCInst *MI, unsigned OpNo, raw_ostream &O, char Asm)
Protected Member Functions
void printAbs (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printHigh (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printClamp (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printClampSI (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printOModSI (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printLiteral (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printLast (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printNeg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printOMOD (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printRel (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printUpdateExecMask (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printUpdatePred (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printWrite (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printBankSwizzle (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printRSel (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printCT (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printKCache (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printSendMsg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printSwizzle (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printWaitFlag (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printHwreg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printEndpgm (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Additional Inherited Members
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 19 of file AMDGPUInstPrinter.h.
Constructor & Destructor Documentation
AMDGPUInstPrinter()
llvm::AMDGPUInstPrinter::AMDGPUInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 21 of file AMDGPUInstPrinter.h.
References llvm::Address, llvm::HexStyle::Asm, llvm::Default, getRegisterName(), MI, llvm::Mod, llvm::MCInstPrinter::MRI, Name, llvm::RISCVFenceField::O, printAbs(), printBankSwizzle(), printClamp(), printClampSI(), printCT(), printEndpgm(), printHigh(), printHwreg(), printIfSet(), printInst(), printInstruction(), printKCache(), printLast(), printLiteral(), printNeg(), printOMOD(), printOModSI(), printRegOperand(), printRel(), printRSel(), printSendMsg(), printSwizzle(), printUpdateExecMask(), printUpdatePred(), printWaitFlag(), and printWrite().
Member Function Documentation
getRegisterName()
static const char* llvm::AMDGPUInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by AMDGPUInstPrinter(), llvm::SIRegisterInfo::getRegAsmName(), and llvm::R600InstPrinter::R600InstPrinter().
printAbs()
void llvm::AMDGPUInstPrinter::printAbs (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printBankSwizzle()
void llvm::AMDGPUInstPrinter::printBankSwizzle (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printClamp()
void llvm::AMDGPUInstPrinter::printClamp (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printClampSI()
void AMDGPUInstPrinter::printClampSI (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1125 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by AMDGPUInstPrinter().
printCT()
void llvm::AMDGPUInstPrinter::printCT (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printEndpgm()
void AMDGPUInstPrinter::printEndpgm (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1333 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by AMDGPUInstPrinter().
printHigh()
void AMDGPUInstPrinter::printHigh (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1118 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by AMDGPUInstPrinter().
printHwreg()
void AMDGPUInstPrinter::printHwreg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1310 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPU::Hwreg::decodeHwreg(), llvm::StringRef::empty(), llvm::AMDGPU::Hwreg::getHwreg(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::AMDGPU::Hwreg::OFFSET_DEFAULT_, and llvm::AMDGPU::Hwreg::WIDTH_DEFAULT_.
Referenced by AMDGPUInstPrinter().
printIfSet() [1/2]
void AMDGPUInstPrinter::printIfSet (const MCInst * MI, unsigned OpNo, raw_ostream & O, StringRef Asm, StringRef Default = "") static
Definition at line 1098 of file AMDGPUInstPrinter.cpp.
References llvm::HexStyle::Asm, assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isImm().
Referenced by AMDGPUInstPrinter(), llvm::R600InstPrinter::printAbs(), llvm::R600InstPrinter::printClamp(), llvm::R600InstPrinter::printLast(), llvm::R600InstPrinter::printNeg(), llvm::R600InstPrinter::printRel(), llvm::R600InstPrinter::printUpdateExecMask(), and llvm::R600InstPrinter::printUpdatePred().
printIfSet() [2/2]
void AMDGPUInstPrinter::printIfSet (const MCInst * MI, unsigned OpNo, raw_ostream & O, char Asm) static
Definition at line 1110 of file AMDGPUInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isImm().
printInst()
void AMDGPUInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 29 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPU::MIMGDimInfo::AsmSuffix, llvm::raw_ostream::flush(), llvm::MCOperand::getImm(), llvm::AMDGPU::getMIMGDimInfoByEncoding(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCSubtargetInfo::hasFeature(), llvm::AMDGPU::isGFX10(), llvm::isInt< 16 >(), llvm::SIInstrFlags::IsNonFlatSeg, llvm::isUInt< 16 >(), MI, llvm::RISCVFenceField::O, and llvm::MCInstrDesc::TSFlags.
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printInstruction()
void llvm::AMDGPUInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printKCache()
void llvm::AMDGPUInstPrinter::printKCache (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printLast()
void llvm::AMDGPUInstPrinter::printLast (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printLiteral()
void llvm::AMDGPUInstPrinter::printLiteral (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printNeg()
void llvm::AMDGPUInstPrinter::printNeg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printOMOD()
void llvm::AMDGPUInstPrinter::printOMOD (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printOModSI()
void AMDGPUInstPrinter::printOModSI (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1132 of file AMDGPUInstPrinter.cpp.
References llvm::SIOutMods::DIV2, llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::SIOutMods::MUL2, and llvm::SIOutMods::MUL4.
Referenced by AMDGPUInstPrinter().
printRegOperand()
void AMDGPUInstPrinter::printRegOperand (unsigned RegNo, raw_ostream & O, const MCRegisterInfo & MRI) static
Definition at line 284 of file AMDGPUInstPrinter.cpp.
References llvm::SISrcMods::ABS, assert(), llvm::AMDGPU::DPP::BCAST15, llvm::AMDGPU::DPP::BCAST31, llvm::AMDGPU::SDWA::BYTE_0, llvm::AMDGPU::SDWA::BYTE_1, llvm::AMDGPU::SDWA::BYTE_2, llvm::AMDGPU::SDWA::BYTE_3, llvm::DoubleToBits(), llvm::SIInstrFlags::DPP, llvm::AMDGPU::DPP::DPP8_FI_1, llvm::AMDGPU::DPP::DPP_FI_1, llvm::AMDGPU::SDWA::DWORD, llvm::FloatToBits(), llvm::MCOperand::getExpr(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getFPImm(), llvm::MCOperand::getImm(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::AMDGPU::getRegBitWidth(), getRegisterName(), llvm::MCInstrDesc::hasImplicitDefOfPhysReg(), llvm::AMDGPU::isCI(), llvm::MCOperand::isExpr(), llvm::MCOperand::isFPImm(), llvm::AMDGPU::isGFX10(), llvm::AMDGPU::isGFX9(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::AMDGPU::isSI(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::AMDGPU::isVI(), LLVM_FALLTHROUGH, llvm_unreachable, MI, MRI, N, llvm::SISrcMods::NEG, llvm::RISCVFenceField::O, llvm::MCOI::OPERAND_IMMEDIATE, llvm::MCOI::OPERAND_PCREL, llvm::AMDGPU::OPERAND_REG_IMM_FP16, llvm::AMDGPU::OPERAND_REG_IMM_FP32, llvm::AMDGPU::OPERAND_REG_IMM_FP64, llvm::AMDGPU::OPERAND_REG_IMM_INT16, llvm::AMDGPU::OPERAND_REG_IMM_INT32, llvm::AMDGPU::OPERAND_REG_IMM_INT64, llvm::AMDGPU::OPERAND_REG_IMM_V2FP16, llvm::AMDGPU::OPERAND_REG_IMM_V2INT16, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FP16, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FP32, llvm::AMDGPU::OPERAND_REG_INLINE_AC_INT16, llvm::AMDGPU::OPERAND_REG_INLINE_AC_INT32, llvm::AMDGPU::OPERAND_REG_INLINE_AC_V2FP16, llvm::AMDGPU::OPERAND_REG_INLINE_AC_V2INT16, llvm::AMDGPU::OPERAND_REG_INLINE_C_FP16, llvm::AMDGPU::OPERAND_REG_INLINE_C_FP32, llvm::AMDGPU::OPERAND_REG_INLINE_C_FP64, llvm::AMDGPU::OPERAND_REG_INLINE_C_INT16, llvm::AMDGPU::OPERAND_REG_INLINE_C_INT32, llvm::AMDGPU::OPERAND_REG_INLINE_C_INT64, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2FP16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2INT16, llvm::MCOI::OPERAND_REGISTER, llvm::MCOI::OPERAND_UNKNOWN, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, llvm::MCExpr::print(), printOperand(), llvm::AMDGPU::DPP::QUAD_PERM_LAST, llvm::MCOperandInfo::RegClass, llvm::AMDGPU::DPP::ROW_HALF_MIRROR, llvm::AMDGPU::DPP::ROW_MIRROR, llvm::AMDGPU::DPP::ROW_ROR_FIRST, llvm::AMDGPU::DPP::ROW_ROR_LAST, llvm::AMDGPU::DPP::ROW_SHARE_FIRST, llvm::AMDGPU::DPP::ROW_SHARE_LAST, llvm::AMDGPU::DPP::ROW_SHL_FIRST, llvm::AMDGPU::DPP::ROW_SHL_LAST, llvm::AMDGPU::DPP::ROW_SHR_FIRST, llvm::AMDGPU::DPP::ROW_SHR_LAST, llvm::AMDGPU::DPP::ROW_XMASK_FIRST, llvm::AMDGPU::DPP::ROW_XMASK_LAST, llvm::SIInstrFlags::SDWA, llvm::SISrcMods::SEXT, llvm::MCInstrDesc::TSFlags, llvm::AMDGPU::SDWA::UNUSED_PAD, llvm::AMDGPU::SDWA::UNUSED_PRESERVE, llvm::AMDGPU::SDWA::UNUSED_SEXT, llvm::SIInstrFlags::VOP3, llvm::SIInstrFlags::VOPC, llvm::AMDGPU::DPP::WAVE_ROL1, llvm::AMDGPU::DPP::WAVE_ROR1, llvm::AMDGPU::DPP::WAVE_SHL1, llvm::AMDGPU::DPP::WAVE_SHR1, llvm::AMDGPU::SDWA::WORD_0, and llvm::AMDGPU::SDWA::WORD_1.
Referenced by AMDGPUInstPrinter(), and llvm::AMDGPUAsmPrinter::PrintAsmOperand().
printRel()
void llvm::AMDGPUInstPrinter::printRel (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printRSel()
void llvm::AMDGPUInstPrinter::printRSel (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printSendMsg()
void AMDGPUInstPrinter::printSendMsg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1144 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPU::SendMsg::decodeMsg(), llvm::AMDGPU::SendMsg::encodeMsg(), llvm::MCOperand::getImm(), llvm::AMDGPU::SendMsg::getMsgName(), llvm::AMDGPU::SendMsg::getMsgOpName(), llvm::MCInst::getOperand(), llvm::X86II::Imm16, llvm::AMDGPU::SendMsg::isValidMsgId(), llvm::AMDGPU::SendMsg::isValidMsgOp(), llvm::AMDGPU::SendMsg::isValidMsgStream(), llvm::AMDGPU::SendMsg::msgRequiresOp(), and llvm::AMDGPU::SendMsg::msgSupportsStream().
Referenced by AMDGPUInstPrinter().
printSwizzle()
void AMDGPUInstPrinter::printSwizzle (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1207 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPU::Swizzle::BITMASK_AND_SHIFT, llvm::AMDGPU::Swizzle::BITMASK_MASK, llvm::AMDGPU::Swizzle::BITMASK_MAX, llvm::AMDGPU::Swizzle::BITMASK_OR_SHIFT, llvm::AMDGPU::Swizzle::BITMASK_PERM_ENC, llvm::AMDGPU::Swizzle::BITMASK_PERM_ENC_MASK, llvm::AMDGPU::Swizzle::BITMASK_XOR_SHIFT, llvm::countPopulation(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), I, llvm::AMDGPU::Swizzle::ID_BITMASK_PERM, llvm::AMDGPU::Swizzle::ID_BROADCAST, llvm::AMDGPU::Swizzle::ID_QUAD_PERM, llvm::AMDGPU::Swizzle::ID_REVERSE, llvm::AMDGPU::Swizzle::ID_SWAP, llvm::AMDGPU::SendMsg::IdSymbolic, llvm::isPowerOf2_64(), llvm::AMDGPU::Swizzle::LANE_MASK, llvm::AMDGPU::Swizzle::LANE_NUM, llvm::AMDGPU::Swizzle::LANE_SHIFT, printSwizzleBitmask(), llvm::AMDGPU::Swizzle::QUAD_PERM_ENC, and llvm::AMDGPU::Swizzle::QUAD_PERM_ENC_MASK.
Referenced by AMDGPUInstPrinter().
printUpdateExecMask()
void llvm::AMDGPUInstPrinter::printUpdateExecMask (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printUpdatePred()
void llvm::AMDGPUInstPrinter::printUpdatePred (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
printWaitFlag()
void AMDGPUInstPrinter::printWaitFlag (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Definition at line 1280 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPU::decodeWaitcnt(), llvm::MCSubtargetInfo::getCPU(), llvm::AMDGPU::getExpcntBitMask(), llvm::MCOperand::getImm(), llvm::AMDGPU::getIsaVersion(), llvm::AMDGPU::getLgkmcntBitMask(), llvm::MCInst::getOperand(), and llvm::AMDGPU::getVmcntBitMask().
Referenced by AMDGPUInstPrinter().
printWrite()
void llvm::AMDGPUInstPrinter::printWrite (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) protected
Referenced by AMDGPUInstPrinter(), and llvm::R600InstPrinter::R600InstPrinter().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUInstPrinter.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUInstPrinter.cpp