LLVM: llvm::BinaryStreamRefBase< RefType, StreamType > Class Template Reference
llvm::BinaryStreamRefBase< RefType, StreamType > Class Template Reference
Common stuff for mutable and immutable StreamRefs.
#include "llvm/Support/BinaryStreamRef.h"
Public Member Functions
llvm::support::endianness getEndian () const
uint32_t getLength () const
RefType drop_front (uint32_t N) const
Return a new BinaryStreamRef with the first N elements removed.
RefType drop_back (uint32_t N) const
Return a new BinaryStreamRef with the last N elements removed.
RefType keep_front (uint32_t N) const
Return a new BinaryStreamRef with only the first N elements remaining.
RefType keep_back (uint32_t N) const
Return a new BinaryStreamRef with only the last N elements remaining.
RefType drop_symmetric (uint32_t N) const
Return a new BinaryStreamRef with the first and last N elements removed.
RefType slice (uint32_t Offset, uint32_t Len) const
Return a new BinaryStreamRef with the first Offset elements removed, and retaining exactly Len elements.
bool valid () const
bool operator== (const RefType &Other) const
Protected Member Functions
BinaryStreamRefBase ()=default
BinaryStreamRefBase (StreamType &BorrowedImpl)
BinaryStreamRefBase (std::shared_ptr< StreamType > SharedImpl, uint32_t Offset, Optional< uint32_t > Length)
BinaryStreamRefBase (StreamType &BorrowedImpl, uint32_t Offset, Optional< uint32_t > Length)
BinaryStreamRefBase (const BinaryStreamRefBase &Other)=default
BinaryStreamRefBase & operator= (const BinaryStreamRefBase &Other)=default
BinaryStreamRefBase & operator= (BinaryStreamRefBase &&Other)=default
BinaryStreamRefBase (BinaryStreamRefBase &&Other)=default
Error checkOffsetForRead (uint32_t Offset, uint32_t DataSize) const
Protected Attributes
std::shared_ptr< StreamType > SharedImpl
StreamType * BorrowedImpl = nullptr
uint32_t ViewOffset = 0
Optional< uint32_t > Length
Detailed Description
template<class RefType, class StreamType>
class llvm::BinaryStreamRefBase< RefType, StreamType >
Common stuff for mutable and immutable StreamRefs.
Definition at line 24 of file BinaryStreamRef.h.
Constructor & Destructor Documentation
BinaryStreamRefBase() [1/6]
template<class RefType, class StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase () protected default
Referenced by llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::BinaryStreamRefBase().
BinaryStreamRefBase() [2/6]
template<class RefType, class StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (StreamType & BorrowedImpl) inline explicit protected
Definition at line 27 of file BinaryStreamRef.h.
BinaryStreamRefBase() [3/6]
template<class RefType, class StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (std::shared_ptr< StreamType > SharedImpl, uint32_t Offset, Optional< uint32_t > Length) inline protected
Definition at line 33 of file BinaryStreamRef.h.
BinaryStreamRefBase() [4/6]
template<class RefType, class StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (StreamType & BorrowedImpl, uint32_t Offset, Optional< uint32_t > Length) inline protected
Definition at line 37 of file BinaryStreamRef.h.
BinaryStreamRefBase() [5/6]
template<class RefType, class StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (const BinaryStreamRefBase< RefType, StreamType > & Other) protected default
BinaryStreamRefBase() [6/6]
template<class RefType, class StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (BinaryStreamRefBase< RefType, StreamType > && Other) protected default
Member Function Documentation
checkOffsetForRead()
template<class RefType, class StreamType> Error llvm::BinaryStreamRefBase< RefType, StreamType >::checkOffsetForRead (uint32_t Offset, uint32_t DataSize) const inline protected
Definition at line 135 of file BinaryStreamRef.h.
drop_back()
template<class RefType, class StreamType> RefType llvm::BinaryStreamRefBase< RefType, StreamType >::drop_back (uint32_t N) const inline
Return a new BinaryStreamRef with the last N elements removed.
If this BinaryStreamRef is length-tracking and N is greater than 0, then this BinaryStreamRef will no longer length-track.
Definition at line 79 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::keep_front().
drop_front()
template<class RefType, class StreamType> RefType llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front (uint32_t N) const inline
Return a new BinaryStreamRef with the first N elements removed.
If this BinaryStreamRef is length-tracking, then the resulting one will be too.
Definition at line 61 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::drop_symmetric(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::keep_back(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::slice(), llvm::BinaryStreamWriter::split(), llvm::BinarySubstreamRef::split(), and llvm::BinaryStreamReader::split().
drop_symmetric()
template<class RefType, class StreamType> RefType llvm::BinaryStreamRefBase< RefType, StreamType >::drop_symmetric (uint32_t N) const inline
Return a new BinaryStreamRef with the first and last N elements removed.
Definition at line 112 of file BinaryStreamRef.h.
getEndian()
template<class RefType, class StreamType> llvm::support::endianness llvm::BinaryStreamRefBase< RefType, StreamType >::getEndian () const inline
Definition at line 47 of file BinaryStreamRef.h.
getLength()
template<class RefType, class StreamType> uint32_t llvm::BinaryStreamRefBase< RefType, StreamType >::getLength () const inline
Definition at line 51 of file BinaryStreamRef.h.
Referenced by llvm::codeview::DebugSubsectionRecordBuilder::calculateSerializedLength(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::checkOffsetForRead(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::drop_back(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::drop_front(), llvm::FixedStreamArray< PSHashRecord >::FixedStreamArray(), llvm::codeview::DebugSubsectionRecord::getRecordLength(), llvm::pdb::DbiModuleList::initialize(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::keep_back(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::keep_front(), llvm::BinarySubstreamRef::size(), and llvm::BinaryStreamWriter::writeStreamRef().
keep_back()
template<class RefType, class StreamType> RefType llvm::BinaryStreamRefBase< RefType, StreamType >::keep_back (uint32_t N) const inline
Return a new BinaryStreamRef with only the last N elements remaining.
Definition at line 105 of file BinaryStreamRef.h.
keep_front()
template<class RefType, class StreamType> RefType llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front (uint32_t N) const inline
Return a new BinaryStreamRef with only the first N elements remaining.
Definition at line 99 of file BinaryStreamRef.h.
Referenced by llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::BinaryStreamWriter::split(), llvm::BinarySubstreamRef::split(), and llvm::BinaryStreamReader::split().
operator=() [1/2]
template<class RefType, class StreamType> BinaryStreamRefBase& llvm::BinaryStreamRefBase< RefType, StreamType >::operator= (const BinaryStreamRefBase< RefType, StreamType > & Other) protected default
Referenced by llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::BinaryStreamRefBase().
operator=() [2/2]
template<class RefType, class StreamType> BinaryStreamRefBase& llvm::BinaryStreamRefBase< RefType, StreamType >::operator= (BinaryStreamRefBase< RefType, StreamType > && Other) protected default
operator==()
template<class RefType, class StreamType> bool llvm::BinaryStreamRefBase< RefType, StreamType >::operator== (const RefType & Other) const inline
Definition at line 124 of file BinaryStreamRef.h.
slice()
template<class RefType, class StreamType> RefType llvm::BinaryStreamRefBase< RefType, StreamType >::slice (uint32_t Offset, uint32_t Len) const inline
Return a new BinaryStreamRef with the first Offset elements removed, and retaining exactly Len elements.
Definition at line 118 of file BinaryStreamRef.h.
Referenced by llvm::BinarySubstreamRef::drop_front(), llvm::BinarySubstreamRef::keep_front(), llvm::BinaryStreamReader::readStreamRef(), llvm::BinarySubstreamRef::slice(), and llvm::BinaryStreamWriter::writeStreamRef().
valid()
template<class RefType, class StreamType> bool llvm::BinaryStreamRefBase< RefType, StreamType >::valid () const inline
Definition at line 122 of file BinaryStreamRef.h.
Referenced by llvm::codeview::DebugStringTableSubsectionRef::valid().
Member Data Documentation
BorrowedImpl
template<class RefType, class StreamType> StreamType* llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl = nullptr protected
Definition at line 144 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::drop_back(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::drop_front(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::getEndian(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::getLength(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::operator==(), and llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::valid().
Length
template<class RefType, class StreamType> Optional<uint32_t> llvm::BinaryStreamRefBase< RefType, StreamType >::Length protected
Definition at line 146 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::BinaryStreamRefBase(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::getLength(), and llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::operator==().
SharedImpl
template<class RefType, class StreamType> std::shared_ptr<StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::SharedImpl protected
Definition at line 143 of file BinaryStreamRef.h.
ViewOffset
template<class RefType, class StreamType> uint32_t llvm::BinaryStreamRefBase< RefType, StreamType >::ViewOffset = 0 protected
Definition at line 145 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::getLength(), and llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::operator==().
The documentation for this class was generated from the following file:
include/llvm/Support/BinaryStreamRef.h