LLVM: llvm::cl::basic_parser_impl Class Reference
llvm::cl::basic_parser_impl Class Reference
#include "llvm/Support/CommandLine.h"
Public Member Functions
basic_parser_impl (Option &)
virtual ~basic_parser_impl ()
enum ValueExpected getValueExpectedFlagDefault () const
void getExtraOptionNames (SmallVectorImpl< StringRef > &)
void initialize ()
size_t getOptionWidth (const Option &O) const
void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printOptionNoValue (const Option &O, size_t GlobalWidth) const
virtual StringRef getValueName () const
virtual void anchor ()
Protected Member Functions
void printOptionName (const Option &O, size_t GlobalWidth) const
Detailed Description
Definition at line 871 of file CommandLine.h.
Constructor & Destructor Documentation
basic_parser_impl()
llvm::cl::basic_parser_impl::basic_parser_impl (Option &) inline
Definition at line 873 of file CommandLine.h.
~basic_parser_impl()
virtual llvm::cl::basic_parser_impl::~basic_parser_impl () inline virtual
Definition at line 875 of file CommandLine.h.
Member Function Documentation
anchor()
void basic_parser_impl::anchor () virtual
Reimplemented in llvm::cl::parser< char >, llvm::cl::parser< std::string >, llvm::cl::parser< float >, llvm::cl::parser< double >, llvm::cl::parser< unsigned long long >, llvm::cl::parser< unsigned long >, llvm::cl::parser< unsigned >, llvm::cl::parser< long long >, llvm::cl::parser< long >, llvm::cl::parser< int >, llvm::cl::parser< boolOrDefault >, and llvm::cl::parser< bool >.
Definition at line 83 of file CommandLine.cpp.
getExtraOptionNames()
void llvm::cl::basic_parser_impl::getExtraOptionNames (SmallVectorImpl< StringRef > &) inline
Definition at line 881 of file CommandLine.h.
getOptionWidth()
size_t basic_parser_impl::getOptionWidth (const Option & O) const
Definition at line 1730 of file CommandLine.cpp.
References argPlusPrefixesSize(), llvm::cl::Option::ArgStr, llvm::cl::Option::getMiscFlags(), getValueStr(), llvm::cl::PositionalEatsArgs, and llvm::StringRef::size().
getValueExpectedFlagDefault()
enum ValueExpected llvm::cl::basic_parser_impl::getValueExpectedFlagDefault () const inline
Definition at line 877 of file CommandLine.h.
References llvm::cl::ValueRequired.
getValueName()
virtual StringRef llvm::cl::basic_parser_impl::getValueName () const inline virtual
Reimplemented in llvm::cl::parser< char >, llvm::cl::parser< std::string >, llvm::cl::parser< float >, llvm::cl::parser< double >, llvm::cl::parser< unsigned long long >, llvm::cl::parser< unsigned long >, llvm::cl::parser< unsigned >, llvm::cl::parser< long long >, llvm::cl::parser< long >, llvm::cl::parser< int >, llvm::cl::parser< boolOrDefault >, and llvm::cl::parser< bool >.
Definition at line 898 of file CommandLine.h.
initialize()
void llvm::cl::basic_parser_impl::initialize () inline
Definition at line 883 of file CommandLine.h.
References llvm::RISCVFenceField::O.
printOptionInfo()
void basic_parser_impl::printOptionInfo (const Option & O, size_t GlobalWidth) const
Definition at line 1746 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::cl::Option::getMiscFlags(), getValueStr(), llvm::cl::Option::HelpStr, llvm::outs(), llvm::cl::PositionalEatsArgs, and llvm::cl::Option::printHelpStr().
printOptionName()
void basic_parser_impl::printOptionName (const Option & O, size_t GlobalWidth) const protected
Definition at line 1762 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::Option::error(), llvm::StringRef::getAsInteger(), llvm::raw_ostream::indent(), llvm::RISCVFenceField::O, llvm::outs(), llvm::cl::parser< DataType >::parse(), and llvm::StringRef::size().
printOptionNoValue()
void basic_parser_impl::printOptionNoValue (const Option & O, size_t GlobalWidth) const
Definition at line 2064 of file CommandLine.cpp.
References llvm::outs().
The documentation for this class was generated from the following files:
include/llvm/Support/CommandLine.h
lib/Support/CommandLine.cpp