LLVM: llvm::ARCTargetStreamer Class Reference
llvm::ARCTargetStreamer Class Reference
#include "Target/ARC/ARCTargetStreamer.h"
Public Member Functions
ARCTargetStreamer (MCStreamer &S)
~ARCTargetStreamer () override
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 16 of file ARCTargetStreamer.h.
Constructor & Destructor Documentation
ARCTargetStreamer()
ARCTargetStreamer::ARCTargetStreamer (MCStreamer & S)
Definition at line 74 of file ARCMCTargetDesc.cpp.
References ~ARCTargetStreamer().
Referenced by createTargetAsmStreamer().
~ARCTargetStreamer()
ARCTargetStreamer::~ARCTargetStreamer () override default
Referenced by ARCTargetStreamer().
The documentation for this class was generated from the following files:
lib/Target/ARC/ARCTargetStreamer.h
lib/Target/ARC/MCTargetDesc/ARCMCTargetDesc.cpp