LLVM: llvm::internal::NfaTranscriber Class Reference
llvm::internal::NfaTranscriber Class Reference
The internal class that maintains all possible paths through an NFA based on a path through the DFA.
#include "llvm/Support/Automaton.h"
Public Member Functions
NfaTranscriber (ArrayRef< NfaStatePair > TransitionInfo)
ArrayRef< NfaStatePair > getTransitionInfo () const
void reset ()
void transition (unsigned TransitionInfoIdx)
ArrayRef< NfaPath > getPaths ()
Detailed Description
The internal class that maintains all possible paths through an NFA based on a path through the DFA.
Definition at line 60 of file Automaton.h.
Constructor & Destructor Documentation
NfaTranscriber()
llvm::internal::NfaTranscriber::NfaTranscriber (ArrayRef< NfaStatePair > TransitionInfo) inline
Definition at line 115 of file Automaton.h.
Member Function Documentation
getPaths()
ArrayRef<NfaPath> llvm::internal::NfaTranscriber::getPaths () inline
Definition at line 141 of file Automaton.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::end(), P, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::reverse().
getTransitionInfo()
ArrayRef<NfaStatePair> llvm::internal::NfaTranscriber::getTransitionInfo () const inline
Definition at line 120 of file Automaton.h.
reset()
void llvm::internal::NfaTranscriber::reset () inline
Definition at line 124 of file Automaton.h.
References llvm::SmallVectorImpl< T >::clear(), and llvm::SpecificBumpPtrAllocator< T >::DestroyAll().
transition()
void llvm::internal::NfaTranscriber::transition (unsigned TransitionInfoIdx) inline
Definition at line 132 of file Automaton.h.
References llvm::NfaStatePair::ToDfaState.
The documentation for this class was generated from the following file:
include/llvm/Support/Automaton.h