LLVM: llvm::MD5 Class Reference
llvm::MD5 Class Reference
#include "llvm/Support/MD5.h"
Classes
struct MD5Result
Public Member Functions
MD5 ()
void update (ArrayRef< uint8_t > Data)
Updates the hash for the byte stream provided.
void update (StringRef Str)
Updates the hash for the StringRef provided.
void final (MD5Result &Result)
Finishes off the hash and puts the result in result.
Static Public Member Functions
static void stringifyResult (MD5Result &Result, SmallString< 32 > &Str)
Translates the bytes in Res to a hex string that is deposited into Str.
static std::array< uint8_t, 16 > hash (ArrayRef< uint8_t > Data)
Computes the hash for a given bytes.
Detailed Description
Definition at line 41 of file MD5.h.
Constructor & Destructor Documentation
MD5()
MD5::MD5 () default
Referenced by llvm::MD5::MD5Result::words().
Member Function Documentation
final()
void MD5::final (MD5Result & Result)
Finishes off the hash and puts the result in result.
Finish the hash and place the resulting hash into result.
Parameters
Result is assumed to be a minimum of 16-bytes in size.
Definition at line 234 of file MD5.cpp.
References llvm::makeArrayRef(), and llvm::support::endian::write32le().
Referenced by llvm::DIEHash::computeCUSignature(), llvm::DIEHash::computeTypeSignature(), llvm::FileInfo::getCoveragePath(), llvm::getUniqueModuleId(), hash(), isInPartition(), llvm::DwarfDebug::makeTypeSignature(), llvm::sys::fs::md5_contents(), llvm::MD5Hash(), and llvm::MCContext::setGenDwarfRootFile().
hash()
std::array< uint8_t, 16 > MD5::hash (ArrayRef< uint8_t > Data) static
Computes the hash for a given bytes.
Definition at line 276 of file MD5.cpp.
References final(), and update().
Referenced by llvm::MD5::MD5Result::words().
stringifyResult()
void MD5::stringifyResult (MD5Result & Result, SmallString< 32 > & Str) static
Translates the bytes in Res to a hex string that is deposited into Str.
The result will be of length 32.
Definition at line 272 of file MD5.cpp.
References llvm::MD5::MD5Result::digest().
Referenced by llvm::getUniqueModuleId(), and llvm::MD5::MD5Result::words().
update() [1/2]
void MD5::update (ArrayRef< uint8_t > Data)
Updates the hash for the byte stream provided.
Incrementally add the bytes in Data to the hash.
Definition at line 189 of file MD5.cpp.
References llvm::ArrayRef< T >::data(), llvm::makeArrayRef(), Size, and llvm::ArrayRef< T >::size().
Referenced by llvm::DIEHash::addSLEB128(), llvm::DIEHash::addULEB128(), llvm::DIEHash::computeCUSignature(), llvm::FileInfo::getCoveragePath(), getDIEStringAttr(), llvm::getUniqueModuleId(), hash(), isInPartition(), llvm::DwarfDebug::makeTypeSignature(), llvm::sys::fs::md5_contents(), llvm::MD5Hash(), llvm::MCContext::setGenDwarfRootFile(), update(), and llvm::MD5::MD5Result::words().
update() [2/2]
void MD5::update (StringRef Str)
Updates the hash for the StringRef provided.
Add the bytes in the StringRef Str to the hash.
Definition at line 227 of file MD5.cpp.
References llvm::StringRef::data(), llvm::StringRef::size(), and update().
The documentation for this class was generated from the following files:
include/llvm/Support/MD5.h
lib/Support/MD5.cpp