LLVM: llvm::MachineRegionInfoPass Class Reference
llvm::MachineRegionInfoPass Class Reference
#include "llvm/CodeGen/MachineRegionInfo.h"
Public Member Functions
MachineRegionInfoPass ()
~MachineRegionInfoPass () override
MachineRegionInfo & getRegionInfo ()
const MachineRegionInfo & getRegionInfo () const
MachineFunctionPass interface
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void verifyAnalysis () const override
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
void print (raw_ostream &OS, const Module *) const override
print - Print out the internal state of the pass.
void dump () const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 85 of file MachineRegionInfo.h.
Constructor & Destructor Documentation
MachineRegionInfoPass()
MachineRegionInfoPass::MachineRegionInfoPass () explicit
Definition at line 78 of file MachineRegionInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::initializeMachineRegionInfoPassPass(), and ~MachineRegionInfoPass().
Referenced by llvm::createMachineRegionInfoPass().
~MachineRegionInfoPass()
MachineRegionInfoPass::~MachineRegionInfoPass () override default
Referenced by MachineRegionInfoPass().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MachineRegionInfoPass::dump () const
Definition at line 123 of file MachineRegionInfo.cpp.
References llvm::RegionInfoBase< Tr >::dump(), and ID.
getAnalysisUsage()
void MachineRegionInfoPass::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 110 of file MachineRegionInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getRegionInfo() [1/2]
MachineRegionInfo& llvm::MachineRegionInfoPass::getRegionInfo () inline
Definition at line 94 of file MachineRegionInfo.h.
Referenced by llvm::GraphTraits< MachineRegionInfoPass * >::getEntryNode(), llvm::GraphTraits< MachineRegionInfoPass * >::nodes_begin(), and llvm::GraphTraits< MachineRegionInfoPass * >::nodes_end().
getRegionInfo() [2/2]
const MachineRegionInfo& llvm::MachineRegionInfoPass::getRegionInfo () const inline
Definition at line 96 of file MachineRegionInfo.h.
References llvm::dump(), F(), and print().
print()
void MachineRegionInfoPass::print (raw_ostream & OS, const Module * M) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 118 of file MachineRegionInfo.cpp.
References llvm::RegionInfoBase< Tr >::print().
releaseMemory()
void MachineRegionInfoPass::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 98 of file MachineRegionInfo.cpp.
References llvm::RegionInfoBase< Tr >::releaseMemory().
Referenced by runOnMachineFunction().
runOnMachineFunction()
bool MachineRegionInfoPass::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 84 of file MachineRegionInfo.cpp.
References DF, llvm::RegionInfoBase< Tr >::dump(), LLVM_DEBUG, llvm::MachineRegionInfo::recalculate(), and releaseMemory().
verifyAnalysis()
void MachineRegionInfoPass::verifyAnalysis () const override virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented from llvm::Pass.
Definition at line 102 of file MachineRegionInfo.cpp.
References llvm::RegionInfoBase< Tr >::verifyAnalysis(), and llvm::RegionInfoBase< RegionTraits< MachineFunction > >::VerifyRegionInfo.
Member Data Documentation
ID
char MachineRegionInfoPass::ID = 0 static
Definition at line 89 of file MachineRegionInfo.h.
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineRegionInfo.h
lib/CodeGen/MachineRegionInfo.cpp