LLVM: llvm::object::ResourceSectionRef Class Reference
llvm::object::ResourceSectionRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
ResourceSectionRef ()=default
ResourceSectionRef (StringRef Ref)
Error load (const COFFObjectFile *O)
Error load (const COFFObjectFile *O, const SectionRef &S)
Expected< ArrayRef< UTF16 > > getEntryNameString (const coff_resource_dir_entry &Entry)
Expected< const coff_resource_dir_table & > getEntrySubDir (const coff_resource_dir_entry &Entry)
Expected< const coff_resource_data_entry & > getEntryData (const coff_resource_dir_entry &Entry)
Expected< const coff_resource_dir_table & > getBaseTable ()
Expected< const coff_resource_dir_entry & > getTableEntry (const coff_resource_dir_table &Table, uint32_t Index)
Expected< StringRef > getContents (const coff_resource_data_entry &Entry)
Detailed Description
Definition at line 1205 of file COFF.h.
Constructor & Destructor Documentation
ResourceSectionRef() [1/2]
llvm::object::ResourceSectionRef::ResourceSectionRef () default
ResourceSectionRef() [2/2]
llvm::object::ResourceSectionRef::ResourceSectionRef (StringRef Ref) inline explicit
Definition at line 1208 of file COFF.h.
References llvm::RISCVFenceField::O, and llvm::ARMBuildAttrs::Section.
Member Function Documentation
getBaseTable()
Expected< const coff_resource_dir_table & > ResourceSectionRef::getBaseTable ()
Definition at line 1733 of file COFFObjectFile.cpp.
Referenced by llvm::object::WindowsResourceParser::parse().
getContents()
Expected< StringRef > ResourceSectionRef::getContents (const coff_resource_data_entry & Entry)
Definition at line 1781 of file COFFObjectFile.cpp.
References llvm::createStringError(), and llvm::object::parse_failed.
getEntryData()
Expected< const coff_resource_data_entry & > ResourceSectionRef::getEntryData (const coff_resource_dir_entry & Entry)
Definition at line 1728 of file COFFObjectFile.cpp.
References assert(), and llvm::object::coff_resource_dir_entry::Offset.
getEntryNameString()
Expected< ArrayRef< UTF16 > > ResourceSectionRef::getEntryNameString (const coff_resource_dir_entry & Entry)
Definition at line 1684 of file COFFObjectFile.cpp.
References assert(), llvm::object::coff_resource_dir_entry::Identifier, llvm::BinaryStreamReader::readObject(), RETURN_IF_ERROR, and llvm::BinaryStreamReader::setOffset().
getEntrySubDir()
Expected< const coff_resource_dir_table & > ResourceSectionRef::getEntrySubDir (const coff_resource_dir_entry & Entry)
Definition at line 1722 of file COFFObjectFile.cpp.
References assert(), and llvm::object::coff_resource_dir_entry::Offset.
getTableEntry()
Expected< const coff_resource_dir_entry & > ResourceSectionRef::getTableEntry (const coff_resource_dir_table & Table, uint32_t Index)
Definition at line 1738 of file COFFObjectFile.cpp.
References llvm::createStringError(), llvm::object::coff_resource_dir_table::NumberOfIDEntries, llvm::object::coff_resource_dir_table::NumberOfNameEntries, and llvm::object::parse_failed.
load() [1/2]
Error ResourceSectionRef::load (const COFFObjectFile * O)
Definition at line 1748 of file COFFObjectFile.cpp.
References llvm::createStringError(), Name, llvm::object::parse_failed, llvm::object::ObjectFile::sections(), and llvm::Expected< T >::takeError().
load() [2/2]
Error ResourceSectionRef::load (const COFFObjectFile * O, const SectionRef & S)
Definition at line 1761 of file COFFObjectFile.cpp.
References B, llvm::support::little, llvm::RISCVFenceField::O, llvm::ARMBuildAttrs::Section, llvm::ArrayRef< T >::size(), llvm::sort(), llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::object::coff_relocation::VirtualAddress.
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp