LLVM: llvm::DWARFAcceleratorTable Class Reference
llvm::DWARFAcceleratorTable Class Reference abstract
The accelerator tables are designed to allow efficient random access (using a symbol name as a key) into debug info by providing an index of the debug info DIEs.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Classes
class Entry
An abstract class representing a single entry in the accelerator tables.
Public Member Functions
DWARFAcceleratorTable (const DWARFDataExtractor &AccelSection, DataExtractor StringSection)
virtual ~DWARFAcceleratorTable ()
virtual Error extract ()=0
virtual void dump (raw_ostream &OS) const =0
DWARFAcceleratorTable (const DWARFAcceleratorTable &)=delete
void operator= (const DWARFAcceleratorTable &)=delete
Protected Attributes
DWARFDataExtractor AccelSection
DataExtractor StringSection
Detailed Description
The accelerator tables are designed to allow efficient random access (using a symbol name as a key) into debug info by providing an index of the debug info DIEs.
This class implements the common functionality of Apple and DWARF 5 accelerator tables. TODO: Generalize the rest of the AppleAcceleratorTable interface and move it to this class.
Definition at line 31 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
DWARFAcceleratorTable() [1/2]
llvm::DWARFAcceleratorTable::DWARFAcceleratorTable (const DWARFDataExtractor & AccelSection, DataExtractor StringSection) inline
Definition at line 69 of file DWARFAcceleratorTable.h.
References dump(), extract(), llvm::DWARFAcceleratorTable::Entry::operator=(), and ~DWARFAcceleratorTable().
~DWARFAcceleratorTable()
DWARFAcceleratorTable::~DWARFAcceleratorTable () virtual default
Referenced by DWARFAcceleratorTable(), and formatAtom().
DWARFAcceleratorTable() [2/2]
llvm::DWARFAcceleratorTable::DWARFAcceleratorTable (const DWARFAcceleratorTable &) delete
Member Function Documentation
dump()
virtual void llvm::DWARFAcceleratorTable::dump (raw_ostream & OS) const pure virtual
Implemented in llvm::DWARFDebugNames, and llvm::AppleAcceleratorTable.
Referenced by llvm::DWARFDebugNames::Abbrev::Abbrev(), llvm::AppleAcceleratorTable::AppleAcceleratorTable(), DWARFAcceleratorTable(), llvm::DWARFDebugNames::DWARFDebugNames(), llvm::DWARFDebugNames::Entry::getAbbrev(), and llvm::DWARFDebugNames::NameIndex::getNextUnitOffset().
extract()
virtual Error llvm::DWARFAcceleratorTable::extract () pure virtual
Implemented in llvm::DWARFDebugNames, and llvm::AppleAcceleratorTable.
Referenced by llvm::AppleAcceleratorTable::AppleAcceleratorTable(), DWARFAcceleratorTable(), llvm::DWARFDebugNames::DWARFDebugNames(), and llvm::DWARFDebugNames::NameIndex::end().
operator=()
void llvm::DWARFAcceleratorTable::operator= (const DWARFAcceleratorTable &) delete
Member Data Documentation
AccelSection
DWARFDataExtractor llvm::DWARFAcceleratorTable::AccelSection protected
Definition at line 33 of file DWARFAcceleratorTable.h.
Referenced by llvm::AppleAcceleratorTable::dump(), llvm::AppleAcceleratorTable::equal_range(), llvm::DWARFDebugNames::extract(), and llvm::AppleAcceleratorTable::ValueIterator::ValueIterator().
StringSection
DataExtractor llvm::DWARFAcceleratorTable::StringSection protected
Definition at line 34 of file DWARFAcceleratorTable.h.
Referenced by llvm::AppleAcceleratorTable::equal_range().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp