LLVM: llvm::cflaa::CFLGraph::ValueInfo Class Reference
llvm::cflaa::CFLGraph::ValueInfo Class Reference
#include "Analysis/CFLGraph.h"
Public Member Functions
bool addNodeToLevel (unsigned Level)
NodeInfo & getNodeInfoAtLevel (unsigned Level)
const NodeInfo & getNodeInfoAtLevel (unsigned Level) const
unsigned getNumLevels () const
Detailed Description
Definition at line 73 of file CFLGraph.h.
Member Function Documentation
addNodeToLevel()
bool llvm::cflaa::CFLGraph::ValueInfo::addNodeToLevel (unsigned Level) inline
Definition at line 77 of file CFLGraph.h.
getNodeInfoAtLevel() [1/2]
NodeInfo& llvm::cflaa::CFLGraph::ValueInfo::getNodeInfoAtLevel (unsigned Level) inline
Definition at line 85 of file CFLGraph.h.
References assert().
getNodeInfoAtLevel() [2/2]
const NodeInfo& llvm::cflaa::CFLGraph::ValueInfo::getNodeInfoAtLevel (unsigned Level) const inline
Definition at line 89 of file CFLGraph.h.
References assert().
getNumLevels()
unsigned llvm::cflaa::CFLGraph::ValueInfo::getNumLevels () const inline
Definition at line 94 of file CFLGraph.h.
References llvm::cflaa::InstantiatedValue::DerefLevel, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), N, and llvm::cflaa::InstantiatedValue::Val.
The documentation for this class was generated from the following file:
lib/Analysis/CFLGraph.h