LLVM: llvm::detail::scope_exit< Callable > Class Template Reference
llvm::detail::scope_exit< Callable > Class Template Reference
#include "llvm/ADT/ScopeExit.h"
Public Member Functions
template<typename Fp >
scope_exit (Fp &&F)
scope_exit (scope_exit &&Rhs)
scope_exit (const scope_exit &)=delete
scope_exit & operator= (scope_exit &&)=delete
scope_exit & operator= (const scope_exit &)=delete
void release ()
~scope_exit ()
Detailed Description
template<typename Callable>
class llvm::detail::scope_exit< Callable >
Definition at line 25 of file ScopeExit.h.
Constructor & Destructor Documentation
scope_exit() [1/3]
template<typename Callable > template<typename Fp > llvm::detail::scope_exit< Callable >::scope_exit (Fp && F) inline explicit
Definition at line 31 of file ScopeExit.h.
Referenced by llvm::detail::scope_exit< Callable >::scope_exit().
scope_exit() [2/3]
template<typename Callable > llvm::detail::scope_exit< Callable >::scope_exit (scope_exit< Callable > && Rhs) inline
Definition at line 33 of file ScopeExit.h.
References llvm::detail::scope_exit< Callable >::operator=(), and llvm::detail::scope_exit< Callable >::scope_exit().
scope_exit() [3/3]
template<typename Callable > llvm::detail::scope_exit< Callable >::scope_exit (const scope_exit< Callable > &) delete
~scope_exit()
template<typename Callable > llvm::detail::scope_exit< Callable >::~scope_exit () inline
Definition at line 43 of file ScopeExit.h.
References LLVM_NODISCARD.
Member Function Documentation
operator=() [1/2]
template<typename Callable > scope_exit& llvm::detail::scope_exit< Callable >::operator= (scope_exit< Callable > &&) delete
Referenced by llvm::detail::scope_exit< Callable >::scope_exit().
operator=() [2/2]
template<typename Callable > scope_exit& llvm::detail::scope_exit< Callable >::operator= (const scope_exit< Callable > &) delete
release()
template<typename Callable > void llvm::detail::scope_exit< Callable >::release () inline
Definition at line 41 of file ScopeExit.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ScopeExit.h