LLVM: llvm::orc::BasicObjectLayerMaterializationUnit Class Reference
llvm::orc::BasicObjectLayerMaterializationUnit Class Reference
Materializes the given object file (represented by a MemoryBuffer instance) by calling 'emit' on the given ObjectLayer.
#include "llvm/ExecutionEngine/Orc/Layer.h"
Public Member Functions
BasicObjectLayerMaterializationUnit (ObjectLayer &L, VModuleKey K, std::unique_ptr< MemoryBuffer > O, SymbolFlagsMap SymbolFlags)
StringRef getName () const override
Return the buffer's identifier as the name for this MaterializationUnit.
Public Member Functions inherited from llvm::orc::MaterializationUnit
MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, VModuleKey K)
virtual ~MaterializationUnit ()
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
void doMaterialize (JITDylib &JD)
Called by materialization dispatchers (see ExecutionSession::DispatchMaterializationFunction) to trigger materialization of this MaterializationUnit.
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Static Public Member Functions
static Expected< std::unique_ptr< BasicObjectLayerMaterializationUnit > > Create (ObjectLayer &L, VModuleKey K, std::unique_ptr< MemoryBuffer > O)
Additional Inherited Members
Protected Attributes inherited from llvm::orc::MaterializationUnit
SymbolFlagsMap SymbolFlags
VModuleKey K
Detailed Description
Materializes the given object file (represented by a MemoryBuffer instance) by calling 'emit' on the given ObjectLayer.
Definition at line 149 of file Layer.h.
Constructor & Destructor Documentation
BasicObjectLayerMaterializationUnit()
llvm::orc::BasicObjectLayerMaterializationUnit::BasicObjectLayerMaterializationUnit (ObjectLayer & L, VModuleKey K, std::unique_ptr< MemoryBuffer > O, SymbolFlagsMap SymbolFlags)
Definition at line 164 of file Layer.cpp.
Member Function Documentation
Create()
Expected< std::unique_ptr< BasicObjectLayerMaterializationUnit > > llvm::orc::BasicObjectLayerMaterializationUnit::Create (ObjectLayer & L, VModuleKey K, std::unique_ptr< MemoryBuffer > O) static
Definition at line 151 of file Layer.cpp.
References llvm::orc::ObjectLayer::getExecutionSession(), and llvm::orc::getObjectSymbolFlags().
Referenced by llvm::orc::ObjectLayer::add().
getName()
StringRef llvm::orc::BasicObjectLayerMaterializationUnit::getName () const override virtual
Return the buffer's identifier as the name for this MaterializationUnit.
Implements llvm::orc::MaterializationUnit.
Definition at line 170 of file Layer.cpp.
References llvm::orc::ObjectLayer::emit().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Layer.h
lib/ExecutionEngine/Orc/Layer.cpp