LLVM: llvm::codeview::TagRecord Class Reference
llvm::codeview::TagRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
bool hasUniqueName () const
bool isNested () const
bool isForwardRef () const
bool containsNestedClass () const
bool isScoped () const
uint16_t getMemberCount () const
ClassOptions getOptions () const
TypeIndex getFieldList () const
StringRef getName () const
StringRef getUniqueName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
uint16_t MemberCount = 0
ClassOptions Options
TypeIndex FieldList
StringRef Name
StringRef UniqueName
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Static Public Attributes
static const int HfaKindShift = 11
static const int HfaKindMask = 0x1800
static const int WinRTKindShift = 14
static const int WinRTKindMask = 0xC000
Protected Member Functions
TagRecord ()=default
TagRecord (TypeRecordKind Kind)
TagRecord (TypeRecordKind Kind, uint16_t MemberCount, ClassOptions Options, TypeIndex FieldList, StringRef Name, StringRef UniqueName)
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 421 of file TypeRecord.h.
Constructor & Destructor Documentation
TagRecord() [1/3]
llvm::codeview::TagRecord::TagRecord () protected default
TagRecord() [2/3]
llvm::codeview::TagRecord::TagRecord (TypeRecordKind Kind) inline explicit protected
Definition at line 424 of file TypeRecord.h.
TagRecord() [3/3]
llvm::codeview::TagRecord::TagRecord (TypeRecordKind Kind, uint16_t MemberCount, ClassOptions Options, TypeIndex FieldList, StringRef Name, StringRef UniqueName) inline protected
Definition at line 425 of file TypeRecord.h.
Member Function Documentation
containsNestedClass()
bool llvm::codeview::TagRecord::containsNestedClass () const inline
Definition at line 448 of file TypeRecord.h.
References llvm::codeview::ContainsNestedClass, and llvm::codeview::None.
getFieldList()
TypeIndex llvm::codeview::TagRecord::getFieldList () const inline
Definition at line 458 of file TypeRecord.h.
References llvm::codeview::FieldList.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getMemberCount()
uint16_t llvm::codeview::TagRecord::getMemberCount () const inline
Definition at line 456 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getName()
StringRef llvm::codeview::TagRecord::getName () const inline
Definition at line 459 of file TypeRecord.h.
References Name.
Referenced by llvm::pdb::TpiStream::findFullDeclForForwardRef(), getHashForUdt(), llvm::pdb::NativeTypeUDT::getName(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getOptions()
ClassOptions llvm::codeview::TagRecord::getOptions () const inline
Definition at line 457 of file TypeRecord.h.
Referenced by getHashForUdt(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getUniqueName()
StringRef llvm::codeview::TagRecord::getUniqueName () const inline
Definition at line 460 of file TypeRecord.h.
Referenced by llvm::pdb::TpiStream::findFullDeclForForwardRef(), getHashForUdt(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
hasUniqueName()
bool llvm::codeview::TagRecord::hasUniqueName () const inline
Definition at line 436 of file TypeRecord.h.
References llvm::codeview::HasUniqueName, and llvm::codeview::None.
Referenced by llvm::pdb::TpiStream::findFullDeclForForwardRef(), and llvm::codeview::TypeRecordMapping::visitMemberEnd().
isForwardRef()
bool llvm::codeview::TagRecord::isForwardRef () const inline
Definition at line 444 of file TypeRecord.h.
References llvm::codeview::ForwardReference, and llvm::codeview::None.
isNested()
bool llvm::codeview::TagRecord::isNested () const inline
Definition at line 440 of file TypeRecord.h.
References llvm::codeview::Nested, and llvm::codeview::None.
isScoped()
bool llvm::codeview::TagRecord::isScoped () const inline
Definition at line 452 of file TypeRecord.h.
References llvm::codeview::None, and llvm::codeview::Scoped.
Member Data Documentation
FieldList
TypeIndex llvm::codeview::TagRecord::FieldList
Definition at line 464 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
HfaKindMask
const int llvm::codeview::TagRecord::HfaKindMask = 0x1800 static
Definition at line 432 of file TypeRecord.h.
HfaKindShift
const int llvm::codeview::TagRecord::HfaKindShift = 11 static
Definition at line 431 of file TypeRecord.h.
MemberCount
uint16_t llvm::codeview::TagRecord::MemberCount = 0
Definition at line 462 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Name
StringRef llvm::codeview::TagRecord::Name
Definition at line 465 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Options
ClassOptions llvm::codeview::TagRecord::Options
Definition at line 463 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeUDT::hasAssignmentOperator(), llvm::pdb::NativeTypeUDT::hasCastOperator(), llvm::pdb::NativeTypeUDT::hasConstructor(), llvm::pdb::NativeTypeUDT::hasNestedTypes(), llvm::pdb::NativeTypeUDT::hasOverloadedOperator(), llvm::pdb::NativeTypeUDT::isIntrinsic(), llvm::pdb::NativeTypeUDT::isNested(), llvm::pdb::NativeTypeUDT::isPacked(), llvm::pdb::NativeTypeUDT::isScoped(), and llvm::codeview::TypeRecordMapping::visitMemberEnd().
UniqueName
StringRef llvm::codeview::TagRecord::UniqueName
Definition at line 466 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
WinRTKindMask
const int llvm::codeview::TagRecord::WinRTKindMask = 0xC000 static
Definition at line 434 of file TypeRecord.h.
WinRTKindShift
const int llvm::codeview::TagRecord::WinRTKindShift = 14 static
Definition at line 433 of file TypeRecord.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h