LLVM: llvm::DWARFDebugPubTable Class Reference
llvm::DWARFDebugPubTable Class Reference
Represents structure for holding and parsing .debug_pub* tables.
#include "llvm/DebugInfo/DWARF/DWARFDebugPubTable.h"
Classes
struct Entry
struct Set
Each table consists of sets of variable length entries.
Public Member Functions
DWARFDebugPubTable (const DWARFObject &Obj, const DWARFSection &Sec, bool LittleEndian, bool GnuStyle)
void dump (raw_ostream &OS) const
ArrayRef< Set > getData ()
Detailed Description
Represents structure for holding and parsing .debug_pub* tables.
Definition at line 24 of file DWARFDebugPubTable.h.
Constructor & Destructor Documentation
DWARFDebugPubTable()
DWARFDebugPubTable::DWARFDebugPubTable (const DWARFObject & Obj, const DWARFSection & Sec, bool LittleEndian, bool GnuStyle)
Definition at line 21 of file DWARFDebugPubTable.cpp.
References llvm::DWARFSection::Data, llvm::DWARFDebugPubTable::Set::Entries, llvm::DataExtractor::getCStrRef(), llvm::DWARFDataExtractor::getRelocatedValue(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), llvm::DataExtractor::isValidOffset(), llvm::DWARFDebugPubTable::Set::Length, Name, llvm::DWARFDebugPubTable::Set::Offset, llvm::DWARFDebugPubTable::Set::Size, llvm::StringRef::size(), and llvm::DWARFDebugPubTable::Set::Version.
Member Function Documentation
dump()
void DWARFDebugPubTable::dump (raw_ostream & OS) const
Definition at line 48 of file DWARFDebugPubTable.cpp.
References llvm::StringRef::data(), llvm::DWARFDebugPubTable::Entry::Descriptor, E, llvm::format(), llvm::dwarf::GDBIndexEntryKindString(), llvm::dwarf::GDBIndexEntryLinkageString(), llvm::dwarf::PubIndexEntryDescriptor::Kind, llvm::dwarf::PubIndexEntryDescriptor::Linkage, llvm::DWARFDebugPubTable::Entry::Name, and llvm::DWARFDebugPubTable::Entry::SecOffset.
getData()
ArrayRef<Set> llvm::DWARFDebugPubTable::getData () inline
Definition at line 75 of file DWARFDebugPubTable.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugPubTable.h
lib/DebugInfo/DWARF/DWARFDebugPubTable.cpp