LLVM: llvm::AMDGPU::HSAMD::MetadataStreamer Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamer Class Reference abstract
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
virtual ~MetadataStreamer ()
virtual bool emitTo (AMDGPUTargetStreamer &TargetStreamer)=0
virtual void begin (const Module &Mod)=0
virtual void end ()=0
virtual void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo)=0
Detailed Description
Definition at line 38 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
~MetadataStreamer()
virtual llvm::AMDGPU::HSAMD::MetadataStreamer::~MetadataStreamer () inline virtual
Definition at line 40 of file AMDGPUHSAMetadataStreamer.h.
References begin(), emitKernel(), emitTo(), end(), and llvm::Mod.
Member Function Documentation
begin()
virtual void llvm::AMDGPU::HSAMD::MetadataStreamer::begin (const Module & Mod) pure virtual
Implemented in llvm::AMDGPU::HSAMD::MetadataStreamerV2, and llvm::AMDGPU::HSAMD::MetadataStreamerV3.
Referenced by ~MetadataStreamer().
emitKernel()
virtual void llvm::AMDGPU::HSAMD::MetadataStreamer::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) pure virtual
Implemented in llvm::AMDGPU::HSAMD::MetadataStreamerV2, and llvm::AMDGPU::HSAMD::MetadataStreamerV3.
Referenced by ~MetadataStreamer().
emitTo()
virtual bool llvm::AMDGPU::HSAMD::MetadataStreamer::emitTo (AMDGPUTargetStreamer & TargetStreamer) pure virtual
Implemented in llvm::AMDGPU::HSAMD::MetadataStreamerV2, and llvm::AMDGPU::HSAMD::MetadataStreamerV3.
Referenced by ~MetadataStreamer().
end()
virtual void llvm::AMDGPU::HSAMD::MetadataStreamer::end () pure virtual
Implemented in llvm::AMDGPU::HSAMD::MetadataStreamerV2, and llvm::AMDGPU::HSAMD::MetadataStreamerV3.
Referenced by ~MetadataStreamer().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h