LLVM: llvm::HexagonFrameLowering Class Reference
llvm::HexagonFrameLowering Class Reference
#include "Target/Hexagon/HexagonFrameLowering.h"
Public Member Functions
HexagonFrameLowering ()
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
Perform most of the PEI work here:
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool enableCalleeSaveSkip (const MachineFunction &MF) const override
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
bool canSimplifyCallFramePseudos (const MachineFunction &MF) const override
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
bool targetHandlesStackFrameRounding () const override
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const override
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
bool needsAligna (const MachineFunction &MF) const
const MachineInstr * getAlignaInstr (const MachineFunction &MF) const
void insertCFIInstructions (MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None(), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool isFPCloseToIncomingSP () const
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 30 of file HexagonFrameLowering.h.
Constructor & Destructor Documentation
HexagonFrameLowering()
llvm::HexagonFrameLowering::HexagonFrameLowering () inline explicit
Definition at line 32 of file HexagonFrameLowering.h.
References emitPrologue().
Member Function Documentation
assignCalleeSavedSpillSlots()
bool HexagonFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1461 of file HexagonFrameLowering.cpp.
References add(), llvm::MachineInstrBuilder::addImm(), llvm::LivePhysRegs::addLiveIns(), llvm::MachineInstrBuilder::addReg(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), B, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::LivePhysRegs::contains(), contains(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), dump_registers(), E, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getIndex(), llvm::getKillRegState(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineFunction::getName(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterInfo::getReservedRegs(), llvm::TargetRegisterInfo::getSpillAlignment(), llvm::TargetRegisterInfo::getSpillSize(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineOperand::isFI(), llvm::MachineOperand::isKill(), llvm::isPowerOf2_32(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::RegState::Kill, LLVM_DEBUG, llvm_unreachable, llvm::HexagonInstrInfo::loadRegFromStackSlot(), MI, MRI, llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Size, llvm::LivePhysRegs::stepForward(), and llvm::HexagonInstrInfo::storeRegToStackSlot().
Referenced by getCalleeSavedSpillSlots().
canSimplifyCallFramePseudos()
bool llvm::HexagonFrameLowering::canSimplifyCallFramePseudos (const MachineFunction & MF) const inline override virtual
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
This is possible only when frame index references between the pseudos won't need adjusting for the call frame adjustments. Normally, that's true if the function has a reserved call frame or a frame pointer. Some targets (Thumb2, for example) may have more complicated criteria, however, and can override this behavior.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 62 of file HexagonFrameLowering.h.
References determineCalleeSaves(), eliminateCallFramePseudoInstr(), I, and processFunctionBeforeFrameFinalized().
determineCalleeSaves()
void HexagonFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1975 of file HexagonFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::HexagonII::BaseImmOffset, llvm::SmallSet< T, N, C >::count(), llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::dbgs(), llvm::RegState::Dead, llvm::TargetFrameLowering::determineCalleeSaves(), llvm::SmallVectorBase::empty(), llvm::HexagonBlockRanges::expandToSubRegs(), F(), llvm::HexagonRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonBlockRanges::InstrIndexMap::getIndex(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::TargetRegisterClass::getRawAllocationOrder(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::HexagonMachineFunctionInfo::hasEHReturn(), llvm::TargetRegisterClass::hasSubClassEq(), llvm::tgtok::In, llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isFI(), isOptNone(), LLVM_DEBUG, llvm::SPII::Load, MRI, needToReserveScavengingSpillSlots(), llvm::None, NumberScavengerSlots, OptimizeSpillSlots, P, llvm::printMBBReference(), Reg, llvm::BitVector::resize(), llvm::BitVector::set(), SI, Size, and llvm::SPII::Store.
Referenced by canSimplifyCallFramePseudos().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator HexagonFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1342 of file HexagonFrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::getOpcode(), I, and MI.
Referenced by canSimplifyCallFramePseudos().
emitEpilogue()
void llvm::HexagonFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const inline override virtual
Implements llvm::TargetFrameLowering.
Definition at line 40 of file HexagonFrameLowering.h.
References enableCalleeSaveSkip().
emitPrologue()
void HexagonFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Perform most of the PEI work here:
saving/restoring of the callee-saved registers,
stack frame creation and destruction. Normally, this work is distributed among various functions, but doing it in one place allows shrink-wrapping of the stack frame.
Implements llvm::TargetFrameLowering.
Definition at line 503 of file HexagonFrameLowering.cpp.
References llvm::MachineInstr::addOperand(), B, llvm::MachineOperand::CreateReg(), EnableShrinkWrapping, llvm::MachineFunction::front(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getNumBlockIDs(), llvm::MachineInstr::getOpcode(), getReturn(), llvm::MachineFunction::getSubtarget(), and isRestoreCall().
Referenced by HexagonFrameLowering().
enableCalleeSaveSkip()
bool HexagonFrameLowering::enableCalleeSaveSkip (const MachineFunction & MF) const override virtual
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 554 of file HexagonFrameLowering.cpp.
References assert(), F(), llvm::MachineFunction::getFunction(), and llvm::MachineFunction::getSubtarget().
Referenced by emitEpilogue().
getAlignaInstr()
const MachineInstr * HexagonFrameLowering::getAlignaInstr (const MachineFunction & MF) const
Definition at line 2452 of file HexagonFrameLowering.cpp.
References llvm::MachineInstr::addOperand(), contains(), llvm::MachineOperand::CreateReg(), llvm::CodeGenOpt::Default, llvm::MachineFrameInfo::estimateStackSize(), F(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::TargetMachine::getOptLevel(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::HexagonMachineFunctionInfo::hasEHReturn(), I, llvm::MachineOperand::isFI(), isMinSize(), isOptSize(), LLVM_FALLTHROUGH, llvm::AArch64CC::LS, MI, N, SpillFuncThreshold, SpillFuncThresholdOs, and Threshold.
Referenced by getCalleeSavedSpillSlots().
getCalleeSavedSpillSlots()
const SpillSlot* llvm::HexagonFrameLowering::getCalleeSavedSpillSlots (unsigned & NumEntries) const inline override virtual
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Each entry in this array contains a <register,offset> pair, indicating the fixed offset from the incoming stack pointer that each register should be spilled at. If a register is not listed here, the code generator is allowed to spill it anywhere it chooses.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 84 of file HexagonFrameLowering.h.
References llvm::array_lengthof(), assignCalleeSavedSpillSlots(), B, getAlignaInstr(), insertCFIInstructions(), MI, MRI, needsAligna(), TII, and TRI.
getFrameIndexReference()
int HexagonFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
Returns the displacement from the frame register to the stack frame of the specified index, along with the frame register used (in output arg FrameReg).
The offset is returned directly, and the base register is returned via FrameReg.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1110 of file HexagonFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineInstr::copyImplicitOps(), EnableSaveRestoreLong, EnableStackOVFSanitizer, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::HexagonSubtarget::getInstrInfo(), getMaxCalleeSavedReg(), llvm::TargetMachine::getOptLevel(), llvm::MachineBasicBlock::getParent(), getSpillFunctionFor(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), hasReturn(), hasTailCall(), I, llvm::HexagonRegisterInfo::isEHReturnCalleeSaveReg(), llvm::TargetMachine::isPositionIndependent(), MI, llvm::CodeGenOpt::None, Reg, SK_FromMem, SK_FromMemTailcall, and SK_ToMem.
Referenced by targetHandlesStackFrameRounding().
hasFP()
bool HexagonFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 992 of file HexagonFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), EliminateFramePointer, enableAllocFrameElim(), EnableStackOVFSanitizer, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getOptLevel(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::Function::hasFnAttribute(), llvm::CodeGenOpt::None, llvm::TargetMachine::Options, and llvm::SystemZISD::TM.
Referenced by llvm::HexagonRegisterInfo::getFrameRegister(), and targetHandlesStackFrameRounding().
hasReservedCallFrame()
bool llvm::HexagonFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const inline override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 57 of file HexagonFrameLowering.h.
insertCFIInstructions()
void HexagonFrameLowering::insertCFIInstructions (MachineFunction & MF) const
Definition at line 871 of file HexagonFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), B, llvm::BuildMI(), C, llvm::MCCFIInstruction::createDefCfa(), llvm::MCCFIInstruction::createOffset(), llvm::MCContext::createTempSymbol(), F(), llvm::find_if(), findCFILocation(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonSubtarget::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), R2, and Reg.
Referenced by getCalleeSavedSpillSlots().
needsAligna()
bool HexagonFrameLowering::needsAligna (const MachineFunction & MF) const
Definition at line 2442 of file HexagonFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by getCalleeSavedSpillSlots().
processFunctionBeforeFrameFinalized()
void HexagonFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1353 of file HexagonFrameLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::alignTo(), assert(), llvm::SmallSet< T, N, C >::count(), llvm::numbers::e, llvm::SmallSet< T, N, C >::empty(), llvm::X86AS::FS, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getLocalFrameMaxAlign(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::MachineFrameInfo::mapLocalFrameObject(), llvm::max(), MI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineFrameInfo::setLocalFrameMaxAlign(), llvm::MachineFrameInfo::setLocalFrameSize(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::HexagonMachineFunctionInfo::setStackAlignBasePhysReg(), and llvm::MachineFrameInfo::setUseLocalStackAllocationBlock().
Referenced by canSimplifyCallFramePseudos().
restoreCalleeSavedRegisters()
bool llvm::HexagonFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const inline override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 51 of file HexagonFrameLowering.h.
spillCalleeSavedRegisters()
bool llvm::HexagonFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const inline override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 45 of file HexagonFrameLowering.h.
targetHandlesStackFrameRounding()
bool llvm::HexagonFrameLowering::targetHandlesStackFrameRounding () const inline override virtual
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
Reimplemented from llvm::TargetFrameLowering.
Definition at line 76 of file HexagonFrameLowering.h.
References getFrameIndexReference(), and hasFP().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonFrameLowering.h
lib/Target/Hexagon/HexagonFrameLowering.cpp