LLVM: llvm::codeview::PrecompRecord Class Reference
llvm::codeview::PrecompRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
PrecompRecord ()=default
PrecompRecord (TypeRecordKind Kind)
uint32_t getStartTypeIndex () const
uint32_t getTypesCount () const
uint32_t getSignature () const
StringRef getPrecompFilePath () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
uint32_t StartTypeIndex = 0
uint32_t TypesCount = 0
uint32_t Signature = 0
StringRef PrecompFilePath
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 934 of file TypeRecord.h.
Constructor & Destructor Documentation
PrecompRecord() [1/2]
llvm::codeview::PrecompRecord::PrecompRecord () default
PrecompRecord() [2/2]
llvm::codeview::PrecompRecord::PrecompRecord (TypeRecordKind Kind) inline explicit
Definition at line 937 of file TypeRecord.h.
Member Function Documentation
getPrecompFilePath()
StringRef llvm::codeview::PrecompRecord::getPrecompFilePath () const inline
Definition at line 942 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getSignature()
uint32_t llvm::codeview::PrecompRecord::getSignature () const inline
Definition at line 941 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getStartTypeIndex()
uint32_t llvm::codeview::PrecompRecord::getStartTypeIndex () const inline
Definition at line 939 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getTypesCount()
uint32_t llvm::codeview::PrecompRecord::getTypesCount () const inline
Definition at line 940 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
Member Data Documentation
PrecompFilePath
StringRef llvm::codeview::PrecompRecord::PrecompFilePath
Definition at line 947 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Signature
uint32_t llvm::codeview::PrecompRecord::Signature = 0
Definition at line 946 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
StartTypeIndex
uint32_t llvm::codeview::PrecompRecord::StartTypeIndex = 0
Definition at line 944 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
TypesCount
uint32_t llvm::codeview::PrecompRecord::TypesCount = 0
Definition at line 945 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h