LLVM: llvm::MemorySSAUtil Class Reference
llvm::MemorySSAUtil Class Reference
#include "llvm/Analysis/MemorySSA.h"
Static Protected Member Functions
static bool defClobbersUseOrDef (MemoryDef *MD, const MemoryUseOrDef *MU, AliasAnalysis &AA)
Friends
class GVNHoist
class MemorySSAWalker
Detailed Description
Definition at line 901 of file MemorySSA.h.
Member Function Documentation
defClobbersUseOrDef()
bool MemorySSAUtil::defClobbersUseOrDef (MemoryDef * MD, const MemoryUseOrDef * MU, AliasAnalysis & AA) static protected
Definition at line 329 of file MemorySSA.cpp.
References llvm::MemoryLocation::get(), instructionClobbersQuery(), and llvm::MayAlias.
Referenced by llvm::GVNHoist::rank().
Friends And Related Function Documentation
GVNHoist
friend class GVNHoist friend
Definition at line 903 of file MemorySSA.h.
MemorySSAWalker
friend class MemorySSAWalker friend
Definition at line 904 of file MemorySSA.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemorySSA.h
lib/Analysis/MemorySSA.cpp