LLVM: llvm::DIContext Class Reference
llvm::DIContext Class Reference abstract
#include "llvm/DebugInfo/DIContext.h"
Public Types
enum DIContextKind { CK_DWARF, CK_PDB }
Public Member Functions
DIContext (DIContextKind K)
virtual ~DIContext ()=default
DIContextKind getKind () const
virtual void dump (raw_ostream &OS, DIDumpOptions DumpOpts)=0
virtual bool verify (raw_ostream &OS, DIDumpOptions DumpOpts={})
virtual DILineInfo getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DILineInfoTable getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DIInliningInfo getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual std::vector< DILocal > getLocalsForAddress (object::SectionedAddress Address)=0
Detailed Description
Definition at line 204 of file DIContext.h.
Member Enumeration Documentation
DIContextKind
enum llvm::DIContext::DIContextKind
Enumerator
CK_DWARF
CK_PDB
Definition at line 206 of file DIContext.h.
Constructor & Destructor Documentation
DIContext()
llvm::DIContext::DIContext (DIContextKind K) inline
Definition at line 211 of file DIContext.h.
~DIContext()
virtual llvm::DIContext::~DIContext () virtual default
Member Function Documentation
dump()
virtual void llvm::DIContext::dump (raw_ostream & OS, DIDumpOptions DumpOpts) pure virtual
Implemented in llvm::DWARFContext, and llvm::pdb::PDBContext.
getInliningInfoForAddress()
virtual DIInliningInfo llvm::DIContext::getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext, and llvm::pdb::PDBContext.
getKind()
DIContextKind llvm::DIContext::getKind () const inline
Definition at line 214 of file DIContext.h.
References llvm::DILineInfo::dump().
Referenced by llvm::pdb::PDBContext::classof(), and llvm::DWARFContext::classof().
getLineInfoForAddress()
virtual DILineInfo llvm::DIContext::getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext, and llvm::pdb::PDBContext.
getLineInfoForAddressRange()
virtual DILineInfoTable llvm::DIContext::getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext, and llvm::pdb::PDBContext.
getLocalsForAddress()
virtual std::vector<DILocal> llvm::DIContext::getLocalsForAddress (object::SectionedAddress Address) pure virtual
Implemented in llvm::DWARFContext, and llvm::pdb::PDBContext.
verify()
virtual bool llvm::DIContext::verify (raw_ostream & OS, DIDumpOptions DumpOpts = {}) inline virtual
Reimplemented in llvm::DWARFContext.
Definition at line 218 of file DIContext.h.
References llvm::Address, and Size.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DIContext.h