LLVM: llvm::codeview::DebugSymbolsSubsection Class Reference
llvm::codeview::DebugSymbolsSubsection Class Reference final
#include "llvm/DebugInfo/CodeView/DebugSymbolsSubsection.h"
Public Member Functions
DebugSymbolsSubsection ()
uint32_t calculateSerializedSize () const override
Error commit (BinaryStreamWriter &Writer) const override
void addSymbol (CVSymbol Symbol)
Public Member Functions inherited from llvm::codeview::DebugSubsection
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsection
static bool classof (const DebugSubsection *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsection
DebugSubsectionKind Kind
Detailed Description
Definition at line 36 of file DebugSymbolsSubsection.h.
Constructor & Destructor Documentation
DebugSymbolsSubsection()
llvm::codeview::DebugSymbolsSubsection::DebugSymbolsSubsection () inline
Definition at line 38 of file DebugSymbolsSubsection.h.
Member Function Documentation
addSymbol()
void DebugSymbolsSubsection::addSymbol (CVSymbol Symbol)
Definition at line 30 of file DebugSymbolsSubsection.cpp.
References llvm::codeview::CVRecord< Kind >::length().
calculateSerializedSize()
uint32_t DebugSymbolsSubsection::calculateSerializedSize () const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 18 of file DebugSymbolsSubsection.cpp.
classof()
static bool llvm::codeview::DebugSymbolsSubsection::classof (const DebugSubsection * S) inline static
Definition at line 39 of file DebugSymbolsSubsection.h.
References llvm::codeview::DebugSubsection::kind(), llvm::ARMBuildAttrs::Symbol, and llvm::codeview::Symbols.
commit()
Error DebugSymbolsSubsection::commit (BinaryStreamWriter & Writer) const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 22 of file DebugSymbolsSubsection.cpp.
References llvm::codeview::EC, llvm::Error::success(), and llvm::BinaryStreamWriter::writeBytes().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSymbolsSubsection.h
lib/DebugInfo/CodeView/DebugSymbolsSubsection.cpp