LLVM: llvm::NonLocalDepResult Class Reference
llvm::NonLocalDepResult Class Reference
This is a result from a NonLocal dependence query.
#include "llvm/Analysis/MemoryDependenceAnalysis.h"
Public Member Functions
NonLocalDepResult (BasicBlock *bb, MemDepResult result, Value *address)
BasicBlock * getBB () const
void setResult (const MemDepResult &R, Value *Addr)
const MemDepResult & getResult () const
Value * getAddress () const
Returns the address of this pointer in this block.
Detailed Description
This is a result from a NonLocal dependence query.
For each BasicBlock (the BB entry) it keeps a MemDepResult and the (potentially phi translated) address that was live in the block.
Definition at line 235 of file MemoryDependenceAnalysis.h.
Constructor & Destructor Documentation
NonLocalDepResult()
llvm::NonLocalDepResult::NonLocalDepResult (BasicBlock * bb, MemDepResult result, Value * address) inline
Definition at line 240 of file MemoryDependenceAnalysis.h.
Member Function Documentation
getAddress()
Value* llvm::NonLocalDepResult::getAddress () const inline
Returns the address of this pointer in this block.
This can be different than the address queried for the non-local result because of phi translation. This returns null if the address was not available in a block (i.e. because phi translation failed) or if this is a cached result and that address was deleted.
The address is always null for a non-local 'call' dependence.
Definition at line 261 of file MemoryDependenceAnalysis.h.
References llvm::Address.
getBB()
BasicBlock* llvm::NonLocalDepResult::getBB () const inline
Definition at line 244 of file MemoryDependenceAnalysis.h.
References llvm::NonLocalDepEntry::getBB().
getResult()
const MemDepResult& llvm::NonLocalDepResult::getResult () const inline
Definition at line 251 of file MemoryDependenceAnalysis.h.
References llvm::NonLocalDepEntry::getResult().
setResult()
void llvm::NonLocalDepResult::setResult (const MemDepResult & R, Value * Addr) inline
Definition at line 246 of file MemoryDependenceAnalysis.h.
References llvm::NonLocalDepEntry::setResult().
The documentation for this class was generated from the following file:
include/llvm/Analysis/MemoryDependenceAnalysis.h