LLVM: llvm::PressureDiffs Class Reference
llvm::PressureDiffs Class Reference
Array of PressureDiffs.
#include "llvm/CodeGen/RegisterPressure.h"
Public Member Functions
PressureDiffs ()=default
~PressureDiffs ()
void clear ()
void init (unsigned N)
Initialize an array of N PressureDiffs.
PressureDiff & operator[] (unsigned Idx)
const PressureDiff & operator[] (unsigned Idx) const
void addInstruction (unsigned Idx, const RegisterOperands &RegOpers, const MachineRegisterInfo &MRI)
Record pressure difference induced by the given operand list to node with index Idx.
Detailed Description
Array of PressureDiffs.
Definition at line 198 of file RegisterPressure.h.
Constructor & Destructor Documentation
PressureDiffs()
llvm::PressureDiffs::PressureDiffs () default
~PressureDiffs()
llvm::PressureDiffs::~PressureDiffs () inline
Definition at line 205 of file RegisterPressure.h.
Member Function Documentation
addInstruction()
void PressureDiffs::addInstruction (unsigned Idx, const RegisterOperands & RegOpers, const MachineRegisterInfo & MRI)
Record pressure difference induced by the given operand list to node with index Idx.
Definition at line 657 of file RegisterPressure.cpp.
References llvm::PressureDiff::addPressureChange(), assert(), llvm::PressureDiff::begin(), llvm::RegisterOperands::Defs, llvm::PressureChange::isValid(), P, llvm::RegisterMaskPair::RegUnit, and llvm::RegisterOperands::Uses.
Referenced by llvm::ScheduleDAGInstrs::buildSchedGraph().
clear()
void llvm::PressureDiffs::clear () inline
Definition at line 207 of file RegisterPressure.h.
References llvm::cl::init(), and N.
init()
void PressureDiffs::init (unsigned N)
Initialize an array of N PressureDiffs.
Definition at line 646 of file RegisterPressure.cpp.
References N, llvm::safe_calloc(), and Size.
Referenced by llvm::ScheduleDAGInstrs::buildSchedGraph().
operator[]() [1/2]
PressureDiff& llvm::PressureDiffs::operator[] (unsigned Idx) inline
Definition at line 211 of file RegisterPressure.h.
References assert().
operator[]() [2/2]
const PressureDiff& llvm::PressureDiffs::operator[] (unsigned Idx) const inline
Definition at line 215 of file RegisterPressure.h.
References MRI.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterPressure.h
lib/CodeGen/RegisterPressure.cpp