LLVM: llvm::pdb::UDTLayoutBase Class Reference
llvm::pdb::UDTLayoutBase Class Reference
#include "llvm/DebugInfo/PDB/UDTLayout.h"
Public Member Functions
UDTLayoutBase (const UDTLayoutBase *Parent, const PDBSymbol &Sym, const std::string &Name, uint32_t OffsetInParent, uint32_t Size, bool IsElided)
uint32_t tailPadding () const override
ArrayRef< LayoutItemBase * > layout_items () const
ArrayRef< BaseClassLayout * > bases () const
ArrayRef< BaseClassLayout * > regular_bases () const
ArrayRef< BaseClassLayout * > virtual_bases () const
uint32_t directVirtualBaseCount () const
ArrayRef< std::unique_ptr< PDBSymbolFunc > > funcs () const
ArrayRef< std::unique_ptr< PDBSymbol > > other_items () const
Public Member Functions inherited from llvm::pdb::LayoutItemBase
LayoutItemBase (const UDTLayoutBase *Parent, const PDBSymbol *Symbol, const std::string &Name, uint32_t OffsetInParent, uint32_t Size, bool IsElided)
virtual ~LayoutItemBase ()=default
uint32_t deepPaddingSize () const
virtual uint32_t immediatePadding () const
const UDTLayoutBase * getParent () const
StringRef getName () const
uint32_t getOffsetInParent () const
uint32_t getSize () const
uint32_t getLayoutSize () const
const PDBSymbol * getSymbol () const
const BitVector & usedBytes () const
bool isElided () const
virtual bool isVBPtr () const
uint32_t containsOffset (uint32_t Off) const
Protected Member Functions
bool hasVBPtrAtOffset (uint32_t Off) const
void initializeChildren (const PDBSymbol &Sym)
void addChildToLayout (std::unique_ptr< LayoutItemBase > Child)
Protected Attributes
uint32_t DirectVBaseCount = 0
UniquePtrVector< PDBSymbol > Other
UniquePtrVector< PDBSymbolFunc > Funcs
UniquePtrVector< LayoutItemBase > ChildStorage
std::vector< LayoutItemBase * > LayoutItems
std::vector< BaseClassLayout * > AllBases
ArrayRef< BaseClassLayout * > NonVirtualBases
ArrayRef< BaseClassLayout * > VirtualBases
VTableLayoutItem * VTable = nullptr
VBPtrLayoutItem * VBPtr = nullptr
Protected Attributes inherited from llvm::pdb::LayoutItemBase
const PDBSymbol * Symbol = nullptr
const UDTLayoutBase * Parent = nullptr
BitVector UsedBytes
std::string Name
uint32_t OffsetInParent = 0
uint32_t SizeOf = 0
uint32_t LayoutSize = 0
bool IsElided = false
Detailed Description
Definition at line 110 of file UDTLayout.h.
Constructor & Destructor Documentation
UDTLayoutBase()
UDTLayoutBase::UDTLayoutBase (const UDTLayoutBase * Parent, const PDBSymbol & Sym, const std::string & Name, uint32_t OffsetInParent, uint32_t Size, bool IsElided)
Definition at line 104 of file UDTLayout.cpp.
References initializeChildren(), llvm::pdb::LayoutItemBase::LayoutSize, llvm::BitVector::reset(), llvm::BitVector::resize(), and llvm::pdb::LayoutItemBase::UsedBytes.
Member Function Documentation
addChildToLayout()
void UDTLayoutBase::addChildToLayout (std::unique_ptr< LayoutItemBase > Child) protected
Definition at line 277 of file UDTLayout.cpp.
References ChildStorage, llvm::BitVector::count(), llvm::pdb::LayoutItemBase::getOffsetInParent(), LayoutItems, llvm::BitVector::resize(), llvm::BitVector::size(), llvm::upper_bound(), and llvm::pdb::LayoutItemBase::UsedBytes.
Referenced by initializeChildren().
bases()
ArrayRef<BaseClassLayout *> llvm::pdb::UDTLayoutBase::bases () const inline
Definition at line 120 of file UDTLayout.h.
directVirtualBaseCount()
uint32_t llvm::pdb::UDTLayoutBase::directVirtualBaseCount () const inline
Definition at line 123 of file UDTLayout.h.
funcs()
ArrayRef<std::unique_ptr<PDBSymbolFunc> > llvm::pdb::UDTLayoutBase::funcs () const inline
Definition at line 124 of file UDTLayout.h.
hasVBPtrAtOffset()
bool UDTLayoutBase::hasVBPtrAtOffset (uint32_t Off) const protected
Definition at line 267 of file UDTLayout.cpp.
References AllBases, llvm::ARCISD::BL, llvm::pdb::LayoutItemBase::getOffsetInParent(), and VBPtr.
Referenced by initializeChildren().
initializeChildren()
void UDTLayoutBase::initializeChildren (const PDBSymbol & Sym) protected
Definition at line 165 of file UDTLayout.cpp.
References addChildToLayout(), AllBases, assert(), llvm::ARCISD::BL, llvm::pdb::Data, DM, llvm::BitVector::find_last(), llvm::pdb::PDBSymbol::findAllChildren(), Funcs, hasVBPtrAtOffset(), llvm::pdb::LayoutItemBase::LayoutSize, llvm::makeArrayRef(), llvm::pdb::Member, NonVirtualBases, Other, llvm::pdb::LayoutItemBase::Parent, llvm::pdb::LayoutItemBase::UsedBytes, llvm::codeview::VB, VBPtr, VirtualBases, and VTable.
Referenced by UDTLayoutBase().
layout_items()
ArrayRef<LayoutItemBase *> llvm::pdb::UDTLayoutBase::layout_items () const inline
Definition at line 119 of file UDTLayout.h.
other_items()
ArrayRef<std::unique_ptr<PDBSymbol> > llvm::pdb::UDTLayoutBase::other_items () const inline
Definition at line 125 of file UDTLayout.h.
References Other.
regular_bases()
ArrayRef<BaseClassLayout *> llvm::pdb::UDTLayoutBase::regular_bases () const inline
Definition at line 121 of file UDTLayout.h.
tailPadding()
uint32_t UDTLayoutBase::tailPadding () const override virtual
Reimplemented from llvm::pdb::LayoutItemBase.
Definition at line 117 of file UDTLayout.cpp.
References LayoutItems, and llvm::pdb::LayoutItemBase::tailPadding().
virtual_bases()
ArrayRef<BaseClassLayout *> llvm::pdb::UDTLayoutBase::virtual_bases () const inline
Definition at line 122 of file UDTLayout.h.
Member Data Documentation
AllBases
std::vector<BaseClassLayout *> llvm::pdb::UDTLayoutBase::AllBases protected
Definition at line 140 of file UDTLayout.h.
Referenced by hasVBPtrAtOffset(), and initializeChildren().
ChildStorage
UniquePtrVector<LayoutItemBase> llvm::pdb::UDTLayoutBase::ChildStorage protected
Definition at line 137 of file UDTLayout.h.
Referenced by addChildToLayout().
DirectVBaseCount
uint32_t llvm::pdb::UDTLayoutBase::DirectVBaseCount = 0 protected
Definition at line 133 of file UDTLayout.h.
Funcs
UniquePtrVector<PDBSymbolFunc> llvm::pdb::UDTLayoutBase::Funcs protected
Definition at line 136 of file UDTLayout.h.
Referenced by initializeChildren().
LayoutItems
std::vector<LayoutItemBase *> llvm::pdb::UDTLayoutBase::LayoutItems protected
Definition at line 138 of file UDTLayout.h.
Referenced by addChildToLayout(), llvm::pdb::ClassLayout::ClassLayout(), and tailPadding().
NonVirtualBases
ArrayRef<BaseClassLayout *> llvm::pdb::UDTLayoutBase::NonVirtualBases protected
Definition at line 141 of file UDTLayout.h.
Referenced by initializeChildren().
Other
UniquePtrVector<PDBSymbol> llvm::pdb::UDTLayoutBase::Other protected
Definition at line 135 of file UDTLayout.h.
Referenced by initializeChildren().
VBPtr
VBPtrLayoutItem* llvm::pdb::UDTLayoutBase::VBPtr = nullptr protected
Definition at line 145 of file UDTLayout.h.
Referenced by hasVBPtrAtOffset(), and initializeChildren().
VirtualBases
ArrayRef<BaseClassLayout *> llvm::pdb::UDTLayoutBase::VirtualBases protected
Definition at line 142 of file UDTLayout.h.
Referenced by initializeChildren().
VTable
VTableLayoutItem* llvm::pdb::UDTLayoutBase::VTable = nullptr protected
Definition at line 144 of file UDTLayout.h.
Referenced by initializeChildren().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/UDTLayout.h
lib/DebugInfo/PDB/UDTLayout.cpp