LLVM: llvm::MCRelocationInfo Class Reference
llvm::MCRelocationInfo Class Reference
Create MCExprs from relocations found in an object file.
#include "llvm/MC/MCDisassembler/MCRelocationInfo.h"
Public Member Functions
MCRelocationInfo (MCContext &Ctx)
MCRelocationInfo (const MCRelocationInfo &)=delete
MCRelocationInfo & operator= (const MCRelocationInfo &)=delete
virtual ~MCRelocationInfo ()
virtual const MCExpr * createExprForCAPIVariantKind (const MCExpr *SubExpr, unsigned VariantKind)
Create an MCExpr for the target-specific VariantKind.
Protected Attributes
MCContext & Ctx
Detailed Description
Create MCExprs from relocations found in an object file.
Definition at line 24 of file MCRelocationInfo.h.
Constructor & Destructor Documentation
MCRelocationInfo() [1/2]
MCRelocationInfo::MCRelocationInfo (MCContext & Ctx)
Definition at line 15 of file MCRelocationInfo.cpp.
References ~MCRelocationInfo().
Referenced by llvm::createMCRelocationInfo().
MCRelocationInfo() [2/2]
llvm::MCRelocationInfo::MCRelocationInfo (const MCRelocationInfo &) delete
~MCRelocationInfo()
MCRelocationInfo::~MCRelocationInfo () virtual default
Referenced by MCRelocationInfo().
Member Function Documentation
createExprForCAPIVariantKind()
const MCExpr * MCRelocationInfo::createExprForCAPIVariantKind (const MCExpr * SubExpr, unsigned VariantKind) virtual
Create an MCExpr for the target-specific VariantKind.
The VariantKinds are defined in llvm-c/Disassembler.h. Used by MCExternalSymbolizer.
Returns
If possible, an MCExpr corresponding to VariantKind, else 0.
Definition at line 20 of file MCRelocationInfo.cpp.
References LLVMDisassembler_VariantKind_None.
operator=()
MCRelocationInfo& llvm::MCRelocationInfo::operator= (const MCRelocationInfo &) delete
Member Data Documentation
Ctx
MCContext& llvm::MCRelocationInfo::Ctx protected
Definition at line 26 of file MCRelocationInfo.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCDisassembler/MCRelocationInfo.h
lib/MC/MCDisassembler/MCRelocationInfo.cpp