LLVM: llvm::detail::PtrUseVisitorBase Class Reference
llvm::detail::PtrUseVisitorBase Class Reference
Implementation of non-dependent functionality for PtrUseVisitor.
#include "llvm/Analysis/PtrUseVisitor.h"
Classes
class PtrInfo
This class provides information about the result of a visit.
struct UseToVisit
A struct of the data needed to visit a particular use.
Protected Member Functions
PtrUseVisitorBase (const DataLayout &DL)
Note that the constructor is protected because this class must be a base class, we can't create instances directly of this class.
void enqueueUsers (Instruction &I)
Enqueue the users of this instruction in the visit worklist.
bool adjustOffsetForGEP (GetElementPtrInst &GEPI)
Walk the operands of a GEP and adjust the offset as appropriate.
Protected Attributes
const DataLayout & DL
Visitation infrastructure
PtrInfo PI
The info collected about the pointer being visited thus far.
SmallVector< UseToVisit, 8 > Worklist
The worklist of to-visit uses.
SmallPtrSet< Use *, 8 > VisitedUses
A set of visited uses to break cycles in unreachable code.
Per-visit state
This state is reset for each instruction visited.
Use * U
The use currently being visited.
bool IsOffsetKnown
True if we have a known constant offset for the use currently being visited.
APInt Offset
The constant offset of the use if that is known.
Detailed Description
Implementation of non-dependent functionality for PtrUseVisitor.
See PtrUseVisitor for the public interface and detailed comments about usage. This class is just a helper base class which is not templated and contains all common code to be shared between different instantiations of PtrUseVisitor.
Definition at line 55 of file PtrUseVisitor.h.
Constructor & Destructor Documentation
PtrUseVisitorBase()
llvm::detail::PtrUseVisitorBase::PtrUseVisitorBase (const DataLayout & DL) inline protected
Note that the constructor is protected because this class must be a base class, we can't create instances directly of this class.
Definition at line 163 of file PtrUseVisitor.h.
References adjustOffsetForGEP(), enqueueUsers(), and I.
Member Function Documentation
adjustOffsetForGEP()
bool detail::PtrUseVisitorBase::adjustOffsetForGEP (GetElementPtrInst & GEPI) protected
Walk the operands of a GEP and adjust the offset as appropriate.
This routine does the heavy lifting of the pointer walk by computing offsets and looking through GEPs.
Definition at line 33 of file PtrUseVisitor.cpp.
References llvm::GetElementPtrInst::accumulateConstantOffset(), DL, llvm::APInt::getBitWidth(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::Value::getType(), IsOffsetKnown, Offset, and llvm::APInt::sextOrTrunc().
Referenced by PtrUseVisitorBase(), and llvm::PtrUseVisitor< SliceBuilder >::visitGetElementPtrInst().
enqueueUsers()
void detail::PtrUseVisitorBase::enqueueUsers (Instruction & I) protected
Enqueue the users of this instruction in the visit worklist.
This will visit the users with the same offset of the current visit (including an unknown offset if that is the current state).
Definition at line 21 of file PtrUseVisitor.cpp.
References IsOffsetKnown, Offset, U, llvm::Value::uses(), VisitedUses, and Worklist.
Referenced by PtrUseVisitorBase(), llvm::PtrUseVisitor< SliceBuilder >::visitAddrSpaceCastInst(), llvm::PtrUseVisitor< SliceBuilder >::visitBitCastInst(), llvm::PtrUseVisitor< SliceBuilder >::visitGetElementPtrInst(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
Member Data Documentation
DL
const DataLayout& llvm::detail::PtrUseVisitorBase::DL protected
Definition at line 118 of file PtrUseVisitor.h.
Referenced by adjustOffsetForGEP(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
IsOffsetKnown
bool llvm::detail::PtrUseVisitorBase::IsOffsetKnown protected
True if we have a known constant offset for the use currently being visited.
Definition at line 154 of file PtrUseVisitor.h.
Referenced by adjustOffsetForGEP(), enqueueUsers(), llvm::PtrUseVisitor< SliceBuilder >::visitGetElementPtrInst(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
Offset
APInt llvm::detail::PtrUseVisitorBase::Offset protected
The constant offset of the use if that is known.
Definition at line 157 of file PtrUseVisitor.h.
Referenced by adjustOffsetForGEP(), enqueueUsers(), llvm::PtrUseVisitor< SliceBuilder >::visitGetElementPtrInst(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
PI
PtrInfo llvm::detail::PtrUseVisitorBase::PI protected
The info collected about the pointer being visited thus far.
Definition at line 124 of file PtrUseVisitor.h.
Referenced by llvm::PtrUseVisitor< SliceBuilder >::visitCallSite(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), llvm::PtrUseVisitor< SliceBuilder >::visitPtrToIntInst(), and llvm::PtrUseVisitor< SliceBuilder >::visitStoreInst().
U
Use* llvm::detail::PtrUseVisitorBase::U protected
The use currently being visited.
Definition at line 150 of file PtrUseVisitor.h.
Referenced by enqueueUsers(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), and llvm::PtrUseVisitor< SliceBuilder >::visitStoreInst().
VisitedUses
SmallPtrSet<Use *, 8> llvm::detail::PtrUseVisitorBase::VisitedUses protected
A set of visited uses to break cycles in unreachable code.
Definition at line 141 of file PtrUseVisitor.h.
Referenced by enqueueUsers().
Worklist
SmallVector<UseToVisit, 8> llvm::detail::PtrUseVisitorBase::Worklist protected
The worklist of to-visit uses.
Definition at line 138 of file PtrUseVisitor.h.
Referenced by enqueueUsers(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
The documentation for this class was generated from the following files:
include/llvm/Analysis/PtrUseVisitor.h
lib/Analysis/PtrUseVisitor.cpp