LLVM: llvm::codeview::CVSymbolDumper Class Reference
llvm::codeview::CVSymbolDumper Class Reference
Dumper for CodeView symbol streams found in COFF object files and PDB files.
#include "llvm/DebugInfo/CodeView/SymbolDumper.h"
Public Member Functions
CVSymbolDumper (ScopedPrinter &W, TypeCollection &Types, CodeViewContainer Container, std::unique_ptr< SymbolDumpDelegate > ObjDelegate, CPUType CPU, bool PrintRecordBytes)
Error dump (CVRecord< SymbolKind > &Record)
Dumps one type record.
Error dump (const CVSymbolArray &Symbols)
Dumps the type records in Data.
CPUType getCompilationCPUType () const
Detailed Description
Dumper for CodeView symbol streams found in COFF object files and PDB files.
Definition at line 25 of file SymbolDumper.h.
Constructor & Destructor Documentation
CVSymbolDumper()
llvm::codeview::CVSymbolDumper::CVSymbolDumper (ScopedPrinter & W, TypeCollection & Types, CodeViewContainer Container, std::unique_ptr< SymbolDumpDelegate > ObjDelegate, CPUType CPU, bool PrintRecordBytes) inline
Definition at line 27 of file SymbolDumper.h.
References dump(), and llvm::codeview::Symbols.
Member Function Documentation
dump() [1/2]
Error CVSymbolDumper::dump (CVRecord< SymbolKind > & Record)
Dumps one type record.
Returns false if there was a type parsing error, and true otherwise. This should be called in order, since the dumper maintains state about previous records which are necessary for cross type references.
Definition at line 653 of file SymbolDumper.cpp.
References llvm::codeview::SymbolVisitorCallbackPipeline::addCallbackToPipeline(), and llvm::RISCVFenceField::W.
Referenced by CVSymbolDumper().
dump() [2/2]
Error CVSymbolDumper::dump (const CVSymbolArray & Symbols)
Dumps the type records in Data.
Returns false if there was a type stream parse error, and true otherwise.
Definition at line 667 of file SymbolDumper.cpp.
References llvm::codeview::SymbolVisitorCallbackPipeline::addCallbackToPipeline(), and llvm::RISCVFenceField::W.
getCompilationCPUType()
CPUType llvm::codeview::CVSymbolDumper::getCompilationCPUType () const inline
Definition at line 45 of file SymbolDumper.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/SymbolDumper.h
lib/DebugInfo/CodeView/SymbolDumper.cpp