LLVM: llvm::SIFrameLowering Class Reference
llvm::SIFrameLowering Class Reference final
#include "Target/AMDGPU/SIFrameLowering.h"
Public Member Functions
SIFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None())
~SIFrameLowering () override=default
void emitEntryFunctionPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
void determineCalleeSavesSGPR (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
bool isSupportedStackID (TargetStackID::Value ID) const override
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
Public Member Functions inherited from llvm::AMDGPUFrameLowering
AMDGPUFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None())
~AMDGPUFrameLowering () override
unsigned getStackWidth (const MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None(), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool isFPCloseToIncomingSP () const
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 21 of file SIFrameLowering.h.
Constructor & Destructor Documentation
SIFrameLowering()
llvm::SIFrameLowering::SIFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl = Align::None()) inline
Definition at line 23 of file SIFrameLowering.h.
References assignCalleeSavedSpillSlots(), determineCalleeSaves(), determineCalleeSavesSGPR(), eliminateCallFramePseudoInstr(), emitEntryFunctionPrologue(), emitEpilogue(), emitPrologue(), getFrameIndexReference(), hasFP(), I, isSupportedStackID(), MI, processFunctionBeforeFrameFinalized(), llvm::ARM_MB::ST, TII, TRI, and ~SIFrameLowering().
~SIFrameLowering()
llvm::SIFrameLowering::~SIFrameLowering () override default
Referenced by SIFrameLowering().
Member Function Documentation
assignCalleeSavedSpillSlots()
bool SIFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1070 of file SIFrameLowering.cpp.
References llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), and llvm::SIMachineFunctionInfo::SGPRForFPSaveRestoreCopy.
Referenced by SIFrameLowering().
determineCalleeSaves()
void SIFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS = nullptr) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 979 of file SIFrameLowering.cpp.
References llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPR(), allStackObjectsAreDead(), llvm::BitVector::any(), llvm::BitVector::clearBitsNotInMask(), llvm::MachineFrameInfo::CreateStackObject(), llvm::dbgs(), llvm::TargetFrameLowering::determineCalleeSaves(), findUnusedSGPRNonCalleeSaved(), llvm::SIMachineFunctionInfo::FramePointerSaveIndex, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIMachineFunctionInfo::getSGPRSpillVGPRs(), llvm::SIMachineFunctionInfo::getSGPRToVGPRSpills(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasCalls(), hasFP(), llvm::SIMachineFunctionInfo::haveFreeLanesForSGPRSpill(), llvm::AMDGPUMachineFunction::isEntryFunction(), LLVM_DEBUG, llvm_unreachable, llvm::printReg(), llvm::BitVector::reset(), llvm::SIMachineFunctionInfo::SGPRForFPSaveRestoreCopy, and llvm::TargetStackID::SGPRSpill.
Referenced by SIFrameLowering().
determineCalleeSavesSGPR()
void SIFrameLowering::determineCalleeSavesSGPR (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS = nullptr) const
Definition at line 1054 of file SIFrameLowering.cpp.
References llvm::BitVector::clearBitsInMask(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUMachineFunction::isEntryFunction(), and llvm::BitVector::reset().
Referenced by SIFrameLowering().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator SIFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1091 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::alignTo(), assert(), llvm::BuildMI(), llvm::MachineBasicBlock::erase(), llvm::MDNode::get(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::TargetFrameLowering::hasReservedCallFrame(), llvm::isUInt< 32 >(), and llvm_unreachable.
Referenced by SIFrameLowering().
emitEntryFunctionPrologue()
void SIFrameLowering::emitEntryFunctionPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const
Definition at line 392 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineRegisterInfo::addLiveIn(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), AMDGPUAS::CONSTANT_ADDRESS, F(), llvm::MachineFunction::front(), llvm::MDNode::get(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::SIMachineFunctionInfo::getGITPtrHigh(), llvm::SIMachineFunctionInfo::getImplicitBufferPtrUserSGPR(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFunction::getRegInfo(), llvm::SIInstrInfo::getRegisterInfo(), llvm::SIInstrInfo::getScratchRsrcWords23(), llvm::AMDGPU::getSMRDEncodedOffset(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasFP(), llvm::SIMachineFunctionInfo::hasImplicitBufferPtr(), llvm::GCNSubtarget::hasMergedShaders(), I, llvm::RegState::ImplicitDefine, llvm::AMDGPUSubtarget::isAmdHsaOrMesa(), llvm::AMDGPUSubtarget::isAmdPalOS(), llvm::AMDGPU::isCompute(), llvm::GCNSubtarget::isMesaGfxShader(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::RegState::Kill, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::MachineMemOperand::MOLoad, MRI, llvm::AMDGPUFunctionArgInfo::PRIVATE_SEGMENT_BUFFER, and llvm::AMDGPUFunctionArgInfo::PRIVATE_SEGMENT_WAVE_BYTE_OFFSET.
Referenced by emitPrologue(), and SIFrameLowering().
emitEpilogue()
void SIFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 822 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::LivePhysRegs::addLiveOuts(), assert(), buildEpilogReload(), llvm::BuildMI(), llvm::LivePhysRegs::empty(), findScratchNonCalleeSaveRegister(), llvm::MachineInstr::FrameDestroy, llvm::SIMachineFunctionInfo::FramePointerSaveIndex, llvm::MachineInstr::FrameSetup, llvm::MDNode::get(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::SIMachineFunctionInfo::getScratchRSrcReg(), llvm::SIMachineFunctionInfo::getSGPRSpillVGPRs(), llvm::SIMachineFunctionInfo::getSGPRToVGPRSpills(), llvm::MachineFrameInfo::getStackID(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::Optional< T >::getValue(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::SIRegisterInfo::getWaveMaskRegClass(), hasFP(), llvm::LivePhysRegs::init(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::SIMachineFunctionInfo::isStackRealigned(), llvm::GCNSubtarget::isWave32(), llvm::RegState::Kill, MRI, Reg, llvm::LivePhysRegs::removeReg(), llvm::MachineInstrBuilder::setMIFlag(), llvm::SIMachineFunctionInfo::SGPRForFPSaveRestoreCopy, llvm::TargetStackID::SGPRSpill, and llvm::LivePhysRegs::stepBackward().
Referenced by SIFrameLowering().
emitPrologue()
void SIFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 676 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::LivePhysRegs::addLiveIns(), llvm::LivePhysRegs::addReg(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), buildPrologSpill(), emitEntryFunctionPrologue(), llvm::LivePhysRegs::empty(), findScratchNonCalleeSaveRegister(), llvm::SIMachineFunctionInfo::FramePointerSaveIndex, llvm::MachineInstr::FrameSetup, llvm::MDNode::get(), llvm::MachineFunction::getFrameInfo(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::getScratchRSrcReg(), llvm::SIMachineFunctionInfo::getSGPRSpillVGPRs(), llvm::SIMachineFunctionInfo::getSGPRToVGPRSpills(), llvm::MachineFrameInfo::getStackID(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::Optional< T >::getValue(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::SIRegisterInfo::getWaveMaskRegClass(), hasFP(), llvm::LivePhysRegs::init(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::GCNSubtarget::isWave32(), llvm::RegState::Kill, MRI, Reg, llvm::LivePhysRegs::removeReg(), llvm::SIMachineFunctionInfo::setIsStackRealigned(), llvm::MachineInstrBuilder::setMIFlag(), llvm::SIMachineFunctionInfo::SGPRForFPSaveRestoreCopy, llvm::TargetStackID::SGPRSpill, and llvm::RegState::Undef.
Referenced by SIFrameLowering().
getFrameIndexReference()
int SIFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
Returns the displacement from the frame register to the stack frame of the specified index, along with the frame register used (in output arg FrameReg).
The offset is returned directly, and the base register is returned via FrameReg.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 937 of file SIFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::SIRegisterInfo::getFrameRegister(), llvm::MachineFrameInfo::getObjectOffset(), and llvm::MachineFunction::getSubtarget().
Referenced by SIFrameLowering().
hasFP()
bool SIFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 1125 of file SIFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasCalls(), llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
Referenced by buildEpilogReload(), determineCalleeSaves(), emitEntryFunctionPrologue(), emitEpilogue(), emitPrologue(), llvm::SIRegisterInfo::getFrameRegister(), reservePrivateMemoryRegs(), and SIFrameLowering().
isSupportedStackID()
bool SIFrameLowering::isSupportedStackID (TargetStackID::Value ID) const override virtual
Reimplemented from llvm::TargetFrameLowering.
Definition at line 664 of file SIFrameLowering.cpp.
References llvm::TargetStackID::Default, llvm_unreachable, llvm::TargetStackID::NoAlloc, llvm::TargetStackID::SGPRSpill, and llvm::TargetStackID::SVEVector.
Referenced by SIFrameLowering().
processFunctionBeforeFrameFinalized()
void SIFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 945 of file SIFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), assert(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::None, and llvm::SIMachineFunctionInfo::removeDeadFrameIndices().
Referenced by SIFrameLowering().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIFrameLowering.h
lib/Target/AMDGPU/SIFrameLowering.cpp