LLVM: llvm::SpeculativeExecutionPass Class Reference
llvm::SpeculativeExecutionPass Class Reference
#include "llvm/Transforms/Scalar/SpeculativeExecution.h"
Public Member Functions
SpeculativeExecutionPass (bool OnlyIfDivergentTarget=false)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, TargetTransformInfo *TTI)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SpeculativeExecutionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 69 of file SpeculativeExecution.h.
Constructor & Destructor Documentation
SpeculativeExecutionPass()
llvm::SpeculativeExecutionPass::SpeculativeExecutionPass (bool OnlyIfDivergentTarget = false)
Definition at line 305 of file SpeculativeExecution.cpp.
Member Function Documentation
run()
PreservedAnalyses llvm::SpeculativeExecutionPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 309 of file SpeculativeExecution.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool llvm::SpeculativeExecutionPass::runImpl (Function & F, TargetTransformInfo * TTI)
Definition at line 153 of file SpeculativeExecution.cpp.
References B, llvm::dbgs(), llvm::dyn_cast(), llvm::BranchInst::getNumSuccessors(), llvm::BasicBlock::getSinglePredecessor(), llvm::BasicBlock::getSingleSuccessor(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::TargetTransformInfo::hasBranchDivergence(), LLVM_DEBUG, runOnBasicBlock(), and llvm::BasicBlock::size().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/SpeculativeExecution.h
lib/Transforms/Scalar/SpeculativeExecution.cpp