LLVM: llvm::dwarf::FrameEntry Class Reference
llvm::dwarf::FrameEntry Class Reference abstract
An entry in either debug_frame or eh_frame.
#include "llvm/DebugInfo/DWARF/DWARFDebugFrame.h"
Public Types
enum FrameKind { FK_CIE, FK_FDE }
Public Member Functions
FrameEntry (FrameKind K, uint64_t Offset, uint64_t Length, uint64_t CodeAlign, int64_t DataAlign, Triple::ArchType Arch)
virtual ~FrameEntry ()
FrameKind getKind () const
uint64_t getOffset () const
uint64_t getLength () const
const CFIProgram & cfis () const
CFIProgram & cfis ()
virtual void dump (raw_ostream &OS, const MCRegisterInfo *MRI, bool IsEH) const =0
Dump the instructions in this CFI fragment.
Protected Attributes
const FrameKind Kind
const uint64_t Offset
Offset of this entry in the section.
const uint64_t Length
Entry length as specified in DWARF.
CFIProgram CFIs
Detailed Description
An entry in either debug_frame or eh_frame.
This entry can be a CIE or an FDE.
Definition at line 131 of file DWARFDebugFrame.h.
Member Enumeration Documentation
FrameKind
enum llvm::dwarf::FrameEntry::FrameKind
Enumerator
FK_CIE
FK_FDE
Definition at line 133 of file DWARFDebugFrame.h.
Constructor & Destructor Documentation
FrameEntry()
llvm::dwarf::FrameEntry::FrameEntry (FrameKind K, uint64_t Offset, uint64_t Length, uint64_t CodeAlign, int64_t DataAlign, Triple::ArchType Arch) inline
Definition at line 135 of file DWARFDebugFrame.h.
~FrameEntry()
virtual llvm::dwarf::FrameEntry::~FrameEntry () inline virtual
Definition at line 140 of file DWARFDebugFrame.h.
Member Function Documentation
cfis() [1/2]
const CFIProgram& llvm::dwarf::FrameEntry::cfis () const inline
Definition at line 145 of file DWARFDebugFrame.h.
cfis() [2/2]
CFIProgram& llvm::dwarf::FrameEntry::cfis () inline
Definition at line 146 of file DWARFDebugFrame.h.
References llvm::dwarf::CFIProgram::dump(), and MRI.
dump()
virtual void llvm::dwarf::FrameEntry::dump (raw_ostream & OS, const MCRegisterInfo * MRI, bool IsEH) const pure virtual
Dump the instructions in this CFI fragment.
Implemented in llvm::dwarf::FDE, and llvm::dwarf::CIE.
getKind()
FrameKind llvm::dwarf::FrameEntry::getKind () const inline
Definition at line 142 of file DWARFDebugFrame.h.
Referenced by llvm::dwarf::CIE::classof(), and llvm::dwarf::FDE::classof().
getLength()
uint64_t llvm::dwarf::FrameEntry::getLength () const inline
Definition at line 144 of file DWARFDebugFrame.h.
getOffset()
uint64_t llvm::dwarf::FrameEntry::getOffset () const inline
Definition at line 143 of file DWARFDebugFrame.h.
Member Data Documentation
CFIs
CFIProgram llvm::dwarf::FrameEntry::CFIs protected
Definition at line 161 of file DWARFDebugFrame.h.
Kind
const FrameKind llvm::dwarf::FrameEntry::Kind protected
Definition at line 153 of file DWARFDebugFrame.h.
Length
const uint64_t llvm::dwarf::FrameEntry::Length protected
Entry length as specified in DWARF.
Definition at line 159 of file DWARFDebugFrame.h.
Offset
const uint64_t llvm::dwarf::FrameEntry::Offset protected
Offset of this entry in the section.
Definition at line 156 of file DWARFDebugFrame.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFDebugFrame.h