LLVM: llvm::LLT Class Reference
llvm::LLT Class Reference
#include "llvm/Support/LowLevelTypeImpl.h"
Public Member Functions
LLT (bool isPointer, bool isVector, uint16_t NumElements, unsigned SizeInBits, unsigned AddressSpace)
LLT ()
LLT (MVT VT)
bool isValid () const
bool isScalar () const
bool isPointer () const
bool isVector () const
uint16_t getNumElements () const
Returns the number of elements in a vector LLT.
unsigned getSizeInBits () const
Returns the total size of the type. Must only be called on sized types.
unsigned getSizeInBytes () const
Returns the total size of the type in bytes, i.e.
LLT getScalarType () const
LLT changeElementType (LLT NewEltTy) const
If this type is a vector, return a vector with the same number of elements but the new element type.
LLT changeElementSize (unsigned NewEltSize) const
If this type is a vector, return a vector with the same number of elements but the new element size.
bool isByteSized () const
unsigned getScalarSizeInBits () const
unsigned getAddressSpace () const
LLT getElementType () const
Returns the vector's element type. Only valid for vector types.
void print (raw_ostream &OS) const
bool operator== (const LLT &RHS) const
bool operator!= (const LLT &RHS) const
Static Public Member Functions
static LLT scalar (unsigned SizeInBits)
Get a low-level scalar or aggregate "bag of bits".
static LLT pointer (unsigned AddressSpace, unsigned SizeInBits)
Get a low-level pointer in the given address space.
static LLT vector (uint16_t NumElements, unsigned ScalarSizeInBits)
Get a low-level vector of some number of elements and element width.
static LLT vector (uint16_t NumElements, LLT ScalarTy)
Get a low-level vector of some number of elements and element type.
static LLT scalarOrVector (uint16_t NumElements, LLT ScalarTy)
static LLT scalarOrVector (uint16_t NumElements, unsigned ScalarSize)
Friends
struct DenseMapInfo< LLT >
class GISelInstProfileBuilder
Detailed Description
Definition at line 39 of file LowLevelTypeImpl.h.
Constructor & Destructor Documentation
LLT() [1/3]
llvm::LLT::LLT (bool isPointer, bool isVector, uint16_t NumElements, unsigned SizeInBits, unsigned AddressSpace) inline explicit
Definition at line 81 of file LowLevelTypeImpl.h.
LLT() [2/3]
llvm::LLT::LLT () inline explicit
Definition at line 85 of file LowLevelTypeImpl.h.
LLT() [3/3]
LLT::LLT (MVT VT) explicit
Definition at line 18 of file LowLevelType.cpp.
References assert(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::isValid(), and llvm::MVT::isVector().
Member Function Documentation
changeElementSize()
LLT llvm::LLT::changeElementSize (unsigned NewEltSize) const inline
If this type is a vector, return a vector with the same number of elements but the new element size.
Otherwise, return the new element type. Invalid for pointer types. For pointer types, use changeElementType.
Definition at line 133 of file LowLevelTypeImpl.h.
References assert(), getNumElements(), getScalarType(), isPointer(), isVector(), scalar(), and vector().
Referenced by llvm::LegalizerHelper::lowerIntrinsicRound(), and llvm::LegalizeMutations::widenScalarOrEltToNextPow2().
changeElementType()
LLT llvm::LLT::changeElementType (LLT NewEltTy) const inline
If this type is a vector, return a vector with the same number of elements but the new element type.
Otherwise, return the new element type.
Definition at line 126 of file LowLevelTypeImpl.h.
References getNumElements(), isVector(), and vector().
Referenced by llvm::LegalizeMutations::changeElementTo().
getAddressSpace()
unsigned llvm::LLT::getAddressSpace () const inline
Definition at line 157 of file LowLevelTypeImpl.h.
References assert().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::LegalizerInfo::computeTables(), llvm::createMemLibcall(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::InstructionSelector::executeMatchTable(), getElementType(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), isConstant(), llvm::LegalityPredicates::isPointer(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::LegalizerHelper::narrowScalar(), print(), and vector().
getElementType()
LLT llvm::LLT::getElementType () const inline
Returns the vector's element type. Only valid for vector types.
Definition at line 167 of file LowLevelTypeImpl.h.
References assert(), getAddressSpace(), getScalarSizeInBits(), isVector(), pointer(), print(), and scalar().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::CSEMIRBuilder::buildConstant(), llvm::CSEMIRBuilder::buildFConstant(), llvm::LegalizationArtifactCombiner::canFoldMergeOpcode(), llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizeRuleSet::clampMinNumElements(), llvm::LegalizeRuleSet::clampNumElements(), llvm::LegalizerInfo::computeTables(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorBuildVector(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorSelect(), fewerEltsToSize64Vector(), getGCDType(), getHalfSizedType(), getInsertVecEltOpInfo(), getMultipleType(), llvm::getMVTForLLT(), getScalarType(), getVectorSHLImm(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), isRegisterType(), isSmallOddVector(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeRawBufferStore(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerInsert(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::LegalizerHelper::lowerUnmergeValues(), llvm::LegalizeRuleSet::minScalarSameAs(), llvm::LegalizeMutations::moreElementsToNextPow2(), moreEltsToNext32Bit(), llvm::LegalizerHelper::narrowScalar(), oneMoreElement(), packSplitRegsToOrigType(), print(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), unpackRegsToOrigType(), and llvm::LegalizerHelper::widenScalar().
getNumElements()
uint16_t llvm::LLT::getNumElements () const inline
Returns the number of elements in a vector LLT.
Must only be called on vector types.
Definition at line 99 of file LowLevelTypeImpl.h.
References assert().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildSplatVector(), changeElementSize(), changeElementType(), llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizeRuleSet::clampMinNumElements(), llvm::LegalizeRuleSet::clampNumElements(), llvm::GISelKnownBits::computeNumSignBits(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::LegalizerHelper::fewerElementsVectorBuildVector(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorSelect(), fewerEltsToSize64Vector(), getBufferStoreFormatOpcode(), getGCDType(), getHalfSizedType(), getInsertVecEltOpInfo(), llvm::GISelKnownBits::getKnownBits(), llvm::getLLTForType(), getMultipleType(), llvm::getMVTForLLT(), getSizeInBits(), getTypeForLLT(), getVectorSHLImm(), llvm::CallLowering::handleAssignments(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), isRegisterType(), isSmallOddVector(), isWideVec16(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeRawBufferStore(), llvm::AArch64CallLowering::lowerReturn(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::LegalizeMutations::moreElementsToNextPow2(), mutationIsSane(), llvm::LegalizerHelper::narrowScalar(), numElementsNotEven(), llvm::LegalityPredicates::numElementsNotPow2(), oneMoreElement(), packSplitRegsToOrigType(), print(), llvm::MachineIRBuilder::validateSelectOp(), llvm::MachineIRBuilder::validateTruncExt(), and llvm::LegalizerHelper::widenScalar().
getScalarSizeInBits()
unsigned llvm::LLT::getScalarSizeInBits () const inline
Definition at line 142 of file LowLevelTypeImpl.h.
References assert().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFConstant(), llvm::GISelKnownBits::computeNumSignBits(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorSelect(), getBufferStoreFormatOpcode(), getElementType(), getMemsetValue(), getNarrowTypeBreakDown(), getSizeInBits(), getTypeForLLT(), llvm::LegalizerHelper::legalizeInstrStep(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerFCopySign(), llvm::LegalizeRuleSet::maxScalarOrElt(), llvm::LegalizeRuleSet::minScalarOrElt(), llvm::LegalizeRuleSet::minScalarOrEltIf(), mutationIsSane(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarShift(), print(), llvm::LegalityPredicates::scalarOrEltNarrowerThan(), llvm::LegalityPredicates::scalarOrEltSizeNotPow2(), llvm::LegalityPredicates::scalarOrEltWiderThan(), llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic(), llvm::GISelKnownBits::signBitIsZero(), llvm::LegalizationArtifactCombiner::tryCombineSExt(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), llvm::LegalizerHelper::widenScalar(), and llvm::LegalizeMutations::widenScalarOrEltToNextPow2().
getScalarType()
LLT llvm::LLT::getScalarType () const inline
Definition at line 120 of file LowLevelTypeImpl.h.
References getElementType(), and isVector().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingWideLoad(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFConstant(), changeElementSize(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), getMemsetValue(), isMultiple32(), isWideVec16(), llvm::CombinerHelper::matchCombineConcatVectors(), mutationIsSane(), and llvm::LegalizerHelper::narrowScalar().
getSizeInBits()
unsigned llvm::LLT::getSizeInBits () const inline
Returns the total size of the type. Must only be called on sized types.
Definition at line 108 of file LowLevelTypeImpl.h.
References getNumElements(), getScalarSizeInBits(), isPointer(), and isScalar().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::RegisterBankInfo::applyDefaultMapping(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingWideLoad(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildFConstant(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), llvm::MachineIRBuilder::buildSequence(), llvm::MachineIRBuilder::buildUnmerge(), llvm::AMDGPURegisterBankInfo::buildVCopy(), llvm::LegalizationArtifactCombiner::canFoldMergeOpcode(), canTurnIntoCOPY(), changeFCMPPredToAArch64CC(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::LegalizerInfo::computeTables(), llvm::ConstantFoldBinOp(), llvm::ConstantFoldExtOp(), llvm::createMemLibcall(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::InstructionSelector::executeMatchTable(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorImplicitDef(), llvm::LegalizerHelper::fewerElementsVectorSelect(), fewerEltsToSize64Vector(), findGISelOptimalMemOpLowering(), findIntrinsicID(), getBufferStoreFormatOpcode(), getBufferStoreOpcode(), getGCDType(), getHalfSizedType(), getInsertVecEltOpInfo(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), getLaneCopyOpcode(), getLeaOP(), getLogicalBitOpcode(), getMemsetValue(), getMultipleType(), llvm::getMVTForLLT(), getNarrowTypeBreakDown(), getOffsetFromIndices(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), llvm::SIRegisterInfo::getRegClassForTypeOnBank(), getRegClassFromGRPhysReg(), llvm::SITargetLowering::getRegisterByName(), llvm::TargetRegisterInfo::getRegSizeInBits(), getShiftTypeForInst(), getSizeInBytes(), getTypeForLLT(), getVectorSHLImm(), isByteSized(), isConstant(), isMultiple32(), isPreISelGenericFloatingPointOpcode(), isRegisterType(), isSmallOddVector(), isWideScalarTruncStore(), isWideVec16(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::LegalizerHelper::legalizeInstrStep(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::LegalizerHelper::libcall(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerBitCount(), llvm::LegalizerHelper::lowerBitreverse(), llvm::LegalizerHelper::lowerDynStackAlloc(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::LegalizerHelper::lowerInsert(), llvm::AArch64CallLowering::lowerReturn(), llvm::LegalizerHelper::lowerUnmergeValues(), llvm::LegalizeRuleSet::maxScalar(), llvm::LegalizeRuleSet::maxScalarIf(), llvm::LegalizeRuleSet::minScalar(), llvm::LegalizerHelper::moreElementsVector(), moreEltsToNext32Bit(), llvm::LegalityPredicates::narrowerThan(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarMul(), llvm::LegalizerHelper::narrowScalarShiftByConstant(), packSplitRegsToOrigType(), llvm::LegalizerHelper::reduceLoadStoreWidth(), llvm::InstructionSelect::runOnMachineFunction(), selectFPConvOpc(), selectMergeValues(), llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic(), selectUnmergeValues(), setRegsToType(), llvm::AMDGPUInstructionSelector::setupMF(), shouldUseAndMask(), llvm::LegalityPredicates::sizeNotPow2(), sizeToSubRegIndex(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), llvm::LegalizationArtifactCombiner::tryCombineAnyExt(), llvm::LegalizationArtifactCombiner::tryCombineExtract(), llvm::LegalizationArtifactCombiner::tryCombineTrunc(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), unpackRegsToOrigType(), llvm::MachineIRBuilder::validateTruncExt(), vector(), vectorSmallerThan(), vectorWiderThan(), llvm::LegalizerHelper::widenScalar(), llvm::LegalityPredicates::widerThan(), and X86SelectAddress().
getSizeInBytes()
unsigned llvm::LLT::getSizeInBytes () const inline
Returns the total size of the type in bytes, i.e.
number of whole bytes needed to represent the size in bits. Must only be called on sized types.
Definition at line 116 of file LowLevelTypeImpl.h.
References getSizeInBits().
Referenced by llvm::AArch64TargetLowering::allowsMisalignedMemoryAccesses(), findGISelOptimalMemOpLowering(), getMemsetValue(), getVectorSHLImm(), and llvm::LegalizerHelper::lowerBswap().
isByteSized()
bool llvm::LLT::isByteSized () const inline
Definition at line 140 of file LowLevelTypeImpl.h.
References getSizeInBits().
Referenced by llvm::LegalizerInfo::getExtOpcodeForWideningConstant().
isPointer()
bool llvm::LLT::isPointer () const inline
Definition at line 93 of file LowLevelTypeImpl.h.
References isValid().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::MachineIRBuilder::buildCast(), llvm::MachineIRBuilder::buildDynStackAlloc(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFrameIndex(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildPtrMask(), llvm::MachineIRBuilder::buildStore(), changeElementSize(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::LegalizerInfo::computeTables(), llvm::createMemLibcall(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::InstructionSelector::executeMatchTable(), getInsertVecEltOpInfo(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), getSizeInBits(), getVectorSHLImm(), isAmbiguous(), llvm::LegalityPredicates::isPointer(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::LegalizerHelper::narrowScalar(), packSplitRegsToOrigType(), print(), llvm::MipsRegisterBankInfo::setRegBank(), llvm::MachineIRBuilder::validateSelectOp(), and vector().
isScalar()
bool llvm::LLT::isScalar () const inline
Definition at line 91 of file LowLevelTypeImpl.h.
References isValid().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::MachineIRBuilder::buildCast(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegalizerInfo::computeTables(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), getInsertVecEltOpInfo(), llvm::MipsRegisterBankInfo::getInstrMapping(), getLaneCopyOpcode(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), getSizeInBits(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerInsert(), llvm::ARMCallLowering::lowerReturn(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::MachineIRBuilder::materializePtrAdd(), llvm::LegalityPredicates::narrowerThan(), llvm::LegalizerHelper::narrowScalar(), print(), selectFPConvOpc(), shouldUseAndMask(), llvm::LegalityPredicates::sizeNotPow2(), sizeToSubRegIndex(), llvm::MachineIRBuilder::validateBinaryOp(), llvm::MachineIRBuilder::validateSelectOp(), llvm::MachineIRBuilder::validateShiftOp(), llvm::MachineIRBuilder::validateTruncExt(), and llvm::LegalityPredicates::widerThan().
isValid()
bool llvm::LLT::isValid () const inline
Definition at line 89 of file LowLevelTypeImpl.h.
Referenced by llvm::GISelInstProfileBuilder::addNodeIDMachineOperand(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::MIPatternMatch::bind_helper< LLT >::bind(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildStore(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), llvm::MachineRegisterInfo::constrainRegAttrs(), getGCDType(), llvm::AArch64RegisterBankInfo::getInstrMapping(), getNarrowTypeBreakDown(), llvm::AMDGPURegisterBankInfo::getRegBankFromRegClass(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::MachineInstr::getTypeToPrint(), getVectorSHLImm(), isImplicitOperandIn(), isPointer(), isScalar(), isVector(), llvm::LegalizerHelper::legalizeInstrStep(), llvm::CombinerHelper::matchCombineCopy(), print(), llvm::MachineOperand::print(), llvm::printRegClassOrBank(), llvm::LegalizerHelper::reduceLoadStoreWidth(), llvm::InstructionSelect::runOnMachineFunction(), llvm::AMDGPUInstructionSelector::setupMF(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), and unsupportedBinOp().
isVector()
bool llvm::LLT::isVector () const inline
Definition at line 95 of file LowLevelTypeImpl.h.
References isValid().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::CSEMIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::CSEMIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::LegalizationArtifactCombiner::canFoldMergeOpcode(), canTurnIntoCOPY(), changeElementSize(), changeElementType(), llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizeRuleSet::clampMinNumElements(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), llvm::LegalizerInfo::computeTables(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorImplicitDef(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorSelect(), findGISelOptimalMemOpLowering(), getBufferStoreFormatOpcode(), getElementType(), getGCDType(), getHalfSizedType(), getInsertVecEltOpInfo(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::GISelKnownBits::getKnownBits(), getLaneCopyOpcode(), getMemsetValue(), getMultipleType(), llvm::getMVTForLLT(), getNarrowTypeBreakDown(), getRegClassFromGRPhysReg(), getScalarType(), getTypeForLLT(), getVectorShiftImm(), getVectorSHLImm(), llvm::CallLowering::handleAssignments(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), isPreISelGenericFloatingPointOpcode(), isRegisterType(), isSmallOddVector(), isWideScalarTruncStore(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::LegalizerHelper::legalizeInstrStep(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeRawBufferStore(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerInsert(), llvm::AArch64CallLowering::lowerReturn(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::LegalizerHelper::lowerUnmergeValues(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::LegalizeRuleSet::minScalarSameAs(), mutationIsSane(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarMul(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::LegalizerHelper::narrowScalarShift(), numElementsNotEven(), llvm::LegalityPredicates::numElementsNotPow2(), packSplitRegsToOrigType(), print(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), unpackRegsToOrigType(), llvm::MachineIRBuilder::validateBinaryOp(), llvm::MachineIRBuilder::validateSelectOp(), llvm::MachineIRBuilder::validateShiftOp(), llvm::MachineIRBuilder::validateTruncExt(), vector(), vectorSmallerThan(), and vectorWiderThan().
operator!=()
bool llvm::LLT::operator!= (const LLT & RHS) const inline
Definition at line 182 of file LowLevelTypeImpl.h.
operator==()
bool llvm::LLT::operator== (const LLT & RHS) const inline
Definition at line 177 of file LowLevelTypeImpl.h.
pointer()
static LLT llvm::LLT::pointer (unsigned AddressSpace, unsigned SizeInBits) inline static
Get a low-level pointer in the given address space.
Definition at line 49 of file LowLevelTypeImpl.h.
References assert().
Referenced by llvm::AArch64CallLowering::AArch64CallLowering(), llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::ARMLegalizerInfo::ARMLegalizerInfo(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), getElementType(), llvm::getLLTForType(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::MipsCallLowering::MipsHandler::handle(), isSupportedType(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), llvm::X86LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeLoad(), llvm::MipsCallLowering::lowerCall(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), verifyAddrSpace(), and llvm::X86CallLowering::X86CallLowering().
print()
void LLT::print (raw_ostream & OS) const
Definition at line 36 of file LowLevelType.cpp.
References assert(), getAddressSpace(), getElementType(), getNumElements(), getScalarSizeInBits(), isPointer(), isScalar(), isValid(), and isVector().
Referenced by getElementType(), and llvm::operator<<().
scalar()
static LLT llvm::LLT::scalar (unsigned SizeInBits) inline static
Get a low-level scalar or aggregate "bag of bits".
Definition at line 42 of file LowLevelTypeImpl.h.
References assert().
Referenced by llvm::AArch64CallLowering::AArch64CallLowering(), llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), allocateVGPR32Input(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingWideLoad(), llvm::ARMLegalizerInfo::ARMLegalizerInfo(), changeElementSize(), llvm::RegisterBankInfo::OperandsMapper::createVRegs(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), extractF64Exponent(), findGISelOptimalMemOpLowering(), llvm::IRTranslator::getAnalysisUsage(), getElementType(), getGCDType(), getHalfSizedType(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::getLLTForMVT(), llvm::getLLTForType(), getMemsetValue(), getMultipleType(), getNarrowTypeBreakDown(), getOffsetFromIndices(), llvm::AArch64TargetLowering::getOptimalMemOpLLT(), llvm::AMDGPURegisterBankInfo::getRegBankFromRegClass(), llvm::AVRTargetLowering::getRegisterByName(), llvm::PPCTargetLowering::getRegisterByName(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::CallLowering::handleAssignments(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), isConstant(), isSupportedType(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFceil(), llvm::AMDGPULegalizerInfo::legalizeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV16(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFDIVFastIntrin(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::LegalizerHelper::legalizeInstrStep(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::X86LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeIsAddrSpace(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeRawBufferStore(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerBitCount(), llvm::LegalizerHelper::lowerDynStackAlloc(), llvm::LegalizerHelper::lowerExtract(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::LegalizerHelper::lowerInsert(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::AMDGPURegisterBankInfo::lowerScalarMinMax(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::LegalizerHelper::lowerSITOFP(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::LegalizerHelper::lowerUITOFP(), llvm::LegalizerHelper::lowerUnmergeValues(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::LegalizerHelper::moreElementsVector(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarShift(), llvm::LegalizerHelper::reduceLoadStoreWidth(), scalarOrVector(), llvm::MipsRegisterBankInfo::setRegBank(), sizeToSubRegIndex(), llvm::AMDGPURegisterBankInfo::splitBufferOffsets(), verifyAddrSpace(), and llvm::X86CallLowering::X86CallLowering().
scalarOrVector() [1/2]
static LLT llvm::LLT::scalarOrVector (uint16_t NumElements, LLT ScalarTy) inline static
Definition at line 73 of file LowLevelTypeImpl.h.
References vector().
Referenced by llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), fewerEltsToSize64Vector(), getGCDType(), getHalfSizedType(), getNarrowTypeBreakDown(), llvm::LegalizerHelper::legalizeInstrStep(), and scalarOrVector().
scalarOrVector() [2/2]
static LLT llvm::LLT::scalarOrVector (uint16_t NumElements, unsigned ScalarSize) inline static
Definition at line 77 of file LowLevelTypeImpl.h.
References scalar(), and scalarOrVector().
vector() [1/2]
static LLT llvm::LLT::vector (uint16_t NumElements, unsigned ScalarSizeInBits) inline static
Get a low-level vector of some number of elements and element width.
NumElements must be at least 2.
Definition at line 57 of file LowLevelTypeImpl.h.
References assert().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AArch64TargetLowering::allowsMisalignedMemoryAccesses(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingWideLoad(), changeElementSize(), changeElementType(), llvm::LegalizeRuleSet::clampMinNumElements(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::LegalizerHelper::fewerElementsVectorBuildVector(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorSelect(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::getLLTForMVT(), llvm::getLLTForType(), getMultipleType(), llvm::AArch64TargetLowering::getOptimalMemOpLLT(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::X86LegalizerInfo::legalizeIntrinsic(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::LegalizeMutations::moreElementsToNextPow2(), moreEltsToNext32Bit(), oneMoreElement(), packSplitRegsToOrigType(), scalarOrVector(), verifyAddrSpace(), and llvm::LegalizerHelper::widenScalar().
vector() [2/2]
static LLT llvm::LLT::vector (uint16_t NumElements, LLT ScalarTy) inline static
Get a low-level vector of some number of elements and element type.
Definition at line 65 of file LowLevelTypeImpl.h.
References assert(), getAddressSpace(), getSizeInBits(), isPointer(), and isVector().
Friends And Related Function Documentation
DenseMapInfo< LLT >
friend struct DenseMapInfo< LLT > friend
Definition at line 184 of file LowLevelTypeImpl.h.
GISelInstProfileBuilder
friend class GISelInstProfileBuilder friend
Definition at line 185 of file LowLevelTypeImpl.h.
The documentation for this class was generated from the following files:
include/llvm/Support/LowLevelTypeImpl.h
lib/Support/LowLevelType.cpp