LLVM: llvm::CombinerInfo Class Reference
llvm::CombinerInfo Class Reference abstract
#include "llvm/CodeGen/GlobalISel/CombinerInfo.h"
Public Member Functions
CombinerInfo (bool AllowIllegalOps, bool ShouldLegalizeIllegal, LegalizerInfo *LInfo, bool OptEnabled, bool OptSize, bool MinSize)
virtual ~CombinerInfo ()=default
virtual bool combine (GISelChangeObserver &Observer, MachineInstr &MI, MachineIRBuilder &B) const =0
Attempt to combine instructions using MI as the root.
Public Attributes
bool IllegalOpsAllowed
If IllegalOpsAllowed is false, the CombinerHelper will make use of the legalizerInfo to check for legality before each transformation.
bool LegalizeIllegalOps
If LegalizeIllegalOps is true, the Combiner will also legalize the illegal ops that are created.
const LegalizerInfo * LInfo
bool EnableOpt
Whether optimizations should be enabled.
bool EnableOptSize
Whether we're optimizing for size.
bool EnableMinSize
Whether we're optimizing for minsize (-Oz).
Detailed Description
Definition at line 27 of file CombinerInfo.h.
Constructor & Destructor Documentation
CombinerInfo()
llvm::CombinerInfo::CombinerInfo (bool AllowIllegalOps, bool ShouldLegalizeIllegal, LegalizerInfo * LInfo, bool OptEnabled, bool OptSize, bool MinSize) inline
Definition at line 29 of file CombinerInfo.h.
References assert(), LegalizeIllegalOps, and ~CombinerInfo().
~CombinerInfo()
virtual llvm::CombinerInfo::~CombinerInfo () virtual default
Referenced by CombinerInfo().
Member Function Documentation
combine()
virtual bool llvm::CombinerInfo::combine (GISelChangeObserver & Observer, MachineInstr & MI, MachineIRBuilder & B) const pure virtual
Attempt to combine instructions using MI as the root.
Use Observer to report the creation, modification, and erasure of instructions. GISelChangeObserver will automatically report certain kinds of operations. These operations are:
Instructions that are newly inserted into the MachineFunction
Instructions that are erased from the MachineFunction.
However, it is important to report instruction modification and this is not automatic.
Referenced by llvm::Combiner::combineMachineInstrs().
Member Data Documentation
EnableMinSize
bool llvm::CombinerInfo::EnableMinSize
Whether we're optimizing for minsize (-Oz).
Definition at line 55 of file CombinerInfo.h.
EnableOpt
bool llvm::CombinerInfo::EnableOpt
Whether optimizations should be enabled.
This is to distinguish between uses of the combiner unconditionally and only when optimizations are specifically enabled/
Definition at line 51 of file CombinerInfo.h.
EnableOptSize
bool llvm::CombinerInfo::EnableOptSize
Whether we're optimizing for size.
Definition at line 53 of file CombinerInfo.h.
IllegalOpsAllowed
bool llvm::CombinerInfo::IllegalOpsAllowed
If IllegalOpsAllowed is false, the CombinerHelper will make use of the legalizerInfo to check for legality before each transformation.
Definition at line 41 of file CombinerInfo.h.
LegalizeIllegalOps
bool llvm::CombinerInfo::LegalizeIllegalOps
If LegalizeIllegalOps is true, the Combiner will also legalize the illegal ops that are created.
Definition at line 45 of file CombinerInfo.h.
Referenced by CombinerInfo().
LInfo
const LegalizerInfo* llvm::CombinerInfo::LInfo
Definition at line 46 of file CombinerInfo.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/CombinerInfo.h