LLVM: llvm::LineEditor Class Reference
llvm::LineEditor Class Reference
#include "llvm/LineEditor/LineEditor.h"
Classes
struct Completion
A possible completion at a given cursor position.
struct CompletionAction
The action to perform upon a completion request.
struct InternalData
Public Member Functions
LineEditor (StringRef ProgName, StringRef HistoryPath="", FILE *In=stdin, FILE *Out=stdout, FILE *Err=stderr)
Create a LineEditor object.
~LineEditor ()
llvm::Optional< std::string > readLine () const
Reads a line.
void saveHistory ()
void loadHistory ()
template<typename T >
void setCompleter (T Comp)
Set the completer for this LineEditor.
template<typename T >
void setListCompleter (T Comp)
Set the completer for this LineEditor to the given list completer.
CompletionAction getCompletionAction (StringRef Buffer, size_t Pos) const
Use the current completer to produce a CompletionAction for the given completion request.
const std::string & getPrompt () const
void setPrompt (const std::string &P)
Static Public Member Functions
static std::string getDefaultHistoryPath (StringRef ProgName)
Detailed Description
Definition at line 22 of file LineEditor.h.
Constructor & Destructor Documentation
LineEditor()
LineEditor::LineEditor (StringRef ProgName, StringRef HistoryPath = "", FILE * In = stdin, FILE * Out = stdout, FILE * Err = stderr)
Create a LineEditor object.
Parameters
ProgName The name of the current program. Used to form a default prompt.
HistoryPath Path to the file in which to store history data, if possible.
In The input stream used by the editor.
Out The output stream used by the editor.
Err The error stream used by the editor.
Definition at line 198 of file LineEditor.cpp.
Referenced by readLine().
~LineEditor()
LineEditor::~LineEditor ()
Definition at line 234 of file LineEditor.cpp.
References saveHistory().
Member Function Documentation
getCompletionAction()
LineEditor::CompletionAction LineEditor::getCompletionAction (StringRef Buffer, size_t Pos) const
Use the current completer to produce a CompletionAction for the given completion request.
If the current completer is a list completer, this will return an AK_Insert CompletionAction if each completion has a common prefix, or an AK_ShowCompletions CompletionAction otherwise.
Parameters
Buffer The string to complete
Pos The zero-based cursor position in the StringRef
Definition at line 83 of file LineEditor.cpp.
References llvm::LineEditor::CompletionAction::AK_ShowCompletions, and llvm::LineEditor::CompletionAction::Kind.
Referenced by setListCompleter().
getDefaultHistoryPath()
std::string LineEditor::getDefaultHistoryPath (StringRef ProgName) static
Definition at line 23 of file LineEditor.cpp.
References llvm::LineEditor::CompletionAction::AK_Insert, llvm::LineEditor::CompletionAction::AK_ShowCompletions, llvm::sys::path::append(), assert(), llvm::LineEditor::CompletionAction::Completions, E, llvm::sys::path::home_directory(), I, llvm::LineEditor::CompletionAction::Kind, llvm::SmallString< InternalLen >::str(), and llvm::LineEditor::CompletionAction::Text.
getPrompt()
const std::string& llvm::LineEditor::getPrompt () const inline
Definition at line 105 of file LineEditor.h.
loadHistory()
void LineEditor::loadHistory ()
Definition at line 249 of file LineEditor.cpp.
readLine()
Optional< std::string > LineEditor::readLine () const
Reads a line.
Returns
The line, or llvm::Optional<std::string>() on EOF.
Definition at line 256 of file LineEditor.cpp.
References llvm::tgtok::In, and LineEditor().
saveHistory()
void LineEditor::saveHistory ()
Definition at line 242 of file LineEditor.cpp.
Referenced by ~LineEditor().
setCompleter()
template<typename T > void llvm::LineEditor::setCompleter (T Comp) inline
Set the completer for this LineEditor.
A completer is a function object which takes arguments of type StringRef (the string to complete) and size_t (the zero-based cursor position in the StringRef) and returns a CompletionAction.
Definition at line 84 of file LineEditor.h.
setListCompleter()
template<typename T > void llvm::LineEditor::setListCompleter (T Comp) inline
Set the completer for this LineEditor to the given list completer.
A list completer is a function object which takes arguments of type StringRef (the string to complete) and size_t (the zero-based cursor position in the StringRef) and returns a std::vector<Completion>.
Definition at line 92 of file LineEditor.h.
References getCompletionAction().
setPrompt()
void llvm::LineEditor::setPrompt (const std::string & P) inline
Definition at line 106 of file LineEditor.h.
References llvm::Data, and P.
The documentation for this class was generated from the following files:
include/llvm/LineEditor/LineEditor.h
lib/LineEditor/LineEditor.cpp