LLVM: llvm::jitlink::MachOJITLinker_arm64 Class Reference
llvm::jitlink::MachOJITLinker_arm64 Class Reference
Public Member Functions
MachOJITLinker_arm64 (std::unique_ptr< JITLinkContext > Ctx, PassConfiguration PassConfig)
Public Member Functions inherited from llvm::jitlink::JITLinkerBase
JITLinkerBase (std::unique_ptr< JITLinkContext > Ctx, PassConfiguration Passes)
virtual ~JITLinkerBase ()
Friends
class JITLinker< MachOJITLinker_arm64 >
Additional Inherited Members
Static Public Member Functions inherited from llvm::jitlink::JITLinker< MachOJITLinker_arm64 >
static void link (ArgTs &&... Args)
Link constructs a LinkerImpl instance and calls linkPhase1.
Protected Types inherited from llvm::jitlink::JITLinkerBase
using SegmentLayoutMap = DenseMap< unsigned, SegmentLayout >
Protected Member Functions inherited from llvm::jitlink::JITLinkerBase
void linkPhase1 (std::unique_ptr< JITLinkerBase > Self)
void linkPhase2 (std::unique_ptr< JITLinkerBase > Self, Expected< AsyncLookupResult > LookupResult, SegmentLayoutMap Layout)
void linkPhase3 (std::unique_ptr< JITLinkerBase > Self, Error Err)
Static Protected Member Functions inherited from llvm::jitlink::JITLinkerBase
static JITTargetAddress alignToBlock (JITTargetAddress Addr, Block &B)
static char * alignToBlock (char *P, Block &B)
Detailed Description
Definition at line 475 of file MachO_arm64.cpp.
Constructor & Destructor Documentation
MachOJITLinker_arm64()
llvm::jitlink::MachOJITLinker_arm64::MachOJITLinker_arm64 (std::unique_ptr< JITLinkContext > Ctx, PassConfiguration PassConfig) inline
Definition at line 479 of file MachO_arm64.cpp.
References assert(), B, llvm::jitlink::MachO_arm64_Edges::Branch26, llvm::object::ObjectFile::createMachOObjectFile(), llvm::jitlink::MachO_arm64_Edges::Delta32, llvm::jitlink::MachO_arm64_Edges::Delta64, E, llvm::jitlink::Edge::getAddend(), llvm::jitlink::Addressable::getAddress(), llvm::jitlink::Symbol::getAddress(), llvm::jitlink::Edge::getKind(), llvm::jitlink::getMachOARM64RelocationKindName(), llvm::jitlink::Edge::getOffset(), llvm::jitlink::Edge::getTarget(), llvm::jitlink::MachO_arm64_Edges::GOTPage21, llvm::jitlink::MachO_arm64_Edges::GOTPageOffset12, llvm::X86II::ImmShift, llvm::jitlink::MachO_arm64_Edges::LDRLiteral19, llvm_unreachable, llvm::max(), llvm::jitlink::MachO_arm64_Edges::NegDelta32, llvm::jitlink::MachO_arm64_Edges::NegDelta64, llvm::jitlink::MachO_arm64_Edges::Page21, llvm::jitlink::MachO_arm64_Edges::PageOffset12, llvm::jitlink::MachO_arm64_Edges::Pointer32, llvm::jitlink::MachO_arm64_Edges::Pointer64, llvm::jitlink::printEdge(), llvm::RISCVFenceField::R, and llvm::Error::success().
Friends And Related Function Documentation
JITLinker< MachOJITLinker_arm64 >
friend class JITLinker< MachOJITLinker_arm64 > friend
Definition at line 476 of file MachO_arm64.cpp.
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/MachO_arm64.cpp