LLVM: llvm::EscapeEnumerator Class Reference
llvm::EscapeEnumerator Class Reference
EscapeEnumerator - This is a little algorithm to find all escape points from a function so that "finally"-style code can be inserted.
#include "llvm/Transforms/Utils/EscapeEnumerator.h"
Public Member Functions
EscapeEnumerator (Function &F, const char *N="cleanup", bool HandleExceptions=true)
IRBuilder * Next ()
Detailed Description
EscapeEnumerator - This is a little algorithm to find all escape points from a function so that "finally"-style code can be inserted.
In addition to finding the existing return and unwind instructions, it also (if necessary) transforms any call instructions into invokes and sends them to a landing pad.
Definition at line 27 of file EscapeEnumerator.h.
Constructor & Destructor Documentation
EscapeEnumerator()
llvm::EscapeEnumerator::EscapeEnumerator (Function & F, const char * N = "cleanup", bool HandleExceptions = true) inline
Definition at line 37 of file EscapeEnumerator.h.
References Next().
Member Function Documentation
Next()
IRBuilder * EscapeEnumerator::Next ()
Definition at line 29 of file EscapeEnumerator.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, C, llvm::changeToInvokeAndSplitBasicBlock(), llvm::classifyEHPersonality(), llvm::BasicBlock::Create(), llvm::LandingPadInst::Create(), llvm::ResumeInst::Create(), llvm::Function::doesNotThrow(), llvm::SmallVectorBase::empty(), llvm::StructType::get(), llvm::FunctionCallee::getCallee(), llvm::Value::getContext(), getDefaultPersonalityFn(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::BasicBlock::getTerminator(), I, llvm::isScopedEHPersonality(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), llvm::LandingPadInst::setCleanup(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::SmallVectorBase::size().
Referenced by llvm::createShadowStackGCLoweringPass(), EscapeEnumerator(), and isAtomic().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/EscapeEnumerator.h
lib/Transforms/Utils/EscapeEnumerator.cpp