LLVM: llvm::RuntimeDyldCheckerExprEval Class Reference
llvm::RuntimeDyldCheckerExprEval Class Reference
Public Member Functions
RuntimeDyldCheckerExprEval (const RuntimeDyldCheckerImpl &Checker, raw_ostream &ErrStream)
bool evaluate (StringRef Expr) const
Detailed Description
Definition at line 29 of file RuntimeDyldChecker.cpp.
Constructor & Destructor Documentation
RuntimeDyldCheckerExprEval()
llvm::RuntimeDyldCheckerExprEval::RuntimeDyldCheckerExprEval (const RuntimeDyldCheckerImpl & Checker, raw_ostream & ErrStream) inline
Definition at line 31 of file RuntimeDyldChecker.cpp.
Member Function Documentation
evaluate()
bool llvm::RuntimeDyldCheckerExprEval::evaluate (StringRef Expr) const inline
Definition at line 35 of file RuntimeDyldChecker.cpp.
References assert(), llvm::StringRef::bytes_begin(), llvm::MCInst::dump_pretty(), llvm::StringRef::empty(), llvm::StringRef::find(), llvm::StringRef::find_first_not_of(), llvm::format(), llvm::StringRef::getAsInteger(), llvm::MCOperand::getImm(), llvm::MCDisassembler::getInstruction(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm_unreachable, llvm::StringRef::ltrim(), llvm::BitmaskEnumDetail::Mask(), llvm::StringRef::npos, llvm::nulls(), llvm::StringRef::rtrim(), AMDGPU::ElfNote::SectionName, Size, llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::raw_string_ostream::str(), llvm::StringRef::substr(), llvm::MCDisassembler::Success, llvm::ARMBuildAttrs::Symbol, and llvm::StringRef::trim().
Referenced by llvm::RuntimeDyldCheckerImpl::check().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldChecker.cpp