LLVM: llvm::pdb::DbiStreamBuilder Class Reference
llvm::pdb::DbiStreamBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/DbiStreamBuilder.h"
Public Member Functions
DbiStreamBuilder (msf::MSFBuilder &Msf)
~DbiStreamBuilder ()
DbiStreamBuilder (const DbiStreamBuilder &)=delete
DbiStreamBuilder & operator= (const DbiStreamBuilder &)=delete
void setVersionHeader (PdbRaw_DbiVer V)
void setAge (uint32_t A)
void setBuildNumber (uint16_t B)
void setBuildNumber (uint8_t Major, uint8_t Minor)
void setPdbDllVersion (uint16_t V)
void setPdbDllRbld (uint16_t R)
void setFlags (uint16_t F)
void setMachineType (PDB_Machine M)
void setMachineType (COFF::MachineTypes M)
void setSectionMap (ArrayRef< SecMapEntry > SecMap)
Error addDbgStream (pdb::DbgHeaderType Type, ArrayRef< uint8_t > Data)
uint32_t addECName (StringRef Name)
uint32_t calculateSerializedLength () const
void setGlobalsStreamIndex (uint32_t Index)
void setPublicsStreamIndex (uint32_t Index)
void setSymbolRecordStreamIndex (uint32_t Index)
void addNewFpoData (const codeview::FrameData &FD)
void addOldFpoData (const object::FpoData &Fpo)
Expected< DbiModuleDescriptorBuilder & > addModuleInfo (StringRef ModuleName)
Error addModuleSourceFile (DbiModuleDescriptorBuilder &Module, StringRef File)
Expected< uint32_t > getSourceFileNameIndex (StringRef FileName)
Error finalizeMsfLayout ()
Error commit (const msf::MSFLayout &Layout, WritableBinaryStreamRef MsfBuffer)
void addSectionContrib (const SectionContrib &SC)
Static Public Member Functions
static std::vector< SecMapEntry > createSectionMap (ArrayRef< llvm::object::coff_section > SecHdrs)
Detailed Description
Definition at line 43 of file DbiStreamBuilder.h.
Constructor & Destructor Documentation
DbiStreamBuilder() [1/2]
DbiStreamBuilder::DbiStreamBuilder (msf::MSFBuilder & Msf)
Definition at line 27 of file DbiStreamBuilder.cpp.
References llvm::pdb::x86.
~DbiStreamBuilder()
DbiStreamBuilder::~DbiStreamBuilder ()
Definition at line 32 of file DbiStreamBuilder.cpp.
DbiStreamBuilder() [2/2]
llvm::pdb::DbiStreamBuilder::DbiStreamBuilder (const DbiStreamBuilder &) delete
Member Function Documentation
addDbgStream()
Error DbiStreamBuilder::addDbgStream (pdb::DbgHeaderType Type, ArrayRef< uint8_t > Data)
Definition at line 88 of file DbiStreamBuilder.cpp.
References assert(), llvm::pdb::NewFPO, Size, llvm::ArrayRef< T >::size(), llvm::Error::success(), and llvm::BinaryStreamWriter::writeArray().
addECName()
uint32_t DbiStreamBuilder::addECName (StringRef Name)
Definition at line 101 of file DbiStreamBuilder.cpp.
References llvm::pdb::PDBStringTableBuilder::insert().
addModuleInfo()
Expected< DbiModuleDescriptorBuilder & > DbiStreamBuilder::addModuleInfo (StringRef ModuleName)
Definition at line 114 of file DbiStreamBuilder.cpp.
addModuleSourceFile()
Error DbiStreamBuilder::addModuleSourceFile (DbiModuleDescriptorBuilder & Module, StringRef File)
Definition at line 121 of file DbiStreamBuilder.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::insert(), llvm::StringMapImpl::size(), and llvm::Error::success().
addNewFpoData()
void DbiStreamBuilder::addNewFpoData (const codeview::FrameData & FD)
Definition at line 77 of file DbiStreamBuilder.cpp.
addOldFpoData()
void DbiStreamBuilder::addOldFpoData (const object::FpoData & Fpo)
Definition at line 84 of file DbiStreamBuilder.cpp.
addSectionContrib()
void llvm::pdb::DbiStreamBuilder::addSectionContrib (const SectionContrib & SC) inline
Definition at line 83 of file DbiStreamBuilder.h.
References Allocator, finalize, llvm::pdb::kInvalidStreamIndex, llvm::pdb::SectionContribs, and Size.
calculateSerializedLength()
uint32_t DbiStreamBuilder::calculateSerializedLength () const
Definition at line 105 of file DbiStreamBuilder.cpp.
References llvm::pdb::PDBStringTableBuilder::calculateSerializedSize().
Referenced by finalizeMsfLayout().
commit()
Error DbiStreamBuilder::commit (const msf::MSFLayout & Layout, WritableBinaryStreamRef MsfBuffer)
Definition at line 391 of file DbiStreamBuilder.cpp.
References assert(), llvm::BinaryStreamWriter::bytesRemaining(), llvm::pdb::PDBStringTableBuilder::commit(), llvm::pdb::DbiSecContribVer60, llvm::codeview::EC, if(), llvm::pdb::invalid_format, llvm::pdb::kInvalidStreamIndex, llvm::makeArrayRef(), Size, llvm::pdb::StreamDBI, llvm::Error::success(), llvm::BinaryStreamWriter::writeArray(), llvm::BinaryStreamWriter::writeEnum(), llvm::BinaryStreamWriter::writeInteger(), llvm::BinaryStreamWriter::writeObject(), and llvm::BinaryStreamWriter::writeStreamRef().
createSectionMap()
std::vector< SecMapEntry > DbiStreamBuilder::createSectionMap (ArrayRef< llvm::object::coff_section > SecHdrs) static
Definition at line 356 of file DbiStreamBuilder.cpp.
References llvm::MCID::Add, and llvm::MipsISD::Ret.
finalizeMsfLayout()
Error DbiStreamBuilder::finalizeMsfLayout ()
Definition at line 291 of file DbiStreamBuilder.cpp.
References llvm::msf::MSFBuilder::addStream(), calculateSerializedLength(), llvm::codeview::EC, llvm::pdb::FPO, llvm::makeArrayRef(), MI, llvm::pdb::NewFPO, llvm::msf::MSFBuilder::setStreamSize(), Size, llvm::pdb::StreamDBI, llvm::Error::success(), and llvm::BinaryStreamWriter::writeArray().
getSourceFileNameIndex()
Expected< uint32_t > DbiStreamBuilder::getSourceFileNameIndex (StringRef FileName)
Definition at line 129 of file DbiStreamBuilder.cpp.
References llvm::pdb::DbiStreamHeader::Age, llvm::alignTo(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::pdb::DbiStreamHeader::BuildNumber, llvm::BinaryStreamWriter::bytesRemaining(), llvm::pdb::PDBStringTableBuilder::calculateSerializedSize(), llvm::pdb::Data, llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), llvm::codeview::EC, llvm::pdb::DbiStreamHeader::ECSubstreamSize, llvm::StringMap< ValueTy, AllocatorTy >::end(), F(), llvm::pdb::DbiStreamHeader::FileInfoSize, llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::pdb::DbiStreamHeader::Flags, llvm::MutableBinaryByteStream::getLength(), llvm::BinaryStreamWriter::getOffset(), llvm::pdb::DbiStreamHeader::GlobalSymbolStreamIndex, H, I, llvm::pdb::invalid_format, llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front(), llvm::support::little, llvm::pdb::DbiStreamHeader::MachineType, llvm::pdb::DbiStreamHeader::MFCTypeServerIndex, MI, llvm::pdb::DbiStreamHeader::ModiSubstreamSize, Name, llvm::pdb::no_entry, llvm::pdb::DbiStreamHeader::OptionalDbgHdrSize, llvm::BinaryStreamWriter::padToAlignment(), llvm::pdb::DbiStreamHeader::PdbDllRbld, llvm::pdb::DbiStreamHeader::PdbDllVersion, llvm::pdb::DbiStreamHeader::PublicSymbolStreamIndex, llvm::pdb::DbiStreamHeader::SecContrSubstreamSize, llvm::pdb::DbiStreamHeader::SectionMapSize, Size, llvm::StringMapImpl::size(), llvm::Error::success(), llvm::pdb::DbiStreamHeader::SymRecordStreamIndex, llvm::pdb::DbiStreamHeader::TypeServerSize, llvm::pdb::DbiStreamHeader::VersionHeader, llvm::pdb::DbiStreamHeader::VersionSignature, llvm::BinaryStreamWriter::writeCString(), and llvm::BinaryStreamWriter::writeInteger().
operator=()
DbiStreamBuilder& llvm::pdb::DbiStreamBuilder::operator= (const DbiStreamBuilder &) delete
setAge()
void DbiStreamBuilder::setAge (uint32_t A)
Definition at line 36 of file DbiStreamBuilder.cpp.
setBuildNumber() [1/2]
void DbiStreamBuilder::setBuildNumber (uint16_t B)
Definition at line 38 of file DbiStreamBuilder.cpp.
References B.
setBuildNumber() [2/2]
void DbiStreamBuilder::setBuildNumber (uint8_t Major, uint8_t Minor)
Definition at line 40 of file DbiStreamBuilder.cpp.
References llvm::pdb::DbiBuildNo::BuildMajorMask, llvm::pdb::DbiBuildNo::BuildMajorShift, llvm::pdb::DbiBuildNo::BuildMinorMask, llvm::pdb::DbiBuildNo::BuildMinorShift, and llvm::pdb::DbiBuildNo::NewVersionFormatMask.
setFlags()
void DbiStreamBuilder::setFlags (uint16_t F)
Definition at line 52 of file DbiStreamBuilder.cpp.
References F().
setGlobalsStreamIndex()
void DbiStreamBuilder::setGlobalsStreamIndex (uint32_t Index)
Definition at line 65 of file DbiStreamBuilder.cpp.
setMachineType() [1/2]
void DbiStreamBuilder::setMachineType (PDB_Machine M)
Definition at line 54 of file DbiStreamBuilder.cpp.
setMachineType() [2/2]
void DbiStreamBuilder::setMachineType (COFF::MachineTypes M)
Definition at line 56 of file DbiStreamBuilder.cpp.
setPdbDllRbld()
void DbiStreamBuilder::setPdbDllRbld (uint16_t R)
Definition at line 50 of file DbiStreamBuilder.cpp.
setPdbDllVersion()
void DbiStreamBuilder::setPdbDllVersion (uint16_t V)
Definition at line 48 of file DbiStreamBuilder.cpp.
setPublicsStreamIndex()
void DbiStreamBuilder::setPublicsStreamIndex (uint32_t Index)
Definition at line 73 of file DbiStreamBuilder.cpp.
setSectionMap()
void DbiStreamBuilder::setSectionMap (ArrayRef< SecMapEntry > SecMap)
Definition at line 61 of file DbiStreamBuilder.cpp.
setSymbolRecordStreamIndex()
void DbiStreamBuilder::setSymbolRecordStreamIndex (uint32_t Index)
Definition at line 69 of file DbiStreamBuilder.cpp.
setVersionHeader()
void DbiStreamBuilder::setVersionHeader (PdbRaw_DbiVer V)
Definition at line 34 of file DbiStreamBuilder.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/DbiStreamBuilder.h
lib/DebugInfo/PDB/Native/DbiStreamBuilder.cpp