LLVM: llvm::MachO::PackedVersion Class Reference
llvm::MachO::PackedVersion Class Reference
#include "llvm/TextAPI/MachO/PackedVersion.h"
Public Member Functions
constexpr PackedVersion ()=default
constexpr PackedVersion (uint32_t RawVersion)
PackedVersion (unsigned Major, unsigned Minor, unsigned Subminor)
bool empty () const
unsigned getMajor () const
Retrieve the major version number.
unsigned getMinor () const
Retrieve the minor version number, if provided.
unsigned getSubminor () const
Retrieve the subminor version number, if provided.
bool parse32 (StringRef Str)
std::pair< bool, bool > parse64 (StringRef Str)
bool operator< (const PackedVersion &O) const
bool operator== (const PackedVersion &O) const
bool operator!= (const PackedVersion &O) const
uint32_t rawValue () const
void print (raw_ostream &OS) const
Detailed Description
Definition at line 22 of file PackedVersion.h.
Constructor & Destructor Documentation
PackedVersion() [1/3]
constexpr llvm::MachO::PackedVersion::PackedVersion () default
PackedVersion() [2/3]
constexpr llvm::MachO::PackedVersion::PackedVersion (uint32_t RawVersion) inline explicit
Definition at line 27 of file PackedVersion.h.
PackedVersion() [3/3]
llvm::MachO::PackedVersion::PackedVersion (unsigned Major, unsigned Minor, unsigned Subminor) inline
Definition at line 28 of file PackedVersion.h.
Member Function Documentation
empty()
bool llvm::MachO::PackedVersion::empty () const inline
Definition at line 31 of file PackedVersion.h.
getMajor()
unsigned llvm::MachO::PackedVersion::getMajor () const inline
Retrieve the major version number.
Definition at line 34 of file PackedVersion.h.
Referenced by print().
getMinor()
unsigned llvm::MachO::PackedVersion::getMinor () const inline
Retrieve the minor version number, if provided.
Definition at line 37 of file PackedVersion.h.
Referenced by print().
getSubminor()
unsigned llvm::MachO::PackedVersion::getSubminor () const inline
Retrieve the subminor version number, if provided.
Definition at line 40 of file PackedVersion.h.
References parse32(), and parse64().
Referenced by print().
operator!=()
bool llvm::MachO::PackedVersion::operator!= (const PackedVersion & O) const inline
Definition at line 49 of file PackedVersion.h.
operator<()
bool llvm::MachO::PackedVersion::operator< (const PackedVersion & O) const inline
Definition at line 45 of file PackedVersion.h.
operator==()
bool llvm::MachO::PackedVersion::operator== (const PackedVersion & O) const inline
Definition at line 47 of file PackedVersion.h.
parse32()
bool llvm::MachO::PackedVersion::parse32 (StringRef Str)
Definition at line 23 of file PackedVersion.cpp.
References llvm::StringRef::empty(), llvm::getAsUnsignedInteger(), llvm::SmallVectorBase::size(), and llvm::SplitString().
Referenced by getSubminor(), and llvm::yaml::ScalarTraits< FlowStringRef >::mustQuote().
parse64()
std::pair< bool, bool > llvm::MachO::PackedVersion::parse64 (StringRef Str)
Definition at line 57 of file PackedVersion.cpp.
References llvm::StringRef::empty(), llvm::getAsUnsignedInteger(), llvm::SmallVectorBase::size(), and llvm::SplitString().
Referenced by getSubminor().
print()
void llvm::MachO::PackedVersion::print (raw_ostream & OS) const
Definition at line 104 of file PackedVersion.cpp.
References llvm::format(), getMajor(), getMinor(), and getSubminor().
Referenced by llvm::MachO::operator<<(), and rawValue().
rawValue()
uint32_t llvm::MachO::PackedVersion::rawValue () const inline
Definition at line 51 of file PackedVersion.h.
References print().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/MachO/PackedVersion.h
lib/TextAPI/MachO/PackedVersion.cpp