LLVM: llvm::codeview::DebugFrameDataSubsection Class Reference
llvm::codeview::DebugFrameDataSubsection Class Reference final
#include "llvm/DebugInfo/CodeView/DebugFrameDataSubsection.h"
Public Member Functions
DebugFrameDataSubsection (bool IncludeRelocPtr)
uint32_t calculateSerializedSize () const override
Error commit (BinaryStreamWriter &Writer) const override
void addFrameData (const FrameData &Frame)
void setFrames (ArrayRef< FrameData > Frames)
Public Member Functions inherited from llvm::codeview::DebugSubsection
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsection
static bool classof (const DebugSubsection *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsection
DebugSubsectionKind Kind
Detailed Description
Definition at line 41 of file DebugFrameDataSubsection.h.
Constructor & Destructor Documentation
DebugFrameDataSubsection()
llvm::codeview::DebugFrameDataSubsection::DebugFrameDataSubsection (bool IncludeRelocPtr) inline
Definition at line 43 of file DebugFrameDataSubsection.h.
Member Function Documentation
addFrameData()
void DebugFrameDataSubsection::addFrameData (const FrameData & Frame)
Definition at line 59 of file DebugFrameDataSubsection.cpp.
calculateSerializedSize()
uint32_t DebugFrameDataSubsection::calculateSerializedSize () const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 36 of file DebugFrameDataSubsection.cpp.
References llvm::codeview::FrameData, and Size.
classof()
static bool llvm::codeview::DebugFrameDataSubsection::classof (const DebugSubsection * S) inline static
Definition at line 46 of file DebugFrameDataSubsection.h.
References llvm::codeview::FrameData, and llvm::codeview::DebugSubsection::kind().
commit()
Error DebugFrameDataSubsection::commit (BinaryStreamWriter & Writer) const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 43 of file DebugFrameDataSubsection.cpp.
References llvm::codeview::EC, llvm::makeArrayRef(), llvm::codeview::FrameData::RvaStart, llvm::sort(), llvm::Error::success(), llvm::BinaryStreamWriter::writeArray(), and llvm::BinaryStreamWriter::writeInteger().
setFrames()
void llvm::codeview::DebugFrameDataSubsection::setFrames (ArrayRef< FrameData > Frames)
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugFrameDataSubsection.h
lib/DebugInfo/CodeView/DebugFrameDataSubsection.cpp