LLVM: llvm::codeview::AppendingTypeTableBuilder Class Reference
llvm::codeview::AppendingTypeTableBuilder Class Reference
#include "llvm/DebugInfo/CodeView/AppendingTypeTableBuilder.h"
Public Member Functions
AppendingTypeTableBuilder (BumpPtrAllocator &Storage)
~AppendingTypeTableBuilder ()
Optional< TypeIndex > getFirst () override
Optional< TypeIndex > getNext (TypeIndex Prev) override
CVType getType (TypeIndex Index) override
StringRef getTypeName (TypeIndex Index) override
bool contains (TypeIndex Index) override
uint32_t size () override
uint32_t capacity () override
void reset ()
TypeIndex nextTypeIndex () const
BumpPtrAllocator & getAllocator ()
ArrayRef< ArrayRef< uint8_t > > records () const
TypeIndex insertRecordBytes (ArrayRef< uint8_t > &Record)
TypeIndex insertRecord (ContinuationRecordBuilder &Builder)
template<typename T >
TypeIndex writeLeafType (T &Record)
Public Member Functions inherited from llvm::codeview::TypeCollection
virtual ~TypeCollection ()=default
bool empty ()
template<typename TFunc >
void ForEachRecord (TFunc Func)
Detailed Description
Definition at line 29 of file AppendingTypeTableBuilder.h.
Constructor & Destructor Documentation
AppendingTypeTableBuilder()
AppendingTypeTableBuilder::AppendingTypeTableBuilder (BumpPtrAllocator & Storage) explicit
Definition at line 34 of file AppendingTypeTableBuilder.cpp.
References ~AppendingTypeTableBuilder().
~AppendingTypeTableBuilder()
AppendingTypeTableBuilder::~AppendingTypeTableBuilder () default
Referenced by AppendingTypeTableBuilder().
Member Function Documentation
capacity()
uint32_t AppendingTypeTableBuilder::capacity () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 69 of file AppendingTypeTableBuilder.cpp.
contains()
bool AppendingTypeTableBuilder::contains (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 60 of file AppendingTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::isNoneType(), llvm::codeview::TypeIndex::isSimple(), and llvm::codeview::TypeIndex::toArrayIndex().
getAllocator()
BumpPtrAllocator& llvm::codeview::AppendingTypeTableBuilder::getAllocator () inline
Definition at line 54 of file AppendingTypeTableBuilder.h.
References insertRecord(), insertRecordBytes(), and records().
getFirst()
Optional< TypeIndex > AppendingTypeTableBuilder::getFirst () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 39 of file AppendingTypeTableBuilder.cpp.
References llvm::codeview::TypeCollection::empty(), llvm::codeview::TypeIndex::FirstNonSimpleIndex, and llvm::codeview::None.
getNext()
Optional< TypeIndex > AppendingTypeTableBuilder::getNext (TypeIndex Prev) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 46 of file AppendingTypeTableBuilder.cpp.
References nextTypeIndex(), and llvm::codeview::None.
getType()
CVType AppendingTypeTableBuilder::getType (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 52 of file AppendingTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::toArrayIndex().
getTypeName()
StringRef AppendingTypeTableBuilder::getTypeName (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 56 of file AppendingTypeTableBuilder.cpp.
References llvm_unreachable.
insertRecord()
TypeIndex AppendingTypeTableBuilder::insertRecord (ContinuationRecordBuilder & Builder)
Definition at line 88 of file AppendingTypeTableBuilder.cpp.
References assert(), llvm::codeview::C, llvm::codeview::ContinuationRecordBuilder::end(), insertRecordBytes(), and nextTypeIndex().
Referenced by getAllocator().
insertRecordBytes()
TypeIndex AppendingTypeTableBuilder::insertRecordBytes (ArrayRef< uint8_t > & Record)
Definition at line 78 of file AppendingTypeTableBuilder.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::ArrayRef< T >::data(), nextTypeIndex(), and llvm::ArrayRef< T >::size().
Referenced by getAllocator(), insertRecord(), and writeLeafType().
nextTypeIndex()
TypeIndex AppendingTypeTableBuilder::nextTypeIndex () const
Definition at line 30 of file AppendingTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::fromArrayIndex().
Referenced by getNext(), insertRecord(), and insertRecordBytes().
records()
ArrayRef< ArrayRef< uint8_t > > AppendingTypeTableBuilder::records () const
Definition at line 71 of file AppendingTypeTableBuilder.cpp.
Referenced by getAllocator(), and llvm::CodeViewYAML::detail::LeafRecordImpl< T >::toCodeViewRecord().
reset()
void AppendingTypeTableBuilder::reset ()
Definition at line 75 of file AppendingTypeTableBuilder.cpp.
size()
uint32_t AppendingTypeTableBuilder::size () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 67 of file AppendingTypeTableBuilder.cpp.
writeLeafType()
template<typename T > TypeIndex llvm::codeview::AppendingTypeTableBuilder::writeLeafType (T & Record) inline
Definition at line 60 of file AppendingTypeTableBuilder.h.
References llvm::Data, insertRecordBytes(), and llvm::codeview::SimpleTypeSerializer::serialize().
Referenced by llvm::CodeViewYAML::detail::LeafRecordImpl< T >::toCodeViewRecord().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/AppendingTypeTableBuilder.h
lib/DebugInfo/CodeView/AppendingTypeTableBuilder.cpp