LLVM: llvm::X86RegisterBankInfo Class Reference
llvm::X86RegisterBankInfo Class Reference final
This class provides the information for the target register banks.
#include "Target/X86/X86RegisterBankInfo.h"
Public Member Functions
X86RegisterBankInfo (const TargetRegisterInfo &TRI)
const RegisterBank & getRegBankFromRegClass (const TargetRegisterClass &RC, LLT) const override
Get a register bank that covers RC.
InstructionMappings getInstrAlternativeMappings (const MachineInstr &MI) const override
Get the alternative mappings for MI.
void applyMappingImpl (const OperandsMapper &OpdMapper) const override
See RegisterBankInfo::applyMapping.
const InstructionMapping & getInstrMapping (const MachineInstr &MI) const override
Get the mapping of the different operands of MI on the register bank.
Public Member Functions inherited from llvm::RegisterBankInfo
const RegisterBank * getRegBankFromConstraints (const MachineInstr &MI, unsigned OpIdx, const TargetInstrInfo &TII, const MachineRegisterInfo &MRI) const
Get the register bank for the OpIdx-th operand of MI form the encoding constraints, if any.
virtual ~RegisterBankInfo ()=default
const RegisterBank & getRegBank (unsigned ID) const
Get the register bank identified by ID.
const RegisterBank * getRegBank (Register Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI) const
Get the register bank of Reg.
unsigned getNumRegBanks () const
Get the total number of register banks.
virtual unsigned copyCost (const RegisterBank &A, const RegisterBank &B, unsigned Size) const
Get the cost of a copy from B to A, or put differently, get the cost of A = COPY B.
bool cannotCopy (const RegisterBank &Dst, const RegisterBank &Src, unsigned Size) const
virtual unsigned getBreakDownCost (const ValueMapping &ValMapping, const RegisterBank *CurBank=nullptr) const
Get the cost of using ValMapping to decompose a register.
const InstructionMapping & getInstructionMapping (unsigned ID, unsigned Cost, const ValueMapping *OperandsMapping, unsigned NumOperands) const
Method to get a uniquely generated InstructionMapping.
const InstructionMapping & getInvalidInstructionMapping () const
Method to get a uniquely generated invalid InstructionMapping.
Additional Inherited Members
Public Types inherited from llvm::RegisterBankInfo
using InstructionMappings = SmallVector< const InstructionMapping *, 4 >
Convenient type to represent the alternatives for mapping an instruction.
Static Public Member Functions inherited from llvm::RegisterBankInfo
static void applyDefaultMapping (const OperandsMapper &OpdMapper)
Helper method to apply something that is like the default mapping.
static const TargetRegisterClass * constrainGenericRegister (Register Reg, const TargetRegisterClass &RC, MachineRegisterInfo &MRI)
Constrain the (possibly generic) virtual register Reg to RC.
Public Attributes inherited from llvm::RegisterBankInfo
struct llvm::RegisterBankInfo::PartialMapping ScalarAddx2
VectorAdd
Get the possible mapping for MI.
Static Public Attributes inherited from llvm::RegisterBankInfo
static const unsigned DefaultMappingID = UINT_MAX
Identifier used when the related instruction mapping instance is generated by target independent code.
static const unsigned InvalidMappingID = UINT_MAX - 1
Identifier used when the related instruction mapping instance is generated by the default constructor.
Protected Types inherited from llvm::X86GenRegisterBankInfo
enum PartialMappingIdx {
PMI_None = -1, PMI_GPR8, PMI_GPR16, PMI_GPR32,
PMI_GPR64, PMI_FP32, PMI_FP64, PMI_VEC128,
PMI_VEC256, PMI_VEC512
}
enum ValueMappingIdx {
VMI_None = -1, VMI_3OpsGpr8Idx = PMI_GPR8 * 3, VMI_3OpsGpr16Idx = PMI_GPR16 * 3, VMI_3OpsGpr32Idx = PMI_GPR32 * 3,
VMI_3OpsGpr64Idx = PMI_GPR64 * 3, VMI_3OpsFp32Idx = PMI_FP32 * 3, VMI_3OpsFp64Idx = PMI_FP64 * 3, VMI_3OpsVec128Idx = PMI_VEC128 * 3,
VMI_3OpsVec256Idx = PMI_VEC256 * 3, VMI_3OpsVec512Idx = PMI_VEC512 * 3
}
Protected Member Functions inherited from llvm::RegisterBankInfo
RegisterBankInfo (RegisterBank **RegBanks, unsigned NumRegBanks)
Create a RegisterBankInfo that can accommodate up to NumRegBanks RegisterBank instances.
RegisterBankInfo ()
This constructor is meaningless.
RegisterBank & getRegBank (unsigned ID)
Get the register bank identified by ID.
const TargetRegisterClass & getMinimalPhysRegClass (Register Reg, const TargetRegisterInfo &TRI) const
Get the MinimalPhysRegClass for Reg.
const InstructionMapping & getInstrMappingImpl (const MachineInstr &MI) const
Try to get the mapping of MI.
const PartialMapping & getPartialMapping (unsigned StartIdx, unsigned Length, const RegisterBank &RegBank) const
Get the uniquely generated PartialMapping for the given arguments.
const ValueMapping & getValueMapping (unsigned StartIdx, unsigned Length, const RegisterBank &RegBank) const
The most common ValueMapping consists of a single PartialMapping.
const ValueMapping & getValueMapping (const PartialMapping *BreakDown, unsigned NumBreakDowns) const
Get the ValueMapping for the given arguments.
template<typename Iterator >
const ValueMapping * getOperandsMapping (Iterator Begin, Iterator End) const
Get the uniquely generated array of ValueMapping for the elements of between Begin and End.
const ValueMapping * getOperandsMapping (const SmallVectorImpl< const ValueMapping *> &OpdsMapping) const
Get the uniquely generated array of ValueMapping for the elements of OpdsMapping.
const ValueMapping * getOperandsMapping (std::initializer_list< const ValueMapping *> OpdsMapping) const
Get the uniquely generated array of ValueMapping for the given arguments.
Static Protected Member Functions inherited from llvm::X86GenRegisterBankInfo
static PartialMappingIdx getPartialMappingIdx (const LLT &Ty, bool isFP)
static const RegisterBankInfo::ValueMapping * getValueMapping (PartialMappingIdx Idx, unsigned NumOperands)
Protected Attributes inherited from llvm::RegisterBankInfo
RegisterBank ** RegBanks
Hold the set of supported register banks.
unsigned NumRegBanks
Total number of register banks.
DenseMap< unsigned, std::unique_ptr< const PartialMapping > > MapOfPartialMappings
Keep dynamically allocated PartialMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< const ValueMapping > > MapOfValueMappings
Keep dynamically allocated ValueMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< ValueMapping[]> > MapOfOperandsMappings
Keep dynamically allocated array of ValueMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< const InstructionMapping > > MapOfInstructionMappings
Keep dynamically allocated InstructionMapping in a separate map.
DenseMap< unsigned, const TargetRegisterClass * > PhysRegMinimalRCs
Getting the minimal register class of a physreg is expensive.
Static Protected Attributes inherited from llvm::X86GenRegisterBankInfo
static RegisterBankInfo::PartialMapping PartMappings []
static RegisterBankInfo::ValueMapping ValMappings []
Detailed Description
This class provides the information for the target register banks.
Definition at line 43 of file X86RegisterBankInfo.h.
Constructor & Destructor Documentation
X86RegisterBankInfo()
X86RegisterBankInfo::X86RegisterBankInfo (const TargetRegisterInfo & TRI)
Definition at line 28 of file X86RegisterBankInfo.cpp.
References assert(), llvm::RegisterBank::covers(), llvm::RegisterBankInfo::getRegBank(), llvm::TargetRegisterInfo::getRegClass(), and llvm::RegisterBank::getSize().
Member Function Documentation
applyMappingImpl()
void X86RegisterBankInfo::applyMappingImpl (const OperandsMapper & OpdMapper) const override virtual
See RegisterBankInfo::applyMapping.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 272 of file X86RegisterBankInfo.cpp.
References llvm::RegisterBankInfo::applyDefaultMapping().
getInstrAlternativeMappings()
RegisterBankInfo::InstructionMappings X86RegisterBankInfo::getInstrAlternativeMappings (const MachineInstr & MI) const override virtual
Get the alternative mappings for MI.
Alternative in the sense different from getInstrMapping.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 278 of file X86RegisterBankInfo.cpp.
References llvm::RegisterBankInfo::getInstrAlternativeMappings(), llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::getSizeInBits(), llvm::MachineFunction::getSubtarget(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Size, and TRI.
getInstrMapping()
const RegisterBankInfo::InstructionMapping & X86RegisterBankInfo::getInstrMapping (const MachineInstr & MI) const override virtual
Get the mapping of the different operands of MI on the register bank.
This mapping should be the direct translation of MI. In other words, when MI is mapped with the returned mapping, only the register banks of the operands of MI need to be updated. In particular, neither the opcode nor the type of MI needs to be updated for this direct mapping.
The target independent implementation gives a mapping based on the register classes for the target specific opcode. It uses the ID RegisterBankInfo::DefaultMappingID for that mapping. Make sure you do not use that ID for the alternative mapping for MI. See getInstrAlternativeMappings for the alternative mappings.
For instance, if MI is a vector add, the mapping should not be a scalarization of the add.
Postcondition
returnedVal.verify(MI).
Note
If returnedVal does not verify MI, this would probably mean that the target does not support that instruction.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 162 of file X86RegisterBankInfo.cpp.
References assert(), llvm::RegisterBankInfo::DefaultMappingID, llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::RegisterBankInfo::getInstructionMapping(), llvm::RegisterBankInfo::getInvalidInstructionMapping(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::X86GenRegisterBankInfo::getValueMapping(), llvm::isPreISelGenericOpcode(), llvm::RegisterBankInfo::InstructionMapping::isValid(), llvm::X86GenRegisterBankInfo::PMI_GPR8, llvm::X86GenRegisterBankInfo::PMI_None, and Size.
getRegBankFromRegClass()
const RegisterBank & X86RegisterBankInfo::getRegBankFromRegClass (const TargetRegisterClass & RC, LLT Ty) const override virtual
Get a register bank that covers RC.
Precondition
RC is a user-defined register class (as opposed as one generated by TableGen).
Note
The mapping RC -> RegBank could be built while adding the coverage for the register banks. However, we do not do it, because, at least for now, we only need this information for register classes that are used in the description of instruction. In other words, there are just a handful of them and we do not want to waste space.
Todo:
This should be TableGen'ed.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 44 of file X86RegisterBankInfo.cpp.
References llvm::RegisterBankInfo::getRegBank(), and llvm_unreachable.
The documentation for this class was generated from the following files:
lib/Target/X86/X86RegisterBankInfo.h
lib/Target/X86/X86RegisterBankInfo.cpp