LLVM: llvm::ConstantFP Class Reference
llvm::ConstantFP Class Reference final
ConstantFP - Floating Point Values [float, double].
#include "llvm/IR/Constants.h"
Public Member Functions
ConstantFP (const ConstantFP &)=delete
const APFloat & getValueAPF () const
bool isZero () const
Return true if the value is positive or negative zero.
bool isNegative () const
Return true if the sign bit is set.
bool isInfinity () const
Return true if the value is infinity.
bool isNaN () const
Return true if the value is a NaN.
bool isExactlyValue (const APFloat &V) const
We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
bool isExactlyValue (double V) const
Public Member Functions inherited from llvm::ConstantData
ConstantData (const ConstantData &)=delete
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefElement () const
Return true if this is a vector constant that includes any undefined elements.
bool containsConstantExpression () const
Return true if this is a vector constant that includes any constant expressions.
bool canTrap () const
Return true if evaluation of this constant could trap.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry.
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static Constant * getZeroValueForNegation (Type *Ty)
Floating point negation must be implemented with f(x) = -0.0 - x.
static Constant * get (Type *Ty, double V)
This returns a ConstantFP, or a vector containing a splat of a ConstantFP, for the specified value in the specified type.
static Constant * get (Type *Ty, const APFloat &V)
If Ty is a vector type, return a Constant with a splat of the given value.
static Constant * get (Type *Ty, StringRef Str)
static ConstantFP * get (LLVMContext &Context, const APFloat &V)
static Constant * getNaN (Type *Ty, bool Negative=false, uint64_t Payload=0)
static Constant * getQNaN (Type *Ty, bool Negative=false, APInt *Payload=nullptr)
static Constant * getSNaN (Type *Ty, bool Negative=false, APInt *Payload=nullptr)
static Constant * getNegativeZero (Type *Ty)
static Constant * getInfinity (Type *Ty, bool Negative=false)
static bool isValueValidForType (Type *Ty, const APFloat &V)
Return true if Ty is big enough to represent V.
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::ConstantData
static bool classof (const Value *V)
Methods to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class Constant
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::ConstantData
ConstantData (Type *Ty, ValueTy VT)
void * operator new (size_t s)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
ConstantFP - Floating Point Values [float, double].
Definition at line 263 of file Constants.h.
Constructor & Destructor Documentation
ConstantFP()
llvm::ConstantFP::ConstantFP (const ConstantFP &) delete
Member Function Documentation
classof()
static bool llvm::ConstantFP::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 332 of file Constants.h.
References llvm::Value::getValueID().
get() [1/4]
Constant * ConstantFP::get (Type * Ty, double V) static
This returns a ConstantFP, or a vector containing a splat of a ConstantFP, for the specified value in the specified type.
This should only be used for simple constant values like 2.0/1.0 etc, that are known-valid both as host double and as the target format.
Definition at line 767 of file Constants.cpp.
References C, Context, llvm::APFloat::convert(), llvm::Type::getContext(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::APFloatBase::rmNearestTiesToEven, and TypeToFloatSemantics().
Referenced by llvm::MachineIRBuilder::buildFConstant(), llvm::canConstantFoldCallTo(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldUnaryInstruction(), llvm::createAMDGPUPrintfRuntimeBinding(), createAndInstr(), llvm::MDBuilder::createFPMath(), createPowWithIntegerExponent(), llvm::createSimpleTargetReduction(), llvm::AMDGPULibCalls::fold(), FoldBitCast(), foldFDivConstantDivisor(), FunctionNumber(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getBinOpIdentity(), llvm::SelectionDAG::getConstantFP(), getConstantVector(), llvm::ConstantDataSequential::getElementAsConstant(), getIntToFPVal(), getMulHu(), getNegatibleInsts(), getNormalLoadInput(), llvm::Constant::getNullValue(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), llvm::getSafeVectorConstantForBinop(), getSignedIntOrFpConstant(), getSqrtCall(), llvm::InnerLoopVectorizer::getStepVector(), llvm::hoistRegion(), LLVMConstReal(), LLVMConstRealOfString(), LLVMConstRealOfStringAndSize(), llvm::log2(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), LowerFPToInt(), LowerNegateToMultiply(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::fuzzerop::makeConstantsWithType(), optimizeSQRT(), simplifyBinaryIntrinsic(), SimplifyFDivInst(), SimplifyNVVMIntrinsic(), valueHasFloatPrecision(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFSub(), and llvm::LegalizerHelper::widenScalar().
get() [2/4]
Constant * ConstantFP::get (Type * Ty, const APFloat & V) static
If Ty is a vector type, return a Constant with a splat of the given value.
Otherwise return a ConstantFP for the given value.
Definition at line 783 of file Constants.cpp.
References assert(), C, llvm::Type::getContext(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and llvm::Value::getType().
get() [3/4]
Constant * ConstantFP::get (Type * Ty, StringRef Str) static
Definition at line 795 of file Constants.cpp.
References C, Context, llvm::Type::getContext(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and TypeToFloatSemantics().
get() [4/4]
ConstantFP * ConstantFP::get (LLVMContext & Context, const APFloat & V) static
Definition at line 862 of file Constants.cpp.
References assert(), llvm::ISD::ConstantFP, llvm::LLVMContextImpl::FPConstants, llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getFP128Ty(), llvm::Type::getHalfTy(), llvm::Type::getPPC_FP128Ty(), llvm::APFloat::getSemantics(), llvm::Type::getX86_FP80Ty(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm::LLVMContext::pImpl, llvm::APFloatBase::PPCDoubleDouble(), and llvm::APFloatBase::x87DoubleExtended().
getInfinity()
Constant * ConstantFP::getInfinity (Type * Ty, bool Negative = false) static
Definition at line 890 of file Constants.cpp.
References assert(), C, llvm::ISD::ConstantFP, llvm::Type::getContext(), llvm::APFloat::getInf(), llvm::Type::getScalarType(), llvm::APFloat::getSemantics(), llvm::ConstantVector::getSplat(), and TypeToFloatSemantics().
Referenced by getSqrtCall(), and simplifyBinaryIntrinsic().
getNaN()
Constant * ConstantFP::getNaN (Type * Ty, bool Negative = false, uint64_t Payload = 0) static
Definition at line 808 of file Constants.cpp.
References C, llvm::Type::getContext(), llvm::APFloat::getNaN(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and TypeToFloatSemantics().
Referenced by llvm::ConstantFoldBinaryInstruction(), propagateNaN(), and simplifyFPOp().
getNegativeZero()
Constant * ConstantFP::getNegativeZero (Type * Ty) static
Definition at line 841 of file Constants.cpp.
References C, llvm::Type::getContext(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::APFloat::getZero(), and TypeToFloatSemantics().
Referenced by llvm::BinaryOperator::CreateFNegFMF(), llvm::ConstantExpr::getBinOpIdentity(), SimplifyFRemInst(), and llvm::InstCombiner::visitAtomicRMWInst().
getQNaN()
Constant * ConstantFP::getQNaN (Type * Ty, bool Negative = false, APInt * Payload = nullptr) static
Definition at line 819 of file Constants.cpp.
References C, llvm::Type::getContext(), llvm::APFloat::getQNaN(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and TypeToFloatSemantics().
getSNaN()
Constant * ConstantFP::getSNaN (Type * Ty, bool Negative = false, APInt * Payload = nullptr) static
Definition at line 830 of file Constants.cpp.
References C, llvm::Type::getContext(), llvm::Type::getScalarType(), llvm::APFloat::getSNaN(), llvm::ConstantVector::getSplat(), and TypeToFloatSemantics().
getValueAPF()
const APFloat& llvm::ConstantFP::getValueAPF () const inline
Definition at line 302 of file Constants.h.
Referenced by llvm::DwarfUnit::addConstantFPValue(), llvm::MachineIRBuilder::buildFConstant(), llvm::canConstantFoldCallTo(), CC_MipsO32_FP64(), ConvertToSInt(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::DwarfDebug::emitDebugLocValue(), emitDebugValueComment(), emitGlobalConstantFP(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), fitsInFPType(), llvm::getConstantVRegValWithLookThrough(), llvm::FPMathOperator::getFPAccuracy(), getImplicitScaleFactor(), getOpenCLAlignment(), llvm::ConstantFPSDNode::getValueAPF(), getVectorSHLImm(), llvm::HexagonLowerToMC(), llvm::ConstantFPSDNode::isExactlyValue(), llvm::isMathLibCallNoop(), isStackPtrRelative(), llvm::ARMLegalizerInfo::legalizeCustom(), LLVMConstRealGetDouble(), llvm::log2(), llvm::WebAssemblyMCInstLower::lower(), llvm::HexagonTargetLowering::LowerBITCAST(), llvm::ARMAsmPrinter::lowerOperand(), shouldUseAndMask(), VisitGlobalVariableForEmission(), and llvm::LegalizerHelper::widenScalar().
getZeroValueForNegation()
Constant * ConstantFP::getZeroValueForNegation (Type * Ty) static
Floating point negation must be implemented with f(x) = -0.0 - x.
This method returns the negative zero constant for floating point or vector floating point types; for all other types, it returns the null value.
Definition at line 853 of file Constants.cpp.
References llvm::Constant::getNullValue(), and llvm::Type::isFPOrFPVectorTy().
Referenced by llvm::BinaryOperator::CreateFNeg(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUWNeg(), llvm::IRTranslator::getAnalysisUsage(), llvm::ConstantExpr::getNeg(), llvm::LegalizerHelper::lower(), and llvm::SelectionDAGBuilder::UpdateSplitBlock().
isExactlyValue() [1/2]
bool ConstantFP::isExactlyValue (const APFloat & V) const
We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
As such, this method can be used to do an exact bit-for-bit comparison of two floating point values. The version with a double operand is retained because it's so convenient to write isExactlyValue(2.0), but please use it only for simple constants.
Definition at line 906 of file Constants.cpp.
References llvm_unreachable.
Referenced by llvm::AMDGPULibCalls::fold(), llvm::log2(), and shouldKeepFDivF32().
isExactlyValue() [2/2]
bool llvm::ConstantFP::isExactlyValue (double V) const inline
Definition at line 324 of file Constants.h.
References llvm::APFloat::convert(), llvm::APFloat::getSemantics(), and llvm::APFloatBase::rmNearestTiesToEven.
isInfinity()
bool llvm::ConstantFP::isInfinity () const inline
Return true if the value is infinity.
Definition at line 311 of file Constants.h.
References llvm::APFloat::isInfinity().
Referenced by llvm::ConstantFPSDNode::isInfinity().
isNaN()
bool llvm::ConstantFP::isNaN () const inline
Return true if the value is a NaN.
Definition at line 314 of file Constants.h.
References llvm::APFloat::isNaN().
Referenced by llvm::ConstantFPSDNode::isNaN().
isNegative()
bool llvm::ConstantFP::isNegative () const inline
Return true if the sign bit is set.
Definition at line 308 of file Constants.h.
References llvm::APFloat::isNegative().
Referenced by isMulPowOf2(), llvm::ConstantFPSDNode::isNegative(), llvm::log2(), and selectFCMPOpc().
isValueValidForType()
bool ConstantFP::isValueValidForType (Type * Ty, const APFloat & V) static
Return true if Ty is big enough to represent V.
Definition at line 1363 of file Constants.cpp.
References llvm::lltok::APFloat, llvm::APFloat::convert(), llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::APFloat::getSemantics(), llvm::Type::getTypeID(), llvm::Type::HalfTyID, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm::Type::PPC_FP128TyID, llvm::APFloatBase::PPCDoubleDouble(), llvm::APFloatBase::rmNearestTiesToEven, llvm::Type::X86_FP80TyID, and llvm::APFloatBase::x87DoubleExtended().
Referenced by FunctionNumber().
isZero()
bool llvm::ConstantFP::isZero () const inline
Return true if the value is positive or negative zero.
Definition at line 305 of file Constants.h.
References llvm::APFloat::isZero().
Referenced by isMulPowOf2(), llvm::ConstantFPSDNode::isZero(), llvm::log2(), and selectFCMPOpc().
Friends And Related Function Documentation
Constant
friend class Constant friend
Definition at line 264 of file Constants.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Constants.h
lib/IR/Constants.cpp