LLVM: llvm::TypeFinder Class Reference
llvm::TypeFinder Class Reference
TypeFinder - Walk over a module, identifying all of the types that are used by the module.
#include "llvm/IR/TypeFinder.h"
Public Types
using iterator = std::vector< StructType * >::iterator
using const_iterator = std::vector< StructType * >::const_iterator
Public Member Functions
TypeFinder ()=default
void run (const Module &M, bool onlyNamed)
void clear ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
iterator erase (iterator I, iterator E)
StructType *& operator[] (unsigned Idx)
DenseSet< const MDNode * > & getVisitedMetadata ()
Detailed Description
TypeFinder - Walk over a module, identifying all of the types that are used by the module.
Definition at line 30 of file TypeFinder.h.
Member Typedef Documentation
const_iterator
using llvm::TypeFinder::const_iterator = std::vector<StructType*>::const_iterator
Definition at line 47 of file TypeFinder.h.
iterator
using llvm::TypeFinder::iterator = std::vector<StructType*>::iterator
Definition at line 46 of file TypeFinder.h.
Constructor & Destructor Documentation
TypeFinder()
llvm::TypeFinder::TypeFinder () default
Member Function Documentation
begin() [1/2]
iterator llvm::TypeFinder::begin () inline
Definition at line 49 of file TypeFinder.h.
Referenced by llvm::Module::getIdentifiedStructTypes().
begin() [2/2]
const_iterator llvm::TypeFinder::begin () const inline
Definition at line 52 of file TypeFinder.h.
clear()
void TypeFinder::clear ()
Definition at line 84 of file TypeFinder.cpp.
References C, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::clear(), E, llvm::SmallVectorBase::empty(), llvm::Value::getType(), I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), N, llvm::User::operands(), llvm::MDNode::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Type::subtype_rbegin(), and llvm::Type::subtype_rend().
empty()
bool llvm::TypeFinder::empty () const inline
Definition at line 55 of file TypeFinder.h.
end() [1/2]
iterator llvm::TypeFinder::end () inline
Definition at line 50 of file TypeFinder.h.
Referenced by llvm::Module::getIdentifiedStructTypes().
end() [2/2]
const_iterator llvm::TypeFinder::end () const inline
Definition at line 53 of file TypeFinder.h.
erase()
iterator llvm::TypeFinder::erase (iterator I, iterator E) inline
Definition at line 57 of file TypeFinder.h.
getVisitedMetadata()
DenseSet<const MDNode *>& llvm::TypeFinder::getVisitedMetadata () inline
Definition at line 61 of file TypeFinder.h.
operator[]()
StructType*& llvm::TypeFinder::operator[] (unsigned Idx) inline
Definition at line 59 of file TypeFinder.h.
run()
void TypeFinder::run (const Module & M, bool onlyNamed)
Definition at line 31 of file TypeFinder.cpp.
References llvm::Module::aliases(), G, llvm::Module::globals(), I, and llvm::RISCVFenceField::O.
Referenced by llvm::Module::getIdentifiedStructTypes(), llvm::IRMover::IRMover(), and StripTypeNames().
size()
size_t llvm::TypeFinder::size () const inline
Definition at line 56 of file TypeFinder.h.
Referenced by StripTypeNames().
The documentation for this class was generated from the following files:
include/llvm/IR/TypeFinder.h
lib/IR/TypeFinder.cpp