LLVM: llvm::HexagonBlockRanges::RangeList Class Reference
llvm::HexagonBlockRanges::RangeList Class Reference
#include "Target/Hexagon/HexagonBlockRanges.h"
Public Member Functions
void add (IndexType Start, IndexType End, bool Fixed, bool TiedEnd)
void add (const IndexRange &Range)
void include (const RangeList &RL)
void unionize (bool MergeAdjacent=false)
void subtract (const IndexRange &Range)
Detailed Description
Definition at line 105 of file HexagonBlockRanges.h.
Member Function Documentation
add() [1/2]
void llvm::HexagonBlockRanges::RangeList::add (IndexType Start, IndexType End, bool Fixed, bool TiedEnd) inline
Definition at line 107 of file HexagonBlockRanges.h.
add() [2/2]
void llvm::HexagonBlockRanges::RangeList::add (const IndexRange & Range) inline
Definition at line 110 of file HexagonBlockRanges.h.
References B.
include()
void HexagonBlockRanges::RangeList::include (const RangeList & RL)
Definition at line 75 of file HexagonBlockRanges.cpp.
References llvm::is_contained().
subtract()
void HexagonBlockRanges::RangeList::subtract (const IndexRange & Range)
Definition at line 141 of file HexagonBlockRanges.cpp.
References llvm::sys::path::begin(), llvm::HexagonBlockRanges::IndexRange::end(), I, llvm::HexagonBlockRanges::IndexRange::overlaps(), and llvm::T.
unionize()
void HexagonBlockRanges::RangeList::unionize (bool MergeAdjacent = false)
Definition at line 83 of file HexagonBlockRanges.cpp.
References add(), assert(), B, llvm::sys::path::begin(), llvm::empty(), llvm::HexagonBlockRanges::IndexRange::end(), llvm::HexagonBlockRanges::IndexRange::Fixed, Merge, llvm::HexagonBlockRanges::IndexType::None, llvm::HexagonBlockRanges::IndexRange::overlaps(), llvm::sort(), and llvm::HexagonBlockRanges::IndexRange::start().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonBlockRanges.h
lib/Target/Hexagon/HexagonBlockRanges.cpp