LLVM: llvm::parallel::detail::TaskGroup Class Reference
llvm::parallel::detail::TaskGroup Class Reference
#include "llvm/Support/Parallel.h"
Public Member Functions
TaskGroup ()
~TaskGroup ()
void spawn (std::function< void()> f)
void sync () const
Detailed Description
Definition at line 66 of file Parallel.h.
Constructor & Destructor Documentation
TaskGroup()
llvm::parallel::detail::TaskGroup::TaskGroup ()
Definition at line 146 of file Parallel.cpp.
~TaskGroup()
llvm::parallel::detail::TaskGroup::~TaskGroup ()
Definition at line 147 of file Parallel.cpp.
References llvm::parallel::detail::TaskGroupInstances.
Member Function Documentation
spawn()
void llvm::parallel::detail::TaskGroup::spawn (std::function< void()> f)
Definition at line 149 of file Parallel.cpp.
References llvm::parallel::detail::Latch::dec(), F(), and llvm::parallel::detail::Latch::inc().
sync()
void llvm::parallel::detail::TaskGroup::sync () const inline
Definition at line 76 of file Parallel.h.
References llvm::parallel::detail::Latch::sync().
The documentation for this class was generated from the following files:
include/llvm/Support/Parallel.h
lib/Support/Parallel.cpp