LLVM: llvm::MachO::InterfaceFileRef Class Reference
llvm::MachO::InterfaceFileRef Class Reference
Reference to an interface file.
#include "llvm/TextAPI/MachO/InterfaceFile.h"
Public Types
using const_target_iterator = TargetList::const_iterator
using const_target_range = llvm::iterator_range< const_target_iterator >
Public Member Functions
InterfaceFileRef ()=default
InterfaceFileRef (StringRef InstallName)
InterfaceFileRef (StringRef InstallName, const TargetList Targets)
StringRef getInstallName () const
void addTarget (const Target &Target)
template<typename RangeT >
void addTargets (RangeT &&Targets)
const_target_range targets () const
ArchitectureSet getArchitectures () const
PlatformSet getPlatforms () const
bool operator== (const InterfaceFileRef &O) const
bool operator!= (const InterfaceFileRef &O) const
bool operator< (const InterfaceFileRef &O) const
Detailed Description
Reference to an interface file.
Definition at line 81 of file InterfaceFile.h.
Member Typedef Documentation
const_target_iterator
using llvm::MachO::InterfaceFileRef::const_target_iterator = TargetList::const_iterator
Definition at line 98 of file InterfaceFile.h.
const_target_range
using llvm::MachO::InterfaceFileRef::const_target_range = llvm::iterator_range<const_target_iterator>
Definition at line 99 of file InterfaceFile.h.
Constructor & Destructor Documentation
InterfaceFileRef() [1/3]
llvm::MachO::InterfaceFileRef::InterfaceFileRef () default
InterfaceFileRef() [2/3]
llvm::MachO::InterfaceFileRef::InterfaceFileRef (StringRef InstallName) inline
Definition at line 85 of file InterfaceFile.h.
InterfaceFileRef() [3/3]
llvm::MachO::InterfaceFileRef::InterfaceFileRef (StringRef InstallName, const TargetList Targets) inline
Definition at line 87 of file InterfaceFile.h.
Member Function Documentation
addTarget()
void llvm::MachO::InterfaceFileRef::addTarget (const Target & Target)
Definition at line 44 of file InterfaceFile.cpp.
References llvm::MachO::detail::addEntry().
addTargets()
template<typename RangeT > void llvm::MachO::InterfaceFileRef::addTargets (RangeT && Targets) inline
Definition at line 93 of file InterfaceFile.h.
getArchitectures()
ArchitectureSet llvm::MachO::InterfaceFileRef::getArchitectures () const inline
Definition at line 102 of file InterfaceFile.h.
References llvm::MachO::mapToArchitectureSet().
getInstallName()
StringRef llvm::MachO::InterfaceFileRef::getInstallName () const inline
Definition at line 90 of file InterfaceFile.h.
Referenced by llvm::MachO::detail::addEntry().
getPlatforms()
PlatformSet llvm::MachO::InterfaceFileRef::getPlatforms () const inline
Definition at line 106 of file InterfaceFile.h.
References llvm::MachO::mapToPlatformSet().
operator!=()
bool llvm::MachO::InterfaceFileRef::operator!= (const InterfaceFileRef & O) const inline
Definition at line 112 of file InterfaceFile.h.
operator<()
bool llvm::MachO::InterfaceFileRef::operator< (const InterfaceFileRef & O) const inline
Definition at line 116 of file InterfaceFile.h.
operator==()
bool llvm::MachO::InterfaceFileRef::operator== (const InterfaceFileRef & O) const inline
Definition at line 108 of file InterfaceFile.h.
targets()
const_target_range llvm::MachO::InterfaceFileRef::targets () const inline
Definition at line 100 of file InterfaceFile.h.
The documentation for this class was generated from the following files:
include/llvm/TextAPI/MachO/InterfaceFile.h
lib/TextAPI/MachO/InterfaceFile.cpp