LLVM: llvm::JITEventListener Class Reference
llvm::JITEventListener Class Reference
JITEventListener - Abstract interface for use by the JIT to notify clients about significant events during compilation.
#include "llvm/ExecutionEngine/JITEventListener.h"
Public Types
using ObjectKey = uint64_t
Public Member Functions
JITEventListener ()=default
virtual ~JITEventListener ()=default
virtual void notifyObjectLoaded (ObjectKey K, const object::ObjectFile &Obj, const RuntimeDyld::LoadedObjectInfo &L)
notifyObjectLoaded - Called after an object has had its sections allocated and addresses assigned to all symbols.
virtual void notifyFreeingObject (ObjectKey K)
notifyFreeingObject - Called just before the memory associated with a previously emitted object is released.
Static Public Member Functions
static JITEventListener * createGDBRegistrationListener ()
static JITEventListener * createIntelJITEventListener ()
static JITEventListener * createIntelJITEventListener (IntelJITEventsWrapper *AlternativeImpl)
static JITEventListener * createOProfileJITEventListener ()
static JITEventListener * createOProfileJITEventListener (OProfileWrapper *AlternativeImpl)
static JITEventListener * createPerfJITEventListener ()
Detailed Description
JITEventListener - Abstract interface for use by the JIT to notify clients about significant events during compilation.
For example, to notify profilers and debuggers that need to know where functions have been emitted.
The default implementation of each method does nothing.
Definition at line 42 of file JITEventListener.h.
Member Typedef Documentation
ObjectKey
using llvm::JITEventListener::ObjectKey = uint64_t
Definition at line 44 of file JITEventListener.h.
Constructor & Destructor Documentation
JITEventListener()
llvm::JITEventListener::JITEventListener () default
~JITEventListener()
virtual llvm::JITEventListener::~JITEventListener () virtual default
Member Function Documentation
createGDBRegistrationListener()
JITEventListener * llvm::JITEventListener::createGDBRegistrationListener () static
Definition at line 229 of file GDBRegistrationListener.cpp.
Referenced by llvm::MCJIT::createJIT(), and LLVMCreateGDBRegistrationListener().
createIntelJITEventListener() [1/2]
JITEventListener * llvm::JITEventListener::createIntelJITEventListener () inline static
Definition at line 76 of file JITEventListener.h.
Referenced by LLVMCreateIntelJITEventListener().
createIntelJITEventListener() [2/2]
JITEventListener * llvm::JITEventListener::createIntelJITEventListener (IntelJITEventsWrapper * AlternativeImpl) inline static
Definition at line 78 of file JITEventListener.h.
createOProfileJITEventListener() [1/2]
JITEventListener * llvm::JITEventListener::createOProfileJITEventListener () inline static
Definition at line 92 of file JITEventListener.h.
Referenced by LLVMCreateOProfileJITEventListener().
createOProfileJITEventListener() [2/2]
static JITEventListener* llvm::JITEventListener::createOProfileJITEventListener (OProfileWrapper * AlternativeImpl) inline static
Definition at line 94 of file JITEventListener.h.
createPerfJITEventListener()
JITEventListener * llvm::JITEventListener::createPerfJITEventListener () inline static
Definition at line 103 of file JITEventListener.h.
References DEFINE_SIMPLE_CONVERSION_FUNCTIONS.
Referenced by LLVMCreatePerfJITEventListener().
notifyFreeingObject()
virtual void llvm::JITEventListener::notifyFreeingObject (ObjectKey K) inline virtual
notifyFreeingObject - Called just before the memory associated with a previously emitted object is released.
Definition at line 63 of file JITEventListener.h.
notifyObjectLoaded()
virtual void llvm::JITEventListener::notifyObjectLoaded (ObjectKey K, const object::ObjectFile & Obj, const RuntimeDyld::LoadedObjectInfo & L) inline virtual
notifyObjectLoaded - Called after an object has had its sections allocated and addresses assigned to all symbols.
Note: Section memory will not have been relocated yet. notifyFunctionLoaded will not be called for individual functions in the object.
ELF-specific information The ObjectImage contains the generated object image with section headers updated to reflect the address at which sections were loaded and with relocations performed in-place on debug sections.
Definition at line 58 of file JITEventListener.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITEventListener.h
lib/ExecutionEngine/ExecutionEngine.cpp
lib/ExecutionEngine/GDBRegistrationListener.cpp
lib/ExecutionEngine/IntelJITEvents/IntelJITEventListener.cpp
lib/ExecutionEngine/OProfileJIT/OProfileJITEventListener.cpp
lib/ExecutionEngine/PerfJITEvents/PerfJITEventListener.cpp