LLVM: llvm::MachinePostDominatorTree Class Reference
llvm::MachinePostDominatorTree Class Reference
MachinePostDominatorTree - an analysis pass wrapper for DominatorTree used to compute the post-dominator tree for MachineFunctions.
#include "llvm/CodeGen/MachinePostDominators.h"
Public Member Functions
MachinePostDominatorTree ()
FunctionPass * createMachinePostDominatorTreePass ()
const SmallVectorImpl< MachineBasicBlock * > & getRoots () const
MachineDomTreeNode * getRootNode () const
MachineDomTreeNode * operator[] (MachineBasicBlock *BB) const
MachineDomTreeNode * getNode (MachineBasicBlock *BB) const
bool dominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool dominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
bool properlyDominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool properlyDominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
bool isVirtualRoot (const MachineDomTreeNode *Node) const
MachineBasicBlock * findNearestCommonDominator (MachineBasicBlock *A, MachineBasicBlock *B) const
MachineBasicBlock * findNearestCommonDominator (ArrayRef< MachineBasicBlock *> Blocks) const
Returns the nearest common dominator of the given blocks.
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void verifyAnalysis () const override
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
void print (llvm::raw_ostream &OS, const Module *M=nullptr) const override
print - Print out the internal state of the pass.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
MachinePostDominatorTree - an analysis pass wrapper for DominatorTree used to compute the post-dominator tree for MachineFunctions.
Definition at line 27 of file MachinePostDominators.h.
Constructor & Destructor Documentation
MachinePostDominatorTree()
llvm::MachinePostDominatorTree::MachinePostDominatorTree ()
Referenced by createMachinePostDominatorTreePass().
Member Function Documentation
createMachinePostDominatorTreePass()
FunctionPass * MachinePostDominatorTree::createMachinePostDominatorTreePass ()
Definition at line 36 of file MachinePostDominators.cpp.
References MachinePostDominatorTree().
dominates() [1/2]
bool llvm::MachinePostDominatorTree::dominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 52 of file MachinePostDominators.h.
Referenced by greaterWithBias(), and isMinSize().
dominates() [2/2]
bool llvm::MachinePostDominatorTree::dominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 57 of file MachinePostDominators.h.
findNearestCommonDominator() [1/2]
MachineBasicBlock* llvm::MachinePostDominatorTree::findNearestCommonDominator (MachineBasicBlock * A, MachineBasicBlock * B) const inline
Definition at line 75 of file MachinePostDominators.h.
References getAnalysisUsage(), and runOnMachineFunction().
Referenced by isMinSize(), and isVRegCompatibleReg().
findNearestCommonDominator() [2/2]
MachineBasicBlock * MachinePostDominatorTree::findNearestCommonDominator (ArrayRef< MachineBasicBlock *> Blocks) const
Returns the nearest common dominator of the given blocks.
If that tree node is a virtual root, a nullptr will be returned.
Definition at line 51 of file MachinePostDominators.cpp.
References assert(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), and llvm::ArrayRef< T >::front().
getAnalysisUsage()
void MachinePostDominatorTree::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 46 of file MachinePostDominators.cpp.
References llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by findNearestCommonDominator().
getNode()
MachineDomTreeNode* llvm::MachinePostDominatorTree::getNode (MachineBasicBlock * BB) const inline
Definition at line 48 of file MachinePostDominators.h.
getRootNode()
MachineDomTreeNode* llvm::MachinePostDominatorTree::getRootNode () const inline
Definition at line 42 of file MachinePostDominators.h.
getRoots()
const SmallVectorImpl<MachineBasicBlock *>& llvm::MachinePostDominatorTree::getRoots () const inline
Definition at line 38 of file MachinePostDominators.h.
isVirtualRoot()
bool llvm::MachinePostDominatorTree::isVirtualRoot (const MachineDomTreeNode * Node) const inline
Definition at line 71 of file MachinePostDominators.h.
operator[]()
MachineDomTreeNode* llvm::MachinePostDominatorTree::operator[] (MachineBasicBlock * BB) const inline
Definition at line 44 of file MachinePostDominators.h.
print()
void MachinePostDominatorTree::print (llvm::raw_ostream & OS, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 76 of file MachinePostDominators.cpp.
Referenced by releaseMemory().
properlyDominates() [1/2]
bool llvm::MachinePostDominatorTree::properlyDominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 61 of file MachinePostDominators.h.
properlyDominates() [2/2]
bool llvm::MachinePostDominatorTree::properlyDominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 66 of file MachinePostDominators.h.
releaseMemory()
void llvm::MachinePostDominatorTree::releaseMemory () inline override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 87 of file MachinePostDominators.h.
References print(), and verifyAnalysis().
runOnMachineFunction()
bool MachinePostDominatorTree::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 40 of file MachinePostDominators.cpp.
Referenced by findNearestCommonDominator(), and isMinSize().
verifyAnalysis()
void MachinePostDominatorTree::verifyAnalysis () const override virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented from llvm::Pass.
Definition at line 67 of file MachinePostDominators.cpp.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::Basic, llvm::errs(), and llvm::VerifyMachineDomInfo.
Referenced by releaseMemory().
Member Data Documentation
ID
char MachinePostDominatorTree::ID = 0 static
Definition at line 32 of file MachinePostDominators.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePostDominators.h
lib/CodeGen/MachinePostDominators.cpp