LLVM: llvm::RecurrenceDescriptor::InstDesc Class Reference
llvm::RecurrenceDescriptor::InstDesc Class Reference
This POD struct holds information about a potential recurrence operation.
#include "llvm/Analysis/IVDescriptors.h"
Public Member Functions
InstDesc (bool IsRecur, Instruction *I, Instruction *UAI=nullptr)
InstDesc (Instruction *I, MinMaxRecurrenceKind K, Instruction *UAI=nullptr)
bool isRecurrence ()
bool hasUnsafeAlgebra ()
Instruction * getUnsafeAlgebraInst ()
MinMaxRecurrenceKind getMinMaxKind ()
Instruction * getPatternInst ()
Detailed Description
This POD struct holds information about a potential recurrence operation.
Definition at line 102 of file IVDescriptors.h.
Constructor & Destructor Documentation
InstDesc() [1/2]
llvm::RecurrenceDescriptor::InstDesc::InstDesc (bool IsRecur, Instruction * I, Instruction * UAI = nullptr) inline
Definition at line 104 of file IVDescriptors.h.
InstDesc() [2/2]
llvm::RecurrenceDescriptor::InstDesc::InstDesc (Instruction * I, MinMaxRecurrenceKind K, Instruction * UAI = nullptr) inline
Definition at line 108 of file IVDescriptors.h.
Member Function Documentation
getMinMaxKind()
MinMaxRecurrenceKind llvm::RecurrenceDescriptor::InstDesc::getMinMaxKind () inline
Definition at line 118 of file IVDescriptors.h.
Referenced by llvm::RecurrenceDescriptor::isMinMaxSelectCmpPattern(), and llvm::RecurrenceDescriptor::isRecurrenceInstr().
getPatternInst()
Instruction* llvm::RecurrenceDescriptor::InstDesc::getPatternInst () inline
Definition at line 120 of file IVDescriptors.h.
References llvm::RecurrenceDescriptor::AddReductionVar(), llvm::RecurrenceDescriptor::areAllUsesIn(), llvm::RecurrenceDescriptor::getRecurrenceBinOp(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), llvm::RecurrenceDescriptor::hasMultipleUsesOf(), I, llvm::RecurrenceDescriptor::isConditionalRdxPattern(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), llvm::RecurrenceDescriptor::isMinMaxSelectCmpPattern(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), and llvm::RecurrenceDescriptor::isReductionPHI().
getUnsafeAlgebraInst()
Instruction* llvm::RecurrenceDescriptor::InstDesc::getUnsafeAlgebraInst () inline
Definition at line 116 of file IVDescriptors.h.
Referenced by llvm::RecurrenceDescriptor::isRecurrenceInstr().
hasUnsafeAlgebra()
bool llvm::RecurrenceDescriptor::InstDesc::hasUnsafeAlgebra () inline
Definition at line 114 of file IVDescriptors.h.
isRecurrence()
bool llvm::RecurrenceDescriptor::InstDesc::isRecurrence () inline
Definition at line 112 of file IVDescriptors.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/IVDescriptors.h