LLVM: llvm::mca::RegisterFile Class Reference
llvm::mca::RegisterFile Class Reference
Manages hardware register files, and tracks register definitions for register renaming purposes.
#include "llvm/MCA/HardwareUnits/RegisterFile.h"
Public Member Functions
RegisterFile (const MCSchedModel &SM, const MCRegisterInfo &mri, unsigned NumRegs=0)
void addRegisterWrite (WriteRef Write, MutableArrayRef< unsigned > UsedPhysRegs)
void addRegisterRead (ReadState &RS, const MCSubtargetInfo &STI) const
void removeRegisterWrite (const WriteState &WS, MutableArrayRef< unsigned > FreedPhysRegs)
bool tryEliminateMove (WriteState &WS, ReadState &RS)
unsigned isAvailable (ArrayRef< MCPhysReg > Regs) const
unsigned getNumRegisterFiles () const
void cycleStart ()
void dump () const
Public Member Functions inherited from llvm::mca::HardwareUnit
HardwareUnit ()=default
virtual ~HardwareUnit ()
Detailed Description
Manages hardware register files, and tracks register definitions for register renaming purposes.
Definition at line 36 of file RegisterFile.h.
Constructor & Destructor Documentation
RegisterFile()
llvm::mca::RegisterFile::RegisterFile (const MCSchedModel & SM, const MCRegisterInfo & mri, unsigned NumRegs = 0)
Definition at line 25 of file RegisterFile.cpp.
References assert(), E, llvm::SmallVectorImpl< T >::emplace_back(), llvm::MCSchedModel::getExtraProcessorInfo(), llvm::MCSchedModel::hasExtraProcessorInfo(), I, Info, llvm::MCRegisterFileDesc::NumPhysRegs, llvm::MCRegisterFileDesc::NumRegisterCostEntries, llvm::MCExtraProcessorInfo::NumRegisterFiles, llvm::MCRegisterFileDesc::RegisterCostEntryIdx, llvm::MCExtraProcessorInfo::RegisterCostTable, and llvm::MCExtraProcessorInfo::RegisterFiles.
Member Function Documentation
addRegisterRead()
void llvm::mca::RegisterFile::addRegisterRead (ReadState & RS, const MCSubtargetInfo & STI) const
Definition at line 398 of file RegisterFile.cpp.
References llvm::mca::WriteState::addUser(), llvm::mca::ReadState::getDescriptor(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::mca::ReadState::getRegisterID(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::WriteState::getWriteResourceID(), llvm::mca::ReadState::isIndependentFromDef(), llvm::PPCISD::SC, llvm::mca::ReadDescriptor::SchedClassID, llvm::mca::ReadState::setDependentWrites(), llvm::mca::ReadState::setPRF(), llvm::mca::ReadState::setReadZero(), llvm::SmallVectorBase::size(), and llvm::mca::ReadDescriptor::UseIndex.
Referenced by llvm::mca::DispatchStage::DispatchStage().
addRegisterWrite()
void llvm::mca::RegisterFile::addRegisterWrite (WriteRef Write, MutableArrayRef< unsigned > UsedPhysRegs)
Definition at line 147 of file RegisterFile.cpp.
References llvm::mca::WriteState::addUser(), assert(), llvm::APInt::clearBit(), llvm::mca::WriteState::clearsSuperRegisters(), llvm::dbgs(), llvm::MCRegisterInfo::getName(), llvm::mca::WriteState::getRegisterID(), llvm::mca::WriteRef::getSourceIndex(), llvm::mca::WriteRef::getWriteState(), I, llvm::mca::WriteState::isEliminated(), llvm::mca::WriteState::isWriteZero(), LLVM_DEBUG, second, llvm::APInt::setBit(), and llvm::mca::WriteState::setPRF().
Referenced by llvm::mca::DispatchStage::DispatchStage().
cycleStart()
void llvm::mca::RegisterFile::cycleStart ()
Definition at line 61 of file RegisterFile.cpp.
References llvm::MCRegisterFileDesc::AllowZeroMoveEliminationOnly, llvm::SmallVectorImpl< T >::emplace_back(), llvm::ArrayRef< T >::empty(), llvm::errs(), llvm::MCRegisterInfo::getName(), llvm::MCRegisterInfo::getRegClass(), I, llvm::MCRegisterInfo::isSuperRegister(), llvm::MCRegisterFileDesc::MaxMovesEliminatedPerCycle, llvm::MCRegisterFileDesc::NumPhysRegs, Reg, and llvm::SmallVectorBase::size().
Referenced by llvm::mca::DispatchStage::cycleStart(), and getNumRegisterFiles().
dump()
void llvm::mca::RegisterFile::dump () const
Definition at line 475 of file RegisterFile.cpp.
References llvm::dbgs(), llvm::APInt::dump(), E, llvm::MCRegisterInfo::getName(), getNumRegisterFiles(), llvm::MCRegisterInfo::getNumRegs(), I, and llvm::NVPTX::PTXCvtMode::RM.
Referenced by llvm::mca::DispatchStage::dump(), and getNumRegisterFiles().
getNumRegisterFiles()
unsigned llvm::mca::RegisterFile::getNumRegisterFiles () const inline
Definition at line 226 of file RegisterFile.h.
References cycleStart(), dump(), and llvm::SmallVectorBase::size().
Referenced by llvm::mca::DispatchStage::cycleStart(), llvm::mca::DispatchStage::DispatchStage(), dump(), isAvailable(), and llvm::mca::RetireStage::notifyInstructionRetired().
isAvailable()
unsigned llvm::mca::RegisterFile::isAvailable (ArrayRef< MCPhysReg > Regs) const
Definition at line 427 of file RegisterFile.cpp.
References llvm::dbgs(), E, getNumRegisterFiles(), I, and LLVM_DEBUG.
Referenced by llvm::mca::DispatchStage::DispatchStage().
removeRegisterWrite()
void llvm::mca::RegisterFile::removeRegisterWrite (const WriteState & WS, MutableArrayRef< unsigned > FreedPhysRegs)
Definition at line 243 of file RegisterFile.cpp.
References assert(), llvm::mca::WriteState::clearsSuperRegisters(), llvm::mca::WriteState::getCyclesLeft(), llvm::mca::WriteState::getRegisterID(), llvm::mca::WriteRef::getWriteState(), I, llvm::mca::WriteRef::invalidate(), llvm::mca::WriteState::isEliminated(), llvm::mca::WriteState::isWriteZero(), second, and llvm::mca::UNKNOWN_CYCLES.
Referenced by llvm::mca::RetireStage::notifyInstructionRetired().
tryEliminateMove()
bool llvm::mca::RegisterFile::tryEliminateMove (WriteState & WS, ReadState & RS)
Definition at line 291 of file RegisterFile.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::mca::WriteState::clearsSuperRegisters(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MCRegisterInfo::getName(), llvm::mca::WriteState::getRegisterID(), llvm::mca::ReadState::getRegisterID(), llvm::mca::WriteRef::getSourceIndex(), llvm::mca::WriteRef::getWriteState(), I, if(), llvm::mca::WriteRef::isValid(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::resize(), second, llvm::mca::WriteState::setEliminated(), llvm::mca::ReadState::setReadZero(), llvm::mca::WriteState::setWriteZero(), llvm::SmallVectorBase::size(), and llvm::sort().
Referenced by llvm::mca::DispatchStage::DispatchStage().
The documentation for this class was generated from the following files:
include/llvm/MCA/HardwareUnits/RegisterFile.h
lib/MCA/HardwareUnits/RegisterFile.cpp