LLVM: llvm::MachinePassRegistry< PassCtorTy > Class Template Reference
llvm::MachinePassRegistry< PassCtorTy > Class Template Reference
MachinePassRegistry - Track the registration of machine passes.
#include "llvm/CodeGen/MachinePassRegistry.h"
Public Member Functions
MachinePassRegistryNode< PassCtorTy > * getList ()
PassCtorTy getDefault ()
void setDefault (PassCtorTy C)
void setDefault (StringRef Name)
setDefault - Set the default constructor by name.
void setListener (MachinePassRegistryListener< PassCtorTy > *L)
void Add (MachinePassRegistryNode< PassCtorTy > *Node)
Add - Adds a function pass to the registration list.
void Remove (MachinePassRegistryNode< PassCtorTy > *Node)
Remove - Removes a function pass from the registration list.
Detailed Description
template<typename PassCtorTy>
class llvm::MachinePassRegistry< PassCtorTy >
MachinePassRegistry - Track the registration of machine passes.
Definition at line 73 of file MachinePassRegistry.h.
Member Function Documentation
Add()
template<typename PassCtorTy> void llvm::MachinePassRegistry< PassCtorTy >::Add (MachinePassRegistryNode< PassCtorTy > * Node) inline
Add - Adds a function pass to the registration list.
Definition at line 106 of file MachinePassRegistry.h.
Referenced by llvm::MachineSchedRegistry::MachineSchedRegistry(), llvm::RegisterRegAllocBase< RegisterRegAlloc >::RegisterRegAllocBase(), and llvm::RegisterScheduler::RegisterScheduler().
getDefault()
template<typename PassCtorTy> PassCtorTy llvm::MachinePassRegistry< PassCtorTy >::getDefault () inline
Definition at line 87 of file MachinePassRegistry.h.
Referenced by llvm::RegisterRegAllocBase< RegisterRegAlloc >::getDefault().
getList()
template<typename PassCtorTy> MachinePassRegistryNode<PassCtorTy>* llvm::MachinePassRegistry< PassCtorTy >::getList () inline
Definition at line 86 of file MachinePassRegistry.h.
Referenced by llvm::RegisterRegAllocBase< RegisterRegAlloc >::getList(), llvm::RegisterScheduler::getList(), and llvm::MachineSchedRegistry::getList().
Remove()
template<typename PassCtorTy> void llvm::MachinePassRegistry< PassCtorTy >::Remove (MachinePassRegistryNode< PassCtorTy > * Node) inline
Remove - Removes a function pass from the registration list.
Definition at line 116 of file MachinePassRegistry.h.
Referenced by llvm::MachineSchedRegistry::~MachineSchedRegistry(), llvm::RegisterRegAllocBase< RegisterRegAlloc >::~RegisterRegAllocBase(), and llvm::RegisterScheduler::~RegisterScheduler().
setDefault() [1/2]
template<typename PassCtorTy> void llvm::MachinePassRegistry< PassCtorTy >::setDefault (PassCtorTy C) inline
Definition at line 88 of file MachinePassRegistry.h.
Referenced by llvm::RegisterRegAllocBase< RegisterRegAlloc >::setDefault().
setDefault() [2/2]
template<typename PassCtorTy> void llvm::MachinePassRegistry< PassCtorTy >::setDefault (StringRef Name) inline
setDefault - Set the default constructor by name.
Definition at line 90 of file MachinePassRegistry.h.
setListener()
template<typename PassCtorTy> void llvm::MachinePassRegistry< PassCtorTy >::setListener (MachinePassRegistryListener< PassCtorTy > * L) inline
Definition at line 102 of file MachinePassRegistry.h.
Referenced by llvm::RegisterRegAllocBase< RegisterRegAlloc >::setListener(), llvm::RegisterScheduler::setListener(), and llvm::MachineSchedRegistry::setListener().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachinePassRegistry.h