LLVM: llvm::ObjectSizeOffsetEvaluator Class Reference
llvm::ObjectSizeOffsetEvaluator Class Reference
Evaluate the size and offset of an object pointed to by a Value*.
#include "llvm/Analysis/MemoryBuiltins.h"
Public Member Functions
ObjectSizeOffsetEvaluator (const DataLayout &DL, const TargetLibraryInfo *TLI, LLVMContext &Context, ObjectSizeOpts EvalOpts={})
SizeOffsetEvalType compute (Value *V)
bool knownSize (SizeOffsetEvalType SizeOffset)
bool knownOffset (SizeOffsetEvalType SizeOffset)
bool anyKnown (SizeOffsetEvalType SizeOffset)
bool bothKnown (SizeOffsetEvalType SizeOffset)
SizeOffsetEvalType visitAllocaInst (AllocaInst &I)
SizeOffsetEvalType visitCallSite (CallSite CS)
SizeOffsetEvalType visitExtractElementInst (ExtractElementInst &I)
SizeOffsetEvalType visitExtractValueInst (ExtractValueInst &I)
SizeOffsetEvalType visitGEPOperator (GEPOperator &GEP)
SizeOffsetEvalType visitIntToPtrInst (IntToPtrInst &)
SizeOffsetEvalType visitLoadInst (LoadInst &I)
SizeOffsetEvalType visitPHINode (PHINode &PHI)
SizeOffsetEvalType visitSelectInst (SelectInst &I)
SizeOffsetEvalType visitInstruction (Instruction &I)
Public Member Functions inherited from llvm::InstVisitor< ObjectSizeOffsetEvaluator, SizeOffsetEvalType >
void visit (Iterator Start, Iterator End)
void visit (Module &M)
void visit (Function &F)
void visit (BasicBlock &BB)
void visit (Module *M)
void visit (Function *F)
void visit (BasicBlock *BB)
SizeOffsetEvalType visit (Instruction *I)
SizeOffsetEvalType visit (Instruction &I)
void visitModule (Module &M)
void visitFunction (Function &F)
void visitBasicBlock (BasicBlock &BB)
SizeOffsetEvalType visitICmpInst (ICmpInst &I)
SizeOffsetEvalType visitFCmpInst (FCmpInst &I)
SizeOffsetEvalType visitAllocaInst (AllocaInst &I)
SizeOffsetEvalType visitLoadInst (LoadInst &I)
SizeOffsetEvalType visitStoreInst (StoreInst &I)
SizeOffsetEvalType visitAtomicCmpXchgInst (AtomicCmpXchgInst &I)
SizeOffsetEvalType visitAtomicRMWInst (AtomicRMWInst &I)
SizeOffsetEvalType visitFenceInst (FenceInst &I)
SizeOffsetEvalType visitGetElementPtrInst (GetElementPtrInst &I)
SizeOffsetEvalType visitPHINode (PHINode &I)
SizeOffsetEvalType visitTruncInst (TruncInst &I)
SizeOffsetEvalType visitZExtInst (ZExtInst &I)
SizeOffsetEvalType visitSExtInst (SExtInst &I)
SizeOffsetEvalType visitFPTruncInst (FPTruncInst &I)
SizeOffsetEvalType visitFPExtInst (FPExtInst &I)
SizeOffsetEvalType visitFPToUIInst (FPToUIInst &I)
SizeOffsetEvalType visitFPToSIInst (FPToSIInst &I)
SizeOffsetEvalType visitUIToFPInst (UIToFPInst &I)
SizeOffsetEvalType visitSIToFPInst (SIToFPInst &I)
SizeOffsetEvalType visitPtrToIntInst (PtrToIntInst &I)
SizeOffsetEvalType visitIntToPtrInst (IntToPtrInst &I)
SizeOffsetEvalType visitBitCastInst (BitCastInst &I)
SizeOffsetEvalType visitAddrSpaceCastInst (AddrSpaceCastInst &I)
SizeOffsetEvalType visitSelectInst (SelectInst &I)
SizeOffsetEvalType visitVAArgInst (VAArgInst &I)
SizeOffsetEvalType visitExtractElementInst (ExtractElementInst &I)
SizeOffsetEvalType visitInsertElementInst (InsertElementInst &I)
SizeOffsetEvalType visitShuffleVectorInst (ShuffleVectorInst &I)
SizeOffsetEvalType visitExtractValueInst (ExtractValueInst &I)
SizeOffsetEvalType visitInsertValueInst (InsertValueInst &I)
SizeOffsetEvalType visitLandingPadInst (LandingPadInst &I)
SizeOffsetEvalType visitFuncletPadInst (FuncletPadInst &I)
SizeOffsetEvalType visitCleanupPadInst (CleanupPadInst &I)
SizeOffsetEvalType visitCatchPadInst (CatchPadInst &I)
SizeOffsetEvalType visitFreezeInst (FreezeInst &I)
SizeOffsetEvalType visitDbgDeclareInst (DbgDeclareInst &I)
SizeOffsetEvalType visitDbgValueInst (DbgValueInst &I)
SizeOffsetEvalType visitDbgVariableIntrinsic (DbgVariableIntrinsic &I)
SizeOffsetEvalType visitDbgLabelInst (DbgLabelInst &I)
SizeOffsetEvalType visitDbgInfoIntrinsic (DbgInfoIntrinsic &I)
SizeOffsetEvalType visitMemSetInst (MemSetInst &I)
SizeOffsetEvalType visitMemCpyInst (MemCpyInst &I)
SizeOffsetEvalType visitMemMoveInst (MemMoveInst &I)
SizeOffsetEvalType visitMemTransferInst (MemTransferInst &I)
SizeOffsetEvalType visitMemIntrinsic (MemIntrinsic &I)
SizeOffsetEvalType visitVAStartInst (VAStartInst &I)
SizeOffsetEvalType visitVAEndInst (VAEndInst &I)
SizeOffsetEvalType visitVACopyInst (VACopyInst &I)
SizeOffsetEvalType visitIntrinsicInst (IntrinsicInst &I)
SizeOffsetEvalType visitCallInst (CallInst &I)
SizeOffsetEvalType visitInvokeInst (InvokeInst &I)
SizeOffsetEvalType visitCallBrInst (CallBrInst &I)
SizeOffsetEvalType visitReturnInst (ReturnInst &I)
SizeOffsetEvalType visitBranchInst (BranchInst &I)
SizeOffsetEvalType visitSwitchInst (SwitchInst &I)
SizeOffsetEvalType visitIndirectBrInst (IndirectBrInst &I)
SizeOffsetEvalType visitResumeInst (ResumeInst &I)
SizeOffsetEvalType visitUnreachableInst (UnreachableInst &I)
SizeOffsetEvalType visitCleanupReturnInst (CleanupReturnInst &I)
SizeOffsetEvalType visitCatchReturnInst (CatchReturnInst &I)
SizeOffsetEvalType visitCatchSwitchInst (CatchSwitchInst &I)
SizeOffsetEvalType visitTerminator (Instruction &I)
SizeOffsetEvalType visitCastInst (CastInst &I)
SizeOffsetEvalType visitUnaryOperator (UnaryOperator &I)
SizeOffsetEvalType visitBinaryOperator (BinaryOperator &I)
SizeOffsetEvalType visitCmpInst (CmpInst &I)
SizeOffsetEvalType visitUnaryInstruction (UnaryInstruction &I)
SizeOffsetEvalType visitCallBase (CallBase &I)
SizeOffsetEvalType visitCallSite (CallSite CS)
void visitInstruction (Instruction &I)
Static Public Member Functions
static SizeOffsetEvalType unknown ()
Detailed Description
Evaluate the size and offset of an object pointed to by a Value*.
May create code to compute the result at run-time.
Definition at line 284 of file MemoryBuiltins.h.
Constructor & Destructor Documentation
ObjectSizeOffsetEvaluator()
ObjectSizeOffsetEvaluator::ObjectSizeOffsetEvaluator (const DataLayout & DL, const TargetLibraryInfo * TLI, LLVMContext & Context, ObjectSizeOpts EvalOpts = {})
Definition at line 824 of file MemoryBuiltins.cpp.
Member Function Documentation
anyKnown()
bool llvm::ObjectSizeOffsetEvaluator::anyKnown (SizeOffsetEvalType SizeOffset) inline
Definition at line 322 of file MemoryBuiltins.h.
Referenced by compute().
bothKnown()
bool llvm::ObjectSizeOffsetEvaluator::bothKnown (SizeOffsetEvalType SizeOffset) inline
Definition at line 326 of file MemoryBuiltins.h.
References GEP.
Referenced by compute(), getBoundsCheckCond(), visitGEPOperator(), visitPHINode(), and visitSelectInst().
compute()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::compute (Value * V)
Definition at line 836 of file MemoryBuiltins.cpp.
References anyKnown(), llvm::ObjectSizeOffsetVisitor::bothKnown(), bothKnown(), llvm::SmallPtrSetImplBase::clear(), llvm::ObjectSizeOffsetVisitor::compute(), llvm::dbgs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), GEP, llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::DataLayout::getIndexType(), getOpcode(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, llvm::IRBuilderBase::SetInsertPoint(), llvm::Value::stripPointerCasts(), unknown(), llvm::InstVisitor< ObjectSizeOffsetEvaluator, SizeOffsetEvalType >::visit(), and visitGEPOperator().
Referenced by getBoundsCheckCond(), and llvm::lowerObjectSizeCall().
knownOffset()
bool llvm::ObjectSizeOffsetEvaluator::knownOffset (SizeOffsetEvalType SizeOffset) inline
Definition at line 318 of file MemoryBuiltins.h.
knownSize()
bool llvm::ObjectSizeOffsetEvaluator::knownSize (SizeOffsetEvalType SizeOffset) inline
Definition at line 314 of file MemoryBuiltins.h.
unknown()
static SizeOffsetEvalType llvm::ObjectSizeOffsetEvaluator::unknown () inline static
Definition at line 305 of file MemoryBuiltins.h.
Referenced by compute(), llvm::lowerObjectSizeCall(), visitAllocaInst(), visitCallSite(), visitExtractElementInst(), visitExtractValueInst(), visitGEPOperator(), visitInstruction(), visitIntToPtrInst(), visitLoadInst(), visitPHINode(), and visitSelectInst().
visitAllocaInst()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitAllocaInst (AllocaInst & I)
Definition at line 917 of file MemoryBuiltins.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::ConstantInt::get(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getArraySize(), llvm::DataLayout::getTypeAllocSize(), llvm::AllocaInst::isArrayAllocation(), llvm::Type::isSized(), and unknown().
visitCallSite()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitCallSite (CallSite CS)
Definition at line 930 of file MemoryBuiltins.cpp.
References AllocFnsTy::AllocTy, llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), AllocFnsTy::FstParam, getAllocationSize(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgument(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), AllocFnsTy::SndParam, StrDupLike, and unknown().
visitExtractElementInst()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitExtractElementInst (ExtractElementInst & I)
Definition at line 961 of file MemoryBuiltins.cpp.
References unknown().
visitExtractValueInst()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitExtractValueInst (ExtractValueInst & I)
Definition at line 966 of file MemoryBuiltins.cpp.
References unknown().
visitGEPOperator()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitGEPOperator (GEPOperator & GEP)
Definition at line 971 of file MemoryBuiltins.cpp.
References bothKnown(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::EmitGEPOffset(), llvm::GEPOperator::getPointerOperand(), and unknown().
Referenced by compute().
visitInstruction()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitInstruction (Instruction & I)
Definition at line 1048 of file MemoryBuiltins.cpp.
References llvm::dbgs(), LLVM_DEBUG, and unknown().
visitIntToPtrInst()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitIntToPtrInst (IntToPtrInst &)
Definition at line 981 of file MemoryBuiltins.cpp.
References unknown().
visitLoadInst()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitLoadInst (LoadInst & I)
Definition at line 986 of file MemoryBuiltins.cpp.
References unknown().
visitPHINode()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitPHINode (PHINode & PHI)
Definition at line 990 of file MemoryBuiltins.cpp.
References llvm::PHINode::addIncoming(), bothKnown(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::numbers::e, llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::PHINode::hasConstantValue(), llvm::Value::replaceAllUsesWith(), llvm::IRBuilderBase::SetInsertPoint(), and unknown().
visitSelectInst()
SizeOffsetEvalType ObjectSizeOffsetEvaluator::visitSelectInst (SelectInst & I)
Definition at line 1032 of file MemoryBuiltins.cpp.
References bothKnown(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::SelectInst::getTrueValue(), and unknown().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemoryBuiltins.h
lib/Analysis/MemoryBuiltins.cpp