LLVM: llvm::SectionEntry Class Reference
llvm::SectionEntry Class Reference
SectionEntry - represents a section emitted into memory by the dynamic linker.
#include "ExecutionEngine/RuntimeDyld/RuntimeDyldImpl.h"
Public Member Functions
SectionEntry (StringRef name, uint8_t *address, size_t size, size_t allocationSize, uintptr_t objAddress)
StringRef getName () const
uint8_t * getAddress () const
uint8_t * getAddressWithOffset (unsigned OffsetBytes) const
Return the address of this section with an offset.
size_t getSize () const
uint64_t getLoadAddress () const
void setLoadAddress (uint64_t LA)
uint64_t getLoadAddressWithOffset (unsigned OffsetBytes) const
Return the load address of this section with an offset.
uintptr_t getStubOffset () const
void advanceStubOffset (unsigned StubSize)
uintptr_t getObjAddress () const
Detailed Description
SectionEntry - represents a section emitted into memory by the dynamic linker.
Definition at line 46 of file RuntimeDyldImpl.h.
Constructor & Destructor Documentation
SectionEntry()
llvm::SectionEntry::SectionEntry (StringRef name, uint8_t * address, size_t size, size_t allocationSize, uintptr_t objAddress) inline
Definition at line 75 of file RuntimeDyldImpl.h.
Member Function Documentation
advanceStubOffset()
void llvm::SectionEntry::advanceStubOffset (unsigned StubSize) inline
Definition at line 108 of file RuntimeDyldImpl.h.
References assert().
Referenced by llvm::RuntimeDyldMachOX86_64::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::RuntimeDyldMachOAArch64::finalizeSection(), llvm::RuntimeDyldCOFFAArch64::generateRelocationStub(), llvm::RuntimeDyldCOFFX86_64::generateRelocationStub(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldELF::resolveRelocation().
getAddress()
uint8_t* llvm::SectionEntry::getAddress () const inline
Definition at line 87 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldMachO::dumpRelocationToResolve(), llvm::dumpSectionMemory(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::RuntimeDyldMachOAArch64::finalizeSection(), llvm::RuntimeDyldELF::loadObject(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOX86_64 >::registerEHFrames(), and llvm::RuntimeDyldELF::resolveRelocation().
getAddressWithOffset()
uint8_t* llvm::SectionEntry::getAddressWithOffset (unsigned OffsetBytes) const inline
Return the address of this section with an offset.
Definition at line 90 of file RuntimeDyldImpl.h.
References assert().
Referenced by llvm::applyPPChighesta(), llvm::RuntimeDyldMachOAArch64::decodeAddend(), llvm::RuntimeDyldMachOARM::decodeAddend(), llvm::RuntimeDyldMachOX86_64::finalizeSection(), llvm::RuntimeDyldMachOI386::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::RuntimeDyldCOFFAArch64::generateRelocationStub(), llvm::RuntimeDyldCOFFX86_64::generateRelocationStub(), llvm::RuntimeDyldELF::loadObject(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachO::processScatteredVANILLA(), llvm::RuntimeDyldELFMips::resolveMIPSN32Relocation(), llvm::RuntimeDyldELFMips::resolveMIPSN64Relocation(), llvm::RuntimeDyldELFMips::resolveMIPSO32Relocation(), llvm::RuntimeDyldELFMips::resolveRelocation(), llvm::RuntimeDyldCOFFX86_64::resolveRelocation(), llvm::RuntimeDyldMachOX86_64::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), llvm::RuntimeDyldELF::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), and llvm::RuntimeDyldMachOAArch64::resolveRelocation().
getLoadAddress()
uint64_t llvm::SectionEntry::getLoadAddress () const inline
Definition at line 97 of file RuntimeDyldImpl.h.
Referenced by llvm::computeDelta(), llvm::RuntimeDyldMachO::dumpRelocationToResolve(), and llvm::dumpSectionMemory().
getLoadAddressWithOffset()
uint64_t llvm::SectionEntry::getLoadAddressWithOffset (unsigned OffsetBytes) const inline
Return the load address of this section with an offset.
Definition at line 101 of file RuntimeDyldImpl.h.
References assert().
Referenced by llvm::applyPPChighesta(), llvm::RuntimeDyldCOFFAArch64::generateRelocationStub(), llvm::RuntimeDyldCOFFX86_64::generateRelocationStub(), llvm::RuntimeDyldELF::loadObject(), llvm::RuntimeDyldELFMips::resolveMIPSO32Relocation(), llvm::RuntimeDyldELFMips::resolveRelocation(), llvm::RuntimeDyldCOFFX86_64::resolveRelocation(), llvm::RuntimeDyldMachOX86_64::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), and llvm::RuntimeDyldMachOAArch64::resolveRelocation().
getName()
StringRef llvm::SectionEntry::getName () const inline
Definition at line 85 of file RuntimeDyldImpl.h.
References Name.
Referenced by llvm::dumpSectionMemory(), and llvm::RuntimeDyldELF::loadObject().
getObjAddress()
uintptr_t llvm::SectionEntry::getObjAddress () const inline
Definition at line 113 of file RuntimeDyldImpl.h.
Referenced by llvm::computeDelta(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), and llvm::RuntimeDyldCOFFX86_64::processRelocationRef().
getSize()
size_t llvm::SectionEntry::getSize () const inline
Definition at line 95 of file RuntimeDyldImpl.h.
References Size.
Referenced by llvm::dumpSectionMemory().
getStubOffset()
uintptr_t llvm::SectionEntry::getStubOffset () const inline
Definition at line 106 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldMachOX86_64::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::RuntimeDyldMachOAArch64::finalizeSection(), llvm::RuntimeDyldCOFFAArch64::generateRelocationStub(), llvm::RuntimeDyldCOFFX86_64::generateRelocationStub(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldELF::resolveRelocation().
setLoadAddress()
void llvm::SectionEntry::setLoadAddress (uint64_t LA) inline
Definition at line 98 of file RuntimeDyldImpl.h.
The documentation for this class was generated from the following file:
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldImpl.h