LLVM: llvm::orc::IRCompileLayer::IRCompiler Class Reference
llvm::orc::IRCompileLayer::IRCompiler Class Reference abstract
#include "llvm/ExecutionEngine/Orc/IRCompileLayer.h"
Public Member Functions
IRCompiler (IRMaterializationUnit::ManglingOptions MO)
virtual ~IRCompiler ()
const IRMaterializationUnit::ManglingOptions & getManglingOptions () const
virtual Expected< std::unique_ptr< MemoryBuffer > > operator() (Module &M)=0
Protected Member Functions
IRMaterializationUnit::ManglingOptions & manglingOptions ()
Detailed Description
Definition at line 32 of file IRCompileLayer.h.
Constructor & Destructor Documentation
IRCompiler()
llvm::orc::IRCompileLayer::IRCompiler::IRCompiler (IRMaterializationUnit::ManglingOptions MO) inline
Definition at line 34 of file IRCompileLayer.h.
References ~IRCompiler().
~IRCompiler()
llvm::orc::IRCompileLayer::IRCompiler::~IRCompiler () virtual
Definition at line 14 of file IRCompileLayer.cpp.
Referenced by IRCompiler().
Member Function Documentation
getManglingOptions()
const IRMaterializationUnit::ManglingOptions& llvm::orc::IRCompileLayer::IRCompiler::getManglingOptions () const inline
Definition at line 36 of file IRCompileLayer.h.
References operator()().
manglingOptions()
IRMaterializationUnit::ManglingOptions& llvm::orc::IRCompileLayer::IRCompiler::manglingOptions () inline protected
Definition at line 42 of file IRCompileLayer.h.
operator()()
virtual Expected<std::unique_ptr<MemoryBuffer> > llvm::orc::IRCompileLayer::IRCompiler::operator() (Module & M) pure virtual
Implemented in llvm::orc::ConcurrentIRCompiler, and llvm::orc::SimpleCompiler.
Referenced by getManglingOptions().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IRCompileLayer.h
lib/ExecutionEngine/Orc/IRCompileLayer.cpp