LLVM: llvm::PPCInstPrinter Class Reference
llvm::PPCInstPrinter Class Reference
#include "Target/PowerPC/MCTargetDesc/PPCInstPrinter.h"
Public Member Functions
PPCInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, Triple T)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, raw_ostream &OS)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &OS)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printPredicateOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printATBitsAsHint (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU1ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU2ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU3ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU4ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printS5ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU5ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU6ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU7ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU8ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU10ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU12ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printS16ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printU16ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printBranchOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printAbsBranchOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printTLSCall (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printcrbitm (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemRegImm (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemRegReg (const MCInst *MI, unsigned OpNo, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 21 of file PPCInstPrinter.h.
Constructor & Destructor Documentation
PPCInstPrinter()
llvm::PPCInstPrinter::PPCInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, Triple T) inline
Definition at line 30 of file PPCInstPrinter.h.
References llvm::Address, getRegisterName(), MI, llvm::RISCVFenceField::O, printAbsBranchOperand(), printAliasInstr(), printATBitsAsHint(), printBranchOperand(), printcrbitm(), printCustomAliasOperand(), printInst(), printInstruction(), printMemRegImm(), printMemRegReg(), printOperand(), printPredicateOperand(), printRegName(), printS16ImmOperand(), printS5ImmOperand(), printTLSCall(), printU10ImmOperand(), printU12ImmOperand(), printU16ImmOperand(), printU1ImmOperand(), printU2ImmOperand(), printU3ImmOperand(), printU4ImmOperand(), printU5ImmOperand(), printU6ImmOperand(), printU7ImmOperand(), and printU8ImmOperand().
Member Function Documentation
getRegisterName()
static const char* llvm::PPCInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by PPCInstPrinter(), printOperand(), and printRegName().
printAbsBranchOperand()
void PPCInstPrinter::printAbsBranchOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 416 of file PPCInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and printOperand().
Referenced by PPCInstPrinter().
printAliasInstr()
bool llvm::PPCInstPrinter::printAliasInstr (const MCInst * MI, raw_ostream & OS)
Referenced by PPCInstPrinter(), and printInst().
printATBitsAsHint()
void PPCInstPrinter::printATBitsAsHint (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 298 of file PPCInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printBranchOperand()
void PPCInstPrinter::printBranchOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 402 of file PPCInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and printOperand().
Referenced by PPCInstPrinter().
printcrbitm()
void PPCInstPrinter::printcrbitm (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 425 of file PPCInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and llvm_unreachable.
Referenced by PPCInstPrinter().
printCustomAliasOperand()
void llvm::PPCInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & OS)
Referenced by PPCInstPrinter().
printInst()
void PPCInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 67 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::Triple::isOSAIX(), llvm::MCOperand::isReg(), llvm::ISD::OR, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), and printOperand().
Referenced by PPCInstPrinter().
printInstruction()
void llvm::PPCInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by PPCInstPrinter(), and printInst().
printMemRegImm()
void PPCInstPrinter::printMemRegImm (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 443 of file PPCInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), printOperand(), and printS16ImmOperand().
Referenced by PPCInstPrinter().
printMemRegReg()
void PPCInstPrinter::printMemRegReg (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 454 of file PPCInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printOperand().
Referenced by PPCInstPrinter().
printOperand()
void PPCInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 538 of file PPCInstPrinter.cpp.
References assert(), llvm::MCInstrInfo::get(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::PPCInstrInfo::getRegNumForOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MII, llvm::MCInstPrinter::MRI, llvm::MCExpr::print(), Reg, ShowVSRNumsAsVR, and llvm::PPCRegisterInfo::stripRegisterPrefix().
Referenced by PPCInstPrinter(), printAbsBranchOperand(), printBranchOperand(), printInst(), printMemRegImm(), printMemRegReg(), printPredicateOperand(), printS16ImmOperand(), printTLSCall(), and printU16ImmOperand().
printPredicateOperand()
void PPCInstPrinter::printPredicateOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 201 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm_unreachable, llvm::PPC::PRED_BIT_SET, llvm::PPC::PRED_BIT_UNSET, llvm::PPC::PRED_EQ, llvm::PPC::PRED_EQ_MINUS, llvm::PPC::PRED_EQ_PLUS, llvm::PPC::PRED_GE, llvm::PPC::PRED_GE_MINUS, llvm::PPC::PRED_GE_PLUS, llvm::PPC::PRED_GT, llvm::PPC::PRED_GT_MINUS, llvm::PPC::PRED_GT_PLUS, llvm::PPC::PRED_LE, llvm::PPC::PRED_LE_MINUS, llvm::PPC::PRED_LE_PLUS, llvm::PPC::PRED_LT, llvm::PPC::PRED_LT_MINUS, llvm::PPC::PRED_LT_PLUS, llvm::PPC::PRED_NE, llvm::PPC::PRED_NE_MINUS, llvm::PPC::PRED_NE_PLUS, llvm::PPC::PRED_NU, llvm::PPC::PRED_NU_MINUS, llvm::PPC::PRED_NU_PLUS, llvm::PPC::PRED_UN, llvm::PPC::PRED_UN_MINUS, llvm::PPC::PRED_UN_PLUS, and printOperand().
Referenced by PPCInstPrinter().
printRegName()
void PPCInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 50 of file PPCInstPrinter.cpp.
References getRegisterName(), and llvm::NVPTX::PTXCvtMode::RN.
Referenced by PPCInstPrinter().
printS16ImmOperand()
void PPCInstPrinter::printS16ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 386 of file PPCInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and printOperand().
Referenced by PPCInstPrinter(), and printMemRegImm().
printS5ImmOperand()
void PPCInstPrinter::printS5ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 335 of file PPCInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printTLSCall()
void PPCInstPrinter::printTLSCall (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 467 of file PPCInstPrinter.cpp.
References llvm::Triple::AIX, FullRegNames, FullRegNamesWithPercent, llvm::MCOperand::getExpr(), llvm::MCInst::getOperand(), llvm::Triple::getOS(), llvm::MCConstantExpr::getValue(), llvm::MCSymbolRefExpr::getVariantKindName(), llvm::Triple::isOSDarwin(), printOperand(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by PPCInstPrinter().
printU10ImmOperand()
void PPCInstPrinter::printU10ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 372 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU12ImmOperand()
void PPCInstPrinter::printU12ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 379 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU16ImmOperand()
void PPCInstPrinter::printU16ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 394 of file PPCInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and printOperand().
Referenced by PPCInstPrinter().
printU1ImmOperand()
void PPCInstPrinter::printU1ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 307 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU2ImmOperand()
void PPCInstPrinter::printU2ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 314 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU3ImmOperand()
void PPCInstPrinter::printU3ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 321 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU4ImmOperand()
void PPCInstPrinter::printU4ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 328 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU5ImmOperand()
void PPCInstPrinter::printU5ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 342 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU6ImmOperand()
void PPCInstPrinter::printU6ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 349 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU7ImmOperand()
void PPCInstPrinter::printU7ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 356 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
printU8ImmOperand()
void PPCInstPrinter::printU8ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 366 of file PPCInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by PPCInstPrinter().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/MCTargetDesc/PPCInstPrinter.h
lib/Target/PowerPC/MCTargetDesc/PPCInstPrinter.cpp