LLVM: llvm::RemarkStreamer Class Reference
llvm::RemarkStreamer Class Reference
Streamer for remarks.
#include "llvm/IR/RemarkStreamer.h"
Public Member Functions
RemarkStreamer (std::unique_ptr< remarks::RemarkSerializer > RemarkSerializer, Optional< StringRef > Filename=None)
Optional< StringRef > getFilename () const
Return the filename that the remark diagnostics are emitted to.
raw_ostream & getStream ()
Return stream that the remark diagnostics are emitted to.
remarks::RemarkSerializer & getSerializer ()
Return the serializer used for this stream.
Error setFilter (StringRef Filter)
Set a pass filter based on a regex Filter.
void emit (const DiagnosticInfoOptimizationBase &Diag)
Emit a diagnostic through the streamer.
bool needsSection () const
Check if the remarks also need to have associated metadata in a section.
Detailed Description
Streamer for remarks.
Definition at line 27 of file RemarkStreamer.h.
Constructor & Destructor Documentation
RemarkStreamer()
RemarkStreamer::RemarkStreamer (std::unique_ptr< remarks::RemarkSerializer > RemarkSerializer, Optional< StringRef > Filename = None)
Definition at line 32 of file RemarkStreamer.cpp.
References string.
Member Function Documentation
emit()
void RemarkStreamer::emit (const DiagnosticInfoOptimizationBase & Diag)
Emit a diagnostic through the streamer.
Definition at line 104 of file RemarkStreamer.cpp.
References llvm::Filter, and llvm::DiagnosticInfoOptimizationBase::getPassName().
Referenced by getSerializer().
getFilename()
Optional<StringRef> llvm::RemarkStreamer::getFilename () const inline
Return the filename that the remark diagnostics are emitted to.
Definition at line 44 of file RemarkStreamer.h.
References llvm::None.
Referenced by llvm::AsmPrinter::emitRemarksSection().
getSerializer()
remarks::RemarkSerializer& llvm::RemarkStreamer::getSerializer () inline
Return the serializer used for this stream.
Definition at line 50 of file RemarkStreamer.h.
References emit(), llvm::Filter, needsSection(), and setFilter().
Referenced by llvm::AsmPrinter::emitRemarksSection().
getStream()
raw_ostream& llvm::RemarkStreamer::getStream () inline
Return stream that the remark diagnostics are emitted to.
Definition at line 48 of file RemarkStreamer.h.
needsSection()
bool RemarkStreamer::needsSection () const
Check if the remarks also need to have associated metadata in a section.
Definition at line 115 of file RemarkStreamer.cpp.
References assert(), llvm::remarks::Bitstream, llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, EnableRemarksSection, llvm::RemarkSetupFileError::ID, llvm::RemarkSetupPatternError::ID, llvm::RemarkSetupFormatError::ID, llvm::remarks::Separate, and llvm::remarks::YAMLStrTab.
Referenced by llvm::AsmPrinter::emitRemarksSection(), and getSerializer().
setFilter()
Error RemarkStreamer::setFilter (StringRef Filter)
Set a pass filter based on a regex Filter.
Returns an error if the regex is invalid.
Definition at line 38 of file RemarkStreamer.cpp.
References llvm::createStringError(), llvm::Regex::isValid(), llvm::make_error_code(), and llvm::Error::success().
Referenced by getSerializer(), and llvm::setupOptimizationRemarks().
The documentation for this class was generated from the following files:
include/llvm/IR/RemarkStreamer.h
lib/IR/RemarkStreamer.cpp