LLVM: llvm::ARMAttributeParser Class Reference
llvm::ARMAttributeParser Class Reference
#include "llvm/Support/ARMAttributeParser.h"
Public Member Functions
ARMAttributeParser (ScopedPrinter *SW)
ARMAttributeParser ()
void Parse (ArrayRef< uint8_t > Section, bool isLittle)
bool hasAttribute (unsigned Tag) const
unsigned getAttributeValue (unsigned Tag) const
Detailed Description
Definition at line 20 of file ARMAttributeParser.h.
Constructor & Destructor Documentation
ARMAttributeParser() [1/2]
llvm::ARMAttributeParser::ARMAttributeParser (ScopedPrinter * SW) inline
Definition at line 123 of file ARMAttributeParser.h.
ARMAttributeParser() [2/2]
llvm::ARMAttributeParser::ARMAttributeParser () inline
Definition at line 125 of file ARMAttributeParser.h.
References Parse(), and llvm::ARMBuildAttrs::Section.
Member Function Documentation
getAttributeValue()
unsigned llvm::ARMAttributeParser::getAttributeValue (unsigned Tag) const inline
Definition at line 133 of file ARMAttributeParser.h.
Referenced by llvm::object::ELFObjectFileBase::getARMFeatures(), and llvm::object::ELFObjectFileBase::setARMSubArch().
hasAttribute()
bool llvm::ARMAttributeParser::hasAttribute (unsigned Tag) const inline
Definition at line 129 of file ARMAttributeParser.h.
Referenced by llvm::object::ELFObjectFileBase::getARMFeatures(), and llvm::object::ELFObjectFileBase::setARMSubArch().
Parse()
void llvm::ARMAttributeParser::Parse (ArrayRef< uint8_t > Section, bool isLittle)
Definition at line 698 of file ARMAttributeParser.cpp.
References llvm::ArrayRef< T >::data(), llvm::errs(), llvm::support::endian::read32be(), llvm::support::endian::read32le(), and llvm::ArrayRef< T >::size().
Referenced by ARMAttributeParser(), and llvm::object::ELFObjectFile< ELFT >::getBuildAttributes().
The documentation for this class was generated from the following files:
include/llvm/Support/ARMAttributeParser.h
lib/Support/ARMAttributeParser.cpp