LLVM: llvm::GlobalsAAResult Class Reference
llvm::GlobalsAAResult Class Reference
An alias analysis result set for globals.
#include "llvm/Analysis/GlobalsModRef.h"
Classes
class FunctionInfo
The mod/ref information collected for a particular function.
Public Member Functions
GlobalsAAResult (GlobalsAAResult &&Arg)
~GlobalsAAResult ()
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
alias - If one of the pointers is to a global that we are tracking, and the other is some random pointer, we know there cannot be an alias, because the address of the global isn't taken.
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
FunctionModRefBehavior getModRefBehavior (const Function *F)
getModRefBehavior - Return the behavior of the specified function if called from the specified call site.
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
getModRefBehavior - Return the behavior of the specified function if called from the specified call site.
Public Member Functions inherited from llvm::AAResultBase< GlobalsAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Static Public Member Functions
static GlobalsAAResult analyzeModule (Module &M, std::function< const TargetLibraryInfo &(Function &F)> GetTLI, CallGraph &CG)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< GlobalsAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
An alias analysis result set for globals.
This focuses on handling aliasing properties of globals and interprocedural function call mod/ref information.
Definition at line 31 of file GlobalsModRef.h.
Constructor & Destructor Documentation
GlobalsAAResult()
GlobalsAAResult::GlobalsAAResult (GlobalsAAResult && Arg)
Definition at line 955 of file GlobalsModRef.cpp.
References Arg, assert(), and H.
~GlobalsAAResult()
GlobalsAAResult::~GlobalsAAResult ()
Definition at line 969 of file GlobalsModRef.cpp.
Member Function Documentation
alias()
AliasResult GlobalsAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
alias - If one of the pointers is to a global that we are tracking, and the other is some random pointer, we know there cannot be an alias, because the address of the global isn't taken.
Definition at line 816 of file GlobalsModRef.cpp.
References llvm::AAResultBase< DerivedT >::alias(), llvm::all_of(), llvm::CallBase::args(), llvm::CallBase::doesNotAccessMemory(), llvm::dyn_cast(), EnableUnsafeGlobalsModRefAliasResults, llvm::GetUnderlyingObject(), llvm::GetUnderlyingObjects(), llvm::is_contained(), llvm::isIdentifiedObject(), llvm::ModRef, llvm::NoAlias, llvm::NoModRef, llvm::CallBase::onlyReadsMemory(), llvm::MemoryLocation::Ptr, and llvm::Ref.
analyzeModule()
GlobalsAAResult GlobalsAAResult::analyzeModule (Module & M, std::function< const TargetLibraryInfo &(Function &F)> GetTLI, CallGraph & CG) static
Definition at line 971 of file GlobalsModRef.cpp.
References llvm::Module::getDataLayout().
Referenced by llvm::GlobalsAA::run(), and llvm::GlobalsAAWrapperPass::runOnModule().
getModRefBehavior() [1/2]
FunctionModRefBehavior GlobalsAAResult::getModRefBehavior (const Function * F)
getModRefBehavior - Return the behavior of the specified function if called from the specified call site.
The call site may be null in which case the most generic behavior of this function should be returned.
Definition at line 244 of file GlobalsModRef.cpp.
References llvm::FMRB_DoesNotAccessMemory, llvm::FMRB_OnlyReadsMemory, llvm::FMRB_UnknownModRefBehavior, llvm::AAResultBase< DerivedT >::getModRefBehavior(), llvm::isModOrRefSet(), and llvm::isModSet().
getModRefBehavior() [2/2]
FunctionModRefBehavior GlobalsAAResult::getModRefBehavior (const CallBase * Call)
getModRefBehavior - Return the behavior of the specified function if called from the specified call site.
The call site may be null in which case the most generic behavior of this function should be returned.
Definition at line 258 of file GlobalsModRef.cpp.
References assert(), C, llvm::SmallPtrSetImplBase::clear(), F(), llvm::FMRB_DoesNotAccessMemory, llvm::FMRB_OnlyReadsMemory, llvm::FMRB_UnknownModRefBehavior, llvm::CallBase::getCalledFunction(), llvm::Module::getDataLayout(), llvm::Function::getFunction(), llvm::GlobalVariable::getInitializer(), llvm::AAResultBase< DerivedT >::getModRefBehavior(), llvm::Operator::getOpcode(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::GetUnderlyingObject(), llvm::GlobalValue::hasLocalLinkage(), llvm::CallBase::hasOperandBundles(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isAllocLikeFn(), llvm::isFreeCall(), llvm::isModOrRefSet(), llvm::isModSet(), llvm::Type::isPointerTy(), llvm::Mod, llvm::Ref, llvm::scc_begin(), SI, llvm::Value::users(), and llvm::Value::uses().
getModRefInfo()
ModRefInfo GlobalsAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Definition at line 927 of file GlobalsModRef.cpp.
References llvm::AAResultBase< GlobalsAAResult >::AAResultBase(), function, llvm::CallBase::getCalledFunction(), llvm::AAResultBase< DerivedT >::getModRefInfo(), llvm::GetUnderlyingObject(), llvm::GlobalValue::hasLocalLinkage(), llvm::intersectModRef(), llvm::isModOrRefSet(), llvm::ModRef, llvm::NoModRef, llvm::MemoryLocation::Ptr, and llvm::unionModRef().
The documentation for this class was generated from the following files:
include/llvm/Analysis/GlobalsModRef.h
lib/Analysis/GlobalsModRef.cpp