LLVM: llvm::codeview::VirtualBaseClassRecord Class Reference
llvm::codeview::VirtualBaseClassRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
VirtualBaseClassRecord ()=default
VirtualBaseClassRecord (TypeRecordKind Kind)
VirtualBaseClassRecord (TypeRecordKind Kind, MemberAttributes Attrs, TypeIndex BaseType, TypeIndex VBPtrType, uint64_t Offset, uint64_t Index)
VirtualBaseClassRecord (TypeRecordKind Kind, MemberAccess Access, TypeIndex BaseType, TypeIndex VBPtrType, uint64_t Offset, uint64_t Index)
MemberAccess getAccess () const
TypeIndex getBaseType () const
TypeIndex getVBPtrType () const
uint64_t getVBPtrOffset () const
uint64_t getVTableIndex () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
MemberAttributes Attrs
TypeIndex BaseType
TypeIndex VBPtrType
uint64_t VBPtrOffset = 0
uint64_t VTableIndex = 0
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 890 of file TypeRecord.h.
Constructor & Destructor Documentation
VirtualBaseClassRecord() [1/4]
llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord () default
VirtualBaseClassRecord() [2/4]
llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord (TypeRecordKind Kind) inline explicit
Definition at line 893 of file TypeRecord.h.
VirtualBaseClassRecord() [3/4]
llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord (TypeRecordKind Kind, MemberAttributes Attrs, TypeIndex BaseType, TypeIndex VBPtrType, uint64_t Offset, uint64_t Index) inline
Definition at line 894 of file TypeRecord.h.
VirtualBaseClassRecord() [4/4]
llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord (TypeRecordKind Kind, MemberAccess Access, TypeIndex BaseType, TypeIndex VBPtrType, uint64_t Offset, uint64_t Index) inline
Definition at line 899 of file TypeRecord.h.
Member Function Documentation
getAccess()
MemberAccess llvm::codeview::VirtualBaseClassRecord::getAccess () const inline
Definition at line 905 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
getBaseType()
TypeIndex llvm::codeview::VirtualBaseClassRecord::getBaseType () const inline
Definition at line 906 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getVBPtrOffset()
uint64_t llvm::codeview::VirtualBaseClassRecord::getVBPtrOffset () const inline
Definition at line 908 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getVBPtrType()
TypeIndex llvm::codeview::VirtualBaseClassRecord::getVBPtrType () const inline
Definition at line 907 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getVTableIndex()
uint64_t llvm::codeview::VirtualBaseClassRecord::getVTableIndex () const inline
Definition at line 909 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
Member Data Documentation
Attrs
MemberAttributes llvm::codeview::VirtualBaseClassRecord::Attrs
Definition at line 911 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
BaseType
TypeIndex llvm::codeview::VirtualBaseClassRecord::BaseType
Definition at line 912 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
VBPtrOffset
uint64_t llvm::codeview::VirtualBaseClassRecord::VBPtrOffset = 0
Definition at line 914 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
VBPtrType
TypeIndex llvm::codeview::VirtualBaseClassRecord::VBPtrType
Definition at line 913 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
VTableIndex
uint64_t llvm::codeview::VirtualBaseClassRecord::VTableIndex = 0
Definition at line 915 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h