LLVM: llvm::Timer Class Reference
llvm::Timer Class Reference
This class is used to track the amount of time spent between invocations of its startTimer()/stopTimer() methods.
#include "llvm/Support/Timer.h"
Public Member Functions
Timer (StringRef TimerName, StringRef TimerDescription)
Timer (StringRef TimerName, StringRef TimerDescription, TimerGroup &tg)
Timer (const Timer &RHS)
const Timer & operator= (const Timer &T)
~Timer ()
Timer ()
Create an uninitialized timer, client must use 'init'.
void init (StringRef TimerName, StringRef TimerDescription)
void init (StringRef TimerName, StringRef TimerDescription, TimerGroup &tg)
const std::string & getName () const
const std::string & getDescription () const
bool isInitialized () const
bool isRunning () const
Check if the timer is currently running.
bool hasTriggered () const
Check if startTimer() has ever been called on this timer.
void startTimer ()
Start the timer running.
void stopTimer ()
Stop the timer.
void clear ()
Clear the timer state.
TimeRecord getTotalTime () const
Return the duration for which this timer has been running.
Friends
class TimerGroup
Detailed Description
This class is used to track the amount of time spent between invocations of its startTimer()/stopTimer() methods.
Given appropriate OS support it can also keep track of the RSS of the program at various points. By default, the Timer will print the amount of time it has captured to standard error when the last timer is destroyed, otherwise it is printed when its TimerGroup is destroyed. Timers do not print their information if they are never started.
Definition at line 76 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/4]
llvm::Timer::Timer (StringRef TimerName, StringRef TimerDescription) inline explicit
Definition at line 88 of file Timer.h.
References llvm::cl::init().
Timer() [2/4]
llvm::Timer::Timer (StringRef TimerName, StringRef TimerDescription, TimerGroup & tg) inline
Definition at line 91 of file Timer.h.
References llvm::cl::init().
Timer() [3/4]
llvm::Timer::Timer (const Timer & RHS) inline
Definition at line 94 of file Timer.h.
References assert().
~Timer()
Timer::~Timer ()
Definition at line 108 of file Timer.cpp.
Timer() [4/4]
llvm::Timer::Timer () inline explicit
Create an uninitialized timer, client must use 'init'.
Definition at line 104 of file Timer.h.
References llvm::cl::init().
Member Function Documentation
clear()
void Timer::clear ()
Clear the timer state.
Definition at line 153 of file Timer.cpp.
Referenced by llvm::TimerGroup::clear(), and llvm::TimerGroup::~TimerGroup().
getDescription()
const std::string& llvm::Timer::getDescription () const inline
Definition at line 109 of file Timer.h.
getName()
const std::string& llvm::Timer::getName () const inline
Definition at line 108 of file Timer.h.
References Name.
getTotalTime()
TimeRecord llvm::Timer::getTotalTime () const inline
Return the duration for which this timer has been running.
Definition at line 130 of file Timer.h.
hasTriggered()
bool llvm::Timer::hasTriggered () const inline
Check if startTimer() has ever been called on this timer.
Definition at line 116 of file Timer.h.
References clear().
Referenced by llvm::TimePassesHandler::print(), and llvm::TimerGroup::~TimerGroup().
init() [1/2]
void Timer::init (StringRef TimerName, StringRef TimerDescription)
Definition at line 94 of file Timer.cpp.
References getDefaultTimerGroup(), and llvm::cl::init().
Referenced by llvm::TimeRecord::print().
init() [2/2]
void Timer::init (StringRef TimerName, StringRef TimerDescription, TimerGroup & tg)
Definition at line 98 of file Timer.cpp.
References assert(), llvm::StringRef::begin(), llvm::StringRef::end(), and Name.
isInitialized()
bool llvm::Timer::isInitialized () const inline
Definition at line 110 of file Timer.h.
Referenced by llvm::TimeRecord::print().
isRunning()
bool llvm::Timer::isRunning () const inline
Check if the timer is currently running.
Definition at line 113 of file Timer.h.
Referenced by llvm::TimePassesHandler::print(), and llvm::TimerGroup::~TimerGroup().
operator=()
const Timer& llvm::Timer::operator= (const Timer & T) inline
Definition at line 97 of file Timer.h.
References assert().
startTimer()
void Timer::startTimer ()
Start the timer running.
Time between calls to startTimer/stopTimer is counted by the Timer class. Note that these calls must be correctly paired.
Definition at line 138 of file Timer.cpp.
References assert(), llvm::TimeRecord::getCurrentTime(), and llvm::SignpostEmitter::startTimerInterval().
Referenced by llvm::TimePassesHandler::print(), llvm::TimeRegion::TimeRegion(), and llvm::TimerGroup::~TimerGroup().
stopTimer()
void Timer::stopTimer ()
Stop the timer.
Definition at line 145 of file Timer.cpp.
References assert(), llvm::SignpostEmitter::endTimerInterval(), and llvm::TimeRecord::getCurrentTime().
Referenced by llvm::TimeRegion::~TimeRegion(), and llvm::TimerGroup::~TimerGroup().
Friends And Related Function Documentation
TimerGroup
friend class TimerGroup friend
Definition at line 133 of file Timer.h.
The documentation for this class was generated from the following files:
include/llvm/Support/Timer.h
lib/Support/Timer.cpp