LLVM: llvm::CallInfo Class Reference
llvm::CallInfo Class Reference
Public Member Functions
void insert (CallInst *Call, GVN::ValueTable &VN)
const VNtoInsns & getScalarVNTable () const
const VNtoInsns & getLoadVNTable () const
const VNtoInsns & getStoreVNTable () const
Detailed Description
Definition at line 217 of file GVNHoist.cpp.
Member Function Documentation
getLoadVNTable()
const VNtoInsns& llvm::CallInfo::getLoadVNTable () const inline
Definition at line 240 of file GVNHoist.cpp.
getScalarVNTable()
const VNtoInsns& llvm::CallInfo::getScalarVNTable () const inline
Definition at line 239 of file GVNHoist.cpp.
getStoreVNTable()
const VNtoInsns& llvm::CallInfo::getStoreVNTable () const inline
Definition at line 241 of file GVNHoist.cpp.
insert()
void llvm::CallInfo::insert (CallInst * Call, GVN::ValueTable & VN) inline
Definition at line 224 of file GVNHoist.cpp.
References llvm::CallBase::doesNotAccessMemory(), llvm::InvalidVN, llvm::GVN::ValueTable::lookupOrAdd(), and llvm::CallBase::onlyReadsMemory().
The documentation for this class was generated from the following file:
lib/Transforms/Scalar/GVNHoist.cpp