LLVM: llvm::SubsumingPositionIterator Class Reference
llvm::SubsumingPositionIterator Class Reference
A visitor class for IR positions.
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
SubsumingPositionIterator (const IRPosition &IRP)
iterator begin ()
iterator end ()
Detailed Description
A visitor class for IR positions.
Given a position P, the SubsumingPositionIterator allows to visit "subsuming positions" wrt. attributes/information. Thus, if a piece of information holds for a subsuming position, it also holds for the position P.
The subsuming positions always include the initial position and then, depending on the position kind, additionally the following ones:
for IRP_RETURNED:
the function (IRP_FUNCTION)
for IRP_ARGUMENT:
the function (IRP_FUNCTION)
for IRP_CALL_SITE:
the callee (IRP_FUNCTION), if known
for IRP_CALL_SITE_RETURNED:
the callee (IRP_RETURNED), if known
the call site (IRP_FUNCTION)
the callee (IRP_FUNCTION), if known
for IRP_CALL_SITE_ARGUMENT:
the argument of the callee (IRP_ARGUMENT), if known
the callee (IRP_FUNCTION), if known
the position the call site argument is associated with if it is not anchored to the call site, e.g., if it is an argument then the argument (IRP_ARGUMENT)
Definition at line 516 of file Attributor.h.
Constructor & Destructor Documentation
SubsumingPositionIterator()
SubsumingPositionIterator::SubsumingPositionIterator (const IRPosition & IRP)
Definition at line 483 of file Attributor.cpp.
References llvm::Function::arg_size(), llvm::IRPosition::argument(), assert(), Callee, llvm::IRPosition::callsite_function(), llvm::IRPosition::function(), llvm::IRPosition::getAnchorValue(), llvm::Function::getArg(), llvm::IRPosition::getArgNo(), llvm::IRPosition::getAssociatedFunction(), llvm::IRPosition::getAssociatedValue(), llvm::IRPosition::getPositionKind(), llvm::IRPosition::IRP_ARGUMENT, llvm::IRPosition::IRP_CALL_SITE, llvm::IRPosition::IRP_CALL_SITE_ARGUMENT, llvm::IRPosition::IRP_CALL_SITE_RETURNED, llvm::IRPosition::IRP_FLOAT, llvm::IRPosition::IRP_FUNCTION, llvm::IRPosition::IRP_INVALID, llvm::IRPosition::IRP_RETURNED, llvm::IRPosition::returned(), and llvm::IRPosition::value().
Member Function Documentation
begin()
iterator llvm::SubsumingPositionIterator::begin () inline
Definition at line 522 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T >::begin().
end()
iterator llvm::SubsumingPositionIterator::end () inline
Definition at line 523 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T >::end().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/Attributor.cpp