LLVM: llvm::jitlink::Section Class Reference
llvm::jitlink::Section Class Reference
Represents an object file section.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Types
using symbol_iterator = SymbolSet::iterator
using const_symbol_iterator = SymbolSet::const_iterator
using block_iterator = BlockSet::iterator
using const_block_iterator = BlockSet::const_iterator
Public Member Functions
~Section ()
StringRef getName () const
Returns the name of this section.
sys::Memory::ProtectionFlags getProtectionFlags () const
Returns the protection flags for this section.
SectionOrdinal getOrdinal () const
Returns the ordinal for this section.
iterator_range< block_iterator > blocks ()
Returns an iterator over the blocks defined in this section.
iterator_range< const_block_iterator > blocks () const
Returns an iterator over the blocks defined in this section.
iterator_range< symbol_iterator > symbols ()
Returns an iterator over the symbols defined in this section.
iterator_range< const_symbol_iterator > symbols () const
Returns an iterator over the symbols defined in this section.
SymbolSet::size_type symbols_size ()
Return the number of symbols in this section.
Friends
class LinkGraph
Detailed Description
Represents an object file section.
Definition at line 532 of file JITLink.h.
Member Typedef Documentation
block_iterator
using llvm::jitlink::Section::block_iterator = BlockSet::iterator
Definition at line 547 of file JITLink.h.
const_block_iterator
using llvm::jitlink::Section::const_block_iterator = BlockSet::const_iterator
Definition at line 548 of file JITLink.h.
const_symbol_iterator
using llvm::jitlink::Section::const_symbol_iterator = SymbolSet::const_iterator
Definition at line 545 of file JITLink.h.
symbol_iterator
using llvm::jitlink::Section::symbol_iterator = SymbolSet::iterator
Definition at line 544 of file JITLink.h.
Constructor & Destructor Documentation
~Section()
llvm::jitlink::Section::~Section ()
Definition at line 145 of file JITLink.cpp.
References B.
Member Function Documentation
blocks() [1/2]
iterator_range<block_iterator> llvm::jitlink::Section::blocks () inline
Returns an iterator over the blocks defined in this section.
Definition at line 562 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::jitlink::SectionRange::SectionRange().
blocks() [2/2]
iterator_range<const_block_iterator> llvm::jitlink::Section::blocks () const inline
Returns an iterator over the blocks defined in this section.
Definition at line 567 of file JITLink.h.
References llvm::make_range().
getName()
StringRef llvm::jitlink::Section::getName () const inline
Returns the name of this section.
Definition at line 553 of file JITLink.h.
References Name.
Referenced by llvm::jitlink::LinkGraph::findSectionByName(), and llvm::jitlink::operator<<().
getOrdinal()
SectionOrdinal llvm::jitlink::Section::getOrdinal () const inline
Returns the ordinal for this section.
Definition at line 559 of file JITLink.h.
getProtectionFlags()
sys::Memory::ProtectionFlags llvm::jitlink::Section::getProtectionFlags () const inline
Returns the protection flags for this section.
Definition at line 556 of file JITLink.h.
symbols() [1/2]
iterator_range<symbol_iterator> llvm::jitlink::Section::symbols () inline
Returns an iterator over the symbols defined in this section.
Definition at line 572 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::jitlink::LinkGraph::splitBlock().
symbols() [2/2]
iterator_range<const_symbol_iterator> llvm::jitlink::Section::symbols () const inline
Returns an iterator over the symbols defined in this section.
Definition at line 577 of file JITLink.h.
References llvm::make_range().
symbols_size()
SymbolSet::size_type llvm::jitlink::Section::symbols_size () inline
Return the number of symbols in this section.
Definition at line 582 of file JITLink.h.
References assert(), and Name.
Friends And Related Function Documentation
LinkGraph
friend class LinkGraph friend
Definition at line 533 of file JITLink.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLink.h
lib/ExecutionEngine/JITLink/JITLink.cpp