LLVM: llvm::PrettyStackTraceEntry Class Reference
llvm::PrettyStackTraceEntry Class Reference abstract
PrettyStackTraceEntry - This class is used to represent a frame of the "pretty" stack trace that is dumped when a program crashes.
#include "llvm/Support/PrettyStackTrace.h"
Public Member Functions
PrettyStackTraceEntry ()
virtual ~PrettyStackTraceEntry ()
virtual void print (raw_ostream &OS) const =0
print - Emit information about this stack frame to OS.
const PrettyStackTraceEntry * getNextEntry () const
getNextEntry - Return the next entry in the list of frames.
Friends
PrettyStackTraceEntry * ReverseStackTrace (PrettyStackTraceEntry *)
Detailed Description
PrettyStackTraceEntry - This class is used to represent a frame of the "pretty" stack trace that is dumped when a program crashes.
You can define subclasses of this and declare them on the program stack: when they are constructed and destructed, they will add their symbolic frames to a virtual stack trace. This gets dumped out if the program crashes.
Definition at line 45 of file PrettyStackTrace.h.
Constructor & Destructor Documentation
PrettyStackTraceEntry()
PrettyStackTraceEntry::PrettyStackTraceEntry ()
Definition at line 198 of file PrettyStackTrace.cpp.
References PrettyStackTraceHead, and printForSigInfoIfNeeded().
~PrettyStackTraceEntry()
PrettyStackTraceEntry::~PrettyStackTraceEntry () virtual
Definition at line 208 of file PrettyStackTrace.cpp.
References assert(), PrettyStackTraceHead, and printForSigInfoIfNeeded().
Member Function Documentation
getNextEntry()
const PrettyStackTraceEntry* llvm::PrettyStackTraceEntry::getNextEntry () const inline
getNextEntry - Return the next entry in the list of frames.
Definition at line 59 of file PrettyStackTrace.h.
print()
virtual void llvm::PrettyStackTraceEntry::print (raw_ostream & OS) const pure virtual
print - Emit information about this stack frame to OS.
Implemented in llvm::PassManagerPrettyStackEntry, llvm::PrettyStackTraceProgram, llvm::PrettyStackTraceFormat, and llvm::PrettyStackTraceString.
Referenced by llvm::PrettyStackTraceProgram::PrettyStackTraceProgram(), and llvm::PrettyStackTraceString::PrettyStackTraceString().
Friends And Related Function Documentation
ReverseStackTrace
PrettyStackTraceEntry* ReverseStackTrace (PrettyStackTraceEntry * Head) friend
Definition at line 63 of file PrettyStackTrace.cpp.
The documentation for this class was generated from the following files:
include/llvm/Support/PrettyStackTrace.h
lib/Support/PrettyStackTrace.cpp