LLVM: llvm::StringMapEntry< ValueTy > Class Template Reference
llvm::StringMapEntry< ValueTy > Class Template Reference final
StringMapEntry - This is used to represent one value that is inserted into a StringMap.
#include "llvm/ADT/StringMap.h"
Public Member Functions
StringRef getKey () const
const char * getKeyData () const
getKeyData - Return the start of the string data that is the key for this value.
StringRef first () const
template<typename AllocatorTy >
void Destroy (AllocatorTy &Allocator)
Destroy - Destroy this StringMapEntry, releasing memory back to the specified allocator.
void Destroy ()
Destroy this object, releasing memory back to the malloc allocator.
Public Member Functions inherited from llvm::StringMapEntryStorage< ValueTy >
StringMapEntryStorage (size_t strLen)
template<typename... InitTy>
StringMapEntryStorage (size_t strLen, InitTy &&... InitVals)
StringMapEntryStorage (StringMapEntryStorage &E)=delete
const ValueTy & getValue () const
ValueTy & getValue ()
void setValue (const ValueTy &V)
Public Member Functions inherited from llvm::StringMapEntryBase
StringMapEntryBase (size_t Len)
size_t getKeyLength () const
Static Public Member Functions
template<typename AllocatorTy , typename... InitTy>
static StringMapEntry * Create (StringRef Key, AllocatorTy &Allocator, InitTy &&... InitVals)
Create a StringMapEntry for the specified key construct the value using InitiVals.
template<typename... InitType>
static StringMapEntry * Create (StringRef Key, InitType &&... InitVal)
Create - Create a StringMapEntry with normal malloc/free.
static StringMapEntry * Create (StringRef Key)
static StringMapEntry & GetStringMapEntryFromKeyData (const char *KeyData)
GetStringMapEntryFromKeyData - Given key data that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Additional Inherited Members
Public Attributes inherited from llvm::StringMapEntryStorage< ValueTy >
ValueTy second
Detailed Description
template<typename ValueTy>
class llvm::StringMapEntry< ValueTy >
StringMapEntry - This is used to represent one value that is inserted into a StringMap.
It contains the Value itself and the key: the string length and data.
Definition at line 158 of file StringMap.h.
Member Function Documentation
Create() [1/3]
template<typename ValueTy> template<typename AllocatorTy , typename... InitTy> static StringMapEntry* llvm::StringMapEntry< ValueTy >::Create (StringRef Key, AllocatorTy & Allocator, InitTy &&... InitVals) inline static
Create a StringMapEntry for the specified key construct the value using InitiVals.
Definition at line 178 of file StringMap.h.
Referenced by llvm::Value::getName(), and llvm::StringPool::intern().
Create() [2/3]
template<typename ValueTy> template<typename... InitType> static StringMapEntry* llvm::StringMapEntry< ValueTy >::Create (StringRef Key, InitType &&... InitVal) inline static
Create - Create a StringMapEntry with normal malloc/free.
Definition at line 204 of file StringMap.h.
Create() [3/3]
template<typename ValueTy> static StringMapEntry* llvm::StringMapEntry< ValueTy >::Create (StringRef Key) inline static
Definition at line 209 of file StringMap.h.
Destroy() [1/2]
template<typename ValueTy> template<typename AllocatorTy > void llvm::StringMapEntry< ValueTy >::Destroy (AllocatorTy & Allocator) inline
Destroy - Destroy this StringMapEntry, releasing memory back to the specified allocator.
Definition at line 223 of file StringMap.h.
Referenced by llvm::PooledStringPtr::clear(), llvm::Value::deleteValue(), llvm::StringMap< uint64_t >::erase(), and llvm::ValueSymbolTable::~ValueSymbolTable().
Destroy() [2/2]
template<typename ValueTy> void llvm::StringMapEntry< ValueTy >::Destroy () inline
Destroy this object, releasing memory back to the malloc allocator.
Definition at line 231 of file StringMap.h.
first()
template<typename ValueTy> StringRef llvm::StringMapEntry< ValueTy >::first () const inline
Definition at line 171 of file StringMap.h.
getKey()
template<typename ValueTy> StringRef llvm::StringMapEntry< ValueTy >::getKey () const inline
Definition at line 162 of file StringMap.h.
Referenced by llvm::StringMap< uint64_t >::count(), getFilename(), llvm::Value::getName(), llvm::StringSet< AllocatorTy >::insert(), and llvm::StringMap< uint64_t >::insert().
getKeyData()
template<typename ValueTy> const char* llvm::StringMapEntry< ValueTy >::getKeyData () const inline
getKeyData - Return the start of the string data that is the key for this value.
The string data is always stored immediately after the StringMapEntry object.
Definition at line 169 of file StringMap.h.
Referenced by llvm::PooledStringPtr::begin(), llvm::StringMapEntry< llvm::Comdat >::Create(), llvm::PooledStringPtr::end(), and llvm::TargetIntrinsicInfo::getIntrinsicID().
GetStringMapEntryFromKeyData()
template<typename ValueTy> static StringMapEntry& llvm::StringMapEntry< ValueTy >::GetStringMapEntryFromKeyData (const char * KeyData) inline static
GetStringMapEntryFromKeyData - Given key data that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Definition at line 215 of file StringMap.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/StringMap.h