LLVM: llvm::BTFKindDataSec Class Reference
llvm::BTFKindDataSec Class Reference
Handle data sections.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFKindDataSec (AsmPrinter *AsmPrt, std::string SecName)
uint32_t getSize ()
Get the size of this BTF type entry.
void addVar (uint32_t Id, const MCSymbol *Sym, uint32_t Size)
std::string getName ()
void completeType (BTFDebug &BDebug)
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
void emitType (MCStreamer &OS)
Emit types for this BTF type entry.
Public Member Functions inherited from llvm::BTFTypeBase
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
Additional Inherited Members
Protected Attributes inherited from llvm::BTFTypeBase
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
Handle data sections.
Definition at line 174 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFKindDataSec()
BTFKindDataSec::BTFKindDataSec (AsmPrinter * AsmPrt, std::string SecName)
Definition at line 346 of file BTFDebug.cpp.
References llvm::BTFTypeBase::BTFType, llvm::BTF::CommonType::Info, llvm::BTFTypeBase::Kind, and llvm::BTF::CommonType::Size.
Member Function Documentation
addVar()
void llvm::BTFKindDataSec::addVar (uint32_t Id, const MCSymbol * Sym, uint32_t Size) inline
Definition at line 184 of file BTFDebug.h.
completeType()
void BTFKindDataSec::completeType (BTFDebug & BDebug) virtual
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
Reimplemented from llvm::BTFTypeBase.
Definition at line 353 of file BTFDebug.cpp.
References llvm::BTFDebug::addString(), llvm::BTFTypeBase::BTFType, llvm::BTF::CommonType::Info, Name, and llvm::BTF::CommonType::NameOff.
emitType()
void BTFKindDataSec::emitType (MCStreamer & OS) virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented from llvm::BTFTypeBase.
Definition at line 358 of file BTFDebug.cpp.
References llvm::HexStyle::Asm, llvm::MCStreamer::EmitIntValue(), and llvm::BTFTypeBase::emitType().
getName()
std::string llvm::BTFKindDataSec::getName () inline
Definition at line 187 of file BTFDebug.h.
References llvm::BTFTypeBase::completeType(), llvm::BTFTypeBase::emitType(), and Name.
getSize()
uint32_t llvm::BTFKindDataSec::getSize () inline virtual
Get the size of this BTF type entry.
Reimplemented from llvm::BTFTypeBase.
Definition at line 181 of file BTFDebug.h.
References llvm::BTF::BTFDataSecVarSize, and llvm::BTFTypeBase::getSize().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp