LLVM: llvm::MachO::TextAPIWriter Class Reference
llvm::MachO::TextAPIWriter Class Reference
#include "llvm/TextAPI/MachO/TextAPIWriter.h"
Public Member Functions
TextAPIWriter ()=delete
Static Public Member Functions
static Error writeToStream (raw_ostream &os, const InterfaceFile &)
Detailed Description
Definition at line 19 of file TextAPIWriter.h.
Constructor & Destructor Documentation
TextAPIWriter()
llvm::MachO::TextAPIWriter::TextAPIWriter () delete
Member Function Documentation
writeToStream()
Error llvm::MachO::TextAPIWriter::writeToStream (raw_ostream & os, const InterfaceFile & File) static
Definition at line 1128 of file TextStub.cpp.
References llvm::MachO::TextAPIContext::FileKind, llvm::MachO::InterfaceFile::getFileType(), llvm::MachO::InterfaceFile::getPath(), llvm::MachO::TextAPIContext::Path, and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/MachO/TextAPIWriter.h
lib/TextAPI/MachO/TextStub.cpp