LLVM: llvm::DivergenceAnalysis Class Reference
llvm::DivergenceAnalysis Class Reference
Generic divergence analysis for reducible CFGs.
#include "llvm/Analysis/DivergenceAnalysis.h"
Public Member Functions
DivergenceAnalysis (const Function &F, const Loop *RegionLoop, const DominatorTree &DT, const LoopInfo &LI, SyncDependenceAnalysis &SDA, bool IsLCSSAForm)
This instance will analyze the whole function F or the loop RegionLoop.
const Loop * getRegionLoop () const
The loop that defines the analyzed region (if any).
const Function & getFunction () const
bool inRegion (const BasicBlock &BB) const
Whether BB is part of the region.
bool inRegion (const Instruction &I) const
Whether I is part of the region.
void addUniformOverride (const Value &UniVal)
Mark UniVal as a value that is always uniform.
void markDivergent (const Value &DivVal)
Mark DivVal as a value that is always divergent.
void compute ()
Propagate divergence to all instructions in the region.
bool hasDetectedDivergence () const
Whether any value was marked or analyzed to be divergent.
bool isAlwaysUniform (const Value &Val) const
Whether Val will always return a uniform value regardless of its operands.
bool isDivergent (const Value &Val) const
Whether Val is divergent at its definition.
bool isDivergentUse (const Use &U) const
Whether U is divergent. Uses of a uniform value can be divergent.
void print (raw_ostream &OS, const Module *) const
Detailed Description
Generic divergence analysis for reducible CFGs.
This analysis propagates divergence in a data-parallel context from sources of divergence to all users. It requires reducible CFGs. All assignments should be in SSA form.
Definition at line 37 of file DivergenceAnalysis.h.
Constructor & Destructor Documentation
DivergenceAnalysis()
DivergenceAnalysis::DivergenceAnalysis (const Function & F, const Loop * RegionLoop, const DominatorTree & DT, const LoopInfo & LI, SyncDependenceAnalysis & SDA, bool IsLCSSAForm)
This instance will analyze the whole function F or the loop RegionLoop.
Parameters
RegionLoop if non-null the analysis is restricted to RegionLoop. Otherwise the whole function is analyzed.
IsLCSSAForm whether the analysis may assume that the IR in the region in in LCSSA form.
Definition at line 94 of file DivergenceAnalysis.cpp.
Member Function Documentation
addUniformOverride()
void DivergenceAnalysis::addUniformOverride (const Value & UniVal)
Mark UniVal as a value that is always uniform.
Definition at line 106 of file DivergenceAnalysis.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dyn_cast(), llvm::PHINode::getIncomingValue(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getNumSuccessors(), llvm::Instruction::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::PHINode::hasConstantOrUndefValue(), I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), isDivergent(), llvm_unreachable, and llvm::User::operands().
Referenced by getFunction(), and llvm::GPUDivergenceAnalysis::GPUDivergenceAnalysis().
compute()
void DivergenceAnalysis::compute ()
Propagate divergence to all instructions in the region.
Divergence is seeded by calls to markDivergent.
Definition at line 363 of file DivergenceAnalysis.cpp.
References llvm::dyn_cast(), I, isAlwaysUniform(), isDivergent(), llvm::Instruction::isTerminator(), and markDivergent().
Referenced by getFunction(), and llvm::GPUDivergenceAnalysis::GPUDivergenceAnalysis().
getFunction()
const Function& llvm::DivergenceAnalysis::getFunction () const inline
Definition at line 52 of file DivergenceAnalysis.h.
References addUniformOverride(), compute(), I, inRegion(), and markDivergent().
Referenced by llvm::GPUDivergenceAnalysis::getFunction(), and llvm::GPUDivergenceAnalysis::print().
getRegionLoop()
const Loop* llvm::DivergenceAnalysis::getRegionLoop () const inline
The loop that defines the analyzed region (if any).
Definition at line 51 of file DivergenceAnalysis.h.
hasDetectedDivergence()
bool llvm::DivergenceAnalysis::hasDetectedDivergence () const inline
Whether any value was marked or analyzed to be divergent.
Definition at line 70 of file DivergenceAnalysis.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), isAlwaysUniform(), isDivergent(), isDivergentUse(), and print().
Referenced by llvm::GPUDivergenceAnalysis::hasDivergence().
inRegion() [1/2]
bool DivergenceAnalysis::inRegion (const BasicBlock & BB) const
Whether BB is part of the region.
Definition at line 183 of file DivergenceAnalysis.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Value::getName(), llvm::Loop::getName(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), isAlwaysUniform(), isDivergent(), llvm::SyncDependenceAnalysis::join_blocks(), LLVM_DEBUG, markDivergent(), llvm::User::operands(), llvm::BasicBlock::phis(), llvm::successors(), and llvm::Value::users().
Referenced by getFunction(), and inRegion().
inRegion() [2/2]
bool DivergenceAnalysis::inRegion (const Instruction & I) const
Whether I is part of the region.
Definition at line 179 of file DivergenceAnalysis.cpp.
References llvm::Instruction::getParent(), and inRegion().
isAlwaysUniform()
bool DivergenceAnalysis::isAlwaysUniform (const Value & Val) const
Whether Val will always return a uniform value regardless of its operands.
Definition at line 407 of file DivergenceAnalysis.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::find().
Referenced by compute(), hasDetectedDivergence(), inRegion(), and markDivergent().
isDivergent()
bool DivergenceAnalysis::isDivergent (const Value & Val) const
Whether Val is divergent at its definition.
Definition at line 411 of file DivergenceAnalysis.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::find().
Referenced by addUniformOverride(), compute(), llvm::GPUDivergenceAnalysis::getFunction(), hasDetectedDivergence(), inRegion(), llvm::GPUDivergenceAnalysis::isDivergent(), isDivergentUse(), llvm::GPUDivergenceAnalysis::isUniform(), and print().
isDivergentUse()
bool DivergenceAnalysis::isDivergentUse (const Use & U) const
Whether U is divergent. Uses of a uniform value can be divergent.
Definition at line 415 of file DivergenceAnalysis.cpp.
References llvm::Use::get(), llvm::Instruction::getParent(), llvm::Use::getUser(), and isDivergent().
Referenced by llvm::GPUDivergenceAnalysis::getFunction(), hasDetectedDivergence(), llvm::GPUDivergenceAnalysis::isDivergentUse(), and llvm::GPUDivergenceAnalysis::isUniformUse().
markDivergent()
void DivergenceAnalysis::markDivergent (const Value & DivVal)
Mark DivVal as a value that is always divergent.
Definition at line 100 of file DivergenceAnalysis.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and isAlwaysUniform().
Referenced by compute(), getFunction(), llvm::GPUDivergenceAnalysis::GPUDivergenceAnalysis(), and inRegion().
print()
void DivergenceAnalysis::print (raw_ostream & OS, const Module *) const
Definition at line 421 of file DivergenceAnalysis.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), llvm::instructions(), and isDivergent().
Referenced by hasDetectedDivergence(), llvm::GPUDivergenceAnalysis::isUniformUse(), and llvm::GPUDivergenceAnalysis::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DivergenceAnalysis.h
lib/Analysis/DivergenceAnalysis.cpp