LLVM: llvm::X86TTIImpl Class Reference
llvm::X86TTIImpl Class Reference
#include "Target/X86/X86TargetTransformInfo.h"
Public Member Functions
X86TTIImpl (const X86TargetMachine *TM, const Function &F)
Scalar TTI Implementations
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
Cache TTI Implementation
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
Public Member Functions inherited from llvm::BasicTTIImplBase< X86TTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast) const
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
bool shouldBuildLookupTables ()
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI)
int getInstructionLatency (const Instruction *I)
virtual unsigned getCacheLineSize () const
virtual unsigned getPrefetchDistance () const
virtual unsigned getMinPrefetchStride () const
virtual unsigned getMaxPrefetchIterationsAhead () const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
Estimate the overhead of scalarizing an instruction.
unsigned getScalarizationOverhead (Type *VecTy, ArrayRef< const Value * > Args)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
Estimate the overhead of scalarizing an instructions unique non-constant operands.
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >(), const Instruction *CxtI=nullptr)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF=1)
Get intrinsic cost based on arguments.
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=std::numeric_limits< unsigned >::max())
Get intrinsic cost based on argument types.
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned Opcode, Type *Ty, bool IsPairwise)
Try to calculate arithmetic and shuffle op costs for reduction operations.
unsigned getMinMaxReductionCost (Type *Ty, Type *CondTy, bool IsPairwise, bool)
Try to calculate op costs for min/max reduction operations.
unsigned getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< X86TTIImpl >
unsigned getCallCost (const Function *F, int NumArgs, const User *U)
unsigned getCallCost (const Function *F, ArrayRef< const Value * > Arguments, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getUserCost (const User *U, ArrayRef< const Value * > Operands)
int getInstructionLatency (const Instruction *I)
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value *> Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
unsigned getMemcpyCost (const Instruction *I)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &)
bool isLegalAddImmediate (int64_t Imm)
bool isLegalICmpImmediate (int64_t Imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2)
bool canMacroFuseCmp ()
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo)
bool shouldFavorPostInc () const
bool shouldFavorBackedgeIndex (const Loop *L) const
bool isLegalMaskedStore (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedLoad (Type *DataType, MaybeAlign Alignment)
bool isLegalNTStore (Type *DataType, Align Alignment)
bool isLegalNTLoad (Type *DataType, Align Alignment)
bool isLegalMaskedScatter (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedGather (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedCompressStore (Type *DataType)
bool isLegalMaskedExpandLoad (Type *DataType)
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace)
bool prefersVectorizedAddressing ()
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool LSRWithInstrQueries ()
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA ()
bool isTypeLegal (Type *Ty)
bool shouldBuildLookupTables ()
bool shouldBuildLookupTablesForConstant (Constant *C)
bool useColdCCForColdCall (Function &F)
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value *> Args, unsigned VF)
bool supportsEfficientVectorElementLoadStore ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization ()
bool enableMaskedInterleavedAccessVectorization ()
bool isFPVectorizationPotentiallyUnsafe ()
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast)
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit)
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
int getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth ()
bool shouldMaximizeVectorBandwidth (bool OptSize) const
unsigned getMinimumVF (unsigned ElemWidth) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader)
unsigned getCacheLineSize () const
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride () const
unsigned getMaxPrefetchIterationsAhead () const
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value *> Args, const Instruction *CxtI=nullptr)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Ty, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction *I)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type *> Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value *> Args, FastMathFlags FMF, unsigned VF)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type *> Tys)
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned, Type *, bool)
unsigned getMinMaxReductionCost (Type *, Type *, bool, bool)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type *> Tys)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type *> &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument *> &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool useReductionIntrinsic (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
Vector TTI Implementations
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getLoadStoreVecRegBitWidth (unsigned AS) const
unsigned getMaxInterleaveFactor (unsigned VF)
int getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value *> Args=ArrayRef< const Value *>(), const Instruction *CxtI=nullptr)
int getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
int getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
int getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I=nullptr)
int getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
int getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
int getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
int getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
Calculate the cost of Gather / Scatter operation.
int getAddressComputationCost (Type *PtrTy, ScalarEvolution *SE, const SCEV *Ptr)
unsigned getAtomicMemIntrinsicMaxElementSize () const
int getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type *> Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=UINT_MAX)
int getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Value *> Args, FastMathFlags FMF, unsigned VF=1)
int getArithmeticReductionCost (unsigned Opcode, Type *Ty, bool IsPairwiseForm)
int getMinMaxReductionCost (Type *Ty, Type *CondTy, bool IsPairwiseForm, bool IsUnsigned)
int getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
int getInterleavedMemoryOpCostAVX512 (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
int getInterleavedMemoryOpCostAVX2 (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
int getIntImmCost (int64_t)
Calculate the cost of materializing a 64-bit value.
int getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getUserCost (const User *U, ArrayRef< const Value *> Operands)
int getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
int getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
bool isLSRCostLess (TargetTransformInfo::LSRCost &C1, TargetTransformInfo::LSRCost &C2)
bool canMacroFuseCmp ()
bool isLegalMaskedLoad (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedStore (Type *DataType, MaybeAlign Alignment)
bool isLegalNTLoad (Type *DataType, Align Alignment)
bool isLegalNTStore (Type *DataType, Align Alignment)
bool isLegalMaskedGather (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedScatter (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedExpandLoad (Type *DataType)
bool isLegalMaskedCompressStore (Type *DataType)
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument *> &Args) const
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization ()
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< X86TTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
virtual ~BasicTTIImplBase ()=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< X86TTIImpl >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned)
bool isStridedAccess (const SCEV *Ptr)
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr)
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance)
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 27 of file X86TargetTransformInfo.h.
Constructor & Destructor Documentation
X86TTIImpl()
llvm::X86TTIImpl::X86TTIImpl (const X86TargetMachine * TM, const Function & F) inline explicit
Definition at line 97 of file X86TargetTransformInfo.h.
References areFunctionArgsABICompatible(), areInlineCompatible(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, Callee, canMacroFuseCmp(), enableInterleavedAccessVectorization(), enableMemCmpExpansion(), getAddressComputationCost(), getArithmeticInstrCost(), getArithmeticReductionCost(), getAtomicMemIntrinsicMaxElementSize(), getCacheAssociativity(), getCacheSize(), getCastInstrCost(), getCmpSelInstrCost(), getGatherScatterOpCost(), getInterleavedMemoryOpCost(), getInterleavedMemoryOpCostAVX2(), getInterleavedMemoryOpCostAVX512(), getIntImmCost(), getIntImmCostInst(), getIntImmCostIntrin(), getIntrinsicInstrCost(), getLoadStoreVecRegBitWidth(), getMaskedMemoryOpCost(), getMaxInterleaveFactor(), getMemoryOpCost(), getMinMaxReductionCost(), getNumberOfRegisters(), getPopcntSupport(), getRegisterBitWidth(), getShuffleCost(), getUserCost(), getVectorInstrCost(), hasDivRemOp(), I, isFCmpOrdCheaperThanFCmpZero(), isLegalMaskedCompressStore(), isLegalMaskedExpandLoad(), isLegalMaskedGather(), isLegalMaskedLoad(), isLegalMaskedScatter(), isLegalMaskedStore(), isLegalNTLoad(), isLegalNTStore(), isLSRCostLess(), llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OP_None, Operands, and llvm::Vector.
Member Function Documentation
areFunctionArgsABICompatible()
bool X86TTIImpl::areFunctionArgsABICompatible (const Function * Caller, const Function * Callee, SmallPtrSetImpl< Argument *> & Args) const
Definition at line 3499 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::areFunctionArgsABICompatible(), llvm::TargetMachine::getSubtarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SystemZISD::TM, and llvm::X86Subtarget::useAVX512Regs().
Referenced by X86TTIImpl().
areInlineCompatible()
bool X86TTIImpl::areInlineCompatible (const Function * Caller, const Function * Callee) const
Definition at line 3484 of file X86TargetTransformInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), and llvm::SystemZISD::TM.
Referenced by X86TTIImpl().
canMacroFuseCmp()
bool X86TTIImpl::canMacroFuseCmp ()
Definition at line 3336 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasBranchFusion(), and llvm::X86Subtarget::hasMacroFusion().
Referenced by X86TTIImpl().
enableInterleavedAccessVectorization()
bool X86TTIImpl::enableInterleavedAccessVectorization ()
Definition at line 3539 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::isAtom().
Referenced by X86TTIImpl().
enableMemCmpExpansion()
X86TTIImpl::TTI::MemCmpExpansionOptions X86TTIImpl::enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
Definition at line 3516 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::MemCmpExpansionOptions::AllowOverlappingLoads, llvm::TargetLoweringBase::getMaxExpandSizeMemcmp(), llvm::X86Subtarget::getPreferVectorWidth(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::is64Bit(), llvm::TargetTransformInfo::MemCmpExpansionOptions::LoadSizes, llvm::TargetTransformInfo::MemCmpExpansionOptions::MaxNumLoads, llvm::TargetTransformInfo::MemCmpExpansionOptions::NumLoadsPerBlock, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by X86TTIImpl().
getAddressComputationCost()
int X86TTIImpl::getAddressComputationCost (Type * PtrTy, ScalarEvolution * SE, const SCEV * Ptr)
Definition at line 2536 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::getAddressComputationCost(), llvm::TargetTransformInfoImplBase::getConstantStrideStep(), llvm::TargetTransformInfoImplBase::isStridedAccess(), and llvm::Type::isVectorTy().
Referenced by X86TTIImpl().
getArithmeticInstrCost()
int X86TTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None, ArrayRef< const Value *> Args = ArrayRef<const Value *>(), const Instruction * CxtI = nullptr)
Definition at line 172 of file X86TargetTransformInfo.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FSUB, llvm::BasicTTIImplBase< X86TTIImpl >::getArithmeticInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSE42(), llvm::X86Subtarget::hasXOP(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, if(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::X86Subtarget::isSLM(), llvm::AArch64CC::LT, llvm::max(), llvm::TargetTransformInfoImplBase::minRequiredElementSize(), llvm::ISD::MUL, llvm::TargetTransformInfo::OK_NonUniformConstantValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::TargetTransformInfo::OK_UniformValue, llvm::TargetTransformInfo::OP_None, llvm::TargetTransformInfo::OP_PowerOf2, llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::UDIV, llvm::ISD::UREM, llvm::X86Subtarget::useGLMDivSqrtCosts(), llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by X86TTIImpl().
getArithmeticReductionCost()
int X86TTIImpl::getArithmeticReductionCost (unsigned Opcode, Type * Ty, bool IsPairwiseForm)
Definition at line 2561 of file X86TargetTransformInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::ISD::FADD, llvm::BasicTTIImplBase< X86TTIImpl >::getArithmeticReductionCost(), llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::Type::getVectorElementType(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), if(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Type::isIntegerTy(), llvm::EVT::isSimple(), llvm::X86Subtarget::isSLM(), llvm::AArch64CC::LT, llvm::ISD::OR, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i1, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v64i1, llvm::MVT::v8f32, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i8.
Referenced by X86TTIImpl().
getAtomicMemIntrinsicMaxElementSize()
unsigned X86TTIImpl::getAtomicMemIntrinsicMaxElementSize () const
Definition at line 1884 of file X86TargetTransformInfo.cpp.
Referenced by X86TTIImpl().
getCacheAssociativity()
llvm::Optional< unsigned > X86TTIImpl::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 98 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, LLVM_FALLTHROUGH, and llvm_unreachable.
Referenced by X86TTIImpl().
getCacheSize()
llvm::Optional< unsigned > X86TTIImpl::getCacheSize (TargetTransformInfo::CacheLevel Level) const virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 68 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
Referenced by X86TTIImpl().
getCastInstrCost()
int X86TTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, const Instruction * I = nullptr)
Definition at line 1273 of file X86TargetTransformInfo.cpp.
References assert(), llvm::ConvertCostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::BasicTTIImplBase< X86TTIImpl >::getCastInstrCost(), llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i64, if(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::EVT::isSimple(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::TRUNCATE, llvm::TargetLoweringBase::TypeSplitVector, llvm::ISD::UINT_TO_FP, llvm::MVT::v16f32, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::ISD::ZERO_EXTEND.
Referenced by X86TTIImpl().
getCmpSelInstrCost()
int X86TTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, const Instruction * I = nullptr)
Definition at line 1703 of file X86TargetTransformInfo.cpp.
References assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::MVT::f32, llvm::MVT::f64, llvm::BasicTTIImplBase< X86TTIImpl >::getCmpSelInstrCost(), llvm::MVT::getScalarSizeInBits(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSE42(), llvm::X86Subtarget::hasXOP(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::MVT::is128BitVector(), llvm::X86Subtarget::isSLM(), llvm::MVT::isVector(), llvm::AArch64CC::LT, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by getMaskedMemoryOpCost(), getUserCost(), and X86TTIImpl().
getGatherScatterOpCost()
int X86TTIImpl::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, Value * Ptr, bool VariableMask, unsigned Alignment)
Calculate the cost of Gather / Scatter operation.
Definition at line 3292 of file X86TargetTransformInfo.cpp.
References assert(), llvm::dyn_cast(), llvm::PointerType::getAddressSpace(), llvm::Value::getType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVLX(), isLegalMaskedGather(), isLegalMaskedScatter(), llvm::Type::isVectorTy(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by X86TTIImpl().
getInterleavedMemoryOpCost()
int X86TTIImpl::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 3799 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::getInterleavedMemoryOpCost(), getInterleavedMemoryOpCostAVX2(), getInterleavedMemoryOpCostAVX512(), llvm::Type::getVectorElementType(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by X86TTIImpl().
getInterleavedMemoryOpCostAVX2()
int X86TTIImpl::getInterleavedMemoryOpCostAVX2 (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 3558 of file X86TargetTransformInfo.cpp.
References assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::VectorType::get(), llvm::BasicTTIImplBase< X86TTIImpl >::getInterleavedMemoryOpCost(), getMemoryOpCost(), llvm::EVT::getSimpleVT(), llvm::MVT::getStoreSize(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::DataLayout::getTypeStoreSize(), llvm::TargetLoweringBase::getValueType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::EVT::isSimple(), llvm::MVT::isVector(), llvm::SPII::Load, llvm::ArrayRef< T >::size(), llvm::SPII::Store, llvm::MVT::v16i8, llvm::MVT::v2i8, llvm::MVT::v32i8, llvm::MVT::v4f64, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v8f32, and llvm::MVT::v8i8.
Referenced by getInterleavedMemoryOpCost(), and X86TTIImpl().
getInterleavedMemoryOpCostAVX512()
int X86TTIImpl::getInterleavedMemoryOpCostAVX512 (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 3674 of file X86TargetTransformInfo.cpp.
References assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::VectorType::get(), llvm::BasicTTIImplBase< X86TTIImpl >::getInterleavedMemoryOpCost(), getMemoryOpCost(), llvm::Type::getScalarType(), getShuffleCost(), llvm::MVT::getStoreSize(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::DataLayout::getTypeStoreSize(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::getVT(), llvm::SPII::Load, llvm::max(), llvm::ArrayRef< T >::size(), llvm::TargetTransformInfo::SK_PermuteSingleSrc, llvm::TargetTransformInfo::SK_PermuteTwoSrc, llvm::SPII::Store, llvm::MVT::v16i8, llvm::MVT::v32i8, llvm::MVT::v64i8, and llvm::MVT::v8i8.
Referenced by getInterleavedMemoryOpCost(), and X86TTIImpl().
getIntImmCost() [1/2]
int X86TTIImpl::getIntImmCost (int64_t Val)
Calculate the cost of materializing a 64-bit value.
This helper method might only calculate a fraction of a larger immediate. Therefore it is valid to return a cost of ZERO.
Definition at line 2992 of file X86TargetTransformInfo.cpp.
References llvm::isInt< 32 >(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCost(), getIntImmCostInst(), getIntImmCostIntrin(), and X86TTIImpl().
getIntImmCost() [2/2]
int X86TTIImpl::getIntImmCost (const APInt & Imm, Type * Ty)
Definition at line 3002 of file X86TargetTransformInfo.cpp.
References llvm::alignTo(), llvm::APInt::ashr(), assert(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::Type::isIntegerTy(), llvm::max(), llvm::APInt::sext(), llvm::APInt::sextOrTrunc(), and llvm::TargetTransformInfo::TCC_Free.
getIntImmCostInst()
int X86TTIImpl::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty)
Definition at line 3036 of file X86TargetTransformInfo.cpp.
References llvm::MCID::Add, assert(), llvm::MCID::Call, llvm::divideCeil(), llvm::APInt::getBitWidth(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getZExtValue(), llvm::Type::isIntegerTy(), llvm::isUInt< 32 >(), llvm::SPII::Load, llvm::MipsISD::Ret, llvm::MCID::Select, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by X86TTIImpl().
getIntImmCostIntrin()
int X86TTIImpl::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty)
Definition at line 3133 of file X86TargetTransformInfo.cpp.
References assert(), llvm::APInt::getBitWidth(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), and llvm::TargetTransformInfo::TCC_Free.
Referenced by X86TTIImpl().
getIntrinsicInstrCost() [1/2]
int X86TTIImpl::getIntrinsicInstrCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Type *> Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed = UINT_MAX)
Definition at line 1886 of file X86TargetTransformInfo.cpp.
References llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, llvm::CostTableLookup(), llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::DELETED_NODE, llvm::TargetTransformInfoImplBase::DL, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FSQRT, llvm::Type::getContainedType(), llvm::BasicTTIImplBase< X86TTIImpl >::getIntrinsicInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasCDI(), llvm::X86Subtarget::hasLZCNT(), llvm::X86Subtarget::hasPOPCNT(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE42(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasXOP(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, if(), llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isSLM(), llvm::AArch64CC::LT, llvm::ISD::SADDO, llvm::ISD::SADDSAT, llvm::ISD::SSUBSAT, llvm::ISD::UADDO, llvm::ISD::UADDSAT, llvm::X86Subtarget::useGLMDivSqrtCosts(), llvm::ISD::USUBSAT, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by X86TTIImpl().
getIntrinsicInstrCost() [2/2]
int X86TTIImpl::getIntrinsicInstrCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Value *> Args, FastMathFlags FMF, unsigned VF = 1)
Definition at line 2290 of file X86TargetTransformInfo.cpp.
References llvm::CostTableLookup(), llvm::ISD::DELETED_NODE, llvm::TargetTransformInfoImplBase::DL, llvm::ISD::FSHL, llvm::BasicTTIImplBase< X86TTIImpl >::getIntrinsicInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasXOP(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, if(), llvm::X86Subtarget::is64Bit(), llvm::AArch64CC::LT, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
getLoadStoreVecRegBitWidth()
unsigned X86TTIImpl::getLoadStoreVecRegBitWidth (unsigned AS) const
Definition at line 150 of file X86TargetTransformInfo.cpp.
References getRegisterBitWidth().
Referenced by X86TTIImpl().
getMaskedMemoryOpCost()
int X86TTIImpl::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace)
Definition at line 2480 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::DL, llvm::dyn_cast(), llvm::VectorType::get(), llvm::BasicTTIImplBase< X86TTIImpl >::getCFInstrCost(), getCmpSelInstrCost(), llvm::Type::getContext(), llvm::Type::getInt8Ty(), getMemoryOpCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getScalarizationOverhead(), llvm::Type::getScalarType(), getShuffleCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::X86Subtarget::hasAVX512(), isLegalMaskedLoad(), isLegalMaskedStore(), llvm::isPowerOf2_32(), llvm::SPII::Load, llvm::AArch64CC::LT, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::TargetTransformInfo::SK_PermuteTwoSrc, and llvm::SPII::Store.
Referenced by X86TTIImpl().
getMaxInterleaveFactor()
unsigned X86TTIImpl::getMaxInterleaveFactor (unsigned VF)
Definition at line 154 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasAVX(), and llvm::X86Subtarget::isAtom().
Referenced by X86TTIImpl().
getMemoryOpCost()
int X86TTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction * I = nullptr)
Definition at line 2436 of file X86TargetTransformInfo.cpp.
References assert(), llvm::TargetTransformInfoImplBase::DL, llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getScalarizationOverhead(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::isPowerOf2_32(), llvm::X86Subtarget::isUnalignedMem32Slow(), llvm::SPII::Load, llvm::AArch64CC::LT, and llvm::SPII::Store.
Referenced by getInterleavedMemoryOpCostAVX2(), getInterleavedMemoryOpCostAVX512(), getMaskedMemoryOpCost(), getUserCost(), and X86TTIImpl().
getMinMaxReductionCost()
int X86TTIImpl::getMinMaxReductionCost (Type * Ty, Type * CondTy, bool IsPairwiseForm, bool IsUnsigned)
Definition at line 2759 of file X86TargetTransformInfo.cpp.
References assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::ISD::FMINNUM, llvm::BasicTTIImplBase< X86TTIImpl >::getMinMaxReductionCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSE42(), if(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), llvm::AArch64CC::LT, llvm::ISD::SMIN, llvm::ISD::UMIN, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by X86TTIImpl().
getNumberOfRegisters()
unsigned X86TTIImpl::getNumberOfRegisters (unsigned ClassID) const
Definition at line 119 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::is64Bit(), and llvm::Vector.
Referenced by X86TTIImpl().
getPopcntSupport()
TargetTransformInfo::PopcntSupportKind X86TTIImpl::getPopcntSupport (unsigned TyWidth)
Definition at line 60 of file X86TargetTransformInfo.cpp.
References assert(), llvm::X86Subtarget::hasPOPCNT(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
Referenced by X86TTIImpl().
getRegisterBitWidth()
unsigned X86TTIImpl::getRegisterBitWidth (bool Vector) const
Definition at line 132 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::getPreferVectorWidth(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), and llvm::X86Subtarget::is64Bit().
Referenced by getLoadStoreVecRegBitWidth(), and X86TTIImpl().
getShuffleCost()
int X86TTIImpl::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp)
Definition at line 889 of file X86TargetTransformInfo.cpp.
References llvm::alignDown(), assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::VectorType::get(), llvm::Type::getPrimitiveSizeInBits(), llvm::BasicTTIImplBase< X86TTIImpl >::getShuffleCost(), llvm::MVT::getSizeInBits(), llvm::MVT::getStoreSize(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::DataLayout::getTypeStoreSize(), llvm::Type::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasVBMI(), llvm::X86Subtarget::hasXOP(), llvm::MVT::isVector(), llvm::AArch64CC::LT, llvm::TargetTransformInfo::SK_Broadcast, llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_PermuteSingleSrc, llvm::TargetTransformInfo::SK_PermuteTwoSrc, llvm::TargetTransformInfo::SK_Reverse, llvm::TargetTransformInfo::SK_Select, llvm::TargetTransformInfo::SK_Transpose, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by getInterleavedMemoryOpCostAVX512(), getMaskedMemoryOpCost(), and X86TTIImpl().
getUserCost()
unsigned X86TTIImpl::getUserCost (const User * U, ArrayRef< const Value *> Operands)
Definition at line 3168 of file X86TargetTransformInfo.cpp.
References llvm::all_of(), assert(), llvm::TargetTransformInfoImplBase::DL, llvm::dyn_cast(), GEP, llvm::IntegerType::get(), llvm::VectorType::get(), llvm::BasicTTIImplBase< X86TTIImpl >::getCFInstrCost(), getCmpSelInstrCost(), llvm::Type::getContext(), llvm::X86Subtarget::getGatherOverhead(), llvm::Type::getInt1Ty(), getMemoryOpCost(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::GetElementPtrInst::getPointerOperand(), llvm::DataLayout::getPointerSizeInBits(), llvm::Type::getPrimitiveSizeInBits(), llvm::BasicTTIImplBase< X86TTIImpl >::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::X86Subtarget::getScatterOverhead(), llvm::getSplatValue(), llvm::Value::getType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetTransformInfoImplCRTPBase< X86TTIImpl >::getUserCost(), llvm::Type::getVectorElementType(), getVectorInstrCost(), llvm::Type::getVectorNumElements(), llvm::X86Subtarget::hasAVX512(), llvm::Type::isVectorTy(), llvm::SPII::Load, llvm::max(), and llvm::TargetTransformInfo::TCC_Basic.
Referenced by X86TTIImpl().
getVectorInstrCost()
int X86TTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Definition at line 2385 of file X86TargetTransformInfo.cpp.
References assert(), llvm::CostTableLookup(), llvm::TargetTransformInfoImplBase::DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::Type::getScalarType(), llvm::MVT::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getVectorInstrCost(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::X86Subtarget::isSLM(), llvm::Type::isVectorTy(), and llvm::AArch64CC::LT.
Referenced by getUserCost(), and X86TTIImpl().
hasDivRemOp()
bool X86TTIImpl::hasDivRemOp (Type * DataType, bool IsSigned)
Definition at line 3475 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::DL, llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::isOperationLegal(), llvm::ISD::SDIVREM, and llvm::ISD::UDIVREM.
Referenced by X86TTIImpl().
isFCmpOrdCheaperThanFCmpZero()
bool X86TTIImpl::isFCmpOrdCheaperThanFCmpZero (Type * Ty)
Definition at line 3480 of file X86TargetTransformInfo.cpp.
Referenced by X86TTIImpl().
isLegalMaskedCompressStore()
bool X86TTIImpl::isLegalMaskedCompressStore (Type * DataType)
Definition at line 3426 of file X86TargetTransformInfo.cpp.
References isLegalMaskedExpandLoad().
Referenced by X86TTIImpl().
isLegalMaskedExpandLoad()
bool X86TTIImpl::isLegalMaskedExpandLoad (Type * DataType)
Definition at line 3402 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVBMI2(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and llvm::Type::isIntegerTy().
Referenced by isLegalMaskedCompressStore(), and X86TTIImpl().
isLegalMaskedGather()
bool X86TTIImpl::isLegalMaskedGather (Type * DataType, MaybeAlign Alignment)
Definition at line 3430 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::getScalarType(), llvm::Type::getVectorNumElements(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasFastGather(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), and llvm::isPowerOf2_32().
Referenced by getGatherScatterOpCost(), isLegalMaskedScatter(), and X86TTIImpl().
isLegalMaskedLoad()
bool X86TTIImpl::isLegalMaskedLoad (Type * DataType, MaybeAlign Alignment)
Definition at line 3340 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::getScalarType(), llvm::Type::getVectorNumElements(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasBWI(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by getMaskedMemoryOpCost(), isLegalMaskedStore(), and X86TTIImpl().
isLegalMaskedScatter()
bool X86TTIImpl::isLegalMaskedScatter (Type * DataType, MaybeAlign Alignment)
Definition at line 3468 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasAVX512(), and isLegalMaskedGather().
Referenced by getGatherScatterOpCost(), and X86TTIImpl().
isLegalMaskedStore()
bool X86TTIImpl::isLegalMaskedStore (Type * DataType, MaybeAlign Alignment)
Definition at line 3363 of file X86TargetTransformInfo.cpp.
References isLegalMaskedLoad().
Referenced by getMaskedMemoryOpCost(), and X86TTIImpl().
isLegalNTLoad()
bool X86TTIImpl::isLegalNTLoad (Type * DataType, Align Alignment)
Definition at line 3367 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::DL, llvm::DataLayout::getTypeStoreSize(), llvm::X86Subtarget::hasAVX2(), and llvm::X86Subtarget::hasSSE1().
Referenced by X86TTIImpl().
isLegalNTStore()
bool X86TTIImpl::isLegalNTStore (Type * DataType, Align Alignment)
Definition at line 3378 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::DL, llvm::DataLayout::getTypeStoreSize(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE4A(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and llvm::isPowerOf2_32().
Referenced by X86TTIImpl().
isLSRCostLess()
bool X86TTIImpl::isLSRCostLess (TargetTransformInfo::LSRCost & C1, TargetTransformInfo::LSRCost & C2)
Definition at line 3325 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::Insns, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
Referenced by X86TTIImpl().
The documentation for this class was generated from the following files:
lib/Target/X86/X86TargetTransformInfo.h
lib/Target/X86/X86TargetTransformInfo.cpp