LLVM: llvm::MachineFrameInfo Class Reference
llvm::MachineFrameInfo Class Reference
The MachineFrameInfo class represents an abstract stack frame until prolog/epilog code is inserted.
#include "llvm/CodeGen/MachineFrameInfo.h"
Public Types
enum SSPLayoutKind { SSPLK_None, SSPLK_LargeArray, SSPLK_SmallArray, SSPLK_AddrOf }
Stack Smashing Protection (SSP) rules require that vulnerable stack allocations are located close the stack protector.
Public Member Functions
MachineFrameInfo (unsigned StackAlignment, bool StackRealignable, bool ForcedRealign)
bool hasStackObjects () const
Return true if there are any stack objects in this function.
bool hasVarSizedObjects () const
This method may be called any time after instruction selection is complete to determine if the stack frame for this function contains any variable sized objects.
int getStackProtectorIndex () const
Return the index for the stack protector object.
void setStackProtectorIndex (int I)
bool hasStackProtectorIndex () const
int getFunctionContextIndex () const
Return the index for the function context object.
void setFunctionContextIndex (int I)
bool isFrameAddressTaken () const
This method may be called any time after instruction selection is complete to determine if there is a call to @llvm.frameaddress in this function.
void setFrameAddressIsTaken (bool T)
bool isReturnAddressTaken () const
This method may be called any time after instruction selection is complete to determine if there is a call to @llvm.returnaddress in this function.
void setReturnAddressIsTaken (bool s)
bool hasStackMap () const
This method may be called any time after instruction selection is complete to determine if there is a call to builtin @llvm.experimental.stackmap.
void setHasStackMap (bool s=true)
bool hasPatchPoint () const
This method may be called any time after instruction selection is complete to determine if there is a call to builtin @llvm.experimental.patchpoint.
void setHasPatchPoint (bool s=true)
int getObjectIndexBegin () const
Return the minimum frame object index.
int getObjectIndexEnd () const
Return one past the maximum frame object index.
unsigned getNumFixedObjects () const
Return the number of fixed objects.
unsigned getNumObjects () const
Return the number of objects.
void mapLocalFrameObject (int ObjectIndex, int64_t Offset)
Map a frame index into the local object block.
std::pair< int, int64_t > getLocalFrameObjectMap (int i) const
Get the local offset mapping for a for an object.
int64_t getLocalFrameObjectCount () const
Return the number of objects allocated into the local object block.
void setLocalFrameSize (int64_t sz)
Set the size of the local object blob.
int64_t getLocalFrameSize () const
Get the size of the local object blob.
void setLocalFrameMaxAlign (Align Alignment)
Required alignment of the local object blob, which is the strictest alignment of any object in it.
Align getLocalFrameMaxAlign () const
Return the required alignment of the local object blob.
bool getUseLocalStackAllocationBlock () const
Get whether the local allocation blob should be allocated together or let PEI allocate the locals in it directly.
void setUseLocalStackAllocationBlock (bool v)
setUseLocalStackAllocationBlock - Set whether the local allocation blob should be allocated together or let PEI allocate the locals in it directly.
bool isObjectPreAllocated (int ObjectIdx) const
Return true if the object was pre-allocated into the local block.
int64_t getObjectSize (int ObjectIdx) const
Return the size of the specified object.
void setObjectSize (int ObjectIdx, int64_t Size)
Change the size of the specified stack object.
unsigned getObjectAlignment (int ObjectIdx) const
Return the alignment of the specified stack object.
void setObjectAlignment (int ObjectIdx, unsigned Align)
setObjectAlignment - Change the alignment of the specified stack object.
const AllocaInst * getObjectAllocation (int ObjectIdx) const
Return the underlying Alloca of the specified stack object if it exists.
int64_t getObjectOffset (int ObjectIdx) const
Return the assigned stack offset of the specified object from the incoming stack pointer.
bool isObjectZExt (int ObjectIdx) const
void setObjectZExt (int ObjectIdx, bool IsZExt)
bool isObjectSExt (int ObjectIdx) const
void setObjectSExt (int ObjectIdx, bool IsSExt)
void setObjectOffset (int ObjectIdx, int64_t SPOffset)
Set the stack frame offset of the specified object.
SSPLayoutKind getObjectSSPLayout (int ObjectIdx) const
void setObjectSSPLayout (int ObjectIdx, SSPLayoutKind Kind)
uint64_t getStackSize () const
Return the number of bytes that must be allocated to hold all of the fixed size frame objects.
void setStackSize (uint64_t Size)
Set the size of the stack.
uint64_t estimateStackSize (const MachineFunction &MF) const
Estimate and return the size of the stack frame.
int getOffsetAdjustment () const
Return the correction for frame offsets.
void setOffsetAdjustment (int Adj)
Set the correction for frame offsets.
unsigned getMaxAlignment () const
Return the alignment in bytes that this function must be aligned to, which is greater than the default stack alignment provided by the target.
void ensureMaxAlignment (Align Alignment)
Make sure the function is at least Align bytes aligned.
void ensureMaxAlignment (unsigned Align)
FIXME: Remove this once transition to Align is over.
bool adjustsStack () const
Return true if this function adjusts the stack – e.g., when calling another function.
void setAdjustsStack (bool V)
bool hasCalls () const
Return true if the current function has any function calls.
void setHasCalls (bool V)
bool hasOpaqueSPAdjustment () const
Returns true if the function contains opaque dynamic stack adjustments.
void setHasOpaqueSPAdjustment (bool B)
bool hasCopyImplyingStackAdjustment () const
Returns true if the function contains operations which will lower down to instructions which manipulate the stack pointer.
void setHasCopyImplyingStackAdjustment (bool B)
bool hasVAStart () const
Returns true if the function calls the llvm.va_start intrinsic.
void setHasVAStart (bool B)
bool hasMustTailInVarArgFunc () const
Returns true if the function is variadic and contains a musttail call.
void setHasMustTailInVarArgFunc (bool B)
bool hasTailCall () const
Returns true if the function contains a tail call.
void setHasTailCall ()
void computeMaxCallFrameSize (const MachineFunction &MF)
Computes the maximum size of a callframe and the AdjustsStack property.
unsigned getMaxCallFrameSize () const
Return the maximum size of a call frame that must be allocated for an outgoing function call.
bool isMaxCallFrameSizeComputed () const
void setMaxCallFrameSize (unsigned S)
unsigned getCVBytesOfCalleeSavedRegisters () const
Returns how many bytes of callee-saved registers the target pushed in the prologue.
void setCVBytesOfCalleeSavedRegisters (unsigned S)
int CreateFixedObject (uint64_t Size, int64_t SPOffset, bool IsImmutable, bool isAliased=false)
Create a new object at a fixed location on the stack.
int CreateFixedSpillStackObject (uint64_t Size, int64_t SPOffset, bool IsImmutable=false)
Create a spill slot at a fixed location on the stack.
bool isFixedObjectIndex (int ObjectIdx) const
Returns true if the specified index corresponds to a fixed stack object.
bool isAliasedObjectIndex (int ObjectIdx) const
Returns true if the specified index corresponds to an object that might be pointed to by an LLVM IR value.
bool isImmutableObjectIndex (int ObjectIdx) const
Returns true if the specified index corresponds to an immutable object.
void setIsImmutableObjectIndex (int ObjectIdx, bool IsImmutable)
Marks the immutability of an object.
bool isSpillSlotObjectIndex (int ObjectIdx) const
Returns true if the specified index corresponds to a spill slot.
bool isStatepointSpillSlotObjectIndex (int ObjectIdx) const
uint8_t getStackID (int ObjectIdx) const
void setStackID (int ObjectIdx, uint8_t ID)
bool isDeadObjectIndex (int ObjectIdx) const
Returns true if the specified index corresponds to a dead object.
bool isVariableSizedObjectIndex (int ObjectIdx) const
Returns true if the specified index corresponds to a variable sized object.
void markAsStatepointSpillSlotObjectIndex (int ObjectIdx)
int CreateStackObject (uint64_t Size, Align Alignment, bool isSpillSlot, const AllocaInst *Alloca=nullptr, uint8_t ID=0)
Create a new statically sized stack object, returning a nonnegative identifier to represent it.
int CreateStackObject (uint64_t Size, unsigned Alignment, bool isSpillSlot, const AllocaInst *Alloca=nullptr, uint8_t ID=0)
FIXME: Remove this function when transition to Align is over.
int CreateSpillStackObject (uint64_t Size, Align Alignment)
Create a new statically sized stack object that represents a spill slot, returning a nonnegative identifier to represent it.
int CreateSpillStackObject (uint64_t Size, unsigned Alignment)
FIXME: Remove this function when transition to Align is over.
void RemoveStackObject (int ObjectIdx)
Remove or mark dead a statically sized stack object.
int CreateVariableSizedObject (Align Alignment, const AllocaInst *Alloca)
Notify the MachineFrameInfo object that a variable sized object has been created.
int CreateVariableSizedObject (unsigned Alignment, const AllocaInst *Alloca)
FIXME: Remove this function when transition to Align is over.
const std::vector< CalleeSavedInfo > & getCalleeSavedInfo () const
Returns a reference to call saved info vector for the current function.
std::vector< CalleeSavedInfo > & getCalleeSavedInfo ()
void setCalleeSavedInfo (const std::vector< CalleeSavedInfo > &CSI)
Used by prolog/epilog inserter to set the function's callee saved information.
bool isCalleeSavedInfoValid () const
Has the callee saved info been calculated yet?
void setCalleeSavedInfoValid (bool v)
MachineBasicBlock * getSavePoint () const
void setSavePoint (MachineBasicBlock *NewSave)
MachineBasicBlock * getRestorePoint () const
void setRestorePoint (MachineBasicBlock *NewRestore)
BitVector getPristineRegs (const MachineFunction &MF) const
Return a set of physical registers that are pristine.
void print (const MachineFunction &MF, raw_ostream &OS) const
Used by the MachineFunction printer to print information about stack objects.
void dump (const MachineFunction &MF) const
dump - Print the function to stderr.
Detailed Description
The MachineFrameInfo class represents an abstract stack frame until prolog/epilog code is inserted.
This class is key to allowing stack frame representation optimizations, such as frame pointer elimination. It also allows more mundane (but still important) optimizations, such as reordering of abstract objects on the stack frame.
To support this, the class assigns unique integer identifiers to stack objects requested clients. These identifiers are negative integers for fixed stack objects (such as arguments passed on the stack) or nonnegative for objects that may be reordered. Instructions which refer to stack objects use a special MO_FrameIndex operand to represent these frame indexes.
Because this class keeps track of all references to the stack frame, it knows when a variable sized object is allocated on the stack. This is the sole condition which prevents frame pointer elimination, which is an important optimization on register-poor architectures. Because original variable sized alloca's in the source program are the only source of variable sized stack objects, it is safe to decide whether there will be any variable sized objects before all stack objects are known (for example, register allocator spill code never needs variable sized objects).
When prolog/epilog code emission is performed, the final stack frame is built and the machine instructions are modified to refer to the actual stack offsets of the object, eliminating all MO_FrameIndex operands from the program.
Abstract Stack Frame Information
Definition at line 106 of file MachineFrameInfo.h.
Member Enumeration Documentation
SSPLayoutKind
enum llvm::MachineFrameInfo::SSPLayoutKind
Stack Smashing Protection (SSP) rules require that vulnerable stack allocations are located close the stack protector.
Enumerator
SSPLK_None
Did not trigger a stack protector.
No effect on data layout.
SSPLK_LargeArray
Array or nested array >= SSP-buffer-size.
Closest to the stack protector.
SSPLK_SmallArray
Array or nested array < SSP-buffer-size.
2nd closest to the stack protector.
SSPLK_AddrOf
The address of this allocation is exposed and triggered protection.
3rd closest to the protector.
Definition at line 110 of file MachineFrameInfo.h.
Constructor & Destructor Documentation
MachineFrameInfo()
llvm::MachineFrameInfo::MachineFrameInfo (unsigned StackAlignment, bool StackRealignable, bool ForcedRealign) inline explicit
Definition at line 339 of file MachineFrameInfo.h.
Member Function Documentation
adjustsStack()
bool llvm::MachineFrameInfo::adjustsStack () const inline
Return true if this function adjusts the stack – e.g., when calling another function.
This is only valid during and after prolog/epilog code insertion.
Definition at line 578 of file MachineFrameInfo.h.
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::MIRPrinter::convert(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), estimateStackSize(), and stashEntryDbgValues().
computeMaxCallFrameSize()
void MachineFrameInfo::computeMaxCallFrameSize (const MachineFunction & MF)
Computes the maximum size of a callframe and the AdjustsStack property.
This only works for targets defining TargetInstrInfo::getCallFrameSetupOpcode(), getCallFrameDestroyOpcode(), and getFrameSize(). This is usually computed by the prologue epilogue inserter but some targets may call this to compute it earlier.
Definition at line 189 of file MachineFrameInfo.cpp.
References assert(), llvm::InlineAsm::Extra_IsAlignStack, llvm::TargetInstrInfo::getCallFrameDestroyOpcode(), llvm::TargetInstrInfo::getCallFrameSetupOpcode(), llvm::TargetInstrInfo::getFrameSize(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getSubtarget(), llvm::max(), MI, llvm::InlineAsm::MIOp_ExtraInfo, Size, and TII.
Referenced by llvm::ARMTargetLowering::finalizeLowering(), llvm::AArch64TargetLowering::getVaListSizeInBits(), and llvm::AArch64Subtarget::mirFileLoaded().
CreateFixedObject()
int MachineFrameInfo::CreateFixedObject (uint64_t Size, int64_t SPOffset, bool IsImmutable, bool isAliased = false)
Create a new object at a fixed location on the stack.
All fixed objects should be created before other objects are created for efficiency. By default, fixed objects are not pointed to by LLVM IR values. This returns an index with a negative value.
Definition at line 82 of file MachineFrameInfo.cpp.
References assert(), clampStackAlignment(), llvm::commonAlignment(), and llvm::Align::None().
Referenced by llvm::AArch64CallLowering::AArch64CallLowering(), llvm::analyzeArguments(), AnalyzeReturnValues(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), CalculateTailCallArgDest(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::LanaiFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineCalleeSaves(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), EnsureStackAlignment(), getMOVL(), getNextIntArgReg(), getOrCreateFixedStackObject(), llvm::SystemZFrameLowering::getOrCreateFramePointerSaveIndex(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::MIRParserImpl::initializeFrameInfo(), isSortedByValueNo(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::SITargetLowering::LowerCall(), lowerCallResult(), LowerCallResult(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerINTRINSIC_W_CHAIN(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::MipsTargetLowering::lowerSTORE(), LowerVASTART(), mayTailCallThisCC(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::FunctionLoweringInfo::set(), shouldGuaranteeTCO(), truncateScalarIntegerArg(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), and unpackFromMemLoc().
CreateFixedSpillStackObject()
int MachineFrameInfo::CreateFixedSpillStackObject (uint64_t Size, int64_t SPOffset, bool IsImmutable = false)
Create a spill slot at a fixed location on the stack.
Returns an index with a negative value.
Definition at line 101 of file MachineFrameInfo.cpp.
References clampStackAlignment(), llvm::commonAlignment(), and llvm::Align::None().
Referenced by llvm::ARCFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), assignCalleeSavedSpillSlots(), and llvm::MIRParserImpl::initializeFrameInfo().
CreateSpillStackObject() [1/2]
int MachineFrameInfo::CreateSpillStackObject (uint64_t Size, Align Alignment)
Create a new statically sized stack object that represents a spill slot, returning a nonnegative identifier to represent it.
Definition at line 65 of file MachineFrameInfo.cpp.
References clampStackAlignment(), CreateStackObject(), and ensureMaxAlignment().
Referenced by llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPR(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::VirtRegMap::assignVirt2Phys(), llvm::HexagonFrameLowering::determineCalleeSaves(), and INITIALIZE_PASS().
CreateSpillStackObject() [2/2]
int llvm::MachineFrameInfo::CreateSpillStackObject (uint64_t Size, unsigned Alignment) inline
FIXME: Remove this function when transition to Align is over.
Definition at line 752 of file MachineFrameInfo.h.
References llvm::assumeAligned().
CreateStackObject() [1/2]
int MachineFrameInfo::CreateStackObject (uint64_t Size, Align Alignment, bool isSpillSlot, const AllocaInst * Alloca = nullptr, uint8_t ID = 0)
Create a new statically sized stack object, returning a nonnegative identifier to represent it.
Definition at line 50 of file MachineFrameInfo.cpp.
References assert(), clampStackAlignment(), and ensureMaxAlignment().
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), assignCalleeSavedSpillSlots(), llvm::X86TargetLowering::BuildFILD(), callingConvSupported(), CC_RISCV_FastCC(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::MipsFunctionInfo::createISRRegFI(), llvm::XCoreFunctionInfo::createLRSpillSlot(), CreateSpillStackObject(), llvm::SelectionDAG::CreateStackTemporary(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), EnsureStackAlignment(), getAddressForMemoryInput(), llvm::RISCVMachineFunctionInfo::getMoveF64FrameIndex(), llvm::MipsFunctionInfo::getMoveF64ViaSpillFI(), getMOVL(), getNormalLoadInput(), getVectorCompareInfo(), INITIALIZE_PASS(), llvm::MIRParserImpl::initializeFrameInfo(), insertCSRRestores(), isSortedByValueNo(), LowerADJUST_TRAMPOLINE(), llvm::SparcTargetLowering::LowerCall_32(), lowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), lowerINT_TO_FP_vXi64(), lowerUINT_TO_FP_vec(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), and llvm::FunctionLoweringInfo::set().
CreateStackObject() [2/2]
int llvm::MachineFrameInfo::CreateStackObject (uint64_t Size, unsigned Alignment, bool isSpillSlot, const AllocaInst * Alloca = nullptr, uint8_t ID = 0) inline
FIXME: Remove this function when transition to Align is over.
Definition at line 740 of file MachineFrameInfo.h.
References llvm::assumeAligned().
CreateVariableSizedObject() [1/2]
int MachineFrameInfo::CreateVariableSizedObject (Align Alignment, const AllocaInst * Alloca)
Notify the MachineFrameInfo object that a variable sized object has been created.
This must be created whenever a variable sized object is created, whether or not the index returned is actually used.
Definition at line 73 of file MachineFrameInfo.cpp.
References clampStackAlignment(), and ensureMaxAlignment().
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), and llvm::FunctionLoweringInfo::set().
CreateVariableSizedObject() [2/2]
int llvm::MachineFrameInfo::CreateVariableSizedObject (unsigned Alignment, const AllocaInst * Alloca) inline
FIXME: Remove this function when transition to Align is over.
Definition at line 767 of file MachineFrameInfo.h.
References llvm::assumeAligned().
dump()
LLVM_DUMP_METHOD void MachineFrameInfo::dump (const MachineFunction & MF) const
dump - Print the function to stderr.
Definition at line 255 of file MachineFrameInfo.cpp.
References llvm::dbgs(), and print().
ensureMaxAlignment() [1/2]
void MachineFrameInfo::ensureMaxAlignment (Align Alignment)
Make sure the function is at least Align bytes aligned.
Definition at line 31 of file MachineFrameInfo.cpp.
References assert().
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), CreateSpillStackObject(), CreateStackObject(), CreateVariableSizedObject(), llvm::CCState::ensureMaxAlignment(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::HexagonTargetLowering::LowerCall(), and llvm::MachineFunction::MachineFunction().
ensureMaxAlignment() [2/2]
void llvm::MachineFrameInfo::ensureMaxAlignment (unsigned Align) inline
FIXME: Remove this once transition to Align is over.
Definition at line 571 of file MachineFrameInfo.h.
References llvm::assumeAligned().
estimateStackSize()
uint64_t MachineFrameInfo::estimateStackSize (const MachineFunction & MF) const
Estimate and return the size of the stack frame.
Definition at line 136 of file MachineFrameInfo.cpp.
References adjustsStack(), llvm::TargetStackID::Default, llvm::numbers::e, llvm::TargetSubtargetInfo::getFrameLowering(), getMaxAlignment(), getMaxCallFrameSize(), getObjectAlignment(), getObjectIndexBegin(), getObjectIndexEnd(), getObjectOffset(), getObjectSize(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlignment(), getStackID(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::getTransientStackAlignment(), llvm::TargetFrameLowering::hasReservedCallFrame(), hasVarSizedObjects(), isDeadObjectIndex(), llvm::max(), and llvm::TargetRegisterInfo::needsStackRealignment().
Referenced by llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::XCoreFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::MipsFrameLowering::estimateStackSize(), llvm::HexagonFrameLowering::getAlignaInstr(), llvm::XCoreFunctionInfo::isLargeFrame(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized().
getCalleeSavedInfo() [1/2]
const std::vector<CalleeSavedInfo>& llvm::MachineFrameInfo::getCalleeSavedInfo () const inline
Returns a reference to call saved info vector for the current function.
Definition at line 772 of file MachineFrameInfo.h.
Referenced by addCalleeSavedRegs(), llvm::LivePhysRegs::addLiveOutsNoPristines(), llvm::Thumb1FrameLowering::canUseAsEpilogue(), llvm::MIRPrinter::convertStackObjects(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), enableAllocFrameElim(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::TargetFrameLowering::getCalleeSaves(), llvm::RISCVFrameLowering::getFirstSPAdjustAmount(), llvm::RISCVFrameLowering::getFrameIndexReference(), getLoadStoreOffsetAlign(), getPristineRegs(), getSVECalleeSaveSlotRange(), llvm::HexagonFrameLowering::insertCFIInstructions(), insertCSRRestores(), InsertLDR_STR(), llvm::Mips16RegisterInfo::intRegClass(), llvm::Mips16InstrInfo::makeFrame(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::Mips16InstrInfo::restoreFrame(), and ShouldSignReturnAddress().
getCalleeSavedInfo() [2/2]
std::vector<CalleeSavedInfo>& llvm::MachineFrameInfo::getCalleeSavedInfo () inline
Definition at line 776 of file MachineFrameInfo.h.
getCVBytesOfCalleeSavedRegisters()
unsigned llvm::MachineFrameInfo::getCVBytesOfCalleeSavedRegisters () const inline
Returns how many bytes of callee-saved registers the target pushed in the prologue.
Only used for debug info.
Definition at line 637 of file MachineFrameInfo.h.
Referenced by llvm::CodeViewDebug::beginFunctionImpl(), and llvm::MIRPrinter::convert().
getFunctionContextIndex()
int llvm::MachineFrameInfo::getFunctionContextIndex () const inline
Return the index for the function context object.
This object is used for SjLj exceptions.
Definition at line 359 of file MachineFrameInfo.h.
Referenced by getRetpolineSymbol(), and llvm::ARMTargetLowering::ReplaceNodeResults().
getLocalFrameMaxAlign()
Align llvm::MachineFrameInfo::getLocalFrameMaxAlign () const inline
Return the required alignment of the local object blob.
Definition at line 427 of file MachineFrameInfo.h.
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), and llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized().
getLocalFrameObjectCount()
int64_t llvm::MachineFrameInfo::getLocalFrameObjectCount () const inline
Return the number of objects allocated into the local object block.
Definition at line 412 of file MachineFrameInfo.h.
References llvm::SmallVectorBase::size().
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), and llvm::MIRPrinter::convertStackObjects().
getLocalFrameObjectMap()
std::pair<int, int64_t> llvm::MachineFrameInfo::getLocalFrameObjectMap (int i) const inline
Get the local offset mapping for a for an object.
Definition at line 405 of file MachineFrameInfo.h.
References assert(), and llvm::SmallVectorBase::size().
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), and llvm::MIRPrinter::convertStackObjects().
getLocalFrameSize()
int64_t llvm::MachineFrameInfo::getLocalFrameSize () const inline
Get the size of the local object blob.
Definition at line 418 of file MachineFrameInfo.h.
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), llvm::MIRPrinter::convert(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), lookupCandidateBaseReg(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), and llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized().
getMaxAlignment()
unsigned llvm::MachineFrameInfo::getMaxAlignment () const inline
Return the alignment in bytes that this function must be aligned to, which is greater than the default stack alignment provided by the target.
Definition at line 566 of file MachineFrameInfo.h.
References llvm::Align::value().
Referenced by addExclusiveRegPair(), llvm::PPCFrameLowering::addScavengingSpillSlot(), AdjustStackOffset(), AssignProtectedObjSet(), calculateSetFPREG(), llvm::MIRPrinter::convert(), llvm::PPCFrameLowering::determineFrameLayout(), emitAlignedDPRCS2Spills(), llvm::SIFrameLowering::emitEpilogue(), llvm::HexagonDAGToDAGISel::EmitFunctionEntryCode(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), enableAllocFrameElim(), estimateStackSize(), getOpenCLAlignment(), llvm::RISCVFrameLowering::hasBP(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::TargetRegisterInfo::needsStackRealignment(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::replaceFPWithRealFP(), and llvm::HexagonDAGToDAGISel::SelectFrameIndex().
getMaxCallFrameSize()
unsigned llvm::MachineFrameInfo::getMaxCallFrameSize () const inline
Return the maximum size of a call frame that must be allocated for an outgoing function call.
This is only available if CallFrameSetup/Destroy pseudo instructions are used by the target, and then only during or after prolog/epilog code insertion.
Definition at line 623 of file MachineFrameInfo.h.
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), llvm::MIRPrinter::convert(), llvm::PPCFrameLowering::determineFrameLayout(), enableAllocFrameElim(), estimateStackSize(), llvm::X86FrameLowering::getWin64EHFrameIndexRef(), llvm::AArch64FrameLowering::getWinEHFuncletFrameSize(), llvm::RISCVFrameLowering::hasBP(), llvm::AArch64FrameLowering::hasFP(), llvm::Thumb1FrameLowering::hasReservedCallFrame(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::Mips16FrameLowering::hasReservedCallFrame(), llvm::ARMFrameLowering::hasReservedCallFrame(), isFuncletReturnInstr(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), stashEntryDbgValues(), and llvm::SystemZInstrInfo::SystemZInstrInfo().
getNumFixedObjects()
unsigned llvm::MachineFrameInfo::getNumFixedObjects () const inline
Return the number of fixed objects.
Definition at line 393 of file MachineFrameInfo.h.
Referenced by llvm::AVRFrameAnalyzer::runOnMachineFunction().
getNumObjects()
unsigned llvm::MachineFrameInfo::getNumObjects () const inline
Return the number of objects.
Definition at line 396 of file MachineFrameInfo.h.
Referenced by llvm::R600FrameLowering::getFrameIndexReference(), llvm::R600InstrInfo::getIndirectIndexBegin(), llvm::R600InstrInfo::getIndirectIndexEnd(), llvm::AArch64InstrInfo::getOutliningType(), and llvm::AVRFrameAnalyzer::runOnMachineFunction().
getObjectAlignment()
unsigned llvm::MachineFrameInfo::getObjectAlignment (int ObjectIdx) const inline
Return the alignment of the specified stack object.
Definition at line 464 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::addFrameReference(), AdjustStackOffset(), AssignProtectedObjSet(), buildEpilogReload(), buildMUBUFOffsetLoadStore(), buildPrologSpill(), llvm::MIRPrinter::convertStackObjects(), determineSVEStackObjectOffsets(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::TargetLoweringBase::emitPatchPoint(), estimateStackSize(), llvm::HexagonEvaluator::evaluate(), fixupFuncForFI(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getContiguousRangeOfSetBits(), getFrameIndexMMO(), getFrameIndexOperandNum(), llvm::R600FrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), llvm::MipsInstrInfo::GetMemOperand(), getMemsetStores(), getMemsetValue(), getStartOrEndSlot(), getVCmpInst(), llvm::GISelKnownBits::inferAlignmentForFrameIdx(), llvm::SelectionDAG::InferPtrAlignment(), INITIALIZE_PASS(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), false::IntervalSorter::operator()(), llvm::X86FrameLowering::orderFrameObjects(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIRegisterInfo::restoreSGPR(), scavengeStackSlot(), shouldUseZeroOffsetLdSt(), spillIncomingStatepointValue(), llvm::SIRegisterInfo::spillSGPR(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), and tryToElideArgumentCopy().
getObjectAllocation()
const AllocaInst* llvm::MachineFrameInfo::getObjectAllocation (int ObjectIdx) const inline
Return the underlying Alloca of the specified stack object if it exists.
Returns 0 if none exists.
Definition at line 483 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::MIRPrinter::convertStackObjects(), llvm::StackProtector::copyToMachineFrameInfo(), getStartOrEndSlot(), and printFrameIndex().
getObjectIndexBegin()
int llvm::MachineFrameInfo::getObjectIndexBegin () const inline
Return the minimum frame object index.
Definition at line 387 of file MachineFrameInfo.h.
Referenced by AdjustStackOffset(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), AssignProtectedObjSet(), llvm::VirtRegMap::assignVirt2StackSlot(), computeFreeStackSlots(), llvm::MIRPrinter::convertStackObjects(), determineSVEStackObjectOffsets(), llvm::MipsFrameLowering::estimateStackSize(), estimateStackSize(), getFrameIndexOperandNum(), llvm::R600FrameLowering::getFrameIndexReference(), getOrCreateFixedStackObject(), printFrameIndex(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIMachineFunctionInfo::removeDeadFrameIndices(), shouldGuaranteeTCO(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
getObjectIndexEnd()
int llvm::MachineFrameInfo::getObjectIndexEnd () const inline
Return one past the maximum frame object index.
Definition at line 390 of file MachineFrameInfo.h.
Referenced by AdjustStackOffset(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), AssignProtectedObjSet(), llvm::MIRPrinter::convertStackObjects(), llvm::StackProtector::copyToMachineFrameInfo(), determineSVEStackObjectOffsets(), estimateStackSize(), getFrameIndexOperandNum(), getStartOrEndSlot(), INITIALIZE_PASS(), false::IntervalSorter::operator()(), llvm::X86FrameLowering::orderFrameObjects(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIMachineFunctionInfo::removeDeadFrameIndices(), llvm::AVRFrameAnalyzer::runOnMachineFunction(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
getObjectOffset()
int64_t llvm::MachineFrameInfo::getObjectOffset (int ObjectIdx) const inline
Return the assigned stack offset of the specified object from the incoming stack pointer.
Definition at line 491 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::AMDGPUTargetLowering::addTokenForArgument(), AdjustStackOffset(), AssignProtectedObjSet(), buildEpilogReload(), buildMUBUFOffsetLoadStore(), buildPrologSpill(), computeFreeStackSlots(), llvm::MIRPrinter::convertStackObjects(), determineSVEStackObjectOffsets(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::Mips16FrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::MipsFrameLowering::estimateStackSize(), estimateStackSize(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), GetEHSpillList(), llvm::NVPTXFrameLowering::getFrameIndexReference(), llvm::MipsSEFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::SIFrameLowering::getFrameIndexReference(), llvm::SparcFrameLowering::getFrameIndexReference(), llvm::VEFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::AArch64FrameLowering::getFrameIndexReferencePreferSP(), llvm::X86FrameLowering::getFrameIndexReferenceSP(), getOrCreateFixedStackObject(), llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), GetSpillList(), llvm::HexagonFrameLowering::insertCFIInstructions(), isConsecutiveLSLoc(), MatchingStackOffset(), mayTailCallThisCC(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), shouldClusterFI(), and shouldGuaranteeTCO().
getObjectSize()
int64_t llvm::MachineFrameInfo::getObjectSize (int ObjectIdx) const inline
Return the size of the specified object.
Definition at line 450 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::addFrameReference(), llvm::AMDGPUTargetLowering::addTokenForArgument(), AdjustStackOffset(), llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPR(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), AssignProtectedObjSet(), CC_MipsO32_FP64(), computeFreeStackSlots(), llvm::MIRPrinter::convertStackObjects(), determineSVEStackObjectOffsets(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::ARCFrameLowering::emitEpilogue(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::ARCFrameLowering::emitPrologue(), llvm::MipsFrameLowering::estimateStackSize(), estimateStackSize(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), getFrameIndexMMO(), getFrameIndexOperandNum(), llvm::R600FrameLowering::getFrameIndexReference(), llvm::MipsInstrInfo::GetMemOperand(), getOrCreateFixedStackObject(), getStartOrEndSlot(), INITIALIZE_PASS(), isConsecutiveLSLoc(), llvm::SystemZInstrInfo::isStackSlotCopy(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), MatchingStackOffset(), mayTailCallThisCC(), false::IntervalSorter::operator()(), llvm::X86FrameLowering::orderFrameObjects(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::AVRFrameAnalyzer::runOnMachineFunction(), scavengeStackSlot(), shouldGuaranteeTCO(), shouldUseZeroOffsetLdSt(), spillIncomingStatepointValue(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), and tryToElideArgumentCopy().
getObjectSSPLayout()
SSPLayoutKind llvm::MachineFrameInfo::getObjectSSPLayout (int ObjectIdx) const inline
Definition at line 533 of file MachineFrameInfo.h.
References assert().
Referenced by AssignProtectedObjSet(), getStartOrEndSlot(), and INITIALIZE_PASS().
getOffsetAdjustment()
int llvm::MachineFrameInfo::getOffsetAdjustment () const inline
Return the correction for frame offsets.
Definition at line 559 of file MachineFrameInfo.h.
Referenced by llvm::CodeViewDebug::beginFunctionImpl(), llvm::MIRPrinter::convert(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), and llvm::TargetFrameLowering::getFrameIndexReference().
getPristineRegs()
BitVector MachineFrameInfo::getPristineRegs (const MachineFunction & MF) const
Return a set of physical registers that are pristine.
Pristine registers hold a value that is useless to the current function, but that must be preserved - they are callee saved registers that are not saved.
Before the PrologueEpilogueInserter has placed the CSR spill code, this method always returns an empty set.
Definition at line 114 of file MachineFrameInfo.cpp.
References getCalleeSavedInfo(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, isCalleeSavedInfoValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), MRI, and TRI.
Referenced by llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::CriticalAntiDepBreaker::StartBlock(), and llvm::AggressiveAntiDepBreaker::StartBlock().
getRestorePoint()
MachineBasicBlock* llvm::MachineFrameInfo::getRestorePoint () const inline
Definition at line 791 of file MachineFrameInfo.h.
Referenced by llvm::MIRPrinter::convert(), insertCSRRestores(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), and stashEntryDbgValues().
getSavePoint()
MachineBasicBlock* llvm::MachineFrameInfo::getSavePoint () const inline
Definition at line 789 of file MachineFrameInfo.h.
Referenced by llvm::MIRPrinter::convert(), insertCSRRestores(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), stashEntryDbgValues(), and updateLiveness().
getStackID()
uint8_t llvm::MachineFrameInfo::getStackID (int ObjectIdx) const inline
See also
StackID
Definition at line 700 of file MachineFrameInfo.h.
Referenced by allSGPRSpillsAreDead(), AssignProtectedObjSet(), computeFreeStackSlots(), llvm::MIRPrinter::convertStackObjects(), determineSVEStackObjectOffsets(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), estimateStackSize(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), insertCSRRestores(), and false::IntervalSorter::operator()().
getStackProtectorIndex()
int llvm::MachineFrameInfo::getStackProtectorIndex () const inline
Return the index for the stack protector object.
Definition at line 353 of file MachineFrameInfo.h.
Referenced by AssignProtectedObjSet(), llvm::MIRPrinter::convertStackObjects(), INITIALIZE_PASS(), lookupCandidateBaseReg(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and WindowsRequiresStackProbe().
getStackSize()
uint64_t llvm::MachineFrameInfo::getStackSize () const inline
Return the number of bytes that must be allocated to hold all of the fixed size frame objects.
This is only valid after Prolog/Epilog code insertion has finalized the stack frame layout.
Definition at line 550 of file MachineFrameInfo.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::PPCFrameLowering::canUseAsEpilogue(), llvm::MIRPrinter::convert(), llvm::createXCoreFrameToArgsOffsetEliminationPass(), llvm::ARCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::emitFrameDirective(), llvm::AVRFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AsmPrinter::emitStackSizeSection(), enableAllocFrameElim(), getDwarfRegNum(), llvm::RISCVFrameLowering::getFirstSPAdjustAmount(), llvm::MipsSEFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::SparcFrameLowering::getFrameIndexReference(), llvm::VEFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), getOpenCLAlignment(), llvm::AArch64InstrInfo::getOutliningType(), getStackOffset(), llvm::RISCVFrameLowering::hasBP(), llvm::WebAssemblyFrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::PPCFrameLowering::hasFP(), llvm::WebAssemblyFrameLowering::hasReservedCallFrame(), INITIALIZE_PASS(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), stashEntryDbgValues(), llvm::HexagonPacketizerList::useCalleesSP(), and llvm::HexagonPacketizerList::useCallersSP().
getUseLocalStackAllocationBlock()
bool llvm::MachineFrameInfo::getUseLocalStackAllocationBlock () const inline
Get whether the local allocation blob should be allocated together or let PEI allocate the locals in it directly.
Definition at line 431 of file MachineFrameInfo.h.
Referenced by AdjustStackOffset(), and AssignProtectedObjSet().
hasCalls()
bool llvm::MachineFrameInfo::hasCalls () const inline
Return true if the current function has any function calls.
Definition at line 582 of file MachineFrameInfo.h.
References HasCalls.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPR(), llvm::ARCFrameLowering::assignCalleeSavedSpillSlots(), llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), calculateSetFPREG(), llvm::AArch64FrameLowering::canUseRedZone(), llvm::MIRPrinter::convert(), llvm::SystemZFrameLowering::determineCalleeSaves(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::TargetOptions::DisableFramePointerElim(), llvm::ARCFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitPrologue(), llvm::VEFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::SIFrameLowering::hasFP(), insertCSRRestores(), llvm::WebAssemblyFrameLowering::needsPrologForEH(), llvm::SIRegisterInfo::requiresRegisterScavenging(), reservePrivateMemoryRegs(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), and verifyLeafProcRegUse().
hasCopyImplyingStackAdjustment()
bool llvm::MachineFrameInfo::hasCopyImplyingStackAdjustment () const inline
Returns true if the function contains operations which will lower down to instructions which manipulate the stack pointer.
Definition at line 591 of file MachineFrameInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::hasFP().
hasMustTailInVarArgFunc()
bool llvm::MachineFrameInfo::hasMustTailInVarArgFunc () const inline
Returns true if the function is variadic and contains a musttail call.
Definition at line 603 of file MachineFrameInfo.h.
Referenced by llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::MIRPrinter::convert(), handleMustTailForwardedRegisters(), and isSortedByValueNo().
hasOpaqueSPAdjustment()
bool llvm::MachineFrameInfo::hasOpaqueSPAdjustment () const inline
Returns true if the function contains opaque dynamic stack adjustments.
Definition at line 586 of file MachineFrameInfo.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), CantUseSP(), llvm::MIRPrinter::convert(), and llvm::X86FrameLowering::hasFP().
hasPatchPoint()
bool llvm::MachineFrameInfo::hasPatchPoint () const inline
This method may be called any time after instruction selection is complete to determine if there is a call to builtin @llvm.experimental.patchpoint.
Definition at line 383 of file MachineFrameInfo.h.
Referenced by llvm::MIRPrinter::convert(), llvm::WebAssemblyFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), INITIALIZE_PASS(), and llvm::PPCFrameLowering::needsFP().
hasStackMap()
bool llvm::MachineFrameInfo::hasStackMap () const inline
This method may be called any time after instruction selection is complete to determine if there is a call to builtin @llvm.experimental.stackmap.
Definition at line 377 of file MachineFrameInfo.h.
Referenced by llvm::MIRPrinter::convert(), llvm::WebAssemblyFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), and llvm::PPCFrameLowering::needsFP().
hasStackObjects()
bool llvm::MachineFrameInfo::hasStackObjects () const inline
Return true if there are any stack objects in this function.
Definition at line 345 of file MachineFrameInfo.h.
Referenced by llvm::NVPTXFrameLowering::emitPrologue(), insertCSRRestores(), llvm::X86FrameLowering::needsFrameIndexResolution(), llvm::TargetFrameLowering::needsFrameIndexResolution(), llvm::SIRegisterInfo::requiresFrameIndexReplacementScavenging(), llvm::SIRegisterInfo::requiresRegisterScavenging(), reservePrivateMemoryRegs(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
hasStackProtectorIndex()
bool llvm::MachineFrameInfo::hasStackProtectorIndex () const inline
Definition at line 355 of file MachineFrameInfo.h.
Referenced by AssignProtectedObjSet(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::MIRPrinter::convertStackObjects(), INITIALIZE_PASS(), and lookupCandidateBaseReg().
hasTailCall()
bool llvm::MachineFrameInfo::hasTailCall () const inline
Returns true if the function contains a tail call.
Definition at line 607 of file MachineFrameInfo.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), getUnderlyingObjectsForInstr(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
hasVarSizedObjects()
bool llvm::MachineFrameInfo::hasVarSizedObjects () const inline
This method may be called any time after instruction selection is complete to determine if the stack frame for this function contains any variable sized objects.
Definition at line 350 of file MachineFrameInfo.h.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), AdjustStackOffset(), AssignProtectedObjSet(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::ARMFrameLowering::canSimplifyCallFramePseudos(), CantUseSP(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AsmPrinter::emitStackSizeSection(), estimateStackSize(), getDwarfRegNum(), llvm::R600InstrInfo::getIndirectIndexEnd(), getLoadStoreOffsetAlign(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::LanaiRegisterInfo::hasBasePointer(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::MipsFrameLowering::hasBP(), llvm::RISCVFrameLowering::hasBP(), llvm::MipsFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), llvm::VEFrameLowering::hasFP(), llvm::WebAssemblyFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::AVRFrameLowering::hasReservedCallFrame(), llvm::SparcFrameLowering::hasReservedCallFrame(), llvm::Thumb1FrameLowering::hasReservedCallFrame(), llvm::Mips16FrameLowering::hasReservedCallFrame(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::VEFrameLowering::hasReservedCallFrame(), llvm::RISCVFrameLowering::hasReservedCallFrame(), llvm::WebAssemblyFrameLowering::hasReservedCallFrame(), llvm::MSP430FrameLowering::hasReservedCallFrame(), llvm::ARMFrameLowering::hasReservedCallFrame(), llvm::AArch64FrameLowering::hasReservedCallFrame(), llvm::X86FrameLowering::hasReservedCallFrame(), INITIALIZE_PASS(), llvm::HexagonFrameLowering::needsAligna(), llvm::PPCFrameLowering::needsFP(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AVRDynAllocaSR::runOnMachineFunction(), and llvm::HexagonDAGToDAGISel::SelectFrameIndex().
hasVAStart()
bool llvm::MachineFrameInfo::hasVAStart () const inline
Returns true if the function calls the llvm.va_start intrinsic.
Definition at line 599 of file MachineFrameInfo.h.
Referenced by llvm::MIRPrinter::convert(), isSortedByValueNo(), and LowerVASTART().
isAliasedObjectIndex()
bool llvm::MachineFrameInfo::isAliasedObjectIndex (int ObjectIdx) const inline
Returns true if the specified index corresponds to an object that might be pointed to by an LLVM IR value.
Definition at line 663 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::MIRPrinter::convertStackObjects(), and llvm::FixedStackPseudoSourceValue::isAliased().
isCalleeSavedInfoValid()
bool llvm::MachineFrameInfo::isCalleeSavedInfoValid () const inline
Has the callee saved info been calculated yet?
Definition at line 785 of file MachineFrameInfo.h.
Referenced by addCalleeSavedRegs(), llvm::LiveRegUnits::addLiveOuts(), llvm::LivePhysRegs::addLiveOutsNoPristines(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::TargetFrameLowering::getCalleeSaves(), llvm::AArch64InstrInfo::getOutliningType(), getPristineRegs(), getSVECalleeSaveSlotRange(), InsertLDR_STR(), and llvm::PPCRegisterInfo::requiresFrameIndexScavenging().
isDeadObjectIndex()
bool llvm::MachineFrameInfo::isDeadObjectIndex (int ObjectIdx) const inline
Returns true if the specified index corresponds to a dead object.
Definition at line 714 of file MachineFrameInfo.h.
References assert().
Referenced by AdjustStackOffset(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), AssignProtectedObjSet(), llvm::MIRPrinter::convertStackObjects(), llvm::StackProtector::copyToMachineFrameInfo(), determineSVEStackObjectOffsets(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), estimateStackSize(), INITIALIZE_PASS(), false::IntervalSorter::operator()(), and llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized().
isFixedObjectIndex()
bool llvm::MachineFrameInfo::isFixedObjectIndex (int ObjectIdx) const inline
Returns true if the specified index corresponds to a fixed stack object.
Definition at line 657 of file MachineFrameInfo.h.
Referenced by llvm::BaseIndexOffset::computeAliasing(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::MipsSEFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), getLoadStoreOffsetAlign(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetValue(), LowerAsSplatVectorLoad(), MatchingStackOffset(), printFrameIndex(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AVRFrameAnalyzer::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), shouldClusterFI(), shouldGuaranteeTCO(), and shouldUseZeroOffsetLdSt().
isFrameAddressTaken()
bool llvm::MachineFrameInfo::isFrameAddressTaken () const inline
This method may be called any time after instruction selection is complete to determine if there is a call to @llvm.frameaddress in this function.
Definition at line 365 of file MachineFrameInfo.h.
Referenced by llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::MIRPrinter::convert(), llvm::PPCFrameLowering::emitPrologue(), llvm::MipsFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), llvm::VEFrameLowering::hasFP(), llvm::WebAssemblyFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), and usePackedStack().
isImmutableObjectIndex()
bool llvm::MachineFrameInfo::isImmutableObjectIndex (int ObjectIdx) const inline
Returns true if the specified index corresponds to an immutable object.
Definition at line 670 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::MIRPrinter::convertStackObjects(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), llvm::FixedStackPseudoSourceValue::isConstant(), and MatchingStackOffset().
isMaxCallFrameSizeComputed()
bool llvm::MachineFrameInfo::isMaxCallFrameSizeComputed () const inline
Definition at line 630 of file MachineFrameInfo.h.
Referenced by llvm::MIRPrinter::convert(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::AArch64FrameLowering::hasFP(), llvm::AArch64Subtarget::mirFileLoaded(), and stashEntryDbgValues().
isObjectPreAllocated()
bool llvm::MachineFrameInfo::isObjectPreAllocated (int ObjectIdx) const inline
Return true if the object was pre-allocated into the local block.
Definition at line 443 of file MachineFrameInfo.h.
References assert().
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), INITIALIZE_PASS(), and lookupCandidateBaseReg().
isObjectSExt()
bool llvm::MachineFrameInfo::isObjectSExt (int ObjectIdx) const inline
Definition at line 511 of file MachineFrameInfo.h.
References assert().
Referenced by MatchingStackOffset().
isObjectZExt()
bool llvm::MachineFrameInfo::isObjectZExt (int ObjectIdx) const inline
Definition at line 499 of file MachineFrameInfo.h.
References assert().
Referenced by MatchingStackOffset().
isReturnAddressTaken()
bool llvm::MachineFrameInfo::isReturnAddressTaken () const inline
This method may be called any time after instruction selection is complete to determine if there is a call to @llvm.returnaddress in this function.
Definition at line 371 of file MachineFrameInfo.h.
Referenced by llvm::MIRPrinter::convert(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::Mips16FrameLowering::spillCalleeSavedRegisters(), and llvm::MipsSEFrameLowering::spillCalleeSavedRegisters().
isSpillSlotObjectIndex()
bool llvm::MachineFrameInfo::isSpillSlotObjectIndex (int ObjectIdx) const inline
Returns true if the specified index corresponds to a spill slot.
Definition at line 687 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::MIRPrinter::convertStackObjects(), llvm::MachineInstr::getRestoreSize(), llvm::MachineInstr::getSpillSize(), getSpillSlotSize(), llvm::FixedStackPseudoSourceValue::mayAlias(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
isStatepointSpillSlotObjectIndex()
bool llvm::MachineFrameInfo::isStatepointSpillSlotObjectIndex (int ObjectIdx) const inline
Definition at line 693 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::TargetLoweringBase::emitPatchPoint().
isVariableSizedObjectIndex()
bool llvm::MachineFrameInfo::isVariableSizedObjectIndex (int ObjectIdx) const inline
Returns true if the specified index corresponds to a variable sized object.
Definition at line 722 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::MIRPrinter::convertStackObjects(), and scavengeStackSlot().
mapLocalFrameObject()
void llvm::MachineFrameInfo::mapLocalFrameObject (int ObjectIndex, int64_t Offset) inline
Map a frame index into the local object block.
Definition at line 399 of file MachineFrameInfo.h.
References llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by INITIALIZE_PASS(), llvm::MIRParserImpl::initializeFrameInfo(), and llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized().
markAsStatepointSpillSlotObjectIndex()
void llvm::MachineFrameInfo::markAsStatepointSpillSlotObjectIndex (int ObjectIdx) inline
Definition at line 728 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::StatepointLoweringState::allocateStackSlot().
print()
void MachineFrameInfo::print (const MachineFunction & MF, raw_ostream & OS) const
Used by the MachineFunction printer to print information about stack objects.
Implemented in MachineFunction.cpp.
Definition at line 214 of file MachineFrameInfo.cpp.
References llvm::numbers::e, llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), and llvm::MachineFunction::getSubtarget().
Referenced by dump(), and llvm::MachineFunction::print().
RemoveStackObject()
void llvm::MachineFrameInfo::RemoveStackObject (int ObjectIdx) inline
Remove or mark dead a statically sized stack object.
Definition at line 757 of file MachineFrameInfo.h.
Referenced by getStartOrEndSlot(), false::IntervalSorter::operator()(), llvm::SIMachineFunctionInfo::removeDeadFrameIndices(), and tryToElideArgumentCopy().
setAdjustsStack()
void llvm::MachineFrameInfo::setAdjustsStack (bool V) inline
Definition at line 579 of file MachineFrameInfo.h.
Referenced by llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::ARMTargetLowering::getJumpTableEncoding(), GetTLSADDR(), getVectorSHLImm(), llvm::MIRParserImpl::initializeFrameInfo(), LowerToTLSExecModel(), mayTailCallThisCC(), and stashEntryDbgValues().
setCalleeSavedInfo()
void llvm::MachineFrameInfo::setCalleeSavedInfo (const std::vector< CalleeSavedInfo > & CSI) inline
Used by prolog/epilog inserter to set the function's callee saved information.
Definition at line 780 of file MachineFrameInfo.h.
Referenced by assignCalleeSavedSpillSlots(), and llvm::MIRParserImpl::initializeFrameInfo().
setCalleeSavedInfoValid()
void llvm::MachineFrameInfo::setCalleeSavedInfoValid (bool v) inline
Definition at line 787 of file MachineFrameInfo.h.
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), and insertCSRRestores().
setCVBytesOfCalleeSavedRegisters()
void llvm::MachineFrameInfo::setCVBytesOfCalleeSavedRegisters (unsigned S) inline
Definition at line 640 of file MachineFrameInfo.h.
References Size.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), and llvm::MIRParserImpl::initializeFrameInfo().
setFrameAddressIsTaken()
void llvm::MachineFrameInfo::setFrameAddressIsTaken (bool T) inline
Definition at line 366 of file MachineFrameInfo.h.
References llvm::T.
Referenced by callingConvSupported(), getComparePred(), getFRAMEADDR(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::ARCTargetLowering::isLegalAddressingMode(), llvm::PPCTargetLowering::isLegalAddressingMode(), lowerFABS64(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), LowerINTRINSIC_W_CHAIN(), LowerVASTART(), LowerVectorINT_TO_FP(), and mayTailCallThisCC().
setFunctionContextIndex()
void llvm::MachineFrameInfo::setFunctionContextIndex (int I) inline
Definition at line 360 of file MachineFrameInfo.h.
References I.
Referenced by FixedPointIntrinsicToOpcode().
setHasCalls()
void llvm::MachineFrameInfo::setHasCalls (bool V) inline
Definition at line 583 of file MachineFrameInfo.h.
Referenced by GetTLSADDR(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::makeAddress(), llvm::InstructionSelect::runOnMachineFunction(), and llvm::SelectionDAGISel::runOnMachineFunction().
setHasCopyImplyingStackAdjustment()
void llvm::MachineFrameInfo::setHasCopyImplyingStackAdjustment (bool B) inline
Definition at line 594 of file MachineFrameInfo.h.
References B.
Referenced by LowerINTRINSIC_W_CHAIN().
setHasMustTailInVarArgFunc()
void llvm::MachineFrameInfo::setHasMustTailInVarArgFunc (bool B) inline
Definition at line 604 of file MachineFrameInfo.h.
References B.
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), and llvm::FunctionLoweringInfo::set().
setHasOpaqueSPAdjustment()
void llvm::MachineFrameInfo::setHasOpaqueSPAdjustment (bool B) inline
Definition at line 587 of file MachineFrameInfo.h.
References B.
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), and llvm::FunctionLoweringInfo::set().
setHasPatchPoint()
void llvm::MachineFrameInfo::setHasPatchPoint (bool s = true) inline
Definition at line 384 of file MachineFrameInfo.h.
Referenced by llvm::MIRParserImpl::initializeFrameInfo().
setHasStackMap()
void llvm::MachineFrameInfo::setHasStackMap (bool s = true) inline
Definition at line 378 of file MachineFrameInfo.h.
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), and llvm::FastISel::selectStackmap().
setHasTailCall()
void llvm::MachineFrameInfo::setHasTailCall () inline
Definition at line 608 of file MachineFrameInfo.h.
Referenced by buildCallOperands(), CC_RISCV_FastCC(), llvm::ARMTargetLowering::CCAssignFnForReturn(), getCallOpcode(), getMOVL(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), and mayTailCallThisCC().
setHasVAStart()
void llvm::MachineFrameInfo::setHasVAStart (bool B) inline
Definition at line 600 of file MachineFrameInfo.h.
References B.
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), and llvm::FunctionLoweringInfo::set().
setIsImmutableObjectIndex()
void llvm::MachineFrameInfo::setIsImmutableObjectIndex (int ObjectIdx, bool IsImmutable) inline
Marks the immutability of an object.
Definition at line 680 of file MachineFrameInfo.h.
References assert().
Referenced by tryToElideArgumentCopy().
setLocalFrameMaxAlign()
void llvm::MachineFrameInfo::setLocalFrameMaxAlign (Align Alignment) inline
Required alignment of the local object blob, which is the strictest alignment of any object in it.
Definition at line 422 of file MachineFrameInfo.h.
Referenced by INITIALIZE_PASS(), and llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized().
setLocalFrameSize()
void llvm::MachineFrameInfo::setLocalFrameSize (int64_t sz) inline
Set the size of the local object blob.
Definition at line 415 of file MachineFrameInfo.h.
Referenced by INITIALIZE_PASS(), llvm::MIRParserImpl::initializeFrameInfo(), and llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized().
setMaxCallFrameSize()
void llvm::MachineFrameInfo::setMaxCallFrameSize (unsigned S) inline
Definition at line 633 of file MachineFrameInfo.h.
Referenced by llvm::PPCFrameLowering::determineFrameLayoutAndUpdate(), enableAllocFrameElim(), llvm::RISCVFrameLowering::hasBP(), llvm::MIRParserImpl::initializeFrameInfo(), and stashEntryDbgValues().
setObjectAlignment()
void llvm::MachineFrameInfo::setObjectAlignment (int ObjectIdx, unsigned Align) inline
setObjectAlignment - Change the alignment of the specified stack object.
Definition at line 471 of file MachineFrameInfo.h.
References assert(), and llvm::assumeAligned().
Referenced by determineSVEStackObjectOffsets(), emitAlignedDPRCS2Spills(), getContiguousRangeOfSetBits(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetValue(), getStartOrEndSlot(), llvm::MIRParserImpl::initializeFrameInfo(), LowerAsSplatVectorLoad(), false::IntervalSorter::operator()(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::FunctionLoweringInfo::set(), and shouldUseZeroOffsetLdSt().
setObjectOffset()
void llvm::MachineFrameInfo::setObjectOffset (int ObjectIdx, int64_t SPOffset) inline
Set the stack frame offset of the specified object.
The offset is relative to the stack pointer on entry to the function.
Definition at line 525 of file MachineFrameInfo.h.
References assert().
Referenced by AdjustStackOffset(), llvm::ARCFrameLowering::assignCalleeSavedSpillSlots(), AssignProtectedObjSet(), determineSVEStackObjectOffsets(), llvm::PPCFrameLowering::emitPrologue(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), and scavengeStackSlot().
setObjectSExt()
void llvm::MachineFrameInfo::setObjectSExt (int ObjectIdx, bool IsSExt) inline
Definition at line 517 of file MachineFrameInfo.h.
References assert().
Referenced by shouldGuaranteeTCO().
setObjectSize()
void llvm::MachineFrameInfo::setObjectSize (int ObjectIdx, int64_t Size) inline
Change the size of the specified stack object.
Definition at line 457 of file MachineFrameInfo.h.
References assert(), and Size.
Referenced by false::IntervalSorter::operator()().
setObjectSSPLayout()
void llvm::MachineFrameInfo::setObjectSSPLayout (int ObjectIdx, SSPLayoutKind Kind) inline
Definition at line 539 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::StackProtector::copyToMachineFrameInfo(), and getStartOrEndSlot().
setObjectZExt()
void llvm::MachineFrameInfo::setObjectZExt (int ObjectIdx, bool IsZExt) inline
Definition at line 505 of file MachineFrameInfo.h.
References assert().
Referenced by shouldGuaranteeTCO().
setOffsetAdjustment()
void llvm::MachineFrameInfo::setOffsetAdjustment (int Adj) inline
Set the correction for frame offsets.
Definition at line 562 of file MachineFrameInfo.h.
Referenced by llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), and llvm::MIRParserImpl::initializeFrameInfo().
setRestorePoint()
void llvm::MachineFrameInfo::setRestorePoint (MachineBasicBlock * NewRestore) inline
Definition at line 792 of file MachineFrameInfo.h.
References llvm::dump(), and print().
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), and stashEntryDbgValues().
setReturnAddressIsTaken()
void llvm::MachineFrameInfo::setReturnAddressIsTaken (bool s) inline
Definition at line 372 of file MachineFrameInfo.h.
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), llvm::PPCTargetLowering::isLegalAddressingMode(), lowerFABS64(), LowerINTRINSIC_W_CHAIN(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerVectorINT_TO_FP(), and llvm::SITargetLowering::shouldEmitPCReloc().
setSavePoint()
void llvm::MachineFrameInfo::setSavePoint (MachineBasicBlock * NewSave) inline
Definition at line 790 of file MachineFrameInfo.h.
Referenced by giveUpWithRemarks(), llvm::MIRParserImpl::initializeFrameInfo(), and stashEntryDbgValues().
setStackID()
void llvm::MachineFrameInfo::setStackID (int ObjectIdx, uint8_t ID) inline
See also
StackID
Definition at line 705 of file MachineFrameInfo.h.
References assert().
Referenced by llvm::MIRParserImpl::initializeFrameInfo(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::SIMachineFunctionInfo::removeDeadFrameIndices(), llvm::FunctionLoweringInfo::set(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), and llvm::AArch64InstrInfo::storeRegToStackSlot().
setStackProtectorIndex()
void llvm::MachineFrameInfo::setStackProtectorIndex (int I) inline
Definition at line 354 of file MachineFrameInfo.h.
References I.
Referenced by FixedPointIntrinsicToOpcode(), and llvm::MIRParserImpl::initializeFrameInfo().
setStackSize()
void llvm::MachineFrameInfo::setStackSize (uint64_t Size) inline
Set the size of the stack.
Definition at line 553 of file MachineFrameInfo.h.
References Size.
Referenced by AdjustStackOffset(), AssignProtectedObjSet(), llvm::PPCFrameLowering::determineFrameLayoutAndUpdate(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), enableAllocFrameElim(), llvm::RISCVFrameLowering::hasBP(), and llvm::MIRParserImpl::initializeFrameInfo().
setUseLocalStackAllocationBlock()
void llvm::MachineFrameInfo::setUseLocalStackAllocationBlock (bool v) inline
setUseLocalStackAllocationBlock - Set whether the local allocation blob should be allocated together or let PEI allocate the locals in it directly.
Definition at line 438 of file MachineFrameInfo.h.
Referenced by INITIALIZE_PASS(), and llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineFrameInfo.h
lib/CodeGen/MachineFrameInfo.cpp