LLVM: llvm::pdb::PDBSymDumper Class Reference
llvm::pdb::PDBSymDumper Class Reference
#include "llvm/DebugInfo/PDB/PDBSymDumper.h"
Public Member Functions
PDBSymDumper (bool ShouldRequireImpl)
virtual ~PDBSymDumper ()
virtual void dump (const PDBSymbolAnnotation &Symbol)
virtual void dump (const PDBSymbolBlock &Symbol)
virtual void dump (const PDBSymbolCompiland &Symbol)
virtual void dump (const PDBSymbolCompilandDetails &Symbol)
virtual void dump (const PDBSymbolCompilandEnv &Symbol)
virtual void dump (const PDBSymbolCustom &Symbol)
virtual void dump (const PDBSymbolData &Symbol)
virtual void dump (const PDBSymbolExe &Symbol)
virtual void dump (const PDBSymbolFunc &Symbol)
virtual void dump (const PDBSymbolFuncDebugEnd &Symbol)
virtual void dump (const PDBSymbolFuncDebugStart &Symbol)
virtual void dump (const PDBSymbolLabel &Symbol)
virtual void dump (const PDBSymbolPublicSymbol &Symbol)
virtual void dump (const PDBSymbolThunk &Symbol)
virtual void dump (const PDBSymbolTypeArray &Symbol)
virtual void dump (const PDBSymbolTypeBaseClass &Symbol)
virtual void dump (const PDBSymbolTypeBuiltin &Symbol)
virtual void dump (const PDBSymbolTypeCustom &Symbol)
virtual void dump (const PDBSymbolTypeDimension &Symbol)
virtual void dump (const PDBSymbolTypeEnum &Symbol)
virtual void dump (const PDBSymbolTypeFriend &Symbol)
virtual void dump (const PDBSymbolTypeFunctionArg &Symbol)
virtual void dump (const PDBSymbolTypeFunctionSig &Symbol)
virtual void dump (const PDBSymbolTypeManaged &Symbol)
virtual void dump (const PDBSymbolTypePointer &Symbol)
virtual void dump (const PDBSymbolTypeTypedef &Symbol)
virtual void dump (const PDBSymbolTypeUDT &Symbol)
virtual void dump (const PDBSymbolTypeVTable &Symbol)
virtual void dump (const PDBSymbolTypeVTableShape &Symbol)
virtual void dump (const PDBSymbolUnknown &Symbol)
virtual void dump (const PDBSymbolUsingNamespace &Symbol)
virtual void dumpRight (const PDBSymbolTypeArray &Symbol)
virtual void dumpRight (const PDBSymbolTypeBaseClass &Symbol)
virtual void dumpRight (const PDBSymbolTypeBuiltin &Symbol)
virtual void dumpRight (const PDBSymbolTypeCustom &Symbol)
virtual void dumpRight (const PDBSymbolTypeDimension &Symbol)
virtual void dumpRight (const PDBSymbolTypeEnum &Symbol)
virtual void dumpRight (const PDBSymbolTypeFriend &Symbol)
virtual void dumpRight (const PDBSymbolTypeFunctionArg &Symbol)
virtual void dumpRight (const PDBSymbolTypeFunctionSig &Symbol)
virtual void dumpRight (const PDBSymbolTypeManaged &Symbol)
virtual void dumpRight (const PDBSymbolTypePointer &Symbol)
virtual void dumpRight (const PDBSymbolTypeTypedef &Symbol)
virtual void dumpRight (const PDBSymbolTypeUDT &Symbol)
virtual void dumpRight (const PDBSymbolTypeVTable &Symbol)
virtual void dumpRight (const PDBSymbolTypeVTableShape &Symbol)
Detailed Description
Definition at line 19 of file PDBSymDumper.h.
Constructor & Destructor Documentation
PDBSymDumper()
PDBSymDumper::PDBSymDumper (bool ShouldRequireImpl)
Definition at line 19 of file PDBSymDumper.cpp.
References ~PDBSymDumper().
~PDBSymDumper()
PDBSymDumper::~PDBSymDumper () virtual default
Referenced by PDBSymDumper().
Member Function Documentation
dump() [1/31]
void PDBSymDumper::dump (const PDBSymbolAnnotation & Symbol) virtual
Definition at line 24 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
Referenced by llvm::pdb::PDBSymbolCompilandEnv::dump(), llvm::pdb::PDBSymbolAnnotation::dump(), llvm::pdb::PDBSymbolTypeVTableShape::dump(), llvm::pdb::PDBSymbolCompilandDetails::dump(), llvm::pdb::PDBSymbolTypeBuiltin::dump(), llvm::pdb::PDBSymbolTypeCustom::dump(), llvm::pdb::PDBSymbolTypePointer::dump(), llvm::pdb::PDBSymbolTypeDimension::dump(), llvm::pdb::PDBSymbolBlock::dump(), llvm::pdb::PDBSymbolTypeFriend::dump(), llvm::pdb::PDBSymbolFuncDebugStart::dump(), llvm::pdb::PDBSymbolTypeFunctionArg::dump(), llvm::pdb::PDBSymbolLabel::dump(), llvm::pdb::PDBSymbolPublicSymbol::dump(), llvm::pdb::PDBSymbolTypeManaged::dump(), llvm::pdb::PDBSymbolTypeTypedef::dump(), llvm::pdb::PDBSymbolTypeArray::dump(), llvm::pdb::PDBSymbolThunk::dump(), llvm::pdb::PDBSymbolTypeVTable::dump(), llvm::pdb::PDBSymbolCompiland::dump(), llvm::pdb::PDBSymbolUsingNamespace::dump(), llvm::pdb::PDBSymbolExe::dump(), llvm::pdb::PDBSymbolFuncDebugEnd::dump(), llvm::pdb::PDBSymbolData::dump(), llvm::pdb::PDBSymbolTypeFunctionSig::dump(), llvm::pdb::PDBSymbolTypeEnum::dump(), llvm::pdb::PDBSymbolTypeBaseClass::dump(), llvm::pdb::PDBSymbolFunc::dump(), llvm::pdb::PDBSymbolTypeUDT::dump(), and llvm::pdb::PDBSymbolCustom::dump().
dump() [2/31]
void PDBSymDumper::dump (const PDBSymbolBlock & Symbol) virtual
Definition at line 28 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [3/31]
void PDBSymDumper::dump (const PDBSymbolCompiland & Symbol) virtual
Definition at line 32 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [4/31]
void PDBSymDumper::dump (const PDBSymbolCompilandDetails & Symbol) virtual
Definition at line 36 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [5/31]
void PDBSymDumper::dump (const PDBSymbolCompilandEnv & Symbol) virtual
Definition at line 40 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [6/31]
void PDBSymDumper::dump (const PDBSymbolCustom & Symbol) virtual
Definition at line 44 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [7/31]
void PDBSymDumper::dump (const PDBSymbolData & Symbol) virtual
Definition at line 48 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [8/31]
void PDBSymDumper::dump (const PDBSymbolExe & Symbol) virtual
Definition at line 52 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [9/31]
void PDBSymDumper::dump (const PDBSymbolFunc & Symbol) virtual
Definition at line 56 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [10/31]
void PDBSymDumper::dump (const PDBSymbolFuncDebugEnd & Symbol) virtual
Definition at line 60 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [11/31]
void PDBSymDumper::dump (const PDBSymbolFuncDebugStart & Symbol) virtual
Definition at line 64 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [12/31]
void PDBSymDumper::dump (const PDBSymbolLabel & Symbol) virtual
Definition at line 68 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [13/31]
void PDBSymDumper::dump (const PDBSymbolPublicSymbol & Symbol) virtual
Definition at line 72 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [14/31]
void PDBSymDumper::dump (const PDBSymbolThunk & Symbol) virtual
Definition at line 76 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [15/31]
void PDBSymDumper::dump (const PDBSymbolTypeArray & Symbol) virtual
Definition at line 80 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [16/31]
void PDBSymDumper::dump (const PDBSymbolTypeBaseClass & Symbol) virtual
Definition at line 84 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [17/31]
void PDBSymDumper::dump (const PDBSymbolTypeBuiltin & Symbol) virtual
Definition at line 88 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [18/31]
void PDBSymDumper::dump (const PDBSymbolTypeCustom & Symbol) virtual
Definition at line 92 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [19/31]
void PDBSymDumper::dump (const PDBSymbolTypeDimension & Symbol) virtual
Definition at line 96 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [20/31]
void PDBSymDumper::dump (const PDBSymbolTypeEnum & Symbol) virtual
Definition at line 100 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [21/31]
void PDBSymDumper::dump (const PDBSymbolTypeFriend & Symbol) virtual
Definition at line 104 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [22/31]
void PDBSymDumper::dump (const PDBSymbolTypeFunctionArg & Symbol) virtual
Definition at line 108 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [23/31]
void PDBSymDumper::dump (const PDBSymbolTypeFunctionSig & Symbol) virtual
Definition at line 112 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [24/31]
void PDBSymDumper::dump (const PDBSymbolTypeManaged & Symbol) virtual
Definition at line 116 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [25/31]
void PDBSymDumper::dump (const PDBSymbolTypePointer & Symbol) virtual
Definition at line 120 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [26/31]
void PDBSymDumper::dump (const PDBSymbolTypeTypedef & Symbol) virtual
Definition at line 124 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [27/31]
void PDBSymDumper::dump (const PDBSymbolTypeUDT & Symbol) virtual
Definition at line 128 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [28/31]
void PDBSymDumper::dump (const PDBSymbolTypeVTable & Symbol) virtual
Definition at line 132 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [29/31]
void PDBSymDumper::dump (const PDBSymbolTypeVTableShape & Symbol) virtual
Definition at line 136 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [30/31]
void PDBSymDumper::dump (const PDBSymbolUnknown & Symbol) virtual
Definition at line 140 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dump() [31/31]
void PDBSymDumper::dump (const PDBSymbolUsingNamespace & Symbol) virtual
Definition at line 144 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
dumpRight() [1/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeArray & Symbol) inline virtual
Definition at line 56 of file PDBSymDumper.h.
Referenced by llvm::pdb::PDBSymbolTypeArray::dumpRight(), llvm::pdb::PDBSymbolTypePointer::dumpRight(), and llvm::pdb::PDBSymbolTypeFunctionSig::dumpRight().
dumpRight() [2/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeBaseClass & Symbol) inline virtual
Definition at line 57 of file PDBSymDumper.h.
dumpRight() [3/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeBuiltin & Symbol) inline virtual
Definition at line 58 of file PDBSymDumper.h.
dumpRight() [4/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeCustom & Symbol) inline virtual
Definition at line 59 of file PDBSymDumper.h.
dumpRight() [5/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeDimension & Symbol) inline virtual
Definition at line 60 of file PDBSymDumper.h.
dumpRight() [6/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeEnum & Symbol) inline virtual
Definition at line 61 of file PDBSymDumper.h.
dumpRight() [7/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeFriend & Symbol) inline virtual
Definition at line 62 of file PDBSymDumper.h.
dumpRight() [8/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeFunctionArg & Symbol) inline virtual
Definition at line 63 of file PDBSymDumper.h.
dumpRight() [9/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeFunctionSig & Symbol) inline virtual
Definition at line 64 of file PDBSymDumper.h.
dumpRight() [10/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeManaged & Symbol) inline virtual
Definition at line 65 of file PDBSymDumper.h.
dumpRight() [11/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypePointer & Symbol) inline virtual
Definition at line 66 of file PDBSymDumper.h.
dumpRight() [12/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeTypedef & Symbol) inline virtual
Definition at line 67 of file PDBSymDumper.h.
dumpRight() [13/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeUDT & Symbol) inline virtual
Definition at line 68 of file PDBSymDumper.h.
dumpRight() [14/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeVTable & Symbol) inline virtual
Definition at line 69 of file PDBSymDumper.h.
dumpRight() [15/15]
virtual void llvm::pdb::PDBSymDumper::dumpRight (const PDBSymbolTypeVTableShape & Symbol) inline virtual
Definition at line 70 of file PDBSymDumper.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/PDBSymDumper.h
lib/DebugInfo/PDB/PDBSymDumper.cpp