LLVM: llvm::DevirtSCCRepeatedPass< PassT > Class Template Reference
llvm::DevirtSCCRepeatedPass< PassT > Class Template Reference
A helper that repeats an SCC pass each time an indirect call is refined to a direct call by that pass.
#include "llvm/Analysis/CGSCCPassManager.h"
Public Member Functions
DevirtSCCRepeatedPass (PassT Pass, int MaxIterations)
PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Runs the wrapped pass up to MaxIterations on the SCC, iterating whenever an indirect call is refined.
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< DevirtSCCRepeatedPass< PassT > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
template<typename PassT>
class llvm::DevirtSCCRepeatedPass< PassT >
A helper that repeats an SCC pass each time an indirect call is refined to a direct call by that pass.
While the CGSCC pass manager works to re-visit SCCs and RefSCCs as they change shape, we may also want to repeat an SCC pass if it simply refines an indirect call to a direct call, even if doing so does not alter the shape of the graph. Note that this only pertains to direct calls to functions where IPO across the SCC may be able to compute more precise results. For intrinsics, we assume scalar optimizations already can fully reason about them.
This repetition has the potential to be very large however, as each one might refine a single call site. As a consequence, in practice we use an upper bound on the number of repetitions to limit things.
Definition at line 553 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
DevirtSCCRepeatedPass()
template<typename PassT > llvm::DevirtSCCRepeatedPass< PassT >::DevirtSCCRepeatedPass (PassT Pass, int MaxIterations) inline explicit
Definition at line 556 of file CGSCCPassManager.h.
Member Function Documentation
run()
template<typename PassT > PreservedAnalyses llvm::DevirtSCCRepeatedPass< PassT >::run (LazyCallGraph::SCC & InitialC, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR) inline
Runs the wrapped pass up to MaxIterations on the SCC, iterating whenever an indirect call is refined.
Definition at line 561 of file CGSCCPassManager.h.
References llvm::PreservedAnalyses::all(), llvm::any_of(), assert(), llvm::LazyCallGraph::SCC::begin(), C, llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::SmallVectorBase::empty(), llvm::LazyCallGraph::SCC::end(), F(), llvm::Value::getName(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::instructions(), llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::CGSCCUpdateResult::InvalidatedSCCs, LLVM_DEBUG, MaxIterations, N, Pass, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runAfterPassInvalidated(), llvm::PassInstrumentation::runBeforePass(), and llvm::CGSCCUpdateResult::UpdatedC.
The documentation for this class was generated from the following file:
include/llvm/Analysis/CGSCCPassManager.h