LLVM: llvm::yaml::Document Class Reference
llvm::yaml::Document Class Reference
A YAML Stream is a sequence of Documents.
#include "llvm/Support/YAMLParser.h"
Public Member Functions
Document (Stream &ParentStream)
Node * parseBlockNode ()
Root for parsing a node. Returns a single node.
bool skip ()
Finish parsing the current document and return true if there are more.
Node * getRoot ()
Parse and return the root level node.
const std::map< StringRef, StringRef > & getTagMap () const
Friends
class Node
class document_iterator
Detailed Description
A YAML Stream is a sequence of Documents.
A document contains a root node.
Definition at line 522 of file YAMLParser.h.
Constructor & Destructor Documentation
Document()
Document::Document (Stream & ParentStream)
Definition at line 2276 of file YAMLParser.cpp.
References llvm::yaml::Token::Kind, and llvm::yaml::Token::TK_DocumentStart.
Member Function Documentation
getRoot()
Node* llvm::yaml::Document::getRoot () inline
Parse and return the root level node.
Definition at line 534 of file YAMLParser.h.
Referenced by llvm::remarks::YAMLRemarkParser::parseRemark(), and skip().
getTagMap()
const std::map<StringRef, StringRef>& llvm::yaml::Document::getTagMap () const inline
Definition at line 540 of file YAMLParser.h.
parseBlockNode()
Node * Document::parseBlockNode ()
Root for parsing a node. Returns a single node.
Definition at line 2320 of file YAMLParser.cpp.
References llvm::StringRef::copy(), llvm::StringRef::drop_back(), llvm::StringRef::find_first_of(), llvm::yaml::Token::Kind, llvm_unreachable, llvm::StringRef::ltrim(), llvm::yaml::MappingNode::MT_Block, llvm::yaml::MappingNode::MT_Flow, llvm::yaml::MappingNode::MT_Inline, llvm::yaml::Token::Range, llvm::yaml::SequenceNode::ST_Block, llvm::yaml::SequenceNode::ST_Flow, llvm::yaml::SequenceNode::ST_Indentless, llvm::StringRef::substr(), llvm::yaml::Token::TK_Alias, llvm::yaml::Token::TK_Anchor, llvm::yaml::Token::TK_BlockEntry, llvm::yaml::Token::TK_BlockMappingStart, llvm::yaml::Token::TK_BlockScalar, llvm::yaml::Token::TK_BlockSequenceStart, llvm::yaml::Token::TK_DocumentEnd, llvm::yaml::Token::TK_DocumentStart, llvm::yaml::Token::TK_Error, llvm::yaml::Token::TK_FlowEntry, llvm::yaml::Token::TK_FlowMappingEnd, llvm::yaml::Token::TK_FlowMappingStart, llvm::yaml::Token::TK_FlowSequenceEnd, llvm::yaml::Token::TK_FlowSequenceStart, llvm::yaml::Token::TK_Key, llvm::yaml::Token::TK_Scalar, llvm::yaml::Token::TK_StreamEnd, llvm::yaml::Token::TK_Tag, llvm::yaml::Token::TK_TagDirective, llvm::yaml::Token::TK_VersionDirective, and llvm::yaml::Token::Value.
skip()
bool Document::skip ()
Finish parsing the current document and return true if there are more.
Return false otherwise.
Definition at line 2288 of file YAMLParser.cpp.
References llvm::StringRef::begin(), getRoot(), llvm::yaml::Token::Kind, llvm::yaml::Token::Range, llvm::yaml::Node::skip(), llvm::yaml::Token::TK_DocumentEnd, and llvm::yaml::Token::TK_StreamEnd.
Friends And Related Function Documentation
document_iterator
friend class document_iterator friend
Definition at line 544 of file YAMLParser.h.
Node
friend class Node friend
Definition at line 543 of file YAMLParser.h.
The documentation for this class was generated from the following files:
include/llvm/Support/YAMLParser.h
lib/Support/YAMLParser.cpp