LLVM: llvm::AMDGPUTargetELFStreamer Class Reference
llvm::AMDGPUTargetELFStreamer Class Reference final
#include "Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h"
Public Member Functions
AMDGPUTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
MCELFStreamer & getStreamer ()
void finish () override
void EmitDirectiveAMDGCNTarget (StringRef Target) override
void EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override
void EmitDirectiveHSACodeObjectISA (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override
void EmitAMDKernelCodeT (const amd_kernel_code_t &Header) override
void EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override
void emitAMDGPULDS (MCSymbol *Sym, unsigned Size, unsigned Align) override
bool EmitISAVersion (StringRef IsaVersionString) override
bool EmitHSAMetadata (msgpack::Document &HSAMetadata, bool Strict) override
bool EmitHSAMetadata (const AMDGPU::HSAMD::Metadata &HSAMetadata) override
bool EmitCodeEnd () override
void EmitAmdhsaKernelDescriptor (const MCSubtargetInfo &STI, StringRef KernelName, const amdhsa::kernel_descriptor_t &KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr, bool ReserveXNACK) override
Public Member Functions inherited from llvm::AMDGPUTargetStreamer
AMDGPUTargetStreamer (MCStreamer &S)
AMDGPUPALMetadata * getPALMetadata ()
virtual bool EmitHSAMetadataV2 (StringRef HSAMetadataString)
virtual bool EmitHSAMetadataV3 (StringRef HSAMetadataString)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
Additional Inherited Members
Static Public Member Functions inherited from llvm::AMDGPUTargetStreamer
static StringRef getArchNameFromElfMach (unsigned ElfMach)
static unsigned getElfMach (StringRef GPU)
Protected Member Functions inherited from llvm::AMDGPUTargetStreamer
MCContext & getContext () const
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 134 of file AMDGPUTargetStreamer.h.
Constructor & Destructor Documentation
AMDGPUTargetELFStreamer()
AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 396 of file AMDGPUTargetStreamer.cpp.
References llvm::ELF::EF_AMDGPU_MACH, llvm::ELF::EF_AMDGPU_SRAM_ECC, llvm::ELF::EF_AMDGPU_XNACK, llvm::MCObjectStreamer::getAssembler(), llvm::MCSubtargetInfo::getCPU(), llvm::MCAssembler::getELFHeaderEFlags(), llvm::AMDGPUTargetStreamer::getElfMach(), getStreamer(), llvm::AMDGPU::hasSRAMECC(), llvm::AMDGPU::hasXNACK(), and llvm::MCAssembler::setELFHeaderEFlags().
Member Function Documentation
emitAMDGPULDS()
void AMDGPUTargetELFStreamer::emitAMDGPULDS (MCSymbol * Sym, unsigned Size, unsigned Align) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 509 of file AMDGPUTargetStreamer.cpp.
References assert(), llvm::MCConstantExpr::create(), llvm::MCSymbol::declareCommon(), llvm::AMDGPUTargetStreamer::getContext(), llvm::MCSymbol::getName(), llvm::MCSymbolELF::isBindingSet(), llvm::isPowerOf2_32(), llvm::report_fatal_error(), llvm::MCSymbolELF::setBinding(), llvm::MCSymbol::setExternal(), llvm::MCSymbol::setIndex(), llvm::MCSymbolELF::setSize(), llvm::MCSymbolELF::setType(), llvm::ELF::SHN_AMDGPU_LDS, llvm::ELF::STB_GLOBAL, llvm::ELF::STT_OBJECT, and llvm::ARMBuildAttrs::Symbol.
EmitAMDGPUSymbolType()
void AMDGPUTargetELFStreamer::EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 502 of file AMDGPUTargetStreamer.cpp.
References llvm::MCStreamer::getContext(), llvm::MCContext::getOrCreateSymbol(), getStreamer(), llvm::MCSymbolELF::setType(), and llvm::ARMBuildAttrs::Symbol.
EmitAmdhsaKernelDescriptor()
void AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor (const MCSubtargetInfo & STI, StringRef KernelName, const amdhsa::kernel_descriptor_t & KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr, bool ReserveXNACK) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 612 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), llvm::MCSymbolELF::getBinding(), llvm::MCStreamer::getContext(), llvm::MCSymbolELF::getOther(), getStreamer(), llvm::MCSymbolELF::getVisibility(), llvm::amdhsa::kernel_descriptor_t::kernel_code_entry_byte_offset, offsetof, llvm::MCSymbolELF::setBinding(), llvm::MCSymbolELF::setVisibility(), llvm::ELF::STT_OBJECT, llvm::ELF::STV_DEFAULT, llvm::ELF::STV_PROTECTED, llvm::MCSymbolRefExpr::VK_AMDGPU_REL64, and llvm::MCSymbolRefExpr::VK_None.
EmitAMDKernelCodeT()
void AMDGPUTargetELFStreamer::EmitAMDKernelCodeT (const amd_kernel_code_t & Header) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 494 of file AMDGPUTargetStreamer.cpp.
References llvm::MCStreamer::EmitBytes(), getStreamer(), llvm::MCStreamer::PopSection(), and llvm::MCStreamer::PushSection().
EmitCodeEnd()
bool AMDGPUTargetELFStreamer::EmitCodeEnd () override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 600 of file AMDGPUTargetStreamer.cpp.
References llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitValueToAlignment(), getStreamer(), I, llvm::MCStreamer::PopSection(), and llvm::MCStreamer::PushSection().
EmitDirectiveAMDGCNTarget()
void AMDGPUTargetELFStreamer::EmitDirectiveAMDGCNTarget (StringRef Target) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 454 of file AMDGPUTargetStreamer.cpp.
EmitDirectiveHSACodeObjectISA()
void AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectISA (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 467 of file AMDGPUTargetStreamer.cpp.
References llvm::MCConstantExpr::create(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::AMDGPUTargetStreamer::getContext(), AMDGPU::ElfNote::NoteNameV2, AMDGPU::ElfNote::NT_AMDGPU_HSA_ISA, and llvm::StringRef::size().
EmitDirectiveHSACodeObjectVersion()
void AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 456 of file AMDGPUTargetStreamer.cpp.
References llvm::MCConstantExpr::create(), llvm::MCStreamer::EmitIntValue(), llvm::AMDGPUTargetStreamer::getContext(), AMDGPU::ElfNote::NoteNameV2, and AMDGPU::ElfNote::NT_AMDGPU_HSA_CODE_OBJECT_VERSION.
EmitHSAMetadata() [1/2]
bool AMDGPUTargetELFStreamer::EmitHSAMetadata (msgpack::Document & HSAMetadata, bool Strict) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 549 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCELFStreamer::EmitLabel(), llvm::AMDGPUTargetStreamer::getContext(), llvm::msgpack::Document::getRoot(), AMDGPU::ElfNote::NoteNameV3, llvm::ELF::NT_AMDGPU_METADATA, Verifier, llvm::AMDGPU::HSAMD::V3::MetadataVerifier::verify(), and llvm::msgpack::Document::writeToBlob().
EmitHSAMetadata() [2/2]
bool AMDGPUTargetELFStreamer::EmitHSAMetadata (const AMDGPU::HSAMD::Metadata & HSAMetadata) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 576 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCELFStreamer::EmitLabel(), llvm::AMDGPUTargetStreamer::getContext(), AMDGPU::ElfNote::NoteNameV2, llvm::ELF::NT_AMD_AMDGPU_HSA_METADATA, and llvm::wasm::toString().
EmitISAVersion()
bool AMDGPUTargetELFStreamer::EmitISAVersion (StringRef IsaVersionString) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 530 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCELFStreamer::EmitLabel(), llvm::AMDGPUTargetStreamer::getContext(), AMDGPU::ElfNote::NoteNameV2, and llvm::ELF::NT_AMD_AMDGPU_ISA.
finish()
void AMDGPUTargetELFStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 422 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCConstantExpr::create(), llvm::MCObjectStreamer::EmitBytes(), llvm::AMDGPUTargetStreamer::getContext(), llvm::AMDGPUTargetStreamer::getPALMetadata(), getStreamer(), llvm::AMDGPUPALMetadata::getType(), llvm::AMDGPUPALMetadata::getVendor(), Name, AMDGPU::ElfNote::SectionName, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOTE, llvm::StringRef::size(), and llvm::AMDGPUPALMetadata::toBlob().
getStreamer()
MCELFStreamer & AMDGPUTargetELFStreamer::getStreamer ()
Definition at line 416 of file AMDGPUTargetStreamer.cpp.
Referenced by AMDGPUTargetELFStreamer(), EmitAMDGPUSymbolType(), EmitAmdhsaKernelDescriptor(), EmitAMDKernelCodeT(), EmitCodeEnd(), and finish().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.cpp