LLVM: llvm::pdb::NativeEnumTypes Class Reference
llvm::pdb::NativeEnumTypes Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeEnumTypes.h"
Public Member Functions
NativeEnumTypes (NativeSession &Session, codeview::LazyRandomTypeCollection &TypeCollection, std::vector< codeview::TypeLeafKind > Kinds)
NativeEnumTypes (NativeSession &Session, std::vector< codeview::TypeIndex > Indices)
uint32_t getChildCount () const override
std::unique_ptr< PDBSymbol > getChildAtIndex (uint32_t Index) const override
std::unique_ptr< PDBSymbol > getNext () override
void reset () override
Public Member Functions inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
virtual ~IPDBEnumChildren ()=default
Additional Inherited Members
Public Types inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
using ChildTypePtr = std::unique_ptr< PDBSymbol >
using MyType = IPDBEnumChildren< PDBSymbol >
Detailed Description
Definition at line 24 of file NativeEnumTypes.h.
Constructor & Destructor Documentation
NativeEnumTypes() [1/2]
NativeEnumTypes::NativeEnumTypes (NativeSession & Session, codeview::LazyRandomTypeCollection & TypeCollection, std::vector< codeview::TypeLeafKind > Kinds)
Definition at line 23 of file NativeEnumTypes.cpp.
References llvm::codeview::LazyRandomTypeCollection::getFirst(), llvm::codeview::getModifiedType(), llvm::codeview::LazyRandomTypeCollection::getNext(), llvm::codeview::LazyRandomTypeCollection::getType(), llvm::is_contained(), llvm::codeview::TypeIndex::isSimple(), llvm::codeview::isUdtForwardRef(), and llvm::codeview::CVRecord< Kind >::kind().
NativeEnumTypes() [2/2]
NativeEnumTypes::NativeEnumTypes (NativeSession & Session, std::vector< codeview::TypeIndex > Indices)
Definition at line 50 of file NativeEnumTypes.cpp.
Member Function Documentation
getChildAtIndex()
std::unique_ptr< PDBSymbol > NativeEnumTypes::getChildAtIndex (uint32_t Index) const override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 58 of file NativeEnumTypes.cpp.
References llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::pdb::SymbolCache::getSymbolById(), and llvm::pdb::NativeSession::getSymbolCache().
Referenced by getNext().
getChildCount()
uint32_t NativeEnumTypes::getChildCount () const override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 54 of file NativeEnumTypes.cpp.
getNext()
std::unique_ptr< PDBSymbol > NativeEnumTypes::getNext () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 66 of file NativeEnumTypes.cpp.
References getChildAtIndex().
reset()
void NativeEnumTypes::reset () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 70 of file NativeEnumTypes.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeEnumTypes.h
lib/DebugInfo/PDB/Native/NativeEnumTypes.cpp