LLVM: llvm::SCEVAAResult Class Reference
llvm::SCEVAAResult Class Reference
A simple alias analysis implementation that uses ScalarEvolution to answer queries.
#include "llvm/Analysis/ScalarEvolutionAliasAnalysis.h"
Public Member Functions
SCEVAAResult (ScalarEvolution &SE)
SCEVAAResult (SCEVAAResult &&Arg)
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
Public Member Functions inherited from llvm::AAResultBase< SCEVAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< SCEVAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
A simple alias analysis implementation that uses ScalarEvolution to answer queries.
Definition at line 26 of file ScalarEvolutionAliasAnalysis.h.
Constructor & Destructor Documentation
SCEVAAResult() [1/2]
llvm::SCEVAAResult::SCEVAAResult (ScalarEvolution & SE) inline explicit
Definition at line 30 of file ScalarEvolutionAliasAnalysis.h.
Referenced by llvm::SCEVAA::run().
SCEVAAResult() [2/2]
llvm::SCEVAAResult::SCEVAAResult (SCEVAAResult && Arg) inline
Definition at line 31 of file ScalarEvolutionAliasAnalysis.h.
References alias().
Member Function Documentation
alias()
AliasResult SCEVAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 25 of file ScalarEvolutionAliasAnalysis.cpp.
References llvm::MemoryLocation::AATags, llvm::AAResultBase< DerivedT >::alias(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getSCEV(), llvm::SCEV::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ConstantRange::getUnsignedMax(), llvm::ConstantRange::getUnsignedMin(), llvm::ScalarEvolution::getUnsignedRange(), llvm::LocationSize::getValue(), llvm::LocationSize::hasValue(), llvm::Type::isPointerTy(), llvm::LocationSize::isZero(), llvm::MustAlias, llvm::NoAlias, llvm::MemoryLocation::Ptr, llvm::MemoryLocation::Size, llvm::LocationSize::unknown(), and llvm::MemoryLocation::UnknownSize.
Referenced by SCEVAAResult().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolutionAliasAnalysis.h
lib/Analysis/ScalarEvolutionAliasAnalysis.cpp