LLVM: llvm::AAResultBase< DerivedT >::AAResultsProxy Class Reference
llvm::AAResultBase< DerivedT >::AAResultsProxy Class Reference
This proxy class models a common pattern where we delegate to either the top-level AAResults aggregation if one is registered, or to the current result if none are registered.
#include "llvm/Analysis/AliasAnalysis.h"
Public Member Functions
AAResultsProxy (AAResults *AAR, DerivedT &CurrentResult)
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Detailed Description
template<typename DerivedT>
class llvm::AAResultBase< DerivedT >::AAResultsProxy
This proxy class models a common pattern where we delegate to either the top-level AAResults aggregation if one is registered, or to the current result if none are registered.
Definition at line 965 of file AliasAnalysis.h.
Constructor & Destructor Documentation
AAResultsProxy()
template<typename DerivedT> llvm::AAResultBase< DerivedT >::AAResultsProxy::AAResultsProxy (AAResults * AAR, DerivedT & CurrentResult) inline
Definition at line 970 of file AliasAnalysis.h.
Member Function Documentation
alias()
template<typename DerivedT> AliasResult llvm::AAResultBase< DerivedT >::AAResultsProxy::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI) inline
Definition at line 973 of file AliasAnalysis.h.
References llvm::AAResults::alias().
Referenced by llvm::BasicAAResult::getModRefInfo(), and MergeAliasResults().
getArgModRefInfo()
template<typename DerivedT> ModRefInfo llvm::AAResultBase< DerivedT >::AAResultsProxy::getArgModRefInfo (const CallBase * Call, unsigned ArgIdx) inline
Definition at line 985 of file AliasAnalysis.h.
References llvm::AAResults::getArgModRefInfo().
getModRefBehavior() [1/2]
template<typename DerivedT> FunctionModRefBehavior llvm::AAResultBase< DerivedT >::AAResultsProxy::getModRefBehavior (const CallBase * Call) inline
Definition at line 990 of file AliasAnalysis.h.
References llvm::AAResults::getModRefBehavior().
Referenced by llvm::BasicAAResult::getModRefBehavior().
getModRefBehavior() [2/2]
template<typename DerivedT> FunctionModRefBehavior llvm::AAResultBase< DerivedT >::AAResultsProxy::getModRefBehavior (const Function * F) inline
Definition at line 995 of file AliasAnalysis.h.
References llvm::AAResults::getModRefBehavior().
getModRefInfo() [1/2]
template<typename DerivedT> ModRefInfo llvm::AAResultBase< DerivedT >::AAResultsProxy::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI) inline
Definition at line 999 of file AliasAnalysis.h.
References llvm::AAResults::getModRefInfo().
getModRefInfo() [2/2]
template<typename DerivedT> ModRefInfo llvm::AAResultBase< DerivedT >::AAResultsProxy::getModRefInfo (const CallBase * Call1, const CallBase * Call2, AAQueryInfo & AAQI) inline
Definition at line 1005 of file AliasAnalysis.h.
References llvm::AAResults::getModRefInfo().
pointsToConstantMemory()
template<typename DerivedT> bool llvm::AAResultBase< DerivedT >::AAResultsProxy::pointsToConstantMemory (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool OrLocal) inline
Definition at line 979 of file AliasAnalysis.h.
References llvm::AAResults::pointsToConstantMemory().
The documentation for this class was generated from the following file:
include/llvm/Analysis/AliasAnalysis.h