LLVM: llvm::HexagonCVIResource Class Reference
llvm::HexagonCVIResource Class Reference
#include "Target/Hexagon/MCTargetDesc/HexagonShuffler.h"
Public Types
using UnitsAndLanes = std::pair< unsigned, unsigned >
using TypeUnitsAndLanes = DenseMap< unsigned, UnitsAndLanes >
Public Member Functions
HexagonCVIResource (TypeUnitsAndLanes *TUL, MCInstrInfo const &MCII, unsigned s, MCInst const *id)
bool isValid () const
unsigned getLanes () const
bool mayLoad () const
bool mayStore () const
Public Member Functions inherited from llvm::HexagonResource
HexagonResource (unsigned s)
void setUnits (unsigned s)
unsigned setWeight (unsigned s)
unsigned getUnits () const
unsigned getWeight () const
Static Public Member Functions
static void SetupTUL (TypeUnitsAndLanes *TUL, StringRef CPU)
Static Public Member Functions inherited from llvm::HexagonResource
static bool lessUnits (const HexagonResource &A, const HexagonResource &B)
static bool lessWeight (const HexagonResource &A, const HexagonResource &B)
Detailed Description
Definition at line 65 of file HexagonShuffler.h.
Member Typedef Documentation
TypeUnitsAndLanes
using llvm::HexagonCVIResource::TypeUnitsAndLanes = DenseMap<unsigned, UnitsAndLanes>
Definition at line 68 of file HexagonShuffler.h.
UnitsAndLanes
using llvm::HexagonCVIResource::UnitsAndLanes = std::pair<unsigned, unsigned>
Definition at line 67 of file HexagonShuffler.h.
Constructor & Destructor Documentation
HexagonCVIResource()
HexagonCVIResource::HexagonCVIResource (TypeUnitsAndLanes * TUL, MCInstrInfo const & MCII, unsigned s, MCInst const * id)
Definition at line 144 of file HexagonShuffler.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), first, llvm::HexagonMCInstrInfo::getDesc(), llvm::HexagonMCInstrInfo::getType(), mayLoad(), mayStore(), second, and llvm::HexagonResource::setUnits().
Member Function Documentation
getLanes()
unsigned llvm::HexagonCVIResource::getLanes () const inline
Definition at line 99 of file HexagonShuffler.h.
isValid()
bool llvm::HexagonCVIResource::isValid () const inline
Definition at line 98 of file HexagonShuffler.h.
mayLoad()
bool llvm::HexagonCVIResource::mayLoad () const inline
Definition at line 100 of file HexagonShuffler.h.
References llvm::SPII::Load.
Referenced by HexagonCVIResource().
mayStore()
bool llvm::HexagonCVIResource::mayStore () const inline
Definition at line 101 of file HexagonShuffler.h.
References llvm::SPII::Store.
Referenced by HexagonCVIResource().
SetupTUL()
void HexagonCVIResource::SetupTUL (TypeUnitsAndLanes * TUL, StringRef CPU) static
Definition at line 108 of file HexagonShuffler.cpp.
References llvm::HexagonII::TypeCVI_4SLOT_MPY, llvm::HexagonII::TypeCVI_GATHER, llvm::HexagonII::TypeCVI_HIST, llvm::HexagonII::TypeCVI_SCATTER, llvm::HexagonII::TypeCVI_SCATTER_DV, llvm::HexagonII::TypeCVI_SCATTER_NEW_ST, llvm::HexagonII::TypeCVI_VA, llvm::HexagonII::TypeCVI_VA_DV, llvm::HexagonII::TypeCVI_VINLANESAT, llvm::HexagonII::TypeCVI_VM_LD, llvm::HexagonII::TypeCVI_VM_NEW_ST, llvm::HexagonII::TypeCVI_VM_ST, llvm::HexagonII::TypeCVI_VM_STU, llvm::HexagonII::TypeCVI_VM_TMP_LD, llvm::HexagonII::TypeCVI_VM_VP_LDU, llvm::HexagonII::TypeCVI_VP, llvm::HexagonII::TypeCVI_VP_VS, llvm::HexagonII::TypeCVI_VS, llvm::HexagonII::TypeCVI_VS_VX, llvm::HexagonII::TypeCVI_VX, llvm::HexagonII::TypeCVI_VX_DV, llvm::HexagonII::TypeCVI_VX_LATE, and llvm::HexagonII::TypeCVI_ZW.
Referenced by llvm::HexagonShuffler::HexagonShuffler().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonShuffler.h
lib/Target/Hexagon/MCTargetDesc/HexagonShuffler.cpp