LLVM: llvm::IVUsers Class Reference
llvm::IVUsers Class Reference
#include "llvm/Analysis/IVUsers.h"
Public Types
typedef ilist< IVStrideUse >::iterator iterator
typedef ilist< IVStrideUse >::const_iterator const_iterator
Public Member Functions
IVUsers (Loop *L, AssumptionCache *AC, LoopInfo *LI, DominatorTree *DT, ScalarEvolution *SE)
IVUsers (IVUsers &&X)
IVUsers (const IVUsers &)=delete
IVUsers & operator= (IVUsers &&)=delete
IVUsers & operator= (const IVUsers &)=delete
Loop * getLoop () const
bool AddUsersIfInteresting (Instruction *I)
AddUsersIfInteresting - Inspect the specified Instruction.
IVStrideUse & AddUser (Instruction *User, Value *Operand)
const SCEV * getReplacementExpr (const IVStrideUse &IU) const
getReplacementExpr - Return a SCEV expression which computes the value of the OperandValToReplace of the given IVStrideUse.
const SCEV * getExpr (const IVStrideUse &IU) const
getExpr - Return the expression for the use.
const SCEV * getStride (const IVStrideUse &IU, const Loop *L) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
bool isIVUserOrOperand (Instruction *Inst) const
void releaseMemory ()
void print (raw_ostream &OS, const Module *=nullptr) const
void dump () const
dump - This method is used for debugging.
Protected Member Functions
bool AddUsersImpl (Instruction *I, SmallPtrSetImpl< Loop *> &SimpleLoopNests)
AddUsersImpl - Inspect the specified instruction.
Friends
class IVStrideUse
Detailed Description
Definition at line 93 of file IVUsers.h.
Member Typedef Documentation
const_iterator
typedef ilist<IVStrideUse>::const_iterator llvm::IVUsers::const_iterator
Definition at line 143 of file IVUsers.h.
iterator
typedef ilist<IVStrideUse>::iterator llvm::IVUsers::iterator
Definition at line 142 of file IVUsers.h.
Constructor & Destructor Documentation
IVUsers() [1/3]
IVUsers::IVUsers (Loop * L, AssumptionCache * AC, LoopInfo * LI, DominatorTree * DT, ScalarEvolution * SE)
Definition at line 305 of file IVUsers.cpp.
References AddUsersIfInteresting(), llvm::BasicBlock::begin(), llvm::CodeMetrics::collectEphemeralValues(), llvm::LoopBase< BlockT, LoopT >::getHeader(), and I.
IVUsers() [2/3]
llvm::IVUsers::IVUsers (IVUsers && X) inline
Definition at line 113 of file IVUsers.h.
References llvm::IVStrideUse::IVUsers, and llvm::CallbackVH::operator=().
IVUsers() [3/3]
llvm::IVUsers::IVUsers (const IVUsers &) delete
Member Function Documentation
AddUser()
IVStrideUse & IVUsers::AddUser (Instruction * User, Value * Operand)
Definition at line 300 of file IVUsers.cpp.
AddUsersIfInteresting()
bool IVUsers::AddUsersIfInteresting (Instruction * I)
AddUsersIfInteresting - Inspect the specified Instruction.
If it is a reducible SCEV, recursively add its users to the IVUsesByStride set and return true. Otherwise, return false.
Definition at line 291 of file IVUsers.cpp.
Referenced by IVUsers().
AddUsersImpl()
bool IVUsers::AddUsersImpl (Instruction * I, SmallPtrSetImpl< Loop *> & SimpleLoopNests) protected
AddUsersImpl - Inspect the specified instruction.
If it is a reducible SCEV, recursively add its users to the IVUsesByStride set and return true. Otherwise, return false.
Definition at line 168 of file IVUsers.cpp.
References llvm::dbgs(), llvm::denormalizeForPostIncUse(), llvm::Module::getDataLayout(), llvm::PHINode::getIncomingValueNumForOperand(), llvm::Instruction::getModule(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), isInteresting(), llvm::DataLayout::isLegalInteger(), llvm::isSafeToSpeculativelyExecute(), isSimplifiedLoopNest(), IVUseShouldUsePostIncValue(), LLVM_DEBUG, llvm::normalizeForPostIncUseIf(), and llvm::Value::uses().
begin() [1/2]
iterator llvm::IVUsers::begin () inline
Definition at line 144 of file IVUsers.h.
begin() [2/2]
const_iterator llvm::IVUsers::begin () const inline
Definition at line 146 of file IVUsers.h.
dump()
LLVM_DUMP_METHOD void IVUsers::dump () const
dump - This method is used for debugging.
Definition at line 346 of file IVUsers.cpp.
References llvm::dbgs(), and print().
empty()
bool llvm::IVUsers::empty () const inline
Definition at line 148 of file IVUsers.h.
Referenced by mayUsePostIncMode().
end() [1/2]
iterator llvm::IVUsers::end () inline
Definition at line 145 of file IVUsers.h.
end() [2/2]
const_iterator llvm::IVUsers::end () const inline
Definition at line 147 of file IVUsers.h.
getExpr()
const SCEV * IVUsers::getExpr (const IVStrideUse & IU) const
getExpr - Return the expression for the use.
Definition at line 390 of file IVUsers.cpp.
References llvm::IVStrideUse::getPostIncLoops(), and llvm::normalizeForPostIncUse().
getLoop()
Loop* llvm::IVUsers::getLoop () const inline
Definition at line 124 of file IVUsers.h.
References llvm::HexagonMCInstrInfo::getExpr(), and I.
getReplacementExpr()
const SCEV * IVUsers::getReplacementExpr (const IVStrideUse & IU) const
getReplacementExpr - Return a SCEV expression which computes the value of the OperandValToReplace of the given IVStrideUse.
getReplacementExpr - Return a SCEV expression which computes the value of the OperandValToReplace.
Definition at line 385 of file IVUsers.cpp.
References llvm::IVStrideUse::getOperandValToReplace().
Referenced by print().
getStride()
const SCEV * IVUsers::getStride (const IVStrideUse & IU, const Loop * L) const
Definition at line 412 of file IVUsers.cpp.
References findAddRecForLoop(), and llvm::HexagonMCInstrInfo::getExpr().
isIVUserOrOperand()
bool llvm::IVUsers::isIVUserOrOperand (Instruction * Inst) const inline
Definition at line 150 of file IVUsers.h.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::createIVUsersPass(), llvm::dump(), and print().
operator=() [1/2]
IVUsers& llvm::IVUsers::operator= (IVUsers &&) delete
operator=() [2/2]
IVUsers& llvm::IVUsers::operator= (const IVUsers &) delete
print()
void IVUsers::print (raw_ostream & OS, const Module * M = nullptr) const
Definition at line 319 of file IVUsers.cpp.
References llvm::ScalarEvolution::getBackedgeTakenCount(), llvm::LoopBase< BlockT, LoopT >::getHeader(), getReplacementExpr(), llvm::ScalarEvolution::hasLoopInvariantBackedgeTakenCount(), and llvm::Value::printAsOperand().
Referenced by dump().
releaseMemory()
void IVUsers::releaseMemory ()
Definition at line 349 of file IVUsers.cpp.
Friends And Related Function Documentation
IVStrideUse
friend class IVStrideUse friend
Definition at line 94 of file IVUsers.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/IVUsers.h
lib/Analysis/IVUsers.cpp