LLVM: llvm::opt::Arg Class Reference
llvm::opt::Arg Class Reference
A concrete instance of a particular driver option.
#include "llvm/Option/Arg.h"
Public Member Functions
Arg (const Option Opt, StringRef Spelling, unsigned Index, const Arg *BaseArg=nullptr)
Arg (const Option Opt, StringRef Spelling, unsigned Index, const char *Value0, const Arg *BaseArg=nullptr)
Arg (const Option Opt, StringRef Spelling, unsigned Index, const char *Value0, const char *Value1, const Arg *BaseArg=nullptr)
Arg (const Arg &)=delete
Arg & operator= (const Arg &)=delete
~Arg ()
const Option & getOption () const
StringRef getSpelling () const
Returns the used prefix and name of the option: For --foo=bar, returns --foo=.
unsigned getIndex () const
const Arg & getBaseArg () const
Return the base argument which generated this arg.
void setBaseArg (const Arg *BaseArg)
const Arg * getAlias () const
Args are converted to their unaliased form.
void setAlias (std::unique_ptr< Arg > Alias)
bool getOwnsValues () const
void setOwnsValues (bool Value) const
bool isClaimed () const
void claim () const
Set the Arg claimed bit.
unsigned getNumValues () const
const char * getValue (unsigned N=0) const
SmallVectorImpl< const char * > & getValues ()
const SmallVectorImpl< const char * > & getValues () const
bool containsValue (StringRef Value) const
void render (const ArgList &Args, ArgStringList &Output) const
Append the argument onto the given array as strings.
void renderAsInput (const ArgList &Args, ArgStringList &Output) const
Append the argument, render as an input, onto the given array as strings.
void print (raw_ostream &O) const
void dump () const
std::string getAsString (const ArgList &Args) const
Return a formatted version of the argument and its values, for diagnostics.
Detailed Description
A concrete instance of a particular driver option.
The Arg class encodes just enough information to be able to derive the argument values efficiently.
Definition at line 34 of file Arg.h.
Constructor & Destructor Documentation
Arg() [1/4]
Arg::Arg (const Option Opt, StringRef Spelling, unsigned Index, const Arg * BaseArg = nullptr)
Definition at line 21 of file Arg.cpp.
Arg() [2/4]
Arg::Arg (const Option Opt, StringRef Spelling, unsigned Index, const char * Value0, const Arg * BaseArg = nullptr)
Definition at line 25 of file Arg.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Arg() [3/4]
Arg::Arg (const Option Opt, StringRef Spelling, unsigned Index, const char * Value0, const char * Value1, const Arg * BaseArg = nullptr)
Definition at line 32 of file Arg.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Arg() [4/4]
llvm::opt::Arg::Arg (const Arg &) delete
~Arg()
Arg::~Arg ()
Definition at line 40 of file Arg.cpp.
References llvm::numbers::e, and llvm::SmallVectorBase::size().
Member Function Documentation
claim()
void llvm::opt::Arg::claim () const inline
Set the Arg claimed bit.
Definition at line 109 of file Arg.h.
References getBaseArg().
Referenced by llvm::opt::ArgList::AddAllArgs(), llvm::opt::ArgList::AddAllArgsExcept(), llvm::opt::ArgList::AddAllArgsTranslated(), llvm::opt::ArgList::AddAllArgValues(), llvm::opt::ArgList::ClaimAllArgs(), and llvm::opt::ArgList::getLastArg().
containsValue()
bool llvm::opt::Arg::containsValue (StringRef Value) const inline
Definition at line 120 of file Arg.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, dump(), llvm::numbers::e, getAsString(), getNumValues(), llvm::RISCVFenceField::O, print(), render(), and renderAsInput().
dump()
LLVM_DUMP_METHOD void Arg::dump () const
Definition at line 65 of file Arg.cpp.
References llvm::dbgs(), and print().
Referenced by containsValue().
getAlias()
const Arg* llvm::opt::Arg::getAlias () const inline
Args are converted to their unaliased form.
For args that originally came from an alias, this returns the alias the arg was produced from.
Definition at line 100 of file Arg.h.
getAsString()
std::string Arg::getAsString (const ArgList & Args) const
Return a formatted version of the argument and its values, for diagnostics.
Since this is for diagnostics, if this Arg was produced through an alias, this returns the string representation of the alias that the user wrote.
Definition at line 68 of file Arg.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), render(), and llvm::raw_svector_ostream::str().
Referenced by containsValue().
getBaseArg()
const Arg& llvm::opt::Arg::getBaseArg () const inline
Return the base argument which generated this arg.
This is either the argument itself or the argument it was derived from during tool chain specific argument translation.
Definition at line 93 of file Arg.h.
Referenced by claim(), and isClaimed().
getIndex()
unsigned llvm::opt::Arg::getIndex () const inline
Definition at line 87 of file Arg.h.
Referenced by render().
getNumValues()
unsigned llvm::opt::Arg::getNumValues () const inline
Definition at line 111 of file Arg.h.
References llvm::SmallVectorBase::size().
Referenced by containsValue(), and render().
getOption()
const Option& llvm::opt::Arg::getOption () const inline
Definition at line 77 of file Arg.h.
Referenced by llvm::opt::ArgList::AddAllArgsExcept(), llvm::opt::ArgList::append(), render(), and renderAsInput().
getOwnsValues()
bool llvm::opt::Arg::getOwnsValues () const inline
Definition at line 103 of file Arg.h.
getSpelling()
StringRef llvm::opt::Arg::getSpelling () const inline
Returns the used prefix and name of the option: For --foo=bar, returns --foo=.
This is often the wrong function to call:
Use getValue() to get bar.
Use getAsString() to get a string suitable for printing an Arg in a diagnostic.
Definition at line 85 of file Arg.h.
Referenced by render().
getValue()
const char* llvm::opt::Arg::getValue (unsigned N = 0) const inline
Definition at line 113 of file Arg.h.
References N.
Referenced by llvm::opt::ArgList::AddAllArgsTranslated(), llvm::dlltoolDriverMain(), and render().
getValues() [1/2]
SmallVectorImpl<const char *>& llvm::opt::Arg::getValues () inline
Definition at line 117 of file Arg.h.
Referenced by llvm::opt::Option::accept(), llvm::opt::ArgList::AddAllArgValues(), and llvm::opt::Option::matches().
getValues() [2/2]
const SmallVectorImpl<const char *>& llvm::opt::Arg::getValues () const inline
Definition at line 118 of file Arg.h.
isClaimed()
bool llvm::opt::Arg::isClaimed () const inline
Definition at line 106 of file Arg.h.
References getBaseArg().
Referenced by llvm::opt::ArgList::ClaimAllArgs().
operator=()
Arg& llvm::opt::Arg::operator= (const Arg &) delete
print()
void Arg::print (raw_ostream & O) const
Definition at line 47 of file Arg.cpp.
References llvm::numbers::e, llvm::opt::Option::print(), and llvm::SmallVectorBase::size().
Referenced by containsValue(), dump(), and llvm::opt::ArgList::print().
render()
void Arg::render (const ArgList & Args, ArgStringList & Output) const
Append the argument onto the given array as strings.
Definition at line 96 of file Arg.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::numbers::e, llvm::SmallVectorTemplateCommon< T, typename >::end(), getIndex(), getNumValues(), getOption(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), getSpelling(), getValue(), llvm::opt::ArgList::MakeArgString(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::opt::Option::RenderCommaJoinedStyle, llvm::opt::Option::RenderJoinedStyle, llvm::opt::Option::RenderSeparateStyle, llvm::opt::Option::RenderValuesStyle, and llvm::raw_svector_ostream::str().
Referenced by llvm::opt::ArgList::AddAllArgs(), llvm::opt::ArgList::AddAllArgsExcept(), llvm::opt::ArgList::AddLastArg(), containsValue(), getAsString(), and renderAsInput().
renderAsInput()
void Arg::renderAsInput (const ArgList & Args, ArgStringList & Output) const
Append the argument, render as an input, onto the given array as strings.
The distinction is that some options only render their values when rendered as a input (e.g., Xlinker).
Definition at line 87 of file Arg.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getOption(), and render().
Referenced by containsValue().
setAlias()
void llvm::opt::Arg::setAlias (std::unique_ptr< Arg > Alias) inline
Definition at line 101 of file Arg.h.
Referenced by llvm::opt::Option::accept().
setBaseArg()
void llvm::opt::Arg::setBaseArg (const Arg * BaseArg) inline
Definition at line 96 of file Arg.h.
setOwnsValues()
void llvm::opt::Arg::setOwnsValues (bool Value) const inline
Definition at line 104 of file Arg.h.
Referenced by llvm::opt::Option::accept(), and llvm::opt::Option::matches().
The documentation for this class was generated from the following files:
include/llvm/Option/Arg.h
lib/Option/Arg.cpp