LLVM: llvm::BitsRecTy Class Reference
llvm::BitsRecTy Class Reference
'bits<n>' - Represent a fixed number of bits
#include "llvm/TableGen/Record.h"
Public Member Functions
unsigned getNumBits () const
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
Return true if all values of 'this' type can be converted to the specified type.
bool typeIsA (const RecTy *RHS) const override
Return true if 'this' type is equal to or a subtype of RHS.
Public Member Functions inherited from llvm::RecTy
RecTy (RecTyKind K)
virtual ~RecTy ()=default
RecTyKind getRecTyKind () const
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static BitsRecTy * get (unsigned Sz)
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, CodeRecTyKind, IntRecTyKind,
StringRecTyKind, ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
'bits<n>' - Represent a fixed number of bits
Definition at line 118 of file Record.h.
Member Function Documentation
classof()
static bool llvm::BitsRecTy::classof (const RecTy * RT) inline static
Definition at line 124 of file Record.h.
References llvm::RecTy::BitsRecTyKind, and llvm::RecTy::getRecTyKind().
get()
BitsRecTy * BitsRecTy::get (unsigned Sz) static
Definition at line 84 of file Record.cpp.
References Allocator.
Referenced by QualifiedNameOfImplicitName().
getAsString()
std::string BitsRecTy::getAsString () const override virtual
Implements llvm::RecTy.
Definition at line 94 of file Record.cpp.
References Size, and llvm::utostr().
getNumBits()
unsigned llvm::BitsRecTy::getNumBits () const inline
Definition at line 130 of file Record.h.
References llvm::RecTy::getAsString(), Size, llvm::RecTy::typeIsA(), and llvm::RecTy::typeIsConvertibleTo().
Referenced by llvm::TypedInit::convertInitializerBitRange().
typeIsA()
bool BitsRecTy::typeIsA (const RecTy * RHS) const override virtual
Return true if 'this' type is equal to or a subtype of RHS.
For example, a bit set is not an int, but they are convertible.
Reimplemented from llvm::RecTy.
Definition at line 105 of file Record.cpp.
References Size.
typeIsConvertibleTo()
bool BitsRecTy::typeIsConvertibleTo (const RecTy * RHS) const override virtual
Return true if all values of 'this' type can be converted to the specified type.
Reimplemented from llvm::RecTy.
Definition at line 98 of file Record.cpp.
References llvm::RecTy::BitRecTyKind, llvm::RecTy::getRecTyKind(), llvm::RecTy::IntRecTyKind, Size, and llvm::RecTy::typeIsConvertibleTo().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp