LLVM: llvm::CalleeSavedInfo Class Reference
llvm::CalleeSavedInfo Class Reference
The CalleeSavedInfo class tracks the information need to locate where a callee saved register is in the current frame.
#include "llvm/CodeGen/MachineFrameInfo.h"
Public Member Functions
CalleeSavedInfo (unsigned R, int FI=0)
unsigned getReg () const
int getFrameIdx () const
unsigned getDstReg () const
void setFrameIdx (int FI)
void setDstReg (unsigned SpillReg)
bool isRestored () const
void setRestored (bool R)
bool isSpilledToReg () const
Detailed Description
The CalleeSavedInfo class tracks the information need to locate where a callee saved register is in the current frame.
Callee saved reg can also be saved to a different register rather than on the stack by setting DstReg instead of FrameIdx.
Definition at line 33 of file MachineFrameInfo.h.
Constructor & Destructor Documentation
CalleeSavedInfo()
llvm::CalleeSavedInfo::CalleeSavedInfo (unsigned R, int FI = 0) inline explicit
Definition at line 57 of file MachineFrameInfo.h.
Member Function Documentation
getDstReg()
unsigned llvm::CalleeSavedInfo::getDstReg () const inline
Definition at line 63 of file MachineFrameInfo.h.
References DstReg.
getFrameIdx()
int llvm::CalleeSavedInfo::getFrameIdx () const inline
Definition at line 62 of file MachineFrameInfo.h.
References FrameIdx.
Referenced by llvm::XCoreFrameLowering::emitPrologue().
getReg()
unsigned llvm::CalleeSavedInfo::getReg () const inline
Definition at line 61 of file MachineFrameInfo.h.
Referenced by llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), and llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
isRestored()
bool llvm::CalleeSavedInfo::isRestored () const inline
Definition at line 72 of file MachineFrameInfo.h.
isSpilledToReg()
bool llvm::CalleeSavedInfo::isSpilledToReg () const inline
Definition at line 74 of file MachineFrameInfo.h.
setDstReg()
void llvm::CalleeSavedInfo::setDstReg (unsigned SpillReg) inline
Definition at line 68 of file MachineFrameInfo.h.
References DstReg.
setFrameIdx()
void llvm::CalleeSavedInfo::setFrameIdx (int FI) inline
Definition at line 64 of file MachineFrameInfo.h.
References FrameIdx.
setRestored()
void llvm::CalleeSavedInfo::setRestored (bool R) inline
Definition at line 73 of file MachineFrameInfo.h.
Referenced by llvm::MIRParserImpl::parseCalleeSavedRegister(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), and llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
Member Data Documentation
DstReg
unsigned llvm::CalleeSavedInfo::DstReg
Definition at line 37 of file MachineFrameInfo.h.
Referenced by getDstReg(), and setDstReg().
FrameIdx
int llvm::CalleeSavedInfo::FrameIdx
Definition at line 36 of file MachineFrameInfo.h.
Referenced by getFrameIdx(), and setFrameIdx().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineFrameInfo.h