LLVM: llvm::ContextAndReplaceableUses Class Reference
llvm::ContextAndReplaceableUses Class Reference
Pointer to the context, with optional RAUW support.
#include "llvm/IR/Metadata.h"
Public Member Functions
ContextAndReplaceableUses (LLVMContext &Context)
ContextAndReplaceableUses (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses)
ContextAndReplaceableUses ()=delete
ContextAndReplaceableUses (ContextAndReplaceableUses &&)=delete
ContextAndReplaceableUses (const ContextAndReplaceableUses &)=delete
ContextAndReplaceableUses & operator= (ContextAndReplaceableUses &&)=delete
ContextAndReplaceableUses & operator= (const ContextAndReplaceableUses &)=delete
~ContextAndReplaceableUses ()
operator LLVMContext & ()
bool hasReplaceableUses () const
Whether this contains RAUW support.
LLVMContext & getContext () const
ReplaceableMetadataImpl * getReplaceableUses () const
ReplaceableMetadataImpl * getOrCreateReplaceableUses ()
Ensure that this has RAUW support, and then return it.
void makeReplaceable (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses)
Assign RAUW support to this.
std::unique_ptr< ReplaceableMetadataImpl > takeReplaceableUses ()
Drop RAUW support.
Detailed Description
Pointer to the context, with optional RAUW support.
Either a raw (non-null) pointer to the LLVMContext, or an owned pointer to ReplaceableMetadataImpl (which has a reference to LLVMContext).
Definition at line 778 of file Metadata.h.
Constructor & Destructor Documentation
ContextAndReplaceableUses() [1/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (LLVMContext & Context) inline
Definition at line 782 of file Metadata.h.
ContextAndReplaceableUses() [2/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses) inline
Definition at line 783 of file Metadata.h.
References assert().
ContextAndReplaceableUses() [3/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses () delete
ContextAndReplaceableUses() [4/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (ContextAndReplaceableUses &&) delete
ContextAndReplaceableUses() [5/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (const ContextAndReplaceableUses &) delete
~ContextAndReplaceableUses()
llvm::ContextAndReplaceableUses::~ContextAndReplaceableUses () inline
Definition at line 794 of file Metadata.h.
Member Function Documentation
getContext()
LLVMContext& llvm::ContextAndReplaceableUses::getContext () const inline
Definition at line 803 of file Metadata.h.
References llvm::PointerUnion< PTs >::get().
getOrCreateReplaceableUses()
ReplaceableMetadataImpl* llvm::ContextAndReplaceableUses::getOrCreateReplaceableUses () inline
Ensure that this has RAUW support, and then return it.
Definition at line 816 of file Metadata.h.
getReplaceableUses()
ReplaceableMetadataImpl* llvm::ContextAndReplaceableUses::getReplaceableUses () const inline
Definition at line 809 of file Metadata.h.
References llvm::PointerUnion< PTs >::get().
Referenced by llvm::MDNode::dropAllReferences().
hasReplaceableUses()
bool llvm::ContextAndReplaceableUses::hasReplaceableUses () const inline
Whether this contains RAUW support.
Definition at line 799 of file Metadata.h.
References llvm::PointerUnion< PTs >::is().
Referenced by llvm::MDNode::dropAllReferences(), and llvm::MDNode::resolve().
makeReplaceable()
void llvm::ContextAndReplaceableUses::makeReplaceable (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses) inline
Assign RAUW support to this.
Make this replaceable, taking ownership of ReplaceableUses (which must not be null).
Definition at line 827 of file Metadata.h.
References assert().
operator LLVMContext &()
llvm::ContextAndReplaceableUses::operator LLVMContext & () inline
Definition at line 796 of file Metadata.h.
operator=() [1/2]
ContextAndReplaceableUses& llvm::ContextAndReplaceableUses::operator= (ContextAndReplaceableUses &&) delete
operator=() [2/2]
ContextAndReplaceableUses& llvm::ContextAndReplaceableUses::operator= (const ContextAndReplaceableUses &) delete
takeReplaceableUses()
std::unique_ptr<ReplaceableMetadataImpl> llvm::ContextAndReplaceableUses::takeReplaceableUses () inline
Drop RAUW support.
Cede ownership of RAUW support, returning it.
Definition at line 838 of file Metadata.h.
References assert().
Referenced by llvm::MDNode::dropAllReferences(), and llvm::MDNode::resolve().
The documentation for this class was generated from the following file:
include/llvm/IR/Metadata.h