LLVM: llvm::generic_gep_type_iterator< ItTy > Class Template Reference
llvm::generic_gep_type_iterator< ItTy > Class Template Reference
#include "llvm/IR/GetElementPtrTypeIterator.h"
Public Member Functions
bool operator== (const generic_gep_type_iterator &x) const
bool operator!= (const generic_gep_type_iterator &x) const
Type * getIndexedType () const
Value * getOperand () const
generic_gep_type_iterator & operator++ ()
generic_gep_type_iterator operator++ (int)
bool isStruct () const
bool isSequential () const
StructType * getStructType () const
StructType * getStructTypeOrNull () const
bool isBoundedSequential () const
uint64_t getSequentialNumElements () const
Static Public Member Functions
static generic_gep_type_iterator begin (Type *Ty, ItTy It)
static generic_gep_type_iterator end (ItTy It)
Detailed Description
template<typename ItTy = User::const_op_iterator>
class llvm::generic_gep_type_iterator< ItTy >
Definition at line 31 of file GetElementPtrTypeIterator.h.
Member Function Documentation
begin()
template<typename ItTy = User::const_op_iterator> static generic_gep_type_iterator llvm::generic_gep_type_iterator< ItTy >::begin (Type * Ty, ItTy It) inline static
Definition at line 43 of file GetElementPtrTypeIterator.h.
References I.
Referenced by llvm::gep_type_begin().
end()
template<typename ItTy = User::const_op_iterator> static generic_gep_type_iterator llvm::generic_gep_type_iterator< ItTy >::end (ItTy It) inline static
Definition at line 50 of file GetElementPtrTypeIterator.h.
References I.
Referenced by llvm::gep_type_end().
getIndexedType()
template<typename ItTy = User::const_op_iterator> Type* llvm::generic_gep_type_iterator< ItTy >::getIndexedType () const inline
Definition at line 68 of file GetElementPtrTypeIterator.h.
References llvm::PointerUnion< PTs >::dyn_cast(), llvm::PointerUnion< PTs >::get(), llvm::generic_gep_type_iterator< ItTy >::getOperand(), and llvm::T.
Referenced by CC_MipsO32_FP64(), computeKnownBitsFromOperator(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::EmitGEPOffset(), evaluateGEPOffsetExpression(), evaluateICmpRelation(), getComparePred(), llvm::getGEPInductionOperand(), llvm::DataLayout::getIndexedOffsetInType(), getMaxPointerSize(), getOffsetFromIndex(), isGEPFoldable(), isPromotedInstructionLegal(), llvm::AArch64TargetLowering::isZExtFree(), matchesOr(), llvm::generic_gep_type_iterator< ItTy >::operator++(), propagateMetadata(), llvm::Interpreter::visitAllocaInst(), and llvm::InstCombiner::visitGetElementPtrInst().
getOperand()
template<typename ItTy = User::const_op_iterator> Value* llvm::generic_gep_type_iterator< ItTy >::getOperand () const inline
Definition at line 74 of file GetElementPtrTypeIterator.h.
Referenced by llvm::DataLayout::getIndexedOffsetInType(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), isSafeSROAGEP(), propagateMetadata(), and llvm::Interpreter::visitAllocaInst().
getSequentialNumElements()
template<typename ItTy = User::const_op_iterator> uint64_t llvm::generic_gep_type_iterator< ItTy >::getSequentialNumElements () const inline
Definition at line 119 of file GetElementPtrTypeIterator.h.
References assert(), and llvm::generic_gep_type_iterator< ItTy >::isBoundedSequential().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), and isSafeSROAGEP().
getStructType()
template<typename ItTy = User::const_op_iterator> StructType* llvm::generic_gep_type_iterator< ItTy >::getStructType () const inline
Definition at line 109 of file GetElementPtrTypeIterator.h.
References llvm::PointerUnion< PTs >::get().
Referenced by llvm::createSeparateConstOffsetFromGEPPass().
getStructTypeOrNull()
template<typename ItTy = User::const_op_iterator> StructType* llvm::generic_gep_type_iterator< ItTy >::getStructTypeOrNull () const inline
Definition at line 111 of file GetElementPtrTypeIterator.h.
References llvm::PointerUnion< PTs >::dyn_cast().
Referenced by CC_MipsO32_FP64(), computeKnownBitsFromOperator(), llvm::EmitGEPOffset(), evaluateGEPOffsetExpression(), getComparePred(), llvm::DataLayout::getIndexedOffsetInType(), getMaxPointerSize(), getOffsetFromIndex(), getUniformBase(), isPromotedInstructionLegal(), and llvm::Interpreter::visitAllocaInst().
isBoundedSequential()
template<typename ItTy = User::const_op_iterator> bool llvm::generic_gep_type_iterator< ItTy >::isBoundedSequential () const inline
Definition at line 115 of file GetElementPtrTypeIterator.h.
References llvm::generic_gep_type_iterator< ItTy >::isSequential().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::generic_gep_type_iterator< ItTy >::getSequentialNumElements(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), and isSafeSROAGEP().
isSequential()
template<typename ItTy = User::const_op_iterator> bool llvm::generic_gep_type_iterator< ItTy >::isSequential () const inline
Definition at line 107 of file GetElementPtrTypeIterator.h.
References llvm::PointerUnion< PTs >::is().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::createSeparateConstOffsetFromGEPPass(), GEPSequentialConstIndexed(), llvm::generic_gep_type_iterator< ItTy >::isBoundedSequential(), and isGEPFoldable().
isStruct()
template<typename ItTy = User::const_op_iterator> bool llvm::generic_gep_type_iterator< ItTy >::isStruct () const inline
Definition at line 106 of file GetElementPtrTypeIterator.h.
References llvm::PointerUnion< PTs >::is().
Referenced by llvm::canReplaceOperandWithVariable(), isSafeSROAGEP(), matchesOr(), and llvm::InstCombiner::visitGetElementPtrInst().
operator!=()
template<typename ItTy = User::const_op_iterator> bool llvm::generic_gep_type_iterator< ItTy >::operator!= (const generic_gep_type_iterator< ItTy > & x) const inline
Definition at line 60 of file GetElementPtrTypeIterator.h.
References llvm::generic_gep_type_iterator< ItTy >::operator==().
operator++() [1/2]
template<typename ItTy = User::const_op_iterator> generic_gep_type_iterator& llvm::generic_gep_type_iterator< ItTy >::operator++ () inline
Definition at line 76 of file GetElementPtrTypeIterator.h.
References llvm::dyn_cast(), and llvm::generic_gep_type_iterator< ItTy >::getIndexedType().
operator++() [2/2]
template<typename ItTy = User::const_op_iterator> generic_gep_type_iterator llvm::generic_gep_type_iterator< ItTy >::operator++ (int) inline
Definition at line 87 of file GetElementPtrTypeIterator.h.
operator==()
template<typename ItTy = User::const_op_iterator> bool llvm::generic_gep_type_iterator< ItTy >::operator== (const generic_gep_type_iterator< ItTy > & x) const inline
Definition at line 56 of file GetElementPtrTypeIterator.h.
Referenced by llvm::generic_gep_type_iterator< ItTy >::operator!=().
The documentation for this class was generated from the following file:
include/llvm/IR/GetElementPtrTypeIterator.h