LLVM: llvm::MachineConstantPool Class Reference
llvm::MachineConstantPool Class Reference
The MachineConstantPool class keeps track of constants referenced by a function which must be spilled to memory.
#include "llvm/CodeGen/MachineConstantPool.h"
Public Member Functions
MachineConstantPool (const DataLayout &DL)
The only constructor.
~MachineConstantPool ()
unsigned getConstantPoolAlignment () const
getConstantPoolAlignment - Return the alignment required by the whole constant pool, of which the first element must be aligned.
unsigned getConstantPoolIndex (const Constant *C, unsigned Alignment)
getConstantPoolIndex - Create a new entry in the constant pool or return an existing one.
unsigned getConstantPoolIndex (MachineConstantPoolValue *V, unsigned Alignment)
bool isEmpty () const
isEmpty - Return true if this constant pool contains no constants.
const std::vector< MachineConstantPoolEntry > & getConstants () const
void print (raw_ostream &OS) const
print - Used by the MachineFunction printer to print information about constant pool objects.
void dump () const
dump - Call print(cerr) to be called from the debugger.
Detailed Description
The MachineConstantPool class keeps track of constants referenced by a function which must be spilled to memory.
This is used for constants which are unable to be used directly as operands to instructions, which typically include floating point and large integer constants.
Instructions reference the address of these constant pool constants through the use of MO_ConstantPoolIndex values. When emitting assembly or machine code, these virtual address references are converted to refer to the address of the function constant pool values. The machine constant pool.
Definition at line 120 of file MachineConstantPool.h.
Constructor & Destructor Documentation
MachineConstantPool()
llvm::MachineConstantPool::MachineConstantPool (const DataLayout & DL) inline explicit
The only constructor.
Definition at line 131 of file MachineConstantPool.h.
~MachineConstantPool()
MachineConstantPool::~MachineConstantPool ()
Definition at line 1035 of file MachineFunction.cpp.
References llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), Deleted, llvm::numbers::e, E, I, and llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MachineConstantPool::dump () const
dump - Call print(cerr) to be called from the debugger.
Definition at line 1151 of file MachineFunction.cpp.
References llvm::dbgs(), and llvm::MachineFunction::print().
getConstantPoolAlignment()
unsigned llvm::MachineConstantPool::getConstantPoolAlignment () const inline
getConstantPoolAlignment - Return the alignment required by the whole constant pool, of which the first element must be aligned.
Definition at line 137 of file MachineConstantPool.h.
References C.
getConstantPoolIndex() [1/2]
unsigned MachineConstantPool::getConstantPoolIndex (const Constant * C, unsigned Alignment)
getConstantPoolIndex - Create a new entry in the constant pool or return an existing one.
Create a new entry in the constant pool or return an existing one.
User must specify the minimum required alignment for the object.
User must specify the log2 of the minimum required alignment for the object.
Definition at line 1097 of file MachineFunction.cpp.
References assert(), CanShareConstantPoolEntry(), and llvm::numbers::e.
Referenced by addExclusiveRegPair(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), canTurnIntoCOPY(), duplicateCPV(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitPostSt(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getLaneCopyOpcode(), llvm::MIRParserImpl::initializeConstantPool(), llvm::XCoreInstrInfo::loadImmediate(), and llvm::ARMTargetLowering::ReplaceNodeResults().
getConstantPoolIndex() [2/2]
unsigned MachineConstantPool::getConstantPoolIndex (MachineConstantPoolValue * V, unsigned Alignment)
Definition at line 1117 of file MachineFunction.cpp.
References assert(), and llvm::MachineConstantPoolValue::getExistingMachineCPValue().
getConstants()
const std::vector<MachineConstantPoolEntry>& llvm::MachineConstantPool::getConstants () const inline
Definition at line 149 of file MachineConstantPool.h.
References llvm::dump(), and llvm::MachineConstantPoolValue::print().
Referenced by llvm::MIRPrinter::convert(), duplicateCPV(), llvm::WebAssemblyAsmPrinter::EmitConstantPool(), llvm::AsmPrinter::EmitConstantPool(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), getConstantFromPool(), llvm::AsmPrinter::GetCPISymbol(), llvm::SystemZConstantPoolValue::getExistingMachineCPValue(), llvm::ARMConstantPoolValue::getExistingMachineCPValueImpl(), and llvm::ARMBaseInstrInfo::produceSameValue().
isEmpty()
bool llvm::MachineConstantPool::isEmpty () const inline
isEmpty - Return true if this constant pool contains no constants.
Definition at line 147 of file MachineConstantPool.h.
print()
void MachineConstantPool::print (raw_ostream & OS) const
print - Used by the MachineFunction printer to print information about constant pool objects.
Implemented in MachineFunction.cpp
Definition at line 1135 of file MachineFunction.cpp.
References llvm::numbers::e.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineConstantPool.h
lib/CodeGen/MachineFunction.cpp