LLVM: llvm::pdb::DbiStream Class Reference
llvm::pdb::DbiStream Class Reference
#include "llvm/DebugInfo/PDB/Native/DbiStream.h"
Public Member Functions
DbiStream (std::unique_ptr< BinaryStream > Stream)
~DbiStream ()
Error reload (PDBFile *Pdb)
PdbRaw_DbiVer getDbiVersion () const
uint32_t getAge () const
uint16_t getPublicSymbolStreamIndex () const
uint16_t getGlobalSymbolStreamIndex () const
uint16_t getFlags () const
bool isIncrementallyLinked () const
bool hasCTypes () const
bool isStripped () const
uint16_t getBuildNumber () const
uint16_t getBuildMajorVersion () const
uint16_t getBuildMinorVersion () const
uint16_t getPdbDllRbld () const
uint32_t getPdbDllVersion () const
uint32_t getSymRecordStreamIndex () const
PDB_Machine getMachineType () const
const DbiStreamHeader * getHeader () const
BinarySubstreamRef getSectionContributionData () const
BinarySubstreamRef getSecMapSubstreamData () const
BinarySubstreamRef getModiSubstreamData () const
BinarySubstreamRef getFileInfoSubstreamData () const
BinarySubstreamRef getTypeServerMapSubstreamData () const
BinarySubstreamRef getECSubstreamData () const
uint32_t getDebugStreamIndex (DbgHeaderType Type) const
If the given stream type is present, returns its stream index.
const DbiModuleList & modules () const
FixedStreamArray< object::coff_section > getSectionHeaders () const
bool hasOldFpoRecords () const
FixedStreamArray< object::FpoData > getOldFpoRecords () const
bool hasNewFpoRecords () const
const codeview::DebugFrameDataSubsectionRef & getNewFpoRecords () const
FixedStreamArray< SecMapEntry > getSectionMap () const
void visitSectionContributions (ISectionContribVisitor &Visitor) const
Expected< StringRef > getECName (uint32_t NI) const
Friends
class DbiStreamBuilder
Detailed Description
Definition at line 37 of file DbiStream.h.
Constructor & Destructor Documentation
DbiStream()
DbiStream::DbiStream (std::unique_ptr< BinaryStream > Stream) explicit
Definition at line 47 of file DbiStream.cpp.
References ~DbiStream().
~DbiStream()
DbiStream::~DbiStream () default
Referenced by DbiStream().
Member Function Documentation
getAge()
uint32_t DbiStream::getAge () const
Definition at line 152 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::Age.
getBuildMajorVersion()
uint16_t DbiStream::getBuildMajorVersion () const
Definition at line 178 of file DbiStream.cpp.
References llvm::pdb::DbiBuildNo::BuildMajorMask, llvm::pdb::DbiBuildNo::BuildMajorShift, and llvm::pdb::DbiStreamHeader::BuildNumber.
getBuildMinorVersion()
uint16_t DbiStream::getBuildMinorVersion () const
Definition at line 183 of file DbiStream.cpp.
References llvm::pdb::DbiBuildNo::BuildMinorMask, llvm::pdb::DbiBuildNo::BuildMinorShift, and llvm::pdb::DbiStreamHeader::BuildNumber.
getBuildNumber()
uint16_t DbiStream::getBuildNumber () const
Definition at line 176 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::BuildNumber.
getDbiVersion()
PdbRaw_DbiVer DbiStream::getDbiVersion () const
Definition at line 147 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::VersionHeader.
getDebugStreamIndex()
uint32_t DbiStream::getDebugStreamIndex (DbgHeaderType Type) const
If the given stream type is present, returns its stream index.
If it is not present, returns InvalidStreamIndex.
Definition at line 378 of file DbiStream.cpp.
References llvm::pdb::kInvalidStreamIndex, llvm::T, and llvm::pdb::Type.
Referenced by getECName().
getECName()
Expected< StringRef > DbiStream::getECName (uint32_t NI) const
Definition at line 236 of file DbiStream.cpp.
References llvm::pdb::corrupt_file, llvm::pdb::DbiSecContribV2, llvm::pdb::DbiSecContribVer60, llvm::codeview::EC, llvm::BinarySubstreamRef::empty(), llvm::pdb::feature_unsupported, llvm::pdb::FPO, llvm::X86AS::FS, getDebugStreamIndex(), llvm::pdb::PDBStringTable::getStringForID(), llvm::codeview::DebugFrameDataSubsectionRef::initialize(), llvm::pdb::kInvalidStreamIndex, llvm::pdb::NewFPO, llvm::codeview::Pdb, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readEnum(), llvm::pdb::PDBFile::safelyCreateIndexedStream(), llvm::pdb::SectionHdr, llvm::BinarySubstreamRef::StreamData, llvm::Error::success(), and llvm::Expected< T >::takeError().
getECSubstreamData()
BinarySubstreamRef DbiStream::getECSubstreamData () const
Definition at line 363 of file DbiStream.cpp.
References llvm::codeview::EC, llvm::BinarySubstreamRef::empty(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), llvm::pdb::SecMapHeader::SecCount, llvm::BinarySubstreamRef::StreamData, and llvm::Error::success().
getFileInfoSubstreamData()
BinarySubstreamRef DbiStream::getFileInfoSubstreamData () const
Definition at line 355 of file DbiStream.cpp.
getFlags()
uint16_t DbiStream::getFlags () const
Definition at line 162 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::Flags.
getGlobalSymbolStreamIndex()
uint16_t DbiStream::getGlobalSymbolStreamIndex () const
Definition at line 158 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::GlobalSymbolStreamIndex.
getHeader()
const DbiStreamHeader* llvm::pdb::DbiStream::getHeader () const inline
Definition at line 66 of file DbiStream.h.
References llvm::pdb::DbiSecContribVer60, and llvm::pdb::SectionContribs.
getMachineType()
PDB_Machine DbiStream::getMachineType () const
Definition at line 196 of file DbiStream.cpp.
References Machine, and llvm::pdb::DbiStreamHeader::MachineType.
getModiSubstreamData()
BinarySubstreamRef DbiStream::getModiSubstreamData () const
Definition at line 351 of file DbiStream.cpp.
getNewFpoRecords()
const DebugFrameDataSubsectionRef & DbiStream::getNewFpoRecords () const
Definition at line 213 of file DbiStream.cpp.
getOldFpoRecords()
FixedStreamArray< object::FpoData > DbiStream::getOldFpoRecords () const
Definition at line 207 of file DbiStream.cpp.
getPdbDllRbld()
uint16_t DbiStream::getPdbDllRbld () const
Definition at line 188 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::PdbDllRbld.
getPdbDllVersion()
uint32_t DbiStream::getPdbDllVersion () const
Definition at line 190 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::PdbDllVersion.
getPublicSymbolStreamIndex()
uint16_t DbiStream::getPublicSymbolStreamIndex () const
Definition at line 154 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::PublicSymbolStreamIndex.
getSecMapSubstreamData()
BinarySubstreamRef DbiStream::getSecMapSubstreamData () const
Definition at line 347 of file DbiStream.cpp.
getSectionContributionData()
BinarySubstreamRef DbiStream::getSectionContributionData () const
Definition at line 343 of file DbiStream.cpp.
getSectionHeaders()
FixedStreamArray< object::coff_section > DbiStream::getSectionHeaders () const
Definition at line 201 of file DbiStream.cpp.
getSectionMap()
FixedStreamArray< SecMapEntry > DbiStream::getSectionMap () const
Definition at line 219 of file DbiStream.cpp.
getSymRecordStreamIndex()
uint32_t DbiStream::getSymRecordStreamIndex () const
Definition at line 192 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::SymRecordStreamIndex.
getTypeServerMapSubstreamData()
BinarySubstreamRef DbiStream::getTypeServerMapSubstreamData () const
Definition at line 359 of file DbiStream.cpp.
hasCTypes()
bool DbiStream::hasCTypes () const
Definition at line 168 of file DbiStream.cpp.
References llvm::pdb::DbiFlags::FlagHasCTypesMask, and llvm::pdb::DbiStreamHeader::Flags.
Referenced by llvm::pdb::NativeExeSymbol::hasCTypes().
hasNewFpoRecords()
bool DbiStream::hasNewFpoRecords () const
Definition at line 211 of file DbiStream.cpp.
hasOldFpoRecords()
bool DbiStream::hasOldFpoRecords () const
Definition at line 205 of file DbiStream.cpp.
isIncrementallyLinked()
bool DbiStream::isIncrementallyLinked () const
Definition at line 164 of file DbiStream.cpp.
References llvm::pdb::DbiFlags::FlagIncrementalMask, and llvm::pdb::DbiStreamHeader::Flags.
isStripped()
bool DbiStream::isStripped () const
Definition at line 172 of file DbiStream.cpp.
References llvm::pdb::DbiStreamHeader::Flags, and llvm::pdb::DbiFlags::FlagStrippedMask.
Referenced by llvm::pdb::NativeExeSymbol::hasPrivateSymbols().
modules()
const DbiModuleList & DbiStream::modules () const
Definition at line 217 of file DbiStream.cpp.
Referenced by llvm::pdb::SymbolCache::getNumCompilands(), llvm::pdb::SymbolCache::getOrCreateCompiland(), and llvm::pdb::SymbolCache::SymbolCache().
reload()
Error DbiStream::reload (PDBFile * Pdb)
Definition at line 52 of file DbiStream.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::pdb::corrupt_file, llvm::codeview::EC, llvm::pdb::DbiStreamHeader::ECSubstreamSize, llvm::BinarySubstreamRef::empty(), llvm::pdb::feature_unsupported, llvm::pdb::DbiStreamHeader::FileInfoSize, llvm::pdb::DbiModuleList::initialize(), llvm::pdb::DbiStreamHeader::ModiSubstreamSize, llvm::pdb::DbiStreamHeader::OptionalDbgHdrSize, llvm::pdb::PdbDbiV70, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), llvm::BinaryStreamReader::readSubstream(), llvm::pdb::PDBStringTable::reload(), llvm::pdb::DbiStreamHeader::SecContrSubstreamSize, llvm::pdb::DbiStreamHeader::SectionMapSize, llvm::BinarySubstreamRef::StreamData, llvm::Error::success(), llvm::pdb::DbiStreamHeader::TypeServerSize, llvm::pdb::DbiStreamHeader::VersionHeader, and llvm::pdb::DbiStreamHeader::VersionSignature.
visitSectionContributions()
void DbiStream::visitSectionContributions (ISectionContribVisitor & Visitor) const
Definition at line 223 of file DbiStream.cpp.
References assert(), llvm::pdb::DbiSecContribV2, llvm::pdb::DbiSecContribVer60, llvm::PPCISD::SC, and llvm::pdb::ISectionContribVisitor::visit().
Friends And Related Function Documentation
DbiStreamBuilder
friend class DbiStreamBuilder friend
Definition at line 38 of file DbiStream.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/DbiStream.h
lib/DebugInfo/PDB/Native/DbiStream.cpp