LLVM: llvm::X86InstPrinterCommon Class Reference
llvm::X86InstPrinterCommon Class Reference abstract
#include "Target/X86/MCTargetDesc/X86InstPrinterCommon.h"
Public Member Functions
virtual void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)=0
void printCondCode (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printSSEAVXCC (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printVPCOMMnemonic (const MCInst *MI, raw_ostream &OS)
void printVPCMPMnemonic (const MCInst *MI, raw_ostream &OS)
void printCMPMnemonic (const MCInst *MI, bool IsVCmp, raw_ostream &OS)
void printRoundingControl (const MCInst *MI, unsigned Op, raw_ostream &O)
void printPCRelImm (const MCInst *MI, unsigned OpNo, raw_ostream &O)
printPCRelImm - This is used to print an immediate value that ends up being encoded as a pc-relative value (e.g.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
virtual void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS)=0
Print the specified MCInst to the specified raw_ostream.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Protected Member Functions
void printInstFlags (const MCInst *MI, raw_ostream &O)
void printOptionalSegReg (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printVKPair (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Additional Inherited Members
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 21 of file X86InstPrinterCommon.h.
Member Function Documentation
printCMPMnemonic()
void X86InstPrinterCommon::printCMPMnemonic (const MCInst * MI, bool IsVCmp, raw_ostream & OS)
Definition at line 208 of file X86InstPrinterCommon.cpp.
References llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm_unreachable, and printSSEAVXCC().
Referenced by llvm::X86ATTInstPrinter::printVecCompareInstr(), and llvm::X86IntelInstPrinter::printVecCompareInstr().
printCondCode()
void X86InstPrinterCommon::printCondCode (const MCInst * MI, unsigned Op, raw_ostream & OS)
Definition at line 27 of file X86InstPrinterCommon.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm_unreachable.
printInstFlags()
void X86InstPrinterCommon::printInstFlags (const MCInst * MI, raw_ostream & O) protected
Definition at line 322 of file X86InstPrinterCommon.cpp.
References llvm::MCInstrInfo::get(), llvm::MCInst::getFlags(), llvm::MCInst::getOpcode(), llvm::X86::IP_HAS_LOCK, llvm::X86::IP_HAS_NOTRACK, llvm::X86::IP_HAS_REPEAT, llvm::X86::IP_HAS_REPEAT_NE, llvm::X86II::LOCK, llvm::MCInstPrinter::MII, llvm::X86II::NOTRACK, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::X86ATTInstPrinter::printInst(), and llvm::X86IntelInstPrinter::printInst().
printOperand()
virtual void llvm::X86InstPrinterCommon::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) pure virtual
Implemented in llvm::X86IntelInstPrinter, and llvm::X86ATTInstPrinter.
Referenced by printOptionalSegReg().
printOptionalSegReg()
void X86InstPrinterCommon::printOptionalSegReg (const MCInst * MI, unsigned OpNo, raw_ostream & O) protected
Definition at line 314 of file X86InstPrinterCommon.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printOperand().
Referenced by llvm::X86ATTInstPrinter::printMemOffset(), llvm::X86IntelInstPrinter::printMemOffset(), llvm::X86ATTInstPrinter::printMemReference(), llvm::X86IntelInstPrinter::printMemReference(), llvm::X86ATTInstPrinter::printSrcIdx(), and llvm::X86IntelInstPrinter::printSrcIdx().
printPCRelImm()
void X86InstPrinterCommon::printPCRelImm (const MCInst * MI, unsigned OpNo, raw_ostream & O)
printPCRelImm - This is used to print an immediate value that ends up being encoded as a pc-relative value (e.g.
for jumps and calls). In Intel-style these print slightly differently than normal immediates. for example, a $ is not emitted.
Definition at line 294 of file X86InstPrinterCommon.cpp.
References llvm::Address, assert(), llvm::MCOI::BranchTarget, llvm::dyn_cast(), llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by llvm::X86ATTInstPrinter::printInst().
printRoundingControl()
void X86InstPrinterCommon::printRoundingControl (const MCInst * MI, unsigned Op, raw_ostream & O)
Definition at line 269 of file X86InstPrinterCommon.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm_unreachable, llvm::X86::TO_NEAREST_INT, llvm::X86::TO_NEG_INF, llvm::X86::TO_POS_INF, and llvm::X86::TO_ZERO.
printSSEAVXCC()
void X86InstPrinterCommon::printSSEAVXCC (const MCInst * MI, unsigned Op, raw_ostream & OS)
Definition at line 51 of file X86InstPrinterCommon.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm_unreachable.
Referenced by printCMPMnemonic(), and printVPCMPMnemonic().
printVKPair()
void X86InstPrinterCommon::printVKPair (const MCInst * MI, unsigned OpNo, raw_ostream & OS) protected
Definition at line 339 of file X86InstPrinterCommon.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm_unreachable, and llvm::MCInstPrinter::printRegName().
printVPCMPMnemonic()
void X86InstPrinterCommon::printVPCMPMnemonic (const MCInst * MI, raw_ostream & OS)
Definition at line 121 of file X86InstPrinterCommon.cpp.
References llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm_unreachable, and printSSEAVXCC().
Referenced by llvm::X86ATTInstPrinter::printVecCompareInstr(), and llvm::X86IntelInstPrinter::printVecCompareInstr().
printVPCOMMnemonic()
void X86InstPrinterCommon::printVPCOMMnemonic (const MCInst * MI, raw_ostream & OS)
Definition at line 91 of file X86InstPrinterCommon.cpp.
References llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and llvm_unreachable.
Referenced by llvm::X86ATTInstPrinter::printVecCompareInstr(), and llvm::X86IntelInstPrinter::printVecCompareInstr().
The documentation for this class was generated from the following files:
lib/Target/X86/MCTargetDesc/X86InstPrinterCommon.h
lib/Target/X86/MCTargetDesc/X86InstPrinterCommon.cpp