LLVM: llvm::IntervalPartition Class Reference
llvm::IntervalPartition Class Reference
#include "llvm/Analysis/IntervalPartition.h"
Public Member Functions
IntervalPartition ()
bool runOnFunction (Function &F) override
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
IntervalPartition (IntervalPartition &I, bool)
void print (raw_ostream &O, const Module *=nullptr) const override
print - Print out the internal state of the pass.
Interval * getRootInterval ()
bool isDegeneratePartition ()
Interval * getBlockInterval (BasicBlock *BB)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
const std::vector< Interval * > & getIntervals () const
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 42 of file IntervalPartition.h.
Constructor & Destructor Documentation
IntervalPartition() [1/2]
IntervalPartition::IntervalPartition ()
Definition at line 26 of file IntervalPartition.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeIntervalPartitionPass().
IntervalPartition() [2/2]
IntervalPartition::IntervalPartition (IntervalPartition & I, bool)
Definition at line 98 of file IntervalPartition.cpp.
References assert(), llvm::numbers::e, E, getRootInterval(), I, llvm::intervals_begin(), and llvm::intervals_end().
Member Function Documentation
getAnalysisUsage()
void llvm::IntervalPartition::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 83 of file IntervalPartition.h.
References llvm::AnalysisUsage::setPreservesAll().
getBlockInterval()
Interval* llvm::IntervalPartition::getBlockInterval (BasicBlock * BB) inline
Definition at line 77 of file IntervalPartition.h.
References I.
Referenced by llvm::getSourceGraphNode().
getIntervals()
const std::vector<Interval*>& llvm::IntervalPartition::getIntervals () const inline
Definition at line 88 of file IntervalPartition.h.
References I, and releaseMemory().
getRootInterval()
Interval* llvm::IntervalPartition::getRootInterval () inline
Definition at line 68 of file IntervalPartition.h.
Referenced by llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::IntervalIterator(), and IntervalPartition().
isDegeneratePartition()
bool llvm::IntervalPartition::isDegeneratePartition () inline
Definition at line 72 of file IntervalPartition.h.
print()
void IntervalPartition::print (raw_ostream & OS, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 46 of file IntervalPartition.cpp.
References llvm::numbers::e, I, and llvm::Interval::Nodes.
releaseMemory()
void llvm::IntervalPartition::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Referenced by getIntervals().
runOnFunction()
bool IntervalPartition::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 75 of file IntervalPartition.cpp.
References assert(), llvm::numbers::e, E, I, llvm::intervals_begin(), and llvm::intervals_end().
Member Data Documentation
ID
char IntervalPartition::ID = 0 static
Definition at line 51 of file IntervalPartition.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/IntervalPartition.h
lib/Analysis/IntervalPartition.cpp