LLVM: Node Class Reference
Node Class Reference abstract
#include "llvm/Demangle/ItaniumDemangle.h"
Inherited by AbiTagAttr, ArraySubscriptExpr, ArrayType, BinaryExpr, BoolExpr, BracedExpr, BracedRangeExpr, CallExpr, CastExpr, ClosureTypeName, ConditionalExpr, ConversionExpr, ConversionOperatorType, CtorDtorName, CtorVtableSpecialName, DeleteExpr, DotSuffix, DtorName, DynamicExceptionSpec, ElaboratedTypeSpefType, EnableIfAttr, EnclosingExpr, ExpandedSpecialSubstitution, FloatLiteralImpl< Float >, FoldExpr, ForwardTemplateReference, FunctionEncoding, FunctionParam, FunctionType, GlobalQualifiedName, InitListExpr, IntegerCastExpr, IntegerLiteral, LambdaExpr, LiteralOperator, LocalName, MemberExpr, NameType, NameWithTemplateArgs, NestedName, NewExpr, NodeArrayNode, NoexceptSpec, NonTypeTemplateParamDecl, ObjCProtoName, ParameterPack, ParameterPackExpansion, PixelVectorType, PointerToMemberType, PointerType, PostfixExpr, PostfixQualifiedType, PrefixExpr, QualifiedName, QualType, ReferenceType, SizeofParamPackExpr, SpecialName, SpecialSubstitution, StdQualifiedName, StringLiteral, StructuredBindingName, SyntheticTemplateParamName, TemplateArgs, TemplateArgumentPack, TemplateParamPackDecl, TemplateTemplateParamDecl, ThrowExpr, TypeTemplateParamDecl, UnnamedTypeName, UUIDOfExpr, VectorType, and VendorExtQualType.
Public Types
enum Kind : unsigned char
enum Cache : unsigned char { Cache::Yes, Cache::No, Cache::Unknown }
Three-way bool to track a cached value.
Public Member Functions
Node (Kind K_, Cache RHSComponentCache_=Cache::No, Cache ArrayCache_=Cache::No, Cache FunctionCache_=Cache::No)
template<typename Fn >
void visit (Fn F) const
Visit the most-derived object corresponding to this object.
bool hasRHSComponent (OutputStream &S) const
bool hasArray (OutputStream &S) const
bool hasFunction (OutputStream &S) const
Kind getKind () const
virtual bool hasRHSComponentSlow (OutputStream &) const
virtual bool hasArraySlow (OutputStream &) const
virtual bool hasFunctionSlow (OutputStream &) const
virtual const Node * getSyntaxNode (OutputStream &) const
void print (OutputStream &S) const
virtual void printLeft (OutputStream &) const =0
virtual void printRight (OutputStream &) const
virtual StringView getBaseName () const
virtual ~Node ()=default
DEMANGLE_DUMP_METHOD void dump () const
Public Attributes
Cache RHSComponentCache
Tracks if this node has a component on its right side, in which case we need to call printRight.
Cache ArrayCache
Track if this node is a (possibly qualified) array type.
Cache FunctionCache
Track if this node is a (possibly qualified) function type.
Detailed Description
Definition at line 113 of file ItaniumDemangle.h.
Member Enumeration Documentation
Cache
enum Node::Cache : unsigned char strong
Three-way bool to track a cached value.
Unknown is possible if this node has an unexpanded parameter pack below it that may affect this cache.
Enumerator
Yes
No
Unknown
Definition at line 123 of file ItaniumDemangle.h.
Kind
enum Node::Kind : unsigned char
Definition at line 115 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
Node()
Node::Node (Kind K_, Cache RHSComponentCache_ = Cache::No, Cache ArrayCache_ = Cache::No, Cache FunctionCache_ = Cache::No) inline
Definition at line 143 of file ItaniumDemangle.h.
References F(), and visit().
~Node()
virtual Node::~Node () virtual default
Referenced by getBaseName().
Member Function Documentation
dump()
DEMANGLE_DUMP_METHOD void Node::dump () const
Referenced by llvm::SDValue::dump(), and getBaseName().
getBaseName()
virtual StringView Node::getBaseName () const inline virtual
Reimplemented in SpecialSubstitution, ExpandedSpecialSubstitution, StdQualifiedName, GlobalQualifiedName, NameWithTemplateArgs, QualifiedName, NestedName, and NameType.
Definition at line 202 of file ItaniumDemangle.h.
References DEMANGLE_DUMP_METHOD, dump(), and ~Node().
Referenced by NestedName::getBaseName(), QualifiedName::getBaseName(), NameWithTemplateArgs::getBaseName(), and StdQualifiedName::getBaseName().
getKind()
Kind Node::getKind () const inline
Definition at line 175 of file ItaniumDemangle.h.
Referenced by ObjCProtoName::isObjCObject(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseCtorDtorName(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseTemplateArgs(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseTemplateParam(), BracedExpr::printLeft(), BracedRangeExpr::printLeft(), and LambdaExpr::printLeft().
getSyntaxNode()
virtual const Node* Node::getSyntaxNode (OutputStream &) const inline virtual
Reimplemented in ForwardTemplateReference, and ParameterPack.
Definition at line 183 of file ItaniumDemangle.h.
Referenced by ForwardTemplateReference::getSyntaxNode().
hasArray()
bool Node::hasArray (OutputStream & S) const inline
Definition at line 163 of file ItaniumDemangle.h.
References hasArraySlow(), Unknown, and Yes.
Referenced by QualType::hasArraySlow(), ForwardTemplateReference::hasArraySlow(), PointerToMemberType::printLeft(), and PointerToMemberType::printRight().
hasArraySlow()
virtual bool Node::hasArraySlow (OutputStream &) const inline virtual
Reimplemented in ForwardTemplateReference, ParameterPack, ArrayType, and QualType.
Definition at line 178 of file ItaniumDemangle.h.
Referenced by hasArray().
hasFunction()
bool Node::hasFunction (OutputStream & S) const inline
Definition at line 169 of file ItaniumDemangle.h.
References hasFunctionSlow(), Unknown, and Yes.
Referenced by QualType::hasFunctionSlow(), ForwardTemplateReference::hasFunctionSlow(), PointerToMemberType::printLeft(), and PointerToMemberType::printRight().
hasFunctionSlow()
virtual bool Node::hasFunctionSlow (OutputStream &) const inline virtual
Reimplemented in ForwardTemplateReference, ParameterPack, FunctionEncoding, FunctionType, and QualType.
Definition at line 179 of file ItaniumDemangle.h.
Referenced by hasFunction().
hasRHSComponent()
bool Node::hasRHSComponent (OutputStream & S) const inline
Definition at line 157 of file ItaniumDemangle.h.
References hasRHSComponentSlow(), Unknown, and Yes.
Referenced by QualType::hasRHSComponentSlow(), ReferenceType::hasRHSComponentSlow(), PointerToMemberType::hasRHSComponentSlow(), ForwardTemplateReference::hasRHSComponentSlow(), and NonTypeTemplateParamDecl::printLeft().
hasRHSComponentSlow()
virtual bool Node::hasRHSComponentSlow (OutputStream &) const inline virtual
Reimplemented in ForwardTemplateReference, ParameterPack, FunctionEncoding, FunctionType, ArrayType, PointerToMemberType, ReferenceType, PointerType, and QualType.
Definition at line 177 of file ItaniumDemangle.h.
Referenced by hasRHSComponent().
print()
void Node::print (OutputStream & S) const inline
Definition at line 187 of file ItaniumDemangle.h.
References No, printLeft(), and printRight().
Referenced by llvm::ItaniumPartialDemangler::getFunctionDeclContextName(), ElaboratedTypeSpefType::printLeft(), ObjCProtoName::printLeft(), NoexceptSpec::printLeft(), FunctionEncoding::printLeft(), LiteralOperator::printLeft(), SpecialName::printLeft(), CtorVtableSpecialName::printLeft(), NestedName::printLeft(), LocalName::printLeft(), QualifiedName::printLeft(), VectorType::printLeft(), NameWithTemplateArgs::printLeft(), StdQualifiedName::printLeft(), BinaryExpr::printLeft(), ArraySubscriptExpr::printLeft(), PostfixExpr::printLeft(), ConditionalExpr::printLeft(), MemberExpr::printLeft(), EnclosingExpr::printLeft(), CallExpr::printLeft(), NewExpr::printLeft(), DeleteExpr::printLeft(), PrefixExpr::printLeft(), ConversionExpr::printLeft(), InitListExpr::printLeft(), BracedExpr::printLeft(), BracedRangeExpr::printLeft(), FoldExpr::printLeft(), ThrowExpr::printLeft(), UUIDOfExpr::printLeft(), StringLiteral::printLeft(), IntegerCastExpr::printLeft(), ArrayType::printRight(), FunctionType::printRight(), FunctionEncoding::printRight(), and NodeArray::printWithComma().
printLeft()
virtual void Node::printLeft (OutputStream &) const pure virtual
Implemented in FloatLiteralImpl< Float >, IntegerLiteral, IntegerCastExpr, LambdaExpr, StringLiteral, BoolExpr, UUIDOfExpr, ThrowExpr, FoldExpr, BracedRangeExpr, BracedExpr, InitListExpr, ConversionExpr, FunctionParam, PrefixExpr, DeleteExpr, NewExpr, CallExpr, SizeofParamPackExpr, CastExpr, EnclosingExpr, MemberExpr, ConditionalExpr, PostfixExpr, ArraySubscriptExpr, BinaryExpr, StructuredBindingName, ClosureTypeName, UnnamedTypeName, DtorName, CtorDtorName, SpecialSubstitution, ExpandedSpecialSubstitution, StdQualifiedName, GlobalQualifiedName, NameWithTemplateArgs, ForwardTemplateReference, TemplateArgs, ParameterPackExpansion, TemplateArgumentPack, ParameterPack, TemplateParamPackDecl, TemplateTemplateParamDecl, NonTypeTemplateParamDecl, TypeTemplateParamDecl, SyntheticTemplateParamName, PixelVectorType, VectorType, QualifiedName, LocalName, NestedName, CtorVtableSpecialName, SpecialName, LiteralOperator, FunctionEncoding, DynamicExceptionSpec, NoexceptSpec, FunctionType, ArrayType, PointerToMemberType, ReferenceType, PointerType, ObjCProtoName, EnableIfAttr, AbiTagAttr, ElaboratedTypeSpefType, NameType, PostfixQualifiedType, ConversionOperatorType, QualType, VendorExtQualType, DotSuffix, and NodeArrayNode.
Referenced by print(), QualType::printLeft(), AbiTagAttr::printLeft(), PointerToMemberType::printLeft(), NonTypeTemplateParamDecl::printLeft(), ParameterPack::printLeft(), ForwardTemplateReference::printLeft(), DtorName::printLeft(), and CastExpr::printLeft().
printRight()
virtual void Node::printRight (OutputStream &) const inline virtual
Reimplemented in ForwardTemplateReference, ParameterPack, TemplateParamPackDecl, TemplateTemplateParamDecl, NonTypeTemplateParamDecl, TypeTemplateParamDecl, FunctionEncoding, FunctionType, ArrayType, PointerToMemberType, ReferenceType, PointerType, and QualType.
Definition at line 200 of file ItaniumDemangle.h.
Referenced by print(), QualType::printRight(), PointerToMemberType::printRight(), NonTypeTemplateParamDecl::printRight(), ParameterPack::printRight(), and ForwardTemplateReference::printRight().
visit()
template<typename Fn > void Node::visit (Fn F) const
Visit the most-derived object corresponding to this object.
Visit the node.
Calls F(P), where P is the node cast to the appropriate derived class.
Definition at line 2150 of file ItaniumDemangle.h.
References assert(), CASE, and FOR_EACH_NODE_KIND.
Referenced by Node().
Member Data Documentation
ArrayCache
Cache Node::ArrayCache
Track if this node is a (possibly qualified) array type.
This can affect how we format the output string.
Definition at line 136 of file ItaniumDemangle.h.
Referenced by ParameterPack::ParameterPack().
FunctionCache
Cache Node::FunctionCache
Track if this node is a (possibly qualified) function type.
This can affect how we format the output string.
Definition at line 140 of file ItaniumDemangle.h.
Referenced by ParameterPack::ParameterPack().
RHSComponentCache
Cache Node::RHSComponentCache
Tracks if this node has a component on its right side, in which case we need to call printRight.
Definition at line 132 of file ItaniumDemangle.h.
Referenced by ParameterPack::ParameterPack().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h