LLVM: llvm::orc::ReExportsMaterializationUnit Class Reference
llvm::orc::ReExportsMaterializationUnit Class Reference
A materialization unit for symbol aliases.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
ReExportsMaterializationUnit (JITDylib *SourceJD, JITDylibLookupFlags SourceJDLookupFlags, SymbolAliasMap Aliases, VModuleKey K)
SourceJD is allowed to be nullptr, in which case the source JITDylib is taken to be whatever JITDylib these definitions are materialized in (and MatchNonExported has no effect).
StringRef getName () const override
Return the name of this materialization unit.
Public Member Functions inherited from llvm::orc::MaterializationUnit
MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, VModuleKey K)
virtual ~MaterializationUnit ()
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
void doMaterialize (JITDylib &JD)
Called by materialization dispatchers (see ExecutionSession::DispatchMaterializationFunction) to trigger materialization of this MaterializationUnit.
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Additional Inherited Members
Protected Attributes inherited from llvm::orc::MaterializationUnit
SymbolFlagsMap SymbolFlags
VModuleKey K
Detailed Description
A materialization unit for symbol aliases.
Allows existing symbols to be aliased with alternate flags.
Definition at line 637 of file Core.h.
Constructor & Destructor Documentation
ReExportsMaterializationUnit()
llvm::orc::ReExportsMaterializationUnit::ReExportsMaterializationUnit (JITDylib * SourceJD, JITDylibLookupFlags SourceJDLookupFlags, SymbolAliasMap Aliases, VModuleKey K)
SourceJD is allowed to be nullptr, in which case the source JITDylib is taken to be whatever JITDylib these definitions are materialized in (and MatchNonExported has no effect).
This is useful for defining aliases within a JITDylib.
Note: Care must be taken that no sets of aliases form a cycle, as such a cycle will result in a deadlock when any symbol in the cycle is resolved.
Definition at line 581 of file Core.cpp.
Member Function Documentation
getName()
StringRef llvm::orc::ReExportsMaterializationUnit::getName () const override virtual
Return the name of this materialization unit.
Useful for debugging output.
Implements llvm::orc::MaterializationUnit.
Definition at line 588 of file Core.cpp.
References llvm::orc::SymbolLookupSet::add(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::dbgs(), llvm::orc::MaterializationResponsibility::delegate(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::orc::SymbolLookupSet::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::orc::JITDylib::getExecutionSession(), llvm::orc::JITDylib::getName(), llvm::orc::MaterializationResponsibility::getRequestedSymbols(), llvm::orc::MaterializationResponsibility::getTargetJITDylib(), I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), LLVM_DEBUG, Name, llvm::orc::reexports(), llvm::orc::MaterializationResponsibility::replace(), llvm::orc::Resolved, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::orc::Static, llvm::orc::symbolAliases(), and llvm::orc::MaterializationUnit::SymbolFlags.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp