LLVM: llvm::ARMAsmPrinter Class Reference
llvm::ARMAsmPrinter Class Reference
#include "Target/ARM/ARMAsmPrinter.h"
Public Member Functions
ARMAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
void printOperand (const MachineInstr *MI, int OpNum, raw_ostream &O)
void PrintSymbolOperand (const MachineOperand &MO, raw_ostream &O) override
Print the MachineOperand as a symbol.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNum, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNum, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const override
Let the target do anything it needs to do after emitting inlineasm.
void EmitJumpTableAddrs (const MachineInstr *MI)
void EmitJumpTableInsts (const MachineInstr *MI)
void EmitJumpTableTBInst (const MachineInstr *MI, unsigned OffsetWidth)
void EmitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - This uses the EmitInstruction() method to print assembly for each instruction.
void EmitConstantPool () override
Print to the current output stream assembly representations of the constants in the constant pool MCP.
void EmitFunctionBodyEnd () override
Targets can override this to emit stuff after the last basic block in the function.
void EmitFunctionEntryLabel () override
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
void EmitStartOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the start of their file.
void EmitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
void EmitXXStructor (const DataLayout &DL, const Constant *CV) override
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
void EmitGlobalVariable (const GlobalVariable *GV) override
Emit the specified global variable to the .s file.
MCSymbol * GetCPISymbol (unsigned CPID) const override
Return the symbol for the specified constant pool entry.
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp)
void LowerPATCHABLE_FUNCTION_ENTER (const MachineInstr &MI)
void LowerPATCHABLE_FUNCTION_EXIT (const MachineInstr &MI)
void LowerPATCHABLE_TAIL_CALL (const MachineInstr &MI)
unsigned getISAEncoding () override
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV) override
EmitMachineConstantPoolValue - Print a machine constantpool value to the .s file.
Public Member Functions inherited from llvm::AsmPrinter
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getCurExceptionSym ()
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
bool doFinalization (Module &M) override
Shut down the asmprinter.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void EmitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitRemarksSection (RemarkStreamer &RS)
CFIMoveType needsCFIMoves () const
bool needsOnlyDebugCFIMoves () const
Returns false if needsCFIMoves() == CFI_M_EH for any function in the module.
bool needsSEHMoves ()
virtual void EmitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void EmitAlignment (Align Alignment, const GlobalObject *GV=nullptr) const
Emit an alignment directive to the specified power of two boundary.
virtual const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void EmitGlobalConstant (const DataLayout &DL, const Constant *CV)
Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps (StackMaps &SM)
Emit the stack maps.
virtual void EmitFunctionBodyStart ()
Targets can override this to emit stuff before the first basic block in the function.
virtual void EmitBasicBlockStart (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the start of a basic block.
virtual void EmitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual void EmitFunctionDescriptor ()
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void EmitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void EmitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset".
void EmitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void EmitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-byte offset of a string from the start of its section.
void EmitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void EmitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual void EmitDebugValue (const MCExpr *Value, unsigned Size) const
Emit the directive and value for debug thread local expression.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T >
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void emitInlineAsmStart () const
Let the target do anything it needs to do before emitting inlineasm.
void EmitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
void EmitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum SledKind : uint8_t {
SledKind::FUNCTION_ENTER = 0, SledKind::FUNCTION_EXIT = 1, SledKind::TAIL_CALL = 2, SledKind::LOG_ARGS_ENTER = 3,
SledKind::CUSTOM_EVENT = 4, SledKind::TYPED_EVENT = 5
}
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
using GOTEquivUsePair = std::pair< const GlobalVariable *, unsigned >
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
Static Public Member Functions inherited from llvm::AsmPrinter
static Align getGVAlignment (const GlobalValue *GV, const DataLayout &DL, Align InAlign=Align::None())
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineLoopInfo.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE
Optimization remark emitter.
MachineBlockFrequencyInfo * MBFI
ProfileSummaryInfo * PSI
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
unsigned XRayFnUniqueID = 0
DenseMap< const MCSection *, unsigned > PatchableFunctionEntryID
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::AsmPrinter
MCSymbol * CurrentFnBegin = nullptr
SmallVector< HandlerInfo, 1 > Handlers
A vector of all debug/EH info emitters we should use.
Detailed Description
Definition at line 31 of file ARMAsmPrinter.h.
Constructor & Destructor Documentation
ARMAsmPrinter()
ARMAsmPrinter::ARMAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) explicit
Definition at line 55 of file ARMAsmPrinter.cpp.
Member Function Documentation
EmitConstantPool()
void llvm::ARMAsmPrinter::EmitConstantPool () inline override virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 93 of file ARMAsmPrinter.h.
References llvm::ARM::M.
EmitEndOfAsmFile()
void ARMAsmPrinter::EmitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 514 of file ARMAsmPrinter.cpp.
References llvm::ARMBuildAttrs::ABI_optimization_goals, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::AsmPrinter::EmitAlignment(), llvm::ARMTargetStreamer::emitAttribute(), emitNonLazySymbolPointer(), llvm::ARMTargetStreamer::finishAttributeSection(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MCObjectFileInfo::getNonLazySymbolPointerSection(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetMachine::getTargetTriple(), llvm::MachineModuleInfoMachO::GetThreadLocalGVStubList(), llvm::MCObjectFileInfo::getThreadLocalPointerSection(), llvm::Triple::isOSBinFormatMachO(), llvm::ARMSubtarget::isTargetAEABI(), llvm::ARMSubtarget::isTargetGNUAEABI(), llvm::ARMSubtarget::isTargetMuslAEABI(), llvm::MCAF_SubsectionsViaSymbols, llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutStreamer, llvm::AsmPrinter::TM, and llvm::TT.
EmitFunctionBodyEnd()
void ARMAsmPrinter::EmitFunctionBodyEnd () override virtual
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 60 of file ARMAsmPrinter.cpp.
References llvm::MCDR_DataRegionEnd, and llvm::AsmPrinter::OutStreamer.
EmitFunctionEntryLabel()
void ARMAsmPrinter::EmitFunctionEntryLabel () override virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 69 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::ARMFunctionInfo::isThumbFunction(), llvm::MCAF_Code16, llvm::MCAF_Code32, and llvm::AsmPrinter::OutStreamer.
EmitGlobalVariable()
void ARMAsmPrinter::EmitGlobalVariable (const GlobalVariable * GV) override virtual
Emit the specified global variable to the .s file.
EmitGlobalVariable - Emit the specified global variable to the .s file.
Reimplemented from llvm::AsmPrinter.
Definition at line 96 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::EmitGlobalVariable().
emitInlineAsmEnd()
void ARMAsmPrinter::emitInlineAsmEnd (const MCSubtargetInfo & StartInfo, const MCSubtargetInfo * EndInfo) const override virtual
Let the target do anything it needs to do after emitting inlineasm.
This callback can be used restore the original mode in case the inlineasm contains directives to switch modes. StartInfo - the original subtarget info before inline asm EndInfo - the final subtarget info after parsing the inline asm, or NULL if the value is unknown.
Reimplemented from llvm::AsmPrinter.
Definition at line 464 of file ARMAsmPrinter.cpp.
References isThumb(), llvm::MCAF_Code16, llvm::MCAF_Code32, and llvm::AsmPrinter::OutStreamer.
EmitInstruction()
void ARMAsmPrinter::EmitInstruction (const MachineInstr *) override virtual
Targets should implement this to emit instructions.
CONSTPOOL_ENTRY - This instruction represents a floating constant pool in the function. The first operand is the ID# for this instruction, the second is the index into the MachineConstantPool that this is, the third is the size in bytes of this constant pool entry. The required alignment is specified on the basic block holding this MI.
Reimplemented from llvm::AsmPrinter.
Definition at line 1244 of file ARMAsmPrinter.cpp.
References llvm::MCInstBuilder::addExpr(), llvm::MCInstBuilder::addImm(), llvm::MCInst::addOperand(), llvm::MCInstBuilder::addReg(), llvm::AArch64ISD::ADR, llvm::ARMCC::AL, assert(), llvm::MCOI::BranchTarget, llvm::MachineConstantPoolEntry::ConstVal, llvm::convertAddSubFlagsOpcode(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::ARMMCExpr::createLower16(), llvm::MCOperand::createReg(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::ARMMCExpr::createUpper16(), llvm::AsmPrinter::EmitGlobalConstant(), llvm::ARMTargetStreamer::emitInst(), EmitJumpTableAddrs(), EmitJumpTableInsts(), EmitJumpTableTBInst(), EmitMachineConstantPoolValue(), llvm::AsmPrinter::EmitToStreamer(), FramePtr, llvm::MachineInstr::FrameSetup, llvm::ARMSubtarget::genExecuteOnly(), getBFLabel(), llvm::MachineConstantPool::getConstants(), GetCPISymbol(), llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineInstr::getFlag(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), getPICLabel(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::ARMSubtarget::hasV4TOps(), llvm::ARMSubtarget::hasV5TOps(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isKill(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::MachineOperand::isMBB(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isSymbol(), llvm::ARMSubtarget::isTargetDarwin(), llvm::ARMSubtarget::isTargetEHABICompatible(), llvm::ARMSubtarget::isTargetMachO(), llvm::ARMSubtarget::isTargetWindows(), llvm_unreachable, llvm::LowerARMMachineInstrToMCInst(), LowerPATCHABLE_FUNCTION_ENTER(), LowerPATCHABLE_FUNCTION_EXIT(), LowerPATCHABLE_TAIL_CALL(), llvm::MachineConstantPoolEntry::MachineCPVal, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::MCInst::setOpcode(), llvm::ISD::TRAP, llvm::ARMSubtarget::useR7AsFramePointer(), and llvm::MachineConstantPoolEntry::Val.
EmitJumpTableAddrs()
void ARMAsmPrinter::EmitJumpTableAddrs (const MachineInstr * MI)
Definition at line 937 of file ARMAsmPrinter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::EmitAlignment(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getOperand(), llvm::AsmPrinter::isPositionIndependent(), llvm::ARMSubtarget::isROPI(), llvm::ARMFunctionInfo::isThumbFunction(), llvm::HexagonISD::JT, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT32, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by EmitInstruction().
EmitJumpTableInsts()
void ARMAsmPrinter::EmitJumpTableInsts (const MachineInstr * MI)
Definition at line 983 of file ARMAsmPrinter.cpp.
References llvm::ARMCC::AL, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::MCSymbolRefExpr::create(), llvm::AsmPrinter::EmitAlignment(), llvm::AsmPrinter::EmitToStreamer(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getOperand(), llvm::HexagonISD::JT, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by EmitInstruction().
EmitJumpTableTBInst()
void ARMAsmPrinter::EmitJumpTableTBInst (const MachineInstr * MI, unsigned OffsetWidth)
Definition at line 1011 of file ARMAsmPrinter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::ARM, assert(), llvm::MachineConstantPoolEntry::ConstVal, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createDiv(), llvm::MCBinaryExpr::createSub(), llvm::ARMFunctionInfo::EHPrologueRemappedRegs, llvm::AsmPrinter::EmitAlignment(), llvm::ARMTargetStreamer::emitMovSP(), llvm::ARMTargetStreamer::emitPad(), llvm::ARMTargetStreamer::emitRegSave(), llvm::ARMTargetStreamer::emitSetFP(), llvm::SmallVectorBase::empty(), llvm::errs(), FramePtr, llvm::MachineInstr::FrameSetup, llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), GetCPISymbol(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineInstr::getFlag(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isImplicit(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::ARMSubtarget::isThumb1Only(), llvm::MachineOperand::isUndef(), llvm::HexagonISD::JT, LLVM_FALLTHROUGH, llvm_unreachable, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::AsmPrinter::MAI, llvm::MachineInstr::mayStore(), llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT16, llvm::MCDR_DataRegionJT8, llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::MachineInstr::print(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, and llvm::MachineConstantPoolEntry::Val.
Referenced by EmitInstruction().
EmitMachineConstantPoolValue()
void ARMAsmPrinter::EmitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) override virtual
EmitMachineConstantPoolValue - Print a machine constantpool value to the .s file.
Reimplemented from llvm::AsmPrinter.
Definition at line 859 of file ARMAsmPrinter.cpp.
References assert(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::AsmPrinter::EmitGlobalConstant(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::getCurExceptionSym(), llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::ARMConstantPoolValue::getLabelId(), llvm::ARMConstantPoolValue::getModifier(), getModifierVariantKind(), llvm::ARMConstantPoolValue::getPCAdjustment(), getPICLabel(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineConstantPoolValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ARMConstantPoolValue::isBlockAddress(), llvm::ARMConstantPoolValue::isExtSymbol(), llvm::ARMConstantPoolValue::isGlobalValue(), llvm::ARMConstantPoolValue::isLSDA(), llvm::ARMConstantPoolValue::isMachineBasicBlock(), llvm::ARMConstantPoolValue::isPromotedGlobal(), llvm::ARMSubtarget::isTargetMachO(), llvm::ARMII::MO_NONLAZY, llvm::ARMConstantPoolValue::mustAddCurrentAddress(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and Size.
Referenced by EmitInstruction(), and getModifierVariantKind().
EmitStartOfAsmFile()
void ARMAsmPrinter::EmitStartOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 474 of file ARMAsmPrinter.cpp.
References llvm::Module::getModuleInlineAsm(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isThumb(), llvm::MCAF_Code16, llvm::MCAF_SyntaxUnified, llvm::AsmPrinter::OutStreamer, llvm::AsmPrinter::TM, and llvm::TT.
EmitXXStructor()
void ARMAsmPrinter::EmitXXStructor (const DataLayout & DL, const Constant * CV) override virtual
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented from llvm::AsmPrinter.
Definition at line 79 of file ARMAsmPrinter.cpp.
References assert(), llvm::MCSymbolRefExpr::create(), llvm::dyn_cast(), E, llvm::AsmPrinter::getDataLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ARMSubtarget::isTargetELF(), llvm::ARMII::MO_NO_FLAG, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, Size, llvm::Constant::stripPointerCasts(), llvm::MCSymbolRefExpr::VK_ARM_TARGET1, and llvm::MCSymbolRefExpr::VK_None.
GetCPISymbol()
MCSymbol * ARMAsmPrinter::GetCPISymbol (unsigned CPID) const override virtual
Return the symbol for the specified constant pool entry.
GetCPISymbol - Return the symbol for the specified constant pool entry.
Reimplemented from llvm::AsmPrinter.
Definition at line 242 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getFunctionNumber(), llvm::MCContext::getOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), Name, and llvm::AsmPrinter::OutContext.
Referenced by EmitInstruction(), EmitJumpTableTBInst(), lowerOperand(), and printOperand().
getISAEncoding()
unsigned llvm::ARMAsmPrinter::getISAEncoding () inline override virtual
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented from llvm::AsmPrinter.
Definition at line 133 of file ARMAsmPrinter.h.
References llvm::Triple::ARMSubArch_v6m, llvm::Triple::ARMSubArch_v7m, llvm::ARM::DW_ISA_ARM_arm, llvm::ARM::DW_ISA_ARM_thumb, llvm::Triple::getSubArch(), GetSymbolRef(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatMachO(), isThumb(), llvm::Triple::isThumb(), llvm::ARMBuildAttrs::Symbol, and llvm::TT.
getPassName()
StringRef llvm::ARMAsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 72 of file ARMAsmPrinter.h.
References F(), MI, llvm::RISCVFenceField::O, and printOperand().
lowerOperand()
bool ARMAsmPrinter::lowerOperand (const MachineOperand & MO, MCOperand & MCOp)
Definition at line 72 of file ARMMCInstLower.cpp.
References assert(), llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createFPImm(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::ARMSubtarget::genExecuteOnly(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::ConstantFP::getValueAPF(), llvm::APFloatBase::IEEEdouble(), llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, llvm::AsmPrinter::OutContext, and llvm::APFloatBase::rmTowardZero.
Referenced by llvm::LowerARMMachineInstrToMCInst().
LowerPATCHABLE_FUNCTION_ENTER()
void ARMAsmPrinter::LowerPATCHABLE_FUNCTION_ENTER (const MachineInstr & MI)
Definition at line 216 of file ARMMCInstLower.cpp.
References llvm::AsmPrinter::FUNCTION_ENTER.
Referenced by EmitInstruction().
LowerPATCHABLE_FUNCTION_EXIT()
void ARMAsmPrinter::LowerPATCHABLE_FUNCTION_EXIT (const MachineInstr & MI)
Definition at line 221 of file ARMMCInstLower.cpp.
References llvm::AsmPrinter::FUNCTION_EXIT.
Referenced by EmitInstruction().
LowerPATCHABLE_TAIL_CALL()
void ARMAsmPrinter::LowerPATCHABLE_TAIL_CALL (const MachineInstr & MI)
Definition at line 226 of file ARMMCInstLower.cpp.
References llvm::AsmPrinter::TAIL_CALL.
Referenced by EmitInstruction().
PrintAsmMemoryOperand()
bool ARMAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 436 of file ARMAsmPrinter.cpp.
References assert(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ARMInstPrinter::getRegisterName(), and llvm::MachineOperand::isReg().
PrintAsmOperand()
bool ARMAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & O) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate for machine specific ExtraCodes or when the arch-independent handling would be too complex otherwise.
Reimplemented from llvm::AsmPrinter.
Definition at line 262 of file ARMAsmPrinter.cpp.
References contains(), llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetRegisterInfo::getRegClass(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::ARMInstPrinter::getRegisterName(), llvm::TargetRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::InlineAsm::hasRegClassConstraint(), llvm::MachineOperand::isImm(), llvm::ARMBaseTargetMachine::isLittleEndian(), llvm::MachineOperand::isReg(), llvm::InlineAsm::isUseOperandTiedToDef(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::AsmPrinter::MF, llvm::InlineAsm::MIOp_FirstOperand, llvm::AsmPrinter::PrintAsmOperand(), printOperand(), Reg, SubReg, llvm::AsmPrinter::TM, and TRI.
printOperand()
void ARMAsmPrinter::printOperand (const MachineInstr * MI, int OpNum, raw_ostream & O)
Definition at line 199 of file ARMAsmPrinter.cpp.
References assert(), contains(), llvm::ARMSubtarget::genExecuteOnly(), GetCPISymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::ARMInstPrinter::getRegisterName(), llvm::MachineOperand::getSubReg(), llvm::TargetRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::Register::isPhysicalRegister(), llvm_unreachable, llvm::AsmPrinter::MAI, llvm::AsmPrinter::MF, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::ARMII::MO_HI16, llvm::MachineOperand::MO_Immediate, llvm::ARMII::MO_LO16, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::Pass::print(), llvm::MCSymbol::print(), PrintSymbolOperand(), Reg, and TRI.
Referenced by PrintAsmOperand().
PrintSymbolOperand()
void ARMAsmPrinter::PrintSymbolOperand (const MachineOperand & MO, raw_ostream & OS) override virtual
Print the MachineOperand as a symbol.
Targets with complex handling of symbol references should override the base implementation.
Reimplemented from llvm::AsmPrinter.
Definition at line 187 of file ARMAsmPrinter.cpp.
References assert(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::isGlobal(), llvm::AsmPrinter::MAI, llvm::ARMII::MO_HI16, llvm::ARMII::MO_LO16, llvm::RISCVFenceField::O, llvm::Pass::print(), and llvm::AsmPrinter::printOffset().
Referenced by printOperand().
runOnMachineFunction()
bool ARMAsmPrinter::runOnMachineFunction (MachineFunction & F) override virtual
runOnMachineFunction - This uses the EmitInstruction() method to print assembly for each instruction.
Reimplemented from llvm::AsmPrinter.
Definition at line 106 of file ARMAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::CodeGenOpt::Aggressive, llvm::ARMCC::AL, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::EmitAlignment(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::EmitToStreamer(), llvm::AsmPrinter::emitXRayTable(), F(), llvm::MachineFunction::getConstantPool(), llvm::MachineFunction::getFunction(), llvm::ARMFunctionInfo::getGlobalsPromotedToConstantPool(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getOptLevel(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::GlobalValue::hasInternalLinkage(), llvm::Function::hasMinSize(), llvm::Function::hasOptNone(), llvm::Function::hasOptSize(), llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::ARMSubtarget::isTargetCOFF(), llvm::MCAF_Code16, llvm::CodeGenOpt::None, llvm::AsmPrinter::OutStreamer, llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, llvm::AsmPrinter::SetupMachineFunction(), and llvm::AsmPrinter::TM.
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMAsmPrinter.h
lib/Target/ARM/ARMAsmPrinter.cpp
lib/Target/ARM/ARMMCInstLower.cpp