LLVM: llvm::ARCMCInstLower Class Reference
llvm::ARCMCInstLower Class Reference
This class is used to lower an MachineInstr into an MCInst.
#include "Target/ARC/ARCMCInstLower.h"
Public Member Functions
ARCMCInstLower (MCContext *C, AsmPrinter &asmprinter)
void Lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand LowerOperand (const MachineOperand &MO, unsigned offset=0) const
Detailed Description
This class is used to lower an MachineInstr into an MCInst.
Definition at line 26 of file ARCMCInstLower.h.
Constructor & Destructor Documentation
ARCMCInstLower()
ARCMCInstLower::ARCMCInstLower (MCContext * C, AsmPrinter & asmprinter)
Definition at line 26 of file ARCMCInstLower.cpp.
References llvm::MCID::Add, assert(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::ARMBuildAttrs::Symbol, and llvm::MCSymbolRefExpr::VK_None.
Member Function Documentation
Lower()
void ARCMCInstLower::Lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 104 of file ARCMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::numbers::e, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCOperand::isValid(), LowerOperand(), and llvm::MCInst::setOpcode().
LowerOperand()
MCOperand ARCMCInstLower::LowerOperand (const MachineOperand & MO, unsigned offset = 0) const
Definition at line 76 of file ARCMCInstLower.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::MachineOperand::MO_RegisterMask.
Referenced by Lower().
The documentation for this class was generated from the following files:
lib/Target/ARC/ARCMCInstLower.h
lib/Target/ARC/ARCMCInstLower.cpp