LLVM: llvm::MipsAsmBackend Class Reference
llvm::MipsAsmBackend Class Reference
#include "Target/Mips/MCTargetDesc/MipsAsmBackend.h"
Public Member Functions
MipsAsmBackend (const Target &T, const MCRegisterInfo &MRI, const Triple &TT, StringRef CPU, bool N32)
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const override
ApplyFixup - Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Optional< MCFixupKind > getFixupKind (StringRef Name) const override
Map a relocation name used in .reloc to a fixup kind.
const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
unsigned getNumFixupKinds () const override
Get the number of target specific fixup kinds.
bool writeNopData (raw_ostream &OS, uint64_t Count) const override
WriteNopData - Write an (optimal) nop sequence of Count bytes to the given output.
bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target) override
Hook to check if a relocation is needed for some target specific reason.
bool isMicroMips (const MCSymbol *Sym) const override
Check whether a given symbol has been flagged with MICROMIPS flag.
Target Relaxation Interfaces
bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const override
MayNeedRelaxation - Check whether the given instruction may need relaxation.
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout) const override
fixupNeedsRelaxation - Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
void relaxInstruction (const MCInst &Inst, const MCSubtargetInfo &STI, MCInst &Res) const override
RelaxInstruction - Relax the instruction in the given fragment to the next wider instruction.
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual void alignBranchesBegin (MCObjectStreamer &OS, const MCInst &Inst)
Give the target a chance to manipulate state related to instruction alignment (e.g.
virtual void alignBranchesEnd (MCObjectStreamer &OS, const MCInst &Inst)
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, uint64_t &Value, bool &WasForced)
virtual bool requiresDiffExpressionRelocations () const
Check whether the given target requires emitting differences of two symbols as a set of relocations.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Additional Inherited Members
Public Attributes inherited from llvm::MCAsmBackend
const support::endianness Endian
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (support::endianness Endian)
Detailed Description
Definition at line 30 of file MipsAsmBackend.h.
Constructor & Destructor Documentation
MipsAsmBackend()
llvm::MipsAsmBackend::MipsAsmBackend (const Target & T, const MCRegisterInfo & MRI, const Triple & TT, StringRef CPU, bool N32) inline
Definition at line 35 of file MipsAsmBackend.h.
References applyFixup(), llvm::HexStyle::Asm, createObjectTargetWriter(), llvm::Data, Fixup, getFixupKind(), getFixupKindInfo(), and Name.
Referenced by llvm::createMipsAsmBackend().
Member Function Documentation
applyFixup()
void MipsAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const override virtual
ApplyFixup - Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Implements llvm::MCAsmBackend.
Definition at line 243 of file MipsAsmBackend.cpp.
References adjustFixupValue(), calculateMMLEIndex(), llvm::MCAsmBackend::Endian, llvm::Mips::fixup_MICROMIPS_PC10_S1, llvm::Mips::fixup_Mips_16, llvm::Mips::fixup_Mips_64, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::MCAssembler::getContext(), getFixupKindInfo(), llvm::MCFixup::getKind(), llvm::MCFixup::getOffset(), llvm::support::little, llvm::BitmaskEnumDetail::Mask(), needsMMLEByteOrder(), and llvm::MCFixupKindInfo::TargetSize.
Referenced by MipsAsmBackend().
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > MipsAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 219 of file MipsAsmBackend.cpp.
References llvm::createMipsELFObjectWriter().
Referenced by MipsAsmBackend().
fixupNeedsRelaxation()
bool llvm::MipsAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout) const inline override virtual
fixupNeedsRelaxation - Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Implements llvm::MCAsmBackend.
Definition at line 69 of file MipsAsmBackend.h.
References llvm_unreachable.
getFixupKind()
Optional< MCFixupKind > MipsAsmBackend::getFixupKind (StringRef Name) const override virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 303 of file MipsAsmBackend.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::Mips::fixup_MICROMIPS_CALL16, llvm::Mips::fixup_MICROMIPS_GOT16, llvm::Mips::fixup_MICROMIPS_GOT_DISP, llvm::Mips::fixup_MICROMIPS_GOT_OFST, llvm::Mips::fixup_MICROMIPS_GOT_PAGE, llvm::Mips::fixup_MICROMIPS_GOTTPREL, llvm::Mips::fixup_MICROMIPS_JALR, llvm::Mips::fixup_MICROMIPS_TLS_DTPREL_HI16, llvm::Mips::fixup_MICROMIPS_TLS_DTPREL_LO16, llvm::Mips::fixup_MICROMIPS_TLS_GD, llvm::Mips::fixup_MICROMIPS_TLS_LDM, llvm::Mips::fixup_MICROMIPS_TLS_TPREL_HI16, llvm::Mips::fixup_MICROMIPS_TLS_TPREL_LO16, llvm::Mips::fixup_Mips_CALL16, llvm::Mips::fixup_Mips_CALL_HI16, llvm::Mips::fixup_Mips_CALL_LO16, llvm::Mips::fixup_Mips_DTPREL_HI, llvm::Mips::fixup_Mips_DTPREL_LO, llvm::Mips::fixup_Mips_GOT, llvm::Mips::fixup_Mips_GOT_DISP, llvm::Mips::fixup_Mips_GOT_HI16, llvm::Mips::fixup_Mips_GOT_LO16, llvm::Mips::fixup_Mips_GOT_OFST, llvm::Mips::fixup_Mips_GOT_PAGE, llvm::Mips::fixup_Mips_GOTTPREL, llvm::Mips::fixup_Mips_JALR, llvm::Mips::fixup_Mips_TLSGD, llvm::Mips::fixup_Mips_TLSLDM, llvm::Mips::fixup_Mips_TPREL_HI, llvm::Mips::fixup_Mips_TPREL_LO, llvm::FK_Data_4, llvm::FK_NONE, llvm::MCAsmBackend::getFixupKind(), getFixupKindInfo(), and Name.
Referenced by MipsAsmBackend().
getFixupKindInfo()
const MCFixupKindInfo & MipsAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 346 of file MipsAsmBackend.cpp.
References llvm::array_lengthof(), assert(), llvm::MCAsmBackend::Endian, llvm::FirstTargetFixupKind, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), getNumFixupKinds(), llvm::support::little, and llvm::Mips::NumTargetFixupKinds.
Referenced by applyFixup(), getFixupKind(), and MipsAsmBackend().
getNumFixupKinds()
unsigned llvm::MipsAsmBackend::getNumFixupKinds () const inline override virtual
Get the number of target specific fixup kinds.
Implements llvm::MCAsmBackend.
Definition at line 51 of file MipsAsmBackend.h.
References llvm::Mips::NumTargetFixupKinds.
Referenced by getFixupKindInfo().
isMicroMips()
bool MipsAsmBackend::isMicroMips (const MCSymbol * Sym) const override virtual
Check whether a given symbol has been flagged with MICROMIPS flag.
Reimplemented from llvm::MCAsmBackend.
Definition at line 576 of file MipsAsmBackend.cpp.
References llvm::ELF::STO_MIPS_MICROMIPS.
Referenced by relaxInstruction().
mayNeedRelaxation()
bool llvm::MipsAsmBackend::mayNeedRelaxation (const MCInst & Inst, const MCSubtargetInfo & STI) const inline override virtual
MayNeedRelaxation - Check whether the given instruction may need relaxation.
Parameters
Inst - The instruction to test.
Implements llvm::MCAsmBackend.
Definition at line 62 of file MipsAsmBackend.h.
relaxInstruction()
void llvm::MipsAsmBackend::relaxInstruction (const MCInst & Inst, const MCSubtargetInfo & STI, MCInst & Res) const inline override virtual
RelaxInstruction - Relax the instruction in the given fragment to the next wider instruction.
Parameters
Inst - The instruction to relax, which may be the same as the output.
[out] Res On return, the relaxed instruction.
Implements llvm::MCAsmBackend.
Definition at line 83 of file MipsAsmBackend.h.
References isMicroMips(), shouldForceRelocation(), and writeNopData().
shouldForceRelocation()
bool MipsAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target) override virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented from llvm::MCAsmBackend.
Definition at line 533 of file MipsAsmBackend.cpp.
References llvm::Mips::fixup_MICROMIPS_CALL16, llvm::Mips::fixup_MICROMIPS_GOT16, llvm::Mips::fixup_MICROMIPS_GOT_DISP, llvm::Mips::fixup_MICROMIPS_GOT_OFST, llvm::Mips::fixup_MICROMIPS_GOT_PAGE, llvm::Mips::fixup_MICROMIPS_GOTTPREL, llvm::Mips::fixup_MICROMIPS_JALR, llvm::Mips::fixup_MICROMIPS_TLS_DTPREL_HI16, llvm::Mips::fixup_MICROMIPS_TLS_DTPREL_LO16, llvm::Mips::fixup_MICROMIPS_TLS_GD, llvm::Mips::fixup_MICROMIPS_TLS_LDM, llvm::Mips::fixup_MICROMIPS_TLS_TPREL_HI16, llvm::Mips::fixup_MICROMIPS_TLS_TPREL_LO16, llvm::Mips::fixup_Mips_CALL16, llvm::Mips::fixup_Mips_CALL_HI16, llvm::Mips::fixup_Mips_CALL_LO16, llvm::Mips::fixup_Mips_DTPREL_HI, llvm::Mips::fixup_Mips_DTPREL_LO, llvm::Mips::fixup_Mips_GOT, llvm::Mips::fixup_Mips_GOT_DISP, llvm::Mips::fixup_Mips_GOT_HI16, llvm::Mips::fixup_Mips_GOT_LO16, llvm::Mips::fixup_Mips_GOT_OFST, llvm::Mips::fixup_Mips_GOT_PAGE, llvm::Mips::fixup_Mips_GOTTPREL, llvm::Mips::fixup_Mips_JALR, llvm::Mips::fixup_Mips_TLSGD, llvm::Mips::fixup_Mips_TLSLDM, llvm::Mips::fixup_Mips_TPREL_HI, llvm::Mips::fixup_Mips_TPREL_LO, llvm::FixupKind(), and llvm::MCFixup::getKind().
Referenced by relaxInstruction().
writeNopData()
bool MipsAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count) const override virtual
WriteNopData - Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 521 of file MipsAsmBackend.cpp.
References llvm::raw_ostream::write_zeros().
Referenced by relaxInstruction().
The documentation for this class was generated from the following files:
lib/Target/Mips/MCTargetDesc/MipsAsmBackend.h
lib/Target/Mips/MCTargetDesc/MipsAsmBackend.cpp