LLVM: llvm::sys::path::reverse_iterator Class Reference
llvm::sys::path::reverse_iterator Class Reference
Reverse path iterator.
#include "llvm/Support/Path.h"
Public Member Functions
reference operator* () const
reverse_iterator & operator++ ()
bool operator== (const reverse_iterator &RHS) const
ptrdiff_t operator- (const reverse_iterator &RHS) const
Difference in bytes between this and RHS.
Public Member Functions inherited from llvm::iterator_facade_base< reverse_iterator, std::input_iterator_tag, const StringRef >
reverse_iterator operator+ (std::ptrdiff_t n) const
reverse_iterator operator- (std::ptrdiff_t n) const
reverse_iterator & operator++ ()
reverse_iterator operator++ (int)
reverse_iterator & operator-- ()
reverse_iterator operator-- (int)
bool operator!= (const reverse_iterator &RHS) const
bool operator> (const reverse_iterator &RHS) const
bool operator<= (const reverse_iterator &RHS) const
bool operator>= (const reverse_iterator &RHS) const
const StringRef * operator-> ()
const StringRef * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Friends
reverse_iterator rbegin (StringRef path, Style style)
Get reverse begin iterator over path.
reverse_iterator rend (StringRef path)
Get reverse end iterator over path.
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< reverse_iterator, std::input_iterator_tag, const StringRef >
enum
Detailed Description
Reverse path iterator.
This is an input iterator that iterates over the individual components in path in reverse order. The traversal order is exactly reversed from that of const_iterator
Definition at line 78 of file Path.h.
Member Function Documentation
operator*()
reference llvm::sys::path::reverse_iterator::operator* () const inline
Definition at line 90 of file Path.h.
References llvm::sys::path::append(), llvm::sys::path::begin(), llvm::sys::path::convert_to_slash(), llvm::sys::path::end(), llvm::sys::path::extension(), llvm::sys::path::filename(), llvm::sys::path::get_separator(), llvm::sys::path::has_extension(), llvm::sys::path::has_filename(), llvm::sys::path::has_parent_path(), llvm::sys::path::has_relative_path(), llvm::sys::path::has_root_directory(), llvm::sys::path::has_root_name(), llvm::sys::path::has_root_path(), llvm::sys::path::has_stem(), llvm::sys::path::home_directory(), llvm::sys::path::is_absolute(), llvm::sys::path::is_relative(), llvm::sys::path::is_separator(), llvm::sys::path::native, llvm::operator-(), llvm::operator==(), llvm::sys::path::parent_path(), llvm::sys::path::rbegin(), llvm::sys::path::relative_path(), llvm::sys::path::remove_dots(), llvm::sys::path::remove_filename(), llvm::sys::path::remove_leading_dotslash(), llvm::sys::path::rend(), llvm::sys::path::replace_extension(), llvm::sys::path::replace_path_prefix(), llvm::sys::path::root_directory(), llvm::sys::path::root_name(), llvm::sys::path::root_path(), llvm::sys::path::stem(), and llvm::sys::path::system_temp_directory().
operator++()
reverse_iterator & llvm::sys::path::reverse_iterator::operator++ ()
Definition at line 312 of file Path.cpp.
References llvm::sys::path::is_separator(), and llvm::StringRef::npos.
operator-()
ptrdiff_t llvm::sys::path::reverse_iterator::operator- (const reverse_iterator & RHS) const
Difference in bytes between this and RHS.
Definition at line 342 of file Path.cpp.
operator==()
bool llvm::sys::path::reverse_iterator::operator== (const reverse_iterator & RHS) const
Definition at line 337 of file Path.cpp.
References llvm::StringRef::begin().
Friends And Related Function Documentation
rbegin
reverse_iterator rbegin (StringRef path, Style style = Style::native) friend
Get reverse begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first reverse component of path.
Definition at line 295 of file Path.cpp.
rend
reverse_iterator rend (StringRef path) friend
Get reverse end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the reverse end of path.
Definition at line 304 of file Path.cpp.
The documentation for this class was generated from the following files:
include/llvm/Support/Path.h
lib/Support/Path.cpp