LLVM: llvm::orc::IRLayer Class Reference
llvm::orc::IRLayer Class Reference abstract
Interface for layers that accept LLVM IR.
#include "llvm/ExecutionEngine/Orc/Layer.h"
Public Member Functions
IRLayer (ExecutionSession &ES, const IRMaterializationUnit::ManglingOptions *&MO)
virtual ~IRLayer ()
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this layer.
const IRMaterializationUnit::ManglingOptions *& getManglingOptions () const
Get the mangling options for this layer.
void setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit)
Sets the CloneToNewContextOnEmit flag (false by default).
bool getCloneToNewContextOnEmit () const
Returns the current value of the CloneToNewContextOnEmit flag.
virtual Error add (JITDylib &JD, ThreadSafeModule TSM, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
virtual void emit (MaterializationResponsibility R, ThreadSafeModule TSM)=0
Emit should materialize the given IR.
Detailed Description
Interface for layers that accept LLVM IR.
Definition at line 64 of file Layer.h.
Constructor & Destructor Documentation
IRLayer()
llvm::orc::IRLayer::IRLayer (ExecutionSession & ES, const IRMaterializationUnit::ManglingOptions *& MO) inline
Definition at line 66 of file Layer.h.
~IRLayer()
llvm::orc::IRLayer::~IRLayer () virtual
Definition at line 19 of file Layer.cpp.
Member Function Documentation
add()
Error llvm::orc::IRLayer::add (JITDylib & JD, ThreadSafeModule TSM, VModuleKey K = VModuleKey()) virtual
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Definition at line 21 of file Layer.cpp.
References llvm::orc::JITDylib::define(), and getManglingOptions().
emit()
virtual void llvm::orc::IRLayer::emit (MaterializationResponsibility R, ThreadSafeModule TSM) pure virtual
Emit should materialize the given IR.
Implemented in llvm::orc::IRSpeculationLayer, llvm::orc::CompileOnDemandLayer, llvm::orc::IRCompileLayer, and llvm::orc::IRTransformLayer.
Referenced by llvm::orc::BasicIRLayerMaterializationUnit::BasicIRLayerMaterializationUnit(), and llvm::orc::IRTransformLayer::emit().
getCloneToNewContextOnEmit()
bool llvm::orc::IRLayer::getCloneToNewContextOnEmit () const inline
Returns the current value of the CloneToNewContextOnEmit flag.
Definition at line 94 of file Layer.h.
References add(), llvm::orc::MaterializationUnit::K, and llvm::orc::IRMaterializationUnit::TSM.
Referenced by llvm::orc::BasicIRLayerMaterializationUnit::BasicIRLayerMaterializationUnit().
getExecutionSession()
ExecutionSession& llvm::orc::IRLayer::getExecutionSession () inline
Returns the ExecutionSession for this layer.
Definition at line 73 of file Layer.h.
Referenced by llvm::orc::IRTransformLayer::emit(), llvm::orc::IRCompileLayer::emit(), and llvm::orc::CompileOnDemandLayer::emit().
getManglingOptions()
const IRMaterializationUnit::ManglingOptions*& llvm::orc::IRLayer::getManglingOptions () const inline
Get the mangling options for this layer.
Definition at line 76 of file Layer.h.
Referenced by add().
setCloneToNewContextOnEmit()
void llvm::orc::IRLayer::setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit) inline
Sets the CloneToNewContextOnEmit flag (false by default).
When set, IR modules added to this layer will be cloned on to a new context before emit is called. This can be used by clients who want to load all IR using one LLVMContext (to save memory via type and constant uniquing), but want to move Modules to fresh contexts before compiling them to enable concurrent compilation. Single threaded clients, or clients who load every module on a new context, need not set this.
Definition at line 89 of file Layer.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Layer.h
lib/ExecutionEngine/Orc/Layer.cpp