LLVM: llvm::GCModuleInfo Class Reference
llvm::GCModuleInfo Class Reference
An analysis pass which caches information about the entire Module.
#include "llvm/CodeGen/GCMetadata.h"
Public Types
using FuncInfoVec = std::vector< std::unique_ptr< GCFunctionInfo > >
List of per function info objects.
using iterator = SmallVector< std::unique_ptr< GCStrategy >, 1 >::const_iterator
Public Member Functions
GCStrategy * getGCStrategy (const StringRef Name)
Lookup the GCStrategy object associated with the given gc name.
FuncInfoVec::iterator funcinfo_begin ()
FuncInfoVec::iterator funcinfo_end ()
GCModuleInfo ()
void clear ()
clear - Resets the pass.
iterator begin () const
begin/end - Iterators for used strategies.
iterator end () const
GCFunctionInfo & getFunctionInfo (const Function &F)
get - Look up function metadata.
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
An analysis pass which caches information about the entire Module.
Records both the function level information used by GCRoots and a cache of the 'active' gc strategy objects for the current Module.
Definition at line 152 of file GCMetadata.h.
Member Typedef Documentation
FuncInfoVec
using llvm::GCModuleInfo::FuncInfoVec = std::vector<std::unique_ptr<GCFunctionInfo> >
List of per function info objects.
In theory, Each of these may be associated with a different GC.
Definition at line 166 of file GCMetadata.h.
iterator
using llvm::GCModuleInfo::iterator = SmallVector<std::unique_ptr<GCStrategy>, 1>::const_iterator
Definition at line 181 of file GCMetadata.h.
Constructor & Destructor Documentation
GCModuleInfo()
GCModuleInfo::GCModuleInfo ()
Definition at line 63 of file GCMetadata.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeGCModuleInfoPass().
Member Function Documentation
begin()
iterator llvm::GCModuleInfo::begin () const inline
begin/end - Iterators for used strategies.
Definition at line 194 of file GCMetadata.h.
References llvm::SmallVectorTemplateCommon< T >::begin().
Referenced by llvm::AsmPrinter::doFinalization(), and llvm::AsmPrinter::emitStackMaps().
clear()
void GCModuleInfo::clear ()
clear - Resets the pass.
Any pass, which uses GCModuleInfo, should call it in doFinalization().
Definition at line 82 of file GCMetadata.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear().
Referenced by llvm::createGCInfoPrinter().
end()
iterator llvm::GCModuleInfo::end () const inline
Definition at line 195 of file GCMetadata.h.
References llvm::SmallVectorTemplateCommon< T >::end(), and F().
Referenced by llvm::AsmPrinter::doFinalization(), and llvm::AsmPrinter::emitStackMaps().
funcinfo_begin()
FuncInfoVec::iterator llvm::GCModuleInfo::funcinfo_begin () inline
Definition at line 168 of file GCMetadata.h.
Referenced by EmitCamlGlobal().
funcinfo_end()
FuncInfoVec::iterator llvm::GCModuleInfo::funcinfo_end () inline
Definition at line 169 of file GCMetadata.h.
Referenced by EmitCamlGlobal().
getFunctionInfo()
GCFunctionInfo & GCModuleInfo::getFunctionInfo (const Function & F)
get - Look up function metadata.
This is currently assumed have the side effect of initializing the associated GCStrategy. That will soon change.
Definition at line 67 of file GCMetadata.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Function::getGC(), getGCStrategy(), llvm::Function::hasGC(), I, and llvm::GlobalValue::isDeclaration().
Referenced by llvm::createGCInfoPrinter(), and INITIALIZE_PASS_BEGIN().
getGCStrategy()
GCStrategy * GCModuleInfo::getGCStrategy (const StringRef Name)
Lookup the GCStrategy object associated with the given gc name.
Objects are owned internally; No caller should attempt to delete the returned objects.
Definition at line 147 of file GCMetadata.cpp.
References llvm::Registry< T >::begin(), llvm::Registry< T >::end(), llvm::Registry< T >::entries(), error, llvm::Entry::Name, Name, and llvm::report_fatal_error().
Referenced by getFunctionInfo().
Member Data Documentation
ID
char GCModuleInfo::ID = 0 static
Definition at line 183 of file GCMetadata.h.
Referenced by INITIALIZE_PASS().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GCMetadata.h
lib/CodeGen/GCMetadata.cpp