LLVM: llvm::SpecialCaseList Class Reference
llvm::SpecialCaseList Class Reference
#include "llvm/Support/SpecialCaseList.h"
Classes
class Matcher
Represents a set of regular expressions.
struct Section
Public Member Functions
~SpecialCaseList ()
bool inSection (StringRef Section, StringRef Prefix, StringRef Query, StringRef Category=StringRef()) const
Returns true, if special case list contains a line.
unsigned inSectionBlame (StringRef Section, StringRef Prefix, StringRef Query, StringRef Category=StringRef()) const
Returns the line number corresponding to the special case list entry if the special case list contains a line.
Static Public Member Functions
static std::unique_ptr< SpecialCaseList > create (const std::vector< std::string > &Paths, llvm::vfs::FileSystem &FS, std::string &Error)
Parses the special case list entries from files.
static std::unique_ptr< SpecialCaseList > create (const MemoryBuffer *MB, std::string &Error)
Parses the special case list from a memory buffer.
static std::unique_ptr< SpecialCaseList > createOrDie (const std::vector< std::string > &Paths, llvm::vfs::FileSystem &FS)
Parses the special case list entries from files.
Protected Types
using SectionEntries = StringMap< StringMap< Matcher > >
Protected Member Functions
bool createInternal (const std::vector< std::string > &Paths, vfs::FileSystem &VFS, std::string &Error)
bool createInternal (const MemoryBuffer *MB, std::string &Error)
SpecialCaseList ()=default
SpecialCaseList (SpecialCaseList const &)=delete
SpecialCaseList & operator= (SpecialCaseList const &)=delete
bool parse (const MemoryBuffer *MB, StringMap< size_t > &SectionsMap, std::string &Error)
Parses just-constructed SpecialCaseList entries from a memory buffer.
unsigned inSectionBlame (const SectionEntries &Entries, StringRef Prefix, StringRef Query, StringRef Category) const
Protected Attributes
std::vector< Section > Sections
Detailed Description
Definition at line 67 of file SpecialCaseList.h.
Member Typedef Documentation
SectionEntries
using llvm::SpecialCaseList::SectionEntries = StringMap<StringMap<Matcher> > protected
Definition at line 132 of file SpecialCaseList.h.
Constructor & Destructor Documentation
~SpecialCaseList()
llvm::SpecialCaseList::~SpecialCaseList ()
Definition at line 202 of file SpecialCaseList.cpp.
SpecialCaseList() [1/2]
llvm::SpecialCaseList::SpecialCaseList () protected default
Referenced by create().
SpecialCaseList() [2/2]
llvm::SpecialCaseList::SpecialCaseList (SpecialCaseList const &) protected delete
Member Function Documentation
create() [1/2]
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::create (const std::vector< std::string > & Paths, llvm::vfs::FileSystem & FS, std::string & Error) static
Parses the special case list entries from files.
On failure, returns 0 and writes an error message to string.
Definition at line 74 of file SpecialCaseList.cpp.
References SpecialCaseList().
Referenced by createOrDie().
create() [2/2]
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::create (const MemoryBuffer * MB, std::string & Error) static
Parses the special case list from a memory buffer.
On failure, returns 0 and writes an error message to string.
Definition at line 82 of file SpecialCaseList.cpp.
References SpecialCaseList().
createInternal() [1/2]
bool llvm::SpecialCaseList::createInternal (const std::vector< std::string > & Paths, vfs::FileSystem & VFS, std::string & Error) protected
Definition at line 99 of file SpecialCaseList.cpp.
References llvm::ErrorOr< T >::get(), llvm::vfs::FileSystem::getBufferForFile(), llvm::ErrorOr< T >::getError(), parse(), and Sections.
createInternal() [2/2]
bool llvm::SpecialCaseList::createInternal (const MemoryBuffer * MB, std::string & Error) protected
Definition at line 118 of file SpecialCaseList.cpp.
References parse(), and Sections.
createOrDie()
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::createOrDie (const std::vector< std::string > & Paths, llvm::vfs::FileSystem & FS) static
Parses the special case list entries from files.
On failure, reports a fatal error.
Definition at line 91 of file SpecialCaseList.cpp.
References create(), llvm::Error, and llvm::report_fatal_error().
Referenced by INITIALIZE_PASS().
inSection()
bool llvm::SpecialCaseList::inSection (StringRef Section, StringRef Prefix, StringRef Query, StringRef Category = StringRef()) const
Returns true, if special case list contains a line.
@Prefix:<E>=@Category
where satisfies wildcard expression <E> in a given .
Definition at line 204 of file SpecialCaseList.cpp.
References inSectionBlame().
inSectionBlame() [1/2]
unsigned llvm::SpecialCaseList::inSectionBlame (StringRef Section, StringRef Prefix, StringRef Query, StringRef Category = StringRef()) const
Returns the line number corresponding to the special case list entry if the special case list contains a line.
@Prefix:<E>=@Category
where satisfies wildcard expression <E> in a given . Returns zero if there is no blacklist entry corresponding to this expression.
Definition at line 209 of file SpecialCaseList.cpp.
References Sections.
Referenced by inSection().
inSectionBlame() [2/2]
unsigned llvm::SpecialCaseList::inSectionBlame (const SectionEntries & Entries, StringRef Prefix, StringRef Query, StringRef Category) const protected
Definition at line 222 of file SpecialCaseList.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), and I.
operator=()
SpecialCaseList& llvm::SpecialCaseList::operator= (SpecialCaseList const &) protected delete
parse()
bool llvm::SpecialCaseList::parse (const MemoryBuffer * MB, StringMap< size_t > & SectionsMap, std::string & Error) protected
Parses just-constructed SpecialCaseList entries from a memory buffer.
Definition at line 126 of file SpecialCaseList.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), E, llvm::SmallVectorTemplateCommon< T >::end(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::MemoryBuffer::getBuffer(), I, llvm::Regex::isValid(), llvm::cl::Prefix, llvm::ARMBuildAttrs::Section, Sections, and llvm::StringRef::split().
Referenced by createInternal().
Member Data Documentation
Sections
std::vector<Section> llvm::SpecialCaseList::Sections protected
Definition at line 141 of file SpecialCaseList.h.
Referenced by createInternal(), inSectionBlame(), and parse().
The documentation for this class was generated from the following files:
include/llvm/Support/SpecialCaseList.h
lib/Support/SpecialCaseList.cpp