LLVM: llvm::xray::RecordPrinter Class Reference
llvm::xray::RecordPrinter Class Reference
#include "llvm/XRay/RecordPrinter.h"
Public Member Functions
RecordPrinter (raw_ostream &O, std::string D)
RecordPrinter (raw_ostream &O)
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
Definition at line 22 of file RecordPrinter.h.
Constructor & Destructor Documentation
RecordPrinter() [1/2]
llvm::xray::RecordPrinter::RecordPrinter (raw_ostream & O, std::string D) inline explicit
Definition at line 27 of file RecordPrinter.h.
RecordPrinter() [2/2]
llvm::xray::RecordPrinter::RecordPrinter (raw_ostream & O) inline explicit
Definition at line 30 of file RecordPrinter.h.
References visit().
Member Function Documentation
visit() [1/12]
Error llvm::xray::RecordPrinter::visit (BufferExtents & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 15 of file RecordPrinter.cpp.
References llvm::formatv(), llvm::xray::BufferExtents::size(), and llvm::Error::success().
Referenced by RecordPrinter(), and llvm::xray::BlockPrinter::visit().
visit() [2/12]
Error llvm::xray::RecordPrinter::visit (WallclockRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 20 of file RecordPrinter.cpp.
References llvm::formatv(), llvm::xray::WallclockRecord::nanos(), llvm::xray::WallclockRecord::seconds(), and llvm::Error::success().
visit() [3/12]
Error llvm::xray::RecordPrinter::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 26 of file RecordPrinter.cpp.
References llvm::xray::NewCPUIDRecord::cpuid(), llvm::formatv(), llvm::Error::success(), and llvm::xray::NewCPUIDRecord::tsc().
visit() [4/12]
Error llvm::xray::RecordPrinter::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 31 of file RecordPrinter.cpp.
References llvm::formatv(), llvm::Error::success(), and llvm::xray::TSCWrapRecord::tsc().
visit() [5/12]
Error llvm::xray::RecordPrinter::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 36 of file RecordPrinter.cpp.
References llvm::xray::CustomEventRecord::cpu(), llvm::xray::CustomEventRecord::data(), llvm::formatv(), llvm::xray::CustomEventRecord::size(), llvm::Error::success(), and llvm::xray::CustomEventRecord::tsc().
visit() [6/12]
Error llvm::xray::RecordPrinter::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 59 of file RecordPrinter.cpp.
References llvm::xray::CallArgRecord::arg(), llvm::formatv(), and llvm::Error::success().
visit() [7/12]
Error llvm::xray::RecordPrinter::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 64 of file RecordPrinter.cpp.
References llvm::formatv(), llvm::xray::PIDRecord::pid(), and llvm::Error::success().
visit() [8/12]
Error llvm::xray::RecordPrinter::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 69 of file RecordPrinter.cpp.
References llvm::formatv(), llvm::Error::success(), and llvm::xray::NewBufferRecord::tid().
visit() [9/12]
Error llvm::xray::RecordPrinter::visit (EndBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 74 of file RecordPrinter.cpp.
References llvm::Error::success().
visit() [10/12]
Error llvm::xray::RecordPrinter::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 79 of file RecordPrinter.cpp.
References llvm::xray::CUSTOM_EVENT, llvm::xray::FunctionRecord::delta(), llvm::xray::ENTER, llvm::xray::ENTER_ARG, llvm::xray::EXIT, llvm::formatv(), llvm::xray::FunctionRecord::functionId(), llvm::xray::FunctionRecord::recordType(), llvm::Error::success(), llvm::xray::TAIL_EXIT, and llvm::xray::TYPED_EVENT.
visit() [11/12]
Error llvm::xray::RecordPrinter::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 44 of file RecordPrinter.cpp.
References llvm::xray::CustomEventRecordV5::data(), llvm::xray::CustomEventRecordV5::delta(), llvm::formatv(), llvm::xray::CustomEventRecordV5::size(), and llvm::Error::success().
visit() [12/12]
Error llvm::xray::RecordPrinter::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 51 of file RecordPrinter.cpp.
References llvm::xray::TypedEventRecord::data(), llvm::xray::TypedEventRecord::delta(), llvm::xray::TypedEventRecord::eventType(), llvm::formatv(), llvm::xray::TypedEventRecord::size(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/XRay/RecordPrinter.h
lib/XRay/RecordPrinter.cpp