LLVM: llvm::LoopVersioning Class Reference
llvm::LoopVersioning Class Reference
This class emits a version of the loop where run-time checks ensure that may-alias pointers can't overlap.
#include "llvm/Transforms/Utils/LoopVersioning.h"
Public Member Functions
LoopVersioning (const LoopAccessInfo &LAI, Loop *L, LoopInfo *LI, DominatorTree *DT, ScalarEvolution *SE, bool UseLAIChecks=true)
Expects LoopAccessInfo, Loop, LoopInfo, DominatorTree as input.
void versionLoop ()
Performs the CFG manipulation part of versioning the loop including the DominatorTree and LoopInfo updates.
void versionLoop (const SmallVectorImpl< Instruction *> &DefsUsedOutside)
Same but if the client has already precomputed the set of values used outside the loop, this API will allows passing that.
Loop * getVersionedLoop ()
Returns the versioned loop.
Loop * getNonVersionedLoop ()
Returns the fall-back loop.
void setAliasChecks (SmallVector< RuntimePointerChecking::PointerCheck, 4 > Checks)
Sets the runtime alias checks for versioning the loop.
void setSCEVChecks (SCEVUnionPredicate Check)
Sets the runtime SCEV checks for versioning the loop.
void annotateLoopWithNoAlias ()
Annotate memory instructions in the versioned loop with no-alias metadata based on the memchecks issued.
void prepareNoAliasMetadata ()
Set up the aliasing scopes based on the memchecks.
void annotateInstWithNoAlias (Instruction *VersionedInst, const Instruction *OrigInst)
Add the noalias annotations to VersionedInst.
Detailed Description
This class emits a version of the loop where run-time checks ensure that may-alias pointers can't overlap.
It currently only supports single-exit loops and assumes that the loop already has a preheader.
Definition at line 35 of file LoopVersioning.h.
Constructor & Destructor Documentation
LoopVersioning()
LoopVersioning::LoopVersioning (const LoopAccessInfo & LAI, Loop * L, LoopInfo * LI, DominatorTree * DT, ScalarEvolution * SE, bool UseLAIChecks = true)
Expects LoopAccessInfo, Loop, LoopInfo, DominatorTree as input.
It uses runtime check provided by the user. If UseLAIChecks is true, we will retain the default checks made by LAI. Otherwise, construct an object having no checks and we expect the user to add them.
Definition at line 34 of file LoopVersioning.cpp.
References assert(), llvm::RuntimePointerChecking::getChecks(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopAccessInfo::getPSE(), llvm::LoopAccessInfo::getRuntimePointerChecking(), llvm::PredicatedScalarEvolution::getUnionPredicate(), llvm::Loop::isLoopSimplifyForm(), setAliasChecks(), and setSCEVChecks().
Member Function Documentation
annotateInstWithNoAlias()
void LoopVersioning::annotateInstWithNoAlias (Instruction * VersionedInst, const Instruction * OrigInst)
Add the noalias annotations to VersionedInst.
OrigInst is the instruction corresponding to VersionedInst in the original loop. Initialize the aliasing scopes with prepareNoAliasMetadata once before this can be called.
Definition at line 224 of file LoopVersioning.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), annotateLoopWithNoAlias(), AnnotateNoAlias, llvm::MDNode::concatenate(), Context, llvm::depth_first(), F(), llvm::MDNode::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Instruction::getMetadata(), llvm::LoopAccessInfo::getNumRuntimePointerChecks(), llvm::PassRegistry::getPassRegistry(), llvm::getPointerOperand(), llvm::LoopAccessInfo::getPSE(), llvm::PredicatedScalarEvolution::getUnionPredicate(), llvm::LoopAccessInfo::hasConvergentOp(), llvm::initializeLoopVersioningPassPass(), llvm::SCEVUnionPredicate::isAlwaysTrue(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), runOnFunction(), llvm::Instruction::setMetadata(), and versionLoop().
Referenced by annotateLoopWithNoAlias(), and getNonVersionedLoop().
annotateLoopWithNoAlias()
void LoopVersioning::annotateLoopWithNoAlias ()
Annotate memory instructions in the versioned loop with no-alias metadata based on the memchecks issued.
This is just wrapper that calls prepareNoAliasMetadata and annotateInstWithNoAlias on the instructions of the versioned loop.
Definition at line 211 of file LoopVersioning.cpp.
References annotateInstWithNoAlias(), AnnotateNoAlias, llvm::LoopAccessInfo::getDepChecker(), llvm::MemoryDepChecker::getMemoryInstructions(), I, and prepareNoAliasMetadata().
Referenced by annotateInstWithNoAlias(), and getNonVersionedLoop().
getNonVersionedLoop()
Loop* llvm::LoopVersioning::getNonVersionedLoop () inline
Returns the fall-back loop.
Control flows here if pointers in the loop may alias (i.e. one of the memchecks failed).
Definition at line 71 of file LoopVersioning.h.
References annotateInstWithNoAlias(), annotateLoopWithNoAlias(), Check(), I, prepareNoAliasMetadata(), setAliasChecks(), and setSCEVChecks().
getVersionedLoop()
Loop* llvm::LoopVersioning::getVersionedLoop () inline
Returns the versioned loop.
Control flows here if pointers in the loop don't alias (i.e. all memchecks passed). (This loop is actually the same as the original loop that we got constructed with.)
Definition at line 67 of file LoopVersioning.h.
prepareNoAliasMetadata()
void LoopVersioning::prepareNoAliasMetadata ()
Set up the aliasing scopes based on the memchecks.
This needs to be called before the first call to annotateInstWithNoAlias.
Definition at line 169 of file LoopVersioning.cpp.
References Check(), llvm::RuntimePointerChecking::CheckingGroups, Context, llvm::MDBuilder::createAnonymousAliasScope(), llvm::MDBuilder::createAnonymousAliasScopeDomain(), llvm::MDNode::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::RuntimePointerChecking::getPointerInfo(), llvm::LoopAccessInfo::getRuntimePointerChecking(), llvm::RuntimePointerChecking::PointerInfo::PointerValue, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by annotateLoopWithNoAlias(), and getNonVersionedLoop().
setAliasChecks()
void LoopVersioning::setAliasChecks (SmallVector< RuntimePointerChecking::PointerCheck, 4 > Checks)
Sets the runtime alias checks for versioning the loop.
Definition at line 47 of file LoopVersioning.cpp.
Referenced by getNonVersionedLoop(), isLoadConditional(), and LoopVersioning().
setSCEVChecks()
void LoopVersioning::setSCEVChecks (SCEVUnionPredicate Check)
Sets the runtime SCEV checks for versioning the loop.
Definition at line 52 of file LoopVersioning.cpp.
Referenced by getNonVersionedLoop(), and LoopVersioning().
versionLoop() [1/2]
void llvm::LoopVersioning::versionLoop () inline
Performs the CFG manipulation part of versioning the loop including the DominatorTree and LoopInfo updates.
The loop that was used to construct the class will be the "versioned" loop i.e. the loop that will receive control if all the memchecks pass.
This allows the loop transform pass to operate on the same loop regardless of whether versioning was necessary or not:
for each loop L: analyze L if versioning is necessary version L transform L
Definition at line 58 of file LoopVersioning.h.
References llvm::findDefsUsedOutsideOfLoop(), and versionLoop().
Referenced by annotateInstWithNoAlias(), and versionLoop().
versionLoop() [2/2]
void LoopVersioning::versionLoop (const SmallVectorImpl< Instruction *> & DefsUsedOutside)
Same but if the client has already precomputed the set of values used outside the loop, this API will allows passing that.
Definition at line 56 of file LoopVersioning.cpp.
References llvm::PHINode::addIncoming(), llvm::LoopAccessInfo::addRuntimeChecks(), assert(), llvm::BasicBlock::begin(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::cloneLoopWithPreheader(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::BinaryOperator::Create(), llvm::PHINode::Create(), llvm::BranchInst::Create(), llvm::dyn_cast(), llvm::ValueMap< KeyT, ValueT, Config >::end(), llvm::Instruction::eraseFromParent(), llvm::ValueMap< KeyT, ValueT, Config >::find(), llvm::BasicBlock::front(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValue(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getModule(), llvm::Value::getName(), llvm::User::getNumOperands(), llvm::LoopAccessInfo::getPSE(), llvm::BasicBlock::getTerminator(), llvm::PredicatedScalarEvolution::getUnionPredicate(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::remapInstructionsInBlocks(), llvm::ValueMapIterator< DenseMapT, KeyT >::ValueTypeProxy::second, llvm::Value::setName(), llvm::SplitBlock(), and llvm::Value::users().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/LoopVersioning.h
lib/Transforms/Utils/LoopVersioning.cpp