LLVM: llvm::DWARFDebugAranges Class Reference
llvm::DWARFDebugAranges Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugAranges.h"
Public Member Functions
void generate (DWARFContext *CTX)
uint64_t findAddress (uint64_t Address) const
Detailed Description
Definition at line 21 of file DWARFDebugAranges.h.
Member Function Documentation
findAddress()
uint64_t DWARFDebugAranges::findAddress (uint64_t Address) const
Definition at line 116 of file DWARFDebugAranges.cpp.
References llvm::Address, and llvm::partition_point().
Referenced by llvm::DWARFContext::getCompileUnitForOffset().
generate()
void DWARFDebugAranges::generate (DWARFContext * CTX)
Definition at line 40 of file DWARFDebugAranges.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::clear(), llvm::DWARFContext::compile_units(), E, llvm::WithColor::error(), llvm::DWARFObject::getArangesSection(), llvm::DWARFContext::getDWARFObj(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::DWARFContext::isLittleEndian(), llvm::sort(), llvm::Expected< T >::takeError(), and llvm::toString().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugAranges.h
lib/DebugInfo/DWARF/DWARFDebugAranges.cpp