LLVM: llvm::formatted_raw_ostream Class Reference
llvm::formatted_raw_ostream Class Reference
formatted_raw_ostream - A raw_ostream that wraps another one and keeps track of line and column position, allowing padding out to specific column boundaries and querying the number of lines written to the stream.
#include "llvm/Support/FormattedStream.h"
Public Member Functions
formatted_raw_ostream (raw_ostream &Stream)
formatted_raw_ostream - Open the specified file for writing.
formatted_raw_ostream ()
~formatted_raw_ostream () override
formatted_raw_ostream & PadToColumn (unsigned NewCol)
PadToColumn - Align the output to some column number.
unsigned getColumn ()
getColumn - Return the column number
unsigned getLine ()
getLine - Return the line number
raw_ostream & resetColor () override
Resets the colors to terminal defaults.
raw_ostream & reverseColor () override
Reverses the foreground and background colors.
raw_ostream & changeColor (enum Colors Color, bool Bold, bool BG) override
Changes the foreground color of text that will be output from this point forward.
bool is_displayed () const override
This function determines if this stream is connected to a "tty" or "console" window.
Public Member Functions inherited from llvm::raw_ostream
raw_ostream (bool unbuffered=false)
raw_ostream (const raw_ostream &)=delete
void operator= (const raw_ostream &)=delete
virtual ~raw_ostream ()
uint64_t tell () const
tell - Return the current offset with the file.
void SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
void SetBufferSize (size_t Size)
Set the stream to be buffered, using the specified buffer size.
size_t GetBufferSize () const
void SetUnbuffered ()
Set the stream to be unbuffered.
size_t GetNumBytesInBuffer () const
void flush ()
raw_ostream & operator<< (char C)
raw_ostream & operator<< (unsigned char C)
raw_ostream & operator<< (signed char C)
raw_ostream & operator<< (StringRef Str)
raw_ostream & operator<< (const char *Str)
raw_ostream & operator<< (const std::string &Str)
raw_ostream & operator<< (const SmallVectorImpl< char > &Str)
raw_ostream & operator<< (unsigned long N)
raw_ostream & operator<< (long N)
raw_ostream & operator<< (unsigned long long N)
raw_ostream & operator<< (long long N)
raw_ostream & operator<< (const void *P)
raw_ostream & operator<< (unsigned int N)
raw_ostream & operator<< (int N)
raw_ostream & operator<< (double N)
raw_ostream & write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
raw_ostream & operator<< (Colors C)
raw_ostream & write_uuid (const uuid_t UUID)
raw_ostream & write_escaped (StringRef Str, bool UseHexEscapes=false)
Output Str, turning '\', '', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
raw_ostream & write (unsigned char C)
raw_ostream & write (const char *Ptr, size_t Size)
raw_ostream & operator<< (const format_object_base &Fmt)
raw_ostream & operator<< (const FormattedString &)
raw_ostream & operator<< (const FormattedNumber &)
raw_ostream & operator<< (const formatv_object_base &)
raw_ostream & operator<< (const FormattedBytes &)
raw_ostream & indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
raw_ostream & write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
virtual bool has_colors () const
This function determines if this stream is displayed and supports colors.
virtual void enable_colors (bool)
Additional Inherited Members
Public Types inherited from llvm::raw_ostream
enum Colors {
Colors::BLACK = 0, Colors::RED, Colors::GREEN, Colors::YELLOW,
Colors::BLUE, Colors::MAGENTA, Colors::CYAN, Colors::WHITE,
Colors::SAVEDCOLOR, Colors::RESET
}
using uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Static Public Attributes inherited from llvm::raw_ostream
static const Colors BLACK = Colors::BLACK
static const Colors RED = Colors::RED
static const Colors GREEN = Colors::GREEN
static const Colors YELLOW = Colors::YELLOW
static const Colors BLUE = Colors::BLUE
static const Colors MAGENTA = Colors::MAGENTA
static const Colors CYAN = Colors::CYAN
static const Colors WHITE = Colors::WHITE
static const Colors SAVEDCOLOR = Colors::SAVEDCOLOR
static const Colors RESET = Colors::RESET
Protected Member Functions inherited from llvm::raw_ostream
void SetBuffer (char *BufferStart, size_t Size)
Use the provided buffer as the raw_ostream buffer.
virtual size_t preferred_buffer_size () const
Return an efficient buffer size for the underlying output mechanism.
const char * getBufferStart () const
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Detailed Description
formatted_raw_ostream - A raw_ostream that wraps another one and keeps track of line and column position, allowing padding out to specific column boundaries and querying the number of lines written to the stream.
Definition at line 26 of file FormattedStream.h.
Constructor & Destructor Documentation
formatted_raw_ostream() [1/2]
llvm::formatted_raw_ostream::formatted_raw_ostream (raw_ostream & Stream) inline
formatted_raw_ostream - Open the specified file for writing.
If an error occurs, information about the error is put into ErrorInfo, and the stream should be immediately destroyed; the string will be empty if no error occurred.
As a side effect, the given Stream is set to be Unbuffered. This is because formatted_raw_ostream does its own buffering, so it doesn't want another layer of buffering to be happening underneath it.
Definition at line 88 of file FormattedStream.h.
formatted_raw_ostream() [2/2]
llvm::formatted_raw_ostream::formatted_raw_ostream () inline explicit
Definition at line 92 of file FormattedStream.h.
~formatted_raw_ostream()
llvm::formatted_raw_ostream::~formatted_raw_ostream () inline override
Definition at line 96 of file FormattedStream.h.
References llvm::raw_ostream::flush(), and PadToColumn().
Member Function Documentation
changeColor()
raw_ostream& llvm::formatted_raw_ostream::changeColor (enum Colors Color, bool Bold, bool BG) inline override virtual
Changes the foreground color of text that will be output from this point forward.
Parameters
Color ANSI color to use, the special SAVEDCOLOR can be used to change only the bold attribute, and keep colors untouched
Bold bold/brighter text, default false
BG if true change the background, default: change foreground
Returns
itself so it can be used within << invocations
Reimplemented from llvm::raw_ostream.
Definition at line 124 of file FormattedStream.h.
References llvm::raw_ostream::changeColor().
getColumn()
unsigned llvm::formatted_raw_ostream::getColumn () inline
getColumn - Return the column number
Definition at line 109 of file FormattedStream.h.
Referenced by PadToColumn().
getLine()
unsigned llvm::formatted_raw_ostream::getLine () inline
getLine - Return the line number
Definition at line 112 of file FormattedStream.h.
is_displayed()
bool llvm::formatted_raw_ostream::is_displayed () const inline override virtual
This function determines if this stream is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Reimplemented from llvm::raw_ostream.
Definition at line 129 of file FormattedStream.h.
References llvm::fdbgs(), llvm::ferrs(), llvm::fouts(), llvm::raw_ostream::GetBufferSize(), llvm::raw_ostream::is_displayed(), llvm::raw_ostream::SetBufferSize(), and llvm::raw_ostream::SetUnbuffered().
PadToColumn()
formatted_raw_ostream & formatted_raw_ostream::PadToColumn (unsigned NewCol)
PadToColumn - Align the output to some column number.
If the current column is already equal to or more than NewCol, PadToColumn inserts one space.
Parameters
NewCol - The column to move to.
NewCol - The column to move to.
Definition at line 67 of file FormattedStream.cpp.
References llvm::raw_ostream::getBufferStart(), getColumn(), llvm::raw_ostream::GetNumBytesInBuffer(), llvm::raw_ostream::indent(), llvm::max(), Size, and llvm::raw_ostream::write().
Referenced by emitComments(), printDwarfFileDirective(), and ~formatted_raw_ostream().
resetColor()
raw_ostream& llvm::formatted_raw_ostream::resetColor () inline override virtual
Resets the colors to terminal defaults.
Call this when you are done outputting colored text, or before program exit.
Reimplemented from llvm::raw_ostream.
Definition at line 114 of file FormattedStream.h.
References llvm::raw_ostream::resetColor().
reverseColor()
raw_ostream& llvm::formatted_raw_ostream::reverseColor () inline override virtual
Reverses the foreground and background colors.
Reimplemented from llvm::raw_ostream.
Definition at line 119 of file FormattedStream.h.
References llvm::raw_ostream::reverseColor().
The documentation for this class was generated from the following files:
include/llvm/Support/FormattedStream.h
lib/Support/FormattedStream.cpp