LLVM: llvm::pdb::NativeRawSymbol Class Reference
llvm::pdb::NativeRawSymbol Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeRawSymbol.h"
Public Member Functions
NativeRawSymbol (NativeSession &PDBSession, PDB_SymType Tag, SymIndexId SymbolId)
void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const override
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByVA (uint64_t VA) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLines () const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByVA (uint64_t VA, uint32_t Length) const override
void getDataBytes (SmallVector< uint8_t, 32 > &Bytes) const override
void getFrontEndVersion (VersionInfo &Version) const override
void getBackEndVersion (VersionInfo &Version) const override
PDB_MemberAccess getAccess () const override
uint32_t getAddressOffset () const override
uint32_t getAddressSection () const override
uint32_t getAge () const override
SymIndexId getArrayIndexTypeId () const override
uint32_t getBaseDataOffset () const override
uint32_t getBaseDataSlot () const override
SymIndexId getBaseSymbolId () const override
PDB_BuiltinType getBuiltinType () const override
uint32_t getBitPosition () const override
PDB_CallingConv getCallingConvention () const override
SymIndexId getClassParentId () const override
std::string getCompilerName () const override
uint32_t getCount () const override
uint32_t getCountLiveRanges () const override
PDB_Lang getLanguage () const override
SymIndexId getLexicalParentId () const override
std::string getLibraryName () const override
uint32_t getLiveRangeStartAddressOffset () const override
uint32_t getLiveRangeStartAddressSection () const override
uint32_t getLiveRangeStartRelativeVirtualAddress () const override
codeview::RegisterId getLocalBasePointerRegisterId () const override
SymIndexId getLowerBoundId () const override
uint32_t getMemorySpaceKind () const override
std::string getName () const override
uint32_t getNumberOfAcceleratorPointerTags () const override
uint32_t getNumberOfColumns () const override
uint32_t getNumberOfModifiers () const override
uint32_t getNumberOfRegisterIndices () const override
uint32_t getNumberOfRows () const override
std::string getObjectFileName () const override
uint32_t getOemId () const override
SymIndexId getOemSymbolId () const override
uint32_t getOffsetInUdt () const override
PDB_Cpu getPlatform () const override
uint32_t getRank () const override
codeview::RegisterId getRegisterId () const override
uint32_t getRegisterType () const override
uint32_t getRelativeVirtualAddress () const override
uint32_t getSamplerSlot () const override
uint32_t getSignature () const override
uint32_t getSizeInUdt () const override
uint32_t getSlot () const override
std::string getSourceFileName () const override
std::unique_ptr< IPDBLineNumber > getSrcLineOnTypeDefn () const override
uint32_t getStride () const override
SymIndexId getSubTypeId () const override
std::string getSymbolsFileName () const override
SymIndexId getSymIndexId () const override
uint32_t getTargetOffset () const override
uint32_t getTargetRelativeVirtualAddress () const override
uint64_t getTargetVirtualAddress () const override
uint32_t getTargetSection () const override
uint32_t getTextureSlot () const override
uint32_t getTimeStamp () const override
uint32_t getToken () const override
SymIndexId getTypeId () const override
uint32_t getUavSlot () const override
std::string getUndecoratedName () const override
std::string getUndecoratedNameEx (PDB_UndnameFlags Flags) const override
SymIndexId getUnmodifiedTypeId () const override
SymIndexId getUpperBoundId () const override
Variant getValue () const override
uint32_t getVirtualBaseDispIndex () const override
uint32_t getVirtualBaseOffset () const override
SymIndexId getVirtualTableShapeId () const override
std::unique_ptr< PDBSymbolTypeBuiltin > getVirtualBaseTableType () const override
PDB_DataKind getDataKind () const override
PDB_SymType getSymTag () const override
codeview::GUID getGuid () const override
int32_t getOffset () const override
int32_t getThisAdjust () const override
int32_t getVirtualBasePointerOffset () const override
PDB_LocType getLocationType () const override
PDB_Machine getMachineType () const override
codeview::ThunkOrdinal getThunkOrdinal () const override
uint64_t getLength () const override
uint64_t getLiveRangeLength () const override
uint64_t getVirtualAddress () const override
PDB_UdtType getUdtKind () const override
bool hasConstructor () const override
bool hasCustomCallingConvention () const override
bool hasFarReturn () const override
bool isCode () const override
bool isCompilerGenerated () const override
bool isConstType () const override
bool isEditAndContinueEnabled () const override
bool isFunction () const override
bool getAddressTaken () const override
bool getNoStackOrdering () const override
bool hasAlloca () const override
bool hasAssignmentOperator () const override
bool hasCTypes () const override
bool hasCastOperator () const override
bool hasDebugInfo () const override
bool hasEH () const override
bool hasEHa () const override
bool hasInlAsm () const override
bool hasInlineAttribute () const override
bool hasInterruptReturn () const override
bool hasFramePointer () const override
bool hasLongJump () const override
bool hasManagedCode () const override
bool hasNestedTypes () const override
bool hasNoInlineAttribute () const override
bool hasNoReturnAttribute () const override
bool hasOptimizedCodeDebugInfo () const override
bool hasOverloadedOperator () const override
bool hasSEH () const override
bool hasSecurityChecks () const override
bool hasSetJump () const override
bool hasStrictGSCheck () const override
bool isAcceleratorGroupSharedLocal () const override
bool isAcceleratorPointerTagLiveRange () const override
bool isAcceleratorStubFunction () const override
bool isAggregated () const override
bool isIntroVirtualFunction () const override
bool isCVTCIL () const override
bool isConstructorVirtualBase () const override
bool isCxxReturnUdt () const override
bool isDataAligned () const override
bool isHLSLData () const override
bool isHotpatchable () const override
bool isIndirectVirtualBaseClass () const override
bool isInterfaceUdt () const override
bool isIntrinsic () const override
bool isLTCG () const override
bool isLocationControlFlowDependent () const override
bool isMSILNetmodule () const override
bool isMatrixRowMajor () const override
bool isManagedCode () const override
bool isMSILCode () const override
bool isMultipleInheritance () const override
bool isNaked () const override
bool isNested () const override
bool isOptimizedAway () const override
bool isPacked () const override
bool isPointerBasedOnSymbolValue () const override
bool isPointerToDataMember () const override
bool isPointerToMemberFunction () const override
bool isPureVirtual () const override
bool isRValueReference () const override
bool isRefUdt () const override
bool isReference () const override
bool isRestrictedType () const override
bool isReturnValue () const override
bool isSafeBuffers () const override
bool isScoped () const override
bool isSdl () const override
bool isSingleInheritance () const override
bool isSplitted () const override
bool isStatic () const override
bool hasPrivateSymbols () const override
bool isUnalignedType () const override
bool isUnreached () const override
bool isValueUdt () const override
bool isVirtual () const override
bool isVirtualBaseClass () const override
bool isVirtualInheritance () const override
bool isVolatileType () const override
bool wasInlined () const override
std::string getUnused () const override
Public Member Functions inherited from llvm::pdb::IPDBRawSymbol
virtual ~IPDBRawSymbol ()
Protected Attributes
NativeSession & Session
PDB_SymType Tag
SymIndexId SymbolId
Friends
class SymbolCache
Detailed Description
Definition at line 21 of file NativeRawSymbol.h.
Constructor & Destructor Documentation
NativeRawSymbol()
NativeRawSymbol::NativeRawSymbol (NativeSession & PDBSession, PDB_SymType Tag, SymIndexId SymbolId)
Definition at line 18 of file NativeRawSymbol.cpp.
Member Function Documentation
dump()
void NativeRawSymbol::dump (raw_ostream & OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypePointer, llvm::pdb::NativeTypeVTShape, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypeArray, llvm::pdb::NativeTypeBuiltin, and llvm::pdb::NativeTypeTypedef.
Definition at line 22 of file NativeRawSymbol.cpp.
References llvm::pdb::dumpSymbolField(), llvm::pdb::dumpSymbolIdField(), Session, SymbolId, llvm::pdb::SymIndexId, and Tag.
Referenced by llvm::pdb::NativeCompilandSymbol::dump(), llvm::pdb::NativeSymbolEnumerator::dump(), llvm::pdb::NativeTypeArray::dump(), llvm::pdb::NativeTypeTypedef::dump(), llvm::pdb::NativeTypeVTShape::dump(), llvm::pdb::NativeTypePointer::dump(), llvm::pdb::NativeTypeEnum::dump(), llvm::pdb::NativeTypeUDT::dump(), and llvm::pdb::NativeTypeFunctionSig::dump().
findChildren() [1/2]
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findChildren (PDB_SymType Type) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig, and llvm::pdb::NativeTypeEnum.
Definition at line 32 of file NativeRawSymbol.cpp.
findChildren() [2/2]
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 37 of file NativeRawSymbol.cpp.
findChildrenByAddr()
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 43 of file NativeRawSymbol.cpp.
findChildrenByRVA()
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 55 of file NativeRawSymbol.cpp.
findChildrenByVA()
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 49 of file NativeRawSymbol.cpp.
findInlineeLines()
std::unique_ptr< IPDBEnumLineNumbers > NativeRawSymbol::findInlineeLines () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 77 of file NativeRawSymbol.cpp.
findInlineeLinesByAddr()
std::unique_ptr< IPDBEnumLineNumbers > NativeRawSymbol::findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 82 of file NativeRawSymbol.cpp.
findInlineeLinesByRVA()
std::unique_ptr< IPDBEnumLineNumbers > NativeRawSymbol::findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 88 of file NativeRawSymbol.cpp.
findInlineeLinesByVA()
std::unique_ptr< IPDBEnumLineNumbers > NativeRawSymbol::findInlineeLinesByVA (uint64_t VA, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 93 of file NativeRawSymbol.cpp.
findInlineFramesByAddr()
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 61 of file NativeRawSymbol.cpp.
findInlineFramesByRVA()
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findInlineFramesByRVA (uint32_t RVA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 67 of file NativeRawSymbol.cpp.
findInlineFramesByVA()
std::unique_ptr< IPDBEnumSymbols > NativeRawSymbol::findInlineFramesByVA (uint64_t VA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 72 of file NativeRawSymbol.cpp.
getAccess()
PDB_MemberAccess NativeRawSymbol::getAccess () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 101 of file NativeRawSymbol.cpp.
References llvm::pdb::Private.
getAddressOffset()
uint32_t NativeRawSymbol::getAddressOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 105 of file NativeRawSymbol.cpp.
getAddressSection()
uint32_t NativeRawSymbol::getAddressSection () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 109 of file NativeRawSymbol.cpp.
getAddressTaken()
bool NativeRawSymbol::getAddressTaken () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 440 of file NativeRawSymbol.cpp.
getAge()
uint32_t NativeRawSymbol::getAge () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 113 of file NativeRawSymbol.cpp.
getArrayIndexTypeId()
SymIndexId NativeRawSymbol::getArrayIndexTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeArray.
Definition at line 117 of file NativeRawSymbol.cpp.
getBackEndVersion()
void NativeRawSymbol::getBackEndVersion (VersionInfo & Version) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 119 of file NativeRawSymbol.cpp.
References llvm::pdb::VersionInfo::Build, llvm::pdb::VersionInfo::Major, llvm::pdb::VersionInfo::Minor, and llvm::pdb::VersionInfo::QFE.
getBaseDataOffset()
uint32_t NativeRawSymbol::getBaseDataOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 126 of file NativeRawSymbol.cpp.
getBaseDataSlot()
uint32_t NativeRawSymbol::getBaseDataSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 130 of file NativeRawSymbol.cpp.
getBaseSymbolId()
SymIndexId NativeRawSymbol::getBaseSymbolId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 134 of file NativeRawSymbol.cpp.
getBitPosition()
uint32_t NativeRawSymbol::getBitPosition () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 140 of file NativeRawSymbol.cpp.
getBuiltinType()
PDB_BuiltinType NativeRawSymbol::getBuiltinType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeBuiltin.
Definition at line 136 of file NativeRawSymbol.cpp.
References llvm::pdb::None.
getCallingConvention()
PDB_CallingConv NativeRawSymbol::getCallingConvention () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig.
Definition at line 144 of file NativeRawSymbol.cpp.
getClassParentId()
SymIndexId NativeRawSymbol::getClassParentId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypePointer, and llvm::pdb::NativeSymbolEnumerator.
Definition at line 148 of file NativeRawSymbol.cpp.
getCompilerName()
std::string NativeRawSymbol::getCompilerName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 150 of file NativeRawSymbol.cpp.
getCount()
uint32_t NativeRawSymbol::getCount () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
Definition at line 154 of file NativeRawSymbol.cpp.
getCountLiveRanges()
uint32_t NativeRawSymbol::getCountLiveRanges () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 158 of file NativeRawSymbol.cpp.
getDataBytes()
void NativeRawSymbol::getDataBytes (SmallVector< uint8_t, 32 > & Bytes) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 97 of file NativeRawSymbol.cpp.
References llvm::SmallVectorImpl< T >::clear().
getDataKind()
PDB_DataKind NativeRawSymbol::getDataKind () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeSymbolEnumerator.
Definition at line 360 of file NativeRawSymbol.cpp.
References llvm::pdb::Unknown.
getFrontEndVersion()
void NativeRawSymbol::getFrontEndVersion (VersionInfo & Version) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 162 of file NativeRawSymbol.cpp.
References llvm::pdb::VersionInfo::Build, llvm::pdb::VersionInfo::Major, llvm::pdb::VersionInfo::Minor, and llvm::pdb::VersionInfo::QFE.
getGuid()
codeview::GUID NativeRawSymbol::getGuid () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 366 of file NativeRawSymbol.cpp.
getLanguage()
PDB_Lang NativeRawSymbol::getLanguage () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 169 of file NativeRawSymbol.cpp.
References llvm::codeview::Cobol.
getLength()
uint64_t NativeRawSymbol::getLength () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeArray, llvm::pdb::NativeTypePointer, and llvm::pdb::NativeTypeBuiltin.
Definition at line 392 of file NativeRawSymbol.cpp.
Referenced by llvm::pdb::NativeTypeArray::getCount().
getLexicalParentId()
SymIndexId NativeRawSymbol::getLexicalParentId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeSymbolEnumerator.
Definition at line 173 of file NativeRawSymbol.cpp.
getLibraryName()
std::string NativeRawSymbol::getLibraryName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 175 of file NativeRawSymbol.cpp.
getLiveRangeLength()
uint64_t NativeRawSymbol::getLiveRangeLength () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 396 of file NativeRawSymbol.cpp.
getLiveRangeStartAddressOffset()
uint32_t NativeRawSymbol::getLiveRangeStartAddressOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 179 of file NativeRawSymbol.cpp.
getLiveRangeStartAddressSection()
uint32_t NativeRawSymbol::getLiveRangeStartAddressSection () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 183 of file NativeRawSymbol.cpp.
getLiveRangeStartRelativeVirtualAddress()
uint32_t NativeRawSymbol::getLiveRangeStartRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 187 of file NativeRawSymbol.cpp.
getLocalBasePointerRegisterId()
codeview::RegisterId NativeRawSymbol::getLocalBasePointerRegisterId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 191 of file NativeRawSymbol.cpp.
References llvm::N86::EAX.
getLocationType()
PDB_LocType NativeRawSymbol::getLocationType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeSymbolEnumerator.
Definition at line 380 of file NativeRawSymbol.cpp.
References llvm::pdb::Null.
getLowerBoundId()
SymIndexId NativeRawSymbol::getLowerBoundId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 195 of file NativeRawSymbol.cpp.
getMachineType()
PDB_Machine NativeRawSymbol::getMachineType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 384 of file NativeRawSymbol.cpp.
References llvm::pdb::Invalid.
getMemorySpaceKind()
uint32_t NativeRawSymbol::getMemorySpaceKind () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 197 of file NativeRawSymbol.cpp.
getName()
std::string NativeRawSymbol::getName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeSymbolEnumerator, and llvm::pdb::NativeTypeTypedef.
Definition at line 201 of file NativeRawSymbol.cpp.
getNoStackOrdering()
bool NativeRawSymbol::getNoStackOrdering () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 444 of file NativeRawSymbol.cpp.
getNumberOfAcceleratorPointerTags()
uint32_t NativeRawSymbol::getNumberOfAcceleratorPointerTags () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 205 of file NativeRawSymbol.cpp.
getNumberOfColumns()
uint32_t NativeRawSymbol::getNumberOfColumns () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 209 of file NativeRawSymbol.cpp.
getNumberOfModifiers()
uint32_t NativeRawSymbol::getNumberOfModifiers () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 213 of file NativeRawSymbol.cpp.
getNumberOfRegisterIndices()
uint32_t NativeRawSymbol::getNumberOfRegisterIndices () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 217 of file NativeRawSymbol.cpp.
getNumberOfRows()
uint32_t NativeRawSymbol::getNumberOfRows () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 221 of file NativeRawSymbol.cpp.
getObjectFileName()
std::string NativeRawSymbol::getObjectFileName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 225 of file NativeRawSymbol.cpp.
getOemId()
uint32_t NativeRawSymbol::getOemId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 229 of file NativeRawSymbol.cpp.
getOemSymbolId()
SymIndexId NativeRawSymbol::getOemSymbolId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 233 of file NativeRawSymbol.cpp.
getOffset()
int32_t NativeRawSymbol::getOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 368 of file NativeRawSymbol.cpp.
getOffsetInUdt()
uint32_t NativeRawSymbol::getOffsetInUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 235 of file NativeRawSymbol.cpp.
getPlatform()
PDB_Cpu NativeRawSymbol::getPlatform () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 239 of file NativeRawSymbol.cpp.
getRank()
uint32_t NativeRawSymbol::getRank () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 243 of file NativeRawSymbol.cpp.
getRegisterId()
codeview::RegisterId NativeRawSymbol::getRegisterId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 247 of file NativeRawSymbol.cpp.
References llvm::N86::EAX.
getRegisterType()
uint32_t NativeRawSymbol::getRegisterType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 251 of file NativeRawSymbol.cpp.
getRelativeVirtualAddress()
uint32_t NativeRawSymbol::getRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 255 of file NativeRawSymbol.cpp.
getSamplerSlot()
uint32_t NativeRawSymbol::getSamplerSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 259 of file NativeRawSymbol.cpp.
getSignature()
uint32_t NativeRawSymbol::getSignature () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 263 of file NativeRawSymbol.cpp.
getSizeInUdt()
uint32_t NativeRawSymbol::getSizeInUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 267 of file NativeRawSymbol.cpp.
getSlot()
uint32_t NativeRawSymbol::getSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 271 of file NativeRawSymbol.cpp.
getSourceFileName()
std::string NativeRawSymbol::getSourceFileName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 275 of file NativeRawSymbol.cpp.
getSrcLineOnTypeDefn()
std::unique_ptr< IPDBLineNumber > NativeRawSymbol::getSrcLineOnTypeDefn () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 280 of file NativeRawSymbol.cpp.
getStride()
uint32_t NativeRawSymbol::getStride () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 284 of file NativeRawSymbol.cpp.
getSubTypeId()
SymIndexId NativeRawSymbol::getSubTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 288 of file NativeRawSymbol.cpp.
getSymbolsFileName()
std::string NativeRawSymbol::getSymbolsFileName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 290 of file NativeRawSymbol.cpp.
getSymIndexId()
SymIndexId NativeRawSymbol::getSymIndexId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 292 of file NativeRawSymbol.cpp.
References SymbolId.
Referenced by llvm::pdb::NativeSymbolEnumerator::getClassParentId(), llvm::pdb::NativeTypeUDT::getUnmodifiedTypeId(), and llvm::pdb::NativeTypeEnum::getUnmodifiedTypeId().
getSymTag()
PDB_SymType NativeRawSymbol::getSymTag () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeBuiltin.
Definition at line 364 of file NativeRawSymbol.cpp.
References Tag.
Referenced by llvm::pdb::SymbolCache::createGlobalsEnumerator().
getTargetOffset()
uint32_t NativeRawSymbol::getTargetOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 294 of file NativeRawSymbol.cpp.
getTargetRelativeVirtualAddress()
uint32_t NativeRawSymbol::getTargetRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 298 of file NativeRawSymbol.cpp.
getTargetSection()
uint32_t NativeRawSymbol::getTargetSection () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 306 of file NativeRawSymbol.cpp.
getTargetVirtualAddress()
uint64_t NativeRawSymbol::getTargetVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 302 of file NativeRawSymbol.cpp.
getTextureSlot()
uint32_t NativeRawSymbol::getTextureSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 310 of file NativeRawSymbol.cpp.
getThisAdjust()
int32_t NativeRawSymbol::getThisAdjust () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig.
Definition at line 372 of file NativeRawSymbol.cpp.
getThunkOrdinal()
codeview::ThunkOrdinal NativeRawSymbol::getThunkOrdinal () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 388 of file NativeRawSymbol.cpp.
References llvm::codeview::Standard.
getTimeStamp()
uint32_t NativeRawSymbol::getTimeStamp () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 314 of file NativeRawSymbol.cpp.
getToken()
uint32_t NativeRawSymbol::getToken () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 318 of file NativeRawSymbol.cpp.
getTypeId()
SymIndexId NativeRawSymbol::getTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypePointer, llvm::pdb::NativeTypeArray, llvm::pdb::NativeSymbolEnumerator, and llvm::pdb::NativeTypeTypedef.
Definition at line 322 of file NativeRawSymbol.cpp.
getUavSlot()
uint32_t NativeRawSymbol::getUavSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 324 of file NativeRawSymbol.cpp.
getUdtKind()
PDB_UdtType NativeRawSymbol::getUdtKind () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT.
Definition at line 404 of file NativeRawSymbol.cpp.
References llvm::pdb::Struct.
getUndecoratedName()
std::string NativeRawSymbol::getUndecoratedName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 328 of file NativeRawSymbol.cpp.
getUndecoratedNameEx()
std::string NativeRawSymbol::getUndecoratedNameEx (PDB_UndnameFlags Flags) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 332 of file NativeRawSymbol.cpp.
getUnmodifiedTypeId()
SymIndexId NativeRawSymbol::getUnmodifiedTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 337 of file NativeRawSymbol.cpp.
getUnused()
std::string NativeRawSymbol::getUnused () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 732 of file NativeRawSymbol.cpp.
getUpperBoundId()
SymIndexId NativeRawSymbol::getUpperBoundId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 339 of file NativeRawSymbol.cpp.
getValue()
Variant NativeRawSymbol::getValue () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeSymbolEnumerator.
Definition at line 341 of file NativeRawSymbol.cpp.
References llvm::pdb::Variant.
getVirtualAddress()
uint64_t NativeRawSymbol::getVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 400 of file NativeRawSymbol.cpp.
getVirtualBaseDispIndex()
uint32_t NativeRawSymbol::getVirtualBaseDispIndex () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 345 of file NativeRawSymbol.cpp.
getVirtualBaseOffset()
uint32_t NativeRawSymbol::getVirtualBaseOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 349 of file NativeRawSymbol.cpp.
getVirtualBasePointerOffset()
int32_t NativeRawSymbol::getVirtualBasePointerOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 376 of file NativeRawSymbol.cpp.
getVirtualBaseTableType()
std::unique_ptr< PDBSymbolTypeBuiltin > NativeRawSymbol::getVirtualBaseTableType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 356 of file NativeRawSymbol.cpp.
getVirtualTableShapeId()
SymIndexId NativeRawSymbol::getVirtualTableShapeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT.
Definition at line 353 of file NativeRawSymbol.cpp.
hasAlloca()
bool NativeRawSymbol::hasAlloca () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 448 of file NativeRawSymbol.cpp.
hasAssignmentOperator()
bool NativeRawSymbol::hasAssignmentOperator () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
Definition at line 452 of file NativeRawSymbol.cpp.
hasCastOperator()
bool NativeRawSymbol::hasCastOperator () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
Definition at line 460 of file NativeRawSymbol.cpp.
hasConstructor()
bool NativeRawSymbol::hasConstructor () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
Definition at line 408 of file NativeRawSymbol.cpp.
hasCTypes()
bool NativeRawSymbol::hasCTypes () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 456 of file NativeRawSymbol.cpp.
hasCustomCallingConvention()
bool NativeRawSymbol::hasCustomCallingConvention () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 412 of file NativeRawSymbol.cpp.
hasDebugInfo()
bool NativeRawSymbol::hasDebugInfo () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 464 of file NativeRawSymbol.cpp.
hasEH()
bool NativeRawSymbol::hasEH () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 468 of file NativeRawSymbol.cpp.
hasEHa()
bool NativeRawSymbol::hasEHa () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 472 of file NativeRawSymbol.cpp.
hasFarReturn()
bool NativeRawSymbol::hasFarReturn () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 416 of file NativeRawSymbol.cpp.
hasFramePointer()
bool NativeRawSymbol::hasFramePointer () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 488 of file NativeRawSymbol.cpp.
hasInlAsm()
bool NativeRawSymbol::hasInlAsm () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 476 of file NativeRawSymbol.cpp.
hasInlineAttribute()
bool NativeRawSymbol::hasInlineAttribute () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 480 of file NativeRawSymbol.cpp.
hasInterruptReturn()
bool NativeRawSymbol::hasInterruptReturn () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 484 of file NativeRawSymbol.cpp.
hasLongJump()
bool NativeRawSymbol::hasLongJump () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 492 of file NativeRawSymbol.cpp.
hasManagedCode()
bool NativeRawSymbol::hasManagedCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 496 of file NativeRawSymbol.cpp.
hasNestedTypes()
bool NativeRawSymbol::hasNestedTypes () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 500 of file NativeRawSymbol.cpp.
hasNoInlineAttribute()
bool NativeRawSymbol::hasNoInlineAttribute () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 504 of file NativeRawSymbol.cpp.
hasNoReturnAttribute()
bool NativeRawSymbol::hasNoReturnAttribute () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 508 of file NativeRawSymbol.cpp.
hasOptimizedCodeDebugInfo()
bool NativeRawSymbol::hasOptimizedCodeDebugInfo () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 512 of file NativeRawSymbol.cpp.
hasOverloadedOperator()
bool NativeRawSymbol::hasOverloadedOperator () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 516 of file NativeRawSymbol.cpp.
hasPrivateSymbols()
bool NativeRawSymbol::hasPrivateSymbols () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 696 of file NativeRawSymbol.cpp.
hasSecurityChecks()
bool NativeRawSymbol::hasSecurityChecks () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 524 of file NativeRawSymbol.cpp.
hasSEH()
bool NativeRawSymbol::hasSEH () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 520 of file NativeRawSymbol.cpp.
hasSetJump()
bool NativeRawSymbol::hasSetJump () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 528 of file NativeRawSymbol.cpp.
hasStrictGSCheck()
bool NativeRawSymbol::hasStrictGSCheck () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 532 of file NativeRawSymbol.cpp.
isAcceleratorGroupSharedLocal()
bool NativeRawSymbol::isAcceleratorGroupSharedLocal () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 536 of file NativeRawSymbol.cpp.
isAcceleratorPointerTagLiveRange()
bool NativeRawSymbol::isAcceleratorPointerTagLiveRange () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 540 of file NativeRawSymbol.cpp.
isAcceleratorStubFunction()
bool NativeRawSymbol::isAcceleratorStubFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 544 of file NativeRawSymbol.cpp.
isAggregated()
bool NativeRawSymbol::isAggregated () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 548 of file NativeRawSymbol.cpp.
isCode()
bool NativeRawSymbol::isCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 420 of file NativeRawSymbol.cpp.
isCompilerGenerated()
bool NativeRawSymbol::isCompilerGenerated () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 424 of file NativeRawSymbol.cpp.
isConstructorVirtualBase()
bool NativeRawSymbol::isConstructorVirtualBase () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig.
Definition at line 560 of file NativeRawSymbol.cpp.
isConstType()
bool NativeRawSymbol::isConstType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypeUDT, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypePointer, llvm::pdb::NativeTypeBuiltin, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
Definition at line 428 of file NativeRawSymbol.cpp.
isCVTCIL()
bool NativeRawSymbol::isCVTCIL () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 556 of file NativeRawSymbol.cpp.
isCxxReturnUdt()
bool NativeRawSymbol::isCxxReturnUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeFunctionSig.
Definition at line 564 of file NativeRawSymbol.cpp.
isDataAligned()
bool NativeRawSymbol::isDataAligned () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 568 of file NativeRawSymbol.cpp.
isEditAndContinueEnabled()
bool NativeRawSymbol::isEditAndContinueEnabled () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 432 of file NativeRawSymbol.cpp.
isFunction()
bool NativeRawSymbol::isFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 436 of file NativeRawSymbol.cpp.
isHLSLData()
bool NativeRawSymbol::isHLSLData () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 572 of file NativeRawSymbol.cpp.
isHotpatchable()
bool NativeRawSymbol::isHotpatchable () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 576 of file NativeRawSymbol.cpp.
isIndirectVirtualBaseClass()
bool NativeRawSymbol::isIndirectVirtualBaseClass () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 580 of file NativeRawSymbol.cpp.
isInterfaceUdt()
bool NativeRawSymbol::isInterfaceUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 584 of file NativeRawSymbol.cpp.
isIntrinsic()
bool NativeRawSymbol::isIntrinsic () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 588 of file NativeRawSymbol.cpp.
isIntroVirtualFunction()
bool NativeRawSymbol::isIntroVirtualFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 552 of file NativeRawSymbol.cpp.
isLocationControlFlowDependent()
bool NativeRawSymbol::isLocationControlFlowDependent () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 596 of file NativeRawSymbol.cpp.
isLTCG()
bool NativeRawSymbol::isLTCG () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 592 of file NativeRawSymbol.cpp.
isManagedCode()
bool NativeRawSymbol::isManagedCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 608 of file NativeRawSymbol.cpp.
isMatrixRowMajor()
bool NativeRawSymbol::isMatrixRowMajor () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 604 of file NativeRawSymbol.cpp.
isMSILCode()
bool NativeRawSymbol::isMSILCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 612 of file NativeRawSymbol.cpp.
isMSILNetmodule()
bool NativeRawSymbol::isMSILNetmodule () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 600 of file NativeRawSymbol.cpp.
isMultipleInheritance()
bool NativeRawSymbol::isMultipleInheritance () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 616 of file NativeRawSymbol.cpp.
isNaked()
bool NativeRawSymbol::isNaked () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 620 of file NativeRawSymbol.cpp.
isNested()
bool NativeRawSymbol::isNested () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT, and llvm::pdb::NativeTypeEnum.
Definition at line 624 of file NativeRawSymbol.cpp.
isOptimizedAway()
bool NativeRawSymbol::isOptimizedAway () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 628 of file NativeRawSymbol.cpp.
isPacked()
bool NativeRawSymbol::isPacked () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 632 of file NativeRawSymbol.cpp.
isPointerBasedOnSymbolValue()
bool NativeRawSymbol::isPointerBasedOnSymbolValue () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 636 of file NativeRawSymbol.cpp.
isPointerToDataMember()
bool NativeRawSymbol::isPointerToDataMember () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 640 of file NativeRawSymbol.cpp.
isPointerToMemberFunction()
bool NativeRawSymbol::isPointerToMemberFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 644 of file NativeRawSymbol.cpp.
isPureVirtual()
bool NativeRawSymbol::isPureVirtual () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 648 of file NativeRawSymbol.cpp.
isReference()
bool NativeRawSymbol::isReference () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 660 of file NativeRawSymbol.cpp.
isRefUdt()
bool NativeRawSymbol::isRefUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 656 of file NativeRawSymbol.cpp.
isRestrictedType()
bool NativeRawSymbol::isRestrictedType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 664 of file NativeRawSymbol.cpp.
isReturnValue()
bool NativeRawSymbol::isReturnValue () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 668 of file NativeRawSymbol.cpp.
isRValueReference()
bool NativeRawSymbol::isRValueReference () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 652 of file NativeRawSymbol.cpp.
isSafeBuffers()
bool NativeRawSymbol::isSafeBuffers () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 672 of file NativeRawSymbol.cpp.
isScoped()
bool NativeRawSymbol::isScoped () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 676 of file NativeRawSymbol.cpp.
isSdl()
bool NativeRawSymbol::isSdl () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 680 of file NativeRawSymbol.cpp.
isSingleInheritance()
bool NativeRawSymbol::isSingleInheritance () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 684 of file NativeRawSymbol.cpp.
isSplitted()
bool NativeRawSymbol::isSplitted () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 688 of file NativeRawSymbol.cpp.
isStatic()
bool NativeRawSymbol::isStatic () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 692 of file NativeRawSymbol.cpp.
isUnalignedType()
bool NativeRawSymbol::isUnalignedType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypePointer, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypeBuiltin, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
Definition at line 700 of file NativeRawSymbol.cpp.
isUnreached()
bool NativeRawSymbol::isUnreached () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 704 of file NativeRawSymbol.cpp.
isValueUdt()
bool NativeRawSymbol::isValueUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeEnum, and llvm::pdb::NativeTypeUDT.
Definition at line 708 of file NativeRawSymbol.cpp.
isVirtual()
bool NativeRawSymbol::isVirtual () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 712 of file NativeRawSymbol.cpp.
isVirtualBaseClass()
bool NativeRawSymbol::isVirtualBaseClass () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 716 of file NativeRawSymbol.cpp.
isVirtualInheritance()
bool NativeRawSymbol::isVirtualInheritance () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypePointer.
Definition at line 720 of file NativeRawSymbol.cpp.
isVolatileType()
bool NativeRawSymbol::isVolatileType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Reimplemented in llvm::pdb::NativeTypeUDT, llvm::pdb::NativeTypeFunctionSig, llvm::pdb::NativeTypeEnum, llvm::pdb::NativeTypePointer, llvm::pdb::NativeSymbolEnumerator, llvm::pdb::NativeTypeBuiltin, llvm::pdb::NativeTypeArray, and llvm::pdb::NativeTypeVTShape.
Definition at line 724 of file NativeRawSymbol.cpp.
wasInlined()
bool NativeRawSymbol::wasInlined () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 728 of file NativeRawSymbol.cpp.
Friends And Related Function Documentation
SymbolCache
friend class SymbolCache friend
Definition at line 22 of file NativeRawSymbol.h.
Member Data Documentation
Session
NativeSession& llvm::pdb::NativeRawSymbol::Session protected
Definition at line 232 of file NativeRawSymbol.h.
Referenced by llvm::pdb::NativeCompilandSymbol::dump(), llvm::pdb::NativeSymbolEnumerator::dump(), llvm::pdb::NativeTypeArray::dump(), llvm::pdb::NativeTypeTypedef::dump(), dump(), llvm::pdb::NativeTypeVTShape::dump(), llvm::pdb::NativeTypePointer::dump(), llvm::pdb::NativeTypeEnum::dump(), llvm::pdb::NativeTypeUDT::dump(), llvm::pdb::NativeTypeFunctionSig::dump(), llvm::pdb::NativeExeSymbol::findChildren(), llvm::pdb::NativeTypeEnum::findChildren(), llvm::pdb::NativeTypeFunctionSig::findChildren(), llvm::pdb::NativeExeSymbol::getAge(), llvm::pdb::NativeTypeArray::getArrayIndexTypeId(), llvm::pdb::NativeTypePointer::getClassParentId(), llvm::pdb::NativeTypeArray::getCount(), llvm::pdb::NativeExeSymbol::getGuid(), llvm::pdb::NativeExeSymbol::getSymbolsFileName(), llvm::pdb::NativeTypeTypedef::getTypeId(), llvm::pdb::NativeTypeArray::getTypeId(), llvm::pdb::NativeTypePointer::getTypeId(), llvm::pdb::NativeTypeFunctionSig::getTypeId(), llvm::pdb::NativeTypeUDT::getVirtualTableShapeId(), llvm::pdb::NativeExeSymbol::hasCTypes(), llvm::pdb::NativeExeSymbol::hasPrivateSymbols(), llvm::pdb::NativeTypeFunctionSig::initialize(), and llvm::pdb::NativeTypeFunctionSig::~NativeTypeFunctionSig().
SymbolId
SymIndexId llvm::pdb::NativeRawSymbol::SymbolId protected
Definition at line 234 of file NativeRawSymbol.h.
Referenced by dump(), and getSymIndexId().
Tag
PDB_SymType llvm::pdb::NativeRawSymbol::Tag protected
Definition at line 233 of file NativeRawSymbol.h.
Referenced by dump(), and getSymTag().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeRawSymbol.h
lib/DebugInfo/PDB/Native/NativeRawSymbol.cpp