LLVM: llvm::FaultMaps Class Reference
llvm::FaultMaps Class Reference
#include "llvm/CodeGen/FaultMaps.h"
Public Types
enum FaultKind { FaultingLoad = 1, FaultingLoadStore, FaultingStore, FaultKindMax }
Public Member Functions
FaultMaps (AsmPrinter &AP)
void recordFaultingOp (FaultKind FaultTy, const MCSymbol *FaultingLabel, const MCSymbol *HandlerLabel)
void serializeToFaultMapSection ()
void reset ()
Static Public Member Functions
static const char * faultTypeToString (FaultKind)
Detailed Description
Definition at line 26 of file FaultMaps.h.
Member Enumeration Documentation
FaultKind
enum llvm::FaultMaps::FaultKind
Enumerator
FaultingLoad
FaultingLoadStore
FaultingStore
FaultKindMax
Definition at line 28 of file FaultMaps.h.
Constructor & Destructor Documentation
FaultMaps()
FaultMaps::FaultMaps (AsmPrinter & AP) explicit
Definition at line 28 of file FaultMaps.cpp.
Member Function Documentation
faultTypeToString()
const char * FaultMaps::faultTypeToString (FaultMaps::FaultKind FT) static
Definition at line 105 of file FaultMaps.cpp.
References FaultingLoad, FaultingLoadStore, FaultingStore, llvm_unreachable, and llvm::operator<<().
Referenced by llvm::operator<<(), and serializeToFaultMapSection().
recordFaultingOp()
void FaultMaps::recordFaultingOp (FaultKind FaultTy, const MCSymbol * FaultingLabel, const MCSymbol * HandlerLabel)
Definition at line 30 of file FaultMaps.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::CurrentFnSymForSize, and llvm::AsmPrinter::OutStreamer.
reset()
void llvm::FaultMaps::reset () inline
Definition at line 42 of file FaultMaps.h.
References FaultKindMax, and llvm::MCSymbol::getName().
Referenced by llvm::X86AsmPrinter::doInitialization().
serializeToFaultMapSection()
void FaultMaps::serializeToFaultMapSection ()
Definition at line 47 of file FaultMaps.cpp.
References llvm::dbgs(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValue(), llvm::Fault, FaultMapVersion, faultTypeToString(), llvm::MCObjectFileInfo::getFaultMapSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCContext::getOrCreateSymbol(), LLVM_DEBUG, llvm::AsmPrinter::OutStreamer, and llvm::MCStreamer::SwitchSection().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/FaultMaps.h
lib/CodeGen/FaultMaps.cpp