LLVM: llvm::BinaryStreamWriter Class Reference
llvm::BinaryStreamWriter Class Reference
Provides write only access to a subclass of WritableBinaryStream.
#include "llvm/Support/BinaryStreamWriter.h"
Public Member Functions
BinaryStreamWriter ()=default
BinaryStreamWriter (WritableBinaryStreamRef Ref)
BinaryStreamWriter (WritableBinaryStream &Stream)
BinaryStreamWriter (MutableArrayRef< uint8_t > Data, llvm::support::endianness Endian)
BinaryStreamWriter (const BinaryStreamWriter &Other)
BinaryStreamWriter & operator= (const BinaryStreamWriter &Other)
virtual ~BinaryStreamWriter ()
Error writeBytes (ArrayRef< uint8_t > Buffer)
Write the bytes specified in Buffer to the underlying stream.
template<typename T >
Error writeInteger (T Value)
Write the integer Value to the underlying stream in the specified endianness.
template<typename T >
Error writeEnum (T Num)
Similar to writeInteger.
Error writeULEB128 (uint64_t Value)
Write the unsigned integer Value to the underlying stream using ULEB128 encoding.
Error writeSLEB128 (int64_t Value)
Write the unsigned integer Value to the underlying stream using ULEB128 encoding.
Error writeCString (StringRef Str)
Write the string Str to the underlying stream followed by a null terminator.
Error writeFixedString (StringRef Str)
Write the string Str to the underlying stream without a null terminator.
Error writeStreamRef (BinaryStreamRef Ref)
Efficiently reads all data from Ref, and writes it to this stream.
Error writeStreamRef (BinaryStreamRef Ref, uint32_t Size)
Efficiently reads Size bytes from Ref, and writes it to this stream.
template<typename T >
Error writeObject (const T &Obj)
Writes the object Obj to the underlying stream, as if by using memcpy.
template<typename T >
Error writeArray (ArrayRef< T > Array)
Writes an array of objects of type T to the underlying stream, as if by using memcpy.
template<typename T , typename U >
Error writeArray (VarStreamArray< T, U > Array)
Writes all data from the array Array to the underlying stream.
template<typename T >
Error writeArray (FixedStreamArray< T > Array)
Writes all elements from the array Array to the underlying stream.
std::pair< BinaryStreamWriter, BinaryStreamWriter > split (uint32_t Off) const
Splits the Writer into two Writers at a given offset.
void setOffset (uint32_t Off)
uint32_t getOffset () const
uint32_t getLength () const
uint32_t bytesRemaining () const
Error padToAlignment (uint32_t Align)
Protected Attributes
WritableBinaryStreamRef Stream
uint32_t Offset = 0
Detailed Description
Provides write only access to a subclass of WritableBinaryStream.
Provides bounds checking and helpers for writing certain common data types such as null-terminated strings, integers in various flavors of endianness, etc. Can be subclassed to provide reading and writing of custom datatypes, although no methods are overridable.
Definition at line 31 of file BinaryStreamWriter.h.
Constructor & Destructor Documentation
BinaryStreamWriter() [1/5]
llvm::BinaryStreamWriter::BinaryStreamWriter () default
BinaryStreamWriter() [2/5]
BinaryStreamWriter::BinaryStreamWriter (WritableBinaryStreamRef Ref) explicit
Definition at line 18 of file BinaryStreamWriter.cpp.
BinaryStreamWriter() [3/5]
BinaryStreamWriter::BinaryStreamWriter (WritableBinaryStream & Stream) explicit
Definition at line 21 of file BinaryStreamWriter.cpp.
BinaryStreamWriter() [4/5]
BinaryStreamWriter::BinaryStreamWriter (MutableArrayRef< uint8_t > Data, llvm::support::endianness Endian) explicit
Definition at line 24 of file BinaryStreamWriter.cpp.
BinaryStreamWriter() [5/5]
llvm::BinaryStreamWriter::BinaryStreamWriter (const BinaryStreamWriter & Other) inline
Definition at line 39 of file BinaryStreamWriter.h.
~BinaryStreamWriter()
virtual llvm::BinaryStreamWriter::~BinaryStreamWriter () inline virtual
Definition at line 48 of file BinaryStreamWriter.h.
References writeBytes().
Member Function Documentation
bytesRemaining()
uint32_t llvm::BinaryStreamWriter::bytesRemaining () const inline
Definition at line 186 of file BinaryStreamWriter.h.
References getLength(), getOffset(), and padToAlignment().
Referenced by llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), commitFpm(), llvm::msf::WritableMappedBlockStream::createFpmStream(), llvm::pdb::PDBFileBuilder::getNamedStreamIndex(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
getLength()
uint32_t llvm::BinaryStreamWriter::getLength () const inline
Definition at line 185 of file BinaryStreamWriter.h.
References llvm::BinaryStream::getLength().
Referenced by llvm::codeview::ContinuationRecordBuilder::begin(), bytesRemaining(), padToAlignment(), split(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
getOffset()
uint32_t llvm::BinaryStreamWriter::getOffset () const inline
Definition at line 184 of file BinaryStreamWriter.h.
References Offset.
Referenced by addPadding(), llvm::codeview::ContinuationRecordBuilder::begin(), bytesRemaining(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::codeview::DebugStringTableSubsection::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::codeview::SimpleTypeSerializer::serialize(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
operator=()
BinaryStreamWriter& llvm::BinaryStreamWriter::operator= (const BinaryStreamWriter & Other) inline
Definition at line 42 of file BinaryStreamWriter.h.
References Offset, and Stream.
padToAlignment()
Error BinaryStreamWriter::padToAlignment (uint32_t Align)
Definition at line 95 of file BinaryStreamWriter.cpp.
References llvm::alignTo(), getLength(), Offset, llvm::stream_too_short, llvm::Error::success(), and writeInteger().
Referenced by bytesRemaining(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::codeview::DebugChecksumsSubsection::commit(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), and llvm::codeview::CodeViewRecordIO::padToAlignment().
setOffset()
void llvm::BinaryStreamWriter::setOffset (uint32_t Off) inline
Definition at line 183 of file BinaryStreamWriter.h.
References Offset.
Referenced by llvm::codeview::ContinuationRecordBuilder::begin(), llvm::msf::MSFBuilder::commit(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
split()
std::pair< BinaryStreamWriter, BinaryStreamWriter > BinaryStreamWriter::split (uint32_t Off) const
Splits the Writer into two Writers at a given offset.
Definition at line 83 of file BinaryStreamWriter.cpp.
References assert(), llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), getLength(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front(), Offset, and Stream.
Referenced by llvm::pdb::PDBStringTableBuilder::commit(), and writeArray().
writeArray() [1/3]
template<typename T > Error llvm::BinaryStreamWriter::writeArray (ArrayRef< T > Array) inline
Writes an array of objects of type T to the underlying stream, as if by using memcpy.
It is up to the caller to ensure that type of Obj can be safely copied in this fashion, as no checks are made to ensure that this is safe.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 151 of file BinaryStreamWriter.h.
References llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::empty(), llvm::invalid_array_size, llvm::ArrayRef< T >::size(), llvm::Error::success(), llvm::T, and writeBytes().
Referenced by llvm::pdb::DbiStreamBuilder::addDbgStream(), llvm::codeview::DebugFrameDataSubsection::commit(), llvm::codeview::DebugSymbolRVASubsection::commit(), llvm::pdb::GSIHashStreamBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::codeview::DebugChecksumsSubsection::commit(), llvm::codeview::DebugInlineeLinesSubsection::commit(), llvm::msf::MSFBuilder::commit(), llvm::codeview::DebugLinesSubsection::commit(), llvm::pdb::DbiStreamBuilder::finalizeMsfLayout(), and writeRecords().
writeArray() [2/3]
template<typename T , typename U > Error llvm::BinaryStreamWriter::writeArray (VarStreamArray< T, U > Array) inline
Writes all data from the array Array to the underlying stream.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 168 of file BinaryStreamWriter.h.
References llvm::VarStreamArray< ValueType, Extractor >::getUnderlyingStream(), and writeStreamRef().
writeArray() [3/3]
template<typename T > Error llvm::BinaryStreamWriter::writeArray (FixedStreamArray< T > Array) inline
Writes all elements from the array Array to the underlying stream.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 176 of file BinaryStreamWriter.h.
References llvm::FixedStreamArray< T >::getUnderlyingStream(), split(), and writeStreamRef().
writeBytes()
Error BinaryStreamWriter::writeBytes (ArrayRef< uint8_t > Buffer)
Write the bytes specified in Buffer to the underlying stream.
On success, updates the offset so that subsequent writes will occur at the next unwritten position.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 28 of file BinaryStreamWriter.cpp.
References Offset, llvm::ArrayRef< T >::size(), Stream, llvm::Error::success(), and llvm::WritableBinaryStreamRef::writeBytes().
Referenced by llvm::codeview::DebugSymbolsSubsection::commit(), llvm::pdb::PDBFileBuilder::commit(), llvm::pdb::TpiStreamBuilder::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::msf::WritableMappedBlockStream::createFpmStream(), llvm::pdb::PDBFileBuilder::getNamedStreamIndex(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), llvm::codeview::CodeViewRecordIO::mapGuid(), writeArray(), writeFixedString(), writeInteger(), writeObject(), writeSLEB128(), writeStreamRef(), writeULEB128(), and ~BinaryStreamWriter().
writeCString()
Error BinaryStreamWriter::writeCString (StringRef Str)
Write the string Str to the underlying stream followed by a null terminator.
On success, updates the offset so that subsequent writes occur at the next unwritten position. Str need not be null terminated on input.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 47 of file BinaryStreamWriter.cpp.
References llvm::Error::success(), writeFixedString(), and writeObject().
Referenced by llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::codeview::CodeViewRecordIO::mapStringZ(), and writeEnum().
writeEnum()
template<typename T > Error llvm::BinaryStreamWriter::writeEnum (T Num) inline
Similar to writeInteger.
Definition at line 74 of file BinaryStreamWriter.h.
References Size, writeCString(), writeFixedString(), writeSLEB128(), writeStreamRef(), and writeULEB128().
Referenced by llvm::pdb::DbiStreamBuilder::commit(), llvm::codeview::DebugInlineeLinesSubsection::commit(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
writeFixedString()
Error BinaryStreamWriter::writeFixedString (StringRef Str)
Write the string Str to the underlying stream without a null terminator.
On success, updates the offset so that subsequent writes occur at the next unwritten position.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 56 of file BinaryStreamWriter.cpp.
References llvm::arrayRefFromStringRef(), and writeBytes().
Referenced by llvm::pdb::NamedStreamMap::commit(), writeCString(), and writeEnum().
writeInteger()
template<typename T > Error llvm::BinaryStreamWriter::writeInteger (T Value) inline
Write the integer Value to the underlying stream in the specified endianness.
On success, updates the offset so that subsequent writes occur at the next unwritten position.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 64 of file BinaryStreamWriter.h.
References llvm::BinaryStream::getEndian(), llvm::T, and writeBytes().
Referenced by addPadding(), llvm::pdb::NamedStreamMap::commit(), llvm::codeview::DebugFrameDataSubsection::commit(), llvm::codeview::DebugCrossModuleExportsSubsection::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::codeview::DebugInlineeLinesSubsection::commit(), llvm::msf::MSFBuilder::commit(), llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::commit(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::codeview::CodeViewRecordIO::mapInteger(), llvm::codeview::CodeViewRecordIO::mapStringZVectorZ(), padToAlignment(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), and llvm::pdb::writeSparseBitVector().
writeObject()
template<typename T > Error llvm::BinaryStreamWriter::writeObject (const T & Obj) inline
Writes the object Obj to the underlying stream, as if by using memcpy.
It is up to the caller to ensure that type of Obj can be safely copied in this fashion, as no checks are made to ensure that this is safe.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 135 of file BinaryStreamWriter.h.
References writeBytes().
Referenced by llvm::codeview::ContinuationRecordBuilder::begin(), llvm::pdb::GSIHashStreamBuilder::commit(), llvm::pdb::TpiStreamBuilder::commit(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::codeview::DebugChecksumsSubsection::commit(), llvm::codeview::DebugInlineeLinesSubsection::commit(), llvm::msf::MSFBuilder::commit(), llvm::codeview::DebugLinesSubsection::commit(), llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::commit(), commitFpm(), llvm::pdb::PDBFileBuilder::getNamedStreamIndex(), llvm::codeview::SimpleTypeSerializer::serialize(), writeCString(), and writeRecords().
writeSLEB128()
Error BinaryStreamWriter::writeSLEB128 (int64_t Value)
Write the unsigned integer Value to the underlying stream using ULEB128 encoding.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 41 of file BinaryStreamWriter.cpp.
References llvm::encodeSLEB128(), Size, and writeBytes().
Referenced by writeEnum().
writeStreamRef() [1/2]
Error BinaryStreamWriter::writeStreamRef (BinaryStreamRef Ref)
Efficiently reads all data from Ref, and writes it to this stream.
This operation will not invoke any copies of the source data, regardless of the source stream's implementation.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 61 of file BinaryStreamWriter.cpp.
References llvm::BinaryStreamRefBase< RefType, StreamType >::getLength().
Referenced by llvm::pdb::TpiStreamBuilder::commit(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), writeArray(), writeEnum(), and writeRecords().
writeStreamRef() [2/2]
Error BinaryStreamWriter::writeStreamRef (BinaryStreamRef Ref, uint32_t Size)
Efficiently reads Size bytes from Ref, and writes it to this stream.
This operation will not invoke any copies of the source data, regardless of the source stream's implementation.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 65 of file BinaryStreamWriter.cpp.
References llvm::BinaryStreamRefBase< RefType, StreamType >::slice(), llvm::Error::success(), and writeBytes().
writeULEB128()
Error BinaryStreamWriter::writeULEB128 (uint64_t Value)
Write the unsigned integer Value to the underlying stream using ULEB128 encoding.
Returns
a success error code if the data was successfully written, otherwise returns an appropriate error code.
Definition at line 35 of file BinaryStreamWriter.cpp.
References llvm::encodeULEB128(), Size, and writeBytes().
Referenced by writeEnum().
Member Data Documentation
Offset
uint32_t llvm::BinaryStreamWriter::Offset = 0 protected
Definition at line 191 of file BinaryStreamWriter.h.
Referenced by getOffset(), operator=(), padToAlignment(), setOffset(), split(), and writeBytes().
Stream
WritableBinaryStreamRef llvm::BinaryStreamWriter::Stream protected
Definition at line 190 of file BinaryStreamWriter.h.
Referenced by operator=(), split(), and writeBytes().
The documentation for this class was generated from the following files:
include/llvm/Support/BinaryStreamWriter.h
lib/Support/BinaryStreamWriter.cpp