LLVM: llvm::ilist_base< EnableSentinelTracking > Class Template Reference
llvm::ilist_base< EnableSentinelTracking > Class Template Reference
Implementations of list algorithms using ilist_node_base.
#include "llvm/ADT/ilist_base.h"
Public Types
using node_base_type = ilist_node_base< EnableSentinelTracking >
Static Public Member Functions
static void insertBeforeImpl (node_base_type &Next, node_base_type &N)
static void removeImpl (node_base_type &N)
static void removeRangeImpl (node_base_type &First, node_base_type &Last)
static void transferBeforeImpl (node_base_type &Next, node_base_type &First, node_base_type &Last)
template<class T >
static void insertBefore (T &Next, T &N)
template<class T >
static void remove (T &N)
template<class T >
static void removeRange (T &First, T &Last)
template<class T >
static void transferBefore (T &Next, T &First, T &Last)
Detailed Description
template<bool EnableSentinelTracking>
class llvm::ilist_base< EnableSentinelTracking >
Implementations of list algorithms using ilist_node_base.
Definition at line 18 of file ilist_base.h.
Member Typedef Documentation
node_base_type
template<bool EnableSentinelTracking> using llvm::ilist_base< EnableSentinelTracking >::node_base_type = ilist_node_base<EnableSentinelTracking>
Definition at line 20 of file ilist_base.h.
Member Function Documentation
insertBefore()
template<bool EnableSentinelTracking> template<class T > static void llvm::ilist_base< EnableSentinelTracking >::insertBefore (T & Next, T & N) inline static
Definition at line 76 of file ilist_base.h.
References llvm::ilist_base< EnableSentinelTracking >::insertBeforeImpl().
insertBeforeImpl()
template<bool EnableSentinelTracking> static void llvm::ilist_base< EnableSentinelTracking >::insertBeforeImpl (node_base_type & Next, node_base_type & N) inline static
Definition at line 22 of file ilist_base.h.
Referenced by llvm::ilist_base< EnableSentinelTracking >::insertBefore().
remove()
template<bool EnableSentinelTracking> template<class T > static void llvm::ilist_base< EnableSentinelTracking >::remove (T & N) inline static
Definition at line 80 of file ilist_base.h.
References N, and llvm::ilist_base< EnableSentinelTracking >::removeImpl().
removeImpl()
template<bool EnableSentinelTracking> static void llvm::ilist_base< EnableSentinelTracking >::removeImpl (node_base_type & N) inline static
Definition at line 30 of file ilist_base.h.
Referenced by llvm::ilist_base< EnableSentinelTracking >::remove().
removeRange()
template<bool EnableSentinelTracking> template<class T > static void llvm::ilist_base< EnableSentinelTracking >::removeRange (T & First, T & Last) inline static
Definition at line 81 of file ilist_base.h.
References llvm::ilist_base< EnableSentinelTracking >::removeRangeImpl().
removeRangeImpl()
template<bool EnableSentinelTracking> static void llvm::ilist_base< EnableSentinelTracking >::removeRangeImpl (node_base_type & First, node_base_type & Last) inline static
Definition at line 41 of file ilist_base.h.
Referenced by llvm::ilist_base< EnableSentinelTracking >::removeRange().
transferBefore()
template<bool EnableSentinelTracking> template<class T > static void llvm::ilist_base< EnableSentinelTracking >::transferBefore (T & Next, T & First, T & Last) inline static
Definition at line 85 of file ilist_base.h.
References llvm::ilist_base< EnableSentinelTracking >::transferBeforeImpl().
transferBeforeImpl()
template<bool EnableSentinelTracking> static void llvm::ilist_base< EnableSentinelTracking >::transferBeforeImpl (node_base_type & Next, node_base_type & First, node_base_type & Last) inline static
Definition at line 52 of file ilist_base.h.
References assert().
Referenced by llvm::ilist_base< EnableSentinelTracking >::transferBefore().
The documentation for this class was generated from the following file:
include/llvm/ADT/ilist_base.h