LLVM: llvm::AMDGPUInstructionSelector Class Reference
llvm::AMDGPUInstructionSelector Class Reference
#include "Target/AMDGPU/AMDGPUInstructionSelector.h"
Public Member Functions
AMDGPUInstructionSelector (const GCNSubtarget &STI, const AMDGPURegisterBankInfo &RBI, const AMDGPUTargetMachine &TM)
bool select (MachineInstr &I) override
Select the (possibly generic) instruction I to only use target-specific opcodes.
void setupMF (MachineFunction &MF, GISelKnownBits &KB, CodeGenCoverage &CoverageInfo) override
Setup per-MF selector state.
Public Member Functions inherited from llvm::InstructionSelector
virtual ~InstructionSelector ()=default
virtual void setupGeneratedPerFunctionState (MachineFunction &MF)
Static Public Member Functions
static const char * getName ()
Additional Inherited Members
Public Attributes inherited from llvm::InstructionSelector
CodeGenCoverage * CoverageInfo = nullptr
GISelKnownBits * KnownBits = nullptr
MachineFunction * MF = nullptr
Protected Types inherited from llvm::InstructionSelector
using ComplexRendererFns = Optional< SmallVector< std::function< void(MachineInstrBuilder &)>, 4 > >
using RecordedMIVector = SmallVector< MachineInstr *, 4 >
using NewMIVector = SmallVector< MachineInstrBuilder, 4 >
Protected Member Functions inherited from llvm::InstructionSelector
InstructionSelector ()
template<class TgtInstructionSelector , class PredicateBitset , class ComplexMatcherMemFn , class CustomRendererFn >
bool executeMatchTable (TgtInstructionSelector &ISel, NewMIVector &OutMIs, MatcherState &State, const ISelInfoTy< PredicateBitset, ComplexMatcherMemFn, CustomRendererFn > &ISelInfo, const int64_t *MatchTable, const TargetInstrInfo &TII, MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI, const RegisterBankInfo &RBI, const PredicateBitset &AvailableFeatures, CodeGenCoverage &CoverageInfo) const
Execute a given matcher table and return true if the match was successful and false otherwise.
virtual const int64_t * getMatchTable () const
virtual bool testImmPredicate_I64 (unsigned, int64_t) const
virtual bool testImmPredicate_APInt (unsigned, const APInt &) const
virtual bool testImmPredicate_APFloat (unsigned, const APFloat &) const
virtual bool testMIPredicate_MI (unsigned, const MachineInstr &) const
bool constrainOperandRegToRegClass (MachineInstr &I, unsigned OpIdx, const TargetRegisterClass &RC, const TargetInstrInfo &TII, const TargetRegisterInfo &TRI, const RegisterBankInfo &RBI) const
Constrain a register operand of an instruction I to a specified register class.
bool isOperandImmEqual (const MachineOperand &MO, int64_t Value, const MachineRegisterInfo &MRI) const
bool isBaseWithConstantOffset (const MachineOperand &Root, const MachineRegisterInfo &MRI) const
Return true if the specified operand is a G_PTR_ADD with a G_CONSTANT on the right-hand side.
bool isObviouslySafeToFold (MachineInstr &MI, MachineInstr &IntoMI) const
Return true if MI can obviously be folded into IntoMI.
Detailed Description
Definition at line 46 of file AMDGPUInstructionSelector.h.
Constructor & Destructor Documentation
AMDGPUInstructionSelector()
AMDGPUInstructionSelector::AMDGPUInstructionSelector (const GCNSubtarget & STI, const AMDGPURegisterBankInfo & RBI, const AMDGPUTargetMachine & TM)
Definition at line 49 of file AMDGPUInstructionSelector.cpp.
References DEBUG_TYPE, and getName().
Member Function Documentation
getName()
static const char* llvm::AMDGPUInstructionSelector::getName () static
Referenced by AMDGPUInstructionSelector().
select()
bool AMDGPUInstructionSelector::select (MachineInstr & I) override virtual
Select the (possibly generic) instruction I to only use target-specific opcodes.
It is OK to insert multiple instructions, but they cannot be generic pre-isel instructions.
Returns
whether selection succeeded.
Precondition
I.getParent() && I.getParent()->getParent()
Postcondition
if returns true: for I in all mutated/inserted instructions: !isPreISelGenericOpcode(I.getOpcode())
Implements llvm::InstructionSelector.
Definition at line 1769 of file AMDGPUInstructionSelector.cpp.
References llvm::SISrcMods::ABS, llvm::BuildMI(), llvm::InstructionSelector::CoverageInfo, llvm::MachineRegisterInfo::createVirtualRegister(), llvm::Default, llvm::SmallVectorBase::empty(), getAddrSpace(), llvm::getConstantVRegVal(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::AMDGPU::getSMRDEncodedOffset(), llvm::Optional< T >::getValue(), llvm::MachineRegisterInfo::getVRegDef(), llvm::GCNSubtarget::hasFlatInstOffsets(), llvm::Optional< T >::hasValue(), llvm::MachineInstr::isCopy(), llvm::isKnownNeverNaN(), llvm::SIInstrInfo::isLegalFLATOffset(), llvm::AMDGPU::isLegalSMRDImmOffset(), llvm::MachineInstr::isPHI(), llvm::MachineInstr::isPreISelOpcode(), llvm::isUInt< 32 >(), llvm::MachineInstr::memoperands_begin(), llvm::SISrcMods::NEG, llvm::TargetOptions::NoNaNsFPMath, llvm::None, llvm::TargetMachine::Options, Signed, and llvm::SmallVectorBase::size().
setupMF()
void AMDGPUInstructionSelector::setupMF (MachineFunction & mf, GISelKnownBits & KB, CodeGenCoverage & covinfo) override virtual
Setup per-MF selector state.
Reimplemented from llvm::InstructionSelector.
Definition at line 67 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::MachineOperand::CreateImm(), llvm::MachineOperand::CreateReg(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), llvm::PointerUnion< PTs >::dyn_cast(), llvm::MachineInstr::eraseFromParent(), llvm::PointerUnion< PTs >::get(), llvm::SIRegisterInfo::getBoolRC(), llvm::SIRegisterInfo::getConstrainedRegClassForOperand(), llvm::MachineInstr::getDebugLoc(), llvm::RegisterBank::getID(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::SIRegisterInfo::getRegClassForTypeOnBank(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::MachineRegisterInfo::getRegClassOrRegBank(), llvm::MachineFunction::getRegInfo(), llvm::LLT::getSizeInBits(), llvm::MachineOperand::getSubReg(), llvm::MachineRegisterInfo::getType(), llvm::SIRegisterInfo::getVCC(), llvm::TargetRegisterClass::hasSuperClassEq(), I, llvm::MachineOperand::isDead(), llvm::MachineOperand::isDebug(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isEarlyClobber(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isInternalRead(), llvm::MachineOperand::isKill(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::SIRegisterInfo::isSGPRClass(), llvm::MachineOperand::isUndef(), llvm::LLT::isValid(), LLVM_DEBUG, llvm_unreachable, MI, llvm::MachineInstr::operands(), Reg, llvm::MachineInstr::setDesc(), llvm::MachineRegisterInfo::setRegClass(), and llvm::InstructionSelector::setupMF().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUInstructionSelector.h
lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp