LLVM: llvm::MemorySSAPrinterPass Class Reference
llvm::MemorySSAPrinterPass Class Reference
Printer pass for MemorySSA.
#include "llvm/Analysis/MemorySSA.h"
Public Member Functions
MemorySSAPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MemorySSAPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for MemorySSA.
Definition at line 949 of file MemorySSA.h.
Constructor & Destructor Documentation
MemorySSAPrinterPass()
llvm::MemorySSAPrinterPass::MemorySSAPrinterPass (raw_ostream & OS) inline explicit
Definition at line 953 of file MemorySSA.h.
Member Function Documentation
run()
PreservedAnalyses MemorySSAPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 2265 of file MemorySSA.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::Value::getName(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemorySSA.h
lib/Analysis/MemorySSA.cpp