LLVM: llvm::GlobalValueSummary Class Reference
llvm::GlobalValueSummary Class Reference
Function and variable summary information to aid decisions and implementation of importing.
#include "llvm/IR/ModuleSummaryIndex.h"
Classes
struct GVFlags
Group flags (Linkage, NotEligibleToImport, etc.) as a bitfield.
Public Types
enum SummaryKind : unsigned { AliasKind, FunctionKind, GlobalVarKind }
Sububclass discriminator (for dyn_cast<> et al.)
Public Member Functions
virtual ~GlobalValueSummary ()=default
GlobalValue::GUID getOriginalName () const
Returns the hash of the original name, it is identical to the GUID for externally visible symbols, but not for local ones.
void setOriginalName (GlobalValue::GUID Name)
Initialize the original name hash in this summary.
SummaryKind getSummaryKind () const
Which kind of summary subclass this is.
void setModulePath (StringRef ModPath)
Set the path to the module containing this function, for use in the combined index.
StringRef modulePath () const
Get the path to the module containing this function.
GVFlags flags () const
Get the flags for this GlobalValue (see struct GVFlags).
GlobalValue::LinkageTypes linkage () const
Return linkage type recorded for this global value.
void setLinkage (GlobalValue::LinkageTypes Linkage)
Sets the linkage to the value determined by global summary-based optimization.
bool notEligibleToImport () const
Return true if this global value can't be imported.
bool isLive () const
void setLive (bool Live)
void setDSOLocal (bool Local)
bool isDSOLocal () const
void setCanAutoHide (bool CanAutoHide)
bool canAutoHide () const
void setNotEligibleToImport ()
Flag that this global value cannot be imported.
ArrayRef< ValueInfo > refs () const
Return the list of values referenced by this global value definition.
GlobalValueSummary * getBaseObject ()
If this is an alias summary, returns the summary of the aliased object (a global variable or function), otherwise returns itself.
const GlobalValueSummary * getBaseObject () const
Protected Member Functions
GlobalValueSummary (SummaryKind K, GVFlags Flags, std::vector< ValueInfo > Refs)
Friends
class ModuleSummaryIndex
Detailed Description
Function and variable summary information to aid decisions and implementation of importing.
Definition at line 280 of file ModuleSummaryIndex.h.
Member Enumeration Documentation
SummaryKind
enum llvm::GlobalValueSummary::SummaryKind : unsigned
Sububclass discriminator (for dyn_cast<> et al.)
Enumerator
AliasKind
FunctionKind
GlobalVarKind
Definition at line 283 of file ModuleSummaryIndex.h.
Constructor & Destructor Documentation
GlobalValueSummary()
llvm::GlobalValueSummary::GlobalValueSummary (SummaryKind K, GVFlags Flags, std::vector< ValueInfo > Refs) inline protected
Definition at line 357 of file ModuleSummaryIndex.h.
References assert().
~GlobalValueSummary()
virtual llvm::GlobalValueSummary::~GlobalValueSummary () virtual default
Member Function Documentation
canAutoHide()
bool llvm::GlobalValueSummary::canAutoHide () const inline
Definition at line 410 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::CanAutoHide.
flags()
GVFlags llvm::GlobalValueSummary::flags () const inline
Get the flags for this GlobalValue (see struct GVFlags).
Definition at line 384 of file ModuleSummaryIndex.h.
Referenced by getLinkageNameWithSpace(), and writeTypeIdCompatibleVtableSummaryRecord().
getBaseObject() [1/2]
GlobalValueSummary * llvm::GlobalValueSummary::getBaseObject () inline
If this is an alias summary, returns the summary of the aliased object (a global variable or function), otherwise returns itself.
Definition at line 483 of file ModuleSummaryIndex.h.
Referenced by llvm::ModuleSummaryIndex::canImportGlobalVar(), and isWeakObjectWithRWAccess().
getBaseObject() [2/2]
const GlobalValueSummary * llvm::GlobalValueSummary::getBaseObject () const inline
Definition at line 477 of file ModuleSummaryIndex.h.
getOriginalName()
GlobalValue::GUID llvm::GlobalValueSummary::getOriginalName () const inline
Returns the hash of the original name, it is identical to the GUID for externally visible symbols, but not for local ones.
Definition at line 368 of file ModuleSummaryIndex.h.
getSummaryKind()
SummaryKind llvm::GlobalValueSummary::getSummaryKind () const inline
Which kind of summary subclass this is.
Definition at line 374 of file ModuleSummaryIndex.h.
Referenced by llvm::AliasSummary::classof(), llvm::FunctionSummary::classof(), llvm::GlobalVarSummary::classof(), and getLinkageNameWithSpace().
isDSOLocal()
bool llvm::GlobalValueSummary::isDSOLocal () const inline
Definition at line 406 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::DSOLocal.
isLive()
bool llvm::GlobalValueSummary::isLive () const inline
Definition at line 400 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::Live.
Referenced by llvm::ModuleSummaryIndex::isGlobalValueLive(), and llvm::updateIndexWPDForExports().
linkage()
GlobalValue::LinkageTypes llvm::GlobalValueSummary::linkage () const inline
Return linkage type recorded for this global value.
Definition at line 387 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::Linkage.
Referenced by llvm::ModuleSummaryIndex::canImportGlobalVar(), and getNodeLabel().
modulePath()
StringRef llvm::GlobalValueSummary::modulePath () const inline
Get the path to the module containing this function.
Definition at line 381 of file ModuleSummaryIndex.h.
Referenced by computeImportForFunction(), computeImportForReferencedGlobals(), and getLinkageNameWithSpace().
notEligibleToImport()
bool llvm::GlobalValueSummary::notEligibleToImport () const inline
Return true if this global value can't be imported.
Definition at line 398 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::NotEligibleToImport.
Referenced by llvm::ModuleSummaryIndex::canImportGlobalVar().
refs()
ArrayRef<ValueInfo> llvm::GlobalValueSummary::refs () const inline
Return the list of values referenced by this global value definition.
Definition at line 416 of file ModuleSummaryIndex.h.
Referenced by computeImportForFunction(), computeImportForReferencedGlobals(), getLinkageNameWithSpace(), propagateAttributesToRefs(), and writeTypeIdCompatibleVtableSummaryRecord().
setCanAutoHide()
void llvm::GlobalValueSummary::setCanAutoHide (bool CanAutoHide) inline
Definition at line 408 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::CanAutoHide.
setDSOLocal()
void llvm::GlobalValueSummary::setDSOLocal (bool Local) inline
Definition at line 404 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::DSOLocal.
setLinkage()
void llvm::GlobalValueSummary::setLinkage (GlobalValue::LinkageTypes Linkage) inline
Sets the linkage to the value determined by global summary-based optimization.
Will be applied in the ThinLTO backends.
Definition at line 393 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::Linkage.
setLive()
void llvm::GlobalValueSummary::setLive (bool Live) inline
Definition at line 402 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::Live.
setModulePath()
void llvm::GlobalValueSummary::setModulePath (StringRef ModPath) inline
Set the path to the module containing this function, for use in the combined index.
Definition at line 378 of file ModuleSummaryIndex.h.
setNotEligibleToImport()
void llvm::GlobalValueSummary::setNotEligibleToImport () inline
Flag that this global value cannot be imported.
Definition at line 413 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::GVFlags::NotEligibleToImport.
setOriginalName()
void llvm::GlobalValueSummary::setOriginalName (GlobalValue::GUID Name) inline
Initialize the original name hash in this summary.
Definition at line 371 of file ModuleSummaryIndex.h.
References Name.
Friends And Related Function Documentation
ModuleSummaryIndex
friend class ModuleSummaryIndex friend
Definition at line 423 of file ModuleSummaryIndex.h.
The documentation for this class was generated from the following file:
include/llvm/IR/ModuleSummaryIndex.h