LLVM: llvm::DependenceInfo Class Reference
llvm::DependenceInfo Class Reference
DependenceInfo - This class is the main dependence-analysis driver.
#include "llvm/Analysis/DependenceAnalysis.h"
Public Member Functions
DependenceInfo (Function *F, AliasAnalysis *AA, ScalarEvolution *SE, LoopInfo *LI)
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Handle transitive invalidation when the cached analysis results go away.
std::unique_ptr< Dependence > depends (Instruction *Src, Instruction *Dst, bool PossiblyLoopIndependent)
depends - Tests for a dependence between the Src and Dst instructions.
const SCEV * getSplitIteration (const Dependence &Dep, unsigned Level)
getSplitIteration - Give a dependence that's splittable at some particular level, return the iteration that should be used to split the loop.
Function * getFunction () const
Detailed Description
DependenceInfo - This class is the main dependence-analysis driver.
Definition at line 271 of file DependenceAnalysis.h.
Constructor & Destructor Documentation
DependenceInfo()
llvm::DependenceInfo::DependenceInfo (Function * F, AliasAnalysis * AA, ScalarEvolution * SE, LoopInfo * LI) inline
Definition at line 273 of file DependenceAnalysis.h.
References F().
Member Function Documentation
depends()
std::unique_ptr< Dependence > DependenceInfo::depends (Instruction * Src, Instruction * Dst, bool PossiblyLoopIndependent)
depends - Tests for a dependence between the Src and Dst instructions.
Returns NULL if no dependence; otherwise, returns a Dependence (or a FullDependence) with as much information as can be gleaned. The flag PossiblyLoopIndependent should be set by the caller if it appears that control flow can reach from Src to Dst without traversing a loop back edge.
Definition at line 3402 of file DependenceAnalysis.cpp.
References llvm::SmallBitVector::any(), assert(), llvm::SmallBitVector::count(), llvm::dbgs(), Delinearize, dumpSmallBitVector(), llvm::Dependence::DVEntry::EQ, F(), llvm::MemoryLocation::get(), llvm::FullDependence::getDirection(), llvm::getLoadStorePointerOperand(), isLoadOrStore(), LLVM_DEBUG, llvm_unreachable, llvm::MayAlias, llvm::Instruction::mayReadOrWriteMemory(), llvm::MustAlias, llvm::NoAlias, llvm::Dependence::DVEntry::NONE, P, llvm::PartialAlias, propagate(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallBitVector::reset(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallBitVector::set(), llvm::SmallBitVector::set_bits(), SI, llvm::SmallVectorBase::size(), and underlyingObjectsAlias().
Referenced by checkDependencies(), dumpExampleDependence(), llvm::IndexedReference::hasTemporalReuse(), llvm::isSafeToMoveBefore(), and populateDependencyMatrix().
getFunction()
Function* llvm::DependenceInfo::getFunction () const inline
Definition at line 333 of file DependenceAnalysis.h.
References B, C, D, llvm::Dependence::DVEntry::Direction, llvm::Dependence::DVEntry::Distance, llvm::Dependence::dump(), llvm::Empty, F(), llvm::isKnownNonNegative(), Loops, llvm::Lower, propagate(), Size, llvm::Upper, X, and Y.
Referenced by dumpExampleDependence().
getSplitIteration()
const SCEV * DependenceInfo::getSplitIteration (const Dependence & Dep, unsigned Level)
getSplitIteration - Give a dependence that's splittable at some particular level, return the iteration that should be used to split the loop.
Generally, the dependence analyzer will be used to build a dependence graph for a function (basically a map from instructions to dependences). Looking for cycles in the graph shows us loops that cannot be trivially vectorized/parallelized.
We can try to improve the situation by examining all the dependences that make up the cycle, looking for ones we can break. Sometimes, peeling the first or last iteration of a loop will break dependences, and there are flags for those possibilities. Sometimes, splitting a loop at some other iteration will do the trick, and we've got a flag for that case. Rather than waste the space to record the exact iteration (since we rarely know), we provide a method that calculates the iteration. It's a drag that it must work from scratch, but wonderful in that it's possible.
Here's an example:
for (i = 0; i < 10; i++) A[i] = ... ... = A[11 - i]
There's a loop-carried flow dependence from the store to the load, found by the weak-crossing SIV test. The dependence will have a flag, indicating that the dependence can be broken by splitting the loop. Calling getSplitIteration will return 5. Splitting the loop breaks the dependence, like so:
for (i = 0; i <= 5; i++) A[i] = ... ... = A[11 - i] for (i = 6; i < 10; i++) A[i] = ... ... = A[11 - i]
breaks the dependence and allows us to vectorize/parallelize both loops.
Definition at line 3826 of file DependenceAnalysis.cpp.
References llvm::SmallBitVector::any(), assert(), llvm::SmallBitVector::count(), llvm::dbgs(), Delinearize, F(), llvm::MemoryLocation::get(), llvm::Dependence::getDst(), llvm::getLoadStorePointerOperand(), llvm::Dependence::getSrc(), isLoadOrStore(), llvm::Dependence::isSplitable(), LLVM_DEBUG, llvm_unreachable, llvm::Instruction::mayReadFromMemory(), llvm::Instruction::mayWriteToMemory(), llvm::MustAlias, P, propagate(), llvm::SmallBitVector::reset(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallBitVector::set(), llvm::SmallBitVector::set_bits(), SI, llvm::SmallVectorBase::size(), and underlyingObjectsAlias().
Referenced by dumpExampleDependence().
invalidate()
bool DependenceInfo::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Handle transitive invalidation when the cached analysis results go away.
Definition at line 3377 of file DependenceAnalysis.cpp.
References F(), llvm::PreservedAnalyses::getChecker(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DependenceAnalysis.h
lib/Analysis/DependenceAnalysis.cpp