LLVM: llvm::DependenceAnalysis Class Reference
llvm::DependenceAnalysis Class Reference
AnalysisPass to compute dependence information in a function.
#include "llvm/Analysis/DependenceAnalysis.h"
Public Types
typedef DependenceInfo Result
Public Member Functions
Result run (Function &F, FunctionAnalysisManager &FAM)
Friends
struct AnalysisInfoMixin< DependenceAnalysis >
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< DependenceAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< DependenceAnalysis >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
AnalysisPass to compute dependence information in a function.
Definition at line 938 of file DependenceAnalysis.h.
Member Typedef Documentation
Result
typedef DependenceInfo llvm::DependenceAnalysis::Result
Definition at line 940 of file DependenceAnalysis.h.
Member Function Documentation
run()
DependenceAnalysis::Result DependenceAnalysis::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 126 of file DependenceAnalysis.cpp.
References F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), INITIALIZE_PASS_BEGIN(), and INITIALIZE_PASS_DEPENDENCY.
Friends And Related Function Documentation
AnalysisInfoMixin< DependenceAnalysis >
friend struct AnalysisInfoMixin< DependenceAnalysis > friend
Definition at line 945 of file DependenceAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DependenceAnalysis.h
lib/Analysis/DependenceAnalysis.cpp