LLVM: llvm::IRTranslator Class Reference
llvm::IRTranslator Class Reference
#include "llvm/CodeGen/GlobalISel/IRTranslator.h"
Public Member Functions
IRTranslator ()
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 61 of file IRTranslator.h.
Constructor & Destructor Documentation
IRTranslator()
IRTranslator::IRTranslator ()
Definition at line 113 of file IRTranslator.cpp.
References assert(), llvm::dbgs(), llvm::Instruction::getDebugLoc(), llvm::MachineInstr::getDebugLoc(), llvm::DebugLoc::getLine(), LLVM_DEBUG, and MI.
Member Function Documentation
getAnalysisUsage()
void IRTranslator::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 153 of file IRTranslator.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::addSuccessorWithoutProb(), assert(), llvm::MachineIRBuilder::buildBr(), llvm::MachineIRBuilder::buildBrCond(), llvm::MachineIRBuilder::buildBrJT(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildJumpTable(), llvm::MachineIRBuilder::buildSub(), llvm::MachineIRBuilder::buildZExtOrTrunc(), C, llvm::SwitchInst::cases(), llvm::SwitchCG::CC_BitTests, llvm::SwitchCG::CC_JumpTable, llvm::SwitchCG::CaseBlock::CmpLHS, llvm::computeValueLLTs(), llvm::copy(), llvm::MachineInstr::copyFlagsFromInstruction(), llvm::dbgs(), llvm::SwitchCG::JumpTable::Default, llvm::dyn_cast(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_TRUE, llvm::SwitchCG::JumpTableHeader::First, llvm::ConstantInt::get(), llvm::AllocaInst::getAlignment(), llvm::AllocaInst::getAllocatedType(), llvm::Constant::getAllOnesValue(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::AllocaInst::getArraySize(), llvm::MachineBasicBlock::getBasicBlock(), llvm::BranchInst::getCondition(), llvm::SwitchInst::getCondition(), llvm::Module::getDataLayout(), llvm::SwitchInst::getDefaultDest(), llvm::Type::getInt8PtrTy(), llvm::getLLTForType(), llvm::MachineIRBuilder::getMBB(), llvm::Instruction::getModule(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Constant::getNullValue(), llvm::SwitchInst::getNumCases(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::MachineBasicBlock::getParent(), llvm::Type::getPointerTo(), llvm::PPC::getPredicate(), llvm::MachineInstrBuilder::getReg(), llvm::ReturnInst::getReturnValue(), llvm::getSelectionDAGFallbackAnalysisUsage(), llvm::BranchInst::getSuccessor(), llvm::AllocaInst::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeStoreSize(), llvm::ConstantFP::getZeroValueForNegation(), I, llvm::CmpInst::ICMP_UGT, if(), llvm::Type::isAggregateType(), llvm::CmpInst::isIntPredicate(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::Type::isSized(), llvm::BranchInst::isUnconditional(), llvm::BranchProbability::isUnknown(), llvm::Type::isVoidTy(), llvm::HexagonISD::JT, llvm::SwitchCG::JumpTable::JTI, llvm::SwitchCG::JumpTableHeader::Last, LLVM_DEBUG, llvm::SwitchCG::JumpTable::MBB, MRI, llvm::SwitchCG::JumpTableHeader::OmitRangeCheck, llvm::Value::print(), llvm::SwitchCG::JumpTable::Reg, reportTranslationError(), llvm::MipsISD::Ret, llvm::LLT::scalar(), llvm::MachineIRBuilder::setDebugLoc(), llvm::MachineIRBuilder::setMBB(), SI, Size, llvm::SmallVectorBase::size(), llvm::SwitchCG::sortAndRangeify(), llvm::succ_size(), Success, llvm::successors(), llvm::SwitchCG::JumpTableHeader::SValue, and llvm::RISCVFenceField::W.
Referenced by getPassName().
getPassName()
StringRef llvm::IRTranslator::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 621 of file IRTranslator.h.
References getAnalysisUsage(), and runOnMachineFunction().
runOnMachineFunction()
bool IRTranslator::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 2239 of file IRTranslator.cpp.
References llvm::GISelObserverWrapper::addObserver(), Arg, assert(), checkForMustTailInVarArgFn(), llvm::Function::empty(), EnableCSEInIRTranslator, F(), llvm::GISelCSEAnalysisWrapper::get(), llvm::Module::getDataLayout(), llvm::Instruction::getDebugLoc(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHI(), llvm::TargetMachine::getOptLevel(), llvm::GlobalValue::getParent(), llvm::Function::getSubprogram(), llvm::BasicBlock::hasAddressTaken(), llvm::Function::isVarArg(), llvm::make_scope_exit(), MRI, llvm::CodeGenOpt::None, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineBasicBlock::push_back(), llvm::GISelObserverWrapper::removeObserver(), reportTranslationError(), llvm::MachineBasicBlock::setHasAddressTaken(), llvm::GISelCSEInfo::setMF(), llvm::ArrayRef< T >::size(), llvm::FunctionPass::skipFunction(), llvm::raw_string_ostream::str(), llvm::MachineBasicBlock::succ_begin(), llvm::SystemZISD::TM, Verifier, and Wrapper.
Referenced by getPassName().
Member Data Documentation
ID
char IRTranslator::ID = 0 static
Definition at line 63 of file IRTranslator.h.
Referenced by getOffsetFromIndices().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/IRTranslator.h
lib/CodeGen/GlobalISel/IRTranslator.cpp