LLVM: llvm::codeview::CodeViewRecordStreamer Class Reference
llvm::codeview::CodeViewRecordStreamer Class Reference abstract
#include "llvm/DebugInfo/CodeView/CodeViewRecordIO.h"
Public Member Functions
virtual void EmitBytes (StringRef Data)=0
virtual void EmitIntValue (uint64_t Value, unsigned Size)=0
virtual void EmitBinaryData (StringRef Data)=0
virtual void AddComment (const Twine &T)=0
virtual void AddRawComment (const Twine &T)=0
virtual bool isVerboseAsm ()=0
virtual std::string getTypeName (TypeIndex TI)=0
virtual ~CodeViewRecordStreamer ()=default
Detailed Description
Definition at line 30 of file CodeViewRecordIO.h.
Constructor & Destructor Documentation
~CodeViewRecordStreamer()
virtual llvm::codeview::CodeViewRecordStreamer::~CodeViewRecordStreamer () virtual default
Member Function Documentation
AddComment()
virtual void llvm::codeview::CodeViewRecordStreamer::AddComment (const Twine & T) pure virtual
AddRawComment()
virtual void llvm::codeview::CodeViewRecordStreamer::AddRawComment (const Twine & T) pure virtual
EmitBinaryData()
virtual void llvm::codeview::CodeViewRecordStreamer::EmitBinaryData (StringRef Data) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::mapByteVectorTail().
EmitBytes()
virtual void llvm::codeview::CodeViewRecordStreamer::EmitBytes (StringRef Data) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::endRecord(), llvm::codeview::CodeViewRecordIO::mapGuid(), and llvm::codeview::CodeViewRecordIO::mapStringZ().
EmitIntValue()
virtual void llvm::codeview::CodeViewRecordStreamer::EmitIntValue (uint64_t Value, unsigned Size) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::mapInteger(), and llvm::codeview::CodeViewRecordIO::mapStringZVectorZ().
getTypeName()
virtual std::string llvm::codeview::CodeViewRecordStreamer::getTypeName (TypeIndex TI) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::mapInteger().
isVerboseAsm()
virtual bool llvm::codeview::CodeViewRecordStreamer::isVerboseAsm () pure virtual
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/CodeViewRecordIO.h