LLVM: llvm::NVPTXRegisterInfo Class Reference
llvm::NVPTXRegisterInfo Class Reference
#include "Target/NVPTX/NVPTXRegisterInfo.h"
Public Member Functions
NVPTXRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
NVPTX Callee Saved Registers.
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
ManagedStringPool * getStrPool () const
const char * getName (unsigned RegNo) const
Detailed Description
Definition at line 24 of file NVPTXRegisterInfo.h.
Constructor & Destructor Documentation
NVPTXRegisterInfo()
NVPTXRegisterInfo::NVPTXRegisterInfo ()
Definition at line 95 of file NVPTXRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void NVPTXRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 112 of file NVPTXRegisterInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), and MI.
getCalleeSavedRegs()
const MCPhysReg * NVPTXRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
NVPTX Callee Saved Registers.
Definition at line 102 of file NVPTXRegisterInfo.cpp.
getFrameRegister()
Register NVPTXRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 129 of file NVPTXRegisterInfo.cpp.
getName()
const char* llvm::NVPTXRegisterInfo::getName (unsigned RegNo) const inline
Definition at line 51 of file NVPTXRegisterInfo.h.
References llvm::c_str(), llvm::ManagedStringPool::getManagedString(), llvm::getNVPTXRegClassName(), llvm::getNVPTXRegClassStr(), getStrPool(), and llvm::RISCVFenceField::O.
Referenced by llvm::NVPTXAsmPrinter::getFunctionFrameSymbol().
getReservedRegs()
BitVector NVPTXRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 107 of file NVPTXRegisterInfo.cpp.
getStrPool()
ManagedStringPool* llvm::NVPTXRegisterInfo::getStrPool () const inline
Definition at line 47 of file NVPTXRegisterInfo.h.
Referenced by getName().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXRegisterInfo.h
lib/Target/NVPTX/NVPTXRegisterInfo.cpp