LLVM: llvm::MCEncodedFragment Class Reference
llvm::MCEncodedFragment Class Reference
Interface implemented by fragments that contain encoded instructions and/or data.
#include "llvm/MC/MCFragment.h"
Public Member Functions
bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
void setAlignToBundleEnd (bool V)
uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment.
void setBundlePadding (uint8_t N)
Set the padding size for this fragment.
const MCSubtargetInfo * getSubtargetInfo () const
Retrieve the MCSubTargetInfo in effect when the instruction was encoded.
void setHasInstructions (const MCSubtargetInfo &STI)
Record that the fragment contains instructions with the MCSubtargetInfo in effect when the instruction was encoded.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const MCFragment *F)
Protected Member Functions
MCEncodedFragment (MCFragment::FragmentType FType, bool HasInstructions, MCSection *Sec)
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
ilist_node_impl ()=default
Protected Attributes
const MCSubtargetInfo * STI = nullptr
The MCSubtargetInfo in effect when the instruction was encoded.
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB, FT_BoundaryAlign, FT_SymbolId, FT_CVInlineLines,
FT_CVDefRange, FT_Dummy
}
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, true >
Detailed Description
Interface implemented by fragments that contain encoded instructions and/or data.
Definition at line 113 of file MCFragment.h.
Constructor & Destructor Documentation
MCEncodedFragment()
llvm::MCEncodedFragment::MCEncodedFragment (MCFragment::FragmentType FType, bool HasInstructions, MCSection * Sec) inline protected
Definition at line 120 of file MCFragment.h.
Member Function Documentation
alignToBundleEnd()
bool llvm::MCEncodedFragment::alignToBundleEnd () const inline
Should this fragment be placed at the end of an aligned bundle?
Definition at line 144 of file MCFragment.h.
Referenced by llvm::computeBundlePadding(), and llvm::MCAssembler::writeFragmentPadding().
classof()
static bool llvm::MCEncodedFragment::classof (const MCFragment * F) inline static
Definition at line 129 of file MCFragment.h.
References llvm::MCFragment::FT_CompactEncodedInst, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Dwarf, llvm::MCFragment::FT_DwarfFrame, llvm::MCFragment::FT_Relaxable, and llvm::MCFragment::getKind().
getBundlePadding()
uint8_t llvm::MCEncodedFragment::getBundlePadding () const inline
Get the padding size that must be inserted before this fragment.
Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
Definition at line 152 of file MCFragment.h.
Referenced by llvm::MCAssembler::writeFragmentPadding().
getSubtargetInfo()
const MCSubtargetInfo* llvm::MCEncodedFragment::getSubtargetInfo () const inline
Retrieve the MCSubTargetInfo in effect when the instruction was encoded.
Guaranteed to be non-null if hasInstructions() == true
Definition at line 160 of file MCFragment.h.
Referenced by CanReuseDataFragment(), CheckBundleSubtargets(), llvm::MCAssembler::Finish(), and llvm::MCELFStreamer::MCELFStreamer().
setAlignToBundleEnd()
void llvm::MCEncodedFragment::setAlignToBundleEnd (bool V) inline
Definition at line 145 of file MCFragment.h.
Referenced by CheckBundleSubtargets(), and llvm::MCELFStreamer::EmitBundleUnlock().
setBundlePadding()
void llvm::MCEncodedFragment::setBundlePadding (uint8_t N) inline
Set the padding size for this fragment.
By default it's a no-op, and only some fragments have a meaningful implementation.
Definition at line 156 of file MCFragment.h.
References N.
Referenced by llvm::MCAsmLayout::layoutFragment(), and llvm::MCELFStreamer::MCELFStreamer().
setHasInstructions()
void llvm::MCEncodedFragment::setHasInstructions (const MCSubtargetInfo & STI) inline
Record that the fragment contains instructions with the MCSubtargetInfo in effect when the instruction was encoded.
Definition at line 164 of file MCFragment.h.
References llvm::MCFragment::HasInstructions.
Referenced by CheckBundleSubtargets(), llvm::MCWasmStreamer::EmitIdent(), llvm::MCXCOFFStreamer::EmitInstToData(), llvm::MCWinCOFFStreamer::EmitInstToData(), and llvm::MCELFStreamer::MCELFStreamer().
Member Data Documentation
STI
const MCSubtargetInfo* llvm::MCEncodedFragment::STI = nullptr protected
The MCSubtargetInfo in effect when the instruction was encoded.
It must be non-null for instructions.
Definition at line 126 of file MCFragment.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h