LLVM: llvm::VPRegionBlock Class Reference
llvm::VPRegionBlock Class Reference
VPRegionBlock represents a collection of VPBasicBlocks and VPRegionBlocks which form a Single-Entry-Single-Exit subgraph of the output IR CFG.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPRegionBlock (VPBlockBase *Entry, VPBlockBase *Exit, const std::string &Name="", bool IsReplicator=false)
VPRegionBlock (const std::string &Name="", bool IsReplicator=false)
~VPRegionBlock () override
const VPBlockBase * getEntry () const
VPBlockBase * getEntry ()
void setEntry (VPBlockBase *EntryBlock)
Set EntryBlock as the entry VPBlockBase of this VPRegionBlock.
VPBlockBase & front () const
const VPBlockBase * getExit () const
VPBlockBase * getExit ()
void setExit (VPBlockBase *ExitBlock)
Set ExitBlock as the exit VPBlockBase of this VPRegionBlock.
bool isReplicator () const
An indicator whether this region is to generate multiple replicated instances of output IR corresponding to its VPBlockBases.
void execute (struct VPTransformState *State) override
The method which generates the output IR instructions that correspond to this VPRegionBlock, thereby "executing" the VPlan.
Public Member Functions inherited from llvm::VPBlockBase
virtual ~VPBlockBase ()=default
const std::string & getName () const
void setName (const Twine &newName)
unsigned getVPBlockID () const
VPRegionBlock * getParent ()
const VPRegionBlock * getParent () const
void setParent (VPRegionBlock *P)
const VPBasicBlock * getEntryBasicBlock () const
VPBasicBlock * getEntryBasicBlock ()
const VPBasicBlock * getExitBasicBlock () const
VPBasicBlock * getExitBasicBlock ()
const VPBlocksTy & getSuccessors () const
VPBlocksTy & getSuccessors ()
const VPBlocksTy & getPredecessors () const
VPBlocksTy & getPredecessors ()
VPBlockBase * getSingleSuccessor () const
VPBlockBase * getSinglePredecessor () const
size_t getNumSuccessors () const
size_t getNumPredecessors () const
VPBlockBase * getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
VPBlockBase * getEnclosingBlockWithPredecessors ()
const VPBlocksTy & getHierarchicalSuccessors ()
VPBlockBase * getSingleHierarchicalSuccessor ()
const VPBlocksTy & getHierarchicalPredecessors ()
VPBlockBase * getSingleHierarchicalPredecessor ()
VPValue * getCondBit ()
const VPValue * getCondBit () const
void setCondBit (VPValue *CV)
VPValue * getPredicate ()
const VPValue * getPredicate () const
void setPredicate (VPValue *Pred)
void setOneSuccessor (VPBlockBase *Successor)
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
void setTwoSuccessors (VPBlockBase *IfTrue, VPBlockBase *IfFalse, VPValue *Condition)
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
void setPredecessors (ArrayRef< VPBlockBase *> NewPreds)
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
void clearPredecessors ()
Remove all the predecessor of this block.
void clearSuccessors ()
Remove all the successors of this block and set to null its condition bit.
void printAsOperand (raw_ostream &OS, bool PrintType) const
void print (raw_ostream &OS) const
bool isLegalToHoistInto ()
Return true if it is legal to hoist instructions into this block.
Static Public Member Functions
static bool classof (const VPBlockBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPBlockBase
static void deleteCFG (VPBlockBase *Entry)
Delete all blocks reachable from a given VPBlockBase, inclusive.
Additional Inherited Members
Public Types inherited from llvm::VPBlockBase
using VPBlockTy = enum { VPBasicBlockSC, VPRegionBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
using VPBlocksTy = SmallVectorImpl< VPBlockBase * >
Protected Member Functions inherited from llvm::VPBlockBase
VPBlockBase (const unsigned char SC, const std::string &N)
Detailed Description
VPRegionBlock represents a collection of VPBasicBlocks and VPRegionBlocks which form a Single-Entry-Single-Exit subgraph of the output IR CFG.
A VPRegionBlock may indicate that its contents are to be replicated several times. This is designed to support predicated scalarization, in which a scalar if-then code structure needs to be generated VF * UF times. Having this replication indicator helps to keep a single model for multiple candidate VF's. The actual replication takes place only once the desired VF and UF have been determined.
Definition at line 1146 of file VPlan.h.
Constructor & Destructor Documentation
VPRegionBlock() [1/2]
llvm::VPRegionBlock::VPRegionBlock (VPBlockBase * Entry, VPBlockBase * Exit, const std::string & Name = "", bool IsReplicator = false) inline
Definition at line 1159 of file VPlan.h.
References assert(), llvm::SmallVectorBase::empty(), llvm::VPBlockBase::getPredecessors(), llvm::VPBlockBase::getSuccessors(), and llvm::VPBlockBase::setParent().
VPRegionBlock() [2/2]
llvm::VPRegionBlock::VPRegionBlock (const std::string & Name = "", bool IsReplicator = false) inline
Definition at line 1168 of file VPlan.h.
~VPRegionBlock()
llvm::VPRegionBlock::~VPRegionBlock () inline override
Definition at line 1172 of file VPlan.h.
Member Function Documentation
classof()
static bool llvm::VPRegionBlock::classof (const VPBlockBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 1178 of file VPlan.h.
References llvm::VPBlockBase::getVPBlockID().
execute()
void VPRegionBlock::execute (struct VPTransformState * State) override virtual
The method which generates the output IR instructions that correspond to this VPRegionBlock, thereby "executing" the VPlan.
Implements llvm::VPBlockBase.
Definition at line 231 of file VPlan.cpp.
References assert(), llvm::dbgs(), llvm::VPTransformState::Instance, LLVM_DEBUG, llvm::VPTransformState::UF, and llvm::VPTransformState::VF.
front()
VPBlockBase& llvm::VPRegionBlock::front () const inline
Definition at line 1198 of file VPlan.h.
getEntry() [1/2]
const VPBlockBase* llvm::VPRegionBlock::getEntry () const inline
Definition at line 1182 of file VPlan.h.
Referenced by llvm::VPlan::dump(), llvm::VPBlockBase::getEnclosingBlockWithPredecessors(), llvm::GraphTraits< VPRegionBlock * >::getEntryNode(), llvm::GraphTraits< const VPRegionBlock * >::getEntryNode(), llvm::GraphTraits< VPRegionBlock * >::nodes_begin(), llvm::GraphTraits< const VPRegionBlock * >::nodes_begin(), llvm::VPValue::replaceAllUsesWith(), verifyBlocksInRegion(), verifyRegion(), and verifyRegionRec().
getEntry() [2/2]
VPBlockBase* llvm::VPRegionBlock::getEntry () inline
Definition at line 1183 of file VPlan.h.
getExit() [1/2]
const VPBlockBase* llvm::VPRegionBlock::getExit () const inline
Definition at line 1200 of file VPlan.h.
Referenced by llvm::VPBlockBase::getEnclosingBlockWithSuccessors(), llvm::GraphTraits< Inverse< VPRegionBlock * > >::nodes_begin(), verifyBlocksInRegion(), verifyRegion(), and verifyRegionRec().
getExit() [2/2]
VPBlockBase* llvm::VPRegionBlock::getExit () inline
Definition at line 1201 of file VPlan.h.
isReplicator()
bool llvm::VPRegionBlock::isReplicator () const inline
An indicator whether this region is to generate multiple replicated instances of output IR corresponding to its VPBlockBases.
Definition at line 1214 of file VPlan.h.
Referenced by llvm::VPlan::dump().
setEntry()
void llvm::VPRegionBlock::setEntry (VPBlockBase * EntryBlock) inline
Set EntryBlock as the entry VPBlockBase of this VPRegionBlock.
EntryBlock must have no predecessors.
Definition at line 1187 of file VPlan.h.
References assert(), llvm::SmallVectorBase::empty(), llvm::VPBlockBase::getPredecessors(), and llvm::VPBlockBase::setParent().
setExit()
void llvm::VPRegionBlock::setExit (VPBlockBase * ExitBlock) inline
Set ExitBlock as the exit VPBlockBase of this VPRegionBlock.
ExitBlock must have no successors.
Definition at line 1205 of file VPlan.h.
References assert(), llvm::SmallVectorBase::empty(), llvm::VPBlockBase::getSuccessors(), and llvm::VPBlockBase::setParent().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp