LLVM: llvm::AMDGPUAAResult Class Reference
llvm::AMDGPUAAResult Class Reference
A simple AA result that uses TBAA metadata to answer queries.
#include "Target/AMDGPU/AMDGPUAliasAnalysis.h"
Public Member Functions
AMDGPUAAResult (const DataLayout &DL, Triple T)
AMDGPUAAResult (AMDGPUAAResult &&Arg)
bool invalidate (Function &, const PreservedAnalyses &)
Handle invalidation events from the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
Public Member Functions inherited from llvm::AAResultBase< AMDGPUAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< AMDGPUAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
A simple AA result that uses TBAA metadata to answer queries.
Definition at line 31 of file AMDGPUAliasAnalysis.h.
Constructor & Destructor Documentation
AMDGPUAAResult() [1/2]
llvm::AMDGPUAAResult::AMDGPUAAResult (const DataLayout & DL, Triple T) inline explicit
Definition at line 37 of file AMDGPUAliasAnalysis.h.
Referenced by llvm::AMDGPUAAWrapperPass::doInitialization(), and llvm::AMDGPUAA::run().
AMDGPUAAResult() [2/2]
llvm::AMDGPUAAResult::AMDGPUAAResult (AMDGPUAAResult && Arg) inline
Definition at line 39 of file AMDGPUAliasAnalysis.h.
Member Function Documentation
alias()
AliasResult AMDGPUAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 78 of file AMDGPUAliasAnalysis.cpp.
References llvm::AAResultBase< DerivedT >::alias(), getAliasResult(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::NoAlias, and llvm::MemoryLocation::Ptr.
Referenced by invalidate().
invalidate()
bool llvm::AMDGPUAAResult::invalidate (Function & , const PreservedAnalyses &) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 45 of file AMDGPUAliasAnalysis.h.
References alias(), B, and pointsToConstantMemory().
pointsToConstantMemory()
bool AMDGPUAAResult::pointsToConstantMemory (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool OrLocal)
Definition at line 92 of file AMDGPUAliasAnalysis.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, Arg, AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, F(), llvm::Function::getCallingConv(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::GetUnderlyingObject(), llvm::Function::hasParamAttribute(), llvm::NoAlias, llvm::AAResultBase< DerivedT >::pointsToConstantMemory(), llvm::MemoryLocation::Ptr, and llvm::CallingConv::SPIR_KERNEL.
Referenced by invalidate().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUAliasAnalysis.h
lib/Target/AMDGPU/AMDGPUAliasAnalysis.cpp