LLVM: llvm::MCAssembler Class Reference
llvm::MCAssembler Class Reference
#include "llvm/MC/MCAssembler.h"
Classes
struct CGProfileEntry
Public Types
using SectionListType = std::vector< MCSection * >
using SymbolDataListType = std::vector< const MCSymbol * >
using const_iterator = pointee_iterator< SectionListType::const_iterator >
using iterator = pointee_iterator< SectionListType::iterator >
using const_symbol_iterator = pointee_iterator< SymbolDataListType::const_iterator >
using symbol_iterator = pointee_iterator< SymbolDataListType::iterator >
using symbol_range = iterator_range< symbol_iterator >
using const_symbol_range = iterator_range< const_symbol_iterator >
using const_indirect_symbol_iterator = std::vector< IndirectSymbolData >::const_iterator
using indirect_symbol_iterator = std::vector< IndirectSymbolData >::iterator
using const_data_region_iterator = std::vector< DataRegionData >::const_iterator
using data_region_iterator = std::vector< DataRegionData >::iterator
using VersionInfoType = struct { bool EmitBuildVersion
MachO specific deployment target version info.
Public Member Functions
MCAssembler (MCContext &Context, std::unique_ptr< MCAsmBackend > Backend, std::unique_ptr< MCCodeEmitter > Emitter, std::unique_ptr< MCObjectWriter > Writer)
Construct a new assembler instance.
MCAssembler (const MCAssembler &)=delete
MCAssembler & operator= (const MCAssembler &)=delete
~MCAssembler ()
uint64_t computeFragmentSize (const MCAsmLayout &Layout, const MCFragment &F) const
Compute the effective fragment size assuming it is laid out at the given SectionAddress and FragmentOffset.
const MCSymbol * getAtom (const MCSymbol &S) const
Find the symbol which defines the atom containing the given symbol, or null if there is no such symbol.
bool isSymbolLinkerVisible (const MCSymbol &SD) const
Check whether a particular symbol is visible to the linker and is required in the symbol table, or whether it can be discarded by the assembler.
void writeSectionData (raw_ostream &OS, const MCSection *Section, const MCAsmLayout &Layout) const
Emit the section contents to OS.
bool isThumbFunc (const MCSymbol *Func) const
Check whether a given symbol has been flagged with .thumb_func.
void setIsThumbFunc (const MCSymbol *Func)
Flag a function symbol as the target of a .thumb_func directive.
unsigned getELFHeaderEFlags () const
ELF e_header flags.
void setELFHeaderEFlags (unsigned Flags)
const VersionInfoType & getVersionInfo () const
MachO deployment target version information.
void setVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion=VersionTuple())
void setBuildVersion (MachO::PlatformType Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion=VersionTuple())
void reset ()
Reuse an assembler instance.
MCContext & getContext () const
MCAsmBackend * getBackendPtr () const
MCCodeEmitter * getEmitterPtr () const
MCObjectWriter * getWriterPtr () const
MCAsmBackend & getBackend () const
MCCodeEmitter & getEmitter () const
MCObjectWriter & getWriter () const
MCDwarfLineTableParams getDWARFLinetableParams () const
void setDWARFLinetableParams (MCDwarfLineTableParams P)
void Finish ()
Finish - Do final processing and write the object to the output stream.
void layout (MCAsmLayout &Layout)
bool getSubsectionsViaSymbols () const
void setSubsectionsViaSymbols (bool Value)
bool isIncrementalLinkerCompatible () const
void setIncrementalLinkerCompatible (bool Value)
bool getRelaxAll () const
void setRelaxAll (bool Value)
bool isBundlingEnabled () const
unsigned getBundleAlignSize () const
void setBundleAlignSize (unsigned Size)
void dump () const
Section List Access
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_t size () const
Symbol List Access
symbol_iterator symbol_begin ()
const_symbol_iterator symbol_begin () const
symbol_iterator symbol_end ()
const_symbol_iterator symbol_end () const
symbol_range symbols ()
const_symbol_range symbols () const
size_t symbol_size () const
Indirect Symbol List Access
std::vector< IndirectSymbolData > & getIndirectSymbols ()
indirect_symbol_iterator indirect_symbol_begin ()
const_indirect_symbol_iterator indirect_symbol_begin () const
indirect_symbol_iterator indirect_symbol_end ()
const_indirect_symbol_iterator indirect_symbol_end () const
size_t indirect_symbol_size () const
Linker Option List Access
std::vector< std::vector< std::string > > & getLinkerOptions ()
Backend Data Access
bool registerSection (MCSection &Section)
void registerSymbol (const MCSymbol &Symbol, bool *Created=nullptr)
ArrayRef< std::string > getFileNames ()
void addFileName (StringRef FileName)
void writeFragmentPadding (raw_ostream &OS, const MCEncodedFragment &F, uint64_t FSize) const
Write the necessary bundle padding to OS.
Public Attributes
union {
MCVersionMinType Type
Used when EmitBuildVersion==false.
MachO::PlatformType Platform
Used when EmitBuildVersion==true.
} TypeOrPlatform
unsigned Major
unsigned Minor
unsigned Update
VersionTuple SDKVersion
An optional version of the SDK that was used to build the source.
std::vector< std::pair< StringRef, const MCSymbol * > > Symvers
Friends
class MCAsmLayout
Data Region List Access
std::vector< CGProfileEntry > CGProfile
std::vector< DataRegionData > & getDataRegions ()
data_region_iterator data_region_begin ()
const_data_region_iterator data_region_begin () const
data_region_iterator data_region_end ()
const_data_region_iterator data_region_end () const
size_t data_region_size () const
MCLOHContainer & getLOHContainer ()
const MCLOHContainer & getLOHContainer () const
Detailed Description
Definition at line 60 of file MCAssembler.h.
Member Typedef Documentation
const_data_region_iterator
using llvm::MCAssembler::const_data_region_iterator = std::vector<DataRegionData>::const_iterator
Definition at line 82 of file MCAssembler.h.
const_indirect_symbol_iterator
using llvm::MCAssembler::const_indirect_symbol_iterator = std::vector<IndirectSymbolData>::const_iterator
Definition at line 78 of file MCAssembler.h.
const_iterator
using llvm::MCAssembler::const_iterator = pointee_iterator<SectionListType::const_iterator>
Definition at line 67 of file MCAssembler.h.
const_symbol_iterator
using llvm::MCAssembler::const_symbol_iterator = pointee_iterator<SymbolDataListType::const_iterator>
Definition at line 71 of file MCAssembler.h.
const_symbol_range
using llvm::MCAssembler::const_symbol_range = iterator_range<const_symbol_iterator>
Definition at line 75 of file MCAssembler.h.
data_region_iterator
using llvm::MCAssembler::data_region_iterator = std::vector<DataRegionData>::iterator
Definition at line 83 of file MCAssembler.h.
indirect_symbol_iterator
using llvm::MCAssembler::indirect_symbol_iterator = std::vector<IndirectSymbolData>::iterator
Definition at line 79 of file MCAssembler.h.
iterator
using llvm::MCAssembler::iterator = pointee_iterator<SectionListType::iterator>
Definition at line 68 of file MCAssembler.h.
SectionListType
using llvm::MCAssembler::SectionListType = std::vector<MCSection *>
Definition at line 64 of file MCAssembler.h.
symbol_iterator
using llvm::MCAssembler::symbol_iterator = pointee_iterator<SymbolDataListType::iterator>
Definition at line 72 of file MCAssembler.h.
symbol_range
using llvm::MCAssembler::symbol_range = iterator_range<symbol_iterator>
Definition at line 74 of file MCAssembler.h.
SymbolDataListType
using llvm::MCAssembler::SymbolDataListType = std::vector<const MCSymbol *>
Definition at line 65 of file MCAssembler.h.
VersionInfoType
using llvm::MCAssembler::VersionInfoType = struct { bool EmitBuildVersion
MachO specific deployment target version info.
Definition at line 89 of file MCAssembler.h.
Constructor & Destructor Documentation
MCAssembler() [1/2]
MCAssembler::MCAssembler (MCContext & Context, std::unique_ptr< MCAsmBackend > Backend, std::unique_ptr< MCCodeEmitter > Emitter, std::unique_ptr< MCObjectWriter > Writer)
Construct a new assembler instance.
Definition at line 82 of file MCAssembler.cpp.
References ~MCAssembler().
MCAssembler() [2/2]
llvm::MCAssembler::MCAssembler (const MCAssembler &) delete
~MCAssembler()
MCAssembler::~MCAssembler () default
Referenced by MCAssembler().
Member Function Documentation
addFileName()
void llvm::MCAssembler::addFileName (StringRef FileName) inline
Definition at line 441 of file MCAssembler.h.
References llvm::computeBundlePadding(), llvm::dump(), F(), and llvm::is_contained().
Referenced by llvm::MCObjectStreamer::EmitFileDirective().
begin() [1/2]
iterator llvm::MCAssembler::begin () inline
Definition at line 333 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::computeSymbolTable(), dump(), and needPadding().
begin() [2/2]
const_iterator llvm::MCAssembler::begin () const inline
Definition at line 334 of file MCAssembler.h.
computeFragmentSize()
uint64_t MCAssembler::computeFragmentSize (const MCAsmLayout & Layout, const MCFragment & F) const
Compute the effective fragment size assuming it is laid out at the given SectionAddress and FragmentOffset.
Definition at line 288 of file MCAssembler.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::MCExpr::evaluateAsValue(), F(), llvm::MCFragment::FT_Align, llvm::MCFragment::FT_BoundaryAlign, llvm::MCFragment::FT_CompactEncodedInst, llvm::MCFragment::FT_CVDefRange, llvm::MCFragment::FT_CVInlineLines, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Dummy, llvm::MCFragment::FT_Dwarf, llvm::MCFragment::FT_DwarfFrame, llvm::MCFragment::FT_Fill, llvm::MCFragment::FT_LEB, llvm::MCFragment::FT_Org, llvm::MCFragment::FT_Relaxable, llvm::MCFragment::FT_SymbolId, llvm::MCAlignFragment::getAlignment(), getBackend(), getBackendPtr(), getContext(), llvm::MCAsmLayout::getFragmentOffset(), llvm::MCFragment::getKind(), llvm::MCOrgFragment::getLoc(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCAsmBackend::getMinimumNopSize(), llvm::MCOrgFragment::getOffset(), llvm::MCFragment::getParent(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCAlignFragment::hasEmitNops(), llvm_unreachable, llvm::offsetToAlignment(), llvm::MCContext::reportError(), llvm::MCAsmBackend::shouldInsertExtraNopBytesForCodeAlign(), Size, and llvm::MCSection::UseCodeAlign().
Referenced by llvm::MCAsmLayout::getSectionAddressSize(), needPadding(), and writeFragment().
data_region_begin() [1/2]
data_region_iterator llvm::MCAssembler::data_region_begin () inline
Definition at line 401 of file MCAssembler.h.
data_region_begin() [2/2]
const_data_region_iterator llvm::MCAssembler::data_region_begin () const inline
Definition at line 402 of file MCAssembler.h.
data_region_end() [1/2]
data_region_iterator llvm::MCAssembler::data_region_end () inline
Definition at line 406 of file MCAssembler.h.
data_region_end() [2/2]
const_data_region_iterator llvm::MCAssembler::data_region_end () const inline
Definition at line 407 of file MCAssembler.h.
data_region_size()
size_t llvm::MCAssembler::data_region_size () const inline
Definition at line 411 of file MCAssembler.h.
dump()
LLVM_DUMP_METHOD void MCAssembler::dump () const
Definition at line 1189 of file MCAssembler.cpp.
References begin(), end(), llvm::errs(), symbol_begin(), and symbol_end().
Referenced by layout().
end() [1/2]
iterator llvm::MCAssembler::end () inline
Definition at line 336 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::computeSymbolTable(), dump(), and needPadding().
end() [2/2]
const_iterator llvm::MCAssembler::end () const inline
Definition at line 337 of file MCAssembler.h.
Finish()
void MCAssembler::Finish ()
Finish - Do final processing and write the object to the output stream.
Writer is used for custom object writer (as the MCJIT does), if not specified it is automatically created from backend.
Definition at line 865 of file MCAssembler.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::Data, llvm::MCCodeEmitter::encodeInstruction(), llvm::encodeSLEB128(), llvm::encodeULEB128(), llvm::MCExpr::evaluateKnownAbsolute(), llvm::MCAsmBackend::fixupNeedsRelaxationAdvanced(), llvm::FK_Data_1, getBackend(), getBackendPtr(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCLEBFragment::getContents(), getEmitter(), getEmitterPtr(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), llvm::MCRelaxableFragment::getInst(), llvm::MCFixup::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCEncodedFragment::getSubtargetInfo(), llvm::MCValue::getSymA(), llvm::MCLEBFragment::getValue(), getWriter(), llvm::MCLEBFragment::isSigned(), layout(), llvm::MCAsmBackend::relaxInstruction(), llvm::report_fatal_error(), llvm::MCRelaxableFragment::setInst(), llvm::SmallVectorBase::size(), llvm::MCSymbolRefExpr::VK_X86_ABS8, and llvm::MCObjectWriter::writeObject().
Referenced by llvm::MCObjectStreamer::FinishImpl().
getAtom()
const MCSymbol * MCAssembler::getAtom (const MCSymbol & S) const
Find the symbol which defines the atom containing the given symbol, or null if there is no such symbol.
Definition at line 172 of file MCAssembler.cpp.
References assert(), B, DF, llvm::MCExpr::evaluateAsRelocatable(), llvm::MCAsmBackend::evaluateTargetFixup(), Fixup, llvm::MCFixupKindInfo::FKF_Constant, llvm::MCFixupKindInfo::FKF_IsAlignedDownTo32Bits, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCFixupKindInfo::FKF_IsTarget, llvm::MCContext::getAsmInfo(), llvm::MCFragment::getAtom(), getBackend(), getBackendPtr(), llvm::MCValue::getConstant(), getContext(), llvm::MCAsmBackend::getFixupKindInfo(), llvm::MCSymbol::getFragment(), llvm::MCAsmLayout::getFragmentOffset(), llvm::MCFixup::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCFixup::getLoc(), llvm::MCFixup::getOffset(), llvm::MCFragment::getParent(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCFixup::getValue(), getWriterPtr(), llvm::MCValue::isAbsolute(), llvm::MCSymbol::isDefined(), llvm::MCSymbol::isInSection(), llvm::MCAsmInfo::isSectionAtomizableBySymbols(), isSymbolLinkerVisible(), llvm::MCSymbol::isUndefined(), llvm::MCContext::reportError(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by canUseLocalRelocation(), and getFixupKindLog2Size().
getBackend()
MCAsmBackend& llvm::MCAssembler::getBackend () const inline
Definition at line 289 of file MCAssembler.h.
Referenced by computeFragmentSize(), llvm::MCWinCOFFStreamer::EmitAssemblerFlag(), llvm::MCELFStreamer::EmitAssemblerFlag(), llvm::MCWasmStreamer::EmitAssemblerFlag(), llvm::MCObjectStreamer::EmitInstruction(), Finish(), getAtom(), llvm::MachObjectWriter::isFixupKindPCRel(), isIFunc(), layout(), needPadding(), llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer(), writeFragment(), and writeFragmentPadding().
getBackendPtr()
MCAsmBackend* llvm::MCAssembler::getBackendPtr () const inline
Definition at line 283 of file MCAssembler.h.
Referenced by absoluteSymbolDiff(), computeFragmentSize(), Finish(), getAtom(), layout(), needPadding(), reset(), writeFragmentPadding(), and writeSectionData().
getBundleAlignSize()
unsigned llvm::MCAssembler::getBundleAlignSize () const inline
Definition at line 322 of file MCAssembler.h.
Referenced by llvm::computeBundlePadding(), llvm::MCELFStreamer::EmitBundleAlignMode(), llvm::MCELFStreamer::MCELFStreamer(), setSectionAlignmentForBundling(), and writeFragmentPadding().
getContext()
MCContext& llvm::MCAssembler::getContext () const inline
Definition at line 281 of file MCAssembler.h.
References Context.
Referenced by adjustFixupValue(), llvm::AVRAsmBackend::applyFixup(), llvm::MipsAsmBackend::applyFixup(), llvm::ARMAsmBackend::applyFixup(), llvm::RISCVAsmBackend::applyFixup(), canUseLocalRelocation(), computeFragmentSize(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitFrame(), llvm::MCELFStreamer::EmitIdent(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::CodeViewContext::encodeDefRange(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::RISCVAsmBackend::evaluateTargetFixup(), llvm::MipsTargetELFStreamer::finish(), llvm::SparcMCExpr::fixELFSymbolsInTLSFixups(), getARMFixupKindMachOInfo(), getAtom(), llvm::MCAsmLayout::getBaseSymbol(), getFixupKindLog2Size(), getFixupKindSize(), getFixupOffset(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), isIFunc(), layout(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), needPadding(), llvm::MachObjectWriter::recordRelocation(), and llvm::RISCVAsmBackend::shouldInsertFixupForCodeAlign().
getDataRegions()
std::vector<DataRegionData>& llvm::MCAssembler::getDataRegions () inline
Definition at line 399 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::writeObject().
getDWARFLinetableParams()
MCDwarfLineTableParams llvm::MCAssembler::getDWARFLinetableParams () const inline
Definition at line 295 of file MCAssembler.h.
Referenced by needPadding().
getELFHeaderEFlags()
unsigned llvm::MCAssembler::getELFHeaderEFlags () const inline
ELF e_header flags.
Definition at line 251 of file MCAssembler.h.
Referenced by llvm::AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer(), llvm::AVRELFStreamer::AVRELFStreamer(), createPPCMCAsmInfo(), llvm::MipsTargetELFStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetELFStreamer::emitDirectiveNaN2008(), llvm::MipsTargetELFStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic2(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder(), llvm::MipsTargetELFStreamer::finish(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer(), and llvm::MipsTargetELFStreamer::setUsesMicroMips().
getEmitter()
MCCodeEmitter& llvm::MCAssembler::getEmitter () const inline
Definition at line 291 of file MCAssembler.h.
Referenced by CheckBundleSubtargets(), llvm::MCWasmStreamer::EmitIdent(), llvm::MCXCOFFStreamer::EmitInstToData(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), and Finish().
getEmitterPtr()
MCCodeEmitter* llvm::MCAssembler::getEmitterPtr () const inline
Definition at line 285 of file MCAssembler.h.
Referenced by Finish(), reset(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
getFileNames()
ArrayRef<std::string> llvm::MCAssembler::getFileNames () inline
Definition at line 439 of file MCAssembler.h.
Referenced by getTime(), and isIFunc().
getIndirectSymbols()
std::vector<IndirectSymbolData>& llvm::MCAssembler::getIndirectSymbols () inline
Definition at line 364 of file MCAssembler.h.
getLinkerOptions()
std::vector<std::vector<std::string> >& llvm::MCAssembler::getLinkerOptions () inline
Definition at line 388 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::writeObject().
getLOHContainer() [1/2]
MCLOHContainer& llvm::MCAssembler::getLOHContainer () inline
Definition at line 420 of file MCAssembler.h.
Referenced by reset(), and llvm::MachObjectWriter::writeObject().
getLOHContainer() [2/2]
const MCLOHContainer& llvm::MCAssembler::getLOHContainer () const inline
Definition at line 421 of file MCAssembler.h.
getRelaxAll()
bool llvm::MCAssembler::getRelaxAll () const inline
Definition at line 317 of file MCAssembler.h.
Referenced by CanReuseDataFragment(), CheckBundleSubtargets(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MCELFStreamer::MCELFStreamer(), and needPadding().
getSubsectionsViaSymbols()
bool llvm::MCAssembler::getSubsectionsViaSymbols () const inline
Definition at line 307 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl().
getVersionInfo()
const VersionInfoType& llvm::MCAssembler::getVersionInfo () const inline
MachO deployment target version information.
Definition at line 255 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::writeObject().
getWriter()
MCObjectWriter& llvm::MCAssembler::getWriter () const inline
Definition at line 293 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitAddrsig(), llvm::MCObjectStreamer::EmitAddrsigSym(), Finish(), layout(), and llvm::RISCVAsmBackend::shouldInsertFixupForCodeAlign().
getWriterPtr()
MCObjectWriter* llvm::MCAssembler::getWriterPtr () const inline
Definition at line 287 of file MCAssembler.h.
Referenced by llvm::RISCVAsmBackend::evaluateTargetFixup(), getAtom(), and reset().
indirect_symbol_begin() [1/2]
indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_begin () inline
Definition at line 368 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::bindIndirectSymbols().
indirect_symbol_begin() [2/2]
const_indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_begin () const inline
Definition at line 371 of file MCAssembler.h.
indirect_symbol_end() [1/2]
indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_end () inline
Definition at line 375 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::bindIndirectSymbols().
indirect_symbol_end() [2/2]
const_indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_end () const inline
Definition at line 378 of file MCAssembler.h.
indirect_symbol_size()
size_t llvm::MCAssembler::indirect_symbol_size () const inline
Definition at line 382 of file MCAssembler.h.
isBundlingEnabled()
bool llvm::MCAssembler::isBundlingEnabled () const inline
Definition at line 320 of file MCAssembler.h.
Referenced by CanReuseDataFragment(), CheckBundleSubtargets(), llvm::MCObjectStreamer::EmitInstruction(), hasVariantSymbol(), llvm::MCELFStreamer::MCELFStreamer(), setSectionAlignmentForBundling(), and writeFragmentPadding().
isIncrementalLinkerCompatible()
bool llvm::MCAssembler::isIncrementalLinkerCompatible () const inline
Definition at line 310 of file MCAssembler.h.
isSymbolLinkerVisible()
bool MCAssembler::isSymbolLinkerVisible (const MCSymbol & SD) const
Check whether a particular symbol is visible to the linker and is required in the symbol table, or whether it can be discarded by the assembler.
This also effects whether the assembler treats the label as potentially defining a separate atom.
Definition at line 161 of file MCAssembler.cpp.
References llvm::MCSymbol::isTemporary(), and llvm::MCSymbol::isUsedInReloc().
Referenced by llvm::MachObjectWriter::computeSymbolTable(), and getAtom().
isThumbFunc()
bool MCAssembler::isThumbFunc (const MCSymbol * Func) const
Check whether a given symbol has been flagged with .thumb_func.
Definition at line 130 of file MCAssembler.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), llvm::MCSymbolRefExpr::getKind(), llvm::MCValue::getRefKind(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isVariable(), llvm::Ref, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), getARMFixupKindMachOInfo(), isIFunc(), and llvm::ARMAsmBackend::shouldForceRelocation().
layout()
void MCAssembler::layout (MCAsmLayout & Layout)
Definition at line 760 of file MCAssembler.cpp.
References llvm::MCAsmBackend::applyFixup(), assert(), DEBUG_WITH_TYPE, dump(), llvm::numbers::e, llvm::errs(), llvm::MCObjectWriter::executePostLayoutBinding(), getBackend(), getBackendPtr(), getContext(), llvm::MCSection::getFragmentList(), llvm::MCAsmLayout::getSectionOrder(), getWriter(), llvm_unreachable, llvm::MCSection::setLayoutOrder(), llvm::MCSection::setOrdinal(), and llvm::MCAsmBackend::shouldInsertFixupForCodeAlign().
Referenced by Finish().
operator=()
MCAssembler& llvm::MCAssembler::operator= (const MCAssembler &) delete
registerSection()
bool MCAssembler::registerSection (MCSection & Section)
Definition at line 122 of file MCAssembler.cpp.
References llvm::MCSection::isRegistered(), and llvm::MCSection::setIsRegistered().
Referenced by llvm::MCObjectStreamer::changeSectionImpl(), llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolIndex(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), and llvm::MipsTargetELFStreamer::finish().
registerSymbol()
void MCAssembler::registerSymbol (const MCSymbol & Symbol, bool * Created = nullptr)
Definition at line 453 of file MCAssembler.cpp.
References llvm::MCSymbol::isRegistered(), and llvm::MCSymbol::setIsRegistered().
Referenced by llvm::MachObjectWriter::bindIndirectSymbols(), llvm::MCELFStreamer::ChangeSection(), llvm::MCWasmStreamer::ChangeSection(), llvm::MipsELFStreamer::createPendingLabelRelocs(), llvm::MCObjectStreamer::EmitAddrsigSym(), llvm::MCObjectStreamer::EmitAssignment(), llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolIndex(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolStorageClass(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolType(), llvm::MCXCOFFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MCELFStreamer::EmitIdent(), llvm::MCObjectStreamer::EmitLabel(), llvm::MipsTargetELFStreamer::emitLabel(), llvm::MCObjectStreamer::EmitLabelAtPos(), llvm::MCELFStreamer::EmitLocalCommonSymbol(), llvm::MCXCOFFStreamer::EmitSymbolAttribute(), llvm::MCWinCOFFStreamer::EmitSymbolAttribute(), llvm::MCELFStreamer::EmitSymbolAttribute(), llvm::MCWasmStreamer::EmitSymbolAttribute(), llvm::MCELFStreamer::EmitWeakReference(), llvm::MCWasmStreamer::EmitWeakReference(), llvm::SparcMCExpr::fixELFSymbolsInTLSFixups(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::HexagonMCELFStreamer::HexagonMCEmitLocalCommonSymbol(), and isIFunc().
reset()
void MCAssembler::reset ()
Reuse an assembler instance.
Definition at line 95 of file MCAssembler.cpp.
References getBackendPtr(), getEmitterPtr(), getLOHContainer(), getWriterPtr(), llvm::MCCodeEmitter::reset(), llvm::MCObjectWriter::reset(), llvm::MCAsmBackend::reset(), and llvm::MCLOHContainer::reset().
setBuildVersion()
void llvm::MCAssembler::setBuildVersion (MachO::PlatformType Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion = VersionTuple()) inline
Definition at line 266 of file MCAssembler.h.
setBundleAlignSize()
void llvm::MCAssembler::setBundleAlignSize (unsigned Size) inline
Definition at line 324 of file MCAssembler.h.
References assert(), and Size.
Referenced by llvm::MCELFStreamer::EmitBundleAlignMode().
setDWARFLinetableParams()
void llvm::MCAssembler::setDWARFLinetableParams (MCDwarfLineTableParams P) inline
Definition at line 296 of file MCAssembler.h.
References layout(), and P.
setELFHeaderEFlags()
void llvm::MCAssembler::setELFHeaderEFlags (unsigned Flags) inline
Definition at line 252 of file MCAssembler.h.
Referenced by llvm::AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer(), llvm::AVRELFStreamer::AVRELFStreamer(), createPPCMCAsmInfo(), llvm::MipsTargetELFStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetELFStreamer::emitDirectiveNaN2008(), llvm::MipsTargetELFStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic2(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder(), llvm::MipsTargetELFStreamer::finish(), llvm::HexagonGetLastSlot(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer(), and llvm::MipsTargetELFStreamer::setUsesMicroMips().
setIncrementalLinkerCompatible()
void llvm::MCAssembler::setIncrementalLinkerCompatible (bool Value) inline
Definition at line 313 of file MCAssembler.h.
setIsThumbFunc()
void llvm::MCAssembler::setIsThumbFunc (const MCSymbol * Func) inline
Flag a function symbol as the target of a .thumb_func directive.
Definition at line 248 of file MCAssembler.h.
References llvm::SmallPtrSetImpl< PtrType >::insert().
setRelaxAll()
void llvm::MCAssembler::setRelaxAll (bool Value) inline
Definition at line 318 of file MCAssembler.h.
Referenced by llvm::createELFStreamer(), llvm::createWasmStreamer(), and llvm::createXCOFFStreamer().
setSubsectionsViaSymbols()
void llvm::MCAssembler::setSubsectionsViaSymbols (bool Value) inline
Definition at line 308 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitAssemblerFlag().
setVersionMin()
void llvm::MCAssembler::setVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion = VersionTuple()) inline
Definition at line 256 of file MCAssembler.h.
size()
size_t llvm::MCAssembler::size () const inline
Definition at line 339 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::writeObject().
symbol_begin() [1/2]
symbol_iterator llvm::MCAssembler::symbol_begin () inline
Definition at line 344 of file MCAssembler.h.
Referenced by dump().
symbol_begin() [2/2]
const_symbol_iterator llvm::MCAssembler::symbol_begin () const inline
Definition at line 345 of file MCAssembler.h.
symbol_end() [1/2]
symbol_iterator llvm::MCAssembler::symbol_end () inline
Definition at line 347 of file MCAssembler.h.
Referenced by dump().
symbol_end() [2/2]
const_symbol_iterator llvm::MCAssembler::symbol_end () const inline
Definition at line 348 of file MCAssembler.h.
symbol_size()
size_t llvm::MCAssembler::symbol_size () const inline
Definition at line 355 of file MCAssembler.h.
symbols() [1/2]
symbol_range llvm::MCAssembler::symbols () inline
Definition at line 350 of file MCAssembler.h.
References llvm::make_range().
Referenced by llvm::MachObjectWriter::computeSymbolTable(), isIFunc(), and isInSymtab().
symbols() [2/2]
const_symbol_range llvm::MCAssembler::symbols () const inline
Definition at line 351 of file MCAssembler.h.
References llvm::make_range().
writeFragmentPadding()
void MCAssembler::writeFragmentPadding (raw_ostream & OS, const MCEncodedFragment & F, uint64_t FSize) const
Write the necessary bundle padding to OS.
Expects a fragment F containing instructions and its size FSize.
Definition at line 463 of file MCAssembler.cpp.
References llvm::MCEncodedFragment::alignToBundleEnd(), assert(), getBackend(), getBackendPtr(), getBundleAlignSize(), llvm::MCEncodedFragment::getBundlePadding(), llvm::MCFragment::hasInstructions(), isBundlingEnabled(), and llvm::report_fatal_error().
Referenced by llvm::MCELFStreamer::MCELFStreamer(), and writeFragment().
writeSectionData()
void MCAssembler::writeSectionData (raw_ostream & OS, const MCSection * Section, const MCAsmLayout & Layout) const
Emit the section contents to OS.
Definition at line 668 of file MCAssembler.cpp.
References assert(), llvm::numbers::e, F(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_begin(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_end(), llvm::MCFragment::FT_Align, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Fill, getBackendPtr(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCAsmLayout::getSectionFileSize(), llvm::MCSection::isVirtualSection(), llvm_unreachable, llvm::report_fatal_error(), and llvm::SmallVectorBase::size().
Referenced by addData(), and isIFunc().
Friends And Related Function Documentation
MCAsmLayout
friend class MCAsmLayout friend
Definition at line 61 of file MCAssembler.h.
Member Data Documentation
CGProfile
std::vector<CGProfileEntry> llvm::MCAssembler::CGProfile
Definition at line 430 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::emitCGProfileEntry().
Major
unsigned llvm::MCAssembler::Major
Definition at line 94 of file MCAssembler.h.
Minor
unsigned llvm::MCAssembler::Minor
Definition at line 95 of file MCAssembler.h.
Platform
MachO::PlatformType llvm::MCAssembler::Platform
Used when EmitBuildVersion==true.
Definition at line 92 of file MCAssembler.h.
SDKVersion
VersionTuple llvm::MCAssembler::SDKVersion
An optional version of the SDK that was used to build the source.
Definition at line 98 of file MCAssembler.h.
Symvers
std::vector<std::pair<StringRef, const MCSymbol *> > llvm::MCAssembler::Symvers
Definition at line 210 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::emitELFSymverDirective(), and isIFunc().
Type
MCVersionMinType llvm::MCAssembler::Type
Used when EmitBuildVersion==false.
Definition at line 91 of file MCAssembler.h.
TypeOrPlatform
union { ... } llvm::MCAssembler::TypeOrPlatform
Update
unsigned llvm::MCAssembler::Update
Definition at line 96 of file MCAssembler.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCAssembler.h
lib/MC/MCAssembler.cpp