LLVM: llvm::object::SectionRef Class Reference
llvm::object::SectionRef Class Reference
This is a value type class that represents a single section in the list of sections in the object file.
#include "llvm/Object/ObjectFile.h"
Public Member Functions
SectionRef ()=default
SectionRef (DataRefImpl SectionP, const ObjectFile *Owner)
SectionRef.
bool operator== (const SectionRef &Other) const
bool operator!= (const SectionRef &Other) const
bool operator< (const SectionRef &Other) const
void moveNext ()
Expected< StringRef > getName () const
uint64_t getAddress () const
uint64_t getIndex () const
uint64_t getSize () const
Expected< StringRef > getContents () const
uint64_t getAlignment () const
Get the alignment of this section as the actual value (not log 2).
bool isCompressed () const
bool isText () const
Whether this section contains instructions.
bool isData () const
Whether this section contains data, not instructions.
bool isBSS () const
Whether this section contains BSS uninitialized data.
bool isVirtual () const
bool isBitcode () const
bool isStripped () const
bool isBerkeleyText () const
Whether this section will be placed in the text segment, according to the Berkeley size format.
bool isBerkeleyData () const
Whether this section will be placed in the data segment, according to the Berkeley size format.
bool containsSymbol (SymbolRef S) const
relocation_iterator relocation_begin () const
relocation_iterator relocation_end () const
iterator_range< relocation_iterator > relocations () const
Expected< section_iterator > getRelocatedSection () const
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObject () const
Friends
class SymbolRef
Detailed Description
This is a value type class that represents a single section in the list of sections in the object file.
Definition at line 81 of file ObjectFile.h.
Constructor & Destructor Documentation
SectionRef() [1/2]
llvm::object::SectionRef::SectionRef () default
SectionRef() [2/2]
llvm::object::SectionRef::SectionRef (DataRefImpl SectionP, const ObjectFile * Owner) inline
SectionRef.
Definition at line 411 of file ObjectFile.h.
Member Function Documentation
containsSymbol()
bool SectionRef::containsSymbol (SymbolRef S) const
Definition at line 47 of file ObjectFile.cpp.
References llvm::consumeError(), llvm::object::SymbolRef::getSection(), and llvm::Expected< T >::takeError().
getAddress()
uint64_t llvm::object::SectionRef::getAddress () const inline
Definition at line 438 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionAddress().
Referenced by llvm::RuntimeDyldMachOX86_64::finalizeSection(), llvm::getOffset(), and llvm::RuntimeDyldMachO::getRelocationValueRef().
getAlignment()
uint64_t llvm::object::SectionRef::getAlignment () const inline
Get the alignment of this section as the actual value (not log 2).
Definition at line 458 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionAlignment().
Referenced by llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), and llvm::RuntimeDyldImpl::emitSection().
getContents()
Expected< StringRef > llvm::object::SectionRef::getContents () const inline
Definition at line 450 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionContents(), and llvm::Expected< T >::takeError().
Referenced by llvm::RuntimeDyldImpl::emitSection().
getIndex()
uint64_t llvm::object::SectionRef::getIndex () const inline
Definition at line 442 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionIndex().
getName()
Expected< StringRef > llvm::object::SectionRef::getName () const inline
Definition at line 434 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionName().
Referenced by llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::RuntimeDyldImpl::emitSection(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::RuntimeDyldMachOI386::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::object::Decompressor::isCompressed(), and loadObj().
getObject()
const ObjectFile * llvm::object::SectionRef::getObject () const inline
Definition at line 514 of file ObjectFile.h.
Referenced by llvm::object::ELFSectionRef::ELFSectionRef(), llvm::object::ELFSectionRef::getObject(), llvm::isReadOnlyData(), llvm::isRequiredForExecution(), and llvm::isZeroInit().
getRawDataRefImpl()
DataRefImpl llvm::object::SectionRef::getRawDataRefImpl () const inline
Definition at line 510 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldMachOI386::finalizeSection(), llvm::object::COFFObjectFile::getCOFFSection(), llvm::DenseMapInfo< object::SectionRef >::getHashValue(), llvm::object::MachOObjectFile::getSectionID(), llvm::object::COFFObjectFile::getSectionID(), llvm::object::MachOObjectFile::getSectionType(), llvm::object::WasmObjectFile::getWasmSection(), and llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
getRelocatedSection()
Expected< section_iterator > llvm::object::SectionRef::getRelocatedSection () const inline
Definition at line 506 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocatedSection().
getSize()
uint64_t llvm::object::SectionRef::getSize () const inline
Definition at line 446 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionSize().
Referenced by llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), and llvm::RuntimeDyldImpl::emitSection().
isBerkeleyData()
bool llvm::object::SectionRef::isBerkeleyData () const inline
Whether this section will be placed in the data segment, according to the Berkeley size format.
This is true if the section is allocatable and contains data (e.g. PROGBITS), but is not text.
Definition at line 494 of file ObjectFile.h.
References llvm::object::ObjectFile::isBerkeleyData().
isBerkeleyText()
bool llvm::object::SectionRef::isBerkeleyText () const inline
Whether this section will be placed in the text segment, according to the Berkeley size format.
This is true if the section is allocatable, and contains either code or readonly data.
Definition at line 490 of file ObjectFile.h.
References llvm::object::ObjectFile::isBerkeleyText().
isBitcode()
bool llvm::object::SectionRef::isBitcode () const inline
Definition at line 482 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionBitcode().
isBSS()
bool llvm::object::SectionRef::isBSS () const inline
Whether this section contains BSS uninitialized data.
Definition at line 474 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionBSS().
isCompressed()
bool llvm::object::SectionRef::isCompressed () const inline
Definition at line 462 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionCompressed().
Referenced by llvm::object::Decompressor::isCompressed().
isData()
bool llvm::object::SectionRef::isData () const inline
Whether this section contains data, not instructions.
Definition at line 470 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionData().
isStripped()
bool llvm::object::SectionRef::isStripped () const inline
Definition at line 486 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionStripped().
isText()
bool llvm::object::SectionRef::isText () const inline
Whether this section contains instructions.
Definition at line 466 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionText().
Referenced by llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::RuntimeDyldMachOX86_64::finalizeSection(), llvm::RuntimeDyldMachOI386::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::RuntimeDyldMachO::getRelocationValueRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
isVirtual()
bool llvm::object::SectionRef::isVirtual () const inline
Definition at line 478 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionVirtual().
Referenced by llvm::RuntimeDyldImpl::emitSection().
moveNext()
void llvm::object::SectionRef::moveNext () inline
Definition at line 430 of file ObjectFile.h.
References llvm::object::ObjectFile::moveSectionNext().
operator!=()
bool llvm::object::SectionRef::operator!= (const SectionRef & Other) const inline
Definition at line 421 of file ObjectFile.h.
References Other.
operator<()
bool llvm::object::SectionRef::operator< (const SectionRef & Other) const inline
Definition at line 425 of file ObjectFile.h.
References assert().
operator==()
bool llvm::object::SectionRef::operator== (const SectionRef & Other) const inline
Definition at line 416 of file ObjectFile.h.
relocation_begin()
relocation_iterator llvm::object::SectionRef::relocation_begin () const inline
Definition at line 498 of file ObjectFile.h.
References llvm::object::ObjectFile::section_rel_begin().
relocation_end()
relocation_iterator llvm::object::SectionRef::relocation_end () const inline
Definition at line 502 of file ObjectFile.h.
References llvm::object::ObjectFile::section_rel_end().
relocations()
iterator_range<relocation_iterator> llvm::object::SectionRef::relocations () const inline
Definition at line 130 of file ObjectFile.h.
References llvm::object::RelocationRef::getObject(), llvm::object::RelocationRef::getRawDataRefImpl(), and llvm::make_range().
Referenced by loadObj().
Friends And Related Function Documentation
SymbolRef
friend class SymbolRef friend
Definition at line 82 of file ObjectFile.h.
The documentation for this class was generated from the following files:
include/llvm/Object/ObjectFile.h
lib/Object/ObjectFile.cpp