LLVM: llvm::DiagnosticPrinterRawOStream Class Reference
llvm::DiagnosticPrinterRawOStream Class Reference
Basic diagnostic printer that uses an underlying raw_ostream.
#include "llvm/IR/DiagnosticPrinter.h"
Public Member Functions
DiagnosticPrinterRawOStream (raw_ostream &Stream)
DiagnosticPrinter & operator<< (char C) override
DiagnosticPrinter & operator<< (unsigned char C) override
DiagnosticPrinter & operator<< (signed char C) override
DiagnosticPrinter & operator<< (StringRef Str) override
DiagnosticPrinter & operator<< (const char *Str) override
DiagnosticPrinter & operator<< (const std::string &Str) override
DiagnosticPrinter & operator<< (unsigned long N) override
DiagnosticPrinter & operator<< (long N) override
DiagnosticPrinter & operator<< (unsigned long long N) override
DiagnosticPrinter & operator<< (long long N) override
DiagnosticPrinter & operator<< (const void *P) override
DiagnosticPrinter & operator<< (unsigned int N) override
DiagnosticPrinter & operator<< (int N) override
DiagnosticPrinter & operator<< (double N) override
DiagnosticPrinter & operator<< (const Twine &Str) override
DiagnosticPrinter & operator<< (const Value &V) override
DiagnosticPrinter & operator<< (const Module &M) override
DiagnosticPrinter & operator<< (const SMDiagnostic &Diag) override
Public Member Functions inherited from llvm::DiagnosticPrinter
virtual ~DiagnosticPrinter ()=default
Protected Attributes
raw_ostream & Stream
Detailed Description
Basic diagnostic printer that uses an underlying raw_ostream.
Definition at line 61 of file DiagnosticPrinter.h.
Constructor & Destructor Documentation
DiagnosticPrinterRawOStream()
llvm::DiagnosticPrinterRawOStream::DiagnosticPrinterRawOStream (raw_ostream & Stream) inline
Definition at line 66 of file DiagnosticPrinter.h.
References C, N, llvm::DiagnosticPrinter::operator<<(), and P.
Member Function Documentation
operator<<() [1/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (char C) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 22 of file DiagnosticPrinter.cpp.
References C, and Stream.
Referenced by operator<<().
operator<<() [2/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (unsigned char C) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 27 of file DiagnosticPrinter.cpp.
References C, and Stream.
operator<<() [3/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (signed char C) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 32 of file DiagnosticPrinter.cpp.
References C, and Stream.
operator<<() [4/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (StringRef Str) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 37 of file DiagnosticPrinter.cpp.
References Stream.
operator<<() [5/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (const char * Str) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 42 of file DiagnosticPrinter.cpp.
References Stream.
operator<<() [6/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (const std::string & Str) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 47 of file DiagnosticPrinter.cpp.
References Stream.
operator<<() [7/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (unsigned long N) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 53 of file DiagnosticPrinter.cpp.
References N, and Stream.
operator<<() [8/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (long N) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 57 of file DiagnosticPrinter.cpp.
References N, and Stream.
operator<<() [9/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (unsigned long long N) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 62 of file DiagnosticPrinter.cpp.
References N, and Stream.
operator<<() [10/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (long long N) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 68 of file DiagnosticPrinter.cpp.
References N, and Stream.
operator<<() [11/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (const void * P) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 73 of file DiagnosticPrinter.cpp.
References P, and Stream.
operator<<() [12/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (unsigned int N) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 78 of file DiagnosticPrinter.cpp.
References N, and Stream.
operator<<() [13/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (int N) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 83 of file DiagnosticPrinter.cpp.
References N, and Stream.
operator<<() [14/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (double N) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 88 of file DiagnosticPrinter.cpp.
References N, and Stream.
operator<<() [15/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (const Twine & Str) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 93 of file DiagnosticPrinter.cpp.
References llvm::Twine::print(), and Stream.
operator<<() [16/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (const Value & V) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 99 of file DiagnosticPrinter.cpp.
References llvm::Value::getName(), and Stream.
operator<<() [17/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (const Module & M) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 104 of file DiagnosticPrinter.cpp.
References llvm::Module::getModuleIdentifier(), operator<<(), and Stream.
operator<<() [18/18]
DiagnosticPrinter & DiagnosticPrinterRawOStream::operator<< (const SMDiagnostic & Diag) override virtual
Implements llvm::DiagnosticPrinter.
Definition at line 111 of file DiagnosticPrinter.cpp.
References llvm::SMDiagnostic::print(), and Stream.
Member Data Documentation
Stream
raw_ostream& llvm::DiagnosticPrinterRawOStream::Stream protected
Definition at line 63 of file DiagnosticPrinter.h.
Referenced by operator<<().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticPrinter.h
lib/IR/DiagnosticPrinter.cpp