LLVM: llvm::MachineRegisterInfo::Delegate Class Reference
llvm::MachineRegisterInfo::Delegate Class Reference abstract
#include "llvm/CodeGen/MachineRegisterInfo.h"
Public Member Functions
virtual ~Delegate ()=default
virtual void MRI_NoteNewVirtualRegister (unsigned Reg)=0
Detailed Description
Definition at line 54 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
~Delegate()
virtual llvm::MachineRegisterInfo::Delegate::~Delegate () virtual default
Member Function Documentation
MRI_NoteNewVirtualRegister()
virtual void llvm::MachineRegisterInfo::Delegate::MRI_NoteNewVirtualRegister (unsigned Reg) pure virtual
Referenced by llvm::MachineRegisterInfo::cloneVirtualRegister(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), and llvm::MachineRegisterInfo::createVirtualRegister().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineRegisterInfo.h
lib/CodeGen/MachineRegisterInfo.cpp