LLVM: llvm::SparcMachineFunctionInfo Class Reference
llvm::SparcMachineFunctionInfo Class Reference
#include "Target/Sparc/SparcMachineFunctionInfo.h"
Public Member Functions
SparcMachineFunctionInfo ()
SparcMachineFunctionInfo (MachineFunction &MF)
unsigned getGlobalBaseReg () const
void setGlobalBaseReg (unsigned Reg)
int getVarArgsFrameOffset () const
void setVarArgsFrameOffset (int Offset)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
void setLeafProc (bool rhs)
bool isLeafProc () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 19 of file SparcMachineFunctionInfo.h.
Constructor & Destructor Documentation
SparcMachineFunctionInfo() [1/2]
llvm::SparcMachineFunctionInfo::SparcMachineFunctionInfo () inline
Definition at line 34 of file SparcMachineFunctionInfo.h.
SparcMachineFunctionInfo() [2/2]
llvm::SparcMachineFunctionInfo::SparcMachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 37 of file SparcMachineFunctionInfo.h.
Member Function Documentation
getGlobalBaseReg()
unsigned llvm::SparcMachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 41 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcInstrInfo::getGlobalBaseReg().
getSRetReturnReg()
unsigned llvm::SparcMachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 47 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerReturn_32().
getVarArgsFrameOffset()
int llvm::SparcMachineFunctionInfo::getVarArgsFrameOffset () const inline
Definition at line 44 of file SparcMachineFunctionInfo.h.
Referenced by LowerVASTART().
isLeafProc()
bool llvm::SparcMachineFunctionInfo::isLeafProc () const inline
Definition at line 51 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitPrologue(), and llvm::SparcFrameLowering::getFrameIndexReference().
setGlobalBaseReg()
void llvm::SparcMachineFunctionInfo::setGlobalBaseReg (unsigned Reg) inline
Definition at line 42 of file SparcMachineFunctionInfo.h.
References Reg.
Referenced by llvm::SparcInstrInfo::getGlobalBaseReg().
setLeafProc()
void llvm::SparcMachineFunctionInfo::setLeafProc (bool rhs) inline
Definition at line 50 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcFrameLowering::determineCalleeSaves().
setSRetReturnReg()
void llvm::SparcMachineFunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 48 of file SparcMachineFunctionInfo.h.
References Reg.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32().
setVarArgsFrameOffset()
void llvm::SparcMachineFunctionInfo::setVarArgsFrameOffset (int Offset) inline
Definition at line 45 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
The documentation for this class was generated from the following files:
lib/Target/Sparc/SparcMachineFunctionInfo.h
lib/Target/Sparc/SparcMachineFunctionInfo.cpp