LLVM: llvm::DeclContext Class Reference
llvm::DeclContext Class Reference
A DeclContext is a named program scope that is used for ODR uniquing of types.
#include "llvm/DWARFLinker/DWARFLinkerDeclContext.h"
Public Types
using Map = DenseSet< DeclContext *, DeclMapInfo >
Public Member Functions
DeclContext ()
DeclContext (unsigned Hash, uint32_t Line, uint32_t ByteSize, uint16_t Tag, StringRef Name, StringRef File, const DeclContext &Parent, DWARFDie LastSeenDIE=DWARFDie(), unsigned CUId=0)
uint32_t getQualifiedNameHash () const
bool setLastSeenDIE (CompileUnit &U, const DWARFDie &Die)
Set the last DIE/CU a context was seen in and, possibly invalidate the context if it is ambiguous.
uint32_t getCanonicalDIEOffset () const
void setCanonicalDIEOffset (uint32_t Offset)
bool isDefinedInClangModule () const
void setDefinedInClangModule (bool Val)
uint16_t getTag () const
StringRef getName () const
Detailed Description
A DeclContext is a named program scope that is used for ODR uniquing of types.
The set of DeclContext for the ODR-subject parts of a Dwarf link is expanded (and uniqued) with each new object file processed. We need to determine the context of each DIE in an linked object file to see if the corresponding type has already been emitted.
The contexts are conceptually organized as a tree (eg. a function scope is contained in a namespace scope that contains other scopes), but storing/accessing them in an actual tree is too inefficient: we need to be able to very quickly query a context for a given child context by name. Storing a StringMap in each DeclContext would be too space inefficient.
The solution here is to give each DeclContext a link to its parent (this allows to walk up the tree), but to query the existence of a specific DeclContext using a separate DenseMap keyed on the hash of the fully qualified name of the context.
Definition at line 73 of file DWARFLinkerDeclContext.h.
Member Typedef Documentation
Map
using llvm::DeclContext::Map = DenseSet<DeclContext *, DeclMapInfo>
Definition at line 75 of file DWARFLinkerDeclContext.h.
Constructor & Destructor Documentation
DeclContext() [1/2]
llvm::DeclContext::DeclContext () inline
Definition at line 77 of file DWARFLinkerDeclContext.h.
Referenced by llvm::DeclContextTree::getChildDeclContext().
DeclContext() [2/2]
llvm::DeclContext::DeclContext (unsigned Hash, uint32_t Line, uint32_t ByteSize, uint16_t Tag, StringRef Name, StringRef File, const DeclContext & Parent, DWARFDie LastSeenDIE = DWARFDie(), unsigned CUId = 0) inline
Definition at line 79 of file DWARFLinkerDeclContext.h.
Member Function Documentation
getCanonicalDIEOffset()
uint32_t llvm::DeclContext::getCanonicalDIEOffset () const inline
Definition at line 90 of file DWARFLinkerDeclContext.h.
Referenced by llvm::CompileUnit::fixupForwardReferences().
getName()
StringRef llvm::DeclContext::getName () const inline
Definition at line 97 of file DWARFLinkerDeclContext.h.
References File, and Name.
getQualifiedNameHash()
uint32_t llvm::DeclContext::getQualifiedNameHash () const inline
Definition at line 86 of file DWARFLinkerDeclContext.h.
Referenced by llvm::DeclContextTree::getChildDeclContext().
getTag()
uint16_t llvm::DeclContext::getTag () const inline
Definition at line 96 of file DWARFLinkerDeclContext.h.
References llvm::Tag.
Referenced by llvm::DeclContextTree::getChildDeclContext().
isDefinedInClangModule()
bool llvm::DeclContext::isDefinedInClangModule () const inline
Definition at line 93 of file DWARFLinkerDeclContext.h.
setCanonicalDIEOffset()
void llvm::DeclContext::setCanonicalDIEOffset (uint32_t Offset) inline
Definition at line 91 of file DWARFLinkerDeclContext.h.
setDefinedInClangModule()
void llvm::DeclContext::setDefinedInClangModule (bool Val) inline
Definition at line 94 of file DWARFLinkerDeclContext.h.
setLastSeenDIE()
bool llvm::DeclContext::setLastSeenDIE (CompileUnit & U, const DWARFDie & Die)
Set the last DIE/CU a context was seen in and, possibly invalidate the context if it is ambiguous.
In the current implementation, we don't handle overloaded functions well, because the argument types are not taken into account when computing the DeclContext tree.
Some of this is mitigated byt using mangled names that do contain the arguments types, but sometimes (e.g. with function templates) we don't have that. In that case, just do not unique anything that refers to the contexts we are not able to distinguish.
If a context that is not a namespace appears twice in the same CU, we know it is ambiguous. Make it invalid.
Definition at line 30 of file DWARFLinkerDeclContext.cpp.
References llvm::CompileUnit::DIEInfo::Ctxt, llvm::CompileUnit::getInfo(), llvm::CompileUnit::getOrigUnit(), and llvm::CompileUnit::getUniqueID().
The documentation for this class was generated from the following files:
include/llvm/DWARFLinker/DWARFLinkerDeclContext.h
lib/DWARFLinker/DWARFLinkerDeclContext.cpp