LLVM: llvm::TruncInstCombine Class Reference
llvm::TruncInstCombine Class Reference
#include "Transforms/AggressiveInstCombine/AggressiveInstCombineInternal.h"
Public Member Functions
TruncInstCombine (TargetLibraryInfo &TLI, const DataLayout &DL, const DominatorTree &DT)
bool run (Function &F)
Perform TruncInst pattern optimization on given function.
Detailed Description
Definition at line 52 of file AggressiveInstCombineInternal.h.
Constructor & Destructor Documentation
TruncInstCombine()
llvm::TruncInstCombine::TruncInstCombine (TargetLibraryInfo & TLI, const DataLayout & DL, const DominatorTree & DT) inline
Definition at line 79 of file AggressiveInstCombineInternal.h.
References F(), and run().
Member Function Documentation
run()
bool TruncInstCombine::run (Function & F)
Perform TruncInst pattern optimization on given function.
Definition at line 387 of file TruncInstCombine.cpp.
References llvm::dbgs(), I, llvm::DominatorTree::isReachableFromEntry(), and LLVM_DEBUG.
Referenced by runImpl(), and TruncInstCombine().
The documentation for this class was generated from the following files:
lib/Transforms/AggressiveInstCombine/AggressiveInstCombineInternal.h
lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp