LLVM: llvm::df_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
llvm::df_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
#include "llvm/ADT/DepthFirstIterator.h"
Public Types
using pointer = typename super::pointer
Public Member Functions
bool operator== (const df_iterator &x) const
bool operator!= (const df_iterator &x) const
const NodeRef & operator* () const
NodeRef operator-> () const
df_iterator & operator++ ()
df_iterator & skipChildren ()
Skips all children of the current node and traverses to next node.
df_iterator operator++ (int)
bool nodeVisited (NodeRef Node) const
unsigned getPathLength () const
getPathLength - Return the length of the path from the entry node to the current node, counting both nodes.
NodeRef getPath (unsigned n) const
getPath - Return the n'th node in the path from the entry node to the current node.
Static Public Member Functions
static df_iterator begin (const GraphT &G)
static df_iterator end (const GraphT &G)
static df_iterator begin (const GraphT &G, SetType &S)
static df_iterator end (const GraphT &G, SetType &S)
Additional Inherited Members
Public Attributes inherited from llvm::df_iterator_storage< SetType, ExtStorage >
SetType Visited
Detailed Description
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>>
class llvm::df_iterator< GraphT, SetType, ExtStorage, GT >
Definition at line 85 of file DepthFirstIterator.h.
Member Typedef Documentation
pointer
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> using llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::pointer = typename super::pointer
Definition at line 147 of file DepthFirstIterator.h.
Member Function Documentation
begin() [1/2]
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::begin (const GraphT & G) inline static
Definition at line 150 of file DepthFirstIterator.h.
Referenced by llvm::df_begin().
begin() [2/2]
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::begin (const GraphT & G, SetType & S) inline static
Definition at line 156 of file DepthFirstIterator.h.
end() [1/2]
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::end (const GraphT & G) inline static
Definition at line 153 of file DepthFirstIterator.h.
Referenced by llvm::df_end().
end() [2/2]
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::end (const GraphT & G, SetType & S) inline static
Definition at line 159 of file DepthFirstIterator.h.
getPath()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeRef llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::getPath (unsigned n) const inline
getPath - Return the n'th node in the path from the entry node to the current node.
Definition at line 210 of file DepthFirstIterator.h.
Referenced by isSupportedGuardInstruction().
getPathLength()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> unsigned llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::getPathLength () const inline
getPathLength - Return the length of the path from the entry node to the current node, counting both nodes.
Definition at line 206 of file DepthFirstIterator.h.
Referenced by isSupportedGuardInstruction().
nodeVisited()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::nodeVisited (NodeRef Node) const inline
Definition at line 200 of file DepthFirstIterator.h.
operator!=()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator!= (const df_iterator< GraphT, SetType, ExtStorage, GT > & x) const inline
Definition at line 164 of file DepthFirstIterator.h.
operator*()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> const NodeRef& llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator* () const inline
Definition at line 166 of file DepthFirstIterator.h.
operator++() [1/2]
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> df_iterator& llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator++ () inline
Definition at line 174 of file DepthFirstIterator.h.
operator++() [2/2]
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator++ (int) inline
Definition at line 190 of file DepthFirstIterator.h.
operator->()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeRef llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator-> () const inline
Definition at line 172 of file DepthFirstIterator.h.
operator==()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator== (const df_iterator< GraphT, SetType, ExtStorage, GT > & x) const inline
Definition at line 161 of file DepthFirstIterator.h.
skipChildren()
template<class GraphT, class SetType = df_iterator_default_set<typename GraphTraits<GraphT>::NodeRef>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> df_iterator& llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::skipChildren () inline
Skips all children of the current node and traverses to next node.
Note: This function takes care of incrementing the iterator. If you always increment and call this function, you risk walking off the end.
Definition at line 183 of file DepthFirstIterator.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/DepthFirstIterator.h