LLVM: llvm::MemoryDependenceResults Class Reference
llvm::MemoryDependenceResults Class Reference
Provides a lazy, caching interface for making common memory aliasing information queries, backed by LLVM's alias analysis passes.
#include "llvm/Analysis/MemoryDependenceAnalysis.h"
Public Types
using NonLocalDepInfo = std::vector< NonLocalDepEntry >
Public Member Functions
MemoryDependenceResults (AliasAnalysis &AA, AssumptionCache &AC, const TargetLibraryInfo &TLI, DominatorTree &DT, PhiValues &PV, unsigned DefaultBlockScanLimit)
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation in the new PM.
unsigned getDefaultBlockScanLimit () const
Some methods limit the number of instructions they will examine.
MemDepResult getDependency (Instruction *QueryInst, OrderedBasicBlock *OBB=nullptr)
Returns the instruction on which a memory operation depends.
const NonLocalDepInfo & getNonLocalCallDependency (CallBase *QueryCall)
Perform a full dependency query for the specified call, returning the set of blocks that the value is potentially live across.
void getNonLocalPointerDependency (Instruction *QueryInst, SmallVectorImpl< NonLocalDepResult > &Result)
Perform a full dependency query for an access to the QueryInst's specified memory location, returning the set of instructions that either define or clobber the value.
void removeInstruction (Instruction *InstToRemove)
Removes an instruction from the dependence analysis, updating the dependence of instructions that previously depended on it.
void invalidateCachedPointerInfo (Value *Ptr)
Invalidates cached information about the specified pointer, because it may be too conservative in memdep.
void invalidateCachedPredecessors ()
Clears the PredIteratorCache info.
MemDepResult getPointerDependencyFrom (const MemoryLocation &Loc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock *BB, Instruction *QueryInst=nullptr, unsigned *Limit=nullptr, OrderedBasicBlock *OBB=nullptr)
Returns the instruction on which a memory location depends.
MemDepResult getSimplePointerDependencyFrom (const MemoryLocation &MemLoc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock *BB, Instruction *QueryInst, unsigned *Limit, OrderedBasicBlock *OBB)
MemDepResult getInvariantGroupPointerDependency (LoadInst *LI, BasicBlock *BB)
This analysis looks for other loads and stores with invariant.group metadata and the same pointer operand.
void releaseMemory ()
Release memory in caches.
Static Public Member Functions
static unsigned getLoadLoadClobberFullWidthSize (const Value *MemLocBase, int64_t MemLocOffs, unsigned MemLocSize, const LoadInst *LI)
Looks at a memory location for a load (specified by MemLocBase, Offs, and Size) and compares it against a load.
Detailed Description
Provides a lazy, caching interface for making common memory aliasing information queries, backed by LLVM's alias analysis passes.
The dependency information returned is somewhat unusual, but is pragmatic. If queried about a store or call that might modify memory, the analysis will return the instruction[s] that may either load from that memory or store to it. If queried with a load or call that can never modify memory, the analysis will return calls and stores that might modify the pointer, but generally does not return loads unless a) they are volatile, or b) they load from must-aliased pointers. Returning a dependence on must-alias'd pointers instead of all pointers interacts well with the internal caching mechanism.
Definition at line 276 of file MemoryDependenceAnalysis.h.
Member Typedef Documentation
NonLocalDepInfo
using llvm::MemoryDependenceResults::NonLocalDepInfo = std::vector<NonLocalDepEntry>
Definition at line 282 of file MemoryDependenceAnalysis.h.
Constructor & Destructor Documentation
MemoryDependenceResults()
llvm::MemoryDependenceResults::MemoryDependenceResults (AliasAnalysis & AA, AssumptionCache & AC, const TargetLibraryInfo & TLI, DominatorTree & DT, PhiValues & PV, unsigned DefaultBlockScanLimit) inline
Definition at line 368 of file MemoryDependenceAnalysis.h.
References F(), isLoad(), and P.
Member Function Documentation
getDefaultBlockScanLimit()
unsigned MemoryDependenceResults::getDefaultBlockScanLimit () const
Some methods limit the number of instructions they will examine.
The return value of this method is the default limit that will be used if no limit is explicitly passed in.
Definition at line 1813 of file MemoryDependenceAnalysis.cpp.
Referenced by eliminateDeadStores(), GetLocation(), and getSimplePointerDependencyFrom().
getDependency()
MemDepResult MemoryDependenceResults::getDependency (Instruction * QueryInst, OrderedBasicBlock * OBB = nullptr)
Returns the instruction on which a memory operation depends.
See the class comment for more details. It is illegal to call this on non-memory instructions.
Definition at line 715 of file MemoryDependenceAnalysis.cpp.
References llvm::BasicBlock::begin(), llvm::Function::getEntryBlock(), llvm::MemDepResult::getInst(), llvm::ilist_node_impl< OptionsT >::getIterator(), GetLocation(), llvm::MemDepResult::getNonFuncLocal(), llvm::MemDepResult::getNonLocal(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), getPointerDependencyFrom(), llvm::MemDepResult::getUnknown(), I, isLoad(), llvm::isModSet(), llvm::AAResults::onlyReadsMemory(), llvm::MemoryLocation::Ptr, and RemoveFromReverseMap().
Referenced by llvm::createMemDepPrinter(), eliminateDeadStores(), and getNonLocalCallDependency().
getInvariantGroupPointerDependency()
MemDepResult MemoryDependenceResults::getInvariantGroupPointerDependency (LoadInst * LI, BasicBlock * BB)
This analysis looks for other loads and stores with invariant.group metadata and the same pointer operand.
Returns Unknown if it does not find anything, and Def if it can be assumed that 2 instructions load or store the same value and NonLocal which indicate that non-local Def was found, which can be retrieved by calling getNonLocalPointerDependency with the same queried instruction.
Definition at line 357 of file MemoryDependenceAnalysis.cpp.
References assert(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), GEP, llvm::MemDepResult::getDef(), llvm::MemDepResult::getNonLocal(), llvm::Instruction::getParent(), llvm::LoadInst::getPointerOperand(), llvm::MemDepResult::getUnknown(), llvm::Instruction::hasMetadata(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::Other, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::stripPointerCasts(), and llvm::Value::uses().
Referenced by getPointerDependencyFrom().
getLoadLoadClobberFullWidthSize()
unsigned MemoryDependenceResults::getLoadLoadClobberFullWidthSize (const Value * MemLocBase, int64_t MemLocOffs, unsigned MemLocSize, const LoadInst * LI) static
Looks at a memory location for a load (specified by MemLocBase, Offs, and Size) and compares it against a load.
If the specified load could be safely widened to a larger integer load that is 1) still efficient, 2) safe for the target, and 3) would provide the specified memory location value, then this function returns the size in bytes of the load width to use. If not, this returns zero.
Definition at line 241 of file MemoryDependenceAnalysis.cpp.
References llvm::DataLayout::fitsInLegalInteger(), llvm::LoadInst::getAlignment(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GetPointerBaseWithConstantOffset(), llvm::LoadInst::getPointerOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::Function::hasFnAttribute(), llvm::LoadInst::isSimple(), and llvm::NextPowerOf2().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingLoad().
getNonLocalCallDependency()
const MemoryDependenceResults::NonLocalDepInfo & MemoryDependenceResults::getNonLocalCallDependency (CallBase * QueryCall)
Perform a full dependency query for the specified call, returning the set of blocks that the value is potentially live across.
The returned set of results will include a "NonLocal" result for all blocks where the value is live across.
This method assumes the instruction returns a "NonLocal" dependency within its own block.
This returns a reference to an internal data structure that may be invalidated on the next non-local query or when an instruction is removed. Clients must copy this data if they want it around longer than that.
Definition at line 786 of file MemoryDependenceAnalysis.cpp.
References assert(), AssertSorted(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorBase::empty(), llvm::PredIteratorCache::get(), getDependency(), llvm::Instruction::getParent(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, llvm::AAResults::onlyReadsMemory(), llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallPtrSetImplBase::size(), llvm::sort(), and llvm::upper_bound().
Referenced by llvm::createMemDepPrinter().
getNonLocalPointerDependency()
void MemoryDependenceResults::getNonLocalPointerDependency (Instruction * QueryInst, SmallVectorImpl< NonLocalDepResult > & Result)
Perform a full dependency query for an access to the QueryInst's specified memory location, returning the set of instructions that either define or clobber the value.
Warning: For a volatile query instruction, the dependencies will be accurate, and thus usable for reordering, but it is never legal to remove the query instruction.
This method assumes the pointer has a "NonLocal" dependency within QueryInst's parent basic block.
Definition at line 915 of file MemoryDependenceAnalysis.cpp.
References llvm::Address, assert(), llvm::SmallVectorImpl< T >::clear(), llvm::BasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::MemoryLocation::get(), llvm::MemDepResult::getInst(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), getPointerDependencyFrom(), llvm::NonLocalDepEntry::getResult(), llvm::Value::getType(), llvm::MemDepResult::getUnknown(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MemDepResult::isClobber(), llvm::MemDepResult::isDef(), isLoad(), isOrdered(), llvm::Type::isPointerTy(), isVolatile(), llvm::MemoryLocation::Ptr, llvm::SmallVectorTemplateBase< T >::push_back(), RemoveFromReverseMap(), llvm::NonLocalDepEntry::setResult(), SI, and llvm::upper_bound().
Referenced by llvm::createMemDepPrinter().
getPointerDependencyFrom()
MemDepResult MemoryDependenceResults::getPointerDependencyFrom (const MemoryLocation & Loc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock * BB, Instruction * QueryInst = nullptr, unsigned * Limit = nullptr, OrderedBasicBlock * OBB = nullptr)
Returns the instruction on which a memory location depends.
If isLoad is true, this routine ignores may-aliases with read-only operations. If isLoad is false, this routine ignores may-aliases with reads from read-only locations. If possible, pass the query instruction as well; this function may take advantage of the metadata annotated to the query instruction to refine the result. Limit can be used to set the maximum number of instructions that will be examined to find the pointer dependency. On return, it will be set to the number of instructions left to examine. If a null pointer is passed in, the limit will default to the value of -memdep-block-scan-limit.
Note that this is an uncached query, and thus may be inefficient.
Definition at line 328 of file MemoryDependenceAnalysis.cpp.
References assert(), getInvariantGroupPointerDependency(), getSimplePointerDependencyFrom(), llvm::MemDepResult::getUnknown(), llvm::MemDepResult::isDef(), llvm::MemDepResult::isNonLocal(), and llvm::MemDepResult::isUnknown().
Referenced by eliminateDeadStores(), getDependency(), getNonLocalPointerDependency(), and handleFree().
getSimplePointerDependencyFrom()
MemDepResult MemoryDependenceResults::getSimplePointerDependencyFrom (const MemoryLocation & MemLoc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock * BB, Instruction * QueryInst, unsigned * Limit, OrderedBasicBlock * OBB)
Definition at line 441 of file MemoryDependenceAnalysis.cpp.
References llvm::AAResults::alias(), llvm::BasicBlock::begin(), llvm::AAResults::callCapturesBefore(), llvm::clearMust(), llvm::dyn_cast(), llvm::MemoryLocation::get(), llvm::MemDepResult::getClobber(), llvm::Module::getDataLayout(), llvm::MemDepResult::getDef(), getDefaultBlockScanLimit(), llvm::Function::getEntryBlock(), llvm::AAResults::getModRefInfo(), llvm::BasicBlock::getModule(), llvm::MemDepResult::getNonFuncLocal(), llvm::MemDepResult::getNonLocal(), llvm::BasicBlock::getParent(), llvm::GetUnderlyingObject(), llvm::MemDepResult::getUnknown(), llvm::Instruction::hasMetadata(), I, llvm::isModAndRefSet(), llvm::isModOrRefSet(), llvm::AAResults::isMustAlias(), llvm::isNoAliasFn(), llvm::isStrongerThanUnordered(), isVolatile(), LLVM_FALLTHROUGH, llvm::Mod, llvm::Monotonic, llvm::MustAlias, llvm::NoAlias, llvm::NoModRef, llvm::PartialAlias, llvm::AAResults::pointsToConstantMemory(), llvm::MemoryLocation::Ptr, llvm::Ref, llvm::Release, and SI.
Referenced by getPointerDependencyFrom().
invalidate()
bool MemoryDependenceResults::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Handle invalidation in the new PM.
Definition at line 1794 of file MemoryDependenceAnalysis.cpp.
References F(), llvm::PreservedAnalyses::getChecker(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
invalidateCachedPointerInfo()
void MemoryDependenceResults::invalidateCachedPointerInfo (Value * Ptr)
Invalidates cached information about the specified pointer, because it may be too conservative in memdep.
This is an optional call that can be used when the client detects an equivalence between the pointer and some other value and replaces the other value with ptr. This can make Ptr available in more places that cached info does not necessarily keep.
Definition at line 1526 of file MemoryDependenceAnalysis.cpp.
References llvm::Value::getType(), llvm::PhiValues::invalidateValue(), and llvm::Type::isPointerTy().
invalidateCachedPredecessors()
void MemoryDependenceResults::invalidateCachedPredecessors ()
Clears the PredIteratorCache info.
This needs to be done when the CFG changes, e.g., due to splitting critical edges.
Definition at line 1538 of file MemoryDependenceAnalysis.cpp.
References llvm::PredIteratorCache::clear().
releaseMemory()
void llvm::MemoryDependenceResults::releaseMemory ()
Release memory in caches.
removeInstruction()
void MemoryDependenceResults::removeInstruction (Instruction * InstToRemove)
Removes an instruction from the dependence analysis, updating the dependence of instructions that previously depended on it.
Definition at line 1542 of file MemoryDependenceAnalysis.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), D, llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MemDepResult::getInst(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer(), llvm::Value::getType(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::PhiValues::invalidateValue(), llvm::Type::isPointerTy(), llvm::Instruction::isTerminator(), LLVM_DEBUG, P, llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorTemplateBase< T >::push_back(), RemoveFromReverseMap(), and llvm::sort().
Referenced by deleteDeadInstruction(), llvm::FoldSingleEntryPHINodes(), and llvm::gvn::AvailableValue::MaterializeAdjustedValue().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemoryDependenceAnalysis.h
lib/Analysis/MemoryDependenceAnalysis.cpp