LLVM: llvm::VPlanTransforms Class Reference
llvm::VPlanTransforms Class Reference
#include "Transforms/Vectorize/VPlanTransforms.h"
Static Public Member Functions
static void VPInstructionsToVPRecipes (Loop *OrigLoop, VPlanPtr &Plan, LoopVectorizationLegality::InductionList *Inductions, SmallPtrSetImpl< Instruction *> &DeadInstructions)
Replaces the VPInstructions in Plan with corresponding widen recipes.
Detailed Description
Definition at line 22 of file VPlanTransforms.h.
Member Function Documentation
VPInstructionsToVPRecipes()
void VPlanTransforms::VPInstructionsToVPRecipes (Loop * OrigLoop, VPlanPtr & Plan, LoopVectorizationLegality::InductionList * Inductions, SmallPtrSetImpl< Instruction *> & DeadInstructions) static
Replaces the VPInstructions in Plan with corresponding widen recipes.
Definition at line 19 of file VPlanTransforms.cpp.
References llvm::VPBasicBlock::begin(), llvm::SmallPtrSetImpl< PtrType >::count(), E, llvm::VPBasicBlock::end(), llvm::VPRecipeBase::eraseFromParent(), GEP, llvm::VPBlockBase::getCondBit(), llvm::InductionDescriptor::getKind(), llvm::getLoadStorePointerOperand(), llvm::VPValue::getUnderlyingValue(), I, llvm::InductionDescriptor::IK_FpInduction, llvm::InductionDescriptor::IK_IntInduction, llvm::VPRecipeBase::insertBefore(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), and llvm::VPBlockBase::setCondBit().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanTransforms.h
lib/Transforms/Vectorize/VPlanTransforms.cpp