LLVM: llvm::xray::LogBuilderConsumer Class Reference
llvm::xray::LogBuilderConsumer Class Reference
#include "llvm/XRay/FDRRecordConsumer.h"
Public Member Functions
LogBuilderConsumer (std::vector< std::unique_ptr< Record >> &R)
Error consume (std::unique_ptr< Record > R) override
Public Member Functions inherited from llvm::xray::RecordConsumer
virtual ~RecordConsumer ()=default
Detailed Description
Definition at line 28 of file FDRRecordConsumer.h.
Constructor & Destructor Documentation
LogBuilderConsumer()
llvm::xray::LogBuilderConsumer::LogBuilderConsumer (std::vector< std::unique_ptr< Record >> & R) inline explicit
Definition at line 32 of file FDRRecordConsumer.h.
References llvm::xray::RecordConsumer::consume().
Member Function Documentation
consume()
Error llvm::xray::LogBuilderConsumer::consume (std::unique_ptr< Record > R) override virtual
Implements llvm::xray::RecordConsumer.
Definition at line 13 of file LogBuilderConsumer.cpp.
References llvm::createStringError(), llvm::make_error_code(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecordConsumer.h
lib/XRay/LogBuilderConsumer.cpp