LLVM: llvm::MemoryUseOrDef Class Reference
llvm::MemoryUseOrDef Class Reference
Class that has the common methods + fields of memory uses/defs.
#include "llvm/Analysis/MemorySSA.h"
Public Member Functions
void * operator new (size_t)=delete
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (MemoryAccess)
Instruction * getMemoryInst () const
Get the instruction that this MemoryUse represents.
MemoryAccess * getDefiningAccess () const
Get the access that produces the memory state used by this Use.
bool isOptimized () const
MemoryAccess * getOptimized () const
void setOptimized (MemoryAccess *)
Optional< AliasResult > getOptimizedAccessType () const
void resetOptimized ()
Reset the ID of what this MemoryUse was optimized to, causing it to be rewalked by the walker if necessary.
Public Member Functions inherited from llvm::MemoryAccess
MemoryAccess (const MemoryAccess &)=delete
MemoryAccess & operator= (const MemoryAccess &)=delete
void * operator new (size_t)=delete
BasicBlock * getBlock () const
void print (raw_ostream &OS) const
void dump () const
memoryaccess_def_iterator defs_begin ()
This iterator walks over all of the defs in a given MemoryAccess.
const_memoryaccess_def_iterator defs_begin () const
memoryaccess_def_iterator defs_end ()
const_memoryaccess_def_iterator defs_end () const
AllAccessType::self_iterator getIterator ()
Get the iterators for the all access list and the defs only list We default to the all access list.
AllAccessType::const_self_iterator getIterator () const
AllAccessType::reverse_self_iterator getReverseIterator ()
AllAccessType::const_reverse_self_iterator getReverseIterator () const
DefsOnlyType::self_iterator getDefsIterator ()
DefsOnlyType::const_self_iterator getDefsIterator () const
DefsOnlyType::reverse_self_iterator getReverseDefsIterator ()
DefsOnlyType::const_reverse_self_iterator getReverseDefsIterator () const
Public Member Functions inherited from llvm::DerivedUser
DerivedUser (Type *Ty, unsigned VK, Use *U, unsigned NumOps, DeleteValueTy DeleteValue)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MemoryAccess, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const Value *MA)
Static Public Member Functions inherited from llvm::MemoryAccess
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
MemoryUseOrDef (LLVMContext &C, MemoryAccess *DMA, unsigned Vty, DeleteValueTy DeleteValue, Instruction *MI, BasicBlock *BB, unsigned NumOperands)
~MemoryUseOrDef ()=default
void setOptimizedAccessType (Optional< AliasResult > AR)
void setDefiningAccess (MemoryAccess *DMA, bool Optimized=false, Optional< AliasResult > AR=MayAlias)
Protected Member Functions inherited from llvm::MemoryAccess
void setBlock (BasicBlock *BB)
Used by MemorySSA to change the block of a MemoryAccess when it is moved.
unsigned getID () const
Used for debugging and tracking things about MemoryAccesses.
MemoryAccess (LLVMContext &C, unsigned Vty, DeleteValueTy DeleteValue, BasicBlock *BB, unsigned NumOperands)
~MemoryAccess ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MemoryAccess, Options... >::type >
ilist_node_impl ()=default
Friends
class MemorySSA
class MemorySSAUpdater
Additional Inherited Members
Public Types inherited from llvm::MemoryAccess
using AllAccessType = ilist_node< MemoryAccess, ilist_tag< MSSAHelpers::AllAccessTag > >
using DefsOnlyType = ilist_node< MemoryAccess, ilist_tag< MSSAHelpers::DefsOnlyTag > >
using iterator = user_iterator
The user iterators for a memory access.
using const_iterator = const_user_iterator
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::DerivedUser
using DeleteValueTy = void(*)(DerivedUser *)
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MemoryAccess, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< MemoryAccess, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MemoryAccess, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MemoryAccess, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MemoryAccess, Options... >::type, true, true >
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Class that has the common methods + fields of memory uses/defs.
It's a little awkward to have, but there are many cases where we want either a use or def, and there are many cases where uses are needed (defs aren't acceptable), and vice-versa.
This class should never be instantiated directly; make a MemoryUse or MemoryDef instead.
Definition at line 248 of file MemorySSA.h.
Constructor & Destructor Documentation
MemoryUseOrDef()
llvm::MemoryUseOrDef::MemoryUseOrDef (LLVMContext & C, MemoryAccess * DMA, unsigned Vty, DeleteValueTy DeleteValue, Instruction * MI, BasicBlock * BB, unsigned NumOperands) inline protected
Definition at line 285 of file MemorySSA.h.
~MemoryUseOrDef()
llvm::MemoryUseOrDef::~MemoryUseOrDef () protected default
Member Function Documentation
classof()
static bool llvm::MemoryUseOrDef::classof (const Value * MA) inline static
Definition at line 260 of file MemorySSA.h.
References llvm::Value::getValueID().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::MemoryUseOrDef::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (MemoryAccess)
getDefiningAccess()
MemoryAccess* llvm::MemoryUseOrDef::getDefiningAccess () const inline
Get the access that produces the memory state used by this Use.
Definition at line 258 of file MemorySSA.h.
Referenced by llvm::MemorySSAUpdater::applyInsertUpdates(), llvm::canSinkOrHoistInst(), llvm::MemorySSAUpdater::insertDef(), pointerInvalidatedByLoopWithMSSA(), llvm::GVNHoist::rank(), and llvm::MemorySSA::verifyOrderingDominationAndDefUses().
getMemoryInst()
Instruction* llvm::MemoryUseOrDef::getMemoryInst () const inline
Get the instruction that this MemoryUse represents.
Definition at line 255 of file MemorySSA.h.
Referenced by llvm::MemorySSAAnnotatedWriter::emitInstructionAnnot(), instructionClobbersQuery(), lifetimeEndsAt(), and llvm::GVNHoist::rank().
getOptimized()
MemoryAccess * llvm::MemoryUseOrDef::getOptimized () const inline
Definition at line 679 of file MemorySSA.h.
getOptimizedAccessType()
Optional<AliasResult> llvm::MemoryUseOrDef::getOptimizedAccessType () const inline
Definition at line 272 of file MemorySSA.h.
isOptimized()
bool llvm::MemoryUseOrDef::isOptimized () const inline
Definition at line 673 of file MemorySSA.h.
operator new()
void* llvm::MemoryUseOrDef::operator new (size_t) delete
resetOptimized()
void llvm::MemoryUseOrDef::resetOptimized () inline
Reset the ID of what this MemoryUse was optimized to, causing it to be rewalked by the walker if necessary.
This really should only be called by tests.
Definition at line 692 of file MemorySSA.h.
setDefiningAccess()
void llvm::MemoryUseOrDef::setDefiningAccess (MemoryAccess * DMA, bool Optimized = false, Optional< AliasResult > AR = MayAlias) inline protected
Definition at line 300 of file MemorySSA.h.
Referenced by llvm::MemorySSA::createDefinedAccess(), llvm::MemorySSAUpdater::insertDef(), and llvm::MemorySSAUpdater::insertUse().
setOptimized()
void llvm::MemoryUseOrDef::setOptimized (MemoryAccess * MA) inline
Definition at line 685 of file MemorySSA.h.
setOptimizedAccessType()
void llvm::MemoryUseOrDef::setOptimizedAccessType (Optional< AliasResult > AR) inline protected
Definition at line 296 of file MemorySSA.h.
Friends And Related Function Documentation
MemorySSA
friend class MemorySSA friend
Definition at line 282 of file MemorySSA.h.
MemorySSAUpdater
friend class MemorySSAUpdater friend
Definition at line 283 of file MemorySSA.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/MemorySSA.h