LLVM: llvm::LazyCallGraphAnalysis Class Reference
llvm::LazyCallGraphAnalysis Class Reference
An analysis pass which computes the call graph for a module.
#include "llvm/Analysis/LazyCallGraph.h"
Public Types
using Result = LazyCallGraph
Inform generic clients of the result type.
Public Member Functions
LazyCallGraph run (Module &M, ModuleAnalysisManager &AM)
Compute the LazyCallGraph for the module M.
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< LazyCallGraphAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< LazyCallGraphAnalysis >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
An analysis pass which computes the call graph for a module.
Definition at line 1257 of file LazyCallGraph.h.
Member Typedef Documentation
Result
using llvm::LazyCallGraphAnalysis::Result = LazyCallGraph
Inform generic clients of the result type.
Definition at line 1264 of file LazyCallGraph.h.
Member Function Documentation
run()
LazyCallGraph llvm::LazyCallGraphAnalysis::run (Module & M, ModuleAnalysisManager & AM) inline
Compute the LazyCallGraph for the module M.
This just builds the set of entry points to the call graph. The rest is built lazily as it is walked.
Definition at line 1270 of file LazyCallGraph.h.
References F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::LazyCallGraph::LazyCallGraph().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyCallGraph.h
lib/Analysis/LazyCallGraph.cpp