LLVM: llvm::UnsetInit Class Reference
llvm::UnsetInit Class Reference
'?' - Represents an uninitialized value
#include "llvm/TableGen/Record.h"
Public Member Functions
UnsetInit (const UnsetInit &)=delete
UnsetInit & operator= (const UnsetInit &)=delete
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
bool isComplete () const override
This virtual method should be overridden by values that may not be completely specified yet.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a string form.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Static Public Member Functions
static bool classof (const Init *I)
static UnsetInit * get ()
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First, IK_FirstTypedInit, IK_BitInit, IK_BitsInit,
IK_CodeInit, IK_DagInit, IK_DefInit, IK_FieldInit,
IK_IntInit, IK_ListInit, IK_FirstOpInit, IK_BinOpInit,
IK_TernOpInit, IK_UnOpInit, IK_LastOpInit, IK_CondOpInit,
IK_FoldOpInit, IK_IsAOpInit, IK_StringInit, IK_VarInit,
IK_VarListElementInit, IK_VarBitInit, IK_VarDefInit, IK_LastTypedInit,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
'?' - Represents an uninitialized value
Definition at line 457 of file Record.h.
Constructor & Destructor Documentation
UnsetInit()
llvm::UnsetInit::UnsetInit (const UnsetInit &) delete
Member Function Documentation
classof()
static bool llvm::UnsetInit::classof (const Init * I) inline static
Definition at line 464 of file Record.h.
References llvm::Init::getKind().
convertInitializerTo()
Init * UnsetInit::convertInitializerTo (RecTy * Ty) const override virtual
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Implements llvm::Init.
Definition at line 307 of file Record.cpp.
get()
UnsetInit * UnsetInit::get () static
Definition at line 298 of file Record.cpp.
Referenced by llvm::BinOpInit::Fold(), isObjectStart(), and llvm::RecordVal::RecordVal().
getAsString()
std::string llvm::UnsetInit::getAsString () const inline override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 479 of file Record.h.
getBit()
Init* llvm::UnsetInit::getBit (unsigned Bit) const inline override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 473 of file Record.h.
getCastTo()
Init * UnsetInit::getCastTo (RecTy * Ty) const override virtual
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Otherwise, return nullptr.
Implements llvm::Init.
Definition at line 303 of file Record.cpp.
isComplete()
bool llvm::UnsetInit::isComplete () const inline override virtual
This virtual method should be overridden by values that may not be completely specified yet.
Reimplemented from llvm::Init.
Definition at line 477 of file Record.h.
isConcrete()
bool llvm::UnsetInit::isConcrete () const inline override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 478 of file Record.h.
operator=()
UnsetInit& llvm::UnsetInit::operator= (const UnsetInit &) delete
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp