LLVM: llvm::StackSafetyGlobalInfoWrapperPass Class Reference
llvm::StackSafetyGlobalInfoWrapperPass Class Reference
This pass performs the global (interprocedural) stack safety analysis (legacy pass manager).
#include "llvm/Analysis/StackSafetyAnalysis.h"
Public Member Functions
StackSafetyGlobalInfoWrapperPass ()
const StackSafetyGlobalInfo & getResult () const
void print (raw_ostream &O, const Module *M) const override
print - Print out the internal state of the pass.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool runOnModule (Module &M) override
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
This pass performs the global (interprocedural) stack safety analysis (legacy pass manager).
Definition at line 101 of file StackSafetyAnalysis.h.
Constructor & Destructor Documentation
StackSafetyGlobalInfoWrapperPass()
StackSafetyGlobalInfoWrapperPass::StackSafetyGlobalInfoWrapperPass ()
Definition at line 640 of file StackSafetyAnalysis.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeStackSafetyGlobalInfoWrapperPassPass().
Member Function Documentation
getAnalysisUsage()
void StackSafetyGlobalInfoWrapperPass::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 651 of file StackSafetyAnalysis.cpp.
References llvm::AnalysisUsage::addRequired().
getResult()
const StackSafetyGlobalInfo& llvm::StackSafetyGlobalInfoWrapperPass::getResult () const inline
Definition at line 109 of file StackSafetyAnalysis.h.
References llvm::RISCVFenceField::O, and llvm::StackSafetyInfo::print().
Referenced by runOnModule().
print()
void StackSafetyGlobalInfoWrapperPass::print (raw_ostream & OS, const Module * M) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 646 of file StackSafetyAnalysis.cpp.
runOnModule()
bool StackSafetyGlobalInfoWrapperPass::runOnModule (Module & M) override virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 656 of file StackSafetyAnalysis.cpp.
References F(), and getResult().
Member Data Documentation
ID
char StackSafetyGlobalInfoWrapperPass::ID = 0 static
Definition at line 105 of file StackSafetyAnalysis.h.
Referenced by llvm::StackSafetyGlobalPrinterPass::run().
The documentation for this class was generated from the following files:
include/llvm/Analysis/StackSafetyAnalysis.h
lib/Analysis/StackSafetyAnalysis.cpp