LLVM: llvm::pdb::DbiModuleSourceFilesIterator Class Reference
llvm::pdb::DbiModuleSourceFilesIterator Class Reference
#include "llvm/DebugInfo/PDB/Native/DbiModuleList.h"
Public Member Functions
DbiModuleSourceFilesIterator (const DbiModuleList &Modules, uint32_t Modi, uint16_t Filei)
DbiModuleSourceFilesIterator ()=default
DbiModuleSourceFilesIterator (const DbiModuleSourceFilesIterator &R)=default
DbiModuleSourceFilesIterator & operator= (const DbiModuleSourceFilesIterator &R)=default
bool operator== (const DbiModuleSourceFilesIterator &R) const
const StringRef & operator* () const
StringRef & operator* ()
bool operator< (const DbiModuleSourceFilesIterator &RHS) const
std::ptrdiff_t operator- (const DbiModuleSourceFilesIterator &R) const
DbiModuleSourceFilesIterator & operator+= (std::ptrdiff_t N)
DbiModuleSourceFilesIterator & operator-= (std::ptrdiff_t N)
Public Member Functions inherited from llvm::iterator_facade_base< DbiModuleSourceFilesIterator, std::random_access_iterator_tag, StringRef >
DbiModuleSourceFilesIterator operator+ (std::ptrdiff_t n) const
DbiModuleSourceFilesIterator operator- (std::ptrdiff_t n) const
DbiModuleSourceFilesIterator & operator++ ()
DbiModuleSourceFilesIterator operator++ (int)
DbiModuleSourceFilesIterator & operator-- ()
DbiModuleSourceFilesIterator operator-- (int)
bool operator!= (const DbiModuleSourceFilesIterator &RHS) const
bool operator> (const DbiModuleSourceFilesIterator &RHS) const
bool operator<= (const DbiModuleSourceFilesIterator &RHS) const
bool operator>= (const DbiModuleSourceFilesIterator &RHS) const
StringRef * operator-> ()
StringRef * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< DbiModuleSourceFilesIterator, std::random_access_iterator_tag, StringRef >
enum
Detailed Description
Definition at line 31 of file DbiModuleList.h.
Constructor & Destructor Documentation
DbiModuleSourceFilesIterator() [1/3]
DbiModuleSourceFilesIterator::DbiModuleSourceFilesIterator (const DbiModuleList & Modules, uint32_t Modi, uint16_t Filei)
Definition at line 23 of file DbiModuleList.cpp.
References operator==().
DbiModuleSourceFilesIterator() [2/3]
llvm::pdb::DbiModuleSourceFilesIterator::DbiModuleSourceFilesIterator () default
Referenced by llvm::pdb::DbiModuleList::source_files().
DbiModuleSourceFilesIterator() [3/3]
llvm::pdb::DbiModuleSourceFilesIterator::DbiModuleSourceFilesIterator (const DbiModuleSourceFilesIterator & R) default
Member Function Documentation
operator*() [1/2]
const StringRef& llvm::pdb::DbiModuleSourceFilesIterator::operator* () const inline
Definition at line 48 of file DbiModuleList.h.
operator*() [2/2]
StringRef& llvm::pdb::DbiModuleSourceFilesIterator::operator* () inline
Definition at line 49 of file DbiModuleList.h.
References N, operator+=(), operator-(), operator-=(), and operator<().
operator+=()
DbiModuleSourceFilesIterator & DbiModuleSourceFilesIterator::operator+= (std::ptrdiff_t N)
Definition at line 96 of file DbiModuleList.cpp.
References assert(), N, and operator-=().
Referenced by operator*(), and operator-().
operator-()
std::ptrdiff_t DbiModuleSourceFilesIterator::operator- (const DbiModuleSourceFilesIterator & R) const
Definition at line 71 of file DbiModuleList.cpp.
References assert(), llvm::pdb::DbiModuleList::getSourceFileCount(), and operator+=().
Referenced by operator*(), and operator<().
operator-=()
DbiModuleSourceFilesIterator & DbiModuleSourceFilesIterator::operator-= (std::ptrdiff_t N)
Definition at line 106 of file DbiModuleList.cpp.
References assert(), llvm::consumeError(), llvm::pdb::DbiModuleList::getFileName(), llvm::pdb::DbiModuleList::getModuleCount(), llvm::pdb::DbiModuleList::getSourceFileCount(), and N.
Referenced by operator*(), and operator+=().
operator<()
bool DbiModuleSourceFilesIterator::operator< (const DbiModuleSourceFilesIterator & RHS) const
Definition at line 58 of file DbiModuleList.cpp.
References assert(), and operator-().
Referenced by operator*(), and operator==().
operator=()
DbiModuleSourceFilesIterator& llvm::pdb::DbiModuleSourceFilesIterator::operator= (const DbiModuleSourceFilesIterator & R) default
operator==()
bool DbiModuleSourceFilesIterator::operator== (const DbiModuleSourceFilesIterator & R) const
Definition at line 30 of file DbiModuleList.cpp.
References assert(), and operator<().
Referenced by DbiModuleSourceFilesIterator().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/DbiModuleList.h
lib/DebugInfo/PDB/Native/DbiModuleList.cpp