LLVM: llvm::LinkDiagnosticInfo Class Reference
llvm::LinkDiagnosticInfo Class Reference
#include "Linker/LinkDiagnosticInfo.h"
Public Member Functions
LinkDiagnosticInfo (DiagnosticSeverity Severity, const Twine &Msg)
void print (DiagnosticPrinter &DP) const override
Print using the given DP a user-friendly message.
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Detailed Description
Definition at line 15 of file LinkDiagnosticInfo.h.
Constructor & Destructor Documentation
LinkDiagnosticInfo()
LinkDiagnosticInfo::LinkDiagnosticInfo (DiagnosticSeverity Severity, const Twine & Msg)
Definition at line 346 of file IRMover.cpp.
Referenced by print().
Member Function Documentation
print()
void LinkDiagnosticInfo::print (DiagnosticPrinter & DP) const override virtual
Print using the given DP a user-friendly message.
This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implements llvm::DiagnosticInfo.
Definition at line 349 of file IRMover.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, C, llvm::DS_Warning, E, function, llvm::ValueMap< KeyT, ValueT, Config >::getMDMap(), llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), llvm::inconvertibleErrorCode(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), LinkDiagnosticInfo(), llvm::RF_IgnoreMissingLocals, llvm::RF_MoveDistinctMDs, and llvm::T.
The documentation for this class was generated from the following files:
lib/Linker/LinkDiagnosticInfo.h
lib/Linker/IRMover.cpp