LLVM: llvm::mca::InstructionBase Class Reference
llvm::mca::InstructionBase Class Reference
Base class for instructions consumed by the simulation pipeline.
#include "llvm/MCA/Instruction.h"
Public Member Functions
InstructionBase (const InstrDesc &D)
SmallVectorImpl< WriteState > & getDefs ()
const ArrayRef< WriteState > getDefs () const
SmallVectorImpl< ReadState > & getUses ()
const ArrayRef< ReadState > getUses () const
const InstrDesc & getDesc () const
unsigned getLatency () const
unsigned getNumMicroOps () const
bool hasDependentUsers () const
unsigned getNumUsers () const
bool isOptimizableMove () const
void setOptimizableMove ()
bool isMemOp () const
Detailed Description
Base class for instructions consumed by the simulation pipeline.
This class tracks data dependencies as well as generic properties of the instruction.
Definition at line 395 of file Instruction.h.
Constructor & Destructor Documentation
InstructionBase()
llvm::mca::InstructionBase::InstructionBase (const InstrDesc & D) inline
Definition at line 412 of file Instruction.h.
Member Function Documentation
getDefs() [1/2]
SmallVectorImpl<WriteState>& llvm::mca::InstructionBase::getDefs () inline
Definition at line 414 of file Instruction.h.
Referenced by llvm::mca::DispatchStage::DispatchStage().
getDefs() [2/2]
const ArrayRef<WriteState> llvm::mca::InstructionBase::getDefs () const inline
Definition at line 415 of file Instruction.h.
getDesc()
const InstrDesc& llvm::mca::InstructionBase::getDesc () const inline
Definition at line 418 of file Instruction.h.
Referenced by llvm::mca::Scheduler::analyzeDataDependencies(), llvm::mca::LSUnit::dispatch(), llvm::mca::DispatchStage::DispatchStage(), llvm::mca::InstructionTables::execute(), llvm::mca::DispatchStage::isAvailable(), llvm::mca::Scheduler::isAvailable(), llvm::mca::LSUnit::isAvailable(), llvm::mca::Scheduler::mustIssueImmediately(), llvm::mca::ExecuteStage::notifyReservedOrReleasedBuffers(), llvm::mca::LSUnitBase::onInstructionRetired(), llvm::mca::Scheduler::select(), and llvm::mca::verifyInstructionEliminated().
getLatency()
unsigned llvm::mca::InstructionBase::getLatency () const inline
Definition at line 420 of file Instruction.h.
References llvm::mca::InstrDesc::MaxLatency.
getNumMicroOps()
unsigned llvm::mca::InstructionBase::getNumMicroOps () const inline
Definition at line 421 of file Instruction.h.
References llvm::mca::InstrDesc::NumMicroOps.
Referenced by llvm::mca::RetireControlUnit::dispatch(), llvm::mca::DispatchStage::DispatchStage(), llvm::mca::ExecuteStage::execute(), llvm::mca::ExecuteStage::isAvailable(), and llvm::mca::DispatchStage::isAvailable().
getNumUsers()
unsigned llvm::mca::InstructionBase::getNumUsers () const inline
Definition at line 428 of file Instruction.h.
References llvm::tgtok::Def.
getUses() [1/2]
SmallVectorImpl<ReadState>& llvm::mca::InstructionBase::getUses () inline
Definition at line 416 of file Instruction.h.
Referenced by llvm::mca::DispatchStage::DispatchStage().
getUses() [2/2]
const ArrayRef<ReadState> llvm::mca::InstructionBase::getUses () const inline
Definition at line 417 of file Instruction.h.
hasDependentUsers()
bool llvm::mca::InstructionBase::hasDependentUsers () const inline
Definition at line 423 of file Instruction.h.
References llvm::any_of(), llvm::tgtok::Def, and llvm::mca::WriteState::getNumUsers().
Referenced by llvm::mca::Scheduler::issueInstruction().
isMemOp()
bool llvm::mca::InstructionBase::isMemOp () const inline
Definition at line 438 of file Instruction.h.
References llvm::mca::InstrDesc::MayLoad, and llvm::mca::InstrDesc::MayStore.
Referenced by llvm::mca::Scheduler::analyzeDataDependencies(), llvm::mca::Scheduler::dispatch(), llvm::mca::Scheduler::isAvailable(), llvm::mca::Scheduler::issueInstruction(), and llvm::mca::LSUnit::onInstructionExecuted().
isOptimizableMove()
bool llvm::mca::InstructionBase::isOptimizableMove () const inline
Definition at line 436 of file Instruction.h.
Referenced by llvm::mca::DispatchStage::DispatchStage().
setOptimizableMove()
void llvm::mca::InstructionBase::setOptimizableMove () inline
Definition at line 437 of file Instruction.h.
The documentation for this class was generated from the following file:
include/llvm/MCA/Instruction.h