LLVM: llvm::SMFixIt Class Reference
llvm::SMFixIt Class Reference
Represents a single fixit, a replacement of one range of text with another.
#include "llvm/Support/SourceMgr.h"
Public Member Functions
SMFixIt (SMLoc Loc, const Twine &Insertion)
SMFixIt (SMRange R, const Twine &Replacement)
StringRef getText () const
SMRange getRange () const
bool operator< (const SMFixIt &Other) const
Detailed Description
Represents a single fixit, a replacement of one range of text with another.
Definition at line 229 of file SourceMgr.h.
Constructor & Destructor Documentation
SMFixIt() [1/2]
llvm::SMFixIt::SMFixIt (SMLoc Loc, const Twine & Insertion) inline
Definition at line 236 of file SourceMgr.h.
References assert(), and llvm::SMLoc::isValid().
SMFixIt() [2/2]
llvm::SMFixIt::SMFixIt (SMRange R, const Twine & Replacement) inline
Definition at line 242 of file SourceMgr.h.
References assert(), and llvm::SMRange::isValid().
Member Function Documentation
getRange()
SMRange llvm::SMFixIt::getRange () const inline
Definition at line 248 of file SourceMgr.h.
getText()
StringRef llvm::SMFixIt::getText () const inline
Definition at line 247 of file SourceMgr.h.
operator<()
bool llvm::SMFixIt::operator< (const SMFixIt & Other) const inline
Definition at line 250 of file SourceMgr.h.
References llvm::SMRange::End, llvm::SMLoc::getPointer(), and llvm::SMRange::Start.
The documentation for this class was generated from the following file:
include/llvm/Support/SourceMgr.h