LLVM: llvm::XCoreInstPrinter Class Reference
llvm::XCoreInstPrinter Class Reference
#include "Target/XCore/MCTargetDesc/XCoreInstPrinter.h"
Public Member Functions
XCoreInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 23 of file XCoreInstPrinter.h.
Constructor & Destructor Documentation
XCoreInstPrinter()
llvm::XCoreInstPrinter::XCoreInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 25 of file XCoreInstPrinter.h.
References llvm::Address, getRegisterName(), MI, llvm::RISCVFenceField::O, printInst(), printInstruction(), and printRegName().
Member Function Documentation
getRegisterName()
static const char* llvm::XCoreInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by printRegName(), and XCoreInstPrinter().
printInst()
void XCoreInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 33 of file XCoreInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, llvm::MCInstPrinter::printAnnotation(), printInstruction(), and llvm::report_fatal_error().
Referenced by XCoreInstPrinter().
printInstruction()
void llvm::XCoreInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by printInst(), and XCoreInstPrinter().
printRegName()
void XCoreInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 29 of file XCoreInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
Referenced by printExpr(), and XCoreInstPrinter().
The documentation for this class was generated from the following files:
lib/Target/XCore/MCTargetDesc/XCoreInstPrinter.h
lib/Target/XCore/MCTargetDesc/XCoreInstPrinter.cpp