LLVM: llvm::DbgValueLoc Class Reference
llvm::DbgValueLoc Class Reference
A single location or constant.
#include "CodeGen/AsmPrinter/DebugLocEntry.h"
Public Member Functions
DbgValueLoc (const DIExpression *Expr, int64_t i)
DbgValueLoc (const DIExpression *Expr, const ConstantFP *CFP)
DbgValueLoc (const DIExpression *Expr, const ConstantInt *CIP)
DbgValueLoc (const DIExpression *Expr, MachineLocation Loc)
DbgValueLoc (const DIExpression *Expr, TargetIndexLocation Loc)
bool isLocation () const
bool isTargetIndexLocation () const
bool isInt () const
bool isConstantFP () const
bool isConstantInt () const
int64_t getInt () const
const ConstantFP * getConstantFP () const
const ConstantInt * getConstantInt () const
MachineLocation getLoc () const
TargetIndexLocation getTargetIndexLocation () const
bool isFragment () const
bool isEntryVal () const
const DIExpression * getExpression () const
LLVM_DUMP_METHOD void dump () const
Friends
bool operator== (const DbgValueLoc &, const DbgValueLoc &)
Compare two DbgValueLocs for equality.
bool operator< (const DbgValueLoc &, const DbgValueLoc &)
Compare two fragments based on their offset.
Detailed Description
A single location or constant.
Definition at line 38 of file DebugLocEntry.h.
Constructor & Destructor Documentation
DbgValueLoc() [1/5]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, int64_t i) inline
Definition at line 67 of file DebugLocEntry.h.
DbgValueLoc() [2/5]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, const ConstantFP * CFP) inline
Definition at line 71 of file DebugLocEntry.h.
DbgValueLoc() [3/5]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, const ConstantInt * CIP) inline
Definition at line 75 of file DebugLocEntry.h.
DbgValueLoc() [4/5]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, MachineLocation Loc) inline
Definition at line 79 of file DebugLocEntry.h.
References assert().
DbgValueLoc() [5/5]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, TargetIndexLocation Loc) inline
Definition at line 83 of file DebugLocEntry.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void llvm::DbgValueLoc::dump () const inline
Definition at line 104 of file DebugLocEntry.h.
References llvm::dbgs(), llvm::Metadata::dump(), and llvm::Value::dump().
getConstantFP()
const ConstantFP* llvm::DbgValueLoc::getConstantFP () const inline
Definition at line 94 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
getConstantInt()
const ConstantInt* llvm::DbgValueLoc::getConstantInt () const inline
Definition at line 95 of file DebugLocEntry.h.
getExpression()
const DIExpression* llvm::DbgValueLoc::getExpression () const inline
Definition at line 100 of file DebugLocEntry.h.
References llvm::operator<(), and llvm::TargetIndexLocation::operator==().
Referenced by llvm::DwarfDebug::emitDebugLocValue(), llvm::DbgVariable::initializeDbgValue(), llvm::operator<(), and llvm::DebugLocEntry::sortUniqueValues().
getInt()
int64_t llvm::DbgValueLoc::getInt () const inline
Definition at line 93 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
getLoc()
MachineLocation llvm::DbgValueLoc::getLoc () const inline
Definition at line 96 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
getTargetIndexLocation()
TargetIndexLocation llvm::DbgValueLoc::getTargetIndexLocation () const inline
Definition at line 97 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
isConstantFP()
bool llvm::DbgValueLoc::isConstantFP () const inline
Definition at line 91 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
isConstantInt()
bool llvm::DbgValueLoc::isConstantInt () const inline
Definition at line 92 of file DebugLocEntry.h.
isEntryVal()
bool llvm::DbgValueLoc::isEntryVal () const inline
Definition at line 99 of file DebugLocEntry.h.
isFragment()
bool llvm::DbgValueLoc::isFragment () const inline
Definition at line 98 of file DebugLocEntry.h.
Referenced by llvm::DebugLocEntry::addValues().
isInt()
bool llvm::DbgValueLoc::isInt () const inline
Definition at line 90 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
isLocation()
bool llvm::DbgValueLoc::isLocation () const inline
Definition at line 86 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
isTargetIndexLocation()
bool llvm::DbgValueLoc::isTargetIndexLocation () const inline
Definition at line 87 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
Friends And Related Function Documentation
operator<
bool operator< (const DbgValueLoc & A, const DbgValueLoc & B) friend
Compare two fragments based on their offset.
Definition at line 208 of file DebugLocEntry.h.
operator==
bool operator== (const DbgValueLoc & A, const DbgValueLoc & B) friend
Compare two DbgValueLocs for equality.
Definition at line 184 of file DebugLocEntry.h.
Member Data Documentation
CFP
const ConstantFP* llvm::DbgValueLoc::CFP
Definition at line 55 of file DebugLocEntry.h.
Referenced by llvm::operator==().
CIP
const ConstantInt* llvm::DbgValueLoc::CIP
Definition at line 56 of file DebugLocEntry.h.
Referenced by llvm::operator==().
Int
int64_t llvm::DbgValueLoc::Int
Definition at line 54 of file DebugLocEntry.h.
Referenced by llvm::operator==().
Loc
MachineLocation llvm::DbgValueLoc::Loc
Or a location in the machine frame.
Definition at line 61 of file DebugLocEntry.h.
Referenced by llvm::operator==().
TIL
TargetIndexLocation llvm::DbgValueLoc::TIL
Or a location from target specific location.
Definition at line 63 of file DebugLocEntry.h.
Referenced by llvm::operator==().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/DebugLocEntry.h