LLVM: llvm::ArrayRef< T > Class Template Reference
llvm::ArrayRef< T > Class Template Reference
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
#include "llvm/ADT/APInt.h"
Inherited by llvm::MutableArrayRef< T >, and llvm::MutableArrayRef< BitWord >.
Public Types
using iterator = const T *
using const_iterator = const T *
using size_type = size_t
using reverse_iterator = std::reverse_iterator< iterator >
Public Member Functions
Constructors
ArrayRef ()=default
Construct an empty ArrayRef.
ArrayRef (NoneType)
Construct an empty ArrayRef from None.
ArrayRef (const T &OneElt)
Construct an ArrayRef from a single element.
ArrayRef (const T *data, size_t length)
Construct an ArrayRef from a pointer and length.
ArrayRef (const T *begin, const T *end)
Construct an ArrayRef from a range.
template<typename U >
ArrayRef (const SmallVectorTemplateCommon< T, U > &Vec)
Construct an ArrayRef from a SmallVector.
template<typename A >
ArrayRef (const std::vector< T, A > &Vec)
Construct an ArrayRef from a std::vector.
template<size_t N>
constexpr ArrayRef (const std::array< T, N > &Arr)
Construct an ArrayRef from a std::array.
template<size_t N>
constexpr ArrayRef (const T(&Arr)[N])
Construct an ArrayRef from a C array.
ArrayRef (const std::initializer_list< T > &Vec)
Construct an ArrayRef from a std::initializer_list.
template<typename U >
ArrayRef (const ArrayRef< U *> &A, typename std::enable_if< std::is_convertible< U *const *, T const *>::value >::type *=nullptr)
Construct an ArrayRef<const T*> from ArrayRef<T*>.
template<typename U , typename DummyT >
ArrayRef (const SmallVectorTemplateCommon< U *, DummyT > &Vec, typename std::enable_if< std::is_convertible< U *const *, T const *>::value >::type *=nullptr)
Construct an ArrayRef<const T*> from a SmallVector<T*>.
template<typename U , typename A >
ArrayRef (const std::vector< U *, A > &Vec, typename std::enable_if< std::is_convertible< U *const *, T const *>::value >::type *=0)
Construct an ArrayRef<const T*> from std::vector<T*>.
Simple Operations
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
empty - Check if the array is empty.
const T * data () const
size_t size () const
size - Get the array size.
const T & front () const
front - Get the first element.
const T & back () const
back - Get the last element.
template<typename Allocator >
ArrayRef< T > copy (Allocator &A)
bool equals (ArrayRef RHS) const
equals - Check for element-wise equality.
ArrayRef< T > slice (size_t N, size_t M) const
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
ArrayRef< T > slice (size_t N) const
slice(n) - Chop off the first N elements of the array.
ArrayRef< T > drop_front (size_t N=1) const
Drop the first N elements of the array.
ArrayRef< T > drop_back (size_t N=1) const
Drop the last N elements of the array.
template<class PredicateT >
ArrayRef< T > drop_while (PredicateT Pred) const
Return a copy of *this with the first N elements satisfying the given predicate removed.
template<class PredicateT >
ArrayRef< T > drop_until (PredicateT Pred) const
Return a copy of *this with the first N elements not satisfying the given predicate removed.
ArrayRef< T > take_front (size_t N=1) const
Return a copy of *this with only the first N elements.
ArrayRef< T > take_back (size_t N=1) const
Return a copy of *this with only the last N elements.
template<class PredicateT >
ArrayRef< T > take_while (PredicateT Pred) const
Return the first N elements of this Array that satisfy the given predicate.
template<class PredicateT >
ArrayRef< T > take_until (PredicateT Pred) const
Return the first N elements of this Array that don't satisfy the given predicate.
Operator Overloads
const T & operator[] (size_t Index) const
template<typename U >
std::enable_if< std::is_same< U, T >::value, ArrayRef< T > >::type & operator= (U &&Temporary)=delete
Disallow accidental assignment from a temporary.
template<typename U >
std::enable_if< std::is_same< U, T >::value, ArrayRef< T > >::type & operator= (std::initializer_list< U >)=delete
Disallow accidental assignment from a temporary.
Expensive Operations
std::vector< T > vec () const
Conversion operators
operator std::vector< T > () const
Detailed Description
template<typename T>
class llvm::ArrayRef< T >
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
a start pointer and a length. It allows various APIs to take consecutive elements easily and conveniently.
This class does not own the underlying data, it is expected to be used in situations where the data resides in some other buffer, whose lifetime extends past that of the ArrayRef. For this reason, it is not in general safe to store an ArrayRef.
This is intended to be trivially copyable, so it should be passed by value.
Definition at line 32 of file APInt.h.
Member Typedef Documentation
const_iterator
template<typename T> using llvm::ArrayRef< T >::const_iterator = const T *
Definition at line 44 of file ArrayRef.h.
iterator
template<typename T> using llvm::ArrayRef< T >::iterator = const T *
Definition at line 43 of file ArrayRef.h.
reverse_iterator
template<typename T> using llvm::ArrayRef< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 46 of file ArrayRef.h.
size_type
template<typename T> using llvm::ArrayRef< T >::size_type = size_t
Definition at line 45 of file ArrayRef.h.
Constructor & Destructor Documentation
ArrayRef() [1/13]
template<typename T> llvm::ArrayRef< T >::ArrayRef () default
Construct an empty ArrayRef.
ArrayRef() [2/13]
template<typename T> llvm::ArrayRef< T >::ArrayRef (NoneType) inline
Construct an empty ArrayRef from None.
Definition at line 63 of file ArrayRef.h.
ArrayRef() [3/13]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T & OneElt) inline
Construct an ArrayRef from a single element.
Definition at line 66 of file ArrayRef.h.
ArrayRef() [4/13]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T * data, size_t length) inline
Construct an ArrayRef from a pointer and length.
Definition at line 70 of file ArrayRef.h.
ArrayRef() [5/13]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T * begin, const T * end) inline
Construct an ArrayRef from a range.
Definition at line 74 of file ArrayRef.h.
ArrayRef() [6/13]
template<typename T> template<typename U > llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< T, U > & Vec) inline
Construct an ArrayRef from a SmallVector.
This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 81 of file ArrayRef.h.
ArrayRef() [7/13]
template<typename T> template<typename A > llvm::ArrayRef< T >::ArrayRef (const std::vector< T, A > & Vec) inline
Construct an ArrayRef from a std::vector.
Definition at line 87 of file ArrayRef.h.
ArrayRef() [8/13]
template<typename T> template<size_t N> constexpr llvm::ArrayRef< T >::ArrayRef (const std::array< T, N > & Arr) inline
Construct an ArrayRef from a std::array.
Definition at line 92 of file ArrayRef.h.
ArrayRef() [9/13]
template<typename T> template<size_t N> constexpr llvm::ArrayRef< T >::ArrayRef (const T(&) Arr[N]) inline
Construct an ArrayRef from a C array.
Definition at line 97 of file ArrayRef.h.
ArrayRef() [10/13]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const std::initializer_list< T > & Vec) inline
Construct an ArrayRef from a std::initializer_list.
Definition at line 107 of file ArrayRef.h.
ArrayRef() [11/13]
template<typename T> template<typename U > llvm::ArrayRef< T >::ArrayRef (const ArrayRef< U *> & A, typename std::enable_if< std::is_convertible< U *const *, T const *>::value >::type * = nullptr) inline
Construct an ArrayRef<const T*> from ArrayRef<T*>.
This uses SFINAE to ensure that only ArrayRefs of pointers can be converted.
Definition at line 117 of file ArrayRef.h.
ArrayRef() [12/13]
template<typename T> template<typename U , typename DummyT > llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< U *, DummyT > & Vec, typename std::enable_if< std::is_convertible< U *const *, T const *>::value >::type * = nullptr) inline
Construct an ArrayRef<const T*> from a SmallVector<T*>.
This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 127 of file ArrayRef.h.
ArrayRef() [13/13]
template<typename T> template<typename U , typename A > llvm::ArrayRef< T >::ArrayRef (const std::vector< U *, A > & Vec, typename std::enable_if< std::is_convertible< U *const *, T const *>::value >::type * = 0) inline
Construct an ArrayRef<const T*> from std::vector<T*>.
This uses SFINAE to ensure that only vectors of pointers can be converted.
Definition at line 137 of file ArrayRef.h.
Member Function Documentation
back()
template<typename T> const T& llvm::ArrayRef< T >::back () const inline
back - Get the last element.
Definition at line 167 of file ArrayRef.h.
Referenced by llvm::AttributeList::addParamAttribute(), llvm::DIExpression::appendToStack(), llvm::ConstantFoldLoadFromConstPtr(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::AttributeList::get(), llvm::Record::getDirectSuperClasses(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), llvm::isAllocaPromotable(), isIdentifierChar(), isImplicitOperandIn(), isSwitchDense(), llvm::RandomIRBuilder::newSink(), llvm::SLPVectorizerPass::runImpl(), and SimplifyGEPInst().
begin()
template<typename T> iterator llvm::ArrayRef< T >::begin () const inline
Definition at line 146 of file ArrayRef.h.
Referenced by llvm::lto::LTO::add(), llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), llvm::AArch64FunctionInfo::addLOHDirective(), llvm::AttributeList::addParamAttribute(), llvm::SpillPlacement::addPrefSpill(), llvm::DebugLocEntry::addValues(), llvm::TargetLibraryInfoImpl::addVectorizableFunctions(), alwaysAvailable(), AnyAliasLiveIn(), llvm::DIExpression::append(), llvm::DIExpression::appendToStack(), llvm::mca::SourceMgr::begin(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildBuildVectorTrunc(), llvm::MachineIRBuilder::buildConcatVectors(), buildFixItLine(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildSequence(), BuildSubAggregate(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MDNodeOpsKey::calculateHash(), llvm::Interpreter::callFunction(), canWidenShuffleElements(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::UnOpInit::clone(), cloneConstantExprWithNewAddressSpace(), llvm::collectPGOFuncNameStrings(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::MDNodeOpsKey::compareOps(), llvm::ComputeLinearIndex(), llvm::concatenateVectors(), llvm::ConstantFoldGetElementPtr(), llvm::object::convertUTF16LEToUTF8String(), llvm::convertUTF16ToUTF8String(), llvm::GlobalObject::copyMetadata(), llvm::DIBuilder::createExpression(), CreateGCRelocates(), llvm::createLibcall(), llvm::DeleteDeadBlocks(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::MCDwarfFrameEmitter::Emit(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::equals(), llvm::AccelTableBase::finalize(), llvm::FindInsertedValue(), findMatchingInlineAsmOperand(), llvm::ScalarEvolution::forgetValue(), llvm::gep_type_begin(), llvm::AttributeSetNode::get(), llvm::RecordRecTy::get(), llvm::AttributeList::get(), llvm::ConstantArray::get(), llvm::BitsInit::get(), llvm::ListInit::get(), llvm::CondOpInit::get(), llvm::VarDefInit::get(), llvm::DagInit::get(), llvm::ScalarEvolution::getAddExpr(), llvm::gsym::GsymReader::getAddressOffsetIndex(), llvm::SelectionDAG::getCommutedVectorShuffle(), getFauxShuffleMask(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::ConstantAggrKeyType< ConstantClass >::getHash(), llvm::ConstantExprKeyType::getHash(), llvm::MDNodeKeyImpl< DIExpression >::getHashValue(), llvm::InvokeInst::getLandingPadInst(), llvm::SelectionDAG::getNode(), getNoopInput(), getNumAllocatableRegsForConstraints(), getOffsetFromIndices(), llvm::Attributor::ArgumentReplacementInfo::getReplacementTypes(), getShuffleComment(), getStatepointArgs(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::SelectionDAG::getVectorShuffle(), llvm::ConstantExpr::getWithOperands(), llvm::hash_value(), initialize(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), llvm::sroa::AllocaSlices::insert(), is128BitUnpackShuffleMask(), llvm::isAllocaPromotable(), llvm::ShuffleVectorInst::isConcat(), llvm::MCSubtargetInfo::isCPUStringValid(), llvm::slpvectorizer::BoUpSLP::isDeleted(), isHorizontalBinOp(), llvm::LiveRange::isLiveAtIndexes(), isSortedByValueNo(), llvm::LiveRange::isUndefIn(), lle_X_fprintf(), lle_X_printf(), LLVMRemarkEntryGetFirstArg(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), lowerShuffleAsBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleOfExtractsAsVperm(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), LowerVECTOR_SHUFFLEv8i8(), llvm::lto::LTO::LTO(), llvm::object::MachOBindEntry::MachOBindEntry(), llvm::object::MachORebaseEntry::MachORebaseEntry(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), matchBinaryPermuteShuffle(), matchShuffleAsInsertPS(), llvm::object::ExportEntry::moveNext(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), NarrowVector(), llvm::object::ExportEntry::nodeOffset(), llvm::OwningArrayRef< T >::OwningArrayRef(), llvm::opt::OptTable::ParseArgs(), parseWholeProgramDevirtResolutionByArg(), ProfileCondOpInit(), ProfileDagInit(), propagateMetadata(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readFixedString(), readWideAPInt(), replaceShuffleOfInsert(), llvm::SLPVectorizerPass::runImpl(), llvm::MachineFunction::setCallSiteLandingPad(), setCoroInfo(), llvm::MachineInstr::setPhysRegsDeadExcept(), llvm::gsym::GsymCreator::setUUID(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyShuffleOfShuffle(), llvm::TGLexer::TGLexer(), llvm::toStringRef(), tryToVectorizeHorReductionOrInstOperands(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), llvm::codeview::VFTableRecord::VFTableRecord(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), wrapConstantAsMetadata(), and writeToResolutionFile().
copy()
template<typename T> template<typename Allocator > ArrayRef<T> llvm::ArrayRef< T >::copy (Allocator & A) inline
Definition at line 173 of file ArrayRef.h.
Referenced by llvm::StructType::setBody().
data()
template<typename T> const T* llvm::ArrayRef< T >::data () const inline
Definition at line 155 of file ArrayRef.h.
Referenced by adjustDuplex(), analyzeHeader(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadFromConstPtr(), llvm::convertUTF16ToUTF8String(), llvm::crc32(), llvm::DWARFFormValue::createFromBlockValue(), llvm::MutableArrayRef< BitWord >::data(), decodeCRBitMOperand(), decodeRVCInstrRdRs1Rs2(), llvm::codeview::TypeDeserializer::deserializeAs(), llvm::codeview::discoverTypeIndices(), discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), dumpLocation(), llvm::object::ELFFile< ELFT >::dynamicEntries(), eatBytes(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::symbolize::LLVMSymbolizer::flush(), llvm::codeview::forEachCodeViewRecord(), llvm::ConstantDataVector::get(), llvm::gsym::GsymReader::getAddrOffsets(), llvm::codeview::getBytesAsCharacters(), llvm::lto::InputFile::getComdatTable(), getCStringLength(), getDecoderTable(), getDigit(), getEncodedIntegerLength(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantExpr::getGetElementPtr(), llvm::DenseMapInfo< ArrayRef< T > >::getHashValue(), llvm::object::COFFObjectFile::getHintName(), llvm::msf::MappedBlockStream::getLength(), llvm::SimpleBitstreamCursor::getPointerToByte(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::getSectionName(), llvm::codeview::GloballyHashedType::GloballyHashedType(), llvm::MipsTargetLowering::HandleByVal(), handleFieldList(), handleMethodOverloadList(), handleOneMethod(), handlePointer(), llvm::codeview::AppendingTypeTableBuilder::insertRecordBytes(), llvm::codeview::GlobalTypeTableBuilder::insertRecordBytes(), llvm::DenseMapInfo< ArrayRef< T > >::isEqual(), llvm::codeview::CVRecord< TypeLeafKind >::kind(), llvm::Function::lookupIntrinsicID(), llvm::codeview::CodeViewRecordIO::mapGuid(), nextLEB(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::object::MachORebaseEntry::operator==(), llvm::object::MachOBindEntry::operator==(), llvm::ARMAttributeParser::Parse(), parseImmediate(), llvm::ScopedPrinter::printBinary(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readObject(), llvm::BinaryByteStream::str(), llvm::codeview::CVRecord< TypeLeafKind >::str_data(), llvm::MD5::update(), llvm::BinaryStreamWriter::writeArray(), writeArrayData(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::yaml::BinaryRef::writeAsHex(), llvm::MutableBinaryByteStream::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::gsym::FileWriter::writeData(), and llvm::xxHash64().
drop_back()
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::drop_back (size_t N = 1) const inline
Drop the last N elements of the array.
Definition at line 203 of file ArrayRef.h.
Referenced by llvm::DIExpression::appendToStack(), buildEpilogReload(), EltsFromConsecutiveLoads(), and llvm::Record::getDirectSuperClasses().
drop_front()
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::drop_front (size_t N = 1) const inline
Drop the first N elements of the array.
Definition at line 197 of file ArrayRef.h.
Referenced by llvm::codeview::CVRecord< TypeLeafKind >::content(), llvm::crc32(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), dwarfCCToCodeView(), llvm::opt::OptTable::findNearest(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::codeview::forEachCodeViewRecord(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), llvm::object::COFFObjectFile::getHintName(), llvm::msf::MappedBlockStream::getLength(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), handleBaseClass(), handleDataMember(), handleEnumerator(), handleFieldList(), handleMethodOverloadList(), handleNestedType(), handleOneMethod(), handleOverloadedMethod(), handlePointer(), handleStaticDataMember(), handleVirtualBaseClass(), llvm::codeview::GloballyHashedType::hashType(), llvm::HexagonTargetLowering::LowerBITCAST(), llvm::LegalizerHelper::narrowScalar(), llvm::codeview::BinaryAnnotationIterator::operator*(), llvm::object::MinidumpFile::MemoryInfoIterator::operator++(), packSplitRegsToOrigType(), resolveTypeIndexReferences(), llvm::msf::MSFBuilder::setStreamSize(), llvm::SHA1::update(), and writeWithCommas().
drop_until()
template<typename T> template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::drop_until (PredicateT Pred) const inline
Return a copy of *this with the first N elements not satisfying the given predicate removed.
Definition at line 216 of file ArrayRef.h.
drop_while()
template<typename T> template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::drop_while (PredicateT Pred) const inline
Return a copy of *this with the first N elements satisfying the given predicate removed.
Definition at line 210 of file ArrayRef.h.
empty()
template<typename T> bool llvm::ArrayRef< T >::empty () const inline
empty - Check if the array is empty.
Definition at line 153 of file ArrayRef.h.
Referenced by addData(), llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::DIExpression::append(), llvm::DIExpression::appendToStack(), llvm::CallLowering::ArgInfo::ArgInfo(), argsAreStructReturn(), llvm::AttributeListImpl::AttributeListImpl(), buildExtractionBlockSet(), buildFixItLine(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildSequence(), callIsStructReturn(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::collectPGOFuncNameStrings(), combineX86ShuffleChain(), llvm::MDNodeOpsKey::compareOps(), computeExcessPressureDelta(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertValueInstruction(), llvm::convertUTF16ToUTF8String(), llvm::StructType::create(), llvm::IRBuilder< TargetFolder >::CreateAnd(), CreateGCRelocates(), llvm::IRBuilder< TargetFolder >::CreateOr(), CriticalPathStep(), llvm::mca::RegisterFile::cycleStart(), llvm::AttributeListImpl::dump(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::WebAssemblyTargetAsmStreamer::emitLocal(), llvm::CodeViewContext::encodeInlineLineTable(), findCalledFunction(), llvm::FindInsertedValue(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::symbolize::LLVMSymbolizer::flush(), foldCONCAT_VECTORS(), llvm::codeview::forEachCodeViewRecord(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::AttributeSetNode::get(), llvm::RecordRecTy::get(), llvm::AttributeList::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::ListInit::get(), llvm::GCNTTIImpl::getArithmeticInstrCost(), getBuildDwordsVector(), getChainID(), llvm::Record::getDirectSuperClasses(), getExpressionFrameOffset(), getFeatures(), llvm::MCSchedModel::getForwardingDelayCycles(), getFPSequenceIfElementsMatch(), getGCDType(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), getIndexedTypeInternal(), getIntSequenceIfElementsMatch(), getOpenFileImpl(), llvm::getOrderedReduction(), getOrSelfReference(), getParentPad(), llvm::InstrProfReaderIndex< HashTableImpl >::getRecords(), GetRMWLibcall(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getScalarizationOverhead(), llvm::getShuffleReduction(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::Intrinsic::getType(), llvm::ConstantStruct::getTypeForElements(), llvm::DFAPacketizer::getUsedResources(), handleFieldList(), handleMethodOverloadList(), llvm::AttrBuilder::hasAttributes(), llvm::MipsInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::AArch64InstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), insertLifetimeMarkersSurroundingCall(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), insertUseHolderAfter(), llvm::xray::Profile::internPath(), isCoalescable(), llvm::ShuffleVectorInst::isConcat(), llvm::slpvectorizer::BoUpSLP::isDeleted(), isIFunc(), isImplicitOperandIn(), isInBoundsIndices(), IsInterestingCmp(), isReInterleaveMask(), isSingleSourceMaskImpl(), isSortedByValueNo(), llvm::coverage::LineCoverageStats::LineCoverageStats(), LLVMRemarkEntryGetFirstArg(), llvm::coverage::CoverageMapping::load(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::MipsCallLowering::lowerReturn(), lowerV8I16GeneralSingleInputShuffle(), llvm::GlobPattern::match(), llvm::fuzzerop::matchFirstType(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::codeview::BinaryAnnotationIterator::operator*(), llvm::raw_ostream::operator<<(), llvm::operator<<(), llvm::yaml::operator==(), llvm::PassBuilder::parsePassPipeline(), llvm::PrintMessage(), llvm::PromoteMemToReg(), pushDepHeight(), QualifiedNameOfImplicitName(), resolveTypeIndexReferences(), llvm::SIRegisterInfo::restoreSGPR(), llvm::lto::LTO::run(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), selectJumpTableArmEncoding(), llvm::StructType::setBody(), llvm::MachineInstr::setMemRefs(), llvm::SelectionDAG::setNodeMemRefs(), llvm::SIRegisterInfo::spillSGPR(), llvm::SplitBlockPredecessors(), llvm::splitCodeGen(), llvm::to_hexString(), llvm::CodeViewYAML::toCodeViewSubsectionList(), truncateToSize(), llvm::VPBlendRecipe::VPBlendRecipe(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::BinaryStreamWriter::writeArray(), llvm::MutableBinaryByteStream::writeBytes(), llvm::AppendingBinaryByteStream::writeBytes(), writeContent(), and writeWithCommas().
end()
template<typename T> iterator llvm::ArrayRef< T >::end () const inline
Definition at line 147 of file ArrayRef.h.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), llvm::AArch64FunctionInfo::addLOHDirective(), llvm::AttributeList::addParamAttribute(), llvm::SpillPlacement::addPrefSpill(), llvm::DebugLocEntry::addValues(), llvm::TargetLibraryInfoImpl::addVectorizableFunctions(), llvm::DIExpression::append(), llvm::DIExpression::appendToStack(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildBuildVectorTrunc(), llvm::MachineIRBuilder::buildConcatVectors(), buildFixItLine(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildSequence(), BuildSubAggregate(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MDNodeOpsKey::calculateHash(), llvm::Interpreter::callFunction(), canWidenShuffleElements(), llvm::LiveIntervals::checkRegMaskInterference(), cloneConstantExprWithNewAddressSpace(), llvm::collectPGOFuncNameStrings(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::MDNodeOpsKey::compareOps(), llvm::ComputeLinearIndex(), llvm::concatenateVectors(), llvm::ConstantFoldGetElementPtr(), llvm::ConvertCostTableLookup(), llvm::convertUTF16ToUTF8String(), llvm::CostTableLookup(), llvm::DIBuilder::createExpression(), CreateGCRelocates(), llvm::createLibcall(), llvm::DeleteDeadBlocks(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::MCDwarfFrameEmitter::Emit(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::mca::SourceMgr::end(), llvm::AccelTableBase::finalize(), Find(), llvm::FindInsertedValue(), findMatchingInlineAsmOperand(), llvm::ScalarEvolution::forgetValue(), llvm::gep_type_end(), llvm::AttributeSetNode::get(), llvm::RecordRecTy::get(), llvm::AttributeList::get(), llvm::ConstantArray::get(), llvm::BitsInit::get(), llvm::ListInit::get(), llvm::CondOpInit::get(), llvm::VarDefInit::get(), llvm::DagInit::get(), llvm::ScalarEvolution::getAddExpr(), llvm::SelectionDAG::getCommutedVectorShuffle(), getFauxShuffleMask(), llvm::getFMA3Group(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::ConstantAggrKeyType< ConstantClass >::getHash(), llvm::ConstantExprKeyType::getHash(), llvm::MDNodeKeyImpl< DIExpression >::getHashValue(), llvm::InvokeInst::getLandingPadInst(), llvm::SelectionDAG::getNode(), getNoopInput(), getNumAllocatableRegsForConstraints(), getOffsetFromIndices(), llvm::HexagonTargetLowering::getPreferredVectorAction(), getRegLanes(), llvm::Attributor::ArgumentReplacementInfo::getReplacementTypes(), getShuffleComment(), getStatepointArgs(), llvm::SelectionDAG::getVectorShuffle(), llvm::ConstantExpr::getWithOperands(), llvm::hash_value(), llvm::cl::HideUnrelatedOptions(), initialize(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), llvm::sroa::AllocaSlices::insert(), is128BitUnpackShuffleMask(), llvm::isAllocaPromotable(), llvm::ShuffleVectorInst::isConcat(), llvm::MCSubtargetInfo::isCPUStringValid(), llvm::slpvectorizer::BoUpSLP::isDeleted(), isEXTMask(), isHorizontalBinOp(), llvm::LiveRange::isLiveAtIndexes(), llvm::DataLayout::isNonIntegralAddressSpace(), isSortedByValueNo(), llvm::LiveRange::isUndefIn(), lle_X_fprintf(), lle_X_printf(), Lookup(), lookupFoldTableImpl(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), lowerShuffleAsBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleOfExtractsAsVperm(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), LowerVECTOR_SHUFFLEv8i8(), llvm::lto::LTO::LTO(), llvm::object::MachOBindEntry::MachOBindEntry(), llvm::object::MachORebaseEntry::MachORebaseEntry(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), matchBinaryPermuteShuffle(), matchShuffleAsInsertPS(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), llvm::coverage::FunctionRecordIterator::operator++(), llvm::OwningArrayRef< T >::OwningArrayRef(), llvm::opt::OptTable::ParseArgs(), performCustomAdjustments(), ProfileCondOpInit(), ProfileDagInit(), propagateMetadata(), replaceShuffleOfInsert(), llvm::SLPVectorizerPass::runImpl(), llvm::MachineFunction::setCallSiteLandingPad(), setCoroInfo(), llvm::MachineInstr::setPhysRegsDeadExcept(), llvm::gsym::GsymCreator::setUUID(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyShuffleOfShuffle(), llvm::TGLexer::TGLexer(), tryToVectorizeHorReductionOrInstOperands(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), llvm::codeview::VFTableRecord::VFTableRecord(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), wrapConstantAsMetadata(), and writeToResolutionFile().
equals()
template<typename T> bool llvm::ArrayRef< T >::equals (ArrayRef< T > RHS) const inline
equals - Check for element-wise equality.
Definition at line 180 of file ArrayRef.h.
Referenced by llvm::operator==().
front()
template<typename T> const T& llvm::ArrayRef< T >::front () const inline
front - Get the first element.
Definition at line 161 of file ArrayRef.h.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates(), canSinkInstructions(), DecodeFixedType(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::ConstantVector::get(), getChainID(), getNumAllocatableRegsForConstraints(), llvm::DFAPacketizer::getUsedResources(), handleFieldList(), llvm::slpvectorizer::BoUpSLP::isDeleted(), isSwitchDense(), llvm::coverage::LineCoverageStats::LineCoverageStats(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::codeview::BinaryAnnotationIterator::operator*(), llvm::PassBuilder::parsePassPipeline(), llvm::PrintMessage(), llvm::SLPVectorizerPass::runImpl(), and wrapConstantAsMetadata().
operator std::vector< T >()
template<typename T> llvm::ArrayRef< T >::operator std::vector< T > () const inline
Definition at line 280 of file ArrayRef.h.
operator=() [1/2]
template<typename T> template<typename U > std::enable_if<std::is_same<U, T>::value, ArrayRef<T> >::type& llvm::ArrayRef< T >::operator= (U && Temporary) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
Referenced by llvm::OwningArrayRef< T >::operator=().
operator=() [2/2]
template<typename T> template<typename U > std::enable_if<std::is_same<U, T>::value, ArrayRef<T> >::type& llvm::ArrayRef< T >::operator= (std::initializer_list< U >) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
operator[]()
template<typename T> const T& llvm::ArrayRef< T >::operator[] (size_t Index) const inline
Definition at line 249 of file ArrayRef.h.
rbegin()
template<typename T> reverse_iterator llvm::ArrayRef< T >::rbegin () const inline
Definition at line 149 of file ArrayRef.h.
Referenced by getNoopInput(), llvm::ScheduleDAGMI::initQueues(), and llvm::SLPVectorizerPass::runImpl().
rend()
template<typename T> reverse_iterator llvm::ArrayRef< T >::rend () const inline
Definition at line 150 of file ArrayRef.h.
Referenced by getNoopInput(), llvm::ScheduleDAGMI::initQueues(), and llvm::SLPVectorizerPass::runImpl().
size()
template<typename T> size_t llvm::ArrayRef< T >::size () const inline
size - Get the array size.
Definition at line 158 of file ArrayRef.h.
Referenced by AddCalls(), llvm::MachineFunction::addCatchTypeInfo(), addData(), llvm::pdb::DbiStreamBuilder::addDbgStream(), llvm::MachineFunction::addFilterTypeInfo(), llvm::InstCombineWorklist::AddInitialGroup(), addOperands(), llvm::gsym::GsymReader::addressForIndex(), llvm::msf::MSFBuilder::addStream(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::pdb::TpiStreamBuilder::addTypeRecord(), adjustDuplex(), adjustFixupValue(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateRegBlock(), allocateSGPR32InputImpl(), llvm::MachineFunction::allocateShuffleMask(), llvm::CCState::AllocateStack(), allocateVGPR32Input(), allSameBlock(), allSameType(), alwaysAvailable(), llvm::MipsInstrInfo::analyzeBranch(), analyzeHeader(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::AVRAsmBackend::applyFixup(), llvm::ARMAsmBackend::applyFixup(), llvm::RISCVAsmBackend::applyFixup(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates(), arrayDataSize(), llvm::MipsCallLowering::MipsHandler::assignVRegs(), llvm::SimpleBitstreamCursor::AtEndOfStream(), llvm::yaml::BinaryRef::binary_size(), buildClonedLoopBlocks(), buildClonedLoops(), buildEpilogReload(), llvm::coro::Shape::buildFrom(), llvm::ConstantFoldingMIRBuilder::buildInstr(), llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstr(), buildNew(), buildOrChain(), llvm::MachineIRBuilder::buildSequence(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::Interpreter::callFunction(), llvm::canConstantFoldCallTo(), canDecodeBlob(), canEvaluateShuffled(), llvm::AArch64InstrInfo::canInsertSelect(), llvm::SystemZInstrInfo::canInsertSelect(), llvm::X86InstrInfo::canInsertSelect(), canLowerByDroppingEvenElements(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canonicalizeShuffleMaskWithCommute(), llvm::SimpleBitstreamCursor::canSkipToPos(), canWidenShuffleElements(), CC_ARM_AAPCS_Custom_Aggregate(), CC_RISCV_FastCC(), CheckForLiveRegDefMasked(), llvm::CallInst::classof(), llvm::BitVector::clearBitsNotInMask(), llvm::UnOpInit::clone(), llvm::BinOpInit::clone(), llvm::TernOpInit::clone(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::FunctionComparator::cmpOperations(), llvm::object::coffnamecpy(), llvm::collectPGOFuncNameStrings(), combineConcatVectorOps(), combineShuffleOfSplatVal(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), llvm::sys::commandLineFitsWithinSystemLimits(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::MDNodeOpsKey::compareOps(), computeAddrMap(), llvm::ComputeEditDistance(), computeExcessPressureDelta(), llvm::SelectionDAG::computeKnownBits(), computeMaxPressureDelta(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::mca::computeProcResourceMasks(), computeZeroableShuffleElements(), llvm::concatenateVectors(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadFromConstPtr(), llvm::detail::IEEEFloat::convert(), llvm::TypedInit::convertInitializerBitRange(), llvm::BitsInit::convertInitializerBitRange(), llvm::IntInit::convertInitializerBitRange(), llvm::TypedInit::convertInitListSlice(), llvm::ListInit::convertInitListSlice(), llvm::detail::IEEEFloat::convertToInteger(), convertToString(), llvm::object::convertUTF16LEToUTF8String(), llvm::convertUTF16ToUTF8String(), llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::GlobalObject::copyMetadata(), llvm::SIInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), llvm::crc32(), llvm::GetElementPtrConstantExpr::Create(), llvm::ConstantAggrKeyType< ConstantClass >::create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), llvm::CleanupPadInst::Create(), llvm::CatchPadInst::Create(), llvm::IRBuilder< TargetFolder >::CreateAnd(), llvm::MDBuilder::createBranchWeights(), llvm::CallInst::CreateFree(), llvm::DWARFFormValue::createFromBlockValue(), CreateGCRelocates(), llvm::IRBuilder< TargetFolder >::CreateGEP(), llvm::IRBuilder< TargetFolder >::CreateInBoundsGEP(), createIndexMap(), llvm::IRBuilder< TargetFolder >::CreateNAryOp(), llvm::IRBuilder< TargetFolder >::CreateOr(), llvm::createPGOIndirectCallPromotionLegacyPass(), createPHIsForSplitLoopExit(), llvm::createSanitizerCtorAndInitFunctions(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAATypeNode(), CriticalPathStep(), decodeBDVAddr64Disp12Operand(), decodeCRBitMOperand(), DecodeIITType(), DecodeMoveHRegInstruction(), llvm::DecodePSHUFBMask(), DecodeRegisterClass(), decodeRVCInstrRdRs1Rs2(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::object::Decompressor::decompress(), llvm::DeleteDeadBlocks(), llvm::GCNIterativeScheduler::detachSchedule(), llvm::AttributeListImpl::dump(), llvm::AttributeSet::dump(), dumpLocation(), llvm::dumpRegSetPressure(), dwarfCCToCodeView(), eatBytes(), llvm::LiveRangeEdit::eliminateDeadDefs(), EltsFromConsecutiveLoads(), llvm::MCDwarfLineTableHeader::Emit(), llvm::BitstreamWriter::emitBlob(), encodeCnt(), evaluateInDifferentElementOrder(), llvm::BitstreamWriter::ExitBlock(), extractBitsForFixup(), llvm::FenceInst::FenceInst(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::AccelTableBase::finalize(), findFirstNonGlobal(), llvm::FindInsertedValue(), findLiveReferences(), llvm::wholeprogramdevirt::findLowestOffset(), findMatchingInlineAsmOperand(), findStrip(), llvm::symbolize::LLVMSymbolizer::flush(), FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::codeview::forEachCodeViewRecord(), llvm::ScalarEvolution::forgetValue(), llvm::codeview::detail::GuidAdapter::format(), llvm::CodeViewYAML::fromDebugH(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), genShuffleBland(), llvm::FunctionType::get(), llvm::AttributeList::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::BitsInit::get(), llvm::ListInit::get(), llvm::ConstantDataVector::get(), llvm::CondOpInit::get(), llvm::VarDefInit::get(), llvm::DagInit::get(), llvm::ScalarEvolution::getAddExpr(), llvm::gsym::GsymReader::getAddrOffsets(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::BitVector::getBitCapacity(), llvm::getBitcodeFileContents(), getBuildDwordsVector(), llvm::codeview::getBytesAsCharacters(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), getChainID(), llvm::irsymtab::Reader::getComdatTable(), getConstVector(), getDecoderTable(), llvm::irsymtab::Reader::getDependentLibraries(), getDigit(), llvm::DIExpression::getElement(), llvm::object::getExtendedSymbolTableIndex(), llvm::gsym::GsymReader::getFile(), llvm::CCState::getFirstUnallocated(), getFixupKindSize(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getGCDType(), llvm::TargetTransformInfoImplBase::getGEPCost(), llvm::ScalarEvolution::getGEPExpr(), llvm::ConstantExpr::getGetElementPtr(), getHalfShuffleMask(), llvm::object::COFFObjectFile::getHintName(), getIndexedTypeInternal(), llvm::AArch64Disassembler::getInstruction(), llvm::AMDGPUDisassembler::getInstruction(), llvm::HexagonTTIImpl::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getIntrinsicCost(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::InvokeInst::getLandingPadInst(), llvm::BinaryByteStream::getLength(), llvm::msf::MappedBlockStream::getLength(), llvm::IntegerType::getMask(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedScatter(), llvm::object::MinidumpFile::getMemoryInfoList(), llvm::BitVector::getMemorySize(), llvm::SelectionDAG::getMergeValues(), llvm::SourceMgr::GetMessage(), llvm::SelectionDAG::getNode(), getNoopInput(), getNumAllocatableRegsForConstraints(), llvm::DIExpression::getNumElements(), llvm::irsymtab::Reader::getNumModules(), llvm::opt::OptTable::getNumOptions(), getOffsetFromIndices(), llvm::ConstantExpr::getOpcodeName(), getOpenFileImpl(), llvm::DIBuilder::getOrCreateTypeArray(), getOrSelfReference(), llvm::AArch64TTIImpl::getPopcntSupport(), llvm::MachineTraceMetrics::Trace::getResourceDepth(), llvm::MachineTraceMetrics::Trace::getResourceLength(), GetRMWLibcall(), getSameOpcode(), llvm::object::WasmObjectFile::getSectionSize(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), getShuffleMaskIndexOfOneElementFromOp0IntoOp1(), getStatepointArgs(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::ConstantStruct::getTypeForElements(), llvm::RegPressureTracker::getUpwardPressureDelta(), getV4X86ShuffleImm(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), llvm::ConstantExpr::getWithOperands(), llvm::CodeViewYAML::GlobalHash::GlobalHash(), llvm::codeview::GloballyHashedType::GloballyHashedType(), group2Shuffle(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::MipsTargetLowering::HandleByVal(), hasIdenticalHalvesShuffleMask(), hasIdenticalMMOs(), llvm::mca::SourceMgr::hasNext(), llvm::hasUTF16ByteOrderMark(), hasUTF8ByteOrderMark(), inferDSOLocal(), llvm::MipsInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::codeview::MergingTypeTableBuilder::insertRecordAs(), llvm::codeview::AppendingTypeTableBuilder::insertRecordBytes(), llvm::codeview::GlobalTypeTableBuilder::insertRecordBytes(), llvm::AArch64InstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), instrumentMaskedLoadOrStore(), llvm::msf::MappedBlockStream::invalidateCache(), inversePermutation(), is128BitUnpackShuffleMask(), isACalleeSavedRegister(), isAddSubOrSubAddMask(), isBigEndian(), isCanonical(), llvm::SelectionDAG::isConstantFPBuildVectorOrConstantFP(), isDeInterleaveMask(), isDeInterleaveMaskOfFactor(), llvm::slpvectorizer::BoUpSLP::isDeleted(), llvm::X86TargetLowering::isDesirableToCombineBuildVectorToShuffleTruncate(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), isIdentifierChar(), isIdentity(), llvm::ShuffleVectorInst::isIdentityMask(), isIdentityMaskImpl(), isImplicitOperandIn(), isInBoundsIndices(), isINSMask(), IsInterestingCmp(), isLaneCrossingShuffleMask(), isLocalCopy(), isMips64EL(), isNonZeroElementsInOrder(), isNoopShuffleMask(), isPermutation(), isReInterleaveMask(), isRepeatedShuffleMask(), isRepeatedTargetShuffleMask(), llvm::ShuffleVectorInst::isReverseMask(), isReverseMask(), llvm::ShuffleVectorInst::isSelectMask(), isShuffle(), isShuffleEquivalent(), isShuffleMaskInputInPlace(), isSingleSHUFPSMask(), llvm::ShuffleVectorInst::isSingleSourceMask(), isSingleSourceMaskImpl(), isSortedByValueNo(), isSplat(), isSwiftError(), isSwitchDense(), isTargetShuffleEquivalent(), llvm::ShuffleVectorInst::isTransposeMask(), llvm::SelectionDAG::isUndef(), isUndefLowerHalf(), isUndefUpperHalf(), isValidEncoding(), isVectorPredicable(), isVMOVNMask(), isVTBLMask(), isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), llvm::ShuffleVectorInst::isZeroEltSplatMask(), llvm::codeview::CVRecord< TypeLeafKind >::kind(), llvm::BinaryItemTraits< codeview::CVSymbol >::length(), llvm::codeview::CVRecord< TypeLeafKind >::length(), llvm::codeview::limitSymbolArrayToScope(), llvm::coverage::LineCoverageStats::LineCoverageStats(), lle_X_atexit(), lle_X_fprintf(), lle_X_scanf(), lle_X_sscanf(), LLVMInitializeHexagonDisassembler(), llvm::coverage::CoverageMapping::load(), llvm::object::ResourceSectionRef::load(), lookupFunction(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), lower512BitShuffle(), llvm::HexagonTargetLowering::LowerBITCAST(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::X86CallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), llvm::LegalizerHelper::lowerShuffleVector(), lowerShuffleWithPSHUFB(), lowerShuffleWithVPMOV(), lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV64I8Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::orc::makeJITDylibSearchOrder(), llvm::TargetLowering::makeLibCall(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), match1BitShuffleAsKSHIFT(), matchBinaryPermuteShuffle(), llvm::Intrinsic::matchIntrinsicVarArg(), matchShuffleAsBlend(), matchShuffleAsEXTRQ(), matchShuffleAsInsertPS(), matchShuffleAsINSERTQ(), matchShuffleAsRotate(), matchShuffleAsShift(), matchShuffleAsVPMOV(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::SIInstrInfo::materializeImmediate(), llvm::object::MinidumpFile::MemoryInfoIterator::MemoryInfoIterator(), llvm::LegalizerHelper::moreElementsVector(), multikeySort(), narrowShuffle(), llvm::AllocationOrder::next(), nextByte(), nextLEB(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::object::MinidumpFile::MemoryInfoIterator::operator==(), llvm::ConstantAggrKeyType< ConstantClass >::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::CallLowering::packRegs(), llvm::ARMAttributeParser::Parse(), parseImmediate(), llvm::PerTargetMIParsingState::parseInstrName(), parseTypeIdSummaryRecord(), peek(), llvm::mca::SourceMgr::peekNext(), llvm::AsmLexer::peekTokens(), llvm::CallBase::populateBundleOperandInfos(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::ScopedPrinter::printBinary(), llvm::PrintMessage(), llvm::BitcodeAnalyzer::printStats(), processShaderInputArgs(), llvm::VarDefInit::Profile(), ProfileBitsInit(), ProfileCondOpInit(), ProfileListInit(), ProfileRecordRecTy(), ProfileVarDefInit(), propagateMetadata(), llvm::propagateMetadata(), pushDepHeight(), QualifiedNameOfImplicitName(), llvm::AppendingBinaryByteStream::readBytes(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readFixedString(), readInstruction16(), readInstruction32(), readInstruction64(), llvm::BinaryStreamReader::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::IndexedInstrProfReader::readNextRecord(), readWideAPInt(), rebuildLoopAfterUnswitch(), recomputeLiveInValues(), llvm::Attributor::registerFunctionSignatureRewrite(), relocationViaAlloca(), llvm::CatchSwitchInst::removeHandler(), llvm::MachineInstr::RemoveOperand(), replaceShuffleOfInsert(), llvm::SITargetLowering::requiresUniformRegister(), llvm::BitVector::resize(), llvm::SIRegisterInfo::restoreSGPR(), rotateSign(), llvm::orc::runAsMain(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::SLPVectorizerPass::runImpl(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::scaleShuffleMask(), selectJumpTableArmEncoding(), SelectPairHalf(), llvm::StructType::setBody(), llvm::SelectionDAG::setNodeMemRefs(), setSummary(), SimplifyExtractValueInst(), SimplifyGEPInst(), simplifyShuffleOfShuffle(), llvm::mca::SourceMgr::size(), llvm::yaml::SequenceTraits< ArrayRef< T > >::size(), llvm::SimpleBitstreamCursor::SizeInBytes(), llvm::SimpleBitstreamCursor::skipToEnd(), slotForIndex(), llvm::sortPtrAccesses(), speculatePHIs(), llvm::SIRegisterInfo::spillSGPR(), splitAndLowerShuffle(), llvm::SplitBlockPredecessors(), llvm::splitCodeGen(), llvm::SplitLandingPadPredecessors(), splitMask(), llvm::BinaryByteStream::str(), llvm::codeview::CVRecord< TypeLeafKind >::str_data(), StrengthenNoWrapFlags(), llvm::ARMBaseInstrInfo::SubsumesPredicate(), llvm::PPCInstrInfo::SubsumesPredicate(), llvm::orc::SymbolLookupSet::SymbolLookupSet(), llvm::to_hexString(), llvm::toStringRef(), unifyReturnBlockSet(), llvm::CallLowering::unpackRegs(), unpackRegsToOrigType(), unswitchNontrivialInvariants(), llvm::SHA1::update(), llvm::MD5::update(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::TypeDumpVisitor::visitUnknownType(), llvm::VPBlendRecipe::VPBlendRecipe(), llvm::object::WindowsResourceCOFFWriter::WindowsResourceCOFFWriter(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), wrapConstantAsMetadata(), llvm::coverage::CoverageFilenamesSectionWriter::write(), llvm::BinaryStreamWriter::writeArray(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::yaml::BinaryRef::writeAsHex(), llvm::BinaryStreamWriter::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::WritableBinaryStreamRef::writeBytes(), writeContent(), llvm::gsym::FileWriter::writeData(), llvm::codeview::ContinuationRecordBuilder::writeMemberType(), writeWithCommas(), llvm::xxHash64(), and llvm::LiveDebugVariables::~LiveDebugVariables().
slice() [1/2]
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::slice (size_t N, size_t M) const inline
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
Definition at line 188 of file ArrayRef.h.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), buildEpilogReload(), buildNew(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantExprKeyType::create(), DecodeFixedType(), llvm::dlltoolDriverMain(), eatBytes(), llvm::BitstreamWriter::ExitBlock(), llvm::FindInsertedValue(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::ConstantExpr::getAsInstruction(), llvm::AMDGPUDisassembler::getInstruction(), llvm::object::MinidumpFile::getMemoryInfoList(), llvm::object::MinidumpFile::getRawStream(), llvm::ConstantExpr::getWithOperands(), llvm::codeview::GloballyHashedType::hashType(), isSortedByValueNo(), isUndefInRange(), isUndefOrZeroInRange(), LLVMInitializeHexagonDisassembler(), LowerAVXCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), lowerShuffleAsByteShiftMask(), llvm::GlobPattern::match(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), matchShuffleAsVPMOV(), partitionShuffleOfConcats(), propagateMetadata(), llvm::BinaryByteStream::readBytes(), llvm::msf::MappedBlockStream::readBytes(), llvm::BinaryByteStream::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::Interpreter::runFunction(), llvm::SLPVectorizerPass::runImpl(), SimplifyExtractValueInst(), SimplifyGEPInst(), and splitAndLowerShuffle().
slice() [2/2]
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::slice (size_t N) const inline
slice(n) - Chop off the first N elements of the array.
Definition at line 194 of file ArrayRef.h.
Referenced by llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::slice().
take_back()
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::take_back (size_t N = 1) const inline
Return a copy of *this with only the last N elements.
Definition at line 228 of file ArrayRef.h.
Referenced by optimizeVectorResizeWithIntegerBitCasts().
take_front()
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::take_front (size_t N = 1) const inline
Return a copy of *this with only the first N elements.
Definition at line 221 of file ArrayRef.h.
Referenced by llvm::crc32(), llvm::codeview::forEachCodeViewRecord(), llvm::AttributeList::get(), llvm::codeview::GloballyHashedType::hashType(), llvm::HexagonTargetLowering::LowerBITCAST(), optimizeVectorResizeWithIntegerBitCasts(), packSplitRegsToOrigType(), llvm::BinaryItemStream< T, Traits >::readBytes(), and writeWithCommas().
take_until()
template<typename T> template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::take_until (PredicateT Pred) const inline
Return the first N elements of this Array that don't satisfy the given predicate.
Definition at line 242 of file ArrayRef.h.
take_while()
template<typename T> template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::take_while (PredicateT Pred) const inline
Return the first N elements of this Array that satisfy the given predicate.
Definition at line 236 of file ArrayRef.h.
vec()
template<typename T> std::vector<T> llvm::ArrayRef< T >::vec () const inline
Definition at line 273 of file ArrayRef.h.
The documentation for this class was generated from the following files:
include/llvm/ADT/APInt.h
include/llvm/ADT/ArrayRef.h