LLVM: llvm::PPCTargetStreamer Class Reference
llvm::PPCTargetStreamer Class Reference abstract
#include "Target/PowerPC/PPCTargetStreamer.h"
Public Member Functions
PPCTargetStreamer (MCStreamer &S)
~PPCTargetStreamer () override
virtual void emitTCEntry (const MCSymbol &S)=0
virtual void emitMachine (StringRef CPU)=0
virtual void emitAbiVersion (int AbiVersion)=0
virtual void emitLocalEntry (MCSymbolELF *S, const MCExpr *LocalOffset)=0
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 21 of file PPCTargetStreamer.h.
Constructor & Destructor Documentation
PPCTargetStreamer()
PPCTargetStreamer::PPCTargetStreamer (MCStreamer & S)
Definition at line 52 of file PPCMCTargetDesc.cpp.
References ~PPCTargetStreamer().
Referenced by createPPCMCAsmInfo().
~PPCTargetStreamer()
PPCTargetStreamer::~PPCTargetStreamer () override default
Referenced by PPCTargetStreamer().
Member Function Documentation
emitAbiVersion()
virtual void llvm::PPCTargetStreamer::emitAbiVersion (int AbiVersion) pure virtual
Referenced by addNegOperand(), and createPPCMCAsmInfo().
emitLocalEntry()
virtual void llvm::PPCTargetStreamer::emitLocalEntry (MCSymbolELF * S, const MCExpr * LocalOffset) pure virtual
Referenced by addNegOperand(), and createPPCMCAsmInfo().
emitMachine()
virtual void llvm::PPCTargetStreamer::emitMachine (StringRef CPU) pure virtual
Referenced by addNegOperand(), and createPPCMCAsmInfo().
emitTCEntry()
virtual void llvm::PPCTargetStreamer::emitTCEntry (const MCSymbol & S) pure virtual
Referenced by createPPCMCAsmInfo().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCTargetStreamer.h
lib/Target/PowerPC/MCTargetDesc/PPCMCTargetDesc.cpp