LLVM: llvm::BasicBlock Class Reference
llvm::BasicBlock Class Reference final
LLVM Basic Block Representation.
#include "llvm/IR/BasicBlock.h"
Classes
class phi_iterator_impl
Iterator to walk just the phi nodes in the basic block.
Public Types
using InstListType = SymbolTableList< Instruction >
using iterator = InstListType::iterator
Instruction iterators...
using const_iterator = InstListType::const_iterator
using reverse_iterator = InstListType::reverse_iterator
using const_reverse_iterator = InstListType::const_reverse_iterator
using phi_iterator = phi_iterator_impl<>
using const_phi_iterator = phi_iterator_impl< const PHINode, BasicBlock::const_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
BasicBlock (const BasicBlock &)=delete
BasicBlock & operator= (const BasicBlock &)=delete
~BasicBlock ()
LLVMContext & getContext () const
Get the context in which this basic block lives.
const Function * getParent () const
Return the enclosing method, or null if none.
Function * getParent ()
const Module * getModule () const
Return the module owning the function this basic block belongs to, or nullptr if the function does not have a module.
Module * getModule ()
const Instruction * getTerminator () const LLVM_READONLY
Returns the terminator instruction if the block is well formed or null if the block is not well formed.
Instruction * getTerminator ()
const CallInst * getTerminatingDeoptimizeCall () const
Returns the call instruction calling @llvm.experimental.deoptimize prior to the terminating return instruction of this basic block, if such a call is present.
CallInst * getTerminatingDeoptimizeCall ()
const CallInst * getTerminatingMustTailCall () const
Returns the call instruction marked 'musttail' prior to the terminating return instruction of this basic block, if such a call is present.
CallInst * getTerminatingMustTailCall ()
const Instruction * getFirstNonPHI () const
Returns a pointer to the first instruction in this block that is not a PHINode instruction.
Instruction * getFirstNonPHI ()
const Instruction * getFirstNonPHIOrDbg () const
Returns a pointer to the first instruction in this block that is not a PHINode or a debug intrinsic.
Instruction * getFirstNonPHIOrDbg ()
const Instruction * getFirstNonPHIOrDbgOrLifetime () const
Returns a pointer to the first instruction in this block that is not a PHINode, a debug intrinsic, or a lifetime intrinsic.
Instruction * getFirstNonPHIOrDbgOrLifetime ()
const_iterator getFirstInsertionPt () const
Returns an iterator to the first instruction in this block that is suitable for inserting a non-PHI instruction.
iterator getFirstInsertionPt ()
iterator_range< filter_iterator< BasicBlock::const_iterator, std::function< bool(const Instruction &)> > > instructionsWithoutDebug () const
Return a const iterator range over the instructions in the block, skipping any debug instructions.
iterator_range< filter_iterator< BasicBlock::iterator, std::function< bool(Instruction &)> > > instructionsWithoutDebug ()
Return an iterator range over the instructions in the block, skipping any debug instructions.
filter_iterator< BasicBlock::const_iterator, std::function< bool(const Instruction &)> >::difference_type sizeWithoutDebug () const
Return the size of the basic block ignoring debug instructions.
void removeFromParent ()
Unlink 'this' from the containing function, but do not delete it.
SymbolTableList< BasicBlock >::iterator eraseFromParent ()
Unlink 'this' from the containing function and delete it.
void moveBefore (BasicBlock *MovePos)
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
void moveAfter (BasicBlock *MovePos)
Unlink this basic block from its current function and insert it right after MovePos in the function MovePos lives in.
void insertInto (Function *Parent, BasicBlock *InsertBefore=nullptr)
Insert unlinked basic block into a function.
const BasicBlock * getSinglePredecessor () const
Return the predecessor of this block if it has a single predecessor block.
BasicBlock * getSinglePredecessor ()
const BasicBlock * getUniquePredecessor () const
Return the predecessor of this block if it has a unique predecessor block.
BasicBlock * getUniquePredecessor ()
bool hasNPredecessors (unsigned N) const
Return true if this block has exactly N predecessors.
bool hasNPredecessorsOrMore (unsigned N) const
Return true if this block has N predecessors or more.
const BasicBlock * getSingleSuccessor () const
Return the successor of this block if it has a single successor.
BasicBlock * getSingleSuccessor ()
const BasicBlock * getUniqueSuccessor () const
Return the successor of this block if it has a unique successor.
BasicBlock * getUniqueSuccessor ()
iterator begin ()
Instruction iterator methods.
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
const Instruction & front () const
Instruction & front ()
const Instruction & back () const
Instruction & back ()
iterator_range< const_phi_iterator > phis () const
Returns a range that iterates over the phis in the basic block.
iterator_range< phi_iterator > phis ()
const InstListType & getInstList () const
Return the underlying instruction list container.
InstListType & getInstList ()
ValueSymbolTable * getValueSymbolTable ()
Returns a pointer to the symbol table if one exists.
void dropAllReferences ()
Cause all subinstructions to "let go" of all the references that said subinstructions are maintaining.
void removePredecessor (BasicBlock *Pred, bool KeepOneInputPHIs=false)
Notify the BasicBlock that the predecessor Pred is no longer able to reach it.
bool canSplitPredecessors () const
BasicBlock * splitBasicBlock (iterator I, const Twine &BBName="")
Split the basic block into two basic blocks at the specified instruction.
BasicBlock * splitBasicBlock (Instruction *I, const Twine &BBName="")
bool hasAddressTaken () const
Returns true if there are any uses of this basic block other than direct branches, switches, etc.
void replacePhiUsesWith (BasicBlock *Old, BasicBlock *New)
Update all phi nodes in this basic block to refer to basic block New instead of basic block Old.
void replaceSuccessorsPhiUsesWith (BasicBlock *Old, BasicBlock *New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of basic block Old.
void replaceSuccessorsPhiUsesWith (BasicBlock *New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of to it.
bool isEHPad () const
Return true if this basic block is an exception handling block.
bool isLandingPad () const
Return true if this basic block is a landing pad.
const LandingPadInst * getLandingPadInst () const
Return the landingpad instruction associated with the landing pad.
LandingPadInst * getLandingPadInst ()
bool isLegalToHoistInto () const
Return true if it is legal to hoist instructions into this block.
Optional< uint64_t > getIrrLoopHeaderWeight () const
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< BasicBlock, Function >
BasicBlock * getPrevNode ()
const BasicBlock * getPrevNode () const
Get the previous node, or nullptr for the list head.
BasicBlock * getNextNode ()
Get the next node, or nullptr for the list tail.
const BasicBlock * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< BasicBlock, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static BasicBlock * Create (LLVMContext &Context, const Twine &Name="", Function *Parent=nullptr, BasicBlock *InsertBefore=nullptr)
Creates a new BasicBlock.
static InstListType BasicBlock::* getSublistAccess (Instruction *)
Returns a pointer to a member of the instruction list.
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast.
Friends
class BlockAddress
class SymbolTableListTraits< BasicBlock >
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< BasicBlock, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< BasicBlock, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< BasicBlock, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< BasicBlock, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< BasicBlock, Options... >::type, true, true >
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node_with_parent< BasicBlock, Function >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< BasicBlock, Options... >::type >
ilist_node_impl ()=default
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
LLVM Basic Block Representation.
This represents a single basic block in LLVM. A basic block is simply a container of instructions that execute sequentially. Basic blocks are Values because they are referenced by instructions such as branches and switch tables. The type of a BasicBlock is "Type::LabelTy" because the basic block represents a label to which a branch can jump.
A well formed basic block is formed of a list of non-terminating instructions followed by a single terminator instruction. Terminator instructions may not occur in the middle of basic blocks, and must terminate the blocks. The BasicBlock class allows malformed basic blocks to occur because it may be useful in the intermediate stage of constructing or modifying a program. However, the verifier will ensure that basic blocks are "well formed".
Definition at line 57 of file BasicBlock.h.
Member Typedef Documentation
const_iterator
using llvm::BasicBlock::const_iterator = InstListType::const_iterator
Definition at line 90 of file BasicBlock.h.
const_phi_iterator
using llvm::BasicBlock::const_phi_iterator = phi_iterator_impl<const PHINode, BasicBlock::const_iterator>
Definition at line 324 of file BasicBlock.h.
const_reverse_iterator
using llvm::BasicBlock::const_reverse_iterator = InstListType::const_reverse_iterator
Definition at line 92 of file BasicBlock.h.
InstListType
using llvm::BasicBlock::InstListType = SymbolTableList<Instruction>
Definition at line 60 of file BasicBlock.h.
iterator
using llvm::BasicBlock::iterator = InstListType::iterator
Instruction iterators...
Definition at line 89 of file BasicBlock.h.
phi_iterator
using llvm::BasicBlock::phi_iterator = phi_iterator_impl<>
Definition at line 322 of file BasicBlock.h.
reverse_iterator
using llvm::BasicBlock::reverse_iterator = InstListType::reverse_iterator
Definition at line 91 of file BasicBlock.h.
Constructor & Destructor Documentation
BasicBlock()
llvm::BasicBlock::BasicBlock (const BasicBlock &) delete
~BasicBlock()
BasicBlock::~BasicBlock ()
Definition at line 63 of file BasicBlock.cpp.
References assert(), llvm::iplist_impl< IntrusiveListT, TraitsT >::clear(), llvm::Constant::destroyConstant(), dropAllReferences(), llvm::ConstantInt::get(), getContext(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getIntToPtr(), getParent(), llvm::Value::getType(), hasAddressTaken(), llvm::Value::replaceAllUsesWith(), llvm::SymbolTableListTraits< ValueSubClass >::setSymTabObject(), llvm::Value::use_empty(), and llvm::Value::user_back().
Member Function Documentation
back() [1/2]
const Instruction& llvm::BasicBlock::back () const inline
Definition at line 287 of file BasicBlock.h.
Referenced by llvm::DomTreeUpdater::callbackDeleteBB(), llvm::AAResults::canBasicBlockModify(), CheckForCanReleaseCFGHazard(), llvm::CloneAndPruneIntoFromInst(), createCallInst(), createCast(), llvm::createObjCARCOptPass(), FindPredecessorAutoreleaseWithSafePath(), findUnwindDestinations(), llvm::SCEVExpander::getRelatedExistingExpansion(), intersect(), promoteSingleBlockAlloca(), llvm::SimplifyInstructionsInBlock(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::Solve(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
back() [2/2]
Instruction& llvm::BasicBlock::back () inline
Definition at line 288 of file BasicBlock.h.
begin() [1/2]
iterator llvm::BasicBlock::begin () inline
Instruction iterator methods.
Definition at line 273 of file BasicBlock.h.
Referenced by AddReachableCodeToWorklist(), llvm::MemorySSAUpdater::applyInsertUpdates(), llvm::calculateWasmEHInfo(), llvm::Interpreter::callFunction(), CanPropagatePredecessorsForPHIs(), canSplitCallSite(), CheckForCanReleaseCFGHazard(), llvm::CloneAndPruneIntoFromInst(), CloneLoopBlocks(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::computePeelCount(), ComputePostOrders(), createCallInst(), llvm::OpenMPIRBuilder::CreateCancel(), createCast(), llvm::createCodeGenPreparePass(), llvm::createObjCARCOptPass(), llvm::OpenMPIRBuilder::CreateParallel(), llvm::createScalarizerPass(), llvm::createShadowStackGCLoweringPass(), cse(), DeleteBasicBlock(), despeculateCountZeros(), llvm::PostDominatorTree::dominates(), llvm::DominatorTree::dominates(), llvm::GVNExpression::Expression::dump(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), eliminateDeadStores(), llvm::EliminateDuplicatePHINodes(), eliminateRecursiveTailCall(), ensureValueAvailableInSuccessor(), llvm::OrderedBasicBlock::eraseInstruction(), eraseLifetimeMarkersOnInputs(), llvm::Evaluator::EvaluateFunction(), llvm::CodeExtractor::extractCodeRegion(), llvm::FastISel::fastEmitZExtFromI1(), llvm::FindAvailablePtrLoadStore(), llvm::objcarc::FindDependencies(), findIBRPredecessor(), findInitTrampolineFromBB(), llvm::CodeExtractor::findInputsOutputs(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), findPHIToPartitionLoops(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), findRetainForStoreStrongContraction(), findTRECandidate(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), fixPhis(), FoldCondBranchOnPHI(), llvm::FoldSingleEntryPHINodes(), FoldTwoEntryPHINode(), llvm::Loop::getCanonicalInductionVariable(), llvm::MemoryDependenceResults::getDependency(), llvm::GetIfCondition(), getInductionVariable(), GetLocation(), getMemSetPatternValue(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getUnrollingPreferences(), llvm::PPCTTIImpl::getUserCost(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleByValArgumentInit(), HandleCallsInBlockInlinedThroughInvoke(), handleEndBlock(), hasProfileData(), hasUsesOutsideLoop(), llvm::hoistAllInstructionsInto(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::InlineFunction(), InsertRootInitializers(), InsertSafepointPoll(), insertSinCosCall(), instrumentMaskedLoadOrStore(), is_empty(), llvm::isGuaranteedToTransferExecutionToSuccessor(), IsIncrementNUW(), IsNonLocalValue(), isOnlyReachableViaThisEdge(), llvm::isSafeToLoadUnconditionally(), llvm::Value::isUsedInBasicBlock(), isZero(), llvm::IVUsers::IVUsers(), LLVMGetFirstInstruction(), LLVMGetLastInstruction(), LLVMGetPreviousInstruction(), llvm::log2(), makeBitReverse(), makeStatepointExplicitImpl(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::MarkBlockExecutable(), MarkBlocksLiveIn(), memoryIsNotModifiedBetween(), llvm::MergeBasicBlockIntoOnlyPred(), mergeCleanupPad(), mergeEmptyReturnBlocks(), moveLCSSAPhis(), NegateValue(), normalizeForInvokeSafepoint(), operator new(), operator<<(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeSQRT(), llvm::OrderedBasicBlock::OrderedBasicBlock(), llvm::peelLoop(), performMaskedAtomicOp(), phis(), ProcessBlock(), processInternalGlobal(), promoteMemoryToRegister(), promoteSingleBlockAlloca(), PushLoopPHIs(), removeEmptyCleanup(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), removeUndefIntroducingPredecessor(), replacePhiUsesWith(), ReplaceUsesOfWith(), RetagMask(), rewritePHINodesForExitAndUnswitchedBlocks(), RewriteUsesOfClonedInstructions(), runOnBasicBlock(), scalarizeMaskedCompressStore(), shouldKeepInEntry(), shouldRotateLoopExitingLatch(), SimplifyCondBranchToCondBranch(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SimplifyIndirectBrOnSelect(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopIVs(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), llvm::sinkRegion(), sizeWithoutDebug(), SpeculativelyExecuteBB(), llvm::SplitBlock(), llvm::SplitBlockPredecessors(), splitCallSite(), llvm::SplitCriticalEdge(), llvm::JumpThreadingPass::ThreadEdge(), llvm::JumpThreadingPass::ThreadGuard(), truncateIVUse(), tryToElideArgumentCopy(), tryToMoveFreeBeforeNullTest(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::JumpThreadingPass::TryToUnfoldSelectInCurrBB(), tryToVectorizeHorReductionOrInstOperands(), TurnSwitchRangeIntoICmp(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), unswitchNontrivialInvariants(), updateForIncomingValueLocation(), UpdatePHINodes(), updatePhiNodes(), llvm::LoopVersioning::versionLoop(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit(), llvm::Interpreter::visitIndirectBrInst(), llvm::InstCombiner::visitPHINode(), and llvm::InstCombiner::visitStoreInst().
begin() [2/2]
const_iterator llvm::BasicBlock::begin () const inline
Definition at line 274 of file BasicBlock.h.
canSplitPredecessors()
bool BasicBlock::canSplitPredecessors () const
Definition at line 378 of file BasicBlock.cpp.
References getFirstNonPHI(), and llvm::Instruction::isEHPad().
Referenced by canSplitCallSite(), canSplitPredecessors(), classof(), and llvm::SplitBlockPredecessors().
classof()
static bool llvm::BasicBlock::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 350 of file BasicBlock.h.
References canSplitPredecessors(), dropAllReferences(), llvm::Value::getValueID(), I, removePredecessor(), and splitBasicBlock().
Create()
static BasicBlock* llvm::BasicBlock::Create (LLVMContext & Context, const Twine & Name = "", Function * Parent = nullptr, BasicBlock * InsertBefore = nullptr) inline static
Creates a new BasicBlock.
If the Parent parameter is specified, the basic block is automatically inserted at either the end of the function (if InsertBefore is 0), or before the specified basic block.
Definition at line 99 of file BasicBlock.h.
References llvm::ISD::BasicBlock, and Name.
Referenced by addBoundsChecking(), AddCalls(), assureFPCallStub(), canCreateThunkFor(), llvm::CloneBasicBlock(), llvm::CloneFunction(), llvm::OpenMPIRBuilder::CreateCancel(), createDevirtTriggerFunc(), llvm::MIRParserImpl::createDummyFunction(), llvm::createDwarfEHPass(), createEmptyFunction(), createFPFnStub(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), CreatePrologue(), createResumeEntryBlock(), llvm::createSanitizerCtorAndInitFunctions(), createWrapper(), llvm::createX86RetpolineThunksPass(), llvm::VPBlockBase::deleteCFG(), ehAwareSplitEdge(), eliminateRecursiveTailCall(), llvm::orc::IRSpeculationLayer::emit(), llvm::CodeExtractor::extractCodeRegion(), llvm::CodeExtractor::findInputsOutputs(), llvm::SanitizerStatReport::finish(), FitWeights(), FoldCondBranchOnPHI(), FunctionNumber(), getSignature(), INITIALIZE_PASS(), insertLifetimeMarkersSurroundingCall(), insertUniqueBackedgeBlock(), instrumentMaskedLoadOrStore(), LLVMAppendBasicBlockInContext(), LLVMCreateBasicBlockInContext(), LLVMInsertBasicBlockInContext(), llvm::orc::makeStub(), mayLoopAccessLocation(), needsRuntimeRegistrationOfSectionRange(), llvm::EscapeEnumerator::Next(), optimizeSQRT(), performMaskedAtomicOp(), ReplaceUsesOfWith(), llvm::UnifyFunctionExitNodes::runOnFunction(), scaleWeights(), selectJumpTableArmEncoding(), shouldKeepInEntry(), SimplifyCondBranchToCondBranch(), SimplifyIndirectBrOnSelect(), llvm::sinkRegion(), splitBasicBlock(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), splitRetconCoroutine(), SwitchToLookupTable(), llvm::JumpThreadingPass::ThreadEdge(), llvm::JumpThreadingPass::UnfoldSelectInstr(), and unifyReturnBlockSet().
dropAllReferences()
void BasicBlock::dropAllReferences ()
Cause all subinstructions to "let go" of all the references that said subinstructions are maintaining.
This allows one to 'delete' a whole class at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is delete'd for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 233 of file BasicBlock.cpp.
References llvm::User::dropAllReferences(), and I.
Referenced by classof(), deleteDeadBlocksFromLoop(), llvm::Function::dropAllReferences(), and ~BasicBlock().
empty()
bool llvm::BasicBlock::empty () const inline
Definition at line 284 of file BasicBlock.h.
Referenced by llvm::DomTreeUpdater::callbackDeleteBB(), is_empty(), and phis().
end() [1/2]
iterator llvm::BasicBlock::end () inline
Definition at line 275 of file BasicBlock.h.
Referenced by AddReachableCodeToWorklist(), llvm::MemorySSAUpdater::changeToUnreachable(), llvm::changeToUnreachable(), CheckForCanReleaseCFGHazard(), llvm::CloneFunction(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::ConvertDebugDeclareToDebugValue(), llvm::OpenMPIRBuilder::CreateCancel(), createCast(), llvm::OpenMPIRBuilder::CreateParallel(), cse(), DeleteBasicBlock(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), eliminateDeadStores(), eliminateRecursiveTailCall(), llvm::OrderedBasicBlock::eraseInstruction(), llvm::CodeExtractor::extractCodeRegion(), llvm::objcarc::FindDependencies(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), findSafeStoreForStoreStrongContraction(), first_use_of_in_block(), getFirstInsertionPt(), getMemSetPatternValue(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getUnrollingPreferences(), llvm::PPCTTIImpl::getUserCost(), HandleCallsInBlockInlinedThroughInvoke(), handleEndBlock(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), hasProfileData(), llvm::hoistAllInstructionsInto(), INITIALIZE_PASS(), llvm::insertDebugValuesForPHIs(), InsertSafepointPoll(), llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::isInTailCallPosition(), isOnlyReachableViaThisEdge(), llvm::isPotentiallyReachable(), isSafeAndProfitableToSinkLoad(), llvm::Value::isUsedInBasicBlock(), llvm::isValidAssumeForContext(), isZero(), LLVMGetFirstInstruction(), LLVMGetLastInstruction(), LLVMGetNextInstruction(), LLVMPositionBuilder(), makeBitReverse(), MarkBlocksLiveIn(), memoryIsNotModifiedBetween(), mergeConditionalStoreToAddress(), llvm::Instruction::moveBefore(), llvm::InjectorIRStrategy::mutate(), NegateValue(), llvm::RandomIRBuilder::newSource(), operator new(), OptimizeExtractBits(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::OrderedBasicBlock::OrderedBasicBlock(), passingValueIsAlwaysUndefined(), performMaskedAtomicOp(), llvm::PrepareToSplitEntryBlock(), ProcessBlock(), promoteMemoryToRegister(), propagateMetadata(), removeTriviallyEmptyRange(), llvm::OrderedBasicBlock::replaceInstruction(), replacePhiUsesWith(), RetagMask(), RewriteUsesOfClonedInstructions(), runOnBasicBlock(), scalarizeMaskedCompressStore(), llvm::IRBuilderBase::SetInsertPoint(), shouldInstrumentBlock(), shouldRotateLoopExitingLatch(), llvm::SimplifyInstructionsInBlock(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), SinkCast(), sinkCmpExpression(), llvm::sinkRegion(), SinkShiftAndTruncate(), sizeWithoutDebug(), SpeculativelyExecuteBB(), splitBasicBlock(), llvm::JumpThreadingPass::ThreadEdge(), TryToSinkInstruction(), tryToVectorizeHorReductionOrInstOperands(), unswitchTrivialBranch(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit().
end() [2/2]
const_iterator llvm::BasicBlock::end () const inline
Definition at line 276 of file BasicBlock.h.
eraseFromParent()
iplist< BasicBlock >::iterator BasicBlock::eraseFromParent ()
Unlink 'this' from the containing function and delete it.
Definition at line 121 of file BasicBlock.cpp.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::Function::getBasicBlockList(), llvm::ilist_node_impl< ilist_detail::compute_node_options< BasicBlock, Options... >::type >::getIterator(), and getParent().
Referenced by llvm::CloneAndPruneIntoFromInst(), createCast(), llvm::createCodeGenPreparePass(), llvm::OpenMPIRBuilder::CreateParallel(), DeleteBasicBlock(), deleteDeadBlocksFromLoop(), despeculateCountZeros(), getFirstInsertionPt(), llvm::InlineFunction(), llvm::MergeBasicBlockIntoOnlyPred(), mergeCleanupPad(), mergeEmptyReturnBlocks(), removeEmptyCleanup(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), and unifyReturnBlockSet().
front() [1/2]
const Instruction& llvm::BasicBlock::front () const inline
Definition at line 285 of file BasicBlock.h.
Referenced by calculateStateNumbersForInvokes(), llvm::AAResults::canBasicBlockModify(), llvm::CloneAndPruneFunctionInto(), llvm::CloneAndPruneIntoFromInst(), CloneInstructionInExitBlock(), llvm::createAArch64StackTaggingPass(), llvm::SSAUpdaterTraits< SSAUpdater >::CreateEmptyPHI(), createFFSIntrinsic(), createPHIsForSplitLoopExit(), CreatePrologue(), createRetPHINode(), createUnreachableSwitchDefault(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), despeculateCountZeros(), detectShiftUntilZeroIdiom(), llvm::GVNExpression::Expression::dump(), eliminateDeadStores(), eliminateRecursiveTailCall(), ensureValueAvailableInSuccessor(), llvm::CodeExtractor::findInputsOutputs(), findLocationForEntrySafepoint(), findTRECandidate(), llvm::IRPosition::getAttrs(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), getOffsetFromIndices(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), GetRMWLibcall(), getSuccState(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), INITIALIZE_PASS(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), insertSpills(), insertTrivialPHIs(), instrumentMaskedLoadOrStore(), IsIncrementNUW(), isLoadConditional(), isOnlyReachableViaThisEdge(), isProfitableForVectorization(), isSafeToExecuteUnconditionally(), isSafeToPromoteArgument(), isSuspendBlock(), isZero(), MarkBlocksLiveIn(), llvm::MergeBlockIntoPredecessor(), mergeCleanupPad(), mergeEmptyReturnBlocks(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), promoteSingleBlockAlloca(), llvm::removeAllNonTerminatorAndEHPadInstructions(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), rewritePHIs(), llvm::Attributor::run(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyIndirectBrOnSelect(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), llvm::SplitEdge(), StackMallocSizeClass(), truncateIVUse(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), unswitchTrivialSwitch(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), llvm::LoopVersioning::versionLoop(), and llvm::InstCombiner::visitStoreInst().
front() [2/2]
Instruction& llvm::BasicBlock::front () inline
Definition at line 286 of file BasicBlock.h.
getContext()
LLVMContext & BasicBlock::getContext () const
Get the context in which this basic block lives.
Definition at line 32 of file BasicBlock.cpp.
References assert(), llvm::ISD::BasicBlock, C, llvm::Type::getContext(), llvm::Type::getLabelTy(), llvm::Value::getType(), insertInto(), Name, llvm::Value::setName(), and llvm::Value::Value().
Referenced by AddRuntimeUnrollDisableMetaData(), allPredecessorsComeFromSameSource(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::SwitchInstProfUpdateWrapper::buildProfBranchWeightsMD(), calcArraySize(), llvm::DomTreeUpdater::callbackDeleteBB(), llvm::CloneBasicBlock(), llvm::CloneFunction(), llvm::CallBrInst::Create(), llvm::OpenMPIRBuilder::CreateCancel(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createStringMetadata(), llvm::VPBlockBase::deleteCFG(), DisableAllLoopOptsOnLoop(), ehAwareSplitEdge(), llvm::emitBCmp(), llvm::emitCalloc(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), llvm::emitMalloc(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitMemCpyChk(), llvm::emitStrLen(), llvm::emitStrNCmp(), EqualityPropUnSafe(), eraseDeadBBsAndChildren(), llvm::CodeExtractor::extractCodeRegion(), llvm::CodeExtractor::findInputsOutputs(), FitWeights(), llvm::AMDGPULibCalls::fold(), FoldCondBranchOnPHI(), insertCall(), insertUniqueBackedgeBlock(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isOnlyReachableViaThisEdge(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MemorySSA::moveTo(), optimizeMemCmpConstantSize(), optimizeSQRT(), llvm::parseWidenableBranch(), patchAndReplaceAllUsesWith(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::IRCEPass::run(), llvm::runIPSCCP(), scaleWeights(), llvm::LoopVectorizeHints::setAlreadyVectorized(), setBranchWeights(), llvm::Loop::setLoopAlreadyUnrolled(), SimplifyIndirectBrOnSelect(), llvm::sinkRegion(), splitBasicBlock(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), llvm::JumpThreadingPass::ThreadEdge(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnreachableInst::UnreachableInst(), updatePredecessorProfileMetadata(), and ~BasicBlock().
getFirstInsertionPt() [1/2]
BasicBlock::const_iterator BasicBlock::getFirstInsertionPt () const
Returns an iterator to the first instruction in this block that is suitable for inserting a non-PHI instruction.
In particular, it skips all PHIs and LandingPad instructions.
Definition at line 223 of file BasicBlock.cpp.
References end(), getFirstNonPHI(), and llvm::ilist_node_impl< OptionsT >::getIterator().
Referenced by cheapToScalarize(), CloneInstructionInExitBlock(), llvm::ConvertDebugDeclareToDebugValue(), ConvertToSInt(), llvm::DemoteRegToStack(), llvm::GVNExpression::Expression::dump(), eraseDeadBBsAndChildren(), llvm::VPlan::execute(), llvm::SCEVExpander::expandCodeFor(), findInsertPointAfter(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), foldGuardedRotateToFunnelShift(), getFirstInsertionPt(), getFirstNonPHIOrDbgOrLifetime(), GetPointerOperand(), getRetComponentType(), getScalarIntrinsicDeclaration(), getSignature(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), hasSameExtUse(), hasUsesOutsideLoop(), llvm::insertDebugValuesForPHIs(), insertSpills(), instrumentMaskedLoadOrStore(), IsInterestingCmp(), isPromotedResultSafe(), makeBitReverse(), makeStatepointExplicitImpl(), MarkBlocksLiveIn(), mergeConditionalStoreToAddress(), llvm::InjectorIRStrategy::mutate(), llvm::InstDeleterIRStrategy::mutate(), llvm::RandomIRBuilder::newSink(), llvm::RandomIRBuilder::newSource(), OptimizeExtractBits(), llvm::SCEVExpander::replaceCongruentIVs(), replaceExtractElements(), rewriteMaterializableInstructions(), llvm::InstCombiner::run(), setInsertionPoint(), shouldInstrumentBlock(), simplifyRelocatesOffABase(), SinkCast(), sinkCmpExpression(), SinkShiftAndTruncate(), llvm::SplitLandingPadPredecessors(), llvm::JumpThreadingPass::ThreadGuard(), truncateIVUse(), TryToSinkInstruction(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), llvm::InstCombiner::visitStoreInst(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getFirstInsertionPt() [2/2]
iterator llvm::BasicBlock::getFirstInsertionPt () inline
Definition at line 178 of file BasicBlock.h.
References eraseFromParent(), getFirstInsertionPt(), getSinglePredecessor(), insertInto(), instructionsWithoutDebug(), moveAfter(), moveBefore(), removeFromParent(), and sizeWithoutDebug().
getFirstNonPHI() [1/2]
const Instruction * BasicBlock::getFirstNonPHI () const
Returns a pointer to the first instruction in this block that is not a PHINode instruction.
When adding instructions to the beginning of the basic block, they should be added before the returned value, not before the first instruction, which might be PHI. Returns 0 is there's no non-PHI instruction.
Definition at line 196 of file BasicBlock.cpp.
References I.
Referenced by llvm::MachineFunction::addLandingPad(), llvm::calculateClrEHStateNumbers(), calculateStateNumbersForInvokes(), llvm::calculateWasmEHInfo(), CanGenerateTest(), canSplitPredecessors(), canSplitPredecessors(), Cleanup(), CloneLoopBlocks(), llvm::colorEHFunclets(), ConnectEpilog(), ConnectProlog(), createCallInst(), llvm::createMemCpyLoopKnownSize(), llvm::OpenMPIRBuilder::CreateParallel(), createPHIsForSplitLoopExit(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), ehAwareSplitEdge(), eraseDeadBBsAndChildren(), llvm::CodeExtractor::findInputsOutputs(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), findUnwindDestinations(), findWasmUnwindDestinations(), fixPhis(), getFirstInsertionPt(), getFirstNonPHI(), getJumpThreadDuplicationCost(), getLandingPadInst(), getParentPad(), GetPointerOperand(), getSignature(), getSuccPad(), getSuccState(), getTerminatingMustTailCall(), getUnwindDestTokenHelper(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleInlinedEHPad(), hoist(), llvm::InlineFunction(), llvm::insertDebugValuesForPHIs(), insertSpills(), isAtomic(), llvm::isDereferenceableAndAlignedInLoop(), isEHPad(), isLandingPad(), isProfitableForVectorization(), isWrapperOnlyCall(), mapWasmLandingPadIndex(), markAliveBlocks(), mayUsePostIncMode(), moveLCSSAPhis(), relocationViaAlloca(), removeEmptyCleanup(), replaceAllUsesOfWithIn(), rewritePHIs(), llvm::IRTranslator::runOnMachineFunction(), llvm::SplitLandingPadPredecessors(), TypeSizeToSizeIndex(), and llvm::UnrollRuntimeLoopRemainder().
getFirstNonPHI() [2/2]
Instruction* llvm::BasicBlock::getFirstNonPHI () inline
Definition at line 152 of file BasicBlock.h.
References getFirstNonPHI(), and getFirstNonPHIOrDbg().
getFirstNonPHIOrDbg() [1/2]
const Instruction * BasicBlock::getFirstNonPHIOrDbg () const
Returns a pointer to the first instruction in this block that is not a PHINode or a debug intrinsic.
Definition at line 203 of file BasicBlock.cpp.
References I.
Referenced by llvm::createCodeGenPreparePass(), doCallSiteSplitting(), eliminateSwiftErrorArgument(), eliminateTailRecursion(), FindPHIForConditionForwarding(), foldReturnAndProcessPred(), getFirstNonPHI(), getFirstNonPHIOrDbg(), InitializeUniqueCases(), llvm::SimpleLoopSafetyInfo::isGuaranteedToExecute(), isIgnorableInst(), isPredicatedOnPHI(), mergeCleanupPad(), llvm::moveInstsBottomUp(), replaceSwiftErrorOps(), SimplifyCondBranchToTwoReturns(), llvm::SplitBlockPredecessors(), SwitchToLookupTable(), TryToMergeLandingPad(), TurnSwitchRangeIntoICmp(), and llvm::InstCombiner::visitAllocaInst().
getFirstNonPHIOrDbg() [2/2]
Instruction* llvm::BasicBlock::getFirstNonPHIOrDbg () inline
Definition at line 160 of file BasicBlock.h.
References getFirstNonPHIOrDbg(), and getFirstNonPHIOrDbgOrLifetime().
getFirstNonPHIOrDbgOrLifetime() [1/2]
const Instruction * BasicBlock::getFirstNonPHIOrDbgOrLifetime () const
Returns a pointer to the first instruction in this block that is not a PHINode, a debug intrinsic, or a lifetime intrinsic.
Definition at line 210 of file BasicBlock.cpp.
References I, and llvm::Instruction::isLifetimeStartOrEnd().
Referenced by getFirstNonPHIOrDbg(), getFirstNonPHIOrDbgOrLifetime(), GetSortedValueDataFromCallTargets(), shouldInstrumentBlock(), simplifyTerminatorLeadingToRet(), and llvm::SplitCriticalEdge().
getFirstNonPHIOrDbgOrLifetime() [2/2]
Instruction* llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime () inline
Definition at line 168 of file BasicBlock.h.
References getFirstInsertionPt(), and getFirstNonPHIOrDbgOrLifetime().
getInstList() [1/2]
const InstListType& llvm::BasicBlock::getInstList () const inline
Return the underlying instruction list container.
Currently you need to access the underlying instruction list container directly if you want to modify it.
Definition at line 338 of file BasicBlock.h.
Referenced by assertBranchOrSelectConditionHoisted(), calcArraySize(), llvm::DomTreeUpdater::callbackDeleteBB(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::changeToUnreachable(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneBasicBlock(), llvm::CloneFunction(), CloneInstructionInExitBlock(), llvm::JumpThreadingPass::CloneInstructions(), llvm::UnaryOperator::Create(), llvm::BinaryOperator::Create(), createCallHelper(), createInvokeHelper(), createMalloc(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), eliminateRecursiveTailCall(), llvm::Instruction::eraseFromParent(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), FunctionNumber(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::hoistAllInstructionsInto(), HoistThenElseCodeToIf(), llvm::InlineFunction(), llvm::Instruction::insertAfter(), llvm::Instruction::insertBefore(), llvm::IRBuilderDefaultInserter::InsertHelper(), insertLifetimeMarkersSurroundingCall(), llvm::InstCombiner::InsertNewInstBefore(), insertUniqueBackedgeBlock(), llvm::Instruction::Instruction(), LdStHasDebugValue(), llvm::MergeBasicBlockIntoOnlyPred(), moveBBContents(), llvm::Instruction::moveBefore(), llvm::Instruction::removeFromParent(), removePredecessor(), llvm::ReplaceInstWithInst(), llvm::InstCombiner::run(), llvm::UnifyFunctionExitNodes::runOnFunction(), SpeculativelyExecuteBB(), splitBasicBlock(), llvm::SplitLandingPadPredecessors(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::UnrollLoop(), unswitchTrivialBranch(), updateForIncomingValueLocation(), and llvm::InstCombiner::visitGetElementPtrInst().
getInstList() [2/2]
InstListType& llvm::BasicBlock::getInstList () inline
Definition at line 339 of file BasicBlock.h.
getIrrLoopHeaderWeight()
Optional< uint64_t > BasicBlock::getIrrLoopHeaderWeight () const
Definition at line 479 of file BasicBlock.cpp.
References llvm::StringRef::equals(), llvm::Instruction::getMetadata(), llvm::MDString::getString(), and getTerminator().
Referenced by getLandingPadInst().
getLandingPadInst() [1/2]
const LandingPadInst * BasicBlock::getLandingPadInst () const
Return the landingpad instruction associated with the landing pad.
Definition at line 475 of file BasicBlock.cpp.
References llvm::dyn_cast(), and getFirstNonPHI().
Referenced by getLandingPadInst(), getParentPad(), isEHPad(), makeStatepointExplicitImpl(), MarkBlocksLiveIn(), and llvm::SplitLandingPadPredecessors().
getLandingPadInst() [2/2]
LandingPadInst* llvm::BasicBlock::getLandingPadInst () inline
Definition at line 421 of file BasicBlock.h.
References assert(), D, DEFINE_SIMPLE_CONVERSION_FUNCTIONS, getIrrLoopHeaderWeight(), getLandingPadInst(), llvm::Value::getSubclassDataFromValue(), isLegalToHoistInto(), llvm::Value::setValueSubclassData(), and llvm::skipDebugIntrinsics().
getModule() [1/2]
const Module * BasicBlock::getModule () const
Return the module owning the function this basic block belongs to, or nullptr if the function does not have a module.
Note: this is undefined behavior if the block does not have a parent.
Definition at line 140 of file BasicBlock.cpp.
References getParent(), and llvm::GlobalValue::getParent().
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), Cleanup(), llvm::CloneFunction(), llvm::IRBuilderBase::CreateBinaryIntrinsic(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), eliminateDeadStores(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), llvm::InnerLoopVectorizer::emitSCEVChecks(), emitUnaryFloatFnCallHelper(), llvm::LazyValueInfo::eraseBlock(), llvm::FindAvailablePtrLoadStore(), findPHIToPartitionLoops(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getEdgeValueLocal(), llvm::Instruction::getModule(), getModule(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), getParent(), GetPointerOperand(), llvm::LazyValueInfo::getPredicateOnEdge(), llvm::getPtrStride(), getSignature(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), getVectorType(), handleEndBlock(), isIgnorableInst(), isLoadConditional(), isObjectDereferencedInBlock(), mayUsePostIncMode(), llvm::MemoryDepChecker::Dependence::print(), llvm::printLoop(), llvm::JumpThreadingPass::ProcessBlock(), llvm::promoteLoopAccessesToScalars(), ReduceLoopStrength(), ReplaceUsesOfWith(), llvm::LoopRotatePass::run(), llvm::IndVarSimplifyPass::run(), llvm::LoopIdiomRecognizePass::run(), llvm::simplifyCFG(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), llvm::LazyValueInfo::threadEdge(), llvm::JumpThreadingPass::ThreadGuard(), tryToVectorizeHorReductionOrInstOperands(), llvm::UnrollRuntimeLoopRemainder(), llvm::LoopVersioning::versionLoop(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getModule() [2/2]
Module* llvm::BasicBlock::getModule () inline
Definition at line 114 of file BasicBlock.h.
References getModule(), getTerminator(), and LLVM_READONLY.
getParent() [1/2]
const Function* llvm::BasicBlock::getParent () const inline
Return the enclosing method, or null if none.
Definition at line 106 of file BasicBlock.h.
Referenced by addNoRecurseAttrsTopDown(), allPredecessorsComeFromSameSource(), calculateSEHStateNumbers(), callIntrinsic(), canFoldIVIncExpr(), CanGenerateTest(), castToIncrementInst(), llvm::changeToUnreachable(), CloneLoopBlocks(), cloneLoopBlocks(), llvm::cloneLoopWithPreheader(), llvm::CodeMetrics::collectEphemeralValues(), combineADDToADDZE(), CompareValueComplexity(), llvm::LoopSafetyInfo::computeBlockColors(), computeKnownBitsFromAssume(), llvm::computePeelCount(), llvm::computeUnrollCount(), copyMustTailReturn(), llvm::SanitizerStatReport::create(), llvm::IRBuilder< TargetFolder >::CreateAlloca(), llvm::createArgumentPromotionPass(), llvm::OpenMPIRBuilder::CreateCancel(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilderBase::CreateFAddReduce(), createFFSIntrinsic(), llvm::IRBuilderBase::CreateFMulReduce(), llvm::IRBuilderBase::CreateGCRelocate(), llvm::IRBuilderBase::CreateGCResult(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), llvm::IRBuilderBase::CreateGlobalString(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilder< TargetFolder >::CreateLaunderInvariantGroup(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMaskedStore(), createMaskInstrs(), llvm::IRBuilderBase::CreateMemCpy(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), llvm::IRBuilderBase::CreateMemMove(), createMemMoveLoop(), llvm::IRBuilderBase::CreateMemSet(), createMemSetLoop(), llvm::OpenMPIRBuilder::CreateParallel(), createPopcntIntrinsic(), llvm::IRBuilder< TargetFolder >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< TargetFolder >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< TargetFolder >::CreatePreserveUnionAccessIndex(), llvm::createScalarizerPass(), llvm::IRBuilder< TargetFolder >::CreateStripInvariantGroup(), DeleteBasicBlock(), llvm::VPBlockBase::deleteCFG(), deleteDeadInstruction(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), despeculateCountZeros(), DisableAllLoopOptsOnLoop(), llvm::InstCombiner::dominatesAllUses(), ehAwareSplitEdge(), eliminateDeadStores(), eliminateRecursiveTailCall(), llvm::orc::IRSpeculationLayer::emit(), llvm::AArch64TargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::PPCTargetLowering::emitTrailingFence(), enableCallSafepoints(), llvm::LazyValueInfo::enableDT(), EqualityPropUnSafe(), eraseFromParent(), llvm::slpvectorizer::BoUpSLP::eraseInstructions(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), llvm::CodeExtractor::extractCodeRegion(), llvm::CodeExtractor::findAllocas(), llvm::findDevirtualizableCallsForTypeTest(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::CodeExtractor::findInputsOutputs(), llvm::SwitchCG::SwitchLowering::findJumpTables(), findTRECandidate(), findUnwindDestinations(), FitWeights(), llvm::AMDGPULibCalls::fold(), FoldCondBranchOnPHI(), FoldTwoEntryPHINode(), llvm::formLCSSAForInstructions(), llvm::gatherUnrollingPreferences(), generateUnsignedDivisionCode(), llvm::BlockAddress::get(), llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit(), llvm::IRPosition::getAttrs(), llvm::CallBase::getCaller(), getCommonReturnValue(), getComparePred(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), getDebugLocString(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), llvm::MemoryDependenceResults::getDependency(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getEstimatedNumberOfCaseClusters(), llvm::Trace::getFunction(), llvm::Instruction::getFunction(), llvm::ValueEnumerator::getGlobalBasicBlockID(), getInnermostLoopFor(), llvm::TargetLoweringBase::getIRStackGuard(), llvm::MemoryDependenceResults::getLoadLoadClobberFullWidthSize(), GetLocation(), llvm::ARMTTIImpl::getMemcpyCost(), getModule(), getParameterABIAttributes(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::getParent(), getParentPad(), getPointerOperands(), llvm::getPtrStride(), getReductionIntrinsic(), llvm::SCEVExpander::getRelatedExistingExpansion(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), getSignature(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), getSubprogram(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::ARMTTIImpl::getUnrollingPreferences(), getValueSymbolTable(), getVarName(), handleEndBlock(), HandleInlinedEHPad(), HandleInlinedLandingPad(), handlePhiDef(), hasProfileData(), hasSameExtUse(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::DivergenceAnalysis::inRegion(), insertCall(), llvm::insertDebugValuesForPHIs(), insertLifetimeMarkersSurroundingCall(), InsertSafepointPoll(), insertSinCosCall(), instrumentMaskedLoadOrStore(), llvm::isAllocaPromotable(), isCallPromotable(), llvm::CaptureTracker::isDereferenceableOrNull(), isDynamicConstant(), llvm::CodeExtractor::isEligible(), isExplicitVecOuterLoop(), llvm::SelectionDAGBuilder::isExportableFromCurrentBlock(), llvm::isInTailCallPosition(), isLoadConditional(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), IsMasked(), IsNonLocalValue(), isNotUsedOrFreeInLoop(), isNoWrap(), isObjectDereferencedInBlock(), isOnlyReachableViaThisEdge(), isPointerValueDeadOnEntryToFunction(), llvm::isPotentiallyReachable(), isPromotedInstructionLegal(), llvm::RecurrenceDescriptor::isReductionPHI(), isReportingError(), llvm::AllocaInst::isStaticAlloca(), llvm::TargetLoweringBase::isSuitableForJumpTable(), llvm::LoopVectorizationLegality::isUniform(), llvm::AMDGPULibCalls::isUnsafeMath(), isValidCandidateForColdCC(), isZero(), LLVMGetNextBasicBlock(), LLVMGetPreviousBasicBlock(), LLVMInsertBasicBlockInContext(), LLVMInsertExistingBasicBlockAfterInsertBlock(), llvm::BlockAddress::lookup(), llvm::CallLowering::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::ARMTargetLowering::makeDMB(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), llvm::SITargetLowering::mayBeEmittedAsTailCall(), maybeEndlessLoop(), maybePrintComdat(), mayLoopAccessLocation(), mayUsePostIncMode(), memoryIsNotModifiedBetween(), llvm::MergeBasicBlockIntoOnlyPred(), mergeCleanupPad(), moveAfter(), moveBefore(), moveLCSSAPhis(), needsRuntimeRegistrationOfSectionRange(), NegateValue(), optimizeSQRT(), llvm::peelLoop(), performMaskedAtomicOp(), placeSplitBlockCarefully(), populateWorklist(), llvm::PrepareToSplitEntryBlock(), llvm::LegacyDivergenceAnalysis::print(), llvm::MemoryDepChecker::Dependence::print(), llvm::Value::print(), printIRBlockReference(), llvm::JumpThreadingPass::ProcessBlock(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), promoteSingleBlockAlloca(), ReduceLoopStrength(), llvm::AssumptionCache::registerAssumption(), removeFromParent(), RemoveInstInputs(), removeUndefIntroducingPredecessor(), replaceAllUsesOfWithIn(), replaceConstantExprOp(), replaceExtractElements(), ReplaceUsesOfWith(), reportLoadElim(), RetagMask(), llvm::SSAUpdaterBulk::RewriteAllUses(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), RewriteUsesOfClonedInstructions(), llvm::IRCEPass::run(), llvm::LoopAccessInfoPrinterPass::run(), llvm::LoopRotatePass::run(), llvm::IndVarSimplifyPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::LoopCachePrinterPass::run(), llvm::DDGAnalysis::run(), llvm::Attributor::run(), llvm::IVUsersWrapperPass::runOnLoop(), scaleWeights(), llvm::IRBuilderBase::setConstrainedFPFunctionAttr(), llvm::setProfMetadata(), llvm::AArch64TTIImpl::shouldConsiderAddressTypePromotion(), shouldConvert(), llvm::ARMTTIImpl::shouldFavorBackedgeIndex(), ShrinkDemandedConstant(), SimplifyCondBranchToCondBranch(), SimplifyIndirectBrOnSelect(), simplifyLoopInst(), simplifyRelocatesOffABase(), sinkLoopInvariantInstructions(), llvm::sinkRegion(), llvm::LoopPass::skipLoop(), splitBasicBlock(), llvm::fuzzerop::splitBlockDescriptor(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SwitchToLookupTable(), llvm::JumpThreadingPass::ThreadEdge(), TryToMergeLandingPad(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), TypeSizeToSizeIndex(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), UpdateAnalysisInformation(), updateOperand(), useFuncSeen(), UseTlsOffset(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitLandingPadInst(), and ~BasicBlock().
getParent() [2/2]
Function* llvm::BasicBlock::getParent () inline
Definition at line 107 of file BasicBlock.h.
References getModule().
getSinglePredecessor() [1/2]
const BasicBlock * BasicBlock::getSinglePredecessor () const
Return the predecessor of this block if it has a single predecessor block.
If this basic block has a single predecessor block, return the block, otherwise return a null pointer.
Otherwise return a null pointer.
Definition at line 240 of file BasicBlock.cpp.
References E, llvm::pred_begin(), and llvm::pred_end().
Referenced by allPredecessorsComeFromSameSource(), assertBranchOrSelectConditionHoisted(), CanGenerateTest(), CanPropagatePredecessorsForPHIs(), CanProveNotTakenFirstIteration(), canSafelyUnrollMultiExitLoop(), llvm::CloneAndPruneIntoFromInst(), createCallInst(), llvm::createCodeGenPreparePass(), detectShiftUntilZeroIdiom(), llvm::DominatorTree::dominates(), llvm::VPlan::dump(), llvm::VPPredInstPHIRecipe::execute(), FindPHIForConditionForwarding(), FindWidenableTerminatorAboveLoop(), foldICmpWithDominatingICmp(), getFirstInsertionPt(), llvm::GetIfCondition(), getSinglePredecessor(), handlePhiDef(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), IsMasked(), isOnlyReachableViaThisEdge(), llvm::isValidAssumeForContext(), llvm::JumpThreadingPass::MaybeMergeBasicBlockIntoOnlyPred(), llvm::MergeBasicBlockIntoOnlyPred(), mergeBlocksIntoPredecessors(), mergeCleanupPad(), mergeConditionalStores(), mergeConditionalStoreToAddress(), llvm::JumpThreadingPass::ProcessGuards(), processUGT_ADDCST_ADD(), recordConditions(), ReduceSwitchRange(), removeUndefIntroducingPredecessor(), replaceAllUsesOfWithIn(), llvm::InstCombiner::replacedSelectWithOperand(), ReplaceUsesOfWith(), reportMayClobberedLoad(), llvm::SpeculativeExecutionPass::runImpl(), shouldInstrumentBlock(), shouldRotateLoopExitingLatch(), SimplifyIndirectBrOnSelect(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), simplifySuspendPoint(), llvm::SplitEdge(), tryToMoveFreeBeforeNullTest(), and tryWidenCondBranchToCondBranch().
getSinglePredecessor() [2/2]
BasicBlock* llvm::BasicBlock::getSinglePredecessor () inline
Definition at line 227 of file BasicBlock.h.
References getSinglePredecessor(), and getUniquePredecessor().
getSingleSuccessor() [1/2]
const BasicBlock * BasicBlock::getSingleSuccessor () const
Return the successor of this block if it has a single successor.
Otherwise return a null pointer.
This method is analogous to getSinglePredecessor above.
Definition at line 275 of file BasicBlock.cpp.
References E, SI, llvm::succ_begin(), and llvm::succ_end().
Referenced by llvm::createCodeGenPreparePass(), llvm::VPlan::dump(), ensureValueAvailableInSuccessor(), llvm::VPlan::execute(), FindWidenableTerminatorAboveLoop(), getSingleSuccessor(), getUniquePredecessor(), insertSpills(), mergeBlocksIntoPredecessors(), mergeConditionalStores(), llvm::SpeculativeExecutionPass::runImpl(), and llvm::sinkRegion().
getSingleSuccessor() [2/2]
BasicBlock* llvm::BasicBlock::getSingleSuccessor () inline
Definition at line 255 of file BasicBlock.h.
References getSingleSuccessor(), and getUniqueSuccessor().
getSublistAccess()
static InstListType BasicBlock::* llvm::BasicBlock::getSublistAccess (Instruction *) inline static
Returns a pointer to a member of the instruction list.
Definition at line 342 of file BasicBlock.h.
References getValueSymbolTable().
getTerminatingDeoptimizeCall() [1/2]
const CallInst * BasicBlock::getTerminatingDeoptimizeCall () const
Returns the call instruction calling @llvm.experimental.deoptimize prior to the terminating return instruction of this basic block, if such a call is present.
Otherwise, returns null.
Definition at line 181 of file BasicBlock.cpp.
References llvm::dyn_cast(), and F().
Referenced by llvm::canPeel(), findUnwindDestinations(), llvm::getLoopEstimatedTripCount(), getTerminatingDeoptimizeCall(), getTerminator(), llvm::InlineFunction(), isVeryLikelyToDeopt(), and tryWidenCondBranchToCondBranch().
getTerminatingDeoptimizeCall() [2/2]
CallInst* llvm::BasicBlock::getTerminatingDeoptimizeCall () inline
Definition at line 131 of file BasicBlock.h.
References getTerminatingDeoptimizeCall(), and getTerminatingMustTailCall().
getTerminatingMustTailCall() [1/2]
const CallInst * BasicBlock::getTerminatingMustTailCall () const
Returns the call instruction marked 'musttail' prior to the terminating return instruction of this basic block, if such a call is present.
Otherwise, returns null.
Definition at line 150 of file BasicBlock.cpp.
References llvm::dyn_cast(), llvm::User::getOperand(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), and llvm::ReturnInst::getReturnValue().
Referenced by getTerminatingDeoptimizeCall(), getTerminatingMustTailCall(), and llvm::InlineFunction().
getTerminatingMustTailCall() [2/2]
CallInst* llvm::BasicBlock::getTerminatingMustTailCall () inline
Definition at line 140 of file BasicBlock.h.
References getFirstNonPHI(), and getTerminatingMustTailCall().
getTerminator() [1/2]
const Instruction * BasicBlock::getTerminator () const
Returns the terminator instruction if the block is well formed or null if the block is not well formed.
Definition at line 144 of file BasicBlock.cpp.
Referenced by AddReachableCodeToWorklist(), allPredecessorsComeFromSameSource(), assertBranchOrSelectConditionHoisted(), llvm::LoopVectorizationLegality::blockNeedsPredication(), BrPHIToSelect(), llvm::CFGMST< Edge, BBInfo >::buildEdges(), canFoldIVIncExpr(), CanGenerateTest(), llvm::canPeel(), canRenameComdat(), canSinkInstructions(), canSplitPredecessors(), llvm::changeToUnreachable(), checkBasicSSA(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneFunction(), llvm::CloneFunctionInto(), CloneLoopBlocks(), cloneLoopBlocks(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::colorEHFunclets(), llvm::FunctionComparator::compare(), computeKnownBitsFromOperator(), ComputePostOrders(), llvm::ComputeSpeculationCost(), computeUnlikelySuccessors(), ConnectEpilog(), ConnectProlog(), llvm::ConstantFoldTerminator(), ConvertToSInt(), copyMustTailReturn(), createCallInst(), llvm::OpenMPIRBuilder::CreateCancel(), createCast(), llvm::createCodeGenPreparePass(), llvm::VPRecipeBuilder::createEdgeMask(), createFFSIntrinsic(), CreateGCRelocates(), llvm::createLICMPass(), llvm::createLowerSwitchPass(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), llvm::createObjCARCOptPass(), llvm::OpenMPIRBuilder::CreateParallel(), createPHIsForSplitLoopExit(), CreatePrologue(), createResumeEntryBlock(), createUnreachableSwitchDefault(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::VPBlockBase::deleteCFG(), llvm::DemotePHIToStack(), despeculateCountZeros(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), doCallSiteSplitting(), DominatesMergePoint(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), ehAwareSplitEdge(), eliminateDeadStores(), eliminateTailRecursion(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), llvm::InnerLoopVectorizer::emitSCEVChecks(), enableCallSafepoints(), EvaluateConstantChrecAtConstant(), llvm::Evaluator::EvaluateFunction(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPBasicBlock::execute(), llvm::VPlan::execute(), llvm::CodeExtractor::extractCodeRegion(), llvm::FastISel::fastEmitZExtFromI1(), findBasePointer(), llvm::orc::SpeculateQuery::findCalles(), findIBRPredecessor(), findInnerReductionPhi(), llvm::CodeExtractor::findInputsOutputs(), findInsertPointAfter(), FindMostPopularDest(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), FindPHIForConditionForwarding(), findUnconditionalPreds(), FindWidenableTerminatorAboveLoop(), FitWeights(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixLCSSAPHIs(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), FoldCondBranchOnPHI(), foldGuardedRotateToFunnelShift(), foldICmpWithDominatingICmp(), foldOperationIntoPhiValue(), foldReturnAndProcessPred(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), llvm::ScalarEvolution::forgetValue(), genericValueTraversal(), genLoopLimit(), GetBestDestForJumpOnUndef(), getBranchHint(), getBranchInsertPoint(), llvm::InnerLoopVectorizer::getBroadcastInstrs(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::DOTGraphTraits< const Function * >::getEdgeAttributes(), llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel(), getEdgeValueLocal(), getEHPadFromPredecessor(), llvm::GetIfCondition(), getInductionVariable(), getInnermostLoopFor(), getInsertPointForUses(), getIrrLoopHeaderWeight(), getJumpThreadDuplicationCost(), llvm::getLoopEstimatedTripCount(), llvm::Loop::getLoopGuardBranch(), getMaxBackedgeTakenCount(), getModule(), getNumBytes(), llvm::RegionTraits< Function >::getNumSuccessors(), getOnlyLiveSuccessor(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), getOutliningBenefit(), getOutliningPenalty(), getParentPad(), GetPointerOperand(), getSignature(), llvm::GetSuccessorNumber(), getSuccState(), getTerminator(), getVectorType(), handleFree(), handlePhiDef(), hasOnlyUniformBranches(), hasProfileData(), hasZeroSignBit(), hoist(), llvm::hoistAllInstructionsInto(), llvm::SCEVExpander::hoistIVInc(), llvm::hoistRegion(), INITIALIZE_PASS(), llvm::InlineFunction(), insertBoundsCheck(), llvm::DIBuilder::insertDeclare(), insertLifetimeMarkersSurroundingCall(), llvm::InsertPreheaderForLoop(), insertSpills(), insertUniqueBackedgeBlock(), inversePermutation(), is_empty(), IsAcceptableTarget(), isChainSelectCmpBranch(), llvm::CaptureTracker::isDereferenceableOrNull(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isIgnorableInst(), IsIncrementNUW(), llvm::isInTailCallPosition(), IsInterestingCmp(), isLegalToHoistInto(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isLoopDead(), isLoopExitTestBasedOn(), isNotUsedOrFreeInLoop(), isOnlyReachableViaThisEdge(), isProfitableForVectorization(), isPromotedInstructionLegal(), isSafeAndProfitableToSinkLoad(), isSafePHIToSpeculate(), llvm::isSafeToExpandAt(), llvm::BasicBlockEdge::isSingleEdge(), isUnconditionalBranch(), llvm::isUniformLoop(), isUniformlyReached(), makeBitReverse(), llvm::Loop::makeLoopInvariant(), MarkBlocksLiveIn(), matchPair(), llvm::JumpThreadingPass::MaybeMergeBasicBlockIntoOnlyPred(), mayLoopAccessLocation(), mayUsePostIncMode(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeCleanupPad(), mergeConditionalStoreToAddress(), mergeEmptyReturnBlocks(), moveBBContents(), moveLCSSAPhis(), llvm::MemorySSAUpdater::moveToPlace(), needsLFTR(), llvm::EscapeEnumerator::Next(), normalizePredicate(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeSQRT(), patchAndReplaceAllUsesWith(), llvm::peelLoop(), llvm::PHITransAddr::PHITranslateWithInsertion(), prepareForSplit(), llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), llvm::JumpThreadingPass::ProcessBlock(), ProcessBlock(), llvm::JumpThreadingPass::ProcessBranchOnPHI(), llvm::JumpThreadingPass::ProcessImpliedCondition(), processUGT_ADDCST_ADD(), llvm::promoteLoopAccessesToScalars(), llvm::GVNHoist::rank(), recordCondition(), relocationViaAlloca(), llvm::removeAllNonTerminatorAndEHPadInstructions(), llvm::MemorySSAUpdater::removeBlocks(), removeEmptyCleanup(), removeUndefIntroducingPredecessor(), llvm::removeUnwindEdge(), replaceAllUsesOfWithIn(), replaceConstantExprOp(), llvm::InstCombiner::replacedSelectWithOperand(), replaceSuccessorsPhiUsesWith(), reportMayClobberedLoad(), llvm::IRCEPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::Attributor::run(), llvm::SpeculativeExecutionPass::runImpl(), llvm::runIPSCCP(), llvm::MachinePipeliner::runOnMachineFunction(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), scaleWeights(), selectSGPRVectorRegClassID(), setBranchWeights(), shouldConvert(), llvm::StackProtector::shouldEmitSDCheck(), shouldRotateLoopExitingLatch(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), SimplifyIndirectBrOnSelect(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), SinkCast(), llvm::sinkRegion(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), SpeculativelyExecuteBB(), splitBasicBlock(), splitBeforeCatchSwitch(), llvm::fuzzerop::splitBlockDescriptor(), splitCallSite(), llvm::SplitCriticalEdge(), SplitCriticalSideEffectEdges(), llvm::SplitEdge(), llvm::SplitIndirectBrCriticalEdges(), llvm::SplitLandingPadPredecessors(), llvm::succ_begin(), llvm::succ_end(), ThreadCmpOverPHI(), llvm::JumpThreadingPass::ThreadEdge(), truncateIVUse(), llvm::JumpThreadingPass::TryThreadEdge(), tryToElideArgumentCopy(), TryToMergeLandingPad(), tryToMoveFreeBeforeNullTest(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSinkInstruction(), llvm::JumpThreadingPass::TryToUnfoldSelect(), tryUnmergingGEPsAcrossIndirectBr(), turnGuardIntoBranch(), turnToExplicitForm(), llvm::JumpThreadingPass::UnfoldSelectInstr(), unifyReturnBlockSet(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchAllTrivialConditions(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), llvm::MemorySSAUpdater::updateForClonedBlockIntoPred(), UpdatePDTWorklist(), updatePredecessorProfileMetadata(), llvm::LoopVersioning::versionLoop(), visitIVCast(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitStoreInst(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
getTerminator() [2/2]
Instruction* llvm::BasicBlock::getTerminator () inline
Definition at line 122 of file BasicBlock.h.
References getTerminatingDeoptimizeCall(), and getTerminator().
getUniquePredecessor() [1/2]
const BasicBlock * BasicBlock::getUniquePredecessor () const
Return the predecessor of this block if it has a unique predecessor block.
If this basic block has a unique predecessor block, return the block, otherwise return a null pointer.
Otherwise return a null pointer.
Note that unique predecessor doesn't mean single edge, there can be multiple edges from the unique predecessor to this block (for example a switch statement with multiple cases having the same destination).
Note that unique predecessor doesn't mean single edge, there can be multiple edges from the unique predecessor to this block (for example a switch statement with multiple cases having the same destination).
Definition at line 253 of file BasicBlock.cpp.
References E, llvm::pred_begin(), and llvm::pred_end().
Referenced by areOuterLoopExitPHIsSupported(), llvm::createCodeGenPreparePass(), llvm::OpenMPIRBuilder::CreateParallel(), findLocationForEntrySafepoint(), llvm::Loop::getLoopGuardBranch(), getSinglePredecessor(), getUniquePredecessor(), IsAcceptableTarget(), isDynamicConstant(), isZero(), makeStatepointExplicitImpl(), llvm::MergeBlockIntoPredecessor(), llvm::MemorySSAUpdater::moveAllAfterMergeBlocks(), moveLCSSAPhis(), normalizeForInvokeSafepoint(), reuseTableCompare(), llvm::Attributor::run(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
getUniquePredecessor() [2/2]
BasicBlock* llvm::BasicBlock::getUniquePredecessor () inline
Definition at line 239 of file BasicBlock.h.
References getSingleSuccessor(), getUniquePredecessor(), hasNPredecessors(), hasNPredecessorsOrMore(), and N.
getUniqueSuccessor() [1/2]
const BasicBlock * BasicBlock::getUniqueSuccessor () const
Return the successor of this block if it has a unique successor.
Otherwise return a null pointer.
This method is analogous to getUniquePredecessor above.
Definition at line 283 of file BasicBlock.cpp.
References E, SI, llvm::succ_begin(), and llvm::succ_end().
Referenced by llvm::OpenMPIRBuilder::CreateParallel(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::Loop::getLoopGuardBranch(), getSingleSuccessor(), getUniqueSuccessor(), IsBackEdge(), isVeryLikelyToDeopt(), llvm::MergeBlockIntoPredecessor(), moveLCSSAPhis(), and TryToMergeLandingPad().
getUniqueSuccessor() [2/2]
BasicBlock* llvm::BasicBlock::getUniqueSuccessor () inline
Definition at line 265 of file BasicBlock.h.
References getUniqueSuccessor().
getValueSymbolTable()
ValueSymbolTable * BasicBlock::getValueSymbolTable ()
Returns a pointer to the symbol table if one exists.
Definition at line 26 of file BasicBlock.cpp.
References F(), and getParent().
Referenced by getSublistAccess().
hasAddressTaken()
bool llvm::BasicBlock::hasAddressTaken () const inline
Returns true if there are any uses of this basic block other than direct branches, switches, etc.
to it.
Definition at line 396 of file BasicBlock.h.
References llvm::Value::getSubclassDataFromValue(), replacePhiUsesWith(), and replaceSuccessorsPhiUsesWith().
Referenced by llvm::CloneFunction(), llvm::CloneFunctionInto(), llvm::createCodeGenPreparePass(), despeculateCountZeros(), llvm::AsmPrinter::EmitBasicBlockStart(), foldReturnAndProcessPred(), llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit(), getSuccPad(), hasAddressTakenAndUsed(), isBlockValidForExtraction(), llvm::isSafeToUnrollAndJam(), llvm::BlockAddress::lookup(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::GVNHoist::rank(), llvm::IRTranslator::runOnMachineFunction(), llvm::UnrollLoop(), and ~BasicBlock().
hasNPredecessors()
bool BasicBlock::hasNPredecessors (unsigned N) const
Return true if this block has exactly N predecessors.
Definition at line 267 of file BasicBlock.cpp.
References llvm::hasNItems(), llvm::pred_begin(), and llvm::pred_end().
Referenced by ensureValueAvailableInSuccessor(), getUniquePredecessor(), llvm::InstCombiner::visitStoreInst(), and llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor().
hasNPredecessorsOrMore()
bool BasicBlock::hasNPredecessorsOrMore (unsigned N) const
Return true if this block has N predecessors or more.
Definition at line 271 of file BasicBlock.cpp.
References llvm::hasNItemsOrMore(), llvm::pred_begin(), and llvm::pred_end().
Referenced by getUniquePredecessor(), and TryToMergeLandingPad().
insertInto()
void BasicBlock::insertInto (Function * Parent, BasicBlock * InsertBefore = nullptr)
Insert unlinked basic block into a function.
Inserts an unlinked basic block into Parent. If InsertBefore is provided, inserts before that basic block, otherwise inserts at the end.
Precondition
getParent() is nullptr.
Definition at line 53 of file BasicBlock.cpp.
References assert(), llvm::Function::getBasicBlockList(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
Referenced by getContext(), and getFirstInsertionPt().
instructionsWithoutDebug() [1/2]
iterator_range< filter_iterator< BasicBlock::const_iterator, std::function< bool(const Instruction &)> > > BasicBlock::instructionsWithoutDebug () const
Return a const iterator range over the instructions in the block, skipping any debug instructions.
Definition at line 94 of file BasicBlock.cpp.
References I, and llvm::make_filter_range().
Referenced by allPredecessorsComeFromSameSource(), areOuterLoopExitPHIsSupported(), BlockIsSimpleEnoughToThreadThrough(), llvm::CodeExtractorAnalysisCache::CodeExtractorAnalysisCache(), llvm::orc::SpeculateQuery::findCalles(), findInnerReductionPhi(), GetCaseResults(), getFirstInsertionPt(), getOutliningBenefit(), hasProfileData(), isSafeToSpeculateStore(), mergeConditionalStoreToAddress(), llvm::LegacyDivergenceAnalysis::print(), and sizeWithoutDebug().
instructionsWithoutDebug() [2/2]
iterator_range< filter_iterator< BasicBlock::iterator, std::function< bool(Instruction &)> > > BasicBlock::instructionsWithoutDebug ()
Return an iterator range over the instructions in the block, skipping any debug instructions.
Definition at line 103 of file BasicBlock.cpp.
References I, and llvm::make_filter_range().
isEHPad()
bool llvm::BasicBlock::isEHPad () const inline
Return true if this basic block is an exception handling block.
Definition at line 411 of file BasicBlock.h.
References getFirstNonPHI(), getLandingPadInst(), llvm::Instruction::isEHPad(), and isLandingPad().
Referenced by calculateCXXStateNumbers(), calculateSEHStateNumbers(), llvm::calculateWasmEHInfo(), canSplitCallSite(), eraseDeadBBsAndChildren(), getParameterABIAttributes(), getPredState(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::GVNHoist::rank(), separateNestedLoop(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), llvm::fuzzerop::splitBlockDescriptor(), and llvm::SplitCriticalEdge().
isLandingPad()
bool BasicBlock::isLandingPad () const
Return true if this basic block is a landing pad.
Being a ``landing pad'' means that the basic block is the destination of the 'unwind' edge of an invoke instruction.
I.e., it's the destination of the 'unwind' edge of an invoke instruction.
Definition at line 470 of file BasicBlock.cpp.
References getFirstNonPHI().
Referenced by createPHIsForSplitLoopExit(), isEHPad(), mayUsePostIncMode(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), and llvm::JumpThreadingPass::ThreadEdge().
isLegalToHoistInto()
bool BasicBlock::isLegalToHoistInto () const
Return true if it is legal to hoist instructions into this block.
Definition at line 390 of file BasicBlock.cpp.
References assert(), and getTerminator().
Referenced by getLandingPadInst().
moveAfter()
void BasicBlock::moveAfter (BasicBlock * MovePos)
Unlink this basic block from its current function and insert it right after MovePos in the function MovePos lives in.
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right after MovePos.
Definition at line 134 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), llvm::ilist_node_impl< ilist_detail::compute_node_options< BasicBlock, Options... >::type >::getIterator(), llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::splice().
Referenced by CreatePrologue(), getFirstInsertionPt(), llvm::MergeBasicBlockIntoOnlyPred(), placeSplitBlockCarefully(), and llvm::JumpThreadingPass::ThreadEdge().
moveBefore()
void BasicBlock::moveBefore (BasicBlock * MovePos)
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
Definition at line 127 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), llvm::ilist_node_impl< ilist_detail::compute_node_options< BasicBlock, Options... >::type >::getIterator(), llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::splice().
Referenced by buildClonedLoopBlocks(), llvm::OpenMPIRBuilder::CreateParallel(), getFirstInsertionPt(), mayUsePostIncMode(), shouldRotateLoopExitingLatch(), and llvm::sinkRegion().
operator=()
BasicBlock& llvm::BasicBlock::operator= (const BasicBlock &) delete
phis() [1/2]
iterator_range<const_phi_iterator> llvm::BasicBlock::phis () const inline
Returns a range that iterates over the phis in the basic block.
Note that this cannot be used with basic blocks that have no terminator.
Definition at line 329 of file BasicBlock.h.
Referenced by AddPHINodeEntriesForMappedBlock(), AddPredecessorToBlock(), areInnerLoopExitPHIsSupported(), areOuterLoopExitPHIsSupported(), assertBranchOrSelectConditionHoisted(), llvm::canIfConvertPHINodes(), ConnectEpilog(), ConvertToSInt(), llvm::createCodeGenPreparePass(), createPHIsForSplitLoopExit(), llvm::DeleteDeadPHIs(), deleteLoopIfDead(), llvm::GVNExpression::Expression::dump(), llvm::FastISel::fastEmitZExtFromI1(), findInnerReductionPhi(), FindPHIForConditionForwarding(), llvm::InnerLoopVectorizer::fixCrossIterationPHIs(), llvm::InnerLoopVectorizer::fixLCSSAPHIs(), llvm::InnerLoopVectorizer::fixReduction(), fixupPHINodeForNormalDest(), fixupPHINodeForUnwindDest(), ForwardSwitchConditionToPHI(), llvm::Loop::getInductionVariable(), getMaxBackedgeTakenCount(), getOtherIncomingValue(), GetPointerOperand(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::DivergenceAnalysis::inRegion(), isEpilogProfitable(), isExistingPhi(), IsIncrementNUW(), isKnownTypeIdMember(), isLoopDead(), isProfitableChain(), llvm::LoopVectorizationLegality::isUniform(), llvm::MergeBlockIntoPredecessor(), moveLCSSAPhis(), processHeaderPhiOperands(), PushLoopPHIs(), removeUndefIntroducingPredecessor(), replaceAllUsesOfWithIn(), llvm::SCEVExpander::replaceCongruentIVs(), rewritePHINodesForExitAndUnswitchedBlocks(), rewritePHINodesForUnswitchedExitBlock(), scaleWeights(), scanPHIsAndUpdateValueMap(), shouldRotateLoopExitingLatch(), simplifyTerminatorLeadingToRet(), SpeculativelyExecuteBB(), llvm::fuzzerop::splitBlockDescriptor(), splitCallSite(), tryToElideArgumentCopy(), tryWidenCondBranchToCondBranch(), and llvm::UnrollAndJamLoop().
phis() [2/2]
iterator_range< BasicBlock::phi_iterator > BasicBlock::phis ()
Definition at line 297 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), empty(), and P.
rbegin() [1/2]
reverse_iterator llvm::BasicBlock::rbegin () inline
Definition at line 278 of file BasicBlock.h.
Referenced by checkForMustTailInVarArgFn(), findLiveSetAtInst(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), isIgnorableInst(), llvm::moveInstsBottomUp(), patchAndReplaceAllUsesWith(), shouldRotateLoopExitingLatch(), and sinkLoopInvariantInstructions().
rbegin() [2/2]
const_reverse_iterator llvm::BasicBlock::rbegin () const inline
Definition at line 279 of file BasicBlock.h.
removeFromParent()
void BasicBlock::removeFromParent ()
Unlink 'this' from the containing function, but do not delete it.
Definition at line 117 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), llvm::ilist_node_impl< ilist_detail::compute_node_options< BasicBlock, Options... >::type >::getIterator(), getParent(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by llvm::DomTreeUpdater::callbackDeleteBB(), llvm::DomTreeUpdater::deleteBB(), and getFirstInsertionPt().
removePredecessor()
void BasicBlock::removePredecessor (BasicBlock * Pred, bool KeepOneInputPHIs = false)
Notify the BasicBlock that the predecessor Pred is no longer able to reach it.
This method is used to notify a BasicBlock that the specified Predecessor of the block is no longer able to reach it.
This is actually not used to update the Predecessor list, but is actually used to update the PHI nodes that reside in the block. Note that this should be called while the predecessor still refers to this block.
Definition at line 308 of file BasicBlock.cpp.
References assert(), begin(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::find(), front(), llvm::UndefValue::get(), llvm::PHINode::getIncomingBlock(), getInstList(), llvm::PHINode::getNumIncomingValues(), llvm::PHINode::hasConstantValue(), llvm::Value::hasNUsesOrMore(), llvm::Other, llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_front(), llvm::pred_begin(), llvm::pred_end(), llvm::PHINode::removeIncomingValue(), and llvm::Value::replaceAllUsesWith().
Referenced by llvm::changeToCall(), classof(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), FitWeights(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), HandleInlinedLandingPad(), markAliveBlocks(), llvm::JumpThreadingPass::ProcessBlock(), llvm::RemovePredecessorAndSimplify(), RemoveSwitchAfterSelectConversion(), removeUndefIntroducingPredecessor(), llvm::removeUnwindEdge(), replaceConditionalBranchesOnConstant(), setBranchWeights(), shouldRotateLoopExitingLatch(), SimplifyCondBranchToTwoReturns(), llvm::SplitCriticalEdge(), SwitchToLookupTable(), llvm::JumpThreadingPass::ThreadEdge(), tryWidenCondBranchToCondBranch(), and unswitchTrivialSwitch().
rend() [1/2]
reverse_iterator llvm::BasicBlock::rend () inline
Definition at line 280 of file BasicBlock.h.
Referenced by checkForMustTailInVarArgFn(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), isIgnorableInst(), llvm::moveInstsBottomUp(), patchAndReplaceAllUsesWith(), shouldRotateLoopExitingLatch(), sinkLoopInvariantInstructions(), and splitCallSite().
rend() [2/2]
const_reverse_iterator llvm::BasicBlock::rend () const inline
Definition at line 281 of file BasicBlock.h.
replacePhiUsesWith()
void BasicBlock::replacePhiUsesWith (BasicBlock * Old, BasicBlock * New)
Update all phi nodes in this basic block to refer to basic block New instead of basic block Old.
Definition at line 441 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), end(), llvm::ARM_PROC::IE, and llvm::PHINode::replaceIncomingBlockWith().
Referenced by hasAddressTaken(), moveLCSSAPhis(), replaceSuccessorsPhiUsesWith(), and scaleWeights().
replaceSuccessorsPhiUsesWith() [1/2]
void BasicBlock::replaceSuccessorsPhiUsesWith (BasicBlock * Old, BasicBlock * New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of basic block Old.
Definition at line 452 of file BasicBlock.cpp.
References llvm::for_each(), getTerminator(), replacePhiUsesWith(), and llvm::successors().
Referenced by hasAddressTaken(), and replaceSuccessorsPhiUsesWith().
replaceSuccessorsPhiUsesWith() [2/2]
void BasicBlock::replaceSuccessorsPhiUsesWith (BasicBlock * New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of to it.
Definition at line 464 of file BasicBlock.cpp.
References replaceSuccessorsPhiUsesWith().
size()
size_t llvm::BasicBlock::size () const inline
Definition at line 283 of file BasicBlock.h.
Referenced by canCreateThunkFor(), llvm::OpenMPIRBuilder::CreateParallel(), detectShiftUntilZeroIdiom(), FitWeights(), getSignature(), llvm::SpeculativeExecutionPass::runImpl(), tryToMoveFreeBeforeNullTest(), and unswitchTrivialSwitch().
sizeWithoutDebug()
filter_iterator< BasicBlock::const_iterator, std::function< bool(const Instruction &)> >::difference_type BasicBlock::sizeWithoutDebug () const
Return the size of the basic block ignoring debug instructions.
Definition at line 112 of file BasicBlock.cpp.
References begin(), end(), and instructionsWithoutDebug().
Referenced by getFirstInsertionPt().
splitBasicBlock() [1/2]
BasicBlock * BasicBlock::splitBasicBlock (iterator I, const Twine & BBName = "")
Split the basic block into two basic blocks at the specified instruction.
This splits a basic block into two at the specified instruction.
Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the original BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. The newly formed BasicBlock is returned. This function invalidates the specified iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Also note that this doesn't preserve any passes. To split blocks while keeping loop information consistent, use the SplitBlock utility function.
Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the new BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. This invalidates the iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Definition at line 414 of file BasicBlock.cpp.
References assert(), Create(), llvm::BranchInst::Create(), end(), getContext(), getInstList(), llvm::ilist_node_with_parent< BasicBlock, Function >::getNextNode(), getParent(), getTerminator(), I, and llvm::Instruction::setDebugLoc().
Referenced by llvm::changeToInvokeAndSplitBasicBlock(), classof(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), llvm::OpenMPIRBuilder::CreateParallel(), CreatePrologue(), createResumeEntryBlock(), despeculateCountZeros(), llvm::VPlan::execute(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), INITIALIZE_PASS(), llvm::InlineFunction(), insertBoundsCheck(), insertSpills(), performMaskedAtomicOp(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), shouldKeepInEntry(), splitBasicBlock(), splitBeforeCatchSwitch(), llvm::SplitBlock(), llvm::fuzzerop::splitBlockDescriptor(), and unifyReturnBlockSet().
splitBasicBlock() [2/2]
BasicBlock* llvm::BasicBlock::splitBasicBlock (Instruction * I, const Twine & BBName = "") inline
Definition at line 390 of file BasicBlock.h.
References llvm::ilist_node_impl< OptionsT >::getIterator(), and splitBasicBlock().
Friends And Related Function Documentation
BlockAddress
friend class BlockAddress friend
Definition at line 63 of file BasicBlock.h.
SymbolTableListTraits< BasicBlock >
friend class SymbolTableListTraits< BasicBlock > friend
Definition at line 64 of file BasicBlock.h.
The documentation for this class was generated from the following files:
include/llvm/IR/BasicBlock.h
lib/IR/BasicBlock.cpp