LLVM: llvm::codeview::DebugInlineeLinesSubsectionRef Class Reference
llvm::codeview::DebugInlineeLinesSubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h"
Public Member Functions
DebugInlineeLinesSubsectionRef ()
Error initialize (BinaryStreamReader Reader)
Error initialize (BinaryStreamRef Section)
bool valid () const
bool hasExtraFiles () const
Iterator begin () const
Iterator end () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 61 of file DebugInlineeLinesSubsection.h.
Constructor & Destructor Documentation
DebugInlineeLinesSubsectionRef()
DebugInlineeLinesSubsectionRef::DebugInlineeLinesSubsectionRef ()
Definition at line 42 of file DebugInlineeLinesSubsection.cpp.
References llvm::codeview::InlineeLines.
Member Function Documentation
begin()
Iterator llvm::codeview::DebugInlineeLinesSubsectionRef::begin () const inline
Definition at line 80 of file DebugInlineeLinesSubsection.h.
References llvm::codeview::Lines.
classof()
static bool llvm::codeview::DebugInlineeLinesSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 68 of file DebugInlineeLinesSubsection.h.
References initialize(), llvm::codeview::InlineeLines, and llvm::codeview::DebugSubsectionRef::kind().
end()
Iterator llvm::codeview::DebugInlineeLinesSubsectionRef::end () const inline
Definition at line 81 of file DebugInlineeLinesSubsection.h.
References llvm::codeview::Lines.
hasExtraFiles()
bool DebugInlineeLinesSubsectionRef::hasExtraFiles () const
Definition at line 57 of file DebugInlineeLinesSubsection.cpp.
References llvm::codeview::ExtraFiles.
Referenced by initialize().
initialize() [1/2]
Error DebugInlineeLinesSubsectionRef::initialize (BinaryStreamReader Reader)
Definition at line 45 of file DebugInlineeLinesSubsection.cpp.
References assert(), llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::EC, llvm::VarStreamArray< ValueType, Extractor >::getExtractor(), hasExtraFiles(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readEnum(), and llvm::Error::success().
Referenced by llvm::codeview::visitDebugSubsection().
initialize() [2/2]
Error llvm::codeview::DebugInlineeLinesSubsectionRef::initialize (BinaryStreamRef Section) inline
Definition at line 73 of file DebugInlineeLinesSubsection.h.
References initialize().
valid()
bool llvm::codeview::DebugInlineeLinesSubsectionRef::valid () const inline
Definition at line 77 of file DebugInlineeLinesSubsection.h.
References llvm::codeview::Lines.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h
lib/DebugInfo/CodeView/DebugInlineeLinesSubsection.cpp