LLVM: llvm::codeview::TypeDumpVisitor Class Reference
llvm::codeview::TypeDumpVisitor Class Reference
Dumper for CodeView type streams found in COFF object files and PDB files.
#include "llvm/DebugInfo/CodeView/TypeDumpVisitor.h"
Public Member Functions
TypeDumpVisitor (TypeCollection &TpiTypes, ScopedPrinter *W, bool PrintRecordBytes)
void setIpiTypes (TypeCollection &Types)
When dumping types from an IPI stream in a PDB, a type index may refer to a type or an item ID.
void printTypeIndex (StringRef FieldName, TypeIndex TI) const
void printItemIndex (StringRef FieldName, TypeIndex TI) const
Error visitUnknownType (CVType &Record) override
Action to take on unknown types. By default, they are ignored.
Error visitUnknownMember (CVMemberRecord &Record) override
Error visitTypeBegin (CVType &Record) override
Paired begin/end actions for all types.
Error visitTypeBegin (CVType &Record, TypeIndex Index) override
Error visitTypeEnd (CVType &Record) override
Error visitMemberBegin (CVMemberRecord &Record) override
Error visitMemberEnd (CVMemberRecord &Record) override
Public Member Functions inherited from llvm::codeview::TypeVisitorCallbacks
virtual ~TypeVisitorCallbacks ()=default
Detailed Description
Dumper for CodeView type streams found in COFF object files and PDB files.
Definition at line 26 of file TypeDumpVisitor.h.
Constructor & Destructor Documentation
TypeDumpVisitor()
llvm::codeview::TypeDumpVisitor::TypeDumpVisitor (TypeCollection & TpiTypes, ScopedPrinter * W, bool PrintRecordBytes) inline
Definition at line 28 of file TypeDumpVisitor.h.
Member Function Documentation
printItemIndex()
void TypeDumpVisitor::printItemIndex (StringRef FieldName, TypeIndex TI) const
Definition at line 165 of file TypeDumpVisitor.cpp.
References llvm::codeview::printTypeIndex().
Referenced by setIpiTypes(), and visitMemberEnd().
printTypeIndex()
void TypeDumpVisitor::printTypeIndex (StringRef FieldName, TypeIndex TI) const
Definition at line 161 of file TypeDumpVisitor.cpp.
References llvm::codeview::printTypeIndex().
Referenced by setIpiTypes(), visitMemberEnd(), and visitUnknownType().
setIpiTypes()
void llvm::codeview::TypeDumpVisitor::setIpiTypes (TypeCollection & Types) inline
When dumping types from an IPI stream in a PDB, a type index may refer to a type or an item ID.
The dumper will lookup the "name" of the index in the item database if appropriate. If ItemDB is null, it will use TypeDB, which is correct when dumping types from an object file (/Z7).
Definition at line 36 of file TypeDumpVisitor.h.
References printItemIndex(), printTypeIndex(), visitMemberBegin(), visitMemberEnd(), visitTypeBegin(), visitTypeEnd(), visitUnknownMember(), and visitUnknownType().
visitMemberBegin()
Error TypeDumpVisitor::visitMemberBegin (CVMemberRecord & Record) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 192 of file TypeDumpVisitor.cpp.
References getLeafTypeName(), llvm::ScopedPrinter::getOStream(), llvm::ScopedPrinter::indent(), llvm::codeview::CVMemberRecord::Kind, llvm::makeArrayRef(), llvm::ScopedPrinter::printEnum(), llvm::ScopedPrinter::startLine(), and llvm::Error::success().
Referenced by setIpiTypes().
visitMemberEnd()
Error TypeDumpVisitor::visitMemberEnd (CVMemberRecord & Record) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 201 of file TypeDumpVisitor.cpp.
References Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, Arguments, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::codeview::CVMemberRecord::Data, llvm::codeview::FieldListRecord::Data, llvm::codeview::EC, llvm::codeview::FieldList, llvm::formatv(), llvm::codeview::MemberAttributes::getAccess(), llvm::codeview::TypeServer2Record::getAge(), llvm::codeview::BuildInfoRecord::getArgs(), llvm::codeview::ProcedureRecord::getArgumentList(), llvm::codeview::MemberFunctionRecord::getArgumentList(), llvm::codeview::BitFieldRecord::getBitOffset(), llvm::codeview::BitFieldRecord::getBitSize(), llvm::codeview::getBytesAsCharacters(), llvm::codeview::ProcedureRecord::getCallConv(), llvm::codeview::MemberFunctionRecord::getCallConv(), llvm::codeview::MemberFunctionRecord::getClassType(), llvm::codeview::MemberFuncIdRecord::getClassType(), llvm::codeview::VFTableRecord::getCompleteClass(), llvm::codeview::MemberPointerInfo::getContainingType(), llvm::codeview::ClassRecord::getDerivationList(), llvm::codeview::ArrayRecord::getElementType(), llvm::codeview::VFTableShapeRecord::getEntryCount(), llvm::codeview::TagRecord::getFieldList(), llvm::codeview::MemberAttributes::getFlags(), llvm::codeview::MemberFuncIdRecord::getFunctionType(), llvm::codeview::FuncIdRecord::getFunctionType(), llvm::codeview::TypeServer2Record::getGuid(), llvm::codeview::StringIdRecord::getId(), llvm::codeview::ArrayRecord::getIndexType(), llvm::codeview::ArgListRecord::getIndices(), llvm::codeview::StringListRecord::getIndices(), llvm::codeview::UdtSourceLineRecord::getLineNumber(), llvm::codeview::UdtModSourceLineRecord::getLineNumber(), llvm::codeview::TagRecord::getMemberCount(), llvm::codeview::PointerRecord::getMemberInfo(), llvm::codeview::MemberAttributes::getMethodKind(), llvm::codeview::VFTableRecord::getMethodNames(), llvm::codeview::MethodOverloadListRecord::getMethods(), llvm::codeview::PointerRecord::getMode(), llvm::codeview::ModifierRecord::getModifiedType(), llvm::codeview::ModifierRecord::getModifiers(), llvm::codeview::UdtModSourceLineRecord::getModule(), llvm::codeview::MemberFuncIdRecord::getName(), llvm::codeview::ArrayRecord::getName(), llvm::codeview::TagRecord::getName(), llvm::codeview::TypeServer2Record::getName(), llvm::codeview::FuncIdRecord::getName(), llvm::codeview::VFTableRecord::getName(), llvm::codeview::ProcedureRecord::getOptions(), llvm::codeview::MemberFunctionRecord::getOptions(), llvm::codeview::TagRecord::getOptions(), llvm::codeview::VFTableRecord::getOverriddenVTable(), llvm::codeview::ProcedureRecord::getParameterCount(), llvm::codeview::MemberFunctionRecord::getParameterCount(), llvm::codeview::FuncIdRecord::getParentScope(), llvm::codeview::PointerRecord::getPointerKind(), llvm::codeview::PointerRecord::getReferentType(), llvm::codeview::MemberPointerInfo::getRepresentation(), llvm::codeview::ProcedureRecord::getReturnType(), llvm::codeview::MemberFunctionRecord::getReturnType(), llvm::codeview::PointerRecord::getSize(), llvm::codeview::ArrayRecord::getSize(), llvm::codeview::ClassRecord::getSize(), llvm::codeview::UnionRecord::getSize(), llvm::codeview::UdtSourceLineRecord::getSourceFile(), llvm::codeview::UdtModSourceLineRecord::getSourceFile(), llvm::codeview::StringIdRecord::getString(), llvm::codeview::MemberFunctionRecord::getThisPointerAdjustment(), llvm::codeview::MemberFunctionRecord::getThisType(), llvm::codeview::BitFieldRecord::getType(), llvm::codeview::UdtSourceLineRecord::getUDT(), llvm::codeview::UdtModSourceLineRecord::getUDT(), llvm::codeview::EnumRecord::getUnderlyingType(), llvm::codeview::TagRecord::getUniqueName(), llvm::codeview::VFTableRecord::getVFPtrOffset(), llvm::codeview::ClassRecord::getVTableShape(), llvm::codeview::HasUniqueName, I, llvm::codeview::PointerRecord::isConst(), llvm::codeview::PointerRecord::isFlat(), llvm::codeview::PointerRecord::isLValueReferenceThisPtr(), llvm::codeview::PointerRecord::isPointerToMember(), llvm::codeview::PointerRecord::isRestrict(), llvm::codeview::PointerRecord::isRValueReferenceThisPtr(), llvm::codeview::PointerRecord::isUnaligned(), llvm::codeview::PointerRecord::isVolatile(), llvm::makeArrayRef(), MI, llvm::Mod, N, llvm::codeview::None, llvm::ScopedPrinter::printBinaryBlock(), llvm::ScopedPrinter::printEnum(), llvm::ScopedPrinter::printFlags(), llvm::ScopedPrinter::printHex(), printItemIndex(), llvm::ScopedPrinter::printNumber(), llvm::ScopedPrinter::printString(), printTypeIndex(), Size, llvm::ScopedPrinter::startLine(), llvm::Error::success(), llvm::ScopedPrinter::unindent(), llvm::codeview::Vanilla, visitKnownRecord(), and llvm::codeview::visitMemberRecordStream().
Referenced by setIpiTypes().
visitTypeBegin() [1/2]
Error TypeDumpVisitor::visitTypeBegin (CVType & Record) override virtual
Paired begin/end actions for all types.
Receives all record data, including the fixed-length record prefix.
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 169 of file TypeDumpVisitor.cpp.
References llvm::codeview::TypeIndex::fromArrayIndex(), and llvm::codeview::TypeCollection::size().
Referenced by setIpiTypes().
visitTypeBegin() [2/2]
Error TypeDumpVisitor::visitTypeBegin (CVType & Record, TypeIndex Index) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 173 of file TypeDumpVisitor.cpp.
References llvm::codeview::TypeIndex::getIndex(), getLeafTypeName(), llvm::ScopedPrinter::getOStream(), llvm::ScopedPrinter::indent(), llvm::codeview::CVRecord< Kind >::kind(), llvm::makeArrayRef(), llvm::ScopedPrinter::printEnum(), llvm::ScopedPrinter::startLine(), and llvm::Error::success().
visitTypeEnd()
Error TypeDumpVisitor::visitTypeEnd (CVType & Record) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 183 of file TypeDumpVisitor.cpp.
References llvm::codeview::CVRecord< Kind >::content(), llvm::codeview::getBytesAsCharacters(), llvm::ScopedPrinter::printBinaryBlock(), llvm::ScopedPrinter::startLine(), llvm::Error::success(), and llvm::ScopedPrinter::unindent().
Referenced by setIpiTypes().
visitUnknownMember()
Error TypeDumpVisitor::visitUnknownMember (CVMemberRecord & Record) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 454 of file TypeDumpVisitor.cpp.
References llvm::codeview::CVMemberRecord::Kind, llvm::ScopedPrinter::printHex(), and llvm::Error::success().
Referenced by setIpiTypes().
visitUnknownType()
Error TypeDumpVisitor::visitUnknownType (CVType & Record) override virtual
Action to take on unknown types. By default, they are ignored.
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 459 of file TypeDumpVisitor.cpp.
References llvm::codeview::CVRecord< Kind >::content(), llvm::tgtok::Field, llvm::codeview::OneMethodRecord::getAccess(), llvm::codeview::DataMemberRecord::getAccess(), llvm::codeview::StaticDataMemberRecord::getAccess(), llvm::codeview::EnumeratorRecord::getAccess(), llvm::codeview::BaseClassRecord::getAccess(), llvm::codeview::VirtualBaseClassRecord::getAccess(), llvm::codeview::BaseClassRecord::getBaseOffset(), llvm::codeview::BaseClassRecord::getBaseType(), llvm::codeview::VirtualBaseClassRecord::getBaseType(), llvm::codeview::ListContinuationRecord::getContinuationIndex(), llvm::codeview::DataMemberRecord::getFieldOffset(), llvm::codeview::OneMethodRecord::getMethodKind(), llvm::codeview::OverloadedMethodRecord::getMethodList(), llvm::codeview::NestedTypeRecord::getName(), llvm::codeview::OneMethodRecord::getName(), llvm::codeview::OverloadedMethodRecord::getName(), llvm::codeview::DataMemberRecord::getName(), llvm::codeview::StaticDataMemberRecord::getName(), llvm::codeview::EnumeratorRecord::getName(), llvm::codeview::NestedTypeRecord::getNestedType(), llvm::codeview::OverloadedMethodRecord::getNumOverloads(), llvm::codeview::OneMethodRecord::getOptions(), llvm::codeview::PrecompRecord::getPrecompFilePath(), llvm::codeview::PrecompRecord::getSignature(), llvm::codeview::EndPrecompRecord::getSignature(), llvm::codeview::PrecompRecord::getStartTypeIndex(), llvm::codeview::OneMethodRecord::getType(), llvm::codeview::DataMemberRecord::getType(), llvm::codeview::StaticDataMemberRecord::getType(), llvm::codeview::VFPtrRecord::getType(), llvm::codeview::PrecompRecord::getTypesCount(), llvm::codeview::EnumeratorRecord::getValue(), llvm::codeview::VirtualBaseClassRecord::getVBPtrOffset(), llvm::codeview::VirtualBaseClassRecord::getVBPtrType(), llvm::codeview::OneMethodRecord::getVFTableOffset(), llvm::codeview::VirtualBaseClassRecord::getVTableIndex(), llvm::codeview::OneMethodRecord::isIntroducingVirtual(), llvm::codeview::CVRecord< Kind >::kind(), llvm::makeArrayRef(), llvm::codeview::LabelRecord::Mode, llvm::codeview::Nested, llvm::codeview::None, llvm::ScopedPrinter::printEnum(), llvm::ScopedPrinter::printHex(), llvm::ScopedPrinter::printNumber(), llvm::ScopedPrinter::printString(), printTypeIndex(), llvm::ArrayRef< T >::size(), llvm::Error::success(), llvm::codeview::Vanilla, visitKnownMember(), and visitKnownRecord().
Referenced by setIpiTypes().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/TypeDumpVisitor.h
lib/DebugInfo/CodeView/TypeDumpVisitor.cpp