LLVM: llvm::legacy::PassManagerBase Class Reference
llvm::legacy::PassManagerBase Class Reference abstract
PassManagerBase - An abstract interface to allow code to add passes to a pass manager without having to hard-code what kind of pass manager it is.
#include "llvm/IR/LegacyPassManager.h"
Public Member Functions
virtual ~PassManagerBase ()
virtual void add (Pass *P)=0
Add a pass to the queue of passes to run.
Detailed Description
PassManagerBase - An abstract interface to allow code to add passes to a pass manager without having to hard-code what kind of pass manager it is.
Definition at line 35 of file LegacyPassManager.h.
Constructor & Destructor Documentation
~PassManagerBase()
PassManagerBase::~PassManagerBase () virtual
Definition at line 1817 of file LegacyPassManager.cpp.
Member Function Documentation
add()
virtual void llvm::legacy::PassManagerBase::add (Pass * P) pure virtual
Add a pass to the queue of passes to run.
This passes ownership of the Pass to the PassManager. When the PassManager is destroyed, the pass will be destroyed as well, so there is no need to delete the pass. This may even destroy the pass right away if it is found to be redundant. This implies that all passes MUST be allocated with 'new'.
Implemented in llvm::legacy::FunctionPassManager, and llvm::legacy::PassManager.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), addCoroutineEarlyPasses(), addCoroutineOpt0Passes(), addCoroutineOptimizerLastPasses(), addCoroutineScalarOptimizerPasses(), addCoroutineSCCPasses(), llvm::PassManagerBuilder::addExtension(), llvm::TargetPassConfig::addPass(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), addPassesToGenerateCode(), llvm::TargetPassConfig::addPrintPass(), llvm::TargetPassConfig::addVerifyPass(), llvm::HexagonTargetMachine::adjustPassManager(), llvm::AMDGPUTargetMachine::adjustPassManager(), llvm::NVPTXTargetMachine::adjustPassManager(), llvm::PassManagerBuilder::populateFunctionPassManager(), llvm::PassManagerBuilder::populateLTOPassManager(), llvm::PassManagerBuilder::populateModulePassManager(), and llvm::PassManagerBuilder::populateThinLTOPassManager().
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassManager.h
lib/IR/LegacyPassManager.cpp