LLVM: llvm::MCXCOFFObjectTargetWriter Class Reference
llvm::MCXCOFFObjectTargetWriter Class Reference
#include "llvm/MC/MCXCOFFObjectWriter.h"
Public Member Functions
~MCXCOFFObjectTargetWriter () override
Triple::ObjectFormatType getFormat () const override
bool is64Bit () const
Public Member Functions inherited from llvm::MCObjectTargetWriter
virtual ~MCObjectTargetWriter ()=default
Static Public Member Functions
static bool classof (const MCObjectTargetWriter *W)
Protected Member Functions
MCXCOFFObjectTargetWriter (bool Is64Bit)
Detailed Description
Definition at line 18 of file MCXCOFFObjectWriter.h.
Constructor & Destructor Documentation
MCXCOFFObjectTargetWriter()
MCXCOFFObjectTargetWriter::MCXCOFFObjectTargetWriter (bool Is64Bit) protected
Definition at line 13 of file MCXCOFFObjectTargetWriter.cpp.
References ~MCXCOFFObjectTargetWriter().
~MCXCOFFObjectTargetWriter()
MCXCOFFObjectTargetWriter::~MCXCOFFObjectTargetWriter () override default
Referenced by MCXCOFFObjectTargetWriter().
Member Function Documentation
classof()
static bool llvm::MCXCOFFObjectTargetWriter::classof (const MCObjectTargetWriter * W) inline static
Definition at line 26 of file MCXCOFFObjectWriter.h.
References llvm::MCObjectTargetWriter::getFormat(), and llvm::Triple::XCOFF.
getFormat()
Triple::ObjectFormatType llvm::MCXCOFFObjectTargetWriter::getFormat () const inline override virtual
Implements llvm::MCObjectTargetWriter.
Definition at line 25 of file MCXCOFFObjectWriter.h.
References llvm::Triple::XCOFF.
is64Bit()
bool llvm::MCXCOFFObjectTargetWriter::is64Bit () const inline
Definition at line 29 of file MCXCOFFObjectWriter.h.
References llvm::createXCOFFObjectWriter().
The documentation for this class was generated from the following files:
include/llvm/MC/MCXCOFFObjectWriter.h
lib/MC/MCXCOFFObjectTargetWriter.cpp