LLVM: llvm::RawInstrProfReader< IntPtrT > Class Template Reference
llvm::RawInstrProfReader< IntPtrT > Class Template Reference
Reader for the raw instrprof binary format from runtime.
#include "llvm/ProfileData/InstrProfReader.h"
Public Member Functions
RawInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer)
RawInstrProfReader (const RawInstrProfReader &)=delete
RawInstrProfReader & operator= (const RawInstrProfReader &)=delete
Error readHeader () override
Read the header. Required before reading first record.
Error readNextRecord (NamedInstrProfRecord &Record) override
Read a single record.
bool isIRLevelProfile () const override
bool hasCSIRLevelProfile () const override
InstrProfSymtab & getSymtab () override
Return the PGO symtab.
Public Member Functions inherited from llvm::InstrProfReader
InstrProfReader ()=default
virtual ~InstrProfReader ()=default
InstrProfIterator begin ()
Iterator over profile data.
InstrProfIterator end ()
void accumulateCounts (CountSumOrPercent &Sum, bool IsCS)
Compute the sum of counts and return in Sum.
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
Error getError ()
Get the current error.
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &DataBuffer)
Static Public Member Functions inherited from llvm::InstrProfReader
static Expected< std::unique_ptr< InstrProfReader > > create (const Twine &Path)
Factory method to create an appropriately typed reader for the given instrprof file.
static Expected< std::unique_ptr< InstrProfReader > > create (std::unique_ptr< MemoryBuffer > Buffer)
Additional Inherited Members
Protected Member Functions inherited from llvm::InstrProfReader
Error error (instrprof_error Err)
Set the current error and return same.
Error error (Error &&E)
Error success ()
Clear the current error and return a successful one.
Protected Attributes inherited from llvm::InstrProfReader
std::unique_ptr< InstrProfSymtab > Symtab
Detailed Description
template<class IntPtrT>
class llvm::RawInstrProfReader< IntPtrT >
Reader for the raw instrprof binary format from runtime.
This format is a raw memory dump of the instrumentation-baed profiling data from the runtime. It has no index.
Templated on the unsigned type whose size matches pointers on the platform that wrote the profile.
Definition at line 187 of file InstrProfReader.h.
Constructor & Destructor Documentation
RawInstrProfReader() [1/2]
template<class IntPtrT > llvm::RawInstrProfReader< IntPtrT >::RawInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer) inline
Definition at line 210 of file InstrProfReader.h.
RawInstrProfReader() [2/2]
template<class IntPtrT > llvm::RawInstrProfReader< IntPtrT >::RawInstrProfReader (const RawInstrProfReader< IntPtrT > &) delete
Member Function Documentation
getSymtab()
template<class IntPtrT > InstrProfSymtab& llvm::RawInstrProfReader< IntPtrT >::getSymtab () inline override virtual
Return the PGO symtab.
There are three different readers: Raw, Text, and Indexed profile readers. The first two types of readers are used only by llvm-profdata tool, while the indexed profile reader is also used by llvm-cov tool and the compiler (backend or frontend). Since creating PGO symtab can create significant runtime and memory overhead (as it touches data for the whole program), InstrProfSymtab for the indexed profile reader should be created on demand and it is recommended to be only used for dumping purpose with llvm-proftool, not with the compiler.
Implements llvm::InstrProfReader.
Definition at line 227 of file InstrProfReader.h.
References assert(), llvm::support::big, llvm::InstrProfSymtab::getFuncName(), llvm::getHostEndianness(), getName(), llvm::sys::getSwappedBytes(), llvm::support::little, and std::swap().
hasCSIRLevelProfile()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::hasCSIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 223 of file InstrProfReader.h.
hasFormat()
template<class IntPtrT > bool RawInstrProfReader::hasFormat (const MemoryBuffer & DataBuffer) static
Definition at line 295 of file InstrProfReader.cpp.
References llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), llvm::sys::getSwappedBytes(), and Magic.
Referenced by llvm::InstrProfReader::create().
isIRLevelProfile()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::isIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 219 of file InstrProfReader.h.
operator=()
template<class IntPtrT > RawInstrProfReader& llvm::RawInstrProfReader< IntPtrT >::operator= (const RawInstrProfReader< IntPtrT > &) delete
readHeader()
template<class IntPtrT > Error RawInstrProfReader::readHeader () override virtual
Read the header. Required before reading first record.
Implements llvm::InstrProfReader.
Definition at line 305 of file InstrProfReader.cpp.
References llvm::bad_header, llvm::bad_magic, llvm::InstrProfReader::error(), and llvm::InstrProfReader::readHeader().
readNextRecord()
template<class IntPtrT > Error RawInstrProfReader::readNextRecord (NamedInstrProfRecord & Record) override virtual
Read a single record.
Implements llvm::InstrProfReader.
Definition at line 475 of file InstrProfReader.cpp.
References E, llvm::InstrProfReader::error(), and llvm::InstrProfReader::success().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp