LLVM: llvm::BTFTypeArray Class Reference
llvm::BTFTypeArray Class Reference
Handle array type.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFTypeArray (uint32_t ElemTypeId, uint32_t NumElems)
uint32_t getSize ()
Get the size of this BTF type entry.
void completeType (BTFDebug &BDebug)
Represent a BTF array.
void emitType (MCStreamer &OS)
Emit types for this BTF type entry.
Public Member Functions inherited from llvm::BTFTypeBase
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
Additional Inherited Members
Protected Attributes inherited from llvm::BTFTypeBase
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
Handle array type.
Definition at line 107 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFTypeArray()
BTFTypeArray::BTFTypeArray (uint32_t ElemTypeId, uint32_t NumElems)
Definition at line 187 of file BTFDebug.cpp.
References llvm::BTFTypeBase::BTFType, llvm::BTF::CommonType::Info, llvm::BTFTypeBase::Kind, llvm::BTF::CommonType::NameOff, and llvm::BTF::CommonType::Size.
Member Function Documentation
completeType()
void BTFTypeArray::completeType (BTFDebug & BDebug) virtual
Represent a BTF array.
Reimplemented from llvm::BTFTypeBase.
Definition at line 198 of file BTFDebug.cpp.
References llvm::BTFDebug::getArrayIndexTypeId(), and llvm::BTFTypeBase::IsCompleted.
emitType()
void BTFTypeArray::emitType (MCStreamer & OS) virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented from llvm::BTFTypeBase.
Definition at line 210 of file BTFDebug.cpp.
References llvm::MCStreamer::EmitIntValue(), and llvm::BTFTypeBase::emitType().
getSize()
uint32_t llvm::BTFTypeArray::getSize () inline virtual
Get the size of this BTF type entry.
Reimplemented from llvm::BTFTypeBase.
Definition at line 112 of file BTFDebug.h.
References llvm::BTF::BTFArraySize, llvm::BTFTypeBase::completeType(), llvm::BTFTypeBase::emitType(), and llvm::BTFTypeBase::getSize().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp