LLVM: llvm::BPFInstrInfo Class Reference
llvm::BPFInstrInfo Class Reference
#include "Target/BPF/BPFInstrInfo.h"
Public Member Functions
BPFInstrInfo ()
const BPFRegisterInfo & getRegisterInfo () const
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
bool expandPostRAPseudo (MachineInstr &MI) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
Detailed Description
Definition at line 24 of file BPFInstrInfo.h.
Constructor & Destructor Documentation
BPFInstrInfo()
BPFInstrInfo::BPFInstrInfo ()
Definition at line 28 of file BPFInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool BPFInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 164 of file BPFInstrInfo.cpp.
Referenced by getRegisterInfo().
copyPhysReg()
void BPFInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 31 of file BPFInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::RegState::Define, llvm::MachineBasicBlock::erase(), llvm::getKillRegState(), I, llvm::RegState::Kill, llvm_unreachable, llvm::Log2_64(), and MI.
Referenced by getRegisterInfo().
expandPostRAPseudo()
bool BPFInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 115 of file BPFInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), and llvm::ARMISD::MEMCPY.
Referenced by getRegisterInfo().
getRegisterInfo()
const BPFRegisterInfo& llvm::BPFInstrInfo::getRegisterInfo () const inline
Definition at line 30 of file BPFInstrInfo.h.
References analyzeBranch(), copyPhysReg(), expandPostRAPseudo(), llvm::ISD::FrameIndex, I, loadRegFromStackSlot(), MI, storeRegToStackSlot(), and TRI.
Referenced by llvm::BPFSubtarget::getRegisterInfo().
insertBranch()
unsigned BPFInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 219 of file BPFInstrInfo.cpp.
loadRegFromStackSlot()
void BPFInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 147 of file BPFInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), and llvm_unreachable.
Referenced by getRegisterInfo().
removeBranch()
unsigned BPFInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 240 of file BPFInstrInfo.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and I.
storeRegToStackSlot()
void BPFInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 124 of file BPFInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getKillRegState(), and llvm_unreachable.
Referenced by getRegisterInfo().
The documentation for this class was generated from the following files:
lib/Target/BPF/BPFInstrInfo.h
lib/Target/BPF/BPFInstrInfo.cpp