LLVM: llvm::SymbolRewriter::RewriteMapParser Class Reference
llvm::SymbolRewriter::RewriteMapParser Class Reference
#include "llvm/Transforms/Utils/SymbolRewriter.h"
Public Member Functions
bool parse (const std::string &MapFile, RewriteDescriptorList *Descriptors)
Detailed Description
Definition at line 94 of file SymbolRewriter.h.
Member Function Documentation
parse()
bool RewriteMapParser::parse (const std::string & MapFile, RewriteDescriptorList * Descriptors)
Definition at line 251 of file SymbolRewriter.cpp.
References llvm::dyn_cast(), llvm::StringRef::equals(), llvm::tgtok::Field, llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), llvm::yaml::KeyValueNode::getKey(), llvm::PassRegistry::getPassRegistry(), llvm::yaml::ScalarNode::getValue(), llvm::yaml::KeyValueNode::getValue(), llvm::initializeRewriteSymbolsLegacyPassPass(), llvm::StringRef::lower(), parse(), llvm::yaml::Stream::printError(), llvm::report_fatal_error(), and llvm::Sched::Source.
Referenced by llvm::RewriteSymbolPass::runImpl().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/SymbolRewriter.h
lib/Transforms/Utils/SymbolRewriter.cpp