LLVM: llvm::NaryReassociatePass Class Reference
llvm::NaryReassociatePass Class Reference
#include "llvm/Transforms/Scalar/NaryReassociate.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, AssumptionCache *AC_, DominatorTree *DT_, ScalarEvolution *SE_, TargetLibraryInfo *TLI_, TargetTransformInfo *TTI_)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< NaryReassociatePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 102 of file NaryReassociate.h.
Member Function Documentation
run()
PreservedAnalyses NaryReassociatePass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 180 of file NaryReassociate.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool NaryReassociatePass::runImpl (Function & F, AssumptionCache * AC_, DominatorTree * DT_, ScalarEvolution * SE_, TargetLibraryInfo * TLI_, TargetTransformInfo * TTI_)
Definition at line 197 of file NaryReassociate.cpp.
References llvm::Module::getDataLayout(), and llvm::GlobalValue::getParent().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/NaryReassociate.h
lib/Transforms/Scalar/NaryReassociate.cpp