LLVM: llvm::MemoryBuffer Class Reference
llvm::MemoryBuffer Class Reference abstract
This interface provides simple read-only access to a block of memory, and provides simple methods for reading files and standard input into a memory buffer.
#include "llvm/Support/MemoryBuffer.h"
Public Types
enum BufferKind { MemoryBuffer_Malloc, MemoryBuffer_MMap }
The kind of memory backing used to support the MemoryBuffer.
Public Member Functions
MemoryBuffer (const MemoryBuffer &)=delete
MemoryBuffer & operator= (const MemoryBuffer &)=delete
virtual ~MemoryBuffer ()
const char * getBufferStart () const
const char * getBufferEnd () const
size_t getBufferSize () const
StringRef getBuffer () const
virtual StringRef getBufferIdentifier () const
Return an identifier for this buffer, typically the filename it was read from.
virtual BufferKind getBufferKind () const =0
Return information on the memory mechanism used to support the MemoryBuffer.
MemoryBufferRef getMemBufferRef () const
Static Public Member Functions
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFile (const Twine &Filename, int64_t FileSize=-1, bool RequiresNullTerminator=true, bool IsVolatile=false)
Open the specified file as a MemoryBuffer, returning a new MemoryBuffer if successful, otherwise returning null.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileAsStream (const Twine &Filename)
Read all of the specified file into a MemoryBuffer as a stream (i.e.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getOpenFileSlice (sys::fs::file_t FD, const Twine &Filename, uint64_t MapSize, int64_t Offset, bool IsVolatile=false)
Given an already-open file descriptor, map some slice of it into a MemoryBuffer.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getOpenFile (sys::fs::file_t FD, const Twine &Filename, uint64_t FileSize, bool RequiresNullTerminator=true, bool IsVolatile=false)
Given an already-open file descriptor, read the file and return a MemoryBuffer.
static std::unique_ptr< MemoryBuffer > getMemBuffer (StringRef InputData, StringRef BufferName="", bool RequiresNullTerminator=true)
Open the specified memory range as a MemoryBuffer.
static std::unique_ptr< MemoryBuffer > getMemBuffer (MemoryBufferRef Ref, bool RequiresNullTerminator=true)
static std::unique_ptr< MemoryBuffer > getMemBufferCopy (StringRef InputData, const Twine &BufferName="")
Open the specified memory range as a MemoryBuffer, copying the contents and taking ownership of it.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getSTDIN ()
Read all of stdin into a file buffer, and return it.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileOrSTDIN (const Twine &Filename, int64_t FileSize=-1, bool RequiresNullTerminator=true)
Open the specified file as a MemoryBuffer, or open stdin if the Filename is "-".
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileSlice (const Twine &Filename, uint64_t MapSize, uint64_t Offset, bool IsVolatile=false)
Map a subrange of the specified file as a MemoryBuffer.
Protected Member Functions
MemoryBuffer ()=default
void init (const char *BufStart, const char *BufEnd, bool RequiresNullTerminator)
init - Initialize this MemoryBuffer as a reference to externally allocated memory, memory that we know is already null terminated.
Static Protected Attributes
static constexpr sys::fs::mapped_file_region::mapmode Mapmode
Detailed Description
This interface provides simple read-only access to a block of memory, and provides simple methods for reading files and standard input into a memory buffer.
In addition to basic access to the characters in the file, this interface guarantees you can read one character past the end of the file, and that this character will read as '\0'.
The '\0' guarantee is needed to support an optimization – it's intended to be more efficient for clients which are reading all the data to stop reading when they encounter a '\0' than to continually check the file position to see if it has reached the end of the file.
Definition at line 41 of file MemoryBuffer.h.
Member Enumeration Documentation
BufferKind
enum llvm::MemoryBuffer::BufferKind
The kind of memory backing used to support the MemoryBuffer.
Enumerator
MemoryBuffer_Malloc
MemoryBuffer_MMap
Definition at line 139 of file MemoryBuffer.h.
Constructor & Destructor Documentation
MemoryBuffer() [1/2]
llvm::MemoryBuffer::MemoryBuffer () protected default
MemoryBuffer() [2/2]
llvm::MemoryBuffer::MemoryBuffer (const MemoryBuffer &) delete
~MemoryBuffer()
MemoryBuffer::~MemoryBuffer () virtual
Definition at line 41 of file MemoryBuffer.cpp.
Member Function Documentation
getBuffer()
StringRef llvm::MemoryBuffer::getBuffer () const inline
Definition at line 63 of file MemoryBuffer.h.
References getBufferSize().
Referenced by llvm::vfs::InMemoryFileSystem::addFileNoOwn(), llvm::TGLexer::getLoc(), getMemBufferRef(), isOperator(), llvm::SpecialCaseList::parse(), and llvm::TGLexer::TGLexer().
getBufferEnd()
const char* llvm::MemoryBuffer::getBufferEnd () const inline
Definition at line 60 of file MemoryBuffer.h.
Referenced by llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), llvm::DiffFilesWithTolerance(), llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), llvm::WritableMemoryBuffer::getBufferEnd(), llvm::WriteThroughMemoryBuffer::getBufferEnd(), llvm::SourceMgr::GetMessage(), llvm::line_iterator::line_iterator(), and llvm::CodeGenCoverage::parse().
getBufferIdentifier()
virtual StringRef llvm::MemoryBuffer::getBufferIdentifier () const inline virtual
Return an identifier for this buffer, typically the filename it was read from.
Reimplemented in llvm::SmallVectorMemoryBuffer.
Definition at line 69 of file MemoryBuffer.h.
References getFile(), getFileAsStream(), getFileOrSTDIN(), getFileSlice(), getMemBuffer(), getMemBufferCopy(), getOpenFile(), getOpenFileSlice(), getSTDIN(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile, and llvm::Ref.
Referenced by llvm::vfs::InMemoryFileSystem::addFileNoOwn(), getMemBufferRef(), llvm::SourceMgr::GetMessage(), llvm::orc::DumpObjects::operator()(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), and llvm::SymbolRemappingReader::read().
getBufferKind()
virtual BufferKind llvm::MemoryBuffer::getBufferKind () const pure virtual
Return information on the memory mechanism used to support the MemoryBuffer.
Implemented in llvm::SmallVectorMemoryBuffer.
getBufferSize()
size_t llvm::MemoryBuffer::getBufferSize () const inline
Definition at line 61 of file MemoryBuffer.h.
Referenced by llvm::FileCheck::CanonicalizeFile(), llvm::DiffFilesWithTolerance(), getBuffer(), llvm::TextInstrProfReader::hasFormat(), llvm::RawInstrProfReader< IntPtrT >::hasFormat(), llvm::IndexedInstrProfReader::hasFormat(), llvm::line_iterator::line_iterator(), and llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge().
getBufferStart()
const char* llvm::MemoryBuffer::getBufferStart () const inline
Definition at line 59 of file MemoryBuffer.h.
Referenced by llvm::FileCheck::CanonicalizeFile(), llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), llvm::DiffFilesWithTolerance(), llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), llvm::WritableMemoryBuffer::getBufferStart(), llvm::WriteThroughMemoryBuffer::getBufferStart(), llvm::SourceMgr::GetMessage(), llvm::TextInstrProfReader::hasFormat(), llvm::RawInstrProfReader< IntPtrT >::hasFormat(), llvm::IndexedInstrProfReader::hasFormat(), llvm::sampleprof::SampleProfileReaderRawBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderExtBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderCompactBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderGCC::hasFormat(), llvm::line_iterator::line_iterator(), llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge(), and llvm::CodeGenCoverage::parse().
getFile()
ErrorOr< std::unique_ptr< MemoryBuffer > > MemoryBuffer::getFile (const Twine & Filename, int64_t FileSize = -1, bool RequiresNullTerminator = true, bool IsVolatile = false) static
Open the specified file as a MemoryBuffer, returning a new MemoryBuffer if successful, otherwise returning null.
If FileSize is specified, this means that the client knows that the file exists and that it has the specified size.
Parameters
IsVolatile Set to true to indicate that the contents of the file can change outside the user's control, e.g. when libclang tries to parse while the user is editing/updating the file or if the file is on an NFS.
Definition at line 231 of file MemoryBuffer.cpp.
References getOpenFileImpl(), and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile.
Referenced by llvm::SourceMgr::AddIncludeFile(), llvm::BTFDebug::BTFDebug(), llvm::LTOCodeGenerator::compileOptimized(), llvm::computeLTOCacheKey(), llvm::createBlockExtractorPass(), llvm::LTOModule::createFromFile(), llvm::object::ObjectFile::createObjectFile(), llvm::remarks::createYAMLParserFromMeta(), llvm::DiffFilesWithTolerance(), doList(), llvm::object::Archive::Child::getBuffer(), llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), getBufferIdentifier(), getFileOrSTDIN(), llvm::unittest::getInputFileDirectory(), llvm::identify_magic(), llvm::LTOModule::isBitcodeFile(), LLVMCreateMemoryBufferWithContentsOfFile(), llvm::orc::StaticLibraryDefinitionGenerator::Load(), openFile(), llvm::SymbolRewriter::RewriteMapParser::parse(), parseCHRFilterFiles(), printSymbolizedStackTrace(), processRemarkVersion(), llvm::runFuzzerOnInputs(), selectJumpTableArmEncoding(), llvm::TableGenMain(), and llvm::updateIndexWPDForExports().
getFileAsStream()
ErrorOr< std::unique_ptr< MemoryBuffer > > MemoryBuffer::getFileAsStream (const Twine & Filename) static
Read all of the specified file into a MemoryBuffer as a stream (i.e.
until EOF reached). This is useful for special files that look like a regular file but have 0 size (e.g. /proc/cpuinfo on Linux).
Definition at line 507 of file MemoryBuffer.cpp.
References llvm::sys::fs::closeFile(), llvm::errorToErrorCode(), getMemoryBufferForStream(), llvm::sys::fs::OF_None, llvm::sys::fs::openNativeFileForRead(), llvm::MipsISD::Ret, and llvm::Expected< T >::takeError().
Referenced by llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), getBufferIdentifier(), llvm::sys::getHostCPUName(), and getProcCpuinfoContent().
getFileOrSTDIN()
ErrorOr< std::unique_ptr< MemoryBuffer > > MemoryBuffer::getFileOrSTDIN (const Twine & Filename, int64_t FileSize = -1, bool RequiresNullTerminator = true) static
Open the specified file as a MemoryBuffer, or open stdin if the Filename is "-".
Definition at line 143 of file MemoryBuffer.cpp.
References getFile(), getSTDIN(), and llvm::Twine::toStringRef().
Referenced by branchDiv(), llvm::object::createBinary(), llvm::createMIRParserFromFile(), llvm::symbolize::LLVMSymbolizer::flush(), llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), getBufferIdentifier(), llvm::getModuleSummaryIndexForFile(), llvm::coverage::CoverageMapping::load(), llvm::pdb::loadDataForPDB(), llvm::gsym::GsymReader::openFile(), setupMemoryBuffer(), and llvm::TableGenMain().
getFileSlice()
ErrorOr< std::unique_ptr< MemoryBuffer > > MemoryBuffer::getFileSlice (const Twine & Filename, uint64_t MapSize, uint64_t Offset, bool IsVolatile = false) static
Map a subrange of the specified file as a MemoryBuffer.
Definition at line 154 of file MemoryBuffer.cpp.
References llvm::sys::fs::mapped_file_region::alignment(), llvm::sys::fs::mapped_file_region::const_data(), and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile.
Referenced by llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), and getBufferIdentifier().
getMemBuffer() [1/2]
std::unique_ptr< MemoryBuffer > MemoryBuffer::getMemBuffer (StringRef InputData, StringRef BufferName = "", bool RequiresNullTerminator = true) static
Open the specified memory range as a MemoryBuffer.
Note that InputData must be null terminated if RequiresNullTerminator is true.
Definition at line 112 of file MemoryBuffer.cpp.
References llvm::MipsISD::Ret.
Referenced by llvm::vfs::InMemoryFileSystem::addFileNoOwn(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), getBufferIdentifier(), getMemBuffer(), llvm::NewArchiveMember::getOldMember(), llvm::MIRParserImpl::initializeMachineFunction(), LLVMBinaryCopyMemoryBuffer(), LLVMCreateMemoryBufferWithMemoryRange(), llvm::LTOModule::makeBuffer(), llvm::parseModule(), and llvm::yaml::Scanner::Scanner().
getMemBuffer() [2/2]
std::unique_ptr< MemoryBuffer > MemoryBuffer::getMemBuffer (MemoryBufferRef Ref, bool RequiresNullTerminator = true) static
Definition at line 120 of file MemoryBuffer.cpp.
References llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferIdentifier(), and getMemBuffer().
getMemBufferCopy()
std::unique_ptr< MemoryBuffer > MemoryBuffer::getMemBufferCopy (StringRef InputData, const Twine & BufferName = "") static
Open the specified memory range as a MemoryBuffer, copying the contents and taking ownership of it.
InputData does not have to be null terminated.
Definition at line 135 of file MemoryBuffer.cpp.
References getMemBufferCopyImpl().
Referenced by llvm::orc::OrcMCJITReplacement::addObjectFile(), llvm::BTFDebug::BTFDebug(), llvm::gsym::GsymReader::copyBuffer(), llvm::FileCheckPatternContext::defineCmdlineVariables(), EmitDebugSectionImpl(), llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), getBufferIdentifier(), llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest(), isOperator(), LLVMCreateMemoryBufferWithMemoryRangeCopy(), LLVMWriteBitcodeToMemoryBuffer(), llvm::lto::localCache(), llvm::FileCheck::readCheckFile(), llvm::orc::OrcMCJITReplacement::setProcessAllSections(), srcMgrDiagHandler(), and llvm::InstrProfWriter::writeBuffer().
getMemBufferRef()
MemoryBufferRef MemoryBuffer::getMemBufferRef () const
Definition at line 519 of file MemoryBuffer.cpp.
References llvm::Data, getBuffer(), and getBufferIdentifier().
Referenced by llvm::LTOModule::getProducerString(), llvm::LTOModule::isBitcodeForTarget(), and llvm::orc::SimpleCompiler::operator()().
getOpenFile()
ErrorOr< std::unique_ptr< MemoryBuffer > > MemoryBuffer::getOpenFile (sys::fs::file_t FD, const Twine & Filename, uint64_t FileSize, bool RequiresNullTerminator = true, bool IsVolatile = false) static
Given an already-open file descriptor, read the file and return a MemoryBuffer.
Parameters
IsVolatile Set to true to indicate that the contents of the file can change outside the user's control, e.g. when libclang tries to parse while the user is editing/updating the file or if the file is on an NFS.
Definition at line 482 of file MemoryBuffer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile.
Referenced by llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), getBufferIdentifier(), llvm::NewArchiveMember::getFile(), llvm::lto::localCache(), and pathHasTraversal().
getOpenFileSlice()
ErrorOr< std::unique_ptr< MemoryBuffer > > MemoryBuffer::getOpenFileSlice (sys::fs::file_t FD, const Twine & Filename, uint64_t MapSize, int64_t Offset, bool IsVolatile = false) static
Given an already-open file descriptor, map some slice of it into a MemoryBuffer.
The slice is specified by an Offset and MapSize. Since this is in the middle of a file, the buffer is not null terminated.
Definition at line 489 of file MemoryBuffer.cpp.
References assert(), and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile.
Referenced by llvm::LTOModule::createFromOpenFileSlice(), llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), and getBufferIdentifier().
getSTDIN()
ErrorOr< std::unique_ptr< MemoryBuffer > > MemoryBuffer::getSTDIN () static
Read all of stdin into a file buffer, and return it.
Definition at line 496 of file MemoryBuffer.cpp.
References llvm::sys::ChangeStdinToBinary(), getMemoryBufferForStream(), and llvm::sys::fs::getStdinHandle().
Referenced by llvm::WritableMemoryBuffer::getBuffer(), llvm::WriteThroughMemoryBuffer::getBuffer(), getBufferIdentifier(), getFileOrSTDIN(), and LLVMCreateMemoryBufferWithSTDIN().
init()
void MemoryBuffer::init (const char * BufStart, const char * BufEnd, bool RequiresNullTerminator) protected
init - Initialize this MemoryBuffer as a reference to externally allocated memory, memory that we know is already null terminated.
Definition at line 45 of file MemoryBuffer.cpp.
References assert().
Referenced by llvm::SmallVectorMemoryBuffer::SmallVectorMemoryBuffer().
operator=()
MemoryBuffer& llvm::MemoryBuffer::operator= (const MemoryBuffer &) delete
Member Data Documentation
Mapmode
constexpr sys::fs::mapped_file_region::mapmode llvm::MemoryBuffer::Mapmode static protected
Initial value:
=
      sys::fs::mapped_file_region::readonly
Definition at line 51 of file MemoryBuffer.h.
The documentation for this class was generated from the following files:
include/llvm/Support/MemoryBuffer.h
lib/Support/MemoryBuffer.cpp