LLVM: llvm::X86TargetStreamer Class Reference
llvm::X86TargetStreamer Class Reference abstract
X86 target streamer implementing x86-only assembly directives.
#include "Target/X86/MCTargetDesc/X86TargetStreamer.h"
Public Member Functions
X86TargetStreamer (MCStreamer &S)
virtual bool emitFPOProc (const MCSymbol *ProcSym, unsigned ParamsSize, SMLoc L={})=0
virtual bool emitFPOEndPrologue (SMLoc L={})=0
virtual bool emitFPOEndProc (SMLoc L={})=0
virtual bool emitFPOData (const MCSymbol *ProcSym, SMLoc L={})=0
virtual bool emitFPOPushReg (unsigned Reg, SMLoc L={})=0
virtual bool emitFPOStackAlloc (unsigned StackAlloc, SMLoc L={})=0
virtual bool emitFPOStackAlign (unsigned Align, SMLoc L={})=0
virtual bool emitFPOSetFrame (unsigned Reg, SMLoc L={})=0
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
X86 target streamer implementing x86-only assembly directives.
Definition at line 17 of file X86TargetStreamer.h.
Constructor & Destructor Documentation
X86TargetStreamer()
llvm::X86TargetStreamer::X86TargetStreamer (MCStreamer & S) inline
Definition at line 19 of file X86TargetStreamer.h.
References emitFPOData(), emitFPOEndProc(), emitFPOEndPrologue(), emitFPOProc(), emitFPOPushReg(), emitFPOSetFrame(), emitFPOStackAlign(), emitFPOStackAlloc(), and Reg.
Member Function Documentation
emitFPOData()
virtual bool llvm::X86TargetStreamer::emitFPOData (const MCSymbol * ProcSym, SMLoc L = {}) pure virtual
Referenced by X86TargetStreamer().
emitFPOEndProc()
virtual bool llvm::X86TargetStreamer::emitFPOEndProc (SMLoc L = {}) pure virtual
Referenced by X86TargetStreamer().
emitFPOEndPrologue()
virtual bool llvm::X86TargetStreamer::emitFPOEndPrologue (SMLoc L = {}) pure virtual
Referenced by printConstant(), and X86TargetStreamer().
emitFPOProc()
virtual bool llvm::X86TargetStreamer::emitFPOProc (const MCSymbol * ProcSym, unsigned ParamsSize, SMLoc L = {}) pure virtual
Referenced by X86TargetStreamer().
emitFPOPushReg()
virtual bool llvm::X86TargetStreamer::emitFPOPushReg (unsigned Reg, SMLoc L = {}) pure virtual
Referenced by printConstant(), and X86TargetStreamer().
emitFPOSetFrame()
virtual bool llvm::X86TargetStreamer::emitFPOSetFrame (unsigned Reg, SMLoc L = {}) pure virtual
Referenced by printConstant(), and X86TargetStreamer().
emitFPOStackAlign()
virtual bool llvm::X86TargetStreamer::emitFPOStackAlign (unsigned Align, SMLoc L = {}) pure virtual
Referenced by printConstant(), and X86TargetStreamer().
emitFPOStackAlloc()
virtual bool llvm::X86TargetStreamer::emitFPOStackAlloc (unsigned StackAlloc, SMLoc L = {}) pure virtual
Referenced by printConstant(), and X86TargetStreamer().
The documentation for this class was generated from the following file:
lib/Target/X86/MCTargetDesc/X86TargetStreamer.h