LLVM: llvm::InductionDescriptor Class Reference
llvm::InductionDescriptor Class Reference
A struct for saving information about induction variables.
#include "llvm/Analysis/IVDescriptors.h"
Public Types
enum InductionKind { IK_NoInduction, IK_IntInduction, IK_PtrInduction, IK_FpInduction }
This enum represents the kinds of inductions that we support.
Public Member Functions
InductionDescriptor ()=default
Default constructor - creates an invalid induction.
int getConsecutiveDirection () const
Get the consecutive direction.
Value * getStartValue () const
InductionKind getKind () const
const SCEV * getStep () const
BinaryOperator * getInductionBinOp () const
ConstantInt * getConstIntStepValue () const
bool hasUnsafeAlgebra ()
Returns true if the induction type is FP and the binary operator does not have the "fast-math" property.
Instruction * getUnsafeAlgebraInst ()
Returns induction operator that does not have "fast-math" property and requires FP unsafe mode.
Instruction::BinaryOps getInductionOpcode () const
Returns binary opcode of the induction operator.
const SmallVectorImpl< Instruction * > & getCastInsts () const
Returns a reference to the type cast instructions in the induction update chain, that are redundant when guarded with a runtime SCEV overflow check.
Static Public Member Functions
static bool isInductionPHI (PHINode *Phi, const Loop *L, ScalarEvolution *SE, InductionDescriptor &D, const SCEV *Expr=nullptr, SmallVectorImpl< Instruction *> *CastsToIgnore=nullptr)
Returns true if Phi is an induction in the loop L.
static bool isFPInductionPHI (PHINode *Phi, const Loop *L, ScalarEvolution *SE, InductionDescriptor &D)
Returns true if Phi is a floating point induction in the loop L.
static bool isInductionPHI (PHINode *Phi, const Loop *L, PredicatedScalarEvolution &PSE, InductionDescriptor &D, bool Assume=false)
Returns true if Phi is a loop L induction, in the context associated with the run-time predicate of PSE.
Detailed Description
A struct for saving information about induction variables.
Definition at line 260 of file IVDescriptors.h.
Member Enumeration Documentation
InductionKind
enum llvm::InductionDescriptor::InductionKind
This enum represents the kinds of inductions that we support.
Enumerator
IK_NoInduction
Not an induction variable.
IK_IntInduction
Integer induction variable. Step = C.
IK_PtrInduction
Pointer induction var. Step = C / sizeof(elem).
IK_FpInduction
Floating point induction variable.
Definition at line 263 of file IVDescriptors.h.
Constructor & Destructor Documentation
InductionDescriptor()
llvm::InductionDescriptor::InductionDescriptor () default
Default constructor - creates an invalid induction.
Referenced by llvm::RecurrenceDescriptor::getRecurrenceBinOp().
Member Function Documentation
getCastInsts()
const SmallVectorImpl<Instruction *>& llvm::InductionDescriptor::getCastInsts () const inline
Returns a reference to the type cast instructions in the induction update chain, that are redundant when guarded with a runtime SCEV overflow check.
Definition at line 342 of file IVDescriptors.h.
Referenced by llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::LoopVectorizationLegality::isUniform(), and llvm::InnerLoopVectorizer::recordVectorLoopValueForInductionCast().
getConsecutiveDirection()
int InductionDescriptor::getConsecutiveDirection () const
Get the consecutive direction.
Returns: 0 - unknown or non-consecutive. 1 - consecutive and increasing. -1 - consecutive and decreasing.
Definition at line 836 of file IVDescriptors.cpp.
References llvm::ConstantInt::getSExtValue(), llvm::ConstantInt::isMinusOne(), and llvm::ConstantInt::isOne().
getConstIntStepValue()
ConstantInt * InductionDescriptor::getConstIntStepValue () const
Definition at line 843 of file IVDescriptors.cpp.
References llvm::dyn_cast().
Referenced by llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::Loop::isCanonical(), and llvm::LoopVectorizationLegality::isUniform().
getInductionBinOp()
BinaryOperator* llvm::InductionDescriptor::getInductionBinOp () const inline
Definition at line 283 of file IVDescriptors.h.
References D.
Referenced by llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::Loop::LoopBounds::getBounds(), and llvm::Loop::getInductionVariable().
getInductionOpcode()
Instruction::BinaryOps llvm::InductionDescriptor::getInductionOpcode () const inline
Returns binary opcode of the induction operator.
Definition at line 334 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::Loop::isAuxiliaryInductionVariable(), and llvm::Loop::isCanonical().
getKind()
InductionKind llvm::InductionDescriptor::getKind () const inline
Definition at line 281 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::LoopVectorizationLegality::isUniform(), llvm::VPRecipeBuilder::tryToOptimizeInduction(), and llvm::VPlanTransforms::VPInstructionsToVPRecipes().
getStartValue()
Value* llvm::InductionDescriptor::getStartValue () const inline
Definition at line 280 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::Loop::LoopBounds::getBounds(), llvm::Loop::isCanonical(), and llvm::LoopVectorizationLegality::isUniform().
getStep()
const SCEV* llvm::InductionDescriptor::getStep () const inline
Definition at line 282 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::Loop::LoopBounds::getBounds(), and llvm::Loop::isAuxiliaryInductionVariable().
getUnsafeAlgebraInst()
Instruction* llvm::InductionDescriptor::getUnsafeAlgebraInst () inline
Returns induction operator that does not have "fast-math" property and requires FP unsafe mode.
Definition at line 324 of file IVDescriptors.h.
Referenced by llvm::LoopVectorizationLegality::isUniform().
hasUnsafeAlgebra()
bool llvm::InductionDescriptor::hasUnsafeAlgebra () inline
Returns true if the induction type is FP and the binary operator does not have the "fast-math" property.
Such operation requires a relaxed FP mode.
Definition at line 317 of file IVDescriptors.h.
Referenced by llvm::LoopVectorizationLegality::isUniform().
isFPInductionPHI()
bool InductionDescriptor::isFPInductionPHI (PHINode * Phi, const Loop * L, ScalarEvolution * SE, InductionDescriptor & D) static
Returns true if Phi is a floating point induction in the loop L.
If Phi is an induction, the induction descriptor D will contain the data describing this induction.
Definition at line 849 of file IVDescriptors.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::ScalarEvolution::getUnknown(), I, and llvm::Type::isFloatingPointTy().
isInductionPHI() [1/2]
bool InductionDescriptor::isInductionPHI (PHINode * Phi, const Loop * L, ScalarEvolution * SE, InductionDescriptor & D, const SCEV * Expr = nullptr, SmallVectorImpl< Instruction *> * CastsToIgnore = nullptr) static
Returns true if Phi is an induction in the loop L.
If Phi is an induction, the induction descriptor D will contain the data describing this induction. If by some other means the caller has a better SCEV expression for Phi than the one returned by the ScalarEvolution analysis, it can be passed through Expr. If the def-use chain associated with the phi includes casts (that we know we can ignore under proper runtime checks), they are passed through CastsToIgnore.
Definition at line 1051 of file IVDescriptors.cpp.
References assert(), llvm::dbgs(), llvm::dyn_cast(), llvm::ScalarEvolution::getConstant(), llvm::Module::getDataLayout(), llvm::PHINode::getIncomingValueForBlock(), llvm::SCEVAddRecExpr::getLoop(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Instruction::getModule(), llvm::Type::getPointerElementType(), llvm::ScalarEvolution::getSCEV(), llvm::ConstantInt::getSExtValue(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::SCEVConstant::getValue(), llvm::Type::isIntegerTy(), llvm::ScalarEvolution::isLoopInvariant(), llvm::Type::isPointerTy(), llvm::Type::isSized(), LLVM_DEBUG, and Size.
Referenced by findInnerReductionPhi(), llvm::Loop::LoopBounds::getBounds(), llvm::Loop::getInductionDescriptor(), llvm::Loop::getInductionVariable(), llvm::Loop::isAuxiliaryInductionVariable(), and llvm::LoopVectorizationLegality::isUniform().
isInductionPHI() [2/2]
bool InductionDescriptor::isInductionPHI (PHINode * Phi, const Loop * L, PredicatedScalarEvolution & PSE, InductionDescriptor & D, bool Assume = false) static
Returns true if Phi is a loop L induction, in the context associated with the run-time predicate of PSE.
If Assume is true, this can add further SCEV predicates to PSE in order to prove that Phi is an induction. If Phi is an induction, D will contain the data describing this induction.
Definition at line 1007 of file IVDescriptors.cpp.
References D, llvm::dbgs(), llvm::dyn_cast(), llvm::PredicatedScalarEvolution::getAsAddRec(), getCastsForInductionPHI(), llvm::PredicatedScalarEvolution::getSCEV(), llvm::PredicatedScalarEvolution::getSE(), llvm::Value::getType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatingPointTy(), llvm::Type::isFloatTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), and LLVM_DEBUG.
The documentation for this class was generated from the following files:
include/llvm/Analysis/IVDescriptors.h
lib/Analysis/IVDescriptors.cpp