LLVM: llvm::codeview::SymbolVisitorCallbacks Class Reference
llvm::codeview::SymbolVisitorCallbacks Class Reference
#include "llvm/DebugInfo/CodeView/SymbolVisitorCallbacks.h"
Public Member Functions
virtual ~SymbolVisitorCallbacks ()=default
virtual Error visitUnknownSymbol (CVSymbol &Record)
Action to take on unknown symbols. By default, they are ignored.
virtual Error visitSymbolBegin (CVSymbol &Record, uint32_t Offset)
Paired begin/end actions for all symbols.
virtual Error visitSymbolBegin (CVSymbol &Record)
virtual Error visitSymbolEnd (CVSymbol &Record)
Friends
class CVSymbolVisitor
Detailed Description
Definition at line 18 of file SymbolVisitorCallbacks.h.
Constructor & Destructor Documentation
~SymbolVisitorCallbacks()
virtual llvm::codeview::SymbolVisitorCallbacks::~SymbolVisitorCallbacks () virtual default
Member Function Documentation
visitSymbolBegin() [1/2]
virtual Error llvm::codeview::SymbolVisitorCallbacks::visitSymbolBegin (CVSymbol & Record, uint32_t Offset) inline virtual
Paired begin/end actions for all symbols.
Receives all record data, including the fixed-length record prefix. visitSymbolBegin() should return the type of the Symbol, or an error if it cannot be determined.
Reimplemented in llvm::codeview::SymbolDeserializer, and llvm::codeview::SymbolVisitorCallbackPipeline.
Definition at line 32 of file SymbolVisitorCallbacks.h.
References llvm::Error::success().
Referenced by llvm::codeview::CVSymbolVisitor::visitSymbolRecord().
visitSymbolBegin() [2/2]
virtual Error llvm::codeview::SymbolVisitorCallbacks::visitSymbolBegin (CVSymbol & Record) inline virtual
Reimplemented in llvm::codeview::SymbolDeserializer, llvm::codeview::SymbolSerializer, llvm::codeview::SymbolVisitorCallbackPipeline, and llvm::codeview::SymbolRecordMapping.
Definition at line 35 of file SymbolVisitorCallbacks.h.
References llvm::Error::success().
visitSymbolEnd()
virtual Error llvm::codeview::SymbolVisitorCallbacks::visitSymbolEnd (CVSymbol & Record) inline virtual
Reimplemented in llvm::codeview::SymbolDeserializer, llvm::codeview::SymbolSerializer, llvm::codeview::SymbolVisitorCallbackPipeline, and llvm::codeview::SymbolRecordMapping.
Definition at line 36 of file SymbolVisitorCallbacks.h.
References llvm::Error::success().
Referenced by finishVisitation().
visitUnknownSymbol()
virtual Error llvm::codeview::SymbolVisitorCallbacks::visitUnknownSymbol (CVSymbol & Record) inline virtual
Action to take on unknown symbols. By default, they are ignored.
Reimplemented in llvm::codeview::SymbolVisitorCallbackPipeline.
Definition at line 25 of file SymbolVisitorCallbacks.h.
References llvm::Error::success().
Referenced by finishVisitation().
Friends And Related Function Documentation
CVSymbolVisitor
friend class CVSymbolVisitor friend
Definition at line 19 of file SymbolVisitorCallbacks.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolVisitorCallbacks.h