LLVM: llvm::xray::TraceExpander Class Reference
llvm::xray::TraceExpander Class Reference
#include "llvm/XRay/FDRTraceExpander.h"
Public Member Functions
TraceExpander (function_ref< void(const XRayRecord &)> F, uint16_t L)
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Error flush ()
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
Definition at line 23 of file FDRTraceExpander.h.
Constructor & Destructor Documentation
TraceExpander()
llvm::xray::TraceExpander::TraceExpander (function_ref< void(const XRayRecord &)> F, uint16_t L) inline explicit
Definition at line 38 of file FDRTraceExpander.h.
References flush(), and visit().
Member Function Documentation
flush()
Error llvm::xray::TraceExpander::flush ()
Definition at line 125 of file FDRTraceExpander.cpp.
References llvm::Error::success().
Referenced by TraceExpander().
visit() [1/12]
Error llvm::xray::TraceExpander::visit (BufferExtents &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 21 of file FDRTraceExpander.cpp.
References llvm::Error::success().
Referenced by TraceExpander().
visit() [2/12]
Error llvm::xray::TraceExpander::visit (WallclockRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 26 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [3/12]
Error llvm::xray::TraceExpander::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 28 of file FDRTraceExpander.cpp.
References llvm::xray::NewCPUIDRecord::cpuid(), llvm::Error::success(), and llvm::xray::NewCPUIDRecord::tsc().
visit() [4/12]
Error llvm::xray::TraceExpander::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 34 of file FDRTraceExpander.cpp.
References llvm::Error::success(), and llvm::xray::TSCWrapRecord::tsc().
visit() [5/12]
Error llvm::xray::TraceExpander::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 39 of file FDRTraceExpander.cpp.
References llvm::xray::XRayRecord::CPU, llvm::xray::CustomEventRecord::cpu(), llvm::xray::CUSTOM_EVENT, llvm::xray::XRayRecord::Data, llvm::xray::CustomEventRecord::data(), llvm::xray::XRayRecord::PId, llvm::Error::success(), llvm::xray::XRayRecord::TId, llvm::xray::XRayRecord::TSC, llvm::xray::CustomEventRecord::tsc(), and llvm::xray::XRayRecord::Type.
visit() [6/12]
Error llvm::xray::TraceExpander::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 84 of file FDRTraceExpander.cpp.
References llvm::xray::CallArgRecord::arg(), llvm::xray::XRayRecord::CallArgs, llvm::xray::ENTER_ARG, llvm::Error::success(), and llvm::xray::XRayRecord::Type.
visit() [7/12]
Error llvm::xray::TraceExpander::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 90 of file FDRTraceExpander.cpp.
References llvm::xray::PIDRecord::pid(), and llvm::Error::success().
visit() [8/12]
Error llvm::xray::TraceExpander::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 95 of file FDRTraceExpander.cpp.
References llvm::Error::success(), and llvm::xray::NewBufferRecord::tid().
visit() [9/12]
Error llvm::xray::TraceExpander::visit (EndBufferRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 104 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [10/12]
Error llvm::xray::TraceExpander::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 110 of file FDRTraceExpander.cpp.
References llvm::xray::XRayRecord::CPU, llvm::xray::FunctionRecord::delta(), llvm::xray::XRayRecord::FuncId, llvm::xray::FunctionRecord::functionId(), llvm::xray::XRayRecord::PId, llvm::xray::FunctionRecord::recordType(), llvm::Error::success(), llvm::xray::XRayRecord::TId, llvm::xray::XRayRecord::TSC, and llvm::xray::XRayRecord::Type.
visit() [11/12]
Error llvm::xray::TraceExpander::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 53 of file FDRTraceExpander.cpp.
References llvm::xray::XRayRecord::CPU, llvm::xray::CUSTOM_EVENT, llvm::xray::XRayRecord::Data, llvm::xray::CustomEventRecordV5::data(), llvm::xray::CustomEventRecordV5::delta(), llvm::xray::XRayRecord::PId, llvm::Error::success(), llvm::xray::XRayRecord::TId, llvm::xray::XRayRecord::TSC, and llvm::xray::XRayRecord::Type.
visit() [12/12]
Error llvm::xray::TraceExpander::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 68 of file FDRTraceExpander.cpp.
References llvm::xray::XRayRecord::CPU, llvm::xray::XRayRecord::Data, llvm::xray::TypedEventRecord::data(), llvm::xray::TypedEventRecord::delta(), llvm::xray::TypedEventRecord::eventType(), llvm::xray::XRayRecord::PId, llvm::xray::XRayRecord::RecordType, llvm::Error::success(), llvm::xray::XRayRecord::TId, llvm::xray::XRayRecord::TSC, llvm::xray::XRayRecord::Type, and llvm::xray::TYPED_EVENT.
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRTraceExpander.h
lib/XRay/FDRTraceExpander.cpp