LLVM: llvm::pdb::DIASectionContrib Class Reference
llvm::pdb::DIASectionContrib Class Reference
#include "llvm/DebugInfo/PDB/DIA/DIASectionContrib.h"
Public Member Functions
DIASectionContrib (const DIASession &PDBSession, CComPtr< IDiaSectionContrib > DiaSection)
std::unique_ptr< PDBSymbolCompiland > getCompiland () const override
uint32_t getAddressSection () const override
uint32_t getAddressOffset () const override
uint32_t getRelativeVirtualAddress () const override
uint64_t getVirtualAddress () const override
uint32_t getLength () const override
bool isNotPaged () const override
bool hasCode () const override
bool hasCode16Bit () const override
bool hasInitializedData () const override
bool hasUninitializedData () const override
bool isRemoved () const override
bool hasComdat () const override
bool isDiscardable () const override
bool isNotCached () const override
bool isShared () const override
bool isExecutable () const override
bool isReadable () const override
bool isWritable () const override
uint32_t getDataCrc32 () const override
uint32_t getRelocationsCrc32 () const override
uint32_t getCompilandId () const override
Public Member Functions inherited from llvm::pdb::IPDBSectionContrib
virtual ~IPDBSectionContrib ()
Detailed Description
Definition at line 19 of file DIASectionContrib.h.
Constructor & Destructor Documentation
DIASectionContrib()
DIASectionContrib::DIASectionContrib (const DIASession & PDBSession, CComPtr< IDiaSectionContrib > DiaSection) explicit
Definition at line 17 of file DIASectionContrib.cpp.
Member Function Documentation
getAddressOffset()
uint32_t DIASectionContrib::getAddressOffset () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 45 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
getAddressSection()
uint32_t DIASectionContrib::getAddressSection () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 41 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
getCompiland()
std::unique_ptr< PDBSymbolCompiland > DIASectionContrib::getCompiland () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 21 of file DIASectionContrib.cpp.
References llvm::ARMBuildAttrs::Symbol.
getCompilandId()
uint32_t DIASectionContrib::getCompilandId () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 123 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
getDataCrc32()
uint32_t DIASectionContrib::getDataCrc32 () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 115 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
getLength()
uint32_t DIASectionContrib::getLength () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 58 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
getRelativeVirtualAddress()
uint32_t DIASectionContrib::getRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 53 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
getRelocationsCrc32()
uint32_t DIASectionContrib::getRelocationsCrc32 () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 119 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
getVirtualAddress()
uint64_t DIASectionContrib::getVirtualAddress () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 49 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
hasCode()
bool DIASectionContrib::hasCode () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 66 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
hasCode16Bit()
bool DIASectionContrib::hasCode16Bit () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 70 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
hasComdat()
bool DIASectionContrib::hasComdat () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 87 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
hasInitializedData()
bool DIASectionContrib::hasInitializedData () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 74 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
hasUninitializedData()
bool DIASectionContrib::hasUninitializedData () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 78 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isDiscardable()
bool DIASectionContrib::isDiscardable () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 91 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isExecutable()
bool DIASectionContrib::isExecutable () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 103 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isNotCached()
bool DIASectionContrib::isNotCached () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 95 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isNotPaged()
bool DIASectionContrib::isNotPaged () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 62 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isReadable()
bool DIASectionContrib::isReadable () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 107 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isRemoved()
bool DIASectionContrib::isRemoved () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 83 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isShared()
bool DIASectionContrib::isShared () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 99 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
isWritable()
bool DIASectionContrib::isWritable () const override virtual
Implements llvm::pdb::IPDBSectionContrib.
Definition at line 111 of file DIASectionContrib.cpp.
References PrivateGetDIAValue().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/DIA/DIASectionContrib.h
lib/DebugInfo/PDB/DIA/DIASectionContrib.cpp