LLVM: llvm::BitCodeAbbrev Class Reference
llvm::BitCodeAbbrev Class Reference
BitCodeAbbrev - This class represents an abbreviation record.
#include "llvm/Bitstream/BitCodes.h"
Public Member Functions
BitCodeAbbrev ()=default
BitCodeAbbrev (std::initializer_list< BitCodeAbbrevOp > OperandList)
unsigned getNumOperandInfos () const
const BitCodeAbbrevOp & getOperandInfo (unsigned N) const
void Add (const BitCodeAbbrevOp &OpInfo)
Detailed Description
BitCodeAbbrev - This class represents an abbreviation record.
An abbreviation allows a complex record that has redundancy to be stored in a specialized format instead of the fully-general, fully-vbr, format.
Definition at line 167 of file BitCodes.h.
Constructor & Destructor Documentation
BitCodeAbbrev() [1/2]
llvm::BitCodeAbbrev::BitCodeAbbrev () default
BitCodeAbbrev() [2/2]
llvm::BitCodeAbbrev::BitCodeAbbrev (std::initializer_list< BitCodeAbbrevOp > OperandList) inline explicit
Definition at line 173 of file BitCodes.h.
Member Function Documentation
Add()
void llvm::BitCodeAbbrev::Add (const BitCodeAbbrevOp & OpInfo) inline
Definition at line 183 of file BitCodes.h.
References llvm::SmallVectorTemplateBase< T >::push_back().
getNumOperandInfos()
unsigned llvm::BitCodeAbbrev::getNumOperandInfos () const inline
Definition at line 176 of file BitCodes.h.
References llvm::SmallVectorBase::size().
Referenced by llvm::BitstreamWriter::EmitRecordWithArray(), llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
getOperandInfo()
const BitCodeAbbrevOp& llvm::BitCodeAbbrev::getOperandInfo (unsigned N) const inline
Definition at line 179 of file BitCodes.h.
References N.
Referenced by llvm::BitstreamWriter::EmitRecordWithArray(), llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
The documentation for this class was generated from the following file:
include/llvm/Bitstream/BitCodes.h