LLVM: llvm::X86MachineFunctionInfo Class Reference
llvm::X86MachineFunctionInfo Class Reference
X86MachineFunctionInfo - This class is derived from MachineFunction and contains private X86 target-specific information for each MachineFunction.
#include "Target/X86/X86MachineFunctionInfo.h"
Public Member Functions
X86MachineFunctionInfo ()=default
X86MachineFunctionInfo (MachineFunction &MF)
bool getForceFramePointer () const
void setForceFramePointer (bool forceFP)
bool getHasPushSequences () const
void setHasPushSequences (bool HasPush)
bool getRestoreBasePointer () const
void setRestoreBasePointer (const MachineFunction *MF)
int getRestoreBasePointerOffset () const
DenseMap< int, unsigned > & getWinEHXMMSlotInfo ()
const DenseMap< int, unsigned > & getWinEHXMMSlotInfo () const
unsigned getCalleeSavedFrameSize () const
void setCalleeSavedFrameSize (unsigned bytes)
unsigned getBytesToPopOnReturn () const
void setBytesToPopOnReturn (unsigned bytes)
int getRAIndex () const
void setRAIndex (int Index)
int getFAIndex () const
void setFAIndex (int Index)
int getTCReturnAddrDelta () const
void setTCReturnAddrDelta (int delta)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
unsigned getGlobalBaseReg () const
void setGlobalBaseReg (unsigned Reg)
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Idx)
int getRegSaveFrameIndex () const
void setRegSaveFrameIndex (int Idx)
unsigned getVarArgsGPOffset () const
void setVarArgsGPOffset (unsigned Offset)
unsigned getVarArgsFPOffset () const
void setVarArgsFPOffset (unsigned Offset)
unsigned getArgumentStackSize () const
void setArgumentStackSize (unsigned size)
unsigned getNumLocalDynamicTLSAccesses () const
void incNumLocalDynamicTLSAccesses ()
bool getHasSEHFramePtrSave () const
void setHasSEHFramePtrSave (bool V)
int getSEHFramePtrSaveIndex () const
void setSEHFramePtrSaveIndex (int Index)
SmallVectorImpl< ForwardedRegister > & getForwardedMustTailRegParms ()
bool isSplitCSR () const
void setIsSplitCSR (bool s)
bool getUsesRedZone () const
void setUsesRedZone (bool V)
bool hasWinAlloca () const
void setHasWinAlloca (bool v)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
X86MachineFunctionInfo - This class is derived from MachineFunction and contains private X86 target-specific information for each MachineFunction.
Definition at line 24 of file X86MachineFunctionInfo.h.
Constructor & Destructor Documentation
X86MachineFunctionInfo() [1/2]
llvm::X86MachineFunctionInfo::X86MachineFunctionInfo () default
X86MachineFunctionInfo() [2/2]
llvm::X86MachineFunctionInfo::X86MachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 115 of file X86MachineFunctionInfo.h.
Member Function Documentation
getArgumentStackSize()
unsigned llvm::X86MachineFunctionInfo::getArgumentStackSize () const inline
Definition at line 164 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), and llvm::X86AsmPrinter::EmitFunctionBodyStart().
getBytesToPopOnReturn()
unsigned llvm::X86MachineFunctionInfo::getBytesToPopOnReturn () const inline
Definition at line 134 of file X86MachineFunctionInfo.h.
Referenced by getMOVL(), MatchingStackOffset(), and Passv64i1ArgInRegs().
getCalleeSavedFrameSize()
unsigned llvm::X86MachineFunctionInfo::getCalleeSavedFrameSize () const inline
Definition at line 131 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::inlineStackProbe(), and isFuncletReturnInstr().
getFAIndex()
int llvm::X86MachineFunctionInfo::getFAIndex () const inline
Definition at line 140 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::getFrameIndexReference(), and LowerINTRINSIC_W_CHAIN().
getForceFramePointer()
bool llvm::X86MachineFunctionInfo::getForceFramePointer () const inline
Definition at line 117 of file X86MachineFunctionInfo.h.
getForwardedMustTailRegParms()
SmallVectorImpl<ForwardedRegister>& llvm::X86MachineFunctionInfo::getForwardedMustTailRegParms () inline
Definition at line 176 of file X86MachineFunctionInfo.h.
Referenced by getMOVL(), and isSortedByValueNo().
getGlobalBaseReg()
unsigned llvm::X86MachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 149 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86InstrInfo::getGlobalBaseReg(), and llvm::X86InstrInfo::getSerializableDirectMachineOperandTargetFlags().
getHasPushSequences()
bool llvm::X86MachineFunctionInfo::getHasPushSequences () const inline
Definition at line 120 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr().
getHasSEHFramePtrSave()
bool llvm::X86MachineFunctionInfo::getHasSEHFramePtrSave () const inline
Definition at line 170 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::restoreWin32EHStackPointers().
getNumLocalDynamicTLSAccesses()
unsigned llvm::X86MachineFunctionInfo::getNumLocalDynamicTLSAccesses () const inline
Definition at line 167 of file X86MachineFunctionInfo.h.
Referenced by llvm::createX86GlobalBaseRegPass().
getRAIndex()
int llvm::X86MachineFunctionInfo::getRAIndex () const inline
Definition at line 137 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86TargetLowering::getReturnAddressFrameIndex().
getRegSaveFrameIndex()
int llvm::X86MachineFunctionInfo::getRegSaveFrameIndex () const inline
Definition at line 155 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
getRestoreBasePointer()
bool llvm::X86MachineFunctionInfo::getRestoreBasePointer () const inline
Definition at line 123 of file X86MachineFunctionInfo.h.
References setRestoreBasePointer().
Referenced by llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::getFrameIndexReference().
getRestoreBasePointerOffset()
int llvm::X86MachineFunctionInfo::getRestoreBasePointerOffset () const inline
Definition at line 125 of file X86MachineFunctionInfo.h.
Referenced by getRetpolineSymbol().
getSEHFramePtrSaveIndex()
int llvm::X86MachineFunctionInfo::getSEHFramePtrSaveIndex () const inline
Definition at line 173 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::restoreWin32EHStackPointers().
getSRetReturnReg()
unsigned llvm::X86MachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 146 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo(), and Passv64i1ArgInRegs().
getTCReturnAddrDelta()
int llvm::X86MachineFunctionInfo::getTCReturnAddrDelta () const inline
Definition at line 143 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::getFrameIndexReference(), and llvm::X86FrameLowering::getFrameIndexReferencePreferSP().
getUsesRedZone()
bool llvm::X86MachineFunctionInfo::getUsesRedZone () const inline
Definition at line 183 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue(), and llvm::X86InstrInfo::isFunctionSafeToOutlineFrom().
getVarArgsFPOffset()
unsigned llvm::X86MachineFunctionInfo::getVarArgsFPOffset () const inline
Definition at line 161 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
getVarArgsFrameIndex()
int llvm::X86MachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 152 of file X86MachineFunctionInfo.h.
getVarArgsGPOffset()
unsigned llvm::X86MachineFunctionInfo::getVarArgsGPOffset () const inline
Definition at line 158 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
getWinEHXMMSlotInfo() [1/2]
DenseMap<int, unsigned>& llvm::X86MachineFunctionInfo::getWinEHXMMSlotInfo () inline
Definition at line 127 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::getWin64EHFrameIndexRef(), and isFuncletReturnInstr().
getWinEHXMMSlotInfo() [2/2]
const DenseMap<int, unsigned>& llvm::X86MachineFunctionInfo::getWinEHXMMSlotInfo () const inline
Definition at line 128 of file X86MachineFunctionInfo.h.
hasWinAlloca()
bool llvm::X86MachineFunctionInfo::hasWinAlloca () const inline
Definition at line 186 of file X86MachineFunctionInfo.h.
Referenced by getSubOpcode().
incNumLocalDynamicTLSAccesses()
void llvm::X86MachineFunctionInfo::incNumLocalDynamicTLSAccesses () inline
Definition at line 168 of file X86MachineFunctionInfo.h.
Referenced by LowerToTLSLocalDynamicModel().
isSplitCSR()
bool llvm::X86MachineFunctionInfo::isSplitCSR () const inline
Definition at line 180 of file X86MachineFunctionInfo.h.
setArgumentStackSize()
void llvm::X86MachineFunctionInfo::setArgumentStackSize (unsigned size) inline
Definition at line 165 of file X86MachineFunctionInfo.h.
References llvm::size().
Referenced by isSortedByValueNo().
setBytesToPopOnReturn()
void llvm::X86MachineFunctionInfo::setBytesToPopOnReturn (unsigned bytes) inline
Definition at line 135 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
setCalleeSavedFrameSize()
void llvm::X86MachineFunctionInfo::setCalleeSavedFrameSize (unsigned bytes) inline
Definition at line 132 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), and llvm::X86FrameLowering::emitPrologue().
setFAIndex()
void llvm::X86MachineFunctionInfo::setFAIndex (int Index) inline
Definition at line 141 of file X86MachineFunctionInfo.h.
Referenced by LowerINTRINSIC_W_CHAIN().
setForceFramePointer()
void llvm::X86MachineFunctionInfo::setForceFramePointer (bool forceFP) inline
Definition at line 118 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
setGlobalBaseReg()
void llvm::X86MachineFunctionInfo::setGlobalBaseReg (unsigned Reg) inline
Definition at line 150 of file X86MachineFunctionInfo.h.
References Reg.
Referenced by llvm::X86InstrInfo::getGlobalBaseReg().
setHasPushSequences()
void llvm::X86MachineFunctionInfo::setHasPushSequences (bool HasPush) inline
Definition at line 121 of file X86MachineFunctionInfo.h.
Referenced by INITIALIZE_PASS().
setHasSEHFramePtrSave()
void llvm::X86MachineFunctionInfo::setHasSEHFramePtrSave (bool V) inline
Definition at line 171 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots().
setHasWinAlloca()
void llvm::X86MachineFunctionInfo::setHasWinAlloca (bool v) inline
Definition at line 187 of file X86MachineFunctionInfo.h.
setIsSplitCSR()
void llvm::X86MachineFunctionInfo::setIsSplitCSR (bool s) inline
Definition at line 181 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86TargetLowering::isIntDivCheap().
setRAIndex()
void llvm::X86MachineFunctionInfo::setRAIndex (int Index) inline
Definition at line 138 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86TargetLowering::getReturnAddressFrameIndex().
setRegSaveFrameIndex()
void llvm::X86MachineFunctionInfo::setRegSaveFrameIndex (int Idx) inline
Definition at line 156 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
setRestoreBasePointer()
void X86MachineFunctionInfo::setRestoreBasePointer (const MachineFunction * MF)
Definition at line 18 of file X86MachineFunctionInfo.cpp.
References contains(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::X86RegisterInfo::getSlotSize(), llvm::MachineFunction::getSubtarget(), and Reg.
Referenced by getRestoreBasePointer(), and getRetpolineSymbol().
setSEHFramePtrSaveIndex()
void llvm::X86MachineFunctionInfo::setSEHFramePtrSaveIndex (int Index) inline
Definition at line 174 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots().
setSRetReturnReg()
void llvm::X86MachineFunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 147 of file X86MachineFunctionInfo.h.
References Reg.
Referenced by isSortedByValueNo().
setTCReturnAddrDelta()
void llvm::X86MachineFunctionInfo::setTCReturnAddrDelta (int delta) inline
Definition at line 144 of file X86MachineFunctionInfo.h.
Referenced by getMOVL().
setUsesRedZone()
void llvm::X86MachineFunctionInfo::setUsesRedZone (bool V) inline
Definition at line 184 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue().
setVarArgsFPOffset()
void llvm::X86MachineFunctionInfo::setVarArgsFPOffset (unsigned Offset) inline
Definition at line 162 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
setVarArgsFrameIndex()
void llvm::X86MachineFunctionInfo::setVarArgsFrameIndex (int Idx) inline
Definition at line 153 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
setVarArgsGPOffset()
void llvm::X86MachineFunctionInfo::setVarArgsGPOffset (unsigned Offset) inline
Definition at line 159 of file X86MachineFunctionInfo.h.
Referenced by isSortedByValueNo().
The documentation for this class was generated from the following files:
lib/Target/X86/X86MachineFunctionInfo.h
lib/Target/X86/X86MachineFunctionInfo.cpp