LLVM: llvm::object::ArchiveMemberHeader Class Reference
llvm::object::ArchiveMemberHeader Class Reference
#include "llvm/Object/Archive.h"
Public Member Functions
ArchiveMemberHeader (Archive const *Parent, const char *RawHeaderPtr, uint64_t Size, Error *Err)
Expected< StringRef > getRawName () const
Get the name without looking up long names.
Expected< StringRef > getName (uint64_t Size) const
Get the name looking up long names.
Expected< uint64_t > getSize () const
Expected< sys::fs::perms > getAccessMode () const
Expected< sys::TimePoint< std::chrono::seconds > > getLastModified () const
StringRef getRawLastModified () const
Expected< unsigned > getUID () const
Expected< unsigned > getGID () const
uint64_t getSizeOf () const
Friends
class Archive
Detailed Description
Definition at line 37 of file Archive.h.
Constructor & Destructor Documentation
ArchiveMemberHeader()
ArchiveMemberHeader::ArchiveMemberHeader (Archive const * Parent, const char * RawHeaderPtr, uint64_t Size, Error * Err)
Definition at line 53 of file Archive.cpp.
Member Function Documentation
getAccessMode()
Expected< sys::fs::perms > ArchiveMemberHeader::getAccessMode () const
Definition at line 244 of file Archive.cpp.
References llvm::StringRef::data(), llvm::raw_ostream::flush(), llvm::StringRef::getAsInteger(), llvm::object::Binary::getData(), malformedError(), llvm::MipsISD::Ret, llvm::StringRef::rtrim(), and llvm::raw_ostream::write_escaped().
Referenced by llvm::object::Archive::Child::getAccessMode().
getGID()
Expected< unsigned > ArchiveMemberHeader::getGID () const
Definition at line 302 of file Archive.cpp.
References llvm::StringRef::data(), llvm::StringRef::empty(), llvm::raw_ostream::flush(), llvm::StringRef::getAsInteger(), llvm::object::Binary::getData(), malformedError(), llvm::MipsISD::Ret, llvm::StringRef::rtrim(), and llvm::raw_ostream::write_escaped().
Referenced by llvm::object::Archive::Child::getGID(), and getRawLastModified().
getLastModified()
Expected< sys::TimePoint< std::chrono::seconds > > ArchiveMemberHeader::getLastModified () const
Definition at line 263 of file Archive.cpp.
References llvm::StringRef::data(), llvm::raw_ostream::flush(), llvm::StringRef::getAsInteger(), llvm::object::Binary::getData(), malformedError(), llvm::StringRef::rtrim(), llvm::sys::toTimePoint(), and llvm::raw_ostream::write_escaped().
Referenced by llvm::object::Archive::Child::getLastModified().
getName()
Expected< StringRef > ArchiveMemberHeader::getName (uint64_t Size) const
Get the name looking up long names.
Definition at line 128 of file Archive.cpp.
References llvm::StringRef::data(), llvm::raw_ostream::flush(), llvm::Expected< T >::get(), llvm::StringRef::getAsInteger(), llvm::object::Binary::getData(), getRawName(), llvm::object::Archive::getStringTable(), llvm::object::Archive::K_GNU, llvm::object::Archive::K_GNU64, llvm::object::Archive::kind(), malformedError(), Name, offsetof, llvm::StringRef::rtrim(), llvm::StringRef::size(), llvm::StringRef::substr(), llvm::Expected< T >::takeError(), and llvm::raw_ostream::write_escaped().
Referenced by llvm::object::Archive::Child::getName(), llvm::object::Archive::Child::getParent(), and llvm::object::Archive::Symbol::operator==().
getRawLastModified()
StringRef llvm::object::ArchiveMemberHeader::getRawLastModified () const inline
Definition at line 56 of file Archive.h.
References getGID(), getUID(), and llvm::StringRef::rtrim().
Referenced by llvm::object::Archive::Child::getRawLastModified().
getRawName()
Expected< StringRef > ArchiveMemberHeader::getRawName () const
Get the name without looking up long names.
Definition at line 100 of file Archive.cpp.
References assert(), llvm::StringRef::data(), llvm::sys::path::end(), llvm::StringRef::find(), llvm::object::Binary::getData(), llvm::object::Archive::K_BSD, llvm::object::Archive::K_DARWIN64, llvm::object::Archive::kind(), malformedError(), and llvm::StringRef::npos.
Referenced by getName(), llvm::object::Archive::Child::getRawName(), and llvm::object::Archive::Child::getRawSize().
getSize()
Expected< uint64_t > ArchiveMemberHeader::getSize () const
Definition at line 226 of file Archive.cpp.
References llvm::StringRef::data(), llvm::raw_ostream::flush(), llvm::StringRef::getAsInteger(), llvm::object::Binary::getData(), malformedError(), llvm::MipsISD::Ret, llvm::StringRef::rtrim(), and llvm::raw_ostream::write_escaped().
Referenced by llvm::object::Archive::Child::getAccessMode(), llvm::object::Archive::Child::getRawSize(), and llvm::object::Archive::Child::getSize().
getSizeOf()
uint64_t llvm::object::ArchiveMemberHeader::getSizeOf () const inline
Definition at line 65 of file Archive.h.
References Name, Size, and llvm::MCID::Terminator.
Referenced by llvm::object::Archive::Child::getName().
getUID()
Expected< unsigned > ArchiveMemberHeader::getUID () const
Definition at line 283 of file Archive.cpp.
References llvm::StringRef::data(), llvm::StringRef::empty(), llvm::raw_ostream::flush(), llvm::StringRef::getAsInteger(), llvm::object::Binary::getData(), malformedError(), llvm::MipsISD::Ret, llvm::StringRef::rtrim(), and llvm::raw_ostream::write_escaped().
Referenced by getRawLastModified(), and llvm::object::Archive::Child::getUID().
Friends And Related Function Documentation
Archive
friend class Archive friend
Definition at line 39 of file Archive.h.
Referenced by llvm::object::Archive::symbol_iterator::operator++().
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp