LLVM: llvm::PressureDiff Class Reference
llvm::PressureDiff Class Reference
List of PressureChanges in order of increasing, unique PSetID.
#include "llvm/CodeGen/RegisterPressure.h"
Public Types
using const_iterator = const PressureChange *
Public Member Functions
const_iterator begin () const
const_iterator end () const
void addPressureChange (unsigned RegUnit, bool IsDec, const MachineRegisterInfo *MRI)
Add a change in pressure to the pressure diff of a given instruction.
void dump (const TargetRegisterInfo &TRI) const
Detailed Description
List of PressureChanges in order of increasing, unique PSetID.
Use a small fixed number, because we can fit more PressureChanges in an empty SmallVector than ever need to be tracked per register class. If more PSets are affected, then we only track the most constrained.
Definition at line 141 of file RegisterPressure.h.
Member Typedef Documentation
const_iterator
using llvm::PressureDiff::const_iterator = const PressureChange *
Definition at line 155 of file RegisterPressure.h.
Member Function Documentation
addPressureChange()
void PressureDiff::addPressureChange (unsigned RegUnit, bool IsDec, const MachineRegisterInfo * MRI)
Add a change in pressure to the pressure diff of a given instruction.
Definition at line 670 of file RegisterPressure.cpp.
References E, llvm::MachineRegisterInfo::getPressureSets(), llvm::PressureChange::getPSet(), llvm::PressureChange::getUnitInc(), llvm::PSetIterator::getWeight(), I, llvm::PressureChange::isValid(), llvm::PSetIterator::isValid(), llvm::PressureChange::setUnitInc(), and std::swap().
Referenced by llvm::PressureDiffs::addInstruction(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
begin()
const_iterator llvm::PressureDiff::begin () const inline
Definition at line 157 of file RegisterPressure.h.
Referenced by llvm::PressureDiffs::addInstruction(), and llvm::RegPressureTracker::getUpwardPressureDelta().
dump()
LLVM_DUMP_METHOD void PressureDiff::dump (const TargetRegisterInfo & TRI) const
Definition at line 126 of file RegisterPressure.cpp.
References llvm::dbgs(), llvm::PressureChange::getPSet(), llvm::TargetRegisterInfo::getRegPressureSetName(), llvm::PressureChange::getUnitInc(), llvm::PressureChange::isValid(), and LLVM_DUMP_METHOD.
Referenced by llvm::RegPressureTracker::getMaxUpwardPressureDelta(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
end()
const_iterator llvm::PressureDiff::end () const inline
Definition at line 158 of file RegisterPressure.h.
References llvm::dump(), MRI, llvm::RegisterMaskPair::RegUnit, and TRI.
Referenced by llvm::RegPressureTracker::getUpwardPressureDelta().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterPressure.h
lib/CodeGen/RegisterPressure.cpp