LLVM: llvm::codeview::DebugLinesSubsection Class Reference
llvm::codeview::DebugLinesSubsection Class Reference final
#include "llvm/DebugInfo/CodeView/DebugLinesSubsection.h"
Public Member Functions
DebugLinesSubsection (DebugChecksumsSubsection &Checksums, DebugStringTableSubsection &Strings)
void createBlock (StringRef FileName)
void addLineInfo (uint32_t Offset, const LineInfo &Line)
void addLineAndColumnInfo (uint32_t Offset, const LineInfo &Line, uint32_t ColStart, uint32_t ColEnd)
uint32_t calculateSerializedSize () const override
Error commit (BinaryStreamWriter &Writer) const override
void setRelocationAddress (uint16_t Segment, uint32_t Offset)
void setCodeSize (uint32_t Size)
void setFlags (LineFlags Flags)
bool hasColumnInfo () const
Public Member Functions inherited from llvm::codeview::DebugSubsection
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsection
static bool classof (const DebugSubsection *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsection
DebugSubsectionKind Kind
Detailed Description
Definition at line 105 of file DebugLinesSubsection.h.
Constructor & Destructor Documentation
DebugLinesSubsection()
DebugLinesSubsection::DebugLinesSubsection (DebugChecksumsSubsection & Checksums, DebugStringTableSubsection & Strings)
Definition at line 71 of file DebugLinesSubsection.cpp.
Member Function Documentation
addLineAndColumnInfo()
void DebugLinesSubsection::addLineAndColumnInfo (uint32_t Offset, const LineInfo & Line, uint32_t ColStart, uint32_t ColEnd)
Definition at line 89 of file DebugLinesSubsection.cpp.
References addLineInfo(), assert(), B, llvm::codeview::ColumnNumberEntry::EndColumn, and llvm::codeview::ColumnNumberEntry::StartColumn.
addLineInfo()
void DebugLinesSubsection::addLineInfo (uint32_t Offset, const LineInfo & Line)
Definition at line 81 of file DebugLinesSubsection.cpp.
References B, llvm::codeview::LineNumberEntry::Flags, llvm::codeview::LineInfo::getRawData(), and llvm::codeview::LineNumberEntry::Offset.
Referenced by addLineAndColumnInfo().
calculateSerializedSize()
uint32_t DebugLinesSubsection::calculateSerializedSize () const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 137 of file DebugLinesSubsection.cpp.
References B, hasColumnInfo(), and Size.
classof()
static bool llvm::codeview::DebugLinesSubsection::classof (const DebugSubsection * S) inline static
Definition at line 119 of file DebugLinesSubsection.h.
References llvm::codeview::LineFragmentHeader::CodeSize, llvm::codeview::LineFragmentHeader::Flags, llvm::codeview::DebugSubsection::kind(), llvm::codeview::LF_None, llvm::codeview::Lines, llvm::codeview::LineFragmentHeader::RelocOffset, llvm::codeview::LineFragmentHeader::RelocSegment, and Size.
commit()
Error DebugLinesSubsection::commit (BinaryStreamWriter & Writer) const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 103 of file DebugLinesSubsection.cpp.
References assert(), B, llvm::codeview::LineBlockFragmentHeader::BlockSize, llvm::codeview::LineFragmentHeader::CodeSize, llvm::codeview::EC, llvm::codeview::LineFragmentHeader::Flags, hasColumnInfo(), llvm::codeview::LF_HaveColumns, llvm::makeArrayRef(), llvm::codeview::LineBlockFragmentHeader::NameIndex, llvm::codeview::LineBlockFragmentHeader::NumLines, llvm::codeview::LineFragmentHeader::RelocOffset, llvm::codeview::LineFragmentHeader::RelocSegment, llvm::Error::success(), llvm::BinaryStreamWriter::writeArray(), and llvm::BinaryStreamWriter::writeObject().
createBlock()
void DebugLinesSubsection::createBlock (StringRef FileName)
Definition at line 75 of file DebugLinesSubsection.cpp.
References llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset().
hasColumnInfo()
bool DebugLinesSubsection::hasColumnInfo () const
Definition at line 158 of file DebugLinesSubsection.cpp.
References llvm::codeview::LF_HaveColumns.
Referenced by calculateSerializedSize(), and commit().
setCodeSize()
void DebugLinesSubsection::setCodeSize (uint32_t Size)
Definition at line 154 of file DebugLinesSubsection.cpp.
References Size.
setFlags()
void DebugLinesSubsection::setFlags (LineFlags Flags)
Definition at line 156 of file DebugLinesSubsection.cpp.
setRelocationAddress()
void DebugLinesSubsection::setRelocationAddress (uint16_t Segment, uint32_t Offset)
Definition at line 148 of file DebugLinesSubsection.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugLinesSubsection.h
lib/DebugInfo/CodeView/DebugLinesSubsection.cpp