LLVM: llvm::symbolize::DIPrinter Class Reference
llvm::symbolize::DIPrinter Class Reference
#include "llvm/DebugInfo/Symbolize/DIPrinter.h"
Public Types
enum OutputStyle { OutputStyle::LLVM, OutputStyle::GNU }
Public Member Functions
DIPrinter (raw_ostream &OS, bool PrintFunctionNames=true, bool PrintPretty=false, int PrintSourceContext=0, bool Verbose=false, bool Basenames=false, OutputStyle Style=OutputStyle::LLVM)
DIPrinter & operator<< (const DILineInfo &Info)
DIPrinter & operator<< (const DIInliningInfo &Info)
DIPrinter & operator<< (const DIGlobal &Global)
DIPrinter & operator<< (const DILocal &Local)
Detailed Description
Definition at line 27 of file DIPrinter.h.
Member Enumeration Documentation
OutputStyle
enum llvm::symbolize::DIPrinter::OutputStyle strong
Enumerator
LLVM
GNU
Definition at line 29 of file DIPrinter.h.
Constructor & Destructor Documentation
DIPrinter()
llvm::symbolize::DIPrinter::DIPrinter (raw_ostream & OS, bool PrintFunctionNames = true, bool PrintPretty = false, int PrintSourceContext = 0, bool Verbose = false, bool Basenames = false, OutputStyle Style = OutputStyle::LLVM) inline
Definition at line 44 of file DIPrinter.h.
References operator<<().
Member Function Documentation
operator<<() [1/4]
DIPrinter & llvm::symbolize::DIPrinter::operator<< (const DILineInfo & Info)
Definition at line 95 of file DIPrinter.cpp.
Referenced by DIPrinter().
operator<<() [2/4]
DIPrinter & llvm::symbolize::DIPrinter::operator<< (const DIInliningInfo & Info)
Definition at line 100 of file DIPrinter.cpp.
References llvm::DIInliningInfo::getFrame(), and llvm::DIInliningInfo::getNumberOfFrames().
operator<<() [3/4]
DIPrinter & llvm::symbolize::DIPrinter::operator<< (const DIGlobal & Global)
Definition at line 111 of file DIPrinter.cpp.
References llvm::DILineInfo::Addr2LineBadString, llvm::DILineInfo::BadString, llvm::DIGlobal::Name, Name, llvm::DIGlobal::Size, and llvm::DIGlobal::Start.
operator<<() [4/4]
DIPrinter & llvm::symbolize::DIPrinter::operator<< (const DILocal & Local)
Definition at line 120 of file DIPrinter.cpp.
References llvm::DILocal::DeclFile, llvm::DILocal::DeclLine, llvm::DILocal::FrameOffset, llvm::DILocal::FunctionName, llvm::DILocal::Name, llvm::DILocal::Size, and llvm::DILocal::TagOffset.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/DIPrinter.h
lib/DebugInfo/Symbolize/DIPrinter.cpp