LLVM: llvm::sys::Process Class Reference
llvm::sys::Process Class Reference
A collection of legacy interfaces for querying information about the current executing process.
#include "llvm/Support/Process.h"
Static Public Member Functions
static Expected< unsigned > getPageSize ()
Get the process's page size.
static unsigned getPageSizeEstimate ()
Get the process's estimated page size.
static size_t GetMallocUsage ()
Return process memory usage.
static void GetTimeUsage (TimePoint<> &elapsed, std::chrono::nanoseconds &user_time, std::chrono::nanoseconds &sys_time)
This static function will set user_time to the amount of CPU time spent in user (non-kernel) mode and sys_time to the amount of CPU time spent in system (kernel) mode.
static void PreventCoreFiles ()
This function makes the necessary calls to the operating system to prevent core files or any other kind of large memory dumps that can occur when a program fails.
static bool AreCoreFilesPrevented ()
true if PreventCoreFiles has been called, false otherwise.
static Optional< std::string > GetEnv (StringRef name)
static Optional< std::string > FindInEnvPath (StringRef EnvName, StringRef FileName, ArrayRef< std::string > IgnoreList)
This function searches for an existing file in the list of directories in a PATH like environment variable, and returns the first file found, according to the order of the entries in the PATH like environment variable.
static Optional< std::string > FindInEnvPath (StringRef EnvName, StringRef FileName)
static std::error_code FixupStandardFileDescriptors ()
static std::error_code SafelyCloseFileDescriptor (int FD)
static bool StandardInIsUserInput ()
This function determines if the standard input is connected directly to a user's input (keyboard probably), rather than coming from a file or pipe.
static bool StandardOutIsDisplayed ()
This function determines if the standard output is connected to a "tty" or "console" window.
static bool StandardErrIsDisplayed ()
This function determines if the standard error is connected to a "tty" or "console" window.
static bool FileDescriptorIsDisplayed (int fd)
This function determines if the given file descriptor is connected to a "tty" or "console" window.
static bool FileDescriptorHasColors (int fd)
This function determines if the given file descriptor is displayd and supports colors.
static unsigned StandardOutColumns ()
This function determines the number of columns in the window if standard output is connected to a "tty" or "console" window.
static unsigned StandardErrColumns ()
This function determines the number of columns in the window if standard error is connected to a "tty" or "console" window.
static bool StandardOutHasColors ()
This function determines whether the terminal connected to standard output supports colors.
static bool StandardErrHasColors ()
This function determines whether the terminal connected to standard error supports colors.
static void UseANSIEscapeCodes (bool enable)
Enables or disables whether ANSI escape sequences are used to output colors.
static bool ColorNeedsFlush ()
Whether changing colors requires the output to be flushed.
static const char * OutputColor (char c, bool bold, bool bg)
This function returns the colorcode escape sequences.
static const char * OutputBold (bool bg)
Same as OutputColor, but only enables the bold attribute.
static const char * OutputReverse ()
This function returns the escape sequence to reverse forground and background colors.
static const char * ResetColor ()
Resets the terminals colors, or returns an escape sequence to do so.
static unsigned GetRandomNumber ()
Get the result of a process wide random number generator.
static LLVM_ATTRIBUTE_NORETURN void Exit (int RetCode)
Equivalent to ::exit(), except when running inside a CrashRecoveryContext.
Detailed Description
A collection of legacy interfaces for querying information about the current executing process.
Definition at line 43 of file Process.h.
Member Function Documentation
AreCoreFilesPrevented()
bool Process::AreCoreFilesPrevented () static
true if PreventCoreFiles has been called, false otherwise.
Definition at line 90 of file Process.cpp.
References coreFilesPrevented, and LLVM_ATTRIBUTE_NORETURN.
Referenced by getPageSizeEstimate().
ColorNeedsFlush()
static bool llvm::sys::Process::ColorNeedsFlush () static
Whether changing colors requires the output to be flushed.
This is needed on systems that don't support escape sequences for changing colors.
Referenced by llvm::raw_fd_ostream::changeColor(), getPageSizeEstimate(), llvm::raw_fd_ostream::resetColor(), and llvm::raw_fd_ostream::reverseColor().
Exit()
LLVM_ATTRIBUTE_NORETURN void Process::Exit (int RetCode) static
Equivalent to ::exit(), except when running inside a CrashRecoveryContext.
In that case, the control flow will resume after RunSafely(), like for a crash, rather than exiting the current process.
Definition at line 93 of file Process.cpp.
References llvm::CrashRecoveryContext::GetCurrent().
Referenced by getPageSizeEstimate(), and llvm::report_fatal_error().
FileDescriptorHasColors()
static bool llvm::sys::Process::FileDescriptorHasColors (int fd) static
This function determines if the given file descriptor is displayd and supports colors.
Referenced by getPageSizeEstimate(), and llvm::raw_fd_ostream::has_colors().
FileDescriptorIsDisplayed()
static bool llvm::sys::Process::FileDescriptorIsDisplayed (int fd) static
This function determines if the given file descriptor is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Referenced by getPageSizeEstimate(), and llvm::raw_fd_ostream::is_displayed().
FindInEnvPath() [1/2]
Optional< std::string > Process::FindInEnvPath (StringRef EnvName, StringRef FileName, ArrayRef< std::string > IgnoreList) static
This function searches for an existing file in the list of directories in a PATH like environment variable, and returns the first file found, according to the order of the entries in the PATH like environment variable.
If an ignore list is specified, then any folder which is in the PATH like environment variable but is also in IgnoreList is not considered.
Definition at line 36 of file Process.cpp.
References llvm::any_of(), llvm::sys::path::append(), assert(), llvm::sys::EnvPathSeparator, llvm::sys::fs::equivalent(), llvm::sys::fs::exists(), GetEnv(), llvm::Optional< T >::getValue(), llvm::Optional< T >::hasValue(), llvm::sys::path::is_absolute(), llvm::SplitString(), and llvm::SmallString< InternalLen >::str().
Referenced by FindInEnvPath(), and getPageSizeEstimate().
FindInEnvPath() [2/2]
Optional< std::string > Process::FindInEnvPath (StringRef EnvName, StringRef FileName) static
Definition at line 31 of file Process.cpp.
References FindInEnvPath().
FixupStandardFileDescriptors()
static std::error_code llvm::sys::Process::FixupStandardFileDescriptors () static
Referenced by getPageSizeEstimate().
GetEnv()
static Optional<std::string> llvm::sys::Process::GetEnv (StringRef name) static
Referenced by FindInEnvPath(), getPageSizeEstimate(), getSearchPaths(), llvm::cl::ParseCommandLineOptions(), and llvm::cl::ParseEnvironmentOptions().
GetMallocUsage()
static size_t llvm::sys::Process::GetMallocUsage () static
Return process memory usage.
This static function will return the total amount of memory allocated by the process. This only counts the memory allocated via the malloc, calloc and realloc functions and includes any "free" holes in the allocated space.
Referenced by getMemUsage(), and getPageSizeEstimate().
getPageSize()
static Expected<unsigned> llvm::sys::Process::getPageSize () static
Get the process's page size.
This may fail if the underlying syscall returns an error. In most cases, page size information is used for optimization, and this error can be safely discarded by calling consumeError, and an estimated page size substituted instead.
Referenced by getPageSizeEstimate().
getPageSizeEstimate()
static unsigned llvm::sys::Process::getPageSizeEstimate () inline static
Get the process's estimated page size.
This function always succeeds, but if the underlying syscall to determine the page size fails then this will silently return an estimated page size. The estimated page size is guaranteed to be a power of 2.
Definition at line 56 of file Process.h.
References AreCoreFilesPrevented(), ColorNeedsFlush(), llvm::consumeError(), Exit(), FileDescriptorHasColors(), FileDescriptorIsDisplayed(), FindInEnvPath(), FixupStandardFileDescriptors(), GetEnv(), GetMallocUsage(), getPageSize(), GetRandomNumber(), GetTimeUsage(), LLVM_ATTRIBUTE_NORETURN, name, OutputBold(), OutputColor(), OutputReverse(), PageSize, PreventCoreFiles(), ResetColor(), SafelyCloseFileDescriptor(), StandardErrColumns(), StandardErrHasColors(), StandardErrIsDisplayed(), StandardInIsUserInput(), StandardOutColumns(), StandardOutHasColors(), StandardOutIsDisplayed(), and UseANSIEscapeCodes().
Referenced by llvm::jitlink::InProcessMemoryManager::allocate(), llvm::orc::OrcAArch64::emitIndirectStubsBlock(), llvm::orc::OrcX86_64_Base::emitIndirectStubsBlock(), llvm::orc::OrcI386::emitIndirectStubsBlock(), llvm::orc::OrcMips32_Base::emitIndirectStubsBlock(), llvm::orc::OrcMips64::emitIndirectStubsBlock(), getOpenFileImpl(), and llvm::trimBlockToPageSize().
GetRandomNumber()
static unsigned llvm::sys::Process::GetRandomNumber () static
Get the result of a process wide random number generator.
The generator will be automatically seeded in non-deterministic fashion.
Referenced by llvm::sys::fs::createUniquePath(), and getPageSizeEstimate().
GetTimeUsage()
static void llvm::sys::Process::GetTimeUsage (TimePoint<> & elapsed, std::chrono::nanoseconds & user_time, std::chrono::nanoseconds & sys_time) static
This static function will set user_time to the amount of CPU time spent in user (non-kernel) mode and sys_time to the amount of CPU time spent in system (kernel) mode.
If the operating system does not support collection of these metrics, a zero duration will be for both values.
Parameters
elapsed Returns the system_clock::now() giving current time
user_time Returns the current amount of user time for the process
sys_time Returns the current amount of system time for the process
Referenced by getPageSizeEstimate().
OutputBold()
static const char* llvm::sys::Process::OutputBold (bool bg) static
Same as OutputColor, but only enables the bold attribute.
Referenced by llvm::raw_fd_ostream::changeColor(), and getPageSizeEstimate().
OutputColor()
static const char* llvm::sys::Process::OutputColor (char c, bool bold, bool bg) static
This function returns the colorcode escape sequences.
If ColorNeedsFlush() is true then this function will change the colors and return an empty escape sequence. In that case it is the responsibility of the client to flush the output stream prior to calling this function.
Referenced by llvm::raw_fd_ostream::changeColor(), and getPageSizeEstimate().
OutputReverse()
static const char* llvm::sys::Process::OutputReverse () static
This function returns the escape sequence to reverse forground and background colors.
Referenced by getPageSizeEstimate(), and llvm::raw_fd_ostream::reverseColor().
PreventCoreFiles()
static void llvm::sys::Process::PreventCoreFiles () static
This function makes the necessary calls to the operating system to prevent core files or any other kind of large memory dumps that can occur when a program fails.
Prevent core file generation.
Referenced by getPageSizeEstimate().
ResetColor()
static const char* llvm::sys::Process::ResetColor () static
Resets the terminals colors, or returns an escape sequence to do so.
Referenced by getPageSizeEstimate(), and llvm::raw_fd_ostream::resetColor().
SafelyCloseFileDescriptor()
static std::error_code llvm::sys::Process::SafelyCloseFileDescriptor (int FD) static
Referenced by llvm::raw_fd_ostream::close(), copyAccessAndModificationTime(), getPageSizeEstimate(), and llvm::raw_fd_ostream::~raw_fd_ostream().
StandardErrColumns()
static unsigned llvm::sys::Process::StandardErrColumns () static
This function determines the number of columns in the window if standard error is connected to a "tty" or "console" window.
If standard error is not connected to a tty or console, or if the number of columns cannot be determined, this routine returns zero.
Referenced by getPageSizeEstimate().
StandardErrHasColors()
static bool llvm::sys::Process::StandardErrHasColors () static
This function determines whether the terminal connected to standard error supports colors.
If standard error is not connected to a terminal, this function returns false.
Referenced by getPageSizeEstimate().
StandardErrIsDisplayed()
static bool llvm::sys::Process::StandardErrIsDisplayed () static
This function determines if the standard error is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Referenced by getPageSizeEstimate().
StandardInIsUserInput()
static bool llvm::sys::Process::StandardInIsUserInput () static
This function determines if the standard input is connected directly to a user's input (keyboard probably), rather than coming from a file or pipe.
Referenced by getPageSizeEstimate().
StandardOutColumns()
static unsigned llvm::sys::Process::StandardOutColumns () static
This function determines the number of columns in the window if standard output is connected to a "tty" or "console" window.
If standard output is not connected to a tty or console, or if the number of columns cannot be determined, this routine returns zero.
Referenced by getPageSizeEstimate().
StandardOutHasColors()
static bool llvm::sys::Process::StandardOutHasColors () static
This function determines whether the terminal connected to standard output supports colors.
If standard output is not connected to a terminal, this function returns false.
Referenced by getPageSizeEstimate().
StandardOutIsDisplayed()
static bool llvm::sys::Process::StandardOutIsDisplayed () static
This function determines if the standard output is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Referenced by getPageSizeEstimate().
UseANSIEscapeCodes()
static void llvm::sys::Process::UseANSIEscapeCodes (bool enable) static
Enables or disables whether ANSI escape sequences are used to output colors.
This only has an effect on Windows. Note: Setting this option is not thread-safe and should only be done during initialization.
Referenced by getPageSizeEstimate().
The documentation for this class was generated from the following files:
include/llvm/Support/Process.h
lib/Support/Process.cpp