LLVM: llvm::BranchProbability Class Reference
llvm::BranchProbability Class Reference
#include "llvm/Support/BranchProbability.h"
Public Member Functions
BranchProbability ()
BranchProbability (uint32_t Numerator, uint32_t Denominator)
bool isZero () const
bool isUnknown () const
uint32_t getNumerator () const
BranchProbability getCompl () const
raw_ostream & print (raw_ostream &OS) const
void dump () const
uint64_t scale (uint64_t Num) const
Scale a large integer.
uint64_t scaleByInverse (uint64_t Num) const
Scale a large integer by the inverse.
BranchProbability & operator+= (BranchProbability RHS)
BranchProbability & operator-= (BranchProbability RHS)
BranchProbability & operator*= (BranchProbability RHS)
BranchProbability & operator*= (uint32_t RHS)
BranchProbability & operator/= (BranchProbability RHS)
BranchProbability & operator/= (uint32_t RHS)
BranchProbability operator+ (BranchProbability RHS) const
BranchProbability operator- (BranchProbability RHS) const
BranchProbability operator* (BranchProbability RHS) const
BranchProbability operator* (uint32_t RHS) const
BranchProbability operator/ (BranchProbability RHS) const
BranchProbability operator/ (uint32_t RHS) const
bool operator== (BranchProbability RHS) const
bool operator!= (BranchProbability RHS) const
bool operator< (BranchProbability RHS) const
bool operator> (BranchProbability RHS) const
bool operator<= (BranchProbability RHS) const
bool operator>= (BranchProbability RHS) const
Static Public Member Functions
static BranchProbability getZero ()
static BranchProbability getOne ()
static BranchProbability getUnknown ()
static BranchProbability getRaw (uint32_t N)
static BranchProbability getBranchProbability (uint64_t Numerator, uint64_t Denominator)
template<class ProbabilityIter >
static void normalizeProbabilities (ProbabilityIter Begin, ProbabilityIter End)
static uint32_t getDenominator ()
Detailed Description
Definition at line 30 of file BranchProbability.h.
Constructor & Destructor Documentation
BranchProbability() [1/2]
llvm::BranchProbability::BranchProbability () inline
Definition at line 43 of file BranchProbability.h.
Referenced by getBranchProbability(), getCompl(), getOne(), getRaw(), getUnknown(), and getZero().
BranchProbability() [2/2]
BranchProbability::BranchProbability (uint32_t Numerator, uint32_t Denominator)
Definition at line 39 of file BranchProbability.cpp.
References assert().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void BranchProbability::dump () const
Definition at line 36 of file BranchProbability.cpp.
References llvm::dbgs(), and print().
Referenced by getCompl().
getBranchProbability()
BranchProbability BranchProbability::getBranchProbability (uint64_t Numerator, uint64_t Denominator) static
Definition at line 52 of file BranchProbability.cpp.
References assert(), and BranchProbability().
Referenced by checkMDProf(), getCHRBiasThreshold(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), getRaw(), hasProfileData(), isFormingBranchFromSelectProfitable(), llvm::JumpThreadingPass::ThreadEdge(), UpdatePDTWorklist(), and updatePredecessorProfileMetadata().
getCompl()
BranchProbability llvm::BranchProbability::getCompl () const inline
Definition at line 69 of file BranchProbability.h.
References BranchProbability(), dump(), print(), scale(), and scaleByInverse().
Referenced by llvm::BranchProbabilityInfo::getBranchProbStackProtector(), getLayoutSuccessorProbThreshold(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), scaleCaseProbality(), splitMBB(), and updatePredecessorProfileMetadata().
getDenominator()
static uint32_t llvm::BranchProbability::getDenominator () inline static
Definition at line 66 of file BranchProbability.h.
Referenced by llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), llvm::MachineBasicBlock::print(), scaleCaseProbality(), and llvm::MachineBasicBlock::validateSuccProbs().
getNumerator()
uint32_t llvm::BranchProbability::getNumerator () const inline
Definition at line 65 of file BranchProbability.h.
Referenced by getAdjustedProbability(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), llvm::getWeightFromBranchProb(), llvm::MIPrinter::print(), llvm::MachineBasicBlock::print(), scaleCaseProbality(), and updatePredecessorProfileMetadata().
getOne()
static BranchProbability llvm::BranchProbability::getOne () inline static
Definition at line 50 of file BranchProbability.h.
References BranchProbability().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), getAdjustedProbability(), getBlockName(), scaleCaseProbality(), and UpdatePDTWorklist().
getRaw()
static BranchProbability llvm::BranchProbability::getRaw (uint32_t N) inline static
Definition at line 54 of file BranchProbability.h.
References BranchProbability(), getBranchProbability(), and normalizeProbabilities().
Referenced by toString().
getUnknown()
static BranchProbability llvm::BranchProbability::getUnknown () inline static
Definition at line 51 of file BranchProbability.h.
References BranchProbability().
Referenced by llvm::SelectionDAGBuilder::getFrameIndexTy(), llvm::MachineBasicBlock::setIsCleanupFuncletEntry(), splitMBB(), and llvm::MachineBasicBlock::splitSuccessor().
getZero()
static BranchProbability llvm::BranchProbability::getZero () inline static
Definition at line 49 of file BranchProbability.h.
References BranchProbability().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MachineBasicBlock::findBranchDebugLoc(), findUnwindDestinations(), llvm::BranchProbabilityInfo::getEdgeProbability(), llvm::MachineBranchProbabilityInfo::getHotSucc(), llvm::BranchProbabilityInfo::getHotSucc(), getLayoutSuccessorProbThreshold(), greaterWithBias(), insertLifetimeMarkersSurroundingCall(), llvm::ARMTargetLowering::ReplaceNodeResults(), scaleCaseProbality(), UpdatePDTWorklist(), and llvm::SelectionDAGBuilder::visitBitTestCase().
isUnknown()
bool llvm::BranchProbability::isUnknown () const inline
Definition at line 47 of file BranchProbability.h.
Referenced by findUncondBrI(), llvm::IRTranslator::getAnalysisUsage(), llvm::SelectionDAGBuilder::isExportableFromCurrentBlock(), print(), llvm::MachineBasicBlock::setSuccProbability(), and splitMBB().
isZero()
bool llvm::BranchProbability::isZero () const inline
Definition at line 46 of file BranchProbability.h.
normalizeProbabilities()
template<class ProbabilityIter > void llvm::BranchProbability::normalizeProbabilities (ProbabilityIter Begin, ProbabilityIter End) static
Definition at line 205 of file BranchProbability.h.
Referenced by getRaw(), llvm::guessSuccessors(), llvm::MachineBasicBlock::normalizeSuccProbs(), and llvm::JumpThreadingPass::ThreadEdge().
operator!=()
bool llvm::BranchProbability::operator!= (BranchProbability RHS) const inline
Definition at line 173 of file BranchProbability.h.
operator*() [1/2]
BranchProbability llvm::BranchProbability::operator* (BranchProbability RHS) const inline
Definition at line 148 of file BranchProbability.h.
operator*() [2/2]
BranchProbability llvm::BranchProbability::operator* (uint32_t RHS) const inline
Definition at line 154 of file BranchProbability.h.
operator*=() [1/2]
BranchProbability& llvm::BranchProbability::operator*= (BranchProbability RHS) inline
Definition at line 107 of file BranchProbability.h.
References assert().
operator*=() [2/2]
BranchProbability& llvm::BranchProbability::operator*= (uint32_t RHS) inline
Definition at line 114 of file BranchProbability.h.
References assert().
operator+()
BranchProbability llvm::BranchProbability::operator+ (BranchProbability RHS) const inline
Definition at line 136 of file BranchProbability.h.
operator+=()
BranchProbability& llvm::BranchProbability::operator+= (BranchProbability RHS) inline
Definition at line 91 of file BranchProbability.h.
References assert().
operator-()
BranchProbability llvm::BranchProbability::operator- (BranchProbability RHS) const inline
Definition at line 142 of file BranchProbability.h.
operator-=()
BranchProbability& llvm::BranchProbability::operator-= (BranchProbability RHS) inline
Definition at line 99 of file BranchProbability.h.
References assert().
operator/() [1/2]
BranchProbability llvm::BranchProbability::operator/ (BranchProbability RHS) const inline
Definition at line 160 of file BranchProbability.h.
operator/() [2/2]
BranchProbability llvm::BranchProbability::operator/ (uint32_t RHS) const inline
Definition at line 166 of file BranchProbability.h.
operator/=() [1/2]
BranchProbability& llvm::BranchProbability::operator/= (BranchProbability RHS) inline
Definition at line 121 of file BranchProbability.h.
References assert().
operator/=() [2/2]
BranchProbability& llvm::BranchProbability::operator/= (uint32_t RHS) inline
Definition at line 128 of file BranchProbability.h.
References assert().
operator<()
bool llvm::BranchProbability::operator< (BranchProbability RHS) const inline
Definition at line 175 of file BranchProbability.h.
References assert().
operator<=()
bool llvm::BranchProbability::operator<= (BranchProbability RHS) const inline
Definition at line 187 of file BranchProbability.h.
References assert().
operator==()
bool llvm::BranchProbability::operator== (BranchProbability RHS) const inline
Definition at line 172 of file BranchProbability.h.
operator>()
bool llvm::BranchProbability::operator> (BranchProbability RHS) const inline
Definition at line 181 of file BranchProbability.h.
References assert().
operator>=()
bool llvm::BranchProbability::operator>= (BranchProbability RHS) const inline
Definition at line 193 of file BranchProbability.h.
References assert().
print()
raw_ostream & BranchProbability::print (raw_ostream & OS) const
Definition at line 24 of file BranchProbability.cpp.
References llvm::format(), isUnknown(), and llvm::Percent.
Referenced by dump(), getCompl(), and llvm::operator<<().
scale()
uint64_t BranchProbability::scale (uint64_t Num) const
Scale a large integer.
Scales Num. Guarantees full precision. Returns the floor of the result.
Returns
Num times this.
Definition at line 106 of file BranchProbability.cpp.
Referenced by llvm::CFGMST< Edge, BBInfo >::buildEdges(), getCompl(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), llvm::BlockFrequency::operator*=(), llvm::bfi_detail::BlockMass::operator*=(), and scaleCaseProbality().
scaleByInverse()
uint64_t BranchProbability::scaleByInverse (uint64_t Num) const
Scale a large integer by the inverse.
Scales Num by the inverse of this. Guarantees full precision. Returns the floor of the result.
Returns
Num divided by this.
Definition at line 110 of file BranchProbability.cpp.
Referenced by getCompl(), and llvm::BlockFrequency::operator/=().
The documentation for this class was generated from the following files:
include/llvm/Support/BranchProbability.h
lib/Support/BranchProbability.cpp