LLVM: llvm::User Class Reference
llvm::User Class Reference
#include "llvm/IR/User.h"
Classes
struct const_value_op_iterator
struct value_op_iterator
Iterator for directly iterating over the operand Values.
Public Types
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Value *V)
Protected Member Functions
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Friends
template<unsigned >
struct HungoffOperandTraits
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Definition at line 44 of file User.h.
Member Typedef Documentation
const_op_iterator
using llvm::User::const_op_iterator = const Use*
Definition at line 225 of file User.h.
const_op_range
using llvm::User::const_op_range = iterator_range<const_op_iterator>
Definition at line 227 of file User.h.
op_iterator
using llvm::User::op_iterator = Use*
Definition at line 224 of file User.h.
op_range
using llvm::User::op_range = iterator_range<op_iterator>
Definition at line 226 of file User.h.
Constructor & Destructor Documentation
User() [1/2]
llvm::User::User (Type * ty, unsigned vty, Use * , unsigned NumOps) inline protected
Definition at line 73 of file User.h.
References allocHungoffUses(), assert(), getOperandList(), growHungoffUses(), llvm::Value::HasHungOffUses, N, llvm::Value::NumUserOperands, llvm::Value::NumUserOperandsBits, and ~User().
Referenced by llvm::slpvectorizer::BoUpSLP::vectorizeTree().
~User()
llvm::User::~User () protected default
Referenced by User().
User() [2/2]
llvm::User::User (const User &) delete
Member Function Documentation
allocHungoffUses()
void llvm::User::allocHungoffUses (unsigned N, bool IsPhi = false) protected
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
Parameters
IsPhi identifies callers which are phi nodes and which need N BasicBlock* allocated along with N
Definition at line 39 of file User.cpp.
References assert(), llvm::Value::HasHungOffUses, and llvm::size().
Referenced by llvm::MemoryPhi::allocHungoffUses(), llvm::PHINode::allocHungoffUses(), llvm::SelectInst::areInvalidOperands(), llvm::LandingPadInst::Create(), llvm::CallBrInst::Create(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), growHungoffUses(), llvm::PHINode::hasConstantOrUndefValue(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), and User().
classof()
static bool llvm::User::classof (const Value * V) inline static
Definition at line 306 of file User.h.
dropAllReferences()
void llvm::User::dropAllReferences () inline
Drop all references to operands.
This function is in charge of "letting go" of all objects that this User refers to. This allows one to 'delete' a whole class at a time, even though there may be circular references... First all references are dropped, and all use counts go to zero. Then everything is deleted for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 294 of file User.h.
References From, operands(), and replaceUsesOfWith().
Referenced by assertBranchOrSelectConditionHoisted(), Cleanup(), llvm::GlobalVariable::dropAllReferences(), llvm::BasicBlock::dropAllReferences(), llvm::Function::dropAllReferences(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), getOrInsertValueProfilingCall(), isPromotedResultSafe(), isUnconditionalBranch(), okayForPHIOfOps(), llvm::MemorySSAUpdater::removeBlocks(), llvm::AMDGPULibCalls::useNative(), and llvm::MemorySSA::~MemorySSA().
getDescriptor() [1/2]
ArrayRef< const uint8_t > llvm::User::getDescriptor () const
Returns the descriptor co-allocated with this User instance.
Definition at line 92 of file User.cpp.
Referenced by getNumOperands().
getDescriptor() [2/2]
MutableArrayRef< uint8_t > llvm::User::getDescriptor ()
Returns the descriptor co-allocated with this User instance.
Definition at line 97 of file User.cpp.
References assert(), llvm::Value::HasDescriptor, llvm::Value::HasHungOffUses, llvm::Value::NumUserOperandsBits, and Size.
getNumOperands()
unsigned llvm::User::getNumOperands () const inline
Definition at line 191 of file User.h.
References getDescriptor(), and llvm::Value::NumUserOperands.
Referenced by llvm::SwitchInst::addCase(), llvm::LandingPadInst::addClause(), llvm::IndirectBrInst::addDestination(), llvm::CatchSwitchInst::addHandler(), llvm::PHINode::addIncoming(), AddReachableCodeToWorklist(), aliasSameBasePointerGEPs(), alwaysAvailable(), llvm::MemorySSAUpdater::applyInsertUpdates(), llvm::SelectInst::areInvalidOperands(), BatchCommitValueTo(), llvm::PHINode::block_end(), BuildConstantFromSCEV(), canReplaceGEPIdxWithZero(), canSinkInstructions(), canTransformAccumulatorRecursion(), canTrapImpl(), cloneConstantExprWithNewAddressSpace(), llvm::GetElementPtrInst::cloneImpl(), llvm::CallInst::cloneImpl(), llvm::FuncletPadInst::cloneImpl(), llvm::ReturnInst::cloneImpl(), llvm::BranchInst::cloneImpl(), llvm::InvokeInst::cloneImpl(), llvm::CallBrInst::cloneImpl(), llvm::CatchReturnInst::cloneImpl(), llvm::CleanupReturnInst::cloneImpl(), llvm::JumpThreadingPass::CloneInstructions(), llvm::FunctionComparator::cmpConstants(), llvm::FunctionComparator::cmpOperations(), computeKnownBitsFromOperator(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFold(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), convert_i1_to_i8(), ConvertDoubleToBytes(), llvm::LandingPadInst::Create(), llvm::CallBrInst::Create(), llvm::CallInst::CreateFree(), llvm::createScalarizerPass(), llvm::createSeparateConstOffsetFromGEPPass(), DCEInstruction(), deleteDeadInstruction(), doPromotion(), llvm::GVNExpression::Expression::dump(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), eliminateRecursiveTailCall(), emitGlobalConstantArray(), emitGlobalConstantStruct(), emitSignedInt64(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::InstCombiner::eraseInstFromFunction(), EvaluateConstantChrecAtConstant(), EvaluateExpression(), llvm::Evaluator::EvaluateFunction(), evaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), ExposePointerBase(), llvm::FenceInst::FenceInst(), findUnwindDestinations(), FindUsedValues(), findUsedValues(), foldGuardedRotateToFunnelShift(), GEPSequentialConstIndexed(), GEPToVectorIndex(), getAllocationSize(), llvm::ConstantExpr::getAsInstruction(), llvm::PHINode::getBasicBlockIndex(), getComparePred(), llvm::getGEPInductionOperand(), getGEPSmallConstantIntOffsetV(), getInductionVariable(), llvm::SCEVExpander::getIVIncOperand(), llvm::InvokeInst::getLandingPadInst(), getLoopPhiForCounter(), llvm::SystemZTTIImpl::getMemoryOpCost(), getMetadataTypeOrder(), getNoopInput(), llvm::SwitchInst::getNumCases(), llvm::LandingPadInst::getNumClauses(), llvm::IndirectBrInst::getNumDestinations(), llvm::CatchSwitchInst::getNumHandlers(), llvm::PHINode::getNumIncomingValues(), llvm::GEPOperator::getNumIndices(), llvm::GetElementPtrInst::getNumIndices(), llvm::SwitchInst::getNumSuccessors(), llvm::IndirectBrInst::getNumSuccessors(), llvm::CatchSwitchInst::getNumSuccessors(), getOffsetFromIndex(), getOffsetFromIndices(), getOrInsertValueProfilingCall(), getParentPad(), llvm::getPointerAtOffset(), getPointerOperands(), getRangeForAffineARHelper(), llvm::ReturnInst::getReturnValue(), getScalarIntrinsicDeclaration(), llvm::ConstantVector::getSplatValue(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::X86TTIImpl::getUserCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), llvm::DbgVariableIntrinsic::getVariableLocation(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), growHungoffUses(), llvm::Constant::handleOperandChange(), llvm::GetElementPtrInst::hasAllConstantIndices(), llvm::GetElementPtrInst::hasAllZeroIndices(), llvm::PHINode::hasConstantOrUndefValue(), llvm::GEPOperator::hasIndices(), llvm::GetElementPtrInst::hasIndices(), hasOnlyOneNonZeroIndex(), INITIALIZE_PASS(), llvm::isBytewiseValue(), llvm::ShuffleVectorInst::isConcat(), llvm::BranchInst::isConditional(), llvm::slpvectorizer::BoUpSLP::isDeleted(), isEmptyXXStructor(), llvm::isGEPBasedOnPointerToString(), isGEPFoldable(), llvm::Instruction::isIdenticalToWhenDefined(), isIgnorableInst(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), isOnlyReachableViaThisEdge(), llvm::isPointerOffset(), isPromotedInstructionLegal(), isPromotedResultSafe(), IsSafeComputationToRemove(), isSafeSROAGEP(), llvm::isSafeToSpeculativelyExecute(), llvm::Instruction::isSameOperationAs(), isSExtLoad(), isSimpleEnoughValueToCommitHelper(), llvm::BranchInst::isUnconditional(), LinearizeExprTree(), matchesOr(), llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue(), maybePrintCallAddrSpace(), mergeEmptyReturnBlocks(), moveUp(), okayForPHIOfOps(), llvm::HungoffOperandTraits< 3 >::op_end(), llvm::OptionalOperandTraits< GlobalVariable >::operands(), llvm::VariadicOperandTraits< ConstantExpr, 1 >::operands(), llvm::HungoffOperandTraits< 3 >::operands(), llvm::orc::CtorDtorIterator::operator*(), operator<<(), llvm::ConstantExprKeyType::operator==(), orderValue(), parseGlobalCtors(), llvm::CallBase::populateBundleOperandInfos(), predictValueUseListOrder(), llvm::VPBlendRecipe::print(), propagateMetadata(), llvm::remapInstruction(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), removeGlobalCtors(), llvm::CatchSwitchInst::removeHandler(), llvm::PHINode::removeIncomingValue(), RemoveInstInputs(), replaceAllUsesOfWithIn(), llvm::VPValue::replaceAllUsesWith(), llvm::PHINode::replaceIncomingBlockWith(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::replaceOperandsInPlace(), replaceUsesOfWith(), ReplaceUsesOfWith(), llvm::returnTypeIsEligibleForTailCall(), llvm::InstCombiner::run(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::InnerLoopVectorizer::scalarizeInstruction(), llvm::PHINode::setIncomingValueForBlock(), ShrinkDemandedConstant(), simplifyAndDCEInstruction(), sinkLastInstruction(), SRAGlobal(), llvm::stripGetElementPtr(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), VerifySubExpr(), llvm::LoopVersioning::versionLoop(), llvm::InstCombiner::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::Interpreter::visitReturnInst(), llvm::InstCombiner::visitReturnInst(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getOperand()
Value* llvm::User::getOperand (unsigned i) const inline
Definition at line 169 of file User.h.
References assert(), getOperandList(), and llvm::Value::NumUserOperands.
Referenced by AddReachableCodeToWorklist(), addStackMapLiveVars(), aliasSameBasePointerGEPs(), alwaysAvailable(), annotateAnyAllocSite(), annotateNonNullAndDereferenceable(), areExtractExts(), AreSequentialAccesses(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), BatchCommitValueTo(), llvm::BinaryOperator::BinaryOperator(), BreakUpSubtract(), BuildConstantFromSCEV(), AAValueConstantRangeFloating::calculateBinaryOperator(), AAValueConstantRangeFloating::calculateCmpInst(), canEvaluateShifted(), canEvaluateShiftedShift(), canEvaluateShuffled(), canFoldIVIncExpr(), CanGenerateTest(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canNarrowShiftAmt(), cannotBeOrderedLessThanZeroImpl(), canonicalizeBitCastExtElt(), canonicalizeCmpWithConstant(), llvm::InstCombiner::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeICmpBool(), canonicalizeInsertSplat(), canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), CanPHITrans(), canReplaceGEPIdxWithZero(), llvm::canReplaceOperandWithVariable(), canSinkInstructions(), canTailPredicateInstruction(), canTransformAccumulatorRecursion(), castRequiresQueuePtr(), CC_MipsO32_FP64(), cheapToScalarize(), checkForNegativeOperand(), CleanupPointerRootUsers(), cloneConstantExprWithNewAddressSpace(), llvm::AllocaInst::cloneImpl(), llvm::LoadInst::cloneImpl(), llvm::StoreInst::cloneImpl(), llvm::AtomicCmpXchgInst::cloneImpl(), llvm::AtomicRMWInst::cloneImpl(), llvm::SelectInst::cloneImpl(), llvm::VAArgInst::cloneImpl(), llvm::ExtractElementInst::cloneImpl(), llvm::InsertElementInst::cloneImpl(), llvm::ShuffleVectorInst::cloneImpl(), llvm::TruncInst::cloneImpl(), llvm::ZExtInst::cloneImpl(), llvm::SExtInst::cloneImpl(), llvm::FPTruncInst::cloneImpl(), llvm::FPExtInst::cloneImpl(), llvm::UIToFPInst::cloneImpl(), llvm::SIToFPInst::cloneImpl(), llvm::FPToUIInst::cloneImpl(), llvm::FPToSIInst::cloneImpl(), llvm::IntToPtrInst::cloneImpl(), llvm::PtrToIntInst::cloneImpl(), llvm::BitCastInst::cloneImpl(), llvm::AddrSpaceCastInst::cloneImpl(), llvm::FreezeInst::cloneImpl(), llvm::JumpThreadingPass::CloneInstructions(), cloneInstructionWithNewAddressSpace(), llvm::FunctionComparator::cmpConstants(), llvm::FunctionComparator::cmpOperations(), llvm::collectCmpOps(), collectInsertionElements(), collectShuffleElements(), collectSingleShuffleElements(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), collectValuesToDemote(), combineADDToADDZE(), CommitValueTo(), llvm::InstCombiner::commonCastTransforms(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonIRemTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), llvm::InstCombiner::commonShiftTransforms(), computeBytesPoppedByCalleeForSRet(), computeKnownBitsFromOperator(), computeKnownBitsFromShiftOperator(), llvm::ComputeMultiple(), llvm::computeOverflowForSignedAdd(), computeUnlikelySuccessors(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFold(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), constantFoldUser(), convert_i1_to_i8(), ConvertDoubleToBytes(), ConvertShiftToMul(), ConvertToSInt(), llvm::UnaryOperator::Create(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createConstantHoistingPass(), llvm::createDwarfEHPass(), createFFSIntrinsic(), llvm::createObjCARCOptPass(), createPowWithIntegerExponent(), createRdxShuffleMask(), createReplacementInstr(), llvm::createScalarizerPass(), llvm::createSeparateConstOffsetFromGEPPass(), DCEInstruction(), decomposeSimpleLinearExpr(), deleteDeadInstruction(), despeculateCountZeros(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), dropRedundantMaskingOfLeftShiftInput(), llvm::GVNExpression::Expression::dump(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), eliminateRecursiveTailCall(), emitGlobalConstantArray(), emitGlobalConstantStruct(), emitGlobalConstantVector(), emitSignedInt64(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), EqualityPropUnSafe(), llvm::slpvectorizer::BoUpSLP::eraseInstructions(), EvaluateConstantChrecAtConstant(), EvaluateExpression(), llvm::Evaluator::EvaluateFunction(), evaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPPredInstPHIRecipe::execute(), ExpandBinOp(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), ExposePointerBase(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), ExtractConstantBytes(), ExtractEquivalentCondition(), factorizeFAddFSub(), FindAllMemoryUses(), findDemandedEltsBySingleUser(), findFinalIVValue(), findFuncPointers(), findGlobalCtors(), findInitTrampoline(), findInitTrampolineFromAlloca(), findInitTrampolineFromBB(), findMatchingInlineAsmOperand(), FindPredecessorAutoreleaseWithSafePath(), FindSingleUseMultiplyFactors(), findStoreAlignment(), findUnwindDestinations(), FindUsedValues(), findUsedValues(), FixedPointIntrinsicToOpcode(), foldAndOrOfEqualityCmpsWithConstants(), foldAndToXor(), foldBitCastBitwiseLogic(), foldConstantCastPair(), foldConstantInsEltIntoShuffle(), foldFabsWithFcmpZero(), foldFCmpReciprocalAndZero(), foldFDivConstantDividend(), foldFDivConstantDivisor(), foldGuardedRotateToFunnelShift(), foldICmpBitCast(), foldICmpOfUAddOv(), foldICmpShlOne(), foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), foldICmpWithMinMax(), foldICmpWithZextOrSext(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), foldIsPowerOf2(), llvm::InstCombiner::FoldItoFPtoI(), foldLogicCastConstant(), foldNoWrapAdd(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), foldOrToXor(), foldSelectBinOpIdentity(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), foldSelectICmpLshrAshr(), foldSelectInst(), foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedLogic(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldUnsignedUnderflowCheck(), foldVectorCmp(), foldVecTruncToExtElt(), foldXorToXor(), llvm::ScalarEvolution::forgetValue(), generatePoisonChecks(), generatePoisonChecksForBinOp(), GenerateSignBits(), GEPSequentialConstIndexed(), GEPToVectorIndex(), llvm::IndirectBrInst::getAddress(), llvm::ExtractValueInst::getAggregateOperand(), llvm::InsertValueInst::getAggregateOperand(), getAlternateBinop(), llvm::IRTranslator::getAnalysisUsage(), llvm::AllocaInst::getArraySize(), getAsConstantIndexedAddress(), llvm::IRPosition::getAttrs(), llvm::GlobalIndirectSymbol::getBaseObject(), getBinOpsForFactorization(), llvm::Loop::LoopBounds::getBounds(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), getCastsForInductionPHI(), getChainID(), getCmpOpsType(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), getCommonReturnValue(), getCompareCC(), llvm::AtomicCmpXchgInst::getCompareOperand(), getComparePred(), llvm::SwitchInst::getCondition(), getConstantAt(), llvm::SwitchInst::getDefaultDest(), getDemandedBitsLHSMask(), DivRemPairWorklistEntry::getDividend(), DivRemPairWorklistEntry::getDivisor(), getExtractIndex(), llvm::getGEPInductionOperand(), getGEPSmallConstantIntOffsetV(), llvm::getGuaranteedNonFullPoisonOp(), llvm::PHINode::getIncomingValue(), llvm::CallBrInst::getIndirectDestLabel(), llvm::GlobalIndirectSymbol::getIndirectSymbol(), getInductionVariable(), llvm::Loop::getInductionVariable(), llvm::InsertValueInst::getInsertedValueOperand(), llvm::SCEVExpander::getIVIncOperand(), GetLoopInvariantInsertPosition(), getLoopPhiForCounter(), llvm::ShuffleVectorInst::getMask(), getMaskedTypeForICmpPair(), getMaxPointerSize(), llvm::SystemZTTIImpl::getMemoryOpCost(), getMulHu(), getNegatibleInsts(), llvm::AtomicCmpXchgInst::getNewValOperand(), getNoopInput(), getOffsetFromIndex(), getOffsetFromIndices(), getOrInsertValueProfilingCall(), getParameterABIAttributes(), getParentPad(), llvm::CatchSwitchInst::getParentPad(), llvm::getPointerAtOffset(), llvm::LoadInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::GEPOperator::getPointerOperand(), llvm::PtrToIntOperator::getPointerOperand(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::AtomicRMWInst::getPointerOperand(), llvm::GetElementPtrInst::getPointerOperand(), llvm::VAArgInst::getPointerOperand(), llvm::PtrToIntInst::getPointerOperand(), llvm::AddrSpaceCastInst::getPointerOperand(), getPointerOperands(), getRangeForAffineARHelper(), getRecurrenceVar(), getReducedType(), getRelevantOperands(), llvm::objcarc::getreturnRVOperand(), llvm::ReturnInst::getReturnValue(), getScalarIntrinsicDeclaration(), getShiftedValue(), llvm::ConstantVector::getSplatValue(), llvm::BitCastOperator::getSrcTy(), llvm::getStrideFromPointer(), llvm::SwitchInst::getSuccessor(), llvm::IndirectBrInst::getSuccessor(), llvm::CatchSwitchInst::getSuccessor(), llvm::BasicBlock::getTerminatingMustTailCall(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), llvm::SITargetLowering::getTgtMemIntrinsic(), llvm::CatchSwitchInst::getUnwindDest(), llvm::X86TTIImpl::getUserCost(), llvm::GCNTTIImpl::getUserCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), llvm::AtomicRMWInst::getValOperand(), getValueFromICmpCondition(), llvm::StoreInst::getValueOperand(), getVectorType(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), GlobalWasGeneratedByCompiler(), handleBrSelExpect(), handleFree(), handleIndirectSymViaGOTPCRel(), llvm::Constant::handleOperandChange(), handlePhiDef(), llvm::GetElementPtrInst::hasAllConstantIndices(), llvm::GetElementPtrInst::hasAllZeroIndices(), hasOnlyOneNonZeroIndex(), hasSameExtUse(), hasStoreUsersOnly(), hasUndefContents(), hasZeroSignBit(), hoistInsEltConst(), llvm::SCEVExpander::hoistIVInc(), llvm::hoistRegion(), impliesEquivalanceIfFalse(), impliesEquivalanceIfTrue(), INITIALIZE_PASS(), llvm::InlineFunction(), insertValues(), instrumentMaskedLoadOrStore(), inversePermutation(), isAddOfNonZero(), llvm::isAllocaPromotable(), isAllocSiteRemovable(), isAlwaysLive(), llvm::AllocaInst::isArrayAllocation(), isBroadcastShuffle(), llvm::isBytewiseValue(), isCallPromotable(), isChainSelectCmpBranch(), llvm::ShuffleVectorInst::isConcat(), isCondRelevantToAnyCallArgument(), isContiguous(), llvm::slpvectorizer::BoUpSLP::isDeleted(), isEqualImpl(), llvm::TargetLoweringBase::isExtFree(), isExtractBitsCandidateUse(), llvm::SystemZTTIImpl::isFoldableLoad(), llvm::InductionDescriptor::isFPInductionPHI(), isFuncOrArgAttr(), llvm::isGEPBasedOnPointerToString(), isGEPFoldable(), isGOTEquivalentCandidate(), isIgnorableInst(), isImpliedCondICmps(), llvm::CastInst::isIntegerCast(), isInterestingPointerComparison(), isInterestingPointerSubtraction(), isIntExtFree(), isLoadInvariantInLoop(), isLoopExitTestBasedOn(), llvm::CastInst::isLosslessCast(), llvm::AArch64TargetLowering::isMaskAndCmp0FoldingBeneficial(), llvm::RecurrenceDescriptor::isMinMaxSelectCmpPattern(), isMulPowOf2(), llvm::CastInst::isNoopCast(), isOnlyReachableViaThisEdge(), llvm::isPointerOffset(), llvm::AArch64TargetLowering::isProfitableToHoist(), isPromotedInstructionLegal(), isPromotedResultSafe(), isReassociableOp(), isReInterleaveMask(), isRepeatedByteSequence(), isReportingError(), isReturnNonNull(), isSafeAndProfitableToSinkLoad(), IsSafeComputationToRemove(), isSafeSROAGEP(), isSafeToEliminateVarargsCast(), llvm::isSafeToSpeculativelyExecute(), isSameCompare(), llvm::Instruction::isSameOperationAs(), isSExtLoad(), isShuffleEquivalentToSelect(), isShuffleExtractingFromLHS(), isSimpleEnoughValueToCommitHelper(), llvm::AllocaInst::isStaticAlloca(), isStrideMul(), isVectorReductionOp(), isZero(), llvm::AArch64TargetLowering::isZExtFree(), LdStHasDebugValue(), LinearizeExprTree(), lookThroughCast(), llvm::FastISel::lowerCallTo(), llvm::AsmPrinter::lowerConstant(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerIsConstantIntrinsic(), LowerNegateToMultiply(), llvm::LTOModule::makeBuffer(), mapBinOpcode(), llvm::matchDecomposedSelectPattern(), matchDeMorgansLaws(), matchesOr(), matchPairwiseReduction(), matchPairwiseReductionAtLevel(), matchRotate(), matchUAddWithOverflowConstantEdgeCases(), matchVectorSplittingReduction(), maybePrintCallAddrSpace(), mayDivideByZero(), mayUsePostIncMode(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), mergeCleanupPad(), mergeEmptyReturnBlocks(), MightBeFoldableInst(), moveUp(), MulWillOverflow(), narrowUDivURem(), narrowVectorSelect(), llvm::Constant::needsRelocation(), NegateValue(), normalizePredicate(), llvm::orc::CtorDtorIterator::operator*(), operator<<(), llvm::ConstantExprKeyType::operator==(), OptimizeAwayTrappingUsesOfLoads(), llvm::FastISel::optimizeCmpPredicate(), OptimizeExtractBits(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeIntegerToVectorInsertions(), OptimizeNoopCopyExpression(), optimizeSQRT(), parseGlobalCtors(), performSink(), PickMostRelevantLoop(), llvm::PointerMayBeCaptured(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), llvm::VPBlendRecipe::print(), processAnd(), processAShr(), processBinOp(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCmp(), processSDiv(), processSelect(), processSExt(), processSRem(), processUDivOrURem(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), promotedOpIsNUW(), llvm::promoteLoopAccessesToScalars(), propagateMetadata(), PushDefUseChildren(), reassociateFCmps(), llvm::remapInstruction(), llvm::safestack::StackColoring::removeAllMarkers(), removeGlobalCtors(), RemoveInstInputs(), replaceAllUsesOfWithIn(), llvm::VPValue::replaceAllUsesWith(), replaceConditionalBranchesOnConstant(), llvm::replaceCreatedSSACopys(), llvm::InstCombiner::replacedSelectWithOperand(), replaceExtractElements(), replaceUsesOfWith(), ReplaceUsesOfWith(), reportLoadElim(), llvm::returnTypeIsEligibleForTailCall(), reuseTableCompare(), rewriteSingleStoreAlloca(), llvm::LoopPredicationPass::run(), llvm::InstCombiner::run(), llvm::SLPVectorizerPass::runImpl(), llvm::StackProtector::runOnFunction(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::salvageDebugInfoForDbgValues(), llvm::salvageDebugInfoImpl(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), llvm::InnerLoopVectorizer::scalarizeInstruction(), scaleCaseProbality(), llvm::FastISel::selectBinaryOp(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectCast(), llvm::FastISel::selectExtractValue(), llvm::FastISel::selectGetElementPtr(), llvm::FastISel::selectOperator(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), setLimitsForBinOp(), setLimitsForIntrinsic(), ShouldBreakUpSubtract(), shouldKeepFDivF32(), shouldMergeGEPs(), llvm::ARMTargetLowering::shouldSinkOperands(), llvm::AArch64TargetLowering::shouldSinkOperands(), ShrinkDemandedConstant(), shrinkInsertElt(), shrinkSplatShuffle(), simplifyAndDCEInstruction(), simplifyAndOfICmpsWithAdd(), simplifyAndOrOfFCmps(), simplifyAndOrOfICmpsWithConstants(), simplifyAndOrOfICmpsWithZero(), simplifyAssocCastAssoc(), SimplifyAssociativeBinOp(), SimplifyBSwap(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SimplifyICmpInst(), simplifyICmpWithBinOp(), SimplifyIndirectBrOnSelect(), llvm::SimplifyInstruction(), simplifyOrOfICmpsWithAdd(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), llvm::InstCombiner::simplifyRangeCheck(), SimplifyRelativeLoad(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), SimplifyWithOpReplaced(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86vpermv(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), sinkLastInstruction(), SinkShiftAndTruncate(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), splitMergedValStore(), SRAGlobal(), llvm::stripGetElementPtr(), supportedAddressingMode(), ThreadBinOpOverSelect(), truncateIVUse(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), TryToMergeLandingPad(), llvm::VPRecipeBuilder::tryToOptimizeInduction(), tryToRecognizePopCount(), TryToShrinkGlobalToBoolean(), TryToSinkInstruction(), llvm::JumpThreadingPass::TryToUnfoldSelect(), tryToVectorizeHorReductionOrInstOperands(), tryUnmergingGEPsAcrossIndirectBr(), TypeSizeToSizeIndex(), updateOperand(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), UpgradeX86AddSubSatIntrinsics(), upgradeX86ConcatShift(), upgradeX86Rotate(), VerifySubExpr(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::Interpreter::visitAllocaInst(), llvm::InstCombiner::visitAnd(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitAShr(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitBitCast(), llvm::Interpreter::visitBitCastInst(), llvm::Interpreter::visitExtractElementInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFAdd(), llvm::Interpreter::visitFCmpInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFNeg(), llvm::Interpreter::visitFPExtInst(), llvm::InstCombiner::visitFPToSI(), llvm::Interpreter::visitFPToSIInst(), llvm::InstCombiner::visitFPToUI(), llvm::Interpreter::visitFPToUIInst(), llvm::InstCombiner::visitFPTrunc(), llvm::Interpreter::visitFPTruncInst(), llvm::InstCombiner::visitFreeze(), llvm::InstCombiner::visitFRem(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::Interpreter::visitICmpInst(), llvm::InstCombiner::visitICmpInst(), llvm::Interpreter::visitInsertElementInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitInsertValueInst(), llvm::InstCombiner::visitIntToPtr(), llvm::Interpreter::visitIntToPtrInst(), visitIVCast(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLoadInst(), llvm::Interpreter::visitLShr(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitPtrToInt(), llvm::Interpreter::visitPtrToIntInst(), llvm::InstCombiner::visitReturnInst(), llvm::InstCombiner::visitSDiv(), llvm::Interpreter::visitSelectInst(), llvm::InstCombiner::visitSExt(), llvm::Interpreter::visitSExtInst(), llvm::Interpreter::visitShl(), llvm::InstCombiner::visitShl(), llvm::Interpreter::visitShuffleVectorInst(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::Interpreter::visitSIToFPInst(), llvm::InstCombiner::visitSRem(), llvm::Interpreter::visitStoreInst(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::Interpreter::visitTruncInst(), llvm::InstCombiner::visitUDiv(), llvm::Interpreter::visitUIToFPInst(), llvm::Interpreter::visitUnaryOperator(), llvm::InstCombiner::visitURem(), llvm::Interpreter::visitVAArgInst(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::Interpreter::visitZExtInst(), llvm::InnerLoopVectorizer::widenInstruction(), willNotOverflow(), X86ChooseCmpImmediateOpcode(), and llvm::reassociate::XorOpnd::XorOpnd().
getOperandList() [1/2]
const Use* llvm::User::getOperandList () const inline
Definition at line 162 of file User.h.
References llvm::Value::HasHungOffUses.
Referenced by llvm::LandingPadInst::addClause(), llvm::IndirectBrInst::addDestination(), llvm::CatchSwitchInst::addHandler(), llvm::CallBrInst::Create(), llvm::LandingPadInst::getClause(), llvm::ConstantExpr::getOpcodeName(), getOperand(), getOperandList(), getOperandUse(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), growHungoffUses(), llvm::Constant::handleOperandChange(), llvm::PHINode::hasConstantOrUndefValue(), llvm::LandingPadInst::isCatch(), llvm::LandingPadInst::isFilter(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), llvm::HungoffOperandTraits< 3 >::op_begin(), op_begin(), llvm::HungoffOperandTraits< 3 >::op_end(), op_end(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), setOperand(), and User().
getOperandList() [2/2]
Use* llvm::User::getOperandList () inline
Definition at line 165 of file User.h.
References getOperandList().
getOperandUse() [1/2]
const Use& llvm::User::getOperandUse (unsigned i) const inline
Definition at line 182 of file User.h.
References assert(), getOperandList(), and llvm::Value::NumUserOperands.
Referenced by BrPHIToSelect(), llvm::GVNExpression::Expression::dump(), llvm::formLCSSAForInstructions(), llvm::CallBase::getArgOperandUse(), llvm::IRPosition::getAttrs(), llvm::CallBrInst::getIndirectDestLabelUse(), getParentPad(), getTypePartition(), shouldFixMainFunction(), llvm::ARMTargetLowering::shouldSinkOperands(), llvm::AArch64TargetLowering::shouldSinkOperands(), ShrinkDemandedConstant(), and sinkLastInstruction().
getOperandUse() [2/2]
Use& llvm::User::getOperandUse (unsigned i) inline
Definition at line 186 of file User.h.
References assert(), getOperandList(), and llvm::Value::NumUserOperands.
growHungoffUses()
void llvm::User::growHungoffUses (unsigned N, bool IsPhi = false) protected
Grow the number of hung off uses.
Note that allocHungoffUses should be called if there are no uses.
Definition at line 58 of file User.cpp.
References allocHungoffUses(), assert(), llvm::copy(), getNumOperands(), getOperandList(), llvm::Value::HasHungOffUses, and llvm::Use::zap().
Referenced by llvm::LandingPadInst::Create(), llvm::CallBrInst::Create(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::SwitchInst::removeCase(), llvm::PHINode::removeIncomingValue(), and User().
Op() [1/2]
template<int Idx> Use& llvm::User::Op () inline protected
Definition at line 133 of file User.h.
Referenced by llvm::CallBrInst::Create(), llvm::CatchPadInst::getCatchSwitch(), llvm::BranchInst::getCondition(), llvm::CallBrInst::getDefaultDest(), llvm::CallBrInst::getIndirectDest(), llvm::ConstantExpr::getOpcode(), llvm::AtomicRMWInst::getOperation(), llvm::BranchInst::getSuccessor(), llvm::DbgVariableIntrinsic::getVariableLocation(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::Constant::handleOperandChange(), llvm::ShuffleVectorInst::isValidOperands(), llvm::CatchSwitchInst::removeHandler(), llvm::PHINode::removeIncomingValue(), llvm::PHINode::replaceIncomingBlockWith(), llvm::CatchPadInst::setCatchSwitch(), llvm::BranchInst::setCondition(), llvm::CallBrInst::setDefaultDest(), llvm::PHINode::setIncomingValueForBlock(), llvm::CallBrInst::setIndirectDest(), llvm::BranchInst::setSuccessor(), llvm::BranchInst::swapSuccessors(), and llvm::UnreachableInst::UnreachableInst().
Op() [2/2]
template<int Idx> const Use& llvm::User::Op () const inline protected
Definition at line 136 of file User.h.
References assert(), llvm::Value::HasHungOffUses, and llvm::Value::NumUserOperands.
op_begin() [1/2]
op_iterator llvm::User::op_begin () inline
Definition at line 229 of file User.h.
References getOperandList().
Referenced by alwaysAvailable(), llvm::RecurrenceDescriptor::areAllUsesIn(), llvm::SelectInst::areInvalidOperands(), llvm::PHINode::block_begin(), buildMultiplyTree(), llvm::objcarc::CanUse(), CC_MipsO32_FP64(), CloneInstructionInExitBlock(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantFoldLoadFromConstPtr(), llvm::CallInst::CreateFree(), createReplacementInstr(), llvm::createSeparateConstOffsetFromGEPPass(), DominatesMergePoint(), doPromotion(), llvm::EmitGEPOffset(), llvm::slpvectorizer::BoUpSLP::eraseInstructions(), ExposePointerBase(), llvm::FenceInst::FenceInst(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), llvm::gep_type_begin(), llvm::ConstantExpr::getAsInstruction(), getComparePred(), getDebugLocFromInstOrOperands(), llvm::PHINode::getIncomingBlock(), llvm::SCEVExpander::getIVIncOperand(), llvm::InvokeInst::getLandingPadInst(), getMaxPointerSize(), getMetadataTypeOrder(), llvm::Use::getOperandNo(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::ConstantExpr::getWithOperands(), llvm::CatchSwitchInst::handler_begin(), llvm::RecurrenceDescriptor::hasMultipleUsesOf(), hasUsesOutsideLoop(), llvm::GEPOperator::idx_begin(), llvm::GetElementPtrInst::idx_begin(), INITIALIZE_PASS(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), llvm::Instruction::isIdenticalToWhenDefined(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue(), operands(), llvm::CallBase::populateBundleOperandInfos(), llvm::CatchSwitchInst::removeHandler(), llvm::PHINode::removeIncomingValue(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), llvm::AAEvaluator::run(), llvm::SimplifyInstruction(), llvm::InnerLoopVectorizer::sinkScalarOperands(), SpeculativelyExecuteBB(), value_op_begin(), llvm::sroa::AllocaSliceRewriter::visit(), and llvm::InstCombiner::visitGetElementPtrInst().
op_begin() [2/2]
const_op_iterator llvm::User::op_begin () const inline
Definition at line 230 of file User.h.
References getOperandList().
op_end() [1/2]
op_iterator llvm::User::op_end () inline
Definition at line 231 of file User.h.
References getOperandList(), and llvm::Value::NumUserOperands.
Referenced by alwaysAvailable(), llvm::RecurrenceDescriptor::areAllUsesIn(), llvm::SelectInst::areInvalidOperands(), buildMultiplyTree(), canFoldIVIncExpr(), llvm::objcarc::CanUse(), CC_MipsO32_FP64(), CloneInstructionInExitBlock(), llvm::ConstantFoldLoadFromConstPtr(), llvm::CallInst::CreateFree(), createReplacementInstr(), llvm::createSeparateConstOffsetFromGEPPass(), DominatesMergePoint(), doPromotion(), llvm::EmitGEPOffset(), ExposePointerBase(), llvm::FenceInst::FenceInst(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), llvm::gep_type_end(), llvm::AllocaInst::getAllocationSizeInBits(), llvm::ConstantExpr::getAsInstruction(), getComparePred(), getDebugLocFromInstOrOperands(), llvm::SCEVExpander::getIVIncOperand(), llvm::InvokeInst::getLandingPadInst(), getMaxPointerSize(), getMetadataTypeOrder(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::CatchSwitchInst::handler_end(), llvm::RecurrenceDescriptor::hasMultipleUsesOf(), hasUsesOutsideLoop(), llvm::GEPOperator::idx_end(), llvm::GetElementPtrInst::idx_end(), INITIALIZE_PASS(), llvm::Instruction::isIdenticalToWhenDefined(), llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue(), operands(), llvm::CallBase::populateBundleOperandInfos(), llvm::CatchSwitchInst::removeHandler(), llvm::PHINode::removeIncomingValue(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), llvm::AAEvaluator::run(), llvm::SimplifyInstruction(), llvm::InnerLoopVectorizer::sinkScalarOperands(), SpeculativelyExecuteBB(), usesOperand(), value_op_end(), llvm::sroa::AllocaSliceRewriter::visit(), and llvm::InstCombiner::visitGetElementPtrInst().
op_end() [2/2]
const_op_iterator llvm::User::op_end () const inline
Definition at line 234 of file User.h.
References getOperandList(), and llvm::Value::NumUserOperands.
operand_values() [1/2]
iterator_range<value_op_iterator> llvm::User::operand_values () inline
Definition at line 261 of file User.h.
References llvm::make_range(), value_op_begin(), and value_op_end().
Referenced by llvm::canConstantFoldCallTo(), collectHomogenousInstGraphLoopInvariants(), findProfitablePHIs(), isNullOrUndef(), llvm::isSafeToExpandAt(), matchVectorSplittingReduction(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), okayForPHIOfOps(), operandReferences(), rematerializeLiveValues(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), tryToVectorizeHorReductionOrInstOperands(), and llvm::LazyCallGraph::visitReferences().
operand_values() [2/2]
iterator_range<const_value_op_iterator> llvm::User::operand_values () const inline
Definition at line 282 of file User.h.
References llvm::make_range(), value_op_begin(), and value_op_end().
operands() [1/2]
op_range llvm::User::operands () inline
Definition at line 237 of file User.h.
References op_begin(), and op_end().
Referenced by AddReachableCodeToWorklist(), llvm::DivergenceAnalysis::addUniformOverride(), analyzeLoopUnrollCost(), appendSpeculatableOperands(), BuildConstantFromSCEV(), callHasFloatingPointArgument(), callHasFP128Argument(), canEvaluateShuffled(), canFoldIVIncExpr(), canMoveAboveCall(), castRequiresQueuePtr(), Cleanup(), llvm::TypeFinder::clear(), cloneInstructionWithNewAddressSpace(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::collectUsedGlobalVariables(), llvm::ConstantFoldInstruction(), llvm::ConstantFoldLoadFromConstPtr(), ConstHasGlobalValuePredicate(), contains(), DeleteTriviallyDeadInstructions(), dropAllReferences(), emitSignedInt64(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::InstCombiner::eraseInstFromFunction(), findArgumentCopyElisionCandidates(), findGlobalCtors(), findRefEdges(), forEachUser(), GetAnyNonZeroConstInt(), getComparePred(), getConstantEvolvingPHIOperands(), getMetadataTypeOrder(), getOperandsExtensionCost(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), llvm::VPRecipeBuilder::handleReplication(), hasConcreteDefImpl(), llvm::Loop::hasLoopInvariantOperands(), hasPositiveOperands(), llvm::PHINode::incoming_values(), INITIALIZE_PASS(), llvm::SlotTracker::initializeIndexIfNeeded(), llvm::DivergenceAnalysis::inRegion(), instrumentMaskedLoadOrStore(), isBlockValidForExtraction(), isEphemeralValueOf(), isFuncOrArgAttr(), isOnlyReachableViaThisEdge(), isPromotedResultSafe(), isReferencingMDNode(), llvm::isSafeToMoveBefore(), isSExtLoad(), isSimpleEnoughValueToCommitHelper(), isStrideMul(), isUnconditionalBranch(), llvm::Loop::makeLoopInvariant(), mapBinOpcode(), llvm::LoopInfo::movementPreservesLCSSAForm(), okayForPHIOfOps(), onlySingleValue(), orderValue(), parseGlobalCtors(), predictValueUseListOrder(), processHeaderPhiOperands(), processUDivOrURem(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::DemandedBitsWrapperPass::releaseMemory(), RemoveDeadConstant(), llvm::InstCombiner::run(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), updateSuccessor(), usesOperand(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InnerLoopVectorizer::widenInstruction(), and wrapConstantAsMetadata().
operands() [2/2]
const_op_range llvm::User::operands () const inline
Definition at line 240 of file User.h.
References op_begin(), and op_end().
operator delete() [1/3]
LLVM_NO_SANITIZE_MEMORY_ATTRIBUTE void llvm::User::operator delete (void * Usr)
Free memory allocated for User and Use objects.
Definition at line 167 of file User.cpp.
References assert(), llvm::Value::HasDescriptor, llvm::Value::HasHungOffUses, llvm::Value::NumUserOperands, llvm::DescriptorInfo::SizeInBytes, and llvm::Use::zap().
operator delete() [2/3]
void llvm::User::operator delete (void * Usr, unsigned) inline
Placement delete - required by std, called if the ctor throws.
Definition at line 102 of file User.h.
References llvm_unreachable.
operator delete() [3/3]
void llvm::User::operator delete (void * Usr, unsigned , unsigned) inline
Placement delete - required by std, called if the ctor throws.
Definition at line 114 of file User.h.
References llvm_unreachable.
operator new() [1/3]
void * llvm::User::operator new (size_t Size) protected
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Definition at line 149 of file User.cpp.
References llvm::Value::HasDescriptor, llvm::Value::HasHungOffUses, and llvm::Value::NumUserOperands.
operator new() [2/3]
void * llvm::User::operator new (size_t Size, unsigned Us) protected
Allocate a User with the operands co-allocated.
This is used for subclasses which have a fixed number of operands.
Definition at line 141 of file User.cpp.
operator new() [3/3]
void * llvm::User::operator new (size_t Size, unsigned Us, unsigned DescBytes) protected
Allocate a User with the operands co-allocated.
If DescBytes is non-zero then allocate an additional DescBytes bytes before the operands. These bytes can be accessed by calling getDescriptor.
DescBytes needs to be divisible by sizeof(void *). The allocated descriptor, if any, is aligned to sizeof(void *) bytes.
This is used for subclasses which have a fixed number of operands.
Definition at line 145 of file User.cpp.
OpFrom()
template<int Idx, typename U > static Use& llvm::User::OpFrom (const U * that) inline static protected
Definition at line 127 of file User.h.
replaceUsesOfWith()
void llvm::User::replaceUsesOfWith (Value * From, Value * To)
Replace uses of one Value with another.
Replaces all references to the "From" definition with references to the "To" definition.
Definition at line 20 of file User.cpp.
References assert(), E, getNumOperands(), getOperand(), and setOperand().
Referenced by canonicalizeSaturatedAdd(), createRetBitCast(), llvm::DemoteRegToStack(), dropAllReferences(), llvm::CodeExtractor::findInputsOutputs(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), hasProfileData(), insertLifetimeMarkersSurroundingCall(), isBroadcastShuffle(), IsNonLocalValue(), isZeroLengthArray(), makeAllConstantUsesInstructions(), OptimizeGlobalAddressOfMalloc(), processMemAccess(), ReduceSwitchRange(), rematerializeLiveValues(), removeEmptyCleanup(), ReplaceUsesOfWith(), llvm::SplitIndirectBrCriticalEdges(), and llvm::slpvectorizer::BoUpSLP::vectorizeTree().
setGlobalVariableNumOperands()
void llvm::User::setGlobalVariableNumOperands (unsigned NumOps) inline
Set the number of operands on a GlobalVariable.
GlobalVariable always allocates space for a single operands, but doesn't always use it.
FIXME: As that the number of operands is used to find the start of the allocated memory in operator delete, we need to always think we have 1 operand before delete.
Definition at line 207 of file User.h.
References assert(), and llvm::Value::NumUserOperands.
Referenced by llvm::GlobalVariable::operator delete(), and llvm::GlobalVariable::setInitializer().
setNumHungOffUseOperands()
void llvm::User::setNumHungOffUseOperands (unsigned NumOps) inline
Subclasses with hung off uses need to manage the operand count themselves.
In these instances, the operand count isn't used to find the OperandList, so there's no issue in having the operand count change.
Definition at line 215 of file User.h.
References assert(), llvm::Value::HasHungOffUses, llvm::Value::NumUserOperands, and llvm::Value::NumUserOperandsBits.
Referenced by llvm::SwitchInst::addCase(), llvm::LandingPadInst::addClause(), llvm::IndirectBrInst::addDestination(), llvm::CatchSwitchInst::addHandler(), llvm::PHINode::addIncoming(), llvm::LandingPadInst::Create(), llvm::CallBrInst::Create(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), llvm::CatchSwitchInst::removeHandler(), and llvm::PHINode::removeIncomingValue().
setOperand()
void llvm::User::setOperand (unsigned i, Value * Val) inline
Definition at line 174 of file User.h.
References assert(), getOperandList(), and llvm::Value::NumUserOperands.
Referenced by BreakUpSubtract(), canonicalizeSaturatedAdd(), cloneInstForMustTail(), llvm::JumpThreadingPass::CloneInstructions(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonIRemTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), llvm::InstCombiner::commonShiftTransforms(), llvm::RandomIRBuilder::connectToSink(), ConvertShiftToMul(), createHWLoopAnalysis(), llvm::createScalarizerPass(), llvm::createSeparateConstOffsetFromGEPPass(), DCEInstruction(), deleteDeadInstruction(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), eliminateRecursiveTailCall(), foldCtpop(), foldCttzCtlz(), foldFabsWithFcmpZero(), foldICmpBitCast(), foldICmpWithMinMax(), llvm::FoldReturnIntoUncondBranch(), foldSelectBinOpIdentity(), foldShiftedShift(), foldShuffleWithInsert(), foldXorToXor(), forceIndeterminateEdge(), llvm::BlockAddress::get(), getShiftedValue(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::insertDebugValuesForPHIs(), isOnlyReachableViaThisEdge(), isPromotedResultSafe(), isSafeAndProfitableToSinkLoad(), LinearizeExprTree(), llvm::BlockAddress::lookup(), LowerNegateToMultiply(), makeBitReverse(), MarkBlocksLiveIn(), mayUsePostIncMode(), mergeEmptyReturnBlocks(), NegateValue(), normalizePredicate(), operator<<(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::remapInstruction(), replaceAllUsesOfWithIn(), llvm::VPValue::replaceAllUsesWith(), llvm::replaceDbgUsesWithUndef(), replaceGEPIdxWithZero(), replaceUsesOfWith(), rewriteDebugUsers(), RewriteUsesOfClonedInstructions(), llvm::InnerLoopVectorizer::scalarizeInstruction(), llvm::IndirectBrInst::setAddress(), llvm::SwitchInst::setCondition(), llvm::SwitchInst::setDefaultDest(), llvm::PHINode::setIncomingValue(), llvm::GlobalIndirectSymbol::setIndirectSymbol(), llvm::CatchSwitchInst::setParentPad(), llvm::SwitchInst::setSuccessor(), llvm::IndirectBrInst::setSuccessor(), llvm::CatchSwitchInst::setSuccessor(), llvm::CatchSwitchInst::setUnwindDest(), llvm::SwitchInst::CaseHandle::setValue(), ShrinkDemandedConstant(), simplifyAllocaArraySize(), simplifyAndDCEInstruction(), simplifyAssocCastAssoc(), SimplifyBSwap(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SimplifyIndirectBrOnSelect(), simplifyValueKnownNonZero(), simplifyX86vpermv(), SpeculativelyExecuteBB(), TryToSinkInstruction(), tryUnmergingGEPsAcrossIndirectBr(), TypeSizeToSizeIndex(), updateOperand(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitReturnInst(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitStoreInst(), and llvm::InstCombiner::visitXor().
value_op_begin() [1/2]
value_op_iterator llvm::User::value_op_begin () inline
Definition at line 255 of file User.h.
References op_begin(), and llvm::User::value_op_iterator::value_op_iterator().
Referenced by llvm::EliminateDuplicatePHINodes(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionLatency(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), llvm::TargetTransformInfo::getUserCost(), markAliveBlocks(), operand_values(), llvm::BranchInst::successors(), and llvm::IndirectBrInst::successors().
value_op_begin() [2/2]
const_value_op_iterator llvm::User::value_op_begin () const inline
Definition at line 276 of file User.h.
References op_begin().
value_op_end() [1/2]
value_op_iterator llvm::User::value_op_end () inline
Definition at line 258 of file User.h.
References op_end(), and llvm::User::value_op_iterator::value_op_iterator().
Referenced by llvm::EliminateDuplicatePHINodes(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionLatency(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), llvm::TargetTransformInfo::getUserCost(), markAliveBlocks(), operand_values(), llvm::BranchInst::successors(), and llvm::IndirectBrInst::successors().
value_op_end() [2/2]
const_value_op_iterator llvm::User::value_op_end () const inline
Definition at line 279 of file User.h.
References op_end().
Friends And Related Function Documentation
HungoffOperandTraits
template<unsigned > friend struct HungoffOperandTraits friend
Definition at line 46 of file User.h.
The documentation for this class was generated from the following files:
include/llvm/IR/User.h
lib/IR/User.cpp