LLVM: llvm::PBQP::GraphBase Class Reference
llvm::PBQP::GraphBase Class Reference
#include "llvm/CodeGen/PBQP/Graph.h"
Public Types
using NodeId = unsigned
using EdgeId = unsigned
Static Public Member Functions
static NodeId invalidNodeId ()
Returns a value representing an invalid (non-existent) node.
static EdgeId invalidEdgeId ()
Returns a value representing an invalid (non-existent) edge.
Detailed Description
Definition at line 26 of file Graph.h.
Member Typedef Documentation
EdgeId
using llvm::PBQP::GraphBase::EdgeId = unsigned
Definition at line 29 of file Graph.h.
NodeId
using llvm::PBQP::GraphBase::NodeId = unsigned
Definition at line 28 of file Graph.h.
Member Function Documentation
invalidEdgeId()
static EdgeId llvm::PBQP::GraphBase::invalidEdgeId () inline static
Returns a value representing an invalid (non-existent) edge.
Definition at line 37 of file Graph.h.
References llvm::max().
Referenced by llvm::PBQP::Graph< RegAllocSolverImpl >::findEdge().
invalidNodeId()
static NodeId llvm::PBQP::GraphBase::invalidNodeId () inline static
Returns a value representing an invalid (non-existent) node.
Definition at line 32 of file Graph.h.
References llvm::max().
Referenced by llvm::PBQP::RegAlloc::GraphMetadata::getNodeIdForVReg().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/PBQP/Graph.h