LLVM: llvm::PBQP::RegAlloc::MatrixMetadata Class Reference
llvm::PBQP::RegAlloc::MatrixMetadata Class Reference
Metadata to speed allocatability test.
#include "llvm/CodeGen/RegAllocPBQP.h"
Public Member Functions
MatrixMetadata (const Matrix &M)
MatrixMetadata (const MatrixMetadata &)=delete
MatrixMetadata & operator= (const MatrixMetadata &)=delete
unsigned getWorstRow () const
unsigned getWorstCol () const
const bool * getUnsafeRows () const
const bool * getUnsafeCols () const
Detailed Description
Metadata to speed allocatability test.
Keeps track of the number of infinities in each row and column.
Definition at line 51 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
MatrixMetadata() [1/2]
llvm::PBQP::RegAlloc::MatrixMetadata::MatrixMetadata (const Matrix & M) inline
Definition at line 53 of file RegAllocPBQP.h.
References llvm::PBQP::Matrix::getCols(), llvm::PBQP::Matrix::getRows(), llvm::max(), and operator=().
MatrixMetadata() [2/2]
llvm::PBQP::RegAlloc::MatrixMetadata::MatrixMetadata (const MatrixMetadata &) delete
Member Function Documentation
getUnsafeCols()
const bool* llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeCols () const inline
Definition at line 82 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
getUnsafeRows()
const bool* llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeRows () const inline
Definition at line 81 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
getWorstCol()
unsigned llvm::PBQP::RegAlloc::MatrixMetadata::getWorstCol () const inline
Definition at line 80 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
getWorstRow()
unsigned llvm::PBQP::RegAlloc::MatrixMetadata::getWorstRow () const inline
Definition at line 79 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
operator=()
MatrixMetadata& llvm::PBQP::RegAlloc::MatrixMetadata::operator= (const MatrixMetadata &) delete
Referenced by MatrixMetadata(), and llvm::PBQP::RegAlloc::NodeMetadata::NodeMetadata().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/RegAllocPBQP.h