LLVM: llvm::object::WindowsResourceParser::TreeNode Class Reference
llvm::object::WindowsResourceParser::TreeNode Class Reference
#include "llvm/Object/WindowsResource.h"
Public Types
template<typename T >
using Children = std::map< T, std::unique_ptr< TreeNode > >
Public Member Functions
void print (ScopedPrinter &Writer, StringRef Name) const
uint32_t getTreeSize () const
uint32_t getStringIndex () const
uint32_t getDataIndex () const
uint16_t getMajorVersion () const
uint16_t getMinorVersion () const
uint32_t getCharacteristics () const
bool checkIsDataNode () const
const Children< uint32_t > & getIDChildren () const
const Children< std::string > & getStringChildren () const
Friends
class WindowsResourceParser
Detailed Description
Definition at line 168 of file WindowsResource.h.
Member Typedef Documentation
Children
template<typename T > using llvm::object::WindowsResourceParser::TreeNode::Children = std::map<T, std::unique_ptr<TreeNode> >
Definition at line 171 of file WindowsResource.h.
Member Function Documentation
checkIsDataNode()
bool llvm::object::WindowsResourceParser::TreeNode::checkIsDataNode () const inline
Definition at line 180 of file WindowsResource.h.
getCharacteristics()
uint32_t llvm::object::WindowsResourceParser::TreeNode::getCharacteristics () const inline
Definition at line 179 of file WindowsResource.h.
References Characteristics.
getDataIndex()
uint32_t llvm::object::WindowsResourceParser::TreeNode::getDataIndex () const inline
Definition at line 176 of file WindowsResource.h.
getIDChildren()
const Children<uint32_t>& llvm::object::WindowsResourceParser::TreeNode::getIDChildren () const inline
Definition at line 181 of file WindowsResource.h.
Referenced by llvm::object::coffnamecpy().
getMajorVersion()
uint16_t llvm::object::WindowsResourceParser::TreeNode::getMajorVersion () const inline
Definition at line 177 of file WindowsResource.h.
getMinorVersion()
uint16_t llvm::object::WindowsResourceParser::TreeNode::getMinorVersion () const inline
Definition at line 178 of file WindowsResource.h.
getStringChildren()
const Children<std::string>& llvm::object::WindowsResourceParser::TreeNode::getStringChildren () const inline
Definition at line 182 of file WindowsResource.h.
Referenced by llvm::object::coffnamecpy().
getStringIndex()
uint32_t llvm::object::WindowsResourceParser::TreeNode::getStringIndex () const inline
Definition at line 175 of file WindowsResource.h.
getTreeSize()
uint32_t llvm::object::WindowsResourceParser::TreeNode::getTreeSize () const
Definition at line 565 of file WindowsResource.cpp.
References Size.
Referenced by llvm::object::WindowsResourceCOFFWriter::WindowsResourceCOFFWriter().
print()
void llvm::object::WindowsResourceParser::TreeNode::print (ScopedPrinter & Writer, StringRef Name) const
Definition at line 551 of file WindowsResource.cpp.
References llvm::to_string().
Referenced by llvm::object::WindowsResourceParser::printTree().
Friends And Related Function Documentation
WindowsResourceParser
friend class WindowsResourceParser friend
Definition at line 187 of file WindowsResource.h.
The documentation for this class was generated from the following files:
include/llvm/Object/WindowsResource.h
lib/Object/WindowsResource.cpp