LLVM: llvm::CombinerHelper Class Reference
llvm::CombinerHelper Class Reference
#include "llvm/CodeGen/GlobalISel/CombinerHelper.h"
Public Member Functions
CombinerHelper (GISelChangeObserver &Observer, MachineIRBuilder &B, GISelKnownBits *KB=nullptr, MachineDominatorTree *MDT=nullptr)
void replaceRegWith (MachineRegisterInfo &MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
void replaceRegOpWith (MachineRegisterInfo &MRI, MachineOperand &FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
bool tryCombineCopy (MachineInstr &MI)
If MI is COPY, try to combine it.
bool matchCombineCopy (MachineInstr &MI)
void applyCombineCopy (MachineInstr &MI)
bool isPredecessor (MachineInstr &DefMI, MachineInstr &UseMI)
Returns true if DefMI precedes UseMI or they are the same instruction.
bool dominates (MachineInstr &DefMI, MachineInstr &UseMI)
Returns true if DefMI dominates UseMI.
bool tryCombineExtendingLoads (MachineInstr &MI)
If MI is extend that consumes the result of a load, try to combine it.
bool matchCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
void applyCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
bool tryCombineIndexedLoadStore (MachineInstr &MI)
Combine MI into a pre-indexed or post-indexed load/store operation if legal and the surrounding code makes it useful.
bool matchCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo)
void applyCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo)
bool matchElideBrByInvertingCond (MachineInstr &MI)
void applyElideBrByInvertingCond (MachineInstr &MI)
bool tryElideBrByInvertingCond (MachineInstr &MI)
bool tryCombineConcatVectors (MachineInstr &MI)
If MI is G_CONCAT_VECTORS, try to combine it.
bool matchCombineConcatVectors (MachineInstr &MI, bool &IsUndef, SmallVectorImpl< Register > &Ops)
Check if the G_CONCAT_VECTORS MI is undef or if it can be flattened into a build_vector.
void applyCombineConcatVectors (MachineInstr &MI, bool IsUndef, const ArrayRef< Register > Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if IsUndef is true.
bool tryCombineShuffleVector (MachineInstr &MI)
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
bool matchCombineShuffleVector (MachineInstr &MI, SmallVectorImpl< Register > &Ops)
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
void applyCombineShuffleVector (MachineInstr &MI, const ArrayRef< Register > Ops)
Replace MI with a concat_vectors with Ops.
bool tryCombineMemCpyFamily (MachineInstr &MI, unsigned MaxLen=0)
Optimize memcpy intrinsics et al, e.g.
bool matchPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo)
bool applyPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo)
bool tryCombine (MachineInstr &MI)
Try to transform MI by using all of the above combine functions.
Protected Attributes
MachineIRBuilder & Builder
MachineRegisterInfo & MRI
GISelChangeObserver & Observer
GISelKnownBits * KB
MachineDominatorTree * MDT
Detailed Description
Definition at line 51 of file CombinerHelper.h.
Constructor & Destructor Documentation
CombinerHelper()
CombinerHelper::CombinerHelper (GISelChangeObserver & Observer, MachineIRBuilder & B, GISelKnownBits * KB = nullptr, MachineDominatorTree * MDT = nullptr)
Definition at line 34 of file CombinerHelper.cpp.
Member Function Documentation
applyCombineConcatVectors()
void CombinerHelper::applyCombineConcatVectors (MachineInstr & MI, bool IsUndef, const ArrayRef< Register > Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if IsUndef is true.
Definition at line 170 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildBuildVector(), Builder, llvm::MachineIRBuilder::buildUndef(), llvm::MachineRegisterInfo::cloneVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), MI, MRI, replaceRegWith(), and llvm::MachineIRBuilder::setInsertPt().
Referenced by tryCombineConcatVectors().
applyCombineCopy()
void CombinerHelper::applyCombineCopy (MachineInstr & MI)
Definition at line 108 of file CombinerHelper.cpp.
References llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), MRI, and replaceRegWith().
Referenced by tryCombineCopy().
applyCombineExtendingLoads()
void CombinerHelper::applyCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
rewrites to:
rewrites to:
Definition at line 452 of file CombinerHelper.cpp.
References Builder, llvm::MachineIRBuilder::buildTrunc(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::cloneVirtualRegister(), llvm::GISelChangeObserver::erasingInstr(), llvm::PreferredTuple::ExtendOpcode, llvm::MCInstrInfo::get(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::PreferredTuple::MI, MRI, Observer, llvm::SmallVectorTemplateBase< T >::push_back(), replaceRegOpWith(), replaceRegWith(), llvm::MachineInstr::setDesc(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineOperand::setReg(), llvm::PreferredTuple::Ty, llvm::MachineRegisterInfo::use_operands(), and UseMI.
Referenced by tryCombineExtendingLoads().
applyCombineIndexedLoadStore()
void CombinerHelper::applyCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo)
Definition at line 737 of file CombinerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::IndexedLoadStoreMatchInfo::Addr, llvm::MachineInstrBuilder::addUse(), llvm::IndexedLoadStoreMatchInfo::Base, llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::IndexedLoadStoreMatchInfo::IsPre, LLVM_DEBUG, llvm_unreachable, MRI, and llvm::IndexedLoadStoreMatchInfo::Offset.
Referenced by tryCombineIndexedLoadStore().
applyCombineShuffleVector()
void CombinerHelper::applyCombineShuffleVector (MachineInstr & MI, const ArrayRef< Register > Ops)
Replace MI with a concat_vectors with Ops.
Definition at line 277 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildCopy(), Builder, llvm::MachineIRBuilder::buildMerge(), llvm::MachineRegisterInfo::cloneVirtualRegister(), DefMI, llvm::MachineInstr::eraseFromParent(), llvm::PreferredTuple::ExtendOpcode, function, llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineInstr::isPHI(), llvm::LLT::isValid(), MI, MRI, replaceRegWith(), llvm::MachineIRBuilder::setInsertPt(), llvm::ArrayRef< T >::size(), llvm::PreferredTuple::Ty, and UseMI.
Referenced by tryCombineShuffleVector().
applyElideBrByInvertingCond()
void CombinerHelper::applyElideBrByInvertingCond (MachineInstr & MI)
Definition at line 826 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineInstr::eraseFromParent(), llvm::CmpInst::getInversePredicate(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), MRI, Observer, llvm::MachineOperand::setMBB(), and llvm::MachineOperand::setPredicate().
Referenced by tryElideBrByInvertingCond().
applyPtrAddImmedChain()
bool CombinerHelper::applyPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo)
Definition at line 1375 of file CombinerHelper.cpp.
References assert(), llvm::PtrAddChain::Base, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::PtrAddChain::Imm, MRI, Observer, and llvm::MachineOperand::setReg().
dominates()
bool CombinerHelper::dominates (MachineInstr & DefMI, MachineInstr & UseMI)
Returns true if DefMI dominates UseMI.
By definition an instruction dominates itself.
If we haven't been provided with a MachineDominatorTree during construction, this function returns a conservative result that tracks just a single basic block.
Definition at line 575 of file CombinerHelper.cpp.
References assert(), llvm::dbgs(), llvm::MachineDominatorTree::dominates(), ForceLegalIndexing, llvm::getDefIgnoringCopies(), llvm::MachineInstr::getOpcode(), llvm::getOpcodeDef(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), isPredecessor(), LLVM_DEBUG, MDT, MI, MRI, llvm::MachineRegisterInfo::use_instructions(), and UseMI.
isPredecessor()
bool CombinerHelper::isPredecessor (MachineInstr & DefMI, MachineInstr & UseMI)
Returns true if DefMI precedes UseMI or they are the same instruction.
Both must be in the same basic block.
Definition at line 562 of file CombinerHelper.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineInstr::getParent(), I, llvm_unreachable, and UseMI.
Referenced by dominates().
matchCombineConcatVectors()
bool CombinerHelper::matchCombineConcatVectors (MachineInstr & MI, bool & IsUndef, SmallVectorImpl< Register > & Ops)
Check if the G_CONCAT_VECTORS MI is undef or if it can be flattened into a build_vector.
In the first case IsUndef will be true. In the second case Ops will contain the operands needed to produce the flattened build_vector.
Precondition
MI.getOpcode() == G_CONCAT_VECTORS.
Definition at line 125 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildUndef(), llvm::tgtok::Def, llvm::LLT::getNumElements(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarType(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::MachineIRBuilder::setInsertPt(), llvm::RegState::Undef, and llvm::MachineInstr::uses().
Referenced by tryCombineConcatVectors().
matchCombineCopy()
bool CombinerHelper::matchCombineCopy (MachineInstr & MI)
Definition at line 72 of file CombinerHelper.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegBankOrNull(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::MachineRegisterInfo::getType(), llvm::Register::isPhysicalRegister(), llvm::LLT::isValid(), and MRI.
Referenced by tryCombineCopy().
matchCombineExtendingLoads()
bool CombinerHelper::matchCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
Definition at line 386 of file CombinerHelper.cpp.
References assert(), llvm::dbgs(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineRegisterInfo::getType(), llvm::isPowerOf2_32(), LLVM_DEBUG, llvm::PreferredTuple::MI, MRI, llvm::PreferredTuple::Ty, llvm::MachineRegisterInfo::use_instructions(), and UseMI.
Referenced by tryCombineExtendingLoads().
matchCombineIndexedLoadStore()
bool CombinerHelper::matchCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo)
Definition at line 721 of file CombinerHelper.cpp.
References llvm::IndexedLoadStoreMatchInfo::Addr, llvm::IndexedLoadStoreMatchInfo::Base, llvm::MachineInstr::getOpcode(), llvm::IndexedLoadStoreMatchInfo::IsPre, and llvm::IndexedLoadStoreMatchInfo::Offset.
Referenced by tryCombineIndexedLoadStore().
matchCombineShuffleVector()
bool CombinerHelper::matchCombineShuffleVector (MachineInstr & MI, SmallVectorImpl< Register > & Ops)
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
Ops will contain the operands needed to produce the flattened concat_vectors.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 201 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildUndef(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getShuffleMask(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), llvm::BitmaskEnumDetail::Mask(), MI, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::MachineIRBuilder::setInsertPt().
Referenced by tryCombineShuffleVector().
matchElideBrByInvertingCond()
bool CombinerHelper::matchElideBrByInvertingCond (MachineInstr & MI)
Definition at line 779 of file CombinerHelper.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), llvm::MachineBasicBlock::isLayoutSuccessor(), and MRI.
Referenced by tryElideBrByInvertingCond().
matchPtrAddImmedChain()
bool CombinerHelper::matchPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo)
Definition at line 1342 of file CombinerHelper.cpp.
References llvm::PtrAddChain::Base, llvm::getConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::PtrAddChain::Imm, and MRI.
replaceRegOpWith()
void CombinerHelper::replaceRegOpWith (MachineRegisterInfo & MRI, MachineOperand & FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
Definition at line 54 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineOperand::getParent(), Observer, and llvm::MachineOperand::setReg().
Referenced by applyCombineExtendingLoads().
replaceRegWith()
void CombinerHelper::replaceRegWith (MachineRegisterInfo & MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
Definition at line 42 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildCopy(), Builder, llvm::GISelChangeObserver::changingAllUsesOfReg(), llvm::MachineRegisterInfo::constrainRegAttrs(), llvm::GISelChangeObserver::finishedChangingAllUsesOfReg(), Observer, and llvm::MachineRegisterInfo::replaceRegWith().
Referenced by applyCombineConcatVectors(), applyCombineCopy(), applyCombineExtendingLoads(), and applyCombineShuffleVector().
tryCombine()
bool CombinerHelper::tryCombine (MachineInstr & MI)
Try to transform MI by using all of the above combine functions.
Returns true if changed.
Definition at line 1388 of file CombinerHelper.cpp.
References tryCombineCopy(), tryCombineExtendingLoads(), and tryCombineIndexedLoadStore().
tryCombineConcatVectors()
bool CombinerHelper::tryCombineConcatVectors (MachineInstr & MI)
If MI is G_CONCAT_VECTORS, try to combine it.
Returns true if MI changed. Right now, we support:
concat_vector(undef, undef) => undef
concat_vector(build_vector(A, B), build_vector(C, D)) => build_vector(A, B, C, D)
Precondition
MI.getOpcode() == G_CONCAT_VECTORS.
Definition at line 115 of file CombinerHelper.cpp.
References applyCombineConcatVectors(), and matchCombineConcatVectors().
tryCombineCopy()
bool CombinerHelper::tryCombineCopy (MachineInstr & MI)
If MI is COPY, try to combine it.
Returns true if MI changed.
Definition at line 65 of file CombinerHelper.cpp.
References applyCombineCopy(), and matchCombineCopy().
Referenced by tryCombine().
tryCombineExtendingLoads()
bool CombinerHelper::tryCombineExtendingLoads (MachineInstr & MI)
If MI is extend that consumes the result of a load, try to combine it.
Returns true if MI changed.
Definition at line 377 of file CombinerHelper.cpp.
References applyCombineExtendingLoads(), and matchCombineExtendingLoads().
Referenced by tryCombine().
tryCombineIndexedLoadStore()
bool CombinerHelper::tryCombineIndexedLoadStore (MachineInstr & MI)
Combine MI into a pre-indexed or post-indexed load/store operation if legal and the surrounding code makes it useful.
Definition at line 712 of file CombinerHelper.cpp.
References applyCombineIndexedLoadStore(), and matchCombineIndexedLoadStore().
Referenced by tryCombine().
tryCombineMemCpyFamily()
bool CombinerHelper::tryCombineMemCpyFamily (MachineInstr & MI, unsigned MaxLen = 0)
Optimize memcpy intrinsics et al, e.g.
constant len calls. /p MaxLen if non-zero specifies the max length of a mem libcall to inline.
For example (pre-indexed):
$addr = G_PTR_ADD $base, $offset
[...]
$val = G_LOAD $addr
[...]
$whatever = COPY $addr
–>
$val, $addr = G_INDEXED_LOAD $base, $offset, 1 (IsPre)
[...]
$whatever = COPY $addr
or (post-indexed):
G_STORE $val, $base
[...]
$addr = G_PTR_ADD $base, $offset
[...]
$whatever = COPY $addr
–>
$addr = G_INDEXED_STORE $val, $base, $offset
[...]
$whatever = COPY $addr
Definition at line 1291 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::eraseFromParent(), llvm::MachineMemOperand::getBaseAlignment(), llvm::getConstantVRegValWithLookThrough(), llvm::MachineInstr::getIntrinsicID(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineMemOperand::isVolatile(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), and MRI.
tryCombineShuffleVector()
bool CombinerHelper::tryCombineShuffleVector (MachineInstr & MI)
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
Returns true if MI changed.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 192 of file CombinerHelper.cpp.
References applyCombineShuffleVector(), and matchCombineShuffleVector().
tryElideBrByInvertingCond()
bool CombinerHelper::tryElideBrByInvertingCond (MachineInstr & MI)
Definition at line 819 of file CombinerHelper.cpp.
References applyElideBrByInvertingCond(), and matchElideBrByInvertingCond().
Member Data Documentation
Builder
MachineIRBuilder& llvm::CombinerHelper::Builder protected
Definition at line 53 of file CombinerHelper.h.
Referenced by applyCombineConcatVectors(), applyCombineExtendingLoads(), applyCombineShuffleVector(), matchCombineConcatVectors(), matchCombineShuffleVector(), and replaceRegWith().
KB
GISelKnownBits* llvm::CombinerHelper::KB protected
Definition at line 56 of file CombinerHelper.h.
MDT
MachineDominatorTree* llvm::CombinerHelper::MDT protected
Definition at line 57 of file CombinerHelper.h.
Referenced by dominates().
MRI
MachineRegisterInfo& llvm::CombinerHelper::MRI protected
Definition at line 54 of file CombinerHelper.h.
Referenced by applyCombineConcatVectors(), applyCombineCopy(), applyCombineExtendingLoads(), applyCombineIndexedLoadStore(), applyCombineShuffleVector(), applyElideBrByInvertingCond(), applyPtrAddImmedChain(), dominates(), getMemsetValue(), matchCombineConcatVectors(), matchCombineCopy(), matchCombineExtendingLoads(), matchCombineShuffleVector(), matchElideBrByInvertingCond(), matchPtrAddImmedChain(), and tryCombineMemCpyFamily().
Observer
GISelChangeObserver& llvm::CombinerHelper::Observer protected
Definition at line 55 of file CombinerHelper.h.
Referenced by applyCombineExtendingLoads(), applyElideBrByInvertingCond(), applyPtrAddImmedChain(), replaceRegOpWith(), and replaceRegWith().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CombinerHelper.h
lib/CodeGen/GlobalISel/CombinerHelper.cpp