LLVM: llvm::codeview::FunctionId Class Reference
llvm::codeview::FunctionId Class Reference
#include "llvm/DebugInfo/CodeView/FunctionId.h"
Public Member Functions
FunctionId ()
FunctionId (uint32_t Index)
uint32_t getIndex () const
Detailed Description
Definition at line 17 of file FunctionId.h.
Constructor & Destructor Documentation
FunctionId() [1/2]
llvm::codeview::FunctionId::FunctionId () inline
Definition at line 19 of file FunctionId.h.
FunctionId() [2/2]
llvm::codeview::FunctionId::FunctionId (uint32_t Index) inline explicit
Definition at line 21 of file FunctionId.h.
Member Function Documentation
getIndex()
uint32_t llvm::codeview::FunctionId::getIndex () const inline
Definition at line 23 of file FunctionId.h.
Referenced by llvm::codeview::operator!=(), llvm::codeview::operator<(), llvm::codeview::operator<=(), llvm::codeview::operator==(), llvm::codeview::operator>(), and llvm::codeview::operator>=().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/FunctionId.h