LLVM: llvm::MCInstrDesc Class Reference
llvm::MCInstrDesc Class Reference
Describe properties that are true of each instruction in the target description file.
#include "llvm/MC/MCInstrDesc.h"
Public Types
using const_opInfo_iterator = const MCOperandInfo *
Public Member Functions
int getOperandConstraint (unsigned OpNum, MCOI::OperandConstraint Constraint) const
Returns the value of the specific constraint if it is set.
bool getDeprecatedInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info) const
Returns true if a certain instruction is deprecated and if so returns the reason in Info.
unsigned getOpcode () const
Return the opcode number for this descriptor.
unsigned getNumOperands () const
Return the number of declared MachineOperands for this MachineInstruction.
const_opInfo_iterator opInfo_begin () const
const_opInfo_iterator opInfo_end () const
iterator_range< const_opInfo_iterator > operands () const
unsigned getNumDefs () const
Return the number of MachineOperands that are register definitions.
uint64_t getFlags () const
Return flags of this instruction.
bool isPreISelOpcode () const
bool isVariadic () const
Return true if this instruction can have a variable number of operands.
bool hasOptionalDef () const
Set if this instruction has an optional definition, e.g.
bool isPseudo () const
Return true if this is a pseudo instruction that doesn't correspond to a real machine instruction.
bool isReturn () const
Return true if the instruction is a return.
bool isAdd () const
Return true if the instruction is an add instruction.
bool isTrap () const
Return true if this instruction is a trap.
bool isMoveReg () const
Return true if the instruction is a register to register move.
bool isCall () const
Return true if the instruction is a call.
bool isBarrier () const
Returns true if the specified instruction stops control flow from executing the instruction immediately following it.
bool isTerminator () const
Returns true if this instruction part of the terminator for a basic block.
bool isBranch () const
Returns true if this is a conditional, unconditional, or indirect branch.
bool isIndirectBranch () const
Return true if this is an indirect branch, such as a branch through a register.
bool isConditionalBranch () const
Return true if this is a branch which may fall through to the next instruction or may transfer control flow to some other block.
bool isUnconditionalBranch () const
Return true if this is a branch which always transfers control flow to some other block.
bool mayAffectControlFlow (const MCInst &MI, const MCRegisterInfo &RI) const
Return true if this is a branch or an instruction which directly writes to the program counter.
bool isPredicable () const
Return true if this instruction has a predicate operand that controls execution.
bool isCompare () const
Return true if this instruction is a comparison.
bool isMoveImmediate () const
Return true if this instruction is a move immediate (including conditional moves) instruction.
bool isBitcast () const
Return true if this instruction is a bitcast instruction.
bool isSelect () const
Return true if this is a select instruction.
bool isNotDuplicable () const
Return true if this instruction cannot be safely duplicated.
bool hasDelaySlot () const
Returns true if the specified instruction has a delay slot which must be filled by the code generator.
bool canFoldAsLoad () const
Return true for instructions that can be folded as memory operands in other instructions.
bool isRegSequenceLike () const
Return true if this instruction behaves the same way as the generic REG_SEQUENCE instructions.
bool isExtractSubregLike () const
Return true if this instruction behaves the same way as the generic EXTRACT_SUBREG instructions.
bool isInsertSubregLike () const
Return true if this instruction behaves the same way as the generic INSERT_SUBREG instructions.
bool isConvergent () const
Return true if this instruction is convergent.
bool variadicOpsAreDefs () const
Return true if variadic operands of this instruction are definitions.
bool isAuthenticated () const
Return true if this instruction authenticates a pointer (e.g.
bool mayLoad () const
Return true if this instruction could possibly read memory.
bool mayStore () const
Return true if this instruction could possibly modify memory.
bool mayRaiseFPException () const
Return true if this instruction may raise a floating-point exception.
bool hasUnmodeledSideEffects () const
Return true if this instruction has side effects that are not modeled by other flags.
bool isCommutable () const
Return true if this may be a 2- or 3-address instruction (of the form "X = op Y, Z, ..."), which produces the same result if Y and Z are exchanged.
bool isConvertibleTo3Addr () const
Return true if this is a 2-address instruction which can be changed into a 3-address instruction if needed.
bool usesCustomInsertionHook () const
Return true if this instruction requires custom insertion support when the DAG scheduler is inserting it into a machine basic block.
bool hasPostISelHook () const
Return true if this instruction requires adjustment after instruction selection by calling a target hook.
bool isRematerializable () const
Returns true if this instruction is a candidate for remat.
bool isAsCheapAsAMove () const
Returns true if this instruction has the same cost (or less) than a move instruction.
bool hasExtraSrcRegAllocReq () const
Returns true if this instruction source operands have special register allocation requirements that are not captured by the operand register classes.
bool hasExtraDefRegAllocReq () const
Returns true if this instruction def operands have special register allocation requirements that are not captured by the operand register classes.
const MCPhysReg * getImplicitUses () const
Return a list of registers that are potentially read by any instance of this machine instruction.
unsigned getNumImplicitUses () const
Return the number of implicit uses this instruction has.
const MCPhysReg * getImplicitDefs () const
Return a list of registers that are potentially written by any instance of this machine instruction.
unsigned getNumImplicitDefs () const
Return the number of implicit defs this instruct has.
bool hasImplicitUseOfPhysReg (unsigned Reg) const
Return true if this instruction implicitly uses the specified physical register.
bool hasImplicitDefOfPhysReg (unsigned Reg, const MCRegisterInfo *MRI=nullptr) const
Return true if this instruction implicitly defines the specified physical register.
unsigned getSchedClass () const
Return the scheduling class for this instruction.
unsigned getSize () const
Return the number of bytes in the encoding of this instruction, or zero if the encoding size cannot be known from the opcode.
int findFirstPredOperandIdx () const
Find the index of the first operand in the operand list that is used to represent the predicate.
bool hasDefOfPhysReg (const MCInst &MI, unsigned Reg, const MCRegisterInfo &RI) const
Return true if this instruction defines the specified physical register, either explicitly or implicitly.
Public Attributes
unsigned short Opcode
unsigned short NumOperands
unsigned char NumDefs
unsigned char Size
unsigned short SchedClass
uint64_t Flags
uint64_t TSFlags
const MCPhysReg * ImplicitUses
const MCPhysReg * ImplicitDefs
const MCOperandInfo * OpInfo
int64_t DeprecatedFeature
bool(* ComplexDeprecationInfo)(MCInst &, const MCSubtargetInfo &, std::string &)
Detailed Description
Describe properties that are true of each instruction in the target description file.
This captures information about side effects, register use and many other things. There is one instance of this struct for each target instruction class, and the MachineInstr class points to this struct directly to describe itself.
Definition at line 188 of file MCInstrDesc.h.
Member Typedef Documentation
const_opInfo_iterator
using llvm::MCInstrDesc::const_opInfo_iterator = const MCOperandInfo *
Definition at line 237 of file MCInstrDesc.h.
Member Function Documentation
canFoldAsLoad()
bool llvm::MCInstrDesc::canFoldAsLoad () const inline
Return true for instructions that can be folded as memory operands in other instructions.
The most common use for this is instructions that are simple loads from memory that don't modify the loaded value in any way, but it can also be used for instructions that can be expressed as constant-pool loads, such as V_SETALLONES on x86, to allow them to be folded when it is beneficial. This should only be set on instructions that return a value in their only virtual register definition.
Definition at line 367 of file MCInstrDesc.h.
References llvm::MCID::FoldableAsLoad.
findFirstPredOperandIdx()
int llvm::MCInstrDesc::findFirstPredOperandIdx () const inline
Find the index of the first operand in the operand list that is used to represent the predicate.
It returns -1 if none is found.
Definition at line 628 of file MCInstrDesc.h.
References llvm::numbers::e.
Referenced by llvm::IsCPSRDead< MCInst >().
getDeprecatedInfo()
bool MCInstrDesc::getDeprecatedInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) const
Returns true if a certain instruction is deprecated and if so returns the reason in Info.
Definition at line 21 of file MCInstrDesc.cpp.
References ComplexDeprecationInfo, DeprecatedFeature, and llvm::MCSubtargetInfo::getFeatureBits().
getFlags()
uint64_t llvm::MCInstrDesc::getFlags () const inline
Return flags of this instruction.
Definition at line 253 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::hasProperty().
getImplicitDefs()
const MCPhysReg* llvm::MCInstrDesc::getImplicitDefs () const inline
Return a list of registers that are potentially written by any instance of this machine instruction.
For example, on X86, many instructions implicitly set the flags register. In this case, they are marked as setting the FLAGS. Likewise, many instructions always deposit their result in a physical register. For example, the X86 divide instruction always deposits the quotient and remainder in the EAX/EDX registers. For that instruction, this will return a list containing the EAX/EDX/EFLAGS registers.
This method returns null if the instruction has no implicit defs.
Definition at line 588 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::addImplicitDefUseOperands(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::InstrEmitter::EmitDbgLabel(), getPhysicalRegisterVT(), HasImplicitCPSRDef(), llvm::rdf::TargetOperandInfo::isFixedReg(), isImplicitOperandIn(), llvm::PPCInstrInfo::optimizeCompareInstr(), and llvm::mca::verifyOperands().
getImplicitUses()
const MCPhysReg* llvm::MCInstrDesc::getImplicitUses () const inline
Return a list of registers that are potentially read by any instance of this machine instruction.
For example, on X86, the "adc" instruction adds two register operands and adds the carry bit in from the flags register. In this case, the instruction is marked as implicitly reading the flags. Likewise, the variable shift instruction on X86 is marked as implicitly reading the 'CL' register, which it always does.
This method returns null if the instruction has no implicit uses.
Definition at line 566 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::addImplicitDefUseOperands(), llvm::InstrEmitter::EmitDbgLabel(), llvm::rdf::TargetOperandInfo::isFixedReg(), isImplicitOperandIn(), llvm::PPCInstrInfo::optimizeCompareInstr(), and llvm::mca::verifyOperands().
getNumDefs()
unsigned llvm::MCInstrDesc::getNumDefs () const inline
Return the number of MachineOperands that are register definitions.
Register definitions always occur at the start of the machine operand list. This is the number of "outs" in the .td file, and does not include implicit defs.
Definition at line 250 of file MCInstrDesc.h.
Referenced by AnyAliasLiveIn(), atomicReadDroppedOnZero(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), canEnableCoalescing(), CheckForPhysRegDependency(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::TargetInstrInfo::commuteInstructionImpl(), computeBytesPoppedByCalleeForSRet(), llvm::createBreakFalseDeps(), llvm::createR600ISelDag(), definesFullReg(), llvm::InstrEmitter::EmitDbgLabel(), encodeBitmaskPerm(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::FastISel::fastEmitInst_f(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrr(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::TargetInstrInfo::findCommutedOpIndices(), findStartOfTree(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::Localizer::getAnalysisUsage(), getCompareCC(), llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs(), llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs(), llvm::ARMBaseInstrInfo::getLDMVariableDefsSize(), getNewSource(), llvm::MachineInstr::getNumExplicitDefs(), llvm::X86II::getOperandBias(), getPhysicalRegisterVT(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::ARMTargetLowering::getSchedulingPreference(), gwsIntrinToOpcode(), llvm::ResourcePriorityQueue::initNumRegDefsLeft(), insertPHI(), isCoalescable(), isCopyFeedingInvariantStore(), isCrossCopy(), llvm::HexagonInstrInfo::isDependent(), isMulPowOf2(), isRegOrImmWithInputMods(), isVirtualRegisterOperand(), oneUseDominatesOtherUses(), llvm::HexagonMCInstrInfo::predicateInfo(), printMasking(), llvm::HexagonMCChecker::reportBranchErrors(), llvm::SystemZHazardRecognizer::Reset(), rewritesSort(), llvm::X86InstrInfo::unfoldMemoryOperand(), and llvm::mca::verifyOperands().
getNumImplicitDefs()
unsigned llvm::MCInstrDesc::getNumImplicitDefs () const inline
Return the number of implicit defs this instruct has.
Definition at line 591 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::addImplicitDefUseOperands(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), copyExtraImplicitOps(), llvm::InstrEmitter::EmitDbgLabel(), llvm::MachineInstr::getNumDefs(), stripExtraCopyOperands(), and llvm::mca::verifyOperands().
getNumImplicitUses()
unsigned llvm::MCInstrDesc::getNumImplicitUses () const inline
Return the number of implicit uses this instruction has.
Definition at line 569 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::addImplicitDefUseOperands(), copyExtraImplicitOps(), llvm::InstrEmitter::EmitDbgLabel(), llvm::SIInstrInfo::expandPostRAPseudo(), getRegNum(), llvm::SIInstrInfo::isFoldableCopy(), stripExtraCopyOperands(), llvm::SIInstrInfo::verifyInstruction(), and llvm::mca::verifyOperands().
getNumOperands()
unsigned llvm::MCInstrDesc::getNumOperands () const inline
Return the number of declared MachineOperands for this MachineInstruction.
Note that variadic (isVariadic() returns true) instructions may have additional operands at the end of the list, and note that the machine instruction may include implicit register def/uses as well.
Definition at line 235 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::addImplicitDefUseOperands(), addLiveInRegs(), llvm::MachineInstr::addOperand(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), canEnableCoalescing(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), copyExtraImplicitOps(), llvm::MachineInstr::copyImplicitOps(), llvm::PPCInstrInfo::copyPhysReg(), llvm::createLanaiDelaySlotFillerPass(), llvm::createR600ISelDag(), CriticalPathStep(), definesFullReg(), llvm::InstrEmitter::EmitDbgLabel(), emitDirectiveRelocJalr(), Expand2AddrKreg(), Expand2AddrUndef(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::findFirstVPTPredOperandIdx(), llvm::PPCInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::X86InstrInfo::foldMemoryOperandImpl(), FuseTwoAddrInst(), llvm::LegalizerInfo::getAction(), llvm::X86::getCondFromBranch(), getCondFromBranch(), llvm::X86::getCondFromCMov(), llvm::X86::getCondFromSETCC(), GetDSubRegs(), llvm::X86InstrInfo::getExecutionDomainCustom(), llvm::ARMBaseInstrInfo::getLDMVariableDefsSize(), getLit64Encoding(), getLSMultipleTransferSize(), getMemoryOpOffset(), getNewSource(), llvm::MachineInstr::getNumExplicitOperands(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::X86II::getOperandBias(), llvm::SIInstrInfo::getOpRegClass(), llvm::TargetInstrInfo::getRegClass(), llvm::SIInstrInfo::getRegClass(), getTargetMBB(), INITIALIZE_PASS(), isCopy(), isCopyFeedingInvariantStore(), llvm::SIInstrInfo::isFoldableCopy(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::AArch64InstrInfo::isGPRCopy(), llvm::AArch64InstrInfo::isGPRZero(), isOperandOf(), isPCRel32Branch(), llvm::SIInstrInfo::isReallyTriviallyReMaterializable(), needsExpandMemInst(), llvm::HexagonMCInstrInfo::predicateInfo(), llvm::WebAssemblyInstPrinter::printInst(), RemoveDeadAddBetweenLEAAndJT(), llvm::SystemZHazardRecognizer::Reset(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), stripExtraCopyOperands(), tryAddToFoldList(), tryToFoldACImm(), llvm::SystemZInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), VerifyLowRegs(), and llvm::mca::verifyOperands().
getOpcode()
unsigned llvm::MCInstrDesc::getOpcode () const inline
Return the opcode number for this descriptor.
Definition at line 228 of file MCInstrDesc.h.
Referenced by adjustDefLatency(), llvm::constrainOperandRegClass(), llvm::createRISCVMCCodeEmitter(), llvm::MipsSEInstrInfo::expandPostRAPseudo(), llvm::Mips16InstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::findCommutedOpIndices(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getLDMVariableDefsSize(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::ARMBaseInstrInfo::getOperandLatency(), hasRAWHazard(), INITIALIZE_PASS(), llvm::HexagonInstrInfo::isComplex(), isFpMulInstruction(), isPCRel(), raise_relocation_error(), llvm::SIInstrInfo::verifyInstruction(), and VerifyLowRegs().
getOperandConstraint()
int llvm::MCInstrDesc::getOperandConstraint (unsigned OpNum, MCOI::OperandConstraint Constraint) const inline
Returns the value of the specific constraint if it is set.
Returns -1 if it is not set.
Definition at line 212 of file MCInstrDesc.h.
References llvm::MCOperandInfo::Constraints, Info, and MI.
Referenced by llvm::MachineInstr::addOperand(), canEnableCoalescing(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::constrainSelectedInstRegOperands(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86II::getOperandBias(), getRegNum(), llvm::MachineInstr::hasComplexRegisterTies(), isCoalescable(), isMatchingOrAlias(), isOperandOf(), isRegOrImmWithInputMods(), isVectorPredicable(), printMasking(), llvm::SystemZHazardRecognizer::Reset(), and tieOpsIfNeeded().
getSchedClass()
unsigned llvm::MCInstrDesc::getSchedClass () const inline
Return the scheduling class for this instruction.
The scheduling class is an index into the InstrItineraryData table. This returns zero if there is no known scheduling information for the instruction.
Definition at line 619 of file MCInstrDesc.h.
Referenced by llvm::DFAPacketizer::canReserveResources(), llvm::ResourceManager::canReserveResources(), llvm::TargetSchedModel::computeInstrLatency(), llvm::TargetSchedModel::computeOperandLatency(), llvm::TargetSchedModel::computeReciprocalThroughput(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::PPCInstrInfo::getInstrLatency(), llvm::TargetInstrInfo::getInstrLatency(), llvm::HexagonInstrInfo::getInstrTimingClassLatency(), getItineraryLatency(), getLatency(), llvm::ARMBaseInstrInfo::getLDMVariableDefsSize(), llvm::TargetSchedModel::getNumMicroOps(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::TargetInstrInfo::getNumMicroOps(), getNumMicroOpsSwiftLdSt(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), llvm::HexagonMCInstrInfo::getOtherReservedSlots(), llvm::ARMTargetLowering::getSchedulingPreference(), getUnderlyingObjects(), llvm::HexagonMCInstrInfo::getUnits(), llvm::HexagonInstrInfo::getUnits(), llvm::TargetInstrInfo::hasLowDefLatency(), llvm::HexagonPacketizerList::ignorePseudoInstruction(), llvm::HexagonInstrInfo::isEarlySourceInstr(), llvm::HexagonInstrInfo::isLateResultInstr(), llvm::HexagonInstrInfo::isTC1(), llvm::HexagonInstrInfo::isTC2(), llvm::HexagonInstrInfo::isTC2Early(), llvm::HexagonInstrInfo::isTC4x(), llvm::DFAPacketizer::reserveResources(), llvm::ResourceManager::reserveResources(), llvm::TargetSchedModel::resolveSchedClass(), and llvm::mca::verifyOperands().
getSize()
unsigned llvm::MCInstrDesc::getSize () const inline
Return the number of bytes in the encoding of this instruction, or zero if the encoding size cannot be known from the opcode.
Definition at line 623 of file MCInstrDesc.h.
References Size.
Referenced by llvm::createRISCVMCCodeEmitter(), llvm::MipsMCCodeEmitter::encodeInstruction(), llvm::MSP430MCCodeEmitter::encodeInstruction(), llvm::ARCInstrInfo::getInstSizeInBytes(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::AVRInstrInfo::getInstSizeInBytes(), llvm::PPCMCCodeEmitter::getInstSizeInBytes(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::SIInstrInfo::getInstSizeInBytes(), getLit64Encoding(), llvm::HexagonInstrInfo::getSize(), getUnconditionalBrDisp(), HasConditionalBranch(), and needsPCRel().
hasDefOfPhysReg()
bool MCInstrDesc::hasDefOfPhysReg (const MCInst & MI, unsigned Reg, const MCRegisterInfo & RI) const
Return true if this instruction defines the specified physical register, either explicitly or implicitly.
Definition at line 53 of file MCInstrDesc.cpp.
References llvm::numbers::e, llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), hasImplicitDefOfPhysReg(), llvm::MCOperand::isReg(), llvm::MCRegisterInfo::isSubRegisterEq(), NumDefs, NumOperands, and variadicOpsAreDefs().
Referenced by llvm::IsCPSRDead< MCInst >(), and mayAffectControlFlow().
hasDelaySlot()
bool llvm::MCInstrDesc::hasDelaySlot () const inline
Returns true if the specified instruction has a delay slot which must be filled by the code generator.
Definition at line 358 of file MCInstrDesc.h.
References llvm::MCID::DelaySlot.
Referenced by covertDoubleImmToSingleImm(), and needsExpandMemInst().
hasExtraDefRegAllocReq()
bool llvm::MCInstrDesc::hasExtraDefRegAllocReq () const inline
Returns true if this instruction def operands have special register allocation requirements that are not captured by the operand register classes.
e.g. ARM::LDRD's two def registers must be an even / odd pair, ARM::LDM registers have to be in ascending order. Post-register allocation passes should not attempt to change allocations for definitions of instructions with this flag.
Definition at line 554 of file MCInstrDesc.h.
References llvm::MCID::ExtraDefRegAllocReq.
hasExtraSrcRegAllocReq()
bool llvm::MCInstrDesc::hasExtraSrcRegAllocReq () const inline
Returns true if this instruction source operands have special register allocation requirements that are not captured by the operand register classes.
e.g. ARM::STRD's two source registers must be an even / odd pair, ARM::STM registers have to be in ascending order. Post-register allocation passes should not attempt to change allocations for sources of instructions with this flag.
Definition at line 544 of file MCInstrDesc.h.
References llvm::MCID::ExtraSrcRegAllocReq.
hasImplicitDefOfPhysReg()
bool MCInstrDesc::hasImplicitDefOfPhysReg (unsigned Reg, const MCRegisterInfo * MRI = nullptr) const
Return true if this instruction implicitly defines the specified physical register.
Definition at line 44 of file MCInstrDesc.cpp.
References ImplicitDefs, and llvm::MCRegisterInfo::isSubRegister().
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::RISCVInstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), hasDefOfPhysReg(), and llvm::AMDGPUInstPrinter::printRegOperand().
hasImplicitUseOfPhysReg()
bool llvm::MCInstrDesc::hasImplicitUseOfPhysReg (unsigned Reg) const inline
Return true if this instruction implicitly uses the specified physical register.
Definition at line 602 of file MCInstrDesc.h.
References MRI, and Reg.
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), and llvm::X86InstrInfo::getOutliningType().
hasOptionalDef()
bool llvm::MCInstrDesc::hasOptionalDef () const inline
Set if this instruction has an optional definition, e.g.
ARM instructions which can set condition code if 's' bit is set.
Definition at line 267 of file MCInstrDesc.h.
References llvm::MCID::HasOptionalDef.
Referenced by llvm::ARMBaseInstrInfo::FoldImmediate(), getRealVLDOpcode(), VerifyLowRegs(), and llvm::mca::verifyOperands().
hasPostISelHook()
bool llvm::MCInstrDesc::hasPostISelHook () const inline
Return true if this instruction requires adjustment after instruction selection by calling a target hook.
For example, this can be used to fill in ARM 's' optional operand depending on whether the conditional flag register is used.
Definition at line 515 of file MCInstrDesc.h.
References llvm::MCID::HasPostISelHook.
hasUnmodeledSideEffects()
bool llvm::MCInstrDesc::hasUnmodeledSideEffects () const inline
Return true if this instruction has side effects that are not modeled by other flags.
This does not return true for instructions whose effects are captured by:
Their operand list and implicit definition/use list. Register use/def info is explicit for instructions.
Memory accesses. Use mayLoad/mayStore.
Calling, branching, returning: use isCall/isReturn/isBranch.
Examples of side effects would be modifying 'invisible' machine state like a control register, flushing a cache, modifying a register invisible to LLVM, etc.
Definition at line 461 of file MCInstrDesc.h.
References llvm::MCID::UnmodeledSideEffects.
Referenced by llvm::mca::verifyOperands().
isAdd()
bool llvm::MCInstrDesc::isAdd () const inline
Return true if the instruction is an add instruction.
Definition at line 277 of file MCInstrDesc.h.
References llvm::MCID::Add.
Referenced by llvm::createHexagonHardwareLoops(), and isImmValidForOpcode().
isAsCheapAsAMove()
bool llvm::MCInstrDesc::isAsCheapAsAMove () const inline
Returns true if this instruction has the same cost (or less) than a move instruction.
This is useful during certain types of optimizations (e.g., remat during two-address conversion or machine licm) where we would like to remat or hoist the instruction, but not if it costs more than moving the instruction into the appropriate register. Note, we are not marking copies from and to the same register class with this flag.
This method could be called by interface TargetInstrInfo::isAsCheapAsAMove for different subtargets.
Definition at line 536 of file MCInstrDesc.h.
References llvm::MCID::CheapAsAMove.
isAuthenticated()
bool llvm::MCInstrDesc::isAuthenticated () const inline
Return true if this instruction authenticates a pointer (e.g.
LDRAx/BRAx from ARMv8.3, which perform loads/branches with authentication).
An authenticated instruction may fail in an ABI-defined manner when operating on an invalid signed pointer.
Definition at line 425 of file MCInstrDesc.h.
References llvm::MCID::Authenticated.
isBarrier()
bool llvm::MCInstrDesc::isBarrier () const inline
Returns true if the specified instruction stops control flow from executing the instruction immediately following it.
Examples include unconditional branches and return instructions.
Definition at line 291 of file MCInstrDesc.h.
References llvm::MCID::Barrier.
isBitcast()
bool llvm::MCInstrDesc::isBitcast () const inline
Return true if this instruction is a bitcast instruction.
Definition at line 346 of file MCInstrDesc.h.
References llvm::MCID::Bitcast.
isBranch()
bool llvm::MCInstrDesc::isBranch () const inline
Returns true if this is a conditional, unconditional, or indirect branch.
Predicates below can be used to discriminate between these cases, and the TargetInstrInfo::AnalyzeBranch method can be used to get more information.
Definition at line 305 of file MCInstrDesc.h.
References llvm::MCID::Branch.
Referenced by llvm::PPCDispatchGroupSBHazardRecognizer::EmitInstruction(), llvm::RISCVInstrInfo::getBranchDestBlock(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::IsCPSRDead< MCInst >(), isPCRel(), mayAffectControlFlow(), needsExpandMemInst(), raise_relocation_error(), llvm::HexagonMCChecker::reportBranchErrors(), and llvm::SIInstrInfo::verifyInstruction().
isCall()
bool llvm::MCInstrDesc::isCall () const inline
Return true if the instruction is a call.
Definition at line 286 of file MCInstrDesc.h.
References llvm::MCID::Call.
Referenced by llvm::mca::computeMaxLatency(), findPotentialBlockers(), llvm::ARMBaseInstrInfo::getOperandLatency(), hasVariantSymbol(), isControlFlow(), llvm::IsCPSRDead< MCInst >(), isImplicitOperandIn(), mayAffectControlFlow(), needsExpandMemInst(), raise_relocation_error(), llvm::HexagonMCChecker::reportBranchErrors(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ResourcePriorityQueue::SUSchedulingCost(), and llvm::mca::verifyOperands().
isCommutable()
bool llvm::MCInstrDesc::isCommutable () const inline
Return true if this may be a 2- or 3-address instruction (of the form "X = op Y, Z, ..."), which produces the same result if Y and Z are exchanged.
If this flag is set, then the TargetInstrInfo::commuteInstruction method may be used to hack on the instruction.
Note that this flag may be set on instructions that are only commutable sometimes. In these cases, the call to commuteInstruction will fail. Also note that some instructions require non-trivial modification to commute them.
Definition at line 479 of file MCInstrDesc.h.
References llvm::MCID::Commutable.
Referenced by convertTailJumpOpcode(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::SIInstrInfo::findCommutedOpIndices(), gwsIntrinToOpcode(), and isOperandOf().
isCompare()
bool llvm::MCInstrDesc::isCompare () const inline
Return true if this instruction is a comparison.
Definition at line 339 of file MCInstrDesc.h.
References llvm::MCID::Compare.
Referenced by getNewValueJumpOpcode().
isConditionalBranch()
bool llvm::MCInstrDesc::isConditionalBranch () const inline
Return true if this is a branch which may fall through to the next instruction or may transfer control flow to some other block.
The TargetInstrInfo::AnalyzeBranch method can be used to get more information about this branch.
Definition at line 315 of file MCInstrDesc.h.
References isBranch().
Referenced by hasVariantSymbol(), and isFirstMacroFusibleInst().
isConvergent()
bool llvm::MCInstrDesc::isConvergent () const inline
Return true if this instruction is convergent.
Convergent instructions may not be made control-dependent on any additional values.
Definition at line 413 of file MCInstrDesc.h.
References llvm::MCID::Convergent.
isConvertibleTo3Addr()
bool llvm::MCInstrDesc::isConvertibleTo3Addr () const inline
Return true if this is a 2-address instruction which can be changed into a 3-address instruction if needed.
Doing this transformation can be profitable in the register allocator, because it means that the instruction can use a 2-address form if possible, but degrade into a less efficient form if the source and dest register cannot be assigned to the same register. For example, this allows the x86 backend to turn a "shl reg, 3" instruction into an LEA instruction, which is the same speed as the shift but has bigger code size.
If this returns true, then the target must implement the TargetInstrInfo::convertToThreeAddress method for this instruction, which is allowed to fail if the transformation isn't valid for this specific instruction (e.g. shl reg, 4 on x86).
Definition at line 495 of file MCInstrDesc.h.
References llvm::MCID::ConvertibleTo3Addr.
isExtractSubregLike()
bool llvm::MCInstrDesc::isExtractSubregLike () const inline
Return true if this instruction behaves the same way as the generic EXTRACT_SUBREG instructions.
E.g., on ARM, rX, rY VMOVRRD dZ is equivalent to two EXTRACT_SUBREG: rX = EXTRACT_SUBREG dZ, ssub_0 rY = EXTRACT_SUBREG dZ, ssub_1
Note that for the optimizers to be able to take advantage of this property, TargetInstrInfo::getExtractSubregLikeInputs has to be override accordingly.
Definition at line 392 of file MCInstrDesc.h.
References llvm::MCID::ExtractSubreg.
isIndirectBranch()
bool llvm::MCInstrDesc::isIndirectBranch () const inline
Return true if this is an indirect branch, such as a branch through a register.
Definition at line 309 of file MCInstrDesc.h.
References llvm::MCID::IndirectBranch.
Referenced by hasVariantSymbol(), llvm::IsCPSRDead< MCInst >(), and mayAffectControlFlow().
isInsertSubregLike()
bool llvm::MCInstrDesc::isInsertSubregLike () const inline
Return true if this instruction behaves the same way as the generic INSERT_SUBREG instructions.
E.g., on ARM, dX = VSETLNi32 dY, rZ, Imm is equivalent to a INSERT_SUBREG: dX = INSERT_SUBREG dY, rZ, translateImmToSubIdx(Imm)
Note that for the optimizers to be able to take advantage of this property, TargetInstrInfo::getInsertSubregLikeInputs has to be override accordingly.
Definition at line 406 of file MCInstrDesc.h.
References llvm::MCID::InsertSubreg.
isMoveImmediate()
bool llvm::MCInstrDesc::isMoveImmediate () const inline
Return true if this instruction is a move immediate (including conditional moves) instruction.
Definition at line 343 of file MCInstrDesc.h.
References llvm::MCID::MoveImm.
isMoveReg()
bool llvm::MCInstrDesc::isMoveReg () const inline
Return true if the instruction is a register to register move.
Definition at line 283 of file MCInstrDesc.h.
References llvm::MCID::MoveReg.
isNotDuplicable()
bool llvm::MCInstrDesc::isNotDuplicable () const inline
Return true if this instruction cannot be safely duplicated.
For example, if the instruction has a unique labels attached to it, duplicating it would cause multiple definition errors.
Definition at line 354 of file MCInstrDesc.h.
References llvm::MCID::NotDuplicable.
isPredicable()
bool llvm::MCInstrDesc::isPredicable () const inline
Return true if this instruction has a predicate operand that controls execution.
It may be set to 'always', or may be set to other values. There are various methods in TargetInstrInfo that can be used to control and modify the predicate in this instruction.
Definition at line 336 of file MCInstrDesc.h.
References llvm::MCID::Predicable.
Referenced by DecodePredicateOperand(), llvm::MachineInstr::findFirstPredOperandIdx(), llvm::IsCPSRDead< MCInst >(), llvm::HexagonInstrInfo::isPredicable(), llvm::TargetInstrInfo::isPredicable(), isVectorPredicable(), and VerifyLowRegs().
isPreISelOpcode()
bool llvm::MCInstrDesc::isPreISelOpcode () const inline
Returns
true if this instruction is emitted before instruction selection and should be legalized/regbankselected/selected.
Definition at line 257 of file MCInstrDesc.h.
References llvm::MCID::PreISelOpcode.
isPseudo()
bool llvm::MCInstrDesc::isPseudo () const inline
Return true if this is a pseudo instruction that doesn't correspond to a real machine instruction.
Definition at line 271 of file MCInstrDesc.h.
References llvm::MCID::Pseudo.
Referenced by llvm::ResourceManager::canReserveResources(), llvm::PPCInstrInfo::FoldImmediate(), llvm::HexagonMCInstrInfo::isCanon(), makeCombineInst(), and llvm::ResourceManager::reserveResources().
isRegSequenceLike()
bool llvm::MCInstrDesc::isRegSequenceLike () const inline
Return true if this instruction behaves the same way as the generic REG_SEQUENCE instructions.
E.g., on ARM, dX VMOVDRR rY, rZ is equivalent to dX = REG_SEQUENCE rY, ssub_0, rZ, ssub_1.
Note that for the optimizers to be able to take advantage of this property, TargetInstrInfo::getRegSequenceLikeInputs has to be override accordingly.
Definition at line 379 of file MCInstrDesc.h.
References llvm::MCID::RegSequence.
isRematerializable()
bool llvm::MCInstrDesc::isRematerializable () const inline
Returns true if this instruction is a candidate for remat.
This flag is only used in TargetInstrInfo method isTriviallyRematerializable.
If this flag is set, the isReallyTriviallyReMaterializable() or isReallyTriviallyReMaterializableGeneric methods are called to verify the instruction is really rematable.
Definition at line 523 of file MCInstrDesc.h.
References llvm::MCID::Rematerializable.
Referenced by llvm::TargetInstrInfo::isTriviallyReMaterializable().
isReturn()
bool llvm::MCInstrDesc::isReturn () const inline
Return true if the instruction is a return.
Definition at line 274 of file MCInstrDesc.h.
References llvm::MCID::Return.
Referenced by llvm::HexagonShuffler::check(), hasVariantSymbol(), llvm::IsCPSRDead< MCInst >(), mayAffectControlFlow(), llvm::HexagonMCChecker::reportBranchErrors(), llvm::SelectionDAGISel::runOnMachineFunction(), and llvm::mca::verifyOperands().
isSelect()
bool llvm::MCInstrDesc::isSelect () const inline
Return true if this is a select instruction.
Definition at line 349 of file MCInstrDesc.h.
References llvm::MCID::Select.
isTerminator()
bool llvm::MCInstrDesc::isTerminator () const inline
Returns true if this instruction part of the terminator for a basic block.
Typically this is things like return and branch instructions.
Various passes use this to insert code into the bottom of a basic block, but before control flow occurs.
Definition at line 299 of file MCInstrDesc.h.
References llvm::MCID::Terminator.
Referenced by isControlFlow(), llvm::IsCPSRDead< MCInst >(), and llvm::HexagonInstrInfo::isSchedulingBoundary().
isTrap()
bool llvm::MCInstrDesc::isTrap () const inline
Return true if this instruction is a trap.
Definition at line 280 of file MCInstrDesc.h.
References llvm::MCID::Trap.
isUnconditionalBranch()
bool llvm::MCInstrDesc::isUnconditionalBranch () const inline
Return true if this is a branch which always transfers control flow to some other block.
The TargetInstrInfo::AnalyzeBranch method can be used to get more information about this branch.
Definition at line 323 of file MCInstrDesc.h.
References isBranch().
Referenced by hasVariantSymbol().
isVariadic()
bool llvm::MCInstrDesc::isVariadic () const inline
Return true if this instruction can have a variable number of operands.
In this case, the variable operands will be after the normal operands but before the implicit definitions and uses (if any are present).
Definition at line 263 of file MCInstrDesc.h.
References llvm::MCID::Variadic.
Referenced by llvm::MachineInstr::addOperand(), llvm::InstrEmitter::EmitDbgLabel(), llvm::MachineInstr::getNumExplicitDefs(), llvm::MachineInstr::getNumExplicitOperands(), llvm::WebAssemblyInstPrinter::printInst(), tryToFoldACImm(), and llvm::SIInstrInfo::verifyInstruction().
mayAffectControlFlow()
bool MCInstrDesc::mayAffectControlFlow (const MCInst & MI, const MCRegisterInfo & RI) const
Return true if this is a branch or an instruction which directly writes to the program counter.
Considered 'may' affect rather than 'does' affect as things like predication are not taken into account.
Definition at line 32 of file MCInstrDesc.cpp.
References llvm::MCRegisterInfo::getProgramCounter(), hasDefOfPhysReg(), isBranch(), isCall(), isIndirectBranch(), and isReturn().
mayLoad()
bool llvm::MCInstrDesc::mayLoad () const inline
Return true if this instruction could possibly read memory.
Instructions with this flag set are not necessarily simple load instructions, they may load a value and modify it, for example.
Definition at line 436 of file MCInstrDesc.h.
References llvm::MCID::MayLoad.
Referenced by llvm::addFrameReference(), llvm::HexagonShuffler::check(), llvm::HexagonInstrInfo::getNonExtOpcode(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::ARMBaseInstrInfo::getOperandLatency(), getRegNum(), llvm::HexagonInstrInfo::hasNonExtEquivalent(), llvm::HexagonInstrInfo::isComplex(), needsExpandMemInst(), llvm::PPCHazardRecognizer970::PPCHazardRecognizer970(), llvm::HexagonMCChecker::reportBranchErrors(), llvm::SelectionDAGISel::SelectCodeCommon(), and llvm::mca::verifyOperands().
mayRaiseFPException()
bool llvm::MCInstrDesc::mayRaiseFPException () const inline
Return true if this instruction may raise a floating-point exception.
Definition at line 445 of file MCInstrDesc.h.
References llvm::MCID::MayRaiseFPException.
Referenced by isAddWithImmediate(), and llvm::SelectionDAGISel::mayRaiseFPException().
mayStore()
bool llvm::MCInstrDesc::mayStore () const inline
Return true if this instruction could possibly modify memory.
Instructions with this flag set are not necessarily simple store instructions, they may store a modified value based on their operands, or may not actually modify anything, for example.
Definition at line 442 of file MCInstrDesc.h.
References llvm::MCID::MayStore.
Referenced by llvm::addFrameReference(), buildMUBUFOffsetLoadStore(), llvm::HexagonShuffler::check(), llvm::HexagonInstrInfo::getNonExtOpcode(), llvm::ARMBaseInstrInfo::getNumMicroOps(), getPostIncrementOperand(), getRegNum(), llvm::HexagonInstrInfo::hasNonExtEquivalent(), llvm::HexagonInstrInfo::isComplex(), needsExpandMemInst(), llvm::PPCHazardRecognizer970::PPCHazardRecognizer970(), llvm::HexagonMCChecker::reportBranchErrors(), rewritesSort(), llvm::SelectionDAGISel::SelectCodeCommon(), and llvm::mca::verifyOperands().
operands()
iterator_range<const_opInfo_iterator> llvm::MCInstrDesc::operands () const inline
Definition at line 242 of file MCInstrDesc.h.
References llvm::make_range().
Referenced by llvm::RISCVInstrInfo::verifyInstruction().
opInfo_begin()
const_opInfo_iterator llvm::MCInstrDesc::opInfo_begin () const inline
Definition at line 239 of file MCInstrDesc.h.
Referenced by llvm::LegalizerInfo::verify().
opInfo_end()
const_opInfo_iterator llvm::MCInstrDesc::opInfo_end () const inline
Definition at line 240 of file MCInstrDesc.h.
Referenced by llvm::LegalizerInfo::verify().
usesCustomInsertionHook()
bool llvm::MCInstrDesc::usesCustomInsertionHook () const inline
Return true if this instruction requires custom insertion support when the DAG scheduler is inserting it into a machine basic block.
If this is true for the instruction, it basically means that it is a pseudo instruction used at SelectionDAG time that is expanded out into magic code by the target when MachineInstrs are formed.
If this is true, the TargetLoweringInfo::InsertAtEndOfBasicBlock method is used to insert this into the MachineBasicBlock.
Definition at line 507 of file MCInstrDesc.h.
References llvm::MCID::UsesCustomInserter.
variadicOpsAreDefs()
bool llvm::MCInstrDesc::variadicOpsAreDefs () const inline
Return true if variadic operands of this instruction are definitions.
Definition at line 416 of file MCInstrDesc.h.
References llvm::MCID::VariadicOpsAreDefs.
Referenced by hasDefOfPhysReg().
Member Data Documentation
ComplexDeprecationInfo
bool(* llvm::MCInstrDesc::ComplexDeprecationInfo) (MCInst &, const MCSubtargetInfo &, std::string &)
Definition at line 207 of file MCInstrDesc.h.
Referenced by getDeprecatedInfo().
DeprecatedFeature
int64_t llvm::MCInstrDesc::DeprecatedFeature
Definition at line 203 of file MCInstrDesc.h.
Referenced by getDeprecatedInfo().
Flags
uint64_t llvm::MCInstrDesc::Flags
Definition at line 195 of file MCInstrDesc.h.
ImplicitDefs
const MCPhysReg* llvm::MCInstrDesc::ImplicitDefs
Definition at line 198 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::addImplicitDefUseOperands(), CheckForPhysRegDependency(), computeBytesPoppedByCalleeForSRet(), llvm::FastISel::fastEmitInst_f(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrr(), getPhysicalRegisterVT(), hasImplicitDefOfPhysReg(), INITIALIZE_PASS(), isImplicitOperandIn(), and llvm::PPCInstrInfo::optimizeCompareInstr().
ImplicitUses
const MCPhysReg* llvm::MCInstrDesc::ImplicitUses
Definition at line 197 of file MCInstrDesc.h.
Referenced by llvm::MachineInstr::addImplicitDefUseOperands(), getRegNum(), INITIALIZE_PASS(), isImplicitOperandIn(), and llvm::PPCInstrInfo::optimizeCompareInstr().
NumDefs
unsigned char llvm::MCInstrDesc::NumDefs
Definition at line 192 of file MCInstrDesc.h.
Referenced by hasDefOfPhysReg(), and llvm::X86InstrInfo::unfoldMemoryOperand().
NumOperands
unsigned short llvm::MCInstrDesc::NumOperands
Definition at line 191 of file MCInstrDesc.h.
Referenced by AddThumb1SBit(), findFirstVectorPredOperandIdx(), getRealVLDOpcode(), llvm::AMDGPU::getRegOperandSize(), hasDefOfPhysReg(), llvm::SIInstrInfo::isInlineConstant(), isRegOrImmWithInputMods(), llvm::AMDGPU::isSISrcFPOperand(), llvm::AMDGPU::isSISrcInlinableOperand(), llvm::AMDGPU::isSISrcOperand(), isVectorPredicable(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::WebAssemblyMCInstLower::lower(), and llvm::WebAssemblyInstPrinter::printInst().
Opcode
unsigned short llvm::MCInstrDesc::Opcode
Definition at line 190 of file MCInstrDesc.h.
Referenced by llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::MachineInstr::getOpcode(), and llvm::ARMBaseInstrInfo::getOperandLatency().
OpInfo
const MCOperandInfo* llvm::MCInstrDesc::OpInfo
Definition at line 199 of file MCInstrDesc.h.
Referenced by addRegsToSet(), AddThumb1SBit(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::TargetSchedModel::computeOperandLatency(), covertDoubleImmToSingleImm(), llvm::createR600ISelDag(), llvm::X86AsmPrinter::EmitInstruction(), llvm::MachineInstr::findFirstPredOperandIdx(), findFirstVectorPredOperandIdx(), llvm::findFirstVPTPredOperandIdx(), llvm::PPCInstrInfo::FoldImmediate(), llvm::LegalizerInfo::getAction(), llvm::SIInstrInfo::getInstSizeInBytes(), getLit64Encoding(), llvm::AMDGPU::getOperandSize(), llvm::SIInstrInfo::getOpRegClass(), getRealVLDOpcode(), llvm::TargetInstrInfo::getRegClass(), llvm::SIInstrInfo::getRegClass(), getRegNum(), llvm::PPCInstrInfo::getRegNumForOperand(), llvm::AMDGPU::getRegOperandSize(), llvm::MachineInstr::getTypeToPrint(), llvm::SIInstrInfo::isBufferSMRD(), llvm::SIInstrInfo::isImmOperandLegal(), llvm::SIInstrInfo::isInlineConstant(), isInlineConstantIfFolded(), llvm::SIInstrInfo::isOperandLegal(), isRegOrImmWithInputMods(), llvm::AMDGPU::isSISrcFPOperand(), llvm::AMDGPU::isSISrcInlinableOperand(), llvm::AMDGPU::isSISrcOperand(), isVectorPredicable(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::WebAssemblyMCInstLower::lower(), llvm::SIInstrInfo::moveToVALU(), needsExpandMemInst(), needsPCRel(), operator<<(), llvm::HexagonMCInstrInfo::predicateInfo(), llvm::WebAssemblyInstPrinter::printInst(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::AMDGPUInstPrinter::printRegOperand(), llvm::HexagonMCChecker::reportBranchErrors(), rewriteP2Align(), tryAddToFoldList(), tryToFoldACImm(), llvm::SystemZInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), and VerifyLowRegs().
SchedClass
unsigned short llvm::MCInstrDesc::SchedClass
Definition at line 194 of file MCInstrDesc.h.
Size
unsigned char llvm::MCInstrDesc::Size
Definition at line 193 of file MCInstrDesc.h.
TSFlags
uint64_t llvm::MCInstrDesc::TSFlags
Definition at line 196 of file MCInstrDesc.h.
Referenced by llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::X86InstrInfo::commuteInstructionImpl(), commuteVPTERNLOG(), convertTailJumpOpcode(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::createR600MCCodeEmitter(), llvm::createRISCVMCCodeEmitter(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::X86_MC::X86MCInstrAnalysis::evaluateMemoryOperandAddress(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::HexagonMCInstrInfo::getAddrMode(), llvm::HexagonInstrInfo::getAddrMode(), getAddrOffset(), llvm::HexagonInstrInfo::getCExtOpNum(), llvm::SIInstrInfo::getClampMask(), llvm::ARMBaseInstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomain(), llvm::HexagonMCInstrInfo::getExtendableOp(), llvm::HexagonMCInstrInfo::getExtentAlignment(), llvm::HexagonMCInstrInfo::getExtentBits(), llvm::X86InstrInfo::getFMA3OpcodeToCommuteOperands(), getFPReg(), llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), llvm::ARMHazardRecognizer::getHazardType(), getINCDECFromLEA(), getLit64Encoding(), llvm::HexagonInstrInfo::getMaxValue(), llvm::HexagonMCInstrInfo::getMemAccessSize(), llvm::HexagonInstrInfo::getMemAccessSize(), llvm::X86InstrInfo::getMemOperandWithOffset(), llvm::HexagonInstrInfo::getMinValue(), llvm::HexagonMCInstrInfo::getNewValueOp(), llvm::HexagonMCInstrInfo::getNewValueOp2(), llvm::SystemZInstrInfo::getOpcodeForOffset(), getPrefixes(), getRealVLDOpcode(), getRegNum(), getTruncatedShiftCount(), llvm::HexagonInstrInfo::getType(), HasConditionalBranch(), llvm::MipsInstrInfo::HasForbiddenSlot(), llvm::SIInstrInfo::hasFPClamp(), llvm::SIInstrInfo::hasIntClamp(), llvm::X86InstrInfo::hasLockPrefix(), llvm::HexagonMCInstrInfo::hasNewValue(), llvm::HexagonMCInstrInfo::hasNewValue2(), hasRAWHazard(), llvm::HexagonMCInstrInfo::hasTmpDst(), INITIALIZE_PASS(), llvm::HexagonMCInstrInfo::isAccumulator(), llvm::HexagonInstrInfo::isAccumulator(), llvm::HexagonInstrInfo::isAddrModeWithOffset(), isAddWithImmediate(), llvm::HexagonMCInstrInfo::isCofMax1(), llvm::HexagonMCInstrInfo::isCofRelax1(), llvm::HexagonMCInstrInfo::isCofRelax2(), llvm::HexagonInstrInfo::isConstExtended(), llvm::HexagonMCInstrInfo::isCVINew(), llvm::SIInstrInfo::isDisableWQM(), llvm::SIInstrInfo::isDOT(), llvm::SIInstrInfo::isDPP(), llvm::SIInstrInfo::isDS(), isEFLAGSLive(), llvm::SIInstrInfo::isEXP(), llvm::HexagonMCInstrInfo::isExtendable(), llvm::HexagonInstrInfo::isExtendable(), llvm::HexagonMCInstrInfo::isExtended(), llvm::HexagonInstrInfo::isExtended(), llvm::HexagonMCInstrInfo::isExtentSigned(), llvm::SIInstrInfo::isFixedSize(), llvm::SIInstrInfo::isFLAT(), llvm::HexagonMCInstrInfo::isFloat(), llvm::SIInstrInfo::isFPAtomic(), isFpMulInstruction(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), llvm::SIInstrInfo::isGather4(), llvm::SIInstrInfo::isMAI(), isMatchingOrAlias(), llvm::SIInstrInfo::isMIMG(), IsMovrelsSDWAOpcode(), llvm::SIInstrInfo::isMTBUF(), llvm::SIInstrInfo::isMUBUF(), llvm::HexagonMCInstrInfo::isNewValue(), llvm::HexagonInstrInfo::isNewValue(), llvm::HexagonInstrInfo::isNewValueStore(), llvm::HexagonInstrInfo::isOperandExtended(), llvm::SIInstrInfo::isPacked(), isPCRel32Branch(), llvm::ARCInstrInfo::isPostIncrement(), llvm::ARMBaseInstrInfo::isPredicable(), llvm::HexagonInstrInfo::isPredicated(), llvm::HexagonMCInstrInfo::isPredicated(), llvm::HexagonMCInstrInfo::isPredicatedNew(), llvm::HexagonInstrInfo::isPredicatedNew(), llvm::HexagonMCInstrInfo::isPredicatedTrue(), llvm::HexagonInstrInfo::isPredicatedTrue(), llvm::HexagonMCInstrInfo::isPredicateLate(), llvm::ARCInstrInfo::isPreIncrement(), isRegOrImmWithInputMods(), llvm::HexagonMCInstrInfo::isRestrictNoSlot1Store(), llvm::HexagonMCInstrInfo::isRestrictSlot1AOK(), IsRevOpcode(), isRIPRelative(), llvm::SIInstrInfo::isSALU(), llvm::SIInstrInfo::isScalarStore(), llvm::SIInstrInfo::isScalarUnit(), llvm::SIInstrInfo::isSDWA(), llvm::SIInstrInfo::isSegmentSpecificFLAT(), llvm::SIInstrInfo::isSGPRSpill(), isSimpleBD12Move(), isSimpleMove(), llvm::SIInstrInfo::isSMRD(), llvm::HexagonInstrInfo::isSolo(), llvm::HexagonMCInstrInfo::isSoloAX(), llvm::SIInstrInfo::isSOP1(), llvm::SIInstrInfo::isSOP2(), llvm::SIInstrInfo::isSOPC(), llvm::SIInstrInfo::isSOPK(), llvm::SIInstrInfo::isSOPP(), llvm::SIInstrInfo::isVALU(), llvm::SIInstrInfo::isVGPRSpill(), llvm::SIInstrInfo::isVINTRP(), llvm::SIInstrInfo::isVOP1(), llvm::SIInstrInfo::isVOP2(), llvm::SIInstrInfo::isVOP3(), llvm::SIInstrInfo::isVOP3P(), llvm::SIInstrInfo::isVOPC(), llvm::SIInstrInfo::isWQM(), llvm::HexagonInstrInfo::mayBeCurLoad(), llvm::HexagonInstrInfo::mayBeNewStore(), performCustomAdjustments(), llvm::PPCHazardRecognizer970::PPCHazardRecognizer970(), llvm::HexagonMCInstrInfo::prefersSlot3(), llvm::AMDGPUInstPrinter::printInst(), llvm::X86InstPrinterCommon::printInstFlags(), printMasking(), llvm::AMDGPUInstPrinter::printRegOperand(), llvm::X86ATTInstPrinter::printVecCompareInstr(), llvm::X86IntelInstPrinter::printVecCompareInstr(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), llvm::MipsInstrInfo::SafeInForbiddenSlot(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::SIInstrInfo::sopkIsZext(), updateOperand(), usedAsAddr(), llvm::SIInstrInfo::usesFPDPRounding(), llvm::SIInstrInfo::usesLGKM_CNT(), llvm::SIInstrInfo::usesVM_CNT(), and VisitGlobalVariableForEmission().
The documentation for this class was generated from the following files:
include/llvm/MC/MCInstrDesc.h
lib/MC/MCInstrDesc.cpp