LLVM: llvm::codeview::GlobalTypeTableBuilder Class Reference
llvm::codeview::GlobalTypeTableBuilder Class Reference
#include "llvm/DebugInfo/CodeView/GlobalTypeTableBuilder.h"
Public Member Functions
GlobalTypeTableBuilder (BumpPtrAllocator &Storage)
~GlobalTypeTableBuilder ()
Optional< TypeIndex > getFirst () override
Optional< TypeIndex > getNext (TypeIndex Prev) override
CVType getType (TypeIndex Index) override
StringRef getTypeName (TypeIndex Index) override
bool contains (TypeIndex Index) override
uint32_t size () override
uint32_t capacity () override
void reset ()
TypeIndex nextTypeIndex () const
BumpPtrAllocator & getAllocator ()
ArrayRef< ArrayRef< uint8_t > > records () const
ArrayRef< GloballyHashedType > hashes () const
template<typename CreateFunc >
TypeIndex insertRecordAs (GloballyHashedType Hash, size_t RecordSize, CreateFunc Create)
TypeIndex insertRecordBytes (ArrayRef< uint8_t > Data)
TypeIndex insertRecord (ContinuationRecordBuilder &Builder)
template<typename T >
TypeIndex writeLeafType (T &Record)
Public Member Functions inherited from llvm::codeview::TypeCollection
virtual ~TypeCollection ()=default
bool empty ()
template<typename TFunc >
void ForEachRecord (TFunc Func)
Detailed Description
Definition at line 31 of file GlobalTypeTableBuilder.h.
Constructor & Destructor Documentation
GlobalTypeTableBuilder()
GlobalTypeTableBuilder::GlobalTypeTableBuilder (BumpPtrAllocator & Storage) explicit
Definition at line 34 of file GlobalTypeTableBuilder.cpp.
References ~GlobalTypeTableBuilder().
~GlobalTypeTableBuilder()
GlobalTypeTableBuilder::~GlobalTypeTableBuilder () default
Referenced by GlobalTypeTableBuilder().
Member Function Documentation
capacity()
uint32_t GlobalTypeTableBuilder::capacity () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 72 of file GlobalTypeTableBuilder.cpp.
contains()
bool GlobalTypeTableBuilder::contains (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 63 of file GlobalTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::isNoneType(), llvm::codeview::TypeIndex::isSimple(), and llvm::codeview::TypeIndex::toArrayIndex().
getAllocator()
BumpPtrAllocator& llvm::codeview::GlobalTypeTableBuilder::getAllocator () inline
Definition at line 66 of file GlobalTypeTableBuilder.h.
References hashes(), and records().
getFirst()
Optional< TypeIndex > GlobalTypeTableBuilder::getFirst () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 41 of file GlobalTypeTableBuilder.cpp.
References llvm::codeview::TypeCollection::empty(), llvm::codeview::TypeIndex::FirstNonSimpleIndex, and llvm::codeview::None.
getNext()
Optional< TypeIndex > GlobalTypeTableBuilder::getNext (TypeIndex Prev) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 48 of file GlobalTypeTableBuilder.cpp.
References nextTypeIndex(), and llvm::codeview::None.
getType()
CVType GlobalTypeTableBuilder::getType (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 54 of file GlobalTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::toArrayIndex().
getTypeName()
StringRef GlobalTypeTableBuilder::getTypeName (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 59 of file GlobalTypeTableBuilder.cpp.
References llvm_unreachable.
hashes()
ArrayRef< GloballyHashedType > GlobalTypeTableBuilder::hashes () const
Definition at line 78 of file GlobalTypeTableBuilder.cpp.
Referenced by getAllocator().
insertRecord()
TypeIndex GlobalTypeTableBuilder::insertRecord (ContinuationRecordBuilder & Builder)
Definition at line 99 of file GlobalTypeTableBuilder.cpp.
References assert(), llvm::codeview::C, llvm::codeview::ContinuationRecordBuilder::end(), insertRecordBytes(), and nextTypeIndex().
Referenced by insertRecordAs().
insertRecordAs()
template<typename CreateFunc > TypeIndex llvm::codeview::GlobalTypeTableBuilder::insertRecordAs (GloballyHashedType Hash, size_t RecordSize, CreateFunc Create) inline
Definition at line 72 of file GlobalTypeTableBuilder.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::Data, llvm::ArrayRef< T >::empty(), insertRecord(), insertRecordBytes(), LLVM_UNLIKELY, nextTypeIndex(), llvm::codeview::NotTranslated, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by insertRecordBytes().
insertRecordBytes()
TypeIndex GlobalTypeTableBuilder::insertRecordBytes (ArrayRef< uint8_t > Data)
Definition at line 87 of file GlobalTypeTableBuilder.cpp.
References assert(), llvm::Data, llvm::ArrayRef< T >::data(), llvm::codeview::GloballyHashedType::hashType(), insertRecordAs(), and llvm::ArrayRef< T >::size().
Referenced by insertRecord(), insertRecordAs(), and writeLeafType().
nextTypeIndex()
TypeIndex GlobalTypeTableBuilder::nextTypeIndex () const
Definition at line 30 of file GlobalTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::fromArrayIndex().
Referenced by getNext(), insertRecord(), and insertRecordAs().
records()
ArrayRef< ArrayRef< uint8_t > > GlobalTypeTableBuilder::records () const
Definition at line 74 of file GlobalTypeTableBuilder.cpp.
Referenced by getAllocator().
reset()
void GlobalTypeTableBuilder::reset ()
Definition at line 82 of file GlobalTypeTableBuilder.cpp.
size()
uint32_t GlobalTypeTableBuilder::size () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 70 of file GlobalTypeTableBuilder.cpp.
writeLeafType()
template<typename T > TypeIndex llvm::codeview::GlobalTypeTableBuilder::writeLeafType (T & Record) inline
Definition at line 106 of file GlobalTypeTableBuilder.h.
References insertRecordBytes(), and llvm::codeview::SimpleTypeSerializer::serialize().
Referenced by getStringIdTypeIdx().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/GlobalTypeTableBuilder.h
lib/DebugInfo/CodeView/GlobalTypeTableBuilder.cpp