LLVM: llvm::object::MinidumpFile::MemoryInfoIterator Class Reference
llvm::object::MinidumpFile::MemoryInfoIterator Class Reference
#include "llvm/Object/Minidump.h"
Public Member Functions
MemoryInfoIterator (ArrayRef< uint8_t > Storage, size_t Stride)
bool operator== (const MemoryInfoIterator &R) const
const minidump::MemoryInfo & operator* () const
MemoryInfoIterator & operator++ ()
Public Member Functions inherited from llvm::iterator_facade_base< MemoryInfoIterator, std::forward_iterator_tag, minidump::MemoryInfo >
MemoryInfoIterator operator+ (std::ptrdiff_t n) const
MemoryInfoIterator operator- (std::ptrdiff_t n) const
MemoryInfoIterator & operator++ ()
MemoryInfoIterator operator++ (int)
MemoryInfoIterator & operator-- ()
MemoryInfoIterator operator-- (int)
bool operator!= (const MemoryInfoIterator &RHS) const
bool operator> (const MemoryInfoIterator &RHS) const
bool operator<= (const MemoryInfoIterator &RHS) const
bool operator>= (const MemoryInfoIterator &RHS) const
minidump::MemoryInfo * operator-> ()
minidump::MemoryInfo * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< MemoryInfoIterator, std::forward_iterator_tag, minidump::MemoryInfo >
enum
Detailed Description
Definition at line 105 of file Minidump.h.
Constructor & Destructor Documentation
MemoryInfoIterator()
llvm::object::MinidumpFile::MemoryInfoIterator::MemoryInfoIterator (ArrayRef< uint8_t > Storage, size_t Stride) inline
Definition at line 110 of file Minidump.h.
References assert(), and llvm::ArrayRef< T >::size().
Member Function Documentation
operator*()
const minidump::MemoryInfo& llvm::object::MinidumpFile::MemoryInfoIterator::operator* () const inline
Definition at line 119 of file Minidump.h.
References assert(), llvm::ArrayRef< T >::data(), and llvm::ArrayRef< T >::size().
operator++()
MemoryInfoIterator& llvm::object::MinidumpFile::MemoryInfoIterator::operator++ () inline
Definition at line 124 of file Minidump.h.
References llvm::arrayRefFromStringRef(), llvm::object::Binary::Binary(), llvm::object::Binary::Data, llvm::ArrayRef< T >::drop_front(), llvm::object::MinidumpFile::getMemoryInfoList(), llvm::object::MinidumpFile::getRawStream(), llvm::object::Binary::ID_Minidump, llvm::max(), llvm::object::parse_failed, Size, llvm::T, llvm::Expected< T >::takeError(), and llvm::object::unexpected_eof.
operator==()
bool llvm::object::MinidumpFile::MemoryInfoIterator::operator== (const MemoryInfoIterator & R) const inline
Definition at line 115 of file Minidump.h.
References llvm::ArrayRef< T >::size().
The documentation for this class was generated from the following file:
include/llvm/Object/Minidump.h