LLVM: llvm::codeview::DebugSymbolRVASubsection Class Reference
llvm::codeview::DebugSymbolRVASubsection Class Reference final
#include "llvm/DebugInfo/CodeView/DebugSymbolRVASubsection.h"
Public Member Functions
DebugSymbolRVASubsection ()
Error commit (BinaryStreamWriter &Writer) const override
uint32_t calculateSerializedSize () const override
void addRVA (uint32_t RVA)
Public Member Functions inherited from llvm::codeview::DebugSubsection
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsection
static bool classof (const DebugSubsection *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsection
DebugSubsectionKind Kind
Detailed Description
Definition at line 45 of file DebugSymbolRVASubsection.h.
Constructor & Destructor Documentation
DebugSymbolRVASubsection()
DebugSymbolRVASubsection::DebugSymbolRVASubsection ()
Definition at line 26 of file DebugSymbolRVASubsection.cpp.
Member Function Documentation
addRVA()
void llvm::codeview::DebugSymbolRVASubsection::addRVA (uint32_t RVA) inline
Definition at line 56 of file DebugSymbolRVASubsection.h.
calculateSerializedSize()
uint32_t DebugSymbolRVASubsection::calculateSerializedSize () const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 33 of file DebugSymbolRVASubsection.cpp.
classof()
static bool llvm::codeview::DebugSymbolRVASubsection::classof (const DebugSubsection * S) inline static
Definition at line 49 of file DebugSymbolRVASubsection.h.
References llvm::codeview::CoffSymbolRVA, and llvm::codeview::DebugSubsection::kind().
commit()
Error DebugSymbolRVASubsection::commit (BinaryStreamWriter & Writer) const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 29 of file DebugSymbolRVASubsection.cpp.
References llvm::makeArrayRef(), and llvm::BinaryStreamWriter::writeArray().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSymbolRVASubsection.h
lib/DebugInfo/CodeView/DebugSymbolRVASubsection.cpp