LLVM: llvm::MCDwarfFrameEmitter Class Reference
llvm::MCDwarfFrameEmitter Class Reference
#include "llvm/MC/MCDwarf.h"
Static Public Member Functions
static void Emit (MCObjectStreamer &streamer, MCAsmBackend *MAB, bool isEH)
static void EmitAdvanceLoc (MCObjectStreamer &Streamer, uint64_t AddrDelta)
static void EncodeAdvanceLoc (MCContext &Context, uint64_t AddrDelta, raw_ostream &OS, uint32_t *Offset=nullptr, uint32_t *Size=nullptr)
Detailed Description
Definition at line 624 of file MCDwarf.h.
Member Function Documentation
Emit()
void MCDwarfFrameEmitter::Emit (MCObjectStreamer & streamer, MCAsmBackend * MAB, bool isEH) static
Definition at line 1822 of file MCDwarf.cpp.
References llvm::ArrayRef< T >::begin(), llvm::MCDwarfFrameInfo::CompactUnwindEncoding, Context, llvm::MCContext::createTempSymbol(), E, llvm::MCObjectStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitValueToAlignment(), llvm::ArrayRef< T >::end(), llvm::MCStreamer::generateCompactUnwindEncodings(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCObjectFileInfo::getCompactUnwindDwarfEHFrameOnly(), llvm::MCObjectFileInfo::getCompactUnwindSection(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getDwarfFrameInfos(), llvm::MCObjectFileInfo::getDwarfFrameSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getOmitDwarfIfHaveCompactUnwind(), llvm::MCObjectFileInfo::getSupportsCompactUnwindWithoutEHFrame(), I, llvm::ARMBuildAttrs::Section, llvm::stable_sort(), llvm::MCStreamer::SwitchSection(), X, and Y.
Referenced by llvm::MCObjectStreamer::EmitFrames().
EmitAdvanceLoc()
void MCDwarfFrameEmitter::EmitAdvanceLoc (MCObjectStreamer & Streamer, uint64_t AddrDelta) static
Definition at line 1891 of file MCDwarf.cpp.
References Context, llvm::MCObjectStreamer::EmitBytes(), EncodeAdvanceLoc(), llvm::MCStreamer::getContext(), and llvm::raw_svector_ostream::str().
Referenced by llvm::MCObjectStreamer::EmitDwarfAdvanceFrameAddr().
EncodeAdvanceLoc()
void MCDwarfFrameEmitter::EncodeAdvanceLoc (MCContext & Context, uint64_t AddrDelta, raw_ostream & OS, uint32_t * Offset = nullptr, uint32_t * Size = nullptr) static
Definition at line 1900 of file MCDwarf.cpp.
References assert(), llvm::support::big, E, llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::isLittleEndian(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::isUInt< 8 >(), llvm::isUIntN(), llvm::support::little, ScaleAddrDelta(), llvm::raw_ostream::tell(), and llvm::raw_ostream::write_zeros().
Referenced by EmitAdvanceLoc(), and needPadding().
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp