LLVM: llvm::SIScheduleBlockScheduler Class Reference
llvm::SIScheduleBlockScheduler Class Reference
#include "Target/AMDGPU/SIMachineScheduler.h"
Public Member Functions
SIScheduleBlockScheduler (SIScheduleDAGMI *DAG, SISchedulerBlockSchedulerVariant Variant, SIScheduleBlocks BlocksStruct)
~SIScheduleBlockScheduler ()=default
std::vector< SIScheduleBlock * > getBlocks ()
unsigned getVGPRUsage ()
unsigned getSGPRUsage ()
Detailed Description
Definition at line 321 of file SIMachineScheduler.h.
Constructor & Destructor Documentation
SIScheduleBlockScheduler()
SIScheduleBlockScheduler::SIScheduleBlockScheduler (SIScheduleDAGMI * DAG, SISchedulerBlockSchedulerVariant Variant, SIScheduleBlocks BlocksStruct)
Definition at line 1440 of file SIMachineScheduler.cpp.
References assert(), llvm::BlockLatencyRegUsage, llvm::BlockRegUsage, llvm::Data, llvm::dbgs(), llvm::Depth, llvm::numbers::e, E, llvm::SIScheduleDAGMI::fillVgprSgprCost(), llvm::SIScheduleBlock::getID(), llvm::SIScheduleBlock::getInRegs(), llvm::SIScheduleDAGMI::getInRegs(), llvm::SIScheduleDAGMI::getMRI(), llvm::TargetRegisterInfo::getNumRegPressureSets(), llvm::SIScheduleBlock::getOutRegs(), llvm::SIScheduleDAGMI::getOutRegs(), llvm::SIScheduleBlock::getPreds(), llvm::MachineRegisterInfo::getPressureSets(), getReasonStr(), llvm::SIScheduleBlock::getSuccs(), llvm::SIScheduleDAGMI::getTRI(), llvm::SIScheduleDAGMI::getVGPRSetID(), llvm::PSetIterator::getWeight(), I, llvm::SIScheduleBlock::isHighLatencyBlock(), llvm::PSetIterator::isValid(), llvm::Register::isVirtualRegister(), llvm::Latency, LLVM_DEBUG, llvm::NoCand, llvm::NodeOrder, llvm::printVRegOrUnit(), Reg, llvm::RegUsage, llvm::Successor, llvm::SIScheduleBlocks::TopDownBlock2Index, llvm::SIScheduleBlocks::TopDownIndex2Block, llvm::SISched::tryGreater(), and llvm::SISched::tryLess().
~SIScheduleBlockScheduler()
llvm::SIScheduleBlockScheduler::~SIScheduleBlockScheduler () default
Member Function Documentation
getBlocks()
std::vector<SIScheduleBlock*> llvm::SIScheduleBlockScheduler::getBlocks () inline
Definition at line 354 of file SIMachineScheduler.h.
Referenced by llvm::SIScheduler::scheduleVariant().
getSGPRUsage()
unsigned llvm::SIScheduleBlockScheduler::getSGPRUsage () inline
Definition at line 357 of file SIMachineScheduler.h.
References assert(), llvm::NoCand, and llvm::SISchedulerCandidate::Reason.
Referenced by llvm::SIScheduler::scheduleVariant().
getVGPRUsage()
unsigned llvm::SIScheduleBlockScheduler::getVGPRUsage () inline
Definition at line 356 of file SIMachineScheduler.h.
Referenced by llvm::SIScheduler::scheduleVariant().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIMachineScheduler.h
lib/Target/AMDGPU/SIMachineScheduler.cpp