LLVM: llvm::codeview::DebugSymbolsSubsectionRef Class Reference
llvm::codeview::DebugSymbolsSubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugSymbolsSubsection.h"
Public Member Functions
DebugSymbolsSubsectionRef ()
Error initialize (BinaryStreamReader Reader)
CVSymbolArray::Iterator begin () const
CVSymbolArray::Iterator end () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 18 of file DebugSymbolsSubsection.h.
Constructor & Destructor Documentation
DebugSymbolsSubsectionRef()
llvm::codeview::DebugSymbolsSubsectionRef::DebugSymbolsSubsectionRef () inline
Definition at line 20 of file DebugSymbolsSubsection.h.
Member Function Documentation
begin()
CVSymbolArray::Iterator llvm::codeview::DebugSymbolsSubsectionRef::begin () const inline
Definition at line 29 of file DebugSymbolsSubsection.h.
References llvm::VarStreamArray< ValueType, Extractor >::begin().
classof()
static bool llvm::codeview::DebugSymbolsSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 23 of file DebugSymbolsSubsection.h.
References initialize(), llvm::codeview::DebugSubsectionRef::kind(), and llvm::codeview::Symbols.
end()
CVSymbolArray::Iterator llvm::codeview::DebugSymbolsSubsectionRef::end () const inline
Definition at line 30 of file DebugSymbolsSubsection.h.
References llvm::VarStreamArray< ValueType, Extractor >::end().
initialize()
Error DebugSymbolsSubsectionRef::initialize (BinaryStreamReader Reader)
Definition at line 14 of file DebugSymbolsSubsection.cpp.
References llvm::BinaryStreamReader::getLength(), and llvm::BinaryStreamReader::readArray().
Referenced by classof(), and llvm::codeview::visitDebugSubsection().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSymbolsSubsection.h
lib/DebugInfo/CodeView/DebugSymbolsSubsection.cpp