LLVM: llvm::mca::InstructionTables Class Reference
llvm::mca::InstructionTables Class Reference final
#include "llvm/MCA/Stages/InstructionTables.h"
Public Member Functions
InstructionTables (const MCSchedModel &Model)
bool hasWorkToComplete () const override
Returns true if some instructions are still executing this stage.
Error execute (InstRef &IR) override
The primary action that this stage performs on instruction IR.
Public Member Functions inherited from llvm::mca::Stage
Stage ()
virtual ~Stage ()
virtual bool isAvailable (const InstRef &IR) const
Returns true if it can execute IR during this cycle.
virtual Error cycleStart ()
Called once at the start of each cycle.
virtual Error cycleEnd ()
Called once at the end of each cycle.
void setNextInSequence (Stage *NextStage)
bool checkNextStage (const InstRef &IR) const
Error moveToTheNextStage (InstRef &IR)
Called when an instruction is ready to move the next pipeline stage.
void addListener (HWEventListener *Listener)
Add a listener to receive callbacks during the execution of this stage.
template<typename EventT >
void notifyEvent (const EventT &Event) const
Notify listeners of a particular hardware event.
Additional Inherited Members
Protected Member Functions inherited from llvm::mca::Stage
const std::set< HWEventListener * > & getListeners () const
Detailed Description
Definition at line 28 of file InstructionTables.h.
Constructor & Destructor Documentation
InstructionTables()
llvm::mca::InstructionTables::InstructionTables (const MCSchedModel & Model) inline
Definition at line 34 of file InstructionTables.h.
References llvm::mca::computeProcResourceMasks().
Member Function Documentation
execute()
Error llvm::mca::InstructionTables::execute (InstRef & IR) override virtual
The primary action that this stage performs on instruction IR.
Implements llvm::mca::Stage.
Definition at line 22 of file InstructionTables.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::find(), llvm::mca::InstructionBase::getDesc(), llvm::mca::InstRef::getInstruction(), llvm::MCSchedModel::getProcResource(), I, llvm::MCProcResourceDesc::NumUnits, llvm::mca::InstrDesc::Resources, and llvm::MCProcResourceDesc::SubUnitsIdxBegin.
Referenced by hasWorkToComplete().
hasWorkToComplete()
bool llvm::mca::InstructionTables::hasWorkToComplete () const inline override virtual
Returns true if some instructions are still executing this stage.
Implements llvm::mca::Stage.
Definition at line 39 of file InstructionTables.h.
References execute(), and IR.
The documentation for this class was generated from the following files:
include/llvm/MCA/Stages/InstructionTables.h
lib/MCA/Stages/InstructionTables.cpp