LLVM: llvm::sys::fs::directory_iterator Class Reference
llvm::sys::fs::directory_iterator Class Reference
directory_iterator - Iterates through the entries in path.
#include "llvm/Support/FileSystem.h"
Public Member Functions
directory_iterator (const Twine &path, std::error_code &ec, bool follow_symlinks=true)
directory_iterator (const directory_entry &de, std::error_code &ec, bool follow_symlinks=true)
directory_iterator ()=default
Construct end iterator.
directory_iterator & increment (std::error_code &ec)
const directory_entry & operator* () const
const directory_entry * operator-> () const
bool operator== (const directory_iterator &RHS) const
bool operator!= (const directory_iterator &RHS) const
Detailed Description
directory_iterator - Iterates through the entries in path.
There is no operator++ because we need an error_code. If it's really needed we can make it call report_fatal_error on error.
Definition at line 1280 of file FileSystem.h.
Constructor & Destructor Documentation
directory_iterator() [1/3]
llvm::sys::fs::directory_iterator::directory_iterator (const Twine & path, std::error_code & ec, bool follow_symlinks = true) inline explicit
Definition at line 1285 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_construct(), and llvm::Twine::toStringRef().
directory_iterator() [2/3]
llvm::sys::fs::directory_iterator::directory_iterator (const directory_entry & de, std::error_code & ec, bool follow_symlinks = true) inline explicit
Definition at line 1294 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_construct(), and llvm::sys::fs::directory_entry::path().
directory_iterator() [3/3]
llvm::sys::fs::directory_iterator::directory_iterator () default
Construct end iterator.
Member Function Documentation
increment()
directory_iterator& llvm::sys::fs::directory_iterator::increment (std::error_code & ec) inline
Definition at line 1306 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_increment().
operator!=()
bool llvm::sys::fs::directory_iterator::operator!= (const directory_iterator & RHS) const inline
Definition at line 1324 of file FileSystem.h.
operator*()
const directory_entry& llvm::sys::fs::directory_iterator::operator* () const inline
Definition at line 1311 of file FileSystem.h.
operator->()
const directory_entry* llvm::sys::fs::directory_iterator::operator-> () const inline
Definition at line 1312 of file FileSystem.h.
operator==()
bool llvm::sys::fs::directory_iterator::operator== (const directory_iterator & RHS) const inline
Definition at line 1314 of file FileSystem.h.
The documentation for this class was generated from the following file:
include/llvm/Support/FileSystem.h