LLVM: llvm::MMIAddrLabelMap Class Reference
llvm::MMIAddrLabelMap Class Reference
Public Member Functions
MMIAddrLabelMap (MCContext &context)
~MMIAddrLabelMap ()
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (BasicBlock *BB)
void takeDeletedSymbolsForFunction (Function *F, std::vector< MCSymbol *> &Result)
If we have any deleted symbols for F, return them.
void UpdateForDeletedBlock (BasicBlock *BB)
void UpdateForRAUWBlock (BasicBlock *Old, BasicBlock *New)
Detailed Description
Definition at line 63 of file MachineModuleInfo.cpp.
Constructor & Destructor Documentation
MMIAddrLabelMap()
llvm::MMIAddrLabelMap::MMIAddrLabelMap (MCContext & context) inline
Definition at line 86 of file MachineModuleInfo.cpp.
~MMIAddrLabelMap()
llvm::MMIAddrLabelMap::~MMIAddrLabelMap () inline
Definition at line 88 of file MachineModuleInfo.cpp.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty(), and F().
Member Function Documentation
getAddrLabelSymbolToEmit()
ArrayRef< MCSymbol * > MMIAddrLabelMap::getAddrLabelSymbolToEmit (BasicBlock * BB)
Definition at line 104 of file MachineModuleInfo.cpp.
References assert(), Context, llvm::BasicBlock::getParent(), llvm::BasicBlock::hasAddressTaken(), and takeDeletedSymbolsForFunction().
Referenced by llvm::MachineModuleInfo::getAddrLabelSymbolToEmit().
takeDeletedSymbolsForFunction()
void MMIAddrLabelMap::takeDeletedSymbolsForFunction (Function * F, std::vector< MCSymbol *> & Result)
If we have any deleted symbols for F, return them.
Definition at line 137 of file MachineModuleInfo.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), I, and std::swap().
Referenced by getAddrLabelSymbolToEmit().
UpdateForDeletedBlock()
void MMIAddrLabelMap::UpdateForDeletedBlock (BasicBlock * BB)
Definition at line 149 of file MachineModuleInfo.cpp.
References assert(), and llvm::MCSymbol::isDefined().
UpdateForRAUWBlock()
void MMIAddrLabelMap::UpdateForRAUWBlock (BasicBlock * Old, BasicBlock * New)
Definition at line 173 of file MachineModuleInfo.cpp.
References assert().
The documentation for this class was generated from the following file:
lib/CodeGen/MachineModuleInfo.cpp