LLVM: llvm::LanaiMachineFunctionInfo Class Reference
llvm::LanaiMachineFunctionInfo Class Reference
#include "Target/Lanai/LanaiMachineFunctionInfo.h"
Public Member Functions
LanaiMachineFunctionInfo (MachineFunction &MF)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
unsigned getGlobalBaseReg ()
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 24 of file LanaiMachineFunctionInfo.h.
Constructor & Destructor Documentation
LanaiMachineFunctionInfo()
llvm::LanaiMachineFunctionInfo::LanaiMachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 43 of file LanaiMachineFunctionInfo.h.
Member Function Documentation
getGlobalBaseReg()
unsigned LanaiMachineFunctionInfo::getGlobalBaseReg ()
Definition at line 15 of file LanaiMachineFunctionInfo.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), and llvm::MachineFunction::getRegInfo().
Referenced by setSRetReturnReg().
getSRetReturnReg()
unsigned llvm::LanaiMachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 46 of file LanaiMachineFunctionInfo.h.
Referenced by CC_Lanai32_VarArg().
getVarArgsFrameIndex()
int llvm::LanaiMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 51 of file LanaiMachineFunctionInfo.h.
Referenced by llvm::LanaiTargetLowering::LowerVASTART().
setSRetReturnReg()
void llvm::LanaiMachineFunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 47 of file LanaiMachineFunctionInfo.h.
References getGlobalBaseReg(), and Reg.
Referenced by CC_Lanai32_VarArg().
setVarArgsFrameIndex()
void llvm::LanaiMachineFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 52 of file LanaiMachineFunctionInfo.h.
Referenced by CC_Lanai32_VarArg().
The documentation for this class was generated from the following files:
lib/Target/Lanai/LanaiMachineFunctionInfo.h
lib/Target/Lanai/LanaiMachineFunctionInfo.cpp