LLVM: llvm::LinkingSymbolResolver Class Reference
llvm::LinkingSymbolResolver Class Reference
#include "ExecutionEngine/MCJIT/MCJIT.h"
Public Member Functions
LinkingSymbolResolver (MCJIT &Parent, std::shared_ptr< LegacyJITSymbolResolver > Resolver)
JITSymbol findSymbol (const std::string &Name) override
This method returns the address of the specified function or variable.
JITSymbol findSymbolInLogicalDylib (const std::string &Name) override
This method returns the address of the specified symbol if it exists within the logical dynamic library represented by this JITSymbolResolver.
Public Member Functions inherited from llvm::LegacyJITSymbolResolver
void lookup (const LookupSet &Symbols, OnResolvedFunction OnResolved) final
Performs lookup by, for each symbol, first calling findSymbolInLogicalDylib and if that fails calling findSymbol.
Expected< LookupSet > getResponsibilitySet (const LookupSet &Symbols) final
Performs flags lookup by calling findSymbolInLogicalDylib and returning the flags value for that symbol.
Public Member Functions inherited from llvm::JITSymbolResolver
virtual ~JITSymbolResolver ()=default
Additional Inherited Members
Public Types inherited from llvm::JITSymbolResolver
using LookupSet = std::set< StringRef >
using LookupResult = std::map< StringRef, JITEvaluatedSymbol >
using OnResolvedFunction = unique_function< void(Expected< LookupResult >)>
Detailed Description
Definition at line 28 of file MCJIT.h.
Constructor & Destructor Documentation
LinkingSymbolResolver()
llvm::LinkingSymbolResolver::LinkingSymbolResolver (MCJIT & Parent, std::shared_ptr< LegacyJITSymbolResolver > Resolver) inline
Definition at line 30 of file MCJIT.h.
References findSymbol(), and Name.
Member Function Documentation
findSymbol()
JITSymbol LinkingSymbolResolver::findSymbol (const std::string & Name) override virtual
This method returns the address of the specified function or variable.
It is used to resolve symbols during module linking.
If the returned symbol's address is equal to ~0ULL then RuntimeDyld will skip all relocations for that symbol, and the client will be responsible for handling them manually.
Implements llvm::LegacyJITSymbolResolver.
Definition at line 670 of file MCJIT.cpp.
Referenced by LinkingSymbolResolver(), and llvm::MCJIT::Register().
findSymbolInLogicalDylib()
JITSymbol llvm::LinkingSymbolResolver::findSymbolInLogicalDylib (const std::string & Name) inline override virtual
This method returns the address of the specified symbol if it exists within the logical dynamic library represented by this JITSymbolResolver.
Unlike findSymbol, queries through this interface should return addresses for hidden symbols.
This is of particular importance for the Orc JIT APIs, which support lazy compilation by breaking up modules: Each of those broken out modules must be able to resolve hidden symbols provided by the others. Clients writing memory managers for MCJIT can usually ignore this method.
This method will be queried by RuntimeDyld when checking for previous definitions of common symbols.
Implements llvm::LegacyJITSymbolResolver.
Definition at line 37 of file MCJIT.h.
The documentation for this class was generated from the following files:
lib/ExecutionEngine/MCJIT/MCJIT.h
lib/ExecutionEngine/MCJIT/MCJIT.cpp