LLVM: llvm::FoldingSetBase::Node Class Reference
llvm::FoldingSetBase::Node Class Reference
Node - This class is used to maintain the singly linked bucket list in a folding set.
#include "llvm/ADT/FoldingSet.h"
Public Member Functions
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Detailed Description
Node - This class is used to maintain the singly linked bucket list in a folding set.
Definition at line 135 of file FoldingSet.h.
Constructor & Destructor Documentation
Node()
llvm::FoldingSetBase::Node::Node () default
Referenced by llvm::SDDbgInfo::add(), llvm::SelectionDAG::addHeapAllocSite(), llvm::SDNode::areOnlyUsersOf(), and llvm::SelectionDAG::isConstantFPBuildVectorOrConstantFP().
Member Function Documentation
getNextInBucket()
void* llvm::FoldingSetBase::Node::getNextInBucket () const inline
Definition at line 144 of file FoldingSet.h.
Referenced by llvm::FoldingSetBucketIteratorImpl::advance(), llvm::FoldingSetBase::InsertNode(), and llvm::FoldingSetBase::RemoveNode().
SetNextInBucket()
void llvm::FoldingSetBase::Node::SetNextInBucket (void * N) inline
Definition at line 145 of file FoldingSet.h.
References llvm::FoldingSetBase::clear(), and N.
Referenced by llvm::FoldingSetBase::InsertNode(), and llvm::FoldingSetBase::RemoveNode().
The documentation for this class was generated from the following file:
include/llvm/ADT/FoldingSet.h