LLVM: llvm::TimeRegion Class Reference
llvm::TimeRegion Class Reference
The TimeRegion class is used as a helper class to call the startTimer() and stopTimer() methods of the Timer class.
#include "llvm/Support/Timer.h"
Public Member Functions
TimeRegion (Timer &t)
TimeRegion (Timer *t)
~TimeRegion ()
Detailed Description
The TimeRegion class is used as a helper class to call the startTimer() and stopTimer() methods of the Timer class.
When the object is constructed, it starts the timer specified as its argument. When it is destroyed, it stops the relevant timer. This makes it easy to time a region of code.
Definition at line 140 of file Timer.h.
Constructor & Destructor Documentation
TimeRegion() [1/2]
llvm::TimeRegion::TimeRegion (Timer & t) inline explicit
Definition at line 145 of file Timer.h.
References llvm::Timer::startTimer().
TimeRegion() [2/2]
llvm::TimeRegion::TimeRegion (Timer * t) inline explicit
Definition at line 148 of file Timer.h.
References llvm::Timer::startTimer().
~TimeRegion()
llvm::TimeRegion::~TimeRegion () inline
Definition at line 151 of file Timer.h.
References llvm::Timer::stopTimer().
The documentation for this class was generated from the following file:
include/llvm/Support/Timer.h