LLVM: llvm::DeclContextTree Class Reference
llvm::DeclContextTree Class Reference
This class gives a tree-like API to the DenseMap that stores the DeclContext objects.
#include "llvm/DWARFLinker/DWARFLinkerDeclContext.h"
Public Member Functions
PointerIntPair< DeclContext *, 1 > getChildDeclContext (DeclContext &Context, const DWARFDie &DIE, CompileUnit &Unit, UniquingStringPool &StringPool, bool InClangModule)
Get the child of Context described by DIE in Unit.
DeclContext & getRoot ()
Detailed Description
This class gives a tree-like API to the DenseMap that stores the DeclContext objects.
It holds the BumpPtrAllocator where these objects will be allocated.
Definition at line 118 of file DWARFLinkerDeclContext.h.
Member Function Documentation
getChildDeclContext()
PointerIntPair< DeclContext *, 1 > llvm::DeclContextTree::getChildDeclContext (DeclContext & Context, const DWARFDie & DIE, CompileUnit & Unit, UniquingStringPool & StringPool, bool InClangModule)
Get the child of Context described by DIE in Unit.
The required strings will be interned in StringPool.
Returns
The child DeclContext along with one bit that is set if this context is invalid.
An invalid context means it shouldn't be considered for uniquing, but its not returning null, because some children of that context might be uniquing candidates.
FIXME: The invalid bit along the return value is to emulate some dsymutil-classic functionality.
Definition at line 43 of file DWARFLinkerDeclContext.cpp.
References llvm::DILineInfoSpecifier::AbsoluteFilePath, Allocator, assert(), Context, llvm::DeclContext::DeclContext(), llvm::StringRef::empty(), llvm::DWARFDie::find(), llvm::DWARFUnit::getCompilationDir(), llvm::DWARFUnit::getContext(), llvm::DWARFContext::getLineTableForUnit(), llvm::DWARFDie::getName(), llvm::CompileUnit::getOrigUnit(), llvm::DeclContext::getQualifiedNameHash(), llvm::CompileUnit::getResolvedPath(), llvm::DWARFDie::getTag(), llvm::DeclContext::getTag(), llvm::CompileUnit::getUniqueID(), llvm::hash_combine(), llvm::LinkageName, LLVM_FALLTHROUGH, llvm::AArch64CC::LT, llvm::max(), llvm::CompileUnit::setResolvedPath(), llvm::ShortName, and llvm::dwarf::toUnsigned().
getRoot()
DeclContext& llvm::DeclContextTree::getRoot () inline
Definition at line 136 of file DWARFLinkerDeclContext.h.
References Allocator.
The documentation for this class was generated from the following files:
include/llvm/DWARFLinker/DWARFLinkerDeclContext.h
lib/DWARFLinker/DWARFLinkerDeclContext.cpp