LLVM: llvm::MCAsmLayout Class Reference
llvm::MCAsmLayout Class Reference
Encapsulates the layout of an assembly file at a particular point in time.
#include "llvm/MC/MCAsmLayout.h"
Public Member Functions
MCAsmLayout (MCAssembler &Assembler)
MCAssembler & getAssembler () const
Get the assembler object this is a layout for.
void invalidateFragmentsFrom (MCFragment *F)
Invalidate the fragments starting with F because it has been resized.
void layoutFragment (MCFragment *Fragment)
Perform layout for a single fragment, assuming that the previous fragment has already been laid out correctly, and the parent section has been initialized.
Section Access (in layout order)
llvm::SmallVectorImpl< MCSection * > & getSectionOrder ()
const llvm::SmallVectorImpl< MCSection * > & getSectionOrder () const
Fragment Layout Data
uint64_t getFragmentOffset (const MCFragment *F) const
Get the offset of the given fragment inside its containing section.
Utility Functions
uint64_t getSectionAddressSize (const MCSection *Sec) const
Get the address space size of the given section, as it effects layout.
uint64_t getSectionFileSize (const MCSection *Sec) const
Get the data size of the given section, as emitted to the object file.
bool getSymbolOffset (const MCSymbol &S, uint64_t &Val) const
Get the offset of the given symbol, as computed in the current layout.
uint64_t getSymbolOffset (const MCSymbol &S) const
Variant that reports a fatal error if the offset is not computable.
const MCSymbol * getBaseSymbol (const MCSymbol &Symbol) const
If this symbol is equivalent to A + Constant, return A.
Detailed Description
Encapsulates the layout of an assembly file at a particular point in time.
Assembly may require computing multiple layouts for a particular assembly file as part of the relaxation process. This class encapsulates the layout at a single point in time in such a way that it is always possible to efficiently compute the exact address of any symbol in the assembly file, even during the relaxation process.
Definition at line 28 of file MCAsmLayout.h.
Constructor & Destructor Documentation
MCAsmLayout()
MCAsmLayout::MCAsmLayout (MCAssembler & Assembler)
Definition at line 32 of file MCFragment.cpp.
References assert(), F(), llvm::MCFragment::getLayoutOrder(), and llvm::MCFragment::getParent().
Member Function Documentation
getAssembler()
MCAssembler& llvm::MCAsmLayout::getAssembler () const inline
Get the assembler object this is a layout for.
Definition at line 50 of file MCAsmLayout.h.
References invalidateFragmentsFrom(), and layoutFragment().
Referenced by llvm::CodeViewContext::encodeDefRange(), llvm::MCExpr::evaluateAsRelocatable(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsValue(), getBaseSymbol(), getSectionAddressSize(), needPadding(), and llvm::MachObjectWriter::writeObject().
getBaseSymbol()
const MCSymbol * MCAsmLayout::getBaseSymbol (const MCSymbol & Symbol) const
If this symbol is equivalent to A + Constant, return A.
Definition at line 139 of file MCFragment.cpp.
References llvm::HexStyle::Asm, llvm::MCExpr::evaluateAsValue(), getAssembler(), llvm::MCAssembler::getContext(), llvm::MCExpr::getLoc(), llvm::MCSymbol::getName(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isCommon(), llvm::MCSymbol::isVariable(), and llvm::MCContext::reportError().
Referenced by getSectionOrder(), getSymbolValue(), and isIFunc().
getFragmentOffset()
uint64_t MCAsmLayout::getFragmentOffset (const MCFragment * F) const
Get the offset of the given fragment inside its containing section.
Definition at line 77 of file MCFragment.cpp.
References assert().
Referenced by canUseLocalRelocation(), llvm::MCAssembler::computeFragmentSize(), llvm::RISCVAsmBackend::evaluateTargetFixup(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), getFixupOffset(), llvm::MachObjectWriter::getFragmentAddress(), getLabelOffset(), getSectionAddressSize(), getSectionOrder(), isIFunc(), and needPadding().
getSectionAddressSize()
uint64_t MCAsmLayout::getSectionAddressSize (const MCSection * Sec) const
Get the address space size of the given section, as it effects layout.
This may differ from the size reported by
See also
getSectionSize() by not including section tail padding.
Definition at line 175 of file MCFragment.cpp.
References llvm::MCAssembler::computeFragmentSize(), getAssembler(), llvm::MCSection::getFragmentList(), and getFragmentOffset().
Referenced by llvm::MachObjectWriter::computeSectionAddresses(), llvm::MachObjectWriter::getPaddingSize(), getSectionFileSize(), getSectionOrder(), isAssociative(), isIFunc(), llvm::MachObjectWriter::writeObject(), and llvm::MachObjectWriter::writeSection().
getSectionFileSize()
uint64_t MCAsmLayout::getSectionFileSize (const MCSection * Sec) const
Get the data size of the given section, as emitted to the object file.
This may include additional padding, or be 0 for virtual sections.
Definition at line 181 of file MCFragment.cpp.
References getSectionAddressSize(), and llvm::MCSection::isVirtualSection().
Referenced by getSectionOrder(), llvm::MachObjectWriter::writeObject(), llvm::MachObjectWriter::writeSection(), and llvm::MCAssembler::writeSectionData().
getSectionOrder() [1/2]
llvm::SmallVectorImpl<MCSection *>& llvm::MCAsmLayout::getSectionOrder () inline
Definition at line 65 of file MCAsmLayout.h.
Referenced by llvm::MachObjectWriter::computeSectionAddresses(), llvm::MachObjectWriter::getPaddingSize(), llvm::MCAssembler::layout(), and needPadding().
getSectionOrder() [2/2]
const llvm::SmallVectorImpl<MCSection *>& llvm::MCAsmLayout::getSectionOrder () const inline
Definition at line 66 of file MCAsmLayout.h.
References getBaseSymbol(), getFragmentOffset(), getSectionAddressSize(), getSectionFileSize(), getSymbolOffset(), and llvm::ARMBuildAttrs::Symbol.
getSymbolOffset() [1/2]
bool MCAsmLayout::getSymbolOffset (const MCSymbol & S, uint64_t & Val) const
Get the offset of the given symbol, as computed in the current layout.
Returns
True on success.
Definition at line 129 of file MCFragment.cpp.
References getSymbolOffsetImpl().
Referenced by canUseLocalRelocation(), llvm::MCAssembler::computeFragmentSize(), llvm::RISCVAsmBackend::evaluateTargetFixup(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), getFixupOffset(), getSectionOrder(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolValue(), isIFunc(), and isInSymtab().
getSymbolOffset() [2/2]
uint64_t MCAsmLayout::getSymbolOffset (const MCSymbol & S) const
Variant that reports a fatal error if the offset is not computable.
Definition at line 133 of file MCFragment.cpp.
References getSymbolOffsetImpl().
invalidateFragmentsFrom()
void MCAsmLayout::invalidateFragmentsFrom (MCFragment * F)
Invalidate the fragments starting with F because it has been resized.
The fragment's size should have already been updated, but its bundle padding will be recomputed.
Definition at line 51 of file MCFragment.cpp.
References assert(), llvm::MCFragment::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), I, and layoutFragment().
Referenced by getAssembler(), and needPadding().
layoutFragment()
void MCAsmLayout::layoutFragment (MCFragment * Fragment)
Perform layout for a single fragment, assuming that the previous fragment has already been laid out correctly, and the parent section has been initialized.
Definition at line 389 of file MCAssembler.cpp.
References assert(), llvm::computeBundlePadding(), F(), llvm::MCFragment::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::MCFragment::hasInstructions(), llvm::report_fatal_error(), and llvm::MCEncodedFragment::setBundlePadding().
Referenced by getAssembler(), and invalidateFragmentsFrom().
The documentation for this class was generated from the following files:
include/llvm/MC/MCAsmLayout.h
lib/MC/MCAssembler.cpp
lib/MC/MCFragment.cpp