LLVM: llvm::MCDwarfLoc Class Reference
llvm::MCDwarfLoc Class Reference
Instances of this class represent the information from a dwarf .loc directive.
#include "llvm/MC/MCDwarf.h"
Public Member Functions
unsigned getFileNum () const
Get the FileNum of this MCDwarfLoc.
unsigned getLine () const
Get the Line of this MCDwarfLoc.
unsigned getColumn () const
Get the Column of this MCDwarfLoc.
unsigned getFlags () const
Get the Flags of this MCDwarfLoc.
unsigned getIsa () const
Get the Isa of this MCDwarfLoc.
unsigned getDiscriminator () const
Get the Discriminator of this MCDwarfLoc.
void setFileNum (unsigned fileNum)
Set the FileNum of this MCDwarfLoc.
void setLine (unsigned line)
Set the Line of this MCDwarfLoc.
void setColumn (unsigned column)
Set the Column of this MCDwarfLoc.
void setFlags (unsigned flags)
Set the Flags of this MCDwarfLoc.
void setIsa (unsigned isa)
Set the Isa of this MCDwarfLoc.
void setDiscriminator (unsigned discriminator)
Set the Discriminator of this MCDwarfLoc.
Friends
class MCContext
class MCDwarfLineEntry
Detailed Description
Instances of this class represent the information from a dwarf .loc directive.
Definition at line 70 of file MCDwarf.h.
Member Function Documentation
getColumn()
unsigned llvm::MCDwarfLoc::getColumn () const inline
Get the Column of this MCDwarfLoc.
Definition at line 107 of file MCDwarf.h.
getDiscriminator()
unsigned llvm::MCDwarfLoc::getDiscriminator () const inline
Get the Discriminator of this MCDwarfLoc.
Definition at line 116 of file MCDwarf.h.
getFileNum()
unsigned llvm::MCDwarfLoc::getFileNum () const inline
Get the FileNum of this MCDwarfLoc.
Definition at line 101 of file MCDwarf.h.
getFlags()
unsigned llvm::MCDwarfLoc::getFlags () const inline
Get the Flags of this MCDwarfLoc.
Definition at line 110 of file MCDwarf.h.
getIsa()
unsigned llvm::MCDwarfLoc::getIsa () const inline
Get the Isa of this MCDwarfLoc.
Definition at line 113 of file MCDwarf.h.
getLine()
unsigned llvm::MCDwarfLoc::getLine () const inline
Get the Line of this MCDwarfLoc.
Definition at line 104 of file MCDwarf.h.
setColumn()
void llvm::MCDwarfLoc::setColumn (unsigned column) inline
Set the Column of this MCDwarfLoc.
Definition at line 125 of file MCDwarf.h.
References assert().
Referenced by llvm::MCContext::setCurrentDwarfLoc().
setDiscriminator()
void llvm::MCDwarfLoc::setDiscriminator (unsigned discriminator) inline
Set the Discriminator of this MCDwarfLoc.
Definition at line 143 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
setFileNum()
void llvm::MCDwarfLoc::setFileNum (unsigned fileNum) inline
Set the FileNum of this MCDwarfLoc.
Definition at line 119 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
setFlags()
void llvm::MCDwarfLoc::setFlags (unsigned flags) inline
Set the Flags of this MCDwarfLoc.
Definition at line 131 of file MCDwarf.h.
References assert().
Referenced by llvm::MCContext::setCurrentDwarfLoc().
setIsa()
void llvm::MCDwarfLoc::setIsa (unsigned isa) inline
Set the Isa of this MCDwarfLoc.
Definition at line 137 of file MCDwarf.h.
References assert(), and llvm::isa().
Referenced by llvm::MCContext::setCurrentDwarfLoc().
setLine()
void llvm::MCDwarfLoc::setLine (unsigned line) inline
Set the Line of this MCDwarfLoc.
Definition at line 122 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
Friends And Related Function Documentation
MCContext
friend class MCContext friend
Definition at line 88 of file MCDwarf.h.
MCDwarfLineEntry
friend class MCDwarfLineEntry friend
Definition at line 89 of file MCDwarf.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCDwarf.h