LLVM: llvm::Check::FileCheckType Class Reference
llvm::Check::FileCheckType Class Reference
#include "llvm/Support/FileCheck.h"
Public Member Functions
FileCheckType (FileCheckKind Kind=CheckNone)
FileCheckType (const FileCheckType &)=default
FileCheckType & operator= (const FileCheckType &)=default
operator FileCheckKind () const
int getCount () const
FileCheckType & setCount (int C)
std::string getDescription (StringRef Prefix) const
Detailed Description
Definition at line 67 of file FileCheck.h.
Constructor & Destructor Documentation
FileCheckType() [1/2]
llvm::Check::FileCheckType::FileCheckType (FileCheckKind Kind = CheckNone) inline
Definition at line 72 of file FileCheck.h.
FileCheckType() [2/2]
llvm::Check::FileCheckType::FileCheckType (const FileCheckType &) default
Member Function Documentation
getCount()
int llvm::Check::FileCheckType::getCount () const inline
Definition at line 78 of file FileCheck.h.
References C, getDescription(), and llvm::cl::Prefix.
Referenced by llvm::Pattern::getCount().
getDescription()
std::string Check::FileCheckType::getDescription (StringRef Prefix) const
Definition at line 942 of file FileCheck.cpp.
References llvm::Check::CheckBadCount, llvm::Check::CheckBadNot, llvm::Check::CheckDAG, llvm::Check::CheckEmpty, llvm::Check::CheckEOF, llvm::Check::CheckLabel, llvm::Check::CheckNext, llvm::Check::CheckNone, llvm::Check::CheckNot, llvm::Check::CheckPlain, llvm::Check::CheckSame, llvm_unreachable, llvm::cl::Prefix, and llvm::StringRef::str().
Referenced by PrintMatch(), and PrintNoMatch().
operator FileCheckKind()
llvm::Check::FileCheckType::operator FileCheckKind () const inline
Definition at line 76 of file FileCheck.h.
operator=()
FileCheckType& llvm::Check::FileCheckType::operator= (const FileCheckType &) default
setCount()
Check::FileCheckType & Check::FileCheckType::setCount (int C)
Definition at line 934 of file FileCheck.cpp.
References assert(), C, and llvm::Check::CheckPlain.
Referenced by FindCheckType().
The documentation for this class was generated from the following files:
include/llvm/Support/FileCheck.h
lib/Support/FileCheck.cpp