LLVM: llvm::DiagnosticInfoInlineAsm Class Reference
llvm::DiagnosticInfoInlineAsm Class Reference
Diagnostic information for inline asm reporting.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoInlineAsm (const Twine &MsgStr, DiagnosticSeverity Severity=DS_Error)
MsgStr is the message to be reported to the frontend.
DiagnosticInfoInlineAsm (unsigned LocCookie, const Twine &MsgStr, DiagnosticSeverity Severity=DS_Error)
LocCookie if non-zero gives the line number for this report.
DiagnosticInfoInlineAsm (const Instruction &I, const Twine &MsgStr, DiagnosticSeverity Severity=DS_Error)
Instr gives the original instruction that triggered the diagnostic.
unsigned getLocCookie () const
const Twine & getMsgStr () const
const Instruction * getInstruction () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for inline asm reporting.
This is basically a message and an optional location.
Definition at line 128 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoInlineAsm() [1/3]
llvm::DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm (const Twine & MsgStr, DiagnosticSeverity Severity = DS_Error) inline
MsgStr is the message to be reported to the frontend.
This class does not copy MsgStr, therefore the reference must be valid for the whole life time of the Diagnostic.
Definition at line 141 of file DiagnosticInfo.h.
DiagnosticInfoInlineAsm() [2/3]
llvm::DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm (unsigned LocCookie, const Twine & MsgStr, DiagnosticSeverity Severity = DS_Error) inline
LocCookie if non-zero gives the line number for this report.
MsgStr gives the message. This class does not copy MsgStr, therefore the reference must be valid for the whole life time of the Diagnostic.
Definition at line 149 of file DiagnosticInfo.h.
References llvm::DS_Error, and I.
DiagnosticInfoInlineAsm() [3/3]
DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm (const Instruction & I, const Twine & MsgStr, DiagnosticSeverity Severity = DS_Error)
Instr gives the original instruction that triggered the diagnostic.
MsgStr gives the message. This class does not copy MsgStr, therefore the reference must be valid for the whole life time of the Diagnostic. Same for I.
Definition at line 53 of file DiagnosticInfo.cpp.
References llvm::Instruction::getMetadata().
Member Function Documentation
classof()
static bool llvm::DiagnosticInfoInlineAsm::classof (const DiagnosticInfo * DI) inline static
Definition at line 169 of file DiagnosticInfo.h.
References llvm::DK_InlineAsm, and llvm::DiagnosticInfo::getKind().
getInstruction()
const Instruction* llvm::DiagnosticInfoInlineAsm::getInstruction () const inline
Definition at line 164 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::print().
getLocCookie()
unsigned llvm::DiagnosticInfoInlineAsm::getLocCookie () const inline
Definition at line 162 of file DiagnosticInfo.h.
Referenced by print().
getMsgStr()
const Twine& llvm::DiagnosticInfoInlineAsm::getMsgStr () const inline
Definition at line 163 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoInlineAsm::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 65 of file DiagnosticInfo.cpp.
References getLocCookie(), and getMsgStr().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp