LLVM: llvm::orc::ConcurrentIRCompiler Class Reference
llvm::orc::ConcurrentIRCompiler Class Reference
A thread-safe version of SimpleCompiler.
#include "llvm/ExecutionEngine/Orc/CompileUtils.h"
Public Member Functions
ConcurrentIRCompiler (JITTargetMachineBuilder JTMB, ObjectCache *ObjCache=nullptr)
void setObjectCache (ObjectCache *ObjCache)
Expected< std::unique_ptr< MemoryBuffer > > operator() (Module &M) override
Public Member Functions inherited from llvm::orc::IRCompileLayer::IRCompiler
IRCompiler (IRMaterializationUnit::ManglingOptions MO)
virtual ~IRCompiler ()
const IRMaterializationUnit::ManglingOptions & getManglingOptions () const
Additional Inherited Members
Protected Member Functions inherited from llvm::orc::IRCompileLayer::IRCompiler
IRMaterializationUnit::ManglingOptions & manglingOptions ()
Detailed Description
A thread-safe version of SimpleCompiler.
This class creates a new TargetMachine and SimpleCompiler instance for each compile.
Definition at line 85 of file CompileUtils.h.
Constructor & Destructor Documentation
ConcurrentIRCompiler()
llvm::orc::ConcurrentIRCompiler::ConcurrentIRCompiler (JITTargetMachineBuilder JTMB, ObjectCache * ObjCache = nullptr)
Definition at line 81 of file CompileUtils.cpp.
Member Function Documentation
operator()()
Expected< std::unique_ptr< MemoryBuffer > > llvm::orc::ConcurrentIRCompiler::operator() (Module & M) override virtual
Implements llvm::orc::IRCompileLayer::IRCompiler.
Definition at line 87 of file CompileUtils.cpp.
References C, llvm::cantFail(), llvm::orc::JITTargetMachineBuilder::createTargetMachine(), and llvm::SystemZISD::TM.
setObjectCache()
void llvm::orc::ConcurrentIRCompiler::setObjectCache (ObjectCache * ObjCache) inline
Definition at line 90 of file CompileUtils.h.
References llvm::orc::SimpleCompiler::operator()().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/CompileUtils.h
lib/ExecutionEngine/Orc/CompileUtils.cpp