LLVM: llvm::ResourcePriorityQueue Class Reference
llvm::ResourcePriorityQueue Class Reference
#include "llvm/CodeGen/ResourcePriorityQueue.h"
Public Member Functions
ResourcePriorityQueue (SelectionDAGISel *IS)
bool isBottomUp () const override
void initNodes (std::vector< SUnit > &sunits) override
Initialize nodes.
void addNode (const SUnit *SU) override
void updateNode (const SUnit *SU) override
void releaseState () override
unsigned getLatency (unsigned NodeNum) const
unsigned getNumSolelyBlockNodes (unsigned NodeNum) const
int SUSchedulingCost (SUnit *SU)
Single cost function reflecting benefit of scheduling SU in the current cycle.
void initNumRegDefsLeft (SUnit *SU)
InitNumRegDefsLeft - Determine the # of regs defined by this node.
void updateNumRegDefsLeft (SUnit *SU)
int regPressureDelta (SUnit *SU, bool RawPressure=false)
Estimates change in reg pressure from this SU.
int rawRegPressureDelta (SUnit *SU, unsigned RCId)
bool empty () const override
void push (SUnit *U) override
SUnit * pop () override
Main access point - returns next instructions to be placed in scheduling sequence.
void remove (SUnit *SU) override
void scheduledNode (SUnit *SU) override
scheduledNode - Main resource tracking point.
bool isResourceAvailable (SUnit *SU)
Check if scheduling of this SU is possible in the current packet.
void reserveResources (SUnit *SU)
Keep track of available resources.
Public Member Functions inherited from llvm::SchedulingPriorityQueue
SchedulingPriorityQueue (bool rf=false)
virtual ~SchedulingPriorityQueue ()=default
bool hasReadyFilter () const
virtual bool tracksRegPressure () const
virtual bool isReady (SUnit *) const
void push_all (const std::vector< SUnit *> &Nodes)
virtual void dump (ScheduleDAG *) const
virtual void unscheduledNode (SUnit *)
void setCurCycle (unsigned Cycle)
unsigned getCurCycle () const
Detailed Description
Definition at line 37 of file ResourcePriorityQueue.h.
Constructor & Destructor Documentation
ResourcePriorityQueue()
ResourcePriorityQueue::ResourcePriorityQueue (SelectionDAGISel * IS)
Definition at line 43 of file ResourcePriorityQueue.cpp.
References assert(), llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::TargetInstrInfo::CreateTargetScheduleState(), llvm::numbers::e, llvm::TargetRegisterClass::getID(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNumOperands(), llvm::TargetRegisterInfo::getNumRegClasses(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getRegClassFor(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterInfo::getRegPressureLimit(), llvm::SDValue::getResNo(), llvm::SDNode::getSimpleValueType(), llvm::MachineFunction::getSubtarget(), llvm::SDep::getSUnit(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::SDep::isCtrl(), llvm::SDNode::isMachineOpcode(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SelectionDAGISel::MF, llvm::SUnit::Preds, llvm::TargetRegisterInfo::regclasses(), llvm::SUnit::Succs, llvm::SelectionDAGISel::TLI, and llvm::ISD::TokenFactor.
Member Function Documentation
addNode()
void llvm::ResourcePriorityQueue::addNode (const SUnit * SU) inline override virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 83 of file ResourcePriorityQueue.h.
empty()
bool llvm::ResourcePriorityQueue::empty () const inline override virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 114 of file ResourcePriorityQueue.h.
References push().
Referenced by pop().
getLatency()
unsigned llvm::ResourcePriorityQueue::getLatency (unsigned NodeNum) const inline
Definition at line 93 of file ResourcePriorityQueue.h.
References assert().
getNumSolelyBlockNodes()
unsigned llvm::ResourcePriorityQueue::getNumSolelyBlockNodes (unsigned NodeNum) const inline
Definition at line 98 of file ResourcePriorityQueue.h.
References assert().
initNodes()
void ResourcePriorityQueue::initNodes (std::vector< SUnit > & sunits) override virtual
Initialize nodes.
Implements llvm::SchedulingPriorityQueue.
Definition at line 163 of file ResourcePriorityQueue.cpp.
References llvm::numbers::e, initNumRegDefsLeft(), and llvm::SUnit::NodeQueueId.
initNumRegDefsLeft()
void ResourcePriorityQueue::initNumRegDefsLeft (SUnit * SU)
InitNumRegDefsLeft - Determine the # of regs defined by this node.
Definition at line 534 of file ResourcePriorityQueue.cpp.
References llvm::ISD::CopyFromReg, llvm::MCInstrInfo::get(), llvm::SUnit::getNode(), llvm::MCInstrDesc::getNumDefs(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::SUnit::isAvailable, N, llvm::SUnit::NumRegDefsLeft, and push().
Referenced by initNodes().
isBottomUp()
bool llvm::ResourcePriorityQueue::isBottomUp () const inline override virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 79 of file ResourcePriorityQueue.h.
isResourceAvailable()
bool ResourcePriorityQueue::isResourceAvailable (SUnit * SU)
Check if scheduling of this SU is possible in the current packet.
Definition at line 239 of file ResourcePriorityQueue.cpp.
References llvm::numbers::e, llvm::MCInstrInfo::get(), llvm::SDNode::getGluedNode(), llvm::SDNode::getMachineOpcode(), llvm::SUnit::getNode(), and llvm::SDNode::isMachineOpcode().
Referenced by reserveResources(), and SUSchedulingCost().
pop()
SUnit * ResourcePriorityQueue::pop () override virtual
Main access point - returns next instructions to be placed in scheduling sequence.
Implements llvm::SchedulingPriorityQueue.
Definition at line 586 of file ResourcePriorityQueue.cpp.
References DisableDFASched, E, empty(), I, SUSchedulingCost(), and std::swap().
push()
void ResourcePriorityQueue::push (SUnit * U) override virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 225 of file ResourcePriorityQueue.cpp.
References llvm::SDep::getSUnit(), llvm::SUnit::NodeNum, and llvm::SUnit::Succs.
Referenced by initNumRegDefsLeft().
rawRegPressureDelta()
int ResourcePriorityQueue::rawRegPressureDelta (SUnit * SU, unsigned RCId)
Definition at line 319 of file ResourcePriorityQueue.cpp.
References llvm::numbers::e, llvm::TargetRegisterClass::getID(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SDValue::getResNo(), llvm::SDNode::getSimpleValueType(), llvm::SDNode::isMachineOpcode(), and llvm::TargetLoweringBase::isTypeLegal().
Referenced by regPressureDelta().
regPressureDelta()
int ResourcePriorityQueue::regPressureDelta (SUnit * SU, bool RawPressure = false)
Estimates change in reg pressure from this SU.
It is achieved by trivial tracking of defined and used vregs in dependent instructions. The RawPressure flag makes this function to ignore existing reg file sizes, and report raw def/use balance.
Definition at line 353 of file ResourcePriorityQueue.cpp.
References llvm::SUnit::getNode(), llvm::SDNode::isMachineOpcode(), rawRegPressureDelta(), and llvm::TargetRegisterInfo::regclasses().
Referenced by SUSchedulingCost().
releaseState()
void llvm::ResourcePriorityQueue::releaseState () inline override virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 89 of file ResourcePriorityQueue.h.
remove()
void ResourcePriorityQueue::remove (SUnit * SU) override virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 618 of file ResourcePriorityQueue.cpp.
References assert(), llvm::find(), I, and std::swap().
reserveResources()
void ResourcePriorityQueue::reserveResources (SUnit * SU)
Keep track of available resources.
Definition at line 282 of file ResourcePriorityQueue.cpp.
References llvm::MCInstrInfo::get(), llvm::SDNode::getGluedNode(), llvm::SDNode::getMachineOpcode(), llvm::SUnit::getNode(), llvm::SDNode::isMachineOpcode(), isResourceAvailable(), llvm::MCSchedModel::IssueWidth, and llvm::InstrItineraryData::SchedModel.
Referenced by scheduledNode().
scheduledNode()
void ResourcePriorityQueue::scheduledNode (SUnit * SU) override virtual
scheduledNode - Main resource tracking point.
Main resource tracking point.
Reimplemented from llvm::SchedulingPriorityQueue.
Definition at line 460 of file ResourcePriorityQueue.cpp.
References llvm::numbers::e, llvm::TargetRegisterClass::getID(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SDValue::getResNo(), llvm::SDNode::getSimpleValueType(), llvm::SDep::getSUnit(), llvm::SDep::isCtrl(), llvm::SDNode::isMachineOpcode(), llvm::TargetLoweringBase::isTypeLegal(), numberCtrlDepsInSU(), numberCtrlPredInSU(), llvm::SUnit::NumPreds, llvm::SUnit::NumRegDefsLeft, llvm::SUnit::Preds, reserveResources(), and llvm::SUnit::Succs.
SUSchedulingCost()
int ResourcePriorityQueue::SUSchedulingCost (SUnit * SU)
Single cost function reflecting benefit of scheduling SU in the current cycle.
Returns single number reflecting benefit of scheduling SU in the current cycle.
Definition at line 389 of file ResourcePriorityQueue.cpp.
References llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::MCInstrInfo::get(), llvm::SUnit::getHeight(), llvm::SUnit::getNode(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::MCInstrDesc::isCall(), isResourceAvailable(), llvm::SUnit::isScheduled, llvm::SUnit::isScheduleHigh, N, llvm::SUnit::NodeNum, PriorityFour, PriorityOne, PriorityThree, regPressureDelta(), RegPressureThreshold, ScaleOne, ScaleTwo, and llvm::ISD::TokenFactor.
Referenced by pop().
updateNode()
void llvm::ResourcePriorityQueue::updateNode (const SUnit * SU) inline override virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 87 of file ResourcePriorityQueue.h.
updateNumRegDefsLeft()
void llvm::ResourcePriorityQueue::updateNumRegDefsLeft (SUnit * SU)
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ResourcePriorityQueue.h
lib/CodeGen/SelectionDAG/ResourcePriorityQueue.cpp