LLVM: llvm::IRBuilderDefaultInserter Class Reference
llvm::IRBuilderDefaultInserter Class Reference
This provides the default implementation of the IRBuilder 'InsertHelper' method that is called whenever an instruction is created by IRBuilder and needs to be inserted.
#include "llvm/IR/IRBuilder.h"
Protected Member Functions
void InsertHelper (Instruction *I, const Twine &Name, BasicBlock *BB, BasicBlock::iterator InsertPt) const
Detailed Description
This provides the default implementation of the IRBuilder 'InsertHelper' method that is called whenever an instruction is created by IRBuilder and needs to be inserted.
By default, this inserts the instruction at the insertion point.
Definition at line 61 of file IRBuilder.h.
Member Function Documentation
InsertHelper()
void llvm::IRBuilderDefaultInserter::InsertHelper (Instruction * I, const Twine & Name, BasicBlock * BB, BasicBlock::iterator InsertPt) const inline protected
Definition at line 63 of file IRBuilder.h.
References llvm::BasicBlock::getInstList(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), and llvm::Value::setName().
Referenced by llvm::IRBuilder< TargetFolder >::Insert(), and llvm::IRBuilderCallbackInserter::InsertHelper().
The documentation for this class was generated from the following file:
include/llvm/IR/IRBuilder.h