LLVM: llvm::IRBuilderBase Class Reference
llvm::IRBuilderBase Class Reference
Common base class shared among various IRBuilders.
#include "llvm/IR/IRBuilder.h"
Classes
class FastMathFlagGuard
class InsertPoint
InsertPoint - A saved insertion point.
class InsertPointGuard
Public Member Functions
IRBuilderBase (LLVMContext &context, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetCurrentDebugLocation (DebugLoc L)
Set location information used by debugging information.
const DebugLoc & getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
void clearFastMathFlags ()
Clear the fast-math flags.
void setDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void setFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
void setIsFPConstrained (bool IsCon)
Enable/Disable use of constrained floating point math.
bool getIsFPConstrained ()
Query for the use of constrained floating point math.
void setDefaultConstrainedExcept (fp::ExceptionBehavior NewExcept)
Set the exception handling to be used with constrained floating point.
void setDefaultConstrainedRounding (fp::RoundingMode NewRounding)
Set the rounding mode handling to be used with constrained floating point.
fp::ExceptionBehavior getDefaultConstrainedExcept ()
Get the exception handling used with constrained floating point.
fp::RoundingMode getDefaultConstrainedRounding ()
Get the rounding mode handling used with constrained floating point.
void setConstrainedFPFunctionAttr ()
void setConstrainedFPCallAttr (CallInst *I)
GlobalVariable * CreateGlobalString (StringRef Str, const Twine &Name="", unsigned AddressSpace=0)
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getInt128Ty ()
Fetch the type representing a 128-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout &DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, MaybeAlign Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, MaybeAlign Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemSet(Value *Ptr, Value *Val, uint64_t Size, unsigned Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead of this one")
Create and insert an element unordered-atomic memset of the region of memory starting at the given pointer to the given value.
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, uint64_t Size, Align Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemSet(Value *Ptr, Value *Val, Value *Size, unsigned Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead of this one")
FIXME: Remove this function once transition to Align is over.
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, Value *Size, Align Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemCpy(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign instead")
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemCpy (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemCpy(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign instead")
FIXME: Remove this function once transition to Align is over.
CallInst * CreateMemCpy (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memcpy between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemMove(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign")
Create and insert a memmove between the specified pointers.
CallInst * CreateMemMove (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemMove(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign")
FIXME: Remove this function once transition to Align is over.
CallInst * CreateMemMove (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memmove between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateFAddReduce (Value *Acc, Value *Src)
Create a vector fadd reduction intrinsic of the source vector.
CallInst * CreateFMulReduce (Value *Acc, Value *Src)
Create a vector fmul reduction intrinsic of the source vector.
CallInst * CreateAddReduce (Value *Src)
Create a vector int add reduction intrinsic of the source vector.
CallInst * CreateMulReduce (Value *Src)
Create a vector int mul reduction intrinsic of the source vector.
CallInst * CreateAndReduce (Value *Src)
Create a vector int AND reduction intrinsic of the source vector.
CallInst * CreateOrReduce (Value *Src)
Create a vector int OR reduction intrinsic of the source vector.
CallInst * CreateXorReduce (Value *Src)
Create a vector int XOR reduction intrinsic of the source vector.
CallInst * CreateIntMaxReduce (Value *Src, bool IsSigned=false)
Create a vector integer max reduction intrinsic of the source vector.
CallInst * CreateIntMinReduce (Value *Src, bool IsSigned=false)
Create a vector integer min reduction intrinsic of the source vector.
CallInst * CreateFPMaxReduce (Value *Src, bool NoNaN=false)
Create a vector float max reduction intrinsic of the source vector.
CallInst * CreateFPMinReduce (Value *Src, bool NoNaN=false)
Create a vector float min reduction intrinsic of the source vector.
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateInvariantStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a call to invariant.start intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, unsigned Align, Value *Mask, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, unsigned Align, Value *Mask)
Create a call to Masked Store intrinsic.
CallInst * CreateMaskedGather (Value *Ptrs, unsigned Align, Value *Mask=nullptr, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Gather intrinsic.
CallInst * CreateMaskedScatter (Value *Val, Value *Ptrs, unsigned Align, Value *Mask=nullptr)
Create a call to Masked Scatter intrinsic.
CallInst * CreateAssumption (Value *Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Value *> CallArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< Use > CallArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Conveninence function for the common case when CallArgs are filled in using makeArrayRef(CS.arg_begin(), CS.arg_end()); Use needs to be .get()'ed to get the Value pointer.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> InvokeArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< Use > InvokeArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
CallInst * CreateUnaryIntrinsic (Intrinsic::ID ID, Value *V, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 1 operand which is mangled on its type.
CallInst * CreateBinaryIntrinsic (Intrinsic::ID ID, Value *LHS, Value *RHS, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 2 operands which is mangled on the first type.
CallInst * CreateIntrinsic (Intrinsic::ID ID, ArrayRef< Type *> Types, ArrayRef< Value *> Args, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with args, mangled using Types.
CallInst * CreateMinNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minnum intrinsic.
CallInst * CreateMaxNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maxnum intrinsic.
CallInst * CreateMinimum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minimum intrinsic.
CallInst * CreateMaximum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maximum intrinsic.
Protected Attributes
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
MDNode * DefaultFPMathTag
FastMathFlags FMF
bool IsFPConstrained
fp::ExceptionBehavior DefaultConstrainedExcept
fp::RoundingMode DefaultConstrainedRounding
ArrayRef< OperandBundleDef > DefaultOperandBundles
Detailed Description
Common base class shared among various IRBuilders.
Definition at line 88 of file IRBuilder.h.
Constructor & Destructor Documentation
IRBuilderBase()
llvm::IRBuilderBase::IRBuilderBase (LLVMContext & context, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 106 of file IRBuilder.h.
Member Function Documentation
clearFastMathFlags()
void llvm::IRBuilderBase::clearFastMathFlags () inline
Clear the fast-math flags.
Definition at line 219 of file IRBuilder.h.
References llvm::FastMathFlags::clear().
ClearInsertionPoint()
void llvm::IRBuilderBase::ClearInsertionPoint () inline
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 121 of file IRBuilder.h.
Referenced by llvm::SCEVExpander::clearInsertPoint().
CreateAddReduce()
CallInst * IRBuilderBase::CreateAddReduce (Value * Src)
Create a vector int add reduction intrinsic of the source vector.
Definition at line 347 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateAndReduce()
CallInst * IRBuilderBase::CreateAndReduce (Value * Src)
Create a vector int AND reduction intrinsic of the source vector.
Definition at line 357 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateAssumption()
CallInst * IRBuilderBase::CreateAssumption (Value * Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
Definition at line 458 of file IRBuilder.cpp.
CreateBinaryIntrinsic()
CallInst * IRBuilderBase::CreateBinaryIntrinsic (Intrinsic::ID ID, Value * LHS, Value * RHS, Instruction * FMFSource = nullptr, const Twine & Name = "")
Create a call to intrinsic ID with 2 operands which is mangled on the first type.
Definition at line 747 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getModule(), llvm::Value::getType(), and Name.
Referenced by canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), generatePoisonChecksForBinOp(), and OptimizeNoopCopyExpression().
CreateElementUnorderedAtomicMemCpy() [1/2]
CallInst* llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert an element unordered-atomic memcpy between the specified pointers.
DstAlign/SrcAlign are the alignments of the Dst/Src pointers, respectively.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 571 of file IRBuilder.h.
CreateElementUnorderedAtomicMemCpy() [2/2]
CallInst * IRBuilderBase::CreateElementUnorderedAtomicMemCpy (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, Value * Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 203 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Instruction::setMetadata(), and Size.
CreateElementUnorderedAtomicMemMove() [1/2]
CallInst* llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert an element unordered-atomic memmove between the specified pointers.
DstAlign/SrcAlign are the alignments of the Dst/Src pointers, respectively.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 639 of file IRBuilder.h.
References llvm::BitmaskEnumDetail::Mask(), and Name.
CreateElementUnorderedAtomicMemMove() [2/2]
CallInst * IRBuilderBase::CreateElementUnorderedAtomicMemMove (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, Value * Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 278 of file IRBuilder.cpp.
References llvm::CallBase::addParamAttr(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), BB, createCallHelper(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Attribute::getWithAlignment(), llvm::Instruction::setMetadata(), and Size.
CreateElementUnorderedAtomicMemSet() [1/2]
CallInst* llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet (Value * Ptr, Value * Val, uint64_t Size, Align Alignment, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Definition at line 484 of file IRBuilder.h.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align.
CreateElementUnorderedAtomicMemSet() [2/2]
CallInst * IRBuilderBase::CreateElementUnorderedAtomicMemSet (Value * Ptr, Value * Val, Value * Size, Align Alignment, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 127 of file IRBuilder.cpp.
References BB, createCallHelper(), CreateMemCpy(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), isVolatile(), llvm::Instruction::setMetadata(), and Size.
CreateFAddReduce()
CallInst * IRBuilderBase::CreateFAddReduce (Value * Acc, Value * Src)
Create a vector fadd reduction intrinsic of the source vector.
The first parameter is a scalar accumulator value for ordered reductions.
Definition at line 329 of file IRBuilder.cpp.
References createCallHelper(), llvm::Intrinsic::getDeclaration(), GetInsertBlock(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), and llvm::Value::getType().
Referenced by llvm::createSimpleTargetReduction().
CreateFMulReduce()
CallInst * IRBuilderBase::CreateFMulReduce (Value * Acc, Value * Src)
Create a vector fmul reduction intrinsic of the source vector.
The first parameter is a scalar accumulator value for ordered reductions.
Definition at line 338 of file IRBuilder.cpp.
References createCallHelper(), llvm::Intrinsic::getDeclaration(), GetInsertBlock(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), and llvm::Value::getType().
Referenced by llvm::createSimpleTargetReduction().
CreateFPMaxReduce()
CallInst * IRBuilderBase::CreateFPMaxReduce (Value * Src, bool NoNaN = false)
Create a vector float max reduction intrinsic of the source vector.
Definition at line 384 of file IRBuilder.cpp.
References FMF, getReductionIntrinsic(), and llvm::FastMathFlags::setNoNaNs().
Referenced by llvm::createSimpleTargetReduction().
CreateFPMinReduce()
CallInst * IRBuilderBase::CreateFPMinReduce (Value * Src, bool NoNaN = false)
Create a vector float min reduction intrinsic of the source vector.
Definition at line 395 of file IRBuilder.cpp.
References FMF, getReductionIntrinsic(), and llvm::FastMathFlags::setNoNaNs().
Referenced by llvm::createSimpleTargetReduction().
CreateGCRelocate()
CallInst * IRBuilderBase::CreateGCRelocate (Instruction * Statepoint, int BaseOffset, int DerivedOffset, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Definition at line 723 of file IRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), and llvm::GlobalValue::getParent().
CreateGCResult()
CallInst * IRBuilderBase::CreateGCResult (Instruction * Statepoint, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
Definition at line 711 of file IRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getParent(), and llvm::GlobalValue::getParent().
CreateGCStatepointCall() [1/3]
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, ArrayRef< Value *> CallArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine & Name = "")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 630 of file IRBuilder.cpp.
References Name, and llvm::None.
CreateGCStatepointCall() [2/3]
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, uint32_t Flags, ArrayRef< Use > CallArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value *> GCArgs, const Twine & Name = "")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 639 of file IRBuilder.cpp.
References Name.
CreateGCStatepointCall() [3/3]
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine & Name = "")
Conveninence function for the common case when CallArgs are filled in using makeArrayRef(CS.arg_begin(), CS.arg_end()); Use needs to be .get()'ed to get the Value pointer.
Definition at line 648 of file IRBuilder.cpp.
References Name, and llvm::None.
CreateGCStatepointInvoke() [1/3]
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value *> InvokeArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine & Name = "")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 680 of file IRBuilder.cpp.
References Name, and llvm::None.
CreateGCStatepointInvoke() [2/3]
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, uint32_t Flags, ArrayRef< Use > InvokeArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value *> GCArgs, const Twine & Name = "")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 691 of file IRBuilder.cpp.
References Name.
CreateGCStatepointInvoke() [3/3]
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine & Name = "")
Definition at line 701 of file IRBuilder.cpp.
References Name, and llvm::None.
CreateGlobalString()
GlobalVariable * IRBuilderBase::CreateGlobalString (StringRef Str, const Twine & Name = "", unsigned AddressSpace = 0)
Make a new global variable with initializer type i8*.
CreateGlobalString - Make a new global variable with an initializer that has array of i8 type filled in with the nul terminated string value specified.
Make a new global variable with an initializer that has array of i8 type filled in with the null terminated string value specified. The new global variable will be marked mergable with any others of the same contents. If Name is specified, it is the name of the global variable created.
If Name is specified, it is the name of the global variable created.
Definition at line 42 of file IRBuilder.cpp.
References BB, Context, llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ConstantDataArray::getString(), llvm::Value::getType(), llvm::GlobalValue::Global, Name, llvm::Align::None(), llvm::GlobalValue::NotThreadLocal, llvm::GlobalValue::PrivateLinkage, and llvm::GlobalValue::setUnnamedAddr().
Referenced by isReportingError().
CreateIntMaxReduce()
CallInst * IRBuilderBase::CreateIntMaxReduce (Value * Src, bool IsSigned = false)
Create a vector integer max reduction intrinsic of the source vector.
Definition at line 372 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateIntMinReduce()
CallInst * IRBuilderBase::CreateIntMinReduce (Value * Src, bool IsSigned = false)
Create a vector integer min reduction intrinsic of the source vector.
Definition at line 378 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateIntrinsic()
CallInst * IRBuilderBase::CreateIntrinsic (Intrinsic::ID ID, ArrayRef< Type *> Types, ArrayRef< Value *> Args, Instruction * FMFSource = nullptr, const Twine & Name = "")
Create a call to intrinsic ID with args, mangled using Types.
If FMFSource is provided, copy fast-math-flags from that instruction to the intrinsic.
Definition at line 756 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), and llvm::BasicBlock::getModule().
Referenced by getMulHu(), INITIALIZE_PASS(), llvm::makeGuardControlFlowExplicit(), and simplifyX86addcarry().
CreateInvariantStart()
CallInst * IRBuilderBase::CreateInvariantStart (Value * Ptr, ConstantInt * Size = nullptr)
Create a call to invariant.start intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 438 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ConstantInt::getType(), llvm::Value::getType(), and Size.
CreateLifetimeEnd()
CallInst * IRBuilderBase::CreateLifetimeEnd (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.end intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 422 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ConstantInt::getType(), llvm::Value::getType(), and Size.
Referenced by GetRMWLibcall().
CreateLifetimeStart()
CallInst * IRBuilderBase::CreateLifetimeStart (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.start intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 406 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ConstantInt::getType(), llvm::Value::getType(), and Size.
Referenced by GetRMWLibcall().
CreateMaskedGather()
CallInst * IRBuilderBase::CreateMaskedGather (Value * Ptrs, unsigned Align, Value * Mask = nullptr, Value * PassThru = nullptr, const Twine & Name = "")
Create a call to Masked Gather intrinsic.
Create a call to a Masked Gather intrinsic.
Ptrs - vector of pointers for loading Align - alignment for one element Mask - vector of booleans which indicates what vector lanes should be accessed in memory PassThru - pass-through value that is used to fill the masked-off lanes of the result Name - name of the result variable
Definition at line 528 of file IRBuilder.cpp.
References Context, llvm::VectorType::get(), llvm::UndefValue::get(), llvm::Constant::getAllOnesValue(), llvm::Type::getInt1Ty(), getInt32(), llvm::Value::getType(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaskedLoad()
CallInst * IRBuilderBase::CreateMaskedLoad (Value * Ptr, unsigned Align, Value * Mask, Value * PassThru = nullptr, const Twine & Name = "")
Create a call to Masked Load intrinsic.
Create a call to a Masked Load intrinsic.
Ptr - base pointer for the load Align - alignment of the source location Mask - vector of booleans which indicates what vector lanes should be accessed in memory PassThru - pass-through value that is used to fill the masked-off lanes of the result Name - name of the result variable
Definition at line 476 of file IRBuilder.cpp.
References assert(), llvm::UndefValue::get(), getInt32(), llvm::Value::getType(), and llvm::BitmaskEnumDetail::Mask().
Referenced by simplifyX86MaskedLoad(), UpgradeMaskedLoad(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaskedScatter()
CallInst * IRBuilderBase::CreateMaskedScatter (Value * Data, Value * Ptrs, unsigned Align, Value * Mask = nullptr)
Create a call to Masked Scatter intrinsic.
Create a call to a Masked Scatter intrinsic.
Data - data to be stored, Ptrs - the vector of pointers, where the Data elements should be stored Align - alignment for one element Mask - vector of booleans which indicates what vector lanes should be accessed in memory
Definition at line 559 of file IRBuilder.cpp.
References assert(), Context, llvm::Data, llvm::VectorType::get(), llvm::Constant::getAllOnesValue(), llvm::Type::getInt1Ty(), getInt32(), and llvm::Value::getType().
Referenced by llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaskedStore()
CallInst * IRBuilderBase::CreateMaskedStore (Value * Val, Value * Ptr, unsigned Align, Value * Mask)
Create a call to Masked Store intrinsic.
Create a call to a Masked Store intrinsic.
Val - data to be stored, Ptr - base pointer for the store Align - alignment of the destination location Mask - vector of booleans which indicates what vector lanes should be accessed in memory
Definition at line 497 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), and Name.
Referenced by simplifyX86MaskedStore(), UpgradeMaskedStore(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaximum()
CallInst* llvm::IRBuilderBase::CreateMaximum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the maximum intrinsic.
Definition at line 837 of file IRBuilder.h.
References llvm::maximum(), and Name.
CreateMaxNum()
CallInst* llvm::IRBuilderBase::CreateMaxNum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the maxnum intrinsic.
Definition at line 827 of file IRBuilder.h.
References llvm::maxnum(), and Name.
CreateMemCpy() [1/2]
CallInst* llvm::IRBuilderBase::CreateMemCpy (Value * Dst, MaybeAlign DstAlign, Value * Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Definition at line 535 of file IRBuilder.h.
References isVolatile(), and LLVM_ATTRIBUTE_DEPRECATED.
Referenced by annotateNonNullAndDereferenceable(), CreateElementUnorderedAtomicMemSet(), handleMemIntrinsicPtrUse(), isCallPromotable(), isReportingError(), llvm::LibCallSimplifier::LibCallSimplifier(), moveUp(), optimizeMemCmpConstantSize(), and StackMallocSizeClass().
CreateMemCpy() [2/2]
CallInst * IRBuilderBase::CreateMemCpy (Value * Dst, MaybeAlign DstAlign, Value * Src, MaybeAlign SrcAlign, Value * Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 165 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Instruction::setMetadata(), and Size.
CreateMemMove() [1/2]
CallInst* llvm::IRBuilderBase::CreateMemMove (Value * Dst, MaybeAlign DstAlign, Value * Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Definition at line 605 of file IRBuilder.h.
References isVolatile().
Referenced by handleMemIntrinsicPtrUse(), isCallPromotable(), isReportingError(), llvm::LibCallSimplifier::LibCallSimplifier(), moveUp(), and optimizeMemCmpConstantSize().
CreateMemMove() [2/2]
CallInst * IRBuilderBase::CreateMemMove (Value * Dst, MaybeAlign DstAlign, Value * Src, MaybeAlign SrcAlign, Value * Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 244 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Instruction::setMetadata(), and Size.
CreateMemSet() [1/2]
CallInst* llvm::IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, uint64_t Size, MaybeAlign Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert a memset to the specified pointer and the specified value.
If the pointer isn't an i8*, it will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 452 of file IRBuilder.h.
References isVolatile(), and Size.
Referenced by annotateNonNullAndDereferenceable(), getAllocaSizeInBytes(), handleMemIntrinsicPtrUse(), hasUndefContents(), isCallPromotable(), llvm::LibCallSimplifier::LibCallSimplifier(), moveUp(), and optimizeMemCmpConstantSize().
CreateMemSet() [2/2]
CallInst * IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, Value * Size, MaybeAlign Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 99 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Instruction::setMetadata(), and Size.
CreateMinimum()
CallInst* llvm::IRBuilderBase::CreateMinimum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the minimum intrinsic.
Definition at line 832 of file IRBuilder.h.
References llvm::minimum(), and Name.
CreateMinNum()
CallInst* llvm::IRBuilderBase::CreateMinNum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the minnum intrinsic.
Definition at line 822 of file IRBuilder.h.
References llvm::minnum(), and Name.
CreateMulReduce()
CallInst * IRBuilderBase::CreateMulReduce (Value * Src)
Create a vector int mul reduction intrinsic of the source vector.
Definition at line 352 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateOrReduce()
CallInst * IRBuilderBase::CreateOrReduce (Value * Src)
Create a vector int OR reduction intrinsic of the source vector.
Definition at line 362 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateUnaryIntrinsic()
CallInst * IRBuilderBase::CreateUnaryIntrinsic (Intrinsic::ID ID, Value * V, Instruction * FMFSource = nullptr, const Twine & Name = "")
Create a call to intrinsic ID with 1 operand which is mangled on its type.
Definition at line 739 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getModule(), llvm::Value::getType(), and Name.
Referenced by getMulHu().
CreateXorReduce()
CallInst * IRBuilderBase::CreateXorReduce (Value * Src)
Create a vector int XOR reduction intrinsic of the source vector.
Definition at line 367 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
getContext()
LLVMContext& llvm::IRBuilderBase::getContext () const inline
Definition at line 128 of file IRBuilder.h.
References Context.
Referenced by Cleanup(), createOrdering(), emitBinaryFloatFnCallHelper(), emitUnaryFloatFnCallHelper(), performMaskedAtomicOp(), and SegmentOffset().
getCurrentDebugLocation()
const DebugLoc& llvm::IRBuilderBase::getCurrentDebugLocation () const inline
Get location information used by debugging information.
Definition at line 159 of file IRBuilder.h.
Referenced by llvm::SCEVExpander::getCurrentDebugLocation().
getCurrentFunctionReturnType()
Type * IRBuilderBase::getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
Definition at line 56 of file IRBuilder.cpp.
References assert(), BB, llvm::BasicBlock::getInstList(), getInt8PtrTy(), llvm::BasicBlock::getParent(), llvm::Function::getReturnType(), llvm::Value::getType(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), InsertPt, and SetInstDebugLocation().
getDefaultConstrainedExcept()
fp::ExceptionBehavior llvm::IRBuilderBase::getDefaultConstrainedExcept () inline
Get the exception handling used with constrained floating point.
Definition at line 247 of file IRBuilder.h.
getDefaultConstrainedRounding()
fp::RoundingMode llvm::IRBuilderBase::getDefaultConstrainedRounding () inline
Get the rounding mode handling used with constrained floating point.
Definition at line 252 of file IRBuilder.h.
getDefaultFPMathTag()
MDNode* llvm::IRBuilderBase::getDefaultFPMathTag () const inline
Get the floating point math metadata being used.
Definition at line 213 of file IRBuilder.h.
getDoubleTy()
Type* llvm::IRBuilderBase::getDoubleTy () inline
Fetch the type representing a 64-bit floating point value.
Definition at line 423 of file IRBuilder.h.
References llvm::Type::getDoubleTy().
Referenced by optimizeDoubleFP().
getFalse()
ConstantInt* llvm::IRBuilderBase::getFalse () inline
Get the constant value for i1 false.
Definition at line 340 of file IRBuilder.h.
References llvm::ConstantInt::getFalse().
Referenced by buildOrChain(), createFFSIntrinsic(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), handleNoSuspendCoroutine(), and llvm::LoopPredicationPass::run().
getFastMathFlags()
FastMathFlags llvm::IRBuilderBase::getFastMathFlags () const inline
Get the flags to be applied to created floating point ops.
Definition at line 216 of file IRBuilder.h.
Referenced by getMulHu().
getFloatTy()
Type* llvm::IRBuilderBase::getFloatTy () inline
Fetch the type representing a 32-bit floating point value.
Definition at line 418 of file IRBuilder.h.
References llvm::Type::getFloatTy().
Referenced by getMulHu(), and optimizeDoubleFP().
getHalfTy()
Type* llvm::IRBuilderBase::getHalfTy () inline
Fetch the type representing a 16-bit floating point value.
Definition at line 413 of file IRBuilder.h.
References llvm::Type::getHalfTy().
GetInsertBlock()
BasicBlock* llvm::IRBuilderBase::GetInsertBlock () const inline
Definition at line 126 of file IRBuilder.h.
Referenced by callIntrinsic(), llvm::SanitizerStatReport::create(), createCallHelper(), CreateFAddReduce(), createFFSIntrinsic(), CreateFMulReduce(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), createInvokeHelper(), createPopcntIntrinsic(), llvm::orc::IRSpeculationLayer::emit(), llvm::AArch64TargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::emitBCmp(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::emitMalloc(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::emitStrLen(), llvm::emitStrNCmp(), llvm::PPCTargetLowering::emitTrailingFence(), emitUnaryFloatFnCallHelper(), generateUnsignedDivisionCode(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), llvm::TargetLoweringBase::getIRStackGuard(), getReductionIntrinsic(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), insertSinCosCall(), isKnownTypeIdMember(), isReportingError(), llvm::ARMTargetLowering::makeDMB(), optimizeMemCmpConstantSize(), performMaskedAtomicOp(), RetagMask(), llvm::HWAddressSanitizerPass::run(), TypeSizeToSizeIndex(), and UseTlsOffset().
GetInsertPoint()
BasicBlock::iterator llvm::IRBuilderBase::GetInsertPoint () const inline
Definition at line 127 of file IRBuilder.h.
Referenced by createCallHelper(), createInvokeHelper(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::expandDivision(), llvm::expandRemainder(), insertBoundsCheck(), instrumentOneFunc(), llvm::log2(), performMaskedAtomicOp(), postDominates(), and TypeSizeToSizeIndex().
getInt()
ConstantInt* llvm::IRBuilderBase::getInt (const APInt & AI) inline
Get a constant integer value.
Definition at line 371 of file IRBuilder.h.
References llvm::ConstantInt::get().
Referenced by annotateNonNullAndDereferenceable().
getInt1()
ConstantInt* llvm::IRBuilderBase::getInt1 (bool V) inline
Get a constant value representing either true or false.
Definition at line 330 of file IRBuilder.h.
References llvm::ConstantInt::get().
Referenced by llvm::createBitMaskForGaps(), CreateMemCpy(), CreateMemMove(), and CreateMemSet().
getInt128Ty()
IntegerType* llvm::IRBuilderBase::getInt128Ty () inline
Fetch the type representing a 128-bit integer.
Definition at line 405 of file IRBuilder.h.
References llvm::Type::getInt128Ty().
getInt16()
ConstantInt* llvm::IRBuilderBase::getInt16 (uint16_t C) inline
Get a constant 16-bit value.
Definition at line 350 of file IRBuilder.h.
References llvm::ConstantInt::get().
getInt16Ty()
IntegerType* llvm::IRBuilderBase::getInt16Ty () inline
Fetch the type representing a 16-bit integer.
Definition at line 390 of file IRBuilder.h.
References llvm::Type::getInt16Ty().
Referenced by llvm::ModuleSanitizerCoveragePass::run().
getInt1Ty()
IntegerType* llvm::IRBuilderBase::getInt1Ty () inline
Fetch the type representing a single bit.
Definition at line 380 of file IRBuilder.h.
References llvm::Type::getInt1Ty().
Referenced by EmitX86ScalarSelect(), getX86MaskVec(), and upgradeMaskedCompare().
getInt32()
ConstantInt* llvm::IRBuilderBase::getInt32 (uint32_t C) inline
Get a constant 32-bit value.
Definition at line 355 of file IRBuilder.h.
References llvm::ConstantInt::get().
Referenced by canonicalizeInsertSplat(), CreateElementUnorderedAtomicMemCpy(), CreateElementUnorderedAtomicMemMove(), CreateElementUnorderedAtomicMemSet(), CreateGCRelocate(), CreateGCRelocates(), llvm::createInterleaveMask(), CreateMaskedGather(), CreateMaskedLoad(), CreateMaskedScatter(), CreateMaskedStore(), createOrdering(), createRdxShuffleMask(), llvm::createReplicatedMask(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPBasicBlock::execute(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), foldVecTruncToExtElt(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), getMulHu(), llvm::InnerLoopVectorizer::getOrCreateScalarValue(), llvm::getOrderedReduction(), getOrInsertGlobal(), getScalarIntrinsicDeclaration(), llvm::getShuffleReduction(), getSignature(), getStatepointArgs(), getSuccState(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), instrumentOneFunc(), isIndirectBrTarget(), isReportingError(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::makeDMB(), optimizeIntegerToVectorInsertions(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), llvm::InnerLoopVectorizer::reverseVector(), shouldKeepInEntry(), simplifyAllocaArraySize(), TypeSizeToSizeIndex(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
getInt32Ty()
IntegerType* llvm::IRBuilderBase::getInt32Ty () inline
Fetch the type representing a 32-bit integer.
Definition at line 395 of file IRBuilder.h.
References llvm::Type::getInt32Ty().
Referenced by llvm::SanitizerStatReport::create(), createOrdering(), createPowWithIntegerExponent(), createPrivateNonConstGlobalForString(), createRdxShuffleMask(), llvm::emitBCmp(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitMemCCpy(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitPutChar(), llvm::emitPutS(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::emitStrChr(), llvm::emitStrNCmp(), llvm::emitVSNPrintf(), llvm::emitVSPrintf(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainderUpTo32Bits(), getGlobalVariableI32(), getIntrinsicForMaskedAtomicRMWBinOp(), getIntToFPVal(), getMul64(), getMulHu(), getOrInsertGlobal(), llvm::getShuffleReduction(), getSignature(), getSuccState(), GlobalWasGeneratedByCompiler(), insertSinCosCall(), insertValues(), instrumentMaskedLoadOrStore(), isAtomic(), llvm::log2(), RetagMask(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), shouldKeepInEntry(), and TypeSizeToSizeIndex().
getInt64()
ConstantInt* llvm::IRBuilderBase::getInt64 (uint64_t C) inline
Get a constant 64-bit value.
Definition at line 360 of file IRBuilder.h.
References llvm::ConstantInt::get().
Referenced by annotateNonNullAndDereferenceable(), CreateInvariantStart(), CreateLifetimeEnd(), CreateLifetimeStart(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), getMul64(), getStatepointArgs(), instrumentOneFunc(), isIndirectBrTarget(), needsRuntimeRegistrationOfSectionRange(), shouldKeepInEntry(), and splitRetconCoroutine().
getInt64Ty()
IntegerType* llvm::IRBuilderBase::getInt64Ty () inline
Fetch the type representing a 64-bit integer.
Definition at line 400 of file IRBuilder.h.
References llvm::Type::getInt64Ty().
Referenced by llvm::createAArch64StackTaggingPass(), CreateInvariantStart(), CreateLifetimeEnd(), CreateLifetimeStart(), createPrivateNonConstGlobalForString(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo64Bits(), getIntrinsicForMaskedAtomicRMWBinOp(), getMul64(), getOrInsertGlobal(), INITIALIZE_PASS(), instrumentOneFunc(), isIndirectBrTarget(), llvm::log2(), postDominates(), llvm::ModuleSanitizerCoveragePass::run(), and shouldKeepInEntry().
getInt8()
ConstantInt* llvm::IRBuilderBase::getInt8 (uint8_t C) inline
Get a constant 8-bit value.
Definition at line 345 of file IRBuilder.h.
References llvm::ConstantInt::get().
Referenced by annotateNonNullAndDereferenceable(), convert_i1_to_i8(), createResumeEntryBlock(), isReportingError(), and shouldKeepInEntry().
getInt8PtrTy()
PointerType* llvm::IRBuilderBase::getInt8PtrTy (unsigned AddrSpace = 0) inline
Fetch the type representing a pointer to an 8-bit integer value.
Definition at line 433 of file IRBuilder.h.
References llvm::Type::getInt8PtrTy().
Referenced by llvm::castToCStr(), llvm::SanitizerStatReport::create(), llvm::createAArch64StackTaggingPass(), createOrdering(), createPrivateNonConstGlobalForString(), CreatePrologue(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createThreadSanitizerLegacyPassPass(), llvm::emitBCmp(), llvm::emitCalloc(), llvm::emitFGetSUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), llvm::emitMalloc(), llvm::emitMemCCpy(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitMemCpyChk(), llvm::emitPutS(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::emitStpCpy(), llvm::emitStpNCpy(), llvm::emitStrCat(), llvm::emitStrChr(), llvm::emitStrCpy(), llvm::emitStrDup(), llvm::emitStrLCat(), llvm::emitStrLCpy(), llvm::emitStrLen(), llvm::emitStrNCat(), llvm::emitStrNCmp(), llvm::emitStrNCpy(), llvm::emitVSNPrintf(), llvm::emitVSPrintf(), getCurrentFunctionReturnType(), getOrInsertGlobal(), getSignature(), getStackGuard(), getSuccState(), GlobalWasGeneratedByCompiler(), handleNoSuspendCoroutine(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isAtomic(), isIndirectBrTarget(), IsNonLocalValue(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerSubFn(), MarkBlocksLiveIn(), mayLoopAccessLocation(), postDominates(), RetagMask(), llvm::HWAddressSanitizerPass::run(), shouldKeepInEntry(), TypeSizeToSizeIndex(), llvm::UpgradeGlobalVariable(), and UseTlsOffset().
getInt8Ty()
IntegerType* llvm::IRBuilderBase::getInt8Ty () inline
Fetch the type representing an 8-bit integer.
Definition at line 385 of file IRBuilder.h.
References llvm::Type::getInt8Ty().
Referenced by annotateNonNullAndDereferenceable(), createPrivateNonConstGlobalForString(), createResumeEntryBlock(), llvm::createSeparateConstOffsetFromGEPPass(), getAllocaSizeInBytes(), getOrInsertGlobal(), instrumentMaskedLoadOrStore(), IsNonLocalValue(), isReportingError(), llvm::LibCallSimplifier::LibCallSimplifier(), lowerLocalAllocas(), optimizeMemCmpConstantSize(), RetagMask(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), shouldKeepInEntry(), simplifyX86addcarry(), TypeSizeToSizeIndex(), unifyBitWidth(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), and UseTlsOffset().
getIntN()
ConstantInt* llvm::IRBuilderBase::getIntN (unsigned N, uint64_t C) inline
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
Definition at line 366 of file IRBuilder.h.
References llvm::ConstantInt::get().
Referenced by annotateNonNullAndDereferenceable(), and getIntrinsicForMaskedAtomicRMWBinOp().
getIntNTy()
IntegerType* llvm::IRBuilderBase::getIntNTy (unsigned N) inline
Fetch the type representing an N-bit integer.
Definition at line 408 of file IRBuilder.h.
References llvm::Type::getIntNTy().
Referenced by annotateNonNullAndDereferenceable(), ApplyX86MaskOn1BitsVec(), createCmpXchgInstFun(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), getMulHu(), getOrInsertGlobal(), simplifyX86movmsk(), and TypeSizeToSizeIndex().
getIntPtrTy()
IntegerType* llvm::IRBuilderBase::getIntPtrTy (const DataLayout & DL, unsigned AddrSpace = 0) inline
Fetch the type representing a pointer to an integer value.
Definition at line 438 of file IRBuilder.h.
References llvm::DataLayout::getIntPtrType().
Referenced by llvm::SanitizerStatReport::create(), getOrInsertGlobal(), mayLoopAccessLocation(), and llvm::HWAddressSanitizerPass::run().
getIsFPConstrained()
bool llvm::IRBuilderBase::getIsFPConstrained () inline
Query for the use of constrained floating point math.
Definition at line 234 of file IRBuilder.h.
getTrue()
ConstantInt* llvm::IRBuilderBase::getTrue () inline
Get the constant value for i1 true.
Definition at line 335 of file IRBuilder.h.
References llvm::ConstantInt::getTrue().
Referenced by createFFSIntrinsic(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::VPBranchOnMaskRecipe::execute(), foldCttzCtlz(), generateUnsignedDivisionCode(), insertSinCosCall(), and llvm::LoopPredicationPass::run().
getVoidTy()
Type* llvm::IRBuilderBase::getVoidTy () inline
Fetch the type representing void.
Definition at line 428 of file IRBuilder.h.
References llvm::Type::getVoidTy().
Referenced by llvm::SanitizerStatReport::create(), createPrivateNonConstGlobalForString(), llvm::createThreadSanitizerLegacyPassPass(), getOrInsertGlobal(), getSignature(), instrumentMaskedLoadOrStore(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), shouldKeepInEntry(), and TypeSizeToSizeIndex().
LLVM_ATTRIBUTE_DEPRECATED() [1/6]
llvm::IRBuilderBase::LLVM_ATTRIBUTE_DEPRECATED (CallInst * CreateElementUnorderedAtomicMemSet Value *Ptr, Value *Val, uint64_t Size, unsigned Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr, "Use the version that takes Align instead of this one") inline
Create and insert an element unordered-atomic memset of the region of memory starting at the given pointer to the given value.
If the pointer isn't an i8*, it will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags. FIXME: Remove this function once transition to Align is over. Use the version that takes Align instead of this one.
Definition at line 473 of file IRBuilder.h.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align.
LLVM_ATTRIBUTE_DEPRECATED() [2/6]
llvm::IRBuilderBase::LLVM_ATTRIBUTE_DEPRECATED (CallInst * CreateElementUnorderedAtomicMemSet Value *Ptr, Value *Val, Value *Size, unsigned Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr, "Use the version that takes Align instead of this one") inline
FIXME: Remove this function once transition to Align is over.
Use the version that takes Align instead of this one.
Definition at line 497 of file IRBuilder.h.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align.
LLVM_ATTRIBUTE_DEPRECATED() [3/6]
llvm::IRBuilderBase::LLVM_ATTRIBUTE_DEPRECATED (CallInst * CreateMemCpyValue *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr, "Use the version that takes MaybeAlign instead") inline
Create and insert a memcpy between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags. FIXME: Remove this function once transition to Align is over. Use the version that takes MaybeAlign instead of this one.
Definition at line 522 of file IRBuilder.h.
References isVolatile().
LLVM_ATTRIBUTE_DEPRECATED() [4/6]
llvm::IRBuilderBase::LLVM_ATTRIBUTE_DEPRECATED (CallInst * CreateMemCpyValue *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr, "Use the version that takes MaybeAlign instead")
FIXME: Remove this function once transition to Align is over.
Use the version that takes MaybeAlign instead of this one.
LLVM_ATTRIBUTE_DEPRECATED() [5/6]
llvm::IRBuilderBase::LLVM_ATTRIBUTE_DEPRECATED (CallInst * CreateMemMove Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr, "Use the version that takes MaybeAlign") inline
Create and insert a memmove between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags. FIXME: Remove this function once transition to Align is over. Use the version that takes MaybeAlign instead of this one.
Definition at line 595 of file IRBuilder.h.
References isVolatile().
LLVM_ATTRIBUTE_DEPRECATED() [6/6]
llvm::IRBuilderBase::LLVM_ATTRIBUTE_DEPRECATED (CallInst * CreateMemMove Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr, "Use the version that takes MaybeAlign") inline
FIXME: Remove this function once transition to Align is over.
Use the version that takes MaybeAlign instead of this one.
Definition at line 615 of file IRBuilder.h.
References isVolatile().
restoreIP()
void llvm::IRBuilderBase::restoreIP (InsertPoint IP) inline
Sets the current insert point to a previously-saved location.
Definition at line 205 of file IRBuilder.h.
References llvm::IRBuilderBase::InsertPoint::getBlock(), llvm::IRBuilderBase::InsertPoint::getPoint(), and llvm::IRBuilderBase::InsertPoint::isSet().
Referenced by llvm::InnerLoopVectorizer::getOrCreateVectorValue(), and llvm::IRBuilderBase::InsertPointGuard::~InsertPointGuard().
saveAndClearIP()
InsertPoint llvm::IRBuilderBase::saveAndClearIP () inline
Returns the current insert point, clearing it in the process.
Definition at line 198 of file IRBuilder.h.
saveIP()
InsertPoint llvm::IRBuilderBase::saveIP () const inline
Returns the current insert point.
Definition at line 193 of file IRBuilder.h.
Referenced by llvm::InnerLoopVectorizer::getOrCreateVectorValue().
setConstrainedFPCallAttr()
void llvm::IRBuilderBase::setConstrainedFPCallAttr (CallInst * I) inline
Definition at line 265 of file IRBuilder.h.
References llvm::CallBase::addAttribute(), llvm::AttributeList::FunctionIndex, and llvm::CallBase::hasFnAttr().
setConstrainedFPFunctionAttr()
void llvm::IRBuilderBase::setConstrainedFPFunctionAttr () inline
Definition at line 256 of file IRBuilder.h.
References llvm::Function::addFnAttr(), assert(), F(), llvm::BasicBlock::getParent(), and llvm::Function::hasFnAttribute().
SetCurrentDebugLocation()
void llvm::IRBuilderBase::SetCurrentDebugLocation (DebugLoc L) inline
Set location information used by debugging information.
Definition at line 156 of file IRBuilder.h.
Referenced by canFoldIVIncExpr(), llvm::createAMDGPUPrintfRuntimeBinding(), CreatePrologue(), getMulHu(), INITIALIZE_PASS(), insertValues(), promotedOpIsNUW(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::SCEVExpander::SetCurrentDebugLocation(), llvm::InnerLoopVectorizer::setDebugLocFromInst(), shouldKeepFDivF32(), SimplifyIndirectBrOnSelect(), simplifyRelocatesOffABase(), and llvm::IRBuilderBase::InsertPointGuard::~InsertPointGuard().
setDefaultConstrainedExcept()
void llvm::IRBuilderBase::setDefaultConstrainedExcept (fp::ExceptionBehavior NewExcept) inline
Set the exception handling to be used with constrained floating point.
Definition at line 237 of file IRBuilder.h.
setDefaultConstrainedRounding()
void llvm::IRBuilderBase::setDefaultConstrainedRounding (fp::RoundingMode NewRounding) inline
Set the rounding mode handling to be used with constrained floating point.
Definition at line 242 of file IRBuilder.h.
setDefaultFPMathTag()
void llvm::IRBuilderBase::setDefaultFPMathTag (MDNode * FPMathTag) inline
Set the floating point math metadata to be used.
Definition at line 222 of file IRBuilder.h.
setFastMathFlags()
void llvm::IRBuilderBase::setFastMathFlags (FastMathFlags NewFMF) inline
Set the fast-math flags to be used with generated fp-math operators.
Definition at line 225 of file IRBuilder.h.
Referenced by buildMultiplyTree(), llvm::createMinMaxOp(), createPowWithIntegerExponent(), llvm::createTargetReduction(), llvm::AMDGPULibCalls::fold(), FoldTwoEntryPHINode(), getMulHu(), HoistThenElseCodeToIf(), optimizeBinaryDoubleFP(), optimizeDoubleFP(), optimizeTrigReflections(), replaceUnaryCall(), shouldKeepFDivF32(), and llvm::InstCombiner::visitFDiv().
SetInsertPoint() [1/3]
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB) inline
This specifies that created instructions should be appended to the end of the specified block.
Definition at line 132 of file IRBuilder.h.
References llvm::BasicBlock::end().
Referenced by canonicalizeSaturatedAdd(), combineLoadToOperationType(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::createAMDGPUPrintfRuntimeBinding(), createFFSIntrinsic(), createResumeEntryBlock(), createRetPHINode(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), despeculateCountZeros(), llvm::orc::IRSpeculationLayer::emit(), emitSetAndGetSwiftErrorValueAround(), eraseDeadBBsAndChildren(), llvm::VPBasicBlock::execute(), llvm::VPlan::execute(), FitWeights(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixLCSSAPHIs(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), llvm::InnerLoopVectorizer::fixReduction(), llvm::AMDGPULibCalls::fold(), FoldTwoEntryPHINode(), generatedUnsignedRemainderCode(), generateSignedDivisionCode(), generateSignedRemainderCode(), llvm::InnerLoopVectorizer::getBroadcastInstrs(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), getScalarIntrinsicDeclaration(), getSignature(), INITIALIZE_PASS(), insertSinCosCall(), instrumentMaskedLoadOrStore(), isCallPromotable(), isKnownTypeIdMember(), isReInterleaveMask(), lowerLocalAllocas(), llvm::lowerObjectSizeCall(), lowerSubFn(), llvm::EscapeEnumerator::Next(), optimizeMemCmpConstantSize(), performMaskedAtomicOp(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), ReduceSwitchRange(), removeBitcastsFromLoadStoreOnMinMax(), removeUndefIntroducingPredecessor(), RetagMask(), setInsertionPoint(), llvm::SCEVExpander::setInsertPoint(), shouldKeepInEntry(), SimplifyCondBranchToTwoReturns(), SimplifyIndirectBrOnSelect(), splitMergedValStore(), SwitchToLookupTable(), TypeSizeToSizeIndex(), llvm::UpgradeIntrinsicCall(), visitIVCast(), and llvm::ObjectSizeOffsetEvaluator::visitPHINode().
SetInsertPoint() [2/3]
void llvm::IRBuilderBase::SetInsertPoint (Instruction * I) inline
This specifies that created instructions should be inserted before the specified instruction.
Definition at line 139 of file IRBuilder.h.
References assert(), llvm::BasicBlock::end(), llvm::Instruction::getDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), and llvm::Instruction::getParent().
SetInsertPoint() [3/3]
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB, BasicBlock::iterator IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 148 of file IRBuilder.h.
References llvm::BasicBlock::end().
SetInstDebugLocation()
void llvm::IRBuilderBase::SetInstDebugLocation (Instruction * I) const inline
If this builder has a current debug location, set it on the specified instruction.
Definition at line 163 of file IRBuilder.h.
References llvm::Instruction::setDebugLoc().
Referenced by createCallHelper(), createInvokeHelper(), and getCurrentFunctionReturnType().
setIsFPConstrained()
void llvm::IRBuilderBase::setIsFPConstrained (bool IsCon) inline
Enable/Disable use of constrained floating point math.
When enabled the CreateF<op>() calls instead create constrained floating point intrinsic calls. Fast math flags are unaffected by this setting.
Definition at line 231 of file IRBuilder.h.
Member Data Documentation
BB
BasicBlock* llvm::IRBuilderBase::BB protected
Definition at line 92 of file IRBuilder.h.
Referenced by CreateBinaryIntrinsic(), CreateElementUnorderedAtomicMemCpy(), CreateElementUnorderedAtomicMemMove(), CreateElementUnorderedAtomicMemSet(), CreateGCRelocate(), CreateGCResult(), CreateGlobalString(), CreateIntrinsic(), CreateInvariantStart(), CreateLifetimeEnd(), CreateLifetimeStart(), CreateMaskedStore(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), CreateUnaryIntrinsic(), and getCurrentFunctionReturnType().
Context
LLVMContext& llvm::IRBuilderBase::Context protected
Definition at line 94 of file IRBuilder.h.
Referenced by CreateGlobalString(), CreateMaskedGather(), and CreateMaskedScatter().
DefaultConstrainedExcept
fp::ExceptionBehavior llvm::IRBuilderBase::DefaultConstrainedExcept protected
Definition at line 100 of file IRBuilder.h.
DefaultConstrainedRounding
fp::RoundingMode llvm::IRBuilderBase::DefaultConstrainedRounding protected
Definition at line 101 of file IRBuilder.h.
DefaultFPMathTag
MDNode* llvm::IRBuilderBase::DefaultFPMathTag protected
Definition at line 96 of file IRBuilder.h.
Referenced by llvm::IRBuilderBase::FastMathFlagGuard::~FastMathFlagGuard().
DefaultOperandBundles
ArrayRef<OperandBundleDef> llvm::IRBuilderBase::DefaultOperandBundles protected
Definition at line 103 of file IRBuilder.h.
FMF
FastMathFlags llvm::IRBuilderBase::FMF protected
Definition at line 97 of file IRBuilder.h.
Referenced by CreateFPMaxReduce(), CreateFPMinReduce(), and llvm::IRBuilderBase::FastMathFlagGuard::~FastMathFlagGuard().
InsertPt
BasicBlock::iterator llvm::IRBuilderBase::InsertPt protected
Definition at line 93 of file IRBuilder.h.
Referenced by getCurrentFunctionReturnType().
IsFPConstrained
bool llvm::IRBuilderBase::IsFPConstrained protected
Definition at line 99 of file IRBuilder.h.
The documentation for this class was generated from the following files:
include/llvm/IR/IRBuilder.h
lib/IR/IRBuilder.cpp