LLVM: llvm::coverage::CoverageFilenamesSectionWriter Class Reference
llvm::coverage::CoverageFilenamesSectionWriter Class Reference
Writer of the filenames section for the instrumentation based code coverage.
#include "llvm/ProfileData/Coverage/CoverageMappingWriter.h"
Public Member Functions
CoverageFilenamesSectionWriter (ArrayRef< StringRef > Filenames)
void write (raw_ostream &OS)
Write encoded filenames to the given output stream.
Detailed Description
Writer of the filenames section for the instrumentation based code coverage.
Definition at line 29 of file CoverageMappingWriter.h.
Constructor & Destructor Documentation
CoverageFilenamesSectionWriter()
CoverageFilenamesSectionWriter::CoverageFilenamesSectionWriter (ArrayRef< StringRef > Filenames)
Definition at line 27 of file CoverageMappingWriter.cpp.
References assert(), llvm::StringSet< AllocatorTy >::insert(), and Name.
Member Function Documentation
write()
void CoverageFilenamesSectionWriter::write (raw_ostream & OS)
Write encoded filenames to the given output stream.
Definition at line 37 of file CoverageMappingWriter.cpp.
References C, E, llvm::encodeULEB128(), Expressions, llvm::coverage::Counter::getExpression(), llvm::coverage::Counter::getExpressionID(), I, llvm::coverage::Counter::isExpression(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), and llvm::ArrayRef< T >::size().
Referenced by llvm::coverage::CoverageMappingWriter::CoverageMappingWriter().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingWriter.h
lib/ProfileData/Coverage/CoverageMappingWriter.cpp