LLVM: llvm::PressureChange Class Reference
llvm::PressureChange Class Reference
Capture a change in pressure for a single pressure set.
#include "llvm/CodeGen/RegisterPressure.h"
Public Member Functions
PressureChange ()=default
PressureChange (unsigned id)
bool isValid () const
unsigned getPSet () const
unsigned getPSetOrMax () const
int getUnitInc () const
void setUnitInc (int Inc)
bool operator== (const PressureChange &RHS) const
void dump () const
Detailed Description
Capture a change in pressure for a single pressure set.
UnitInc may be expressed in terms of upward or downward pressure depending on the client and will be dynamically adjusted for current liveness.
Pressure increments are tiny, typically 1-2 units, and this is only for heuristics, so we don't check UnitInc overflow. Instead, we may have a higher level assert that pressure is consistent within a region. We also effectively ignore dead defs which don't affect heuristics much.
Definition at line 103 of file RegisterPressure.h.
Constructor & Destructor Documentation
PressureChange() [1/2]
llvm::PressureChange::PressureChange () default
PressureChange() [2/2]
llvm::PressureChange::PressureChange (unsigned id) inline
Definition at line 109 of file RegisterPressure.h.
References assert(), and llvm::max().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void PressureChange::dump () const
Definition at line 139 of file RegisterPressure.cpp.
References llvm::dbgs().
getPSet()
unsigned llvm::PressureChange::getPSet () const inline
Definition at line 115 of file RegisterPressure.h.
References assert().
Referenced by llvm::PressureDiff::addPressureChange(), computeLiveOuts(), llvm::PressureDiff::dump(), llvm::RegPressureTracker::getMaxUpwardPressureDelta(), llvm::GenericScheduler::initCandidate(), llvm::ConvergingVLIWScheduler::traceCandidate(), and llvm::GenericSchedulerBase::traceCandidate().
getPSetOrMax()
unsigned llvm::PressureChange::getPSetOrMax () const inline
Definition at line 121 of file RegisterPressure.h.
References llvm::max().
Referenced by llvm::tryPressure().
getUnitInc()
int llvm::PressureChange::getUnitInc () const inline
Definition at line 125 of file RegisterPressure.h.
Referenced by llvm::PressureDiff::addPressureChange(), computeLiveOuts(), llvm::PressureDiff::dump(), llvm::RegPressureTracker::getMaxDownwardPressureDelta(), llvm::RegPressureTracker::getMaxUpwardPressureDelta(), llvm::GenericScheduler::initCandidate(), llvm::GCNMaxOccupancySchedStrategy::initialize(), llvm::ConvergingVLIWScheduler::SchedulingCost(), llvm::ConvergingVLIWScheduler::traceCandidate(), llvm::GenericSchedulerBase::traceCandidate(), and llvm::tryPressure().
isValid()
bool llvm::PressureChange::isValid () const inline
Definition at line 113 of file RegisterPressure.h.
Referenced by llvm::PressureDiffs::addInstruction(), llvm::PressureDiff::addPressureChange(), computeLiveOuts(), computeMaxPressureDelta(), llvm::PressureDiff::dump(), llvm::RegPressureTracker::getMaxUpwardPressureDelta(), llvm::RegPressureTracker::getUpwardPressureDelta(), llvm::GenericScheduler::initCandidate(), llvm::ConvergingVLIWScheduler::traceCandidate(), llvm::GenericSchedulerBase::traceCandidate(), and llvm::tryPressure().
operator==()
bool llvm::PressureChange::operator== (const PressureChange & RHS) const inline
Definition at line 129 of file RegisterPressure.h.
References llvm::dump().
setUnitInc()
void llvm::PressureChange::setUnitInc (int Inc) inline
Definition at line 127 of file RegisterPressure.h.
Referenced by llvm::PressureDiff::addPressureChange(), computeExcessPressureDelta(), computeMaxPressureDelta(), llvm::RegPressureTracker::getUpwardPressureDelta(), and llvm::GCNMaxOccupancySchedStrategy::initialize().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterPressure.h
lib/CodeGen/RegisterPressure.cpp