LLVM: llvm::FunctionToLoopPassAdaptor< LoopPassT > Class Template Reference
llvm::FunctionToLoopPassAdaptor< LoopPassT > Class Template Reference
Adaptor that maps from a function to its loops.
#include "llvm/Transforms/Scalar/LoopPassManager.h"
Public Member Functions
FunctionToLoopPassAdaptor (LoopPassT Pass, bool UseMemorySSA=false, bool DebugLogging=false)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Runs the loop passes across every loop in the function.
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< FunctionToLoopPassAdaptor< LoopPassT > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
template<typename LoopPassT>
class llvm::FunctionToLoopPassAdaptor< LoopPassT >
Adaptor that maps from a function to its loops.
Designed to allow composition of a LoopPass(Manager) and a FunctionPassManager. Note that if this pass is constructed with a FunctionAnalysisManager it will run the LoopAnalysisManagerFunctionProxy analysis prior to running the loop passes over the function to enable a LoopAnalysisManager to be used within this run safely.
Definition at line 138 of file LoopPassManager.h.
Constructor & Destructor Documentation
FunctionToLoopPassAdaptor()
template<typename LoopPassT> llvm::FunctionToLoopPassAdaptor< LoopPassT >::FunctionToLoopPassAdaptor (LoopPassT Pass, bool UseMemorySSA = false, bool DebugLogging = false) inline explicit
Definition at line 266 of file LoopPassManager.h.
Member Function Documentation
run()
template<typename LoopPassT> PreservedAnalyses llvm::FunctionToLoopPassAdaptor< LoopPassT >::run (Function & F, FunctionAnalysisManager & AM) inline
Runs the loop passes across every loop in the function.
Definition at line 275 of file LoopPassManager.h.
References llvm::PreservedAnalyses::all(), llvm::internal::appendLoopsToWorklist(), assert(), llvm::PriorityWorklist< T, SmallVector< T, N >, SmallDenseMap< T, ptrdiff_t > >::empty(), F(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::Loop::isRecursivelyLCSSAForm(), Pass, llvm::PriorityWorklist< T, SmallVector< T, N >, SmallDenseMap< T, ptrdiff_t > >::pop_back_val(), llvm::reverse(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runAfterPassInvalidated(), llvm::PassInstrumentation::runBeforePass(), llvm::LPMUpdater::skipCurrentLoop(), and llvm::LoopBase< BlockT, LoopT >::verifyLoop().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Scalar/LoopPassManager.h