LLVM: llvm::ValueHandleBase Class Reference
llvm::ValueHandleBase Class Reference
This is the common base class of value handles.
#include "llvm/IR/ValueHandle.h"
Public Member Functions
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Static Public Member Functions
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types
enum HandleBaseKind { Assert, Callback, Weak, WeakTracking }
This indicates what sub class the handle actually is.
Protected Member Functions
ValueHandleBase (const ValueHandleBase &RHS)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
Value * getValPtr () const
void RemoveFromUseList ()
Remove this ValueHandle from its current use list.
void clearValPtr ()
Clear the underlying pointer without clearing the use list.
Static Protected Member Functions
static bool isValid (Value *V)
Friends
class Value
Detailed Description
This is the common base class of value handles.
ValueHandle's are smart pointers to Value's that have special behavior when the value is deleted or ReplaceAllUsesWith'd. See the specific handles below for details.
Definition at line 29 of file ValueHandle.h.
Member Enumeration Documentation
HandleBaseKind
enum llvm::ValueHandleBase::HandleBaseKind protected
This indicates what sub class the handle actually is.
This is to avoid having a vtable for the light-weight handle pointers. The fully general Callback version does have a vtable.
Enumerator
Assert
Callback
Weak
WeakTracking
Definition at line 37 of file ValueHandle.h.
Constructor & Destructor Documentation
ValueHandleBase() [1/4]
llvm::ValueHandleBase::ValueHandleBase (const ValueHandleBase & RHS) inline protected
Definition at line 39 of file ValueHandle.h.
ValueHandleBase() [2/4]
llvm::ValueHandleBase::ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase & RHS) inline protected
Definition at line 42 of file ValueHandle.h.
References getValPtr(), and isValid().
ValueHandleBase() [3/4]
llvm::ValueHandleBase::ValueHandleBase (HandleBaseKind Kind) inline explicit
Definition at line 56 of file ValueHandle.h.
ValueHandleBase() [4/4]
llvm::ValueHandleBase::ValueHandleBase (HandleBaseKind Kind, Value * V) inline
Definition at line 58 of file ValueHandle.h.
References getValPtr(), and isValid().
~ValueHandleBase()
llvm::ValueHandleBase::~ValueHandleBase () inline
Definition at line 64 of file ValueHandle.h.
References getValPtr(), isValid(), and RemoveFromUseList().
Member Function Documentation
clearValPtr()
void llvm::ValueHandleBase::clearValPtr () inline protected
Clear the underlying pointer without clearing the use list.
This should only be used if a derived class has manually removed the handle from the use list.
Definition at line 110 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer(), List, llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setPointer(), ValueIsDeleted(), and ValueIsRAUWd().
Referenced by llvm::PoisoningVH< llvm::BasicBlock >::operator=(), and llvm::PoisoningVH< llvm::BasicBlock >::~PoisoningVH().
getValPtr()
Value* llvm::ValueHandleBase::getValPtr () const inline protected
Definition at line 95 of file ValueHandle.h.
Referenced by llvm::cflaa::FunctionHandle< AAResult >::allUsesReplacedWith(), llvm::IVStrideUse::getUser(), llvm::DenseMapInfo< ValueMapCallbackVH< KeyT, ValueT, Config > >::isEqual(), llvm::WeakVH::operator Value *(), llvm::WeakTrackingVH::operator Value *(), llvm::CallbackVH::operator Value *(), llvm::AssertingVH< ValueTy >::operator ValueTy *(), llvm::TrackingVH< ValueTy >::operator ValueTy *(), llvm::PoisoningVH< ValueTy >::operator ValueTy *(), operator*(), llvm::AssertingVH< llvm::PHINode >::operator*(), llvm::TrackingVH< llvm::Value >::operator*(), llvm::PoisoningVH< llvm::BasicBlock >::operator*(), operator->(), llvm::AssertingVH< llvm::PHINode >::operator->(), llvm::TrackingVH< llvm::Value >::operator->(), llvm::PoisoningVH< llvm::BasicBlock >::operator->(), operator=(), llvm::AssertingVH< llvm::PHINode >::operator=(), llvm::TrackingVH< llvm::Value >::operator=(), llvm::WeakTrackingVH::pointsToAliveValue(), ValueHandleBase(), and ~ValueHandleBase().
isValid()
static bool llvm::ValueHandleBase::isValid (Value * V) inline static protected
Definition at line 97 of file ValueHandle.h.
References RemoveFromUseList().
Referenced by operator=(), llvm::WeakTrackingVH::pointsToAliveValue(), ValueHandleBase(), and ~ValueHandleBase().
operator*()
Value& llvm::ValueHandleBase::operator* () const inline
Definition at line 92 of file ValueHandle.h.
References getValPtr().
operator->()
Value* llvm::ValueHandleBase::operator-> () const inline
Definition at line 91 of file ValueHandle.h.
References getValPtr().
operator=() [1/2]
Value* llvm::ValueHandleBase::operator= (Value * RHS) inline
Definition at line 69 of file ValueHandle.h.
References getValPtr(), isValid(), and RemoveFromUseList().
Referenced by llvm::WeakVH::operator=(), llvm::WeakTrackingVH::operator=(), llvm::MMIAddrLabelMapCallbackPtr::setPtr(), llvm::CallbackVH::setValPtr(), llvm::WeakTrackingVH::WeakTrackingVH(), and llvm::WeakVH::WeakVH().
operator=() [2/2]
Value* llvm::ValueHandleBase::operator= (const ValueHandleBase & RHS) inline
Definition at line 80 of file ValueHandle.h.
References getValPtr(), isValid(), and RemoveFromUseList().
RemoveFromUseList()
void ValueHandleBase::RemoveFromUseList () protected
Remove this ValueHandle from its current use list.
Definition at line 845 of file Value.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::isPointerIntoBucketsArray(), and llvm::LLVMContextImpl::ValueHandles.
Referenced by isValid(), operator=(), and ~ValueHandleBase().
ValueIsDeleted()
void ValueHandleBase::ValueIsDeleted (Value * V) static
Definition at line 871 of file Value.cpp.
References assert(), Assert, llvm::Value::getContext(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValueHandles.
Referenced by annotateAnyAllocSite(), clearValPtr(), and llvm::Value::~Value().
ValueIsRAUWd()
void ValueHandleBase::ValueIsRAUWd (Value * Old, Value * New) static
Definition at line 924 of file Value.cpp.
References assert(), Assert, llvm::Value::getContext(), llvm::Value::getType(), and llvm::LLVMContext::pImpl.
Referenced by annotateAnyAllocSite(), clearValPtr(), contains(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::SSAUpdaterBulk::RewriteAllUses(), and llvm::SSAUpdater::RewriteUse().
Friends And Related Function Documentation
Value
friend class Value friend
Definition at line 30 of file ValueHandle.h.
The documentation for this class was generated from the following files:
include/llvm/IR/ValueHandle.h
lib/IR/Value.cpp