LLVM: llvm::LegalizationArtifactCombiner Class Reference
llvm::LegalizationArtifactCombiner Class Reference
#include "llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h"
Public Member Functions
LegalizationArtifactCombiner (MachineIRBuilder &B, MachineRegisterInfo &MRI, const LegalizerInfo &LI)
bool tryCombineAnyExt (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryCombineZExt (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryCombineSExt (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryCombineTrunc (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryFoldImplicitDef (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
Try to fold G_[ASZ]EXT (G_IMPLICIT_DEF).
bool tryCombineMerges (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryCombineExtract (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryCombineInstruction (MachineInstr &MI, SmallVectorImpl< MachineInstr *> &DeadInsts, GISelObserverWrapper &WrapperObserver)
Try to combine away MI.
Static Public Member Functions
static bool canFoldMergeOpcode (unsigned MergeOp, unsigned ConvertOp, LLT OpTy, LLT DestTy)
static bool isMergeLikeOpcode (unsigned Opc)
Detailed Description
Definition at line 26 of file LegalizationArtifactCombiner.h.
Constructor & Destructor Documentation
LegalizationArtifactCombiner()
llvm::LegalizationArtifactCombiner::LegalizationArtifactCombiner (MachineIRBuilder & B, MachineRegisterInfo & MRI, const LegalizerInfo & LI) inline
Definition at line 44 of file LegalizationArtifactCombiner.h.
Member Function Documentation
canFoldMergeOpcode()
static bool llvm::LegalizationArtifactCombiner::canFoldMergeOpcode (unsigned MergeOp, unsigned ConvertOp, LLT OpTy, LLT DestTy) inline static
Definition at line 232 of file LegalizationArtifactCombiner.h.
References llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), and llvm::LLT::isVector().
isMergeLikeOpcode()
static bool llvm::LegalizationArtifactCombiner::isMergeLikeOpcode (unsigned Opc) inline static
Definition at line 409 of file LegalizationArtifactCombiner.h.
tryCombineAnyExt()
bool llvm::LegalizationArtifactCombiner::tryCombineAnyExt (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 48 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineIRBuilder::buildAnyExtOrTrunc(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), LLVM_DEBUG, llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GAnyExt(), llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::mi_match(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::MachineIRBuilder::setInstr().
tryCombineExtract()
bool llvm::LegalizationArtifactCombiner::tryCombineExtract (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 420 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::MachineIRBuilder::setInstr().
tryCombineInstruction()
bool llvm::LegalizationArtifactCombiner::tryCombineInstruction (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, GISelObserverWrapper & WrapperObserver) inline
Try to combine away MI.
Returns true if it combined away the MI. Adds instructions that are dead as a result of the combine into DeadInsts, which can include MI.
Definition at line 473 of file LegalizationArtifactCombiner.h.
References llvm::LegalizeActionStep::Action, assert(), llvm::GISelObserverWrapper::changedInstr(), llvm::dbgs(), DefMI, llvm::SmallVectorBase::empty(), llvm::GISelObserverWrapper::erasingInstr(), llvm::LegalizerInfo::getAction(), llvm::LLT::getElementType(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), llvm::LLT::isValid(), llvm::LLT::isVector(), llvm::Register::isVirtual(), llvm::LegalizeActions::Legal, LLVM_DEBUG, llvm_unreachable, llvm::MIPatternMatch::m_Copy(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), llvm::LegalizeActions::NotFound, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::LegalizeActions::Unsupported, and llvm::MachineRegisterInfo::use_instructions().
Referenced by llvm::Legalizer::legalizeMachineFunction().
tryCombineMerges()
bool llvm::LegalizationArtifactCombiner::tryCombineMerges (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 283 of file LegalizationArtifactCombiner.h.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::getDefIgnoringCopies(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineRegisterInfo::replaceRegWith(), and llvm::MachineIRBuilder::setInstr().
Referenced by combineAwayG_UNMERGE_VALUES().
tryCombineSExt()
bool llvm::LegalizationArtifactCombiner::tryCombineSExt (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 141 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineIRBuilder::buildAnyExtOrTrunc(), llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), LLVM_DEBUG, llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::mi_match(), and llvm::MachineIRBuilder::setInstr().
tryCombineTrunc()
bool llvm::LegalizationArtifactCombiner::tryCombineTrunc (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 168 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::MachineIRBuilder::setInstr().
tryCombineZExt()
bool llvm::LegalizationArtifactCombiner::tryCombineZExt (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 97 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildAnyExtOrTrunc(), llvm::MachineIRBuilder::buildConstant(), llvm::dbgs(), llvm::APInt::getAllOnesValue(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), LLVM_DEBUG, llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::BitmaskEnumDetail::Mask(), llvm::MIPatternMatch::mi_match(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineIRBuilder::setInstr(), and llvm::APInt::zext().
tryFoldImplicitDef()
bool llvm::LegalizationArtifactCombiner::tryFoldImplicitDef (MachineInstr & MI, SmallVectorImpl< MachineInstr *> & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Try to fold G_[ASZ]EXT (G_IMPLICIT_DEF).
Definition at line 196 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), DefMI, llvm::MachineInstr::getOpcode(), llvm::getOpcodeDef(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), LLVM_DEBUG, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::MachineIRBuilder::setInstr().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h