LLVM: llvm::CFLSteensAAResult Class Reference
llvm::CFLSteensAAResult Class Reference
#include "llvm/Analysis/CFLSteensAliasAnalysis.h"
Classes
class FunctionInfo
Information we have about a function and would like to keep around.
Public Member Functions
CFLSteensAAResult (std::function< const TargetLibraryInfo &(Function &)> GetTLI)
CFLSteensAAResult (CFLSteensAAResult &&Arg)
~CFLSteensAAResult ()
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Handle invalidation events from the new pass manager.
void scan (Function *Fn)
Inserts the given Function into the cache.
void evict (Function *Fn)
const Optional< FunctionInfo > & ensureCached (Function *Fn)
Ensures that the given function is available in the cache.
const cflaa::AliasSummary * getAliasSummary (Function &Fn)
Get the alias summary for the given function Return nullptr if the summary is not found or not available.
AliasResult query (const MemoryLocation &LocA, const MemoryLocation &LocB)
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
Public Member Functions inherited from llvm::AAResultBase< CFLSteensAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< CFLSteensAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
Definition at line 39 of file CFLSteensAliasAnalysis.h.
Constructor & Destructor Documentation
CFLSteensAAResult() [1/2]
llvm::CFLSteensAAResult::CFLSteensAAResult (std::function< const TargetLibraryInfo &(Function &)> GetTLI) explicit
CFLSteensAAResult() [2/2]
CFLSteensAAResult::CFLSteensAAResult (CFLSteensAAResult && Arg)
Definition at line 67 of file CFLSteensAliasAnalysis.cpp.
References ~CFLSteensAAResult().
~CFLSteensAAResult()
CFLSteensAAResult::~CFLSteensAAResult () default
Referenced by CFLSteensAAResult().
Member Function Documentation
alias()
AliasResult llvm::CFLSteensAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI) inline
Definition at line 73 of file CFLSteensAliasAnalysis.h.
References llvm::AAResultBase< DerivedT >::alias(), F(), llvm::MayAlias, llvm::MustAlias, llvm::MemoryLocation::Ptr, and query().
ensureCached()
const Optional< CFLSteensAAResult::FunctionInfo > & CFLSteensAAResult::ensureCached (Function * Fn)
Ensures that the given function is available in the cache.
Ensures that the given function is available in the cache, and returns the entry.
Returns the appropriate entry from the cache.
Definition at line 247 of file CFLSteensAliasAnalysis.cpp.
References assert(), and scan().
evict()
void CFLSteensAAResult::evict (Function * Fn)
Definition at line 242 of file CFLSteensAliasAnalysis.cpp.
getAliasSummary()
const AliasSummary * CFLSteensAAResult::getAliasSummary (Function & Fn)
Get the alias summary for the given function Return nullptr if the summary is not found or not available.
Definition at line 258 of file CFLSteensAliasAnalysis.cpp.
invalidate()
bool llvm::CFLSteensAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 53 of file CFLSteensAliasAnalysis.h.
References query(), and scan().
query()
AliasResult CFLSteensAAResult::query (const MemoryLocation & LocA, const MemoryLocation & LocB)
Definition at line 266 of file CFLSteensAliasAnalysis.cpp.
References assert(), llvm::dbgs(), llvm::cflaa::StratifiedSets< T >::find(), llvm::cflaa::hasUnknownOrCallerAttr(), llvm::cflaa::isGlobalOrArgAttr(), LLVM_DEBUG, llvm::MayAlias, llvm::NoAlias, llvm::cflaa::parentFunctionOfValue(), and llvm::MemoryLocation::Ptr.
scan()
void CFLSteensAAResult::scan (Function * Fn)
Inserts the given Function into the cache.
Definition at line 227 of file CFLSteensAliasAnalysis.cpp.
References assert().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CFLSteensAliasAnalysis.h
lib/Analysis/CFLSteensAliasAnalysis.cpp