LLVM: llvm::GCNTargetMachine Class Reference
llvm::GCNTargetMachine Class Reference final
#include "Target/AMDGPU/AMDGPUTargetMachine.h"
Public Member Functions
GCNTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
const GCNSubtarget * getSubtargetImpl (const Function &) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
TargetTransformInfo getTargetTransformInfo (const Function &F) override
Get a TargetTransformInfo implementation for the target.
bool useIPRA () const override
True if the target wants to use interprocedural register allocation by default.
yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const override
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const override
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const override
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
Public Member Functions inherited from llvm::AMDGPUTargetMachine
AMDGPUTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL)
~AMDGPUTargetMachine () override
const TargetSubtargetInfo * getSubtargetImpl () const
TargetLoweringObjectFile * getObjFileLowering () const override
void adjustPassManager (PassManagerBuilder &) override
Allow the target to modify the pass manager, e.g.
uint64_t getNullPointerValue (unsigned AddrSpace) const
Get the integer value of a null pointer in the given address space.
Public Member Functions inherited from llvm::LLVMTargetMachine
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
virtual bool isMachineVerifierClean () const
Returns true if the target is expected to pass all machine verifier checks.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context)
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
virtual bool usesPhysRegsForPEI () const
True if the target uses physical regs at Prolog/Epilog insertion time.
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const Module &M, const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOpt::Level getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOpt::Level Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
bool shouldPrintMachineCode () const
bool getUniqueSectionNames () const
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
TargetIRAnalysis getTargetIRAnalysis ()
Get a TargetIRAnalysis appropriate for the target.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
Additional Inherited Members
Public Attributes inherited from llvm::TargetMachine
const TargetOptions DefaultOptions
TargetOptions Options
Static Public Attributes inherited from llvm::AMDGPUTargetMachine
static bool EnableLateStructurizeCFG = false
static bool EnableFunctionCalls = false
Protected Member Functions inherited from llvm::AMDGPUTargetMachine
StringRef getGPUName (const Function &F) const
StringRef getFeatureString (const Function &F) const
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::AMDGPUTargetMachine
std::unique_ptr< TargetLoweringObjectFile > TLOF
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
CodeGenOpt::Level OptLevel = CodeGenOpt::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
Detailed Description
Definition at line 94 of file AMDGPUTargetMachine.h.
Constructor & Destructor Documentation
GCNTargetMachine()
GCNTargetMachine::GCNTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
Definition at line 503 of file AMDGPUTargetMachine.cpp.
Member Function Documentation
convertFuncInfoToYAML()
yaml::MachineFunctionInfo * GCNTargetMachine::convertFuncInfoToYAML (const MachineFunction & MF) const override virtual
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
Reimplemented from llvm::TargetMachine.
Definition at line 1009 of file AMDGPUTargetMachine.cpp.
References llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
createDefaultFuncInfoYAML()
yaml::MachineFunctionInfo * GCNTargetMachine::createDefaultFuncInfoYAML () const override virtual
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
Reimplemented from llvm::TargetMachine.
Definition at line 1004 of file AMDGPUTargetMachine.cpp.
createPassConfig()
TargetPassConfig * GCNTargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 1000 of file AMDGPUTargetMachine.cpp.
getSubtargetImpl()
const GCNSubtarget * GCNTargetMachine::getSubtargetImpl (const Function &) const override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Implements llvm::AMDGPUTargetMachine.
Definition at line 511 of file AMDGPUTargetMachine.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::X86AS::FS, llvm::AMDGPUTargetMachine::getFeatureString(), llvm::AMDGPUTargetMachine::getGPUName(), I, llvm::TargetMachine::resetTargetOptions(), ScalarizeGlobal, and llvm::TargetMachine::TargetTriple.
getTargetTransformInfo()
TargetTransformInfo GCNTargetMachine::getTargetTransformInfo (const Function & F) override virtual
Get a TargetTransformInfo implementation for the target.
The TTI returned uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 533 of file AMDGPUTargetMachine.cpp.
References llvm::AAResults::addAAResult(), llvm::TargetPassConfig::addCodeGenPrepare(), llvm::TargetPassConfig::addIRPasses(), llvm::ScheduleDAGMI::addMutation(), llvm::CodeGenOpt::Aggressive, llvm::Triple::amdgcn, llvm::AMDGPUPerfHintAnalysisID, C, llvm::createAlwaysInlinerLegacyPass(), llvm::createAMDGPUAAWrapperPass(), llvm::createAMDGPUAlwaysInlinePass(), llvm::createAMDGPUAnnotateKernelFeaturesPass(), llvm::createAMDGPUCFGStructurizerPass(), llvm::createAMDGPUCodeGenPreparePass(), llvm::createAMDGPUFixFunctionBitcastsPass(), llvm::createAMDGPUISelDag(), llvm::createAMDGPULowerIntrinsicsPass(), llvm::createAMDGPULowerKernelArgumentsPass(), llvm::createAMDGPUOpenCLEnqueuedBlockLoweringPass(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createAMDGPUPromoteAlloca(), llvm::createAMDGPUPropagateAttributesEarlyPass(), llvm::createAtomicExpandPass(), llvm::createBarrierNoopPass(), llvm::createEarlyCSEPass(), llvm::createExternalAAWrapperPass(), llvm::createFlattenCFGPass(), llvm::createGenericSchedLive(), llvm::createGVNPass(), llvm::createInferAddressSpacesPass(), llvm::createLICMPass(), llvm::createLoadClusterDAGMutation(), llvm::createLoadStoreVectorizerPass(), llvm::createLowerSwitchPass(), llvm::createNaryReassociatePass(), llvm::createR600ClauseMergePass(), llvm::createR600ControlFlowFinalizer(), llvm::createR600EmitClauseMarkers(), llvm::createR600ExpandSpecialInstrsPass(), llvm::createR600ISelDag(), createR600MachineScheduler(), llvm::createR600OpenCLImageTypeLoweringPass(), llvm::createR600Packetizer(), llvm::createR600VectorRegMerger(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createSpeculativeExecutionPass(), llvm::createSROAPass(), llvm::createStoreClusterDAGMutation(), llvm::createStraightLineStrengthReducePass(), llvm::createStructurizeCFGPass(), EnableAMDGPUAliasAnalysis, EnableLoadStoreVectorizer, EnableLowerKernelArguments, EnableR600IfConvert, EnableR600StructurizeCFG, EnableScalarIRPasses, EnableSROA, llvm::FinalizeMachineBundlesID, llvm::FuncletLayoutID, llvm::Pass::getAnalysisIfAvailable(), llvm::Triple::getArch(), llvm::TargetMachine::getOptLevel(), llvm::getStandardCSEConfigForOpt(), llvm::TargetMachine::getTargetTriple(), llvm::IfConverterID, llvm::CodeGenOpt::None, P, llvm::PatchableFunctionID, llvm::Triple::r600, llvm::StackMapLivenessID, llvm::ScheduleDAG::TII, llvm::SystemZISD::TM, and llvm::ScheduleDAG::TRI.
parseMachineFunctionInfo()
bool GCNTargetMachine::parseMachineFunctionInfo (const yaml::MachineFunctionInfo & , PerFunctionMIParsingState & PFS, SMDiagnostic & Error, SMRange & SourceRange) const override virtual
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
Reimplemented from llvm::TargetMachine.
Definition at line 1015 of file AMDGPUTargetMachine.cpp.
References Arg, llvm::yaml::SIMachineFunctionInfo::ArgInfo, llvm::ArgDescriptor::createArg(), llvm::ArgDescriptor::createRegister(), llvm::ArgDescriptor::createStack(), llvm::AMDGPUFunctionArgInfo::DispatchID, llvm::AMDGPUFunctionArgInfo::DispatchPtr, llvm::SourceMgr::DK_Error, llvm::yaml::SIMode::DX10Clamp, llvm::AMDGPU::SIModeRegisterDefaults::DX10Clamp, llvm::AMDGPUFunctionArgInfo::FlatScratchInit, llvm::yaml::SIMode::FP32Denormals, llvm::AMDGPU::SIModeRegisterDefaults::FP32Denormals, llvm::yaml::SIMode::FP64FP16Denormals, llvm::AMDGPU::SIModeRegisterDefaults::FP64FP16Denormals, llvm::yaml::SIMachineFunctionInfo::FrameOffsetReg, llvm::MemoryBuffer::getBufferIdentifier(), llvm::MachineFunction::getInfo(), llvm::SourceMgr::getMainFileID(), llvm::SourceMgr::getMemoryBuffer(), llvm::Optional< T >::getValue(), llvm::yaml::SIMode::IEEE, llvm::AMDGPU::SIModeRegisterDefaults::IEEE, llvm::AMDGPUFunctionArgInfo::ImplicitArgPtr, llvm::AMDGPUFunctionArgInfo::ImplicitBufferPtr, llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), llvm::yaml::SIArgument::IsRegister, llvm::AMDGPUFunctionArgInfo::KernargSegmentPtr, llvm::yaml::SIArgument::Mask, llvm::PerFunctionMIParsingState::MF, llvm::AMDGPUMachineFunction::Mode, llvm::yaml::SIMachineFunctionInfo::Mode, llvm::None, llvm::parseNamedRegisterReference(), llvm::AMDGPUFunctionArgInfo::PrivateSegmentBuffer, llvm::AMDGPUFunctionArgInfo::PrivateSegmentSize, llvm::AMDGPUFunctionArgInfo::PrivateSegmentWaveByteOffset, llvm::AMDGPUFunctionArgInfo::QueuePtr, Reg, llvm::yaml::SIArgument::RegisterName, llvm::yaml::SIMachineFunctionInfo::ScratchRSrcReg, llvm::yaml::SIMachineFunctionInfo::ScratchWaveOffsetReg, llvm::PerFunctionMIParsingState::SM, llvm::yaml::StringValue::SourceRange, llvm::yaml::SIArgument::StackOffset, llvm::yaml::SIMachineFunctionInfo::StackPtrOffsetReg, llvm::yaml::StringValue::Value, llvm::AMDGPUFunctionArgInfo::WorkGroupIDX, llvm::AMDGPUFunctionArgInfo::WorkGroupIDY, llvm::AMDGPUFunctionArgInfo::WorkGroupIDZ, llvm::AMDGPUFunctionArgInfo::WorkGroupInfo, llvm::AMDGPUFunctionArgInfo::WorkItemIDX, llvm::AMDGPUFunctionArgInfo::WorkItemIDY, and llvm::AMDGPUFunctionArgInfo::WorkItemIDZ.
useIPRA()
bool llvm::GCNTargetMachine::useIPRA () const inline override virtual
True if the target wants to use interprocedural register allocation by default.
The -enable-ipra flag can be used to override this.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 110 of file AMDGPUTargetMachine.h.
References llvm::TargetMachine::convertFuncInfoToYAML(), llvm::TargetMachine::createDefaultFuncInfoYAML(), and llvm::TargetMachine::parseMachineFunctionInfo().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUTargetMachine.h
lib/Target/AMDGPU/AMDGPUTargetMachine.cpp