LLVM: llvm::CachedHashStringRef Class Reference
llvm::CachedHashStringRef Class Reference
A container which contains a StringRef plus a precomputed hash.
#include "llvm/ADT/CachedHashString.h"
Public Member Functions
CachedHashStringRef (StringRef S)
CachedHashStringRef (StringRef S, uint32_t Hash)
StringRef val () const
const char * data () const
uint32_t size () const
uint32_t hash () const
Detailed Description
A container which contains a StringRef plus a precomputed hash.
Definition at line 29 of file CachedHashString.h.
Constructor & Destructor Documentation
CachedHashStringRef() [1/2]
llvm::CachedHashStringRef::CachedHashStringRef (StringRef S) inline explicit
Definition at line 36 of file CachedHashString.h.
Referenced by llvm::DenseMapInfo< CachedHashStringRef >::getEmptyKey(), llvm::DenseMapInfo< CachedHashStringRef >::getTombstoneKey(), and llvm::CachedHashString::operator CachedHashStringRef().
CachedHashStringRef() [2/2]
llvm::CachedHashStringRef::CachedHashStringRef (StringRef S, uint32_t Hash) inline
Definition at line 39 of file CachedHashString.h.
References assert(), llvm::max(), and llvm::StringRef::size().
Member Function Documentation
data()
const char* llvm::CachedHashStringRef::data () const inline
Definition at line 45 of file CachedHashString.h.
hash()
uint32_t llvm::CachedHashStringRef::hash () const inline
Definition at line 47 of file CachedHashString.h.
Referenced by llvm::DenseMapInfo< CachedHashStringRef >::getHashValue(), and llvm::DenseMapInfo< CachedHashStringRef >::isEqual().
size()
uint32_t llvm::CachedHashStringRef::size () const inline
Definition at line 46 of file CachedHashString.h.
Referenced by llvm::StringTableBuilder::add().
val()
StringRef llvm::CachedHashStringRef::val () const inline
Definition at line 44 of file CachedHashString.h.
Referenced by llvm::DenseMapInfo< CachedHashStringRef >::isEqual(), llvm::CachedHashString::operator CachedHashStringRef(), and llvm::CachedHashString::operator StringRef().
The documentation for this class was generated from the following file:
include/llvm/ADT/CachedHashString.h