LLVM: llvm::CrashRecoveryContext Class Reference
llvm::CrashRecoveryContext Class Reference
Crash recovery helper object.
#include "llvm/Support/CrashRecoveryContext.h"
Public Member Functions
CrashRecoveryContext ()
~CrashRecoveryContext ()
void registerCleanup (CrashRecoveryContextCleanup *cleanup)
Register cleanup handler, which is used when the recovery context is finished.
void unregisterCleanup (CrashRecoveryContextCleanup *cleanup)
bool RunSafely (function_ref< void()> Fn)
Execute the provided callback function (with the given arguments) in a protected context.
bool RunSafely (void(*Fn)(void *), void *UserData)
bool RunSafelyOnThread (function_ref< void()>, unsigned RequestedStackSize=0)
Execute the provide callback function (with the given arguments) in a protected context which is run in another thread (optionally with a requested stack size).
bool RunSafelyOnThread (void(*Fn)(void *), void *UserData, unsigned RequestedStackSize=0)
LLVM_ATTRIBUTE_NORETURN void HandleExit (int RetCode)
Explicitly trigger a crash recovery in the current process, and return failure from RunSafely().
Static Public Member Functions
static void Enable ()
Enable crash recovery.
static void Disable ()
Disable crash recovery.
static CrashRecoveryContext * GetCurrent ()
Return the active context, if the code is currently executing in a thread which is in a protected context.
static bool isRecoveringFromCrash ()
Return true if the current thread is recovering from a crash.
Public Attributes
int RetCode = 0
In case of a crash, this is the crash identifier.
bool DumpStackAndCleanupOnFailure = false
Selects whether handling of failures should be done in the same way as for regular crashes.
Detailed Description
Crash recovery helper object.
This class implements support for running operations in a safe context so that crashes (memory errors, stack overflow, assertion violations) can be detected and control restored to the crashing thread. Crash detection is purely "best effort", the exact set of failures which can be recovered from is platform dependent.
Clients make use of this code by first calling CrashRecoveryContext::Enable(), and then executing unsafe operations via a CrashRecoveryContext object. For example:
void actual_work(void *);
void foo() {
  CrashRecoveryContext CRC;
  if (!CRC.RunSafely(actual_work, 0)) {
     ... a crash was detected, report error to user ...
  }
  ... no crash was detected ...
}
To assist recovery the class allows specifying set of actions that will be executed in any case, whether crash occurs or not. These actions may be used to reclaim resources in the case of crash.
Definition at line 46 of file CrashRecoveryContext.h.
Constructor & Destructor Documentation
CrashRecoveryContext()
llvm::CrashRecoveryContext::CrashRecoveryContext () inline
Definition at line 51 of file CrashRecoveryContext.h.
References cleanup(), Disable(), Enable(), GetCurrent(), isRecoveringFromCrash(), registerCleanup(), RunSafely(), unregisterCleanup(), and ~CrashRecoveryContext().
~CrashRecoveryContext()
CrashRecoveryContext::~CrashRecoveryContext ()
Definition at line 100 of file CrashRecoveryContext.cpp.
References llvm::CrashRecoveryContextCleanup::cleanupFired, llvm::CrashRecoveryContextCleanup::recoverResources(), and tlIsRecoveringFromCrash.
Referenced by CrashRecoveryContext().
Member Function Documentation
Disable()
void CrashRecoveryContext::Disable () static
Disable crash recovery.
Definition at line 142 of file CrashRecoveryContext.cpp.
References uninstallExceptionOrSignalHandlers().
Referenced by CrashRecoveryContext(), CrashRecoverySignalHandler(), and unregisterCleanup().
Enable()
void CrashRecoveryContext::Enable () static
Enable crash recovery.
Definition at line 133 of file CrashRecoveryContext.cpp.
References installExceptionOrSignalHandlers().
Referenced by CrashRecoveryContext().
GetCurrent()
CrashRecoveryContext * CrashRecoveryContext::GetCurrent () static
Return the active context, if the code is currently executing in a thread which is in a protected context.
Definition at line 122 of file CrashRecoveryContext.cpp.
Referenced by CrashRecoveryContext(), llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >::create(), and llvm::sys::Process::Exit().
HandleExit()
LLVM_ATTRIBUTE_NORETURN void CrashRecoveryContext::HandleExit (int RetCode)
Explicitly trigger a crash recovery in the current process, and return failure from RunSafely().
This function does not return.
Definition at line 425 of file CrashRecoveryContext.cpp.
References assert(), and llvm_unreachable.
Referenced by RunSafelyOnThread().
isRecoveringFromCrash()
bool CrashRecoveryContext::isRecoveringFromCrash () static
Return true if the current thread is recovering from a crash.
Definition at line 118 of file CrashRecoveryContext.cpp.
References tlIsRecoveringFromCrash.
Referenced by CrashRecoveryContext().
registerCleanup()
void CrashRecoveryContext::registerCleanup (CrashRecoveryContextCleanup * cleanup)
Register cleanup handler, which is used when the recovery context is finished.
The recovery context owns the handler.
Definition at line 150 of file CrashRecoveryContext.cpp.
References cleanup().
Referenced by CrashRecoveryContext(), and llvm::CrashRecoveryContextCleanupRegistrar< T, Cleanup >::CrashRecoveryContextCleanupRegistrar().
RunSafely() [1/2]
bool CrashRecoveryContext::RunSafely (function_ref< void()> Fn)
Execute the provided callback function (with the given arguments) in a protected context.
Returns
True if the function completed successfully, and false if the function crashed (or HandleCrash was called explicitly). Clients should make as little assumptions as possible about the program state when RunSafely has returned false.
Definition at line 405 of file CrashRecoveryContext.cpp.
References assert(), and LLVM_ATTRIBUTE_NORETURN.
Referenced by CrashRecoveryContext(), RunSafely(), and unregisterCleanup().
RunSafely() [2/2]
bool llvm::CrashRecoveryContext::RunSafely (void(*)(void *) Fn, void * UserData) inline
Definition at line 82 of file CrashRecoveryContext.h.
References RunSafely(), and RunSafelyOnThread().
RunSafelyOnThread() [1/2]
bool CrashRecoveryContext::RunSafelyOnThread (function_ref< void()> Fn, unsigned RequestedStackSize = 0)
Execute the provide callback function (with the given arguments) in a protected context which is run in another thread (optionally with a requested stack size).
See RunSafely() and llvm_execute_on_thread().
On Darwin, if PRIO_DARWIN_BG is set on the calling thread, it will be propagated to the new thread as well.
Definition at line 472 of file CrashRecoveryContext.cpp.
References hasThreadBackgroundPriority(), Info, llvm::llvm_execute_on_thread(), llvm::None, and RunSafelyOnThread_Dispatch().
Referenced by RunSafely(), and RunSafelyOnThread().
RunSafelyOnThread() [2/2]
bool llvm::CrashRecoveryContext::RunSafelyOnThread (void(*)(void *) Fn, void * UserData, unsigned RequestedStackSize = 0) inline
Definition at line 95 of file CrashRecoveryContext.h.
References HandleExit(), LLVM_ATTRIBUTE_NORETURN, RetCode, and RunSafelyOnThread().
unregisterCleanup()
void CrashRecoveryContext::unregisterCleanup (CrashRecoveryContextCleanup * cleanup)
Definition at line 161 of file CrashRecoveryContext.cpp.
References assert(), cleanup(), Disable(), llvm::sys::ThreadLocal< T >::get(), if(), installExceptionOrSignalHandlers(), llvm_unreachable, RunSafely(), llvm::sys::ThreadLocal< T >::set(), and uninstallExceptionOrSignalHandlers().
Referenced by CrashRecoveryContext(), and llvm::CrashRecoveryContextCleanupRegistrar< T, Cleanup >::unregister().
Member Data Documentation
DumpStackAndCleanupOnFailure
bool llvm::CrashRecoveryContext::DumpStackAndCleanupOnFailure = false
Selects whether handling of failures should be done in the same way as for regular crashes.
When this is active, a crash would print the callstack, clean-up any temporary files and create a coredump/minidump.
Definition at line 111 of file CrashRecoveryContext.h.
RetCode
int llvm::CrashRecoveryContext::RetCode = 0
In case of a crash, this is the crash identifier.
Definition at line 106 of file CrashRecoveryContext.h.
Referenced by RunSafelyOnThread().
The documentation for this class was generated from the following files:
include/llvm/Support/CrashRecoveryContext.h
lib/Support/CrashRecoveryContext.cpp