LLVM: llvm::MCStreamer Class Reference
llvm::MCStreamer Class Reference abstract
Streaming machine code generation interface.
#include "llvm/MC/MCStreamer.h"
Public Member Functions
MCStreamer (const MCStreamer &)=delete
MCStreamer & operator= (const MCStreamer &)=delete
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
virtual void visitUsedSymbol (const MCSymbol &Sym)
void setTargetStreamer (MCTargetStreamer *TS)
virtual void reset ()
State management.
MCContext & getContext () const
virtual MCAssembler * getAssemblerPtr ()
void setUseAssemblerInfoForParsing (bool v)
bool getUseAssemblerInfoForParsing ()
MCTargetStreamer * getTargetStreamer ()
void setAllowAutoPadding (bool v)
bool getAllowAutoPadding () const
virtual MCSymbol * EmitCFILabel ()
When emitting an object file, create and emit a real label.
WinEH::FrameInfo * EnsureValidWinFrameInfo (SMLoc Loc)
Retreive the current frame info if one is available and it is not yet closed.
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
bool hasUnfinishedDwarfFrameInfo ()
unsigned getNumWinFrameInfos ()
ArrayRef< std::unique_ptr< WinEH::FrameInfo > > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual void EmitFileDirective (StringRef Filename)
Switch to a new logical file.
virtual void EmitIdent (StringRef IdentString)
Emit the "identifiers" directive.
unsigned EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual Expected< unsigned > tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual void emitDwarfFile0Directive (StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, unsigned CUID=0)
Specify the "root" file of the compilation, using the ".file 0" extension.
virtual void EmitCFIBKeyFrame ()
virtual void EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName)
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
virtual bool EmitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind)
Associate a filename with a specified logical file number, and also specify that file's checksum information.
virtual bool EmitCVFuncIdDirective (unsigned FunctionId)
Introduces a function id for use with .cv_loc.
virtual bool EmitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc)
Introduces an inline call site id for use with .cv_loc.
virtual void EmitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc)
This implements the CodeView '.cv_loc' assembler directive.
virtual void EmitCVLinetableDirective (unsigned FunctionId, const MCSymbol *FnStart, const MCSymbol *FnEnd)
This implements the CodeView '.cv_linetable' assembler directive.
virtual void EmitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym)
This implements the CodeView '.cv_inline_linetable' assembler directive.
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, StringRef FixedSizePortion)
This implements the CodeView '.cv_def_range' assembler directive.
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeRegisterRelHeader DRHdr)
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr)
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeRegisterHeader DRHdr)
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeFramePointerRelHeader DRHdr)
virtual void EmitCVStringTableDirective ()
This implements the CodeView '.cv_stringtable' assembler directive.
virtual void EmitCVFileChecksumsDirective ()
This implements the CodeView '.cv_filechecksums' assembler directive.
virtual void EmitCVFileChecksumOffsetDirective (unsigned FileNo)
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
virtual void EmitCVFPOData (const MCSymbol *ProcSym, SMLoc Loc={})
This implements the CodeView '.cv_fpo_data' assembler directive.
virtual void emitAbsoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size)
Emit the absolute difference between two symbols.
virtual void emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo)
Emit the absolute difference between two symbols encoded with ULEB128.
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
virtual void EmitCFISections (bool EH, bool Debug)
void EmitCFIStartProc (bool IsSimple, SMLoc Loc=SMLoc())
void EmitCFIEndProc ()
virtual void EmitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void EmitCFIDefCfaOffset (int64_t Offset)
virtual void EmitCFIDefCfaRegister (int64_t Register)
virtual void EmitCFIOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFIRememberState ()
virtual void EmitCFIRestoreState ()
virtual void EmitCFISameValue (int64_t Register)
virtual void EmitCFIRestore (int64_t Register)
virtual void EmitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void EmitCFIEscape (StringRef Values)
virtual void EmitCFIReturnColumn (int64_t Register)
virtual void EmitCFIGnuArgsSize (int64_t Size)
virtual void EmitCFISignalFrame ()
virtual void EmitCFIUndefined (int64_t Register)
virtual void EmitCFIRegister (int64_t Register1, int64_t Register2)
virtual void EmitCFIWindowSave ()
virtual void EmitCFINegateRAState ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProc (SMLoc Loc=SMLoc())
virtual void EmitWinCFIFuncletOrFuncEnd (SMLoc Loc=SMLoc())
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
virtual void EmitWinCFIStartChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushReg (MCRegister Register, SMLoc Loc=SMLoc())
virtual void EmitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIAllocStack (unsigned Size, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushFrame (bool Code, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProlog (SMLoc Loc=SMLoc())
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except, SMLoc Loc=SMLoc())
virtual void EmitWinEHHandlerData (SMLoc Loc=SMLoc())
virtual void emitCGProfileEntry (const MCSymbolRefExpr *From, const MCSymbolRefExpr *To, uint64_t Count)
MCSection * getAssociatedPDataSection (const MCSection *TextSec)
Get the .pdata section used for the given section.
MCSection * getAssociatedXDataSection (const MCSection *TextSec)
Get the .xdata section used for the given section.
virtual void EmitSyntaxDirective ()
virtual bool EmitRelocDirective (const MCExpr &Offset, StringRef Name, const MCExpr *Expr, SMLoc Loc, const MCSubtargetInfo &STI)
Emit a .reloc directive.
virtual void EmitAddrsig ()
virtual void EmitAddrsigSym (const MCSymbol *Sym)
virtual void EmitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI)
Emit the given Instruction into the current section.
virtual void EmitBundleAlignMode (unsigned AlignPow2)
Set the bundle alignment mode from now on in the section.
virtual void EmitBundleLock (bool AlignToEnd)
The following instructions are a bundle-locked group.
virtual void EmitBundleUnlock ()
Ends a bundle-locked group.
void EmitRawText (const Twine &String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
virtual void FinishImpl ()
Streamer specific finalization.
void Finish ()
Finish emission of machine code.
virtual bool mayHaveInstructions (MCSection &Sec) const
Assembly File Formatting.
virtual bool isVerboseAsm () const
Return true if this streamer supports verbose assembly and if it is enabled.
virtual bool hasRawTextSupport () const
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
virtual bool isIntegratedAssemblerRequired () const
Is the integrated assembler required for this streamer to function correctly?
virtual void AddComment (const Twine &T, bool EOL=true)
Add a textual comment.
virtual raw_ostream & GetCommentOS ()
Return a raw_ostream that comments can be written to.
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
Print T and prefix it with the comment string (normally #) and optionally a tab.
virtual void addExplicitComment (const Twine &T)
Add explicit comment T.
virtual void emitExplicitComments ()
Emit added explicit comments.
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
Symbol & Section Management
MCSectionSubPair getCurrentSection () const
Return the current section that the streamer is emitting code to.
MCSection * getCurrentSectionOnly () const
MCSectionSubPair getPreviousSection () const
Return the previous section that the streamer is emitting code to.
unsigned GetSymbolOrder (const MCSymbol *Sym) const
Returns an index to represent the order a symbol was emitted in.
virtual void ChangeSection (MCSection *, const MCExpr *)
Update streamer for a new active section.
void PushSection ()
Save the current and previous section on the section stack.
bool PopSection ()
Restore the current and previous section from the section stack.
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
void SwitchSectionNoChange (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
virtual void InitSections (bool NoExecStack)
Create the default sections and set the initial one.
MCSymbol * endSection (MCSection *Section)
void AssignFragment (MCSymbol *Symbol, MCFragment *Fragment)
Sets the symbol's section.
virtual void EmitLabel (MCSymbol *Symbol, SMLoc Loc=SMLoc())
Emit a label for Symbol into the current section.
virtual void EmitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void EmitAssemblerFlag (MCAssemblerFlag Flag)
Note in the output the specified Flag.
virtual void EmitLinkerOptions (ArrayRef< std::string > Kind)
Emit the given list Options of strings as linker options into the output.
virtual void EmitDataRegion (MCDataRegionType Kind)
Note in the output the specified region Kind.
virtual void EmitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Specify the Mach-O minimum deployment target version.
virtual void EmitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Emit/Specify Mach-O build version command.
void EmitVersionForTarget (const Triple &Target, const VersionTuple &SDKVersion)
virtual void EmitThumbFunc (MCSymbol *Func)
Note in the output that the specified Func is a Thumb mode function (ARM target only).
virtual void EmitAssignment (MCSymbol *Symbol, const MCExpr *Value)
Emit an assignment of Value to Symbol.
virtual void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol)
Emit an weak reference from Alias to Symbol.
virtual bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute)=0
Add the given Attribute to Symbol.
virtual void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue)
Set the DescValue for the Symbol.
virtual void BeginCOFFSymbolDef (const MCSymbol *Symbol)
Start emitting COFF symbol definition.
virtual void EmitCOFFSymbolStorageClass (int StorageClass)
Emit the storage class of the symbol.
virtual void EmitCOFFSymbolType (int Type)
Emit the type of the symbol.
virtual void EndCOFFSymbolDef ()
Marks the end of the symbol definition.
virtual void EmitCOFFSafeSEH (MCSymbol const *Symbol)
virtual void EmitCOFFSymbolIndex (MCSymbol const *Symbol)
Emits the symbol table index of a Symbol into the current section.
virtual void EmitCOFFSectionIndex (MCSymbol const *Symbol)
Emits a COFF section index.
virtual void EmitCOFFSecRel32 (MCSymbol const *Symbol, uint64_t Offset)
Emits a COFF section relative relocation.
virtual void EmitCOFFImgRel32 (MCSymbol const *Symbol, int64_t Offset)
Emits a COFF image relative relocation.
virtual void EmitXCOFFLocalCommonSymbol (MCSymbol *LabelSym, uint64_t Size, MCSymbol *CsectSym, unsigned ByteAlignment)
Emits an lcomm directive with XCOFF csect information.
virtual void emitELFSize (MCSymbol *Symbol, const MCExpr *Value)
Emit an ELF .size directive.
virtual void emitELFSymverDirective (StringRef AliasName, const MCSymbol *Aliasee)
Emit an ELF .symver directive.
virtual void EmitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment)=0
Emit a common symbol.
virtual void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment)
Emit a local common (.lcomm) symbol.
virtual void EmitZerofill (MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, unsigned ByteAlignment=0, SMLoc Loc=SMLoc())=0
Emit the zerofill section and an optional symbol.
virtual void EmitTBSSSymbol (MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0)
Emit a thread local bss (.tbss) symbol.
Generating Data
virtual void EmitBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void EmitBinaryData (StringRef Data)
Functionally identical to EmitBytes.
virtual void EmitValueImpl (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
Emit the expression Value into the output as a native integer of the given Size bytes.
void EmitValue (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
virtual void EmitIntValue (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
virtual void EmitIntValueInHex (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
virtual void EmitULEB128Value (const MCExpr *Value)
virtual void EmitSLEB128Value (const MCExpr *Value)
void EmitULEB128IntValue (uint64_t Value, unsigned PadTo=0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void EmitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void EmitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
virtual void EmitDTPRel64Value (const MCExpr *Value)
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
virtual void EmitDTPRel32Value (const MCExpr *Value)
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
virtual void EmitTPRel64Value (const MCExpr *Value)
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
virtual void EmitTPRel32Value (const MCExpr *Value)
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
virtual void EmitGPRel64Value (const MCExpr *Value)
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
virtual void EmitGPRel32Value (const MCExpr *Value)
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc())
Emit Size bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc())
Emit NumValues copies of Size bytes.
void EmitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
virtual void EmitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0)
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
virtual void EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0)
Emit nops until the byte alignment ByteAlignment is reached.
virtual void emitValueToOffset (const MCExpr *Offset, unsigned char Value, SMLoc Loc)
Emit some number of copies of Value until the byte offset Offset is reached.
virtual void EmitCodePaddingBasicBlockStart (const MCCodePaddingContext &Context)
virtual void EmitCodePaddingBasicBlockEnd (const MCCodePaddingContext &Context)
Protected Member Functions
MCStreamer (MCContext &Ctx)
virtual void EmitCFIStartProcImpl (MCDwarfFrameInfo &Frame)
virtual void EmitCFIEndProcImpl (MCDwarfFrameInfo &CurFrame)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void EmitRawTextImpl (StringRef String)
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
bool checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc)
Returns true if the the .cv_loc directive is in the right section.
Detailed Description
Streaming machine code generation interface.
This interface is intended to provide a programatic interface that is very similar to the level that an assembler .s file provides. It has callbacks to emit bytes, handle directives, etc. The implementation of this interface retains state to know what the current section is etc.
There are multiple implementations of this interface: one for writing out a .s file, and implementations that write out .o files of various formats.
Definition at line 197 of file MCStreamer.h.
Constructor & Destructor Documentation
MCStreamer() [1/2]
MCStreamer::MCStreamer (MCContext & Ctx) protected
Definition at line 91 of file MCStreamer.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
MCStreamer() [2/2]
llvm::MCStreamer::MCStreamer (const MCStreamer &) delete
~MCStreamer()
MCStreamer::~MCStreamer () virtual
Definition at line 97 of file MCStreamer.cpp.
Member Function Documentation
AddBlankLine()
virtual void llvm::MCStreamer::AddBlankLine () inline virtual
AddBlankLine - Emit a blank line to a .s file to pretty it up.
Definition at line 349 of file MCStreamer.h.
Referenced by llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), emitNonLazyStubs(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), getGNUBinOpPrecedence(), and llvm::StackMaps::serializeToStackMapSection().
AddComment()
virtual void llvm::MCStreamer::AddComment (const Twine & T, bool EOL = true) inline virtual
Add a textual comment.
Typically for comments that can be emitted to the generated .s file if applicable as a QoI issue to make the output of the compiler more readable. This only affects the MCAsmStreamer, and only when verbose assembly output is enabled.
If the comment includes embedded
's, they will each get the comment prefix as appropriate. The added comment should not end with a
. By default, each comment is terminated with an end of line, i.e. the EOL param is set to true by default. If one prefers not to end the comment with a new line then the EOL param should be passed with a false value.
Definition at line 328 of file MCStreamer.h.
Referenced by llvm::BTFDebug::BTFDebug(), NoAutoPaddingScope::changeAndComment(), llvm::X86AsmPrinter::EmitInstruction(), llvm::CodeViewContext::emitLineTableForFunction(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::BTFTypeBase::emitType(), llvm::BTFTypeInt::emitType(), and llvm::BTFTypeStruct::emitType().
addExplicitComment()
void MCStreamer::addExplicitComment (const Twine & T) virtual
Add explicit comment T.
T is required to be a valid comment in the output and does not need to be escaped.
Definition at line 120 of file MCStreamer.cpp.
AssignFragment()
void MCStreamer::AssignFragment (MCSymbol * Symbol, MCFragment * Fragment)
Sets the symbol's section.
Each emitted symbol will be tracked in the ordering table, so we can sort on them later.
Definition at line 391 of file MCStreamer.cpp.
References assert(), llvm::MCSymbol::setFragment(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and llvm::ARMBuildAttrs::Symbol.
BeginCOFFSymbolDef()
void MCStreamer::BeginCOFFSymbolDef (const MCSymbol * Symbol) virtual
Start emitting COFF symbol definition.
Parameters
Symbol - The symbol to have its External & Type fields set.
Reimplemented in llvm::RecordStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1054 of file MCStreamer.cpp.
References llvm_unreachable.
ChangeSection()
void MCStreamer::ChangeSection (MCSection * , const MCExpr *) virtual
Update streamer for a new active section.
This is called by PopSection and SwitchSection, if the current section changes.
Reimplemented in llvm::MCObjectStreamer, llvm::MCWasmStreamer, and llvm::MCELFStreamer.
Definition at line 1079 of file MCStreamer.cpp.
Referenced by SwitchSection().
checkCVLocSection()
bool MCStreamer::checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc) protected
Returns true if the the .cv_loc directive is in the right section.
Definition at line 301 of file MCStreamer.cpp.
References getContext(), getCurrentSectionOnly(), llvm::MCContext::getCVContext(), llvm::CodeViewContext::getCVFunctionInfo(), llvm::MCContext::reportError(), and llvm::MCCVFunctionInfo::Section.
Referenced by llvm::MCObjectStreamer::EmitCVLocDirective().
emitAbsoluteSymbolDiff()
void MCStreamer::emitAbsoluteSymbolDiff (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Size) virtual
Emit the absolute difference between two symbols.
Precondition
Offset of Hi is greater than the offset Lo.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1022 of file MCStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::MCAsmInfo::doesSetDirectiveSuppressReloc(), EmitAssignment(), EmitSymbolValue(), EmitValue(), and llvm::MCContext::getAsmInfo().
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), and printFPOReg().
emitAbsoluteSymbolDiffAsULEB128()
void MCStreamer::emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol * Hi, const MCSymbol * Lo) virtual
Emit the absolute difference between two symbols encoded with ULEB128.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1041 of file MCStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), and EmitULEB128Value().
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128().
EmitAddrsig()
virtual void llvm::MCStreamer::EmitAddrsig () inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1002 of file MCStreamer.h.
EmitAddrsigSym()
virtual void llvm::MCStreamer::EmitAddrsigSym (const MCSymbol * Sym) inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1003 of file MCStreamer.h.
EmitAssemblerFlag()
void MCStreamer::EmitAssemblerFlag (MCAssemblerFlag Flag) virtual
Note in the output the specified Flag.
Reimplemented in llvm::MCWasmStreamer, llvm::MCELFStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1051 of file MCStreamer.cpp.
EmitAssignment()
void MCStreamer::EmitAssignment (MCSymbol * Symbol, const MCExpr * Value) virtual
Emit an assignment of Value to Symbol.
This corresponds to an assembler statement such as: symbol = value
The assignment generates no code, but has the side effect of binding the value in the current context. For the assembly streamer, this prints the binding into the .s file.
Parameters
Symbol - The symbol being assigned to.
Value - The value for the symbol.
Reimplemented in llvm::MCObjectStreamer, and llvm::RecordStreamer.
Definition at line 970 of file MCStreamer.cpp.
References llvm::MCTargetStreamer::emitAssignment(), getTargetStreamer(), llvm::MCSymbol::setVariableValue(), and visitUsedExpr().
Referenced by emitAbsoluteSymbolDiff(), llvm::RecordStreamer::EmitAssignment(), llvm::MCObjectStreamer::EmitAssignment(), llvm::RecordStreamer::flushSymverDirectives(), forceExpAbs(), getPlatformName(), isOperator(), and llvm::MCContext::setSymbolValue().
EmitBinaryData()
void MCStreamer::EmitBinaryData (StringRef Data) virtual
Functionally identical to EmitBytes.
When emitting textual assembly, this method uses .byte directives instead of .ascii or .asciz for readability.
Definition at line 1082 of file MCStreamer.cpp.
References EmitBytes().
Referenced by NoAutoPaddingScope::changeAndComment(), llvm::AsmPrinter::XRayFunctionEntry::emit(), emitOneV5FileEntry(), and llvm::MCDwarfLineStr::emitSection().
EmitBuildVersion()
virtual void llvm::MCStreamer::EmitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion) inline virtual
Emit/Specify Mach-O build version command.
Platform should be one of MachO::PlatformType.
Definition at line 477 of file MCStreamer.h.
References llvm::LCOMM::ByteAlignment, Size, and StorageClass.
Referenced by EmitVersionForTarget().
EmitBundleAlignMode()
void MCStreamer::EmitBundleAlignMode (unsigned AlignPow2) virtual
Set the bundle alignment mode from now on in the section.
The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
Reimplemented in llvm::MCObjectStreamer, and llvm::MCELFStreamer.
Definition at line 1098 of file MCStreamer.cpp.
EmitBundleLock()
void MCStreamer::EmitBundleLock (bool AlignToEnd) virtual
The following instructions are a bundle-locked group.
Parameters
AlignToEnd - If true, the bundle-locked group will be aligned to the end of a bundle.
Reimplemented in llvm::MCObjectStreamer, and llvm::MCELFStreamer.
Definition at line 1099 of file MCStreamer.cpp.
EmitBundleUnlock()
void MCStreamer::EmitBundleUnlock () virtual
Ends a bundle-locked group.
Reimplemented in llvm::MCObjectStreamer, and llvm::MCELFStreamer.
Definition at line 1101 of file MCStreamer.cpp.
EmitBytes()
void MCStreamer::EmitBytes (StringRef Data) virtual
Emit the bytes in Data into the output.
This is used to implement assembler directives such as .byte, .ascii, etc.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1081 of file MCStreamer.cpp.
Referenced by llvm::BTFDebug::BTFDebug(), NoAutoPaddingScope::changeAndComment(), llvm::MCDwarfLineAddr::Emit(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAMDKernelCodeT(), EmitBinaryData(), llvm::AArch64TargetStreamer::emitInst(), llvm::ARMTargetStreamer::emitInst(), EmitIntValue(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), EmitNop(), emitNullTerminatedSymbolName(), emitOneV5FileEntry(), llvm::MCDwarfLineStr::emitRef(), EmitSLEB128IntValue(), EmitULEB128IntValue(), and llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer().
EmitCFIAdjustCfaOffset()
void MCStreamer::EmitCFIAdjustCfaOffset (int64_t Adjustment) virtual
Definition at line 487 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createAdjustCfaOffset(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by llvm::X86AsmPrinter::EmitInstruction(), and PrintCFIEscape().
EmitCFIBKeyFrame()
void MCStreamer::EmitCFIBKeyFrame () virtual
Definition at line 231 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::IsBKeyFrame.
Referenced by PrintCFIEscape().
EmitCFIDefCfa()
void MCStreamer::EmitCFIDefCfa (int64_t Register, int64_t Offset) virtual
Definition at line 466 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createDefCfa(), llvm::MCDwarfFrameInfo::CurrentCfaRegister, EmitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, and Register.
Referenced by printDwarfFileDirective().
EmitCFIDefCfaOffset()
void MCStreamer::EmitCFIDefCfaOffset (int64_t Offset) virtual
Definition at line 477 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createDefCfaOffset(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by printDwarfFileDirective().
EmitCFIDefCfaRegister()
void MCStreamer::EmitCFIDefCfaRegister (int64_t Register) virtual
Definition at line 497 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCDwarfFrameInfo::CurrentCfaRegister, EmitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, and Register.
Referenced by PrintCFIEscape().
EmitCFIEndProc()
void MCStreamer::EmitCFIEndProc ()
Definition at line 447 of file MCStreamer.cpp.
References EmitCFIEndProcImpl().
EmitCFIEndProcImpl()
void MCStreamer::EmitCFIEndProcImpl (MCDwarfFrameInfo & CurFrame) protected virtual
Reimplemented in llvm::MipsELFStreamer.
Definition at line 454 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::End.
Referenced by EmitCFIEndProc(), and printDwarfFileDirective().
EmitCFIEscape()
void MCStreamer::EmitCFIEscape (StringRef Values) virtual
Definition at line 584 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createEscape(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIGnuArgsSize()
void MCStreamer::EmitCFIGnuArgsSize (int64_t Size) virtual
Definition at line 593 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createGnuArgsSize(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFILabel()
MCSymbol * MCStreamer::EmitCFILabel () virtual
When emitting an object file, create and emit a real label.
When emitting textual assembly, this should do nothing to avoid polluting our output.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 460 of file MCStreamer.cpp.
Referenced by EmitCFIAdjustCfaOffset(), EmitCFIDefCfa(), EmitCFIDefCfaOffset(), EmitCFIDefCfaRegister(), EmitCFIEscape(), EmitCFIGnuArgsSize(), EmitCFINegateRAState(), EmitCFIOffset(), EmitCFIRegister(), EmitCFIRelOffset(), EmitCFIRememberState(), EmitCFIRestore(), EmitCFIRestoreState(), EmitCFISameValue(), EmitCFIUndefined(), EmitCFIWindowSave(), EmitWinCFIAllocStack(), EmitWinCFIEndChained(), EmitWinCFIEndProc(), EmitWinCFIEndProlog(), EmitWinCFIFuncletOrFuncEnd(), EmitWinCFIPushFrame(), EmitWinCFIPushReg(), EmitWinCFISaveReg(), EmitWinCFISaveXMM(), EmitWinCFISetFrame(), EmitWinCFIStartChained(), and EmitWinCFIStartProc().
EmitCFILsda()
void MCStreamer::EmitCFILsda (const MCSymbol * Sym, unsigned Encoding) virtual
Definition at line 537 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::Lsda, and llvm::MCDwarfFrameInfo::LsdaEncoding.
Referenced by PrintCFIEscape().
EmitCFINegateRAState()
void MCStreamer::EmitCFINegateRAState () virtual
Definition at line 640 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createNegateRAState(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIOffset()
void MCStreamer::EmitCFIOffset (int64_t Register, int64_t Offset) virtual
Definition at line 508 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createOffset(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIPersonality()
void MCStreamer::EmitCFIPersonality (const MCSymbol * Sym, unsigned Encoding) virtual
Definition at line 528 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::Personality, and llvm::MCDwarfFrameInfo::PersonalityEncoding.
Referenced by PrintCFIEscape().
EmitCFIRegister()
void MCStreamer::EmitCFIRegister (int64_t Register1, int64_t Register2) virtual
Definition at line 620 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRegister(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIRelOffset()
void MCStreamer::EmitCFIRelOffset (int64_t Register, int64_t Offset) virtual
Definition at line 518 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRelOffset(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIRememberState()
void MCStreamer::EmitCFIRememberState () virtual
Definition at line 545 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRememberState(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIRestore()
void MCStreamer::EmitCFIRestore (int64_t Register) virtual
Definition at line 574 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRestore(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIRestoreState()
void MCStreamer::EmitCFIRestoreState () virtual
Definition at line 554 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRestoreState(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIReturnColumn()
void MCStreamer::EmitCFIReturnColumn (int64_t Register) virtual
Definition at line 649 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::RAReg, and Register.
Referenced by PrintCFIEscape().
EmitCFISameValue()
void MCStreamer::EmitCFISameValue (int64_t Register) virtual
Definition at line 564 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createSameValue(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFISections()
void MCStreamer::EmitCFISections (bool EH, bool Debug) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 418 of file MCStreamer.cpp.
References assert().
Referenced by llvm::MCObjectStreamer::EmitCFISections(), and printDwarfFileDirective().
EmitCFISignalFrame()
void MCStreamer::EmitCFISignalFrame () virtual
Definition at line 603 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::IsSignalFrame.
Referenced by PrintCFIEscape().
EmitCFIStartProc()
void MCStreamer::EmitCFIStartProc (bool IsSimple, SMLoc Loc = SMLoc())
Definition at line 422 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::CurrentCfaRegister, EmitCFIStartProcImpl(), llvm::MCContext::getAsmInfo(), getContext(), llvm::MCAsmInfo::getInitialFrameState(), hasUnfinishedDwarfFrameInfo(), llvm::MCDwarfFrameInfo::IsSimple, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaRegister, and llvm::MCContext::reportError().
EmitCFIStartProcImpl()
void MCStreamer::EmitCFIStartProcImpl (MCDwarfFrameInfo & Frame) protected virtual
Reimplemented in llvm::MipsELFStreamer.
Definition at line 444 of file MCStreamer.cpp.
Referenced by EmitCFIStartProc().
EmitCFIUndefined()
void MCStreamer::EmitCFIUndefined (int64_t Register) virtual
Definition at line 610 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createUndefined(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
EmitCFIWindowSave()
void MCStreamer::EmitCFIWindowSave () virtual
Definition at line 630 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createWindowSave(), EmitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
Referenced by PrintCFIEscape().
emitCGProfileEntry()
void MCStreamer::emitCGProfileEntry (const MCSymbolRefExpr * From, const MCSymbolRefExpr * To, uint64_t Count) virtual
Reimplemented in llvm::MCELFStreamer.
Definition at line 762 of file MCStreamer.cpp.
Referenced by llvm::TargetLoweringObjectFileELF::emitModuleMetadata().
EmitCodeAlignment()
void MCStreamer::EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit = 0) virtual
Emit nops until the byte alignment ByteAlignment is reached.
This used to align code where the alignment bytes may be executed. This can emit different bytes for different sizes to optimize execution.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1094 of file MCStreamer.cpp.
Referenced by NoAutoPaddingScope::changeAndComment(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), llvm::ConstantPool::emitEntries(), llvm::MipsTargetELFStreamer::finish(), and smallData().
EmitCodePaddingBasicBlockEnd()
virtual void llvm::MCStreamer::EmitCodePaddingBasicBlockEnd (const MCCodePaddingContext & Context) inline virtual
Definition at line 803 of file MCStreamer.h.
EmitCodePaddingBasicBlockStart()
virtual void llvm::MCStreamer::EmitCodePaddingBasicBlockStart (const MCCodePaddingContext & Context) inline virtual
Definition at line 800 of file MCStreamer.h.
EmitCOFFImgRel32()
void MCStreamer::EmitCOFFImgRel32 (MCSymbol const * Symbol, int64_t Offset) virtual
Emits a COFF image relative relocation.
Parameters
Symbol - Symbol the image relative relocation should point to.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 934 of file MCStreamer.cpp.
EmitCOFFSafeSEH()
void MCStreamer::EmitCOFFSafeSEH (MCSymbol const * Symbol) virtual
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 926 of file MCStreamer.cpp.
EmitCOFFSecRel32()
void MCStreamer::EmitCOFFSecRel32 (MCSymbol const * Symbol, uint64_t Offset) virtual
Emits a COFF section relative relocation.
Parameters
Symbol - Symbol the section relative relocation should point to.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 932 of file MCStreamer.cpp.
Referenced by llvm::CodeViewContext::emitLineTableForFunction(), and EmitSymbolValue().
EmitCOFFSectionIndex()
void MCStreamer::EmitCOFFSectionIndex (MCSymbol const * Symbol) virtual
Emits a COFF section index.
Parameters
Symbol - Symbol the section number relocation should point to.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 930 of file MCStreamer.cpp.
Referenced by llvm::CodeViewContext::emitLineTableForFunction().
EmitCOFFSymbolIndex()
void MCStreamer::EmitCOFFSymbolIndex (MCSymbol const * Symbol) virtual
Emits the symbol table index of a Symbol into the current section.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 928 of file MCStreamer.cpp.
EmitCOFFSymbolStorageClass()
void MCStreamer::EmitCOFFSymbolStorageClass (int StorageClass) virtual
Emit the storage class of the symbol.
Parameters
StorageClass - The storage class the symbol should have.
Reimplemented in llvm::RecordStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1061 of file MCStreamer.cpp.
References llvm_unreachable.
EmitCOFFSymbolType()
void MCStreamer::EmitCOFFSymbolType (int Type) virtual
Emit the type of the symbol.
Parameters
Type - A COFF type identifier (see COFF::SymbolType in X86COFF.h)
Reimplemented in llvm::RecordStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1064 of file MCStreamer.cpp.
References llvm_unreachable.
EmitCommonSymbol()
virtual void llvm::MCStreamer::EmitCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) pure virtual
Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol if non-zero. This must be a power of 2.
Implemented in llvm::MCWinCOFFStreamer, llvm::RecordStreamer, llvm::MCWasmStreamer, llvm::MCELFStreamer, and llvm::MCXCOFFStreamer.
EmitCVDefRangeDirective() [1/5]
void MCStreamer::EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, StringRef FixedSizePortion) virtual
This implements the CodeView '.cv_def_range' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 345 of file MCStreamer.cpp.
Referenced by llvm::MCObjectStreamer::EmitCVDefRangeDirective(), and EmitCVDefRangeDirective().
EmitCVDefRangeDirective() [2/5]
void MCStreamer::EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeRegisterRelHeader DRHdr) virtual
Definition at line 349 of file MCStreamer.cpp.
References copyBytesForDefRange(), and EmitCVDefRangeDirective().
EmitCVDefRangeDirective() [3/5]
void MCStreamer::EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr) virtual
Definition at line 357 of file MCStreamer.cpp.
References copyBytesForDefRange(), and EmitCVDefRangeDirective().
EmitCVDefRangeDirective() [4/5]
void MCStreamer::EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeRegisterHeader DRHdr) virtual
Definition at line 366 of file MCStreamer.cpp.
References copyBytesForDefRange(), and EmitCVDefRangeDirective().
EmitCVDefRangeDirective() [5/5]
void MCStreamer::EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeFramePointerRelHeader DRHdr) virtual
Definition at line 374 of file MCStreamer.cpp.
References copyBytesForDefRange(), and EmitCVDefRangeDirective().
EmitCVFileChecksumOffsetDirective()
virtual void llvm::MCStreamer::EmitCVFileChecksumOffsetDirective (unsigned FileNo) inline virtual
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 917 of file MCStreamer.h.
EmitCVFileChecksumsDirective()
virtual void llvm::MCStreamer::EmitCVFileChecksumsDirective () inline virtual
This implements the CodeView '.cv_filechecksums' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 913 of file MCStreamer.h.
EmitCVFileDirective()
bool MCStreamer::EmitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind) virtual
Associate a filename with a specified logical file number, and also specify that file's checksum information.
This implements the '.cv_file 4 "foo.c"' assembler directive. Returns true on success.
Definition at line 271 of file MCStreamer.cpp.
References llvm::CodeViewContext::addFile(), getContext(), and llvm::MCContext::getCVContext().
Referenced by llvm::CodeViewDebug::CodeViewDebug().
EmitCVFPOData()
virtual void llvm::MCStreamer::EmitCVFPOData (const MCSymbol * ProcSym, SMLoc Loc = {}) inline virtual
This implements the CodeView '.cv_fpo_data' assembler directive.
Definition at line 920 of file MCStreamer.h.
References llvm::codeview::Code, Debug, From, llvm::MipsISD::Hi, and llvm::MipsISD::Lo.
EmitCVFuncIdDirective()
bool MCStreamer::EmitCVFuncIdDirective (unsigned FunctionId) virtual
Introduces a function id for use with .cv_loc.
Definition at line 278 of file MCStreamer.cpp.
References getContext(), llvm::MCContext::getCVContext(), and llvm::CodeViewContext::recordFunctionId().
Referenced by printDwarfFileDirective().
EmitCVInlineLinetableDirective()
void MCStreamer::EmitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol * FnStartSym, const MCSymbol * FnEndSym) virtual
This implements the CodeView '.cv_inline_linetable' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 327 of file MCStreamer.cpp.
Referenced by llvm::MCObjectStreamer::EmitCVInlineLinetableDirective(), and printDwarfFileDirective().
EmitCVInlineSiteIdDirective()
bool MCStreamer::EmitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc) virtual
Introduces an inline call site id for use with .cv_loc.
Includes extra information for inline line table generation.
Definition at line 282 of file MCStreamer.cpp.
References getContext(), llvm::MCContext::getCVContext(), llvm::CodeViewContext::recordInlinedCallSiteId(), and llvm::MCContext::reportError().
Referenced by llvm::CodeViewDebug::CodeViewDebug(), and printDwarfFileDirective().
EmitCVLinetableDirective()
void MCStreamer::EmitCVLinetableDirective (unsigned FunctionId, const MCSymbol * FnStart, const MCSymbol * FnEnd) virtual
This implements the CodeView '.cv_linetable' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 323 of file MCStreamer.cpp.
Referenced by printDwarfFileDirective().
EmitCVLocDirective()
void MCStreamer::EmitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc) virtual
This implements the CodeView '.cv_loc' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 296 of file MCStreamer.cpp.
EmitCVStringTableDirective()
virtual void llvm::MCStreamer::EmitCVStringTableDirective () inline virtual
This implements the CodeView '.cv_stringtable' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 910 of file MCStreamer.h.
EmitDataRegion()
virtual void llvm::MCStreamer::EmitDataRegion (MCDataRegionType Kind) inline virtual
Note in the output the specified region Kind.
Definition at line 468 of file MCStreamer.h.
Referenced by llvm::ConstantPool::emitEntries(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), and llvm::MipsAsmPrinter::EmitInstruction().
EmitDTPRel32Value()
void MCStreamer::EmitDTPRel32Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
This is used to implement assembler directives such as .dtprelword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 181 of file MCStreamer.cpp.
References llvm::report_fatal_error().
Referenced by llvm::MipsAsmPrinter::EmitDebugValue().
EmitDTPRel64Value()
void MCStreamer::EmitDTPRel64Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
This is used to implement assembler directives such as .dtpreldword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 177 of file MCStreamer.cpp.
References llvm::report_fatal_error().
Referenced by llvm::MipsAsmPrinter::EmitDebugValue().
emitDwarfFile0Directive()
void MCStreamer::emitDwarfFile0Directive (StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, unsigned CUID = 0) virtual
Specify the "root" file of the compilation, using the ".file 0" extension.
Definition at line 222 of file MCStreamer.cpp.
References getContext(), and llvm::MCContext::setMCLineTableRootFile().
EmitDwarfFileDirective()
unsigned llvm::MCStreamer::EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum = None, Optional< StringRef > Source = None, unsigned CUID = 0) inline
Associate a filename with a specified logical file number.
This implements the DWARF2 '.file 4 "foo.c"' assembler directive.
Definition at line 817 of file MCStreamer.h.
References llvm::cantFail(), llvm::lltok::ChecksumKind, llvm::codeview::None, and llvm::Sched::Source.
EmitDwarfLocDirective()
void MCStreamer::EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) virtual
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 238 of file MCStreamer.cpp.
References getContext(), and llvm::MCContext::setCurrentDwarfLoc().
Referenced by llvm::MCObjectStreamer::EmitDwarfLocDirective(), and printDwarfFileDirective().
EmitEHSymAttributes()
void MCStreamer::EmitEHSymAttributes (const MCSymbol * Symbol, MCSymbol * EHSymbol) virtual
Definition at line 383 of file MCStreamer.cpp.
emitELFSize()
void MCStreamer::emitELFSize (MCSymbol * Symbol, const MCExpr * Value) virtual
Emit an ELF .size directive.
This corresponds to an assembler statement such as: .size symbol, expression
Reimplemented in llvm::MCWasmStreamer, and llvm::MCELFStreamer.
Definition at line 1072 of file MCStreamer.cpp.
Referenced by llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), and llvm::MipsAsmPrinter::EmitStartOfAsmFile().
emitELFSymverDirective()
void MCStreamer::emitELFSymverDirective (StringRef AliasName, const MCSymbol * Aliasee) virtual
Emit an ELF .symver directive.
This corresponds to an assembler statement such as: .symver _start, foo@SOME_VERSION
Parameters
AliasName - The versioned alias (i.e. "foo@@SOME_VERSION")
Aliasee - The aliased symbol (i.e. "_start")
Reimplemented in llvm::RecordStreamer, and llvm::MCELFStreamer.
Definition at line 1073 of file MCStreamer.cpp.
emitExplicitComments()
void MCStreamer::emitExplicitComments () virtual
Emit added explicit comments.
Definition at line 121 of file MCStreamer.cpp.
EmitFileDirective()
void MCStreamer::EmitFileDirective (StringRef Filename) virtual
Switch to a new logical file.
This is used to implement the '.file "foo.c"' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1060 of file MCStreamer.cpp.
emitFill() [1/3]
void MCStreamer::emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
This implements directives such as '.space'.
Definition at line 203 of file MCStreamer.cpp.
References llvm::MCConstantExpr::create(), and getContext().
Referenced by EmitGenDwarfRanges(), EmitZeros(), and PrintQuotedString().
emitFill() [2/3]
void MCStreamer::emitFill (const MCExpr & NumBytes, uint64_t FillValue, SMLoc Loc = SMLoc()) virtual
Emit Size bytes worth of the value specified by FillValue.
This is used to implement assembler directives such as .space or .skip.
Parameters
NumBytes - The number of bytes to emit.
FillValue - The value to use when filling bytes.
Loc - The location of the expression for error reporting.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1088 of file MCStreamer.cpp.
emitFill() [3/3]
void MCStreamer::emitFill (const MCExpr & NumValues, int64_t Size, int64_t Expr, SMLoc Loc = SMLoc()) virtual
Emit NumValues copies of Size bytes.
Each Size bytes is taken from the lowest order 4 bytes of Expr expression.
This is used to implement assembler directives such as .fill.
Parameters
NumValues - The number of copies of Size bytes to emit.
Size - The size (in bytes) of each repeated value.
Expr - The expression from which Size bytes are used.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1089 of file MCStreamer.cpp.
EmitGPRel32Value()
void MCStreamer::EmitGPRel32Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
This is used to implement assembler directives such as .gprel32 on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 197 of file MCStreamer.cpp.
References llvm::report_fatal_error().
EmitGPRel64Value()
void MCStreamer::EmitGPRel64Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
This is used to implement assembler directives such as .gpdword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 193 of file MCStreamer.cpp.
References llvm::report_fatal_error().
EmitIdent()
virtual void llvm::MCStreamer::EmitIdent (StringRef IdentString) inline virtual
Emit the "identifiers" directive.
This implements the '.ident "version foo"' assembler directive.
Reimplemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 813 of file MCStreamer.h.
EmitInstruction()
void MCStreamer::EmitInstruction (const MCInst & Inst, const MCSubtargetInfo & STI) virtual
Emit the given Instruction into the current section.
Reimplemented in llvm::MCObjectStreamer, llvm::RecordStreamer, llvm::MipsELFStreamer, and llvm::HexagonMCELFStreamer.
Definition at line 1015 of file MCStreamer.cpp.
References llvm::MCOperand::getExpr(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and visitUsedExpr().
Referenced by addNegOperand(), NoAutoPaddingScope::changeAndComment(), covertDoubleImmToSingleImm(), EmitBinary(), EmitCall(), llvm::MipsTargetStreamer::emitII(), llvm::RecordStreamer::EmitInstruction(), llvm::MCObjectStreamer::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), EmitNop(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRRX(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), EmitSETHI(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::AsmPrinter::EmitToStreamer(), llvm::IsCPSRDead< MCInst >(), isMatchingOrAlias(), IsRevOpcode(), matchRegisterNameHelper(), needsExpandMemInst(), and printMCExpr().
EmitIntValue()
void MCStreamer::EmitIntValue (uint64_t Value, unsigned Size) virtual
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
EmitIntValue - Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 131 of file MCStreamer.cpp.
References assert(), EmitBytes(), llvm::MCContext::getAsmInfo(), llvm::isIntN(), llvm::MCAsmInfo::isLittleEndian(), llvm::isUIntN(), and Size.
Referenced by ARM64EmitUnwindCode(), ARM64EmitUnwindInfo(), llvm::BTFDebug::BTFDebug(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::AMDGPUTargetELFStreamer::EmitCodeEnd(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectISA(), llvm::AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectVersion(), EmitDwarfLineTable(), emitDwarfSetLineAddr(), emitEncodingByte(), llvm::CodeViewContext::emitFileChecksums(), llvm::MCObjectStreamer::emitFill(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::MCELFStreamer::EmitIdent(), llvm::MipsELFStreamer::EmitIntValue(), llvm::CodeViewContext::emitLineTableForFunction(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), emitNonLazySymbolPointer(), emitOneV5FileEntry(), llvm::MCDwarfLineStr::emitRef(), llvm::CodeViewContext::emitStringTable(), llvm::BTFTypeBase::emitType(), llvm::BTFTypeInt::emitType(), llvm::BTFTypeEnum::emitType(), llvm::BTFTypeArray::emitType(), llvm::BTFTypeStruct::emitType(), llvm::BTFTypeFuncProto::emitType(), llvm::BTFKindVar::emitType(), llvm::BTFKindDataSec::emitType(), EmitUnwindCode(), EmitUnwindInfo(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::WebAssemblyTargetStreamer::emitValueType(), getTryAncestor(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), llvm::operator<<(), printFPOReg(), llvm::StackMaps::recordStatepoint(), llvm::FaultMaps::serializeToFaultMapSection(), and smallData().
EmitIntValueInHex()
virtual void llvm::MCStreamer::EmitIntValueInHex (uint64_t Value, unsigned Size) inline virtual
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
Definition at line 662 of file MCStreamer.h.
EmitLabel()
void MCStreamer::EmitLabel (MCSymbol * Symbol, SMLoc Loc = SMLoc()) virtual
Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented in llvm::MCObjectStreamer, llvm::RecordStreamer, llvm::MipsELFStreamer, llvm::MCELFStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 400 of file MCStreamer.cpp.
References assert(), llvm::MCTargetStreamer::emitLabel(), getContext(), getCurrentSectionOnly(), llvm::MCSymbol::getFragment(), getTargetStreamer(), llvm::MCSymbol::isUndefined(), llvm::MCSymbol::isVariable(), llvm::MCSymbol::redefineIfPossible(), llvm::MCContext::reportError(), and llvm::MCSymbol::setFragment().
Referenced by ARM64EmitUnwindInfo(), llvm::BTFDebug::beginInstruction(), NoAutoPaddingScope::changeAndComment(), covertDoubleImmToSingleImm(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCDwarfDwoLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), emitDirectiveRelocJalr(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), llvm::ConstantPool::emitEntries(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), EmitGenDwarfInfo(), llvm::X86AsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::RecordStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitLabelAtPos(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), emitNonLazySymbolPointer(), EmitNop(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), EmitUnwindInfo(), llvm::BTFDebug::endFunctionImpl(), endSection(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), getGNUBinOpPrecedence(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), getRealVLDOpcode(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::MCGenDwarfLabelEntry::Make(), matchRegisterNameHelper(), needsExpandMemInst(), printFPOReg(), printMCExpr(), llvm::FaultMaps::serializeToFaultMapSection(), llvm::StackMaps::serializeToStackMapSection(), smallData(), SwitchSection(), and truncateToSize().
EmitLinkerOptions()
virtual void llvm::MCStreamer::EmitLinkerOptions (ArrayRef< std::string > Kind) inline virtual
Emit the given list Options of strings as linker options into the output.
Definition at line 465 of file MCStreamer.h.
Referenced by llvm::TargetLoweringObjectFileMachO::emitModuleMetadata().
EmitLocalCommonSymbol()
void MCStreamer::EmitLocalCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) virtual
Emit a local common (.lcomm) symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the common symbol in bytes.
Reimplemented in llvm::MCWinCOFFStreamer, llvm::MCELFStreamer, and llvm::MCWasmStreamer.
Definition at line 1075 of file MCStreamer.cpp.
EmitLOHDirective()
virtual void llvm::MCStreamer::EmitLOHDirective (MCLOHType Kind, const MCLOHArgs & Args) inline virtual
Emit a Linker Optimization Hint (LOH) directive.
Parameters
Args - Arguments of the LOH.
Definition at line 586 of file MCStreamer.h.
References llvm::Data.
emitRawComment()
void MCStreamer::emitRawComment (const Twine & T, bool TabPrefix = true) virtual
Print T and prefix it with the comment string (normally #) and optionally a tab.
This prints the comment immediately, not at the end of the current line. It is basically a safe version of EmitRawText: since it only prints comments, the object streamer ignores it instead of asserting.
Definition at line 118 of file MCStreamer.cpp.
Referenced by NoAutoPaddingScope::changeAndComment(), llvm::X86AsmPrinter::EmitInstruction(), and llvm::AVRTargetStreamer::finish().
EmitRawText()
void MCStreamer::EmitRawText (const Twine & String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
This capability is indicated by the hasRawTextSupport() predicate. By default this aborts.
Definition at line 948 of file MCStreamer.cpp.
References EmitRawTextImpl(), and llvm::Twine::toStringRef().
Referenced by llvm::NVPTXTargetStreamer::closeLastSection(), llvm::MCTargetStreamer::emitDwarfFileDirective(), llvm::MCTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitValue(), and llvm::NVPTXTargetStreamer::outputDwarfFileDirectives().
EmitRawTextImpl()
void MCStreamer::EmitRawTextImpl (StringRef String) protected virtual
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
This capability is indicated by the hasRawTextSupport() predicate.
Definition at line 939 of file MCStreamer.cpp.
References llvm::report_fatal_error().
Referenced by EmitRawText().
EmitRelocDirective()
virtual bool llvm::MCStreamer::EmitRelocDirective (const MCExpr & Offset, StringRef Name, const MCExpr * Expr, SMLoc Loc, const MCSubtargetInfo & STI) inline virtual
Emit a .reloc directive.
Returns true if the relocation could not be emitted because Name is not known.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 996 of file MCStreamer.h.
Referenced by emitDirectiveRelocJalr(), and needsExpandMemInst().
EmitSLEB128IntValue()
void MCStreamer::EmitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
EmitSLEB128IntValue - Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
Definition at line 155 of file MCStreamer.cpp.
References EmitBytes(), llvm::encodeSLEB128(), and llvm::raw_svector_ostream::str().
Referenced by llvm::MCObjectStreamer::EmitSLEB128Value().
EmitSLEB128Value()
void MCStreamer::EmitSLEB128Value (const MCExpr * Value) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1087 of file MCStreamer.cpp.
EmitSymbolAttribute()
virtual bool llvm::MCStreamer::EmitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) pure virtual
Add the given Attribute to Symbol.
Implemented in llvm::RecordStreamer, llvm::MCWasmStreamer, llvm::MCELFStreamer, llvm::MCWinCOFFStreamer, and llvm::MCXCOFFStreamer.
Referenced by emitNonLazySymbolPointer(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::AVRTargetStreamer::finish(), isOperator(), and smallData().
EmitSymbolDesc()
void MCStreamer::EmitSymbolDesc (MCSymbol * Symbol, unsigned DescValue) virtual
Set the DescValue for the Symbol.
Parameters
Symbol - The symbol to have its n_desc field set.
DescValue - The value to set into the n_desc field.
Reimplemented in llvm::MCWasmStreamer, llvm::MCELFStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1053 of file MCStreamer.cpp.
EmitSymbolValue()
void MCStreamer::EmitSymbolValue (const MCSymbol * Sym, unsigned Size, bool IsSectionRelative = false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
Definition at line 166 of file MCStreamer.cpp.
References assert(), llvm::MCSymbolRefExpr::create(), EmitCOFFSecRel32(), EmitValueImpl(), and getContext().
Referenced by createPPCMCAsmInfo(), llvm::AsmPrinter::XRayFunctionEntry::emit(), emitAbsoluteSymbolDiff(), emitDwarfSetLineAddr(), llvm::CodeViewContext::emitFileChecksumOffset(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::StackMaps::recordStatepoint(), and llvm::FaultMaps::serializeToFaultMapSection().
EmitSyntaxDirective()
void MCStreamer::EmitSyntaxDirective () virtual
Definition at line 813 of file MCStreamer.cpp.
EmitTBSSSymbol()
void MCStreamer::EmitTBSSSymbol (MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment = 0) virtual
Emit a thread local bss (.tbss) symbol.
Parameters
Section - The thread local common section.
Symbol - The thread local common symbol to emit.
Size - The size of the symbol.
ByteAlignment - The alignment of the thread local common symbol if non-zero. This must be a power of 2 on some targets.
Reimplemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1077 of file MCStreamer.cpp.
EmitThumbFunc()
void MCStreamer::EmitThumbFunc (MCSymbol * Func) virtual
Note in the output that the specified Func is a Thumb mode function (ARM target only).
Reimplemented in llvm::MCWasmStreamer, llvm::MCELFStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1052 of file MCStreamer.cpp.
EmitTPRel32Value()
void MCStreamer::EmitTPRel32Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
This is used to implement assembler directives such as .tprelword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 189 of file MCStreamer.cpp.
References llvm::report_fatal_error().
EmitTPRel64Value()
void MCStreamer::EmitTPRel64Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
This is used to implement assembler directives such as .tpreldword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 185 of file MCStreamer.cpp.
References llvm::report_fatal_error().
EmitULEB128IntValue()
void MCStreamer::EmitULEB128IntValue (uint64_t Value, unsigned PadTo = 0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
EmitULEB128IntValue - Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
Definition at line 146 of file MCStreamer.cpp.
References EmitBytes(), llvm::encodeULEB128(), and llvm::raw_svector_ostream::str().
Referenced by EmitAbbrev(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128(), EmitDwarfLineTable(), emitDwarfSetLineAddr(), EmitGenDwarfAbbrev(), EmitGenDwarfInfo(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), emitOneV5FileEntry(), llvm::MCDwarfLineStr::emitRef(), and llvm::MCObjectStreamer::EmitULEB128Value().
EmitULEB128Value()
void MCStreamer::EmitULEB128Value (const MCExpr * Value) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1086 of file MCStreamer.cpp.
Referenced by emitAbsoluteSymbolDiffAsULEB128().
EmitValue()
void MCStreamer::EmitValue (const MCExpr * Value, unsigned Size, SMLoc Loc = SMLoc())
Definition at line 162 of file MCStreamer.cpp.
References EmitValueImpl().
Referenced by ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfo(), EmitAbsDifference(), emitAbsoluteSymbolDiff(), emitAbsValue(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::ConstantPool::emitEntries(), emitFDESymbol(), EmitGenDwarfAranges(), EmitGenDwarfRanges(), emitNonLazySymbolPointer(), EmitPersonality(), llvm::MCDwarfLineStr::emitRef(), EmitRuntimeFunction(), EmitSymbolRefWithOfs(), EmitUnwindInfo(), llvm::AVRMCELFStreamer::EmitValueForModiferKind(), printFPOReg(), llvm::StackMaps::recordStatepoint(), llvm::FaultMaps::serializeToFaultMapSection(), and smallData().
EmitValueImpl()
void MCStreamer::EmitValueImpl (const MCExpr * Value, unsigned Size, SMLoc Loc = SMLoc()) virtual
Emit the expression Value into the output as a native integer of the given Size bytes.
This is used to implement assembler directives such as .word, .quad, etc.
Parameters
Value - The value to emit.
Size - The size of the integer (in bytes) to emit. This must match a native machine width.
Loc - The location of the expression for error reporting.
Reimplemented in llvm::MCObjectStreamer, llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MipsELFStreamer.
Definition at line 1083 of file MCStreamer.cpp.
References visitUsedExpr().
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), EmitSymbolValue(), EmitValue(), and llvm::MCObjectStreamer::EmitValueImpl().
EmitValueToAlignment()
void MCStreamer::EmitValueToAlignment (unsigned ByteAlignment, int64_t Value = 0, unsigned ValueSize = 1, unsigned MaxBytesToEmit = 0) virtual
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
If the number of bytes need to emit for the alignment is not a multiple of ValueSize, then the contents of the emitted fill bytes is undefined.
This used to implement the .align assembler directive.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
Value - The value to use when filling bytes.
ValueSize - The size of the integer (in bytes) to emit for Value. This must match a native machine width.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented in llvm::MCObjectStreamer, llvm::MCELFStreamer, and llvm::MCWasmStreamer.
Definition at line 1091 of file MCStreamer.cpp.
Referenced by ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfo(), createPPCMCAsmInfo(), llvm::AMDGPUTargetELFStreamer::EmitCodeEnd(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), EmitRuntimeFunction(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), EmitUnwindInfo(), llvm::MipsTargetELFStreamer::finish(), printFPOReg(), and llvm::StackMaps::recordStatepoint().
emitValueToOffset()
void MCStreamer::emitValueToOffset (const MCExpr * Offset, unsigned char Value, SMLoc Loc) virtual
Emit some number of copies of Value until the byte offset Offset is reached.
This is used to implement assembler directives such as .org.
Parameters
Offset - The offset to reach. This may be an expression, but the expression must be associated with the current section.
Value - The value to use when filling bytes.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1096 of file MCStreamer.cpp.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
EmitVersionForTarget()
void MCStreamer::EmitVersionForTarget (const Triple & Target, const VersionTuple & SDKVersion)
Definition at line 1129 of file MCStreamer.cpp.
References assert(), EmitBuildVersion(), EmitVersionMin(), llvm::Triple::getiOSVersion(), llvm::Triple::getMacOSXVersion(), llvm::Triple::getOSMajorVersion(), llvm::Triple::getWatchOSVersion(), llvm::Triple::isMacCatalystEnvironment(), llvm::Triple::isMacOSX(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSDarwin(), llvm::Triple::isTvOS(), llvm::Triple::isWatchOS(), llvm::MCVM_IOSVersionMin, llvm::MCVM_OSXVersionMin, llvm::MCVM_TvOSVersionMin, llvm::MCVM_WatchOSVersionMin, and llvm::MachO::PLATFORM_MACCATALYST.
EmitVersionMin()
virtual void llvm::MCStreamer::EmitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion) inline virtual
Specify the Mach-O minimum deployment target version.
Definition at line 471 of file MCStreamer.h.
Referenced by EmitVersionForTarget().
EmitWeakReference()
void MCStreamer::EmitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) virtual
Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented in llvm::MCObjectStreamer, llvm::MCWasmStreamer, and llvm::MCELFStreamer.
Definition at line 1080 of file MCStreamer.cpp.
EmitWinCFIAllocStack()
void MCStreamer::EmitWinCFIAllocStack (unsigned Size, SMLoc Loc = SMLoc()) virtual
Definition at line 853 of file MCStreamer.cpp.
References llvm::Win64EH::Instruction::Alloc(), EmitCFILabel(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, and llvm::MCContext::reportError().
Referenced by PrintCFIEscape(), and printConstant().
EmitWinCFIEndChained()
void MCStreamer::EmitWinCFIEndChained (SMLoc Loc = SMLoc()) virtual
Definition at line 723 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, EmitCFILabel(), llvm::WinEH::FrameInfo::End, EnsureValidWinFrameInfo(), getContext(), and llvm::MCContext::reportError().
Referenced by PrintCFIEscape().
EmitWinCFIEndProc()
void MCStreamer::EmitWinCFIEndProc (SMLoc Loc = SMLoc()) virtual
Definition at line 688 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, EmitCFILabel(), llvm::WinEH::FrameInfo::End, EnsureValidWinFrameInfo(), getContext(), and llvm::MCContext::reportError().
Referenced by PrintCFIEscape().
EmitWinCFIEndProlog()
void MCStreamer::EmitWinCFIEndProlog (SMLoc Loc = SMLoc()) virtual
Definition at line 916 of file MCStreamer.cpp.
References EmitCFILabel(), EnsureValidWinFrameInfo(), and llvm::WinEH::FrameInfo::PrologEnd.
Referenced by PrintCFIEscape(), and printConstant().
EmitWinCFIFuncletOrFuncEnd()
void MCStreamer::EmitWinCFIFuncletOrFuncEnd (SMLoc Loc = SMLoc()) virtual
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
We cannot use the End marker, as it is not set at the point of emitting .xdata, in order to indicate that the frame is active.
Definition at line 699 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, EmitCFILabel(), EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::FuncletOrFuncEnd, getContext(), and llvm::MCContext::reportError().
EmitWinCFIPushFrame()
void MCStreamer::EmitWinCFIPushFrame (bool Code, SMLoc Loc = SMLoc()) virtual
Definition at line 902 of file MCStreamer.cpp.
References EmitCFILabel(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::Win64EH::Instruction::PushMachFrame(), and llvm::MCContext::reportError().
Referenced by PrintCFIEscape(), and printConstant().
EmitWinCFIPushReg()
void MCStreamer::EmitWinCFIPushReg (MCRegister Register, SMLoc Loc = SMLoc()) virtual
Definition at line 819 of file MCStreamer.cpp.
References EmitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::Instructions, and llvm::Win64EH::Instruction::PushNonVol().
Referenced by PrintCFIEscape(), and printConstant().
EmitWinCFISaveReg()
void MCStreamer::EmitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc = SMLoc()) virtual
Definition at line 870 of file MCStreamer.cpp.
References EmitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::MCContext::reportError(), and llvm::Win64EH::Instruction::SaveNonVol().
Referenced by PrintCFIEscape(), and printConstant().
EmitWinCFISaveXMM()
void MCStreamer::EmitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc = SMLoc()) virtual
Definition at line 887 of file MCStreamer.cpp.
References EmitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::MCContext::reportError(), and llvm::Win64EH::Instruction::SaveXMM().
Referenced by PrintCFIEscape(), and printConstant().
EmitWinCFISetFrame()
void MCStreamer::EmitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc = SMLoc()) virtual
Definition at line 831 of file MCStreamer.cpp.
References EmitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::WinEH::FrameInfo::LastFrameInst, llvm::MCContext::reportError(), and llvm::Win64EH::Instruction::SetFPReg().
Referenced by PrintCFIEscape(), and printConstant().
EmitWinCFIStartChained()
void MCStreamer::EmitWinCFIStartChained (SMLoc Loc = SMLoc()) virtual
Definition at line 710 of file MCStreamer.cpp.
References EmitCFILabel(), EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::Function, getCurrentSectionOnly(), and llvm::WinEH::FrameInfo::TextSection.
Referenced by PrintCFIEscape().
EmitWinCFIStartProc()
void MCStreamer::EmitWinCFIStartProc (const MCSymbol * Symbol, SMLoc Loc = SMLoc()) virtual
Definition at line 671 of file MCStreamer.cpp.
References EmitCFILabel(), llvm::WinEH::FrameInfo::End, llvm::MCContext::getAsmInfo(), getContext(), getCurrentSectionOnly(), llvm::MCContext::reportError(), llvm::WinEH::FrameInfo::TextSection, and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by PrintCFIEscape().
EmitWindowsUnwindTables()
void MCStreamer::EmitWindowsUnwindTables () protected virtual
Definition at line 953 of file MCStreamer.cpp.
EmitWinEHHandler()
void MCStreamer::EmitWinEHHandler (const MCSymbol * Sym, bool Unwind, bool Except, SMLoc Loc = SMLoc()) virtual
Definition at line 737 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::ExceptionHandler, getContext(), llvm::WinEH::FrameInfo::HandlesExceptions, llvm::WinEH::FrameInfo::HandlesUnwind, and llvm::MCContext::reportError().
Referenced by PrintCFIEscape().
EmitWinEHHandlerData()
void MCStreamer::EmitWinEHHandlerData (SMLoc Loc = SMLoc()) virtual
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 754 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, EnsureValidWinFrameInfo(), getContext(), and llvm::MCContext::reportError().
Referenced by PrintCFIEscape().
EmitXCOFFLocalCommonSymbol()
void MCStreamer::EmitXCOFFLocalCommonSymbol (MCSymbol * LabelSym, uint64_t Size, MCSymbol * CsectSym, unsigned ByteAlignment) virtual
Emits an lcomm directive with XCOFF csect information.
Parameters
LabelSym - Label on the block of storage.
Size - The size of the block of storage.
CsectSym - Csect name for the block of storage.
ByteAlignment - The alignment of the symbol in bytes. Must be a power of 2.
Reimplemented in llvm::MCXCOFFStreamer.
Definition at line 1067 of file MCStreamer.cpp.
References llvm_unreachable.
EmitZerofill()
virtual void llvm::MCStreamer::EmitZerofill (MCSection * Section, MCSymbol * Symbol = nullptr, uint64_t Size = 0, unsigned ByteAlignment = 0, SMLoc Loc = SMLoc()) pure virtual
Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol if non-zero. This must be a power of 2 on some targets.
Implemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, llvm::MCWinCOFFStreamer, llvm::RecordStreamer, and llvm::MCXCOFFStreamer.
EmitZeros()
void MCStreamer::EmitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
The implementation in this class just redirects to emitFill.
This function properly handles data in virtual sections.
Definition at line 208 of file MCStreamer.cpp.
References emitFill().
Referenced by llvm::AsmPrinter::XRayFunctionEntry::emit(), llvm::MCXCOFFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), and llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol().
EndCOFFSymbolDef()
void MCStreamer::EndCOFFSymbolDef () virtual
Marks the end of the symbol definition.
Reimplemented in llvm::RecordStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1057 of file MCStreamer.cpp.
References llvm_unreachable.
endSection()
MCSymbol * MCStreamer::endSection (MCSection * Section)
Definition at line 1117 of file MCStreamer.cpp.
References EmitLabel(), llvm::MCSection::getEndSymbol(), llvm::MCSymbol::isInSection(), and SwitchSection().
Referenced by EmitDwarfLineTable().
EnsureValidWinFrameInfo()
WinEH::FrameInfo * MCStreamer::EnsureValidWinFrameInfo (SMLoc Loc)
Retreive the current frame info if one is available and it is not yet closed.
Otherwise, issue an error and return null.
Definition at line 656 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::End, llvm::MCContext::getAsmInfo(), getContext(), llvm::MCContext::reportError(), and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by EmitWinCFIAllocStack(), EmitWinCFIEndChained(), EmitWinCFIEndProc(), EmitWinCFIEndProlog(), EmitWinCFIFuncletOrFuncEnd(), EmitWinCFIPushFrame(), EmitWinCFIPushReg(), EmitWinCFISaveReg(), EmitWinCFISaveXMM(), EmitWinCFISetFrame(), EmitWinCFIStartChained(), EmitWinEHHandler(), and EmitWinEHHandlerData().
Finish()
void MCStreamer::Finish ()
Finish emission of machine code.
Definition at line 956 of file MCStreamer.cpp.
References llvm::MCTargetStreamer::finish(), FinishImpl(), getContext(), getTargetStreamer(), and llvm::MCContext::reportError().
FinishImpl()
void MCStreamer::FinishImpl () virtual
Streamer specific finalization.
Reimplemented in llvm::MCObjectStreamer, llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1100 of file MCStreamer.cpp.
Referenced by Finish().
generateCompactUnwindEncodings()
void MCStreamer::generateCompactUnwindEncodings (MCAsmBackend * MAB)
Definition at line 123 of file MCStreamer.cpp.
References llvm::MCAsmBackend::generateCompactUnwindEncoding().
Referenced by llvm::MCDwarfFrameEmitter::Emit().
getAllowAutoPadding()
bool llvm::MCStreamer::getAllowAutoPadding () const inline
Definition at line 278 of file MCStreamer.h.
Referenced by NoAutoPaddingScope::changeAndComment(), and hasVariantSymbol().
getAssemblerPtr()
virtual MCAssembler* llvm::MCStreamer::getAssemblerPtr () inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 268 of file MCStreamer.h.
getAssociatedPDataSection()
MCSection * MCStreamer::getAssociatedPDataSection (const MCSection * TextSec)
Get the .pdata section used for the given section.
Typically the given section is either the main .text section or some other COMDAT .text section, but it may be any section containing code.
Definition at line 801 of file MCStreamer.cpp.
References getContext(), and getWinCFISection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), and llvm::Win64EH::ARM64UnwindEmitter::Emit().
getAssociatedXDataSection()
MCSection * MCStreamer::getAssociatedXDataSection (const MCSection * TextSec)
Get the .xdata section used for the given section.
Definition at line 807 of file MCStreamer.cpp.
References getContext(), and getWinCFISection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), llvm::Win64EH::ARM64UnwindEmitter::Emit(), llvm::Win64EH::UnwindEmitter::EmitUnwindInfo(), and llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo().
GetCommentOS()
raw_ostream & MCStreamer::GetCommentOS () virtual
Return a raw_ostream that comments can be written to.
Unlike AddComment, you are required to terminate comments with
if you use this method.
Definition at line 108 of file MCStreamer.cpp.
References llvm::nulls().
getContext()
MCContext& llvm::MCStreamer::getContext () const inline
Definition at line 266 of file MCStreamer.h.
References Context.
Referenced by llvm::AssemblerConstantPools::addEntry(), llvm::CodeViewContext::addFile(), ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfo(), llvm::BTFDebug::beginInstruction(), llvm::BTFDebug::BTFDebug(), buildSymbolDiff(), NoAutoPaddingScope::changeAndComment(), llvm::NVPTXTargetStreamer::changeSection(), llvm::MCTargetStreamer::changeSection(), llvm::MCObjectStreamer::changeSectionImpl(), checkCVLocSection(), llvm::CodeViewDebug::CodeViewDebug(), convertTailJumpOpcode(), covertDoubleImmToSingleImm(), createPPCMCAsmInfo(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCDwarfLineTable::Emit(), llvm::MCDwarfLineAddr::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), EmitAbsDifference(), llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), llvm::AMDGPUTargetELFStreamer::EmitAMDGPUSymbolType(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::MipsELFStreamer::EmitCFIEndProcImpl(), llvm::MipsELFStreamer::EmitCFILabel(), EmitCFIStartProc(), llvm::MipsELFStreamer::EmitCFIStartProcImpl(), llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MCObjectStreamer::EmitCVDefRangeDirective(), llvm::MCObjectStreamer::EmitCVFileChecksumOffsetDirective(), llvm::MCObjectStreamer::EmitCVFileChecksumsDirective(), EmitCVFileDirective(), EmitCVFuncIdDirective(), llvm::MCObjectStreamer::EmitCVInlineLinetableDirective(), EmitCVInlineSiteIdDirective(), llvm::MCObjectStreamer::EmitCVLocDirective(), llvm::MCObjectStreamer::EmitCVStringTableDirective(), emitDwarfFile0Directive(), EmitDwarfLineTable(), EmitDwarfLocDirective(), emitFDESymbol(), llvm::CodeViewContext::emitFileChecksumOffset(), llvm::CodeViewContext::emitFileChecksums(), llvm::MCObjectStreamer::emitFill(), emitFill(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::MCELFStreamer::EmitIdent(), llvm::ARMTargetStreamer::emitInst(), llvm::MipsELFStreamer::EmitInstruction(), EmitLabel(), llvm::CodeViewContext::emitLineTableForFunction(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), emitNonLazySymbolPointer(), emitOneV5FileEntry(), EmitPersonality(), llvm::NVPTXTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitRawBytes(), llvm::MCDwarfLineStr::emitRef(), llvm::MCObjectStreamer::EmitRelocDirective(), EmitRuntimeFunction(), llvm::MCDwarfLineStr::emitSection(), llvm::CodeViewContext::emitStringTable(), EmitSymbolRefWithOfs(), EmitSymbolValue(), EmitUnwindInfo(), llvm::MCTargetStreamer::emitValue(), llvm::AVRMCELFStreamer::EmitValueForModiferKind(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::MCELFStreamer::EmitWeakReference(), llvm::MCWasmStreamer::EmitWeakReference(), EmitWinCFIAllocStack(), EmitWinCFIEndChained(), EmitWinCFIEndProc(), EmitWinCFIFuncletOrFuncEnd(), EmitWinCFIPushFrame(), EmitWinCFISaveReg(), EmitWinCFISaveXMM(), EmitWinCFISetFrame(), EmitWinCFIStartProc(), EmitWinEHHandler(), EmitWinEHHandlerData(), llvm::BTFDebug::endFunctionImpl(), EnsureValidWinFrameInfo(), llvm::AVRTargetStreamer::finish(), Finish(), llvm::MCWinCOFFStreamer::FinishImpl(), llvm::MCObjectStreamer::FinishImpl(), llvm::MCObjectStreamer::flushPendingLabels(), llvm::RecordStreamer::flushSymverDirectives(), forceExpAbs(), GetAbsDifference(), getAssociatedPDataSection(), getAssociatedXDataSection(), llvm::AMDGPUTargetStreamer::getContext(), getDataAlignmentFactor(), getDwarfLineTableSymbol(), llvm::RISCVMCAsmInfo::getExprForFDESymbol(), llvm::SparcELFMCAsmInfo::getExprForFDESymbol(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::SparcELFMCAsmInfo::getExprForPersonalitySymbol(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), getSizeForEncoding(), hasUnfinishedDwarfFrameInfo(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::MCELFStreamer::InitSections(), llvm::MCWinCOFFStreamer::InitSections(), InitSections(), llvm::MCDwarfLineEntry::Make(), llvm::MCGenDwarfLabelEntry::Make(), matchRegisterNameHelper(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), printFPOReg(), smallData(), and tryEmitDwarfFileDirective().
getCurrentSection()
MCSectionSubPair llvm::MCStreamer::getCurrentSection () const inline
Return the current section that the streamer is emitting code to.
Definition at line 357 of file MCStreamer.h.
References llvm::SmallVectorTemplateCommon< T >::back(), and llvm::SmallVectorBase::empty().
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), and llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol().
getCurrentSectionOnly()
MCSection* llvm::MCStreamer::getCurrentSectionOnly () const inline
Definition at line 362 of file MCStreamer.h.
Referenced by llvm::AssemblerConstantPools::addEntry(), llvm::MCObjectStreamer::addPendingLabel(), canReuseBoundaryAlignFragment(), llvm::MCELFStreamer::ChangeSection(), CheckBundleSubtargets(), checkCVLocSection(), llvm::AssemblerConstantPools::clearCacheForCurrentSection(), llvm::MCELFStreamer::EmitBundleLock(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolIndex(), llvm::CodeViewContext::emitDefRange(), llvm::MCObjectStreamer::EmitDwarfLocDirective(), llvm::MCObjectStreamer::emitFill(), llvm::AssemblerConstantPools::emitForCurrentSection(), llvm::CodeViewContext::emitInlineLineTableForFunction(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MCELFStreamer::EmitLabel(), EmitLabel(), llvm::MCELFStreamer::EmitLabelAtPos(), llvm::MCObjectStreamer::EmitLabelAtPos(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::MCObjectStreamer::EmitValueToAlignment(), EmitWinCFIStartChained(), EmitWinCFIStartProc(), llvm::MCELFStreamer::FinishImpl(), llvm::MCObjectStreamer::flushPendingLabels(), llvm::MCObjectStreamer::getCurrentFragment(), hasVariantSymbol(), llvm::MCObjectStreamer::insert(), llvm::MCGenDwarfLabelEntry::Make(), and llvm::MCELFStreamer::MCELFStreamer().
getCurrentWinFrameInfo()
WinEH::FrameInfo* llvm::MCStreamer::getCurrentWinFrameInfo () inline protected
Definition at line 239 of file MCStreamer.h.
References FuncId.
getDwarfFrameInfos()
ArrayRef< MCDwarfFrameInfo > MCStreamer::getDwarfFrameInfos () const
Definition at line 114 of file MCStreamer.cpp.
Referenced by llvm::MCDwarfFrameEmitter::Emit(), and llvm::X86AsmPrinter::EmitInstruction().
getDwarfLineTableSymbol()
MCSymbol * MCStreamer::getDwarfLineTableSymbol (unsigned CUID) virtual
Definition at line 247 of file MCStreamer.cpp.
References llvm::MCContext::getAsmInfo(), getContext(), llvm::MCDwarfLineTable::getLabel(), llvm::MCContext::getMCDwarfLineTable(), llvm::MCContext::getOrCreateSymbol(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), llvm::cl::Prefix, and llvm::MCDwarfLineTable::setLabel().
Referenced by llvm::MCGenDwarfInfo::Emit(), and printDwarfFileDirective().
getNumFrameInfos()
unsigned MCStreamer::getNumFrameInfos ()
Definition at line 113 of file MCStreamer.cpp.
Referenced by llvm::MCObjectStreamer::EmitFrames(), and llvm::X86AsmPrinter::EmitInstruction().
getNumWinFrameInfos()
unsigned llvm::MCStreamer::getNumWinFrameInfos () inline
Definition at line 293 of file MCStreamer.h.
getPreviousSection()
MCSectionSubPair llvm::MCStreamer::getPreviousSection () const inline
Return the previous section that the streamer is emitting code to.
Definition at line 365 of file MCStreamer.h.
References llvm::SmallVectorTemplateCommon< T >::back(), and llvm::SmallVectorBase::empty().
GetSymbolOrder()
unsigned llvm::MCStreamer::GetSymbolOrder (const MCSymbol * Sym) const inline
Returns an index to represent the order a symbol was emitted in.
(zero if we did not emit that symbol)
Definition at line 373 of file MCStreamer.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
getTargetStreamer()
MCTargetStreamer* llvm::MCStreamer::getTargetStreamer () inline
Definition at line 273 of file MCStreamer.h.
Referenced by checkScale(), llvm::MipsELFStreamer::createPendingLabelRelocs(), EmitAssignment(), EmitLabel(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), Finish(), and printConstant().
getUseAssemblerInfoForParsing()
bool llvm::MCStreamer::getUseAssemblerInfoForParsing () inline
Definition at line 271 of file MCStreamer.h.
Referenced by llvm::MCObjectStreamer::getAssemblerPtr().
getWinFrameInfos()
ArrayRef<std::unique_ptr<WinEH::FrameInfo> > llvm::MCStreamer::getWinFrameInfos () const inline
Definition at line 294 of file MCStreamer.h.
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), and llvm::Win64EH::ARM64UnwindEmitter::Emit().
hasRawTextSupport()
virtual bool llvm::MCStreamer::hasRawTextSupport () const inline virtual
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
Definition at line 309 of file MCStreamer.h.
Referenced by makeCombineInst().
hasUnfinishedDwarfFrameInfo()
bool MCStreamer::hasUnfinishedDwarfFrameInfo ()
Definition at line 257 of file MCStreamer.cpp.
References getContext(), and llvm::MCContext::reportError().
Referenced by EmitCFIStartProc().
InitSections()
void MCStreamer::InitSections (bool NoExecStack) virtual
Create the default sections and set the initial one.
Reimplemented in llvm::MCWinCOFFStreamer, and llvm::MCELFStreamer.
Definition at line 387 of file MCStreamer.cpp.
References getContext(), and SwitchSection().
isIntegratedAssemblerRequired()
virtual bool llvm::MCStreamer::isIntegratedAssemblerRequired () const inline virtual
Is the integrated assembler required for this streamer to function correctly?
Reimplemented in llvm::MCObjectStreamer.
Definition at line 313 of file MCStreamer.h.
isVerboseAsm()
virtual bool llvm::MCStreamer::isVerboseAsm () const inline virtual
Return true if this streamer supports verbose assembly and if it is enabled.
Definition at line 305 of file MCStreamer.h.
Referenced by llvm::X86AsmPrinter::EmitInstruction().
mayHaveInstructions()
virtual bool llvm::MCStreamer::mayHaveInstructions (MCSection & Sec) const inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1032 of file MCStreamer.h.
References llvm::createAsmStreamer(), and llvm::createNullStreamer().
Referenced by llvm::MCContext::finalizeDwarfSections().
operator=()
MCStreamer& llvm::MCStreamer::operator= (const MCStreamer &) delete
PopSection()
bool llvm::MCStreamer::PopSection () inline
Restore the current and previous section from the section stack.
Calls ChangeSection as needed.
Returns false if the stack was empty.
Definition at line 393 of file MCStreamer.h.
References llvm::SmallVectorTemplateCommon< T >::end(), I, llvm::SmallVectorTemplateBase< T >::pop_back(), and llvm::SmallVectorBase::size().
Referenced by llvm::AMDGPUTargetELFStreamer::EmitAMDKernelCodeT(), llvm::AMDGPUTargetELFStreamer::EmitCodeEnd(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MCELFStreamer::EmitIdent(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and makeCombineInst().
PushSection()
void llvm::MCStreamer::PushSection () inline
Save the current and previous section on the section stack.
Definition at line 384 of file MCStreamer.h.
References llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::AMDGPUTargetELFStreamer::EmitAMDKernelCodeT(), llvm::AMDGPUTargetELFStreamer::EmitCodeEnd(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MCELFStreamer::EmitIdent(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and makeCombineInst().
reset()
void MCStreamer::reset () virtual
State management.
Reimplemented in llvm::MCObjectStreamer, llvm::MCWasmStreamer, llvm::MCWinCOFFStreamer, and llvm::MCELFStreamer.
Definition at line 99 of file MCStreamer.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), and llvm::MCObjectStreamer::reset().
setAllowAutoPadding()
void llvm::MCStreamer::setAllowAutoPadding (bool v) inline
Definition at line 277 of file MCStreamer.h.
Referenced by NoAutoPaddingScope::changeAndComment(), and llvm::MCObjectStreamer::MCObjectStreamer().
setTargetStreamer()
void llvm::MCStreamer::setTargetStreamer (MCTargetStreamer * TS) inline
Definition at line 258 of file MCStreamer.h.
Referenced by llvm::MCTargetStreamer::MCTargetStreamer().
setUseAssemblerInfoForParsing()
void llvm::MCStreamer::setUseAssemblerInfoForParsing (bool v) inline
Definition at line 270 of file MCStreamer.h.
SubSection()
bool llvm::MCStreamer::SubSection (const MCExpr * Subsection) inline
Definition at line 408 of file MCStreamer.h.
References llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorBase::empty(), and llvm::ARMBuildAttrs::Section.
SwitchSection()
void MCStreamer::SwitchSection (MCSection * Section, const MCExpr * Subsection = nullptr) virtual
Set the current section where code is being emitted to Section.
This is required to update CurSection.
This corresponds to assembler directives like .section, .text, etc.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 1103 of file MCStreamer.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), ChangeSection(), EmitLabel(), llvm::MCSection::getBeginSymbol(), and llvm::MCSection::hasEnded().
Referenced by llvm::BTFDebug::BTFDebug(), llvm::Win64EH::UnwindEmitter::Emit(), llvm::Win64EH::ARM64UnwindEmitter::Emit(), llvm::MCDwarfDwoLineTable::Emit(), llvm::MCDwarfLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), emitConstantPool(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), EmitDwarfLineTable(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::MCELFStreamer::EmitIdent(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), emitNonLazyStubs(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::MCDwarfLineStr::emitSection(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::Win64EH::UnwindEmitter::EmitUnwindInfo(), llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo(), endSection(), llvm::MipsTargetELFStreamer::finish(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::MCELFStreamer::InitSections(), llvm::MCWinCOFFStreamer::InitSections(), InitSections(), makeCombineInst(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), llvm::FaultMaps::serializeToFaultMapSection(), llvm::StackMaps::serializeToStackMapSection(), smallData(), and llvm::MipsELFStreamer::SwitchSection().
SwitchSectionNoChange()
void llvm::MCStreamer::SwitchSectionNoChange (MCSection * Section, const MCExpr * Subsection = nullptr) inline
Set the current section where code is being emitted to Section.
This is required to update CurSection. This version does not call ChangeSection.
Definition at line 426 of file MCStreamer.h.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), and llvm::ARMBuildAttrs::Symbol.
tryEmitDwarfFileDirective()
Expected< unsigned > MCStreamer::tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum = None, Optional< StringRef > Source = None, unsigned CUID = 0) virtual
Associate a filename with a specified logical file number.
Also associate a directory, optional checksum, and optional source text with the logical file. This implements the DWARF2 '.file 4 "dir/foo.c"' assembler directive, and the DWARF5 '.file 4 "dir/foo.c" md5 "..." source "..."' assembler directive.
Definition at line 213 of file MCStreamer.cpp.
References getContext(), and llvm::MCContext::getDwarfFile().
visitUsedExpr()
void MCStreamer::visitUsedExpr (const MCExpr & Expr)
Definition at line 989 of file MCStreamer.cpp.
References llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCExpr::Unary, and visitUsedSymbol().
Referenced by EmitAssignment(), EmitInstruction(), llvm::HexagonMCELFStreamer::EmitSymbol(), EmitValueImpl(), llvm::HexagonMCExpr::visitUsedExpr(), llvm::LanaiMCExpr::visitUsedExpr(), llvm::AVRMCExpr::visitUsedExpr(), llvm::ARMMCExpr::visitUsedExpr(), llvm::RISCVMCExpr::visitUsedExpr(), llvm::MipsMCExpr::visitUsedExpr(), llvm::PPCMCExpr::visitUsedExpr(), llvm::SparcMCExpr::visitUsedExpr(), and llvm::AArch64MCExpr::visitUsedExpr().
visitUsedSymbol()
void MCStreamer::visitUsedSymbol (const MCSymbol & Sym) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 986 of file MCStreamer.cpp.
Referenced by visitUsedExpr().
The documentation for this class was generated from the following files:
include/llvm/MC/MCStreamer.h
lib/MC/MCStreamer.cpp