LLVM: llvm::IntInit Class Reference
llvm::IntInit Class Reference
'7' - Represent an initialization by a literal integer value.
#include "llvm/TableGen/Record.h"
Public Member Functions
IntInit (const IntInit &)=delete
IntInit & operator= (const IntInit &)=delete
int64_t getValue () const
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a string form.
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Static Public Member Functions
static bool classof (const Init *I)
static IntInit * get (int64_t V)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First, IK_FirstTypedInit, IK_BitInit, IK_BitsInit,
IK_CodeInit, IK_DagInit, IK_DefInit, IK_FieldInit,
IK_IntInit, IK_ListInit, IK_FirstOpInit, IK_BinOpInit,
IK_TernOpInit, IK_UnOpInit, IK_LastOpInit, IK_CondOpInit,
IK_FoldOpInit, IK_IsAOpInit, IK_StringInit, IK_VarInit,
IK_VarListElementInit, IK_VarBitInit, IK_VarDefInit, IK_LastTypedInit,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
'7' - Represent an initialization by a literal integer value.
Definition at line 564 of file Record.h.
Constructor & Destructor Documentation
IntInit()
llvm::IntInit::IntInit (const IntInit &) delete
Member Function Documentation
classof()
static bool llvm::IntInit::classof (const Init * I) inline static
Definition at line 574 of file Record.h.
References llvm::Init::getKind().
convertInitializerBitRange()
Init * IntInit::convertInitializerBitRange (ArrayRef< unsigned > Bits) const override virtual
This method is used to implement the bitrange selection operator.
Given an initializer, it selects the specified bits out, returning them as a new init of bits type. If it is not legal to use the bit subscript operator on this initializer, return null.
Reimplemented from llvm::TypedInit.
Definition at line 505 of file Record.cpp.
References llvm::numbers::e, llvm::BitInit::get(), llvm::BitsInit::get(), and llvm::ArrayRef< T >::size().
convertInitializerTo()
Init * IntInit::convertInitializerTo (RecTy * Ty) const override virtual
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Reimplemented from llvm::TypedInit.
Definition at line 478 of file Record.cpp.
References canFitInBitfield(), llvm::BitInit::get(), and llvm::BitsInit::get().
get()
IntInit * IntInit::get (int64_t V) static
Definition at line 460 of file Record.cpp.
References Allocator, and I.
Referenced by llvm::BitInit::convertInitializerTo(), llvm::BitsInit::convertInitializerTo(), llvm::UnOpInit::Fold(), llvm::BinOpInit::Fold(), and llvm::IsAOpInit::Fold().
getAsString()
std::string IntInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 468 of file Record.cpp.
References llvm::itostr().
getBit()
Init* llvm::IntInit::getBit (unsigned Bit) const inline override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 588 of file Record.h.
References llvm::BitInit::get().
getValue()
int64_t llvm::IntInit::getValue () const inline
Definition at line 580 of file Record.h.
References llvm::tgtok::Bits.
Referenced by llvm::BinOpInit::Fold().
isConcrete()
bool llvm::IntInit::isConcrete () const inline override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 585 of file Record.h.
References llvm::RecTy::getAsString().
operator=()
IntInit& llvm::IntInit::operator= (const IntInit &) delete
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp