LLVM: llvm::MCRegUnitMaskIterator Class Reference
llvm::MCRegUnitMaskIterator Class Reference
MCRegUnitMaskIterator enumerates a list of register units and their associated lane masks for Reg.
#include "llvm/MC/MCRegisterInfo.h"
Public Member Functions
MCRegUnitMaskIterator ()=default
MCRegUnitMaskIterator (MCRegister Reg, const MCRegisterInfo *MCRI)
Constructs an iterator that traverses the register units and their associated LaneMasks in Reg.
std::pair< unsigned, LaneBitmask > operator* () const
Returns a (RegUnit, LaneMask) pair.
bool isValid () const
Returns true if this iterator is not yet at the end.
void operator++ ()
Moves to the next position.
Detailed Description
MCRegUnitMaskIterator enumerates a list of register units and their associated lane masks for Reg.
The register units are in ascending numerical order.
Definition at line 698 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
MCRegUnitMaskIterator() [1/2]
llvm::MCRegUnitMaskIterator::MCRegUnitMaskIterator () default
MCRegUnitMaskIterator() [2/2]
llvm::MCRegUnitMaskIterator::MCRegUnitMaskIterator (MCRegister Reg, const MCRegisterInfo * MCRI) inline
Constructs an iterator that traverses the register units and their associated LaneMasks in Reg.
Definition at line 707 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::get(), and llvm::MCRegisterDesc::RegUnitLaneMasks.
Member Function Documentation
isValid()
bool llvm::MCRegUnitMaskIterator::isValid () const inline
Returns true if this iterator is not yet at the end.
Definition at line 719 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::LiveRegUnits::addRegMasked(), foreachUnit(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::RegisterAggr::insert(), and updateLiveIn().
operator*()
std::pair<unsigned,LaneBitmask> llvm::MCRegUnitMaskIterator::operator* () const inline
Returns a (RegUnit, LaneMask) pair.
Definition at line 714 of file MCRegisterInfo.h.
operator++()
void llvm::MCRegUnitMaskIterator::operator++ () inline
Moves to the next position.
Definition at line 722 of file MCRegisterInfo.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCRegisterInfo.h