LLVM: llvm::LazyBranchProbabilityInfoPass Class Reference
llvm::LazyBranchProbabilityInfoPass Class Reference
This is an alternative analysis pass to BranchProbabilityInfoWrapperPass.
#include "llvm/Analysis/LazyBranchProbabilityInfo.h"
Public Member Functions
LazyBranchProbabilityInfoPass ()
BranchProbabilityInfo & getBPI ()
Compute and return the branch probabilities.
const BranchProbabilityInfo & getBPI () const
Compute and return the branch probabilities.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool runOnFunction (Function &F) override
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void print (raw_ostream &OS, const Module *M) const override
print - Print out the internal state of the pass.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Member Functions
static void getLazyBPIAnalysisUsage (AnalysisUsage &AU)
Helper for client passes to set up the analysis usage on behalf of this pass.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
This is an alternative analysis pass to BranchProbabilityInfoWrapperPass.
The difference is that with this pass the branch probabilities are not computed when the analysis pass is executed but rather when the BPI results is explicitly requested by the analysis client.
There are some additional requirements for any client pass that wants to use the analysis:
The pass needs to initialize dependent passes with:
INITIALIZE_PASS_DEPENDENCY(LazyBPIPass)
Similarly, getAnalysisUsage should call:
LazyBranchProbabilityInfoPass::getLazyBPIAnalysisUsage(AU)
The computed BPI should be requested with getAnalysis<LazyBranchProbabilityInfoPass>().getBPI() before LoopInfo could be invalidated for example by changing the CFG.
Note that it is expected that we wouldn't need this functionality for the new PM since with the new PM, analyses are executed on demand.
Definition at line 50 of file LazyBranchProbabilityInfo.h.
Constructor & Destructor Documentation
LazyBranchProbabilityInfoPass()
LazyBranchProbabilityInfoPass::LazyBranchProbabilityInfoPass ()
Definition at line 35 of file LazyBranchProbabilityInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeLazyBranchProbabilityInfoPassPass().
Member Function Documentation
getAnalysisUsage()
void LazyBranchProbabilityInfoPass::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 45 of file LazyBranchProbabilityInfo.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by getBPI().
getBPI() [1/2]
BranchProbabilityInfo& llvm::LazyBranchProbabilityInfoPass::getBPI () inline
Compute and return the branch probabilities.
Definition at line 92 of file LazyBranchProbabilityInfo.h.
Referenced by llvm::BPIPassTrait< LazyBranchProbabilityInfoPass >::getBPI().
getBPI() [2/2]
const BranchProbabilityInfo& llvm::LazyBranchProbabilityInfoPass::getBPI () const inline
Compute and return the branch probabilities.
Definition at line 95 of file LazyBranchProbabilityInfo.h.
References F(), getAnalysisUsage(), getLazyBPIAnalysisUsage(), llvm::initializeLazyBPIPassPass(), print(), releaseMemory(), and runOnFunction().
getLazyBPIAnalysisUsage()
void LazyBranchProbabilityInfoPass::getLazyBPIAnalysisUsage (AnalysisUsage & AU) static
Helper for client passes to set up the analysis usage on behalf of this pass.
Definition at line 65 of file LazyBranchProbabilityInfo.cpp.
References llvm::AnalysisUsage::addRequired().
Referenced by llvm::LazyBlockFrequencyInfoPass::getAnalysisUsage(), getBPI(), and llvm::LazyBlockFrequencyInfoPass::getLazyBFIAnalysisUsage().
print()
void LazyBranchProbabilityInfoPass::print (raw_ostream & OS, const Module * M) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 40 of file LazyBranchProbabilityInfo.cpp.
Referenced by getBPI().
releaseMemory()
void LazyBranchProbabilityInfoPass::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 55 of file LazyBranchProbabilityInfo.cpp.
Referenced by getBPI().
runOnFunction()
bool LazyBranchProbabilityInfoPass::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 57 of file LazyBranchProbabilityInfo.cpp.
References F().
Referenced by getBPI().
Member Data Documentation
ID
Lazy Branch Probability true char LazyBranchProbabilityInfoPass::ID = 0 static
Definition at line 87 of file LazyBranchProbabilityInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyBranchProbabilityInfo.h
lib/Analysis/LazyBranchProbabilityInfo.cpp