LLVM: llvm::codeview::VFTableRecord Class Reference
llvm::codeview::VFTableRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
VFTableRecord ()=default
VFTableRecord (TypeRecordKind Kind)
VFTableRecord (TypeIndex CompleteClass, TypeIndex OverriddenVFTable, uint32_t VFPtrOffset, StringRef Name, ArrayRef< StringRef > Methods)
TypeIndex getCompleteClass () const
TypeIndex getOverriddenVTable () const
uint32_t getVFPtrOffset () const
StringRef getName () const
ArrayRef< StringRef > getMethodNames () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex CompleteClass
TypeIndex OverriddenVFTable
uint32_t VFPtrOffset = 0
std::vector< StringRef > MethodNames
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 696 of file TypeRecord.h.
Constructor & Destructor Documentation
VFTableRecord() [1/3]
llvm::codeview::VFTableRecord::VFTableRecord () default
VFTableRecord() [2/3]
llvm::codeview::VFTableRecord::VFTableRecord (TypeRecordKind Kind) inline explicit
Definition at line 699 of file TypeRecord.h.
VFTableRecord() [3/3]
llvm::codeview::VFTableRecord::VFTableRecord (TypeIndex CompleteClass, TypeIndex OverriddenVFTable, uint32_t VFPtrOffset, StringRef Name, ArrayRef< StringRef > Methods) inline
Definition at line 700 of file TypeRecord.h.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
Member Function Documentation
getCompleteClass()
TypeIndex llvm::codeview::VFTableRecord::getCompleteClass () const inline
Definition at line 709 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getMethodNames()
ArrayRef<StringRef> llvm::codeview::VFTableRecord::getMethodNames () const inline
Definition at line 714 of file TypeRecord.h.
References llvm::makeArrayRef().
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getName()
StringRef llvm::codeview::VFTableRecord::getName () const inline
Definition at line 712 of file TypeRecord.h.
References llvm::makeArrayRef().
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getOverriddenVTable()
TypeIndex llvm::codeview::VFTableRecord::getOverriddenVTable () const inline
Definition at line 710 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getVFPtrOffset()
uint32_t llvm::codeview::VFTableRecord::getVFPtrOffset () const inline
Definition at line 711 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
CompleteClass
TypeIndex llvm::codeview::VFTableRecord::CompleteClass
Definition at line 718 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
MethodNames
std::vector<StringRef> llvm::codeview::VFTableRecord::MethodNames
Definition at line 721 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
OverriddenVFTable
TypeIndex llvm::codeview::VFTableRecord::OverriddenVFTable
Definition at line 719 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
VFPtrOffset
uint32_t llvm::codeview::VFTableRecord::VFPtrOffset = 0
Definition at line 720 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h