LLVM: llvm::SectionKind Class Reference
llvm::SectionKind Class Reference
SectionKind - This is a simple POD value that classifies the properties of a section.
#include "llvm/MC/SectionKind.h"
Public Member Functions
bool isMetadata () const
bool isText () const
bool isExecuteOnly () const
bool isReadOnly () const
bool isMergeableCString () const
bool isMergeable1ByteCString () const
bool isMergeable2ByteCString () const
bool isMergeable4ByteCString () const
bool isMergeableConst () const
bool isMergeableConst4 () const
bool isMergeableConst8 () const
bool isMergeableConst16 () const
bool isMergeableConst32 () const
bool isWriteable () const
bool isThreadLocal () const
bool isThreadBSS () const
bool isThreadData () const
bool isGlobalWriteableData () const
bool isBSS () const
bool isBSSLocal () const
bool isBSSExtern () const
bool isCommon () const
bool isData () const
bool isReadOnlyWithRel () const
Static Public Member Functions
static SectionKind getMetadata ()
static SectionKind getText ()
static SectionKind getExecuteOnly ()
static SectionKind getReadOnly ()
static SectionKind getMergeable1ByteCString ()
static SectionKind getMergeable2ByteCString ()
static SectionKind getMergeable4ByteCString ()
static SectionKind getMergeableConst4 ()
static SectionKind getMergeableConst8 ()
static SectionKind getMergeableConst16 ()
static SectionKind getMergeableConst32 ()
static SectionKind getThreadBSS ()
static SectionKind getThreadData ()
static SectionKind getBSS ()
static SectionKind getBSSLocal ()
static SectionKind getBSSExtern ()
static SectionKind getCommon ()
static SectionKind getData ()
static SectionKind getReadOnlyWithRel ()
Detailed Description
SectionKind - This is a simple POD value that classifies the properties of a section.
A section is classified into the deepest possible classification, and then the target maps them onto their sections based on what capabilities they have.
The comments below describe these as if they were an inheritance hierarchy in order to explain the predicates below.
Definition at line 22 of file SectionKind.h.
Member Function Documentation
getBSS()
static SectionKind llvm::SectionKind::getBSS () inline static
Definition at line 197 of file SectionKind.h.
Referenced by getELFKindForNamedSection(), llvm::TargetLoweringObjectFile::getKindForGlobal(), and useCompactUnwind().
getBSSExtern()
static SectionKind llvm::SectionKind::getBSSExtern () inline static
Definition at line 199 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
getBSSLocal()
static SectionKind llvm::SectionKind::getBSSLocal () inline static
Definition at line 198 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
getCommon()
static SectionKind llvm::SectionKind::getCommon () inline static
Definition at line 200 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
getData()
static SectionKind llvm::SectionKind::getData () inline static
Definition at line 201 of file SectionKind.h.
Referenced by computeSectionKind(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), GetAEABIUnwindPersonalityName(), getCOFFStaticStructorSection(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::TargetLoweringObjectFileWasm::getStaticCtorSection(), getWasmKindForNamedSection(), llvm::TargetLoweringObjectFileMachO::Initialize(), llvm::TargetLoweringObjectFileCOFF::Initialize(), llvm::TargetLoweringObjectFileWasm::InitializeWasm(), llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection(), and useCompactUnwind().
getExecuteOnly()
static SectionKind llvm::SectionKind::getExecuteOnly () inline static
Definition at line 180 of file SectionKind.h.
Referenced by llvm::MCContext::getELFSection(), llvm::ARMElfTargetObjectFile::getExplicitSectionGlobal(), and llvm::ARMElfTargetObjectFile::SelectSectionForGlobal().
getMergeable1ByteCString()
static SectionKind llvm::SectionKind::getMergeable1ByteCString () inline static
Definition at line 182 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal(), and useCompactUnwind().
getMergeable2ByteCString()
static SectionKind llvm::SectionKind::getMergeable2ByteCString () inline static
Definition at line 185 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal(), and useCompactUnwind().
getMergeable4ByteCString()
static SectionKind llvm::SectionKind::getMergeable4ByteCString () inline static
Definition at line 188 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
getMergeableConst16()
static SectionKind llvm::SectionKind::getMergeableConst16 () inline static
Definition at line 193 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MachineConstantPoolEntry::getSectionKind(), and useCompactUnwind().
getMergeableConst32()
static SectionKind llvm::SectionKind::getMergeableConst32 () inline static
Definition at line 194 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal(), and llvm::MachineConstantPoolEntry::getSectionKind().
getMergeableConst4()
static SectionKind llvm::SectionKind::getMergeableConst4 () inline static
Definition at line 191 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MachineConstantPoolEntry::getSectionKind(), and useCompactUnwind().
getMergeableConst8()
static SectionKind llvm::SectionKind::getMergeableConst8 () inline static
Definition at line 192 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MachineConstantPoolEntry::getSectionKind(), and useCompactUnwind().
getMetadata()
static SectionKind llvm::SectionKind::getMetadata () inline static
Definition at line 178 of file SectionKind.h.
Referenced by llvm::WebAssemblyAsmPrinter::EmitEndOfAsmFile(), emitNonLazyStubs(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), getELFKindForNamedSection(), llvm::AMDGPUTargetObjectFile::getExplicitSectionGlobal(), transformCallee(), and useCompactUnwind().
getReadOnly()
static SectionKind llvm::SectionKind::getReadOnly () inline static
Definition at line 181 of file SectionKind.h.
Referenced by computeSectionKind(), llvm::MCContext::createELFGroupSection(), llvm::MCContext::createELFRelSection(), llvm::AsmPrinter::doFinalization(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), getCOFFStaticStructorSection(), llvm::MCContext::getELFSection(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFile::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::MachineConstantPoolEntry::getSectionKind(), llvm::TargetLoweringObjectFileCOFF::Initialize(), and useCompactUnwind().
getReadOnlyWithRel()
static SectionKind llvm::SectionKind::getReadOnlyWithRel () inline static
Definition at line 202 of file SectionKind.h.
Referenced by llvm::AsmPrinter::emitXRayTable(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MachineConstantPoolEntry::getSectionKind(), and useCompactUnwind().
getText()
static SectionKind llvm::SectionKind::getText () inline static
Definition at line 179 of file SectionKind.h.
Referenced by computeSectionKind(), llvm::MCContext::getELFSection(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::HexagonTargetObjectFile::getLutUsedFunction(), getWasmKindForNamedSection(), and useCompactUnwind().
getThreadBSS()
static SectionKind llvm::SectionKind::getThreadBSS () inline static
Definition at line 195 of file SectionKind.h.
Referenced by getELFKindForNamedSection(), llvm::TargetLoweringObjectFile::getKindForGlobal(), and useCompactUnwind().
getThreadData()
static SectionKind llvm::SectionKind::getThreadData () inline static
Definition at line 196 of file SectionKind.h.
Referenced by getELFKindForNamedSection(), and llvm::TargetLoweringObjectFile::getKindForGlobal().
isBSS()
bool llvm::SectionKind::isBSS () const inline
Definition at line 159 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), getCOFFSectionFlags(), getCOFFSectionNameForUniqueGlobal(), getELFSectionType(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), getSectionPrefixForGlobal(), getXCoreSectionType(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isGlobalWriteableData(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::RISCVELFTargetObjectFile::SelectSectionForGlobal(), llvm::LanaiTargetObjectFile::SelectSectionForGlobal(), llvm::MipsTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection().
isBSSExtern()
bool llvm::SectionKind::isBSSExtern () const inline
Definition at line 161 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isBSSLocal()
bool llvm::SectionKind::isBSSLocal () const inline
Definition at line 160 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection().
isCommon()
bool llvm::SectionKind::isCommon () const inline
Definition at line 163 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isGlobalWriteableData(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection().
isData()
bool llvm::SectionKind::isData () const inline
Definition at line 165 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), getSectionPrefixForGlobal(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isGlobalWriteableData(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::RISCVELFTargetObjectFile::SelectSectionForGlobal(), llvm::LanaiTargetObjectFile::SelectSectionForGlobal(), llvm::MipsTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection().
isExecuteOnly()
bool llvm::SectionKind::isExecuteOnly () const inline
Definition at line 120 of file SectionKind.h.
Referenced by getELFSectionFlags(), and selectELFSectionForGlobal().
isGlobalWriteableData()
bool llvm::SectionKind::isGlobalWriteableData () const inline
Definition at line 155 of file SectionKind.h.
References isBSS(), isCommon(), isData(), and isReadOnlyWithRel().
Referenced by llvm::MCSectionWasm::isWasmData(), and isWriteable().
isMergeable1ByteCString()
bool llvm::SectionKind::isMergeable1ByteCString () const inline
Definition at line 131 of file SectionKind.h.
Referenced by getEntrySizeForKind(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
isMergeable2ByteCString()
bool llvm::SectionKind::isMergeable2ByteCString () const inline
Definition at line 132 of file SectionKind.h.
Referenced by getEntrySizeForKind(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isMergeable4ByteCString()
bool llvm::SectionKind::isMergeable4ByteCString () const inline
Definition at line 133 of file SectionKind.h.
Referenced by getEntrySizeForKind().
isMergeableConst()
bool llvm::SectionKind::isMergeableConst () const inline
Definition at line 135 of file SectionKind.h.
Referenced by getELFSectionFlags(), getEntrySizeForKind(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), isReadOnly(), selectELFSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection().
isMergeableConst16()
bool llvm::SectionKind::isMergeableConst16 () const inline
Definition at line 141 of file SectionKind.h.
Referenced by getEntrySizeForKind(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), getXCoreSectionFlags(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isMergeableConst32()
bool llvm::SectionKind::isMergeableConst32 () const inline
Definition at line 142 of file SectionKind.h.
Referenced by getEntrySizeForKind(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), and llvm::TargetLoweringObjectFileCOFF::getSectionForConstant().
isMergeableConst4()
bool llvm::SectionKind::isMergeableConst4 () const inline
Definition at line 139 of file SectionKind.h.
Referenced by getEntrySizeForKind(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), getXCoreSectionFlags(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isMergeableConst8()
bool llvm::SectionKind::isMergeableConst8 () const inline
Definition at line 140 of file SectionKind.h.
Referenced by getEntrySizeForKind(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), getXCoreSectionFlags(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isMergeableCString()
bool llvm::SectionKind::isMergeableCString () const inline
Definition at line 127 of file SectionKind.h.
Referenced by getELFSectionFlags(), getEntrySizeForKind(), getXCoreSectionFlags(), isReadOnly(), selectELFSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
isMetadata()
bool llvm::SectionKind::isMetadata () const inline
Definition at line 116 of file SectionKind.h.
Referenced by getCOFFSectionFlags(), getELFSectionFlags(), and getXCoreSectionFlags().
isReadOnly()
bool llvm::SectionKind::isReadOnly () const inline
Definition at line 122 of file SectionKind.h.
References isMergeableConst(), and isMergeableCString().
Referenced by getCOFFSectionFlags(), getCOFFSectionNameForUniqueGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFile::getSectionForConstant(), getSectionPrefixForGlobal(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::MCSectionWasm::isWasmData(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::AMDGPUTargetObjectFile::SelectSectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::MipsTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
isReadOnlyWithRel()
bool llvm::SectionKind::isReadOnlyWithRel () const inline
Definition at line 167 of file SectionKind.h.
Referenced by getCOFFSectionFlags(), getCOFFSectionNameForUniqueGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), getSectionPrefixForGlobal(), isGlobalWriteableData(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
isText()
bool llvm::SectionKind::isText () const inline
Definition at line 118 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitAlignment(), getCOFFSectionFlags(), getCOFFSectionNameForUniqueGlobal(), getELFSectionFlags(), getSectionPrefixForGlobal(), getWasmKindForNamedSection(), getXCoreSectionFlags(), isDwarfSection(), isExecuteOnlyFunction(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), llvm::MCSectionXCOFF::UseCodeAlign(), and llvm::MCSectionCOFF::UseCodeAlign().
isThreadBSS()
bool llvm::SectionKind::isThreadBSS () const inline
Definition at line 152 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), getELFSectionType(), getSectionPrefixForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isThreadData()
bool llvm::SectionKind::isThreadData () const inline
Definition at line 153 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), getSectionPrefixForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isThreadLocal()
bool llvm::SectionKind::isThreadLocal () const inline
Definition at line 148 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), getCOFFSectionFlags(), getCOFFSectionNameForUniqueGlobal(), getELFSectionFlags(), llvm::MCSectionWasm::isWasmData(), isWriteable(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
isWriteable()
bool llvm::SectionKind::isWriteable () const inline
Definition at line 144 of file SectionKind.h.
References isGlobalWriteableData(), and isThreadLocal().
Referenced by getCOFFSectionFlags(), getELFSectionFlags(), getXCoreSectionFlags(), and isDwarfSection().
The documentation for this class was generated from the following file:
include/llvm/MC/SectionKind.h