LLVM: llvm::MachinePassRegistryNode< PassCtorTy > Class Template Reference
llvm::MachinePassRegistryNode< PassCtorTy > Class Template Reference
MachinePassRegistryNode - Machine pass node stored in registration list.
#include "llvm/CodeGen/MachinePassRegistry.h"
Public Member Functions
MachinePassRegistryNode (const char *N, const char *D, PassCtorTy C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
StringRef getName () const
StringRef getDescription () const
PassCtorTy getCtor () const
void setNext (MachinePassRegistryNode *N)
Detailed Description
template<typename PassCtorTy>
class llvm::MachinePassRegistryNode< PassCtorTy >
MachinePassRegistryNode - Machine pass node stored in registration list.
Definition at line 48 of file MachinePassRegistry.h.
Constructor & Destructor Documentation
MachinePassRegistryNode()
template<typename PassCtorTy> llvm::MachinePassRegistryNode< PassCtorTy >::MachinePassRegistryNode (const char * N, const char * D, PassCtorTy C) inline
Definition at line 56 of file MachinePassRegistry.h.
Member Function Documentation
getCtor()
template<typename PassCtorTy> PassCtorTy llvm::MachinePassRegistryNode< PassCtorTy >::getCtor () const inline
Definition at line 64 of file MachinePassRegistry.h.
getDescription()
template<typename PassCtorTy> StringRef llvm::MachinePassRegistryNode< PassCtorTy >::getDescription () const inline
Definition at line 63 of file MachinePassRegistry.h.
getName()
template<typename PassCtorTy> StringRef llvm::MachinePassRegistryNode< PassCtorTy >::getName () const inline
Definition at line 62 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry< FunctionPassCtor >::Remove().
getNext()
template<typename PassCtorTy> MachinePassRegistryNode* llvm::MachinePassRegistryNode< PassCtorTy >::getNext () const inline
Definition at line 60 of file MachinePassRegistry.h.
Referenced by llvm::RegisterRegAllocBase< RegisterRegAlloc >::getNext(), llvm::RegisterScheduler::getNext(), and llvm::MachineSchedRegistry::getNext().
getNextAddress()
template<typename PassCtorTy> MachinePassRegistryNode** llvm::MachinePassRegistryNode< PassCtorTy >::getNextAddress () inline
Definition at line 61 of file MachinePassRegistry.h.
setNext()
template<typename PassCtorTy> void llvm::MachinePassRegistryNode< PassCtorTy >::setNext (MachinePassRegistryNode< PassCtorTy > * N) inline
Definition at line 65 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry< FunctionPassCtor >::Add().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachinePassRegistry.h