LLVM: llvm::pdb::DbiModuleList Class Reference
llvm::pdb::DbiModuleList Class Reference
#include "llvm/DebugInfo/PDB/Native/DbiModuleList.h"
Public Member Functions
Error initialize (BinaryStreamRef ModInfo, BinaryStreamRef FileInfo)
Expected< StringRef > getFileName (uint32_t Index) const
uint32_t getModuleCount () const
uint32_t getSourceFileCount () const
uint16_t getSourceFileCount (uint32_t Modi) const
iterator_range< DbiModuleSourceFilesIterator > source_files (uint32_t Modi) const
DbiModuleDescriptor getModuleDescriptor (uint32_t Modi) const
Detailed Description
Definition at line 69 of file DbiModuleList.h.
Member Function Documentation
getFileName()
Expected< StringRef > DbiModuleList::getFileName (uint32_t Index) const
Definition at line 268 of file DbiModuleList.cpp.
References llvm::pdb::index_out_of_bounds, Name, llvm::BinaryStreamReader::readCString(), and llvm::BinaryStreamReader::setOffset().
Referenced by llvm::pdb::DbiModuleSourceFilesIterator::operator-=().
getModuleCount()
uint32_t DbiModuleList::getModuleCount () const
Definition at line 241 of file DbiModuleList.cpp.
Referenced by llvm::pdb::SymbolCache::getNumCompilands(), llvm::pdb::DbiModuleSourceFilesIterator::operator-=(), and llvm::pdb::SymbolCache::SymbolCache().
getModuleDescriptor()
DbiModuleDescriptor DbiModuleList::getModuleDescriptor (uint32_t Modi) const
Definition at line 253 of file DbiModuleList.cpp.
References assert().
Referenced by llvm::pdb::SymbolCache::getOrCreateCompiland().
getSourceFileCount() [1/2]
uint32_t DbiModuleList::getSourceFileCount () const
Definition at line 245 of file DbiModuleList.cpp.
Referenced by llvm::pdb::DbiModuleSourceFilesIterator::operator-(), and llvm::pdb::DbiModuleSourceFilesIterator::operator-=().
getSourceFileCount() [2/2]
uint16_t DbiModuleList::getSourceFileCount (uint32_t Modi) const
Definition at line 249 of file DbiModuleList.cpp.
initialize()
Error DbiModuleList::initialize (BinaryStreamRef ModInfo, BinaryStreamRef FileInfo)
Definition at line 162 of file DbiModuleList.cpp.
References assert(), llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), I, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), llvm::BinaryStreamReader::readStreamRef(), and llvm::Error::success().
Referenced by llvm::pdb::DbiStream::reload().
source_files()
iterator_range< DbiModuleSourceFilesIterator > DbiModuleList::source_files (uint32_t Modi) const
Definition at line 262 of file DbiModuleList.cpp.
References llvm::pdb::DbiModuleSourceFilesIterator::DbiModuleSourceFilesIterator().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/DbiModuleList.h
lib/DebugInfo/PDB/Native/DbiModuleList.cpp