LLVM: llvm::MIBundleBuilder Class Reference
llvm::MIBundleBuilder Class Reference
Helper class for constructing bundles of MachineInstrs.
#include "llvm/CodeGen/MachineInstrBuilder.h"
Public Member Functions
MIBundleBuilder (MachineBasicBlock &BB, MachineBasicBlock::iterator Pos)
Create an MIBundleBuilder that inserts instructions into a new bundle in BB above the bundle or instruction at Pos.
MIBundleBuilder (MachineBasicBlock &BB, MachineBasicBlock::iterator B, MachineBasicBlock::iterator E)
Create a bundle from the sequence of instructions between B and E.
MIBundleBuilder (MachineInstr *MI)
Create an MIBundleBuilder representing an existing instruction or bundle that has MI as its head.
MachineBasicBlock & getMBB () const
Return a reference to the basic block containing this bundle.
bool empty () const
Return true if no instructions have been inserted in this bundle yet.
MachineBasicBlock::instr_iterator begin () const
Return an iterator to the first bundled instruction.
MachineBasicBlock::instr_iterator end () const
Return an iterator beyond the last bundled instruction.
MIBundleBuilder & insert (MachineBasicBlock::instr_iterator I, MachineInstr *MI)
Insert MI into this bundle before I which must point to an instruction in the bundle, or end().
MIBundleBuilder & prepend (MachineInstr *MI)
Insert MI into MBB by prepending it to the instructions in the bundle.
MIBundleBuilder & append (MachineInstr *MI)
Insert MI into MBB by appending it to the instructions in the bundle.
Detailed Description
Helper class for constructing bundles of MachineInstrs.
MIBundleBuilder can create a bundle from scratch by inserting new MachineInstrs one at a time, or it can create a bundle from a sequence of existing MachineInstrs in a basic block.
Definition at line 512 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
MIBundleBuilder() [1/3]
llvm::MIBundleBuilder::MIBundleBuilder (MachineBasicBlock & BB, MachineBasicBlock::iterator Pos) inline
Create an MIBundleBuilder that inserts instructions into a new bundle in BB above the bundle or instruction at Pos.
Definition at line 520 of file MachineInstrBuilder.h.
MIBundleBuilder() [2/3]
llvm::MIBundleBuilder::MIBundleBuilder (MachineBasicBlock & BB, MachineBasicBlock::iterator B, MachineBasicBlock::iterator E) inline
Create a bundle from the sequence of instructions between B and E.
Definition at line 524 of file MachineInstrBuilder.h.
References assert(), B, llvm::MachineInstr::bundleWithPred(), and MI.
MIBundleBuilder() [3/3]
llvm::MIBundleBuilder::MIBundleBuilder (MachineInstr * MI) inline explicit
Create an MIBundleBuilder representing an existing instruction or bundle that has MI as its head.
Definition at line 538 of file MachineInstrBuilder.h.
Member Function Documentation
append()
MIBundleBuilder& llvm::MIBundleBuilder::append (MachineInstr * MI) inline
Insert MI into MBB by appending it to the instructions in the bundle.
MI will become the last instruction in the bundle.
Definition at line 585 of file MachineInstrBuilder.h.
References llvm::sys::path::end().
Referenced by emitGPDisp(), llvm::SIInstrInfo::expandPostRAPseudo(), and for().
begin()
MachineBasicBlock::instr_iterator llvm::MIBundleBuilder::begin () const inline
Return an iterator to the first bundled instruction.
Definition at line 550 of file MachineInstrBuilder.h.
Referenced by llvm::SITargetLowering::bundleInstWithWaitcnt(), and llvm::SIInstrInfo::expandPostRAPseudo().
empty()
bool llvm::MIBundleBuilder::empty () const inline
Return true if no instructions have been inserted in this bundle yet.
Empty bundles aren't representable in a MachineBasicBlock.
Definition at line 547 of file MachineInstrBuilder.h.
end()
MachineBasicBlock::instr_iterator llvm::MIBundleBuilder::end () const inline
Return an iterator beyond the last bundled instruction.
Definition at line 553 of file MachineInstrBuilder.h.
getMBB()
MachineBasicBlock& llvm::MIBundleBuilder::getMBB () const inline
Return a reference to the basic block containing this bundle.
Definition at line 543 of file MachineInstrBuilder.h.
insert()
MIBundleBuilder& llvm::MIBundleBuilder::insert (MachineBasicBlock::instr_iterator I, MachineInstr * MI) inline
Insert MI into this bundle before I which must point to an instruction in the bundle, or end().
Definition at line 557 of file MachineInstrBuilder.h.
References llvm::MachineInstr::BundledPred, llvm::MachineInstr::BundledSucc, llvm::MachineInstr::bundleWithPred(), llvm::MachineInstr::bundleWithSucc(), llvm::empty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::insert(), and llvm::MachineInstr::setFlag().
prepend()
MIBundleBuilder& llvm::MIBundleBuilder::prepend (MachineInstr * MI) inline
Insert MI into MBB by prepending it to the instructions in the bundle.
MI will become the first instruction in the bundle.
Definition at line 579 of file MachineInstrBuilder.h.
References llvm::sys::path::begin().
Referenced by llvm::finalizeBundle().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineInstrBuilder.h