LLVM: llvm::ErrorOr< T > Class Template Reference
llvm::ErrorOr< T > Class Template Reference
Represents either an error or a value T.
#include "llvm/Support/ErrorOr.h"
Public Types
using storage_type = typename std::conditional< isRef, wrap, T >::type
Public Member Functions
template<class E >
ErrorOr (E ErrorCode, typename std::enable_if< std::is_error_code_enum< E >::value||std::is_error_condition_enum< E >::value, void *>::type=nullptr)
ErrorOr (std::error_code EC)
template<class OtherT >
ErrorOr (OtherT &&Val, typename std::enable_if< std::is_convertible< OtherT, T >::value >::type *=nullptr)
ErrorOr (const ErrorOr &Other)
template<class OtherT >
ErrorOr (const ErrorOr< OtherT > &Other, typename std::enable_if< std::is_convertible< OtherT, T >::value >::type *=nullptr)
template<class OtherT >
ErrorOr (const ErrorOr< OtherT > &Other, typename std::enable_if< !std::is_convertible< OtherT, const T &>::value >::type *=nullptr)
ErrorOr (ErrorOr &&Other)
template<class OtherT >
ErrorOr (ErrorOr< OtherT > &&Other, typename std::enable_if< std::is_convertible< OtherT, T >::value >::type *=nullptr)
template<class OtherT >
ErrorOr (ErrorOr< OtherT > &&Other, typename std::enable_if<!std::is_convertible< OtherT, T >::value >::type *=nullptr)
ErrorOr & operator= (const ErrorOr &Other)
ErrorOr & operator= (ErrorOr &&Other)
~ErrorOr ()
operator bool () const
Return false if there is an error.
reference get ()
const_reference get () const
std::error_code getError () const
pointer operator-> ()
const_pointer operator-> () const
reference operator* ()
const_reference operator* () const
Friends
template<class OtherT >
class ErrorOr
Detailed Description
template<class T>
class llvm::ErrorOr< T >
Represents either an error or a value T.
ErrorOr<T> is a pointer-like class that represents the result of an operation. The result is either an error, or a value of type T. This is designed to emulate the usage of returning a pointer where nullptr indicates failure. However instead of just knowing that the operation failed, we also have an error_code and optional user data that describes why it failed.
It is used like the following.
ErrorOr<Buffer> getBuffer();
auto buffer = getBuffer();
if (error_code ec = buffer.getError())
  return ec;
buffer->write("adena");
Implicit conversion to bool returns true if there is a usable value. The unary * and -> operators provide pointer like access to the value. Accessing the value when there is an error has undefined behavior.
When T is a reference type the behavior is slightly different. The reference is held in a std::reference_wrapper<std::remove_reference<T>::type>, and there is special handling to make operator -> work as if T was not a reference.
T cannot be a rvalue reference.
Definition at line 56 of file ErrorOr.h.
Member Typedef Documentation
storage_type
template<class T> using llvm::ErrorOr< T >::storage_type = typename std::conditional<isRef, wrap, T>::type
Definition at line 64 of file ErrorOr.h.
Constructor & Destructor Documentation
ErrorOr() [1/9]
template<class T> template<class E > llvm::ErrorOr< T >::ErrorOr (E ErrorCode, typename std::enable_if< std::is_error_code_enum< E >::value||std::is_error_condition_enum< E >::value, void *>::type = nullptr) inline
Definition at line 74 of file ErrorOr.h.
References llvm::make_error_code().
ErrorOr() [2/9]
template<class T> llvm::ErrorOr< T >::ErrorOr (std::error_code EC) inline
Definition at line 82 of file ErrorOr.h.
ErrorOr() [3/9]
template<class T> template<class OtherT > llvm::ErrorOr< T >::ErrorOr (OtherT && Val, typename std::enable_if< std::is_convertible< OtherT, T >::value >::type * = nullptr) inline
Definition at line 87 of file ErrorOr.h.
ErrorOr() [4/9]
template<class T> llvm::ErrorOr< T >::ErrorOr (const ErrorOr< T > & Other) inline
Definition at line 94 of file ErrorOr.h.
ErrorOr() [5/9]
template<class T> template<class OtherT > llvm::ErrorOr< T >::ErrorOr (const ErrorOr< OtherT > & Other, typename std::enable_if< std::is_convertible< OtherT, T >::value >::type * = nullptr) inline
Definition at line 99 of file ErrorOr.h.
ErrorOr() [6/9]
template<class T> template<class OtherT > llvm::ErrorOr< T >::ErrorOr (const ErrorOr< OtherT > & Other, typename std::enable_if< !std::is_convertible< OtherT, const T &>::value >::type * = nullptr) inline explicit
Definition at line 107 of file ErrorOr.h.
ErrorOr() [7/9]
template<class T> llvm::ErrorOr< T >::ErrorOr (ErrorOr< T > && Other) inline
Definition at line 114 of file ErrorOr.h.
References llvm::Other.
ErrorOr() [8/9]
template<class T> template<class OtherT > llvm::ErrorOr< T >::ErrorOr (ErrorOr< OtherT > && Other, typename std::enable_if< std::is_convertible< OtherT, T >::value >::type * = nullptr) inline
Definition at line 119 of file ErrorOr.h.
References llvm::Other.
ErrorOr() [9/9]
template<class T> template<class OtherT > llvm::ErrorOr< T >::ErrorOr (ErrorOr< OtherT > && Other, typename std::enable_if<!std::is_convertible< OtherT, T >::value >::type * = nullptr) inline explicit
Definition at line 129 of file ErrorOr.h.
References llvm::Other.
~ErrorOr()
template<class T> llvm::ErrorOr< T >::~ErrorOr () inline
Definition at line 146 of file ErrorOr.h.
Referenced by llvm::ErrorOr< T >::operator*().
Member Function Documentation
get() [1/2]
template<class T> reference llvm::ErrorOr< T >::get () inline
Definition at line 156 of file ErrorOr.h.
Referenced by branchDiv(), llvm::object::createBinary(), llvm::LTOModule::createFromFile(), llvm::LTOModule::createFromOpenFileSlice(), llvm::SpecialCaseList::createInternal(), llvm::object::ObjectFile::createObjectFile(), llvm::DiffFilesWithTolerance(), doList(), ExpandResponseFile(), llvm::symbolize::LLVMSymbolizer::flush(), llvm::LTOModule::isBitcodeFile(), LLVMCreateMemoryBufferWithContentsOfFile(), LLVMCreateMemoryBufferWithSTDIN(), LLVMGetBitcodeModuleInContext2(), LLVMParseBitcodeInContext2(), llvm::pdb::PDBContext::PDBContext(), and setupMemoryBuffer().
get() [2/2]
template<class T> const_reference llvm::ErrorOr< T >::get () const inline
Definition at line 157 of file ErrorOr.h.
getError()
template<class T> std::error_code llvm::ErrorOr< T >::getError () const inline
Definition at line 159 of file ErrorOr.h.
Referenced by branchDiv(), llvm::LTOCodeGenerator::compileOptimized(), llvm::object::createBinary(), llvm::LTOModule::createFromFile(), llvm::LTOModule::createFromOpenFileSlice(), llvm::SpecialCaseList::createInternal(), llvm::object::ObjectFile::createObjectFile(), llvm::remarks::createYAMLParserFromMeta(), llvm::DiffFilesWithTolerance(), llvm::vfs::RedirectingFileSystem::dir_begin(), doList(), ExpandResponseFile(), llvm::object::Archive::Child::getBuffer(), llvm::NewArchiveMember::getFile(), llvm::sys::getHostCPUName(), llvm::getModuleSummaryIndexForFile(), getProcCpuinfoContent(), llvm::vfs::RedirectingFileSystem::getRealPath(), LLVMCreateMemoryBufferWithContentsOfFile(), LLVMCreateMemoryBufferWithSTDIN(), LLVMGetBitcodeModuleInContext2(), LLVMParseBitcodeInContext2(), llvm::pdb::loadDataForPDB(), llvm::lto::localCache(), openFile(), llvm::vfs::RedirectingFileSystem::openFileForRead(), llvm::ErrorOr< T >::operator*(), llvm::SymbolRewriter::RewriteMapParser::parse(), parseBitcodeFileImpl(), processRemarkVersion(), setupMemoryBuffer(), llvm::vfs::OverlayFileSystem::status(), llvm::vfs::RedirectingFileSystem::status(), and llvm::TableGenMain().
operator bool()
template<class T> llvm::ErrorOr< T >::operator bool () const inline explicit
Return false if there is an error.
Definition at line 152 of file ErrorOr.h.
operator*() [1/2]
template<class T> reference llvm::ErrorOr< T >::operator* () inline
Definition at line 169 of file ErrorOr.h.
operator*() [2/2]
template<class T> const_reference llvm::ErrorOr< T >::operator* () const inline
Definition at line 173 of file ErrorOr.h.
References assert(), llvm::AlignedCharArrayUnion< T, Ts >::buffer, llvm::ErrorOr< T >::ErrorOr, llvm::ErrorOr< T >::ErrorStorage, llvm::ErrorOr< T >::getError(), llvm::Other, T1, llvm::ErrorOr< T >::TStorage, and llvm::ErrorOr< T >::~ErrorOr().
operator->() [1/2]
template<class T> pointer llvm::ErrorOr< T >::operator-> () inline
Definition at line 163 of file ErrorOr.h.
operator->() [2/2]
template<class T> const_pointer llvm::ErrorOr< T >::operator-> () const inline
Definition at line 167 of file ErrorOr.h.
operator=() [1/2]
template<class T> ErrorOr& llvm::ErrorOr< T >::operator= (const ErrorOr< T > & Other) inline
Definition at line 136 of file ErrorOr.h.
operator=() [2/2]
template<class T> ErrorOr& llvm::ErrorOr< T >::operator= (ErrorOr< T > && Other) inline
Definition at line 141 of file ErrorOr.h.
References llvm::Other.
Friends And Related Function Documentation
ErrorOr
template<class T> template<class OtherT > friend class ErrorOr friend
Definition at line 57 of file ErrorOr.h.
Referenced by llvm::ErrorOr< T >::operator*().
Member Data Documentation
ErrorStorage
template<class T> AlignedCharArrayUnion<std::error_code> llvm::ErrorOr< T >::ErrorStorage
Definition at line 263 of file ErrorOr.h.
Referenced by llvm::ErrorOr< T >::operator*().
TStorage
template<class T> AlignedCharArrayUnion<storage_type> llvm::ErrorOr< T >::TStorage
Definition at line 262 of file ErrorOr.h.
Referenced by llvm::ErrorOr< T >::operator*().
The documentation for this class was generated from the following file:
include/llvm/Support/ErrorOr.h