LLVM: llvm::orc::ImplSymbolMap Class Reference
llvm::orc::ImplSymbolMap Class Reference
#include "llvm/ExecutionEngine/Orc/Speculation.h"
Public Types
using AliaseeDetails = std::pair< SymbolStringPtr, JITDylib * >
using Alias = SymbolStringPtr
using ImapTy = DenseMap< Alias, AliaseeDetails >
Public Member Functions
void trackImpls (SymbolAliasMap ImplMaps, JITDylib *SrcJD)
Friends
class Speculator
Detailed Description
Definition at line 39 of file Speculation.h.
Member Typedef Documentation
Alias
using llvm::orc::ImplSymbolMap::Alias = SymbolStringPtr
Definition at line 44 of file Speculation.h.
AliaseeDetails
using llvm::orc::ImplSymbolMap::AliaseeDetails = std::pair<SymbolStringPtr, JITDylib *>
Definition at line 43 of file Speculation.h.
ImapTy
using llvm::orc::ImplSymbolMap::ImapTy = DenseMap<Alias, AliaseeDetails>
Definition at line 45 of file Speculation.h.
Member Function Documentation
trackImpls()
void llvm::orc::ImplSymbolMap::trackImpls (SymbolAliasMap ImplMaps, JITDylib * SrcJD)
Definition at line 28 of file Speculation.cpp.
References assert(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), and llvm::orc::Speculator::speculateFor().
Referenced by llvm::orc::LazyReexportsMaterializationUnit::getName().
Friends And Related Function Documentation
Speculator
friend class Speculator friend
Definition at line 40 of file Speculation.h.
Referenced by llvm::orc::Speculator::Speculator().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Speculation.h
lib/ExecutionEngine/Orc/Speculation.cpp