LLVM: llvm::codeview::EnumeratorRecord Class Reference
llvm::codeview::EnumeratorRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
EnumeratorRecord ()=default
EnumeratorRecord (TypeRecordKind Kind)
EnumeratorRecord (MemberAttributes Attrs, APSInt Value, StringRef Name)
EnumeratorRecord (MemberAccess Access, APSInt Value, StringRef Name)
MemberAccess getAccess () const
APSInt getValue () const
StringRef getName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
MemberAttributes Attrs
APSInt Value
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 835 of file TypeRecord.h.
Constructor & Destructor Documentation
EnumeratorRecord() [1/4]
llvm::codeview::EnumeratorRecord::EnumeratorRecord () default
EnumeratorRecord() [2/4]
llvm::codeview::EnumeratorRecord::EnumeratorRecord (TypeRecordKind Kind) inline explicit
Definition at line 838 of file TypeRecord.h.
EnumeratorRecord() [3/4]
llvm::codeview::EnumeratorRecord::EnumeratorRecord (MemberAttributes Attrs, APSInt Value, StringRef Name) inline
Definition at line 839 of file TypeRecord.h.
References llvm::Enumerator.
EnumeratorRecord() [4/4]
llvm::codeview::EnumeratorRecord::EnumeratorRecord (MemberAccess Access, APSInt Value, StringRef Name) inline
Definition at line 842 of file TypeRecord.h.
References llvm::Enumerator.
Member Function Documentation
getAccess()
MemberAccess llvm::codeview::EnumeratorRecord::getAccess () const inline
Definition at line 846 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
getName()
StringRef llvm::codeview::EnumeratorRecord::getName () const inline
Definition at line 848 of file TypeRecord.h.
References Name.
Referenced by llvm::pdb::NativeTypeEnum::getName(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
getValue()
APSInt llvm::codeview::EnumeratorRecord::getValue () const inline
Definition at line 847 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
Member Data Documentation
Attrs
MemberAttributes llvm::codeview::EnumeratorRecord::Attrs
Definition at line 850 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Name
StringRef llvm::codeview::EnumeratorRecord::Name
Definition at line 852 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Value
APSInt llvm::codeview::EnumeratorRecord::Value
Definition at line 851 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h