LLVM: ParameterPackExpansion Class Reference
ParameterPackExpansion Class Reference final
A pack expansion.
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
ParameterPackExpansion (const Node *Child_)
template<typename Fn >
void match (Fn F) const
const Node * getChild () const
void printLeft (OutputStream &S) const override
Public Member Functions inherited from Node
Node (Kind K_, Cache RHSComponentCache_=Cache::No, Cache ArrayCache_=Cache::No, Cache FunctionCache_=Cache::No)
template<typename Fn >
void visit (Fn F) const
Visit the most-derived object corresponding to this object.
bool hasRHSComponent (OutputStream &S) const
bool hasArray (OutputStream &S) const
bool hasFunction (OutputStream &S) const
Kind getKind () const
virtual bool hasRHSComponentSlow (OutputStream &) const
virtual bool hasArraySlow (OutputStream &) const
virtual bool hasFunctionSlow (OutputStream &) const
virtual const Node * getSyntaxNode (OutputStream &) const
void print (OutputStream &S) const
virtual void printRight (OutputStream &) const
virtual StringView getBaseName () const
virtual ~Node ()=default
DEMANGLE_DUMP_METHOD void dump () const
Additional Inherited Members
Public Types inherited from Node
enum Kind : unsigned char
enum Cache : unsigned char { Cache::Yes, Cache::No, Cache::Unknown }
Three-way bool to track a cached value.
Public Attributes inherited from Node
Cache RHSComponentCache
Tracks if this node has a component on its right side, in which case we need to call printRight.
Cache ArrayCache
Track if this node is a (possibly qualified) array type.
Cache FunctionCache
Track if this node is a (possibly qualified) function type.
Detailed Description
A pack expansion.
Below this node, there are some unexpanded ParameterPacks which each have Child->ParameterPackSize elements.
Definition at line 1150 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
ParameterPackExpansion()
ParameterPackExpansion::ParameterPackExpansion (const Node * Child_) inline
Definition at line 1154 of file ItaniumDemangle.h.
Member Function Documentation
getChild()
const Node* ParameterPackExpansion::getChild () const inline
Definition at line 1159 of file ItaniumDemangle.h.
match()
template<typename Fn > void ParameterPackExpansion::match (Fn F) const inline
Definition at line 1157 of file ItaniumDemangle.h.
References F().
printLeft()
void ParameterPackExpansion::printLeft (OutputStream & S) const inline override virtual
Implements Node.
Definition at line 1161 of file ItaniumDemangle.h.
References OutputStream::CurrentPackIndex, OutputStream::CurrentPackMax, E, OutputStream::getCurrentPosition(), I, llvm::max(), and OutputStream::setCurrentPosition().
Referenced by SizeofParamPackExpr::printLeft().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h