LLVM: llvm::RegScavenger Class Reference
llvm::RegScavenger Class Reference
#include "llvm/CodeGen/RegisterScavenging.h"
Public Member Functions
RegScavenger ()=default
void enterBasicBlock (MachineBasicBlock &MBB)
Start tracking liveness from the begin of basic block MBB.
void enterBasicBlockEnd (MachineBasicBlock &MBB)
Start tracking liveness from the end of basic block MBB.
void forward ()
Move the internal MBB iterator and update register states.
void forward (MachineBasicBlock::iterator I)
Move the internal MBB iterator and update register states until it has processed the specific iterator.
void unprocess ()
Invert the behavior of forward() on the current instruction (undo the changes to the available registers made by forward()).
void unprocess (MachineBasicBlock::iterator I)
Unprocess instructions until you reach the provided iterator.
void backward ()
Update internal register state and move MBB iterator backwards.
void backward (MachineBasicBlock::iterator I)
Call backward() as long as the internal iterator does not point to I.
void skipTo (MachineBasicBlock::iterator I)
Move the internal MBB iterator but do not update register states.
MachineBasicBlock::iterator getCurrentPosition () const
bool isRegUsed (Register Reg, bool includeReserved=true) const
Return if a specific register is currently used.
BitVector getRegsAvailable (const TargetRegisterClass *RC)
Return all available registers in the register class in Mask.
Register FindUnusedReg (const TargetRegisterClass *RC) const
Find an unused register of the specified register class.
void addScavengingFrameIndex (int FI)
Add a scavenging frame index.
bool isScavengingFrameIndex (int FI) const
Query whether a frame index is a scavenging frame index.
void getScavengingFrameIndices (SmallVectorImpl< int > &A) const
Get an array of scavenging frame indices.
Register scavengeRegister (const TargetRegisterClass *RC, MachineBasicBlock::iterator I, int SPAdj, bool AllowSpill=true)
Make a register of the specific register class available and do the appropriate bookkeeping.
Register scavengeRegister (const TargetRegisterClass *RegClass, int SPAdj, bool AllowSpill=true)
Register scavengeRegisterBackwards (const TargetRegisterClass &RC, MachineBasicBlock::iterator To, bool RestoreAfter, int SPAdj, bool AllowSpill=true)
Make a register of the specific register class available from the current position backwards to the place before To.
void setRegUsed (Register Reg, LaneBitmask LaneMask=LaneBitmask::getAll())
Tell the scavenger a register is used.
Detailed Description
Definition at line 34 of file RegisterScavenging.h.
Constructor & Destructor Documentation
RegScavenger()
llvm::RegScavenger::RegScavenger () default
Member Function Documentation
addScavengingFrameIndex()
void llvm::RegScavenger::addScavengingFrameIndex (int FI) inline
Add a scavenging frame index.
Definition at line 132 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized().
backward() [1/2]
void RegScavenger::backward ()
Update internal register state and move MBB iterator backwards.
Contrary to unprocess() this method gives precise results even in the absence of kill flags.
Definition at line 261 of file RegisterScavenging.cpp.
References assert(), llvm::MachineBasicBlock::begin(), I, MI, and llvm::LiveRegUnits::stepBackward().
Referenced by backward(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), scavengeFrameVirtualRegsInBlock(), and unprocess().
backward() [2/2]
void llvm::RegScavenger::backward (MachineBasicBlock::iterator I) inline
Call backward() as long as the internal iterator does not point to I.
Definition at line 107 of file RegisterScavenging.h.
References backward().
enterBasicBlock()
void RegScavenger::enterBasicBlock (MachineBasicBlock & MBB)
Start tracking liveness from the begin of basic block MBB.
Definition at line 84 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::addLiveIns(), and llvm::cl::init().
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::SIInstrInfo::copyPhysReg(), INITIALIZE_PASS(), llvm::Mips16InstrInfo::loadImmediate(), and llvm::PPCFrameLowering::replaceFPWithRealFP().
enterBasicBlockEnd()
void RegScavenger::enterBasicBlockEnd (MachineBasicBlock & MBB)
Start tracking liveness from the end of basic block MBB.
Use backward() to move towards the beginning of the block. This is preferred to enterBasicBlock() and forward() because it does not depend on the presence of kill flags.
Definition at line 89 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::addLiveOuts(), addRegUnits(), assert(), llvm::MachineBasicBlock::begin(), llvm::BitVector::clear(), llvm::MachineBasicBlock::end(), llvm::cl::init(), llvm::MachineInstr::isDebugInstr(), llvm::Register::isPhysicalRegister(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegUnitRootIterator::isValid(), MI, llvm::MachineInstr::operands(), Reg, llvm::BitVector::reset(), llvm::BitVector::set(), and TRI.
Referenced by llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), and scavengeFrameVirtualRegsInBlock().
FindUnusedReg()
Register RegScavenger::FindUnusedReg (const TargetRegisterClass * RC) const
Find an unused register of the specified register class.
Return 0 if none is found.
Definition at line 288 of file RegisterScavenging.cpp.
References llvm::dbgs(), isRegUsed(), LLVM_DEBUG, llvm::printReg(), Reg, and TRI.
Referenced by llvm::SIInstrInfo::copyPhysReg(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), getCurrentPosition(), INITIALIZE_PASS(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), and ReplaceFrameIndex().
forward() [1/2]
void RegScavenger::forward ()
Move the internal MBB iterator and update register states.
Definition at line 176 of file RegisterScavenging.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineBasicBlock::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), I, llvm::ARM_PROC::IE, llvm::Register::isPhysicalRegister(), isRegUsed(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm_unreachable, MI, MRI, SubReg, TRI, and llvm::MachineFunction::verify().
Referenced by llvm::SIInstrInfo::copyPhysReg(), forward(), INITIALIZE_PASS(), llvm::Mips16InstrInfo::loadImmediate(), and llvm::PPCFrameLowering::replaceFPWithRealFP().
forward() [2/2]
void llvm::RegScavenger::forward (MachineBasicBlock::iterator I) inline
Move the internal MBB iterator and update register states until it has processed the specific iterator.
Definition at line 87 of file RegisterScavenging.h.
References llvm::MachineBasicBlock::begin(), forward(), I, and unprocess().
getCurrentPosition()
MachineBasicBlock::iterator llvm::RegScavenger::getCurrentPosition () const inline
Definition at line 119 of file RegisterScavenging.h.
References FindUnusedReg(), getRegsAvailable(), isRegUsed(), and Reg.
getRegsAvailable()
BitVector RegScavenger::getRegsAvailable (const TargetRegisterClass * RC)
Return all available registers in the register class in Mask.
Definition at line 299 of file RegisterScavenging.cpp.
References assert(), llvm::BitVector::clearBitsNotInMask(), llvm::BitVector::find_first(), llvm::MachineBasicBlock::getFirstTerminator(), InstrLimit, isRegUsed(), llvm::MCRegAliasIterator::isValid(), llvm::Register::isVirtualRegister(), llvm::BitmaskEnumDetail::Mask(), MI, llvm::BitVector::none(), llvm::BitVector::reset(), llvm::BitVector::test(), TRI, and UseMI.
Referenced by getCurrentPosition(), llvm::Mips16InstrInfo::loadImmediate(), llvm::PPCFrameLowering::replaceFPWithRealFP(), and scavengeRegister().
getScavengingFrameIndices()
void llvm::RegScavenger::getScavengingFrameIndices (SmallVectorImpl< int > & A) const inline
Get an array of scavenging frame indices.
Definition at line 147 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::ARM_PROC::IE, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and scavengeRegister().
isRegUsed()
bool RegScavenger::isRegUsed (Register Reg, bool includeReserved = true) const
Return if a specific register is currently used.
Definition at line 282 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::available().
Referenced by FindUnusedReg(), forward(), llvm::SIInstrInfo::getAddNoCarry(), getCurrentPosition(), getRegsAvailable(), llvm::PPCFrameLowering::replaceFPWithRealFP(), and scavengeRegister().
isScavengingFrameIndex()
bool llvm::RegScavenger::isScavengingFrameIndex (int FI) const inline
Query whether a frame index is a scavenging frame index.
Definition at line 137 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, and llvm::ARM_PROC::IE.
Referenced by llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), and llvm::ARMBaseRegisterInfo::eliminateFrameIndex().
scavengeRegister() [1/2]
Register RegScavenger::scavengeRegister (const TargetRegisterClass * RC, MachineBasicBlock::iterator I, int SPAdj, bool AllowSpill = true)
Make a register of the specific register class available and do the appropriate bookkeeping.
SPAdj is the stack adjustment due to call frame, it's passed along to eliminateFrameIndex(). Returns the scavenged register. This is deprecated as it depends on the quality of the kill flags being present; Use scavengeRegisterBackwards() instead!
If AllowSpill is false, fail if a spill is required to make the register available, and return NoRegister.
Definition at line 535 of file RegisterScavenging.cpp.
References llvm::BitVector::any(), llvm::dbgs(), llvm::MachineInstr::getMF(), getRegsAvailable(), I, isRegUsed(), llvm::MCRegAliasIterator::isValid(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MI, llvm::MachineInstr::operands(), llvm::printReg(), llvm::BitVector::reset(), TRI, and UseMI.
Referenced by buildMUBUFOffsetLoadStore(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::SIInstrInfo::copyPhysReg(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SIInstrInfo::getAddNoCarry(), getScavengingFrameIndices(), InsertFPConstInst(), InsertSPConstInst(), ReplaceFrameIndex(), llvm::SIRegisterInfo::restoreSGPR(), scavengeRegister(), and llvm::SIRegisterInfo::spillSGPR().
scavengeRegister() [2/2]
Register llvm::RegScavenger::scavengeRegister (const TargetRegisterClass * RegClass, int SPAdj, bool AllowSpill = true) inline
Definition at line 166 of file RegisterScavenging.h.
References llvm::LiveRegUnits::addUnits(), llvm::LaneBitmask::getAll(), InstrLimit, llvm::MachineRegisterInfo::isReserved(), llvm::LiveRegUnits::removeUnits(), llvm::scavengeFrameVirtualRegs(), scavengeRegister(), scavengeRegisterBackwards(), setRegUsed(), and UseMI.
scavengeRegisterBackwards()
Register RegScavenger::scavengeRegisterBackwards (const TargetRegisterClass & RC, MachineBasicBlock::iterator To, bool RestoreAfter, int SPAdj, bool AllowSpill = true)
Make a register of the specific register class available from the current position backwards to the place before To.
If RestoreAfter is true this includes the instruction following the current position. SPAdj is the stack adjustment due to call frame, it's passed along to eliminateFrameIndex(). Returns the scavenged register.
If AllowSpill is false, fail if a spill is required to make the register available, and return NoRegister.
Definition at line 580 of file RegisterScavenging.cpp.
References assert(), llvm::dbgs(), llvm::MachineBasicBlock::end(), findSurvivorBackwards(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterClass::getRawAllocationOrder(), LLVM_DEBUG, MRI, P, llvm::printReg(), Reg, llvm::LiveRegUnits::removeReg(), TRI, and UseMI.
Referenced by llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), scavengeRegister(), and scavengeVReg().
setRegUsed()
void RegScavenger::setRegUsed (Register Reg, LaneBitmask LaneMask = LaneBitmask::getAll())
Tell the scavenger a register is used.
Definition at line 53 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::addRegMasked(), assert(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::LiveRegUnits::init(), MRI, llvm::BitVector::resize(), SI, TII, and TRI.
Referenced by llvm::SIInstrInfo::copyPhysReg(), InsertFPConstInst(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), InsertSPConstInst(), ReplaceFrameIndex(), scavengeFrameVirtualRegsInBlock(), and scavengeRegister().
skipTo()
void llvm::RegScavenger::skipTo (MachineBasicBlock::iterator I) inline
Move the internal MBB iterator but do not update register states.
Definition at line 113 of file RegisterScavenging.h.
References I.
unprocess() [1/2]
void RegScavenger::unprocess ()
Invert the behavior of forward() on the current instruction (undo the changes to the available registers made by forward()).
Definition at line 157 of file RegisterScavenging.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineInstr::isDebugInstr(), and MI.
Referenced by forward(), and unprocess().
unprocess() [2/2]
void llvm::RegScavenger::unprocess (MachineBasicBlock::iterator I) inline
Unprocess instructions until you reach the provided iterator.
Definition at line 97 of file RegisterScavenging.h.
References backward(), and unprocess().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterScavenging.h
lib/CodeGen/RegisterScavenging.cpp