LLVM: llvm::object::WindowsResource Class Reference
llvm::object::WindowsResource Class Reference
#include "llvm/Object/WindowsResource.h"
Public Member Functions
Expected< ResourceEntryRef > getHeadEntry ()
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *V)
static Expected< std::unique_ptr< WindowsResource > > createWindowsResource (MemoryBufferRef Source)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Friends
class ResourceEntryRef
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_COFFImportFile, ID_IR,
ID_TapiUniversal, ID_TapiFile, ID_Minidump, ID_WinRes,
ID_StartObjects, ID_COFF, ID_XCOFF32, ID_XCOFF64,
ID_ELF32L, ID_ELF32B, ID_ELF64L, ID_ELF64B,
ID_MachO32L, ID_MachO32B, ID_MachO64L, ID_MachO64B,
ID_Wasm, ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 136 of file WindowsResource.h.
Member Function Documentation
classof()
static bool llvm::object::WindowsResource::classof (const Binary * V) inline static
Definition at line 140 of file WindowsResource.h.
References llvm::object::Binary::isWinRes(), and llvm::Sched::Source.
createWindowsResource()
Expected< std::unique_ptr< WindowsResource > > llvm::object::WindowsResource::createWindowsResource (MemoryBufferRef Source) static
Definition at line 60 of file WindowsResource.cpp.
References llvm::MemoryBufferRef::getBufferIdentifier(), llvm::MemoryBufferRef::getBufferSize(), llvm::object::invalid_file_type, llvm::MipsISD::Ret, llvm::object::WIN_RES_MAGIC_SIZE, and llvm::object::WIN_RES_NULL_ENTRY_SIZE.
Referenced by llvm::object::createBinary().
getHeadEntry()
Expected< ResourceEntryRef > llvm::object::WindowsResource::getHeadEntry ()
Definition at line 69 of file WindowsResource.cpp.
References llvm::X86ISD::BSR, E, llvm::object::Binary::getFileName(), llvm::BinaryByteStream::getLength(), llvm::Ref, ResourceEntryRef, and llvm::object::unexpected_eof.
Referenced by llvm::object::WindowsResourceParser::parse().
Friends And Related Function Documentation
ResourceEntryRef
friend class ResourceEntryRef friend
Definition at line 146 of file WindowsResource.h.
Referenced by getHeadEntry().
The documentation for this class was generated from the following files:
include/llvm/Object/WindowsResource.h
lib/Object/WindowsResource.cpp