LLVM: llvm::SDUse Class Reference
llvm::SDUse Class Reference
Represents a use of a SDNode.
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Member Functions
SDUse ()=default
SDUse (const SDUse &U)=delete
SDUse & operator= (const SDUse &)=delete
operator const SDValue & () const
Normally SDUse will just implicitly convert to an SDValue that it holds.
const SDValue & get () const
If implicit conversion to SDValue doesn't work, the get() method returns the SDValue.
SDNode * getUser ()
This returns the SDNode that contains this Use.
SDUse * getNext () const
Get the next SDUse in the use list.
SDNode * getNode () const
Convenience function for get().getNode().
unsigned getResNo () const
Convenience function for get().getResNo().
EVT getValueType () const
Convenience function for get().getValueType().
bool operator== (const SDValue &V) const
Convenience function for get().operator==.
bool operator!= (const SDValue &V) const
Convenience function for get().operator!=.
bool operator< (const SDValue &V) const
Convenience function for get().operator<.
Friends
class SelectionDAG
class SDNode
class HandleSDNode
Detailed Description
Represents a use of a SDNode.
This class holds an SDValue, which records the SDNode being used and the result number, a pointer to the SDNode using the value, and Next and Prev pointers, which link together all the uses of an SDNode.
Definition at line 263 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
SDUse() [1/2]
llvm::SDUse::SDUse () default
SDUse() [2/2]
llvm::SDUse::SDUse (const SDUse & U) delete
Member Function Documentation
get()
const SDValue& llvm::SDUse::get () const inline
If implicit conversion to SDValue doesn't work, the get() method returns the SDValue.
Definition at line 283 of file SelectionDAGNodes.h.
Referenced by LowerBUILD_VECTOR_i1().
getNext()
SDUse* llvm::SDUse::getNext () const inline
Get the next SDUse in the use list.
Definition at line 289 of file SelectionDAGNodes.h.
Referenced by llvm::SDNode::use_iterator::operator++().
getNode()
SDNode* llvm::SDUse::getNode () const inline
Convenience function for get().getNode().
Definition at line 292 of file SelectionDAGNodes.h.
References llvm::SDValue::getNode().
Referenced by llvm::simplify_type< SDUse >::getSimplifiedValue(), llvm::SelectionDAG::MorphNodeTo(), and llvm::SelectionDAG::RemoveDeadNodes().
getResNo()
unsigned llvm::SDUse::getResNo () const inline
Convenience function for get().getResNo().
Definition at line 294 of file SelectionDAGNodes.h.
References llvm::SDValue::getResNo().
Referenced by ExtendUsesToFormExtLoad(), findGlueUse(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and llvm::SelectionDAG::ReplaceAllUsesWith().
getUser()
SDNode* llvm::SDUse::getUser () inline
This returns the SDNode that contains this Use.
Definition at line 286 of file SelectionDAGNodes.h.
Referenced by ExtendUsesToFormExtLoad(), findGlueUse(), getCombineLoadStoreParts(), llvm::SDNode::use_iterator::getOperandNo(), and llvm::SDNode::use_iterator::operator*().
getValueType()
EVT llvm::SDUse::getValueType () const inline
Convenience function for get().getValueType().
Definition at line 296 of file SelectionDAGNodes.h.
References llvm::SDValue::getValueType().
operator const SDValue &()
llvm::SDUse::operator const SDValue & () const inline
Normally SDUse will just implicitly convert to an SDValue that it holds.
Definition at line 279 of file SelectionDAGNodes.h.
operator!=()
bool llvm::SDUse::operator!= (const SDValue & V) const inline
Convenience function for get().operator!=.
Definition at line 304 of file SelectionDAGNodes.h.
operator<()
bool llvm::SDUse::operator< (const SDValue & V) const inline
Convenience function for get().operator<.
Definition at line 309 of file SelectionDAGNodes.h.
operator=()
SDUse& llvm::SDUse::operator= (const SDUse &) delete
operator==()
bool llvm::SDUse::operator== (const SDValue & V) const inline
Convenience function for get().operator==.
Definition at line 299 of file SelectionDAGNodes.h.
Friends And Related Function Documentation
HandleSDNode
friend class HandleSDNode friend
Definition at line 317 of file SelectionDAGNodes.h.
SDNode
friend class SDNode friend
Definition at line 315 of file SelectionDAGNodes.h.
SelectionDAG
friend class SelectionDAG friend
Definition at line 314 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SelectionDAGNodes.h