LLVM: llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > Class Template Reference
llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > Class Template Reference
The core module pass which does a post-order walk of the SCCs and runs a CGSCC pass over each one.
#include "llvm/Analysis/CGSCCPassManager.h"
Public Member Functions
ModuleToPostOrderCGSCCPassAdaptor (CGSCCPassT Pass)
ModuleToPostOrderCGSCCPassAdaptor (const ModuleToPostOrderCGSCCPassAdaptor &Arg)
ModuleToPostOrderCGSCCPassAdaptor (ModuleToPostOrderCGSCCPassAdaptor &&Arg)
ModuleToPostOrderCGSCCPassAdaptor & operator= (ModuleToPostOrderCGSCCPassAdaptor RHS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Runs the CGSCC pass across every SCC in the module.
Friends
void swap (ModuleToPostOrderCGSCCPassAdaptor &LHS, ModuleToPostOrderCGSCCPassAdaptor &RHS)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
template<typename CGSCCPassT>
class llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >
The core module pass which does a post-order walk of the SCCs and runs a CGSCC pass over each one.
Designed to allow composition of a CGSCCPass(Manager) and a ModulePassManager. Note that this pass must be run with a module analysis manager as it uses the LazyCallGraph analysis. It will also run the CGSCCAnalysisManagerModuleProxy analysis prior to running the CGSCC pass over the module to enable a FunctionAnalysisManager to be used within this run safely.
Definition at line 330 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
ModuleToPostOrderCGSCCPassAdaptor() [1/3]
template<typename CGSCCPassT > llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::ModuleToPostOrderCGSCCPassAdaptor (CGSCCPassT Pass) inline explicit
Definition at line 333 of file CGSCCPassManager.h.
ModuleToPostOrderCGSCCPassAdaptor() [2/3]
template<typename CGSCCPassT > llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::ModuleToPostOrderCGSCCPassAdaptor (const ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > & Arg) inline
Definition at line 338 of file CGSCCPassManager.h.
ModuleToPostOrderCGSCCPassAdaptor() [3/3]
template<typename CGSCCPassT > llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::ModuleToPostOrderCGSCCPassAdaptor (ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > && Arg) inline
Definition at line 342 of file CGSCCPassManager.h.
Member Function Documentation
operator=()
template<typename CGSCCPassT > ModuleToPostOrderCGSCCPassAdaptor& llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::operator= (ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > RHS) inline
Definition at line 351 of file CGSCCPassManager.h.
References Pass, llvm::RequireAnalysisPass< AnalysisT, IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), and std::swap().
run()
template<typename CGSCCPassT > PreservedAnalyses llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::run (Module & M, ModuleAnalysisManager & AM)
Runs the CGSCC pass across every SCC in the module.
Definition at line 735 of file CGSCCPassManager.h.
References llvm::PreservedAnalyses::all(), assert(), llvm::LazyCallGraph::SCC::begin(), llvm::LazyCallGraph::buildRefSCCs(), C, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::CGSCCUpdateResult::CrossSCCPA, llvm::dbgs(), llvm::PriorityWorklist< T, SmallVector< T, N >, SmallDenseMap< T, ptrdiff_t > >::empty(), llvm::LazyCallGraph::SCC::end(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs >::Result::getManager(), llvm::LazyCallGraph::SCC::getOuterRefSCC(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PriorityWorklist< T, SmallVector< T, N >, SmallDenseMap< T, ptrdiff_t > >::insert(), llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::CGSCCUpdateResult::InvalidatedSCCs, LLVM_DEBUG, Pass, llvm::PriorityWorklist< T, SmallVector< T, N >, SmallDenseMap< T, ptrdiff_t > >::pop_back_val(), llvm::LazyCallGraph::postorder_ref_scc_begin(), llvm::LazyCallGraph::postorder_ref_scc_end(), llvm::reverse(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runAfterPassInvalidated(), llvm::PassInstrumentation::runBeforePass(), llvm::CGSCCUpdateResult::UpdatedC, and llvm::CGSCCUpdateResult::UpdatedRC.
Friends And Related Function Documentation
swap
template<typename CGSCCPassT > void swap (ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > & LHS, ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT > & RHS) friend
Definition at line 345 of file CGSCCPassManager.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/CGSCCPassManager.h