LLVM: llvm::InjectTLIMappings Class Reference
llvm::InjectTLIMappings Class Reference
#include "llvm/Transforms/Utils/InjectTLIMappings.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InjectTLIMappings >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 20 of file InjectTLIMappings.h.
Member Function Documentation
run()
PreservedAnalyses InjectTLIMappings::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 150 of file InjectTLIMappings.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and runImpl().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/InjectTLIMappings.h
lib/Transforms/Utils/InjectTLIMappings.cpp