LLVM: llvm::InterferenceCache Class Reference
llvm::InterferenceCache Class Reference
#include "CodeGen/InterferenceCache.h"
Classes
class Cursor
Cursor - The primary query interface for the block interference cache.
Public Member Functions
InterferenceCache ()=default
~InterferenceCache ()
void reinitPhysRegEntries ()
void init (MachineFunction *mf, LiveIntervalUnion *liuarray, SlotIndexes *indexes, LiveIntervals *lis, const TargetRegisterInfo *tri)
init - Prepare cache for a new function.
unsigned getMaxCursors () const
getMaxCursors - Return the maximum number of concurrent cursors that can be supported.
Friends
class Cursor
Detailed Description
Definition at line 32 of file InterferenceCache.h.
Constructor & Destructor Documentation
InterferenceCache()
llvm::InterferenceCache::InterferenceCache () default
~InterferenceCache()
llvm::InterferenceCache::~InterferenceCache () inline
Definition at line 164 of file InterferenceCache.h.
References llvm::cl::init().
Member Function Documentation
getMaxCursors()
unsigned llvm::InterferenceCache::getMaxCursors () const inline
getMaxCursors - Return the maximum number of concurrent cursors that can be supported.
Definition at line 177 of file InterferenceCache.h.
init()
void InterferenceCache::init (MachineFunction * mf, LiveIntervalUnion * liuarray, SlotIndexes * indexes, LiveIntervals * lis, const TargetRegisterInfo * tri)
init - Prepare cache for a new function.
Definition at line 54 of file InterferenceCache.cpp.
References clear(), and reinitPhysRegEntries().
reinitPhysRegEntries()
void InterferenceCache::reinitPhysRegEntries ()
Definition at line 46 of file InterferenceCache.cpp.
References llvm::MCRegisterInfo::getNumRegs(), and llvm::safe_calloc().
Referenced by init().
Friends And Related Function Documentation
Cursor
friend class Cursor friend
Definition at line 160 of file InterferenceCache.h.
The documentation for this class was generated from the following files:
lib/CodeGen/InterferenceCache.h
lib/CodeGen/InterferenceCache.cpp