LLVM: llvm::AttributeList Class Reference
llvm::AttributeList Class Reference
#include "llvm/IR/Attributes.h"
Public Types
enum AttrIndex : unsigned { ReturnIndex = 0U, FunctionIndex = ~0U, FirstArgIndex = 1 }
using iterator = const AttributeSet *
Public Member Functions
AttributeList ()=default
LLVM_NODISCARD AttributeList addAttribute (LLVMContext &C, unsigned Index, Attribute::AttrKind Kind) const
Add an attribute to the attribute set at the given index.
LLVM_NODISCARD AttributeList addAttribute (LLVMContext &C, unsigned Index, StringRef Kind, StringRef Value=StringRef()) const
Add an attribute to the attribute set at the given index.
LLVM_NODISCARD AttributeList addAttribute (LLVMContext &C, unsigned Index, Attribute A) const
Add an attribute to the attribute set at the given index.
LLVM_NODISCARD AttributeList addAttributes (LLVMContext &C, unsigned Index, const AttrBuilder &B) const
Add attributes to the attribute set at the given index.
LLVM_NODISCARD AttributeList addParamAttribute (LLVMContext &C, unsigned ArgNo, Attribute::AttrKind Kind) const
Add an argument attribute to the list.
LLVM_NODISCARD AttributeList addParamAttribute (LLVMContext &C, unsigned ArgNo, StringRef Kind, StringRef Value=StringRef()) const
Add an argument attribute to the list.
LLVM_NODISCARD AttributeList addParamAttribute (LLVMContext &C, ArrayRef< unsigned > ArgNos, Attribute A) const
Add an attribute to the attribute list at the given arg indices.
LLVM_NODISCARD AttributeList addParamAttributes (LLVMContext &C, unsigned ArgNo, const AttrBuilder &B) const
Add an argument attribute to the list.
LLVM_NODISCARD AttributeList removeAttribute (LLVMContext &C, unsigned Index, Attribute::AttrKind Kind) const
Remove the specified attribute at the specified index from this attribute list.
LLVM_NODISCARD AttributeList removeAttribute (LLVMContext &C, unsigned Index, StringRef Kind) const
Remove the specified attribute at the specified index from this attribute list.
LLVM_NODISCARD AttributeList removeAttributes (LLVMContext &C, unsigned Index, const AttrBuilder &AttrsToRemove) const
Remove the specified attributes at the specified index from this attribute list.
LLVM_NODISCARD AttributeList removeAttributes (LLVMContext &C, unsigned Index) const
Remove all attributes at the specified index from this attribute list.
LLVM_NODISCARD AttributeList removeParamAttribute (LLVMContext &C, unsigned ArgNo, Attribute::AttrKind Kind) const
Remove the specified attribute at the specified arg index from this attribute list.
LLVM_NODISCARD AttributeList removeParamAttribute (LLVMContext &C, unsigned ArgNo, StringRef Kind) const
Remove the specified attribute at the specified arg index from this attribute list.
LLVM_NODISCARD AttributeList removeParamAttributes (LLVMContext &C, unsigned ArgNo, const AttrBuilder &AttrsToRemove) const
Remove the specified attribute at the specified arg index from this attribute list.
LLVM_NODISCARD AttributeList removeParamAttributes (LLVMContext &C, unsigned ArgNo) const
Remove all attributes at the specified arg index from this attribute list.
LLVM_NODISCARD AttributeList addDereferenceableAttr (LLVMContext &C, unsigned Index, uint64_t Bytes) const
Add the dereferenceable attribute to the attribute set at the given index.
LLVM_NODISCARD AttributeList addDereferenceableParamAttr (LLVMContext &C, unsigned ArgNo, uint64_t Bytes) const
Add the dereferenceable attribute to the attribute set at the given arg index.
LLVM_NODISCARD AttributeList addDereferenceableOrNullAttr (LLVMContext &C, unsigned Index, uint64_t Bytes) const
Add the dereferenceable_or_null attribute to the attribute set at the given index.
LLVM_NODISCARD AttributeList addDereferenceableOrNullParamAttr (LLVMContext &C, unsigned ArgNo, uint64_t Bytes) const
Add the dereferenceable_or_null attribute to the attribute set at the given arg index.
LLVM_NODISCARD AttributeList addAllocSizeAttr (LLVMContext &C, unsigned Index, unsigned ElemSizeArg, const Optional< unsigned > &NumElemsArg)
Add the allocsize attribute to the attribute set at the given index.
LLVM_NODISCARD AttributeList addAllocSizeParamAttr (LLVMContext &C, unsigned ArgNo, unsigned ElemSizeArg, const Optional< unsigned > &NumElemsArg)
Add the allocsize attribute to the attribute set at the given arg index.
LLVMContext & getContext () const
Retrieve the LLVM context.
AttributeSet getAttributes (unsigned Index) const
The attributes for the specified index are returned.
AttributeSet getParamAttributes (unsigned ArgNo) const
The attributes for the argument or parameter at the given index are returned.
AttributeSet getRetAttributes () const
The attributes for the ret value are returned.
AttributeSet getFnAttributes () const
The function attributes are returned.
bool hasAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return true if the attribute exists at the given index.
bool hasAttribute (unsigned Index, StringRef Kind) const
Return true if the attribute exists at the given index.
bool hasAttributes (unsigned Index) const
Return true if attribute exists at the given index.
bool hasParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Return true if the attribute exists for the given argument.
bool hasParamAttr (unsigned ArgNo, StringRef Kind) const
Return true if the attribute exists for the given argument.
bool hasParamAttrs (unsigned ArgNo) const
Return true if attributes exists for the given argument.
bool hasFnAttribute (Attribute::AttrKind Kind) const
Equivalent to hasAttribute(AttributeList::FunctionIndex, Kind) but may be faster.
bool hasFnAttribute (StringRef Kind) const
Equivalent to hasAttribute(AttributeList::FunctionIndex, Kind) but may be faster.
bool hasParamAttribute (unsigned ArgNo, Attribute::AttrKind Kind) const
Equivalent to hasAttribute(ArgNo + FirstArgIndex, Kind).
bool hasAttrSomewhere (Attribute::AttrKind Kind, unsigned *Index=nullptr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
Attribute getAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return the attribute object that exists at the given index.
Attribute getAttribute (unsigned Index, StringRef Kind) const
Return the attribute object that exists at the given index.
Attribute getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Return the attribute object that exists at the arg index.
Attribute getParamAttr (unsigned ArgNo, StringRef Kind) const
Return the attribute object that exists at the given index.
MaybeAlign getRetAlignment () const
Return the alignment of the return value.
MaybeAlign getParamAlignment (unsigned ArgNo) const
Return the alignment for the specified function parameter.
Type * getParamByValType (unsigned ArgNo) const
Return the byval type for the specified function parameter.
MaybeAlign getStackAlignment (unsigned Index) const
Get the stack alignment.
uint64_t getDereferenceableBytes (unsigned Index) const
Get the number of dereferenceable bytes (or zero if unknown).
uint64_t getParamDereferenceableBytes (unsigned ArgNo) const
Get the number of dereferenceable bytes (or zero if unknown) of an arg.
uint64_t getDereferenceableOrNullBytes (unsigned Index) const
Get the number of dereferenceable_or_null bytes (or zero if unknown).
uint64_t getParamDereferenceableOrNullBytes (unsigned ArgNo) const
Get the number of dereferenceable_or_null bytes (or zero if unknown) of an arg.
std::pair< unsigned, Optional< unsigned > > getAllocSizeArgs (unsigned Index) const
Get the allocsize argument numbers (or pair(0, 0) if unknown).
std::string getAsString (unsigned Index, bool InAttrGrp=false) const
Return the attributes at the index as a string.
iterator begin () const
iterator end () const
unsigned getNumAttrSets () const
unsigned index_begin () const
Use these to iterate over the valid attribute indices.
unsigned index_end () const
bool operator== (const AttributeList &RHS) const
operator==/!= - Provide equality predicates.
bool operator!= (const AttributeList &RHS) const
void * getRawPointer () const
Return a raw pointer that uniquely identifies this attribute list.
bool isEmpty () const
Return true if there are no attributes.
void dump () const
Static Public Member Functions
static AttributeList get (LLVMContext &C, ArrayRef< std::pair< unsigned, Attribute >> Attrs)
Create an AttributeList with the specified parameters in it.
static AttributeList get (LLVMContext &C, ArrayRef< std::pair< unsigned, AttributeSet >> Attrs)
static AttributeList get (LLVMContext &C, AttributeSet FnAttrs, AttributeSet RetAttrs, ArrayRef< AttributeSet > ArgAttrs)
Create an AttributeList from attribute sets for a function, its return value, and all of its arguments.
static AttributeList get (LLVMContext &C, ArrayRef< AttributeList > Attrs)
Return an AttributeList with the specified parameters in it.
static AttributeList get (LLVMContext &C, unsigned Index, ArrayRef< Attribute::AttrKind > Kinds)
static AttributeList get (LLVMContext &C, unsigned Index, ArrayRef< StringRef > Kind)
static AttributeList get (LLVMContext &C, unsigned Index, const AttrBuilder &B)
Friends
class AttrBuilder
class AttributeListImpl
class AttributeSet
class AttributeSetNode
template<typename Ty >
struct DenseMapInfo
Detailed Description
Definition at line 337 of file Attributes.h.
Member Typedef Documentation
iterator
using llvm::AttributeList::iterator = const AttributeSet *
Definition at line 648 of file Attributes.h.
Member Enumeration Documentation
AttrIndex
enum llvm::AttributeList::AttrIndex : unsigned
Enumerator
ReturnIndex
FunctionIndex
FirstArgIndex
Definition at line 339 of file Attributes.h.
Constructor & Destructor Documentation
AttributeList()
llvm::AttributeList::AttributeList () default
Member Function Documentation
addAllocSizeAttr()
AttributeList AttributeList::addAllocSizeAttr (LLVMContext & C, unsigned Index, unsigned ElemSizeArg, const Optional< unsigned > & NumElemsArg)
Add the allocsize attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1275 of file Attributes.cpp.
References llvm::AttrBuilder::addAllocSizeAttr(), and B.
addAllocSizeParamAttr()
LLVM_NODISCARD AttributeList llvm::AttributeList::addAllocSizeParamAttr (LLVMContext & C, unsigned ArgNo, unsigned ElemSizeArg, const Optional< unsigned > & NumElemsArg) inline
Add the allocsize attribute to the attribute set at the given arg index.
Returns a new list because attribute lists are immutable.
Definition at line 524 of file Attributes.h.
References llvm::Intrinsic::getAttributes(), and llvm::Attribute::hasAttribute().
addAttribute() [1/3]
AttributeList AttributeList::addAttribute (LLVMContext & C, unsigned Index, Attribute::AttrKind Kind) const
Add an attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1132 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), and B.
Referenced by llvm::Function::addAttribute(), llvm::CallBase::addAttribute(), addIfNotExistent(), fixupFPReturnAndCall(), forceRenaming(), llvm::AMDGPULibFunc::getOrInsertFunction(), GetRMWLibcall(), INITIALIZE_PASS(), and wrapConstantAsMetadata().
addAttribute() [2/3]
AttributeList AttributeList::addAttribute (LLVMContext & C, unsigned Index, StringRef Kind, StringRef Value = StringRef()) const
Add an attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1140 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), and B.
addAttribute() [3/3]
AttributeList AttributeList::addAttribute (LLVMContext & C, unsigned Index, Attribute A) const
Add an attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1148 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), and B.
addAttributes()
AttributeList AttributeList::addAttributes (LLVMContext & C, unsigned Index, const AttrBuilder & B) const
Add attributes to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1155 of file Attributes.cpp.
References assert(), attrIdxToArrayIdx(), llvm::AttributeListImpl::begin(), llvm::AttributeListImpl::end(), llvm::AttributeSet::get(), get(), llvm::AttrBuilder::getAlignment(), llvm::Intrinsic::getAttributes(), getImpl(), llvm::AttrBuilder::hasAttributes(), llvm::AttrBuilder::merge(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
Referenced by llvm::Function::addAttributes().
addDereferenceableAttr()
AttributeList AttributeList::addDereferenceableAttr (LLVMContext & C, unsigned Index, uint64_t Bytes) const
Add the dereferenceable attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1258 of file Attributes.cpp.
References llvm::AttrBuilder::addDereferenceableAttr(), and B.
Referenced by llvm::Function::addDereferenceableAttr(), and llvm::CallBase::addDereferenceableAttr().
addDereferenceableOrNullAttr()
AttributeList AttributeList::addDereferenceableOrNullAttr (LLVMContext & C, unsigned Index, uint64_t Bytes) const
Add the dereferenceable_or_null attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1267 of file Attributes.cpp.
References llvm::AttrBuilder::addDereferenceableOrNullAttr(), and B.
Referenced by llvm::Function::addDereferenceableOrNullAttr(), and llvm::CallBase::addDereferenceableOrNullAttr().
addDereferenceableOrNullParamAttr()
LLVM_NODISCARD AttributeList llvm::AttributeList::addDereferenceableOrNullParamAttr (LLVMContext & C, unsigned ArgNo, uint64_t Bytes) const inline
Add the dereferenceable_or_null attribute to the attribute set at the given arg index.
Returns a new list because attribute lists are immutable.
Definition at line 510 of file Attributes.h.
References LLVM_NODISCARD.
Referenced by llvm::Function::addDereferenceableOrNullParamAttr().
addDereferenceableParamAttr()
LLVM_NODISCARD AttributeList llvm::AttributeList::addDereferenceableParamAttr (LLVMContext & C, unsigned ArgNo, uint64_t Bytes) const inline
Add the dereferenceable attribute to the attribute set at the given arg index.
Returns a new list because attribute lists are immutable.
Definition at line 497 of file Attributes.h.
References LLVM_NODISCARD.
Referenced by llvm::Function::addDereferenceableParamAttr().
addParamAttribute() [1/3]
LLVM_NODISCARD AttributeList llvm::AttributeList::addParamAttribute (LLVMContext & C, unsigned ArgNo, Attribute::AttrKind Kind) const inline
Add an argument attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 413 of file Attributes.h.
References LLVM_NODISCARD.
Referenced by llvm::Function::addParamAttr(), llvm::CallBase::addParamAttr(), annotateAnyAllocSite(), INITIALIZE_PASS(), processCallSite(), llvm::ModuleSanitizerCoveragePass::run(), and shouldKeepInEntry().
addParamAttribute() [2/3]
LLVM_NODISCARD AttributeList llvm::AttributeList::addParamAttribute (LLVMContext & C, unsigned ArgNo, StringRef Kind, StringRef Value = StringRef()) const inline
Add an argument attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 421 of file Attributes.h.
References A, and LLVM_NODISCARD.
addParamAttribute() [3/3]
AttributeList AttributeList::addParamAttribute (LLVMContext & C, ArrayRef< unsigned > ArgNos, Attribute A) const
Add an attribute to the attribute list at the given arg indices.
Returns a new list because attribute lists are immutable.
Definition at line 1184 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), assert(), attrIdxToArrayIdx(), B, llvm::ArrayRef< T >::back(), llvm::ArrayRef< T >::begin(), llvm::AttributeListImpl::begin(), llvm::ArrayRef< T >::end(), llvm::AttributeListImpl::end(), llvm::AttributeSet::get(), getImpl(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
addParamAttributes()
LLVM_NODISCARD AttributeList llvm::AttributeList::addParamAttributes (LLVMContext & C, unsigned ArgNo, const AttrBuilder & B) const inline
Add an argument attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 434 of file Attributes.h.
References LLVM_NODISCARD.
Referenced by llvm::Argument::addAttrs(), llvm::Function::addParamAttrs(), and annotateNonNullAndDereferenceable().
begin()
AttributeList::iterator AttributeList::begin () const
Definition at line 1391 of file Attributes.cpp.
References llvm::AttributeSet::begin().
dump()
LLVM_DUMP_METHOD void AttributeList::dump () const
Definition at line 1408 of file Attributes.cpp.
References llvm::dbgs(), llvm::numbers::e, and llvm::Intrinsic::getAttributes().
end()
AttributeList::iterator AttributeList::end () const
Definition at line 1395 of file Attributes.cpp.
References llvm::AttributeSet::end().
get() [1/7]
AttributeList AttributeList::get (LLVMContext & C, ArrayRef< std::pair< unsigned, Attribute >> Attrs) static
Create an AttributeList with the specified parameters in it.
Definition at line 972 of file Attributes.cpp.
References assert(), llvm::ArrayRef< T >::begin(), C, E, llvm::SmallVectorImpl< T >::emplace_back(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), llvm::AttributeSet::get(), I, llvm::Attribute::None, llvm::none_of(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by addAttributes(), AddCalls(), annotateAnyAllocSite(), llvm::CloneFunctionInto(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createDeadArgHackingPass(), doPromotion(), llvm::emitMemCpyChk(), FunctionNumber(), llvm::GlobalVariable::getAttributesAsList(), GetGlobalTypeString(), getRetComponentType(), getReturnAttrs(), getSignature(), llvm::InlineFunction(), legalizeCallAttributes(), makeStatepointExplicitImpl(), llvm::promoteCall(), and llvm::Attributor::registerFunctionSignatureRewrite().
get() [2/7]
AttributeList AttributeList::get (LLVMContext & C, ArrayRef< std::pair< unsigned, AttributeSet >> Attrs) static
Definition at line 1008 of file Attributes.cpp.
References assert(), attrIdxToArrayIdx(), llvm::ArrayRef< T >::back(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), getImpl(), llvm::none_of(), and llvm::ArrayRef< T >::size().
get() [3/7]
AttributeList AttributeList::get (LLVMContext & C, AttributeSet FnAttrs, AttributeSet RetAttrs, ArrayRef< AttributeSet > ArgAttrs) static
Create an AttributeList from attribute sets for a function, its return value, and all of its arguments.
Definition at line 1039 of file Attributes.cpp.
References llvm::ArrayRef< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ArrayRef< T >::end(), getImpl(), llvm::AttributeSet::hasAttributes(), I, llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::take_front().
get() [4/7]
AttributeList AttributeList::get (LLVMContext & C, ArrayRef< AttributeList > Attrs) static
Return an AttributeList with the specified parameters in it.
Definition at line 1106 of file Attributes.cpp.
References llvm::ArrayRef< T >::empty(), llvm::AttributeSet::get(), getImpl(), I, List, llvm::max(), llvm::AttrBuilder::merge(), and llvm::ArrayRef< T >::size().
get() [5/7]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, ArrayRef< Attribute::AttrKind > Kinds) static
Definition at line 1090 of file Attributes.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, C, llvm::SmallVectorImpl< T >::emplace_back(), and llvm::Attribute::get().
get() [6/7]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, ArrayRef< StringRef > Kind) static
Definition at line 1098 of file Attributes.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, C, llvm::SmallVectorImpl< T >::emplace_back(), and llvm::Attribute::get().
get() [7/7]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, const AttrBuilder & B) static
Definition at line 1080 of file Attributes.cpp.
References attrIdxToArrayIdx(), llvm::AttributeSet::get(), getImpl(), and llvm::AttrBuilder::hasAttributes().
getAllocSizeArgs()
std::pair< unsigned, Optional< unsigned > > AttributeList::getAllocSizeArgs (unsigned Index) const
Get the allocsize argument numbers (or pair(0, 0) if unknown).
Definition at line 1376 of file Attributes.cpp.
References getAllocSizeArgs(), and llvm::Intrinsic::getAttributes().
Referenced by getAllocSizeArgs(), and isFuncOrArgAttr().
getAsString()
std::string AttributeList::getAsString (unsigned Index, bool InAttrGrp = false) const
Return the attributes at the index as a string.
Definition at line 1380 of file Attributes.cpp.
References getAsString(), and llvm::Intrinsic::getAttributes().
Referenced by getAsString(), maybePrintCallAddrSpace(), and maybePrintComdat().
getAttribute() [1/2]
Attribute AttributeList::getAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return the attribute object that exists at the given index.
Definition at line 1342 of file Attributes.cpp.
References getAttribute(), and llvm::Intrinsic::getAttributes().
Referenced by addIfNotExistent(), FixedPointIntrinsicToOpcode(), forceRenaming(), llvm::IRPosition::getAttr(), llvm::Function::getAttribute(), getAttribute(), llvm::CallBase::getAttribute(), getDeoptLowering(), llvm::HexagonTargetMachine::getSubtargetImpl(), isFuncOrArgAttr(), llvm::parseStatepointDirectivesFromAttrs(), llvm::CallLowering::setArgFlags(), and wrapConstantAsMetadata().
getAttribute() [2/2]
Attribute AttributeList::getAttribute (unsigned Index, StringRef Kind) const
Return the attribute object that exists at the given index.
Definition at line 1347 of file Attributes.cpp.
References getAttribute(), and llvm::Intrinsic::getAttributes().
getAttributes()
AttributeSet AttributeList::getAttributes (unsigned Index) const
The attributes for the specified index are returned.
Definition at line 1384 of file Attributes.cpp.
References attrIdxToArrayIdx().
Referenced by llvm::AttrBuilder::AttrBuilder(), llvm::FunctionComparator::cmpMem(), doPromotion(), llvm::IRPosition::getAttr(), getAttrKindEncoding(), getMetadataTypeOrder(), getParameterABIAttributes(), getRetComponentType(), getSignature(), getSuccPad(), llvm::AttrBuilder::hasAttributes(), haveSameSpecialState(), LLVMGetAttributeCountAtIndex(), LLVMGetAttributesAtIndex(), llvm::NVPTXTargetLowering::LowerFormalArguments(), maybePrintCallAddrSpace(), llvm::AttrBuilder::removeAttributes(), and llvm::IRPosition::removeAttrs().
getContext()
LLVMContext & AttributeList::getContext () const
Retrieve the LLVM context.
Definition at line 1287 of file Attributes.cpp.
Referenced by legalizeCallAttributes().
getDereferenceableBytes()
uint64_t AttributeList::getDereferenceableBytes (unsigned Index) const
Get the number of dereferenceable bytes (or zero if unknown).
Definition at line 1367 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes(), and getDereferenceableBytes().
Referenced by llvm::Function::getDereferenceableBytes(), getDereferenceableBytes(), and llvm::CallBase::getDereferenceableBytes().
getDereferenceableOrNullBytes()
uint64_t AttributeList::getDereferenceableOrNullBytes (unsigned Index) const
Get the number of dereferenceable_or_null bytes (or zero if unknown).
Definition at line 1371 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes(), and getDereferenceableOrNullBytes().
Referenced by llvm::Function::getDereferenceableOrNullBytes(), getDereferenceableOrNullBytes(), and llvm::CallBase::getDereferenceableOrNullBytes().
getFnAttributes()
AttributeSet AttributeList::getFnAttributes () const
The function attributes are returned.
Definition at line 1297 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes().
Referenced by AddCalls(), annotateAnyAllocSite(), llvm::createDeadArgHackingPass(), doPromotion(), llvm::CodeExtractor::findInputsOutputs(), GetGlobalTypeString(), getRetComponentType(), getSignature(), llvm::InlineFunction(), isFuncOrArgAttr(), legalizeCallAttributes(), maybePrintCallAddrSpace(), maybePrintComdat(), llvm::promoteCall(), and llvm::Attributor::registerFunctionSignatureRewrite().
getNumAttrSets()
unsigned AttributeList::getNumAttrSets () const
Definition at line 1403 of file Attributes.cpp.
Referenced by AddCalls(), llvm::FunctionComparator::cmpMem(), forceRenaming(), GetGlobalTypeString(), isFuncOrArgAttr(), and wrapConstantAsMetadata().
getParamAlignment()
MaybeAlign AttributeList::getParamAlignment (unsigned ArgNo) const
Return the alignment for the specified function parameter.
Definition at line 1355 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes().
Referenced by getOpenCLAlignment(), llvm::Function::getParamAlign(), llvm::CallBase::getParamAlign(), llvm::CallBase::getParamAlignment(), and getParameterABIAttributes().
getParamAttr() [1/2]
Attribute llvm::AttributeList::getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const inline
Return the attribute object that exists at the arg index.
Definition at line 597 of file Attributes.h.
References getAttribute().
Referenced by llvm::CallBase::getParamAttr(), and llvm::Function::getParamAttribute().
getParamAttr() [2/2]
Attribute llvm::AttributeList::getParamAttr (unsigned ArgNo, StringRef Kind) const inline
Return the attribute object that exists at the given index.
Definition at line 602 of file Attributes.h.
References getAttribute(), llvm::Attribute::getDereferenceableBytes(), and llvm::Attribute::getStackAlignment().
getParamAttributes()
AttributeSet AttributeList::getParamAttributes (unsigned ArgNo) const
The attributes for the argument or parameter at the given index are returned.
Definition at line 1289 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes().
Referenced by AddCalls(), annotateAnyAllocSite(), annotateNonNullAndDereferenceable(), llvm::createDeadArgHackingPass(), doPromotion(), GetGlobalTypeString(), getRetComponentType(), getSignature(), llvm::InlineFunction(), isFuncOrArgAttr(), maybePrintCallAddrSpace(), maybePrintComdat(), llvm::promoteCall(), and llvm::Attributor::registerFunctionSignatureRewrite().
getParamByValType()
Type * AttributeList::getParamByValType (unsigned ArgNo) const
Return the byval type for the specified function parameter.
Definition at line 1359 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes().
Referenced by llvm::Function::getParamByValType(), and llvm::CallBase::getParamByValType().
getParamDereferenceableBytes()
uint64_t llvm::AttributeList::getParamDereferenceableBytes (unsigned ArgNo) const inline
Get the number of dereferenceable bytes (or zero if unknown) of an arg.
Definition at line 623 of file Attributes.h.
References llvm::Attribute::getDereferenceableBytes(), and llvm::Attribute::getDereferenceableOrNullBytes().
Referenced by llvm::Function::getParamDereferenceableBytes().
getParamDereferenceableOrNullBytes()
uint64_t llvm::AttributeList::getParamDereferenceableOrNullBytes (unsigned ArgNo) const inline
Get the number of dereferenceable_or_null bytes (or zero if unknown) of an arg.
Definition at line 633 of file Attributes.h.
References llvm::Attribute::getAllocSizeArgs(), llvm::Attribute::getAsString(), and llvm::Attribute::getDereferenceableOrNullBytes().
Referenced by llvm::Function::getParamDereferenceableOrNullBytes().
getRawPointer()
void* llvm::AttributeList::getRawPointer () const inline
Return a raw pointer that uniquely identifies this attribute list.
Definition at line 664 of file Attributes.h.
getRetAlignment()
MaybeAlign AttributeList::getRetAlignment () const
Return the alignment of the return value.
Definition at line 1351 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes().
Referenced by llvm::CallBase::getRetAlign(), and llvm::CallBase::getRetAlignment().
getRetAttributes()
AttributeSet AttributeList::getRetAttributes () const
The attributes for the ret value are returned.
Definition at line 1293 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes().
Referenced by AddCalls(), annotateAnyAllocSite(), llvm::createDeadArgHackingPass(), doPromotion(), GetGlobalTypeString(), getRetComponentType(), getSignature(), llvm::InlineFunction(), isFuncOrArgAttr(), llvm::PPCInstrInfo::isSignOrZeroExtended(), makeStatepointExplicitImpl(), and llvm::Attributor::registerFunctionSignatureRewrite().
getStackAlignment()
MaybeAlign AttributeList::getStackAlignment (unsigned Index) const
Get the stack alignment.
Definition at line 1363 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes(), and getStackAlignment().
Referenced by llvm::Function::getFnStackAlignment(), and getStackAlignment().
hasAttribute() [1/2]
bool AttributeList::hasAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return true if the attribute exists at the given index.
Definition at line 1301 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes(), and hasAttribute().
Referenced by addIfNotExistent(), llvm::analyzeArguments(), llvm::CallBase::CountBundleInputs(), forceRenaming(), FunctionNumber(), llvm::IRPosition::getAttr(), getDeoptLowering(), llvm::GetReturnInfo(), llvm::Function::hasAttribute(), hasAttribute(), INITIALIZE_PASS(), IsCallReturnTwice(), llvm::AArch64TargetLowering::isIntDivCheap(), llvm::X86TargetLowering::isIntDivCheap(), isLibCallInTailPosition(), LowerADJUST_TRAMPOLINE(), llvm::AArch64CallLowering::lowerReturn(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::paramHasAttr(), llvm::Function::returnDoesNotAlias(), llvm::CallBase::returnDoesNotAlias(), llvm::CallLowering::setArgFlags(), and wrapConstantAsMetadata().
hasAttribute() [2/2]
bool AttributeList::hasAttribute (unsigned Index, StringRef Kind) const
Return true if the attribute exists at the given index.
Definition at line 1306 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes(), and hasAttribute().
hasAttributes()
bool AttributeList::hasAttributes (unsigned Index) const
Return true if attribute exists at the given index.
Definition at line 1310 of file Attributes.cpp.
References llvm::Intrinsic::getAttributes(), and hasAttributes().
Referenced by hasAttributes(), isFuncOrArgAttr(), maybePrintCallAddrSpace(), and maybePrintComdat().
hasAttrSomewhere()
bool AttributeList::hasAttrSomewhere (Attribute::AttrKind Kind, unsigned * Index = nullptr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
If Index is not nullptr, the index of a parameter with the specified attribute is provided.
Definition at line 1327 of file Attributes.cpp.
References E, and I.
Referenced by annotateAnyAllocSite(), llvm::XCoreFrameLowering::emitPrologue(), findUnwindDestinations(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::SystemZRegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::SystemZRegisterInfo::getCallPreservedMask(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), getRetComponentType(), llvm::CallBase::hasByValArgument(), OptimizeFunctions(), promoteArguments(), llvm::Attributor::registerFunctionSignatureRewrite(), and StripAttr().
hasFnAttribute() [1/2]
bool AttributeList::hasFnAttribute (Attribute::AttrKind Kind) const
Equivalent to hasAttribute(AttributeList::FunctionIndex, Kind) but may be faster.
Definition at line 1314 of file Attributes.cpp.
Referenced by llvm::AArch64TargetLowering::getOptimalMemOpLLT(), llvm::ARMTargetLowering::getOptimalMemOpType(), llvm::AArch64TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::SITargetLowering::getTgtMemIntrinsic(), llvm::Function::hasFnAttribute(), isFuncOrArgAttr(), and useFuncSeen().
hasFnAttribute() [2/2]
bool AttributeList::hasFnAttribute (StringRef Kind) const
Equivalent to hasAttribute(AttributeList::FunctionIndex, Kind) but may be faster.
Definition at line 1318 of file Attributes.cpp.
References FunctionIndex.
hasParamAttr() [1/2]
bool llvm::AttributeList::hasParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const inline
Return true if the attribute exists for the given argument.
Definition at line 559 of file Attributes.h.
References llvm::Attribute::hasAttribute().
hasParamAttr() [2/2]
bool llvm::AttributeList::hasParamAttr (unsigned ArgNo, StringRef Kind) const inline
Return true if the attribute exists for the given argument.
Definition at line 564 of file Attributes.h.
References llvm::Attribute::hasAttribute().
hasParamAttribute()
bool AttributeList::hasParamAttribute (unsigned ArgNo, Attribute::AttrKind Kind) const
Equivalent to hasAttribute(ArgNo + FirstArgIndex, Kind).
Definition at line 1322 of file Attributes.cpp.
Referenced by annotateAnyAllocSite(), getOpenCLAlignment(), getParameterABIAttributes(), getRetComponentType(), llvm::Argument::hasByValOrInAllocaAttr(), llvm::Function::hasParamAttribute(), llvm::Function::hasStructRetAttr(), isArgPassedInSGPR(), llvm::AMDGPU::isArgPassedInSGPR(), llvm::NVPTXTargetLowering::LowerFormalArguments(), and llvm::Argument::onlyReadsMemory().
hasParamAttrs()
bool llvm::AttributeList::hasParamAttrs (unsigned ArgNo) const inline
Return true if attributes exists for the given argument.
Definition at line 569 of file Attributes.h.
References getAttribute().
index_begin()
unsigned llvm::AttributeList::index_begin () const inline
Use these to iterate over the valid attribute indices.
Definition at line 656 of file Attributes.h.
References FunctionIndex.
Referenced by llvm::FunctionComparator::cmpMem(), getAttrKindEncoding(), and getMetadataTypeOrder().
index_end()
unsigned llvm::AttributeList::index_end () const inline
Definition at line 657 of file Attributes.h.
Referenced by llvm::FunctionComparator::cmpMem(), getAttrKindEncoding(), and getMetadataTypeOrder().
isEmpty()
bool llvm::AttributeList::isEmpty () const inline
Return true if there are no attributes.
Definition at line 669 of file Attributes.h.
References llvm::dump().
Referenced by annotateAnyAllocSite(), llvm::createDeadArgHackingPass(), llvm::ValueEnumerator::getAttributeListID(), getMetadataTypeOrder(), llvm::InlineFunction(), isFuncOrArgAttr(), legalizeCallAttributes(), and LowerADJUST_TRAMPOLINE().
operator!=()
bool llvm::AttributeList::operator!= (const AttributeList & RHS) const inline
Definition at line 661 of file Attributes.h.
operator==()
bool llvm::AttributeList::operator== (const AttributeList & RHS) const inline
operator==/!= - Provide equality predicates.
Definition at line 660 of file Attributes.h.
removeAttribute() [1/2]
AttributeList AttributeList::removeAttribute (LLVMContext & C, unsigned Index, Attribute::AttrKind Kind) const
Remove the specified attribute at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1204 of file Attributes.cpp.
References assert(), attrIdxToArrayIdx(), llvm::AttributeListImpl::begin(), llvm::AttributeListImpl::end(), getImpl(), and llvm::SmallVectorBase::size().
Referenced by addIfNotExistent(), emitBinaryFloatFnCallHelper(), emitUnaryFloatFnCallHelper(), forceRenaming(), llvm::Function::removeAttribute(), llvm::CallBase::removeAttribute(), llvm::IRPosition::removeAttrs(), StripAttr(), and wrapConstantAsMetadata().
removeAttribute() [2/2]
AttributeList AttributeList::removeAttribute (LLVMContext & C, unsigned Index, StringRef Kind) const
Remove the specified attribute at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1217 of file Attributes.cpp.
References assert(), attrIdxToArrayIdx(), llvm::AttributeListImpl::begin(), llvm::AttributeListImpl::end(), getImpl(), and llvm::SmallVectorBase::size().
removeAttributes() [1/2]
AttributeList AttributeList::removeAttributes (LLVMContext & C, unsigned Index, const AttrBuilder & AttrsToRemove) const
Remove the specified attributes at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1231 of file Attributes.cpp.
References attrIdxToArrayIdx(), llvm::AttributeListImpl::begin(), llvm::AttributeListImpl::end(), getImpl(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
Referenced by INITIALIZE_PASS(), and llvm::Function::removeAttributes().
removeAttributes() [2/2]
AttributeList AttributeList::removeAttributes (LLVMContext & C, unsigned Index) const
Remove all attributes at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1246 of file Attributes.cpp.
References attrIdxToArrayIdx(), llvm::AttributeListImpl::begin(), llvm::AttributeListImpl::end(), and getImpl().
removeParamAttribute() [1/2]
LLVM_NODISCARD AttributeList llvm::AttributeList::removeParamAttribute (LLVMContext & C, unsigned ArgNo, Attribute::AttrKind Kind) const inline
Remove the specified attribute at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 462 of file Attributes.h.
Referenced by llvm::Function::removeParamAttr(), and llvm::CallBase::removeParamAttr().
removeParamAttribute() [2/2]
LLVM_NODISCARD AttributeList llvm::AttributeList::removeParamAttribute (LLVMContext & C, unsigned ArgNo, StringRef Kind) const inline
Remove the specified attribute at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 469 of file Attributes.h.
removeParamAttributes() [1/2]
LLVM_NODISCARD AttributeList llvm::AttributeList::removeParamAttributes (LLVMContext & C, unsigned ArgNo, const AttrBuilder & AttrsToRemove) const inline
Remove the specified attribute at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 477 of file Attributes.h.
Referenced by llvm::Function::removeParamAttrs().
removeParamAttributes() [2/2]
LLVM_NODISCARD AttributeList llvm::AttributeList::removeParamAttributes (LLVMContext & C, unsigned ArgNo) const inline
Remove all attributes at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 484 of file Attributes.h.
References LLVM_NODISCARD.
Friends And Related Function Documentation
AttrBuilder
friend class AttrBuilder friend
Definition at line 346 of file Attributes.h.
AttributeListImpl
friend class AttributeListImpl friend
Definition at line 347 of file Attributes.h.
AttributeSet
friend class AttributeSet friend
Definition at line 348 of file Attributes.h.
AttributeSetNode
friend class AttributeSetNode friend
Definition at line 349 of file Attributes.h.
DenseMapInfo
template<typename Ty > friend struct DenseMapInfo friend
Definition at line 350 of file Attributes.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp