LLVM: llvm::codeview::ClassRecord Class Reference
llvm::codeview::ClassRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
ClassRecord ()=default
ClassRecord (TypeRecordKind Kind)
ClassRecord (TypeRecordKind Kind, uint16_t MemberCount, ClassOptions Options, TypeIndex FieldList, TypeIndex DerivationList, TypeIndex VTableShape, uint64_t Size, StringRef Name, StringRef UniqueName)
HfaKind getHfa () const
WindowsRTClassKind getWinRTKind () const
TypeIndex getDerivationList () const
TypeIndex getVTableShape () const
uint64_t getSize () const
Public Member Functions inherited from llvm::codeview::TagRecord
bool hasUniqueName () const
bool isNested () const
bool isForwardRef () const
bool containsNestedClass () const
bool isScoped () const
uint16_t getMemberCount () const
ClassOptions getOptions () const
TypeIndex getFieldList () const
StringRef getName () const
StringRef getUniqueName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex DerivationList
TypeIndex VTableShape
uint64_t Size = 0
Public Attributes inherited from llvm::codeview::TagRecord
uint16_t MemberCount = 0
ClassOptions Options
TypeIndex FieldList
StringRef Name
StringRef UniqueName
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Static Public Attributes inherited from llvm::codeview::TagRecord
static const int HfaKindShift = 11
static const int HfaKindMask = 0x1800
static const int WinRTKindShift = 14
static const int WinRTKindMask = 0xC000
Protected Member Functions inherited from llvm::codeview::TagRecord
TagRecord ()=default
TagRecord (TypeRecordKind Kind)
TagRecord (TypeRecordKind Kind, uint16_t MemberCount, ClassOptions Options, TypeIndex FieldList, StringRef Name, StringRef UniqueName)
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 470 of file TypeRecord.h.
Constructor & Destructor Documentation
ClassRecord() [1/3]
llvm::codeview::ClassRecord::ClassRecord () default
ClassRecord() [2/3]
llvm::codeview::ClassRecord::ClassRecord (TypeRecordKind Kind) inline explicit
Definition at line 473 of file TypeRecord.h.
ClassRecord() [3/3]
llvm::codeview::ClassRecord::ClassRecord (TypeRecordKind Kind, uint16_t MemberCount, ClassOptions Options, TypeIndex FieldList, TypeIndex DerivationList, TypeIndex VTableShape, uint64_t Size, StringRef Name, StringRef UniqueName) inline
Definition at line 474 of file TypeRecord.h.
Member Function Documentation
getDerivationList()
TypeIndex llvm::codeview::ClassRecord::getDerivationList () const inline
Definition at line 493 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getHfa()
HfaKind llvm::codeview::ClassRecord::getHfa () const inline
Definition at line 481 of file TypeRecord.h.
getSize()
uint64_t llvm::codeview::ClassRecord::getSize () const inline
Definition at line 495 of file TypeRecord.h.
References Size.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getVTableShape()
TypeIndex llvm::codeview::ClassRecord::getVTableShape () const inline
Definition at line 494 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getWinRTKind()
WindowsRTClassKind llvm::codeview::ClassRecord::getWinRTKind () const inline
Definition at line 487 of file TypeRecord.h.
Member Data Documentation
DerivationList
TypeIndex llvm::codeview::ClassRecord::DerivationList
Definition at line 497 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Size
uint64_t llvm::codeview::ClassRecord::Size = 0
Definition at line 499 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
VTableShape
TypeIndex llvm::codeview::ClassRecord::VTableShape
Definition at line 498 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h