LLVM: llvm::CodeRecTy Class Reference
llvm::CodeRecTy Class Reference
'code' - Represent a code fragment
#include "llvm/TableGen/Record.h"
Public Member Functions
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
Return true if all values of 'this' type can be converted to the specified type.
Public Member Functions inherited from llvm::RecTy
RecTy (RecTyKind K)
virtual ~RecTy ()=default
RecTyKind getRecTyKind () const
void print (raw_ostream &OS) const
void dump () const
virtual bool typeIsA (const RecTy *RHS) const
Return true if 'this' type is equal to or a subtype of RHS.
ListRecTy * getListTy ()
Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static CodeRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, CodeRecTyKind, IntRecTyKind,
StringRecTyKind, ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
'code' - Represent a code fragment
Definition at line 140 of file Record.h.
Member Function Documentation
classof()
static bool llvm::CodeRecTy::classof (const RecTy * RT) inline static
Definition at line 146 of file Record.h.
References llvm::RecTy::CodeRecTyKind, and llvm::RecTy::getRecTyKind().
get()
static CodeRecTy* llvm::CodeRecTy::get () inline static
Definition at line 150 of file Record.h.
getAsString()
std::string llvm::CodeRecTy::getAsString () const inline override virtual
Implements llvm::RecTy.
Definition at line 152 of file Record.h.
References llvm::RecTy::typeIsConvertibleTo().
typeIsConvertibleTo()
bool CodeRecTy::typeIsConvertibleTo (const RecTy * RHS) const override virtual
Return true if all values of 'this' type can be converted to the specified type.
Reimplemented from llvm::RecTy.
Definition at line 116 of file Record.cpp.
References llvm::RecTy::CodeRecTyKind, llvm::RecTy::getRecTyKind(), and llvm::RecTy::StringRecTyKind.
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp