LLVM: llvm::codeview::BaseClassRecord Class Reference
llvm::codeview::BaseClassRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
BaseClassRecord ()=default
BaseClassRecord (TypeRecordKind Kind)
BaseClassRecord (MemberAttributes Attrs, TypeIndex Type, uint64_t Offset)
BaseClassRecord (MemberAccess Access, TypeIndex Type, uint64_t Offset)
MemberAccess getAccess () const
TypeIndex getBaseType () const
uint64_t getBaseOffset () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
MemberAttributes Attrs
TypeIndex Type
uint64_t Offset = 0
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 869 of file TypeRecord.h.
Constructor & Destructor Documentation
BaseClassRecord() [1/4]
llvm::codeview::BaseClassRecord::BaseClassRecord () default
BaseClassRecord() [2/4]
llvm::codeview::BaseClassRecord::BaseClassRecord (TypeRecordKind Kind) inline explicit
Definition at line 872 of file TypeRecord.h.
BaseClassRecord() [3/4]
llvm::codeview::BaseClassRecord::BaseClassRecord (MemberAttributes Attrs, TypeIndex Type, uint64_t Offset) inline
Definition at line 873 of file TypeRecord.h.
BaseClassRecord() [4/4]
llvm::codeview::BaseClassRecord::BaseClassRecord (MemberAccess Access, TypeIndex Type, uint64_t Offset) inline
Definition at line 876 of file TypeRecord.h.
Member Function Documentation
getAccess()
MemberAccess llvm::codeview::BaseClassRecord::getAccess () const inline
Definition at line 880 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
getBaseOffset()
uint64_t llvm::codeview::BaseClassRecord::getBaseOffset () const inline
Definition at line 882 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getBaseType()
TypeIndex llvm::codeview::BaseClassRecord::getBaseType () const inline
Definition at line 881 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
Member Data Documentation
Attrs
MemberAttributes llvm::codeview::BaseClassRecord::Attrs
Definition at line 884 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Offset
uint64_t llvm::codeview::BaseClassRecord::Offset = 0
Definition at line 886 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Type
TypeIndex llvm::codeview::BaseClassRecord::Type
Definition at line 885 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h