LLVM: llvm::codeview::StringsAndChecksumsRef Class Reference
llvm::codeview::StringsAndChecksumsRef Class Reference
#include "llvm/DebugInfo/CodeView/StringsAndChecksums.h"
Public Member Functions
StringsAndChecksumsRef ()
StringsAndChecksumsRef (const DebugStringTableSubsectionRef &Strings)
StringsAndChecksumsRef (const DebugStringTableSubsectionRef &Strings, const DebugChecksumsSubsectionRef &Checksums)
void setStrings (const DebugStringTableSubsectionRef &Strings)
void setChecksums (const DebugChecksumsSubsectionRef &CS)
void reset ()
void resetStrings ()
void resetChecksums ()
template<typename T >
void initialize (T &&FragmentRange)
const DebugStringTableSubsectionRef & strings () const
const DebugChecksumsSubsectionRef & checksums () const
bool hasStrings () const
bool hasChecksums () const
Detailed Description
Definition at line 21 of file StringsAndChecksums.h.
Constructor & Destructor Documentation
StringsAndChecksumsRef() [1/3]
StringsAndChecksumsRef::StringsAndChecksumsRef () default
StringsAndChecksumsRef() [2/3]
StringsAndChecksumsRef::StringsAndChecksumsRef (const DebugStringTableSubsectionRef & Strings) explicit
Definition at line 23 of file StringsAndChecksums.cpp.
StringsAndChecksumsRef() [3/3]
StringsAndChecksumsRef::StringsAndChecksumsRef (const DebugStringTableSubsectionRef & Strings, const DebugChecksumsSubsectionRef & Checksums)
Definition at line 27 of file StringsAndChecksums.cpp.
References assert(), llvm::consumeError(), llvm::codeview::DebugSubsectionRecord::getRecordData(), llvm::codeview::DebugSubsectionRecord::kind(), and llvm::codeview::StringTable.
Member Function Documentation
checksums()
const DebugChecksumsSubsectionRef& llvm::codeview::StringsAndChecksumsRef::checksums () const inline
Definition at line 65 of file StringsAndChecksums.h.
Referenced by llvm::CodeViewYAML::toCodeViewSubsectionList().
hasChecksums()
bool llvm::codeview::StringsAndChecksumsRef::hasChecksums () const inline
Definition at line 68 of file StringsAndChecksums.h.
hasStrings()
bool llvm::codeview::StringsAndChecksumsRef::hasStrings () const inline
Definition at line 67 of file StringsAndChecksums.h.
initialize()
template<typename T > void llvm::codeview::StringsAndChecksumsRef::initialize (T && FragmentRange) inline
Definition at line 40 of file StringsAndChecksums.h.
References llvm::codeview::FileChecksums, and llvm::codeview::StringTable.
Referenced by llvm::codeview::detail::visitDebugSubsections().
reset()
void StringsAndChecksumsRef::reset ()
Definition at line 42 of file StringsAndChecksums.cpp.
References resetChecksums(), and resetStrings().
resetChecksums()
void StringsAndChecksumsRef::resetChecksums ()
Definition at line 52 of file StringsAndChecksums.cpp.
Referenced by reset().
resetStrings()
void StringsAndChecksumsRef::resetStrings ()
Definition at line 47 of file StringsAndChecksums.cpp.
Referenced by reset().
setChecksums()
void StringsAndChecksumsRef::setChecksums (const DebugChecksumsSubsectionRef & CS)
Definition at line 64 of file StringsAndChecksums.cpp.
References assert(), llvm::consumeError(), llvm::codeview::FileChecksums, llvm::codeview::DebugSubsectionRecord::getRecordData(), and llvm::codeview::DebugSubsectionRecord::kind().
setStrings()
void StringsAndChecksumsRef::setStrings (const DebugStringTableSubsectionRef & Strings)
Definition at line 57 of file StringsAndChecksums.cpp.
strings()
const DebugStringTableSubsectionRef& llvm::codeview::StringsAndChecksumsRef::strings () const inline
Definition at line 64 of file StringsAndChecksums.h.
Referenced by llvm::CodeViewYAML::toCodeViewSubsectionList().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/StringsAndChecksums.h
lib/DebugInfo/CodeView/StringsAndChecksums.cpp