LLVM: llvm::TrackUnresolvedResolver Class Reference
llvm::TrackUnresolvedResolver Class Reference final
(Optionally) delegate resolving to a sub-resolver, and keep track whether there were unresolved references.
#include "llvm/TableGen/Record.h"
Public Member Functions
TrackUnresolvedResolver (Resolver *R=nullptr)
bool foundUnresolved () const
Init * resolve (Init *VarName) override
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Public Member Functions inherited from llvm::Resolver
Resolver (Record *CurRec)
virtual ~Resolver ()
Record * getCurrentRecord () const
virtual bool keepUnsetBits () const
bool isFinal () const
void setFinal (bool Final)
Detailed Description
(Optionally) delegate resolving to a sub-resolver, and keep track whether there were unresolved references.
Definition at line 1971 of file Record.h.
Constructor & Destructor Documentation
TrackUnresolvedResolver()
llvm::TrackUnresolvedResolver::TrackUnresolvedResolver (Resolver * R = nullptr) inline explicit
Definition at line 1976 of file Record.h.
Member Function Documentation
foundUnresolved()
bool llvm::TrackUnresolvedResolver::foundUnresolved () const inline
Definition at line 1979 of file Record.h.
References llvm::tgtok::VarName.
Referenced by llvm::VarDefInit::Fold(), and llvm::VarDefInit::resolveReferences().
resolve()
Init * TrackUnresolvedResolver::resolve (Init * VarName) override virtual
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Implements llvm::Resolver.
Definition at line 2448 of file Record.cpp.
References I, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp