LLVM: llvm::sampleprof::SampleProfileWriterExtBinary Class Reference
llvm::sampleprof::SampleProfileWriterExtBinary Class Reference
#include "llvm/ProfileData/SampleProfWriter.h"
Public Member Functions
SampleProfileWriterExtBinary (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeSample (const FunctionSamples &S) override
Write samples of a top-level function to a binary file.
virtual void setProfileSymbolList (ProfileSymbolList *PSL) override
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriterExtBinaryBase
virtual std::error_code write (const StringMap< FunctionSamples > &ProfileMap) override
Write all the sample profiles in the given map of samples.
void setToCompressAllSections ()
void setToCompressSection (SecType Type)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
SampleProfileWriterBinary (std::unique_ptr< raw_ostream > &OS)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
virtual ~SampleProfileWriter ()=default
raw_ostream & getOutputStream ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriterExtBinaryBase
uint64_t markSectionStart (SecType Type)
Return the current position and prepare to use it as the start position of a section.
std::error_code addNewSection (SecType Sec, uint64_t SectionStart)
Add a new section into section header table.
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
virtual std::error_code writeMagicIdent (SampleProfileFormat Format)
virtual std::error_code writeNameTable ()
std::error_code writeSummary ()
std::error_code writeNameIdx (StringRef FName)
std::error_code writeBody (const FunctionSamples &S)
void stablizeNameTable (std::set< StringRef > &V)
void addName (StringRef FName)
void addNames (const FunctionSamples &S)
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeFuncProfiles (const StringMap< FunctionSamples > &ProfileMap)
void computeSummary (const StringMap< FunctionSamples > &ProfileMap)
Compute summary for this profile.
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriterExtBinaryBase
SmallVector< SecHdrTableEntry, 8 > SectionHdrLayout
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriterBinary
MapVector< StringRef, uint32_t > NameTable
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
SampleProfileFormat Format = SPF_None
Profile format.
Detailed Description
Definition at line 193 of file SampleProfWriter.h.
Constructor & Destructor Documentation
SampleProfileWriterExtBinary()
llvm::sampleprof::SampleProfileWriterExtBinary::SampleProfileWriterExtBinary (std::unique_ptr< raw_ostream > & OS) inline
Definition at line 195 of file SampleProfWriter.h.
References llvm::sampleprof::SampleProfileWriter::writeSample().
Member Function Documentation
setProfileSymbolList()
virtual void llvm::sampleprof::SampleProfileWriterExtBinary::setProfileSymbolList (ProfileSymbolList * PSL) inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 201 of file SampleProfWriter.h.
References llvm::sampleprof::SecFuncOffsetTable, llvm::sampleprof::SecLBRProfile, llvm::sampleprof::SecNameTable, llvm::sampleprof::SecProfileSymbolList, and llvm::sampleprof::SecProfSummary.
writeSample()
std::error_code SampleProfileWriterExtBinary::writeSample (const FunctionSamples & S) override virtual
Write samples of a top-level function to a binary file.
Returns
true if the samples were written successfully, false otherwise.
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 147 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleProfileWriter::computeSummary(), llvm::encodeULEB128(), entry, llvm::sampleprof::FunctionSamples::getHeadSamples(), llvm::sampleprof::FunctionSamples::getName(), I, Name, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SecFuncOffsetTable, llvm::sampleprof::SecLBRProfile, llvm::sampleprof::SecNameTable, llvm::sampleprof::SecProfileSymbolList, llvm::sampleprof::SecProfSummary, llvm::success, and llvm::sampleprof::SampleProfileWriter::writeFuncProfiles().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp