LLVM: llvm::DWARFDebugLine::SectionParser Class Reference
llvm::DWARFDebugLine::SectionParser Class Reference
Helper to allow for parsing of an entire .debug_line section in sequence.
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
Public Types
using cu_range = DWARFUnitVector::iterator_range
using tu_range = DWARFUnitVector::iterator_range
using LineToUnitMap = std::map< uint64_t, DWARFUnit * >
Public Member Functions
SectionParser (DWARFDataExtractor &Data, const DWARFContext &C, cu_range CUs, tu_range TUs)
LineTable parseNext (function_ref< void(Error)> RecoverableErrorCallback, function_ref< void(Error)> UnrecoverableErrorCallback, raw_ostream *OS=nullptr)
Get the next line table from the section.
void skip (function_ref< void(Error)> ErrorCallback)
Skip the current line table and go to the following line table (if present) immediately.
bool done () const
Indicates if the parser has parsed as much as possible.
uint64_t getOffset () const
Get the offset the parser has reached.
Detailed Description
Helper to allow for parsing of an entire .debug_line section in sequence.
Definition at line 317 of file DWARFDebugLine.h.
Member Typedef Documentation
cu_range
using llvm::DWARFDebugLine::SectionParser::cu_range = DWARFUnitVector::iterator_range
Definition at line 319 of file DWARFDebugLine.h.
LineToUnitMap
using llvm::DWARFDebugLine::SectionParser::LineToUnitMap = std::map<uint64_t, DWARFUnit *>
Definition at line 321 of file DWARFDebugLine.h.
tu_range
using llvm::DWARFDebugLine::SectionParser::tu_range = DWARFUnitVector::iterator_range
Definition at line 320 of file DWARFDebugLine.h.
Constructor & Destructor Documentation
SectionParser()
DWARFDebugLine::SectionParser::SectionParser (DWARFDataExtractor & Data, const DWARFContext & C, cu_range CUs, tu_range TUs)
Definition at line 1124 of file DWARFDebugLine.cpp.
References buildLineToUnitMap(), and llvm::DataExtractor::isValidOffset().
Member Function Documentation
done()
bool llvm::DWARFDebugLine::SectionParser::done () const inline
Indicates if the parser has parsed as much as possible.
Note
Certain problems with the line table structure might mean that parsing stops before the end of the section is reached.
Definition at line 352 of file DWARFDebugLine.h.
Referenced by llvm::DWARFContext::dump().
getOffset()
uint64_t llvm::DWARFDebugLine::SectionParser::getOffset () const inline
Get the offset the parser has reached.
Definition at line 355 of file DWARFDebugLine.h.
References Context, llvm::AArch64CC::LT, and P.
Referenced by llvm::DWARFContext::dump().
parseNext()
DWARFDebugLine::LineTable DWARFDebugLine::SectionParser::parseNext (function_ref< void(Error)> RecoverableErrorCallback, function_ref< void(Error)> UnrecoverableErrorCallback, raw_ostream * OS = nullptr)
Get the next line table from the section.
Report any issues via the callbacks.
Parameters
RecoverableErrorCallback - any issues that don't prevent further parsing of the table will be reported through this callback.
UnrecoverableErrorCallback - any issues that prevent further parsing of the table will be reported through this callback.
OS - if not null, the parser will print information about the table as it parses it.
Definition at line 1138 of file DWARFDebugLine.cpp.
References assert(), llvm::DataExtractor::isValidOffset(), and llvm::AArch64CC::LT.
Referenced by llvm::DWARFContext::dump().
skip()
void DWARFDebugLine::SectionParser::skip (function_ref< void(Error)> ErrorCallback)
Skip the current line table and go to the following line table (if present) immediately.
Parameters
ErrorCallback - report any prologue parsing issues via this callback.
Definition at line 1153 of file DWARFDebugLine.cpp.
References assert(), llvm::DataExtractor::isValidOffset(), and llvm::AArch64CC::LT.
Referenced by llvm::DWARFContext::dump().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLine.h
lib/DebugInfo/DWARF/DWARFDebugLine.cpp