LLVM: llvm::R600FrameLowering Class Reference
llvm::R600FrameLowering Class Reference
#include "Target/AMDGPU/R600FrameLowering.h"
Public Member Functions
R600FrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None())
~R600FrameLowering () override
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
Public Member Functions inherited from llvm::AMDGPUFrameLowering
AMDGPUFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None())
~AMDGPUFrameLowering () override
unsigned getStackWidth (const MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None(), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool isFPCloseToIncomingSP () const
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 16 of file R600FrameLowering.h.
Constructor & Destructor Documentation
R600FrameLowering()
llvm::R600FrameLowering::R600FrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl = Align::None()) inline
Definition at line 18 of file R600FrameLowering.h.
References ~R600FrameLowering().
~R600FrameLowering()
R600FrameLowering::~R600FrameLowering () override default
Referenced by R600FrameLowering().
Member Function Documentation
emitEpilogue()
void llvm::R600FrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const inline override virtual
Implements llvm::TargetFrameLowering.
Definition at line 25 of file R600FrameLowering.h.
References getFrameIndexReference().
emitPrologue()
void llvm::R600FrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const inline override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 23 of file R600FrameLowering.h.
getFrameIndexReference()
int R600FrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
Returns
The number of registers allocated for FI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 21 of file R600FrameLowering.cpp.
References llvm::alignTo(), llvm::MachineFunction::getFrameInfo(), llvm::R600RegisterInfo::getFrameRegister(), llvm::MachineFrameInfo::getNumObjects(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectSize(), llvm::AMDGPUFrameLowering::getStackWidth(), and llvm::MachineFunction::getSubtarget().
Referenced by emitEpilogue(), and llvm::R600InstrInfo::getIndirectIndexEnd().
hasFP()
bool llvm::R600FrameLowering::hasFP (const MachineFunction & MF) const inline override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 30 of file R600FrameLowering.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/R600FrameLowering.h
lib/Target/AMDGPU/R600FrameLowering.cpp