LLVM: llvm::orc::CtorDtorRunner Class Reference
llvm::orc::CtorDtorRunner Class Reference
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
Public Member Functions
CtorDtorRunner (JITDylib &JD)
void add (iterator_range< CtorDtorIterator > CtorDtors)
Error run ()
Detailed Description
Definition at line 157 of file ExecutionUtils.h.
Constructor & Destructor Documentation
CtorDtorRunner()
llvm::orc::CtorDtorRunner::CtorDtorRunner (JITDylib & JD) inline
Definition at line 159 of file ExecutionUtils.h.
References add().
Member Function Documentation
add()
void llvm::orc::CtorDtorRunner::add (iterator_range< CtorDtorIterator > CtorDtors)
Definition at line 116 of file ExecutionUtils.cpp.
References assert(), llvm::iterator_range< IteratorT >::begin(), llvm::dbgs(), llvm::iterator_range< IteratorT >::empty(), llvm::GlobalValue::ExternalLinkage, and llvm::GlobalValue::HiddenVisibility.
Referenced by llvm::orc::LLJIT::recordCtorDtors().
run()
Error llvm::orc::CtorDtorRunner::run ()
Definition at line 144 of file ExecutionUtils.cpp.
References llvm::orc::SymbolLookupSet::add(), assert(), llvm::orc::SymbolLookupSet::containsDuplicates(), llvm::orc::makeJITDylibSearchOrder(), llvm::orc::MatchAllSymbols, Name, and llvm::Error::success().
Referenced by llvm::orc::LLJIT::runConstructors(), and llvm::orc::LLJIT::runDestructors().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutionUtils.h
lib/ExecutionEngine/Orc/ExecutionUtils.cpp