LLVM: llvm::BPFMCInstLower Class Reference
llvm::BPFMCInstLower Class Reference
#include "Target/BPF/BPFMCInstLower.h"
Public Member Functions
BPFMCInstLower (MCContext &ctx, AsmPrinter &printer)
void Lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand LowerSymbolOperand (const MachineOperand &MO, MCSymbol *Sym) const
MCSymbol * GetGlobalAddressSymbol (const MachineOperand &MO) const
MCSymbol * GetExternalSymbolSymbol (const MachineOperand &MO) const
Detailed Description
Definition at line 26 of file BPFMCInstLower.h.
Constructor & Destructor Documentation
BPFMCInstLower()
llvm::BPFMCInstLower::BPFMCInstLower (MCContext & ctx, AsmPrinter & printer) inline
Definition at line 32 of file BPFMCInstLower.h.
References LowerSymbolOperand(), and MI.
Member Function Documentation
GetExternalSymbolSymbol()
MCSymbol * BPFMCInstLower::GetExternalSymbolSymbol (const MachineOperand & MO) const
Definition at line 32 of file BPFMCInstLower.cpp.
References llvm::AsmPrinter::GetExternalSymbolSymbol(), and llvm::MachineOperand::getSymbolName().
Referenced by Lower().
GetGlobalAddressSymbol()
MCSymbol * BPFMCInstLower::GetGlobalAddressSymbol (const MachineOperand & MO) const
Definition at line 27 of file BPFMCInstLower.cpp.
References llvm::MachineOperand::getGlobal(), and llvm::AsmPrinter::getSymbol().
Referenced by Lower().
Lower()
void BPFMCInstLower::Lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 47 of file BPFMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::numbers::e, llvm::errs(), GetExternalSymbolSymbol(), GetGlobalAddressSymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), llvm_unreachable, LowerSymbolOperand(), llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, llvm::MachineInstr::print(), and llvm::MCInst::setOpcode().
LowerSymbolOperand()
MCOperand BPFMCInstLower::LowerSymbolOperand (const MachineOperand & MO, MCSymbol * Sym) const
Definition at line 36 of file BPFMCInstLower.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::isJTI(), and llvm_unreachable.
Referenced by Lower().
The documentation for this class was generated from the following files:
lib/Target/BPF/BPFMCInstLower.h
lib/Target/BPF/BPFMCInstLower.cpp