LLVM: llvm::R600TargetMachine Class Reference
llvm::R600TargetMachine Class Reference final
#include "Target/AMDGPU/AMDGPUTargetMachine.h"
Public Member Functions
R600TargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
const R600Subtarget * getSubtargetImpl (const Function &) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
TargetTransformInfo getTargetTransformInfo (const Function &F) override
Get a TargetTransformInfo implementation for the target.
bool isMachineVerifierClean () const override
Returns true if the target is expected to pass all machine verifier checks.
Public Member Functions inherited from llvm::AMDGPUTargetMachine
AMDGPUTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL)
~AMDGPUTargetMachine () override
const TargetSubtargetInfo * getSubtargetImpl () const
TargetLoweringObjectFile * getObjFileLowering () const override
void adjustPassManager (PassManagerBuilder &) override
Allow the target to modify the pass manager, e.g.
uint64_t getNullPointerValue (unsigned AddrSpace) const
Get the integer value of a null pointer in the given address space.
Public Member Functions inherited from llvm::LLVMTargetMachine
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context)
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
virtual bool usesPhysRegsForPEI () const
True if the target uses physical regs at Prolog/Epilog insertion time.
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const Module &M, const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOpt::Level getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOpt::Level Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
bool shouldPrintMachineCode () const
bool getUniqueSectionNames () const
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
TargetIRAnalysis getTargetIRAnalysis ()
Get a TargetIRAnalysis appropriate for the target.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
Additional Inherited Members
Public Attributes inherited from llvm::TargetMachine
const TargetOptions DefaultOptions
TargetOptions Options
Static Public Attributes inherited from llvm::AMDGPUTargetMachine
static bool EnableLateStructurizeCFG = false
static bool EnableFunctionCalls = false
Protected Member Functions inherited from llvm::AMDGPUTargetMachine
StringRef getGPUName (const Function &F) const
StringRef getFeatureString (const Function &F) const
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::AMDGPUTargetMachine
std::unique_ptr< TargetLoweringObjectFile > TLOF
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
CodeGenOpt::Level OptLevel = CodeGenOpt::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
Detailed Description
Definition at line 69 of file AMDGPUTargetMachine.h.
Constructor & Destructor Documentation
R600TargetMachine()
R600TargetMachine::R600TargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
Definition at line 459 of file AMDGPUTargetMachine.cpp.
References EnableAMDGPUFunctionCallsOpt, llvm::AMDGPUTargetMachine::EnableFunctionCalls, and llvm::TargetMachine::setRequiresStructuredCFG().
Member Function Documentation
createPassConfig()
TargetPassConfig * R600TargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 808 of file AMDGPUTargetMachine.cpp.
References llvm::TargetPassConfig::addFastRegAlloc(), llvm::TargetPassConfig::addILPOpts(), llvm::TargetPassConfig::addMachineSSAOptimization(), llvm::TargetPassConfig::addOptimizedRegAlloc(), llvm::TargetPassConfig::addPostRegAlloc(), llvm::AMDGPUUnifyDivergentExitNodesID, llvm::BranchRelaxationPassID, C, llvm::createAMDGPUAnnotateUniformValues(), llvm::createAMDGPUAtomicOptimizerPass(), llvm::createAMDGPUMachineCFGStructurizerPass(), createGCNMaxOccupancyMachineScheduler(), llvm::createLCSSAPass(), llvm::createSIAddIMGInitPass(), llvm::createSIAnnotateControlFlowPass(), llvm::createSIFixupVectorISelPass(), llvm::createSIInsertWaitcntsPass(), llvm::createSILowerI1CopiesPass(), createSIMachineScheduler(), llvm::createSIMemoryLegalizerPass(), llvm::createSIModeRegisterPass(), llvm::createSinkingPass(), llvm::createSIShrinkInstructionsPass(), llvm::createSIWholeQuadModePass(), llvm::createStructurizeCFGPass(), llvm::DeadMachineInstructionElimID, llvm::DetectDeadLanesID, llvm::EarlyIfConverterID, llvm::EarlyMachineLICMID, EnableAtomicOptimizations, EnableDCEInRA, EnableDPPCombine, EnableEarlyIfConversion, EnableRegReassign, EnableSDWAPeephole, llvm::GCNSubtarget::enableSIScheduler(), llvm::GCNDPPCombineID, llvm::GCNNSAReassignID, llvm::GCNRegBankReassignID, llvm::TargetMachine::getOptLevel(), llvm::MachineFunction::getSubtarget(), LateCFGStructurize, llvm::MachineCSEID, llvm::MachineSchedulerID, llvm::MachineSchedContext::MF, llvm::CodeGenOpt::None, OptExecMaskPreRA, llvm::PHIEliminationID, llvm::PostRAHazardRecognizerID, llvm::RegisterCoalescerID, llvm::SIFixSGPRCopiesID, llvm::SIFixVGPRCopiesID, llvm::SIFoldOperandsID, llvm::SIFormMemoryClausesID, llvm::SIInsertSkipsPassID, llvm::SILoadStoreOptimizerID, llvm::SILowerControlFlowID, llvm::SILowerSGPRSpillsID, llvm::SIOptimizeExecMaskingID, llvm::SIOptimizeExecMaskingPreRAID, llvm::SIPeepholeSDWAID, llvm::SIPreAllocateWWMRegsID, and llvm::ARM_MB::ST.
getSubtargetImpl()
const R600Subtarget * R600TargetMachine::getSubtargetImpl (const Function &) const override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Implements llvm::AMDGPUTargetMachine.
Definition at line 474 of file AMDGPUTargetMachine.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::X86AS::FS, llvm::AMDGPUTargetMachine::getFeatureString(), llvm::AMDGPUTargetMachine::getGPUName(), I, llvm::TargetMachine::resetTargetOptions(), and llvm::TargetMachine::TargetTriple.
getTargetTransformInfo()
TargetTransformInfo R600TargetMachine::getTargetTransformInfo (const Function & F) override virtual
Get a TargetTransformInfo implementation for the target.
The TTI returned uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 495 of file AMDGPUTargetMachine.cpp.
isMachineVerifierClean()
bool llvm::R600TargetMachine::isMachineVerifierClean () const inline override virtual
Returns true if the target is expected to pass all machine verifier checks.
This is a stopgap measure to fix targets one by one. We will remove this at some point and always enable the verifier when EXPENSIVE_CHECKS is enabled.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 85 of file AMDGPUTargetMachine.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUTargetMachine.h
lib/Target/AMDGPU/AMDGPUTargetMachine.cpp