LLVM: llvm::MDNodeOpsKey Class Reference
llvm::MDNodeOpsKey Class Reference
Structure for hashing arbitrary MDNode operands.
#include "IR/LLVMContextImpl.h"
Public Member Functions
unsigned getHash () const
Protected Member Functions
MDNodeOpsKey (ArrayRef< Metadata *> Ops)
template<class NodeTy >
MDNodeOpsKey (const NodeTy *N, unsigned Offset=0)
template<class NodeTy >
bool compareOps (const NodeTy *RHS, unsigned Offset=0) const
Static Protected Member Functions
static unsigned calculateHash (MDNode *N, unsigned Offset=0)
Detailed Description
Structure for hashing arbitrary MDNode operands.
Definition at line 206 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeOpsKey() [1/2]
llvm::MDNodeOpsKey::MDNodeOpsKey (ArrayRef< Metadata *> Ops) inline protected
Definition at line 212 of file LLVMContextImpl.h.
MDNodeOpsKey() [2/2]
template<class NodeTy > llvm::MDNodeOpsKey::MDNodeOpsKey (const NodeTy * N, unsigned Offset = 0) inline protected
Definition at line 216 of file LLVMContextImpl.h.
Member Function Documentation
calculateHash()
unsigned MDNodeOpsKey::calculateHash (MDNode * N, unsigned Offset = 0) static protected
Definition at line 182 of file LLVMContextImpl.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::hash_combine_range(), llvm::MDNode::op_begin(), and llvm::MDNode::op_end().
Referenced by llvm::MDNodeKeyImpl< MDTuple >::calculateHash(), and llvm::MDNodeKeyImpl< GenericDINode >::calculateHash().
compareOps()
template<class NodeTy > bool llvm::MDNodeOpsKey::compareOps (const NodeTy * RHS, unsigned Offset = 0) const inline protected
Definition at line 220 of file LLVMContextImpl.h.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), llvm::lltok::equal, llvm::MDNode::getNumOperands(), N, llvm::MDNode::op_begin(), and llvm::ArrayRef< T >::size().
getHash()
unsigned llvm::MDNodeOpsKey::getHash () const inline
Definition at line 242 of file LLVMContextImpl.h.
The documentation for this class was generated from the following files:
lib/IR/LLVMContextImpl.h
lib/IR/LLVMContextImpl.cpp