LLVM: llvm::pdb::GlobalsStream Class Reference
llvm::pdb::GlobalsStream Class Reference
#include "llvm/DebugInfo/PDB/Native/GlobalsStream.h"
Public Member Functions
GlobalsStream (std::unique_ptr< msf::MappedBlockStream > Stream)
~GlobalsStream ()
const GSIHashTable & getGlobalsTable () const
Error reload ()
std::vector< std::pair< uint32_t, codeview::CVSymbol > > findRecordsByName (StringRef Name, const SymbolStream &Symbols) const
Detailed Description
Definition at line 70 of file GlobalsStream.h.
Constructor & Destructor Documentation
GlobalsStream()
GlobalsStream::GlobalsStream (std::unique_ptr< msf::MappedBlockStream > Stream) explicit
Definition at line 35 of file GlobalsStream.cpp.
References ~GlobalsStream().
~GlobalsStream()
GlobalsStream::~GlobalsStream () default
Referenced by GlobalsStream().
Member Function Documentation
findRecordsByName()
std::vector< std::pair< uint32_t, codeview::CVSymbol > > GlobalsStream::findRecordsByName (StringRef Name, const SymbolStream & Symbols) const
Definition at line 48 of file GlobalsStream.cpp.
References assert(), llvm::pdb::GSIHashTable::BucketMap, llvm::codeview::getSymbolName(), llvm::pdb::GSIHashTable::HashBuckets, llvm::pdb::GSIHashTable::HashRecords, llvm::pdb::hashStringV1(), llvm::pdb::IPHR_HASH, LLVM_LIKELY, llvm::pdb::PSHashRecord::Off, llvm::pdb::SymbolStream::readRecord(), and llvm::FixedStreamArray< T >::size().
getGlobalsTable()
const GSIHashTable& llvm::pdb::GlobalsStream::getGlobalsTable () const inline
Definition at line 74 of file GlobalsStream.h.
References Name, and llvm::pdb::Symbols.
Referenced by llvm::pdb::NativeEnumGlobals::NativeEnumGlobals().
reload()
Error GlobalsStream::reload ()
Definition at line 40 of file GlobalsStream.cpp.
References E, llvm::pdb::GSIHashTable::read(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/GlobalsStream.h
lib/DebugInfo/PDB/Native/GlobalsStream.cpp