LLVM: llvm::PseudoSourceValue Class Reference
llvm::PseudoSourceValue Class Reference
Special value supplied for machine level alias analysis.
#include "llvm/CodeGen/PseudoSourceValue.h"
Public Types
enum PSVKind : unsigned {
Stack, GOT, JumpTable, ConstantPool,
FixedStack, GlobalValueCallEntry, ExternalSymbolCallEntry, TargetCustom
}
Public Member Functions
PseudoSourceValue (unsigned Kind, const TargetInstrInfo &TII)
virtual ~PseudoSourceValue ()
unsigned kind () const
bool isStack () const
bool isGOT () const
bool isConstantPool () const
bool isJumpTable () const
unsigned getAddressSpace () const
unsigned getTargetCustom () const
virtual bool isConstant (const MachineFrameInfo *) const
Test whether the memory pointed to by this PseudoSourceValue has a constant value.
virtual bool isAliased (const MachineFrameInfo *) const
Test whether the memory pointed to by this PseudoSourceValue may also be pointed to by an LLVM IR Value.
virtual bool mayAlias (const MachineFrameInfo *) const
Return true if the memory pointed to by this PseudoSourceValue can ever alias an LLVM IR Value.
Friends
class MachineMemOperand
class MIRFormatter
raw_ostream & llvm::operator<< (raw_ostream &OS, const PseudoSourceValue *PSV)
Detailed Description
Special value supplied for machine level alias analysis.
It indicates that a memory access references the functions stack frame (e.g., a spill slot), below the stack frame (e.g., argument space), or constant pool.
Definition at line 36 of file PseudoSourceValue.h.
Member Enumeration Documentation
PSVKind
enum llvm::PseudoSourceValue::PSVKind : unsigned
Enumerator
Stack
GOT
JumpTable
ConstantPool
FixedStack
GlobalValueCallEntry
ExternalSymbolCallEntry
TargetCustom
Definition at line 38 of file PseudoSourceValue.h.
Constructor & Destructor Documentation
PseudoSourceValue()
PseudoSourceValue::PseudoSourceValue (unsigned Kind, const TargetInstrInfo & TII) explicit
Definition at line 27 of file PseudoSourceValue.cpp.
References llvm::TargetInstrInfo::getAddressSpaceForPseudoSourceKind().
~PseudoSourceValue()
PseudoSourceValue::~PseudoSourceValue () virtual
Definition at line 33 of file PseudoSourceValue.cpp.
References llvm::RISCVFenceField::O, and TargetCustom.
Member Function Documentation
getAddressSpace()
unsigned llvm::PseudoSourceValue::getAddressSpace () const inline
Definition at line 74 of file PseudoSourceValue.h.
Referenced by llvm::MachinePointerInfo::MachinePointerInfo().
getTargetCustom()
unsigned llvm::PseudoSourceValue::getTargetCustom () const inline
Definition at line 76 of file PseudoSourceValue.h.
References isAliased(), isConstant(), mayAlias(), and TargetCustom.
isAliased()
bool PseudoSourceValue::isAliased (const MachineFrameInfo *) const virtual
Test whether the memory pointed to by this PseudoSourceValue may also be pointed to by an LLVM IR Value.
Reimplemented in llvm::CallEntryPseudoSourceValue, llvm::FixedStackPseudoSourceValue, llvm::AMDGPUGWSResourcePseudoSourceValue, and llvm::AMDGPUPseudoSourceValue.
Definition at line 50 of file PseudoSourceValue.cpp.
References isConstantPool(), isGOT(), isJumpTable(), isStack(), and llvm_unreachable.
Referenced by llvm::FixedStackPseudoSourceValue::classof(), and getTargetCustom().
isConstant()
bool PseudoSourceValue::isConstant (const MachineFrameInfo *) const virtual
Test whether the memory pointed to by this PseudoSourceValue has a constant value.
Reimplemented in llvm::CallEntryPseudoSourceValue, llvm::FixedStackPseudoSourceValue, and llvm::AMDGPUPseudoSourceValue.
Definition at line 42 of file PseudoSourceValue.cpp.
References isConstantPool(), isGOT(), isJumpTable(), isStack(), and llvm_unreachable.
Referenced by llvm::FixedStackPseudoSourceValue::classof(), and getTargetCustom().
isConstantPool()
bool llvm::PseudoSourceValue::isConstantPool () const inline
Definition at line 71 of file PseudoSourceValue.h.
References ConstantPool.
Referenced by isAliased(), isConstant(), and mayAlias().
isGOT()
bool llvm::PseudoSourceValue::isGOT () const inline
Definition at line 70 of file PseudoSourceValue.h.
References GOT.
Referenced by isAliased(), isConstant(), and mayAlias().
isJumpTable()
bool llvm::PseudoSourceValue::isJumpTable () const inline
Definition at line 72 of file PseudoSourceValue.h.
References JumpTable.
Referenced by isAliased(), isConstant(), and mayAlias().
isStack()
bool llvm::PseudoSourceValue::isStack () const inline
Definition at line 69 of file PseudoSourceValue.h.
References Stack.
Referenced by isAliased(), isConstant(), and isStackPtrRelative().
kind()
unsigned llvm::PseudoSourceValue::kind () const inline
Definition at line 67 of file PseudoSourceValue.h.
Referenced by llvm::AMDGPUBufferPseudoSourceValue::classof(), llvm::AMDGPUImagePseudoSourceValue::classof(), llvm::AMDGPUGWSResourcePseudoSourceValue::classof(), llvm::FixedStackPseudoSourceValue::classof(), llvm::GlobalValuePseudoSourceValue::classof(), llvm::ExternalSymbolPseudoSourceValue::classof(), and INITIALIZE_PASS().
mayAlias()
bool PseudoSourceValue::mayAlias (const MachineFrameInfo *) const virtual
Return true if the memory pointed to by this PseudoSourceValue can ever alias an LLVM IR Value.
Reimplemented in llvm::CallEntryPseudoSourceValue, llvm::FixedStackPseudoSourceValue, llvm::AMDGPUGWSResourcePseudoSourceValue, and llvm::AMDGPUPseudoSourceValue.
Definition at line 56 of file PseudoSourceValue.cpp.
References isConstantPool(), isGOT(), and isJumpTable().
Referenced by llvm::FixedStackPseudoSourceValue::classof(), llvm::TargetInstrInfo::describeLoadedValue(), getTargetCustom(), and llvm::MachineInstr::mayAlias().
Friends And Related Function Documentation
llvm::operator<<
raw_ostream& llvm::operator<< (raw_ostream & OS, const PseudoSourceValue * PSV) friend
MachineMemOperand
friend class MachineMemOperand friend
Definition at line 55 of file PseudoSourceValue.h.
MIRFormatter
friend class MIRFormatter friend
Definition at line 56 of file PseudoSourceValue.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/PseudoSourceValue.h
lib/CodeGen/PseudoSourceValue.cpp