LLVM: llvm::R600InstPrinter Class Reference
llvm::R600InstPrinter Class Reference
#include "Target/AMDGPU/MCTargetDesc/AMDGPUInstPrinter.h"
Public Member Functions
R600InstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printAbs (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printBankSwizzle (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printClamp (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printCT (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printKCache (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLast (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLiteral (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printNeg (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printOMOD (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printRel (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printRSel (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printUpdateExecMask (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printUpdatePred (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printWrite (const MCInst *MI, unsigned OpNo, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 237 of file AMDGPUInstPrinter.h.
Constructor & Destructor Documentation
R600InstPrinter()
llvm::R600InstPrinter::R600InstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 239 of file AMDGPUInstPrinter.h.
References llvm::Address, llvm::AMDGPUInstPrinter::getRegisterName(), MI, llvm::RISCVFenceField::O, llvm::AMDGPUInstPrinter::printAbs(), llvm::AMDGPUInstPrinter::printBankSwizzle(), llvm::AMDGPUInstPrinter::printClamp(), llvm::AMDGPUInstPrinter::printCT(), llvm::AMDGPUInstPrinter::printInst(), llvm::AMDGPUInstPrinter::printInstruction(), llvm::AMDGPUInstPrinter::printKCache(), llvm::AMDGPUInstPrinter::printLast(), llvm::AMDGPUInstPrinter::printLiteral(), llvm::AMDGPUInstPrinter::printNeg(), llvm::AMDGPUInstPrinter::printOMOD(), llvm::AMDGPUInstPrinter::printRel(), llvm::AMDGPUInstPrinter::printRSel(), llvm::AMDGPUInstPrinter::printUpdateExecMask(), llvm::AMDGPUInstPrinter::printUpdatePred(), and llvm::AMDGPUInstPrinter::printWrite().
Member Function Documentation
getRegisterName()
static const char* llvm::R600InstPrinter::getRegisterName (unsigned RegNo) static
printAbs()
void R600InstPrinter::printAbs (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1354 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPUInstPrinter::printIfSet().
printBankSwizzle()
void R600InstPrinter::printBankSwizzle (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1359 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
printClamp()
void R600InstPrinter::printClamp (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1383 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPUInstPrinter::printIfSet().
printCT()
void R600InstPrinter::printCT (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1388 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
printInst()
void R600InstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 1346 of file AMDGPUInstPrinter.cpp.
References llvm::raw_ostream::flush().
printInstruction()
void llvm::R600InstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
printKCache()
void R600InstPrinter::printKCache (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1403 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
printLast()
void R600InstPrinter::printLast (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1415 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPUInstPrinter::printIfSet().
printLiteral()
void R600InstPrinter::printLiteral (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1420 of file AMDGPUInstPrinter.cpp.
References assert(), llvm::BitsToFloat(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and llvm::MCExpr::print().
printMemOperand()
void R600InstPrinter::printMemOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1454 of file AMDGPUInstPrinter.cpp.
References printOperand().
printNeg()
void R600InstPrinter::printNeg (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1433 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPUInstPrinter::printIfSet().
printOMOD()
void R600InstPrinter::printOMOD (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1438 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
printOperand()
void R600InstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1461 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getFPImm(), llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isFPImm(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::MCExpr::print().
printRel()
void R600InstPrinter::printRel (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1496 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPUInstPrinter::printIfSet().
printRSel()
void R600InstPrinter::printRSel (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1501 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
printUpdateExecMask()
void R600InstPrinter::printUpdateExecMask (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1531 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPUInstPrinter::printIfSet().
printUpdatePred()
void R600InstPrinter::printUpdatePred (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1536 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPUInstPrinter::printIfSet().
printWrite()
void R600InstPrinter::printWrite (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 1541 of file AMDGPUInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUInstPrinter.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUInstPrinter.cpp