LLVM: llvm::DiagnosticInfoResourceLimit Class Reference
llvm::DiagnosticInfoResourceLimit Class Reference
Diagnostic information for stack size etc.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoResourceLimit (const Function &Fn, const char *ResourceName, uint64_t ResourceSize, DiagnosticSeverity Severity=DS_Warning, DiagnosticKind Kind=DK_ResourceLimit, uint64_t ResourceLimit=0)
The function that is concerned by this stack size diagnostic.
const Function & getFunction () const
const char * getResourceName () const
uint64_t getResourceSize () const
uint64_t getResourceLimit () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for stack size etc.
reporting. This is basically a function and a size.
Definition at line 176 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoResourceLimit()
llvm::DiagnosticInfoResourceLimit::DiagnosticInfoResourceLimit (const Function & Fn, const char * ResourceName, uint64_t ResourceSize, DiagnosticSeverity Severity = DS_Warning, DiagnosticKind Kind = DK_ResourceLimit, uint64_t ResourceLimit = 0) inline
The function that is concerned by this stack size diagnostic.
The computed stack size.
Definition at line 193 of file DiagnosticInfo.h.
Member Function Documentation
classof()
static bool llvm::DiagnosticInfoResourceLimit::classof (const DiagnosticInfo * DI) inline static
Definition at line 209 of file DiagnosticInfo.h.
References llvm::DK_ResourceLimit, llvm::DK_StackSize, and llvm::DiagnosticInfo::getKind().
getFunction()
const Function& llvm::DiagnosticInfoResourceLimit::getFunction () const inline
Definition at line 201 of file DiagnosticInfo.h.
getResourceLimit()
uint64_t llvm::DiagnosticInfoResourceLimit::getResourceLimit () const inline
Definition at line 204 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::print().
getResourceName()
const char* llvm::DiagnosticInfoResourceLimit::getResourceName () const inline
Definition at line 202 of file DiagnosticInfo.h.
getResourceSize()
uint64_t llvm::DiagnosticInfoResourceLimit::getResourceSize () const inline
Definition at line 203 of file DiagnosticInfo.h.
print()
void DiagnosticInfoResourceLimit::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 71 of file DiagnosticInfo.cpp.
References getFunction().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp