LLVM: llvm::MipsTargetELFStreamer Class Reference
llvm::MipsTargetELFStreamer Class Reference
#include "Target/Mips/MipsTargetStreamer.h"
Public Member Functions
bool isMicroMipsEnabled () const
MCELFStreamer & getStreamer ()
MipsTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
void setPic (bool Value) override
void emitLabel (MCSymbol *Symbol) override
void emitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
void finish () override
void emitDirectiveSetMicroMips () override
void emitDirectiveSetNoMicroMips () override
void setUsesMicroMips () override
void emitDirectiveSetMips16 () override
void emitDirectiveSetNoReorder () override
void emitDirectiveEnd (StringRef Name) override
void emitDirectiveEnt (const MCSymbol &Symbol) override
void emitDirectiveAbiCalls () override
void emitDirectiveNaN2008 () override
void emitDirectiveNaNLegacy () override
void emitDirectiveOptionPic0 () override
void emitDirectiveOptionPic2 () override
void emitDirectiveInsn () override
void emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) override
void emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override
void emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override
void emitDirectiveCpLoad (unsigned RegNo) override
void emitDirectiveCpLocal (unsigned RegNo) override
bool emitDirectiveCpRestore (int Offset, function_ref< unsigned()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI) override
void emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol &Sym, bool IsReg) override
void emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister) override
void emitMipsAbiFlags ()
Public Member Functions inherited from llvm::MipsTargetStreamer
MipsTargetStreamer (MCStreamer &S)
virtual void emitDirectiveSetNoMips16 ()
virtual void emitDirectiveSetReorder ()
virtual void emitDirectiveSetMacro ()
virtual void emitDirectiveSetNoMacro ()
virtual void emitDirectiveSetMsa ()
virtual void emitDirectiveSetNoMsa ()
virtual void emitDirectiveSetMt ()
virtual void emitDirectiveSetNoMt ()
virtual void emitDirectiveSetCRC ()
virtual void emitDirectiveSetNoCRC ()
virtual void emitDirectiveSetVirt ()
virtual void emitDirectiveSetNoVirt ()
virtual void emitDirectiveSetGINV ()
virtual void emitDirectiveSetNoGINV ()
virtual void emitDirectiveSetAt ()
virtual void emitDirectiveSetAtWithArg (unsigned RegNo)
virtual void emitDirectiveSetNoAt ()
virtual void emitDirectiveSetArch (StringRef Arch)
virtual void emitDirectiveSetMips0 ()
virtual void emitDirectiveSetMips1 ()
virtual void emitDirectiveSetMips2 ()
virtual void emitDirectiveSetMips3 ()
virtual void emitDirectiveSetMips4 ()
virtual void emitDirectiveSetMips5 ()
virtual void emitDirectiveSetMips32 ()
virtual void emitDirectiveSetMips32R2 ()
virtual void emitDirectiveSetMips32R3 ()
virtual void emitDirectiveSetMips32R5 ()
virtual void emitDirectiveSetMips32R6 ()
virtual void emitDirectiveSetMips64 ()
virtual void emitDirectiveSetMips64R2 ()
virtual void emitDirectiveSetMips64R3 ()
virtual void emitDirectiveSetMips64R5 ()
virtual void emitDirectiveSetMips64R6 ()
virtual void emitDirectiveSetDsp ()
virtual void emitDirectiveSetDspr2 ()
virtual void emitDirectiveSetNoDsp ()
virtual void emitDirectiveSetPop ()
virtual void emitDirectiveSetPush ()
virtual void emitDirectiveSetSoftFloat ()
virtual void emitDirectiveSetHardFloat ()
virtual void emitDirectiveModuleFP ()
virtual void emitDirectiveModuleOddSPReg ()
virtual void emitDirectiveModuleSoftFloat ()
virtual void emitDirectiveModuleHardFloat ()
virtual void emitDirectiveModuleMT ()
virtual void emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value)
virtual void emitDirectiveSetOddSPReg ()
virtual void emitDirectiveSetNoOddSPReg ()
virtual void emitDirectiveModuleCRC ()
virtual void emitDirectiveModuleNoCRC ()
virtual void emitDirectiveModuleVirt ()
virtual void emitDirectiveModuleNoVirt ()
virtual void emitDirectiveModuleGINV ()
virtual void emitDirectiveModuleNoGINV ()
void emitR (unsigned Opcode, unsigned Reg0, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitII (unsigned Opcode, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRX (unsigned Opcode, unsigned Reg0, MCOperand Op1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRI (unsigned Opcode, unsigned Reg0, int32_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRR (unsigned Opcode, unsigned Reg0, unsigned Reg1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRX (unsigned Opcode, unsigned Reg0, unsigned Reg1, MCOperand Op2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRR (unsigned Opcode, unsigned Reg0, unsigned Reg1, unsigned Reg2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRRX (unsigned Opcode, unsigned Reg0, unsigned Reg1, unsigned Reg2, MCOperand Op3, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRI (unsigned Opcode, unsigned Reg0, unsigned Reg1, int16_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRIII (unsigned Opcode, unsigned Reg0, unsigned Reg1, int16_t Imm0, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitAddu (unsigned DstReg, unsigned SrcReg, unsigned TrgReg, bool Is64Bit, const MCSubtargetInfo *STI)
void emitDSLL (unsigned DstReg, unsigned SrcReg, int16_t ShiftAmount, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitEmptyDelaySlot (bool hasShortDelaySlot, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitNop (SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitStoreWithImmOffset (unsigned Opcode, unsigned SrcReg, unsigned BaseReg, int64_t Offset, function_ref< unsigned()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a store instruction with an offset.
void emitLoadWithImmOffset (unsigned Opcode, unsigned DstReg, unsigned BaseReg, int64_t Offset, unsigned TmpReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a load instruction with an immediate offset.
void emitGPRestore (int Offset, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit the $gp restore operation for .cprestore.
void forbidModuleDirective ()
void reallowModuleDirective ()
bool isModuleDirectiveAllowed ()
template<class PredicateLibrary >
void updateABIInfo (const PredicateLibrary &P)
MipsABIFlagsSection & getABIFlagsSection ()
const MipsABIInfo & getABI () const
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
Additional Inherited Members
Protected Attributes inherited from llvm::MipsTargetStreamer
llvm::Optional< MipsABIInfo > ABI
MipsABIFlagsSection ABIFlagsSection
bool GPRInfoSet
unsigned GPRBitMask
int GPROffset
bool FPRInfoSet
unsigned FPRBitMask
int FPROffset
bool FrameInfoSet
int FrameOffset
unsigned FrameReg
unsigned GPReg
unsigned ReturnReg
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 307 of file MipsTargetStreamer.h.
Constructor & Destructor Documentation
MipsTargetELFStreamer()
MipsTargetELFStreamer::MipsTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 767 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABI, llvm::ELF::EF_MIPS_ARCH_1, llvm::ELF::EF_MIPS_ARCH_2, llvm::ELF::EF_MIPS_ARCH_3, llvm::ELF::EF_MIPS_ARCH_32, llvm::ELF::EF_MIPS_ARCH_32R2, llvm::ELF::EF_MIPS_ARCH_32R6, llvm::ELF::EF_MIPS_ARCH_4, llvm::ELF::EF_MIPS_ARCH_5, llvm::ELF::EF_MIPS_ARCH_64, llvm::ELF::EF_MIPS_ARCH_64R2, llvm::ELF::EF_MIPS_ARCH_64R6, llvm::ELF::EF_MIPS_MACH_OCTEON, llvm::ELF::EF_MIPS_NAN2008, llvm::Triple::getArch(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCAssembler::getELFHeaderEFlags(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCContext::getObjectFileInfo(), getStreamer(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::MCObjectFileInfo::isPositionIndependent(), llvm::MipsABIInfo::N64(), llvm::MipsABIInfo::O32(), and llvm::MCAssembler::setELFHeaderEFlags().
Member Function Documentation
emitAssignment()
void MipsTargetELFStreamer::emitAssignment (MCSymbol * Symbol, const MCExpr * Value) override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 931 of file MipsTargetStreamer.cpp.
References llvm::MCExpr::getKind(), llvm::ELF::STO_MIPS_MICROMIPS, llvm::ARMBuildAttrs::Symbol, and llvm::MCExpr::SymbolRef.
emitDirectiveAbiCalls()
void MipsTargetELFStreamer::emitDirectiveAbiCalls () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1038 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveCpLoad()
void MipsTargetELFStreamer::emitDirectiveCpLoad (unsigned RegNo) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1111 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::clear(), llvm::MipsMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createReg(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsTargetStreamer::getABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getOrCreateSymbol(), getStreamer(), llvm::MipsTargetStreamer::GPReg, llvm::MipsMCExpr::MEK_HI, llvm::MipsMCExpr::MEK_LO, llvm::MCAssembler::registerSymbol(), llvm::MCInst::setOpcode(), and llvm::MCSymbolRefExpr::VK_None.
emitDirectiveCpLocal()
void MipsTargetELFStreamer::emitDirectiveCpLocal (unsigned RegNo) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1168 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveCpLocal().
emitDirectiveCpRestore()
bool MipsTargetELFStreamer::emitDirectiveCpRestore (int Offset, function_ref< unsigned()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo * STI) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1173 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveCpRestore(), llvm::MipsTargetStreamer::emitStoreWithImmOffset(), llvm::MipsTargetStreamer::getABI(), and llvm::MipsTargetStreamer::GPReg.
emitDirectiveCpreturn()
void MipsTargetELFStreamer::emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1253 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsTargetStreamer::getABI(), getStreamer(), llvm::MipsTargetStreamer::GPReg, llvm::ARM_MB::LD, llvm::ISD::OR, and llvm::MCInst::setOpcode().
emitDirectiveCpsetup()
void MipsTargetELFStreamer::emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol & Sym, bool IsReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1194 of file MipsTargetStreamer.cpp.
References llvm::MipsMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MipsMCExpr::createGpOff(), llvm::MipsTargetStreamer::emitRRI(), llvm::MipsTargetStreamer::emitRRR(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsTargetStreamer::getABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getOrCreateSymbol(), getStreamer(), llvm::MipsTargetStreamer::GPReg, llvm::MipsMCExpr::MEK_HI, and llvm::MipsMCExpr::MEK_LO.
emitDirectiveEnd()
void MipsTargetELFStreamer::emitDirectiveEnd (StringRef Name) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 982 of file MipsTargetStreamer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValueImpl(), llvm::MipsTargetStreamer::FPRBitMask, llvm::MipsTargetStreamer::FPRInfoSet, llvm::MipsTargetStreamer::FPROffset, llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::FrameOffset, llvm::MipsTargetStreamer::FrameReg, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::MCContext::getOrCreateSymbol(), getStreamer(), llvm::MipsTargetStreamer::GPRBitMask, llvm::MipsTargetStreamer::GPRInfoSet, llvm::MipsTargetStreamer::GPROffset, llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::MCAssembler::registerSection(), llvm::MipsTargetStreamer::ReturnReg, llvm::MCSection::setAlignment(), llvm::ELF::SHT_PROGBITS, Size, llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
emitDirectiveEnt()
void MipsTargetELFStreamer::emitDirectiveEnt (const MCSymbol & Symbol) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1031 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FPRInfoSet, llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::GPRInfoSet, llvm::ELF::STT_FUNC, and llvm::ARMBuildAttrs::Symbol.
emitDirectiveInsn()
void MipsTargetELFStreamer::emitDirectiveInsn () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1080 of file MipsTargetStreamer.cpp.
References llvm::MipsELFStreamer::createPendingLabelRelocs(), llvm::MipsTargetStreamer::emitDirectiveInsn(), and llvm::MCTargetStreamer::Streamer.
emitDirectiveNaN2008()
void MipsTargetELFStreamer::emitDirectiveNaN2008 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1045 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_NAN2008, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveNaNLegacy()
void MipsTargetELFStreamer::emitDirectiveNaNLegacy () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1052 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_NAN2008, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveOptionPic0()
void MipsTargetELFStreamer::emitDirectiveOptionPic0 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1059 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_PIC, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveOptionPic2()
void MipsTargetELFStreamer::emitDirectiveOptionPic2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1068 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveSetMicroMips()
void MipsTargetELFStreamer::emitDirectiveSetMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 949 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetMips16()
void MipsTargetELFStreamer::emitDirectiveSetMips16 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 966 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_ARCH_ASE_M16, llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveSetNoMicroMips()
void MipsTargetELFStreamer::emitDirectiveSetNoMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 954 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetNoReorder()
void MipsTargetELFStreamer::emitDirectiveSetNoReorder () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 974 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_NOREORDER, llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitFMask()
void MipsTargetELFStreamer::emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1104 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FPRBitMask, llvm::MipsTargetStreamer::FPRInfoSet, and llvm::MipsTargetStreamer::FPROffset.
emitFrame()
void MipsTargetELFStreamer::emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1086 of file MipsTargetStreamer.cpp.
References Context, llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::FrameOffset, llvm::MipsTargetStreamer::FrameReg, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCContext::getRegisterInfo(), getStreamer(), and llvm::MipsTargetStreamer::ReturnReg.
emitLabel()
void MipsTargetELFStreamer::emitLabel (MCSymbol * Symbol) override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 846 of file MipsTargetStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), getStreamer(), isMicroMipsEnabled(), llvm::MCAssembler::registerSymbol(), llvm::ELF::STO_MIPS_MICROMIPS, llvm::ELF::STT_FUNC, and llvm::ARMBuildAttrs::Symbol.
emitMask()
void MipsTargetELFStreamer::emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1097 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::GPRBitMask, llvm::MipsTargetStreamer::GPRInfoSet, and llvm::MipsTargetStreamer::GPROffset.
emitMipsAbiFlags()
void MipsTargetELFStreamer::emitMipsAbiFlags ()
Definition at line 1277 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, Context, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), getStreamer(), llvm::MCAssembler::registerSection(), llvm::MCSection::setAlignment(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_MIPS_ABIFLAGS, and llvm::MCStreamer::SwitchSection().
Referenced by finish().
finish()
void MipsTargetELFStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 857 of file MipsTargetStreamer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::ELF::EF_MIPS_32BITMODE, llvm::ELF::EF_MIPS_ABI2, llvm::ELF::EF_MIPS_ABI_O32, llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, llvm::MCStreamer::EmitCodeAlignment(), emitMipsAbiFlags(), llvm::MipsELFStreamer::EmitMipsOptionRecords(), llvm::MCStreamer::EmitValueToAlignment(), llvm::MipsTargetStreamer::getABI(), llvm::MCSection::getAlignment(), llvm::MCObjectStreamer::getAssembler(), llvm::MCObjectFileInfo::getBSSSection(), llvm::MCAssembler::getContext(), llvm::MCObjectFileInfo::getDataSection(), llvm::MCAssembler::getELFHeaderEFlags(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCContext::getObjectFileInfo(), getStreamer(), llvm::MCObjectFileInfo::getTextSection(), llvm::max(), llvm::MCAssembler::registerSection(), llvm::ARMBuildAttrs::Section, llvm::MCSection::setAlignment(), llvm::MCAssembler::setELFHeaderEFlags(), llvm::MCTargetStreamer::Streamer, llvm::MCStreamer::SwitchSection(), and llvm::MCSectionELF::UseCodeAlign().
getStreamer()
MCELFStreamer & MipsTargetELFStreamer::getStreamer ()
Definition at line 945 of file MipsTargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by emitDirectiveAbiCalls(), emitDirectiveCpLoad(), emitDirectiveCpreturn(), emitDirectiveCpsetup(), emitDirectiveEnd(), emitDirectiveNaN2008(), emitDirectiveNaNLegacy(), emitDirectiveOptionPic0(), emitDirectiveOptionPic2(), emitDirectiveSetMips16(), emitDirectiveSetNoReorder(), emitFrame(), emitLabel(), emitMipsAbiFlags(), finish(), MipsTargetELFStreamer(), and setUsesMicroMips().
isMicroMipsEnabled()
bool llvm::MipsTargetELFStreamer::isMicroMipsEnabled () const inline
Definition at line 313 of file MipsTargetStreamer.h.
References llvm::MCTargetStreamer::getStreamer().
Referenced by llvm::MipsELFStreamer::createPendingLabelRelocs(), and emitLabel().
setPic()
void llvm::MipsTargetELFStreamer::setPic (bool Value) inline override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 317 of file MipsTargetStreamer.h.
References llvm::MCTargetStreamer::emitAssignment(), llvm::MipsTargetStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetStreamer::emitDirectiveCpLoad(), llvm::MipsTargetStreamer::emitDirectiveCpLocal(), llvm::MipsTargetStreamer::emitDirectiveCpRestore(), llvm::MipsTargetStreamer::emitDirectiveCpreturn(), llvm::MipsTargetStreamer::emitDirectiveCpsetup(), llvm::MipsTargetStreamer::emitDirectiveEnd(), llvm::MipsTargetStreamer::emitDirectiveEnt(), llvm::MipsTargetStreamer::emitDirectiveInsn(), llvm::MipsTargetStreamer::emitDirectiveNaN2008(), llvm::MipsTargetStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetStreamer::emitDirectiveOptionPic2(), llvm::MipsTargetStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetMips16(), llvm::MipsTargetStreamer::emitDirectiveSetNoMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetNoReorder(), llvm::MipsTargetStreamer::emitFMask(), llvm::MipsTargetStreamer::emitFrame(), llvm::MCTargetStreamer::emitLabel(), llvm::MipsTargetStreamer::emitMask(), llvm::MCTargetStreamer::finish(), Name, llvm::MipsTargetStreamer::ReturnReg, llvm::MipsTargetStreamer::setUsesMicroMips(), and llvm::ARMBuildAttrs::Symbol.
setUsesMicroMips()
void MipsTargetELFStreamer::setUsesMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 959 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_MICROMIPS, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsTargetStreamer.h
lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp