LLVM: llvm::SystemZMachineFunctionInfo Class Reference
llvm::SystemZMachineFunctionInfo Class Reference
#include "Target/SystemZ/SystemZMachineFunctionInfo.h"
Public Member Functions
SystemZMachineFunctionInfo (MachineFunction &MF)
SystemZ::GPRRegs getSpillGPRRegs () const
void setSpillGPRRegs (unsigned Low, unsigned High, unsigned Offs)
SystemZ::GPRRegs getRestoreGPRRegs () const
void setRestoreGPRRegs (unsigned Low, unsigned High, unsigned Offs)
unsigned getVarArgsFirstGPR () const
void setVarArgsFirstGPR (unsigned GPR)
unsigned getVarArgsFirstFPR () const
void setVarArgsFirstFPR (unsigned FPR)
unsigned getVarArgsFrameIndex () const
void setVarArgsFrameIndex (unsigned FI)
unsigned getRegSaveFrameIndex () const
void setRegSaveFrameIndex (unsigned FI)
int getFramePointerSaveIndex () const
void setFramePointerSaveIndex (int Idx)
bool getManipulatesSP () const
void setManipulatesSP (bool MSP)
unsigned getNumLocalDynamicTLSAccesses () const
void incNumLocalDynamicTLSAccesses ()
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 27 of file SystemZMachineFunctionInfo.h.
Constructor & Destructor Documentation
SystemZMachineFunctionInfo()
llvm::SystemZMachineFunctionInfo::SystemZMachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 41 of file SystemZMachineFunctionInfo.h.
Member Function Documentation
getFramePointerSaveIndex()
int llvm::SystemZMachineFunctionInfo::getFramePointerSaveIndex () const inline
Definition at line 85 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::getOrCreateFramePointerSaveIndex().
getManipulatesSP()
bool llvm::SystemZMachineFunctionInfo::getManipulatesSP () const inline
Definition at line 90 of file SystemZMachineFunctionInfo.h.
getNumLocalDynamicTLSAccesses()
unsigned llvm::SystemZMachineFunctionInfo::getNumLocalDynamicTLSAccesses () const inline
Definition at line 94 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::createSystemZLDCleanupPass().
getRegSaveFrameIndex()
unsigned llvm::SystemZMachineFunctionInfo::getRegSaveFrameIndex () const inline
Definition at line 81 of file SystemZMachineFunctionInfo.h.
getRestoreGPRRegs()
SystemZ::GPRRegs llvm::SystemZMachineFunctionInfo::getRestoreGPRRegs () const inline
Definition at line 59 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::emitEpilogue(), and llvm::SystemZFrameLowering::restoreCalleeSavedRegisters().
getSpillGPRRegs()
SystemZ::GPRRegs llvm::SystemZMachineFunctionInfo::getSpillGPRRegs () const inline
Definition at line 49 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::emitPrologue(), and llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
getVarArgsFirstFPR()
unsigned llvm::SystemZMachineFunctionInfo::getVarArgsFirstFPR () const inline
Definition at line 72 of file SystemZMachineFunctionInfo.h.
getVarArgsFirstGPR()
unsigned llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR () const inline
Definition at line 68 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZFrameLowering::determineCalleeSaves(), and llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
getVarArgsFrameIndex()
unsigned llvm::SystemZMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 76 of file SystemZMachineFunctionInfo.h.
incNumLocalDynamicTLSAccesses()
void llvm::SystemZMachineFunctionInfo::incNumLocalDynamicTLSAccesses () inline
Definition at line 95 of file SystemZMachineFunctionInfo.h.
setFramePointerSaveIndex()
void llvm::SystemZMachineFunctionInfo::setFramePointerSaveIndex (int Idx) inline
Definition at line 86 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::getOrCreateFramePointerSaveIndex().
setManipulatesSP()
void llvm::SystemZMachineFunctionInfo::setManipulatesSP (bool MSP) inline
Definition at line 91 of file SystemZMachineFunctionInfo.h.
setRegSaveFrameIndex()
void llvm::SystemZMachineFunctionInfo::setRegSaveFrameIndex (unsigned FI) inline
Definition at line 82 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setRestoreGPRRegs()
void llvm::SystemZMachineFunctionInfo::setRestoreGPRRegs (unsigned Low, unsigned High, unsigned Offs) inline
Definition at line 60 of file SystemZMachineFunctionInfo.h.
References llvm::SystemZ::GPRRegs::GPROffset, High, llvm::SystemZ::GPRRegs::HighGPR, and llvm::SystemZ::GPRRegs::LowGPR.
Referenced by llvm::SystemZFrameLowering::assignCalleeSavedSpillSlots().
setSpillGPRRegs()
void llvm::SystemZMachineFunctionInfo::setSpillGPRRegs (unsigned Low, unsigned High, unsigned Offs) inline
Definition at line 50 of file SystemZMachineFunctionInfo.h.
References llvm::SystemZ::GPRRegs::GPROffset, High, llvm::SystemZ::GPRRegs::HighGPR, and llvm::SystemZ::GPRRegs::LowGPR.
Referenced by llvm::SystemZFrameLowering::assignCalleeSavedSpillSlots().
setVarArgsFirstFPR()
void llvm::SystemZMachineFunctionInfo::setVarArgsFirstFPR (unsigned FPR) inline
Definition at line 73 of file SystemZMachineFunctionInfo.h.
References FPR.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setVarArgsFirstGPR()
void llvm::SystemZMachineFunctionInfo::setVarArgsFirstGPR (unsigned GPR) inline
Definition at line 69 of file SystemZMachineFunctionInfo.h.
References llvm::GPR.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setVarArgsFrameIndex()
void llvm::SystemZMachineFunctionInfo::setVarArgsFrameIndex (unsigned FI) inline
Definition at line 77 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZMachineFunctionInfo.h
lib/Target/SystemZ/SystemZMachineFunctionInfo.cpp