LLVM: llvm::LoopInstSimplifyPass Class Reference
llvm::LoopInstSimplifyPass Class Reference
Performs Loop Inst Simplify Pass.
#include "llvm/Transforms/Scalar/LoopInstSimplify.h"
Public Member Functions
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopInstSimplifyPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Performs Loop Inst Simplify Pass.
Definition at line 25 of file LoopInstSimplify.h.
Member Function Documentation
run()
PreservedAnalyses LoopInstSimplifyPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 224 of file LoopInstSimplify.cpp.
References llvm::LoopStandardAnalysisResults::AC, llvm::PreservedAnalyses::all(), llvm::LoopStandardAnalysisResults::DT, llvm::getLoopPassPreservedAnalyses(), llvm::Optional< T >::getPointer(), llvm::Optional< T >::hasValue(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::LoopStandardAnalysisResults::LI, llvm::LoopStandardAnalysisResults::MSSA, simplifyLoopInst(), llvm::LoopStandardAnalysisResults::TLI, llvm::VerifyMemorySSA, and llvm::MemorySSA::verifyMemorySSA().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopInstSimplify.h
lib/Transforms/Scalar/LoopInstSimplify.cpp