LLVM: llvm::CCValAssign Class Reference
llvm::CCValAssign Class Reference
CCValAssign - Represent assignment of one arg/retval to a location.
#include "llvm/CodeGen/CallingConvLower.h"
Public Types
enum LocInfo {
Full, SExt, ZExt, AExt,
SExtUpper, ZExtUpper, AExtUpper, BCvt,
Trunc, VExt, FPExt, Indirect
}
Public Member Functions
void convertToReg (unsigned RegNo)
void convertToMem (unsigned Offset)
unsigned getValNo () const
MVT getValVT () const
bool isRegLoc () const
bool isMemLoc () const
bool needsCustom () const
Register getLocReg () const
unsigned getLocMemOffset () const
unsigned getExtraInfo () const
MVT getLocVT () const
LocInfo getLocInfo () const
bool isExtInLoc () const
bool isUpperBitsInLoc () const
Static Public Member Functions
static CCValAssign getReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP)
static CCValAssign getCustomReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP)
static CCValAssign getMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP)
static CCValAssign getCustomMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP)
static CCValAssign getPending (unsigned ValNo, MVT ValVT, MVT LocVT, LocInfo HTP, unsigned ExtraInfo=0)
Detailed Description
CCValAssign - Represent assignment of one arg/retval to a location.
Definition at line 33 of file CallingConvLower.h.
Member Enumeration Documentation
LocInfo
enum llvm::CCValAssign::LocInfo
Enumerator
Full
SExt
ZExt
AExt
SExtUpper
ZExtUpper
AExtUpper
BCvt
Trunc
VExt
FPExt
Indirect
Definition at line 35 of file CallingConvLower.h.
Member Function Documentation
convertToMem()
void llvm::CCValAssign::convertToMem (unsigned Offset) inline
Definition at line 137 of file CallingConvLower.h.
convertToReg()
void llvm::CCValAssign::convertToReg (unsigned RegNo) inline
Definition at line 132 of file CallingConvLower.h.
Referenced by lowerRegToMasks(), and Passv64i1ArgInRegs().
getCustomMem()
static CCValAssign llvm::CCValAssign::getCustomMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP) inline static
Definition at line 116 of file CallingConvLower.h.
References getMem(), and llvm::MipsISD::Ret.
Referenced by llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), CC_Sparc_Assign_Split_64(), CC_Sparc_Assign_SRet(), f64AssignAAPCS(), and f64AssignAPCS().
getCustomReg()
static CCValAssign llvm::CCValAssign::getCustomReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP) inline static
Definition at line 93 of file CallingConvLower.h.
References getReg(), and llvm::MipsISD::Ret.
Referenced by CC_AIX(), CC_PPC32_SPE_CustomSplitFP64(), CC_PPC32_SPE_RetF64(), CC_Sparc64_Half(), CC_Sparc_Assign_Ret_Split_64(), CC_Sparc_Assign_Split_64(), CC_X86_32_RegCall_Assign2Regs(), f64AssignAAPCS(), f64AssignAPCS(), f64RetAssign(), and fixupVariableFloatArgs().
getExtraInfo()
unsigned llvm::CCValAssign::getExtraInfo () const inline
Definition at line 152 of file CallingConvLower.h.
getLocInfo()
LocInfo llvm::CCValAssign::getLocInfo () const inline
Definition at line 155 of file CallingConvLower.h.
Referenced by llvm::AArch64CallLowering::AArch64CallLowering(), llvm::analyzeArguments(), AnalyzeReturnValues(), canUseSiblingCall(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), convertLocVTToValVT(), convertValVTToLocVT(), llvm::CallLowering::ValueHandler::extendRegister(), fixupVariableFloatArgs(), getComparePred(), getMOVL(), llvm::ARCTargetLowering::getTargetNodeName(), llvm::MipsCallLowering::MipsHandler::handle(), isFunctionGlobalAddress(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::BPFTargetLowering::LowerOperation(), lowerRegToMasks(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), MatchingStackOffset(), mayTailCallThisCC(), Passv64i1ArgInRegs(), llvm::CCState::resultsCompatible(), shouldGuaranteeTCO(), truncateScalarIntegerArg(), UnpackFromArgumentSlot(), unpackFromMemLoc(), and unpackFromRegLoc().
getLocMemOffset()
unsigned llvm::CCValAssign::getLocMemOffset () const inline
Definition at line 151 of file CallingConvLower.h.
References assert(), and isMemLoc().
Referenced by llvm::analyzeArguments(), AnalyzeReturnValues(), buildCallOperands(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), EnsureStackAlignment(), getComparePred(), getMOVL(), llvm::ARCTargetLowering::getTargetNodeName(), llvm::MipsCallLowering::MipsHandler::handle(), isSortedByValueNo(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerCallResult(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerVASTART(), MatchingStackOffset(), mayTailCallThisCC(), llvm::CallLowering::resultsCompatible(), llvm::CCState::resultsCompatible(), setLocInfo(), shouldGuaranteeTCO(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), and unpackFromMemLoc().
getLocReg()
Register llvm::CCValAssign::getLocReg () const inline
Definition at line 150 of file CallingConvLower.h.
References assert(), and isRegLoc().
Referenced by llvm::analyzeArguments(), AnalyzeReturnValues(), buildCallOperands(), canUseSiblingCall(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), EnsureStackAlignment(), fixupVariableFloatArgs(), getComparePred(), getMOVL(), llvm::ARCTargetLowering::getTargetNodeName(), getv64i1Argument(), llvm::MipsCallLowering::MipsHandler::handle(), isFunctionGlobalAddress(), isSupportedType(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::BPFTargetLowering::LowerOperation(), lowerRegToMasks(), llvm::ARMCallLowering::lowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), MatchingStackOffset(), mayTailCallThisCC(), llvm::TargetLowering::parametersInCSRMatch(), Passv64i1ArgInRegs(), llvm::CallLowering::resultsCompatible(), llvm::CCState::resultsCompatible(), setLocInfo(), truncateScalarIntegerArg(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), and unpackFromRegLoc().
getLocVT()
MVT llvm::CCValAssign::getLocVT () const inline
Definition at line 153 of file CallingConvLower.h.
Referenced by llvm::AArch64CallLowering::AArch64CallLowering(), llvm::analyzeArguments(), AnalyzeReturnValues(), buildCallOperands(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), CC_RISCVAssign2XLen(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), convertLocVTToValVT(), convertValVTToLocVT(), EnsureStackAlignment(), llvm::CallLowering::ValueHandler::extendRegister(), fixupVariableFloatArgs(), getComparePred(), getMOVL(), llvm::ARCTargetLowering::getTargetNodeName(), llvm::MipsCallLowering::MipsHandler::handle(), isFunctionGlobalAddress(), isSupportedType(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::BPFTargetLowering::LowerOperation(), lowerRegToMasks(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), MatchingStackOffset(), mayTailCallThisCC(), Passv64i1ArgInRegs(), setLocInfo(), shouldGuaranteeTCO(), truncateScalarIntegerArg(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), unpackFromMemLoc(), unpackFromRegLoc(), and llvm::X86CallLowering::X86CallLowering().
getMem()
static CCValAssign llvm::CCValAssign::getMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP) inline static
Definition at line 102 of file CallingConvLower.h.
References llvm::MipsISD::Ret.
Referenced by llvm::analyzeStandardArguments(), callingConvSupported(), CC_Lanai32_VarArg(), CC_MipsO32(), CC_RISCV(), CC_RISCV_FastCC(), CC_RISCVAssign2XLen(), CC_Sparc64_Full(), CC_Sparc64_Half(), CC_X86_Intr(), fixupVariableFloatArgs(), getCustomMem(), llvm::CCState::HandleByVal(), and setLocInfo().
getPending()
static CCValAssign llvm::CCValAssign::getPending (unsigned ValNo, MVT ValVT, MVT LocVT, LocInfo HTP, unsigned ExtraInfo = 0) inline static
Definition at line 127 of file CallingConvLower.h.
References getReg().
Referenced by CC_AArch64_Custom_Block(), CC_AArch64_Custom_Stack_Block(), CC_ARM_AAPCS_Custom_Aggregate(), CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), and CC_X86_32_MCUInReg().
getReg()
static CCValAssign llvm::CCValAssign::getReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP) inline static
Definition at line 79 of file CallingConvLower.h.
References llvm::MipsISD::Ret.
Referenced by AnalyzeArguments(), llvm::analyzeStandardArguments(), CC_AArch64_Custom_Block(), CC_AIX(), CC_MipsO32(), CC_RISCV(), CC_RISCV_FastCC(), CC_RISCVAssign2XLen(), CC_Sparc64_Full(), CC_Sparc64_Half(), CC_X86_32_MCUInReg(), CC_X86_32_VectorCall(), CC_X86_64_VectorCall(), CC_X86_VectorCallAssignRegister(), fixupVariableFloatArgs(), getCustomReg(), getPending(), and setLocInfo().
getValNo()
unsigned llvm::CCValAssign::getValNo () const inline
Definition at line 142 of file CallingConvLower.h.
Referenced by llvm::CCState::AnalyzeArgumentsSecondPass(), buildCallOperands(), CC_RISCVAssign2XLen(), computeBytesPoppedByCalleeForSRet(), fixupVariableFloatArgs(), getComparePred(), isSortedByValueNo(), LowerVASTART(), setLocInfo(), and truncateScalarIntegerArg().
getValVT()
MVT llvm::CCValAssign::getValVT () const inline
Definition at line 143 of file CallingConvLower.h.
Referenced by AnalyzeReturnValues(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), CC_RISCVAssign2XLen(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), convertLocVTToValVT(), convertValVTToLocVT(), EnsureStackAlignment(), fixupVariableFloatArgs(), getComparePred(), getMOVL(), getv64i1Argument(), llvm::MipsCallLowering::MipsHandler::handle(), isFunctionGlobalAddress(), isSupportedType(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerRegToMasks(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), mayTailCallThisCC(), Passv64i1ArgInRegs(), setLocInfo(), shouldGuaranteeTCO(), truncateScalarIntegerArg(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), unpackFromMemLoc(), and llvm::X86CallLowering::X86CallLowering().
isExtInLoc()
bool llvm::CCValAssign::isExtInLoc () const inline
Definition at line 156 of file CallingConvLower.h.
References AExt, SExt, and ZExt.
Referenced by convertLocVTToValVT(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerRegToMasks(), and shouldGuaranteeTCO().
isMemLoc()
bool llvm::CCValAssign::isMemLoc () const inline
Definition at line 146 of file CallingConvLower.h.
Referenced by llvm::analyzeArguments(), AnalyzeReturnValues(), buildCallOperands(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), EnsureStackAlignment(), getComparePred(), getLocMemOffset(), getMOVL(), llvm::ARCTargetLowering::getTargetNodeName(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerVASTART(), mayTailCallThisCC(), llvm::MipsCallLowering::MipsCallLowering(), setLocInfo(), truncateScalarIntegerArg(), unpackF64OnRV32DSoftABI(), and UnpackFromArgumentSlot().
isRegLoc()
bool llvm::CCValAssign::isRegLoc () const inline
Definition at line 145 of file CallingConvLower.h.
Referenced by llvm::analyzeArguments(), AnalyzeReturnValues(), buildCallOperands(), canUseSiblingCall(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), EnsureStackAlignment(), fixupVariableFloatArgs(), getComparePred(), getLocReg(), getMOVL(), llvm::ARCTargetLowering::getTargetNodeName(), getv64i1Argument(), isFunctionGlobalAddress(), isSupportedType(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::BPFTargetLowering::LowerOperation(), llvm::ARMCallLowering::lowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), MatchingStackOffset(), mayTailCallThisCC(), llvm::MipsCallLowering::MipsCallLowering(), llvm::TargetLowering::parametersInCSRMatch(), Passv64i1ArgInRegs(), llvm::CallLowering::resultsCompatible(), llvm::CCState::resultsCompatible(), truncateScalarIntegerArg(), unpackF64OnRV32DSoftABI(), and UnpackFromArgumentSlot().
isUpperBitsInLoc()
bool llvm::CCValAssign::isUpperBitsInLoc () const inline
Definition at line 160 of file CallingConvLower.h.
References AExtUpper, SExtUpper, and ZExtUpper.
needsCustom()
bool llvm::CCValAssign::needsCustom () const inline
Definition at line 148 of file CallingConvLower.h.
Referenced by llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ARMTargetLowering::CCAssignFnForReturn(), getComparePred(), getMOVL(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), lowerRegToMasks(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), MatchingStackOffset(), Passv64i1ArgInRegs(), and truncateScalarIntegerArg().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/CallingConvLower.h