LLVM: llvm::MCLOHDirective Class Reference
llvm::MCLOHDirective Class Reference
Store Linker Optimization Hint information (LOH).
#include "llvm/MC/MCLinkerOptimizationHint.h"
Public Types
using LOHArgs = SmallVectorImpl< MCSymbol * >
Public Member Functions
MCLOHDirective (MCLOHType Kind, const LOHArgs &Args)
MCLOHType getKind () const
const LOHArgs & getArgs () const
void emit (MachObjectWriter &ObjWriter, const MCAsmLayout &Layout) const
Emit this directive as: <kind, numArgs, addr1, ..., addrN>
uint64_t getEmitSize (const MachObjectWriter &ObjWriter, const MCAsmLayout &Layout) const
Get the size in bytes of this directive if emitted in ObjWriter with the given Layout.
Detailed Description
Store Linker Optimization Hint information (LOH).
Definition at line 102 of file MCLinkerOptimizationHint.h.
Member Typedef Documentation
LOHArgs
using llvm::MCLOHDirective::LOHArgs = SmallVectorImpl<MCSymbol *>
Definition at line 115 of file MCLinkerOptimizationHint.h.
Constructor & Destructor Documentation
MCLOHDirective()
llvm::MCLOHDirective::MCLOHDirective (MCLOHType Kind, const LOHArgs & Args) inline
Definition at line 117 of file MCLinkerOptimizationHint.h.
References assert(), and llvm::isValidMCLOHType().
Referenced by llvm::MCLOHContainer::addDirective().
Member Function Documentation
emit()
void MCLOHDirective::emit (MachObjectWriter & ObjWriter, const MCAsmLayout & Layout) const
Emit this directive as: <kind, numArgs, addr1, ..., addrN>
Definition at line 36 of file MCLinkerOptimizationHint.cpp.
References llvm::support::endian::Writer::OS, and llvm::MachObjectWriter::W.
Referenced by getArgs().
getArgs()
const LOHArgs& llvm::MCLOHDirective::getArgs () const inline
Definition at line 124 of file MCLinkerOptimizationHint.h.
References emit(), and getEmitSize().
getEmitSize()
uint64_t MCLOHDirective::getEmitSize (const MachObjectWriter & ObjWriter, const MCAsmLayout & Layout) const
Get the size in bytes of this directive if emitted in ObjWriter with the given Layout.
Definition at line 42 of file MCLinkerOptimizationHint.cpp.
References llvm::size().
Referenced by getArgs().
getKind()
MCLOHType llvm::MCLOHDirective::getKind () const inline
Definition at line 122 of file MCLinkerOptimizationHint.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCLinkerOptimizationHint.h
lib/MC/MCLinkerOptimizationHint.cpp