LLVM: llvm::SwitchInst::CaseHandle Class Reference
llvm::SwitchInst::CaseHandle Class Reference
#include "llvm/IR/Instructions.h"
Public Member Functions
CaseHandle (SwitchInst *SI, ptrdiff_t Index)
void setValue (ConstantInt *V)
Sets the new value for current case.
void setSuccessor (BasicBlock *S)
Sets the new successor for current case.
Public Member Functions inherited from llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >
ConstantInt * getCaseValue () const
Resolves case value for current case.
BasicBlock * getCaseSuccessor () const
Resolves successor for current case.
unsigned getCaseIndex () const
Returns number of current case.
unsigned getSuccessorIndex () const
Returns successor index for current case successor.
bool operator== (const CaseHandleImpl &RHS) const
Friends
class SwitchInst::CaseIteratorImpl< CaseHandle >
Additional Inherited Members
Protected Types inherited from llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >
using SwitchInstType = SwitchInst
Protected Member Functions inherited from llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >
CaseHandleImpl ()=default
CaseHandleImpl (SwitchInst *SI, ptrdiff_t Index)
Protected Attributes inherited from llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >
SwitchInst * SI
ptrdiff_t Index
Detailed Description
Definition at line 3225 of file Instructions.h.
Constructor & Destructor Documentation
CaseHandle()
llvm::SwitchInst::CaseHandle::CaseHandle (SwitchInst * SI, ptrdiff_t Index) inline
Definition at line 3230 of file Instructions.h.
Member Function Documentation
setSuccessor()
void llvm::SwitchInst::CaseHandle::setSuccessor (BasicBlock * S) inline
Sets the new successor for current case.
Definition at line 3240 of file Instructions.h.
References llvm::SwitchInst::setSuccessor().
Referenced by llvm::SwitchInst::addCase().
setValue()
void llvm::SwitchInst::CaseHandle::setValue (ConstantInt * V) inline
Sets the new value for current case.
Definition at line 3233 of file Instructions.h.
References assert(), and llvm::User::setOperand().
Referenced by llvm::SwitchInst::addCase().
Friends And Related Function Documentation
SwitchInst::CaseIteratorImpl< CaseHandle >
friend class SwitchInst::CaseIteratorImpl< CaseHandle > friend
Definition at line 3227 of file Instructions.h.
The documentation for this class was generated from the following file:
include/llvm/IR/Instructions.h