LLVM: llvm::orc::SimpleCompiler Class Reference
llvm::orc::SimpleCompiler Class Reference
Simple compile functor: Takes a single IR module and returns an ObjectFile.
#include "llvm/ExecutionEngine/Orc/CompileUtils.h"
Public Types
using CompileResult = std::unique_ptr< MemoryBuffer >
Public Member Functions
SimpleCompiler (TargetMachine &TM, ObjectCache *ObjCache=nullptr)
Construct a simple compile functor with the given target.
void setObjectCache (ObjectCache *NewCache)
Set an ObjectCache to query before compiling.
Expected< CompileResult > operator() (Module &M) override
Compile a Module to an ObjectFile.
Public Member Functions inherited from llvm::orc::IRCompileLayer::IRCompiler
IRCompiler (IRMaterializationUnit::ManglingOptions MO)
virtual ~IRCompiler ()
const IRMaterializationUnit::ManglingOptions & getManglingOptions () const
Additional Inherited Members
Protected Member Functions inherited from llvm::orc::IRCompileLayer::IRCompiler
IRMaterializationUnit::ManglingOptions & manglingOptions ()
Detailed Description
Simple compile functor: Takes a single IR module and returns an ObjectFile.
This compiler supports a single compilation thread and LLVMContext only. For multithreaded compilation, use ConcurrentIRCompiler below.
Definition at line 39 of file CompileUtils.h.
Member Typedef Documentation
CompileResult
using llvm::orc::SimpleCompiler::CompileResult = std::unique_ptr<MemoryBuffer>
Definition at line 41 of file CompileUtils.h.
Constructor & Destructor Documentation
SimpleCompiler()
llvm::orc::SimpleCompiler::SimpleCompiler (TargetMachine & TM, ObjectCache * ObjCache = nullptr) inline
Construct a simple compile functor with the given target.
Definition at line 44 of file CompileUtils.h.
Member Function Documentation
operator()()
Expected< SimpleCompiler::CompileResult > llvm::orc::SimpleCompiler::operator() (Module & M) override virtual
Compile a Module to an ObjectFile.
Implements llvm::orc::IRCompileLayer::IRCompiler.
Definition at line 37 of file CompileUtils.cpp.
References llvm::TargetMachine::addPassesToEmitMC(), llvm::object::ObjectFile::createObjectFile(), llvm::MemoryBuffer::getMemBufferRef(), llvm::Module::getModuleIdentifier(), llvm::ObjectCache::getObject(), llvm::inconvertibleErrorCode(), llvm::ObjectCache::notifyObjectCompiled(), and llvm::legacy::PassManager::run().
Referenced by setObjectCache(), and llvm::orc::ConcurrentIRCompiler::setObjectCache().
setObjectCache()
void llvm::orc::SimpleCompiler::setObjectCache (ObjectCache * NewCache) inline
Set an ObjectCache to query before compiling.
Definition at line 49 of file CompileUtils.h.
References operator()().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/CompileUtils.h
lib/ExecutionEngine/Orc/CompileUtils.cpp