LLVM: llvm::object::ELFSymbolRef Class Reference
llvm::object::ELFSymbolRef Class Reference
#include "llvm/Object/ELFObjectFile.h"
Public Member Functions
ELFSymbolRef (const SymbolRef &B)
const ELFObjectFileBase * getObject () const
uint64_t getSize () const
uint8_t getBinding () const
uint8_t getOther () const
uint8_t getELFType () const
StringRef getELFTypeName () const
Public Member Functions inherited from llvm::object::SymbolRef
SymbolRef ()=default
SymbolRef (DataRefImpl SymbolP, const ObjectFile *Owner)
SymbolRef (const BasicSymbolRef &B)
Expected< StringRef > getName () const
Expected< uint64_t > getAddress () const
Returns the symbol virtual address (i.e.
uint64_t getValue () const
Return the value of the symbol depending on the object this can be an offset or a virtual address.
uint32_t getAlignment () const
Get the alignment of this symbol as the actual value (not log 2).
uint64_t getCommonSize () const
Expected< SymbolRef::Type > getType () const
Expected< section_iterator > getSection () const
Get section this symbol is defined in reference to.
const ObjectFile * getObject () const
Public Member Functions inherited from llvm::object::BasicSymbolRef
BasicSymbolRef ()=default
BasicSymbolRef (DataRefImpl SymbolP, const SymbolicFile *Owner)
bool operator== (const BasicSymbolRef &Other) const
bool operator< (const BasicSymbolRef &Other) const
void moveNext ()
Error printName (raw_ostream &OS) const
uint32_t getFlags () const
Get symbol flags (bitwise OR of SymbolRef::Flags)
DataRefImpl getRawDataRefImpl () const
const SymbolicFile * getObject () const
Additional Inherited Members
Public Types inherited from llvm::object::SymbolRef
enum Type {
ST_Unknown, ST_Data, ST_Debug, ST_File,
ST_Function, ST_Other
}
Public Types inherited from llvm::object::BasicSymbolRef
enum Flags : unsigned {
SF_None = 0, SF_Undefined = 1U << 0, SF_Global = 1U << 1, SF_Weak = 1U << 2,
SF_Absolute = 1U << 3, SF_Common = 1U << 4, SF_Indirect = 1U << 5, SF_Exported = 1U << 6,
SF_FormatSpecific = 1U << 7, SF_Thumb = 1U << 8, SF_Hidden = 1U << 9, SF_Const = 1U << 10,
SF_Executable = 1U << 11
}
Detailed Description
Definition at line 136 of file ELFObjectFile.h.
Constructor & Destructor Documentation
ELFSymbolRef()
llvm::object::ELFSymbolRef::ELFSymbolRef (const SymbolRef & B) inline
Definition at line 138 of file ELFObjectFile.h.
References assert(), and llvm::object::SymbolRef::getObject().
Member Function Documentation
getBinding()
uint8_t llvm::object::ELFSymbolRef::getBinding () const inline
Definition at line 150 of file ELFObjectFile.h.
References llvm::object::getObject().
getELFType()
uint8_t llvm::object::ELFSymbolRef::getELFType () const inline
Definition at line 158 of file ELFObjectFile.h.
References llvm::object::getObject().
getELFTypeName()
StringRef llvm::object::ELFSymbolRef::getELFTypeName () const inline
Definition at line 162 of file ELFObjectFile.h.
References llvm::object::Binary::getELFType().
getObject()
const ELFObjectFileBase* llvm::object::ELFSymbolRef::getObject () const inline
Definition at line 142 of file ELFObjectFile.h.
References llvm::object::BasicSymbolRef::getObject().
getOther()
uint8_t llvm::object::ELFSymbolRef::getOther () const inline
Definition at line 154 of file ELFObjectFile.h.
References llvm::object::getObject().
getSize()
uint64_t llvm::object::ELFSymbolRef::getSize () const inline
Definition at line 146 of file ELFObjectFile.h.
References llvm::object::getObject().
The documentation for this class was generated from the following file:
include/llvm/Object/ELFObjectFile.h