LLVM: llvm::pdb::InfoStream Class Reference
llvm::pdb::InfoStream Class Reference
#include "llvm/DebugInfo/PDB/Native/InfoStream.h"
Public Member Functions
InfoStream (std::unique_ptr< BinaryStream > Stream)
Error reload ()
uint32_t getStreamSize () const
const InfoStreamHeader * getHeader () const
bool containsIdStream () const
PdbRaw_ImplVer getVersion () const
uint32_t getSignature () const
uint32_t getAge () const
codeview::GUID getGuid () const
uint32_t getNamedStreamMapByteSize () const
PdbRaw_Features getFeatures () const
ArrayRef< PdbRaw_FeatureSig > getFeatureSignatures () const
const NamedStreamMap & getNamedStreams () const
BinarySubstreamRef getNamedStreamsBuffer () const
Expected< uint32_t > getNamedStreamIndex (llvm::StringRef Name) const
StringMap< uint32_t > named_streams () const
Friends
class InfoStreamBuilder
Detailed Description
Definition at line 28 of file InfoStream.h.
Constructor & Destructor Documentation
InfoStream()
InfoStream::InfoStream (std::unique_ptr< BinaryStream > Stream)
Definition at line 22 of file InfoStream.cpp.
Member Function Documentation
containsIdStream()
bool InfoStream::containsIdStream () const
Definition at line 99 of file InfoStream.cpp.
References llvm::pdb::PdbFeatureContainsIdStream.
Referenced by getHeader(), and llvm::pdb::PDBFile::hasPDBIpiStream().
getAge()
uint32_t InfoStream::getAge () const
Definition at line 111 of file InfoStream.cpp.
References llvm::pdb::InfoStreamHeader::Age.
Referenced by getHeader().
getFeatures()
PdbRaw_Features InfoStream::getFeatures () const
Definition at line 119 of file InfoStream.cpp.
Referenced by getHeader().
getFeatureSignatures()
ArrayRef< PdbRaw_FeatureSig > InfoStream::getFeatureSignatures () const
Definition at line 121 of file InfoStream.cpp.
Referenced by getHeader().
getGuid()
GUID InfoStream::getGuid () const
Definition at line 113 of file InfoStream.cpp.
References llvm::pdb::InfoStreamHeader::Guid.
Referenced by getHeader().
getHeader()
const InfoStreamHeader* llvm::pdb::InfoStream::getHeader () const inline
Definition at line 38 of file InfoStream.h.
References containsIdStream(), getAge(), getFeatures(), getFeatureSignatures(), getGuid(), getNamedStreamIndex(), getNamedStreamMapByteSize(), getNamedStreams(), getNamedStreamsBuffer(), getSignature(), getVersion(), Name, named_streams(), and llvm::pdb::PdbFeatureNone.
getNamedStreamIndex()
Expected< uint32_t > InfoStream::getNamedStreamIndex (llvm::StringRef Name) const
Definition at line 88 of file InfoStream.cpp.
References llvm::pdb::NamedStreamMap::get(), and llvm::pdb::no_stream.
Referenced by getHeader().
getNamedStreamMapByteSize()
uint32_t InfoStream::getNamedStreamMapByteSize () const
Definition at line 115 of file InfoStream.cpp.
Referenced by getHeader().
getNamedStreams()
const NamedStreamMap & InfoStream::getNamedStreams () const
Definition at line 125 of file InfoStream.cpp.
Referenced by getHeader().
getNamedStreamsBuffer()
BinarySubstreamRef InfoStream::getNamedStreamsBuffer () const
Definition at line 129 of file InfoStream.cpp.
Referenced by getHeader().
getSignature()
uint32_t InfoStream::getSignature () const
Definition at line 107 of file InfoStream.cpp.
References llvm::pdb::InfoStreamHeader::Signature.
Referenced by getHeader().
getStreamSize()
uint32_t InfoStream::getStreamSize () const
Definition at line 86 of file InfoStream.cpp.
getVersion()
PdbRaw_ImplVer InfoStream::getVersion () const
Definition at line 103 of file InfoStream.cpp.
References llvm::pdb::InfoStreamHeader::Version.
Referenced by getHeader().
named_streams()
StringMap< uint32_t > InfoStream::named_streams () const
Definition at line 95 of file InfoStream.cpp.
References llvm::pdb::NamedStreamMap::entries().
Referenced by getHeader().
reload()
Error InfoStream::reload ()
Definition at line 25 of file InfoStream.cpp.
References llvm::pdb::corrupt_file, llvm::codeview::EC, llvm::BinaryStreamReader::getOffset(), llvm::joinErrors(), llvm::pdb::NamedStreamMap::load(), llvm::pdb::PdbImplVC110, llvm::pdb::PdbImplVC140, llvm::pdb::PdbImplVC70, llvm::pdb::PdbImplVC80, llvm::BinaryStreamReader::readObject(), llvm::BinaryStreamReader::readSubstream(), llvm::BinaryStreamReader::setOffset(), and llvm::pdb::InfoStreamHeader::Version.
Friends And Related Function Documentation
InfoStreamBuilder
friend class InfoStreamBuilder friend
Definition at line 29 of file InfoStream.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/InfoStream.h
lib/DebugInfo/PDB/Native/InfoStream.cpp