LLVM: llvm::lto::InputFile Class Reference
llvm::lto::InputFile Class Reference
An input file.
#include "llvm/LTO/LTO.h"
Classes
class Symbol
The purpose of this class is to only expose the symbol information that an LTO client should need in order to do symbol resolution.
Public Member Functions
~InputFile ()
ArrayRef< Symbol > symbols () const
A range over the symbols in this InputFile.
StringRef getCOFFLinkerOpts () const
Returns linker options specified in the input file.
ArrayRef< StringRef > getDependentLibraries () const
Returns dependent library specifiers from the input file.
StringRef getName () const
Returns the path to the InputFile.
StringRef getTargetTriple () const
Returns the input file's target triple.
StringRef getSourceFileName () const
Returns the source file path specified at compile time.
ArrayRef< StringRef > getComdatTable () const
BitcodeModule & getSingleBitcodeModule ()
Static Public Member Functions
static Expected< std::unique_ptr< InputFile > > create (MemoryBufferRef Object)
Create an InputFile.
Detailed Description
An input file.
This is a symbol table wrapper that only exposes the information that an LTO client should need in order to do symbol resolution.
Definition at line 104 of file LTO.h.
Constructor & Destructor Documentation
~InputFile()
InputFile::~InputFile () default
Referenced by llvm::thinLTOInternalizeAndPromoteInIndex().
Member Function Documentation
create()
Expected< std::unique_ptr< InputFile > > InputFile::create (MemoryBufferRef Object) static
Create an InputFile.
Definition at line 431 of file LTO.cpp.
References File, I, llvm::object::readIRSymtab(), and llvm::Expected< T >::takeError().
Referenced by llvm::ThinLTOCodeGenerator::addModule(), and llvm::LTOModule::createInputFile().
getCOFFLinkerOpts()
StringRef llvm::lto::InputFile::getCOFFLinkerOpts () const inline
Returns linker options specified in the input file.
Definition at line 160 of file LTO.h.
getComdatTable()
ArrayRef<StringRef> llvm::lto::InputFile::getComdatTable () const inline
Definition at line 175 of file LTO.h.
References llvm::ArrayRef< T >::data(), getSingleBitcodeModule(), and I.
getDependentLibraries()
ArrayRef<StringRef> llvm::lto::InputFile::getDependentLibraries () const inline
Returns dependent library specifiers from the input file.
Definition at line 163 of file LTO.h.
References llvm::irsymtab::Symbol::getName().
Referenced by llvm::LTOModule::getDependentLibrary(), and llvm::LTOModule::getDependentLibraryCount().
getName()
StringRef InputFile::getName () const
Returns the path to the InputFile.
Definition at line 460 of file LTO.cpp.
Referenced by writeToResolutionFile().
getSingleBitcodeModule()
BitcodeModule & InputFile::getSingleBitcodeModule ()
Definition at line 464 of file LTO.cpp.
References assert(), llvm::lto::createInProcessThinBackend(), and llvm::heavyweight_hardware_concurrency().
Referenced by getComdatTable().
getSourceFileName()
StringRef llvm::lto::InputFile::getSourceFileName () const inline
Returns the source file path specified at compile time.
Definition at line 172 of file LTO.h.
getTargetTriple()
StringRef llvm::lto::InputFile::getTargetTriple () const inline
Returns the input file's target triple.
Definition at line 169 of file LTO.h.
symbols()
ArrayRef<Symbol> llvm::lto::InputFile::symbols () const inline
A range over the symbols in this InputFile.
Definition at line 157 of file LTO.h.
Referenced by writeToResolutionFile().
The documentation for this class was generated from the following files:
include/llvm/LTO/LTO.h
lib/LTO/LTO.cpp