LLVM: llvm::CGSCCToFunctionPassAdaptor< FunctionPassT > Class Template Reference
llvm::CGSCCToFunctionPassAdaptor< FunctionPassT > Class Template Reference
Adaptor that maps from a SCC to its functions.
#include "llvm/Analysis/CGSCCPassManager.h"
Public Member Functions
CGSCCToFunctionPassAdaptor (FunctionPassT Pass)
CGSCCToFunctionPassAdaptor (const CGSCCToFunctionPassAdaptor &Arg)
CGSCCToFunctionPassAdaptor (CGSCCToFunctionPassAdaptor &&Arg)
CGSCCToFunctionPassAdaptor & operator= (CGSCCToFunctionPassAdaptor RHS)
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Runs the function pass across every function in the module.
Friends
void swap (CGSCCToFunctionPassAdaptor &LHS, CGSCCToFunctionPassAdaptor &RHS)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< CGSCCToFunctionPassAdaptor< FunctionPassT > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
template<typename FunctionPassT>
class llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >
Adaptor that maps from a SCC to its functions.
Designed to allow composition of a FunctionPass(Manager) and a CGSCCPassManager. Note that if this pass is constructed with a pointer to a CGSCCAnalysisManager it will run the FunctionAnalysisManagerCGSCCProxy analysis prior to running the function pass over the SCC to enable a FunctionAnalysisManager to be used within this run safely.
Definition at line 430 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
CGSCCToFunctionPassAdaptor() [1/3]
template<typename FunctionPassT > llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::CGSCCToFunctionPassAdaptor (FunctionPassT Pass) inline explicit
Definition at line 433 of file CGSCCPassManager.h.
CGSCCToFunctionPassAdaptor() [2/3]
template<typename FunctionPassT > llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::CGSCCToFunctionPassAdaptor (const CGSCCToFunctionPassAdaptor< FunctionPassT > & Arg) inline
Definition at line 438 of file CGSCCPassManager.h.
CGSCCToFunctionPassAdaptor() [3/3]
template<typename FunctionPassT > llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::CGSCCToFunctionPassAdaptor (CGSCCToFunctionPassAdaptor< FunctionPassT > && Arg) inline
Definition at line 441 of file CGSCCPassManager.h.
Member Function Documentation
operator=()
template<typename FunctionPassT > CGSCCToFunctionPassAdaptor& llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::operator= (CGSCCToFunctionPassAdaptor< FunctionPassT > RHS) inline
Definition at line 449 of file CGSCCPassManager.h.
References std::swap().
run()
template<typename FunctionPassT > PreservedAnalyses llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR) inline
Runs the function pass across every function in the module.
Definition at line 455 of file CGSCCPassManager.h.
References llvm::PreservedAnalyses::all(), assert(), C, llvm::dbgs(), F(), llvm::PreservedAnalyses::getChecker(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs >::Result::getManager(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), LLVM_DEBUG, llvm::LazyCallGraph::lookupSCC(), N, Pass, llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runBeforePass(), and llvm::updateCGAndAnalysisManagerForFunctionPass().
Friends And Related Function Documentation
swap
template<typename FunctionPassT > void swap (CGSCCToFunctionPassAdaptor< FunctionPassT > & LHS, CGSCCToFunctionPassAdaptor< FunctionPassT > & RHS) friend
Definition at line 444 of file CGSCCPassManager.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/CGSCCPassManager.h