LLVM: llvm::PPCInstrInfo Class Reference
llvm::PPCInstrInfo Class Reference
#include "Target/PowerPC/PPCInstrInfo.h"
Public Member Functions
PPCInstrInfo (PPCSubtarget &STI)
const PPCRegisterInfo & getRegisterInfo () const
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
bool isXFormMemOp (unsigned Opcode) const
ScheduleHazardRecognizer * CreateTargetHazardRecognizer (const TargetSubtargetInfo *STI, const ScheduleDAG *DAG) const override
CreateTargetHazardRecognizer - Return the hazard recognizer to use for this target when scheduling the DAG.
ScheduleHazardRecognizer * CreateTargetPostRAHazardRecognizer (const InstrItineraryData *II, const ScheduleDAG *DAG) const override
CreateTargetPostRAHazardRecognizer - Return the postRA hazard recognizer to use for this target when scheduling the DAG.
unsigned getInstrLatency (const InstrItineraryData *ItinData, const MachineInstr &MI, unsigned *PredCost=nullptr) const override
int getOperandLatency (const InstrItineraryData *ItinData, const MachineInstr &DefMI, unsigned DefIdx, const MachineInstr &UseMI, unsigned UseIdx) const override
int getOperandLatency (const InstrItineraryData *ItinData, SDNode *DefNode, unsigned DefIdx, SDNode *UseNode, unsigned UseIdx) const override
bool hasLowDefLatency (const TargetSchedModel &SchedModel, const MachineInstr &DefMI, unsigned DefIdx) const override
bool useMachineCombiner () const override
bool getMachineCombinerPatterns (MachineInstr &Root, SmallVectorImpl< MachineCombinerPattern > &P) const override
Return true when there is potentially a faster code sequence for an instruction chain ending in <Root>.
bool isAssociativeAndCommutative (const MachineInstr &Inst) const override
bool isCoalescableExtInstr (const MachineInstr &MI, unsigned &SrcReg, unsigned &DstReg, unsigned &SubIdx) const override
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
bool isReallyTriviallyReMaterializable (const MachineInstr &MI, AAResults *AA) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
bool findCommutedOpIndices (const MachineInstr &MI, unsigned &SrcOpIdx1, unsigned &SrcOpIdx2) const override
void insertNoop (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
bool canInsertSelect (const MachineBasicBlock &, ArrayRef< MachineOperand > Cond, unsigned, unsigned, int &, int &, int &) const override
void insertSelect (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, unsigned DstReg, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
unsigned getStoreOpcodeForSpill (unsigned Reg, const TargetRegisterClass *RC=nullptr) const
unsigned getLoadOpcodeForSpill (unsigned Reg, const TargetRegisterClass *RC=nullptr) const
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
bool FoldImmediate (MachineInstr &UseMI, MachineInstr &DefMI, unsigned Reg, MachineRegisterInfo *MRI) const override
bool isProfitableToIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, unsigned ExtraPredCycles, BranchProbability Probability) const override
bool isProfitableToIfCvt (MachineBasicBlock &TMBB, unsigned NumT, unsigned ExtraT, MachineBasicBlock &FMBB, unsigned NumF, unsigned ExtraF, BranchProbability Probability) const override
bool isProfitableToDupForIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, BranchProbability Probability) const override
bool isProfitableToUnpredicate (MachineBasicBlock &TMBB, MachineBasicBlock &FMBB) const override
bool isPredicated (const MachineInstr &MI) const override
bool isUnpredicatedTerminator (const MachineInstr &MI) const override
bool PredicateInstruction (MachineInstr &MI, ArrayRef< MachineOperand > Pred) const override
bool SubsumesPredicate (ArrayRef< MachineOperand > Pred1, ArrayRef< MachineOperand > Pred2) const override
bool DefinesPredicate (MachineInstr &MI, std::vector< MachineOperand > &Pred) const override
bool analyzeCompare (const MachineInstr &MI, unsigned &SrcReg, unsigned &SrcReg2, int &Mask, int &Value) const override
bool optimizeCompareInstr (MachineInstr &CmpInstr, unsigned SrcReg, unsigned SrcReg2, int Mask, int Value, const MachineRegisterInfo *MRI) const override
bool getMemOperandWithOffsetWidth (const MachineInstr &LdSt, const MachineOperand *&BaseOp, int64_t &Offset, unsigned &Width, const TargetRegisterInfo *TRI) const
Return true if get the base operand, byte offset of an instruction and the memory width.
bool areMemAccessesTriviallyDisjoint (const MachineInstr &MIa, const MachineInstr &MIb) const override
Return true if two MIs access different memory addresses and false otherwise.
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
void getNoop (MCInst &NopInst) const override
Return the noop instruction to use for a noop.
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableBitmaskMachineOperandTargetFlags () const override
bool expandVSXMemPseudo (MachineInstr &MI) const
bool expandPostRAPseudo (MachineInstr &MI) const override
const TargetRegisterClass * updatedRC (const TargetRegisterClass *RC) const
bool isTOCSaveMI (const MachineInstr &MI) const
bool isSignOrZeroExtended (const MachineInstr &MI, bool SignExt, const unsigned PhiDepth) const
bool isSignExtended (const MachineInstr &MI, const unsigned depth=0) const
Return true if the output of the instruction is always a sign-extended, i.e.
bool isZeroExtended (const MachineInstr &MI, const unsigned depth=0) const
Return true if the output of the instruction is always zero-extended, i.e.
bool convertToImmediateForm (MachineInstr &MI, MachineInstr **KilledDef=nullptr) const
bool foldFrameOffset (MachineInstr &MI) const
bool isADDIInstrEligibleForFolding (MachineInstr &ADDIMI, int64_t &Imm) const
bool isADDInstrEligibleForFolding (MachineInstr &ADDMI) const
bool isImmInstrEligibleForFolding (MachineInstr &MI, unsigned &BaseReg, unsigned &XFormOpcode, int64_t &OffsetOfImmInstr, ImmInstrInfo &III) const
bool isValidToBeChangedReg (MachineInstr *ADDMI, unsigned Index, MachineInstr *&ADDIMI, int64_t &OffsetAddi, int64_t OffsetImm) const
void fixupIsDeadOrKill (MachineInstr &StartMI, MachineInstr &EndMI, unsigned RegNo) const
Fixup killed/dead flag for register RegNo between instructions [StartMI, EndMI].
void replaceInstrWithLI (MachineInstr &MI, const LoadImmediateInfo &LII) const
void replaceInstrOperandWithImm (MachineInstr &MI, unsigned OpNo, int64_t Imm) const
bool instrHasImmForm (unsigned Opc, bool IsVFReg, ImmInstrInfo &III, bool PostRA) const
MachineInstr * getDefMIPostRA (unsigned Reg, MachineInstr &MI, bool &SeenIntermediateUse) const
bool isBDNZ (unsigned Opcode) const
Check Opcode is BDNZ (Decrement CTR and branch if it is still nonzero).
MachineInstr * findLoopInstr (MachineBasicBlock &PreHeader, SmallPtrSet< MachineBasicBlock *, 8 > &Visited) const
Find the hardware loop instruction used to set-up the specified loop.
std::unique_ptr< TargetInstrInfo::PipelinerLoopInfo > analyzeLoopForPipelining (MachineBasicBlock *LoopBB) const override
Analyze loop L, which must be a single-basic-block loop, and if the conditions can be understood enough produce a PipelinerLoopInfo object.
Static Public Member Functions
static bool isSameClassPhysRegCopy (unsigned Opcode)
static bool isVFRegister (unsigned Reg)
static bool isVRRegister (unsigned Reg)
static int getRecordFormOpcode (unsigned Opcode)
static unsigned getRegNumForOperand (const MCInstrDesc &Desc, unsigned Reg, unsigned OpNo)
getRegNumForOperand - some operands use different numbering schemes for the same registers.
Protected Member Functions
MachineInstr * commuteInstructionImpl (MachineInstr &MI, bool NewMI, unsigned OpIdx1, unsigned OpIdx2) const override
Commutes the operands in the given instruction.
Detailed Description
Definition at line 112 of file PPCInstrInfo.h.
Constructor & Destructor Documentation
PPCInstrInfo()
PPCInstrInfo::PPCInstrInfo (PPCSubtarget & STI) explicit
Definition at line 99 of file PPCInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool PPCInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 495 of file PPCInstrInfo.cpp.
analyzeCompare()
bool PPCInstrInfo::analyzeCompare (const MachineInstr & MI, unsigned & SrcReg, unsigned & SrcReg2, int & Mask, int & Value) const override
Definition at line 1590 of file PPCInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
analyzeLoopForPipelining()
std::unique_ptr< TargetInstrInfo::PipelinerLoopInfo > PPCInstrInfo::analyzeLoopForPipelining (MachineBasicBlock * LoopBB) const override
Analyze loop L, which must be a single-basic-block loop, and if the conditions can be understood enough produce a PipelinerLoopInfo object.
Definition at line 4224 of file PPCInstrInfo.cpp.
References llvm::MachineBasicBlock::end(), findLoopInstr(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineBasicBlock::getParent(), llvm::MachineRegisterInfo::getUniqueVRegDef(), I, isBDNZ(), MRI, and llvm::MachineBasicBlock::pred_begin().
areMemAccessesTriviallyDisjoint()
bool PPCInstrInfo::areMemAccessesTriviallyDisjoint (const MachineInstr & MIa, const MachineInstr & MIb) const override
Return true if two MIs access different memory addresses and false otherwise.
Definition at line 4280 of file PPCInstrInfo.cpp.
References assert(), getMemOperandWithOffsetWidth(), getRegisterInfo(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineOperand::isIdenticalTo(), llvm::max(), llvm::MachineInstr::mayLoadOrStore(), and TRI.
canInsertSelect()
bool PPCInstrInfo::canInsertSelect (const MachineBasicBlock & MBB, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg, int & CondCycles, int & TrueCycles, int & FalseCycles) const override
Definition at line 755 of file PPCInstrInfo.cpp.
commuteInstructionImpl()
MachineInstr * PPCInstrInfo::commuteInstructionImpl (MachineInstr & MI, bool NewMI, unsigned OpIdx1, unsigned OpIdx2) const override protected
Commutes the operands in the given instruction.
The commutable operands are specified by their indices OpIdx1 and OpIdx2.
Do not call this method for a non-commutable instruction or for non-commutable pair of operand indices OpIdx1 and OpIdx2. Even though the instruction is commutable, the method may still fail to commute the operands, null pointer is returned in such cases.
For example, we can commute rlwimi instructions, but only if the rotate amt is zero. We also have to munge the immediates a bit.
Definition at line 368 of file PPCInstrInfo.cpp.
References assert(), llvm::BuildMI(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::RegState::Define, llvm::getDeadRegState(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::getKillRegState(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isKill(), MI, llvm::MachineOperand::setImm(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setReg(), llvm::MachineOperand::setSubReg(), and llvm::MCOI::TIED_TO.
convertToImmediateForm()
bool PPCInstrInfo::convertToImmediateForm (MachineInstr & MI, MachineInstr ** KilledDef = nullptr) const
Definition at line 2734 of file PPCInstrInfo.cpp.
References assert(), llvm::dbgs(), DefMI, llvm::MachineInstr::dump(), fixupIsDeadOrKill(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::APInt::getSExtValue(), llvm::MachineRegisterInfo::hasOneUse(), llvm::LoadImmediateInfo::Imm, instrHasImmForm(), llvm::MachineOperand::isImm(), llvm::isInt< 16 >(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineRegisterInfo::isSSA(), llvm::isUInt< 16 >(), isVFRegister(), LLVM_DEBUG, llvm::BitmaskEnumDetail::Mask(), MRI, replaceInstrOperandWithImm(), replaceInstrWithLI(), llvm::APInt::rotl(), selectReg(), llvm::MachineOperand::setImm(), llvm::MachineRegisterInfo::use_empty(), and llvm::MachineRegisterInfo::use_instructions().
copyPhysReg()
void PPCInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 904 of file PPCInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), getCRBitValue(), llvm::getCRFromCRBit(), llvm::MCRegisterInfo::getEncodingValue(), llvm::getKillRegState(), llvm::TargetRegisterInfo::getMatchingSuperReg(), llvm::MCInstrDesc::getNumOperands(), getRegisterInfo(), llvm::PPCSubtarget::hasDirectMove(), llvm::PPCSubtarget::hasP9Vector(), llvm::RegState::Kill, llvm_unreachable, llvm::PPCISD::MFOCRF, llvm::ISD::OR, TRI, and VSXSelfCopyCrash.
CreateTargetHazardRecognizer()
ScheduleHazardRecognizer * PPCInstrInfo::CreateTargetHazardRecognizer (const TargetSubtargetInfo * STI, const ScheduleDAG * DAG) const override
CreateTargetHazardRecognizer - Return the hazard recognizer to use for this target when scheduling the DAG.
Definition at line 108 of file PPCInstrInfo.cpp.
References llvm::TargetInstrInfo::CreateTargetHazardRecognizer(), llvm::PPC::DIR_440, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500mc, and llvm::PPC::DIR_E5500.
CreateTargetPostRAHazardRecognizer()
ScheduleHazardRecognizer * PPCInstrInfo::CreateTargetPostRAHazardRecognizer (const InstrItineraryData * II, const ScheduleDAG * DAG) const override
CreateTargetPostRAHazardRecognizer - Return the postRA hazard recognizer to use for this target when scheduling the DAG.
Definition at line 125 of file PPCInstrInfo.cpp.
References assert(), llvm::PPC::DIR_440, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500mc, llvm::PPC::DIR_E5500, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::MachineFunction::getSubtarget(), llvm::ScheduleDAG::MF, and llvm::ScheduleDAG::TII.
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > PPCInstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 2013 of file PPCInstrInfo.cpp.
References llvm::BitmaskEnumDetail::Mask(), and llvm::PPCII::MO_ACCESS_MASK.
DefinesPredicate()
bool PPCInstrInfo::DefinesPredicate (MachineInstr & MI, std::vector< MachineOperand > & Pred) const override
Definition at line 1554 of file PPCInstrInfo.cpp.
References llvm::array_lengthof(), llvm::TargetRegisterClass::begin(), llvm::MachineOperand::clobbersPhysReg(), llvm::TargetRegisterClass::contains(), llvm::numbers::e, llvm::TargetRegisterClass::end(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, llvm::ARM_PROC::IE, llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isRegMask().
expandPostRAPseudo()
bool PPCInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 2116 of file PPCInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), expandVSXMemPseudo(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), isAnImmediateOperand(), llvm::MachineOperand::isReg(), llvm::ARM_MB::LD, MI, llvm::PPC::PRED_NE_MINUS, R2, Reg, llvm::MachineInstr::RemoveOperand(), and llvm::MachineInstr::setDesc().
expandVSXMemPseudo()
bool PPCInstrInfo::expandVSXMemPseudo (MachineInstr & MI) const
Definition at line 2050 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::PPCISD::LFIWAX, llvm::PPCISD::LFIWZX, llvm_unreachable, llvm::MachineInstr::setDesc(), and llvm::PPCISD::STFIWX.
Referenced by expandPostRAPseudo().
findCommutedOpIndices()
bool PPCInstrInfo::findCommutedOpIndices (const MachineInstr & MI, unsigned & SrcOpIdx1, unsigned & SrcOpIdx2) const override
Definition at line 452 of file PPCInstrInfo.cpp.
References llvm::TargetInstrInfo::findCommutedOpIndices(), llvm::PPC::getAltVSXFMAOpcode(), and llvm::MachineInstr::getOpcode().
findLoopInstr()
MachineInstr * PPCInstrInfo::findLoopInstr (MachineBasicBlock & PreHeader, SmallPtrSet< MachineBasicBlock *, 8 > & Visited) const
Find the hardware loop instruction used to set-up the specified loop.
On PPC, we have two instructions used to set-up the hardware loop (MTCTRloop, MTCTR8loop) with corresponding endloop (BDNZ, BDNZ8) instructions to indicate the end of a loop.
Definition at line 4244 of file PPCInstrInfo.cpp.
References I, and llvm::MachineBasicBlock::instrs().
Referenced by analyzeLoopForPipelining().
fixupIsDeadOrKill()
void PPCInstrInfo::fixupIsDeadOrKill (MachineInstr & StartMI, MachineInstr & EndMI, unsigned RegNo) const
Fixup killed/dead flag for register RegNo between instructions [StartMI, EndMI].
Some PostRA transformations may violate register killed/dead flags semantics, this function can be called to fix up. Before calling this function,
Ensure that RegNo liveness is killed after instruction EndMI.
Ensure that there is no new definition between (StartMI, EndMI) and possible definition for RegNo is StartMI or EndMI.
Ensure that all instructions between [StartMI, EndMI] are in same basic block.
Definition at line 2435 of file PPCInstrInfo.cpp.
References assert(), llvm::numbers::e, E, llvm::MachineInstr::findRegisterUseOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineRegisterInfo::isSSA(), llvm::MachineOperand::isUse(), MI, MRI, llvm::MachineBasicBlock::rend(), llvm::MachineOperand::setIsDead(), and llvm::MachineOperand::setIsKill().
Referenced by convertToImmediateForm(), and swapMIOperands().
foldFrameOffset()
bool PPCInstrInfo::foldFrameOffset (MachineInstr & MI) const
Definition at line 2536 of file PPCInstrInfo.cpp.
References assert(), getDefMIPostRA(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), isADDInstrEligibleForFolding(), isImmInstrEligibleForFolding(), llvm::MachineRegisterInfo::isSSA(), isValidToBeChangedReg(), MRI, and Reg.
FoldImmediate()
bool PPCInstrInfo::FoldImmediate (MachineInstr & UseMI, MachineInstr & DefMI, unsigned Reg, MachineRegisterInfo * MRI) const override
Definition at line 1324 of file PPCInstrInfo.cpp.
References assert(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MachineOperand::isImm(), llvm::PPCSubtarget::isPPC64(), llvm::MCInstrDesc::isPseudo(), llvm::MachineOperand::isReg(), llvm::MCInstrDesc::OpInfo, Reg, and llvm::MachineOperand::setReg().
getDefMIPostRA()
MachineInstr * PPCInstrInfo::getDefMIPostRA (unsigned Reg, MachineInstr & MI, bool & SeenIntermediateUse) const
Definition at line 2307 of file PPCInstrInfo.cpp.
References assert(), DefMI, llvm::numbers::e, E, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::MachineRegisterInfo::getVRegDef(), instrHasImmForm(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::MachineRegisterInfo::isSSA(), llvm::MachineOperand::isUse(), isVFRegister(), llvm::Register::isVirtualRegister(), llvm::ARM_MB::LD, llvm::TargetRegisterInfo::lookThruCopyLike(), llvm::PPCISD::LXVD2X, MI, MRI, llvm::ISD::OR, Reg, llvm::MachineBasicBlock::rend(), SOK_LastOpcodeSpill, llvm::PPCISD::STXVD2X, and TRI.
Referenced by foldFrameOffset(), and isValidToBeChangedReg().
getInstrLatency()
unsigned PPCInstrInfo::getInstrLatency (const InstrItineraryData * ItinData, const MachineInstr & MI, unsigned * PredCost = nullptr) const override
Definition at line 145 of file PPCInstrInfo.cpp.
References llvm::numbers::e, llvm::MachineInstr::getDesc(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::InstrItineraryData::getOperandCycle(), llvm::MCInstrDesc::getSchedClass(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::Latency, llvm::max(), and UseOldLatencyCalc.
Referenced by getOperandLatency().
getInstSizeInBytes()
unsigned PPCInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
This returns the maximum number of bytes.
Definition at line 1994 of file PPCInstrInfo.cpp.
References llvm::TargetMachine::getMCAsmInfo(), llvm::StackMapOpers::getNumPatchBytes(), llvm::PatchPointOpers::getNumPatchBytes(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), llvm::ISD::INLINEASM, and llvm::ISD::INLINEASM_BR.
Referenced by GetInitialOffset(), and llvm::PPCTargetLowering::getPrefLoopAlignment().
getLoadOpcodeForSpill()
unsigned PPCInstrInfo::getLoadOpcodeForSpill (unsigned Reg, const TargetRegisterClass * RC = nullptr) const
Definition at line 1114 of file PPCInstrInfo.cpp.
References llvm::addFrameReference(), llvm::BuildMI(), contains(), llvm::MachineFunction::getInfo(), llvm::getKillRegState(), getStoreOpcodeForSpill(), isXFormMemOp(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::PPCFunctionInfo::setHasNonRISpills(), llvm::PPCFunctionInfo::setHasSpills(), llvm::PPCFunctionInfo::setSpillsCR(), llvm::PPCFunctionInfo::setSpillsVRSAVE(), SOK_CRBitSpill, SOK_CRSpill, SOK_Float4Spill, SOK_Float8Spill, SOK_Int4Spill, SOK_Int8Spill, SOK_QuadBitSpill, SOK_QuadFloat4Spill, SOK_QuadFloat8Spill, SOK_SPESpill, SOK_SpillToVSR, SOK_VectorFloat4Spill, SOK_VectorFloat8Spill, SOK_VRSaveSpill, SOK_VRVectorSpill, and SOK_VSXVectorSpill.
Referenced by storeRegToStackSlot().
getMachineCombinerPatterns()
bool PPCInstrInfo::getMachineCombinerPatterns (MachineInstr & Root, SmallVectorImpl< MachineCombinerPattern > & P) const override
Return true when there is potentially a faster code sequence for an instruction chain ending in <Root>.
All potential patterns are output in the <Pattern> array.
Definition at line 267 of file PPCInstrInfo.cpp.
References llvm::CodeGenOpt::Aggressive, llvm::TargetInstrInfo::getMachineCombinerPatterns(), llvm::TargetMachine::getOptLevel(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getTarget(), llvm::PPCSubtarget::getTargetMachine(), llvm::TargetMachine::Options, and llvm::TargetOptions::UnsafeFPMath.
getMemOperandWithOffsetWidth()
bool PPCInstrInfo::getMemOperandWithOffsetWidth (const MachineInstr & LdSt, const MachineOperand *& BaseOp, int64_t & Offset, unsigned & Width, const TargetRegisterInfo * TRI) const
Return true if get the base operand, byte offset of an instruction and the memory width.
Width is the size of memory that is being loaded/stored (e.g. 1, 2, 4, 8).
Definition at line 4259 of file PPCInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::hasOneMemOperand(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoadOrStore(), and llvm::MachineInstr::memoperands_begin().
Referenced by areMemAccessesTriviallyDisjoint().
getNoop()
void PPCInstrInfo::getNoop (MCInst & NopInst) const override
Return the noop instruction to use for a noop.
Definition at line 488 of file PPCInstrInfo.cpp.
References llvm::MCInst::setOpcode().
getOperandLatency() [1/2]
int PPCInstrInfo::getOperandLatency (const InstrItineraryData * ItinData, const MachineInstr & DefMI, unsigned DefIdx, const MachineInstr & UseMI, unsigned UseIdx) const override
Definition at line 175 of file PPCInstrInfo.cpp.
References llvm::PPC::DIR_7400, llvm::PPC::DIR_750, llvm::PPC::DIR_970, llvm::PPC::DIR_E5500, llvm::PPC::DIR_PWR4, llvm::PPC::DIR_PWR5, llvm::PPC::DIR_PWR5X, llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR6X, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::PPCSubtarget::getCPUDirective(), getInstrLatency(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::hasSuperClassEq(), llvm::MachineInstr::isBranch(), llvm::Register::isVirtualRegister(), llvm::Latency, MRI, and Reg.
getOperandLatency() [2/2]
int llvm::PPCInstrInfo::getOperandLatency (const InstrItineraryData * ItinData, SDNode * DefNode, unsigned DefIdx, SDNode * UseNode, unsigned UseIdx) const inline override
Definition at line 216 of file PPCInstrInfo.h.
getRecordFormOpcode()
int PPCInstrInfo::getRecordFormOpcode (unsigned Opcode) static
Definition at line 3870 of file PPCInstrInfo.cpp.
Referenced by selectI64Imm().
getRegisterInfo()
const PPCRegisterInfo& llvm::PPCInstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 185 of file PPCInstrInfo.h.
Referenced by areMemAccessesTriviallyDisjoint(), copyPhysReg(), fixupIsDeadOrKill(), getDefMIPostRA(), optimizeCompareInstr(), replaceInstrOperandWithImm(), and swapMIOperands().
getRegNumForOperand()
static unsigned llvm::PPCInstrInfo::getRegNumForOperand (const MCInstrDesc & Desc, unsigned Reg, unsigned OpNo) inline static
getRegNumForOperand - some operands use different numbering schemes for the same registers.
For example, a VSX instruction may have any of vs0-vs63 allocated whereas an Altivec instruction could only have vs32-vs63 allocated (numbered as v0-v31). This function returns the actual register number needed for the opcode/operand number combination. The operand number argument will be useful when we need to extend this to instructions that use both Altivec and VSX numbering (for different operands).
Definition at line 465 of file PPCInstrInfo.h.
References llvm::MCInstrDesc::OpInfo, Reg, and llvm::MCOperandInfo::RegClass.
Referenced by llvm::PPCMCCodeEmitter::getMachineOpValue(), and llvm::PPCInstPrinter::printOperand().
getSerializableBitmaskMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > PPCInstrInfo::getSerializableBitmaskMachineOperandTargetFlags () const override
Definition at line 2034 of file PPCInstrInfo.cpp.
References llvm::makeArrayRef(), llvm::PPCII::MO_NLP_FLAG, llvm::PPCII::MO_NLP_HIDDEN_FLAG, llvm::PPCII::MO_PIC_FLAG, and llvm::PPCII::MO_PLT.
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > PPCInstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 2019 of file PPCInstrInfo.cpp.
References llvm::makeArrayRef(), llvm::MipsII::MO_DTPREL_LO, llvm::PPCII::MO_HA, llvm::AVRII::MO_LO, llvm::AArch64II::MO_TLS, llvm::PPCII::MO_TLSLD_LO, llvm::PPCII::MO_TOC_LO, llvm::PPCII::MO_TPREL_HA, and llvm::MipsII::MO_TPREL_LO.
getStoreOpcodeForSpill()
unsigned PPCInstrInfo::getStoreOpcodeForSpill (unsigned Reg, const TargetRegisterClass * RC = nullptr) const
Definition at line 1027 of file PPCInstrInfo.cpp.
References contains(), llvm_unreachable, SOK_CRBitSpill, SOK_CRSpill, SOK_Float4Spill, SOK_Float8Spill, SOK_Int4Spill, SOK_Int8Spill, SOK_QuadBitSpill, SOK_QuadFloat4Spill, SOK_QuadFloat8Spill, SOK_SPESpill, SOK_SpillToVSR, SOK_VectorFloat4Spill, SOK_VectorFloat8Spill, SOK_VRSaveSpill, SOK_VRVectorSpill, and SOK_VSXVectorSpill.
Referenced by getLoadOpcodeForSpill().
hasLowDefLatency()
bool llvm::PPCInstrInfo::hasLowDefLatency (const TargetSchedModel & SchedModel, const MachineInstr & DefMI, unsigned DefIdx) const inline override
Definition at line 223 of file PPCInstrInfo.h.
insertBranch()
unsigned PPCInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 702 of file PPCInstrInfo.cpp.
insertNoop()
void PPCInstrInfo::insertNoop (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override
Definition at line 468 of file PPCInstrInfo.cpp.
References llvm::BuildMI(), llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::PPC::DIR_PWR9, and llvm::PPCSubtarget::getCPUDirective().
insertSelect()
void PPCInstrInfo::insertSelect (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, unsigned DstReg, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg) const override
Definition at line 792 of file PPCInstrInfo.cpp.
instrHasImmForm()
bool PPCInstrInfo::instrHasImmForm (unsigned Opc, bool IsVFReg, ImmInstrInfo & III, bool PostRA) const
Definition at line 2991 of file PPCInstrInfo.cpp.
References llvm::ISD::ADDC, llvm::ImmInstrInfo::ImmMustBeMultipleOf, llvm::ImmInstrInfo::ImmOpcode, llvm::ImmInstrInfo::ImmOpNo, llvm::ImmInstrInfo::ImmWidth, llvm::ImmInstrInfo::IsCommutative, llvm::ImmInstrInfo::IsSummingOperands, llvm::ARM_MB::LD, LLVM_FALLTHROUGH, llvm_unreachable, llvm::ImmInstrInfo::OpNoForForwarding, llvm::ISD::OR, llvm::ImmInstrInfo::SignedImm, llvm::RISCVISD::SRAW, llvm::ImmInstrInfo::TruncateImmTo, llvm::ISD::XOR, llvm::ImmInstrInfo::ZeroIsSpecialNew, and llvm::ImmInstrInfo::ZeroIsSpecialOrig.
Referenced by convertToImmediateForm(), getDefMIPostRA(), and isImmInstrEligibleForFolding().
isADDIInstrEligibleForFolding()
bool PPCInstrInfo::isADDIInstrEligibleForFolding (MachineInstr & ADDIMI, int64_t & Imm) const
Definition at line 2626 of file PPCInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::getOperand().
Referenced by isValidToBeChangedReg().
isADDInstrEligibleForFolding()
bool PPCInstrInfo::isADDInstrEligibleForFolding (MachineInstr & ADDMI) const
Definition at line 2639 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::getOpcode().
Referenced by foldFrameOffset().
isAssociativeAndCommutative()
bool PPCInstrInfo::isAssociativeAndCommutative (const MachineInstr & Inst) const override
Definition at line 233 of file PPCInstrInfo.cpp.
References llvm::ISD::FADD, llvm::X86ISD::FADDS, llvm::ISD::FMUL, llvm::X86ISD::FMULS, and llvm::MachineInstr::getOpcode().
isBDNZ()
bool PPCInstrInfo::isBDNZ (unsigned Opcode) const
Check Opcode is BDNZ (Decrement CTR and branch if it is still nonzero).
Definition at line 4150 of file PPCInstrInfo.cpp.
References llvm::PPCISD::BDNZ, llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getSubtarget(), and TII.
Referenced by analyzeLoopForPipelining().
isCoalescableExtInstr()
bool PPCInstrInfo::isCoalescableExtInstr (const MachineInstr & MI, unsigned & SrcReg, unsigned & DstReg, unsigned & SubIdx) const override
Definition at line 283 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
isImmInstrEligibleForFolding()
bool PPCInstrInfo::isImmInstrEligibleForFolding (MachineInstr & MI, unsigned & BaseReg, unsigned & XFormOpcode, int64_t & OffsetOfImmInstr, ImmInstrInfo & III) const
Definition at line 2646 of file PPCInstrInfo.cpp.
References assert(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ImmInstrInfo::ImmOpNo, instrHasImmForm(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::ImmInstrInfo::IsSummingOperands, isVFRegister(), llvm::MachineInstr::mayLoadOrStore(), and llvm::ImmInstrInfo::OpNoForForwarding.
Referenced by foldFrameOffset().
isLoadFromStackSlot()
unsigned PPCInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 298 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::getOpcode().
isPredicated()
bool PPCInstrInfo::isPredicated (const MachineInstr & MI) const override
Definition at line 1415 of file PPCInstrInfo.cpp.
Referenced by isUnpredicatedTerminator().
isProfitableToDupForIfCvt()
bool llvm::PPCInstrInfo::isProfitableToDupForIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, BranchProbability Probability) const inline override
Definition at line 325 of file PPCInstrInfo.h.
isProfitableToIfCvt() [1/2]
bool llvm::PPCInstrInfo::isProfitableToIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, unsigned ExtraPredCycles, BranchProbability Probability) const inline override
Definition at line 313 of file PPCInstrInfo.h.
isProfitableToIfCvt() [2/2]
bool PPCInstrInfo::isProfitableToIfCvt (MachineBasicBlock & TMBB, unsigned NumT, unsigned ExtraT, MachineBasicBlock & FMBB, unsigned NumF, unsigned ExtraF, BranchProbability Probability) const override
Definition at line 1406 of file PPCInstrInfo.cpp.
References MBBDefinesCTR().
isProfitableToUnpredicate()
bool llvm::PPCInstrInfo::isProfitableToUnpredicate (MachineBasicBlock & TMBB, MachineBasicBlock & FMBB) const inline override
Definition at line 330 of file PPCInstrInfo.h.
References llvm::HexagonMCInstrInfo::isPredicated(), and llvm::BitmaskEnumDetail::Mask().
isReallyTriviallyReMaterializable()
bool PPCInstrInfo::isReallyTriviallyReMaterializable (const MachineInstr & MI, AAResults * AA) const override
Definition at line 318 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), llvm_unreachable, and llvm::PPCISD::QVGPCI.
isSameClassPhysRegCopy()
static bool llvm::PPCInstrInfo::isSameClassPhysRegCopy (unsigned Opcode) inline static
Definition at line 190 of file PPCInstrInfo.h.
References llvm::ISD::OR, and UseMI.
isSignExtended()
bool llvm::PPCInstrInfo::isSignExtended (const MachineInstr & MI, const unsigned depth = 0) const inline
Return true if the output of the instruction is always a sign-extended, i.e.
0 to 31-th bits are same as 32-th bit.
Definition at line 411 of file PPCInstrInfo.h.
Referenced by optimizeCompareInstr().
isSignOrZeroExtended()
bool PPCInstrInfo::isSignOrZeroExtended (const MachineInstr & MI, bool SignExt, const unsigned PhiDepth) const
Definition at line 3990 of file PPCInstrInfo.cpp.
References llvm::ISD::AND, assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, D, llvm::dyn_cast(), E, llvm::Function::getAttributes(), llvm::MachineBasicBlock::getBasicBlock(), llvm::IntegerType::getBitWidth(), llvm::Function::getEntryBlock(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachineFunction::getInfo(), llvm::MachineInstr::getNumOperands(), getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::AttributeList::getRetAttributes(), llvm::Function::getReturnType(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getVRegDef(), llvm::AttributeSet::hasAttribute(), I, llvm::MachineBasicBlock::instr_begin(), llvm::MachineInstr::isCall(), llvm::MachineOperand::isGlobal(), llvm::MachineRegisterInfo::isLiveIn(), llvm::PPCFunctionInfo::isLiveInSExt(), llvm::PPCFunctionInfo::isLiveInZExt(), llvm::MachineOperand::isReg(), isSignExtendingOp(), llvm::PPCSubtarget::isSVR4ABI(), llvm::Register::isVirtualRegister(), isZeroExtendingOp(), MRI, and llvm::ISD::OR.
isStoreToStackSlot()
unsigned PPCInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 352 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::getOpcode().
isTOCSaveMI()
bool PPCInstrInfo::isTOCSaveMI (const MachineInstr & MI) const
Definition at line 3973 of file PPCInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
isUnpredicatedTerminator()
bool PPCInstrInfo::isUnpredicatedTerminator (const MachineInstr & MI) const override
Definition at line 1426 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isBranch(), isPredicated(), and llvm::MachineInstr::isTerminator().
isValidToBeChangedReg()
bool PPCInstrInfo::isValidToBeChangedReg (MachineInstr * ADDMI, unsigned Index, MachineInstr *& ADDIMI, int64_t & OffsetAddi, int64_t OffsetImm) const
Definition at line 2689 of file PPCInstrInfo.cpp.
References assert(), getDefMIPostRA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), isADDIInstrEligibleForFolding(), llvm::isInt< 16 >(), and llvm::MachineOperand::isKill().
Referenced by foldFrameOffset().
isVFRegister()
static bool llvm::PPCInstrInfo::isVFRegister (unsigned Reg) inline static
Definition at line 395 of file PPCInstrInfo.h.
Referenced by convertToImmediateForm(), getDefMIPostRA(), and isImmInstrEligibleForFolding().
isVRRegister()
static bool llvm::PPCInstrInfo::isVRRegister (unsigned Reg) inline static
Definition at line 398 of file PPCInstrInfo.h.
isXFormMemOp()
bool llvm::PPCInstrInfo::isXFormMemOp (unsigned Opcode) const inline
Definition at line 187 of file PPCInstrInfo.h.
References llvm::PPCII::XFormMemOp.
Referenced by getLoadOpcodeForSpill(), and storeRegToStackSlot().
isZeroExtended()
bool llvm::PPCInstrInfo::isZeroExtended (const MachineInstr & MI, const unsigned depth = 0) const inline
Return true if the output of the instruction is always zero-extended, i.e.
0 to 31-th bits are all zeros
Definition at line 417 of file PPCInstrInfo.h.
References llvm::foldFrameOffset().
Referenced by optimizeCompareInstr().
loadRegFromStackSlot()
void PPCInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 1277 of file PPCInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::numbers::e, llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::PPCSubtarget::hasVSX(), llvm::MachineBasicBlock::insert(), llvm::MachineMemOperand::MOLoad, reverseBranchCondition(), llvm::PPCFunctionInfo::setHasSpills(), and llvm::SmallVectorBase::size().
Referenced by llvm::PPCFrameLowering::restoreCalleeSavedRegisters().
optimizeCompareInstr()
bool PPCInstrInfo::optimizeCompareInstr (MachineInstr & CmpInstr, unsigned SrcReg, unsigned SrcReg2, int Mask, int Value, const MachineRegisterInfo * MRI) const override
Definition at line 1620 of file PPCInstrInfo.cpp.
References llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), assert(), B, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineInstr::clearRegisterDeads(), llvm::MachineOperand::CreateReg(), llvm::MachineInstr::definesRegister(), DisableCmpOpt, llvm::numbers::e, E, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), first, llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MCInstrDesc::getImplicitDefs(), llvm::MCInstrDesc::getImplicitUses(), llvm::PPC::getNonRecordFormOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::PPC::getPredicate(), llvm::PPC::getPredicateCondition(), llvm::PPC::getPredicateHint(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::PPC::getSwappedPredicate(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), I, llvm::ARM_PROC::IE, llvm::MCInstrDesc::ImplicitDefs, llvm::MCInstrDesc::ImplicitUses, llvm::PPCSubtarget::isPPC64(), isSignExtended(), llvm::Register::isVirtualRegister(), isZeroExtended(), llvm::RegState::Kill, llvm::TargetRegisterInfo::lookThruCopyLike(), MI, llvm::MachineInstr::modifiesRegister(), llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_GT, llvm::PPC::PRED_LE, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineInstr::readsRegister(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::SmallVectorBase::size(), TRI, llvm::MachineRegisterInfo::use_empty(), llvm::MachineRegisterInfo::use_instr_begin(), llvm::MachineRegisterInfo::use_instr_end(), and UseMI.
PredicateInstruction()
bool PPCInstrInfo::PredicateInstruction (MachineInstr & MI, ArrayRef< MachineOperand > Pred) const override
Definition at line 1437 of file PPCInstrInfo.cpp.
References add(), B, llvm::PPCISD::BCTRL, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), getReg(), llvm::PPCSubtarget::isPPC64(), llvm_unreachable, MI, llvm::PPC::PRED_BIT_SET, llvm::PPC::PRED_BIT_UNSET, llvm::MachineInstr::RemoveOperand(), and llvm::MachineInstr::setDesc().
removeBranch()
unsigned PPCInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 670 of file PPCInstrInfo.cpp.
References assert(), B, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), and I.
replaceInstrOperandWithImm()
void PPCInstrInfo::replaceInstrOperandWithImm (MachineInstr & MI, unsigned OpNo, int64_t Imm) const
Definition at line 2253 of file PPCInstrInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineInstr::findRegisterUseOperandIdx(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MachineInstr::implicit_operands(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::MachineInstr::RemoveOperand(), and TRI.
Referenced by convertToImmediateForm(), and swapMIOperands().
replaceInstrWithLI()
void PPCInstrInfo::replaceInstrWithLI (MachineInstr & MI, const LoadImmediateInfo & LII) const
Definition at line 2284 of file PPCInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::MachineInstr::getNumOperands(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::LoadImmediateInfo::Imm, llvm::RegState::ImplicitDefine, llvm::LoadImmediateInfo::Is64Bit, MI, llvm::MachineInstr::RemoveOperand(), llvm::LoadImmediateInfo::SetCR, and llvm::MachineInstr::setDesc().
Referenced by convertToImmediateForm(), and swapMIOperands().
reverseBranchCondition()
bool PPCInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 1314 of file PPCInstrInfo.cpp.
Referenced by loadRegFromStackSlot().
storeRegToStackSlot()
void PPCInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 1224 of file PPCInstrInfo.cpp.
References llvm::addFrameReference(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::BuildMI(), llvm::numbers::e, llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), getLoadOpcodeForSpill(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::MachineBasicBlock::insert(), isXFormMemOp(), llvm::MachineMemOperand::MOStore, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::PPCFunctionInfo::setHasNonRISpills(), llvm::PPCFunctionInfo::setSpillsCR(), llvm::PPCFunctionInfo::setSpillsVRSAVE(), llvm::SmallVectorBase::size(), and updatedRC().
Referenced by llvm::PPCFrameLowering::spillCalleeSavedRegisters().
SubsumesPredicate()
bool PPCInstrInfo::SubsumesPredicate (ArrayRef< MachineOperand > Pred1, ArrayRef< MachineOperand > Pred2) const override
Definition at line 1523 of file PPCInstrInfo.cpp.
References assert(), getReg(), llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_GT, llvm::PPC::PRED_LE, llvm::PPC::PRED_LT, and llvm::ArrayRef< T >::size().
updatedRC()
const TargetRegisterClass * PPCInstrInfo::updatedRC (const TargetRegisterClass * RC) const
Definition at line 3864 of file PPCInstrInfo.cpp.
Referenced by storeRegToStackSlot().
useMachineCombiner()
bool llvm::PPCInstrInfo::useMachineCombiner () const inline override
Definition at line 232 of file PPCInstrInfo.h.
References llvm::ISD::FrameIndex, and P.
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCInstrInfo.h
lib/Target/PowerPC/PPCInstrInfo.cpp