LLVM: llvm::DWARFGdbIndex Class Reference
llvm::DWARFGdbIndex Class Reference
#include "llvm/DebugInfo/DWARF/DWARFGdbIndex.h"
Public Member Functions
void dump (raw_ostream &OS)
void parse (DataExtractor Data)
Public Attributes
bool HasContent = false
bool HasError = false
Detailed Description
Definition at line 22 of file DWARFGdbIndex.h.
Member Function Documentation
dump()
void DWARFGdbIndex::dump (raw_ostream & OS)
Definition at line 98 of file DWARFGdbIndex.cpp.
References llvm::Data, llvm::StringRef::drop_front(), llvm::DataExtractor::getData(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), HasContent, HasError, I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorImpl< T >::resize().
Referenced by llvm::DWARFContext::dump().
parse()
void DWARFGdbIndex::parse (DataExtractor Data)
Definition at line 196 of file DWARFGdbIndex.cpp.
References llvm::StringRef::empty(), llvm::DataExtractor::getData(), HasContent, and HasError.
Member Data Documentation
HasContent
bool llvm::DWARFGdbIndex::HasContent = false
Definition at line 76 of file DWARFGdbIndex.h.
Referenced by dump(), and parse().
HasError
bool llvm::DWARFGdbIndex::HasError = false
Definition at line 77 of file DWARFGdbIndex.h.
Referenced by dump(), and parse().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFGdbIndex.h
lib/DebugInfo/DWARF/DWARFGdbIndex.cpp