LLVM: llvm::MCParsedAsmOperand Class Reference
llvm::MCParsedAsmOperand Class Reference abstract
MCParsedAsmOperand - This abstract class represents a source-level assembly instruction operand.
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
Public Member Functions
virtual ~MCParsedAsmOperand ()=default
void setConstraint (StringRef C)
StringRef getConstraint ()
void setMCOperandNum (unsigned OpNum)
unsigned getMCOperandNum ()
virtual StringRef getSymName ()
virtual void * getOpDecl ()
virtual bool isToken () const =0
isToken - Is this a token operand?
virtual bool isImm () const =0
isImm - Is this an immediate operand?
virtual bool isReg () const =0
isReg - Is this a register operand?
virtual unsigned getReg () const =0
virtual bool isMem () const =0
isMem - Is this a memory operand?
virtual SMLoc getStartLoc () const =0
getStartLoc - Get the location of the first token of this operand.
virtual SMLoc getEndLoc () const =0
getEndLoc - Get the location of the last token of this operand.
virtual bool needAddressOf () const
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
virtual bool isOffsetOfLocal () const
isOffsetOfLocal - Do we need to emit code to get the offset of the local variable, rather than its value? Only valid when parsing MS-style inline assembly.
virtual SMLoc getOffsetOfLoc () const
getOffsetOfLoc - Get the location of the offset operator.
virtual void print (raw_ostream &OS) const =0
print - Print a debug representation of the operand to the given stream.
virtual void dump () const
dump - Print to the debug stream.
Protected Member Functions
MCParsedAsmOperand ()=default
MCParsedAsmOperand (const MCParsedAsmOperand &RHS)=default
MCParsedAsmOperand & operator= (const MCParsedAsmOperand &)=default
Detailed Description
MCParsedAsmOperand - This abstract class represents a source-level assembly instruction operand.
It should be subclassed by target-specific code. This base class is used by target-independent clients and is the interface between parsing an asm instruction and recognizing it.
Definition at line 24 of file MCParsedAsmOperand.h.
Constructor & Destructor Documentation
MCParsedAsmOperand() [1/2]
llvm::MCParsedAsmOperand::MCParsedAsmOperand () protected default
MCParsedAsmOperand() [2/2]
llvm::MCParsedAsmOperand::MCParsedAsmOperand (const MCParsedAsmOperand & RHS) protected default
~MCParsedAsmOperand()
virtual llvm::MCParsedAsmOperand::~MCParsedAsmOperand () virtual default
Member Function Documentation
dump()
void MCParsedAsmOperand::dump () const virtual
dump - Print to the debug stream.
Definition at line 131 of file MCAsmParser.cpp.
References llvm::dbgs().
Referenced by getOffsetOfLoc().
getConstraint()
StringRef llvm::MCParsedAsmOperand::getConstraint () inline
Definition at line 46 of file MCParsedAsmOperand.h.
Referenced by rewritesSort().
getEndLoc()
virtual SMLoc llvm::MCParsedAsmOperand::getEndLoc () const pure virtual
getEndLoc - Get the location of the last token of this operand.
Implemented in llvm::X86Operand.
Referenced by getOpDecl().
getMCOperandNum()
unsigned llvm::MCParsedAsmOperand::getMCOperandNum () inline
Definition at line 49 of file MCParsedAsmOperand.h.
Referenced by rewritesSort().
getOffsetOfLoc()
virtual SMLoc llvm::MCParsedAsmOperand::getOffsetOfLoc () const inline virtual
getOffsetOfLoc - Get the location of the offset operator.
Reimplemented in llvm::X86Operand.
Definition at line 80 of file MCParsedAsmOperand.h.
References dump(), and print().
getOpDecl()
virtual void* llvm::MCParsedAsmOperand::getOpDecl () inline virtual
Reimplemented in llvm::X86Operand.
Definition at line 52 of file MCParsedAsmOperand.h.
References getEndLoc(), getReg(), getStartLoc(), isImm(), isMem(), isReg(), and isToken().
Referenced by rewritesSort().
getReg()
virtual unsigned llvm::MCParsedAsmOperand::getReg () const pure virtual
Implemented in llvm::X86Operand.
Referenced by getOpDecl(), llvm::MCTargetAsmParser::regsEqual(), and rewritesSort().
getStartLoc()
virtual SMLoc llvm::MCParsedAsmOperand::getStartLoc () const pure virtual
getStartLoc - Get the location of the first token of this operand.
Implemented in llvm::X86Operand.
Referenced by getOpDecl(), and printMCExpr().
getSymName()
virtual StringRef llvm::MCParsedAsmOperand::getSymName () inline virtual
Reimplemented in llvm::X86Operand.
Definition at line 51 of file MCParsedAsmOperand.h.
Referenced by rewritesSort().
isImm()
virtual bool llvm::MCParsedAsmOperand::isImm () const pure virtual
isImm - Is this an immediate operand?
Implemented in llvm::X86Operand.
Referenced by getOpDecl(), and rewritesSort().
isMem()
virtual bool llvm::MCParsedAsmOperand::isMem () const pure virtual
isMem - Is this a memory operand?
Implemented in llvm::X86Operand.
Referenced by getOpDecl().
isOffsetOfLocal()
virtual bool llvm::MCParsedAsmOperand::isOffsetOfLocal () const inline virtual
isOffsetOfLocal - Do we need to emit code to get the offset of the local variable, rather than its value? Only valid when parsing MS-style inline assembly.
Reimplemented in llvm::X86Operand.
Definition at line 77 of file MCParsedAsmOperand.h.
Referenced by rewritesSort().
isReg()
virtual bool llvm::MCParsedAsmOperand::isReg () const pure virtual
isReg - Is this a register operand?
Implemented in llvm::X86Operand.
Referenced by getOpDecl(), llvm::MCTargetAsmParser::regsEqual(), and rewritesSort().
isToken()
virtual bool llvm::MCParsedAsmOperand::isToken () const pure virtual
isToken - Is this a token operand?
Implemented in llvm::X86Operand.
Referenced by getOpDecl(), and previousEqual().
needAddressOf()
virtual bool llvm::MCParsedAsmOperand::needAddressOf () const inline virtual
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
Reimplemented in llvm::X86Operand.
Definition at line 72 of file MCParsedAsmOperand.h.
Referenced by rewritesSort().
operator=()
MCParsedAsmOperand& llvm::MCParsedAsmOperand::operator= (const MCParsedAsmOperand &) protected default
print()
virtual void llvm::MCParsedAsmOperand::print (raw_ostream & OS) const pure virtual
print - Print a debug representation of the operand to the given stream.
Implemented in llvm::X86Operand.
Referenced by getOffsetOfLoc(), and llvm::operator<<().
setConstraint()
void llvm::MCParsedAsmOperand::setConstraint (StringRef C) inline
Definition at line 45 of file MCParsedAsmOperand.h.
References llvm::StringRef::str().
setMCOperandNum()
void llvm::MCParsedAsmOperand::setMCOperandNum (unsigned OpNum) inline
Definition at line 48 of file MCParsedAsmOperand.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCParser/MCParsedAsmOperand.h
lib/MC/MCParser/MCAsmParser.cpp