LLVM: llvm::Function Class Reference
llvm::Function Class Reference
#include "llvm/IR/Function.h"
Classes
class ProfileCount
Class to represent profile counts.
Public Types
enum ProfileCountType { PCT_Invalid, PCT_Real, PCT_Synthetic }
using BasicBlockListType = SymbolTableList< BasicBlock >
using iterator = BasicBlockListType::iterator
using const_iterator = BasicBlockListType::const_iterator
using arg_iterator = Argument *
using const_arg_iterator = const Argument *
Public Types inherited from llvm::GlobalObject
enum VCallVisibility { VCallVisibilityPublic = 0, VCallVisibilityLinkageUnit = 1, VCallVisibilityTranslationUnit = 2 }
Public Types inherited from llvm::GlobalValue
enum LinkageTypes {
ExternalLinkage = 0, AvailableExternallyLinkage, LinkOnceAnyLinkage, LinkOnceODRLinkage,
WeakAnyLinkage, WeakODRLinkage, AppendingLinkage, InternalLinkage,
PrivateLinkage, ExternalWeakLinkage, CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0, HiddenVisibility, ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0, DLLImportStorageClass = 1, DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0, GeneralDynamicTLSModel, LocalDynamicTLSModel, InitialExecTLSModel,
LocalExecTLSModel
}
enum UnnamedAddr { UnnamedAddr::None, UnnamedAddr::Local, UnnamedAddr::Global }
using GUID = uint64_t
Declare a type to represent a global unique identifier for a global value.
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
bool hasLazyArguments () const
hasLazyArguments/CheckLazyArguments - The argument list of a function is built on demand, so that the list isn't allocated until the first client needs it.
Function (const Function &)=delete
void operator= (const Function &)=delete
~Function ()
const Function & getFunction () const
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
unsigned getInstructionCount () const
Returns the number of non-debug IR instructions in this function.
FunctionType * getFunctionType () const
Returns the FunctionType for me.
Type * getReturnType () const
Returns the type of the ret val.
LLVMContext & getContext () const
getContext - Return a reference to the LLVMContext associated with this function.
bool isVarArg () const
isVarArg - Return true if this function takes a variable number of arguments.
bool isMaterializable () const
void setIsMaterializable (bool V)
Intrinsic::ID getIntrinsicID () const LLVM_READONLY
getIntrinsicID - This method returns the ID number of the specified function, or Intrinsic::not_intrinsic if the function is not an intrinsic, or if the pointer is null.
bool isIntrinsic () const
isIntrinsic - Returns true if the function's name starts with "llvm.".
void recalculateIntrinsicID ()
Recalculate the ID for this function if it is an Intrinsic defined in llvm/Intrinsics.h.
CallingConv::ID getCallingConv () const
getCallingConv()/setCallingConv(CC) - These method get and set the calling convention of this function.
void setCallingConv (CallingConv::ID CC)
AttributeList getAttributes () const
Return the attribute list for this Function.
void setAttributes (AttributeList Attrs)
Set the attribute list for this Function.
void addFnAttr (Attribute::AttrKind Kind)
Add function attributes to this function.
void addFnAttr (StringRef Kind, StringRef Val=StringRef())
Add function attributes to this function.
void addFnAttr (Attribute Attr)
Add function attributes to this function.
void removeFnAttr (Attribute::AttrKind Kind)
Remove function attributes from this function.
void removeFnAttr (StringRef Kind)
Remove function attribute from this function.
void setEntryCount (ProfileCount Count, const DenseSet< GlobalValue::GUID > *Imports=nullptr)
Set the entry count for this function.
void setEntryCount (uint64_t Count, ProfileCountType Type=PCT_Real, const DenseSet< GlobalValue::GUID > *Imports=nullptr)
A convenience wrapper for setting entry count.
ProfileCount getEntryCount (bool AllowSynthetic=false) const
Get the entry count for this function.
bool hasProfileData (bool IncludeSynthetic=false) const
Return true if the function is annotated with profile data.
DenseSet< GlobalValue::GUID > getImportGUIDs () const
Returns the set of GUIDs that needs to be imported to the function for sample PGO, to enable the same inlines as the profiled optimized binary.
void setSectionPrefix (StringRef Prefix)
Set the section prefix for this function.
Optional< StringRef > getSectionPrefix () const
Get the section prefix for this function.
bool hasFnAttribute (Attribute::AttrKind Kind) const
Return true if the function has the attribute.
bool hasFnAttribute (StringRef Kind) const
Return true if the function has the attribute.
Attribute getFnAttribute (Attribute::AttrKind Kind) const
Return the attribute for the given attribute kind.
Attribute getFnAttribute (StringRef Kind) const
Return the attribute for the given attribute kind.
unsigned getFnStackAlignment () const
Return the stack alignment for the function.
bool hasGC () const
hasGC/getGC/setGC/clearGC - The name of the garbage collection algorithm to use during code generation.
const std::string & getGC () const
void setGC (std::string Str)
void clearGC ()
void addAttribute (unsigned i, Attribute::AttrKind Kind)
adds the attribute to the list of attributes.
void addAttribute (unsigned i, Attribute Attr)
adds the attribute to the list of attributes.
void addAttributes (unsigned i, const AttrBuilder &Attrs)
adds the attributes to the list of attributes.
void addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
adds the attribute to the list of attributes for the given arg.
void addParamAttr (unsigned ArgNo, Attribute Attr)
adds the attribute to the list of attributes for the given arg.
void addParamAttrs (unsigned ArgNo, const AttrBuilder &Attrs)
adds the attributes to the list of attributes for the given arg.
void removeAttribute (unsigned i, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
void removeAttribute (unsigned i, StringRef Kind)
removes the attribute from the list of attributes.
void removeAttributes (unsigned i, const AttrBuilder &Attrs)
removes the attributes from the list of attributes.
void removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
void removeParamAttr (unsigned ArgNo, StringRef Kind)
removes the attribute from the list of attributes.
void removeParamAttrs (unsigned ArgNo, const AttrBuilder &Attrs)
removes the attribute from the list of attributes.
bool hasAttribute (unsigned i, Attribute::AttrKind Kind) const
check if an attributes is in the list of attributes.
bool hasParamAttribute (unsigned ArgNo, Attribute::AttrKind Kind) const
check if an attributes is in the list of attributes.
Attribute getParamAttribute (unsigned ArgNo, Attribute::AttrKind Kind) const
gets the specified attribute from the list of attributes.
Attribute getAttribute (unsigned i, Attribute::AttrKind Kind) const
gets the attribute from the list of attributes.
Attribute getAttribute (unsigned i, StringRef Kind) const
gets the attribute from the list of attributes.
void addDereferenceableAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
void addDereferenceableParamAttr (unsigned ArgNo, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes for the given arg.
void addDereferenceableOrNullAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes.
void addDereferenceableOrNullParamAttr (unsigned ArgNo, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes for the given arg.
unsigned getParamAlignment (unsigned ArgNo) const
Extract the alignment for a call or parameter (0=unknown).
MaybeAlign getParamAlign (unsigned ArgNo) const
Type * getParamByValType (unsigned ArgNo) const
Extract the byval type for a parameter.
uint64_t getDereferenceableBytes (unsigned i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getParamDereferenceableBytes (unsigned ArgNo) const
Extract the number of dereferenceable bytes for a parameter.
uint64_t getDereferenceableOrNullBytes (unsigned i) const
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
uint64_t getParamDereferenceableOrNullBytes (unsigned ArgNo) const
Extract the number of dereferenceable_or_null bytes for a parameter.
bool doesNotAccessMemory () const
Determine if the function does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the function does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReadMemory () const
Determine if the function does not access or only writes memory.
void setDoesNotReadMemory ()
bool onlyAccessesArgMemory () const
Determine if the call can access memmory only using pointers based on its arguments.
void setOnlyAccessesArgMemory ()
bool onlyAccessesInaccessibleMemory () const
Determine if the function may only access memory that is inaccessible from the IR.
void setOnlyAccessesInaccessibleMemory ()
bool onlyAccessesInaccessibleMemOrArgMem () const
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
void setOnlyAccessesInaccessibleMemOrArgMem ()
bool doesNotReturn () const
Determine if the function cannot return.
void setDoesNotReturn ()
bool doesNoCfCheck () const
Determine if the function should not perform indirect branch tracking.
bool doesNotThrow () const
Determine if the function cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the call cannot be duplicated.
void setCannotDuplicate ()
bool isConvergent () const
Determine if the call is convergent.
void setConvergent ()
void setNotConvergent ()
bool isSpeculatable () const
Determine if the call has sideeffects.
void setSpeculatable ()
bool doesNotFreeMemory () const
Determine if the call might deallocate memory.
void setDoesNotFreeMemory ()
bool doesNotRecurse () const
Determine if the function is known not to recurse, directly or indirectly.
void setDoesNotRecurse ()
bool hasUWTable () const
True if the ABI mandates (or the user requested) that this function be in a unwind table.
void setHasUWTable ()
bool needsUnwindTableEntry () const
True if this function needs an unwind table.
bool hasStructRetAttr () const
Determine if the function returns a structure through first or second pointer argument.
bool returnDoesNotAlias () const
Determine if the parameter or return value is marked with NoAlias attribute.
void setReturnDoesNotAlias ()
bool hasOptNone () const
Do not optimize this function (-O0).
bool hasMinSize () const
Optimize this function for minimum size (-Oz).
bool hasOptSize () const
Optimize this function for size (-Os) or minimum size (-Oz).
void copyAttributesFrom (const Function *Src)
copyAttributesFrom - copy all additional attributes (those not needed to create a Function) from the Function Src to this one.
void deleteBody ()
deleteBody - This method deletes the body of the function, and converts the linkage to external.
void removeFromParent ()
removeFromParent - This method unlinks 'this' from the containing module, but does not delete it.
void eraseFromParent ()
eraseFromParent - This method unlinks 'this' from the containing module and deletes it.
void stealArgumentListFrom (Function &Src)
Steal arguments from another function.
const BasicBlockListType & getBasicBlockList () const
Get the underlying elements of the Function...
BasicBlockListType & getBasicBlockList ()
const BasicBlock & getEntryBlock () const
BasicBlock & getEntryBlock ()
ValueSymbolTable * getValueSymbolTable ()
getSymbolTable() - Return the symbol table if any, otherwise nullptr.
const ValueSymbolTable * getValueSymbolTable () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_t size () const
bool empty () const
const BasicBlock & front () const
BasicBlock & front ()
const BasicBlock & back () const
BasicBlock & back ()
size_t arg_size () const
bool arg_empty () const
bool hasPersonalityFn () const
Check whether this function has a personality function.
Constant * getPersonalityFn () const
Get the personality function associated with this function.
void setPersonalityFn (Constant *Fn)
bool hasPrefixData () const
Check whether this function has prefix data.
Constant * getPrefixData () const
Get the prefix data associated with this function.
void setPrefixData (Constant *PrefixData)
bool hasPrologueData () const
Check whether this function has prologue data.
Constant * getPrologueData () const
Get the prologue data associated with this function.
void setPrologueData (Constant *PrologueData)
void print (raw_ostream &OS, AssemblyAnnotationWriter *AAW=nullptr, bool ShouldPreserveUseListOrder=false, bool IsForDebug=false) const
Print the function to an output stream with an optional AssemblyAnnotationWriter.
void viewCFG () const
viewCFG - This function is meant for use from the debugger.
void viewCFGOnly () const
viewCFGOnly - This function is meant for use from the debugger.
void dropAllReferences ()
dropAllReferences() - This method causes all the subinstructions to "let go" of all references that they are maintaining.
bool hasAddressTaken (const User **=nullptr) const
hasAddressTaken - returns true if there are any uses of this function other than direct calls or invokes to it, or blockaddress expressions.
bool isDefTriviallyDead () const
isDefTriviallyDead - Return true if it is trivially safe to remove this function definition from the module (because it isn't externally visible, does not have its address taken, and has no callers).
bool callsFunctionThatReturnsTwice () const
callsFunctionThatReturnsTwice - Return true if the function has a call to setjmp or other function that gcc recognizes as "returning twice".
void setSubprogram (DISubprogram *SP)
Set the attached subprogram.
DISubprogram * getSubprogram () const
Get the attached subprogram.
bool isDebugInfoForProfiling () const
Returns true if we should emit debug info for profiling.
bool nullPointerIsDefined () const
Check if null pointer dereferencing is considered undefined behavior for the function.
Function Argument Iteration
arg_iterator arg_begin ()
const_arg_iterator arg_begin () const
arg_iterator arg_end ()
const_arg_iterator arg_end () const
Argument * getArg (unsigned i) const
iterator_range< arg_iterator > args ()
iterator_range< const_arg_iterator > args () const
Public Member Functions inherited from llvm::GlobalObject
GlobalObject (const GlobalObject &)=delete
unsigned getAlignment () const
LLVM_ATTRIBUTE_DEPRECATED (void setAlignment(unsigned Align), "Please use `void setAlignment(MaybeAlign Align)`")
FIXME: Remove this setter once the migration to MaybeAlign is over.
void setAlignment (MaybeAlign Align)
unsigned getGlobalObjectSubClassData () const
void setGlobalObjectSubClassData (unsigned Val)
bool hasSection () const
Check if this global has a custom object file section.
StringRef getSection () const
Get the custom section of this global if it has one.
void setSection (StringRef S)
Change the section for this global.
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
void setComdat (Comdat *C)
bool hasMetadata () const
Check if this has any metadata.
bool hasMetadata (unsigned KindID) const
Check if this has any metadata of the given kind.
bool hasMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode *>> &MDs) const
Appends all attachments for the global to MDs, sorting by attachment ID.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void copyMetadata (const GlobalObject *Src, unsigned Offset)
Copy metadata from Src, adjusting offsets by Offset.
void addTypeMetadata (unsigned Offset, Metadata *TypeID)
void addVCallVisibilityMetadata (VCallVisibility Visibility)
VCallVisibility getVCallVisibility () const
void clearMetadata ()
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode *> &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode *> &MDs) const
void setMetadata (unsigned KindID, MDNode *MD)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *MD)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Public Member Functions inherited from llvm::GlobalValue
GlobalValue (const GlobalValue &)=delete
unsigned getAlignment () const
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
void setUnnamedAddr (UnnamedAddr Val)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
StringRef getSection () const
PointerType * getType () const
Global values are always pointers.
Type * getValueType () const
void setDSOLocal (bool Local)
bool isDSOLocal () const
bool hasPartition () const
StringRef getPartition () const
void setPartition (StringRef Part)
bool isDefinitionExact () const
Return true if the currently visible definition of this global (if any) is exactly the definition we will see at runtime.
bool hasExactDefinition () const
Return true if this global has an exact defintion.
bool isInterposable () const
Return true if this global's definition can be substituted with an arbitrary definition at link time.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
bool hasValidDeclarationLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool isWeakForLinker () const
std::string getGlobalIdentifier () const
Return the modified name for this global value suitable to be used as the key for a global lookup (e.g.
GUID getGUID () const
Return a 64-bit global unique ID constructed from global value name (i.e.
bool isDeclaration () const
Return true if the primary definition of this global value is outside of the current translation unit.
bool isDeclarationForLinker () const
bool isStrongDefinitionForLinker () const
Returns true if this global's definition will be the one chosen by the linker.
bool canIncreaseAlignment () const
const GlobalObject * getBaseObject () const
GlobalObject * getBaseObject ()
bool isAbsoluteSymbolRef () const
Returns whether this is a reference to an absolute symbol.
Optional< ConstantRange > getAbsoluteSymbolRange () const
If this is an absolute symbol reference, returns the range of the symbol, otherwise returns None.
void removeFromParent ()
This method unlinks 'this' from the containing module, but does not delete it.
void eraseFromParent ()
This method unlinks 'this' from the containing module and deletes it.
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
bool canBeOmittedFromSymbolTable () const
True if GV can be left out of the object symbol table.
bool isMaterializable () const
If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Error materialize ()
Make sure this GlobalValue is fully read.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefElement () const
Return true if this is a vector constant that includes any undefined elements.
bool containsConstantExpression () const
Return true if this is a vector constant that includes any constant expressions.
bool canTrap () const
Return true if evaluation of this constant could trap.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry.
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Function, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static Function * Create (FunctionType *Ty, LinkageTypes Linkage, unsigned AddrSpace, const Twine &N="", Module *M=nullptr)
static Function * Create (FunctionType *Ty, LinkageTypes Linkage, const Twine &N="", Module *M=nullptr)
static Function * Create (FunctionType *Ty, LinkageTypes Linkage, const Twine &N, Module &M)
Creates a new function and attaches it to a module.
static Intrinsic::ID lookupIntrinsicID (StringRef Name)
This does the actual lookup of an intrinsic ID which matches the given function name.
static BasicBlockListType Function::* getSublistAccess (BasicBlock *)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::GlobalObject
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalValue
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isValidDeclarationLinkage (LinkageTypes Linkage)
static bool isInterposableLinkage (LinkageTypes Linkage)
Whether the definition of this global may be replaced by something non-equivalent at link time.
static bool isDiscardableIfUnused (LinkageTypes Linkage)
Whether the definition of this global may be discarded if it is not used in its compilation unit.
static bool isWeakForLinker (LinkageTypes Linkage)
Whether the definition of this global may be replaced at link time.
static StringRef dropLLVMManglingEscape (StringRef Name)
If the given string begins with the GlobalValue name mangling escape character '\1', drop it.
static std::string getGlobalIdentifier (StringRef Name, GlobalValue::LinkageTypes Linkage, StringRef FileName)
Return the modified name for a global value suitable to be used as the key for a global lookup (e.g.
static GUID getGUID (StringRef GlobalName)
Return a 64-bit global unique ID constructed from global value name (i.e.
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class SymbolTableListTraits< Function >
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::GlobalObject
enum { LastAlignmentBit = 4, HasMetadataHashEntryBit, HasSectionHashEntryBit, GlobalObjectBits }
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Function, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< Function, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Function, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Function, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Function, Options... >::type, true, true >
Protected Member Functions inherited from llvm::GlobalObject
GlobalObject (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace=0)
void copyAttributesFrom (const GlobalObject *Src)
Protected Member Functions inherited from llvm::GlobalValue
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
void setParent (Module *parent)
~GlobalValue ()
void copyAttributesFrom (const GlobalValue *Src)
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Function, Options... >::type >
ilist_node_impl ()=default
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::GlobalObject
Comdat * ObjComdat
Protected Attributes inherited from llvm::GlobalValue
Type * ValueType
unsigned Linkage: 4
unsigned Visibility: 2
unsigned UnnamedAddrVal: 2
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
unsigned HasLLVMReservedName: 1
True if the function's name starts with "llvm.".
unsigned IsDSOLocal: 1
If true then there is a definition within the same linkage unit and that definition cannot be runtime preempted.
unsigned HasPartition: 1
True if this symbol has a partition name assigned (see https://lld.llvm.org/Partitions.html).
Intrinsic::ID IntID
The intrinsic ID for this subclass (which must be a Function).
Module * Parent
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes inherited from llvm::GlobalObject
static const unsigned GlobalObjectSubClassDataBits
Static Protected Attributes inherited from llvm::GlobalValue
static const unsigned GlobalValueSubClassDataBits = 16
Detailed Description
Definition at line 59 of file Function.h.
Member Typedef Documentation
arg_iterator
using llvm::Function::arg_iterator = Argument *
Definition at line 67 of file Function.h.
BasicBlockListType
using llvm::Function::BasicBlockListType = SymbolTableList<BasicBlock>
Definition at line 61 of file Function.h.
const_arg_iterator
using llvm::Function::const_arg_iterator = const Argument *
Definition at line 68 of file Function.h.
const_iterator
using llvm::Function::const_iterator = BasicBlockListType::const_iterator
Definition at line 65 of file Function.h.
iterator
using llvm::Function::iterator = BasicBlockListType::iterator
Definition at line 64 of file Function.h.
Member Enumeration Documentation
ProfileCountType
enum llvm::Function::ProfileCountType
Enumerator
PCT_Invalid
PCT_Real
PCT_Synthetic
Definition at line 255 of file Function.h.
Constructor & Destructor Documentation
Function()
llvm::Function::Function (const Function &) delete
~Function()
Function::~Function ()
Definition at line 289 of file Function.cpp.
References llvm::Argument::Argument(), Arguments, assert(), llvm::numbers::e, llvm::Value::getSubclassDataFromValue(), llvm::Type::isVoidTy(), and llvm::Value::setValueSubclassData().
Member Function Documentation
addAttribute() [1/2]
void Function::addAttribute (unsigned i, Attribute::AttrKind Kind)
adds the attribute to the list of attributes.
Definition at line 399 of file Function.cpp.
References llvm::AttributeList::addAttribute(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
Referenced by AddCalls(), LLVMAddTargetDependentFunctionAttr(), setRetDoesNotAlias(), and setRetNonNull().
addAttribute() [2/2]
void Function::addAttribute (unsigned i, Attribute Attr)
adds the attribute to the list of attributes.
Definition at line 405 of file Function.cpp.
References llvm::AttributeList::addAttribute(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
addAttributes()
void Function::addAttributes (unsigned i, const AttrBuilder & Attrs)
adds the attributes to the list of attributes.
Definition at line 411 of file Function.cpp.
References llvm::AttributeList::addAttributes(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
Referenced by llvm::createX86RetpolineThunksPass(), removeUseSoftFloat(), and setFastFlags().
addDereferenceableAttr()
void Function::addDereferenceableAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
Definition at line 471 of file Function.cpp.
References llvm::AttributeList::addDereferenceableAttr(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
addDereferenceableOrNullAttr()
void Function::addDereferenceableOrNullAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes.
Definition at line 483 of file Function.cpp.
References llvm::AttributeList::addDereferenceableOrNullAttr(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
addDereferenceableOrNullParamAttr()
void Function::addDereferenceableOrNullParamAttr (unsigned ArgNo, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes for the given arg.
Definition at line 489 of file Function.cpp.
References llvm::AttributeList::addDereferenceableOrNullParamAttr(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
addDereferenceableParamAttr()
void Function::addDereferenceableParamAttr (unsigned ArgNo, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes for the given arg.
Definition at line 477 of file Function.cpp.
References llvm::AttributeList::addDereferenceableParamAttr(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
addFnAttr() [1/3]
void llvm::Function::addFnAttr (Attribute::AttrKind Kind) inline
Add function attributes to this function.
Definition at line 229 of file Function.h.
References llvm::AttributeList::FunctionIndex.
Referenced by addForcedAttributes(), adjustCallerSSPLevel(), adjustCallerStackProbes(), adjustCallerStackProbeSize(), adjustMinLegalVectorWidth(), adjustNullPointerValidAttr(), assureFPCallStub(), createDevirtTriggerFunc(), createFPFnStub(), llvm::CodeExtractor::findInputsOutputs(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), handleAttr(), INITIALIZE_PASS(), llvm::NVPTXTargetLowering::LowerCall(), prepareForSplit(), runImpl(), selectJumpTableArmEncoding(), setCannotDuplicate(), llvm::IRBuilderBase::setConstrainedFPFunctionAttr(), setDoesNotFreeMemory(), setNonLazyBind(), and shouldKeepInEntry().
addFnAttr() [2/3]
void llvm::Function::addFnAttr (StringRef Kind, StringRef Val = StringRef()) inline
Add function attributes to this function.
Definition at line 234 of file Function.h.
References llvm::AttributeList::FunctionIndex, and llvm::Attribute::get().
addFnAttr() [3/3]
void llvm::Function::addFnAttr (Attribute Attr) inline
Add function attributes to this function.
Definition at line 240 of file Function.h.
References llvm::AttributeList::FunctionIndex.
addParamAttr() [1/2]
void Function::addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
adds the attribute to the list of attributes for the given arg.
Definition at line 417 of file Function.cpp.
References llvm::AttributeList::addParamAttribute(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
Referenced by llvm::Argument::addAttr(), createCloneDeclaration(), llvm::OpenMPIRBuilder::CreateParallel(), insertLifetimeMarkersSurroundingCall(), setDoesNotAlias(), setDoesNotCapture(), setOnlyReadsMemory(), and setReturnedArg().
addParamAttr() [2/2]
void Function::addParamAttr (unsigned ArgNo, Attribute Attr)
adds the attribute to the list of attributes for the given arg.
Definition at line 423 of file Function.cpp.
References llvm::AttributeList::addParamAttribute(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
addParamAttrs()
void Function::addParamAttrs (unsigned ArgNo, const AttrBuilder & Attrs)
adds the attributes to the list of attributes for the given arg.
Definition at line 429 of file Function.cpp.
References llvm::AttributeList::addParamAttributes(), llvm::Intrinsic::getAttributes(), and llvm::Value::getContext().
arg_begin() [1/2]
arg_iterator llvm::Function::arg_begin () inline
Definition at line 706 of file Function.h.
References Arguments.
Referenced by addByteCountSuffix(), llvm::Interpreter::callFunction(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::orc::cloneFunctionDecl(), llvm::CloneModule(), llvm::FunctionComparator::compareSignature(), llvm::createDeadArgHackingPass(), createWrapper(), determinePointerReadAttrs(), doPromotion(), eliminateRecursiveTailCall(), EnsureStackAlignment(), llvm::Evaluator::EvaluateFunction(), llvm::CodeExtractor::findInputsOutputs(), findTRECandidate(), FunctionNumber(), getFrameType(), getRetComponentType(), llvm::MipsCCState::getSpecialCallingConvForCallee(), HasNestArgument(), hasSameArgumentList(), INITIALIZE_PASS(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), isDynamicConstant(), LLVMGetFirstParam(), LLVMGetLastParam(), LLVMGetParam(), LLVMGetParams(), LLVMGetPreviousParam(), lookupFunction(), LowerVASTART(), mayTailCallThisCC(), needsFPFromSig(), PropagateConstantsIntoArguments(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::SwiftErrorValueTracking::setFunction(), UnpackFromArgumentSlot(), and UpgradeIntrinsicFunction1().
arg_begin() [2/2]
const_arg_iterator llvm::Function::arg_begin () const inline
Definition at line 710 of file Function.h.
References Arguments.
arg_empty()
bool llvm::Function::arg_empty () const inline
Definition at line 740 of file Function.h.
Referenced by CC_RISCV_FastCC(), llvm::RISCVCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), PropagateConstantsIntoArguments(), and UnpackFromArgumentSlot().
arg_end() [1/2]
arg_iterator llvm::Function::arg_end () inline
Definition at line 715 of file Function.h.
Referenced by addByteCountSuffix(), llvm::Interpreter::callFunction(), llvm::orc::cloneFunctionDecl(), llvm::FunctionComparator::compareSignature(), createWrapper(), doPromotion(), eliminateRecursiveTailCall(), llvm::Evaluator::EvaluateFunction(), findTRECandidate(), getRetComponentType(), HasNestArgument(), INITIALIZE_PASS(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), LLVMGetFirstParam(), LLVMGetLastParam(), LLVMGetParams(), lookupFunction(), mayTailCallThisCC(), PushArgMD(), and llvm::SwiftErrorValueTracking::setFunction().
arg_end() [2/2]
const_arg_iterator llvm::Function::arg_end () const inline
Definition at line 719 of file Function.h.
arg_size()
size_t llvm::Function::arg_size () const inline
Definition at line 739 of file Function.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::Interpreter::callFunction(), CC_X86_Intr(), llvm::CloneFunctionInto(), llvm::FunctionComparator::compareSignature(), determinePointerReadAttrs(), llvm::X86FrameLowering::emitPrologue(), findArgumentCopyElisionCandidates(), llvm::FunctionComparator::functionHash(), llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo(), llvm::IRPosition::getAssociatedArgument(), llvm::IRPosition::getAttrs(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), llvm::AMDGPULibFunc::getFunction(), llvm::AMDGPULibFunc::getOrInsertFunction(), getRetComponentType(), llvm::MipsCCState::getSpecialCallingConvForCallee(), getSuccPad(), hasSameArgumentList(), INITIALIZE_PASS(), lookupFunction(), needsFPFromSig(), needsFPStubFromParams(), PropagateConstantsIntoArguments(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::GVNHoist::run(), stealArgumentListFrom(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), UpgradeIntrinsicFunction1(), UpgradeX86IntrinsicFunction(), and whichFPParamVariantNeeded().
args() [1/2]
iterator_range<arg_iterator> llvm::Function::args () inline
Definition at line 730 of file Function.h.
References llvm::make_range().
Referenced by AddAliasScopeMetadata(), AddAlignmentAssumptions(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::coro::buildCoroutineFrame(), canCreateThunkFor(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneFunction(), llvm::CloneFunctionInto(), llvm::createDeadArgHackingPass(), eliminateSwiftError(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo(), FunctionNumber(), genericValueTraversal(), llvm::IRPosition::getAttrs(), llvm::AMDGPUSubtarget::getExplicitKernArgSize(), llvm::GPUDivergenceAnalysis::GPUDivergenceAnalysis(), handleEndBlock(), hasAnyNonFlatUseOfReg(), llvm::HexagonEvaluator::HexagonEvaluator(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::ValueEnumerator::incorporateFunction(), INITIALIZE_PASS(), initSlots2Values(), insertIfNamed(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isReassociableOp(), llvm::X86CallLowering::lowerFormalArguments(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::orc::makeStub(), MarkBlocksLiveIn(), markTails(), maybePrintComdat(), okayForPHIOfOps(), populateExternalRelations(), llvm::LegacyDivergenceAnalysis::print(), promoteArguments(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), replaceSwiftErrorOps(), llvm::AAEvaluator::run(), runSCCP(), StackMallocSizeClass(), stripNonValidAttributesFromPrototype(), tryToElideArgumentCopy(), TypeSizeToSizeIndex(), and wrapConstantAsMetadata().
args() [2/2]
iterator_range<const_arg_iterator> llvm::Function::args () const inline
Definition at line 733 of file Function.h.
References llvm::make_range().
back() [1/2]
const BasicBlock& llvm::Function::back () const inline
Definition at line 700 of file Function.h.
Referenced by hasProfileData().
back() [2/2]
BasicBlock& llvm::Function::back () inline
Definition at line 701 of file Function.h.
begin() [1/2]
iterator llvm::Function::begin () inline
Definition at line 691 of file Function.h.
Referenced by llvm::CFGMST< Edge, BBInfo >::buildEdges(), llvm::CloneFunctionInto(), createCast(), llvm::createCodeGenPreparePass(), llvm::createDeadArgHackingPass(), llvm::createLowerSwitchPass(), CreatePrologue(), llvm::createShadowStackGCLoweringPass(), doCallSiteSplitting(), eliminateTailRecursion(), llvm::EliminateUnreachableBlocks(), llvm::PMDataManager::emitInstrCountChangedRemark(), emitSignedInt64(), llvm::CodeExtractor::findInputsOutputs(), getFilename(), getRetComponentType(), llvm::coverage::CoverageMapping::getUniqueSourceFiles(), HandleByValArgument(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::isInlineViable(), isOnlyReachableViaThisEdge(), iterativelySimplifyCFG(), LLVMGetFirstBasicBlock(), LLVMGetLastBasicBlock(), LLVMGetPreviousBasicBlock(), MarkBlocksLiveIn(), mergeEmptyReturnBlocks(), needsFP(), llvm::GraphTraits< BlockFrequencyInfo * >::nodes_begin(), llvm::GraphTraits< Function * >::nodes_begin(), llvm::GraphTraits< const Function * >::nodes_begin(), llvm::LegacyDivergenceAnalysis::print(), runOnFunction(), runPartiallyInlineLibCalls(), scalarizeMaskedCompressStore(), SimplifyFunction(), llvm::sinkRegion(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit().
begin() [2/2]
const_iterator llvm::Function::begin () const inline
Definition at line 692 of file Function.h.
callsFunctionThatReturnsTwice()
bool Function::callsFunctionThatReturnsTwice () const
callsFunctionThatReturnsTwice - Return true if the function has a call to setjmp or other function that gcc recognizes as "returning twice".
Definition at line 1475 of file Function.cpp.
References I, and llvm::instructions().
Referenced by createCallInst(), INITIALIZE_PASS(), markTails(), and llvm::SelectionDAGISel::runOnMachineFunction().
cannotDuplicate()
bool llvm::Function::cannotDuplicate () const inline
Determine if the call cannot be duplicated.
Definition at line 552 of file Function.h.
classof()
static bool llvm::Function::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 791 of file Function.h.
References llvm::tgtok::Bit, C, D, F(), getSubprogram(), llvm::Value::getValueID(), llvm::NullPointerIsDefined(), and llvm::Value::setValueSubclassData().
clearGC()
void Function::clearGC ()
Definition at line 506 of file Function.cpp.
References llvm::LLVMContext::deleteGC(), and llvm::Value::getContext().
Referenced by LLVMSetGC().
copyAttributesFrom()
void Function::copyAttributesFrom (const Function * Src)
copyAttributesFrom - copy all additional attributes (those not needed to create a Function) from the Function Src to this one.
Copy all additional attributes (those not needed to create a Function) from the Function Src to this one.
Definition at line 515 of file Function.cpp.
References llvm::GlobalObject::copyAttributesFrom(), getAttributes(), getCallingConv(), getGC(), getPersonalityFn(), getPrefixData(), getPrologueData(), hasGC(), hasPersonalityFn(), hasPrefixData(), and hasPrologueData().
Referenced by addVariantDeclaration(), canCreateAliasFor(), canCreateThunkFor(), llvm::orc::cloneFunctionDecl(), llvm::CloneFunctionInto(), llvm::CloneModule(), llvm::createDeadArgHackingPass(), doPromotion(), getRetComponentType(), and INITIALIZE_PASS().
Create() [1/3]
static Function* llvm::Function::Create (FunctionType * Ty, LinkageTypes Linkage, unsigned AddrSpace, const Twine & N = "", Module * M = nullptr) inline static
Definition at line 135 of file Function.h.
References N.
Referenced by AddCalls(), addVariantDeclaration(), assureFPCallStub(), canCreateAliasFor(), canCreateThunkFor(), llvm::CloneFunction(), llvm::orc::cloneFunctionDecl(), llvm::CloneModule(), llvm::convertToDeclaration(), createCloneDeclaration(), llvm::createDeadArgHackingPass(), createDevirtTriggerFunc(), llvm::MIRParserImpl::createDummyFunction(), createEmptyFunction(), createFPFnStub(), createGlobalFwdRef(), llvm::createSanitizerCtorAndInitFunctions(), createWrapper(), llvm::createX86RetpolineThunksPass(), doPromotion(), llvm::orc::IRSpeculationLayer::emit(), llvm::CodeExtractor::findInputsOutputs(), llvm::SanitizerStatReport::finish(), forceRenaming(), FunctionNumber(), getMinVisibility(), llvm::Module::getOrInsertFunction(), getRetComponentType(), getSignature(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isKnownTypeIdMember(), LLVMAddFunction(), makeVisible(), needsRuntimeRegistrationOfSectionRange(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), selectJumpTableArmEncoding(), shouldKeepInEntry(), and UpgradeIntrinsicFunction1().
Create() [2/3]
static Function* llvm::Function::Create (FunctionType * Ty, LinkageTypes Linkage, const Twine & N = "", Module * M = nullptr) inline static
Definition at line 142 of file Function.h.
References DECLARE_TRANSPARENT_OPERAND_ACCESSORS, and N.
Create() [3/3]
Function * Function::Create (FunctionType * Ty, LinkageTypes Linkage, const Twine & N, Module & M) static
Creates a new function and attaches it to a module.
Places the function in the program address space as specified by the module's data layout.
Definition at line 235 of file Function.cpp.
References llvm::Module::getDataLayout(), llvm::DataLayout::getProgramAddressSpace(), and N.
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::Function::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
deleteBody()
void llvm::Function::deleteBody () inline
deleteBody - This method deletes the body of the function, and converts the linkage to external.
Definition at line 644 of file Function.h.
Referenced by llvm::createBlockExtractorPass(), llvm::orc::moveFunctionBody(), and llvm::Attributor::run().
doesNoCfCheck()
bool llvm::Function::doesNoCfCheck () const inline
Determine if the function should not perform indirect branch tracking.
Definition at line 541 of file Function.h.
Referenced by IsCallReturnTwice().
doesNotAccessMemory()
bool llvm::Function::doesNotAccessMemory () const inline
Determine if the function does not access memory.
Definition at line 484 of file Function.h.
Referenced by llvm::BasicAAResult::getModRefBehavior(), getOffsetFromIndices(), getUniformBase(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), and setDoesNotAccessMemory().
doesNotFreeMemory()
bool llvm::Function::doesNotFreeMemory () const inline
Determine if the call might deallocate memory.
Definition at line 579 of file Function.h.
Referenced by InstrBreaksNoFree().
doesNotReadMemory()
bool llvm::Function::doesNotReadMemory () const inline
Determine if the function does not access or only writes memory.
Definition at line 500 of file Function.h.
Referenced by llvm::BasicAAResult::getModRefBehavior().
doesNotRecurse()
bool llvm::Function::doesNotRecurse () const inline
Determine if the function is known not to recurse, directly or indirectly.
Definition at line 588 of file Function.h.
Referenced by addNoRecurseAttrs(), addNoRecurseAttrsTopDown(), deduceFunctionAttributeInRPO(), hasAnyNonFlatUseOfReg(), processInternalGlobal(), and setDoesNotRecurse().
doesNotReturn()
bool llvm::Function::doesNotReturn () const inline
Determine if the function cannot return.
Definition at line 533 of file Function.h.
Referenced by runImpl().
doesNotThrow()
bool llvm::Function::doesNotThrow () const inline
Determine if the function cannot unwind.
Definition at line 544 of file Function.h.
Referenced by llvm::EHStreamer::callToNoUnwindFunction(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::doesNotThrow(), llvm::CodeExtractor::findInputsOutputs(), llvm::IRPosition::getAttrs(), llvm::EscapeEnumerator::Next(), runImpl(), setDoesNotThrow(), and llvm::InstCombiner::visitCallInst().
dropAllReferences()
void Function::dropAllReferences ()
dropAllReferences() - This method causes all the subinstructions to "let go" of all references that they are maintaining.
This allows one to 'delete' a whole module at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is deleted for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Since no other object in the module can have references into the body of a function, dropping all references deletes the entire body of the function, including any contained basic blocks.
Definition at line 377 of file Function.cpp.
References llvm::User::dropAllReferences(), llvm::BasicBlock::dropAllReferences(), llvm::Value::getSubclassDataFromValue(), and llvm::Value::setValueSubclassData().
Referenced by llvm::Module::dropAllReferences(), and llvm::InlinerPass::run().
empty()
bool llvm::Function::empty () const inline
Definition at line 697 of file Function.h.
Referenced by llvm::VerifierSupport::DebugInfoCheckFailed(), enableCallSafepoints(), getFirstFunctionBlock(), InsertSafepointPoll(), IsInterestingCmp(), llvm::optimizeGlobalCtorsList(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::IRTranslator::runOnMachineFunction(), stripNonValidDataFromBody(), and llvm::updateIndexWPDForExports().
end() [1/2]
iterator llvm::Function::end () inline
Definition at line 693 of file Function.h.
Referenced by llvm::CFGMST< Edge, BBInfo >::buildEdges(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneFunctionInto(), llvm::cloneLoopWithPreheader(), llvm::createBlockExtractorPass(), createCast(), llvm::createCodeGenPreparePass(), llvm::createLowerSwitchPass(), CreatePrologue(), llvm::createShadowStackGCLoweringPass(), doCallSiteSplitting(), eliminateTailRecursion(), llvm::EliminateUnreachableBlocks(), emitSignedInt64(), fixupLineNumbers(), getRetComponentType(), llvm::coverage::CoverageMapping::getUniqueSourceFiles(), HandleInlinedEHPad(), HandleInlinedLandingPad(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::isInlineViable(), isOnlyReachableViaThisEdge(), iterativelySimplifyCFG(), LLVMGetFirstBasicBlock(), LLVMGetLastBasicBlock(), LLVMGetNextBasicBlock(), mergeEmptyReturnBlocks(), needsFP(), llvm::GraphTraits< BlockFrequencyInfo * >::nodes_end(), llvm::GraphTraits< Function * >::nodes_end(), llvm::GraphTraits< const Function * >::nodes_end(), llvm::peelLoop(), placeSplitBlockCarefully(), llvm::LegacyDivergenceAnalysis::print(), runPartiallyInlineLibCalls(), scalarizeMaskedCompressStore(), SimplifyFunction(), llvm::sinkRegion(), llvm::UnrollRuntimeLoopRemainder(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit().
end() [2/2]
const_iterator llvm::Function::end () const inline
Definition at line 694 of file Function.h.
eraseFromParent()
void Function::eraseFromParent ()
eraseFromParent - This method unlinks 'this' from the containing module and deletes it.
Definition at line 244 of file Function.cpp.
References llvm::Argument::getParent().
Referenced by canCreateAliasFor(), canCreateThunkFor(), createWrapper(), getRetComponentType(), getSignature(), hasProfileData(), INITIALIZE_PASS(), PushArgMD(), llvm::ArgumentPromotionPass::run(), llvm::UnreachableBlockElimPass::run(), llvm::Attributor::run(), stripDeadPrototypes(), StripSymbolNames(), llvm::UpgradeARCRuntime(), llvm::UpgradeCallsToIntrinsic(), and llvm::PredicateInfo::~PredicateInfo().
front() [1/2]
const BasicBlock& llvm::Function::front () const inline
Definition at line 698 of file Function.h.
Referenced by llvm::Interpreter::callFunction(), canCreateThunkFor(), llvm::CloneAndPruneFunctionInto(), llvm::CloneFunctionInto(), llvm::Evaluator::EvaluateFunction(), llvm::GraphTraits< BlockFrequencyInfo * >::getEntryNode(), getFirstFunctionBlock(), getParentPad(), handleEndBlock(), INITIALIZE_PASS(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), instrumentMaskedLoadOrStore(), llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::IntervalIterator(), isOnlyUsedInEntryBlock(), isSafeToPromoteArgument(), llvm::AllocaInst::isStaticAlloca(), markAliveBlocks(), MarkBlocksLiveIn(), prepareICWorklistFromFunction(), promoteSingleBlockAlloca(), runSCCP(), and StackMallocSizeClass().
front() [2/2]
BasicBlock& llvm::Function::front () inline
Definition at line 699 of file Function.h.
getArg()
Argument* llvm::Function::getArg (unsigned i) const inline
Definition at line 724 of file Function.h.
References assert().
Referenced by llvm::IRPosition::getAssociatedArgument(), and llvm::SubsumingPositionIterator::SubsumingPositionIterator().
getAttribute() [1/2]
Attribute llvm::Function::getAttribute (unsigned i, Attribute::AttrKind Kind) const inline
gets the attribute from the list of attributes.
Definition at line 413 of file Function.h.
References llvm::AttributeList::getAttribute().
getAttribute() [2/2]
Attribute llvm::Function::getAttribute (unsigned i, StringRef Kind) const inline
gets the attribute from the list of attributes.
Definition at line 418 of file Function.h.
References llvm::AttributeList::getAttribute().
getAttributes()
AttributeList llvm::Function::getAttributes () const inline
Return the attribute list for this Function.
Definition at line 223 of file Function.h.
Referenced by llvm::Argument::addAttrs(), llvm::analyzeArguments(), annotateAnyAllocSite(), llvm::attributesPermitTailCall(), llvm::TargetLowering::BuildSDIVPow2(), canCreateThunkFor(), llvm::CloneFunctionInto(), llvm::FunctionComparator::compareSignature(), copyAttributesFrom(), createPowWithIntegerExponent(), doPromotion(), EmitCmp(), llvm::XCoreFrameLowering::emitPrologue(), llvm::CodeExtractor::findInputsOutputs(), findUnwindDestinations(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::SystemZRegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::SystemZRegisterInfo::getCallPreservedMask(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), getIntToFPVal(), llvm::ARMTTIImpl::getMemcpyCost(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getOpenCLAlignment(), getRetComponentType(), getSqrtCall(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::Argument::hasByValOrInAllocaAttr(), INITIALIZE_PASS(), insertSinCosCall(), isArgPassedInSGPR(), llvm::AMDGPU::isArgPassedInSGPR(), isLibCallInTailPosition(), isReportingError(), llvm::PPCInstrInfo::isSignOrZeroExtended(), LowerADJUST_TRAMPOLINE(), llvm::AArch64CallLowering::lowerReturn(), llvm::orc::makeStub(), llvm::IRAttributeManifest::manifestAttrs(), maybePrintComdat(), llvm::Argument::onlyReadsMemory(), optimizeDoubleFP(), OptimizeFunctions(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::paramHasAttr(), performXorCombine(), produceCompactUnwindFrame(), promoteArguments(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), RemoveAttribute(), llvm::FunctionLoweringInfo::set(), simplifyDivRem(), useFuncSeen(), and llvm::InstCombiner::visitFDiv().
getBasicBlockList() [1/2]
const BasicBlockListType& llvm::Function::getBasicBlockList () const inline
Get the underlying elements of the Function...
the basic block list is empty for external functions.
Definition at line 668 of file Function.h.
Referenced by AddCalls(), llvm::CloneAndPruneIntoFromInst(), llvm::cloneLoopWithPreheader(), llvm::FunctionComparator::cmpConstants(), llvm::createDeadArgHackingPass(), doPromotion(), llvm::BasicBlock::eraseFromParent(), llvm::CodeExtractor::findInputsOutputs(), getRetComponentType(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::BasicBlock::insertInto(), insertLifetimeMarkersSurroundingCall(), insertUniqueBackedgeBlock(), instrumentMaskedLoadOrStore(), llvm::orc::SpeculateQuery::isStraightLine(), isWrapperOnlyCall(), LLVMInsertExistingBasicBlockAfterInsertBlock(), llvm::BasicBlock::moveAfter(), llvm::BasicBlock::moveBefore(), llvm::orc::BlockFreqQuery::operator()(), llvm::peelLoop(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::BasicBlock::removeFromParent(), llvm::SplitCriticalEdge(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), and llvm::UnrollRuntimeLoopRemainder().
getBasicBlockList() [2/2]
BasicBlockListType& llvm::Function::getBasicBlockList () inline
Definition at line 669 of file Function.h.
getCallingConv()
CallingConv::ID llvm::Function::getCallingConv () const inline
getCallingConv()/setCallingConv(CC) - These method get and set the calling convention of this function.
The enum values for the known calling conventions are defined in CallingConv.h.
Definition at line 212 of file Function.h.
References llvm::CallingConv::MaxID.
Referenced by llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), areCallingConvEligibleForTCO_64SVR4(), AssignProtectedObjSet(), llvm::SIInstrInfo::calculateLDSSpillAddress(), callHasRegMask(), canCreateThunkFor(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::X86Subtarget::classifyGlobalFunctionReference(), combineADDToADDZE(), llvm::FunctionComparator::compareSignature(), computeCalleeSaveRegisterPairs(), copyAttributesFrom(), llvm::createSIWholeQuadModePass(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernel(), llvm::AVRFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), emitXBegin(), llvm::X86FrameLowering::enableShrinkWrapping(), findUnwindDestinations(), getAssignFnsForCC(), getBufferOffsetForMMO(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::AVRRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::SIRegisterInfo::getCalleeSavedRegs(), llvm::SystemZRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::PPCRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::X86RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegsViaCopy(), getDSShaderTypeValue(), getElementByteSizeValue(), llvm::AMDGPUSubtarget::getExplicitKernArgSize(), llvm::AMDGPUSubtarget::getFlatWorkGroupSizes(), getFPOffset(), getFPReg(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::X86RegisterInfo::getGPRsForTailCall(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), llvm::Mangler::getNameWithPrefix(), llvm::X86RegisterInfo::getReservedRegs(), getRsrcReg(), GetScratchRegister(), llvm::TargetFrameLowering::getStackAlignmentSkew(), getSubprogram(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::CallLowering::handleAssignments(), llvm::X86FrameLowering::has128ByteRedZone(), hasAnyNonFlatUseOfReg(), hasChangeableCC(), llvm::ARMTargetLowering::hasStandaloneRem(), INITIALIZE_PASS(), llvm::InlineFunction(), isArgPassedInSGPR(), llvm::AMDGPU::isArgPassedInSGPR(), isCallableFunction(), llvm::TargetRegisterInfo::isCalleeSavedPhysReg(), isCallPromotable(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::isKernelFunction(), llvm::GCNSubtarget::isMesaGfxShader(), llvm::AMDGPUSubtarget::isMesaKernel(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), isSubBorrowChain(), isSupportedType(), llvm::SIInstrInfo::legalizeOperands(), LowerADJUST_TRAMPOLINE(), llvm::AArch64CallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::SITargetLowering::LowerCall(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::MipsCallLowering::lowerReturn(), LowerVACOPY(), MatchingStackOffset(), llvm::SITargetLowering::mayBeEmittedAsTailCall(), maybePrintComdat(), mayTailCallThisCC(), llvm::AMDGPUAAResult::pointsToConstantMemory(), propagateCallAttrsFromCallee(), llvm::Intrinsic::remangleIntrinsicFunction(), reservePrivateMemoryRegs(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::CallLowering::resultsCompatible(), llvm::FunctionLoweringInfo::set(), llvm::AMDGPU::SIModeRegisterDefaults::SIModeRegisterDefaults(), llvm::AArch64TargetLowering::supportSplitCSR(), llvm::PPCTargetLowering::supportSplitCSR(), tryToElideArgumentCopy(), unifyReturnBlockSet(), usePackedStack(), llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
getContext()
LLVMContext & Function::getContext () const
getContext - Return a reference to the LLVMContext associated with this function.
Definition at line 223 of file Function.cpp.
References llvm::Type::getContext(), and llvm::Value::getType().
Referenced by AddAliasScopeMetadata(), llvm::OpenMPIRBuilder::addAttributes(), llvm::Argument::addAttrs(), addBoundsChecking(), addExclusiveRegPair(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::OptimizationRemarkEmitter::allowExtraAnalysis(), llvm::coro::buildCoroutineFrame(), llvm::MachineIRBuilder::buildFConstant(), buildFrameType(), llvm::coro::Shape::buildFrom(), canCreateThunkFor(), CC_RISCV_FastCC(), llvm::CloneFunctionInto(), combineInstructionsOverFunction(), llvm::computeLegalValueVTs(), convertImplicitDefToConstZero(), llvm::createAArch64StackTaggingPass(), llvm::createDwarfEHPass(), createFPFnStub(), createMaskInstrs(), llvm::createMemLibcall(), createMemMoveLoop(), createMemSetLoop(), llvm::createPGOFuncNameMetadata(), CreatePrologue(), createResumeEntryBlock(), llvm::createShadowStackGCLoweringPass(), llvm::X86InstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), doPromotion(), duplicateCPV(), eliminateRecursiveTailCall(), llvm::OptimizationRemarkEmitter::emit(), llvm::PMDataManager::emitInstrCountChangedRemark(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitPostSt(), llvm::RISCVFrameLowering::emitPrologue(), llvm::AArch64RegisterInfo::emitReservedArgRegCallError(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), eraseDeadBBsAndChildren(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), llvm::FastISel::fastEmit_ri_(), fixupLineNumbers(), llvm::AMDGPULibCalls::fold(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::BlockAddress::get(), getAssignFnsForCC(), llvm::IRPosition::getAttrs(), getCallOpcode(), llvm::ScalarEvolution::getContext(), getInsertVecEltOpInfo(), llvm::AMDGPU::getIntegerAttribute(), llvm::AMDGPU::getIntegerPairAttribute(), getMemsetValue(), getOffsetFromIndices(), getRetComponentType(), getSignature(), GetSortedValueDataFromCallTargets(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), getSuccPad(), getUnderlyingObjects(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), getVariantKind(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::CallLowering::handleAssignments(), HandleInlinedEHPad(), hasAnyNonFlatUseOfReg(), hasProfileData(), llvm::SelectionDAG::init(), INITIALIZE_PASS(), insertLifetimeMarkersSurroundingCall(), llvm::MachineOptimizationRemark::isEnabled(), llvm::MachineOptimizationRemarkMissed::isEnabled(), llvm::MachineOptimizationRemarkAnalysis::isEnabled(), llvm::OptimizationRemark::isEnabled(), llvm::OptimizationRemarkMissed::isEnabled(), llvm::OptimizationRemarkAnalysis::isEnabled(), IsInterestingCmp(), llvm::isLibFreeFunction(), IsSafeAndProfitableToMove(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::LegalizerHelper::libcall(), LLVMAddTargetDependentFunctionAttr(), llvm::XCoreInstrInfo::loadImmediate(), llvm::BlockAddress::lookup(), llvm::LegalizerHelper::lower(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), LowerFPToInt(), lowerLoadRelative(), llvm::lowerObjectSizeCall(), llvm::MipsCallLowering::lowerReturn(), makeStatepointExplicitImpl(), MarkBlocksLiveIn(), llvm::OptimizationRemarkEmitter::OptimizationRemarkEmitter(), performMaskedAtomicOp(), prepareForSplit(), llvm::MIPrinter::print(), llvm::MachineInstr::print(), llvm::promoteCall(), llvm::Attributor::registerFunctionSignatureRewrite(), RemoveAttribute(), removeDoneExport(), llvm::ARMTargetLowering::ReplaceNodeResults(), reportIllegalCopy(), llvm::CallLowering::resultsCompatible(), rewrite(), llvm::InlinerPass::run(), llvm::OptimizationRemarkEmitterAnalysis::run(), llvm::legacy::FunctionPassManagerImpl::run(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::ConstantHoistingPass::runImpl(), llvm::LPPassManager::runOnFunction(), llvm::OptimizationRemarkEmitterWrapperPass::runOnFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MachineOptimizationRemarkEmitterPass::runOnMachineFunction(), selectJumpTableArmEncoding(), llvm::FunctionLoweringInfo::set(), setCoroInfo(), llvm::AArch64TTIImpl::shouldConsiderAddressTypePromotion(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::FunctionPass::skipFunction(), llvm::LoopPass::skipLoop(), llvm::RegionPass::skipRegion(), splitRetconCoroutine(), stashEntryDbgValues(), stripNonValidAttributesFromPrototype(), stripNonValidDataFromBody(), unifyReturnBlockSet(), llvm::UpgradeIntrinsicFunction(), UpgradeIntrinsicFunction1(), UpgradePTESTIntrinsic(), WarnSize(), and llvm::LegalizerHelper::widenScalar().
getDereferenceableBytes()
uint64_t llvm::Function::getDereferenceableBytes (unsigned i) const inline
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
Parameters
i AttributeList index, referring to a return value or argument.
Definition at line 459 of file Function.h.
References llvm::AttributeList::getDereferenceableBytes().
getDereferenceableOrNullBytes()
uint64_t llvm::Function::getDereferenceableOrNullBytes (unsigned i) const inline
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
Parameters
i AttributeList index, referring to a return value or argument.
Definition at line 472 of file Function.h.
References llvm::AttributeList::getDereferenceableOrNullBytes().
getEntryBlock() [1/2]
const BasicBlock& llvm::Function::getEntryBlock () const inline
Definition at line 675 of file Function.h.
Referenced by addArgumentAttrsFromCallsites(), llvm::CFGMST< Edge, BBInfo >::buildEdges(), llvm::BranchProbabilityInfo::calculate(), calculateStateNumbersForInvokes(), canCreateThunkFor(), llvm::CloneAndPruneIntoFromInst(), llvm::colorEHFunclets(), llvm::FunctionComparator::compare(), ComputePostOrders(), llvm::createConstantHoistingPass(), llvm::OpenMPIRBuilder::CreateParallel(), CreatePrologue(), llvm::createScalarizerPass(), llvm::createShadowStackGCLoweringPass(), cxxDtorIsEmpty(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), eliminateRecursiveTailCall(), eliminateSwiftError(), eliminateSwiftErrorArgument(), findArgumentCopyElisionCandidates(), llvm::FindFunctionBackedges(), llvm::CodeExtractor::findInputsOutputs(), findLocationForEntrySafepoint(), findTRECandidate(), llvm::FunctionComparator::functionHash(), llvm::IRPosition::getAttrs(), GetCtorAndDtorPriority(), llvm::MemoryDependenceResults::getDependency(), llvm::GraphTraits< Function * >::getEntryNode(), llvm::GraphTraits< const Function * >::getEntryNode(), getFirstNonAllocaInTheEntryBlock(), GetLocation(), getParentPad(), getPredState(), GetRMWLibcall(), getSignature(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), getSuccState(), hasSameExtUse(), INITIALIZE_PASS(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), InsertRootInitializers(), insertSinCosCall(), instrumentMaskedLoadOrStore(), isAtomic(), isColdCallSite(), llvm::CaptureTracker::isDereferenceableOrNull(), isEmptyFunction(), llvm::SelectionDAGBuilder::isExportableFromCurrentBlock(), IsInterestingCmp(), isObjectDereferencedInBlock(), isOnlyReachableViaThisEdge(), llvm::isPotentiallyReachable(), isPromotedInstructionLegal(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isWrapperOnlyCall(), isZero(), maybePrintComdat(), memoryIsNotModifiedBetween(), llvm::MergeBasicBlockIntoOnlyPred(), NegateValue(), prepareForSplit(), llvm::PrepareToSplitEntryBlock(), llvm::JumpThreadingPass::ProcessBlock(), processDbgDeclares(), processInternalGlobal(), promoteMemoryToRegister(), llvm::RegionInfo::recalculate(), relocationViaAlloca(), removeUndefIntroducingPredecessor(), replaceSwiftErrorOps(), llvm::ModuleSanitizerCoveragePass::run(), llvm::ConstantHoistingPass::run(), llvm::GVNHoist::run(), llvm::SLPVectorizerPass::runImpl(), runImpl(), llvm::IRTranslator::runOnMachineFunction(), shouldInstrumentBlock(), shouldKeepInEntry(), llvm::RegionPass::skipRegion(), llvm::fuzzerop::splitBlockDescriptor(), TryToMergeLandingPad(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TypeSizeToSizeIndex(), UpdateAnalysisInformation(), valueDominatesPHI(), and llvm::InstCombiner::visitAllocaInst().
getEntryBlock() [2/2]
BasicBlock& llvm::Function::getEntryBlock () inline
Definition at line 676 of file Function.h.
getEntryCount()
ProfileCount Function::getEntryCount (bool AllowSynthetic = false) const
Get the entry count for this function.
Entry count is the number of times the function was executed. When AllowSynthetic is false, only pgo_data will be returned.
Definition at line 1571 of file Function.cpp.
References llvm::Function::ProfileCount::getInvalid(), llvm::MDNode::getOperand(), llvm::ConstantInt::getValue(), and llvm::APInt::getZExtValue().
Referenced by llvm::BlockFrequencyInfoImplBase::getProfileCountFromFreq(), llvm::InlineFunction(), machine_size_opts_detail::isFunctionColdInCallGraph(), llvm::ProfileSummaryInfo::isFunctionColdInCallGraph(), llvm::ProfileSummaryInfo::isFunctionEntryCold(), llvm::ProfileSummaryInfo::isFunctionEntryHot(), llvm::ProfileSummaryInfo::isFunctionHotInCallGraph(), machine_size_opts_detail::isFunctionHotInCallGraphNthPercentile(), llvm::ProfileSummaryInfo::isFunctionHotInCallGraphNthPercentile(), and llvm::updateProfileCallee().
getFnAttribute() [1/2]
Attribute llvm::Function::getFnAttribute (Attribute::AttrKind Kind) const inline
Return the attribute for the given attribute kind.
Definition at line 333 of file Function.h.
References llvm::AttributeList::FunctionIndex, and getAttribute().
Referenced by AddCalls(), adjustCallerStackProbes(), adjustCallerStackProbeSize(), adjustMinLegalVectorWidth(), adjustNullPointerValidAttr(), llvm::NVPTXTargetLowering::allowUnsafeFPMath(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::TargetTransformInfoImplBase::areFunctionArgsABICompatible(), llvm::TargetTransformInfoImplBase::areInlineCompatible(), llvm::TargetLoweringBase::areJTsAllowed(), llvm::AArch64InstrInfo::buildOutlinedFrame(), CC_RISCV_FastCC(), NoAutoPaddingScope::changeAndComment(), checkFunctionsAttributeConsistency(), llvm::TargetOptions::DisableFramePointerElim(), doesNotGeneratecode(), eliminateTailRecursion(), llvm::AsmPrinter::EmitDebugValue(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::MipsSEFrameLowering::emitPrologue(), foldFPToIntToFP(), getAllocationSize(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), llvm::MachineFunction::getDenormalMode(), getDeoptLowering(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::AMDGPUTargetMachine::getFeatureString(), llvm::AMDGPUTargetMachine::getGPUName(), llvm::AMDGPU::getIntegerAttribute(), llvm::AMDGPU::getIntegerPairAttribute(), getRecipEstimateForFunc(), llvm::X86TargetLowering::getStackProbeSize(), llvm::X86TargetLowering::getStackProbeSymbolName(), getSubOpcode(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), hasUnsafeFPMath(), INITIALIZE_PASS(), isEqual(), llvm::RecurrenceDescriptor::isReductionPHI(), isThumbFunction(), llvm::LoopVectorizationLegality::isUniform(), llvm::AMDGPULibCalls::isUnsafeMath(), llvm::CallLowering::lowerCall(), LowerInterruptReturn(), outliningCandidatesSigningKeyConsensus(), outliningCandidatesSigningScopeConsensus(), llvm::AsmPrinter::recordSled(), runOnFunction(), llvm::StackProtector::runOnFunction(), ShouldSignReturnAddress(), ShouldSignWithAKey(), llvm::AMDGPU::SIModeRegisterDefaults::SIModeRegisterDefaults(), SimplifyNVVMIntrinsic(), llvm::NVPTXTargetLowering::useF32FTZ(), WindowsRequiresStackProbe(), and windowsRequiresStackProbe().
getFnAttribute() [2/2]
Attribute llvm::Function::getFnAttribute (StringRef Kind) const inline
Return the attribute for the given attribute kind.
Definition at line 338 of file Function.h.
References llvm::AttributeList::FunctionIndex, and getAttribute().
getFnStackAlignment()
unsigned llvm::Function::getFnStackAlignment () const inline
Return the stack alignment for the function.
Definition at line 343 of file Function.h.
References llvm::AttributeList::FunctionIndex, and llvm::AttributeList::getStackAlignment().
Referenced by getFnStackAlignment(), and llvm::MachineFunction::MachineFunction().
getFunction()
const Function& llvm::Function::getFunction () const inline
Definition at line 133 of file Function.h.
Referenced by llvm::FunctionComparator::cmpConstants(), llvm::createArgumentPromotionPass(), llvm::createBlockExtractorPass(), llvm::createPGOIndirectCallPromotionLegacyPass(), llvm::AsmPrinter::doFinalization(), llvm::GlobalsAAResult::getModRefBehavior(), INITIALIZE_PASS(), and isPromotedInstructionLegal().
getFunctionType()
FunctionType* llvm::Function::getFunctionType () const inline
Returns the FunctionType for me.
Definition at line 163 of file Function.h.
Referenced by annotateAnyAllocSite(), annotateNonNullAndDereferenceable(), assureFPCallStub(), llvm::Interpreter::callExternalFunction(), llvm::Interpreter::callFunction(), callingConvSupported(), canCreateAliasFor(), canCreateThunkFor(), CC_Lanai32_VarArg(), CC_RISCV(), checkWFRetconPrototype(), llvm::CloneFunction(), llvm::FunctionComparator::compareSignature(), llvm::createDeadArgHackingPass(), createFPFnStub(), llvm::IRBuilder< TargetFolder >::CreateLaunderInvariantGroup(), llvm::IRBuilder< TargetFolder >::CreateStripInvariantGroup(), createWrapper(), doPromotion(), eliminateTailRecursion(), llvm::WebAssemblyAsmPrinter::EmitFunctionBodyStart(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::Evaluator::EvaluateBlock(), forceRenaming(), getAllocationDataForFunction(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), llvm::Evaluator::getFormalParams(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::Mangler::getNameWithPrefix(), getParentPad(), getRetComponentType(), llvm::coro::Shape::getRetconResultTypes(), getSignature(), getSuccPad(), INITIALIZE_PASS(), llvm::InlineFunction(), isCallPromotable(), llvm::CodeExtractor::isEligible(), isKnownTypeIdMember(), llvm::isLegalToPromote(), llvm::isLibFreeFunction(), isReportingError(), lookupFunction(), LowerADJUST_TRAMPOLINE(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), lowerObjCCall(), llvm::orc::makeStub(), maybePrintComdat(), needsFPStubFromParams(), llvm::DiagnosticInfoUnsupported::print(), llvm::promoteCall(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::Intrinsic::remangleIntrinsicFunction(), llvm::DeadArgumentEliminationPass::run(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::CallBase::setCalledFunction(), ShrinkDemandedConstant(), llvm::UpgradeARCRuntime(), UpgradeIntrinsicFunction1(), UpgradePTESTIntrinsic(), UpgradeX86IntrinsicFunction(), UpgradeX86IntrinsicsWith8BitMask(), and whichFPParamVariantNeeded().
getGC()
const std::string & Function::getGC () const
Definition at line 496 of file Function.cpp.
References assert(), llvm::Value::getContext(), and llvm::LLVMContext::getGC().
Referenced by llvm::FunctionComparator::compareSignature(), copyAttributesFrom(), llvm::createShadowStackGCLoweringPass(), llvm::GCModuleInfo::getFunctionInfo(), llvm::InlineFunction(), LLVMGetGC(), maybePrintComdat(), shouldRewriteFunction(), and shouldRewriteStatepointsIn().
getImportGUIDs()
DenseSet< GlobalValue::GUID > Function::getImportGUIDs () const
Returns the set of GUIDs that needs to be imported to the function for sample PGO, to enable the same inlines as the profiled optimized binary.
Definition at line 1593 of file Function.cpp.
References llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert().
getInstructionCount()
unsigned Function::getInstructionCount () const
Returns the number of non-debug IR instructions in this function.
This is equivalent to the sum of the sizes of each basic block contained within this function.
Definition at line 227 of file Function.cpp.
Referenced by llvm::LPPassManager::runOnFunction(), and llvm::FPPassManager::runOnFunction().
getIntrinsicID()
Intrinsic::ID llvm::Function::getIntrinsicID () const inline
getIntrinsicID - This method returns the ID number of the specified function, or Intrinsic::not_intrinsic if the function is not an intrinsic, or if the pointer is null.
This value is always defined to be zero to allow easy checking for whether a function is intrinsic or not. The particular intrinsic functions which correspond to this value are defined in llvm/Intrinsics.h.
Definition at line 193 of file Function.h.
Referenced by llvm::CallGraphNode::addCalledFunction(), addIntrinsicToSummary(), llvm::canConstantFoldCallTo(), computeKnownBitsFromAssume(), llvm::ConstantFoldCall(), llvm::IRBuilder< TargetFolder >::CreateConstrainedFPCall(), CreateGCRelocates(), createPowWithIntegerExponent(), llvm::createShadowStackGCLoweringPass(), llvm::VerifierSupport::DebugInfoCheckFailed(), DeleteBasicBlock(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::AMDGPULibCalls::fold(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), llvm::objcarc::GetFunctionClass(), llvm::getIntrinsicForCallSite(), llvm::IntrinsicInst::getIntrinsicID(), getOffsetFromIndices(), getParentPad(), getScalarIntrinsicDeclaration(), getSignature(), handleBrSelExpect(), handleSwitchExpect(), hasOnlyColdCalls(), INITIALIZE_PASS(), InsertRootInitializers(), isFuncOrArgAttr(), llvm::isInlineViable(), isKnownNonZeroFromAssume(), llvm::ARMTTIImpl::isLoweredToCall(), lowerExpectIntrinsic(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), makeStatepointExplicitImpl(), markAliveBlocks(), optimizeDoubleFP(), llvm::Intrinsic::remangleIntrinsicFunction(), llvm::returnTypeIsEligibleForTailCall(), llvm::LoopDataPrefetchPass::run(), llvm::FastISel::selectInstruction(), simplifyBinaryIntrinsic(), simplifyIntrinsic(), simplifyUnaryIntrinsic(), llvm::UpgradeIntrinsicFunction(), useFuncSeen(), and llvm::Interpreter::visitCallSite().
getParamAlign()
MaybeAlign llvm::Function::getParamAlign (unsigned ArgNo) const inline
Definition at line 446 of file Function.h.
References llvm::AttributeList::getParamAlignment().
Referenced by llvm::Argument::getParamAlign().
getParamAlignment()
unsigned llvm::Function::getParamAlignment (unsigned ArgNo) const inline
Extract the alignment for a call or parameter (0=unknown).
FIXME: Remove this function once transition to Align is over. Use getParamAlign() instead.
Definition at line 440 of file Function.h.
Referenced by llvm::Argument::getParamAlignment(), INITIALIZE_PASS(), and llvm::InlineFunction().
getParamAttribute()
Attribute llvm::Function::getParamAttribute (unsigned ArgNo, Attribute::AttrKind Kind) const inline
gets the specified attribute from the list of attributes.
Definition at line 408 of file Function.h.
References llvm::Intrinsic::getAttributes(), and llvm::AttributeList::getParamAttr().
Referenced by llvm::Argument::getAttribute().
getParamByValType()
Type* llvm::Function::getParamByValType (unsigned ArgNo) const inline
Extract the byval type for a parameter.
Definition at line 451 of file Function.h.
References llvm::AttributeList::getParamByValType(), llvm::Type::getPointerElementType(), and llvm::Intrinsic::getType().
Referenced by llvm::Argument::getParamByValType(), and llvm::promoteCall().
getParamDereferenceableBytes()
uint64_t llvm::Function::getParamDereferenceableBytes (unsigned ArgNo) const inline
Extract the number of dereferenceable bytes for a parameter.
Parameters
ArgNo Index of an argument, with 0 being the first function arg.
Definition at line 465 of file Function.h.
References llvm::AttributeList::getParamDereferenceableBytes().
Referenced by llvm::Argument::getDereferenceableBytes().
getParamDereferenceableOrNullBytes()
uint64_t llvm::Function::getParamDereferenceableOrNullBytes (unsigned ArgNo) const inline
Extract the number of dereferenceable_or_null bytes for a parameter.
Parameters
ArgNo AttributeList ArgNo, referring to an argument.
Definition at line 479 of file Function.h.
References llvm::AttributeList::getParamDereferenceableOrNullBytes().
Referenced by llvm::Argument::getDereferenceableOrNullBytes().
getPersonalityFn()
Constant * Function::getPersonalityFn () const
Get the personality function associated with this function.
Definition at line 1484 of file Function.cpp.
References assert().
Referenced by llvm::WinException::beginFunclet(), llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::canSimplifyInvokeNoUnwind(), llvm::rdf::DataFlowGraph::DefStack::clear_block(), llvm::CloneFunctionInto(), llvm::LoopSafetyInfo::computeBlockColors(), copyAttributesFrom(), createCallInst(), llvm::createObjCARCOptPass(), createPHIsForCMOVsInSinkBB(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitLoweredCatchRet(), llvm::XCoreFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::WinException::endFunclet(), llvm::ARMException::endFunction(), llvm::WinException::endFunction(), llvm::CodeExtractor::extractCodeRegion(), findUnwindDestinations(), llvm::getEHScopeMembership(), getMOVL(), getSEHRegistrationNodeSize(), INITIALIZE_PASS(), llvm::InlineFunction(), isFuncletReturnInstr(), IsInterestingCmp(), isSortedByValueNo(), isUsingScopeBasedEH(), llvm::MachineFunction::MachineFunction(), MarkBlocksLiveIn(), matchPair(), maybePrintComdat(), mergeCleanupPad(), needFuncLabelsForEHOrDebugInfo(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::StackProtector::runOnFunction(), llvm::FunctionLoweringInfo::set(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), and llvm::InstCombiner::visitLandingPadInst().
getPrefixData()
Constant * Function::getPrefixData () const
Get the prefix data associated with this function.
Definition at line 1494 of file Function.cpp.
References assert().
Referenced by copyAttributesFrom(), llvm::AsmPrinter::EmitDebugValue(), and maybePrintComdat().
getPrologueData()
Constant * Function::getPrologueData () const
Get the prologue data associated with this function.
Definition at line 1504 of file Function.cpp.
References assert().
Referenced by copyAttributesFrom(), llvm::AsmPrinter::EmitDebugValue(), and maybePrintComdat().
getReturnType()
Type* llvm::Function::getReturnType () const inline
Returns the type of the ret val.
Definition at line 168 of file Function.h.
Referenced by assureFPCallStub(), llvm::Interpreter::callFunction(), callingConvSupported(), canCreateThunkFor(), CC_RISCV_FastCC(), llvm::ConstantFoldCall(), copyMustTailReturn(), llvm::IRBuilder< TargetFolder >::CreateLaunderInvariantGroup(), llvm::IRBuilder< TargetFolder >::CreateStripInvariantGroup(), explicifyGuards(), FindPredecessorAutoreleaseWithSafePath(), findUnwindDestinations(), llvm::IRPosition::getAttrs(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), getFunctionReturns(), getParentPad(), getRetComponentType(), llvm::MipsCCState::getSpecialCallingConvForCallee(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), llvm::isLegalToPromote(), llvm::ARMTTIImpl::isLoweredToCall(), isReturnNonNull(), llvm::PPCInstrInfo::isSignOrZeroExtended(), lowerGuardIntrinsic(), llvm::BPFTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::makeGuardControlFlowExplicit(), llvm::orc::makeStub(), MatchingStackOffset(), maybePrintComdat(), needsFPFromSig(), needsFPReturnHelper(), NumRetVals(), llvm::promoteCall(), PropagateConstantReturn(), llvm::runIPSCCP(), llvm::FastISel::selectStackmap(), llvm::FunctionLoweringInfo::set(), setRetNonNull(), shouldKeepInEntry(), simplifyBinaryIntrinsic(), simplifyIntrinsic(), splitRetconCoroutine(), stripNonValidAttributesFromPrototype(), tryToElideArgumentCopy(), unifyReturnBlockSet(), and UpgradeIntrinsicFunction1().
getSectionPrefix()
Optional< StringRef > Function::getSectionPrefix () const
Get the section prefix for this function.
Definition at line 1611 of file Function.cpp.
References assert(), and llvm::None.
Referenced by callsShareTOCBase().
getSublistAccess()
static BasicBlockListType Function::* llvm::Function::getSublistAccess (BasicBlock *) inline static
Definition at line 671 of file Function.h.
getSubprogram()
DISubprogram * Function::getSubprogram () const
Get the attached subprogram.
Calls getMetadata() with LLVMContext::MD_dbg and casts the result to DISubprogram.
Definition at line 1525 of file Metadata.cpp.
Referenced by addDiscriminators(), llvm::BTFDebug::beginFunctionImpl(), llvm::DwarfDebug::beginFunctionImpl(), llvm::BTFDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), canCreateThunkFor(), llvm::CloneFunction(), llvm::CloneFunctionInto(), collectCallSiteParameters(), collectRegDefs(), CreatePrologue(), doPromotion(), llvm::DwarfDebug::emitInitialLocDirective(), llvm::CodeViewDebug::endFunctionImpl(), llvm::DwarfDebug::endFunctionImpl(), llvm::CodeExtractor::extractCodeRegion(), llvm::sampleprof::FunctionSamples::findInlinedFunctions(), GetSortedValueDataFromCallTargets(), giveUpWithRemarks(), hasDebugInfo(), llvm::LexicalScopes::initialize(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), llvm::BTFDebug::InstLower(), performSink(), processDbgDeclares(), llvm::Attributor::registerFunctionSignatureRewrite(), removeDebugValues(), runOnFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), shouldKeepInEntry(), llvm::DISubprogram::splitFlags(), and stashEntryDbgValues().
getValueSymbolTable() [1/2]
ValueSymbolTable* llvm::Function::getValueSymbolTable () inline
getSymbolTable() - Return the symbol table if any, otherwise nullptr.
Definition at line 683 of file Function.h.
Referenced by emitSignedInt64(), FunctionNumber(), llvm::MIRParserImpl::initializeFrameInfo(), parseGlobalValue(), parseIRValue(), and toString().
getValueSymbolTable() [2/2]
const ValueSymbolTable* llvm::Function::getValueSymbolTable () const inline
Definition at line 684 of file Function.h.
hasAddressTaken()
bool Function::hasAddressTaken (const User ** PutOffender = nullptr) const
hasAddressTaken - returns true if there are any uses of this function other than direct calls or invokes to it, or blockaddress expressions.
hasAddressTaken - returns true if there are any uses of this function other than direct calls or invokes to it.
Optionally passes back an offending user for diagnostic purposes.
Definition at line 1439 of file Function.cpp.
References llvm::dyn_cast(), and llvm::Value::uses().
Referenced by llvm::canRenameComdatFunc(), llvm::canTrackArgumentsInterprocedurally(), llvm::createDeadArgHackingPass(), hasOnlyColdCalls(), hasProfileData(), INITIALIZE_PASS(), IsCallReturnTwice(), llvm::TargetFrameLowering::isSafeForNoCSROpt(), OptimizeFunctions(), selectJumpTableArmEncoding(), and shouldRecordFunctionAddr().
hasAttribute()
bool llvm::Function::hasAttribute (unsigned i, Attribute::AttrKind Kind) const inline
check if an attributes is in the list of attributes.
Definition at line 398 of file Function.h.
References llvm::Intrinsic::getAttributes(), and llvm::AttributeList::hasAttribute().
Referenced by setRetDoesNotAlias(), and setRetNonNull().
hasFnAttribute() [1/2]
bool llvm::Function::hasFnAttribute (Attribute::AttrKind Kind) const inline
Return true if the function has the attribute.
Definition at line 323 of file Function.h.
References llvm::AttributeList::hasFnAttribute().
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo(), addForcedAttributes(), adjustCallerSSPLevel(), adjustCallerStackProbes(), adjustCallerStackProbeSize(), adjustMinLegalVectorWidth(), llvm::NVPTXTargetLowering::allowUnsafeFPMath(), allPredecessorsComeFromSameSource(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::buildModuleSummaryIndex(), llvm::AArch64InstrInfo::buildOutlinedFrame(), calculateSetFPREG(), llvm::AArch64TargetLowering::canMergeStoresTo(), llvm::X86TargetLowering::canMergeStoresTo(), llvm::TargetRegisterInfo::canRealignStack(), llvm::canTrackReturnsInterprocedurally(), canTransformToMemCmp(), llvm::AArch64FrameLowering::canUseRedZone(), CC_RISCV_FastCC(), NoAutoPaddingScope::changeAndComment(), checkNumAlignedDPRCS2Regs(), llvm::X86Subtarget::classifyGlobalFunctionReference(), combineStore(), computeCalleeSaveRegisterPairs(), llvm::createAMDGPUFunctionInliningPass(), llvm::createDeadArgHackingPass(), llvm::createLoadStoreVectorizerPass(), llvm::createSampleProfileLoaderPass(), llvm::createSIWholeQuadModePass(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::TargetOptions::DisableFramePointerElim(), doesNotGeneratecode(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::AsmPrinter::EmitDebugValue(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), EmitNop(), emitPostSt(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::ARMFrameLowering::enableCalleeSaveSkip(), llvm::TargetFrameLowering::enableCalleeSaveSkip(), llvm::X86FrameLowering::enableShrinkWrapping(), EqualityPropUnSafe(), findStackProtectorIntrinsic(), fixupLineNumbers(), FoldTwoEntryPHINode(), get64BitArgumentXMMs(), llvm::RISCVRegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), getCallOpcode(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::Attributor::getDataLayout(), getDeoptLowering(), llvm::ARMTargetLowering::getExceptionSelectorRegister(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), getFnStackAlignment(), llvm::AArch64FrameLowering::getFrameIndexReference(), llvm::getInlineCost(), llvm::MemoryDependenceResults::getLoadLoadClobberFullWidthSize(), llvm::GCNSubtarget::getMaxNumSGPRs(), llvm::GCNSubtarget::getMaxNumVGPRs(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::MipsTargetLowering::getOpndList(), llvm::AArch64InstrInfo::getOutliningCandidateInfo(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::AArch64RegisterInfo::getReservedRegs(), getRetComponentType(), llvm::MipsCCState::getSpecialCallingConvForCallee(), llvm::X86TargetLowering::getStackProbeSize(), llvm::X86TargetLowering::getStackProbeSymbolName(), getSubOpcode(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), getVectorSHLImm(), llvm::AMDGPUSubtarget::getWavesPerEU(), giveUpWithRemarks(), handleAttr(), llvm::X86FrameLowering::has128ByteRedZone(), llvm::HexagonFrameLowering::hasFP(), hasProfileData(), hasReturnsTwiceAttr(), llvm::ARMTargetLowering::hasStandaloneRem(), hasVulnerableLoad(), INITIALIZE_PASS(), llvm::AArch64TargetLowering::insertCopiesSplitCSR(), llvm::PPCTargetLowering::insertCopiesSplitCSR(), insertCSRRestores(), instrumentMaskedLoadOrStore(), isAtomic(), llvm::ProfileSummaryInfo::isFunctionEntryCold(), llvm::isInlineViable(), llvm::X86TargetLowering::isIntDivCheap(), llvm::lowertypetests::isJumpTableCanonical(), llvm::PPCTargetLowering::isLegalAddressingMode(), isNoReturnDef(), llvm::TargetFrameLowering::isSafeForNoCSROpt(), isSortedByValueNo(), isSubBorrowChain(), isWrapperOnlyCall(), llvm::MipsSEInstrInfo::loadRegFromStack(), LowerInterruptReturn(), LowerRotate(), llvm::MachineFunction::MachineFunction(), MatchingStackOffset(), maybeEndlessLoop(), mayLoopAccessLocation(), mayTailCallThisCC(), llvm::mustSuppressSpeculation(), llvm::PPCFrameLowering::needsFP(), llvm::WebAssemblyFrameLowering::needsPrologForEH(), llvm::TargetRegisterInfo::needsStackRealignment(), OptimizeFunctions(), outliningCandidatesSigningKeyConsensus(), outliningCandidatesSigningScopeConsensus(), Passv64i1ArgInRegs(), performBRCONDCombine(), PGOMemOPSizeOptImpl(), postDominates(), promoteArguments(), PropagateConstantReturn(), llvm::AsmPrinter::recordSled(), llvm::LegacyInlinerBase::removeDeadFunctions(), removeUseSoftFloat(), replaceDevirtTrigger(), llvm::X86TargetLowering::ReplaceNodeResults(), reportLoadElim(), RetagMask(), llvm::LoadStoreVectorizerPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::SLPVectorizerPass::runImpl(), runImpl(), llvm::IRBuilderBase::setConstrainedFPFunctionAttr(), setDoesNotFreeMemory(), setNonLazyBind(), llvm::AsmPrinter::SetupMachineFunction(), llvm::TargetMachine::shouldAssumeDSOLocal(), shouldRecordFunctionAddr(), ShouldSignReturnAddress(), ShouldSignWithAKey(), llvm::MachineFunction::shouldSplitStack(), ShrinkLoadReplaceStoreWithStore(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), stashEntryDbgValues(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64TargetLowering::supportSplitCSR(), llvm::PPCTargetLowering::supportSplitCSR(), TypeSizeToSizeIndex(), UnpackFromArgumentSlot(), llvm::NVPTXTargetLowering::useF32FTZ(), usePackedStack(), WindowsRequiresStackProbe(), and windowsRequiresStackProbe().
hasFnAttribute() [2/2]
bool llvm::Function::hasFnAttribute (StringRef Kind) const inline
Return true if the function has the attribute.
Definition at line 328 of file Function.h.
References llvm::AttributeList::hasFnAttribute().
hasGC()
bool llvm::Function::hasGC () const inline
hasGC/getGC/setGC/clearGC - The name of the garbage collection algorithm to use during code generation.
Definition at line 354 of file Function.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::FunctionComparator::compareSignature(), copyAttributesFrom(), llvm::createGCInfoPrinter(), llvm::createShadowStackGCLoweringPass(), FixedPointIntrinsicToOpcode(), llvm::GCModuleInfo::getFunctionInfo(), getParentPad(), INITIALIZE_PASS(), llvm::InlineFunction(), InsertRootInitializers(), LLVMGetGC(), maybePrintComdat(), llvm::SelectionDAGISel::runOnMachineFunction(), shouldRewriteFunction(), and shouldRewriteStatepointsIn().
hasLazyArguments()
bool llvm::Function::hasLazyArguments () const inline
hasLazyArguments/CheckLazyArguments - The argument list of a function is built on demand, so that the list isn't allocated until the first client needs it.
The hasLazyArguments predicate returns true if the arg list hasn't been set up yet.
Definition at line 104 of file Function.h.
References N.
Referenced by stealArgumentListFrom().
hasMinSize()
bool llvm::Function::hasMinSize () const inline
Optimize this function for minimum size (-Oz).
Definition at line 630 of file Function.h.
Referenced by combineADDToADDZE(), combineFMinNumFMaxNum(), combineInstructionsOverFunction(), combineMul(), llvm::createBreakFalseDeps(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), EmitCmp(), emitConstantSizeRepmov(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ARMSubtarget::getGPRAllocationOrder(), getImmedFromMO(), llvm::ARMTTIImpl::getMemcpyCost(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::ARMSubtarget::ignoreCSRForAllocationOrder(), INITIALIZE_PASS(), InsertBitToMaskVector(), isMinSize(), isOptSize(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), performMaskedAtomicOp(), reduceVMULWidth(), llvm::ARMAsmPrinter::runOnMachineFunction(), scaleCaseProbality(), llvm::RISCVTargetLowering::shouldExpandShift(), llvm::AArch64TargetLowering::shouldExpandShift(), llvm::X86TargetLowering::shouldExpandShift(), shouldLowerMemFuncForSize(), llvm::AArch64InstrInfo::shouldOutlineFromFunctionByDefault(), and splitStores().
hasOptNone()
bool llvm::Function::hasOptNone () const inline
Do not optimize this function (-O0).
Definition at line 627 of file Function.h.
Referenced by llvm::CodeViewDebug::beginFunctionImpl(), llvm::createAArch64StackTaggingPass(), llvm::getInlineCost(), isOptNone(), llvm::WarnMissedTransformationsPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::InlinerPass::run(), runImpl(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::FunctionPass::skipFunction(), llvm::LoopPass::skipLoop(), and llvm::RegionPass::skipRegion().
hasOptSize()
bool llvm::Function::hasOptSize () const inline
Optimize this function for size (-Os) or minimum size (-Oz).
Definition at line 633 of file Function.h.
Referenced by llvm::CodeViewDebug::beginFunctionImpl(), combineFMA(), combineFMADDSUB(), combineReductionToHorizontal(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::createCodeGenPreparePass(), llvm::createX86FixupBWInsts(), llvm::createX86PadShortFunctions(), deleteDeadInstruction(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::gatherUnrollingPreferences(), getLayoutSuccessorProbThreshold(), getScalarEpilogueLowering(), llvm::ARMTTIImpl::getUnrollingPreferences(), insertDeleteInstructions(), isLEA(), isOptSize(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), isReportingError(), llvm::TargetLoweringBase::isSuitableForJumpTable(), ProfitableToMerge(), llvm::ARMAsmPrinter::runOnMachineFunction(), salvageDebugInfoFromEmptyBlock(), llvm::ARMTTIImpl::shouldFavorBackedgeIndex(), shouldLowerMemFuncForSize(), llvm::FastISel::shouldOptForSize(), llvm::SelectionDAG::shouldOptForSize(), llvm::TailDuplicator::shouldTailDuplicate(), tryToUnrollLoop(), and UpdateCPSRUse().
hasParamAttribute()
bool llvm::Function::hasParamAttribute (unsigned ArgNo, Attribute::AttrKind Kind) const inline
check if an attributes is in the list of attributes.
Definition at line 403 of file Function.h.
References llvm::Intrinsic::getAttributes(), and llvm::AttributeList::hasParamAttribute().
Referenced by llvm::IRPosition::getAttrs(), llvm::Argument::hasAttribute(), llvm::Argument::hasSwiftErrorAttr(), llvm::Argument::hasSwiftSelfAttr(), llvm::AMDGPUAAResult::pointsToConstantMemory(), setDoesNotAlias(), setDoesNotCapture(), setOnlyReadsMemory(), and setReturnedArg().
hasPersonalityFn()
bool llvm::Function::hasPersonalityFn () const inline
Check whether this function has a personality function.
Definition at line 743 of file Function.h.
Referenced by appendEndToFunction(), llvm::WinException::beginFunclet(), llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::rdf::DataFlowGraph::DefStack::clear_block(), llvm::CloneFunctionInto(), llvm::LoopSafetyInfo::computeBlockColors(), copyAttributesFrom(), createCallInst(), llvm::createObjCARCOptPass(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::WinException::endFunclet(), llvm::ARMException::endFunction(), llvm::WinException::endFunction(), eraseDeadBBsAndChildren(), llvm::CodeExtractor::extractCodeRegion(), llvm::IRPosition::getAttrs(), getMOVL(), getParentPad(), getSEHRegistrationNodeSize(), INITIALIZE_PASS(), llvm::InlineFunction(), IsInterestingCmp(), isUsingScopeBasedEH(), llvm::MachineFunction::MachineFunction(), maybePrintComdat(), needFuncLabelsForEHOrDebugInfo(), llvm::WebAssemblyFrameLowering::needsPrologForEH(), recoverFramePointer(), llvm::StackProtector::runOnFunction(), and llvm::FunctionLoweringInfo::set().
hasPrefixData()
bool llvm::Function::hasPrefixData () const inline
Check whether this function has prefix data.
Definition at line 752 of file Function.h.
Referenced by copyAttributesFrom(), llvm::AsmPrinter::EmitDebugValue(), and maybePrintComdat().
hasProfileData()
bool llvm::Function::hasProfileData (bool IncludeSynthetic = false) const inline
Return true if the function is annotated with profile data.
Presence of entry counts from a profile run implies the function has profile annotations. If IncludeSynthetic is false, only return true when the profile data is real.
Definition at line 308 of file Function.h.
References llvm::Function::ProfileCount::hasValue(), and llvm::cl::Prefix.
Referenced by llvm::buildModuleSummaryIndex(), llvm::computePeelCount(), llvm::computeUnrollCount(), getLayoutSuccessorProbThreshold(), hasProfileData(), llvm::ProfileSummaryInfo::isColdCallSite(), LoopIsOuterMostWithPredecessor(), llvm::JumpThreadingPass::run(), sinkLoopInvariantInstructions(), updatePredecessorProfileMetadata(), and writeTypeIdCompatibleVtableSummaryRecord().
hasPrologueData()
bool llvm::Function::hasPrologueData () const inline
Check whether this function has prologue data.
Definition at line 761 of file Function.h.
References print().
Referenced by copyAttributesFrom(), llvm::AsmPrinter::EmitDebugValue(), and maybePrintComdat().
hasStructRetAttr()
bool llvm::Function::hasStructRetAttr () const inline
Determine if the function returns a structure through first or second pointer argument.
Definition at line 611 of file Function.h.
References llvm::AttributeList::hasParamAttribute().
Referenced by AnalyzeReturnValues(), CC_Lanai32_VarArg(), llvm::ARMTargetLowering::CCAssignFnForReturn(), getMOVL(), llvm::Mangler::getNameWithPrefix(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::BPFTargetLowering::LowerOperation(), llvm::SparcTargetLowering::LowerReturn_32(), and UnpackFromArgumentSlot().
hasUWTable()
bool llvm::Function::hasUWTable () const inline
True if the ABI mandates (or the user requested) that this function be in a unwind table.
Definition at line 597 of file Function.h.
Referenced by llvm::CodeExtractor::findInputsOutputs().
isConvergent()
bool llvm::Function::isConvergent () const inline
Determine if the call is convergent.
Definition at line 560 of file Function.h.
References llvm::MCID::Convergent.
isDebugInfoForProfiling()
bool Function::isDebugInfoForProfiling () const
Returns true if we should emit debug info for profiling.
Definition at line 1529 of file Metadata.cpp.
References getSubprogram().
Referenced by llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
isDefTriviallyDead()
bool Function::isDefTriviallyDead () const
isDefTriviallyDead - Return true if it is trivially safe to remove this function definition from the module (because it isn't externally visible, does not have its address taken, and has no callers).
To make this more accurate, call removeDeadConstantUsers first.
Definition at line 1459 of file Function.cpp.
References llvm::Value::users().
Referenced by optimizeGlobalsInModule(), llvm::LegacyInlinerBase::removeDeadFunctions(), and llvm::AlwaysInlinerPass::run().
isIntrinsic()
bool llvm::Function::isIntrinsic () const inline
isIntrinsic - Returns true if the function's name starts with "llvm.".
It's possible for this function to return true while getIntrinsicID() returns Intrinsic::not_intrinsic!
Definition at line 198 of file Function.h.
References Name.
Referenced by llvm::CallGraphNode::addCalledFunction(), llvm::CloneAndPruneIntoFromInst(), DeleteBasicBlock(), llvm::getIntrinsicForCallSite(), llvm::TargetLibraryInfoImpl::getLibFunc(), getOffsetFromIndices(), llvm::Module::getOrInsertFunction(), getParameterABIAttributes(), getParentPad(), getRetComponentType(), INITIALIZE_PASS(), llvm::SlotTracker::initializeIndexIfNeeded(), llvm::TargetTransformInfoImplBase::isLoweredToCall(), llvm::ARMTTIImpl::isLoweredToCall(), isReferencingMDNode(), and optimizeDoubleFP().
isMaterializable()
bool llvm::Function::isMaterializable () const inline
Definition at line 178 of file Function.h.
Referenced by maybePrintComdat().
isSpeculatable()
bool llvm::Function::isSpeculatable () const inline
Determine if the call has sideeffects.
Definition at line 571 of file Function.h.
isVarArg()
bool llvm::Function::isVarArg () const inline
isVarArg - Return true if this function takes a variable number of arguments.
Definition at line 176 of file Function.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SystemZFrameLowering::assignCalleeSavedSpillSlots(), canCreateThunkFor(), combineADDToADDZE(), llvm::FunctionComparator::compareSignature(), createCallInst(), llvm::XCoreFunctionInfo::createLRSpillSlot(), createWrapper(), llvm::SystemZFrameLowering::determineCalleeSaves(), llvm::XCoreFrameLowering::determineCalleeSaves(), determinePointerReadAttrs(), llvm::ARCFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitPrologue(), llvm::CodeExtractor::findInputsOutputs(), findUnwindDestinations(), llvm::FunctionComparator::functionHash(), llvm::AMDGPULibFunc::getFunction(), llvm::AMDGPULibFunc::getOrInsertFunction(), llvm::CallLowering::handleAssignments(), hasOnlyColdCalls(), INITIALIZE_PASS(), llvm::isLegalToPromote(), isSupportedType(), lookupFunction(), LowerADJUST_TRAMPOLINE(), llvm::X86CallLowering::lowerFormalArguments(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::MipsCallLowering::lowerReturn(), OptimizeFunctions(), promoteArguments(), PropagateConstantsIntoArguments(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::IRTranslator::runOnMachineFunction(), llvm::FunctionLoweringInfo::set(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), tryToElideArgumentCopy(), and usePackedStack().
lookupIntrinsicID()
Intrinsic::ID Function::lookupIntrinsicID (StringRef Name) static
This does the actual lookup of an intrinsic ID which matches the given function name.
Definition at line 565 of file Function.cpp.
References assert(), llvm::ArrayRef< T >::data(), findTargetSubtable(), IntrinsicNameTable, llvm::Intrinsic::isOverloaded(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), llvm::Intrinsic::not_intrinsic, and llvm::StringRef::size().
Referenced by LLVMLookupIntrinsicID(), and parseGlobalValue().
needsUnwindTableEntry()
bool llvm::Function::needsUnwindTableEntry () const inline
True if this function needs an unwind table.
Definition at line 605 of file Function.h.
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::ARMException::endFunction(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), llvm::AsmPrinter::needsCFIMoves(), llvm::MachineFunction::needsFrameMoves(), llvm::AsmPrinter::needsSEHMoves(), and needsWinCFI().
nullPointerIsDefined()
bool Function::nullPointerIsDefined () const
Check if null pointer dereferencing is considered undefined behavior for the function.
Return value: false => null pointer dereference is undefined. Return value: true => null pointer dereference is not undefined.
Definition at line 1622 of file Function.cpp.
Referenced by adjustNullPointerValidAttr(), llvm::getInlineCost(), llvm::NullPointerIsDefined(), and llvm::PointerMayBeCaptured().
onlyAccessesArgMemory()
bool llvm::Function::onlyAccessesArgMemory () const inline
Determine if the call can access memmory only using pointers based on its arguments.
Definition at line 509 of file Function.h.
Referenced by llvm::BasicAAResult::getModRefBehavior(), and setOnlyAccessesArgMemory().
onlyAccessesInaccessibleMemOrArgMem()
bool llvm::Function::onlyAccessesInaccessibleMemOrArgMem () const inline
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
Definition at line 525 of file Function.h.
Referenced by llvm::BasicAAResult::getModRefBehavior().
onlyAccessesInaccessibleMemory()
bool llvm::Function::onlyAccessesInaccessibleMemory () const inline
Determine if the function may only access memory that is inaccessible from the IR.
Definition at line 516 of file Function.h.
Referenced by llvm::BasicAAResult::getModRefBehavior().
onlyReadsMemory()
bool llvm::Function::onlyReadsMemory () const inline
Determine if the function does not access or only reads memory.
Definition at line 492 of file Function.h.
Referenced by llvm::IRPosition::getAttrs(), llvm::BasicAAResult::getModRefBehavior(), getUniformBase(), HandleByValArgument(), PropagateConstantsIntoArguments(), and setOnlyReadsMemory().
operator=()
void llvm::Function::operator= (const Function &) delete
print()
void Function::print (raw_ostream & OS, AssemblyAnnotationWriter * AAW = nullptr, bool ShouldPreserveUseListOrder = false, bool IsForDebug = false) const
Print the function to an output stream with an optional AssemblyAnnotationWriter.
Definition at line 4222 of file AsmWriter.cpp.
References getParent(), and llvm::RISCVFenceField::W.
Referenced by intersect(), and isMustExecuteIn().
recalculateIntrinsicID()
void Function::recalculateIntrinsicID ()
Recalculate the ID for this function if it is an Intrinsic defined in llvm/Intrinsics.h.
Sets the intrinsic ID to Intrinsic::not_intrinsic if the name of this function does not match an intrinsic in that header. Note, this method does not need to be called directly, as it is called from Value::setName() whenever the name of this function changes.
Definition at line 585 of file Function.cpp.
References llvm::Value::getName(), Name, llvm::Intrinsic::not_intrinsic, and llvm::StringRef::startswith().
removeAttribute() [1/2]
void Function::removeAttribute (unsigned i, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
Definition at line 435 of file Function.cpp.
References llvm::Intrinsic::getAttributes(), llvm::Value::getContext(), and llvm::AttributeList::removeAttribute().
Referenced by runOnFunction(), and splitRetconCoroutine().
removeAttribute() [2/2]
void Function::removeAttribute (unsigned i, StringRef Kind)
removes the attribute from the list of attributes.
Definition at line 441 of file Function.cpp.
References llvm::Intrinsic::getAttributes(), llvm::Value::getContext(), and llvm::AttributeList::removeAttribute().
removeAttributes()
void Function::removeAttributes (unsigned i, const AttrBuilder & Attrs)
removes the attributes from the list of attributes.
Definition at line 447 of file Function.cpp.
References llvm::Intrinsic::getAttributes(), llvm::Value::getContext(), and llvm::AttributeList::removeAttributes().
Referenced by adjustCallerSSPLevel(), CreateVarArgHelper(), INITIALIZE_PASS(), and removeUseSoftFloat().
removeFnAttr() [1/2]
void llvm::Function::removeFnAttr (Attribute::AttrKind Kind) inline
Remove function attributes from this function.
Definition at line 245 of file Function.h.
References llvm::AttributeList::FunctionIndex.
Referenced by adjustMinLegalVectorWidth(), llvm::IRPosition::getAttrs(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), and splitRetconCoroutine().
removeFnAttr() [2/2]
void llvm::Function::removeFnAttr (StringRef Kind) inline
Remove function attribute from this function.
Definition at line 250 of file Function.h.
References llvm::AttributeList::FunctionIndex, and llvm::Intrinsic::getAttributes().
removeFromParent()
void Function::removeFromParent ()
removeFromParent - This method unlinks 'this' from the containing module, but does not delete it.
Definition at line 240 of file Function.cpp.
References llvm::Argument::getParent().
removeParamAttr() [1/2]
void Function::removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
Definition at line 453 of file Function.cpp.
References llvm::Intrinsic::getAttributes(), llvm::Value::getContext(), and llvm::AttributeList::removeParamAttribute().
Referenced by llvm::Argument::removeAttr().
removeParamAttr() [2/2]
void Function::removeParamAttr (unsigned ArgNo, StringRef Kind)
removes the attribute from the list of attributes.
Definition at line 459 of file Function.cpp.
References llvm::Intrinsic::getAttributes(), llvm::Value::getContext(), and llvm::AttributeList::removeParamAttribute().
removeParamAttrs()
void Function::removeParamAttrs (unsigned ArgNo, const AttrBuilder & Attrs)
removes the attribute from the list of attributes.
Definition at line 465 of file Function.cpp.
References llvm::Intrinsic::getAttributes(), llvm::Value::getContext(), and llvm::AttributeList::removeParamAttributes().
returnDoesNotAlias()
bool llvm::Function::returnDoesNotAlias () const inline
Determine if the parameter or return value is marked with NoAlias attribute.
Definition at line 618 of file Function.h.
References llvm::AttributeList::hasAttribute(), llvm::NoAlias, and llvm::AttributeList::ReturnIndex.
Referenced by llvm::buildModuleSummaryIndex().
setAttributes()
void llvm::Function::setAttributes (AttributeList Attrs) inline
Set the attribute list for this Function.
Definition at line 226 of file Function.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::Argument::addAttrs(), llvm::CloneFunctionInto(), FunctionNumber(), llvm::Module::getOrInsertFunction(), getRetComponentType(), INITIALIZE_PASS(), llvm::IRAttributeManifest::manifestAttrs(), RemoveAttribute(), and llvm::UpgradeIntrinsicFunction().
setCallingConv()
void llvm::Function::setCallingConv (CallingConv::ID CC) inline
Definition at line 216 of file Function.h.
References assert(), and llvm::CallingConv::MaxID.
Referenced by explicifyGuards(), FunctionNumber(), hasProfileData(), llvm::InlineFunction(), lowerGuardIntrinsic(), OptimizeFunctions(), and llvm::Intrinsic::remangleIntrinsicFunction().
setCannotDuplicate()
void llvm::Function::setCannotDuplicate () inline
Definition at line 555 of file Function.h.
setConvergent()
void llvm::Function::setConvergent () inline
Definition at line 563 of file Function.h.
References llvm::MCID::Convergent.
setDoesNotAccessMemory()
void llvm::Function::setDoesNotAccessMemory () inline
Definition at line 487 of file Function.h.
Referenced by setDoesNotAccessMemory().
setDoesNotFreeMemory()
void llvm::Function::setDoesNotFreeMemory () inline
Definition at line 582 of file Function.h.
setDoesNotReadMemory()
void llvm::Function::setDoesNotReadMemory () inline
Definition at line 503 of file Function.h.
setDoesNotRecurse()
void llvm::Function::setDoesNotRecurse () inline
Definition at line 591 of file Function.h.
Referenced by setDoesNotRecurse().
setDoesNotReturn()
void llvm::Function::setDoesNotReturn () inline
Definition at line 536 of file Function.h.
setDoesNotThrow()
void llvm::Function::setDoesNotThrow () inline
Definition at line 547 of file Function.h.
Referenced by llvm::CodeExtractor::findInputsOutputs(), getSignature(), and setDoesNotThrow().
setEntryCount() [1/2]
void Function::setEntryCount (ProfileCount Count, const DenseSet< GlobalValue::GUID > * Imports = nullptr)
Set the entry count for this function.
Entry count is the number of times this function was executed based on pgo data. Imports points to a set of GUIDs that needs to be imported by the function for sample PGO, to enable the same inlines as the profiled optimized binary.
Definition at line 1548 of file Function.cpp.
References assert(), llvm::MDBuilder::createFunctionEntryCount(), llvm::Value::getContext(), llvm::Function::ProfileCount::getCount(), llvm::Function::ProfileCount::getType(), llvm::Function::ProfileCount::hasValue(), llvm::Function::ProfileCount::isSynthetic(), setMetadata(), and llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::size().
Referenced by llvm::createSampleProfileLoaderPass(), llvm::CodeExtractor::extractCodeRegion(), GetSortedValueDataFromCallTargets(), and llvm::updateProfileCallee().
setEntryCount() [2/2]
void Function::setEntryCount (uint64_t Count, Function::ProfileCountType Type = PCT_Real, const DenseSet< GlobalValue::GUID > * Imports = nullptr)
A convenience wrapper for setting entry count.
Definition at line 1566 of file Function.cpp.
setGC()
void Function::setGC (std::string Str)
Definition at line 501 of file Function.cpp.
References llvm::Value::getContext(), and llvm::LLVMContext::setGC().
Referenced by FunctionNumber(), llvm::InlineFunction(), and LLVMSetGC().
setHasUWTable()
void llvm::Function::setHasUWTable () inline
Definition at line 600 of file Function.h.
Referenced by llvm::CodeExtractor::findInputsOutputs().
setIsMaterializable()
void llvm::Function::setIsMaterializable (bool V) inline
Definition at line 181 of file Function.h.
References llvm::BitmaskEnumDetail::Mask().
setNotConvergent()
void llvm::Function::setNotConvergent () inline
Definition at line 566 of file Function.h.
References llvm::MCID::Convergent.
setOnlyAccessesArgMemory()
void llvm::Function::setOnlyAccessesArgMemory () inline
Definition at line 512 of file Function.h.
Referenced by setOnlyAccessesArgMemory().
setOnlyAccessesInaccessibleMemOrArgMem()
void llvm::Function::setOnlyAccessesInaccessibleMemOrArgMem () inline
Definition at line 528 of file Function.h.
setOnlyAccessesInaccessibleMemory()
void llvm::Function::setOnlyAccessesInaccessibleMemory () inline
Definition at line 519 of file Function.h.
setOnlyReadsMemory()
void llvm::Function::setOnlyReadsMemory () inline
Definition at line 495 of file Function.h.
Referenced by setOnlyReadsMemory().
setPersonalityFn()
void Function::setPersonalityFn (Constant * Fn)
Definition at line 1489 of file Function.cpp.
Referenced by llvm::CloneFunctionInto(), llvm::CloneModule(), llvm::CodeExtractor::extractCodeRegion(), FunctionNumber(), and llvm::InlineFunction().
setPrefixData()
void Function::setPrefixData (Constant * PrefixData)
Definition at line 1499 of file Function.cpp.
Referenced by FunctionNumber().
setPrologueData()
void Function::setPrologueData (Constant * PrologueData)
Definition at line 1509 of file Function.cpp.
References assert(), llvm::tgtok::Bit, C, llvm::ConstantPointerNull::get(), llvm::Value::getContext(), llvm::Type::getInt1PtrTy(), llvm::Value::getSubclassDataFromValue(), and llvm::Value::setValueSubclassData().
Referenced by FunctionNumber().
setReturnDoesNotAlias()
void llvm::Function::setReturnDoesNotAlias () inline
Definition at line 622 of file Function.h.
References llvm::NoAlias, and llvm::AttributeList::ReturnIndex.
setSectionPrefix()
void Function::setSectionPrefix (StringRef Prefix)
Set the section prefix for this function.
Definition at line 1605 of file Function.cpp.
References llvm::MDBuilder::createFunctionSectionPrefix(), llvm::Value::getContext(), and setMetadata().
Referenced by llvm::createCodeGenPreparePass().
setSpeculatable()
void llvm::Function::setSpeculatable () inline
Definition at line 574 of file Function.h.
setSubprogram()
void Function::setSubprogram (DISubprogram * SP)
Set the attached subprogram.
Calls setMetadata() with LLVMContext::MD_dbg.
Definition at line 1521 of file Metadata.cpp.
References setMetadata().
Referenced by doPromotion(), INITIALIZE_PASS(), llvm::Attributor::registerFunctionSignatureRewrite(), and llvm::stripDebugInfo().
size()
size_t llvm::Function::size () const inline
Definition at line 696 of file Function.h.
Referenced by addVariantDeclaration(), canCreateThunkFor(), llvm::IRPosition::getAttrs(), GetGlobalTypeString(), isWrapperOnlyCall(), iterativelyFlattenCFG(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::removeUnreachableBlocks(), llvm::GraphTraits< Function * >::size(), and llvm::GraphTraits< const Function * >::size().
stealArgumentListFrom()
void Function::stealArgumentListFrom (Function & Src)
Steal arguments from another function.
Drop this function's arguments and splice in the ones from Src. Requires that this has no function body.
Definition at line 332 of file Function.cpp.
References llvm::all_of(), arg_size(), Arguments, assert(), llvm::SmallVectorBase::empty(), llvm::Value::getSubclassDataFromValue(), hasLazyArguments(), makeArgArray(), Name, llvm::Value::setValueSubclassData(), and llvm::Value::use_empty().
viewCFG()
void Function::viewCFG () const
viewCFG - This function is meant for use from the debugger.
You can just say 'call F->viewCFG()' and a ghostview window should pop up from the program, displaying the CFG of the current function with the code for each basic block inside. This depends on there being a 'dot' and 'gv' program in your path.
You can just say 'call F->viewCFG()' and a ghostview window should pop up from the program, displaying the CFG of the current function. This depends on there being a 'dot' and 'gv' program in your path.
Definition at line 178 of file CFGPrinter.cpp.
References CFGFuncName, llvm::StringRef::contains(), getName(), and ViewGraph().
Referenced by LLVMViewFunctionCFG().
viewCFGOnly()
void Function::viewCFGOnly () const
viewCFGOnly - This function is meant for use from the debugger.
It works just like viewCFG, but it does not include the contents of basic blocks into the nodes, just the label. If you are only interested in the CFG this can make the graph smaller.
Definition at line 189 of file CFGPrinter.cpp.
References CFGFuncName, llvm::StringRef::contains(), getName(), and ViewGraph().
Referenced by LLVMViewFunctionCFGOnly(), and llvm::CFGViewerPass::run().
Friends And Related Function Documentation
SymbolTableListTraits< Function >
friend class SymbolTableListTraits< Function > friend
Definition at line 97 of file Function.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Function.h
lib/Analysis/CFGPrinter.cpp
lib/IR/AsmWriter.cpp
lib/IR/Function.cpp
lib/IR/Metadata.cpp