LLVM: llvm::MCFragment Class Reference
llvm::MCFragment Class Reference
#include "llvm/MC/MCFragment.h"
Public Types
enum FragmentType : uint8_t {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB, FT_BoundaryAlign, FT_SymbolId, FT_CVInlineLines,
FT_CVDefRange, FT_Dummy
}
Public Member Functions
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Protected Member Functions
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
ilist_node_impl ()=default
Protected Attributes
bool HasInstructions
Friends
class MCAsmLayout
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, true >
Detailed Description
Definition at line 31 of file MCFragment.h.
Member Enumeration Documentation
FragmentType
enum llvm::MCFragment::FragmentType : uint8_t
Enumerator
FT_Align
FT_Data
FT_CompactEncodedInst
FT_Fill
FT_Relaxable
FT_Org
FT_Dwarf
FT_DwarfFrame
FT_LEB
FT_BoundaryAlign
FT_SymbolId
FT_CVInlineLines
FT_CVDefRange
FT_Dummy
Definition at line 35 of file MCFragment.h.
Constructor & Destructor Documentation
MCFragment() [1/3]
MCFragment::MCFragment (FragmentType Kind, bool HasInstructions, MCSection * Parent = nullptr) protected
Definition at line 235 of file MCFragment.cpp.
References llvm::MCSection::getFragmentList(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
MCFragment() [2/3]
llvm::MCFragment::MCFragment () delete
MCFragment() [3/3]
llvm::MCFragment::MCFragment (const MCFragment &) delete
Member Function Documentation
destroy()
void MCFragment::destroy ()
Destroys the current fragment.
This must be used instead of delete as MCFragment is non-virtual. This method will dispatch to the appropriate subclass.
Definition at line 243 of file MCFragment.cpp.
References FT_Align, FT_BoundaryAlign, FT_CompactEncodedInst, FT_CVDefRange, FT_CVInlineLines, FT_Data, FT_Dummy, FT_Dwarf, FT_DwarfFrame, FT_Fill, FT_LEB, FT_Org, FT_Relaxable, and FT_SymbolId.
Referenced by llvm::computeBundlePadding().
dump()
LLVM_DUMP_METHOD void MCFragment::dump () const
Definition at line 310 of file MCFragment.cpp.
References DF, llvm::numbers::e, llvm::errs(), FT_Align, FT_BoundaryAlign, FT_CompactEncodedInst, FT_CVDefRange, FT_CVInlineLines, FT_Data, FT_Dummy, FT_Dwarf, FT_DwarfFrame, FT_Fill, FT_LEB, FT_Org, FT_Relaxable, FT_SymbolId, getKind(), hasInstructions(), llvm::hexdigit(), and llvm::SmallVectorBase::size().
Referenced by hasInstructions().
getAtom()
const MCSymbol* llvm::MCFragment::getAtom () const inline
Definition at line 90 of file MCFragment.h.
Referenced by llvm::MCAssembler::getAtom(), and llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl().
getKind()
FragmentType llvm::MCFragment::getKind () const inline
Definition at line 85 of file MCFragment.h.
Referenced by llvm::MCDummyFragment::classof(), llvm::MCEncodedFragment::classof(), llvm::MCEncodedFragmentWithFixups< 8, 1 >::classof(), llvm::MCDataFragment::classof(), llvm::MCCompactEncodedInstFragment::classof(), llvm::MCRelaxableFragment::classof(), llvm::MCAlignFragment::classof(), llvm::MCFillFragment::classof(), llvm::MCOrgFragment::classof(), llvm::MCLEBFragment::classof(), llvm::MCDwarfLineAddrFragment::classof(), llvm::MCDwarfCallFrameFragment::classof(), llvm::MCSymbolIdFragment::classof(), llvm::MCCVInlineLineTableFragment::classof(), llvm::MCCVDefRangeFragment::classof(), llvm::MCBoundaryAlignFragment::classof(), llvm::MCAssembler::computeFragmentSize(), dump(), and isInSymtab().
getLayoutOrder()
unsigned llvm::MCFragment::getLayoutOrder () const inline
Definition at line 93 of file MCFragment.h.
Referenced by llvm::MCAsmLayout::MCAsmLayout().
getParent()
MCSection* llvm::MCFragment::getParent () const inline
Definition at line 87 of file MCFragment.h.
Referenced by canUseLocalRelocation(), llvm::MCAssembler::computeFragmentSize(), llvm::MCObjectStreamer::EmitLabelAtPos(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), getFixupOffset(), llvm::MachObjectWriter::getFragmentAddress(), llvm::MCSymbol::getSection(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolValue(), llvm::MCAsmLayout::invalidateFragmentsFrom(), isIFunc(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MCAsmLayout::layoutFragment(), and llvm::MCAsmLayout::MCAsmLayout().
hasInstructions()
bool llvm::MCFragment::hasInstructions () const inline
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Definition at line 98 of file MCFragment.h.
References dump(), and HasInstructions.
Referenced by CanReuseDataFragment(), dump(), isInSymtab(), llvm::MCAsmLayout::layoutFragment(), and llvm::MCAssembler::writeFragmentPadding().
operator=()
MCFragment& llvm::MCFragment::operator= (const MCFragment &) delete
setAtom()
void llvm::MCFragment::setAtom (const MCSymbol * Value) inline
Definition at line 91 of file MCFragment.h.
setLayoutOrder()
void llvm::MCFragment::setLayoutOrder (unsigned Value) inline
Definition at line 94 of file MCFragment.h.
setParent()
void llvm::MCFragment::setParent (MCSection * Value) inline
Definition at line 88 of file MCFragment.h.
Referenced by llvm::MCSection::flushPendingLabels(), llvm::MCSection::getSubsectionInsertionPoint(), and llvm::MCObjectStreamer::insert().
Friends And Related Function Documentation
MCAsmLayout
friend class MCAsmLayout friend
Definition at line 32 of file MCFragment.h.
Member Data Documentation
HasInstructions
bool llvm::MCFragment::HasInstructions protected
Definition at line 69 of file MCFragment.h.
Referenced by hasInstructions(), and llvm::MCEncodedFragment::setHasInstructions().
The documentation for this class was generated from the following files:
include/llvm/MC/MCFragment.h
lib/MC/MCFragment.cpp