LLVM: llvm::const_set_bits_iterator_impl< BitVectorT > Class Template Reference
llvm::const_set_bits_iterator_impl< BitVectorT > Class Template Reference
ForwardIterator for the bits that are set.
#include "llvm/ADT/BitVector.h"
Public Member Functions
const_set_bits_iterator_impl (const BitVectorT &Parent, int Current)
const_set_bits_iterator_impl (const BitVectorT &Parent)
const_set_bits_iterator_impl (const const_set_bits_iterator_impl &)=default
const_set_bits_iterator_impl operator++ (int)
const_set_bits_iterator_impl & operator++ ()
unsigned operator* () const
bool operator== (const const_set_bits_iterator_impl &Other) const
bool operator!= (const const_set_bits_iterator_impl &Other) const
Detailed Description
template<typename BitVectorT>
class llvm::const_set_bits_iterator_impl< BitVectorT >
ForwardIterator for the bits that are set.
Iterators get invalidated when resize / reserve is called.
Definition at line 31 of file BitVector.h.
Constructor & Destructor Documentation
const_set_bits_iterator_impl() [1/3]
template<typename BitVectorT > llvm::const_set_bits_iterator_impl< BitVectorT >::const_set_bits_iterator_impl (const BitVectorT & Parent, int Current) inline
Definition at line 41 of file BitVector.h.
Referenced by llvm::const_set_bits_iterator_impl< BitVectorT >::const_set_bits_iterator_impl().
const_set_bits_iterator_impl() [2/3]
template<typename BitVectorT > llvm::const_set_bits_iterator_impl< BitVectorT >::const_set_bits_iterator_impl (const BitVectorT & Parent) inline explicit
Definition at line 43 of file BitVector.h.
References llvm::const_set_bits_iterator_impl< BitVectorT >::const_set_bits_iterator_impl().
const_set_bits_iterator_impl() [3/3]
template<typename BitVectorT > llvm::const_set_bits_iterator_impl< BitVectorT >::const_set_bits_iterator_impl (const const_set_bits_iterator_impl< BitVectorT > &) default
Member Function Documentation
operator!=()
template<typename BitVectorT > bool llvm::const_set_bits_iterator_impl< BitVectorT >::operator!= (const const_set_bits_iterator_impl< BitVectorT > & Other) const inline
Definition at line 66 of file BitVector.h.
References assert().
operator*()
template<typename BitVectorT > unsigned llvm::const_set_bits_iterator_impl< BitVectorT >::operator* () const inline
Definition at line 58 of file BitVector.h.
operator++() [1/2]
template<typename BitVectorT > const_set_bits_iterator_impl llvm::const_set_bits_iterator_impl< BitVectorT >::operator++ (int) inline
Definition at line 47 of file BitVector.h.
operator++() [2/2]
template<typename BitVectorT > const_set_bits_iterator_impl& llvm::const_set_bits_iterator_impl< BitVectorT >::operator++ () inline
Definition at line 53 of file BitVector.h.
operator==()
template<typename BitVectorT > bool llvm::const_set_bits_iterator_impl< BitVectorT >::operator== (const const_set_bits_iterator_impl< BitVectorT > & Other) const inline
Definition at line 60 of file BitVector.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/ADT/BitVector.h