LLVM: llvm::InnerLoopVectorizer Class Reference
llvm::InnerLoopVectorizer Class Reference
InnerLoopVectorizer vectorizes loops which contain only one basic block to a specified vectorization factor (VF).
Public Types
using VectorParts = SmallVector< Value *, 2 >
A type for vectorized values in the new loop.
Public Member Functions
InnerLoopVectorizer (Loop *OrigLoop, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, unsigned VecWidth, unsigned UnrollFactor, LoopVectorizationLegality *LVL, LoopVectorizationCostModel *CM)
virtual ~InnerLoopVectorizer ()=default
BasicBlock * createVectorizedLoopSkeleton ()
Create a new empty loop.
void widenInstruction (Instruction &I)
Widen a single instruction within the innermost loop.
void fixVectorizedLoop ()
Fix the vectorized code, taking care of header phi's, live-outs, and more.
bool areSafetyChecksAdded ()
void widenGEP (GetElementPtrInst *GEP, unsigned UF, unsigned VF, bool IsPtrLoopInvariant, SmallBitVector &IsIndexLoopInvariant)
Vectorize a single GetElementPtrInst based on information gathered and decisions taken during planning.
void widenPHIInstruction (Instruction *PN, unsigned UF, unsigned VF)
Vectorize a single PHINode in a block.
void scalarizeInstruction (Instruction *Instr, const VPIteration &Instance, bool IfPredicateInstr)
A helper function to scalarize a single Instruction in the innermost loop.
void widenIntOrFpInduction (PHINode *IV, TruncInst *Trunc=nullptr)
Widen an integer or floating-point induction variable IV.
Value * getOrCreateVectorValue (Value *V, unsigned Part)
getOrCreateVectorValue and getOrCreateScalarValue coordinate to generate a vector or scalar value on-demand if one is not yet available.
Value * getOrCreateScalarValue (Value *V, const VPIteration &Instance)
Return a value in the new loop corresponding to V from the original loop at unroll and vector indices Instance.
void packScalarIntoVectorValue (Value *V, const VPIteration &Instance)
Construct the vector value of a scalarized value V one lane at a time.
void vectorizeInterleaveGroup (Instruction *Instr, VPTransformState &State, VPValue *Addr, VPValue *BlockInMask=nullptr)
Try to vectorize the interleaved access group that Instr belongs to with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
void vectorizeMemoryInstruction (Instruction *Instr, VPTransformState &State, VPValue *Addr, VPValue *BlockInMask=nullptr)
Vectorize Load and Store instructions with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
void setDebugLocFromInst (IRBuilder<> &B, const Value *Ptr)
Set the debug location in the builder using the debug location in the instruction.
void fixNonInductionPHIs (void)
Fix the non-induction PHIs in the OrigPHIsToFix vector.
Protected Types
using PhiVector = SmallVector< PHINode *, 4 >
A small list of PHINodes.
using ScalarParts = SmallVector< SmallVector< Value *, 4 >, 2 >
A type for scalarized values in the new loop.
Protected Member Functions
void fixupIVUsers (PHINode *OrigPhi, const InductionDescriptor &II, Value *CountRoundDown, Value *EndValue, BasicBlock *MiddleBlock)
Set up the values of the IVs correctly when exiting the vector loop.
PHINode * createInductionVariable (Loop *L, Value *Start, Value *End, Value *Step, Instruction *DL)
Create a new induction variable inside L.
void fixCrossIterationPHIs ()
Handle all cross-iteration phis in the header.
void fixFirstOrderRecurrence (PHINode *Phi)
Fix a first-order recurrence.
void fixReduction (PHINode *Phi)
Fix a reduction cross-iteration phi.
void clearReductionWrapFlags (RecurrenceDescriptor &RdxDesc)
Clear NSW/NUW flags from reduction instructions if necessary.
void fixLCSSAPHIs ()
The Loop exit block may have single value PHI nodes with some incoming value.
void sinkScalarOperands (Instruction *PredInst)
Iteratively sink the scalarized operands of a predicated instruction into the block that was created for it.
void truncateToMinimalBitwidths ()
Shrinks vector element sizes to the smallest bitwidth they can be legally represented as.
virtual Value * getBroadcastInstrs (Value *V)
Create a broadcast instruction.
virtual Value * getStepVector (Value *Val, int StartIdx, Value *Step, Instruction::BinaryOps Opcode=Instruction::BinaryOpsEnd)
This function adds (StartIdx, StartIdx + Step, StartIdx + 2*Step, ...) to each vector element of Val.
void buildScalarSteps (Value *ScalarIV, Value *Step, Instruction *EntryVal, const InductionDescriptor &ID)
Compute scalar induction steps.
void createVectorIntOrFpInductionPHI (const InductionDescriptor &II, Value *Step, Instruction *EntryVal)
Create a vector induction phi node based on an existing scalar one.
bool shouldScalarizeInstruction (Instruction *I) const
Returns true if an instruction I should be scalarized instead of vectorized for the chosen vectorization factor.
bool needsScalarInduction (Instruction *IV) const
Returns true if we should generate a scalar version of IV.
void recordVectorLoopValueForInductionCast (const InductionDescriptor &ID, const Instruction *EntryVal, Value *VectorLoopValue, unsigned Part, unsigned Lane=UINT_MAX)
If there is a cast involved in the induction variable ID, which should be ignored in the vectorized loop body, this function records the VectorLoopValue of the respective Phi also as the VectorLoopValue of the cast.
virtual Value * reverseVector (Value *Vec)
Generate a shuffle sequence that will reverse the vector Vec.
Value * getOrCreateTripCount (Loop *NewLoop)
Returns (and creates if needed) the original loop trip count.
Value * getOrCreateVectorTripCount (Loop *NewLoop)
Returns (and creates if needed) the trip count of the widened loop.
Value * createBitOrPointerCast (Value *V, VectorType *DstVTy, const DataLayout &DL)
Returns a bitcasted value to the requested vector type.
void emitMinimumIterationCountCheck (Loop *L, BasicBlock *Bypass)
Emit a bypass check to see if the vector trip count is zero, including if it overflows.
void emitSCEVChecks (Loop *L, BasicBlock *Bypass)
Emit a bypass check to see if all of the SCEV assumptions we've had to make are correct.
void emitMemRuntimeChecks (Loop *L, BasicBlock *Bypass)
Emit bypass checks to check any memory assumptions we may have made.
Value * emitTransformedIndex (IRBuilder<> &B, Value *Index, ScalarEvolution *SE, const DataLayout &DL, const InductionDescriptor &ID) const
Compute the transformed value of Index at offset StartValue using step StepValue.
void addNewMetadata (Instruction *To, const Instruction *Orig)
Add additional metadata to To that was not present on Orig.
void addMetadata (Instruction *To, Instruction *From)
Add metadata from one instruction to another.
void addMetadata (ArrayRef< Value *> To, Instruction *From)
Similar to the previous function but it adds the metadata to a vector of instructions.
Protected Attributes
Loop * OrigLoop
The original loop.
PredicatedScalarEvolution & PSE
A wrapper around ScalarEvolution used to add runtime SCEV checks.
LoopInfo * LI
Loop Info.
DominatorTree * DT
Dominator Tree.
AliasAnalysis * AA
Alias Analysis.
const TargetLibraryInfo * TLI
Target Library Info.
const TargetTransformInfo * TTI
Target Transform Info.
AssumptionCache * AC
Assumption Cache.
OptimizationRemarkEmitter * ORE
Interface to emit optimization remarks.
std::unique_ptr< LoopVersioning > LVer
LoopVersioning.
unsigned VF
The vectorization SIMD factor to use.
unsigned UF
The vectorization unroll factor to use.
IRBuilder Builder
The builder that we use.
BasicBlock * LoopVectorPreHeader
The vector-loop preheader.
BasicBlock * LoopScalarPreHeader
The scalar-loop preheader.
BasicBlock * LoopMiddleBlock
Middle Block between the vector and the scalar.
BasicBlock * LoopExitBlock
The ExitBlock of the scalar loop.
BasicBlock * LoopVectorBody
The vector loop body.
BasicBlock * LoopScalarBody
The scalar loop body.
SmallVector< BasicBlock *, 4 > LoopBypassBlocks
A list of all bypass blocks. The first block is the entry of the loop.
PHINode * Induction = nullptr
The new Induction variable which was added to the new block.
PHINode * OldInduction = nullptr
The induction variable of the old basic block.
VectorizerValueMap VectorLoopValueMap
Maps values from the original loop to their corresponding values in the vectorized loop.
SmallVector< Instruction *, 4 > PredicatedInstructions
Store instructions that were predicated.
Value * TripCount = nullptr
Trip count of the original loop.
Value * VectorTripCount = nullptr
Trip count of the widened loop (TripCount - TripCount % (VF*UF))
LoopVectorizationLegality * Legal
The legality analysis.
LoopVectorizationCostModel * Cost
The profitablity analysis.
bool AddedSafetyChecks = false
DenseMap< PHINode *, Value * > IVEndValues
SmallVector< PHINode *, 8 > OrigPHIsToFix
Friends
class LoopVectorizationPlanner
Detailed Description
InnerLoopVectorizer vectorizes loops which contain only one basic block to a specified vectorization factor (VF).
This class performs the widening of scalars into vectors, or multiple scalars. This class also implements the following features:
It inserts an epilogue loop for handling loops that don't have iteration counts that are known to be a multiple of the vectorization factor.
It handles the code generation for reduction variables.
Scalarization (implementation using scalars) of un-vectorizable instructions. InnerLoopVectorizer does not perform any vectorization-legality checks, and relies on the caller to check for the different legality aspects. The InnerLoopVectorizer relies on the LoopVectorizationLegality class to provide information about the induction and reduction variables that were found to a given vectorization factor.
Definition at line 398 of file LoopVectorize.cpp.
Member Typedef Documentation
PhiVector
using llvm::InnerLoopVectorizer::PhiVector = SmallVector<PHINode *, 4> protected
A small list of PHINodes.
Definition at line 511 of file LoopVectorize.cpp.
ScalarParts
using llvm::InnerLoopVectorizer::ScalarParts = SmallVector<SmallVector<Value *, 4>, 2> protected
A type for scalarized values in the new loop.
Each value from the original loop, when scalarized, is represented by UF x VF scalar values in the new unrolled loop, where UF is the unroll factor and VF is the vectorization factor.
Definition at line 517 of file LoopVectorize.cpp.
VectorParts
using llvm::InnerLoopVectorizer::VectorParts = SmallVector<Value *, 2>
A type for vectorized values in the new loop.
Each value from the original loop, when vectorized, is represented by UF vector values in the new unrolled loop, where UF is the unroll factor.
Definition at line 429 of file LoopVectorize.cpp.
Constructor & Destructor Documentation
InnerLoopVectorizer()
llvm::InnerLoopVectorizer::InnerLoopVectorizer (Loop * OrigLoop, PredicatedScalarEvolution & PSE, LoopInfo * LI, DominatorTree * DT, const TargetLibraryInfo * TLI, const TargetTransformInfo * TTI, AssumptionCache * AC, OptimizationRemarkEmitter * ORE, unsigned VecWidth, unsigned UnrollFactor, LoopVectorizationLegality * LVL, LoopVectorizationCostModel * CM) inline
Definition at line 400 of file LoopVectorize.cpp.
References createVectorizedLoopSkeleton(), fixVectorizedLoop(), I, widenInstruction(), and ~InnerLoopVectorizer().
~InnerLoopVectorizer()
virtual llvm::InnerLoopVectorizer::~InnerLoopVectorizer () virtual default
Referenced by InnerLoopVectorizer().
Member Function Documentation
addMetadata() [1/2]
void InnerLoopVectorizer::addMetadata (Instruction * To, Instruction * From) protected
Add metadata from one instruction to another.
This includes both the original MDs from From and additional ones (
See also
addNewMetadata). Use this for newly created instructions in the vector loop.
Definition at line 917 of file LoopVectorize.cpp.
References addNewMetadata(), and llvm::propagateMetadata().
Referenced by addMetadata(), vectorizeMemoryInstruction(), widenGEP(), widenInstruction(), and widenIntOrFpInduction().
addMetadata() [2/2]
void InnerLoopVectorizer::addMetadata (ArrayRef< Value *> To, Instruction * From) protected
Similar to the previous function but it adds the metadata to a vector of instructions.
Definition at line 923 of file LoopVectorize.cpp.
References addMetadata(), and I.
addNewMetadata()
void InnerLoopVectorizer::addNewMetadata (Instruction * To, const Instruction * Orig) protected
Add additional metadata to To that was not present on Orig.
Currently this is used to add the noalias annotations based on the inserted memchecks. Use this for instructions that are cloned into the vector loop.
Definition at line 909 of file LoopVectorize.cpp.
References LVer.
Referenced by addMetadata(), and scalarizeInstruction().
areSafetyChecksAdded()
bool llvm::InnerLoopVectorizer::areSafetyChecksAdded () inline
Definition at line 424 of file LoopVectorize.cpp.
References AddedSafetyChecks.
Referenced by llvm::LoopVectorizePass::processLoop().
buildScalarSteps()
void InnerLoopVectorizer::buildScalarSteps (Value * ScalarIV, Value * Step, Instruction * EntryVal, const InductionDescriptor & ID) protected
Compute scalar induction steps.
ScalarIV is the scalar induction variable on which to base the steps, Step is the size of the step, and EntryVal is the value from the original loop that maps to the steps. Note that EntryVal doesn't have to be an induction variable - it can also be a truncate instruction.
Definition at line 1958 of file LoopVectorize.cpp.
References llvm::MCID::Add, addFastMathFlag(), assert(), Builder, Cost, llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::InductionDescriptor::getInductionOpcode(), llvm::Type::getScalarType(), getSignedIntOrFpConstant(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), recordVectorLoopValueForInductionCast(), llvm::VectorizerValueMap::setScalarValue(), UF, VectorLoopValueMap, and VF.
Referenced by widenIntOrFpInduction().
clearReductionWrapFlags()
void InnerLoopVectorizer::clearReductionWrapFlags (RecurrenceDescriptor & RdxDesc) protected
Clear NSW/NUW flags from reduction instructions if necessary.
Definition at line 3887 of file LoopVectorize.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallVectorBase::empty(), llvm::RecurrenceDescriptor::getLoopExitInstr(), getOrCreateVectorValue(), llvm::Instruction::getParent(), llvm::RecurrenceDescriptor::getRecurrenceKind(), llvm::SmallPtrSetImpl< PtrType >::insert(), OrigLoop, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::RecurrenceDescriptor::RK_IntegerAdd, llvm::RecurrenceDescriptor::RK_IntegerMult, UF, and llvm::Value::users().
Referenced by fixReduction().
createBitOrPointerCast()
Value * InnerLoopVectorizer::createBitOrPointerCast (Value * V, VectorType * DstVTy, const DataLayout & DL) protected
Returns a bitcasted value to the requested vector type.
Also handles bitcasts of vector<float> <-> vector<pointer> types.
Definition at line 2654 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast(), llvm::VectorType::get(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::Type::getIntNTy(), llvm::SequentialType::getNumElements(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::CastInst::isBitOrNoopPointerCastable(), llvm::Type::isFloatingPointTy(), llvm::Type::isPointerTy(), and VF.
Referenced by vectorizeInterleaveGroup().
createInductionVariable()
PHINode * InnerLoopVectorizer::createInductionVariable (Loop * L, Value * Start, Value * End, Value * Step, Instruction * DL) protected
Create a new induction variable inside L.
Definition at line 2529 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton().
createVectorIntOrFpInductionPHI()
void InnerLoopVectorizer::createVectorIntOrFpInductionPHI (const InductionDescriptor & II, Value * Step, Instruction * EntryVal) protected
Create a vector induction phi node based on an existing scalar one.
EntryVal is the value from the original loop that maps to the vector phi node, and Step is the loop-invariant step. If EntryVal is a truncate instruction, instead of widening the original IV, we widen a version of the IV truncated to EntryVal's type.
Definition at line 1685 of file LoopVectorize.cpp.
References assert().
Referenced by widenIntOrFpInduction().
createVectorizedLoopSkeleton()
BasicBlock * InnerLoopVectorizer::createVectorizedLoopSkeleton ()
Create a new empty loop.
Unlink the old loop and connect the new one. Return the pre-header block of the new loop.
Definition at line 2911 of file LoopVectorize.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::PHINode::addIncoming(), assert(), B, Builder, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), Cost, llvm::CmpInst::Create(), llvm::PHINode::Create(), llvm::BranchInst::Create(), createInductionVariable(), DT, emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), emitSCEVChecks(), emitTransformedIndex(), llvm::CallingConv::Fast, llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::ConstantInt::get(), llvm::CastInst::getCastOpcode(), llvm::Module::getDataLayout(), llvm::Instruction::getDebugLoc(), getDebugLocFromInstOrOperands(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::Loop::getLoopID(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getModule(), getOrCreateTripCount(), getOrCreateVectorTripCount(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::LoopVectorizationLegality::getPrimaryInduction(), llvm::PredicatedScalarEvolution::getSE(), llvm::InductionDescriptor::getStartValue(), llvm::InductionDescriptor::getStep(), llvm::BasicBlock::getTerminator(), llvm::IRBuilderBase::getTrue(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::Optional< T >::getValue(), llvm::LoopVectorizationLegality::getWidestInductionType(), llvm::Optional< T >::hasValue(), llvm::CmpInst::ICMP_EQ, Induction, IVEndValues, Legal, LI, List, LLVMLoopVectorizeFollowupAll, LoopBypassBlocks, LoopExitBlock, LoopMiddleBlock, LoopScalarBody, LoopScalarPreHeader, LoopVectorBody, LoopVectorPreHeader, llvm::makeFollowupLoopID(), OldInduction, ORE, OrigLoop, PSE, llvm::ReplaceInstWithInst(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::Instruction::setDebugLoc(), llvm::PHINode::setIncomingValueForBlock(), llvm::IRBuilderBase::SetInsertPoint(), llvm::Loop::setLoopID(), llvm::Value::setName(), llvm::SplitBlock(), UF, llvm::DominatorTreeBase< NodeT, IsPostDom >::verify(), and VF.
Referenced by llvm::LoopVectorizationPlanner::executePlan(), and InnerLoopVectorizer().
emitMemRuntimeChecks()
void InnerLoopVectorizer::emitMemRuntimeChecks (Loop * L, BasicBlock * Bypass) protected
Emit bypass checks to check any memory assumptions we may have made.
Definition at line 2765 of file LoopVectorize.cpp.
References AddedSafetyChecks, llvm::LoopAccessInfo::addRuntimeChecks(), assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), Cost, llvm::BranchInst::Create(), DEBUG_TYPE, DT, llvm::OptimizationRemarkEmitter::emit(), EnableVPlanNativePath, llvm::LoopVectorizeHints::FK_Enabled, llvm::LoopVectorizeHints::getForce(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getLAI(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getParent(), llvm::PredicatedScalarEvolution::getSE(), llvm::Loop::getStartLoc(), llvm::BasicBlock::getTerminator(), llvm::Function::hasOptSize(), llvm::LoopVectorizationCostModel::Hints, Legal, LI, LoopBypassBlocks, LoopExitBlock, LoopVectorPreHeader, LVer, ORE, OrigLoop, PSE, llvm::ReplaceInstWithInst(), llvm::Value::setName(), and llvm::SplitBlock().
Referenced by createVectorizedLoopSkeleton().
emitMinimumIterationCountCheck()
void InnerLoopVectorizer::emitMinimumIterationCountCheck (Loop * L, BasicBlock * Bypass) protected
Emit a bypass check to see if the vector trip count is zero, including if it overflows.
Definition at line 2684 of file LoopVectorize.cpp.
References assert(), Builder, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), Cost, llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateICmp(), DT, llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::ConstantInt::get(), llvm::IRBuilderBase::getFalse(), llvm::DomTreeNodeBase< NodeT >::getIDom(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), getOrCreateTripCount(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, LI, LoopBypassBlocks, LoopExitBlock, LoopVectorPreHeader, P, llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::ReplaceInstWithInst(), llvm::LoopVectorizationCostModel::requiresScalarEpilogue(), llvm::SplitBlock(), UF, and VF.
Referenced by createVectorizedLoopSkeleton().
emitSCEVChecks()
void InnerLoopVectorizer::emitSCEVChecks (Loop * L, BasicBlock * Bypass) protected
Emit a bypass check to see if all of the SCEV assumptions we've had to make are correct.
Definition at line 2726 of file LoopVectorize.cpp.
References AddedSafetyChecks, assert(), C, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::BranchInst::Create(), DT, llvm::Module::getDataLayout(), llvm::BasicBlock::getModule(), llvm::BasicBlock::getParent(), llvm::PredicatedScalarEvolution::getSE(), llvm::BasicBlock::getTerminator(), llvm::PredicatedScalarEvolution::getUnionPredicate(), llvm::Function::hasOptSize(), LI, LoopBypassBlocks, LoopExitBlock, LoopVectorPreHeader, PSE, llvm::ReplaceInstWithInst(), llvm::Value::setName(), and llvm::SplitBlock().
Referenced by createVectorizedLoopSkeleton().
emitTransformedIndex()
Value * InnerLoopVectorizer::emitTransformedIndex (IRBuilder<> & B, Value * Index, ScalarEvolution * SE, const DataLayout & DL, const InductionDescriptor & ID) const protected
Compute the transformed value of Index at offset StartValue using step StepValue.
For integer induction, returns StartValue + Index * StepValue. For pointer induction, returns StartValue[Index * StepValue]. FIXME: The newly created binary instructions should contain nsw/nuw flags, which can be found from the original scalar operations.
Definition at line 2823 of file LoopVectorize.cpp.
References assert(), B, CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateGEP(), CreateMul(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::SCEVExpander::expandCodeFor(), llvm::InductionDescriptor::getConstIntStepValue(), llvm::InductionDescriptor::getInductionBinOp(), llvm::IRBuilderBase::GetInsertPoint(), llvm::InductionDescriptor::getKind(), llvm::InductionDescriptor::getStartValue(), llvm::InductionDescriptor::getStep(), llvm::Value::getType(), llvm::InductionDescriptor::IK_FpInduction, llvm::InductionDescriptor::IK_IntInduction, llvm::InductionDescriptor::IK_NoInduction, llvm::InductionDescriptor::IK_PtrInduction, llvm::ConstantInt::isMinusOne(), llvm_unreachable, llvm::FastMathFlags::setFast(), X, and Y.
Referenced by createVectorizedLoopSkeleton(), fixupIVUsers(), widenIntOrFpInduction(), and widenPHIInstruction().
fixCrossIterationPHIs()
void InnerLoopVectorizer::fixCrossIterationPHIs () protected
Handle all cross-iteration phis in the header.
Definition at line 3487 of file LoopVectorize.cpp.
References fixFirstOrderRecurrence(), fixReduction(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::isFirstOrderRecurrence(), llvm::LoopVectorizationLegality::isReductionVariable(), Legal, OrigLoop, and llvm::BasicBlock::phis().
Referenced by fixVectorizedLoop().
fixFirstOrderRecurrence()
void InnerLoopVectorizer::fixFirstOrderRecurrence (PHINode * Phi) protected
Fix a first-order recurrence.
This is the second phase of vectorizing this phi node.
Definition at line 3503 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), llvm::BasicBlock::begin(), Builder, llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::VectorType::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingValueForBlock(), llvm::IRBuilderBase::getInt32(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), getOrCreateVectorValue(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::VectorizerValueMap::getVectorValue(), I, llvm::Loop::isLoopInvariant(), LI, LoopMiddleBlock, LoopScalarPreHeader, LoopVectorBody, LoopVectorPreHeader, OrigLoop, llvm::Value::replaceAllUsesWith(), llvm::VectorizerValueMap::resetVectorValue(), llvm::IRBuilderBase::SetInsertPoint(), UF, VectorLoopValueMap, and VF.
Referenced by fixCrossIterationPHIs().
fixLCSSAPHIs()
void InnerLoopVectorizer::fixLCSSAPHIs () protected
The Loop exit block may have single value PHI nodes with some incoming value.
While vectorizing we only handled real values that were defined inside the loop and we should have one value for each predecessor of its parent basic block. See PR14725.
Definition at line 3918 of file LoopVectorize.cpp.
References Builder, Cost, getOrCreateScalarValue(), llvm::BasicBlock::getTerminator(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), LoopExitBlock, LoopMiddleBlock, llvm::BasicBlock::phis(), llvm::IRBuilderBase::SetInsertPoint(), UF, and VF.
Referenced by fixVectorizedLoop().
fixNonInductionPHIs()
void InnerLoopVectorizer::fixNonInductionPHIs (void)
Fix the non-induction PHIs in the OrigPHIsToFix vector.
Definition at line 4003 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), Builder, llvm::PHINode::getNumIncomingValues(), getOrCreateVectorValue(), llvm::Instruction::getParent(), llvm::VectorizerValueMap::getVectorValue(), OrigPHIsToFix, llvm::predecessors(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SmallVectorBase::size(), and VectorLoopValueMap.
Referenced by fixVectorizedLoop().
fixReduction()
void InnerLoopVectorizer::fixReduction (PHINode * Phi) protected
Fix a reduction cross-iteration phi.
This is the second phase of vectorizing this phi node.
Definition at line 3681 of file LoopVectorize.cpp.
References addFastMathFlag(), llvm::PHINode::addIncoming(), assert(), Builder, clearReductionWrapFlags(), Cost, llvm::PHINode::Create(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::createMinMaxOp(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::createTargetReduction(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::IRBuilder< T, Inserter >::CreateZExt(), E, llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::VectorType::get(), llvm::PHINode::getBasicBlockIndex(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingValueForBlock(), llvm::IRBuilderBase::getInt32(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), getOrCreateVectorValue(), llvm::RecurrenceDescriptor::getRecurrenceBinOp(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), llvm::RecurrenceDescriptor::getRecurrenceKind(), llvm::LoopVectorizationLegality::getReductionVars(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::VectorizerValueMap::getVectorValue(), llvm::LoopVectorizationLegality::hasFunNoNaNAttr(), I, llvm::LoopVectorizationLegality::isReductionVariable(), Legal, LI, LoopBypassBlocks, LoopExitBlock, LoopMiddleBlock, LoopScalarPreHeader, LoopVectorBody, LoopVectorPreHeader, OrigLoop, llvm::BasicBlock::phis(), llvm::VectorizerValueMap::resetVectorValue(), llvm::RecurrenceDescriptor::RK_FloatMinMax, llvm::RecurrenceDescriptor::RK_IntegerMinMax, setDebugLocFromInst(), llvm::PHINode::setIncomingValue(), llvm::IRBuilderBase::SetInsertPoint(), TTI, UF, llvm::Value::users(), VectorLoopValueMap, and VF.
Referenced by fixCrossIterationPHIs().
fixupIVUsers()
void InnerLoopVectorizer::fixupIVUsers (PHINode * OrigPhi, const InductionDescriptor & II, Value * CountRoundDown, Value * EndValue, BasicBlock * MiddleBlock) protected
Set up the values of the IVs correctly when exiting the vector loop.
Definition at line 3142 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), B, llvm::LoopBase< BlockT, LoopT >::contains(), emitTransformedIndex(), llvm::ConstantInt::get(), llvm::PHINode::getBasicBlockIndex(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BasicBlock::getModule(), llvm::Instruction::getOpcode(), llvm::PredicatedScalarEvolution::getSE(), llvm::InductionDescriptor::getStep(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::hash_combine(), llvm::hash_combine_range(), I, llvm::isEqual(), llvm::Instruction::isIdenticalTo(), llvm::Type::isIntegerTy(), OrigLoop, PostInc, PSE, llvm::Value::setName(), llvm::Value::users(), llvm::User::value_op_begin(), and llvm::User::value_op_end().
Referenced by fixVectorizedLoop().
fixVectorizedLoop()
void InnerLoopVectorizer::fixVectorizedLoop ()
Fix the vectorized code, taking care of header phi's, live-outs, and more.
Definition at line 3451 of file LoopVectorize.cpp.
References assert(), cse(), EnableVPlanNativePath, fixCrossIterationPHIs(), fixLCSSAPHIs(), fixNonInductionPHIs(), fixupIVUsers(), llvm::ScalarEvolution::forgetLoop(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), getOrCreateVectorTripCount(), llvm::PredicatedScalarEvolution::getSE(), IVEndValues, Legal, LI, LoopMiddleBlock, LoopVectorBody, OrigLoop, OrigPHIsToFix, PredicatedInstructions, PSE, sinkScalarOperands(), truncateToMinimalBitwidths(), and VF.
Referenced by llvm::LoopVectorizationPlanner::executePlan(), and InnerLoopVectorizer().
getBroadcastInstrs()
Value * InnerLoopVectorizer::getBroadcastInstrs (Value * V) protected virtual
Create a broadcast instruction.
This method generates a broadcast instruction (shuffle) for loop invariant values and for the induction value. If this is the induction variable then we extend it to N, N+1, ... this is needed because each iteration in the loop corresponds to a SIMD element.
Definition at line 1666 of file LoopVectorize.cpp.
References Builder, llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::DominatorTree::dominates(), DT, llvm::dyn_cast(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Loop::isLoopInvariant(), LoopVectorPreHeader, OrigLoop, llvm::IRBuilderBase::SetInsertPoint(), and VF.
Referenced by getOrCreateVectorValue(), llvm::InnerLoopUnroller::InnerLoopUnroller(), and widenIntOrFpInduction().
getOrCreateScalarValue()
Value * InnerLoopVectorizer::getOrCreateScalarValue (Value * V, const VPIteration & Instance)
Return a value in the new loop corresponding to V from the original loop at unroll and vector indices Instance.
If the value has been vectorized but not scalarized, the necessary extractelement instruction will be generated.
Definition at line 2073 of file LoopVectorize.cpp.
References assert(), Builder, Cost, llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilderBase::getInt32(), getOrCreateVectorValue(), llvm::VectorizerValueMap::getScalarValue(), llvm::VectorizerValueMap::hasScalarValue(), llvm::Loop::isLoopInvariant(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::VPIteration::Lane, OrigLoop, llvm::VPIteration::Part, VectorLoopValueMap, and VF.
Referenced by fixLCSSAPHIs(), scalarizeInstruction(), and widenInstruction().
getOrCreateTripCount()
Value * InnerLoopVectorizer::getOrCreateTripCount (Loop * NewLoop) protected
Returns (and creates if needed) the original loop trip count.
Definition at line 2561 of file LoopVectorize.cpp.
References assert(), Builder, llvm::CastInst::CreatePointerCast(), llvm::SCEVExpander::expandCodeFor(), llvm::PredicatedScalarEvolution::getBackedgeTakenCount(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getModule(), llvm::Type::getPrimitiveSizeInBits(), llvm::PredicatedScalarEvolution::getSE(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::LoopVectorizationLegality::getWidestInductionType(), llvm::Type::isPointerTy(), Legal, PSE, and TripCount.
Referenced by createVectorizedLoopSkeleton(), emitMinimumIterationCountCheck(), llvm::LoopVectorizationPlanner::executePlan(), and getOrCreateVectorTripCount().
getOrCreateVectorTripCount()
Value * InnerLoopVectorizer::getOrCreateVectorTripCount (Loop * NewLoop) protected
Returns (and creates if needed) the trip count of the widened loop.
Definition at line 2608 of file LoopVectorize.cpp.
References assert(), Builder, Cost, llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateURem(), llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::ConstantInt::get(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), getOrCreateTripCount(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::isPowerOf2_32(), llvm::LoopVectorizationCostModel::requiresScalarEpilogue(), UF, VectorTripCount, and VF.
Referenced by createVectorizedLoopSkeleton(), and fixVectorizedLoop().
getOrCreateVectorValue()
Value * InnerLoopVectorizer::getOrCreateVectorValue (Value * V, unsigned Part)
getOrCreateVectorValue and getOrCreateScalarValue coordinate to generate a vector or scalar value on-demand if one is not yet available.
When vectorizing a loop, we visit the definition of an instruction before its uses. When visiting the definition, we either vectorize or scalarize the instruction, creating an entry for it in the corresponding map. (In some cases, such as induction variables, we will create both vector and scalar entries.) Then, as we encounter uses of the definition, we derive values for each scalar or vector use unless such a value is already available. For example, if we scalarize a definition and one of its uses is vector, we build the required vector on-demand with an insertelement sequence when visiting the use. Otherwise, if the use is scalar, we can use the existing scalar definition.
Return a value in the new loop corresponding to V from the original loop at unroll index Part. If the value has already been vectorized, the corresponding vector entry in VectorLoopValueMap is returned. If, however, the value has a scalar entry in VectorLoopValueMap, we construct a new vector value on-demand by inserting the scalar values into a vector with an insertelement sequence. If the value has been neither vectorized nor scalarized, it must be loop invariant, so we simply broadcast the value into a vector.
Definition at line 1999 of file LoopVectorize.cpp.
References assert(), B, Builder, Cost, EnableVPlanNativePath, llvm::ConstantInt::get(), llvm::VectorType::get(), llvm::UndefValue::get(), getBroadcastInstrs(), llvm::VectorizerValueMap::getScalarValue(), llvm::Value::getType(), llvm::VectorizerValueMap::getVectorValue(), llvm::VectorizerValueMap::hasAnyScalarValue(), llvm::LoopVectorizationLegality::hasStride(), llvm::VectorizerValueMap::hasVectorValue(), I, Induction, llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), Legal, packScalarIntoVectorValue(), llvm::IRBuilderBase::restoreIP(), llvm::IRBuilderBase::saveIP(), llvm::IRBuilderBase::SetInsertPoint(), llvm::VectorizerValueMap::setVectorValue(), llvm::RegState::Undef, VectorLoopValueMap, and VF.
Referenced by clearReductionWrapFlags(), fixFirstOrderRecurrence(), fixNonInductionPHIs(), fixReduction(), getOrCreateScalarValue(), truncateToMinimalBitwidths(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenGEP(), and widenInstruction().
getStepVector()
Value * InnerLoopVectorizer::getStepVector (Value * Val, int StartIdx, Value * Step, Instruction::BinaryOps Opcode = Instruction::BinaryOpsEnd) protected virtual
This function adds (StartIdx, StartIdx + Step, StartIdx + 2*Step, ...) to each vector element of Val.
The sequence starts at StartIndex. Opcode is relevant for FP induction variable.
Definition at line 1902 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::ConstantVector::get(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::FastMathFlags::setFast().
Referenced by llvm::InnerLoopUnroller::InnerLoopUnroller(), and widenIntOrFpInduction().
needsScalarInduction()
bool InnerLoopVectorizer::needsScalarInduction (Instruction * IV) const protected
Returns true if we should generate a scalar version of IV.
Definition at line 1767 of file LoopVectorize.cpp.
References llvm::any_of(), llvm::LoopBase< BlockT, LoopT >::contains(), I, OrigLoop, shouldScalarizeInstruction(), and llvm::Value::users().
Referenced by widenIntOrFpInduction().
packScalarIntoVectorValue()
void InnerLoopVectorizer::packScalarIntoVectorValue (Value * V, const VPIteration & Instance)
Construct the vector value of a scalarized value V one lane at a time.
Definition at line 2106 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilderBase::getInt32(), llvm::VectorizerValueMap::getScalarValue(), llvm::Value::getType(), llvm::VectorizerValueMap::getVectorValue(), Induction, llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::VPIteration::Lane, llvm::VPIteration::Part, llvm::VectorizerValueMap::resetVectorValue(), and VectorLoopValueMap.
Referenced by llvm::VPReplicateRecipe::execute(), and getOrCreateVectorValue().
recordVectorLoopValueForInductionCast()
void InnerLoopVectorizer::recordVectorLoopValueForInductionCast (const InductionDescriptor & ID, const Instruction * EntryVal, Value * VectorLoopValue, unsigned Part, unsigned Lane = UINT_MAX) protected
If there is a cast involved in the induction variable ID, which should be ignored in the vectorized loop body, this function records the VectorLoopValue of the respective Phi also as the VectorLoopValue of the cast.
We had already proved that the casted Phi is equal to the uncasted Phi in the vectorized loop (under a runtime guard), and therefore there is no need to vectorize the cast - the same value can be used in the vector loop for both the Phi and the cast. If VectorLoopValue is a scalarized value, Lane is also specified, Otherwise, VectorLoopValue is a widened/vectorized value.
EntryVal is the value from the original loop that maps to the vector phi node and is used to distinguish what is the IV currently being processed - original one (if EntryVal is a phi corresponding to the original IV) or the "newly-created" one based on the proof mentioned above (see also buildScalarSteps() and createVectorIntOrFPInductionPHI()). In the latter case EntryVal is a TruncInst and we must not record anything for that IV, but it's error-prone to expect callers of this routine to care about that, hence this explicit parameter.
Definition at line 1777 of file LoopVectorize.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorBase::empty(), llvm::InductionDescriptor::getCastInsts(), llvm::VectorizerValueMap::setScalarValue(), llvm::VectorizerValueMap::setVectorValue(), and VectorLoopValueMap.
Referenced by buildScalarSteps(), and widenIntOrFpInduction().
reverseVector()
Value * InnerLoopVectorizer::reverseVector (Value * Vec) protected virtual
Generate a shuffle sequence that will reverse the vector Vec.
Definition at line 2119 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::IRBuilderBase::getInt32(), llvm::Value::getType(), llvm::Type::isVectorTy(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and VF.
Referenced by llvm::InnerLoopUnroller::InnerLoopUnroller(), vectorizeInterleaveGroup(), and vectorizeMemoryInstruction().
scalarizeInstruction()
void InnerLoopVectorizer::scalarizeInstruction (Instruction * Instr, const VPIteration & Instance, bool IfPredicateInstr)
A helper function to scalarize a single Instruction in the innermost loop.
Generates a sequence of scalar instances for each lane between MinLane and MaxLane, times each part between MinPart and MaxPart, inclusive..
Definition at line 2491 of file LoopVectorize.cpp.
References AC, addNewMetadata(), assert(), Builder, llvm::Instruction::clone(), llvm::numbers::e, llvm::Value::getName(), llvm::User::getNumOperands(), llvm::User::getOperand(), getOrCreateScalarValue(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), llvm::Type::isAggregateType(), llvm::Type::isVoidTy(), op, PredicatedInstructions, llvm::AssumptionCache::registerAssumption(), setDebugLocFromInst(), llvm::Value::setName(), llvm::User::setOperand(), llvm::VectorizerValueMap::setScalarValue(), and VectorLoopValueMap.
Referenced by llvm::VPReplicateRecipe::execute().
setDebugLocFromInst()
void InnerLoopVectorizer::setDebugLocFromInst (IRBuilder<> & B, const Value * Ptr)
Set the debug location in the builder using the debug location in the instruction.
Definition at line 820 of file LoopVectorize.cpp.
References llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::dbgs(), LLVM_DEBUG, llvm::IRBuilderBase::SetCurrentDebugLocation(), UF, and VF.
Referenced by llvm::VPBlendRecipe::execute(), fixReduction(), scalarizeInstruction(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenInstruction(), and widenPHIInstruction().
shouldScalarizeInstruction()
bool InnerLoopVectorizer::shouldScalarizeInstruction (Instruction * I) const protected
Returns true if an instruction I should be scalarized instead of vectorized for the chosen vectorization factor.
Definition at line 1762 of file LoopVectorize.cpp.
References Cost, llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), and VF.
Referenced by needsScalarInduction(), and widenIntOrFpInduction().
sinkScalarOperands()
void InnerLoopVectorizer::sinkScalarOperands (Instruction * PredInst) protected
Iteratively sink the scalarized operands of a predicated instruction into the block that was created for it.
Definition at line 3939 of file LoopVectorize.cpp.
References llvm::all_of(), llvm::SetVector< T, Vector, Set >::begin(), llvm::SetVector< T, Vector, Set >::clear(), llvm::dyn_cast(), llvm::SetVector< T, Vector, Set >::end(), llvm::PHINode::getIncomingValueNumForOperand(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Instruction::getParent(), I, LI, llvm::User::op_begin(), and llvm::User::op_end().
Referenced by fixVectorizedLoop().
truncateToMinimalBitwidths()
void InnerLoopVectorizer::truncateToMinimalBitwidths () protected
Shrinks vector element sizes to the smallest bitwidth they can be legally represented as.
Definition at line 3325 of file LoopVectorize.cpp.
References B, Cost, llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::dyn_cast(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::Instruction::eraseFromParent(), llvm::SmallPtrSetImpl< PtrType >::find(), llvm::IntegerType::get(), llvm::VectorType::get(), llvm::Type::getContext(), llvm::LoopVectorizationCostModel::getMinimalBitwidths(), llvm::User::getOperand(), getOrCreateVectorValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::VectorizerValueMap::hasAnyVectorValue(), I, llvm::ARM_PROC::IE, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm_unreachable, llvm::Value::replaceAllUsesWith(), llvm::VectorizerValueMap::resetVectorValue(), SI, smallestIntegerVectorType(), llvm::Value::takeName(), UF, llvm::Value::use_empty(), and VectorLoopValueMap.
Referenced by fixVectorizedLoop().
vectorizeInterleaveGroup()
void InnerLoopVectorizer::vectorizeInterleaveGroup (Instruction * Instr, VPTransformState & State, VPValue * Addr, VPValue * BlockInMask = nullptr)
Try to vectorize the interleaved access group that Instr belongs to with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
Use State to translate given VPValues to IR values in the vectorized loop.
Definition at line 2169 of file LoopVectorize.cpp.
References llvm::InterleaveGroup< InstTy >::addMetadata(), assert(), Builder, llvm::concatenateVectors(), Cost, llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::createBitMaskForGaps(), createBitOrPointerCast(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::createInterleaveMask(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::createReplicatedMask(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::createStrideMask(), gep, llvm::VPTransformState::get(), llvm::VectorType::get(), llvm::UndefValue::get(), llvm::InterleaveGroup< InstTy >::getAlignment(), llvm::Module::getDataLayout(), llvm::InterleaveGroup< InstTy >::getFactor(), llvm::InterleaveGroup< InstTy >::getIndex(), llvm::InterleaveGroup< InstTy >::getInsertPos(), llvm::IRBuilderBase::getInt32(), llvm::LoopVectorizationCostModel::getInterleavedAccessGroup(), llvm::InterleaveGroup< InstTy >::getMember(), getMemInstValueType(), llvm::Instruction::getModule(), getOrCreateVectorValue(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerTo(), llvm::Value::getType(), I, llvm::InterleaveGroup< InstTy >::isReverse(), llvm::LoopVectorizationCostModel::isScalarEpilogueAllowed(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::InterleaveGroup< InstTy >::requiresScalarEpilogue(), reverseVector(), setDebugLocFromInst(), llvm::VectorizerValueMap::setVectorValue(), llvm::Value::stripPointerCasts(), TTI, UF, useMaskedInterleavedAccesses(), VectorLoopValueMap, and VF.
Referenced by llvm::VPInterleaveRecipe::execute(), and vectorizeMemoryInstruction().
vectorizeMemoryInstruction()
void InnerLoopVectorizer::vectorizeMemoryInstruction (Instruction * Instr, VPTransformState & State, VPValue * Addr, VPValue * BlockInMask = nullptr)
Vectorize Load and Store instructions with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
Use State to translate given VPValues to IR values in the vectorized loop.
Definition at line 2354 of file LoopVectorize.cpp.
References addMetadata(), assert(), Builder, llvm::LoopVectorizationCostModel::CM_GatherScatter, llvm::LoopVectorizationCostModel::CM_Interleave, llvm::LoopVectorizationCostModel::CM_Unknown, llvm::LoopVectorizationCostModel::CM_Widen, llvm::LoopVectorizationCostModel::CM_Widen_Reverse, Cost, llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::dyn_cast(), gep, llvm::VPTransformState::get(), llvm::VectorType::get(), llvm::UndefValue::get(), llvm::Module::getDataLayout(), llvm::IRBuilderBase::getInt32(), llvm::getLoadStoreAlignment(), getMemInstValueType(), llvm::Instruction::getModule(), getOrCreateVectorValue(), llvm::Type::getPointerTo(), llvm::DataLayout::getValueOrABITypeAlignment(), llvm::LoopVectorizationCostModel::getWideningDecision(), LI, reverseVector(), setDebugLocFromInst(), llvm::GetElementPtrInst::setIsInBounds(), llvm::VectorizerValueMap::setVectorValue(), SI, UF, llvm::Align::value(), vectorizeInterleaveGroup(), VectorLoopValueMap, and VF.
Referenced by llvm::VPWidenMemoryInstructionRecipe::execute().
widenGEP()
void InnerLoopVectorizer::widenGEP (GetElementPtrInst * GEP, unsigned UF, unsigned VF, bool IsPtrLoopInvariant, SmallBitVector & IsIndexLoopInvariant)
Vectorize a single GetElementPtrInst based on information gathered and decisions taken during planning.
Definition at line 4039 of file LoopVectorize.cpp.
References addMetadata(), llvm::SmallBitVector::all(), assert(), Builder, llvm::Instruction::clone(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::enumerate(), getOrCreateVectorValue(), llvm::GetElementPtrInst::getPointerOperand(), llvm::GetElementPtrInst::getSourceElementType(), llvm::GetElementPtrInst::indices(), llvm::IRBuilder< T, Inserter >::Insert(), llvm::GetElementPtrInst::isInBounds(), llvm::VectorizerValueMap::setVectorValue(), UF, and VectorLoopValueMap.
Referenced by llvm::VPWidenGEPRecipe::execute().
widenInstruction()
void InnerLoopVectorizer::widenInstruction (Instruction & I)
Widen a single instruction within the innermost loop.
Vectorize casts.
Definition at line 4206 of file LoopVectorize.cpp.
References llvm::MCID::Add, addMetadata(), Builder, llvm::IRBuilder< T, Inserter >::CreateNAryOp(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), getOrCreateScalarValue(), getOrCreateVectorValue(), llvm::PredicatedScalarEvolution::getSCEV(), llvm::PredicatedScalarEvolution::getSE(), llvm::ScalarEvolution::isLoopInvariant(), llvm_unreachable, llvm::User::operands(), OrigLoop, PSE, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MCID::Select, setDebugLocFromInst(), llvm::VectorizerValueMap::setVectorValue(), UF, and VectorLoopValueMap.
Referenced by InnerLoopVectorizer().
widenIntOrFpInduction()
void InnerLoopVectorizer::widenIntOrFpInduction (PHINode * IV, TruncInst * Trunc = nullptr)
Widen an integer or floating-point induction variable IV.
If Trunc is provided, the integer induction variable will first be truncated to the corresponding type.
Definition at line 1805 of file LoopVectorize.cpp.
References addMetadata(), assert(), Builder, buildScalarSteps(), llvm::IRBuilder< T, Inserter >::CreateCast(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), createVectorIntOrFpInductionPHI(), emitTransformedIndex(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), getBroadcastInstrs(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::BasicBlock::getModule(), llvm::PredicatedScalarEvolution::getSE(), getStepVector(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), Induction, llvm::Type::isIntegerTy(), llvm::ScalarEvolution::isLoopInvariant(), llvm::ScalarEvolution::isSCEVable(), Legal, LoopVectorPreHeader, needsScalarInduction(), OldInduction, OrigLoop, PSE, recordVectorLoopValueForInductionCast(), llvm::Value::setName(), llvm::VectorizerValueMap::setVectorValue(), shouldScalarizeInstruction(), UF, VectorLoopValueMap, and VF.
Referenced by llvm::VPWidenIntOrFpInductionRecipe::execute().
widenPHIInstruction()
void InnerLoopVectorizer::widenPHIInstruction (Instruction * PN, unsigned UF, unsigned VF)
Vectorize a single PHINode in a block.
This method handles the induction variable canonicalization. It supports both VF = 1 for unrolled loops and arbitrary length vectors.
Definition at line 4108 of file LoopVectorize.cpp.
References assert(), Builder, Cost, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::count(), llvm::PHINode::Create(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), emitTransformedIndex(), EnableVPlanNativePath, llvm::ConstantInt::get(), llvm::VectorType::get(), llvm::Module::getDataLayout(), llvm::BasicBlock::getFirstInsertionPt(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::BasicBlock::getModule(), llvm::User::getNumOperands(), llvm::Instruction::getParent(), llvm::PredicatedScalarEvolution::getSE(), llvm::Value::getType(), llvm::InductionDescriptor::IK_FpInduction, llvm::InductionDescriptor::IK_IntInduction, llvm::InductionDescriptor::IK_NoInduction, llvm::InductionDescriptor::IK_PtrInduction, Induction, llvm::LoopVectorizationLegality::isFirstOrderRecurrence(), llvm::Type::isPointerTy(), llvm::LoopVectorizationLegality::isReductionVariable(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), Legal, llvm_unreachable, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), LoopVectorBody, OrigLoop, OrigPHIsToFix, P, PSE, setDebugLocFromInst(), llvm::Value::setName(), llvm::VectorizerValueMap::setScalarValue(), llvm::VectorizerValueMap::setVectorValue(), UF, VectorLoopValueMap, and VF.
Referenced by llvm::VPWidenPHIRecipe::execute().
Friends And Related Function Documentation
LoopVectorizationPlanner
friend class LoopVectorizationPlanner friend
Definition at line 508 of file LoopVectorize.cpp.
Member Data Documentation
AA
AliasAnalysis* llvm::InnerLoopVectorizer::AA protected
Alias Analysis.
Definition at line 685 of file LoopVectorize.cpp.
Referenced by collectSupportedLoops(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizePass::run(), and llvm::LoopVectorizePass::runImpl().
AC
AssumptionCache* llvm::InnerLoopVectorizer::AC protected
Assumption Cache.
Definition at line 694 of file LoopVectorize.cpp.
Referenced by collectSupportedLoops(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizePass::run(), llvm::LoopVectorizePass::runImpl(), and scalarizeInstruction().
AddedSafetyChecks
bool llvm::InnerLoopVectorizer::AddedSafetyChecks = false protected
Definition at line 768 of file LoopVectorize.cpp.
Referenced by areSafetyChecksAdded(), emitMemRuntimeChecks(), and emitSCEVChecks().
Builder
IRBuilder llvm::InnerLoopVectorizer::Builder protected
The builder that we use.
Definition at line 715 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), createBitOrPointerCast(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::VPRecipeBuilder::createEdgeMask(), createVectorizedLoopSkeleton(), emitMinimumIterationCountCheck(), llvm::LoopVectorizationPlanner::executePlan(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), fixNonInductionPHIs(), fixReduction(), getBroadcastInstrs(), getOrCreateScalarValue(), getOrCreateTripCount(), getOrCreateVectorTripCount(), getOrCreateVectorValue(), getStepVector(), packScalarIntoVectorValue(), reverseVector(), scalarizeInstruction(), llvm::VPRecipeBuilder::tryToCreateRecipe(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenGEP(), widenInstruction(), widenIntOrFpInduction(), and widenPHIInstruction().
Cost
LoopVectorizationCostModel* llvm::InnerLoopVectorizer::Cost protected
The profitablity analysis.
Definition at line 765 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), fixLCSSAPHIs(), fixReduction(), getOrCreateScalarValue(), getOrCreateVectorTripCount(), getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::getVectorCallCost(), isStrideMul(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), shouldScalarizeInstruction(), truncateToMinimalBitwidths(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), and widenPHIInstruction().
DT
DominatorTree* llvm::InnerLoopVectorizer::DT protected
Dominator Tree.
Definition at line 682 of file LoopVectorize.cpp.
Referenced by collectSupportedLoops(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), emitSCEVChecks(), llvm::LoopVectorizationPlanner::executePlan(), getBroadcastInstrs(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), llvm::LoopVectorizePass::run(), and llvm::LoopVectorizePass::runImpl().
Induction
PHINode* llvm::InnerLoopVectorizer::Induction = nullptr protected
The new Induction variable which was added to the new block.
Definition at line 741 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), createVectorizedLoopSkeleton(), getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), packScalarIntoVectorValue(), widenIntOrFpInduction(), and widenPHIInstruction().
IVEndValues
DenseMap<PHINode *, Value *> llvm::InnerLoopVectorizer::IVEndValues protected
Definition at line 772 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), and fixVectorizedLoop().
Legal
LoopVectorizationLegality* llvm::InnerLoopVectorizer::Legal protected
The legality analysis.
Definition at line 762 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::blockNeedsPredication(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::createLoopVectorizePass(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), fixCrossIterationPHIs(), fixReduction(), fixVectorizedLoop(), getOrCreateTripCount(), getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::LoopVectorizationCostModel::isLegalMaskedLoad(), llvm::LoopVectorizationCostModel::isLegalMaskedStore(), llvm::LoopVectorizationCostModel::isOptimizableIVTruncate(), llvm::LoopVectorizationCostModel::isPredicatedInst(), llvm::LoopVectorizationCostModel::isScalarWithPredication(), isStrideMul(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::VPRecipeBuilder::tryToCreateRecipe(), llvm::VPRecipeBuilder::tryToOptimizeInduction(), llvm::VPRecipeBuilder::tryToWidenMemory(), widenIntOrFpInduction(), and widenPHIInstruction().
LI
LoopInfo* llvm::InnerLoopVectorizer::LI protected
Loop Info.
Definition at line 679 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::calculateRegisterUsage(), collectSupportedLoops(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), emitSCEVChecks(), llvm::LoopVectorizationPlanner::executePlan(), fixFirstOrderRecurrence(), fixReduction(), fixVectorizedLoop(), llvm::LoopVectorizationCostModel::isLegalGatherOrScatter(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizePass::run(), llvm::LoopVectorizePass::runImpl(), sinkScalarOperands(), llvm::VPRecipeBuilder::tryToCreateRecipe(), and vectorizeMemoryInstruction().
LoopBypassBlocks
SmallVector<BasicBlock *, 4> llvm::InnerLoopVectorizer::LoopBypassBlocks protected
A list of all bypass blocks. The first block is the entry of the loop.
Definition at line 738 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), emitSCEVChecks(), and fixReduction().
LoopExitBlock
BasicBlock* llvm::InnerLoopVectorizer::LoopExitBlock protected
The ExitBlock of the scalar loop.
Definition at line 729 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), emitSCEVChecks(), fixLCSSAPHIs(), and fixReduction().
LoopMiddleBlock
BasicBlock* llvm::InnerLoopVectorizer::LoopMiddleBlock protected
Middle Block between the vector and the scalar.
Definition at line 726 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), fixReduction(), and fixVectorizedLoop().
LoopScalarBody
BasicBlock* llvm::InnerLoopVectorizer::LoopScalarBody protected
The scalar loop body.
Definition at line 735 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton().
LoopScalarPreHeader
BasicBlock* llvm::InnerLoopVectorizer::LoopScalarPreHeader protected
The scalar-loop preheader.
Definition at line 723 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), fixFirstOrderRecurrence(), and fixReduction().
LoopVectorBody
BasicBlock* llvm::InnerLoopVectorizer::LoopVectorBody protected
The vector loop body.
Definition at line 732 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), fixFirstOrderRecurrence(), fixReduction(), fixVectorizedLoop(), and widenPHIInstruction().
LoopVectorPreHeader
BasicBlock* llvm::InnerLoopVectorizer::LoopVectorPreHeader protected
The vector-loop preheader.
Definition at line 720 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), emitSCEVChecks(), fixFirstOrderRecurrence(), fixReduction(), getBroadcastInstrs(), and widenIntOrFpInduction().
LVer
std::unique_ptr<LoopVersioning> llvm::InnerLoopVectorizer::LVer protected
LoopVersioning.
It's only set up (non-null) if memchecks were used.
This is currently only used to add no-alias metadata based on the memchecks. The actually versioning is performed manually.
Definition at line 704 of file LoopVectorize.cpp.
Referenced by addNewMetadata(), and emitMemRuntimeChecks().
OldInduction
PHINode* llvm::InnerLoopVectorizer::OldInduction = nullptr protected
The induction variable of the old basic block.
Definition at line 744 of file LoopVectorize.cpp.
Referenced by createVectorizedLoopSkeleton(), and widenIntOrFpInduction().
ORE
OptimizationRemarkEmitter* llvm::InnerLoopVectorizer::ORE protected
Interface to emit optimization remarks.
Definition at line 697 of file LoopVectorize.cpp.
Referenced by collectSupportedLoops(), llvm::LoopVectorizationCostModel::computeMaxVF(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizePass::run(), llvm::LoopVectorizePass::runImpl(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), and llvm::LoopVectorizationCostModel::selectVectorizationFactor().
OrigLoop
Loop* llvm::InnerLoopVectorizer::OrigLoop protected
The original loop.
Definition at line 671 of file LoopVectorize.cpp.
Referenced by clearReductionWrapFlags(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::VPRecipeBuilder::createBlockInMask(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), fixCrossIterationPHIs(), fixFirstOrderRecurrence(), fixReduction(), fixupIVUsers(), fixVectorizedLoop(), getBroadcastInstrs(), getOrCreateScalarValue(), needsScalarInduction(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::VPRecipeBuilder::tryToBlend(), llvm::VPRecipeBuilder::tryToCreateRecipe(), widenInstruction(), widenIntOrFpInduction(), and widenPHIInstruction().
OrigPHIsToFix
SmallVector<PHINode *, 8> llvm::InnerLoopVectorizer::OrigPHIsToFix protected
Definition at line 776 of file LoopVectorize.cpp.
Referenced by fixNonInductionPHIs(), fixVectorizedLoop(), and widenPHIInstruction().
PredicatedInstructions
SmallVector<Instruction *, 4> llvm::InnerLoopVectorizer::PredicatedInstructions protected
Store instructions that were predicated.
Definition at line 753 of file LoopVectorize.cpp.
Referenced by fixVectorizedLoop(), and scalarizeInstruction().
PSE
PredicatedScalarEvolution& llvm::InnerLoopVectorizer::PSE protected
A wrapper around ScalarEvolution used to add runtime SCEV checks.
Applies dynamic knowledge to simplify SCEV expressions and converts them to a more usable form.
Definition at line 676 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), emitSCEVChecks(), fixupIVUsers(), fixVectorizedLoop(), getOrCreateTripCount(), isStrideMul(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), widenInstruction(), widenIntOrFpInduction(), and widenPHIInstruction().
TLI
const TargetLibraryInfo* llvm::InnerLoopVectorizer::TLI protected
Target Library Info.
Definition at line 688 of file LoopVectorize.cpp.
Referenced by collectSupportedLoops(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizePass::run(), llvm::LoopVectorizePass::runImpl(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::VPRecipeBuilder::tryToCreateRecipe(), and llvm::VPRecipeBuilder::tryToWiden().
TripCount
Value* llvm::InnerLoopVectorizer::TripCount = nullptr protected
Trip count of the original loop.
Definition at line 756 of file LoopVectorize.cpp.
Referenced by getOrCreateTripCount().
TTI
const TargetTransformInfo* llvm::InnerLoopVectorizer::TTI protected
Target Transform Info.
Definition at line 691 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), collectSupportedLoops(), llvm::LoopVectorizationCostModel::computeMaxVF(), fixReduction(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::LoopVectorizationCostModel::isLegalMaskedGather(), llvm::LoopVectorizationCostModel::isLegalMaskedLoad(), llvm::LoopVectorizationCostModel::isLegalMaskedScatter(), llvm::LoopVectorizationCostModel::isLegalMaskedStore(), llvm::LoopVectorizationCostModel::isOptimizableIVTruncate(), isStrideMul(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizePass::run(), llvm::LoopVectorizePass::runImpl(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), and vectorizeInterleaveGroup().
UF
unsigned llvm::InnerLoopVectorizer::UF protected
The vectorization unroll factor to use.
Each scalar is vectorized to this many different vector instructions.
Definition at line 712 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), clearReductionWrapFlags(), createVectorizedLoopSkeleton(), emitMinimumIterationCountCheck(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), fixReduction(), getOrCreateVectorTripCount(), llvm::LoopVectorizationPlanner::setBestPlan(), setDebugLocFromInst(), truncateToMinimalBitwidths(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenGEP(), widenInstruction(), widenIntOrFpInduction(), and widenPHIInstruction().
VectorLoopValueMap
VectorizerValueMap llvm::InnerLoopVectorizer::VectorLoopValueMap protected
Maps values from the original loop to their corresponding values in the vectorized loop.
A key value can map to either vector values, scalar values or both kinds of values, depending on whether the key was vectorized and scalarized.
Definition at line 750 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), llvm::LoopVectorizationPlanner::executePlan(), fixFirstOrderRecurrence(), fixNonInductionPHIs(), fixReduction(), getOrCreateScalarValue(), getOrCreateVectorValue(), packScalarIntoVectorValue(), recordVectorLoopValueForInductionCast(), scalarizeInstruction(), truncateToMinimalBitwidths(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenGEP(), widenInstruction(), widenIntOrFpInduction(), and widenPHIInstruction().
VectorTripCount
Value* llvm::InnerLoopVectorizer::VectorTripCount = nullptr protected
Trip count of the widened loop (TripCount - TripCount % (VF*UF))
Definition at line 759 of file LoopVectorize.cpp.
Referenced by getOrCreateVectorTripCount().
VF
unsigned llvm::InnerLoopVectorizer::VF protected
The vectorization SIMD factor to use.
Each vector will have this many vector elements.
Definition at line 708 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), llvm::LoopVectorizationPlanner::buildVPlans(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), createBitOrPointerCast(), createVectorizedLoopSkeleton(), emitMinimumIterationCountCheck(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), fixReduction(), fixVectorizedLoop(), getBroadcastInstrs(), getOrCreateScalarValue(), getOrCreateVectorTripCount(), getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), isStrideMul(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), reverseVector(), llvm::LoopVectorizationCostModel::selectUserVectorizationFactor(), llvm::LoopVectorizationPlanner::setBestPlan(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), setDebugLocFromInst(), shouldScalarizeInstruction(), llvm::VPRecipeBuilder::tryToCreateRecipe(), llvm::VPRecipeBuilder::tryToOptimizeInduction(), llvm::VPRecipeBuilder::tryToWiden(), llvm::VPRecipeBuilder::tryToWidenMemory(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenIntOrFpInduction(), and widenPHIInstruction().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorize.cpp