LLVM: llvm::orc::LegacyLookupFnResolver< LegacyLookupFn > Class Template Reference
llvm::orc::LegacyLookupFnResolver< LegacyLookupFn > Class Template Reference final
An ORC SymbolResolver implementation that uses a legacy findSymbol-like function to perform lookup;.
#include "llvm/ExecutionEngine/Orc/Legacy.h"
Public Types
using ErrorReporter = std::function< void(Error)>
Public Member Functions
LegacyLookupFnResolver (ExecutionSession &ES, LegacyLookupFn LegacyLookup, ErrorReporter ReportError)
SymbolNameSet getResponsibilitySet (const SymbolNameSet &Symbols) final
Returns the subset of the given symbols that the caller is responsible for materializing.
SymbolNameSet lookup (std::shared_ptr< AsynchronousSymbolQuery > Query, SymbolNameSet Symbols) final
For each symbol in Symbols that can be found, assigns that symbols value in Query.
Public Member Functions inherited from llvm::orc::SymbolResolver
virtual ~SymbolResolver ()=default
Detailed Description
template<typename LegacyLookupFn>
class llvm::orc::LegacyLookupFnResolver< LegacyLookupFn >
An ORC SymbolResolver implementation that uses a legacy findSymbol-like function to perform lookup;.
Definition at line 174 of file Legacy.h.
Member Typedef Documentation
ErrorReporter
template<typename LegacyLookupFn > using llvm::orc::LegacyLookupFnResolver< LegacyLookupFn >::ErrorReporter = std::function<void(Error)>
Definition at line 176 of file Legacy.h.
Constructor & Destructor Documentation
LegacyLookupFnResolver()
template<typename LegacyLookupFn > llvm::orc::LegacyLookupFnResolver< LegacyLookupFn >::LegacyLookupFnResolver (ExecutionSession & ES, LegacyLookupFn LegacyLookup, ErrorReporter ReportError) inline
Definition at line 178 of file Legacy.h.
Member Function Documentation
getResponsibilitySet()
template<typename LegacyLookupFn > SymbolNameSet llvm::orc::LegacyLookupFnResolver< LegacyLookupFn >::getResponsibilitySet (const SymbolNameSet & Symbols) inline final virtual
Returns the subset of the given symbols that the caller is responsible for materializing.
Implements llvm::orc::SymbolResolver.
Definition at line 183 of file Legacy.h.
References llvm::orc::getResponsibilitySetWithLegacyFn(), and ReportError().
lookup()
template<typename LegacyLookupFn > SymbolNameSet llvm::orc::LegacyLookupFnResolver< LegacyLookupFn >::lookup (std::shared_ptr< AsynchronousSymbolQuery > Query, SymbolNameSet Symbols) inline final virtual
For each symbol in Symbols that can be found, assigns that symbols value in Query.
Returns the set of symbols that could not be found.
Implements llvm::orc::SymbolResolver.
Definition at line 193 of file Legacy.h.
References llvm::orc::lookupWithLegacyFn(), and ReportError().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Legacy.h