LLVM: llvm::codeview::BitFieldRecord Class Reference
llvm::codeview::BitFieldRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
BitFieldRecord ()=default
BitFieldRecord (TypeRecordKind Kind)
BitFieldRecord (TypeIndex Type, uint8_t BitSize, uint8_t BitOffset)
TypeIndex getType () const
uint8_t getBitOffset () const
uint8_t getBitSize () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex Type
uint8_t BitSize = 0
uint8_t BitOffset = 0
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 540 of file TypeRecord.h.
Constructor & Destructor Documentation
BitFieldRecord() [1/3]
llvm::codeview::BitFieldRecord::BitFieldRecord () default
BitFieldRecord() [2/3]
llvm::codeview::BitFieldRecord::BitFieldRecord (TypeRecordKind Kind) inline explicit
Definition at line 543 of file TypeRecord.h.
BitFieldRecord() [3/3]
llvm::codeview::BitFieldRecord::BitFieldRecord (TypeIndex Type, uint8_t BitSize, uint8_t BitOffset) inline
Definition at line 544 of file TypeRecord.h.
Member Function Documentation
getBitOffset()
uint8_t llvm::codeview::BitFieldRecord::getBitOffset () const inline
Definition at line 549 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getBitSize()
uint8_t llvm::codeview::BitFieldRecord::getBitSize () const inline
Definition at line 550 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getType()
TypeIndex llvm::codeview::BitFieldRecord::getType () const inline
Definition at line 548 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
BitOffset
uint8_t llvm::codeview::BitFieldRecord::BitOffset = 0
Definition at line 554 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
BitSize
uint8_t llvm::codeview::BitFieldRecord::BitSize = 0
Definition at line 553 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Type
TypeIndex llvm::codeview::BitFieldRecord::Type
Definition at line 552 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h