LLVM: llvm::MetadataTracking Class Reference
llvm::MetadataTracking Class Reference
API for tracking metadata references through RAUW and deletion.
#include "llvm/IR/Metadata.h"
Public Types
using OwnerTy = PointerUnion< MetadataAsValue *, Metadata * >
Static Public Member Functions
static bool track (Metadata *&MD)
Track the reference to metadata.
static bool track (void *Ref, Metadata &MD, Metadata &Owner)
Track the reference to metadata for Metadata.
static bool track (void *Ref, Metadata &MD, MetadataAsValue &Owner)
Track the reference to metadata for MetadataAsValue.
static void untrack (Metadata *&MD)
Stop tracking a reference to metadata.
static void untrack (void *Ref, Metadata &MD)
static bool retrack (Metadata *&MD, Metadata *&New)
Move tracking from one reference to another.
static bool retrack (void *Ref, Metadata &MD, void *New)
static bool isReplaceable (const Metadata &MD)
Check whether metadata is replaceable.
Detailed Description
API for tracking metadata references through RAUW and deletion.
Shared API for updating Metadata pointers in subclasses that support RAUW.
This API is not meant to be used directly. See TrackingMDRef for a user-friendly tracking reference.
Definition at line 210 of file Metadata.h.
Member Typedef Documentation
OwnerTy
using llvm::MetadataTracking::OwnerTy = PointerUnion<MetadataAsValue *, Metadata *>
Definition at line 265 of file Metadata.h.
Member Function Documentation
isReplaceable()
bool MetadataTracking::isReplaceable (const Metadata & MD) static
Check whether metadata is replaceable.
Definition at line 193 of file Metadata.cpp.
References assert(), I, and llvm::Ref.
Referenced by llvm::TrackingMDRef::hasTrivialDestructor().
retrack() [1/2]
static bool llvm::MetadataTracking::retrack (Metadata *& MD, Metadata *& New) inline static
Move tracking from one reference to another.
Semantically equivalent to untrack(MD) followed by track(New), except that ownership callbacks are maintained.
Note: it is an error if *MD does not equal New.
Returns
true iff tracking is supported by MD.
Definition at line 257 of file Metadata.h.
Referenced by llvm::TrackingMDRef::operator!=().
retrack() [2/2]
bool MetadataTracking::retrack (void * Ref, Metadata & MD, void * New) static
Definition at line 178 of file Metadata.cpp.
References assert().
track() [1/3]
static bool llvm::MetadataTracking::track (Metadata *& MD) inline static
Track the reference to metadata.
Register MD with *MD, if the subclass supports tracking. If *MD gets RAUW'ed, MD will be updated to the new address. If *MD gets deleted, MD will be set to nullptr.
If tracking isn't supported, *MD will not change.
Returns
true iff tracking is supported by MD.
Definition at line 221 of file Metadata.h.
Referenced by llvm::MetadataAsValue::getIfExists(), llvm::TrackingMDRef::operator!=(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::DistinctMDOperandPlaceholder::replaceUseWith(), and llvm::MDOperand::reset().
track() [2/3]
static bool llvm::MetadataTracking::track (void * Ref, Metadata & MD, Metadata & Owner) inline static
Track the reference to metadata for Metadata.
As track(Metadata*&), but with support for calling back to Owner to tell it that its operand changed. This could trigger Owner being re-uniqued.
Definition at line 230 of file Metadata.h.
track() [3/3]
static bool llvm::MetadataTracking::track (void * Ref, Metadata & MD, MetadataAsValue & Owner) inline static
Track the reference to metadata for MetadataAsValue.
As track(Metadata*&), but with support for calling back to Owner to tell it that its operand changed. This could trigger Owner being re-uniqued.
Definition at line 239 of file Metadata.h.
untrack() [1/2]
static void llvm::MetadataTracking::untrack (Metadata *& MD) inline static
Stop tracking a reference to metadata.
Stops *MD from tracking MD.
Definition at line 246 of file Metadata.h.
References llvm::Ref, and untrack().
Referenced by llvm::MetadataAsValue::getIfExists(), llvm::TrackingMDRef::operator!=(), llvm::DistinctMDOperandPlaceholder::replaceUseWith(), llvm::MDOperand::reset(), and untrack().
untrack() [2/2]
void MetadataTracking::untrack (void * Ref, Metadata & MD) static
Definition at line 170 of file Metadata.cpp.
References assert().
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/IR/Metadata.cpp