LLVM: llvm::MCAsmInfo Class Reference
llvm::MCAsmInfo Class Reference
This class is intended to be used as a base class for asm properties and features specific to the target.
#include "llvm/MC/MCAsmInfo.h"
Public Member Functions
MCAsmInfo ()
virtual ~MCAsmInfo ()
unsigned getCodePointerSize () const
Get the code pointer size in bytes.
unsigned getCalleeSaveStackSlotSize () const
Get the callee-saved register stack slot size in bytes.
bool isLittleEndian () const
True if the target is little endian.
bool isStackGrowthDirectionUp () const
True if target stack grow up.
bool hasSubsectionsViaSymbols () const
const char * getData8bitsDirective () const
const char * getData16bitsDirective () const
const char * getData32bitsDirective () const
const char * getData64bitsDirective () const
const char * getGPRel64Directive () const
const char * getGPRel32Directive () const
const char * getDTPRel64Directive () const
const char * getDTPRel32Directive () const
const char * getTPRel64Directive () const
const char * getTPRel32Directive () const
virtual MCSection * getNonexecutableStackSection (MCContext &Ctx) const
Targets can implement this method to specify a section to switch to if the translation unit doesn't have any trampolines that require an executable stack.
virtual bool isSectionAtomizableBySymbols (const MCSection &Section) const
True if the section is atomized using the symbols in it.
virtual const MCExpr * getExprForPersonalitySymbol (const MCSymbol *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCExpr * getExprForFDESymbol (const MCSymbol *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual bool isAcceptableChar (char C) const
Return true if C is an acceptable character inside a symbol name.
virtual bool isValidUnquotedName (StringRef Name) const
Return true if the identifier Name does not need quotes to be syntactically correct.
virtual bool shouldOmitSectionDirective (StringRef SectionName) const
Return true if the .section directive should be omitted when emitting SectionName.
bool usesSunStyleELFSectionSwitchSyntax () const
bool usesELFSectionDirectiveForBSS () const
bool needsDwarfSectionOffsetDirective () const
bool hasMachoZeroFillDirective () const
bool hasMachoTBSSDirective () const
bool hasCOFFAssociativeComdats () const
bool hasCOFFComdatConstants () const
virtual unsigned getMaxInstLength (const MCSubtargetInfo *STI=nullptr) const
Returns the maximum possible encoded instruction size in bytes.
unsigned getMinInstAlignment () const
bool getDollarIsPC () const
const char * getSeparatorString () const
unsigned getCommentColumn () const
This indicates the column (zero-based) at which asm comments should be printed.
StringRef getCommentString () const
const char * getLabelSuffix () const
bool useAssignmentForEHBegin () const
bool needsLocalForSize () const
StringRef getPrivateGlobalPrefix () const
StringRef getPrivateLabelPrefix () const
bool hasLinkerPrivateGlobalPrefix () const
StringRef getLinkerPrivateGlobalPrefix () const
const char * getInlineAsmStart () const
const char * getInlineAsmEnd () const
const char * getCode16Directive () const
const char * getCode32Directive () const
const char * getCode64Directive () const
unsigned getAssemblerDialect () const
bool doesAllowAtInName () const
bool supportsNameQuoting () const
bool doesSupportDataRegionDirectives () const
bool useDotAlignForAlignment () const
const char * getZeroDirective () const
const char * getAsciiDirective () const
const char * getAscizDirective () const
bool getAlignmentIsInBytes () const
unsigned getTextAlignFillValue () const
const char * getGlobalDirective () const
bool doesSetDirectiveSuppressReloc () const
bool hasAggressiveSymbolFolding () const
bool getCOMMDirectiveAlignmentIsInBytes () const
LCOMM::LCOMMType getLCOMMDirectiveAlignmentType () const
bool hasFunctionAlignment () const
bool hasDotTypeDotSizeDirective () const
bool hasSingleParameterDotFile () const
bool hasIdentDirective () const
bool hasNoDeadStrip () const
bool hasAltEntry () const
const char * getWeakDirective () const
const char * getWeakRefDirective () const
bool hasWeakDefDirective () const
bool hasWeakDefCanBeHiddenDirective () const
bool hasLinkOnceDirective () const
bool hasDotLGloblDirective () const
MCSymbolAttr getHiddenVisibilityAttr () const
MCSymbolAttr getHiddenDeclarationVisibilityAttr () const
MCSymbolAttr getProtectedVisibilityAttr () const
bool getSymbolsHaveSMC () const
bool doesSupportDebugInformation () const
bool doesSupportExceptionHandling () const
ExceptionHandling getExceptionHandlingType () const
WinEH::EncodingType getWinEHEncodingType () const
void setExceptionsType (ExceptionHandling EH)
bool usesCFIForEH () const
Returns true if the exception handling method for the platform uses call frame information to unwind.
bool usesWindowsCFI () const
bool doesDwarfUseRelocationsAcrossSections () const
bool doDwarfFDESymbolsUseAbsDiff () const
bool useDwarfRegNumForCFI () const
bool useParensForSymbolVariant () const
bool supportsExtendedDwarfLocDirective () const
void addInitialFrameState (const MCCFIInstruction &Inst)
const std::vector< MCCFIInstruction > & getInitialFrameState () const
bool useIntegratedAssembler () const
Return true if assembly (inline or otherwise) should be parsed.
virtual void setUseIntegratedAssembler (bool Value)
Set whether assembly (inline or otherwise) should be parsed.
bool preserveAsmComments () const
Return true if assembly (inline or otherwise) should be parsed.
virtual void setPreserveAsmComments (bool Value)
Set whether assembly (inline or otherwise) should be parsed.
DebugCompressionType compressDebugSections () const
void setCompressDebugSections (DebugCompressionType CompressDebugSections)
bool shouldUseLogicalShr () const
bool canRelaxRelocations () const
void setRelaxELFRelocations (bool V)
bool hasMipsExpressions () const
bool needsFunctionDescriptors () const
Protected Attributes
unsigned CodePointerSize = 4
Code pointer size in bytes. Default is 4.
unsigned CalleeSaveStackSlotSize = 4
Size of the stack slot reserved for callee-saved registers, in bytes.
bool IsLittleEndian = true
True if target is little endian. Default is true.
bool StackGrowsUp = false
True if target stack grow up. Default is false.
bool HasSubsectionsViaSymbols = false
True if this target has the MachO .subsections_via_symbols directive.
bool HasMachoZeroFillDirective = false
True if this is a MachO target that supports the macho-specific .zerofill directive for emitting BSS Symbols.
bool HasMachoTBSSDirective = false
True if this is a MachO target that supports the macho-specific .tbss directive for emitting thread local BSS Symbols.
bool HasCOFFAssociativeComdats = false
True if this is a non-GNU COFF target.
bool HasCOFFComdatConstants = false
True if this is a non-GNU COFF target.
unsigned MaxInstLength = 4
This is the maximum possible length of an instruction, which is needed to compute the size of an inline asm.
unsigned MinInstAlignment = 1
Every possible instruction length is a multiple of this value.
bool DollarIsPC = false
The '$' token, when not referencing an identifier or constant, refers to the current PC.
const char * SeparatorString
This string, if specified, is used to separate instructions from each other when on the same line.
StringRef CommentString
This indicates the comment character used by the assembler.
const char * LabelSuffix
This is appended to emitted labels. Defaults to ":".
bool UseAssignmentForEHBegin = false
bool NeedsLocalForSize = false
StringRef PrivateGlobalPrefix
This prefix is used for globals like constant pool entries that are completely private to the .s file and should not have names in the .o file.
StringRef PrivateLabelPrefix
This prefix is used for labels for basic blocks.
StringRef LinkerPrivateGlobalPrefix
This prefix is used for symbols that should be passed through the assembler but be removed by the linker.
const char * InlineAsmStart
If these are nonempty, they contain a directive to emit before and after an inline assembly statement.
const char * InlineAsmEnd
const char * Code16Directive
These are assembly directives that tells the assembler to interpret the following instructions differently.
const char * Code32Directive
const char * Code64Directive
unsigned AssemblerDialect = 0
Which dialect of an assembler variant to use. Defaults to 0.
bool AllowAtInName = false
This is true if the assembler allows @ characters in symbol names.
bool SupportsQuotedNames = true
If this is true, symbol names with invalid characters will be printed in quotes.
bool UseDataRegionDirectives = false
This is true if data region markers should be printed as ".data_region/.end_data_region" directives.
bool UseDotAlignForAlignment = false
True if .align is to be used for alignment.
const char * ZeroDirective
This should be set to the directive used to get some number of zero bytes emitted to the current section.
const char * AsciiDirective
This directive allows emission of an ascii string with the standard C escape characters embedded into it.
const char * AscizDirective
If not null, this allows for special handling of zero terminated strings on this target.
const char * Data8bitsDirective
These directives are used to output some unit of integer data to the current section.
const char * Data16bitsDirective
const char * Data32bitsDirective
const char * Data64bitsDirective
const char * GPRel64Directive = nullptr
If non-null, a directive that is used to emit a word which should be relocated as a 64-bit GP-relative offset, e.g.
const char * GPRel32Directive = nullptr
If non-null, a directive that is used to emit a word which should be relocated as a 32-bit GP-relative offset, e.g.
const char * DTPRel32Directive = nullptr
If non-null, directives that are used to emit a word/dword which should be relocated as a 32/64-bit DTP/TP-relative offset, e.g.
const char * DTPRel64Directive = nullptr
const char * TPRel32Directive = nullptr
const char * TPRel64Directive = nullptr
bool SunStyleELFSectionSwitchSyntax = false
This is true if this target uses "Sun Style" syntax for section switching ("#alloc,#write" etc) instead of the normal ELF syntax (,"a,w") in .section directives.
bool UsesELFSectionDirectiveForBSS = false
This is true if this target uses ELF '.section' directive before the '.bss' one.
bool NeedsDwarfSectionOffsetDirective = false
bool AlignmentIsInBytes = true
If this is true (the default) then the asmprinter emits ".align N" directives, where N is the number of bytes to align to.
unsigned TextAlignFillValue = 0
If non-zero, this is used to fill the executable space created as the result of a alignment directive.
const char * GlobalDirective
This is the directive used to declare a global entity.
bool SetDirectiveSuppressesReloc = false
True if the expression .long f - g uses a relocation but it can be suppressed by writing a = f - g .long a.
bool HasAggressiveSymbolFolding = true
False if the assembler requires that we use.
bool COMMDirectiveAlignmentIsInBytes = true
True is .comm's and .lcomms optional alignment is to be specified in bytes instead of log2(n).
LCOMM::LCOMMType LCOMMDirectiveAlignmentType = LCOMM::NoAlignment
Describes if the .lcomm directive for the target supports an alignment argument and how it is interpreted.
bool HasFunctionAlignment = true
bool HasDotTypeDotSizeDirective = true
True if the target has .type and .size directives, this is true for most ELF targets.
bool HasSingleParameterDotFile = true
True if the target has a single parameter .file directive, this is true for ELF targets.
bool HasIdentDirective = false
True if the target has a .ident directive, this is true for ELF targets.
bool HasNoDeadStrip = false
True if this target supports the MachO .no_dead_strip directive.
bool HasAltEntry = false
True if this target supports the MachO .alt_entry directive.
const char * WeakDirective
Used to declare a global as being a weak symbol. Defaults to ".weak".
const char * WeakRefDirective = nullptr
This directive, if non-null, is used to declare a global as being a weak undefined symbol.
bool HasWeakDefDirective = false
True if we have a directive to declare a global as being a weak defined symbol.
bool HasWeakDefCanBeHiddenDirective = false
True if we have a directive to declare a global as being a weak defined symbol that can be hidden (unexported).
bool HasLinkOnceDirective = false
True if we have a .linkonce directive.
bool HasDotLGloblDirective = false
True if we have a .lglobl directive, which is used to emit the information of a static symbol into the symbol table.
MCSymbolAttr HiddenVisibilityAttr = MCSA_Hidden
This attribute, if not MCSA_Invalid, is used to declare a symbol as having hidden visibility.
MCSymbolAttr HiddenDeclarationVisibilityAttr = MCSA_Hidden
This attribute, if not MCSA_Invalid, is used to declare an undefined symbol as having hidden visibility.
MCSymbolAttr ProtectedVisibilityAttr = MCSA_Protected
This attribute, if not MCSA_Invalid, is used to declare a symbol as having protected visibility.
bool SymbolsHaveSMC = false
bool SupportsDebugInformation = false
True if target supports emission of debugging information.
ExceptionHandling ExceptionsType = ExceptionHandling::None
Exception handling format for the target. Defaults to None.
WinEH::EncodingType WinEHEncodingType = WinEH::EncodingType::Invalid
Windows exception handling data (.pdata) encoding. Defaults to Invalid.
bool DwarfUsesRelocationsAcrossSections = true
True if Dwarf2 output generally uses relocations for references to other .debug_* sections.
bool DwarfFDESymbolsUseAbsDiff = false
True if DWARF FDE symbol reference relocations should be replaced by an absolute difference.
bool DwarfRegNumForCFI = false
True if dwarf register numbers are printed instead of symbolic register names in .cfi_* directives.
bool UseParensForSymbolVariant = false
True if target uses parens to indicate the symbol variant instead of .
bool SupportsExtendedDwarfLocDirective = true
True if the target supports flags in ".loc" directive, false if only location is allowed.
std::vector< MCCFIInstruction > InitialFrameState
bool UseIntegratedAssembler
Should we use the integrated assembler? The integrated assembler should be enabled by default (by the constructors) when failing to parse a valid piece of assembly (inline or otherwise) is considered a bug.
bool PreserveAsmComments
Preserve Comments in assembly.
DebugCompressionType CompressDebugSections = DebugCompressionType::None
Compress DWARF debug sections. Defaults to no compression.
bool UseLogicalShr = true
True if the integrated assembler should interpret 'a >> b' constant expressions as logical rather than arithmetic.
bool RelaxELFRelocations = true
bool HasMipsExpressions = false
bool NeedsFunctionDescriptors = false
Detailed Description
This class is intended to be used as a base class for asm properties and features specific to the target.
Definition at line 56 of file MCAsmInfo.h.
Constructor & Destructor Documentation
MCAsmInfo()
MCAsmInfo::MCAsmInfo () explicit
Definition at line 31 of file MCAsmInfo.cpp.
References AsciiDirective, AscizDirective, Code16Directive, Code32Directive, Code64Directive, CommentString, Data16bitsDirective, Data32bitsDirective, Data64bitsDirective, Data8bitsDirective, llvm::Default, llvm::Enable, GlobalDirective, InlineAsmEnd, InlineAsmStart, LabelSuffix, LinkerPrivateGlobalPrefix, PreserveAsmComments, PrivateGlobalPrefix, PrivateLabelPrefix, SeparatorString, SupportsExtendedDwarfLocDirective, UseIntegratedAssembler, WeakDirective, ZeroDirective, and ~MCAsmInfo().
~MCAsmInfo()
MCAsmInfo::~MCAsmInfo () virtual default
Referenced by MCAsmInfo().
Member Function Documentation
addInitialFrameState()
void MCAsmInfo::addInitialFrameState (const MCCFIInstruction & Inst)
Definition at line 73 of file MCAsmInfo.cpp.
References InitialFrameState.
Referenced by createAArch64MCAsmInfo(), createARCMCAsmInfo(), createARMMCAsmInfo(), createHexagonMCAsmInfo(), createMipsMCAsmInfo(), createPPCMCAsmInfo(), createRISCVMCAsmInfo(), createSparcMCAsmInfo(), createSparcV9MCAsmInfo(), createSystemZMCAsmInfo(), createVEMCAsmInfo(), createX86MCAsmInfo(), and createXCoreMCAsmInfo().
canRelaxRelocations()
bool llvm::MCAsmInfo::canRelaxRelocations () const inline
Definition at line 665 of file MCAsmInfo.h.
Referenced by convertTailJumpOpcode(), getRelocType32(), and getRelocType64().
compressDebugSections()
DebugCompressionType llvm::MCAsmInfo::compressDebugSections () const inline
Definition at line 655 of file MCAsmInfo.h.
Referenced by isIFunc().
doDwarfFDESymbolsUseAbsDiff()
bool llvm::MCAsmInfo::doDwarfFDESymbolsUseAbsDiff () const inline
Definition at line 626 of file MCAsmInfo.h.
Referenced by emitFDESymbol().
doesAllowAtInName()
bool llvm::MCAsmInfo::doesAllowAtInName () const inline
Definition at line 534 of file MCAsmInfo.h.
doesDwarfUseRelocationsAcrossSections()
bool llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections () const inline
Definition at line 622 of file MCAsmInfo.h.
Referenced by llvm::DwarfTypeUnit::addGlobalType(), llvm::DwarfUnit::addSectionLabel(), llvm::MCGenDwarfInfo::Emit(), llvm::AsmPrinter::emitDwarfStringOffset(), llvm::AsmPrinter::emitDwarfSymbolReference(), llvm::DIEString::EmitValue(), getCIEVersion(), llvm::MCDwarfLineStr::MCDwarfLineStr(), and llvm::DIEString::SizeOf().
doesSetDirectiveSuppressReloc()
bool llvm::MCAsmInfo::doesSetDirectiveSuppressReloc () const inline
Definition at line 552 of file MCAsmInfo.h.
Referenced by llvm::MCStreamer::emitAbsoluteSymbolDiff(), and llvm::AsmPrinter::EmitJumpTableInfo().
doesSupportDataRegionDirectives()
bool llvm::MCAsmInfo::doesSupportDataRegionDirectives () const inline
Definition at line 537 of file MCAsmInfo.h.
Referenced by truncateToSize().
doesSupportDebugInformation()
bool llvm::MCAsmInfo::doesSupportDebugInformation () const inline
Definition at line 596 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::doInitialization().
doesSupportExceptionHandling()
bool llvm::MCAsmInfo::doesSupportExceptionHandling () const inline
Definition at line 598 of file MCAsmInfo.h.
References llvm::None.
getAlignmentIsInBytes()
bool llvm::MCAsmInfo::getAlignmentIsInBytes () const inline
Definition at line 548 of file MCAsmInfo.h.
getAsciiDirective()
const char* llvm::MCAsmInfo::getAsciiDirective () const inline
Definition at line 546 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getAscizDirective()
const char* llvm::MCAsmInfo::getAscizDirective () const inline
Definition at line 547 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getAssemblerDialect()
unsigned llvm::MCAsmInfo::getAssemblerDialect () const inline
Definition at line 533 of file MCAsmInfo.h.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), EmitGCCInlineAsmStr(), getPlatformName(), LLVMSetDisasmOptions(), and llvm::X86MCExpr::printImpl().
getCalleeSaveStackSlotSize()
unsigned llvm::MCAsmInfo::getCalleeSaveStackSlotSize () const inline
Get the callee-saved register stack slot size in bytes.
Definition at line 415 of file MCAsmInfo.h.
Referenced by getDataAlignmentFactor().
getCode16Directive()
const char* llvm::MCAsmInfo::getCode16Directive () const inline
Definition at line 530 of file MCAsmInfo.h.
Referenced by truncateToSize().
getCode32Directive()
const char* llvm::MCAsmInfo::getCode32Directive () const inline
Definition at line 531 of file MCAsmInfo.h.
Referenced by truncateToSize().
getCode64Directive()
const char* llvm::MCAsmInfo::getCode64Directive () const inline
Definition at line 532 of file MCAsmInfo.h.
Referenced by truncateToSize().
getCodePointerSize()
unsigned llvm::MCAsmInfo::getCodePointerSize () const inline
Get the code pointer size in bytes.
Definition at line 411 of file MCAsmInfo.h.
Referenced by createPPCMCAsmInfo(), llvm::AsmPrinter::doFinalization(), dwarfCCToCodeView(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::DwarfUnit::emitCommonHeader(), EmitDwarfLineTable(), llvm::AsmPrinter::EmitDwarfOffset(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), emitListsTableHeaderStart(), emitRangeList(), llvm::AsmPrinter::emitXRayTable(), llvm::MCDwarfLineAddr::FixedEncode(), getCIEVersion(), getSizeForEncoding(), llvm::DIELabel::SizeOf(), llvm::DIEDelta::SizeOf(), llvm::DIEEntry::SizeOf(), llvm::DIELocList::SizeOf(), and useCompactUnwind().
getCOMMDirectiveAlignmentIsInBytes()
bool llvm::MCAsmInfo::getCOMMDirectiveAlignmentIsInBytes () const inline
Definition at line 558 of file MCAsmInfo.h.
Referenced by getPlatformName().
getCommentColumn()
unsigned llvm::MCAsmInfo::getCommentColumn () const inline
This indicates the column (zero-based) at which asm comments should be printed.
Definition at line 508 of file MCAsmInfo.h.
Referenced by emitComments(), and printDwarfFileDirective().
getCommentString()
StringRef llvm::MCAsmInfo::getCommentString () const inline
Definition at line 510 of file MCAsmInfo.h.
Referenced by llvm::AsmLexer::AsmLexer(), emitComments(), llvm::HexagonInstrInfo::getInlineAsmLength(), getPlatformName(), isAsmComment(), llvm::AsmLexer::peekTokens(), llvm::MCInstPrinter::printAnnotation(), printDwarfFileDirective(), llvm::AArch64InstPrinter::printInst(), llvm::AsmPrinter::PrintSpecial(), llvm::MCSectionWasm::PrintSwitchToSection(), llvm::MCSectionELF::PrintSwitchToSection(), and truncateToSize().
getData16bitsDirective()
const char* llvm::MCAsmInfo::getData16bitsDirective () const inline
Definition at line 430 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getData32bitsDirective()
const char* llvm::MCAsmInfo::getData32bitsDirective () const inline
Definition at line 431 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getData64bitsDirective()
const char* llvm::MCAsmInfo::getData64bitsDirective () const inline
Definition at line 432 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getData8bitsDirective()
const char* llvm::MCAsmInfo::getData8bitsDirective () const inline
Definition at line 429 of file MCAsmInfo.h.
Referenced by llvm::NVPTXTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitRawBytes(), and PrintQuotedString().
getDollarIsPC()
bool llvm::MCAsmInfo::getDollarIsPC () const inline
Definition at line 503 of file MCAsmInfo.h.
getDTPRel32Directive()
const char* llvm::MCAsmInfo::getDTPRel32Directive () const inline
Definition at line 436 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getDTPRel64Directive()
const char* llvm::MCAsmInfo::getDTPRel64Directive () const inline
Definition at line 435 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getExceptionHandlingType()
ExceptionHandling llvm::MCAsmInfo::getExceptionHandlingType () const inline
Definition at line 602 of file MCAsmInfo.h.
Referenced by llvm::TargetPassConfig::addPassesToHandleExceptions(), appendEndToFunction(), llvm::ARMException::beginFunction(), llvm::EHStreamer::computeCallSiteTable(), llvm::X86TargetMachine::createPassConfig(), llvm::AsmPrinter::doInitialization(), llvm::AsmPrinter::emitCFIInstruction(), llvm::EHStreamer::emitExceptionTable(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), llvm::ARMException::endFunction(), eraseDeadBBsAndChildren(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::Initialize(), llvm::ARMSubtarget::isXRaySupported(), matchPair(), llvm::AsmPrinter::needsCFIMoves(), and llvm::WebAssemblyFrameLowering::needsPrologForEH().
getExprForFDESymbol()
const MCExpr * MCAsmInfo::getExprForFDESymbol (const MCSymbol * Sym, unsigned Encoding, MCStreamer & Streamer) const virtual
Reimplemented in llvm::SparcELFMCAsmInfo, and llvm::RISCVMCAsmInfo.
Definition at line 89 of file MCAsmInfo.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::dwarf::DW_EH_PE_pcrel, llvm::MCStreamer::EmitLabel(), and llvm::MCStreamer::getContext().
Referenced by emitFDESymbol(), llvm::RISCVMCAsmInfo::getExprForFDESymbol(), llvm::SparcELFMCAsmInfo::getExprForFDESymbol(), and getExprForPersonalitySymbol().
getExprForPersonalitySymbol()
const MCExpr * MCAsmInfo::getExprForPersonalitySymbol (const MCSymbol * Sym, unsigned Encoding, MCStreamer & Streamer) const virtual
Reimplemented in llvm::X86_64MCAsmInfoDarwin, llvm::SparcELFMCAsmInfo, and llvm::AArch64MCAsmInfoDarwin.
Definition at line 82 of file MCAsmInfo.cpp.
References getExprForFDESymbol().
Referenced by EmitPersonality(), and llvm::SparcELFMCAsmInfo::getExprForPersonalitySymbol().
getGlobalDirective()
const char* llvm::MCAsmInfo::getGlobalDirective () const inline
Definition at line 550 of file MCAsmInfo.h.
Referenced by getPlatformName().
getGPRel32Directive()
const char* llvm::MCAsmInfo::getGPRel32Directive () const inline
Definition at line 434 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getGPRel64Directive()
const char* llvm::MCAsmInfo::getGPRel64Directive () const inline
Definition at line 433 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getHiddenDeclarationVisibilityAttr()
MCSymbolAttr llvm::MCAsmInfo::getHiddenDeclarationVisibilityAttr () const inline
Definition at line 586 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitVisibility().
getHiddenVisibilityAttr()
MCSymbolAttr llvm::MCAsmInfo::getHiddenVisibilityAttr () const inline
Definition at line 584 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitVisibility().
getInitialFrameState()
const std::vector<MCCFIInstruction>& llvm::MCAsmInfo::getInitialFrameState () const inline
Definition at line 635 of file MCAsmInfo.h.
Referenced by llvm::MCStreamer::EmitCFIStartProc(), and getCIEVersion().
getInlineAsmEnd()
const char* llvm::MCAsmInfo::getInlineAsmEnd () const inline
Definition at line 529 of file MCAsmInfo.h.
Referenced by EmitGCCInlineAsmStr().
getInlineAsmStart()
const char* llvm::MCAsmInfo::getInlineAsmStart () const inline
Definition at line 528 of file MCAsmInfo.h.
Referenced by EmitGCCInlineAsmStr().
getLabelSuffix()
const char* llvm::MCAsmInfo::getLabelSuffix () const inline
Definition at line 511 of file MCAsmInfo.h.
Referenced by truncateToSize().
getLCOMMDirectiveAlignmentType()
LCOMM::LCOMMType llvm::MCAsmInfo::getLCOMMDirectiveAlignmentType () const inline
Definition at line 562 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), and getPlatformName().
getLinkerPrivateGlobalPrefix()
StringRef llvm::MCAsmInfo::getLinkerPrivateGlobalPrefix () const inline
Definition at line 522 of file MCAsmInfo.h.
Referenced by llvm::MCContext::createLinkerPrivateTempSymbol().
getMaxInstLength()
virtual unsigned llvm::MCAsmInfo::getMaxInstLength (const MCSubtargetInfo * STI = nullptr) const inline virtual
Returns the maximum possible encoded instruction size in bytes.
If STI is null, this should be the maximum size for any subtarget.
Reimplemented in llvm::AMDGPUMCAsmInfo.
Definition at line 498 of file MCAsmInfo.h.
Referenced by llvm::HexagonInstrInfo::getInlineAsmLength(), and llvm::TargetInstrInfo::getInlineAsmLength().
getMinInstAlignment()
unsigned llvm::MCAsmInfo::getMinInstAlignment () const inline
Definition at line 502 of file MCAsmInfo.h.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), getCIEVersion(), and ScaleAddrDelta().
getNonexecutableStackSection()
virtual MCSection* llvm::MCAsmInfo::getNonexecutableStackSection (MCContext & Ctx) const inline virtual
Targets can implement this method to specify a section to switch to if the translation unit doesn't have any trampolines that require an executable stack.
Definition at line 443 of file MCAsmInfo.h.
References C, Name, and llvm::ARMBuildAttrs::Section.
Referenced by llvm::AsmPrinter::doFinalization(), and llvm::MCELFStreamer::InitSections().
getPrivateGlobalPrefix()
StringRef llvm::MCAsmInfo::getPrivateGlobalPrefix () const inline
Definition at line 515 of file MCAsmInfo.h.
Referenced by llvm::MCContext::createTempSymbol(), llvm::LanaiMCInstLower::GetConstantPoolIndexSymbol(), llvm::MCStreamer::getDwarfLineTableSymbol(), llvm::LanaiMCInstLower::GetJumpTableSymbol(), llvm::MCContext::getOrCreateFrameAllocSymbol(), llvm::MCContext::getOrCreateLSDASymbol(), and llvm::MCContext::getOrCreateParentFrameOffsetSymbol().
getPrivateLabelPrefix()
StringRef llvm::MCAsmInfo::getPrivateLabelPrefix () const inline
Definition at line 516 of file MCAsmInfo.h.
Referenced by llvm::MachineBasicBlock::getSymbol().
getProtectedVisibilityAttr()
MCSymbolAttr llvm::MCAsmInfo::getProtectedVisibilityAttr () const inline
Definition at line 590 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitVisibility().
getSeparatorString()
const char* llvm::MCAsmInfo::getSeparatorString () const inline
Definition at line 504 of file MCAsmInfo.h.
Referenced by llvm::HexagonInstrInfo::getInlineAsmLength(), llvm::TargetInstrInfo::getInlineAsmLength(), llvm::AsmLexer::LexToken(), llvm::AsmLexer::peekTokens(), and truncateToSize().
getSymbolsHaveSMC()
bool llvm::MCAsmInfo::getSymbolsHaveSMC () const inline
Definition at line 594 of file MCAsmInfo.h.
Referenced by createPPCMCAsmInfo().
getTextAlignFillValue()
unsigned llvm::MCAsmInfo::getTextAlignFillValue () const inline
Definition at line 549 of file MCAsmInfo.h.
Referenced by parseHexOcta(), and PrintQuotedString().
getTPRel32Directive()
const char* llvm::MCAsmInfo::getTPRel32Directive () const inline
Definition at line 438 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getTPRel64Directive()
const char* llvm::MCAsmInfo::getTPRel64Directive () const inline
Definition at line 437 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
getWeakDirective()
const char* llvm::MCAsmInfo::getWeakDirective () const inline
Definition at line 572 of file MCAsmInfo.h.
Referenced by getPlatformName().
getWeakRefDirective()
const char* llvm::MCAsmInfo::getWeakRefDirective () const inline
Definition at line 573 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::emitGlobalGOTEquivs(), and getPlatformName().
getWinEHEncodingType()
WinEH::EncodingType llvm::MCAsmInfo::getWinEHEncodingType () const inline
Definition at line 603 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::doInitialization().
getZeroDirective()
const char* llvm::MCAsmInfo::getZeroDirective () const inline
Definition at line 545 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
hasAggressiveSymbolFolding()
bool llvm::MCAsmInfo::hasAggressiveSymbolFolding () const inline
Definition at line 556 of file MCAsmInfo.h.
Referenced by forceExpAbs().
hasAltEntry()
bool llvm::MCAsmInfo::hasAltEntry () const inline
Definition at line 571 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::emitGlobalGOTEquivs().
hasCOFFAssociativeComdats()
bool llvm::MCAsmInfo::hasCOFFAssociativeComdats () const inline
Definition at line 493 of file MCAsmInfo.h.
Referenced by getWinCFISection().
hasCOFFComdatConstants()
bool llvm::MCAsmInfo::hasCOFFComdatConstants () const inline
Definition at line 494 of file MCAsmInfo.h.
Referenced by llvm::TargetLoweringObjectFileCOFF::getSectionForConstant().
hasDotLGloblDirective()
bool llvm::MCAsmInfo::hasDotLGloblDirective () const inline
Definition at line 582 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitLinkage().
hasDotTypeDotSizeDirective()
bool llvm::MCAsmInfo::hasDotTypeDotSizeDirective () const inline
Definition at line 567 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitDebugValue(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::emitGlobalGOTEquivs(), llvm::AsmPrinter::EmitGlobalVariable(), and getPlatformName().
hasFunctionAlignment()
bool llvm::MCAsmInfo::hasFunctionAlignment () const inline
Definition at line 566 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitDebugValue().
hasIdentDirective()
bool llvm::MCAsmInfo::hasIdentDirective () const inline
Definition at line 569 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal(), and printDwarfFileDirective().
hasLinkerPrivateGlobalPrefix()
bool llvm::MCAsmInfo::hasLinkerPrivateGlobalPrefix () const inline
Definition at line 518 of file MCAsmInfo.h.
References llvm::StringRef::empty().
hasLinkOnceDirective()
bool llvm::MCAsmInfo::hasLinkOnceDirective () const inline
Definition at line 580 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitLinkage().
hasMachoTBSSDirective()
bool llvm::MCAsmInfo::hasMachoTBSSDirective () const inline
Definition at line 492 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable().
hasMachoZeroFillDirective()
bool llvm::MCAsmInfo::hasMachoZeroFillDirective () const inline
Definition at line 491 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable().
hasMipsExpressions()
bool llvm::MCAsmInfo::hasMipsExpressions () const inline
Definition at line 667 of file MCAsmInfo.h.
Referenced by llvm::AsmLexer::LexToken().
hasNoDeadStrip()
bool llvm::MCAsmInfo::hasNoDeadStrip () const inline
Definition at line 570 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal(), and getPlatformName().
hasSingleParameterDotFile()
bool llvm::MCAsmInfo::hasSingleParameterDotFile () const inline
Definition at line 568 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::doInitialization(), and PrintQuotedString().
hasSubsectionsViaSymbols()
bool llvm::MCAsmInfo::hasSubsectionsViaSymbols () const inline
Definition at line 425 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitDebugValue(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::EmitGlobalConstant(), and getPlatformName().
hasWeakDefCanBeHiddenDirective()
bool llvm::MCAsmInfo::hasWeakDefCanBeHiddenDirective () const inline
Definition at line 576 of file MCAsmInfo.h.
Referenced by canBeHidden().
hasWeakDefDirective()
bool llvm::MCAsmInfo::hasWeakDefDirective () const inline
Definition at line 574 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitLinkage().
isAcceptableChar()
bool MCAsmInfo::isAcceptableChar (char C) const virtual
Return true if C is an acceptable character inside a symbol name.
Reimplemented in llvm::MCAsmInfoXCOFF.
Definition at line 103 of file MCAsmInfo.cpp.
Referenced by llvm::MCAsmInfoXCOFF::isAcceptableChar(), and isValidUnquotedName().
isLittleEndian()
bool llvm::MCAsmInfo::isLittleEndian () const inline
True if the target is little endian.
Definition at line 420 of file MCAsmInfo.h.
Referenced by llvm::ARMTargetStreamer::emitInst(), llvm::MCStreamer::EmitIntValue(), llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc(), parseHexOcta(), PrintCFIEscape(), and PrintQuotedString().
isSectionAtomizableBySymbols()
bool MCAsmInfo::isSectionAtomizableBySymbols (const MCSection & Section) const virtual
True if the section is atomized using the symbols in it.
This is false if the section is not atomized at all (most ELF sections) or if it is atomized based on its contents (MachO' __TEXT,__cstring for example).
Reimplemented in llvm::MCAsmInfoDarwin.
Definition at line 77 of file MCAsmInfo.cpp.
Referenced by canUseLocalRelocation(), canUsePrivateLabel(), llvm::MCAssembler::getAtom(), and getFixupKindLog2Size().
isStackGrowthDirectionUp()
bool llvm::MCAsmInfo::isStackGrowthDirectionUp () const inline
True if target stack grow up.
Definition at line 423 of file MCAsmInfo.h.
Referenced by getDataAlignmentFactor().
isValidUnquotedName()
bool MCAsmInfo::isValidUnquotedName (StringRef Name) const virtual
Return true if the identifier Name does not need quotes to be syntactically correct.
Definition at line 108 of file MCAsmInfo.cpp.
References C, llvm::StringRef::empty(), and isAcceptableChar().
Referenced by llvm::MCSymbol::print().
needsDwarfSectionOffsetDirective()
bool llvm::MCAsmInfo::needsDwarfSectionOffsetDirective () const inline
Definition at line 485 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::emitDwarfSymbolReference(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), llvm::AsmPrinter::EmitLabelPlusOffset(), and getCIEVersion().
needsFunctionDescriptors()
bool llvm::MCAsmInfo::needsFunctionDescriptors () const inline
Definition at line 668 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitDebugValue(), and llvm::AsmPrinter::SetupMachineFunction().
needsLocalForSize()
bool llvm::MCAsmInfo::needsLocalForSize () const inline
Definition at line 514 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::SetupMachineFunction().
preserveAsmComments()
bool llvm::MCAsmInfo::preserveAsmComments () const inline
Return true if assembly (inline or otherwise) should be parsed.
Definition at line 648 of file MCAsmInfo.h.
setCompressDebugSections()
void llvm::MCAsmInfo::setCompressDebugSections (DebugCompressionType CompressDebugSections) inline
Definition at line 659 of file MCAsmInfo.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo().
setExceptionsType()
void llvm::MCAsmInfo::setExceptionsType (ExceptionHandling EH) inline
Definition at line 605 of file MCAsmInfo.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo().
setPreserveAsmComments()
virtual void llvm::MCAsmInfo::setPreserveAsmComments (bool Value) inline virtual
Set whether assembly (inline or otherwise) should be parsed.
Definition at line 651 of file MCAsmInfo.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo().
setRelaxELFRelocations()
void llvm::MCAsmInfo::setRelaxELFRelocations (bool V) inline
Definition at line 666 of file MCAsmInfo.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo().
setUseIntegratedAssembler()
virtual void llvm::MCAsmInfo::setUseIntegratedAssembler (bool Value) inline virtual
Set whether assembly (inline or otherwise) should be parsed.
Reimplemented in llvm::ARMELFMCAsmInfo.
Definition at line 643 of file MCAsmInfo.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo().
shouldOmitSectionDirective()
bool MCAsmInfo::shouldOmitSectionDirective (StringRef SectionName) const virtual
Return true if the .section directive should be omitted when emitting SectionName.
For example:
shouldOmitSectionDirective(".text")
returns false => .section .text,#alloc,#execinstr returns true => .text
Reimplemented in llvm::NVPTXMCAsmInfo, and llvm::AMDGPUMCAsmInfo.
Definition at line 122 of file MCAsmInfo.cpp.
References usesELFSectionDirectiveForBSS().
Referenced by llvm::AMDGPUMCAsmInfo::shouldOmitSectionDirective(), llvm::MCSectionWasm::shouldOmitSectionDirective(), and llvm::MCSectionELF::ShouldOmitSectionDirective().
shouldUseLogicalShr()
bool llvm::MCAsmInfo::shouldUseLogicalShr () const inline
Definition at line 663 of file MCAsmInfo.h.
Referenced by getGNUBinOpPrecedence().
supportsExtendedDwarfLocDirective()
bool llvm::MCAsmInfo::supportsExtendedDwarfLocDirective () const inline
Definition at line 629 of file MCAsmInfo.h.
Referenced by printDwarfFileDirective().
supportsNameQuoting()
bool llvm::MCAsmInfo::supportsNameQuoting () const inline
Definition at line 535 of file MCAsmInfo.h.
Referenced by llvm::MCSymbol::print().
useAssignmentForEHBegin()
bool llvm::MCAsmInfo::useAssignmentForEHBegin () const inline
Definition at line 513 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::EmitDebugValue().
useDotAlignForAlignment()
bool llvm::MCAsmInfo::useDotAlignForAlignment () const inline
Definition at line 541 of file MCAsmInfo.h.
Referenced by PrintQuotedString().
useDwarfRegNumForCFI()
bool llvm::MCAsmInfo::useDwarfRegNumForCFI () const inline
Definition at line 627 of file MCAsmInfo.h.
Referenced by printDwarfFileDirective().
useIntegratedAssembler()
bool llvm::MCAsmInfo::useIntegratedAssembler () const inline
Return true if assembly (inline or otherwise) should be parsed.
Definition at line 640 of file MCAsmInfo.h.
Referenced by llvm::AsmPrinter::emitPatchableFunctionEntries(), and srcMgrDiagHandler().
useParensForSymbolVariant()
bool llvm::MCAsmInfo::useParensForSymbolVariant () const inline
Definition at line 628 of file MCAsmInfo.h.
usesCFIForEH()
bool llvm::MCAsmInfo::usesCFIForEH () const inline
Returns true if the exception handling method for the platform uses call frame information to unwind.
Definition at line 611 of file MCAsmInfo.h.
References llvm::WinEH::ARM, and llvm::DwarfCFI.
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::EHStreamer::computeCallSiteTable(), and llvm::DwarfCFIException::endModule().
usesELFSectionDirectiveForBSS()
bool llvm::MCAsmInfo::usesELFSectionDirectiveForBSS () const inline
Definition at line 481 of file MCAsmInfo.h.
Referenced by shouldOmitSectionDirective().
usesSunStyleELFSectionSwitchSyntax()
bool llvm::MCAsmInfo::usesSunStyleELFSectionSwitchSyntax () const inline
Definition at line 477 of file MCAsmInfo.h.
Referenced by llvm::MCSectionELF::PrintSwitchToSection().
usesWindowsCFI()
bool llvm::MCAsmInfo::usesWindowsCFI () const inline
Definition at line 616 of file MCAsmInfo.h.
References llvm::WinEH::Invalid, llvm::WinEH, and llvm::WinEH::X86.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::WinException::beginFunction(), llvm::X86FrameLowering::canUseLEAForSPInEpilogue(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MCStreamer::EmitWinCFIStartProc(), llvm::WinException::endFunclet(), llvm::MCStreamer::EnsureValidWinFrameInfo(), ExpandMOVImmSExti8(), llvm::X86FrameLowering::getFrameIndexReference(), giveUpWithRemarks(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), LowerINTRINSIC_W_CHAIN(), llvm::AsmPrinter::needsSEHMoves(), and needsWinCFI().
Member Data Documentation
AlignmentIsInBytes
bool llvm::MCAsmInfo::AlignmentIsInBytes = true protected
If this is true (the default) then the asmprinter emits ".align N" directives, where N is the number of bytes to align to.
Otherwise, it emits ".align log2(N)", e.g. 3 to align to an 8 byte boundary. Defaults to true.
Definition at line 235 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMCOFFMCAsmInfoMicrosoft::ARMCOFFMCAsmInfoMicrosoft(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MSP430MCAsmInfo::MSP430MCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), and llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo().
AllowAtInName
bool llvm::MCAsmInfo::AllowAtInName = false protected
This is true if the assembler allows @ characters in symbol names.
Defaults to false.
Definition at line 157 of file MCAsmInfo.h.
Referenced by llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
AsciiDirective
const char* llvm::MCAsmInfo::AsciiDirective protected
This directive allows emission of an ascii string with the standard C escape characters embedded into it.
If a target doesn't support this, it can be set to null. Defaults to "\t.ascii\t"
Definition at line 183 of file MCAsmInfo.h.
Referenced by MCAsmInfo(), llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
AscizDirective
const char* llvm::MCAsmInfo::AscizDirective protected
If not null, this allows for special handling of zero terminated strings on this target.
This is commonly supported as ".asciz". If a target doesn't support this, it can be set to null. Defaults to "\t.asciz\t"
Definition at line 188 of file MCAsmInfo.h.
Referenced by llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), MCAsmInfo(), llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
AssemblerDialect
unsigned llvm::MCAsmInfo::AssemblerDialect = 0 protected
Which dialect of an assembler variant to use. Defaults to 0.
Definition at line 153 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
CalleeSaveStackSlotSize
unsigned llvm::MCAsmInfo::CalleeSaveStackSlotSize = 4 protected
Size of the stack slot reserved for callee-saved registers, in bytes.
Default is same as pointer size.
Definition at line 67 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AVRMCAsmInfo::AVRMCAsmInfo(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MSP430MCAsmInfo::MSP430MCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::PPCXCOFFMCAsmInfo::PPCXCOFFMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::VEELFMCAsmInfo::VEELFMCAsmInfo(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), and llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
Code16Directive
const char* llvm::MCAsmInfo::Code16Directive protected
These are assembly directives that tells the assembler to interpret the following instructions differently.
Defaults to ".code16", ".code32", ".code64".
Definition at line 148 of file MCAsmInfo.h.
Referenced by llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), and MCAsmInfo().
Code32Directive
const char* llvm::MCAsmInfo::Code32Directive protected
Definition at line 149 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), and MCAsmInfo().
Code64Directive
const char* llvm::MCAsmInfo::Code64Directive protected
Definition at line 150 of file MCAsmInfo.h.
Referenced by MCAsmInfo().
CodePointerSize
unsigned llvm::MCAsmInfo::CodePointerSize = 4 protected
Code pointer size in bytes. Default is 4.
Definition at line 63 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::AVRMCAsmInfo::AVRMCAsmInfo(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MSP430MCAsmInfo::MSP430MCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::PPCXCOFFMCAsmInfo::PPCXCOFFMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::VEELFMCAsmInfo::VEELFMCAsmInfo(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
COMMDirectiveAlignmentIsInBytes
bool llvm::MCAsmInfo::COMMDirectiveAlignmentIsInBytes = true protected
True is .comm's and .lcomms optional alignment is to be specified in bytes instead of log2(n).
Defaults to true.
Definition at line 271 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), and llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo().
CommentString
StringRef llvm::MCAsmInfo::CommentString protected
This indicates the comment character used by the assembler.
Defaults to "#"
Definition at line 114 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMCOFFMCAsmInfoMicrosoft::ARMCOFFMCAsmInfoMicrosoft(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::AVRMCAsmInfo::AVRMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), MCAsmInfo(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MSP430MCAsmInfo::MSP430MCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
CompressDebugSections
DebugCompressionType llvm::MCAsmInfo::CompressDebugSections = DebugCompressionType::None protected
Compress DWARF debug sections. Defaults to no compression.
Definition at line 389 of file MCAsmInfo.h.
Data16bitsDirective
const char* llvm::MCAsmInfo::Data16bitsDirective protected
Definition at line 195 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), MCAsmInfo(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::VEELFMCAsmInfo::VEELFMCAsmInfo(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
Data32bitsDirective
const char* llvm::MCAsmInfo::Data32bitsDirective protected
Definition at line 196 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), MCAsmInfo(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::VEELFMCAsmInfo::VEELFMCAsmInfo(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
Data64bitsDirective
const char* llvm::MCAsmInfo::Data64bitsDirective protected
Definition at line 197 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), MCAsmInfo(), llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::VEELFMCAsmInfo::VEELFMCAsmInfo(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
Data8bitsDirective
const char* llvm::MCAsmInfo::Data8bitsDirective protected
These directives are used to output some unit of integer data to the current section.
If a data directive is set to null, smaller data directives will be used to emit the large sizes. Defaults to "\t.byte\t", "\t.short\t", "\t.long\t", "\t.quad\t"
Definition at line 194 of file MCAsmInfo.h.
Referenced by MCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::VEELFMCAsmInfo::VEELFMCAsmInfo(), and llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo().
DollarIsPC
bool llvm::MCAsmInfo::DollarIsPC = false protected
The '$' token, when not referencing an identifier or constant, refers to the current PC.
Defaults to false.
Definition at line 106 of file MCAsmInfo.h.
Referenced by llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo().
DTPRel32Directive
const char* llvm::MCAsmInfo::DTPRel32Directive = nullptr protected
If non-null, directives that are used to emit a word/dword which should be relocated as a 32/64-bit DTP/TP-relative offset, e.g.
.dtprelword/ .dtpreldword/.tprelword/.tpreldword on Mips.
Definition at line 212 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
DTPRel64Directive
const char* llvm::MCAsmInfo::DTPRel64Directive = nullptr protected
Definition at line 213 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
DwarfFDESymbolsUseAbsDiff
bool llvm::MCAsmInfo::DwarfFDESymbolsUseAbsDiff = false protected
True if DWARF FDE symbol reference relocations should be replaced by an absolute difference.
Definition at line 358 of file MCAsmInfo.h.
Referenced by llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
DwarfRegNumForCFI
bool llvm::MCAsmInfo::DwarfRegNumForCFI = false protected
True if dwarf register numbers are printed instead of symbolic register names in .cfi_* directives.
Defaults to false.
Definition at line 362 of file MCAsmInfo.h.
Referenced by llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::ARMELFMCAsmInfo::setUseIntegratedAssembler(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
DwarfUsesRelocationsAcrossSections
bool llvm::MCAsmInfo::DwarfUsesRelocationsAcrossSections = true protected
True if Dwarf2 output generally uses relocations for references to other .debug_* sections.
Definition at line 354 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), and llvm::BPFMCAsmInfo::setDwarfUsesRelocationsAcrossSections().
ExceptionsType
ExceptionHandling llvm::MCAsmInfo::ExceptionsType = ExceptionHandling::None protected
Exception handling format for the target. Defaults to None.
Definition at line 347 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMCOFFMCAsmInfoMicrosoft::ARMCOFFMCAsmInfoMicrosoft(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
GlobalDirective
const char* llvm::MCAsmInfo::GlobalDirective protected
This is the directive used to declare a global entity.
Defaults to ".globl".
Definition at line 245 of file MCAsmInfo.h.
Referenced by MCAsmInfo(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
GPRel32Directive
const char* llvm::MCAsmInfo::GPRel32Directive = nullptr protected
If non-null, a directive that is used to emit a word which should be relocated as a 32-bit GP-relative offset, e.g.
.gpword on Mips or .gprel32 on Alpha. Defaults to nullptr.
Definition at line 207 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
GPRel64Directive
const char* llvm::MCAsmInfo::GPRel64Directive = nullptr protected
If non-null, a directive that is used to emit a word which should be relocated as a 64-bit GP-relative offset, e.g.
.gpdword on Mips. Defaults to nullptr.
Definition at line 202 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
HasAggressiveSymbolFolding
bool llvm::MCAsmInfo::HasAggressiveSymbolFolding = true protected
False if the assembler requires that we use.
Lc = a - b
.long Lc
instead of
.long a - b
Defaults to true.
Definition at line 267 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), and llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
HasAltEntry
bool llvm::MCAsmInfo::HasAltEntry = false protected
True if this target supports the MachO .alt_entry directive.
Defaults to false.
Definition at line 299 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
HasCOFFAssociativeComdats
bool llvm::MCAsmInfo::HasCOFFAssociativeComdats = false protected
True if this is a non-GNU COFF target.
The COFF port of the GNU linker doesn't handle associative comdats in the way that we would like to use them.
Definition at line 90 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), and llvm::MCAsmInfoGNUCOFF::MCAsmInfoGNUCOFF().
HasCOFFComdatConstants
bool llvm::MCAsmInfo::HasCOFFComdatConstants = false protected
True if this is a non-GNU COFF target.
For GNU targets, we don't generate constants into comdat sections.
Definition at line 94 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), and llvm::MCAsmInfoGNUCOFF::MCAsmInfoGNUCOFF().
HasDotLGloblDirective
bool llvm::MCAsmInfo::HasDotLGloblDirective = false protected
True if we have a .lglobl directive, which is used to emit the information of a static symbol into the symbol table.
Defaults to false.
Definition at line 322 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF().
HasDotTypeDotSizeDirective
bool llvm::MCAsmInfo::HasDotTypeDotSizeDirective = true protected
True if the target has .type and .size directives, this is true for most ELF targets.
Defaults to true.
Definition at line 283 of file MCAsmInfo.h.
Referenced by llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
HasFunctionAlignment
bool llvm::MCAsmInfo::HasFunctionAlignment = true protected
Definition at line 279 of file MCAsmInfo.h.
Referenced by llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
HasIdentDirective
bool llvm::MCAsmInfo::HasIdentDirective = false protected
True if the target has a .ident directive, this is true for ELF targets.
Defaults to false.
Definition at line 291 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::MCAsmInfoELF::MCAsmInfoELF(), and llvm::MCAsmInfoWasm::MCAsmInfoWasm().
HasLinkOnceDirective
bool llvm::MCAsmInfo::HasLinkOnceDirective = false protected
True if we have a .linkonce directive.
This is used on cygwin/mingw. Defaults to false.
Definition at line 318 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoCOFF::MCAsmInfoCOFF().
HasMachoTBSSDirective
bool llvm::MCAsmInfo::HasMachoTBSSDirective = false protected
True if this is a MachO target that supports the macho-specific .tbss directive for emitting thread local BSS Symbols.
Default is false.
Definition at line 85 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
HasMachoZeroFillDirective
bool llvm::MCAsmInfo::HasMachoZeroFillDirective = false protected
True if this is a MachO target that supports the macho-specific .zerofill directive for emitting BSS Symbols.
Default is false.
Definition at line 81 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
HasMipsExpressions
bool llvm::MCAsmInfo::HasMipsExpressions = false protected
Definition at line 401 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
HasNoDeadStrip
bool llvm::MCAsmInfo::HasNoDeadStrip = false protected
True if this target supports the MachO .no_dead_strip directive.
Defaults to false.
Definition at line 295 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), and llvm::MCAsmInfoWasm::MCAsmInfoWasm().
HasSingleParameterDotFile
bool llvm::MCAsmInfo::HasSingleParameterDotFile = true protected
True if the target has a single parameter .file directive, this is true for ELF targets.
Defaults to true.
Definition at line 287 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
HasSubsectionsViaSymbols
bool llvm::MCAsmInfo::HasSubsectionsViaSymbols = false protected
True if this target has the MachO .subsections_via_symbols directive.
Default is false.
Definition at line 77 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
HasWeakDefCanBeHiddenDirective
bool llvm::MCAsmInfo::HasWeakDefCanBeHiddenDirective = false protected
True if we have a directive to declare a global as being a weak defined symbol that can be hidden (unexported).
Defaults to false.
Definition at line 314 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), and llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
HasWeakDefDirective
bool llvm::MCAsmInfo::HasWeakDefDirective = false protected
True if we have a directive to declare a global as being a weak defined symbol.
Defaults to false.
Definition at line 310 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
HiddenDeclarationVisibilityAttr
MCSymbolAttr llvm::MCAsmInfo::HiddenDeclarationVisibilityAttr = MCSA_Hidden protected
This attribute, if not MCSA_Invalid, is used to declare an undefined symbol as having hidden visibility.
Defaults to MCSA_Hidden.
Definition at line 330 of file MCAsmInfo.h.
Referenced by llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
HiddenVisibilityAttr
MCSymbolAttr llvm::MCAsmInfo::HiddenVisibilityAttr = MCSA_Hidden protected
This attribute, if not MCSA_Invalid, is used to declare a symbol as having hidden visibility.
Defaults to MCSA_Hidden.
Definition at line 326 of file MCAsmInfo.h.
Referenced by llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
InitialFrameState
std::vector<MCCFIInstruction> llvm::MCAsmInfo::InitialFrameState protected
Definition at line 374 of file MCAsmInfo.h.
Referenced by addInitialFrameState().
InlineAsmEnd
const char* llvm::MCAsmInfo::InlineAsmEnd protected
Definition at line 143 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), MCAsmInfo(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
InlineAsmStart
const char* llvm::MCAsmInfo::InlineAsmStart protected
If these are nonempty, they contain a directive to emit before and after an inline assembly statement.
Defaults to "#APP\n", "#NO_APP\n"
Definition at line 142 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), MCAsmInfo(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
IsLittleEndian
bool llvm::MCAsmInfo::IsLittleEndian = true protected
True if target is little endian. Default is true.
Definition at line 70 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::PPCXCOFFMCAsmInfo::PPCXCOFFMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), and llvm::SystemZMCAsmInfo::SystemZMCAsmInfo().
LabelSuffix
const char* llvm::MCAsmInfo::LabelSuffix protected
This is appended to emitted labels. Defaults to ":".
Definition at line 117 of file MCAsmInfo.h.
Referenced by MCAsmInfo().
LCOMMDirectiveAlignmentType
LCOMM::LCOMMType llvm::MCAsmInfo::LCOMMDirectiveAlignmentType = LCOMM::NoAlignment protected
Describes if the .lcomm directive for the target supports an alignment argument and how it is interpreted.
Defaults to NoAlignment.
Definition at line 275 of file MCAsmInfo.h.
Referenced by llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), and llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo().
LinkerPrivateGlobalPrefix
StringRef llvm::MCAsmInfo::LinkerPrivateGlobalPrefix protected
This prefix is used for symbols that should be passed through the assembler but be removed by the linker.
This is 'l' on Darwin, currently used for some ObjC metadata. The default of "" meast that for this system a plain private symbol should be used. Defaults to "".
Definition at line 138 of file MCAsmInfo.h.
Referenced by MCAsmInfo(), and llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
MaxInstLength
unsigned llvm::MCAsmInfo::MaxInstLength = 4 protected
This is the maximum possible length of an instruction, which is needed to compute the size of an inline asm.
Defaults to 4.
Definition at line 98 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMCOFFMCAsmInfoMicrosoft::ARMCOFFMCAsmInfoMicrosoft(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::AMDGPUMCAsmInfo::getMaxInstLength(), and llvm::VEELFMCAsmInfo::VEELFMCAsmInfo().
MinInstAlignment
unsigned llvm::MCAsmInfo::MinInstAlignment = 1 protected
Every possible instruction length is a multiple of this value.
Factored out in .debug_frame and .debug_line. Defaults to 1.
Definition at line 102 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), and llvm::VEELFMCAsmInfo::VEELFMCAsmInfo().
NeedsDwarfSectionOffsetDirective
bool llvm::MCAsmInfo::NeedsDwarfSectionOffsetDirective = false protected
Definition at line 227 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoCOFF::MCAsmInfoCOFF().
NeedsFunctionDescriptors
bool llvm::MCAsmInfo::NeedsFunctionDescriptors = false protected
Definition at line 404 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF().
NeedsLocalForSize
bool llvm::MCAsmInfo::NeedsLocalForSize = false protected
Definition at line 123 of file MCAsmInfo.h.
Referenced by llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo().
PreserveAsmComments
bool llvm::MCAsmInfo::PreserveAsmComments protected
Preserve Comments in assembly.
Definition at line 386 of file MCAsmInfo.h.
Referenced by MCAsmInfo().
PrivateGlobalPrefix
StringRef llvm::MCAsmInfo::PrivateGlobalPrefix protected
This prefix is used for globals like constant pool entries that are completely private to the .s file and should not have names in the .o file.
Defaults to "L"
Definition at line 128 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMCOFFMCAsmInfoMicrosoft::ARMCOFFMCAsmInfoMicrosoft(), llvm::AVRMCAsmInfo::AVRMCAsmInfo(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), MCAsmInfo(), llvm::MCAsmInfoELF::MCAsmInfoELF(), llvm::MCAsmInfoWasm::MCAsmInfoWasm(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
PrivateLabelPrefix
StringRef llvm::MCAsmInfo::PrivateLabelPrefix protected
This prefix is used for labels for basic blocks.
Defaults to the same as PrivateGlobalPrefix.
Definition at line 132 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMCOFFMCAsmInfoMicrosoft::ARMCOFFMCAsmInfoMicrosoft(), MCAsmInfo(), llvm::MCAsmInfoELF::MCAsmInfoELF(), llvm::MCAsmInfoWasm::MCAsmInfoWasm(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
ProtectedVisibilityAttr
MCSymbolAttr llvm::MCAsmInfo::ProtectedVisibilityAttr = MCSA_Protected protected
This attribute, if not MCSA_Invalid, is used to declare a symbol as having protected visibility.
Defaults to MCSA_Protected
Definition at line 334 of file MCAsmInfo.h.
Referenced by llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
RelaxELFRelocations
bool llvm::MCAsmInfo::RelaxELFRelocations = true protected
Definition at line 397 of file MCAsmInfo.h.
SeparatorString
const char* llvm::MCAsmInfo::SeparatorString protected
This string, if specified, is used to separate instructions from each other when on the same line.
Defaults to ';'
Definition at line 110 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), MCAsmInfo(), and llvm::MSP430MCAsmInfo::MSP430MCAsmInfo().
SetDirectiveSuppressesReloc
bool llvm::MCAsmInfo::SetDirectiveSuppressesReloc = false protected
True if the expression .long f - g uses a relocation but it can be suppressed by writing a = f - g .long a.
Definition at line 252 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoDarwin::MCAsmInfoDarwin().
StackGrowsUp
bool llvm::MCAsmInfo::StackGrowsUp = false protected
True if target stack grow up. Default is false.
Definition at line 73 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo().
SunStyleELFSectionSwitchSyntax
bool llvm::MCAsmInfo::SunStyleELFSectionSwitchSyntax = false protected
This is true if this target uses "Sun Style" syntax for section switching ("#alloc,#write" etc) instead of the normal ELF syntax (,"a,w") in .section directives.
Defaults to false.
Definition at line 220 of file MCAsmInfo.h.
Referenced by llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), and llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo().
SupportsDebugInformation
bool llvm::MCAsmInfo::SupportsDebugInformation = false protected
True if target supports emission of debugging information.
Defaults to false.
Definition at line 344 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::AVRMCAsmInfo::AVRMCAsmInfo(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::VEELFMCAsmInfo::VEELFMCAsmInfo(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
SupportsExtendedDwarfLocDirective
bool llvm::MCAsmInfo::SupportsExtendedDwarfLocDirective = true protected
True if the target supports flags in ".loc" directive, false if only location is allowed.
Definition at line 370 of file MCAsmInfo.h.
Referenced by MCAsmInfo(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
SupportsQuotedNames
bool llvm::MCAsmInfo::SupportsQuotedNames = true protected
If this is true, symbol names with invalid characters will be printed in quotes.
Definition at line 161 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
SymbolsHaveSMC
bool llvm::MCAsmInfo::SymbolsHaveSMC = false protected
Definition at line 338 of file MCAsmInfo.h.
Referenced by llvm::PPCXCOFFMCAsmInfo::PPCXCOFFMCAsmInfo().
TextAlignFillValue
unsigned llvm::MCAsmInfo::TextAlignFillValue = 0 protected
If non-zero, this is used to fill the executable space created as the result of a alignment directive.
Defaults to 0
Definition at line 239 of file MCAsmInfo.h.
Referenced by llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
TPRel32Directive
const char* llvm::MCAsmInfo::TPRel32Directive = nullptr protected
Definition at line 214 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
TPRel64Directive
const char* llvm::MCAsmInfo::TPRel64Directive = nullptr protected
Definition at line 215 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
UseAssignmentForEHBegin
bool llvm::MCAsmInfo::UseAssignmentForEHBegin = false protected
Definition at line 120 of file MCAsmInfo.h.
Referenced by llvm::MipsMCAsmInfo::MipsMCAsmInfo().
UseDataRegionDirectives
bool llvm::MCAsmInfo::UseDataRegionDirectives = false protected
This is true if data region markers should be printed as ".data_region/.end_data_region" directives.
If false, use "$d/$a" labels instead.
Definition at line 166 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), and llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
UseDotAlignForAlignment
bool llvm::MCAsmInfo::UseDotAlignForAlignment = false protected
True if .align is to be used for alignment.
Only power-of-two alignment is supported.
Definition at line 170 of file MCAsmInfo.h.
Referenced by llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF().
UseIntegratedAssembler
bool llvm::MCAsmInfo::UseIntegratedAssembler protected
Should we use the integrated assembler? The integrated assembler should be enabled by default (by the constructors) when failing to parse a valid piece of assembly (inline or otherwise) is considered a bug.
It may then be overridden after construction (see LLVMTargetMachine::initAsmInfo()).
Definition at line 383 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::AVRMCAsmInfo::AVRMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), MCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MSP430MCAsmInfo::MSP430MCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::ARMELFMCAsmInfo::setUseIntegratedAssembler(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
UseLogicalShr
bool llvm::MCAsmInfo::UseLogicalShr = true protected
True if the integrated assembler should interpret 'a >> b' constant expressions as logical rather than arithmetic.
Definition at line 393 of file MCAsmInfo.h.
Referenced by llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), and llvm::MCAsmInfoCOFF::MCAsmInfoCOFF().
UseParensForSymbolVariant
bool llvm::MCAsmInfo::UseParensForSymbolVariant = false protected
True if target uses parens to indicate the symbol variant instead of .
For example, foo(plt) instead of foo. Defaults to false.
Definition at line 366 of file MCAsmInfo.h.
Referenced by llvm::ARMCOFFMCAsmInfoGNU::ARMCOFFMCAsmInfoGNU(), and llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo().
UsesELFSectionDirectiveForBSS
bool llvm::MCAsmInfo::UsesELFSectionDirectiveForBSS = false protected
This is true if this target uses ELF '.section' directive before the '.bss' one.
It's used for PPC/Linux which doesn't support the '.bss' directive only. Defaults to false.
Definition at line 225 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::AVRMCAsmInfo::AVRMCAsmInfo(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), llvm::MSP430MCAsmInfo::MSP430MCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), and llvm::VEELFMCAsmInfo::VEELFMCAsmInfo().
WeakDirective
const char* llvm::MCAsmInfo::WeakDirective protected
Used to declare a global as being a weak symbol. Defaults to ".weak".
Definition at line 302 of file MCAsmInfo.h.
Referenced by MCAsmInfo(), and llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo().
WeakRefDirective
const char* llvm::MCAsmInfo::WeakRefDirective = nullptr protected
This directive, if non-null, is used to declare a global as being a weak undefined symbol.
Defaults to nullptr.
Definition at line 306 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), llvm::LanaiMCAsmInfo::LanaiMCAsmInfo(), llvm::MCAsmInfoCOFF::MCAsmInfoCOFF(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::MCAsmInfoELF::MCAsmInfoELF(), and llvm::MCAsmInfoWasm::MCAsmInfoWasm().
WinEHEncodingType
WinEH::EncodingType llvm::MCAsmInfo::WinEHEncodingType = WinEH::EncodingType::Invalid protected
Windows exception handling data (.pdata) encoding. Defaults to Invalid.
Definition at line 350 of file MCAsmInfo.h.
Referenced by llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
ZeroDirective
const char* llvm::MCAsmInfo::ZeroDirective protected
This should be set to the directive used to get some number of zero bytes emitted to the current section.
Common cases are "\t.zero\t" and "\t.space\t". If this is set to null, the Data*bitsDirective's will be used to emit zero bytes. Defaults to "\t.zero\t"
Definition at line 178 of file MCAsmInfo.h.
Referenced by llvm::ARCMCAsmInfo::ARCMCAsmInfo(), llvm::HexagonMCAsmInfo::HexagonMCAsmInfo(), MCAsmInfo(), llvm::MCAsmInfoDarwin::MCAsmInfoDarwin(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::PPCXCOFFMCAsmInfo::PPCXCOFFMCAsmInfo(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), llvm::SystemZMCAsmInfo::SystemZMCAsmInfo(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), and llvm::XCoreMCAsmInfo::XCoreMCAsmInfo().
The documentation for this class was generated from the following files:
include/llvm/MC/MCAsmInfo.h
lib/MC/MCAsmInfo.cpp