LLVM: llvm::DIELoc Class Reference
llvm::DIELoc Class Reference
DIELoc - Represents an expression location.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIELoc ()=default
unsigned ComputeSize (const AsmPrinter *AP) const
ComputeSize - Calculate the size of the location expression.
dwarf::Form BestForm (unsigned DwarfVersion) const
BestForm - Choose the best form for data.
void EmitValue (const AsmPrinter *Asm, dwarf::Form Form) const
EmitValue - Emit location data.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
SizeOf - Determine size of location data in bytes.
void print (raw_ostream &O) const
Public Member Functions inherited from llvm::DIEValueList
value_iterator addValue (BumpPtrAllocator &Alloc, const DIEValue &V)
template<class T >
value_iterator addValue (BumpPtrAllocator &Alloc, dwarf::Attribute Attribute, dwarf::Form Form, T &&Value)
void takeValues (DIEValueList &Other)
Take ownership of the nodes in Other, and append them to the back of the list.
value_range values ()
const_value_range values () const
Additional Inherited Members
Public Types inherited from llvm::DIEValueList
using value_range = iterator_range< value_iterator >
using const_value_range = iterator_range< const_value_iterator >
Detailed Description
DIELoc - Represents an expression location.
Definition at line 903 of file DIE.h.
Constructor & Destructor Documentation
DIELoc()
llvm::DIELoc::DIELoc () default
Member Function Documentation
BestForm()
dwarf::Form llvm::DIELoc::BestForm (unsigned DwarfVersion) const inline
BestForm - Choose the best form for data.
Definition at line 915 of file DIE.h.
References llvm::HexStyle::Asm, llvm::RISCVFenceField::O, and print().
Referenced by llvm::DwarfUnit::addBlock().
ComputeSize()
unsigned DIELoc::ComputeSize (const AsmPrinter * AP) const
ComputeSize - Calculate the size of the location expression.
ComputeSize - calculate the size of the location expression.
Definition at line 703 of file DIE.cpp.
References Size, and llvm::cl::values().
Referenced by llvm::DwarfUnit::addBlock(), and llvm::DIEDwarfExpression::DIEDwarfExpression().
EmitValue()
void DIELoc::EmitValue (const AsmPrinter * Asm, dwarf::Form Form) const
EmitValue - Emit location data.
Definition at line 714 of file DIE.cpp.
References llvm::AsmPrinter::emitInt16(), llvm::AsmPrinter::emitInt32(), llvm::AsmPrinter::emitInt8(), llvm::AsmPrinter::EmitULEB128(), llvm_unreachable, Size, and llvm::cl::values().
print()
LLVM_DUMP_METHOD void DIELoc::print (raw_ostream & O) const
Definition at line 744 of file DIE.cpp.
References printValues(), and Size.
SizeOf()
unsigned DIELoc::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
SizeOf - Determine size of location data in bytes.
Definition at line 731 of file DIE.cpp.
References llvm::getULEB128Size(), LLVM_DUMP_METHOD, llvm_unreachable, and Size.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp