LLVM: llvm::codeview::FieldListDeserializer Class Reference
llvm::codeview::FieldListDeserializer Class Reference
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
Public Member Functions
FieldListDeserializer (BinaryStreamReader &Reader)
~FieldListDeserializer () override
Error visitMemberBegin (CVMemberRecord &Record) override
Error visitMemberEnd (CVMemberRecord &Record) override
Public Member Functions inherited from llvm::codeview::TypeVisitorCallbacks
virtual ~TypeVisitorCallbacks ()=default
virtual Error visitUnknownType (CVType &Record)
Action to take on unknown types. By default, they are ignored.
virtual Error visitTypeBegin (CVType &Record)
Paired begin/end actions for all types.
virtual Error visitTypeBegin (CVType &Record, TypeIndex Index)
virtual Error visitTypeEnd (CVType &Record)
virtual Error visitUnknownMember (CVMemberRecord &Record)
Detailed Description
Definition at line 102 of file TypeDeserializer.h.
Constructor & Destructor Documentation
FieldListDeserializer()
llvm::codeview::FieldListDeserializer::FieldListDeserializer (BinaryStreamReader & Reader) inline explicit
Definition at line 113 of file TypeDeserializer.h.
References llvm::consumeError(), and llvm::codeview::FieldList.
~FieldListDeserializer()
llvm::codeview::FieldListDeserializer::~FieldListDeserializer () inline override
Definition at line 119 of file TypeDeserializer.h.
References llvm::consumeError(), and llvm::codeview::FieldList.
Member Function Documentation
visitMemberBegin()
Error llvm::codeview::FieldListDeserializer::visitMemberBegin (CVMemberRecord & Record) inline override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 125 of file TypeDeserializer.h.
visitMemberEnd()
Error llvm::codeview::FieldListDeserializer::visitMemberEnd (CVMemberRecord & Record) inline override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 130 of file TypeDeserializer.h.
References llvm::codeview::EC, and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeDeserializer.h