LLVM: llvm::orc::LocalIndirectStubsManager< TargetT > Class Template Reference
llvm::orc::LocalIndirectStubsManager< TargetT > Class Template Reference
IndirectStubsManager implementation for the host architecture, e.g.
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Public Member Functions
Error createStub (StringRef StubName, JITTargetAddress StubAddr, JITSymbolFlags StubFlags) override
Create a single stub with the given name, target address and flags.
Error createStubs (const StubInitsMap &StubInits) override
Create StubInits.size() stubs with the given names, target addresses, and flags.
JITEvaluatedSymbol findStub (StringRef Name, bool ExportedStubsOnly) override
Find the stub with the given name.
JITEvaluatedSymbol findPointer (StringRef Name) override
Find the implementation-pointer for the stub.
Error updatePointer (StringRef Name, JITTargetAddress NewAddr) override
Change the value of the implementation pointer for the stub.
Public Member Functions inherited from llvm::orc::IndirectStubsManager
virtual ~IndirectStubsManager ()=default
Additional Inherited Members
Public Types inherited from llvm::orc::IndirectStubsManager
using StubInitsMap = StringMap< std::pair< JITTargetAddress, JITSymbolFlags > >
Map type for initializing the manager. See init.
Detailed Description
template<typename TargetT>
class llvm::orc::LocalIndirectStubsManager< TargetT >
IndirectStubsManager implementation for the host architecture, e.g.
OrcX86_64. (See OrcArchitectureSupport.h).
Definition at line 293 of file IndirectionUtils.h.
Member Function Documentation
createStub()
template<typename TargetT > Error llvm::orc::LocalIndirectStubsManager< TargetT >::createStub (StringRef StubName, JITTargetAddress StubAddr, JITSymbolFlags StubFlags) inline override virtual
Create a single stub with the given name, target address and flags.
Implements llvm::orc::IndirectStubsManager.
Definition at line 295 of file IndirectionUtils.h.
References llvm::Lock.
createStubs()
template<typename TargetT > Error llvm::orc::LocalIndirectStubsManager< TargetT >::createStubs (const StubInitsMap & StubInits) inline override virtual
Create StubInits.size() stubs with the given names, target addresses, and flags.
Implements llvm::orc::IndirectStubsManager.
Definition at line 306 of file IndirectionUtils.h.
References llvm::Lock.
findPointer()
template<typename TargetT > JITEvaluatedSymbol llvm::orc::LocalIndirectStubsManager< TargetT >::findPointer (StringRef Name) inline override virtual
Find the implementation-pointer for the stub.
Implements llvm::orc::IndirectStubsManager.
Definition at line 334 of file IndirectionUtils.h.
References assert(), I, and llvm::Lock.
findStub()
template<typename TargetT > JITEvaluatedSymbol llvm::orc::LocalIndirectStubsManager< TargetT >::findStub (StringRef Name, bool ExportedStubsOnly) inline override virtual
Find the stub with the given name.
If ExportedStubsOnly is true, this will only return a result if the stub's flags indicate that it is exported.
Implements llvm::orc::IndirectStubsManager.
Definition at line 318 of file IndirectionUtils.h.
References assert(), I, and llvm::Lock.
updatePointer()
template<typename TargetT > Error llvm::orc::LocalIndirectStubsManager< TargetT >::updatePointer (StringRef Name, JITTargetAddress NewAddr) inline override virtual
Change the value of the implementation pointer for the stub.
Implements llvm::orc::IndirectStubsManager.
Definition at line 347 of file IndirectionUtils.h.
References assert(), I, llvm::Lock, and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/IndirectionUtils.h