LLVM: llvm::AsmPrinterHandler Class Reference
llvm::AsmPrinterHandler Class Reference abstract
Collects and handles AsmPrinter objects required to build debug or EH information.
#include "llvm/CodeGen/AsmPrinterHandler.h"
Public Member Functions
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void setSymbolSize (const MCSymbol *Sym, uint64_t Size)=0
For symbols that have a size designated (e.g.
virtual void endModule ()=0
Emit all sections that should come after the content.
virtual void beginFunction (const MachineFunction *MF)=0
Gather pre-function debug information.
virtual void markFunctionEnd ()
virtual void endFunction (const MachineFunction *MF)=0
Gather post-function debug information.
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void endFragment ()
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
virtual void beginInstruction (const MachineInstr *MI)=0
Process beginning of an instruction.
virtual void endInstruction ()=0
Process end of an instruction.
Detailed Description
Collects and handles AsmPrinter objects required to build debug or EH information.
Definition at line 31 of file AsmPrinterHandler.h.
Constructor & Destructor Documentation
~AsmPrinterHandler()
AsmPrinterHandler::~AsmPrinterHandler () virtual default
Pin vtable to this file.
Referenced by llvm::AsmPrinter::emitStackMaps().
Member Function Documentation
beginFragment()
virtual void llvm::AsmPrinterHandler::beginFragment (const MachineBasicBlock * MBB, ExceptionSymbolProvider ESP) inline virtual
Reimplemented in llvm::DwarfCFIException.
Definition at line 56 of file AsmPrinterHandler.h.
beginFunclet()
virtual void llvm::AsmPrinterHandler::beginFunclet (const MachineBasicBlock & MBB, MCSymbol * Sym = nullptr) inline virtual
Emit target-specific EH funclet machinery.
Reimplemented in llvm::WinException.
Definition at line 61 of file AsmPrinterHandler.h.
beginFunction()
virtual void llvm::AsmPrinterHandler::beginFunction (const MachineFunction * MF) pure virtual
Gather pre-function debug information.
Every beginFunction(MF) call should be followed by an endFunction(MF) call.
Implemented in llvm::DebugHandlerBase, llvm::WinException, llvm::ARMException, llvm::DwarfCFIException, llvm::WinCFGuard, and llvm::WasmException.
beginInstruction()
virtual void llvm::AsmPrinterHandler::beginInstruction (const MachineInstr * MI) pure virtual
Process beginning of an instruction.
Implemented in llvm::DwarfDebug, llvm::CodeViewDebug, llvm::BTFDebug, llvm::EHStreamer, llvm::DebugHandlerBase, and llvm::WinCFGuard.
Referenced by endFunclet().
endFragment()
virtual void llvm::AsmPrinterHandler::endFragment () inline virtual
Reimplemented in llvm::DwarfCFIExceptionBase.
Definition at line 58 of file AsmPrinterHandler.h.
endFunclet()
virtual void llvm::AsmPrinterHandler::endFunclet () inline virtual
Reimplemented in llvm::WinException.
Definition at line 63 of file AsmPrinterHandler.h.
References beginInstruction(), endInstruction(), and MI.
endFunction()
virtual void llvm::AsmPrinterHandler::endFunction (const MachineFunction * MF) pure virtual
Gather post-function debug information.
Please note that some AsmPrinter implementations may not call beginFunction at all.
Implemented in llvm::DebugHandlerBase, llvm::WinException, llvm::ARMException, llvm::DwarfCFIException, llvm::WinCFGuard, and llvm::WasmException.
endInstruction()
virtual void llvm::AsmPrinterHandler::endInstruction () pure virtual
Process end of an instruction.
Implemented in llvm::EHStreamer, llvm::DebugHandlerBase, and llvm::WinCFGuard.
Referenced by endFunclet().
endModule()
virtual void llvm::AsmPrinterHandler::endModule () pure virtual
Emit all sections that should come after the content.
Implemented in llvm::DwarfDebug, llvm::CodeViewDebug, llvm::BTFDebug, llvm::WinException, llvm::ARMException, llvm::DwarfCFIException, llvm::WinCFGuard, and llvm::WasmException.
markFunctionEnd()
void AsmPrinterHandler::markFunctionEnd () virtual
Reimplemented in llvm::WinException, llvm::DwarfCFIExceptionBase, and llvm::WasmException.
Definition at line 3137 of file AsmPrinter.cpp.
setSymbolSize()
virtual void llvm::AsmPrinterHandler::setSymbolSize (const MCSymbol * Sym, uint64_t Size) pure virtual
For symbols that have a size designated (e.g.
common symbols), this tracks that size.
Implemented in llvm::DwarfDebug, llvm::CodeViewDebug, llvm::BTFDebug, llvm::EHStreamer, and llvm::WinCFGuard.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AsmPrinterHandler.h
lib/CodeGen/AsmPrinter/AsmPrinter.cpp