LLVM: llvm::xray::RecordVisitor Class Reference
llvm::xray::RecordVisitor Class Reference abstract
#include "llvm/XRay/FDRRecords.h"
Public Member Functions
virtual ~RecordVisitor ()=default
virtual Error visit (BufferExtents &)=0
virtual Error visit (WallclockRecord &)=0
virtual Error visit (NewCPUIDRecord &)=0
virtual Error visit (TSCWrapRecord &)=0
virtual Error visit (CustomEventRecord &)=0
virtual Error visit (CallArgRecord &)=0
virtual Error visit (PIDRecord &)=0
virtual Error visit (NewBufferRecord &)=0
virtual Error visit (EndBufferRecord &)=0
virtual Error visit (FunctionRecord &)=0
virtual Error visit (CustomEventRecordV5 &)=0
virtual Error visit (TypedEventRecord &)=0
Detailed Description
Definition at line 399 of file FDRRecords.h.
Constructor & Destructor Documentation
~RecordVisitor()
virtual llvm::xray::RecordVisitor::~RecordVisitor () virtual default
Member Function Documentation
visit() [1/12]
virtual Error llvm::xray::RecordVisitor::visit (BufferExtents &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
Referenced by llvm::xray::BufferExtents::apply(), llvm::xray::WallclockRecord::apply(), llvm::xray::NewCPUIDRecord::apply(), llvm::xray::TSCWrapRecord::apply(), llvm::xray::CustomEventRecord::apply(), llvm::xray::CustomEventRecordV5::apply(), llvm::xray::TypedEventRecord::apply(), llvm::xray::CallArgRecord::apply(), llvm::xray::PIDRecord::apply(), llvm::xray::NewBufferRecord::apply(), llvm::xray::EndBufferRecord::apply(), and llvm::xray::FunctionRecord::apply().
visit() [2/12]
virtual Error llvm::xray::RecordVisitor::visit (WallclockRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [3/12]
virtual Error llvm::xray::RecordVisitor::visit (NewCPUIDRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [4/12]
virtual Error llvm::xray::RecordVisitor::visit (TSCWrapRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [5/12]
virtual Error llvm::xray::RecordVisitor::visit (CustomEventRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [6/12]
virtual Error llvm::xray::RecordVisitor::visit (CallArgRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [7/12]
virtual Error llvm::xray::RecordVisitor::visit (PIDRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [8/12]
virtual Error llvm::xray::RecordVisitor::visit (NewBufferRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [9/12]
virtual Error llvm::xray::RecordVisitor::visit (EndBufferRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [10/12]
virtual Error llvm::xray::RecordVisitor::visit (FunctionRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [11/12]
virtual Error llvm::xray::RecordVisitor::visit (CustomEventRecordV5 &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
visit() [12/12]
virtual Error llvm::xray::RecordVisitor::visit (TypedEventRecord &) pure virtual
Implemented in llvm::xray::RecordInitializer, llvm::xray::BlockVerifier, llvm::xray::BlockIndexer, llvm::xray::BlockPrinter, llvm::xray::TraceExpander, llvm::xray::FDRTraceWriter, and llvm::xray::RecordPrinter.
The documentation for this class was generated from the following file:
include/llvm/XRay/FDRRecords.h