LLVM: llvm::AMDGPULibCalls Class Reference
llvm::AMDGPULibCalls Class Reference
Public Member Functions
AMDGPULibCalls (const TargetMachine *TM_=nullptr)
bool fold (CallInst *CI, AliasAnalysis *AA=nullptr)
void initNativeFuncs ()
bool useNative (CallInst *CI)
Protected Member Functions
bool isUnsafeMath (const CallInst *CI) const
void replaceCall (Value *With)
Protected Attributes
CallInst * CI
Detailed Description
Definition at line 60 of file AMDGPULibCalls.cpp.
Constructor & Destructor Documentation
AMDGPULibCalls()
llvm::AMDGPULibCalls::AMDGPULibCalls (const TargetMachine * TM_ = nullptr) inline
Definition at line 157 of file AMDGPULibCalls.cpp.
References llvm::AnalysisUsage::addRequired(), F(), fold(), llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeAMDGPUSimplifyLibCallsPass(), llvm::initializeAMDGPUUseNativeCallsPass(), initNativeFuncs(), runOnFunction(), and useNative().
Member Function Documentation
fold()
bool AMDGPULibCalls::fold (CallInst * CI, AliasAnalysis * AA = nullptr)
Definition at line 640 of file AMDGPULibCalls.cpp.
References assert(), B, CI, Context, llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::dbgs(), llvm::dyn_cast(), llvm::AMDGPULibFuncBase::EI_COS, llvm::AMDGPULibFuncBase::EI_DIVIDE, llvm::AMDGPULibFuncBase::EI_FMA, llvm::AMDGPULibFuncBase::EI_MAD, llvm::AMDGPULibFuncBase::EI_NFMA, llvm::AMDGPULibFuncBase::EI_POW, llvm::AMDGPULibFuncBase::EI_POWN, llvm::AMDGPULibFuncBase::EI_POWR, llvm::AMDGPULibFuncBase::EI_READ_PIPE_2, llvm::AMDGPULibFuncBase::EI_READ_PIPE_4, llvm::AMDGPULibFuncBase::EI_RECIP, llvm::AMDGPULibFuncBase::EI_ROOTN, llvm::AMDGPULibFuncBase::EI_SIN, llvm::AMDGPULibFuncBase::EI_SQRT, llvm::AMDGPULibFuncBase::EI_WRITE_PIPE_2, llvm::AMDGPULibFuncBase::EI_WRITE_PIPE_4, EnablePreLink, llvm::errs(), llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, false, llvm::ConstantFP::get(), llvm::ConstantDataVector::get(), llvm::CallBase::getArgOperand(), getArgType(), llvm::CallBase::getCalledFunction(), llvm::BasicBlock::getContext(), llvm::Function::getContext(), llvm::AMDGPULibFunc::getId(), llvm::Function::getIntrinsicID(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::CallBase::getNumArgOperands(), llvm::AMDGPULibFunc::getNumArgs(), getOptTable(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::AMDGPULibFunc::getPrefix(), llvm::Value::getType(), getVecSize(), llvm::AMDGPULibFuncBase::HALF, HasNative(), llvm::ConstantFP::isExactlyValue(), isUnsafeMath(), LLVM_DEBUG, llvm::AMDGPULibFuncBase::NATIVE, llvm::AMDGPULibFuncBase::NOPFX, llvm::SmallVectorTemplateBase< T >::push_back(), replaceCall(), llvm::CallBase::setCalledFunction(), llvm::IRBuilderBase::setFastMathFlags(), llvm::IRBuilderBase::SetInsertPoint(), llvm::AMDGPULibFunc::setPrefix(), llvm::SmallVectorBase::size(), TableRef::size, and TableRef::table.
Referenced by AMDGPULibCalls().
initNativeFuncs()
void AMDGPULibCalls::initNativeFuncs ()
Definition at line 506 of file AMDGPULibCalls.cpp.
References llvm::AMDGPULibFuncBase::Param::ArgType, llvm::CallInst::Create(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::AMDGPULibFuncBase::EI_COS, llvm::AMDGPULibFuncBase::EI_SIN, llvm::CallBase::getArgOperand(), llvm::AMDGPULibFunc::getLeads(), llvm::Instruction::getModule(), llvm::AMDGPULibFuncBase::NATIVE, replaceCall(), llvm::AMDGPULibFunc::setId(), llvm::AMDGPULibFunc::setPrefix(), UseNative, and llvm::AMDGPULibFuncBase::Param::VectorSize.
Referenced by AMDGPULibCalls().
isUnsafeMath()
bool AMDGPULibCalls::isUnsafeMath (const CallInst * CI) const protected
Definition at line 492 of file AMDGPULibCalls.cpp.
References F(), llvm::find(), llvm::Function::getFnAttribute(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::Attribute::getValueAsString(), and UseNative.
Referenced by fold(), and llvm::log2().
replaceCall()
void llvm::AMDGPULibCalls::replaceCall (Value * With) inline protected
Definition at line 151 of file AMDGPULibCalls.cpp.
References llvm::Instruction::eraseFromParent(), and llvm::Value::replaceAllUsesWith().
Referenced by fold(), initNativeFuncs(), and llvm::log2().
useNative()
bool AMDGPULibCalls::useNative (CallInst * CI)
Definition at line 546 of file AMDGPULibCalls.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), CI, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreatePointerCast(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::User::dropAllReferences(), llvm::AMDGPULibFuncBase::EI_SINCOS, llvm::Instruction::eraseFromParent(), llvm::AMDGPULibFuncBase::F64, llvm::FunctionType::get(), llvm::VectorType::get(), llvm::PointerType::get(), llvm::CallBase::getArgOperand(), getArgType(), llvm::CallBase::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::AMDGPULibFunc::getId(), llvm::Type::getInt64Ty(), llvm::Type::getIntNTy(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::AMDGPULibFunc::getName(), llvm::CallBase::getNumArgOperands(), llvm::AMDGPULibFunc::getOrInsertFunction(), llvm::Type::getPointerAddressSpace(), llvm::AMDGPULibFunc::getPrefix(), llvm::Value::getType(), HasNative(), I, llvm::AMDGPULibFunc::isMangled(), llvm::isPowerOf2_32(), Name, llvm::AMDGPULibFuncBase::NATIVE, llvm::AMDGPULibFuncBase::NOPFX, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::CallBase::setAttributes(), llvm::CallBase::setCalledFunction(), llvm::AMDGPULibFunc::setPrefix(), Size, and llvm::to_string().
Referenced by AMDGPULibCalls().
Member Data Documentation
CI
CallInst* llvm::AMDGPULibCalls::CI protected
Definition at line 147 of file AMDGPULibCalls.cpp.
Referenced by fold(), and useNative().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPULibCalls.cpp