LLVM: llvm::MemTransferBase< BaseCL > Class Template Reference
llvm::MemTransferBase< BaseCL > Class Template Reference
Common base class for all memory transfer intrinsics.
#include "llvm/IR/IntrinsicInst.h"
Public Member Functions
Value * getRawSource () const
Return the arguments to the instruction.
const Use & getRawSourceUse () const
Use & getRawSourceUse ()
Value * getSource () const
This is just like getRawSource, but it strips off any cast instructions that feed it, giving the original input.
unsigned getSourceAddressSpace () const
unsigned getSourceAlignment () const
FIXME: Remove this function once transition to Align is over.
MaybeAlign getSourceAlign () const
void setSource (Value *Ptr)
void setSourceAlignment (unsigned Alignment)
FIXME: Remove this function once transition to Align is over.
void setSourceAlignment (MaybeAlign Alignment)
void setSourceAlignment (Align Alignment)
Detailed Description
template<class BaseCL>
class llvm::MemTransferBase< BaseCL >
Common base class for all memory transfer intrinsics.
Simply provides common methods.
Definition at line 389 of file IntrinsicInst.h.
Member Function Documentation
getRawSource()
template<class BaseCL> Value* llvm::MemTransferBase< BaseCL >::getRawSource () const inline
Return the arguments to the instruction.
Definition at line 395 of file IntrinsicInst.h.
Referenced by llvm::expandMemCpyAsLoop(), llvm::expandMemMoveAsLoop(), FixedPointIntrinsicToOpcode(), getComparePred(), llvm::MemoryLocation::getForSource(), hasUndefContents(), isCallPromotable(), moveUp(), AllocaSlices::SliceBuilder::SliceBuilder(), and llvm::sroa::AllocaSliceRewriter::visit().
getRawSourceUse() [1/2]
template<class BaseCL> const Use& llvm::MemTransferBase< BaseCL >::getRawSourceUse () const inline
Definition at line 398 of file IntrinsicInst.h.
getRawSourceUse() [2/2]
template<class BaseCL> Use& llvm::MemTransferBase< BaseCL >::getRawSourceUse () inline
Definition at line 401 of file IntrinsicInst.h.
getSource()
template<class BaseCL> Value* llvm::MemTransferBase< BaseCL >::getSource () const inline
This is just like getRawSource, but it strips off any cast instructions that feed it, giving the original input.
The returned value is guaranteed to be a pointer.
Definition at line 406 of file IntrinsicInst.h.
Referenced by llvm::VNCoercion::getMemInstValueForLoadHelper(), hasUndefContents(), INITIALIZE_PASS(), isOnlyCopiedFromConstantGlobal(), and moveUp().
getSourceAddressSpace()
template<class BaseCL> unsigned llvm::MemTransferBase< BaseCL >::getSourceAddressSpace () const inline
Definition at line 408 of file IntrinsicInst.h.
Referenced by getComparePred(), llvm::ARMTTIImpl::getMemcpyCost(), and AllocaSlices::SliceBuilder::SliceBuilder().
getSourceAlign()
template<class BaseCL> MaybeAlign llvm::MemTransferBase< BaseCL >::getSourceAlign () const inline
Definition at line 418 of file IntrinsicInst.h.
Referenced by isCallPromotable(), and moveUp().
getSourceAlignment()
template<class BaseCL> unsigned llvm::MemTransferBase< BaseCL >::getSourceAlignment () const inline
FIXME: Remove this function once transition to Align is over.
Use getSourceAlign() instead.
Definition at line 414 of file IntrinsicInst.h.
Referenced by llvm::expandMemCpyAsLoop(), llvm::expandMemMoveAsLoop(), FixedPointIntrinsicToOpcode(), getComparePred(), llvm::ARMTTIImpl::getMemcpyCost(), hasUndefContents(), INITIALIZE_PASS(), and llvm::sroa::AllocaSliceRewriter::visit().
setSource()
template<class BaseCL> void llvm::MemTransferBase< BaseCL >::setSource (Value * Ptr) inline
Definition at line 422 of file IntrinsicInst.h.
Referenced by llvm::sroa::AllocaSliceRewriter::visit().
setSourceAlignment() [1/3]
template<class BaseCL> void llvm::MemTransferBase< BaseCL >::setSourceAlignment (unsigned Alignment) inline
FIXME: Remove this function once transition to Align is over.
Use the version that takes MaybeAlign instead of this one.
Definition at line 430 of file IntrinsicInst.h.
Referenced by llvm::sroa::AllocaSliceRewriter::visit().
setSourceAlignment() [2/3]
template<class BaseCL> void llvm::MemTransferBase< BaseCL >::setSourceAlignment (MaybeAlign Alignment) inline
Definition at line 433 of file IntrinsicInst.h.
setSourceAlignment() [3/3]
template<class BaseCL> void llvm::MemTransferBase< BaseCL >::setSourceAlignment (Align Alignment) inline
Definition at line 439 of file IntrinsicInst.h.
The documentation for this class was generated from the following file:
include/llvm/IR/IntrinsicInst.h