LLVM: llvm::sys::fs::file_status Class Reference
llvm::sys::fs::file_status Class Reference
Represents the result of a call to sys::fs::status().
#include "llvm/Support/FileSystem.h"
Public Member Functions
file_status ()=default
file_status (file_type Type)
file_status (file_type Type, perms Perms, dev_t Dev, nlink_t Links, ino_t Ino, time_t ATime, uint32_t ATimeNSec, time_t MTime, uint32_t MTimeNSec, uid_t UID, gid_t GID, off_t Size)
UniqueID getUniqueID () const
uint32_t getLinkCount () const
Public Member Functions inherited from llvm::sys::fs::basic_file_status
basic_file_status ()=default
basic_file_status (file_type Type)
basic_file_status (file_type Type, perms Perms, time_t ATime, uint32_t ATimeNSec, time_t MTime, uint32_t MTimeNSec, uid_t UID, gid_t GID, off_t Size)
file_type type () const
perms permissions () const
TimePoint getLastAccessedTime () const
The file access time as reported from the underlying file system.
TimePoint getLastModificationTime () const
The file modification time as reported from the underlying file system.
uint32_t getUser () const
uint32_t getGroup () const
uint64_t getSize () const
void type (file_type v)
void permissions (perms p)
Friends
bool equivalent (file_status A, file_status B)
Do file_status's represent the same thing?
Additional Inherited Members
Protected Attributes inherited from llvm::sys::fs::basic_file_status
time_t fs_st_atime = 0
time_t fs_st_mtime = 0
uint32_t fs_st_atime_nsec = 0
uint32_t fs_st_mtime_nsec = 0
uid_t fs_st_uid = 0
gid_t fs_st_gid = 0
off_t fs_st_size = 0
file_type Type = file_type::status_error
perms Perms = perms_not_known
Detailed Description
Represents the result of a call to sys::fs::status().
Definition at line 246 of file FileSystem.h.
Constructor & Destructor Documentation
file_status() [1/3]
llvm::sys::fs::file_status::file_status () default
file_status() [2/3]
llvm::sys::fs::file_status::file_status (file_type Type) inline explicit
Definition at line 263 of file FileSystem.h.
file_status() [3/3]
llvm::sys::fs::file_status::file_status (file_type Type, perms Perms, dev_t Dev, nlink_t Links, ino_t Ino, time_t ATime, uint32_t ATimeNSec, time_t MTime, uint32_t MTimeNSec, uid_t UID, gid_t GID, off_t Size) inline
Definition at line 266 of file FileSystem.h.
References llvm::sys::fs::copy_file(), llvm::sys::fs::create_directories(), llvm::sys::fs::create_directory(), llvm::sys::fs::create_hard_link(), llvm::sys::fs::create_link(), llvm::sys::fs::current_path(), llvm::sys::fs::exists(), llvm::sys::fs::expand_tilde(), From, llvm::sys::fs::getUniqueID(), llvm::sys::fs::group_all, llvm::sys::fs::make_absolute(), llvm::sys::fs::md5_contents(), llvm::sys::fs::owner_all, llvm::sys::fs::real_path(), llvm::sys::fs::remove_directories(), llvm::sys::fs::rename(), llvm::sys::fs::resize_file(), llvm::sys::fs::set_current_path(), Size, and llvm::sys::fs::status().
Member Function Documentation
getLinkCount()
uint32_t llvm::sys::fs::file_status::getLinkCount () const
getUniqueID()
UniqueID llvm::sys::fs::file_status::getUniqueID () const
Referenced by llvm::vfs::Status::copyWithNewName(), and llvm::sys::fs::getUniqueID().
Friends And Related Function Documentation
equivalent
bool equivalent (file_status A, file_status B) friend
Do file_status's represent the same thing?
Parameters
A Input file_status.
B Input file_status.
assert(status_known(A) || status_known(B));
Returns
True if A and B both represent the same file system entity, false otherwise.
The documentation for this class was generated from the following file:
include/llvm/Support/FileSystem.h