LLVM: llvm::WebAssemblyInstPrinter Class Reference
llvm::WebAssemblyInstPrinter Class Reference final
#include "Target/WebAssembly/MCTargetDesc/WebAssemblyInstPrinter.h"
Public Member Functions
WebAssemblyInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS) override
Print the specified MCInst to the specified raw_ostream.
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printBrList (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printWebAssemblyP2AlignOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printWebAssemblySignatureOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 26 of file WebAssemblyInstPrinter.h.
Constructor & Destructor Documentation
WebAssemblyInstPrinter()
WebAssemblyInstPrinter::WebAssemblyInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI)
Definition at line 35 of file WebAssemblyInstPrinter.cpp.
Member Function Documentation
getRegisterName()
static const char* llvm::WebAssemblyInstPrinter::getRegisterName (unsigned RegNo) static
printBrList()
void WebAssemblyInstPrinter::printBrList (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 253 of file WebAssemblyInstPrinter.cpp.
References E, llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), and I.
printInst()
void WebAssemblyInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 47 of file WebAssemblyInstPrinter.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::MCInstPrinter::CommentStream, llvm::Depth, E, llvm::SmallVectorBase::empty(), llvm::bitc::END_BLOCK, llvm::MCInstrInfo::get(), llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), I, llvm::SmallSet< T, N, C >::insert(), llvm::MCOperand::isImm(), llvm::MCInstrDesc::isVariadic(), llvm::AMDGPUISD::LOOP, llvm::MCInstPrinter::MII, llvm::MCInstrDesc::NumOperands, llvm::WebAssembly::OPERAND_BASIC_BLOCK, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), printOperand(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), llvm::SmallVectorBase::size(), and llvm::utostr().
printInstruction()
void llvm::WebAssemblyInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by printInst().
printOperand()
void WebAssemblyInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 209 of file WebAssemblyInstPrinter.cpp.
References llvm::lltok::APFloat, assert(), llvm::MCInstrInfo::get(), llvm::MCOperand::getExpr(), llvm::MCOperand::getFPImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::WebAssemblyFunctionInfo::getWARegStackId(), Info, llvm::MCOperand::isExpr(), llvm::MCOperand::isFPImm(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MII, llvm::WebAssembly::OPERAND_F32IMM, llvm::WebAssembly::OPERAND_F64IMM, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, llvm::MCExpr::print(), printRegName(), llvm::WebAssembly::signatureToString(), llvm::toString(), llvm::WebAssemblyFunctionInfo::UnusedReg, and llvm::MCSymbolRefExpr::VK_WASM_TYPEINDEX.
Referenced by printInst().
printRegName()
void WebAssemblyInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 40 of file WebAssemblyInstPrinter.cpp.
References assert(), and llvm::WebAssemblyFunctionInfo::UnusedReg.
Referenced by printOperand().
printWebAssemblyP2AlignOperand()
void WebAssemblyInstPrinter::printWebAssemblyP2AlignOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 264 of file WebAssemblyInstPrinter.cpp.
References llvm::WebAssembly::GetDefaultP2Align(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), and llvm::MCInst::getOperand().
printWebAssemblySignatureOperand()
void WebAssemblyInstPrinter::printWebAssemblySignatureOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 273 of file WebAssemblyInstPrinter.cpp.
References llvm::WebAssembly::anyTypeToString(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm::WebAssembly::signatureToString(), and llvm::wasm::WASM_TYPE_NORESULT.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyInstPrinter.h
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyInstPrinter.cpp