LLVM: llvm::object::Archive::Child Class Reference
llvm::object::Archive::Child Class Reference
#include "llvm/Object/Archive.h"
Public Member Functions
Child (const Archive *Parent, const char *Start, Error *Err)
Child (const Archive *Parent, StringRef Data, uint16_t StartOfFile)
bool operator== (const Child &other) const
const Archive * getParent () const
Expected< Child > getNext () const
Expected< StringRef > getName () const
Expected< std::string > getFullName () const
Expected< StringRef > getRawName () const
Expected< sys::TimePoint< std::chrono::seconds > > getLastModified () const
StringRef getRawLastModified () const
Expected< unsigned > getUID () const
Expected< unsigned > getGID () const
Expected< sys::fs::perms > getAccessMode () const
Expected< uint64_t > getSize () const
Expected< uint64_t > getRawSize () const
Expected< StringRef > getBuffer () const
uint64_t getChildOffset () const
uint64_t getDataOffset () const
Expected< MemoryBufferRef > getMemoryBufferRef () const
Expected< std::unique_ptr< Binary > > getAsBinary (LLVMContext *Context=nullptr) const
Detailed Description
Definition at line 87 of file Archive.h.
Constructor & Destructor Documentation
Child() [1/2]
Archive::Child::Child (const Archive * Parent, const char * Start, Error * Err)
Definition at line 327 of file Archive.cpp.
Referenced by getNext().
Child() [2/2]
Archive::Child::Child (const Archive * Parent, StringRef Data, uint16_t StartOfFile)
Definition at line 321 of file Archive.cpp.
Member Function Documentation
getAccessMode()
Expected<sys::fs::perms> llvm::object::Archive::Child::getAccessMode () const inline
Definition at line 127 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getAccessMode(), and llvm::object::ArchiveMemberHeader::getSize().
Referenced by llvm::NewArchiveMember::getOldMember().
getAsBinary()
Expected< std::unique_ptr< Binary > > Archive::Child::getAsBinary (LLVMContext * Context = nullptr) const
Definition at line 519 of file Archive.cpp.
References Context, llvm::object::createBinary(), llvm::Expected< T >::get(), getMemoryBufferRef(), and llvm::Expected< T >::takeError().
getBuffer()
Expected< StringRef > Archive::Child::getBuffer () const
Definition at line 434 of file Archive.cpp.
References llvm::StringRef::data(), llvm::errorCodeToError(), llvm::Expected< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), getFullName(), getSize(), llvm::object::Archive::isThin(), Size, and llvm::Expected< T >::takeError().
Referenced by getMemoryBufferRef().
getChildOffset()
uint64_t Archive::Child::getChildOffset () const
Definition at line 488 of file Archive.cpp.
References llvm::object::Binary::Data, llvm::StringRef::data(), and llvm::MemoryBufferRef::getBuffer().
getDataOffset()
uint64_t llvm::object::Archive::Child::getDataOffset () const inline
Definition at line 138 of file Archive.h.
References Context.
getFullName()
Expected< std::string > Archive::Child::getFullName () const
Definition at line 416 of file Archive.cpp.
References llvm::sys::path::append(), assert(), llvm::Expected< T >::get(), llvm::MemoryBufferRef::getBufferIdentifier(), llvm::object::Binary::getMemoryBufferRef(), getName(), llvm::sys::path::is_absolute(), llvm::object::Archive::isThin(), Name, llvm::sys::path::parent_path(), and llvm::Expected< T >::takeError().
Referenced by getBuffer().
getGID()
Expected<unsigned> llvm::object::Archive::Child::getGID () const inline
Definition at line 125 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getGID().
Referenced by llvm::NewArchiveMember::getOldMember().
getLastModified()
Expected<sys::TimePoint<std::chrono::seconds> > llvm::object::Archive::Child::getLastModified () const inline
Definition at line 116 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getLastModified().
Referenced by llvm::NewArchiveMember::getOldMember().
getMemoryBufferRef()
Expected< MemoryBufferRef > Archive::Child::getMemoryBufferRef () const
Definition at line 507 of file Archive.cpp.
References llvm::createFileError(), llvm::Expected< T >::get(), getBuffer(), getName(), Name, and llvm::Expected< T >::takeError().
Referenced by getAsBinary(), and llvm::NewArchiveMember::getOldMember().
getName()
Expected< StringRef > Archive::Child::getName () const
Definition at line 495 of file Archive.cpp.
References llvm::Expected< T >::get(), llvm::object::ArchiveMemberHeader::getName(), getRawSize(), llvm::object::ArchiveMemberHeader::getSizeOf(), Name, and llvm::Expected< T >::takeError().
Referenced by getFullName(), getMemoryBufferRef(), and getNext().
getNext()
Expected< Archive::Child > Archive::Child::getNext () const
Definition at line 456 of file Archive.cpp.
References Child(), llvm::consumeError(), llvm::object::Binary::Data, llvm::StringRef::data(), llvm::Expected< T >::get(), llvm::MemoryBufferRef::getBufferEnd(), llvm::object::Binary::getData(), getName(), malformedError(), llvm::StringRef::size(), and llvm::Expected< T >::takeError().
Referenced by llvm::object::Archive::ChildFallibleIterator::inc().
getParent()
const Archive* llvm::object::Archive::Child::getParent () const inline
Definition at line 109 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getName().
getRawLastModified()
StringRef llvm::object::Archive::Child::getRawLastModified () const inline
Definition at line 120 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getRawLastModified().
getRawName()
Expected<StringRef> llvm::object::Archive::Child::getRawName () const inline
Definition at line 114 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getRawName().
getRawSize()
Expected< uint64_t > Archive::Child::getRawSize () const
Returns
the size in the archive header for this member.
Definition at line 404 of file Archive.cpp.
References llvm::Expected< T >::get(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::object::ArchiveMemberHeader::getSize(), Name, and llvm::Expected< T >::takeError().
Referenced by getName().
getSize()
Expected< uint64_t > Archive::Child::getSize () const
Returns
the size of the archive member without the header or padding.
Definition at line 394 of file Archive.cpp.
References llvm::Expected< T >::get(), llvm::object::ArchiveMemberHeader::getSize(), Size, llvm::StringRef::size(), and llvm::Expected< T >::takeError().
Referenced by getBuffer().
getUID()
Expected<unsigned> llvm::object::Archive::Child::getUID () const inline
Definition at line 124 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getUID().
Referenced by llvm::NewArchiveMember::getOldMember().
operator==()
bool llvm::object::Archive::Child::operator== (const Child & other) const inline
Definition at line 104 of file Archive.h.
References assert(), and llvm::StringRef::begin().
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp