LLVM: llvm::LivePhysRegs Class Reference
llvm::LivePhysRegs Class Reference
A set of physical registers with utility functions to track liveness when walking backward/forward through a basic block.
#include "llvm/CodeGen/LivePhysRegs.h"
Public Types
using const_iterator = RegisterSet::const_iterator
Public Member Functions
LivePhysRegs ()=default
Constructs an unitialized set. init() needs to be called to initialize it.
LivePhysRegs (const TargetRegisterInfo &TRI)
Constructs and initializes an empty set.
LivePhysRegs (const LivePhysRegs &)=delete
LivePhysRegs & operator= (const LivePhysRegs &)=delete
void init (const TargetRegisterInfo &TRI)
(re-)initializes and clears the set.
void clear ()
Clears the set.
bool empty () const
Returns true if the set is empty.
void addReg (MCPhysReg Reg)
Adds a physical register and all its sub-registers to the set.
void removeReg (MCPhysReg Reg)
Removes a physical register, all its sub-registers, and all its super-registers from the set.
void removeRegsInMask (const MachineOperand &MO, SmallVectorImpl< std::pair< MCPhysReg, const MachineOperand *>> *Clobbers=nullptr)
Removes physical registers clobbered by the regmask operand MO.
bool contains (MCPhysReg Reg) const
Returns true if register Reg is contained in the set.
bool available (const MachineRegisterInfo &MRI, MCPhysReg Reg) const
Returns true if register Reg and no aliasing register is in the set.
void removeDefs (const MachineInstr &MI)
Remove defined registers and regmask kills from the set.
void addUses (const MachineInstr &MI)
Add uses to the set.
void stepBackward (const MachineInstr &MI)
Simulates liveness when stepping backwards over an instruction(bundle).
void stepForward (const MachineInstr &MI, SmallVectorImpl< std::pair< MCPhysReg, const MachineOperand *>> &Clobbers)
Simulates liveness when stepping forward over an instruction(bundle).
void addLiveIns (const MachineBasicBlock &MBB)
Adds all live-in registers of basic block MBB.
void addLiveOuts (const MachineBasicBlock &MBB)
Adds all live-out registers of basic block MBB.
void addLiveOutsNoPristines (const MachineBasicBlock &MBB)
Adds all live-out registers of basic block MBB but skips pristine registers.
const_iterator begin () const
const_iterator end () const
void print (raw_ostream &OS) const
Prints the currently live registers to OS.
void dump () const
Dumps the currently live registers to the debug output.
Detailed Description
A set of physical registers with utility functions to track liveness when walking backward/forward through a basic block.
Definition at line 48 of file LivePhysRegs.h.
Member Typedef Documentation
const_iterator
using llvm::LivePhysRegs::const_iterator = RegisterSet::const_iterator
Definition at line 149 of file LivePhysRegs.h.
Constructor & Destructor Documentation
LivePhysRegs() [1/3]
llvm::LivePhysRegs::LivePhysRegs () default
Constructs an unitialized set. init() needs to be called to initialize it.
Referenced by LivePhysRegs().
LivePhysRegs() [2/3]
llvm::LivePhysRegs::LivePhysRegs (const TargetRegisterInfo & TRI) inline
Constructs and initializes an empty set.
Definition at line 58 of file LivePhysRegs.h.
References llvm::MCRegisterInfo::getNumRegs(), LivePhysRegs(), operator=(), and llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::setUniverse().
LivePhysRegs() [3/3]
llvm::LivePhysRegs::LivePhysRegs (const LivePhysRegs &) delete
Member Function Documentation
addLiveIns()
void LivePhysRegs::addLiveIns (const MachineBasicBlock & MBB)
Adds all live-in registers of basic block MBB.
Live in registers are the registers in the blocks live-in list and the pristine registers.
Definition at line 236 of file LivePhysRegs.cpp.
References llvm::MachineBasicBlock::getParent().
Referenced by llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::computeAndAddLiveIns(), contains(), llvm::SIFrameLowering::emitPrologue(), findScratchNonCalleeSaveRegister(), and llvm::operator<<().
addLiveOuts()
void LivePhysRegs::addLiveOuts (const MachineBasicBlock & MBB)
Adds all live-out registers of basic block MBB.
Live out registers are the union of the live-in registers of the successor blocks and pristine registers. Live out registers of the end block are the callee saved registers. If a register is not added by this method, it is guaranteed to not be live out from MBB, although a sub-register may be. This is true both before and after regalloc.
Definition at line 230 of file LivePhysRegs.cpp.
References addLiveOutsNoPristines(), and llvm::MachineBasicBlock::getParent().
Referenced by CompareMBBNumbers(), ComputeCommonTailLength(), contains(), llvm::SIFrameLowering::emitEpilogue(), findTemporariesForLR(), llvm::ScheduleDAGInstrs::fixupKills(), getLiveRegsAt(), llvm::ReachingDefAnalysis::getLocalLiveOutMIDef(), INITIALIZE_PASS(), isCompareZero(), llvm::ReachingDefAnalysis::isReachingDefLiveOut(), llvm::ReachingDefAnalysis::isRegUsedAfter(), mergeOperations(), and llvm::X86InstrInfo::replaceBranchWithTailCall().
addLiveOutsNoPristines()
void LivePhysRegs::addLiveOutsNoPristines (const MachineBasicBlock & MBB)
Adds all live-out registers of basic block MBB but skips pristine registers.
Definition at line 207 of file LivePhysRegs.cpp.
References addReg(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), Info, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), llvm::MachineBasicBlock::isReturnBlock(), and llvm::MachineBasicBlock::successors().
Referenced by addLiveOuts(), llvm::computeLiveIns(), contains(), and llvm::recomputeLivenessFlags().
addReg()
void llvm::LivePhysRegs::addReg (MCPhysReg Reg) inline
Adds a physical register and all its sub-registers to the set.
Definition at line 79 of file LivePhysRegs.h.
References assert(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::insert(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by addCalleeSavedRegs(), addLiveOutsNoPristines(), addUses(), available(), llvm::SIFrameLowering::emitPrologue(), findScratchNonCalleeSaveRegister(), findTemporariesForLR(), stepForward(), and toggleKills().
addUses()
void LivePhysRegs::addUses (const MachineInstr & MI)
Add uses to the set.
Definition at line 58 of file LivePhysRegs.cpp.
References addReg(), and llvm::phys_regs_and_masks().
Referenced by contains(), llvm::recomputeLivenessFlags(), and stepBackward().
available()
bool LivePhysRegs::available (const MachineRegisterInfo & MRI, MCPhysReg Reg) const
Returns true if register Reg and no aliasing register is in the set.
Definition at line 139 of file LivePhysRegs.cpp.
References addReg(), llvm::LaneBitmask::all(), llvm::LaneBitmask::any(), assert(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::count(), llvm::MCSubRegIndexIterator::getSubReg(), llvm::MCSubRegIndexIterator::getSubRegIndex(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::MachineRegisterInfo::isReserved(), llvm::MCSubRegIndexIterator::isValid(), llvm::MachineBasicBlock::liveins(), llvm::BitmaskEnumDetail::Mask(), Reg, and SI.
Referenced by ComputeCommonTailLength(), contains(), llvm::HexagonInstrInfo::expandPostRAPseudo(), findScratchNonCalleeSaveRegister(), mergeOperations(), llvm::recomputeLivenessFlags(), and toggleKills().
begin()
const_iterator llvm::LivePhysRegs::begin () const inline
Definition at line 151 of file LivePhysRegs.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::begin().
Referenced by print().
clear()
void llvm::LivePhysRegs::clear () inline
Clears the set.
Definition at line 73 of file LivePhysRegs.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::clear().
Referenced by ComputeCommonTailLength(), and mergeOperations().
contains()
bool llvm::LivePhysRegs::contains (MCPhysReg Reg) const inline
Returns true if register Reg is contained in the set.
This also works if only the super register of Reg has been defined, because addReg() always adds all sub-registers to the set as well. Note: Returns false if just some sub registers are live, use available() when searching a free register.
Definition at line 106 of file LivePhysRegs.h.
References addLiveIns(), addLiveOuts(), addLiveOutsNoPristines(), addUses(), available(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::count(), MI, MRI, Reg, removeDefs(), stepBackward(), and stepForward().
Referenced by llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), findTemporariesForLR(), llvm::ReachingDefAnalysis::getLocalLiveOutMIDef(), isCompareZero(), llvm::ReachingDefAnalysis::isReachingDefLiveOut(), and llvm::ReachingDefAnalysis::isRegUsedAfter().
dump()
LLVM_DUMP_METHOD void LivePhysRegs::dump () const
Dumps the currently live registers to the debug output.
Definition at line 134 of file LivePhysRegs.cpp.
References llvm::dbgs().
Referenced by end().
empty()
bool llvm::LivePhysRegs::empty () const inline
Returns true if the set is empty.
Definition at line 76 of file LivePhysRegs.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::empty().
Referenced by addCalleeSavedRegs(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), and print().
end()
const_iterator llvm::LivePhysRegs::end () const inline
Definition at line 152 of file LivePhysRegs.h.
References dump(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), and print().
Referenced by print().
init()
void llvm::LivePhysRegs::init (const TargetRegisterInfo & TRI) inline
(re-)initializes and clears the set.
Definition at line 66 of file LivePhysRegs.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::clear(), llvm::MCRegisterInfo::getNumRegs(), and llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::setUniverse().
Referenced by llvm::computeLiveIns(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), findUnusedSGPRNonCalleeSaved(), llvm::ScheduleDAGInstrs::fixupKills(), mergeOperations(), and llvm::recomputeLivenessFlags().
operator=()
LivePhysRegs& llvm::LivePhysRegs::operator= (const LivePhysRegs &) delete
Referenced by LivePhysRegs().
print()
void LivePhysRegs::print (raw_ostream & OS) const
Prints the currently live registers to OS.
Print the currently live registers to OS.
Definition at line 116 of file LivePhysRegs.cpp.
References begin(), E, empty(), end(), I, and llvm::printReg().
Referenced by end(), and llvm::operator<<().
removeDefs()
void LivePhysRegs::removeDefs (const MachineInstr & MI)
Remove defined registers and regmask kills from the set.
Definition at line 45 of file LivePhysRegs.cpp.
References llvm::phys_regs_and_masks(), removeReg(), and removeRegsInMask().
Referenced by contains(), llvm::recomputeLivenessFlags(), and stepBackward().
removeReg()
void llvm::LivePhysRegs::removeReg (MCPhysReg Reg) inline
Removes a physical register, all its sub-registers, and all its super-registers from the set.
Definition at line 89 of file LivePhysRegs.h.
References assert(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase(), and removeRegsInMask().
Referenced by addCalleeSavedRegs(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), llvm::ScheduleDAGInstrs::fixupKills(), removeDefs(), and stepForward().
removeRegsInMask()
void LivePhysRegs::removeRegsInMask (const MachineOperand & MO, SmallVectorImpl< std::pair< MCPhysReg, const MachineOperand *>> * Clobbers = nullptr)
Removes physical registers clobbered by the regmask operand MO.
Remove all registers from the set that get clobbered by the register mask.
The clobbers set will be the list of live registers clobbered by the regmask.
Definition at line 31 of file LivePhysRegs.cpp.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::begin(), llvm::MachineOperand::clobbersPhysReg(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), and llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase().
Referenced by llvm::ScheduleDAGInstrs::fixupKills(), removeDefs(), removeReg(), and stepForward().
stepBackward()
void LivePhysRegs::stepBackward (const MachineInstr & MI)
Simulates liveness when stepping backwards over an instruction(bundle).
Simulates liveness when stepping backwards over an instruction(bundle): Remove Defs, add uses.
Remove Defs, add uses. This is the recommended way of calculating liveness.
This is the recommended way of calculating liveness.
Definition at line 68 of file LivePhysRegs.cpp.
References addUses(), and removeDefs().
Referenced by ComputeCommonTailLength(), llvm::computeLiveIns(), contains(), llvm::SIFrameLowering::emitEpilogue(), findTemporariesForLR(), and getLiveRegsAt().
stepForward()
void LivePhysRegs::stepForward (const MachineInstr & MI, SmallVectorImpl< std::pair< MCPhysReg, const MachineOperand *>> & Clobbers)
Simulates liveness when stepping forward over an instruction(bundle).
Simulates liveness when stepping forward over an instruction(bundle): Remove killed-uses, add defs.
Remove killed-uses, add defs. This is the not recommended way, because it depends on accurate kill flags. If possible use stepBackward() instead of this function. The clobbers set will be the list of registers either defined or clobbered by a regmask. The operand will identify whether this is a regmask or register operand.
This is the not recommended way, because it depends on accurate kill flags. If possible use stepBackward() instead of this function.
Definition at line 80 of file LivePhysRegs.cpp.
References addReg(), assert(), llvm::MachineOperand::clobbersPhysReg(), llvm::Register::isPhysicalRegister(), llvm::RISCVFenceField::O, Reg, removeReg(), and removeRegsInMask().
Referenced by llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), contains(), and llvm::X86InstrInfo::replaceBranchWithTailCall().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LivePhysRegs.h
lib/CodeGen/LivePhysRegs.cpp