LLVM: llvm::codeview::OverloadedMethodRecord Class Reference
llvm::codeview::OverloadedMethodRecord Class Reference
For method overload sets. LF_METHOD.
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
OverloadedMethodRecord ()=default
OverloadedMethodRecord (TypeRecordKind Kind)
OverloadedMethodRecord (uint16_t NumOverloads, TypeIndex MethodList, StringRef Name)
uint16_t getNumOverloads () const
TypeIndex getMethodList () const
StringRef getName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
uint16_t NumOverloads = 0
TypeIndex MethodList
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
For method overload sets. LF_METHOD.
Definition at line 770 of file TypeRecord.h.
Constructor & Destructor Documentation
OverloadedMethodRecord() [1/3]
llvm::codeview::OverloadedMethodRecord::OverloadedMethodRecord () default
OverloadedMethodRecord() [2/3]
llvm::codeview::OverloadedMethodRecord::OverloadedMethodRecord (TypeRecordKind Kind) inline explicit
Definition at line 773 of file TypeRecord.h.
OverloadedMethodRecord() [3/3]
llvm::codeview::OverloadedMethodRecord::OverloadedMethodRecord (uint16_t NumOverloads, TypeIndex MethodList, StringRef Name) inline
Definition at line 774 of file TypeRecord.h.
Member Function Documentation
getMethodList()
TypeIndex llvm::codeview::OverloadedMethodRecord::getMethodList () const inline
Definition at line 780 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getName()
StringRef llvm::codeview::OverloadedMethodRecord::getName () const inline
Definition at line 781 of file TypeRecord.h.
References Name.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getNumOverloads()
uint16_t llvm::codeview::OverloadedMethodRecord::getNumOverloads () const inline
Definition at line 779 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
Member Data Documentation
MethodList
TypeIndex llvm::codeview::OverloadedMethodRecord::MethodList
Definition at line 784 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Name
StringRef llvm::codeview::OverloadedMethodRecord::Name
Definition at line 785 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
NumOverloads
uint16_t llvm::codeview::OverloadedMethodRecord::NumOverloads = 0
Definition at line 783 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h