LLVM: llvm::VPWidenPHIRecipe Class Reference
llvm::VPWidenPHIRecipe Class Reference
A recipe for handling all phi nodes except for integer and FP inductions.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenPHIRecipe (PHINode *Phi)
~VPWidenPHIRecipe () override=default
void execute (VPTransformState &State) override
Generate the phi/select nodes.
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenGEPSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Detailed Description
A recipe for handling all phi nodes except for integer and FP inductions.
Definition at line 818 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenPHIRecipe()
llvm::VPWidenPHIRecipe::VPWidenPHIRecipe (PHINode * Phi) inline
Definition at line 823 of file VPlan.h.
~VPWidenPHIRecipe()
llvm::VPWidenPHIRecipe::~VPWidenPHIRecipe () override default
Member Function Documentation
classof()
static bool llvm::VPWidenPHIRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 827 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID(), llvm::RISCVFenceField::O, and print().
execute()
void VPWidenPHIRecipe::execute (VPTransformState & State) override virtual
Generate the phi/select nodes.
Implements llvm::VPRecipeBase.
Definition at line 7370 of file LoopVectorize.cpp.
References llvm::VPTransformState::ILV, llvm::VPTransformState::UF, llvm::VPTransformState::VF, and llvm::InnerLoopVectorizer::widenPHIInstruction().
print()
void VPWidenPHIRecipe::print (raw_ostream & O, const Twine & Indent) const override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 700 of file VPlan.cpp.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp