LLVM: llvm::AVRMachineFunctionInfo Class Reference
llvm::AVRMachineFunctionInfo Class Reference
Contains AVR-specific information for each MachineFunction.
#include "Target/AVR/AVRMachineFunctionInfo.h"
Public Member Functions
AVRMachineFunctionInfo ()
AVRMachineFunctionInfo (MachineFunction &MF)
bool getHasSpills () const
void setHasSpills (bool B)
bool getHasAllocas () const
void setHasAllocas (bool B)
bool getHasStackArgs () const
void setHasStackArgs (bool B)
unsigned getCalleeSavedFrameSize () const
void setCalleeSavedFrameSize (unsigned Bytes)
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Idx)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Contains AVR-specific information for each MachineFunction.
Definition at line 21 of file AVRMachineFunctionInfo.h.
Constructor & Destructor Documentation
AVRMachineFunctionInfo() [1/2]
llvm::AVRMachineFunctionInfo::AVRMachineFunctionInfo () inline
Definition at line 42 of file AVRMachineFunctionInfo.h.
AVRMachineFunctionInfo() [2/2]
llvm::AVRMachineFunctionInfo::AVRMachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 46 of file AVRMachineFunctionInfo.h.
Member Function Documentation
getCalleeSavedFrameSize()
unsigned llvm::AVRMachineFunctionInfo::getCalleeSavedFrameSize () const inline
Definition at line 59 of file AVRMachineFunctionInfo.h.
Referenced by llvm::AVRFrameLowering::emitEpilogue(), and llvm::AVRFrameLowering::emitPrologue().
getHasAllocas()
bool llvm::AVRMachineFunctionInfo::getHasAllocas () const inline
Definition at line 53 of file AVRMachineFunctionInfo.h.
Referenced by llvm::AVRFrameLowering::hasFP().
getHasSpills()
bool llvm::AVRMachineFunctionInfo::getHasSpills () const inline
Definition at line 50 of file AVRMachineFunctionInfo.h.
Referenced by llvm::AVRFrameLowering::hasFP().
getHasStackArgs()
bool llvm::AVRMachineFunctionInfo::getHasStackArgs () const inline
Definition at line 56 of file AVRMachineFunctionInfo.h.
Referenced by llvm::AVRFrameLowering::hasFP().
getVarArgsFrameIndex()
int llvm::AVRMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 62 of file AVRMachineFunctionInfo.h.
Referenced by llvm::intCCToAVRCC().
setCalleeSavedFrameSize()
void llvm::AVRMachineFunctionInfo::setCalleeSavedFrameSize (unsigned Bytes) inline
Definition at line 60 of file AVRMachineFunctionInfo.h.
Referenced by llvm::AVRFrameLowering::spillCalleeSavedRegisters().
setHasAllocas()
void llvm::AVRMachineFunctionInfo::setHasAllocas (bool B) inline
Definition at line 54 of file AVRMachineFunctionInfo.h.
References B.
Referenced by llvm::AVRFrameAnalyzer::runOnMachineFunction().
setHasSpills()
void llvm::AVRMachineFunctionInfo::setHasSpills (bool B) inline
Definition at line 51 of file AVRMachineFunctionInfo.h.
References B.
Referenced by llvm::AVRInstrInfo::storeRegToStackSlot().
setHasStackArgs()
void llvm::AVRMachineFunctionInfo::setHasStackArgs (bool B) inline
Definition at line 57 of file AVRMachineFunctionInfo.h.
References B.
Referenced by llvm::AVRFrameAnalyzer::runOnMachineFunction().
setVarArgsFrameIndex()
void llvm::AVRMachineFunctionInfo::setVarArgsFrameIndex (int Idx) inline
Definition at line 63 of file AVRMachineFunctionInfo.h.
Referenced by llvm::analyzeArguments().
The documentation for this class was generated from the following file:
lib/Target/AVR/AVRMachineFunctionInfo.h