LLVM: llvm::mca::Pipeline Class Reference
llvm::mca::Pipeline Class Reference
A pipeline for a specific subtarget.
#include "llvm/MCA/Pipeline.h"
Public Member Functions
Pipeline ()
void appendStage (std::unique_ptr< Stage > S)
Expected< unsigned > run ()
Returns the total number of simulated cycles.
void addEventListener (HWEventListener *Listener)
Detailed Description
A pipeline for a specific subtarget.
It emulates an out-of-order execution of instructions. Instructions are fetched from a MCInst sequence managed by an initial 'Fetch' stage. Instructions are firstly fetched, then dispatched to the schedulers, and then executed.
This class tracks the lifetime of an instruction from the moment where it gets dispatched to the schedulers, to the moment where it finishes executing and register writes are architecturally committed. In particular, it monitors changes in the state of every instruction in flight.
Instructions are executed in a loop of iterations. The number of iterations is defined by the SourceMgr object, which is managed by the initial stage of the instruction pipeline.
The Pipeline entry point is method 'run()' which executes cycles in a loop until there are new instructions to dispatch, and not every instruction has been retired.
Internally, the Pipeline collects statistical information in the form of histograms. For example, it tracks how the dispatch group size changes over time.
Definition at line 52 of file Pipeline.h.
Constructor & Destructor Documentation
Pipeline()
llvm::mca::Pipeline::Pipeline () inline
Definition at line 67 of file Pipeline.h.
References addEventListener(), appendStage(), and run().
Member Function Documentation
addEventListener()
void llvm::mca::Pipeline::addEventListener (HWEventListener * Listener)
Definition at line 24 of file Pipeline.cpp.
References llvm::any_of().
Referenced by Pipeline().
appendStage()
void llvm::mca::Pipeline::appendStage (std::unique_ptr< Stage > S)
Definition at line 75 of file Pipeline.cpp.
References assert(), llvm::dbgs(), LLVM_DEBUG, and llvm::mca::Stage::setNextInSequence().
Referenced by Pipeline().
run()
Expected< unsigned > llvm::mca::Pipeline::run ()
Returns the total number of simulated cycles.
Definition at line 37 of file Pipeline.cpp.
References assert().
Referenced by Pipeline().
The documentation for this class was generated from the following files:
include/llvm/MCA/Pipeline.h
lib/MCA/Pipeline.cpp