LLVM: llvm::LanaiMCExpr Class Reference
llvm::LanaiMCExpr Class Reference
#include "Target/Lanai/MCTargetDesc/LanaiMCExpr.h"
Public Types
enum VariantKind { VK_Lanai_None, VK_Lanai_ABS_HI, VK_Lanai_ABS_LO }
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
VariantKind getKind () const
const MCExpr * getSubExpr () const
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &) const override
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static const LanaiMCExpr * create (VariantKind Kind, const MCExpr *Expr, MCContext &Ctx)
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
Detailed Description
Definition at line 17 of file LanaiMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::LanaiMCExpr::VariantKind
Enumerator
VK_Lanai_None
VK_Lanai_ABS_HI
VK_Lanai_ABS_LO
Definition at line 19 of file LanaiMCExpr.h.
Member Function Documentation
classof()
static bool llvm::LanaiMCExpr::classof (const MCExpr * E) inline static
Definition at line 49 of file LanaiMCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
create()
const LanaiMCExpr * LanaiMCExpr::create (VariantKind Kind, const MCExpr * Expr, MCContext & Ctx) static
Definition at line 17 of file LanaiMCExpr.cpp.
Referenced by llvm::LanaiMCInstLower::LowerSymbolOperand().
evaluateAsRelocatableImpl()
bool LanaiMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 49 of file LanaiMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), llvm::MCValue::get(), llvm::MCValue::getConstant(), getKind(), getSubExpr(), llvm::MCValue::getSymA(), and llvm::MCValue::getSymB().
Referenced by getSubExpr().
findAssociatedFragment()
MCFragment* llvm::LanaiMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 42 of file LanaiMCExpr.h.
References llvm::MCExpr::findAssociatedFragment(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void llvm::LanaiMCExpr::fixELFSymbolsInTLSFixups (MCAssembler &) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 47 of file LanaiMCExpr.h.
getKind()
VariantKind llvm::LanaiMCExpr::getKind () const inline
Definition at line 33 of file LanaiMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), and shouldBeSls().
getSubExpr()
const MCExpr* llvm::LanaiMCExpr::getSubExpr () const inline
Definition at line 36 of file LanaiMCExpr.h.
References evaluateAsRelocatableImpl(), Fixup, printImpl(), and visitUsedExpr().
Referenced by evaluateAsRelocatableImpl(), findAssociatedFragment(), printImpl(), and visitUsedExpr().
printImpl()
void LanaiMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 22 of file LanaiMCExpr.cpp.
References getSubExpr(), llvm_unreachable, llvm::MCExpr::print(), VK_Lanai_ABS_HI, VK_Lanai_ABS_LO, and VK_Lanai_None.
Referenced by getSubExpr().
visitUsedExpr()
void LanaiMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 45 of file LanaiMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
Referenced by getSubExpr().
The documentation for this class was generated from the following files:
lib/Target/Lanai/MCTargetDesc/LanaiMCExpr.h
lib/Target/Lanai/MCTargetDesc/LanaiMCExpr.cpp