LLVM: llvm::ValueAsMetadata Class Reference
llvm::ValueAsMetadata Class Reference
Value wrapper in the Metadata hierarchy.
#include "llvm/IR/Metadata.h"
Public Member Functions
Value * getValue () const
Type * getType () const
LLVMContext & getContext () const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static ValueAsMetadata * get (Value *V)
static ConstantAsMetadata * getConstant (Value *C)
static LocalAsMetadata * getLocal (Value *Local)
static ValueAsMetadata * getIfExists (Value *V)
static ConstantAsMetadata * getConstantIfExists (Value *C)
static LocalAsMetadata * getLocalIfExists (Value *Local)
static void handleDeletion (Value *V)
static void handleRAUW (Value *From, Value *To)
static bool classof (const Metadata *MD)
Protected Member Functions
ValueAsMetadata (unsigned ID, Value *V)
~ValueAsMetadata ()=default
void replaceAllUsesWith (Metadata *MD)
Handle collisions after Value::replaceAllUsesWith().
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Friends
class ReplaceableMetadataImpl
class LLVMContextImpl
Additional Inherited Members
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Value wrapper in the Metadata hierarchy.
This is a custom value handle that allows other metadata to refer to classes in the Value hierarchy.
Because of full uniquing support, each value is only wrapped by a single ValueAsMetadata object, so the lookup maps are far more efficient than those using ValueHandleBase.
Definition at line 339 of file Metadata.h.
Constructor & Destructor Documentation
ValueAsMetadata()
llvm::ValueAsMetadata::ValueAsMetadata (unsigned ID, Value * V) inline protected
Definition at line 351 of file Metadata.h.
References assert().
~ValueAsMetadata()
llvm::ValueAsMetadata::~ValueAsMetadata () protected default
Member Function Documentation
classof()
static bool llvm::ValueAsMetadata::classof (const Metadata * MD) inline static
Definition at line 397 of file Metadata.h.
References llvm::Metadata::getMetadataID().
get()
ValueAsMetadata * ValueAsMetadata::get (Value * V) static
Definition at line 348 of file Metadata.cpp.
References assert(), C, llvm::Value::getContext(), llvm::Value::IsUsedByMD, llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValuesAsMetadata.
Referenced by llvm::formLCSSAForInstructions(), FunctionNumber(), getDbgIntrinsicValueImpl(), llvm::insertDebugValuesForPHIs(), instrumentMaskedLoadOrStore(), IsInterestingCmp(), LLVMValueAsMetadata(), makeBitReverse(), operator<<(), llvm::remapInstruction(), llvm::replaceDbgUsesWithUndef(), RetagMask(), RewriteUsesOfClonedInstructions(), llvm::CGProfilePass::run(), TryToSinkInstruction(), and wrapValueInMetadata().
getConstant()
static ConstantAsMetadata* llvm::ValueAsMetadata::getConstant (Value * C) inline static
Definition at line 361 of file Metadata.h.
References C.
Referenced by llvm::ConstantAsMetadata::get(), and wrapConstantAsMetadata().
getConstantIfExists()
static ConstantAsMetadata* llvm::ValueAsMetadata::getConstantIfExists (Value * C) inline static
Definition at line 371 of file Metadata.h.
Referenced by llvm::ConstantAsMetadata::getIfExists().
getContext()
LLVMContext& llvm::ValueAsMetadata::getContext () const inline
Definition at line 381 of file Metadata.h.
References From, and llvm::Value::getContext().
getIfExists()
ValueAsMetadata * ValueAsMetadata::getIfExists (Value * V) static
Definition at line 367 of file Metadata.cpp.
References assert(), llvm::Value::getContext(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValuesAsMetadata.
getLocal()
static LocalAsMetadata* llvm::ValueAsMetadata::getLocal (Value * Local) inline static
Definition at line 365 of file Metadata.h.
Referenced by llvm::LocalAsMetadata::get().
getLocalIfExists()
static LocalAsMetadata* llvm::ValueAsMetadata::getLocalIfExists (Value * Local) inline static
Definition at line 375 of file Metadata.h.
Referenced by llvm::LocalAsMetadata::getIfExists().
getType()
Type* llvm::ValueAsMetadata::getType () const inline
Definition at line 380 of file Metadata.h.
References llvm::Value::getType().
getValue()
Value* llvm::ValueAsMetadata::getValue () const inline
Definition at line 379 of file Metadata.h.
Referenced by forEachUser(), getOptimizationFlags(), llvm::ConstantAsMetadata::getValue(), handleDeletion(), handleRAUW(), and llvm::ValueEnumerator::print().
handleDeletion()
void ValueAsMetadata::handleDeletion (Value * V) static
Definition at line 372 of file Metadata.cpp.
References assert(), llvm::Type::getContext(), llvm::Value::getType(), getValue(), I, llvm::LLVMContext::pImpl, replaceAllUsesWith(), llvm::SPII::Store, and llvm::LLVMContextImpl::ValuesAsMetadata.
Referenced by llvm::Value::~Value().
handleRAUW()
void ValueAsMetadata::handleRAUW (Value * From, Value * To) static
Definition at line 391 of file Metadata.cpp.
References assert(), C, llvm::ConstantAsMetadata::get(), llvm::Type::getContext(), getLocalFunctionMetadata(), llvm::Value::getType(), getValue(), I, llvm::Value::IsUsedByMD, replaceAllUsesWith(), and llvm::SPII::Store.
Referenced by contains(), and getStartOrEndSlot().
replaceAllUsesWith()
void llvm::ValueAsMetadata::replaceAllUsesWith (Metadata * MD) inline protected
Handle collisions after Value::replaceAllUsesWith().
RAUW isn't supported directly for ValueAsMetadata, but if the wrapped Value gets RAUW'ed and the target already exists, this is used to merge the two metadata nodes.
Definition at line 392 of file Metadata.h.
References llvm::ReplaceableMetadataImpl::replaceAllUsesWith().
Referenced by handleDeletion(), and handleRAUW().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 341 of file Metadata.h.
ReplaceableMetadataImpl
friend class ReplaceableMetadataImpl friend
Definition at line 340 of file Metadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/IR/Metadata.cpp