LLVM: llvm::MCCVLoc Class Reference
llvm::MCCVLoc Class Reference
Instances of this class represent the information from a .cv_loc directive.
#include "llvm/MC/MCCodeView.h"
Public Member Functions
const MCSymbol * getLabel () const
unsigned getFunctionId () const
unsigned getFileNum () const
Get the FileNum of this MCCVLoc.
unsigned getLine () const
Get the Line of this MCCVLoc.
unsigned getColumn () const
Get the Column of this MCCVLoc.
bool isPrologueEnd () const
bool isStmt () const
void setLabel (const MCSymbol *L)
void setFunctionId (unsigned FID)
void setFileNum (unsigned fileNum)
Set the FileNum of this MCCVLoc.
void setLine (unsigned line)
Set the Line of this MCCVLoc.
void setColumn (unsigned column)
Set the Column of this MCCVLoc.
void setPrologueEnd (bool PE)
void setIsStmt (bool IS)
Friends
class CodeViewContext
Detailed Description
Instances of this class represent the information from a .cv_loc directive.
Definition at line 31 of file MCCodeView.h.
Member Function Documentation
getColumn()
unsigned llvm::MCCVLoc::getColumn () const inline
Get the Column of this MCCVLoc.
Definition at line 62 of file MCCodeView.h.
Referenced by llvm::CodeViewContext::emitLineTableForFunction().
getFileNum()
unsigned llvm::MCCVLoc::getFileNum () const inline
Get the FileNum of this MCCVLoc.
Definition at line 56 of file MCCodeView.h.
Referenced by llvm::CodeViewContext::emitLineTableForFunction().
getFunctionId()
unsigned llvm::MCCVLoc::getFunctionId () const inline
Definition at line 53 of file MCCodeView.h.
Referenced by llvm::CodeViewContext::addLineEntry().
getLabel()
const MCSymbol* llvm::MCCVLoc::getLabel () const inline
Definition at line 51 of file MCCodeView.h.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().
getLine()
unsigned llvm::MCCVLoc::getLine () const inline
Get the Line of this MCCVLoc.
Definition at line 59 of file MCCodeView.h.
isPrologueEnd()
bool llvm::MCCVLoc::isPrologueEnd () const inline
Definition at line 64 of file MCCodeView.h.
isStmt()
bool llvm::MCCVLoc::isStmt () const inline
Definition at line 65 of file MCCodeView.h.
setColumn()
void llvm::MCCVLoc::setColumn (unsigned column) inline
Set the Column of this MCCVLoc.
Definition at line 78 of file MCCodeView.h.
References assert().
setFileNum()
void llvm::MCCVLoc::setFileNum (unsigned fileNum) inline
Set the FileNum of this MCCVLoc.
Definition at line 72 of file MCCodeView.h.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().
setFunctionId()
void llvm::MCCVLoc::setFunctionId (unsigned FID) inline
Definition at line 69 of file MCCodeView.h.
setIsStmt()
void llvm::MCCVLoc::setIsStmt (bool IS) inline
Definition at line 84 of file MCCodeView.h.
setLabel()
void llvm::MCCVLoc::setLabel (const MCSymbol * L) inline
Definition at line 67 of file MCCodeView.h.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().
setLine()
void llvm::MCCVLoc::setLine (unsigned line) inline
Set the Line of this MCCVLoc.
Definition at line 75 of file MCCodeView.h.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().
setPrologueEnd()
void llvm::MCCVLoc::setPrologueEnd (bool PE) inline
Definition at line 83 of file MCCodeView.h.
Friends And Related Function Documentation
CodeViewContext
friend class CodeViewContext friend
Definition at line 41 of file MCCodeView.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCCodeView.h