LLVM: llvm::TargetTransformInfoImplBase Class Reference
llvm::TargetTransformInfoImplBase Class Reference
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
#include "llvm/Analysis/TargetTransformInfoImpl.h"
Public Member Functions
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value *> Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
unsigned getMemcpyCost (const Instruction *I)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &)
bool isLegalAddImmediate (int64_t Imm)
bool isLegalICmpImmediate (int64_t Imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2)
bool canMacroFuseCmp ()
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo)
bool shouldFavorPostInc () const
bool shouldFavorBackedgeIndex (const Loop *L) const
bool isLegalMaskedStore (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedLoad (Type *DataType, MaybeAlign Alignment)
bool isLegalNTStore (Type *DataType, Align Alignment)
bool isLegalNTLoad (Type *DataType, Align Alignment)
bool isLegalMaskedScatter (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedGather (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedCompressStore (Type *DataType)
bool isLegalMaskedExpandLoad (Type *DataType)
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace)
bool prefersVectorizedAddressing ()
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool LSRWithInstrQueries ()
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA ()
bool isTypeLegal (Type *Ty)
bool shouldBuildLookupTables ()
bool shouldBuildLookupTablesForConstant (Constant *C)
bool useColdCCForColdCall (Function &F)
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value *> Args, unsigned VF)
bool supportsEfficientVectorElementLoadStore ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization ()
bool enableMaskedInterleavedAccessVectorization ()
bool isFPVectorizationPotentiallyUnsafe ()
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast)
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit)
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
int getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth ()
bool shouldMaximizeVectorBandwidth (bool OptSize) const
unsigned getMinimumVF (unsigned ElemWidth) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader)
unsigned getCacheLineSize () const
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride () const
unsigned getMaxPrefetchIterationsAhead () const
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value *> Args, const Instruction *CxtI=nullptr)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Ty, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction *I)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type *> Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value *> Args, FastMathFlags FMF, unsigned VF)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type *> Tys)
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned, Type *, bool)
unsigned getMinMaxReductionCost (Type *, Type *, bool, bool)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type *> Tys)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type *> &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument *> &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool useReductionIntrinsic (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
Protected Types
typedef TargetTransformInfo TTI
Protected Member Functions
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned)
bool isStridedAccess (const SCEV *Ptr)
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr)
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance)
Protected Attributes
const DataLayout & DL
Detailed Description
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
Definition at line 31 of file TargetTransformInfoImpl.h.
Member Typedef Documentation
TTI
typedef TargetTransformInfo llvm::TargetTransformInfoImplBase::TTI protected
Definition at line 33 of file TargetTransformInfoImpl.h.
Constructor & Destructor Documentation
TargetTransformInfoImplBase() [1/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const DataLayout & DL) inline explicit protected
Definition at line 37 of file TargetTransformInfoImpl.h.
TargetTransformInfoImplBase() [2/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const TargetTransformInfoImplBase & Arg) inline
Definition at line 41 of file TargetTransformInfoImpl.h.
TargetTransformInfoImplBase() [3/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (TargetTransformInfoImplBase && Arg) inline
Definition at line 43 of file TargetTransformInfoImpl.h.
Member Function Documentation
allowsMisalignedMemoryAccesses()
bool llvm::TargetTransformInfoImplBase::allowsMisalignedMemoryAccesses (LLVMContext & Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool * Fast) inline
Definition at line 339 of file TargetTransformInfoImpl.h.
areFunctionArgsABICompatible()
bool llvm::TargetTransformInfoImplBase::areFunctionArgsABICompatible (const Function * Caller, const Function * Callee, SmallPtrSetImpl< Argument *> & Args) const inline
Definition at line 558 of file TargetTransformInfoImpl.h.
References llvm::Function::getFnAttribute().
Referenced by llvm::X86TTIImpl::areFunctionArgsABICompatible().
areInlineCompatible()
bool llvm::TargetTransformInfoImplBase::areInlineCompatible (const Function * Caller, const Function * Callee) const inline
Definition at line 550 of file TargetTransformInfoImpl.h.
References llvm::Function::getFnAttribute().
Referenced by llvm::GCNTTIImpl::getVectorSplitCost().
canMacroFuseCmp()
bool llvm::TargetTransformInfoImplBase::canMacroFuseCmp () inline
Definition at line 245 of file TargetTransformInfoImpl.h.
canSaveCmp()
bool llvm::TargetTransformInfoImplBase::canSaveCmp (Loop * L, BranchInst ** BI, ScalarEvolution * SE, LoopInfo * LI, DominatorTree * DT, AssumptionCache * AC, TargetLibraryInfo * LibInfo) inline
Definition at line 247 of file TargetTransformInfoImpl.h.
collectFlatAddressOperands()
bool llvm::TargetTransformInfoImplBase::collectFlatAddressOperands (SmallVectorImpl< int > & OpIndexes, Intrinsic::ID IID) const inline
Definition at line 163 of file TargetTransformInfoImpl.h.
enableAggressiveInterleaving()
bool llvm::TargetTransformInfoImplBase::enableAggressiveInterleaving (bool LoopHasReductions) inline
Definition at line 326 of file TargetTransformInfoImpl.h.
enableInterleavedAccessVectorization()
bool llvm::TargetTransformInfoImplBase::enableInterleavedAccessVectorization () inline
Definition at line 333 of file TargetTransformInfoImpl.h.
enableMaskedInterleavedAccessVectorization()
bool llvm::TargetTransformInfoImplBase::enableMaskedInterleavedAccessVectorization () inline
Definition at line 335 of file TargetTransformInfoImpl.h.
enableMemCmpExpansion()
TTI::MemCmpExpansionOptions llvm::TargetTransformInfoImplBase::enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const inline
Definition at line 328 of file TargetTransformInfoImpl.h.
getAddressComputationCost()
unsigned llvm::TargetTransformInfoImplBase::getAddressComputationCost (Type * Tp, ScalarEvolution * , const SCEV *) inline
Definition at line 507 of file TargetTransformInfoImpl.h.
getArithmeticInstrCost()
unsigned llvm::TargetTransformInfoImplBase::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value *> Args, const Instruction * CxtI = nullptr) inline
Definition at line 432 of file TargetTransformInfoImpl.h.
getArithmeticReductionCost()
unsigned llvm::TargetTransformInfoImplBase::getArithmeticReductionCost (unsigned , Type * , bool) inline
Definition at line 512 of file TargetTransformInfoImpl.h.
getAtomicMemIntrinsicMaxElementSize()
unsigned llvm::TargetTransformInfoImplBase::getAtomicMemIntrinsicMaxElementSize () const inline
Definition at line 522 of file TargetTransformInfoImpl.h.
getCacheAssociativity()
llvm::Optional<unsigned> llvm::TargetTransformInfoImplBase::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const inline
Definition at line 414 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, LLVM_FALLTHROUGH, and llvm_unreachable.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCacheAssociativity().
getCacheLineSize()
unsigned llvm::TargetTransformInfoImplBase::getCacheLineSize () const inline
Definition at line 402 of file TargetTransformInfoImpl.h.
getCacheSize()
llvm::Optional<unsigned> llvm::TargetTransformInfoImplBase::getCacheSize (TargetTransformInfo::CacheLevel Level) const inline
Definition at line 404 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, LLVM_FALLTHROUGH, and llvm_unreachable.
getCallCost()
unsigned llvm::TargetTransformInfoImplBase::getCallCost (FunctionType * FTy, int NumArgs, const User * U) inline
Definition at line 130 of file TargetTransformInfoImpl.h.
References assert(), llvm::FunctionType::getNumParams(), and llvm::TargetTransformInfo::TCC_Basic.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), and llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost().
getCallInstrCost()
unsigned llvm::TargetTransformInfoImplBase::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type *> Tys) inline
Definition at line 501 of file TargetTransformInfoImpl.h.
getCastInstrCost()
unsigned llvm::TargetTransformInfoImplBase::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, const Instruction * I) inline
Definition at line 447 of file TargetTransformInfoImpl.h.
getCFInstrCost()
unsigned llvm::TargetTransformInfoImplBase::getCFInstrCost (unsigned Opcode) inline
Definition at line 455 of file TargetTransformInfoImpl.h.
getCmpSelInstrCost()
unsigned llvm::TargetTransformInfoImplBase::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, const Instruction * I) inline
Definition at line 457 of file TargetTransformInfoImpl.h.
getConstantStrideStep()
const SCEVConstant* llvm::TargetTransformInfoImplBase::getConstantStrideStep (ScalarEvolution * SE, const SCEV * Ptr) inline protected
Definition at line 681 of file TargetTransformInfoImpl.h.
References llvm::dyn_cast(), llvm::SCEVAddRecExpr::getStepRecurrence(), and isStridedAccess().
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and isConstantStridedAccessLessThan().
getCostOfKeepingLiveOverCall()
unsigned llvm::TargetTransformInfoImplBase::getCostOfKeepingLiveOverCall (ArrayRef< Type *> Tys) inline
Definition at line 516 of file TargetTransformInfoImpl.h.
getDataLayout()
const DataLayout& llvm::TargetTransformInfoImplBase::getDataLayout () const inline
Definition at line 45 of file TargetTransformInfoImpl.h.
References DL.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getEstimatedNumberOfCaseClusters(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::RISCVTTIImpl::getIntImmCost(), and llvm::HexagonTTIImpl::getUserCost().
getEstimatedNumberOfCaseClusters()
unsigned llvm::TargetTransformInfoImplBase::getEstimatedNumberOfCaseClusters (const SwitchInst & SI, unsigned & JTSize, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI) inline
Definition at line 116 of file TargetTransformInfoImpl.h.
References llvm::SwitchInst::getNumCases().
getExtCost()
int llvm::TargetTransformInfoImplBase::getExtCost (const Instruction * I, const Value * Src) inline
Definition at line 126 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost().
getExtractWithExtendCost()
unsigned llvm::TargetTransformInfoImplBase::getExtractWithExtendCost (unsigned Opcode, Type * Dst, VectorType * VecTy, unsigned Index) inline
Definition at line 450 of file TargetTransformInfoImpl.h.
getFlatAddressSpace()
unsigned llvm::TargetTransformInfoImplBase::getFlatAddressSpace () inline
Definition at line 159 of file TargetTransformInfoImpl.h.
getFPOpCost()
unsigned llvm::TargetTransformInfoImplBase::getFPOpCost (Type * Ty) inline
Definition at line 353 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
getGatherScatterOpCost()
unsigned llvm::TargetTransformInfoImplBase::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, Value * Ptr, bool VariableMask, unsigned Alignment) inline
Definition at line 476 of file TargetTransformInfoImpl.h.
Referenced by llvm::HexagonTTIImpl::getGatherScatterOpCost().
getGEPCost()
int llvm::TargetTransformInfoImplBase::getGEPCost (Type * PointeeType, const Value * Ptr, ArrayRef< const Value *> Operands) inline
Definition at line 105 of file TargetTransformInfoImpl.h.
References Size, llvm::ArrayRef< T >::size(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost().
getGISelRematGlobalCost()
unsigned llvm::TargetTransformInfoImplBase::getGISelRematGlobalCost () const inline
Definition at line 615 of file TargetTransformInfoImpl.h.
getInlinerVectorBonusPercent()
int llvm::TargetTransformInfoImplBase::getInlinerVectorBonusPercent () inline
Definition at line 147 of file TargetTransformInfoImpl.h.
getInliningThresholdMultiplier()
unsigned llvm::TargetTransformInfoImplBase::getInliningThresholdMultiplier () inline
Definition at line 145 of file TargetTransformInfoImpl.h.
getInterleavedMemoryOpCost()
unsigned llvm::TargetTransformInfoImplBase::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond = false, bool UseMaskForGaps = false) inline
Definition at line 482 of file TargetTransformInfoImpl.h.
getIntImmCodeSizeCost()
int llvm::TargetTransformInfoImplBase::getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty) inline
Definition at line 355 of file TargetTransformInfoImpl.h.
getIntImmCost()
unsigned llvm::TargetTransformInfoImplBase::getIntImmCost (const APInt & Imm, Type * Ty) inline
Definition at line 360 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
Referenced by llvm::AArch64TTIImpl::AArch64TTIImpl(), llvm::PPCTTIImpl::getIntImmCost(), llvm::ARMTTIImpl::isFPVectorizationPotentiallyUnsafe(), and llvm::PPCTTIImpl::PPCTTIImpl().
getIntImmCostInst()
unsigned llvm::TargetTransformInfoImplBase::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty) inline
Definition at line 362 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostInst().
getIntImmCostIntrin()
unsigned llvm::TargetTransformInfoImplBase::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty) inline
Definition at line 367 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostIntrin().
getIntrinsicInstrCost() [1/2]
unsigned llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Type *> Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed) inline
Definition at line 491 of file TargetTransformInfoImpl.h.
getIntrinsicInstrCost() [2/2]
unsigned llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Value *> Args, FastMathFlags FMF, unsigned VF) inline
Definition at line 496 of file TargetTransformInfoImpl.h.
getLoadStoreVecRegBitWidth()
unsigned llvm::TargetTransformInfoImplBase::getLoadStoreVecRegBitWidth (unsigned AddrSpace) const inline
Definition at line 576 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getPopcntSupport(), and llvm::R600TTIImpl::getTLI().
getLoadVectorFactor()
unsigned llvm::TargetTransformInfoImplBase::getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline
Definition at line 594 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getPopcntSupport().
getMaskedMemoryOpCost()
unsigned llvm::TargetTransformInfoImplBase::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace) inline
Definition at line 471 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), and llvm::HexagonTTIImpl::getMaskedMemoryOpCost().
getMaxInterleaveFactor()
unsigned llvm::TargetTransformInfoImplBase::getMaxInterleaveFactor (unsigned VF) inline
Definition at line 430 of file TargetTransformInfoImpl.h.
getMaxPrefetchIterationsAhead()
unsigned llvm::TargetTransformInfoImplBase::getMaxPrefetchIterationsAhead () const inline
Definition at line 428 of file TargetTransformInfoImpl.h.
getMemcpyCost()
unsigned llvm::TargetTransformInfoImplBase::getMemcpyCost (const Instruction * I) inline
Definition at line 149 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Expensive.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getIntrinsicCost().
getMemcpyLoopLoweringType()
Type* llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType (LLVMContext & Context, Value * Length, unsigned SrcAlign, unsigned DestAlign) const inline
Definition at line 536 of file TargetTransformInfoImpl.h.
References llvm::Type::getInt8Ty().
getMemcpyLoopResidualLoweringType()
void llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type *> & OpsOut, LLVMContext & Context, unsigned RemainingBytes, unsigned SrcAlign, unsigned DestAlign) const inline
Definition at line 541 of file TargetTransformInfoImpl.h.
References llvm::Type::getInt8Ty(), and llvm::SmallVectorTemplateBase< T >::push_back().
getMemoryOpCost()
unsigned llvm::TargetTransformInfoImplBase::getMemoryOpCost (unsigned Opcode, Type * Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction * I) inline
Definition at line 466 of file TargetTransformInfoImpl.h.
getMinimumVF()
unsigned llvm::TargetTransformInfoImplBase::getMinimumVF (unsigned ElemWidth) const inline
Definition at line 393 of file TargetTransformInfoImpl.h.
getMinMaxReductionCost()
unsigned llvm::TargetTransformInfoImplBase::getMinMaxReductionCost (Type * , Type * , bool , bool) inline
Definition at line 514 of file TargetTransformInfoImpl.h.
getMinPrefetchStride()
unsigned llvm::TargetTransformInfoImplBase::getMinPrefetchStride () const inline
Definition at line 427 of file TargetTransformInfoImpl.h.
getMinVectorRegisterBitWidth()
unsigned llvm::TargetTransformInfoImplBase::getMinVectorRegisterBitWidth () inline
Definition at line 389 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getPopcntSupport(), and llvm::R600TTIImpl::getTLI().
getNumberOfParts()
unsigned llvm::TargetTransformInfoImplBase::getNumberOfParts (Type * Tp) inline
Definition at line 505 of file TargetTransformInfoImpl.h.
getNumberOfRegisters()
unsigned llvm::TargetTransformInfoImplBase::getNumberOfRegisters (unsigned ClassID) const inline
Definition at line 372 of file TargetTransformInfoImpl.h.
Referenced by llvm::WebAssemblyTTIImpl::getNumberOfRegisters(), llvm::GCNTTIImpl::getPopcntSupport(), and llvm::R600TTIImpl::getTLI().
getOperandsScalarizationOverhead()
unsigned llvm::TargetTransformInfoImplBase::getOperandsScalarizationOverhead (ArrayRef< const Value *> Args, unsigned VF) inline
Definition at line 321 of file TargetTransformInfoImpl.h.
getOperationCost()
unsigned llvm::TargetTransformInfoImplBase::getOperationCost (unsigned Opcode, Type * Ty, Type * OpTy) inline
Definition at line 47 of file TargetTransformInfoImpl.h.
References assert(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::DataLayout::isLegalInteger(), llvm::Type::isPointerTy(), llvm_unreachable, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Expensive, and llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperationCost(), and llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost().
getOrCreateResultFromMemIntrinsic()
Value* llvm::TargetTransformInfoImplBase::getOrCreateResultFromMemIntrinsic (IntrinsicInst * Inst, Type * ExpectedType) inline
Definition at line 531 of file TargetTransformInfoImpl.h.
getPopcntSupport()
TTI::PopcntSupportKind llvm::TargetTransformInfoImplBase::getPopcntSupport (unsigned IntTyWidthInBit) inline
Definition at line 345 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::PSK_Software.
getPrefetchDistance()
unsigned llvm::TargetTransformInfoImplBase::getPrefetchDistance () const inline
Definition at line 426 of file TargetTransformInfoImpl.h.
getRegisterBitWidth()
unsigned llvm::TargetTransformInfoImplBase::getRegisterBitWidth (bool Vector) const inline
Definition at line 387 of file TargetTransformInfoImpl.h.
getRegisterClassForType()
unsigned llvm::TargetTransformInfoImplBase::getRegisterClassForType (bool Vector, Type * Ty = nullptr) const inline
Definition at line 374 of file TargetTransformInfoImpl.h.
getRegisterClassName()
const char* llvm::TargetTransformInfoImplBase::getRegisterClassName (unsigned ClassID) const inline
Definition at line 378 of file TargetTransformInfoImpl.h.
getScalarizationOverhead()
unsigned llvm::TargetTransformInfoImplBase::getScalarizationOverhead (Type * Ty, bool Insert, bool Extract) inline
Definition at line 317 of file TargetTransformInfoImpl.h.
getScalingFactorCost()
int llvm::TargetTransformInfoImplBase::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) inline
Definition at line 293 of file TargetTransformInfoImpl.h.
References isLegalAddressingMode().
getShuffleCost()
unsigned llvm::TargetTransformInfoImplBase::getShuffleCost (TTI::ShuffleKind Kind, Type * Ty, int Index, Type * SubTp) inline
Definition at line 442 of file TargetTransformInfoImpl.h.
getStoreVectorFactor()
unsigned llvm::TargetTransformInfoImplBase::getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline
Definition at line 600 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getPopcntSupport().
getTgtMemIntrinsic()
bool llvm::TargetTransformInfoImplBase::getTgtMemIntrinsic (IntrinsicInst * Inst, MemIntrinsicInfo & Info) inline
Definition at line 518 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getPopcntSupport().
getUnrollingPreferences()
void llvm::TargetTransformInfoImplBase::getUnrollingPreferences (Loop * , ScalarEvolution & , TTI::UnrollingPreferences &) inline
Definition at line 223 of file TargetTransformInfoImpl.h.
getVectorInstrCost()
unsigned llvm::TargetTransformInfoImplBase::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index) inline
Definition at line 462 of file TargetTransformInfoImpl.h.
hasBranchDivergence()
bool llvm::TargetTransformInfoImplBase::hasBranchDivergence () inline
Definition at line 153 of file TargetTransformInfoImpl.h.
hasDivRemOp()
bool llvm::TargetTransformInfoImplBase::hasDivRemOp (Type * DataType, bool IsSigned) inline
Definition at line 287 of file TargetTransformInfoImpl.h.
hasVolatileVariant()
bool llvm::TargetTransformInfoImplBase::hasVolatileVariant (Instruction * I, unsigned AddrSpace) inline
Definition at line 289 of file TargetTransformInfoImpl.h.
haveFastSqrt()
bool llvm::TargetTransformInfoImplBase::haveFastSqrt (Type * Ty) inline
Definition at line 349 of file TargetTransformInfoImpl.h.
isAlwaysUniform()
bool llvm::TargetTransformInfoImplBase::isAlwaysUniform (const Value * V) inline
Definition at line 157 of file TargetTransformInfoImpl.h.
isConstantStridedAccessLessThan()
bool llvm::TargetTransformInfoImplBase::isConstantStridedAccessLessThan (ScalarEvolution * SE, const SCEV * Ptr, int64_t MergeDistance) inline protected
Definition at line 689 of file TargetTransformInfoImpl.h.
References llvm::SCEVConstant::getAPInt(), llvm::APInt::getBitWidth(), getConstantStrideStep(), and llvm::APInt::getSExtValue().
Referenced by llvm::AArch64TTIImpl::getAddressComputationCost(), and llvm::ARMTTIImpl::getAddressComputationCost().
isFCmpOrdCheaperThanFCmpZero()
bool llvm::TargetTransformInfoImplBase::isFCmpOrdCheaperThanFCmpZero (Type * Ty) inline
Definition at line 351 of file TargetTransformInfoImpl.h.
isFPVectorizationPotentiallyUnsafe()
bool llvm::TargetTransformInfoImplBase::isFPVectorizationPotentiallyUnsafe () inline
Definition at line 337 of file TargetTransformInfoImpl.h.
isHardwareLoopProfitable()
bool llvm::TargetTransformInfoImplBase::isHardwareLoopProfitable (Loop * L, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * LibInfo, HardwareLoopInfo & HWLoopInfo) inline
Definition at line 209 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isHardwareLoopProfitable().
isIndexedLoadLegal()
bool llvm::TargetTransformInfoImplBase::isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type * Ty, const DataLayout & DL) const inline
Definition at line 566 of file TargetTransformInfoImpl.h.
isIndexedStoreLegal()
bool llvm::TargetTransformInfoImplBase::isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type * Ty, const DataLayout & DL) const inline
Definition at line 571 of file TargetTransformInfoImpl.h.
isLegalAddImmediate()
bool llvm::TargetTransformInfoImplBase::isLegalAddImmediate (int64_t Imm) inline
Definition at line 226 of file TargetTransformInfoImpl.h.
isLegalAddressingMode()
bool llvm::TargetTransformInfoImplBase::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction * I = nullptr) inline
Definition at line 230 of file TargetTransformInfoImpl.h.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), and getScalingFactorCost().
isLegalICmpImmediate()
bool llvm::TargetTransformInfoImplBase::isLegalICmpImmediate (int64_t Imm) inline
Definition at line 228 of file TargetTransformInfoImpl.h.
isLegalMaskedCompressStore()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedCompressStore (Type * DataType) inline
Definition at line 283 of file TargetTransformInfoImpl.h.
isLegalMaskedExpandLoad()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedExpandLoad (Type * DataType) inline
Definition at line 285 of file TargetTransformInfoImpl.h.
isLegalMaskedGather()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedGather (Type * DataType, MaybeAlign Alignment) inline
Definition at line 279 of file TargetTransformInfoImpl.h.
isLegalMaskedLoad()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedLoad (Type * DataType, MaybeAlign Alignment) inline
Definition at line 259 of file TargetTransformInfoImpl.h.
isLegalMaskedScatter()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedScatter (Type * DataType, MaybeAlign Alignment) inline
Definition at line 275 of file TargetTransformInfoImpl.h.
isLegalMaskedStore()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedStore (Type * DataType, MaybeAlign Alignment) inline
Definition at line 257 of file TargetTransformInfoImpl.h.
isLegalNTLoad()
bool llvm::TargetTransformInfoImplBase::isLegalNTLoad (Type * DataType, Align Alignment) inline
Definition at line 268 of file TargetTransformInfoImpl.h.
References llvm::DataLayout::getTypeStoreSize(), and llvm::isPowerOf2_32().
isLegalNTStore()
bool llvm::TargetTransformInfoImplBase::isLegalNTStore (Type * DataType, Align Alignment) inline
Definition at line 261 of file TargetTransformInfoImpl.h.
References llvm::DataLayout::getTypeStoreSize(), and llvm::isPowerOf2_32().
isLegalToVectorizeLoad()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoad (LoadInst * LI) const inline
Definition at line 578 of file TargetTransformInfoImpl.h.
isLegalToVectorizeLoadChain()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const inline
Definition at line 582 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getPopcntSupport(), and llvm::R600TTIImpl::getTLI().
isLegalToVectorizeStore()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStore (StoreInst * SI) const inline
Definition at line 580 of file TargetTransformInfoImpl.h.
isLegalToVectorizeStoreChain()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const inline
Definition at line 588 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getPopcntSupport(), and llvm::R600TTIImpl::getTLI().
isLoweredToCall()
bool llvm::TargetTransformInfoImplBase::isLoweredToCall (const Function * F) inline
Definition at line 173 of file TargetTransformInfoImpl.h.
References assert(), llvm::Value::getName(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), llvm::Function::isIntrinsic(), and Name.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionLatency(), llvm::SystemZTTIImpl::getUnrollingPreferences(), and llvm::ARMTTIImpl::isLoweredToCall().
isLSRCostLess()
bool llvm::TargetTransformInfoImplBase::isLSRCostLess (TTI::LSRCost & C1, TTI::LSRCost & C2) inline
Definition at line 238 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isLSRCostLess().
isProfitableToHoist()
bool llvm::TargetTransformInfoImplBase::isProfitableToHoist (Instruction * I) inline
Definition at line 306 of file TargetTransformInfoImpl.h.
isSourceOfDivergence()
bool llvm::TargetTransformInfoImplBase::isSourceOfDivergence (const Value * V) inline
Definition at line 155 of file TargetTransformInfoImpl.h.
isStridedAccess()
bool llvm::TargetTransformInfoImplBase::isStridedAccess (const SCEV * Ptr) inline protected
Definition at line 677 of file TargetTransformInfoImpl.h.
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and getConstantStrideStep().
isTruncateFree()
bool llvm::TargetTransformInfoImplBase::isTruncateFree (Type * Ty1, Type * Ty2) inline
Definition at line 304 of file TargetTransformInfoImpl.h.
isTypeLegal()
bool llvm::TargetTransformInfoImplBase::isTypeLegal (Type * Ty) inline
Definition at line 310 of file TargetTransformInfoImpl.h.
LSRWithInstrQueries()
bool llvm::TargetTransformInfoImplBase::LSRWithInstrQueries () inline
Definition at line 302 of file TargetTransformInfoImpl.h.
minRequiredElementSize()
unsigned llvm::TargetTransformInfoImplBase::minRequiredElementSize (const Value * Val, bool & isSigned) inline protected
Definition at line 622 of file TargetTransformInfoImpl.h.
References llvm::numbers::e, llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and llvm::max().
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost().
preferPredicateOverEpilogue()
bool llvm::TargetTransformInfoImplBase::preferPredicateOverEpilogue (Loop * L, LoopInfo * LI, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * TLI, DominatorTree * DT, const LoopAccessInfo * LAI) const inline
Definition at line 216 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::preferPredicateOverEpilogue().
prefersVectorizedAddressing()
bool llvm::TargetTransformInfoImplBase::prefersVectorizedAddressing () inline
Definition at line 291 of file TargetTransformInfoImpl.h.
rewriteIntrinsicWithAddressSpace()
bool llvm::TargetTransformInfoImplBase::rewriteIntrinsicWithAddressSpace (IntrinsicInst * II, Value * OldV, Value * NewV) const inline
Definition at line 168 of file TargetTransformInfoImpl.h.
shouldBuildLookupTables()
bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTables () inline
Definition at line 312 of file TargetTransformInfoImpl.h.
shouldBuildLookupTablesForConstant()
bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTablesForConstant (Constant * C) inline
Definition at line 313 of file TargetTransformInfoImpl.h.
shouldConsiderAddressTypePromotion()
bool llvm::TargetTransformInfoImplBase::shouldConsiderAddressTypePromotion (const Instruction & I, bool & AllowPromotionWithoutCommonHeader) inline
Definition at line 396 of file TargetTransformInfoImpl.h.
shouldExpandReduction()
bool llvm::TargetTransformInfoImplBase::shouldExpandReduction (const IntrinsicInst * II) const inline
Definition at line 611 of file TargetTransformInfoImpl.h.
shouldFavorBackedgeIndex()
bool llvm::TargetTransformInfoImplBase::shouldFavorBackedgeIndex (const Loop * L) const inline
Definition at line 255 of file TargetTransformInfoImpl.h.
shouldFavorPostInc()
bool llvm::TargetTransformInfoImplBase::shouldFavorPostInc () const inline
Definition at line 253 of file TargetTransformInfoImpl.h.
shouldMaximizeVectorBandwidth()
bool llvm::TargetTransformInfoImplBase::shouldMaximizeVectorBandwidth (bool OptSize) const inline
Definition at line 391 of file TargetTransformInfoImpl.h.
supportsEfficientVectorElementLoadStore()
bool llvm::TargetTransformInfoImplBase::supportsEfficientVectorElementLoadStore () inline
Definition at line 324 of file TargetTransformInfoImpl.h.
useAA()
bool llvm::TargetTransformInfoImplBase::useAA () inline
Definition at line 308 of file TargetTransformInfoImpl.h.
useColdCCForColdCall()
bool llvm::TargetTransformInfoImplBase::useColdCCForColdCall (Function & F) inline
Definition at line 315 of file TargetTransformInfoImpl.h.
useReductionIntrinsic()
bool llvm::TargetTransformInfoImplBase::useReductionIntrinsic (unsigned Opcode, Type * Ty, TTI::ReductionFlags Flags) const inline
Definition at line 606 of file TargetTransformInfoImpl.h.
Member Data Documentation
DL
const DataLayout& llvm::TargetTransformInfoImplBase::DL protected
Definition at line 35 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::BasicTTIImplBase(), llvm::NVPTXTTIImpl::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::AArch64TTIImpl::getArithmeticReductionCost(), llvm::GCNTTIImpl::getArithmeticReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticReductionCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::HexagonTTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::HexagonTTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost(), getDataLayout(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getEstimatedNumberOfCaseClusters(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getExtCost(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getFPOpCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::PPCTTIImpl::getInterleavedMemoryOpCost(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::RISCVTTIImpl::getIntImmCost(), llvm::HexagonTTIImpl::getIntrinsicInstrCost(), llvm::PPCTTIImpl::getIntrinsicInstrCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMemoryOpCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::GCNTTIImpl::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getNumberOfParts(), llvm::AArch64TTIImpl::getPopcntSupport(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getScalingFactorCost(), llvm::PPCTTIImpl::getShuffleCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getShuffleCost(), llvm::GCNTTIImpl::getShuffleCost(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::PPCTTIImpl::getUserCost(), llvm::HexagonTTIImpl::getUserCost(), llvm::X86TTIImpl::getUserCost(), llvm::AArch64TTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::GCNTTIImpl::getVectorInstrCost(), llvm::R600TTIImpl::getVectorInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getVectorInstrCost(), llvm::SystemZTTIImpl::hasDivRemOp(), llvm::X86TTIImpl::hasDivRemOp(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::haveFastSqrt(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isLegalAddressingMode(), llvm::X86TTIImpl::isLegalNTLoad(), llvm::X86TTIImpl::isLegalNTStore(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isTypeLegal(), llvm::ARMTTIImpl::preferPredicateOverEpilogue(), and llvm::PPCTTIImpl::vectorCostAdjustment().
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetTransformInfoImpl.h