LLVM: llvm::raw_ostream Class Reference
llvm::raw_ostream Class Reference abstract
This class implements an extremely fast bulk output stream that can only output to a stream.
#include "llvm/Support/raw_ostream.h"
Public Types
enum Colors {
Colors::BLACK = 0, Colors::RED, Colors::GREEN, Colors::YELLOW,
Colors::BLUE, Colors::MAGENTA, Colors::CYAN, Colors::WHITE,
Colors::SAVEDCOLOR, Colors::RESET
}
using uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Public Member Functions
raw_ostream (bool unbuffered=false)
raw_ostream (const raw_ostream &)=delete
void operator= (const raw_ostream &)=delete
virtual ~raw_ostream ()
uint64_t tell () const
tell - Return the current offset with the file.
void SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
void SetBufferSize (size_t Size)
Set the stream to be buffered, using the specified buffer size.
size_t GetBufferSize () const
void SetUnbuffered ()
Set the stream to be unbuffered.
size_t GetNumBytesInBuffer () const
void flush ()
raw_ostream & operator<< (char C)
raw_ostream & operator<< (unsigned char C)
raw_ostream & operator<< (signed char C)
raw_ostream & operator<< (StringRef Str)
raw_ostream & operator<< (const char *Str)
raw_ostream & operator<< (const std::string &Str)
raw_ostream & operator<< (const SmallVectorImpl< char > &Str)
raw_ostream & operator<< (unsigned long N)
raw_ostream & operator<< (long N)
raw_ostream & operator<< (unsigned long long N)
raw_ostream & operator<< (long long N)
raw_ostream & operator<< (const void *P)
raw_ostream & operator<< (unsigned int N)
raw_ostream & operator<< (int N)
raw_ostream & operator<< (double N)
raw_ostream & write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
raw_ostream & operator<< (Colors C)
raw_ostream & write_uuid (const uuid_t UUID)
raw_ostream & write_escaped (StringRef Str, bool UseHexEscapes=false)
Output Str, turning '\', '', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
raw_ostream & write (unsigned char C)
raw_ostream & write (const char *Ptr, size_t Size)
raw_ostream & operator<< (const format_object_base &Fmt)
raw_ostream & operator<< (const FormattedString &)
raw_ostream & operator<< (const FormattedNumber &)
raw_ostream & operator<< (const formatv_object_base &)
raw_ostream & operator<< (const FormattedBytes &)
raw_ostream & indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
raw_ostream & write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
virtual raw_ostream & changeColor (enum Colors Color, bool Bold=false, bool BG=false)
Changes the foreground color of text that will be output from this point forward.
virtual raw_ostream & resetColor ()
Resets the colors to terminal defaults.
virtual raw_ostream & reverseColor ()
Reverses the foreground and background colors.
virtual bool is_displayed () const
This function determines if this stream is connected to a "tty" or "console" window.
virtual bool has_colors () const
This function determines if this stream is displayed and supports colors.
virtual void enable_colors (bool)
Static Public Attributes
static const Colors BLACK = Colors::BLACK
static const Colors RED = Colors::RED
static const Colors GREEN = Colors::GREEN
static const Colors YELLOW = Colors::YELLOW
static const Colors BLUE = Colors::BLUE
static const Colors MAGENTA = Colors::MAGENTA
static const Colors CYAN = Colors::CYAN
static const Colors WHITE = Colors::WHITE
static const Colors SAVEDCOLOR = Colors::SAVEDCOLOR
static const Colors RESET = Colors::RESET
Protected Member Functions
void SetBuffer (char *BufferStart, size_t Size)
Use the provided buffer as the raw_ostream buffer.
virtual size_t preferred_buffer_size () const
Return an efficient buffer size for the underlying output mechanism.
const char * getBufferStart () const
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Detailed Description
This class implements an extremely fast bulk output stream that can only output to a stream.
It does not support seeking, reopening, rewinding, line buffered disciplines etc. It is a simple buffer that outputs a chunk at a time.
Definition at line 46 of file raw_ostream.h.
Member Typedef Documentation
uuid_t
using llvm::raw_ostream::uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Definition at line 235 of file raw_ostream.h.
Member Enumeration Documentation
Colors
enum llvm::raw_ostream::Colors strong
Enumerator
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
SAVEDCOLOR
RESET
Definition at line 76 of file raw_ostream.h.
Constructor & Destructor Documentation
raw_ostream() [1/2]
llvm::raw_ostream::raw_ostream (bool unbuffered = false) inline explicit
Definition at line 100 of file raw_ostream.h.
raw_ostream() [2/2]
llvm::raw_ostream::raw_ostream (const raw_ostream &) delete
~raw_ostream()
raw_ostream::~raw_ostream () virtual
Definition at line 79 of file raw_ostream.cpp.
References assert().
Member Function Documentation
changeColor()
virtual raw_ostream& llvm::raw_ostream::changeColor (enum Colors Color, bool Bold = false, bool BG = false) inline virtual
Changes the foreground color of text that will be output from this point forward.
Parameters
Color ANSI color to use, the special SAVEDCOLOR can be used to change only the bold attribute, and keep colors untouched
Bold bold/brighter text, default false
BG if true change the background, default: change foreground
Returns
itself so it can be used within << invocations
Reimplemented in llvm::raw_fd_ostream, and llvm::formatted_raw_ostream.
Definition at line 273 of file raw_ostream.h.
Referenced by llvm::WithColor::changeColor(), llvm::formatted_raw_ostream::changeColor(), operator<<(), and llvm::WithColor::WithColor().
enable_colors()
virtual void llvm::raw_ostream::enable_colors (bool) inline virtual
Reimplemented in llvm::raw_fd_ostream.
Definition at line 299 of file raw_ostream.h.
References Size.
flush()
void llvm::raw_ostream::flush () inline
Definition at line 155 of file raw_ostream.h.
Referenced by llvm::raw_fd_ostream::changeColor(), llvm::raw_fd_ostream::close(), computeMemberData(), computeStringTable(), llvm::LTOCodeGenerator::DiagnosticHandler(), llvm::AsmPrinter::doFinalization(), llvm::VPlan::dump(), llvm::pdb::PDBSymbol::dumpChildStats(), llvm::pdb::PDBSymbol::dumpProperties(), emitComments(), EmitDebugSectionImpl(), llvm::emitLinkerFlagsForGlobalCOFF(), fail(), llvm::MCJIT::generateCodeForModule(), llvm::object::ArchiveMemberHeader::getAccessMode(), llvm::Attribute::getAsString(), getBlockName(), getDebugLocString(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), getFilename(), llvm::object::ArchiveMemberHeader::getGID(), llvm::object::ArchiveMemberHeader::getLastModified(), llvm::object::ArchiveMemberHeader::getName(), llvm::LazyCallGraph::SCC::getName(), llvm::LazyCallGraph::RefSCC::getName(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), getShuffleComment(), llvm::object::ArchiveMemberHeader::getSize(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), llvm::object::ArchiveMemberHeader::getUID(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsSameAsFreshTree(), llvm::isThumbFunc(), LLVMGetDiagInfoDescription(), LLVMGetSymbolAddress(), LLVMGetSymbolName(), LLVMMoveToContainingSection(), LLVMParseIRInContext(), LLVMPrintModuleToString(), LLVMPrintTypeToString(), LLVMPrintValueToString(), LLVMTargetMachineEmit(), LLVMTargetMachineEmitToFile(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::map(), llvm::operator<<(), llvm::DiagnosticInfoUnsupported::print(), PrintCurStackTrace(), llvm::opt::OptTable::PrintHelp(), llvm::AMDGPUInstPrinter::printInst(), llvm::R600InstPrinter::printInst(), llvm::PrintStatistics(), llvm::PrintStatisticsJSON(), llvm::RuntimeDyldELF::processRelocationRef(), reportError(), ReportError(), reportOpenError(), rescheduleLexographically(), llvm::raw_fd_ostream::resetColor(), llvm::raw_fd_ostream::reverseColor(), llvm::raw_fd_ostream::seek(), setFastFlags(), llvm::setProfMetadata(), llvm::raw_sha1_ostream::sha1(), llvm::formatv_object_base::str(), llvm::AMDGPU::IsaInfo::streamIsaVersion(), llvm::sys::StrError(), llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty(), llvm::writeArchive(), writeLimits(), writeToResolutionFile(), llvm::circular_raw_ostream::~circular_raw_ostream(), llvm::gsym::FileWriter::~FileWriter(), llvm::formatted_raw_ostream::~formatted_raw_ostream(), llvm::raw_fd_ostream::~raw_fd_ostream(), llvm::raw_null_ostream::~raw_null_ostream(), llvm::raw_os_ostream::~raw_os_ostream(), and llvm::raw_string_ostream::~raw_string_ostream().
GetBufferSize()
size_t llvm::raw_ostream::GetBufferSize () const inline
Definition at line 129 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::is_displayed().
getBufferStart()
const char* llvm::raw_ostream::getBufferStart () const inline protected
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Definition at line 338 of file raw_ostream.h.
References Mode.
Referenced by llvm::orc::DumpObjects::operator()(), and llvm::formatted_raw_ostream::PadToColumn().
GetNumBytesInBuffer()
size_t llvm::raw_ostream::GetNumBytesInBuffer () const inline
Definition at line 147 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::PadToColumn(), and SetBuffered().
has_colors()
virtual bool llvm::raw_ostream::has_colors () const inline virtual
This function determines if this stream is displayed and supports colors.
Reimplemented in llvm::raw_fd_ostream.
Definition at line 295 of file raw_ostream.h.
Referenced by llvm::WithColor::colorsEnabled().
indent()
raw_ostream & raw_ostream::indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
Definition at line 496 of file raw_ostream.cpp.
Referenced by llvm::IndexedReference::computeRefCost(), llvm::pdb::IPDBSourceFile::dump(), llvm::dwarf::CFIProgram::dump(), llvm::LexicalScope::dump(), llvm::DWARFDie::dump(), dumpAttribute(), llvm::DWARFLocationTable::dumpLocationList(), llvm::RGPassManager::dumpPassStructure(), llvm::LPPassManager::dumpPassStructure(), llvm::Pass::dumpPassStructure(), llvm::legacy::FunctionPassManagerImpl::dumpPassStructure(), llvm::FPPassManager::dumpPassStructure(), dumpRanges(), llvm::DWARFDebugLoc::dumpRawEntry(), llvm::DWARFDebugLoclists::dumpRawEntry(), llvm::pdb::dumpSymbolField(), llvm::pdb::dumpSymbolIdField(), llvm::StringMatcher::Emit(), emitBasicBlockLoopComments(), llvm::detail::PadAdapter< T >::format(), llvm::CacheCost::getCacheCost(), llvm::IndexedReference::hasSpacialReuse(), llvm::slpvectorizer::BoUpSLP::isDeleted(), llvm::gsym::operator<<(), operator<<(), llvm::operator<<(), llvm::formatted_raw_ostream::PadToColumn(), llvm::DWARFDebugLine::LineTable::parse(), llvm::WebAssemblyException::print(), llvm::MemoryDepChecker::Dependence::print(), llvm::SCEVEqualPredicate::print(), llvm::sampleprof::FunctionSamples::print(), llvm::SCEVWrapPredicate::print(), llvm::RegionBase< RegionTraits< Function > >::print(), llvm::RuntimePointerChecking::print(), llvm::LoopBase< BasicBlock, Loop >::print(), llvm::LoopAccessInfo::print(), llvm::LoopAccessLegacyAnalysis::print(), llvm::MachineBasicBlock::print(), llvm::slpvectorizer::BoUpSLP::VLOperands::print(), llvm::PredicatedScalarEvolution::print(), llvm::RuntimePointerChecking::printChecks(), PrintChildLoopComment(), llvm::PrintDomTree(), llvm::cl::generic_parser_base::printGenericOptionDiff(), PrintHelpOptionList(), llvm::cl::Option::printHelpStr(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::cl::basic_parser_impl::printOptionName(), PrintParentLoopComment(), llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster(), llvm::TargetRegistry::printRegisteredTargetsForVersion(), printWithSpacePadding(), llvm::LoopAccessInfoPrinterPass::run(), sortSubCommands(), and llvm::TimerGroup::~TimerGroup().
is_displayed()
virtual bool llvm::raw_ostream::is_displayed () const inline virtual
This function determines if this stream is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Reimplemented in llvm::raw_fd_ostream, llvm::formatted_raw_ostream, and llvm::circular_raw_ostream.
Definition at line 292 of file raw_ostream.h.
Referenced by llvm::CheckBitcodeOutputToConsole(), llvm::circular_raw_ostream::is_displayed(), and llvm::formatted_raw_ostream::is_displayed().
operator<<() [1/21]
raw_ostream& llvm::raw_ostream::operator<< (char C) inline
Definition at line 160 of file raw_ostream.h.
References C, and write().
Referenced by operator<<().
operator<<() [2/21]
raw_ostream& llvm::raw_ostream::operator<< (unsigned char C) inline
Definition at line 167 of file raw_ostream.h.
References C, and write().
operator<<() [3/21]
raw_ostream& llvm::raw_ostream::operator<< (signed char C) inline
Definition at line 174 of file raw_ostream.h.
References C, and write().
operator<<() [4/21]
raw_ostream& llvm::raw_ostream::operator<< (StringRef Str) inline
Definition at line 181 of file raw_ostream.h.
References llvm::StringRef::data(), Size, llvm::StringRef::size(), and write().
operator<<() [5/21]
raw_ostream& llvm::raw_ostream::operator<< (const char * Str) inline
Definition at line 196 of file raw_ostream.h.
References llvm::sys::operator<<().
operator<<() [6/21]
raw_ostream& llvm::raw_ostream::operator<< (const std::string & Str) inline
Definition at line 203 of file raw_ostream.h.
References write().
operator<<() [7/21]
raw_ostream& llvm::raw_ostream::operator<< (const SmallVectorImpl< char > & Str) inline
Definition at line 208 of file raw_ostream.h.
References N, llvm::sys::operator<<(), P, and write().
operator<<() [8/21]
raw_ostream & raw_ostream::operator<< (unsigned long N)
Definition at line 122 of file raw_ostream.cpp.
References llvm::Integer, and llvm::write_integer().
operator<<() [9/21]
raw_ostream & raw_ostream::operator<< (long N)
Definition at line 127 of file raw_ostream.cpp.
References llvm::Integer, and llvm::write_integer().
operator<<() [10/21]
raw_ostream & raw_ostream::operator<< (unsigned long long N)
Definition at line 132 of file raw_ostream.cpp.
References llvm::Integer, and llvm::write_integer().
operator<<() [11/21]
raw_ostream & raw_ostream::operator<< (long long N)
Definition at line 137 of file raw_ostream.cpp.
References llvm::Integer, and llvm::write_integer().
operator<<() [12/21]
raw_ostream & raw_ostream::operator<< (const void * P)
Definition at line 205 of file raw_ostream.cpp.
References llvm::PrefixLower, and llvm::write_hex().
operator<<() [13/21]
raw_ostream& llvm::raw_ostream::operator<< (unsigned int N) inline
Definition at line 218 of file raw_ostream.h.
References N.
operator<<() [14/21]
raw_ostream& llvm::raw_ostream::operator<< (int N) inline
Definition at line 222 of file raw_ostream.h.
References C, N, llvm::sys::operator<<(), and llvm::write_hex().
operator<<() [15/21]
raw_ostream & raw_ostream::operator<< (double N)
Definition at line 210 of file raw_ostream.cpp.
References assert(), llvm::Exponent, and llvm::write_double().
operator<<() [16/21]
raw_ostream & raw_ostream::operator<< (Colors C)
Definition at line 147 of file raw_ostream.cpp.
References changeColor(), RESET, and resetColor().
operator<<() [17/21]
raw_ostream & raw_ostream::operator<< (const format_object_base & Fmt)
Definition at line 305 of file raw_ostream.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::format_object_base::print(), llvm::SmallVectorImpl< T >::resize(), and write().
operator<<() [18/21]
raw_ostream & raw_ostream::operator<< (const FormattedString & FS)
Definition at line 351 of file raw_ostream.cpp.
References indent(), llvm::FormattedString::JustifyCenter, llvm::FormattedString::JustifyLeft, llvm::FormattedString::JustifyNone, llvm::FormattedString::JustifyRight, llvm_unreachable, operator<<(), and llvm::StringRef::size().
operator<<() [19/21]
raw_ostream & raw_ostream::operator<< (const FormattedNumber & FN)
Definition at line 379 of file raw_ostream.cpp.
References indent(), llvm::Integer, llvm::Lower, llvm::PrefixLower, llvm::PrefixUpper, llvm::SmallVectorBase::size(), llvm::Upper, llvm::write_hex(), and llvm::write_integer().
operator<<() [20/21]
raw_ostream & raw_ostream::operator<< (const formatv_object_base & Obj)
Definition at line 345 of file raw_ostream.cpp.
References llvm::formatv_object_base::format().
operator<<() [21/21]
raw_ostream & raw_ostream::operator<< (const FormattedBytes & FB)
Definition at line 402 of file raw_ostream.cpp.
References llvm::alignTo(), assert(), llvm::ArrayRef< T >::empty(), llvm::Optional< T >::getValue(), llvm::Optional< T >::hasValue(), I, indent(), llvm::isPrint(), llvm::Log2_64_Ceil(), llvm::Lower, Size, llvm::Upper, and llvm::write_hex().
operator=()
void llvm::raw_ostream::operator= (const raw_ostream &) delete
preferred_buffer_size()
size_t raw_ostream::preferred_buffer_size () const protected virtual
Return an efficient buffer size for the underlying output mechanism.
Definition at line 89 of file raw_ostream.cpp.
Referenced by llvm::raw_fd_ostream::seek(), and SetBuffered().
resetColor()
virtual raw_ostream& llvm::raw_ostream::resetColor () inline virtual
Resets the colors to terminal defaults.
Call this when you are done outputting colored text, or before program exit.
Reimplemented in llvm::raw_fd_ostream, and llvm::formatted_raw_ostream.
Definition at line 284 of file raw_ostream.h.
Referenced by operator<<(), llvm::WithColor::resetColor(), and llvm::formatted_raw_ostream::resetColor().
reverseColor()
virtual raw_ostream& llvm::raw_ostream::reverseColor () inline virtual
Reverses the foreground and background colors.
Reimplemented in llvm::raw_fd_ostream, and llvm::formatted_raw_ostream.
Definition at line 287 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::reverseColor().
SetBuffer()
void llvm::raw_ostream::SetBuffer (char * BufferStart, size_t Size) inline protected
Use the provided buffer as the raw_ostream buffer.
This is intended for use only by subclasses which can arrange for the output to go directly into the desired output buffer, instead of being copied on each flush.
Definition at line 329 of file raw_ostream.h.
SetBuffered()
void raw_ostream::SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
Definition at line 94 of file raw_ostream.cpp.
References assert(), GetNumBytesInBuffer(), Mode, preferred_buffer_size(), SetBufferSize(), SetUnbuffered(), and Size.
Referenced by write().
SetBufferSize()
void llvm::raw_ostream::SetBufferSize (size_t Size) inline
Set the stream to be buffered, using the specified buffer size.
Definition at line 124 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::is_displayed(), and SetBuffered().
SetUnbuffered()
void llvm::raw_ostream::SetUnbuffered () inline
Set the stream to be unbuffered.
When unbuffered, the stream will flush after every write. This routine will also flush the buffer immediately when the stream is being set to unbuffered.
Definition at line 142 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::is_displayed(), and SetBuffered().
tell()
uint64_t llvm::raw_ostream::tell () const inline
tell - Return the current offset with the file.
Definition at line 113 of file raw_ostream.h.
Referenced by llvm::gsym::FileWriter::alignTo(), computeMemberData(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::DWARFYAML::EmitDebugAranges(), llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc(), llvm::MCDwarfLineAddr::FixedEncode(), getSymbols(), isMips64EL(), pad(), printLine(), printMemberHeader(), printWithSpacePadding(), llvm::raw_fd_ostream::seek(), llvm::gsym::FileWriter::tell(), writeCOFF(), llvm::sampleprof::SampleProfileWriterCompactBinary::writeFuncOffsetTable(), llvm::MachObjectWriter::writeObject(), and writeSymbolTable().
write() [1/2]
raw_ostream & raw_ostream::write (unsigned char C)
Definition at line 222 of file raw_ostream.cpp.
References C, LLVM_UNLIKELY, and SetBuffered().
Referenced by adjustFixupValue(), llvm::raw_fd_ostream::changeColor(), llvm::InstrProfRecordWriterTrait::EmitData(), llvm::DWARFYAML::EmitDebugAbbrev(), llvm::DWARFYAML::EmitDebugLine(), llvm::DWARFYAML::EmitDebugStr(), emitExternalFile(), EmitFileEntry(), EmitGCCInlineAsmStr(), llvm::InstrProfRecordWriterTrait::EmitKey(), emitMagic(), EmitMSInlineAsmStr(), llvm::DWARFYAML::EmitPubSection(), emitStrTab(), emitVersion(), llvm::circular_raw_ostream::flushBufferWithBanner(), llvm::remarks::BitstreamRemarkSerializerHelper::flushToStream(), getFixupKindSize(), getLit64Encoding(), isMips64EL(), llvm::orc::DumpObjects::operator()(), operator<<(), operator<<(), llvm::formatted_raw_ostream::PadToColumn(), printBSDMemberHeader(), llvm::raw_fd_ostream::resetColor(), llvm::raw_fd_ostream::reverseColor(), llvm::raw_fd_ostream::seek(), llvm::remarks::StringTable::serialize(), shouldKeepInEntry(), llvm::support::endian::write(), write(), llvm::write_hex(), write_padding(), write_unsigned_impl(), writeArrayData(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::yaml::BinaryRef::writeAsHex(), llvm::WriteBitcodeToFile(), writeCOFF(), llvm::gsym::FileWriter::writeData(), llvm::writeFileAtomically(), llvm::WriteIndexToFile(), writeInteger(), writeLimits(), llvm::ARMAsmBackend::writeNopData(), llvm::RISCVAsmBackend::writeNopData(), llvm::gsym::FileWriter::writeSLEB(), writeSymbolTable(), llvm::WriteThinLinkBitcodeToFile(), llvm::gsym::FileWriter::writeU16(), llvm::gsym::FileWriter::writeU32(), llvm::gsym::FileWriter::writeU64(), llvm::gsym::FileWriter::writeU8(), writeUint32(), writeUint64(), writeUint8(), llvm::gsym::FileWriter::writeULEB(), writeWithCommas(), zero(), ZeroFillBytes(), and llvm::raw_fd_ostream::~raw_fd_ostream().
write() [2/2]
raw_ostream & raw_ostream::write (const char * Ptr, size_t Size)
Definition at line 242 of file raw_ostream.cpp.
References assert(), LLVM_FALLTHROUGH, LLVM_UNLIKELY, SetBuffered(), Size, and write().
write_escaped()
raw_ostream & raw_ostream::write_escaped (StringRef Str, bool UseHexEscapes = false)
Output Str, turning '\', '', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
Definition at line 165 of file raw_ostream.cpp.
References llvm::isPrint().
Referenced by llvm::DWARFFormValue::dump(), llvm::DWARFContext::dump(), llvm::AsmToken::dump(), llvm::StringToOffsetTable::EmitCharArray(), llvm::StringToOffsetTable::EmitString(), llvm::object::ArchiveMemberHeader::getAccessMode(), llvm::object::ArchiveMemberHeader::getGID(), llvm::object::ArchiveMemberHeader::getLastModified(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::ArchiveMemberHeader::getSize(), llvm::object::ArchiveMemberHeader::getUID(), llvm::UndefVarError::log(), llvm::Pattern::printSubstitutions(), llvm::MCExternalSymbolizer::tryAddingPcLoadReferenceComment(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
write_hex()
raw_ostream & raw_ostream::write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
Definition at line 142 of file raw_ostream.cpp.
References llvm::Lower, and llvm::write_hex().
Referenced by dumpDataAux(), llvm::DIEInteger::print(), llvm::AArch64InstPrinter::printAlignedLabel(), llvm::ARMInstPrinter::printExpandedImmOperand(), printExpr(), printHex32(), llvm::AArch64InstPrinter::printLogicalImm(), llvm::ARMInstPrinter::printOperand(), PrintQuotedString(), printSImmOperand(), llvm::ARMInstPrinter::printVMOVModImmOperand(), llvm::HexagonShuffler::shuffle(), and llvm::Twine::toNullTerminatedStringRef().
write_uuid()
raw_ostream & raw_ostream::write_uuid (const uuid_t UUID)
Definition at line 155 of file raw_ostream.cpp.
References llvm::format().
Referenced by dumpUUID(), and llvm::yaml::ScalarTraits< uuid_t >::output().
write_zeros()
raw_ostream & raw_ostream::write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
Definition at line 501 of file raw_ostream.cpp.
Referenced by adjustFixupValue(), llvm::gsym::FileWriter::alignTo(), llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc(), llvm::MCDwarfLineAddr::FixedEncode(), getFixupKindNumBytes(), isMips64EL(), writeCOFF(), writeContent(), llvm::AVRAsmBackend::writeNopData(), llvm::MipsAsmBackend::writeNopData(), and llvm::MachObjectWriter::writeObject().
Member Data Documentation
BLACK
const raw_ostream::Colors raw_ostream::BLACK = Colors::BLACK static
Definition at line 89 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
BLUE
const raw_ostream::Colors raw_ostream::BLUE = Colors::BLUE static
Definition at line 93 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
CYAN
const raw_ostream::Colors raw_ostream::CYAN = Colors::CYAN static
Definition at line 95 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
GREEN
const raw_ostream::Colors raw_ostream::GREEN = Colors::GREEN static
Definition at line 91 of file raw_ostream.h.
Referenced by llvm::SMDiagnostic::print(), and llvm::WithColor::WithColor().
MAGENTA
const raw_ostream::Colors raw_ostream::MAGENTA = Colors::MAGENTA static
Definition at line 94 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
RED
const raw_ostream::Colors raw_ostream::RED = Colors::RED static
Definition at line 90 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
RESET
const raw_ostream::Colors raw_ostream::RESET = Colors::RESET static
Definition at line 98 of file raw_ostream.h.
SAVEDCOLOR
const raw_ostream::Colors raw_ostream::SAVEDCOLOR = Colors::SAVEDCOLOR static
Definition at line 97 of file raw_ostream.h.
Referenced by llvm::raw_fd_ostream::changeColor(), and llvm::SMDiagnostic::print().
WHITE
const raw_ostream::Colors raw_ostream::WHITE = Colors::WHITE static
Definition at line 96 of file raw_ostream.h.
YELLOW
const raw_ostream::Colors raw_ostream::YELLOW = Colors::YELLOW static
Definition at line 92 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
The documentation for this class was generated from the following files:
include/llvm/Support/raw_ostream.h
lib/Support/raw_ostream.cpp