LLVM: llvm::BTFTypeBase Class Reference
llvm::BTFTypeBase Class Reference
The base class for BTF type generation.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
virtual uint32_t getSize ()
Get the size of this BTF type entry.
virtual void completeType (BTFDebug &BDebug)
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
virtual void emitType (MCStreamer &OS)
Emit types for this BTF type entry.
Protected Attributes
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
The base class for BTF type generation.
Definition at line 33 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFTypeBase()
llvm::BTFTypeBase::BTFTypeBase () inline
Definition at line 41 of file BTFDebug.h.
References ~BTFTypeBase().
~BTFTypeBase()
virtual llvm::BTFTypeBase::~BTFTypeBase () virtual default
Referenced by BTFTypeBase().
Member Function Documentation
completeType()
virtual void llvm::BTFTypeBase::completeType (BTFDebug & BDebug) inline virtual
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
Reimplemented in llvm::BTFKindDataSec, llvm::BTFKindVar, llvm::BTFTypeFunc, llvm::BTFTypeFuncProto, llvm::BTFTypeStruct, llvm::BTFTypeArray, llvm::BTFTypeEnum, llvm::BTFTypeInt, llvm::BTFTypeFwd, and llvm::BTFTypeDerived.
Definition at line 51 of file BTFDebug.h.
References emitType().
Referenced by llvm::BTFKindDataSec::getName(), llvm::BTFTypeInt::getSize(), llvm::BTFTypeEnum::getSize(), llvm::BTFTypeArray::getSize(), llvm::BTFTypeStruct::getSize(), llvm::BTFTypeFuncProto::getSize(), llvm::BTFTypeFunc::getSize(), and llvm::BTFKindVar::getSize().
emitType()
void BTFTypeBase::emitType (MCStreamer & OS) virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented in llvm::BTFKindDataSec, llvm::BTFKindVar, llvm::BTFTypeFunc, llvm::BTFTypeFuncProto, llvm::BTFTypeStruct, llvm::BTFTypeArray, llvm::BTFTypeEnum, llvm::BTFTypeInt, llvm::BTFTypeFwd, and llvm::BTFTypeDerived.
Definition at line 34 of file BTFDebug.cpp.
References llvm::MCStreamer::AddComment(), BTFType, llvm::MCStreamer::EmitIntValue(), Id, llvm::BTF::CommonType::Info, Kind, llvm::BTF::CommonType::NameOff, llvm::BTF::CommonType::Size, llvm::to_string(), and llvm::Twine::utohexstr().
Referenced by completeType(), llvm::BTFTypeDerived::emitType(), llvm::BTFTypeFwd::emitType(), llvm::BTFTypeInt::emitType(), llvm::BTFTypeEnum::emitType(), llvm::BTFTypeArray::emitType(), llvm::BTFTypeStruct::emitType(), llvm::BTFTypeFuncProto::emitType(), llvm::BTFTypeFunc::emitType(), llvm::BTFKindVar::emitType(), llvm::BTFKindDataSec::emitType(), llvm::BTFKindDataSec::getName(), llvm::BTFTypeInt::getSize(), llvm::BTFTypeEnum::getSize(), llvm::BTFTypeArray::getSize(), llvm::BTFTypeStruct::getSize(), llvm::BTFTypeFuncProto::getSize(), llvm::BTFTypeFunc::getSize(), and llvm::BTFKindVar::getSize().
getId()
uint32_t llvm::BTFTypeBase::getId () inline
Definition at line 44 of file BTFDebug.h.
References Id.
getSize()
virtual uint32_t llvm::BTFTypeBase::getSize () inline virtual
Get the size of this BTF type entry.
Reimplemented in llvm::BTFKindDataSec, llvm::BTFKindVar, llvm::BTFTypeFunc, llvm::BTFTypeFuncProto, llvm::BTFTypeStruct, llvm::BTFTypeArray, llvm::BTFTypeEnum, and llvm::BTFTypeInt.
Definition at line 47 of file BTFDebug.h.
References llvm::BTF::CommonTypeSize.
Referenced by llvm::BTFTypeInt::getSize(), llvm::BTFTypeEnum::getSize(), llvm::BTFTypeArray::getSize(), llvm::BTFTypeStruct::getSize(), llvm::BTFTypeFuncProto::getSize(), llvm::BTFTypeFunc::getSize(), llvm::BTFKindVar::getSize(), and llvm::BTFKindDataSec::getSize().
roundupToBytes()
uint32_t llvm::BTFTypeBase::roundupToBytes (uint32_t NumBits) inline
Definition at line 45 of file BTFDebug.h.
Referenced by llvm::BTFTypeEnum::BTFTypeEnum(), llvm::BTFTypeInt::BTFTypeInt(), and llvm::BTFTypeStruct::BTFTypeStruct().
setId()
void llvm::BTFTypeBase::setId (uint32_t Id) inline
Definition at line 43 of file BTFDebug.h.
References Id.
Member Data Documentation
BTFType
struct BTF::CommonType llvm::BTFTypeBase::BTFType protected
Definition at line 38 of file BTFDebug.h.
Referenced by llvm::BTFKindDataSec::BTFKindDataSec(), llvm::BTFKindVar::BTFKindVar(), llvm::BTFTypeArray::BTFTypeArray(), llvm::BTFTypeDerived::BTFTypeDerived(), llvm::BTFTypeEnum::BTFTypeEnum(), llvm::BTFTypeFunc::BTFTypeFunc(), llvm::BTFTypeFuncProto::BTFTypeFuncProto(), llvm::BTFTypeFwd::BTFTypeFwd(), llvm::BTFTypeInt::BTFTypeInt(), llvm::BTFTypeStruct::BTFTypeStruct(), llvm::BTFTypeDerived::completeType(), llvm::BTFTypeFwd::completeType(), llvm::BTFTypeInt::completeType(), llvm::BTFTypeEnum::completeType(), llvm::BTFTypeStruct::completeType(), llvm::BTFTypeFuncProto::completeType(), llvm::BTFTypeFunc::completeType(), llvm::BTFKindVar::completeType(), llvm::BTFKindDataSec::completeType(), emitType(), and llvm::BTFTypeDerived::setPointeeType().
Id
uint32_t llvm::BTFTypeBase::Id protected
Definition at line 37 of file BTFDebug.h.
Referenced by emitType(), getId(), and setId().
IsCompleted
bool llvm::BTFTypeBase::IsCompleted protected
Definition at line 36 of file BTFDebug.h.
Referenced by llvm::BTFTypeDerived::completeType(), llvm::BTFTypeFwd::completeType(), llvm::BTFTypeInt::completeType(), llvm::BTFTypeEnum::completeType(), llvm::BTFTypeArray::completeType(), llvm::BTFTypeStruct::completeType(), llvm::BTFTypeFuncProto::completeType(), and llvm::BTFTypeFunc::completeType().
Kind
uint8_t llvm::BTFTypeBase::Kind protected
Definition at line 35 of file BTFDebug.h.
Referenced by llvm::BTFKindDataSec::BTFKindDataSec(), llvm::BTFKindVar::BTFKindVar(), llvm::BTFTypeArray::BTFTypeArray(), llvm::BTFTypeDerived::BTFTypeDerived(), llvm::BTFTypeEnum::BTFTypeEnum(), llvm::BTFTypeFunc::BTFTypeFunc(), llvm::BTFTypeFuncProto::BTFTypeFuncProto(), llvm::BTFTypeFwd::BTFTypeFwd(), llvm::BTFTypeInt::BTFTypeInt(), llvm::BTFTypeStruct::BTFTypeStruct(), llvm::BTFTypeDerived::completeType(), and emitType().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp