LLVM: llvm::BTFTypeInt Class Reference
llvm::BTFTypeInt Class Reference
Handle int type.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFTypeInt (uint32_t Encoding, uint32_t SizeInBits, uint32_t OffsetInBits, StringRef TypeName)
uint32_t getSize ()
Get the size of this BTF type entry.
void completeType (BTFDebug &BDebug)
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
void emitType (MCStreamer &OS)
Emit types for this BTF type entry.
Public Member Functions inherited from llvm::BTFTypeBase
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
Additional Inherited Members
Protected Attributes inherited from llvm::BTFTypeBase
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
Handle int type.
Definition at line 80 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFTypeInt()
BTFTypeInt::BTFTypeInt (uint32_t Encoding, uint32_t SizeInBits, uint32_t OffsetInBits, StringRef TypeName)
Definition at line 113 of file BTFDebug.cpp.
References llvm::BTFTypeBase::BTFType, llvm::BTF::CommonType::Info, llvm::BTF::INT_BOOL, llvm::BTF::INT_SIGNED, llvm::BTFTypeBase::Kind, llvm_unreachable, llvm::BTFTypeBase::roundupToBytes(), and llvm::BTF::CommonType::Size.
Member Function Documentation
completeType()
void BTFTypeInt::completeType (BTFDebug & BDebug) virtual
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
Reimplemented from llvm::BTFTypeBase.
Definition at line 140 of file BTFDebug.cpp.
References llvm::BTFDebug::addString(), llvm::BTFTypeBase::BTFType, llvm::BTFTypeBase::IsCompleted, and llvm::BTF::CommonType::NameOff.
emitType()
void BTFTypeInt::emitType (MCStreamer & OS) virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented from llvm::BTFTypeBase.
Definition at line 148 of file BTFDebug.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCStreamer::EmitIntValue(), llvm::BTFTypeBase::emitType(), and llvm::Twine::utohexstr().
getSize()
uint32_t llvm::BTFTypeInt::getSize () inline virtual
Get the size of this BTF type entry.
Reimplemented from llvm::BTFTypeBase.
Definition at line 87 of file BTFDebug.h.
References llvm::BTFTypeBase::completeType(), llvm::BTFTypeBase::emitType(), and llvm::BTFTypeBase::getSize().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp