LLVM: llvm::CallGraphPrinterPass Class Reference
llvm::CallGraphPrinterPass Class Reference
Printer pass for the CallGraphAnalysis results.
#include "llvm/Analysis/CallGraph.h"
Public Member Functions
CallGraphPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< CallGraphPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the CallGraphAnalysis results.
Definition at line 308 of file CallGraph.h.
Constructor & Destructor Documentation
CallGraphPrinterPass()
llvm::CallGraphPrinterPass::CallGraphPrinterPass (raw_ostream & OS) inline explicit
Definition at line 312 of file CallGraph.h.
Member Function Documentation
run()
PreservedAnalyses CallGraphPrinterPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 247 of file CallGraph.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::CallGraph::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CallGraph.h
lib/Analysis/CallGraph.cpp