LLVM: llvm::StackMaps Class Reference
llvm::StackMaps Class Reference
#include "llvm/CodeGen/StackMaps.h"
Classes
struct CallsiteInfo
struct FunctionInfo
struct LiveOutReg
struct Location
Public Types
using OpType = enum { DirectMemRefOp, IndirectMemRefOp, ConstantOp }
using LocationVec = SmallVector< Location, 8 >
using LiveOutVec = SmallVector< LiveOutReg, 8 >
using ConstantPool = MapVector< uint64_t, uint64_t >
using FnInfoMap = MapVector< const MCSymbol *, FunctionInfo >
using CallsiteInfoList = std::vector< CallsiteInfo >
Public Member Functions
StackMaps (AsmPrinter &AP)
void reset ()
void recordStackMap (const MCSymbol &L, const MachineInstr &MI)
Generate a stackmap record for a stackmap instruction.
void recordPatchPoint (const MCSymbol &L, const MachineInstr &MI)
Generate a stackmap record for a patchpoint instruction.
void recordStatepoint (const MCSymbol &L, const MachineInstr &MI)
Generate a stackmap record for a statepoint instruction.
void serializeToStackMapSection ()
If there is any stack map data, create a stack map section and serialize the map info into it.
CallsiteInfoList & getCSInfos ()
Get call site info.
FnInfoMap & getFnInfos ()
Get function info.
Detailed Description
Definition at line 193 of file StackMaps.h.
Member Typedef Documentation
CallsiteInfoList
using llvm::StackMaps::CallsiteInfoList = std::vector<CallsiteInfo>
Definition at line 264 of file StackMaps.h.
ConstantPool
using llvm::StackMaps::ConstantPool = MapVector<uint64_t, uint64_t>
Definition at line 240 of file StackMaps.h.
FnInfoMap
using llvm::StackMaps::FnInfoMap = MapVector<const MCSymbol *, FunctionInfo>
Definition at line 263 of file StackMaps.h.
LiveOutVec
using llvm::StackMaps::LiveOutVec = SmallVector<LiveOutReg, 8>
Definition at line 239 of file StackMaps.h.
LocationVec
using llvm::StackMaps::LocationVec = SmallVector<Location, 8>
Definition at line 238 of file StackMaps.h.
OpType
using llvm::StackMaps::OpType = enum { DirectMemRefOp, IndirectMemRefOp, ConstantOp }
Definition at line 228 of file StackMaps.h.
Constructor & Destructor Documentation
StackMaps()
StackMaps::StackMaps (AsmPrinter & AP)
Definition at line 86 of file StackMaps.cpp.
References llvm_unreachable, and StackMapVersion.
Member Function Documentation
getCSInfos()
CallsiteInfoList& llvm::StackMaps::getCSInfos () inline
Get call site info.
Definition at line 286 of file StackMaps.h.
getFnInfos()
FnInfoMap& llvm::StackMaps::getFnInfos () inline
Get function info.
Definition at line 289 of file StackMaps.h.
References llvm::dbgs(), debug, llvm::BitmaskEnumDetail::Mask(), MI, print(), Reg, and TRI.
recordPatchPoint()
void StackMaps::recordPatchPoint (const MCSymbol & L, const MachineInstr & MI)
Generate a stackmap record for a patchpoint instruction.
Definition at line 372 of file StackMaps.cpp.
References assert(), llvm::numbers::e, llvm::MachineInstr::getOpcode(), llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), and llvm::StackMaps::Location::Register.
Referenced by EmitNop().
recordStackMap()
void StackMaps::recordStackMap (const MCSymbol & L, const MachineInstr & MI)
Generate a stackmap record for a stackmap instruction.
MI must be a raw STACKMAP, not a PATCHPOINT.
Definition at line 362 of file StackMaps.cpp.
References assert(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::PatchPointOpers::IDPos, llvm::MachineInstr::operands_begin(), and llvm::MachineInstr::operands_end().
Referenced by EmitNop().
recordStatepoint()
void StackMaps::recordStatepoint (const MCSymbol & L, const MachineInstr & MI)
Generate a stackmap record for a statepoint instruction.
Definition at line 393 of file StackMaps.cpp.
References assert(), llvm::dbgs(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::MachineInstr::getOpcode(), LLVM_DEBUG, llvm::AArch64CC::LO, llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::SmallVectorBase::size(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size(), StackMapVersion, and UINT64_MAX.
reset()
void llvm::StackMaps::reset () inline
Definition at line 232 of file StackMaps.h.
Referenced by llvm::SystemZAsmPrinter::doInitialization(), and llvm::X86AsmPrinter::doInitialization().
serializeToStackMapSection()
void StackMaps::serializeToStackMapSection ()
If there is any stack map data, create a stack map section and serialize the map info into it.
Serialize the stackmap data.
This clears the stack map data structures afterwards.
Definition at line 548 of file StackMaps.cpp.
References llvm::MCStreamer::AddBlankLine(), assert(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear(), llvm::dbgs(), llvm::MCStreamer::EmitLabel(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::empty(), llvm::MCContext::getObjectFileInfo(), llvm::MCContext::getOrCreateSymbol(), llvm::MCObjectFileInfo::getStackMapSection(), LLVM_DEBUG, llvm::AsmPrinter::OutStreamer, and llvm::MCStreamer::SwitchSection().
Referenced by llvm::AsmPrinter::emitStackMaps().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/StackMaps.h
lib/CodeGen/StackMaps.cpp