LLVM: llvm::CFLSteensAAResult::FunctionInfo Class Reference
llvm::CFLSteensAAResult::FunctionInfo Class Reference
Information we have about a function and would like to keep around.
Public Member Functions
FunctionInfo (Function &Fn, const SmallVectorImpl< Value *> &RetVals, StratifiedSets< InstantiatedValue > S)
const StratifiedSets< InstantiatedValue > & getStratifiedSets () const
const AliasSummary & getAliasSummary () const
Detailed Description
Information we have about a function and would like to keep around.
Definition at line 72 of file CFLSteensAliasAnalysis.cpp.
Constructor & Destructor Documentation
FunctionInfo()
llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo (Function & Fn, const SmallVectorImpl< Value *> & RetVals, StratifiedSets< InstantiatedValue > S)
Definition at line 116 of file CFLSteensAliasAnalysis.cpp.
References llvm::cflaa::StratifiedSetsBuilder< T >::add(), llvm::cflaa::StratifiedSetsBuilder< T >::addBelow(), llvm::cflaa::StratifiedSetsBuilder< T >::addWith(), llvm::Function::arg_size(), llvm::Function::args(), assert(), llvm::cflaa::StratifiedSetsBuilder< T >::build(), canSkipAddingToSets(), E, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::cflaa::StratifiedSets< T >::find(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::cflaa::CFLGraphBuilder< CFLAA >::getCFLGraph(), llvm::cflaa::getExternallyVisibleAttrs(), llvm::cflaa::StratifiedSets< T >::getLink(), llvm::cflaa::CFLGraphBuilder< CFLAA >::getReturnValues(), I, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::codeview::Link, llvm::cflaa::MaxSupportedArgsInSummary, llvm::cflaa::StratifiedSetsBuilder< T >::noteAttributes(), and llvm::cflaa::UnknownOffset.
Member Function Documentation
getAliasSummary()
const AliasSummary& llvm::CFLSteensAAResult::FunctionInfo::getAliasSummary () const inline
Definition at line 84 of file CFLSteensAliasAnalysis.cpp.
References llvm::max().
getStratifiedSets()
const StratifiedSets<InstantiatedValue>& llvm::CFLSteensAAResult::FunctionInfo::getStratifiedSets () const inline
Definition at line 80 of file CFLSteensAliasAnalysis.cpp.
The documentation for this class was generated from the following file:
lib/Analysis/CFLSteensAliasAnalysis.cpp