LLVM: llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > Class Template Reference
llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > Class Template Reference
PointerIntPair - This class implements a pair of a pointer and small integer.
#include "llvm/ADT/PointerIntPair.h"
Public Member Functions
constexpr PointerIntPair ()=default
PointerIntPair (PointerTy PtrVal, IntType IntVal)
PointerIntPair (PointerTy PtrVal)
PointerTy getPointer () const
IntType getInt () const
void setPointer (PointerTy PtrVal) LLVM_LVALUE_FUNCTION
void setInt (IntType IntVal) LLVM_LVALUE_FUNCTION
void initWithPointer (PointerTy PtrVal) LLVM_LVALUE_FUNCTION
void setPointerAndInt (PointerTy PtrVal, IntType IntVal) LLVM_LVALUE_FUNCTION
PointerTy const * getAddrOfPointer () const
PointerTy * getAddrOfPointer ()
void * getOpaqueValue () const
void setFromOpaqueValue (void *Val) LLVM_LVALUE_FUNCTION
bool operator== (const PointerIntPair &RHS) const
bool operator!= (const PointerIntPair &RHS) const
bool operator< (const PointerIntPair &RHS) const
bool operator> (const PointerIntPair &RHS) const
bool operator<= (const PointerIntPair &RHS) const
bool operator>= (const PointerIntPair &RHS) const
Static Public Member Functions
static PointerIntPair getFromOpaqueValue (void *V)
static PointerIntPair getFromOpaqueValue (const void *V)
Detailed Description
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>>
class llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >
PointerIntPair - This class implements a pair of a pointer and small integer.
It is designed to represent this in the space required by one pointer by bitmangling the integer into the low part of the pointer. This can only be done for small integers: typically up to 3 bits, but it depends on the number of bits available according to PointerLikeTypeTraits for the type.
Note that PointerIntPair always puts the IntVal part in the highest bits possible. For example, PointerIntPair<void*, 1, bool> will put the bit for the bool into bit #2, not bit #0, which allows the low two bits to be used for something else. For example, this allows: PointerIntPair<PointerIntPair<void*, 1, bool>, 1, bool> ... and the two bools will land in different bits.
Definition at line 45 of file PointerIntPair.h.
Constructor & Destructor Documentation
PointerIntPair() [1/3]
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> constexpr llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::PointerIntPair () default
PointerIntPair() [2/3]
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::PointerIntPair (PointerTy PtrVal, IntType IntVal) inline
Definition at line 53 of file PointerIntPair.h.
PointerIntPair() [3/3]
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::PointerIntPair (PointerTy PtrVal) inline explicit
Definition at line 57 of file PointerIntPair.h.
Member Function Documentation
getAddrOfPointer() [1/2]
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> PointerTy const* llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getAddrOfPointer () const inline
Definition at line 80 of file PointerIntPair.h.
Referenced by llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::getAddrOfPointer().
getAddrOfPointer() [2/2]
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> PointerTy* llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getAddrOfPointer () inline
Definition at line 84 of file PointerIntPair.h.
getFromOpaqueValue() [1/2]
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> static PointerIntPair llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getFromOpaqueValue (void * V) inline static
Definition at line 97 of file PointerIntPair.h.
Referenced by llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::getFromOpaqueValue(), and llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getFromVoidPointer().
getFromOpaqueValue() [2/2]
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> static PointerIntPair llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getFromOpaqueValue (const void * V) inline static
Definition at line 105 of file PointerIntPair.h.
getInt()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> IntType llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt () const inline
Definition at line 61 of file PointerIntPair.h.
Referenced by llvm::ValueHandleBase::clearValPtr(), emitNonLazySymbolPointer(), llvm::cfg::Update< NodePtr >::getKind(), llvm::LazyCallGraph::Edge::getKind(), llvm::MCSymbol::getName(), llvm::IntrusiveBackListNode::getNext(), llvm::RecordVal::getPrefix(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::isCall(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::isCallBr(), llvm::gvn::AvailableValue::isCoercedLoadValue(), llvm::DwarfStringPoolEntryRef::isIndexed(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::isInvoke(), llvm::gvn::AvailableValue::isMemIntrinValue(), llvm::gvn::AvailableValue::isSimpleValue(), llvm::RegionNodeBase< RegionTraits< Function > >::isSubRegion(), llvm::gvn::AvailableValue::isUndefValue(), llvm::MCSymbol::MCSymbol(), llvm::GlobalsAAResult::FunctionInfo::operator=(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator==(), llvm::IntervalMapImpl::NodeRef::size(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
getOpaqueValue()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> void* llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getOpaqueValue () const inline
Definition at line 91 of file PointerIntPair.h.
Referenced by llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getAsVoidPointer(), llvm::DenseMapInfo< PointerIntPair< PointerTy, IntBits, IntType > >::getHashValue(), and llvm::IntervalMapImpl::NodeRef::operator bool().
getPointer()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> PointerTy llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer () const inline
Definition at line 59 of file PointerIntPair.h.
Referenced by llvm::GlobalsAAResult::FunctionInfo::addFunctionInfo(), llvm::ValueHandleBase::clearValPtr(), llvm::SplitEditor::dump(), llvm::X86AsmPrinter::EmitFunctionBodyEnd(), emitNonLazySymbolPointer(), llvm::GlobalsAAResult::FunctionInfo::FunctionInfo(), llvm::IntervalMapImpl::NodeRef::get(), llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::getAddrOfPointer(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::gvn::AvailableValue::getCoercedLoadValue(), llvm::RegionNodeBase< RegionTraits< Function > >::getEntry(), llvm::MCSymbol::getFragment(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::getInstruction(), llvm::gvn::AvailableValue::getMemIntrinValue(), llvm::IntrusiveBackListNode::getNext(), llvm::LazyCallGraph::Edge::getNode(), llvm::gvn::AvailableValue::getSimpleValue(), GetSymbolFromOperand(), llvm::cfg::Update< NodePtr >::getTo(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::RecordVal::getType(), llvm::SlotIndex::isValid(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::operator bool(), llvm::LazyCallGraph::Edge::operator bool(), llvm::unique_function< ReturnT(ParamTs...)>::operator bool(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::operator->(), llvm::GlobalsAAResult::FunctionInfo::operator=(), llvm::IntervalMapImpl::NodeRef::operator==(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndex::SlotIndex(), llvm::IntervalMapImpl::NodeRef::subtree(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), and llvm::unique_function< ReturnT(ParamTs...)>::~unique_function().
initWithPointer()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> void llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::initWithPointer (PointerTy PtrVal) inline
Definition at line 71 of file PointerIntPair.h.
Referenced by llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::PointerIntPair().
operator!=()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> bool llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::operator!= (const PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > & RHS) const inline
Definition at line 114 of file PointerIntPair.h.
operator<()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> bool llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::operator< (const PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > & RHS) const inline
Definition at line 118 of file PointerIntPair.h.
operator<=()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> bool llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::operator<= (const PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > & RHS) const inline
Definition at line 121 of file PointerIntPair.h.
operator==()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> bool llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::operator== (const PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > & RHS) const inline
Definition at line 110 of file PointerIntPair.h.
operator>()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> bool llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::operator> (const PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > & RHS) const inline
Definition at line 119 of file PointerIntPair.h.
operator>=()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> bool llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::operator>= (const PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > & RHS) const inline
Definition at line 125 of file PointerIntPair.h.
setFromOpaqueValue()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> void llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setFromOpaqueValue (void * Val) inline
Definition at line 93 of file PointerIntPair.h.
Referenced by llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::getFromOpaqueValue().
setInt()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> void llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setInt (IntType IntVal) inline
Definition at line 67 of file PointerIntPair.h.
Referenced by llvm::SplitEditor::dump(), llvm::MCSymbol::MCSymbol(), NewGVN::ValueDFS::operator<(), and llvm::IntervalMapImpl::NodeRef::setSize().
setPointer()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> void llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setPointer (PointerTy PtrVal) inline
Definition at line 63 of file PointerIntPair.h.
Referenced by llvm::ValueHandleBase::clearValPtr(), llvm::MCSymbol::getFragment(), NewGVN::ValueDFS::operator<(), llvm::MCSymbol::setFragment(), and llvm::MCSymbol::setUndefined().
setPointerAndInt()
template<typename PointerTy, unsigned IntBits, typename IntType = unsigned, typename PtrTraits = PointerLikeTypeTraits<PointerTy>, typename Info = PointerIntPairInfo<PointerTy, IntBits, PtrTraits>> void llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setPointerAndInt (PointerTy PtrVal, IntType IntVal) inline
Definition at line 75 of file PointerIntPair.h.
Referenced by llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::PointerIntPair().
The documentation for this class was generated from the following file:
include/llvm/ADT/PointerIntPair.h