LLVM: llvm::orc::LLJIT Class Reference
llvm::orc::LLJIT Class Reference
A pre-fabricated ORC JIT stack that can serve as an alternative to MCJIT.
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
~LLJIT ()
Destruct this instance.
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this instance.
const DataLayout & getDataLayout () const
Returns a reference to the DataLayout for this instance.
JITDylib & getMainJITDylib ()
Returns a reference to the JITDylib representing the JIT'd main program.
JITDylib * getJITDylibByName (StringRef Name)
Returns the JITDylib with the given name, or nullptr if no JITDylib with that name exists.
JITDylib & createJITDylib (std::string Name)
Create a new JITDylib with the given name and return a reference to it.
Error defineAbsolute (StringRef Name, JITEvaluatedSymbol Address)
Convenience method for defining an absolute symbol.
Error addIRModule (JITDylib &JD, ThreadSafeModule TSM)
Adds an IR module to the given JITDylib.
Error addIRModule (ThreadSafeModule TSM)
Adds an IR module to the Main JITDylib.
Error addObjectFile (JITDylib &JD, std::unique_ptr< MemoryBuffer > Obj)
Adds an object file to the given JITDylib.
Error addObjectFile (std::unique_ptr< MemoryBuffer > Obj)
Adds an object file to the given JITDylib.
Expected< JITEvaluatedSymbol > lookupLinkerMangled (JITDylib &JD, StringRef Name)
Look up a symbol in JITDylib JD by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Expected< JITEvaluatedSymbol > lookupLinkerMangled (StringRef Name)
Look up a symbol in the main JITDylib by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Expected< JITEvaluatedSymbol > lookup (JITDylib &JD, StringRef UnmangledName)
Look up a symbol in JITDylib JD based on its IR symbol name.
Expected< JITEvaluatedSymbol > lookup (StringRef UnmangledName)
Look up a symbol in the main JITDylib based on its IR symbol name.
Error runConstructors ()
Runs all not-yet-run static constructors.
Error runDestructors ()
Runs all not-yet-run static destructors.
ObjectLayer & getObjLinkingLayer ()
Returns a reference to the ObjLinkingLayer.
ObjectTransformLayer & getObjTransformLayer ()
Returns a reference to the object transform layer.
Static Public Member Functions
static Expected< std::unique_ptr< LLJIT > > Create (LLJITBuilderState &S)
Protected Member Functions
LLJIT (LLJITBuilderState &S, Error &Err)
Create an LLJIT instance with a single compile thread.
std::string mangle (StringRef UnmangledName)
Error applyDataLayout (Module &M)
void recordCtorDtors (Module &M)
Static Protected Member Functions
static std::unique_ptr< ObjectLayer > createObjectLinkingLayer (LLJITBuilderState &S, ExecutionSession &ES)
static Expected< std::unique_ptr< IRCompileLayer::IRCompiler > > createCompileFunction (LLJITBuilderState &S, JITTargetMachineBuilder JTMB)
Protected Attributes
std::unique_ptr< ExecutionSession > ES
JITDylib & Main
DataLayout DL
std::unique_ptr< ThreadPool > CompileThreads
std::unique_ptr< ObjectLayer > ObjLinkingLayer
ObjectTransformLayer ObjTransformLayer
std::unique_ptr< IRCompileLayer > CompileLayer
CtorDtorRunner CtorRunner
CtorDtorRunner DtorRunner
Friends
template<typename , typename , typename >
class LLJITBuilderSetters
Detailed Description
A pre-fabricated ORC JIT stack that can serve as an alternative to MCJIT.
Create instances using LLJITBuilder.
Definition at line 35 of file LLJIT.h.
Constructor & Destructor Documentation
~LLJIT()
llvm::orc::LLJIT::~LLJIT ()
Destruct this instance.
If a multi-threaded instance, waits for all compile threads to complete.
Definition at line 52 of file LLJIT.cpp.
LLJIT()
llvm::orc::LLJIT::LLJIT (LLJITBuilderState & S, Error & Err) protected
Create an LLJIT instance with a single compile thread.
Definition at line 130 of file LLJIT.cpp.
Referenced by getObjTransformLayer().
Member Function Documentation
addIRModule() [1/2]
Error llvm::orc::LLJIT::addIRModule (JITDylib & JD, ThreadSafeModule TSM)
Adds an IR module to the given JITDylib.
Definition at line 63 of file LLJIT.cpp.
References assert().
Referenced by addIRModule(), and createJITDylib().
addIRModule() [2/2]
Error llvm::orc::LLJIT::addIRModule (ThreadSafeModule TSM) inline
Adds an IR module to the Main JITDylib.
Definition at line 77 of file LLJIT.h.
References addIRModule(), addObjectFile(), and Main.
addObjectFile() [1/2]
Error llvm::orc::LLJIT::addObjectFile (JITDylib & JD, std::unique_ptr< MemoryBuffer > Obj)
Adds an object file to the given JITDylib.
Definition at line 73 of file LLJIT.cpp.
References assert(), and llvm::orc::LLJITBuilderState::ES.
Referenced by addIRModule(), and addObjectFile().
addObjectFile() [2/2]
Error llvm::orc::LLJIT::addObjectFile (std::unique_ptr< MemoryBuffer > Obj) inline
Adds an object file to the given JITDylib.
Definition at line 85 of file LLJIT.h.
References addObjectFile(), lookupLinkerMangled(), and Main.
applyDataLayout()
Error llvm::orc::LLJIT::applyDataLayout (Module & M) protected
Definition at line 178 of file LLJIT.cpp.
References DL, llvm::Module::getDataLayout(), llvm::inconvertibleErrorCode(), llvm::DataLayout::isDefault(), llvm::Module::setDataLayout(), and llvm::Error::success().
Create()
static Expected<std::unique_ptr<LLJIT> > llvm::orc::LLJIT::Create (LLJITBuilderState & S) static
createCompileFunction()
Expected< std::unique_ptr< IRCompileLayer::IRCompiler > > llvm::orc::LLJIT::createCompileFunction (LLJITBuilderState & S, JITTargetMachineBuilder JTMB) static protected
If there is a custom compile function creator set then use it.
Definition at line 111 of file LLJIT.cpp.
References llvm::orc::LLJITBuilderState::CreateCompileFunction, llvm::orc::JITTargetMachineBuilder::createTargetMachine(), llvm::orc::LLJITBuilderState::NumCompileThreads, and llvm::SystemZISD::TM.
Referenced by getObjTransformLayer().
createJITDylib()
JITDylib& llvm::orc::LLJIT::createJITDylib (std::string Name) inline
Create a new JITDylib with the given name and return a reference to it.
JITDylib names must be unique. If the given name is derived from user input or elsewhere in the environment then the client should check (e.g. by calling getJITDylibByName) that the given name is not already in use.
Definition at line 66 of file LLJIT.h.
References addIRModule(), llvm::Address, defineAbsolute(), ES, and Name.
createObjectLinkingLayer()
std::unique_ptr< ObjectLayer > llvm::orc::LLJIT::createObjectLinkingLayer (LLJITBuilderState & S, ExecutionSession & ES) static protected
Definition at line 87 of file LLJIT.cpp.
References llvm::orc::LLJITBuilderState::CreateObjectLinkingLayer, llvm::orc::LLJITBuilderState::ES, and llvm::orc::LLJITBuilderState::JTMB.
Referenced by getObjTransformLayer().
defineAbsolute()
Error llvm::orc::LLJIT::defineAbsolute (StringRef Name, JITEvaluatedSymbol Address)
Convenience method for defining an absolute symbol.
Definition at line 57 of file LLJIT.cpp.
References llvm::orc::absoluteSymbols(), and llvm::orc::LLJITBuilderState::ES.
Referenced by createJITDylib().
getDataLayout()
const DataLayout& llvm::orc::LLJIT::getDataLayout () const inline
Returns a reference to the DataLayout for this instance.
Definition at line 49 of file LLJIT.h.
References DL.
getExecutionSession()
ExecutionSession& llvm::orc::LLJIT::getExecutionSession () inline
Returns the ExecutionSession for this instance.
Definition at line 46 of file LLJIT.h.
References ES.
getJITDylibByName()
JITDylib* llvm::orc::LLJIT::getJITDylibByName (StringRef Name) inline
Returns the JITDylib with the given name, or nullptr if no JITDylib with that name exists.
Definition at line 56 of file LLJIT.h.
References ES.
getMainJITDylib()
JITDylib& llvm::orc::LLJIT::getMainJITDylib () inline
Returns a reference to the JITDylib representing the JIT'd main program.
Definition at line 52 of file LLJIT.h.
References Main.
getObjLinkingLayer()
ObjectLayer& llvm::orc::LLJIT::getObjLinkingLayer () inline
Returns a reference to the ObjLinkingLayer.
Definition at line 118 of file LLJIT.h.
References ObjLinkingLayer.
getObjTransformLayer()
ObjectTransformLayer& llvm::orc::LLJIT::getObjTransformLayer () inline
Returns a reference to the object transform layer.
Definition at line 121 of file LLJIT.h.
References createCompileFunction(), createObjectLinkingLayer(), ES, LLJIT(), and ObjTransformLayer.
lookup() [1/2]
Expected<JITEvaluatedSymbol> llvm::orc::LLJIT::lookup (JITDylib & JD, StringRef UnmangledName) inline
Look up a symbol in JITDylib JD based on its IR symbol name.
Definition at line 102 of file LLJIT.h.
References lookupLinkerMangled(), and mangle().
Referenced by lookup().
lookup() [2/2]
Expected<JITEvaluatedSymbol> llvm::orc::LLJIT::lookup (StringRef UnmangledName) inline
Look up a symbol in the main JITDylib based on its IR symbol name.
Definition at line 107 of file LLJIT.h.
References lookup(), and Main.
lookupLinkerMangled() [1/2]
Expected< JITEvaluatedSymbol > llvm::orc::LLJIT::lookupLinkerMangled (JITDylib & JD, StringRef Name)
Look up a symbol in JITDylib JD by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Definition at line 79 of file LLJIT.cpp.
References llvm::orc::LLJITBuilderState::ES, llvm::orc::makeJITDylibSearchOrder(), and llvm::orc::MatchAllSymbols.
Referenced by addObjectFile(), lookup(), and lookupLinkerMangled().
lookupLinkerMangled() [2/2]
Expected<JITEvaluatedSymbol> llvm::orc::LLJIT::lookupLinkerMangled (StringRef Name) inline
Look up a symbol in the main JITDylib by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Definition at line 97 of file LLJIT.h.
References lookupLinkerMangled(), and Main.
mangle()
std::string llvm::orc::LLJIT::mangle (StringRef UnmangledName) protected
Definition at line 169 of file LLJIT.cpp.
References DL, and llvm::Mangler::getNameWithPrefix().
Referenced by lookup().
recordCtorDtors()
void llvm::orc::LLJIT::recordCtorDtors (Module & M) protected
Definition at line 190 of file LLJIT.cpp.
References llvm::orc::CtorDtorRunner::add(), CtorRunner, DtorRunner, llvm::orc::getConstructors(), and llvm::orc::getDestructors().
runConstructors()
Error llvm::orc::LLJIT::runConstructors () inline
Runs all not-yet-run static constructors.
Definition at line 112 of file LLJIT.h.
References CtorRunner, and llvm::orc::CtorDtorRunner::run().
runDestructors()
Error llvm::orc::LLJIT::runDestructors () inline
Runs all not-yet-run static destructors.
Definition at line 115 of file LLJIT.h.
References DtorRunner, and llvm::orc::CtorDtorRunner::run().
Friends And Related Function Documentation
LLJITBuilderSetters
template<typename , typename , typename > friend class LLJITBuilderSetters friend
Definition at line 36 of file LLJIT.h.
Member Data Documentation
CompileLayer
std::unique_ptr<IRCompileLayer> llvm::orc::LLJIT::CompileLayer protected
Definition at line 147 of file LLJIT.h.
CompileThreads
std::unique_ptr<ThreadPool> llvm::orc::LLJIT::CompileThreads protected
Definition at line 143 of file LLJIT.h.
CtorRunner
CtorDtorRunner llvm::orc::LLJIT::CtorRunner protected
Definition at line 149 of file LLJIT.h.
Referenced by recordCtorDtors(), and runConstructors().
DL
DataLayout llvm::orc::LLJIT::DL protected
Definition at line 142 of file LLJIT.h.
Referenced by applyDataLayout(), getDataLayout(), and mangle().
DtorRunner
CtorDtorRunner llvm::orc::LLJIT::DtorRunner protected
Definition at line 149 of file LLJIT.h.
Referenced by recordCtorDtors(), and runDestructors().
ES
std::unique_ptr<ExecutionSession> llvm::orc::LLJIT::ES protected
Definition at line 139 of file LLJIT.h.
Referenced by createJITDylib(), getExecutionSession(), getJITDylibByName(), and getObjTransformLayer().
Main
JITDylib& llvm::orc::LLJIT::Main protected
Definition at line 140 of file LLJIT.h.
Referenced by addIRModule(), llvm::orc::LLLazyJIT::addLazyIRModule(), addObjectFile(), getMainJITDylib(), lookup(), and lookupLinkerMangled().
ObjLinkingLayer
std::unique_ptr<ObjectLayer> llvm::orc::LLJIT::ObjLinkingLayer protected
Definition at line 145 of file LLJIT.h.
Referenced by getObjLinkingLayer().
ObjTransformLayer
ObjectTransformLayer llvm::orc::LLJIT::ObjTransformLayer protected
Definition at line 146 of file LLJIT.h.
Referenced by getObjTransformLayer().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LLJIT.h
lib/ExecutionEngine/Orc/LLJIT.cpp