LLVM: llvm::codeview::UdtSourceLineRecord Class Reference
llvm::codeview::UdtSourceLineRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
UdtSourceLineRecord ()=default
UdtSourceLineRecord (TypeRecordKind Kind)
UdtSourceLineRecord (TypeIndex UDT, TypeIndex SourceFile, uint32_t LineNumber)
TypeIndex getUDT () const
TypeIndex getSourceFile () const
uint32_t getLineNumber () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex UDT
TypeIndex SourceFile
uint32_t LineNumber = 0
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 633 of file TypeRecord.h.
Constructor & Destructor Documentation
UdtSourceLineRecord() [1/3]
llvm::codeview::UdtSourceLineRecord::UdtSourceLineRecord () default
UdtSourceLineRecord() [2/3]
llvm::codeview::UdtSourceLineRecord::UdtSourceLineRecord (TypeRecordKind Kind) inline explicit
Definition at line 636 of file TypeRecord.h.
UdtSourceLineRecord() [3/3]
llvm::codeview::UdtSourceLineRecord::UdtSourceLineRecord (TypeIndex UDT, TypeIndex SourceFile, uint32_t LineNumber) inline
Definition at line 637 of file TypeRecord.h.
Member Function Documentation
getLineNumber()
uint32_t llvm::codeview::UdtSourceLineRecord::getLineNumber () const inline
Definition at line 643 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getSourceFile()
TypeIndex llvm::codeview::UdtSourceLineRecord::getSourceFile () const inline
Definition at line 642 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getUDT()
TypeIndex llvm::codeview::UdtSourceLineRecord::getUDT () const inline
Definition at line 641 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
LineNumber
uint32_t llvm::codeview::UdtSourceLineRecord::LineNumber = 0
Definition at line 647 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
SourceFile
TypeIndex llvm::codeview::UdtSourceLineRecord::SourceFile
Definition at line 646 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
UDT
TypeIndex llvm::codeview::UdtSourceLineRecord::UDT
Definition at line 645 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h