LLVM: llvm::codeview::StaticDataMemberRecord Class Reference
llvm::codeview::StaticDataMemberRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
StaticDataMemberRecord ()=default
StaticDataMemberRecord (TypeRecordKind Kind)
StaticDataMemberRecord (MemberAttributes Attrs, TypeIndex Type, StringRef Name)
StaticDataMemberRecord (MemberAccess Access, TypeIndex Type, StringRef Name)
MemberAccess getAccess () const
TypeIndex getType () const
StringRef getName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
MemberAttributes Attrs
TypeIndex Type
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 814 of file TypeRecord.h.
Constructor & Destructor Documentation
StaticDataMemberRecord() [1/4]
llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord () default
StaticDataMemberRecord() [2/4]
llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord (TypeRecordKind Kind) inline explicit
Definition at line 817 of file TypeRecord.h.
StaticDataMemberRecord() [3/4]
llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord (MemberAttributes Attrs, TypeIndex Type, StringRef Name) inline
Definition at line 818 of file TypeRecord.h.
StaticDataMemberRecord() [4/4]
llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord (MemberAccess Access, TypeIndex Type, StringRef Name) inline
Definition at line 821 of file TypeRecord.h.
Member Function Documentation
getAccess()
MemberAccess llvm::codeview::StaticDataMemberRecord::getAccess () const inline
Definition at line 825 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
getName()
StringRef llvm::codeview::StaticDataMemberRecord::getName () const inline
Definition at line 827 of file TypeRecord.h.
References Name.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getType()
TypeIndex llvm::codeview::StaticDataMemberRecord::getType () const inline
Definition at line 826 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
Member Data Documentation
Attrs
MemberAttributes llvm::codeview::StaticDataMemberRecord::Attrs
Definition at line 829 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Name
StringRef llvm::codeview::StaticDataMemberRecord::Name
Definition at line 831 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Type
TypeIndex llvm::codeview::StaticDataMemberRecord::Type
Definition at line 830 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h