LLVM: llvm::MCDwarfLineStr Class Reference
llvm::MCDwarfLineStr Class Reference
Manage the .debug_line_str section contents, if we use it.
Public Member Functions
MCDwarfLineStr (MCContext &Ctx)
Construct an instance that can emit .debug_line_str (for use in a normal v5 line table).
void emitRef (MCStreamer *MCOS, StringRef Path)
Emit a reference to the string.
void emitSection (MCStreamer *MCOS)
Emit the .debug_line_str section if appropriate.
Detailed Description
Manage the .debug_line_str section contents, if we use it.
Definition at line 49 of file MCDwarf.cpp.
Constructor & Destructor Documentation
MCDwarfLineStr()
llvm::MCDwarfLineStr::MCDwarfLineStr (MCContext & Ctx) inline explicit
Construct an instance that can emit .debug_line_str (for use in a normal v5 line table).
Definition at line 57 of file MCDwarf.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), emitRef(), emitSection(), llvm::MCContext::getAsmInfo(), llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfLineStrSection(), and llvm::MCContext::getObjectFileInfo().
Referenced by llvm::MCDwarfLineTable::Emit().
Member Function Documentation
emitRef()
void MCDwarfLineStr::emitRef (MCStreamer * MCOS, StringRef Path)
Emit a reference to the string.
Definition at line 322 of file MCDwarf.cpp.
References llvm::StringTableBuilder::add(), assert(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitULEB128IntValue(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::getContext(), makeStartPlusIntExpr(), and Name.
Referenced by emitOneV5FileEntry(), and MCDwarfLineStr().
emitSection()
void MCDwarfLineStr::emitSection (MCStreamer * MCOS)
Emit the .debug_line_str section if appropriate.
Definition at line 310 of file MCDwarf.cpp.
References llvm::Data, llvm::SmallVectorTemplateCommon< T >::data(), llvm::MCStreamer::EmitBinaryData(), llvm::StringTableBuilder::finalizeInOrder(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfLineStrSection(), llvm::MCContext::getObjectFileInfo(), llvm::StringTableBuilder::getSize(), llvm::SmallVectorImpl< char >::resize(), llvm::SmallString< InternalLen >::str(), llvm::MCStreamer::SwitchSection(), and llvm::StringTableBuilder::write().
Referenced by llvm::MCDwarfLineTable::Emit(), and MCDwarfLineStr().
The documentation for this class was generated from the following file:
lib/MC/MCDwarf.cpp