LLVM: llvm::object::BindRebaseSegInfo Class Reference
llvm::object::BindRebaseSegInfo Class Reference
#include "llvm/Object/MachO.h"
Public Member Functions
BindRebaseSegInfo (const MachOObjectFile *Obj)
const char * checkSegAndOffsets (int32_t SegIndex, uint64_t SegOffset, uint8_t PointerSize, uint32_t Count=1, uint32_t Skip=0)
StringRef segmentName (int32_t SegIndex)
StringRef sectionName (int32_t SegIndex, uint64_t SegOffset)
uint64_t address (uint32_t SegIndex, uint64_t SegOffset)
Detailed Description
Definition at line 131 of file MachO.h.
Constructor & Destructor Documentation
BindRebaseSegInfo()
BindRebaseSegInfo::BindRebaseSegInfo (const MachOObjectFile * Obj)
Definition at line 4000 of file MachOObjectFile.cpp.
References llvm::consumeError(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::hasPageZeroSegment(), Info, llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), and llvm::Expected< T >::takeError().
Member Function Documentation
address()
uint64_t BindRebaseSegInfo::address (uint32_t SegIndex, uint64_t SegOffset)
Definition at line 4101 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::bindTable(), llvm::RISCVFenceField::O, and SI.
checkSegAndOffsets()
const char * BindRebaseSegInfo::checkSegAndOffsets (int32_t SegIndex, uint64_t SegOffset, uint8_t PointerSize, uint32_t Count = 1, uint32_t Skip = 0)
Definition at line 4035 of file MachOObjectFile.cpp.
sectionName()
StringRef BindRebaseSegInfo::sectionName (int32_t SegIndex, uint64_t SegOffset)
Definition at line 4094 of file MachOObjectFile.cpp.
segmentName()
StringRef BindRebaseSegInfo::segmentName (int32_t SegIndex)
Definition at line 4068 of file MachOObjectFile.cpp.
References llvm_unreachable, and SI.
The documentation for this class was generated from the following files:
include/llvm/Object/MachO.h
lib/Object/MachOObjectFile.cpp