LLVM: llvm::FoldingSetNodeIDRef Class Reference
llvm::FoldingSetNodeIDRef Class Reference
FoldingSetNodeIDRef - This class describes a reference to an interned FoldingSetNodeID, which can be a useful to store node id data rather than using plain FoldingSetNodeIDs, since the 32-element SmallVector is often much larger than necessary, and the possibility of heap allocation means it requires a non-trivial destructor call.
#include "llvm/ADT/FoldingSet.h"
Public Member Functions
FoldingSetNodeIDRef ()=default
FoldingSetNodeIDRef (const unsigned *D, size_t S)
unsigned ComputeHash () const
ComputeHash - Compute a strong hash value for this FoldingSetNodeIDRef, used to lookup the node in the FoldingSetBase.
bool operator== (FoldingSetNodeIDRef) const
bool operator!= (FoldingSetNodeIDRef RHS) const
bool operator< (FoldingSetNodeIDRef) const
Used to compare the "ordering" of two nodes as defined by the profiled bits and their ordering defined by memcmp().
const unsigned * getData () const
size_t getSize () const
Detailed Description
FoldingSetNodeIDRef - This class describes a reference to an interned FoldingSetNodeID, which can be a useful to store node id data rather than using plain FoldingSetNodeIDs, since the 32-element SmallVector is often much larger than necessary, and the possibility of heap allocation means it requires a non-trivial destructor call.
Definition at line 277 of file FoldingSet.h.
Constructor & Destructor Documentation
FoldingSetNodeIDRef() [1/2]
llvm::FoldingSetNodeIDRef::FoldingSetNodeIDRef () default
Referenced by llvm::FoldingSetNodeID::ComputeHash(), llvm::FoldingSetNodeID::Intern(), llvm::FoldingSetNodeID::operator<(), and llvm::FoldingSetNodeID::operator==().
FoldingSetNodeIDRef() [2/2]
llvm::FoldingSetNodeIDRef::FoldingSetNodeIDRef (const unsigned * D, size_t S) inline
Definition at line 283 of file FoldingSet.h.
References llvm::IndexedInstrProf::ComputeHash(), and llvm::operator==().
Member Function Documentation
ComputeHash()
unsigned FoldingSetNodeIDRef::ComputeHash () const
ComputeHash - Compute a strong hash value for this FoldingSetNodeIDRef, used to lookup the node in the FoldingSetBase.
Definition at line 29 of file FoldingSet.cpp.
References llvm::hash_combine_range().
Referenced by llvm::FoldingSetTrait< SCEV >::ComputeHash(), llvm::FoldingSetTrait< SCEVPredicate >::ComputeHash(), llvm::FoldingSetNodeID::ComputeHash(), and llvm::SDVTListNode::SDVTListNode().
getData()
const unsigned* llvm::FoldingSetNodeIDRef::getData () const inline
Definition at line 297 of file FoldingSet.h.
References llvm::Data.
getSize()
size_t llvm::FoldingSetNodeIDRef::getSize () const inline
Definition at line 298 of file FoldingSet.h.
References Size.
operator!=()
bool llvm::FoldingSetNodeIDRef::operator!= (FoldingSetNodeIDRef RHS) const inline
Definition at line 291 of file FoldingSet.h.
References llvm::operator<().
operator<()
bool FoldingSetNodeIDRef::operator< (FoldingSetNodeIDRef RHS) const
Used to compare the "ordering" of two nodes as defined by the profiled bits and their ordering defined by memcmp().
Definition at line 40 of file FoldingSet.cpp.
References memcmp.
operator==()
bool FoldingSetNodeIDRef::operator== (FoldingSetNodeIDRef RHS) const
Definition at line 33 of file FoldingSet.cpp.
References memcmp.
The documentation for this class was generated from the following files:
include/llvm/ADT/FoldingSet.h
lib/Support/FoldingSet.cpp