LLVM: llvm::PPCTargetMachine Class Reference
llvm::PPCTargetMachine Class Reference final
Common code between 32-bit and 64-bit PowerPC targets.
#include "Target/PowerPC/PPCTargetMachine.h"
Public Types
enum PPCABI { PPC_ABI_UNKNOWN, PPC_ABI_ELFv1, PPC_ABI_ELFv2 }
Public Member Functions
PPCTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
~PPCTargetMachine () override
const PPCSubtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
const PPCSubtarget * getSubtargetImpl () const =delete
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetTransformInfo getTargetTransformInfo (const Function &F) override
Get a TargetTransformInfo implementation for the target.
TargetLoweringObjectFile * getObjFileLowering () const override
bool isELFv2ABI () const
bool isPPC64 () const
Public Member Functions inherited from llvm::LLVMTargetMachine
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
virtual bool isMachineVerifierClean () const
Returns true if the target is expected to pass all machine verifier checks.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context)
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
virtual bool usesPhysRegsForPEI () const
True if the target uses physical regs at Prolog/Epilog insertion time.
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const Module &M, const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOpt::Level getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOpt::Level Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
bool shouldPrintMachineCode () const
bool getUniqueSectionNames () const
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
TargetIRAnalysis getTargetIRAnalysis ()
Get a TargetIRAnalysis appropriate for the target.
virtual void adjustPassManager (PassManagerBuilder &)
Allow the target to modify the pass manager, e.g.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
Additional Inherited Members
Public Attributes inherited from llvm::TargetMachine
const TargetOptions DefaultOptions
TargetOptions Options
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
CodeGenOpt::Level OptLevel = CodeGenOpt::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
Detailed Description
Common code between 32-bit and 64-bit PowerPC targets.
Definition at line 25 of file PPCTargetMachine.h.
Member Enumeration Documentation
PPCABI
enum llvm::PPCTargetMachine::PPCABI
Enumerator
PPC_ABI_UNKNOWN
PPC_ABI_ELFv1
PPC_ABI_ELFv2
Definition at line 27 of file PPCTargetMachine.h.
Constructor & Destructor Documentation
PPCTargetMachine()
PPCTargetMachine::PPCTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
Definition at line 293 of file PPCTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo(), and ~PPCTargetMachine().
~PPCTargetMachine()
PPCTargetMachine::~PPCTargetMachine () override default
Referenced by PPCTargetMachine().
Member Function Documentation
createPassConfig()
TargetPassConfig * PPCTargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 394 of file PPCTargetMachine.cpp.
References llvm::TargetPassConfig::addIRPasses(), llvm::TargetPassConfig::addMachineSSAOptimization(), llvm::Triple::BGQ, llvm::createAtomicExpandPass(), llvm::createEarlyCSEPass(), llvm::createHardwareLoopsPass(), llvm::createLICMPass(), llvm::createLoopDataPrefetchPass(), llvm::createPPCBoolRetToIntPass(), llvm::createPPCBranchCoalescingPass(), llvm::createPPCBranchSelectionPass(), llvm::createPPCCTRLoopsVerify(), llvm::createPPCEarlyReturnPass(), llvm::createPPCExpandISELPass(), llvm::createPPCISelDag(), llvm::createPPCLoopInstrFormPrepPass(), llvm::createPPCLowerMASSVEntriesPass(), llvm::createPPCMIPeepholePass(), llvm::createPPCPreEmitPeepholePass(), llvm::createPPCQPXLoadSplatPass(), llvm::createPPCReduceCRLogicalsPass(), llvm::createPPCTLSDynamicCallPass(), llvm::createPPCTOCRegDepsPass(), llvm::createPPCVSXCopyPass(), llvm::createPPCVSXSwapRemovalPass(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::DeadMachineInstructionElimID, llvm::CodeGenOpt::Default, DisableCTRLoops, DisableInstrFormPrep, DisableMIPeephole, DisableQPXLoadSplat, DisableVSXSwapRemoval, llvm::EarlyIfConverterID, EnableBranchCoalescing, EnableExtraTOCRegDeps, EnableGEPOpt, EnableMachineCombinerPass, EnablePrefetch, llvm::TargetMachine::getOptLevel(), llvm::PassRegistry::getPassRegistry(), llvm::IfConverterID, llvm::initializePPCVSXFMAMutatePass(), llvm::TargetMachine::isPositionIndependent(), llvm::LiveVariablesID, llvm::MachineCombinerID, llvm::MachinePipelinerID, llvm::MachineSchedulerID, llvm::CodeGenOpt::None, llvm::Triple::ppc64le, llvm::PPCVSXFMAMutateID, ReduceCRLogical, llvm::RegisterCoalescerID, llvm::SystemZISD::TM, and VSXFMAMutateEarly.
getObjFileLowering()
TargetLoweringObjectFile* llvm::PPCTargetMachine::getObjFileLowering () const inline override virtual
Reimplemented from llvm::TargetMachine.
Definition at line 53 of file PPCTargetMachine.h.
getSubtargetImpl() [1/2]
const PPCSubtarget * PPCTargetMachine::getSubtargetImpl (const Function &) const override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 311 of file PPCTargetMachine.cpp.
References C, computeFSAdditions(), createPPCMachineScheduler(), createPPCPostMachineScheduler(), llvm::StringRef::empty(), llvm::X86AS::FS, llvm::Function::getFnAttribute(), llvm::TargetMachine::getOptLevel(), llvm::TargetMachine::getTargetTriple(), llvm::Attribute::getValueAsString(), llvm::Attribute::hasAttribute(), I, llvm::CodeGenOpt::None, llvm::Attribute::None, llvm::PostMachineSchedulerID, llvm::PostRASchedulerID, llvm::TargetMachine::resetTargetOptions(), llvm::StringRef::str(), llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, llvm::TargetMachine::TargetTriple, and llvm::SystemZISD::TM.
getSubtargetImpl() [2/2]
const PPCSubtarget* llvm::PPCTargetMachine::getSubtargetImpl () const delete
getTargetTransformInfo()
TargetTransformInfo PPCTargetMachine::getTargetTransformInfo (const Function & F) override virtual
Get a TargetTransformInfo implementation for the target.
The TTI returned uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 531 of file PPCTargetMachine.cpp.
References createPPCMachineScheduler(), createPPCPostMachineScheduler(), PPCPostRASchedRegistry, and PPCPreRASchedRegistry.
isELFv2ABI()
bool llvm::PPCTargetMachine::isELFv2ABI () const inline
Definition at line 56 of file PPCTargetMachine.h.
References PPC_ABI_ELFv2.
Referenced by llvm::PPCRegisterInfo::getLargestLegalSuperClass(), and llvm::PPCSubtarget::isELFv2ABI().
isPPC64()
bool llvm::PPCTargetMachine::isPPC64 () const inline
Definition at line 57 of file PPCTargetMachine.h.
References llvm::Triple::getArch(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::ppc64, and llvm::Triple::ppc64le.
Referenced by llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getFrameRegister(), llvm::PPCRegisterInfo::getPointerRegClass(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCTTIImpl::getUserCost(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::PPCSubtarget::isPPC64(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), and selectI64Imm().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCTargetMachine.h
lib/Target/PowerPC/PPCTargetMachine.cpp