LLVM: llvm::StringSwitch< T, R > Class Template Reference
llvm::StringSwitch< T, R > Class Template Reference
A switch()-like statement whose cases are string literals.
#include "llvm/ADT/StringSwitch.h"
Public Member Functions
StringSwitch (StringRef S)
StringSwitch (const StringSwitch &)=delete
void operator= (const StringSwitch &)=delete
void operator= (StringSwitch &&other)=delete
StringSwitch (StringSwitch &&other)
~StringSwitch ()=default
StringSwitch & Case (StringLiteral S, T Value)
StringSwitch & EndsWith (StringLiteral S, T Value)
StringSwitch & StartsWith (StringLiteral S, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, StringLiteral S9, T Value)
StringSwitch & CaseLower (StringLiteral S, T Value)
StringSwitch & EndsWithLower (StringLiteral S, T Value)
StringSwitch & StartsWithLower (StringLiteral S, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value)
LLVM_NODISCARD R Default (T Value)
LLVM_NODISCARD operator R ()
Detailed Description
template<typename T, typename R = T>
class llvm::StringSwitch< T, R >
A switch()-like statement whose cases are string literals.
The StringSwitch class is a simple form of a switch() statement that determines whether the given string matches one of the given string literals. The template type parameter T is the type of the value that will be returned from the string-switch expression. For example, the following code switches on the name of a color in argv[i]:
Color color = StringSwitch<Color>(argv[i])
  .Case("red", Red)
  .Case("orange", Orange)
  .Case("yellow", Yellow)
  .Case("green", Green)
  .Case("blue", Blue)
  .Case("indigo", Indigo)
  .Cases("violet", "purple", Violet)
  .Default(UnknownColor);
Definition at line 42 of file StringSwitch.h.
Constructor & Destructor Documentation
StringSwitch() [1/3]
template<typename T , typename R = T> llvm::StringSwitch< T, R >::StringSwitch (StringRef S) inline explicit
Definition at line 51 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::operator=().
StringSwitch() [2/3]
template<typename T , typename R = T> llvm::StringSwitch< T, R >::StringSwitch (const StringSwitch< T, R > &) delete
StringSwitch() [3/3]
template<typename T , typename R = T> llvm::StringSwitch< T, R >::StringSwitch (StringSwitch< T, R > && other) inline
Definition at line 61 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::~StringSwitch().
~StringSwitch()
template<typename T , typename R = T> llvm::StringSwitch< T, R >::~StringSwitch () default
Referenced by llvm::StringSwitch< T, R >::StringSwitch().
Member Function Documentation
Case()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Case (StringLiteral S, T Value) inline
Definition at line 67 of file StringSwitch.h.
Referenced by llvm::AArch64StringToVectorLayout(), llvm::ARMCondCodeFromString(), llvm::ARMVectorCondCodeFromString(), llvm::StringSwitch< T, R >::Cases(), checkParametrizedPassName(), llvm::classifyEHPersonality(), llvm::MachO::Target::create(), llvm::DWARFContext::defaultErrorHandler(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::MipsSEFrameLowering::emitPrologue(), encodeCnt(), llvm::ARM::getArchSynonym(), llvm::Triple::getArchTypeForLLVMName(), getARClassRegisterMask(), llvm::DIFile::getChecksumKind(), llvm::DICompileUnit::getEmissionKind(), getEmulation(), llvm::MipsAsmBackend::getFixupKind(), getFixupKindSize(), llvm::ARM::getFPUSynonym(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForPowerPC(), llvm::sys::getHostNumPhysicalCores(), getIdentifierKind(), llvm::TGLexer::getLoc(), llvm::getMachineType(), llvm::dwarf::getMacinfo(), getMClassFlagsMask(), getMetadataKeywordKind(), llvm::DICompileUnit::getNameTableKind(), getOSTypeFromPlatform(), llvm::ConstrainedFPCmpIntrinsic::getPredicate(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::VETargetLowering::getRegisterByName(), llvm::LanaiTargetLowering::getRegisterByName(), llvm::SparcTargetLowering::getRegisterByName(), llvm::AVRTargetLowering::getRegisterByName(), llvm::HexagonTargetLowering::getRegisterByName(), llvm::SITargetLowering::getRegisterByName(), llvm::PPCTargetLowering::getRegisterByName(), llvm::X86TargetLowering::getRegisterByName(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), getSpecialRegForName(), llvm::RISCVABI::getTargetABI(), llvm::RISCVMCExpr::getVariantKindForName(), llvm::VFABI::getVFParamKindFromString(), llvm::object::WasmObjectFile::getWasmRelocation(), llvm::yaml::ScalarTraits< ELFArchMapper >::input(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), insertNoDuplicates(), isRegOrImmWithInputMods(), MCAttrForString(), llvm::yaml::ScalarTraits< FlowStringRef >::mustQuote(), parseArch(), parseAttrKind(), llvm::parseDenormalFPAttribute(), llvm::remarks::parseFormat(), parseGlobalValue(), parseIRValue(), parseNamePrefix(), llvm::SparcMCExpr::parseVariantKind(), parseVendor(), llvm::SymbolRemappingReader::read(), RefineErrorLoc(), llvm::LPAC::stringToLanaiAluCode(), llvm::RISCVFPRndMode::stringToRoundingMode(), llvm::StrToExceptionBehavior(), llvm::StrToRoundingMode(), and UpgradeIntrinsicFunction1().
CaseLower()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CaseLower (StringLiteral S, T Value) inline
Definition at line 140 of file StringSwitch.h.
References llvm::StringRef::equals_lower().
Referenced by llvm::StringSwitch< T, R >::CasesLower().
Cases() [1/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, T Value) inline
Definition at line 88 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case().
Referenced by llvm::StringSwitch< T, R >::Cases(), llvm::ARM::getArchSynonym(), llvm::ARM::getFPUSynonym(), llvm::getMachineType(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), isValidAIXExternalSymSDNode(), MCAttrForString(), parseArch(), RefineErrorLoc(), llvm::Triple::Triple(), and UpgradeIntrinsicFunction1().
Cases() [2/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value) inline
Definition at line 92 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [3/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value) inline
Definition at line 97 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [4/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value) inline
Definition at line 102 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [5/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, T Value) inline
Definition at line 107 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [6/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, T Value) inline
Definition at line 113 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [7/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, T Value) inline
Definition at line 119 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [8/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, T Value) inline
Definition at line 125 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [9/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, StringLiteral S9, T Value) inline
Definition at line 132 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
CasesLower() [1/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, T Value) inline
Definition at line 161 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower().
Referenced by llvm::StringSwitch< T, R >::CasesLower().
CasesLower() [2/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value) inline
Definition at line 165 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower(), and llvm::StringSwitch< T, R >::CasesLower().
CasesLower() [3/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value) inline
Definition at line 170 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower(), and llvm::StringSwitch< T, R >::CasesLower().
CasesLower() [4/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value) inline
Definition at line 175 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower(), llvm::StringSwitch< T, R >::CasesLower(), and LLVM_NODISCARD.
Default()
template<typename T , typename R = T> LLVM_NODISCARD R llvm::StringSwitch< T, R >::Default (T Value) inline
Definition at line 181 of file StringSwitch.h.
References LLVM_NODISCARD.
Referenced by llvm::AArch64StringToVectorLayout(), llvm::ARMCondCodeFromString(), llvm::ARMVectorCondCodeFromString(), checkParametrizedPassName(), llvm::classifyEHPersonality(), llvm::MachO::Target::create(), llvm::createX86_64AsmBackend(), llvm::DWARFContext::defaultErrorHandler(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::MipsSEFrameLowering::emitPrologue(), encodeCnt(), llvm::ARM::getArchSynonym(), llvm::Triple::getArchTypeForLLVMName(), getARClassRegisterMask(), llvm::DIFile::getChecksumKind(), llvm::DICompileUnit::getEmissionKind(), getEmulation(), llvm::MipsAsmBackend::getFixupKind(), getFixupKindSize(), llvm::ARM::getFPUSynonym(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForPowerPC(), llvm::sys::getHostNumPhysicalCores(), getHWDivSynonym(), getIdentifierKind(), llvm::TGLexer::getLoc(), llvm::getMachineType(), llvm::dwarf::getMacinfo(), getMClassFlagsMask(), getMetadataKeywordKind(), llvm::DICompileUnit::getNameTableKind(), getOSTypeFromPlatform(), llvm::ConstrainedFPCmpIntrinsic::getPredicate(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::VETargetLowering::getRegisterByName(), llvm::LanaiTargetLowering::getRegisterByName(), llvm::SparcTargetLowering::getRegisterByName(), llvm::AVRTargetLowering::getRegisterByName(), llvm::HexagonTargetLowering::getRegisterByName(), llvm::SITargetLowering::getRegisterByName(), llvm::MipsTargetLowering::getRegisterByName(), llvm::PPCTargetLowering::getRegisterByName(), llvm::X86TargetLowering::getRegisterByName(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), getSpecialRegForName(), llvm::RISCVABI::getTargetABI(), llvm::RISCVMCExpr::getVariantKindForName(), llvm::VFABI::getVFParamKindFromString(), llvm::object::WasmObjectFile::getWasmRelocation(), llvm::yaml::ScalarTraits< ELFArchMapper >::input(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), insertNoDuplicates(), isRegOrImmWithInputMods(), isValidAIXExternalSymSDNode(), LowerVectorINT_TO_FP(), llvm::remarks::magicToFormat(), llvm::object::MachOObjectFile::mapDebugSectionName(), llvm::object::COFFObjectFile::mapDebugSectionName(), MaybePredicatedInst(), MCAttrForString(), llvm::yaml::ScalarTraits< FlowStringRef >::mustQuote(), parseArch(), llvm::ARM::parseArchISA(), parseAttrKind(), llvm::parseDenormalFPAttribute(), parseEnvironment(), llvm::remarks::parseFormat(), parseFormat(), parseGlobalValue(), parseIRValue(), parseNamePrefix(), parseOS(), parseSubArch(), llvm::SparcMCExpr::parseVariantKind(), parseVendor(), llvm::SymbolRemappingReader::read(), RefineErrorLoc(), SizeForSuffix(), llvm::LPAC::stringToLanaiAluCode(), llvm::RISCVFPRndMode::stringToRoundingMode(), llvm::StrToExceptionBehavior(), llvm::StrToRoundingMode(), llvm::LPCC::suffixToLanaiCondCode(), llvm::Triple::Triple(), and UpgradeIntrinsicFunction1().
EndsWith()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::EndsWith (StringLiteral S, T Value) inline
Definition at line 74 of file StringSwitch.h.
References llvm::StringRef::endswith().
Referenced by parseFormat(), parseSubArch(), SizeForSuffix(), and llvm::LPCC::suffixToLanaiCondCode().
EndsWithLower()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::EndsWithLower (StringLiteral S, T Value) inline
Definition at line 147 of file StringSwitch.h.
References llvm::StringRef::endswith_lower().
operator R()
template<typename T , typename R = T> LLVM_NODISCARD llvm::StringSwitch< T, R >::operator R () inline
Definition at line 188 of file StringSwitch.h.
References assert().
operator=() [1/2]
template<typename T , typename R = T> void llvm::StringSwitch< T, R >::operator= (const StringSwitch< T, R > &) delete
Referenced by llvm::StringSwitch< T, R >::StringSwitch().
operator=() [2/2]
template<typename T , typename R = T> void llvm::StringSwitch< T, R >::operator= (StringSwitch< T, R > && other) delete
StartsWith()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::StartsWith (StringLiteral S, T Value) inline
Definition at line 81 of file StringSwitch.h.
References llvm::StringRef::startswith().
Referenced by llvm::Triple::getArchTypeForLLVMName(), llvm::object::WasmObjectFile::getWasmRelocation(), llvm::remarks::magicToFormat(), MaybePredicatedInst(), parseArch(), llvm::ARM::parseArchISA(), parseEnvironment(), parseOS(), llvm::Triple::Triple(), and UpgradeIntrinsicFunction1().
StartsWithLower()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::StartsWithLower (StringLiteral S, T Value) inline
Definition at line 154 of file StringSwitch.h.
References llvm::StringRef::startswith_lower().
The documentation for this class was generated from the following file:
include/llvm/ADT/StringSwitch.h