LLVM: llvm::SimpleBitstreamCursor Class Reference
llvm::SimpleBitstreamCursor Class Reference
This represents a position within a bitstream.
#include "llvm/Bitstream/BitstreamReader.h"
Public Types
using word_t = size_t
This is the current data we have pulled from the stream but have not returned to the client.
Public Member Functions
SimpleBitstreamCursor ()=default
SimpleBitstreamCursor (ArrayRef< uint8_t > BitcodeBytes)
SimpleBitstreamCursor (StringRef BitcodeBytes)
SimpleBitstreamCursor (MemoryBufferRef BitcodeBytes)
bool canSkipToPos (size_t pos) const
bool AtEndOfStream ()
uint64_t GetCurrentBitNo () const
Return the bit # of the bit we are reading.
uint64_t getCurrentByteNo () const
ArrayRef< uint8_t > getBitcodeBytes () const
Error JumpToBit (uint64_t BitNo)
Reset the stream to the specified bit number.
const uint8_t * getPointerToByte (uint64_t ByteNo, uint64_t NumBytes)
Get a pointer into the bitstream at the specified byte offset.
const uint8_t * getPointerToBit (uint64_t BitNo, uint64_t NumBytes)
Get a pointer into the bitstream at the specified bit offset.
Error fillCurWord ()
Expected< word_t > Read (unsigned NumBits)
Expected< uint32_t > ReadVBR (unsigned NumBits)
Expected< uint64_t > ReadVBR64 (unsigned NumBits)
void SkipToFourByteBoundary ()
size_t SizeInBytes () const
Return the size of the stream in bytes.
void skipToEnd ()
Skip to the end of the file.
Static Public Attributes
static const constexpr size_t MaxChunkSize = sizeof(word_t) * 8
Detailed Description
This represents a position within a bitstream.
There may be multiple independent cursors reading within one bitstream, each maintaining their own local state.
Definition at line 80 of file BitstreamReader.h.
Member Typedef Documentation
word_t
using llvm::SimpleBitstreamCursor::word_t = size_t
This is the current data we have pulled from the stream but have not returned to the client.
This is specifically and intentionally defined to follow the word size of the host machine for efficiency. We use word_t in places that are aware of this to make it perfectly explicit what is going on.
Definition at line 90 of file BitstreamReader.h.
Constructor & Destructor Documentation
SimpleBitstreamCursor() [1/4]
llvm::SimpleBitstreamCursor::SimpleBitstreamCursor () default
SimpleBitstreamCursor() [2/4]
llvm::SimpleBitstreamCursor::SimpleBitstreamCursor (ArrayRef< uint8_t > BitcodeBytes) inline explicit
Definition at line 103 of file BitstreamReader.h.
SimpleBitstreamCursor() [3/4]
llvm::SimpleBitstreamCursor::SimpleBitstreamCursor (StringRef BitcodeBytes) inline explicit
Definition at line 105 of file BitstreamReader.h.
SimpleBitstreamCursor() [4/4]
llvm::SimpleBitstreamCursor::SimpleBitstreamCursor (MemoryBufferRef BitcodeBytes) inline explicit
Definition at line 107 of file BitstreamReader.h.
Member Function Documentation
AtEndOfStream()
bool llvm::SimpleBitstreamCursor::AtEndOfStream () inline
Definition at line 115 of file BitstreamReader.h.
References llvm::ArrayRef< T >::size().
Referenced by llvm::BitcodeAnalyzer::analyze(), llvm::remarks::BitstreamParserHelper::atEndOfStream(), llvm::BitstreamCursor::BitstreamCursor(), llvm::BitstreamCursor::EnterSubBlock(), parseBlock(), and readIdentificationCode().
canSkipToPos()
bool llvm::SimpleBitstreamCursor::canSkipToPos (size_t pos) const inline
Definition at line 110 of file BitstreamReader.h.
References llvm::ArrayRef< T >::size().
Referenced by llvm::BitstreamCursor::BitstreamCursor(), hasInvalidBitcodeHeader(), and llvm::BitstreamCursor::readRecord().
fillCurWord()
Error llvm::SimpleBitstreamCursor::fillCurWord () inline
Definition at line 163 of file BitstreamReader.h.
References B, llvm::createStringError(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::size(), and llvm::Error::success().
Referenced by llvm::BitstreamCursor::BitstreamCursor().
getBitcodeBytes()
ArrayRef<uint8_t> llvm::SimpleBitstreamCursor::getBitcodeBytes () const inline
Definition at line 127 of file BitstreamReader.h.
Referenced by analyzeHeader(), llvm::BitstreamCursor::BitstreamCursor(), llvm::getBitcodeFileContents(), and llvm::BitcodeAnalyzer::printStats().
GetCurrentBitNo()
uint64_t llvm::SimpleBitstreamCursor::GetCurrentBitNo () const inline
Return the bit # of the bit we are reading.
Definition at line 120 of file BitstreamReader.h.
Referenced by llvm::BitstreamCursor::BitstreamCursor(), llvm::getBitcodeFileContents(), isBlock(), jumpToValueSymbolTable(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::BitcodeAnalyzer::printStats(), llvm::BitstreamCursor::readRecord(), and llvm::MetadataLoader::MetadataLoaderImpl::upgradeDebugIntrinsics().
getCurrentByteNo()
uint64_t llvm::SimpleBitstreamCursor::getCurrentByteNo () const inline
Definition at line 125 of file BitstreamReader.h.
Referenced by llvm::BitstreamCursor::BitstreamCursor(), and llvm::getBitcodeFileContents().
getPointerToBit()
const uint8_t* llvm::SimpleBitstreamCursor::getPointerToBit (uint64_t BitNo, uint64_t NumBytes) inline
Get a pointer into the bitstream at the specified bit offset.
The bit offset must be on a byte boundary.
Definition at line 158 of file BitstreamReader.h.
References assert().
getPointerToByte()
const uint8_t* llvm::SimpleBitstreamCursor::getPointerToByte (uint64_t ByteNo, uint64_t NumBytes) inline
Get a pointer into the bitstream at the specified byte offset.
Definition at line 151 of file BitstreamReader.h.
References llvm::ArrayRef< T >::data().
Referenced by llvm::BitstreamCursor::BitstreamCursor().
JumpToBit()
Error llvm::SimpleBitstreamCursor::JumpToBit (uint64_t BitNo) inline
Reset the stream to the specified bit number.
Definition at line 130 of file BitstreamReader.h.
References assert(), and llvm::Error::success().
Referenced by llvm::BitstreamCursor::BitstreamCursor(), llvm::BitcodeModule::getLTOInfo(), llvm::BitcodeModule::getSummary(), isBlock(), jumpToValueSymbolTable(), and llvm::BitcodeModule::readSummary().
Read()
Expected<word_t> llvm::SimpleBitstreamCursor::Read (unsigned NumBits) inline
Definition at line 189 of file BitstreamReader.h.
References assert(), llvm::createStringError(), llvm::BitmaskEnumDetail::Mask(), and R2.
Referenced by llvm::BitstreamCursor::BitstreamCursor(), llvm::BitstreamCursor::EnterSubBlock(), hasInvalidBitcodeHeader(), llvm::remarks::BitstreamParserHelper::parseMagic(), readAbbreviatedField(), llvm::BitstreamCursor::ReadAbbrevRecord(), llvm::BitstreamCursor::readRecord(), and ReadSignature().
ReadVBR()
Expected<uint32_t> llvm::SimpleBitstreamCursor::ReadVBR (unsigned NumBits) inline
Definition at line 232 of file BitstreamReader.h.
References llvm::Expected< T >::get().
Referenced by llvm::BitstreamCursor::BitstreamCursor(), llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamCursor::ReadAbbrevRecord(), llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
ReadVBR64()
Expected<uint64_t> llvm::SimpleBitstreamCursor::ReadVBR64 (unsigned NumBits) inline
Definition at line 259 of file BitstreamReader.h.
References llvm::Expected< T >::get().
Referenced by llvm::BitstreamCursor::BitstreamCursor(), readAbbreviatedField(), llvm::BitstreamCursor::ReadAbbrevRecord(), llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
SizeInBytes()
size_t llvm::SimpleBitstreamCursor::SizeInBytes () const inline
Return the size of the stream in bytes.
Definition at line 298 of file BitstreamReader.h.
References llvm::ArrayRef< T >::size().
Referenced by llvm::BitstreamCursor::BitstreamCursor().
skipToEnd()
void llvm::SimpleBitstreamCursor::skipToEnd () inline
Skip to the end of the file.
Definition at line 301 of file BitstreamReader.h.
References llvm::ArrayRef< T >::size().
Referenced by llvm::BitstreamCursor::BitstreamCursor(), llvm::BitstreamCursor::readRecord(), and llvm::remarks::BitstreamParserHelper::skipToEnd().
SkipToFourByteBoundary()
void llvm::SimpleBitstreamCursor::SkipToFourByteBoundary () inline
Definition at line 284 of file BitstreamReader.h.
Referenced by llvm::BitstreamCursor::EnterSubBlock(), and llvm::BitstreamCursor::readRecord().
Member Data Documentation
MaxChunkSize
const constexpr size_t llvm::SimpleBitstreamCursor::MaxChunkSize = sizeof(word_t) * 8 static
Definition at line 100 of file BitstreamReader.h.
The documentation for this class was generated from the following file:
include/llvm/Bitstream/BitstreamReader.h