LLVM: llvm::HexagonMCCodeEmitter Class Reference
llvm::HexagonMCCodeEmitter Class Reference
#include "Target/Hexagon/MCTargetDesc/HexagonMCCodeEmitter.h"
Public Member Functions
HexagonMCCodeEmitter (MCInstrInfo const &MII, MCContext &MCT)
void encodeInstruction (MCInst const &MI, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups, MCSubtargetInfo const &STI) const override
Emit the bundle.
void EncodeSingleInstruction (const MCInst &MI, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI, uint32_t Parse) const
EncodeSingleInstruction - Emit a single.
uint64_t getBinaryCodeForInstr (MCInst const &MI, SmallVectorImpl< MCFixup > &Fixups, MCSubtargetInfo const &STI) const
unsigned getMachineOpValue (MCInst const &MI, MCOperand const &MO, SmallVectorImpl< MCFixup > &Fixups, MCSubtargetInfo const &STI) const
Return binary encoding of operand.
Public Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter (const MCCodeEmitter &)=delete
MCCodeEmitter & operator= (const MCCodeEmitter &)=delete
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
virtual void emitPrefix (const MCInst &Inst, raw_ostream &OS, const MCSubtargetInfo &STI) const
Emit the prefixes of given instruction on the output stream.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Detailed Description
Definition at line 34 of file HexagonMCCodeEmitter.h.
Constructor & Destructor Documentation
HexagonMCCodeEmitter()
llvm::HexagonMCCodeEmitter::HexagonMCCodeEmitter (MCInstrInfo const & MII, MCContext & MCT) inline
Definition at line 49 of file HexagonMCCodeEmitter.h.
References encodeInstruction(), EncodeSingleInstruction(), getBinaryCodeForInstr(), getMachineOpValue(), and MI.
Member Function Documentation
encodeInstruction()
void HexagonMCCodeEmitter::encodeInstruction (MCInst const & MI, raw_ostream & OS, SmallVectorImpl< MCFixup > & Fixups, MCSubtargetInfo const & STI) const override virtual
Emit the bundle.
Implements llvm::MCCodeEmitter.
Definition at line 367 of file HexagonMCCodeEmitter.cpp.
References assert(), llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::HexagonMCInstrInfo::bundleSize(), llvm::dbgs(), llvm::MCSubtargetInfo::getFeatureBits(), HEXAGON_INSTR_SIZE, I, llvm::HexagonMCInstrInfo::isBundle(), llvm::HexagonMCInstrInfo::isImmext(), LLVM_DEBUG, and MI.
Referenced by HexagonMCCodeEmitter().
EncodeSingleInstruction()
void HexagonMCCodeEmitter::EncodeSingleInstruction (const MCInst & MI, raw_ostream & OS, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI, uint32_t Parse) const
EncodeSingleInstruction - Emit a single.
Definition at line 406 of file HexagonMCCodeEmitter.cpp.
References assert(), llvm::dbgs(), llvm::HexagonMCInstrInfo::getDesc(), llvm::MCOperand::getInst(), llvm::HexagonMCInstrInfo::getName(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::HexagonII::INST_PARSE_DUPLEX, llvm::HexagonMCInstrInfo::isBundle(), llvm::support::little, LLVM_ATTRIBUTE_NORETURN, LLVM_DEBUG, and llvm_unreachable.
Referenced by HexagonMCCodeEmitter().
getBinaryCodeForInstr()
uint64_t llvm::HexagonMCCodeEmitter::getBinaryCodeForInstr (MCInst const & MI, SmallVectorImpl< MCFixup > & Fixups, MCSubtargetInfo const & STI) const
Referenced by HexagonMCCodeEmitter().
getMachineOpValue()
unsigned HexagonMCCodeEmitter::getMachineOpValue (MCInst const & MI, MCOperand const & MO, SmallVectorImpl< MCFixup > & Fixups, MCSubtargetInfo const & STI) const
Return binary encoding of operand.
Definition at line 719 of file HexagonMCCodeEmitter.cpp.
References assert(), llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::HexagonMCInstrInfo::getDuplexRegisterNumbering(), llvm::MCOperand::getExpr(), llvm::MCOperand::getInst(), llvm::HexagonMCInstrInfo::getNewValueOperand(), llvm::HexagonMCInstrInfo::getNewValueOperand2(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::HexagonMCInstrInfo::getType(), llvm::HexagonMCInstrInfo::hasNewValue(), llvm::HexagonMCInstrInfo::hasNewValue2(), I, llvm::MCOperand::isImm(), llvm::HexagonMCInstrInfo::isImmext(), llvm::HexagonMCInstrInfo::isNewValue(), llvm::HexagonMCInstrInfo::isPredicated(), llvm::HexagonMCInstrInfo::isPredicatedTrue(), llvm::MCOperand::isReg(), llvm::HexagonMCInstrInfo::isSubInstruction(), llvm::HexagonMCInstrInfo::isVector(), Reg, RegisterMatches(), llvm::HexagonMCInstrInfo::SubregisterBit(), llvm::HexagonII::TypeCJ, and UseReg().
Referenced by HexagonMCCodeEmitter().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonMCCodeEmitter.h
lib/Target/Hexagon/MCTargetDesc/HexagonMCCodeEmitter.cpp