LLVM: llvm::codeview::UdtModSourceLineRecord Class Reference
llvm::codeview::UdtModSourceLineRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
UdtModSourceLineRecord ()=default
UdtModSourceLineRecord (TypeRecordKind Kind)
UdtModSourceLineRecord (TypeIndex UDT, TypeIndex SourceFile, uint32_t LineNumber, uint16_t Module)
TypeIndex getUDT () const
TypeIndex getSourceFile () const
uint32_t getLineNumber () const
uint16_t getModule () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex UDT
TypeIndex SourceFile
uint32_t LineNumber = 0
uint16_t Module = 0
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 651 of file TypeRecord.h.
Constructor & Destructor Documentation
UdtModSourceLineRecord() [1/3]
llvm::codeview::UdtModSourceLineRecord::UdtModSourceLineRecord () default
UdtModSourceLineRecord() [2/3]
llvm::codeview::UdtModSourceLineRecord::UdtModSourceLineRecord (TypeRecordKind Kind) inline explicit
Definition at line 654 of file TypeRecord.h.
UdtModSourceLineRecord() [3/3]
llvm::codeview::UdtModSourceLineRecord::UdtModSourceLineRecord (TypeIndex UDT, TypeIndex SourceFile, uint32_t LineNumber, uint16_t Module) inline
Definition at line 655 of file TypeRecord.h.
Member Function Documentation
getLineNumber()
uint32_t llvm::codeview::UdtModSourceLineRecord::getLineNumber () const inline
Definition at line 662 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getModule()
uint16_t llvm::codeview::UdtModSourceLineRecord::getModule () const inline
Definition at line 663 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getSourceFile()
TypeIndex llvm::codeview::UdtModSourceLineRecord::getSourceFile () const inline
Definition at line 661 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getUDT()
TypeIndex llvm::codeview::UdtModSourceLineRecord::getUDT () const inline
Definition at line 660 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
LineNumber
uint32_t llvm::codeview::UdtModSourceLineRecord::LineNumber = 0
Definition at line 667 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Module
uint16_t llvm::codeview::UdtModSourceLineRecord::Module = 0
Definition at line 668 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
SourceFile
TypeIndex llvm::codeview::UdtModSourceLineRecord::SourceFile
Definition at line 666 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
UDT
TypeIndex llvm::codeview::UdtModSourceLineRecord::UDT
Definition at line 665 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h