LLVM: llvm::TargetSubtargetInfo Class Reference
llvm::TargetSubtargetInfo Class Reference
TargetSubtargetInfo - Generic base class for all target subtargets.
#include "llvm/CodeGen/TargetSubtargetInfo.h"
Public Types
using AntiDepBreakMode = enum { ANTIDEP_NONE, ANTIDEP_CRITICAL, ANTIDEP_ALL }
using RegClassVector = SmallVectorImpl< const TargetRegisterClass * >
Public Member Functions
TargetSubtargetInfo ()=delete
TargetSubtargetInfo (const TargetSubtargetInfo &)=delete
TargetSubtargetInfo & operator= (const TargetSubtargetInfo &)=delete
~TargetSubtargetInfo () override
virtual bool isXRaySupported () const
virtual const TargetInstrInfo * getInstrInfo () const
virtual const TargetFrameLowering * getFrameLowering () const
virtual const TargetLowering * getTargetLowering () const
virtual const SelectionDAGTargetInfo * getSelectionDAGInfo () const
virtual const CallLowering * getCallLowering () const
virtual InstructionSelector * getInstructionSelector () const
virtual RegisterScheduler::FunctionPassCtor getDAGScheduler (CodeGenOpt::Level) const
Target can subclass this hook to select a different DAG scheduler.
virtual const LegalizerInfo * getLegalizerInfo () const
virtual const TargetRegisterInfo * getRegisterInfo () const
getRegisterInfo - If register information is available, return it.
virtual const RegisterBankInfo * getRegBankInfo () const
If the information for the register banks is available, return it.
virtual const InstrItineraryData * getInstrItineraryData () const
getInstrItineraryData - Returns instruction itinerary data for the target or specific subtarget.
virtual unsigned resolveSchedClass (unsigned SchedClass, const MachineInstr *MI, const TargetSchedModel *SchedModel) const
Resolve a SchedClass at runtime, where SchedClass identifies an MCSchedClassDesc with the isVariant property.
virtual bool isZeroIdiom (const MachineInstr *MI, APInt &Mask) const
Returns true if MI is a dependency breaking zero-idiom instruction for the subtarget.
virtual bool isDependencyBreaking (const MachineInstr *MI, APInt &Mask) const
Returns true if MI is a dependency breaking instruction for the subtarget.
virtual bool isOptimizableRegisterMove (const MachineInstr *MI) const
Returns true if MI is a candidate for move elimination.
virtual bool enableMachineScheduler () const
True if the subtarget should run MachineScheduler after aggressive coalescing.
virtual bool enableMachineSchedDefaultSched () const
True if the machine scheduler should disable the TLI preference for preRA scheduling with the source level scheduler.
virtual bool enableMachinePipeliner () const
True if the subtarget should run MachinePipeliner.
virtual bool enableJoinGlobalCopies () const
True if the subtarget should enable joining global copies.
virtual bool enablePostRAScheduler () const
True if the subtarget should run a scheduler after register allocation.
virtual bool enablePostRAMachineScheduler () const
True if the subtarget should run a machine scheduler after register allocation.
virtual bool enableAtomicExpand () const
True if the subtarget should run the atomic expansion pass.
virtual bool enableIndirectBrExpand () const
True if the subtarget should run the indirectbr expansion pass.
virtual void overrideSchedPolicy (MachineSchedPolicy &Policy, unsigned NumRegionInstrs) const
Override generic scheduling policy within a region.
virtual void adjustSchedDependency (SUnit *def, SUnit *use, SDep &dep) const
virtual AntiDepBreakMode getAntiDepBreakMode () const
virtual void getCriticalPathRCs (RegClassVector &CriticalPathRCs) const
virtual void getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> &Mutations) const
virtual void getSMSMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> &Mutations) const
virtual bool useDFAforSMS () const
Default to DFA for resource management, return false when target will use ProcResource in InstrSchedModel instead.
virtual CodeGenOpt::Level getOptLevelToEnablePostRAScheduler () const
virtual bool enableRALocalReassignment (CodeGenOpt::Level OptLevel) const
True if the subtarget should run the local reassignment heuristic of the register allocator.
virtual bool enableAdvancedRASplitCost () const
True if the subtarget should consider the cost of local intervals created by a split candidate when choosing the best split candidate.
virtual bool useAA () const
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
virtual bool addrSinkUsingGEPs () const
Sink addresses into blocks using GEP instructions rather than pointer casts and arithmetic.
virtual bool enableEarlyIfConversion () const
Enable the use of the early if conversion pass.
virtual std::unique_ptr< PBQPRAConstraint > getCustomPBQPConstraints () const
Return PBQPConstraint(s) for the target.
virtual bool enableSubRegLiveness () const
Enable tracking of subregister liveness in register allocator.
virtual void mirFileLoaded (MachineFunction &MF) const
This is called after a .mir file was loaded.
virtual bool ignoreCSRForAllocationOrder (const MachineFunction &MF, unsigned PhysReg) const
True if the register allocator should use the allocation orders exactly as written in the tablegen descriptions, false if it should allocate the specified physical register later if is it callee-saved.
Public Member Functions inherited from llvm::MCSubtargetInfo
MCSubtargetInfo (const MCSubtargetInfo &)=default
MCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetSubTypeKV > PD, const MCWriteProcResEntry *WPR, const MCWriteLatencyEntry *WL, const MCReadAdvanceEntry *RA, const InstrStage *IS, const unsigned *OC, const unsigned *FP)
MCSubtargetInfo ()=delete
MCSubtargetInfo & operator= (const MCSubtargetInfo &)=delete
MCSubtargetInfo & operator= (MCSubtargetInfo &&)=delete
virtual ~MCSubtargetInfo ()=default
const Triple & getTargetTriple () const
StringRef getCPU () const
const FeatureBitset & getFeatureBits () const
void setFeatureBits (const FeatureBitset &FeatureBits_)
bool hasFeature (unsigned Feature) const
void setDefaultFeatures (StringRef CPU, StringRef FS)
Set the features to the default for the given CPU with an appended feature string.
FeatureBitset ToggleFeature (uint64_t FB)
Toggle a feature and return the re-computed feature bits.
FeatureBitset ToggleFeature (const FeatureBitset &FB)
Toggle a feature and return the re-computed feature bits.
FeatureBitset ToggleFeature (StringRef FS)
Toggle a set of features and return the re-computed feature bits.
FeatureBitset ApplyFeatureFlag (StringRef FS)
Apply a feature flag and return the re-computed feature bits, including all feature bits implied by the flag.
FeatureBitset SetFeatureBitsTransitively (const FeatureBitset &FB)
Set/clear additional feature bits, including all other bits they imply.
FeatureBitset ClearFeatureBitsTransitively (const FeatureBitset &FB)
bool checkFeatures (StringRef FS) const
Check whether the subtarget features are enabled/disabled as per the provided string, ignoring all other features.
const MCSchedModel & getSchedModelForCPU (StringRef CPU) const
Get the machine model of a CPU.
const MCSchedModel & getSchedModel () const
Get the machine model for this subtarget's CPU.
const MCWriteProcResEntry * getWriteProcResBegin (const MCSchedClassDesc *SC) const
Return an iterator at the first process resource consumed by the given scheduling class.
const MCWriteProcResEntry * getWriteProcResEnd (const MCSchedClassDesc *SC) const
const MCWriteLatencyEntry * getWriteLatencyEntry (const MCSchedClassDesc *SC, unsigned DefIdx) const
int getReadAdvanceCycles (const MCSchedClassDesc *SC, unsigned UseIdx, unsigned WriteResID) const
ArrayRef< MCReadAdvanceEntry > getReadAdvanceEntries (const MCSchedClassDesc &SC) const
Return the set of ReadAdvance entries declared by the scheduling class descriptor in input.
InstrItineraryData getInstrItineraryForCPU (StringRef CPU) const
Get scheduling itinerary of a CPU.
void initInstrItins (InstrItineraryData &InstrItins) const
Initialize an InstrItineraryData instance.
virtual unsigned resolveVariantSchedClass (unsigned SchedClass, const MCInst *MI, unsigned CPUID) const
Resolve a variant scheduling class for the given MCInst and CPU.
bool isCPUStringValid (StringRef CPU) const
Check whether the CPU string is valid.
virtual unsigned getHwMode () const
virtual Optional< unsigned > getCacheSize (unsigned Level) const
Return the cache size in bytes for the given level of cache.
virtual Optional< unsigned > getCacheAssociativity (unsigned Level) const
Return the cache associatvity for the given level of cache.
virtual Optional< unsigned > getCacheLineSize (unsigned Level) const
Return the target cache line size in bytes at a given level.
virtual unsigned getCacheLineSize () const
Return the target cache line size in bytes.
virtual unsigned getPrefetchDistance () const
Return the preferred prefetch distance in terms of instructions.
virtual unsigned getMaxPrefetchIterationsAhead () const
Return the maximum prefetch distance in terms of loop iterations.
virtual unsigned getMinPrefetchStride () const
Return the minimum stride necessary to trigger software prefetching.
Protected Member Functions
TargetSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetSubTypeKV > PD, const MCWriteProcResEntry *WPR, const MCWriteLatencyEntry *WL, const MCReadAdvanceEntry *RA, const InstrStage *IS, const unsigned *OC, const unsigned *FP)
Protected Member Functions inherited from llvm::MCSubtargetInfo
void InitMCProcessorInfo (StringRef CPU, StringRef FS)
Initialize the scheduling model and feature bits.
Detailed Description
TargetSubtargetInfo - Generic base class for all target subtargets.
All Target-specific options that control code generation and printing should be exposed through a TargetSubtargetInfo-derived class.
Definition at line 62 of file TargetSubtargetInfo.h.
Member Typedef Documentation
AntiDepBreakMode
using llvm::TargetSubtargetInfo::AntiDepBreakMode = enum { ANTIDEP_NONE, ANTIDEP_CRITICAL, ANTIDEP_ALL }
Definition at line 75 of file TargetSubtargetInfo.h.
RegClassVector
using llvm::TargetSubtargetInfo::RegClassVector = SmallVectorImpl<const TargetRegisterClass *>
Definition at line 76 of file TargetSubtargetInfo.h.
Constructor & Destructor Documentation
TargetSubtargetInfo() [1/3]
TargetSubtargetInfo::TargetSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetSubTypeKV > PD, const MCWriteProcResEntry * WPR, const MCWriteLatencyEntry * WL, const MCReadAdvanceEntry * RA, const InstrStage * IS, const unsigned * OC, const unsigned * FP) protected
Definition at line 17 of file TargetSubtargetInfo.cpp.
References ~TargetSubtargetInfo().
TargetSubtargetInfo() [2/3]
llvm::TargetSubtargetInfo::TargetSubtargetInfo () delete
TargetSubtargetInfo() [3/3]
llvm::TargetSubtargetInfo::TargetSubtargetInfo (const TargetSubtargetInfo &) delete
~TargetSubtargetInfo()
TargetSubtargetInfo::~TargetSubtargetInfo () override default
Referenced by TargetSubtargetInfo().
Member Function Documentation
addrSinkUsingGEPs()
virtual bool llvm::TargetSubtargetInfo::addrSinkUsingGEPs () const inline virtual
Sink addresses into blocks using GEP instructions rather than pointer casts and arithmetic.
Definition at line 281 of file TargetSubtargetInfo.h.
References useAA().
adjustSchedDependency()
virtual void llvm::TargetSubtargetInfo::adjustSchedDependency (SUnit * def, SUnit * use, SDep & dep) const inline virtual
Definition at line 229 of file TargetSubtargetInfo.h.
Referenced by llvm::ScheduleDAGInstrs::addVRegDefDeps(), and getUnderlyingObjects().
enableAdvancedRASplitCost()
bool TargetSubtargetInfo::enableAdvancedRASplitCost () const virtual
True if the subtarget should consider the cost of local intervals created by a split candidate when choosing the best split candidate.
This heuristic may be compile time intensive.
Definition at line 49 of file TargetSubtargetInfo.cpp.
Referenced by getOptLevelToEnablePostRAScheduler().
enableAtomicExpand()
bool TargetSubtargetInfo::enableAtomicExpand () const virtual
True if the subtarget should run the atomic expansion pass.
Definition at line 28 of file TargetSubtargetInfo.cpp.
Referenced by enableMachinePipeliner().
enableEarlyIfConversion()
virtual bool llvm::TargetSubtargetInfo::enableEarlyIfConversion () const inline virtual
Enable the use of the early if conversion pass.
Definition at line 286 of file TargetSubtargetInfo.h.
Referenced by adjCycles().
enableIndirectBrExpand()
bool TargetSubtargetInfo::enableIndirectBrExpand () const virtual
True if the subtarget should run the indirectbr expansion pass.
Definition at line 32 of file TargetSubtargetInfo.cpp.
Referenced by enableMachinePipeliner().
enableJoinGlobalCopies()
bool TargetSubtargetInfo::enableJoinGlobalCopies () const virtual
True if the subtarget should enable joining global copies.
By default this is enabled if the machine scheduler is enabled, but can be overridden.
Definition at line 40 of file TargetSubtargetInfo.cpp.
References enableMachineScheduler().
Referenced by enableMachinePipeliner(), and isTerminalReg().
enableMachinePipeliner()
virtual bool llvm::TargetSubtargetInfo::enableMachinePipeliner () const inline virtual
True if the subtarget should run MachinePipeliner.
Definition at line 195 of file TargetSubtargetInfo.h.
References enableAtomicExpand(), enableIndirectBrExpand(), enableJoinGlobalCopies(), enablePostRAMachineScheduler(), and enablePostRAScheduler().
enableMachineSchedDefaultSched()
virtual bool llvm::TargetSubtargetInfo::enableMachineSchedDefaultSched () const inline virtual
True if the machine scheduler should disable the TLI preference for preRA scheduling with the source level scheduler.
Definition at line 192 of file TargetSubtargetInfo.h.
Referenced by llvm::createDefaultScheduler().
enableMachineScheduler()
bool TargetSubtargetInfo::enableMachineScheduler () const virtual
True if the subtarget should run MachineScheduler after aggressive coalescing.
This currently replaces the SelectionDAG scheduler with the "source" order scheduler (though see below for an option to turn this off and use the TargetLowering preference). It does not yet disable the postRA scheduler.
Definition at line 36 of file TargetSubtargetInfo.cpp.
Referenced by llvm::createDefaultScheduler(), enableJoinGlobalCopies(), enablePostRAMachineScheduler(), and isOptimizableRegisterMove().
enablePostRAMachineScheduler()
bool TargetSubtargetInfo::enablePostRAMachineScheduler () const virtual
True if the subtarget should run a machine scheduler after register allocation.
Definition at line 57 of file TargetSubtargetInfo.cpp.
References enableMachineScheduler(), and enablePostRAScheduler().
Referenced by enableMachinePipeliner().
enablePostRAScheduler()
bool TargetSubtargetInfo::enablePostRAScheduler () const virtual
True if the subtarget should run a scheduler after register allocation.
By default this queries the PostRAScheduling bit in the scheduling model which is the preferred way to influence this.
Definition at line 53 of file TargetSubtargetInfo.cpp.
References llvm::MCSubtargetInfo::getSchedModel(), and llvm::MCSchedModel::PostRAScheduler.
Referenced by enableMachinePipeliner(), enablePostRAMachineScheduler(), and INITIALIZE_PASS().
enableRALocalReassignment()
bool TargetSubtargetInfo::enableRALocalReassignment (CodeGenOpt::Level OptLevel) const virtual
True if the subtarget should run the local reassignment heuristic of the register allocator.
This heuristic may be compile time intensive, OptLevel provides a finer grain to tune the register allocator.
Definition at line 44 of file TargetSubtargetInfo.cpp.
Referenced by getOptLevelToEnablePostRAScheduler().
enableSubRegLiveness()
virtual bool llvm::TargetSubtargetInfo::enableSubRegLiveness () const inline virtual
Enable tracking of subregister liveness in register allocator.
Please use MachineRegisterInfo::subRegLivenessEnabled() instead where possible.
Definition at line 298 of file TargetSubtargetInfo.h.
References mirFileLoaded().
getAntiDepBreakMode()
virtual AntiDepBreakMode llvm::TargetSubtargetInfo::getAntiDepBreakMode () const inline virtual
Definition at line 233 of file TargetSubtargetInfo.h.
Referenced by INITIALIZE_PASS().
getCallLowering()
virtual const CallLowering* llvm::TargetSubtargetInfo::getCallLowering () const inline virtual
Definition at line 103 of file TargetSubtargetInfo.h.
Referenced by llvm::createLibcall(), and llvm::createMemLibcall().
getCriticalPathRCs()
virtual void llvm::TargetSubtargetInfo::getCriticalPathRCs (RegClassVector & CriticalPathRCs) const inline virtual
Definition at line 238 of file TargetSubtargetInfo.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by INITIALIZE_PASS().
getCustomPBQPConstraints()
virtual std::unique_ptr<PBQPRAConstraint> llvm::TargetSubtargetInfo::getCustomPBQPConstraints () const inline virtual
Return PBQPConstraint(s) for the target.
Override to provide custom PBQP constraints.
Definition at line 291 of file TargetSubtargetInfo.h.
Referenced by normalizePBQPSpillWeight().
getDAGScheduler()
virtual RegisterScheduler::FunctionPassCtor llvm::TargetSubtargetInfo::getDAGScheduler (CodeGenOpt::Level) const inline virtual
Target can subclass this hook to select a different DAG scheduler.
Definition at line 115 of file TargetSubtargetInfo.h.
Referenced by llvm::createDefaultScheduler().
getFrameLowering()
virtual const TargetFrameLowering* llvm::TargetSubtargetInfo::getFrameLowering () const inline virtual
Definition at line 96 of file TargetSubtargetInfo.h.
Referenced by addExclusiveRegPair(), AdjustStackOffset(), assignCalleeSavedSpillSlots(), AssignProtectedObjSet(), llvm::CodeViewDebug::beginFunctionImpl(), checkNumAlignedDPRCS2Regs(), collectRegDefs(), llvm::DwarfCompileUnit::constructLabelDIE(), llvm::createNVPTXPrologEpilogPass(), llvm::TargetOptions::DisableFramePointerElim(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), emitDebugValueComment(), llvm::WinException::endFunclet(), eraseDeadBBsAndChildren(), llvm::MachineFrameInfo::estimateStackSize(), getFnStackAlignment(), llvm::AVRRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::X86InstrInfo::getSPAdjust(), llvm::TargetInstrInfo::getSPAdjust(), giveUpWithRemarks(), llvm::MipsCallLowering::MipsHandler::handle(), INITIALIZE_PASS(), llvm::MIRParserImpl::initializeFrameInfo(), insertCSRRestores(), insertCSRSaves(), llvm::Mips16RegisterInfo::intRegClass(), isCallableFunction(), lookupCandidateBaseReg(), llvm::MachineFunction::MachineFunction(), mayCombineMisaligned(), llvm::TargetRegisterInfo::needsStackRealignment(), llvm::MachineFrameInfo::print(), llvm::scavengeFrameVirtualRegs(), llvm::ScheduleDAGMILive::scheduleMI(), llvm::FunctionLoweringInfo::set(), and stashEntryDbgValues().
getInstrInfo()
virtual const TargetInstrInfo* llvm::TargetSubtargetInfo::getInstrInfo () const inline virtual
Definition at line 95 of file TargetSubtargetInfo.h.
Referenced by addExclusiveRegPair(), llvm::MachineBasicBlock::addLiveIn(), adjCycles(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), allPhiOperandsUndefined(), llvm::ARMBasicBlockUtils::ARMBasicBlockUtils(), AssignProtectedObjSet(), atomicReadDroppedOnZero(), attemptDebugCopyProp(), llvm::MachineBasicBlock::canSplitCriticalEdge(), collectCallSiteParameters(), collectRegDefs(), llvm::MachineFrameInfo::computeMaxCallFrameSize(), llvm::createBURRListDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::createSourceListDAGScheduler(), llvm::createSystemZLDCleanupPass(), llvm::createXCoreFrameToArgsOffsetEliminationPass(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::ARMFrameLowering::determineCalleeSaves(), doesNotGeneratecode(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), emitComments(), llvm::SparcFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), EmitNop(), llvm::AsmPrinter::emitNops(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologueInsns(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitThumb2LoadConstPool(), estimateRSStackSizeLimit(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::finalizeBundle(), FixedPointIntrinsicToOpcode(), for(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::PerTargetMIParsingState::getBitmaskTargetFlag(), llvm::ARMFrameLowering::getCalleeSaves(), getCallOpcode(), llvm::PerTargetMIParsingState::getDirectTargetFlag(), llvm::getEHScopeMembership(), getFPReg(), llvm::ARMHazardRecognizer::getHazardType(), GetInitialOffset(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::MSP430InstrInfo::getInstSizeInBytes(), getLoadStoreOffsetAlign(), getNewValueJumpOpcode(), llvm::SDNode::getOperationName(), llvm::PerTargetMIParsingState::getRegisterByName(), getRegUnits(), getSchedRegions(), llvm::PerTargetMIParsingState::getSubRegIndex(), llvm::PerTargetMIParsingState::getTargetIndex(), getTargetIndexName(), llvm::BPFTargetLowering::getTargetNodeName(), getUnderlyingArgRegs(), llvm::TargetSchedModel::init(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::ConvergingVLIWScheduler::initialize(), llvm::PostGenericScheduler::initialize(), INITIALIZE_PASS(), llvm::TailDuplicator::initMF(), insertCopy(), insertCSRRestores(), insertCSRSaves(), llvm::Mips16RegisterInfo::intRegClass(), isBackwardPropagatableCopy(), llvm::PPCInstrInfo::isBDNZ(), isCoalescable(), isCompareZero(), isFpMulInstruction(), isHardwareLoop(), isLibCallInTailPosition(), isTerminalReg(), IsUnconditionalJump(), isVirtualRegisterOperand(), LoopIsOuterMostWithPredecessor(), llvm::LegalizerHelper::lowerBitCount(), llvm::X86CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::MachineInstr::mayAlias(), false::IntervalSorter::operator()(), llvm::MachineBasicBlock::print(), llvm::MachineInstr::print(), printMemOperand(), llvm::MachineOperand::printTargetFlags(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::TargetInstrInfo::reassociateOps(), llvm::MachineRegisterInfo::recomputeRegClass(), replaceFI(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::ResourceManager::ResourceManager(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::UnreachableBlockElimPass::run(), llvm::BreakFalseDeps::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::Mips16RegisterInfo::saveScavengerRegister(), llvm::FunctionLoweringInfo::set(), setCallTargetReg(), llvm::SwiftErrorValueTracking::setFunction(), llvm::MachineIRBuilder::setMF(), llvm::RegScavenger::setRegUsed(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::MachineBasicBlock::SkipPHIsLabelsAndDebug(), llvm::SparcFrameLowering::SparcFrameLowering(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), stashEntryDbgValues(), subRangeLiveAt(), UpdateOperandRegClass(), llvm::MachineBasicBlock::updateTerminator(), llvm::MachineFunction::verify(), llvm::VLIWResourceModel::VLIWResourceModel(), and llvm::LegalizerHelper::widenScalar().
getInstrItineraryData()
virtual const InstrItineraryData* llvm::TargetSubtargetInfo::getInstrItineraryData () const inline virtual
getInstrItineraryData - Returns instruction itinerary data for the target or specific subtarget.
Definition at line 131 of file TargetSubtargetInfo.h.
Referenced by llvm::R600InstrInfo::CreateTargetScheduleState(), llvm::HexagonInstrInfo::CreateTargetScheduleState(), and getUnderlyingObjects().
getInstructionSelector()
virtual InstructionSelector* llvm::TargetSubtargetInfo::getInstructionSelector () const inline virtual
Definition at line 109 of file TargetSubtargetInfo.h.
Referenced by llvm::InstructionSelect::runOnMachineFunction().
getLegalizerInfo()
virtual const LegalizerInfo* llvm::TargetSubtargetInfo::getLegalizerInfo () const inline virtual
Definition at line 119 of file TargetSubtargetInfo.h.
Referenced by llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::machineFunctionIsIllegal(), and llvm::Legalizer::runOnMachineFunction().
getOptLevelToEnablePostRAScheduler()
virtual CodeGenOpt::Level llvm::TargetSubtargetInfo::getOptLevelToEnablePostRAScheduler () const inline virtual
Definition at line 260 of file TargetSubtargetInfo.h.
References llvm::CodeGenOpt::Default, enableAdvancedRASplitCost(), enableRALocalReassignment(), and useAA().
Referenced by INITIALIZE_PASS().
getPostRAMutations()
virtual void llvm::TargetSubtargetInfo::getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> & Mutations) const inline virtual
Definition at line 244 of file TargetSubtargetInfo.h.
getRegBankInfo()
virtual const RegisterBankInfo* llvm::TargetSubtargetInfo::getRegBankInfo () const inline virtual
If the information for the register banks is available, return it.
Otherwise return nullptr.
Definition at line 127 of file TargetSubtargetInfo.h.
Referenced by getCallOpcode(), llvm::PerTargetMIParsingState::getMMOTargetFlag(), INITIALIZE_PASS_END(), isAmbiguous(), llvm::X86CallLowering::lowerCall(), and llvm::AArch64CallLowering::lowerCall().
getRegisterInfo()
virtual const TargetRegisterInfo* llvm::TargetSubtargetInfo::getRegisterInfo () const inline virtual
getRegisterInfo - If register information is available, return it.
If not, return null.
Definition at line 123 of file TargetSubtargetInfo.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addLiveInRegs(), addSavedGPR(), adjCycles(), AdjustStackOffset(), llvm::MachineFunction::allocateRegMask(), llvm::A57ChainingConstraint::apply(), llvm::HexagonSubtarget::CallMutation::apply(), assignCalleeSavedSpillSlots(), AssignProtectedObjSet(), atomicReadDroppedOnZero(), llvm::DebugHandlerBase::beginFunction(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::HexagonPacketizerList::canPromoteToDotCur(), CC_X86_64_VectorCall(), checkNumAlignedDPRCS2Regs(), collectRegDefs(), computeLiveOuts(), llvm::TargetSchedModel::computeOutputLatency(), llvm::DwarfCompileUnit::constructLabelDIE(), llvm::MIRPrinter::convertCallSiteObjects(), llvm::GCNTargetMachine::convertFuncInfoToYAML(), llvm::MIRPrinter::convertStackObjects(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::createBURRListDAGScheduler(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::MipsFunctionInfo::createISRRegFI(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::createNVPTXPrologEpilogPass(), llvm::createSourceListDAGScheduler(), llvm::AArch64InstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::SystemZFrameLowering::determineCalleeSaves(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::DwarfDebug::emitDebugLocValue(), emitDebugValueComment(), llvm::ARMFrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::emitFrameDirective(), EmitGCCInlineAsmStr(), llvm::AsmPrinter::emitImplicitDef(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), emitKill(), llvm::XCoreFrameLowering::emitPrologue(), estimateRSStackSizeLimit(), llvm::MachineFrameInfo::estimateStackSize(), llvm::finalizeBundle(), findMatchingInlineAsmOperand(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), for(), llvm::TargetFrameLowering::getCalleeSaves(), getDwarfRegNum(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::AVRRegisterInfo::getLargestLegalSuperClass(), getLoadStoreOffsetAlign(), getMemcpyLoadsAndStores(), llvm::PerTargetMIParsingState::getMMOTargetFlag(), llvm::MipsFunctionInfo::getMoveF64ViaSpillFI(), getNewValueJumpOpcode(), getOpenCLAlignment(), llvm::RISCVInstrInfo::getOutliningType(), llvm::MachineFrameInfo::getPristineRegs(), GetRegistersForValue(), llvm::PerTargetMIParsingState::getRegMask(), getRegTy(), getRegUnits(), llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), giveUpWithRemarks(), HandleVRSaveUpdate(), llvm::SparcFrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), llvm::VEFrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), INITIALIZE_PASS(), INITIALIZE_PASS_END(), llvm::TailDuplicator::initMF(), insertCSRRestores(), insertCSRSaves(), isACalleeSavedRegister(), isBackwardPropagatableCopy(), isCallableFunction(), isCoalescable(), isFpMulInstruction(), isImplicitOperandIn(), isIntersect(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), llvm::AArch64InstrInfo::isMBBSafeToOutlineFrom(), isNonFoldablePartialRegisterLoad(), llvm::TargetInstrInfo::isSchedulingBoundary(), isTerminalReg(), isVirtualRegisterOperand(), llvm::LiveRegMatrix::LiveRegMatrix(), lookupCandidateBaseReg(), LoopIsOuterMostWithPredecessor(), llvm::MipsCallLowering::lowerCall(), llvm::MachineFunction::MachineFunction(), MakeM0Inst(), needsReferenceType(), numVectorEltsOrZero(), llvm::PerTargetMIParsingState::parseInstrName(), patchMatchingInput(), llvm::PhysicalRegisterUsageInfo::print(), llvm::MIRPrinter::print(), llvm::RegisterBankInfo::OperandsMapper::print(), llvm::MachineFunction::print(), llvm::MachineBasicBlock::print(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::TargetInstrInfo::reassociateOps(), ReplaceFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::BreakFalseDeps::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::ReachingDefAnalysis::runOnMachineFunction(), llvm::LiveStacks::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::FunctionLoweringInfo::set(), setAliasRegs(), llvm::RegScavenger::setRegUsed(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::PerTargetMIParsingState::setTarget(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), stashEntryDbgValues(), llvm::X86InstrInfo::unfoldMemoryOperand(), updateLiveIn(), UpdateOperandRegClass(), UpdatePredRedefs(), llvm::DwarfCompileUnit::updateSubprogramScopeDIE(), llvm::MachineFunction::verify(), and llvm::VirtRegAuxInfo::weightCalcHelper().
getSelectionDAGInfo()
virtual const SelectionDAGTargetInfo* llvm::TargetSubtargetInfo::getSelectionDAGInfo () const inline virtual
Definition at line 100 of file TargetSubtargetInfo.h.
Referenced by llvm::SelectionDAG::init(), and isContractable().
getSMSMutations()
virtual void llvm::TargetSubtargetInfo::getSMSMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> & Mutations) const inline virtual
Definition at line 250 of file TargetSubtargetInfo.h.
Referenced by llvm::SwingSchedulerDAG::SwingSchedulerDAG().
getTargetLowering()
virtual const TargetLowering* llvm::TargetSubtargetInfo::getTargetLowering () const inline virtual
Definition at line 99 of file TargetSubtargetInfo.h.
Referenced by llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::calculateDbgEntityHistory(), llvm::rdf::DataFlowGraph::DefStack::clear_block(), llvm::createDwarfEHPass(), llvm::createLibcall(), llvm::createMemLibcall(), llvm::FunctionLoweringInfo::CreateReg(), llvm::FunctionLoweringInfo::CreateRegs(), llvm::CombinerHelper::dominates(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::XCoreFrameLowering::emitPrologue(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WinException::endFunclet(), llvm::MachineIRBuilder::getBoolExtOp(), llvm::SystemZRegisterInfo::getCalleeSavedRegs(), llvm::SystemZRegisterInfo::getCallPreservedMask(), getMemsetValue(), llvm::CCState::HandleByVal(), llvm::SelectionDAG::init(), INITIALIZE_PASS(), llvm::isInTailCallPosition(), isRegOtherThanSPAndFP(), llvm::TargetInstrInfo::isSchedulingBoundary(), LoopIsOuterMostWithPredecessor(), llvm::LegalizerHelper::lowerDynStackAlloc(), llvm::LegalizerHelper::lowerReadRegister(), llvm::MachineFunction::MachineFunction(), llvm::StackProtector::runOnFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AMDGPUPerfHintAnalysis::runOnSCC(), llvm::FunctionLoweringInfo::set(), and llvm::SwiftErrorValueTracking::setFunction().
ignoreCSRForAllocationOrder()
virtual bool llvm::TargetSubtargetInfo::ignoreCSRForAllocationOrder (const MachineFunction & MF, unsigned PhysReg) const inline virtual
True if the register allocator should use the allocation orders exactly as written in the tablegen descriptions, false if it should allocate the specified physical register later if is it callee-saved.
Definition at line 306 of file TargetSubtargetInfo.h.
isDependencyBreaking()
virtual bool llvm::TargetSubtargetInfo::isDependencyBreaking (const MachineInstr * MI, APInt & Mask) const inline virtual
Returns true if MI is a dependency breaking instruction for the subtarget.
Similar in behavior to isZeroIdiom. However, it knows how to identify all dependency breaking instructions (i.e. not just zero-idioms).
As for isZeroIdiom, this method returns a mask of "broken" dependencies. (See method isZeroIdiom for a detailed description of Mask).
Definition at line 165 of file TargetSubtargetInfo.h.
References isZeroIdiom().
isOptimizableRegisterMove()
virtual bool llvm::TargetSubtargetInfo::isOptimizableRegisterMove (const MachineInstr * MI) const inline virtual
Returns true if MI is a candidate for move elimination.
A candidate for move elimination may be optimized out at register renaming stage. Subtargets can specify the set of optimizable moves by instantiating tablegen class IsOptimizableRegisterMove (see llvm/Target/TargetInstrPredicate.td).
SubtargetEmitter is responsible for processing all the definitions of class IsOptimizableRegisterMove, and auto-generate an override for this method.
Definition at line 178 of file TargetSubtargetInfo.h.
References enableMachineScheduler().
isXRaySupported()
virtual bool llvm::TargetSubtargetInfo::isXRaySupported () const inline virtual
Definition at line 83 of file TargetSubtargetInfo.h.
isZeroIdiom()
virtual bool llvm::TargetSubtargetInfo::isZeroIdiom (const MachineInstr * MI, APInt & Mask) const inline virtual
Returns true if MI is a dependency breaking zero-idiom instruction for the subtarget.
This function also sets bits in Mask related to input operands that are not in a data dependency relationship. There is one bit for each machine operand; implicit operands follow explicit operands in the bit representation used for Mask. An empty (i.e. a mask with all bits cleared) means: data dependencies are "broken" for all the explicit input machine operands of MI.
Definition at line 154 of file TargetSubtargetInfo.h.
Referenced by isDependencyBreaking().
mirFileLoaded()
void TargetSubtargetInfo::mirFileLoaded (MachineFunction & MF) const virtual
This is called after a .mir file was loaded.
Definition at line 65 of file TargetSubtargetInfo.cpp.
Referenced by enableSubRegLiveness(), and llvm::MIRParserImpl::initializeMachineFunction().
operator=()
TargetSubtargetInfo& llvm::TargetSubtargetInfo::operator= (const TargetSubtargetInfo &) delete
overrideSchedPolicy()
virtual void llvm::TargetSubtargetInfo::overrideSchedPolicy (MachineSchedPolicy & Policy, unsigned NumRegionInstrs) const inline virtual
Override generic scheduling policy within a region.
This is a convenient way for targets that don't provide any custom scheduling heuristics (no custom MachineSchedStrategy) to make changes to the generic scheduling policy.
Definition at line 224 of file TargetSubtargetInfo.h.
resolveSchedClass()
virtual unsigned llvm::TargetSubtargetInfo::resolveSchedClass (unsigned SchedClass, const MachineInstr * MI, const TargetSchedModel * SchedModel) const inline virtual
Resolve a SchedClass at runtime, where SchedClass identifies an MCSchedClassDesc with the isVariant property.
This may return the ID of another variant SchedClass, but repeated invocation must quickly terminate in a nonvariant SchedClass.
Definition at line 139 of file TargetSubtargetInfo.h.
Referenced by llvm::TargetSchedModel::resolveSchedClass().
useAA()
bool TargetSubtargetInfo::useAA () const virtual
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
Definition at line 61 of file TargetSubtargetInfo.cpp.
Referenced by addrSinkUsingGEPs(), llvm::ScheduleDAGInstrs::buildSchedGraph(), getOptLevelToEnablePostRAScheduler(), and llvm::BasicTTIImplBase< AMDGPUTTIImpl >::useAA().
useDFAforSMS()
virtual bool llvm::TargetSubtargetInfo::useDFAforSMS () const inline virtual
Default to DFA for resource management, return false when target will use ProcResource in InstrSchedModel instead.
Definition at line 256 of file TargetSubtargetInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TargetSubtargetInfo.h
lib/CodeGen/TargetSubtargetInfo.cpp