LLVM: llvm::MipsABIInfo Class Reference
llvm::MipsABIInfo Class Reference
#include "Target/Mips/MCTargetDesc/MipsABIInfo.h"
Public Types
enum ABI { ABI::Unknown, ABI::O32, ABI::N32, ABI::N64 }
Public Member Functions
MipsABIInfo (ABI ThisABI)
bool IsKnown () const
bool IsO32 () const
bool IsN32 () const
bool IsN64 () const
ABI GetEnumValue () const
ArrayRef< MCPhysReg > GetByValArgRegs () const
The registers to use for byval arguments.
ArrayRef< MCPhysReg > GetVarArgRegs () const
The registers to use for the variable argument list.
unsigned GetCalleeAllocdArgSizeInBytes (CallingConv::ID CC) const
Obtain the size of the area allocated by the callee for arguments.
bool operator< (const MipsABIInfo Other) const
Ordering of ABI's MipsGenSubtargetInfo.inc will use this to resolve conflicts when given multiple ABI options.
unsigned GetStackPtr () const
unsigned GetFramePtr () const
unsigned GetBasePtr () const
unsigned GetGlobalPtr () const
unsigned GetNullPtr () const
unsigned GetZeroReg () const
unsigned GetPtrAdduOp () const
unsigned GetPtrAddiuOp () const
unsigned GetPtrSubuOp () const
unsigned GetPtrAndOp () const
unsigned GetGPRMoveOp () const
bool ArePtrs64bit () const
bool AreGprs64bit () const
unsigned GetEhDataReg (unsigned I) const
Static Public Member Functions
static MipsABIInfo Unknown ()
static MipsABIInfo O32 ()
static MipsABIInfo N32 ()
static MipsABIInfo N64 ()
static MipsABIInfo computeTargetABI (const Triple &TT, StringRef CPU, const MCTargetOptions &Options)
Protected Attributes
ABI ThisABI
Detailed Description
Definition at line 23 of file MipsABIInfo.h.
Member Enumeration Documentation
ABI
enum llvm::MipsABIInfo::ABI strong
Enumerator
Unknown
O32
N32
N64
Definition at line 25 of file MipsABIInfo.h.
Constructor & Destructor Documentation
MipsABIInfo()
llvm::MipsABIInfo::MipsABIInfo (ABI ThisABI) inline
Definition at line 31 of file MipsABIInfo.h.
Referenced by N32(), N64(), O32(), and Unknown().
Member Function Documentation
AreGprs64bit()
bool llvm::MipsABIInfo::AreGprs64bit () const inline
Definition at line 75 of file MipsABIInfo.h.
References GetEhDataReg(), I, IsN32(), and IsN64().
Referenced by GetZeroReg().
ArePtrs64bit()
bool llvm::MipsABIInfo::ArePtrs64bit () const inline
Definition at line 74 of file MipsABIInfo.h.
References IsN64().
Referenced by covertDoubleImmToSingleImm(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsSEFrameLowering::emitPrologue(), GetBasePtr(), GetFramePtr(), GetGlobalPtr(), GetGPRMoveOp(), GetNullPtr(), llvm::MipsRegisterInfo::getPointerRegClass(), GetPtrAddiuOp(), GetPtrAdduOp(), GetPtrAndOp(), GetPtrSubuOp(), GetStackPtr(), isShiftedUIntAtAnyPosition(), llvm::MipsSEInstrInfo::loadRegFromStack(), and llvm::MipsSEFrameLowering::spillCalleeSavedRegisters().
computeTargetABI()
MipsABIInfo MipsABIInfo::computeTargetABI (const Triple & TT, StringRef CPU, const MCTargetOptions & Options) static
Definition at line 57 of file MipsABIInfo.cpp.
References assert(), llvm::StringRef::empty(), llvm::MCTargetOptions::getABIName(), llvm::Triple::getEnvironment(), llvm::Triple::GNUABIN32, llvm::Triple::isMIPS64(), N32(), N64(), O32(), and llvm::StringRef::startswith().
Referenced by computeDataLayout(), llvm::createMipsAsmBackend(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), and N64().
GetBasePtr()
unsigned MipsABIInfo::GetBasePtr () const
Definition at line 82 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by llvm::MipsSEFrameLowering::getFrameIndexReference(), and operator<().
GetByValArgRegs()
ArrayRef< MCPhysReg > MipsABIInfo::GetByValArgRegs () const
The registers to use for byval arguments.
Definition at line 33 of file MipsABIInfo.cpp.
References IsN32(), IsN64(), IsO32(), llvm_unreachable, and llvm::makeArrayRef().
Referenced by GetEnumValue(), and llvm::MipsTargetLowering::HandleByVal().
GetCalleeAllocdArgSizeInBytes()
unsigned MipsABIInfo::GetCalleeAllocdArgSizeInBytes (CallingConv::ID CC) const
Obtain the size of the area allocated by the callee for arguments.
CallingConv::FastCall affects the value for O32.
Definition at line 49 of file MipsABIInfo.cpp.
References llvm::CallingConv::Fast, IsN32(), IsN64(), IsO32(), and llvm_unreachable.
Referenced by GetEnumValue(), llvm::MipsCallLowering::lowerFormalArguments(), and UnpackFromArgumentSlot().
GetEhDataReg()
unsigned MipsABIInfo::GetEhDataReg (unsigned I) const
Definition at line 118 of file MipsABIInfo.cpp.
References I, and IsN64().
Referenced by AreGprs64bit(), llvm::MipsSEFrameLowering::emitEpilogue(), and llvm::MipsSEFrameLowering::emitPrologue().
GetEnumValue()
ABI llvm::MipsABIInfo::GetEnumValue () const inline
Definition at line 44 of file MipsABIInfo.h.
References GetByValArgRegs(), GetCalleeAllocdArgSizeInBytes(), GetVarArgRegs(), and ThisABI.
Referenced by operator<().
GetFramePtr()
unsigned MipsABIInfo::GetFramePtr () const
Definition at line 78 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::getFrameIndexReference(), and operator<().
GetGlobalPtr()
unsigned MipsABIInfo::GetGlobalPtr () const
Definition at line 86 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by operator<().
GetGPRMoveOp()
unsigned MipsABIInfo::GetGPRMoveOp () const
Definition at line 114 of file MipsABIInfo.cpp.
References ArePtrs64bit(), and llvm::ISD::OR.
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), and operator<().
GetNullPtr()
unsigned MipsABIInfo::GetNullPtr () const
Definition at line 90 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsSEFrameLowering::emitPrologue(), isShiftedUIntAtAnyPosition(), and operator<().
GetPtrAddiuOp()
unsigned MipsABIInfo::GetPtrAddiuOp () const
Definition at line 102 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsSEFrameLowering::emitPrologue(), and operator<().
GetPtrAdduOp()
unsigned MipsABIInfo::GetPtrAdduOp () const
Definition at line 98 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), isShiftedUIntAtAnyPosition(), llvm::MipsSEInstrInfo::loadImmediate(), and operator<().
GetPtrAndOp()
unsigned MipsABIInfo::GetPtrAndOp () const
Definition at line 110 of file MipsABIInfo.cpp.
References llvm::ISD::AND, and ArePtrs64bit().
Referenced by llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), and operator<().
GetPtrSubuOp()
unsigned MipsABIInfo::GetPtrSubuOp () const
Definition at line 106 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), and operator<().
GetStackPtr()
unsigned MipsABIInfo::GetStackPtr () const
Definition at line 74 of file MipsABIInfo.cpp.
References ArePtrs64bit().
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::getFrameIndexReference(), and operator<().
GetVarArgRegs()
ArrayRef< MCPhysReg > MipsABIInfo::GetVarArgRegs () const
The registers to use for the variable argument list.
Definition at line 41 of file MipsABIInfo.cpp.
References IsN32(), IsN64(), IsO32(), llvm_unreachable, and llvm::makeArrayRef().
Referenced by GetEnumValue(), and llvm::MipsCallLowering::lowerFormalArguments().
GetZeroReg()
unsigned MipsABIInfo::GetZeroReg () const
Definition at line 94 of file MipsABIInfo.cpp.
References AreGprs64bit().
Referenced by llvm::MipsInstrInfo::getEquivalentCompactForm(), isShiftedUIntAtAnyPosition(), and operator<().
IsKnown()
bool llvm::MipsABIInfo::IsKnown () const inline
Definition at line 40 of file MipsABIInfo.h.
References Unknown.
IsN32()
bool llvm::MipsABIInfo::IsN32 () const inline
Definition at line 42 of file MipsABIInfo.h.
References N32.
Referenced by AreGprs64bit(), computeDataLayout(), llvm::createMipsAsmBackend(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), GetByValArgRegs(), GetCalleeAllocdArgSizeInBytes(), GetVarArgRegs(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::MipsSubtarget::isABI_N32(), isShiftedUIntAtAnyPosition(), lowerFABS64(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MipsTargetLowering::MipsTargetLowering(), and UnpackFromArgumentSlot().
IsN64()
bool llvm::MipsABIInfo::IsN64 () const inline
Definition at line 43 of file MipsABIInfo.h.
References N64.
Referenced by AreGprs64bit(), ArePtrs64bit(), computeDataLayout(), covertDoubleImmToSingleImm(), llvm::MipsFrameLowering::eliminateCallFramePseudoInstr(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MipsSEFrameLowering::emitPrologue(), GetByValArgRegs(), GetCalleeAllocdArgSizeInBytes(), GetEhDataReg(), llvm::MipsTargetLowering::getOpndList(), GetVarArgRegs(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::MipsSubtarget::isABI_N64(), isShiftedUIntAtAnyPosition(), lowerFABS64(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MipsTargetLowering::MipsTargetLowering(), and UnpackFromArgumentSlot().
IsO32()
bool llvm::MipsABIInfo::IsO32 () const inline
Definition at line 41 of file MipsABIInfo.h.
References O32.
Referenced by computeDataLayout(), llvm::MipsTargetLowering::createFastISel(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), GetByValArgRegs(), GetCalleeAllocdArgSizeInBytes(), GetVarArgRegs(), llvm::MipsTargetLowering::HandleByVal(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::MipsSubtarget::isABI_O32(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::MipsTargetLowering::MipsTargetLowering(), and UnpackFromArgumentSlot().
N32()
static MipsABIInfo llvm::MipsABIInfo::N32 () inline static
Definition at line 35 of file MipsABIInfo.h.
References MipsABIInfo(), and N32.
Referenced by computeTargetABI().
N64()
static MipsABIInfo llvm::MipsABIInfo::N64 () inline static
Definition at line 36 of file MipsABIInfo.h.
References computeTargetABI(), MipsABIInfo(), N64, and llvm::TT.
Referenced by computeTargetABI(), and llvm::MipsTargetELFStreamer::MipsTargetELFStreamer().
O32()
static MipsABIInfo llvm::MipsABIInfo::O32 () inline static
Definition at line 34 of file MipsABIInfo.h.
References MipsABIInfo(), and O32.
Referenced by computeTargetABI(), and llvm::MipsTargetELFStreamer::MipsTargetELFStreamer().
operator<()
bool llvm::MipsABIInfo::operator< (const MipsABIInfo Other) const inline
Ordering of ABI's MipsGenSubtargetInfo.inc will use this to resolve conflicts when given multiple ABI options.
Definition at line 59 of file MipsABIInfo.h.
References GetBasePtr(), GetEnumValue(), GetFramePtr(), GetGlobalPtr(), GetGPRMoveOp(), GetNullPtr(), GetPtrAddiuOp(), GetPtrAdduOp(), GetPtrAndOp(), GetPtrSubuOp(), GetStackPtr(), and GetZeroReg().
Unknown()
static MipsABIInfo llvm::MipsABIInfo::Unknown () inline static
Definition at line 33 of file MipsABIInfo.h.
References MipsABIInfo(), and Unknown.
Member Data Documentation
ThisABI
ABI llvm::MipsABIInfo::ThisABI protected
Definition at line 28 of file MipsABIInfo.h.
Referenced by GetEnumValue().
The documentation for this class was generated from the following files:
lib/Target/Mips/MCTargetDesc/MipsABIInfo.h
lib/Target/Mips/MCTargetDesc/MipsABIInfo.cpp