LLVM: llvm::xray::FDRTraceWriter Class Reference
llvm::xray::FDRTraceWriter Class Reference
The FDRTraceWriter allows us to hand-craft an XRay Flight Data Recorder (FDR) mode log file.
#include "llvm/XRay/FDRTraceWriter.h"
Public Member Functions
FDRTraceWriter (raw_ostream &O, const XRayFileHeader &H)
~FDRTraceWriter ()
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
The FDRTraceWriter allows us to hand-craft an XRay Flight Data Recorder (FDR) mode log file.
This is used primarily for testing, generating sequences of FDR records that can be read/processed. It can also be used to generate various kinds of execution traces without using the XRay runtime. Note that this writer does not do any validation, but uses the types of records defined in the FDRRecords.h file.
Definition at line 29 of file FDRTraceWriter.h.
Constructor & Destructor Documentation
FDRTraceWriter()
llvm::xray::FDRTraceWriter::FDRTraceWriter (raw_ostream & O, const XRayFileHeader & H) explicit
Definition at line 61 of file FDRTraceWriter.cpp.
References llvm::xray::XRayFileHeader::ConstantTSC, llvm::xray::XRayFileHeader::CycleFrequency, llvm::xray::XRayFileHeader::FreeFormData, llvm::xray::XRayFileHeader::NonstopTSC, llvm::xray::XRayFileHeader::Type, and llvm::xray::XRayFileHeader::Version.
~FDRTraceWriter()
llvm::xray::FDRTraceWriter::~FDRTraceWriter ()
Definition at line 79 of file FDRTraceWriter.cpp.
Member Function Documentation
visit() [1/12]
Error llvm::xray::FDRTraceWriter::visit (BufferExtents & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 81 of file FDRTraceWriter.cpp.
References llvm::xray::BufferExtents::size().
visit() [2/12]
Error llvm::xray::FDRTraceWriter::visit (WallclockRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 85 of file FDRTraceWriter.cpp.
References llvm::xray::WallclockRecord::nanos(), and llvm::xray::WallclockRecord::seconds().
visit() [3/12]
Error llvm::xray::FDRTraceWriter::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 89 of file FDRTraceWriter.cpp.
References llvm::xray::NewCPUIDRecord::cpuid(), and llvm::xray::NewCPUIDRecord::tsc().
visit() [4/12]
Error llvm::xray::FDRTraceWriter::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 93 of file FDRTraceWriter.cpp.
References llvm::xray::TSCWrapRecord::tsc().
visit() [5/12]
Error llvm::xray::FDRTraceWriter::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 97 of file FDRTraceWriter.cpp.
References llvm::xray::CustomEventRecord::cpu(), D, llvm::xray::CustomEventRecord::data(), E, llvm::xray::CustomEventRecord::size(), llvm::Error::success(), and llvm::xray::CustomEventRecord::tsc().
visit() [6/12]
Error llvm::xray::FDRTraceWriter::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 124 of file FDRTraceWriter.cpp.
References llvm::xray::CallArgRecord::arg().
visit() [7/12]
Error llvm::xray::FDRTraceWriter::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 128 of file FDRTraceWriter.cpp.
References llvm::xray::PIDRecord::pid().
visit() [8/12]
Error llvm::xray::FDRTraceWriter::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 132 of file FDRTraceWriter.cpp.
References llvm::xray::NewBufferRecord::tid().
visit() [9/12]
Error llvm::xray::FDRTraceWriter::visit (EndBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 136 of file FDRTraceWriter.cpp.
visit() [10/12]
Error llvm::xray::FDRTraceWriter::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 140 of file FDRTraceWriter.cpp.
References llvm::xray::FunctionRecord::delta(), llvm::xray::FunctionRecord::functionId(), llvm::xray::FunctionRecord::recordType(), and llvm::Error::success().
visit() [11/12]
Error llvm::xray::FDRTraceWriter::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 106 of file FDRTraceWriter.cpp.
References D, llvm::xray::CustomEventRecordV5::data(), llvm::xray::CustomEventRecordV5::delta(), E, llvm::xray::CustomEventRecordV5::size(), and llvm::Error::success().
visit() [12/12]
Error llvm::xray::FDRTraceWriter::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 115 of file FDRTraceWriter.cpp.
References D, llvm::xray::TypedEventRecord::data(), llvm::xray::TypedEventRecord::delta(), E, llvm::xray::TypedEventRecord::eventType(), llvm::xray::TypedEventRecord::size(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRTraceWriter.h
lib/XRay/FDRTraceWriter.cpp