LLVM: llvm::MCMachObjectTargetWriter Class Reference
llvm::MCMachObjectTargetWriter Class Reference abstract
#include "llvm/MC/MCMachObjectWriter.h"
Public Member Functions
virtual ~MCMachObjectTargetWriter ()
virtual Triple::ObjectFormatType getFormat () const
Lifetime Management
virtual void reset ()
Accessors
bool is64Bit () const
uint32_t getCPUType () const
uint32_t getCPUSubtype () const
unsigned getLocalDifferenceRelocationType () const
API
virtual void recordRelocation (MachObjectWriter *Writer, MCAssembler &Asm, const MCAsmLayout &Layout, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, uint64_t &FixedValue)=0
Public Member Functions inherited from llvm::MCObjectTargetWriter
virtual ~MCObjectTargetWriter ()=default
Static Public Member Functions
static bool classof (const MCObjectTargetWriter *W)
Public Attributes
unsigned LocalDifference_RIT
Protected Member Functions
MCMachObjectTargetWriter (bool Is64Bit_, uint32_t CPUType_, uint32_t CPUSubtype_)
void setLocalDifferenceRelocationType (unsigned Type)
Protected Attributes
uint32_t CPUSubtype
Detailed Description
Definition at line 28 of file MCMachObjectWriter.h.
Constructor & Destructor Documentation
MCMachObjectTargetWriter()
MCMachObjectTargetWriter::MCMachObjectTargetWriter (bool Is64Bit_, uint32_t CPUType_, uint32_t CPUSubtype_) protected
Definition at line 13 of file MCMachObjectTargetWriter.cpp.
References ~MCMachObjectTargetWriter().
~MCMachObjectTargetWriter()
MCMachObjectTargetWriter::~MCMachObjectTargetWriter () virtual default
Referenced by MCMachObjectTargetWriter(), and setLocalDifferenceRelocationType().
Member Function Documentation
classof()
static bool llvm::MCMachObjectTargetWriter::classof (const MCObjectTargetWriter * W) inline static
Definition at line 48 of file MCMachObjectWriter.h.
References llvm::MCObjectTargetWriter::getFormat(), and llvm::Triple::MachO.
getCPUSubtype()
uint32_t llvm::MCMachObjectTargetWriter::getCPUSubtype () const inline
Definition at line 64 of file MCMachObjectWriter.h.
References CPUSubtype.
getCPUType()
uint32_t llvm::MCMachObjectTargetWriter::getCPUType () const inline
Definition at line 63 of file MCMachObjectWriter.h.
getFormat()
virtual Triple::ObjectFormatType llvm::MCMachObjectTargetWriter::getFormat () const inline virtual
Implements llvm::MCObjectTargetWriter.
Definition at line 47 of file MCMachObjectWriter.h.
References llvm::Triple::MachO.
getLocalDifferenceRelocationType()
unsigned llvm::MCMachObjectTargetWriter::getLocalDifferenceRelocationType () const inline
Definition at line 65 of file MCMachObjectWriter.h.
References llvm::HexStyle::Asm, Fixup, LocalDifference_RIT, and recordRelocation().
is64Bit()
bool llvm::MCMachObjectTargetWriter::is64Bit () const inline
Definition at line 62 of file MCMachObjectWriter.h.
recordRelocation()
virtual void llvm::MCMachObjectTargetWriter::recordRelocation (MachObjectWriter * Writer, MCAssembler & Asm, const MCAsmLayout & Layout, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, uint64_t & FixedValue) pure virtual
Referenced by llvm::MachObjectWriter::addRelocation(), and getLocalDifferenceRelocationType().
reset()
virtual void llvm::MCMachObjectTargetWriter::reset () inline virtual
Definition at line 55 of file MCMachObjectWriter.h.
setLocalDifferenceRelocationType()
void llvm::MCMachObjectTargetWriter::setLocalDifferenceRelocationType (unsigned Type) inline protected
Definition at line 40 of file MCMachObjectWriter.h.
References ~MCMachObjectTargetWriter().
Member Data Documentation
CPUSubtype
uint32_t llvm::MCMachObjectTargetWriter::CPUSubtype protected
Definition at line 32 of file MCMachObjectWriter.h.
Referenced by getCPUSubtype().
LocalDifference_RIT
unsigned llvm::MCMachObjectTargetWriter::LocalDifference_RIT
Definition at line 34 of file MCMachObjectWriter.h.
Referenced by getLocalDifferenceRelocationType().
The documentation for this class was generated from the following files:
include/llvm/MC/MCMachObjectWriter.h
lib/MC/MCMachObjectTargetWriter.cpp