LLVM: llvm::AssemblerConstantPools Class Reference
llvm::AssemblerConstantPools Class Reference
#include "llvm/MC/ConstantPools.h"
Public Member Functions
void emitAll (MCStreamer &Streamer)
void emitForCurrentSection (MCStreamer &Streamer)
void clearCacheForCurrentSection (MCStreamer &Streamer)
const MCExpr * addEntry (MCStreamer &Streamer, const MCExpr *Expr, unsigned Size, SMLoc Loc)
Detailed Description
Definition at line 70 of file ConstantPools.h.
Member Function Documentation
addEntry()
const MCExpr * AssemblerConstantPools::addEntry (MCStreamer & Streamer, const MCExpr * Expr, unsigned Size, SMLoc Loc)
Definition at line 109 of file ConstantPools.cpp.
References llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), and Size.
clearCacheForCurrentSection()
void AssemblerConstantPools::clearCacheForCurrentSection (MCStreamer & Streamer)
Definition at line 103 of file ConstantPools.cpp.
References llvm::HexagonISD::CP, and llvm::MCStreamer::getCurrentSectionOnly().
emitAll()
void AssemblerConstantPools::emitAll (MCStreamer & Streamer)
Definition at line 87 of file ConstantPools.cpp.
References llvm::HexagonISD::CP, and emitConstantPool().
emitForCurrentSection()
void AssemblerConstantPools::emitForCurrentSection (MCStreamer & Streamer)
Definition at line 97 of file ConstantPools.cpp.
References llvm::HexagonISD::CP, emitConstantPool(), and llvm::MCStreamer::getCurrentSectionOnly().
The documentation for this class was generated from the following files:
include/llvm/MC/ConstantPools.h
lib/MC/ConstantPools.cpp