LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerV2 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerV2 Class Reference final
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerV2 ()=default
~MetadataStreamerV2 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()
Detailed Description
Definition at line 121 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerV2()
llvm::AMDGPU::HSAMD::MetadataStreamerV2::MetadataStreamerV2 () default
~MetadataStreamerV2()
llvm::AMDGPU::HSAMD::MetadataStreamerV2::~MetadataStreamerV2 () default
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::begin (const Module & Mod) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 454 of file AMDGPUHSAMetadataStreamer.cpp.
emitKernel()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 470 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::AccQual, llvm::CallingConv::AMDGPU_KERNEL, llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::Function::args(), llvm::StringSwitch< T, R >::Case(), llvm::AMDGPU::HSAMD::Kernel::Key::CodeProps, AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPU::HSAMD::Kernel::Key::DebugProps, llvm::AMDGPU::HSAMD::Default, llvm::StringSwitch< T, R >::Default(), llvm::Type::DoubleTyID, llvm::errs(), llvm::StringRef::find(), AMDGPUAS::FLAT_ADDRESS, llvm::Type::FloatTyID, llvm::msgpack::Document::fromYAML(), llvm::Argument::getArgNo(), llvm::msgpack::Document::getArrayNode(), llvm::msgpack::DocNode::getDocument(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), llvm::Type::getIntegerBitWidth(), llvm::GlobalObject::getMetadata(), llvm::Module::getNamedMetadata(), llvm::msgpack::Document::getNode(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::Argument::getParent(), llvm::GlobalValue::getParent(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerElementType(), getType(), llvm::Type::getTypeID(), llvm::Attribute::getValueAsString(), llvm::Type::getVectorElementType(), AMDGPUAS::GLOBAL_ADDRESS, llvm::Type::HalfTyID, llvm::Function::hasFnAttribute(), llvm::Type::IntegerTyID, llvm::CodeModel::Kernel, llvm::AMDGPU::HSAMD::Kernel::Key::LanguageVersion, AMDGPUAS::LOCAL_ADDRESS, llvm::AMDGPU::HSAMD::Metadata::mKernels, llvm::None, llvm::StringRef::npos, llvm::MDNode::operands(), llvm::Type::PointerTyID, llvm::AMDGPU::HSAMD::Key::Printf, AMDGPUAS::PRIVATE_ADDRESS, llvm::msgpack::ArrayDocNode::push_back(), AMDGPUAS::REGION_ADDRESS, llvm::StringRef::startswith(), llvm::StringRef::str(), llvm::raw_string_ostream::str(), llvm::msgpack::Document::toYAML(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName, llvm::Type::VectorTyID, llvm::IndexedInstrProf::Version, llvm::AMDGPU::HSAMD::VersionMajor, and llvm::AMDGPU::HSAMD::VersionMinor.
emitTo()
bool llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitTo (AMDGPUTargetStreamer & TargetStreamer) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 450 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUTargetStreamer::EmitHSAMetadata().
end()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::end () override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 459 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::DumpHSAMetadata, llvm::AMDGPU::HSAMD::toString(), and llvm::VerifyHSAMetadata.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp