LLVM: llvm::object::ELFFile< ELFT > Class Template Reference
llvm::object::ELFFile< ELFT > Class Template Reference
#include "llvm/Object/ELF.h"
Public Types
using uintX_t = typename ELFT::uint
using Elf_Ehdr = typename ELFT::Ehdr
using Elf_Shdr = typename ELFT::Shdr
using Elf_Sym = typename ELFT::Sym
using Elf_Dyn = typename ELFT::Dyn
using Elf_Phdr = typename ELFT::Phdr
using Elf_Rel = typename ELFT::Rel
using Elf_Rela = typename ELFT::Rela
using Elf_Relr = typename ELFT::Relr
using Elf_Verdef = typename ELFT::Verdef
using Elf_Verdaux = typename ELFT::Verdaux
using Elf_Verneed = typename ELFT::Verneed
using Elf_Vernaux = typename ELFT::Vernaux
using Elf_Versym = typename ELFT::Versym
using Elf_Hash = typename ELFT::Hash
using Elf_GnuHash = typename ELFT::GnuHash
using Elf_Nhdr = typename ELFT::Nhdr
using Elf_Note = typename ELFT::Note
using Elf_Note_Iterator = typename ELFT::NoteIterator
using Elf_Dyn_Range = typename ELFT::DynRange
using Elf_Shdr_Range = typename ELFT::ShdrRange
using Elf_Sym_Range = typename ELFT::SymRange
using Elf_Rel_Range = typename ELFT::RelRange
using Elf_Rela_Range = typename ELFT::RelaRange
using Elf_Relr_Range = typename ELFT::RelrRange
using Elf_Phdr_Range = typename ELFT::PhdrRange
using WarningHandler = llvm::function_ref< Error(const Twine &Msg)>
Public Member Functions
const uint8_t * base () const
size_t getBufSize () const
const Elf_Ehdr * getHeader () const
template<typename T >
Expected< const T * > getEntry (uint32_t Section, uint32_t Entry) const
template<typename T >
Expected< const T * > getEntry (const Elf_Shdr *Section, uint32_t Entry) const
Expected< StringRef > getStringTable (const Elf_Shdr *Section, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< StringRef > getStringTableForSymtab (const Elf_Shdr &Section) const
Expected< StringRef > getStringTableForSymtab (const Elf_Shdr &Section, Elf_Shdr_Range Sections) const
Expected< ArrayRef< Elf_Word > > getSHNDXTable (const Elf_Shdr &Section) const
Expected< ArrayRef< Elf_Word > > getSHNDXTable (const Elf_Shdr &Section, Elf_Shdr_Range Sections) const
StringRef getRelocationTypeName (uint32_t Type) const
void getRelocationTypeName (uint32_t Type, SmallVectorImpl< char > &Result) const
uint32_t getRelativeRelocationType () const
std::string getDynamicTagAsString (unsigned Arch, uint64_t Type) const
std::string getDynamicTagAsString (uint64_t Type) const
Expected< const Elf_Sym * > getRelocationSymbol (const Elf_Rel *Rel, const Elf_Shdr *SymTab) const
Get the symbol for a given relocation.
bool isLE () const
bool isMipsELF64 () const
bool isMips64EL () const
Expected< Elf_Shdr_Range > sections () const
Expected< Elf_Dyn_Range > dynamicEntries () const
Expected< const uint8_t * > toMappedAddr (uint64_t VAddr) const
Expected< Elf_Sym_Range > symbols (const Elf_Shdr *Sec) const
Expected< Elf_Rela_Range > relas (const Elf_Shdr *Sec) const
Expected< Elf_Rel_Range > rels (const Elf_Shdr *Sec) const
Expected< Elf_Relr_Range > relrs (const Elf_Shdr *Sec) const
Expected< std::vector< Elf_Rela > > decode_relrs (Elf_Relr_Range relrs) const
Expected< std::vector< Elf_Rela > > android_relas (const Elf_Shdr *Sec) const
Expected< Elf_Phdr_Range > program_headers () const
Iterate over program header table.
Elf_Note_Iterator notes_begin (const Elf_Phdr &Phdr, Error &Err) const
Get an iterator over notes in a program header.
Elf_Note_Iterator notes_begin (const Elf_Shdr &Shdr, Error &Err) const
Get an iterator over notes in a section.
Elf_Note_Iterator notes_end () const
Get the end iterator for notes.
iterator_range< Elf_Note_Iterator > notes (const Elf_Phdr &Phdr, Error &Err) const
Get an iterator range over notes of a program header.
iterator_range< Elf_Note_Iterator > notes (const Elf_Shdr &Shdr, Error &Err) const
Get an iterator range over notes of a section.
Expected< StringRef > getSectionStringTable (Elf_Shdr_Range Sections, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< uint32_t > getSectionIndex (const Elf_Sym *Sym, Elf_Sym_Range Syms, ArrayRef< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (const Elf_Sym *Sym, const Elf_Shdr *SymTab, ArrayRef< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (const Elf_Sym *Sym, Elf_Sym_Range Symtab, ArrayRef< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (uint32_t Index) const
Expected< const Elf_Sym * > getSymbol (const Elf_Shdr *Sec, uint32_t Index) const
Expected< StringRef > getSectionName (const Elf_Shdr *Section, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< StringRef > getSectionName (const Elf_Shdr *Section, StringRef DotShstrtab) const
template<typename T >
Expected< ArrayRef< T > > getSectionContentsAsArray (const Elf_Shdr *Sec) const
Expected< ArrayRef< uint8_t > > getSectionContents (const Elf_Shdr *Sec) const
Static Public Member Functions
static Expected< ELFFile > create (StringRef Object)
Detailed Description
template<class ELFT>
class llvm::object::ELFFile< ELFT >
Definition at line 51 of file ELF.h.
Member Typedef Documentation
Elf_Dyn
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Dyn = typename ELFT::Dyn
Definition at line 79 of file ELF.h.
Elf_Dyn_Range
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Dyn_Range = typename ELFT::DynRange
Definition at line 94 of file ELF.h.
Elf_Ehdr
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Ehdr = typename ELFT::Ehdr
Definition at line 76 of file ELF.h.
Elf_GnuHash
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_GnuHash = typename ELFT::GnuHash
Definition at line 90 of file ELF.h.
Elf_Hash
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Hash = typename ELFT::Hash
Definition at line 89 of file ELF.h.
Elf_Nhdr
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Nhdr = typename ELFT::Nhdr
Definition at line 91 of file ELF.h.
Elf_Note
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Note = typename ELFT::Note
Definition at line 92 of file ELF.h.
Elf_Note_Iterator
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Note_Iterator = typename ELFT::NoteIterator
Definition at line 93 of file ELF.h.
Elf_Phdr
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Phdr = typename ELFT::Phdr
Definition at line 80 of file ELF.h.
Elf_Phdr_Range
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Phdr_Range = typename ELFT::PhdrRange
Definition at line 100 of file ELF.h.
Elf_Rel
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Rel = typename ELFT::Rel
Definition at line 81 of file ELF.h.
Elf_Rel_Range
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Rel_Range = typename ELFT::RelRange
Definition at line 97 of file ELF.h.
Elf_Rela
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Rela = typename ELFT::Rela
Definition at line 82 of file ELF.h.
Elf_Rela_Range
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Rela_Range = typename ELFT::RelaRange
Definition at line 98 of file ELF.h.
Elf_Relr
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Relr = typename ELFT::Relr
Definition at line 83 of file ELF.h.
Elf_Relr_Range
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Relr_Range = typename ELFT::RelrRange
Definition at line 99 of file ELF.h.
Elf_Shdr
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Shdr = typename ELFT::Shdr
Definition at line 77 of file ELF.h.
Elf_Shdr_Range
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Shdr_Range = typename ELFT::ShdrRange
Definition at line 95 of file ELF.h.
Elf_Sym
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Sym = typename ELFT::Sym
Definition at line 78 of file ELF.h.
Elf_Sym_Range
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Sym_Range = typename ELFT::SymRange
Definition at line 96 of file ELF.h.
Elf_Verdaux
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Verdaux = typename ELFT::Verdaux
Definition at line 85 of file ELF.h.
Elf_Verdef
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Verdef = typename ELFT::Verdef
Definition at line 84 of file ELF.h.
Elf_Vernaux
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Vernaux = typename ELFT::Vernaux
Definition at line 87 of file ELF.h.
Elf_Verneed
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Verneed = typename ELFT::Verneed
Definition at line 86 of file ELF.h.
Elf_Versym
template<class ELFT> using llvm::object::ELFFile< ELFT >::Elf_Versym = typename ELFT::Versym
Definition at line 88 of file ELF.h.
uintX_t
template<class ELFT> using llvm::object::ELFFile< ELFT >::uintX_t = typename ELFT::uint
Definition at line 75 of file ELF.h.
WarningHandler
template<class ELFT> using llvm::object::ELFFile< ELFT >::WarningHandler = llvm::function_ref<Error(const Twine &Msg)>
Definition at line 107 of file ELF.h.
Member Function Documentation
android_relas()
template<class ELFT> Expected< std::vector< typename ELFT::Rela > > ELFFile::android_relas (const Elf_Shdr * Sec) const
Definition at line 351 of file ELF.cpp.
References llvm::Expected< T >::takeError().
Referenced by llvm::object::ELFFile< ELFT >::relrs().
base()
template<class ELFT> const uint8_t* llvm::object::ELFFile< ELFT >::base () const inline
Definition at line 109 of file ELF.h.
References llvm::StringRef::bytes_begin().
Referenced by llvm::object::ELFFile< ELFT >::getEntry(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::object::ELFFile< ELFT >::program_headers(), and llvm::object::ELFFile< ELFT >::sections().
create()
template<class ELFT > Expected< ELFFile< ELFT > > llvm::object::ELFFile< ELFT >::create (StringRef Object) static
Definition at line 501 of file ELF.h.
References llvm::object::createError(), and llvm::StringRef::size().
Referenced by llvm::object::ELFObjectFile< ELFT >::create(), and llvm::object::ELFFile< ELFT >::getHeader().
decode_relrs()
template<class ELFT> Expected< std::vector< typename ELFT::Rela > > ELFFile::decode_relrs (Elf_Relr_Range relrs) const
Definition at line 272 of file ELF.cpp.
Referenced by llvm::object::ELFFile< ELFT >::relrs().
dynamicEntries()
template<class ELFT> Expected< typename ELFT::DynRange > ELFFile::dynamicEntries () const
Definition at line 500 of file ELF.cpp.
References llvm::ArrayRef< T >::back(), llvm::object::createError(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::empty(), llvm::makeArrayRef(), llvm::ELF::PT_DYNAMIC, llvm::ELF::SHT_DYNAMIC, and llvm::Expected< T >::takeError().
Referenced by llvm::object::ELFFile< ELFT >::isMips64EL().
getBufSize()
template<class ELFT> size_t llvm::object::ELFFile< ELFT >::getBufSize () const inline
Definition at line 111 of file ELF.h.
References llvm::StringRef::size().
Referenced by llvm::object::ELFFile< ELFT >::program_headers().
getDynamicTagAsString() [1/2]
template<class ELFT> std::string ELFFile::getDynamicTagAsString (unsigned Arch, uint64_t Type) const
Definition at line 431 of file ELF.cpp.
References llvm::ELF::EM_AARCH64, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC64, and llvm::utohexstr().
Referenced by llvm::object::ELFFile< ELFT >::getHeader().
getDynamicTagAsString() [2/2]
template<class ELFT> std::string ELFFile::getDynamicTagAsString (uint64_t Type) const
Definition at line 495 of file ELF.cpp.
getEntry() [1/2]
template<class ELFT > template<typename T > Expected< const T * > llvm::object::ELFFile< ELFT >::getEntry (uint32_t Section, uint32_t Entry) const
Definition at line 560 of file ELF.h.
References llvm::object::ELFFile< ELFT >::getSection().
Referenced by llvm::object::ELFFile< ELFT >::getHeader().
getEntry() [2/2]
template<class ELFT > template<typename T > Expected< const T * > llvm::object::ELFFile< ELFT >::getEntry (const Elf_Shdr * Section, uint32_t Entry) const
Definition at line 570 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base(), llvm::object::createError(), llvm::object::getSecIndexForError(), llvm::StringRef::size(), llvm::T, and llvm::Twine::utohexstr().
getHeader()
template<class ELFT> const Elf_Ehdr* llvm::object::ELFFile< ELFT >::getHeader () const inline
Definition at line 119 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base(), llvm::object::ELFFile< ELFT >::create(), llvm::object::defaultWarningHandler(), llvm::object::ELFFile< ELFT >::getDynamicTagAsString(), llvm::object::ELFFile< ELFT >::getEntry(), llvm::object::ELFFile< ELFT >::getRelativeRelocationType(), llvm::object::ELFFile< ELFT >::getRelocationSymbol(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::object::ELFFile< ELFT >::getStringTableForSymtab(), and llvm::ARMBuildAttrs::Section.
Referenced by llvm::object::ELFObjectFile< ELFT >::getArch(), llvm::object::ELFObjectFile< ELFT >::getFileFormatName(), llvm::object::ELFObjectFile< ELFT >::getPlatformFlags(), llvm::object::ELFFile< ELFT >::getRelativeRelocationType(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::ELFFile< ELFT >::getSectionStringTable(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::object::ELFObjectFile< ELFT >::getStartAddress(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::object::ELFFile< ELFT >::isLE(), llvm::object::ELFFile< ELFT >::isMipsELF64(), llvm::object::ELFObjectFile< ELFT >::isRelocatableObject(), llvm::object::ELFFile< ELFT >::program_headers(), and llvm::object::ELFFile< ELFT >::sections().
getRelativeRelocationType()
template<class ELFT > uint32_t llvm::object::ELFFile< ELFT >::getRelativeRelocationType () const
Definition at line 468 of file ELF.h.
References llvm::object::getELFRelativeRelocationType(), and llvm::object::ELFFile< ELFT >::getHeader().
Referenced by llvm::object::ELFFile< ELFT >::getHeader().
getRelocationSymbol()
template<class ELFT > Expected< const typename ELFT::Sym * > llvm::object::ELFFile< ELFT >::getRelocationSymbol (const Elf_Rel * Rel, const Elf_Shdr * SymTab) const
Get the symbol for a given relocation.
Definition at line 474 of file ELF.h.
References llvm::object::ELFFile< ELFT >::isMips64EL().
Referenced by llvm::object::ELFFile< ELFT >::getHeader().
getRelocationTypeName() [1/2]
template<class ELFT > StringRef llvm::object::ELFFile< ELFT >::getRelocationTypeName (uint32_t Type) const
Definition at line 432 of file ELF.h.
References llvm::object::getELFRelocationTypeName(), and llvm::object::ELFFile< ELFT >::getHeader().
Referenced by llvm::object::ELFFile< ELFT >::getHeader(), and llvm::object::ELFFile< ELFT >::getRelocationTypeName().
getRelocationTypeName() [2/2]
template<class ELFT > void llvm::object::ELFFile< ELFT >::getRelocationTypeName (uint32_t Type, SmallVectorImpl< char > & Result) const
Definition at line 437 of file ELF.h.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::ELFFile< ELFT >::isMipsELF64(), Name, Type2, and Type3.
getSection() [1/3]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (const Elf_Sym * Sym, const Elf_Shdr * SymTab, ArrayRef< Elf_Word > ShndxTable) const
Definition at line 353 of file ELF.h.
References llvm::object::ELFFile< ELFT >::symbols().
Referenced by llvm::object::ELFFile< ELFT >::getEntry(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), and llvm::object::ELFFile< ELFT >::getSection().
getSection() [2/3]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (const Elf_Sym * Sym, Elf_Sym_Range Symtab, ArrayRef< Elf_Word > ShndxTable) const
Definition at line 363 of file ELF.h.
References llvm::object::ELFFile< ELFT >::getSection(), and llvm::object::ELFFile< ELFT >::getSectionIndex().
getSection() [3/3]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (uint32_t Index) const
Definition at line 587 of file ELF.h.
References llvm::object::ELFFile< ELFT >::sections().
getSectionContents()
template<class ELFT > Expected< ArrayRef< uint8_t > > llvm::object::ELFFile< ELFT >::getSectionContents (const Elf_Shdr * Sec) const
Definition at line 427 of file ELF.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::getBuildAttributes().
getSectionContentsAsArray()
template<class ELFT > template<typename T > Expected< ArrayRef< T > > llvm::object::ELFFile< ELFT >::getSectionContentsAsArray (const Elf_Shdr * Sec) const
Definition at line 392 of file ELF.h.
References llvm::object::createError(), llvm::object::getSecIndexForError(), llvm::max(), Size, llvm::StringRef::size(), and llvm::Twine::utohexstr().
getSectionIndex()
template<class ELFT > Expected< uint32_t > llvm::object::ELFFile< ELFT >::getSectionIndex (const Elf_Sym * Sym, Elf_Sym_Range Syms, ArrayRef< Elf_Word > ShndxTable) const
Definition at line 336 of file ELF.h.
References llvm::ELF::SHN_LORESERVE, llvm::ELF::SHN_UNDEF, and llvm::ELF::SHN_XINDEX.
Referenced by llvm::object::ELFFile< ELFT >::getSection().
getSectionName() [1/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionName (const Elf_Shdr * Section, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 684 of file ELF.h.
References llvm::object::ELFFile< ELFT >::getSectionStringTable(), and llvm::object::ELFFile< ELFT >::sections().
getSectionName() [2/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionName (const Elf_Shdr * Section, StringRef DotShstrtab) const
Definition at line 696 of file ELF.h.
References llvm::object::createError(), llvm::StringRef::data(), llvm::object::getSecIndexForError(), llvm::StringRef::size(), and llvm::Twine::utohexstr().
getSectionStringTable()
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionStringTable (Elf_Shdr_Range Sections, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 484 of file ELF.h.
References llvm::object::createError(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::object::ELFFile< ELFT >::getStringTable(), and llvm::ELF::SHN_XINDEX.
Referenced by llvm::object::ELFFile< ELFT >::getSectionName().
getSHNDXTable() [1/2]
template<class ELFT > Expected< ArrayRef< typename ELFT::Word > > llvm::object::ELFFile< ELFT >::getSHNDXTable (const Elf_Shdr & Section) const
Definition at line 622 of file ELF.h.
References llvm::object::ELFFile< ELFT >::sections().
Referenced by llvm::object::ELFFile< ELFT >::getHeader().
getSHNDXTable() [2/2]
template<class ELFT > Expected< ArrayRef< typename ELFT::Word > > llvm::object::ELFFile< ELFT >::getSHNDXTable (const Elf_Shdr & Section, Elf_Shdr_Range Sections) const
Definition at line 631 of file ELF.h.
References assert(), llvm::object::createError(), llvm::object::getELFSectionTypeName(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::ARMBuildAttrs::Section, llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_SYMTAB, llvm::ELF::SHT_SYMTAB_SHNDX, and llvm::ArrayRef< T >::size().
getStringTable()
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTable (const Elf_Shdr * Section, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 596 of file ELF.h.
References llvm::ArrayRef< T >::back(), llvm::ArrayRef< T >::begin(), llvm::object::createError(), llvm::Data, E, llvm::ArrayRef< T >::empty(), llvm::object::getELFSectionTypeName(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::object::getSecIndexForError(), llvm::ARMBuildAttrs::Section, llvm::ELF::SHT_STRTAB, and llvm::ArrayRef< T >::size().
Referenced by llvm::object::ELFFile< ELFT >::getHeader(), llvm::object::ELFFile< ELFT >::getSectionStringTable(), and llvm::object::ELFFile< ELFT >::getStringTableForSymtab().
getStringTableForSymtab() [1/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTableForSymtab (const Elf_Shdr & Section) const
Definition at line 660 of file ELF.h.
References llvm::object::ELFFile< ELFT >::sections().
Referenced by llvm::object::ELFFile< ELFT >::getHeader().
getStringTableForSymtab() [2/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTableForSymtab (const Elf_Shdr & Section, Elf_Shdr_Range Sections) const
Definition at line 669 of file ELF.h.
References llvm::object::createError(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::ELF::SHT_DYNSYM, and llvm::ELF::SHT_SYMTAB.
getSymbol()
template<class ELFT > Expected< const typename ELFT::Sym * > llvm::object::ELFFile< ELFT >::getSymbol (const Elf_Shdr * Sec, uint32_t Index) const
Definition at line 376 of file ELF.h.
References llvm::object::createError(), llvm::object::getSecIndexForError(), and llvm::object::ELFFile< ELFT >::symbols().
isLE()
template<class ELFT> bool llvm::object::ELFFile< ELFT >::isLE () const inline
Definition at line 153 of file ELF.h.
References llvm::ELF::ELFDATA2LSB, and llvm::object::ELFFile< ELFT >::getHeader().
Referenced by llvm::object::ELFFile< ELFT >::isMips64EL().
isMips64EL()
template<class ELFT> bool llvm::object::ELFFile< ELFT >::isMips64EL () const inline
Definition at line 162 of file ELF.h.
References llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::object::ELFFile< ELFT >::isLE(), llvm::object::ELFFile< ELFT >::isMipsELF64(), llvm::object::ELFFile< ELFT >::sections(), and llvm::object::ELFFile< ELFT >::toMappedAddr().
Referenced by llvm::object::ELFFile< ELFT >::getRelocationSymbol().
isMipsELF64()
template<class ELFT> bool llvm::object::ELFFile< ELFT >::isMipsELF64 () const inline
Definition at line 157 of file ELF.h.
References llvm::ELF::ELFCLASS64, llvm::ELF::EM_MIPS, and llvm::object::ELFFile< ELFT >::getHeader().
Referenced by llvm::object::ELFFile< ELFT >::getRelocationTypeName(), and llvm::object::ELFFile< ELFT >::isMips64EL().
notes() [1/2]
template<class ELFT> iterator_range<Elf_Note_Iterator> llvm::object::ELFFile< ELFT >::notes (const Elf_Phdr & Phdr, Error & Err) const inline
Get an iterator range over notes of a program header.
The program header must be of type PT_NOTE.
Parameters
Phdr the program header to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 261 of file ELF.h.
notes() [2/2]
template<class ELFT> iterator_range<Elf_Note_Iterator> llvm::object::ELFFile< ELFT >::notes (const Elf_Shdr & Shdr, Error & Err) const inline
Get an iterator range over notes of a section.
The section must be of type SHT_NOTE.
Parameters
Shdr the section to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 273 of file ELF.h.
notes_begin() [1/2]
template<class ELFT> Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_begin (const Elf_Phdr & Phdr, Error & Err) const inline
Get an iterator over notes in a program header.
The program header must be of type PT_NOTE.
Parameters
Phdr the program header to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 217 of file ELF.h.
notes_begin() [2/2]
template<class ELFT> Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_begin (const Elf_Shdr & Shdr, Error & Err) const inline
Get an iterator over notes in a section.
The section must be of type SHT_NOTE.
Parameters
Shdr the section to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 236 of file ELF.h.
notes_end()
template<class ELFT> Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_end () const inline
Get the end iterator for notes.
Definition at line 250 of file ELF.h.
program_headers()
template<class ELFT> Expected<Elf_Phdr_Range> llvm::object::ELFFile< ELFT >::program_headers () const inline
Iterate over program header table.
Definition at line 193 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base(), llvm::object::createError(), llvm::object::ELFFile< ELFT >::getBufSize(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::makeArrayRef(), and llvm::Twine::utohexstr().
Referenced by llvm::symbolize::LLVMSymbolizer::flush().
relas()
template<class ELFT> Expected<Elf_Rela_Range> llvm::object::ELFFile< ELFT >::relas (const Elf_Shdr * Sec) const inline
Definition at line 176 of file ELF.h.
relrs()
template<class ELFT> Expected<Elf_Relr_Range> llvm::object::ELFFile< ELFT >::relrs (const Elf_Shdr * Sec) const inline
Definition at line 184 of file ELF.h.
References llvm::object::ELFFile< ELFT >::android_relas(), and llvm::object::ELFFile< ELFT >::decode_relrs().
rels()
template<class ELFT> Expected<Elf_Rel_Range> llvm::object::ELFFile< ELFT >::rels (const Elf_Shdr * Sec) const inline
Definition at line 180 of file ELF.h.
sections()
template<class ELFT > Expected< typename ELFT::ShdrRange > llvm::object::ELFFile< ELFT >::sections () const
Definition at line 510 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base(), llvm::object::createError(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::makeArrayRef(), llvm::StringRef::size(), UINT64_MAX, and llvm::Twine::utohexstr().
Referenced by llvm::object::ELFObjectFile< ELFT >::getBuildAttributes(), llvm::object::getSecIndexForError(), llvm::object::ELFFile< ELFT >::getSection(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::object::ELFFile< ELFT >::getStringTableForSymtab(), llvm::object::ELFFile< ELFT >::isMips64EL(), llvm::object::ELFObjectFile< ELFT >::section_begin(), llvm::object::ELFObjectFile< ELFT >::section_end(), and llvm::object::ELFObjectFile< ELFT >::toDRI().
symbols()
template<class ELFT> Expected<Elf_Sym_Range> llvm::object::ELFFile< ELFT >::symbols (const Elf_Shdr * Sec) const inline
Definition at line 170 of file ELF.h.
Referenced by llvm::object::ELFFile< ELFT >::getSection(), and llvm::object::ELFFile< ELFT >::getSymbol().
toMappedAddr()
template<class ELFT> Expected< const uint8_t * > ELFFile::toMappedAddr (uint64_t VAddr) const
Definition at line 557 of file ELF.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::object::createError(), llvm::SmallVectorTemplateCommon< T >::end(), I, llvm::ELF::PT_LOAD, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::upper_bound(), and llvm::Twine::utohexstr().
Referenced by llvm::object::ELFFile< ELFT >::isMips64EL().
The documentation for this class was generated from the following files:
include/llvm/Object/ELF.h
lib/Object/ELF.cpp