LLVM: llvm::DagInit Class Reference
llvm::DagInit Class Reference final
(v a, b) - Represent a DAG tree value.
#include "llvm/TableGen/Record.h"
Public Types
using const_arg_iterator = SmallVectorImpl< Init * >::const_iterator
using const_name_iterator = SmallVectorImpl< StringInit * >::const_iterator
Public Member Functions
DagInit (const DagInit &)=delete
DagInit & operator= (const DagInit &)=delete
void Profile (FoldingSetNodeID &ID) const
Init * getOperator () const
Record * getOperatorAsDef (ArrayRef< SMLoc > Loc) const
StringInit * getName () const
StringRef getNameStr () const
unsigned getNumArgs () const
Init * getArg (unsigned Num) const
StringInit * getArgName (unsigned Num) const
StringRef getArgNameStr (unsigned Num) const
ArrayRef< Init * > getArgs () const
ArrayRef< StringInit * > getArgNames () const
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a string form.
const_arg_iterator arg_begin () const
const_arg_iterator arg_end () const
size_t arg_size () const
bool arg_empty () const
const_name_iterator name_begin () const
const_name_iterator name_end () const
size_t name_size () const
bool name_empty () const
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::TrailingObjects< DagInit, Init *, StringInit *>
const T * getTrailingObjects () const
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
T * getTrailingObjects ()
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
Static Public Member Functions
static bool classof (const Init *I)
static DagInit * get (Init *V, StringInit *VN, ArrayRef< Init *> ArgRange, ArrayRef< StringInit *> NameRange)
static DagInit * get (Init *V, StringInit *VN, ArrayRef< std::pair< Init *, StringInit *>> Args)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TrailingObjects< DagInit, Init *, StringInit *>
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type additionalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the size of the trailing data, if an object were allocated with the given counts (The counts are in the same order as the template arguments).
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type totalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the total size of an object if it were allocated with the given trailing object counts.
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First, IK_FirstTypedInit, IK_BitInit, IK_BitsInit,
IK_CodeInit, IK_DagInit, IK_DefInit, IK_FieldInit,
IK_IntInit, IK_ListInit, IK_FirstOpInit, IK_BinOpInit,
IK_TernOpInit, IK_UnOpInit, IK_LastOpInit, IK_CondOpInit,
IK_FoldOpInit, IK_IsAOpInit, IK_StringInit, IK_VarInit,
IK_VarListElementInit, IK_VarBitInit, IK_VarDefInit, IK_LastTypedInit,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
(v a, b) - Represent a DAG tree value.
DAG inits are required to have at least one value then a (possibly empty) list of arguments. Each argument can have a name associated with it.
Definition at line 1302 of file Record.h.
Member Typedef Documentation
const_arg_iterator
using llvm::DagInit::const_arg_iterator = SmallVectorImpl<Init*>::const_iterator
Definition at line 1371 of file Record.h.
const_name_iterator
using llvm::DagInit::const_name_iterator = SmallVectorImpl<StringInit*>::const_iterator
Definition at line 1372 of file Record.h.
Constructor & Destructor Documentation
DagInit()
llvm::DagInit::DagInit (const DagInit &) delete
Member Function Documentation
arg_begin()
const_arg_iterator llvm::DagInit::arg_begin () const inline
Definition at line 1374 of file Record.h.
arg_empty()
bool llvm::DagInit::arg_empty () const inline
Definition at line 1378 of file Record.h.
arg_end()
const_arg_iterator llvm::DagInit::arg_end () const inline
Definition at line 1375 of file Record.h.
arg_size()
size_t llvm::DagInit::arg_size () const inline
Definition at line 1377 of file Record.h.
classof()
static bool llvm::DagInit::classof (const Init * I) inline static
Definition at line 1321 of file Record.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and llvm::Init::getKind().
get() [1/2]
DagInit * DagInit::get (Init * V, StringInit * VN, ArrayRef< Init *> ArgRange, ArrayRef< StringInit *> NameRange) static
Definition at line 1930 of file Record.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::FoldingSetImpl< T >::FindNodeOrInsertPos(), llvm::TrailingObjects< BaseTy, TrailingTys >::getTrailingObjects(), I, llvm::FoldingSetImpl< T >::InsertNode(), ProfileDagInit(), and llvm::ArrayRef< T >::size().
Referenced by llvm::BinOpInit::Fold(), ForeachDagApply(), get(), and resolveReferences().
get() [2/2]
DagInit * DagInit::get (Init * V, StringInit * VN, ArrayRef< std::pair< Init *, StringInit *>> Args) static
Definition at line 1952 of file Record.cpp.
References Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, get(), and llvm::SmallVectorTemplateBase< T >::push_back().
getArg()
Init* llvm::DagInit::getArg (unsigned Num) const inline
Definition at line 1343 of file Record.h.
References assert().
Referenced by llvm::BinOpInit::Fold(), and ForeachDagApply().
getArgName()
StringInit* llvm::DagInit::getArgName (unsigned Num) const inline
Definition at line 1348 of file Record.h.
References assert().
Referenced by llvm::BinOpInit::Fold(), and ForeachDagApply().
getArgNames()
ArrayRef<StringInit *> llvm::DagInit::getArgNames () const inline
Definition at line 1362 of file Record.h.
References llvm::RecTy::getAsString(), and llvm::makeArrayRef().
getArgNameStr()
StringRef llvm::DagInit::getArgNameStr (unsigned Num) const inline
Definition at line 1353 of file Record.h.
References llvm::StringInit::getValue().
getArgs()
ArrayRef<Init *> llvm::DagInit::getArgs () const inline
Definition at line 1358 of file Record.h.
References llvm::makeArrayRef().
getAsString()
std::string DagInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 2003 of file Record.cpp.
References llvm::numbers::e.
Referenced by llvm::BinOpInit::Fold().
getBit()
Init* llvm::DagInit::getBit (unsigned Bit) const inline override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1386 of file Record.h.
References llvm_unreachable.
getName()
StringInit* llvm::DagInit::getName () const inline
Definition at line 1335 of file Record.h.
getNameStr()
StringRef llvm::DagInit::getNameStr () const inline
Definition at line 1337 of file Record.h.
References llvm::StringInit::getValue().
getNumArgs()
unsigned llvm::DagInit::getNumArgs () const inline
Definition at line 1341 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), and ForeachDagApply().
getOperator()
Init* llvm::DagInit::getOperator () const inline
Definition at line 1332 of file Record.h.
Referenced by llvm::SetTheory::evaluate(), llvm::BinOpInit::Fold(), and ForeachDagApply().
getOperatorAsDef()
Record * DagInit::getOperatorAsDef (ArrayRef< SMLoc > Loc) const
Definition at line 1969 of file Record.cpp.
References llvm::PrintFatalError().
isConcrete()
bool DagInit::isConcrete () const override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 1993 of file Record.cpp.
name_begin()
const_name_iterator llvm::DagInit::name_begin () const inline
Definition at line 1380 of file Record.h.
name_empty()
bool llvm::DagInit::name_empty () const inline
Definition at line 1384 of file Record.h.
name_end()
const_name_iterator llvm::DagInit::name_end () const inline
Definition at line 1381 of file Record.h.
name_size()
size_t llvm::DagInit::name_size () const inline
Definition at line 1383 of file Record.h.
operator=()
DagInit& llvm::DagInit::operator= (const DagInit &) delete
Profile()
void DagInit::Profile (FoldingSetNodeID & ID) const
Definition at line 1965 of file Record.cpp.
References llvm::makeArrayRef(), and ProfileDagInit().
resolveReferences()
Init * DagInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1976 of file Record.cpp.
References Arg, get(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp