LLVM: llvm::TGLexer Class Reference
llvm::TGLexer Class Reference
TGLexer - TableGen Lexer class.
#include "TableGen/TGLexer.h"
Public Types
typedef std::set< std::string > DependenciesSetTy
Public Member Functions
TGLexer (SourceMgr &SrcMgr, ArrayRef< std::string > Macros)
tgtok::TokKind Lex ()
const DependenciesSetTy & getDependencies () const
tgtok::TokKind getCode () const
const std::string & getCurStrVal () const
int64_t getCurIntVal () const
std::pair< int64_t, unsigned > getCurBinaryIntVal () const
SMLoc getLoc () const
Detailed Description
TGLexer - TableGen Lexer class.
Definition at line 74 of file TGLexer.h.
Member Typedef Documentation
DependenciesSetTy
typedef std::set<std::string> llvm::TGLexer::DependenciesSetTy
Definition at line 91 of file TGLexer.h.
Constructor & Destructor Documentation
TGLexer()
TGLexer::TGLexer (SourceMgr & SrcMgr, ArrayRef< std::string > Macros)
Definition at line 46 of file TGLexer.cpp.
References llvm::StringRef::begin(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::for_each(), llvm::MemoryBuffer::getBuffer(), llvm::SourceMgr::getMainFileID(), llvm::SourceMgr::getMemoryBuffer(), and llvm::StringSet< AllocatorTy >::insert().
Member Function Documentation
getCode()
tgtok::TokKind llvm::TGLexer::getCode () const inline
Definition at line 108 of file TGLexer.h.
getCurBinaryIntVal()
std::pair<int64_t, unsigned> llvm::TGLexer::getCurBinaryIntVal () const inline
Definition at line 120 of file TGLexer.h.
References assert(), and llvm::tgtok::BinaryIntVal.
getCurIntVal()
int64_t llvm::TGLexer::getCurIntVal () const inline
Definition at line 116 of file TGLexer.h.
References assert(), and llvm::tgtok::IntVal.
getCurStrVal()
const std::string& llvm::TGLexer::getCurStrVal () const inline
Definition at line 110 of file TGLexer.h.
References assert(), llvm::tgtok::CodeFragment, llvm::tgtok::Id, llvm::tgtok::StrVal, and llvm::tgtok::VarName.
getDependencies()
const DependenciesSetTy& llvm::TGLexer::getDependencies () const inline
Definition at line 104 of file TGLexer.h.
Referenced by llvm::TGParser::getDependencies().
getLoc()
SMLoc TGLexer::getLoc () const
Definition at line 63 of file TGLexer.cpp.
References llvm::SourceMgr::AddIncludeFile(), llvm::StringRef::begin(), llvm::tgtok::BinaryIntVal, llvm::tgtok::Bit, llvm::tgtok::Bits, llvm::StringSwitch< T, R >::Case(), llvm::tgtok::Class, llvm::tgtok::Code, llvm::tgtok::CodeFragment, llvm::tgtok::colon, llvm::tgtok::comma, llvm::tgtok::Dag, llvm::tgtok::Def, llvm::StringSwitch< T, R >::Default(), llvm::tgtok::Defm, llvm::tgtok::Defset, llvm::tgtok::Defvar, llvm::tgtok::ElseKW, llvm::StringRef::end(), llvm::tgtok::Eof, llvm::tgtok::equal, llvm::tgtok::Error, llvm::tgtok::Field, llvm::SourceMgr::FindBufferContainingLoc(), llvm::tgtok::Foreach, llvm::MemoryBuffer::getBuffer(), llvm::SMLoc::getFromPointer(), llvm::SourceMgr::getMemoryBuffer(), llvm::SourceMgr::getParentIncludeLoc(), llvm::SMLoc::getPointer(), llvm::tgtok::greater, llvm::tgtok::Id, llvm::tgtok::If, llvm::tgtok::In, llvm::tgtok::Int, llvm::tgtok::IntVal, llvm::tgtok::l_brace, llvm::tgtok::l_paren, llvm::tgtok::l_square, llvm::tgtok::less, llvm::tgtok::Let, Lex(), llvm::tgtok::List, LLVM_FALLTHROUGH, llvm::tgtok::minus, llvm::tgtok::MultiClass, llvm::tgtok::paste, llvm::tgtok::period, llvm::tgtok::plus, llvm::PrintError(), llvm::PrintFatalError(), llvm::tgtok::question, llvm::tgtok::r_brace, llvm::tgtok::r_paren, llvm::tgtok::r_square, llvm::tgtok::semi, llvm::tgtok::String, llvm::tgtok::StrVal, llvm::tgtok::Then, and llvm::tgtok::VarName.
Referenced by llvm::TGParser::TokError().
Lex()
tgtok::TokKind llvm::TGLexer::Lex () inline
Definition at line 100 of file TGLexer.h.
References llvm::StringRef::begin().
Referenced by getLoc().
The documentation for this class was generated from the following files:
lib/TableGen/TGLexer.h
lib/TableGen/TGLexer.cpp