LLVM: llvm::DIType Class Reference
llvm::DIType Class Reference
Base class for types.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
TempDIType clone () const
unsigned getLine () const
uint64_t getSizeInBits () const
uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
uint64_t getOffsetInBits () const
DIFlags getFlags () const
DIScope * getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
TempDIType cloneWithFlags (DIFlags NewFlags) const
Returns a new temporary DIType with updated Flags.
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isBitField () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isTypePassByValue () const
bool isTypePassByReference () const
bool isBigEndian () const
bool isLittleEndian () const
bool getExportSymbols () const
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
Optional< StringRef > getSource () const
StringRef getName () const
DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
unsigned getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Protected Member Functions
DIType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, ArrayRef< Metadata *> Ops)
~DIType ()=default
void init (unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags)
void mutate (unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags)
Change fields in place.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata *> Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata *> Ops1, ArrayRef< Metadata *> Ops2=None)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata *> Ops1, ArrayRef< Metadata *> Ops2=None)
~MDNode ()=default
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic, FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Base class for types.
TODO: Remove the hardcoded name and context, since many types don't use them. TODO: Split up flags.
Definition at line 583 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DIType()
llvm::DIType::DIType (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, ArrayRef< Metadata *> Ops) inline protected
Definition at line 591 of file DebugInfoMetadata.h.
References llvm::cl::init().
~DIType()
llvm::DIType::~DIType () protected default
Member Function Documentation
classof()
static bool llvm::DIType::classof (const Metadata * MD) inline static
Definition at line 672 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
TempDIType llvm::DIType::clone () const inline
Definition at line 617 of file DebugInfoMetadata.h.
References llvm::MDNode::clone(), and llvm::release.
cloneWithFlags()
TempDIType llvm::DIType::cloneWithFlags (DIFlags NewFlags) const inline
Returns a new temporary DIType with updated Flags.
Definition at line 636 of file DebugInfoMetadata.h.
Referenced by createTypeWithFlags().
getAlignInBits()
uint32_t llvm::DIType::getAlignInBits () const inline
Definition at line 623 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), and rotateSign().
getAlignInBytes()
uint32_t llvm::DIType::getAlignInBytes () const inline
Definition at line 624 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::DwarfUnit::constructTypeDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), and llvm::DwarfUnit::getParentContextString().
getExportSymbols()
bool llvm::DIType::getExportSymbols () const inline
Definition at line 670 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
getFlags()
DIFlags llvm::DIType::getFlags () const inline
Definition at line 626 of file DebugInfoMetadata.h.
Referenced by createTypeWithFlags(), hasConflictingReferenceFlags(), hasVectorBeenPadded(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), llvm::MDNodeKeyImpl< DISubroutineType >::isKeyOf(), isNonTrivial(), rotateSign(), shouldAlwaysEmitCompleteClassType(), and translatePtrToMemberRep().
getLine()
unsigned llvm::DIType::getLine () const inline
Definition at line 621 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::addSourceLine(), getCommonClassOptions(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), and rotateSign().
getName()
StringRef llvm::DIType::getName () const inline
Definition at line 629 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfCompileUnit::addGlobalType(), llvm::DwarfCompileUnit::addGlobalTypeUnitType(), llvm::DwarfUnit::addRnglistsBase(), llvm::BTFDebug::BTFDebug(), calcArraySize(), llvm::BTFTypeDerived::completeType(), llvm::BTFTypeEnum::completeType(), llvm::BTFTypeStruct::completeType(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::DwarfUnit::constructTypeDIE(), llvm::BTFDebug::endFunctionImpl(), llvm::BTFTypeStruct::getName(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfUnit::getParentContextString(), isUnsignedDIType(), shouldAlwaysEmitCompleteClassType(), and shouldEmitUdt().
getOffsetInBits()
uint64_t llvm::DIType::getOffsetInBits () const inline
Definition at line 625 of file DebugInfoMetadata.h.
Referenced by llvm::BTFDebug::BTFDebug(), calcArraySize(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), rotateSign(), and shouldAlwaysEmitCompleteClassType().
getRawName()
MDString* llvm::DIType::getRawName () const inline
Definition at line 633 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::createTypeDIE(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isODRMember(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual(), and rotateSign().
getRawScope()
Metadata* llvm::DIType::getRawScope () const inline
Definition at line 632 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags(), isDINode(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isODRMember(), and llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual().
getScope()
DIScope* llvm::DIType::getScope () const inline
Definition at line 628 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::createTypeDIE(), getCommonClassOptions(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), hasVectorBeenPadded(), llvm::DebugInfoFinder::processLocation(), rotateSign(), and shouldEmitUdt().
getSizeInBits()
uint64_t llvm::DIType::getSizeInBits () const inline
Definition at line 622 of file DebugInfoMetadata.h.
Referenced by llvm::BTFDebug::BTFDebug(), llvm::BTFTypeEnum::BTFTypeEnum(), llvm::BTFTypeStruct::BTFTypeStruct(), calcArraySize(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::DwarfUnit::constructTypeDIE(), dwarfCCToCodeView(), llvm::DebugHandlerBase::getBaseTypeSize(), llvm::DwarfUnit::getParentContextString(), hasVectorBeenPadded(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), rotateSign(), shouldAlwaysEmitCompleteClassType(), shouldEmitUdt(), and translatePtrToMemberRep().
init()
void llvm::DIType::init (unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags) inline protected
Definition at line 599 of file DebugInfoMetadata.h.
isAppleBlockExtension()
bool llvm::DIType::isAppleBlockExtension () const inline
Definition at line 652 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isArtificial()
bool llvm::DIType::isArtificial () const inline
Definition at line 654 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::DwarfUnit::constructSubprogramArguments(), and llvm::DIBuilder::createArtificialType().
isBigEndian()
bool llvm::DIType::isBigEndian () const inline
Definition at line 668 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::getParentContextString(), and isDINode().
isBitField()
bool llvm::DIType::isBitField () const inline
Definition at line 660 of file DebugInfoMetadata.h.
References getFlags().
Referenced by calcArraySize(), and shouldAlwaysEmitCompleteClassType().
isForwardDecl()
bool llvm::DIType::isForwardDecl () const inline
Definition at line 651 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::BTFDebug::BTFDebug(), llvm::DwarfUnit::constructTypeDIE(), llvm::DwarfUnit::createTypeDIE(), getCommonClassOptions(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfUnit::getParentContextString(), shouldAlwaysEmitCompleteClassType(), and shouldEmitUdt().
isLittleEndian()
bool llvm::DIType::isLittleEndian () const inline
Definition at line 669 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::getParentContextString(), and isDINode().
isLValueReference()
bool llvm::DIType::isLValueReference () const inline
Definition at line 662 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructSubprogramArguments().
isObjcClassComplete()
bool llvm::DIType::isObjcClassComplete () const inline
Definition at line 656 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isObjectPointer()
bool llvm::DIType::isObjectPointer () const inline
Definition at line 655 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DIBuilder::createObjectPointerType(), and shouldEmitUdt().
isPrivate()
bool llvm::DIType::isPrivate () const inline
Definition at line 642 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs(), and llvm::DwarfUnit::getOrCreateStaticMemberDIE().
isProtected()
bool llvm::DIType::isProtected () const inline
Definition at line 645 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs(), and llvm::DwarfUnit::getOrCreateStaticMemberDIE().
isPublic()
bool llvm::DIType::isPublic () const inline
Definition at line 648 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs(), and llvm::DwarfUnit::getOrCreateStaticMemberDIE().
isRValueReference()
bool llvm::DIType::isRValueReference () const inline
Definition at line 663 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructSubprogramArguments().
isStaticMember()
bool llvm::DIType::isStaticMember () const inline
Definition at line 661 of file DebugInfoMetadata.h.
References getFlags().
Referenced by shouldAlwaysEmitCompleteClassType().
isTypePassByReference()
bool llvm::DIType::isTypePassByReference () const inline
Definition at line 665 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isTypePassByValue()
bool llvm::DIType::isTypePassByValue () const inline
Definition at line 664 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isVector()
bool llvm::DIType::isVector () const inline
Definition at line 659 of file DebugInfoMetadata.h.
References getFlags().
Referenced by hasConflictingReferenceFlags(), and hasVectorBeenPadded().
isVirtual()
bool llvm::DIType::isVirtual () const inline
Definition at line 653 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs().
mutate()
void llvm::DIType::mutate (unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags) inline protected
Change fields in place.
Definition at line 609 of file DebugInfoMetadata.h.
References assert(), and llvm::cl::init().
The documentation for this class was generated from the following file:
include/llvm/IR/DebugInfoMetadata.h