LLVM: llvm::ScheduleDAGSDNodes::RegDefIter Class Reference
llvm::ScheduleDAGSDNodes::RegDefIter Class Reference
RegDefIter - In place iteration over the values defined by an SUnit.
#include "CodeGen/SelectionDAG/ScheduleDAGSDNodes.h"
Public Member Functions
RegDefIter (const SUnit *SU, const ScheduleDAGSDNodes *SD)
bool IsValid () const
MVT GetValue () const
const SDNode * GetNode () const
unsigned GetIdx () const
void Advance ()
Detailed Description
RegDefIter - In place iteration over the values defined by an SUnit.
This does not need copies of the iterator or any other STLisms. The iterator creates itself, rather than being provided by the SchedDAG.
Definition at line 138 of file ScheduleDAGSDNodes.h.
Constructor & Destructor Documentation
RegDefIter()
ScheduleDAGSDNodes::RegDefIter::RegDefIter (const SUnit * SU, const ScheduleDAGSDNodes * SD)
Definition at line 575 of file ScheduleDAGSDNodes.cpp.
References Advance().
Member Function Documentation
Advance()
void ScheduleDAGSDNodes::RegDefIter::Advance ()
Definition at line 583 of file ScheduleDAGSDNodes.cpp.
References llvm::SDNode::getGluedNode(), llvm::SDNode::getSimpleValueType(), and llvm::SDNode::hasAnyUseOfValue().
Referenced by GetIdx(), and RegDefIter().
GetIdx()
unsigned llvm::ScheduleDAGSDNodes::RegDefIter::GetIdx () const inline
Definition at line 159 of file ScheduleDAGSDNodes.h.
References Advance().
GetNode()
const SDNode* llvm::ScheduleDAGSDNodes::RegDefIter::GetNode () const inline
Definition at line 155 of file ScheduleDAGSDNodes.h.
GetValue()
MVT llvm::ScheduleDAGSDNodes::RegDefIter::GetValue () const inline
Definition at line 150 of file ScheduleDAGSDNodes.h.
References assert(), and IsValid().
Referenced by GetCostForDef().
IsValid()
bool llvm::ScheduleDAGSDNodes::RegDefIter::IsValid () const inline
Definition at line 148 of file ScheduleDAGSDNodes.h.
Referenced by CalcNodeSethiUllmanNumber(), and GetValue().
The documentation for this class was generated from the following files:
lib/CodeGen/SelectionDAG/ScheduleDAGSDNodes.h
lib/CodeGen/SelectionDAG/ScheduleDAGSDNodes.cpp