LLVM: llvm::AnalysisManager< IRUnitT, ExtraArgTs > Class Template Reference
llvm::AnalysisManager< IRUnitT, ExtraArgTs > Class Template Reference
A container for analyses that lazily runs them and caches their results.
#include "llvm/Analysis/InstructionSimplify.h"
Classes
class Invalidator
API to communicate dependencies between analyses during invalidation.
Public Member Functions
AnalysisManager (bool DebugLogging=false)
Construct an empty analysis manager.
AnalysisManager (AnalysisManager &&)=default
AnalysisManager & operator= (AnalysisManager &&)=default
bool empty () const
Returns true if the analysis manager has an empty results cache.
void clear (IRUnitT &IR, llvm::StringRef Name)
Clear any cached analysis results for a single unit of IR.
void clear ()
Clear all analysis results cached by this AnalysisManager.
template<typename PassT >
PassT::Result & getResult (IRUnitT &IR, ExtraArgTs... ExtraArgs)
Get the result of an analysis pass for a given IR unit.
template<typename PassT >
PassT::Result * getCachedResult (IRUnitT &IR) const
Get the cached result of an analysis pass for a given IR unit.
template<typename PassBuilderT >
bool registerPass (PassBuilderT &&PassBuilder)
Register an analysis pass with the manager.
template<typename PassT >
void invalidate (IRUnitT &IR)
Invalidate a specific analysis pass for an IR module.
void invalidate (IRUnitT &IR, const PreservedAnalyses &PA)
Invalidate cached analyses for an IR unit.
Detailed Description
template<typename IRUnitT, typename... ExtraArgTs>
class llvm::AnalysisManager< IRUnitT, ExtraArgTs >
A container for analyses that lazily runs them and caches their results.
This class can manage analyses for any IR unit where the address of the IR unit sufficies as its identity.
Definition at line 41 of file InstructionSimplify.h.
Constructor & Destructor Documentation
AnalysisManager() [1/2]
template<typename IRUnitT, typename... ExtraArgTs> llvm::AnalysisManager< IRUnitT, ExtraArgTs >::AnalysisManager (bool DebugLogging = false) inline
Construct an empty analysis manager.
If DebugLogging is true, we'll log our progress to llvm::dbgs().
Definition at line 730 of file PassManager.h.
AnalysisManager() [2/2]
template<typename IRUnitT, typename... ExtraArgTs> llvm::AnalysisManager< IRUnitT, ExtraArgTs >::AnalysisManager (AnalysisManager< IRUnitT, ExtraArgTs > &&) default
Member Function Documentation
clear() [1/2]
template<typename IRUnitT, typename... ExtraArgTs> void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear (IRUnitT & IR, llvm::StringRef Name) inline
Clear any cached analysis results for a single unit of IR.
This doesn't invalidate, but instead simply deletes, the relevant results. It is useful when the IR is being removed and we want to clear out all the memory pinned for it.
Definition at line 747 of file PassManager.h.
References llvm::dbgs(), and llvm::StringRef::find().
Referenced by llvm::InlinerPass::run().
clear() [2/2]
template<typename IRUnitT, typename... ExtraArgTs> void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear () inline
Clear all analysis results cached by this AnalysisManager.
Like clear(IRUnitT&), this doesn't invalidate the results; it simply deletes them. This lets you clean up the AnalysisManager when the set of IR units itself has potentially changed, and thus we can't even look up a a result and invalidate/clear it directly.
Definition at line 768 of file PassManager.h.
empty()
template<typename IRUnitT, typename... ExtraArgTs> bool llvm::AnalysisManager< IRUnitT, ExtraArgTs >::empty () const inline
Returns true if the analysis manager has an empty results cache.
Definition at line 735 of file PassManager.h.
References assert().
getCachedResult()
template<typename IRUnitT, typename... ExtraArgTs> template<typename PassT > PassT::Result* llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult (IRUnitT & IR) const inline
Get the cached result of an analysis pass for a given IR unit.
This method never runs the analysis.
Returns
null if there is no cached result.
Definition at line 796 of file PassManager.h.
References assert().
Referenced by incorporateNewSCCRange(), llvm::orc::BlockFreqQuery::operator()(), llvm::MergeICmpsPass::run(), llvm::LibCallsShrinkWrapPass::run(), llvm::DCEPass::run(), llvm::BreakCriticalEdgesPass::run(), llvm::ADCEPass::run(), llvm::InstCombinePass::run(), llvm::LowerConstantIntrinsicsPass::run(), llvm::LCSSAPass::run(), llvm::LoopSimplifyPass::run(), llvm::TailCallElimPass::run(), llvm::InternalizePass::run(), llvm::GVN::run(), llvm::SLPVectorizerPass::run(), llvm::PGOMemOPSizeOpt::run(), llvm::InlinerPass::run(), llvm::LazyValueAnalysis::run(), llvm::LoopUnrollPass::run(), llvm::LoopVectorizePass::run(), and llvm::BasicAA::run().
getResult()
template<typename IRUnitT, typename... ExtraArgTs> template<typename PassT > PassT::Result& llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult (IRUnitT & IR, ExtraArgTs... ExtraArgs) inline
Get the result of an analysis pass for a given IR unit.
Runs the analysis if a cached result is not available.
Definition at line 777 of file PassManager.h.
References assert().
Referenced by llvm::createSampleProfileLoaderPass(), llvm::orc::BlockFreqQuery::operator()(), llvm::SyntheticCountsPropagation::run(), llvm::LoadStoreVectorizerPass::run(), llvm::BoundsCheckingPass::run(), llvm::ExpandReductionsPass::run(), llvm::CallSiteSplittingPass::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::MergeICmpsPass::run(), llvm::CGProfilePass::run(), llvm::InjectTLIMappings::run(), llvm::LibCallsShrinkWrapPass::run(), llvm::GCOVProfilerPass::run(), llvm::IRCEPass::run(), llvm::IVUsersPrinterPass::run(), llvm::LoopAccessInfoPrinterPass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::SinkingPass::run(), llvm::PromotePass::run(), llvm::DivRemPairsPass::run(), llvm::LoopFusePass::run(), llvm::NewGVNPass::run(), llvm::ScalarizerPass::run(), llvm::ControlHeightReductionPass::run(), llvm::InferFunctionAttrsPass::run(), llvm::PartialInlinerPass::run(), llvm::BDCEPass::run(), llvm::LoopPredicationPass::run(), llvm::LoopUnrollAndJamPass::run(), llvm::GlobalOptPass::run(), llvm::Float2IntPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::LoopDistributePass::run(), llvm::GuardWideningPass::run(), llvm::LoopLoadEliminationPass::run(), llvm::WarnMissedTransformationsPass::run(), llvm::ThreadSanitizerPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AlignmentFromAssumptionsPass::run(), llvm::AggressiveInstCombinePass::run(), llvm::LoopIdiomRecognizePass::run(), llvm::RewriteStatepointsForGC::run(), llvm::DSEPass::run(), llvm::SampleProfileLoaderPass::run(), llvm::IPSCCPPass::run(), llvm::ADCEPass::run(), llvm::EarlyCSEPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::ThinLTOBitcodeWriterPass::run(), llvm::LoopSinkPass::run(), llvm::LoopStrengthReducePass::run(), llvm::AlwaysInlinerPass::run(), llvm::InstSimplifyPass::run(), llvm::InstCombinePass::run(), llvm::SCCPPass::run(), llvm::LCSSAPass::run(), llvm::InstrProfiling::run(), llvm::MemorySanitizerPass::run(), llvm::SafepointIRVerifierPass::run(), llvm::LoopFullUnrollPass::run(), llvm::StackSafetyAnalysis::run(), llvm::SCEVAA::run(), llvm::SimplifyCFGPass::run(), llvm::MemCpyOptPass::run(), llvm::PGOInstrumentationGen::run(), llvm::ModuleSummaryIndexAnalysis::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::PassManager< Function >::run(), llvm::LoopSimplifyPass::run(), llvm::StackSafetyPrinterPass::run(), llvm::LICMPass::run(), llvm::AAEvaluator::run(), llvm::TailCallElimPass::run(), llvm::PGOInstrumentationUse::run(), llvm::HotColdSplittingPass::run(), llvm::PostDominatorTreePrinterPass::run(), llvm::ReversePostOrderFunctionAttrsPass::run(), llvm::GVN::run(), llvm::BitcodeWriterPass::run(), llvm::SpeculativeExecutionPass::run(), llvm::SLPVectorizerPass::run(), llvm::PGOIndirectCallPromotion::run(), llvm::StackSafetyGlobalAnalysis::run(), llvm::PGOMemOPSizeOpt::run(), llvm::StackSafetyGlobalPrinterPass::run(), llvm::CFLAndersAA::run(), llvm::JumpThreadingPass::run(), llvm::InlinerPass::run(), llvm::AddressSanitizerPass::run(), llvm::NaryReassociatePass::run(), llvm::SpeculateAroundPHIsPass::run(), llvm::SROA::run(), llvm::DemandedBitsAnalysis::run(), llvm::CFLSteensAA::run(), llvm::BlockFrequencyAnalysis::run(), llvm::ModuleAddressSanitizerPass::run(), llvm::ConstantHoistingPass::run(), llvm::DemandedBitsPrinterPass::run(), llvm::BlockFrequencyPrinterPass::run(), llvm::LazyValueAnalysis::run(), llvm::GlobalsAA::run(), llvm::PhiValuesPrinterPass::run(), llvm::LoopUnrollPass::run(), llvm::VerifierPass::run(), llvm::LoopVectorizePass::run(), llvm::OptimizationRemarkEmitterAnalysis::run(), llvm::AssumptionPrinterPass::run(), llvm::DominanceFrontierAnalysis::run(), llvm::ProfileSummaryPrinterPass::run(), llvm::DominanceFrontierPrinterPass::run(), llvm::BranchProbabilityAnalysis::run(), llvm::BranchProbabilityPrinterPass::run(), llvm::BasicAA::run(), llvm::WholeProgramDevirtPass::run(), llvm::DominatorTreePrinterPass::run(), llvm::DominatorTreeVerifierPass::run(), llvm::FunctionToLoopPassAdaptor< LoopPassT >::run(), llvm::PredicateInfoPrinterPass::run(), llvm::PredicateInfoVerifierPass::run(), llvm::GVNHoistPass::run(), llvm::CallGraphPrinterPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::run(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::DDGAnalysisPrinterPass::run(), llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run(), llvm::MemoryDependenceAnalysis::run(), llvm::DevirtSCCRepeatedPass< PassT >::run(), llvm::DependenceAnalysis::run(), llvm::MemorySSAAnalysis::run(), llvm::DependenceAnalysisPrinterPass::run(), llvm::MemorySSAPrinterPass::run(), llvm::MemorySSAVerifierPass::run(), llvm::RegionInfoAnalysis::run(), llvm::RegionInfoPrinterPass::run(), llvm::RegionInfoVerifierPass::run(), llvm::AAManager::run(), llvm::LoopAnalysis::run(), llvm::LoopPrinterPass::run(), llvm::LoopVerifierPass::run(), llvm::LazyCallGraphAnalysis::run(), llvm::LazyCallGraphPrinterPass::run(), llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::run(), llvm::LazyCallGraphDOTPrinterPass::run(), llvm::ScalarEvolutionAnalysis::run(), llvm::ScalarEvolutionVerifierPass::run(), llvm::ScalarEvolutionPrinterPass::run(), and updateNewSCCFunctionAnalyses().
invalidate() [1/2]
template<typename IRUnitT, typename... ExtraArgTs> template<typename PassT > void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate (IRUnitT & IR) inline
Invalidate a specific analysis pass for an IR module.
Note that the analysis result can disregard invalidation, if it determines it is in fact still valid.
Definition at line 849 of file PassManager.h.
References assert().
Referenced by incorporateNewSCCRange(), llvm::PassManager< Function >::run(), llvm::FunctionToLoopPassAdaptor< LoopPassT >::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::run(), llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run(), llvm::DevirtSCCRepeatedPass< PassT >::run(), and llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::run().
invalidate() [2/2]
template<typename IRUnitT, typename... ExtraArgTs> void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate (IRUnitT & IR, const PreservedAnalyses & PA) inline
Invalidate cached analyses for an IR unit.
Walk through all of the analyses pertaining to this unit of IR and invalidate them, unless they are preserved by the PreservedAnalyses set.
Definition at line 859 of file PassManager.h.
References llvm::PreservedAnalyses::allAnalysesInSetPreserved(), assert(), llvm::dbgs(), E, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, llvm::AnalysisInfoMixin< PassInstrumentationAnalysis >::ID(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), IR, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), P, llvm::PassInstrumentation::runAfterAnalysis(), llvm::PassInstrumentation::runBeforeAnalysis(), and second.
operator=()
template<typename IRUnitT, typename... ExtraArgTs> AnalysisManager& llvm::AnalysisManager< IRUnitT, ExtraArgTs >::operator= (AnalysisManager< IRUnitT, ExtraArgTs > &&) default
registerPass()
template<typename IRUnitT, typename... ExtraArgTs> template<typename PassBuilderT > bool llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass (PassBuilderT && PassBuilder) inline
Register an analysis pass with the manager.
The parameter is a callable whose result is an analysis pass. This allows passing in a lambda to construct the analysis.
The analysis type to register is the type returned by calling the PassBuilder argument. If that type has already been registered, then the argument will not be called and this function will return false. Otherwise, we register the analysis returned by calling PassBuilder(), and this function returns true.
(Note: Although the return value of this function indicates whether or not an analysis was previously registered, there intentionally isn't a way to query this directly. Instead, you should just register all the analyses you might want and let this class run them lazily. This idiom lets us minimize the number of times we have to look up analyses in our hashtable.)
Definition at line 829 of file PassManager.h.
Referenced by llvm::PassBuilder::crossRegisterProxies(), and eliminateDeadCode().
The documentation for this class was generated from the following files:
include/llvm/Analysis/InstructionSimplify.h
include/llvm/IR/PassManager.h