LLVM: llvm::SwingSchedulerDAG Class Reference
llvm::SwingSchedulerDAG Class Reference
This class builds the dependence graph for the instructions in a loop, and attempts to schedule the instructions using the SMS algorithm.
#include "llvm/CodeGen/MachinePipeliner.h"
Public Member Functions
SwingSchedulerDAG (MachinePipeliner &P, MachineLoop &L, LiveIntervals &lis, const RegisterClassInfo &rci, unsigned II)
void schedule () override
We override the schedule function in ScheduleDAGInstrs to implement the scheduling part of the Swing Modulo Scheduling algorithm.
void finishBlock () override
Clean up after the software pipeliner runs.
bool hasNewSchedule ()
Return true if the loop kernel has been scheduled.
int getASAP (SUnit *Node)
Return the earliest time an instruction may be scheduled.
int getALAP (SUnit *Node)
Return the latest time an instruction my be scheduled.
int getMOV (SUnit *Node)
The mobility function, which the number of slots in which an instruction may be scheduled.
unsigned getDepth (SUnit *Node)
The depth, in the dependence graph, for a node.
int getZeroLatencyDepth (SUnit *Node)
The maximum unweighted length of a path from an arbitrary node to the given node in which each edge has latency 0.
unsigned getHeight (SUnit *Node)
The height, in the dependence graph, for a node.
int getZeroLatencyHeight (SUnit *Node)
The maximum unweighted length of a path from the given node to an arbitrary node in which each edge has latency 0.
bool isBackedge (SUnit *Source, const SDep &Dep)
Return true if the dependence is a back-edge in the data dependence graph.
bool isLoopCarriedDep (SUnit *Source, const SDep &Dep, bool isSucc=true)
Return true for an order or output dependence that is loop carried potentially.
unsigned getDistance (SUnit *U, SUnit *V, const SDep &Dep)
The distance function, which indicates that operation V of iteration I depends on operations U of iteration I-distance.
void applyInstrChange (MachineInstr *MI, SMSchedule &Schedule)
Apply changes to the instruction if needed.
void fixupRegisterOverlaps (std::deque< SUnit *> &Instrs)
Attempt to fix the degenerate cases when the instruction serialization causes the register lifetimes to overlap.
unsigned getInstrBaseReg (SUnit *SU)
Return the new base register that was stored away for the changed instruction.
void addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation)
Public Member Functions inherited from llvm::ScheduleDAGInstrs
ScheduleDAGInstrs (MachineFunction &mf, const MachineLoopInfo *mli, bool RemoveKillFlags=false)
~ScheduleDAGInstrs () override=default
const TargetSchedModel * getSchedModel () const
Gets the machine model for instruction scheduling.
const MCSchedClassDesc * getSchedClass (SUnit *SU) const
Resolves and cache a resolved scheduling class for an SUnit.
MachineBasicBlock::iterator begin () const
Returns an iterator to the top of the current scheduling region.
MachineBasicBlock::iterator end () const
Returns an iterator to the bottom of the current scheduling region.
SUnit * newSUnit (MachineInstr *MI)
Creates a new SUnit and return a ptr to it.
SUnit * getSUnit (MachineInstr *MI) const
Returns an existing SUnit for this MI, or nullptr.
virtual bool doMBBSchedRegionsTopDown () const
If this method returns true, handling of the scheduling regions themselves (in case of a scheduling boundary in MBB) will be done beginning with the topmost region of MBB.
virtual void startBlock (MachineBasicBlock *BB)
Prepares to perform scheduling in the given block.
virtual void enterRegion (MachineBasicBlock *bb, MachineBasicBlock::iterator begin, MachineBasicBlock::iterator end, unsigned regioninstrs)
Initialize the DAG and common scheduler state for a new scheduling region.
virtual void exitRegion ()
Called when the scheduler has finished scheduling the current region.
void buildSchedGraph (AAResults *AA, RegPressureTracker *RPTracker=nullptr, PressureDiffs *PDiffs=nullptr, LiveIntervals *LIS=nullptr, bool TrackLaneMasks=false)
Builds SUnits for the current region.
void addSchedBarrierDeps ()
Adds dependencies from instructions in the current list of instructions being scheduled to scheduling barrier.
virtual void finalizeSchedule ()
Allow targets to perform final scheduling actions at the level of the whole MachineFunction.
void dumpNode (const SUnit &SU) const override
void dump () const override
std::string getGraphNodeLabel (const SUnit *SU) const override
Returns a label for a DAG node that points to an instruction.
std::string getDAGName () const override
Returns a label for the region of code covered by the DAG.
void fixupKills (MachineBasicBlock &MBB)
Fixes register kill flags that scheduling has made invalid.
bool canAddEdge (SUnit *SuccSU, SUnit *PredSU)
True if an edge can be added from PredSU to SuccSU without creating a cycle.
bool addEdge (SUnit *SuccSU, const SDep &PredDep)
Add a DAG edge to the given SU with the given predecessor dependence data.
Public Member Functions inherited from llvm::ScheduleDAG
ScheduleDAG (MachineFunction &mf)
virtual ~ScheduleDAG ()
void clearDAG ()
Clears the DAG state (between regions).
const MCInstrDesc * getInstrDesc (const SUnit *SU) const
Returns the MCInstrDesc of this SUnit.
virtual void viewGraph (const Twine &Name, const Twine &Title)
Pops up a GraphViz/gv window with the ScheduleDAG rendered using 'dot'.
virtual void viewGraph ()
Out-of-line implementation with no arguments is handy for gdb.
void dumpNodeName (const SUnit &SU) const
virtual void addCustomGraphFeatures (GraphWriter< ScheduleDAG *> &) const
Adds custom features for a visualization of the ScheduleDAG.
unsigned VerifyScheduledDAG (bool isBottomUp)
Verifies that all SUnits were scheduled and that their state is consistent.
Static Public Member Functions
static bool classof (const ScheduleDAGInstrs *DAG)
Additional Inherited Members
Public Types inherited from llvm::ScheduleDAGInstrs
using SUList = std::list< SUnit * >
A list of SUnits, used in Value2SUsMap, during DAG construction.
Public Attributes inherited from llvm::ScheduleDAG
const LLVMTargetMachine & TM
Target processor.
const TargetInstrInfo * TII
Target instruction information.
const TargetRegisterInfo * TRI
Target processor register info.
MachineFunction & MF
Machine function.
MachineRegisterInfo & MRI
Virtual/real register map.
std::vector< SUnit > SUnits
The scheduling units.
SUnit EntrySU
Special node for the region entry.
SUnit ExitSU
Special node for the region exit.
bool StressSched
Protected Types inherited from llvm::ScheduleDAGInstrs
using DbgValueVector = std::vector< std::pair< MachineInstr *, MachineInstr * > >
Protected Member Functions inherited from llvm::ScheduleDAGInstrs
void reduceHugeMemNodeMaps (Value2SUsMap &stores, Value2SUsMap &loads, unsigned N)
Reduces maps in FIFO order, by N SUs.
void addChainDependency (SUnit *SUa, SUnit *SUb, unsigned Latency=0)
Adds a chain edge between SUa and SUb, but only if both AAResults and Target fail to deny the dependency.
void addChainDependencies (SUnit *SU, SUList &SUs, unsigned Latency)
Adds dependencies as needed from all SUs in list to SU.
void addChainDependencies (SUnit *SU, Value2SUsMap &Val2SUsMap)
Adds dependencies as needed from all SUs in map, to SU.
void addChainDependencies (SUnit *SU, Value2SUsMap &Val2SUsMap, ValueType V)
Adds dependencies as needed to SU, from all SUs mapped to V.
void addBarrierChain (Value2SUsMap &map)
Adds barrier chain edges from all SUs in map, and then clear the map.
void insertBarrierChain (Value2SUsMap &map)
Inserts a barrier chain in a huge region, far below current SU.
void initSUnits ()
Creates an SUnit for each real instruction, numbered in top-down topological order.
void addPhysRegDataDeps (SUnit *SU, unsigned OperIdx)
MO is an operand of SU's instruction that defines a physical register.
void addPhysRegDeps (SUnit *SU, unsigned OperIdx)
Adds register dependencies (data, anti, and output) from this SUnit to following instructions in the same scheduling region that depend the physical register referenced at OperIdx.
void addVRegDefDeps (SUnit *SU, unsigned OperIdx)
Adds register output and data dependencies from this SUnit to instructions that occur later in the same scheduling region if they read from or write to the virtual register defined at OperIdx.
void addVRegUseDeps (SUnit *SU, unsigned OperIdx)
Adds a register data dependency if the instruction that defines the virtual register used at OperIdx is mapped to an SUnit.
void startBlockForKills (MachineBasicBlock *BB)
Initializes register live-range state for updating kills.
void toggleKillFlag (MachineInstr &MI, MachineOperand &MO)
Toggles a register operand kill flag.
LaneBitmask getLaneMaskForMO (const MachineOperand &MO) const
Returns a mask for which lanes get read/written by the given (register) machine operand.
bool deadDefHasNoUse (const MachineOperand &MO)
Returns true if the def register in MO has no uses.
Protected Member Functions inherited from llvm::ScheduleDAG
void dumpNodeAll (const SUnit &SU) const
Protected Attributes inherited from llvm::ScheduleDAGInstrs
const MachineLoopInfo * MLI
const MachineFrameInfo & MFI
TargetSchedModel SchedModel
TargetSchedModel provides an interface to the machine model.
bool RemoveKillFlags
True if the DAG builder should remove kill flags (in preparation for rescheduling).
bool CanHandleTerminators = false
The standard DAG builder does not normally include terminators as DAG nodes because it does not create the necessary dependencies to prevent reordering.
bool TrackLaneMasks = false
Whether lane masks should get tracked.
MachineBasicBlock * BB
The block in which to insert instructions.
MachineBasicBlock::iterator RegionBegin
The beginning of the range to be scheduled.
MachineBasicBlock::iterator RegionEnd
The end of the range to be scheduled.
unsigned NumRegionInstrs
Instructions in this region (distance(RegionBegin, RegionEnd)).
DenseMap< MachineInstr *, SUnit * > MISUnitMap
After calling BuildSchedGraph, each machine instruction in the current scheduling region is mapped to an SUnit.
Reg2SUnitsMap Defs
Defs, Uses - Remember where defs and uses of each register are as we iterate upward through the instructions.
Reg2SUnitsMap Uses
VReg2SUnitMultiMap CurrentVRegDefs
Tracks the last instruction(s) in this region defining each virtual register.
VReg2SUnitOperIdxMultiMap CurrentVRegUses
Tracks the last instructions in this region using each virtual register.
AAResults * AAForDep = nullptr
SUnit * BarrierChain = nullptr
Remember a generic side-effecting instruction as we proceed.
UndefValue * UnknownValue
For an unanalyzable memory access, this Value is used in maps.
ScheduleDAGTopologicalSort Topo
Topo - A topological ordering for SUnits which permits fast IsReachable and similar queries.
DbgValueVector DbgValues
Remember instruction that precedes DBG_VALUE.
MachineInstr * FirstDbgValue = nullptr
LivePhysRegs LiveRegs
Set of live physical registers for updating kill flags.
Detailed Description
This class builds the dependence graph for the instructions in a loop, and attempts to schedule the instructions using the SMS algorithm.
Definition at line 112 of file MachinePipeliner.h.
Constructor & Destructor Documentation
SwingSchedulerDAG()
llvm::SwingSchedulerDAG::SwingSchedulerDAG (MachinePipeliner & P, MachineLoop & L, LiveIntervals & lis, const RegisterClassInfo & rci, unsigned II) inline
Definition at line 200 of file MachinePipeliner.h.
References llvm::TargetSubtargetInfo::getSMSMutations(), llvm::MachineFunction::getSubtarget(), and llvm::MachinePipeliner::MF.
Member Function Documentation
addMutation()
void llvm::SwingSchedulerDAG::addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation) inline
Definition at line 278 of file MachinePipeliner.h.
applyInstrChange()
void SwingSchedulerDAG::applyInstrChange (MachineInstr * MI, SMSchedule & Schedule)
Apply changes to the instruction if needed.
The changes are need to improve the scheduling and depend up on the final schedule.
Definition at line 2150 of file MachinePipeliner.cpp.
References llvm::MachineFunction::CloneMachineInstr(), llvm::SMSchedule::cycleScheduled(), llvm::tgtok::Def, llvm::numbers::e, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::TargetInstrInfo::getBaseAndOffsetPosition(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineInstr::isPHI(), llvm::MachinePipeliner::MF, MI, MRI, Reg, llvm::MachineOperand::setImm(), llvm::SUnit::setInstr(), llvm::MachineOperand::setReg(), llvm::SMSchedule::stageScheduled(), and llvm::MachinePipeliner::TII.
Referenced by llvm::SMSchedule::finalizeSchedule().
classof()
static bool llvm::SwingSchedulerDAG::classof (const ScheduleDAGInstrs * DAG) inline static
Definition at line 282 of file MachinePipeliner.h.
References llvm::computeDelta(), and Reg.
finishBlock()
void SwingSchedulerDAG::finishBlock () override virtual
Clean up after the software pipeliner runs.
Reimplemented from llvm::ScheduleDAGInstrs.
Definition at line 570 of file MachinePipeliner.cpp.
References llvm::MachineFunction::DeleteMachineInstr(), llvm::ScheduleDAGInstrs::finishBlock(), and llvm::MachinePipeliner::MF.
fixupRegisterOverlaps()
void SwingSchedulerDAG::fixupRegisterOverlaps (std::deque< SUnit *> & Instrs)
Attempt to fix the degenerate cases when the instruction serialization causes the register lifetimes to overlap.
For example, p' = store_pi(p, b) = load p, offset In this case p and p' overlap, which means that two registers are needed. Instead, this function changes the load to use p' and updates the offset.
Definition at line 2761 of file MachinePipeliner.cpp.
References llvm::MachineFunction::CloneMachineInstr(), llvm::numbers::e, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::TargetInstrInfo::getBaseAndOffsetPosition(), llvm::MachineOperand::getImm(), llvm::SUnit::getInstr(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToUseOperand(), llvm::MachineOperand::isUse(), llvm::MachinePipeliner::MF, MI, llvm::MachineOperand::setImm(), llvm::SUnit::setInstr(), llvm::MachineOperand::setReg(), and llvm::MachinePipeliner::TII.
Referenced by llvm::SMSchedule::finalizeSchedule().
getALAP()
int llvm::SwingSchedulerDAG::getALAP (SUnit * Node) inline
Return the latest time an instruction my be scheduled.
Definition at line 219 of file MachinePipeliner.h.
References llvm::SUnit::NodeNum.
getASAP()
int llvm::SwingSchedulerDAG::getASAP (SUnit * Node) inline
Return the earliest time an instruction may be scheduled.
Definition at line 216 of file MachinePipeliner.h.
References llvm::SUnit::NodeNum.
getDepth()
unsigned llvm::SwingSchedulerDAG::getDepth (SUnit * Node) inline
The depth, in the dependence graph, for a node.
Definition at line 226 of file MachinePipeliner.h.
References llvm::SUnit::getDepth().
Referenced by llvm::NodeSet::computeNodeSetInfo().
getDistance()
unsigned llvm::SwingSchedulerDAG::getDistance (SUnit * U, SUnit * V, const SDep & Dep) inline
The distance function, which indicates that operation V of iteration I depends on operations U of iteration I-distance.
Definition at line 256 of file MachinePipeliner.h.
References llvm::SDep::Anti, llvm::SUnit::getInstr(), llvm::SDep::getKind(), llvm::MachineInstr::isPHI(), and MI.
Referenced by llvm::SMSchedule::computeStart().
getHeight()
unsigned llvm::SwingSchedulerDAG::getHeight (SUnit * Node) inline
The height, in the dependence graph, for a node.
Definition at line 235 of file MachinePipeliner.h.
References llvm::SUnit::getHeight().
getInstrBaseReg()
unsigned llvm::SwingSchedulerDAG::getInstrBaseReg (SUnit * SU) inline
Return the new base register that was stored away for the changed instruction.
Definition at line 270 of file MachinePipeliner.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by llvm::SMSchedule::orderDependence().
getMOV()
int llvm::SwingSchedulerDAG::getMOV (SUnit * Node) inline
The mobility function, which the number of slots in which an instruction may be scheduled.
Definition at line 223 of file MachinePipeliner.h.
Referenced by llvm::NodeSet::computeNodeSetInfo().
getZeroLatencyDepth()
int llvm::SwingSchedulerDAG::getZeroLatencyDepth (SUnit * Node) inline
The maximum unweighted length of a path from an arbitrary node to the given node in which each edge has latency 0.
Definition at line 230 of file MachinePipeliner.h.
References llvm::SUnit::NodeNum.
getZeroLatencyHeight()
int llvm::SwingSchedulerDAG::getZeroLatencyHeight (SUnit * Node) inline
The maximum unweighted length of a path from the given node to an arbitrary node in which each edge has latency 0.
Definition at line 239 of file MachinePipeliner.h.
References llvm::SUnit::NodeNum.
hasNewSchedule()
bool llvm::SwingSchedulerDAG::hasNewSchedule () inline
Return true if the loop kernel has been scheduled.
Definition at line 213 of file MachinePipeliner.h.
isBackedge()
bool llvm::SwingSchedulerDAG::isBackedge (SUnit * Source, const SDep & Dep) inline
Return true if the dependence is a back-edge in the data dependence graph.
Since the DAG doesn't contain cycles, we represent a cycle in the graph using an anti dependence from a Phi to an instruction.
Definition at line 246 of file MachinePipeliner.h.
References llvm::SDep::Anti, llvm::SUnit::getInstr(), llvm::SDep::getKind(), llvm::SDep::getSUnit(), llvm::MachineInstr::isPHI(), and llvm::Sched::Source.
Referenced by llvm::SMSchedule::computeStart(), and multipleIterations().
isLoopCarriedDep()
bool SwingSchedulerDAG::isLoopCarriedDep (SUnit * Source, const SDep & Dep, bool isSucc = true)
Return true for an order or output dependence that is loop carried potentially.
A dependence is loop carried if the destination defines a valu that may be used or defined by the source in a subsequent iteration.
Definition at line 2205 of file MachinePipeliner.cpp.
References assert(), llvm::computeDelta(), D, llvm::tgtok::Def, llvm::TargetInstrInfo::getIncrementValue(), llvm::SUnit::getInstr(), llvm::SDep::getKind(), llvm::TargetInstrInfo::getMemOperandWithOffset(), getPhiRegs(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::SDep::getSUnit(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::SDep::isArtificial(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineInstr::isPHI(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayRaiseFPException(), llvm::MachineInstr::mayStore(), llvm::MachineInstr::memoperands_begin(), llvm::MachinePipeliner::MF, MRI, llvm::SDep::Order, llvm::SDep::Output, SI, std::swap(), SwpPruneLoopCarried, llvm::MachinePipeliner::TII, TRI, and llvm::MemoryLocation::UnknownSize.
Referenced by llvm::SMSchedule::computeStart(), and swapAntiDependences().
schedule()
void SwingSchedulerDAG::schedule () override virtual
We override the schedule function in ScheduleDAGInstrs to implement the scheduling part of the Swing Modulo Scheduling algorithm.
Implements llvm::ScheduleDAGInstrs.
Definition at line 425 of file MachinePipeliner.cpp.
References assert(), llvm::ModuloScheduleExpander::cleanup(), llvm::dbgs(), llvm::Pass::dump(), EmitTestAnnotations, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::ModuloScheduleExpander::expand(), llvm::PeelingModuloScheduleExpander::expand(), ExperimentalCodeGen, llvm::Pass::getAnalysis(), llvm::SMSchedule::getFinalCycle(), llvm::SMSchedule::getFirstCycle(), llvm::SMSchedule::getInstructions(), llvm::SMSchedule::getMaxStageCount(), I, LLVM_DEBUG, llvm::MachinePipeliner::MF, llvm::stable_sort(), llvm::SMSchedule::stageScheduled(), SwpIgnoreRecMII, SwpMaxMii, and SwpMaxStages.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePipeliner.h
lib/CodeGen/MachinePipeliner.cpp