LLVM: llvm::LiveQueryResult Class Reference
llvm::LiveQueryResult Class Reference
Result of a LiveRange query.
#include "llvm/CodeGen/LiveInterval.h"
Public Member Functions
LiveQueryResult (VNInfo *EarlyVal, VNInfo *LateVal, SlotIndex EndPoint, bool Kill)
VNInfo * valueIn () const
Return the value that is live-in to the instruction.
bool isKill () const
Return true if the live-in value is killed by this instruction.
bool isDeadDef () const
Return true if this instruction has a dead def.
VNInfo * valueOut () const
Return the value leaving the instruction, if any.
VNInfo * valueOutOrDead () const
Returns the value alive at the end of the instruction, if any.
VNInfo * valueDefined () const
Return the value defined by this instruction, if any.
SlotIndex endPoint () const
Return the end point of the last live range segment to interact with the instruction, if any.
Detailed Description
Result of a LiveRange query.
This class hides the implementation details of live ranges, and it should be used as the primary interface for examining live ranges around instructions.
Definition at line 89 of file LiveInterval.h.
Constructor & Destructor Documentation
LiveQueryResult()
llvm::LiveQueryResult::LiveQueryResult (VNInfo * EarlyVal, VNInfo * LateVal, SlotIndex EndPoint, bool Kill) inline
Definition at line 96 of file LiveInterval.h.
Member Function Documentation
endPoint()
SlotIndex llvm::LiveQueryResult::endPoint () const inline
Return the end point of the last live range segment to interact with the instruction, if any.
The end point is an invalid SlotIndex only if the live range doesn't intersect the instruction at all.
The end point may be at or past the end of the instruction's basic block. That means the value was live out of the block.
Definition at line 146 of file LiveInterval.h.
Referenced by llvm::LiveIntervals::pruneValue().
isDeadDef()
bool llvm::LiveQueryResult::isDeadDef () const inline
Return true if this instruction has a dead def.
Definition at line 116 of file LiveInterval.h.
References llvm::SlotIndex::isDead().
Referenced by llvm::RegisterOperands::detectDeadDefs().
isKill()
bool llvm::LiveQueryResult::isKill () const inline
Return true if the live-in value is killed by this instruction.
This means that either the live range ends at the instruction, or it changes value.
Definition at line 111 of file LiveInterval.h.
References llvm::RegState::Kill.
Referenced by addSegmentsWithValNo(), llvm::LiveRangeEdit::eraseVirtReg(), and isFullCopyOf().
valueDefined()
VNInfo* llvm::LiveQueryResult::valueDefined () const inline
Return the value defined by this instruction, if any.
This includes dead defs, it is the value created by the instruction's def operands.
Definition at line 134 of file LiveInterval.h.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute(), and llvm::LiveIntervals::shrinkToUses().
valueIn()
VNInfo* llvm::LiveQueryResult::valueIn () const inline
Return the value that is live-in to the instruction.
This is the value that will be read by the instruction's use operands. Return NULL if no value is live-in.
Definition at line 104 of file LiveInterval.h.
Referenced by llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), definesFullReg(), llvm::ConnectedVNInfoEqClasses::Distribute(), isRematerializable(), llvm::LiveIntervals::pruneValue(), llvm::LiveIntervals::shrinkToUses(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
valueOut()
VNInfo* llvm::LiveQueryResult::valueOut () const inline
Return the value leaving the instruction, if any.
This can be a live-through value, or a live def. A dead def returns NULL.
Definition at line 122 of file LiveInterval.h.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute().
valueOutOrDead()
VNInfo* llvm::LiveQueryResult::valueOutOrDead () const inline
Returns the value alive at the end of the instruction, if any.
This can be a live-through value, a live def or a dead def.
Definition at line 128 of file LiveInterval.h.
Referenced by addSegmentsWithValNo(), and llvm::LiveIntervals::pruneValue().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/LiveInterval.h