LLVM: llvm::LegacyAARGetter Class Reference
llvm::LegacyAARGetter Class Reference
This class is a functor to be used in legacy module or SCC passes for computing AA results for a function.
#include "llvm/Analysis/BasicAliasAnalysis.h"
Public Member Functions
LegacyAARGetter (Pass &P)
AAResults & operator() (Function &F)
Detailed Description
This class is a functor to be used in legacy module or SCC passes for computing AA results for a function.
We store the results in fields so that they live long enough to be queried, but we re-use them each time.
Definition at line 261 of file BasicAliasAnalysis.h.
Constructor & Destructor Documentation
LegacyAARGetter()
llvm::LegacyAARGetter::LegacyAARGetter (Pass & P) inline
Definition at line 267 of file BasicAliasAnalysis.h.
Member Function Documentation
operator()()
AAResults& llvm::LegacyAARGetter::operator() (Function & F) inline
Definition at line 268 of file BasicAliasAnalysis.h.
References llvm::createLegacyPMAAResults(), llvm::createLegacyPMBasicAAResult(), and llvm::Optional< T >::emplace().
The documentation for this class was generated from the following file:
include/llvm/Analysis/BasicAliasAnalysis.h