LLVM: llvm::MCInst Class Reference
llvm::MCInst Class Reference
Instances of this class represent a single low-level machine instruction.
#include "llvm/MC/MCInst.h"
Public Types
using iterator = SmallVectorImpl< MCOperand >::iterator
using const_iterator = SmallVectorImpl< MCOperand >::const_iterator
Public Member Functions
MCInst ()=default
void setOpcode (unsigned Op)
unsigned getOpcode () const
void setFlags (unsigned F)
unsigned getFlags () const
void setLoc (SMLoc loc)
SMLoc getLoc () const
const MCOperand & getOperand (unsigned i) const
MCOperand & getOperand (unsigned i)
unsigned getNumOperands () const
void addOperand (const MCOperand &Op)
void clear ()
void erase (iterator I)
void erase (iterator First, iterator Last)
size_t size () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator insert (iterator I, const MCOperand &Op)
void print (raw_ostream &OS) const
void dump () const
void dump_pretty (raw_ostream &OS, const MCInstPrinter *Printer=nullptr, StringRef Separator=" ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given.
void dump_pretty (raw_ostream &OS, StringRef Name, StringRef Separator=" ") const
Detailed Description
Instances of this class represent a single low-level machine instruction.
Definition at line 158 of file MCInst.h.
Member Typedef Documentation
const_iterator
using llvm::MCInst::const_iterator = SmallVectorImpl<MCOperand>::const_iterator
Definition at line 187 of file MCInst.h.
iterator
using llvm::MCInst::iterator = SmallVectorImpl<MCOperand>::iterator
Definition at line 186 of file MCInst.h.
Constructor & Destructor Documentation
MCInst()
llvm::MCInst::MCInst () default
Member Function Documentation
addOperand()
void llvm::MCInst::addOperand (const MCOperand & Op) inline
Definition at line 184 of file MCInst.h.
References llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::X86Operand::addAbsMemOperands(), llvm::HexagonMCInstrInfo::addConstant(), llvm::HexagonMCInstrInfo::addConstExtender(), llvm::X86Operand::addDstIdxOperands(), llvm::MCInstBuilder::addExpr(), llvm::X86Operand::addExpr(), llvm::MCInstBuilder::addFPImm(), llvm::X86Operand::addGR32orGR64Operands(), llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addInst(), llvm::X86Operand::addMaskPairOperands(), llvm::X86Operand::addMemOffsOperands(), llvm::X86Operand::addMemOperands(), addNegOperand(), llvm::MCInstBuilder::addOperand(), addOperand(), addOps(), addOptionalImmOperand(), llvm::MCInstBuilder::addReg(), llvm::X86Operand::addRegOperands(), llvm::X86Operand::addSrcIdxOperands(), adjustDuplex(), NoAutoPaddingScope::changeAndComment(), convertTailJumpOpcode(), llvm::HexagonMCShuffler::copyTo(), covertDoubleImmToSingleImm(), Decode2RImmInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), DecodeACC64DSPRegisterClass(), DecodeAddiGroupBranch(), DecodeAddiur2Simm7(), DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddrMode5FP16Operand(), DecodeAddrMode5Operand(), DecodeAddrMode6Operand(), DecodeAddrModeImm12Operand(), DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeAdrInstruction(), DecodeAFGR64RegisterClass(), DecodeANDI16Imm(), DecodeArmMOVTWInstruction(), DecodeASRRegsRegisterClass(), DecodeBankedReg(), decodeBDAddr12Operand(), decodeBDAddr20Operand(), decodeBDLAddr12Len4Operand(), decodeBDLAddr12Len8Operand(), decodeBDRAddr12Operand(), decodeBDVAddr12Operand(), decodeBDXAddr12Operand(), decodeBDXAddr20Operand(), DecodeBFAfterTargetOperand(), DecodeBFLabelOperand(), DecodeBgtzGroupBranch(), DecodeBgtzGroupBranchMMR6(), DecodeBgtzlGroupBranch(), DecodeBitfieldMaskOperand(), DecodeBitpOperand(), DecodeBlezGroupBranch(), DecodeBlezGroupBranchMMR6(), DecodeBlezlGroupBranch(), decodeBranch(), DecodeBranchImmInstruction(), DecodeBranchTarget(), DecodeBranchTarget10MM(), DecodeBranchTarget1SImm16(), DecodeBranchTarget21(), DecodeBranchTarget21MM(), DecodeBranchTarget26(), DecodeBranchTarget26MM(), DecodeBranchTarget7MM(), DecodeBranchTargetMM(), DecodeCacheeOp_CacheOpR6(), DecodeCacheOp(), DecodeCacheOpMM(), DecodeCall(), DecodeCCOutOperand(), DecodeCCRRegisterClass(), DecodeCGImm(), DecodeCLRMGPRRegisterClass(), decodeCLUIImmOperand(), DecodeCOP0RegisterClass(), DecodeCOP2RegisterClass(), DecodeCopMemInstruction(), DecodeCoprocessor(), DecodeCPPairRegisterClass(), DecodeCPRegsRegisterClass(), DecodeCPSInstruction(), decodeCRBitMOperand(), DecodeCRC(), DecodeCtrRegs64RegisterClass(), DecodeCtrRegsRegisterClass(), DecodeDaddiGroupBranch(), DecodeDAHIDATI(), DecodeDAHIDATIMMR6(), DecodeDDDDRegisterClass(), DecodeDDDRegisterClass(), DecodeDDRegisterClass(), DecodeDEXT(), DecodeDFPRegsRegisterClass(), DecodeDINS(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeExpandedImmOperand(), DecodeFCCRegisterClass(), DecodeFCCRegsRegisterClass(), DecodeFGR32RegisterClass(), DecodeFGR64RegisterClass(), DecodeFGRCCRegisterClass(), DecodeFixedPointScaleImm32(), DecodeFixedPointScaleImm64(), DecodeFMem(), DecodeFMem2(), DecodeFMem3(), DecodeFMemCop2MMR6(), DecodeFMemCop2R6(), DecodeFMemMMR2(), DecodeFMOVLaneInstruction(), DecodeForVMRSandVMSR(), DecodeFPR128RegisterClass(), DecodeFPR16RegisterClass(), DecodeFPR32CRegisterClass(), DecodeFPR32RegisterClass(), DecodeFPR64CRegisterClass(), DecodeFPR64RegisterClass(), DecodeFPR8RegisterClass(), DecodeFPRegsRegisterClass(), decodeFRMArg(), DecodeFromCyclicRange(), DecodeGPR32RegisterClass(), DecodeGPR32spRegisterClass(), DecodeGPR64commonRegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), DecodeGPRCRegisterClass(), DecodeGPRMM16MovePRegisterClass(), DecodeGPRMM16RegisterClass(), DecodeGPRMM16ZeroRegisterClass(), DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodeGPRSeqPairsClassRegisterClass(), DecodeGPRspRegisterClass(), DecodeGPRwithAPSRRegisterClass(), DecodeGPRwithZRRegisterClass(), DecodeGR16RegisterClass(), DecodeGR8RegisterClass(), DecodeGRRegsRegisterClass(), DecodeGuestRegs64RegisterClass(), DecodeGuestRegsRegisterClass(), DecodeHI32DSPRegisterClass(), DecodeHINTInstruction(), DecodeHWRegsRegisterClass(), DecodeI64RegsRegisterClass(), DecodeImm8OptLsl(), DecodeInsSize(), DecodeInstSyncBarrierOption(), DecodeINSVE_DF(), DecodeIntPairRegisterClass(), DecodeIntRegsRegisterClass(), DecodeIT(), DecodeJMPL(), DecodeJumpTarget(), DecodeJumpTargetMM(), DecodeJumpTargetXMM(), DecodeL2RUSInstruction(), DecodeLdLImmInstruction(), DecodeLdRLImmInstruction(), DecodeLi16Imm(), DecodeLO32DSPRegisterClass(), DecodeLoadByte15(), DecodeLogicalImmInstruction(), DecodeLOLoop(), DecodeLongShiftOperand(), DecodeMem(), DecodeMemBarrierOption(), DecodeMemEVA(), DecodeMemExtend(), DecodeMemMMGPImm7Lsl2(), DecodeMemMMImm12(), DecodeMemMMImm16(), DecodeMemMMImm4(), DecodeMemMMImm9(), DecodeMemMMReglistImm4Lsl2(), DecodeMemMMSPImm5Lsl2(), DecodeMemMultipleWritebackInstruction(), DecodeMemOperand(), decodeMemoryOpValue(), decodeMemRIOperands(), decodeMemRIX16Operands(), decodeMemRIXOperands(), DecodeMEMrs9(), DecodeModImmInstruction(), DecodeModImmTiedInstruction(), DecodeModRegsRegisterClass(), DecodeMoveHRegInstruction(), DecodeMoveImmInstruction(), DecodeMovePRegPair(), DecodeMQPRRegisterClass(), DecodeMRSSystemRegister(), DecodeMSA128BRegisterClass(), DecodeMSA128DRegisterClass(), DecodeMSA128HRegisterClass(), DecodeMSA128Mem(), DecodeMSA128WRegisterClass(), DecodeMSACtrlRegisterClass(), DecodeMSRMask(), DecodeMSRSystemRegister(), DecodeMveAddrModeQ(), DecodeMVEModImmInstruction(), DecodeMVEOverlappingLongShift(), DecodeMVEPairVectorIndexOperand(), DecodeMVEVADCInstruction(), DecodeMVEVCMP(), DecodeMveVCTP(), DecodeMVEVPNOT(), DecodeNegImmOperand(), DecodeNEONComplexLane64Instruction(), DecodePairLdStInstruction(), decodePCDBLOperand(), DecodePCRel24BranchTarget(), DecodePCRelLabel19(), DecodePOOL16BEncodedField(), DecodePOP35GroupBranchMMR6(), DecodePOP37GroupBranchMMR6(), DecodePOP65GroupBranchMMR6(), DecodePOP75GroupBranchMMR6(), DecodePostIdxReg(), DecodePowerTwoOperand(), DecodePPRRegisterClass(), decodePredicateOperand(), DecodePredicateOperand(), DecodePredNoALOperand(), DecodePrefeOpMM(), DecodePRRegsRegisterClass(), DecodeQFPRegsRegisterClass(), DecodeQPRRegisterClass(), DecodeQQPRRegisterClass(), DecodeQQQQPRRegisterClass(), DecodeQQQQRegisterClass(), DecodeQQQRegisterClass(), DecodeQQRegisterClass(), decodeRegisterClass(), DecodeRegisterClass(), DecodeRegListOperand(), DecodeRegListOperand16(), DecodeRestrictedFPPredicateOperand(), DecodeRestrictedIPredicateOperand(), DecodeRestrictedSPredicateOperand(), DecodeRestrictedUPredicateOperand(), DecodeReturn(), DecodeRFEInstruction(), DecoderForMRRC2AndMCRR2(), decodeRiMemoryValue(), DecodeRRegsRegisterClass(), decodeRrMemoryValue(), DecodeRUSInstruction(), decodeRVCInstrRdRs1Rs2(), decodeRVCInstrRdRs1UImm(), DecodeSETPANInstruction(), decodeShiftImm(), DecodeShiftRight16Imm(), DecodeShiftRight32Imm(), DecodeShiftRight64Imm(), DecodeShiftRight8Imm(), DecodeSignedLdStInstruction(), DecodeSignedOperand(), DecodeSImm(), DecodeSIMM13(), DecodeSimm18Lsl3(), DecodeSimm19Lsl2(), DecodeSimm23Lsl2(), DecodeSimm9SP(), decodeSImmOperand(), decodeSImmOperandAndLsl1(), DecodeSImmWithOffsetAndScale(), DecodeSORegImmOperand(), DecodeSORegMemOperand(), DecodeSORegRegOperand(), decodeSPE2Operands(), decodeSPE4Operands(), decodeSPE8Operands(), DecodeSpecial3LlSc(), decodeSplsValue(), DecodeSPRRegisterClass(), DecodeStLImmInstruction(), DecodeSVEIncDecImm(), DecodeSVELogicalImmInstruction(), DecodeSWAP(), DecodeSymbolicOperandOff(), DecodeSyncI(), DecodeSyncI_MM(), DecodeSynciR6(), DecodeSystemPStateInstruction(), DecodeT2AddrModeImm0_1020s4(), DecodeT2AddrModeImm12(), DecodeT2AddrModeSOReg(), DecodeT2AddSubSPImm(), DecodeT2Adr(), DecodeT2BInstruction(), DecodeT2BROperand(), DecodeT2CPSInstruction(), DecodeT2Imm7(), DecodeT2Imm7S4(), DecodeT2Imm8(), DecodeT2Imm8S4(), DecodeT2LoadLabel(), DecodeT2MOVTWInstruction(), DecodeT2ShifterImmOperand(), DecodeT2SOImm(), DecodetcGPRRegisterClass(), DecodeTestAndBranch(), DecodetGPREvenRegisterClass(), DecodetGPROddRegisterClass(), DecodeThreeAddrSRegInstruction(), DecodeThumbAddrModeIS(), DecodeThumbAddrModePC(), DecodeThumbAddrModeSP(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPImm(), DecodeThumbAddSPReg(), DecodeThumbBCCTargetOperand(), DecodeThumbBLTargetOperand(), DecodeThumbBROperand(), DecodeThumbCmpBROperand(), DecodeThumbCPS(), DecodeTRAP(), decodeUImmOperand(), DecodeUImmWithOffsetAndScale(), DecodeUnconditionalBranch(), DecodeUnsignedLdStInstruction(), DecodeVCVTD(), DecodeVCVTImmOperand(), DecodeVCVTQ(), DecodeVecShiftLImm(), DecodeVecShiftRImm(), DecodeVectorRegisterClass(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVMOVModImmInstruction(), DecodeVPTMaskOperand(), DecodeVSCCLRM(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), DecodeVSTInstruction(), DecodeVSTRVLDR_SYSREG(), DecodeZPR2RegisterClass(), DecodeZPR3RegisterClass(), DecodeZPR4RegisterClass(), DecodeZPRRegisterClass(), llvm::HexagonMCInstrInfo::deriveDuplex(), llvm::HexagonMCInstrInfo::deriveExtender(), EmitBinary(), EmitCall(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::MipsTargetStreamer::emitII(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRRX(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), EmitSETHI(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), getCompoundInsn(), llvm::ARMInstrInfo::getNoop(), llvm::Thumb1InstrInfo::getNoop(), llvm::Thumb2InstrInfo::getNoop(), llvm::AArch64InstrInfo::getNoop(), getRealVLDOpcode(), getVariantKind(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), incrementLoc(), llvm::BTFDebug::InstLower(), isRegOrImmWithInputMods(), LLVMInitializeHexagonDisassembler(), llvm::XCoreMCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::ARCMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::AArch64MCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), lowerAlignmentHint(), llvm::LowerARMMachineInstrToMCInst(), llvm::AVRMCInstLower::lowerInstruction(), llvm::MipsMCInstLower::LowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerRISCVMachineInstrToMCInst(), llvm::LowerSparcMachineInstrToMCInst(), llvm::LowerVEMachineInstrToMCInst(), makeCombineInst(), needsExpandMemInst(), llvm::HexagonMCInstrInfo::padEndloop(), parseImmediate(), parseLEBImmediate(), PostOperandDecodeAdjust(), llvm::ARMInstPrinter::printInst(), readInstruction64(), RefineErrorLoc(), llvm::ARMAsmBackend::relaxInstruction(), llvm::RISCVAsmBackend::relaxInstruction(), llvm::MipsAsmPrinter::runOnMachineFunction(), ScaleVectorOffset(), SimplifyShortImmForm(), SimplifyShortMoveForm(), translateDstIndex(), translateFPRegister(), translateImmediate(), translateMaskRegister(), translateOperand(), translateRegister(), translateRMMemory(), translateSrcIndex(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), llvm::MCExternalSymbolizer::tryAddingSymbolicOperand(), llvm::AMDGPUSymbolizer::tryAddingSymbolicOperand(), and VisitGlobalVariableForEmission().
begin() [1/2]
iterator llvm::MCInst::begin () inline
Definition at line 193 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T >::begin().
Referenced by AddThumb1SBit(), adjustDuplex(), llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::AMDGPUDisassembler::convertMIMGInst(), decodeMemRIOperands(), decodeMemRIXOperands(), llvm::AMDGPUDisassembler::getInstruction(), getRealVLDOpcode(), HasConditionalBranch(), insertNamedMCOperand(), isRegOrImmWithInputMods(), isVectorPredicable(), LLVMInitializeHexagonDisassembler(), lookForCompound(), llvm::Hexagon::PacketIterator::operator++(), llvm::ARMInstPrinter::printRegisterList(), and llvm::HexagonMCInstrInfo::replaceDuplex().
begin() [2/2]
const_iterator llvm::MCInst::begin () const inline
Definition at line 194 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T >::begin().
clear()
void llvm::MCInst::clear () inline
Definition at line 189 of file MCInst.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::HexagonMCShuffler::copyTo(), covertDoubleImmToSingleImm(), DecodeL5RInstructionFail(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), makeCombineInst(), readInstruction64(), and translateInstruction().
dump()
LLVM_DUMP_METHOD void MCInst::dump () const
Definition at line 94 of file MCInst.cpp.
References llvm::dbgs(), and llvm::MCOperand::print().
Referenced by isPCRel32Branch(), and llvm::HexagonMCShuffler::reshuffleTo().
dump_pretty() [1/2]
void MCInst::dump_pretty (raw_ostream & OS, const MCInstPrinter * Printer = nullptr, StringRef Separator = " ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given.
Operators are separated by the Separator string.
Definition at line 72 of file MCInst.cpp.
References getOpcode(), and llvm::MCInstPrinter::getOpcodeName().
Referenced by llvm::RuntimeDyldCheckerExprEval::evaluate(), getFixupKindSize(), llvm::IsCPSRDead< MCInst >(), PrintCFIEscape(), and llvm::ARMAsmBackend::relaxInstruction().
dump_pretty() [2/2]
void MCInst::dump_pretty (raw_ostream & OS, StringRef Name, StringRef Separator = " ") const
Definition at line 78 of file MCInst.cpp.
References llvm::numbers::e, llvm::StringRef::empty(), and getOpcode().
end() [1/2]
iterator llvm::MCInst::end () inline
Definition at line 195 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T >::end().
Referenced by AddThumb1SBit(), llvm::HexagonMCInstrInfo::bundleInstructions(), DecodeRegListOperand(), HasConditionalBranch(), isVectorPredicable(), lookForCompound(), llvm::Hexagon::PacketIterator::operator++(), and llvm::ARMInstPrinter::printRegisterList().
end() [2/2]
const_iterator llvm::MCInst::end () const inline
Definition at line 196 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T >::end().
erase() [1/2]
void llvm::MCInst::erase (iterator I) inline
Definition at line 190 of file MCInst.h.
References llvm::SmallVectorImpl< T >::erase().
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), convertTailJumpOpcode(), llvm::AMDGPUDisassembler::getInstruction(), LLVMInitializeHexagonDisassembler(), lookForCompound(), removeRegisterOperands(), and llvm::HexagonMCInstrInfo::replaceDuplex().
erase() [2/2]
void llvm::MCInst::erase (iterator First, iterator Last) inline
Definition at line 191 of file MCInst.h.
References llvm::SmallVectorImpl< T >::erase().
getFlags()
unsigned llvm::MCInst::getFlags () const inline
Definition at line 175 of file MCInst.h.
Referenced by llvm::X86_MC::hasLockPrefix(), isPCRel32Branch(), and llvm::X86InstPrinterCommon::printInstFlags().
getLoc()
SMLoc llvm::MCInst::getLoc () const inline
Definition at line 178 of file MCInst.h.
Referenced by llvm::HexagonMCInstrInfo::addConstExtender(), covertDoubleImmToSingleImm(), llvm::createR600MCCodeEmitter(), llvm::createRISCVMCCodeEmitter(), llvm::MSP430MCCodeEmitter::encodeInstruction(), getBranchTargetOpValue(), getLit64Encoding(), HasConditionalBranch(), isNeitherAnorX(), isPCRel(), isPCRel32Branch(), needsPCRel(), llvm::HexagonMCChecker::reportBranchErrors(), llvm::HexagonMCChecker::reportError(), llvm::HexagonMCChecker::reportWarning(), llvm::HexagonShuffler::restrictNoSlot1Store(), and llvm::HexagonShuffler::restrictSlot1AOK().
getNumOperands()
unsigned llvm::MCInst::getNumOperands () const inline
Definition at line 182 of file MCInst.h.
References llvm::SmallVectorBase::size().
Referenced by addNegOperand(), checkLowRegisterList(), llvm::AMDGPUDisassembler::convertDPP8Inst(), convertTailJumpOpcode(), covertDoubleImmToSingleImm(), createLanaiElfRelocation(), createMCStreamer(), createMipsObjectTargetStreamer(), createWinCOFFStreamer(), DecodeT2Adr(), llvm::EmitAnyX86InstComments(), llvm::MipsELFStreamer::EmitInstruction(), llvm::MCStreamer::EmitInstruction(), llvm::HexagonMCELFStreamer::EmitSymbol(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::MCInstrAnalysis::evaluateBranch(), getARMLoadDeprecationInfo(), getARMStoreDeprecationInfo(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), getFixupKindSize(), llvm::AMDGPUDisassembler::getInstruction(), getItineraryLatency(), llvm::HexagonMCCodeEmitter::getMachineOpValue(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm12(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4sp(), getOpIdxForMO(), getRealVLDOpcode(), getRegisterForMxtrC0(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), llvm::MipsMCCodeEmitter::getRegisterListOpValue16(), getVariantKind(), HasConditionalBranch(), llvm::MCInstrDesc::hasDefOfPhysReg(), isMatchingOrAlias(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), isPCRel(), isPCRel32Branch(), isRegOrImmWithInputMods(), isValidDPP8(), listContainsReg(), LowerLargeShift(), llvm::MCInstPrinter::matchAliasPatterns(), needsExpandMemInst(), needsPCRel(), llvm::WebAssemblyInstPrinter::printBrList(), llvm::X86InstPrinterCommon::printCMPMnemonic(), printFMA3Comments(), llvm::ARMInstPrinter::printInst(), llvm::WebAssemblyInstPrinter::printInst(), llvm::MipsInstPrinter::printInst(), llvm::R600InstPrinter::printOperand(), llvm::ARMInstPrinter::printRegisterList(), llvm::AMDGPUInstPrinter::printRegOperand(), printSImmOperand(), llvm::SparcInstPrinter::printSparcAliasInstr(), llvm::X86ATTInstPrinter::printVecCompareInstr(), llvm::X86IntelInstPrinter::printVecCompareInstr(), llvm::X86InstPrinterCommon::printVPCMPMnemonic(), llvm::X86InstPrinterCommon::printVPCOMMnemonic(), removeRegisterOperands(), ScaleVectorOffset(), SimplifyShortImmForm(), SimplifyShortMoveForm(), llvm::AMDGPUDisassembler::tryDecodeInst(), and llvm::mca::verifyOperands().
getOpcode()
unsigned llvm::MCInst::getOpcode () const inline
Definition at line 172 of file MCInst.h.
Referenced by addImplySP(), addNegOperand(), addOptionalImmOperand(), AddThumb1SBit(), adjustDuplex(), allOpsDefaultValue(), llvm::HexagonShuffler::check(), checkDecodedInstruction(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::TargetSchedModel::computeInstrLatency(), llvm::MCSchedModel::computeInstrLatency(), llvm::TargetSchedModel::computeReciprocalThroughput(), llvm::AMDGPUDisassembler::convertDPP8Inst(), llvm::AMDGPUDisassembler::convertMIMGInst(), llvm::AMDGPUDisassembler::convertSDWAInst(), convertTailJumpOpcode(), covertDoubleImmToSingleImm(), createARMMCRelocationInfo(), llvm::createBPFbeMCCodeEmitter(), createLanaiElfRelocation(), createMCStreamer(), createMipsObjectTargetStreamer(), llvm::createR600MCCodeEmitter(), llvm::createRISCVMCCodeEmitter(), createWinCOFFStreamer(), decIncOperator(), DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddSubERegInstruction(), DecodeArmMOVTWInstruction(), DecodeCopMemInstruction(), DecodeDEXT(), DecodeDINS(), DecodeExclusiveLdStInstruction(), DecodeForVMRSandVMSR(), DecodeLogicalImmInstruction(), DecodeLOLoop(), DecodeMem(), DecodeMemEVA(), DecodeMemMMImm12(), DecodeMemMMImm4(), DecodeMemMMImm9(), DecodeMemMMReglistImm4Lsl2(), DecodeMemMultipleWritebackInstruction(), decodeMemRIOperands(), decodeMemRIXOperands(), DecodeModImmInstruction(), DecodeMoveImmInstruction(), DecodeMSA128Mem(), DecodeMSRMask(), DecodeMVEModImmInstruction(), DecodeMVEOverlappingLongShift(), DecodePairLdStInstruction(), DecodePCRelLabel19(), DecodePredicateOperand(), DecodeRegListOperand(), DecodeRegListOperand16(), DecoderForMRRC2AndMCRR2(), DecodeSignedLdStInstruction(), DecodeSpecial3LlSc(), DecodeSVELogicalImmInstruction(), DecodeT2AddrModeImm12(), DecodeT2AddrModeImm8(), DecodeT2AddrModeSOReg(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeTBLInstruction(), DecodeThreeAddrSRegInstruction(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPReg(), DecodeUnsignedLdStInstruction(), DecodeVCVTImmOperand(), DecodeVLD1DupInstruction(), DecodeVLD2DupInstruction(), DecodeVLDInstruction(), DecodeVMOVModImmInstruction(), DecodeVSCCLRM(), DecodeVSTInstruction(), DecodeVSTRVLDR_SYSREG(), llvm::HexagonMCInstrInfo::deriveSubInst(), llvm::EmitAnyX86InstComments(), llvm::AsmPrinter::EmitFunctionBody(), llvm::HexagonMCELFStreamer::EmitInstruction(), encodeBitmaskPerm(), llvm::MipsMCCodeEmitter::encodeInstruction(), llvm::MSP430MCCodeEmitter::encodeInstruction(), llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::X86_MC::X86MCInstrAnalysis::evaluateMemoryOperandAddress(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), getCompoundCandidateGroup(), getCompoundInsn(), getCompoundOp(), getCondFromBranch(), llvm::HexagonMCInstrInfo::getDesc(), llvm::HexagonMCInstrInfo::getDuplexCandidateGroup(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), getFixupKindSize(), llvm::AMDGPUDisassembler::getInstruction(), llvm::PPCMCCodeEmitter::getInstSizeInBytes(), getItineraryLatency(), getLatency(), getLit64Encoding(), llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm12(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4sp(), llvm::HexagonMCInstrInfo::getName(), getPrefixes(), llvm::AVRInstPrinter::getPrettyRegisterName(), getRealVLDOpcode(), llvm::MCSchedModel::getReciprocalThroughput(), getRegisterForMxtrC0(), getRegisterForMxtrDSP(), getRegNum(), getRelaxedOpcode(), getRelaxedOpcodeArith(), getRelaxedOpcodeBranch(), llvm::HexagonMCInstrInfo::getType(), HasConditionalBranch(), hasShortDelaySlot(), hasVariantSymbol(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), insertNamedMCOperand(), instIsBreakpoint(), llvm::MCInstrAnalysis::isBranch(), llvm::HexagonMCInstrInfo::isBundle(), llvm::MCInstrAnalysis::isCall(), llvm::MCInstrAnalysis::isConditionalBranch(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::IsCPSRDead< MCInst >(), isFirstMacroFusibleInst(), llvm::HexagonMCInstrInfo::isImmext(), llvm::MCInstrAnalysis::isIndirectBranch(), isMatchingOrAlias(), IsMovrelsSDWAOpcode(), isNeitherAnorX(), isOrderedCompoundPair(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), isPCRel32Branch(), isRegOrImmWithInputMods(), llvm::MCInstrAnalysis::isReturn(), IsRevOpcode(), isRIPRelative(), llvm::HexagonMCInstrInfo::isSolo(), llvm::HexagonMCInstrInfo::isSubInstruction(), llvm::MCInstrAnalysis::isTerminator(), llvm::MCInstrAnalysis::isUnconditionalBranch(), isValidDPP8(), isVectorPredicable(), LLVMInitializeHexagonDisassembler(), lookForCompound(), llvm::AArch64MCInstLower::Lower(), LowerLargeShift(), makeCombineInst(), llvm::MCInstPrinter::matchAliasPatterns(), matchRegisterNameHelper(), llvm::ARMAsmBackend::mayNeedRelaxation(), llvm::RISCVAsmBackend::mayNeedRelaxation(), needsExpandMemInst(), needsPCRel(), PostOperandDecodeAdjust(), llvm::AArch64InstPrinter::printBarrierOption(), llvm::SparcInstPrinter::printCCOperand(), llvm::X86InstPrinterCommon::printCMPMnemonic(), printFMA3Comments(), llvm::X86ATTInstPrinter::printInst(), llvm::X86IntelInstPrinter::printInst(), llvm::AArch64InstPrinter::printInst(), llvm::ARMInstPrinter::printInst(), llvm::AMDGPUInstPrinter::printInst(), llvm::AVRInstPrinter::printInst(), llvm::PPCInstPrinter::printInst(), llvm::WebAssemblyInstPrinter::printInst(), llvm::MipsInstPrinter::printInst(), llvm::AArch64AppleInstPrinter::printInst(), llvm::X86InstPrinterCommon::printInstFlags(), printMasking(), llvm::ARMInstPrinter::printModImmOperand(), llvm::ARMInstPrinter::printMSRMaskOperand(), llvm::VEInstPrinter::printOperand(), llvm::SparcInstPrinter::printOperand(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::PPCInstPrinter::printOperand(), llvm::ARMInstPrinter::printRegisterList(), llvm::AMDGPUInstPrinter::printRegOperand(), llvm::SparcInstPrinter::printSparcAliasInstr(), llvm::AArch64InstPrinter::printSysAlias(), llvm::X86ATTInstPrinter::printVecCompareInstr(), llvm::X86IntelInstPrinter::printVecCompareInstr(), llvm::X86InstPrinterCommon::printVPCMPMnemonic(), llvm::X86InstPrinterCommon::printVPCOMMnemonic(), llvm::WebAssemblyInstPrinter::printWebAssemblyP2AlignOperand(), readInstruction64(), RefineErrorLoc(), llvm::ARMAsmBackend::relaxInstruction(), llvm::RISCVAsmBackend::relaxInstruction(), removeRegisterOperands(), ScaleVectorOffset(), SimplifyMOVSX(), llvm::HexagonMCInstrInfo::subInstWouldBeExtended(), SwapBits(), translateInstruction(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), llvm::AMDGPUDisassembler::tryDecodeInst(), and llvm::mca::verifyOperands().
getOperand() [1/2]
const MCOperand& llvm::MCInst::getOperand (unsigned i) const inline
Definition at line 180 of file MCInst.h.
Referenced by llvm::HexagonMCInstrInfo::addConstExtender(), addNegOperand(), addOps(), addOptionalImmOperand(), adjustDuplex(), llvm::adjustPqBits(), allOpsDefaultValue(), llvm::HexagonShuffler::check(), checkLowRegisterList(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::AMDGPUDisassembler::convertMIMGInst(), convertTailJumpOpcode(), covertDoubleImmToSingleImm(), createARMMCRelocationInfo(), createBPFMCInstPrinter(), llvm::mca::InstrBuilder::createInstruction(), createLanaiElfRelocation(), createMCStreamer(), createMipsObjectTargetStreamer(), llvm::createR600MCCodeEmitter(), llvm::createRISCVMCCodeEmitter(), createWinCOFFStreamer(), decIncOperator(), DecodeBFAfterTargetOperand(), DecodeInsSize(), DecodeMoveImmInstruction(), DecodeRegListOperand(), decodeRVCInstrRdRs1Rs2(), decodeRVCInstrRdRs1UImm(), llvm::HexagonMCInstrInfo::deriveSubInst(), llvm::EmitAnyX86InstComments(), llvm::MipsELFStreamer::EmitInstruction(), llvm::MCStreamer::EmitInstruction(), llvm::HexagonMCELFStreamer::EmitSymbol(), llvm::MSP430MCCodeEmitter::encodeInstruction(), llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), encodeThumbBLOffset(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::X86_MC::X86MCInstrAnalysis::evaluateMemoryOperandAddress(), llvm::HexagonMCInstrInfo::extenderForIndex(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), llvm::PPCMCCodeEmitter::getAbsCondBrEncoding(), llvm::PPCMCCodeEmitter::getAbsDirectBrEncoding(), getARMLoadDeprecationInfo(), getARMStoreDeprecationInfo(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget7OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue(), getBranchTargetOpValue(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue1SImm16(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueLsl2MMR6(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMM(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMPC10(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMR6(), getCompoundCandidateGroup(), getCompoundInsn(), getCompoundOp(), llvm::PPCMCCodeEmitter::getCondBrEncoding(), getCondFromBranch(), llvm::PPCMCCodeEmitter::getDirectBrEncoding(), llvm::HexagonMCInstrInfo::getDuplexCandidateGroup(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), llvm::HexagonMCInstrInfo::getExtendableOperand(), getFixupKindSize(), llvm::PPCMCCodeEmitter::getImm16Encoding(), llvm::AMDGPUDisassembler::getInstruction(), getITDeprecationInfo(), llvm::MipsMCCodeEmitter::getJumpOffset16OpValue(), llvm::MipsMCCodeEmitter::getJumpTargetOpValue(), llvm::MipsMCCodeEmitter::getJumpTargetOpValueMM(), getLit64Encoding(), llvm::HexagonMCCodeEmitter::getMachineOpValue(), getMCRDeprecationInfo(), llvm::MipsMCCodeEmitter::getMemEncoding(), llvm::MipsMCCodeEmitter::getMemEncodingMMGPImm7Lsl2(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm11(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm12(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm16(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4Lsl1(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4Lsl2(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4sp(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm9(), llvm::MipsMCCodeEmitter::getMemEncodingMMSPImm5Lsl2(), llvm::PPCMCCodeEmitter::getMemRIEncoding(), llvm::PPCMCCodeEmitter::getMemRIX16Encoding(), llvm::PPCMCCodeEmitter::getMemRIXEncoding(), llvm::MipsMCCodeEmitter::getMovePRegPairOpValue(), llvm::MipsMCCodeEmitter::getMovePRegSingleOpValue(), llvm::HexagonMCInstrInfo::getNewValueOperand(), llvm::HexagonMCInstrInfo::getNewValueOperand2(), getOpIdxForMO(), llvm::AVRInstPrinter::getPrettyRegisterName(), getRealVLDOpcode(), getRegisterForMxtrC0(), getRegisterForMxtrDSP(), getRegisterForMxtrFP(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), getRegNum(), getRegOperandNumElts(), llvm::MipsMCCodeEmitter::getSimm18Lsl3Encoding(), llvm::MipsMCCodeEmitter::getSimm19Lsl2Encoding(), llvm::MipsMCCodeEmitter::getSimm23Lsl2Encoding(), llvm::MipsMCCodeEmitter::getSImm3Lsa2Value(), llvm::MipsMCCodeEmitter::getSImm9AddiuspValue(), llvm::MipsMCCodeEmitter::getSizeInsEncoding(), llvm::PPCMCCodeEmitter::getSPE2DisEncoding(), llvm::PPCMCCodeEmitter::getSPE4DisEncoding(), llvm::PPCMCCodeEmitter::getSPE8DisEncoding(), llvm::PPCMCCodeEmitter::getTLSCallEncoding(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), llvm::MipsMCCodeEmitter::getUImm3Mod8Encoding(), llvm::MipsMCCodeEmitter::getUImm4AndValue(), llvm::MipsMCCodeEmitter::getUImm5Lsl2Encoding(), llvm::MipsMCCodeEmitter::getUImm6Lsl2Encoding(), llvm::MipsMCCodeEmitter::getUImmWithOffsetEncoding(), HasConditionalBranch(), llvm::MCInstrDesc::hasDefOfPhysReg(), hasShortDelaySlot(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), instIsBreakpoint(), llvm::HexagonMCInstrInfo::instruction(), is16BitMemOperand(), is32BitMemOperand(), is64BitMemOperand(), llvm::HexagonMCInstrInfo::isBundle(), llvm::IsCPSRDead< MCInst >(), llvm::HexagonMCInstrInfo::isInnerLoop(), isMatchingOrAlias(), llvm::HexagonMCInstrInfo::isMemReorderDisabled(), IsMovrelsSDWAOpcode(), isNeitherAnorX(), isOrderedCompoundPair(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), llvm::HexagonMCInstrInfo::isOuterLoop(), isPCRel(), isPCRel32Branch(), isPostIncrementForm(), isPreIncrementForm(), isReg(), isRegOrImmWithInputMods(), IsRevOpcode(), isRIPRelative(), isShiftedUIntAtAnyPosition(), isValidDPP8(), isVectorPredicable(), listContainsReg(), LLVMInitializeHexagonDisassembler(), LowerLargeShift(), makeCombineInst(), matchAliasCondition(), matchRegisterNameHelper(), llvm::HexagonMCInstrInfo::minConstant(), needsExpandMemInst(), needsPCRel(), PostOperandDecodeAdjust(), llvm::HexagonMCInstrInfo::predicateInfo(), llvm::PPCInstPrinter::printAbsBranchOperand(), llvm::ARMInstPrinter::printAddrMode2OffsetOperand(), llvm::ARMInstPrinter::printAddrMode2Operand(), llvm::ARMInstPrinter::printAddrMode3OffsetOperand(), llvm::ARMInstPrinter::printAddrMode3Operand(), llvm::ARMInstPrinter::printAddrMode5FP16Operand(), llvm::ARMInstPrinter::printAddrMode5Operand(), llvm::ARMInstPrinter::printAddrMode6OffsetOperand(), llvm::ARMInstPrinter::printAddrMode6Operand(), llvm::ARMInstPrinter::printAddrMode7Operand(), llvm::ARMInstPrinter::printAddrModeImm12Operand(), llvm::ARMInstPrinter::printAddrModeTBB(), llvm::ARMInstPrinter::printAddrModeTBH(), llvm::AArch64InstPrinter::printAddSubImm(), llvm::ARMInstPrinter::printAdrLabelOperand(), llvm::AArch64InstPrinter::printAdrpLabel(), llvm::AArch64InstPrinter::printAlignedLabel(), llvm::ARMInstPrinter::printAM2PreOrOffsetIndexOp(), llvm::ARMInstPrinter::printAM3PreOrOffsetIndexOp(), llvm::AArch64InstPrinter::printAMIndexedWB(), llvm::AArch64InstPrinter::printAMNoIndex(), llvm::AArch64InstPrinter::printArithExtend(), llvm::PPCInstPrinter::printATBitsAsHint(), llvm::RISCVInstPrinter::printAtomicMemOp(), llvm::ARMInstPrinter::printBankedRegOperand(), llvm::R600InstPrinter::printBankSwizzle(), llvm::AArch64InstPrinter::printBarrierOption(), llvm::ARMInstPrinter::printBitfieldInvMaskImmOperand(), llvm::PPCInstPrinter::printBranchOperand(), llvm::WebAssemblyInstPrinter::printBrList(), llvm::HexagonInstPrinter::printBrtarget(), llvm::BPFInstPrinter::printBrTargetOperand(), llvm::AArch64InstPrinter::printBTIHintOp(), llvm::LanaiInstPrinter::printCCOperand(), llvm::VEInstPrinter::printCCOperand(), llvm::SparcInstPrinter::printCCOperand(), llvm::ARMInstPrinter::printCImmediate(), llvm::AMDGPUInstPrinter::printClampSI(), llvm::NVPTXInstPrinter::printCmpMode(), llvm::AArch64InstPrinter::printComplexRotationOp(), llvm::ARMInstPrinter::printComplexRotationOp(), llvm::X86InstPrinterCommon::printCondCode(), llvm::AArch64InstPrinter::printCondCode(), llvm::ARMInstPrinter::printCoprocOptionImm(), llvm::ARMInstPrinter::printCPSIFlag(), llvm::ARMInstPrinter::printCPSIMod(), llvm::PPCInstPrinter::printcrbitm(), llvm::RISCVInstPrinter::printCSRSystemRegister(), llvm::R600InstPrinter::printCT(), llvm::NVPTXInstPrinter::printCvtMode(), llvm::AMDGPUInstPrinter::printEndpgm(), llvm::AArch64InstPrinter::printExactFPImm(), llvm::ARMInstPrinter::printExpandedImmOperand(), printExpr(), llvm::AArch64InstPrinter::printExtendedRegister(), llvm::ARMInstPrinter::printFBits16(), llvm::ARMInstPrinter::printFBits32(), llvm::RISCVInstPrinter::printFenceArg(), printFMA3Comments(), llvm::AArch64InstPrinter::printFPImmOperand(), llvm::ARMInstPrinter::printFPImmOperand(), llvm::RISCVInstPrinter::printFRMArg(), llvm::AArch64InstPrinter::printGPR64as32(), llvm::ARMInstPrinter::printGPRPairOperand(), llvm::AArch64InstPrinter::printGPRSeqPairsClassOperand(), llvm::LanaiInstPrinter::printHi16AndImmOperand(), llvm::LanaiInstPrinter::printHi16ImmOperand(), llvm::AMDGPUInstPrinter::printHigh(), llvm::AMDGPUInstPrinter::printHwreg(), llvm::AMDGPUInstPrinter::printIfSet(), llvm::AArch64InstPrinter::printImm(), llvm::BPFInstPrinter::printImm64Operand(), llvm::AArch64InstPrinter::printImm8OptLsl(), llvm::AArch64InstPrinter::printImmHex(), llvm::ARMInstPrinter::printImmPlusOneOperand(), llvm::AArch64InstPrinter::printImmScale(), llvm::MSP430InstPrinter::printInst(), llvm::AArch64InstPrinter::printInst(), llvm::ARMInstPrinter::printInst(), llvm::AMDGPUInstPrinter::printInst(), llvm::HexagonInstPrinter::printInst(), llvm::PPCInstPrinter::printInst(), llvm::WebAssemblyInstPrinter::printInst(), llvm::MipsInstPrinter::printInst(), llvm::AArch64AppleInstPrinter::printInst(), llvm::ARMInstPrinter::printInstSyncBOption(), llvm::AArch64InstPrinter::printInverseCondCode(), llvm::R600InstPrinter::printKCache(), llvm::NVPTXInstPrinter::printLdStCode(), llvm::ARMInstPrinter::printLdStmModeOperand(), llvm::R600InstPrinter::printLiteral(), llvm::LanaiInstPrinter::printLo16AndImmOperand(), llvm::AArch64InstPrinter::printLogicalImm(), llvm::ARMInstPrinter::printMandatoryInvertedPredicateOperand(), llvm::ARMInstPrinter::printMandatoryPredicateOperand(), llvm::ARMInstPrinter::printMandatoryRestrictedPredicateOperand(), printMasking(), llvm::VEInstPrinter::printMemASOperand(), llvm::VEInstPrinter::printMemASXOperand(), llvm::SparcInstPrinter::printMembarTag(), llvm::ARMInstPrinter::printMemBOption(), llvm::AArch64InstPrinter::printMemExtend(), llvm::LanaiInstPrinter::printMemImmOperand(), llvm::X86ATTInstPrinter::printMemOffset(), llvm::X86IntelInstPrinter::printMemOffset(), llvm::BPFInstPrinter::printMemOperand(), llvm::NVPTXInstPrinter::printMemOperand(), llvm::SparcInstPrinter::printMemOperand(), llvm::X86ATTInstPrinter::printMemReference(), llvm::X86IntelInstPrinter::printMemReference(), llvm::PPCInstPrinter::printMemRegImm(), llvm::PPCInstPrinter::printMemRegReg(), llvm::LanaiInstPrinter::printMemRiOperand(), llvm::LanaiInstPrinter::printMemRrOperand(), llvm::LanaiInstPrinter::printMemSplsOperand(), llvm::NVPTXInstPrinter::printMmaCode(), llvm::ARMInstPrinter::printModImmOperand(), llvm::AArch64InstPrinter::printMRSSystemRegister(), llvm::ARMInstPrinter::printMSRMaskOperand(), llvm::AArch64InstPrinter::printMSRSystemRegister(), llvm::ARMInstPrinter::printMveAddrModeQOperand(), llvm::ARMInstPrinter::printMveAddrModeRQOperand(), llvm::ARMInstPrinter::printMveSaturateOp(), llvm::ARMInstPrinter::printMVEVectorList(), llvm::ARMInstPrinter::printNoHashImmediate(), llvm::R600InstPrinter::printOMOD(), llvm::AMDGPUInstPrinter::printOModSI(), llvm::BPFInstPrinter::printOperand(), llvm::LanaiInstPrinter::printOperand(), llvm::RISCVInstPrinter::printOperand(), llvm::NVPTXInstPrinter::printOperand(), llvm::VEInstPrinter::printOperand(), llvm::HexagonInstPrinter::printOperand(), llvm::X86ATTInstPrinter::printOperand(), llvm::X86IntelInstPrinter::printOperand(), llvm::SparcInstPrinter::printOperand(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::ARMInstPrinter::printOperand(), llvm::PPCInstPrinter::printOperand(), llvm::AArch64InstPrinter::printOperand(), llvm::R600InstPrinter::printOperand(), llvm::X86InstPrinterCommon::printOptionalSegReg(), llvm::X86InstPrinterCommon::printPCRelImm(), llvm::ARMInstPrinter::printPImmediate(), llvm::ARMInstPrinter::printPKHASRShiftImm(), llvm::ARMInstPrinter::printPKHLSLShiftImm(), llvm::ARMInstPrinter::printPostIdxImm8Operand(), llvm::ARMInstPrinter::printPostIdxImm8s4Operand(), llvm::ARMInstPrinter::printPostIdxRegOperand(), llvm::AArch64InstPrinter::printPostIncOperand(), llvm::LanaiInstPrinter::printPredicateOperand(), llvm::PPCInstPrinter::printPredicateOperand(), llvm::ARMInstPrinter::printPredicateOperand(), llvm::AArch64InstPrinter::printPrefetchOp(), llvm::NVPTXInstPrinter::printProtoIdent(), llvm::AArch64InstPrinter::printPSBHintOp(), llvm::ARMInstPrinter::printRegisterList(), llvm::AMDGPUInstPrinter::printRegOperand(), llvm::ARMInstPrinter::printRotImmOperand(), llvm::X86InstPrinterCommon::printRoundingControl(), llvm::R600InstPrinter::printRSel(), llvm::PPCInstPrinter::printS16ImmOperand(), llvm::PPCInstPrinter::printS5ImmOperand(), llvm::ARMInstPrinter::printSBitModifierOperand(), llvm::AMDGPUInstPrinter::printSendMsg(), llvm::ARMInstPrinter::printSetendOperand(), llvm::AArch64InstPrinter::printShiftedRegister(), llvm::AArch64InstPrinter::printShifter(), llvm::ARMInstPrinter::printShiftImmOperand(), llvm::AArch64InstPrinter::printSIMDType10Operand(), printSImmOperand(), llvm::ARMInstPrinter::printSORegImmOperand(), llvm::ARMInstPrinter::printSORegRegOperand(), llvm::SparcInstPrinter::printSparcAliasInstr(), llvm::X86InstPrinterCommon::printSSEAVXCC(), llvm::X86ATTInstPrinter::printSTiRegOperand(), llvm::X86IntelInstPrinter::printSTiRegOperand(), llvm::AArch64InstPrinter::printSVELogicalImm(), llvm::AArch64InstPrinter::printSVEPattern(), llvm::AArch64InstPrinter::printSVERegOp(), llvm::AMDGPUInstPrinter::printSwizzle(), llvm::AArch64InstPrinter::printSysAlias(), llvm::AArch64InstPrinter::printSysCROperand(), llvm::AArch64InstPrinter::printSystemPStateField(), llvm::ARMInstPrinter::printT2AddrModeImm0_1020s4Operand(), llvm::ARMInstPrinter::printT2AddrModeImm8OffsetOperand(), llvm::ARMInstPrinter::printT2AddrModeImm8Operand(), llvm::ARMInstPrinter::printT2AddrModeImm8s4OffsetOperand(), llvm::ARMInstPrinter::printT2AddrModeImm8s4Operand(), llvm::ARMInstPrinter::printT2AddrModeSoRegOperand(), llvm::ARMInstPrinter::printT2SOOperand(), llvm::ARMInstPrinter::printThumbAddrModeImm5SOperand(), llvm::ARMInstPrinter::printThumbAddrModeRROperand(), llvm::ARMInstPrinter::printThumbITMask(), llvm::ARMInstPrinter::printThumbLdrLabelOperand(), llvm::ARMInstPrinter::printThumbS4ImmOperand(), llvm::ARMInstPrinter::printThumbSRImm(), llvm::PPCInstPrinter::printTLSCall(), llvm::ARMInstPrinter::printTraceSyncBOption(), llvm::PPCInstPrinter::printU10ImmOperand(), llvm::PPCInstPrinter::printU12ImmOperand(), llvm::PPCInstPrinter::printU16ImmOperand(), llvm::PPCInstPrinter::printU1ImmOperand(), llvm::PPCInstPrinter::printU2ImmOperand(), llvm::PPCInstPrinter::printU3ImmOperand(), llvm::PPCInstPrinter::printU4ImmOperand(), llvm::PPCInstPrinter::printU5ImmOperand(), llvm::PPCInstPrinter::printU6ImmOperand(), llvm::PPCInstPrinter::printU7ImmOperand(), llvm::X86ATTInstPrinter::printU8Imm(), llvm::X86IntelInstPrinter::printU8Imm(), llvm::PPCInstPrinter::printU8ImmOperand(), llvm::AArch64InstPrinter::printUImm12Offset(), printUImmOperand(), llvm::X86ATTInstPrinter::printVecCompareInstr(), llvm::X86IntelInstPrinter::printVecCompareInstr(), llvm::AArch64InstPrinter::printVectorIndex(), llvm::ARMInstPrinter::printVectorIndex(), llvm::AArch64InstPrinter::printVectorList(), llvm::ARMInstPrinter::printVectorListFour(), llvm::ARMInstPrinter::printVectorListFourAllLanes(), llvm::ARMInstPrinter::printVectorListFourSpaced(), llvm::ARMInstPrinter::printVectorListFourSpacedAllLanes(), llvm::ARMInstPrinter::printVectorListOne(), llvm::ARMInstPrinter::printVectorListOneAllLanes(), llvm::ARMInstPrinter::printVectorListThree(), llvm::ARMInstPrinter::printVectorListThreeAllLanes(), llvm::ARMInstPrinter::printVectorListThreeSpaced(), llvm::ARMInstPrinter::printVectorListThreeSpacedAllLanes(), llvm::ARMInstPrinter::printVectorListTwo(), llvm::ARMInstPrinter::printVectorListTwoAllLanes(), llvm::ARMInstPrinter::printVectorListTwoSpaced(), llvm::ARMInstPrinter::printVectorListTwoSpacedAllLanes(), llvm::X86InstPrinterCommon::printVKPair(), llvm::ARMInstPrinter::printVMOVModImmOperand(), llvm::X86InstPrinterCommon::printVPCOMMnemonic(), llvm::ARMInstPrinter::printVPTMask(), llvm::ARMInstPrinter::printVPTPredicateOperand(), llvm::AArch64InstPrinter::printVRegOperand(), llvm::AMDGPUInstPrinter::printWaitFlag(), llvm::WebAssemblyInstPrinter::printWebAssemblyP2AlignOperand(), llvm::WebAssemblyInstPrinter::printWebAssemblySignatureOperand(), llvm::R600InstPrinter::printWrite(), llvm::AArch64InstPrinter::printZPRasFPR(), readInstruction64(), llvm::RISCVAsmBackend::relaxInstruction(), removeRegisterOperands(), llvm::HexagonMCInstrInfo::replaceDuplex(), llvm::HexagonMCChecker::reportBranchErrors(), ScaleVectorOffset(), llvm::HexagonMCInstrInfo::setInnerLoop(), llvm::HexagonMCInstrInfo::setMemReorderDisabled(), llvm::HexagonMCInstrInfo::setOuterLoop(), SimplifyMOVSX(), SimplifyShortImmForm(), SimplifyShortMoveForm(), llvm::HexagonMCInstrInfo::subInstWouldBeExtended(), SwapBits(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), usesGivenOffset(), and llvm::mca::verifyOperands().
getOperand() [2/2]
MCOperand& llvm::MCInst::getOperand (unsigned i) inline
Definition at line 181 of file MCInst.h.
insert()
iterator llvm::MCInst::insert (iterator I, const MCOperand & Op) inline
Definition at line 198 of file MCInst.h.
References llvm::MCOperand::dump(), llvm::SmallVectorImpl< T >::insert(), Name, llvm::MCOperand::print(), and Printer.
Referenced by AddThumb1SBit(), adjustDuplex(), decodeMemRIOperands(), decodeMemRIXOperands(), llvm::AMDGPUDisassembler::getInstruction(), getRealVLDOpcode(), insertNamedMCOperand(), isRegOrImmWithInputMods(), and isVectorPredicable().
print()
void MCInst::print (raw_ostream & OS) const
Definition at line 63 of file MCInst.cpp.
References llvm::numbers::e, and getOpcode().
Referenced by llvm::operator<<().
setFlags()
void llvm::MCInst::setFlags (unsigned F) inline
Definition at line 174 of file MCInst.h.
References F().
Referenced by getPrefixes().
setLoc()
void llvm::MCInst::setLoc (SMLoc loc) inline
Definition at line 177 of file MCInst.h.
Referenced by llvm::HexagonMCInstrInfo::addConstExtender(), addNegOperand(), llvm::HexagonMCShuffler::copyTo(), llvm::MipsTargetStreamer::emitII(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRRX(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), getPrefixes(), llvm::IsCPSRDead< MCInst >(), IsRevOpcode(), matchRegisterNameHelper(), needsExpandMemInst(), and printMCExpr().
setOpcode()
void llvm::MCInst::setOpcode (unsigned Op) inline
Definition at line 171 of file MCInst.h.
Referenced by addNegOperand(), adjustDuplex(), NoAutoPaddingScope::changeAndComment(), llvm::AMDGPUDisassembler::convertMIMGInst(), convertTailJumpOpcode(), covertDoubleImmToSingleImm(), Decode2OpInstructionFail(), DecodeAddiGroupBranch(), DecodeBgtzGroupBranch(), DecodeBgtzGroupBranchMMR6(), DecodeBgtzlGroupBranch(), DecodeBlezGroupBranch(), DecodeBlezGroupBranchMMR6(), DecodeBlezlGroupBranch(), DecodeBranchImmInstruction(), DecodeCPSInstruction(), DecodeDaddiGroupBranch(), DecodeDEXT(), DecodeDINS(), DecodeL2OpInstructionFail(), DecodeL5RInstructionFail(), DecodeLOLoop(), DecodeMemMultipleWritebackInstruction(), DecodeMVEOverlappingLongShift(), DecodePOP35GroupBranchMMR6(), DecodePOP37GroupBranchMMR6(), DecodePOP65GroupBranchMMR6(), DecodePOP75GroupBranchMMR6(), DecodeSETPANInstruction(), DecodeT2AddSubSPImm(), DecodeT2Adr(), DecodeT2CPSInstruction(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeThumb2BCCInstruction(), DecodeVCVTD(), DecodeVCVTQ(), llvm::HexagonMCInstrInfo::deriveDuplex(), llvm::HexagonMCInstrInfo::deriveExtender(), llvm::HexagonMCInstrInfo::deriveSubInst(), EmitBinary(), EmitCall(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::MipsTargetStreamer::emitII(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRRX(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), EmitSETHI(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), encodeBitmaskPerm(), llvm::MipsMCCodeEmitter::encodeInstruction(), getCompoundInsn(), getFixupKindSize(), llvm::Thumb1InstrInfo::getNoop(), llvm::ARMInstrInfo::getNoop(), llvm::Thumb2InstrInfo::getNoop(), llvm::AArch64InstrInfo::getNoop(), llvm::PPCInstrInfo::getNoop(), llvm::X86InstrInfo::getNoop(), getRealVLDOpcode(), getVariantKind(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), incrementLoc(), llvm::BTFDebug::InstLower(), LLVMInitializeHexagonDisassembler(), llvm::XCoreMCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::MSP430MCInstLower::Lower(), llvm::ARCMCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::AArch64MCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), lowerAlignmentHint(), llvm::LowerARMMachineInstrToMCInst(), llvm::AVRMCInstLower::lowerInstruction(), LowerLargeShift(), llvm::MipsMCInstLower::LowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerRISCVMachineInstrToMCInst(), llvm::LowerSparcMachineInstrToMCInst(), llvm::LowerVEMachineInstrToMCInst(), makeCombineInst(), llvm::MCInstBuilder::MCInstBuilder(), needsExpandMemInst(), llvm::HexagonMCInstrInfo::padEndloop(), parseImmediate(), llvm::ARMInstPrinter::printInst(), llvm::ARMAsmBackend::relaxInstruction(), llvm::RISCVAsmBackend::relaxInstruction(), removeRegisterOperands(), llvm::MipsAsmPrinter::runOnMachineFunction(), ScaleVectorOffset(), SimplifyMOVSX(), SimplifyShortImmForm(), SimplifyShortMoveForm(), translateInstruction(), and VisitGlobalVariableForEmission().
size()
size_t llvm::MCInst::size () const inline
Definition at line 192 of file MCInst.h.
References llvm::SmallVectorBase::size().
Referenced by addOptionalImmOperand(), llvm::HexagonMCInstrInfo::bundleSize(), llvm::HexagonMCInstrInfo::isBundle(), llvm::HexagonMCInstrInfo::minConstant(), llvm::HexagonMCInstrInfo::replaceDuplex(), and llvm::HexagonMCInstrInfo::tryCompound().
The documentation for this class was generated from the following files:
include/llvm/MC/MCInst.h
lib/MC/MCInst.cpp