LLVM: llvm::IntervalMapImpl::Path Class Reference
llvm::IntervalMapImpl::Path Class Reference
#include "llvm/ADT/IntervalMap.h"
Public Member Functions
template<typename NodeT >
NodeT & node (unsigned Level) const
unsigned size (unsigned Level) const
unsigned offset (unsigned Level) const
unsigned & offset (unsigned Level)
template<typename NodeT >
NodeT & leaf () const
unsigned leafSize () const
unsigned leafOffset () const
unsigned & leafOffset ()
bool valid () const
valid - Return true if path is at a valid node, not at end().
unsigned height () const
height - Return the height of the tree corresponding to this path.
NodeRef & subtree (unsigned Level) const
subtree - Get the subtree referenced from Level.
void reset (unsigned Level)
reset - Reset cached information about node(Level) from subtree(Level -1).
void push (NodeRef Node, unsigned Offset)
push - Add entry to path.
void pop ()
pop - Remove the last path entry.
void setSize (unsigned Level, unsigned Size)
setSize - Set the size of a node both in the path and in the tree.
void setRoot (void *Node, unsigned Size, unsigned Offset)
setRoot - Clear the path and set a new root node.
void replaceRoot (void *Root, unsigned Size, IdxPair Offsets)
replaceRoot - Replace the current root node with two new entries after the tree height has increased.
NodeRef getLeftSibling (unsigned Level) const
getLeftSibling - Get the left sibling node at Level, or a null NodeRef.
void moveLeft (unsigned Level)
moveLeft - Move path to the left sibling at Level.
void fillLeft (unsigned Height)
fillLeft - Grow path to Height by taking leftmost branches.
NodeRef getRightSibling (unsigned Level) const
getLeftSibling - Get the left sibling node at Level, or a null NodeRef.
void moveRight (unsigned Level)
moveRight - Move path to the left sibling at Level.
bool atBegin () const
atBegin - Return true if path is at begin().
bool atLastEntry (unsigned Level) const
atLastEntry - Return true if the path is at the last entry of the node at Level.
void legalizeForInsert (unsigned Level)
legalizeForInsert - Prepare the path for an insertion at Level.
Detailed Description
Definition at line 770 of file IntervalMap.h.
Member Function Documentation
atBegin()
bool llvm::IntervalMapImpl::Path::atBegin () const inline
atBegin - Return true if path is at begin().
Definition at line 897 of file IntervalMap.h.
References llvm::numbers::e, and llvm::SmallVectorBase::size().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::atBegin(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase().
atLastEntry()
bool llvm::IntervalMapImpl::Path::atLastEntry (unsigned Level) const inline
atLastEntry - Return true if the path is at the last entry of the node at Level.
Parameters
Level Node to examine.
Definition at line 907 of file IntervalMap.h.
References llvm::SmallVectorBase::size().
Referenced by getRightSibling(), and moveRight().
fillLeft()
void llvm::IntervalMapImpl::Path::fillLeft (unsigned Height) inline
fillLeft - Grow path to Height by taking leftmost branches.
Parameters
Height The target height.
Definition at line 881 of file IntervalMap.h.
References push().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::goToBegin().
getLeftSibling()
NodeRef llvm::IntervalMapImpl::Path::getLeftSibling (unsigned Level) const
getLeftSibling - Get the left sibling node at Level, or a null NodeRef.
Parameters
Level Get the sibling to node(Level).
Returns
Left sibling, or NodeRef().
Definition at line 24 of file IntervalMap.cpp.
References offset(), llvm::IntervalMapImpl::NodeRef::size(), and llvm::IntervalMapImpl::NodeRef::subtree().
getRightSibling()
NodeRef llvm::IntervalMapImpl::Path::getRightSibling (unsigned Level) const
getLeftSibling - Get the left sibling node at Level, or a null NodeRef.
Parameters
Level Get the sinbling to node(Level).
Returns
Left sibling, or NodeRef().
Definition at line 74 of file IntervalMap.cpp.
References atLastEntry(), offset(), and llvm::IntervalMapImpl::NodeRef::subtree().
height()
unsigned llvm::IntervalMapImpl::Path::height () const inline
height - Return the height of the tree corresponding to this path.
This matches map->height in a full path.
Definition at line 816 of file IntervalMap.h.
References llvm::SmallVectorBase::size().
Referenced by moveLeft().
leaf()
template<typename NodeT > NodeT& llvm::IntervalMapImpl::Path::leaf () const inline
Definition at line 802 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue().
leafOffset() [1/2]
unsigned llvm::IntervalMapImpl::Path::leafOffset () const inline
Definition at line 806 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator--(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator==(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue().
leafOffset() [2/2]
unsigned& llvm::IntervalMapImpl::Path::leafOffset () inline
Definition at line 807 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
leafSize()
unsigned llvm::IntervalMapImpl::Path::leafSize () const inline
Definition at line 805 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++().
legalizeForInsert()
void llvm::IntervalMapImpl::Path::legalizeForInsert (unsigned Level) inline
legalizeForInsert - Prepare the path for an insertion at Level.
When the path is at end(), node(Level) may not be a legal node. legalizeForInsert ensures that node(Level) is real by moving back to the last node at Level, and setting offset(Level) to size(Level) if required.
Parameters
Level The level where an insertion is about to take place.
Definition at line 916 of file IntervalMap.h.
References N.
moveLeft()
void llvm::IntervalMapImpl::Path::moveLeft (unsigned Level)
moveLeft - Move path to the left sibling at Level.
Leave nodes below Level unaltered.
Parameters
Level Move node(Level).
Definition at line 47 of file IntervalMap.cpp.
References assert(), height(), offset(), llvm::SmallVectorImpl< T >::resize(), and valid().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator--().
moveRight()
void llvm::IntervalMapImpl::Path::moveRight (unsigned Level)
moveRight - Move path to the left sibling at Level.
Leave nodes below Level unaltered.
Parameters
Level Move node(Level).
Definition at line 97 of file IntervalMap.cpp.
References assert(), atLastEntry(), offset(), size(), and subtree().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++().
node()
template<typename NodeT > NodeT& llvm::IntervalMapImpl::Path::node (unsigned Level) const inline
Definition at line 794 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase().
offset() [1/2]
unsigned llvm::IntervalMapImpl::Path::offset (unsigned Level) const inline
Definition at line 798 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), getLeftSibling(), getRightSibling(), moveLeft(), moveRight(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
offset() [2/2]
unsigned& llvm::IntervalMapImpl::Path::offset (unsigned Level) inline
Definition at line 799 of file IntervalMap.h.
pop()
void llvm::IntervalMapImpl::Path::pop () inline
pop - Remove the last path entry.
Definition at line 839 of file IntervalMap.h.
References llvm::SmallVectorTemplateBase< T, bool >::pop_back().
push()
void llvm::IntervalMapImpl::Path::push (NodeRef Node, unsigned Offset) inline
push - Add entry to path.
Parameters
Node Node to add, should be subtree(path.size()-1).
Offset Offset into Node.
Definition at line 834 of file IntervalMap.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
replaceRoot()
void llvm::IntervalMapImpl::Path::replaceRoot (void * Root, unsigned Size, IdxPair Offsets)
replaceRoot - Replace the current root node with two new entries after the tree height has increased.
Parameters
Root The new root node.
Size Number of entries in the new root.
Offsets Offsets into the root and first branch nodes.
Definition at line 18 of file IntervalMap.cpp.
References assert(), llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateCommon< T, typename >::front().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert().
reset()
void llvm::IntervalMapImpl::Path::reset (unsigned Level) inline
reset - Reset cached information about node(Level) from subtree(Level -1).
Parameters
Level 1..height. THe node to update after parent node changed.
Definition at line 827 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase().
setRoot()
void llvm::IntervalMapImpl::Path::setRoot (void * Node, unsigned Size, unsigned Offset) inline
setRoot - Clear the path and set a new root node.
Parameters
Node New root node.
Size New root size.
Offset Offset into root node.
Definition at line 857 of file IntervalMap.h.
References llvm::SmallVectorImpl< T >::clear(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setRoot().
setSize()
void llvm::IntervalMapImpl::Path::setSize (unsigned Level, unsigned Size) inline
setSize - Set the size of a node both in the path and in the tree.
Parameters
Level 0..height. Note that setting the root size won't change map->rootSize.
Size New node size.
Definition at line 847 of file IntervalMap.h.
References Size, and llvm::SmallVectorBase::size().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert().
size()
unsigned llvm::IntervalMapImpl::Path::size (unsigned Level) const inline
Definition at line 797 of file IntervalMap.h.
References llvm::SmallVectorBase::size().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and moveRight().
subtree()
NodeRef& llvm::IntervalMapImpl::Path::subtree (unsigned Level) const inline
subtree - Get the subtree referenced from Level.
When the path is consistent, node(Level + 1) == subtree(Level).
Parameters
Level 0..height-1. The leaves have no subtrees.
Definition at line 821 of file IntervalMap.h.
Referenced by moveRight().
valid()
bool llvm::IntervalMapImpl::Path::valid () const inline
valid - Return true if path is at a valid node, not at end().
Definition at line 810 of file IntervalMap.h.
References llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateCommon< T, typename >::front().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), moveLeft(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid().
The documentation for this class was generated from the following files:
include/llvm/ADT/IntervalMap.h
lib/Support/IntervalMap.cpp