LLVM: llvm::StringSet< AllocatorTy > Class Template Reference
llvm::StringSet< AllocatorTy > Class Template Reference
StringSet - A wrapper for StringMap that provides set-like functionality.
#include "llvm/ADT/StringSet.h"
Public Member Functions
StringSet ()=default
StringSet (std::initializer_list< StringRef > S)
StringSet (AllocatorTy A)
std::pair< typename base::iterator, bool > insert (StringRef Key)
template<typename InputIt >
void insert (const InputIt &Begin, const InputIt &End)
template<typename ValueTy >
std::pair< typename base::iterator, bool > insert (const StringMapEntry< ValueTy > &MapEntry)
Public Member Functions inherited from llvm::StringMap< NoneType, AllocatorTy >
StringMap ()
StringMap (unsigned InitialSize)
StringMap (AllocatorTy A)
StringMap (unsigned InitialSize, AllocatorTy A)
StringMap (std::initializer_list< std::pair< StringRef, NoneType >> List)
StringMap (StringMap &&RHS)
StringMap (const StringMap &RHS)
StringMap & operator= (StringMap RHS)
~StringMap ()
AllocatorTy & getAllocator ()
const AllocatorTy & getAllocator () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator_range< StringMapKeyIterator< NoneType > > keys () const
iterator find (StringRef Key)
const_iterator find (StringRef Key) const
NoneType lookup (StringRef Key) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
NoneType & operator[] (StringRef Key)
Lookup the ValueTy for the Key, or create a default constructed value if the key is not in the map.
size_type count (StringRef Key) const
count - Return 1 if the element is in the map, 0 otherwise.
size_type count (const StringMapEntry< InputTy > &MapEntry) const
bool insert (MapEntryTy *KeyValue)
insert - Insert the specified key/value pair into the map.
std::pair< iterator, bool > insert (std::pair< StringRef, NoneType > KV)
insert - Inserts the specified key/value pair into the map if the key isn't already in the map.
std::pair< iterator, bool > insert_or_assign (StringRef Key, V &&Val)
Inserts an element or assigns to the current element if the key already exists.
std::pair< iterator, bool > try_emplace (StringRef Key, ArgsTy &&... Args)
Emplace a new element for the specified key into the map if the key isn't already in the map.
void clear ()
void remove (MapEntryTy *KeyValue)
remove - Remove the specified key/value pair from the map, but do not erase it.
void erase (iterator I)
bool erase (StringRef Key)
Public Member Functions inherited from llvm::StringMapImpl
unsigned getNumBuckets () const
unsigned getNumItems () const
bool empty () const
unsigned size () const
void swap (StringMapImpl &Other)
Additional Inherited Members
Public Types inherited from llvm::StringMap< NoneType, AllocatorTy >
using MapEntryTy = StringMapEntry< NoneType >
using key_type = const char *
using mapped_type = NoneType
using value_type = StringMapEntry< NoneType >
using size_type = size_t
using const_iterator = StringMapConstIterator< NoneType >
using iterator = StringMapIterator< NoneType >
Static Public Member Functions inherited from llvm::StringMapImpl
static StringMapEntryBase * getTombstoneVal ()
Protected Member Functions inherited from llvm::StringMapImpl
StringMapImpl (unsigned itemSize)
StringMapImpl (StringMapImpl &&RHS)
StringMapImpl (unsigned InitSize, unsigned ItemSize)
unsigned RehashTable (unsigned BucketNo=0)
RehashTable - Grow the table, redistributing values into the buckets with the appropriate mod-of-hashtable-size.
unsigned LookupBucketFor (StringRef Key)
LookupBucketFor - Look up the bucket that the specified string should end up in.
int FindKey (StringRef Key) const
FindKey - Look up the bucket that contains the specified key.
void RemoveKey (StringMapEntryBase *V)
RemoveKey - Remove the specified StringMapEntry from the table, but do not delete it.
StringMapEntryBase * RemoveKey (StringRef Key)
RemoveKey - Remove the StringMapEntry for the specified key from the table, returning it.
void init (unsigned Size)
Allocate the table with the specified number of buckets and otherwise setup the map as empty.
Protected Attributes inherited from llvm::StringMapImpl
StringMapEntryBase ** TheTable = nullptr
unsigned NumBuckets = 0
unsigned NumItems = 0
unsigned NumTombstones = 0
unsigned ItemSize
Detailed Description
template<class AllocatorTy = MallocAllocator>
class llvm::StringSet< AllocatorTy >
StringSet - A wrapper for StringMap that provides set-like functionality.
Definition at line 27 of file StringSet.h.
Constructor & Destructor Documentation
StringSet() [1/3]
template<class AllocatorTy = MallocAllocator> llvm::StringSet< AllocatorTy >::StringSet () default
StringSet() [2/3]
template<class AllocatorTy = MallocAllocator> llvm::StringSet< AllocatorTy >::StringSet (std::initializer_list< StringRef > S) inline
Definition at line 32 of file StringSet.h.
References llvm::StringSet< AllocatorTy >::insert(), and X.
StringSet() [3/3]
template<class AllocatorTy = MallocAllocator> llvm::StringSet< AllocatorTy >::StringSet (AllocatorTy A) inline explicit
Definition at line 36 of file StringSet.h.
Member Function Documentation
insert() [1/3]
template<class AllocatorTy = MallocAllocator> std::pair<typename base::iterator, bool> llvm::StringSet< AllocatorTy >::insert (StringRef Key) inline
Definition at line 38 of file StringSet.h.
References assert(), llvm::StringRef::empty(), llvm::StringMap< NoneType, AllocatorTy >::insert(), and llvm::None.
Referenced by llvm::InstrProfSymtab::addFuncName(), llvm::LTOCodeGenerator::addMustPreserveSymbol(), llvm::coverage::CoverageFilenamesSectionWriter::CoverageFilenamesSectionWriter(), llvm::CodeInit::get(), getMinVisibility(), llvm::vfs::OverlayFileSystem::getRealPath(), llvm::vfs::VFSFromYamlDirIterImpl::increment(), llvm::StringSet< AllocatorTy >::insert(), llvm::MachineRegisterInfo::insertVRegByName(), isMips64EL(), IsRevOpcode(), llvm::opt::OptTable::OptTable(), parseCHRFilterFiles(), llvm::LTOCodeGenerator::setAsmUndefinedRefs(), llvm::StringSet< AllocatorTy >::StringSet(), llvm::TGLexer::TGLexer(), llvm::FileCheck::ValidateCheckPrefixes(), and zero().
insert() [2/3]
template<class AllocatorTy = MallocAllocator> template<typename InputIt > void llvm::StringSet< AllocatorTy >::insert (const InputIt & Begin, const InputIt & End) inline
Definition at line 44 of file StringSet.h.
insert() [3/3]
template<class AllocatorTy = MallocAllocator> template<typename ValueTy > std::pair<typename base::iterator, bool> llvm::StringSet< AllocatorTy >::insert (const StringMapEntry< ValueTy > & MapEntry) inline
Definition at line 51 of file StringSet.h.
References llvm::StringMapEntry< ValueTy >::getKey(), and llvm::StringSet< AllocatorTy >::insert().
The documentation for this class was generated from the following file:
include/llvm/ADT/StringSet.h