LLVM: llvm::AMDGPUAsmPrinter Class Reference
llvm::AMDGPUAsmPrinter Class Reference final
#include "Target/AMDGPU/AMDGPUAsmPrinter.h"
Public Member Functions
AMDGPUAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
const MCSubtargetInfo * getGlobalSTI () const
AMDGPUTargetStreamer * getTargetStreamer () const
bool doFinalization (Module &M) override
Shut down the asmprinter.
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp) const
Wrapper for MCInstLowering.lowerOperand() for the tblgen'erated pseudo lowering.
const MCExpr * lowerConstant (const Constant *CV) override
Lower the specified LLVM Constant to an MCExpr.
bool emitPseudoExpansionLowering (MCStreamer &OutStreamer, const MachineInstr *MI)
tblgen'erated driver function for lowering simple MI->MC pseudo instructions.
void EmitInstruction (const MachineInstr *MI) override
Implemented in AMDGPUMCInstLower.cpp.
void EmitFunctionBodyStart () override
Targets can override this to emit stuff before the first basic block in the function.
void EmitFunctionBodyEnd () override
Targets can override this to emit stuff after the last basic block in the function.
void EmitFunctionEntryLabel () override
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
void EmitBasicBlockStart (const MachineBasicBlock &MBB) override
Targets can override this to emit stuff at the start of a basic block.
void EmitGlobalVariable (const GlobalVariable *GV) override
Emit the specified global variable to the .s file.
void EmitStartOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the start of their file.
void EmitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const override
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Public Member Functions inherited from llvm::AsmPrinter
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getCurExceptionSym ()
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void EmitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitRemarksSection (RemarkStreamer &RS)
CFIMoveType needsCFIMoves () const
bool needsOnlyDebugCFIMoves () const
Returns false if needsCFIMoves() == CFI_M_EH for any function in the module.
bool needsSEHMoves ()
virtual void EmitConstantPool ()
Print to the current output stream assembly representations of the constants in the constant pool MCP.
virtual void EmitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void EmitAlignment (Align Alignment, const GlobalObject *GV=nullptr) const
Emit an alignment directive to the specified power of two boundary.
void EmitGlobalConstant (const DataLayout &DL, const Constant *CV)
Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps (StackMaps &SM)
Emit the stack maps.
virtual void EmitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void EmitFunctionDescriptor ()
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void EmitXXStructor (const DataLayout &DL, const Constant *CV)
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void EmitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void EmitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset".
void EmitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void EmitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-byte offset of a string from the start of its section.
void EmitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void EmitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
virtual void EmitDebugValue (const MCExpr *Value, unsigned Size) const
Emit the directive and value for debug thread local expression.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T >
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void PrintSymbolOperand (const MachineOperand &MO, raw_ostream &OS)
Print the MachineOperand as a symbol.
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS)
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
virtual void emitInlineAsmStart () const
Let the target do anything it needs to do before emitting inlineasm.
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Let the target do anything it needs to do after emitting inlineasm.
void EmitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
void EmitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Attributes
std::vector< std::string > DisasmLines
std::vector< std::string > HexLines
size_t DisasmLineMaxLen
Protected Attributes inherited from llvm::AsmPrinter
MCSymbol * CurrentFnBegin = nullptr
SmallVector< HandlerInfo, 1 > Handlers
A vector of all debug/EH info emitters we should use.
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum SledKind : uint8_t {
SledKind::FUNCTION_ENTER = 0, SledKind::FUNCTION_EXIT = 1, SledKind::TAIL_CALL = 2, SledKind::LOG_ARGS_ENTER = 3,
SledKind::CUSTOM_EVENT = 4, SledKind::TYPED_EVENT = 5
}
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
using GOTEquivUsePair = std::pair< const GlobalVariable *, unsigned >
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
Static Public Member Functions inherited from llvm::AsmPrinter
static Align getGVAlignment (const GlobalValue *GV, const DataLayout &DL, Align InAlign=Align::None())
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineLoopInfo.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE
Optimization remark emitter.
MachineBlockFrequencyInfo * MBFI
ProfileSummaryInfo * PSI
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
unsigned XRayFnUniqueID = 0
DenseMap< const MCSection *, unsigned > PatchableFunctionEntryID
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 39 of file AMDGPUAsmPrinter.h.
Constructor & Destructor Documentation
AMDGPUAsmPrinter()
AMDGPUAsmPrinter::AMDGPUAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) explicit
Definition at line 100 of file AMDGPUAsmPrinter.cpp.
References getGlobalSTI(), and llvm::AMDGPU::IsaInfo::hasCodeObjectV3().
Member Function Documentation
doFinalization()
bool AMDGPUAsmPrinter::doFinalization (Module & M) override virtual
Shut down the asmprinter.
If you override this in your pass, you must make sure to call it explicitly.
Reimplemented from llvm::AsmPrinter.
Definition at line 324 of file AMDGPUAsmPrinter.cpp.
References llvm::Triple::AMDHSA, llvm::Triple::AMDPAL, assert(), llvm::amdhsa::kernel_descriptor_t::compute_pgm_rsrc1, llvm::amdhsa::kernel_descriptor_t::compute_pgm_rsrc2, llvm::SIProgramInfo::ComputePGMRSrc1, llvm::SIProgramInfo::ComputePGMRSrc2, llvm::AsmPrinter::doFinalization(), llvm::AMDGPUTargetStreamer::EmitCodeEnd(), getGlobalSTI(), llvm::MachineFunction::getInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::Triple::getOS(), llvm::MachineFunction::getSubtarget(), getTargetStreamer(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::amdhsa::kernel_descriptor_t::group_segment_fixed_size, llvm::SIMachineFunctionInfo::hasDispatchID(), llvm::SIMachineFunctionInfo::hasDispatchPtr(), llvm::SIMachineFunctionInfo::hasFlatScratchInit(), llvm::SIMachineFunctionInfo::hasKernargSegmentPtr(), llvm::SIMachineFunctionInfo::hasPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::hasQueuePtr(), llvm::AMDGPU::isGFX10(), llvm::AMDGPUMachineFunction::isMemoryBound(), llvm::isUInt< 32 >(), llvm::GCNSubtarget::isWave32(), llvm::amdhsa::kernel_descriptor_t::kernel_code_properties, llvm::SIProgramInfo::LDSSize, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutStreamer, llvm::amdhsa::kernel_descriptor_t::private_segment_fixed_size, and llvm::SIProgramInfo::ScratchSize.
EmitBasicBlockStart()
void AMDGPUAsmPrinter::EmitBasicBlockStart (const MachineBasicBlock & MBB) override virtual
Targets can override this to emit stuff at the start of a basic block.
EmitBasicBlockStart - This method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
By default, this method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 275 of file AMDGPUAsmPrinter.cpp.
References DisasmLineMaxLen, DisasmLines, llvm::AsmPrinter::EmitBasicBlockStart(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineBasicBlock::getNumber(), HexLines, isBlockOnlyReachableByFallthrough(), and llvm::max().
EmitEndOfAsmFile()
void AMDGPUAsmPrinter::EmitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 155 of file AMDGPUAsmPrinter.cpp.
References llvm::Triple::AMDHSA, assert(), llvm::AMDGPUTargetStreamer::EmitISAVersion(), getGlobalSTI(), llvm::Triple::getOS(), getTargetStreamer(), llvm::TargetMachine::getTargetTriple(), llvm::AMDGPU::IsaInfo::hasCodeObjectV3(), llvm::raw_string_ostream::str(), llvm::AMDGPU::IsaInfo::streamIsaVersion(), Success, and llvm::AsmPrinter::TM.
EmitFunctionBodyEnd()
void AMDGPUAsmPrinter::EmitFunctionBodyEnd () override virtual
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 210 of file AMDGPUAsmPrinter.cpp.
References llvm::Triple::AMDHSA, Context, llvm::AMDGPUTargetStreamer::EmitAmdhsaKernelDescriptor(), llvm::SIProgramInfo::FlatUsed, llvm::MachineFunction::getFunction(), getGlobalSTI(), llvm::MachineFunction::getInfo(), llvm::AsmPrinter::getNameWithPrefix(), llvm::AMDGPU::IsaInfo::getNumExtraSGPRs(), llvm::Triple::getOS(), llvm::MCTargetStreamer::getStreamer(), llvm::MachineFunction::getSubtarget(), getTargetStreamer(), llvm::TargetMachine::getTargetTriple(), llvm::AMDGPU::IsaInfo::hasCodeObjectV3(), llvm::AMDGPU::hasXNACK(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::AsmPrinter::MF, llvm::SIProgramInfo::NumSGPRsForWavesPerEU, llvm::SIProgramInfo::NumVGPRsForWavesPerEU, llvm::AsmPrinter::TM, and llvm::SIProgramInfo::VCCUsed.
EmitFunctionBodyStart()
void AMDGPUAsmPrinter::EmitFunctionBodyStart () override virtual
Targets can override this to emit stuff before the first basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 191 of file AMDGPUAsmPrinter.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, llvm::AMDGPUTargetStreamer::EmitAMDKernelCodeT(), F(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), getTargetStreamer(), llvm::GCNSubtarget::hasCodeObjectV3(), llvm::AMDGPUSubtarget::isAmdHsaOrMesa(), llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::AsmPrinter::MF, and llvm::CallingConv::SPIR_KERNEL.
EmitFunctionEntryLabel()
void AMDGPUAsmPrinter::EmitFunctionEntryLabel () override virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 250 of file AMDGPUAsmPrinter.cpp.
References llvm::Triple::AMDHSA, DisasmLineMaxLen, DisasmLines, llvm::AMDGPUTargetStreamer::EmitAMDGPUSymbolType(), llvm::AsmPrinter::EmitFunctionEntryLabel(), llvm::MachineFunction::getFunction(), getGlobalSTI(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getName(), llvm::AsmPrinter::getNameWithPrefix(), llvm::Triple::getOS(), llvm::MachineFunction::getSubtarget(), getTargetStreamer(), llvm::TargetMachine::getTargetTriple(), llvm::AMDGPU::IsaInfo::hasCodeObjectV3(), HexLines, llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::max(), llvm::AsmPrinter::MF, llvm::StringRef::str(), llvm::ELF::STT_AMDGPU_HSA_KERNEL, llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName, and llvm::AsmPrinter::TM.
EmitGlobalVariable()
void AMDGPUAsmPrinter::EmitGlobalVariable (const GlobalVariable * GV) override virtual
Emit the specified global variable to the .s file.
EmitGlobalVariable - Emit the specified global variable to the .s file.
Reimplemented from llvm::AsmPrinter.
Definition at line 287 of file AMDGPUAsmPrinter.cpp.
References llvm::Triple::AMDHSA, llvm::Triple::AMDPAL, llvm::AsmPrinter::EmitGlobalVariable(), llvm::AsmPrinter::EmitLinkage(), llvm::AsmPrinter::EmitVisibility(), llvm::GlobalValue::getAddressSpace(), llvm::GlobalObject::getAlignment(), llvm::Module::getDataLayout(), llvm::GlobalVariable::getInitializer(), llvm::MCSymbol::getName(), llvm::Value::getName(), llvm::Triple::getOS(), llvm::GlobalValue::getParent(), llvm::AsmPrinter::getSymbol(), getTargetStreamer(), llvm::TargetMachine::getTargetTriple(), llvm::DataLayout::getTypeAllocSize(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::getVisibility(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::isDeclaration(), llvm::MCSymbol::isDefined(), llvm::MCSymbol::isVariable(), AMDGPUAS::LOCAL_ADDRESS, llvm::AsmPrinter::OutContext, llvm::MCSymbol::redefineIfPossible(), llvm::report_fatal_error(), llvm::MCContext::reportError(), Size, and llvm::AsmPrinter::TM.
EmitInstruction()
void AMDGPUAsmPrinter::EmitInstruction (const MachineInstr * MI) override virtual
Implemented in AMDGPUMCInstLower.cpp.
Reimplemented from llvm::AsmPrinter.
Definition at line 257 of file AMDGPUMCInstLower.cpp.
References emitPseudoExpansionLowering(), llvm::MachineFunction::getSubtarget(), llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
emitPseudoExpansionLowering()
bool llvm::AMDGPUAsmPrinter::emitPseudoExpansionLowering (MCStreamer & OutStreamer, const MachineInstr * MI)
tblgen'erated driver function for lowering simple MI->MC pseudo instructions.
Referenced by EmitInstruction().
EmitStartOfAsmFile()
void AMDGPUAsmPrinter::EmitStartOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 123 of file AMDGPUAsmPrinter.cpp.
References llvm::Triple::AMDHSA, llvm::Triple::AMDPAL, llvm::AMDGPUTargetStreamer::EmitDirectiveAMDGCNTarget(), llvm::AMDGPUTargetStreamer::EmitDirectiveHSACodeObjectISA(), llvm::AMDGPUTargetStreamer::EmitDirectiveHSACodeObjectVersion(), llvm::getCPU(), getGlobalSTI(), llvm::AMDGPU::getIsaVersion(), llvm::Triple::getOS(), llvm::AMDGPUTargetStreamer::getPALMetadata(), getTargetStreamer(), llvm::TargetMachine::getTargetTriple(), llvm::AMDGPU::IsaInfo::hasCodeObjectV3(), llvm::AMDGPU::IsaVersion::Major, llvm::AMDGPU::IsaVersion::Minor, llvm::AMDGPUPALMetadata::readFromIR(), llvm::AMDGPU::IsaVersion::Stepping, llvm::AMDGPU::IsaInfo::streamIsaVersion(), llvm::AsmPrinter::TM, and llvm::IndexedInstrProf::Version.
getGlobalSTI()
const MCSubtargetInfo * AMDGPUAsmPrinter::getGlobalSTI () const
Definition at line 113 of file AMDGPUAsmPrinter.cpp.
References llvm::TargetMachine::getMCSubtargetInfo(), and llvm::AsmPrinter::TM.
Referenced by AMDGPUAsmPrinter(), doFinalization(), EmitEndOfAsmFile(), EmitFunctionBodyEnd(), EmitFunctionEntryLabel(), EmitStartOfAsmFile(), and hasAnyNonFlatUseOfReg().
getPassName()
StringRef AMDGPUAsmPrinter::getPassName () const override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 109 of file AMDGPUAsmPrinter.cpp.
getTargetStreamer()
AMDGPUTargetStreamer * AMDGPUAsmPrinter::getTargetStreamer () const
Definition at line 117 of file AMDGPUAsmPrinter.cpp.
References llvm::AsmPrinter::OutStreamer.
Referenced by doFinalization(), EmitEndOfAsmFile(), EmitFunctionBodyEnd(), EmitFunctionBodyStart(), EmitFunctionEntryLabel(), EmitGlobalVariable(), EmitStartOfAsmFile(), and getRsrcReg().
isBlockOnlyReachableByFallthrough()
bool AMDGPUAsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const override virtual
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented from llvm::AsmPrinter.
Definition at line 177 of file AMDGPUAsmPrinter.cpp.
References llvm::MachineBasicBlock::back(), llvm::MachineBasicBlock::empty(), llvm::MachineInstr::getOpcode(), and llvm::AsmPrinter::isBlockOnlyReachableByFallthrough().
Referenced by EmitBasicBlockStart().
lowerConstant()
const MCExpr * AMDGPUAsmPrinter::lowerConstant (const Constant * CV) override virtual
Lower the specified LLVM Constant to an MCExpr.
The AsmPrinter::lowerConstantof does not know how to lower addrspacecast, therefore they should be lowered by this function.
Reimplemented from llvm::AsmPrinter.
Definition at line 251 of file AMDGPUMCInstLower.cpp.
References E, lowerAddrSpaceCast(), llvm::AsmPrinter::lowerConstant(), llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::TM.
lowerOperand()
bool AMDGPUAsmPrinter::lowerOperand (const MachineOperand & MO, MCOperand & MCOp) const
Wrapper for MCInstLowering.lowerOperand() for the tblgen'erated pseudo lowering.
Definition at line 220 of file AMDGPUMCInstLower.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::AsmPrinter::MF, and llvm::AsmPrinter::OutContext.
PrintAsmOperand()
bool AMDGPUAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & O) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate for machine specific ExtraCodes or when the arch-independent handling would be too complex otherwise.
Reimplemented from llvm::AsmPrinter.
Definition at line 1283 of file AMDGPUAsmPrinter.cpp.
References llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isReg(), llvm::RISCVFenceField::O, llvm::AsmPrinter::PrintAsmOperand(), and llvm::AMDGPUInstPrinter::printRegOperand().
runOnMachineFunction()
bool AMDGPUAsmPrinter::runOnMachineFunction (MachineFunction & MF) override virtual
Emit the specified function out to the OutStreamer.
Reimplemented from llvm::AsmPrinter.
Definition at line 419 of file AMDGPUAsmPrinter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::SIProgramInfo::ComputePGMRSrc2, Context, DisasmLineMaxLen, DisasmLines, llvm::GCNSubtarget::dumpCode(), llvm::AsmPrinter::EmitFunctionBody(), llvm::empty(), llvm::SIProgramInfo::FloatMode, G_00B84C_TGID_X_EN, G_00B84C_TGID_Y_EN, G_00B84C_TGID_Z_EN, G_00B84C_TIDIG_COMP_CNT, G_00B84C_TRAP_HANDLER, G_00B84C_USER_SGPR, llvm::TargetLoweringObjectFile::getContext(), llvm::MCAssembler::getEmitterPtr(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineFunction::getSubtarget(), llvm::GCNSubtarget::hasMAIInsts(), HexLines, I, llvm::SIProgramInfo::IEEEMode, Info, llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::AMDGPUSubtarget::isAmdPalOS(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::AsmPrinter::isVerbose(), llvm::SIProgramInfo::LDSSize, MI, llvm::AMDGPUMachineFunction::needsWaveLimiter(), llvm::SIProgramInfo::NumAccVGPR, llvm::SIProgramInfo::NumArchVGPR, llvm::SIProgramInfo::NumSGPR, llvm::SIProgramInfo::NumSGPRsForWavesPerEU, llvm::SIProgramInfo::NumVGPR, llvm::SIProgramInfo::NumVGPRsForWavesPerEU, llvm::SIProgramInfo::Occupancy, llvm::AsmPrinter::OutStreamer, llvm::SIProgramInfo::ScratchSize, llvm::MachineFunction::setAlignment(), llvm::AsmPrinter::SetupMachineFunction(), llvm::SIProgramInfo::SGPRBlocks, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PROGBITS, llvm::size(), TII, and llvm::SIProgramInfo::VGPRBlocks.
Member Data Documentation
DisasmLineMaxLen
size_t llvm::AMDGPUAsmPrinter::DisasmLineMaxLen protected
Definition at line 148 of file AMDGPUAsmPrinter.h.
Referenced by EmitBasicBlockStart(), EmitFunctionEntryLabel(), and runOnMachineFunction().
DisasmLines
std::vector<std::string> llvm::AMDGPUAsmPrinter::DisasmLines protected
Definition at line 147 of file AMDGPUAsmPrinter.h.
Referenced by EmitBasicBlockStart(), EmitFunctionEntryLabel(), and runOnMachineFunction().
HexLines
std::vector<std::string> llvm::AMDGPUAsmPrinter::HexLines protected
Definition at line 147 of file AMDGPUAsmPrinter.h.
Referenced by EmitBasicBlockStart(), EmitFunctionEntryLabel(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUAsmPrinter.h
lib/Target/AMDGPU/AMDGPUAsmPrinter.cpp
lib/Target/AMDGPU/AMDGPUMCInstLower.cpp