LLVM: llvm::GCNIterativeScheduler Class Reference
llvm::GCNIterativeScheduler Class Reference
#include "Target/AMDGPU/GCNIterativeScheduler.h"
Classes
class BuildDAG
class OverrideLegacyStrategy
struct Region
struct TentativeSchedule
Public Types
enum StrategyKind { SCHEDULE_MINREGONLY, SCHEDULE_MINREGFORCED, SCHEDULE_LEGACYMAXOCCUPANCY, SCHEDULE_ILP }
Public Types inherited from llvm::ScheduleDAGInstrs
using SUList = std::list< SUnit * >
A list of SUnits, used in Value2SUsMap, during DAG construction.
Public Member Functions
GCNIterativeScheduler (MachineSchedContext *C, StrategyKind S)
void schedule () override
Implement ScheduleDAGInstrs interface for scheduling a sequence of reorderable instructions.
void enterRegion (MachineBasicBlock *BB, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned RegionInstrs) override
Implement the ScheduleDAGInstrs interface for handling the next scheduling region.
void finalizeSchedule () override
Allow targets to perform final scheduling actions at the level of the whole MachineFunction.
Public Member Functions inherited from llvm::ScheduleDAGMILive
ScheduleDAGMILive (MachineSchedContext *C, std::unique_ptr< MachineSchedStrategy > S)
~ScheduleDAGMILive () override
bool hasVRegLiveness () const override
Return true if this DAG supports VReg liveness and RegPressure.
bool isTrackingPressure () const
Return true if register pressure tracking is enabled.
const IntervalPressure & getTopPressure () const
Get current register pressure for the top scheduled instructions.
const RegPressureTracker & getTopRPTracker () const
const IntervalPressure & getBotPressure () const
Get current register pressure for the bottom scheduled instructions.
const RegPressureTracker & getBotRPTracker () const
const IntervalPressure & getRegPressure () const
Get register pressure for the entire scheduling region before scheduling.
const std::vector< PressureChange > & getRegionCriticalPSets () const
PressureDiff & getPressureDiff (const SUnit *SU)
const PressureDiff & getPressureDiff (const SUnit *SU) const
void computeDFSResult ()
Compute a DFSResult after DAG building is complete, and before any queue comparisons.
const SchedDFSResult * getDFSResult () const
Return a non-null DFS result if the scheduling strategy initialized it.
BitVector & getScheduledTrees ()
unsigned computeCyclicCriticalPath ()
Compute the cyclic critical path through the DAG.
void dump () const override
Public Member Functions inherited from llvm::ScheduleDAGMI
ScheduleDAGMI (MachineSchedContext *C, std::unique_ptr< MachineSchedStrategy > S, bool RemoveKillFlags)
~ScheduleDAGMI () override
bool doMBBSchedRegionsTopDown () const override
If this method returns true, handling of the scheduling regions themselves (in case of a scheduling boundary in MBB) will be done beginning with the topmost region of MBB.
LiveIntervals * getLIS () const
void addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation)
Add a postprocessing step to the DAG builder.
MachineBasicBlock::iterator top () const
MachineBasicBlock::iterator bottom () const
void startBlock (MachineBasicBlock *bb) override
Prepares to perform scheduling in the given block.
void finishBlock () override
Cleans up after scheduling in the given block.
void moveInstruction (MachineInstr *MI, MachineBasicBlock::iterator InsertPos)
Change the position of an instruction within the basic block and update live ranges and region boundary iterators.
const SUnit * getNextClusterPred () const
const SUnit * getNextClusterSucc () const
void viewGraph (const Twine &Name, const Twine &Title) override
viewGraph - Pop up a ghostview window with the reachable parts of the DAG rendered using 'dot'.
void viewGraph () override
Out-of-line implementation with no arguments is handy for gdb.
Public Member Functions inherited from llvm::ScheduleDAGInstrs
ScheduleDAGInstrs (MachineFunction &mf, const MachineLoopInfo *mli, bool RemoveKillFlags=false)
~ScheduleDAGInstrs () override=default
const TargetSchedModel * getSchedModel () const
Gets the machine model for instruction scheduling.
const MCSchedClassDesc * getSchedClass (SUnit *SU) const
Resolves and cache a resolved scheduling class for an SUnit.
MachineBasicBlock::iterator begin () const
Returns an iterator to the top of the current scheduling region.
MachineBasicBlock::iterator end () const
Returns an iterator to the bottom of the current scheduling region.
SUnit * newSUnit (MachineInstr *MI)
Creates a new SUnit and return a ptr to it.
SUnit * getSUnit (MachineInstr *MI) const
Returns an existing SUnit for this MI, or nullptr.
virtual void exitRegion ()
Called when the scheduler has finished scheduling the current region.
void buildSchedGraph (AAResults *AA, RegPressureTracker *RPTracker=nullptr, PressureDiffs *PDiffs=nullptr, LiveIntervals *LIS=nullptr, bool TrackLaneMasks=false)
Builds SUnits for the current region.
void addSchedBarrierDeps ()
Adds dependencies from instructions in the current list of instructions being scheduled to scheduling barrier.
void dumpNode (const SUnit &SU) const override
void dump () const override
std::string getGraphNodeLabel (const SUnit *SU) const override
Returns a label for a DAG node that points to an instruction.
std::string getDAGName () const override
Returns a label for the region of code covered by the DAG.
void fixupKills (MachineBasicBlock &MBB)
Fixes register kill flags that scheduling has made invalid.
bool canAddEdge (SUnit *SuccSU, SUnit *PredSU)
True if an edge can be added from PredSU to SuccSU without creating a cycle.
bool addEdge (SUnit *SuccSU, const SDep &PredDep)
Add a DAG edge to the given SU with the given predecessor dependence data.
Public Member Functions inherited from llvm::ScheduleDAG
ScheduleDAG (MachineFunction &mf)
virtual ~ScheduleDAG ()
void clearDAG ()
Clears the DAG state (between regions).
const MCInstrDesc * getInstrDesc (const SUnit *SU) const
Returns the MCInstrDesc of this SUnit.
void dumpNodeName (const SUnit &SU) const
virtual void addCustomGraphFeatures (GraphWriter< ScheduleDAG *> &) const
Adds custom features for a visualization of the ScheduleDAG.
unsigned VerifyScheduledDAG (bool isBottomUp)
Verifies that all SUnits were scheduled and that their state is consistent.
Protected Types
using ScheduleRef = ArrayRef< const SUnit * >
Protected Types inherited from llvm::ScheduleDAGInstrs
using DbgValueVector = std::vector< std::pair< MachineInstr *, MachineInstr * > >
Protected Member Functions
template<typename Range >
GCNRegPressure getSchedulePressure (const Region &R, Range &&Schedule) const
GCNRegPressure getRegionPressure (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End) const
GCNRegPressure getRegionPressure (const Region &R) const
void setBestSchedule (Region &R, ScheduleRef Schedule, const GCNRegPressure &MaxRP=GCNRegPressure())
void scheduleBest (Region &R)
std::vector< MachineInstr * > detachSchedule (ScheduleRef Schedule) const
void sortRegionsByPressure (unsigned TargetOcc)
template<typename Range >
void scheduleRegion (Region &R, Range &&Schedule, const GCNRegPressure &MaxRP=GCNRegPressure())
unsigned tryMaximizeOccupancy (unsigned TargetOcc=std::numeric_limits< unsigned >::max())
void scheduleLegacyMaxOccupancy (bool TryMaximizeOccupancy=true)
void scheduleMinReg (bool force=false)
void scheduleILP (bool TryMaximizeOccupancy=true)
void printRegions (raw_ostream &OS) const
void printSchedResult (raw_ostream &OS, const Region *R, const GCNRegPressure &RP) const
void printSchedRP (raw_ostream &OS, const GCNRegPressure &Before, const GCNRegPressure &After) const
Protected Member Functions inherited from llvm::ScheduleDAGMILive
void buildDAGWithRegPressure ()
Call ScheduleDAGInstrs::buildSchedGraph with register pressure tracking enabled.
void initQueues (ArrayRef< SUnit *> TopRoots, ArrayRef< SUnit *> BotRoots)
Release ExitSU predecessors and setup scheduler queues.
void scheduleMI (SUnit *SU, bool IsTopNode)
Move an instruction and update register pressure.
void initRegPressure ()
void updatePressureDiffs (ArrayRef< RegisterMaskPair > LiveUses)
Update the PressureDiff array for liveness after scheduling this instruction.
void updateScheduledPressure (const SUnit *SU, const std::vector< unsigned > &NewMaxPressure)
void collectVRegUses (SUnit &SU)
Protected Member Functions inherited from llvm::ScheduleDAGMI
void postprocessDAG ()
Apply each ScheduleDAGMutation step in order.
void initQueues (ArrayRef< SUnit *> TopRoots, ArrayRef< SUnit *> BotRoots)
Release ExitSU predecessors and setup scheduler queues.
void updateQueues (SUnit *SU, bool IsTopNode)
Update scheduler DAG and queues after scheduling an instruction.
void placeDebugValues ()
Reinsert debug_values recorded in ScheduleDAGInstrs::DbgValues.
void dumpSchedule () const
dump the scheduled Sequence.
bool checkSchedLimit ()
void findRootsAndBiasEdges (SmallVectorImpl< SUnit *> &TopRoots, SmallVectorImpl< SUnit *> &BotRoots)
void releaseSucc (SUnit *SU, SDep *SuccEdge)
ReleaseSucc - Decrement the NumPredsLeft count of a successor.
void releaseSuccessors (SUnit *SU)
releaseSuccessors - Call releaseSucc on each of SU's successors.
void releasePred (SUnit *SU, SDep *PredEdge)
ReleasePred - Decrement the NumSuccsLeft count of a predecessor.
void releasePredecessors (SUnit *SU)
releasePredecessors - Call releasePred on each of SU's predecessors.
Protected Member Functions inherited from llvm::ScheduleDAGInstrs
void reduceHugeMemNodeMaps (Value2SUsMap &stores, Value2SUsMap &loads, unsigned N)
Reduces maps in FIFO order, by N SUs.
void addChainDependency (SUnit *SUa, SUnit *SUb, unsigned Latency=0)
Adds a chain edge between SUa and SUb, but only if both AAResults and Target fail to deny the dependency.
void addChainDependencies (SUnit *SU, SUList &SUs, unsigned Latency)
Adds dependencies as needed from all SUs in list to SU.
void addChainDependencies (SUnit *SU, Value2SUsMap &Val2SUsMap)
Adds dependencies as needed from all SUs in map, to SU.
void addChainDependencies (SUnit *SU, Value2SUsMap &Val2SUsMap, ValueType V)
Adds dependencies as needed to SU, from all SUs mapped to V.
void addBarrierChain (Value2SUsMap &map)
Adds barrier chain edges from all SUs in map, and then clear the map.
void insertBarrierChain (Value2SUsMap &map)
Inserts a barrier chain in a huge region, far below current SU.
void initSUnits ()
Creates an SUnit for each real instruction, numbered in top-down topological order.
void addPhysRegDataDeps (SUnit *SU, unsigned OperIdx)
MO is an operand of SU's instruction that defines a physical register.
void addPhysRegDeps (SUnit *SU, unsigned OperIdx)
Adds register dependencies (data, anti, and output) from this SUnit to following instructions in the same scheduling region that depend the physical register referenced at OperIdx.
void addVRegDefDeps (SUnit *SU, unsigned OperIdx)
Adds register output and data dependencies from this SUnit to instructions that occur later in the same scheduling region if they read from or write to the virtual register defined at OperIdx.
void addVRegUseDeps (SUnit *SU, unsigned OperIdx)
Adds a register data dependency if the instruction that defines the virtual register used at OperIdx is mapped to an SUnit.
void startBlockForKills (MachineBasicBlock *BB)
Initializes register live-range state for updating kills.
void toggleKillFlag (MachineInstr &MI, MachineOperand &MO)
Toggles a register operand kill flag.
LaneBitmask getLaneMaskForMO (const MachineOperand &MO) const
Returns a mask for which lanes get read/written by the given (register) machine operand.
bool deadDefHasNoUse (const MachineOperand &MO)
Returns true if the def register in MO has no uses.
Protected Member Functions inherited from llvm::ScheduleDAG
void dumpNodeAll (const SUnit &SU) const
Protected Attributes
SpecificBumpPtrAllocator< Region > Alloc
std::vector< Region * > Regions
MachineSchedContext * Context
const StrategyKind Strategy
GCNUpwardRPTracker UPTracker
Protected Attributes inherited from llvm::ScheduleDAGMILive
RegisterClassInfo * RegClassInfo
SchedDFSResult * DFSResult = nullptr
Information about DAG subtrees.
BitVector ScheduledTrees
MachineBasicBlock::iterator LiveRegionEnd
VReg2SUnitMultiMap VRegUses
Maps vregs to the SUnits of their uses in the current scheduling region.
PressureDiffs SUPressureDiffs
bool ShouldTrackPressure = false
Register pressure in this region computed by initRegPressure.
bool ShouldTrackLaneMasks = false
IntervalPressure RegPressure
RegPressureTracker RPTracker
std::vector< PressureChange > RegionCriticalPSets
List of pressure sets that exceed the target's pressure limit before scheduling, listed in increasing set ID order.
IntervalPressure TopPressure
The top of the unscheduled zone.
RegPressureTracker TopRPTracker
IntervalPressure BotPressure
The bottom of the unscheduled zone.
RegPressureTracker BotRPTracker
bool DisconnectedComponentsRenamed = false
True if disconnected subregister components are already renamed.
Protected Attributes inherited from llvm::ScheduleDAGMI
AliasAnalysis * AA
LiveIntervals * LIS
std::unique_ptr< MachineSchedStrategy > SchedImpl
std::vector< std::unique_ptr< ScheduleDAGMutation > > Mutations
Ordered list of DAG postprocessing steps.
MachineBasicBlock::iterator CurrentTop
The top of the unscheduled zone.
MachineBasicBlock::iterator CurrentBottom
The bottom of the unscheduled zone.
const SUnit * NextClusterPred = nullptr
Record the next node in a scheduled cluster.
const SUnit * NextClusterSucc = nullptr
unsigned NumInstrsScheduled = 0
The number of instructions scheduled so far.
Protected Attributes inherited from llvm::ScheduleDAGInstrs
const MachineLoopInfo * MLI
const MachineFrameInfo & MFI
TargetSchedModel SchedModel
TargetSchedModel provides an interface to the machine model.
bool RemoveKillFlags
True if the DAG builder should remove kill flags (in preparation for rescheduling).
bool CanHandleTerminators = false
The standard DAG builder does not normally include terminators as DAG nodes because it does not create the necessary dependencies to prevent reordering.
bool TrackLaneMasks = false
Whether lane masks should get tracked.
MachineBasicBlock * BB
The block in which to insert instructions.
MachineBasicBlock::iterator RegionBegin
The beginning of the range to be scheduled.
MachineBasicBlock::iterator RegionEnd
The end of the range to be scheduled.
unsigned NumRegionInstrs
Instructions in this region (distance(RegionBegin, RegionEnd)).
DenseMap< MachineInstr *, SUnit * > MISUnitMap
After calling BuildSchedGraph, each machine instruction in the current scheduling region is mapped to an SUnit.
Reg2SUnitsMap Defs
Defs, Uses - Remember where defs and uses of each register are as we iterate upward through the instructions.
Reg2SUnitsMap Uses
VReg2SUnitMultiMap CurrentVRegDefs
Tracks the last instruction(s) in this region defining each virtual register.
VReg2SUnitOperIdxMultiMap CurrentVRegUses
Tracks the last instructions in this region using each virtual register.
AAResults * AAForDep = nullptr
SUnit * BarrierChain = nullptr
Remember a generic side-effecting instruction as we proceed.
UndefValue * UnknownValue
For an unanalyzable memory access, this Value is used in maps.
ScheduleDAGTopologicalSort Topo
Topo - A topological ordering for SUnits which permits fast IsReachable and similar queries.
DbgValueVector DbgValues
Remember instruction that precedes DBG_VALUE.
MachineInstr * FirstDbgValue = nullptr
LivePhysRegs LiveRegs
Set of live physical registers for updating kill flags.
Additional Inherited Members
Public Attributes inherited from llvm::ScheduleDAG
const LLVMTargetMachine & TM
Target processor.
const TargetInstrInfo * TII
Target instruction information.
const TargetRegisterInfo * TRI
Target processor register info.
MachineFunction & MF
Machine function.
MachineRegisterInfo & MRI
Virtual/real register map.
std::vector< SUnit > SUnits
The scheduling units.
SUnit EntrySU
Special node for the region entry.
SUnit ExitSU
Special node for the region exit.
bool StressSched
Detailed Description
Definition at line 27 of file GCNIterativeScheduler.h.
Member Typedef Documentation
ScheduleRef
using llvm::GCNIterativeScheduler::ScheduleRef = ArrayRef<const SUnit *> protected
Definition at line 51 of file GCNIterativeScheduler.h.
Member Enumeration Documentation
StrategyKind
enum llvm::GCNIterativeScheduler::StrategyKind
Enumerator
SCHEDULE_MINREGONLY
SCHEDULE_MINREGFORCED
SCHEDULE_LEGACYMAXOCCUPANCY
SCHEDULE_ILP
Definition at line 31 of file GCNIterativeScheduler.h.
Constructor & Destructor Documentation
GCNIterativeScheduler()
GCNIterativeScheduler::GCNIterativeScheduler (MachineSchedContext * C, StrategyKind S)
Definition at line 238 of file GCNIterativeScheduler.cpp.
Member Function Documentation
detachSchedule()
std::vector< MachineInstr * > GCNIterativeScheduler::detachSchedule (ScheduleRef Schedule) const protected
Definition at line 337 of file GCNIterativeScheduler.cpp.
References D, llvm::ScheduleDAGInstrs::DbgValues, llvm::find_if(), llvm::ScheduleDAGInstrs::FirstDbgValue, P, and llvm::ArrayRef< T >::size().
Referenced by getRegionPressure(), and setBestSchedule().
enterRegion()
void GCNIterativeScheduler::enterRegion (MachineBasicBlock * bb, MachineBasicBlock::iterator begin, MachineBasicBlock::iterator end, unsigned regioninstrs) override virtual
Implement the ScheduleDAGInstrs interface for handling the next scheduling region.
enterRegion - Called back from MachineScheduler::runOnMachineFunction after crossing a scheduling boundary.
This covers all instructions in a block, while schedule() may only cover a subset.
[begin, end) includes all instructions in the region, including the boundary itself and single-instruction regions that don't get scheduled.
Reimplemented from llvm::ScheduleDAGMILive.
Definition at line 299 of file GCNIterativeScheduler.cpp.
References Alloc, llvm::ScheduleDAGMILive::enterRegion(), and Regions.
finalizeSchedule()
void GCNIterativeScheduler::finalizeSchedule () override virtual
Allow targets to perform final scheduling actions at the level of the whole MachineFunction.
By default does nothing.
Reimplemented from llvm::ScheduleDAGInstrs.
Definition at line 323 of file GCNIterativeScheduler.cpp.
References Regions, SCHEDULE_ILP, SCHEDULE_LEGACYMAXOCCUPANCY, SCHEDULE_MINREGFORCED, SCHEDULE_MINREGONLY, scheduleILP(), scheduleLegacyMaxOccupancy(), scheduleMinReg(), and Strategy.
getRegionPressure() [1/2]
GCNRegPressure GCNIterativeScheduler::getRegionPressure (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End) const protected
Definition at line 248 of file GCNIterativeScheduler.cpp.
Referenced by getRegionPressure(), scheduleLegacyMaxOccupancy(), and scheduleRegion().
getRegionPressure() [2/2]
GCNRegPressure llvm::GCNIterativeScheduler::getRegionPressure (const Region & R) const inline protected
Definition at line 88 of file GCNIterativeScheduler.h.
References llvm::GCNIterativeScheduler::Region::Begin, detachSchedule(), llvm::GCNIterativeScheduler::Region::End, getRegionPressure(), llvm::max(), printRegions(), printSchedResult(), printSchedRP(), llvm::RISCVFenceField::R, llvm::NVPTX::PTXCvtMode::RP, llvm::GCNIterativeScheduler::TentativeSchedule::Schedule, scheduleBest(), scheduleILP(), scheduleLegacyMaxOccupancy(), scheduleMinReg(), scheduleRegion(), setBestSchedule(), sortRegionsByPressure(), and tryMaximizeOccupancy().
getSchedulePressure()
template<typename Range > GCNRegPressure GCNIterativeScheduler::getSchedulePressure (const Region & R, Range && Schedule) const protected
Definition at line 280 of file GCNIterativeScheduler.cpp.
References B, llvm::GCNIterativeScheduler::Region::Begin, llvm::GCNIterativeScheduler::Region::End, getMachineInstr(), I, llvm::GCNRPTracker::moveMaxPressure(), llvm::GCNUpwardRPTracker::recede(), llvm::GCNUpwardRPTracker::reset(), and llvm::ScheduleDAGMILive::RPTracker.
Referenced by scheduleILP(), scheduleMinReg(), scheduleRegion(), and tryMaximizeOccupancy().
printRegions()
LLVM_DUMP_METHOD void GCNIterativeScheduler::printRegions (raw_ostream & OS) const protected
Definition at line 109 of file GCNIterativeScheduler.cpp.
References llvm::MachineFunction::getSubtarget(), LLVM_DUMP_METHOD, llvm::ScheduleDAG::MF, printLivenessInfo(), printRegion(), Regions, and llvm::ARM_MB::ST.
Referenced by getRegionPressure().
printSchedResult()
LLVM_DUMP_METHOD void GCNIterativeScheduler::printSchedResult (raw_ostream & OS, const Region * R, const GCNRegPressure & RP) const protected
Definition at line 121 of file GCNIterativeScheduler.cpp.
References llvm::GCNIterativeScheduler::Region::Begin, llvm::GCNIterativeScheduler::Region::End, LLVM_DUMP_METHOD, llvm::GCNIterativeScheduler::Region::MaxPressure, printRegion(), and printSchedRP().
Referenced by getRegionPressure(), scheduleILP(), and scheduleMinReg().
printSchedRP()
LLVM_DUMP_METHOD void GCNIterativeScheduler::printSchedRP (raw_ostream & OS, const GCNRegPressure & Before, const GCNRegPressure & After) const protected
Definition at line 131 of file GCNIterativeScheduler.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::ScheduleDAG::MF, llvm::GCNRegPressure::print(), and llvm::ARM_MB::ST.
Referenced by getRegionPressure(), printSchedResult(), scheduleILP(), scheduleLegacyMaxOccupancy(), scheduleMinReg(), and tryMaximizeOccupancy().
schedule()
void GCNIterativeScheduler::schedule () override virtual
Implement ScheduleDAGInstrs interface for scheduling a sequence of reorderable instructions.
schedule - Called back from MachineScheduler::runOnMachineFunction after setting up the current scheduling region.
[RegionBegin, RegionEnd) only includes instructions that have DAG nodes, not scheduling boundaries.
This is a skeletal driver, with all the functionality pushed into helpers, so that it can be easily extended by experimental schedulers. Generally, implementing MachineSchedStrategy should be sufficient to implement a new scheduling algorithm. However, if a scheduler further subclasses ScheduleDAGMILive then it will want to override this virtual method in order to update any specialized state.
Reimplemented from llvm::ScheduleDAGMILive.
Definition at line 312 of file GCNIterativeScheduler.cpp.
References llvm::dbgs(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, llvm::ScheduleDAG::MF, printLivenessInfo(), llvm::ScheduleDAGInstrs::RegionBegin, llvm::ScheduleDAGInstrs::RegionEnd, and Regions.
scheduleBest()
void GCNIterativeScheduler::scheduleBest (Region & R) protected
Definition at line 363 of file GCNIterativeScheduler.cpp.
References assert(), llvm::GCNIterativeScheduler::Region::BestSchedule, and scheduleRegion().
Referenced by getRegionPressure(), scheduleILP(), and scheduleLegacyMaxOccupancy().
scheduleILP()
void GCNIterativeScheduler::scheduleILP (bool TryMaximizeOccupancy = true) protected
Definition at line 575 of file GCNIterativeScheduler.cpp.
References llvm::dbgs(), llvm::GCNIterativeScheduler::BuildDAG::getBottomRoots(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getMinAllowedOccupancy(), getSchedulePressure(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, llvm::makeGCNILPScheduler(), llvm::ScheduleDAG::MF, llvm::ScheduleDAGInstrs::MFI, printSchedResult(), printSchedRP(), Regions, llvm::NVPTX::PTXCvtMode::RP, scheduleBest(), scheduleRegion(), sortRegionsByPressure(), llvm::ARM_MB::ST, and tryMaximizeOccupancy().
Referenced by finalizeSchedule(), and getRegionPressure().
scheduleLegacyMaxOccupancy()
void GCNIterativeScheduler::scheduleLegacyMaxOccupancy (bool TryMaximizeOccupancy = true) protected
Definition at line 487 of file GCNIterativeScheduler.cpp.
References assert(), Context, llvm::dbgs(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getMinAllowedOccupancy(), getRegionPressure(), llvm::MachineFunction::getSubtarget(), I, LLVM_DEBUG, llvm::ScheduleDAG::MF, llvm::ScheduleDAGInstrs::MFI, printSchedRP(), Regions, llvm::GCNIterativeScheduler::OverrideLegacyStrategy::restoreOrder(), llvm::NVPTX::PTXCvtMode::RP, llvm::GCNIterativeScheduler::OverrideLegacyStrategy::schedule(), scheduleBest(), llvm::GCNMaxOccupancySchedStrategy::setTargetOccupancy(), sortRegionsByPressure(), llvm::ARM_MB::ST, and tryMaximizeOccupancy().
Referenced by finalizeSchedule(), and getRegionPressure().
scheduleMinReg()
void GCNIterativeScheduler::scheduleMinReg (bool force = false) protected
Definition at line 542 of file GCNIterativeScheduler.cpp.
References llvm::dbgs(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getOccupancy(), getSchedulePressure(), llvm::MachineFunction::getSubtarget(), llvm::GCNIterativeScheduler::BuildDAG::getTopRoots(), LLVM_DEBUG, llvm::makeMinRegSchedule(), llvm::ScheduleDAG::MF, llvm::ScheduleDAGInstrs::MFI, printSchedResult(), printSchedRP(), Regions, llvm::NVPTX::PTXCvtMode::RP, scheduleRegion(), sortRegionsByPressure(), and llvm::ARM_MB::ST.
Referenced by finalizeSchedule(), and getRegionPressure().
scheduleRegion()
template<typename Range > void GCNIterativeScheduler::scheduleRegion (Region & R, Range && Schedule, const GCNRegPressure & MaxRP = GCNRegPressure()) protected
Definition at line 372 of file GCNIterativeScheduler.cpp.
References llvm::RegisterOperands::adjustLaneLiveness(), assert(), llvm::ScheduleDAGInstrs::BB, llvm::GCNIterativeScheduler::Region::Begin, llvm::RegisterOperands::collect(), llvm::dbgs(), llvm::GCNRegPressure::empty(), llvm::GCNIterativeScheduler::Region::End, llvm::LiveIntervals::getInstructionIndex(), getMachineInstr(), getRegionPressure(), llvm::SlotIndex::getRegSlot(), getSchedulePressure(), llvm::MachineFunction::getSubtarget(), llvm::LiveIntervals::handleMove(), I, llvm::MachineBasicBlock::insert(), llvm::GCNIterativeScheduler::Region::MaxPressure, llvm::ScheduleDAG::MF, MI, llvm::ScheduleDAG::MRI, llvm::ScheduleDAGMI::placeDebugValues(), llvm::GCNRegPressure::print(), llvm::ScheduleDAGInstrs::RegionBegin, llvm::ScheduleDAGInstrs::RegionEnd, llvm::MachineBasicBlock::remove(), llvm::ARM_MB::ST, and llvm::ScheduleDAG::TRI.
Referenced by getRegionPressure(), llvm::GCNIterativeScheduler::OverrideLegacyStrategy::restoreOrder(), scheduleBest(), scheduleILP(), and scheduleMinReg().
setBestSchedule()
void GCNIterativeScheduler::setBestSchedule (Region & R, ScheduleRef Schedule, const GCNRegPressure & MaxRP = GCNRegPressure()) protected
Definition at line 356 of file GCNIterativeScheduler.cpp.
References llvm::GCNIterativeScheduler::Region::BestSchedule, and detachSchedule().
Referenced by getRegionPressure(), and tryMaximizeOccupancy().
sortRegionsByPressure()
void GCNIterativeScheduler::sortRegionsByPressure (unsigned TargetOcc) protected
Definition at line 434 of file GCNIterativeScheduler.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::GCNRegPressure::less(), llvm::GCNIterativeScheduler::Region::MaxPressure, llvm::ScheduleDAG::MF, R2, Regions, llvm::sort(), and llvm::ARM_MB::ST.
Referenced by getRegionPressure(), scheduleILP(), scheduleLegacyMaxOccupancy(), and scheduleMinReg().
tryMaximizeOccupancy()
unsigned GCNIterativeScheduler::tryMaximizeOccupancy (unsigned TargetOcc = std::numeric_limits<unsigned>::max()) protected
Definition at line 450 of file GCNIterativeScheduler.cpp.
References llvm::dbgs(), llvm::MachineFunction::getInfo(), getSchedulePressure(), llvm::MachineFunction::getSubtarget(), llvm::GCNIterativeScheduler::BuildDAG::getTopRoots(), llvm::SIMachineFunctionInfo::increaseOccupancy(), LLVM_DEBUG, llvm::makeMinRegSchedule(), llvm::max(), llvm::ScheduleDAG::MF, llvm::ScheduleDAGInstrs::MFI, printLivenessInfo(), printRegion(), printSchedRP(), Regions, setBestSchedule(), and llvm::ARM_MB::ST.
Referenced by getRegionPressure(), scheduleILP(), and scheduleLegacyMaxOccupancy().
Member Data Documentation
Alloc
SpecificBumpPtrAllocator<Region> llvm::GCNIterativeScheduler::Alloc protected
Definition at line 71 of file GCNIterativeScheduler.h.
Referenced by enterRegion().
Context
MachineSchedContext* llvm::GCNIterativeScheduler::Context protected
Definition at line 74 of file GCNIterativeScheduler.h.
Referenced by scheduleLegacyMaxOccupancy().
Regions
std::vector<Region*> llvm::GCNIterativeScheduler::Regions protected
Definition at line 72 of file GCNIterativeScheduler.h.
Referenced by enterRegion(), finalizeSchedule(), printRegions(), schedule(), scheduleILP(), scheduleLegacyMaxOccupancy(), scheduleMinReg(), sortRegionsByPressure(), and tryMaximizeOccupancy().
Strategy
const StrategyKind llvm::GCNIterativeScheduler::Strategy protected
Definition at line 75 of file GCNIterativeScheduler.h.
Referenced by finalizeSchedule().
UPTracker
GCNUpwardRPTracker llvm::GCNIterativeScheduler::UPTracker mutable protected
Definition at line 76 of file GCNIterativeScheduler.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNIterativeScheduler.h
lib/Target/AMDGPU/GCNIterativeScheduler.cpp