LLVM: llvm::msgpack::MapDocNode Class Reference
llvm::msgpack::MapDocNode Class Reference
A DocNode that is a map.
#include "llvm/BinaryFormat/MsgPackDocument.h"
Public Member Functions
MapDocNode ()
MapDocNode (DocNode &N)
size_t size () const
bool empty () const
MapTy::iterator begin ()
MapTy::iterator end ()
MapTy::iterator find (DocNode Key)
MapTy::iterator find (StringRef Key)
Find the key in the MapDocNode.
DocNode & operator[] (StringRef S)
Member access.
DocNode & operator[] (DocNode Key)
Member access.
Public Member Functions inherited from llvm::msgpack::DocNode
DocNode ()
bool isMap () const
bool isArray () const
bool isScalar () const
bool isString () const
bool isEmpty () const
Type getKind () const
Document * getDocument () const
int64_t & getInt ()
uint64_t & getUInt ()
bool & getBool ()
double & getFloat ()
int64_t getInt () const
uint64_t getUInt () const
bool getBool () const
double getFloat () const
StringRef getString () const
ArrayDocNode & getArray (bool Convert=false)
Get an ArrayDocNode for an array node.
MapDocNode & getMap (bool Convert=false)
Get a MapDocNode for a map node.
std::string toString () const
Convert this node to a string, assuming it is scalar.
StringRef fromString (StringRef S, StringRef Tag="")
Convert the StringRef and use it to set this DocNode (assuming scalar).
Additional Inherited Members
Public Types inherited from llvm::msgpack::DocNode
typedef std::map< DocNode, DocNode > MapTy
typedef std::vector< DocNode > ArrayTy
Protected Attributes inherited from llvm::msgpack::DocNode
union {
int64_t Int
uint64_t UInt
bool Bool
double Float
StringRef Raw
ArrayTy * Array
MapTy * Map
};
Detailed Description
A DocNode that is a map.
Definition at line 197 of file MsgPackDocument.h.
Constructor & Destructor Documentation
MapDocNode() [1/2]
llvm::msgpack::MapDocNode::MapDocNode () inline
Definition at line 199 of file MsgPackDocument.h.
MapDocNode() [2/2]
llvm::msgpack::MapDocNode::MapDocNode (DocNode & N) inline
Definition at line 200 of file MsgPackDocument.h.
References assert(), and llvm::msgpack::Map.
Member Function Documentation
begin()
MapTy::iterator llvm::msgpack::MapDocNode::begin () inline
Definition at line 205 of file MsgPackDocument.h.
References llvm::msgpack::Map.
empty()
bool llvm::msgpack::MapDocNode::empty () const inline
Definition at line 204 of file MsgPackDocument.h.
References llvm::size().
end()
MapTy::iterator llvm::msgpack::MapDocNode::end () inline
Definition at line 206 of file MsgPackDocument.h.
References llvm::msgpack::Map.
find() [1/2]
MapTy::iterator llvm::msgpack::MapDocNode::find (DocNode Key) inline
Definition at line 207 of file MsgPackDocument.h.
References llvm::find(), and llvm::msgpack::Map.
find() [2/2]
DocNode::MapTy::iterator MapDocNode::find (StringRef Key)
Find the key in the MapDocNode.
Definition at line 30 of file MsgPackDocument.cpp.
References llvm::find(), and llvm::msgpack::DocNode::getDocument().
operator[]() [1/2]
DocNode & MapDocNode::operator[] (StringRef S)
Member access.
Member access for MapDocNode.
The string data must remain valid for the lifetime of the Document.
Definition at line 36 of file MsgPackDocument.cpp.
References llvm::msgpack::DocNode::getDocument(), and llvm::msgpack::Document::getNode().
operator[]() [2/2]
DocNode & MapDocNode::operator[] (DocNode Key)
Member access.
Member access for MapDocNode.
Definition at line 41 of file MsgPackDocument.cpp.
References assert(), and llvm::msgpack::DocNode::isEmpty().
size()
size_t llvm::msgpack::MapDocNode::size () const inline
Definition at line 203 of file MsgPackDocument.h.
References llvm::msgpack::Map.
The documentation for this class was generated from the following files:
include/llvm/BinaryFormat/MsgPackDocument.h
lib/BinaryFormat/MsgPackDocument.cpp