LLVM: llvm::SchedDFSResult Class Reference
llvm::SchedDFSResult Class Reference
Compute the values of each DAG node for various metrics during DFS.
#include "llvm/CodeGen/ScheduleDFS.h"
Public Member Functions
SchedDFSResult (bool IsBU, unsigned lim)
unsigned getSubtreeLimit () const
Get the node cutoff before subtrees are considered significant.
bool empty () const
Return true if this DFSResult is uninitialized.
void clear ()
Clear the results.
void resize (unsigned NumSUnits)
Initialize the result data with the size of the DAG.
void compute (ArrayRef< SUnit > SUnits)
Compute various metrics for the DAG with given roots.
unsigned getNumInstrs (const SUnit *SU) const
Get the number of instructions in the given subtree and its children.
unsigned getNumSubInstrs (unsigned SubtreeID) const
Get the number of instructions in the given subtree not including children.
ILPValue getILP (const SUnit *SU) const
Get the ILP value for a DAG node.
unsigned getNumSubtrees () const
The number of subtrees detected in this DAG.
unsigned getSubtreeID (const SUnit *SU) const
Get the ID of the subtree the given DAG node belongs to.
unsigned getSubtreeLevel (unsigned SubtreeID) const
Get the connection level of a subtree.
void scheduleTree (unsigned SubtreeID)
Scheduler callback to update SubtreeConnectLevels when a tree is initially scheduled.
Friends
class SchedDFSImpl
Detailed Description
Compute the values of each DAG node for various metrics during DFS.
Definition at line 65 of file ScheduleDFS.h.
Constructor & Destructor Documentation
SchedDFSResult()
llvm::SchedDFSResult::SchedDFSResult (bool IsBU, unsigned lim) inline
Definition at line 116 of file ScheduleDFS.h.
Member Function Documentation
clear()
void llvm::SchedDFSResult::clear () inline
Clear the results.
Definition at line 128 of file ScheduleDFS.h.
References llvm::SmallVectorImpl< T >::clear().
compute()
void SchedDFSResult::compute (ArrayRef< SUnit > SUnits)
Compute various metrics for the DAG with given roots.
Computes an ILP metric for all nodes in the subDAG reachable via depth-first search from this root.
Definition at line 1447 of file ScheduleDAGInstrs.cpp.
References llvm::SDep::Data, DFS(), llvm::SchedDFSImpl::finalize(), llvm::SDep::getKind(), llvm::SDep::getSUnit(), hasDataSucc(), llvm::SUnit::isBoundaryNode(), llvm::SchedDFSImpl::isVisited(), llvm_unreachable, llvm::SchedDFSImpl::visitCrossEdge(), llvm::SchedDFSImpl::visitPostorderEdge(), llvm::SchedDFSImpl::visitPostorderNode(), and llvm::SchedDFSImpl::visitPreorder().
empty()
bool llvm::SchedDFSResult::empty () const inline
Return true if this DFSResult is uninitialized.
resize() initializes DFSResult, while compute() populates it.
Definition at line 125 of file ScheduleDFS.h.
getILP()
ILPValue llvm::SchedDFSResult::getILP (const SUnit * SU) const inline
Get the ILP value for a DAG node.
A leaf node has an ILP of 1/1.
Definition at line 158 of file ScheduleDFS.h.
References llvm::SUnit::getDepth(), llvm::ILPValue::ILPValue(), and llvm::SUnit::NodeNum.
Referenced by llvm::createGenericSchedPostRA().
getNumInstrs()
unsigned llvm::SchedDFSResult::getNumInstrs (const SUnit * SU) const inline
Get the number of instructions in the given subtree and its children.
Definition at line 145 of file ScheduleDFS.h.
References llvm::SUnit::NodeNum.
Referenced by llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeLabel().
getNumSubInstrs()
unsigned llvm::SchedDFSResult::getNumSubInstrs (unsigned SubtreeID) const inline
Get the number of instructions in the given subtree not including children.
Definition at line 151 of file ScheduleDFS.h.
getNumSubtrees()
unsigned llvm::SchedDFSResult::getNumSubtrees () const inline
The number of subtrees detected in this DAG.
Definition at line 163 of file ScheduleDFS.h.
Referenced by llvm::SchedDFSImpl::finalize().
getSubtreeID()
unsigned llvm::SchedDFSResult::getSubtreeID (const SUnit * SU) const inline
Get the ID of the subtree the given DAG node belongs to.
For convenience, if DFSResults have not been computed yet, give everything tree ID 0.
Definition at line 169 of file ScheduleDFS.h.
References assert(), llvm::empty(), and llvm::SUnit::NodeNum.
Referenced by llvm::createGenericSchedPostRA(), and llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeAttributes().
getSubtreeLevel()
unsigned llvm::SchedDFSResult::getSubtreeLevel (unsigned SubtreeID) const inline
Get the connection level of a subtree.
For bottom-up trees, the connection level is the latency depth (in cycles) of the deepest connection to another subtree.
Definition at line 180 of file ScheduleDFS.h.
References llvm::operator<<().
Referenced by llvm::createGenericSchedPostRA().
getSubtreeLimit()
unsigned llvm::SchedDFSResult::getSubtreeLimit () const inline
Get the node cutoff before subtrees are considered significant.
Definition at line 120 of file ScheduleDFS.h.
resize()
void llvm::SchedDFSResult::resize (unsigned NumSUnits) inline
Initialize the result data with the size of the DAG.
Definition at line 136 of file ScheduleDFS.h.
scheduleTree()
void SchedDFSResult::scheduleTree (unsigned SubtreeID)
Scheduler callback to update SubtreeConnectLevels when a tree is initially scheduled.
The root of the given SubtreeID was just scheduled.
For all subtrees connected to this tree, record the depth of the connection so that the nearest connected subtrees can be prioritized.
Definition at line 1493 of file ScheduleDAGInstrs.cpp.
References C, llvm::dbgs(), LLVM_DEBUG, and llvm::max().
Friends And Related Function Documentation
SchedDFSImpl
friend class SchedDFSImpl friend
Definition at line 66 of file ScheduleDFS.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ScheduleDFS.h
lib/CodeGen/ScheduleDAGInstrs.cpp