LLVM: llvm::MipsCallLowering::MipsHandler Class Reference
llvm::MipsCallLowering::MipsHandler Class Reference abstract
#include "Target/Mips/MipsCallLowering.h"
Public Member Functions
MipsHandler (MachineIRBuilder &MIRBuilder, MachineRegisterInfo &MRI)
virtual ~MipsHandler ()=default
bool handle (ArrayRef< CCValAssign > ArgLocs, ArrayRef< CallLowering::ArgInfo > Args)
Protected Member Functions
bool assignVRegs (ArrayRef< Register > VRegs, ArrayRef< CCValAssign > ArgLocs, unsigned ArgLocsStartIndex, const EVT &VT)
void setLeastSignificantFirst (SmallVectorImpl< Register > &VRegs)
Protected Attributes
MachineIRBuilder & MIRBuilder
MachineRegisterInfo & MRI
Detailed Description
Definition at line 26 of file MipsCallLowering.h.
Constructor & Destructor Documentation
MipsHandler()
llvm::MipsCallLowering::MipsHandler::MipsHandler (MachineIRBuilder & MIRBuilder, MachineRegisterInfo & MRI) inline
Definition at line 28 of file MipsCallLowering.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assignVRegs(), handle(), setLeastSignificantFirst(), and ~MipsHandler().
~MipsHandler()
virtual llvm::MipsCallLowering::MipsHandler::~MipsHandler () virtual default
Referenced by MipsHandler().
Member Function Documentation
assignVRegs()
bool MipsCallLowering::MipsHandler::assignVRegs (ArrayRef< Register > VRegs, ArrayRef< CCValAssign > ArgLocs, unsigned ArgLocsStartIndex, const EVT & VT) protected
Definition at line 39 of file MipsCallLowering.cpp.
References llvm::ArrayRef< T >::size().
Referenced by MipsHandler().
handle()
bool MipsCallLowering::MipsHandler::handle (ArrayRef< CCValAssign > ArgLocs, ArrayRef< CallLowering::ArgInfo > Args)
Definition at line 55 of file MipsCallLowering.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineRegisterInfo::addLiveIn(), llvm::CCValAssign::AExt, llvm::alignTo(), assert(), llvm::MachineIRBuilder::buildLoad(), llvm::MipsISD::BuildPairF64, llvm::SmallVectorImpl< T >::clear(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MipsISD::ExtractElementF64, F(), llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::Full, llvm::Function::getCallingConv(), llvm::Function::getContext(), llvm::Module::getDataLayout(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMBB(), llvm::MachineIRBuilder::getMRI(), llvm::MipsTargetLowering::getNumRegistersForCallingConv(), llvm::GlobalValue::getParent(), llvm::MipsSubtarget::getRegBankInfo(), llvm::MipsSubtarget::getRegisterInfo(), llvm::MipsTargetLowering::getRegisterTypeForCallingConv(), llvm::MVT::getSizeInBits(), llvm::MachinePointerInfo::getStack(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getSubtarget(), llvm::TargetLoweringBase::getValueType(), llvm::CCValAssign::getValVT(), llvm::RegState::Implicit, llvm::MipsSubtarget::isFP64bit(), llvm::MipsSubtarget::isLittle(), llvm_unreachable, llvm::MinAlign(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, MRI, llvm::LLT::pointer(), llvm::SmallVectorTemplateBase< T >::push_back(), Register, llvm::LLT::scalar(), llvm::CCValAssign::SExt, Size, llvm::ArrayRef< T >::size(), and llvm::CCValAssign::ZExt.
Referenced by MipsHandler().
setLeastSignificantFirst()
void MipsCallLowering::MipsHandler::setLeastSignificantFirst (SmallVectorImpl< Register > & VRegs) protected
Definition at line 49 of file MipsCallLowering.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), and llvm::reverse().
Referenced by MipsHandler().
Member Data Documentation
MIRBuilder
MachineIRBuilder& llvm::MipsCallLowering::MipsHandler::MIRBuilder protected
Definition at line 42 of file MipsCallLowering.h.
MRI
MachineRegisterInfo& llvm::MipsCallLowering::MipsHandler::MRI protected
Definition at line 43 of file MipsCallLowering.h.
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsCallLowering.h
lib/Target/Mips/MipsCallLowering.cpp