LLVM: llvm::TrigramIndex Class Reference
llvm::TrigramIndex Class Reference
#include "llvm/Support/TrigramIndex.h"
Public Member Functions
void insert (std::string Regex)
Inserts a new Regex into the index.
bool isDefinitelyOut (StringRef Query) const
Returns true, if special case list definitely does not have a line that matches the query.
bool isDefeated ()
Returned true, iff the heuristic is defeated and not useful.
Detailed Description
Definition at line 39 of file TrigramIndex.h.
Member Function Documentation
insert()
void TrigramIndex::insert (std::string Regex)
Inserts a new Regex into the index.
Definition at line 32 of file TrigramIndex.cpp.
References isAdvancedMetachar(), and llvm::size().
Referenced by llvm::SpecialCaseList::Matcher::insert().
isDefeated()
bool llvm::TrigramIndex::isDefeated () inline
Returned true, iff the heuristic is defeated and not useful.
In this case isDefinitelyOut always returns false.
Definition at line 50 of file TrigramIndex.h.
isDefinitelyOut()
bool TrigramIndex::isDefinitelyOut (StringRef Query) const
Returns true, if special case list definitely does not have a line that matches the query.
Returns false, if it's not sure.
Definition at line 89 of file TrigramIndex.cpp.
References I, and llvm::StringRef::size().
Referenced by llvm::SpecialCaseList::Matcher::match().
The documentation for this class was generated from the following files:
include/llvm/Support/TrigramIndex.h
lib/Support/TrigramIndex.cpp