LLVM: llvm::DWARFExpression::iterator Class Reference
llvm::DWARFExpression::iterator Class Reference
An iterator to go through the expression operations.
#include "llvm/DebugInfo/DWARF/DWARFExpression.h"
Public Member Functions
class Operation & operator++ ()
class Operation & operator* ()
Public Member Functions inherited from llvm::iterator_facade_base< iterator, std::forward_iterator_tag, Operation >
iterator operator+ (std::ptrdiff_t n) const
iterator operator- (std::ptrdiff_t n) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
bool operator!= (const iterator &RHS) const
bool operator> (const iterator &RHS) const
bool operator<= (const iterator &RHS) const
bool operator>= (const iterator &RHS) const
Operation * operator-> ()
Operation * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Friends
class DWARFExpression
bool operator== (const iterator &, const iterator &)
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< iterator, std::forward_iterator_tag, Operation >
enum
Detailed Description
An iterator to go through the expression operations.
Definition at line 99 of file DWARFExpression.h.
Member Function Documentation
operator*()
class Operation& llvm::DWARFExpression::iterator::operator* () inline
Definition at line 122 of file DWARFExpression.h.
References llvm::DWARFExpression::Operation::Description::Op, and llvm::operator==().
operator++()
class Operation& llvm::DWARFExpression::iterator::operator++ () inline
Definition at line 114 of file DWARFExpression.h.
References llvm::DWARFExpression::Operation::extract(), llvm::DataExtractor::getData(), llvm::DWARFExpression::Operation::isError(), llvm::DWARFExpression::Operation::Description::Op, and llvm::StringRef::size().
Friends And Related Function Documentation
DWARFExpression
friend class DWARFExpression friend
Definition at line 102 of file DWARFExpression.h.
operator==
bool operator== (const iterator & LHS, const iterator & RHS) friend
Definition at line 149 of file DWARFExpression.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFExpression.h