LLVM: llvm::po_iterator_storage< LoopBounds, true > Class Template Reference
llvm::po_iterator_storage< LoopBounds, true > Class Template Reference
Public Member Functions
po_iterator_storage (LoopBounds &lb)
void finishPostorder (const MachineBasicBlock *)
bool insertEdge (Optional< const MachineBasicBlock *> From, const MachineBasicBlock *To)
Detailed Description
template<>
class llvm::po_iterator_storage< LoopBounds, true >
Definition at line 444 of file MachineTraceMetrics.cpp.
Constructor & Destructor Documentation
po_iterator_storage()
llvm::po_iterator_storage< LoopBounds, true >::po_iterator_storage (LoopBounds & lb) inline
Definition at line 448 of file MachineTraceMetrics.cpp.
Member Function Documentation
finishPostorder()
void llvm::po_iterator_storage< LoopBounds, true >::finishPostorder (const MachineBasicBlock *) inline
Definition at line 450 of file MachineTraceMetrics.cpp.
insertEdge()
bool llvm::po_iterator_storage< LoopBounds, true >::insertEdge (Optional< const MachineBasicBlock *> From, const MachineBasicBlock * To) inline
Definition at line 452 of file MachineTraceMetrics.cpp.
References llvm::dbgs(), llvm::MachineTraceMetrics::Ensemble::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineTraceMetrics::TraceBlockInfo::hasValidDepth(), llvm::MachineTraceMetrics::TraceBlockInfo::hasValidHeight(), I, llvm::inverse_post_order_ext(), isExitingLoop(), LLVM_DEBUG, llvm::MachineTraceMetrics::Ensemble::MTM, llvm::MachineTraceMetrics::Ensemble::pickTracePred(), llvm::MachineTraceMetrics::Ensemble::pickTraceSucc(), llvm::post_order_ext(), and llvm::printMBBReference().
The documentation for this class was generated from the following file:
lib/CodeGen/MachineTraceMetrics.cpp