LLVM: llvm::IVVisitor Class Reference
llvm::IVVisitor Class Reference abstract
Interface for visiting interesting IV users that are recognized but not simplified by this utility.
#include "llvm/Transforms/Utils/SimplifyIndVar.h"
Public Member Functions
IVVisitor ()=default
virtual ~IVVisitor ()=default
const DominatorTree * getDomTree () const
virtual void visitCast (CastInst *Cast)=0
Protected Member Functions
virtual void anchor ()
Protected Attributes
const DominatorTree * DT = nullptr
Detailed Description
Interface for visiting interesting IV users that are recognized but not simplified by this utility.
Definition at line 32 of file SimplifyIndVar.h.
Constructor & Destructor Documentation
IVVisitor()
llvm::IVVisitor::IVVisitor () default
~IVVisitor()
virtual llvm::IVVisitor::~IVVisitor () virtual default
Member Function Documentation
anchor()
void llvm::IVVisitor::anchor () protected virtual
Definition at line 929 of file SimplifyIndVar.cpp.
getDomTree()
const DominatorTree* llvm::IVVisitor::getDomTree () const inline
Definition at line 42 of file SimplifyIndVar.h.
References llvm::RegState::Dead, DT, Rewriter, llvm::simplifyLoopIVs(), llvm::simplifyUsersOfIV(), and visitCast().
visitCast()
virtual void llvm::IVVisitor::visitCast (CastInst * Cast) pure virtual
Referenced by getDomTree(), and isSimpleIVUser().
Member Data Documentation
DT
const DominatorTree* llvm::IVVisitor::DT = nullptr protected
Definition at line 34 of file SimplifyIndVar.h.
Referenced by getDomTree().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/SimplifyIndVar.h
lib/Transforms/Utils/SimplifyIndVar.cpp