LLVM: llvm::InstrProfiling Class Reference
llvm::InstrProfiling Class Reference
Instrumentation based profiling lowering pass.
#include "llvm/Transforms/Instrumentation/InstrProfiling.h"
Public Member Functions
InstrProfiling ()
InstrProfiling (const InstrProfOptions &Options, bool IsCS=false)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
bool run (Module &M, std::function< const TargetLibraryInfo &(Function &F)> GetTLI)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InstrProfiling >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Instrumentation based profiling lowering pass.
This pass lowers the profile instrumented code generated by FE or the IR based instrumentation pass.
Definition at line 35 of file InstrProfiling.h.
Constructor & Destructor Documentation
InstrProfiling() [1/2]
llvm::InstrProfiling::InstrProfiling () inline
Definition at line 37 of file InstrProfiling.h.
InstrProfiling() [2/2]
llvm::InstrProfiling::InstrProfiling (const InstrProfOptions & Options, bool IsCS = false) inline
Definition at line 38 of file InstrProfiling.h.
References F(), function, llvm::MipsISD::Ins, and run().
Member Function Documentation
run() [1/2]
PreservedAnalyses InstrProfiling::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 376 of file InstrProfiling.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, INITIALIZE_PASS_END(), and llvm::PreservedAnalyses::none().
Referenced by InstrProfiling().
run() [2/2]
bool InstrProfiling::run (Module & M, std::function< const TargetLibraryInfo &(Function &F)> GetTLI)
Definition at line 493 of file InstrProfiling.cpp.
References containsProfilingIntrinsics(), llvm::dyn_cast(), E, llvm::getCoverageUnusedNamesVarName(), llvm::getMemOPSizeRangeFromOption(), llvm::Module::getNamedGlobal(), llvm::Module::getTargetTriple(), I, lowerIntrinsics(), MemOPSizeRange, and llvm::TT.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/InstrProfiling.h
lib/Transforms/Instrumentation/InstrProfiling.cpp