LLVM: llvm::LoopCachePrinterPass Class Reference
llvm::LoopCachePrinterPass Class Reference
Printer pass for the CacheCost results.
#include "llvm/Analysis/LoopCacheAnalysis.h"
Public Member Functions
LoopCachePrinterPass (raw_ostream &OS)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopCachePrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the CacheCost results.
Definition at line 269 of file LoopCacheAnalysis.h.
Constructor & Destructor Documentation
LoopCachePrinterPass()
llvm::LoopCachePrinterPass::LoopCachePrinterPass (raw_ostream & OS) inline explicit
Definition at line 273 of file LoopCacheAnalysis.h.
Member Function Documentation
run()
PreservedAnalyses LoopCachePrinterPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 619 of file LoopCacheAnalysis.cpp.
References llvm::LoopStandardAnalysisResults::AA, llvm::PreservedAnalyses::all(), F(), llvm::CacheCost::getCacheCost(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), llvm::LoopStandardAnalysisResults::LI, and llvm::LoopStandardAnalysisResults::SE.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopCacheAnalysis.h
lib/Analysis/LoopCacheAnalysis.cpp