LLVM: llvm::MachineModuleInfoCOFF Class Reference
llvm::MachineModuleInfoCOFF Class Reference
MachineModuleInfoCOFF - This is a MachineModuleInfoImpl implementation for COFF targets.
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
Public Member Functions
MachineModuleInfoCOFF (const MachineModuleInfo &)
StubValueTy & getGVStubEntry (MCSymbol *Sym)
SymbolListTy GetGVStubList ()
Accessor methods to return the set of stubs in sorted order.
Public Member Functions inherited from llvm::MachineModuleInfoImpl
virtual ~MachineModuleInfoImpl ()
Additional Inherited Members
Public Types inherited from llvm::MachineModuleInfoImpl
using StubValueTy = PointerIntPair< MCSymbol *, 1, bool >
using SymbolListTy = std::vector< std::pair< MCSymbol *, StubValueTy > >
Static Protected Member Functions inherited from llvm::MachineModuleInfoImpl
static SymbolListTy getSortedStubs (DenseMap< MCSymbol *, StubValueTy > &)
Return the entries from a DenseMap in a deterministic sorted orer.
Detailed Description
MachineModuleInfoCOFF - This is a MachineModuleInfoImpl implementation for COFF targets.
Definition at line 84 of file MachineModuleInfoImpls.h.
Constructor & Destructor Documentation
MachineModuleInfoCOFF()
llvm::MachineModuleInfoCOFF::MachineModuleInfoCOFF (const MachineModuleInfo &) inline
Definition at line 92 of file MachineModuleInfoImpls.h.
Member Function Documentation
getGVStubEntry()
StubValueTy& llvm::MachineModuleInfoCOFF::getGVStubEntry (MCSymbol * Sym) inline
Definition at line 94 of file MachineModuleInfoImpls.h.
References assert().
Referenced by llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), and getModifierVariantKind().
GetGVStubList()
SymbolListTy llvm::MachineModuleInfoCOFF::GetGVStubList () inline
Accessor methods to return the set of stubs in sorted order.
Definition at line 101 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedStubs().
Referenced by llvm::AsmPrinter::doFinalization().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfoImpls.h
lib/CodeGen/MachineModuleInfoImpls.cpp