LLVM: llvm::MachineFunctionProperties Class Reference
llvm::MachineFunctionProperties Class Reference
Properties which a MachineFunction may have at a given point in time.
#include "llvm/CodeGen/MachineFunction.h"
Public Types
enum Property : unsigned {
Property::IsSSA, Property::NoPHIs, Property::TracksLiveness, Property::NoVRegs,
Property::FailedISel, Property::Legalized, Property::RegBankSelected, Property::Selected,
Property::LastProperty = Selected
}
Public Member Functions
bool hasProperty (Property P) const
MachineFunctionProperties & set (Property P)
MachineFunctionProperties & reset (Property P)
MachineFunctionProperties & reset ()
Reset all the properties.
MachineFunctionProperties & set (const MachineFunctionProperties &MFP)
MachineFunctionProperties & reset (const MachineFunctionProperties &MFP)
bool verifyRequiredProperties (const MachineFunctionProperties &V) const
void print (raw_ostream &OS) const
Print the MachineFunctionProperties in human-readable form.
Detailed Description
Properties which a MachineFunction may have at a given point in time.
Each of these has checking code in the MachineVerifier, and passes can require that a property be set.
Definition at line 110 of file MachineFunction.h.
Member Enumeration Documentation
Property
enum llvm::MachineFunctionProperties::Property : unsigned strong
Enumerator
IsSSA
NoPHIs
TracksLiveness
NoVRegs
FailedISel
Legalized
RegBankSelected
Selected
LastProperty
Definition at line 146 of file MachineFunction.h.
Member Function Documentation
hasProperty()
bool llvm::MachineFunctionProperties::hasProperty (Property P) const inline
Definition at line 158 of file MachineFunction.h.
References P.
Referenced by llvm::Combiner::combineMachineInstrs(), llvm::TargetInstrInfo::describeLoadedValue(), INITIALIZE_PASS(), insertCSRRestores(), llvm::MachineRegisterInfo::isSSA(), matchPair(), matchSwap(), llvm::MIRPrinter::print(), llvm::InstructionSelect::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::Localizer::runOnMachineFunction(), llvm::RegBankSelect::runOnMachineFunction(), llvm::MachineRegisterInfo::tracksLiveness(), and llvm::MachineFunction::verify().
print()
void MachineFunctionProperties::print (raw_ostream & OS) const
Print the MachineFunctionProperties in human-readable form.
Definition at line 106 of file MachineFunction.cpp.
References llvm::MachineFunction::DeleteMachineBasicBlock(), llvm::ilist_alloc_traits< NodeTy >::deleteNode(), llvm::MachineBasicBlock::getParent(), I, and llvm::MachineFunctionInfo::~MachineFunctionInfo().
Referenced by llvm::MachineFunction::print().
reset() [1/3]
MachineFunctionProperties& llvm::MachineFunctionProperties::reset (Property P) inline
Definition at line 167 of file MachineFunction.h.
References reset().
Referenced by createPHIsForSelects(), llvm::Thumb1FrameLowering::emitPrologue(), emitSelectPseudo(), INITIALIZE_PASS(), llvm::MachineRegisterInfo::invalidateLiveness(), isSSA(), llvm::MachineRegisterInfo::leaveSSA(), reset(), and llvm::MachineFunction::~MachineFunction().
reset() [2/3]
MachineFunctionProperties& llvm::MachineFunctionProperties::reset () inline
Reset all the properties.
Definition at line 173 of file MachineFunction.h.
References reset().
reset() [3/3]
MachineFunctionProperties& llvm::MachineFunctionProperties::reset (const MachineFunctionProperties & MFP) inline
Definition at line 183 of file MachineFunction.h.
References reset().
set() [1/2]
MachineFunctionProperties& llvm::MachineFunctionProperties::set (Property P) inline
Definition at line 162 of file MachineFunction.h.
References P, and set().
Referenced by branchMaxOffsets(), llvm::createFalkorMarkStridedAccessesPass(), llvm::createX86RetpolineThunksPass(), llvm::VirtRegMap::dump(), llvm::Legalizer::getClearedProperties(), llvm::RegBankSelect::getClearedProperties(), llvm::InstructionSelect::getRequiredProperties(), llvm::Legalizer::getRequiredProperties(), llvm::BreakFalseDeps::getRequiredProperties(), llvm::Localizer::getRequiredProperties(), llvm::ReachingDefAnalysis::getRequiredProperties(), llvm::ExecutionDomainFix::getRequiredProperties(), llvm::RegBankSelect::getRequiredProperties(), llvm::InstructionSelect::getSetProperties(), llvm::Legalizer::getSetProperties(), llvm::RegBankSelect::getSetProperties(), hasArgumentDef(), llvm::MIRParserImpl::initializeMachineFunction(), isRegOtherThanSPAndFP(), isSecondInstructionInSequence(), isSSA(), llvm::MachineFunction::MachineFunction(), performSink(), llvm::reportGISelFailure(), llvm::scavengeFrameVirtualRegs(), set(), and llvm::AntiDepBreaker::~AntiDepBreaker().
set() [2/2]
MachineFunctionProperties& llvm::MachineFunctionProperties::set (const MachineFunctionProperties & MFP) inline
Definition at line 178 of file MachineFunction.h.
verifyRequiredProperties()
bool llvm::MachineFunctionProperties::verifyRequiredProperties (const MachineFunctionProperties & V) const inline
Definition at line 190 of file MachineFunction.h.
References print(), and llvm::BitVector::test().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineFunction.h
lib/CodeGen/MachineFunction.cpp