LLVM: llvm::ScopedNoAliasAAResult Class Reference
llvm::ScopedNoAliasAAResult Class Reference
A simple AA result which uses scoped-noalias metadata to answer queries.
#include "llvm/Analysis/ScopedNoAliasAA.h"
Public Member Functions
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Handle invalidation events from the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Public Member Functions inherited from llvm::AAResultBase< ScopedNoAliasAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< ScopedNoAliasAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
A simple AA result which uses scoped-noalias metadata to answer queries.
Definition at line 30 of file ScopedNoAliasAA.h.
Member Function Documentation
alias()
AliasResult ScopedNoAliasAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 78 of file ScopedNoAliasAA.cpp.
References llvm::MemoryLocation::AATags, llvm::AAResultBase< DerivedT >::alias(), EnableScopedNoAlias, llvm::NoAlias, llvm::AAMDNodes::NoAlias, and llvm::AAMDNodes::Scope.
Referenced by invalidate().
getModRefInfo() [1/2]
ModRefInfo ScopedNoAliasAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Definition at line 99 of file ScopedNoAliasAA.cpp.
References llvm::MemoryLocation::AATags, EnableScopedNoAlias, llvm::Instruction::getMetadata(), llvm::AAResultBase< DerivedT >::getModRefInfo(), llvm::AAMDNodes::NoAlias, llvm::NoModRef, and llvm::AAMDNodes::Scope.
Referenced by invalidate().
getModRefInfo() [2/2]
ModRefInfo ScopedNoAliasAAResult::getModRefInfo (const CallBase * Call1, const CallBase * Call2, AAQueryInfo & AAQI)
Definition at line 116 of file ScopedNoAliasAA.cpp.
References EnableScopedNoAlias, llvm::Instruction::getMetadata(), llvm::AAResultBase< DerivedT >::getModRefInfo(), and llvm::NoModRef.
invalidate()
bool llvm::ScopedNoAliasAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 37 of file ScopedNoAliasAA.h.
References alias(), getModRefInfo(), and llvm::NoAlias.
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScopedNoAliasAA.h
lib/Analysis/ScopedNoAliasAA.cpp