LLVM: llvm::ScopedHashTableIterator< K, V, KInfo > Class Template Reference
llvm::ScopedHashTableIterator< K, V, KInfo > Class Template Reference
#include "llvm/ADT/ScopedHashTable.h"
Public Member Functions
ScopedHashTableIterator (ScopedHashTableVal< K, V > *node)
V & operator* () const
V * operator-> () const
bool operator== (const ScopedHashTableIterator &RHS) const
bool operator!= (const ScopedHashTableIterator &RHS) const
ScopedHashTableIterator & operator++ ()
ScopedHashTableIterator operator++ (int)
Detailed Description
template<typename K, typename V, typename KInfo = DenseMapInfo<K>>
class llvm::ScopedHashTableIterator< K, V, KInfo >
Definition at line 118 of file ScopedHashTable.h.
Constructor & Destructor Documentation
ScopedHashTableIterator()
template<typename K , typename V , typename KInfo = DenseMapInfo<K>> llvm::ScopedHashTableIterator< K, V, KInfo >::ScopedHashTableIterator (ScopedHashTableVal< K, V > * node) inline
Definition at line 122 of file ScopedHashTable.h.
Member Function Documentation
operator!=()
template<typename K , typename V , typename KInfo = DenseMapInfo<K>> bool llvm::ScopedHashTableIterator< K, V, KInfo >::operator!= (const ScopedHashTableIterator< K, V, KInfo > & RHS) const inline
Definition at line 135 of file ScopedHashTable.h.
operator*()
template<typename K , typename V , typename KInfo = DenseMapInfo<K>> V& llvm::ScopedHashTableIterator< K, V, KInfo >::operator* () const inline
Definition at line 124 of file ScopedHashTable.h.
References assert(), and llvm::ScopedHashTableVal< K, V >::getValue().
operator++() [1/2]
template<typename K , typename V , typename KInfo = DenseMapInfo<K>> ScopedHashTableIterator& llvm::ScopedHashTableIterator< K, V, KInfo >::operator++ () inline
Definition at line 139 of file ScopedHashTable.h.
References assert(), and llvm::ScopedHashTableVal< K, V >::getNextForKey().
operator++() [2/2]
template<typename K , typename V , typename KInfo = DenseMapInfo<K>> ScopedHashTableIterator llvm::ScopedHashTableIterator< K, V, KInfo >::operator++ (int) inline
Definition at line 144 of file ScopedHashTable.h.
operator->()
template<typename K , typename V , typename KInfo = DenseMapInfo<K>> V* llvm::ScopedHashTableIterator< K, V, KInfo >::operator-> () const inline
Definition at line 128 of file ScopedHashTable.h.
References llvm::ScopedHashTableVal< K, V >::getValue().
operator==()
template<typename K , typename V , typename KInfo = DenseMapInfo<K>> bool llvm::ScopedHashTableIterator< K, V, KInfo >::operator== (const ScopedHashTableIterator< K, V, KInfo > & RHS) const inline
Definition at line 132 of file ScopedHashTable.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ScopedHashTable.h