LLVM: llvm::DIEHash Class Reference
llvm::DIEHash Class Reference
An object containing the capability of hashing and adding hash attributes onto a DIE.
#include "CodeGen/AsmPrinter/DIEHash.h"
Public Member Functions
DIEHash (AsmPrinter *A=nullptr)
uint64_t computeCUSignature (StringRef DWOName, const DIE &Die)
Computes the CU signature.
uint64_t computeTypeSignature (const DIE &Die)
Computes the type signature.
void update (uint8_t Value)
Adds.
void addULEB128 (uint64_t Value)
Encodes and adds.
void addSLEB128 (int64_t Value)
Encodes and adds.
Detailed Description
An object containing the capability of hashing and adding hash attributes onto a DIE.
Definition at line 27 of file DIEHash.h.
Constructor & Destructor Documentation
DIEHash()
llvm::DIEHash::DIEHash (AsmPrinter * A = nullptr) inline
Definition at line 35 of file DIEHash.h.
References computeCUSignature(), and computeTypeSignature().
Member Function Documentation
addSLEB128()
void DIEHash::addSLEB128 (int64_t Value)
Encodes and adds.
Parameters
Value to the hash as a SLEB128.
Definition at line 65 of file DIEHash.cpp.
References addULEB128(), assert(), llvm::dwarf::AttributeString(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::dbgs(), E, llvm::StringRef::empty(), getDIEStringAttr(), llvm::DIE::getParent(), llvm::DIE::getTag(), I, LLVM_DEBUG, Name, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateCommon< T >::rbegin(), llvm::SmallVectorTemplateCommon< T >::rend(), llvm::Tag, llvm::MD5::update(), and llvm::DIEValueList::values().
Referenced by llvm::HashingByteStreamer::EmitSLEB128(), and update().
addULEB128()
void DIEHash::addULEB128 (uint64_t Value)
Encodes and adds.
Adds the unsigned in Value to the hash encoded as a ULEB128.
Parameters
Value to the hash as a ULEB128.
Definition at line 54 of file DIEHash.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::MD5::update().
Referenced by addSLEB128(), llvm::HashingByteStreamer::EmitULEB128(), and update().
computeCUSignature()
uint64_t DIEHash::computeCUSignature (StringRef DWOName, const DIE & Die)
Computes the CU signature.
This is based on the type signature computation given in section 7.27 of the DWARF4 standard.
It is an md5 hash of the flattened description of the DIE with the inclusion of the full CU and all top level CU entities.
Definition at line 383 of file DIEHash.cpp.
References llvm::StringRef::empty(), llvm::MD5::final(), llvm::MD5::MD5Result::high(), and llvm::MD5::update().
Referenced by llvm::DwarfDebug::beginModule(), and DIEHash().
computeTypeSignature()
uint64_t DIEHash::computeTypeSignature (const DIE & Die)
Computes the type signature.
This is based on the type signature computation given in section 7.27 of the DWARF4 standard.
It is an md5 hash of the flattened description of the DIE with the inclusion of additional forms not specifically called out in the standard.
Definition at line 406 of file DIEHash.cpp.
References llvm::MD5::final(), llvm::DIE::getParent(), and llvm::MD5::MD5Result::high().
Referenced by DIEHash().
update()
void llvm::DIEHash::update (uint8_t Value) inline
Adds.
Parameters
Value to the hash.
Definition at line 57 of file DIEHash.h.
References addSLEB128(), addULEB128(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, Name, Numbering, and llvm::Tag.
Referenced by llvm::HashingByteStreamer::EmitInt8().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DIEHash.h
lib/CodeGen/AsmPrinter/DIEHash.cpp