LLVM: llvm::Type Class Reference
llvm::Type Class Reference
The instances of the Type class are immutable: once they are created, they are never changed.
#include "llvm/IR/Type.h"
Public Types
enum TypeID {
VoidTyID = 0, HalfTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, LabelTyID,
MetadataTyID, X86_MMXTyID, TokenTyID, IntegerTyID,
FunctionTyID, StructTyID, ArrayTyID, PointerTyID,
VectorTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type *const *
using subtype_reverse_iterator = std::reverse_iterator< subtype_iterator >
Public Member Functions
void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isFloatingPointTy () const
Return true if this is one of the six floating-point types.
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
Return true if this is X86 MMX.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type *> *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
Type * getSequentialElementType () const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
bool getVectorIsScalable () const
unsigned getVectorNumElements () const
ElementCount getVectorElementCount () const
Type * getVectorElementType () const
Type * getPointerElementType () const
Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static Type * getTokenTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy >
static Type * getScalarTy (LLVMContext &C)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Protected Member Functions
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Static Protected Member Functions
static bool isSequentialType (TypeID TyID)
Protected Attributes
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Friends
class LLVMContextImpl
Detailed Description
The instances of the Type class are immutable: once they are created, they are never changed.
Also note that only one instance of a particular type is ever created. Thus seeing if two types are equal is a matter of doing a trivial pointer comparison. To enforce that no two equal instances are created, Type instances can only be created via static factory methods in class Type and in derived classes. Once allocated, Types are never free'd.
Definition at line 46 of file Type.h.
Member Typedef Documentation
subtype_iterator
using llvm::Type::subtype_iterator = Type * const *
Definition at line 316 of file Type.h.
subtype_reverse_iterator
using llvm::Type::subtype_reverse_iterator = std::reverse_iterator<subtype_iterator>
Definition at line 324 of file Type.h.
Member Enumeration Documentation
TypeID
enum llvm::Type::TypeID
Definitions of all of the base types for the Type system.
Based on this value, you can cast to a class defined in DerivedTypes.h. Note: If you add an element to this, you need to add an element to the Type::getPrimitiveType function, or else things will break! Also update LLVMTypeKind and LLVMGetTypeKind () in the C binding.
Enumerator
VoidTyID
0: type with no size
HalfTyID
1: 16-bit floating point type
FloatTyID
2: 32-bit floating point type
DoubleTyID
3: 64-bit floating point type
X86_FP80TyID
4: 80-bit floating point type (X87)
FP128TyID
5: 128-bit floating point type (112-bit mantissa)
PPC_FP128TyID
6: 128-bit floating point type (two 64-bits, PowerPC)
LabelTyID
7: Labels
MetadataTyID
8: Metadata
X86_MMXTyID
9: MMX vectors (64 bits, X86 specific)
TokenTyID
10: Tokens
IntegerTyID
11: Arbitrary bit width integers
FunctionTyID
12: Functions
StructTyID
13: Structures
ArrayTyID
14: Arrays
PointerTyID
15: Pointers
VectorTyID
16: SIMD 'packed' format, or other vector type
Definition at line 55 of file Type.h.
Constructor & Destructor Documentation
Type()
llvm::Type::Type (LLVMContext & C, TypeID tid) inline explicit protected
Definition at line 91 of file Type.h.
References ~Type().
Referenced by llvm::object::MinidumpFile::create(), llvm::StructType::create(), llvm::IntegerType::getMask(), llvm::StructType::hasName(), and streamMapping().
~Type()
llvm::Type::~Type () protected default
Referenced by Type().
Member Function Documentation
canLosslesslyBitCastTo()
bool Type::canLosslesslyBitCastTo (Type * Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
For example, i8* to i32*. BitCasts are valid for types of the same size only where no re-interpretation of the bits is done. Determine if this type could be losslessly bitcast to Ty
Definition at line 61 of file Type.cpp.
References getTypeID(), isFirstClassType(), and X86_MMXTyID.
Referenced by isFuncOrArgAttr(), and isVectorTy().
dump()
LLVM_DUMP_METHOD void Type::dump () const
Definition at line 4470 of file AsmWriter.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
Referenced by llvm::coro::Shape::buildFrom(), canTailPredicateLoop(), llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), and isSequentialType().
getArrayElementType()
Type* llvm::Type::getArrayElementType () const inline
Definition at line 368 of file Type.h.
References ArrayTyID, assert(), getTypeID(), getVectorElementCount(), getVectorIsScalable(), and getVectorNumElements().
Referenced by computeUnsignedMinMaxValuesFromKnownBits(), llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), getTypePartition(), isConstantUsingVectorTy(), isSupportedType(), and llvm::InstCombiner::visitGetElementPtrInst().
getArrayNumElements()
uint64_t llvm::Type::getArrayNumElements () const inline
Definition at line 427 of file DerivedTypes.h.
Referenced by computeUnsignedMinMaxValuesFromKnownBits(), getAggregateNumElements(), llvm::getConstantDataArrayInfo(), getSequentialElementType(), scalarConstantToHexString(), and llvm::InstCombiner::visitGetElementPtrInst().
getContainedType()
Type* llvm::Type::getContainedType (unsigned i) const inline
This method is used to implement the type iterator (defined at the end of the file).
For derived types, this returns the types 'contained' in the derived type.
Definition at line 336 of file Type.h.
References assert().
Referenced by llvm::createAMDGPUPrintfRuntimeBinding(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), and memVTFromAggregate().
getContext()
LLVMContext& llvm::Type::getContext () const inline
Return the LLVMContext in which this type was uniqued.
Definition at line 130 of file Type.h.
References Context.
Referenced by llvm::AMDGPUCallLowering::AMDGPUCallLowering(), annotateAnyAllocSite(), atomicSizeSupported(), llvm::canConstantFoldCallTo(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), ComputePostOrders(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadFromConstPtr(), llvm::convertPointerToIntegerType(), llvm::StructType::create(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::orc::createIRTypedAddress(), llvm::FunctionLoweringInfo::CreateRegs(), evaluateBitcastFromPtr(), FoldBitCast(), foldConstantCastPair(), foldOperationIntoPhiValue(), foldUnsignedUnderflowCheck(), llvm::InlineAsm::get(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::ConstantFP::get(), llvm::StructType::get(), llvm::ConstantAggregateZero::get(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::VectorType::get(), llvm::ConstantVector::get(), llvm::ConstantPointerNull::get(), llvm::PointerType::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getAlignOf(), getAllocationDataForFunction(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getBinOpAbsorber(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::BasicBlock::getContext(), llvm::Function::getContext(), llvm::Value::getContext(), llvm::EVT::getEVT(), llvm::IntegerType::getExtendedType(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), getFirstNonAllocaInTheEntryBlock(), getFoldedCast(), llvm::ConstantExpr::getICmp(), llvm::ConstantDataSequential::getImpl(), llvm::DataLayout::getIndexType(), llvm::ConstantFP::getInfinity(), llvm::VectorType::getInteger(), llvm::Constant::getIntegerValue(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::DataLayout::getIntPtrType(), llvm::VNCoercion::getLoadValueForLoad(), llvm::IntegerType::getMask(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::VNCoercion::getMemInstValueForLoadHelper(), llvm::TargetLoweringBase::getMemValueType(), llvm::ConstantFP::getNaN(), llvm::ConstantFP::getNegativeZero(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getOffsetOf(), getPromotedType(), llvm::ConstantFP::getQNaN(), getRelevantOperands(), getReturnAttrs(), llvm::GetReturnInfo(), llvm::ConstantExpr::getShuffleVector(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantFP::getSNaN(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::ConstantInt::getTrue(), llvm::VectorType::getTruncatedElementVectorType(), llvm::Module::getTypeByName(), llvm::TargetLoweringBase::getTypeLegalizationCost(), getTypePartition(), llvm::X86TTIImpl::getUserCost(), llvm::TargetLoweringBase::getValueType(), getWithNewBitWidth(), llvm::ValueAsMetadata::handleDeletion(), llvm::ValueAsMetadata::handleRAUW(), hasLifetimeMarkers(), hasSameExtUse(), IsIncrementNSW(), IsIncrementNUW(), isIntegerWideningViable(), isVectorPromotionViableForSlice(), LLVMConstIntOfArbitraryPrecision(), llvm::BlockAddress::lookup(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::X86CallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::CmpInst::makeCmpResultType(), llvm::fuzzerop::makeConstantsWithType(), MulWillOverflow(), operator<<(), llvm::TargetLowering::ParseConstraints(), parseOptionalLinkageAux(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::StructType::setBody(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::StructType::setName(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::sroa::AllocaSliceRewriter::visit(), and llvm::X86CallLowering::X86CallLowering().
getDoublePtrTy()
PointerType * Type::getDoublePtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 196 of file Type.cpp.
References getDoubleTy(), and getPointerTo().
Referenced by getScalarTy().
getDoubleTy()
Type * Type::getDoubleTy (LLVMContext & C) static
Definition at line 169 of file Type.cpp.
References llvm::LLVMContextImpl::DoubleTy, and llvm::LLVMContext::pImpl.
Referenced by ConvertDoubleToBytes(), convertImplicitDefToConstZero(), DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantFP::get(), llvm::ConstantDataVector::get(), getDoublePtrTy(), llvm::IRBuilderBase::getDoubleTy(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getIntrinsicParamType(), getPointerElementType(), getPrimitiveType(), getScalarTy(), llvm::EVT::getTypeForEVT(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LLVMDoubleTypeInContext(), llvm::LegalizerHelper::lower(), LowerFPToInt(), ReplaceFPIntrinsicWithCall(), and shrinkFPConstant().
getExtendedType()
Type * llvm::Type::getExtendedType () const inline
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
For vectors, preserves element count.
Definition at line 615 of file DerivedTypes.h.
References assert(), llvm::VectorType::getExtendedElementVectorType(), llvm::IntegerType::getExtendedType(), and isIntOrIntVectorTy().
Referenced by dropRedundantMaskingOfLeftShiftInput(), and getPointerElementType().
getFloatPtrTy()
PointerType * Type::getFloatPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 192 of file Type.cpp.
References getFloatTy(), and getPointerTo().
Referenced by getScalarTy().
getFloatTy()
Type * Type::getFloatTy (LLVMContext & C) static
Definition at line 168 of file Type.cpp.
References llvm::LLVMContextImpl::FloatTy, and llvm::LLVMContext::pImpl.
Referenced by ConvertDoubleToBytes(), convertImplicitDefToConstZero(), llvm::MDBuilder::createFPMath(), DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantFP::get(), llvm::ConstantDataVector::get(), getFloatPtrTy(), llvm::IRBuilderBase::getFloatTy(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getIntrinsicParamType(), getNormalLoadInput(), getPointerElementType(), getPrimitiveType(), getScalarTy(), llvm::VectorType::getTruncatedElementVectorType(), llvm::EVT::getTypeForEVT(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LLVMFloatTypeInContext(), llvm::LegalizerHelper::lower(), LowerFPToInt(), ReplaceFPIntrinsicWithCall(), shrinkFPConstant(), and UpgradePTESTIntrinsic().
getFltSemantics()
const fltSemantics& llvm::Type::getFltSemantics () const inline
Definition at line 169 of file Type.h.
References DoubleTyID, FloatTyID, FP128TyID, getTypeID(), HalfTyID, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm_unreachable, PPC_FP128TyID, llvm::APFloatBase::PPCDoubleDouble(), X86_FP80TyID, and llvm::APFloatBase::x87DoubleExtended().
Referenced by llvm::canConstantFoldCallTo(), llvm::ConstantFoldCastInstruction(), FoldBitCast(), INITIALIZE_PASS(), llvm::fuzzerop::makeConstantsWithType(), mapBinOpcode(), parseTexFail(), llvm::InstCombiner::visitFAdd(), and llvm::InstCombiner::visitFCmpInst().
getFP128PtrTy()
PointerType * Type::getFP128PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 204 of file Type.cpp.
References getFP128Ty(), and getPointerTo().
Referenced by getScalarTy().
getFP128Ty()
Type * Type::getFP128Ty (LLVMContext & C) static
Definition at line 173 of file Type.cpp.
References llvm::LLVMContextImpl::FP128Ty, and llvm::LLVMContext::pImpl.
Referenced by DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantFP::get(), getFP128PtrTy(), getPointerElementType(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), LLVMFP128TypeInContext(), and llvm::LegalizerHelper::lower().
getFPMantissaWidth()
int Type::getFPMantissaWidth () const
Return the width of the mantissa of this type.
This is only valid on floating-point types. If the FP type does not have a stable mantissa (e.g. ppc long double), this method returns -1.
Definition at line 138 of file Type.cpp.
References assert(), DoubleTyID, FloatTyID, FP128TyID, getTypeID(), HalfTyID, isFloatingPointTy(), isSized(), PPC_FP128TyID, and X86_FP80TyID.
Referenced by isSized(), shrinkFPConstantVector(), and llvm::InstCombiner::visitFPTrunc().
getFunctionNumParams()
unsigned llvm::Type::getFunctionNumParams () const inline
Definition at line 162 of file DerivedTypes.h.
Referenced by getNumContainedTypes().
getFunctionParamType()
Type * llvm::Type::getFunctionParamType (unsigned i) const inline
Definition at line 158 of file DerivedTypes.h.
Referenced by getNumContainedTypes(), and llvm::isLegalToPromote().
getHalfPtrTy()
PointerType * Type::getHalfPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 188 of file Type.cpp.
References getHalfTy(), and getPointerTo().
Referenced by getScalarTy().
getHalfTy()
Type * Type::getHalfTy (LLVMContext & C) static
Definition at line 167 of file Type.cpp.
References llvm::LLVMContextImpl::HalfTy, and llvm::LLVMContext::pImpl.
Referenced by ConvertDoubleToBytes(), DecodeFixedType(), llvm::ConstantFP::get(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getHalfPtrTy(), llvm::IRBuilderBase::getHalfTy(), getIntrinsicParamType(), getPointerElementType(), getPrimitiveType(), llvm::VectorType::getTruncatedElementVectorType(), llvm::EVT::getTypeForEVT(), LLVMHalfTypeInContext(), llvm::LegalizerHelper::lower(), and shrinkFPConstant().
getInt128Ty()
IntegerType * Type::getInt128Ty (LLVMContext & C) static
Definition at line 182 of file Type.cpp.
References llvm::LLVMContextImpl::Int128Ty, and llvm::LLVMContext::pImpl.
Referenced by llvm::IntegerType::get(), llvm::IRBuilderBase::getInt128Ty(), getPointerElementType(), llvm::EVT::getTypeForEVT(), and LLVMInt128TypeInContext().
getInt16PtrTy()
PointerType * Type::getInt16PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 228 of file Type.cpp.
References getInt16Ty(), and getPointerTo().
Referenced by getScalarTy().
getInt16Ty()
IntegerType * Type::getInt16Ty (LLVMContext & C) static
Definition at line 179 of file Type.cpp.
References llvm::LLVMContextImpl::Int16Ty, and llvm::LLVMContext::pImpl.
Referenced by llvm::ConstantFoldLoadThroughBitcast(), ConvertDoubleToBytes(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::CodeExtractor::findInputsOutputs(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), getInt16PtrTy(), llvm::IRBuilderBase::getInt16Ty(), getIntrinsicParamType(), getPointerElementType(), llvm::EVT::getTypeForEVT(), insertLifetimeMarkersSurroundingCall(), llvm::isBytewiseValue(), LLVMInt16TypeInContext(), and needsRuntimeRegistrationOfSectionRange().
getInt1PtrTy()
PointerType * Type::getInt1PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 220 of file Type.cpp.
References getInt1Ty(), and getPointerTo().
Referenced by llvm::InstCombiner::CreateNonTerminatorUnreachable(), llvm::SCEVExpander::getIVIncOperand(), getScalarTy(), and llvm::Function::setPrologueData().
getInt1Ty()
IntegerType * Type::getInt1Ty (LLVMContext & C) static
Definition at line 177 of file Type.cpp.
References llvm::LLVMContextImpl::Int1Ty, and llvm::LLVMContext::pImpl.
Referenced by llvm::SelectInst::areInvalidOperands(), buildFrameType(), llvm::canConstantFoldCallTo(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), CloneLoop(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCompareInstruction(), llvm::MDBuilder::createCallbackEncoding(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedScatter(), DisableAllLoopOptsOnLoop(), llvm::CodeExtractor::findInputsOutputs(), FunctionNumber(), llvm::IntegerType::get(), llvm::ConstantExpr::getAlignOf(), llvm::IRPosition::getAttrs(), getEdgeValueLocal(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), llvm::ConstantExpr::getICmp(), getInt1PtrTy(), llvm::IRBuilderBase::getInt1Ty(), getNegativeIsTrueBoolVec(), getPointerElementType(), GetRMWLibcall(), llvm::ConstantInt::getTrue(), llvm::EVT::getTypeForEVT(), llvm::X86TTIImpl::getUserCost(), llvm::SCEVExpander::hoistIVInc(), insertLifetimeMarkersSurroundingCall(), LLVMInt1TypeInContext(), llvm::CmpInst::makeCmpResultType(), OptimizeGlobalAddressOfMalloc(), performMaskedAtomicOp(), processCmp(), PushDefUseChildren(), ReplaceUsesOfWith(), rewrite(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), SimplifyCondBranchToCondBranch(), SwitchToLookupTable(), TryToShrinkGlobalToBoolean(), UpgradeIntrinsicFunction1(), and llvm::InstCombiner::visitAllocSite().
getInt32PtrTy()
PointerType * Type::getInt32PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 232 of file Type.cpp.
References getInt32Ty(), and getPointerTo().
Referenced by getComparePred(), getScalarTy(), getSignature(), and LowerToTLSExecModel().
getInt32Ty()
IntegerType * Type::getInt32Ty (LLVMContext & C) static
Definition at line 180 of file Type.cpp.
References llvm::LLVMContextImpl::Int32Ty, and llvm::LLVMContext::pImpl.
Referenced by llvm::Module::addModuleFlag(), llvm::annotateValueSite(), BuildConstantFromSCEV(), calcArraySize(), collectShuffleElements(), collectSingleShuffleElements(), llvm::ShuffleVectorInst::commute(), computeBytesPoppedByCalleeForSRet(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), ConvertDoubleToBytes(), llvm::convertPointerToIntegerType(), ConvertToSInt(), llvm::ARMConstantPoolConstant::Create(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::MDBuilder::createBranchWeights(), llvm::IRBuilder< TargetFolder >::CreateConstGEP1_32(), llvm::IRBuilder< TargetFolder >::CreateConstGEP2_32(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< TargetFolder >::CreateGlobalStringPtr(), llvm::IRBuilder< TargetFolder >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< TargetFolder >::CreatePreserveStructAccessIndex(), createPrivateGlobalForSourceLoc(), llvm::createShadowStackGCLoweringPass(), createStringMetadata(), llvm::createThreadSanitizerLegacyPassPass(), llvm::createXCoreISelDag(), doPromotion(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitPostSt(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), evaluateInDifferentElementOrder(), llvm::CodeExtractor::findInputsOutputs(), llvm::SanitizerStatReport::finish(), FoldBitCast(), foldConstantInsEltIntoShuffle(), foldIdentityPaddedShuffles(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldOperationIntoPhiValue(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), getAISize(), llvm::ConstantExpr::getAlignOf(), getComparePred(), getContiguousRangeOfSetBits(), getDefaultPersonalityFn(), getInt32PtrTy(), llvm::IRBuilderBase::getInt32Ty(), getIntrinsicParamType(), getKeyValMD(), getOffsetFromIndices(), llvm::ConstantExpr::getOffsetOf(), getOtherIncomingValue(), getPointerElementType(), getPromotedType(), GetRMWLibcall(), getSignature(), llvm::ConstantExpr::getSizeOf(), llvm::EVT::getTypeForEVT(), getUnconditionalBrDisp(), INITIALIZE_PASS(), insertCall(), insertLifetimeMarkersSurroundingCall(), insertSpills(), instrumentMaskedLoadOrStore(), llvm::isBytewiseValue(), isCallPromotable(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), IsSmallObject(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), LLVMInt32TypeInContext(), llvm::XCoreInstrInfo::loadImmediate(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerLoadRelative(), mapBinOpcode(), MarkBlocksLiveIn(), llvm::MergeBasicBlockIntoOnlyPred(), needsRuntimeRegistrationOfSectionRange(), llvm::EscapeEnumerator::Next(), performMaskedAtomicOp(), PushArgMD(), replaceExtractElements(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::LoopDataPrefetchPass::run(), llvm::SanitizerStatReport::SanitizerStatReport(), SegmentOffset(), shouldFixMainFunction(), shouldKeepInEntry(), ShrinkDemandedConstant(), SimplifyRelativeLoad(), simplifyX86pshufb(), simplifyX86vpermilvar(), simplifyX86vpermv(), splitGlobal(), splitMergedValStore(), SRAGlobal(), unpackLoadToAggregate(), unpackStoreToAggregate(), updateOperand(), llvm::UpgradeIntrinsicCall(), llvm::UpgradeModuleFlags(), validExtractValueIndex(), validInsertValueIndex(), validShuffleVectorIndex(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitShuffleVectorInst(), and llvm::BasicBlock::~BasicBlock().
getInt64PtrTy()
PointerType * Type::getInt64PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 236 of file Type.cpp.
References getInt64Ty(), and getPointerTo().
Referenced by getScalarTy(), INITIALIZE_PASS(), and shouldKeepInEntry().
getInt64Ty()
IntegerType * Type::getInt64Ty (LLVMContext & C) static
Definition at line 181 of file Type.cpp.
References llvm::LLVMContextImpl::Int64Ty, and llvm::LLVMContext::pImpl.
Referenced by llvm::GlobalObject::addTypeMetadata(), llvm::GlobalObject::addVCallVisibilityMetadata(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), llvm::annotateValueSite(), calcArraySize(), collectFunctionUsers(), llvm::ConstantFoldLoadThroughBitcast(), ConvertDoubleToBytes(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::MDBuilder::createCallbackEncoding(), llvm::IRBuilder< TargetFolder >::CreateConstGEP1_64(), llvm::IRBuilder< TargetFolder >::CreateConstGEP2_64(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP2_64(), llvm::MDBuilder::createFunctionEntryCount(), llvm::createIRLevelProfileFlagVar(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::orc::createIRTypedAddress(), llvm::MDBuilder::createMisExpect(), llvm::IRBuilder< TargetFolder >::CreatePtrDiff(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), doPromotion(), llvm::orc::IRSpeculationLayer::emit(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), foldConstantCastPair(), genLoopLimit(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), llvm::ConstantExpr::getAlignOf(), getComparePred(), getImplicitScaleFactor(), getInt64PtrTy(), llvm::IRBuilderBase::getInt64Ty(), getIntrinsicParamType(), getKeyValMD(), llvm::VNCoercion::getMemInstValueForLoadHelper(), llvm::ConstantExpr::getOffsetOf(), getPointerElementType(), GetRMWLibcall(), llvm::ConstantExpr::getSizeOf(), llvm::InstrProfIncrementInst::getStep(), llvm::EVT::getTypeForEVT(), INITIALIZE_PASS(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), llvm::isBytewiseValue(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), IsSafeAndProfitableToMove(), llvm::LegalizerHelper::libcall(), LLVMInt64TypeInContext(), llvm::IntrinsicLowering::LowerIntrinsicCall(), mapBinOpcode(), needsRuntimeRegistrationOfSectionRange(), llvm::CGProfilePass::run(), llvm::AArch64TTIImpl::shouldConsiderAddressTypePromotion(), shouldKeepInEntry(), SimplifyRelativeLoad(), simplifyX86extrq(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::CallInst::updateProfWeight(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::UpgradeTBAANode(), and llvm::AMDGPULibCalls::useNative().
getInt8PtrTy()
PointerType * Type::getInt8PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 224 of file Type.cpp.
References getInt8Ty(), and getPointerTo().
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), appendToGlobalArray(), appendToUsedList(), BuildConstantFromSCEV(), llvm::coro::Shape::buildFrom(), calcArraySize(), llvm::CoroIdInst::clearPromise(), createDevirtTriggerFunc(), llvm::createDwarfEHPass(), createFree(), CreateGCRelocates(), createMalloc(), llvm::createMemLibcall(), CreatePrologue(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), llvm::createThreadSanitizerLegacyPassPass(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), expandBounds(), llvm::SCEVExpander::expandCodeFor(), llvm::SanitizerStatReport::finish(), llvm::BlockAddress::get(), getAllocationDataForFunction(), llvm::IRTranslator::getAnalysisUsage(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), getFirstNonAllocaInTheEntryBlock(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::TargetLoweringBase::getIRStackGuard(), llvm::SCEVExpander::getIVIncOperand(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getNaturalGEPWithOffset(), getNumBytes(), GetPointerOperand(), GetRMWLibcall(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), getScalarTy(), getSignature(), hasLifetimeMarkers(), hasSameExtUse(), INITIALIZE_PASS(), insertCall(), insertLifetimeMarkersSurroundingCall(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), llvm::TargetLoweringBase::insertSSPDeclarations(), instrumentOneFunc(), llvm::isAllocaPromotable(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), llvm::isLibFreeFunction(), IsSmallObject(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), MarkBlocksLiveIn(), needsRuntimeRegistrationOfSectionRange(), llvm::EscapeEnumerator::Next(), prepareForSplit(), llvm::coro::replaceCoroFree(), replaceSwiftErrorOps(), llvm::LoopDataPrefetchPass::run(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::SanitizerStatReport::SanitizerStatReport(), SegmentOffset(), setCoroInfo(), llvm::CoroIdInst::setCoroutineSelf(), setUsedInitializer(), shouldFixMainFunction(), shouldKeepInEntry(), SimplifyRelativeLoad(), unifyBitWidth(), updateOperand(), llvm::sroa::AllocaSliceRewriter::visit(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getInt8Ty()
IntegerType * Type::getInt8Ty (LLVMContext & C) static
Definition at line 178 of file Type.cpp.
References llvm::LLVMContextImpl::Int8Ty, and llvm::LLVMContext::pImpl.
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), calcArraySize(), ComputePostOrders(), ConvertDoubleToBytes(), llvm::createAArch64StackTaggingPass(), llvm::createAMDGPUPrintfRuntimeBinding(), createCallInst(), llvm::createMemCpyLoopUnknownSize(), llvm::createSeparateConstOffsetFromGEPPass(), dump(), llvm::EmbedBitcodeInModule(), llvm::orc::IRSpeculationLayer::emit(), llvm::SCEVExpander::expandCodeFor(), FunctionNumber(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), getArrayElements(), llvm::IRPosition::getAttrs(), llvm::SelectionDAG::getEVTAlignment(), getInt8PtrTy(), llvm::IRBuilderBase::getInt8Ty(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), getIntrinsicParamType(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType(), llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getPointerElementType(), GetPointerOperand(), llvm::EVT::getTypeForEVT(), getTypePartition(), hasSameExtUse(), INITIALIZE_PASS(), llvm::isBytewiseValue(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), isLoadInvariantInLoop(), IsSmallObject(), LLVMInt8TypeInContext(), lowerLoadRelative(), llvm::coro::LowererBase::makeSubFnCall(), patchAndReplaceAllUsesWith(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), shouldKeepInEntry(), llvm::sroa::AllocaSliceRewriter::visit(), and wrapConstantAsMetadata().
getIntegerBitWidth()
unsigned llvm::Type::getIntegerBitWidth () const inline
Definition at line 102 of file DerivedTypes.h.
References llvm::IntegerType::getBitWidth().
Referenced by canBeCheaplyTransformed(), llvm::canConstantFoldCallTo(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::ConstantFoldGetElementPtr(), createFFSIntrinsic(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), EmitX86ScalarSelect(), evaluateGEPOffsetExpression(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), foldICmpWithZextOrSext(), generateSignedDivisionCode(), generateSignedRemainderCode(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getEdgeValueLocal(), llvm::ARMTTIImpl::getIntImmCostInst(), getMaxPointerSize(), getNumContainedTypes(), llvm::DataLayout::getTypeSizeInBits(), getValueFromICmpCondition(), hasSameExtUse(), llvm::HexagonEvaluator::HexagonEvaluator(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::slpvectorizer::BoUpSLP::isLoadCombineReductionCandidate(), isPromotedInstructionLegal(), llvm::ConstantInt::isValueValidForType(), matchesOr(), moveUp(), processUDivOrURem(), and llvm::InstCombiner::visitFAdd().
getIntNPtrTy()
PointerType * Type::getIntNPtrTy (LLVMContext & C, unsigned N, unsigned AS = 0) static
Definition at line 216 of file Type.cpp.
References getIntNTy(), and getPointerTo().
Referenced by getScalarTy().
getIntNTy()
IntegerType * Type::getIntNTy (LLVMContext & C, unsigned N) static
Definition at line 184 of file Type.cpp.
References llvm::IntegerType::get().
Referenced by buildFrameType(), combineLoadToOperationType(), computeRecurrenceType(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createMaskInstrs(), createOrdering(), llvm::createThreadSanitizerLegacyPassPass(), foldBitcastExtElt(), getChainID(), getConstantVector(), GetCtorAndDtorPriority(), llvm::IntegerType::getExtendedType(), getIntNPtrTy(), llvm::IRBuilderBase::getIntNTy(), llvm::DataLayout::getLargestLegalIntType(), getMemCmpLoad(), getOffsetFromIndices(), getPointerElementType(), GetRMWLibcall(), getScalarTy(), llvm::DataLayout::getSmallestLegalIntType(), getTargetNode(), getTypePartition(), getWithNewBitWidth(), hasSameExtUse(), llvm::isBytewiseValue(), isIntegerWideningViable(), isVectorPromotionViableForSlice(), lowerBuildVectorAsBroadcast(), processUDivOrURem(), llvm::ModuleSanitizerCoveragePass::run(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), splitMergedValStore(), llvm::AMDGPULibCalls::useNative(), and llvm::sroa::AllocaSliceRewriter::visit().
getLabelTy()
Type * Type::getLabelTy (LLVMContext & C) static
Definition at line 166 of file Type.cpp.
References llvm::LLVMContextImpl::LabelTy, and llvm::LLVMContext::pImpl.
Referenced by FunctionNumber(), llvm::BasicBlock::getContext(), getPointerElementType(), getPrimitiveType(), and LLVMLabelTypeInContext().
getMetadataTy()
Type * Type::getMetadataTy (LLVMContext & C) static
Definition at line 170 of file Type.cpp.
References llvm::LLVMContextImpl::MetadataTy, and llvm::LLVMContext::pImpl.
Referenced by DecodeFixedType(), llvm::MetadataAsValue::get(), getPointerElementType(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), LLVMMetadataTypeInContext(), and llvm::ValueEnumerator::ValueEnumerator().
getNumContainedTypes()
unsigned llvm::Type::getNumContainedTypes () const inline
Return the number of types in the derived type.
Definition at line 342 of file Type.h.
References getFunctionNumParams(), getFunctionParamType(), getIntegerBitWidth(), getStructElementType(), getStructName(), getStructNumElements(), isFunctionVarArg(), N, and NumContainedTys.
Referenced by llvm::InstCombiner::visitBitCast().
getPointerAddressSpace()
unsigned llvm::Type::getPointerAddressSpace () const inline
Get the address space of this pointer or pointer vector type.
Definition at line 635 of file DerivedTypes.h.
References getScalarType().
Referenced by llvm::AMDGPUAAResult::alias(), annotateDereferenceableBytes(), annotateNonNullBasedOnAccess(), areStridedAccessesIndependent(), atomicSizeSupported(), BuildConstantFromSCEV(), castRequiresQueuePtr(), llvm::castToCStr(), cloneConstantExprWithNewAddressSpace(), llvm::orc::cloneGlobalAliasDecl(), cloneInstructionWithNewAddressSpace(), llvm::InstCombiner::combineLoadToNewType(), llvm::ConstantFoldCastOperand(), createCmpXchgInstFun(), createMaskInstrs(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::createSeparateConstOffsetFromGEPPass(), despeculateCountZeros(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::HexagonTargetLowering::emitStoreConditional(), expandBounds(), foldICmpWithZextOrSext(), getAccessType(), llvm::IntToPtrInst::getAddressSpace(), getAdjustedPtr(), llvm::IRPosition::getAttrs(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::CastInst::getCastOpcode(), getChainID(), llvm::AddrSpaceCastInst::getDestAddressSpace(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::VNCoercion::getLoadValueForLoad(), getMemCmpLoad(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getMemSetPatternValue(), getNumBytes(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperationCost(), llvm::Module::getOrInsertGlobal(), llvm::AtomicCmpXchgInst::getPointerAddressSpace(), llvm::AtomicRMWInst::getPointerAddressSpace(), llvm::PtrToIntInst::getPointerAddressSpace(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), getPointerElementType(), GetPointerOperand(), getPointerOperands(), GetRMWLibcall(), llvm::AddrSpaceCastInst::getSrcAddressSpace(), llvm::DataLayout::getTypeSizeInBits(), llvm::SelectionDAGBuilder::getValueImpl(), GlobalWasGeneratedByCompiler(), handleMemIntrinsicPtrUse(), hasLifetimeMarkers(), hasSameExtUse(), hasUndefContents(), INITIALIZE_PASS(), isCompatibleIVType(), llvm::CastInst::isEliminableCastPair(), isGEPFoldable(), isKnownNonNullFromDominatingCondition(), IsNonLocalValue(), isNoWrap(), isPromotedInstructionLegal(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), llvm::SelectionDAGBuilder::LowerStatepoint(), llvm::MachinePointerInfo::MachinePointerInfo(), maybePrintCallAddrSpace(), moveUp(), optimizeMemCmpConstantSize(), optimizeOnceStoredGlobal(), PerformHeapAllocSRoA(), performMaskedAtomicOp(), llvm::AMDGPUAAResult::pointsToConstantMemory(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::LoopDataPrefetchPass::run(), llvm::HWAddressSanitizerPass::run(), scalarizeMaskedLoad(), scalarizeMaskedStore(), shouldInstrumentReadWriteFromAddress(), simplifyAllocaArraySize(), simplifyInvariantGroupIntrinsic(), llvm::sortPtrAccesses(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::AMDGPULibCalls::useNative(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::sroa::AllocaSliceRewriter::visit(), and llvm::InstCombiner::visitGetElementPtrInst().
getPointerElementType()
Type* llvm::Type::getPointerElementType () const inline
Definition at line 381 of file Type.h.
References assert(), C, getDoubleTy(), getExtendedType(), getFloatTy(), getFP128Ty(), getHalfTy(), getInt128Ty(), getInt16Ty(), getInt1Ty(), getInt32Ty(), getInt64Ty(), getInt8Ty(), getIntNTy(), getLabelTy(), getMetadataTy(), getPointerAddressSpace(), getPPC_FP128Ty(), getPrimitiveType(), getTokenTy(), getTypeID(), getVoidTy(), getWithNewBitWidth(), getX86_FP80Ty(), getX86_MMXTy(), and PointerTyID.
Referenced by annotateAnyAllocSite(), areStridedAccessesIndependent(), buildGEP(), canTailPredicateLoop(), llvm::Evaluator::castCallResultIfNeeded(), cloneConstantExprWithNewAddressSpace(), cloneInstructionWithNewAddressSpace(), llvm::InstCombiner::combineLoadToNewType(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::IRBuilder< TargetFolder >::CreateAlignedLoad(), llvm::IRBuilder< TargetFolder >::CreateCall(), llvm::IRBuilder< TargetFolder >::CreateLoad(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::SCEVExpander::expandCodeFor(), llvm::IRPosition::getAttrs(), getBaseAlign(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), GetHeapSROAValue(), getInitializer(), llvm::Function::getParamByValType(), llvm::CallBase::getParamByValType(), GetPointerOperand(), llvm::SITargetLowering::getTgtMemIntrinsic(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), INITIALIZE_PASS(), llvm::RuntimePointerChecking::insert(), isCallPromotable(), llvm::CastInst::isEliminableCastPair(), llvm::InductionDescriptor::isInductionPHI(), llvm::slpvectorizer::BoUpSLP::isLoadCombineReductionCandidate(), llvm::isSafeToLoadUnconditionally(), moveUp(), operandWithNewAddressSpaceOrCreateUndef(), llvm::promoteLoopAccessesToScalars(), propagateMetadata(), replaceSwiftErrorOps(), simplifyAllocaArraySize(), and TypeSizeToSizeIndex().
getPointerTo()
PointerType * Type::getPointerTo (unsigned AddrSpace = 0) const
Return a pointer to the current type.
This is equivalent to PointerType::get(Foo, AddrSpace).
Definition at line 659 of file Type.cpp.
References llvm::PointerType::get().
Referenced by AreSequentialAccesses(), buildFrameType(), cloneConstantExprWithNewAddressSpace(), cloneInstructionWithNewAddressSpace(), llvm::InstCombiner::combineLoadToNewType(), combineStoreToNewValue(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), createCmpXchgInstFun(), createGlobalFwdRef(), createOrdering(), llvm::createThreadSanitizerLegacyPassPass(), llvm::orc::IRSpeculationLayer::emit(), llvm::HexagonTargetLowering::emitLoadLinked(), emitSetSwiftErrorValue(), llvm::HexagonTargetLowering::emitStoreConditional(), findUnwindDestinations(), getAdjustedPtr(), llvm::ConstantExpr::getAlignOf(), llvm::IRTranslator::getAnalysisUsage(), getDoublePtrTy(), getFloatPtrTy(), getFP128PtrTy(), llvm::ConstantExpr::getGetElementPtr(), getHalfPtrTy(), getInt16PtrTy(), getInt1PtrTy(), getInt32PtrTy(), getInt64PtrTy(), getInt8PtrTy(), getIntNPtrTy(), getIntrinsicParamType(), getPPC_FP128PtrTy(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), getScalarTy(), getTypePartition(), getX86_FP80PtrTy(), getX86_MMXPtrTy(), INITIALIZE_PASS(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerLoadRelative(), lowerSubFn(), llvm::coro::LowererBase::makeSubFnCall(), operandWithNewAddressSpaceOrCreateUndef(), optimizeMemCmpConstantSize(), patchAndReplaceAllUsesWith(), RetagMask(), scalarizeMaskedLoad(), scalarizeMaskedStore(), shouldKeepInEntry(), SimplifyRelativeLoad(), splitMergedValStore(), tryPromoteAllocaToVector(), tryToElideArgumentCopy(), UseTlsOffset(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), and llvm::sroa::AllocaSliceRewriter::visit().
getPPC_FP128PtrTy()
PointerType * Type::getPPC_FP128PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 208 of file Type.cpp.
References getPointerTo(), and getPPC_FP128Ty().
Referenced by getScalarTy().
getPPC_FP128Ty()
Type * Type::getPPC_FP128Ty (LLVMContext & C) static
Definition at line 174 of file Type.cpp.
References llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::PPC_FP128Ty.
Referenced by llvm::ConstantFP::get(), getPointerElementType(), getPPC_FP128PtrTy(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), LLVMPPCFP128TypeInContext(), and shrinkFPConstant().
getPrimitiveSizeInBits()
TypeSize Type::getPrimitiveSizeInBits () const
Return the basic size of this type if it is a primitive type.
These are fixed by LLVM and are not target-dependent. This will return zero if the type does not have a size or is not a primitive type.
If this is a scalable vector type, the scalable property will be set and the runtime size will be a positive integer multiple of the base size.
Note that this may not reflect the size of memory allocated for an instance of the type or the number of bytes that are written when an instance of the type is stored to memory. The DataLayout class provides additional query functions to provide this information.
Definition at line 115 of file Type.cpp.
References DoubleTyID, llvm::TypeSize::Fixed(), FloatTyID, FP128TyID, getBitWidth(), llvm::VectorType::getBitWidth(), getTypeID(), HalfTyID, IntegerTyID, llvm::VectorType::isScalable(), PPC_FP128TyID, VectorTyID, X86_FP80TyID, and X86_MMXTyID.
Referenced by llvm::HexagonTargetLowering::allowTruncateForTailCall(), llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::CastInst::castIsValid(), collectInsertionElements(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldLoadFromConstPtr(), createCmpXchgInstFun(), llvm::DecodePSHUFBMask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), despeculateCountZeros(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::RISCVTargetLowering::emitTrailingFence(), evaluateGEPOffsetExpression(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), llvm::extractConstantMask(), foldBitcastExtElt(), foldICmpWithMinMax(), foldVecTruncToExtElt(), FunctionNumber(), llvm::Constant::getAllOnesValue(), GetAnyNonZeroConstInt(), llvm::CastInst::getCastOpcode(), llvm::ExecutionEngine::getConstantValue(), llvm::VectorType::getInteger(), llvm::SystemZTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCost(), llvm::AArch64TTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCost(), llvm::X86TTIImpl::getIntImmCost(), llvm::SystemZTTIImpl::getIntImmCostInst(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::AArch64TTIImpl::getIntImmCostInst(), llvm::X86TTIImpl::getIntImmCostInst(), llvm::SystemZTTIImpl::getIntImmCostIntrin(), llvm::PPCTTIImpl::getIntImmCostIntrin(), llvm::AArch64TTIImpl::getIntImmCostIntrin(), llvm::X86TTIImpl::getIntImmCostIntrin(), getIntrinsicForMaskedAtomicRMWBinOp(), getIntToFPVal(), llvm::MemoryDependenceResults::getLoadLoadClobberFullWidthSize(), getLoopOperandSizeInBytes(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMemoryOpCost(), getNoopInput(), getOpenCLAlignment(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::NVPTXTargetLowering::getPrototype(), getScalarSizeInBits(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), getTargetConstantBitsFromNode(), llvm::VectorType::getTruncatedElementVectorType(), getTypeSizeIndex(), llvm::X86TTIImpl::getUserCost(), llvm::SystemZTTIImpl::getVectorTruncCost(), INITIALIZE_PASS(), llvm::CastInst::isBitCastable(), llvm::CastInst::isCastable(), IsInterestingCmp(), llvm::ARMTTIImpl::isLegalMaskedLoad(), isMultipleOfTypeSize(), isObjectSize(), isPromotedResultSafe(), isSized(), llvm::RISCVTargetLowering::isTruncateFree(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::ARMTargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::NVPTXTargetLowering::isTruncateFree(), llvm::PPCTargetLowering::isTruncateFree(), llvm::X86TargetLowering::isTruncateFree(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), llvm::AArch64TargetLowering::isZExtFree(), LinearizeExprTree(), LowerCTLZ(), LowerCTPOP(), LowerRotate(), mapBinOpcode(), optimizeVectorResizeWithIntegerBitCasts(), performMaskedAtomicOp(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::replaceAllDbgUsesWith(), llvm::SCEVExpander::replaceCongruentIVs(), scalarConstantToHexString(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::ARMTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::PPCTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::X86TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::HexagonTargetLowering::shouldExpandAtomicLoadInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicLoadInIR(), llvm::ARMTargetLowering::shouldExpandAtomicLoadInIR(), llvm::SparcTargetLowering::shouldExpandAtomicRMWInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicRMWInIR(), llvm::ARMTargetLowering::shouldExpandAtomicRMWInIR(), llvm::HexagonTargetLowering::shouldExpandAtomicStoreInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicStoreInIR(), llvm::ARMTargetLowering::shouldExpandAtomicStoreInIR(), SimplifyICmpInst(), simplifyX86pack(), SwitchToLookupTable(), upgradeAVX512MaskToSelect(), UpgradeX86VPERMT2Intrinsics(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::InstCombiner::visitPHINode(), and llvm::InstCombiner::visitTrunc().
getPrimitiveType()
Type * Type::getPrimitiveType (LLVMContext & C, TypeID IDNumber) static
Return a type based on an identifier.
Definition at line 39 of file Type.cpp.
References DoubleTyID, FloatTyID, FP128TyID, getDoubleTy(), getFloatTy(), getFP128Ty(), getHalfTy(), getLabelTy(), getMetadataTy(), getPPC_FP128Ty(), getTokenTy(), getVoidTy(), getX86_FP80Ty(), getX86_MMXTy(), HalfTyID, LabelTyID, MetadataTyID, PPC_FP128TyID, TokenTyID, VoidTyID, X86_FP80TyID, and X86_MMXTyID.
Referenced by getPointerElementType().
getScalarSizeInBits()
unsigned Type::getScalarSizeInBits () const
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
Otherwise return the getPrimitiveSizeInBits value for this type.
Definition at line 134 of file Type.cpp.
References getPrimitiveSizeInBits(), and getScalarType().
Referenced by areExtractExts(), areInverseVectorBitmasks(), canEvaluateSExtd(), canEvaluateShiftedShift(), canEvaluateTruncated(), canEvaluateZExtd(), canNarrowShiftAmt(), llvm::InstCombiner::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeSaturatedAdd(), canTailPredicateLoop(), llvm::CastInst::castIsValid(), llvm::computeConstantRange(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::computeOverflowForSignedMul(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldGetElementPtr(), llvm::convertPointerToIntegerType(), llvm::createAMDGPUPrintfRuntimeBinding(), createAndInstr(), llvm::CastInst::CreateFPCast(), llvm::CastInst::CreateIntegerCast(), llvm::CastInst::CreateSExtOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateSExtOrTrunc(), llvm::CastInst::CreateTruncOrBitCast(), llvm::CastInst::CreateZExtOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateZExtOrTrunc(), llvm::decomposeBitTestICmp(), llvm::NVPTXAsmPrinter::doFinalization(), dropRedundantMaskingOfLeftShiftInput(), llvm::extractConstantMask(), foldAnyOrAllBitsSet(), foldBitcastExtElt(), foldGuardedRotateToFunnelShift(), foldICmpShlOne(), foldICmpWithTruncSignExtendedVal(), foldICmpWithZextOrSext(), llvm::InstCombiner::FoldItoFPtoI(), foldNoWrapAdd(), foldSelectICmpAndOr(), foldSelectICmpLshrAshr(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedLogic(), foldSignedTruncationCheck(), llvm::InstCombiner::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVecTruncToExtElt(), generatePoisonChecksForBinOp(), GenerateSignBits(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), getBitWidth(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::ExecutionEngine::getConstantValue(), getElSizeLog2Diff(), llvm::IntegerType::getExtendedType(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::ConstantExpr::getFPTrunc(), llvm::ConstantExpr::getIntegerCast(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getLoadVectorFactor(), llvm::SystemZTTIImpl::getMemoryOpCost(), getMulHu(), llvm::TargetTransformInfoImplBase::getOperationCost(), getParentPad(), llvm::AArch64TTIImpl::getPopcntSupport(), getRelevantOperands(), getScalarSizeInBits(), getSelectFoldableConstant(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSExtOrBitCast(), getSubprogram(), getTargetConstantBitsFromNode(), llvm::ConstantExpr::getTrunc(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::SystemZTTIImpl::getVectorTruncCost(), getVectorType(), llvm::getWiderType(), llvm::ConstantExpr::getZExt(), llvm::ConstantExpr::getZExtOrBitCast(), INITIALIZE_PASS(), llvm::RuntimePointerChecking::insert(), insertValues(), llvm::CastInst::isEliminableCastPair(), llvm::SystemZTTIImpl::isFoldableLoad(), isKnownToBeAPowerOfTwo(), llvm::ARMTTIImpl::isLegalMaskedGather(), llvm::ARMTTIImpl::isLegalMaskedLoad(), llvm::CastInst::isNoopCast(), isPromotedResultSafe(), isSized(), llvm::AMDGPUTargetLowering::isTruncateFree(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), llvm::AMDGPUTargetLowering::isZExtFree(), llvm::log2(), LowerBSWAP(), matchRotate(), mayUsePostIncMode(), llvm::TargetTransformInfoImplBase::minRequiredElementSize(), processUGT_ADDCST_ADD(), propagateMetadata(), llvm::InstCombiner::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::DemandedBitsWrapperPass::releaseMemory(), llvm::InstCombiner::replacedSelectWithOperand(), llvm::salvageDebugInfoImpl(), setLimitsForSelectPattern(), ShrinkDemandedConstant(), SimplifyAndInst(), SimplifyAShrInst(), SimplifyLShrInst(), simplifyX86pack(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), tryToRecognizePopCount(), upgradeAVX512MaskToSelect(), UpgradeX86VPERMT2Intrinsics(), llvm::ARMTTIImpl::useReductionIntrinsic(), llvm::AArch64TTIImpl::useReductionIntrinsic(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPtrToInt(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), and llvm::reassociate::XorOpnd::XorOpnd().
getScalarTy()
template<typename ScalarTy > static Type* llvm::Type::getScalarTy (LLVMContext & C) inline static
Definition at line 426 of file Type.h.
References getDoublePtrTy(), getDoubleTy(), getFloatPtrTy(), getFloatTy(), getFP128PtrTy(), getHalfPtrTy(), getInt16PtrTy(), getInt1PtrTy(), getInt32PtrTy(), getInt64PtrTy(), getInt8PtrTy(), getIntNPtrTy(), getIntNTy(), getPointerTo(), getPPC_FP128PtrTy(), getX86_FP80PtrTy(), getX86_MMXPtrTy(), and llvm_unreachable.
getScalarType()
Type* llvm::Type::getScalarType () const inline
If this is a vector type, return the element type, otherwise return 'this'.
Definition at line 307 of file Type.h.
References getVectorElementType(), and isVectorTy().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingLoad(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), llvm::VNCoercion::analyzeLoadFromClobberingStore(), buildNew(), llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::VNCoercion::canCoerceMustAliasedValueToLoad(), canConvertValue(), canonicalizeSaturatedAdd(), llvm::CastInst::castIsValid(), computeKnownBits(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), concatenateTwoVectors(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::GetElementPtrInst::Create(), createPowWithIntegerExponent(), evaluateInDifferentElementOrder(), llvm::InnerLoopVectorizer::fixReduction(), foldBitcastExtElt(), FunctionNumber(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticInstrCost(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), getChainID(), getCmpOpsType(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost(), llvm::DemandedBits::getDemandedBits(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::ConstantExpr::getGetElementPtr(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::ConstantFP::getInfinity(), llvm::Constant::getIntegerValue(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), getLogBase2(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::ConstantFP::getNaN(), llvm::ConstantFP::getNegativeZero(), getParameterABIAttributes(), getParentPad(), getPointerAddressSpace(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::ConstantFP::getQNaN(), llvm::PPCTTIImpl::getRegisterClassForType(), getScalarIntrinsicDeclaration(), getScalarSizeInBits(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), llvm::ConstantFP::getSNaN(), llvm::InnerLoopVectorizer::getStepVector(), llvm::PPCTTIImpl::getUserCost(), llvm::X86TTIImpl::getUserCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getVectorInstrCost(), GlobalWasGeneratedByCompiler(), hasSameExtUse(), llvm::haveNoCommonBitsSet(), llvm::CastInst::isEliminableCastPair(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), isFPOrFPVectorTy(), isIntOrIntVectorTy(), isKnownNonZero(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), isPtrOrPtrVectorTy(), llvm::Instruction::isSameOperationAs(), isStrideMul(), LinearizeExprTree(), LLVMBuildGEP(), LLVMBuildInBoundsGEP(), LLVMBuildStructGEP(), LLVMConstGEP(), LLVMConstInBoundsGEP(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundle(), lowerStatepointMetaArgs(), propagateMetadata(), llvm::InstCombiner::replacedSelectWithOperand(), llvm::HWAddressSanitizerPass::run(), shouldInstrumentReadWriteFromAddress(), shouldKeepFDivF32(), shouldMergeGEPs(), shrinkInsertElt(), upgradeX86ConcatShift(), upgradeX86Rotate(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFCmpInst(), and llvm::InstCombiner::visitGetElementPtrInst().
getSequentialElementType()
Type* llvm::Type::getSequentialElementType () const inline
Definition at line 361 of file Type.h.
References assert(), getArrayNumElements(), getTypeID(), and isSequentialType().
Referenced by llvm::ConstantFoldLoadThroughBitcast(), and llvm::ConstantDataSequential::getImpl().
getStructElementType()
Type * llvm::Type::getStructElementType (unsigned N) const inline
Definition at line 370 of file DerivedTypes.h.
Referenced by llvm::canConstantFoldCallTo(), createCast(), getNumContainedTypes(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), isConstantUsingVectorTy(), originalTypeIsF128(), simplifyBinaryIntrinsic(), and simplifyX86addcarry().
getStructName()
StringRef llvm::Type::getStructName () const inline
Definition at line 362 of file DerivedTypes.h.
References getName().
Referenced by getNumContainedTypes(), and false::operator<<().
getStructNumElements()
unsigned llvm::Type::getStructNumElements () const inline
Definition at line 366 of file DerivedTypes.h.
Referenced by createCast(), getAggregateNumElements(), getNumContainedTypes(), llvm::ConstantAggregateZero::getNumElements(), llvm::UndefValue::getNumElements(), isConstantUsingVectorTy(), and originalTypeIsF128().
getSubclassData()
unsigned llvm::Type::getSubclassData () const inline protected
Definition at line 95 of file Type.h.
Referenced by llvm::PointerType::getAddressSpace(), llvm::IntegerType::getBitWidth(), llvm::StructType::isLiteral(), llvm::StructType::isOpaque(), llvm::StructType::isPacked(), llvm::StructType::isSized(), llvm::FunctionType::isVarArg(), llvm::StructType::setBody(), and setSubclassData().
getTokenTy()
Type * Type::getTokenTy (LLVMContext & C) static
Definition at line 171 of file Type.cpp.
References llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TokenTy.
Referenced by DecodeFixedType(), getPointerElementType(), getPrimitiveType(), LLVMBuildCatchSwitch(), LLVMBuildCleanupPad(), and LLVMTokenTypeInContext().
getTypeID()
TypeID llvm::Type::getTypeID () const inline
Return the type id for the type.
This will return one of the TypeID enum elements defined above.
Definition at line 138 of file Type.h.
Referenced by canLosslesslyBitCastTo(), llvm::IntegerType::classof(), llvm::FunctionType::classof(), llvm::CompositeType::classof(), llvm::StructType::classof(), llvm::SequentialType::classof(), llvm::ArrayType::classof(), llvm::VectorType::classof(), llvm::PointerType::classof(), llvm::FunctionComparator::cmpTypes(), ConvertDoubleToBytes(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::isa_impl< PointerType, Type >::doit(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), executeFAddInst(), executeFCMP_OEQ(), executeFCMP_OGE(), executeFCMP_OGT(), executeFCMP_OLE(), executeFCMP_OLT(), executeFCMP_ONE(), executeFDivInst(), executeFMulInst(), executeFNegInst(), executeFRemInst(), executeFSubInst(), executeICMP_EQ(), executeICMP_NE(), executeICMP_SGE(), executeICMP_SGT(), executeICMP_SLE(), executeICMP_SLT(), executeICMP_UGE(), executeICMP_UGT(), executeICMP_ULE(), executeICMP_ULT(), getArrayElementType(), getAttrKindEncoding(), llvm::ExecutionEngine::getConstantValue(), llvm::EVT::getEVT(), llvm::getFloatFnName(), getFltSemantics(), llvm::ConstantExpr::getFPExtend(), getFPMantissaWidth(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), llvm::DataLayout::getIndexTypeSizeInBits(), getMangledTypeStr(), llvm::Constant::getNullValue(), getOpenCLAlignment(), getPointerElementType(), getPrimitiveSizeInBits(), llvm::NVPTXTargetLowering::getPrototype(), getSequentialElementType(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSIToFP(), llvm::ConstantExpr::getTrunc(), llvm::VectorType::getTruncatedElementVectorType(), getTypeID(), llvm::DataLayout::getTypeSizeInBits(), llvm::ConstantExpr::getUIToFP(), getVectorElementType(), llvm::MVT::getVT(), llvm::ConstantExpr::getZExt(), llvm::hasFloatFn(), isAggregateType(), isArrayTy(), isDoubleTy(), isFirstClassType(), isFloatingPointTy(), isFloatTy(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), isFP128Ty(), isFunctionTy(), isHalfTy(), isIntegerTy(), isLabelTy(), isLeakCheckerRoot(), llvm::XCoreTargetLowering::isLegalAddressingMode(), isMetadataTy(), isPointerTy(), isPPC_FP128Ty(), isSized(), isStructTy(), isTokenTy(), llvm::ConstantFP::isValueValidForType(), isVectorTy(), isVoidTy(), isX86_FP80Ty(), isX86_MMXTy(), llvm::ExecutionEngine::LoadValueFromMemory(), lookupFunction(), needsFPFromSig(), needsFPStubFromParams(), PrintLLVMName(), ReplaceFPIntrinsicWithCall(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection(), llvm::ExecutionEngine::StoreValueToMemory(), llvm::Interpreter::visitAShr(), llvm::Interpreter::visitExtractElementInst(), llvm::Interpreter::visitExtractValueInst(), VisitGlobalVariableForEmission(), llvm::Interpreter::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::Interpreter::visitShuffleVectorInst(), llvm::Interpreter::visitVAArgInst(), whichFPParamVariantNeeded(), and whichFPReturnVariant().
getVectorElementCount()
ElementCount llvm::Type::getVectorElementCount () const inline
Definition at line 574 of file DerivedTypes.h.
Referenced by getArrayElementType(), llvm::ConstantExpr::getShuffleVector(), and getWithNewBitWidth().
getVectorElementType()
Type* llvm::Type::getVectorElementType () const inline
Definition at line 376 of file Type.h.
References assert(), getTypeID(), and VectorTyID.
Referenced by llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::createSimpleTargetReduction(), DecodeFixedType(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::extractConstantMask(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::ConstantExpr::getExtractElement(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::ConstantExpr::getInsertElement(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::getSafeVectorConstantForBinop(), getScalarType(), llvm::X86TTIImpl::getShuffleCost(), llvm::ConstantExpr::getShuffleVector(), llvm::X86TTIImpl::getUserCost(), llvm::ARMTTIImpl::getVectorInstrCost(), group2Shuffle(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::AArch64TTIImpl::isLegalMaskedLoadStore(), largestIntegerVectorType(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), matchIntrinsicType(), scalarizeMaskedCompressStore(), scalarizeMaskedScatter(), ShrinkDemandedConstant(), SimplifyExtractElementInst(), smallestIntegerVectorType(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitInsertElementInst(), and WriteConstantInternal().
getVectorIsScalable()
bool llvm::Type::getVectorIsScalable () const inline
Definition at line 570 of file DerivedTypes.h.
Referenced by combineLoadToOperationType(), generatePoisonChecks(), getArrayElementType(), and llvm::FunctionLoweringInfo::set().
getVectorNumElements()
unsigned llvm::Type::getVectorNumElements () const inline
Definition at line 566 of file DerivedTypes.h.
Referenced by ApplyX86MaskOn1BitsVec(), areInverseVectorBitmasks(), BitCastConstantVector(), canEvaluateShuffled(), canNarrowShiftAmt(), canonicalizeInsertSplat(), llvm::ShuffleVectorInst::changesLength(), collectShuffleElements(), collectSingleShuffleElements(), llvm::ShuffleVectorInst::commute(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::CastInst::CreatePointerCast(), DecodeFixedType(), EmitX86Select(), llvm::extractConstantMask(), findDemandedEltsByAllUsers(), findDemandedEltsBySingleUser(), llvm::findScalarElement(), foldBitcastExtElt(), foldConstantInsEltIntoShuffle(), foldICmpShlOne(), foldICmpWithLowBitMaskedVal(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIdentityShuffles(), foldInsEltIntoSplat(), foldSelectShuffle(), foldShuffleWithInsert(), FunctionNumber(), generatePoisonChecks(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticReductionCost(), getArrayElementType(), llvm::SystemZTTIImpl::getBoolVecToIntConversionCost(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::SystemZTTIImpl::getInterleavedMemoryOpCost(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::ConstantExpr::getIntToPtr(), getLogBase2(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::ConstantDataSequential::getNumElements(), getNumVectorRegs(), getOffsetFromIndices(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperandsScalarizationOverhead(), llvm::getOrderedReduction(), getParameterABIAttributes(), llvm::AArch64TTIImpl::getPopcntSupport(), llvm::ConstantExpr::getPtrToInt(), llvm::getSafeVectorConstantForBinop(), getScalarIntrinsicDeclaration(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getScalarizationOverhead(), llvm::X86TTIImpl::getShuffleCost(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::getShuffleReduction(), llvm::InnerLoopVectorizer::getStepVector(), llvm::X86TTIImpl::getUserCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::SystemZTTIImpl::getVectorTruncCost(), group2Shuffle(), llvm::ShuffleVectorInst::increasesLength(), INITIALIZE_PASS(), llvm::ShuffleVectorInst::isConcat(), isConstantIntVector(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::ShuffleVectorInst::isIdentityWithExtract(), llvm::ShuffleVectorInst::isIdentityWithPadding(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverNaN(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), isReInterleaveMask(), isShuffleEquivalentToSelect(), isShuffleExtractingFromLHS(), isUndefShift(), isVectorReductionOp(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), matchIntrinsicType(), matchPairwiseReduction(), matchPairwiseShuffleMask(), matchVectorSplittingReduction(), processUGT_ADDCST_ADD(), replaceExtractElements(), llvm::Constant::replaceUndefsWith(), scalarConstantToHexString(), scalarizeMaskedScatter(), shouldMergeGEPs(), ShrinkDemandedConstant(), shrinkFPConstantVector(), simplifyDivRem(), SimplifyExtractElementInst(), SimplifyShuffleVectorInst(), simplifyX86movmsk(), simplifyX86pack(), simplifyX86vpermilvar(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), upgradeMaskedCompare(), UpgradeMaskedLoad(), UpgradeMaskedStore(), UpgradeMaskToInt(), UpgradeX86ALIGNIntrinsics(), upgradeX86ConcatShift(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), upgradeX86Rotate(), llvm::ARMTTIImpl::useReductionIntrinsic(), llvm::AArch64TTIImpl::useReductionIntrinsic(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitPtrToInt(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), and WriteConstantInternal().
getVoidTy()
Type * Type::getVoidTy (LLVMContext & C) static
Definition at line 165 of file Type.cpp.
References llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::VoidTy.
Referenced by AddCalls(), addStackMapLiveVars(), buildFrameType(), llvm::CallBrInst::Create(), createCallInst(), createDevirtTriggerFunc(), llvm::MIRParserImpl::createDummyFunction(), llvm::createDwarfEHPass(), createEmptyFunction(), createFree(), llvm::createMemLibcall(), CreatePrologue(), llvm::createSanitizerCtorAndInitFunctions(), llvm::createX86RetpolineThunksPass(), llvm::declareSanitizerInitFunction(), DecodeFixedType(), llvm::orc::IRSpeculationLayer::emit(), EmitInlineAsm(), llvm::CodeExtractor::findInputsOutputs(), llvm::SanitizerStatReport::finish(), fixupFPReturnAndCall(), forEachUser(), llvm::getOrCreateInitFunction(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), getOrInsertValueProfilingCall(), getPointerElementType(), getPrimitiveType(), getRetComponentType(), GetRMWLibcall(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::EVT::getTypeForEVT(), getUnderlyingObjects(), llvm::IRBuilderBase::getVoidTy(), INITIALIZE_PASS(), insertCall(), InsertSafepointPoll(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), insertUseHolderAfter(), instrumentMaskedLoadOrStore(), isCalleeLoad(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), LLVMVoidTypeInContext(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), makeStatepointExplicitImpl(), MarkBlocksLiveIn(), needsRuntimeRegistrationOfSectionRange(), prepareForSplit(), llvm::ModuleSanitizerCoveragePass::run(), selectJumpTableArmEncoding(), shouldKeepInEntry(), llvm::UnreachableInst::UnreachableInst(), and llvm::Interpreter::visitReturnInst().
getWithNewBitWidth()
Type * llvm::Type::getWithNewBitWidth (unsigned NewBitWidth) const inline
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Definition at line 625 of file DerivedTypes.h.
References assert(), llvm::VectorType::get(), getContext(), getIntNTy(), getVectorElementCount(), isIntOrIntVectorTy(), and isVectorTy().
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), and getPointerElementType().
getX86_FP80PtrTy()
PointerType * Type::getX86_FP80PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 200 of file Type.cpp.
References getPointerTo(), and getX86_FP80Ty().
Referenced by getScalarTy().
getX86_FP80Ty()
Type * Type::getX86_FP80Ty (LLVMContext & C) static
Definition at line 172 of file Type.cpp.
References llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::X86_FP80Ty.
Referenced by llvm::ConstantFP::get(), getPointerElementType(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), getX86_FP80PtrTy(), and LLVMX86FP80TypeInContext().
getX86_MMXPtrTy()
PointerType * Type::getX86_MMXPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 212 of file Type.cpp.
References getPointerTo(), and getX86_MMXTy().
Referenced by getScalarTy().
getX86_MMXTy()
Type * Type::getX86_MMXTy (LLVMContext & C) static
Definition at line 175 of file Type.cpp.
References llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::X86_MMXTy.
Referenced by DecodeFixedType(), getPointerElementType(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), getX86_MMXPtrTy(), and LLVMX86MMXTypeInContext().
isAggregateType()
bool llvm::Type::isAggregateType () const inline
Return true if the type is an aggregate type.
This means it is valid as the first operand of an insertvalue or extractvalue instruction. This includes struct and array types, but does not include vector types.
Definition at line 258 of file Type.h.
References ArrayTyID, getTypeID(), and StructTyID.
Referenced by advanceToNextLeafType(), llvm::CastInst::castIsValid(), llvm::ConstantFoldLoadThroughBitcast(), firstRealType(), FunctionNumber(), getAggregateNumElements(), llvm::IRTranslator::getAnalysisUsage(), llvm::ExecutionEngine::getConstantValue(), getOpenCLAlignment(), llvm::NVPTXTargetLowering::getPrototype(), llvm::SelectionDAGBuilder::getValueImpl(), isSupportedReturnType(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::BPFTargetLowering::LowerOperation(), llvm::InnerLoopVectorizer::scalarizeInstruction(), TypeSizeToSizeIndex(), unpackLoadToAggregate(), unpackStoreToAggregate(), and VisitGlobalVariableForEmission().
isArrayTy()
bool llvm::Type::isArrayTy () const inline
True if this is an instance of ArrayType.
Definition at line 221 of file Type.h.
References ArrayTyID, and getTypeID().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingLoad(), llvm::VNCoercion::analyzeLoadFromClobberingWrite(), llvm::VNCoercion::canCoerceMustAliasedValueToLoad(), EvaluateStoreInto(), llvm::FindInsertedValue(), forEachUser(), llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::AArch64TargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), FunctionNumber(), llvm::ConstantAggregateZero::get(), getTypePartition(), llvm::SelectionDAGBuilder::getValueImpl(), isArray(), isConstantUsingVectorTy(), llvm::SCEVUnknown::isOffsetOf(), isSupportedType(), optimizeBinaryDoubleFP(), and llvm::InstCombiner::visitGetElementPtrInst().
isDoubleTy()
bool llvm::Type::isDoubleTy () const inline
Return true if this is 'double', a 64-bit IEEE fp type.
Definition at line 150 of file Type.h.
References DoubleTyID, and getTypeID().
Referenced by appendTypeSuffix(), llvm::canConstantFoldCallTo(), CC_MipsO32_FP64(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::createAMDGPUPrintfRuntimeBinding(), createPowWithIntegerExponent(), emitDebugValueComment(), llvm::Mips16TargetLowering::EmitInstrWithCustomInserter(), emitSignedInt64(), getComparePred(), llvm::ExecutionEngine::getConstantValue(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), getIntToFPVal(), llvm::ARMTTIImpl::getMemoryOpCost(), GetPointerOperand(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::ConstantDataSequential::isElementTypeCompatible(), isHomogeneousAggregate(), llvm::InductionDescriptor::isInductionPHI(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::AArch64TTIImpl::isLegalMaskedLoadStore(), llvm::X86TTIImpl::isLegalNTStore(), llvm::ARMTTIImpl::isLoweredToCall(), llvm::isMathLibCallNoop(), llvm::log2(), llvm::WebAssemblyMCInstLower::lower(), matchIntrinsicType(), optimizeDoubleFP(), shrinkFPConstant(), TypeToFloatSemantics(), llvm::Interpreter::visitAShr(), and whichFPReturnVariant().
isEmptyTy()
bool Type::isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
Definition at line 98 of file Type.cpp.
Referenced by areGlobalsPotentiallyEqual(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), isVectorTy(), llvm::FastISel::lowerCallTo(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), and llvm::FastISel::selectStackmap().
isFirstClassType()
bool llvm::Type::isFirstClassType () const inline
Return true if the type is "first class", meaning it is a valid type for a Value.
Definition at line 244 of file Type.h.
References FunctionTyID, getTypeID(), and VoidTyID.
Referenced by canLosslesslyBitCastTo(), canTrapImpl(), llvm::CastInst::castIsValid(), llvm::FunctionComparator::cmpConstants(), foldConstantCastPair(), FunctionNumber(), llvm::CastInst::getCastOpcode(), llvm::ConstantExpr::getExtractValue(), getFoldedCast(), llvm::ConstantExpr::getInsertValue(), getParentPad(), llvm::ExecutionEngine::InitializeMemory(), llvm::CastInst::isBitCastable(), llvm::CastInst::isCastable(), llvm::FunctionType::isValidArgumentType(), parseOptionalLinkageAux(), and llvm::Value::Value().
isFloatingPointTy()
bool llvm::Type::isFloatingPointTy () const inline
Return true if this is one of the six floating-point types.
Definition at line 162 of file Type.h.
References DoubleTyID, FloatTyID, FP128TyID, getTypeID(), HalfTyID, PPC_FP128TyID, and X86_FP80TyID.
Referenced by llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createCmpXchgInstFun(), llvm::NVPTXAsmPrinter::doFinalization(), FoldBitCast(), foldBitcastExtElt(), FunctionNumber(), llvm::Constant::getAllOnesValue(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::CastInst::getCastOpcode(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::ExecutionEngine::getConstantValue(), getFPMantissaWidth(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionLatency(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::NVPTXTargetLowering::getPrototype(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::MipsCCState::getSpecialCallingConvForCallee(), llvm::InnerLoopVectorizer::getStepVector(), llvm::VectorType::getTruncatedElementVectorType(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::CastInst::isCastable(), isContiguous(), llvm::CastInst::isEliminableCastPair(), llvm::InductionDescriptor::isFPInductionPHI(), isFPOrFPVectorTy(), llvm::InductionDescriptor::isInductionPHI(), isSingleValueType(), isSized(), isSupportedArgumentType(), isSupportedAtomicType(), isSupportedReturnType(), llvm::LoopVectorizationLegality::isUniform(), llvm::VectorType::isValidElementType(), llvm::NVPTXTargetLowering::LowerCall(), llvm::fuzzerop::makeConstantsWithType(), parsePredicateConstraint(), performAtomicOp(), supportedAddressingMode(), TryToShrinkGlobalToBoolean(), UpgradeIntrinsicFunction1(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitAtomicRMWInst(), and VisitGlobalVariableForEmission().
isFloatTy()
bool llvm::Type::isFloatTy () const inline
Return true if this is 'float', a 32-bit IEEE fp type.
Definition at line 147 of file Type.h.
References FloatTyID, and getTypeID().
Referenced by appendTypeSuffix(), llvm::canConstantFoldCallTo(), CC_MipsO32_FP64(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::createAMDGPUPrintfRuntimeBinding(), createPowWithIntegerExponent(), emitDebugValueComment(), llvm::Mips16TargetLowering::EmitInstrWithCustomInserter(), emitSignedInt64(), executeFCMP_ORD(), executeFCMP_UNO(), FunctionNumber(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), getComparePred(), llvm::ExecutionEngine::getConstantValue(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), getIntToFPVal(), GetPointerOperand(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), insertSinCosCall(), llvm::ConstantDataSequential::isElementTypeCompatible(), isHomogeneousAggregate(), llvm::InductionDescriptor::isInductionPHI(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::AArch64TTIImpl::isLegalMaskedLoadStore(), llvm::X86TTIImpl::isLegalNTStore(), llvm::isMathLibCallNoop(), llvm::WebAssemblyMCInstLower::lower(), matchIntrinsicType(), optimizeDoubleFP(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), shouldKeepFDivF32(), TypeToFloatSemantics(), UnpackFromArgumentSlot(), valueHasFloatPrecision(), llvm::Interpreter::visitAShr(), and whichFPReturnVariant().
isFP128Ty()
bool llvm::Type::isFP128Ty () const inline
Return true if this is 'fp128'.
Definition at line 156 of file Type.h.
References FP128TyID, and getTypeID().
Referenced by llvm::ConstantFoldCastInstruction(), emitSignedInt64(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::SparcTargetLowering::LowerF128Op(), matchIntrinsicType(), originalTypeIsF128(), and TypeToFloatSemantics().
isFPOrFPVectorTy()
bool llvm::Type::isFPOrFPVectorTy () const inline
Return true if this is a FP type or a vector of FP.
Definition at line 185 of file Type.h.
References getScalarType(), and isFloatingPointTy().
Referenced by llvm::ARMTargetLowering::canCombineStoreAndExtract(), canonicalizeSaturatedAdd(), llvm::CastInst::castIsValid(), llvm::FPMathOperator::classof(), llvm::ConstantFoldCompareInstruction(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::CastInst::CreateFPCast(), FunctionNumber(), llvm::ConstantExpr::get(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getCastInstrCost(), getDecodedBinaryOpcode(), getDecodedUnaryOpcode(), llvm::ConstantExpr::getFNeg(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), getNegatibleInsts(), getParameterABIAttributes(), getParentPad(), llvm::ConstantExpr::getSIToFP(), getSubprogram(), llvm::ConstantExpr::getUIToFP(), llvm::ConstantFP::getZeroValueForNegation(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverNaN(), matchIntrinsicType(), NegateValue(), originalTypeIsVectorFloat(), upgradeAVX512MaskToSelect(), and UpgradeX86VPERMT2Intrinsics().
isFunctionTy()
bool llvm::Type::isFunctionTy () const inline
True if this is an instance of FunctionType.
Definition at line 215 of file Type.h.
References FunctionTyID, and getTypeID().
Referenced by callingConvSupported(), llvm::convertToDeclaration(), llvm::AsmPrinter::emitGlobalGOTEquivs(), llvm::emitLinkerFlagsForGlobalCOFF(), forceRenaming(), FunctionNumber(), llvm::GlobalVariable::GlobalVariable(), llvm::PointerType::isLoadableOrStorableType(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::FunctionType::isValidReturnType(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), maybeSetDSOLocal(), llvm::XCoreTargetLowering::ReplaceNodeResults(), and llvm::SITargetLowering::shouldEmitGOTReloc().
isFunctionVarArg()
bool llvm::Type::isFunctionVarArg () const inline
Definition at line 154 of file DerivedTypes.h.
Referenced by getNumContainedTypes().
isHalfTy()
bool llvm::Type::isHalfTy () const inline
Return true if this is 'half', a 16-bit IEEE fp type.
Definition at line 144 of file Type.h.
References getTypeID(), and HalfTyID.
Referenced by llvm::canConstantFoldCallTo(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldLoadThroughBitcast(), emitSignedInt64(), FunctionNumber(), getOpenCLAlignment(), llvm::NVPTXTargetLowering::getPrototype(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::ConstantDataSequential::isElementTypeCompatible(), llvm::InductionDescriptor::isInductionPHI(), llvm::ARMTargetLowering::isLegalInterleavedAccessType(), llvm::AArch64TTIImpl::isLegalMaskedLoadStore(), llvm::ARMTTIImpl::isLoweredToCall(), llvm::isMathLibCallNoop(), matchIntrinsicType(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), and TypeToFloatSemantics().
isIntegerTy() [1/2]
bool llvm::Type::isIntegerTy () const inline
True if this is an instance of IntegerType.
Definition at line 197 of file Type.h.
References getTypeID(), and IntegerTyID.
Referenced by llvm::HexagonTargetLowering::allowTruncateForTailCall(), llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::VNCoercion::analyzeLoadFromClobberingLoad(), annotateNonNullAndDereferenceable(), AreSequentialAccesses(), llvm::InnerLoopVectorizer::buildScalarSteps(), canConvertValue(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), combineLoadToOperationType(), llvm::InstCombiner::commonCastTransforms(), llvm::computeMinimumValueSizes(), llvm::ComputeMultiple(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), ComputePTXValueVTs(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::CastInst::CreateBitOrPointerCast(), createCast(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::X86TargetLowering::ExpandInlineAsm(), ExtractConstantBytes(), llvm::extractConstantMask(), llvm::InnerLoopVectorizer::fixupIVUsers(), FoldBitCast(), FoldCondBranchOnPHI(), FoldTwoEntryPHINode(), forEachUser(), llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), FunctionNumber(), genLoopLimit(), getAdjustedPtr(), getAISize(), getAllocationDataForFunction(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::CastInst::getCastOpcode(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), getCompareCC(), getComparePred(), llvm::getConstantDataArrayInfo(), llvm::LazyValueInfo::getConstantRange(), llvm::ExecutionEngine::getConstantValue(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::ConstantExpr::getExtractElement(), getFromRangeMetadata(), llvm::DataLayout::getIndexedOffsetInType(), llvm::ConstantExpr::getInsertElement(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::SystemZTTIImpl::getIntImmCost(), llvm::RISCVTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCost(), llvm::LanaiTTIImpl::getIntImmCost(), llvm::AArch64TTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCost(), llvm::X86TTIImpl::getIntImmCost(), llvm::SystemZTTIImpl::getIntImmCostInst(), llvm::RISCVTTIImpl::getIntImmCostInst(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::AArch64TTIImpl::getIntImmCostInst(), llvm::X86TTIImpl::getIntImmCostInst(), llvm::SystemZTTIImpl::getIntImmCostIntrin(), llvm::PPCTTIImpl::getIntImmCostIntrin(), llvm::AArch64TTIImpl::getIntImmCostIntrin(), llvm::X86TTIImpl::getIntImmCostIntrin(), getLoadStoreAddrMode(), llvm::VNCoercion::getLoadValueForLoad(), getMaskedTypeForICmpPair(), getMaxBackedgeTakenCount(), llvm::AArch64TTIImpl::getMemoryOpCost(), getMulHu(), getNaturalGEPWithOffset(), getNegatibleInsts(), getNegativeIsTrueBoolVec(), getOpenCLAlignment(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), GetPointerOperand(), llvm::NVPTXTargetLowering::getPrototype(), getSignedIntOrFpConstant(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::InnerLoopVectorizer::getStepVector(), getTypePartition(), getUnderlyingObjectFromInt(), getValueFromICmpCondition(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::HexagonTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::hasIterationCountInvariantInParent(), llvm::HexagonEvaluator::HexagonEvaluator(), AAValueConstantRangeFloating::initialize(), isAtomic(), llvm::isBytewiseValue(), llvm::CastInst::isCastable(), isConstantFalse(), isContiguous(), llvm::CastInst::isEliminableCastPair(), isFuncOrArgAttr(), llvm::isGEPBasedOnPointerToString(), llvm::isImpliedCondition(), llvm::InductionDescriptor::isInductionPHI(), llvm::CastInst::isIntegerCast(), isIntegerLoopHeaderPHI(), isIntegerTy(), isIntExtFree(), isIntOrIntVectorTy(), isIntOrPtrTy(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::AArch64TTIImpl::isLegalMaskedLoadStore(), isObjectSize(), isOnlyReachableViaThisEdge(), isPromotedInstructionLegal(), isReportingError(), isSafeAndProfitableToSinkLoad(), isSingleValueType(), isSupportedArgumentType(), isSupportedReturnType(), llvm::RISCVTargetLowering::isTruncateFree(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::ARMTargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::NVPTXTargetLowering::isTruncateFree(), llvm::PPCTargetLowering::isTruncateFree(), llvm::X86TargetLowering::isTruncateFree(), llvm::LoopVectorizationLegality::isUniform(), llvm::VectorType::isValidElementType(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ConstantInt::isValueValidForType(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), llvm::MSP430TargetLowering::isZExtFree(), llvm::AArch64TargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), llvm::log2(), llvm::NVPTXTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerConstantPool(), LowerCTPOP(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::IntrinsicLowering::LowerToByteSwap(), makeBitReverse(), matchIntrinsicType(), memVTFromAggregate(), originalTypeIsF128(), llvm::replaceAllDbgUsesWith(), replaceAllUsesOfWithIn(), llvm::SCEVExpander::replaceCongruentIVs(), ReplaceUsesOfWith(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::ARMTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::PPCTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::X86TargetLowering::shouldConvertConstantLoadToIntImm(), shouldKeepInEntry(), simplifyAllocaArraySize(), simplifyX86addcarry(), AllocaSlices::SliceBuilder::SliceBuilder(), SolveQuadraticAddRecRange(), splitMergedValStore(), llvm::AttributeFuncs::typeIncompatible(), UnpackFromArgumentSlot(), llvm::UnrollRuntimeLoopRemainder(), updatePredecessorProfileMetadata(), UpgradeX86IntrinsicsWith8BitMask(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::InstCombiner::visitBitCast(), VisitGlobalVariableForEmission(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitReturnInst(), llvm::InstCombiner::visitTrunc(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and X86ChooseCmpImmediateOpcode().
isIntegerTy() [2/2]
bool Type::isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
Definition at line 57 of file Type.cpp.
References getBitWidth(), and isIntegerTy().
isIntOrIntVectorTy() [1/2]
bool llvm::Type::isIntOrIntVectorTy () const inline
Return true if this is an integer type or a vector of integer types.
Definition at line 203 of file Type.h.
References getScalarType(), and isIntegerTy().
Referenced by areInverseVectorBitmasks(), buildMultiplyTree(), canonicalizeICmpBool(), llvm::CastInst::castIsValid(), clearAssumptionsOfUsers(), llvm::InstCombiner::commonIDivTransforms(), llvm::computeConstantRange(), computeKnownBits(), llvm::ConstantFoldGetElementPtr(), convertValue(), CreateAdd(), createAndInstr(), llvm::IRBuilder< TargetFolder >::CreateBitOrPointerCast(), llvm::CastInst::CreateIntegerCast(), CreateMul(), CreateNeg(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilder< TargetFolder >::CreateSExtOrTrunc(), llvm::IRBuilder< TargetFolder >::CreateZExtOrTrunc(), foldBitCastBitwiseLogic(), foldLogicCastConstant(), foldOperationIntoSelectOperand(), foldSelectICmpAndOr(), foldSelectICmpLshrAshr(), foldXorToXor(), FunctionNumber(), llvm::ConstantExpr::get(), getDecodedBinaryOpcode(), getDecodedUnaryOpcode(), llvm::VectorType::getExtendedElementVectorType(), getExtendedType(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getIntegerCast(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::ConstantExpr::getIntToPtr(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::ConstantExpr::getNeg(), llvm::ConstantExpr::getNot(), getParameterABIAttributes(), getParentPad(), llvm::ConstantExpr::getPointerCast(), llvm::ConstantExpr::getPtrToInt(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSIToFP(), getSubprogram(), llvm::ConstantInt::getTrue(), llvm::ConstantExpr::getTrunc(), llvm::ConstantExpr::getUIToFP(), llvm::SystemZTTIImpl::getVectorInstrCost(), getWithNewBitWidth(), llvm::ConstantExpr::getZExt(), llvm::haveNoCommonBitsSet(), llvm::CompositeType::indexValid(), llvm::CastInst::isEliminableCastPair(), llvm::isImpliedCondition(), isKnownNonEqual(), llvm::DemandedBits::isUseDead(), LowerBSWAP(), matchIntrinsicType(), llvm::DemandedBitsWrapperPass::releaseMemory(), llvm::InstCombiner::replacedSelectWithOperand(), llvm::InstCombiner::run(), ShrinkDemandedConstant(), SimplifyAddInst(), simplifyDivRem(), simplifyICmpOfBools(), llvm::SimplifyInstruction(), SimplifyMulInst(), SimplifySRemInst(), SimplifySubInst(), tryToRecognizePopCount(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitUDiv(), and llvm::InstCombiner::visitURem().
isIntOrIntVectorTy() [2/2]
bool llvm::Type::isIntOrIntVectorTy (unsigned BitWidth) const inline
Return true if this is an integer type or a vector of integer types of the given width.
Definition at line 207 of file Type.h.
References getScalarType(), and isIntegerTy().
isIntOrPtrTy()
bool llvm::Type::isIntOrPtrTy () const inline
Return true if this is an integer type or a pointer type.
Definition at line 212 of file Type.h.
References isIntegerTy(), and isPointerTy().
Referenced by computeKnownBitsFromOperator(), llvm::NVPTXAsmPrinter::doFinalization(), evaluateICmpRelation(), llvm::ScalarEvolution::getNoopOrAnyExtend(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::ScalarEvolution::getTruncateOrSignExtend(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), hasSameExtUse(), isBitCastSemanticsPreserving(), isContiguous(), isPromotedInstructionLegal(), llvm::ScalarEvolution::isSCEVable(), isSupportedAtomicType(), llvm::X86TargetLowering::markLibCallAttributes(), MightBeFoldableInst(), and llvm::SCEVCastExpr::SCEVCastExpr().
isLabelTy()
bool llvm::Type::isLabelTy () const inline
Return true if this is 'label'.
Definition at line 188 of file Type.h.
References getTypeID(), and LabelTyID.
Referenced by createGlobalFwdRef(), FunctionNumber(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), llvm::FunctionType::isValidReturnType(), and parseOptionalLinkageAux().
isMetadataTy()
bool llvm::Type::isMetadataTy () const inline
Return true if this is 'metadata'.
Definition at line 191 of file Type.h.
References getTypeID(), and MetadataTyID.
Referenced by llvm::canReplaceOperandWithVariable(), forEachUser(), FunctionNumber(), getParentPad(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), llvm::FunctionType::isValidReturnType(), matchIntrinsicType(), and parseOptionalLinkageAux().
isPointerTy()
bool llvm::Type::isPointerTy () const inline
True if this is an instance of PointerType.
Definition at line 224 of file Type.h.
References getTypeID(), and PointerTyID.
Referenced by llvm::AliasSetTracker::add(), llvm::SCEVAAResult::alias(), BuildConstantFromSCEV(), canConvertValue(), canFoldIVIncExpr(), canTailPredicateLoop(), cloneInstructionWithNewAddressSpace(), CompareValueComplexity(), computeKnownBits(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::convertPointerToIntegerType(), llvm::CastInst::CreateBitOrPointerCast(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createCast(), createFree(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::emitFGetCUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), findFuncPointers(), findMatchingInlineAsmOperand(), FindPredecessorAutoreleaseWithSafePath(), findUnwindDestinations(), FitWeights(), FunctionNumber(), genericValueTraversal(), genLoopLimit(), getAdjustedPtr(), llvm::IRPosition::getAttrs(), llvm::CastInst::getCastOpcode(), GetConstantInt(), llvm::ExecutionEngine::getConstantValue(), llvm::ScalarEvolution::getEffectiveSCEVType(), getIndexedTypeInternal(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::GlobalsAAResult::getModRefBehavior(), llvm::AAResults::getModRefInfo(), getNaturalGEPRecursively(), getNaturalGEPWithType(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::TargetTransformInfoImplBase::getOperationCost(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::getOrEnforceKnownAlignment(), llvm::AMDGPULibFunc::getOrInsertFunction(), getParentPad(), llvm::getPointerAtOffset(), llvm::ScalarEvolution::getPointerBase(), getPointerOperands(), llvm::LazyValueInfo::getPredicateAt(), llvm::getPtrStride(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), llvm::SelectionDAG::getSrcValue(), llvm::VNCoercion::getStoreValueForLoadHelper(), llvm::GetStringLength(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::GetUnderlyingObject(), llvm::getUnderlyingObjectsForCodeGen(), llvm::HexagonEvaluator::HexagonEvaluator(), llvm::SCEVExpander::hoistIVInc(), llvm::Attributor::identifyDefaultAbstractAttributes(), inferDSOLocal(), INITIALIZE_PASS(), llvm::MemoryDependenceResults::invalidateCachedPointerInfo(), isCallPromotable(), llvm::CastInst::isCastable(), isCompatibleIVType(), isGEPKnownNonNull(), IsIncrementNUW(), llvm::InductionDescriptor::isInductionPHI(), IsInterestingCmp(), isInterestingPointer(), isIntOrPtrTy(), isKnownNonZero(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::CastInst::isLosslessCast(), isMinMaxWithLoads(), isMulPowOf2(), IsNonLocalValue(), isNoopBitcast(), isObjectDereferencedInBlock(), isPointerBitcastEqualTo(), isPointerOperand(), isPromotedResultSafe(), isPtrOrPtrVectorTy(), isReportingError(), isReturnNonNull(), isSingleValueType(), isSupportedArgumentType(), isSupportedReturnType(), llvm::LoopVectorizationLegality::isUniform(), llvm::VectorType::isValidElementType(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::NVPTXTargetLowering::LowerCall(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), mayUsePostIncMode(), MergeAliasResults(), operator new(), optimizeOnceStoredGlobal(), parseIRValue(), llvm::PointerMayBeCaptured(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SCEVExpander::replaceCongruentIVs(), replaceWithConstant(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), setRetNonNull(), SimplifyICmpInst(), llvm::sortPtrAccesses(), swapMayExposeCSEOpportunities(), TryToShrinkGlobalToBoolean(), llvm::AttributeFuncs::typeIncompatible(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::Interpreter::visitAllocaInst(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitBitCast(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
isPPC_FP128Ty()
bool llvm::Type::isPPC_FP128Ty () const inline
Return true if this is powerpc long double.
Definition at line 159 of file Type.h.
References getTypeID(), and PPC_FP128TyID.
Referenced by llvm::ConstantFoldCastInstruction(), emitGlobalConstantFP(), emitSignedInt64(), FoldBitCast(), llvm::Constant::getAllOnesValue(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::PPCTTIImpl::getUserCost(), isValidElementType(), and TypeToFloatSemantics().
isPtrOrPtrVectorTy()
bool llvm::Type::isPtrOrPtrVectorTy () const inline
Return true if this is a pointer type or a vector of pointer types.
Definition at line 227 of file Type.h.
References getScalarType(), and isPointerTy().
Referenced by llvm::CastInst::castIsValid(), checkFunctionMemoryAccess(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), computeKnownBits(), llvm::ConstantFoldLoadThroughBitcast(), convertValue(), llvm::IRBuilder< TargetFolder >::CreateBitOrPointerCast(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), decomposeSimpleLinearExpr(), findBaseDefiningValue(), FunctionNumber(), getChainID(), llvm::DataLayout::getIndexType(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::DataLayout::getIntPtrType(), llvm::ConstantExpr::getIntToPtr(), getParameterABIAttributes(), getParentPad(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::ConstantExpr::getPtrToInt(), getScalarSizeInBits(), llvm::CastInst::isEliminableCastPair(), isOnlyReachableViaThisEdge(), patchAndReplaceAllUsesWith(), reportLoadElim(), reportMayClobberedLoad(), SimplifyCastInst(), llvm::Value::stripAndAccumulateConstantOffsets(), stripAndComputeConstantOffsets(), llvm::UpgradeBitCastExpr(), and llvm::UpgradeBitCastInst().
isSequentialType()
static bool llvm::Type::isSequentialType (TypeID TyID) inline static protected
Definition at line 113 of file Type.h.
References ArrayTyID, dump(), llvm::RISCVFenceField::O, print(), and VectorTyID.
Referenced by getSequentialElementType().
isSingleValueType()
bool llvm::Type::isSingleValueType () const inline
Return true if the type is a valid type for a register in codegen.
This includes all first-class types except struct and array types.
Definition at line 250 of file Type.h.
References isFloatingPointTy(), isIntegerTy(), isPointerTy(), isVectorTy(), and isX86_MMXTy().
Referenced by canConvertValue(), getMemCmpLoad(), getOpenCLAlignment(), llvm::TargetLowering::ParseConstraints(), processInternalGlobal(), AllocaSlices::SliceBuilder::SliceBuilder(), stripAggregateTypeWrapping(), and llvm::sroa::AllocaSliceRewriter::visit().
isSized()
bool llvm::Type::isSized (SmallPtrSetImpl< Type *> * Visited = nullptr) const inline
Return true if it makes sense to take the size of this type.
To get the actual size for a particular target, it is reasonable to use the DataLayout subsystem to do this.
Definition at line 265 of file Type.h.
References ArrayTyID, getFPMantissaWidth(), getPrimitiveSizeInBits(), getScalarSizeInBits(), getTypeID(), IntegerTyID, isFloatingPointTy(), LLVM_READONLY, PointerTyID, StructTyID, VectorTyID, and X86_MMXTyID.
Referenced by annotateAnyAllocSite(), areGlobalsPotentiallyEqual(), combineLoadToOperationType(), computeArraySize(), computeKnownBitsFromOperator(), llvm::ConstantFoldLoadFromConstPtr(), llvm::createAArch64StackTaggingPass(), createOrdering(), decomposeSimpleLinearExpr(), foldOperationIntoPhiValue(), FunctionNumber(), llvm::IRTranslator::getAnalysisUsage(), getBaseAlign(), getFPMantissaWidth(), getIndexedTypeInternal(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::getLLTForType(), getMaxPointerSize(), getMemCmpLoad(), getNaturalGEPWithOffset(), getParameterABIAttributes(), llvm::Value::getPointerAlignment(), llvm::Value::getPointerDereferenceableBytes(), llvm::DataLayout::getTypeSizeInBits(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), GlobalWasGeneratedByCompiler(), instrumentMaskedLoadOrStore(), isContiguous(), isDenselyPacked(), llvm::isDereferenceableAndAlignedPointer(), isDereferenceableAndAlignedPointer(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::InductionDescriptor::isInductionPHI(), llvm::SITargetLowering::isLegalAddressingMode(), llvm::HexagonTargetLowering::isLegalAddressingMode(), llvm::AArch64TargetLowering::isLegalAddressingMode(), isMulPowOf2(), isNonEscapingGlobalNoAliasWithLoad(), llvm::StructType::isOpaque(), isSafeToEliminateVarargsCast(), IsSmallObject(), isWorthFoldingADDlow(), isZeroLengthArray(), llvm::NVPTXTargetLowering::LowerReturn(), moveUp(), llvm::TargetLowering::ParseConstraints(), performGlobalAddressCombine(), RetagMask(), llvm::AAEvaluator::run(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), SimplifyGEPInst(), llvm::fuzzerop::sizedPtrType(), tryToOptimizeStoreOfMallocToGlobal(), TypeSizeToSizeIndex(), llvm::ObjectSizeOffsetVisitor::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitBitCast(), and llvm::InstCombiner::visitGetElementPtrInst().
isStructTy()
bool llvm::Type::isStructTy () const inline
True if this is an instance of StructType.
Definition at line 218 of file Type.h.
References getTypeID(), and StructTyID.
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingLoad(), llvm::VNCoercion::analyzeLoadFromClobberingWrite(), annotateAnyAllocSite(), llvm::VNCoercion::canCoerceMustAliasedValueToLoad(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), createCast(), createWrapper(), doPromotion(), llvm::FindInsertedValue(), findReturnsToZap(), llvm::ConstantAggregateZero::get(), llvm::SelectionDAGBuilder::getValueImpl(), insertSinCosCall(), isConstantUsingVectorTy(), llvm::SCEVUnknown::isOffsetOf(), isStructure(), isSupportedType(), memVTFromAggregate(), false::next_type(), false::operator<<(), originalTypeIsF128(), tryToReplaceWithConstant(), llvm::Value::Value(), llvm::InlineAsm::Verify(), and llvm::InstCombiner::visitGetElementPtrInst().
isTokenTy()
bool llvm::Type::isTokenTy () const inline
Return true if this is 'token'.
Definition at line 194 of file Type.h.
References getTypeID(), and TokenTyID.
Referenced by llvm::SelectInst::areInvalidOperands(), canSinkInstructions(), llvm::GVNExpression::Expression::dump(), llvm::formLCSSAForInstructions(), FunctionNumber(), getOffsetFromIndices(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), matchIntrinsicType(), llvm::removeAllNonTerminatorAndEHPadInstructions(), llvm::SplitLandingPadPredecessors(), and llvm::SelectionDAGBuilder::visitBitTestCase().
isVectorTy()
bool llvm::Type::isVectorTy () const inline
True if this is an instance of VectorType.
Definition at line 230 of file Type.h.
References canLosslesslyBitCastTo(), getTypeID(), isEmptyTy(), and VectorTyID.
Referenced by llvm::ARMTargetLowering::canCombineStoreAndExtract(), canEvaluateShuffled(), canNarrowShiftAmt(), canonicalizeSaturatedAdd(), llvm::CastInst::castIsValid(), CC_MipsO32_FP64(), collectShuffleElements(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), combineLoadToOperationType(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFoldUnaryInstruction(), convertValue(), llvm::CastInst::CreatePointerCast(), llvm::createSeparateConstOffsetFromGEPPass(), despeculateCountZeros(), llvm::EmitGEPOffset(), evaluateInDifferentElementOrder(), llvm::VPBranchOnMaskRecipe::execute(), executeFCMP_BOOL(), executeFCMP_ONE(), executeFCMP_ORD(), executeFCMP_UNO(), executeSelectInst(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::extractConstantMask(), findBaseDefiningValue(), llvm::findScalarElement(), foldBitCastBitwiseLogic(), foldBitcastExtElt(), foldICmpShlOne(), foldICmpWithLowBitMaskedVal(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), FunctionNumber(), generatePoisonChecks(), llvm::ConstantAggregateZero::get(), llvm::MipsTargetLowering::getABIAlignmentForCallingConv(), llvm::ARMTargetLowering::getABIAlignmentForCallingConv(), llvm::AArch64TTIImpl::getAddressComputationCost(), llvm::X86TTIImpl::getAddressComputationCost(), llvm::ARMTTIImpl::getAddressComputationCost(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticReductionCost(), llvm::SystemZTTIImpl::getBoolVecToIntConversionCost(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::CastInst::getCastOpcode(), getChainID(), getCmpOpsType(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::HexagonTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost(), getCompareCC(), llvm::ConstantExpr::getExtractElement(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getInsertElement(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), getLogBase2(), llvm::SystemZTTIImpl::getMemoryOpCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), getNumVectorRegs(), getOffsetFromIndices(), getOpenCLAlignment(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), getParameterABIAttributes(), getParentPad(), llvm::AArch64TTIImpl::getPopcntSupport(), llvm::NVPTXTargetLowering::getPrototype(), getReducedType(), getRelevantOperands(), llvm::getSafeVectorConstantForBinop(), getScalarIntrinsicDeclaration(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getScalarizationOverhead(), getScalarType(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getShuffleCost(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::MipsCCState::getSpecialCallingConvForCallee(), llvm::InnerLoopVectorizer::getStepVector(), getSubprogram(), getTargetConstantBitsFromNode(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), getUniformBase(), llvm::PPCTTIImpl::getUserCost(), llvm::X86TTIImpl::getUserCost(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::AArch64TTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::HexagonTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), getVectorIntrinsicInstrCost(), llvm::SystemZTTIImpl::getVectorTruncCost(), getWithNewBitWidth(), llvm::CompositeType::indexValid(), INITIALIZE_PASS(), llvm::CastInst::isCastable(), isConstantUsingVectorTy(), llvm::Constant::isElementWiseEqual(), llvm::CastInst::isEliminableCastPair(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::ShuffleVectorInst::isIdentityMask(), llvm::isImpliedCondition(), isIndirectBrTarget(), isIntExtFree(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverNaN(), llvm::PPCTargetLowering::isLegalAddressingMode(), isMulPowOf2(), isPromotedInstructionLegal(), llvm::ShuffleVectorInst::isReverseMask(), llvm::ShuffleVectorInst::isSelectMask(), llvm::ShuffleVectorInst::isSingleSourceMask(), isSingleValueType(), isStrideMul(), llvm::ShuffleVectorInst::isTransposeMask(), isTruePredicate(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), isVectorReductionOp(), llvm::ShuffleVectorInst::isZeroEltSplatMask(), llvm::AArch64TargetLowering::isZExtFree(), llvm::NVPTXTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::NVPTXTargetLowering::LowerFormalArguments(), matchesOr(), matchPairwiseReductionAtLevel(), memVTFromAggregate(), originalTypeIsVectorFloat(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), parsePredicateConstraint(), PickMostRelevantLoop(), processAnd(), processAShr(), processBinOp(), processCallSite(), processPHI(), processSDiv(), processSelect(), processSExt(), processSRem(), processUDivOrURem(), processUGT_ADDCST_ADD(), propagateMetadata(), llvm::Constant::replaceUndefsWith(), llvm::InnerLoopVectorizer::reverseVector(), llvm::salvageDebugInfoImpl(), llvm::FunctionLoweringInfo::set(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), shouldConvertImpl(), shouldMergeGEPs(), llvm::ARMTargetLowering::shouldSinkOperands(), llvm::AArch64TargetLowering::shouldSinkOperands(), ShrinkDemandedConstant(), simplifyDivRem(), simplifyX86movmsk(), supportedAddressingMode(), TryToShrinkGlobalToBoolean(), UnpackFromArgumentSlot(), llvm::PPCTTIImpl::vectorCostAdjustment(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitAShr(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitIntToPtr(), llvm::Interpreter::visitLShr(), llvm::InstCombiner::visitPtrToInt(), llvm::Interpreter::visitShl(), llvm::InstCombiner::visitTrunc(), and llvm::Interpreter::visitUnaryOperator().
isVoidTy()
bool llvm::Type::isVoidTy () const inline
Return true if this is 'void'.
Definition at line 141 of file Type.h.
References getTypeID(), and VoidTyID.
Referenced by addStackMapLiveVars(), llvm::AllocaInst::AllocaInst(), llvm::AMDGPUCallLowering::AMDGPUCallLowering(), annotateAnyAllocSite(), llvm::CallLowering::ArgInfo::ArgInfo(), llvm::coro::Shape::buildFrom(), canCreateThunkFor(), CC_RISCV_FastCC(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::computeValueLLTs(), llvm::ComputeValueVTs(), copyMustTailReturn(), createMalloc(), llvm::createObjCARCOptPass(), llvm::VPRecipeBuilder::createReplicateRegion(), createRetPHINode(), llvm::createScalarizerPass(), createWrapper(), determinePointerReadAttrs(), emitSignedInt64(), llvm::Interpreter::exitCalled(), findMatchingInlineAsmOperand(), FunctionNumber(), llvm::IRTranslator::getAnalysisUsage(), llvm::IRPosition::getAttrs(), getComparePred(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::SystemZTTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMemoryOpCost(), getMetadataTypeOrder(), getOffsetFromIndices(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), getParentPad(), GetPointerOperand(), getRetComponentType(), getUniformBase(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), isEqualImpl(), llvm::isLibFreeFunction(), isOnlyReachableViaThisEdge(), isPromotedResultSafe(), isStrideMul(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), llvm::X86CallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::CallLowering::lowerCall(), lowerCallFromStatepointLoweringInfo(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::SelectionDAGBuilder::LowerStatepoint(), llvm::makeGuardControlFlowExplicit(), makeStatepointExplicitImpl(), llvm::orc::makeStub(), matchIntrinsicType(), maybePrintCallAddrSpace(), llvm::InstDeleterIRStrategy::mutate(), NumRetVals(), okayForPHIOfOps(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), llvm::TargetLowering::ParseConstraints(), parseOptionalLinkageAux(), patchAndReplaceAllUsesWith(), llvm::promoteCall(), PropagateConstantReturn(), removeLifetimeIntrinsicUsers(), replaceAllUsesOfWithIn(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::runIPSCCP(), runSCCP(), llvm::InnerLoopVectorizer::scalarizeInstruction(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), ToVectorTy(), unifyReturnBlockSet(), llvm::Value::Value(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InlineAsm::Verify(), llvm::X86CallLowering::X86CallLowering(), and llvm::Function::~Function().
isX86_FP80Ty()
bool llvm::Type::isX86_FP80Ty () const inline
Return true if this is x86 long double.
Definition at line 153 of file Type.h.
References getTypeID(), and X86_FP80TyID.
Referenced by llvm::ConstantFoldCastInstruction(), emitSignedInt64(), llvm::ExecutionEngine::getConstantValue(), isValidElementType(), MatchingStackOffset(), and TypeToFloatSemantics().
isX86_MMXTy()
bool llvm::Type::isX86_MMXTy () const inline
Return true if this is X86 MMX.
Definition at line 182 of file Type.h.
References getTypeID(), and X86_MMXTyID.
Referenced by llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::CastInst::getCastOpcode(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::CastInst::isBitCastable(), llvm::CastInst::isCastable(), isSingleValueType(), and matchIntrinsicType().
print()
void Type::print (raw_ostream & O, bool IsForDebug = false, bool NoDetails = false) const
Print the current type.
Omit the type details if NoDetails == true. E.g., let st = type { i32, i16 } When NoDetails is true, we only print st. Put differently, NoDetails prints the type as if inlined with the operands when printing an instruction.
Definition at line 4290 of file AsmWriter.cpp.
Referenced by emitGlobalConstantFP(), isSequentialType(), llvm::operator<<(), and llvm::SLPVectorizerPass::runImpl().
setSubclassData()
void llvm::Type::setSubclassData (unsigned val) inline protected
Definition at line 97 of file Type.h.
References assert(), and getSubclassData().
Referenced by llvm::StructType::get(), llvm::IntegerType::getMask(), llvm::IntegerType::IntegerType(), llvm::StructType::isSized(), and llvm::StructType::setBody().
subtype_begin()
subtype_iterator llvm::Type::subtype_begin () const inline
Definition at line 318 of file Type.h.
References ContainedTys.
Referenced by subtype_rend(), and subtypes().
subtype_end()
subtype_iterator llvm::Type::subtype_end () const inline
Definition at line 319 of file Type.h.
References NumContainedTys.
Referenced by subtype_rbegin(), and subtypes().
subtype_rbegin()
subtype_reverse_iterator llvm::Type::subtype_rbegin () const inline
Definition at line 326 of file Type.h.
References subtype_end().
Referenced by llvm::TypeFinder::clear().
subtype_rend()
subtype_reverse_iterator llvm::Type::subtype_rend () const inline
Definition at line 329 of file Type.h.
References subtype_begin().
Referenced by llvm::TypeFinder::clear().
subtypes()
ArrayRef<Type*> llvm::Type::subtypes () const inline
Definition at line 320 of file Type.h.
References llvm::makeArrayRef(), subtype_begin(), and subtype_end().
Referenced by getMetadataTypeOrder().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 89 of file Type.h.
Member Data Documentation
ContainedTys
Type* const* llvm::Type::ContainedTys = nullptr protected
A pointer to the array of Types contained by this Type.
For example, this includes the arguments of a function type, the elements of a structure, the pointee of a pointer, the element type of an array, etc. This pointer may be 0 for types that don't contain other types (Integer, Double, Float).
Definition at line 111 of file Type.h.
Referenced by llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::StructType::getElementType(), llvm::IntegerType::getMask(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::SequentialType::SequentialType(), llvm::StructType::setBody(), and subtype_begin().
NumContainedTys
unsigned llvm::Type::NumContainedTys = 0 protected
Keeps track of how many Type*'s there are in the ContainedTys list.
Definition at line 104 of file Type.h.
Referenced by llvm::StructType::element_end(), llvm::StructType::getElementType(), llvm::IntegerType::getMask(), getNumContainedTypes(), llvm::StructType::getNumElements(), llvm::FunctionType::getNumParams(), llvm::FunctionType::param_end(), llvm::SequentialType::SequentialType(), llvm::StructType::setBody(), and subtype_end().
The documentation for this class was generated from the following files:
include/llvm/IR/Type.h
include/llvm/IR/DerivedTypes.h
lib/IR/AsmWriter.cpp
lib/IR/Type.cpp