LLVM: llvm::VPlanSlp Class Reference
llvm::VPlanSlp Class Reference
Class that maps (parts of) an existing VPlan to trees of combined VPInstructions.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPlanSlp (VPInterleavedAccessInfo &IAI, VPBasicBlock &BB)
~VPlanSlp ()
VPInstruction * buildGraph (ArrayRef< VPValue *> Operands)
Tries to build an SLP tree rooted at Operands and returns a VPInstruction combining Operands, if they can be combined.
unsigned getWidestBundleBits () const
Return the width of the widest combined bundle in bits.
bool isCompletelySLP () const
Return true if all visited instruction can be combined.
Detailed Description
Class that maps (parts of) an existing VPlan to trees of combined VPInstructions.
Definition at line 1681 of file VPlan.h.
Constructor & Destructor Documentation
VPlanSlp()
llvm::VPlanSlp::VPlanSlp (VPInterleavedAccessInfo & IAI, VPBasicBlock & BB) inline
Definition at line 1758 of file VPlan.h.
~VPlanSlp()
llvm::VPlanSlp::~VPlanSlp () inline
Definition at line 1760 of file VPlan.h.
Member Function Documentation
buildGraph()
VPInstruction * VPlanSlp::buildGraph (ArrayRef< VPValue *> Operands)
Tries to build an SLP tree rooted at Operands and returns a VPInstruction combining Operands, if they can be combined.
Definition at line 360 of file VPlanSLP.cpp.
References areCommutative(), assert(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::ArrayRef< T >::empty(), getOpcode(), getOperands(), llvm::Optional< T >::getValue(), I, LLVM_DEBUG, llvm::SPII::Load, print(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), llvm::VPInstruction::SLPLoad, llvm::VPInstruction::SLPStore, and llvm::SPII::Store.
getWidestBundleBits()
unsigned llvm::VPlanSlp::getWidestBundleBits () const inline
Return the width of the widest combined bundle in bits.
Definition at line 1770 of file VPlan.h.
isCompletelySLP()
bool llvm::VPlanSlp::isCompletelySLP () const inline
Return true if all visited instruction can be combined.
Definition at line 1773 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanSLP.cpp