LLVM: llvm::PHINode Class Reference
llvm::PHINode Class Reference
#include "llvm/IR/Instructions.h"
Public Types
using block_iterator = BasicBlock **
using const_block_iterator = BasicBlock *const *
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
block_iterator block_begin ()
const_block_iterator block_begin () const
block_iterator block_end ()
const_block_iterator block_end () const
iterator_range< block_iterator > blocks ()
iterator_range< const_block_iterator > blocks () const
op_range incoming_values ()
const_op_range incoming_values () const
unsigned getNumIncomingValues () const
Return the number of incoming edges.
Value * getIncomingValue (unsigned i) const
Return incoming value number x.
void setIncomingValue (unsigned i, Value *V)
BasicBlock * getIncomingBlock (unsigned i) const
Return incoming basic block number i.
BasicBlock * getIncomingBlock (const Use &U) const
Return incoming basic block corresponding to an operand of the PHI.
BasicBlock * getIncomingBlock (Value::const_user_iterator I) const
Return incoming basic block corresponding to value use iterator.
void setIncomingBlock (unsigned i, BasicBlock *BB)
void replaceIncomingBlockWith (const BasicBlock *Old, BasicBlock *New)
Replace every incoming basic block Old to basic block New.
void addIncoming (Value *V, BasicBlock *BB)
Add an incoming value to the end of the PHI list.
Value * removeIncomingValue (unsigned Idx, bool DeletePHIIfEmpty=true)
Remove an incoming value.
Value * removeIncomingValue (const BasicBlock *BB, bool DeletePHIIfEmpty=true)
int getBasicBlockIndex (const BasicBlock *BB) const
Return the first index of the specified basic block in the value list for this PHI.
Value * getIncomingValueForBlock (const BasicBlock *BB) const
void setIncomingValueForBlock (const BasicBlock *BB, Value *V)
Set every incoming value(s) for block BB to V.
Value * hasConstantValue () const
If the specified PHI node always merges together the same value, return the value, otherwise return null.
bool hasConstantOrUndefValue () const
Whether the specified PHI node always merges together the same value, assuming undefs are equal to a unique non-undef value.
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isIndirectTerminator () const
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode *>> &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode *>> &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void getAAMetadata (AAMDNodes &N, bool Merge=false) const
Fills the AAMDNodes structure with AA metadata from this instruction.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void setAAMetadata (const AAMDNodes &N)
Sets the metadata on this instruction from the AAMDNodes structure.
bool extractProfMetadata (uint64_t &TrueVal, uint64_t &FalseVal) const
Retrieve the raw weight values of a conditional branch or select.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setProfWeight (uint64_t W)
Sets the branch_weights metadata to W for CallInst.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool isExact () const
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const
Return true if this instruction may modify memory.
bool mayReadFromMemory () const
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const
Return true if this atomic instruction stores to memory.
bool mayThrow () const
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const
Return true if the instruction may have side effects.
bool isSafeToRemove () const
Return true if the instruction can be removed if the result is unused.
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
const Instruction * getNextNonDebugInstruction () const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction ()
const Instruction * getPrevNonDebugInstruction () const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction ()
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static PHINode * Create (Type *Ty, unsigned NumReservedValues, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructors - NumReservedValues is a hint for the number of incoming edges that this phi node will have (use 0 if you really have no idea).
static PHINode * Create (Type *Ty, unsigned NumReservedValues, const Twine &NameStr, BasicBlock *InsertAtEnd)
static unsigned getOperandNumForIncomingValue (unsigned i)
static unsigned getIncomingValueNumForOperand (unsigned i)
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isIndirectTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator with indirect targets.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
PHINode * cloneImpl () const
void allocHungoffUses (unsigned N)
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
ilist_node_impl ()=default
Friends
class Instruction
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, true, true >
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Definition at line 2552 of file Instructions.h.
Member Typedef Documentation
block_iterator
using llvm::PHINode::block_iterator = BasicBlock **
Definition at line 2609 of file Instructions.h.
const_block_iterator
using llvm::PHINode::const_block_iterator = BasicBlock * const *
Definition at line 2610 of file Instructions.h.
Member Function Documentation
addIncoming()
void llvm::PHINode::addIncoming (Value * V, BasicBlock * BB) inline
Add an incoming value to the end of the PHI list.
Definition at line 2704 of file Instructions.h.
References llvm::User::getNumOperands(), and llvm::User::setNumHungOffUseOperands().
Referenced by llvm::SSAUpdaterTraits< SSAUpdater >::AddPHIOperand(), cheapToScalarize(), Cleanup(), CloneInstructionInExitBlock(), llvm::JumpThreadingPass::CloneInstructions(), CloneLoopBlocks(), ConnectEpilog(), ConnectProlog(), ConvertToSInt(), llvm::createCodeGenPreparePass(), llvm::createDwarfEHPass(), createFFSIntrinsic(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), createPHIsForSplitLoopExit(), createRetPHINode(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), despeculateCountZeros(), llvm::GVNExpression::Expression::dump(), ehAwareSplitEdge(), eliminateRecursiveTailCall(), ensureValueAvailableInSuccessor(), llvm::VPPredInstPHIRecipe::execute(), llvm::CodeExtractor::findInputsOutputs(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), foldOperationIntoPhiValue(), llvm::formLCSSAForInstructions(), GetPointerOperand(), getSignature(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleInlinedEHPad(), hasProfileData(), hasStoreUsersOnly(), INITIALIZE_PASS(), llvm::InlineFunction(), insertTrivialPHIs(), insertUniqueBackedgeBlock(), inversePermutation(), IsIncrementNUW(), isKnownTypeIdMember(), isLoadConditional(), isOnlyReachableViaThisEdge(), isSafeAndProfitableToSinkLoad(), isSafeToExecuteUnconditionally(), LLVMAddIncoming(), mergeEmptyReturnBlocks(), optimizeSQRT(), performMaskedAtomicOp(), promoteSingleBlockAlloca(), redirectValuesFromPredecessorsToPhi(), removeEmptyCleanup(), RemoveSwitchAfterSelectConversion(), rewrite(), rewritePHIs(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), shouldKeepInEntry(), shouldRotateLoopExitingLatch(), SimplifyCondBranchToCondBranch(), SimplifyIndirectBrOnSelect(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), sinkLastInstruction(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), splitCallSite(), llvm::SplitLandingPadPredecessors(), llvm::JumpThreadingPass::ThreadGuard(), truncateIVUse(), TypeSizeToSizeIndex(), llvm::JumpThreadingPass::UnfoldSelectInstr(), unifyReturnBlockSet(), llvm::UnrollRuntimeLoopRemainder(), UpdatePHINodes(), llvm::LoopVersioning::versionLoop(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InstCombiner::visitStoreInst().
allocHungoffUses()
void llvm::PHINode::allocHungoffUses (unsigned N) inline protected
Definition at line 2585 of file Instructions.h.
References llvm::User::allocHungoffUses().
block_begin() [1/2]
block_iterator llvm::PHINode::block_begin () inline
Definition at line 2612 of file Instructions.h.
References llvm::User::op_begin().
Referenced by llvm::SelectInst::areInvalidOperands(), llvm::EliminateDuplicatePHINodes(), INITIALIZE_PASS(), and llvm::Instruction::isIdenticalToWhenDefined().
block_begin() [2/2]
const_block_iterator llvm::PHINode::block_begin () const inline
Definition at line 2618 of file Instructions.h.
References llvm::User::op_begin().
block_end() [1/2]
block_iterator llvm::PHINode::block_end () inline
Definition at line 2624 of file Instructions.h.
References llvm::User::getNumOperands().
Referenced by llvm::SelectInst::areInvalidOperands(), llvm::EliminateDuplicatePHINodes(), and INITIALIZE_PASS().
block_end() [2/2]
const_block_iterator llvm::PHINode::block_end () const inline
Definition at line 2628 of file Instructions.h.
References llvm::User::getNumOperands().
blocks() [1/2]
iterator_range<block_iterator> llvm::PHINode::blocks () inline
Definition at line 2632 of file Instructions.h.
References llvm::make_range().
Referenced by BrPHIToSelect(), computeUnlikelySuccessors(), and mayUsePostIncMode().
blocks() [2/2]
iterator_range<const_block_iterator> llvm::PHINode::blocks () const inline
Definition at line 2636 of file Instructions.h.
References llvm::make_range().
classof() [1/2]
static bool llvm::PHINode::classof (const Instruction * I) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 2768 of file Instructions.h.
References llvm::Instruction::getOpcode().
classof() [2/2]
static bool llvm::PHINode::classof (const Value * V) inline static
Definition at line 2771 of file Instructions.h.
References llvm::AllocaInst::classof().
cloneImpl()
PHINode * PHINode::cloneImpl () const protected
Definition at line 4260 of file Instructions.cpp.
Create() [1/2]
static PHINode* llvm::PHINode::Create (Type * Ty, unsigned NumReservedValues, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) inline static
Constructors - NumReservedValues is a hint for the number of incoming edges that this phi node will have (use 0 if you really have no idea).
Definition at line 2592 of file Instructions.h.
Referenced by buildClonedLoopBlocks(), cheapToScalarize(), CloneInstructionInExitBlock(), llvm::JumpThreadingPass::CloneInstructions(), cloneInstructionWithNewAddressSpace(), CloneLoopBlocks(), ConnectEpilog(), ConnectProlog(), ConvertToSInt(), llvm::createDwarfEHPass(), llvm::SSAUpdaterTraits< SSAUpdater >::CreateEmptyPHI(), createFFSIntrinsic(), llvm::IRBuilder< TargetFolder >::CreatePHI(), createPHIsForSplitLoopExit(), createResumeEntryBlock(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), decomposeSimpleLinearExpr(), llvm::GVNExpression::Expression::dump(), eliminateRecursiveTailCall(), ensureValueAvailableInSuccessor(), findBasePointer(), llvm::CodeExtractor::findInputsOutputs(), llvm::InnerLoopVectorizer::fixReduction(), foldOperationIntoPhiValue(), llvm::formLCSSAForInstructions(), GetHeapSROAValue(), GetPointerOperand(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), hasProfileData(), INITIALIZE_PASS(), llvm::InlineFunction(), insertTrivialPHIs(), insertUniqueBackedgeBlock(), isLoadConditional(), isOnlyReachableViaThisEdge(), isSafeAndProfitableToSinkLoad(), isSafeToExecuteUnconditionally(), mergeEmptyReturnBlocks(), okayForPHIOfOps(), promoteSingleBlockAlloca(), rewrite(), rewritePHINodesForExitAndUnswitchedBlocks(), rewritePHIs(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyCondBranchToCondBranch(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), sinkLastInstruction(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), splitCallSite(), llvm::SplitLandingPadPredecessors(), llvm::JumpThreadingPass::ThreadGuard(), truncateIVUse(), llvm::UnrollRuntimeLoopRemainder(), UpdatePHINodes(), llvm::LoopVersioning::versionLoop(), llvm::InstCombiner::visitStoreInst(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
Create() [2/2]
static PHINode* llvm::PHINode::Create (Type * Ty, unsigned NumReservedValues, const Twine & NameStr, BasicBlock * InsertAtEnd) inline static
Definition at line 2598 of file Instructions.h.
References llvm::UnaryInstruction::DECLARE_TRANSPARENT_OPERAND_ACCESSORS().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::PHINode::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
getBasicBlockIndex()
int llvm::PHINode::getBasicBlockIndex (const BasicBlock * BB) const inline
Return the first index of the specified basic block in the value list for this PHI.
Returns -1 if no instance.
Definition at line 2732 of file Instructions.h.
References llvm::numbers::e, and llvm::User::getNumOperands().
Referenced by CloneLoopBlocks(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), isLoopCounter(), mayLoopAccessLocation(), mayUsePostIncMode(), removeEmptyCleanup(), RemoveSwitchAfterSelectConversion(), RewriteUsesOfClonedInstructions(), SimplifyCondBranchToCondBranch(), llvm::SplitCriticalEdge(), splitPredecessorsOfLoopExit(), updatePhiNodes(), llvm::Interpreter::visitIndirectBrInst(), and llvm::InstCombiner::visitPHINode().
getIncomingBlock() [1/3]
BasicBlock* llvm::PHINode::getIncomingBlock (unsigned i) const inline
Return incoming basic block number i.
Definition at line 2670 of file Instructions.h.
Referenced by llvm::PredicatedScalarEvolution::areAddRecsEqualWithPreds(), AreEquivalentPhiNodes(), BrPHIToSelect(), BuildConstantFromSCEV(), CanPropagatePredecessorsForPHIs(), cheapToScalarize(), llvm::CloneAndPruneIntoFromInst(), CloneInstructionInExitBlock(), llvm::FunctionComparator::cmpOperations(), computeKnownBitsFromOperator(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), ConvertToSInt(), llvm::createCodeGenPreparePass(), llvm::createObjCARCOptPass(), decomposeSimpleLinearExpr(), llvm::DemotePHIToStack(), despeculateCountZeros(), emitSignedInt64(), llvm::CodeExtractor::extractCodeRegion(), findBasePointer(), findIBRPredecessor(), findInnerReductionPhi(), llvm::CodeExtractor::findInputsOutputs(), findPHIToPartitionLoops(), fixPhis(), FoldCondBranchOnPHI(), foldGuardedRotateToFunnelShift(), foldOperationIntoPhiValue(), FoldTwoEntryPHINode(), gatherIncomingValuesToPhi(), llvm::GetIfCondition(), llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::getIncomingBlock(), getInductionVariable(), getInsertPointForUses(), getOffsetFromIndices(), getOtherIncomingValue(), GetPointerOperand(), getReductionValue(), getScalarIntrinsicDeclaration(), insertUniqueBackedgeBlock(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), IsEquivalentPHI(), llvm::InductionDescriptor::isFPInductionPHI(), isObjectDereferencedInBlock(), isProfitableForVectorization(), isSafeAndProfitableToSinkLoad(), isSafeAndProfitableToSpeculateAroundPHI(), isSafePHIToSpeculate(), IVUseShouldUsePostIncValue(), MarkBlocksLiveIn(), mayUsePostIncMode(), MergeAliasResults(), okayForPHIOfOps(), patchAndReplaceAllUsesWith(), llvm::JumpThreadingPass::ProcessBranchOnPHI(), processPHI(), promoteSingleBlockAlloca(), redirectValuesFromPredecessorsToPhi(), relocationViaAlloca(), removeEmptyCleanup(), llvm::BasicBlock::removePredecessor(), replaceUndefValuesInPhi(), returnEdge(), llvm::InstCombiner::run(), simplifyCommonValuePhi(), sink(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), llvm::SplitCriticalEdge(), SplitCriticalSideEffectEdges(), ThreadCmpOverPHI(), llvm::VPRecipeBuilder::tryToBlend(), llvm::JumpThreadingPass::TryToUnfoldSelect(), llvm::UnrollRuntimeLoopRemainder(), UpdatePHINodes(), updatePhiNodes(), updatePredecessorProfileMetadata(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InstCombiner::visitPHINode().
getIncomingBlock() [2/3]
BasicBlock* llvm::PHINode::getIncomingBlock (const Use & U) const inline
Return incoming basic block corresponding to an operand of the PHI.
Definition at line 2677 of file Instructions.h.
References assert(), llvm::Use::getUser(), and llvm::User::op_begin().
getIncomingBlock() [3/3]
BasicBlock* llvm::PHINode::getIncomingBlock (Value::const_user_iterator I) const inline
Return incoming basic block corresponding to value use iterator.
Definition at line 2685 of file Instructions.h.
getIncomingValue()
Value* llvm::PHINode::getIncomingValue (unsigned i) const inline
Return incoming value number x.
Definition at line 2650 of file Instructions.h.
References llvm::User::getOperand().
Referenced by llvm::DivergenceAnalysis::addUniformOverride(), llvm::PredicatedScalarEvolution::areAddRecsEqualWithPreds(), AreEquivalentPhiNodes(), BuildConstantFromSCEV(), canEvaluateZExtd(), CanPropagatePredecessorsForPHIs(), cheapToScalarize(), llvm::CloneAndPruneIntoFromInst(), CloneLoopBlocks(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), ConvertToSInt(), llvm::createCodeGenPreparePass(), llvm::createObjCARCOptPass(), decomposeSimpleLinearExpr(), llvm::DemotePHIToStack(), despeculateCountZeros(), emitSignedInt64(), findBasePointer(), findInnerReductionPhi(), llvm::CodeExtractor::findInputsOutputs(), findPHIToPartitionLoops(), FoldCondBranchOnPHI(), foldOperationIntoPhiValue(), FoldTwoEntryPHINode(), followLCSSA(), gatherIncomingValuesToPhi(), llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::getIncomingValue(), getInsertPointForUses(), getOffsetFromIndices(), getOtherIncomingValue(), getReductionValue(), getScalarIntrinsicDeclaration(), getShiftedValue(), insertUniqueBackedgeBlock(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), IsEquivalentPHI(), llvm::InductionDescriptor::isFPInductionPHI(), isLoopCounter(), isObjectDereferencedInBlock(), isProfitableForVectorization(), isReturnNonNull(), isSafeAndProfitableToSinkLoad(), isSafeAndProfitableToSpeculateAroundPHI(), isSafePHIToSpeculate(), isSameUnderlyingObjectInLoop(), IVUseShouldUsePostIncValue(), MarkBlocksLiveIn(), mayUsePostIncMode(), MergeAliasResults(), processPHI(), redirectValuesFromPredecessorsToPhi(), relocationViaAlloca(), removeEmptyCleanup(), replaceUndefValuesInPhi(), returnEdge(), simplifyCommonValuePhi(), SimplifyCondBranchToCondBranch(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), SplitCriticalSideEffectEdges(), ThreadCmpOverPHI(), llvm::JumpThreadingPass::TryToUnfoldSelect(), llvm::UnrollRuntimeLoopRemainder(), UpdatePHINodes(), updatePredecessorProfileMetadata(), llvm::LoopVersioning::versionLoop(), llvm::Interpreter::visitIndirectBrInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InstCombiner::visitPHINode().
getIncomingValueForBlock()
Value* llvm::PHINode::getIncomingValueForBlock (const BasicBlock * BB) const inline
Definition at line 2739 of file Instructions.h.
References assert().
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), calculateIterationsToInvariance(), CanPropagatePredecessorsForPHIs(), llvm::JumpThreadingPass::CloneInstructions(), CloneLoopBlocks(), cloneLoopBlocks(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), computeLiveOutSeed(), computeUnlikelySuccessors(), createFFSIntrinsic(), detectShiftUntilZeroIdiom(), llvm::Value::DoPHITranslation(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), ensureValueAvailableInSuccessor(), EvaluateConstantChrecAtConstant(), llvm::Evaluator::EvaluateFunction(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), FoldCondBranchOnPHI(), genLoopLimit(), llvm::Loop::getCanonicalInductionVariable(), getOtherIncomingValue(), HandleInlinedEHPad(), hasProfileData(), llvm::InlineFunction(), inversePermutation(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), IsIncrementNUW(), llvm::InductionDescriptor::isInductionPHI(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::LoopVectorizationLegality::isUniform(), okayForPHIOfOps(), llvm::peelLoop(), llvm::SCEVExpander::replaceCongruentIVs(), SafeToMergeTerminators(), shouldRotateLoopExitingLatch(), SimplifyCondBranchToCondBranch(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnrollLoop(), and UpdatePHINodes().
getIncomingValueNumForOperand()
static unsigned llvm::PHINode::getIncomingValueNumForOperand (unsigned i) inline static
Definition at line 2664 of file Instructions.h.
Referenced by llvm::IVUsers::AddUsersImpl(), AllUsesDominatedByBlock(), canFoldIVIncExpr(), createCallInst(), getInductionVariable(), and llvm::InnerLoopVectorizer::sinkScalarOperands().
getNumIncomingValues()
unsigned llvm::PHINode::getNumIncomingValues () const inline
Return the number of incoming edges.
Definition at line 2646 of file Instructions.h.
References llvm::User::getNumOperands().
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), llvm::DivergenceAnalysis::addUniformOverride(), llvm::PredicatedScalarEvolution::areAddRecsEqualWithPreds(), AreEquivalentPhiNodes(), BrPHIToSelect(), BuildConstantFromSCEV(), canEvaluateZExtd(), CanPropagatePredecessorsForPHIs(), cheapToScalarize(), llvm::CloneAndPruneIntoFromInst(), CloneInstructionInExitBlock(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), ConvertToSInt(), llvm::createCodeGenPreparePass(), llvm::createObjCARCOptPass(), decomposeSimpleLinearExpr(), llvm::DemotePHIToStack(), despeculateCountZeros(), llvm::GVNExpression::Expression::dump(), emitSignedInt64(), llvm::CodeExtractor::extractCodeRegion(), findBasePointer(), findIBRPredecessor(), llvm::CodeExtractor::findInputsOutputs(), findPHIToPartitionLoops(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), fixPhis(), FoldCondBranchOnPHI(), foldOperationIntoPhiValue(), followLCSSA(), llvm::formLCSSAForInstructions(), gatherIncomingValuesToPhi(), GetHeapSROAValue(), llvm::GetIfCondition(), getInsertPointForUses(), getOffsetFromIndices(), getOtherIncomingValue(), GetPointerOperand(), getShiftedValue(), hasProfileData(), INITIALIZE_PASS(), insertUniqueBackedgeBlock(), inversePermutation(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), IsEquivalentPHI(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), llvm::InductionDescriptor::isFPInductionPHI(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), isObjectDereferencedInBlock(), isReturnNonNull(), isSafeAndProfitableToSinkLoad(), isSafeAndProfitableToSpeculateAroundPHI(), isSafePHIToSpeculate(), isSameUnderlyingObjectInLoop(), llvm::LoopVectorizationLegality::isUniform(), IVUseShouldUsePostIncValue(), MarkBlocksLiveIn(), mayUsePostIncMode(), MergeAliasResults(), llvm::JumpThreadingPass::ProcessBranchOnPHI(), processPHI(), promoteSingleBlockAlloca(), redirectValuesFromPredecessorsToPhi(), relocationViaAlloca(), removeEmptyCleanup(), llvm::BasicBlock::removePredecessor(), replaceUndefValuesInPhi(), returnEdge(), simplifyCommonValuePhi(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), SplitCriticalSideEffectEdges(), ThreadCmpOverPHI(), llvm::VPRecipeBuilder::tryToBlend(), llvm::JumpThreadingPass::TryToUnfoldSelect(), tryToVectorizeHorReductionOrInstOperands(), llvm::UnrollRuntimeLoopRemainder(), UpdatePHINodes(), updatePredecessorProfileMetadata(), llvm::SSAUpdaterTraits< SSAUpdater >::ValueIsNewPHI(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), llvm::InstCombiner::visitPHINode(), and llvm::VPBlendRecipe::VPBlendRecipe().
getOperandNumForIncomingValue()
static unsigned llvm::PHINode::getOperandNumForIncomingValue (unsigned i) inline static
Definition at line 2660 of file Instructions.h.
Referenced by cloneInstructionWithNewAddressSpace(), createCallInst(), and llvm::formLCSSAForInstructions().
hasConstantOrUndefValue()
bool PHINode::hasConstantOrUndefValue () const
Whether the specified PHI node always merges together the same value, assuming undefs are equal to a unique non-undef value.
hasConstantOrUndefValue - Whether the specified PHI node always merges together the same value, assuming that undefs result in the same value as non-undefs.
Unlike hasConstantValue, this does not return a value because the unique non-undef incoming value need not dominate the PHI node.
Definition at line 176 of file Instructions.cpp.
References llvm::User::allocHungoffUses(), llvm::numbers::e, E, llvm::User::getNumOperands(), llvm::User::getOperandList(), llvm::Value::getType(), I, llvm::cl::init(), llvm::AllocaInst::Instruction, and llvm::LandingPadInst::isCleanup().
Referenced by llvm::DivergenceAnalysis::addUniformOverride().
hasConstantValue()
Value * PHINode::hasConstantValue () const
If the specified PHI node always merges together the same value, return the value, otherwise return null.
hasConstantValue - If the specified PHI node always merges together the same value, return the value, otherwise return null.
Definition at line 156 of file Instructions.cpp.
References llvm::numbers::e, llvm::UndefValue::get(), and llvm::AllocaInst::getType().
Referenced by computeKnownBitsFromOperator(), llvm::BasicBlock::removePredecessor(), and llvm::ObjectSizeOffsetEvaluator::visitPHINode().
incoming_values() [1/2]
op_range llvm::PHINode::incoming_values () inline
Definition at line 2640 of file Instructions.h.
References llvm::User::operands().
Referenced by canEvaluateSExtd(), canEvaluateShifted(), canEvaluateTruncated(), collectValuesToDemote(), findInnerReductionPhi(), getBaseType(), llvm::PhiValues::invalidate(), isFunctionMallocLike(), isSafeAndProfitableToSinkLoad(), isTriviallyReplaceablePHI(), mayUsePostIncMode(), MergeAliasResults(), patchAndReplaceAllUsesWith(), PHIsEqualValue(), SimplifyPHINode(), ThreadBinOpOverPHI(), and llvm::JumpThreadingPass::TryToUnfoldSelectInCurrBB().
incoming_values() [2/2]
const_op_range llvm::PHINode::incoming_values () const inline
Definition at line 2642 of file Instructions.h.
References llvm::User::operands().
removeIncomingValue() [1/2]
Value * PHINode::removeIncomingValue (unsigned Idx, bool DeletePHIIfEmpty = true)
Remove an incoming value.
This is useful if a predecessor basic block is deleted. The value removed is returned.
If the last incoming value for a PHI node is removed (and DeletePHIIfEmpty is true), the PHI node is destroyed and any uses of it are replaced with dummy values. The only time there should be zero incoming values to a PHI node is when the block is dead, so this strategy is sound.
Definition at line 117 of file Instructions.cpp.
References llvm::copy(), llvm::numbers::e, llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::User::getNumOperands(), llvm::AllocaInst::getType(), llvm::User::growHungoffUses(), llvm::User::Op(), llvm::User::op_begin(), llvm::User::op_end(), llvm::Value::replaceAllUsesWith(), and llvm::User::setNumHungOffUseOperands().
Referenced by llvm::CloneAndPruneIntoFromInst(), CloneLoopBlocks(), llvm::CodeExtractor::findInputsOutputs(), fixPhis(), hasProfileData(), insertUniqueBackedgeBlock(), redirectValuesFromPredecessorsToPhi(), removeEmptyCleanup(), llvm::BasicBlock::removePredecessor(), RemoveSwitchAfterSelectConversion(), RewriteUsesOfClonedInstructions(), and UpdatePHINodes().
removeIncomingValue() [2/2]
Value* llvm::PHINode::removeIncomingValue (const BasicBlock * BB, bool DeletePHIIfEmpty = true) inline
Definition at line 2723 of file Instructions.h.
References assert().
replaceIncomingBlockWith()
void llvm::PHINode::replaceIncomingBlockWith (const BasicBlock * Old, BasicBlock * New) inline
Replace every incoming basic block Old to basic block New.
Definition at line 2695 of file Instructions.h.
References assert(), llvm::User::getNumOperands(), and llvm::User::Op().
Referenced by llvm::BasicBlock::replacePhiUsesWith().
setIncomingBlock()
void llvm::PHINode::setIncomingBlock (unsigned i, BasicBlock * BB) inline
Definition at line 2689 of file Instructions.h.
References assert().
Referenced by llvm::CloneAndPruneIntoFromInst(), CloneLoopBlocks(), llvm::CodeExtractor::extractCodeRegion(), fixPhis(), insertUniqueBackedgeBlock(), mayLoopAccessLocation(), moveLCSSAPhis(), llvm::SplitCriticalEdge(), updatePhiNodes(), and llvm::InstCombiner::visitPHINode().
setIncomingValue()
void llvm::PHINode::setIncomingValue (unsigned i, Value * V) inline
Definition at line 2653 of file Instructions.h.
References assert(), llvm::AllocaInst::getType(), llvm::Value::getType(), and llvm::User::setOperand().
Referenced by llvm::CloneAndPruneIntoFromInst(), CloneLoopBlocks(), ConvertToSInt(), llvm::InnerLoopVectorizer::fixReduction(), ForwardSwitchConditionToPHI(), getShiftedValue(), insertUniqueBackedgeBlock(), mayUsePostIncMode(), moveLCSSAPhis(), processPHI(), relocationViaAlloca(), replaceUndefValuesInPhi(), llvm::JumpThreadingPass::UnfoldSelectInstr(), and llvm::InstCombiner::visitPHINode().
setIncomingValueForBlock()
void llvm::PHINode::setIncomingValueForBlock (const BasicBlock * BB, Value * V) inline
Set every incoming value(s) for block BB to V.
Definition at line 2746 of file Instructions.h.
References assert(), llvm::User::getNumOperands(), and llvm::User::Op().
Referenced by ConnectEpilog(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), and llvm::peelLoop().
Friends And Related Function Documentation
Instruction
friend class Instruction friend
Definition at line 2578 of file Instructions.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Instructions.h
lib/IR/Instructions.cpp