LLVM: llvm::vfs::VFSFromYamlDirIterImpl Class Reference
llvm::vfs::VFSFromYamlDirIterImpl Class Reference
Public Member Functions
VFSFromYamlDirIterImpl (const Twine &Path, RedirectingFileSystem::RedirectingDirectoryEntry::iterator Begin, RedirectingFileSystem::RedirectingDirectoryEntry::iterator End, bool IterateExternalFS, FileSystem &ExternalFS, std::error_code &EC)
std::error_code increment () override
Sets CurrentEntry to the next entry in the directory on success, to directory_entry() at end, or returns a system-defined error_code.
Public Member Functions inherited from llvm::vfs::detail::DirIterImpl
virtual ~DirIterImpl ()
Additional Inherited Members
Public Attributes inherited from llvm::vfs::detail::DirIterImpl
directory_entry CurrentEntry
Detailed Description
Definition at line 1004 of file VirtualFileSystem.cpp.
Constructor & Destructor Documentation
VFSFromYamlDirIterImpl()
VFSFromYamlDirIterImpl::VFSFromYamlDirIterImpl (const Twine & Path, RedirectingFileSystem::RedirectingDirectoryEntry::iterator Begin, RedirectingFileSystem::RedirectingDirectoryEntry::iterator End, bool IterateExternalFS, FileSystem & ExternalFS, std::error_code & EC)
Definition at line 2056 of file VirtualFileSystem.cpp.
Member Function Documentation
increment()
std::error_code VFSFromYamlDirIterImpl::increment () override virtual
Sets CurrentEntry to the next entry in the directory on success, to directory_entry() at end, or returns a system-defined error_code.
Implements llvm::vfs::detail::DirIterImpl.
Definition at line 2066 of file VirtualFileSystem.cpp.
References llvm::sys::path::append(), assert(), llvm::vfs::detail::DirIterImpl::CurrentEntry, llvm::sys::fs::directory_file, llvm::vfs::RedirectingFileSystem::EK_Directory, llvm::vfs::RedirectingFileSystem::EK_File, llvm::StringRef::empty(), llvm::sys::path::filename(), llvm::vfs::directory_iterator::increment(), llvm::StringSet< AllocatorTy >::insert(), llvm_unreachable, llvm::no_such_file_or_directory, llvm::vfs::directory_entry::path(), llvm::sys::fs::regular_file, llvm::SmallString< InternalLen >::str(), and llvm::sys::fs::type_unknown.
The documentation for this class was generated from the following file:
lib/Support/VirtualFileSystem.cpp