LLVM: llvm::XCoreMCInstLower Class Reference
llvm::XCoreMCInstLower Class Reference
This class is used to lower an MachineInstr into an MCInst.
#include "Target/XCore/XCoreMCInstLower.h"
Public Member Functions
XCoreMCInstLower (class AsmPrinter &asmprinter)
void Initialize (MCContext *C)
void Lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand LowerOperand (const MachineOperand &MO, unsigned offset=0) const
Detailed Description
This class is used to lower an MachineInstr into an MCInst.
Definition at line 24 of file XCoreMCInstLower.h.
Constructor & Destructor Documentation
XCoreMCInstLower()
XCoreMCInstLower::XCoreMCInstLower (class AsmPrinter & asmprinter)
Definition at line 26 of file XCoreMCInstLower.cpp.
Member Function Documentation
Initialize()
void XCoreMCInstLower::Initialize (MCContext * C)
Definition at line 29 of file XCoreMCInstLower.cpp.
References llvm::MCID::Add, assert(), C, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::ARMBuildAttrs::Symbol, and llvm::MCSymbolRefExpr::VK_None.
Lower()
void XCoreMCInstLower::Lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 103 of file XCoreMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::numbers::e, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCOperand::isValid(), LowerOperand(), and llvm::MCInst::setOpcode().
LowerOperand()
MCOperand XCoreMCInstLower::LowerOperand (const MachineOperand & MO, unsigned offset = 0) const
Definition at line 77 of file XCoreMCInstLower.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::MachineOperand::MO_RegisterMask.
Referenced by Lower().
The documentation for this class was generated from the following files:
lib/Target/XCore/XCoreMCInstLower.h
lib/Target/XCore/XCoreMCInstLower.cpp