LLVM: llvm::MDNode Class Reference
llvm::MDNode Class Reference
Metadata node.
#include "llvm/IR/Metadata.h"
Classes
struct HasCachedHash
Public Types
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Protected Types
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata *> Ops1, ArrayRef< Metadata *> Ops2=None)
~MDNode ()=default
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Friends
class ReplaceableMetadataImpl
class LLVMContextImpl
Additional Inherited Members
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Metadata node.
Metadata nodes can be uniqued, like constants, or distinct. Temporary metadata nodes (with full support for RAUW) can be used to delay uniquing until forward references are known. The basic metadata node is an MDTuple.
There is limited support for RAUW at construction time. At construction time, if any operand is a temporary node (or an unresolved uniqued node, which indicates a transitive temporary operand), the node itself will be unresolved. As soon as all operands become resolved, it will drop RAUW support permanently.
If an unresolved node is part of a cycle, resolveCycles() needs to be called on some member of the cycle once all temporary nodes have been replaced.
Definition at line 872 of file Metadata.h.
Member Typedef Documentation
mutable_op_range
using llvm::MDNode::mutable_op_range = iterator_range<MDOperand *> protected
Definition at line 904 of file Metadata.h.
op_iterator
using llvm::MDNode::op_iterator = const MDOperand *
Definition at line 1064 of file Metadata.h.
op_range
using llvm::MDNode::op_range = iterator_range<op_iterator>
Definition at line 1065 of file Metadata.h.
Constructor & Destructor Documentation
MDNode() [1/2]
MDNode::MDNode (LLVMContext & Context, unsigned ID, StorageType Storage, ArrayRef< Metadata *> Ops1, ArrayRef< Metadata *> Ops2 = None) protected
Definition at line 505 of file Metadata.cpp.
References isUniqued(), and setOperand().
~MDNode()
llvm::MDNode::~MDNode () protected default
MDNode() [2/2]
llvm::MDNode::MDNode (const MDNode &) delete
Member Function Documentation
classof()
static bool llvm::MDNode::classof (const Metadata * MD) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 1086 of file Metadata.h.
References A, B, llvm::Metadata::getMetadataID(), and intersect().
clone()
TempMDNode MDNode::clone () const
Create a (temporary) clone of this.
Definition at line 523 of file Metadata.cpp.
References llvm::Metadata::getMetadataID(), and llvm_unreachable.
Referenced by llvm::DIType::clone(), cloneOrBuildODR(), and wrapConstantAsMetadata().
concatenate()
MDNode * MDNode::concatenate (MDNode * A, MDNode * B) static
Methods for metadata merging.
Definition at line 897 of file Metadata.cpp.
References B, getContext(), getOrSelfReference(), op_begin(), and op_end().
Referenced by AddAliasScopeMetadata(), llvm::LoopVersioning::annotateInstWithNoAlias(), CloneAliasScopeMetadata(), getMostGenericAliasScope(), and PropagateParallelLoopAccessMetadata().
deleteTemporary()
void MDNode::deleteTemporary (MDNode * N) static
Deallocate a node created by getTemporary.
Calls replaceAllUsesWith(nullptr) before deleting, so any remaining references will be reset.
Definition at line 832 of file Metadata.cpp.
References assert(), isTemporary(), and replaceAllUsesWith().
Referenced by LLVMDisposeTemporaryMDNode(), and llvm::TempMDNodeDeleter::operator()().
dropAllReferences()
void MDNode::dropAllReferences () protected
Definition at line 691 of file Metadata.cpp.
References assert(), E, llvm::Metadata::getMetadataID(), getNumOperands(), getOperand(), llvm::ContextAndReplaceableUses::getReplaceableUses(), llvm::ContextAndReplaceableUses::hasReplaceableUses(), I, isResolved(), isUniqued(), llvm_unreachable, llvm::RISCVFenceField::O, op_begin(), llvm::Ref, llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), resolve(), llvm::ReplaceableMetadataImpl::resolveAllUses(), setOperand(), storeDistinctInContext(), llvm::ContextAndReplaceableUses::takeReplaceableUses(), and llvm::Metadata::Uniqued.
Referenced by llvm::NamedMDNode::~NamedMDNode().
get()
MDTuple * llvm::MDNode::get (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Definition at line 1174 of file Metadata.h.
References llvm::MDTuple::get().
Referenced by AddAliasScopeMetadata(), AddCalls(), llvm::Module::addModuleFlag(), AddRuntimeUnrollDisableMetaData(), llvm::GlobalObject::addVCallVisibilityMetadata(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::annotateValueSite(), llvm::DIExpression::append(), canonicalizeMetadataForValue(), CloneAliasScopeMetadata(), llvm::DILocation::cloneWithDiscriminator(), collectCallSiteParameters(), llvm::GlobalObject::copyMetadata(), llvm::copyRangeMetadata(), createAccessTag(), llvm::MDBuilder::createAliasScope(), llvm::MDBuilder::createAliasScopeDomain(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::MDBuilder::createAnonymousAARoot(), llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createBasicType(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MDBuilder::createBranchWeights(), llvm::MDBuilder::createCallbackEncoding(), llvm::MDBuilder::createCallees(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCommonBlock(), llvm::DIBuilder::createConstantValueExpression(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createExpression(), llvm::createFalkorMarkStridedAccessesPass(), llvm::DIBuilder::createFile(), llvm::DIBuilder::createForwardDecl(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), llvm::DIBuilder::createFriend(), llvm::MDBuilder::createFunctionEntryCount(), llvm::MDBuilder::createFunctionSectionPrefix(), llvm::DIBuilder::createGlobalVariableExpression(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::DIBuilder::createLexicalBlockFile(), llvm::DIBuilder::createMacro(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::MDBuilder::createMisExpect(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::createObjCARCOptPass(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::OpenMPIRBuilder::CreateParallel(), llvm::createPGOFuncNameMetadata(), llvm::DIBuilder::createPointerType(), llvm::DIBuilder::createQualifiedType(), llvm::MDBuilder::createRange(), llvm::DIBuilder::createReferenceType(), llvm::createSIAddIMGInitPass(), llvm::DIBuilder::createStaticMemberType(), createStringMetadata(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubroutineType(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAARoot(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::DIBuilder::createTemplateParameterPack(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::MDBuilder::createUnpredictable(), llvm::DIBuilder::createUnspecifiedType(), llvm::DIBuilder::createVariantMemberType(), llvm::DIBuilder::createVariantPart(), llvm::DIBuilder::createVectorType(), llvm::createX86PadShortFunctions(), llvm::X86InstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), DisableAllLoopOptsOnLoop(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::DIExpression::extractAddressClass(), extractMDNode(), llvm::DIBuilder::finalize(), llvm::DIBuilder::finalizeSubprogram(), findBasePointer(), foldCtpop(), foldCttzCtlz(), llvm::DebugLoc::get(), AAValueConstantRangeImpl::getMDNodeForConstantRange(), llvm::DILocation::getMergedLocation(), getMostGenericRange(), getMulHu(), getNewValueJumpOpcode(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateTypeArray(), getOrSelfReference(), getSubprogram(), hasOnlyUniformBranches(), INITIALIZE_PASS(), InsertReturnAddressAuth(), instrumentMaskedLoadOrStore(), IsInterestingCmp(), isKnownTypeIdMember(), LLVMDIBuilderCreateDebugLocation(), LLVMMDNodeInContext(), LLVMMDNodeInContext2(), llvm::makeFollowupLoopID(), llvm::MDBuilder::mergeCallbackEncodings(), parseGlobalValue(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::DIExpression::prependOpcodes(), PushArgMD(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::DIBuilder::replaceTemporary(), RetagMask(), rotateSign(), llvm::CGProfilePass::run(), selectJumpTableArmEncoding(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::Loop::setLoopAlreadyUnrolled(), setNoClobberMetadata(), setUniformMetadata(), signOutlinedFunction(), splitGlobal(), llvm::StripDebugInfo(), stripDebugLocFromLoopID(), llvm::Instruction::swapProfMetadata(), llvm::DISubprogram::toSPFlags(), transferSRADebugInfo(), TryToShrinkGlobalToBoolean(), llvm::uniteAccessGroups(), llvm::CallInst::updateProfWeight(), llvm::UpgradeModuleFlags(), and llvm::UpgradeTBAANode().
getContext()
LLVMContext& llvm::MDNode::getContext () const inline
Definition at line 932 of file Metadata.h.
References I.
Referenced by llvm::GlobalObject::addMetadata(), llvm::GlobalObject::addTypeMetadata(), llvm::GlobalObject::addVCallVisibilityMetadata(), llvm::DIExpression::append(), llvm::GlobalObject::clearMetadata(), concatenate(), llvm::GlobalObject::copyMetadata(), createAccessTag(), llvm::DIExpression::createFragmentExpression(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::GlobalObject::eraseMetadata(), llvm::DIExpression::extractAddressClass(), llvm::Instruction::extractProfTotalWeight(), fixupLineNumbers(), llvm::DebugLoc::get(), llvm::GlobalObject::getAllMetadata(), getIRBForDbgInsertion(), llvm::DILocation::getMergedLocation(), llvm::GlobalObject::getMetadata(), getMostGenericRange(), intersect(), llvm::makeFollowupLoopID(), llvm::DIExpression::prependOpcodes(), llvm::Instruction::setAAMetadata(), llvm::GlobalObject::setMetadata(), storeDistinctInContext(), llvm::StripDebugInfo(), stripDebugLocFromLoopID(), llvm::Instruction::swapProfMetadata(), llvm::uniteAccessGroups(), and llvm::UpgradeTBAANode().
getDistinct()
MDTuple * llvm::MDNode::getDistinct (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Definition at line 1182 of file Metadata.h.
References llvm::MDTuple::getDistinct().
Referenced by llvm::DebugLoc::appendInlinedAt(), llvm::DICompositeType::buildODRType(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createGlobalVariableExpression(), llvm::DIBuilder::createLexicalBlock(), fixupLineNumbers(), FunctionNumber(), getSubprogram(), inlineLoopID(), llvm::makePostTransformationMetadata(), and llvm::StripDebugInfo().
getIfExists()
MDTuple * llvm::MDNode::getIfExists (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Definition at line 1178 of file Metadata.h.
References llvm::MDTuple::getIfExists().
getMostGenericAliasScope()
MDNode * MDNode::getMostGenericAliasScope (MDNode * A, MDNode * B) static
Definition at line 924 of file Metadata.cpp.
References concatenate().
Referenced by llvm::combineMetadata(), llvm::Instruction::getAAMetadata(), and llvm::propagateMetadata().
getMostGenericAlignmentOrDereferenceable()
MDNode * MDNode::getMostGenericAlignmentOrDereferenceable (MDNode * A, MDNode * B) static
Definition at line 1051 of file Metadata.cpp.
References B, getOperand(), and llvm::ConstantInt::getZExtValue().
Referenced by llvm::combineMetadata().
getMostGenericFPMath()
MDNode * MDNode::getMostGenericFPMath (MDNode * A, MDNode * B) static
Definition at line 931 of file Metadata.cpp.
References B, llvm::APFloatBase::cmpLessThan, llvm::APFloat::compare(), and getOperand().
Referenced by llvm::combineMetadata(), and llvm::propagateMetadata().
getMostGenericRange()
MDNode * MDNode::getMostGenericRange (MDNode * A, MDNode * B) static
Definition at line 979 of file Metadata.cpp.
References addRange(), llvm::ConstantAsMetadata::get(), get(), getContext(), getNumOperands(), getOperand(), llvm::ConstantInt::getValue(), I, llvm::ConstantRange::isFullSet(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), Size, llvm::SmallVectorBase::size(), llvm::APInt::slt(), and tryMergeRange().
Referenced by llvm::combineMetadata().
getMostGenericTBAA()
MDNode * MDNode::getMostGenericTBAA (MDNode * A, MDNode * B) static
Definition at line 476 of file TypeBasedAliasAnalysis.cpp.
References matchAccessTags().
Referenced by llvm::combineMetadata(), llvm::Instruction::getAAMetadata(), and llvm::propagateMetadata().
getNumOperands()
unsigned llvm::MDNode::getNumOperands () const inline
Return number of MDNode operands.
Definition at line 1083 of file Metadata.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), AddRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), addToAccessGroupList(), llvm::cacheAnnotationFromMD(), checkMDProf(), CloneAliasScopeMetadata(), llvm::FunctionComparator::cmpMem(), llvm::MDNodeOpsKey::compareOps(), llvm::computeKnownBitsFromRangeMetadata(), createAccessTag(), llvm::MDBuilder::createMutableTBAAAccessTag(), dropAllReferences(), llvm::MachineInstr::emitError(), EmitGCCInlineAsmStr(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::MDTupleTypedArrayWrapper< T >::empty(), llvm::findOptionMDForLoopID(), llvm::findStringMetadataForLoop(), GetBranchWeights(), llvm::getConstantRangeFromMetadata(), llvm::DOTGraphTraits< const Function * >::getEdgeAttributes(), llvm::ProfileSummary::getFromMD(), llvm::Loop::getLoopID(), getMostGenericRange(), llvm::NamedMDNode::getOperand(), getOptimizationFlags(), getOptionalBoolLoopAttribute(), getParentPad(), getSummaryFromMD(), llvm::GetUnrollMetadata(), getVal(), llvm::getValueProfDataFromInst(), llvm::SwitchInstProfUpdateWrapper::init(), inlineLoopID(), llvm::intersectAccessGroups(), AAValueConstantRangeImpl::isBetterRange(), isContiguous(), isFuncOrArgAttr(), isKeyValuePair(), isKnownTypeIdMember(), isNewFormatTBAATypeNode(), IsRootTBAANode(), IsScalarTBAANodeImpl(), isStructPathTBAA(), llvm::LTOModule::makeBuffer(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), llvm::MDBuilder::mergeCallbackEncodings(), llvm::LocationMetadata::parse(), llvm::DebugInfoFinder::processValue(), rangeMetadataExcludesValue(), llvm::MachinePipeliner::runOnMachineFunction(), llvm::Loop::setLoopID(), llvm::NamedMDNode::setOperand(), llvm::DITypeRefArray::size(), llvm::MDTupleTypedArrayWrapper< T >::size(), srcMgrDiagHandler(), llvm::StripDebugInfo(), llvm::Instruction::swapProfMetadata(), UnrollAndJamCountPragmaValue(), UnrollCountPragmaValue(), UpdatePDTWorklist(), llvm::UpgradeModuleFlags(), llvm::UpgradeTBAANode(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), llvm::TBAAVerifier::visitTBAAMetadata(), wrapConstantAsMetadata(), and WriteConstantInternal().
getOperand()
const MDOperand& llvm::MDNode::getOperand (unsigned I) const inline
Definition at line 1077 of file Metadata.h.
References assert(), and I.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), AccessQualFromMD(), AddRuntimeUnrollDisableMetaData(), ArgTypeFromMD(), llvm::cacheAnnotationFromMD(), checkMDProf(), CloneAliasScopeMetadata(), llvm::FunctionComparator::cmpMem(), llvm::computeKnownBitsFromRangeMetadata(), llvm::MDBuilder::createMutableTBAAAccessTag(), dropAllReferences(), llvm::MachineInstr::emitError(), EmitGCCInlineAsmStr(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::findOptionMDForLoopID(), llvm::findStringMetadataForLoop(), getARClassRegisterMask(), getAssociatedSymbol(), GetBranchWeights(), llvm::AbstractCallSite::getCallbackUses(), llvm::getConstantRangeFromMetadata(), llvm::DOTGraphTraits< const Function * >::getEdgeAttributes(), llvm::Function::getEntryCount(), llvm::FPMathOperator::getFPAccuracy(), llvm::ProfileSummary::getFromMD(), getIntOperandFromRegisterString(), llvm::Loop::getLoopID(), getMDNodeOperandImpl(), getMostGenericAlignmentOrDereferenceable(), getMostGenericFPMath(), getMostGenericRange(), getOptimizationFlags(), getOptionalBoolLoopAttribute(), getParentPad(), getSummaryFromMD(), llvm::GetUnrollMetadata(), getVal(), llvm::getValueProfDataFromInst(), HasAnyUnrollPragma(), HasBranchWeights(), llvm::SwitchInstProfUpdateWrapper::init(), inlineLoopID(), AAValueConstantRangeImpl::isBetterRange(), isContiguous(), isFuncOrArgAttr(), isKeyValuePair(), isKnownTypeIdMember(), llvm::SelectionDAGISel::IsLegalToFold(), isNewFormatTBAATypeNode(), IsScalarTBAANodeImpl(), isStructPathTBAA(), llvm::LTOModule::makeBuffer(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), llvm::MDBuilder::mergeCallbackEncodings(), llvm::DITypeRefArray::operator[](), llvm::MDTupleTypedArrayWrapper< T >::operator[](), llvm::LocationMetadata::parse(), rangeMetadataExcludesValue(), replaceOperandWith(), llvm::MachinePipeliner::runOnMachineFunction(), selectJumpTableArmEncoding(), llvm::Loop::setLoopID(), srcMgrDiagHandler(), llvm::Instruction::swapProfMetadata(), UnrollAndJamCountPragmaValue(), UnrollCountPragmaValue(), UpdatePDTWorklist(), llvm::UpgradeModuleFlags(), UpgradeRetainReleaseMarker(), llvm::UpgradeTBAANode(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), llvm::TBAAVerifier::visitTBAAMetadata(), and wrapConstantAsMetadata().
getTemporary()
TempMDTuple llvm::MDNode::getTemporary (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Definition at line 1186 of file Metadata.h.
References llvm::MDTuple::getTemporary().
Referenced by llvm::MDBuilder::createAnonymousAARoot(), llvm::DIBuilder::createReplaceableCompositeType(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTempGlobalVariableFwdDecl(), llvm::DIBuilder::createTempMacroFile(), llvm::makePostTransformationMetadata(), and stripDebugLocFromLoopID().
intersect()
MDNode * MDNode::intersect (MDNode * A, MDNode * B) static
Definition at line 911 of file Metadata.cpp.
References getContext(), getOrSelfReference(), llvm::is_contained(), op_begin(), and op_end().
Referenced by llvm::combineMetadata(), llvm::Instruction::getAAMetadata(), and llvm::propagateMetadata().
isDistinct()
bool llvm::MDNode::isDistinct () const inline
Definition at line 951 of file Metadata.h.
References llvm::Metadata::Distinct, and llvm::Metadata::Storage.
Referenced by cloneOrBuildODR(), getOptimizationFlags(), hasConflictingReferenceFlags(), isOperandUnresolved(), llvm::ValueEnumerator::print(), rotateSign(), and llvm::StripDebugInfo().
isResolved()
bool llvm::MDNode::isResolved () const inline
Check if node is fully resolved.
If isTemporary(), this always returns false; if isDistinct(), this always returns true.
If isUniqued(), returns true if this has already dropped RAUW support (because all operands are resolved).
As forward declarations are resolved, their containers should get resolved automatically. However, if this (or one of its operands) is involved in a cycle, resolveCycles() needs to be called explicitly.
Definition at line 948 of file Metadata.h.
Referenced by llvm::DIBuilder::DIBuilder(), dropAllReferences(), llvm::DIBuilder::finalize(), forEachUser(), isOperandUnresolved(), llvm::LexicalScope::LexicalScope(), llvm::DIBuilder::replaceArrays(), llvm::DIBuilder::replaceVTableHolder(), resolve(), resolveCycles(), storeDistinctInContext(), and wrapConstantAsMetadata().
isTBAAVtableAccess()
bool MDNode::isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Definition at line 453 of file TypeBasedAliasAnalysis.cpp.
References B, isStructPathTBAA(), matchAccessTags(), and llvm::Tag.
isTemporary()
bool llvm::MDNode::isTemporary () const inline
Definition at line 952 of file Metadata.h.
References llvm::Metadata::Storage, and llvm::Metadata::Temporary.
Referenced by deleteTemporary(), llvm::DIBuilder::finalizeSubprogram(), forEachUser(), isOperandUnresolved(), and resolve().
isUniqued()
bool llvm::MDNode::isUniqued () const inline
Definition at line 950 of file Metadata.h.
References llvm::Metadata::Storage, and llvm::Metadata::Uniqued.
Referenced by dropAllReferences(), isOperandUnresolved(), MDNode(), replaceOperandWith(), resolve(), setOperand(), and wrapConstantAsMetadata().
mutable_begin()
MDOperand* llvm::MDNode::mutable_begin () inline protected
Definition at line 901 of file Metadata.h.
Referenced by replaceOperandWith(), and setOperand().
mutable_end()
MDOperand* llvm::MDNode::mutable_end () inline protected
Definition at line 902 of file Metadata.h.
mutable_operands()
mutable_op_range llvm::MDNode::mutable_operands () inline protected
Definition at line 906 of file Metadata.h.
References Context, and N.
Referenced by isOperandUnresolved().
op_begin()
op_iterator llvm::MDNode::op_begin () const inline
Definition at line 1067 of file Metadata.h.
Referenced by llvm::DITypeRefArray::begin(), llvm::MDTupleTypedArrayWrapper< T >::begin(), llvm::MDNodeOpsKey::calculateHash(), llvm::MDNodeOpsKey::compareOps(), concatenate(), dropAllReferences(), intersect(), llvm::ValueEnumerator::print(), stripDebugLocFromLoopID(), and wrapConstantAsMetadata().
op_end()
op_iterator llvm::MDNode::op_end () const inline
Definition at line 1071 of file Metadata.h.
Referenced by llvm::MDNodeOpsKey::calculateHash(), concatenate(), llvm::DITypeRefArray::end(), llvm::MDTupleTypedArrayWrapper< T >::end(), intersect(), llvm::ValueEnumerator::print(), and stripDebugLocFromLoopID().
operands()
op_range llvm::MDNode::operands () const inline
Definition at line 1075 of file Metadata.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), addToAccessGroupList(), llvm::TypeFinder::clear(), collectMDInDomain(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), forEachUser(), llvm::AbstractCallSite::getCallbackUses(), getOptimizationFlags(), getSummaryFromMD(), hasConflictingReferenceFlags(), hasSelfReference(), llvm::Loop::isAnnotatedParallel(), isOperandUnresolved(), llvm::makeFollowupLoopID(), llvm::ValueEnumerator::print(), llvm::DIBuilder::replaceVTableHolder(), resolveCycles(), rotateSign(), llvm::StripDebugInfo(), stripDebugLocFromLoopID(), and wrapConstantAsMetadata().
operator delete() [1/3]
LLVM_NO_SANITIZE_MEMORY_ATTRIBUTE void MDNode::operator delete (void * Mem) protected
Definition at line 494 of file Metadata.cpp.
References llvm::alignTo(), E, N, and llvm::RISCVFenceField::O.
operator delete() [2/3]
void llvm::MDNode::operator delete (void * , unsigned) inline protected
Required by std, but never called.
Definition at line 890 of file Metadata.h.
References llvm_unreachable.
operator delete() [3/3]
void llvm::MDNode::operator delete (void * , unsigned , bool) inline protected
Required by std, but never called.
Definition at line 895 of file Metadata.h.
References llvm_unreachable.
operator new() [1/2]
void * MDNode::operator new (size_t Size, unsigned NumOps) protected
Definition at line 480 of file Metadata.cpp.
References llvm::alignTo(), E, llvm::RISCVFenceField::O, and Size.
operator new() [2/2]
void* llvm::MDNode::operator new (size_t) delete
operator=()
void llvm::MDNode::operator= (const MDNode &) delete
replaceAllUsesWith()
void llvm::MDNode::replaceAllUsesWith (Metadata * MD) inline
RAUW a temporary.
Precondition
isTemporary() must be true.
Definition at line 957 of file Metadata.h.
References assert().
Referenced by deleteTemporary(), hasSelfReference(), and llvm::DIBuilder::replaceTemporary().
replaceOperandWith()
void MDNode::replaceOperandWith (unsigned I, Metadata * New)
Replace a specific operand.
Definition at line 860 of file Metadata.cpp.
References getOperand(), isUniqued(), mutable_begin(), and setOperand().
Referenced by AddRuntimeUnrollDisableMetaData(), llvm::MDBuilder::createAnonymousAARoot(), DisableAllLoopOptsOnLoop(), inlineLoopID(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), stripDebugLocFromLoopID(), and wrapConstantAsMetadata().
replaceWithDistinct()
template<class T > static std::enable_if<std::is_base_of<MDNode, T>::value, T *>::type llvm::MDNode::replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a distinct one.
Create a distinct version of N – in place, if possible – and return it. Takes ownership of the temporary node.
Definition at line 1002 of file Metadata.h.
References llvm::Metadata::handleChangedOperand(), llvm::Ref, llvm::Metadata::Storage, and llvm::SPII::Store.
Referenced by cloneOrBuildODR(), and llvm::DIBuilder::createArtificialSubprogram().
replaceWithPermanent()
template<class T > static std::enable_if<std::is_base_of<MDNode, T>::value, T *>::type llvm::MDNode::replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a permanent one.
Try to create a uniqued version of N – in place, if possible – and return it. If N cannot be uniqued, return a distinct node instead.
Definition at line 980 of file Metadata.h.
replaceWithUniqued()
template<class T > static std::enable_if<std::is_base_of<MDNode, T>::value, T *>::type llvm::MDNode::replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a uniqued one.
Create a uniqued version of N – in place, if possible – and return it. Takes ownership of the temporary node.
Precondition
N does not self-reference.
Definition at line 992 of file Metadata.h.
Referenced by createTypeWithFlags(), llvm::DIBuilder::replaceTemporary(), and wrapConstantAsMetadata().
resolve()
void MDNode::resolve ()
Resolve a unique, unresolved node.
Definition at line 577 of file Metadata.cpp.
References assert(), llvm::ContextAndReplaceableUses::hasReplaceableUses(), isOperandUnresolved(), isResolved(), isTemporary(), isUniqued(), and llvm::ContextAndReplaceableUses::takeReplaceableUses().
Referenced by dropAllReferences(), and resolveCycles().
resolveCycles()
void MDNode::resolveCycles ()
Resolve cycles.
Once all forward declarations have been resolved, force cycles to be resolved.
Precondition
No operands (or operands' operands, etc.) have isTemporary().
Definition at line 622 of file Metadata.cpp.
References assert(), isResolved(), N, operands(), and resolve().
Referenced by llvm::DIBuilder::finalize(), and wrapConstantAsMetadata().
setOperand()
void MDNode::setOperand (unsigned I, Metadata * New) protected
Set an operand.
Sets the operand directly, without worrying about uniquing.
Definition at line 872 of file Metadata.cpp.
References assert(), I, isUniqued(), mutable_begin(), and llvm::MDOperand::reset().
Referenced by dropAllReferences(), MDNode(), replaceOperandWith(), and llvm::salvageDebugInfoForDbgValues().
storeDistinctInContext()
void MDNode::storeDistinctInContext () protected
Definition at line 838 of file Metadata.cpp.
References assert(), llvm::Metadata::Distinct, llvm::LLVMContextImpl::DistinctMDNodes, getContext(), llvm::Metadata::getMetadataID(), isResolved(), llvm_unreachable, llvm::LLVMContext::pImpl, and llvm::Metadata::Storage.
Referenced by dropAllReferences(), and isOperandUnresolved().
storeImpl() [1/2]
template<class T , class StoreT > T * llvm::MDNode::storeImpl (T * N, StorageType Storage, StoreT & Store) static protected
Definition at line 42 of file MetadataImpl.h.
References llvm::Metadata::Distinct, N, llvm::Metadata::Temporary, and llvm::Metadata::Uniqued.
Referenced by adjustColumn(), llvm::DIFile::getChecksumKind(), and isCanonical().
storeImpl() [2/2]
template<class T > T * llvm::MDNode::storeImpl (T * N, StorageType Storage) static protected
Definition at line 28 of file MetadataImpl.h.
References llvm::Metadata::Distinct, llvm_unreachable, N, llvm::Metadata::Temporary, and llvm::Metadata::Uniqued.
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 874 of file Metadata.h.
ReplaceableMetadataImpl
friend class ReplaceableMetadataImpl friend
Definition at line 873 of file Metadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/Analysis/TypeBasedAliasAnalysis.cpp
lib/IR/Metadata.cpp
lib/IR/MetadataImpl.h