LLVM: llvm::SMDiagnostic Class Reference
llvm::SMDiagnostic Class Reference
Instances of this class encapsulate one diagnostic report, allowing printing to a raw_ostream as a caret diagnostic.
#include "llvm/Support/SourceMgr.h"
Public Member Functions
SMDiagnostic ()=default
SMDiagnostic (StringRef filename, SourceMgr::DiagKind Knd, StringRef Msg)
SMDiagnostic (const SourceMgr &sm, SMLoc L, StringRef FN, int Line, int Col, SourceMgr::DiagKind Kind, StringRef Msg, StringRef LineStr, ArrayRef< std::pair< unsigned, unsigned >> Ranges, ArrayRef< SMFixIt > FixIts=None)
const SourceMgr * getSourceMgr () const
SMLoc getLoc () const
StringRef getFilename () const
int getLineNo () const
int getColumnNo () const
SourceMgr::DiagKind getKind () const
StringRef getMessage () const
StringRef getLineContents () const
ArrayRef< std::pair< unsigned, unsigned > > getRanges () const
void addFixIt (const SMFixIt &Hint)
ArrayRef< SMFixIt > getFixIts () const
void print (const char *ProgName, raw_ostream &S, bool ShowColors=true, bool ShowKindLabel=true) const
Detailed Description
Instances of this class encapsulate one diagnostic report, allowing printing to a raw_ostream as a caret diagnostic.
Definition at line 261 of file SourceMgr.h.
Constructor & Destructor Documentation
SMDiagnostic() [1/3]
llvm::SMDiagnostic::SMDiagnostic () default
SMDiagnostic() [2/3]
llvm::SMDiagnostic::SMDiagnostic (StringRef filename, SourceMgr::DiagKind Knd, StringRef Msg) inline
Definition at line 276 of file SourceMgr.h.
References llvm::None.
SMDiagnostic() [3/3]
SMDiagnostic::SMDiagnostic (const SourceMgr & sm, SMLoc L, StringRef FN, int Line, int Col, SourceMgr::DiagKind Kind, StringRef Msg, StringRef LineStr, ArrayRef< std::pair< unsigned, unsigned >> Ranges, ArrayRef< SMFixIt > FixIts = None)
Definition at line 259 of file SourceMgr.cpp.
References llvm::sort().
Member Function Documentation
addFixIt()
void llvm::SMDiagnostic::addFixIt (const SMFixIt & Hint) inline
Definition at line 296 of file SourceMgr.h.
References llvm::SmallVectorTemplateBase< T >::push_back().
getColumnNo()
int llvm::SMDiagnostic::getColumnNo () const inline
Definition at line 290 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), getGNUBinOpPrecedence(), and llvm::MIRParserImpl::initializeJumpTableInfo().
getFilename()
StringRef llvm::SMDiagnostic::getFilename () const inline
Definition at line 288 of file SourceMgr.h.
getFixIts()
ArrayRef<SMFixIt> llvm::SMDiagnostic::getFixIts () const inline
Definition at line 300 of file SourceMgr.h.
References print().
Referenced by llvm::MachO::DiagHandler(), and llvm::MIRParserImpl::initializeJumpTableInfo().
getKind()
SourceMgr::DiagKind llvm::SMDiagnostic::getKind () const inline
Definition at line 291 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), llvm::MIRParserImpl::error(), getGNUBinOpPrecedence(), llvm::MIRParserImpl::initializeJumpTableInfo(), and llvm::MIRParserImpl::reportDiagnostic().
getLineContents()
StringRef llvm::SMDiagnostic::getLineContents () const inline
Definition at line 293 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), getGNUBinOpPrecedence(), and llvm::MIRParserImpl::initializeJumpTableInfo().
getLineNo()
int llvm::SMDiagnostic::getLineNo () const inline
Definition at line 289 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), llvm::MIRParserImpl::initializeJumpTableInfo(), and srcMgrDiagHandler().
getLoc()
SMLoc llvm::SMDiagnostic::getLoc () const inline
Definition at line 287 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), getGNUBinOpPrecedence(), llvm::MIRParserImpl::initializeJumpTableInfo(), llvm::SourceMgr::PrintMessage(), and srcMgrDiagHandler().
getMessage()
StringRef llvm::SMDiagnostic::getMessage () const inline
Definition at line 292 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), getGNUBinOpPrecedence(), and llvm::MIRParserImpl::initializeJumpTableInfo().
getRanges()
ArrayRef<std::pair<unsigned, unsigned> > llvm::SMDiagnostic::getRanges () const inline
Definition at line 294 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), getGNUBinOpPrecedence(), and llvm::MIRParserImpl::initializeJumpTableInfo().
getSourceMgr()
const SourceMgr* llvm::SMDiagnostic::getSourceMgr () const inline
Definition at line 286 of file SourceMgr.h.
Referenced by llvm::MachO::DiagHandler(), and getGNUBinOpPrecedence().
print()
void SMDiagnostic::print (const char * ProgName, raw_ostream & S, bool ShowColors = true, bool ShowKindLabel = true) const
Definition at line 368 of file SourceMgr.cpp.
References buildFixItLine(), llvm::SourceMgr::DK_Error, llvm::SourceMgr::DK_Note, llvm::SourceMgr::DK_Remark, llvm::SourceMgr::DK_Warning, llvm::numbers::e, llvm::WithColor::error(), llvm::find_if(), llvm::SMLoc::getPointer(), llvm::raw_ostream::GREEN, isNonASCII(), llvm::makeArrayRef(), llvm::WithColor::note(), printSourceLine(), llvm::WithColor::remark(), llvm::raw_ostream::SAVEDCOLOR, TabStop, and llvm::WithColor::warning().
Referenced by llvm::MachO::DiagHandler(), getGNUBinOpPrecedence(), handleDiagnostic(), LLVMParseIRInContext(), llvm::ErrorDiagnostic::log(), makeCombineInst(), llvm::DiagnosticPrinterRawOStream::operator<<(), and llvm::SourceMgr::PrintMessage().
The documentation for this class was generated from the following files:
include/llvm/Support/SourceMgr.h
lib/Support/SourceMgr.cpp