LLVM: llvm::StatisticBase Class Reference
llvm::StatisticBase Class Reference
#include "llvm/ADT/Statistic.h"
Public Member Functions
StatisticBase (const char *DebugType, const char *Name, const char *Desc)
const char * getDebugType () const
const char * getName () const
const char * getDesc () const
Public Attributes
const char * DebugType
const char * Name
const char * Desc
Detailed Description
Definition at line 47 of file Statistic.h.
Constructor & Destructor Documentation
StatisticBase()
llvm::StatisticBase::StatisticBase (const char * DebugType, const char * Name, const char * Desc) inline
Definition at line 53 of file Statistic.h.
Member Function Documentation
getDebugType()
const char* llvm::StatisticBase::getDebugType () const inline
Definition at line 56 of file Statistic.h.
References DebugType.
Referenced by llvm::AreStatisticsEnabled(), and llvm::PrintStatisticsJSON().
getDesc()
const char* llvm::StatisticBase::getDesc () const inline
Definition at line 58 of file Statistic.h.
References Desc.
Referenced by llvm::AreStatisticsEnabled(), and reportInvalidCandidate().
getName()
const char* llvm::StatisticBase::getName () const inline
Definition at line 57 of file Statistic.h.
References Name.
Referenced by llvm::AreStatisticsEnabled(), and llvm::PrintStatisticsJSON().
Member Data Documentation
DebugType
const char* llvm::StatisticBase::DebugType
Definition at line 49 of file Statistic.h.
Referenced by getDebugType().
Desc
const char* llvm::StatisticBase::Desc
Definition at line 51 of file Statistic.h.
Referenced by getDesc().
Name
const char* llvm::StatisticBase::Name
Definition at line 50 of file Statistic.h.
Referenced by getName().
The documentation for this class was generated from the following file:
include/llvm/ADT/Statistic.h