LLVM: llvm::codeview::DebugSymbolRVASubsectionRef Class Reference
llvm::codeview::DebugSymbolRVASubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugSymbolRVASubsection.h"
Public Types
using ArrayType = FixedStreamArray< support::ulittle32_t >
Public Member Functions
DebugSymbolRVASubsectionRef ()
ArrayType::Iterator begin () const
ArrayType::Iterator end () const
Error initialize (BinaryStreamReader &Reader)
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 26 of file DebugSymbolRVASubsection.h.
Member Typedef Documentation
ArrayType
using llvm::codeview::DebugSymbolRVASubsectionRef::ArrayType = FixedStreamArray<support::ulittle32_t>
Definition at line 28 of file DebugSymbolRVASubsection.h.
Constructor & Destructor Documentation
DebugSymbolRVASubsectionRef()
DebugSymbolRVASubsectionRef::DebugSymbolRVASubsectionRef ()
Definition at line 19 of file DebugSymbolRVASubsection.cpp.
References llvm::codeview::CoffSymbolRVA.
Member Function Documentation
begin()
ArrayType::Iterator llvm::codeview::DebugSymbolRVASubsectionRef::begin () const inline
Definition at line 36 of file DebugSymbolRVASubsection.h.
References llvm::FixedStreamArray< T >::begin().
classof()
static bool llvm::codeview::DebugSymbolRVASubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 32 of file DebugSymbolRVASubsection.h.
References llvm::codeview::CoffSymbolRVA, and llvm::codeview::DebugSubsectionRef::kind().
end()
ArrayType::Iterator llvm::codeview::DebugSymbolRVASubsectionRef::end () const inline
Definition at line 37 of file DebugSymbolRVASubsection.h.
References llvm::FixedStreamArray< T >::end(), and initialize().
initialize()
Error DebugSymbolRVASubsectionRef::initialize (BinaryStreamReader & Reader)
Definition at line 22 of file DebugSymbolRVASubsection.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), and llvm::BinaryStreamReader::readArray().
Referenced by end(), and llvm::codeview::visitDebugSubsection().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSymbolRVASubsection.h
lib/DebugInfo/CodeView/DebugSymbolRVASubsection.cpp