LLVM: llvm::AMDGPULegalizerInfo Class Reference
llvm::AMDGPULegalizerInfo Class Reference
This class provides the information for the target register banks.
#include "Target/AMDGPU/AMDGPULegalizerInfo.h"
Public Member Functions
AMDGPULegalizerInfo (const GCNSubtarget &ST, const GCNTargetMachine &TM)
bool legalizeCustom (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B, GISelChangeObserver &Observer) const override
Register getSegmentAperture (unsigned AddrSpace, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeAddrSpaceCast (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeFrint (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeFceil (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeIntrinsicTrunc (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeITOFP (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B, bool Signed) const
bool legalizeMinNumMaxNum (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeExtractVectorElt (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeInsertVectorElt (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeSinCos (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool buildPCRelGlobalAddress (Register DstReg, LLT PtrTy, MachineIRBuilder &B, const GlobalValue *GV, unsigned Offset, unsigned GAFlags=SIInstrInfo::MO_NONE) const
bool legalizeGlobalValue (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeLoad (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B, GISelChangeObserver &Observer) const
bool legalizeFMad (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeAtomicCmpXChg (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
Register getLiveInRegister (MachineRegisterInfo &MRI, Register Reg, LLT Ty) const
bool loadInputValue (Register DstReg, MachineIRBuilder &B, const ArgDescriptor *Arg) const
bool legalizePreloadedArgIntrin (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B, AMDGPUFunctionArgInfo::PreloadedValue ArgType) const
bool legalizeFDIV (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeFDIV16 (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeFDIV32 (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeFDIV64 (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeFastUnsafeFDIV (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeFDIVFastIntrin (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeImplicitArgPtr (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeIsAddrSpace (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B, unsigned AddrSpace) const
Register handleD16VData (MachineIRBuilder &B, MachineRegisterInfo &MRI, Register Reg) const
Handle register layout difference for f16 images for some subtargets.
bool legalizeRawBufferStore (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B, bool IsFormat) const
bool legalizeIntrinsic (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const override
Return true if MI is either legal or has been legalized and false if not legal.
Public Member Functions inherited from llvm::LegalizerInfo
LegalizerInfo ()
virtual ~LegalizerInfo ()=default
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void computeTables ()
Compute any ancillary tables needed to quickly decide how an operation should be handled.
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
void setAction (const InstrAspect &Aspect, LegalizeAction Action)
More friendly way to set an action for common types that have an LLT representation.
void setLegalizeScalarToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
The setAction calls record the non-size-changing legalization actions to take on specificly-sized types.
void setLegalizeVectorElementToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
See also setLegalizeScalarToDifferentSizeStrategy.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Additional Inherited Members
Public Types inherited from llvm::LegalizerInfo
using SizeAndAction = std::pair< uint16_t, LegalizeAction >
using SizeAndActionsVec = std::vector< SizeAndAction >
using SizeChangeStrategy = std::function< SizeAndActionsVec(const SizeAndActionsVec &v)>
Static Public Member Functions inherited from llvm::LegalizerInfo
static bool needsLegalizingToDifferentSize (const LegalizeAction Action)
static SizeAndActionsVec unsupportedForDifferentSizes (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of only supporting a specific set of type sizes.
static SizeAndActionsVec widenToLargerTypesAndNarrowToLargest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of widening the type to a large legal type, unless there is no such type and then instead it should be narrowed to the largest legal type.
static SizeAndActionsVec widenToLargerTypesUnsupportedOtherwise (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndUnsupportedIfTooSmall (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndWidenToSmallest (const SizeAndActionsVec &v)
static SizeAndActionsVec moreToWiderTypesAndLessToWidest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular vector operation consists of having more elements in the vector, to a type that is legal.
static SizeAndActionsVec increaseToLargerTypesAndDecreaseToLargest (const SizeAndActionsVec &v, LegalizeAction IncreaseAction, LegalizeAction DecreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
static SizeAndActionsVec decreaseToSmallerTypesAndIncreaseToSmallest (const SizeAndActionsVec &v, LegalizeAction DecreaseAction, LegalizeAction IncreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
Detailed Description
This class provides the information for the target register banks.
Definition at line 28 of file AMDGPULegalizerInfo.h.
Constructor & Destructor Documentation
AMDGPULegalizerInfo()
AMDGPULegalizerInfo::AMDGPULegalizerInfo (const GCNSubtarget & ST, const GCNTargetMachine & TM)
Definition at line 163 of file AMDGPULegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), llvm::SITargetLowering::allowsMisalignedMemoryAccessesImpl(), llvm::LegalizeRuleSet::alwaysLegal(), llvm::LegalizeMutations::changeTo(), llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizeRuleSet::clampNumElements(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegalizeRuleSet::clampScalarOrElt(), llvm::LegalizerInfo::computeTables(), AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::LegalizeRuleSet::custom(), llvm::LegalizeRuleSet::customFor(), llvm::LegalizeRuleSet::customIf(), elementTypeIs(), llvm::LegalizeRuleSet::fewerElementsIf(), fewerEltsToSize64Vector(), AMDGPUAS::FLAT_ADDRESS, llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LLT::getAddressSpace(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::TargetMachine::getPointerSizeInBits(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), AMDGPUAS::GLOBAL_ADDRESS, isMultiple32(), llvm::LegalityPredicates::isPointer(), llvm::isPowerOf2_32(), isRegisterType(), isSmallOddVector(), llvm::LLT::isVector(), isWideScalarTruncStore(), isWideVec16(), llvm::LegalizeActions::Legal, llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForCartesianProduct(), llvm::LegalizeRuleSet::legalForTypesWithMemDesc(), llvm::LegalizeRuleSet::legalIf(), AMDGPUAS::LOCAL_ADDRESS, llvm::Log2_32_Ceil(), llvm::LegalizeRuleSet::lower(), llvm::LegalizeRuleSet::lowerFor(), llvm::LegalizeRuleSet::lowerIf(), llvm::max(), llvm::LegalizeRuleSet::minScalar(), llvm::LegalizeRuleSet::minScalarOrElt(), llvm::LegalizeRuleSet::minScalarSameAs(), llvm::LegalityQuery::MMODescrs, llvm::LegalizeRuleSet::moreElementsIf(), moreEltsToNext32Bit(), numElementsNotEven(), oneMoreElement(), llvm::LLT::pointer(), AMDGPUAS::PRIVATE_ADDRESS, AMDGPUAS::REGION_ADDRESS, llvm::LegalityPredicates::sameSize(), llvm::LLT::scalar(), llvm::LegalizeMutations::scalarize(), llvm::LegalizeRuleSet::scalarize(), llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::LegalizerInfo::setAction(), Size, sizeIs(), llvm::SystemZISD::TM, llvm::LegalityPredicates::typeInSet(), llvm::LegalityPredicates::typeIs(), llvm::LegalityQuery::Types, llvm::LegalizeRuleSet::unsupportedIf(), llvm::LegalizeRuleSet::unsupportedIfMemSizeNotPow2(), llvm::LLT::vector(), vectorSmallerThan(), vectorWiderThan(), llvm::LegalizerInfo::verify(), llvm::LegalizeRuleSet::widenScalarIf(), llvm::LegalizeMutations::widenScalarOrEltToNextPow2(), and llvm::LegalizeRuleSet::widenScalarToNextPow2().
Member Function Documentation
buildPCRelGlobalAddress()
bool AMDGPULegalizerInfo::buildPCRelGlobalAddress (Register DstReg, LLT PtrTy, MachineIRBuilder & B, const GlobalValue * GV, unsigned Offset, unsigned GAFlags = SIInstrInfo::MO_NONE) const
Definition at line 1618 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildInstr(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineIRBuilder::getMRI(), llvm::LLT::getSizeInBits(), llvm::SIInstrInfo::MO_NONE, llvm::LLT::pointer(), and llvm::MachineRegisterInfo::setRegClass().
Referenced by legalizeGlobalValue().
getLiveInRegister()
Register AMDGPULegalizerInfo::getLiveInRegister (MachineRegisterInfo & MRI, Register Reg, LLT Ty) const
Definition at line 1830 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), and llvm::MachineRegisterInfo::getLiveInVirtReg().
Referenced by loadInputValue().
getSegmentAperture()
Register AMDGPULegalizerInfo::getSegmentAperture (unsigned AddrSpace, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1180 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLoad(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SIMachineFunctionInfo::getArgInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getSubtarget(), llvm::GCNSubtarget::hasApertureRegs(), llvm::AMDGPU::Hwreg::ID_MEM_BASES, llvm::AMDGPU::Hwreg::ID_SHIFT_, loadInputValue(), AMDGPUAS::LOCAL_ADDRESS, llvm::MachineIRBuilder::materializePtrAdd(), llvm::MinAlign(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::MachineMemOperand::MOLoad, llvm::AMDGPU::Hwreg::OFFSET_SHIFT_, llvm::AMDGPU::Hwreg::OFFSET_SRC_PRIVATE_BASE, llvm::AMDGPU::Hwreg::OFFSET_SRC_SHARED_BASE, llvm::LLT::pointer(), AMDGPUAS::PRIVATE_ADDRESS, llvm::AMDGPUFunctionArgInfo::QueuePtr, Register, llvm::LLT::scalar(), llvm::MachineRegisterInfo::setType(), llvm::AMDGPU::Hwreg::WIDTH_M1_SHIFT_, llvm::AMDGPU::Hwreg::WIDTH_M1_SRC_PRIVATE_BASE, and llvm::AMDGPU::Hwreg::WIDTH_M1_SRC_SHARED_BASE.
Referenced by legalizeAddrSpaceCast(), and legalizeIsAddrSpace().
handleD16VData()
Register AMDGPULegalizerInfo::handleD16VData (MachineIRBuilder & B, MachineRegisterInfo & MRI, Register Reg) const
Handle register layout difference for f16 images for some subtargets.
Definition at line 2293 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildUnmerge(), E, llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstrBuilder::getReg(), getReg(), llvm::MachineRegisterInfo::getType(), I, llvm::LLT::isVector(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalar(), and llvm::LLT::vector().
Referenced by legalizeRawBufferStore().
legalizeAddrSpaceCast()
bool AMDGPULegalizerInfo::legalizeAddrSpaceCast (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1250 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildSelect(), AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineInstr::eraseFromParent(), AMDGPUAS::FLAT_ADDRESS, llvm::MCInstrInfo::get(), llvm::SIMachineFunctionInfo::get32BitAddressHighBits(), llvm::LLT::getAddressSpace(), llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getSegmentAperture(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::GCNSubtarget::getTargetLowering(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), llvm::GCNSubtarget::hasFlatAddressSpace(), llvm::CmpInst::ICMP_NE, Info, llvm::SITargetLowering::isNoopAddrSpaceCast(), llvm::Register::isValid(), llvm::LLT::isVector(), AMDGPUAS::LOCAL_ADDRESS, llvm::LLT::pointer(), AMDGPUAS::PRIVATE_ADDRESS, llvm::LLT::scalar(), llvm::MachineInstr::setDesc(), llvm::MachineIRBuilder::setInstr(), and llvm::SystemZISD::TM.
Referenced by legalizeCustom().
legalizeAtomicCmpXChg()
bool AMDGPULegalizerInfo::legalizeAtomicCmpXChg (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1779 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getAddressSpace(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineRegisterInfo::getType(), llvm::SITargetLowering::isFlatGlobalAddrSpace(), llvm::MachineInstr::memoperands(), llvm::MachineIRBuilder::setInstr(), llvm::MachineInstrBuilder::setMemRefs(), and llvm::LLT::vector().
Referenced by legalizeCustom().
legalizeCustom()
bool AMDGPULegalizerInfo::legalizeCustom (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B, GISelChangeObserver & Observer) const override virtual
Reimplemented from llvm::LegalizerInfo.
Definition at line 1134 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstr::getOpcode(), legalizeAddrSpaceCast(), legalizeAtomicCmpXChg(), legalizeExtractVectorElt(), legalizeFceil(), legalizeFDIV(), legalizeFMad(), legalizeFrint(), legalizeGlobalValue(), legalizeInsertVectorElt(), legalizeIntrinsicTrunc(), legalizeITOFP(), legalizeLoad(), legalizeMinNumMaxNum(), legalizeSinCos(), and llvm_unreachable.
legalizeExtractVectorElt()
bool AMDGPULegalizerInfo::legalizeExtractVectorElt (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1530 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineInstr::eraseFromParent(), llvm::getConstantVRegVal(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::Optional< T >::getValue(), MRI, and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeFastUnsafeFDIV()
bool AMDGPULegalizerInfo::legalizeFastUnsafeFDIV (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1936 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildFMul(), llvm::MachineIRBuilder::buildFNeg(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::FmArcp, llvm::AMDGPU::SIModeRegisterDefaults::FP32Denormals, llvm::getConstantFPVRegVal(), llvm::MachineInstr::getFlag(), llvm::MachineInstr::getFlags(), llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMF(), llvm::AMDGPUMachineFunction::getMode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getTarget(), llvm::MachineRegisterInfo::getType(), llvm::TargetMachine::Options, llvm::AMDGPUISD::RCP, llvm::LLT::scalar(), llvm::MachineInstrBuilder::setMIFlags(), and llvm::TargetOptions::UnsafeFPMath.
Referenced by legalizeFDIV().
legalizeFceil()
bool AMDGPULegalizerInfo::legalizeFceil (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1383 of file AMDGPULegalizerInfo.cpp.
References llvm::MCID::Add, assert(), llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildFAdd(), llvm::MachineIRBuilder::buildFCmp(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildSelect(), llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_ONE, llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeFDIV()
bool AMDGPULegalizerInfo::legalizeFDIV (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1913 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), legalizeFastUnsafeFDIV(), legalizeFDIV16(), legalizeFDIV32(), legalizeFDIV64(), llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeFDIV16()
bool AMDGPULegalizerInfo::legalizeFDIV16 (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1997 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildFMul(), llvm::MachineIRBuilder::buildFPExt(), llvm::MachineIRBuilder::buildFPTrunc(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::AMDGPUISD::RCP, llvm::LLT::scalar(), llvm::MachineIRBuilder::setInstr(), and llvm::MachineInstrBuilder::setMIFlags().
Referenced by legalizeFDIV().
legalizeFDIV32()
bool AMDGPULegalizerInfo::legalizeFDIV32 (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 2062 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFMA(), llvm::MachineIRBuilder::buildFMul(), llvm::MachineIRBuilder::buildFNeg(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getFlags(), llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMF(), llvm::AMDGPUMachineFunction::getMode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), Mode, llvm::LLT::scalar(), llvm::MachineIRBuilder::setInstr(), llvm::MachineInstrBuilder::setMIFlags(), and toggleSPDenormMode().
Referenced by legalizeFDIV().
legalizeFDIV64()
bool AMDGPULegalizerInfo::legalizeFDIV64 (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 2129 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFMA(), llvm::MachineIRBuilder::buildFNeg(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineIRBuilder::buildMul(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineIRBuilder::buildXor(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::CmpInst::ICMP_EQ, llvm::makeArrayRef(), llvm::LLT::scalar(), llvm::MachineIRBuilder::setInstr(), and llvm::MachineInstrBuilder::setMIFlags().
Referenced by legalizeFDIV().
legalizeFDIVFastIntrin()
bool AMDGPULegalizerInfo::legalizeFDIVFastIntrin (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 2210 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFAbs(), llvm::MachineIRBuilder::buildFCmp(), llvm::MachineIRBuilder::buildFMul(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineInstr::eraseFromParent(), llvm::CmpInst::FCMP_OGT, llvm::FloatToBits(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::AMDGPUISD::RCP, llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeIntrinsic().
legalizeFMad()
bool AMDGPULegalizerInfo::legalizeFMad (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1756 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::AMDGPU::SIModeRegisterDefaults::FP32Denormals, llvm::AMDGPU::SIModeRegisterDefaults::FP64FP16Denormals, llvm::MachineIRBuilder::getMF(), llvm::AMDGPUMachineFunction::getMode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isScalar(), llvm::LegalizerHelper::Legalized, llvm::LegalizerHelper::lowerFMad(), llvm::LLT::scalar(), and llvm::MachineIRBuilder::setMBB().
Referenced by legalizeCustom().
legalizeFrint()
bool AMDGPULegalizerInfo::legalizeFrint (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1356 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::MachineIRBuilder::buildFAbs(), llvm::MachineIRBuilder::buildFAdd(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFCopysign(), llvm::MachineIRBuilder::buildFSub(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::APFloatBase::IEEEdouble(), llvm::LLT::isScalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeGlobalValue()
bool AMDGPULegalizerInfo::legalizeGlobalValue (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1674 of file AMDGPULegalizerInfo.cpp.
References llvm::AMDGPUMachineFunction::allocateLDSGlobal(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildLoad(), buildPCRelGlobalAddress(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::LLVMContext::diagnose(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getAddressSpace(), llvm::Function::getContext(), llvm::MachineIRBuilder::getDataLayout(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachinePointerInfo::getGOT(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::AMDGPUTargetLowering::hasDefinedInitializer(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::SPII::Load, AMDGPUAS::LOCAL_ADDRESS, llvm::SIInstrInfo::MO_GOTPCREL32, llvm::SIInstrInfo::MO_REL32, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::MachineMemOperand::MOLoad, llvm::LLT::pointer(), AMDGPUAS::REGION_ADDRESS, llvm::MachineIRBuilder::setInstr(), llvm::SITargetLowering::shouldEmitFixup(), and llvm::SITargetLowering::shouldEmitPCReloc().
Referenced by legalizeCustom().
legalizeImplicitArgPtr()
bool AMDGPULegalizerInfo::legalizeImplicitArgPtr (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 2246 of file AMDGPULegalizerInfo.cpp.
References Arg, llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::AMDGPUTargetLowering::FIRST_IMPLICIT, llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::SIMachineFunctionInfo::getPreloadedValue(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::AMDGPUFunctionArgInfo::IMPLICIT_ARG_PTR, llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::AMDGPUFunctionArgInfo::KERNARG_SEGMENT_PTR, legalizePreloadedArgIntrin(), loadInputValue(), llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeIntrinsic().
legalizeInsertVectorElt()
bool AMDGPULegalizerInfo::legalizeInsertVectorElt (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1559 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineInstr::eraseFromParent(), llvm::getConstantVRegVal(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::Optional< T >::getValue(), llvm::MipsISD::Ins, MRI, and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeIntrinsic()
bool AMDGPULegalizerInfo::legalizeIntrinsic (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const override virtual
Return true if MI is either legal or has been legalized and false if not legal.
Reimplemented from llvm::LegalizerInfo.
Definition at line 2348 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::tgtok::Def, llvm::AMDGPUFunctionArgInfo::DISPATCH_ID, llvm::AMDGPUFunctionArgInfo::DISPATCH_PTR, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getIntrinsicID(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::SIRegisterInfo::getWaveMaskRegClass(), llvm::AMDGPUFunctionArgInfo::IMPLICIT_BUFFER_PTR, llvm::AMDGPUFunctionArgInfo::KERNARG_SEGMENT_PTR, legalizeFDIVFastIntrin(), legalizeImplicitArgPtr(), legalizeIsAddrSpace(), legalizePreloadedArgIntrin(), legalizeRawBufferStore(), AMDGPUAS::LOCAL_ADDRESS, AMDGPUAS::PRIVATE_ADDRESS, llvm::AMDGPUFunctionArgInfo::QUEUE_PTR, Reg, llvm::MachineIRBuilder::setInstr(), llvm::MachineOperand::setMBB(), llvm::MachineRegisterInfo::setRegClass(), TRI, verifyCFIntrinsic(), llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_X, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Y, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Z, llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_X, llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_Y, and llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_Z.
legalizeIntrinsicTrunc()
bool AMDGPULegalizerInfo::legalizeIntrinsicTrunc (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1428 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildAShr(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildNot(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildUnmerge(), extractF64Exponent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MipsISD::Hi, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeIsAddrSpace()
bool AMDGPULegalizerInfo::legalizeIsAddrSpace (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B, unsigned AddrSpace) const
Definition at line 2280 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getSegmentAperture(), llvm::CmpInst::ICMP_EQ, llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeIntrinsic().
legalizeITOFP()
bool AMDGPULegalizerInfo::legalizeITOFP (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B, bool Signed) const
Definition at line 1474 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFAdd(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineIRBuilder::buildSITOFP(), llvm::MachineIRBuilder::buildUITOFP(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeLoad()
bool AMDGPULegalizerInfo::legalizeLoad (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B, GISelChangeObserver & Observer) const
Definition at line 1744 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildAddrSpaceCast(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::pointer(), llvm::MachineIRBuilder::setInstr(), and llvm::MachineOperand::setReg().
Referenced by legalizeCustom().
legalizeMinNumMaxNum()
bool AMDGPULegalizerInfo::legalizeMinNumMaxNum (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1506 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMF(), llvm::AMDGPUMachineFunction::getMode(), llvm::MachineInstr::getOpcode(), llvm::AMDGPU::SIModeRegisterDefaults::IEEE, llvm::LegalizerHelper::Legalized, llvm::LegalizerHelper::lowerFMinNumMaxNum(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizePreloadedArgIntrin()
bool AMDGPULegalizerInfo::legalizePreloadedArgIntrin (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B, AMDGPUFunctionArgInfo::PreloadedValue ArgType) const
Definition at line 1888 of file AMDGPULegalizerInfo.cpp.
References Arg, B, llvm::dbgs(), llvm::MachineInstr::eraseFromParent(), llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::SIMachineFunctionInfo::getPreloadedValue(), llvm::MachineOperand::getReg(), LLVM_DEBUG, loadInputValue(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeImplicitArgPtr(), and legalizeIntrinsic().
legalizeRawBufferStore()
bool AMDGPULegalizerInfo::legalizeRawBufferStore (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B, bool IsFormat) const
Definition at line 2315 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildAnyExt(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), handleD16VData(), llvm::LLT::isVector(), llvm::LLT::scalar(), llvm::MachineIRBuilder::setInstr(), and llvm::MachineOperand::setReg().
Referenced by legalizeIntrinsic().
legalizeSinCos()
bool AMDGPULegalizerInfo::legalizeSinCos (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1589 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFMul(), llvm::MachineIRBuilder::buildIntrinsic(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineIRBuilder::setInstr(), and llvm::MachineInstrBuilder::setMIFlags().
Referenced by legalizeCustom().
loadInputValue()
bool AMDGPULegalizerInfo::loadInputValue (Register DstReg, MachineIRBuilder & B, const ArgDescriptor * Arg) const
Definition at line 1841 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineBasicBlock::addLiveIn(), assert(), llvm::MachineBasicBlock::begin(), llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineFunction::front(), llvm::MachineIRBuilder::getInsertPt(), getLiveInRegister(), llvm::ArgDescriptor::getMask(), llvm::MachineIRBuilder::getMBB(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstrBuilder::getReg(), llvm::ArgDescriptor::getRegister(), llvm::ArgDescriptor::isMasked(), llvm::Register::isPhysical(), llvm::ArgDescriptor::isRegister(), llvm::Register::isValid(), llvm::BitmaskEnumDetail::Mask(), MRI, llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInsertPt().
Referenced by getSegmentAperture(), legalizeImplicitArgPtr(), and legalizePreloadedArgIntrin().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPULegalizerInfo.h
lib/Target/AMDGPU/AMDGPULegalizerInfo.cpp