LLVM: llvm::BitcodeWriterPass Class Reference
llvm::BitcodeWriterPass Class Reference
Pass for writing a module of IR out to a bitcode file.
#include "llvm/Bitcode/BitcodeWriterPass.h"
Public Member Functions
BitcodeWriterPass (raw_ostream &OS, bool ShouldPreserveUseListOrder=false, bool EmitSummaryIndex=false, bool EmitModuleHash=false)
Construct a bitcode writer pass around a particular output stream.
PreservedAnalyses run (Module &M, ModuleAnalysisManager &)
Run the bitcode writer pass, and output the module to the selected output stream.
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< BitcodeWriterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass for writing a module of IR out to a bitcode file.
Note that this is intended for use with the new pass manager. To construct a pass for the legacy pass manager, use the function above.
Definition at line 50 of file BitcodeWriterPass.h.
Constructor & Destructor Documentation
BitcodeWriterPass()
llvm::BitcodeWriterPass::BitcodeWriterPass (raw_ostream & OS, bool ShouldPreserveUseListOrder = false, bool EmitSummaryIndex = false, bool EmitModuleHash = false) inline explicit
Construct a bitcode writer pass around a particular output stream.
If ShouldPreserveUseListOrder, encode use-list order so it can be reproduced when deserialized.
If EmitSummaryIndex, emit the summary index (currently for use in ThinLTO optimization).
Definition at line 64 of file BitcodeWriterPass.h.
References run().
Member Function Documentation
run()
PreservedAnalyses BitcodeWriterPass::run (Module & M, ModuleAnalysisManager & AM)
Run the bitcode writer pass, and output the module to the selected output stream.
Definition at line 22 of file BitcodeWriterPass.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::PreservedAnalyses::all(), llvm::dbgs(), llvm::PassRegistry::getPassRegistry(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeWriteBitcodePassPass(), llvm::AnalysisUsage::setPreservesAll(), and llvm::WriteBitcodeToFile().
Referenced by BitcodeWriterPass().
The documentation for this class was generated from the following files:
include/llvm/Bitcode/BitcodeWriterPass.h
lib/Bitcode/Writer/BitcodeWriterPass.cpp