LLVM: llvm::pdb::PDBFileBuilder Class Reference
llvm::pdb::PDBFileBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/PDBFileBuilder.h"
Public Member Functions
PDBFileBuilder (BumpPtrAllocator &Allocator)
~PDBFileBuilder ()
PDBFileBuilder (const PDBFileBuilder &)=delete
PDBFileBuilder & operator= (const PDBFileBuilder &)=delete
Error initialize (uint32_t BlockSize)
msf::MSFBuilder & getMsfBuilder ()
InfoStreamBuilder & getInfoBuilder ()
DbiStreamBuilder & getDbiBuilder ()
TpiStreamBuilder & getTpiBuilder ()
TpiStreamBuilder & getIpiBuilder ()
PDBStringTableBuilder & getStringTableBuilder ()
GSIStreamBuilder & getGsiBuilder ()
Error commit (StringRef Filename, codeview::GUID *Guid)
Expected< uint32_t > getNamedStreamIndex (StringRef Name) const
Error addNamedStream (StringRef Name, StringRef Data)
void addInjectedSource (StringRef Name, std::unique_ptr< MemoryBuffer > Buffer)
Detailed Description
Definition at line 38 of file PDBFileBuilder.h.
Constructor & Destructor Documentation
PDBFileBuilder() [1/2]
PDBFileBuilder::PDBFileBuilder (BumpPtrAllocator & Allocator) explicit
Definition at line 35 of file PDBFileBuilder.cpp.
~PDBFileBuilder()
PDBFileBuilder::~PDBFileBuilder ()
Definition at line 39 of file PDBFileBuilder.cpp.
PDBFileBuilder() [2/2]
llvm::pdb::PDBFileBuilder::PDBFileBuilder (const PDBFileBuilder &) delete
Member Function Documentation
addInjectedSource()
void PDBFileBuilder::addInjectedSource (StringRef Name, std::unique_ptr< MemoryBuffer > Buffer)
Definition at line 102 of file PDBFileBuilder.cpp.
References llvm::arrayRefFromStringRef(), llvm::pdb::PDBStringTableBuilder::calculateSerializedSize(), llvm::codeview::EC, llvm::SmallVectorBase::empty(), getInfoBuilder(), getStringTableBuilder(), llvm::pdb::PDBStringTableBuilder::insert(), llvm::StringRef::lower(), llvm::sys::path::native(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Expected< T >::takeError(), llvm::JamCRC::update(), and llvm::pdb::VC140.
addNamedStream()
Error PDBFileBuilder::addNamedStream (StringRef Name, StringRef Data)
Definition at line 93 of file PDBFileBuilder.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::pdb::Data, llvm::StringRef::size(), llvm::Error::success(), and llvm::Expected< T >::takeError().
commit()
Error PDBFileBuilder::commit (StringRef Filename, codeview::GUID * Guid)
Definition at line 264 of file PDBFileBuilder.cpp.
References llvm::arrayRefFromStringRef(), assert(), llvm::msf::SuperBlock::BlockSize, llvm::msf::blockToOffset(), llvm::pdb::PDBStringTableBuilder::commit(), llvm::FileBufferByteStream::commit(), llvm::codeview::EC, llvm::StringRef::empty(), llvm::FileBufferByteStream::getBufferEnd(), llvm::FileBufferByteStream::getBufferStart(), getNamedStreamIndex(), llvm::codeview::GUID::Guid, H, llvm::Optional< T >::hasValue(), llvm::msf::MSFLayout::SB, llvm::msf::MSFLayout::StreamMap, llvm::pdb::StreamPDB, llvm::Expected< T >::takeError(), llvm::BinaryStreamWriter::writeBytes(), and llvm::xxHash64().
getDbiBuilder()
DbiStreamBuilder & PDBFileBuilder::getDbiBuilder ()
Definition at line 57 of file PDBFileBuilder.cpp.
getGsiBuilder()
GSIStreamBuilder & PDBFileBuilder::getGsiBuilder ()
Definition at line 79 of file PDBFileBuilder.cpp.
References Name, llvm::pdb::NamedStreamMap::set(), and Size.
getInfoBuilder()
InfoStreamBuilder & PDBFileBuilder::getInfoBuilder ()
Definition at line 51 of file PDBFileBuilder.cpp.
Referenced by addInjectedSource().
getIpiBuilder()
TpiStreamBuilder & PDBFileBuilder::getIpiBuilder ()
Definition at line 69 of file PDBFileBuilder.cpp.
References llvm::pdb::StreamIPI.
getMsfBuilder()
MSFBuilder & PDBFileBuilder::getMsfBuilder ()
Definition at line 49 of file PDBFileBuilder.cpp.
getNamedStreamIndex()
Expected< uint32_t > PDBFileBuilder::getNamedStreamIndex (StringRef Name) const
Definition at line 218 of file PDBFileBuilder.cpp.
References llvm::arrayRefFromStringRef(), assert(), llvm::BinaryStreamWriter::bytesRemaining(), llvm::cantFail(), llvm::pdb::HashTable< ValueT >::commit(), llvm::pdb::HashTable< ValueT >::empty(), llvm::pdb::NamedStreamMap::get(), llvm::pdb::no_stream, llvm::pdb::SrcHeaderBlockHeader::Size, llvm::pdb::SrcVerOne, llvm::pdb::SrcHeaderBlockHeader::Version, llvm::BinaryStreamWriter::writeBytes(), and llvm::BinaryStreamWriter::writeObject().
Referenced by commit().
getStringTableBuilder()
PDBStringTableBuilder & PDBFileBuilder::getStringTableBuilder ()
Definition at line 75 of file PDBFileBuilder.cpp.
Referenced by addInjectedSource().
getTpiBuilder()
TpiStreamBuilder & PDBFileBuilder::getTpiBuilder ()
Definition at line 63 of file PDBFileBuilder.cpp.
References llvm::pdb::StreamTPI.
initialize()
Error PDBFileBuilder::initialize (uint32_t BlockSize)
Definition at line 41 of file PDBFileBuilder.cpp.
References llvm::Error::success().
operator=()
PDBFileBuilder& llvm::pdb::PDBFileBuilder::operator= (const PDBFileBuilder &) delete
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/PDBFileBuilder.h
lib/DebugInfo/PDB/Native/PDBFileBuilder.cpp