LLVM: llvm::AAEvaluator Class Reference
llvm::AAEvaluator Class Reference
#include "llvm/Analysis/AliasAnalysisEvaluator.h"
Public Member Functions
AAEvaluator ()
AAEvaluator (AAEvaluator &&Arg)
~AAEvaluator ()
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Run the pass over the function.
Friends
class AAEvalLegacyPass
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AAEvaluator >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 33 of file AliasAnalysisEvaluator.h.
Constructor & Destructor Documentation
AAEvaluator() [1/2]
llvm::AAEvaluator::AAEvaluator () inline
Definition at line 40 of file AliasAnalysisEvaluator.h.
Referenced by llvm::AAEvalLegacyPass::doInitialization().
AAEvaluator() [2/2]
llvm::AAEvaluator::AAEvaluator (AAEvaluator && Arg) inline
Definition at line 45 of file AliasAnalysisEvaluator.h.
References Arg, F(), run(), and ~AAEvaluator().
~AAEvaluator()
AAEvaluator::~AAEvaluator ()
Definition at line 334 of file AliasAnalysisEvaluator.cpp.
References llvm::errs(), and PrintPercent().
Referenced by AAEvaluator().
Member Function Documentation
run()
PreservedAnalyses AAEvaluator::run (Function & F, FunctionAnalysisManager & AM)
Run the pass over the function.
Definition at line 89 of file AliasAnalysisEvaluator.cpp.
References llvm::AAResults::alias(), llvm::PreservedAnalyses::all(), llvm::Function::args(), llvm::SetVector< T, Vector, Set >::begin(), Callee, E, llvm::SetVector< T, Vector, Set >::end(), llvm::errs(), EvalAAMD, F(), llvm::MemoryLocation::get(), llvm::Module::getDataLayout(), llvm::AAResults::getModRefInfo(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::DataLayout::getTypeStoreSize(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::inst_begin(), llvm::inst_end(), isInterestingPointer(), llvm::Type::isSized(), llvm::SPII::Load, llvm::MayAlias, llvm::Mod, llvm::ModRef, llvm::Must, llvm::MustAlias, llvm::MustMod, llvm::MustModRef, llvm::MustRef, llvm::NoAlias, llvm::NoModRef, llvm::User::op_begin(), llvm::User::op_end(), llvm::PartialAlias, llvm::LocationSize::precise(), PrintAll, PrintLoadStoreResults(), PrintMayAlias, PrintMod, PrintModRef, PrintModRefResults(), PrintMust, PrintMustAlias, PrintMustMod, PrintMustModRef, PrintMustRef, PrintNoAlias, PrintNoModRef, PrintPartialAlias, PrintRef, PrintResults(), llvm::Ref, Size, llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::size(), llvm::SetVector< T, Vector, Set >::size(), llvm::SPII::Store, and llvm::LocationSize::unknown().
Referenced by AAEvaluator().
Friends And Related Function Documentation
AAEvalLegacyPass
friend class AAEvalLegacyPass friend
Definition at line 63 of file AliasAnalysisEvaluator.h.
Referenced by llvm::createAAEvalPass().
The documentation for this class was generated from the following files:
include/llvm/Analysis/AliasAnalysisEvaluator.h
lib/Analysis/AliasAnalysisEvaluator.cpp