LLVM: llvm::SIScheduleBlock Class Reference
llvm::SIScheduleBlock Class Reference
#include "Target/AMDGPU/SIMachineScheduler.h"
Public Member Functions
SIScheduleBlock (SIScheduleDAGMI *DAG, SIScheduleBlockCreator *BC, unsigned ID)
~SIScheduleBlock ()=default
unsigned getID () const
void addUnit (SUnit *SU)
Functions for Block construction.
void finalizeUnits ()
void addPred (SIScheduleBlock *Pred)
void addSucc (SIScheduleBlock *Succ, SIScheduleBlockLinkKind Kind)
const std::vector< SIScheduleBlock * > & getPreds () const
ArrayRef< std::pair< SIScheduleBlock *, SIScheduleBlockLinkKind > > getSuccs () const
unsigned getNumHighLatencySuccessors () const
bool isHighLatencyBlock ()
int getCost ()
void fastSchedule ()
std::vector< SUnit * > getScheduledUnits ()
void schedule (MachineBasicBlock::iterator BeginBlock, MachineBasicBlock::iterator EndBlock)
bool isScheduled ()
std::vector< unsigned > & getInternalAdditionnalRegUsage ()
std::set< unsigned > & getInRegs ()
std::set< unsigned > & getOutRegs ()
void printDebug (bool Full)
Public Attributes
unsigned Height
unsigned Depth
Detailed Description
Definition at line 61 of file SIMachineScheduler.h.
Constructor & Destructor Documentation
SIScheduleBlock()
llvm::SIScheduleBlock::SIScheduleBlock (SIScheduleDAGMI * DAG, SIScheduleBlockCreator * BC, unsigned ID) inline
Definition at line 104 of file SIMachineScheduler.h.
~SIScheduleBlock()
llvm::SIScheduleBlock::~SIScheduleBlock () default
Member Function Documentation
addPred()
void SIScheduleBlock::addPred (SIScheduleBlock * Pred)
Definition at line 537 of file SIMachineScheduler.cpp.
References assert(), getID(), llvm::none_of(), and P.
addSucc()
void SIScheduleBlock::addSucc (SIScheduleBlock * Succ, SIScheduleBlockLinkKind Kind)
Definition at line 555 of file SIMachineScheduler.cpp.
References assert(), llvm::Data, getID(), isHighLatencyBlock(), llvm::NoData, llvm::none_of(), and P.
addUnit()
void SIScheduleBlock::addUnit (SUnit * SU)
Functions for Block construction.
Definition at line 197 of file SIMachineScheduler.cpp.
References llvm::dbgs(), llvm::Depth, getReasonStr(), llvm::NoCand, llvm::SUnit::NodeNum, llvm::NodeOrder, llvm::RegUsage, llvm::SISched::tryGreater(), and llvm::SISched::tryLess().
fastSchedule()
void SIScheduleBlock::fastSchedule ()
Definition at line 288 of file SIMachineScheduler.cpp.
finalizeUnits()
void SIScheduleBlock::finalizeUnits ()
Definition at line 526 of file SIMachineScheduler.cpp.
References llvm::SUnit::NodeNum.
Referenced by hasDataDependencyPred().
getCost()
int llvm::SIScheduleBlock::getCost () inline
Definition at line 138 of file SIMachineScheduler.h.
getID()
unsigned llvm::SIScheduleBlock::getID () const inline
Definition at line 110 of file SIMachineScheduler.h.
Referenced by addPred(), addSucc(), and llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
getInRegs()
std::set<unsigned>& llvm::SIScheduleBlock::getInRegs () inline
Definition at line 163 of file SIMachineScheduler.h.
Referenced by llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
getInternalAdditionnalRegUsage()
std::vector<unsigned>& llvm::SIScheduleBlock::getInternalAdditionnalRegUsage () inline
Definition at line 159 of file SIMachineScheduler.h.
getNumHighLatencySuccessors()
unsigned llvm::SIScheduleBlock::getNumHighLatencySuccessors () const inline
Definition at line 129 of file SIMachineScheduler.h.
getOutRegs()
std::set<unsigned>& llvm::SIScheduleBlock::getOutRegs () inline
Definition at line 164 of file SIMachineScheduler.h.
References assert(), llvm::Full, llvm::NoCand, and llvm::SISchedulerCandidate::Reason.
Referenced by llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
getPreds()
const std::vector<SIScheduleBlock*>& llvm::SIScheduleBlock::getPreds () const inline
Definition at line 122 of file SIMachineScheduler.h.
Referenced by llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
getScheduledUnits()
std::vector<SUnit*> llvm::SIScheduleBlock::getScheduledUnits () inline
Definition at line 145 of file SIMachineScheduler.h.
Referenced by llvm::SIScheduler::scheduleVariant().
getSuccs()
ArrayRef<std::pair<SIScheduleBlock*, SIScheduleBlockLinkKind> > llvm::SIScheduleBlock::getSuccs () const inline
Definition at line 124 of file SIMachineScheduler.h.
Referenced by llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
isHighLatencyBlock()
bool llvm::SIScheduleBlock::isHighLatencyBlock () inline
Definition at line 133 of file SIMachineScheduler.h.
Referenced by addSucc(), and llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
isScheduled()
bool llvm::SIScheduleBlock::isScheduled () inline
Definition at line 155 of file SIMachineScheduler.h.
printDebug()
void SIScheduleBlock::printDebug (bool Full)
Definition at line 578 of file SIMachineScheduler.cpp.
References llvm::Data, llvm::dbgs(), P, llvm::printVRegOrUnit(), and Reg.
Referenced by hasDataDependencyPred().
schedule()
void SIScheduleBlock::schedule (MachineBasicBlock::iterator BeginBlock, MachineBasicBlock::iterator EndBlock)
Definition at line 398 of file SIMachineScheduler.cpp.
References assert(), llvm::dbgs(), llvm::find(), llvm::SUnit::getInstr(), llvm::SDep::getSUnit(), I, llvm::SUnit::isScheduled, llvm::SDep::isWeak(), llvm_unreachable, llvm::SUnit::NodeNum, llvm::SUnit::NumPredsLeft, llvm::SUnit::Succs, and llvm::SUnit::WeakPredsLeft.
Member Data Documentation
Depth
unsigned llvm::SIScheduleBlock::Depth
Definition at line 127 of file SIMachineScheduler.h.
Height
unsigned llvm::SIScheduleBlock::Height
Definition at line 126 of file SIMachineScheduler.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIMachineScheduler.h
lib/Target/AMDGPU/SIMachineScheduler.cpp