LLVM: llvm::SDNode Class Reference
llvm::SDNode Class Reference
Represents one node in the SelectionDAG.
#include "llvm/CodeGen/SelectionDAGNodes.h"
Classes
class ConstantSDNodeBitfields
class LoadSDNodeBitfields
class LSBaseSDNodeBitfields
class MemSDNodeBitfields
class SDNodeBitfields
class StoreSDNodeBitfields
class use_iterator
This class provides iterator support for SDUse operands that use a specific SDNode.
struct value_op_iterator
Iterator for directly iterating over the operand SDValue's.
Public Types
using op_iterator = SDUse *
using value_iterator = const EVT *
Public Member Functions
unsigned getOpcode () const
Return the SelectionDAG opcode value for this node.
bool isTargetOpcode () const
Test if this node has a target-specific opcode (in the <target>ISD namespace).
bool isTargetStrictFPOpcode () const
Test if this node has a target-specific opcode that may raise FP exceptions (in the <target>ISD namespace and greater than FIRST_TARGET_STRICTFP_OPCODE).
bool isTargetMemoryOpcode () const
Test if this node has a target-specific memory-referencing opcode (in the <target>ISD namespace and greater than FIRST_TARGET_MEMORY_OPCODE).
bool isUndef () const
Return true if the type of the node type undefined.
bool isMemIntrinsic () const
Test if this node is a memory intrinsic (with valid pointer information).
bool isStrictFPOpcode ()
Test if this node is a strict floating point pseudo-op.
bool isMachineOpcode () const
Test if this node has a post-isel opcode, directly corresponding to a MachineInstr opcode.
unsigned getMachineOpcode () const
This may only be called if isMachineOpcode returns true.
bool getHasDebugValue () const
void setHasDebugValue (bool b)
bool isDivergent () const
bool use_empty () const
Return true if there are no uses of this node.
bool hasOneUse () const
Return true if there is exactly one use of this node.
size_t use_size () const
Return the number of uses of this node.
int getNodeId () const
Return the unique node id.
void setNodeId (int Id)
Set unique node id.
unsigned getIROrder () const
Return the node ordering.
void setIROrder (unsigned Order)
Set the node ordering.
const DebugLoc & getDebugLoc () const
Return the source location info.
void setDebugLoc (DebugLoc dl)
Set source location info.
use_iterator use_begin () const
Provide iteration support to walk over all uses of an SDNode.
iterator_range< use_iterator > uses ()
iterator_range< use_iterator > uses () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
Return true if there are exactly NUSES uses of the indicated value.
bool hasAnyUseOfValue (unsigned Value) const
Return true if there are any use of the indicated value.
bool isOnlyUserOf (const SDNode *N) const
Return true if this node is the only use of N.
bool isOperandOf (const SDNode *N) const
Return true if this node is an operand of N.
bool isPredecessorOf (const SDNode *N) const
Return true if this node is a predecessor of N.
bool hasPredecessor (const SDNode *N) const
Return true if N is a predecessor of this node.
unsigned getNumOperands () const
Return the number of values used by this operation.
uint64_t getConstantOperandVal (unsigned Num) const
Helper method returns the integer value of a ConstantSDNode operand.
const APInt & getConstantOperandAPInt (unsigned Num) const
Helper method returns the APInt of a ConstantSDNode operand.
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< SDUse > ops () const
iterator_range< value_op_iterator > op_values () const
SDVTList getVTList () const
SDNode * getGluedNode () const
If this node has a glue operand, return the node to which the glue operand points.
SDNode * getGluedUser () const
If this node has a glue value with a user, return the user (there is at most one).
const SDNodeFlags getFlags () const
void setFlags (SDNodeFlags NewFlags)
bool isFast ()
void intersectFlagsWith (const SDNodeFlags Flags)
Clear any flags in this node that aren't also set in Flags.
unsigned getNumValues () const
Return the number of values defined/returned by this operator.
EVT getValueType (unsigned ResNo) const
Return the type of a specified result.
MVT getSimpleValueType (unsigned ResNo) const
Return the type of a specified result as a simple type.
TypeSize getValueSizeInBits (unsigned ResNo) const
Returns MVT::getSizeInBits(getValueType(ResNo)).
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=nullptr) const
Return the opcode of this operation for printing.
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printr (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printrFull (raw_ostream &O, const SelectionDAG *G=nullptr) const
Print a SelectionDAG node and all children down to the leaves.
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=nullptr, unsigned depth=100) const
Print a SelectionDAG node and children up to depth "depth." The given SelectionDAG allows target-specific nodes to be printed in human-readable form.
void dump () const
Dump this node, for debugging.
void dumpr () const
Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
Dump this node, for debugging.
void dumpr (const SelectionDAG *G) const
Dump (recursively) this node and its use-def subgraph.
void dumprFull (const SelectionDAG *G=nullptr) const
printrFull to dbgs().
void dumprWithDepth (const SelectionDAG *G=nullptr, unsigned depth=100) const
printrWithDepth to dbgs().
void Profile (FoldingSetNodeID &ID) const
Gather unique data for the node.
void addUse (SDUse &U)
This method should only be used by the SDUse class.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< SDNode, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static use_iterator use_end ()
static bool hasPredecessorHelper (const SDNode *N, SmallPtrSetImpl< const SDNode *> &Visited, SmallVectorImpl< const SDNode *> &Worklist, unsigned int MaxSteps=0, bool TopologicalPrune=false)
Returns true if N is a predecessor of any node in Worklist.
static bool areOnlyUsersOf (ArrayRef< const SDNode *> Nodes, const SDNode *N)
Return true if all the users of N are contained in Nodes.
static constexpr size_t getMaxNumOperands ()
Return the maximum number of operands that a SDNode can hold.
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Public Attributes
uint16_t PersistentId
Unique and persistent id per SDNode in the DAG.
Protected Types
enum { NumSDNodeBits = 3 }
enum { NumMemSDNodeBits = NumSDNodeBits + 4 }
enum { NumLSBaseSDNodeBits = NumMemSDNodeBits + 3 }
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< SDNode, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, true, true >
Protected Member Functions
SDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs)
Create an SDNode.
void DropOperands ()
Release the operands and set this node to have zero operands.
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< SDNode, Options... >::type >
ilist_node_impl ()=default
Static Protected Member Functions
static SDVTList getSDVTList (EVT VT)
Protected Attributes
union {
char RawSDNodeBits [sizeof(uint16_t)]
SDNodeBitfields SDNodeBits
ConstantSDNodeBitfields ConstantSDNodeBits
MemSDNodeBitfields MemSDNodeBits
LSBaseSDNodeBitfields LSBaseSDNodeBits
LoadSDNodeBitfields LoadSDNodeBits
StoreSDNodeBitfields StoreSDNodeBits
};
Friends
class SelectionDAG
class HandleSDNode
Detailed Description
Represents one node in the SelectionDAG.
Definition at line 499 of file SelectionDAGNodes.h.
Member Typedef Documentation
op_iterator
using llvm::SDNode::op_iterator = SDUse *
Definition at line 943 of file SelectionDAGNodes.h.
value_iterator
using llvm::SDNode::value_iterator = const EVT *
Definition at line 1020 of file SelectionDAGNodes.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
NumSDNodeBits
Definition at line 530 of file SelectionDAGNodes.h.
anonymous enum
anonymous enum protected
Enumerator
NumMemSDNodeBits
Definition at line 552 of file SelectionDAGNodes.h.
anonymous enum
anonymous enum protected
Enumerator
NumLSBaseSDNodeBits
Definition at line 568 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
SDNode()
llvm::SDNode::SDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs) inline protected
Create an SDNode.
SDNodes are created without any operands, and never own the operand storage. To add operands, see SelectionDAG::createOperands.
Definition at line 1096 of file SelectionDAGNodes.h.
References assert(), llvm::DebugLoc::hasTrivialDestructor(), and llvm::SDVTList::NumVTs.
Member Function Documentation
addUse()
void llvm::SDNode::addUse (SDUse & U) inline
This method should only be used by the SDUse class.
Definition at line 1084 of file SelectionDAGNodes.h.
Referenced by llvm::SDValue::dumpr().
areOnlyUsersOf()
bool SDNode::areOnlyUsersOf (ArrayRef< const SDNode *> Nodes, const SDNode * N) static
Return true if all the users of N are contained in Nodes.
Return true if the only users of N are contained in Nodes.
NOTE: Requires at least one match, but doesn't require them all.
Definition at line 9074 of file SelectionDAG.cpp.
References llvm::any_of(), E, I, llvm::FoldingSetBase::Node::Node(), use_begin(), and use_end().
Referenced by combineX86ShufflesRecursively().
DropOperands()
void SDNode::DropOperands () protected
Release the operands and set this node to have zero operands.
DropOperands - Release the operands and set this node to have zero operands.
Definition at line 7723 of file SelectionDAG.cpp.
References E, and I.
Referenced by llvm::SelectionDAG::DeleteNode().
dump() [1/2]
LLVM_DUMP_METHOD void SDNode::dump () const
Dump this node, for debugging.
Definition at line 501 of file SelectionDAGDumper.cpp.
Referenced by llvm::AVRDAGToDAGISel::select< ISD::BRIND >(), llvm::ScheduleDAGSDNodes::dumpNode(), earlyExpandDIVFIX(), llvm::InstrEmitter::EmitDbgLabel(), getCombineLoadStoreParts(), GetFPLibCall(), getIPMConversion(), GetPromotionOpcode(), getVPTESTMOpc(), isTargetConstant(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), mayUseP9Setb(), NewSDValueDbgMsg(), numVectorEltsOrZero(), PeepholePPC64ZExtGather(), PerformSHLSimplify(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::SelectionDAGISel::SelectCodeCommon(), selectI64Imm(), llvm::HvxSelector::selectShuffle(), simplifyDivRem(), tryLowerToSLI(), and VerifySDNode().
dump() [2/2]
LLVM_DUMP_METHOD void SDNode::dump (const SelectionDAG * G) const
Dump this node, for debugging.
The given SelectionDAG allows target-specific nodes to be printed in human-readable form.
Definition at line 503 of file SelectionDAGDumper.cpp.
References llvm::dbgs(), and print().
dumpr() [1/2]
LLVM_DUMP_METHOD void SDNode::dumpr () const
Dump (recursively) this node and its use-def subgraph.
Definition at line 918 of file SelectionDAGDumper.cpp.
Referenced by llvm::HexagonTargetLowering::LowerOperation().
dumpr() [2/2]
LLVM_DUMP_METHOD void SDNode::dumpr (const SelectionDAG * G) const
Dump (recursively) this node and its use-def subgraph.
The given SelectionDAG allows target-specific nodes to be printed in human-readable form.
Definition at line 923 of file SelectionDAGDumper.cpp.
dumprFull()
LLVM_DUMP_METHOD void SDNode::dumprFull (const SelectionDAG * G = nullptr) const
printrFull to dbgs().
The given SelectionDAG allows target-specific nodes to be printed in human-readable form. Unlike dumpr, this will print the whole DAG, including children that appear multiple times.
Definition at line 967 of file SelectionDAGDumper.cpp.
Referenced by checkForCyclesHelper(), and llvm::SelectionDAG::salvageDebugInfo().
dumprWithDepth()
LLVM_DUMP_METHOD void SDNode::dumprWithDepth (const SelectionDAG * G = nullptr, unsigned depth = 100) const
printrWithDepth to dbgs().
The given SelectionDAG allows target-specific nodes to be printed in human-readable form. Unlike dumpr, this will print children that appear multiple times wherever they are used.
Definition at line 963 of file SelectionDAGDumper.cpp.
getConstantOperandAPInt()
const APInt & llvm::SDNode::getConstantOperandAPInt (unsigned Num) const inline
Helper method returns the APInt of a ConstantSDNode operand.
Definition at line 1601 of file SelectionDAGNodes.h.
References llvm::SDValue::getOperand().
Referenced by collectConcatOps(), and combineScalarAndWithMaskSetcc().
getConstantOperandVal()
uint64_t llvm::SDNode::getConstantOperandVal (unsigned Num) const inline
Helper method returns the integer value of a ConstantSDNode operand.
Definition at line 1597 of file SelectionDAGNodes.h.
References llvm::SDValue::getOperand().
Referenced by callingConvSupported(), combineBrCond(), combineCMov(), combineExtractWithShuffle(), combineInsertSubvector(), combineOrCmpEqZeroToCtlzSrl(), combineVectorShiftImm(), combineX86SetCC(), ConstantBuildVector(), earlyExpandDIVFIX(), llvm::InstrEmitter::EmitDbgLabel(), findEXTRHalf(), FoldIntToFPToInt(), foldXor1SetCC(), getBufferOffsetForMMO(), getCondFromNode(), GetFPLibCall(), getPermuteMask(), getPromotedVectorElementType(), getShuffleScalarElt(), getTargetShuffleMask(), getVPTESTMOpc(), isCalleeLoad(), llvm::AArch64TargetLowering::isDesirableToCommuteWithShift(), isSlicingProfitable(), lowerMSABitClearImm(), mayUseP9Setb(), narrowExtractedVectorLoad(), needCarryOrOverflowFlag(), onlyZeroFlagUsed(), PeepholePPC64ZExtGather(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceZeroVectorStore(), llvm::SelectionDAG::salvageDebugInfo(), and llvm::SITargetLowering::shouldEmitPCReloc().
getDebugLoc()
const DebugLoc& llvm::SDNode::getDebugLoc () const inline
Return the source location info.
Definition at line 753 of file SelectionDAGNodes.h.
Referenced by llvm::InstrEmitter::EmitDbgLabel(), llvm::SelectionDAG::SelectNodeTo(), and llvm::SelectionDAG::shouldOptForSize().
getFlags()
const SDNodeFlags llvm::SDNode::getFlags () const inline
Definition at line 989 of file SelectionDAGNodes.h.
Referenced by llvm::TargetLowering::BuildSDIV(), CanCombineFCOPYSIGN_EXTEND_ROUND(), CollectOpsToWiden(), combineAdd(), combineFMinNumFMaxNum(), combineFneg(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), llvm::createR600ISelDag(), llvm::InstrEmitter::EmitDbgLabel(), EmitTest(), expandf64Toi32(), findMemSDNode(), foldAddSubOfSignBit(), FoldIntToFPToInt(), fp16SrcZerosHighBits(), getAsNonOpaqueConstant(), llvm::TargetLowering::getNegatedExpression(), getPromotedVectorElementType(), GetPromotionOpcode(), getReductionSDNode(), getSPDenormModeValue(), getVectorCompareInfo(), isCalleeLoad(), isClampZeroToOne(), isContractable(), llvm::SelectionDAG::isKnownNeverNaN(), llvm::TargetLowering::isNegatibleForFree(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::SelectionDAG::matchBinOpReduction(), llvm::AMDGPUTargetLowering::mayIgnoreSignedZero(), narrowExtractedVectorBinOp(), narrowInsertExtractVectorBinOp(), llvm::AMDGPUTargetLowering::performFNegCombine(), print_details(), promoteExtBeforeAdd(), scalarizeBinOpOfSplats(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyDivRem(), simplifyShuffleOfShuffle(), llvm::SITargetLowering::splitBinaryVectorOp(), llvm::SITargetLowering::splitTernaryVectorOp(), llvm::SITargetLowering::splitUnaryVectorOp(), stripTruncAndExt(), tryFoldToZero(), llvm::SelectionDAG::UnrollVectorOp(), and visitORCommutative().
getGluedNode()
SDNode* llvm::SDNode::getGluedNode () const inline
If this node has a glue operand, return the node to which the glue operand points.
Otherwise return NULL.
Definition at line 973 of file SelectionDAGNodes.h.
References llvm::MVT::Glue.
Referenced by addStackMapLiveVars(), llvm::ScheduleDAGSDNodes::RegDefIter::Advance(), canClobberPhysRegDefs(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::ScheduleDAGSDNodes::EmitSchedule(), getARClassRegisterMask(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), isOperandOf(), llvm::ResourcePriorityQueue::isResourceAvailable(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LowerADDRSPACECAST(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), and llvm::ResourcePriorityQueue::reserveResources().
getGluedUser()
SDNode* llvm::SDNode::getGluedUser () const inline
If this node has a glue value with a user, return the user (there is at most one).
Otherwise return NULL.
Definition at line 982 of file SelectionDAGNodes.h.
References llvm::MVT::Glue.
Referenced by llvm::InstrEmitter::EmitDbgLabel(), findGluedUser(), and getARClassRegisterMask().
getHasDebugValue()
bool llvm::SDNode::getHasDebugValue () const inline
Definition at line 723 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::AddDbgValue(), ProcessSDDbgValues(), llvm::SelectionDAG::salvageDebugInfo(), and llvm::SelectionDAG::transferDbgValues().
getIndexedModeName()
const char * SDNode::getIndexedModeName (ISD::MemIndexedMode AM) static
Definition at line 454 of file SelectionDAGDumper.cpp.
References llvm::ISD::POST_DEC, llvm::ISD::POST_INC, llvm::ISD::PRE_DEC, and llvm::ISD::PRE_INC.
getIROrder()
unsigned llvm::SDNode::getIROrder () const inline
Return the node ordering.
Definition at line 747 of file SelectionDAGNodes.h.
Referenced by PerformADDCombineWithOperands(), ProcessSourceNode(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), llvm::SelectionDAG::SelectNodeTo(), llvm::SelectionDAG::shouldOptForSize(), and llvm::SelectionDAG::transferDbgValues().
getMachineOpcode()
unsigned llvm::SDNode::getMachineOpcode () const inline
This may only be called if isMachineOpcode returns true.
It returns the MachineInstr opcode value that the node's opcode corresponds to.
Definition at line 718 of file SelectionDAGNodes.h.
References assert().
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::ARMBaseInstrInfo::areLoadsFromSameBasePtr(), llvm::X86InstrInfo::areLoadsFromSameBasePtr(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), CalcNodeSethiUllmanNumber(), canClobberPhysRegDefs(), canClobberReachingPhysRegUse(), llvm::Thumb1InstrInfo::canCopyGluedNodeDuringSchedule(), canEnableCoalescing(), CheckForPhysRegDependency(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), llvm::createR600ISelDag(), llvm::InstrEmitter::EmitDbgLabel(), FindCallSeqStart(), getCondFromNode(), llvm::TargetInstrInfo::getInstrLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), getOperationName(), getPhysicalRegisterVT(), llvm::ARMTargetLowering::getSchedulingPreference(), getUsefulBitsForUse(), gwsIntrinToOpcode(), isBitfieldExtractOp(), isCalleeLoad(), IsChainDependent(), isMemOPCandidate(), llvm::ResourcePriorityQueue::isResourceAvailable(), llvm::SelectionDAGISel::mayRaiseFPException(), llvm::ScheduleDAGSDNodes::newSUnit(), nodesHaveSameOperandValue(), PeepholePPC64ZExtGather(), PerformANDCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PostISelFolding(), llvm::ResourcePriorityQueue::reserveResources(), llvm::ARMBaseInstrInfo::shouldScheduleLoadsNear(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), and llvm::X86InstrInfo::unfoldMemoryOperand().
getMaxNumOperands()
static constexpr size_t llvm::SDNode::getMaxNumOperands () inline static
Return the maximum number of operands that a SDNode can hold.
Definition at line 928 of file SelectionDAGNodes.h.
References llvm::max().
Referenced by llvm::SelectionDAG::getTokenFactor(), and llvm::SelectionDAG::isConstantFPBuildVectorOrConstantFP().
getNodeId()
int llvm::SDNode::getNodeId () const inline
Return the unique node id.
Definition at line 741 of file SelectionDAGNodes.h.
Referenced by canEnableCoalescing(), getContiguousRangeOfSetBits(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), llvm::SelectionDAGISel::getUninvalidatedNodeId(), hasPredecessorHelper(), insertDAGNode(), llvm::SelectionDAGISel::InvalidateNodeId(), and isOperandOf().
getNumOperands()
unsigned llvm::SDNode::getNumOperands () const inline
Return the number of values used by this operation.
Definition at line 925 of file SelectionDAGNodes.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddGlue(), addShuffleForVecExtend(), llvm::ISD::allOperandsUndef(), llvm::SelectionDAG::AssignTopologicalOrder(), canReduceVMulWidth(), CollectOpsToWiden(), CombineBaseUpdate(), combineBVOfConsecutiveLoads(), combineBVOfVecSExt(), combineConcatVectorOfExtracts(), combineFMA(), combineFMADDSUB(), computeZeroableShuffleElements(), createMMXBuildVector(), llvm::createR600ISelDag(), llvm::SDNodeIterator::end(), ExpandBVWithShuffles(), expandIntrinsicWChainHelper(), foldBitcastedFPLogic(), llvm::PPC::get_VSPLTI_elt(), getARClassRegisterMask(), GetFPLibCall(), getInputChainForNode(), getNormalLoadInput(), getShiftAmountTyForConstant(), llvm::BuildVectorSDNode::getSplatValue(), getTargetShuffleMask(), getTargetVShiftByConstNode(), getTestBitOperand(), gwsIntrinToOpcode(), haveEfficientBuildVectorPattern(), llvm::ISD::isBuildVectorAllOnes(), isConstantOrUndefBUILD_VECTOR(), llvm::BuildVectorSDNode::isConstantSplat(), isExtendedBUILD_VECTOR(), isFPExtLoad(), isMemOPCandidate(), isOpcWithIntImmediate(), isPermutation(), isSETCCorConvertedSETCC(), isSplatZeroExtended(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LowerADDRSPACECAST(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerDSPIntr(), LowerInterruptReturn(), opMustUseVOP3Encoding(), Passv64i1ArgInRegs(), performANDCombine(), PerformANDCombine(), PerformBUILD_VECTORCombine(), performConcatVectorsCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performSRACombine(), pickOpcodeForVT(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), reduceBuildVecToShuffleWithZero(), replaceInChain(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), scalarizeExtractedBinop(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), selectSGPRVectorRegClassID(), ShrinkLoadReplaceStoreWithStore(), simplifyShuffleOfShuffle(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::updateDivergence(), llvm::SelectionDAG::UpdateNodeOperands(), and VerifySDNode().
getNumValues()
unsigned llvm::SDNode::getNumValues () const inline
Return the number of values defined/returned by this operator.
Definition at line 998 of file SelectionDAGNodes.h.
Referenced by AddGlue(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), BURRSort(), CalcNodeSethiUllmanNumber(), callingConvSupported(), canChangeToInt(), canClobberPhysRegDefs(), combineShiftAnd1ToBitTest(), llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), constructRetValue(), doNotCSE(), earlyExpandDIVFIX(), llvm::InstrEmitter::EmitDbgLabel(), emitIntrinsicWithCCAndChain(), findGlueUse(), FixedPointIntrinsicToOpcode(), getAsNonOpaqueConstant(), getCCResult(), getContiguousRangeOfSetBits(), getFPBinOp(), GetFPLibCall(), getFPTernOp(), getOutputChainFromCallSeq(), llvm::ARMTargetLowering::getSchedulingPreference(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), GetVBR(), hasAnyUseOfValue(), hasNUsesOfValue(), llvm::SelectionDAGISel::IsLegalToFold(), isMemOPCandidate(), isOperandOf(), llvm::SITargetLowering::legalizeTargetIndependentNode(), lowerCallResult(), LowerCallResult(), LowerInterruptReturn(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::MipsTargetLowering::LowerOperationWrapper(), llvm::X86TargetLowering::LowerOperationWrapper(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), narrowExtractedVectorBinOp(), narrowInsertExtractVectorBinOp(), llvm::DAGTypeLegalizer::NoteDeletion(), Passv64i1ArgInRegs(), llvm::AArch64TargetLowering::PerformDAGCombine(), print_types(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), RemoveUnusedGlue(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), scalarizeExtractedBinop(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::TargetLowering::ShrinkDemandedOp(), simplifyDivRem(), simplifyShuffleOfShuffle(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), and VerifySDNode().
getOpcode()
unsigned llvm::SDNode::getOpcode () const inline
Return the SelectionDAG opcode value for this node.
For pre-isel nodes (those for which isMachineOpcode returns false), these are the opcode values in the ISD and <target>ISD namespaces. For post-isel opcodes, see getMachineOpcode.
Definition at line 663 of file SelectionDAGNodes.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineTo64bitUMAAL(), AddNodeIDCustom(), AddNodeIDNode(), addStackMapLiveVars(), adjustForFNeg(), adjustForLTGFR(), adjustForSubtraction(), llvm::AVRDAGToDAGISel::select< ISD::BRIND >(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), CalcNodeSethiUllmanNumber(), callingConvSupported(), canEmitConjunction(), canEnableCoalescing(), canFoldInAddressingMode(), canonicalizeBitSelect(), CheckAndImm(), CheckForMaskedLoad(), CheckForPhysRegDependency(), checkHighLaneIndex(), CheckOpcode(), CheckOrImm(), checkValueWidth(), llvm::AddrSpaceCastSDNode::classof(), llvm::MemSDNode::classof(), llvm::AtomicSDNode::classof(), llvm::MemIntrinsicSDNode::classof(), llvm::X86StoreSDNode::classof(), llvm::ShuffleVectorSDNode::classof(), llvm::X86MaskedStoreSDNode::classof(), llvm::TruncSStoreSDNode::classof(), llvm::ConstantSDNode::classof(), llvm::TruncUSStoreSDNode::classof(), llvm::MaskedTruncSStoreSDNode::classof(), llvm::MaskedTruncUSStoreSDNode::classof(), llvm::X86MaskedGatherScatterSDNode::classof(), llvm::ConstantFPSDNode::classof(), llvm::X86MaskedGatherSDNode::classof(), llvm::X86MaskedScatterSDNode::classof(), llvm::GlobalAddressSDNode::classof(), llvm::FrameIndexSDNode::classof(), llvm::LifetimeSDNode::classof(), llvm::JumpTableSDNode::classof(), llvm::ConstantPoolSDNode::classof(), llvm::TargetIndexSDNode::classof(), llvm::BasicBlockSDNode::classof(), llvm::BuildVectorSDNode::classof(), llvm::SrcValueSDNode::classof(), llvm::MDNodeSDNode::classof(), llvm::RegisterSDNode::classof(), llvm::RegisterMaskSDNode::classof(), llvm::BlockAddressSDNode::classof(), llvm::LabelSDNode::classof(), llvm::ExternalSymbolSDNode::classof(), llvm::MCSymbolSDNode::classof(), llvm::CondCodeSDNode::classof(), llvm::VTSDNode::classof(), llvm::LSBaseSDNode::classof(), llvm::LoadSDNode::classof(), llvm::StoreSDNode::classof(), llvm::MaskedLoadStoreSDNode::classof(), llvm::MaskedLoadSDNode::classof(), llvm::MaskedStoreSDNode::classof(), llvm::MaskedGatherScatterSDNode::classof(), llvm::MaskedGatherSDNode::classof(), llvm::MaskedScatterSDNode::classof(), CloneNodeWithValues(), closestSucc(), collectConcatOps(), CollectOpsToWiden(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), CombineANDShift(), combineANDXORWithAllOnesIntoANDNP(), CombineBaseUpdate(), combineBVOfConsecutiveLoads(), combineBVOfVecSExt(), combineCarryDiamond(), combineCastedMaskArithmetic(), combineCCMask(), combineConcatVectorOfExtracts(), combineCVTP2I_CVTTP2I(), combineExtInVec(), combineExtractVectorElt(), combineExtractWithShuffle(), combineExtSetcc(), combineFaddFsub(), combineFMA(), combineFMADDSUB(), combineFMinFMax(), combineFMinNumFMaxNum(), combineFOr(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMul(), combineOrCmpEqZeroToCtlzSrl(), combineOrShiftToFunnelShift(), combinePMULDQ(), combineReductionToHorizontal(), combineScalarAndWithMaskSetcc(), combineSelectAndUse(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineShuffle(), combineShuffleToFMAddSub(), combineSignExtendInReg(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), combineToFPTruncExtElt(), combineTruncatedArithmetic(), combineVectorCompare(), combineVectorCompareAndMaskUnaryOp(), combineVectorInsert(), combineVectorPack(), combineVectorShiftImm(), combineVectorShiftVar(), CombineVLDDUP(), combineX86AddSub(), combineX86INT_TO_FP(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), convertIntLogicToFPLogic(), llvm::createARCISelDag(), llvm::createR600ISelDag(), llvm::createXCoreISelDag(), customLegalizeToWOp(), customLegalizeToWOpWithSExt(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), doNotCSE(), earlyExpandDIVFIX(), emitConjunctionRec(), llvm::InstrEmitter::EmitDbgLabel(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), EmitTest(), Expand64BitShift(), expandDisp(), llvm::TargetLowering::expandMUL(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), extractBooleanFlip(), FindCallSeqStart(), findConsecutiveLoad(), findMemSDNode(), findMUL_LOHI(), findUser(), foldAddSubBoolOfMaskedVal(), foldAddSubOfSignBit(), foldBitcastedFPLogic(), foldExtendedSignBitTest(), foldFPToIntToFP(), FoldIntToFPToInt(), foldMaskedShiftToBEXTR(), foldShuffleOfHorizOp(), llvm::SelectionDAG::FoldSymbolOffset(), foldXor1SetCC(), generateEquivalentSub(), getARClassRegisterMask(), getARMIndexedAddressParts(), getAsNonOpaqueConstant(), getBuildPairElt(), getCombineLoadStoreParts(), getContiguousRangeOfSetBits(), getDivRemArgList(), getDivRemLibcall(), getExpandedMinMaxOps(), GetFPLibCall(), getInputChainForNode(), getIntOperandFromRegisterString(), getIntrinsicID(), getIPMConversion(), getMOVL(), getMVEIndexedAddressParts(), llvm::SelectionDAG::getNode(), getNormalLoadInput(), getOperationName(), getPermuteMask(), getPhysicalRegisterVT(), llvm::AVRTargetLowering::getPostIndexedAddressParts(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::AVRTargetLowering::getPreIndexedAddressParts(), getPromotedVectorElementType(), GetPromotionOpcode(), getPTXCmpMode(), llvm::AVRTargetLowering::getSetCCResultType(), getShiftAmountTyForConstant(), getSPDenormModeValue(), getSplatConstantFP(), getT2IndexedAddressParts(), getTargetConstantBitsFromNode(), getTargetConstantFromNode(), getTargetShuffleMask(), getTestBitOperand(), GetVBR(), getVPTESTMOpc(), hasNonFlagsUse(), hasOnlyLiveInOpers(), hasOnlyLiveOutUses(), hasPredecessorHelper(), hasSingleUsesFromRoot(), hasSourceMods(), hasVRegCycleUse(), isADDADDMUL(), isAddSubOrSubAdd(), isAddSubSExt(), isAddSubZExt(), isBitfieldExtractOp(), isBitfieldExtractOpFromAnd(), isBitfieldExtractOpFromSExtInReg(), isBitfieldExtractOpFromShr(), isBitwiseInverse(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::isBuildVectorOfConstantFPSDNodes(), llvm::ISD::isBuildVectorOfConstantSDNodes(), isCalleeLoad(), IsChainDependent(), isClampZeroToOne(), isConditionalZeroOrAllOnes(), isConsecutiveLS(), isConstantSplatVectorMaskForType(), isContractable(), isCopyFromRegOfInlineAsm(), llvm::AArch64TargetLowering::isDesirableToCommuteWithShift(), llvm::ARMTargetLowering::isDesirableToCommuteWithShift(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isExtendedBUILD_VECTOR(), isFloatingPointZero(), llvm::TargetLoweringBase::isFMADLegalForFAddFSub(), isFNEG(), isFPExtLoad(), llvm::TargetLowering::isGAPlusOffset(), isHorizontalBinOpPart(), isInt32Immediate(), isInt64Immediate(), isLegalMaskCompare(), isMemOPCandidate(), isOpcodeHandled(), isOpcWithIntImmediate(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::ScheduleDAGSDNodes::isPassiveNode(), isPermutation(), isSaturatingConditional(), llvm::AMDGPUTargetLowering::isSDNodeAlwaysUniform(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), isSETCCorConvertedSETCC(), isSeveralBitsExtractOpFromShr(), isSignExtended(), isSlicingProfitable(), isTargetConstant(), isTruncateOf(), isVectorAllOnes(), llvm::ARMTargetLowering::isVectorLoadExtDesirable(), IsVUZPShuffleNode(), isZeroExtended(), isZeroVector(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), lowerAtomicArith(), lowerAtomicArithWithLOCK(), LowerBUILD_VECTOR_i1(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallFromStatepointLoweringInfo(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), LowerCTTZ(), LowerEXTRACT_VECTOR_ELT_SSE4(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerMULH(), llvm::HexagonTargetLowering::LowerOperationWrapper(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerSADDSUBSAT(), LowerShift(), lowerUINT_TO_FP_v2i32(), LowerVECTOR_SHUFFLE(), lowerX86FPLogicOp(), maskMatters(), llvm::SelectionDAG::matchBinOpReduction(), matchLogicBlend(), matchLSNode(), matchPMADDWD(), MayFoldIntoZeroExtend(), mayUseP9Setb(), MergeInputChains(), narrowVectorSelect(), needCarryOrOverflowFlag(), numVectorEltsOrZero(), onlyZeroFlagUsed(), llvm::TargetLowering::parametersInCSRMatch(), ParseBFI(), Passv64i1ArgInRegs(), PerformABSCombine(), PerformADDCombineWithOperands(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performAddSubLongCombine(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::performAssertSZExtCombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), performCMovFPCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCONDCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::MipsSETargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::LanaiTargetLowering::PerformDAGCombine(), llvm::SparcTargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformDAGCombine(), llvm::MipsTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::X86TargetLowering::PerformDAGCombine(), performDivRemCombine(), performExtendCombine(), PerformExtendCombine(), performFDivCombine(), performFpToIntCombine(), performGlobalAddressCombine(), performIntegerAbsCombine(), performIntToFpCombine(), performMADD_MSUBCombine(), performMulCombine(), llvm::AMDGPUTargetLowering::performMulLoHi24Combine(), performNEONPostLDSTCombine(), performORCombine(), PerformORCombine_i1(), performPostLD1Combine(), PerformPREDICATE_CASTCombine(), PerformREMCombine(), performSetccAddFolding(), PerformSETCCCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), PerformSHLSimplify(), performSignExtendInRegCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSRACombine(), PerformSTORECombine(), PerformSUBCombine(), performSVEAndCombine(), performTBZCombine(), PerformUMLALCombine(), PerformVCVTCombine(), PerformVDIVCombine(), performVectorCompareAndMaskUnaryOpCombine(), performXORCombine(), pickOpcodeForVT(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), llvm::SDValue::reachesChainWithoutSideEffects(), reduceBuildVecToShuffleWithZero(), llvm::SelectionDAG::RemoveDeadNodes(), ReplaceCMP_SWAP_128Results(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::XCoreTargetLowering::ReplaceNodeResults(), llvm::HexagonTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::AMDGPUTargetLowering::ReplaceNodeResults(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), resetVRegCycle(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), llvm::SelectionDAG::salvageDebugInfo(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), scalarizeExtractedBinop(), SDValueToConstBool(), SearchLoopIntrinsic(), llvm::HexagonDAGToDAGISel::Select(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), selectI64Imm(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), selectSGPRVectorRegClassID(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask(), llvm::SelectionDAG::shouldOptForSize(), shouldUseLA(), shouldUseZeroOffsetLdSt(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), simplifyI24(), simplifyShuffleOfShuffle(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), stripModuloOnShift(), stripTruncAndExt(), truncateScalarIntegerArg(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), tryCombineToEXTR(), tryExtendDUPToExtractHigh(), tryFoldToZero(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UnrollVectorOverflowOp(), llvm::X86TargetLowering::unwrapAddress(), useSinCos(), VerifySDNode(), visitFMinMax(), and widenCtPop().
getOperand()
const SDValue& llvm::SDNode::getOperand (unsigned Num) const inline
Definition at line 938 of file SelectionDAGNodes.h.
References assert().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), AddCombineToVPADD(), AddGlue(), llvm::MipsSETargetLowering::addMSAFloatType(), addStackMapLiveVars(), adjustForLTGFR(), adjustForSubtraction(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::ARMBaseInstrInfo::areLoadsFromSameBasePtr(), llvm::X86InstrInfo::areLoadsFromSameBasePtr(), llvm::AVRDAGToDAGISel::select< ISD::BRIND >(), buildCallOperands(), BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), calculateByteProvider(), callingConvSupported(), CanCombineFCOPYSIGN_EXTEND_ROUND(), canEmitConjunction(), canEnableCoalescing(), canFoldInAddressingMode(), canLowerToLDG(), canonicalizeBitSelect(), canReduceVMulWidth(), CheckAndImm(), CheckForMaskedLoad(), CheckForPhysRegDependency(), checkHighLaneIndex(), CheckOrImm(), checkV64LaneV128(), checkValueWidth(), collectConcatOps(), CollectOpsToWiden(), combineAcrossLanesIntrinsic(), combineADC(), combineAdd(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineAnd(), combineAndMaskToShift(), combineAndnp(), CombineANDShift(), combineANDXORWithAllOnesIntoANDNP(), CombineBaseUpdate(), combineBasicSADPattern(), combineBEXTR(), combineBitcast(), combineBrCond(), combineBT(), combineBVOfConsecutiveLoads(), combineBVOfVecSExt(), combineCastedMaskArithmetic(), combineCCMask(), combineCMov(), combineCMP(), combineCompareEqual(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectors(), combineCVTP2I_CVTTP2I(), combineExtInVec(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineExtSetcc(), combineFaddFsub(), combineFAnd(), combineFAndFNotToFAndn(), combineFAndn(), combineFMA(), combineFMADDSUB(), combineFMinFMax(), combineFMinNumFMaxNum(), combineFOr(), combineInsertSubvector(), combineKSHIFT(), combineLogicBlendIntoConditionalNegate(), combineLoopMAddPattern(), combineLoopSADPattern(), combineMaskedLoadConstantMask(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combineOrCmpEqZeroToCtlzSrl(), combineOrShiftToFunnelShift(), combineParity(), combinePMULDQ(), combineReductionToHorizontal(), combineSBB(), combineScalarAndWithMaskSetcc(), combineScalarToVector(), combineSelectAndUseCommutative(), combineSetCC(), combineSext(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShiftOfShiftedLogic(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShuffle(), combineShuffleOfConcatUndef(), combineShuffleOfScalars(), combineShuffleOfSplatVal(), combineShuffleToFMAddSub(), combineShuffleToVectorExtend(), combineSignExtendInReg(), combineSIntToFP(), combineStore(), combineSub(), combineSubToSubus(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), combineToFPTruncExtElt(), combineTruncate(), combineTruncatedArithmetic(), combineTruncationShuffle(), combineUIntToFP(), combineVectorCompare(), combineVectorCompareAndMaskUnaryOp(), combineVectorPack(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncation(), combineVectorTruncationWithPACKSS(), combineVectorTruncationWithPACKUS(), CombineVLDDUP(), CombineVMOVDRRCandidateWithVecOp(), combineVTRUNC(), combineX86AddSub(), combineX86INT_TO_FP(), combineX86SetCC(), combineXor(), combineZext(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), ConstantBuildVector(), convertIntLogicToFPLogic(), convertShiftLeftToScale(), createBSWAPShuffleMask(), createMMXBuildVector(), llvm::createMSP430ISelDag(), llvm::createR600ISelDag(), llvm::createXCoreISelDag(), customLegalizeToWOp(), customLegalizeToWOpWithSExt(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), detectZextAbsDiff(), earlyExpandDIVFIX(), elementPairIsContiguous(), EmitCmp(), emitConjunctionRec(), llvm::InstrEmitter::EmitDbgLabel(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), EmitTest(), Expand64BitShift(), llvm::TargetLowering::expandABS(), ExpandBITCAST(), ExpandBVWithShuffles(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandMUL(), ExpandREAD_REGISTER(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), extractBooleanFlip(), FindBFIToCombineWith(), findEXTRHalf(), findMemSDNode(), findUser(), foldAddSubBoolOfMaskedVal(), foldAddSubMasked1(), foldAddSubOfSignBit(), foldBitcastedFPLogic(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::FoldConstantVectorArithmetic(), foldExtendedSignBitTest(), foldFPToIntToFP(), FoldIntToFPToInt(), foldMaskedShiftToScaledMask(), foldShuffleOfConcatUndefs(), foldShuffleOfHorizOp(), foldVectorXorShiftIntoCmp(), foldXor1SetCC(), foldXorTruncShiftIntoCmp(), fp16SrcZerosHighBits(), generateEquivalentSub(), GeneratePerfectShuffle(), llvm::PPC::get_VSPLTI_elt(), getARClassRegisterMask(), getARMIndexedAddressParts(), getAsNonOpaqueConstant(), getBufferOffsetForMMO(), getBuildPairElt(), getCombineLoadStoreParts(), llvm::SelectionDAG::getCommutedVectorShuffle(), getContiguousRangeOfSetBits(), getExpandedMinMaxOps(), GetFPLibCall(), getHopForBuildVector(), getInputChainForNode(), getIntOperandFromRegisterString(), getIntrinsicID(), getIPMConversion(), getKnownUndefForVectorBinop(), getMad64_32(), getMVEIndexedAddressParts(), getNormalLoadInput(), getOneTrueElt(), llvm::ARMBaseInstrInfo::getOperandLatency(), getOperationName(), getPermuteMask(), llvm::AVRTargetLowering::getPostIndexedAddressParts(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::AVRTargetLowering::getPreIndexedAddressParts(), getPromotedVectorElementType(), GetPromotionOpcode(), getPTXCmpMode(), getSETCCOperandType(), llvm::AVRTargetLowering::getSetCCResultType(), getShiftAmountTyForConstant(), getShuffleScalarElt(), getSPDenormModeValue(), getSplatConstantFP(), llvm::BuildVectorSDNode::getSplatValue(), getT2IndexedAddressParts(), getTargetConstantBitsFromNode(), getTargetConstantFromNode(), getTargetShuffleMask(), getTargetVShiftByConstNode(), getTestBitOperand(), getUnderlyingExtractedFromVec(), getUsefulBitsForUse(), getVCmpInst(), getVectorCompareInfo(), llvm::SelectionDAG::getVectorShuffle(), getVPTESTMOpc(), gwsIntrinToOpcode(), HandleMergeInputChains(), hasNormalLoadOperand(), hasOnlyLiveInOpers(), hasOnlyLiveOutUses(), hasSingleUsesFromRoot(), hasSourceMods(), haveEfficientBuildVectorPattern(), isADDADDMUL(), isAddSubOrSubAdd(), isAddSubSExt(), isAddSubZExt(), isAllConstantBuildVector(), isBitfieldExtractOp(), isBitfieldExtractOpFromAnd(), isBitfieldExtractOpFromSExtInReg(), isBitfieldExtractOpFromShr(), isBitwiseInverse(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), isCalleeLoad(), isClampZeroToOne(), isConditionalZeroOrAllOnes(), isConsecutiveLS(), isConstantOrUndefBUILD_VECTOR(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVectorMaskForType(), isContractable(), isCopyFromRegOfInlineAsm(), llvm::RISCVTargetLowering::isDesirableToCommuteWithShift(), llvm::AArch64TargetLowering::isDesirableToCommuteWithShift(), llvm::ARMTargetLowering::isDesirableToCommuteWithShift(), isDispSafeForFrameIndex(), isExtendedBUILD_VECTOR(), isFloatingPointZero(), isFNEG(), isFPExtLoad(), isFusableLoadOpStorePattern(), llvm::TargetLowering::isGAPlusOffset(), isHopBuildVector(), isHorizontalBinOpPart(), isLegalMaskCompare(), llvm::SelectionDAGISel::IsLegalToFold(), isMemOPCandidate(), isOpcodeHandled(), isOpcWithIntImmediate(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), isPerfectIncrement(), isPermutation(), isSaturatingConditional(), llvm::AMDGPUTargetLowering::isSDNodeAlwaysUniform(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), isSETCCorConvertedSETCC(), isSetCCOrZExtSetCC(), isSeveralBitsExtractOpFromShr(), isSlicingProfitable(), isSplatZeroExtended(), isSubBorrowChain(), isTargetConstant(), isTruncateOf(), isVectorAllOnes(), isVectorElementSwap(), isWordAligned(), llvm::PPC::isXXINSERTWMask(), llvm::PPC::isXXPERMDIShuffleMask(), llvm::PPC::isXXSLDWIShuffleMask(), isZeroVector(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), LowerADDRSPACECAST(), LowerANY_EXTEND(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerAtomicArith(), lowerAtomicArithWithLOCK(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorToBitOp(), LowerBuildVectorv4x32(), lowerCallFromStatepointLoweringInfo(), LowerCTPOP(), LowerCTTZ(), lowerDSPIntr(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_VECTOR_ELT_i1(), lowerFCMPIntrinsic(), LowerFPToInt(), lowerICMPIntrinsic(), LowerINSERT_VECTOR_ELT_i1(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), LowerINTRINSIC_W_CHAIN(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerMLOAD(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatImm(), lowerMSASplatZExt(), lowerMSAStoreIntr(), llvm::LanaiTargetLowering::LowerMUL(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerSADDSUBSAT(), LowerShift(), llvm::MSP430TargetLowering::LowerShifts(), lowerShuffleAsBroadcast(), LowerSIGN_EXTEND(), LowerSIGN_EXTEND_Mask(), LowerSVEIntReduction(), LowerSVEIntrinsicEXT(), LowerToHorizontalOp(), LowerTruncateVecI1(), lowerUINT_TO_FP_vXi32(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), lowerX86FPLogicOp(), LowerZERO_EXTEND_Mask(), maskMatters(), llvm::SelectionDAG::matchBinOpReduction(), matchLogicBlend(), matchLSNode(), matchPMADDWD(), mayTailCallThisCC(), mayUseP9Setb(), MergeInputChains(), minMaxOpcToMin3Max3Opc(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowExtractedVectorSelect(), narrowInsertExtractVectorBinOp(), narrowShuffle(), NarrowVector(), nodesHaveSameOperandValue(), numVectorEltsOrZero(), llvm::SDNodeIterator::operator*(), llvm::TargetLowering::parametersInCSRMatch(), ParseBFI(), partitionShuffleOfConcats(), Passv64i1ArgInRegs(), PeepholePPC64ZExtGather(), performADDCombine(), PerformADDCombine(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performAddSubLongCombine(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::performAssertSZExtCombine(), PerformBFICombine(), llvm::SparcTargetLowering::PerformBITCASTCombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), performBRCONDCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCMovFPCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCONDCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), performDSPShiftCombine(), performExtendCombine(), PerformExtendCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFDivCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFpToIntCombine(), performGlobalAddressCombine(), PerformInsertEltCombine(), performIntegerAbsCombine(), performIntrinsicCombine(), PerformIntrinsicCombine(), llvm::AMDGPUTargetLowering::performIntrinsicWOChainCombine(), performIntToFpCombine(), performLD1GatherCombine(), performLDNT1Combine(), performMADD_MSUBCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), performMULCombine(), performMulCombine(), PerformMULCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performMulLoHi24Combine(), performNEONPostLDSTCombine(), performNVCASTCombine(), performORCombine(), PerformORCombine(), PerformORCombine_i1(), PerformORCombineToBFI(), PerformORCombineToSMULWBT(), performPostLD1Combine(), PerformPREDICATE_CASTCombine(), llvm::AMDGPUTargetLowering::performRcpCombine(), PerformREMCombine(), performSELECTCombine(), performSelectCombine(), performSetccAddFolding(), performSETCCCombine(), PerformSETCCCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), PerformSHLSimplify(), performSignExtendInRegCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRACombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSRLCombine(), performST1ScatterCombine(), performSTNT1Combine(), performSTORECombine(), PerformSTORECombine(), PerformSUBCombine(), performSVEAndCombine(), performTBZCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformUMLALCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), performVectorCompareAndMaskUnaryOpCombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), performVSELECTCombine(), performVSelectCombine(), performXORCombine(), performXorCombine(), pickOpcodeForVT(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), reduceVMULWidth(), ReplaceBITCASTResults(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLongIntrinsic(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::HexagonTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), replaceShuffleOfInsert(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), llvm::SelectionDAG::salvageDebugInfo(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), scalarizeExtractedBinop(), llvm::ResourcePriorityQueue::scheduledNode(), SDValueToConstBool(), SearchLoopIntrinsic(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), selectI64Imm(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWChain(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), selectSGPRVectorRegClassID(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HvxSelector::selectShuffle(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HvxSelector::selectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::MipsTargetLowering::shouldFoldConstantShiftPairToMask(), llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), simplifyI24(), simplifyShuffleOfShuffle(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::SelectionDAG::SplitVectorOperand(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), stripModuloOnShift(), stripTruncAndExt(), truncateScalarIntegerArg(), truncateVecElts(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), tryBuildVectorShuffle(), tryCombineCRC32(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryCombineShiftImm(), tryCombineToBSL(), tryCombineToEXTR(), tryConvertSVEWideCompare(), tryFoldToZero(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), tryLowerToSLI(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UnrollVectorOverflowOp(), llvm::X86TargetLowering::unwrapAddress(), llvm::SelectionDAG::UpdateNodeOperands(), useSinCos(), vectorEltWillFoldAway(), VerifySDNode(), visitFMinMax(), visitORCommutative(), widenCtPop(), and WinDBZCheckDenominator().
getOperationName()
std::string SDNode::getOperationName (const SelectionDAG * G = nullptr) const
Return the opcode of this operation for printing.
Definition at line 59 of file SelectionDAGDumper.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDCARRY, llvm::ISD::ADDE, llvm::ISD::ADDROFRETURNADDR, llvm::ISD::ADDRSPACECAST, llvm::ISD::ADJUST_TRAMPOLINE, llvm::ISD::AND, llvm::ISD::ANNOTATION_LABEL, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_FENCE, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_FADD, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BasicBlock, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::ISD::BlockAddress, llvm::ISD::BR, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BRIND, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::ISD::CALLSEQ_END, llvm::ISD::CALLSEQ_START, llvm::ISD::CARRY_FALSE, llvm::ISD::CATCHRET, llvm::ISD::CLEANUPRET, llvm::ISD::CONCAT_VECTORS, llvm::ISD::CONDCODE, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::ConstantPool, llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DEBUGTRAP, llvm::ISD::DELETED_NODE, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_DWARF_CFA, llvm::ISD::EH_LABEL, llvm::ISD::EH_RETURN, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::ISD::EH_SJLJ_SETUP_DISPATCH, llvm::ISD::EntryToken, llvm::ISD::ExternalSymbol, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCBRT, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FGETSIGN, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FRAME_TO_ARGS_OFFSET, llvm::ISD::FRAMEADDR, llvm::ISD::FrameIndex, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::ISD::GC_TRANSITION_END, llvm::ISD::GC_TRANSITION_START, llvm::ISD::GET_DYNAMIC_AREA_OFFSET, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetMachine::getIntrinsicInfo(), getMachineOpcode(), llvm::Intrinsic::getName(), getOpcode(), getOperand(), llvm::SelectionDAG::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::TargetLowering::getTargetNodeName(), llvm::ISD::GLOBAL_OFFSET_TABLE, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::HANDLENODE, llvm::ISD::INIT_TRAMPOLINE, llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, isMachineOpcode(), llvm::ISD::JumpTable, llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, llvm::ISD::LLRINT, llvm::ISD::LLROUND, llvm_unreachable, llvm::ISD::LOAD, llvm::ISD::LOCAL_RECOVER, llvm::ISD::LRINT, llvm::ISD::LROUND, llvm::ISD::MCSymbol, llvm::ISD::MDNODE_SDNODE, llvm::ISD::MERGE_VALUES, llvm::ISD::MGATHER, llvm::ISD::MLOAD, llvm::ISD::MSCATTER, llvm::ISD::MSTORE, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, Name, llvm::None, llvm::ISD::OR, llvm::ISD::PCMARKER, llvm::ISD::PREFETCH, llvm::ISD::READ_REGISTER, llvm::ISD::READCYCLECOUNTER, llvm::ISD::Register, llvm::ISD::RegisterMask, llvm::ISD::RETURNADDR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SADDSAT, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SDIVFIX, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETCCCARRY, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMUL_LOHI, llvm::ISD::SMULFIX, llvm::ISD::SMULFIXSAT, llvm::ISD::SMULO, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SPONENTRY, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SRCVALUE, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::ISD::SSUBSAT, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FCEIL, llvm::ISD::STRICT_FCOS, llvm::ISD::STRICT_FDIV, llvm::ISD::STRICT_FEXP, llvm::ISD::STRICT_FEXP2, llvm::ISD::STRICT_FFLOOR, llvm::ISD::STRICT_FLOG, llvm::ISD::STRICT_FLOG10, llvm::ISD::STRICT_FLOG2, llvm::ISD::STRICT_FMA, llvm::ISD::STRICT_FMAXIMUM, llvm::ISD::STRICT_FMAXNUM, llvm::ISD::STRICT_FMINIMUM, llvm::ISD::STRICT_FMINNUM, llvm::ISD::STRICT_FMUL, llvm::ISD::STRICT_FNEARBYINT, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, llvm::ISD::STRICT_FPOW, llvm::ISD::STRICT_FPOWI, llvm::ISD::STRICT_FREM, llvm::ISD::STRICT_FRINT, llvm::ISD::STRICT_FROUND, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::STRICT_FSIN, llvm::ISD::STRICT_FSQRT, llvm::ISD::STRICT_FSUB, llvm::ISD::STRICT_FTRUNC, llvm::ISD::STRICT_LLRINT, llvm::ISD::STRICT_LLROUND, llvm::ISD::STRICT_LRINT, llvm::ISD::STRICT_LROUND, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::STRICT_UINT_TO_FP, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBCARRY, llvm::ISD::SUBE, llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstant, llvm::ISD::TargetConstantFP, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetFrameIndex, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetIndex, llvm::ISD::TargetJumpTable, TII, llvm::ISD::TokenFactor, llvm::ISD::TRAP, llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UADDSAT, llvm::ISD::UDIV, llvm::ISD::UDIVFIX, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMUL_LOHI, llvm::ISD::UMULFIX, llvm::ISD::UMULFIXSAT, llvm::ISD::UMULO, llvm::ISD::UNDEF, llvm::ISD::UREM, llvm::ISD::USUBO, llvm::ISD::USUBSAT, llvm::utostr(), llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VALUETYPE, llvm::ISD::VASTART, llvm::ISD::VECREDUCE_ADD, llvm::ISD::VECREDUCE_AND, llvm::ISD::VECREDUCE_FADD, llvm::ISD::VECREDUCE_FMAX, llvm::ISD::VECREDUCE_FMIN, llvm::ISD::VECREDUCE_FMUL, llvm::ISD::VECREDUCE_MUL, llvm::ISD::VECREDUCE_OR, llvm::ISD::VECREDUCE_SMAX, llvm::ISD::VECREDUCE_SMIN, llvm::ISD::VECREDUCE_STRICT_FADD, llvm::ISD::VECREDUCE_STRICT_FMUL, llvm::ISD::VECREDUCE_UMAX, llvm::ISD::VECREDUCE_UMIN, llvm::ISD::VECREDUCE_XOR, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::WRITE_REGISTER, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
getSDVTList()
static SDVTList llvm::SDNode::getSDVTList (EVT VT) inline static protected
Definition at line 1087 of file SelectionDAGNodes.h.
References llvm::MipsISD::Ret.
getSimpleValueType()
MVT llvm::SDNode::getSimpleValueType (unsigned ResNo) const inline
Return the type of a specified result as a simple type.
Definition at line 1007 of file SelectionDAGNodes.h.
Referenced by llvm::ScheduleDAGSDNodes::RegDefIter::Advance(), llvm::AVRDAGToDAGISel::select< ISD::BRIND >(), CalcNodeSethiUllmanNumber(), callingConvSupported(), canClobberPhysRegDefs(), canonicalizeBitSelect(), CheckForPhysRegDependency(), checkV64LaneV128(), combineADC(), combineAndnp(), combineANDXORWithAllOnesIntoANDNP(), combineBasicSADPattern(), combineCompareEqual(), combineExtractSubvector(), combineInsertSubvector(), combineMOVMSK(), combineOrCmpEqZeroToCtlzSrl(), combineSBB(), combineShuffleToAddSubOrFMAddSub(), combineShuffleToFMAddSub(), combineVectorCompare(), EmitAVX512Test(), getHopForBuildVector(), getIntOperandFromRegisterString(), getPhysicalRegisterVT(), getPromotedVectorElementType(), getVPTESTMOpc(), isAddSubOrSubAdd(), isCalleeLoad(), isHopBuildVector(), isOperandOf(), isSinCosLibcallAvailable(), isSplatZeroExtended(), isSubBorrowChain(), LowerADDSUBCARRY(), lowerAtomicArith(), lowerAtomicArithWithLOCK(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), LowerEXTEND_VECTOR_INREG(), lowerINT_TO_FP_vXi64(), LowerSIGN_EXTEND(), LowerSIGN_EXTEND_Mask(), lowerToAddSubOrFMAddSub(), LowerToHorizontalOp(), LowerTruncateVecI1(), lowerUINT_TO_FP_vec(), lowerUINT_TO_FP_vXi32(), LowerVSETCC(), lowerX86FPLogicOp(), LowerZERO_EXTEND_Mask(), mayUseP9Setb(), narrowExtractedVectorSelect(), narrowShuffle(), performAddSubLongCombine(), llvm::SparcTargetLowering::PerformBITCASTCombine(), performFDivCombine(), performFpToIntCombine(), PerformVCVTCombine(), PerformVDIVCombine(), pickOpcodeForVT(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::ResourcePriorityQueue::scheduledNode(), ShrinkLoadReplaceStoreWithStore(), tryCombineShiftImm(), and useSinCos().
getValueSizeInBits()
TypeSize llvm::SDNode::getValueSizeInBits (unsigned ResNo) const inline
Returns MVT::getSizeInBits(getValueType(ResNo)).
If the value type is a scalable vector type, the scalable property will be set and the runtime size will be a positive integer multiple of the base size.
Definition at line 1016 of file SelectionDAGNodes.h.
Referenced by generateEquivalentSub(), llvm::isAllOnesOrAllOnesSplat(), llvm::isOneOrOneSplat(), isSlicingProfitable(), and numVectorEltsOrZero().
getValueType()
EVT llvm::SDNode::getValueType (unsigned ResNo) const inline
Return the type of a specified result.
Definition at line 1001 of file SelectionDAGNodes.h.
References assert().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), AddGlue(), llvm::MipsSETargetLowering::addMSAFloatType(), AddNodeIDCustom(), addShuffleForVecExtend(), adjustForSubtraction(), adjustLoadValueTypeImpl(), llvm::AMDGPUTargetLowering::allUsesHaveSourceMods(), llvm::SelectionDAG::areNonVolatileConsecutiveLoads(), BuildExactSDIV(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), callingConvSupported(), CanCombineFCOPYSIGN_EXTEND_ROUND(), canLowerToLDG(), checkV64LaneV128(), CollectOpsToWiden(), combineAcrossLanesIntrinsic(), combineADC(), combineAdd(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineAnd(), combineAndMaskToShift(), CombineANDShift(), CombineBaseUpdate(), combineBEXTR(), combineBitcast(), combineBVOfConsecutiveLoads(), combineBVOfVecSExt(), combineCastedMaskArithmetic(), combineCCMask(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectors(), combineCVTP2I_CVTTP2I(), combineExtInVec(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineExtSetcc(), combineFaddFsub(), combineFAndFNotToFAndn(), combineFMA(), combineFMADDSUB(), combineFMinFMax(), combineFMinNumFMaxNum(), combineFneg(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), combineKSHIFT(), combineLoad(), combineLogicBlendIntoPBLENDV(), combineLoopMAddPattern(), combineLoopSADPattern(), combineMaskedLoadConstantMask(), combineMul(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combineOrCmpEqZeroToCtlzSrl(), combineOrShiftToFunnelShift(), combineParity(), combinePMULDQ(), combineReductionToHorizontal(), combineScalarAndWithMaskSetcc(), combineScalarToVector(), combineSelectAndUse(), combineSetCC(), combineSext(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineShuffle(), combineShuffleOfConcatUndef(), combineShuffleOfScalars(), combineShuffleToVectorExtend(), combineSignExtendInReg(), combineSIntToFP(), combineSub(), combineSubToSubus(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), combineToFPTruncExtElt(), combineTruncate(), combineTruncatedArithmetic(), combineTruncationShuffle(), combineUIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVectorInsert(), combineVectorPack(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncation(), combineVectorTruncationWithPACKSS(), combineVectorTruncationWithPACKUS(), CombineVLDDUP(), CombineVMOVDRRCandidateWithVecOp(), combineVTRUNC(), combineX86AddSub(), combineX86INT_TO_FP(), combineXor(), combineZext(), convertIntLogicToFPLogic(), createBSWAPShuffleMask(), createLoadLR(), llvm::createR600ISelDag(), doNotCSE(), earlyExpandDIVFIX(), EmitCmp(), llvm::InstrEmitter::EmitDbgLabel(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), Expand64BitShift(), llvm::TargetLowering::expandABS(), ExpandBITCAST(), ExpandBVWithShuffles(), llvm::TargetLowering::expandMUL(), ExpandREAD_REGISTER(), llvm::TargetLowering::expandUnalignedLoad(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), extractBooleanFlip(), foldBitcastedFPLogic(), llvm::SelectionDAG::FoldConstantArithmetic(), foldExtendedSignBitTest(), foldFPToIntToFP(), FoldIntToFPToInt(), foldShuffleOfConcatUndefs(), foldShuffleOfHorizOp(), foldVectorXorShiftIntoCmp(), foldXorTruncShiftIntoCmp(), fp16SrcZerosHighBits(), generateEquivalentSub(), GeneratePerfectShuffle(), getAArch64XALUOOp(), getAL(), getARMIndexedAddressParts(), getAsCarry(), getCombineLoadStoreParts(), llvm::SelectionDAG::getCommutedVectorShuffle(), getContiguousRangeOfSetBits(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), GetFPLibCall(), getIPMConversion(), getLoadExtOrTrunc(), getMad64_32(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedScatter(), getMOVL(), getMVEIndexedAddressParts(), getOneTrueElt(), getPermuteMask(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), getPromotedVectorElementType(), GetPromotionOpcode(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::AVRTargetLowering::getSetCCResultType(), getShiftAmountTyForConstant(), getSPDenormModeValue(), getSplatConstantFP(), getT2IndexedAddressParts(), getTestBitOperand(), GetTLSADDR(), getVPTESTMOpc(), gwsIntrinToOpcode(), hasNormalLoadOperand(), haveEfficientBuildVectorPattern(), isADDADDMUL(), isAddSubOrSubAdd(), isAllConstantBuildVector(), isBitfieldExtractOp(), isBitfieldExtractOpFromAnd(), isBitfieldExtractOpFromSExtInReg(), isBitfieldExtractOpFromShr(), isBSwapHWordPair(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), isCalleeLoad(), isClampZeroToOne(), isConditionalZeroOrAllOnes(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::ISD::isConstantSplatVector(), llvm::TargetLowering::isConstFalseVal(), llvm::isConstOrConstSplat(), llvm::TargetLowering::isConstTrueVal(), isContractable(), llvm::AArch64TargetLowering::isDesirableToCommuteWithShift(), isExtendedBUILD_VECTOR(), llvm::TargetLowering::isExtendedTrueVal(), isFloatingPointZero(), llvm::SITargetLowering::isFMADLegalForFAddFSub(), llvm::TargetLoweringBase::isFMADLegalForFAddFSub(), isFNEG(), isFPExtLoad(), isHorizontalBinOpPart(), isInt32Immediate(), isInt64Immediate(), llvm::isIntS16Immediate(), llvm::SelectionDAGISel::IsLegalToFold(), isMemOPCandidate(), isOpcWithIntImmediate(), isPerfectIncrement(), llvm::PPC::isQVALIGNIShuffleMask(), isSeveralBitsExtractOpFromShr(), isSlicingProfitable(), llvm::PPC::isSplatShuffleMask(), isSubBorrowChain(), isTargetConstant(), isVectorElementSwap(), isVMerge(), llvm::PPC::isVSLDOIShuffleMask(), IsVUZPShuffleNode(), isWordAligned(), isXXBRShuffleMaskHelper(), llvm::PPC::isXXPERMDIShuffleMask(), llvm::PPC::isXXSLDWIShuffleMask(), LowerADDSUBCARRY(), llvm::TargetLowering::LowerAsmOperandForConstraint(), LowerCONCAT_VECTORS(), LowerCTPOP(), LowerCTTZ(), lowerDSPIntr(), LowerDYNAMIC_STACKALLOC(), LowerEXTRACT_VECTOR_ELT_SSE4(), lowerFCMPIntrinsic(), lowerICMPIntrinsic(), LowerINTRINSIC_W_CHAIN(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatImm(), lowerMSASplatZExt(), lowerMSAStoreIntr(), llvm::LanaiTargetLowering::LowerMUL(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerShift(), llvm::MipsTargetLowering::lowerSTORE(), LowerSVEIntReduction(), LowerSVEIntrinsicEXT(), LowerToTLSExecModel(), LowerToTLSLocalDynamicModel(), LowerTruncateVectorStore(), LowerXOR(), maskMatters(), mayTailCallThisCC(), mayUseP9Setb(), MergeInputChains(), minMaxOpcToMin3Max3Opc(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowInsertExtractVectorBinOp(), narrowShuffle(), NarrowVector(), narrowVectorSelect(), numVectorEltsOrZero(), partitionShuffleOfConcats(), PerformABSCombine(), performADDCombine(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::performAssertSZExtCombine(), PerformBFICombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), performConcatVectorsCombine(), performCONDCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), performExtendCombine(), PerformExtendCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFpToIntCombine(), PerformInsertEltCombine(), performIntegerAbsCombine(), performIntrinsicCombine(), PerformIntrinsicCombine(), performIntToFpCombine(), performLD1GatherCombine(), performLDNT1Combine(), PerformLOADCombine(), performMADD_MSUBCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), performMULCombine(), performMulCombine(), PerformMULCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), performNEONPostLDSTCombine(), performNVCASTCombine(), performORCombine(), PerformORCombine(), PerformORCombine_i1(), PerformORCombineToBFI(), performPostLD1Combine(), PerformPREDICATE_CASTCombine(), llvm::AMDGPUTargetLowering::performRcpCombine(), PerformREMCombine(), performSelectCombine(), performSetccAddFolding(), performSETCCCombine(), PerformSETCCCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), performSignExtendInRegCombine(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRACombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSRLCombine(), performST1ScatterCombine(), performSUBCombine(), PerformSUBCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), performVectorCompareAndMaskUnaryOpCombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), performVSELECTCombine(), performVSelectCombine(), performXORCombine(), performXorCombine(), PerformXORCombine(), pickOpcodeForVT(), print_types(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), reduceMaskedLoadToScalarLoad(), RemoveUnusedGlue(), ReorganizeVector(), llvm::SelectionDAG::ReplaceAllUsesWith(), ReplaceBITCASTResults(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::HexagonTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), resolveBuildVector(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), scalarizeExtractedBinop(), llvm::TargetLowering::scalarizeVectorLoad(), SDValueToConstBool(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), selectI64Imm(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), selectSGPRVectorRegClassID(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HvxSelector::selectShuffle(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HvxSelector::selectVAlign(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask(), llvm::AMDGPUTargetLowering::shouldReduceLoadWidth(), llvm::X86TargetLowering::shouldReduceLoadWidth(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), simplifyShuffleOfShuffle(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), stripModuloOnShift(), stripTruncAndExt(), truncateVecElts(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), tryBuildVectorShuffle(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryCombineShiftImm(), tryCombineToBSL(), tryCombineToEXTR(), tryConvertSVEWideCompare(), tryFoldToZero(), tryLowerToSLI(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), tryToFoldExtOfMaskedLoad(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UnrollVectorOverflowOp(), useSinCos(), vectorEltWillFoldAway(), VerifySDNode(), visitFMinMax(), widenCtPop(), and WinDBZCheckDenominator().
getVTList()
SDVTList llvm::SDNode::getVTList () const inline
Definition at line 966 of file SelectionDAGNodes.h.
References X.
Referenced by AddNodeIDNode(), adjustLoadValueTypeImpl(), combineADDCARRYDiamond(), combineAddOrSubToADCOrSBB(), combineCarryDiamond(), combineCarryThroughADD(), combineSBB(), llvm::createR600ISelDag(), emitIntrinsicWithCC(), extractBooleanFlip(), foldAddSubMasked1(), getBufferOffsetForMMO(), getCCResult(), getContiguousRangeOfSetBits(), getSPDenormModeValue(), gwsIntrinToOpcode(), isOpcWithIntImmediate(), isPerfectIncrement(), isSubBorrowChain(), llvm::HexagonTargetLowering::LowerAddSubCarry(), LowerADDSUBCARRY(), lowerAtomicArith(), LowerCMP_SWAP(), LowerINTRINSIC_W_CHAIN(), llvm::HexagonTargetLowering::LowerUAddSubO(), MergeInputChains(), parseTexFail(), PeepholePPC64ZExtGather(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performANDCombine(), llvm::R600TargetLowering::PerformDAGCombine(), performSRACombine(), pickOpcodeForVT(), SDValueToConstBool(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), selectSGPRVectorRegClassID(), llvm::SITargetLowering::shouldEmitPCReloc(), simplifyDivRem(), simplifyI24(), tryFoldToZero(), llvm::SelectionDAG::UnrollVectorOverflowOp(), and VerifySDNode().
hasAnyUseOfValue()
bool SDNode::hasAnyUseOfValue (unsigned Value) const
Return true if there are any use of the indicated value.
hasAnyUseOfValue - Return true if there are any use of the indicated value.
This method ignores uses of other values defined by this operation.
Definition at line 9049 of file SelectionDAG.cpp.
References assert(), E, getNumValues(), use_begin(), and use_end().
Referenced by AddCombineTo64bitMLAL(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::ScheduleDAGSDNodes::RegDefIter::Advance(), llvm::AVRDAGToDAGISel::select< ISD::BRIND >(), CalcNodeSethiUllmanNumber(), canClobberPhysRegDefs(), checkBoolTestSetCCCombine(), combineCarryDiamond(), combineSBB(), combineSetCCAtomicArith(), combineX86AddSub(), llvm::InstrEmitter::EmitDbgLabel(), extractBooleanFlip(), foldAddSubMasked1(), isCalleeLoad(), lowerAtomicArith(), llvm::SelectionDAG::makeEquivalentMemoryOrdering(), numVectorEltsOrZero(), performDivRemCombine(), RemoveUnusedGlue(), llvm::SelectionDAG::ReplaceAllUsesWith(), scalarizeBinOpOfSplats(), simplifyDivRem(), and tryFoldToZero().
hasNUsesOfValue()
bool SDNode::hasNUsesOfValue (unsigned NUses, unsigned Value) const
Return true if there are exactly NUSES uses of the indicated value.
hasNUsesOfValue - Return true if there are exactly NUSES uses of the indicated value.
This method ignores uses of other values defined by this operation.
Definition at line 9031 of file SelectionDAG.cpp.
References assert(), E, getNumValues(), use_begin(), and use_end().
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), combineStore(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), getAArch64Cmp(), isFMAddSubOrFMSubAdd(), isFusableLoadOpStorePattern(), LowerInterruptReturn(), Passv64i1ArgInRegs(), performBRCONDCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), and scalarizeExtractedBinop().
hasOneUse()
bool llvm::SDNode::hasOneUse () const inline
Return true if there is exactly one use of this node.
Definition at line 732 of file SelectionDAGNodes.h.
Referenced by bitOpWithConstantIsReducible(), canChangeToInt(), combineAddOrSubToADCOrSBB(), CombineANDShift(), combineCarryThroughADD(), combineMaskedStore(), combineMul(), combineOrCmpEqZeroToCtlzSrl(), combineSelectAndUseCommutative(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineShuffleOfScalars(), combineSub(), llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), emitConjunctionRec(), findMemSDNode(), foldBitcastedFPLogic(), FoldIntToFPToInt(), foldMaskedShiftToBEXTR(), GeneratePerfectShuffle(), getCombineLoadStoreParts(), getContiguousRangeOfSetBits(), llvm::SelectionDAG::GetDemandedBits(), getInputChainForNode(), getSPDenormModeValue(), getSplatConstantFP(), getTestBitOperand(), getVPTESTMOpc(), hasNonFlagsUse(), hasSingleUsesFromRoot(), isAddSubOrSubAdd(), isAddSubSExt(), isAddSubZExt(), isBSwapHWordElement(), isBSwapHWordPair(), isContractable(), isFloatingPointZero(), isFoldableUseOfShuffle(), isHorizontalBinOpPart(), isMemOPCandidate(), isOpcWithIntImmediate(), isPermutation(), isSlicingProfitable(), isTargetConstant(), LowerInterruptReturn(), LowerVectorAllZeroTest(), mayUseP9Setb(), MergeInputChains(), narrowExtractedVectorBinOp(), numVectorEltsOrZero(), PerformADDCombineWithOperands(), PerformARMBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performMulCombine(), PerformShiftCombine(), PerformSTORECombine(), PerformSUBCombine(), PerformVMOVRRDCombine(), llvm::X86TargetLowering::shouldReduceLoadWidth(), llvm::TargetLoweringBase::shouldReduceLoadWidth(), shouldUseLA(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), tryFoldToZero(), visitORCommutative(), widenCtPop(), and zeroExtendToMatch().
hasPredecessor()
bool SDNode::hasPredecessor (const SDNode * N) const
Return true if N is a predecessor of this node.
N is either an operand of this node, or can be reached by recursively traversing up the operands. NOTE: This is an expensive method. Use it carefully.
Definition at line 9146 of file SelectionDAG.cpp.
References hasPredecessorHelper(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by isPredecessorOf().
hasPredecessorHelper()
static bool llvm::SDNode::hasPredecessorHelper (const SDNode * N, SmallPtrSetImpl< const SDNode *> & Visited, SmallVectorImpl< const SDNode *> & Worklist, unsigned int MaxSteps = 0, bool TopologicalPrune = false) inline static
Returns true if N is a predecessor of any node in Worklist.
This helper keeps Visited and Worklist sets externally to allow unions searches to be performed in parallel, caching of results across queries and incremental addition to Worklist. Stops early if N is found but will resume. Remember to clear Visited and Worklists if DAG changes. MaxSteps gives a maximum number of nodes to visit before giving up. The TopologicalPrune flag signals that positive NodeIds are topologically ordered (Operands have strictly smaller node id) and search can be pruned leveraging this.
Definition at line 866 of file SelectionDAGNodes.h.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), getNodeId(), getOpcode(), llvm::SmallPtrSetImpl< PtrType >::insert(), op_values(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallPtrSetImplBase::size(), and llvm::ISD::TokenFactor.
Referenced by CombineBaseUpdate(), findNonImmUse(), getCombineLoadStoreParts(), HandleMergeInputChains(), hasPredecessor(), isFusableLoadOpStorePattern(), performNEONPostLDSTCombine(), performPostLD1Combine(), scalarizeBinOpOfSplats(), and ShrinkLoadReplaceStoreWithStore().
intersectFlagsWith()
void SDNode::intersectFlagsWith (const SDNodeFlags Flags)
Clear any flags in this node that aren't also set in Flags.
If Flags is not in a defined state then this has no effect.
Definition at line 9153 of file SelectionDAG.cpp.
References llvm::SDNodeFlags::intersectWith().
isDivergent()
bool llvm::SDNode::isDivergent () const inline
Definition at line 726 of file SelectionDAGNodes.h.
Referenced by getLoadExtOrTrunc(), getPermuteMask(), gwsIntrinToOpcode(), isClampZeroToOne(), numVectorEltsOrZero(), parseTexFail(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), selectSGPRVectorRegClassID(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::SelectionDAG::updateDivergence(), and llvm::SelectionDAG::VerifyDAGDiverence().
isFast()
bool llvm::SDNode::isFast () inline
Definition at line 991 of file SelectionDAGNodes.h.
References llvm::SDNodeFlags::isFast().
isMachineOpcode()
bool llvm::SDNode::isMachineOpcode () const inline
Test if this node has a post-isel opcode, directly corresponding to a MachineInstr opcode.
Definition at line 713 of file SelectionDAGNodes.h.
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::ARMBaseInstrInfo::areLoadsFromSameBasePtr(), llvm::X86InstrInfo::areLoadsFromSameBasePtr(), llvm::AVRDAGToDAGISel::select< ISD::BRIND >(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), CalcNodeSethiUllmanNumber(), canClobberPhysRegDefs(), CheckForPhysRegDependency(), llvm::MachineSDNode::classof(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), llvm::createR600ISelDag(), llvm::InstrEmitter::EmitNode(), FindCallSeqStart(), getCondFromNode(), getContiguousRangeOfSetBits(), llvm::TargetInstrInfo::getInstrLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), getOperationName(), llvm::ARMTargetLowering::getSchedulingPreference(), getUsefulBitsForUse(), getVPTESTMOpc(), gwsIntrinToOpcode(), isBitfieldExtractOp(), isCalleeLoad(), IsChainDependent(), isPermutation(), IsPredicateKnownToFail(), llvm::ResourcePriorityQueue::isResourceAvailable(), maskMatters(), llvm::SelectionDAGISel::mayRaiseFPException(), mayUseP9Setb(), llvm::ScheduleDAGSDNodes::newSUnit(), PeepholePPC64ZExtGather(), PerformANDCombine(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::ResourcePriorityQueue::regPressureDelta(), llvm::ResourcePriorityQueue::reserveResources(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::HexagonDAGToDAGISel::Select(), llvm::SelectionDAGISel::SelectCodeCommon(), selectSGPRVectorRegClassID(), llvm::X86InstrInfo::unfoldMemoryOperand(), and VerifySDNode().
isMemIntrinsic()
bool llvm::SDNode::isMemIntrinsic () const inline
Test if this node is a memory intrinsic (with valid pointer information).
INTRINSIC_W_CHAIN and INTRINSIC_VOID nodes are sometimes created for non-memory intrinsics (with chains) that are not really instances of MemSDNode. For such nodes, we need some extra state to determine the proper classof relationship.
Definition at line 693 of file SelectionDAGNodes.h.
References llvm::ISD::INTRINSIC_VOID, and llvm::ISD::INTRINSIC_W_CHAIN.
Referenced by llvm::MemSDNode::classof(), and llvm::MemIntrinsicSDNode::classof().
isOnlyUserOf()
bool SDNode::isOnlyUserOf (const SDNode * N) const
Return true if this node is the only use of N.
isOnlyUserOf - Return true if this node is the only use of N.
Definition at line 9060 of file SelectionDAG.cpp.
References E, I, use_begin(), and use_end().
Referenced by combineAnd(), combineLoopMAddPattern(), combineRedundantDWordShuffle(), combineVectorPack(), combineVectorShiftImm(), ExtractBitFromMaskVector(), findNonImmUse(), getFauxShuffleMask(), haveEfficientBuildVectorPattern(), isCalleeLoad(), llvm::ARMTargetLowering::isVectorLoadExtDesirable(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), and simplifyShuffleOfShuffle().
isOperandOf()
bool SDNode::isOperandOf (const SDNode * N) const
Return true if this node is an operand of N.
Definition at line 9093 of file SelectionDAG.cpp.
References llvm::any_of(), llvm::SDValue::getNode(), and op_values().
Referenced by CheckForMaskedLoad().
isPredecessorOf()
bool llvm::SDNode::isPredecessorOf (const SDNode * N) const inline
Return true if this node is a predecessor of N.
NOTE: Implemented on top of hasPredecessor and every bit as expensive. Use carefully.
Definition at line 847 of file SelectionDAGNodes.h.
References hasPredecessor().
Referenced by AddCombineTo64bitMLAL(), llvm::createR600ISelDag(), getCombineLoadStoreParts(), llvm::PPCTargetLowering::getPreIndexedAddressParts(), and scalarizeBinOpOfSplats().
isStrictFPOpcode()
bool llvm::SDNode::isStrictFPOpcode () inline
Test if this node is a strict floating point pseudo-op.
Definition at line 700 of file SelectionDAGNodes.h.
Referenced by combineSIntToFP(), combineUIntToFP(), combineVectorCompareAndMaskUnaryOp(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), createBSWAPShuffleMask(), earlyExpandDIVFIX(), getAArch64XALUOOp(), GetFPLibCall(), getSETCCOperandType(), getShiftAmountTyForConstant(), isCalleeLoad(), isSETCCorConvertedSETCC(), LowerADDRSPACECAST(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerPREFETCH(), LowerTruncateVecI1(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vec(), lowerUINT_TO_FP_vXi32(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), llvm::SelectionDAGISel::mayRaiseFPException(), mayTailCallThisCC(), MergeInputChains(), and llvm::X86TargetLowering::ReplaceNodeResults().
isTargetMemoryOpcode()
bool llvm::SDNode::isTargetMemoryOpcode () const inline
Test if this node has a target-specific memory-referencing opcode (in the <target>ISD namespace and greater than FIRST_TARGET_MEMORY_OPCODE).
Definition at line 681 of file SelectionDAGNodes.h.
References llvm::ISD::FIRST_TARGET_MEMORY_OPCODE.
Referenced by AddNodeIDCustom(), llvm::MemSDNode::classof(), and llvm::MemIntrinsicSDNode::classof().
isTargetOpcode()
bool llvm::SDNode::isTargetOpcode () const inline
Test if this node has a target-specific opcode (in the <target>ISD namespace).
Definition at line 667 of file SelectionDAGNodes.h.
References llvm::ISD::BUILTIN_OP_END.
Referenced by llvm::SelectionDAGISel::mayRaiseFPException().
isTargetStrictFPOpcode()
bool llvm::SDNode::isTargetStrictFPOpcode () const inline
Test if this node has a target-specific opcode that may raise FP exceptions (in the <target>ISD namespace and greater than FIRST_TARGET_STRICTFP_OPCODE).
Note that all target memory opcode are currently automatically considered to possibly raise FP exceptions as well.
Definition at line 674 of file SelectionDAGNodes.h.
References llvm::ISD::FIRST_TARGET_STRICTFP_OPCODE.
Referenced by llvm::SelectionDAGISel::mayRaiseFPException().
isUndef()
bool llvm::SDNode::isUndef () const inline
Return true if the type of the node type undefined.
Definition at line 686 of file SelectionDAGNodes.h.
References llvm::ISD::UNDEF.
Referenced by callingConvSupported(), convertShiftLeftToScale(), llvm::createR600ISelDag(), ExpandHorizontalBinOp(), llvm::SelectionDAG::FoldConstantArithmetic(), GenerateTBL(), getDUPLANEOp(), llvm::BuildVectorSDNode::getSplatValue(), getTargetVShiftByConstNode(), isConstantOrUndef(), isHorizontalBinOpPart(), isSETCCorConvertedSETCC(), LowerToHorizontalOp(), LowerVECTOR_SHUFFLE(), and LowerVECTOR_SHUFFLEv8i8().
op_begin()
op_iterator llvm::SDNode::op_begin () const inline
Definition at line 945 of file SelectionDAGNodes.h.
Referenced by CloneNodeWithValues(), collectConcatOps(), CollectOpsToWiden(), combineBitcast(), combineConcatVectorOfExtracts(), combineConcatVectors(), EmitTest(), foldCONCAT_VECTORS(), generateEquivalentSub(), getAArch64XALUOOp(), getARClassRegisterMask(), getSPDenormModeValue(), llvm::SelectionDAGISel::IsLegalToFold(), LowerADDRSPACECAST(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORAsVariablePermute(), llvm::SelectionDAG::MorphNodeTo(), moveBelowOrigChain(), NarrowVector(), llvm::R600TargetLowering::PerformDAGCombine(), recoverFramePointer(), llvm::SelectionDAG::RemoveDeadNodes(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyShuffleOfShuffle(), llvm::SelectionDAG::UpdateNodeOperands(), and VerifySDNode().
op_end()
op_iterator llvm::SDNode::op_end () const inline
Definition at line 946 of file SelectionDAGNodes.h.
Referenced by CloneNodeWithValues(), collectConcatOps(), CollectOpsToWiden(), combineBitcast(), combineConcatVectorOfExtracts(), combineConcatVectors(), foldCONCAT_VECTORS(), generateEquivalentSub(), getAArch64XALUOOp(), getARClassRegisterMask(), getSPDenormModeValue(), llvm::SelectionDAGISel::IsLegalToFold(), LowerADDRSPACECAST(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerBUILD_VECTOR_i1(), llvm::SelectionDAG::MorphNodeTo(), moveBelowOrigChain(), llvm::R600TargetLowering::PerformDAGCombine(), recoverFramePointer(), llvm::SelectionDAG::RemoveDeadNodes(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyShuffleOfShuffle(), and VerifySDNode().
op_values()
iterator_range<value_op_iterator> llvm::SDNode::op_values () const inline
Definition at line 961 of file SelectionDAGNodes.h.
References llvm::make_range().
Referenced by llvm::ISD::allOperandsUndef(), callingConvSupported(), checkForCyclesHelper(), FindCallSeqStart(), findMatchingInlineAsmOperand(), findMemSDNode(), findNonImmUse(), foldBitcastedFPLogic(), getInputChainForNode(), llvm::TargetLowering::getNegatedExpression(), getNodeRegMask(), getUnderlyingArgRegs(), HandleMergeInputChains(), hasPredecessorHelper(), llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::isBuildVectorOfConstantFPSDNodes(), llvm::ISD::isBuildVectorOfConstantSDNodes(), IsChainDependent(), llvm::BuildVectorSDNode::isConstant(), isConstantOrConstantVector(), isExtendedBUILD_VECTOR(), llvm::TargetLowering::isNegatibleForFree(), llvm::SDValue::isOperandOf(), isOperandOf(), isOperandOf(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerToHorizontalOp(), llvm::TargetLowering::SimplifyDemandedVectorElts(), and simplifyDivRem().
ops()
ArrayRef<SDUse> llvm::SDNode::ops () const inline
Definition at line 947 of file SelectionDAGNodes.h.
References llvm::makeArrayRef().
Referenced by AddNodeIDNode(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineExtractSubvector(), combineFneg(), combineStore(), llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), detectAVGPattern(), extractSubVector(), findConsecutiveLoad(), isFusableLoadOpStorePattern(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), LowerAVXCONCAT_VECTORS(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorToBitOp(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), mayUseP9Setb(), narrowExtractedVectorLoad(), NormalizeBuildVector(), PeepholePPC64ZExtGather(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), tryExtendDUPToExtractHigh(), llvm::SelectionDAG::updateDivergence(), and llvm::SelectionDAG::VerifyDAGDiverence().
print()
void SDNode::print (raw_ostream & OS, const SelectionDAG * G = nullptr) const
Definition at line 973 of file SelectionDAGDumper.cpp.
Referenced by dump(), fail(), llvm::AMDGPUTargetLowering::LowerOperation(), and llvm::BaseIndexOffset::print().
print_details()
void SDNode::print_details (raw_ostream & OS, const SelectionDAG * G) const
Definition at line 519 of file SelectionDAGDumper.cpp.
References llvm::numbers::e, getFlags(), hasNoSignedWrap(), hasNoUnsignedWrap(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), and printMemOperand().
print_types()
void SDNode::print_types (raw_ostream & OS, const SelectionDAG * G) const
Definition at line 509 of file SelectionDAGDumper.cpp.
References llvm::numbers::e, llvm::EVT::getEVTString(), getNumValues(), getValueType(), and llvm::MVT::Other.
printr()
void SDNode::printr (raw_ostream & OS, const SelectionDAG * G = nullptr) const
Definition at line 863 of file SelectionDAGDumper.cpp.
printrFull()
void SDNode::printrFull (raw_ostream & O, const SelectionDAG * G = nullptr) const
Print a SelectionDAG node and all children down to the leaves.
The given SelectionDAG allows target-specific nodes to be printed in human-readable form. Unlike printr, this will print the whole DAG, including children that appear multiple times.
Definition at line 956 of file SelectionDAGDumper.cpp.
Referenced by llvm::SelectionDAGISel::isOrEquivalentToAdd().
printrWithDepth()
void SDNode::printrWithDepth (raw_ostream & O, const SelectionDAG * G = nullptr, unsigned depth = 100) const
Print a SelectionDAG node and children up to depth "depth." The given SelectionDAG allows target-specific nodes to be printed in human-readable form.
Unlike printr, this will print children that appear multiple times wherever they are used.
Definition at line 951 of file SelectionDAGDumper.cpp.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
Profile()
void SDNode::Profile (FoldingSetNodeID & ID) const
Gather unique data for the node.
Profile - Gather unique data for the node.
Definition at line 8993 of file SelectionDAG.cpp.
References AddNodeIDNode(), and llvm::MVT::LAST_VALUETYPE.
setDebugLoc()
void llvm::SDNode::setDebugLoc (DebugLoc dl) inline
Set source location info.
Try to avoid this, putting it in the constructor is preferable.
Definition at line 757 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAGBuilder::getNonRegisterValue(), llvm::SelectionDAG::SelectNodeTo(), and llvm::SelectionDAG::shouldOptForSize().
setFlags()
void llvm::SDNode::setFlags (SDNodeFlags NewFlags) inline
Definition at line 990 of file SelectionDAGNodes.h.
Referenced by getAsNonOpaqueConstant(), llvm::SelectionDAG::getNode(), getPromotedVectorElementType(), isCalleeLoad(), scalarizeBinOpOfSplats(), and llvm::SelectionDAGISel::SelectCodeCommon().
setHasDebugValue()
void llvm::SDNode::setHasDebugValue (bool b) inline
Definition at line 724 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::AddDbgValue().
setIROrder()
void llvm::SDNode::setIROrder (unsigned Order) inline
Set the node ordering.
Definition at line 750 of file SelectionDAGNodes.h.
Referenced by llvm::NVPTXTargetLowering::LowerFormalArguments(), and llvm::SelectionDAG::SelectNodeTo().
setNodeId()
void llvm::SDNode::setNodeId (int Id) inline
Set unique node id.
Definition at line 744 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::AssignTopologicalOrder(), llvm::AVRDAGToDAGISel::select< ISD::BRIND >(), getARClassRegisterMask(), getContiguousRangeOfSetBits(), getVPTESTMOpc(), insertDAGNode(), llvm::SelectionDAGISel::InvalidateNodeId(), llvm::SelectionDAGISel::IsLegalToFold(), isOperandOf(), mayUseP9Setb(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::Select(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::SelectionDAG::SelectNodeTo(), and selectSGPRVectorRegClassID().
use_begin()
use_iterator llvm::SDNode::use_begin () const inline
Provide iteration support to walk over all uses of an SDNode.
Definition at line 817 of file SelectionDAGNodes.h.
Referenced by llvm::AMDGPUTargetLowering::addTokenForArgument(), adjustForLTGFR(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), allUsesTruncate(), areOnlyUsersOf(), CombineBaseUpdate(), combineCompareEqual(), combineMul(), combineShiftOfShiftedLogic(), CombineVLDDUP(), ExpandBITCAST(), ExtendUsesToFormExtLoad(), findConsecutiveLoad(), findGlueUse(), findUser(), FoldIntToFPToInt(), generateEquivalentSub(), getCombineLoadStoreParts(), getCondFromNode(), getInputChainForNode(), gwsIntrinToOpcode(), hasAnyUseOfValue(), hasNonFlagsUse(), hasNUsesOfValue(), hasSingleUsesFromRoot(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isMemOPCandidate(), isOnlyUserOf(), isPermutation(), isSlicingProfitable(), isTargetConstant(), llvm::ARMTargetLowering::isVectorLoadExtDesirable(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerInterruptReturn(), MayFoldIntoStore(), MayFoldIntoZeroExtend(), mayTailCallThisCC(), mayUseCarryFlag(), needCarryOrOverflowFlag(), numVectorEltsOrZero(), onlyZeroFlagUsed(), Passv64i1ArgInRegs(), PerformADDCombineWithOperands(), PerformARMBUILD_VECTORCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performMulCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::PPCTargetLowering::SelectAddressEVXRegReg(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::X86TargetLowering::shouldReduceLoadWidth(), ShrinkLoadReplaceStoreWithStore(), truncateScalarIntegerArg(), usePartialVectorLoads(), useSinCos(), and widenCtPop().
use_empty()
bool llvm::SDNode::use_empty () const inline
Return true if there are no uses of this node.
Definition at line 729 of file SelectionDAGNodes.h.
Referenced by llvm::createR600ISelDag(), llvm::SelectionDAG::DeleteNode(), getInputChainForNode(), getIPMConversion(), GetVBR(), isCalleeLoad(), llvm::ARMTargetLowering::isVectorLoadExtDesirable(), llvm::SelectionDAG::Legalize(), LowerUMULO_SMULO(), llvm::SelectionDAG::MorphNodeTo(), numVectorEltsOrZero(), PeepholePPC64ZExtGather(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::SelectionDAGISel::SelectCodeCommon(), ShrinkLoadReplaceStoreWithStore(), and tryToFoldExtOfExtload().
use_end()
static use_iterator llvm::SDNode::use_end () inline static
Definition at line 821 of file SelectionDAGNodes.h.
Referenced by llvm::AMDGPUTargetLowering::addTokenForArgument(), adjustForLTGFR(), allUsesTruncate(), areOnlyUsersOf(), CombineBaseUpdate(), combineCompareEqual(), CombineVLDDUP(), ExtendUsesToFormExtLoad(), findConsecutiveLoad(), findGlueUse(), findUser(), generateEquivalentSub(), getCombineLoadStoreParts(), getCondFromNode(), gwsIntrinToOpcode(), hasAnyUseOfValue(), hasNonFlagsUse(), hasNUsesOfValue(), isOnlyUserOf(), isSlicingProfitable(), LowerInterruptReturn(), mayTailCallThisCC(), mayUseCarryFlag(), needCarryOrOverflowFlag(), onlyZeroFlagUsed(), Passv64i1ArgInRegs(), PerformADDCombineWithOperands(), llvm::PPCTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::PPCTargetLowering::SelectAddressEVXRegReg(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::X86TargetLowering::shouldReduceLoadWidth(), ShrinkLoadReplaceStoreWithStore(), truncateScalarIntegerArg(), usePartialVectorLoads(), and useSinCos().
use_size()
size_t llvm::SDNode::use_size () const inline
Return the number of uses of this node.
This method takes time proportional to the number of uses.
Definition at line 738 of file SelectionDAGNodes.h.
Referenced by ExpandBITCAST(), isContractable(), and isTargetConstant().
uses() [1/2]
iterator_range<use_iterator> llvm::SDNode::uses () inline
Definition at line 823 of file SelectionDAGNodes.h.
References llvm::make_range().
Referenced by llvm::AMDGPUTargetLowering::allUsesHaveSourceMods(), combineExtractVectorElt(), combineTargetShuffle(), getCombineLoadStoreParts(), getPTXCmpMode(), getVectorCompareInfo(), hasVolatileUser(), isFoldableUseOfShuffle(), isProfitableToUseFlagOp(), isWorthFoldingADDlow(), LowerFABSorFNEG(), MergeInputChains(), PeepholePPC64ZExtGather(), performGlobalAddressCombine(), PerformREMCombine(), PerformSHLSimplify(), promoteExtBeforeAdd(), scalarizeExtractedBinop(), selectI64Imm(), ShrinkLoadReplaceStoreWithStore(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), and llvm::SelectionDAG::updateDivergence().
uses() [2/2]
iterator_range<use_iterator> llvm::SDNode::uses () const inline
Definition at line 826 of file SelectionDAGNodes.h.
References isOperandOf(), llvm::make_range(), and N.
value_begin()
value_iterator llvm::SDNode::value_begin () const inline
Definition at line 1022 of file SelectionDAGNodes.h.
Referenced by AddGlue(), lowerDSPIntr(), parseTexFail(), RemoveUnusedGlue(), and llvm::SITargetLowering::shouldEmitPCReloc().
value_end()
value_iterator llvm::SDNode::value_end () const inline
Definition at line 1023 of file SelectionDAGNodes.h.
References llvm::dump(), G, llvm::RISCVFenceField::O, and print().
Referenced by AddGlue(), lowerDSPIntr(), parseTexFail(), and llvm::SITargetLowering::shouldEmitPCReloc().
Friends And Related Function Documentation
HandleSDNode
friend class HandleSDNode friend
Definition at line 616 of file SelectionDAGNodes.h.
SelectionDAG
friend class SelectionDAG friend
Definition at line 606 of file SelectionDAGNodes.h.
Member Data Documentation
@187
union { ... }
ConstantSDNodeBits
ConstantSDNodeBitfields llvm::SDNode::ConstantSDNodeBits
Definition at line 593 of file SelectionDAGNodes.h.
LoadSDNodeBits
LoadSDNodeBitfields llvm::SDNode::LoadSDNodeBits
Definition at line 596 of file SelectionDAGNodes.h.
LSBaseSDNodeBits
LSBaseSDNodeBitfields llvm::SDNode::LSBaseSDNodeBits
Definition at line 595 of file SelectionDAGNodes.h.
MemSDNodeBits
MemSDNodeBitfields llvm::SDNode::MemSDNodeBits
Definition at line 594 of file SelectionDAGNodes.h.
Referenced by llvm::MemSDNode::MemSDNode().
PersistentId
uint16_t llvm::SDNode::PersistentId
Unique and persistent id per SDNode in the DAG.
Used for debug printing.
Definition at line 653 of file SelectionDAGNodes.h.
Referenced by PrintNodeId(), and VerifySDNode().
RawSDNodeBits
char llvm::SDNode::RawSDNodeBits[sizeof(uint16_t)]
Definition at line 591 of file SelectionDAGNodes.h.
SDNodeBits
SDNodeBitfields llvm::SDNode::SDNodeBits
Definition at line 592 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::isConstantFPBuildVectorOrConstantFP(), and llvm::SelectionDAG::updateDivergence().
StoreSDNodeBits
StoreSDNodeBitfields llvm::SDNode::StoreSDNodeBits
Definition at line 597 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAGNodes.h
lib/CodeGen/SelectionDAG/SelectionDAG.cpp
lib/CodeGen/SelectionDAG/SelectionDAGDumper.cpp