LLVM: llvm::UnreachableBlockElimPass Class Reference
llvm::UnreachableBlockElimPass Class Reference
#include "llvm/CodeGen/UnreachableBlockElim.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< UnreachableBlockElimPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 29 of file UnreachableBlockElim.h.
Member Function Documentation
run()
PreservedAnalyses UnreachableBlockElimPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 70 of file UnreachableBlockElim.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::PreservedAnalyses::all(), assert(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::SmallPtrSetImpl< NodeRef >::count(), llvm::depth_first_ext(), llvm::numbers::e, E, llvm::EliminateUnreachableBlocks(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::Function::eraseFromParent(), llvm::MachineDominatorTree::eraseNode(), F(), llvm::MCInstrInfo::get(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineDominatorTree::getNode(), getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::getRegState(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineInstr::IgnoreBundle, INITIALIZE_PASS(), llvm::MachineOperand::isUndef(), MRI, llvm::numbers::phi, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), llvm::PreservedAnalyses::preserve(), llvm::MachineBasicBlock::removeSuccessor(), llvm::MachineFunction::RenumberBlocks(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), TII, and llvm::UnreachableMachineBlockElimID.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/UnreachableBlockElim.h
lib/CodeGen/UnreachableBlockElim.cpp