LLVM: llvm::opt::ArgList Class Reference
llvm::opt::ArgList Class Reference abstract
ArgList - Ordered collection of driver arguments.
#include "llvm/Option/ArgList.h"
Public Types
using arglist_type = SmallVector< Arg *, 16 >
using iterator = arg_iterator< arglist_type::iterator >
using const_iterator = arg_iterator< arglist_type::const_iterator >
using reverse_iterator = arg_iterator< arglist_type::reverse_iterator >
using const_reverse_iterator = arg_iterator< arglist_type::const_reverse_iterator >
template<unsigned N>
using filtered_iterator = arg_iterator< arglist_type::const_iterator, N >
template<unsigned N>
using filtered_reverse_iterator = arg_iterator< arglist_type::const_reverse_iterator, N >
Public Member Functions
Arg Access
void append (Arg *A)
append - Append A to the arg list.
const arglist_type & getArgs () const
unsigned size () const
template<typename ... OptSpecifiers>
bool hasArgNoClaim (OptSpecifiers ...Ids) const
hasArg - Does the arg list contain any option matching Id.
template<typename ... OptSpecifiers>
bool hasArg (OptSpecifiers ...Ids) const
template<typename ... OptSpecifiers>
Arg * getLastArg (OptSpecifiers ...Ids) const
Return the last argument matching Id, or null.
template<typename ... OptSpecifiers>
Arg * getLastArgNoClaim (OptSpecifiers ...Ids) const
Return the last argument matching Id, or null.
virtual const char * getArgString (unsigned Index) const =0
getArgString - Return the input argument string at Index.
virtual unsigned getNumInputArgStrings () const =0
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Arg Iteration
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
template<typename ... OptSpecifiers>
iterator_range< filtered_iterator< sizeof...(OptSpecifiers)> > filtered (OptSpecifiers ...Ids) const
template<typename ... OptSpecifiers>
iterator_range< filtered_reverse_iterator< sizeof...(OptSpecifiers)> > filtered_reverse (OptSpecifiers ...Ids) const
Arg Removal
void eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
Argument Lookup Utilities
StringRef getLastArgValue (OptSpecifier Id, StringRef Default="") const
getLastArgValue - Return the value of the last argument, or a default.
std::vector< std::string > getAllArgValues (OptSpecifier Id) const
getAllArgValues - Get the values of all instances of the given argument as strings.
Translation Utilities
bool hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default=true) const
hasFlag - Given an option Pos and its negative form Neg, return true if the option is present, false if the negation is present, and Default if neither option is given.
bool hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default=true) const
hasFlag - Given an option Pos, an alias PosAlias and its negative form Neg, return true if the option or its alias is present, false if the negation is present, and Default if none of the options are given.
template<typename ... OptSpecifiers>
void AddLastArg (ArgStringList &Output, OptSpecifiers ...Ids) const
Render only the last argument match Id0, if present.
void AddAllArgsExcept (ArgStringList &Output, ArrayRef< OptSpecifier > Ids, ArrayRef< OptSpecifier > ExcludeIds) const
AddAllArgsExcept - Render all arguments matching any of the given ids and not matching any of the excluded ids.
void AddAllArgs (ArgStringList &Output, ArrayRef< OptSpecifier > Ids) const
AddAllArgs - Render all arguments matching any of the given ids.
void AddAllArgs (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgs - Render all arguments matching the given ids.
void AddAllArgValues (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgValues - Render the argument values of all arguments matching the given ids.
void AddAllArgsTranslated (ArgStringList &Output, OptSpecifier Id0, const char *Translation, bool Joined=false) const
AddAllArgsTranslated - Render all the arguments matching the given ids, but forced to separate args and using the provided name instead of the first option value.
void ClaimAllArgs (OptSpecifier Id0) const
ClaimAllArgs - Claim all arguments which match the given option id.
void ClaimAllArgs () const
ClaimAllArgs - Claim all arguments.
Arg Synthesis
virtual const char * MakeArgStringRef (StringRef Str) const =0
Construct a constant string pointer whose lifetime will match that of the ArgList.
const char * MakeArgString (const Twine &Str) const
const char * GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
void print (raw_ostream &O) const
void dump () const
Protected Member Functions
ArgList ()=default
ArgList (ArgList &&RHS)
ArgList & operator= (ArgList &&RHS)
~ArgList ()=default
Static Protected Member Functions
static OptSpecifier toOptSpecifier (OptSpecifier S)
Detailed Description
ArgList - Ordered collection of driver arguments.
The ArgList class manages a list of Arg instances as well as auxiliary data and convenience methods to allow Tools to quickly check for the presence of Arg instances for a particular Option and to iterate over groups of arguments.
Definition at line 116 of file ArgList.h.
Member Typedef Documentation
arglist_type
using llvm::opt::ArgList::arglist_type = SmallVector<Arg *, 16>
Definition at line 118 of file ArgList.h.
const_iterator
using llvm::opt::ArgList::const_iterator = arg_iterator<arglist_type::const_iterator>
Definition at line 120 of file ArgList.h.
const_reverse_iterator
using llvm::opt::ArgList::const_reverse_iterator = arg_iterator<arglist_type::const_reverse_iterator>
Definition at line 123 of file ArgList.h.
filtered_iterator
template<unsigned N> using llvm::opt::ArgList::filtered_iterator = arg_iterator<arglist_type::const_iterator, N>
Definition at line 126 of file ArgList.h.
filtered_reverse_iterator
template<unsigned N> using llvm::opt::ArgList::filtered_reverse_iterator = arg_iterator<arglist_type::const_reverse_iterator, N>
Definition at line 128 of file ArgList.h.
iterator
using llvm::opt::ArgList::iterator = arg_iterator<arglist_type::iterator>
Definition at line 119 of file ArgList.h.
reverse_iterator
using llvm::opt::ArgList::reverse_iterator = arg_iterator<arglist_type::reverse_iterator>
Definition at line 121 of file ArgList.h.
Constructor & Destructor Documentation
ArgList() [1/2]
llvm::opt::ArgList::ArgList () protected default
ArgList() [2/2]
llvm::opt::ArgList::ArgList (ArgList && RHS) inline protected
Definition at line 155 of file ArgList.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear().
~ArgList()
llvm::opt::ArgList::~ArgList () protected default
Member Function Documentation
AddAllArgs() [1/2]
void ArgList::AddAllArgs (ArgStringList & Output, ArrayRef< OptSpecifier > Ids) const
AddAllArgs - Render all arguments matching any of the given ids.
This is a nicer interface when you don't have a list of Ids to exclude.
Definition at line 122 of file ArgList.cpp.
References AddAllArgsExcept(), and llvm::None.
AddAllArgs() [2/2]
void ArgList::AddAllArgs (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const
AddAllArgs - Render all arguments matching the given ids.
This 3-opt variant of AddAllArgs could be eliminated in favor of one that accepts a single specifier, given the above which accepts any number.
Definition at line 130 of file ArgList.cpp.
References llvm::opt::Arg::claim(), filtered(), and llvm::opt::Arg::render().
AddAllArgsExcept()
void ArgList::AddAllArgsExcept (ArgStringList & Output, ArrayRef< OptSpecifier > Ids, ArrayRef< OptSpecifier > ExcludeIds) const
AddAllArgsExcept - Render all arguments matching any of the given ids and not matching any of the excluded ids.
Definition at line 98 of file ArgList.cpp.
References llvm::opt::Arg::claim(), llvm::opt::Arg::getOption(), llvm::opt::Option::matches(), and llvm::opt::Arg::render().
Referenced by AddAllArgs().
AddAllArgsTranslated()
void ArgList::AddAllArgsTranslated (ArgStringList & Output, OptSpecifier Id0, const char * Translation, bool Joined = false) const
AddAllArgsTranslated - Render all the arguments matching the given ids, but forced to separate args and using the provided name instead of the first option value.
Parameters
Joined - If true, render the argument as joined with the option specifier.
Definition at line 147 of file ArgList.cpp.
References llvm::opt::Arg::claim(), filtered(), llvm::opt::Arg::getValue(), MakeArgString(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
AddAllArgValues()
void ArgList::AddAllArgValues (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const
AddAllArgValues - Render the argument values of all arguments matching the given ids.
Definition at line 138 of file ArgList.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::opt::Arg::claim(), filtered(), and llvm::opt::Arg::getValues().
Referenced by getAllArgValues().
AddLastArg()
template<typename ... OptSpecifiers> void llvm::opt::ArgList::AddLastArg (ArgStringList & Output, OptSpecifiers ... Ids) const inline
Render only the last argument match Id0, if present.
Definition at line 306 of file ArgList.h.
References llvm::opt::Arg::render().
append()
void ArgList::append (Arg * A)
append - Append A to the arg list.
Definition at line 33 of file ArgList.cpp.
References llvm::opt::Arg::getOption(), llvm::opt::Option::getUnaliasedOption(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::RISCVFenceField::O, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase::size().
begin() [1/2]
iterator llvm::opt::ArgList::begin () inline
Definition at line 191 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
begin() [2/2]
const_iterator llvm::opt::ArgList::begin () const inline
Definition at line 197 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
ClaimAllArgs() [1/2]
void ArgList::ClaimAllArgs (OptSpecifier Id0) const
ClaimAllArgs - Claim all arguments which match the given option id.
Definition at line 163 of file ArgList.cpp.
References llvm::opt::Arg::claim(), and filtered().
ClaimAllArgs() [2/2]
void ArgList::ClaimAllArgs () const
ClaimAllArgs - Claim all arguments.
Definition at line 168 of file ArgList.cpp.
References llvm::opt::Arg::claim(), and llvm::opt::Arg::isClaimed().
dump()
LLVM_DUMP_METHOD void ArgList::dump () const
Definition at line 193 of file ArgList.cpp.
References llvm::dbgs(), and print().
end() [1/2]
iterator llvm::opt::ArgList::end () inline
Definition at line 192 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
end() [2/2]
const_iterator llvm::opt::ArgList::end () const inline
Definition at line 198 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
eraseArg()
void ArgList::eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
Definition at line 46 of file ArgList.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), filtered(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::opt::OptSpecifier::getID(), I, and llvm::max().
filtered()
template<typename ... OptSpecifiers> iterator_range<filtered_iterator<sizeof...(OptSpecifiers)> > llvm::opt::ArgList::filtered (OptSpecifiers ... Ids) const inline
Definition at line 205 of file ArgList.h.
References B, llvm::SmallVectorTemplateCommon< T, typename >::begin(), E, and llvm::make_range().
Referenced by AddAllArgs(), AddAllArgsTranslated(), AddAllArgValues(), ClaimAllArgs(), llvm::dlltoolDriverMain(), doList(), eraseArg(), and getSearchPaths().
filtered_reverse()
template<typename ... OptSpecifiers> iterator_range<filtered_reverse_iterator<sizeof...(OptSpecifiers)> > llvm::opt::ArgList::filtered_reverse (OptSpecifiers ... Ids) const inline
Definition at line 216 of file ArgList.h.
References B, E, llvm::make_range(), and llvm::SmallVectorTemplateCommon< T, typename >::rend().
getAllArgValues()
std::vector< std::string > ArgList::getAllArgValues (OptSpecifier Id) const
getAllArgValues - Get the values of all instances of the given argument as strings.
Definition at line 92 of file ArgList.cpp.
References AddAllArgValues(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
getArgs()
const arglist_type& llvm::opt::ArgList::getArgs () const inline
Definition at line 183 of file ArgList.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
getArgString()
virtual const char* llvm::opt::ArgList::getArgString (unsigned Index) const pure virtual
getArgString - Return the input argument string at Index.
Implemented in llvm::opt::DerivedArgList, and llvm::opt::InputArgList.
Referenced by GetOrMakeJoinedArgString(), llvm::opt::Option::matches(), and llvm::opt::OptTable::ParseOneArg().
getLastArg()
template<typename ... OptSpecifiers> Arg* llvm::opt::ArgList::getLastArg (OptSpecifiers ... Ids) const inline
Return the last argument matching Id, or null.
Definition at line 250 of file ArgList.h.
References llvm::opt::Arg::claim().
Referenced by llvm::dlltoolDriverMain(), getLastArgValue(), getOutputPath(), and hasFlag().
getLastArgNoClaim()
template<typename ... OptSpecifiers> Arg* llvm::opt::ArgList::getLastArgNoClaim (OptSpecifiers ... Ids) const inline
Return the last argument matching Id, or null.
Do not "claim" the option (don't mark it as having been used).
Definition at line 262 of file ArgList.h.
getLastArgValue()
StringRef ArgList::getLastArgValue (OptSpecifier Id, StringRef Default = "") const
getLastArgValue - Return the value of the last argument, or a default.
Definition at line 86 of file ArgList.cpp.
References getLastArg().
Referenced by llvm::dlltoolDriverMain().
getNumInputArgStrings()
virtual unsigned llvm::opt::ArgList::getNumInputArgStrings () const pure virtual
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Implemented in llvm::opt::DerivedArgList, and llvm::opt::InputArgList.
Referenced by llvm::opt::Option::matches().
GetOrMakeJoinedArgString()
const char * ArgList::GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
Definition at line 174 of file ArgList.cpp.
References llvm::StringRef::data(), llvm::StringRef::endswith(), getArgString(), MakeArgString(), llvm::StringRef::size(), and llvm::StringRef::startswith().
Referenced by llvm::opt::Arg::render().
hasArg()
template<typename ... OptSpecifiers> bool llvm::opt::ArgList::hasArg (OptSpecifiers ... Ids) const inline
Definition at line 244 of file ArgList.h.
Referenced by llvm::dlltoolDriverMain().
hasArgNoClaim()
template<typename ... OptSpecifiers> bool llvm::opt::ArgList::hasArgNoClaim (OptSpecifiers ... Ids) const inline
hasArg - Does the arg list contain any option matching Id.
Claim Whether the argument should be claimed, if it exists.
Definition at line 240 of file ArgList.h.
Referenced by llvm::dlltoolDriverMain().
hasFlag() [1/2]
bool ArgList::hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default = true) const
hasFlag - Given an option Pos and its negative form Neg, return true if the option is present, false if the negation is present, and Default if neither option is given.
If both the option and its negation are present, the last one wins.
Definition at line 73 of file ArgList.cpp.
References getLastArg().
hasFlag() [2/2]
bool ArgList::hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default = true) const
hasFlag - Given an option Pos, an alias PosAlias and its negative form Neg, return true if the option or its alias is present, false if the negation is present, and Default if none of the options are given.
If multiple options are present, the last one wins.
Definition at line 79 of file ArgList.cpp.
References getLastArg().
MakeArgString()
const char* llvm::opt::ArgList::MakeArgString (const Twine & Str) const inline
Definition at line 352 of file ArgList.h.
References llvm::dump(), llvm::RISCVFenceField::O, print(), and llvm::Twine::toStringRef().
Referenced by llvm::opt::Option::accept(), AddAllArgsTranslated(), llvm::opt::DerivedArgList::getBaseArgs(), llvm::opt::InputArgList::getNumInputArgStrings(), GetOrMakeJoinedArgString(), llvm::opt::DerivedArgList::MakeArgStringRef(), llvm::opt::DerivedArgList::MakeFlagArg(), llvm::opt::DerivedArgList::MakeJoinedArg(), llvm::opt::DerivedArgList::MakePositionalArg(), llvm::opt::DerivedArgList::MakeSeparateArg(), and llvm::opt::Arg::render().
MakeArgStringRef()
virtual const char* llvm::opt::ArgList::MakeArgStringRef (StringRef Str) const pure virtual
Construct a constant string pointer whose lifetime will match that of the ArgList.
Implemented in llvm::opt::DerivedArgList, and llvm::opt::InputArgList.
operator=()
ArgList& llvm::opt::ArgList::operator= (ArgList && RHS) inline protected
Definition at line 161 of file ArgList.h.
Referenced by llvm::opt::InputArgList::operator=().
print()
void ArgList::print (raw_ostream & O) const
Definition at line 185 of file ArgList.cpp.
References llvm::opt::Arg::print().
Referenced by dump().
rbegin() [1/2]
reverse_iterator llvm::opt::ArgList::rbegin () inline
Definition at line 194 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), and llvm::SmallVectorTemplateCommon< T, typename >::rend().
rbegin() [2/2]
const_reverse_iterator llvm::opt::ArgList::rbegin () const inline
Definition at line 200 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), and llvm::SmallVectorTemplateCommon< T, typename >::rend().
rend() [1/2]
reverse_iterator llvm::opt::ArgList::rend () inline
Definition at line 195 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rend().
rend() [2/2]
const_reverse_iterator llvm::opt::ArgList::rend () const inline
Definition at line 201 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rend().
size()
unsigned llvm::opt::ArgList::size () const inline
Definition at line 185 of file ArgList.h.
References llvm::SmallVectorBase::size().
toOptSpecifier()
static OptSpecifier llvm::opt::ArgList::toOptSpecifier (OptSpecifier S) inline static protected
Definition at line 174 of file ArgList.h.
References llvm::sys::path::append().
The documentation for this class was generated from the following files:
include/llvm/Option/ArgList.h
lib/Option/ArgList.cpp