LLVM: llvm::SimpleDDGNode Class Reference
llvm::SimpleDDGNode Class Reference
Subclass of DDGNode representing single or multi-instruction nodes.
#include "llvm/Analysis/DDG.h"
Public Member Functions
SimpleDDGNode ()=delete
SimpleDDGNode (Instruction &I)
SimpleDDGNode (const SimpleDDGNode &N)
SimpleDDGNode (SimpleDDGNode &&N)
~SimpleDDGNode ()
SimpleDDGNode & operator= (const SimpleDDGNode &N)
SimpleDDGNode & operator= (SimpleDDGNode &&N)
const InstructionListType & getInstructions () const
Get the list of instructions in this node.
InstructionListType & getInstructions ()
Instruction * getFirstInstruction () const
Get the first/last instruction in the node.
Instruction * getLastInstruction () const
Public Member Functions inherited from llvm::DDGNode
DDGNode ()=delete
DDGNode (const NodeKind K)
DDGNode (const DDGNode &N)
DDGNode (DDGNode &&N)
virtual ~DDGNode ()=0
DDGNode & operator= (const DDGNode &N)
DDGNode & operator= (DDGNode &&N)
NodeKind getKind () const
Getter for the kind of this node.
bool collectInstructions (llvm::function_ref< bool(Instruction *)> const &Pred, InstructionListType &IList) const
Collect a list of instructions, in IList, for which predicate Pred evaluates to true when iterating over instructions of this node.
Public Member Functions inherited from llvm::DGNode< NodeType, EdgeType >
DGNode (EdgeType &E)
Create a node with a single outgoing edge E.
DGNode ()=default
DGNode (const DGNode< NodeType, EdgeType > &N)
DGNode (DGNode< NodeType, EdgeType > &&N)
DGNode< NodeType, EdgeType > & operator= (const DGNode< NodeType, EdgeType > &N)
DGNode< NodeType, EdgeType > & operator= (const DGNode< NodeType, EdgeType > &&N)
bool operator== (const NodeType &N) const
Static polymorphism: delegate implementation (via isEqualTo) to the derived class.
bool operator!= (const NodeType &N) const
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
const EdgeType & front () const
EdgeType & front ()
const EdgeType & back () const
EdgeType & back ()
bool findEdgesTo (const NodeType &N, SmallVectorImpl< EdgeType *> &EL) const
Collect in EL, all the edges from this node to N.
bool addEdge (EdgeType &E)
Add the given edge E to this node, if it doesn't exist already.
void removeEdge (EdgeType &E)
Remove the given edge E from this node, if it exists.
bool hasEdgeTo (const NodeType &N) const
Test whether there is an edge that goes from this node to N.
const EdgeListTy & getEdges () const
Retrieve the outgoing edges for the node.
EdgeListTy & getEdges ()
void clear ()
Clear the outgoing edges.
Static Public Member Functions
static bool classof (const DDGNode *N)
Define classof to be able to use isa<>, cast<>, dyn_cast<>, etc.
static bool classof (const SimpleDDGNode *N)
Additional Inherited Members
Public Types inherited from llvm::DDGNode
enum NodeKind {
NodeKind::Unknown, NodeKind::SingleInstruction, NodeKind::MultiInstruction, NodeKind::PiBlock,
NodeKind::Root
}
using InstructionListType = SmallVectorImpl< Instruction * >
Public Types inherited from llvm::DGNode< NodeType, EdgeType >
using EdgeListTy = SetVector< EdgeType * >
using iterator = typename EdgeListTy::iterator
using const_iterator = typename EdgeListTy::const_iterator
Protected Member Functions inherited from llvm::DDGNode
void setKind (NodeKind K)
Setter for the kind of this node.
Protected Member Functions inherited from llvm::DGNode< NodeType, EdgeType >
bool isEqualTo (const NodeType &N) const
NodeType & getDerived ()
const NodeType & getDerived () const
const_iterator findEdgeTo (const NodeType &N) const
Find an edge to N.
Protected Attributes inherited from llvm::DGNode< NodeType, EdgeType >
EdgeListTy Edges
Detailed Description
Subclass of DDGNode representing single or multi-instruction nodes.
Definition at line 106 of file DDG.h.
Constructor & Destructor Documentation
SimpleDDGNode() [1/4]
llvm::SimpleDDGNode::SimpleDDGNode () delete
SimpleDDGNode() [2/4]
SimpleDDGNode::SimpleDDGNode (Instruction & I)
Definition at line 103 of file DDG.cpp.
References assert().
SimpleDDGNode() [3/4]
SimpleDDGNode::SimpleDDGNode (const SimpleDDGNode & N)
Definition at line 109 of file DDG.cpp.
References assert(), llvm::DDGNode::getKind(), llvm::DDGNode::MultiInstruction, and llvm::DDGNode::SingleInstruction.
SimpleDDGNode() [4/4]
SimpleDDGNode::SimpleDDGNode (SimpleDDGNode && N)
Definition at line 116 of file DDG.cpp.
References assert(), llvm::DDGNode::getKind(), llvm::DDGNode::MultiInstruction, and llvm::DDGNode::SingleInstruction.
~SimpleDDGNode()
SimpleDDGNode::~SimpleDDGNode ()
Definition at line 123 of file DDG.cpp.
Member Function Documentation
classof() [1/2]
static bool llvm::SimpleDDGNode::classof (const DDGNode * N) inline static
Define classof to be able to use isa<>, cast<>, dyn_cast<>, etc.
Definition at line 141 of file DDG.h.
References llvm::DDGNode::getKind(), llvm::DDGNode::MultiInstruction, and llvm::DDGNode::SingleInstruction.
classof() [2/2]
static bool llvm::SimpleDDGNode::classof (const SimpleDDGNode * N) inline static
Definition at line 145 of file DDG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getInstructions(), llvm::DDGNode::MultiInstruction, llvm::DDGNode::setKind(), llvm::DDGNode::SingleInstruction, and llvm::SmallVectorBase::size().
getFirstInstruction()
Instruction* llvm::SimpleDDGNode::getFirstInstruction () const inline
Get the first/last instruction in the node.
Definition at line 137 of file DDG.h.
getInstructions() [1/2]
const InstructionListType& llvm::SimpleDDGNode::getInstructions () const inline
Get the list of instructions in this node.
Definition at line 127 of file DDG.h.
References assert().
Referenced by classof().
getInstructions() [2/2]
InstructionListType& llvm::SimpleDDGNode::getInstructions () inline
Definition at line 131 of file DDG.h.
getLastInstruction()
Instruction* llvm::SimpleDDGNode::getLastInstruction () const inline
Definition at line 138 of file DDG.h.
operator=() [1/2]
SimpleDDGNode& llvm::SimpleDDGNode::operator= (const SimpleDDGNode & N) inline
Definition at line 114 of file DDG.h.
References llvm::DDGNode::operator=().
operator=() [2/2]
SimpleDDGNode& llvm::SimpleDDGNode::operator= (SimpleDDGNode && N) inline
Definition at line 120 of file DDG.h.
References llvm::DDGNode::operator=().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DDG.h
lib/Analysis/DDG.cpp