LLVM: llvm::SelectionDAGTargetInfo Class Reference
llvm::SelectionDAGTargetInfo Class Reference
Targets can subclass this to parameterize the SelectionDAG lowering and instruction selection process.
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
Public Member Functions
SelectionDAGTargetInfo ()=default
SelectionDAGTargetInfo (const SelectionDAGTargetInfo &)=delete
SelectionDAGTargetInfo & operator= (const SelectionDAGTargetInfo &)=delete
virtual ~SelectionDAGTargetInfo ()
virtual SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memcpy.
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memmove.
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const
Emit target-specific code that performs a memset.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a memcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
virtual SDValue EmitTargetCodeForSetTag (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Addr, SDValue Size, MachinePointerInfo DstPtrInfo, bool ZeroData) const
virtual bool generateFMAsInMachineCombiner (CodeGenOpt::Level OptLevel) const
Detailed Description
Targets can subclass this to parameterize the SelectionDAG lowering and instruction selection process.
Definition at line 31 of file SelectionDAGTargetInfo.h.
Constructor & Destructor Documentation
SelectionDAGTargetInfo() [1/2]
llvm::SelectionDAGTargetInfo::SelectionDAGTargetInfo () explicit default
SelectionDAGTargetInfo() [2/2]
llvm::SelectionDAGTargetInfo::SelectionDAGTargetInfo (const SelectionDAGTargetInfo &) delete
~SelectionDAGTargetInfo()
SelectionDAGTargetInfo::~SelectionDAGTargetInfo () virtual default
Member Function Documentation
EmitTargetCodeForMemchr()
virtual std::pair<SDValue, SDValue> llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemchr (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const inline virtual
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memchr and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 105 of file SelectionDAGTargetInfo.h.
Referenced by getMemCmpLoad().
EmitTargetCodeForMemcmp()
virtual std::pair<SDValue, SDValue> llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemcmp (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const inline virtual
Emit target-specific code that performs a memcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 93 of file SelectionDAGTargetInfo.h.
Referenced by getMemCmpLoad().
EmitTargetCodeForMemcpy()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const inline virtual
Emit target-specific code that performs a memcpy.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented in llvm::ARMSelectionDAGInfo, llvm::X86SelectionDAGInfo, llvm::SystemZSelectionDAGInfo, llvm::LanaiSelectionDAGInfo, llvm::WebAssemblySelectionDAGInfo, llvm::HexagonSelectionDAGInfo, llvm::XCoreSelectionDAGInfo, and llvm::BPFSelectionDAGInfo.
Definition at line 51 of file SelectionDAGTargetInfo.h.
Referenced by llvm::SelectionDAG::getMemcpy().
EmitTargetCodeForMemmove()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemmove (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const inline virtual
Emit target-specific code that performs a memmove.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented in llvm::ARMSelectionDAGInfo, and llvm::WebAssemblySelectionDAGInfo.
Definition at line 67 of file SelectionDAGTargetInfo.h.
Referenced by llvm::SelectionDAG::getMemmove().
EmitTargetCodeForMemset()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const inline virtual
Emit target-specific code that performs a memset.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented in llvm::ARMSelectionDAGInfo, llvm::WebAssemblySelectionDAGInfo, llvm::X86SelectionDAGInfo, llvm::SystemZSelectionDAGInfo, and llvm::AArch64SelectionDAGInfo.
Definition at line 80 of file SelectionDAGTargetInfo.h.
Referenced by llvm::SelectionDAG::getMemset().
EmitTargetCodeForSetTag()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForSetTag (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Addr, SDValue Size, MachinePointerInfo DstPtrInfo, bool ZeroData) const inline virtual
Reimplemented in llvm::AArch64SelectionDAGInfo.
Definition at line 150 of file SelectionDAGTargetInfo.h.
Referenced by FixedPointIntrinsicToOpcode().
EmitTargetCodeForStrcmp()
virtual std::pair<SDValue, SDValue> llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrcmp (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const inline virtual
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the strcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 130 of file SelectionDAGTargetInfo.h.
Referenced by getMemCmpLoad().
EmitTargetCodeForStrcpy()
virtual std::pair<SDValue, SDValue> llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrcpy (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const inline virtual
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
The first returned SDValue is the result of the copy (the start of the destination string for strcpy, a pointer to the null terminator for stpcpy) and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 118 of file SelectionDAGTargetInfo.h.
Referenced by getMemCmpLoad().
EmitTargetCodeForStrlen()
virtual std::pair<SDValue, SDValue> llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const inline virtual
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 138 of file SelectionDAGTargetInfo.h.
Referenced by getMemCmpLoad().
EmitTargetCodeForStrnlen()
virtual std::pair<SDValue, SDValue> llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrnlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const inline virtual
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 144 of file SelectionDAGTargetInfo.h.
Referenced by getMemCmpLoad().
generateFMAsInMachineCombiner()
virtual bool llvm::SelectionDAGTargetInfo::generateFMAsInMachineCombiner (CodeGenOpt::Level OptLevel) const inline virtual
Reimplemented in llvm::AArch64SelectionDAGInfo.
Definition at line 160 of file SelectionDAGTargetInfo.h.
Referenced by isContractable().
operator=()
SelectionDAGTargetInfo& llvm::SelectionDAGTargetInfo::operator= (const SelectionDAGTargetInfo &) delete
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAGTargetInfo.h
lib/CodeGen/SelectionDAG/SelectionDAGTargetInfo.cpp