LLVM: llvm::object::COFFObjectFile Class Reference
llvm::object::COFFObjectFile Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
uintptr_t getSymbolTable () const
uint16_t getMachine () const
uint16_t getSizeOfOptionalHeader () const
uint16_t getCharacteristics () const
uint32_t getTimeDateStamp () const
uint32_t getNumberOfSections () const
uint32_t getPointerToSymbolTable () const
uint32_t getRawNumberOfSymbols () const
uint32_t getNumberOfSymbols () const
const coff_load_configuration32 * getLoadConfig32 () const
const coff_load_configuration64 * getLoadConfig64 () const
StringRef getRelocationTypeName (uint16_t Type) const
COFFObjectFile (MemoryBufferRef Object, std::error_code &EC)
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
section_iterator section_begin () const override
section_iterator section_end () const override
const coff_section * getCOFFSection (const SectionRef &Section) const
COFFSymbolRef getCOFFSymbol (const DataRefImpl &Ref) const
COFFSymbolRef getCOFFSymbol (const SymbolRef &Symbol) const
const coff_relocation * getCOFFRelocation (const RelocationRef &Reloc) const
unsigned getSectionID (SectionRef Sec) const
unsigned getSymbolSectionID (SymbolRef Sym) const
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
Expected< uint64_t > getStartAddress () const override
SubtargetFeatures getFeatures () const override
import_directory_iterator import_directory_begin () const
import_directory_iterator import_directory_end () const
delay_import_directory_iterator delay_import_directory_begin () const
delay_import_directory_iterator delay_import_directory_end () const
export_directory_iterator export_directory_begin () const
export_directory_iterator export_directory_end () const
base_reloc_iterator base_reloc_begin () const
base_reloc_iterator base_reloc_end () const
const debug_directory * debug_directory_begin () const
const debug_directory * debug_directory_end () const
iterator_range< import_directory_iterator > import_directories () const
iterator_range< delay_import_directory_iterator > delay_import_directories () const
iterator_range< export_directory_iterator > export_directories () const
iterator_range< base_reloc_iterator > base_relocs () const
iterator_range< const debug_directory * > debug_directories () const
const dos_header * getDOSHeader () const
const coff_file_header * getCOFFHeader () const
const coff_bigobj_file_header * getCOFFBigObjHeader () const
const pe32_header * getPE32Header () const
const pe32plus_header * getPE32PlusHeader () const
std::error_code getDataDirectory (uint32_t index, const data_directory *&Res) const
std::error_code getSection (int32_t index, const coff_section *&Res) const
std::error_code getSection (StringRef SectionName, const coff_section *&Res) const
template<typename coff_symbol_type >
std::error_code getSymbol (uint32_t Index, const coff_symbol_type *&Res) const
Expected< COFFSymbolRef > getSymbol (uint32_t index) const
template<typename T >
std::error_code getAuxSymbol (uint32_t index, const T *&Res) const
std::error_code getSymbolName (COFFSymbolRef Symbol, StringRef &Res) const
std::error_code getSymbolName (const coff_symbol_generic *Symbol, StringRef &Res) const
ArrayRef< uint8_t > getSymbolAuxData (COFFSymbolRef Symbol) const
uint32_t getSymbolIndex (COFFSymbolRef Symbol) const
size_t getSymbolTableEntrySize () const
ArrayRef< coff_relocation > getRelocations (const coff_section *Sec) const
Expected< StringRef > getSectionName (const coff_section *Sec) const
uint64_t getSectionSize (const coff_section *Sec) const
Error getSectionContents (const coff_section *Sec, ArrayRef< uint8_t > &Res) const
uint64_t getImageBase () const
std::error_code getVaPtr (uint64_t VA, uintptr_t &Res) const
std::error_code getRvaPtr (uint32_t Rva, uintptr_t &Res) const
std::error_code getRvaAndSizeAsBytes (uint32_t RVA, uint32_t Size, ArrayRef< uint8_t > &Contents) const
Given an RVA base and size, returns a valid array of bytes or an error code if the RVA and size is not contained completely within a valid section.
std::error_code getHintName (uint32_t Rva, uint16_t &Hint, StringRef &Name) const
std::error_code getDebugPDBInfo (const debug_directory *DebugDir, const codeview::DebugInfo *&Info, StringRef &PDBFileName) const
Get PDB information out of a codeview debug directory entry.
std::error_code getDebugPDBInfo (const codeview::DebugInfo *&Info, StringRef &PDBFileName) const
Get PDB information from an executable.
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
bool is64 () const
StringRef mapDebugSectionName (StringRef Name) const override
Maps a debug section name to a standard DWARF section name.
template<typename coff_symbol_type >
const coff_symbol_type * toSymb (DataRefImpl Ref) const
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
section_iterator_range sections () const
virtual void setARMSubArch (Triple &TheTriple) const
Triple makeTriple () const
Create a triple from the data in this object file.
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static Expected< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Protected Member Functions
void moveSymbolNext (DataRefImpl &Symb) const override
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint32_t getSymbolAlignment (DataRefImpl Symb) const override
uint64_t getSymbolValueImpl (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual Expected< section_iterator > getRelocatedSection (DataRefImpl Sec) const
uint64_t getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Friends
class ImportDirectoryEntryRef
class ExportDirectoryEntryRef
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_COFFImportFile, ID_IR,
ID_TapiUniversal, ID_TapiFile, ID_Minidump, ID_WinRes,
ID_StartObjects, ID_COFF, ID_XCOFF32, ID_XCOFF64,
ID_ELF32L, ID_ELF32B, ID_ELF64L, ID_ELF64B,
ID_MachO32L, ID_MachO32B, ID_MachO64L, ID_MachO64B,
ID_Wasm, ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 765 of file COFF.h.
Constructor & Destructor Documentation
COFFObjectFile()
COFFObjectFile::COFFObjectFile (MemoryBufferRef Object, std::error_code & EC)
Definition at line 664 of file COFFObjectFile.cpp.
References llvm::object::dos_header::AddressOfNewExeHeader, llvm::object::ObjectFile::base(), llvm::COFF::BigObjMagic, checkSize(), llvm::object::Binary::Data, getNumberOfSections(), getNumberOfSymbols(), llvm::object::getObject(), getPointerToSymbolTable(), llvm::COFF::IMAGE_FILE_MACHINE_UNKNOWN, llvm::object::coff_file_header::isImportLibrary(), llvm::object::coff_file_header::Machine, llvm::object::pe32_header::Magic, memcmp, llvm::COFF::BigObjHeader::MinBigObjectVersion, llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::pe32plus_header::NumberOfRvaAndSize, llvm::object::coff_file_header::NumberOfSections, llvm::object::parse_failed, llvm::COFF::PE32Header::PE32, llvm::COFF::PE32Header::PE32_PLUS, llvm::COFF::PEMagic, llvm::object::coff_file_header::SizeOfOptionalHeader, llvm::object::coff_bigobj_file_header::UUID, and llvm::object::coff_bigobj_file_header::Version.
Referenced by llvm::object::ObjectFile::createCOFFObjectFile().
Member Function Documentation
base_reloc_begin()
base_reloc_iterator COFFObjectFile::base_reloc_begin () const
Definition at line 871 of file COFFObjectFile.cpp.
Referenced by base_relocs().
base_reloc_end()
base_reloc_iterator COFFObjectFile::base_reloc_end () const
Definition at line 875 of file COFFObjectFile.cpp.
Referenced by base_relocs().
base_relocs()
iterator_range< base_reloc_iterator > COFFObjectFile::base_relocs () const
Definition at line 935 of file COFFObjectFile.cpp.
References base_reloc_begin(), base_reloc_end(), and llvm::make_range().
classof()
static bool llvm::object::COFFObjectFile::classof (const Binary * v) inline static
Definition at line 1076 of file COFF.h.
References llvm::object::Binary::isCOFF().
debug_directories()
iterator_range<const debug_directory *> llvm::object::COFFObjectFile::debug_directories () const inline
Definition at line 966 of file COFF.h.
References llvm::make_range().
Referenced by getHintName().
debug_directory_begin()
const debug_directory* llvm::object::COFFObjectFile::debug_directory_begin () const inline
Definition at line 954 of file COFF.h.
debug_directory_end()
const debug_directory* llvm::object::COFFObjectFile::debug_directory_end () const inline
Definition at line 957 of file COFF.h.
delay_import_directories()
iterator_range< delay_import_directory_iterator > COFFObjectFile::delay_import_directories () const
Definition at line 925 of file COFFObjectFile.cpp.
References delay_import_directory_begin(), delay_import_directory_end(), and llvm::make_range().
delay_import_directory_begin()
delay_import_directory_iterator COFFObjectFile::delay_import_directory_begin () const
Definition at line 832 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
delay_import_directory_end()
delay_import_directory_iterator COFFObjectFile::delay_import_directory_end () const
Definition at line 838 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
export_directories()
iterator_range< export_directory_iterator > COFFObjectFile::export_directories () const
Definition at line 931 of file COFFObjectFile.cpp.
References export_directory_begin(), export_directory_end(), and llvm::make_range().
Referenced by llvm::symbolize::SymbolizableObjectFile::create().
export_directory_begin()
export_directory_iterator COFFObjectFile::export_directory_begin () const
Definition at line 844 of file COFFObjectFile.cpp.
References ExportDirectoryEntryRef.
Referenced by export_directories().
export_directory_end()
export_directory_iterator COFFObjectFile::export_directory_end () const
Definition at line 849 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::AddressTableEntries, and ExportDirectoryEntryRef.
Referenced by export_directories().
getArch()
Triple::ArchType COFFObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 898 of file COFFObjectFile.cpp.
References llvm::Triple::aarch64, getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::Triple::thumb, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by getBytesInAddress().
getAuxSymbol()
template<typename T > std::error_code llvm::object::COFFObjectFile::getAuxSymbol (uint32_t index, const T *& Res) const inline
Definition at line 1015 of file COFF.h.
References E, llvm::errorToErrorCode(), getSymbolName(), and llvm::Expected< T >::takeError().
getBytesInAddress()
uint8_t COFFObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 879 of file COFFObjectFile.cpp.
References llvm::Triple::aarch64, getArch(), and llvm::Triple::x86_64.
getCharacteristics()
uint16_t llvm::object::COFFObjectFile::getCharacteristics () const inline
Definition at line 832 of file COFF.h.
References llvm::object::coff_file_header::Characteristics, llvm::object::coff_file_header::isImportLibrary(), and llvm_unreachable.
getCOFFBigObjHeader()
const coff_bigobj_file_header* llvm::object::COFFObjectFile::getCOFFBigObjHeader () const inline
Definition at line 977 of file COFF.h.
getCOFFHeader()
const coff_file_header* llvm::object::COFFObjectFile::getCOFFHeader () const inline
Definition at line 976 of file COFF.h.
getCOFFRelocation()
const coff_relocation * COFFObjectFile::getCOFFRelocation (const RelocationRef & Reloc) const
Definition at line 1167 of file COFFObjectFile.cpp.
References llvm::object::RelocationRef::getRawDataRefImpl().
getCOFFSection()
const coff_section * COFFObjectFile::getCOFFSection (const SectionRef & Section) const
Definition at line 1150 of file COFFObjectFile.cpp.
References llvm::object::SectionRef::getRawDataRefImpl().
Referenced by getDataDirectory(), getRvaAndSizeAsBytes(), and getRvaPtr().
getCOFFSymbol() [1/2]
COFFSymbolRef COFFObjectFile::getCOFFSymbol (const DataRefImpl & Ref) const
Definition at line 1154 of file COFFObjectFile.cpp.
References llvm_unreachable.
Referenced by getCOFFSymbol(), getCommonSymbolSizeImpl(), getSymbolAddress(), getSymbolAlignment(), getSymbolFlags(), getSymbolSection(), getSymbolSectionID(), getSymbolType(), and getSymbolValueImpl().
getCOFFSymbol() [2/2]
COFFSymbolRef COFFObjectFile::getCOFFSymbol (const SymbolRef & Symbol) const
Definition at line 1162 of file COFFObjectFile.cpp.
References getCOFFSymbol(), and llvm::object::BasicSymbolRef::getRawDataRefImpl().
getCommonSymbolSizeImpl()
uint64_t COFFObjectFile::getCommonSymbolSizeImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 243 of file COFFObjectFile.cpp.
References getCOFFSymbol(), and llvm::object::COFFSymbolRef::getValue().
getDataDirectory()
std::error_code COFFObjectFile::getDataDirectory (uint32_t index, const data_directory *& Res) const
Definition at line 940 of file COFFObjectFile.cpp.
References assert(), llvm::errorToErrorCode(), getCOFFSection(), getNumberOfSections(), getSection(), llvm::COFF::isReservedSectionNumber(), llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::pe32plus_header::NumberOfRvaAndSize, llvm::object::parse_failed, llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), and llvm::object::unexpected_eof.
Referenced by getHintName().
getDebugPDBInfo() [1/2]
std::error_code llvm::object::COFFObjectFile::getDebugPDBInfo (const debug_directory * DebugDir, const codeview::DebugInfo *& Info, StringRef & PDBFileName) const
Get PDB information out of a codeview debug directory entry.
Referenced by getHintName().
getDebugPDBInfo() [2/2]
std::error_code llvm::object::COFFObjectFile::getDebugPDBInfo (const codeview::DebugInfo *& Info, StringRef & PDBFileName) const
Get PDB information from an executable.
If the information is not present, Info will be set to nullptr and PDBFileName will be empty. An error is returned only on corrupt object files. Convenience accessor that can be used if the debug directory is not already handy.
getDOSHeader()
const dos_header* llvm::object::COFFObjectFile::getDOSHeader () const inline
Definition at line 970 of file COFF.h.
Referenced by getSectionSize().
getFeatures()
SubtargetFeatures llvm::object::COFFObjectFile::getFeatures () const inline override virtual
Implements llvm::object::ObjectFile.
Definition at line 944 of file COFF.h.
getFileFormatName()
StringRef COFFObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 883 of file COFFObjectFile.cpp.
References getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, and llvm::COFF::IMAGE_FILE_MACHINE_I386.
getHintName()
std::error_code COFFObjectFile::getHintName (uint32_t Rva, uint16_t & Hint, StringRef & Name) const
Definition at line 494 of file COFFObjectFile.cpp.
References llvm::object::debug_directory::AddressOfRawData, llvm::COFF::BASE_RELOCATION_TABLE, llvm::object::Binary::checkOffset(), D, llvm::object::Binary::Data, llvm::ArrayRef< T >::data(), debug_directories(), llvm::COFF::DEBUG_DIRECTORY, llvm::COFF::DELAY_IMPORT_DESCRIPTOR, llvm::ArrayRef< T >::drop_front(), llvm::COFF::EXPORT_TABLE, getDataDirectory(), getDebugPDBInfo(), getRvaAndSizeAsBytes(), getRvaPtr(), llvm::COFF::IMAGE_DEBUG_TYPE_CODEVIEW, llvm::COFF::IMPORT_TABLE, llvm::COFF::LOAD_CONFIG_TABLE, llvm::object::parse_failed, llvm::object::data_directory::RelativeVirtualAddress, llvm::ArrayRef< T >::size(), llvm::object::data_directory::Size, llvm::object::debug_directory::SizeOfData, and llvm::StringRef::split().
getImageBase()
uint64_t COFFObjectFile::getImageBase () const
Definition at line 439 of file COFFObjectFile.cpp.
References llvm::object::pe32_header::ImageBase, and llvm::object::pe32plus_header::ImageBase.
Referenced by llvm::symbolize::SymbolizableObjectFile::create(), getSectionAddress(), getSymbolAddress(), getVaPtr(), and llvm::pdb::PDBContext::PDBContext().
getLoadConfig32()
const coff_load_configuration32* llvm::object::COFFObjectFile::getLoadConfig32 () const inline
Definition at line 881 of file COFF.h.
References assert().
getLoadConfig64()
const coff_load_configuration64* llvm::object::COFFObjectFile::getLoadConfig64 () const inline
Definition at line 886 of file COFF.h.
References assert(), getSectionID(), getSymbolName(), getSymbolSectionID(), getSymbolType(), llvm::Ref, llvm::ARMBuildAttrs::Section, and llvm::ARMBuildAttrs::Symbol.
getMachine()
uint16_t llvm::object::COFFObjectFile::getMachine () const inline
Definition at line 814 of file COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::Machine, and llvm::object::coff_bigobj_file_header::Machine.
Referenced by getArch(), getCOFFFileMachine(), getFileFormatName(), getRelocationTypeName(), and llvm::symbolize::SymbolizableObjectFile::isWin32Module().
getNumberOfSections()
uint32_t llvm::object::COFFObjectFile::getNumberOfSections () const inline
Definition at line 850 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSections, and llvm::object::coff_bigobj_file_header::NumberOfSections.
Referenced by COFFObjectFile(), getDataDirectory(), section_end(), and toSymb().
getNumberOfSymbols()
uint32_t llvm::object::COFFObjectFile::getNumberOfSymbols () const inline
Definition at line 875 of file COFF.h.
Referenced by COFFObjectFile(), getRelocationSymbol(), getSymbolAuxData(), getSymbolIndex(), and section_rel_end().
getPE32Header()
const pe32_header* llvm::object::COFFObjectFile::getPE32Header () const inline
Definition at line 980 of file COFF.h.
getPE32PlusHeader()
const pe32plus_header* llvm::object::COFFObjectFile::getPE32PlusHeader () const inline
Definition at line 981 of file COFF.h.
References llvm::object::getSection().
getPointerToSymbolTable()
uint32_t llvm::object::COFFObjectFile::getPointerToSymbolTable () const inline
Definition at line 858 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::PointerToSymbolTable, and llvm::object::coff_bigobj_file_header::PointerToSymbolTable.
Referenced by COFFObjectFile(), getSymbolAuxData(), section_rel_end(), and toSymb().
getRawNumberOfSymbols()
uint32_t llvm::object::COFFObjectFile::getRawNumberOfSymbols () const inline
Definition at line 867 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSymbols, and llvm::object::coff_bigobj_file_header::NumberOfSymbols.
getRelocationOffset()
uint64_t COFFObjectFile::getRelocationOffset (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1125 of file COFFObjectFile.cpp.
References llvm::object::coff_relocation::VirtualAddress.
getRelocations()
ArrayRef< coff_relocation > COFFObjectFile::getRelocations (const coff_section * Sec) const
Definition at line 1172 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), and getNumberOfRelocations().
getRelocationSymbol()
symbol_iterator COFFObjectFile::getRelocationSymbol (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1130 of file COFFObjectFile.cpp.
References getNumberOfSymbols(), llvm_unreachable, llvm::object::DataRefImpl::p, symbol_end(), llvm::object::ObjectFile::SymbolRef, and llvm::object::coff_relocation::SymbolTableIndex.
getRelocationType()
uint64_t COFFObjectFile::getRelocationType (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1144 of file COFFObjectFile.cpp.
References llvm::object::coff_relocation::Type.
getRelocationTypeName() [1/2]
StringRef COFFObjectFile::getRelocationTypeName (uint16_t Type) const
Definition at line 1181 of file COFFObjectFile.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMAGE_REL_AMD64_ABSOLUTE, llvm::COFF::IMAGE_REL_AMD64_ADDR32, llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_PAIR, llvm::COFF::IMAGE_REL_AMD64_REL32, llvm::COFF::IMAGE_REL_AMD64_REL32_1, llvm::COFF::IMAGE_REL_AMD64_REL32_2, llvm::COFF::IMAGE_REL_AMD64_REL32_3, llvm::COFF::IMAGE_REL_AMD64_REL32_4, llvm::COFF::IMAGE_REL_AMD64_REL32_5, llvm::COFF::IMAGE_REL_AMD64_SECREL, llvm::COFF::IMAGE_REL_AMD64_SECREL7, llvm::COFF::IMAGE_REL_AMD64_SECTION, llvm::COFF::IMAGE_REL_AMD64_SREL32, llvm::COFF::IMAGE_REL_AMD64_SSPAN32, llvm::COFF::IMAGE_REL_AMD64_TOKEN, llvm::COFF::IMAGE_REL_ARM64_ABSOLUTE, llvm::COFF::IMAGE_REL_ARM64_ADDR32, llvm::COFF::IMAGE_REL_ARM64_ADDR32NB, llvm::COFF::IMAGE_REL_ARM64_ADDR64, llvm::COFF::IMAGE_REL_ARM64_BRANCH14, llvm::COFF::IMAGE_REL_ARM64_BRANCH19, llvm::COFF::IMAGE_REL_ARM64_BRANCH26, llvm::COFF::IMAGE_REL_ARM64_PAGEBASE_REL21, llvm::COFF::IMAGE_REL_ARM64_PAGEOFFSET_12A, llvm::COFF::IMAGE_REL_ARM64_PAGEOFFSET_12L, llvm::COFF::IMAGE_REL_ARM64_REL21, llvm::COFF::IMAGE_REL_ARM64_REL32, llvm::COFF::IMAGE_REL_ARM64_SECREL, llvm::COFF::IMAGE_REL_ARM64_SECREL_HIGH12A, llvm::COFF::IMAGE_REL_ARM64_SECREL_LOW12A, llvm::COFF::IMAGE_REL_ARM64_SECREL_LOW12L, llvm::COFF::IMAGE_REL_ARM64_SECTION, llvm::COFF::IMAGE_REL_ARM64_TOKEN, llvm::COFF::IMAGE_REL_ARM_ABSOLUTE, llvm::COFF::IMAGE_REL_ARM_ADDR32, llvm::COFF::IMAGE_REL_ARM_ADDR32NB, llvm::COFF::IMAGE_REL_ARM_BLX11, llvm::COFF::IMAGE_REL_ARM_BLX23T, llvm::COFF::IMAGE_REL_ARM_BLX24, llvm::COFF::IMAGE_REL_ARM_BRANCH11, llvm::COFF::IMAGE_REL_ARM_BRANCH20T, llvm::COFF::IMAGE_REL_ARM_BRANCH24, llvm::COFF::IMAGE_REL_ARM_BRANCH24T, llvm::COFF::IMAGE_REL_ARM_MOV32A, llvm::COFF::IMAGE_REL_ARM_MOV32T, llvm::COFF::IMAGE_REL_ARM_PAIR, llvm::COFF::IMAGE_REL_ARM_REL32, llvm::COFF::IMAGE_REL_ARM_SECREL, llvm::COFF::IMAGE_REL_ARM_SECTION, llvm::COFF::IMAGE_REL_ARM_TOKEN, llvm::COFF::IMAGE_REL_I386_ABSOLUTE, llvm::COFF::IMAGE_REL_I386_DIR16, llvm::COFF::IMAGE_REL_I386_DIR32, llvm::COFF::IMAGE_REL_I386_DIR32NB, llvm::COFF::IMAGE_REL_I386_REL16, llvm::COFF::IMAGE_REL_I386_REL32, llvm::COFF::IMAGE_REL_I386_SECREL, llvm::COFF::IMAGE_REL_I386_SECREL7, llvm::COFF::IMAGE_REL_I386_SECTION, llvm::COFF::IMAGE_REL_I386_SEG12, llvm::COFF::IMAGE_REL_I386_TOKEN, LLVM_COFF_SWITCH_RELOC_TYPE_NAME, and llvm::object::coff_relocation::Type.
getRelocationTypeName() [2/2]
void llvm::object::COFFObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override protected virtual
Implements llvm::object::ObjectFile.
getRvaAndSizeAsBytes()
std::error_code COFFObjectFile::getRvaAndSizeAsBytes (uint32_t RVA, uint32_t Size, ArrayRef< uint8_t > & Contents) const
Given an RVA base and size, returns a valid array of bytes or an error code if the RVA and size is not contained completely within a valid section.
Definition at line 472 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), getCOFFSection(), llvm::object::parse_failed, llvm::object::coff_section::PointerToRawData, llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), and llvm::object::coff_section::VirtualAddress.
Referenced by getHintName().
getRvaPtr()
std::error_code COFFObjectFile::getRvaPtr (uint32_t Rva, uintptr_t & Res) const
Definition at line 457 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), getCOFFSection(), llvm::object::parse_failed, llvm::object::coff_section::PointerToRawData, llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), llvm::object::coff_section::VirtualAddress, and llvm::object::coff_section::VirtualSize.
Referenced by getHintName(), and getVaPtr().
getSection() [1/2]
std::error_code llvm::object::COFFObjectFile::getSection (int32_t index, const coff_section *& Res) const
Referenced by getDataDirectory(), getSymbolAddress(), and getSymbolSection().
getSection() [2/2]
std::error_code llvm::object::COFFObjectFile::getSection (StringRef SectionName, const coff_section *& Res) const
getSectionAddress()
uint64_t COFFObjectFile::getSectionAddress (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 277 of file COFFObjectFile.cpp.
References getImageBase(), and llvm::object::coff_section::VirtualAddress.
getSectionAlignment()
uint64_t COFFObjectFile::getSectionAlignment (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 304 of file COFFObjectFile.cpp.
References llvm::object::coff_section::getAlignment().
getSectionContents() [1/2]
Expected<ArrayRef<uint8_t> > llvm::object::COFFObjectFile::getSectionContents (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by getSectionIndex().
getSectionContents() [2/2]
Error COFFObjectFile::getSectionContents (const coff_section * Sec, ArrayRef< uint8_t > & Res) const
Definition at line 1099 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::checkOffset(), llvm::object::Binary::Data, getSectionSize(), llvm::makeArrayRef(), llvm::object::DataRefImpl::p, llvm::object::coff_section::PointerToRawData, llvm::COFF::SectionSize, and llvm::Error::success().
getSectionID()
unsigned COFFObjectFile::getSectionID (SectionRef Sec) const
Definition at line 331 of file COFFObjectFile.cpp.
References assert(), llvm::object::SectionRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
getSectionIndex()
uint64_t COFFObjectFile::getSectionIndex (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 287 of file COFFObjectFile.cpp.
References E, getSectionContents(), and getSectionSize().
getSectionName() [1/2]
Expected<StringRef> llvm::object::COFFObjectFile::getSectionName (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by moveSectionNext().
getSectionName() [2/2]
Expected< StringRef > COFFObjectFile::getSectionName (const coff_section * Sec) const
Definition at line 1055 of file COFFObjectFile.cpp.
References llvm::createStringError(), decodeBase64StringEntry(), llvm::errorCodeToError(), llvm::StringRef::getAsInteger(), Name, llvm::object::coff_section::Name, llvm::COFF::NameSize, llvm::object::parse_failed, llvm::StringRef::startswith(), and llvm::StringRef::substr().
getSectionSize() [1/2]
uint64_t llvm::object::COFFObjectFile::getSectionSize (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by getSectionContents(), and getSectionIndex().
getSectionSize() [2/2]
uint64_t COFFObjectFile::getSectionSize (const coff_section * Sec) const
Definition at line 1083 of file COFFObjectFile.cpp.
References getDOSHeader(), llvm::object::coff_section::SizeOfRawData, and llvm::object::coff_section::VirtualSize.
getSizeOfOptionalHeader()
uint16_t llvm::object::COFFObjectFile::getSizeOfOptionalHeader () const inline
Definition at line 822 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, and llvm::object::coff_file_header::SizeOfOptionalHeader.
getStartAddress()
Expected< uint64_t > COFFObjectFile::getStartAddress () const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 913 of file COFFObjectFile.cpp.
References llvm::object::pe32_header::AddressOfEntryPoint.
getSymbol() [1/2]
template<typename coff_symbol_type > std::error_code llvm::object::COFFObjectFile::getSymbol (uint32_t Index, const coff_symbol_type *& Res) const inline
Definition at line 990 of file COFF.h.
References llvm::object::parse_failed.
getSymbol() [2/2]
Expected<COFFSymbolRef> llvm::object::COFFObjectFile::getSymbol (uint32_t index) const inline
Definition at line 998 of file COFF.h.
References llvm::errorCodeToError(), and llvm::object::parse_failed.
getSymbolAddress()
Expected< uint64_t > COFFObjectFile::getSymbolAddress (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 168 of file COFFObjectFile.cpp.
References llvm::errorCodeToError(), getCOFFSymbol(), getImageBase(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::ObjectFile::getSymbolValue(), llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::COFF::isReservedSectionNumber(), llvm::ARMBuildAttrs::Section, and llvm::object::coff_section::VirtualAddress.
getSymbolAlignment()
uint32_t COFFObjectFile::getSymbolAlignment (DataRefImpl Symb) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 161 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getValue(), and llvm::PowerOf2Ceil().
getSymbolAuxData()
ArrayRef< uint8_t > COFFObjectFile::getSymbolAuxData (COFFSymbolRef Symbol) const
Definition at line 1022 of file COFFObjectFile.cpp.
References assert(), llvm::object::ObjectFile::base(), llvm::object::COFFSymbolRef::getNumberOfAuxSymbols(), getNumberOfSymbols(), getPointerToSymbolTable(), llvm::object::COFFSymbolRef::getRawPtr(), getSymbolTableEntrySize(), llvm::makeArrayRef(), and llvm::report_fatal_error().
getSymbolFlags()
uint32_t COFFObjectFile::getSymbolFlags (DataRefImpl Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 212 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::COFFSymbolRef::getWeakExternal(), llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_WEAK_EXTERN_SEARCH_ALIAS, llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isExternal(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::object::COFFSymbolRef::isSectionDefinition(), llvm::object::COFFSymbolRef::isUndefined(), llvm::object::COFFSymbolRef::isWeakExternal(), llvm::object::BasicSymbolRef::SF_Absolute, llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::object::BasicSymbolRef::SF_Weak.
getSymbolIndex()
uint32_t COFFObjectFile::getSymbolIndex (COFFSymbolRef Symbol) const
Definition at line 1044 of file COFFObjectFile.cpp.
References assert(), getNumberOfSymbols(), llvm::object::COFFSymbolRef::getRawPtr(), getSymbolTable(), and getSymbolTableEntrySize().
getSymbolName() [1/3]
Expected<StringRef> llvm::object::COFFObjectFile::getSymbolName (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by getSymbolName().
getSymbolName() [2/3]
std::error_code COFFObjectFile::getSymbolName (COFFSymbolRef Symbol, StringRef & Res) const
Definition at line 998 of file COFFObjectFile.cpp.
References llvm::object::COFFSymbolRef::getGeneric(), and getSymbolName().
getSymbolName() [3/3]
std::error_code COFFObjectFile::getSymbolName (const coff_symbol_generic * Symbol, StringRef & Res) const
Definition at line 1003 of file COFFObjectFile.cpp.
References llvm::object::coff_symbol_generic::Name, llvm::COFF::NameSize, llvm::object::StringTableOffset::Offset, llvm::object::coff_symbol_generic::Offset, llvm::object::coff_symbol_generic::ShortName, and llvm::object::StringTableOffset::Zeroes.
getSymbolSection()
Expected< section_iterator > COFFObjectFile::getSymbolSection (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 249 of file COFFObjectFile.cpp.
References llvm::errorCodeToError(), getCOFFSymbol(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::isReservedSectionNumber(), llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, section_end(), and llvm::object::ObjectFile::SectionRef.
getSymbolSectionID()
unsigned COFFObjectFile::getSymbolSectionID (SymbolRef Sym) const
Definition at line 261 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::COFFSymbolRef::getSectionNumber().
getSymbolTable()
uintptr_t llvm::object::COFFObjectFile::getSymbolTable () const inline
Definition at line 806 of file COFF.h.
Referenced by getSymbolIndex(), and symbol_begin().
getSymbolTableEntrySize()
size_t llvm::object::COFFObjectFile::getSymbolTableEntrySize () const inline
Definition at line 1031 of file COFF.h.
References Info, llvm_unreachable, Name, and Size.
Referenced by getSymbolAuxData(), getSymbolIndex(), and section_rel_end().
getSymbolType()
Expected< SymbolRef::Type > COFFObjectFile::getSymbolType (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 189 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getComplexType(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::IMAGE_SYM_DEBUG, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::COFF::isReservedSectionNumber(), llvm::object::COFFSymbolRef::isSectionDefinition(), llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_File, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, and llvm::object::SymbolRef::ST_Unknown.
getSymbolValueImpl()
uint64_t COFFObjectFile::getSymbolValueImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 157 of file COFFObjectFile.cpp.
References getCOFFSymbol(), and llvm::object::COFFSymbolRef::getValue().
getTimeDateStamp()
uint32_t llvm::object::COFFObjectFile::getTimeDateStamp () const inline
Definition at line 842 of file COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::TimeDateStamp, and llvm::object::coff_bigobj_file_header::TimeDateStamp.
getVaPtr()
std::error_code COFFObjectFile::getVaPtr (uint64_t VA, uintptr_t & Res) const
Definition at line 449 of file COFFObjectFile.cpp.
References assert(), getImageBase(), and getRvaPtr().
import_directories()
iterator_range< import_directory_iterator > COFFObjectFile::import_directories () const
Definition at line 920 of file COFFObjectFile.cpp.
References import_directory_begin(), import_directory_end(), and llvm::make_range().
import_directory_begin()
import_directory_iterator COFFObjectFile::import_directory_begin () const
Definition at line 817 of file COFFObjectFile.cpp.
References import_directory_end(), ImportDirectoryEntryRef, and llvm::object::coff_import_directory_table_entry::isNull().
Referenced by import_directories().
import_directory_end()
import_directory_iterator COFFObjectFile::import_directory_end () const
Definition at line 826 of file COFFObjectFile.cpp.
References ImportDirectoryEntryRef.
Referenced by import_directories(), and import_directory_begin().
is64()
bool llvm::object::COFFObjectFile::is64 () const inline
Definition at line 1072 of file COFF.h.
isRelocatableObject()
bool COFFObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 1284 of file COFFObjectFile.cpp.
isSectionBSS()
bool COFFObjectFile::isSectionBSS (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 323 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_READ, and llvm::COFF::IMAGE_SCN_MEM_WRITE.
isSectionCompressed()
bool COFFObjectFile::isSectionCompressed (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 309 of file COFFObjectFile.cpp.
isSectionData()
bool COFFObjectFile::isSectionData (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 318 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA.
isSectionText()
bool COFFObjectFile::isSectionText (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 313 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::COFF::IMAGE_SCN_CNT_CODE.
isSectionVirtual()
bool COFFObjectFile::isSectionVirtual (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 338 of file COFFObjectFile.cpp.
References llvm::object::coff_section::PointerToRawData.
mapDebugSectionName()
StringRef COFFObjectFile::mapDebugSectionName (StringRef Name) const override virtual
Maps a debug section name to a standard DWARF section name.
Reimplemented from llvm::object::ObjectFile.
Definition at line 1288 of file COFFObjectFile.cpp.
References llvm::StringSwitch< T, R >::Default(), Name, and llvm::object::ImportDirectoryEntryRef::operator==().
moveRelocationNext()
void COFFObjectFile::moveRelocationNext (DataRefImpl & Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1120 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
moveSectionNext()
void COFFObjectFile::moveSectionNext (DataRefImpl & Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 266 of file COFFObjectFile.cpp.
References getSectionName(), and llvm::object::DataRefImpl::p.
moveSymbolNext()
void COFFObjectFile::moveSymbolNext (DataRefImpl & Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 134 of file COFFObjectFile.cpp.
section_begin()
section_iterator COFFObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 857 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SectionRef.
section_end()
section_iterator COFFObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 863 of file COFFObjectFile.cpp.
References getNumberOfSections(), llvm::object::coff_file_header::isImportLibrary(), llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SectionRef.
Referenced by getSymbolSection().
section_rel_begin()
relocation_iterator COFFObjectFile::section_rel_begin (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 380 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::sys::path::begin(), llvm::object::Binary::Data, getFirstReloc(), llvm::object::DataRefImpl::p, llvm::object::ObjectFile::RelocationRef, llvm::report_fatal_error(), llvm::MipsISD::Ret, and llvm::object::coff_section::VirtualAddress.
section_rel_end()
relocation_iterator COFFObjectFile::section_rel_end (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 390 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), getNumberOfRelocations(), getNumberOfSymbols(), llvm::object::getObject(), getPointerToSymbolTable(), getSymbolTableEntrySize(), I, llvm::object::DataRefImpl::p, llvm::object::parse_failed, llvm::object::ObjectFile::RelocationRef, and llvm::MipsISD::Ret.
symbol_begin()
basic_symbol_iterator COFFObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 804 of file COFFObjectFile.cpp.
References getSymbolTable(), llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SymbolRef.
symbol_end()
basic_symbol_iterator COFFObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 810 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SymbolRef.
Referenced by getRelocationSymbol().
toSymb()
template<typename coff_symbol_type > const coff_symbol_type* llvm::object::COFFObjectFile::toSymb (DataRefImpl Ref) const
Definition at line 102 of file COFFObjectFile.cpp.
References assert(), llvm::object::ObjectFile::base(), llvm::object::Binary::checkOffset(), llvm::object::Binary::Data, getNumberOfSections(), getPointerToSymbolTable(), llvm::object::DataRefImpl::p, llvm::Ref, and llvm::report_fatal_error().
Friends And Related Function Documentation
ExportDirectoryEntryRef
friend class ExportDirectoryEntryRef friend
Definition at line 768 of file COFF.h.
Referenced by export_directory_begin(), and export_directory_end().
ImportDirectoryEntryRef
friend class ImportDirectoryEntryRef friend
Definition at line 767 of file COFF.h.
Referenced by import_directory_begin(), and import_directory_end().
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp