LLVM: llvm::LiveDebugVariables Class Reference
llvm::LiveDebugVariables Class Reference
#include "CodeGen/LiveDebugVariables.h"
Public Member Functions
LiveDebugVariables ()
~LiveDebugVariables () override
void splitRegister (unsigned OldReg, ArrayRef< unsigned > NewRegs, LiveIntervals &LIS)
splitRegister - Move any user variables in OldReg to the live ranges in NewRegs where they are live.
void emitDebugValues (VirtRegMap *VRM)
emitDebugValues - Emit new DBG_VALUE instructions reflecting the changes that happened during register allocation.
void dump () const
dump - Print data structures to dbgs().
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 32 of file LiveDebugVariables.h.
Constructor & Destructor Documentation
LiveDebugVariables()
LiveDebugVariables::LiveDebugVariables ()
Definition at line 93 of file LiveDebugVariables.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeLiveDebugVariablesPass().
~LiveDebugVariables()
LiveDebugVariables::~LiveDebugVariables () override
Definition at line 1031 of file LiveDebugVariables.cpp.
References llvm::LiveRange::advanceTo(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo(), assert(), llvm::LiveRange::begin(), llvm::LiveRange::beginIndex(), DbgValueLocation::changeLocNo(), llvm::MachineOperand::CreateReg(), llvm::dbgs(), llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::find(), llvm::LiveIntervals::getInterval(), llvm::MachineOperand::getReg(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert(), llvm::MachineOperand::isReg(), LLVM_DEBUG, llvm::Pass::print(), llvm::LiveInterval::reg, llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setMap(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStartUnchecked(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStopUnchecked(), llvm::MachineOperand::setSubReg(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue(), llvm::ArrayRef< T >::size(), splitRegister(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::start(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::stop(), UndefLocNo, llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::value().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void LiveDebugVariables::dump () const
dump - Print data structures to dbgs().
Definition at line 1451 of file LiveDebugVariables.cpp.
References llvm::dbgs(), and llvm::Pass::print().
emitDebugValues()
void LiveDebugVariables::emitDebugValues (VirtRegMap * VRM)
emitDebugValues - Emit new DBG_VALUE instructions reflecting the changes that happened during register allocation.
Parameters
VRM Rename virtual registers according to map.
Definition at line 1441 of file LiveDebugVariables.cpp.
References llvm::Pass::doInitialization().
splitRegister()
void LiveDebugVariables::splitRegister (unsigned OldReg, ArrayRef< unsigned > NewRegs, LiveIntervals & LIS)
splitRegister - Move any user variables in OldReg to the live ranges in NewRegs where they are live.
Mark the values as unavailable where no new register is live.
Definition at line 1167 of file LiveDebugVariables.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::begin(), DbgValueLocation::changeLocNo(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::MachineOperand::CreateFI(), E, llvm::VirtRegMap::getPhys(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::VirtRegMap::getStackSlot(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::MachineOperand::getSubReg(), I, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert(), llvm::VirtRegMap::isAssignedReg(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), DbgValueLocation::isUndef(), llvm::Register::isVirtualRegister(), DbgValueLocation::locNo(), llvm::VirtRegMap::NO_STACK_SLOT, llvm::MachineOperand::setReg(), llvm::MachineOperand::setSubReg(), llvm::MachineOperand::substPhysReg(), Success, TII, and TRI.
Referenced by getNumAllocatableRegsForConstraints(), and ~LiveDebugVariables().
Member Data Documentation
ID
char LiveDebugVariables::ID = 0 static
Definition at line 36 of file LiveDebugVariables.h.
The documentation for this class was generated from the following files:
lib/CodeGen/LiveDebugVariables.h
lib/CodeGen/LiveDebugVariables.cpp