LLVM: llvm::ValueMapCallbackVH< KeyT, ValueT, Config > Class Template Reference
llvm::ValueMapCallbackVH< KeyT, ValueT, Config > Class Template Reference
#include "llvm/IR/ValueMap.h"
Public Member Functions
KeyT Unwrap () const
void deleted () override
Callback for Value destruction.
void allUsesReplacedWith (Value *new_key) override
Callback for Value RAUW.
Public Member Functions inherited from llvm::CallbackVH
CallbackVH ()
CallbackVH (Value *P)
operator Value * () const
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Friends
class ValueMap< KeyT, ValueT, Config >
struct DenseMapInfo< ValueMapCallbackVH >
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert, Callback, Weak, WeakTracking }
This indicates what sub class the handle actually is.
Protected Member Functions inherited from llvm::CallbackVH
~CallbackVH ()=default
CallbackVH (const CallbackVH &)=default
CallbackVH & operator= (const CallbackVH &)=default
void setValPtr (Value *P)
Protected Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (const ValueHandleBase &RHS)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
Value * getValPtr () const
void RemoveFromUseList ()
Remove this ValueHandle from its current use list.
void clearValPtr ()
Clear the underlying pointer without clearing the use list.
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
template<typename KeyT, typename ValueT, typename Config>
class llvm::ValueMapCallbackVH< KeyT, ValueT, Config >
Definition at line 47 of file ValueMap.h.
Member Function Documentation
allUsesReplacedWith()
template<typename KeyT , typename ValueT , typename Config > void llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith (Value *) inline override virtual
Callback for Value RAUW.
Called when this->getValPtr()->replaceAllUsesWith(new_value) is called, before any of the uses have actually been replaced. If WeakTrackingVH were implemented as a CallbackVH, it would use this method to call setValPtr(new_value). AssertingVH would do nothing in this method.
Reimplemented from llvm::CallbackVH.
Definition at line 271 of file ValueMap.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, llvm::ValueMap< KeyT, ValueT, Config >::insert(), llvm::ValueMapIterator< DenseMapT, KeyT >::ValueTypeProxy::second, and llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::Unwrap().
deleted()
template<typename KeyT , typename ValueT , typename Config > void llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::deleted () inline override virtual
Callback for Value destruction.
Called when this->getValPtr() is destroyed, inside ~Value(), so you may call any non-virtual Value method on getValPtr(), but no subclass methods. If WeakTrackingVH were implemented as a CallbackVH, it would use this method to call setValPtr(NULL). AssertingVH would use this method to cause an assertion failure.
All implementations must remove the reference from this object to the Value that's being destroyed.
Reimplemented from llvm::CallbackVH.
Definition at line 260 of file ValueMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), and llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::Unwrap().
Unwrap()
template<typename KeyT , typename ValueT , typename Config > KeyT llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::Unwrap () const inline
Definition at line 258 of file ValueMap.h.
Referenced by llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::deleted(), and llvm::DenseMapInfo< ValueMapCallbackVH< KeyT, ValueT, Config > >::getHashValue().
Friends And Related Function Documentation
DenseMapInfo< ValueMapCallbackVH >
template<typename KeyT , typename ValueT , typename Config > friend struct DenseMapInfo< ValueMapCallbackVH > friend
Definition at line 243 of file ValueMap.h.
ValueMap< KeyT, ValueT, Config >
template<typename KeyT , typename ValueT , typename Config > friend class ValueMap< KeyT, ValueT, Config > friend
Definition at line 242 of file ValueMap.h.
The documentation for this class was generated from the following file:
include/llvm/IR/ValueMap.h