LLVM: llvm::NVPTXMachineFunctionInfo Class Reference
llvm::NVPTXMachineFunctionInfo Class Reference
#include "Target/NVPTX/NVPTXMachineFunctionInfo.h"
Public Member Functions
NVPTXMachineFunctionInfo (MachineFunction &MF)
unsigned getImageHandleSymbolIndex (const char *Symbol)
Returns the index for the symbol Symbol.
const char * getImageHandleSymbol (unsigned Idx) const
Returns the symbol name at the given index.
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 20 of file NVPTXMachineFunctionInfo.h.
Constructor & Destructor Documentation
NVPTXMachineFunctionInfo()
llvm::NVPTXMachineFunctionInfo::NVPTXMachineFunctionInfo (MachineFunction & MF) inline
Definition at line 27 of file NVPTXMachineFunctionInfo.h.
Member Function Documentation
getImageHandleSymbol()
const char* llvm::NVPTXMachineFunctionInfo::getImageHandleSymbol (unsigned Idx) const inline
Returns the symbol name at the given index.
Definition at line 43 of file NVPTXMachineFunctionInfo.h.
References assert(), and llvm::SmallVectorBase::size().
Referenced by VisitGlobalVariableForEmission().
getImageHandleSymbolIndex()
unsigned llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex (const char * Symbol) inline
Returns the index for the symbol Symbol.
If the symbol was previously, added, the same index is returned. Otherwise, the symbol is added and the new index is returned.
Definition at line 32 of file NVPTXMachineFunctionInfo.h.
References llvm::numbers::e, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase::size().
The documentation for this class was generated from the following file:
lib/Target/NVPTX/NVPTXMachineFunctionInfo.h