LLVM: PODSmallVector< T, N > Class Template Reference
PODSmallVector< T, N > Class Template Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
PODSmallVector ()
PODSmallVector (const PODSmallVector &)=delete
PODSmallVector & operator= (const PODSmallVector &)=delete
PODSmallVector (PODSmallVector &&Other)
PODSmallVector & operator= (PODSmallVector &&Other)
void push_back (const T &Elem)
void pop_back ()
void dropBack (size_t Index)
T * begin ()
T * end ()
bool empty () const
size_t size () const
T & back ()
T & operator[] (size_t Index)
void clear ()
~PODSmallVector ()
Detailed Description
template<class T, size_t N>
class PODSmallVector< T, N >
Definition at line 2172 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
PODSmallVector() [1/3]
template<class T, size_t N> PODSmallVector< T, N >::PODSmallVector () inline
Definition at line 2207 of file ItaniumDemangle.h.
PODSmallVector() [2/3]
template<class T, size_t N> PODSmallVector< T, N >::PODSmallVector (const PODSmallVector< T, N > &) delete
PODSmallVector() [3/3]
template<class T, size_t N> PODSmallVector< T, N >::PODSmallVector (PODSmallVector< T, N > && Other) inline
Definition at line 2212 of file ItaniumDemangle.h.
~PODSmallVector()
template<class T, size_t N> PODSmallVector< T, N >::~PODSmallVector () inline
Definition at line 2284 of file ItaniumDemangle.h.
Member Function Documentation
back()
template<class T, size_t N> T& PODSmallVector< T, N >::back () inline
Definition at line 2274 of file ItaniumDemangle.h.
begin()
template<class T, size_t N> T* PODSmallVector< T, N >::begin () inline
Definition at line 2269 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< ManglingParser< Alloc >, Alloc >::popTrailingNodeArray().
clear()
template<class T, size_t N> void PODSmallVector< T, N >::clear () inline
Definition at line 2282 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< ManglingParser< Alloc >, Alloc >::reset().
dropBack()
template<class T, size_t N> void PODSmallVector< T, N >::dropBack (size_t Index) inline
Definition at line 2264 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< ManglingParser< Alloc >, Alloc >::popTrailingNodeArray(), and AbstractManglingParser< ManglingParser< Alloc >, Alloc >::resolveForwardTemplateRefs().
empty()
template<class T, size_t N> bool PODSmallVector< T, N >::empty () const inline
Definition at line 2272 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< ManglingParser< Alloc >, Alloc >::resolveForwardTemplateRefs().
end()
template<class T, size_t N> T* PODSmallVector< T, N >::end () inline
Definition at line 2270 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< ManglingParser< Alloc >, Alloc >::popTrailingNodeArray().
operator=() [1/2]
template<class T, size_t N> PODSmallVector& PODSmallVector< T, N >::operator= (const PODSmallVector< T, N > &) delete
operator=() [2/2]
template<class T, size_t N> PODSmallVector& PODSmallVector< T, N >::operator= (PODSmallVector< T, N > && Other) inline
Definition at line 2226 of file ItaniumDemangle.h.
operator[]()
template<class T, size_t N> T& PODSmallVector< T, N >::operator[] (size_t Index) inline
Definition at line 2278 of file ItaniumDemangle.h.
pop_back()
template<class T, size_t N> void PODSmallVector< T, N >::pop_back () inline
Definition at line 2259 of file ItaniumDemangle.h.
push_back()
template<class T, size_t N> void PODSmallVector< T, N >::push_back (const T & Elem) inline
Definition at line 2253 of file ItaniumDemangle.h.
size()
template<class T, size_t N> size_t PODSmallVector< T, N >::size () const inline
Definition at line 2273 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< ManglingParser< Alloc >, Alloc >::popTrailingNodeArray(), and AbstractManglingParser< ManglingParser< Alloc >, Alloc >::resolveForwardTemplateRefs().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h