LLVM: llvm::GCOVProfilerPass Class Reference
llvm::GCOVProfilerPass Class Reference
The gcov-style instrumentation pass.
#include "llvm/Transforms/Instrumentation/GCOVProfiler.h"
Public Member Functions
GCOVProfilerPass (const GCOVOptions &Options=GCOVOptions::getDefault())
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GCOVProfilerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The gcov-style instrumentation pass.
Definition at line 20 of file GCOVProfiler.h.
Constructor & Destructor Documentation
GCOVProfilerPass()
llvm::GCOVProfilerPass::GCOVProfilerPass (const GCOVOptions & Options = GCOVOptions::getDefault()) inline
Definition at line 22 of file GCOVProfiler.h.
References run().
Member Function Documentation
run()
PreservedAnalyses GCOVProfilerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 578 of file GCOVProfiling.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
Referenced by GCOVProfilerPass().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/GCOVProfiler.h
lib/Transforms/Instrumentation/GCOVProfiling.cpp