LLVM: llvm::HexagonInstPrinter Class Reference
llvm::HexagonInstPrinter Class Reference
Prints bundles as a newline separated list of individual instructions Duplexes are separated by a vertical tab character A trailing line includes bundle properties such as endloop0/1.
#include "Target/Hexagon/MCTargetDesc/HexagonInstPrinter.h"
Public Member Functions
HexagonInstPrinter (MCAsmInfo const &MAI, MCInstrInfo const &MII, MCRegisterInfo const &MRI)
void printInst (MCInst const *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &O, unsigned RegNo) const override
Print the assembler register name.
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printOperand (MCInst const *MI, unsigned OpNo, raw_ostream &O) const
void printBrtarget (MCInst const *MI, unsigned OpNo, raw_ostream &O) const
MCAsmInfo const & getMAI () const
MCInstrInfo const & getMII () const
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static char const * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Prints bundles as a newline separated list of individual instructions Duplexes are separated by a vertical tab character A trailing line includes bundle properties such as endloop0/1.
r0 = add(r1, r2) r0 = #0 jump 0x0 :endloop0 :endloop1
Definition at line 25 of file HexagonInstPrinter.h.
Constructor & Destructor Documentation
HexagonInstPrinter()
llvm::HexagonInstPrinter::HexagonInstPrinter (MCAsmInfo const & MAI, MCInstrInfo const & MII, MCRegisterInfo const & MRI) inline explicit
Definition at line 27 of file HexagonInstPrinter.h.
References llvm::Address, getRegisterName(), MI, llvm::RISCVFenceField::O, printBrtarget(), printInst(), printInstruction(), printOperand(), and printRegName().
Member Function Documentation
getMAI()
MCAsmInfo const& llvm::HexagonInstPrinter::getMAI () const inline
Definition at line 41 of file HexagonInstPrinter.h.
References llvm::MCInstPrinter::MAI.
getMII()
MCInstrInfo const& llvm::HexagonInstPrinter::getMII () const inline
Definition at line 42 of file HexagonInstPrinter.h.
getRegisterName()
static char const* llvm::HexagonInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by HexagonInstPrinter(), llvm::HexagonAsmPrinter::PrintAsmOperand(), printOperand(), llvm::HexagonAsmPrinter::printOperand(), and printRegName().
printBrtarget()
void HexagonInstPrinter::printBrtarget (MCInst const * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 81 of file HexagonInstPrinter.cpp.
References assert(), llvm::format(), llvm::MCOperand::getExpr(), llvm::HexagonMCInstrInfo::getExtendableOp(), llvm::MCInst::getOperand(), llvm::HexagonMCInstrInfo::isConstExtended(), and llvm::MCOperand::isExpr().
Referenced by HexagonInstPrinter().
printInst()
void HexagonInstPrinter::printInst (MCInst const * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 33 of file HexagonInstPrinter.cpp.
References llvm::Address, assert(), llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::HexagonMCInstrInfo::bundleSize(), llvm::MCOperand::getInst(), llvm::MCInst::getOperand(), HEXAGON_PACKET_SIZE, I, llvm::HexagonMCInstrInfo::isBundle(), llvm::HexagonMCInstrInfo::isDuplex(), llvm::HexagonMCInstrInfo::isImmext(), llvm::HexagonMCInstrInfo::isInnerLoop(), llvm::HexagonMCInstrInfo::isOuterLoop(), and printInstruction().
Referenced by HexagonInstPrinter().
printInstruction()
void llvm::HexagonInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by HexagonInstPrinter(), and printInst().
printOperand()
void HexagonInstPrinter::printOperand (MCInst const * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 62 of file HexagonInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getExpr(), llvm::HexagonMCInstrInfo::getExtendableOp(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::MCOperand::isExpr(), llvm::MCOperand::isReg(), and llvm_unreachable.
Referenced by HexagonInstPrinter().
printRegName()
void HexagonInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 29 of file HexagonInstPrinter.cpp.
References getRegisterName().
Referenced by HexagonInstPrinter().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonInstPrinter.h
lib/Target/Hexagon/MCTargetDesc/HexagonInstPrinter.cpp