LLVM: llvm::sys::DynamicLibrary::HandleSet Class Reference
llvm::sys::DynamicLibrary::HandleSet Class Reference
Public Member Functions
HandleSet ()
~HandleSet ()
HandleList::iterator Find (void *Handle)
bool Contains (void *Handle)
bool AddLibrary (void *Handle, bool IsProcess=false, bool CanClose=true)
void * LibLookup (const char *Symbol, DynamicLibrary::SearchOrdering Order)
void * Lookup (const char *Symbol, DynamicLibrary::SearchOrdering Order)
Static Public Member Functions
static void * DLOpen (const char *Filename, std::string *Err)
static void DLClose (void *Handle)
static void * DLSym (void *Handle, const char *Symbol)
Detailed Description
Definition at line 29 of file DynamicLibrary.cpp.
Constructor & Destructor Documentation
HandleSet()
llvm::sys::DynamicLibrary::HandleSet::HandleSet () inline
Definition at line 39 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::HandleSet::~HandleSet().
~HandleSet()
llvm::sys::DynamicLibrary::HandleSet::~HandleSet ()
Referenced by llvm::sys::DynamicLibrary::HandleSet::HandleSet().
Member Function Documentation
AddLibrary()
bool llvm::sys::DynamicLibrary::HandleSet::AddLibrary (void * Handle, bool IsProcess = false, bool CanClose = true) inline
Definition at line 50 of file DynamicLibrary.cpp.
References assert(), llvm::sys::DynamicLibrary::HandleSet::DLClose(), llvm::sys::DynamicLibrary::HandleSet::Find(), and LLVM_LIKELY.
Contains()
bool llvm::sys::DynamicLibrary::HandleSet::Contains (void * Handle) inline
Definition at line 46 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::HandleSet::Find().
DLClose()
static void llvm::sys::DynamicLibrary::HandleSet::DLClose (void * Handle) static
Referenced by llvm::sys::DynamicLibrary::HandleSet::AddLibrary().
DLOpen()
static void* llvm::sys::DynamicLibrary::HandleSet::DLOpen (const char * Filename, std::string * Err) static
DLSym()
static void* llvm::sys::DynamicLibrary::HandleSet::DLSym (void * Handle, const char * Symbol) static
Referenced by llvm::sys::DynamicLibrary::getAddressOfSymbol(), llvm::sys::DynamicLibrary::HandleSet::LibLookup(), and llvm::sys::DynamicLibrary::HandleSet::Lookup().
Find()
HandleList::iterator llvm::sys::DynamicLibrary::HandleSet::Find (void * Handle) inline
Definition at line 42 of file DynamicLibrary.cpp.
References llvm::find().
Referenced by llvm::sys::DynamicLibrary::HandleSet::AddLibrary(), and llvm::sys::DynamicLibrary::HandleSet::Contains().
LibLookup()
void* llvm::sys::DynamicLibrary::HandleSet::LibLookup (const char * Symbol, DynamicLibrary::SearchOrdering Order) inline
Definition at line 76 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::HandleSet::DLSym(), llvm::reverse(), and llvm::sys::DynamicLibrary::SO_LoadOrder.
Referenced by llvm::sys::DynamicLibrary::HandleSet::Lookup().
Lookup()
void* llvm::sys::DynamicLibrary::HandleSet::Lookup (const char * Symbol, DynamicLibrary::SearchOrdering Order) inline
Definition at line 91 of file DynamicLibrary.cpp.
References assert(), llvm::sys::DynamicLibrary::HandleSet::DLSym(), llvm::sys::DynamicLibrary::HandleSet::LibLookup(), llvm::sys::DynamicLibrary::SearchOrder, llvm::sys::DynamicLibrary::SO_Linker, llvm::sys::DynamicLibrary::SO_LoadedFirst, and llvm::sys::DynamicLibrary::SO_LoadedLast.
The documentation for this class was generated from the following file:
lib/Support/DynamicLibrary.cpp