LLVM: llvm::PassInstrumentationCallbacks Class Reference
llvm::PassInstrumentationCallbacks Class Reference
This class manages callbacks registration, as well as provides a way for PassInstrumentation to pass control to the registered callbacks.
#include "llvm/IR/PassInstrumentation.h"
Public Types
using BeforePassFunc = bool(StringRef, Any)
using AfterPassFunc = void(StringRef, Any)
using AfterPassInvalidatedFunc = void(StringRef)
using BeforeAnalysisFunc = void(StringRef, Any)
using AfterAnalysisFunc = void(StringRef, Any)
Public Member Functions
PassInstrumentationCallbacks ()
PassInstrumentationCallbacks (const PassInstrumentationCallbacks &)=delete
Copying PassInstrumentationCallbacks is not intended.
void operator= (const PassInstrumentationCallbacks &)=delete
template<typename CallableT >
void registerBeforePassCallback (CallableT C)
template<typename CallableT >
void registerAfterPassCallback (CallableT C)
template<typename CallableT >
void registerAfterPassInvalidatedCallback (CallableT C)
template<typename CallableT >
void registerBeforeAnalysisCallback (CallableT C)
template<typename CallableT >
void registerAfterAnalysisCallback (CallableT C)
Friends
class PassInstrumentation
Detailed Description
This class manages callbacks registration, as well as provides a way for PassInstrumentation to pass control to the registered callbacks.
Definition at line 68 of file PassInstrumentation.h.
Member Typedef Documentation
AfterAnalysisFunc
using llvm::PassInstrumentationCallbacks::AfterAnalysisFunc = void(StringRef, Any)
Definition at line 82 of file PassInstrumentation.h.
AfterPassFunc
using llvm::PassInstrumentationCallbacks::AfterPassFunc = void(StringRef, Any)
Definition at line 79 of file PassInstrumentation.h.
AfterPassInvalidatedFunc
using llvm::PassInstrumentationCallbacks::AfterPassInvalidatedFunc = void(StringRef)
Definition at line 80 of file PassInstrumentation.h.
BeforeAnalysisFunc
using llvm::PassInstrumentationCallbacks::BeforeAnalysisFunc = void(StringRef, Any)
Definition at line 81 of file PassInstrumentation.h.
BeforePassFunc
using llvm::PassInstrumentationCallbacks::BeforePassFunc = bool(StringRef, Any)
Definition at line 78 of file PassInstrumentation.h.
Constructor & Destructor Documentation
PassInstrumentationCallbacks() [1/2]
llvm::PassInstrumentationCallbacks::PassInstrumentationCallbacks () inline
Definition at line 85 of file PassInstrumentation.h.
References operator=().
PassInstrumentationCallbacks() [2/2]
llvm::PassInstrumentationCallbacks::PassInstrumentationCallbacks (const PassInstrumentationCallbacks &) delete
Copying PassInstrumentationCallbacks is not intended.
Member Function Documentation
operator=()
void llvm::PassInstrumentationCallbacks::operator= (const PassInstrumentationCallbacks &) delete
Referenced by PassInstrumentationCallbacks().
registerAfterAnalysisCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback (CallableT C) inline
Definition at line 110 of file PassInstrumentation.h.
References llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::TimePassesHandler::registerCallbacks().
registerAfterPassCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAfterPassCallback (CallableT C) inline
Definition at line 95 of file PassInstrumentation.h.
References llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PrintIRInstrumentation::registerCallbacks(), and llvm::TimePassesHandler::registerCallbacks().
registerAfterPassInvalidatedCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback (CallableT C) inline
Definition at line 100 of file PassInstrumentation.h.
References llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PrintIRInstrumentation::registerCallbacks(), and llvm::TimePassesHandler::registerCallbacks().
registerBeforeAnalysisCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback (CallableT C) inline
Definition at line 105 of file PassInstrumentation.h.
References llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::TimePassesHandler::registerCallbacks().
registerBeforePassCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerBeforePassCallback (CallableT C) inline
Definition at line 91 of file PassInstrumentation.h.
References llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PrintIRInstrumentation::registerCallbacks(), and llvm::TimePassesHandler::registerCallbacks().
Friends And Related Function Documentation
PassInstrumentation
friend class PassInstrumentation friend
Definition at line 115 of file PassInstrumentation.h.
The documentation for this class was generated from the following file:
include/llvm/IR/PassInstrumentation.h