LLVM: llvm::AttributeListImpl Class Reference
llvm::AttributeListImpl Class Reference final
#include "IR/AttributeImpl.h"
Public Types
using iterator = const AttributeSet *
Public Member Functions
AttributeListImpl (LLVMContext &C, ArrayRef< AttributeSet > Sets)
AttributeListImpl (const AttributeListImpl &)=delete
AttributeListImpl & operator= (const AttributeListImpl &)=delete
void operator delete (void *p)
LLVMContext & getContext ()
Get the context that created this AttributeListImpl.
bool hasFnAttribute (Attribute::AttrKind Kind) const
Return true if the AttributeSet or the FunctionIndex has an enum attribute of the given kind.
iterator begin () const
iterator end () const
void Profile (FoldingSetNodeID &ID) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, ArrayRef< AttributeSet > Nodes)
Friends
class AttributeList
Detailed Description
Definition at line 240 of file AttributeImpl.h.
Member Typedef Documentation
iterator
using llvm::AttributeListImpl::iterator = const AttributeSet *
Definition at line 273 of file AttributeImpl.h.
Constructor & Destructor Documentation
AttributeListImpl() [1/2]
AttributeListImpl::AttributeListImpl (LLVMContext & C, ArrayRef< AttributeSet > Sets)
Definition at line 903 of file Attributes.cpp.
References assert(), attrIdxToArrayIdx(), llvm::copy(), llvm::ArrayRef< T >::empty(), llvm::Attribute::EndAttrKinds, llvm::AttributeList::FunctionIndex, and I.
Referenced by dump().
AttributeListImpl() [2/2]
llvm::AttributeListImpl::AttributeListImpl (const AttributeListImpl &) delete
Member Function Documentation
begin()
iterator llvm::AttributeListImpl::begin () const inline
Definition at line 275 of file AttributeImpl.h.
Referenced by llvm::AttributeList::addAttributes(), llvm::AttributeList::addParamAttribute(), Profile(), llvm::AttributeList::removeAttribute(), and llvm::AttributeList::removeAttributes().
dump()
LLVM_DUMP_METHOD void AttributeListImpl::dump () const
Definition at line 936 of file Attributes.cpp.
References assert(), AttributeList, AttributeListImpl(), C, llvm::ArrayRef< T >::empty(), getImpl(), llvm::LLVMContext::pImpl, Profile(), and llvm::ArrayRef< T >::size().
end()
iterator llvm::AttributeListImpl::end () const inline
Definition at line 276 of file AttributeImpl.h.
References llvm::sys::path::begin(), llvm::dump(), and llvm::AttributeImpl::Profile().
Referenced by llvm::AttributeList::addAttributes(), llvm::AttributeList::addParamAttribute(), Profile(), llvm::AttributeList::removeAttribute(), and llvm::AttributeList::removeAttributes().
getContext()
LLVMContext& llvm::AttributeListImpl::getContext () inline
Get the context that created this AttributeListImpl.
Definition at line 265 of file AttributeImpl.h.
References Context.
hasFnAttribute()
bool llvm::AttributeListImpl::hasFnAttribute (Attribute::AttrKind Kind) const inline
Return true if the AttributeSet or the FunctionIndex has an enum attribute of the given kind.
Definition at line 269 of file AttributeImpl.h.
operator delete()
void llvm::AttributeListImpl::operator delete (void * p) inline
Definition at line 262 of file AttributeImpl.h.
operator=()
AttributeListImpl& llvm::AttributeListImpl::operator= (const AttributeListImpl &) delete
Profile() [1/2]
void AttributeListImpl::Profile (FoldingSetNodeID & ID) const
Definition at line 925 of file Attributes.cpp.
References begin(), end(), and llvm::makeArrayRef().
Referenced by dump().
Profile() [2/2]
void AttributeListImpl::Profile (FoldingSetNodeID & ID, ArrayRef< AttributeSet > Nodes) static
Definition at line 929 of file Attributes.cpp.
References llvm::FoldingSetNodeID::AddPointer().
Friends And Related Function Documentation
AttributeList
friend class AttributeList friend
Definition at line 243 of file AttributeImpl.h.
Referenced by dump().
The documentation for this class was generated from the following files:
lib/IR/AttributeImpl.h
lib/IR/Attributes.cpp