LLVM: llvm::StoreInfo Class Reference
llvm::StoreInfo Class Reference
Public Member Functions
void insert (StoreInst *Store, GVN::ValueTable &VN)
const VNtoInsns & getVNTable () const
Detailed Description
Definition at line 198 of file GVNHoist.cpp.
Member Function Documentation
getVNTable()
const VNtoInsns& llvm::StoreInfo::getVNTable () const inline
Definition at line 213 of file GVNHoist.cpp.
insert()
void llvm::StoreInfo::insert (StoreInst * Store, GVN::ValueTable & VN) inline
Definition at line 204 of file GVNHoist.cpp.
References llvm::StoreInst::getPointerOperand(), llvm::StoreInst::getValueOperand(), llvm::StoreInst::isSimple(), and llvm::GVN::ValueTable::lookupOrAdd().
The documentation for this class was generated from the following file:
lib/Transforms/Scalar/GVNHoist.cpp