LLVM: llvm::DwarfDebug Class Reference
llvm::DwarfDebug Class Reference
Collects and handles dwarf debug information.
#include "CodeGen/AsmPrinter/DwarfDebug.h"
Classes
class NonTypeUnitContext
Public Member Functions
DwarfDebug (AsmPrinter *A, Module *M)
~DwarfDebug () override
void beginModule ()
Emit all Dwarf sections that should come prior to the content.
void endModule () override
Emit all Dwarf sections that should come after the content.
DebugLoc emitInitialLocDirective (const MachineFunction &MF, unsigned CUID)
Emits inital debug location directive.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void addDwarfTypeUnitType (DwarfCompileUnit &CU, StringRef Identifier, DIE &Die, const DICompositeType *CTy)
Add a DIE to the set of types that we're going to pull into type units.
NonTypeUnitContext enterNonTypeUnitContext ()
void addArangeLabel (SymbolCU SCU)
Add a label so that arange data can be generated for it.
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
bool useAllLinkageNames () const
Returns whether we should emit all DW_AT_[MIPS_]linkage_name.
bool useGNUTLSOpcode () const
Returns whether to use DW_OP_GNU_push_tls_address, instead of the standard DW_OP_form_tls_address opcode.
bool useDWARF2Bitfields () const
Returns whether to use the DWARF2 format for bitfields instyead of the DWARF4 format.
bool useInlineStrings () const
Returns whether to use inline strings.
bool useRangesSection () const
Returns whether ranges section should be emitted.
bool useSectionsAsReferences () const
Returns whether to use sections as labels rather than temp symbols.
bool useLocSection () const
Returns whether .debug_loc section should be emitted.
bool generateTypeUnits () const
Returns whether to generate DWARF v4 type units.
AccelTableKind getAccelTableKind () const
Returns what kind (if any) of accelerator tables to emit.
bool useAppleExtensionAttributes () const
bool useSplitDwarf () const
Returns whether or not to change the current debug info for the split dwarf proposal support.
bool useSegmentedStringOffsetsTable () const
Returns whether to generate a string offsets table with (possibly shared) contributions from each CU and type unit.
bool shareAcrossDWOCUs () const
uint16_t getDwarfVersion () const
Returns the Dwarf Version.
const DwarfCompileUnit * getPrevCU () const
Returns the previous CU that was being updated.
void setPrevCU (const DwarfCompileUnit *PrevCU)
const DebugLocStream & getDebugLocs () const
Returns the entries for the .debug_loc section.
void emitDebugLocEntry (ByteStreamer &Streamer, const DebugLocStream::Entry &Entry, const DwarfCompileUnit *CU)
Emit an entry for the debug loc section.
void emitDebugLocEntryLocation (const DebugLocStream::Entry &Entry, const DwarfCompileUnit *CU)
Emit the location for a debug loc entry, including the size header.
void addSubprogramNames (const DICompileUnit &CU, const DISubprogram *SP, DIE &Die)
AddressPool & getAddressPool ()
void addAccelName (const DICompileUnit &CU, StringRef Name, const DIE &Die)
void addAccelObjC (const DICompileUnit &CU, StringRef Name, const DIE &Die)
void addAccelNamespace (const DICompileUnit &CU, StringRef Name, const DIE &Die)
void addAccelType (const DICompileUnit &CU, StringRef Name, const DIE &Die, char Flags)
const MachineFunction * getCurrentFunction () const
bool isLexicalScopeDIENull (LexicalScope *Scope)
A helper function to check whether the DIE for a given Scope is going to be null.
DwarfCompileUnit * lookupCU (const DIE *Die)
Find the matching DwarfCompileUnit for the given CU DIE.
const DwarfCompileUnit * lookupCU (const DIE *Die) const
bool tuneForGDB () const
bool tuneForLLDB () const
bool tuneForSCE () const
void addSectionLabel (const MCSymbol *Sym)
const MCSymbol * getSectionLabel (const MCSection *S)
Public Member Functions inherited from llvm::DebugHandlerBase
void endInstruction () override
Process end of an instruction.
void beginFunction (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunction (const MachineFunction *MF) override
Gather post-function debug information.
MCSymbol * getLabelBeforeInsn (const MachineInstr *MI)
Return Label preceding the instruction.
MCSymbol * getLabelAfterInsn (const MachineInstr *MI)
Return Label immediately following the instruction.
const MCExpr * getFunctionLocalOffsetAfterInsn (const MachineInstr *MI)
Return the function-local offset of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void markFunctionEnd ()
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void endFragment ()
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
Static Public Member Functions
static uint64_t makeTypeSignature (StringRef Identifier)
Perform an MD5 checksum of Identifier and return the lower 64 bits.
static void emitDebugLocValue (const AsmPrinter &AP, const DIBasicType *BT, const DbgValueLoc &Value, DwarfExpression &DwarfExpr)
Static Public Member Functions inherited from llvm::DebugHandlerBase
static uint64_t getBaseTypeSize (const DIType *Ty)
If this type is derived from a base type then return base type size.
Protected Member Functions
void beginFunctionImpl (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunctionImpl (const MachineFunction *MF) override
Gather and emit post-function debug information.
void skippedNonDebugFunction () override
Protected Member Functions inherited from llvm::DebugHandlerBase
DebugHandlerBase (AsmPrinter *A)
void identifyScopeMarkers ()
Indentify instructions that are marking the beginning of or ending of a scope.
void requestLabelBeforeInsn (const MachineInstr *MI)
Ensure that a label will be emitted before MI.
void requestLabelAfterInsn (const MachineInstr *MI)
Ensure that a label will be emitted after MI.
Friends
class NonTypeUnitContext
Additional Inherited Members
Protected Attributes inherited from llvm::DebugHandlerBase
AsmPrinter * Asm
Target of debug info emission.
MachineModuleInfo * MMI
Collected machine module information.
DebugLoc PrevInstLoc
Previous instruction's location information.
MCSymbol * PrevLabel = nullptr
const MachineBasicBlock * PrevInstBB = nullptr
DebugLoc PrologEndLoc
This location indicates end of function prologue and beginning of function body.
const MachineInstr * CurMI = nullptr
If nonnull, stores the current machine instruction we're processing.
LexicalScopes LScopes
DbgValueHistoryMap DbgValues
History of DBG_VALUE and clobber instructions for each user variable.
DbgLabelInstrMap DbgLabels
Mapping of inlined labels and DBG_LABEL machine instruction.
DenseMap< const MachineInstr *, MCSymbol * > LabelsBeforeInsn
Maps instruction with label emitted before instruction.
DenseMap< const MachineInstr *, MCSymbol * > LabelsAfterInsn
Maps instruction with label emitted after instruction.
Detailed Description
Collects and handles dwarf debug information.
Definition at line 297 of file DwarfDebug.h.
Constructor & Destructor Documentation
DwarfDebug()
DwarfDebug::DwarfDebug (AsmPrinter * A, Module * M)
Definition at line 348 of file DwarfDebug.cpp.
References AllLinkageNames, llvm::DebugHandlerBase::Asm, computeAccelTableKind(), llvm::TargetOptions::DebuggerTuning, llvm::Default, DefaultLinkageNames, llvm::dwarf::DWARF_VERSION, DwarfLinkageNames, llvm::MCTargetOptions::DwarfVersion, llvm::Enable, llvm::GDB, GenerateDwarfTypeUnits, llvm::Module::getDwarfVersion(), llvm::MachineModuleInfo::getModule(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isNVPTX(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isPS4CPU(), llvm::LLDB, llvm::TargetOptions::MCOptions, llvm::DebugHandlerBase::MMI, llvm::TargetMachine::Options, llvm::AsmPrinter::OutStreamer, llvm::SCE, llvm::MCTargetOptions::SplitDwarfFile, llvm::AsmPrinter::TM, llvm::TT, tuneForGDB(), tuneForLLDB(), tuneForSCE(), and ~DwarfDebug().
~DwarfDebug()
DwarfDebug::~DwarfDebug () override default
Referenced by DwarfDebug().
Member Function Documentation
addAccelName()
void DwarfDebug::addAccelName (const DICompileUnit & CU, StringRef Name, const DIE & Die)
Definition at line 3047 of file DwarfDebug.cpp.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), and addSubprogramNames().
addAccelNamespace()
void DwarfDebug::addAccelNamespace (const DICompileUnit & CU, StringRef Name, const DIE & Die)
Definition at line 3059 of file DwarfDebug.cpp.
Referenced by llvm::DwarfUnit::getOrCreateNameSpace().
addAccelObjC()
void DwarfDebug::addAccelObjC (const DICompileUnit & CU, StringRef Name, const DIE & Die)
Definition at line 3052 of file DwarfDebug.cpp.
References llvm::Apple, and getAccelTableKind().
Referenced by addSubprogramNames().
addAccelType()
void DwarfDebug::addAccelType (const DICompileUnit & CU, StringRef Name, const DIE & Die, char Flags)
Definition at line 3064 of file DwarfDebug.cpp.
Referenced by llvm::DwarfUnit::applySubprogramAttributes(), and llvm::DwarfUnit::getOrCreateTypeDIE().
addArangeLabel()
void llvm::DwarfDebug::addArangeLabel (SymbolCU SCU) inline
Add a label so that arange data can be generated for it.
Definition at line 648 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocalLabelAddress(), and llvm::DwarfCompileUnit::addLocationAttribute().
addDwarfTypeUnitType()
void DwarfDebug::addDwarfTypeUnitType (DwarfCompileUnit & CU, StringRef Identifier, DIE & Die, const DICompositeType * CTy)
Add a DIE to the set of types that we're going to pull into type units.
Definition at line 2913 of file DwarfDebug.cpp.
References llvm::DwarfUnit::addDIETypeSignature(), llvm::DebugHandlerBase::Asm, assert(), getDwarfVersion(), llvm::DIE::getUnitDie(), llvm::AddressPool::hasBeenUsed(), llvm::MipsISD::Ins, makeTypeSignature(), useSegmentedStringOffsetsTable(), and useSplitDwarf().
Referenced by llvm::DwarfUnit::createTypeDIE().
addSectionLabel()
void llvm::DwarfDebug::addSectionLabel (const MCSymbol * Sym)
addSubprogramNames()
void DwarfDebug::addSubprogramNames (const DICompileUnit & CU, const DISubprogram * SP, DIE & Die)
Definition at line 456 of file DwarfDebug.cpp.
References addAccelName(), addAccelObjC(), llvm::Apple, llvm::DwarfFile::getAbstractSPDies(), getAccelTableKind(), llvm::DIScope::getName(), llvm::DICompileUnit::getNameTableKind(), getObjCClassCategory(), getObjCMethodName(), isObjCClass(), llvm::DICompileUnit::None, and useAllLinkageNames().
Referenced by llvm::DwarfCompileUnit::constructInlinedScopeDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
beginFunctionImpl()
void DwarfDebug::beginFunctionImpl (const MachineFunction * MF) override protected virtual
Gather pre-function debug information.
Implements llvm::DebugHandlerBase.
Definition at line 1823 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, assert(), emitInitialLocDirective(), llvm::LexicalScopes::empty(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getFunctionBegin(), llvm::LexicalScope::getScopeNode(), llvm::MCSymbol::getSection(), llvm::Function::getSubprogram(), llvm::DwarfCompileUnit::getUniqueID(), llvm::DebugHandlerBase::LScopes, llvm::DICompileUnit::NoDebug, llvm::AsmPrinter::OutStreamer, and llvm::DebugHandlerBase::PrologEndLoc.
beginInstruction()
void DwarfDebug::beginInstruction (const MachineInstr * MI) override virtual
Process beginning of an instruction.
Reimplemented from llvm::DebugHandlerBase.
Definition at line 1677 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, assert(), llvm::DebugHandlerBase::beginInstruction(), llvm::DebugHandlerBase::CurMI, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, llvm::Enable, llvm::MachineInstr::FrameSetup, llvm::DebugLoc::getCol(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getFlag(), llvm::MachineFunction::getFunction(), llvm::DebugLoc::getLine(), llvm::MachineInstr::getMF(), llvm::MachineInstr::getParent(), llvm::DebugLoc::getScope(), llvm::Function::getSubprogram(), llvm::MachineInstr::hasDelaySlot(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isMetaInstruction(), llvm::DICompileUnit::NoDebug, llvm::AsmPrinter::OutStreamer, llvm::DebugHandlerBase::PrevInstBB, llvm::DebugHandlerBase::PrevInstLoc, llvm::DebugHandlerBase::PrevLabel, llvm::DebugHandlerBase::PrologEndLoc, and llvm::DebugHandlerBase::requestLabelAfterInsn().
beginModule()
void DwarfDebug::beginModule ()
Emit all Dwarf sections that should come prior to the content.
Definition at line 956 of file DwarfDebug.cpp.
References llvm::DwarfUnit::addSectionDelta(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addUInt(), llvm::any_of(), llvm::DebugHandlerBase::Asm, assert(), llvm::DIE::children(), llvm::DIEHash::computeCUSignature(), llvm::DwarfFile::computeSizeAndOffsets(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::AsmPrinter::createTempSymbol(), llvm::Module::debug_compile_units(), llvm::Module::debug_compile_units_begin(), llvm::Module::debug_compile_units_end(), DisableDebugInfoPrinting, llvm::iterator_range< IteratorT >::empty(), llvm::DwarfCompileUnit::finishEntityDefinition(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), for(), forBothCUs(), llvm::MCSection::getBeginSymbol(), llvm::DwarfUnit::getCUNode(), llvm::MCObjectFileInfo::getDwarfLoclistsSection(), llvm::MCObjectFileInfo::getDwarfMacinfoDWOSection(), llvm::MCObjectFileInfo::getDwarfMacinfoSection(), llvm::MCObjectFileInfo::getDwarfRangesSection(), getDwarfVersion(), llvm::DebugLocStream::getLists(), llvm::MachineModuleInfo::getModule(), llvm::AsmPrinter::getObjFileLowering(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfFile::getRangeLists(), llvm::DwarfCompileUnit::getRanges(), llvm::DwarfCompileUnit::getSkeleton(), llvm::DebugLocStream::getSym(), llvm::DIE::getUnitDie(), llvm::DIEUnit::getUnitDie(), llvm::Module::globals(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::DwarfCompileUnit::hasRangeLists(), llvm::ARM_PROC::IE, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::DICompileUnit::isDebugDirectivesOnly(), llvm::AddressPool::isEmpty(), llvm::TargetOptions::MCOptions, llvm::DebugHandlerBase::MMI, llvm::DICompileUnit::NoDebug, llvm::TargetMachine::Options, P, llvm::MachineModuleInfo::setDebugInfoAvailability(), llvm::DwarfCompileUnit::setDWOId(), llvm::AddressPool::setLabel(), llvm::DwarfFile::setRnglistsTableBaseSym(), llvm::DebugLocStream::setSym(), sortGlobalExprs(), llvm::MCTargetOptions::SplitDwarfFile, llvm::T, llvm::DwarfCompileUnit::takeRanges(), llvm::TimePassesIsEnabled, llvm::AsmPrinter::TM, useRangesSection(), useSegmentedStringOffsetsTable(), and useSplitDwarf().
Referenced by llvm::AsmPrinter::doInitialization().
emitDebugLocEntry()
void DwarfDebug::emitDebugLocEntry (ByteStreamer & Streamer, const DebugLocStream::Entry & Entry, const DwarfCompileUnit * CU)
Emit an entry for the debug loc section.
This can be used to handle an entry that's going to be emitted into the debug loc section.
Definition at line 2176 of file DwarfDebug.cpp.
References llvm::DebugLocStream::getComments().
Referenced by emitDebugLocEntryLocation().
emitDebugLocEntryLocation()
void DwarfDebug::emitDebugLocEntryLocation (const DebugLocStream::Entry & Entry, const DwarfCompileUnit * CU)
Emit the location for a debug loc entry, including the size header.
Definition at line 2298 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, emitDebugLocEntry(), llvm::AsmPrinter::emitInt16(), llvm::AsmPrinter::EmitULEB128(), llvm::DebugLocStream::getBytes(), getDwarfVersion(), llvm::max(), and llvm::AsmPrinter::OutStreamer.
Referenced by emitLocList().
emitDebugLocValue()
void DwarfDebug::emitDebugLocValue (const AsmPrinter & AP, const DIBasicType * BT, const DbgValueLoc & Value, DwarfExpression & DwarfExpr) static
Definition at line 2227 of file DwarfDebug.cpp.
References llvm::DwarfExpression::addExpression(), llvm::DwarfExpression::addFragmentOffset(), llvm::DwarfExpression::addMachineRegExpression(), llvm::DwarfExpression::addSignedConstant(), llvm::DwarfExpression::addUnsignedConstant(), llvm::DwarfExpression::addWasmLocation(), llvm::DwarfExpression::beginEntryValueExpression(), llvm::APFloat::bitcastToAPInt(), llvm::DbgValueLoc::getConstantFP(), llvm::DIBasicType::getEncoding(), llvm::DbgValueLoc::getExpression(), llvm::DbgValueLoc::getInt(), llvm::DbgValueLoc::getLoc(), llvm::MachineLocation::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::DbgValueLoc::getTargetIndexLocation(), llvm::ConstantFP::getValueAPF(), llvm::TargetIndexLocation::Index, llvm::DbgValueLoc::isConstantFP(), llvm::MachineLocation::isIndirect(), llvm::DbgValueLoc::isInt(), llvm::DbgValueLoc::isLocation(), llvm::DbgValueLoc::isTargetIndexLocation(), llvm::AsmPrinter::MF, llvm::TargetIndexLocation::Offset, llvm::DwarfExpression::setEntryValueFlag(), and llvm::DwarfExpression::setMemoryLocationKind().
Referenced by llvm::DwarfCompileUnit::constructCallSiteParmEntryDIEs().
emitInitialLocDirective()
DebugLoc DwarfDebug::emitInitialLocDirective (const MachineFunction & MF, unsigned CUID)
Emits inital debug location directive.
Definition at line 1803 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, DWARF2_FLAG_IS_STMT, findPrologueEndLoc(), getDwarfVersion(), llvm::MachineFunction::getFunction(), llvm::Function::getSubprogram(), and llvm::DebugHandlerBase::PrologEndLoc.
Referenced by beginFunctionImpl(), and llvm::AsmPrinter::emitInitialRawDwarfLocDirective().
endFunctionImpl()
void DwarfDebug::endFunctionImpl (const MachineFunction * MF) override protected virtual
Gather and emit post-function debug information.
Implements llvm::DebugHandlerBase.
Definition at line 1859 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, assert(), llvm::DwarfFile::emitAbbrevs(), llvm::emitAppleAccelTable(), llvm::emitDWARF5AccelTable(), llvm::DwarfStringPool::emitStringOffsetsTableHeader(), llvm::DwarfFile::emitUnits(), llvm::empty(), llvm::LexicalScopes::getAbstractScopesList(), llvm::MCSection::getBeginSymbol(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::MCObjectFileInfo::getDwarfAccelNamespaceSection(), llvm::MCObjectFileInfo::getDwarfAccelNamesSection(), llvm::MCObjectFileInfo::getDwarfAccelObjCSection(), llvm::MCObjectFileInfo::getDwarfAccelTypesSection(), llvm::MCObjectFileInfo::getDwarfStrOffSection(), getDwarfVersion(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getFunctionBegin(), llvm::AsmPrinter::getFunctionEnd(), llvm::AsmPrinter::getObjFileLowering(), llvm::DwarfFile::getScopeLabels(), llvm::LexicalScope::getScopeNode(), llvm::DwarfFile::getScopeVariables(), llvm::DwarfFile::getStringOffsetsStartSym(), llvm::DwarfFile::getStringPool(), llvm::Function::getSubprogram(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::DICompileUnit::LineTablesOnly, llvm_unreachable, llvm::DebugHandlerBase::LScopes, llvm::AsmPrinter::OutStreamer, llvm::DebugHandlerBase::PrevLabel, llvm::ARMBuildAttrs::Section, and useSplitDwarf().
endModule()
void DwarfDebug::endModule () override virtual
Emit all Dwarf sections that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 1206 of file DwarfDebug.cpp.
References llvm::Apple, assert(), llvm::DwarfCompileUnit::createBaseTypeDIEs(), llvm::DebugHandlerBase::CurMI, llvm::Default, llvm::Dwarf, GenerateARangeSection, getAccelTableKind(), llvm::MachineModuleInfo::hasDebugInfo(), llvm_unreachable, llvm::DebugHandlerBase::MMI, llvm::None, P, and useSplitDwarf().
enterNonTypeUnitContext()
DwarfDebug::NonTypeUnitContext DwarfDebug::enterNonTypeUnitContext ()
Definition at line 3011 of file DwarfDebug.cpp.
References llvm::AccelTable< DataT >::addName(), llvm::Apple, llvm::Default, llvm::DICompileUnit::Default, llvm::Dwarf, getAccelTableKind(), llvm::DwarfStringPool::getEntry(), llvm::DICompileUnit::getNameTableKind(), llvm::DwarfFile::getStringPool(), llvm_unreachable, llvm::None, NonTypeUnitContext, llvm::Ref, and useSplitDwarf().
Referenced by llvm::DwarfUnit::createTypeDIE().
generateTypeUnits()
bool llvm::DwarfDebug::generateTypeUnits () const inline
Returns whether to generate DWARF v4 type units.
Definition at line 683 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::createTypeDIE(), and llvm::DwarfUnit::isShareableAcrossCUs().
getAccelTableKind()
AccelTableKind llvm::DwarfDebug::getAccelTableKind () const inline
Returns what kind (if any) of accelerator tables to emit.
Definition at line 688 of file DwarfDebug.h.
Referenced by addAccelObjC(), addSubprogramNames(), endModule(), enterNonTypeUnitContext(), and llvm::DwarfCompileUnit::hasDwarfPubSections().
getAddressPool()
AddressPool& llvm::DwarfDebug::getAddressPool () inline
Definition at line 733 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfUnit::addOpAddress(), and emitRangeList().
getCurrentFunction()
const MachineFunction* llvm::DwarfDebug::getCurrentFunction () const inline
Definition at line 745 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
getDebugLocs()
const DebugLocStream& llvm::DwarfDebug::getDebugLocs () const inline
Returns the entries for the .debug_loc section.
Definition at line 718 of file DwarfDebug.h.
Referenced by emitLocList(), emitLoclistsTableHeader(), and llvm::DIELocList::EmitValue().
getDwarfVersion()
uint16_t DwarfDebug::getDwarfVersion () const
Returns the Dwarf Version.
Definition at line 3069 of file DwarfDebug.cpp.
References llvm::AsmPrinter::OutStreamer.
Referenced by llvm::DwarfUnit::addBlock(), addDwarfTypeUnitType(), llvm::DwarfUnit::addFlag(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfUnit::addLinkageName(), llvm::DwarfCompileUnit::addLocationList(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfUnit::addSectionDelta(), llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::addSectionOffset(), llvm::DwarfUnit::applySubprogramAttributes(), beginModule(), collectCallSiteParameters(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfUnit::emitCommonHeader(), emitDebugLocEntryLocation(), llvm::DwarfCompileUnit::emitHeader(), emitInitialLocDirective(), emitLocList(), emitRangeList(), endFunctionImpl(), GetCompileUnitType(), llvm::DwarfUnit::getDwarfVersion(), llvm::DwarfUnit::getHeaderSize(), llvm::DwarfUnit::getMD5AsBytes(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfUnit::getParentContextString(), llvm::DwarfCompileUnit::hasDwarfPubSections(), hasVectorBeenPadded(), useGNUAnalogForDwarf5Feature(), and llvm::DwarfUnit::~DwarfUnit().
getPrevCU()
const DwarfCompileUnit* llvm::DwarfDebug::getPrevCU () const inline
Returns the previous CU that was being updated.
Definition at line 714 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addRange().
getSectionLabel()
const MCSymbol * DwarfDebug::getSectionLabel (const MCSection * S)
Definition at line 3073 of file DwarfDebug.cpp.
Referenced by emitRangeList().
isLexicalScopeDIENull()
bool DwarfDebug::isLexicalScopeDIENull (LexicalScope * Scope)
A helper function to check whether the DIE for a given Scope is going to be null.
Check whether we should create a DIE for the given Scope, return true if we don't create a DIE (the corresponding DIE is null).
Definition at line 490 of file DwarfDebug.cpp.
References llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::DebugHandlerBase::getLabelAfterInsn(), llvm::LexicalScope::getRanges(), llvm::LexicalScope::isAbstractScope(), and llvm::SmallVectorBase::size().
Referenced by llvm::DwarfCompileUnit::constructLexicalScopeDIE(), and llvm::DwarfCompileUnit::constructScopeDIE().
lookupCU() [1/2]
DwarfCompileUnit* llvm::DwarfDebug::lookupCU (const DIE * Die) inline
Find the matching DwarfCompileUnit for the given CU DIE.
Definition at line 752 of file DwarfDebug.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE().
lookupCU() [2/2]
const DwarfCompileUnit* llvm::DwarfDebug::lookupCU (const DIE * Die) const inline
Definition at line 753 of file DwarfDebug.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
makeTypeSignature()
uint64_t DwarfDebug::makeTypeSignature (StringRef Identifier) static
Perform an MD5 checksum of Identifier and return the lower 64 bits.
Definition at line 2902 of file DwarfDebug.cpp.
References llvm::MD5::final(), llvm::MD5::MD5Result::high(), and llvm::MD5::update().
Referenced by addDwarfTypeUnitType().
setPrevCU()
void llvm::DwarfDebug::setPrevCU (const DwarfCompileUnit * PrevCU) inline
Definition at line 715 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addRange().
setSymbolSize()
void llvm::DwarfDebug::setSymbolSize (const MCSymbol * Sym, uint64_t Size) inline override virtual
For symbols that have a size designated (e.g.
common symbols), this tracks that size.
Implements llvm::AsmPrinterHandler.
Definition at line 652 of file DwarfDebug.h.
References Size.
shareAcrossDWOCUs()
bool DwarfDebug::shareAcrossDWOCUs () const
Definition at line 514 of file DwarfDebug.cpp.
References assert(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::LexicalScope::getInlinedAt(), llvm::LexicalScope::getScopeNode(), llvm::LexicalScope::isAbstractScope(), SplitDwarfCrossCuReferences, and useSplitDwarf().
Referenced by llvm::DwarfUnit::isShareableAcrossCUs().
skippedNonDebugFunction()
void DwarfDebug::skippedNonDebugFunction () override protected virtual
Reimplemented from llvm::DebugHandlerBase.
Definition at line 1850 of file DwarfDebug.cpp.
useAllLinkageNames()
bool llvm::DwarfDebug::useAllLinkageNames () const inline
Returns whether we should emit all DW_AT_[MIPS_]linkage_name.
If not, we still might emit certain cases.
Definition at line 658 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), addSubprogramNames(), and llvm::DwarfUnit::applySubprogramDefinitionAttributes().
useAppleExtensionAttributes()
bool llvm::DwarfDebug::useAppleExtensionAttributes () const inline
Definition at line 690 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::applySubprogramAttributes(), collectCallSiteParameters(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
useDWARF2Bitfields()
bool llvm::DwarfDebug::useDWARF2Bitfields () const inline
Returns whether to use the DWARF2 format for bitfields instyead of the DWARF4 format.
Definition at line 666 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs().
useGNUTLSOpcode()
bool llvm::DwarfDebug::useGNUTLSOpcode () const inline
Returns whether to use DW_OP_GNU_push_tls_address, instead of the standard DW_OP_form_tls_address opcode.
Definition at line 662 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute().
useInlineStrings()
bool llvm::DwarfDebug::useInlineStrings () const inline
Returns whether to use inline strings.
Definition at line 669 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::addString().
useLocSection()
bool llvm::DwarfDebug::useLocSection () const inline
Returns whether .debug_loc section should be emitted.
Definition at line 680 of file DwarfDebug.h.
useRangesSection()
bool llvm::DwarfDebug::useRangesSection () const inline
Returns whether ranges section should be emitted.
Definition at line 672 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), beginModule(), and emitRangeList().
useSectionsAsReferences()
bool llvm::DwarfDebug::useSectionsAsReferences () const inline
Returns whether to use sections as labels rather than temp symbols.
Definition at line 675 of file DwarfDebug.h.
Referenced by computeIndexValue(), llvm::DwarfUnit::emitCommonHeader(), llvm::DwarfCompileUnit::emitHeader(), and llvm::DwarfCompileUnit::initStmtList().
useSegmentedStringOffsetsTable()
bool llvm::DwarfDebug::useSegmentedStringOffsetsTable () const inline
Returns whether to generate a string offsets table with (possibly shared) contributions from each CU and type unit.
This implies the use of DW_FORM_strx* indirect references with DWARF v5 and beyond. Note that DW_FORM_GNU_str_index is also an indirect reference, but it is used with a pre-DWARF v5 implementation of split DWARF sections, which uses a monolithic string offsets table.
Definition at line 704 of file DwarfDebug.h.
Referenced by addDwarfTypeUnitType(), beginModule(), collectCallSiteParameters(), computeIndexValue(), emitRangeList(), and llvm::DwarfUnit::useSegmentedStringOffsetsTable().
useSplitDwarf()
bool llvm::DwarfDebug::useSplitDwarf () const inline
Returns whether or not to change the current debug info for the split dwarf proposal support.
Definition at line 696 of file DwarfDebug.h.
Referenced by addDwarfTypeUnitType(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addSectionLabel(), llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), beginModule(), collectCallSiteParameters(), computeIndexValue(), llvm::emitDWARF5AccelTable(), llvm::DwarfCompileUnit::emitHeader(), llvm::DwarfTypeUnit::emitHeader(), emitRangeList(), llvm::DIELocList::EmitValue(), endFunctionImpl(), endModule(), enterNonTypeUnitContext(), llvm::DwarfCompileUnit::includeMinimalInlineScopes(), and shareAcrossDWOCUs().
Friends And Related Function Documentation
NonTypeUnitContext
friend class NonTypeUnitContext friend
Definition at line 634 of file DwarfDebug.h.
Referenced by enterNonTypeUnitContext().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfDebug.h
lib/CodeGen/AsmPrinter/DwarfDebug.cpp