LLVM: llvm::SDLoc Class Reference
llvm::SDLoc Class Reference
Wrapper class for IR location info (IR ordering and DebugLoc) to be passed into SDNode creation functions.
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Member Functions
SDLoc ()=default
SDLoc (const SDNode *N)
SDLoc (const SDValue V)
SDLoc (const Instruction *I, int Order)
unsigned getIROrder () const
const DebugLoc & getDebugLoc () const
Detailed Description
Wrapper class for IR location info (IR ordering and DebugLoc) to be passed into SDNode creation functions.
When an SDNode is created from the DAGBuilder, the DebugLoc is extracted from the original Instruction, and IROrder is the ordinal position of the instruction. When an SDNode is created after the DAG is being built, both DebugLoc and the IROrder are propagated from the original SDNode. So SDLoc class provides two constructors besides the default one, one to be used by the DAGBuilder, the other to be used by others.
Definition at line 1118 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
SDLoc() [1/4]
llvm::SDLoc::SDLoc () default
SDLoc() [2/4]
llvm::SDLoc::SDLoc (const SDNode * N) inline
Definition at line 1125 of file SelectionDAGNodes.h.
SDLoc() [3/4]
llvm::SDLoc::SDLoc (const SDValue V) inline
Definition at line 1126 of file SelectionDAGNodes.h.
SDLoc() [4/4]
llvm::SDLoc::SDLoc (const Instruction * I, int Order) inline
Definition at line 1127 of file SelectionDAGNodes.h.
References assert(), and llvm::Instruction::getDebugLoc().
Member Function Documentation
getDebugLoc()
const DebugLoc& llvm::SDLoc::getDebugLoc () const inline
Definition at line 1134 of file SelectionDAGNodes.h.
Referenced by emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), errorUnsupported(), fail(), llvm::SelectionDAG::getAddrSpaceCast(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLabelNode(), llvm::SelectionDAG::getLifetimeNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetMemSDNode(), llvm::HexagonTargetLowering::getTargetNodeName(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getVectorShuffle(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), parseTexFail(), llvm::SelectionDAG::SelectNodeTo(), llvm::SITargetLowering::shouldEmitPCReloc(), and llvm::SelectionDAG::shouldOptForSize().
getIROrder()
unsigned llvm::SDLoc::getIROrder () const inline
Definition at line 1133 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::getAddrSpaceCast(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLabelNode(), llvm::SelectionDAG::getLifetimeNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetMemSDNode(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::SelectNodeTo(), and llvm::SelectionDAG::shouldOptForSize().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SelectionDAGNodes.h