LLVM: llvm::DIEValueList Class Reference
llvm::DIEValueList Class Reference
A list of DIE values.
#include "llvm/CodeGen/DIE.h"
Classes
class const_value_iterator
class value_iterator
Public Types
using value_range = iterator_range< value_iterator >
using const_value_range = iterator_range< const_value_iterator >
Public Member Functions
value_iterator addValue (BumpPtrAllocator &Alloc, const DIEValue &V)
template<class T >
value_iterator addValue (BumpPtrAllocator &Alloc, dwarf::Attribute Attribute, dwarf::Form Form, T &&Value)
void takeValues (DIEValueList &Other)
Take ownership of the nodes in Other, and append them to the back of the list.
value_range values ()
const_value_range values () const
Detailed Description
A list of DIE values.
This is a singly-linked list, but instead of reversing the order of insertion, we keep a pointer to the back of the list so we can push in order.
There are two main reasons to choose a linked list over a customized vector-like data structure.
For teardown efficiency, we want DIEs to be BumpPtrAllocated. Using a linked list here makes this way easier to accomplish.
Carrying an extra pointer per DIEValue isn't expensive. 45% of DIEs have 2 or fewer values, and 90% have 5 or fewer. A vector would be over-allocated by 50% on average anyway, the same cost as the linked-list node.
Definition at line 635 of file DIE.h.
Member Typedef Documentation
const_value_range
using llvm::DIEValueList::const_value_range = iterator_range<const_value_iterator>
Definition at line 684 of file DIE.h.
value_range
using llvm::DIEValueList::value_range = iterator_range<value_iterator>
Definition at line 683 of file DIE.h.
Member Function Documentation
addValue() [1/2]
value_iterator llvm::DIEValueList::addValue (BumpPtrAllocator & Alloc, const DIEValue & V) inline
Definition at line 686 of file DIE.h.
Referenced by llvm::DwarfCompileUnit::addAddressExpr(), llvm::DwarfCompileUnit::addBaseTypeRef(), llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addDIETypeSignature(), llvm::DwarfCompileUnit::addExpr(), llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::addLabel(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfUnit::addLabelDelta(), llvm::DwarfCompileUnit::addLocalLabelAddress(), llvm::DwarfCompileUnit::addLocationList(), llvm::DwarfUnit::addSectionDelta(), llvm::DwarfUnit::addSInt(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addUInt(), llvm::DwarfCompileUnit::applyStmtList(), and llvm::DwarfUnit::constructContainingTypeDIEs().
addValue() [2/2]
template<class T > value_iterator llvm::DIEValueList::addValue (BumpPtrAllocator & Alloc, dwarf::Attribute Attribute, dwarf::Form Form, T && Value) inline
Definition at line 691 of file DIE.h.
takeValues()
void llvm::DIEValueList::takeValues (DIEValueList & Other) inline
Take ownership of the nodes in Other, and append them to the back of the list.
Definition at line 698 of file DIE.h.
References llvm::IntrusiveBackList< T >::takeNodes().
Referenced by llvm::DIEDwarfExpression::DIEDwarfExpression().
values() [1/2]
value_range llvm::DIEValueList::values () inline
Definition at line 700 of file DIE.h.
References llvm::IntrusiveBackList< T >::begin(), llvm::IntrusiveBackList< T >::end(), and llvm::make_range().
Referenced by llvm::DIEHash::addSLEB128(), llvm::AsmPrinter::emitDwarfDIE(), llvm::DwarfFile::emitUnit(), getDIEStringAttr(), and printValues().
values() [2/2]
const_value_range llvm::DIEValueList::values () const inline
Definition at line 703 of file DIE.h.
References llvm::IntrusiveBackList< T >::begin(), llvm::IntrusiveBackList< T >::end(), and llvm::make_range().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/DIE.h