LLVM: llvm::MipsSubtarget Class Reference
llvm::MipsSubtarget Class Reference
#include "Target/Mips/MipsSubtarget.h"
Public Member Functions
bool isPositionIndependent () const
bool enablePostRAScheduler () const override
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
void getCriticalPathRCs (RegClassVector &CriticalPathRCs) const override
CodeGenOpt::Level getOptLevelToEnablePostRAScheduler () const override
bool isABI_N64 () const
bool isABI_N32 () const
bool isABI_O32 () const
const MipsABIInfo & getABI () const
bool isABI_FPXX () const
MipsSubtarget (const Triple &TT, StringRef CPU, StringRef FS, bool little, const MipsTargetMachine &TM, MaybeAlign StackAlignOverride)
This constructor initializes the data members to match that of the specified triple.
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
bool hasMips1 () const
bool hasMips2 () const
bool hasMips3 () const
bool hasMips4 () const
bool hasMips5 () const
bool hasMips4_32 () const
bool hasMips4_32r2 () const
bool hasMips32 () const
bool hasMips32r2 () const
bool hasMips32r3 () const
bool hasMips32r5 () const
bool hasMips32r6 () const
bool hasMips64 () const
bool hasMips64r2 () const
bool hasMips64r3 () const
bool hasMips64r5 () const
bool hasMips64r6 () const
bool hasCnMips () const
bool hasCnMipsP () const
bool isLittle () const
bool isABICalls () const
bool isFPXX () const
bool isFP64bit () const
bool useOddSPReg () const
bool noOddSPReg () const
bool isNaN2008 () const
bool inAbs2008Mode () const
bool isGP64bit () const
bool isGP32bit () const
unsigned getGPRSizeInBytes () const
bool isPTR64bit () const
bool isPTR32bit () const
bool hasSym32 () const
bool isSingleFloat () const
bool isTargetELF () const
bool hasVFPU () const
bool inMips16Mode () const
bool inMips16ModeDefault () const
bool inMips16HardFloat () const
bool inMicroMipsMode () const
bool inMicroMips32r6Mode () const
bool hasDSP () const
bool hasDSPR2 () const
bool hasDSPR3 () const
bool hasMSA () const
bool disableMadd4 () const
bool hasEVA () const
bool hasMT () const
bool hasCRC () const
bool hasVirt () const
bool hasGINV () const
bool useIndirectJumpsHazard () const
bool useSmallSection () const
bool hasStandardEncoding () const
bool useSoftFloat () const
bool useLongCalls () const
bool useXGOT () const
bool enableLongBranchPass () const
bool hasExtractInsert () const
Features related to the presence of specific instructions.
bool hasMTHC1 () const
bool allowMixed16_32 () const
bool os16 () const
bool isTargetNaCl () const
bool isXRaySupported () const override
Align getStackAlignment () const
Reloc::Model getRelocationModel () const
MipsSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS, const TargetMachine &TM)
bool systemSupportsUnalignedAccess () const
Does the system support unaligned memory access.
void setHelperClassesMips16 ()
void setHelperClassesMipsSE ()
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
const MipsInstrInfo * getInstrInfo () const override
const TargetFrameLowering * getFrameLowering () const override
const MipsRegisterInfo * getRegisterInfo () const override
const MipsTargetLowering * getTargetLowering () const override
const InstrItineraryData * getInstrItineraryData () const override
const CallLowering * getCallLowering () const override
const LegalizerInfo * getLegalizerInfo () const override
const RegisterBankInfo * getRegBankInfo () const override
InstructionSelector * getInstructionSelector () const override
Static Public Member Functions
static bool useConstantIslands ()
Protected Attributes
std::unique_ptr< CallLowering > CallLoweringInfo
std::unique_ptr< LegalizerInfo > Legalizer
std::unique_ptr< RegisterBankInfo > RegBankInfo
std::unique_ptr< InstructionSelector > InstSelector
Detailed Description
Definition at line 39 of file MipsSubtarget.h.
Constructor & Destructor Documentation
MipsSubtarget()
MipsSubtarget::MipsSubtarget (const Triple & TT, StringRef CPU, StringRef FS, bool little, const MipsTargetMachine & TM, MaybeAlign StackAlignOverride)
This constructor initializes the data members to match that of the specified triple.
Definition at line 70 of file MipsSubtarget.cpp.
References assert(), CallLoweringInfo, llvm::createMipsInstructionSelector(), llvm::errs(), getRegisterInfo(), getTargetLowering(), GPOpt, hasCRC(), hasDSP(), hasDSPR2(), hasGINV(), hasMips32(), hasMips32r2(), hasMips32r5(), hasMips32r6(), hasMips64(), hasMips64r2(), hasMips64r6(), hasMSA(), hasSym32(), hasVirt(), inAbs2008Mode(), InstSelector, isABI_N32(), isABI_N64(), isABI_O32(), isFP64bit(), isGP64bit(), isNaN2008(), llvm::TargetMachine::isPositionIndependent(), RegBankInfo, llvm::report_fatal_error(), and useOddSPReg().
Referenced by isABI_FPXX().
Member Function Documentation
allowMixed16_32()
bool llvm::MipsSubtarget::allowMixed16_32 () const inline
Definition at line 343 of file MipsSubtarget.h.
References inMips16ModeDefault().
Referenced by enableLongBranchPass().
disableMadd4()
bool llvm::MipsSubtarget::disableMadd4 () const inline
Definition at line 316 of file MipsSubtarget.h.
enableLongBranchPass()
bool llvm::MipsSubtarget::enableLongBranchPass () const inline
Definition at line 335 of file MipsSubtarget.h.
References allowMixed16_32(), hasStandardEncoding(), and inMicroMipsMode().
enablePostRAScheduler()
bool MipsSubtarget::enablePostRAScheduler () const override
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
This overrides the PostRAScheduler bit in the SchedModel for any CPU.
Definition at line 225 of file MipsSubtarget.cpp.
getABI()
const MipsABIInfo & MipsSubtarget::getABI () const
Definition at line 279 of file MipsSubtarget.cpp.
References llvm::MipsTargetMachine::getABI().
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::MipsFrameLowering::eliminateCallFramePseudoInstr(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsInstrInfo::getEquivalentCompactForm(), llvm::MipsSEFrameLowering::getFrameIndexReference(), isABI_N32(), isABI_N64(), isABI_O32(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadRegFromStack(), and llvm::MipsSEFrameLowering::spillCalleeSavedRegisters().
getCallLowering()
const CallLowering * MipsSubtarget::getCallLowering () const override
Definition at line 281 of file MipsSubtarget.cpp.
References CallLoweringInfo.
getCriticalPathRCs()
void MipsSubtarget::getCriticalPathRCs (RegClassVector & CriticalPathRCs) const override
Definition at line 227 of file MipsSubtarget.cpp.
References isGP64bit().
getFrameLowering()
const TargetFrameLowering* llvm::MipsSubtarget::getFrameLowering () const inline override
Definition at line 379 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::canRealignStack(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getReservedRegs(), and llvm::MipsTargetLowering::HandleByVal().
getGPRSizeInBytes()
unsigned llvm::MipsSubtarget::getGPRSizeInBytes () const inline
Definition at line 288 of file MipsSubtarget.h.
References isGP64bit().
Referenced by llvm::MipsTargetLowering::HandleByVal().
getInstrInfo()
const MipsInstrInfo* llvm::MipsSubtarget::getInstrInfo () const inline override
Definition at line 378 of file MipsSubtarget.h.
Referenced by llvm::Mips16FrameLowering::determineCalleeSaves(), llvm::MipsFrameLowering::eliminateCallFramePseudoInstr(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), getEquivalentCallShort(), llvm::MipsTargetLowering::HandleByVal(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), Mips16WhichOp8uOr16simm(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), and llvm::MipsSEFrameLowering::spillCalleeSavedRegisters().
getInstrItineraryData()
const InstrItineraryData* llvm::MipsSubtarget::getInstrItineraryData () const inline override
Definition at line 388 of file MipsSubtarget.h.
getInstructionSelector()
InstructionSelector * MipsSubtarget::getInstructionSelector () const override
Definition at line 293 of file MipsSubtarget.cpp.
References InstSelector.
getLegalizerInfo()
const LegalizerInfo * MipsSubtarget::getLegalizerInfo () const override
Definition at line 285 of file MipsSubtarget.cpp.
getOptLevelToEnablePostRAScheduler()
CodeGenOpt::Level MipsSubtarget::getOptLevelToEnablePostRAScheduler () const override
Definition at line 233 of file MipsSubtarget.cpp.
References llvm::CodeGenOpt::Aggressive.
getRegBankInfo()
const RegisterBankInfo * MipsSubtarget::getRegBankInfo () const override
Definition at line 289 of file MipsSubtarget.cpp.
References RegBankInfo.
Referenced by llvm::MipsCallLowering::MipsHandler::handle(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), and SelectMSA3OpIntrinsic().
getRegisterInfo()
const MipsRegisterInfo* llvm::MipsSubtarget::getRegisterInfo () const inline override
Definition at line 382 of file MipsSubtarget.h.
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsFrameLowering::estimateStackSize(), llvm::MipsTargetLowering::getOpndList(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::MipsFrameLowering::hasBP(), llvm::MipsFrameLowering::hasFP(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), and SelectMSA3OpIntrinsic().
getRelocationModel()
Reloc::Model MipsSubtarget::getRelocationModel () const
Definition at line 272 of file MipsSubtarget.cpp.
References llvm::TargetMachine::getRelocationModel().
Referenced by llvm::MipsSEFrameLowering::emitPrologue(), and getStackAlignment().
getSelectionDAGInfo()
const SelectionDAGTargetInfo* llvm::MipsSubtarget::getSelectionDAGInfo () const inline override
Definition at line 375 of file MipsSubtarget.h.
getStackAlignment()
Align llvm::MipsSubtarget::getStackAlignment () const inline
Definition at line 356 of file MipsSubtarget.h.
References getRelocationModel(), and initializeSubtargetDependencies().
getTargetLowering()
const MipsTargetLowering* llvm::MipsSubtarget::getTargetLowering () const inline override
Definition at line 385 of file MipsSubtarget.h.
Referenced by MipsSubtarget().
hasCnMips()
bool llvm::MipsSubtarget::hasCnMips () const inline
Definition at line 275 of file MipsSubtarget.h.
Referenced by llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), performANDCombine(), and performSHLCombine().
hasCnMipsP()
bool llvm::MipsSubtarget::hasCnMipsP () const inline
Definition at line 276 of file MipsSubtarget.h.
hasCRC()
bool llvm::MipsSubtarget::hasCRC () const inline
Definition at line 319 of file MipsSubtarget.h.
Referenced by MipsSubtarget().
hasDSP()
bool llvm::MipsSubtarget::hasDSP () const inline
Definition at line 312 of file MipsSubtarget.h.
Referenced by llvm::MipsSETargetLowering::getRepRegClassFor(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), and performDSPShiftCombine().
hasDSPR2()
bool llvm::MipsSubtarget::hasDSPR2 () const inline
Definition at line 313 of file MipsSubtarget.h.
Referenced by llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), performSRACombine(), and performSRLCombine().
hasDSPR3()
bool llvm::MipsSubtarget::hasDSPR3 () const inline
Definition at line 314 of file MipsSubtarget.h.
hasEVA()
bool llvm::MipsSubtarget::hasEVA () const inline
Definition at line 317 of file MipsSubtarget.h.
hasExtractInsert()
bool llvm::MipsSubtarget::hasExtractInsert () const inline
Features related to the presence of specific instructions.
Definition at line 340 of file MipsSubtarget.h.
References hasMips32r2(), and inMips16Mode().
Referenced by lowerFABS64(), lowerFCOPYSIGN64(), performANDCombine(), and performORCombine().
hasGINV()
bool llvm::MipsSubtarget::hasGINV () const inline
Definition at line 321 of file MipsSubtarget.h.
Referenced by MipsSubtarget().
hasMips1()
bool llvm::MipsSubtarget::hasMips1 () const inline
Definition at line 242 of file MipsSubtarget.h.
hasMips2()
bool llvm::MipsSubtarget::hasMips2 () const inline
Definition at line 243 of file MipsSubtarget.h.
hasMips3()
bool llvm::MipsSubtarget::hasMips3 () const inline
Definition at line 244 of file MipsSubtarget.h.
hasMips32()
bool llvm::MipsSubtarget::hasMips32 () const inline
Definition at line 249 of file MipsSubtarget.h.
References hasMips64().
Referenced by llvm::MipsTargetLowering::createFastISel(), llvm::MipsTargetLowering::HandleByVal(), llvm::MipsTargetLowering::isCheapToSpeculateCtlz(), llvm::MipsTargetLowering::isCheapToSpeculateCttz(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), performADDCombine(), and performSUBCombine().
hasMips32r2()
bool llvm::MipsSubtarget::hasMips32r2 () const inline
Definition at line 253 of file MipsSubtarget.h.
References hasMips64r2().
Referenced by llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsSEFrameLowering::emitPrologue(), hasExtractInsert(), hasMTHC1(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), and useIndirectJumpsHazard().
hasMips32r3()
bool llvm::MipsSubtarget::hasMips32r3 () const inline
Definition at line 257 of file MipsSubtarget.h.
References hasMips64r2().
hasMips32r5()
bool llvm::MipsSubtarget::hasMips32r5 () const inline
Definition at line 261 of file MipsSubtarget.h.
References hasMips64r5().
Referenced by MipsSubtarget().
hasMips32r6()
bool llvm::MipsSubtarget::hasMips32r6 () const inline
Definition at line 265 of file MipsSubtarget.h.
References hasMips64r6().
Referenced by llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsTargetLowering::createFastISel(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), getEquivalentCallShort(), llvm::MipsInstrInfo::getEquivalentCompactForm(), getLoadStoreOffsetSizeInBits(), inMicroMips32r6Mode(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), performADDCombine(), performSUBCombine(), llvm::MipsAsmPrinter::runOnMachineFunction(), and systemSupportsUnalignedAccess().
hasMips4()
bool llvm::MipsSubtarget::hasMips4 () const inline
Definition at line 245 of file MipsSubtarget.h.
Referenced by llvm::MipsTargetLowering::HandleByVal().
hasMips4_32()
bool llvm::MipsSubtarget::hasMips4_32 () const inline
Definition at line 247 of file MipsSubtarget.h.
hasMips4_32r2()
bool llvm::MipsSubtarget::hasMips4_32r2 () const inline
Definition at line 248 of file MipsSubtarget.h.
hasMips5()
bool llvm::MipsSubtarget::hasMips5 () const inline
Definition at line 246 of file MipsSubtarget.h.
hasMips64()
bool llvm::MipsSubtarget::hasMips64 () const inline
Definition at line 269 of file MipsSubtarget.h.
Referenced by llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), hasMips32(), lowerMSABitClearImm(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), and performMADD_MSUBCombine().
hasMips64r2()
bool llvm::MipsSubtarget::hasMips64r2 () const inline
Definition at line 270 of file MipsSubtarget.h.
Referenced by hasMips32r2(), hasMips32r3(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), and performORCombine().
hasMips64r3()
bool llvm::MipsSubtarget::hasMips64r3 () const inline
Definition at line 271 of file MipsSubtarget.h.
hasMips64r5()
bool llvm::MipsSubtarget::hasMips64r5 () const inline
Definition at line 272 of file MipsSubtarget.h.
Referenced by hasMips32r5().
hasMips64r6()
bool llvm::MipsSubtarget::hasMips64r6 () const inline
Definition at line 273 of file MipsSubtarget.h.
Referenced by llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), hasMips32r6(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), and llvm::MipsAsmPrinter::runOnMachineFunction().
hasMSA()
bool llvm::MipsSubtarget::hasMSA () const inline
Definition at line 315 of file MipsSubtarget.h.
Referenced by llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), performANDCombine(), performORCombine(), performSRACombine(), performXORCombine(), SelectMSA3OpIntrinsic(), and UnpackFromArgumentSlot().
hasMT()
bool llvm::MipsSubtarget::hasMT () const inline
Definition at line 318 of file MipsSubtarget.h.
hasMTHC1()
bool llvm::MipsSubtarget::hasMTHC1 () const inline
Definition at line 341 of file MipsSubtarget.h.
References hasMips32r2().
Referenced by llvm::MipsSEInstrInfo::loadImmediate().
hasStandardEncoding()
bool llvm::MipsSubtarget::hasStandardEncoding () const inline
Definition at line 327 of file MipsSubtarget.h.
Referenced by enableLongBranchPass().
hasSym32()
bool llvm::MipsSubtarget::hasSym32 () const inline
Definition at line 291 of file MipsSubtarget.h.
References isABI_N32(), isABI_N64(), and isABI_O32().
Referenced by MipsSubtarget().
hasVFPU()
bool llvm::MipsSubtarget::hasVFPU () const inline
Definition at line 296 of file MipsSubtarget.h.
hasVirt()
bool llvm::MipsSubtarget::hasVirt () const inline
Definition at line 320 of file MipsSubtarget.h.
Referenced by MipsSubtarget().
inAbs2008Mode()
bool llvm::MipsSubtarget::inAbs2008Mode () const inline
Definition at line 285 of file MipsSubtarget.h.
Referenced by MipsSubtarget(), and llvm::MipsTargetLowering::MipsTargetLowering().
initializeSubtargetDependencies()
MipsSubtarget & MipsSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS, const TargetMachine & TM)
Definition at line 238 of file MipsSubtarget.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::TargetMachine::getTargetTriple(), isABI_N32(), isABI_N64(), isABI_O32(), isGP64bit(), ParseSubtargetFeatures(), llvm::report_fatal_error(), and llvm::MIPS_MC::selectMipsCPU().
Referenced by getStackAlignment().
inMicroMips32r6Mode()
bool llvm::MipsSubtarget::inMicroMips32r6Mode () const inline
Definition at line 309 of file MipsSubtarget.h.
References hasMips32r6(), and inMicroMipsMode().
inMicroMipsMode()
bool llvm::MipsSubtarget::inMicroMipsMode () const inline
Definition at line 308 of file MipsSubtarget.h.
Referenced by llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MipsTargetLowering::createFastISel(), emitDirectiveRelocJalr(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), enableLongBranchPass(), llvm::MipsSEInstrInfo::expandPostRAPseudo(), getEquivalentCallShort(), llvm::MipsInstrInfo::getEquivalentCompactForm(), getLoadStoreOffsetSizeInBits(), getUnconditionalBranch(), inMicroMips32r6Mode(), llvm::MipsTargetLowering::MipsTargetLowering(), and llvm::MipsAsmPrinter::runOnMachineFunction().
inMips16HardFloat()
bool llvm::MipsSubtarget::inMips16HardFloat () const inline
Definition at line 305 of file MipsSubtarget.h.
References inMips16Mode().
Referenced by llvm::MipsTargetLowering::getOpndList(), and llvm::MipsCCState::getSpecialCallingConvForCallee().
inMips16Mode()
bool llvm::MipsSubtarget::inMips16Mode () const inline
Definition at line 297 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::canRealignStack(), llvm::MipsFrameLowering::create(), llvm::MipsInstrInfo::create(), llvm::MipsTargetLowering::create(), llvm::MipsTargetLowering::createFastISel(), llvm::MipsAsmPrinter::EmitConstantPool(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getReservedRegs(), hasExtractInsert(), inMips16HardFloat(), llvm::MipsTargetLowering::MipsTargetLowering(), performADDCombine(), performSUBCombine(), and llvm::MipsAsmPrinter::runOnMachineFunction().
inMips16ModeDefault()
bool llvm::MipsSubtarget::inMips16ModeDefault () const inline
Definition at line 298 of file MipsSubtarget.h.
Referenced by allowMixed16_32().
isABI_FPXX()
bool llvm::MipsSubtarget::isABI_FPXX () const inline
Definition at line 231 of file MipsSubtarget.h.
References llvm::X86AS::FS, isABI_O32(), llvm::support::little, MipsSubtarget(), ParseSubtargetFeatures(), and llvm::TT.
Referenced by llvm::MipsSEInstrInfo::loadImmediate().
isABI_N32()
bool MipsSubtarget::isABI_N32 () const
Definition at line 277 of file MipsSubtarget.cpp.
References getABI(), and llvm::MipsABIInfo::IsN32().
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), hasSym32(), initializeSubtargetDependencies(), and MipsSubtarget().
isABI_N64()
bool MipsSubtarget::isABI_N64 () const
Definition at line 276 of file MipsSubtarget.cpp.
References getABI(), and llvm::MipsABIInfo::IsN64().
Referenced by llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), hasSym32(), initializeSubtargetDependencies(), llvm::MipsSEInstrInfo::loadImmediate(), lowerMSALoadIntr(), lowerMSAStoreIntr(), and MipsSubtarget().
isABI_O32()
bool MipsSubtarget::isABI_O32 () const
Definition at line 278 of file MipsSubtarget.cpp.
References getABI(), and llvm::MipsABIInfo::IsO32().
Referenced by llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsTargetLowering::getNumRegistersForCallingConv(), llvm::MipsTargetLowering::getRegisterTypeForCallingConv(), hasSym32(), initializeSubtargetDependencies(), isABI_FPXX(), MipsSubtarget(), and shouldTransformMulToShiftsAddsSubs().
isABICalls()
bool llvm::MipsSubtarget::isABICalls () const inline
Definition at line 279 of file MipsSubtarget.h.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and llvm::MipsRegisterInfo::getReservedRegs().
isFP64bit()
bool llvm::MipsSubtarget::isFP64bit () const inline
Definition at line 281 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::MipsSETargetLowering::MipsSETargetLowering(), and MipsSubtarget().
isFPXX()
bool llvm::MipsSubtarget::isFPXX () const inline
Definition at line 280 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), and llvm::MipsRegisterInfo::getCallPreservedMask().
isGP32bit()
bool llvm::MipsSubtarget::isGP32bit () const inline
Definition at line 287 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::canRealignStack().
isGP64bit()
bool llvm::MipsSubtarget::isGP64bit () const inline
Definition at line 286 of file MipsSubtarget.h.
Referenced by llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), getCriticalPathRCs(), getGPRSizeInBytes(), llvm::MipsTargetLowering::getRegisterByName(), initializeSubtargetDependencies(), llvm::MipsSEInstrInfo::loadImmediate(), lowerFABS64(), lowerFCOPYSIGN64(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MipsAsmPrinter::PrintAsmOperand(), and llvm::MipsAsmPrinter::runOnMachineFunction().
isLittle()
bool llvm::MipsSubtarget::isLittle () const inline
Definition at line 278 of file MipsSubtarget.h.
Referenced by CC_MipsO32(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::MipsTargetLowering::lowerLOAD(), lowerMSABitClearImm(), llvm::MipsTargetLowering::lowerSTORE(), performDSPShiftCombine(), performORCombine(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), and UnpackFromArgumentSlot().
isNaN2008()
bool llvm::MipsSubtarget::isNaN2008 () const inline
Definition at line 284 of file MipsSubtarget.h.
Referenced by MipsSubtarget().
isPositionIndependent()
bool MipsSubtarget::isPositionIndependent () const
Definition at line 220 of file MipsSubtarget.cpp.
References llvm::TargetMachine::isPositionIndependent().
Referenced by getUnconditionalBranch().
isPTR32bit()
bool llvm::MipsSubtarget::isPTR32bit () const inline
Definition at line 290 of file MipsSubtarget.h.
isPTR64bit()
bool llvm::MipsSubtarget::isPTR64bit () const inline
Definition at line 289 of file MipsSubtarget.h.
isSingleFloat()
bool llvm::MipsSubtarget::isSingleFloat () const inline
Definition at line 294 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsTargetLowering::lowerSTORE(), and llvm::MipsSETargetLowering::MipsSETargetLowering().
isTargetELF()
bool llvm::MipsSubtarget::isTargetELF () const inline
Definition at line 295 of file MipsSubtarget.h.
References llvm::Triple::isOSBinFormatELF().
isTargetNaCl()
bool llvm::MipsSubtarget::isTargetNaCl () const inline
Definition at line 348 of file MipsSubtarget.h.
References llvm::Triple::isOSNaCl().
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsRegisterInfo::getReservedRegs(), and llvm::MipsAsmPrinter::runOnMachineFunction().
isXRaySupported()
bool llvm::MipsSubtarget::isXRaySupported () const inline override
Definition at line 350 of file MipsSubtarget.h.
References useConstantIslands().
noOddSPReg()
bool llvm::MipsSubtarget::noOddSPReg () const inline
Definition at line 283 of file MipsSubtarget.h.
os16()
bool llvm::MipsSubtarget::os16 () const inline
Definition at line 346 of file MipsSubtarget.h.
ParseSubtargetFeatures()
void llvm::MipsSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
Referenced by initializeSubtargetDependencies(), and isABI_FPXX().
setHelperClassesMips16()
void llvm::MipsSubtarget::setHelperClassesMips16 ()
Referenced by systemSupportsUnalignedAccess().
setHelperClassesMipsSE()
void llvm::MipsSubtarget::setHelperClassesMipsSE ()
Referenced by systemSupportsUnalignedAccess().
systemSupportsUnalignedAccess()
bool llvm::MipsSubtarget::systemSupportsUnalignedAccess () const inline
Does the system support unaligned memory access.
MIPS32r6/MIPS64r6 require full unaligned access support but does not specify which component of the system provides it. Hardware, software, and hybrid implementations are all valid.
Definition at line 369 of file MipsSubtarget.h.
References hasMips32r6(), setHelperClassesMips16(), and setHelperClassesMipsSE().
Referenced by llvm::MipsSETargetLowering::allowsMisalignedMemoryAccesses(), llvm::MipsTargetLowering::lowerLOAD(), and llvm::MipsTargetLowering::lowerSTORE().
useConstantIslands()
bool MipsSubtarget::useConstantIslands () static
Definition at line 266 of file MipsSubtarget.cpp.
References llvm::dbgs(), LLVM_DEBUG, and Mips16ConstantIslands.
Referenced by branchMaxOffsets(), llvm::MipsAsmPrinter::EmitConstantPool(), and isXRaySupported().
useIndirectJumpsHazard()
bool llvm::MipsSubtarget::useIndirectJumpsHazard () const inline
Definition at line 322 of file MipsSubtarget.h.
References hasMips32r2().
Referenced by llvm::MipsInstrInfo::verifyInstruction().
useLongCalls()
bool llvm::MipsSubtarget::useLongCalls () const inline
Definition at line 331 of file MipsSubtarget.h.
useOddSPReg()
bool llvm::MipsSubtarget::useOddSPReg () const inline
Definition at line 282 of file MipsSubtarget.h.
Referenced by llvm::MipsSEInstrInfo::loadImmediate(), and MipsSubtarget().
useSmallSection()
bool llvm::MipsSubtarget::useSmallSection () const inline
Definition at line 325 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getReservedRegs(), and llvm::MipsTargetObjectFile::IsGlobalInSmallSection().
useSoftFloat()
bool llvm::MipsSubtarget::useSoftFloat () const inline
Definition at line 329 of file MipsSubtarget.h.
Referenced by llvm::MipsSEFrameLowering::emitPrologue(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), and UnpackFromArgumentSlot().
useXGOT()
bool llvm::MipsSubtarget::useXGOT () const inline
Definition at line 333 of file MipsSubtarget.h.
Referenced by llvm::MipsTargetLowering::createFastISel().
Member Data Documentation
CallLoweringInfo
std::unique_ptr<CallLowering> llvm::MipsSubtarget::CallLoweringInfo protected
Definition at line 394 of file MipsSubtarget.h.
Referenced by getCallLowering(), and MipsSubtarget().
InstSelector
std::unique_ptr<InstructionSelector> llvm::MipsSubtarget::InstSelector protected
Definition at line 397 of file MipsSubtarget.h.
Referenced by getInstructionSelector(), and MipsSubtarget().
Legalizer
std::unique_ptr<LegalizerInfo> llvm::MipsSubtarget::Legalizer protected
Definition at line 395 of file MipsSubtarget.h.
RegBankInfo
std::unique_ptr<RegisterBankInfo> llvm::MipsSubtarget::RegBankInfo protected
Definition at line 396 of file MipsSubtarget.h.
Referenced by getRegBankInfo(), and MipsSubtarget().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsSubtarget.h
lib/Target/Mips/MipsSubtarget.cpp