LLVM: llvm::MCLEBFragment Class Reference
llvm::MCLEBFragment Class Reference
#include "llvm/MC/MCFragment.h"
Public Member Functions
MCLEBFragment (const MCExpr &Value_, bool IsSigned_, MCSection *Sec=nullptr)
const MCExpr & getValue () const
bool isSigned () const
SmallString< 8 > & getContents ()
const SmallString< 8 > & getContents () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB, FT_BoundaryAlign, FT_SymbolId, FT_CVInlineLines,
FT_CVDefRange, FT_Dummy
}
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, true >
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
ilist_node_impl ()=default
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions
Detailed Description
Definition at line 372 of file MCFragment.h.
Constructor & Destructor Documentation
MCLEBFragment()
llvm::MCLEBFragment::MCLEBFragment (const MCExpr & Value_, bool IsSigned_, MCSection * Sec = nullptr) inline
Definition at line 382 of file MCFragment.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Member Function Documentation
classof()
static bool llvm::MCLEBFragment::classof (const MCFragment * F) inline static
Definition at line 396 of file MCFragment.h.
References llvm::MCFragment::FT_LEB, and llvm::MCFragment::getKind().
getContents() [1/2]
SmallString<8>& llvm::MCLEBFragment::getContents () inline
Definition at line 391 of file MCFragment.h.
Referenced by llvm::MCAssembler::Finish().
getContents() [2/2]
const SmallString<8>& llvm::MCLEBFragment::getContents () const inline
Definition at line 392 of file MCFragment.h.
getValue()
const MCExpr& llvm::MCLEBFragment::getValue () const inline
Definition at line 387 of file MCFragment.h.
Referenced by llvm::MCAssembler::Finish().
isSigned()
bool llvm::MCLEBFragment::isSigned () const inline
Definition at line 389 of file MCFragment.h.
Referenced by llvm::MCAssembler::Finish().
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h