LLVM: llvm::ConstantAsMetadata Class Reference
llvm::ConstantAsMetadata Class Reference
#include "llvm/IR/Metadata.h"
Public Member Functions
Constant * getValue () const
Public Member Functions inherited from llvm::ValueAsMetadata
Value * getValue () const
Type * getType () const
LLVMContext & getContext () const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static ConstantAsMetadata * get (Constant *C)
static ConstantAsMetadata * getIfExists (Constant *C)
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::ValueAsMetadata
static ValueAsMetadata * get (Value *V)
static ConstantAsMetadata * getConstant (Value *C)
static LocalAsMetadata * getLocal (Value *Local)
static ValueAsMetadata * getIfExists (Value *V)
static ConstantAsMetadata * getConstantIfExists (Value *C)
static LocalAsMetadata * getLocalIfExists (Value *Local)
static void handleDeletion (Value *V)
static void handleRAUW (Value *From, Value *To)
static bool classof (const Metadata *MD)
Friends
class ValueAsMetadata
Additional Inherited Members
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::ValueAsMetadata
ValueAsMetadata (unsigned ID, Value *V)
~ValueAsMetadata ()=default
void replaceAllUsesWith (Metadata *MD)
Handle collisions after Value::replaceAllUsesWith().
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Definition at line 403 of file Metadata.h.
Member Function Documentation
classof()
static bool llvm::ConstantAsMetadata::classof (const Metadata * MD) inline static
Definition at line 422 of file Metadata.h.
References llvm::Metadata::getMetadataID().
get()
static ConstantAsMetadata* llvm::ConstantAsMetadata::get (Constant * C) inline static
Definition at line 410 of file Metadata.h.
References C, and llvm::ValueAsMetadata::getConstant().
Referenced by AddCalls(), llvm::Module::addModuleFlag(), llvm::GlobalObject::addTypeMetadata(), llvm::GlobalObject::addVCallVisibilityMetadata(), llvm::GlobalObject::copyMetadata(), createAccessTag(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MDBuilder::createConstant(), llvm::DIBuilder::createInheritance(), createStringMetadata(), DisableAllLoopOptsOnLoop(), foldCtpop(), foldCttzCtlz(), getConstantOrNull(), getKeyValMD(), AAValueConstantRangeImpl::getMDNodeForConstantRange(), llvm::MDNode::getMostGenericRange(), getMulHu(), llvm::ValueAsMetadata::handleRAUW(), isKnownTypeIdMember(), LLVMMDNodeInContext(), LLVMValueAsMetadata(), PushArgMD(), selectJumpTableArmEncoding(), llvm::LoopVectorizeHints::setAlreadyVectorized(), splitGlobal(), llvm::UpgradeIntrinsicCall(), llvm::UpgradeModuleFlags(), and llvm::UpgradeTBAANode().
getIfExists()
static ConstantAsMetadata* llvm::ConstantAsMetadata::getIfExists (Constant * C) inline static
Definition at line 414 of file Metadata.h.
References llvm::ValueAsMetadata::getConstantIfExists().
getValue()
Constant* llvm::ConstantAsMetadata::getValue () const inline
Definition at line 418 of file Metadata.h.
References llvm::ValueAsMetadata::getValue().
Referenced by getSummaryFromMD(), and wrapConstantAsMetadata().
Friends And Related Function Documentation
ValueAsMetadata
friend class ValueAsMetadata friend
Definition at line 404 of file Metadata.h.
The documentation for this class was generated from the following file:
include/llvm/IR/Metadata.h