LLVM: llvm::PPCFrameLowering Class Reference
llvm::PPCFrameLowering Class Reference
#include "Target/PowerPC/PPCFrameLowering.h"
Public Member Functions
PPCFrameLowering (const PPCSubtarget &STI)
unsigned determineFrameLayoutAndUpdate (MachineFunction &MF, bool UseEstimate=false) const
Determine the frame layout and update the machine function.
unsigned determineFrameLayout (const MachineFunction &MF, bool UseEstimate=false, unsigned *NewMaxCallFrameSize=nullptr) const
Determine the frame layout but do not update the machine function.
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool needsFP (const MachineFunction &MF) const
void replaceFPWithRealFP (MachineFunction &MF) const
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void addScavengingSpillSlot (MachineFunction &MF, RegScavenger *RS) const
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
This function will assign callee saved gprs to volatile vector registers for prologue spills when applicable.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
bool targetHandlesStackFrameRounding () const override
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
unsigned getReturnSaveOffset () const
getReturnSaveOffset - Return the previous frame offset to save the return address.
unsigned getTOCSaveOffset () const
getTOCSaveOffset - Return the previous frame offset to save the TOC register – 64-bit SVR4 ABI only.
unsigned getFramePointerSaveOffset () const
getFramePointerSaveOffset - Return the previous frame offset to save the frame pointer.
unsigned getBasePointerSaveOffset () const
getBasePointerSaveOffset - Return the previous frame offset to save the base pointer.
unsigned getCRSaveOffset () const
getCRSaveOffset - Return the previous frame offset to save the CR register.
unsigned getLinkageSize () const
getLinkageSize - Return the size of the PowerPC ABI linkage area.
const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const override
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
bool enableShrinkWrapping (const MachineFunction &MF) const override
Returns true if the target will correctly handle shrink wrapping.
bool canUseAsPrologue (const MachineBasicBlock &MBB) const override
Methods used by shrink wrapping to determine if MBB can be used for the function prologue/epilogue.
bool canUseAsEpilogue (const MachineBasicBlock &MBB) const override
Check whether or not the given MBB can be used as a epilogue for the target.
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None(), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool isFPCloseToIncomingSP () const
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 22 of file PPCFrameLowering.h.
Constructor & Destructor Documentation
PPCFrameLowering()
PPCFrameLowering::PPCFrameLowering (const PPCSubtarget & STI)
Definition at line 98 of file PPCFrameLowering.cpp.
Member Function Documentation
addScavengingSpillSlot()
void PPCFrameLowering::addScavengingSpillSlot (MachineFunction & MF, RegScavenger * RS) const
Definition at line 2087 of file PPCFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MachineFrameInfo::CreateStackObject(), determineFrameLayout(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::PPCSubtarget::getRegisterInfo(), llvm::TargetRegisterInfo::getSpillAlignment(), llvm::TargetRegisterInfo::getSpillSize(), llvm::TargetFrameLowering::getStackAlignment(), hasNonRISpills(), hasSpills(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::isInt< 16 >(), llvm::PPCSubtarget::isPPC64(), Size, spillsCR(), spillsVRSAVE(), and TRI.
Referenced by processFunctionBeforeFrameFinalized().
assignCalleeSavedSpillSlots()
bool PPCFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
This function will assign callee saved gprs to volatile vector registers for prologue spills when applicable.
It returns false if there are any registers which were not spilled to volatile vector registers.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2130 of file PPCFrameLowering.cpp.
References contains(), EnablePEVectorSpills, llvm::BitVector::find_first(), llvm::TargetRegisterInfo::getAllocatableSet(), llvm::MachineFunction::getFrameInfo(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineFunction::getRegInfo(), llvm::PPCSubtarget::getRegisterInfo(), llvm::MachineFrameInfo::hasCalls(), llvm::PPCSubtarget::hasP9Vector(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::BitVector::none(), Reg, llvm::BitVector::reset(), llvm::BitVector::set_bits(), and llvm::BitVector::size().
canUseAsEpilogue()
bool PPCFrameLowering::canUseAsEpilogue (const MachineBasicBlock & MBB) const override virtual
Check whether or not the given MBB can be used as a epilogue for the target.
The epilogue will be inserted before the first terminator of that block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target. As soon as the target enable shrink-wrapping without overriding this method, we assume that each basic block is a valid epilogue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 725 of file PPCFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::PPCSubtarget::getRedZoneSize(), llvm::PPCSubtarget::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::PPCRegisterInfo::hasBasePointer(), llvm::PPCFunctionInfo::hasFastCall(), hasFP(), llvm::PPCSubtarget::isELFv2ABI(), llvm::PPCSubtarget::isPPC64(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), and llvm::PPCFunctionInfo::usesPICBase().
Referenced by getLinkageSize().
canUseAsPrologue()
bool PPCFrameLowering::canUseAsPrologue (const MachineBasicBlock & MBB) const override virtual
Methods used by shrink wrapping to determine if MBB can be used for the function prologue/epilogue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 718 of file PPCFrameLowering.cpp.
Referenced by getLinkageSize().
determineCalleeSaves()
void PPCFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS = nullptr) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1763 of file PPCFrameLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::PPCFunctionInfo::getBasePointerSaveIndex(), getBasePointerSaveOffset(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), getFramePointerSaveOffset(), llvm::MachineFunction::getInfo(), llvm::PPCSubtarget::getRegisterInfo(), llvm::PPCFunctionInfo::getTailCallSPDelta(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::PPCRegisterInfo::hasBasePointer(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), MustSaveLR(), needsFP(), llvm::TargetMachine::Options, llvm::BitVector::reset(), llvm::PPCFunctionInfo::setBasePointerSaveIndex(), llvm::PPCFunctionInfo::setCRSpillFrameIndex(), llvm::PPCFunctionInfo::setFramePointerSaveIndex(), llvm::PPCFunctionInfo::setMustSaveLR(), llvm::PPCFunctionInfo::setPICBasePointerSaveIndex(), llvm::BitVector::test(), and llvm::PPCFunctionInfo::usesPICBase().
determineFrameLayout()
unsigned PPCFrameLowering::determineFrameLayout (const MachineFunction & MF, bool UseEstimate = false, unsigned * NewMaxCallFrameSize = nullptr) const
Determine the frame layout but do not update the machine function.
determineFrameLayout - Determine the size of the frame and maximum call frame size.
The MachineFunction object can be const in this case as it is not modified.
Definition at line 471 of file PPCFrameLowering.cpp.
References llvm::MachineFrameInfo::adjustsStack(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), getLinkageSize(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::PPCSubtarget::getRedZoneSize(), llvm::PPCSubtarget::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::getStackSize(), llvm::PPCRegisterInfo::hasBasePointer(), llvm::Function::hasFnAttribute(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::max(), MustSaveLR(), and llvm::PPCFunctionInfo::mustSaveTOC().
Referenced by addScavengingSpillSlot(), determineFrameLayoutAndUpdate(), llvm::PPCRegisterInfo::needsFrameBaseReg(), and replaceFPWithRealFP().
determineFrameLayoutAndUpdate()
unsigned PPCFrameLowering::determineFrameLayoutAndUpdate (MachineFunction & MF, bool UseEstimate = false) const
Determine the frame layout and update the machine function.
determineFrameLayoutAndUpdate - Determine the size of the frame and maximum call frame size.
Update the MachineFunction object with the stack size.
Definition at line 458 of file PPCFrameLowering.cpp.
References determineFrameLayout(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::setMaxCallFrameSize(), and llvm::MachineFrameInfo::setStackSize().
Referenced by emitPrologue().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator PPCFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2308 of file PPCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::erase(), llvm::MCInstrInfo::get(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, I, is64Bit(), llvm::isInt< 16 >(), llvm::PPCSubtarget::isPPC64(), llvm::RegState::Kill, llvm::TargetMachine::Options, and TII.
Referenced by restoreCRs().
emitEpilogue()
void PPCFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 1370 of file PPCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::numbers::e, llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::CallingConv::Fast, llvm::PPCFunctionInfo::getBasePointerSaveIndex(), getBasePointerSaveOffset(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::Function::getCallingConv(), getCRSaveOffset(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), getFramePointerSaveOffset(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::PPCFunctionInfo::getMinReservedArea(), llvm::PPCFunctionInfo::getMustSaveCRs(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineOperand::getOffset(), llvm::PPCFunctionInfo::getPICBasePointerSaveIndex(), llvm::PPCSubtarget::getRegisterInfo(), getReturnSaveOffset(), llvm::MachineFrameInfo::getStackSize(), llvm::PPCFunctionInfo::getTailCallSPDelta(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::PPCRegisterInfo::hasBasePointer(), llvm::PPCFunctionInfo::hasFastCall(), hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), Info, llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::MachineOperand::isImm(), llvm::isInt< 16 >(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::RegState::Kill, llvm::ARM_MB::LD, llvm::PPCFunctionInfo::mustSaveLR(), MustSaveLR(), llvm::TargetMachine::Options, llvm::ISD::OR, llvm::SmallVectorBase::size(), TII, and llvm::PPCFunctionInfo::usesPICBase().
emitPrologue()
void PPCFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 775 of file PPCFrameLowering.cpp.
References llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), contains(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), llvm::MCCFIInstruction::createRegister(), determineFrameLayoutAndUpdate(), llvm::numbers::e, E, llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::PPCFunctionInfo::getBasePointerSaveIndex(), getBasePointerSaveOffset(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), getCRSaveOffset(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), getFramePointerSaveOffset(), llvm::MachineFunction::getInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFunction::getMMI(), llvm::PPCFunctionInfo::getMustSaveCRs(), llvm::MachineFrameInfo::getObjectOffset(), llvm::PPCFunctionInfo::getPICBasePointerSaveIndex(), llvm::PPCSubtarget::getRegisterInfo(), llvm::MCContext::getRegisterInfo(), getReturnSaveOffset(), HandleVRSaveUpdate(), llvm::PPCRegisterInfo::hasBasePointer(), hasFP(), I, llvm::RegState::ImplicitKill, Info, llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isELFv2ABI(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::isPowerOf2_32(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::RegState::Kill, llvm_unreachable, llvm::Log2_32(), MRI, llvm::PPCFunctionInfo::mustSaveLR(), MustSaveLR(), llvm::PPCFunctionInfo::mustSaveTOC(), llvm::MachineFunction::needsFrameMoves(), llvm::ISD::OR, R2, Reg, replaceFPWithRealFP(), llvm::report_fatal_error(), llvm::NVPTX::PTXCvtMode::RM, llvm::MachineFrameInfo::setObjectOffset(), llvm::SmallVectorBase::size(), TII, and llvm::PPCFunctionInfo::usesPICBase().
enableShrinkWrapping()
bool PPCFrameLowering::enableShrinkWrapping (const MachineFunction & MF) const override virtual
Returns true if the target will correctly handle shrink wrapping.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2459 of file PPCFrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::PPCSubtarget::isSVR4ABI(), and llvm::PPCFunctionInfo::shrinkWrapDisabled().
Referenced by getLinkageSize().
getBasePointerSaveOffset()
unsigned PPCFrameLowering::getBasePointerSaveOffset () const
getBasePointerSaveOffset - Return the previous frame offset to save the base pointer.
Definition at line 2453 of file PPCFrameLowering.cpp.
References llvm::PPCSubtarget::isAIXABI(), and llvm::report_fatal_error().
Referenced by determineCalleeSaves(), emitEpilogue(), emitPrologue(), and getReturnSaveOffset().
getCalleeSavedSpillSlots()
const PPCFrameLowering::SpillSlot * PPCFrameLowering::getCalleeSavedSpillSlots (unsigned & NumEntries) const override virtual
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Each entry in this array contains a <register,offset> pair, indicating the fixed offset from the incoming stack pointer that each register should be spilled at. If a register is not listed here, the code generator is allowed to spill it anywhere it chooses.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 109 of file PPCFrameLowering.cpp.
References llvm::array_lengthof(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), and llvm::PPCSubtarget::isSVR4ABI().
Referenced by getLinkageSize().
getCRSaveOffset()
unsigned llvm::PPCFrameLowering::getCRSaveOffset () const inline
getCRSaveOffset - Return the previous frame offset to save the CR register.
Definition at line 158 of file PPCFrameLowering.h.
Referenced by emitEpilogue(), and emitPrologue().
getFramePointerSaveOffset()
unsigned PPCFrameLowering::getFramePointerSaveOffset () const
getFramePointerSaveOffset - Return the previous frame offset to save the frame pointer.
Definition at line 2447 of file PPCFrameLowering.cpp.
References llvm::PPCSubtarget::isAIXABI(), and llvm::report_fatal_error().
Referenced by determineCalleeSaves(), emitEpilogue(), emitPrologue(), and getReturnSaveOffset().
getLinkageSize()
unsigned llvm::PPCFrameLowering::getLinkageSize () const inline
getLinkageSize - Return the size of the PowerPC ABI linkage area.
Definition at line 162 of file PPCFrameLowering.h.
References canUseAsEpilogue(), canUseAsPrologue(), enableShrinkWrapping(), and getCalleeSavedSpillSlots().
Referenced by determineFrameLayout(), EnsureStackAlignment(), needStackSlotPassParameters(), and truncateScalarIntegerArg().
getReturnSaveOffset()
unsigned llvm::PPCFrameLowering::getReturnSaveOffset () const inline
getReturnSaveOffset - Return the previous frame offset to save the return address.
Definition at line 142 of file PPCFrameLowering.h.
References getBasePointerSaveOffset(), getFramePointerSaveOffset(), and getTOCSaveOffset().
Referenced by emitEpilogue(), and emitPrologue().
getTOCSaveOffset()
unsigned PPCFrameLowering::getTOCSaveOffset () const
getTOCSaveOffset - Return the previous frame offset to save the TOC register – 64-bit SVR4 ABI only.
Definition at line 2443 of file PPCFrameLowering.cpp.
Referenced by buildCallOperands(), getReturnSaveOffset(), and truncateScalarIntegerArg().
hasFP()
bool PPCFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 533 of file PPCFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), and needsFP().
Referenced by canUseAsEpilogue(), emitEpilogue(), emitPrologue(), llvm::PPCRegisterInfo::getFrameRegister(), and llvm::PPCRegisterInfo::getRegPressureLimit().
needsFP()
bool PPCFrameLowering::needsFP (const MachineFunction & MF) const
Definition at line 544 of file PPCFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::Function::hasFnAttribute(), llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::TargetMachine::Options.
Referenced by determineCalleeSaves(), hasFP(), processFunctionBeforeFrameFinalized(), replaceFPWithRealFP(), and restoreCalleeSavedRegisters().
processFunctionBeforeFrameFinalized()
void PPCFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1837 of file PPCFrameLowering.cpp.
References addScavengingSpillSlot(), assert(), contains(), llvm::numbers::e, llvm::PPCFunctionInfo::getBasePointerSaveIndex(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::PPCFunctionInfo::getPICBasePointerSaveIndex(), llvm::PPCSubtarget::getRegisterInfo(), llvm::MachineFrameInfo::getRestorePoint(), llvm::MachineFrameInfo::getSavePoint(), llvm::PPCFunctionInfo::getTailCallSPDelta(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::PPCRegisterInfo::hasBasePointer(), llvm::PPCSubtarget::hasSPE(), llvm::MachineFrameInfo::hasTailCall(), llvm::PPCSubtarget::isPPC64(), llvm::MachineBasicBlock::isReturnBlock(), llvm::PPCSubtarget::isSVR4ABI(), llvm_unreachable, llvm::PPCFunctionInfo::mustSaveTOC(), needsFP(), llvm::TargetMachine::Options, llvm::SmallVectorTemplateBase< T >::push_back(), R2, Reg, llvm::MachineFrameInfo::setObjectOffset(), llvm::SmallVectorBase::size(), spillsCR(), TRI, and llvm::PPCFunctionInfo::usesPICBase().
replaceFPWithRealFP()
void PPCFrameLowering::replaceFPWithRealFP (MachineFunction & MF) const
Definition at line 558 of file PPCFrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BitVector::count(), determineFrameLayout(), E, llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::RegScavenger::enterBasicBlock(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::RegScavenger::forward(), llvm::MachineFunction::front(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::PPCSubtarget::getRegisterInfo(), llvm::RegScavenger::getRegsAvailable(), llvm::PPCRegisterInfo::hasBasePointer(), I, llvm::isInt< 16 >(), llvm::PPCSubtarget::isPPC64(), llvm::MachineOperand::isReg(), llvm::RegScavenger::isRegUsed(), llvm::MachineBasicBlock::isReturnBlock(), llvm::PPCSubtarget::isSVR4ABI(), needsFP(), llvm::BitVector::reset(), and llvm::MachineOperand::setReg().
Referenced by emitPrologue().
restoreCalleeSavedRegisters()
bool PPCFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2347 of file PPCFrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::numbers::e, llvm::MachineFunction::getInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), I, llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::PPCInstrInfo::loadRegFromStackSlot(), MI, llvm::PPCFunctionInfo::mustSaveTOC(), needsFP(), R2, Reg, restoreCRs(), and TII.
spillCalleeSavedRegisters()
bool PPCFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2184 of file PPCFrameLowering.cpp.
References llvm::addFrameReference(), llvm::MachineBasicBlock::addLiveIn(), llvm::PPCFunctionInfo::addMustSaveCR(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::numbers::e, llvm::MachineFunction::getInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::RegState::ImplicitKill, llvm::MachineBasicBlock::insert(), llvm::PPCSubtarget::isDarwinABI(), llvm::MachineRegisterInfo::isLiveIn(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), MRI, llvm::PPCFunctionInfo::mustSaveTOC(), R2, Reg, llvm::PPCFunctionInfo::setSpillsCR(), llvm::PPCInstrInfo::storeRegToStackSlot(), and TII.
targetHandlesStackFrameRounding()
bool llvm::PPCFrameLowering::targetHandlesStackFrameRounding () const inline override virtual
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
Reimplemented from llvm::TargetFrameLowering.
Definition at line 138 of file PPCFrameLowering.h.
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCFrameLowering.h
lib/Target/PowerPC/PPCFrameLowering.cpp