LLVM: llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager Class Reference
llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager Class Reference
Remote-mapped RuntimeDyld-compatible memory manager.
#include "llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h"
Public Member Functions
~RemoteRTDyldMemoryManager ()
RemoteRTDyldMemoryManager (const RemoteRTDyldMemoryManager &)=delete
RemoteRTDyldMemoryManager & operator= (const RemoteRTDyldMemoryManager &)=delete
RemoteRTDyldMemoryManager (RemoteRTDyldMemoryManager &&)=default
RemoteRTDyldMemoryManager & operator= (RemoteRTDyldMemoryManager &&)=delete
uint8_t * allocateCodeSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName) override
Allocate a memory block of (at least) the given size suitable for executable code.
uint8_t * allocateDataSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName, bool IsReadOnly) override
Allocate a memory block of (at least) the given size suitable for data.
void reserveAllocationSpace (uintptr_t CodeSize, uint32_t CodeAlign, uintptr_t RODataSize, uint32_t RODataAlign, uintptr_t RWDataSize, uint32_t RWDataAlign) override
Inform the memory manager about the total amount of memory required to allocate all sections to be loaded: CodeSize - the total size of all code sections DataSizeRO - the total size of all read-only data sections DataSizeRW - the total size of all read-write data sections.
bool needsToReserveAllocationSpace () override
Override to return true to enable the reserveAllocationSpace callback.
void registerEHFrames (uint8_t *Addr, uint64_t LoadAddr, size_t Size) override
Register the EH frames with the runtime so that c++ exceptions work.
void deregisterEHFrames () override
void notifyObjectLoaded (RuntimeDyld &Dyld, const object::ObjectFile &Obj) override
This method is called after an object has been loaded into memory but before relocations are applied to the loaded sections.
bool finalizeMemory (std::string *ErrMsg=nullptr) override
This method is called when object loading is complete and section page permissions can be applied.
Public Member Functions inherited from llvm::RuntimeDyld::MemoryManager
MemoryManager ()=default
virtual ~MemoryManager ()=default
Friends
class OrcRemoteTargetClient
Detailed Description
Remote-mapped RuntimeDyld-compatible memory manager.
Definition at line 59 of file OrcRemoteTargetClient.h.
Constructor & Destructor Documentation
~RemoteRTDyldMemoryManager()
llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::~RemoteRTDyldMemoryManager () inline
Definition at line 63 of file OrcRemoteTargetClient.h.
References llvm::dbgs(), LLVM_DEBUG, operator=(), and RemoteRTDyldMemoryManager().
RemoteRTDyldMemoryManager() [1/2]
llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::RemoteRTDyldMemoryManager (const RemoteRTDyldMemoryManager &) delete
Referenced by ~RemoteRTDyldMemoryManager().
RemoteRTDyldMemoryManager() [2/2]
llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::RemoteRTDyldMemoryManager (RemoteRTDyldMemoryManager &&) default
Member Function Documentation
allocateCodeSection()
uint8_t* llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::allocateCodeSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName) inline override virtual
Allocate a memory block of (at least) the given size suitable for executable code.
The SectionID is a unique identifier assigned by the RuntimeDyld instance, and optionally recorded by the memory manager to access a loaded section.
Implements llvm::RuntimeDyld::MemoryManager.
Definition at line 74 of file OrcRemoteTargetClient.h.
allocateDataSection()
uint8_t* llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::allocateDataSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName, bool IsReadOnly) inline override virtual
Allocate a memory block of (at least) the given size suitable for data.
The SectionID is a unique identifier assigned by the JIT engine, and optionally recorded by the memory manager to access a loaded section.
Implements llvm::RuntimeDyld::MemoryManager.
Definition at line 86 of file OrcRemoteTargetClient.h.
deregisterEHFrames()
void llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::deregisterEHFrames () inline override virtual
Implements llvm::RuntimeDyld::MemoryManager.
Definition at line 157 of file OrcRemoteTargetClient.h.
finalizeMemory()
bool llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::finalizeMemory (std::string * ErrMsg = nullptr) inline override virtual
This method is called when object loading is complete and section page permissions can be applied.
It is up to the memory manager implementation to decide whether or not to act on this method. The memory manager will typically allocate all sections as read-write and then apply specific permissions when this method is called. Code sections cannot be executed until this function has been called. In addition, any cache coherency operations needed to reliably use the memory are also performed.
Returns true if an error occurred, false otherwise.
Implements llvm::RuntimeDyld::MemoryManager.
Definition at line 179 of file OrcRemoteTargetClient.h.
References llvm::dbgs(), LLVM_DEBUG, llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, and llvm::sys::Memory::MF_WRITE.
needsToReserveAllocationSpace()
bool llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::needsToReserveAllocationSpace () inline override virtual
Override to return true to enable the reserveAllocationSpace callback.
Reimplemented from llvm::RuntimeDyld::MemoryManager.
Definition at line 150 of file OrcRemoteTargetClient.h.
notifyObjectLoaded()
void llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::notifyObjectLoaded (RuntimeDyld & RTDyld, const object::ObjectFile & Obj) inline override virtual
This method is called after an object has been loaded into memory but before relocations are applied to the loaded sections.
Memory managers which are preparing code for execution in an external address space can use this call to remap the section addresses for the newly loaded object.
For clients that do not need access to an ExecutionEngine instance this method should be preferred to its cousin MCJITMemoryManager::notifyObjectLoaded as this method is compatible with ORC JIT stacks.
Reimplemented from llvm::RuntimeDyld::MemoryManager.
Definition at line 164 of file OrcRemoteTargetClient.h.
References llvm::dbgs(), and LLVM_DEBUG.
operator=() [1/2]
RemoteRTDyldMemoryManager& llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::operator= (const RemoteRTDyldMemoryManager &) delete
Referenced by ~RemoteRTDyldMemoryManager().
operator=() [2/2]
RemoteRTDyldMemoryManager& llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::operator= (RemoteRTDyldMemoryManager &&) delete
registerEHFrames()
void llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::registerEHFrames (uint8_t * Addr, uint64_t LoadAddr, size_t Size) inline override virtual
Register the EH frames with the runtime so that c++ exceptions work.
Addr parameter provides the local address of the EH frame section data, while LoadAddr provides the address of the data in the target address space. If the section has not been remapped (which will usually be the case for local execution) these two values will be the same.
Implements llvm::RuntimeDyld::MemoryManager.
Definition at line 152 of file OrcRemoteTargetClient.h.
reserveAllocationSpace()
void llvm::orc::remote::OrcRemoteTargetClient::RemoteRTDyldMemoryManager::reserveAllocationSpace (uintptr_t CodeSize, uint32_t CodeAlign, uintptr_t RODataSize, uint32_t RODataAlign, uintptr_t RWDataSize, uint32_t RWDataAlign) inline override virtual
Inform the memory manager about the total amount of memory required to allocate all sections to be loaded: CodeSize - the total size of all code sections DataSizeRO - the total size of all read-only data sections DataSizeRW - the total size of all read-write data sections.
Note that by default the callback is disabled. To enable it redefine the method needsToReserveAllocationSpace to return true.
Reimplemented from llvm::RuntimeDyld::MemoryManager.
Definition at line 108 of file OrcRemoteTargetClient.h.
References llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
Friends And Related Function Documentation
OrcRemoteTargetClient
friend class OrcRemoteTargetClient friend
Definition at line 60 of file OrcRemoteTargetClient.h.
Referenced by llvm::orc::remote::OrcRemoteTargetClient::terminateSession().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h