LLVM: llvm::LiveRegUnits Class Reference
llvm::LiveRegUnits Class Reference
A set of register units used to track register liveness.
#include "llvm/CodeGen/LiveRegUnits.h"
Public Member Functions
LiveRegUnits ()=default
Constructs a new empty LiveRegUnits set.
LiveRegUnits (const TargetRegisterInfo &TRI)
Constructs and initialize an empty LiveRegUnits set.
void init (const TargetRegisterInfo &TRI)
Initialize and clear the set.
void clear ()
Clears the set.
bool empty () const
Returns true if the set is empty.
void addReg (MCPhysReg Reg)
Adds register units covered by physical register Reg.
void addRegMasked (MCPhysReg Reg, LaneBitmask Mask)
Adds register units covered by physical register Reg that are part of the lanemask Mask.
void removeReg (MCPhysReg Reg)
Removes all register units covered by physical register Reg.
void removeRegsNotPreserved (const uint32_t *RegMask)
Removes register units not preserved by the regmask RegMask.
void addRegsInMask (const uint32_t *RegMask)
Adds register units not preserved by the regmask RegMask.
bool available (MCPhysReg Reg) const
Returns true if no part of physical register Reg is live.
void stepBackward (const MachineInstr &MI)
Updates liveness when stepping backwards over the instruction MI.
void accumulate (const MachineInstr &MI)
Adds all register units used, defined or clobbered in MI.
void addLiveOuts (const MachineBasicBlock &MBB)
Adds registers living out of block MBB.
void addLiveIns (const MachineBasicBlock &MBB)
Adds registers living into block MBB.
void addUnits (const BitVector &RegUnits)
Adds all register units marked in the bitvector RegUnits.
void removeUnits (const BitVector &RegUnits)
Removes all register units marked in the bitvector RegUnits.
const BitVector & getBitVector () const
Return the internal bitvector representation of the set.
Static Public Member Functions
static void accumulateUsedDefed (const MachineInstr &MI, LiveRegUnits &ModifiedRegUnits, LiveRegUnits &UsedRegUnits, const TargetRegisterInfo *TRI)
For a machine instruction MI, adds all register units used in UsedRegUnits and defined or clobbered in ModifiedRegUnits.
Detailed Description
A set of register units used to track register liveness.
Definition at line 30 of file LiveRegUnits.h.
Constructor & Destructor Documentation
LiveRegUnits() [1/2]
llvm::LiveRegUnits::LiveRegUnits () default
Constructs a new empty LiveRegUnits set.
LiveRegUnits() [2/2]
llvm::LiveRegUnits::LiveRegUnits (const TargetRegisterInfo & TRI) inline
Constructs and initialize an empty LiveRegUnits set.
Definition at line 39 of file LiveRegUnits.h.
References init().
Member Function Documentation
accumulate()
void LiveRegUnits::accumulate (const MachineInstr & MI)
Adds all register units used, defined or clobbered in MI.
This is useful when walking over a range of instruction to find registers unused over the whole range.
Definition at line 64 of file LiveRegUnits.cpp.
References addReg(), addRegsInMask(), and llvm::phys_regs_and_masks().
Referenced by available(), canRenameUpToDef(), findSurvivorBackwards(), llvm::outliner::Candidate::initLRU(), false::Chain::str(), and tryToFindRegisterToRename().
accumulateUsedDefed()
static void llvm::LiveRegUnits::accumulateUsedDefed (const MachineInstr & MI, LiveRegUnits & ModifiedRegUnits, LiveRegUnits & UsedRegUnits, const TargetRegisterInfo * TRI) inline static
For a machine instruction MI, adds all register units used in UsedRegUnits and defined or clobbered in ModifiedRegUnits.
This is useful when walking over a range of instructions to track registers used or defined seperately.
Definition at line 47 of file LiveRegUnits.h.
References addReg(), addRegsInMask(), assert(), llvm::TargetRegisterInfo::isConstantPhysReg(), llvm::Register::isPhysical(), llvm::RISCVFenceField::O, and Reg.
Referenced by getRegUnits(), INITIALIZE_PASS(), mayAlias(), and tryToFindRegisterToRename().
addLiveIns()
void LiveRegUnits::addLiveIns (const MachineBasicBlock & MBB)
Adds registers living into block MBB.
Definition at line 136 of file LiveRegUnits.cpp.
References addBlockLiveIns(), and llvm::MachineBasicBlock::getParent().
Referenced by available(), and llvm::RegScavenger::enterBasicBlock().
addLiveOuts()
void LiveRegUnits::addLiveOuts (const MachineBasicBlock & MBB)
Adds registers living out of block MBB.
Live out registers are the union of the live-in registers of the successor blocks and pristine registers. Live out registers of the end block are the callee saved registers.
Definition at line 119 of file LiveRegUnits.cpp.
References addBlockLiveIns(), addCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFrameInfo::isCalleeSavedInfoValid(), llvm::MachineBasicBlock::isReturnBlock(), and llvm::MachineBasicBlock::successors().
Referenced by available(), llvm::RegScavenger::enterBasicBlockEnd(), getTag(), llvm::outliner::Candidate::initLRU(), and false::Chain::str().
addReg()
void llvm::LiveRegUnits::addReg (MCPhysReg Reg) inline
Adds register units covered by physical register Reg.
Definition at line 87 of file LiveRegUnits.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::BitVector::set().
Referenced by accumulate(), accumulateUsedDefed(), addCalleeSavedRegs(), getTag(), stepBackward(), tryToFindRegisterToRename(), and updateDefinedRegisters().
addRegMasked()
void llvm::LiveRegUnits::addRegMasked (MCPhysReg Reg, LaneBitmask Mask) inline
Adds register units covered by physical register Reg that are part of the lanemask Mask.
Definition at line 94 of file LiveRegUnits.h.
References llvm::MCRegUnitMaskIterator::isValid(), llvm::BitmaskEnumDetail::Mask(), llvm::LaneBitmask::none(), and llvm::BitVector::set().
Referenced by addBlockLiveIns(), and llvm::RegScavenger::setRegUsed().
addRegsInMask()
void LiveRegUnits::addRegsInMask (const uint32_t * RegMask)
Adds register units not preserved by the regmask RegMask.
The regmask has the same format as the one in the RegMask machine operand.
Definition at line 35 of file LiveRegUnits.cpp.
References llvm::MachineOperand::clobbersPhysReg(), E, llvm::MCRegisterInfo::getNumRegUnits(), llvm::MCRegUnitRootIterator::isValid(), and llvm::BitVector::set().
Referenced by accumulate(), accumulateUsedDefed(), and removeReg().
addUnits()
void llvm::LiveRegUnits::addUnits (const BitVector & RegUnits) inline
Adds all register units marked in the bitvector RegUnits.
Definition at line 145 of file LiveRegUnits.h.
Referenced by addCalleeSavedRegs(), and llvm::RegScavenger::scavengeRegister().
available()
bool llvm::LiveRegUnits::available (MCPhysReg Reg) const inline
Returns true if no part of physical register Reg is live.
Definition at line 117 of file LiveRegUnits.h.
References accumulate(), addLiveIns(), addLiveOuts(), llvm::MCRegisterInfo::DiffListIterator::isValid(), MI, stepBackward(), and llvm::BitVector::test().
Referenced by clearKillFlags(), findSurvivorBackwards(), llvm::RISCVInstrInfo::getOutliningCandidateInfo(), llvm::AArch64InstrInfo::getOutliningCandidateInfo(), getTag(), hasRegisterDependency(), INITIALIZE_PASS(), llvm::RegScavenger::isRegUsed(), false::Chain::str(), and tryToFindRegisterToRename().
clear()
void llvm::LiveRegUnits::clear () inline
Clears the set.
Definition at line 81 of file LiveRegUnits.h.
References llvm::BitVector::reset().
Referenced by getTag(), and INITIALIZE_PASS().
empty()
bool llvm::LiveRegUnits::empty () const inline
Returns true if the set is empty.
Definition at line 84 of file LiveRegUnits.h.
References llvm::BitVector::none().
Referenced by addCalleeSavedRegs().
getBitVector()
const BitVector& llvm::LiveRegUnits::getBitVector () const inline
Return the internal bitvector representation of the set.
Definition at line 153 of file LiveRegUnits.h.
Referenced by addCalleeSavedRegs().
init()
void llvm::LiveRegUnits::init (const TargetRegisterInfo & TRI) inline
Initialize and clear the set.
Definition at line 74 of file LiveRegUnits.h.
References llvm::MCRegisterInfo::getNumRegUnits(), llvm::BitVector::reset(), and llvm::BitVector::resize().
Referenced by INITIALIZE_PASS(), llvm::outliner::Candidate::initLRU(), LiveRegUnits(), llvm::RegScavenger::setRegUsed(), and tryToFindRegisterToRename().
removeReg()
void llvm::LiveRegUnits::removeReg (MCPhysReg Reg) inline
Removes all register units covered by physical register Reg.
Definition at line 103 of file LiveRegUnits.h.
References addRegsInMask(), llvm::MCRegisterInfo::DiffListIterator::isValid(), removeRegsNotPreserved(), and llvm::BitVector::reset().
Referenced by addCalleeSavedRegs(), llvm::RegScavenger::scavengeRegisterBackwards(), stepBackward(), and updateDefinedRegisters().
removeRegsNotPreserved()
void LiveRegUnits::removeRegsNotPreserved (const uint32_t * RegMask)
Removes register units not preserved by the regmask RegMask.
The regmask has the same format as the one in the RegMask machine operand.
Definition at line 26 of file LiveRegUnits.cpp.
References llvm::MachineOperand::clobbersPhysReg(), E, llvm::MCRegisterInfo::getNumRegUnits(), llvm::MCRegUnitRootIterator::isValid(), and llvm::BitVector::reset().
Referenced by removeReg(), and stepBackward().
removeUnits()
void llvm::LiveRegUnits::removeUnits (const BitVector & RegUnits) inline
Removes all register units marked in the bitvector RegUnits.
Definition at line 149 of file LiveRegUnits.h.
References llvm::BitVector::reset().
Referenced by llvm::RegScavenger::scavengeRegister().
stepBackward()
void LiveRegUnits::stepBackward (const MachineInstr & MI)
Updates liveness when stepping backwards over the instruction MI.
This removes all register units defined or clobbered in MI and then adds the units used (as in use operands) in MI.
Definition at line 44 of file LiveRegUnits.cpp.
References addReg(), llvm::phys_regs_and_masks(), removeReg(), and removeRegsNotPreserved().
Referenced by available(), llvm::RegScavenger::backward(), getTag(), llvm::outliner::Candidate::initLRU(), and false::Chain::str().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveRegUnits.h
lib/CodeGen/LiveRegUnits.cpp