LLVM: llvm::AArch64FunctionInfo::MILOHDirective Class Reference
llvm::AArch64FunctionInfo::MILOHDirective Class Reference
#include "Target/AArch64/AArch64MachineFunctionInfo.h"
Public Types
using LOHArgs = ArrayRef< const MachineInstr * >
Public Member Functions
MILOHDirective (MCLOHType Kind, LOHArgs Args)
MCLOHType getKind () const
LOHArgs getArgs () const
Detailed Description
Definition at line 288 of file AArch64MachineFunctionInfo.h.
Member Typedef Documentation
LOHArgs
using llvm::AArch64FunctionInfo::MILOHDirective::LOHArgs = ArrayRef<const MachineInstr *>
Definition at line 295 of file AArch64MachineFunctionInfo.h.
Constructor & Destructor Documentation
MILOHDirective()
llvm::AArch64FunctionInfo::MILOHDirective::MILOHDirective (MCLOHType Kind, LOHArgs Args) inline
Definition at line 297 of file AArch64MachineFunctionInfo.h.
References assert(), and llvm::isValidMCLOHType().
Referenced by llvm::AArch64FunctionInfo::addLOHDirective().
Member Function Documentation
getArgs()
LOHArgs llvm::AArch64FunctionInfo::MILOHDirective::getArgs () const inline
Definition at line 303 of file AArch64MachineFunctionInfo.h.
getKind()
MCLOHType llvm::AArch64FunctionInfo::MILOHDirective::getKind () const inline
Definition at line 302 of file AArch64MachineFunctionInfo.h.
The documentation for this class was generated from the following file:
lib/Target/AArch64/AArch64MachineFunctionInfo.h