LLVM: llvm::MCSectionMachO Class Reference
llvm::MCSectionMachO Class Reference final
This represents a section on a Mach-O system (used by Mac OS X).
#include "llvm/MC/MCSectionMachO.h"
Public Member Functions
StringRef getSegmentName () const
StringRef getSectionName () const
unsigned getTypeAndAttributes () const
unsigned getStubSize () const
MachO::SectionType getType () const
bool hasAttribute (unsigned Value) const
void PrintSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const override
bool UseCodeAlign () const override
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
bool isVirtualSection () const override
Check whether this section is "virtual", that is has no actual object file contents.
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
SectionKind getKind () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
unsigned getAlignment () const
void setAlignment (Align Value)
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
MCSection::FragmentListType & getFragmentList ()
const MCSection::FragmentListType & getFragmentList () const
const MCDummyFragment & getDummyFragment () const
MCDummyFragment & getDummyFragment ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
MCSection::iterator getSubsectionInsertionPoint (unsigned Subsection)
void dump () const
void addPendingLabel (MCSymbol *label, unsigned Subsection=0)
Add a pending label for the requested subsection.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0, unsigned Subsection=0)
Associate all pending labels in a subsection with a fragment.
void flushPendingLabels ()
Associate all pending labels with empty data fragments.
Static Public Member Functions
static std::string ParseSectionSpecifier (StringRef Spec, StringRef &Segment, StringRef &Section, unsigned &TAA, bool &TAAParsed, unsigned &StubSize)
Parse the section specifier indicated by "Spec".
static bool classof (const MCSection *S)
Static Public Member Functions inherited from llvm::MCSection
static FragmentListType MCSection::* getSublistAccess (MCFragment *)
Support for MCFragment::getNextNode().
Friends
class MCContext
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant {
SV_COFF = 0, SV_ELF, SV_MachO, SV_Wasm,
SV_XCOFF
}
enum BundleLockStateType { NotBundleLocked, BundleLocked, BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
using FragmentListType = iplist< MCFragment >
using const_iterator = FragmentListType::const_iterator
using iterator = FragmentListType::iterator
using const_reverse_iterator = FragmentListType::const_reverse_iterator
using reverse_iterator = FragmentListType::reverse_iterator
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, SectionKind K, MCSymbol *Begin)
~MCSection ()
Protected Attributes inherited from llvm::MCSection
SectionVariant Variant
SectionKind Kind
Detailed Description
This represents a section on a Mach-O system (used by Mac OS X).
On a Mac system, these are also described in /usr/include/mach-o/loader.h.
Definition at line 24 of file MCSectionMachO.h.
Member Function Documentation
classof()
static bool llvm::MCSectionMachO::classof (const MCSection * S) inline static
Definition at line 84 of file MCSectionMachO.h.
References llvm::MCSection::getVariant(), and llvm::MCSection::SV_MachO.
getSectionName()
StringRef llvm::MCSectionMachO::getSectionName () const inline
Definition at line 47 of file MCSectionMachO.h.
Referenced by canGoAfterDWARF(), canUseLocalRelocation(), llvm::MCAsmInfoDarwin::isSectionAtomizableBySymbols(), and PrintSwitchToSection().
getSegmentName()
StringRef llvm::MCSectionMachO::getSegmentName () const inline
Definition at line 41 of file MCSectionMachO.h.
Referenced by canGoAfterDWARF(), canUseLocalRelocation(), getPlatformName(), llvm::MCAsmInfoDarwin::isSectionAtomizableBySymbols(), and PrintSwitchToSection().
getStubSize()
unsigned llvm::MCSectionMachO::getStubSize () const inline
Definition at line 55 of file MCSectionMachO.h.
getType()
MachO::SectionType llvm::MCSectionMachO::getType () const inline
Definition at line 57 of file MCSectionMachO.h.
References llvm::MachO::SECTION_TYPE.
Referenced by llvm::MachObjectWriter::bindIndirectSymbols(), canUseLocalRelocation(), llvm::MCAsmInfoDarwin::isSectionAtomizableBySymbols(), isVirtualSection(), and PrintSwitchToSection().
getTypeAndAttributes()
unsigned llvm::MCSectionMachO::getTypeAndAttributes () const inline
Definition at line 54 of file MCSectionMachO.h.
Referenced by llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), and PrintSwitchToSection().
hasAttribute()
bool llvm::MCSectionMachO::hasAttribute (unsigned Value) const inline
Definition at line 61 of file MCSectionMachO.h.
References isVirtualSection(), ParseSectionSpecifier(), PrintSwitchToSection(), and UseCodeAlign().
Referenced by canUseLocalRelocation(), canUsePrivateLabel(), getFixupKindLog2Size(), and UseCodeAlign().
isVirtualSection()
bool MCSectionMachO::isVirtualSection () const override virtual
Check whether this section is "virtual", that is has no actual object file contents.
Implements llvm::MCSection.
Definition at line 171 of file MCSectionMachO.cpp.
References getType(), llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_THREAD_LOCAL_ZEROFILL, and llvm::MachO::S_ZEROFILL.
Referenced by hasAttribute(), and llvm::MachObjectWriter::writeSection().
ParseSectionSpecifier()
std::string MCSectionMachO::ParseSectionSpecifier (StringRef Spec, StringRef & Segment, StringRef & Section, unsigned & TAA, bool & TAAParsed, unsigned & StubSize) static
Parse the section specifier indicated by "Spec".
ParseSectionSpecifier - Parse the section specifier indicated by "Spec".
This is a string that can appear after a .section directive in a mach-o flavored .s file. If successful, this fills in the specified Out parameters and returns an empty string. When an invalid section specifier is present, this returns a string indicating the problem. If no TAA was parsed, TAA is not altered, and TAAWasSet becomes false.
This is a string that can appear after a .section directive in a mach-o flavored .s file. If successful, this fills in the specified Out parameters and returns an empty string. When an invalid section specifier is present, this returns a string indicating the problem.
Definition at line 182 of file MCSectionMachO.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::sys::path::begin(), llvm::StringRef::empty(), llvm::sys::path::end(), llvm::find_if(), llvm::StringRef::getAsInteger(), llvm::MachO::S_SYMBOL_STUBS, llvm::MachO::SECTION_TYPE, SectionAttrDescriptors, SectionTypeDescriptors, llvm::SmallVectorBase::size(), llvm::StringRef::size(), and llvm::StringRef::split().
Referenced by llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), hasAttribute(), and instrumentMaskedLoadOrStore().
PrintSwitchToSection()
void MCSectionMachO::PrintSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, const MCExpr * Subsection) const override virtual
Implements llvm::MCSection.
Definition at line 103 of file MCSectionMachO.cpp.
References AssemblerName, assert(), AttrFlag, llvm::StringRef::empty(), getSectionName(), getSegmentName(), getType(), getTypeAndAttributes(), llvm::MachO::LAST_KNOWN_SECTION_TYPE, llvm::MachO::SECTION_ATTRIBUTES, SectionAttrDescriptors, and SectionTypeDescriptors.
Referenced by hasAttribute().
UseCodeAlign()
bool MCSectionMachO::UseCodeAlign () const override virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implements llvm::MCSection.
Definition at line 167 of file MCSectionMachO.cpp.
References hasAttribute(), and llvm::MachO::S_ATTR_PURE_INSTRUCTIONS.
Referenced by hasAttribute().
Friends And Related Function Documentation
MCContext
friend class MCContext friend
Definition at line 38 of file MCSectionMachO.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSectionMachO.h
lib/MC/MCSectionMachO.cpp