LLVM: llvm::LoopRotatePass Class Reference
llvm::LoopRotatePass Class Reference
A simple loop rotation transformation.
#include "llvm/Transforms/Scalar/LoopRotation.h"
Public Member Functions
LoopRotatePass (bool EnableHeaderDuplication=true)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopRotatePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A simple loop rotation transformation.
Definition at line 23 of file LoopRotation.h.
Constructor & Destructor Documentation
LoopRotatePass()
LoopRotatePass::LoopRotatePass (bool EnableHeaderDuplication = true)
Definition at line 36 of file LoopRotation.cpp.
Member Function Documentation
run()
PreservedAnalyses LoopRotatePass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 39 of file LoopRotation.cpp.
References llvm::LoopStandardAnalysisResults::AC, llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::PreservedAnalyses::all(), DefaultRotationThreshold, llvm::LoopStandardAnalysisResults::DT, llvm::EnableMSSALoopDependency, F(), llvm::getBestSimplifyQuery(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopAnalysisUsage(), llvm::getLoopPassPreservedAnalyses(), llvm::BasicBlock::getModule(), llvm::BasicBlock::getParent(), llvm::PassRegistry::getPassRegistry(), llvm::Optional< T >::getPointer(), llvm::Optional< T >::hasValue(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeLoopRotateLegacyPassPass(), llvm::LoopStandardAnalysisResults::LI, llvm::LoopRotation(), llvm::LoopStandardAnalysisResults::MSSA, llvm::LoopStandardAnalysisResults::SE, Threshold, llvm::LoopStandardAnalysisResults::TTI, llvm::VerifyMemorySSA, and llvm::MemorySSA::verifyMemorySSA().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopRotation.h
lib/Transforms/Scalar/LoopRotation.cpp