LLVM: llvm::IRMover::IdentifiedStructTypeSet Class Reference
llvm::IRMover::IdentifiedStructTypeSet Class Reference
#include "llvm/Linker/IRMover.h"
Public Member Functions
void addNonOpaque (StructType *Ty)
void switchToNonOpaque (StructType *Ty)
void addOpaque (StructType *Ty)
StructType * findNonOpaque (ArrayRef< Type *> ETypes, bool IsPacked)
bool hasType (StructType *Ty)
Detailed Description
Definition at line 47 of file IRMover.h.
Member Function Documentation
addNonOpaque()
void IRMover::IdentifiedStructTypeSet::addNonOpaque (StructType * Ty)
Definition at line 1530 of file IRMover.cpp.
References assert(), and llvm::StructType::isOpaque().
Referenced by llvm::IRMover::IRMover().
addOpaque()
void IRMover::IdentifiedStructTypeSet::addOpaque (StructType * Ty)
Definition at line 1543 of file IRMover.cpp.
References assert(), and llvm::StructType::isOpaque().
Referenced by llvm::IRMover::IRMover().
findNonOpaque()
StructType * IRMover::IdentifiedStructTypeSet::findNonOpaque (ArrayRef< Type *> ETypes, bool IsPacked)
Definition at line 1549 of file IRMover.cpp.
References I.
hasType()
bool IRMover::IdentifiedStructTypeSet::hasType (StructType * Ty)
Definition at line 1556 of file IRMover.cpp.
References false, I, and llvm::StructType::isOpaque().
switchToNonOpaque()
void IRMover::IdentifiedStructTypeSet::switchToNonOpaque (StructType * Ty)
Definition at line 1535 of file IRMover.cpp.
References assert(), and llvm::StructType::isOpaque().
The documentation for this class was generated from the following files:
include/llvm/Linker/IRMover.h
lib/Linker/IRMover.cpp