LLVM: llvm::Attribute Class Reference
llvm::Attribute Class Reference
#include "llvm/IR/Attributes.h"
Public Types
enum AttrKind { None, EndAttrKinds }
This enumeration lists the attributes that can be associated with parameters, function results, or the function itself.
Public Member Functions
Attribute ()=default
bool isEnumAttribute () const
Return true if the attribute is an Attribute::AttrKind type.
bool isIntAttribute () const
Return true if the attribute is an integer attribute.
bool isStringAttribute () const
Return true if the attribute is a string (target-dependent) attribute.
bool isTypeAttribute () const
Return true if the attribute is a type attribute.
bool hasAttribute (AttrKind Val) const
Return true if the attribute is present.
bool hasAttribute (StringRef Val) const
Return true if the target-dependent attribute is present.
Attribute::AttrKind getKindAsEnum () const
Return the attribute's kind as an enum (Attribute::AttrKind).
uint64_t getValueAsInt () const
Return the attribute's value as an integer.
StringRef getKindAsString () const
Return the attribute's kind as a string.
StringRef getValueAsString () const
Return the attribute's value as a string.
Type * getValueAsType () const
Return the attribute's value as a Type.
MaybeAlign getAlignment () const
Returns the alignment field of an attribute as a byte alignment value.
MaybeAlign getStackAlignment () const
Returns the stack alignment field of an attribute as a byte alignment value.
uint64_t getDereferenceableBytes () const
Returns the number of dereferenceable bytes from the dereferenceable attribute.
uint64_t getDereferenceableOrNullBytes () const
Returns the number of dereferenceable_or_null bytes from the dereferenceable_or_null attribute.
std::pair< unsigned, Optional< unsigned > > getAllocSizeArgs () const
Returns the argument numbers for the allocsize attribute (or pair(0, 0) if not known).
std::string getAsString (bool InAttrGrp=false) const
The Attribute is converted to a string of equivalent mnemonic.
bool operator== (Attribute A) const
Equality and non-equality operators.
bool operator!= (Attribute A) const
bool operator< (Attribute A) const
Less-than operator. Useful for sorting the attributes list.
void Profile (FoldingSetNodeID &ID) const
void * getRawPointer () const
Return a raw pointer that uniquely identifies this attribute.
Static Public Member Functions
static Attribute get (LLVMContext &Context, AttrKind Kind, uint64_t Val=0)
Return a uniquified Attribute object.
static Attribute get (LLVMContext &Context, StringRef Kind, StringRef Val=StringRef())
static Attribute get (LLVMContext &Context, AttrKind Kind, Type *Ty)
static Attribute getWithAlignment (LLVMContext &Context, Align Alignment)
Return a uniquified Attribute object that has the specific alignment set.
static Attribute getWithStackAlignment (LLVMContext &Context, Align Alignment)
static Attribute getWithDereferenceableBytes (LLVMContext &Context, uint64_t Bytes)
static Attribute getWithDereferenceableOrNullBytes (LLVMContext &Context, uint64_t Bytes)
static Attribute getWithAllocSizeArgs (LLVMContext &Context, unsigned ElemSizeArg, const Optional< unsigned > &NumElemsArg)
static Attribute getWithByValType (LLVMContext &Context, Type *Ty)
static Attribute fromRawPointer (void *RawPtr)
Get an attribute from a raw pointer created by getRawPointer.
Detailed Description
Definition at line 51 of file Attributes.h.
Member Enumeration Documentation
AttrKind
enum llvm::Attribute::AttrKind
This enumeration lists the attributes that can be associated with parameters, function results, or the function itself.
Note: The `uwtable' attribute is about the ABI or the user mandating an entry in the unwind table. The `nounwind' attribute is about an exception passing by the function.
In a theoretical system that uses tables for profiling and SjLj for exceptions, they would be fully independent. In a normal system that uses tables for both, the semantics are:
nil = Needs an entry because an exception might pass by. nounwind = No need for an entry uwtable = Needs an entry because the ABI says so and because an exception might pass by. uwtable + nounwind = Needs an entry because the ABI says so.
Enumerator
None
No attributes have been set.
EndAttrKinds
Sentinal value useful for loops.
Definition at line 70 of file Attributes.h.
Constructor & Destructor Documentation
Attribute()
llvm::Attribute::Attribute () default
Referenced by fromRawPointer(), get(), and llvm::AttributeSet::getAttribute().
Member Function Documentation
fromRawPointer()
static Attribute llvm::Attribute::fromRawPointer (void * RawPtr) inline static
Get an attribute from a raw pointer created by getRawPointer.
Definition at line 193 of file Attributes.h.
References Attribute().
Referenced by llvm::unwrap().
get() [1/3]
Attribute Attribute::get (LLVMContext & Context, Attribute::AttrKind Kind, uint64_t Val = 0) static
Return a uniquified Attribute object.
Definition at line 80 of file Attributes.cpp.
References llvm::FoldingSetNodeID::AddInteger(), Attribute(), llvm::LLVMContextImpl::AttrsSet, and llvm::LLVMContext::pImpl.
Referenced by AddCalls(), llvm::Function::addFnAttr(), annotateAnyAllocSite(), llvm::AttributeSetNode::get(), llvm::AttributeList::get(), llvm::IRPosition::getAttrs(), llvm::IRAttribute< Attribute::Returned, AbstractAttribute >::getDeducedAttributes(), LLVMAddTargetDependentFunctionAttr(), LLVMCreateEnumAttribute(), LLVMCreateStringAttribute(), processCallSite(), RemoveNonValidAttrAtIndex(), setInlineRemark(), and llvm::VFABI::setVectorVariantNames().
get() [2/3]
Attribute Attribute::get (LLVMContext & Context, StringRef Kind, StringRef Val = StringRef()) static
Definition at line 104 of file Attributes.cpp.
References llvm::FoldingSetNodeID::AddString(), Attribute(), llvm::LLVMContextImpl::AttrsSet, llvm::StringRef::empty(), and llvm::LLVMContext::pImpl.
get() [3/3]
Attribute Attribute::get (LLVMContext & Context, Attribute::AttrKind Kind, Type * Ty) static
Definition at line 124 of file Attributes.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::FoldingSetNodeID::AddPointer(), Attribute(), llvm::LLVMContextImpl::AttrsSet, and llvm::LLVMContext::pImpl.
getAlignment()
MaybeAlign Attribute::getAlignment () const
Returns the alignment field of an attribute as a byte alignment value.
Definition at line 244 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsInt(), and hasAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), and llvm::AttributeSet::hasAttributes().
getAllocSizeArgs()
std::pair< unsigned, Optional< unsigned > > Attribute::getAllocSizeArgs () const
Returns the argument numbers for the allocsize attribute (or pair(0, 0) if not known).
Definition at line 270 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsInt(), hasAttribute(), and unpackAllocSizeArgs().
Referenced by getAllocationSize(), getAsString(), llvm::AttrBuilder::getByValType(), llvm::AttributeList::getParamDereferenceableOrNullBytes(), and llvm::AttributeSet::hasAttributes().
getAsString()
std::string Attribute::getAsString (bool InAttrGrp = false) const
The Attribute is converted to a string of equivalent mnemonic.
This is, presumably, for writing out the mnemonics for the assembly writer.
Definition at line 276 of file Attributes.cpp.
References llvm::CallingConv::Cold, llvm::MCID::Convergent, llvm::raw_ostream::flush(), getAllocSizeArgs(), getKindAsString(), getValueAsInt(), llvm::AttributeImpl::getValueAsString(), getValueAsType(), hasAttribute(), llvm::Optional< T >::hasValue(), isStringAttribute(), llvm::ISD::JumpTable, llvm_unreachable, Name, llvm::NoAlias, llvm::printEscapedString(), and llvm::utostr().
Referenced by llvm::AttributeSet::dump(), llvm::AttributeList::getParamDereferenceableOrNullBytes(), and llvm::AttributeSet::hasAttributes().
getDereferenceableBytes()
uint64_t Attribute::getDereferenceableBytes () const
Returns the number of dereferenceable bytes from the dereferenceable attribute.
Definition at line 256 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsInt(), and hasAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), llvm::AttributeList::getParamAttr(), llvm::AttributeList::getParamDereferenceableBytes(), and llvm::AttributeSet::hasAttributes().
getDereferenceableOrNullBytes()
uint64_t Attribute::getDereferenceableOrNullBytes () const
Returns the number of dereferenceable_or_null bytes from the dereferenceable_or_null attribute.
Definition at line 263 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsInt(), and hasAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), llvm::AttributeList::getParamDereferenceableBytes(), llvm::AttributeList::getParamDereferenceableOrNullBytes(), and llvm::AttributeSet::hasAttributes().
getKindAsEnum()
Attribute::AttrKind Attribute::getKindAsEnum () const
Return the attribute's kind as an enum (Attribute::AttrKind).
This requires the attribute to be an enum or integer attribute.
Definition at line 199 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getKindAsEnum(), isEnumAttribute(), isIntAttribute(), isTypeAttribute(), and None.
Referenced by llvm::AttrBuilder::addAttribute(), addIfNotExistent(), llvm::FunctionComparator::cmpMem(), llvm::IRPosition::getAttrs(), llvm::AttributeImpl::hasAttribute(), LLVMGetEnumAttributeKind(), and llvm::AttributeImpl::operator<().
getKindAsString()
StringRef Attribute::getKindAsString () const
Return the attribute's kind as a string.
This requires the attribute to be a string attribute.
Definition at line 213 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getKindAsString(), and isStringAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), addIfNotExistent(), getAsString(), llvm::AttributeImpl::hasAttribute(), LLVMGetStringAttributeKind(), and llvm::AttributeImpl::operator<().
getRawPointer()
void* llvm::Attribute::getRawPointer () const inline
Return a raw pointer that uniquely identifies this attribute.
Definition at line 188 of file Attributes.h.
Referenced by llvm::wrap().
getStackAlignment()
MaybeAlign Attribute::getStackAlignment () const
Returns the stack alignment field of an attribute as a byte alignment value.
Definition at line 250 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsInt(), and hasAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), llvm::AttributeList::getParamAttr(), and llvm::AttributeSet::hasAttributes().
getValueAsInt()
uint64_t Attribute::getValueAsInt () const
Return the attribute's value as an integer.
This requires that the attribute be an integer attribute.
Definition at line 206 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsInt(), and isIntAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), getAsString(), isEqualOrWorse(), and llvm::AttributeImpl::operator<().
getValueAsString()
StringRef Attribute::getValueAsString () const
Return the attribute's value as a string.
This requires the attribute to be a string attribute.
Definition at line 220 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsString(), and isStringAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), AddCalls(), adjustCallerStackProbeSize(), adjustMinLegalVectorWidth(), llvm::NVPTXTargetLowering::allowUnsafeFPMath(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::TargetLoweringBase::areJTsAllowed(), llvm::AArch64InstrInfo::buildOutlinedFrame(), CC_RISCV_FastCC(), NoAutoPaddingScope::changeAndComment(), checkFunctionsAttributeConsistency(), llvm::TargetOptions::DisableFramePointerElim(), doesNotGeneratecode(), eliminateTailRecursion(), llvm::AsmPrinter::EmitDebugValue(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::MipsSEFrameLowering::emitPrologue(), FixedPointIntrinsicToOpcode(), foldFPToIntToFP(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), llvm::MachineFunction::getDenormalMode(), getDeoptLowering(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::AMDGPUTargetMachine::getFeatureString(), llvm::AMDGPUTargetMachine::getGPUName(), llvm::AMDGPU::getIntegerAttribute(), llvm::AMDGPU::getIntegerPairAttribute(), getRecipEstimateForFunc(), llvm::X86TargetLowering::getStackProbeSize(), llvm::X86TargetLowering::getStackProbeSymbolName(), getSubOpcode(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::VFABI::getVectorVariantNames(), hasUnsafeFPMath(), isFuncOrArgAttr(), llvm::RecurrenceDescriptor::isReductionPHI(), isThumbFunction(), llvm::LoopVectorizationLegality::isUniform(), llvm::AMDGPULibCalls::isUnsafeMath(), LLVMGetStringAttributeValue(), llvm::CallLowering::lowerCall(), LowerInterruptReturn(), llvm::AttributeImpl::operator<(), outliningCandidatesSigningKeyConsensus(), outliningCandidatesSigningScopeConsensus(), llvm::parseStatepointDirectivesFromAttrs(), replaceAllPrepares(), runOnFunction(), llvm::StackProtector::runOnFunction(), ShouldSignReturnAddress(), ShouldSignWithAKey(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), llvm::AMDGPU::SIModeRegisterDefaults::SIModeRegisterDefaults(), SimplifyNVVMIntrinsic(), llvm::NVPTXTargetLowering::useF32FTZ(), WindowsRequiresStackProbe(), and windowsRequiresStackProbe().
getValueAsType()
Type * Attribute::getValueAsType () const
Return the attribute's value as a Type.
This requires the attribute to be a type attribute.
Definition at line 227 of file Attributes.cpp.
References assert(), llvm::AttributeImpl::getValueAsType(), and isTypeAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), llvm::FunctionComparator::cmpMem(), forceRenaming(), getAsString(), llvm::CallLowering::setArgFlags(), and wrapConstantAsMetadata().
getWithAlignment()
Attribute Attribute::getWithAlignment (LLVMContext & Context, Align Alignment) static
Return a uniquified Attribute object that has the specific alignment set.
Definition at line 145 of file Attributes.cpp.
References assert(), Context, and llvm::Align::value().
Referenced by llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::AttributeSetNode::get(), llvm::IRPosition::getAttrs(), LLVMSetInstrParamAlignment(), LLVMSetParamAlignment(), llvm::MemIntrinsicBase< AnyMemIntrinsic >::setDestAlignment(), and llvm::MemTransferBase< AnyMemIntrinsic >::setSourceAlignment().
getWithAllocSizeArgs()
Attribute Attribute::getWithAllocSizeArgs (LLVMContext & Context, unsigned ElemSizeArg, const Optional< unsigned > & NumElemsArg) static
Definition at line 172 of file Attributes.cpp.
References assert(), Context, and packAllocSizeArgs().
Referenced by llvm::AttributeSetNode::get().
getWithByValType()
Attribute Attribute::getWithByValType (LLVMContext & Context, Type * Ty) static
Definition at line 167 of file Attributes.cpp.
References Context.
Referenced by annotateAnyAllocSite(), forceRenaming(), llvm::AttributeSetNode::get(), LLVMCreateEnumAttribute(), and wrapConstantAsMetadata().
getWithDereferenceableBytes()
Attribute Attribute::getWithDereferenceableBytes (LLVMContext & Context, uint64_t Bytes) static
Definition at line 155 of file Attributes.cpp.
References assert(), and Context.
Referenced by annotateAnyAllocSite(), annotateDereferenceableBytes(), llvm::AttributeSetNode::get(), and llvm::IRPosition::getAttrs().
getWithDereferenceableOrNullBytes()
Attribute Attribute::getWithDereferenceableOrNullBytes (LLVMContext & Context, uint64_t Bytes) static
Definition at line 161 of file Attributes.cpp.
References assert(), and Context.
Referenced by annotateAnyAllocSite(), llvm::AttributeSetNode::get(), and llvm::IRPosition::getAttrs().
getWithStackAlignment()
Attribute Attribute::getWithStackAlignment (LLVMContext & Context, Align Alignment) static
Definition at line 150 of file Attributes.cpp.
References assert(), Context, and llvm::Align::value().
Referenced by llvm::AttributeSetNode::get().
hasAttribute() [1/2]
bool Attribute::hasAttribute (AttrKind Val) const
Return true if the attribute is present.
Definition at line 235 of file Attributes.cpp.
References llvm::AttributeImpl::hasAttribute(), and None.
Referenced by llvm::AttributeList::addAllocSizeParamAttr(), llvm::AttributeSet::addAttribute(), AddCalls(), getAlignment(), getAllocSizeArgs(), getAsString(), llvm::AttributeSetNode::getAttribute(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), llvm::AMDGPUTargetMachine::getFeatureString(), llvm::AMDGPUTargetMachine::getGPUName(), getStackAlignment(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::AttributeSet::hasAttributes(), llvm::AttributeList::hasParamAttr(), llvm::isStatepointDirectiveAttr(), isThumbFunction(), and llvm::AttributeSet::removeAttribute().
hasAttribute() [2/2]
bool Attribute::hasAttribute (StringRef Val) const
Return true if the target-dependent attribute is present.
Definition at line 239 of file Attributes.cpp.
References llvm::AttributeImpl::hasAttribute(), and isStringAttribute().
isEnumAttribute()
bool Attribute::isEnumAttribute () const
Return true if the attribute is an Attribute::AttrKind type.
Definition at line 183 of file Attributes.cpp.
References llvm::AttributeImpl::isEnumAttribute().
Referenced by addIfNotExistent(), llvm::AttributeImpl::getKindAsEnum(), getKindAsEnum(), and llvm::AttributeImpl::operator<().
isIntAttribute()
bool Attribute::isIntAttribute () const
Return true if the attribute is an integer attribute.
Definition at line 187 of file Attributes.cpp.
References llvm::AttributeImpl::isIntAttribute().
Referenced by addIfNotExistent(), llvm::AttributeImpl::getKindAsEnum(), getKindAsEnum(), llvm::AttributeImpl::getValueAsInt(), getValueAsInt(), isEqualOrWorse(), and llvm::AttributeImpl::operator<().
isStringAttribute()
bool Attribute::isStringAttribute () const
Return true if the attribute is a string (target-dependent) attribute.
Definition at line 191 of file Attributes.cpp.
References llvm::AttributeImpl::isStringAttribute().
Referenced by llvm::AttrBuilder::addAttribute(), addIfNotExistent(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), getAsString(), llvm::AMDGPU::getIntegerAttribute(), llvm::AMDGPU::getIntegerPairAttribute(), llvm::AttributeImpl::getKindAsString(), getKindAsString(), llvm::AttributeImpl::getValueAsString(), getValueAsString(), llvm::AttributeImpl::hasAttribute(), hasAttribute(), LLVMIsStringAttribute(), llvm::AttributeImpl::operator<(), llvm::parseStatepointDirectivesFromAttrs(), and llvm::StackProtector::runOnFunction().
isTypeAttribute()
bool Attribute::isTypeAttribute () const
Return true if the attribute is a type attribute.
Definition at line 195 of file Attributes.cpp.
References llvm::AttributeImpl::isTypeAttribute().
Referenced by llvm::FunctionComparator::cmpMem(), llvm::AttributeImpl::getKindAsEnum(), getKindAsEnum(), llvm::AttributeImpl::getValueAsType(), getValueAsType(), and llvm::AttributeImpl::operator<().
operator!=()
bool llvm::Attribute::operator!= (Attribute A) const inline
Definition at line 178 of file Attributes.h.
References operator<().
operator<()
bool Attribute::operator< (Attribute A) const
Less-than operator. Useful for sorting the attributes list.
Definition at line 487 of file Attributes.cpp.
References llvm::AttributeImpl::~AttributeImpl().
Referenced by operator!=().
operator==()
bool llvm::Attribute::operator== (Attribute A) const inline
Equality and non-equality operators.
Definition at line 177 of file Attributes.h.
Referenced by llvm::AttrBuilder::td_empty().
Profile()
void llvm::Attribute::Profile (FoldingSetNodeID & ID) const inline
Definition at line 183 of file Attributes.h.
References llvm::FoldingSetNodeID::AddPointer().
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp