LLVM: llvm::MVT Class Reference
llvm::MVT Class Reference
Machine Value Type.
#include "llvm/Support/MachineValueType.h"
Public Types
enum SimpleValueType : uint8_t {
INVALID_SIMPLE_VALUE_TYPE = 0, Other = 1, i1 = 2, i8 = 3,
i16 = 4, i32 = 5, i64 = 6, i128 = 7,
FIRST_INTEGER_VALUETYPE = i1, LAST_INTEGER_VALUETYPE = i128, f16 = 8, f32 = 9,
f64 = 10, f80 = 11, f128 = 12, ppcf128 = 13,
FIRST_FP_VALUETYPE = f16, LAST_FP_VALUETYPE = ppcf128, v1i1 = 14, v2i1 = 15,
v4i1 = 16, v8i1 = 17, v16i1 = 18, v32i1 = 19,
v64i1 = 20, v128i1 = 21, v256i1 = 22, v512i1 = 23,
v1024i1 = 24, v1i8 = 25, v2i8 = 26, v4i8 = 27,
v8i8 = 28, v16i8 = 29, v32i8 = 30, v64i8 = 31,
v128i8 = 32, v256i8 = 33, v1i16 = 34, v2i16 = 35,
v3i16 = 36, v4i16 = 37, v8i16 = 38, v16i16 = 39,
v32i16 = 40, v64i16 = 41, v128i16 = 42, v1i32 = 43,
v2i32 = 44, v3i32 = 45, v4i32 = 46, v5i32 = 47,
v8i32 = 48, v16i32 = 49, v32i32 = 50, v64i32 = 51,
v128i32 = 52, v256i32 = 53, v512i32 = 54, v1024i32 = 55,
v2048i32 = 56, v1i64 = 57, v2i64 = 58, v4i64 = 59,
v8i64 = 60, v16i64 = 61, v32i64 = 62, v1i128 = 63,
FIRST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE = v1i1, LAST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE = v1i128, v2f16 = 64, v3f16 = 65,
v4f16 = 66, v8f16 = 67, v16f16 = 68, v32f16 = 69,
v1f32 = 70, v2f32 = 71, v3f32 = 72, v4f32 = 73,
v5f32 = 74, v8f32 = 75, v16f32 = 76, v32f32 = 77,
v64f32 = 78, v128f32 = 79, v256f32 = 80, v512f32 = 81,
v1024f32 = 82, v2048f32 = 83, v1f64 = 84, v2f64 = 85,
v4f64 = 86, v8f64 = 87, FIRST_FP_FIXEDLEN_VECTOR_VALUETYPE = v2f16, LAST_FP_FIXEDLEN_VECTOR_VALUETYPE = v8f64,
FIRST_FIXEDLEN_VECTOR_VALUETYPE = v1i1, LAST_FIXEDLEN_VECTOR_VALUETYPE = v8f64, nxv1i1 = 88, nxv2i1 = 89,
nxv4i1 = 90, nxv8i1 = 91, nxv16i1 = 92, nxv32i1 = 93,
nxv1i8 = 94, nxv2i8 = 95, nxv4i8 = 96, nxv8i8 = 97,
nxv16i8 = 98, nxv32i8 = 99, nxv1i16 = 100, nxv2i16 = 101,
nxv4i16 = 102, nxv8i16 = 103, nxv16i16 = 104, nxv32i16 = 105,
nxv1i32 = 106, nxv2i32 = 107, nxv4i32 = 108, nxv8i32 = 109,
nxv16i32 = 110, nxv32i32 = 111, nxv1i64 = 112, nxv2i64 = 113,
nxv4i64 = 114, nxv8i64 = 115, nxv16i64 = 116, nxv32i64 = 117,
FIRST_INTEGER_SCALABLE_VECTOR_VALUETYPE = nxv1i1, LAST_INTEGER_SCALABLE_VECTOR_VALUETYPE = nxv32i64, nxv2f16 = 118, nxv4f16 = 119,
nxv8f16 = 120, nxv1f32 = 121, nxv2f32 = 122, nxv4f32 = 123,
nxv8f32 = 124, nxv16f32 = 125, nxv1f64 = 126, nxv2f64 = 127,
nxv4f64 = 128, nxv8f64 = 129, FIRST_FP_SCALABLE_VECTOR_VALUETYPE = nxv2f16, LAST_FP_SCALABLE_VECTOR_VALUETYPE = nxv8f64,
FIRST_SCALABLE_VECTOR_VALUETYPE = nxv1i1, LAST_SCALABLE_VECTOR_VALUETYPE = nxv8f64, FIRST_VECTOR_VALUETYPE = v1i1, LAST_VECTOR_VALUETYPE = nxv8f64,
x86mmx = 130, Glue = 131, isVoid = 132, Untyped = 133,
exnref = 134, FIRST_VALUETYPE = 1, LAST_VALUETYPE = 135, MAX_ALLOWED_VALUETYPE = 160,
token = 248, Metadata = 249, iPTRAny = 250, vAny = 251,
fAny = 252, iAny = 253, iPTR = 254, Any = 255
}
Public Member Functions
constexpr MVT ()=default
constexpr MVT (SimpleValueType SVT)
bool operator> (const MVT &S) const
bool operator< (const MVT &S) const
bool operator== (const MVT &S) const
bool operator!= (const MVT &S) const
bool operator>= (const MVT &S) const
bool operator<= (const MVT &S) const
bool isValid () const
Return true if this is a valid simple valuetype.
bool isFloatingPoint () const
Return true if this is a FP or a vector FP type.
bool isInteger () const
Return true if this is an integer or a vector integer type.
bool isScalarInteger () const
Return true if this is an integer, not including vectors.
bool isVector () const
Return true if this is a vector value type.
bool isScalableVector () const
Return true if this is a vector value type where the runtime length is machine dependent.
bool isFixedLengthVector () const
bool is16BitVector () const
Return true if this is a 16-bit vector type.
bool is32BitVector () const
Return true if this is a 32-bit vector type.
bool is64BitVector () const
Return true if this is a 64-bit vector type.
bool is128BitVector () const
Return true if this is a 128-bit vector type.
bool is256BitVector () const
Return true if this is a 256-bit vector type.
bool is512BitVector () const
Return true if this is a 512-bit vector type.
bool is1024BitVector () const
Return true if this is a 1024-bit vector type.
bool is2048BitVector () const
Return true if this is a 2048-bit vector type.
bool isOverloaded () const
Return true if this is an overloaded type for TableGen.
MVT getHalfNumVectorElementsVT () const
Return a VT for a vector type with the same element type but half the number of elements.
bool isPow2VectorType () const
Returns true if the given vector is a power of 2.
MVT getPow2VectorType () const
Widens the length of the given vector MVT up to the nearest power of 2 and returns that type.
MVT getScalarType () const
If this is a vector, return the element type, otherwise return this.
MVT getVectorElementType () const
unsigned getVectorNumElements () const
ElementCount getVectorElementCount () const
TypeSize getSizeInBits () const
Returns the size of the specified MVT in bits.
TypeSize getScalarSizeInBits () const
TypeSize getStoreSize () const
Return the number of bytes overwritten by a store of the specified value type.
TypeSize getStoreSizeInBits () const
Return the number of bits overwritten by a store of the specified value type.
bool isByteSized () const
Returns true if the number of bits for the type is a multiple of an 8-bit byte.
bool bitsGT (MVT VT) const
Return true if this has more bits than VT.
bool bitsGE (MVT VT) const
Return true if this has no less bits than VT.
bool bitsLT (MVT VT) const
Return true if this has less bits than VT.
bool bitsLE (MVT VT) const
Return true if this has no more bits than VT.
Static Public Member Functions
static MVT getFloatingPointVT (unsigned BitWidth)
static MVT getIntegerVT (unsigned BitWidth)
static MVT getVectorVT (MVT VT, unsigned NumElements)
static MVT getScalableVectorVT (MVT VT, unsigned NumElements)
static MVT getVectorVT (MVT VT, unsigned NumElements, bool IsScalable)
static MVT getVectorVT (MVT VT, ElementCount EC)
static MVT getVT (Type *Ty, bool HandleUnknown=false)
Return the value type corresponding to the specified type.
static mvt_range all_valuetypes ()
SimpleValueType Iteration.
static mvt_range integer_valuetypes ()
static mvt_range fp_valuetypes ()
static mvt_range vector_valuetypes ()
static mvt_range fixedlen_vector_valuetypes ()
static mvt_range scalable_vector_valuetypes ()
static mvt_range integer_fixedlen_vector_valuetypes ()
static mvt_range fp_fixedlen_vector_valuetypes ()
static mvt_range integer_scalable_vector_valuetypes ()
static mvt_range fp_scalable_vector_valuetypes ()
Public Attributes
SimpleValueType SimpleTy = INVALID_SIMPLE_VALUE_TYPE
Detailed Description
Machine Value Type.
Every type that is supported natively by some processor targeted by LLVM occurs here. This means that any legal value type can be represented by an MVT.
Definition at line 30 of file MachineValueType.h.
Member Enumeration Documentation
SimpleValueType
enum llvm::MVT::SimpleValueType : uint8_t
Enumerator
INVALID_SIMPLE_VALUE_TYPE
Other
i1
i8
i16
i32
i64
i128
FIRST_INTEGER_VALUETYPE
LAST_INTEGER_VALUETYPE
f16
f32
f64
f80
f128
ppcf128
FIRST_FP_VALUETYPE
LAST_FP_VALUETYPE
v1i1
v2i1
v4i1
v8i1
v16i1
v32i1
v64i1
v128i1
v256i1
v512i1
v1024i1
v1i8
v2i8
v4i8
v8i8
v16i8
v32i8
v64i8
v128i8
v256i8
v1i16
v2i16
v3i16
v4i16
v8i16
v16i16
v32i16
v64i16
v128i16
v1i32
v2i32
v3i32
v4i32
v5i32
v8i32
v16i32
v32i32
v64i32
v128i32
v256i32
v512i32
v1024i32
v2048i32
v1i64
v2i64
v4i64
v8i64
v16i64
v32i64
v1i128
FIRST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE
LAST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE
v2f16
v3f16
v4f16
v8f16
v16f16
v32f16
v1f32
v2f32
v3f32
v4f32
v5f32
v8f32
v16f32
v32f32
v64f32
v128f32
v256f32
v512f32
v1024f32
v2048f32
v1f64
v2f64
v4f64
v8f64
FIRST_FP_FIXEDLEN_VECTOR_VALUETYPE
LAST_FP_FIXEDLEN_VECTOR_VALUETYPE
FIRST_FIXEDLEN_VECTOR_VALUETYPE
LAST_FIXEDLEN_VECTOR_VALUETYPE
nxv1i1
nxv2i1
nxv4i1
nxv8i1
nxv16i1
nxv32i1
nxv1i8
nxv2i8
nxv4i8
nxv8i8
nxv16i8
nxv32i8
nxv1i16
nxv2i16
nxv4i16
nxv8i16
nxv16i16
nxv32i16
nxv1i32
nxv2i32
nxv4i32
nxv8i32
nxv16i32
nxv32i32
nxv1i64
nxv2i64
nxv4i64
nxv8i64
nxv16i64
nxv32i64
FIRST_INTEGER_SCALABLE_VECTOR_VALUETYPE
LAST_INTEGER_SCALABLE_VECTOR_VALUETYPE
nxv2f16
nxv4f16
nxv8f16
nxv1f32
nxv2f32
nxv4f32
nxv8f32
nxv16f32
nxv1f64
nxv2f64
nxv4f64
nxv8f64
FIRST_FP_SCALABLE_VECTOR_VALUETYPE
LAST_FP_SCALABLE_VECTOR_VALUETYPE
FIRST_SCALABLE_VECTOR_VALUETYPE
LAST_SCALABLE_VECTOR_VALUETYPE
FIRST_VECTOR_VALUETYPE
LAST_VECTOR_VALUETYPE
x86mmx
Glue
isVoid
Untyped
exnref
FIRST_VALUETYPE
LAST_VALUETYPE
MAX_ALLOWED_VALUETYPE
token
Metadata
iPTRAny
vAny
fAny
iAny
iPTR
Any
Definition at line 32 of file MachineValueType.h.
Constructor & Destructor Documentation
MVT() [1/2]
constexpr llvm::MVT::MVT () default
MVT() [2/2]
constexpr llvm::MVT::MVT (SimpleValueType SVT) inline
Definition at line 268 of file MachineValueType.h.
Member Function Documentation
all_valuetypes()
static mvt_range llvm::MVT::all_valuetypes () inline static
SimpleValueType Iteration.
Definition at line 1125 of file MachineValueType.h.
References FIRST_VALUETYPE, and LAST_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), and llvm::TargetLoweringBase::initActions().
bitsGE()
bool llvm::MVT::bitsGE (MVT VT) const inline
Return true if this has no less bits than VT.
Definition at line 868 of file MachineValueType.h.
References getSizeInBits().
Referenced by combineOrCmpEqZeroToCtlzSrl().
bitsGT()
bool llvm::MVT::bitsGT (MVT VT) const inline
Return true if this has more bits than VT.
Definition at line 863 of file MachineValueType.h.
References getSizeInBits().
Referenced by LowerFCOPYSIGN(), and LowerScalarVariableShift().
bitsLE()
bool llvm::MVT::bitsLE (MVT VT) const inline
Return true if this has no more bits than VT.
Definition at line 878 of file MachineValueType.h.
References getSizeInBits().
Referenced by getMaskNode(), llvm::SITargetLowering::getPreferredVectorAction(), and LowerScalarVariableShift().
bitsLT()
bool llvm::MVT::bitsLT (MVT VT) const inline
Return true if this has less bits than VT.
Definition at line 873 of file MachineValueType.h.
References getSizeInBits().
Referenced by LowerFCOPYSIGN(), and LowerScalarVariableShift().
fixedlen_vector_valuetypes()
static mvt_range llvm::MVT::fixedlen_vector_valuetypes () inline static
Definition at line 1144 of file MachineValueType.h.
References FIRST_FIXEDLEN_VECTOR_VALUETYPE, and LAST_FIXEDLEN_VECTOR_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
fp_fixedlen_vector_valuetypes()
static mvt_range llvm::MVT::fp_fixedlen_vector_valuetypes () inline static
Definition at line 1162 of file MachineValueType.h.
References FIRST_FP_FIXEDLEN_VECTOR_VALUETYPE, and LAST_FP_FIXEDLEN_VECTOR_VALUETYPE.
Referenced by llvm::MipsTargetLowering::MipsTargetLowering().
fp_scalable_vector_valuetypes()
static mvt_range llvm::MVT::fp_scalable_vector_valuetypes () inline static
Definition at line 1174 of file MachineValueType.h.
References FIRST_FP_SCALABLE_VECTOR_VALUETYPE, and LAST_FP_SCALABLE_VECTOR_VALUETYPE.
fp_valuetypes()
static mvt_range llvm::MVT::fp_valuetypes () inline static
Definition at line 1134 of file MachineValueType.h.
References FIRST_FP_VALUETYPE, and LAST_FP_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::TargetLoweringBase::initActions(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
getFloatingPointVT()
static MVT llvm::MVT::getFloatingPointVT (unsigned BitWidth) inline static
Definition at line 882 of file MachineValueType.h.
References f128, f16, f32, f64, f80, and llvm_unreachable.
Referenced by combineCVTP2I_CVTTP2I(), combineHorizontalPredicateResult(), combineX86ShuffleChain(), combineX86ShufflesConstants(), EltsFromConsecutiveLoads(), llvm::EVT::getFloatingPointVT(), lower256BitShuffle(), lowerBuildVectorAsBroadcast(), LowerInterruptReturn(), LowerPREFETCH(), lowerVECTOR_SHUFFLE(), LowerVectorINT_TO_FP(), mayTailCallThisCC(), and truncateScalarIntegerArg().
getHalfNumVectorElementsVT()
MVT llvm::MVT::getHalfNumVectorElementsVT () const inline
Return a VT for a vector type with the same element type but half the number of elements.
Definition at line 395 of file MachineValueType.h.
References assert(), getVectorElementCount(), getVectorElementType(), and getVectorVT().
Referenced by getHopForBuildVector(), getShuffleHalfVectors(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), LowerBITCAST(), LowerCONCAT_VECTORSvXi1(), LowerEXTEND_VECTOR_INREG(), lowerShuffleWithUndefHalf(), and LowerSIGN_EXTEND().
getIntegerVT()
static MVT llvm::MVT::getIntegerVT (unsigned BitWidth) inline static
Definition at line 899 of file MachineValueType.h.
References i1, i128, i16, i32, i64, i8, and INVALID_SIMPLE_VALUE_TYPE.
Referenced by llvm::EVT::changeTypeToInteger(), llvm::EVT::changeVectorElementTypeToInteger(), CombineBaseUpdate(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShufflesConstants(), llvm::computeSignatureVTs(), ConstantBuildVector(), ConvertI1VectorToInteger(), EltsFromConsecutiveLoads(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), ExtractBitFromMaskVector(), llvm::EVT::getIntegerVT(), llvm::getMVTForLLT(), getPermuteNode(), llvm::TargetLoweringBase::getPointerMemTy(), llvm::TargetLoweringBase::getPointerTy(), llvm::AArch64TargetLowering::getPointerTy(), GetRegistersForValue(), llvm::TargetLoweringBase::getScalarShiftAmountTy(), llvm::TargetLoweringBase::hasFastEqualityCompare(), llvm::X86TargetLowering::hasFastEqualityCompare(), llvm::TargetLoweringBase::initActions(), insert1BitVector(), InsertBitToMaskVector(), is128BitUnpackShuffleMask(), isMulPowOf2(), isPromotedInstructionLegal(), isSplatZeroExtended(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), llvm::HexagonTargetLowering::LowerBITCAST(), lowerBuildVectorAsBroadcast(), LowerCTPOP(), lowerFCOPYSIGN64(), LowerINSERT_VECTOR_ELT_i1(), llvm::HexagonTargetLowering::LowerSETCC(), lowerShuffleAsBlend(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleToEXPAND(), lowerShuffleWithPERMV(), LowerTruncateVecI1(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZInRegLUT(), llvm::HexagonTargetLowering::LowerVSELECT(), lowerX86FPLogicOp(), matchShuffleAsShift(), matchShuffleWithPACK(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), mayTailCallThisCC(), memsetStore(), llvm::TargetLowering::ParseConstraints(), performExtendCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), scaleVectorType(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::HexagonTargetLowering::shouldExpandAtomicRMWInIR(), llvm::AArch64TargetLowering::shouldTransformSignedTruncationCheck(), llvm::X86TargetLowering::shouldTransformSignedTruncationCheck(), ShrinkLoadReplaceStoreWithStore(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), llvm::SystemZTargetLowering::SystemZTargetLowering(), truncateScalarIntegerArg(), tryBuildVectorShuffle(), unpackFromMemLoc(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
getPow2VectorType()
MVT llvm::MVT::getPow2VectorType () const inline
Widens the length of the given vector MVT up to the nearest power of 2 and returns that type.
Definition at line 410 of file MachineValueType.h.
References getVectorElementType(), getVectorNumElements(), getVectorVT(), isPow2VectorType(), and llvm::Log2_32_Ceil().
Referenced by llvm::TargetLoweringBase::computeRegisterProperties().
getScalableVectorVT()
static MVT llvm::MVT::getScalableVectorVT (MVT VT, unsigned NumElements) inline static
Definition at line 1018 of file MachineValueType.h.
References f16, f32, f64, i1, i16, i32, i64, i8, INVALID_SIMPLE_VALUE_TYPE, nxv16f32, nxv16i1, nxv16i16, nxv16i32, nxv16i64, nxv16i8, nxv1f32, nxv1f64, nxv1i1, nxv1i16, nxv1i32, nxv1i64, nxv1i8, nxv2f16, nxv2f32, nxv2f64, nxv2i1, nxv2i16, nxv2i32, nxv2i64, nxv2i8, nxv32i1, nxv32i16, nxv32i32, nxv32i64, nxv32i8, nxv4f16, nxv4f32, nxv4f64, nxv4i1, nxv4i16, nxv4i32, nxv4i64, nxv4i8, nxv8f16, nxv8f32, nxv8f64, nxv8i1, nxv8i16, nxv8i32, nxv8i64, nxv8i8, and SimpleTy.
Referenced by getVectorVT().
getScalarSizeInBits()
TypeSize llvm::MVT::getScalarSizeInBits () const inline
Definition at line 831 of file MachineValueType.h.
References getScalarType(), and getSizeInBits().
Referenced by combineAndnp(), combineCVTP2I_CVTTP2I(), combineMOVMSK(), combineTargetShuffle(), combineX86INT_TO_FP(), combineX86ShuffleChain(), llvm::TargetLoweringBase::computeRegisterProperties(), createPackShuffleMask(), llvm::createUnpackShuffleMask(), createVariablePermute(), DecodePALIGNRMask(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), llvm::X86TTIImpl::getCmpSelInstrCost(), getConstantVector(), getConstVector(), llvm::RegsForValue::getCopyFromRegs(), getFauxShuffleMask(), getMemCmpLoad(), llvm::SystemZTargetLowering::getPreferredVectorAction(), llvm::PPCTargetLowering::getPreferredVectorAction(), getPromotedVectorElementType(), getPSHUFShuffleMask(), getScalarValueForVectorElement(), getTargetShuffleMask(), getTargetVShiftNode(), is128BitLaneCrossingShuffleMask(), isRepeatedShuffleMask(), isRepeatedTargetShuffleMask(), isSplatZeroExtended(), lower256BitShuffle(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), LowerCTTZ(), LowerEXTEND_VECTOR_INREG(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFunnelShift(), LowerMGATHER(), LowerMSCATTER(), LowerMSTORE(), LowerRotate(), LowerScalarImmediateShift(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), LowerTruncateVecI1(), lowerV4X128Shuffle(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZInRegLUT(), lowerX86FPLogicOp(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsEXTRQ(), matchShuffleAsINSERTQ(), matchShuffleWithPACK(), matchShuffleWithSHUFPD(), matchUnaryShuffle(), processShaderInputArgs(), scaleVectorType(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), SupportedVectorShiftWithImm(), SupportedVectorVarShift(), and vectorizeExtractedCast().
getScalarType()
MVT llvm::MVT::getScalarType () const inline
If this is a vector, return the element type, otherwise return this.
Definition at line 420 of file MachineValueType.h.
References getVectorElementType(), and isVector().
Referenced by llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), combineConcatVectorOps(), combineExtractSubvector(), combineVectorSignBitsTruncation(), createVariablePermute(), getDUPLANEOp(), getFauxShuffleMask(), llvm::SITargetLowering::getPreferredVectorAction(), llvm::NVPTXTargetLowering::getPreferredVectorAction(), getScalarSizeInBits(), getTargetShuffleMask(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::X86TargetLowering::isShuffleMaskLegal(), LowerADDSAT_SUBSAT(), lowerAddSub(), LowerBITREVERSE(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), LowerMINMAX(), LowerMLOAD(), LowerMSTORE(), LowerMUL(), lowerRegToMasks(), lowerShuffleAsBroadcast(), lowerShuffleAsRotate(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerVectorCTPOP(), matchUnaryShuffle(), parseTexFail(), pickOpcodeForVT(), scalarizeVectorStore(), shouldGuaranteeTCO(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), tryCombineShiftImm(), vectorizeExtractedCast(), and widenSubVector().
getSizeInBits()
TypeSize llvm::MVT::getSizeInBits () const inline
Returns the size of the specified MVT in bits.
If the value type is a scalable vector type, the scalable property will be set and the runtime size will be a positive integer multiple of the base size.
Definition at line 679 of file MachineValueType.h.
References Any, exnref, f128, f16, f32, f64, f80, fAny, llvm::TypeSize::Fixed(), i1, i128, i16, i32, i64, i8, iAny, iPTR, iPTRAny, llvm_unreachable, Metadata, nxv16f32, nxv16i1, nxv16i16, nxv16i32, nxv16i64, nxv16i8, nxv1f32, nxv1f64, nxv1i1, nxv1i16, nxv1i32, nxv1i64, nxv1i8, nxv2f16, nxv2f32, nxv2f64, nxv2i1, nxv2i16, nxv2i32, nxv2i64, nxv2i8, nxv32i1, nxv32i16, nxv32i32, nxv32i64, nxv32i8, nxv4f16, nxv4f32, nxv4f64, nxv4i1, nxv4i16, nxv4i32, nxv4i64, nxv4i8, nxv8f16, nxv8f32, nxv8f64, nxv8i1, nxv8i16, nxv8i32, nxv8i64, nxv8i8, Other, ppcf128, llvm::TypeSize::Scalable(), token, v1024f32, v1024i1, v1024i32, v128f32, v128i1, v128i16, v128i32, v128i8, v16f16, v16f32, v16i1, v16i16, v16i32, v16i64, v16i8, v1f32, v1f64, v1i1, v1i128, v1i16, v1i32, v1i64, v1i8, v2048f32, v2048i32, v256f32, v256i1, v256i32, v256i8, v2f16, v2f32, v2f64, v2i1, v2i16, v2i32, v2i64, v2i8, v32f16, v32f32, v32i1, v32i16, v32i32, v32i64, v32i8, v3f16, v3f32, v3i16, v3i32, v4f16, v4f32, v4f64, v4i1, v4i16, v4i32, v4i64, v4i8, v512f32, v512i1, v512i32, v5f32, v5i32, v64f32, v64i1, v64i16, v64i32, v64i8, v8f16, v8f32, v8f64, v8i1, v8i16, v8i32, v8i64, v8i8, vAny, and x86mmx.
Referenced by llvm::AArch64CallLowering::AArch64CallLowering(), llvm::HexagonTargetLowering::allowsMisalignedMemoryAccesses(), AnalyzeReturnValues(), bitsGE(), bitsGT(), bitsLE(), bitsLT(), callingConvSupported(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), CC_Lanai32_VarArg(), CC_MipsO32_FP64(), CC_Sparc64_Full(), CC_Sparc64_Half(), CC_X86_32_VectorCall(), CC_X86_64_VectorCall(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::EVT::changeVectorElementTypeToInteger(), CombineBaseUpdate(), combineBasicSADPattern(), combineExtractSubvector(), combineHorizontalPredicateResult(), combineInsertSubvector(), combineLoopSADPattern(), combineTargetShuffle(), combineVectorSignBitsTruncation(), combineX86ShuffleChain(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), llvm::TargetLoweringBase::computeRegisterProperties(), convertShiftLeftToScale(), createPackShuffleMask(), createShuffleStride(), createVariablePermute(), DecodePALIGNRMask(), determineLocInfo(), earlyExpandDIVFIX(), EltsFromConsecutiveLoads(), emitConstantSizeRepmov(), EnsureStackAlignment(), llvm::TargetLowering::expandUnalignedStore(), ExtractBitFromMaskVector(), llvm::FastISel::fastEmit_ri_(), finishStackBlock(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), genShuffleBland(), getCompareCC(), getComparePred(), getCopyFromParts(), getCopyFromPartsVector(), getCopyToParts(), getCopyToPartsVector(), getFauxShuffleMask(), getHopForBuildVector(), llvm::getLLTForMVT(), getMaskNode(), getMemCmpLoad(), getMOVL(), getOpenCLAlignment(), llvm::HvxSelector::getPairVT(), llvm::HexagonTargetLowering::getPreferredVectorAction(), getPromotedVectorElementType(), getPSHUFShuffleMask(), llvm::HexagonTargetLowering::getRegForInlineAsmConstraint(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), llvm::ARMTargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), GetRegistersForValue(), llvm::RegsForValue::getRegsAndSizes(), getScalarSizeInBits(), getScalarValueForVectorElement(), llvm::X86TargetLowering::getSetCCResultType(), llvm::X86TTIImpl::getShuffleCost(), llvm::HvxSelector::getSingleVT(), llvm::EVT::getSizeInBits(), getStoreSize(), getTargetShuffleAndZeroables(), getTargetVShiftByConstNode(), getTargetVShiftNode(), llvm::HexagonSubtarget::getTypeAlignment(), llvm::AArch64TargetLowering::getVaListSizeInBits(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::MipsTargetLowering::getVectorTypeBreakdownForCallingConv(), getVectorTypeBreakdownMVT(), getZeroVector(), group2Shuffle(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::CallLowering::handleAssignments(), hasBZHI(), insert1BitVector(), InsertBitToMaskVector(), isByteSized(), isHorizontalBinOp(), llvm::HexagonSubtarget::isHVXVectorType(), isMulPowOf2(), llvm::X86TargetLowering::isShuffleMaskLegal(), isSupportedType(), llvm::LLT::LLT(), LowerAsSplatVectorLoad(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITREVERSE_XOP(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCTLZ(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFPToInt(), LowerHorizontalByteSum(), lowerINT_TO_FP_vXi64(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), LowerSCALAR_TO_VECTOR(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShiftParts(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPSHUFB(), lowerShuffleWithUndefHalf(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerStore(), LowerTruncateVecI1(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTPOP(), LowerVectorIntUnary(), llvm::HexagonTargetLowering::LowerVSELECT(), lowerX86FPLogicOp(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), MatchingStackOffset(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), mayTailCallThisCC(), narrowExtractedVectorSelect(), llvm::TargetLowering::ParseConstraints(), parsePredicateConstraint(), performFDivCombine(), performFpToIntCombine(), PerformTruncatingStoreCombine(), PerformVCVTCombine(), PerformVDIVCombine(), pickOpcodeForVT(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), setGroupSize(), llvm::HexagonTargetLowering::shouldExpandAtomicRMWInIR(), shouldGuaranteeTCO(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyDivRem(), splitAndLowerShuffle(), truncateScalarIntegerArg(), tryCombineShiftImm(), UnpackFromArgumentSlot(), VisitGlobalVariableForEmission(), widenSubVector(), and llvm::X86CallLowering::X86CallLowering().
getStoreSize()
TypeSize llvm::MVT::getStoreSize () const inline
Return the number of bytes overwritten by a store of the specified value type.
If the value type is a scalable vector type, the scalable property will be set and the runtime size will be a positive integer multiple of the base size.
Definition at line 841 of file MachineValueType.h.
References llvm::TypeSize::getKnownMinSize(), getSizeInBits(), and llvm::TypeSize::isScalable().
Referenced by CC_AIX(), CC_MipsO32(), computeBytesPoppedByCalleeForSRet(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), EnsureStackAlignment(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), getRetpolineSymbol(), llvm::X86TTIImpl::getShuffleCost(), getStoreSizeInBits(), getUniformBase(), isSupportedType(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::SITargetLowering::LowerCall(), lowerCallResult(), scalarizeVectorStore(), truncateScalarIntegerArg(), tryToElideArgumentCopy(), and llvm::X86CallLowering::X86CallLowering().
getStoreSizeInBits()
TypeSize llvm::MVT::getStoreSizeInBits () const inline
Return the number of bits overwritten by a store of the specified value type.
If the value type is a scalable vector type, the scalable property will be set and the runtime size will be a positive integer multiple of the base size.
Definition at line 852 of file MachineValueType.h.
References getStoreSize().
Referenced by llvm::HexagonTargetLowering::LowerCall(), and llvm::HexagonTargetLowering::LowerFormalArguments().
getVectorElementCount()
ElementCount llvm::MVT::getVectorElementCount () const inline
Definition at line 670 of file MachineValueType.h.
References getVectorNumElements(), and isScalableVector().
Referenced by getHalfNumVectorElementsVT(), and llvm::EVT::getVectorElementCount().
getVectorElementType()
MVT llvm::MVT::getVectorElementType () const inline
Definition at line 424 of file MachineValueType.h.
References f16, f32, f64, i1, i128, i16, i32, i64, i8, llvm_unreachable, nxv16f32, nxv16i1, nxv16i16, nxv16i32, nxv16i64, nxv16i8, nxv1f32, nxv1f64, nxv1i1, nxv1i16, nxv1i32, nxv1i64, nxv1i8, nxv2f16, nxv2f32, nxv2f64, nxv2i1, nxv2i16, nxv2i32, nxv2i64, nxv2i8, nxv32i1, nxv32i16, nxv32i32, nxv32i64, nxv32i8, nxv4f16, nxv4f32, nxv4f64, nxv4i1, nxv4i16, nxv4i32, nxv4i64, nxv4i8, nxv8f16, nxv8f32, nxv8f64, nxv8i1, nxv8i16, nxv8i32, nxv8i64, nxv8i8, v1024f32, v1024i1, v1024i32, v128f32, v128i1, v128i16, v128i32, v128i8, v16f16, v16f32, v16i1, v16i16, v16i32, v16i64, v16i8, v1f32, v1f64, v1i1, v1i128, v1i16, v1i32, v1i64, v1i8, v2048f32, v2048i32, v256f32, v256i1, v256i32, v256i8, v2f16, v2f32, v2f64, v2i1, v2i16, v2i32, v2i64, v2i8, v32f16, v32f32, v32i1, v32i16, v32i32, v32i64, v32i8, v3f16, v3f32, v3i16, v3i32, v4f16, v4f32, v4f64, v4i1, v4i16, v4i32, v4i64, v4i8, v512f32, v512i1, v512i32, v5f32, v5i32, v64f32, v64i1, v64i16, v64i32, v64i8, v8f16, v8f32, v8f64, v8i1, v8i16, v8i32, v8i64, and v8i8.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::HexagonTargetLowering::allowsMisalignedMemoryAccesses(), callingConvSupported(), llvm::EVT::changeVectorElementTypeToInteger(), combineExtInVec(), combineExtractSubvector(), combineInsertSubvector(), combineRedundantDWordShuffle(), combineTargetShuffle(), computeBytesPoppedByCalleeForSRet(), llvm::TargetLoweringBase::computeRegisterProperties(), convertShiftLeftToScale(), ExtendToType(), ExtractBitFromMaskVector(), getConstVector(), getHalfNumVectorElementsVT(), llvm::getLLTForMVT(), getPow2VectorType(), llvm::HexagonTargetLowering::getPreferredVectorAction(), llvm::X86TargetLowering::getPreferredVectorAction(), getScalarType(), getScalarValueForVectorElement(), llvm::X86TargetLowering::getSetCCResultType(), llvm::X86TTIImpl::getShuffleCost(), getShuffleScalarElt(), getTargetVShiftByConstNode(), getTargetVShiftNode(), llvm::X86TargetLowering::getTgtMemIntrinsic(), getUnderlyingExtractedFromVec(), llvm::EVT::getVectorElementType(), getVectorTypeBreakdownMVT(), getVPTESTMOpc(), getZeroVector(), incDecVectorConstant(), InsertBitToMaskVector(), llvm::HexagonSubtarget::isHVXVectorType(), isLegalT2AddressImmediate(), llvm::LLT::LLT(), Lower256IntVSETCC(), LowerANY_EXTEND(), LowerAVXExtend(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), LowerBUILD_VECTORAsVariablePermute(), LowerBUILD_VECTORvXi1(), LowerBuildVectorv4x32(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::HexagonTargetLowering::LowerEXTRACT_VECTOR_ELT(), LowerHorizontalByteSum(), LowerINSERT_SUBVECTOR(), llvm::HexagonTargetLowering::LowerINSERT_VECTOR_ELT(), LowerIntVSETCC_AVX512(), LowerLoad(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerSCALAR_TO_VECTOR(), LowerScalarVariableShift(), llvm::HexagonTargetLowering::LowerSETCC(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsTruncBroadcast(), lowerShuffleWithUndefHalf(), lowerShuffleWithVPMOV(), LowerSIGN_EXTEND(), LowerSIGN_EXTEND_Mask(), LowerTruncateVecI1(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZ(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), LowerVectorIntUnary(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerZERO_EXTEND(), LowerZERO_EXTEND_Mask(), narrowExtractedVectorSelect(), performConcatVectorsCombine(), performFDivCombine(), performFpToIntCombine(), PerformVCVTCombine(), PerformVDIVCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), scaleVectorType(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::HexagonTargetLowering::shouldExpandAtomicRMWInIR(), split256IntArith(), split512IntArith(), splitAndLowerShuffle(), tryExtendDUPToExtractHigh(), and unrollVectorShift().
getVectorNumElements()
unsigned llvm::MVT::getVectorNumElements () const inline
Definition at line 547 of file MachineValueType.h.
References llvm_unreachable, nxv16f32, nxv16i1, nxv16i16, nxv16i32, nxv16i64, nxv16i8, nxv1f32, nxv1f64, nxv1i1, nxv1i16, nxv1i32, nxv1i64, nxv1i8, nxv2f16, nxv2f32, nxv2f64, nxv2i1, nxv2i16, nxv2i32, nxv2i64, nxv2i8, nxv32i1, nxv32i16, nxv32i32, nxv32i64, nxv32i8, nxv4f16, nxv4f32, nxv4f64, nxv4i1, nxv4i16, nxv4i32, nxv4i64, nxv4i8, nxv8f16, nxv8f32, nxv8f64, nxv8i1, nxv8i16, nxv8i32, nxv8i64, nxv8i8, v1024f32, v1024i1, v1024i32, v128f32, v128i1, v128i16, v128i32, v128i8, v16f16, v16f32, v16i1, v16i16, v16i32, v16i64, v16i8, v1f32, v1f64, v1i1, v1i128, v1i16, v1i32, v1i64, v1i8, v2048f32, v2048i32, v256f32, v256i1, v256i32, v256i8, v2f16, v2f32, v2f64, v2i1, v2i16, v2i32, v2i64, v2i8, v32f16, v32f32, v32i1, v32i16, v32i32, v32i64, v32i8, v3f16, v3f32, v3i16, v3i32, v4f16, v4f32, v4f64, v4i1, v4i16, v4i32, v4i64, v4i8, v512f32, v512i1, v512i32, v5f32, v5i32, v64f32, v64i1, v64i16, v64i32, v64i8, v8f16, v8f32, v8f64, v8i1, v8i16, v8i32, v8i64, and v8i8.
Referenced by llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), callingConvSupported(), combineBasicSADPattern(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineExtractSubvector(), combineHorizontalPredicateResult(), combineInsertSubvector(), combineMOVMSK(), combineTargetShuffle(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), llvm::TargetLoweringBase::computeRegisterProperties(), convertShiftLeftToScale(), createPackShuffleMask(), createShuffleStride(), llvm::createUnpackShuffleMask(), createVariablePermute(), DecodePALIGNRMask(), ExpandHorizontalBinOp(), ExtendToType(), ExtractBitFromMaskVector(), genShuffleBland(), getConstVector(), getFauxShuffleMask(), getGatherNode(), getHopForBuildVector(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::getLLTForMVT(), getMemCmpLoad(), getMOVL(), getPow2VectorType(), llvm::HexagonTargetLowering::getPreferredVectorAction(), llvm::SITargetLowering::getPreferredVectorAction(), llvm::TargetLoweringBase::getPreferredVectorAction(), llvm::NVPTXTargetLowering::getPreferredVectorAction(), llvm::X86TargetLowering::getPreferredVectorAction(), getPrefetchNode(), getScatterNode(), llvm::X86TTIImpl::getShuffleCost(), getShuffleHalfVectors(), getShuffleScalarElt(), getShuffleVectorZeroOrUndef(), getTargetShuffleAndZeroables(), getTargetShuffleMask(), llvm::X86TargetLowering::getTgtMemIntrinsic(), getUnderlyingExtractedFromVec(), getVectorElementCount(), getVectorMaskingNode(), llvm::EVT::getVectorNumElements(), getVectorTypeBreakdownMVT(), getVPTESTMOpc(), getZeroVector(), group2Shuffle(), llvm::CallLowering::handleAssignments(), incDecVectorConstant(), insert1BitVector(), InsertBitToMaskVector(), isAddSubOrSubAdd(), isHopBuildVector(), isHorizontalBinOp(), llvm::HexagonSubtarget::isHVXVectorType(), isPow2VectorType(), llvm::LLT::LLT(), lower1BitShuffle(), lower256BitShuffle(), Lower256IntVSETCC(), LowerAsSplatVectorLoad(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), lowerBuildVectorToBitOp(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), LowerLoad(), LowerMGATHER(), LowerMSCATTER(), LowerMUL(), LowerMULH(), LowerRotate(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleToEXPAND(), lowerShuffleWithPERMV(), lowerShuffleWithUndefHalf(), lowerShuffleWithVPMOV(), LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerSIGN_EXTEND_Mask(), LowerToHorizontalOp(), LowerTruncateVecI1(), lowerV8I16GeneralSingleInputShuffle(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), LowerVectorIntUnary(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerZERO_EXTEND_Mask(), matchShuffleAsEXTRQ(), matchShuffleAsINSERTQ(), matchShuffleWithPACK(), matchShuffleWithSHUFPD(), matchShuffleWithUNPCK(), matchUnaryShuffle(), narrowExtractedVectorSelect(), parseTexFail(), performConcatVectorsCombine(), recoverFramePointer(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeVectorStore(), scaleVectorType(), setGroupSize(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), split256IntArith(), split512IntArith(), splitAndLowerShuffle(), tryExtendDUPToExtractHigh(), and vectorizeExtractedCast().
getVectorVT() [1/3]
static MVT llvm::MVT::getVectorVT (MVT VT, unsigned NumElements) inline static
Definition at line 918 of file MachineValueType.h.
References f16, f32, f64, i1, i128, i16, i32, i64, i8, INVALID_SIMPLE_VALUE_TYPE, SimpleTy, v1024f32, v1024i1, v1024i32, v128f32, v128i1, v128i16, v128i32, v128i8, v16f16, v16f32, v16i1, v16i16, v16i32, v16i64, v16i8, v1f32, v1f64, v1i1, v1i128, v1i16, v1i32, v1i64, v1i8, v2048f32, v2048i32, v256f32, v256i1, v256i32, v256i8, v2f16, v2f32, v2f64, v2i1, v2i16, v2i32, v2i64, v2i8, v32f16, v32f32, v32i1, v32i16, v32i32, v32i64, v32i8, v3f16, v3f32, v3i16, v3i32, v4f16, v4f32, v4f64, v4i1, v4i16, v4i32, v4i64, v4i8, v512f32, v512i1, v512i32, v5f32, v5i32, v64f32, v64i1, v64i16, v64i32, v64i8, v8f16, v8f32, v8f64, v8i1, v8i16, v8i32, v8i64, and v8i8.
Referenced by AddCombineBUILD_VECTORToVPADDL(), callingConvSupported(), llvm::EVT::changeVectorElementTypeToInteger(), CombineBaseUpdate(), combineBasicSADPattern(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineHorizontalPredicateResult(), combineLoopMAddPattern(), combineLoopSADPattern(), combineMulToPMADDWD(), combineTargetShuffle(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShufflesConstants(), createPSADBW(), createVariablePermute(), elementPairIsContiguous(), EltsFromConsecutiveLoads(), ExtractBitFromMaskVector(), getConstVector(), getDUPLANEOp(), getFauxShuffleMask(), getGatherNode(), getHalfNumVectorElementsVT(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), getMaskNode(), llvm::getMVTForLLT(), getOnesVector(), llvm::HvxSelector::getPairVT(), getPermuteNode(), getPow2VectorType(), getPrefetchNode(), getPromotedVectorElementType(), getScatterNode(), llvm::ARMTargetLowering::getSetCCResultType(), llvm::HvxSelector::getSingleVT(), getSPDenormModeValue(), getTargetVShiftNode(), llvm::X86TargetLowering::getTgtMemIntrinsic(), getVectorMaskingNode(), getVectorTypeBreakdownMVT(), llvm::EVT::getVectorVT(), getVectorVT(), getVPTESTMOpc(), getZeroVector(), group2Shuffle(), llvm::HexagonTargetLowering::HexagonTargetLowering(), InsertBitToMaskVector(), is128BitUnpackShuffleMask(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), lower1BitShuffle(), lower256BitShuffle(), Lower256IntVSETCC(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), LowerCONCAT_VECTORS_i1(), LowerCTPOP(), LowerEXTRACT_SUBVECTOR(), LowerHorizontalByteSum(), LowerI64IntToFP_AVX512DQ(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), LowerMUL(), LowerMULH(), LowerPREFETCH(), LowerRotate(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsElementInsertion(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleToEXPAND(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), LowerSIGN_EXTEND_Mask(), LowerStore(), LowerTruncateVecI1(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVectorINT_TO_FP(), LowerVectorIntUnary(), llvm::HexagonTargetLowering::LowerVSELECT(), lowerX86FPLogicOp(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchShuffleAsShift(), matchShuffleWithPACK(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), mayTailCallThisCC(), memVTFromAggregate(), llvm::MipsTargetLowering::MipsTargetLowering(), narrowExtractedVectorSelect(), NarrowVector(), performConcatVectorsCombine(), performExtendCombine(), recoverFramePointer(), reduceVMULWidth(), reorderSubVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scaleVectorType(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::HexagonTargetLowering::shouldExpandAtomicRMWInIR(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), split256IntArith(), split512IntArith(), splitAndLowerShuffle(), tryBuildVectorShuffle(), tryExtendDUPToExtractHigh(), vectorizeExtractedCast(), widenSubVector(), and WidenVector().
getVectorVT() [2/3]
static MVT llvm::MVT::getVectorVT (MVT VT, unsigned NumElements, bool IsScalable) inline static
Definition at line 1084 of file MachineValueType.h.
References getScalableVectorVT(), and getVectorVT().
getVectorVT() [3/3]
static MVT llvm::MVT::getVectorVT (MVT VT, ElementCount EC) inline static
Definition at line 1090 of file MachineValueType.h.
References assert(), getScalableVectorVT(), getVectorVT(), getVT(), MAX_ALLOWED_VALUETYPE, llvm::ElementCount::Min, operator!=(), llvm::operator*(), and llvm::ElementCount::Scalable.
getVT()
MVT MVT::getVT (Type * Ty, bool HandleUnknown = false) static
Return the value type corresponding to the specified type.
This returns all pointers as iPTR. If HandleUnknown is true, unknown types are returned as Other, otherwise they are invalid.
This returns all pointers as MVT::iPTR. If HandleUnknown is true, unknown types are returned as Other, otherwise they are invalid.
Definition at line 324 of file ValueTypes.cpp.
References llvm::Type::DoubleTyID, f128, f16, f32, f64, f80, llvm::Type::FloatTyID, llvm::Type::FP128TyID, getBitWidth(), llvm::VectorType::getElementCount(), llvm::SequentialType::getElementType(), llvm::EVT::getIntegerVT(), llvm::Type::getTypeID(), llvm::EVT::getVectorVT(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, iPTR, isVoid, llvm_unreachable, Other, llvm::Type::PointerTyID, llvm::Type::PPC_FP128TyID, ppcf128, llvm::Type::VectorTyID, llvm::Type::VoidTyID, llvm::Type::X86_FP80TyID, llvm::Type::X86_MMXTyID, and x86mmx.
Referenced by llvm::CallLowering::analyzeArgInfo(), concatSubVector(), getConvRTLibDesc(), llvm::EVT::getEVT(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::RISCVTargetLowering::getTgtMemIntrinsic(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), llvm::SITargetLowering::getTgtMemIntrinsic(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::X86TargetLowering::getTgtMemIntrinsic(), getVectorVT(), llvm::CallLowering::handleAssignments(), llvm::AArch64CallLowering::lowerReturn(), memVTFromAggregate(), and llvm::TargetLowering::ParseConstraints().
integer_fixedlen_vector_valuetypes()
static mvt_range llvm::MVT::integer_fixedlen_vector_valuetypes () inline static
Definition at line 1156 of file MachineValueType.h.
References FIRST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE, and LAST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
integer_scalable_vector_valuetypes()
static mvt_range llvm::MVT::integer_scalable_vector_valuetypes () inline static
Definition at line 1168 of file MachineValueType.h.
References FIRST_INTEGER_SCALABLE_VECTOR_VALUETYPE, and LAST_INTEGER_SCALABLE_VECTOR_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
integer_valuetypes()
static mvt_range llvm::MVT::integer_valuetypes () inline static
Definition at line 1129 of file MachineValueType.h.
References FIRST_INTEGER_VALUETYPE, and LAST_INTEGER_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), PerformTruncatingStoreCombine(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
is1024BitVector()
bool llvm::MVT::is1024BitVector () const inline
Return true if this is a 1024-bit vector type.
Definition at line 374 of file MachineValueType.h.
References v1024i1, v128i8, v16i64, v32i32, and v64i16.
Referenced by llvm::EVT::is1024BitVector().
is128BitVector()
bool llvm::MVT::is128BitVector () const inline
Return true if this is a 128-bit vector type.
Definition at line 349 of file MachineValueType.h.
References v128i1, v16i8, v1i128, v2f64, v2i64, v4f32, v4i32, v8f16, and v8i16.
Referenced by callingConvSupported(), CC_AArch64_Custom_Block(), combineCVTP2I_CVTTP2I(), combineExtractSubvector(), combineVectorSignBitsTruncation(), combineX86INT_TO_FP(), combineX86ShuffleChain(), ExtractBitFromMaskVector(), llvm::X86TTIImpl::getCmpSelInstrCost(), getVPTESTMOpc(), getZeroVector(), InsertBitToMaskVector(), llvm::EVT::is128BitVector(), isHorizontalBinOp(), LowerADDSAT_SUBSAT(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), LowerBuildVectorv4x32(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerRotate(), LowerSCALAR_TO_VECTOR(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRotate(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPSHUFB(), lowerShuffleWithUndefHalf(), LowerTruncateVecI1(), lowerVECTOR_SHUFFLE(), LowerVectorCTPOP(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsInsertPS(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), narrowExtractedVectorSelect(), performAddSubLongCombine(), scalarizeVectorStore(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), SupportedVectorShiftWithImm(), and SupportedVectorVarShift().
is16BitVector()
bool llvm::MVT::is16BitVector () const inline
Return true if this is a 16-bit vector type.
Definition at line 328 of file MachineValueType.h.
References v16i1, v1i16, and v2i8.
Referenced by llvm::EVT::is16BitVector().
is2048BitVector()
bool llvm::MVT::is2048BitVector () const inline
Return true if this is a 2048-bit vector type.
Definition at line 381 of file MachineValueType.h.
References v128i16, v256i8, v32i64, and v64i32.
Referenced by llvm::EVT::is2048BitVector().
is256BitVector()
bool llvm::MVT::is256BitVector () const inline
Return true if this is a 256-bit vector type.
Definition at line 358 of file MachineValueType.h.
References v16f16, v16i16, v256i1, v32i8, v4f64, v4i64, v8f32, and v8i32.
Referenced by CC_X86_VectorCallGetSSEs(), combineConcatVectorOps(), combineLogicBlendIntoPBLENDV(), combineVectorSignBitsTruncation(), combineX86ShuffleChain(), ExpandHorizontalBinOp(), ExtractBitFromMaskVector(), getHopForBuildVector(), getVPTESTMOpc(), getZeroVector(), InsertBitToMaskVector(), llvm::EVT::is256BitVector(), isHopBuildVector(), isHorizontalBinOp(), Lower256IntUnary(), Lower256IntVSETCC(), LowerABS(), LowerADDSAT_SUBSAT(), lowerAddSub(), LowerAVXCONCAT_VECTORS(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), LowerCONCAT_VECTORS(), LowerEXTEND_VECTOR_INREG(), LowerMINMAX(), LowerMUL(), LowerMULH(), LowerRotate(), LowerShift(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsRotate(), lowerShuffleWithPSHUFB(), lowerShuffleWithUndefHalf(), LowerStore(), LowerToHorizontalOp(), LowerTruncateVecI1(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZ(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTPOP(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), narrowExtractedVectorSelect(), narrowShuffle(), split256IntArith(), SupportedVectorShiftWithImm(), and SupportedVectorVarShift().
is32BitVector()
bool llvm::MVT::is32BitVector () const inline
Return true if this is a 32-bit vector type.
Definition at line 334 of file MachineValueType.h.
References v1f32, v1i32, v2f16, v2i16, v32i1, and v4i8.
Referenced by CC_AArch64_Custom_Block(), and llvm::EVT::is32BitVector().
is512BitVector()
bool llvm::MVT::is512BitVector () const inline
Return true if this is a 512-bit vector type.
Definition at line 366 of file MachineValueType.h.
References v16f32, v16i32, v32f16, v32i16, v512i1, v64i8, v8f64, and v8i64.
Referenced by CC_X86_VectorCallGetSSEs(), combineShuffleToAddSubOrFMAddSub(), combineVectorSignBitsTruncation(), combineX86ShuffleChain(), ExtractBitFromMaskVector(), llvm::X86TargetLowering::getSetCCResultType(), getVPTESTMOpc(), getZeroVector(), InsertBitToMaskVector(), llvm::EVT::is512BitVector(), Lower512IntUnary(), LowerAVXCONCAT_VECTORS(), LowerBITREVERSE(), LowerBUILD_VECTORAsVariablePermute(), lowerBuildVectorAsBroadcast(), LowerCONCAT_VECTORS(), LowerEXTEND_VECTOR_INREG(), LowerMGATHER(), LowerMSCATTER(), LowerMSTORE(), LowerScalarImmediateShift(), LowerShift(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleWithPSHUFB(), lowerShuffleWithUndefHalf(), lowerShuffleWithVPMOV(), LowerSIGN_EXTEND_Mask(), lowerToAddSubOrFMAddSub(), lowerV4X128Shuffle(), lowerVECTOR_SHUFFLE(), LowerVectorCTLZ(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTPOP(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), narrowExtractedVectorSelect(), narrowShuffle(), split512IntArith(), and SupportedVectorShiftWithImm().
is64BitVector()
bool llvm::MVT::is64BitVector () const inline
Return true if this is a 64-bit vector type.
Definition at line 341 of file MachineValueType.h.
References v1f64, v1i64, v2f32, v2i32, v4f16, v4i16, v64i1, and v8i8.
Referenced by CC_AArch64_Custom_Block(), llvm::EVT::is64BitVector(), and tryExtendDUPToExtractHigh().
isByteSized()
bool llvm::MVT::isByteSized () const inline
Returns true if the number of bits for the type is a multiple of an 8-bit byte.
Definition at line 858 of file MachineValueType.h.
References getSizeInBits(), and llvm::TypeSize::isByteSized().
isFixedLengthVector()
bool llvm::MVT::isFixedLengthVector () const inline
Definition at line 322 of file MachineValueType.h.
References FIRST_FIXEDLEN_VECTOR_VALUETYPE, and LAST_FIXEDLEN_VECTOR_VALUETYPE.
isFloatingPoint()
bool llvm::MVT::isFloatingPoint () const inline
Return true if this is a FP or a vector FP type.
Definition at line 284 of file MachineValueType.h.
References FIRST_FP_FIXEDLEN_VECTOR_VALUETYPE, FIRST_FP_SCALABLE_VECTOR_VALUETYPE, FIRST_FP_VALUETYPE, LAST_FP_FIXEDLEN_VECTOR_VALUETYPE, LAST_FP_SCALABLE_VECTOR_VALUETYPE, and LAST_FP_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), buildCallOperands(), CC_MipsO32(), CC_X86_32_VectorCall(), CC_X86_64_VectorCall(), combineTargetShuffle(), combineX86ShuffleChain(), combineX86ShufflesConstants(), EltsFromConsecutiveLoads(), EmitAVX512Test(), getConstantVector(), getCopyFromParts(), getCopyToParts(), getTargetShuffleAndZeroables(), llvm::TargetLoweringBase::getTypeToPromoteTo(), getVCmpInst(), getZeroVector(), isAddSubOrSubAdd(), llvm::EVT::isFloatingPoint(), lowerAddSubToHorizontalOp(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBUILD_VECTORAsVariablePermute(), lowerShuffleAsBroadcast(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerVECTOR_SHUFFLE(), performST1ScatterCombine(), pickOpcodeForVT(), truncateScalarIntegerArg(), and UnpackFromArgumentSlot().
isInteger()
bool llvm::MVT::isInteger () const inline
Return true if this is an integer or a vector integer type.
Definition at line 294 of file MachineValueType.h.
References FIRST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE, FIRST_INTEGER_SCALABLE_VECTOR_VALUETYPE, FIRST_INTEGER_VALUETYPE, LAST_INTEGER_FIXEDLEN_VECTOR_VALUETYPE, LAST_INTEGER_SCALABLE_VECTOR_VALUETYPE, and LAST_INTEGER_VALUETYPE.
Referenced by llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), CC_MipsO32_FP64(), computeBytesPoppedByCalleeForSRet(), getCopyFromParts(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getPromotedVectorElementType(), GetRegistersForValue(), getShuffleScalarElt(), llvm::TargetLoweringBase::getTypeToPromoteTo(), InsertBitToMaskVector(), llvm::EVT::isInteger(), isValueTypeInRegForCC(), lower256BitShuffle(), Lower256IntUnary(), Lower512IntUnary(), LowerABS(), LowerADDSAT_SUBSAT(), lowerAddSub(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerFPToInt(), LowerLoad(), LowerSCALAR_TO_VECTOR(), lowerShuffleAsBitBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsTruncBroadcast(), LowerStore(), matchUnaryShuffle(), llvm::TargetLowering::ParseConstraints(), split256IntArith(), split512IntArith(), and truncateScalarIntegerArg().
isOverloaded()
bool llvm::MVT::isOverloaded () const inline
Return true if this is an overloaded type for TableGen.
Definition at line 387 of file MachineValueType.h.
References Any, fAny, iAny, iPTRAny, and vAny.
isPow2VectorType()
bool llvm::MVT::isPow2VectorType () const inline
Returns true if the given vector is a power of 2.
Definition at line 403 of file MachineValueType.h.
References getVectorNumElements().
Referenced by getPow2VectorType(), llvm::SITargetLowering::getPreferredVectorAction(), and llvm::TargetLoweringBase::getPreferredVectorAction().
isScalableVector()
bool llvm::MVT::isScalableVector () const inline
Return true if this is a vector value type where the runtime length is machine dependent.
Definition at line 317 of file MachineValueType.h.
References FIRST_SCALABLE_VECTOR_VALUETYPE, and LAST_SCALABLE_VECTOR_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::TargetLoweringBase::computeRegisterProperties(), llvm::HexagonTargetLowering::getPreferredVectorAction(), getVectorElementCount(), llvm::HexagonSubtarget::isHVXVectorType(), llvm::EVT::isScalableVector(), mayTailCallThisCC(), and parsePredicateConstraint().
isScalarInteger()
bool llvm::MVT::isScalarInteger () const inline
Return true if this is an integer, not including vectors.
Definition at line 304 of file MachineValueType.h.
References FIRST_INTEGER_VALUETYPE, and LAST_INTEGER_VALUETYPE.
Referenced by hasBZHI(), llvm::EVT::isScalarInteger(), LowerBITCAST(), llvm::HexagonTargetLowering::LowerSETCC(), llvm::HexagonTargetLowering::LowerVSELECT(), and truncateScalarIntegerArg().
isValid()
bool llvm::MVT::isValid () const inline
Return true if this is a valid simple valuetype.
Definition at line 278 of file MachineValueType.h.
References FIRST_VALUETYPE, and LAST_VALUETYPE.
Referenced by llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::CallLowering::handleAssignments(), llvm::TargetLoweringBase::initActions(), llvm::LLT::LLT(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setLoadExtAction(), and llvm::TargetLoweringBase::setTruncStoreAction().
isVector()
bool llvm::MVT::isVector () const inline
Return true if this is a vector value type.
Definition at line 310 of file MachineValueType.h.
References FIRST_VECTOR_VALUETYPE, and LAST_VECTOR_VALUETYPE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::PPCTargetLowering::allowsMisalignedMemoryAccesses(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), CC_AIX(), CC_MipsO32_FP64(), CC_X86_32_VectorCall(), CC_X86_64_VectorCall(), combineAndnp(), combineX86ShufflesRecursively(), computeBytesPoppedByCalleeForSRet(), convertLocVTToValVT(), convertValVTToLocVT(), EmitAVX512Test(), llvm::X86TTIImpl::getCmpSelInstrCost(), getComparePred(), getCopyFromParts(), getCopyToPartsVector(), getFauxShuffleMask(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::getLLTForMVT(), getMemCmpLoad(), getPromotedVectorElementType(), getScalarType(), getScalarValueForVectorElement(), llvm::X86TargetLowering::getSetCCResultType(), llvm::X86TTIImpl::getShuffleCost(), getVPTESTMOpc(), isCalleeLoad(), llvm::HexagonSubtarget::isHVXVectorType(), isMulPowOf2(), isSExtLoad(), isValueTypeInRegForCC(), llvm::EVT::isVector(), llvm::LLT::LLT(), LowerAVXExtend(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), LowerBITREVERSE_XOP(), LowerCTLZ(), LowerCTPOP(), LowerCTTZ(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFPToInt(), LowerFunnelShift(), lowerINT_TO_FP_vXi64(), LowerLoad(), lowerRegToMasks(), llvm::AArch64CallLowering::lowerReturn(), LowerRotate(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerStore(), LowerTruncateVecI1(), lowerUINT_TO_FP_vec(), lowerX86FPLogicOp(), parseTexFail(), performConcatVectorsCombine(), pickOpcodeForVT(), processShaderInputArgs(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::HexagonTargetLowering::shouldExpandAtomicRMWInIR(), shouldGuaranteeTCO(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), unrollVectorShift(), and VerifyVectorType().
operator!=()
bool llvm::MVT::operator!= (const MVT & S) const inline
Definition at line 273 of file MachineValueType.h.
References SimpleTy.
Referenced by getVectorVT().
operator<()
bool llvm::MVT::operator< (const MVT & S) const inline
Definition at line 271 of file MachineValueType.h.
References SimpleTy.
operator<=()
bool llvm::MVT::operator<= (const MVT & S) const inline
Definition at line 275 of file MachineValueType.h.
References SimpleTy.
operator==()
bool llvm::MVT::operator== (const MVT & S) const inline
Definition at line 272 of file MachineValueType.h.
References SimpleTy.
operator>()
bool llvm::MVT::operator> (const MVT & S) const inline
Definition at line 270 of file MachineValueType.h.
References SimpleTy.
operator>=()
bool llvm::MVT::operator>= (const MVT & S) const inline
Definition at line 274 of file MachineValueType.h.
References SimpleTy.
scalable_vector_valuetypes()
static mvt_range llvm::MVT::scalable_vector_valuetypes () inline static
Definition at line 1150 of file MachineValueType.h.
References FIRST_SCALABLE_VECTOR_VALUETYPE, and LAST_SCALABLE_VECTOR_VALUETYPE.
vector_valuetypes()
static mvt_range llvm::MVT::vector_valuetypes () inline static
Definition at line 1139 of file MachineValueType.h.
References FIRST_VECTOR_VALUETYPE, and LAST_VECTOR_VALUETYPE.
Member Data Documentation
SimpleTy
SimpleValueType llvm::MVT::SimpleTy = INVALID_SIMPLE_VALUE_TYPE
Definition at line 265 of file MachineValueType.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::MipsSETargetLowering::allowsMisalignedMemoryAccesses(), llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses(), AnalyzeReturnValues(), buildCallOperands(), CC_AArch64_Custom_Block(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), CC_Lanai32_VarArg(), CC_MipsO32_FP64(), llvm::EVT::changeVectorElementTypeToInteger(), checkV64LaneV128(), combineBitcastvxi1(), computeBytesPoppedByCalleeForSRet(), createVariablePermute(), llvm::SITargetLowering::denormalsEnabledForType(), EnsureStackAlignment(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::TargetLowering::findOptimalMemOpLowering(), llvm::ARMTargetLowering::findRepresentativeClass(), llvm::X86TargetLowering::findRepresentativeClass(), llvm::TargetLoweringBase::findRepresentativeClass(), foldVectorXorShiftIntoCmp(), getAL(), llvm::R600RegisterInfo::getCFGStructurizerRegClass(), getCompareCC(), getComparePred(), llvm::TargetLoweringBase::getCondCodeAction(), getContiguousRangeOfSetBits(), getDUPLANEOp(), llvm::EVT::getEVTString(), getExtensionTo64Bits(), GetFPLibCall(), getImplicitScaleFactor(), llvm::EVT::getIntegerVT(), getIntOperandFromRegisterString(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLoadExtAction(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getOperationAction(), llvm::EVT::getRawBits(), llvm::TargetLoweringBase::getRegClassFor(), llvm::HexagonTargetLowering::getRegForInlineAsmConstraint(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLoweringBase::getRegisterType(), llvm::TargetLoweringBase::getRepRegClassCostFor(), llvm::TargetLoweringBase::getRepRegClassFor(), getScalableVectorVT(), llvm::ARMTargetLowering::getScalingFactorCost(), llvm::AVRTargetLowering::getSetCCResultType(), llvm::TargetLoweringBase::getSetCCResultType(), getSVEContainerType(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::TargetLoweringBase::ValueTypeActionImpl::getTypeAction(), llvm::EVT::getTypeForEVT(), llvm::TargetLoweringBase::getTypeToPromoteTo(), llvm::SelectionDAG::getValueType(), getVectorTyFromPredicateVector(), llvm::EVT::getVectorVT(), getVectorVT(), getVPTESTMOpc(), is32Bit(), isConstantSplatVectorMaskForType(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::ARMTargetLowering::isFNegFree(), llvm::PPCTargetLowering::isFPImmLegal(), isLegalAddressImmediate(), llvm::ARMTargetLowering::isLegalAddressingMode(), isLegalT1AddressImmediate(), isLegalT2AddressImmediate(), llvm::ARMTargetLowering::isLegalT2ScaledAddressingMode(), isMulPowOf2(), isOpcWithIntImmediate(), isPerfectIncrement(), IsPTXVectorType(), isSExtLoad(), llvm::EVT::isSimple(), isSinCosLibcallAvailable(), llvm::TargetLoweringBase::isTypeLegal(), llvm::HexagonInstrInfo::isValidAutoIncImm(), isValidIndexedLoad(), isVMOVModifiedImm(), llvm::XCoreTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), lower128BitShuffle(), lower1BitShuffle(), lower256BitShuffle(), lower512BitShuffle(), lowerCallResult(), LowerCallResult(), LowerCMP_SWAP(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::BPFTargetLowering::LowerOperation(), lowerRegToMasks(), LowerSADDSUBSAT(), lowerShuffleAsBlend(), lowerUINT_TO_FP_vec(), llvm::EVT::operator!=(), operator!=(), llvm::EVT::compareRawBits::operator()(), operator<(), operator<=(), operator==(), operator>(), operator>=(), performLD1GatherCombine(), performST1ScatterCombine(), pickOpcodeForVT(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), SDValueToConstBool(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::selectIndexedProgMemLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::NVPTXDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::TargetLoweringBase::ValueTypeActionImpl::setTypeAction(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), ShrinkLoadReplaceStoreWithStore(), llvm::WebAssembly::toValType(), truncateScalarIntegerArg(), unpackFromRegLoc(), usePartialVectorLoads(), useSinCos(), VerifySDNode(), X86ChooseCmpImmediateOpcode(), and X86ChooseCmpOpcode().
The documentation for this class was generated from the following files:
include/llvm/Support/MachineValueType.h
lib/CodeGen/ValueTypes.cpp