LLVM: llvm::BTFStringTable Class Reference
llvm::BTFStringTable Class Reference
String table.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFStringTable ()
uint32_t getSize ()
std::vector< std::string > & getTable ()
uint32_t addString (StringRef S)
Add a string to the string table and returns its offset in the table.
Detailed Description
String table.
Definition at line 193 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFStringTable()
llvm::BTFStringTable::BTFStringTable () inline
Definition at line 204 of file BTFDebug.h.
Member Function Documentation
addString()
uint32_t BTFStringTable::addString (StringRef S)
Add a string to the string table and returns its offset in the table.
Definition at line 368 of file BTFDebug.cpp.
References Size, and llvm::StringRef::size().
Referenced by llvm::BTFDebug::addString().
getSize()
uint32_t llvm::BTFStringTable::getSize () inline
Definition at line 205 of file BTFDebug.h.
References Size.
Referenced by llvm::BTFDebug::BTFDebug().
getTable()
std::vector<std::string>& llvm::BTFStringTable::getTable () inline
Definition at line 206 of file BTFDebug.h.
Referenced by llvm::BTFDebug::BTFDebug().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp