LLVM: llvm::orc::remote::DirectBufferWriter Class Reference
llvm::orc::remote::DirectBufferWriter Class Reference
#include "llvm/ExecutionEngine/Orc/OrcRemoteTargetRPCAPI.h"
Public Member Functions
DirectBufferWriter ()=default
DirectBufferWriter (const char *Src, JITTargetAddress Dst, uint64_t Size)
const char * getSrc () const
JITTargetAddress getDst () const
uint64_t getSize () const
Detailed Description
Definition at line 58 of file OrcRemoteTargetRPCAPI.h.
Constructor & Destructor Documentation
DirectBufferWriter() [1/2]
llvm::orc::remote::DirectBufferWriter::DirectBufferWriter () default
DirectBufferWriter() [2/2]
llvm::orc::remote::DirectBufferWriter::DirectBufferWriter (const char * Src, JITTargetAddress Dst, uint64_t Size) inline
Definition at line 61 of file OrcRemoteTargetRPCAPI.h.
Member Function Documentation
getDst()
JITTargetAddress llvm::orc::remote::DirectBufferWriter::getDst () const inline
Definition at line 65 of file OrcRemoteTargetRPCAPI.h.
Referenced by llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize().
getSize()
uint64_t llvm::orc::remote::DirectBufferWriter::getSize () const inline
Definition at line 66 of file OrcRemoteTargetRPCAPI.h.
References Size.
Referenced by llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize().
getSrc()
const char* llvm::orc::remote::DirectBufferWriter::getSrc () const inline
Definition at line 64 of file OrcRemoteTargetRPCAPI.h.
Referenced by llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRemoteTargetRPCAPI.h