LLVM: llvm::codeview::CVRecord< Kind > Class Template Reference
llvm::codeview::CVRecord< Kind > Class Template Reference
CVRecord is a fat pointer (base + size pair) to a symbol or type record.
#include "llvm/DebugInfo/CodeView/CVRecord.h"
Public Member Functions
CVRecord ()=default
CVRecord (ArrayRef< uint8_t > Data)
CVRecord (const RecordPrefix *P, size_t Size)
bool valid () const
uint32_t length () const
Kind kind () const
ArrayRef< uint8_t > data () const
StringRef str_data () const
ArrayRef< uint8_t > content () const
Public Attributes
ArrayRef< uint8_t > RecordData
Detailed Description
template<typename Kind>
class llvm::codeview::CVRecord< Kind >
CVRecord is a fat pointer (base + size pair) to a symbol or type record.
Carrying the size separately instead of trusting the size stored in the record prefix provides some extra safety and flexibility.
Definition at line 30 of file CVRecord.h.
Constructor & Destructor Documentation
CVRecord() [1/3]
template<typename Kind> llvm::codeview::CVRecord< Kind >::CVRecord () default
CVRecord() [2/3]
template<typename Kind> llvm::codeview::CVRecord< Kind >::CVRecord (ArrayRef< uint8_t > Data) inline
Definition at line 34 of file CVRecord.h.
CVRecord() [3/3]
template<typename Kind> llvm::codeview::CVRecord< Kind >::CVRecord (const RecordPrefix * P, size_t Size) inline
Definition at line 36 of file CVRecord.h.
Member Function Documentation
content()
template<typename Kind> ArrayRef<uint8_t> llvm::codeview::CVRecord< Kind >::content () const inline
Definition at line 57 of file CVRecord.h.
Referenced by llvm::codeview::TypeDeserializer::deserializeAs(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), getSymbolKindName(), llvm::codeview::getSymbolName(), llvm::codeview::SymbolDeserializer::visitSymbolBegin(), llvm::codeview::TypeDeserializer::visitTypeBegin(), llvm::codeview::TypeDumpVisitor::visitTypeEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
data()
template<typename Kind> ArrayRef<uint8_t> llvm::codeview::CVRecord< Kind >::data () const inline
Definition at line 50 of file CVRecord.h.
Referenced by llvm::pdb::DbiModuleDescriptorBuilder::addSymbol(), llvm::BinaryItemTraits< llvm::codeview::CVType >::bytes(), getHashForUdt(), getTagRecordHashForUdt(), and llvm::pdb::hashTypeRecord().
kind()
template<typename Kind> Kind llvm::codeview::CVRecord< Kind >::kind () const inline
Definition at line 43 of file CVRecord.h.
Referenced by llvm::pdb::GSIHashStreamBuilder::addSymbol(), createRecord(), llvm::codeview::TypeDeserializer::deserializeAs(), llvm::codeview::SymbolDeserializer::deserializeAs(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), llvm::pdb::TpiStream::findFullDeclForForwardRef(), llvm::pdb::SymbolCache::findSymbolByTypeIndex(), finishVisitation(), llvm::CodeViewYAML::LeafRecord::fromCodeViewRecord(), fromCodeViewRecordImpl(), llvm::CodeViewYAML::SymbolRecord::fromCodeViewSymbol(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), fromCodeViewSymbolImpl(), llvm::codeview::getModifiedType(), llvm::pdb::SymbolCache::getOrCreateGlobalSymbolByOffset(), llvm::codeview::getScopeEndOffset(), llvm::codeview::getScopeParentOffset(), getSymbolKindName(), llvm::codeview::getSymbolName(), getSymbolNameOffset(), llvm::pdb::hashTagRecord(), llvm::pdb::hashTypeRecord(), llvm::codeview::isUdtForwardRef(), llvm::codeview::limitSymbolArrayToScope(), llvm::codeview::mergeIdRecords(), llvm::pdb::NativeEnumGlobals::NativeEnumGlobals(), llvm::pdb::NativeEnumTypes::NativeEnumTypes(), llvm::codeview::SimpleTypeSerializer::serialize(), llvm::codeview::CVRecord< TypeLeafKind >::valid(), visitKnownRecord(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), visitMemberRecord(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeDumpVisitor::visitTypeBegin(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
length()
template<typename Kind> uint32_t llvm::codeview::CVRecord< Kind >::length () const inline
Definition at line 41 of file CVRecord.h.
Referenced by llvm::codeview::DebugSymbolsSubsection::addSymbol(), llvm::BinaryItemTraits< llvm::codeview::CVType >::length(), and llvm::codeview::TypeRecordMapping::visitTypeBegin().
str_data()
template<typename Kind> StringRef llvm::codeview::CVRecord< Kind >::str_data () const inline
Definition at line 52 of file CVRecord.h.
valid()
template<typename Kind> bool llvm::codeview::CVRecord< Kind >::valid () const inline
Definition at line 39 of file CVRecord.h.
Member Data Documentation
RecordData
template<typename Kind> ArrayRef<uint8_t> llvm::codeview::CVRecord< Kind >::RecordData
Definition at line 61 of file CVRecord.h.
Referenced by llvm::BinaryItemTraits< codeview::CVSymbol >::bytes(), llvm::codeview::CVRecord< TypeLeafKind >::content(), llvm::codeview::CVRecord< TypeLeafKind >::data(), llvm::codeview::discoverTypeIndices(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), llvm::pdb::GSIHashStreamBuilder::SymbolDenseMapInfo::getHashValue(), llvm::codeview::GloballyHashedType::hashType(), llvm::codeview::LocallyHashedType::hashTypeCollection(), llvm::codeview::GloballyHashedType::hashTypeCollection(), llvm::pdb::GSIHashStreamBuilder::SymbolDenseMapInfo::isEqual(), llvm::codeview::CVRecord< TypeLeafKind >::kind(), llvm::BinaryItemTraits< codeview::CVSymbol >::length(), llvm::codeview::CVRecord< TypeLeafKind >::length(), llvm::codeview::limitSymbolArrayToScope(), llvm::codeview::CVRecord< TypeLeafKind >::str_data(), and llvm::codeview::SymbolSerializer::visitSymbolEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/CVRecord.h