LLVM: llvm::AVRInstrInfo Class Reference
llvm::AVRInstrInfo Class Reference
Utilities related to the AVR instruction set.
#include "Target/AVR/AVRInstrInfo.h"
Public Member Functions
AVRInstrInfo ()
const AVRRegisterInfo & getRegisterInfo () const
const MCInstrDesc & getBrCond (AVRCC::CondCodes CC) const
AVRCC::CondCodes getCondFromBranchOpc (unsigned Opc) const
AVRCC::CondCodes getOppositeCondition (AVRCC::CondCodes CC) const
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
MachineBasicBlock * getBranchDestBlock (const MachineInstr &MI) const override
bool isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
unsigned insertIndirectBranch (MachineBasicBlock &MBB, MachineBasicBlock &NewDestBB, const DebugLoc &DL, int64_t BrOffset, RegScavenger *RS) const override
Detailed Description
Utilities related to the AVR instruction set.
Definition at line 64 of file AVRInstrInfo.h.
Constructor & Destructor Documentation
AVRInstrInfo()
llvm::AVRInstrInfo::AVRInstrInfo () explicit
Definition at line 38 of file AVRInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool llvm::AVRInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Definition at line 263 of file AVRInstrInfo.cpp.
copyPhysReg()
void llvm::AVRInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 41 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::AVRSubtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::AVRSubtarget::hasMOVW(), llvm_unreachable, and TRI.
getBranchDestBlock()
MachineBasicBlock * llvm::AVRInstrInfo::getBranchDestBlock (const MachineInstr & MI) const override
Definition at line 504 of file AVRInstrInfo.cpp.
References llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm_unreachable.
getBrCond()
const MCInstrDesc & llvm::AVRInstrInfo::getBrCond (AVRCC::CondCodes CC) const
Definition at line 194 of file AVRInstrInfo.cpp.
References llvm::AVRCC::COND_EQ, llvm::AVRCC::COND_GE, llvm::AVRCC::COND_LO, llvm::AVRCC::COND_LT, llvm::AVRCC::COND_MI, llvm::AVRCC::COND_NE, llvm::AVRCC::COND_PL, llvm::AVRCC::COND_SH, and llvm_unreachable.
Referenced by llvm::AVRTargetLowering::EmitInstrWithCustomInserter().
getCondFromBranchOpc()
AVRCC::CondCodes llvm::AVRInstrInfo::getCondFromBranchOpc (unsigned Opc) const
Definition at line 217 of file AVRInstrInfo.cpp.
References llvm::AVRCC::COND_EQ, llvm::AVRCC::COND_GE, llvm::AVRCC::COND_INVALID, llvm::AVRCC::COND_LO, llvm::AVRCC::COND_LT, llvm::AVRCC::COND_MI, llvm::AVRCC::COND_NE, llvm::AVRCC::COND_PL, and llvm::AVRCC::COND_SH.
Referenced by removeBranch().
getInstSizeInBytes()
unsigned llvm::AVRInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
Definition at line 476 of file AVRInstrInfo.cpp.
References llvm::ISD::EH_LABEL, llvm::AVRSubtarget::getInstrInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MCInstrDesc::getSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::AMDGPUISD::KILL, TII, and llvm::SystemZISD::TM.
Referenced by insertIndirectBranch(), and removeBranch().
getOppositeCondition()
AVRCC::CondCodes llvm::AVRInstrInfo::getOppositeCondition (AVRCC::CondCodes CC) const
Definition at line 240 of file AVRInstrInfo.cpp.
References llvm::AVRCC::COND_EQ, llvm::AVRCC::COND_GE, llvm::AVRCC::COND_LO, llvm::AVRCC::COND_LT, llvm::AVRCC::COND_MI, llvm::AVRCC::COND_NE, llvm::AVRCC::COND_PL, llvm::AVRCC::COND_SH, and llvm_unreachable.
getRegisterInfo()
const AVRRegisterInfo& llvm::AVRInstrInfo::getRegisterInfo () const inline
Definition at line 68 of file AVRInstrInfo.h.
References llvm::ISD::FrameIndex, getOppositeCondition(), MI, and TRI.
Referenced by llvm::AVRSubtarget::getRegisterInfo().
insertBranch()
unsigned llvm::AVRInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 398 of file AVRInstrInfo.cpp.
insertIndirectBranch()
unsigned llvm::AVRInstrInfo::insertIndirectBranch (MachineBasicBlock & MBB, MachineBasicBlock & NewDestBB, const DebugLoc & DL, int64_t BrOffset, RegScavenger * RS) const override
Definition at line 558 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), getInstSizeInBytes(), and MI.
isBranchOffsetInRange()
bool llvm::AVRInstrInfo::isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
Definition at line 532 of file AVRInstrInfo.cpp.
References llvm::isIntN(), and llvm_unreachable.
isLoadFromStackSlot()
unsigned llvm::AVRInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 82 of file AVRInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), and llvm::MachineOperand::isImm().
isStoreToStackSlot()
unsigned llvm::AVRInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 101 of file AVRInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), and llvm::MachineOperand::isImm().
loadRegFromStackSlot()
void llvm::AVRInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 159 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::MVT::i16, llvm::MVT::i8, llvm::TargetRegisterInfo::isTypeLegalForClass(), llvm_unreachable, and llvm::MachineMemOperand::MOLoad.
removeBranch()
unsigned llvm::AVRInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 437 of file AVRInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::AVRCC::COND_INVALID, llvm::MachineBasicBlock::end(), getCondFromBranchOpc(), getInstSizeInBytes(), and I.
reverseBranchCondition()
bool llvm::AVRInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 466 of file AVRInstrInfo.cpp.
storeRegToStackSlot()
void llvm::AVRInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 120 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::MVT::i16, llvm::MVT::i8, llvm::TargetRegisterInfo::isTypeLegalForClass(), llvm_unreachable, llvm::MachineMemOperand::MOStore, and llvm::AVRMachineFunctionInfo::setHasSpills().
The documentation for this class was generated from the following files:
lib/Target/AVR/AVRInstrInfo.h
lib/Target/AVR/AVRInstrInfo.cpp