LLVM: llvm::MipsTargetStreamer Class Reference
llvm::MipsTargetStreamer Class Reference
#include "Target/Mips/MipsTargetStreamer.h"
Public Member Functions
MipsTargetStreamer (MCStreamer &S)
virtual void setPic (bool Value)
virtual void emitDirectiveSetMicroMips ()
virtual void emitDirectiveSetNoMicroMips ()
virtual void setUsesMicroMips ()
virtual void emitDirectiveSetMips16 ()
virtual void emitDirectiveSetNoMips16 ()
virtual void emitDirectiveSetReorder ()
virtual void emitDirectiveSetNoReorder ()
virtual void emitDirectiveSetMacro ()
virtual void emitDirectiveSetNoMacro ()
virtual void emitDirectiveSetMsa ()
virtual void emitDirectiveSetNoMsa ()
virtual void emitDirectiveSetMt ()
virtual void emitDirectiveSetNoMt ()
virtual void emitDirectiveSetCRC ()
virtual void emitDirectiveSetNoCRC ()
virtual void emitDirectiveSetVirt ()
virtual void emitDirectiveSetNoVirt ()
virtual void emitDirectiveSetGINV ()
virtual void emitDirectiveSetNoGINV ()
virtual void emitDirectiveSetAt ()
virtual void emitDirectiveSetAtWithArg (unsigned RegNo)
virtual void emitDirectiveSetNoAt ()
virtual void emitDirectiveEnd (StringRef Name)
virtual void emitDirectiveEnt (const MCSymbol &Symbol)
virtual void emitDirectiveAbiCalls ()
virtual void emitDirectiveNaN2008 ()
virtual void emitDirectiveNaNLegacy ()
virtual void emitDirectiveOptionPic0 ()
virtual void emitDirectiveOptionPic2 ()
virtual void emitDirectiveInsn ()
virtual void emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg)
virtual void emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff)
virtual void emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff)
virtual void emitDirectiveSetArch (StringRef Arch)
virtual void emitDirectiveSetMips0 ()
virtual void emitDirectiveSetMips1 ()
virtual void emitDirectiveSetMips2 ()
virtual void emitDirectiveSetMips3 ()
virtual void emitDirectiveSetMips4 ()
virtual void emitDirectiveSetMips5 ()
virtual void emitDirectiveSetMips32 ()
virtual void emitDirectiveSetMips32R2 ()
virtual void emitDirectiveSetMips32R3 ()
virtual void emitDirectiveSetMips32R5 ()
virtual void emitDirectiveSetMips32R6 ()
virtual void emitDirectiveSetMips64 ()
virtual void emitDirectiveSetMips64R2 ()
virtual void emitDirectiveSetMips64R3 ()
virtual void emitDirectiveSetMips64R5 ()
virtual void emitDirectiveSetMips64R6 ()
virtual void emitDirectiveSetDsp ()
virtual void emitDirectiveSetDspr2 ()
virtual void emitDirectiveSetNoDsp ()
virtual void emitDirectiveSetPop ()
virtual void emitDirectiveSetPush ()
virtual void emitDirectiveSetSoftFloat ()
virtual void emitDirectiveSetHardFloat ()
virtual void emitDirectiveCpLoad (unsigned RegNo)
virtual void emitDirectiveCpLocal (unsigned RegNo)
virtual bool emitDirectiveCpRestore (int Offset, function_ref< unsigned()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
virtual void emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol &Sym, bool IsReg)
virtual void emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister)
virtual void emitDirectiveModuleFP ()
virtual void emitDirectiveModuleOddSPReg ()
virtual void emitDirectiveModuleSoftFloat ()
virtual void emitDirectiveModuleHardFloat ()
virtual void emitDirectiveModuleMT ()
virtual void emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value)
virtual void emitDirectiveSetOddSPReg ()
virtual void emitDirectiveSetNoOddSPReg ()
virtual void emitDirectiveModuleCRC ()
virtual void emitDirectiveModuleNoCRC ()
virtual void emitDirectiveModuleVirt ()
virtual void emitDirectiveModuleNoVirt ()
virtual void emitDirectiveModuleGINV ()
virtual void emitDirectiveModuleNoGINV ()
void emitR (unsigned Opcode, unsigned Reg0, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitII (unsigned Opcode, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRX (unsigned Opcode, unsigned Reg0, MCOperand Op1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRI (unsigned Opcode, unsigned Reg0, int32_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRR (unsigned Opcode, unsigned Reg0, unsigned Reg1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRX (unsigned Opcode, unsigned Reg0, unsigned Reg1, MCOperand Op2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRR (unsigned Opcode, unsigned Reg0, unsigned Reg1, unsigned Reg2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRRX (unsigned Opcode, unsigned Reg0, unsigned Reg1, unsigned Reg2, MCOperand Op3, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRI (unsigned Opcode, unsigned Reg0, unsigned Reg1, int16_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRIII (unsigned Opcode, unsigned Reg0, unsigned Reg1, int16_t Imm0, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitAddu (unsigned DstReg, unsigned SrcReg, unsigned TrgReg, bool Is64Bit, const MCSubtargetInfo *STI)
void emitDSLL (unsigned DstReg, unsigned SrcReg, int16_t ShiftAmount, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitEmptyDelaySlot (bool hasShortDelaySlot, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitNop (SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitStoreWithImmOffset (unsigned Opcode, unsigned SrcReg, unsigned BaseReg, int64_t Offset, function_ref< unsigned()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a store instruction with an offset.
void emitLoadWithImmOffset (unsigned Opcode, unsigned DstReg, unsigned BaseReg, int64_t Offset, unsigned TmpReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a load instruction with an immediate offset.
void emitGPRestore (int Offset, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit the $gp restore operation for .cprestore.
void forbidModuleDirective ()
void reallowModuleDirective ()
bool isModuleDirectiveAllowed ()
template<class PredicateLibrary >
void updateABIInfo (const PredicateLibrary &P)
MipsABIFlagsSection & getABIFlagsSection ()
const MipsABIInfo & getABI () const
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Protected Attributes
llvm::Optional< MipsABIInfo > ABI
MipsABIFlagsSection ABIFlagsSection
bool GPRInfoSet
unsigned GPRBitMask
int GPROffset
bool FPRInfoSet
unsigned FPRBitMask
int FPROffset
bool FrameInfoSet
int FrameOffset
unsigned FrameReg
unsigned GPReg
unsigned ReturnReg
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 24 of file MipsTargetStreamer.h.
Constructor & Destructor Documentation
MipsTargetStreamer()
MipsTargetStreamer::MipsTargetStreamer (MCStreamer & S)
Definition at line 41 of file MipsTargetStreamer.cpp.
References FPRInfoSet, FrameInfoSet, and GPRInfoSet.
Member Function Documentation
emitAddu()
void MipsTargetStreamer::emitAddu (unsigned DstReg, unsigned SrcReg, unsigned TrgReg, bool Is64Bit, const MCSubtargetInfo * STI)
Definition at line 257 of file MipsTargetStreamer.cpp.
References emitRRR().
Referenced by setPic().
emitDirectiveAbiCalls()
void MipsTargetStreamer::emitDirectiveAbiCalls () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 71 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveCpLoad()
void MipsTargetStreamer::emitDirectiveCpLoad (unsigned RegNo) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 112 of file MipsTargetStreamer.cpp.
Referenced by setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveCpLocal()
void MipsTargetStreamer::emitDirectiveCpLocal (unsigned RegNo) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 113 of file MipsTargetStreamer.cpp.
References forbidModuleDirective(), getABI(), and GPReg.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveCpLocal(), llvm::MipsTargetELFStreamer::emitDirectiveCpLocal(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveCpRestore()
bool MipsTargetStreamer::emitDirectiveCpRestore (int Offset, function_ref< unsigned()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo * STI) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 130 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveCpRestore(), llvm::MipsTargetELFStreamer::emitDirectiveCpRestore(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveCpreturn()
void MipsTargetStreamer::emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 139 of file MipsTargetStreamer.cpp.
Referenced by setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveCpsetup()
void MipsTargetStreamer::emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol & Sym, bool IsReg) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 136 of file MipsTargetStreamer.cpp.
Referenced by setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveEnd()
void MipsTargetStreamer::emitDirectiveEnd (StringRef Name) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 69 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveEnt()
void MipsTargetStreamer::emitDirectiveEnt (const MCSymbol & Symbol) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 70 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveInsn()
void MipsTargetStreamer::emitDirectiveInsn () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 76 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsAsmPrinter::EmitBasicBlockEnd(), llvm::MipsTargetAsmStreamer::emitDirectiveInsn(), llvm::MipsTargetELFStreamer::emitDirectiveInsn(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveModuleCRC()
void MipsTargetStreamer::emitDirectiveModuleCRC () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 151 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleFP()
void MipsTargetStreamer::emitDirectiveModuleFP () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 142 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and setPic().
emitDirectiveModuleGINV()
void MipsTargetStreamer::emitDirectiveModuleGINV () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 155 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleHardFloat()
void MipsTargetStreamer::emitDirectiveModuleHardFloat () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 149 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleMT()
void MipsTargetStreamer::emitDirectiveModuleMT () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 150 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleNoCRC()
void MipsTargetStreamer::emitDirectiveModuleNoCRC () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 152 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleNoGINV()
void MipsTargetStreamer::emitDirectiveModuleNoGINV () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 156 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleNoVirt()
void MipsTargetStreamer::emitDirectiveModuleNoVirt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 154 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleOddSPReg()
void MipsTargetStreamer::emitDirectiveModuleOddSPReg () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 144 of file MipsTargetStreamer.cpp.
References ABIFlagsSection, llvm::MipsABIFlagsSection::Is32BitABI, llvm::MipsABIFlagsSection::OddSPReg, and llvm::report_fatal_error().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and setPic().
emitDirectiveModuleSoftFloat()
void MipsTargetStreamer::emitDirectiveModuleSoftFloat () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 148 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveModuleVirt()
void MipsTargetStreamer::emitDirectiveModuleVirt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 153 of file MipsTargetStreamer.cpp.
Referenced by setPic().
emitDirectiveNaN2008()
void MipsTargetStreamer::emitDirectiveNaN2008 () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 72 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveNaNLegacy()
void MipsTargetStreamer::emitDirectiveNaNLegacy () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 73 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveOptionPic0()
void MipsTargetStreamer::emitDirectiveOptionPic0 () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 74 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveOptionPic2()
void MipsTargetStreamer::emitDirectiveOptionPic2 () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 75 of file MipsTargetStreamer.cpp.
Referenced by setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveSetArch()
void MipsTargetStreamer::emitDirectiveSetArch (StringRef Arch) virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 82 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetArch(), and setPic().
emitDirectiveSetAt()
void MipsTargetStreamer::emitDirectiveSetAt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 64 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetAt(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and setPic().
emitDirectiveSetAtWithArg()
void MipsTargetStreamer::emitDirectiveSetAtWithArg (unsigned RegNo) virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 65 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetAtWithArg(), and setPic().
emitDirectiveSetCRC()
void MipsTargetStreamer::emitDirectiveSetCRC () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 58 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetCRC(), and setPic().
emitDirectiveSetDsp()
void MipsTargetStreamer::emitDirectiveSetDsp () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 109 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetDsp(), and setPic().
emitDirectiveSetDspr2()
void MipsTargetStreamer::emitDirectiveSetDspr2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 110 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetDspr2(), and setPic().
emitDirectiveSetFp()
void MipsTargetStreamer::emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value) virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 157 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetFp(), and setPic().
emitDirectiveSetGINV()
void MipsTargetStreamer::emitDirectiveSetGINV () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 62 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetGINV(), and setPic().
emitDirectiveSetHardFloat()
void MipsTargetStreamer::emitDirectiveSetHardFloat () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 106 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetHardFloat(), and setPic().
emitDirectiveSetMacro()
void MipsTargetStreamer::emitDirectiveSetMacro () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 52 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMacro(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and setPic().
emitDirectiveSetMicroMips()
void MipsTargetStreamer::emitDirectiveSetMicroMips () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 45 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveSetMips0()
void MipsTargetStreamer::emitDirectiveSetMips0 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 85 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips0(), and setPic().
emitDirectiveSetMips1()
void MipsTargetStreamer::emitDirectiveSetMips1 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 86 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips1(), and setPic().
emitDirectiveSetMips16()
void MipsTargetStreamer::emitDirectiveSetMips16 () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 48 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveSetMips2()
void MipsTargetStreamer::emitDirectiveSetMips2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 87 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips2(), and setPic().
emitDirectiveSetMips3()
void MipsTargetStreamer::emitDirectiveSetMips3 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 88 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips3(), and setPic().
emitDirectiveSetMips32()
void MipsTargetStreamer::emitDirectiveSetMips32 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 91 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32(), and setPic().
emitDirectiveSetMips32R2()
void MipsTargetStreamer::emitDirectiveSetMips32R2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 92 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32R2(), and setPic().
emitDirectiveSetMips32R3()
void MipsTargetStreamer::emitDirectiveSetMips32R3 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 93 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32R3(), and setPic().
emitDirectiveSetMips32R5()
void MipsTargetStreamer::emitDirectiveSetMips32R5 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 94 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32R5(), and setPic().
emitDirectiveSetMips32R6()
void MipsTargetStreamer::emitDirectiveSetMips32R6 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 95 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32R6(), and setPic().
emitDirectiveSetMips4()
void MipsTargetStreamer::emitDirectiveSetMips4 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 89 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips4(), and setPic().
emitDirectiveSetMips5()
void MipsTargetStreamer::emitDirectiveSetMips5 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 90 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips5(), and setPic().
emitDirectiveSetMips64()
void MipsTargetStreamer::emitDirectiveSetMips64 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 96 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64(), and setPic().
emitDirectiveSetMips64R2()
void MipsTargetStreamer::emitDirectiveSetMips64R2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 97 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64R2(), and setPic().
emitDirectiveSetMips64R3()
void MipsTargetStreamer::emitDirectiveSetMips64R3 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 98 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64R3(), and setPic().
emitDirectiveSetMips64R5()
void MipsTargetStreamer::emitDirectiveSetMips64R5 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 99 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64R5(), and setPic().
emitDirectiveSetMips64R6()
void MipsTargetStreamer::emitDirectiveSetMips64R6 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 100 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64R6(), and setPic().
emitDirectiveSetMsa()
void MipsTargetStreamer::emitDirectiveSetMsa () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 54 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMsa(), and setPic().
emitDirectiveSetMt()
void MipsTargetStreamer::emitDirectiveSetMt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 56 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMt(), and setPic().
emitDirectiveSetNoAt()
void MipsTargetStreamer::emitDirectiveSetNoAt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 68 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoAt(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), and setPic().
emitDirectiveSetNoCRC()
void MipsTargetStreamer::emitDirectiveSetNoCRC () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 59 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoCRC(), and setPic().
emitDirectiveSetNoDsp()
void MipsTargetStreamer::emitDirectiveSetNoDsp () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 111 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoDsp(), and setPic().
emitDirectiveSetNoGINV()
void MipsTargetStreamer::emitDirectiveSetNoGINV () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 63 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoGINV(), and setPic().
emitDirectiveSetNoMacro()
void MipsTargetStreamer::emitDirectiveSetNoMacro () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 53 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMacro(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), and setPic().
emitDirectiveSetNoMicroMips()
void MipsTargetStreamer::emitDirectiveSetNoMicroMips () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 46 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveSetNoMips16()
void MipsTargetStreamer::emitDirectiveSetNoMips16 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 49 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMips16(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and setPic().
emitDirectiveSetNoMsa()
void MipsTargetStreamer::emitDirectiveSetNoMsa () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 55 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMsa(), and setPic().
emitDirectiveSetNoMt()
void MipsTargetStreamer::emitDirectiveSetNoMt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 57 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMt(), and setPic().
emitDirectiveSetNoOddSPReg()
void MipsTargetStreamer::emitDirectiveSetNoOddSPReg () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 162 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoOddSPReg(), and setPic().
emitDirectiveSetNoReorder()
void MipsTargetStreamer::emitDirectiveSetNoReorder () virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 51 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionBodyStart(), needsExpandMemInst(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitDirectiveSetNoVirt()
void MipsTargetStreamer::emitDirectiveSetNoVirt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 61 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoVirt(), and setPic().
emitDirectiveSetOddSPReg()
void MipsTargetStreamer::emitDirectiveSetOddSPReg () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 161 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetOddSPReg(), and setPic().
emitDirectiveSetPop()
void MipsTargetStreamer::emitDirectiveSetPop () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 101 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetPop(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and setPic().
emitDirectiveSetPush()
void MipsTargetStreamer::emitDirectiveSetPush () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 102 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetPush(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and setPic().
emitDirectiveSetReorder()
void MipsTargetStreamer::emitDirectiveSetReorder () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 50 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetReorder(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), needsExpandMemInst(), and setPic().
emitDirectiveSetSoftFloat()
void MipsTargetStreamer::emitDirectiveSetSoftFloat () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 103 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetSoftFloat(), and setPic().
emitDirectiveSetVirt()
void MipsTargetStreamer::emitDirectiveSetVirt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 60 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetVirt(), and setPic().
emitDSLL()
void MipsTargetStreamer::emitDSLL (unsigned DstReg, unsigned SrcReg, int16_t ShiftAmount, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 264 of file MipsTargetStreamer.cpp.
References emitRRI().
Referenced by covertDoubleImmToSingleImm(), isShiftedUIntAtAnyPosition(), and setPic().
emitEmptyDelaySlot()
void MipsTargetStreamer::emitEmptyDelaySlot (bool hasShortDelaySlot, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 275 of file MipsTargetStreamer.cpp.
References emitRR(), and emitRRI().
Referenced by covertDoubleImmToSingleImm(), needsExpandMemInst(), and setPic().
emitFMask()
void MipsTargetStreamer::emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 80 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::printSavedRegsBitmask(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitFrame()
void MipsTargetStreamer::emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 77 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::emitFrameDirective(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitGPRestore()
void MipsTargetStreamer::emitGPRestore (int Offset, SMLoc IDLoc, const MCSubtargetInfo * STI)
Emit the $gp restore operation for .cprestore.
Definition at line 291 of file MipsTargetStreamer.cpp.
References emitLoadWithImmOffset(), and GPReg.
Referenced by needsExpandMemInst(), and setPic().
emitII()
void MipsTargetStreamer::emitII (unsigned Opcode, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 195 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCStreamer::EmitInstruction(), llvm::MCTargetStreamer::getStreamer(), llvm::MCInst::setLoc(), and llvm::MCInst::setOpcode().
Referenced by covertDoubleImmToSingleImm(), and setPic().
emitLoadWithImmOffset()
void MipsTargetStreamer::emitLoadWithImmOffset (unsigned Opcode, unsigned DstReg, unsigned BaseReg, int64_t Offset, unsigned TmpReg, SMLoc IDLoc, const MCSubtargetInfo * STI)
Emit a load instruction with an immediate offset.
DstReg and TmpReg are permitted to be the same register iff DstReg is distinct from BaseReg and DstReg is a GPR. It is the callers responsibility to identify such cases and pass the appropriate register in TmpReg.
Definition at line 334 of file MipsTargetStreamer.cpp.
References emitRI(), emitRRI(), emitRRR(), and llvm::isInt< 16 >().
Referenced by emitGPRestore(), and setPic().
emitMask()
void MipsTargetStreamer::emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) virtual
Reimplemented in llvm::MipsTargetELFStreamer, and llvm::MipsTargetAsmStreamer.
Definition at line 79 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::printSavedRegsBitmask(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
emitNop()
void MipsTargetStreamer::emitNop (SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 283 of file MipsTargetStreamer.cpp.
References emitRR(), emitRRI(), and isMicroMips().
Referenced by covertDoubleImmToSingleImm(), and setPic().
emitR()
void MipsTargetStreamer::emitR (unsigned Opcode, unsigned Reg0, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 166 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCStreamer::EmitInstruction(), llvm::MCTargetStreamer::getStreamer(), llvm::MCInst::setLoc(), and llvm::MCInst::setOpcode().
Referenced by covertDoubleImmToSingleImm(), and setPic().
emitRI()
void MipsTargetStreamer::emitRI (unsigned Opcode, unsigned Reg0, int32_t Imm, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 185 of file MipsTargetStreamer.cpp.
References llvm::MCOperand::createImm(), and emitRX().
Referenced by covertDoubleImmToSingleImm(), emitLoadWithImmOffset(), emitStoreWithImmOffset(), isShiftedUIntAtAnyPosition(), and setPic().
emitRR()
void MipsTargetStreamer::emitRR (unsigned Opcode, unsigned Reg0, unsigned Reg1, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 190 of file MipsTargetStreamer.cpp.
References llvm::MCOperand::createReg(), and emitRX().
Referenced by covertDoubleImmToSingleImm(), emitEmptyDelaySlot(), emitNop(), getRegisterForMxtrC0(), and setPic().
emitRRI()
void MipsTargetStreamer::emitRRI (unsigned Opcode, unsigned Reg0, unsigned Reg1, int16_t Imm, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 236 of file MipsTargetStreamer.cpp.
References llvm::MCOperand::createImm(), and emitRRX().
Referenced by covertDoubleImmToSingleImm(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), emitDSLL(), emitEmptyDelaySlot(), emitLoadWithImmOffset(), emitNop(), emitStoreWithImmOffset(), isShiftedUIntAtAnyPosition(), needsExpandMemInst(), nextReg(), and setPic().
emitRRIII()
void MipsTargetStreamer::emitRRIII (unsigned Opcode, unsigned Reg0, unsigned Reg1, int16_t Imm0, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 242 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCStreamer::EmitInstruction(), llvm::MCTargetStreamer::getStreamer(), llvm::MCInst::setLoc(), and llvm::MCInst::setOpcode().
Referenced by getRegisterForMxtrC0(), and setPic().
emitRRR()
void MipsTargetStreamer::emitRRR (unsigned Opcode, unsigned Reg0, unsigned Reg1, unsigned Reg2, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 217 of file MipsTargetStreamer.cpp.
References llvm::MCOperand::createReg(), and emitRRX().
Referenced by covertDoubleImmToSingleImm(), emitAddu(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), emitLoadWithImmOffset(), emitStoreWithImmOffset(), isShiftedUIntAtAnyPosition(), and setPic().
emitRRRX()
void MipsTargetStreamer::emitRRRX (unsigned Opcode, unsigned Reg0, unsigned Reg1, unsigned Reg2, MCOperand Op3, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 223 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCStreamer::EmitInstruction(), llvm::MCTargetStreamer::getStreamer(), llvm::MCInst::setLoc(), and llvm::MCInst::setOpcode().
Referenced by covertDoubleImmToSingleImm(), and setPic().
emitRRX()
void MipsTargetStreamer::emitRRX (unsigned Opcode, unsigned Reg0, unsigned Reg1, MCOperand Op2, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 205 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCStreamer::EmitInstruction(), llvm::MCTargetStreamer::getStreamer(), llvm::MCInst::setLoc(), and llvm::MCInst::setOpcode().
Referenced by covertDoubleImmToSingleImm(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), emitRRI(), emitRRR(), isShiftedUIntAtAnyPosition(), nextReg(), and setPic().
emitRX()
void MipsTargetStreamer::emitRX (unsigned Opcode, unsigned Reg0, MCOperand Op1, SMLoc IDLoc, const MCSubtargetInfo * STI)
Definition at line 175 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCStreamer::EmitInstruction(), llvm::MCTargetStreamer::getStreamer(), llvm::MCInst::setLoc(), and llvm::MCInst::setOpcode().
Referenced by covertDoubleImmToSingleImm(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), emitRI(), emitRR(), isShiftedUIntAtAnyPosition(), nextReg(), and setPic().
emitStoreWithImmOffset()
void MipsTargetStreamer::emitStoreWithImmOffset (unsigned Opcode, unsigned SrcReg, unsigned BaseReg, int64_t Offset, function_ref< unsigned()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo * STI)
Emit a store instruction with an offset.
Emit a store instruction with an immediate offset.
If the offset is out of range then it will be synthesized using the assembler temporary.
GetATReg() is a callback that can be used to obtain the current assembler temporary and is only called when the assembler temporary is required. It must handle the case where no assembler temporary is available (typically by reporting an error).
Definition at line 297 of file MipsTargetStreamer.cpp.
References emitRI(), emitRRI(), emitRRR(), and llvm::isInt< 16 >().
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveCpRestore(), and setPic().
forbidModuleDirective()
void llvm::MipsTargetStreamer::forbidModuleDirective () inline
Definition at line 164 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), emitDirectiveCpLocal(), emitDirectiveCpRestore(), llvm::MipsTargetAsmStreamer::emitDirectiveCpreturn(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), emitDirectiveInsn(), emitDirectiveSetArch(), emitDirectiveSetAt(), emitDirectiveSetAtWithArg(), emitDirectiveSetDsp(), emitDirectiveSetDspr2(), emitDirectiveSetFp(), emitDirectiveSetHardFloat(), emitDirectiveSetMacro(), llvm::MipsTargetAsmStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetELFStreamer::emitDirectiveSetMicroMips(), emitDirectiveSetMips0(), emitDirectiveSetMips1(), llvm::MipsTargetAsmStreamer::emitDirectiveSetMips16(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), emitDirectiveSetMips2(), emitDirectiveSetMips3(), emitDirectiveSetMips32(), emitDirectiveSetMips32R2(), emitDirectiveSetMips32R3(), emitDirectiveSetMips32R5(), emitDirectiveSetMips32R6(), emitDirectiveSetMips4(), emitDirectiveSetMips5(), emitDirectiveSetMips64(), emitDirectiveSetMips64R2(), emitDirectiveSetMips64R3(), emitDirectiveSetMips64R5(), emitDirectiveSetMips64R6(), emitDirectiveSetMsa(), emitDirectiveSetNoAt(), emitDirectiveSetNoDsp(), emitDirectiveSetNoMacro(), llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMicroMips(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoMicroMips(), emitDirectiveSetNoMips16(), emitDirectiveSetNoMsa(), emitDirectiveSetNoMt(), emitDirectiveSetNoOddSPReg(), llvm::MipsTargetAsmStreamer::emitDirectiveSetNoReorder(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder(), emitDirectiveSetOddSPReg(), emitDirectiveSetPop(), emitDirectiveSetPush(), emitDirectiveSetReorder(), emitDirectiveSetSoftFloat(), and llvm::MipsAsmPrinter::EmitInstruction().
getABI()
const MipsABIInfo& llvm::MipsTargetStreamer::getABI () const inline
Definition at line 177 of file MipsTargetStreamer.h.
References ABI, and assert().
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), emitDirectiveCpLocal(), llvm::MipsTargetELFStreamer::emitDirectiveCpRestore(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), and llvm::MipsTargetELFStreamer::finish().
getABIFlagsSection()
MipsABIFlagsSection& llvm::MipsTargetStreamer::getABIFlagsSection () inline
Definition at line 176 of file MipsTargetStreamer.h.
References ABIFlagsSection.
isModuleDirectiveAllowed()
bool llvm::MipsTargetStreamer::isModuleDirectiveAllowed () inline
Definition at line 166 of file MipsTargetStreamer.h.
reallowModuleDirective()
void llvm::MipsTargetStreamer::reallowModuleDirective () inline
Definition at line 165 of file MipsTargetStreamer.h.
setPic()
virtual void llvm::MipsTargetStreamer::setPic (bool Value) inline virtual
Reimplemented in llvm::MipsTargetELFStreamer.
Definition at line 28 of file MipsTargetStreamer.h.
References emitAddu(), emitDirectiveAbiCalls(), emitDirectiveCpLoad(), emitDirectiveCpLocal(), emitDirectiveCpRestore(), emitDirectiveCpreturn(), emitDirectiveCpsetup(), emitDirectiveEnd(), emitDirectiveEnt(), emitDirectiveInsn(), emitDirectiveModuleCRC(), emitDirectiveModuleFP(), emitDirectiveModuleGINV(), emitDirectiveModuleHardFloat(), emitDirectiveModuleMT(), emitDirectiveModuleNoCRC(), emitDirectiveModuleNoGINV(), emitDirectiveModuleNoVirt(), emitDirectiveModuleOddSPReg(), emitDirectiveModuleSoftFloat(), emitDirectiveModuleVirt(), emitDirectiveNaN2008(), emitDirectiveNaNLegacy(), emitDirectiveOptionPic0(), emitDirectiveOptionPic2(), emitDirectiveSetArch(), emitDirectiveSetAt(), emitDirectiveSetAtWithArg(), emitDirectiveSetCRC(), emitDirectiveSetDsp(), emitDirectiveSetDspr2(), emitDirectiveSetFp(), emitDirectiveSetGINV(), emitDirectiveSetHardFloat(), emitDirectiveSetMacro(), emitDirectiveSetMicroMips(), emitDirectiveSetMips0(), emitDirectiveSetMips1(), emitDirectiveSetMips16(), emitDirectiveSetMips2(), emitDirectiveSetMips3(), emitDirectiveSetMips32(), emitDirectiveSetMips32R2(), emitDirectiveSetMips32R3(), emitDirectiveSetMips32R5(), emitDirectiveSetMips32R6(), emitDirectiveSetMips4(), emitDirectiveSetMips5(), emitDirectiveSetMips64(), emitDirectiveSetMips64R2(), emitDirectiveSetMips64R3(), emitDirectiveSetMips64R5(), emitDirectiveSetMips64R6(), emitDirectiveSetMsa(), emitDirectiveSetMt(), emitDirectiveSetNoAt(), emitDirectiveSetNoCRC(), emitDirectiveSetNoDsp(), emitDirectiveSetNoGINV(), emitDirectiveSetNoMacro(), emitDirectiveSetNoMicroMips(), emitDirectiveSetNoMips16(), emitDirectiveSetNoMsa(), emitDirectiveSetNoMt(), emitDirectiveSetNoOddSPReg(), emitDirectiveSetNoReorder(), emitDirectiveSetNoVirt(), emitDirectiveSetOddSPReg(), emitDirectiveSetPop(), emitDirectiveSetPush(), emitDirectiveSetReorder(), emitDirectiveSetSoftFloat(), emitDirectiveSetVirt(), emitDSLL(), emitEmptyDelaySlot(), emitFMask(), emitFrame(), emitGPRestore(), emitII(), emitLoadWithImmOffset(), emitMask(), emitNop(), emitR(), emitRI(), emitRR(), emitRRI(), emitRRIII(), emitRRR(), emitRRRX(), emitRRX(), emitRX(), emitStoreWithImmOffset(), hasShortDelaySlot(), Name, ReturnReg, setUsesMicroMips(), and llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile().
setUsesMicroMips()
void MipsTargetStreamer::setUsesMicroMips () virtual
Reimplemented in llvm::MipsTargetELFStreamer.
Definition at line 47 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), needsExpandMemInst(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
updateABIInfo()
template<class PredicateLibrary > void llvm::MipsTargetStreamer::updateABIInfo (const PredicateLibrary & P) inline
Definition at line 171 of file MipsTargetStreamer.h.
References ABI, ABIFlagsSection, and llvm::MipsABIFlagsSection::setAllFromPredicates().
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and needsExpandMemInst().
Member Data Documentation
ABI
llvm::Optional<MipsABIInfo> llvm::MipsTargetStreamer::ABI protected
Definition at line 183 of file MipsTargetStreamer.h.
Referenced by getABI(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), and updateABIInfo().
ABIFlagsSection
MipsABIFlagsSection llvm::MipsTargetStreamer::ABIFlagsSection protected
Definition at line 184 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveModuleFP(), emitDirectiveModuleOddSPReg(), llvm::MipsTargetAsmStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetAsmStreamer::emitDirectiveSetFp(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), getABIFlagsSection(), and updateABIInfo().
FPRBitMask
unsigned llvm::MipsTargetStreamer::FPRBitMask protected
Definition at line 191 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFMask().
FPRInfoSet
bool llvm::MipsTargetStreamer::FPRInfoSet protected
Definition at line 190 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveEnt(), llvm::MipsTargetELFStreamer::emitFMask(), and MipsTargetStreamer().
FPROffset
int llvm::MipsTargetStreamer::FPROffset protected
Definition at line 192 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFMask().
FrameInfoSet
bool llvm::MipsTargetStreamer::FrameInfoSet protected
Definition at line 194 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveEnt(), llvm::MipsTargetELFStreamer::emitFrame(), and MipsTargetStreamer().
FrameOffset
int llvm::MipsTargetStreamer::FrameOffset protected
Definition at line 195 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFrame().
FrameReg
unsigned llvm::MipsTargetStreamer::FrameReg protected
Definition at line 196 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFrame().
GPRBitMask
unsigned llvm::MipsTargetStreamer::GPRBitMask protected
Definition at line 187 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitMask().
GPReg
unsigned llvm::MipsTargetStreamer::GPReg protected
Definition at line 197 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), emitDirectiveCpLocal(), llvm::MipsTargetELFStreamer::emitDirectiveCpRestore(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), and emitGPRestore().
GPRInfoSet
bool llvm::MipsTargetStreamer::GPRInfoSet protected
Definition at line 186 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveEnt(), llvm::MipsTargetELFStreamer::emitMask(), and MipsTargetStreamer().
GPROffset
int llvm::MipsTargetStreamer::GPROffset protected
Definition at line 188 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitMask().
ReturnReg
unsigned llvm::MipsTargetStreamer::ReturnReg protected
Definition at line 198 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitFrame(), setPic(), and llvm::MipsTargetELFStreamer::setPic().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsTargetStreamer.h
lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp