LLVM: llvm::RISCVInstrInfo Class Reference
llvm::RISCVInstrInfo Class Reference
#include "Target/RISCV/RISCVInstrInfo.h"
Public Member Functions
RISCVInstrInfo (RISCVSubtarget &STI)
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, MCRegister DstReg, MCRegister SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DstReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void movImm (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, Register DstReg, uint64_t Val, MachineInstr::MIFlag Flag=MachineInstr::NoFlags) const
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &dl, int *BytesAdded=nullptr) const override
unsigned insertIndirectBranch (MachineBasicBlock &MBB, MachineBasicBlock &NewDestBB, const DebugLoc &DL, int64_t BrOffset, RegScavenger *RS=nullptr) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
MachineBasicBlock * getBranchDestBlock (const MachineInstr &MI) const override
bool isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
bool isAsCheapAsAMove (const MachineInstr &MI) const override
bool verifyInstruction (const MachineInstr &MI, StringRef &ErrInfo) const override
bool getMemOperandWithOffsetWidth (const MachineInstr &LdSt, const MachineOperand *&BaseOp, int64_t &Offset, unsigned &Width, const TargetRegisterInfo *TRI) const
bool areMemAccessesTriviallyDisjoint (const MachineInstr &MIa, const MachineInstr &MIb) const override
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
virtual bool isFunctionSafeToOutlineFrom (MachineFunction &MF, bool OutlineFromLinkOnceODRs) const override
virtual bool isMBBSafeToOutlineFrom (MachineBasicBlock &MBB, unsigned &Flags) const override
outliner::OutlinedFunction getOutliningCandidateInfo (std::vector< outliner::Candidate > &RepeatedSequenceLocs) const override
virtual outliner::InstrType getOutliningType (MachineBasicBlock::iterator &MBBI, unsigned Flags) const override
virtual void buildOutlinedFrame (MachineBasicBlock &MBB, MachineFunction &MF, const outliner::OutlinedFunction &OF) const override
virtual MachineBasicBlock::iterator insertOutlinedCall (Module &M, MachineBasicBlock &MBB, MachineBasicBlock::iterator &It, MachineFunction &MF, const outliner::Candidate &C) const override
Protected Attributes
const RISCVSubtarget & STI
Detailed Description
Definition at line 26 of file RISCVInstrInfo.h.
Constructor & Destructor Documentation
RISCVInstrInfo()
RISCVInstrInfo::RISCVInstrInfo (RISCVSubtarget & STI) explicit
Definition at line 35 of file RISCVInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool RISCVInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 236 of file RISCVInstrInfo.cpp.
areMemAccessesTriviallyDisjoint()
bool RISCVInstrInfo::areMemAccessesTriviallyDisjoint (const MachineInstr & MIa, const MachineInstr & MIb) const override
Definition at line 585 of file RISCVInstrInfo.cpp.
References assert(), getMemOperandWithOffsetWidth(), llvm::RISCVSubtarget::getRegisterInfo(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineOperand::isIdenticalTo(), llvm::max(), llvm::MachineInstr::mayLoadOrStore(), STI, and TRI.
buildOutlinedFrame()
void RISCVInstrInfo::buildOutlinedFrame (MachineBasicBlock & MBB, MachineFunction & MF, const outliner::OutlinedFunction & OF) const override virtual
Definition at line 761 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::RegState::Define, E, llvm::MachineBasicBlock::end(), I, and llvm::MachineBasicBlock::insert().
copyPhysReg()
void RISCVInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, MCRegister DstReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 88 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::getKillRegState(), and llvm_unreachable.
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > RISCVInstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 617 of file RISCVInstrInfo.cpp.
References llvm::BitmaskEnumDetail::Mask(), and llvm::RISCVII::MO_DIRECT_FLAG_MASK.
getBranchDestBlock()
MachineBasicBlock * RISCVInstrInfo::getBranchDestBlock (const MachineInstr & MI) const override
Definition at line 425 of file RISCVInstrInfo.cpp.
References assert(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOperand(), and llvm::MCInstrDesc::isBranch().
getInstSizeInBytes()
unsigned RISCVInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
Definition at line 453 of file RISCVInstrInfo.cpp.
References llvm::ISD::EH_LABEL, llvm::MachineInstr::getMF(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::AMDGPUISD::KILL, MRI, llvm::ARM_MB::ST, STI, and llvm::SystemZISD::TM.
Referenced by getOutliningCandidateInfo(), and removeBranch().
getMemOperandWithOffsetWidth()
bool RISCVInstrInfo::getMemOperandWithOffsetWidth (const MachineInstr & LdSt, const MachineOperand *& BaseOp, int64_t & Offset, unsigned & Width, const TargetRegisterInfo * TRI) const
Definition at line 562 of file RISCVInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::hasOneMemOperand(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoadOrStore(), and llvm::MachineInstr::memoperands_begin().
Referenced by areMemAccessesTriviallyDisjoint().
getOutliningCandidateInfo()
outliner::OutlinedFunction RISCVInstrInfo::getOutliningCandidateInfo (std::vector< outliner::Candidate > & RepeatedSequenceLocs) const override
Definition at line 668 of file RISCVInstrInfo.cpp.
References llvm::LiveRegUnits::available(), C, E, getInstSizeInBytes(), I, MachineOutlinerDefault, llvm::remove_if(), and TRI.
getOutliningType()
outliner::InstrType RISCVInstrInfo::getOutliningType (MachineBasicBlock::iterator & MBBI, unsigned Flags) const override virtual
Definition at line 713 of file RISCVInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MCInstrDesc::hasImplicitDefOfPhysReg(), llvm::outliner::Illegal, llvm::outliner::Invisible, llvm::MachineInstr::isCFIInstruction(), llvm::MachineInstr::isInlineAsm(), llvm::MachineInstr::isMetaInstruction(), llvm::MachineInstr::isPosition(), llvm::MachineInstr::isReturn(), llvm::MachineInstr::isTerminator(), llvm::LegalizeActions::Legal, MI, llvm::MachineInstr::modifiesRegister(), llvm::MachineInstr::operands(), llvm::MachineBasicBlock::succ_empty(), and TRI.
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > RISCVInstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 623 of file RISCVInstrInfo.cpp.
References llvm::makeArrayRef(), llvm::RISCVII::MO_CALL, llvm::RISCVII::MO_GOT_HI, llvm::AVRII::MO_HI, llvm::AVRII::MO_LO, llvm::RISCVII::MO_PCREL_HI, llvm::RISCVII::MO_PCREL_LO, llvm::PPCII::MO_PLT, llvm::RISCVII::MO_TLS_GD_HI, llvm::RISCVII::MO_TLS_GOT_HI, llvm::RISCVII::MO_TPREL_ADD, llvm::MipsII::MO_TPREL_HI, and llvm::MipsII::MO_TPREL_LO.
insertBranch()
unsigned RISCVInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & dl, int * BytesAdded = nullptr) const override
Definition at line 338 of file RISCVInstrInfo.cpp.
insertIndirectBranch()
unsigned RISCVInstrInfo::insertIndirectBranch (MachineBasicBlock & MBB, MachineBasicBlock & NewDestBB, const DebugLoc & DL, int64_t BrOffset, RegScavenger * RS = nullptr) const override
Definition at line 375 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::clearVirtRegs(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getParent(), llvm::isInt< 32 >(), llvm::RegState::Kill, llvm::RISCVII::MO_HI, llvm::RISCVII::MO_LO, MRI, llvm::MachineBasicBlock::pred_size(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::report_fatal_error(), llvm::RegScavenger::scavengeRegisterBackwards(), llvm::RegScavenger::setRegUsed(), and llvm::SystemZISD::TM.
insertOutlinedCall()
MachineBasicBlock::iterator RISCVInstrInfo::insertOutlinedCall (Module & M, MachineBasicBlock & MBB, MachineBasicBlock::iterator & It, MachineFunction & MF, const outliner::Candidate & C) const override virtual
Definition at line 787 of file RISCVInstrInfo.cpp.
References llvm::BuildMI(), llvm::MachineFunction::getName(), llvm::Module::getNamedValue(), llvm::MachineBasicBlock::insert(), and llvm::RISCVII::MO_CALL.
isAsCheapAsAMove()
bool RISCVInstrInfo::isAsCheapAsAMove (const MachineInstr & MI) const override
Definition at line 492 of file RISCVInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isAsCheapAsAMove(), and llvm::MachineOperand::isReg().
isBranchOffsetInRange()
bool RISCVInstrInfo::isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
Definition at line 432 of file RISCVInstrInfo.cpp.
References llvm::isIntN(), and llvm_unreachable.
isFunctionSafeToOutlineFrom()
bool RISCVInstrInfo::isFunctionSafeToOutlineFrom (MachineFunction & MF, bool OutlineFromLinkOnceODRs) const override virtual
Definition at line 640 of file RISCVInstrInfo.cpp.
References F(), llvm::MachineFunction::getFunction(), llvm::GlobalValue::hasLinkOnceODRLinkage(), and llvm::GlobalObject::hasSection().
isLoadFromStackSlot()
unsigned RISCVInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 39 of file RISCVInstrInfo.cpp.
References llvm::X86ISD::FLD, llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), and llvm::ARM_MB::LD.
isMBBSafeToOutlineFrom()
bool RISCVInstrInfo::isMBBSafeToOutlineFrom (MachineBasicBlock & MBB, unsigned & Flags) const override virtual
Definition at line 657 of file RISCVInstrInfo.cpp.
isStoreToStackSlot()
unsigned RISCVInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 65 of file RISCVInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), and llvm::MachineOperand::isImm().
loadRegFromStackSlot()
void RISCVInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DstReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 140 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::X86ISD::FLD, llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::ARM_MB::LD, and llvm_unreachable.
movImm()
void RISCVInstrInfo::movImm (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, Register DstReg, uint64_t Val, MachineInstr::MIFlag Flag = MachineInstr::NoFlags) const
Definition at line 164 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RISCVMatInt::generateInstSeq(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), is64Bit(), llvm::isInt< 32 >(), llvm::RegState::Kill, MRI, llvm::report_fatal_error(), llvm::MachineInstrBuilder::setMIFlag(), and llvm::SmallVectorBase::size().
Referenced by llvm::RISCVRegisterInfo::eliminateFrameIndex(), and llvm::RISCVFrameLowering::hasBP().
removeBranch()
unsigned RISCVInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 304 of file RISCVInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), getInstSizeInBytes(), llvm::MachineBasicBlock::getLastNonDebugInstr(), and I.
reverseBranchCondition()
bool RISCVInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 417 of file RISCVInstrInfo.cpp.
storeRegToStackSlot()
void RISCVInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 113 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getKillRegState(), llvm::TargetRegisterInfo::getRegSizeInBits(), and llvm_unreachable.
verifyInstruction()
bool RISCVInstrInfo::verifyInstruction (const MachineInstr & MI, StringRef & ErrInfo) const override
Definition at line 505 of file RISCVInstrInfo.cpp.
References llvm::enumerate(), llvm::MCInstrInfo::get(), llvm::MachineOperand::getImm(), llvm::RISCVSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), llvm_unreachable, llvm::RISCVOp::OPERAND_FIRST_RISCV_IMM, llvm::RISCVOp::OPERAND_LAST_RISCV_IMM, llvm::RISCVOp::OPERAND_SIMM12, llvm::RISCVOp::OPERAND_SIMM13_LSB0, llvm::RISCVOp::OPERAND_SIMM21_LSB0, llvm::RISCVOp::OPERAND_UIMM12, llvm::RISCVOp::OPERAND_UIMM20, llvm::RISCVOp::OPERAND_UIMM4, llvm::RISCVOp::OPERAND_UIMM5, llvm::RISCVOp::OPERAND_UIMMLOG2XLEN, llvm::MCInstrDesc::operands(), and STI.
Member Data Documentation
STI
const RISCVSubtarget& llvm::RISCVInstrInfo::STI protected
Definition at line 134 of file RISCVInstrInfo.h.
Referenced by areMemAccessesTriviallyDisjoint(), getInstSizeInBytes(), and verifyInstruction().
The documentation for this class was generated from the following files:
lib/Target/RISCV/RISCVInstrInfo.h
lib/Target/RISCV/RISCVInstrInfo.cpp