LLVM: llvm::AMDGPUTargetLowering Class Reference
llvm::AMDGPUTargetLowering Class Reference abstract
#include "Target/AMDGPU/AMDGPUISelLowering.h"
Public Types
enum ImplicitParameter { FIRST_IMPLICIT, GRID_DIM = FIRST_IMPLICIT, GRID_OFFSET }
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register, C_RegisterClass, C_Memory, C_Immediate,
C_Other, C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1, CW_Okay = 0, CW_Good = 1, CW_Better = 2,
CW_Best = 3, CW_SpecificReg = CW_Okay, CW_Register = CW_Good, CW_Memory = CW_Better,
CW_Constant = CW_Best, CW_Default = CW_Okay
}
using AsmOperandInfoVector = std::vector< AsmOperandInfo >
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction : uint8_t {
Legal, Promote, Expand, LibCall,
Custom
}
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
enum LegalizeTypeAction : uint8_t {
TypeLegal, TypePromoteInteger, TypeExpandInteger, TypeSoftenFloat,
TypeExpandFloat, TypeScalarizeVector, TypeSplitVector, TypeWidenVector,
TypePromoteFloat
}
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
enum BooleanContent { UndefinedBooleanContent, ZeroOrOneBooleanContent, ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect, ScalarCondVectorVal, VectorMaskSelect }
Enum that describes what type of support for selects the target has.
enum AtomicExpansionKind {
AtomicExpansionKind::None, AtomicExpansionKind::LLSC, AtomicExpansionKind::LLOnly, AtomicExpansionKind::CmpXChg,
AtomicExpansionKind::MaskedIntrinsic
}
Enum that specifies what an atomic load/AtomicRMWInst is expanded to, if at all.
enum MulExpansionKind { MulExpansionKind::Always, MulExpansionKind::OnlyLegalOrCustom }
Enum that specifies when a multiplication should be expanded.
enum ReciprocalEstimate : int { Unspecified = -1, Disabled = 0, Enabled = 1 }
Reciprocal estimate status values used by the functions below.
using LegalizeKind = std::pair< LegalizeTypeAction, EVT >
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
using ArgListTy = std::vector< ArgListEntry >
Public Member Functions
AMDGPUTargetLowering (const TargetMachine &TM, const AMDGPUSubtarget &STI)
bool mayIgnoreSignedZero (SDValue Op) const
bool isFAbsFree (EVT VT) const override
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
bool isFNegFree (EVT VT) const override
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
bool isTruncateFree (EVT Src, EVT Dest) const override
bool isTruncateFree (Type *Src, Type *Dest) const override
Return true if it's free to truncate a value of type FromTy to type ToTy.
bool isZExtFree (Type *Src, Type *Dest) const override
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
bool isZExtFree (EVT Src, EVT Dest) const override
bool isZExtFree (SDValue Val, EVT VT2) const override
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
bool isNarrowingProfitable (EVT VT1, EVT VT2) const override
Return true if it's profitable to narrow operations of type VT1 to VT2.
MVT getVectorIdxTy (const DataLayout &) const override
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
bool isSelectSupported (SelectSupportKind) const override
bool isFPImmLegal (const APFloat &Imm, EVT VT, bool ForCodeSize) const override
Returns true if the target can instruction select the specified FP immediate natively.
bool ShouldShrinkFPConstant (EVT VT) const override
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtType, EVT ExtVT) const override
Return true if it is profitable to reduce a load to a smaller type.
bool isLoadBitCastBeneficial (EVT, EVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const final
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
bool storeOfVectorConstantIsCheap (EVT MemVT, unsigned NumElem, unsigned AS) const override
Return true if it is expected to be cheaper to do a store of a non-zero vector constant with the given size and type for the address space than to store the individual scalar element constants.
bool aggressivelyPreferBuildVectorSources (EVT VecVT) const override
bool isCheapToSpeculateCttz () const override
Return true if it is cheap to speculate a call to intrinsic cttz.
bool isCheapToSpeculateCtlz () const override
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool isSDNodeAlwaysUniform (const SDNode *N) const override
SDValue LowerReturn (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SDLoc &DL, SelectionDAG &DAG) const override
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
SDValue addTokenForArgument (SDValue Chain, SelectionDAG &DAG, MachineFrameInfo &MFI, int ClobberedFI) const
SDValue lowerUnhandledCall (CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals, StringRef Reason) const
SDValue LowerCall (CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower calls into the specified DAG.
SDValue LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
SDValue combineFMinMaxLegacy (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, SDValue True, SDValue False, SDValue CC, DAGCombinerInfo &DCI) const
Generate Min/Max node.
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
bool mergeStoresAfterLegalization (EVT) const override
Allow store merging for the specified type after legalization in addition to before legalization.
bool isFsqrtCheap (SDValue Operand, SelectionDAG &DAG) const override
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
SDValue getSqrtEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps, bool &UseOneConstNR, bool Reciprocal) const override
Hooks for building estimates in place of slower divisions and square roots.
SDValue getRecipEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps) const override
Return a reciprocal estimate value for the input operand.
virtual SDNode * PostISelFolding (MachineSDNode *N, SelectionDAG &DAG) const =0
void computeKnownBitsForTargetNode (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const override
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero and KnownOne bitsets.
unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const override
This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
bool isKnownNeverNaNForTargetNode (SDValue Op, const SelectionDAG &DAG, bool SNaN=false, unsigned Depth=0) const override
If SNaN is false,.
SDValue CreateLiveInRegister (SelectionDAG &DAG, const TargetRegisterClass *RC, unsigned Reg, EVT VT, const SDLoc &SL, bool RawReg=false) const
Helper function that adds Reg to the LiveIn list of the DAG's MachineFunction.
SDValue CreateLiveInRegister (SelectionDAG &DAG, const TargetRegisterClass *RC, unsigned Reg, EVT VT) const
SDValue CreateLiveInRegisterRaw (SelectionDAG &DAG, const TargetRegisterClass *RC, unsigned Reg, EVT VT) const
SDValue loadStackInputValue (SelectionDAG &DAG, EVT VT, const SDLoc &SL, int64_t Offset) const
Similar to CreateLiveInRegister, except value maybe loaded from a stack slot rather than passed in a register.
SDValue storeStackInputValue (SelectionDAG &DAG, const SDLoc &SL, SDValue Chain, SDValue ArgVal, int64_t Offset) const
SDValue loadInputValue (SelectionDAG &DAG, const TargetRegisterClass *RC, EVT VT, const SDLoc &SL, const ArgDescriptor &Arg) const
uint32_t getImplicitParameterOffset (const MachineFunction &MF, const ImplicitParameter Param) const
Helper function that returns the byte offset of the given type of implicit parameter.
MVT getFenceOperandTy (const DataLayout &DL) const override
Return the type for operands of fence.
AtomicExpansionKind shouldExpandAtomicRMWInIR (AtomicRMWInst *) const override
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetLowering &)=delete
TargetLowering & operator= (const TargetLowering &)=delete
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
bool isPositionIndependent () const
virtual bool isSDNodeSourceOfDivergence (const SDNode *N, FunctionLoweringInfo *FLI, LegacyDivergenceAnalysis *DA) const
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
virtual bool isIndexingLegal (MachineInstr &MI, Register Base, Register Offset, bool IsPre, MachineRegisterInfo &MRI) const
Returns true if the specified base+offset is a legal indexed addressing mode for this target.
virtual unsigned getJumpTableEncoding () const
Return the entry encoding for a jump table in the current function.
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
virtual bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const
Return true if folding a constant offset with the given GlobalAddress is legal.
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
Check whether a given call node is in tail position within its function.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS) const
Soften the operands of a comparison.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS, SDValue &Chain, bool IsSignaling=false) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, ArrayRef< SDValue > Ops, MakeLibCallOptions CallOptions, const SDLoc &dl, SDValue Chain=SDValue()) const
Returns a pair of (return value, chain).
bool parametersInCSRMatch (const MachineRegisterInfo &MRI, const uint32_t *CallerPreservedMask, const SmallVectorImpl< CCValAssign > &ArgLocs, const SmallVectorImpl< SDValue > &OutVals) const
Check whether parameters to a call that are passed in callee saved registers are the same as from the calling function.
bool findOptimalMemOpLowering (std::vector< EVT > &MemOps, unsigned Limit, uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, bool AllowOverlap, unsigned DstAS, unsigned SrcAS, const AttributeList &FuncAttributes) const
Determines the optimal series of memory ops to replace the memset / memcpy.
bool ShrinkDemandedConstant (SDValue Op, const APInt &Demanded, TargetLoweringOpt &TLO) const
Check to see if the specified operand of the specified instruction is a constant integer.
virtual bool targetShrinkDemandedConstant (SDValue Op, const APInt &Demanded, TargetLoweringOpt &TLO) const
bool ShrinkDemandedOp (SDValue Op, unsigned BitWidth, const APInt &Demanded, TargetLoweringOpt &TLO) const
Convert x+y to (VT)((SmallVT)x+(SmallVT)y) if the casts are free.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Op.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Helper wrapper around SimplifyDemandedBits, demanding all elements.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedMask, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedBits.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedEltMask, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Vector Op.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedVectorElts.
virtual void computeKnownBitsForTargetInstr (GISelKnownBits &Analysis, Register R, KnownBits &Known, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
virtual void computeKnownBitsForFrameIndex (const SDValue FIOp, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const
Determine which of the bits of FrameIndex FIOp are known to be 0.
virtual bool SimplifyDemandedVectorEltsForTargetNode (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded vector elements, returning true on success.
virtual bool SimplifyDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded bits/elts, returning true on success.
virtual SDValue SimplifyMultipleUseDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
SDValue buildLegalVectorShuffle (EVT VT, const SDLoc &DL, SDValue N0, SDValue N1, MutableArrayRef< int > Mask, SelectionDAG &DAG) const
Tries to build a legal vector shuffle using the provided parameters or equivalent variations.
virtual const Constant * getTargetConstantFromLoad (LoadSDNode *LD) const
This method returns the constant pool value that will be loaded by LD.
bool isConstTrueVal (const SDNode *N) const
Return if the N is a constant or constant vector equal to the true value from getBooleanContents().
bool isConstFalseVal (const SDNode *N) const
Return if the N is a constant or constant vector equal to the false value from getBooleanContents().
bool isExtendedTrueVal (const ConstantSDNode *N, EVT VT, bool SExt) const
Return if N is a True value when extended to VT.
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, const SDLoc &dl) const
Try to simplify a setcc built with the specified operands and cc.
virtual SDValue unwrapAddress (SDValue N) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
virtual bool isDesirableToCommuteWithShift (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to move this shift by a constant amount though its operand, adjusting any immediate operands as necessary to preserve semantics.
virtual bool isDesirableToCombineBuildVectorToShuffleTruncate (ArrayRef< int > ShuffleMask, EVT SrcVT, EVT TruncVT) const
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
Return true if it is profitable for dag combiner to transform a floating point op of specified opcode to a equivalent op of an integer type.
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
This method query the target whether it is beneficial for dag combiner to promote the specified node.
virtual bool supportSwiftError () const
Return true if the target supports swifterror attribute.
virtual bool supportSplitCSR (MachineFunction *MF) const
Return true if the target supports that a subset of CSRs for the given machine function is handled explicitly via copies.
virtual void initializeSplitCSR (MachineBasicBlock *Entry) const
Perform necessary initialization to handle a subset of CSRs explicitly via copies.
virtual void insertCopiesSplitCSR (MachineBasicBlock *Entry, const SmallVectorImpl< MachineBasicBlock *> &Exits) const
Insert explicit copies in entry and exit blocks.
virtual char isNegatibleForFree (SDValue Op, SelectionDAG &DAG, bool LegalOperations, bool ForCodeSize, unsigned Depth=0) const
Return 1 if we can compute the negated form of the specified expression for the same cost as the expression itself, or 2 if we can compute the negated form more cheaply than the expression itself.
virtual SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOperations, bool ForCodeSize, unsigned Depth=0) const
If isNegatibleForFree returns true, return the newly negated expression.
virtual SDValue LowerFormalArguments (SDValue, CallingConv::ID, bool, const SmallVectorImpl< ISD::InputArg > &, const SDLoc &, SelectionDAG &, SmallVectorImpl< SDValue > &) const
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
This function lowers an abstract call to a function into an actual call.
virtual void HandleByVal (CCState *, unsigned &, unsigned) const
Target-specific cleanup for formal ByVal parameters.
virtual bool CanLowerReturn (CallingConv::ID, MachineFunction &, bool, const SmallVectorImpl< ISD::OutputArg > &, LLVMContext &) const
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers.
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
Return true if result of the specified node is used by a return node only.
virtual bool mayBeEmittedAsTailCall (const CallInst *) const
Return true if the target may be able emit the call instruction as a tail call.
virtual const char * getClearCacheBuiltinName () const
Return the builtin name for the __builtin___clear_cache intrinsic Default is to invoke the clear cache library call.
virtual Register getRegisterByName (const char *RegName, LLT Ty, const MachineFunction &MF) const
Return the register ID of the name passed in.
virtual EVT getTypeForExtReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
Return the type that should be used to zero or sign extend a zeroext/signext integer return value.
virtual bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg) const
For some targets, an LLVM struct type must be broken down into multiple simple types, but the calling convention specifies that the entire struct must be passed in a block of consecutive registers.
virtual bool shouldSplitFunctionArgumentsAsLittleEndian (const DataLayout &DL) const
For most targets, an LLVM type must be broken down into multiple smaller types.
virtual const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const
Returns a 0 terminated array of registers that can be safely used as scratch registers.
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, const SDLoc &DL, SelectionDAG &DAG) const
This callback is used to prepare for a volatile or atomic load.
virtual MachineMemOperand::Flags getMMOFlags (const Instruction &I) const
This callback is used to inspect load/store instructions and add target-specific MachineMemOperand flags to them.
virtual bool lowerAtomicStoreAsStoreSDNode (const StoreInst &SI) const
Should SelectionDAG lower an atomic store of the given kind as a normal StoreSDNode (as opposed to an AtomicSDNode)? NOTE: The intention is to eventually migrate all targets to the using StoreSDNodes, but porting is being done target at a time.
virtual bool lowerAtomicLoadAsLoadSDNode (const LoadInst &LI) const
Should SelectionDAG lower an atomic load of the given kind as a normal LoadSDNode (as opposed to an AtomicSDNode)? NOTE: The intention is to eventually migrate all targets to the using LoadSDNodes, but porting is being done target at a time.
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types.
virtual FastISel * createFastISel (FunctionLoweringInfo &, const TargetLibraryInfo *) const
This method returns a target specific FastISel object, or null if the target does not support "fast" ISel.
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to.
virtual AsmOperandInfoVector ParseConstraints (const DataLayout &DL, const TargetRegisterInfo *TRI, ImmutableCallSite CS) const
Split up the constraint string from the inline assembly value into the specific constraints and their prefixes, and also tie in the associated operand values.
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
Examine constraint type and operand type and determine a weight value.
virtual ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const
Examine constraint string and operand type and determine a weight value.
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
Determines the constraint code and constraint type to use for the specific AsmOperandInfo, setting OpInfo.ConstraintCode and OpInfo.ConstraintType.
virtual ConstraintType getConstraintType (StringRef Constraint) const
Given a constraint, return the type of constraint it is for this target.
virtual std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, StringRef Constraint, MVT VT) const
Given a physical register constraint (e.g.
virtual unsigned getInlineAsmMemConstraint (StringRef ConstraintCode) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
virtual void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const
Lower the specified operand into the Ops vector.
virtual SDValue LowerAsmOutputForConstraint (SDValue &Chain, SDValue &Flag, SDLoc DL, const AsmOperandInfo &OpInfo, SelectionDAG &DAG) const
SDValue BuildSDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode *> &Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
SDValue BuildUDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode *> &Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
virtual SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode *> &Created) const
Targets may override this function to provide custom SDIV lowering for power-of-2 denominators.
virtual unsigned combineRepeatedFPDivisors () const
Indicate whether this target prefers to combine FDIVs with the same divisor.
bool expandMUL_LOHI (unsigned Opcode, EVT VT, SDLoc dl, SDValue LHS, SDValue RHS, SmallVectorImpl< SDValue > &Result, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL or [US]MUL_LOHI of n-bit values into two or four nodes, respectively, each computing an n/2-bit part of the result.
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL into two nodes.
bool expandFunnelShift (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand funnel shift.
bool expandROT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand rotations.
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand float(f32) to SINT(i64) conversion.
bool expandFP_TO_UINT (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand float to UINT conversion.
bool expandUINT_TO_FP (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand UINT(i64) to double(f64) conversion.
SDValue expandFMINNUM_FMAXNUM (SDNode *N, SelectionDAG &DAG) const
Expand fminnum/fmaxnum into fminnum_ieee/fmaxnum_ieee with quieted inputs.
bool expandCTPOP (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTPOP nodes.
bool expandCTLZ (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTLZ/CTLZ_ZERO_UNDEF nodes.
bool expandCTTZ (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTTZ/CTTZ_ZERO_UNDEF nodes.
bool expandABS (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand ABS nodes.
std::pair< SDValue, SDValue > scalarizeVectorLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Turn load of vector type into a load of the individual elements.
SDValue scalarizeVectorStore (StoreSDNode *ST, SelectionDAG &DAG) const
std::pair< SDValue, SDValue > expandUnalignedLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Expands an unaligned load to 2 half-size loads for an integer, and possibly more for vectors.
SDValue expandUnalignedStore (StoreSDNode *ST, SelectionDAG &DAG) const
Expands an unaligned store to 2 half-size stores for integer values, and possibly more for vectors.
SDValue IncrementMemoryAddress (SDValue Addr, SDValue Mask, const SDLoc &DL, EVT DataVT, SelectionDAG &DAG, bool IsCompressedMemory) const
Increments memory address Addr according to the type of the value DataVT that should be stored.
SDValue getVectorElementPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, SDValue Index) const
Get a pointer to vector element Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue expandAddSubSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][ADD|SUB]SAT.
SDValue expandFixedPointMul (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[U|S]MULFIX[SAT].
SDValue expandFixedPointDiv (unsigned Opcode, const SDLoc &dl, SDValue LHS, SDValue RHS, unsigned Scale, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]DIVFIX.
void expandUADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::U(ADD|SUB)O.
void expandSADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::S(ADD|SUB)O.
bool expandMULO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]MULO.
SDValue expandVecReduce (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_* into an explicit calculation.
virtual MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr &MI, MachineBasicBlock *MBB) const
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
virtual void AdjustInstrPostInstrSelection (MachineInstr &MI, SDNode *Node) const
This method should be implemented by targets that mark instructions with the 'hasPostISelHook' flag.
virtual bool useLoadStackGuardNode () const
If this function returns true, SelectionDAGBuilder emits a LOAD_STACK_GUARD node when it is lowering Intrinsic::stackprotector.
virtual SDValue emitStackGuardXorFP (SelectionDAG &DAG, SDValue Val, const SDLoc &DL) const
virtual SDValue LowerToTLSEmulatedModel (const GlobalAddressSDNode *GA, SelectionDAG &DAG) const
Lower TLS global address SDNode for target independent emulated TLS model.
virtual SDValue expandIndirectJTBranch (const SDLoc &dl, SDValue Value, SDValue Addr, SelectionDAG &DAG) const
Expands target specific indirect branch for the case of JumpTable expanasion.
SDValue lowerCmpEqZeroToCtlzSrl (SDValue Op, SelectionDAG &DAG) const
Public Member Functions inherited from llvm::TargetLoweringBase
virtual void markLibCallAttributes (MachineFunction *MF, unsigned CC, ArgListTy &Args) const
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
TargetLoweringBase (const TargetLoweringBase &)=delete
TargetLoweringBase & operator= (const TargetLoweringBase &)=delete
virtual ~TargetLoweringBase ()=default
bool isStrictFPEnabled () const
Return true if the target support strict float operation.
const TargetMachine & getTargetMachine () const
virtual bool useSoftFloat () const
virtual MVT getPointerTy (const DataLayout &DL, uint32_t AS=0) const
Return the pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getPointerMemTy (const DataLayout &DL, uint32_t AS=0) const
Return the in-memory pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getFrameIndexTy (const DataLayout &DL) const
Return the type for frame index, which is determined by the alloca address space specified through the data layout.
virtual MVT getScalarShiftAmountTy (const DataLayout &, EVT) const
EVT is not used in-tree, but is used by out-of-tree target.
EVT getShiftAmountTy (EVT LHSTy, const DataLayout &DL, bool LegalTypes=true) const
virtual bool reduceSelectOfFPConstantLoads (EVT CmpOpVT) const
Return true if it is profitable to convert a select of FP constants into a constant pool load whose address depends on the select condition.
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (MVT VT) const
Return the preferred vector type legalization action.
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
virtual bool isIntDivCheap (EVT VT, AttributeList Attr) const
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
virtual bool hasStandaloneRem (EVT VT) const
Return true if the target can handle a standalone remainder operation.
int getRecipEstimateSqrtEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a square root of the given type based on the function's attributes.
int getRecipEstimateDivEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a division of the given type based on the function's attributes.
int getSqrtRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a square root of the given type based on the function's attributes.
int getDivRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a division of the given type based on the function's attributes.
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
Returns map of slow types for division or remainder with corresponding fast types.
bool isJumpExpensive () const
Return true if Flow Control is an expensive operation that should be avoided.
bool isPredictableSelectExpensive () const
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
virtual BranchProbability getPredictableBranchThreshold () const
If a branch or a select condition is skewed in one direction by more than this factor, it is very likely to be predicted correctly.
virtual bool isStoreBitCastBeneficial (EVT StoreVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: (store (y (conv x)), y*)) -> (store x, (x*))
virtual bool canMergeStoresTo (unsigned AS, EVT MemVT, const SelectionDAG &DAG) const
Returns if it's reasonable to merge stores to MemVT size.
virtual bool isCtlzFast () const
Return true if ctlz instruction is fast.
virtual bool isEqualityCmpFoldedWithSignedCmp () const
Return true if instruction generated for equality comparison is folded with instruction generated for signed comparison.
virtual bool hasBitPreservingFPLogic (EVT VT) const
Return true if it is safe to transform an integer-domain bitwise operation into the equivalent floating-point operation.
virtual bool isMultiStoresCheaperThanBitsMerge (EVT LTy, EVT HTy) const
Return true if it is cheaper to split the store of a merged int val from a pair of smaller values into multiple stores.
virtual bool isMaskAndCmp0FoldingBeneficial (const Instruction &AndI) const
Return if the target supports combining a chain like:
virtual bool convertSetCCLogicToBitwiseLogic (EVT VT) const
Use bitwise logic to make pairs of compares more efficient.
virtual MVT hasFastEqualityCompare (unsigned NumBits) const
Return the preferred operand type if the target has a quick way to compare integer values of the given size.
virtual bool hasAndNotCompare (SDValue Y) const
Return true if the target should transform: (X & Y) == Y —> (~X & Y) == 0 (X & Y) != Y —> (~X & Y) != 0.
virtual bool hasAndNot (SDValue X) const
Return true if the target has a bitwise and-not operation: X = ~A & B This can be used to simplify select or other instructions.
virtual bool hasBitTest (SDValue X, SDValue Y) const
Return true if the target has a bit-test instruction: (X & (1 << Y)) ==/!= 0 This knowledge can be used to prevent breaking the pattern, or creating it if it could be recognized.
virtual bool shouldFoldMaskToVariableShiftPair (SDValue X) const
There are two ways to clear extreme bits (either low or high): Mask: x & (-1 << y) (the instcombine canonical form) Shifts: x >> y << y Return true if the variant with 2 variable shifts is preferred.
virtual bool shouldFoldConstantShiftPairToMask (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to fold a pair of shifts into a mask.
virtual bool shouldTransformSignedTruncationCheck (EVT XVT, unsigned KeptBits) const
Should we tranform the IR-optimal check for whether given truncation down into KeptBits would be truncating or not: (add x, (1 << (KeptBits-1))) srccond (1 << KeptBits) Into it's more traditional form: ((x << C) a>> C) dstcond x Return true if we should transform.
virtual bool shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd (SDValue X, ConstantSDNode *XC, ConstantSDNode *CC, SDValue Y, unsigned OldShiftOpcode, unsigned NewShiftOpcode, SelectionDAG &DAG) const
Given the pattern (X & (C l>>/<< Y)) ==/!= 0 return true if it should be transformed into: ((X <</l>> Y) & C) ==/!= 0 WARNING: if 'X' is a constant, the fold may deadlock! FIXME: we could avoid passing XC, but we can't use isConstOrConstSplat() here because it can end up being not linked in.
virtual bool preferIncOfAddToSubOfNot (EVT VT) const
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
Return true if the target can combine store(extractelement VectorTy, Idx).
virtual bool shouldSplatInsEltVarIndex (EVT) const
Return true if inserting a scalar into a variable element of an undef vector is more efficiently handled by splatting the scalar instead.
virtual bool enableAggressiveFMAFusion (EVT VT) const
Return true if target always beneficiates from combining into FMA for a given value type.
virtual EVT getSetCCResultType (const DataLayout &DL, LLVMContext &Context, EVT VT) const
Return the ValueType of the result of SETCC operations.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
Return the ValueType for comparison libcalls.
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
Some scheduler, e.g.
virtual const TargetRegisterClass * getRegClassFor (MVT VT, bool isDivergent=false) const
Return the register class that should be used for the specified value type.
virtual bool requiresUniformRegister (MachineFunction &MF, const Value *) const
Allows target to decide about the register class of the specific value that is live outside the defining block.
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
Return the 'representative' register class for the specified value type.
virtual uint8_t getRepRegClassCostFor (MVT VT) const
Return the cost of the 'representative' register class for the specified value type.
virtual bool shouldExpandShift (SelectionDAG &DAG, SDNode *N) const
Return true if SHIFT instructions should be expanded to SHIFT_PARTS instructions, and false if a library call is preferred (e.g for code-size reasons).
bool isTypeLegal (EVT VT) const
Return true if the target has native support for the specified value type.
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand').
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Vector types are broken down into some number of legal first class types.
virtual unsigned getVectorTypeBreakdownForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, MachineFunction &, unsigned) const
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
virtual bool isShuffleMaskLegal (ArrayRef< int >, EVT) const
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
virtual bool canOpTrap (unsigned Op, EVT VT) const
Returns true if the operation can trap for the value type.
virtual bool isVectorClearMaskLegal (ArrayRef< int >, EVT) const
Similar to isShuffleMaskLegal.
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
virtual bool isSupportedFixedPointOperation (unsigned Op, EVT VT, unsigned Scale) const
Custom method defined by each target to indicate if an operation which may require a scale is supported natively by the target.
LegalizeAction getFixedPointOperationAction (unsigned Op, EVT VT, unsigned Scale) const
Some fixed point operations may be natively supported by the target but only for specific scales.
LegalizeAction getStrictFPOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering.
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal using promotion.
bool isOperationLegalOrCustomOrPromote (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering or using promotion.
bool isOperationCustom (unsigned Op, EVT VT) const
Return true if the operation uses custom lowering, regardless of whether the type is legal or not.
virtual bool areJTsAllowed (const Function *Fn) const
Return true if lowering to a jump table is allowed.
bool rangeFitsInWord (const APInt &Low, const APInt &High, const DataLayout &DL) const
Check whether the range [Low,High] fits in a machine word.
virtual bool isSuitableForJumpTable (const SwitchInst *SI, uint64_t NumCases, uint64_t Range, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
Return true if lowering to a jump table is suitable for a set of case clusters which may contain NumCases cases, Range range of values.
bool isSuitableForBitTests (unsigned NumDests, unsigned NumCmps, const APInt &Low, const APInt &High, const DataLayout &DL) const
Return true if lowering to a bit test is suitable for a set of case clusters which contains NumDests unique destinations, Low and High as its lowest and highest case values, and expects NumCmps case value comparisons.
bool isOperationExpand (unsigned Op, EVT VT) const
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering.
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
bool isLoadExtLegalOrCustom (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal or custom on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation is legal on this target.
bool isTruncStoreLegalOrCustom (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation has solution on this target.
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
bool isCondCodeLegalOrCustom (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal or custom on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
If the action for this operation is to promote, this method returns the ValueType to promote to.
EVT getValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the EVT corresponding to this LLVM type.
EVT getMemValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty, const DataLayout &DL) const
Return the desired alignment for ByVal or InAlloca aggregate function arguments in the caller parameter area.
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
Return the number of registers that this ValueType will eventually require.
virtual MVT getRegisterTypeForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
virtual unsigned getNumRegistersForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain targets require unusual breakdowns of certain types.
virtual Align getABIAlignmentForCallingConv (Type *ArgTy, DataLayout DL) const
Certain targets have context senstive alignment requirements, where one type has the alignment requirement of another type.
bool hasBigEndianPartOrdering (EVT VT, const DataLayout &DL) const
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
bool hasTargetDAGCombine (ISD::NodeType NT) const
If true, the target has custom DAG combine transformations that it can perform for the specified node.
unsigned getGatherAllAliasesMaxDepth () const
virtual unsigned getVaListSizeInBits (const DataLayout &DL) const
Returns the size of the platform's va_list object.
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
virtual unsigned getMaxGluedStoresPerMemcpy () const
Get maximum # of store operations to be glued together.
unsigned getMaxExpandSizeMemcmp (bool OptSize) const
Get maximum # of load operations permitted for memcmp.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (EVT, unsigned AddrSpace=0, unsigned Align=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *=nullptr) const
Determine if the target supports unaligned memory accesses.
virtual bool allowsMisalignedMemoryAccesses (LLT, unsigned AddrSpace=0, unsigned Align=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *=nullptr) const
LLT handling variant.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, unsigned Alignment=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *Fast=nullptr) const
This function returns true if the memory access is aligned or if the target allows this specific unaligned memory access.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, bool *Fast=nullptr) const
Return true if the memory access of this type is aligned or if the target allows this specific unaligned access for the given MachineMemOperand.
virtual bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, unsigned Alignment=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given address space and alignment.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given MachineMemOperand.
virtual EVT getOptimalMemOpType (uint64_t, unsigned, unsigned, bool, bool, bool, const AttributeList &) const
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
virtual LLT getOptimalMemOpLLT (uint64_t, unsigned, unsigned, bool, bool, bool, const AttributeList &) const
LLT returning variant.
virtual bool isSafeMemOpType (MVT) const
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
virtual unsigned getMinimumJumpTableEntries () const
Return lower limit for number of blocks in a jump table.
unsigned getMinimumJumpTableDensity (bool OptForSize) const
Return lower limit of the density in a jump table.
unsigned getMaximumJumpTableSize () const
Return upper limit for number of entries in a jump table.
virtual bool isJumpTableRelative () const
unsigned getStackPointerRegisterToSaveRestore () const
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
virtual unsigned getExceptionPointerRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
virtual unsigned getExceptionSelectorRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
virtual bool needsFixedCatchObjects () const
Align getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
Align getMinFunctionAlignment () const
Return the minimum function alignment.
Align getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual Align getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
virtual bool alignLoopsWithOptSize () const
Should loops be aligned even when the function is marked OptSize (but not MinSize).
virtual Value * getIRStackGuard (IRBuilder<> &IRB) const
If the target has a standard location for the stack protector guard, returns the address of that location.
virtual void insertSSPDeclarations (Module &M) const
Inserts necessary declarations for SSP (stack protection) purpose.
virtual Value * getSDagStackGuard (const Module &M) const
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
virtual bool useStackGuardXorFP () const
If this function returns true, stack protection checks should XOR the frame pointer (or whichever pointer is used to address locals) into the stack guard value before checking it.
virtual Function * getSSPStackGuardCheck (const Module &M) const
If the target has a standard stack protection check function that performs validation and error handling, returns the function.
virtual Value * getSafeStackPointerLocation (IRBuilder<> &IRB) const
Returns the target-specific address of the unsafe stack pointer.
virtual StringRef getStackProbeSymbolName (MachineFunction &MF) const
Returns the name of the symbol used to emit stack probes or the empty string if not applicable.
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual bool isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
virtual bool shouldAlignPointerArgs (CallInst *, unsigned &, unsigned &) const
Return true if the pointer arguments to CI should be aligned by aligning the object whose address is being passed.
virtual void emitAtomicCmpXchgNoStoreLLBalance (IRBuilder<> &Builder) const
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
Returns true if the given (atomic) store should be expanded by the IR-level AtomicExpand pass into an "atomic xchg" which ignores its input.
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
virtual bool shouldExtendTypeInLibCall (EVT Type) const
Returns true if arguments should be extended in lib calls.
virtual AtomicExpansionKind shouldExpandAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst *AI) const
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load.
virtual ISD::NodeType getExtendForAtomicOps () const
Returns how the platform's atomic operations are extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual bool shouldNormalizeToSelectSequence (LLVMContext &Context, EVT VT) const
Returns true if we should normalize select(N0&N1, X, Y) => select(N0, select(N1, X, Y), Y) and select(N0|N1, X, Y) => select(N0, select(N1, X, Y, Y)) if it is likely that it saves us from materializing N0 and N1 in an integer register.
virtual bool isProfitableToCombineMinNumMaxNum (EVT VT) const
virtual bool convertSelectOfConstantsToMath (EVT VT) const
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
virtual bool decomposeMulByConstant (LLVMContext &Context, EVT VT, SDValue C) const
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
virtual bool shouldUseStrictFP_TO_INT (EVT FpVT, EVT IntVT, bool IsSigned) const
Return true if it is more correct/profitable to use strict FP_TO_INT conversion operations - canonicalizing the FP source value instead of converting all cases and then selecting based on value.
virtual bool getAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value *> &, Type *&) const
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
virtual bool isLegalAddressingMode (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AddrSpace, Instruction *I=nullptr) const
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
virtual int getScalingFactorCost (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AS=0) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
virtual bool isLegalAddImmediate (int64_t) const
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
virtual bool isLegalStoreImmediate (int64_t Value) const
Return true if the specified immediate is legal for the value input of a store instruction.
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
virtual bool isCommutativeBinOp (unsigned Opcode) const
Returns true if the opcode is a commutative binary operation.
virtual bool isBinOp (unsigned Opcode) const
Return true if the node is a math/logic binary operator.
virtual bool allowTruncateForTailCall (Type *FromTy, Type *ToTy) const
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
virtual bool isProfitableToHoist (Instruction *I) const
bool isExtFree (const Instruction *I) const
Return true if the extension represented by I is free.
bool isExtLoad (const LoadInst *Load, const Instruction *Ext, const DataLayout &DL) const
Return true if Load and Ext can form an ExtLoad.
virtual bool isSExtCheaperThanZExt (EVT FromTy, EVT ToTy) const
Return true if sign-extension from FromTy to ToTy is cheaper than zero-extension.
virtual bool shouldSinkOperands (Instruction *I, SmallVectorImpl< Use *> &Ops) const
Return true if sinking I's operands to the same basic block as I is profitable, e.g.
virtual bool hasPairedLoad (EVT, unsigned &) const
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory.
virtual bool hasVectorBlend () const
Return true if the target has a vector blend instruction.
virtual unsigned getMaxSupportedInterleaveFactor () const
Get the maximum supported factor for interleaved memory accesses.
virtual bool lowerInterleavedLoad (LoadInst *LI, ArrayRef< ShuffleVectorInst *> Shuffles, ArrayRef< unsigned > Indices, unsigned Factor) const
Lower an interleaved load to target specific intrinsics.
virtual bool lowerInterleavedStore (StoreInst *SI, ShuffleVectorInst *SVI, unsigned Factor) const
Lower an interleaved store to target specific intrinsics.
virtual bool isFPExtFree (EVT DestVT, EVT SrcVT) const
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
virtual bool isFPExtFoldable (const SelectionDAG &DAG, unsigned Opcode, EVT DestVT, EVT SrcVT) const
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
virtual bool isVectorLoadExtDesirable (SDValue ExtVal) const
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
virtual bool isFMAFasterThanFMulAndFAdd (const MachineFunction &MF, EVT) const
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
virtual bool isFMAFasterThanFMulAndFAdd (const Function &F, Type *) const
IR version.
virtual bool isFMADLegalForFAddFSub (const SelectionDAG &DAG, const SDNode *N) const
Returns true if the FADD or FSUB node passed could legally be combined with an fmul to form an ISD::FMAD.
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself.
virtual bool isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
virtual bool shouldScalarizeBinop (SDValue VecOp) const
Try to convert an extract element of a vector binary operation into an extract element followed by a scalar operation.
virtual bool isExtractVecEltCheap (EVT VT, unsigned Index) const
Return true if extraction of a scalar element from the given vector type at the given index is cheap.
virtual bool shouldFormOverflowOp (unsigned Opcode, EVT VT) const
Try to convert math with an overflow comparison into the corresponding DAG node operation.
virtual bool shouldConsiderGEPOffsetSplit () const
virtual bool shouldAvoidTransformToShift (EVT VT, unsigned Amount) const
Return true if creating a shift of the type by the given amount is not profitable.
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
Override the default CondCode to be used to test the result of the comparison libcall against zero.
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
virtual void finalizeLowering (MachineFunction &MF) const
Execute target specific actions to finalize target lowering.
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< int, MVT > getTypeLegalizationCost (const DataLayout &DL, Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
unsigned getMaxAtomicSizeInBitsSupported () const
Returns the maximum atomic operation size (in bits) supported by the backend.
unsigned getMinCmpXchgSizeInBits () const
Returns the size of the smallest cmpxchg or ll/sc instruction the backend supports.
bool supportsUnalignedAtomics () const
Whether the target supports unaligned atomic operations.
virtual bool shouldInsertFencesForAtomic (const Instruction *I) const
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
Perform a store-conditional operation to Addr.
virtual Value * emitMaskedAtomicRMWIntrinsic (IRBuilder<> &Builder, AtomicRMWInst *AI, Value *AlignedAddr, Value *Incr, Value *Mask, Value *ShiftAmt, AtomicOrdering Ord) const
Perform a masked atomicrmw using a target-specific intrinsic.
virtual Value * emitMaskedAtomicCmpXchgIntrinsic (IRBuilder<> &Builder, AtomicCmpXchgInst *CI, Value *AlignedAddr, Value *CmpVal, Value *NewVal, Value *Mask, AtomicOrdering Ord) const
Perform a masked cmpxchg using a target-specific intrinsic.
virtual Instruction * emitLeadingFence (IRBuilder<> &Builder, Instruction *Inst, AtomicOrdering Ord) const
Inserts in the IR a target-specific intrinsic specifying a fence.
virtual Instruction * emitTrailingFence (IRBuilder<> &Builder, Instruction *Inst, AtomicOrdering Ord) const
Static Public Member Functions
static unsigned numBitsUnsigned (SDValue Op, SelectionDAG &DAG)
static unsigned numBitsSigned (SDValue Op, SelectionDAG &DAG)
static bool hasDefinedInitializer (const GlobalValue *GV)
static SDValue stripBitcast (SDValue Val)
static bool allUsesHaveSourceMods (const SDNode *N, unsigned CostThreshold=4)
static CCAssignFn * CCAssignFnForCall (CallingConv::ID CC, bool IsVarArg)
Selects the correct CCAssignFn for a given CallingConvention value.
static CCAssignFn * CCAssignFnForReturn (CallingConv::ID CC, bool IsVarArg)
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions
SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFREM (SDValue Op, SelectionDAG &DAG) const
Split a vector store into multiple scalar stores.
SDValue LowerFCEIL (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFTRUNC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFRINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFNEARBYINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFROUND_LegalFTRUNC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFROUND64 (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFROUND (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFFLOOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFLOG (SDValue Op, SelectionDAG &DAG, double Log2BaseInverted) const
SDValue lowerFEXP (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCTLZ_CTTZ (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINT_TO_FP32 (SDValue Op, SelectionDAG &DAG, bool Signed) const
SDValue LowerINT_TO_FP64 (SDValue Op, SelectionDAG &DAG, bool Signed) const
SDValue LowerUINT_TO_FP (SDValue Op, SelectionDAG &DAG) const
SDValue LowerSINT_TO_FP (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFP64_TO_INT (SDValue Op, SelectionDAG &DAG, bool Signed) const
SDValue LowerFP_TO_FP16 (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFP_TO_UINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFP_TO_SINT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerSIGN_EXTEND_INREG (SDValue Op, SelectionDAG &DAG) const
bool shouldCombineMemoryType (EVT VT) const
SDValue performLoadCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performStoreCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performAssertSZExtCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performIntrinsicWOChainCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue splitBinaryBitConstantOpImpl (DAGCombinerInfo &DCI, const SDLoc &SL, unsigned Opc, SDValue LHS, uint32_t ValLo, uint32_t ValHi) const
Split the 64-bit value LHS into two 32-bit components, and perform the binary operation Opc to it with the corresponding constant operands.
SDValue performShlCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performSraCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performSrlCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performTruncateCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulhsCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulhuCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performMulLoHi24Combine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performCtlz_CttzCombine (const SDLoc &SL, SDValue Cond, SDValue LHS, SDValue RHS, DAGCombinerInfo &DCI) const
SDValue performSelectCombine (SDNode *N, DAGCombinerInfo &DCI) const
bool isConstantCostlierToNegate (SDValue N) const
SDValue performFNegCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performFAbsCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue performRcpCombine (SDNode *N, DAGCombinerInfo &DCI) const
virtual SDValue LowerGlobalAddress (AMDGPUMachineFunction *MFI, SDValue Op, SelectionDAG &DAG) const
std::pair< SDValue, SDValue > split64BitValue (SDValue Op, SelectionDAG &DAG) const
Return 64-bit value Op as two 32-bit integers.
SDValue getLoHalf64 (SDValue Op, SelectionDAG &DAG) const
SDValue getHiHalf64 (SDValue Op, SelectionDAG &DAG) const
std::pair< EVT, EVT > getSplitDestVTs (const EVT &VT, SelectionDAG &DAG) const
Split a vector type into two parts.
std::pair< SDValue, SDValue > splitVector (const SDValue &N, const SDLoc &DL, const EVT &LoVT, const EVT &HighVT, SelectionDAG &DAG) const
Split a vector value into two parts of types LoVT and HiVT.
SDValue SplitVectorLoad (SDValue Op, SelectionDAG &DAG) const
Split a vector load into 2 loads of half the vector.
SDValue WidenVectorLoad (SDValue Op, SelectionDAG &DAG) const
Widen a vector load from vec3 to vec4.
SDValue SplitVectorStore (SDValue Op, SelectionDAG &DAG) const
Split a vector store into 2 stores of half the vector.
SDValue LowerSTORE (SDValue Op, SelectionDAG &DAG) const
SDValue LowerSDIVREM (SDValue Op, SelectionDAG &DAG) const
SDValue LowerUDIVREM (SDValue Op, SelectionDAG &DAG) const
SDValue LowerDIVREM24 (SDValue Op, SelectionDAG &DAG, bool sign) const
void LowerUDIVREM64 (SDValue Op, SelectionDAG &DAG, SmallVectorImpl< SDValue > &Results) const
void analyzeFormalArgumentsCompute (CCState &State, const SmallVectorImpl< ISD::InputArg > &Ins) const
The SelectionDAGBuilder will automatically promote function arguments with illegal types.
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
Value * getDefaultSafeStackPointerLocation (IRBuilder<> &IRB, bool UseTLS) const
void setBooleanContents (BooleanContent Ty)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanVectorContents (BooleanContent Ty)
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type.
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setMinimumJumpTableEntries (unsigned Val)
Indicate the minimum number of blocks to generate jump tables.
void setMaximumJumpTableSize (unsigned)
Indicate the maximum number of entries in jump tables.
void setStackPointerRegisterToSaveRestore (unsigned R)
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches.
void setHasExtractBitsInsn (bool hasExtractInsn=true)
Tells the code generator that the target has BitExtract instructions.
void setJumpIsExpensive (bool isExpensive=true)
Tells the code generator not to expand logic operations on comparison predicates into separate sequences that increase the amount of flow control.
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
Add the specified register class as an available regclass for the specified value type.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (const TargetRegisterInfo *TRI, MVT VT) const
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
void computeRegisterProperties (const TargetRegisterInfo *TRI)
Once all of the register classes are added, this allows us to compute derived properties we expose.
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked load does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked store does or does not work with the specified type and indicate what to do about it.
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works.
void setOperationPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
Convenience method to set an operation to Promote and specify the type in a single call.
void setTargetDAGCombine (ISD::NodeType NT)
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
void setMinFunctionAlignment (Align Alignment)
Set the target's minimum function alignment.
void setPrefFunctionAlignment (Align Alignment)
Set the target's preferred function alignment.
void setPrefLoopAlignment (Align Alignment)
Set the target's preferred loop alignment.
void setMinStackArgumentAlignment (Align Alignment)
Set the minimum stack alignment of an argument.
void setMaxAtomicSizeInBitsSupported (unsigned SizeInBits)
Set the maximum atomic operation size supported by the backend.
void setMinCmpXchgSizeInBits (unsigned SizeInBits)
Sets the minimum cmpxchg or ll/sc size supported by the backend.
void setSupportsUnalignedAtomics (bool UnalignedSupported)
Sets whether unaligned atomic operations are supported.
virtual bool isExtFreeImpl (const Instruction *I) const
Return true if the extension represented by I is free.
bool isLegalRC (const TargetRegisterInfo &TRI, const TargetRegisterClass &RC) const
Return true if the value types that can be represented by the specified register class are all legal.
MachineBasicBlock * emitPatchPoint (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
MachineBasicBlock * emitXRayCustomEvent (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify the XRay custom event operands with target-dependent details.
MachineBasicBlock * emitXRayTypedEvent (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify the XRay typed event operands with target-dependent details.
Static Protected Member Functions
static EVT getEquivalentMemType (LLVMContext &Context, EVT VT)
Additional Inherited Members
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned GatherAllAliasesMaxDepth
Depth that GatherAllAliases should should continue looking for chain dependencies when trying to find a more preferable chain.
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemcpy
Specify maximum number of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxGluedStoresPerMemcpy = 0
Specify max number of store instructions to glue in inlined memcpy.
unsigned MaxLoadsPerMemcmp
Specify maximum number of load instructions per memcmp call.
unsigned MaxLoadsPerMemcmpOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemmove
Specify maximum number of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
Likewise for functions with the OptSize attribute.
bool PredictableSelectIsExpensive
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
bool EnableExtLdPromotion
bool IsStrictFPEnabled
Detailed Description
Definition at line 28 of file AMDGPUISelLowering.h.
Member Enumeration Documentation
ImplicitParameter
enum llvm::AMDGPUTargetLowering::ImplicitParameter
Enumerator
FIRST_IMPLICIT
GRID_DIM
GRID_OFFSET
Definition at line 313 of file AMDGPUISelLowering.h.
Constructor & Destructor Documentation
AMDGPUTargetLowering()
AMDGPUTargetLowering::AMDGPUTargetLowering (const TargetMachine & TM, const AMDGPUSubtarget & STI)
Definition at line 65 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::TargetLoweringBase::AddPromotedToType(), llvm::ISD::AND, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::ISD::BR_JT, llvm::ISD::BRIND, llvm::ISD::BSWAP, llvm::ISD::CONCAT_VECTORS, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::ISD::DYNAMIC_STACKALLOC, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP16_TO_FP, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FPOW, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::TargetLoweringBase::GatherAllAliasesMaxDepth, I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MVT::integer_fixedlen_vector_valuetypes(), llvm::MVT::integer_valuetypes(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLoweringBase::Legal, LLVM_READNONE, llvm::ISD::LOAD, llvm::TargetLoweringBase::MaxStoresPerMemcpy, llvm::TargetLoweringBase::MaxStoresPerMemmove, llvm::TargetLoweringBase::MaxStoresPerMemset, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::OR, llvm::MVT::Other, llvm::TargetLoweringBase::PredictableSelectIsExpensive, llvm::TargetLoweringBase::Promote, llvm::Sched::RegPressure, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::TargetLoweringBase::setHasMultipleConditionRegisters(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMinCmpXchgSizeInBits(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setSupportsUnalignedAtomics(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMUL_LOHI, llvm::ISD::UREM, llvm::MVT::v16f16, llvm::MVT::v16f32, llvm::MVT::v16i32, llvm::MVT::v2f16, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32f16, llvm::MVT::v32f32, llvm::MVT::v32i32, llvm::MVT::v3f16, llvm::MVT::v3f32, llvm::MVT::v3i16, llvm::MVT::v3i32, llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i8, llvm::MVT::v5f32, llvm::MVT::v5i32, llvm::MVT::v8f16, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i32, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
addTokenForArgument()
SDValue AMDGPUTargetLowering::addTokenForArgument (SDValue Chain, SelectionDAG & DAG, MachineFrameInfo & MFI, int ClobberedFI) const
Definition at line 1043 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::getEntryNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::TokenFactor, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by llvm::SITargetLowering::LowerCall(), and stripBitcast().
aggressivelyPreferBuildVectorSources()
bool AMDGPUTargetLowering::aggressivelyPreferBuildVectorSources (EVT VecVT) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 761 of file AMDGPUISelLowering.cpp.
Referenced by stripBitcast().
allUsesHaveSourceMods()
bool AMDGPUTargetLowering::allUsesHaveSourceMods (const SDNode * N, unsigned CostThreshold = 4) static
Definition at line 588 of file AMDGPUISelLowering.cpp.
References llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::SDNode::getValueType(), hasSourceMods(), opMustUseVOP3Encoding(), and llvm::SDNode::uses().
Referenced by isClampZeroToOne(), performFNegCombine(), and stripBitcast().
analyzeFormalArgumentsCompute()
void AMDGPUTargetLowering::analyzeFormalArgumentsCompute (CCState & State, const SmallVectorImpl< ISD::InputArg > & Ins) const protected
The SelectionDAGBuilder will automatically promote function arguments with illegal types.
However, this does not work for the AMDGPU targets since the function arguments are stored in memory as these illegal types. In order to handle this properly we need to get the original types sizes from the LLVM IR Function and fixup the ISD:InputArg values before passing them to AnalyzeFormalArguments() When the SelectionDAGBuilder computes the Ins, it takes care of splitting input values across multiple registers. Each item in the Ins array represents a single value that will be stored in registers. Ins[x].VT is the value type of the value that will be stored in the register, so whatever SDNode we lower the argument to needs to be this type.
In order to correctly lower the arguments we need to know the size of each argument. Since Ins[x].VT gives us the size of the register that will hold the value, we need to look at Ins[x].ArgVT to see the 'real' type for the orignal function argument so that we can deduce the correct memory type to use for Ins[x]. In most cases the correct memory type will be Ins[x].ArgVT. However, this will not always be the case. If, for example, we have a kernel argument of type v8i8, this argument will be split into 8 parts and each part will be represented by its own item in the Ins array. For each part the Ins[x].ArgVT will be the v8i8, which is the full type of the argument before it was split. From this, we deduce that the memory type for each individual part is i8. We pass the memory type as LocVT to the calling convention analysis function and the register type (Ins[x].VT) as the ValVT.
Definition at line 905 of file AMDGPUISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::alignTo(), Arg, llvm::Function::args(), assert(), llvm::ComputeValueVTs(), llvm::CCValAssign::Full, llvm::AMDGPUSubtarget::get(), llvm::DataLayout::getABITypeAlignment(), llvm::Function::getCallingConv(), llvm::Module::getContext(), llvm::CCState::getContext(), llvm::CCValAssign::getCustomMem(), llvm::Module::getDataLayout(), llvm::AMDGPUSubtarget::getExplicitKernelArgOffset(), llvm::MachineFunction::getFunction(), llvm::EVT::getIntegerVT(), llvm::CCState::getMachineFunction(), llvm::TargetLoweringBase::getNumRegistersForCallingConv(), llvm::GlobalValue::getParent(), llvm::EVT::getPow2VectorType(), llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::EVT::getScalarType(), llvm::MVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::EVT::getStoreSize(), llvm::EVT::getStoreSizeInBits(), llvm::DataLayout::getTypeAllocSize(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::EVT::isExtended(), llvm::MVT::isFloatingPoint(), llvm::MVT::isInteger(), llvm::EVT::isPow2VectorType(), llvm::EVT::isVector(), llvm::MVT::isVector(), llvm_unreachable, llvm::max(), llvm::SmallVectorBase::size(), and llvm::ARM_MB::ST.
Referenced by llvm::R600TargetLowering::LowerFormalArguments(), and llvm::SITargetLowering::LowerFormalArguments().
CCAssignFnForCall()
CCAssignFn * AMDGPUTargetLowering::CCAssignFnForCall (CallingConv::ID CC, bool IsVarArg) static
Selects the correct CCAssignFn for a given CallingConvention value.
Definition at line 1033 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUCallLowering::CCAssignFnForCall().
Referenced by llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::SITargetLowering::LowerCall(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), and stripBitcast().
CCAssignFnForReturn()
CCAssignFn * AMDGPUTargetLowering::CCAssignFnForReturn (CallingConv::ID CC, bool IsVarArg) static
Definition at line 1038 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUCallLowering::CCAssignFnForReturn().
Referenced by llvm::SITargetLowering::CanLowerReturn(), llvm::SITargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerReturn(), stripBitcast(), and unpackRegsToOrigType().
combineFMinMaxLegacy()
SDValue AMDGPUTargetLowering::combineFMinMaxLegacy (const SDLoc & DL, EVT VT, SDValue LHS, SDValue RHS, SDValue True, SDValue False, SDValue CC, DAGCombinerInfo & DCI) const
Generate Min/Max node.
Definition at line 1256 of file AMDGPUISelLowering.cpp.
References llvm::AfterLegalizeDAG, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::AMDGPUISD::FMAX_LEGACY, llvm::AMDGPUISD::FMIN_LEGACY, llvm::TargetLowering::DAGCombinerInfo::getDAGCombineLevel(), llvm::SelectionDAG::getNode(), llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer(), llvm_unreachable, llvm::ISD::SETCC_INVALID, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
Referenced by llvm::R600TargetLowering::ReplaceNodeResults(), and stripBitcast().
computeKnownBitsForTargetNode()
void AMDGPUTargetLowering::computeKnownBitsForTargetNode (const SDValue Op, KnownBits & Known, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth = 0) const override virtual
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero and KnownOne bitsets.
Reimplemented from llvm::TargetLowering.
Definition at line 4424 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUISD::BFE_I32, llvm::AMDGPUISD::BFE_U32, llvm::AMDGPUISD::BORROW, llvm::AMDGPUISD::BUFFER_LOAD_UBYTE, llvm::AMDGPUISD::BUFFER_LOAD_USHORT, llvm::AMDGPUISD::CARRY, llvm::SelectionDAG::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::KnownBits::countMinSignBits(), llvm::KnownBits::countMinTrailingZeros(), llvm::dyn_cast(), llvm::AMDGPUISD::FP16_ZEXT, llvm::AMDGPUISD::FP_TO_FP16, llvm::KnownBits::getBitWidth(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::SDValue::getValueType(), llvm::GCNSubtarget::getWavefrontSizeLog2(), llvm::ConstantSDNode::getZExtValue(), llvm::APInt::getZExtValue(), I, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm::KnownBits::isStrictlyPositive(), llvm::AMDGPUISD::LDS, llvm::Log2_32(), llvm::AMDGPUISD::MUL_I24, llvm::AMDGPUISD::MUL_U24, llvm::KnownBits::One, llvm::AMDGPUISD::PERM, llvm::KnownBits::resetAll(), llvm::APInt::setHighBits(), llvm::APInt::setLowBits(), Size, llvm::ARM_MB::ST, llvm::KnownBits::trunc(), and llvm::KnownBits::Zero.
Referenced by isFsqrtCheap().
ComputeNumSignBitsForTargetNode()
unsigned AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode (SDValue Op, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth = 0) const override virtual
This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
The DemandedElts argument allows us to only collect the minimum sign bits that are shared by the requested vector elements.
Reimplemented from llvm::TargetLowering.
Definition at line 4568 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUISD::BFE_I32, llvm::AMDGPUISD::BFE_U32, llvm::AMDGPUISD::BORROW, llvm::AMDGPUISD::BUFFER_LOAD_BYTE, llvm::AMDGPUISD::BUFFER_LOAD_SHORT, llvm::AMDGPUISD::BUFFER_LOAD_UBYTE, llvm::AMDGPUISD::BUFFER_LOAD_USHORT, llvm::AMDGPUISD::CARRY, llvm::SelectionDAG::ComputeNumSignBits(), llvm::dyn_cast(), llvm::AMDGPUISD::FP16_ZEXT, llvm::AMDGPUISD::FP_TO_FP16, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ConstantSDNode::getZExtValue(), llvm::isNullConstant(), and llvm::max().
Referenced by isFsqrtCheap().
CreateLiveInRegister() [1/2]
SDValue AMDGPUTargetLowering::CreateLiveInRegister (SelectionDAG & DAG, const TargetRegisterClass * RC, unsigned Reg, EVT VT, const SDLoc & SL, bool RawReg = false) const
Helper function that adds Reg to the LiveIn list of the DAG's MachineFunction.
Returns
a RegisterSDNode representing Reg if RawReg is true, otherwise a copy from the register.
Definition at line 4118 of file AMDGPUISelLowering.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineRegisterInfo::getLiveInVirtReg(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), llvm::MachineRegisterInfo::isLiveIn(), and MRI.
Referenced by CreateLiveInRegister(), CreateLiveInRegisterRaw(), isFsqrtCheap(), llvm::SITargetLowering::isTypeDesirableForOp(), loadInputValue(), llvm::SITargetLowering::LowerCall(), llvm::SITargetLowering::LowerReturn(), and llvm::SITargetLowering::shouldEmitPCReloc().
CreateLiveInRegister() [2/2]
SDValue llvm::AMDGPUTargetLowering::CreateLiveInRegister (SelectionDAG & DAG, const TargetRegisterClass * RC, unsigned Reg, EVT VT) const inline
Definition at line 282 of file AMDGPUISelLowering.h.
References CreateLiveInRegister(), and llvm::SelectionDAG::getEntryNode().
CreateLiveInRegisterRaw()
SDValue llvm::AMDGPUTargetLowering::CreateLiveInRegisterRaw (SelectionDAG & DAG, const TargetRegisterClass * RC, unsigned Reg, EVT VT) const inline
Definition at line 289 of file AMDGPUISelLowering.h.
References Arg, CreateLiveInRegister(), llvm::SelectionDAG::getEntryNode(), loadInputValue(), loadStackInputValue(), and storeStackInputValue().
Referenced by llvm::R600TargetLowering::LowerOperation().
getEquivalentMemType()
EVT AMDGPUTargetLowering::getEquivalentMemType (LLVMContext & Context, EVT VT) static protected
Definition at line 42 of file AMDGPUISelLowering.cpp.
References assert(), llvm::EVT::getIntegerVT(), llvm::EVT::getStoreSizeInBits(), llvm::EVT::getVectorVT(), and llvm::MVT::i32.
Referenced by adjustLoadValueTypeImpl(), getBufferOffsetForMMO(), isClampZeroToOne(), performLoadCombine(), performStoreCombine(), and llvm::SITargetLowering::ReplaceNodeResults().
getFenceOperandTy()
MVT llvm::AMDGPUTargetLowering::getFenceOperandTy (const DataLayout & DL) const inline override virtual
Return the type for operands of fence.
TODO: Let fence operands be of i32 type and remove this.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 324 of file AMDGPUISelLowering.h.
References llvm::MVT::i32, and shouldExpandAtomicRMWInIR().
getHiHalf64()
SDValue AMDGPUTargetLowering::getHiHalf64 (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 1352 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, and llvm::MVT::v2i32.
Referenced by performSraCombine().
getImplicitParameterOffset()
uint32_t AMDGPUTargetLowering::getImplicitParameterOffset (const MachineFunction & MF, const ImplicitParameter Param) const
Helper function that returns the byte offset of the given type of implicit parameter.
Definition at line 4205 of file AMDGPUISelLowering.cpp.
References llvm::alignTo(), llvm::AMDGPUSubtarget::get(), llvm::AMDGPUMachineFunction::getExplicitKernArgSize(), llvm::AMDGPUSubtarget::getExplicitKernelArgOffset(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetLoweringBase::getTargetMachine(), GRID_DIM, GRID_OFFSET, llvm_unreachable, and llvm::ARM_MB::ST.
Referenced by llvm::SITargetLowering::isTypeDesirableForOp(), and llvm::R600TargetLowering::LowerOperation().
getLoHalf64()
SDValue AMDGPUTargetLowering::getLoHalf64 (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 1344 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, and llvm::MVT::v2i32.
getRecipEstimate()
SDValue AMDGPUTargetLowering::getRecipEstimate (SDValue Operand, SelectionDAG & DAG, int Enabled, int & RefinementSteps) const override virtual
Return a reciprocal estimate value for the input operand.
Enabled is a ReciprocalEstimate enum with value either 'Unspecified' or 'Enabled' as set by a potential default override attribute. If RefinementSteps is 'Unspecified', the number of Newton-Raphson refinement iterations required to generate a sufficient (though not necessarily IEEE-754 compliant) estimate is returned in that parameter. A target may choose to implement its own refinement within this function. If that's true, then return '0' as the number of RefinementSteps to avoid any further refinement of the estimate. An empty SDValue return means no estimate sequence can be created.
Reimplemented from llvm::TargetLowering.
Definition at line 4403 of file AMDGPUISelLowering.cpp.
References llvm::MVT::f32, llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), and llvm::AMDGPUISD::RCP.
Referenced by isFsqrtCheap().
getSplitDestVTs()
std::pair< EVT, EVT > AMDGPUTargetLowering::getSplitDestVTs (const EVT & VT, SelectionDAG & DAG) const protected
Split a vector type into two parts.
The first part is a power of two vector. The second part is whatever is left over, and is a scalar if it would otherwise be a 1-vector.
Definition at line 1364 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::getContext(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), and llvm::PowerOf2Ceil().
Referenced by SplitVectorLoad(), and SplitVectorStore().
getSqrtEstimate()
SDValue AMDGPUTargetLowering::getSqrtEstimate (SDValue Operand, SelectionDAG & DAG, int Enabled, int & RefinementSteps, bool & UseOneConstNR, bool Reciprocal) const override virtual
Hooks for building estimates in place of slower divisions and square roots.
Return either a square root or its reciprocal estimate value for the input operand. Enabled is a ReciprocalEstimate enum with value either 'Unspecified' or 'Enabled' as set by a potential default override attribute. If RefinementSteps is 'Unspecified', the number of Newton-Raphson refinement iterations required to generate a sufficient (though not necessarily IEEE-754 compliant) estimate is returned in that parameter. The boolean UseOneConstNR output is used to select a Newton-Raphson algorithm implementation that uses either one or two constants. The boolean Reciprocal is used to select whether the estimate is for the square root of the input operand or the reciprocal of its square root. A target may choose to implement its own refinement within this function. If that's true, then return '0' as the number of RefinementSteps to avoid any further refinement of the estimate. An empty SDValue return means no estimate sequence can be created.
Reimplemented from llvm::TargetLowering.
Definition at line 4385 of file AMDGPUISelLowering.cpp.
References llvm::MVT::f32, llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), and llvm::AMDGPUISD::RSQ.
Referenced by isFsqrtCheap().
getTargetNodeName()
const char * AMDGPUTargetLowering::getTargetNodeName (unsigned Opcode) const override virtual
This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 4225 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::AMDGPUISD::ATOMIC_DEC, llvm::AMDGPUISD::ATOMIC_INC, llvm::AMDGPUISD::ATOMIC_LOAD_FMAX, llvm::AMDGPUISD::ATOMIC_LOAD_FMIN, llvm::AMDGPUISD::ATOMIC_PK_FADD, llvm::AMDGPUISD::BFE_I32, llvm::AMDGPUISD::BFE_U32, llvm::AMDGPUISD::BFI, llvm::AMDGPUISD::BFM, llvm::AMDGPUISD::BORROW, llvm::AMDGPUISD::BRANCH_COND, llvm::AMDGPUISD::BUFFER_ATOMIC_ADD, llvm::AMDGPUISD::BUFFER_ATOMIC_AND, llvm::AMDGPUISD::BUFFER_ATOMIC_CMPSWAP, llvm::AMDGPUISD::BUFFER_ATOMIC_DEC, llvm::AMDGPUISD::BUFFER_ATOMIC_FADD, llvm::AMDGPUISD::BUFFER_ATOMIC_INC, llvm::AMDGPUISD::BUFFER_ATOMIC_OR, llvm::AMDGPUISD::BUFFER_ATOMIC_PK_FADD, llvm::AMDGPUISD::BUFFER_ATOMIC_SMAX, llvm::AMDGPUISD::BUFFER_ATOMIC_SMIN, llvm::AMDGPUISD::BUFFER_ATOMIC_SUB, llvm::AMDGPUISD::BUFFER_ATOMIC_SWAP, llvm::AMDGPUISD::BUFFER_ATOMIC_UMAX, llvm::AMDGPUISD::BUFFER_ATOMIC_UMIN, llvm::AMDGPUISD::BUFFER_ATOMIC_XOR, llvm::AMDGPUISD::BUFFER_LOAD, llvm::AMDGPUISD::BUFFER_LOAD_BYTE, llvm::AMDGPUISD::BUFFER_LOAD_FORMAT, llvm::AMDGPUISD::BUFFER_LOAD_FORMAT_D16, llvm::AMDGPUISD::BUFFER_LOAD_SHORT, llvm::AMDGPUISD::BUFFER_LOAD_UBYTE, llvm::AMDGPUISD::BUFFER_LOAD_USHORT, llvm::AMDGPUISD::BUFFER_STORE, llvm::AMDGPUISD::BUFFER_STORE_BYTE, llvm::AMDGPUISD::BUFFER_STORE_FORMAT, llvm::AMDGPUISD::BUFFER_STORE_FORMAT_D16, llvm::AMDGPUISD::BUFFER_STORE_SHORT, llvm::AMDGPUISD::BUILD_VERTICAL_VECTOR, llvm::AArch64ISD::CALL, llvm::AMDGPUISD::CARRY, llvm::AMDGPUISD::CLAMP, llvm::AMDGPUISD::CONST_ADDRESS, llvm::AMDGPUISD::CONST_DATA_PTR, llvm::AMDGPUISD::COS_HW, llvm::AMDGPUISD::CVT_F32_UBYTE0, llvm::AMDGPUISD::CVT_F32_UBYTE1, llvm::AMDGPUISD::CVT_F32_UBYTE2, llvm::AMDGPUISD::CVT_F32_UBYTE3, llvm::AMDGPUISD::CVT_PK_I16_I32, llvm::AMDGPUISD::CVT_PK_U16_U32, llvm::AMDGPUISD::CVT_PKNORM_I16_F32, llvm::AMDGPUISD::CVT_PKNORM_U16_F32, llvm::AMDGPUISD::CVT_PKRTZ_F16_F32, llvm::AMDGPUISD::DENORM_MODE, llvm::AMDGPUISD::DIV_FIXUP, llvm::AMDGPUISD::DIV_FMAS, llvm::AMDGPUISD::DIV_SCALE, llvm::AMDGPUISD::DOT4, llvm::AMDGPUISD::DS_ORDERED_COUNT, llvm::AMDGPUISD::DUMMY_CHAIN, llvm::AMDGPUISD::DWORDADDR, llvm::AMDGPUISD::ELSE, llvm::AMDGPUISD::ENDPGM, llvm::AMDGPUISD::EXPORT, llvm::AMDGPUISD::EXPORT_DONE, llvm::AMDGPUISD::FDOT2, llvm::AMDGPUISD::FFBH_I32, llvm::AMDGPUISD::FFBH_U32, llvm::AMDGPUISD::FFBL_B32, llvm::AMDGPUISD::FIRST_MEM_OPCODE_NUMBER, llvm::AMDGPUISD::FIRST_NUMBER, llvm::AMDGPUISD::FMA_W_CHAIN, llvm::AMDGPUISD::FMAD_FTZ, llvm::AMDGPUISD::FMAX3, llvm::AMDGPUISD::FMAX_LEGACY, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN3, llvm::AMDGPUISD::FMIN_LEGACY, llvm::AMDGPUISD::FMUL_LEGACY, llvm::AMDGPUISD::FMUL_W_CHAIN, llvm::AMDGPUISD::FP16_ZEXT, llvm::AMDGPUISD::FP_CLASS, llvm::ISD::FP_TO_FP16, llvm::AMDGPUISD::FRACT, llvm::AMDGPUISD::IF, llvm::AMDGPUISD::INTERP_P1LL_F16, llvm::AMDGPUISD::INTERP_P1LV_F16, llvm::AMDGPUISD::INTERP_P2_F16, llvm::AMDGPUISD::KILL, llvm::AMDGPUISD::LAST_AMDGPU_ISD_NUMBER, llvm::AMDGPUISD::LDEXP, llvm::AMDGPUISD::LDS, llvm::AMDGPUISD::LOAD_CONSTANT, llvm::AMDGPUISD::LOAD_D16_HI, llvm::AMDGPUISD::LOAD_D16_HI_I8, llvm::AMDGPUISD::LOAD_D16_HI_U8, llvm::AMDGPUISD::LOAD_D16_LO, llvm::AMDGPUISD::LOAD_D16_LO_I8, llvm::AMDGPUISD::LOAD_D16_LO_U8, llvm::AMDGPUISD::LOOP, llvm::AMDGPUISD::MAD_I24, llvm::AMDGPUISD::MAD_I64_I32, llvm::AMDGPUISD::MAD_U24, llvm::AMDGPUISD::MAD_U64_U32, llvm::AMDGPUISD::MUL_I24, llvm::AMDGPUISD::MUL_LOHI_I24, llvm::AMDGPUISD::MUL_LOHI_U24, llvm::AMDGPUISD::MUL_U24, llvm::AMDGPUISD::MULHI_I24, llvm::AMDGPUISD::MULHI_U24, NODE_NAME_CASE, llvm::AMDGPUISD::PC_ADD_REL_OFFSET, llvm::AMDGPUISD::PERM, llvm::AMDGPUISD::R600_EXPORT, llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_IFLAG, llvm::AMDGPUISD::RCP_LEGACY, llvm::AMDGPUISD::REGISTER_LOAD, llvm::AMDGPUISD::REGISTER_STORE, llvm::AArch64ISD::RET_FLAG, llvm::AMDGPUISD::RETURN_TO_EPILOG, llvm::AMDGPUISD::RSQ, llvm::AMDGPUISD::RSQ_CLAMP, llvm::AMDGPUISD::RSQ_LEGACY, llvm::AMDGPUISD::SAMPLE, llvm::AMDGPUISD::SAMPLEB, llvm::AMDGPUISD::SAMPLED, llvm::AMDGPUISD::SAMPLEL, llvm::AMDGPUISD::SBUFFER_LOAD, llvm::ISD::SETCC, llvm::AMDGPUISD::SETREG, llvm::AMDGPUISD::SIN_HW, llvm::AMDGPUISD::SMAX3, llvm::AMDGPUISD::SMED3, llvm::AMDGPUISD::SMIN3, llvm::AMDGPUISD::STORE_MSKOR, llvm::AMDGPUISD::TBUFFER_LOAD_FORMAT, llvm::AMDGPUISD::TBUFFER_LOAD_FORMAT_D16, llvm::AMDGPUISD::TBUFFER_STORE_FORMAT, llvm::AMDGPUISD::TBUFFER_STORE_FORMAT_D16, llvm::AArch64ISD::TC_RETURN, llvm::AMDGPUISD::TEXTURE_FETCH, llvm::ISD::TRAP, llvm::AMDGPUISD::TRIG_PREOP, llvm::AMDGPUISD::UMAX3, llvm::AMDGPUISD::UMED3, llvm::AMDGPUISD::UMIN3, llvm::AMDGPUISD::UMUL, and llvm::AMDGPUISD::URECIP.
Referenced by stripBitcast().
getVectorIdxTy()
MVT AMDGPUTargetLowering::getVectorIdxTy (const DataLayout & DL) const override virtual
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 612 of file AMDGPUISelLowering.cpp.
References llvm::MVT::i32.
Referenced by getBufferOffsetForMMO(), parseTexFail(), llvm::R600TargetLowering::ReplaceNodeResults(), splitVector(), SplitVectorLoad(), stripBitcast(), and WidenVectorLoad().
hasDefinedInitializer()
bool AMDGPUTargetLowering::hasDefinedInitializer (const GlobalValue * GV) static
Definition at line 1180 of file AMDGPUISelLowering.cpp.
References llvm::dyn_cast(), llvm::GlobalVariable::getInitializer(), and llvm::GlobalVariable::hasInitializer().
Referenced by llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), and LowerGlobalAddress().
isCheapToSpeculateCtlz()
bool AMDGPUTargetLowering::isCheapToSpeculateCtlz () const override virtual
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 702 of file AMDGPUISelLowering.cpp.
Referenced by stripBitcast().
isCheapToSpeculateCttz()
bool AMDGPUTargetLowering::isCheapToSpeculateCttz () const override virtual
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 698 of file AMDGPUISelLowering.cpp.
Referenced by stripBitcast().
isConstantCostlierToNegate()
bool AMDGPUTargetLowering::isConstantCostlierToNegate (SDValue N) const protected
Definition at line 3632 of file AMDGPUISelLowering.cpp.
References C, llvm::AMDGPUSubtarget::hasInv2PiInlineImm(), llvm::isConstOrConstSplatFP(), and isInv2Pi().
Referenced by performFNegCombine().
isFAbsFree()
bool AMDGPUTargetLowering::isFAbsFree (EVT VT) const override virtual
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 740 of file AMDGPUISelLowering.cpp.
References assert(), llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::AMDGPUSubtarget::has16BitInsts(), and llvm::EVT::isFloatingPoint().
Referenced by stripBitcast().
isFNegFree()
bool AMDGPUTargetLowering::isFNegFree (EVT VT) const override virtual
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 748 of file AMDGPUISelLowering.cpp.
References assert(), llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::AMDGPUSubtarget::has16BitInsts(), llvm::AMDGPUSubtarget::hasVOP3PInsts(), llvm::EVT::isFloatingPoint(), and llvm::MVT::v2f16.
Referenced by stripBitcast().
isFPImmLegal()
bool AMDGPUTargetLowering::isFPImmLegal (const APFloat & , EVT , bool ForCodeSize) const override virtual
Returns true if the target can instruction select the specified FP immediate natively.
If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 622 of file AMDGPUISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getScalarType(), and llvm::AMDGPUSubtarget::has16BitInsts().
Referenced by stripBitcast().
isFsqrtCheap()
bool llvm::AMDGPUTargetLowering::isFsqrtCheap (SDValue X, SelectionDAG & DAG) const inline override virtual
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 242 of file AMDGPUISelLowering.h.
References computeKnownBitsForTargetNode(), ComputeNumSignBitsForTargetNode(), CreateLiveInRegister(), llvm::Depth, llvm::TargetLoweringBase::Enabled, getRecipEstimate(), getSqrtEstimate(), isKnownNeverNaNForTargetNode(), PostISelFolding(), and Reg.
isKnownNeverNaNForTargetNode()
bool AMDGPUTargetLowering::isKnownNeverNaNForTargetNode (SDValue Op, const SelectionDAG & DAG, bool SNaN = false, unsigned Depth = 0) const override virtual
If SNaN is false,.
Returns
true if Op is known to never be any NaN. If sNaN is true, returns if Op is known to never be a signaling NaN.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::SITargetLowering.
Definition at line 4610 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUISD::COS_HW, llvm::AMDGPUISD::CVT_F32_UBYTE0, llvm::AMDGPUISD::CVT_F32_UBYTE1, llvm::AMDGPUISD::CVT_F32_UBYTE2, llvm::AMDGPUISD::CVT_F32_UBYTE3, llvm::AMDGPUISD::CVT_PKRTZ_F16_F32, llvm::AMDGPUISD::DIV_FIXUP, llvm::AMDGPUISD::DIV_FMAS, llvm::AMDGPUISD::DIV_SCALE, llvm::AMDGPUISD::FMAD_FTZ, llvm::AMDGPUISD::FMAX3, llvm::AMDGPUISD::FMAX_LEGACY, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN3, llvm::AMDGPUISD::FMIN_LEGACY, llvm::AMDGPUISD::FMUL_LEGACY, llvm::AMDGPUISD::FRACT, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::SelectionDAG::isKnownNeverNaN(), llvm::AMDGPUISD::LDEXP, llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_LEGACY, llvm::AMDGPUISD::RSQ, llvm::AMDGPUISD::RSQ_CLAMP, llvm::AMDGPUISD::RSQ_LEGACY, llvm::AMDGPUISD::SIN_HW, and llvm::AMDGPUISD::TRIG_PREOP.
Referenced by isFsqrtCheap(), and llvm::SITargetLowering::isKnownNeverNaNForTargetNode().
isLoadBitCastBeneficial()
bool AMDGPUTargetLowering::isLoadBitCastBeneficial (EVT LoadVT, EVT BitcastVT, const SelectionDAG & DAG, const MachineMemOperand & MMO) const final virtual
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 673 of file AMDGPUISelLowering.cpp.
References llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), assert(), llvm::CallingConv::Fast, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), and llvm::MVT::i32.
Referenced by stripBitcast().
isNarrowingProfitable()
bool AMDGPUTargetLowering::isNarrowingProfitable (EVT , EVT) const override virtual
Return true if it's profitable to narrow operations of type VT1 to VT2.
e.g. on x86, it's profitable to narrow from i32 to i8 but not from i32 to i16.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 820 of file AMDGPUISelLowering.cpp.
References llvm::EVT::getSizeInBits().
Referenced by stripBitcast().
isSDNodeAlwaysUniform()
bool AMDGPUTargetLowering::isSDNodeAlwaysUniform (const SDNode * N) const override virtual
Reimplemented from llvm::TargetLowering.
Definition at line 706 of file AMDGPUISelLowering.cpp.
References AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::ISD::EntryToken, getAddrSpace(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::LOAD, and llvm::ISD::TokenFactor.
Referenced by stripBitcast().
isSelectSupported()
bool AMDGPUTargetLowering::isSelectSupported (SelectSupportKind SelType) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 616 of file AMDGPUISelLowering.cpp.
Referenced by stripBitcast().
isTruncateFree() [1/2]
bool AMDGPUTargetLowering::isTruncateFree (EVT Src, EVT Dest) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 773 of file AMDGPUISelLowering.cpp.
References llvm::EVT::getSizeInBits().
Referenced by stripBitcast().
isTruncateFree() [2/2]
bool AMDGPUTargetLowering::isTruncateFree (Type * FromTy, Type * ToTy) const override virtual
Return true if it's free to truncate a value of type FromTy to type ToTy.
e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX. Targets must return false when FromTy <= ToTy.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 782 of file AMDGPUISelLowering.cpp.
References llvm::Type::getScalarSizeInBits(), and llvm::AMDGPUSubtarget::has16BitInsts().
isZExtFree() [1/3]
bool AMDGPUTargetLowering::isZExtFree (Type * FromTy, Type * ToTy) const override virtual
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
The function should return true when it is likely that the truncate can be freely folded with an instruction defining a value of FromTy. If the defining instruction is unknown (because you're looking at a function argument, PHI, etc.) then the target may require an explicit truncate, which is not necessarily free, but this function does not deal with those cases. Targets must return false when FromTy >= ToTy.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 794 of file AMDGPUISelLowering.cpp.
References llvm::Type::getScalarSizeInBits(), and llvm::AMDGPUSubtarget::has16BitInsts().
Referenced by isZExtFree(), and stripBitcast().
isZExtFree() [2/3]
bool AMDGPUTargetLowering::isZExtFree (EVT Src, EVT Dest) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 804 of file AMDGPUISelLowering.cpp.
References llvm::MVT::i16, llvm::MVT::i32, and llvm::MVT::i64.
isZExtFree() [3/3]
bool AMDGPUTargetLowering::isZExtFree (SDValue Val, EVT VT2) const override virtual
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 816 of file AMDGPUISelLowering.cpp.
References llvm::SDValue::getValueType(), and isZExtFree().
loadInputValue()
SDValue AMDGPUTargetLowering::loadInputValue (SelectionDAG & DAG, const TargetRegisterClass * RC, EVT VT, const SDLoc & SL, const ArgDescriptor & Arg) const
Definition at line 4184 of file AMDGPUISelLowering.cpp.
References llvm::ISD::AND, assert(), CreateLiveInRegister(), llvm::SelectionDAG::getConstant(), llvm::ArgDescriptor::getMask(), llvm::SelectionDAG::getNode(), llvm::ArgDescriptor::getRegister(), llvm::SelectionDAG::getShiftAmountConstant(), llvm::ArgDescriptor::getStackOffset(), llvm::ArgDescriptor::isMasked(), llvm::ArgDescriptor::isRegister(), loadStackInputValue(), llvm::BitmaskEnumDetail::Mask(), and llvm::ISD::SRL.
Referenced by CreateLiveInRegisterRaw(), parseTexFail(), and llvm::SITargetLowering::passSpecialInputs().
loadStackInputValue()
SDValue AMDGPUTargetLowering::loadStackInputValue (SelectionDAG & DAG, EVT VT, const SDLoc & SL, int64_t Offset) const
Similar to CreateLiveInRegister, except value maybe loaded from a stack slot rather than passed in a register.
Definition at line 4154 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), getOrCreateFixedStackObject(), llvm::MachinePointerInfo::getStack(), llvm::EVT::getStoreSize(), llvm::MVT::i32, llvm::MachineMemOperand::MODereferenceable, and llvm::MachineMemOperand::MOInvariant.
Referenced by CreateLiveInRegisterRaw(), and loadInputValue().
LowerCall()
SDValue AMDGPUTargetLowering::LowerCall (CallLoweringInfo & , SmallVectorImpl< SDValue > &) const override virtual
This hook must be implemented to lower calls into the specified DAG.
The outgoing arguments to the call are described by the Outs array, and the values to be returned by the call are described by the Ins array. The implementation should fill in the InVals array with legal-type return values from the call, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::SITargetLowering.
Definition at line 1106 of file AMDGPUISelLowering.cpp.
References lowerUnhandledCall().
Referenced by stripBitcast().
LowerCONCAT_VECTORS()
SDValue AMDGPUTargetLowering::LowerCONCAT_VECTORS (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 1223 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::ISD::BITCAST, llvm::SelectionDAG::ExtractVectorElements(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MipsISD::Lo, llvm::SDNode::ops(), llvm::MVT::v2i32, llvm::MVT::v4f16, and llvm::MVT::v4i16.
Referenced by LowerOperation().
LowerCTLZ_CTTZ()
SDValue AMDGPUTargetLowering::LowerCTLZ_CTTZ (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2322 of file AMDGPUISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::BITCAST, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::AMDGPUISD::FFBH_U32, llvm::AMDGPUISD::FFBL_B32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SDValue::getValueType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, isCtlzOpc(), isCttzOpc(), llvm_unreachable, llvm::MipsISD::Lo, llvm::ISD::SELECT, llvm::ISD::SETEQ, llvm::MVT::v2i32, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerOperation().
LowerDIVREM24()
SDValue AMDGPUTargetLowering::LowerDIVREM24 (SDValue Op, SelectionDAG & DAG, bool sign) const protected
Definition at line 1526 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::SelectionDAG::ComputeNumSignBits(), llvm::MVT::f32, llvm::ISD::FABS, llvm::ISD::FMAD, llvm::AMDGPUISD::FMAD_FTZ, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::AMDGPU::SIModeRegisterDefaults::FP32Denormals, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FTRUNC, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getInfo(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMergeValues(), llvm::AMDGPUMachineFunction::getMode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::MVT::i32, llvm::ARM_AM::ia, llvm::ARM_AM::ib, llvm::ISD::MUL, llvm::ISD::OR, llvm::AMDGPUISD::RCP, llvm::ISD::SELECT, llvm::ISD::SETOGE, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SRA, llvm::ISD::SUB, llvm::ISD::UINT_TO_FP, and llvm::ISD::XOR.
Referenced by LowerSDIVREM(), and LowerUDIVREM().
LowerDYNAMIC_STACKALLOC()
SDValue AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG & DAG) const
Definition at line 1111 of file AMDGPUISelLowering.cpp.
References llvm::LLVMContext::diagnose(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getOperand(), and llvm::SDValue::getValueType().
Referenced by LowerOperation(), and stripBitcast().
LowerEXTRACT_SUBVECTOR()
SDValue AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 1243 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
Referenced by LowerOperation().
LowerFCEIL()
SDValue AMDGPUTargetLowering::LowerFCEIL (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2039 of file AMDGPUISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::AND, llvm::MVT::f64, llvm::ISD::FADD, llvm::ISD::FTRUNC, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::ISD::SELECT, llvm::ISD::SETOGT, and llvm::ISD::SETONE.
Referenced by LowerOperation().
lowerFEXP()
SDValue AMDGPUTargetLowering::lowerFEXP (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2304 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FEXP2, llvm::ISD::FMUL, llvm::SelectionDAG::getConstantFP(), llvm::SDNode::getFlags(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), and llvm::numbers::log2e.
Referenced by LowerOperation().
LowerFFLOOR()
SDValue AMDGPUTargetLowering::LowerFFLOOR (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2266 of file AMDGPUISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::AND, llvm::MVT::f64, llvm::ISD::FADD, llvm::ISD::FTRUNC, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::ISD::SELECT, llvm::ISD::SETOLT, and llvm::ISD::SETONE.
Referenced by LowerOperation().
LowerFLOG()
SDValue AMDGPUTargetLowering::LowerFLOG (SDValue Op, SelectionDAG & DAG, double Log2BaseInverted) const protected
Definition at line 2291 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FLOG2, llvm::ISD::FMUL, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), and llvm::SDValue::getValueType().
Referenced by LowerOperation().
LowerFNEARBYINT()
SDValue AMDGPUTargetLowering::LowerFNEARBYINT (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2155 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FRINT, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), and llvm::SDValue::getValueType().
Referenced by LowerOperation().
LowerFP64_TO_INT()
SDValue AMDGPUTargetLowering::LowerFP64_TO_INT (SDValue Op, SelectionDAG & DAG, bool Signed) const protected
Definition at line 2581 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::BitsToDouble(), llvm::MVT::f64, llvm::ISD::FFLOOR, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FTRUNC, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::MipsISD::Lo, and llvm::MVT::v2i32.
Referenced by LowerFP_TO_SINT(), and LowerFP_TO_UINT().
LowerFP_TO_FP16()
SDValue AMDGPUTargetLowering::LowerFP_TO_FP16 (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2610 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), B, llvm::ISD::BITCAST, D, E, llvm::MVT::f32, llvm::MVT::f64, llvm::AMDGPUISD::FP_TO_FP16, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSelectCC(), llvm::SDValue::getSimpleValueType(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), I, llvm::MVT::i32, llvm::MVT::i64, N, llvm::TargetMachine::Options, llvm::ISD::OR, llvm::ISD::SETEQ, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SHL, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SRL, llvm::ISD::SUB, and llvm::TargetOptions::UnsafeFPMath.
Referenced by LowerOperation().
LowerFP_TO_SINT()
SDValue AMDGPUTargetLowering::LowerFP_TO_SINT (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2709 of file AMDGPUISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FP_EXTEND, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::MVT::i64, and LowerFP64_TO_INT().
Referenced by LowerOperation().
LowerFP_TO_UINT()
SDValue AMDGPUTargetLowering::LowerFP_TO_UINT (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2732 of file AMDGPUISelLowering.cpp.
References llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FP_EXTEND, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::MVT::i64, and LowerFP64_TO_INT().
Referenced by LowerOperation().
LowerFREM()
SDValue AMDGPUTargetLowering::LowerFREM (SDValue Op, SelectionDAG & DAG) const protected
Split a vector store into multiple scalar stores.
Returns
The resulting chain.
Definition at line 2024 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), X, and Y.
Referenced by LowerOperation().
LowerFRINT()
SDValue AMDGPUTargetLowering::LowerFRINT (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2128 of file AMDGPUISelLowering.cpp.
References assert(), llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FSUB, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SDValue::getValueType(), and llvm::APFloatBase::IEEEdouble().
Referenced by LowerOperation().
LowerFROUND()
SDValue AMDGPUTargetLowering::LowerFROUND (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2254 of file AMDGPUISelLowering.cpp.
References llvm::MVT::f64, llvm::ISD::FTRUNC, llvm::SDValue::getValueType(), llvm::TargetLoweringBase::isOperationLegal(), llvm_unreachable, LowerFROUND64(), and LowerFROUND_LegalFTRUNC().
Referenced by LowerOperation().
LowerFROUND64()
SDValue AMDGPUTargetLowering::LowerFROUND64 (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2197 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::BITCAST, D, llvm::ISD::EXTRACT_VECTOR_ELT, extractF64Exponent(), llvm::MVT::f64, llvm::ISD::FCOPYSIGN, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::SELECT, llvm::ISD::SETEQ, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SRA, llvm::MVT::v2i32, and X.
Referenced by LowerFROUND().
LowerFROUND_LegalFTRUNC()
SDValue AMDGPUTargetLowering::LowerFROUND_LegalFTRUNC (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2167 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SDValue::getValueType(), llvm::ISD::SELECT, llvm::ISD::SETOGE, and X.
Referenced by LowerFROUND().
LowerFTRUNC()
SDValue AMDGPUTargetLowering::LowerFTRUNC (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2079 of file AMDGPUISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, extractF64Exponent(), llvm::MVT::f64, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SDValue::getValueType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::SELECT, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SRA, and llvm::MVT::v2i32.
Referenced by LowerOperation().
LowerGlobalAddress()
SDValue AMDGPUTargetLowering::LowerGlobalAddress (AMDGPUMachineFunction * MFI, SDValue Op, SelectionDAG & DAG) const protected virtual
Definition at line 1188 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUMachineFunction::allocateLDSGlobal(), assert(), llvm::LLVMContext::diagnose(), G, llvm::GlobalAddressSDNode::getAddressSpace(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getMachineFunction(), llvm::GlobalAddressSDNode::getOffset(), llvm::SDValue::getValueType(), hasDefinedInitializer(), llvm::AMDGPUMachineFunction::isEntryFunction(), AMDGPUAS::LOCAL_ADDRESS, and AMDGPUAS::REGION_ADDRESS.
Referenced by buildPCRelGlobalAddress(), and llvm::R600TargetLowering::ReplaceNodeResults().
LowerINT_TO_FP32()
SDValue AMDGPUTargetLowering::LowerINT_TO_FP32 (SDValue Op, SelectionDAG & DAG, bool Signed) const protected
Definition at line 2396 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::BITCAST, C, llvm::ISD::CTLZ_ZERO_UNDEF, E, llvm::MVT::f32, llvm::ISD::FNEG, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::OR, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SETUGT, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::TRUNCATE, and llvm::ISD::XOR.
Referenced by LowerSINT_TO_FP(), and LowerUINT_TO_FP().
LowerINT_TO_FP64()
SDValue AMDGPUTargetLowering::LowerINT_TO_FP64 (SDValue Op, SelectionDAG & DAG, bool Signed) const protected
Definition at line 2481 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::ISD::FADD, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::AMDGPUISD::LDEXP, llvm::MipsISD::Lo, llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, and llvm::MVT::v2i32.
Referenced by LowerSINT_TO_FP(), and LowerUINT_TO_FP().
LowerOperation()
SDValue AMDGPUTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::SITargetLowering, and llvm::R600TargetLowering.
Definition at line 1122 of file AMDGPUISelLowering.cpp.
References llvm::ISD::CONCAT_VECTORS, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DYNAMIC_STACKALLOC, llvm::errs(), llvm::ISD::EXTRACT_SUBVECTOR, F(), llvm::ISD::FCEIL, llvm::ISD::FEXP, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FNEARBYINT, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FTRUNC, llvm::SDValue::getOpcode(), llvm_unreachable, llvm::numbers::ln10f, llvm::numbers::ln2f, llvm::numbers::log2ef, LowerCONCAT_VECTORS(), LowerCTLZ_CTTZ(), LowerDYNAMIC_STACKALLOC(), LowerEXTRACT_SUBVECTOR(), LowerFCEIL(), lowerFEXP(), LowerFFLOOR(), LowerFLOG(), LowerFNEARBYINT(), LowerFP_TO_FP16(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), LowerFREM(), LowerFRINT(), LowerFROUND(), LowerFTRUNC(), LowerSDIVREM(), LowerSIGN_EXTEND_INREG(), LowerSINT_TO_FP(), LowerUDIVREM(), LowerUINT_TO_FP(), llvm::SDNode::print(), llvm::ISD::SDIVREM, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::UDIVREM, and llvm::ISD::UINT_TO_FP.
Referenced by llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), and stripBitcast().
LowerReturn()
SDValue AMDGPUTargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , const SDLoc & , SelectionDAG &) const override virtual
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
The implementation should return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::SITargetLowering.
Definition at line 1016 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUISD::ENDPGM, llvm::SelectionDAG::getNode(), and llvm::MVT::Other.
Referenced by llvm::SITargetLowering::LowerReturn(), and stripBitcast().
LowerSDIVREM()
SDValue AMDGPUTargetLowering::LowerSDIVREM (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 1963 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::ComputeNumSignBits(), llvm::ISD::EXTRACT_ELEMENT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getHalfSizedIntegerVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSelectCC(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i64, LowerDIVREM24(), llvm::ISD::SDIVREM, llvm::ISD::SETLT, llvm::ISD::SIGN_EXTEND, llvm::ISD::SUB, llvm::ISD::UDIVREM, and llvm::ISD::XOR.
Referenced by LowerOperation(), and llvm::R600TargetLowering::ReplaceNodeResults().
LowerSIGN_EXTEND_INREG()
SDValue AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2755 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::SelectionDAG::ExtractVectorElements(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getValueType(), llvm::MVT::getVectorNumElements(), I, llvm::MVT::isVector(), and llvm::ISD::SIGN_EXTEND_INREG.
Referenced by LowerOperation().
LowerSINT_TO_FP()
SDValue AMDGPUTargetLowering::LowerSINT_TO_FP (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2541 of file AMDGPUISelLowering.cpp.
References assert(), llvm::MipsISD::Ext, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, LowerINT_TO_FP32(), LowerINT_TO_FP64(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::SINT_TO_FP.
Referenced by LowerOperation().
LowerSTORE()
SDValue llvm::AMDGPUTargetLowering::LowerSTORE (SDValue Op, SelectionDAG & DAG) const protected
LowerUDIVREM()
SDValue AMDGPUTargetLowering::LowerUDIVREM (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 1848 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, E, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSelectCC(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::i64, LowerDIVREM24(), LowerUDIVREM64(), llvm::ISD::MUL, llvm::ISD::MULHU, llvm::AMDGPUISD::RCP, Results, llvm::ISD::SETEQ, llvm::ISD::SETUGE, llvm::ISD::SUB, and llvm::AMDGPUISD::URECIP.
Referenced by LowerOperation().
LowerUDIVREM64()
void AMDGPUTargetLowering::LowerUDIVREM64 (SDValue Op, SelectionDAG & DAG, SmallVectorImpl< SDValue > & Results) const protected
Definition at line 1635 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDCARRY, llvm::ISD::AND, assert(), llvm::AArch64ISD::BIT, llvm::ISD::BITCAST, llvm::ISD::EXTRACT_ELEMENT, llvm::MVT::f32, llvm::ISD::FMAD, llvm::AMDGPUISD::FMAD_FTZ, llvm::ISD::FMUL, llvm::AMDGPU::SIModeRegisterDefaults::FP32Denormals, llvm::ISD::FP_TO_UINT, llvm::ISD::FTRUNC, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::EVT::getHalfSizedIntegerVT(), llvm::APInt::getHighBitsSet(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::AMDGPUMachineFunction::getMode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSelectCC(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i1, llvm::MVT::i64, llvm::TargetLoweringBase::isTypeLegal(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::MUL, llvm::ISD::MULHU, llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::AMDGPUISD::RCP, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SHL, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::SUBCARRY, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UREM, llvm::MVT::v2i32, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerUDIVREM(), and llvm::R600TargetLowering::ReplaceNodeResults().
LowerUINT_TO_FP()
SDValue AMDGPUTargetLowering::LowerUINT_TO_FP (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2504 of file AMDGPUISelLowering.cpp.
References assert(), llvm::MipsISD::Ext, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, LowerINT_TO_FP32(), LowerINT_TO_FP64(), llvm::ISD::UINT_TO_FP, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerOperation().
lowerUnhandledCall()
SDValue AMDGPUTargetLowering::lowerUnhandledCall (CallLoweringInfo & CLI, SmallVectorImpl< SDValue > & InVals, StringRef Reason) const
Definition at line 1079 of file AMDGPUISelLowering.cpp.
References Callee, llvm::TargetLowering::CallLoweringInfo::Callee, llvm::TargetLowering::CallLoweringInfo::DAG, llvm::LLVMContext::diagnose(), llvm::TargetLowering::CallLoweringInfo::DL, E, G, llvm::SelectionDAG::getContext(), llvm::SDLoc::getDebugLoc(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getUNDEF(), I, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::TargetLowering::CallLoweringInfo::IsTailCall, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by LowerCall(), llvm::SITargetLowering::LowerCall(), and stripBitcast().
mayIgnoreSignedZero()
bool llvm::AMDGPUTargetLowering::mayIgnoreSignedZero (SDValue Op) const inline
Definition at line 149 of file AMDGPUISelLowering.h.
References llvm::SDNode::getFlags(), llvm::SDValue::getNode(), llvm::TargetLoweringBase::getTargetMachine(), and llvm::SDNodeFlags::hasNoSignedZeros().
Referenced by performFNegCombine().
mergeStoresAfterLegalization()
bool llvm::AMDGPUTargetLowering::mergeStoresAfterLegalization (EVT MemVT) const inline override virtual
Allow store merging for the specified type after legalization in addition to before legalization.
This may transform stores that do not exist earlier (for example, stores created from intrinsics).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 240 of file AMDGPUISelLowering.h.
numBitsSigned()
unsigned AMDGPUTargetLowering::numBitsSigned (SDValue Op, SelectionDAG & DAG) static
Definition at line 57 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::ComputeNumSignBits(), llvm::EVT::getSizeInBits(), and llvm::SDValue::getValueType().
Referenced by getMad64_32(), and isI24().
numBitsUnsigned()
unsigned AMDGPUTargetLowering::numBitsUnsigned (SDValue Op, SelectionDAG & DAG) static
Definition at line 51 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::EVT::getSizeInBits(), and llvm::SDValue::getValueType().
Referenced by getMad64_32(), and isU24().
performAssertSZExtCombine()
SDValue AMDGPUTargetLowering::performAssertSZExtCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 2985 of file AMDGPUISelLowering.cpp.
References llvm::EVT::bitsGE(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), and llvm::ISD::TRUNCATE.
Referenced by PerformDAGCombine().
performCtlz_CttzCombine()
SDValue AMDGPUTargetLowering::performCtlz_CttzCombine (const SDLoc & SL, SDValue Cond, SDValue LHS, SDValue RHS, DAGCombinerInfo & DCI) const protected
Definition at line 3457 of file AMDGPUISelLowering.cpp.
PerformDAGCombine()
SDValue AMDGPUTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const override virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::SITargetLowering, and llvm::R600TargetLowering.
Definition at line 3902 of file AMDGPUISelLowering.cpp.
References llvm::AfterLegalizeDAG, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::AMDGPUISD::BFE_I32, llvm::AMDGPUISD::BFE_U32, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, C, llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), E, llvm::ISD::FABS, llvm::ISD::FNEG, llvm::APInt::getBitsSet(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLowering::DAGCombinerInfo::getDAGCombineLevel(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::ConstantSDNode::getZExtValue(), llvm::APInt::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::AMDGPUSubtarget::hasSDWA(), llvm::Hi_32(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::EVT::isVector(), llvm::Lo_32(), llvm::ISD::LOAD, llvm::ISD::MUL, llvm::AMDGPUISD::MUL_I24, llvm::AMDGPUISD::MUL_LOHI_I24, llvm::AMDGPUISD::MUL_LOHI_U24, llvm::AMDGPUISD::MUL_U24, llvm::AMDGPUISD::MULHI_I24, llvm::AMDGPUISD::MULHI_U24, llvm::ISD::MULHS, llvm::ISD::MULHU, performAssertSZExtCombine(), performFAbsCombine(), performFNegCombine(), performIntrinsicWOChainCombine(), performLoadCombine(), performMulCombine(), performMulhsCombine(), performMulhuCombine(), performMulLoHi24Combine(), performRcpCombine(), performSelectCombine(), performShlCombine(), performSraCombine(), performSrlCombine(), performStoreCombine(), performTruncateCombine(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_IFLAG, llvm::ISD::SELECT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, Signed, simplifyI24(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::TRUNCATE, and llvm::MVT::v2i32.
Referenced by llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), and stripBitcast().
performFAbsCombine()
SDValue AMDGPUTargetLowering::performFAbsCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3865 of file AMDGPUISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::ISD::FP16_TO_FP, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::AMDGPUSubtarget::has16BitInsts(), and llvm::SDValue::hasOneUse().
Referenced by PerformDAGCombine().
performFNegCombine()
SDValue AMDGPUTargetLowering::performFNegCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3663 of file AMDGPUISelLowering.cpp.
References allUsesHaveSourceMods(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::AMDGPUISD::FMAX_LEGACY, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN_LEGACY, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::AMDGPUISD::FMUL_LEGACY, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, fnegFoldsIntoOp(), llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FRINT, llvm::ISD::FSIN, llvm::ISD::FTRUNC, llvm::SelectionDAG::getConstant(), llvm::SDNode::getFlags(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), I, inverseMinMax(), isConstantCostlierToNegate(), mayIgnoreSignedZero(), llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_IFLAG, llvm::AMDGPUISD::RCP_LEGACY, llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::AMDGPUISD::SIN_HW, and llvm::ISD::XOR.
Referenced by PerformDAGCombine().
performIntrinsicWOChainCombine()
SDValue AMDGPUTargetLowering::performIntrinsicWOChainCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3008 of file AMDGPUISelLowering.cpp.
References llvm::SDNode::getOperand(), and simplifyI24().
Referenced by PerformDAGCombine().
performLoadCombine()
SDValue AMDGPUTargetLowering::performLoadCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 2874 of file AMDGPUISelLowering.cpp.
References llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::TargetLowering::expandUnalignedLoad(), llvm::MemSDNode::getAddressSpace(), llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getContext(), getEquivalentMemType(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::EVT::getStoreSize(), llvm::SDValue::getValue(), hasVolatileUser(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::ISD::isNormalLoad(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), N, llvm::TargetLowering::scalarizeVectorLoad(), shouldCombineMemoryType(), and Size.
Referenced by PerformDAGCombine().
performMulCombine()
SDValue AMDGPUTargetLowering::performMulCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3306 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::EVT::bitsLE(), llvm::TargetLowering::DAGCombinerInfo::DAG, getMul24(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::AMDGPUSubtarget::hasMulI24(), llvm::AMDGPUSubtarget::hasMulU24(), llvm::MVT::i16, llvm::MVT::i32, isI24(), isU24(), llvm::EVT::isVector(), and Size.
Referenced by PerformDAGCombine().
performMulhsCombine()
SDValue AMDGPUTargetLowering::performMulhsCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3353 of file AMDGPUISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SDNode::getValueType(), llvm::AMDGPUSubtarget::hasMulI24(), llvm::MVT::i32, isI24(), llvm::EVT::isVector(), and llvm::AMDGPUISD::MULHI_I24.
Referenced by PerformDAGCombine().
performMulhuCombine()
SDValue AMDGPUTargetLowering::performMulhuCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3377 of file AMDGPUISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::AMDGPUSubtarget::hasMulU24(), llvm::MVT::i32, isU24(), llvm::EVT::isVector(), and llvm::AMDGPUISD::MULHI_U24.
Referenced by PerformDAGCombine().
performMulLoHi24Combine()
SDValue AMDGPUTargetLowering::performMulLoHi24Combine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3401 of file AMDGPUISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MVT::i32, llvm::AMDGPUISD::MUL_I24, llvm::AMDGPUISD::MUL_LOHI_I24, llvm::AMDGPUISD::MUL_U24, llvm::AMDGPUISD::MULHI_I24, llvm::AMDGPUISD::MULHI_U24, Signed, and simplifyI24().
Referenced by PerformDAGCombine().
performRcpCombine()
SDValue AMDGPUTargetLowering::performRcpCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3890 of file AMDGPUISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SelectionDAG::getConstantFP(), llvm::SDNode::getOperand(), llvm::APFloat::getSemantics(), and llvm::SDNode::getValueType().
Referenced by fp16SrcZerosHighBits(), and PerformDAGCombine().
performSelectCombine()
SDValue AMDGPUTargetLowering::performSelectCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3574 of file AMDGPUISelLowering.cpp.
References foldFreeOpFromSelect().
Referenced by PerformDAGCombine().
performShlCombine()
SDValue AMDGPUTargetLowering::performShlCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3045 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::isOperationLegal(), llvm::MipsISD::Lo, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::TRUNCATE, llvm::MVT::v2i16, llvm::MVT::v2i32, X, and llvm::ISD::ZERO_EXTEND.
Referenced by PerformDAGCombine().
performSraCombine()
SDValue AMDGPUTargetLowering::performSraCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3113 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), getHiHalf64(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::SRA, and llvm::MVT::v2i32.
Referenced by PerformDAGCombine().
performSrlCombine()
SDValue AMDGPUTargetLowering::performSrlCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3148 of file AMDGPUISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::SRL, and llvm::MVT::v2i32.
Referenced by PerformDAGCombine().
performStoreCombine()
SDValue AMDGPUTargetLowering::performStoreCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 2928 of file AMDGPUISelLowering.cpp.
References llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::TargetLowering::expandUnalignedStore(), llvm::MemSDNode::getAddressSpace(), llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getContext(), getEquivalentMemType(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::StoreSDNode::getValue(), llvm::SDValue::hasOneUse(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::ISD::isNormalStore(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), N, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::TargetLowering::scalarizeVectorStore(), shouldCombineMemoryType(), and Size.
Referenced by PerformDAGCombine().
performTruncateCombine()
SDValue AMDGPUTargetLowering::performTruncateCombine (SDNode * N, DAGCombinerInfo & DCI) const protected
Definition at line 3197 of file AMDGPUISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::EVT::changeTypeToInteger(), llvm::SelectionDAG::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::KnownBits::getBitWidth(), llvm::KnownBits::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::i32, llvm::KnownBits::isConstant(), llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), llvm::EVT::isVector(), llvm::Log2_32(), llvm::ISD::SHL, Size, llvm::ISD::SRA, llvm::ISD::SRL, stripBitcast(), llvm::ISD::TRUNCATE, and llvm::APInt::ule().
Referenced by PerformDAGCombine().
PostISelFolding()
virtual SDNode* llvm::AMDGPUTargetLowering::PostISelFolding (MachineSDNode * N, SelectionDAG & DAG) const pure virtual
Implemented in llvm::SITargetLowering.
Referenced by isFsqrtCheap().
ReplaceNodeResults()
void AMDGPUTargetLowering::ReplaceNodeResults (SDNode * , SmallVectorImpl< SDValue > & , SelectionDAG &) const override virtual
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all.
If the target has no operations that require custom lowering, it need not implement this. The default implementation aborts.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::SITargetLowering, and llvm::R600TargetLowering.
Definition at line 1163 of file AMDGPUISelLowering.cpp.
References llvm::SDNode::getOpcode(), and llvm::ISD::SIGN_EXTEND_INREG.
Referenced by llvm::R600TargetLowering::ReplaceNodeResults(), and stripBitcast().
shouldCombineMemoryType()
bool AMDGPUTargetLowering::shouldCombineMemoryType (EVT VT) const protected
Definition at line 2853 of file AMDGPUISelLowering.cpp.
References llvm::EVT::getScalarType(), llvm::EVT::getStoreSize(), llvm::MVT::i32, llvm::EVT::isByteSized(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), and Size.
Referenced by performLoadCombine(), and performStoreCombine().
shouldExpandAtomicRMWInIR()
TargetLowering::AtomicExpansionKind AMDGPUTargetLowering::shouldExpandAtomicRMWInIR (AtomicRMWInst * RMW) const override virtual
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Default is to never expand.
Reimplemented from llvm::TargetLoweringBase.
Reimplemented in llvm::SITargetLowering.
Definition at line 4708 of file AMDGPUISelLowering.cpp.
References llvm::TargetLoweringBase::CmpXChg, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::AtomicRMWInst::getOperation(), llvm::AtomicRMWInst::Nand, and llvm::TargetLoweringBase::None.
Referenced by getFenceOperandTy(), and llvm::SITargetLowering::shouldExpandAtomicRMWInIR().
shouldReduceLoadWidth()
bool AMDGPUTargetLowering::shouldReduceLoadWidth (SDNode * Load, ISD::LoadExtType ExtTy, EVT NewVT) const override virtual
Return true if it is profitable to reduce a load to a smaller type.
Example: (i16 (trunc (i32 (load x))) -> i16 load x
Reimplemented from llvm::TargetLoweringBase.
Definition at line 635 of file AMDGPUISelLowering.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::MemSDNode::getAddressSpace(), getAlignment(), llvm::MemSDNode::getMemOperand(), llvm::EVT::getStoreSizeInBits(), llvm::SDNode::getValueType(), AMDGPUAS::GLOBAL_ADDRESS, llvm::MemSDNode::isInvariant(), llvm::AMDGPUInstrInfo::isUniformMMO(), N, and llvm::TargetLoweringBase::shouldReduceLoadWidth().
Referenced by stripBitcast().
ShouldShrinkFPConstant()
bool AMDGPUTargetLowering::ShouldShrinkFPConstant (EVT) const override virtual
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 630 of file AMDGPUISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, and llvm::EVT::getScalarType().
Referenced by stripBitcast().
split64BitValue()
std::pair< SDValue, SDValue > AMDGPUTargetLowering::split64BitValue (SDValue Op, SelectionDAG & DAG) const protected
Return 64-bit value Op as two 32-bit integers.
Definition at line 1330 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MipsISD::Lo, and llvm::MVT::v2i32.
Referenced by getPermuteMask(), and splitBinaryBitConstantOpImpl().
splitBinaryBitConstantOpImpl()
SDValue AMDGPUTargetLowering::splitBinaryBitConstantOpImpl (DAGCombinerInfo & DCI, const SDLoc & SL, unsigned Opc, SDValue LHS, uint32_t ValLo, uint32_t ValHi) const protected
Split the 64-bit value LHS into two 32-bit components, and perform the binary operation Opc to it with the corresponding constant operands.
Definition at line 3022 of file AMDGPUISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::MipsISD::Lo, split64BitValue(), and llvm::MVT::v2i32.
Referenced by bitOpWithConstantIsReducible().
splitVector()
std::pair< SDValue, SDValue > AMDGPUTargetLowering::splitVector (const SDValue & N, const SDLoc & DL, const EVT & LoVT, const EVT & HighVT, SelectionDAG & DAG) const protected
Split a vector value into two parts of types LoVT and HiVT.
HiVT could be scalar.
Definition at line 1379 of file AMDGPUISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::MipsISD::Hi, llvm::EVT::isVector(), llvm::MipsISD::Lo, and N.
Referenced by SplitVectorLoad(), and SplitVectorStore().
SplitVectorLoad()
SDValue AMDGPUTargetLowering::SplitVectorLoad (SDValue Op, SelectionDAG & DAG) const protected
Split a vector load into 2 loads of half the vector.
Definition at line 1395 of file AMDGPUISelLowering.cpp.
References llvm::ISD::CONCAT_VECTORS, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getObjectPtrOffset(), llvm::MachineMemOperand::getPointerInfo(), getSplitDestVTs(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), getVectorIdxTy(), llvm::MipsISD::Hi, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::MipsISD::Lo, llvm::SPII::Load, llvm::MinAlign(), llvm::MVT::Other, llvm::TargetLowering::scalarizeVectorLoad(), Size, splitVector(), and llvm::ISD::TokenFactor.
Referenced by getLoadExtOrTrunc().
SplitVectorStore()
SDValue AMDGPUTargetLowering::SplitVectorStore (SDValue Op, SelectionDAG & DAG) const protected
Split a vector store into 2 stores of half the vector.
Definition at line 1482 of file AMDGPUISelLowering.cpp.
References llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getObjectPtrOffset(), llvm::MachineMemOperand::getPointerInfo(), getSplitDestVTs(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTruncStore(), llvm::StoreSDNode::getValue(), llvm::EVT::getVectorNumElements(), llvm::MachinePointerInfo::getWithOffset(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, llvm::MinAlign(), llvm::MVT::Other, llvm::TargetLowering::scalarizeVectorStore(), Size, splitVector(), llvm::SPII::Store, and llvm::ISD::TokenFactor.
Referenced by getSPDenormModeValue().
storeOfVectorConstantIsCheap()
bool AMDGPUTargetLowering::storeOfVectorConstantIsCheap (EVT MemVT, unsigned NumElem, unsigned AddrSpace) const override virtual
Return true if it is expected to be cheaper to do a store of a non-zero vector constant with the given size and type for the address space than to store the individual scalar element constants.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 755 of file AMDGPUISelLowering.cpp.
Referenced by stripBitcast().
storeStackInputValue()
SDValue AMDGPUTargetLowering::storeStackInputValue (SelectionDAG & DAG, const SDLoc & SL, SDValue Chain, SDValue ArgVal, int64_t Offset) const
Definition at line 4170 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::MachinePointerInfo::getStack(), llvm::SelectionDAG::getStore(), llvm::MVT::i32, llvm::MachineMemOperand::MODereferenceable, and llvm::SPII::Store.
Referenced by CreateLiveInRegisterRaw(), and llvm::SITargetLowering::passSpecialInputs().
stripBitcast()
static SDValue llvm::AMDGPUTargetLowering::stripBitcast (SDValue Val) inline static
Definition at line 160 of file AMDGPUISelLowering.h.
References addTokenForArgument(), aggressivelyPreferBuildVectorSources(), allUsesHaveSourceMods(), llvm::ISD::BITCAST, CCAssignFnForCall(), CCAssignFnForReturn(), combineFMinMaxLegacy(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getTargetNodeName(), getVectorIdxTy(), isCheapToSpeculateCtlz(), isCheapToSpeculateCttz(), isFAbsFree(), isFNegFree(), isFPImmLegal(), isLoadBitCastBeneficial(), isNarrowingProfitable(), isSDNodeAlwaysUniform(), isSelectSupported(), isTruncateFree(), isZExtFree(), llvm::SPII::Load, LowerCall(), LowerDYNAMIC_STACKALLOC(), LowerOperation(), LowerReturn(), lowerUnhandledCall(), PerformDAGCombine(), ReplaceNodeResults(), shouldReduceLoadWidth(), ShouldShrinkFPConstant(), and storeOfVectorConstantIsCheap().
Referenced by findMemSDNode(), and performTruncateCombine().
WidenVectorLoad()
SDValue AMDGPUTargetLowering::WidenVectorLoad (SDValue Op, SelectionDAG & DAG) const protected
Widen a vector load from vec3 to vec4.
Definition at line 1457 of file AMDGPUISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::MachineMemOperand::getPointerInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), getVectorIdxTy(), llvm::EVT::getVectorVT(), and llvm::SPII::Load.
Referenced by getLoadExtOrTrunc().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUISelLowering.h
lib/Target/AMDGPU/AMDGPUISelLowering.cpp