LLVM: llvm::DbgLabel Class Reference
llvm::DbgLabel Class Reference
This class is used to track label information.
#include "CodeGen/AsmPrinter/DwarfDebug.h"
Public Member Functions
DbgLabel (const DILabel *L, const DILocation *IA, const MCSymbol *Sym=nullptr)
Symbol before DBG_LABEL instruction.
dwarf::Tag getTag () const
Translate tag to proper Dwarf tag.
const DILabel * getLabel () const
Accessors.
const MCSymbol * getSymbol () const
StringRef getName () const
Public Member Functions inherited from llvm::DbgEntity
DbgEntity (const DINode *N, const DILocation *IA, unsigned ID)
virtual ~DbgEntity ()
void setDIE (DIE &D)
const DINode * getEntity () const
Accessors.
const DILocation * getInlinedAt () const
DIE * getDIE () const
unsigned getDbgEntityID () const
Static Public Member Functions
static bool classof (const DbgEntity *N)
Static Public Member Functions inherited from llvm::DbgEntity
static bool classof (const DbgEntity *N)
Additional Inherited Members
Public Types inherited from llvm::DbgEntity
enum DbgEntityKind { DbgVariableKind, DbgLabelKind }
Detailed Description
This class is used to track label information.
Labels are collected from DBG_LABEL instructions.
Definition at line 235 of file DwarfDebug.h.
Constructor & Destructor Documentation
DbgLabel()
llvm::DbgLabel::DbgLabel (const DILabel * L, const DILocation * IA, const MCSymbol * Sym = nullptr) inline
Symbol before DBG_LABEL instruction.
We need MCSymbol information to generate DW_AT_low_pc.
Definition at line 240 of file DwarfDebug.h.
Member Function Documentation
classof()
static bool llvm::DbgLabel::classof (const DbgEntity * N) inline static
Definition at line 256 of file DwarfDebug.h.
References llvm::DbgEntity::DbgLabelKind, and llvm::DbgEntity::getDbgEntityID().
getLabel()
const DILabel* llvm::DbgLabel::getLabel () const inline
Accessors.
Definition at line 245 of file DwarfDebug.h.
References llvm::DbgEntity::getEntity().
Referenced by llvm::DwarfCompileUnit::applyLabelAttributes(), and llvm::DwarfCompileUnit::constructLabelDIE().
getName()
StringRef llvm::DbgLabel::getName () const inline
Definition at line 248 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::applyLabelAttributes().
getSymbol()
const MCSymbol* llvm::DbgLabel::getSymbol () const inline
Definition at line 246 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::finishEntityDefinition().
getTag()
dwarf::Tag llvm::DbgLabel::getTag () const inline
Translate tag to proper Dwarf tag.
Definition at line 252 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::constructLabelDIE().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/DwarfDebug.h