LLVM: llvm::InstrProfSummaryBuilder Class Reference
llvm::InstrProfSummaryBuilder Class Reference final
#include "llvm/ProfileData/ProfileCommon.h"
Public Member Functions
InstrProfSummaryBuilder (std::vector< uint32_t > Cutoffs)
void addRecord (const InstrProfRecord &)
std::unique_ptr< ProfileSummary > getSummary ()
Additional Inherited Members
Static Public Attributes inherited from llvm::ProfileSummaryBuilder
static const ArrayRef< uint32_t > DefaultCutoffs
A vector of useful cutoff values for detailed summary.
Protected Member Functions inherited from llvm::ProfileSummaryBuilder
ProfileSummaryBuilder (std::vector< uint32_t > Cutoffs)
~ProfileSummaryBuilder ()=default
void addCount (uint64_t Count)
This is called when a count is seen in the profile.
void computeDetailedSummary ()
Protected Attributes inherited from llvm::ProfileSummaryBuilder
SummaryEntryVector DetailedSummary
uint64_t TotalCount = 0
uint64_t MaxCount = 0
uint64_t MaxFunctionCount = 0
uint32_t NumCounts = 0
uint32_t NumFunctions = 0
Detailed Description
Definition at line 67 of file ProfileCommon.h.
Constructor & Destructor Documentation
InstrProfSummaryBuilder()
llvm::InstrProfSummaryBuilder::InstrProfSummaryBuilder (std::vector< uint32_t > Cutoffs) inline
Definition at line 74 of file ProfileCommon.h.
Member Function Documentation
addRecord()
void InstrProfSummaryBuilder::addRecord (const InstrProfRecord & R)
Definition at line 34 of file ProfileSummaryBuilder.cpp.
References llvm::InstrProfRecord::Counts, E, and I.
Referenced by llvm::SampleProfileSummaryBuilder::addRecord(), and llvm::InstrProfRecordWriterTrait::EmitData().
getSummary()
std::unique_ptr< ProfileSummary > InstrProfSummaryBuilder::getSummary ()
Definition at line 101 of file ProfileSummaryBuilder.cpp.
References llvm::ProfileSummaryBuilder::addCount(), llvm::ProfileSummaryBuilder::computeDetailedSummary(), llvm::ProfileSummaryBuilder::DetailedSummary, llvm::ProfileSummaryBuilder::MaxCount, llvm::ProfileSummaryBuilder::MaxFunctionCount, llvm::ProfileSummaryBuilder::NumCounts, llvm::ProfileSummaryBuilder::NumFunctions, llvm::ProfileSummary::PSK_Instr, and llvm::ProfileSummaryBuilder::TotalCount.
Referenced by llvm::IndexedInstrProfReader::hasFormat(), and setSummary().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/ProfileCommon.h
lib/ProfileData/ProfileSummaryBuilder.cpp