LLVM: llvm::CallGraphSCCPass Class Reference
llvm::CallGraphSCCPass Class Reference abstract
#include "llvm/Analysis/CallGraphSCCPass.h"
Public Member Functions
CallGraphSCCPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a pass that prints the Module corresponding to a CallGraph.
virtual bool doInitialization (CallGraph &CG)
doInitialization - This method is called before the SCC's of the program has been processed, allowing the pass to do initialization as necessary.
virtual bool runOnSCC (CallGraphSCC &SCC)=0
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC.
virtual bool doFinalization (CallGraph &CG)
doFinalization - This method is called after the SCC's of the program has been processed, allowing the pass to do final cleanup as necessary.
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manager this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
void getAnalysisUsage (AnalysisUsage &Info) const override
getAnalysisUsage - For this class, we declare that we require and preserve the call graph.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Member Functions
bool skipSCC (CallGraphSCC &SCC) const
Optional passes call this function to check whether the pass should be skipped.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 34 of file CallGraphSCCPass.h.
Constructor & Destructor Documentation
CallGraphSCCPass()
llvm::CallGraphSCCPass::CallGraphSCCPass (char & pid) inline explicit
Definition at line 36 of file CallGraphSCCPass.h.
References createPrinterPass(), llvm::Pass::doFinalization(), and llvm::Pass::doInitialization().
Member Function Documentation
assignPassManager()
void CallGraphSCCPass::assignPassManager (PMStack & PMS, PassManagerType PMT) override virtual
Assign pass manager to manager this pass.
Assign pass manager to manage this pass.
Reimplemented from llvm::Pass.
Definition at line 567 of file CallGraphSCCPass.cpp.
References llvm::PMTopLevelManager::addIndirectPassManager(), assert(), llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_CallGraphPassManager, llvm::PMStack::pop(), llvm::PMStack::push(), llvm::PMTopLevelManager::schedulePass(), and llvm::PMStack::top().
Referenced by doFinalization().
createPrinterPass()
Pass * CallGraphSCCPass::createPrinterPass (raw_ostream & OS, const std::string & Banner) const override virtual
createPrinterPass - Get a pass that prints the Module corresponding to a CallGraph.
Implements llvm::Pass.
Definition at line 679 of file CallGraphSCCPass.cpp.
Referenced by CallGraphSCCPass().
doFinalization()
virtual bool llvm::CallGraphSCCPass::doFinalization (CallGraph & CG) inline virtual
doFinalization - This method is called after the SCC's of the program has been processed, allowing the pass to do final cleanup as necessary.
Reimplemented in llvm::LegacyInlinerBase.
Definition at line 63 of file CallGraphSCCPass.h.
References assignPassManager().
doInitialization()
virtual bool llvm::CallGraphSCCPass::doInitialization (CallGraph & CG) inline virtual
doInitialization - This method is called before the SCC's of the program has been processed, allowing the pass to do initialization as necessary.
Reimplemented in llvm::LegacyInlinerBase.
Definition at line 48 of file CallGraphSCCPass.h.
References runOnSCC().
Referenced by llvm::createArgumentPromotionPass(), and replaceAllPrepares().
getAnalysisUsage()
void CallGraphSCCPass::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - For this class, we declare that we require and preserve the call graph.
For this class, we declare that we require and preserve the call graph.
If the derived class implements this method, it should always explicitly call the implementation here.
Reimplemented from llvm::Pass.
Reimplemented in llvm::DummyCGSCCPass, llvm::LegacyInlinerBase, and llvm::AMDGPUPerfHintAnalysis.
Definition at line 606 of file CallGraphSCCPass.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), B, llvm::forcePrintModuleIR(), llvm::CallGraphSCC::getCallGraph(), llvm::CallGraphNode::getFunction(), llvm::CallGraph::getModule(), llvm::isFunctionInPrintList(), llvm::Module::print(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by llvm::LegacyInlinerBase::getAnalysisUsage(), getPotentialPassManagerType(), replaceAllPrepares(), llvm::ArgumentPromotionPass::run(), and llvm::PostOrderFunctionAttrsPass::run().
getPotentialPassManagerType()
PassManagerType llvm::CallGraphSCCPass::getPotentialPassManagerType () const inline override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 71 of file CallGraphSCCPass.h.
References getAnalysisUsage(), Info, llvm::PMT_CallGraphPassManager, and skipSCC().
runOnSCC()
virtual bool llvm::CallGraphSCCPass::runOnSCC (CallGraphSCC & SCC) pure virtual
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC.
Note that non-recursive (or only self-recursive) functions will have an SCC size of 1, where recursive portions of the call graph will have SCC size > 1.
SCC passes that add or delete functions to the SCC are required to update the SCC list, otherwise stale pointers may be dereferenced.
Implemented in llvm::DummyCGSCCPass, llvm::LegacyInlinerBase, and llvm::AMDGPUPerfHintAnalysis.
Referenced by doInitialization().
skipSCC()
bool CallGraphSCCPass::skipSCC (CallGraphSCC & SCC) const protected
Optional passes call this function to check whether the pass should be skipped.
This is the case when optimization bisect is over the limit.
Definition at line 702 of file CallGraphSCCPass.cpp.
References llvm::CallGraphSCC::getCallGraph(), llvm::Module::getContext(), getDescription(), llvm::CallGraph::getModule(), llvm::LLVMContext::getOptPassGate(), llvm::DummyCGSCCPass::ID, INITIALIZE_PASS, llvm::OptPassGate::isEnabled(), and llvm::OptPassGate::shouldRunPass().
Referenced by getPotentialPassManagerType(), and llvm::LegacyInlinerBase::runOnSCC().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CallGraphSCCPass.h
lib/Analysis/CallGraphSCCPass.cpp