LLVM: llvm::AccelTableData Class Reference
llvm::AccelTableData Class Reference abstract
Interface which the different types of accelerator table data have to conform.
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
virtual ~AccelTableData ()=default
bool operator< (const AccelTableData &Other) const
virtual void print (raw_ostream &OS) const =0
Protected Member Functions
virtual uint64_t order () const =0
Detailed Description
Interface which the different types of accelerator table data have to conform.
It serves as a base class for different values of the template argument of the AccelTable class template.
Definition at line 114 of file AccelTable.h.
Constructor & Destructor Documentation
~AccelTableData()
virtual llvm::AccelTableData::~AccelTableData () virtual default
Member Function Documentation
operator<()
bool llvm::AccelTableData::operator< (const AccelTableData & Other) const inline
Definition at line 118 of file AccelTable.h.
References order(), and print().
order()
virtual uint64_t llvm::AccelTableData::order () const protected pure virtual
Implemented in llvm::AppleAccelTableStaticTypeData, llvm::AppleAccelTableStaticOffsetData, llvm::AppleAccelTableOffsetData, llvm::DWARF5AccelTableStaticData, and llvm::DWARF5AccelTableData.
Referenced by operator<().
print()
virtual void llvm::AccelTableData::print (raw_ostream & OS) const pure virtual
Implemented in llvm::AppleAccelTableStaticTypeData, llvm::AppleAccelTableStaticOffsetData, llvm::AppleAccelTableTypeData, llvm::AppleAccelTableOffsetData, llvm::DWARF5AccelTableStaticData, and llvm::DWARF5AccelTableData.
Referenced by llvm::AppleAccelTableData::Atom::Atom(), llvm::AccelTableBase::HashData::dump(), llvm::AccelTableBase::dump(), llvm::AppleAccelTableData::Atom::dump(), llvm::DWARF5AccelTableData::DWARF5AccelTableData(), llvm::DWARF5AccelTableStaticData::DWARF5AccelTableStaticData(), llvm::AccelTableBase::getUniqueNameCount(), llvm::AccelTableBase::HashData::HashData(), and operator<().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/AccelTable.h