LLVM: llvm::HexagonBlockRanges::IndexType Class Reference
llvm::HexagonBlockRanges::IndexType Class Reference
#include "Target/Hexagon/HexagonBlockRanges.h"
Public Types
enum : unsigned { None = 0, Entry = 1, Exit = 2, First = 11 }
Public Member Functions
IndexType ()
IndexType (unsigned Idx)
operator unsigned () const
bool operator== (unsigned x) const
bool operator== (IndexType Idx) const
bool operator!= (unsigned x) const
bool operator!= (IndexType Idx) const
IndexType operator++ ()
bool operator< (unsigned Idx) const
bool operator< (IndexType Idx) const
bool operator<= (IndexType Idx) const
Static Public Member Functions
static bool isInstr (IndexType X)
Detailed Description
Definition at line 44 of file HexagonBlockRanges.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
None
Entry
Exit
First
Definition at line 46 of file HexagonBlockRanges.h.
Constructor & Destructor Documentation
IndexType() [1/2]
llvm::HexagonBlockRanges::IndexType::IndexType () inline
Definition at line 53 of file HexagonBlockRanges.h.
IndexType() [2/2]
llvm::HexagonBlockRanges::IndexType::IndexType (unsigned Idx) inline
Definition at line 54 of file HexagonBlockRanges.h.
Member Function Documentation
isInstr()
static bool llvm::HexagonBlockRanges::IndexType::isInstr (IndexType X) inline static
Definition at line 56 of file HexagonBlockRanges.h.
References llvm::None, llvm::operator!=(), llvm::HexagonBlockRanges::RegisterRef::operator<(), llvm::operator<=(), llvm::operator==(), llvm::operator>(), and llvm::operator>=().
operator unsigned()
llvm::HexagonBlockRanges::IndexType::operator unsigned () const inline
Definition at line 174 of file HexagonBlockRanges.h.
References assert().
operator!=() [1/2]
bool llvm::HexagonBlockRanges::IndexType::operator!= (unsigned x) const inline
Definition at line 187 of file HexagonBlockRanges.h.
operator!=() [2/2]
bool llvm::HexagonBlockRanges::IndexType::operator!= (IndexType Idx) const inline
Definition at line 191 of file HexagonBlockRanges.h.
operator++()
HexagonBlockRanges::IndexType llvm::HexagonBlockRanges::IndexType::operator++ () inline
Definition at line 196 of file HexagonBlockRanges.h.
References assert(), and llvm::None.
operator<() [1/2]
bool llvm::HexagonBlockRanges::IndexType::operator< (unsigned Idx) const inline
Definition at line 206 of file HexagonBlockRanges.h.
References llvm::HexagonBlockRanges::RegisterRef::operator<().
operator<() [2/2]
bool llvm::HexagonBlockRanges::IndexType::operator< (IndexType Idx) const inline
Definition at line 210 of file HexagonBlockRanges.h.
References llvm::None.
operator<=()
bool llvm::HexagonBlockRanges::IndexType::operator<= (IndexType Idx) const inline
Definition at line 230 of file HexagonBlockRanges.h.
References IR, llvm::HexagonBlockRanges::RegisterRef::operator<(), llvm::operator<<(), llvm::operator==(), and P.
operator==() [1/2]
bool llvm::HexagonBlockRanges::IndexType::operator== (unsigned x) const inline
Definition at line 179 of file HexagonBlockRanges.h.
operator==() [2/2]
bool llvm::HexagonBlockRanges::IndexType::operator== (IndexType Idx) const inline
Definition at line 183 of file HexagonBlockRanges.h.
The documentation for this class was generated from the following file:
lib/Target/Hexagon/HexagonBlockRanges.h