LLVM: llvm::DWARFDebugLoc Class Reference
llvm::DWARFDebugLoc Class Reference final
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
Classes
struct LocationList
A list of locations that contain one variable.
Public Member Functions
DWARFDebugLoc (DWARFDataExtractor Data)
void dump (raw_ostream &OS, const MCRegisterInfo *RegInfo, const DWARFObject &Obj, DIDumpOptions DumpOpts, Optional< uint64_t > Offset) const
Print the location lists found within the debug_loc section.
Error visitLocationList (uint64_t *Offset, function_ref< bool(const DWARFLocationEntry &)> Callback) const override
Call the user-provided callback for each entry (including the end-of-list entry) in the location list starting at Offset.
Public Member Functions inherited from llvm::DWARFLocationTable
DWARFLocationTable (DWARFDataExtractor Data)
virtual ~DWARFLocationTable ()=default
bool dumpLocationList (uint64_t *Offset, raw_ostream &OS, Optional< object::SectionedAddress > BaseAddr, const MCRegisterInfo *MRI, const DWARFObject &Obj, DWARFUnit *U, DIDumpOptions DumpOpts, unsigned Indent) const
Dump the location list at the given Offset.
Error visitAbsoluteLocationList (uint64_t Offset, Optional< object::SectionedAddress > BaseAddr, std::function< Optional< object::SectionedAddress >(uint32_t)> LookupAddr, function_ref< bool(Expected< DWARFLocationExpression >)> Callback) const
Protected Member Functions
void dumpRawEntry (const DWARFLocationEntry &Entry, raw_ostream &OS, unsigned Indent, DIDumpOptions DumpOpts, const DWARFObject &Obj) const override
Additional Inherited Members
Protected Attributes inherited from llvm::DWARFLocationTable
DWARFDataExtractor Data
Detailed Description
Definition at line 83 of file DWARFDebugLoc.h.
Constructor & Destructor Documentation
DWARFDebugLoc()
llvm::DWARFDebugLoc::DWARFDebugLoc (DWARFDataExtractor Data) inline
Definition at line 102 of file DWARFDebugLoc.h.
References llvm::dump().
Member Function Documentation
dump()
void DWARFDebugLoc::dump (raw_ostream & OS, const MCRegisterInfo * RegInfo, const DWARFObject & Obj, DIDumpOptions DumpOpts, Optional< uint64_t > Offset) const
Print the location lists found within the debug_loc section.
Definition at line 187 of file DWARFDebugLoc.cpp.
References llvm::Data, and llvm::None.
Referenced by llvm::DWARFContext::dump().
dumpRawEntry()
void DWARFDebugLoc::dumpRawEntry (const DWARFLocationEntry & Entry, raw_ostream & OS, unsigned Indent, DIDumpOptions DumpOpts, const DWARFObject & Obj) const override protected virtual
Implements llvm::DWARFLocationTable.
Definition at line 250 of file DWARFDebugLoc.cpp.
References llvm::Data, llvm::DWARFFormValue::dumpAddressSection(), llvm::format_hex(), llvm::raw_ostream::indent(), llvm::DWARFLocationEntry::Kind, llvm_unreachable, llvm::DWARFLocationEntry::SectionIndex, llvm::DWARFLocationEntry::Value0, and llvm::DWARFLocationEntry::Value1.
visitLocationList()
Error DWARFDebugLoc::visitLocationList (uint64_t * Offset, function_ref< bool(const DWARFLocationEntry &)> Callback) const override virtual
Call the user-provided callback for each entry (including the end-of-list entry) in the location list starting at Offset.
The callback can return false to terminate the iteration early. Returns an error if it was unable to parse the entire location list correctly. Upon successful termination Offset will be updated point past the end of the list.
Implements llvm::DWARFLocationTable.
Definition at line 210 of file DWARFDebugLoc.cpp.
References C, llvm::Data, E, llvm::DWARFLocationEntry::Kind, llvm::DWARFLocationEntry::Loc, llvm::DWARFLocationEntry::SectionIndex, llvm::Error::success(), llvm::DataExtractor::Cursor::takeError(), llvm::DataExtractor::Cursor::tell(), llvm::DWARFLocationEntry::Value0, and llvm::DWARFLocationEntry::Value1.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLoc.h
lib/DebugInfo/DWARF/DWARFDebugLoc.cpp