LLVM: llvm::SystemZFrameLowering Class Reference
llvm::SystemZFrameLowering Class Reference
#include "Target/SystemZ/SystemZFrameLowering.h"
Public Member Functions
SystemZFrameLowering ()
bool isFPCloseToIncomingSP () const override
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBII, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
unsigned getRegSpillOffset (unsigned Reg) const
int getOrCreateFramePointerSaveIndex (MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None(), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 19 of file SystemZFrameLowering.h.
Constructor & Destructor Documentation
SystemZFrameLowering()
SystemZFrameLowering::SystemZFrameLowering ()
Definition at line 48 of file SystemZFrameLowering.cpp.
References llvm::array_lengthof(), E, llvm::IndexedMap< T, ToIndexT >::grow(), I, and Reg.
Member Function Documentation
assignCalleeSavedSpillSlots()
bool SystemZFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 78 of file SystemZFrameLowering.cpp.
References llvm::SystemZ::ArgGPRs, assert(), llvm::SystemZMC::CallFrameSize, contains(), llvm::SystemZMC::getFirstReg(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetRegisterInfo::getSpillSize(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR(), llvm::SystemZMC::GR64Regs, llvm::Function::isVarArg(), llvm::SystemZ::NumArgGPRs, Reg, llvm::SystemZMachineFunctionInfo::setRestoreGPRRegs(), llvm::SystemZMachineFunctionInfo::setSpillGPRRegs(), Size, and usePackedStack().
Referenced by isFPCloseToIncomingSP(), and usePackedStack().
determineCalleeSaves()
void SystemZFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 171 of file SystemZFrameLowering.cpp.
References llvm::SystemZ::ArgGPRs, contains(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getLandingPads(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR(), llvm::MachineFrameInfo::hasCalls(), hasFP(), I, llvm::Function::isVarArg(), llvm::SystemZ::NumArgGPRs, Reg, llvm::BitVector::set(), llvm::BitVector::test(), and TRI.
Referenced by isFPCloseToIncomingSP().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator SystemZFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 651 of file SystemZFrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::erase(), getOrCreateFramePointerSaveIndex(), hasReservedCallFrame(), and llvm_unreachable.
Referenced by getFrameIndexReference(), and isFPCloseToIncomingSP().
emitEpilogue()
void SystemZFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 579 of file SystemZFrameLowering.cpp.
References assert(), emitIncrement(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::SystemZMachineFunctionInfo::getRestoreGPRRegs(), llvm::MachineFunction::getSubtarget(), llvm::CallingConv::GHC, llvm_unreachable, and llvm::SystemZ::GPRRegs::LowGPR.
Referenced by isFPCloseToIncomingSP().
emitPrologue()
void SystemZFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 419 of file SystemZFrameLowering.cpp.
References llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::SystemZMC::CallFrameSize, llvm::SystemZMC::CFAOffsetFromInitialSP, contains(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), llvm::RegState::Define, llvm::numbers::e, E, emitIncrement(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineFunction::front(), llvm::MDNode::get(), llvm::Function::getCallingConv(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), getFrameIndexReference(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MCContext::getRegisterInfo(), llvm::SystemZMachineFunctionInfo::getSpillGPRRegs(), llvm::MachineFunction::getSubtarget(), llvm::CallingConv::GHC, llvm::Function::hasFnAttribute(), hasFP(), I, llvm::RegState::Kill, llvm_unreachable, llvm::SystemZ::GPRRegs::LowGPR, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::report_fatal_error(), and llvm::AArch64ISD::STG.
Referenced by isFPCloseToIncomingSP().
getFrameIndexReference()
int SystemZFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
Returns the displacement from the frame register to the stack frame of the specified index, along with the frame register used (in output arg FrameReg).
The offset is returned directly, and the base register is returned via FrameReg.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 640 of file SystemZFrameLowering.cpp.
References llvm::SystemZMC::CallFrameSize, eliminateCallFramePseudoInstr(), and llvm::TargetFrameLowering::getFrameIndexReference().
Referenced by llvm::SystemZRegisterInfo::eliminateFrameIndex(), emitPrologue(), and isFPCloseToIncomingSP().
getOrCreateFramePointerSaveIndex()
int SystemZFrameLowering::getOrCreateFramePointerSaveIndex (MachineFunction & MF) const
Definition at line 668 of file SystemZFrameLowering.cpp.
References llvm::SystemZMC::CallFrameSize, llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFunction::getFrameInfo(), llvm::SystemZMachineFunctionInfo::getFramePointerSaveIndex(), llvm::MachineFunction::getInfo(), and llvm::SystemZMachineFunctionInfo::setFramePointerSaveIndex().
Referenced by eliminateCallFramePseudoInstr(), getRegSpillOffset(), and processFunctionBeforeFrameFinalized().
getRegSpillOffset()
unsigned llvm::SystemZFrameLowering::getRegSpillOffset (unsigned Reg) const inline
Definition at line 56 of file SystemZFrameLowering.h.
References getOrCreateFramePointerSaveIndex(), and Reg.
hasFP()
bool SystemZFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 625 of file SystemZFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::TargetMachine::Options.
Referenced by determineCalleeSaves(), emitPrologue(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getReservedRegs(), isFPCloseToIncomingSP(), and restoreCalleeSavedRegisters().
hasReservedCallFrame()
bool SystemZFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 632 of file SystemZFrameLowering.cpp.
Referenced by eliminateCallFramePseudoInstr(), and isFPCloseToIncomingSP().
isFPCloseToIncomingSP()
bool llvm::SystemZFrameLowering::isFPCloseToIncomingSP () const inline override virtual
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 26 of file SystemZFrameLowering.h.
References assignCalleeSavedSpillSlots(), determineCalleeSaves(), eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), getFrameIndexReference(), hasFP(), hasReservedCallFrame(), MI, processFunctionBeforeFrameFinalized(), restoreCalleeSavedRegisters(), spillCalleeSavedRegisters(), and TRI.
processFunctionBeforeFrameFinalized()
void SystemZFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 358 of file SystemZFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::SystemZMC::CallFrameSize, llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), getOrCreateFramePointerSaveIndex(), I, llvm::max(), and usePackedStack().
Referenced by isFPCloseToIncomingSP(), and restoreCalleeSavedRegisters().
restoreCalleeSavedRegisters()
bool SystemZFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 300 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), llvm::RegState::Define, E, llvm::MachineBasicBlock::end(), llvm::MCInstrInfo::get(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::SystemZMachineFunctionInfo::getRestoreGPRRegs(), llvm::MachineFunction::getSubtarget(), llvm::SystemZ::GPRRegs::GPROffset, hasFP(), llvm::SystemZ::GPRRegs::HighGPR, I, llvm::RegState::ImplicitDefine, llvm::TargetInstrInfo::loadRegFromStackSlot(), llvm::SystemZ::GPRRegs::LowGPR, processFunctionBeforeFrameFinalized(), Reg, and TII.
Referenced by isFPCloseToIncomingSP(), and spillCalleeSavedRegisters().
spillCalleeSavedRegisters()
bool SystemZFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 238 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), addSavedGPR(), llvm::SystemZ::ArgGPRs, assert(), llvm::BuildMI(), contains(), E, llvm::MCInstrInfo::get(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::SystemZMachineFunctionInfo::getSpillGPRRegs(), llvm::MachineFunction::getSubtarget(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR(), llvm::SystemZ::GPRRegs::GPROffset, llvm::SystemZ::GPRRegs::HighGPR, I, llvm::Function::isVarArg(), llvm::SystemZ::GPRRegs::LowGPR, llvm::SystemZ::NumArgGPRs, Reg, restoreCalleeSavedRegisters(), llvm::TargetInstrInfo::storeRegToStackSlot(), and TII.
Referenced by addSavedGPR(), and isFPCloseToIncomingSP().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZFrameLowering.h
lib/Target/SystemZ/SystemZFrameLowering.cpp