LLVM: llvm::PrintModulePass Class Reference
llvm::PrintModulePass Class Reference
Pass for printing a Module as LLVM's text IR assembly.
#include "llvm/IR/IRPrintingPasses.h"
Public Member Functions
PrintModulePass ()
PrintModulePass (raw_ostream &OS, const std::string &Banner="", bool ShouldPreserveUseListOrder=false)
PreservedAnalyses run (Module &M, AnalysisManager< Module > &)
Static Public Member Functions
static StringRef name ()
Detailed Description
Pass for printing a Module as LLVM's text IR assembly.
Note: This pass is for use with the new pass manager. Use the create...Pass functions above to create passes for use with the legacy pass manager.
Definition at line 74 of file IRPrintingPasses.h.
Constructor & Destructor Documentation
PrintModulePass() [1/2]
PrintModulePass::PrintModulePass ()
Definition at line 23 of file IRPrintingPasses.cpp.
PrintModulePass() [2/2]
PrintModulePass::PrintModulePass (raw_ostream & OS, const std::string & Banner = "", bool ShouldPreserveUseListOrder = false)
Definition at line 24 of file IRPrintingPasses.cpp.
Member Function Documentation
name()
static StringRef llvm::PrintModulePass::name () inline static
Definition at line 86 of file IRPrintingPasses.h.
run()
PreservedAnalyses PrintModulePass::run (Module & M, AnalysisManager< Module > &)
Definition at line 29 of file IRPrintingPasses.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::Module::functions(), llvm::isFunctionInPrintList(), and llvm::Module::print().
Referenced by llvm::PrintFunctionPass::run().
The documentation for this class was generated from the following files:
include/llvm/IR/IRPrintingPasses.h
lib/IR/IRPrintingPasses.cpp