LLVM: llvm::DWARFExpression::Operation Class Reference
llvm::DWARFExpression::Operation Class Reference
This class represents an Operation in the Expression.
#include "llvm/DebugInfo/DWARF/DWARFExpression.h"
Classes
struct Description
Description of the encoding of one expression Op.
Public Types
enum Encoding : uint8_t {
Size1 = 0, Size2 = 1, Size4 = 2, Size8 = 3,
SizeLEB = 4, SizeAddr = 5, SizeRefAddr = 6, SizeBlock = 7,
BaseTypeRef = 8, SignBit = 0x80, SignedSize1 = SignBit | Size1, SignedSize2 = SignBit | Size2,
SignedSize4 = SignBit | Size4, SignedSize8 = SignBit | Size8, SignedSizeLEB = SignBit | SizeLEB, SizeNA = 0xFF
}
Size and signedness of expression operations' operands.
enum DwarfVersion : uint8_t {
DwarfNA, Dwarf2 = 2, Dwarf3, Dwarf4,
Dwarf5
}
Public Member Functions
Description & getDescription ()
uint8_t getCode ()
uint64_t getRawOperand (unsigned Idx)
uint64_t getOperandEndOffset (unsigned Idx)
uint64_t getEndOffset ()
bool extract (DataExtractor Data, uint16_t Version, uint8_t AddressSize, uint64_t Offset)
bool isError ()
bool print (raw_ostream &OS, const DWARFExpression *Expr, const MCRegisterInfo *RegInfo, DWARFUnit *U, bool isEH)
bool verify (DWARFUnit *U)
Friends
class DWARFExpression::iterator
Detailed Description
This class represents an Operation in the Expression.
Each operation can have up to 2 oprerands.
An Operation can be in Error state (check with isError()). This means that it couldn't be decoded successfully and if it is the case, all others fields contain undefined values.
Definition at line 32 of file DWARFExpression.h.
Member Enumeration Documentation
DwarfVersion
enum llvm::DWARFExpression::Operation::DwarfVersion : uint8_t
Enumerator
DwarfNA
Serves as a marker for unused entries.
Dwarf2
Dwarf3
Dwarf4
Dwarf5
Definition at line 54 of file DWARFExpression.h.
Encoding
enum llvm::DWARFExpression::Operation::Encoding : uint8_t
Size and signedness of expression operations' operands.
Enumerator
Size1
Size2
Size4
Size8
SizeLEB
SizeAddr
SizeRefAddr
SizeBlock
Preceding operand contains block size.
BaseTypeRef
SignBit
SignedSize1
SignedSize2
SignedSize4
SignedSize8
SignedSizeLEB
SizeNA
Unused operands get this encoding.
Definition at line 35 of file DWARFExpression.h.
Member Function Documentation
extract()
bool llvm::DWARFExpression::Operation::extract (DataExtractor Data, uint16_t Version, uint8_t AddressSize, uint64_t Offset)
Definition at line 123 of file DWARFExpression.cpp.
References assert(), llvm::getOpDesc(), llvm::getRefAddrSize(), llvm::DataExtractor::getSLEB128(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), llvm_unreachable, Operands, Signed, and Size.
Referenced by getEndOffset(), and llvm::DWARFExpression::iterator::operator++().
getCode()
uint8_t llvm::DWARFExpression::Operation::getCode () inline
Definition at line 86 of file DWARFExpression.h.
Referenced by isVariableIndexable().
getDescription()
Description& llvm::DWARFExpression::Operation::getDescription () inline
Definition at line 85 of file DWARFExpression.h.
getEndOffset()
uint64_t llvm::DWARFExpression::Operation::getEndOffset () inline
Definition at line 89 of file DWARFExpression.h.
References llvm::Data, extract(), and llvm::DWARFExpression::Operation::Description::Version.
getOperandEndOffset()
uint64_t llvm::DWARFExpression::Operation::getOperandEndOffset (unsigned Idx) inline
Definition at line 88 of file DWARFExpression.h.
getRawOperand()
uint64_t llvm::DWARFExpression::Operation::getRawOperand (unsigned Idx) inline
Definition at line 87 of file DWARFExpression.h.
isError()
bool llvm::DWARFExpression::Operation::isError () inline
Definition at line 92 of file DWARFExpression.h.
References llvm::lltok::Error, print(), and verify().
Referenced by llvm::DWARFVerifier::handleDebugInfo(), isVariableIndexable(), and llvm::DWARFExpression::iterator::operator++().
print()
bool llvm::DWARFExpression::Operation::print (raw_ostream & OS, const DWARFExpression * Expr, const MCRegisterInfo * RegInfo, DWARFUnit * U, bool isEH)
Definition at line 237 of file DWARFExpression.cpp.
References assert(), llvm::StringRef::empty(), llvm::format(), llvm::DWARFUnit::getDIEForOffset(), llvm::DWARFUnit::getOffset(), llvm::DataExtractor::getU8(), Name, Operands, llvm::dwarf::OperationEncodingString(), llvm::prettyPrintRegisterOp(), Signed, and Size.
Referenced by llvm::DWARFExpression::end(), and isError().
verify()
bool llvm::DWARFExpression::Operation::verify (DWARFUnit * U)
Definition at line 318 of file DWARFExpression.cpp.
References llvm::DWARFUnit::getDIEForOffset(), llvm::DWARFUnit::getOffset(), Operands, and Size.
Referenced by llvm::DWARFExpression::end(), and isError().
Friends And Related Function Documentation
DWARFExpression::iterator
friend class DWARFExpression::iterator friend
Definition at line 76 of file DWARFExpression.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFExpression.h
lib/DebugInfo/DWARF/DWARFExpression.cpp