LLVM: llvm::codeview::SymbolVisitorCallbackPipeline Class Reference
llvm::codeview::SymbolVisitorCallbackPipeline Class Reference
#include "llvm/DebugInfo/CodeView/SymbolVisitorCallbackPipeline.h"
Public Member Functions
SymbolVisitorCallbackPipeline ()=default
Error visitUnknownSymbol (CVSymbol &Record) override
Action to take on unknown symbols. By default, they are ignored.
Error visitSymbolBegin (CVSymbol &Record, uint32_t Offset) override
Paired begin/end actions for all symbols.
Error visitSymbolBegin (CVSymbol &Record) override
Error visitSymbolEnd (CVSymbol &Record) override
void addCallbackToPipeline (SymbolVisitorCallbacks &Callbacks)
Public Member Functions inherited from llvm::codeview::SymbolVisitorCallbacks
virtual ~SymbolVisitorCallbacks ()=default
Detailed Description
Definition at line 20 of file SymbolVisitorCallbackPipeline.h.
Constructor & Destructor Documentation
SymbolVisitorCallbackPipeline()
llvm::codeview::SymbolVisitorCallbackPipeline::SymbolVisitorCallbackPipeline () default
Member Function Documentation
addCallbackToPipeline()
void llvm::codeview::SymbolVisitorCallbackPipeline::addCallbackToPipeline (SymbolVisitorCallbacks & Callbacks) inline
Definition at line 56 of file SymbolVisitorCallbackPipeline.h.
Referenced by llvm::codeview::CVSymbolDumper::dump().
visitSymbolBegin() [1/2]
Error llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolBegin (CVSymbol & Record, uint32_t Offset) inline override virtual
Paired begin/end actions for all symbols.
Receives all record data, including the fixed-length record prefix. visitSymbolBegin() should return the type of the Symbol, or an error if it cannot be determined.
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 32 of file SymbolVisitorCallbackPipeline.h.
References llvm::codeview::EC, and llvm::Error::success().
visitSymbolBegin() [2/2]
Error llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolBegin (CVSymbol & Record) inline override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 40 of file SymbolVisitorCallbackPipeline.h.
References llvm::codeview::EC, and llvm::Error::success().
visitSymbolEnd()
Error llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolEnd (CVSymbol & Record) inline override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 48 of file SymbolVisitorCallbackPipeline.h.
References llvm::codeview::EC, and llvm::Error::success().
visitUnknownSymbol()
Error llvm::codeview::SymbolVisitorCallbackPipeline::visitUnknownSymbol (CVSymbol & Record) inline override virtual
Action to take on unknown symbols. By default, they are ignored.
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 24 of file SymbolVisitorCallbackPipeline.h.
References llvm::codeview::EC, and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolVisitorCallbackPipeline.h