LLVM: llvm::Registry< T > Class Template Reference
llvm::Registry< T > Class Template Reference
A global registry used in conjunction with static constructors to make pluggable components (like targets or garbage collectors) "just work" when linked with an executable.
#include "llvm/Support/Registry.h"
Classes
class Add
A static registration template.
class iterator
Iterators for registry entries.
class node
Node in linked list of entries.
Public Types
typedef T type
typedef SimpleRegistryEntry< T > entry
Static Public Member Functions
static void add_node (node *N)
Add a node to the Registry: this is the interface between the plugin and the executable.
static iterator begin ()
static iterator end ()
static iterator_range< iterator > entries ()
Friends
class node
Detailed Description
template<typename T>
class llvm::Registry< T >
A global registry used in conjunction with static constructors to make pluggable components (like targets or garbage collectors) "just work" when linked with an executable.
Definition at line 44 of file Registry.h.
Member Typedef Documentation
entry
template<typename T > typedef SimpleRegistryEntry<T> llvm::Registry< T >::entry
Definition at line 47 of file Registry.h.
type
template<typename T > typedef T llvm::Registry< T >::type
Definition at line 46 of file Registry.h.
Member Function Documentation
add_node()
template<typename T > static void llvm::Registry< T >::add_node (node * N) static
Add a node to the Registry: this is the interface between the plugin and the executable.
This function is exported by the executable and called by the plugin to add a node to the executable's registry. Therefore it's not defined here to avoid it being instantiated in the plugin and is instead defined in the executable (see LLVM_INSTANTIATE_REGISTRY below).
begin()
template<typename T > static iterator llvm::Registry< T >::begin () static
Referenced by llvm::GCModuleInfo::getGCStrategy(), and llvm::AsmPrinter::isBlockOnlyReachableByFallthrough().
end()
template<typename T > static iterator llvm::Registry< T >::end () inline static
Definition at line 99 of file Registry.h.
Referenced by llvm::GCModuleInfo::getGCStrategy(), and llvm::AsmPrinter::isBlockOnlyReachableByFallthrough().
entries()
template<typename T > static iterator_range<iterator> llvm::Registry< T >::entries () inline static
Definition at line 101 of file Registry.h.
References llvm::sys::path::begin(), llvm::sys::path::end(), and llvm::make_range().
Referenced by llvm::GCModuleInfo::getGCStrategy().
Friends And Related Function Documentation
node
template<typename T > friend class node friend
Definition at line 55 of file Registry.h.
The documentation for this class was generated from the following file:
include/llvm/Support/Registry.h