LLVM: llvm::InstCombineWorklist Class Reference
llvm::InstCombineWorklist Class Reference
InstCombineWorklist - This is the worklist management logic for InstCombine.
#include "llvm/Transforms/InstCombine/InstCombineWorklist.h"
Public Member Functions
InstCombineWorklist ()=default
InstCombineWorklist (InstCombineWorklist &&)=default
InstCombineWorklist & operator= (InstCombineWorklist &&)=default
bool isEmpty () const
void Add (Instruction *I)
Add - Add the specified instruction to the worklist if it isn't already in it.
void AddValue (Value *V)
void AddInitialGroup (ArrayRef< Instruction *> List)
AddInitialGroup - Add the specified batch of stuff in reverse order.
void Remove (Instruction *I)
Instruction * RemoveOne ()
void AddUsersToWorkList (Instruction &I)
AddUsersToWorkList - When an instruction is simplified, add all users of the instruction to the work lists because they might get more simplified now.
void Zap ()
Zap - check that the worklist is empty and nuke the backing store for the map if it is large.
Detailed Description
InstCombineWorklist - This is the worklist management logic for InstCombine.
Definition at line 26 of file InstCombineWorklist.h.
Constructor & Destructor Documentation
InstCombineWorklist() [1/2]
llvm::InstCombineWorklist::InstCombineWorklist () default
InstCombineWorklist() [2/2]
llvm::InstCombineWorklist::InstCombineWorklist (InstCombineWorklist &&) default
Member Function Documentation
Add()
void llvm::InstCombineWorklist::Add (Instruction * I) inline
Add - Add the specified instruction to the worklist if it isn't already in it.
Definition at line 40 of file InstCombineWorklist.h.
References assert(), llvm::dbgs(), llvm::Instruction::getParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorBase::size().
Referenced by AddUsersToWorkList(), AddValue(), combineInstructionsOverFunction(), llvm::InstCombiner::eraseInstFromFunction(), getShiftedValue(), llvm::InstCombiner::InsertNewInstBefore(), and processUMulZExtIdiom().
AddInitialGroup()
void llvm::InstCombineWorklist::AddInitialGroup (ArrayRef< Instruction *> List) inline
AddInitialGroup - Add the specified batch of stuff in reverse order.
which should only be done when the worklist is empty and when the group has no duplicates.
Definition at line 58 of file InstCombineWorklist.h.
References assert(), llvm::dbgs(), llvm::SmallVectorBase::empty(), I, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), llvm::SmallVectorImpl< T >::reserve(), llvm::reverse(), and llvm::ArrayRef< T >::size().
AddUsersToWorkList()
void llvm::InstCombineWorklist::AddUsersToWorkList (Instruction & I) inline
AddUsersToWorkList - When an instruction is simplified, add all users of the instruction to the work lists because they might get more simplified now.
Definition at line 92 of file InstCombineWorklist.h.
References Add(), and llvm::Value::users().
Referenced by llvm::InstCombiner::replaceInstUsesWith().
AddValue()
void llvm::InstCombineWorklist::AddValue (Value * V) inline
Definition at line 50 of file InstCombineWorklist.h.
References Add(), and I.
isEmpty()
bool llvm::InstCombineWorklist::isEmpty () const inline
Definition at line 36 of file InstCombineWorklist.h.
References llvm::SmallVectorBase::empty().
operator=()
InstCombineWorklist& llvm::InstCombineWorklist::operator= (InstCombineWorklist &&) default
Remove()
void llvm::InstCombineWorklist::Remove (Instruction * I) inline
Definition at line 72 of file InstCombineWorklist.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::erase(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by llvm::InstCombiner::eraseInstFromFunction().
RemoveOne()
Instruction* llvm::InstCombineWorklist::RemoveOne () inline
Definition at line 82 of file InstCombineWorklist.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::erase(), I, and llvm::SmallVectorImpl< T >::pop_back_val().
Zap()
void llvm::InstCombineWorklist::Zap () inline
Zap - check that the worklist is empty and nuke the backing store for the map if it is large.
Definition at line 100 of file InstCombineWorklist.h.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty().
The documentation for this class was generated from the following file:
include/llvm/Transforms/InstCombine/InstCombineWorklist.h