LLVM: llvm::WebAssemblyFunctionInfo Class Reference
llvm::WebAssemblyFunctionInfo Class Reference final
This class is derived from MachineFunctionInfo and contains private WebAssembly-specific information for each MachineFunction.
#include "Target/WebAssembly/WebAssemblyMachineFunctionInfo.h"
Public Member Functions
WebAssemblyFunctionInfo (MachineFunction &MF)
~WebAssemblyFunctionInfo () override
void initializeBaseYamlFields (const yaml::WebAssemblyFunctionInfo &YamlMFI)
void addParam (MVT VT)
const std::vector< MVT > & getParams () const
void addResult (MVT VT)
const std::vector< MVT > & getResults () const
void clearParamsAndResults ()
void setNumLocals (size_t NumLocals)
void setLocal (size_t i, MVT VT)
void addLocal (MVT VT)
const std::vector< MVT > & getLocals () const
unsigned getVarargBufferVreg () const
void setVarargBufferVreg (unsigned Reg)
unsigned getBasePointerVreg () const
void setBasePointerVreg (unsigned Reg)
void stackifyVReg (unsigned VReg)
void unstackifyVReg (unsigned VReg)
bool isVRegStackified (unsigned VReg) const
void initWARegs ()
void setWAReg (unsigned VReg, unsigned WAReg)
unsigned getWAReg (unsigned VReg) const
bool isCFGStackified () const
void setCFGStackified (bool Value=true)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Static Public Member Functions
static unsigned getWARegStackId (unsigned Reg)
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Static Public Attributes
static const unsigned UnusedReg = -1u
Detailed Description
This class is derived from MachineFunctionInfo and contains private WebAssembly-specific information for each MachineFunction.
Definition at line 32 of file WebAssemblyMachineFunctionInfo.h.
Constructor & Destructor Documentation
WebAssemblyFunctionInfo()
llvm::WebAssemblyFunctionInfo::WebAssemblyFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 63 of file WebAssemblyMachineFunctionInfo.h.
References llvm::yaml::WebAssemblyFunctionInfo::~WebAssemblyFunctionInfo().
~WebAssemblyFunctionInfo()
WebAssemblyFunctionInfo::~WebAssemblyFunctionInfo () override default
Member Function Documentation
addLocal()
void llvm::WebAssemblyFunctionInfo::addLocal (MVT VT) inline
Definition at line 80 of file WebAssemblyMachineFunctionInfo.h.
addParam()
void llvm::WebAssemblyFunctionInfo::addParam (MVT VT) inline
Definition at line 67 of file WebAssemblyMachineFunctionInfo.h.
addResult()
void llvm::WebAssemblyFunctionInfo::addResult (MVT VT) inline
Definition at line 70 of file WebAssemblyMachineFunctionInfo.h.
clearParamsAndResults()
void llvm::WebAssemblyFunctionInfo::clearParamsAndResults () inline
Definition at line 73 of file WebAssemblyMachineFunctionInfo.h.
getBasePointerVreg()
unsigned llvm::WebAssemblyFunctionInfo::getBasePointerVreg () const inline
Definition at line 89 of file WebAssemblyMachineFunctionInfo.h.
References assert().
getLocals()
const std::vector<MVT>& llvm::WebAssemblyFunctionInfo::getLocals () const inline
Definition at line 81 of file WebAssemblyMachineFunctionInfo.h.
getParams()
const std::vector<MVT>& llvm::WebAssemblyFunctionInfo::getParams () const inline
Definition at line 68 of file WebAssemblyMachineFunctionInfo.h.
Referenced by findStartOfTree().
getResults()
const std::vector<MVT>& llvm::WebAssemblyFunctionInfo::getResults () const inline
Definition at line 71 of file WebAssemblyMachineFunctionInfo.h.
References Results.
Referenced by getDepth().
getVarargBufferVreg()
unsigned llvm::WebAssemblyFunctionInfo::getVarargBufferVreg () const inline
Definition at line 83 of file WebAssemblyMachineFunctionInfo.h.
References assert().
getWAReg()
unsigned llvm::WebAssemblyFunctionInfo::getWAReg (unsigned VReg) const inline
Definition at line 123 of file WebAssemblyMachineFunctionInfo.h.
References assert(), I, and llvm::Register::virtReg2Index().
Referenced by llvm::WebAssemblyMCInstLower::lower(), and llvm::WebAssemblyAsmPrinter::regToString().
getWARegStackId()
static unsigned llvm::WebAssemblyFunctionInfo::getWARegStackId (unsigned Reg) inline static
Definition at line 130 of file WebAssemblyMachineFunctionInfo.h.
References assert().
Referenced by llvm::WebAssemblyInstPrinter::printOperand().
initializeBaseYamlFields()
void WebAssemblyFunctionInfo::initializeBaseYamlFields (const yaml::WebAssemblyFunctionInfo & YamlMFI)
Definition at line 91 of file WebAssemblyMachineFunctionInfo.cpp.
References llvm::yaml::WebAssemblyFunctionInfo::CFGStackified.
initWARegs()
void WebAssemblyFunctionInfo::initWARegs ()
Definition at line 23 of file WebAssemblyMachineFunctionInfo.cpp.
References assert(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineFunction::getRegInfo(), Reg, and UnusedReg.
isCFGStackified()
bool llvm::WebAssemblyFunctionInfo::isCFGStackified () const inline
Definition at line 135 of file WebAssemblyMachineFunctionInfo.h.
References llvm::yaml::WebAssemblyFunctionInfo::CFGStackified.
isVRegStackified()
bool llvm::WebAssemblyFunctionInfo::isVRegStackified (unsigned VReg) const inline
Definition at line 109 of file WebAssemblyMachineFunctionInfo.h.
References I, llvm::BitVector::size(), llvm::BitVector::test(), and llvm::Register::virtReg2Index().
Referenced by llvm::WebAssemblyInstrInfo::commuteInstructionImpl(), findStartOfTree(), llvm::WebAssembly::isChild(), moveAndTeeForMultiUse(), oneUseDominatesOtherUses(), and llvm::WebAssemblyAsmPrinter::regToString().
setBasePointerVreg()
void llvm::WebAssemblyFunctionInfo::setBasePointerVreg (unsigned Reg) inline
Definition at line 93 of file WebAssemblyMachineFunctionInfo.h.
References Reg.
setCFGStackified()
void llvm::WebAssemblyFunctionInfo::setCFGStackified (bool Value = true) inline
Definition at line 136 of file WebAssemblyMachineFunctionInfo.h.
References llvm::computeLegalValueVTs(), llvm::computeSignatureVTs(), F(), llvm::tgtok::In, Results, llvm::signatureFromMVTs(), llvm::SystemZISD::TM, and llvm::valTypesFromMVTs().
setLocal()
void llvm::WebAssemblyFunctionInfo::setLocal (size_t i, MVT VT) inline
Definition at line 79 of file WebAssemblyMachineFunctionInfo.h.
Referenced by findStartOfTree().
setNumLocals()
void llvm::WebAssemblyFunctionInfo::setNumLocals (size_t NumLocals) inline
Definition at line 78 of file WebAssemblyMachineFunctionInfo.h.
References llvm::MVT::i32.
Referenced by findStartOfTree().
setVarargBufferVreg()
void llvm::WebAssemblyFunctionInfo::setVarargBufferVreg (unsigned Reg) inline
Definition at line 87 of file WebAssemblyMachineFunctionInfo.h.
References Reg.
setWAReg()
void llvm::WebAssemblyFunctionInfo::setWAReg (unsigned VReg, unsigned WAReg) inline
Definition at line 117 of file WebAssemblyMachineFunctionInfo.h.
References assert(), I, and llvm::Register::virtReg2Index().
stackifyVReg()
void llvm::WebAssemblyFunctionInfo::stackifyVReg (unsigned VReg) inline
Definition at line 97 of file WebAssemblyMachineFunctionInfo.h.
References assert(), I, llvm::BitVector::resize(), llvm::BitVector::set(), llvm::BitVector::size(), and llvm::Register::virtReg2Index().
Referenced by findStartOfTree(), maybeRewriteToDrop(), moveAndTeeForMultiUse(), moveForSingleUse(), and rematerializeCheapDef().
unstackifyVReg()
void llvm::WebAssemblyFunctionInfo::unstackifyVReg (unsigned VReg) inline
Definition at line 104 of file WebAssemblyMachineFunctionInfo.h.
References I, llvm::BitVector::reset(), llvm::BitVector::size(), and llvm::Register::virtReg2Index().
Referenced by unstackifyVRegsUsedInSplitBB().
Member Data Documentation
UnusedReg
const unsigned llvm::WebAssemblyFunctionInfo::UnusedReg = -1u static
Definition at line 95 of file WebAssemblyMachineFunctionInfo.h.
Referenced by INITIALIZE_PASS(), initWARegs(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::WebAssemblyInstPrinter::printRegName(), and llvm::WebAssemblyAsmPrinter::regToString().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.h
lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.cpp