LLVM: llvm::lto::InputFile::Symbol Class Reference
llvm::lto::InputFile::Symbol Class Reference
The purpose of this class is to only expose the symbol information that an LTO client should need in order to do symbol resolution.
#include "llvm/LTO/LTO.h"
Public Member Functions
Symbol (const irsymtab::Symbol &S)
Detailed Description
The purpose of this class is to only expose the symbol information that an LTO client should need in order to do symbol resolution.
Definition at line 132 of file LTO.h.
Constructor & Destructor Documentation
Symbol()
llvm::lto::InputFile::Symbol::Symbol (const irsymtab::Symbol & S) inline
Definition at line 136 of file LTO.h.
References llvm::irsymtab::Symbol::canBeOmittedFromSymbolTable(), llvm::irsymtab::Symbol::getCOFFWeakExternalFallback(), llvm::irsymtab::Symbol::getComdatIndex(), llvm::irsymtab::Symbol::getCommonAlignment(), llvm::irsymtab::Symbol::getCommonSize(), llvm::irsymtab::Symbol::getIRName(), llvm::irsymtab::Symbol::getName(), llvm::irsymtab::Symbol::getSectionName(), llvm::irsymtab::Symbol::getVisibility(), llvm::irsymtab::Symbol::isCommon(), llvm::irsymtab::Symbol::isExecutable(), llvm::irsymtab::Symbol::isIndirect(), llvm::irsymtab::Symbol::isTLS(), llvm::irsymtab::Symbol::isUndefined(), llvm::irsymtab::Symbol::isUsed(), and llvm::irsymtab::Symbol::isWeak().
The documentation for this class was generated from the following file:
include/llvm/LTO/LTO.h