LLVM: llvm::pdb::SymbolStream Class Reference
llvm::pdb::SymbolStream Class Reference
#include "llvm/DebugInfo/PDB/Native/SymbolStream.h"
Public Member Functions
SymbolStream (std::unique_ptr< msf::MappedBlockStream > Stream)
~SymbolStream ()
Error reload ()
const codeview::CVSymbolArray & getSymbolArray () const
codeview::CVSymbol readRecord (uint32_t Offset) const
iterator_range< codeview::CVSymbolArray::Iterator > getSymbols (bool *HadError) const
Error commit ()
Detailed Description
Definition at line 23 of file SymbolStream.h.
Constructor & Destructor Documentation
SymbolStream()
SymbolStream::SymbolStream (std::unique_ptr< msf::MappedBlockStream > Stream)
Definition at line 22 of file SymbolStream.cpp.
~SymbolStream()
SymbolStream::~SymbolStream ()
Definition at line 25 of file SymbolStream.cpp.
Member Function Documentation
commit()
Error SymbolStream::commit ()
Definition at line 41 of file SymbolStream.cpp.
References llvm::Error::success().
getSymbolArray()
const codeview::CVSymbolArray& llvm::pdb::SymbolStream::getSymbolArray () const inline
Definition at line 29 of file SymbolStream.h.
References getSymbols().
getSymbols()
iterator_range< codeview::CVSymbolArray::Iterator > SymbolStream::getSymbols (bool * HadError) const
Definition at line 37 of file SymbolStream.cpp.
References llvm::VarStreamArray< ValueType, Extractor >::begin(), llvm::VarStreamArray< ValueType, Extractor >::end(), and llvm::make_range().
readRecord()
codeview::CVSymbol SymbolStream::readRecord (uint32_t Offset) const
Definition at line 43 of file SymbolStream.cpp.
References llvm::VarStreamArray< ValueType, Extractor >::at().
Referenced by llvm::pdb::GlobalsStream::findRecordsByName().
reload()
Error SymbolStream::reload ()
Definition at line 27 of file SymbolStream.cpp.
References llvm::BinaryStreamReader::readArray(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/SymbolStream.h
lib/DebugInfo/PDB/Native/SymbolStream.cpp