LLVM: llvm::SmallBitVector::reference Class Reference
llvm::SmallBitVector::reference Class Reference
#include "llvm/ADT/SmallBitVector.h"
Public Member Functions
reference (SmallBitVector &b, unsigned Idx)
reference (const reference &)=default
reference & operator= (reference t)
reference & operator= (bool t)
operator bool () const
Detailed Description
Definition at line 66 of file SmallBitVector.h.
Constructor & Destructor Documentation
reference() [1/2]
llvm::SmallBitVector::reference::reference (SmallBitVector & b, unsigned Idx) inline
Definition at line 71 of file SmallBitVector.h.
Referenced by llvm::SmallBitVector::operator[]().
reference() [2/2]
llvm::SmallBitVector::reference::reference (const reference &) default
Member Function Documentation
operator bool()
llvm::SmallBitVector::reference::operator bool () const inline
Definition at line 88 of file SmallBitVector.h.
References assert(), llvm::SmallBitVector::isSmall(), Size, and llvm::SmallBitVector::SmallBitVector().
operator=() [1/2]
reference& llvm::SmallBitVector::reference::operator= (reference t) inline
Definition at line 75 of file SmallBitVector.h.
operator=() [2/2]
reference& llvm::SmallBitVector::reference::operator= (bool t) inline
Definition at line 80 of file SmallBitVector.h.
References llvm::SmallBitVector::reset(), and llvm::SmallBitVector::set().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallBitVector.h