LLVM: llvm::SplitAnalysis Class Reference
llvm::SplitAnalysis Class Reference
SplitAnalysis - Analyze a LiveInterval, looking for live range splitting opportunities.
#include "CodeGen/SplitKit.h"
Classes
struct BlockInfo
Additional information about basic blocks where the current variable is live.
Public Types
using BlockPtrSet = SmallPtrSet< const MachineBasicBlock *, 16 >
Public Member Functions
SplitAnalysis (const VirtRegMap &vrm, const LiveIntervals &lis, const MachineLoopInfo &mli)
void analyze (const LiveInterval *li)
analyze - set CurLI to the specified interval, and analyze how it may be split.
bool didRepairRange () const
didRepairRange() - Returns true if CurLI was invalid and has been repaired by analyze().
void clear ()
clear - clear all data structures so SplitAnalysis is ready to analyze a new interval.
const LiveInterval & getParent () const
getParent - Return the last analyzed interval.
bool isOriginalEndpoint (SlotIndex Idx) const
isOriginalEndpoint - Return true if the original live range was killed or (re-)defined at Idx.
ArrayRef< SlotIndex > getUseSlots () const
getUseSlots - Return an array of SlotIndexes of instructions using CurLI.
ArrayRef< BlockInfo > getUseBlocks () const
getUseBlocks - Return an array of BlockInfo objects for the basic blocks where CurLI has uses.
unsigned getNumThroughBlocks () const
getNumThroughBlocks - Return the number of through blocks.
bool isThroughBlock (unsigned MBB) const
isThroughBlock - Return true if CurLI is live through MBB without uses.
const BitVector & getThroughBlocks () const
getThroughBlocks - Return the set of through blocks.
unsigned getNumLiveBlocks () const
getNumLiveBlocks - Return the number of blocks where CurLI is live.
unsigned countLiveBlocks (const LiveInterval *li) const
countLiveBlocks - Return the number of blocks where li is live.
bool shouldSplitSingleBlock (const BlockInfo &BI, bool SingleInstrs) const
shouldSplitSingleBlock - Returns true if it would help to create a local live range for the instructions in BI.
SlotIndex getLastSplitPoint (unsigned Num)
MachineBasicBlock::iterator getLastSplitPointIter (MachineBasicBlock *BB)
SlotIndex getFirstSplitPoint (unsigned Num)
Public Attributes
const MachineFunction & MF
const VirtRegMap & VRM
const LiveIntervals & LIS
const MachineLoopInfo & Loops
const TargetInstrInfo & TII
Detailed Description
SplitAnalysis - Analyze a LiveInterval, looking for live range splitting opportunities.
Definition at line 95 of file SplitKit.h.
Member Typedef Documentation
BlockPtrSet
using llvm::SplitAnalysis::BlockPtrSet = SmallPtrSet<const MachineBasicBlock *, 16>
Definition at line 221 of file SplitKit.h.
Constructor & Destructor Documentation
SplitAnalysis()
SplitAnalysis::SplitAnalysis (const VirtRegMap & vrm, const LiveIntervals & lis, const MachineLoopInfo & mli)
Definition at line 151 of file SplitKit.cpp.
Member Function Documentation
analyze()
void SplitAnalysis::analyze (const LiveInterval * li)
analyze - set CurLI to the specified interval, and analyze how it may be split.
Definition at line 354 of file SplitKit.cpp.
References clear().
clear()
void SplitAnalysis::clear ()
clear - clear all data structures so SplitAnalysis is ready to analyze a new interval.
Definition at line 156 of file SplitKit.cpp.
References llvm::array_pod_sort(), assert(), llvm::LiveRange::begin(), llvm::BitVector::clear(), llvm::dbgs(), llvm::VNInfo::def, llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::LiveIntervals::getInstructionIndex(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::LiveIntervals::getMBBFromIndex(), llvm::MachineFunction::getNumBlockIDs(), llvm::MachineFunction::getRegInfo(), llvm::VNInfo::isPHIDef(), llvm::SlotIndex::isSameInstr(), llvm::VNInfo::isUnused(), LIS, LLVM_DEBUG, llvm::SplitAnalysis::BlockInfo::MBB, MF, MRI, llvm::LiveInterval::reg, llvm::BitVector::resize(), shrinkToUses(), llvm::MachineRegisterInfo::use_nodbg_operands(), and llvm::LiveRange::valnos.
Referenced by analyze().
countLiveBlocks()
unsigned SplitAnalysis::countLiveBlocks (const LiveInterval * li) const
countLiveBlocks - Return the number of blocks where li is live.
This is guaranteed to return the same number as getNumLiveBlocks() after calling analyze(li).
Definition at line 316 of file SplitKit.cpp.
References llvm::LiveRange::begin(), llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::LiveIntervals::getMBBFromIndex(), and LIS.
didRepairRange()
bool llvm::SplitAnalysis::didRepairRange () const inline
didRepairRange() - Returns true if CurLI was invalid and has been repaired by analyze().
This really shouldn't happen, but sometimes the coalescer can create live ranges that end in mid-air.
Definition at line 178 of file SplitKit.h.
References clear().
getFirstSplitPoint()
SlotIndex llvm::SplitAnalysis::getFirstSplitPoint (unsigned Num) inline
Definition at line 241 of file SplitKit.h.
References llvm::MachineFunction::getBlockNumbered(), and llvm::InsertPointAnalysis::getFirstInsertPoint().
getLastSplitPoint()
SlotIndex llvm::SplitAnalysis::getLastSplitPoint (unsigned Num) inline
Definition at line 233 of file SplitKit.h.
References llvm::MachineFunction::getBlockNumbered(), and llvm::InsertPointAnalysis::getLastInsertPoint().
getLastSplitPointIter()
MachineBasicBlock::iterator llvm::SplitAnalysis::getLastSplitPointIter (MachineBasicBlock * BB) inline
Definition at line 237 of file SplitKit.h.
References llvm::InsertPointAnalysis::getLastInsertPointIter().
getNumLiveBlocks()
unsigned llvm::SplitAnalysis::getNumLiveBlocks () const inline
getNumLiveBlocks - Return the number of blocks where CurLI is live.
Definition at line 212 of file SplitKit.h.
getNumThroughBlocks()
unsigned llvm::SplitAnalysis::getNumThroughBlocks () const inline
getNumThroughBlocks - Return the number of through blocks.
Definition at line 203 of file SplitKit.h.
getParent()
const LiveInterval& llvm::SplitAnalysis::getParent () const inline
getParent - Return the last analyzed interval.
Definition at line 185 of file SplitKit.h.
getThroughBlocks()
const BitVector& llvm::SplitAnalysis::getThroughBlocks () const inline
getThroughBlocks - Return the set of through blocks.
Definition at line 209 of file SplitKit.h.
getUseBlocks()
ArrayRef<BlockInfo> llvm::SplitAnalysis::getUseBlocks () const inline
getUseBlocks - Return an array of BlockInfo objects for the basic blocks where CurLI has uses.
Definition at line 200 of file SplitKit.h.
getUseSlots()
ArrayRef<SlotIndex> llvm::SplitAnalysis::getUseSlots () const inline
getUseSlots - Return an array of SlotIndexes of instructions using CurLI.
This include both use and def operands, at most one entry per instruction.
Definition at line 196 of file SplitKit.h.
isOriginalEndpoint()
bool SplitAnalysis::isOriginalEndpoint (SlotIndex Idx) const
isOriginalEndpoint - Return true if the original live range was killed or (re-)defined at Idx.
Idx should be the 'def' slot for a normal kill/def, and 'use' for an early-clobber def. This can be used to recognize code inserted by earlier live range splitting.
Definition at line 340 of file SplitKit.cpp.
References assert(), llvm::LiveRange::begin(), llvm::LiveRange::empty(), llvm::sys::path::end(), llvm::LiveRange::end(), llvm::LiveRange::find(), llvm::LiveIntervals::getInterval(), llvm::VirtRegMap::getOriginal(), I, LIS, llvm::LiveInterval::reg, and VRM.
isThroughBlock()
bool llvm::SplitAnalysis::isThroughBlock (unsigned MBB) const inline
isThroughBlock - Return true if CurLI is live through MBB without uses.
Definition at line 206 of file SplitKit.h.
References llvm::BitVector::test().
shouldSplitSingleBlock()
bool SplitAnalysis::shouldSplitSingleBlock (const BlockInfo & BI, bool SingleInstrs) const
shouldSplitSingleBlock - Returns true if it would help to create a local live range for the instructions in BI.
There is normally no benefit to creating a live range for a single instruction, but it does enable register class inflation if the instruction has a restricted register class.
Parameters
BI The block to be isolated.
SingleInstrs True when single instructions should be isolated.
Definition at line 1556 of file SplitKit.cpp.
References llvm::SplitAnalysis::BlockInfo::FirstInstr, llvm::SplitAnalysis::BlockInfo::isOneInstr(), llvm::SplitAnalysis::BlockInfo::LiveIn, and llvm::SplitAnalysis::BlockInfo::LiveOut.
Member Data Documentation
LIS
const LiveIntervals& llvm::SplitAnalysis::LIS
Definition at line 99 of file SplitKit.h.
Referenced by clear(), countLiveBlocks(), and isOriginalEndpoint().
Loops
const MachineLoopInfo& llvm::SplitAnalysis::Loops
Definition at line 100 of file SplitKit.h.
MF
const MachineFunction& llvm::SplitAnalysis::MF
Definition at line 97 of file SplitKit.h.
Referenced by clear().
TII
const TargetInstrInfo& llvm::SplitAnalysis::TII
Definition at line 101 of file SplitKit.h.
VRM
const VirtRegMap& llvm::SplitAnalysis::VRM
Definition at line 98 of file SplitKit.h.
Referenced by isOriginalEndpoint().
The documentation for this class was generated from the following files:
lib/CodeGen/SplitKit.h
lib/CodeGen/SplitKit.cpp