LLVM: llvm::ManagedStringPool Class Reference
llvm::ManagedStringPool Class Reference
ManagedStringPool - The strings allocated from a managed string pool are owned by the string pool and will be deleted together with the managed string pool.
#include "Target/NVPTX/ManagedStringPool.h"
Public Member Functions
ManagedStringPool ()=default
~ManagedStringPool ()
std::string * getManagedString (const char *S)
Detailed Description
ManagedStringPool - The strings allocated from a managed string pool are owned by the string pool and will be deleted together with the managed string pool.
Definition at line 25 of file ManagedStringPool.h.
Constructor & Destructor Documentation
ManagedStringPool()
llvm::ManagedStringPool::ManagedStringPool () default
~ManagedStringPool()
llvm::ManagedStringPool::~ManagedStringPool () inline
Definition at line 31 of file ManagedStringPool.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Member Function Documentation
getManagedString()
std::string* llvm::ManagedStringPool::getManagedString (const char * S) inline
Definition at line 39 of file ManagedStringPool.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::NVPTXRegisterInfo::getName(), llvm::NVPTXTargetLowering::LowerCall(), and VisitGlobalVariableForEmission().
The documentation for this class was generated from the following file:
lib/Target/NVPTX/ManagedStringPool.h