LLVM: llvm::object::WindowsResourceCOFFWriter Class Reference
llvm::object::WindowsResourceCOFFWriter Class Reference
Public Member Functions
WindowsResourceCOFFWriter (COFF::MachineTypes MachineType, const WindowsResourceParser &Parser, Error &E)
std::unique_ptr< MemoryBuffer > write (uint32_t TimeDateStamp)
Detailed Description
Definition at line 601 of file WindowsResource.cpp.
Constructor & Destructor Documentation
WindowsResourceCOFFWriter()
llvm::object::WindowsResourceCOFFWriter::WindowsResourceCOFFWriter (COFF::MachineTypes MachineType, const WindowsResourceParser & Parser, Error & E)
Definition at line 640 of file WindowsResource.cpp.
References llvm::alignTo(), llvm::Data, llvm::WritableMemoryBuffer::getNewMemBuffer(), llvm::object::WindowsResourceParser::TreeNode::getTreeSize(), llvm::COFF::Header16Size, llvm::COFF::RelocationSize, llvm::COFF::SectionSize, llvm::ArrayRef< T >::size(), and llvm::COFF::Symbol16Size.
Member Function Documentation
write()
std::unique_ptr< MemoryBuffer > llvm::object::WindowsResourceCOFFWriter::write (uint32_t TimeDateStamp)
Definition at line 706 of file WindowsResource.cpp.
Referenced by llvm::object::writeWindowsResourceCOFF().
The documentation for this class was generated from the following file:
lib/Object/WindowsResource.cpp