LLVM: llvm::BlockFrequency Class Reference
llvm::BlockFrequency Class Reference
#include "llvm/Support/BlockFrequency.h"
Public Member Functions
BlockFrequency (uint64_t Freq=0)
uint64_t getFrequency () const
Returns the frequency as a fixpoint number scaled by the entry frequency.
BlockFrequency & operator*= (BranchProbability Prob)
Multiplies with a branch probability.
BlockFrequency operator* (BranchProbability Prob) const
BlockFrequency & operator/= (BranchProbability Prob)
Divide by a non-zero branch probability using saturating arithmetic.
BlockFrequency operator/ (BranchProbability Prob) const
BlockFrequency & operator+= (BlockFrequency Freq)
Adds another block frequency using saturating arithmetic.
BlockFrequency operator+ (BlockFrequency Freq) const
BlockFrequency & operator-= (BlockFrequency Freq)
Subtracts another block frequency using saturating arithmetic.
BlockFrequency operator- (BlockFrequency Freq) const
BlockFrequency & operator>>= (const unsigned count)
Shift block frequency to the right by count digits saturating to 1.
bool operator< (BlockFrequency RHS) const
bool operator<= (BlockFrequency RHS) const
bool operator> (BlockFrequency RHS) const
bool operator>= (BlockFrequency RHS) const
bool operator== (BlockFrequency RHS) const
Static Public Member Functions
static uint64_t getMaxFrequency ()
Returns the maximum possible frequency, the saturation value.
Detailed Description
Definition at line 24 of file BlockFrequency.h.
Constructor & Destructor Documentation
BlockFrequency()
llvm::BlockFrequency::BlockFrequency (uint64_t Freq = 0) inline
Definition at line 28 of file BlockFrequency.h.
Member Function Documentation
getFrequency()
uint64_t llvm::BlockFrequency::getFrequency () const inline
Returns the frequency as a fixpoint number scaled by the entry frequency.
Definition at line 35 of file BlockFrequency.h.
References llvm::count(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), and operator>>=().
Referenced by llvm::CFGMST< Edge, BBInfo >::buildEdges(), llvm::RegBankSelect::EdgeInsertPoint::canMaterialize(), computeFunctionSummary(), llvm::createCodeGenPreparePass(), llvm::CodeExtractor::extractCodeRegion(), llvm::RegBankSelect::MBBInsertPoint::frequency(), llvm::RegBankSelect::EdgeInsertPoint::frequency(), llvm::SpillPlacement::Node::getDissentingNeighbors(), getLayoutSuccessorProbThreshold(), llvm::LiveIntervals::getSpillWeight(), giveUpWithRemarks(), hasProfileData(), llvm::InlineFunction(), llvm::BlockFrequencyInfoImplBase::printBlockFreq(), llvm::SplitIndirectBrCriticalEdges(), llvm::JumpThreadingPass::ThreadEdge(), and updateCallerBFI().
getMaxFrequency()
static uint64_t llvm::BlockFrequency::getMaxFrequency () inline static
Returns the maximum possible frequency, the saturation value.
Definition at line 31 of file BlockFrequency.h.
Referenced by llvm::SpillPlacement::Node::addBias(), and getLayoutSuccessorProbThreshold().
operator*()
BlockFrequency BlockFrequency::operator* (BranchProbability Prob) const
Definition at line 23 of file BlockFrequency.cpp.
Referenced by getFrequency().
operator*=()
BlockFrequency & BlockFrequency::operator*= (BranchProbability Prob)
Multiplies with a branch probability.
The computation will never overflow.
Definition at line 18 of file BlockFrequency.cpp.
References llvm::BranchProbability::scale().
Referenced by getFrequency().
operator+()
BlockFrequency BlockFrequency::operator+ (BlockFrequency Freq) const
Definition at line 51 of file BlockFrequency.cpp.
Referenced by getFrequency().
operator+=()
BlockFrequency & BlockFrequency::operator+= (BlockFrequency Freq)
Adds another block frequency using saturating arithmetic.
Definition at line 40 of file BlockFrequency.cpp.
References UINT64_MAX.
Referenced by getFrequency().
operator-()
BlockFrequency BlockFrequency::operator- (BlockFrequency Freq) const
Definition at line 66 of file BlockFrequency.cpp.
Referenced by getFrequency().
operator-=()
BlockFrequency & BlockFrequency::operator-= (BlockFrequency Freq)
Subtracts another block frequency using saturating arithmetic.
Definition at line 57 of file BlockFrequency.cpp.
Referenced by getFrequency().
operator/()
BlockFrequency BlockFrequency::operator/ (BranchProbability Prob) const
Definition at line 34 of file BlockFrequency.cpp.
Referenced by getFrequency().
operator/=()
BlockFrequency & BlockFrequency::operator/= (BranchProbability Prob)
Divide by a non-zero branch probability using saturating arithmetic.
Definition at line 29 of file BlockFrequency.cpp.
References llvm::BranchProbability::scaleByInverse().
Referenced by getFrequency().
operator<()
bool llvm::BlockFrequency::operator< (BlockFrequency RHS) const inline
Definition at line 58 of file BlockFrequency.h.
operator<=()
bool llvm::BlockFrequency::operator<= (BlockFrequency RHS) const inline
Definition at line 62 of file BlockFrequency.h.
operator==()
bool llvm::BlockFrequency::operator== (BlockFrequency RHS) const inline
Definition at line 74 of file BlockFrequency.h.
operator>()
bool llvm::BlockFrequency::operator> (BlockFrequency RHS) const inline
Definition at line 66 of file BlockFrequency.h.
operator>=()
bool llvm::BlockFrequency::operator>= (BlockFrequency RHS) const inline
Definition at line 70 of file BlockFrequency.h.
operator>>=()
BlockFrequency & BlockFrequency::operator>>= (const unsigned count)
Shift block frequency to the right by count digits saturating to 1.
Definition at line 72 of file BlockFrequency.cpp.
References assert(), and llvm::count().
Referenced by getFrequency().
The documentation for this class was generated from the following files:
include/llvm/Support/BlockFrequency.h
lib/Support/BlockFrequency.cpp