LLVM: llvm::DIEEntry Class Reference
llvm::DIEEntry Class Reference
A pointer to another debug information entry.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEEntry ()=delete
DIEEntry (DIE &E)
DIE & getEntry () const
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit debug information entry offset.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
void print (raw_ostream &O) const
Detailed Description
A pointer to another debug information entry.
An instance of this class can also be used as a proxy for a debug information entry not yet defined (ie. types.)
Definition at line 313 of file DIE.h.
Constructor & Destructor Documentation
DIEEntry() [1/2]
llvm::DIEEntry::DIEEntry () delete
DIEEntry() [2/2]
llvm::DIEEntry::DIEEntry (DIE & E) inline explicit
Definition at line 318 of file DIE.h.
Member Function Documentation
EmitValue()
void DIEEntry::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit debug information entry offset.
Definition at line 633 of file DIE.cpp.
References llvm::AsmPrinter::EmitLabelPlusOffset(), llvm::AsmPrinter::EmitULEB128(), llvm_unreachable, and llvm::AsmPrinter::OutStreamer.
getEntry()
DIE& llvm::DIEEntry::getEntry () const inline
Definition at line 320 of file DIE.h.
Referenced by llvm::DwarfUnit::addDIEEntry().
print()
LLVM_DUMP_METHOD void DIEEntry::print (raw_ostream & O) const
Definition at line 693 of file DIE.cpp.
References llvm::format().
SizeOf()
unsigned DIEEntry::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
Definition at line 664 of file DIE.cpp.
References llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, llvm::MCAsmInfo::getCodePointerSize(), llvm::AsmPrinter::getDwarfVersion(), llvm::getULEB128Size(), LLVM_DUMP_METHOD, llvm_unreachable, llvm::AsmPrinter::MAI, and llvm::AsmPrinter::OutStreamer.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp