LLVM: llvm::DITypeRefArray Class Reference
llvm::DITypeRefArray Class Reference
#include "llvm/IR/DebugInfoMetadata.h"
Classes
class iterator
Public Member Functions
DITypeRefArray ()=default
DITypeRefArray (const MDTuple *N)
operator bool () const
operator MDTuple * () const
MDTuple * get () const
MDTuple * operator-> () const
MDTuple & operator* () const
unsigned size () const
DIType * operator[] (unsigned I) const
iterator begin () const
iterator end () const
Detailed Description
Definition at line 63 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DITypeRefArray() [1/2]
llvm::DITypeRefArray::DITypeRefArray () default
DITypeRefArray() [2/2]
llvm::DITypeRefArray::DITypeRefArray (const MDTuple * N) inline
Definition at line 68 of file DebugInfoMetadata.h.
Member Function Documentation
begin()
iterator llvm::DITypeRefArray::begin () const inline
Definition at line 109 of file DebugInfoMetadata.h.
References llvm::DITypeRefArray::iterator::iterator(), and llvm::MDNode::op_begin().
end()
iterator llvm::DITypeRefArray::end () const inline
Definition at line 110 of file DebugInfoMetadata.h.
References llvm::DITypeRefArray::iterator::iterator(), and llvm::MDNode::op_end().
get()
MDTuple* llvm::DITypeRefArray::get () const inline
Definition at line 73 of file DebugInfoMetadata.h.
Referenced by rotateSign().
operator bool()
llvm::DITypeRefArray::operator bool () const inline explicit
Definition at line 70 of file DebugInfoMetadata.h.
operator MDTuple *()
llvm::DITypeRefArray::operator MDTuple * () const inline explicit
Definition at line 71 of file DebugInfoMetadata.h.
operator*()
MDTuple& llvm::DITypeRefArray::operator* () const inline
Definition at line 75 of file DebugInfoMetadata.h.
operator->()
MDTuple* llvm::DITypeRefArray::operator-> () const inline
Definition at line 74 of file DebugInfoMetadata.h.
operator[]()
DIType* llvm::DITypeRefArray::operator[] (unsigned I) const inline
Definition at line 79 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
size()
unsigned llvm::DITypeRefArray::size () const inline
Definition at line 78 of file DebugInfoMetadata.h.
References llvm::MDNode::getNumOperands().
Referenced by llvm::DwarfUnit::applySubprogramAttributes(), llvm::BTFDebug::BTFDebug(), llvm::BTFTypeFuncProto::completeType(), llvm::DwarfUnit::constructSubprogramArguments(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), and dwarfCCToCodeView().
The documentation for this class was generated from the following file:
include/llvm/IR/DebugInfoMetadata.h