LLVM: llvm::MCWasmObjectTargetWriter Class Reference
llvm::MCWasmObjectTargetWriter Class Reference abstract
#include "llvm/MC/MCWasmObjectWriter.h"
Public Member Functions
virtual ~MCWasmObjectTargetWriter ()
virtual Triple::ObjectFormatType getFormat () const
virtual unsigned getRelocType (const MCValue &Target, const MCFixup &Fixup) const =0
Accessors
bool is64Bit () const
bool isEmscripten () const
Public Member Functions inherited from llvm::MCObjectTargetWriter
virtual ~MCObjectTargetWriter ()=default
Static Public Member Functions
static bool classof (const MCObjectTargetWriter *W)
Protected Member Functions
MCWasmObjectTargetWriter (bool Is64Bit_, bool IsEmscripten)
Detailed Description
Definition at line 21 of file MCWasmObjectWriter.h.
Constructor & Destructor Documentation
MCWasmObjectTargetWriter()
MCWasmObjectTargetWriter::MCWasmObjectTargetWriter (bool Is64Bit_, bool IsEmscripten) explicit protected
Definition at line 13 of file MCWasmObjectTargetWriter.cpp.
References ~MCWasmObjectTargetWriter().
~MCWasmObjectTargetWriter()
MCWasmObjectTargetWriter::~MCWasmObjectTargetWriter () virtual default
Referenced by MCWasmObjectTargetWriter().
Member Function Documentation
classof()
static bool llvm::MCWasmObjectTargetWriter::classof (const MCObjectTargetWriter * W) inline static
Definition at line 32 of file MCWasmObjectWriter.h.
References Fixup, llvm::MCObjectTargetWriter::getFormat(), getRelocType(), and llvm::Triple::Wasm.
getFormat()
virtual Triple::ObjectFormatType llvm::MCWasmObjectTargetWriter::getFormat () const inline virtual
Implements llvm::MCObjectTargetWriter.
Definition at line 31 of file MCWasmObjectWriter.h.
References llvm::Triple::Wasm.
getRelocType()
virtual unsigned llvm::MCWasmObjectTargetWriter::getRelocType (const MCValue & Target, const MCFixup & Fixup) const pure virtual
Referenced by classof().
is64Bit()
bool llvm::MCWasmObjectTargetWriter::is64Bit () const inline
Definition at line 41 of file MCWasmObjectWriter.h.
isEmscripten()
bool llvm::MCWasmObjectTargetWriter::isEmscripten () const inline
Definition at line 42 of file MCWasmObjectWriter.h.
References llvm::createWasmObjectWriter().
The documentation for this class was generated from the following files:
include/llvm/MC/MCWasmObjectWriter.h
lib/MC/MCWasmObjectTargetWriter.cpp