LLVM: llvm::PredIteratorCache Class Reference
llvm::PredIteratorCache Class Reference
PredIteratorCache - This class is an extremely trivial cache for predecessor iterator queries.
#include "llvm/IR/PredIteratorCache.h"
Public Member Functions
size_t size (BasicBlock *BB) const
ArrayRef< BasicBlock * > get (BasicBlock *BB)
void clear ()
clear - Remove all information.
Detailed Description
PredIteratorCache - This class is an extremely trivial cache for predecessor iterator queries.
This is useful for code that repeatedly wants the predecessor list for the same blocks.
Definition at line 27 of file PredIteratorCache.h.
Member Function Documentation
clear()
void llvm::PredIteratorCache::clear () inline
clear - Remove all information.
Definition at line 71 of file PredIteratorCache.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
Referenced by llvm::MemoryDependenceResults::invalidateCachedPredecessors().
get()
ArrayRef<BasicBlock *> llvm::PredIteratorCache::get (BasicBlock * BB) inline
Definition at line 66 of file PredIteratorCache.h.
References llvm::makeArrayRef().
Referenced by ComputeLiveInBlocks(), llvm::formLCSSAForInstructions(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::SSAUpdaterBulk::HasValueForBlock(), isSafeToExecuteUnconditionally(), llvm::SSAUpdaterBulk::RewriteAllUses(), and SortNonLocalDepInfoCache().
size()
size_t llvm::PredIteratorCache::size (BasicBlock * BB) const inline
Definition at line 65 of file PredIteratorCache.h.
Referenced by llvm::formLCSSAForInstructions(), and isSafeToExecuteUnconditionally().
The documentation for this class was generated from the following file:
include/llvm/IR/PredIteratorCache.h