LLVM: llvm::VPBlockBase Class Reference
llvm::VPBlockBase Class Reference abstract
VPBlockBase is the building block of the Hierarchical Control-Flow Graph.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using VPBlockTy = enum { VPBasicBlockSC, VPRegionBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
using VPBlocksTy = SmallVectorImpl< VPBlockBase * >
Public Member Functions
virtual ~VPBlockBase ()=default
const std::string & getName () const
void setName (const Twine &newName)
unsigned getVPBlockID () const
VPRegionBlock * getParent ()
const VPRegionBlock * getParent () const
void setParent (VPRegionBlock *P)
const VPBasicBlock * getEntryBasicBlock () const
VPBasicBlock * getEntryBasicBlock ()
const VPBasicBlock * getExitBasicBlock () const
VPBasicBlock * getExitBasicBlock ()
const VPBlocksTy & getSuccessors () const
VPBlocksTy & getSuccessors ()
const VPBlocksTy & getPredecessors () const
VPBlocksTy & getPredecessors ()
VPBlockBase * getSingleSuccessor () const
VPBlockBase * getSinglePredecessor () const
size_t getNumSuccessors () const
size_t getNumPredecessors () const
VPBlockBase * getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
VPBlockBase * getEnclosingBlockWithPredecessors ()
const VPBlocksTy & getHierarchicalSuccessors ()
VPBlockBase * getSingleHierarchicalSuccessor ()
const VPBlocksTy & getHierarchicalPredecessors ()
VPBlockBase * getSingleHierarchicalPredecessor ()
VPValue * getCondBit ()
const VPValue * getCondBit () const
void setCondBit (VPValue *CV)
VPValue * getPredicate ()
const VPValue * getPredicate () const
void setPredicate (VPValue *Pred)
void setOneSuccessor (VPBlockBase *Successor)
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
void setTwoSuccessors (VPBlockBase *IfTrue, VPBlockBase *IfFalse, VPValue *Condition)
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
void setPredecessors (ArrayRef< VPBlockBase *> NewPreds)
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
void clearPredecessors ()
Remove all the predecessor of this block.
void clearSuccessors ()
Remove all the successors of this block and set to null its condition bit.
virtual void execute (struct VPTransformState *State)=0
The method which generates the output IR that correspond to this VPBlockBase, thereby "executing" the VPlan.
void printAsOperand (raw_ostream &OS, bool PrintType) const
void print (raw_ostream &OS) const
bool isLegalToHoistInto ()
Return true if it is legal to hoist instructions into this block.
Static Public Member Functions
static void deleteCFG (VPBlockBase *Entry)
Delete all blocks reachable from a given VPBlockBase, inclusive.
Protected Member Functions
VPBlockBase (const unsigned char SC, const std::string &N)
Friends
class VPBlockUtils
Detailed Description
VPBlockBase is the building block of the Hierarchical Control-Flow Graph.
A VPBlockBase can be either a VPBasicBlock or a VPRegionBlock.
Definition at line 343 of file VPlan.h.
Member Typedef Documentation
VPBlocksTy
using llvm::VPBlockBase::VPBlocksTy = SmallVectorImpl<VPBlockBase *>
Definition at line 405 of file VPlan.h.
VPBlockTy
using llvm::VPBlockBase::VPBlockTy = enum { VPBasicBlockSC, VPRegionBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
Values of this enumeration are kept in the SubclassID field of the VPBlockBase objects. They are used for concrete type identification.
Definition at line 403 of file VPlan.h.
Constructor & Destructor Documentation
VPBlockBase()
llvm::VPBlockBase::VPBlockBase (const unsigned char SC, const std::string & N) inline protected
Definition at line 395 of file VPlan.h.
~VPBlockBase()
virtual llvm::VPBlockBase::~VPBlockBase () virtual default
Member Function Documentation
clearPredecessors()
void llvm::VPBlockBase::clearPredecessors () inline
Remove all the predecessor of this block.
Definition at line 543 of file VPlan.h.
References llvm::SmallVectorImpl< T >::clear().
clearSuccessors()
void llvm::VPBlockBase::clearSuccessors () inline
Remove all the successors of this block and set to null its condition bit.
Definition at line 546 of file VPlan.h.
References llvm::SmallVectorImpl< T >::clear().
deleteCFG()
void VPBlockBase::deleteCFG (VPBlockBase * Entry) static
Delete all blocks reachable from a given VPBlockBase, inclusive.
Definition at line 105 of file VPlan.cpp.
References assert(), CFG, llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::dbgs(), llvm::depth_first(), llvm::BasicBlock::getContext(), getExitBasicBlock(), getHierarchicalPredecessors(), llvm::Value::getName(), getName(), llvm::BasicBlock::getParent(), getSuccessors(), llvm::BasicBlock::getTerminator(), llvm::VPTransformState::CFGState::LastBB, LLVM_DEBUG, llvm::VPTransformState::CFGState::PrevBB, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::VPTransformState::CFGState::VPBB2IRBB, and llvm::VPTransformState::CFGState::VPBBsToFix.
Referenced by llvm::VPlan::~VPlan().
execute()
virtual void llvm::VPBlockBase::execute (struct VPTransformState * State) pure virtual
The method which generates the output IR that correspond to this VPBlockBase, thereby "executing" the VPlan.
Implemented in llvm::VPRegionBlock, and llvm::VPBasicBlock.
getCondBit() [1/2]
VPValue* llvm::VPBlockBase::getCondBit () inline
Returns
the condition bit selecting the successor.
Definition at line 500 of file VPlan.h.
Referenced by llvm::VPBasicBlock::execute(), and llvm::VPlanTransforms::VPInstructionsToVPRecipes().
getCondBit() [2/2]
const VPValue* llvm::VPBlockBase::getCondBit () const inline
Definition at line 502 of file VPlan.h.
getEnclosingBlockWithPredecessors()
VPBlockBase * VPBlockBase::getEnclosingBlockWithPredecessors ()
Returns
the closest enclosing block starting from "this", which has predecessors.
the root enclosing block if all enclosing blocks have no predecessors.
Definition at line 97 of file VPlan.cpp.
References assert(), getEnclosingBlockWithPredecessors(), and llvm::VPRegionBlock::getEntry().
Referenced by getEnclosingBlockWithPredecessors().
getEnclosingBlockWithSuccessors()
VPBlockBase * VPBlockBase::getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
Returns
the closest enclosing block starting from "this", which has successors.
the root enclosing block if all enclosing blocks have no successors.
Definition at line 89 of file VPlan.cpp.
References assert(), getEnclosingBlockWithSuccessors(), and llvm::VPRegionBlock::getExit().
Referenced by getEnclosingBlockWithSuccessors().
getEntryBasicBlock() [1/2]
const VPBasicBlock * VPBlockBase::getEntryBasicBlock () const
Returns
the VPBasicBlock that is the entry of this VPBlockBase, recursively, if the latter is a VPRegionBlock. Otherwise, if this VPBlockBase is a VPBasicBlock, it is returned.
the VPBasicBlock that is the entry of Block, possibly indirectly.
Definition at line 60 of file VPlan.cpp.
References llvm::RegionBase< Tr >::getEntry().
Referenced by llvm::VPlan::dump(), and llvm::VPlan::execute().
getEntryBasicBlock() [2/2]
VPBasicBlock * VPBlockBase::getEntryBasicBlock ()
Definition at line 67 of file VPlan.cpp.
References llvm::RegionBase< Tr >::getEntry().
getExitBasicBlock() [1/2]
const VPBasicBlock * VPBlockBase::getExitBasicBlock () const
Returns
the VPBasicBlock that is the exit of this VPBlockBase, recursively, if the latter is a VPRegionBlock. Otherwise, if this VPBlockBase is a VPBasicBlock, it is returned.
the VPBasicBlock that is the exit of Block, possibly indirectly.
Definition at line 75 of file VPlan.cpp.
References llvm::RegionBase< Tr >::getExit().
Referenced by deleteCFG(), llvm::VPlan::dump(), and llvm::VPBasicBlock::execute().
getExitBasicBlock() [2/2]
VPBasicBlock * VPBlockBase::getExitBasicBlock ()
Definition at line 82 of file VPlan.cpp.
References llvm::RegionBase< Tr >::getExit().
getHierarchicalPredecessors()
const VPBlocksTy& llvm::VPBlockBase::getHierarchicalPredecessors () inline
Returns
the predecessors either attached directly to this VPBlockBase or, if this VPBlockBase is the entry block of a VPRegionBlock and has no predecessors of its own, search recursively for the first enclosing VPRegionBlock that has predecessors and return them. If no such VPRegionBlock exists, return the (empty) predecessors of the topmost VPBlockBase reached.
Definition at line 489 of file VPlan.h.
References getPredecessors().
Referenced by deleteCFG().
getHierarchicalSuccessors()
const VPBlocksTy& llvm::VPBlockBase::getHierarchicalSuccessors () inline
Returns
the successors either attached directly to this VPBlockBase or, if this VPBlockBase is the exit block of a VPRegionBlock and has no successors of its own, search recursively for the first enclosing VPRegionBlock that has successors and return them. If no such VPRegionBlock exists, return the (empty) successors of the topmost VPBlockBase reached.
Definition at line 473 of file VPlan.h.
References getSuccessors().
Referenced by llvm::VPlan::execute().
getName()
const std::string& llvm::VPBlockBase::getName () const inline
Definition at line 409 of file VPlan.h.
References Name.
Referenced by deleteCFG(), llvm::VPlan::dump(), and llvm::VPBasicBlock::execute().
getNumPredecessors()
size_t llvm::VPBlockBase::getNumPredecessors () const inline
Definition at line 454 of file VPlan.h.
References llvm::SmallVectorBase::size().
Referenced by verifyRegion().
getNumSuccessors()
size_t llvm::VPBlockBase::getNumSuccessors () const inline
Definition at line 453 of file VPlan.h.
References llvm::SmallVectorBase::size().
Referenced by llvm::VPBlockUtils::connectBlocks(), and verifyRegion().
getParent() [1/2]
VPRegionBlock* llvm::VPBlockBase::getParent () inline
Definition at line 418 of file VPlan.h.
Referenced by llvm::VPBlockUtils::connectBlocks(), llvm::VPRecipeBase::eraseFromParent(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPBlockUtils::isBackEdge(), llvm::VPRecipeBase::removeFromParent(), and llvm::VPlanVerifier::verifyHierarchicalCFG().
getParent() [2/2]
const VPRegionBlock* llvm::VPBlockBase::getParent () const inline
Definition at line 419 of file VPlan.h.
getPredecessors() [1/2]
const VPBlocksTy& llvm::VPBlockBase::getPredecessors () const inline
Definition at line 438 of file VPlan.h.
Referenced by llvm::GraphTraits< Inverse< VPBlockBase * > >::child_begin(), llvm::GraphTraits< Inverse< VPBlockBase * > >::child_end(), llvm::VPBasicBlock::execute(), getHierarchicalPredecessors(), llvm::VPRegionBlock::setEntry(), and llvm::VPRegionBlock::VPRegionBlock().
getPredecessors() [2/2]
VPBlocksTy& llvm::VPBlockBase::getPredecessors () inline
Definition at line 439 of file VPlan.h.
getPredicate() [1/2]
VPValue* llvm::VPBlockBase::getPredicate () inline
Definition at line 506 of file VPlan.h.
Referenced by llvm::VPlan::dump().
getPredicate() [2/2]
const VPValue* llvm::VPBlockBase::getPredicate () const inline
Definition at line 508 of file VPlan.h.
getSingleHierarchicalPredecessor()
VPBlockBase* llvm::VPBlockBase::getSingleHierarchicalPredecessor () inline
Returns
the hierarchical predecessor of this VPBlockBase if it has a single hierarchical predecessor. Otherwise return a null pointer.
Definition at line 495 of file VPlan.h.
References getSinglePredecessor().
Referenced by llvm::VPBasicBlock::execute().
getSingleHierarchicalSuccessor()
VPBlockBase* llvm::VPBlockBase::getSingleHierarchicalSuccessor () inline
Returns
the hierarchical successor of this VPBlockBase if it has a single hierarchical successor. Otherwise return a null pointer.
Definition at line 479 of file VPlan.h.
References getSingleSuccessor().
Referenced by llvm::VPBasicBlock::execute().
getSinglePredecessor()
VPBlockBase* llvm::VPBlockBase::getSinglePredecessor () const inline
Returns
the predecessor of this VPBlockBase if it has a single predecessor. Otherwise return a null pointer.
Definition at line 449 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T >::begin(), and llvm::SmallVectorBase::size().
Referenced by getSingleHierarchicalPredecessor().
getSingleSuccessor()
VPBlockBase* llvm::VPBlockBase::getSingleSuccessor () const inline
Returns
the successor of this VPBlockBase if it has a single successor. Otherwise return a null pointer.
Definition at line 443 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T >::begin(), and llvm::SmallVectorBase::size().
Referenced by getSingleHierarchicalSuccessor(), and llvm::VPRecipeBuilder::tryToCreateRecipe().
getSuccessors() [1/2]
const VPBlocksTy& llvm::VPBlockBase::getSuccessors () const inline
Definition at line 435 of file VPlan.h.
Referenced by llvm::GraphTraits< VPBlockBase * >::child_begin(), llvm::GraphTraits< const VPBlockBase * >::child_begin(), llvm::GraphTraits< VPBlockBase * >::child_end(), llvm::GraphTraits< const VPBlockBase * >::child_end(), llvm::VPBlockUtils::countSuccessorsNoBE(), deleteCFG(), llvm::VPlan::dump(), getHierarchicalSuccessors(), llvm::VPRecipeBuilder::handleReplication(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPRegionBlock::setExit(), and llvm::VPRegionBlock::VPRegionBlock().
getSuccessors() [2/2]
VPBlocksTy& llvm::VPBlockBase::getSuccessors () inline
Definition at line 436 of file VPlan.h.
getVPBlockID()
unsigned llvm::VPBlockBase::getVPBlockID () const inline
Returns
an ID for the concrete type of this object. This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves.
Definition at line 416 of file VPlan.h.
Referenced by llvm::VPBasicBlock::classof(), and llvm::VPRegionBlock::classof().
isLegalToHoistInto()
bool llvm::VPBlockBase::isLegalToHoistInto () inline
Return true if it is legal to hoist instructions into this block.
Definition at line 569 of file VPlan.h.
print()
void llvm::VPBlockBase::print (raw_ostream & OS) const inline
Definition at line 562 of file VPlan.h.
Referenced by llvm::VPInstruction::print().
printAsOperand()
void llvm::VPBlockBase::printAsOperand (raw_ostream & OS, bool PrintType) const inline
Definition at line 558 of file VPlan.h.
References getName().
Referenced by llvm::VPInstruction::print().
setCondBit()
void llvm::VPBlockBase::setCondBit (VPValue * CV) inline
Definition at line 504 of file VPlan.h.
Referenced by llvm::VPlanTransforms::VPInstructionsToVPRecipes().
setName()
void llvm::VPBlockBase::setName (const Twine & newName) inline
Definition at line 411 of file VPlan.h.
References llvm::Twine::str().
Referenced by llvm::VPRecipeBuilder::tryToCreateRecipe().
setOneSuccessor()
void llvm::VPBlockBase::setOneSuccessor (VPBlockBase * Successor) inline
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
This VPBlockBase is not added as predecessor of Successor. This VPBlockBase must have no successors.
Definition at line 515 of file VPlan.h.
References assert(), and llvm::SmallVectorBase::empty().
Referenced by llvm::VPBlockUtils::insertBlockAfter().
setParent()
void llvm::VPBlockBase::setParent (VPRegionBlock * P) inline
Definition at line 421 of file VPlan.h.
References P.
Referenced by llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPRegionBlock::setEntry(), llvm::VPRegionBlock::setExit(), and llvm::VPRegionBlock::VPRegionBlock().
setPredecessors()
void llvm::VPBlockBase::setPredecessors (ArrayRef< VPBlockBase *> NewPreds) inline
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
This VPBlockBase must have no predecessors. This VPBlockBase is not added as successor of any VPBasicBlock in NewPreds.
Definition at line 536 of file VPlan.h.
References assert(), and llvm::SmallVectorBase::empty().
Referenced by llvm::VPBlockUtils::insertBlockAfter(), and llvm::VPBlockUtils::insertTwoBlocksAfter().
setPredicate()
void llvm::VPBlockBase::setPredicate (VPValue * Pred) inline
Definition at line 510 of file VPlan.h.
setTwoSuccessors()
void llvm::VPBlockBase::setTwoSuccessors (VPBlockBase * IfTrue, VPBlockBase * IfFalse, VPValue * Condition) inline
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
Condition is set as the successor selector. This VPBlockBase is not added as predecessor of IfTrue or IfFalse. This VPBlockBase must have no successors.
Definition at line 524 of file VPlan.h.
References assert(), and llvm::SmallVectorBase::empty().
Referenced by llvm::VPBlockUtils::insertTwoBlocksAfter().
Friends And Related Function Documentation
VPBlockUtils
friend class VPBlockUtils friend
Definition at line 344 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp