LLVM: llvm::PeelingModuloScheduleExpander Class Reference
llvm::PeelingModuloScheduleExpander Class Reference
A reimplementation of ModuloScheduleExpander.
#include "llvm/CodeGen/ModuloSchedule.h"
Public Member Functions
PeelingModuloScheduleExpander (MachineFunction &MF, ModuloSchedule &S, LiveIntervals *LIS)
void expand ()
void validateAgainstModuloScheduleExpander ()
Runs ModuloScheduleExpander and treats it as a golden input to validate aspects of the code generated by PeelingModuloScheduleExpander.
Protected Member Functions
void rewriteKernel ()
Converts BB from the original loop body to the rewritten, pipelined steady-state.
Detailed Description
A reimplementation of ModuloScheduleExpander.
It works by generating a standalone kernel loop and peeling out the prologs and epilogs.
Definition at line 273 of file ModuloSchedule.h.
Constructor & Destructor Documentation
PeelingModuloScheduleExpander()
llvm::PeelingModuloScheduleExpander::PeelingModuloScheduleExpander (MachineFunction & MF, ModuloSchedule & S, LiveIntervals * LIS) inline
Definition at line 309 of file ModuloSchedule.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::count(), expand(), llvm::ModuloSchedule::getStage(), Info, and MI.
Member Function Documentation
expand()
void PeelingModuloScheduleExpander::expand ()
Definition at line 1976 of file ModuloSchedule.cpp.
References llvm::HexagonInstrInfo::analyzeLoopForPipelining(), assert(), Info, LLVM_DEBUG, and TII.
Referenced by llvm::SwingSchedulerDAG::schedule().
rewriteKernel()
void PeelingModuloScheduleExpander::rewriteKernel () protected
Converts BB from the original loop body to the rewritten, pipelined steady-state.
Definition at line 1971 of file ModuloSchedule.cpp.
validateAgainstModuloScheduleExpander()
void PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander ()
Runs ModuloScheduleExpander and treats it as a golden input to validate aspects of the code generated by PeelingModuloScheduleExpander.
Definition at line 1988 of file ModuloSchedule.cpp.
References llvm::AnalysisUsage::addRequired(), assert(), llvm::MachineBasicBlock::begin(), llvm::ModuloScheduleExpander::cleanup(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachineBasicBlock::end(), llvm::errs(), llvm::ModuloScheduleExpander::expand(), llvm::Failed(), llvm::raw_ostream::flush(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::PassRegistry::getPassRegistry(), llvm::ModuloScheduleExpander::getRewrittenKernel(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeModuloScheduleTestPass(), llvm::SmallPtrSetImpl< PtrType >::insert(), MRI, llvm::MachineBasicBlock::print(), and llvm::report_fatal_error().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ModuloSchedule.h
lib/CodeGen/ModuloSchedule.cpp