LLVM: llvm::MachO::ArchitectureSet Class Reference
llvm::MachO::ArchitectureSet Class Reference
#include "llvm/TextAPI/MachO/ArchitectureSet.h"
Classes
class arch_iterator
Public Types
using iterator = arch_iterator< ArchSetType >
using const_iterator = arch_iterator< const ArchSetType >
Public Member Functions
constexpr ArchitectureSet ()=default
constexpr ArchitectureSet (ArchSetType Raw)
ArchitectureSet (Architecture Arch)
ArchitectureSet (const std::vector< Architecture > &Archs)
void set (Architecture Arch)
void clear (Architecture Arch)
bool has (Architecture Arch) const
bool contains (ArchitectureSet Archs) const
size_t count () const
bool empty () const
ArchSetType rawValue () const
bool hasX86 () const
ArchitectureSet operator & (const ArchitectureSet &o)
ArchitectureSet operator| (const ArchitectureSet &o)
ArchitectureSet & operator|= (const ArchitectureSet &o)
ArchitectureSet & operator|= (const Architecture &Arch)
bool operator== (const ArchitectureSet &o) const
bool operator!= (const ArchitectureSet &o) const
bool operator< (const ArchitectureSet &o) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
operator std::string () const
operator std::vector< Architecture > () const
void print (raw_ostream &OS) const
Detailed Description
Definition at line 26 of file ArchitectureSet.h.
Member Typedef Documentation
const_iterator
using llvm::MachO::ArchitectureSet::const_iterator = arch_iterator<const ArchSetType>
Definition at line 140 of file ArchitectureSet.h.
iterator
using llvm::MachO::ArchitectureSet::iterator = arch_iterator<ArchSetType>
Definition at line 139 of file ArchitectureSet.h.
Constructor & Destructor Documentation
ArchitectureSet() [1/4]
constexpr llvm::MachO::ArchitectureSet::ArchitectureSet () default
Referenced by ArchitectureSet(), and llvm::MachO::operator|().
ArchitectureSet() [2/4]
constexpr llvm::MachO::ArchitectureSet::ArchitectureSet (ArchSetType Raw) inline
Definition at line 36 of file ArchitectureSet.h.
ArchitectureSet() [3/4]
llvm::MachO::ArchitectureSet::ArchitectureSet (Architecture Arch) inline
Definition at line 37 of file ArchitectureSet.h.
References ArchitectureSet().
ArchitectureSet() [4/4]
llvm::MachO::ArchitectureSet::ArchitectureSet (const std::vector< Architecture > & Archs)
Definition at line 18 of file ArchitectureSet.cpp.
References llvm::MachO::AK_unknown.
Member Function Documentation
begin() [1/2]
iterator llvm::MachO::ArchitectureSet::begin () inline
Definition at line 142 of file ArchitectureSet.h.
begin() [2/2]
const_iterator llvm::MachO::ArchitectureSet::begin () const inline
Definition at line 145 of file ArchitectureSet.h.
clear()
void llvm::MachO::ArchitectureSet::clear (Architecture Arch) inline
Definition at line 46 of file ArchitectureSet.h.
contains()
bool llvm::MachO::ArchitectureSet::contains (ArchitectureSet Archs) const inline
Definition at line 52 of file ArchitectureSet.h.
References count().
count()
size_t llvm::MachO::ArchitectureSet::count () const
Definition at line 27 of file ArchitectureSet.cpp.
Referenced by contains(), and operator std::string().
empty()
bool llvm::MachO::ArchitectureSet::empty () const inline
Definition at line 58 of file ArchitectureSet.h.
Referenced by operator std::string().
end() [1/2]
iterator llvm::MachO::ArchitectureSet::end () inline
Definition at line 143 of file ArchitectureSet.h.
end() [2/2]
const_iterator llvm::MachO::ArchitectureSet::end () const inline
Definition at line 146 of file ArchitectureSet.h.
References print().
has()
bool llvm::MachO::ArchitectureSet::has (Architecture Arch) const inline
Definition at line 48 of file ArchitectureSet.h.
Referenced by hasX86(), llvm::MachO::Symbol::targets(), and llvm::MachO::InterfaceFile::targets().
hasX86()
bool llvm::MachO::ArchitectureSet::hasX86 () const inline
Definition at line 62 of file ArchitectureSet.h.
References has().
Referenced by llvm::yaml::MappingTraits< T >::NormalizedTBD::synthesizeTargets().
operator &()
ArchitectureSet llvm::MachO::ArchitectureSet::operator& (const ArchitectureSet & o) inline
Definition at line 111 of file ArchitectureSet.h.
operator std::string()
llvm::MachO::ArchitectureSet::operator std::string () const
Definition at line 36 of file ArchitectureSet.cpp.
References count(), empty(), llvm::MachO::getArchitectureName(), and llvm::size().
operator std::vector< Architecture >()
llvm::MachO::ArchitectureSet::operator std::vector< Architecture > () const
Definition at line 51 of file ArchitectureSet.cpp.
References llvm::MachO::AK_unknown.
operator!=()
bool llvm::MachO::ArchitectureSet::operator!= (const ArchitectureSet & o) const inline
Definition at line 133 of file ArchitectureSet.h.
operator<()
bool llvm::MachO::ArchitectureSet::operator< (const ArchitectureSet & o) const inline
Definition at line 137 of file ArchitectureSet.h.
operator==()
bool llvm::MachO::ArchitectureSet::operator== (const ArchitectureSet & o) const inline
Definition at line 129 of file ArchitectureSet.h.
operator|()
ArchitectureSet llvm::MachO::ArchitectureSet::operator| (const ArchitectureSet & o) inline
Definition at line 115 of file ArchitectureSet.h.
operator|=() [1/2]
ArchitectureSet& llvm::MachO::ArchitectureSet::operator|= (const ArchitectureSet & o) inline
Definition at line 119 of file ArchitectureSet.h.
operator|=() [2/2]
ArchitectureSet& llvm::MachO::ArchitectureSet::operator|= (const Architecture & Arch) inline
Definition at line 124 of file ArchitectureSet.h.
print()
void llvm::MachO::ArchitectureSet::print (raw_ostream & OS) const
Definition at line 61 of file ArchitectureSet.cpp.
Referenced by end().
rawValue()
ArchSetType llvm::MachO::ArchitectureSet::rawValue () const inline
Definition at line 60 of file ArchitectureSet.h.
set()
void llvm::MachO::ArchitectureSet::set (Architecture Arch) inline
Definition at line 40 of file ArchitectureSet.h.
References llvm::MachO::AK_unknown.
Referenced by llvm::MachO::mapToArchitectureSet().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/MachO/ArchitectureSet.h
lib/TextAPI/MachO/ArchitectureSet.cpp