LLVM: llvm::pdb::DbiModuleDescriptorBuilder Class Reference
llvm::pdb::DbiModuleDescriptorBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/DbiModuleDescriptorBuilder.h"
Public Member Functions
DbiModuleDescriptorBuilder (StringRef ModuleName, uint32_t ModIndex, msf::MSFBuilder &Msf)
~DbiModuleDescriptorBuilder ()
DbiModuleDescriptorBuilder (const DbiModuleDescriptorBuilder &)=delete
DbiModuleDescriptorBuilder & operator= (const DbiModuleDescriptorBuilder &)=delete
void setPdbFilePathNI (uint32_t NI)
void setObjFileName (StringRef Name)
void setFirstSectionContrib (const SectionContrib &SC)
void addSymbol (codeview::CVSymbol Symbol)
void addSymbolsInBulk (ArrayRef< uint8_t > BulkSymbols)
void addDebugSubsection (std::shared_ptr< codeview::DebugSubsection > Subsection)
void addDebugSubsection (const codeview::DebugSubsectionRecord &SubsectionContents)
uint16_t getStreamIndex () const
StringRef getModuleName () const
StringRef getObjFileName () const
unsigned getModuleIndex () const
ArrayRef< std::string > source_files () const
uint32_t calculateSerializedLength () const
uint32_t getNextSymbolOffset () const
Return the offset within the module symbol stream of the next symbol record passed to addSymbol.
void finalize ()
Error finalizeMsfLayout ()
Error commit (BinaryStreamWriter &ModiWriter, const msf::MSFLayout &MsfLayout, WritableBinaryStreamRef MsfBuffer)
Friends
class DbiStreamBuilder
Detailed Description
Definition at line 37 of file DbiModuleDescriptorBuilder.h.
Constructor & Destructor Documentation
DbiModuleDescriptorBuilder() [1/2]
DbiModuleDescriptorBuilder::DbiModuleDescriptorBuilder (StringRef ModuleName, uint32_t ModIndex, msf::MSFBuilder & Msf)
Definition at line 39 of file DbiModuleDescriptorBuilder.cpp.
References llvm::pdb::ModuleInfoHeader::Mod.
~DbiModuleDescriptorBuilder()
DbiModuleDescriptorBuilder::~DbiModuleDescriptorBuilder ()
Definition at line 47 of file DbiModuleDescriptorBuilder.cpp.
DbiModuleDescriptorBuilder() [2/2]
llvm::pdb::DbiModuleDescriptorBuilder::DbiModuleDescriptorBuilder (const DbiModuleDescriptorBuilder &) delete
Member Function Documentation
addDebugSubsection() [1/2]
void llvm::pdb::DbiModuleDescriptorBuilder::addDebugSubsection (std::shared_ptr< codeview::DebugSubsection > Subsection)
Referenced by commit().
addDebugSubsection() [2/2]
void DbiModuleDescriptorBuilder::addDebugSubsection (const codeview::DebugSubsectionRecord & SubsectionContents)
Definition at line 187 of file DbiModuleDescriptorBuilder.cpp.
addSymbol()
void DbiModuleDescriptorBuilder::addSymbol (codeview::CVSymbol Symbol)
Definition at line 66 of file DbiModuleDescriptorBuilder.cpp.
References addSymbolsInBulk(), and llvm::codeview::CVRecord< Kind >::data().
addSymbolsInBulk()
void DbiModuleDescriptorBuilder::addSymbolsInBulk (ArrayRef< uint8_t > BulkSymbols)
Definition at line 71 of file DbiModuleDescriptorBuilder.cpp.
References llvm::codeview::alignOf(), assert(), llvm::ArrayRef< T >::empty(), and llvm::ArrayRef< T >::size().
Referenced by addSymbol().
calculateSerializedLength()
uint32_t DbiModuleDescriptorBuilder::calculateSerializedLength () const
Definition at line 98 of file DbiModuleDescriptorBuilder.cpp.
References llvm::alignTo(), and llvm::RISCVFenceField::O.
commit()
Error DbiModuleDescriptorBuilder::commit (BinaryStreamWriter & ModiWriter, const msf::MSFLayout & MsfLayout, WritableBinaryStreamRef MsfBuffer)
Definition at line 135 of file DbiModuleDescriptorBuilder.cpp.
References addDebugSubsection(), llvm::codeview::alignOf(), assert(), llvm::BinaryStreamWriter::bytesRemaining(), llvm::COFF::DEBUG_SECTION_MAGIC, llvm::codeview::EC, llvm::msf::MSFBuilder::getAllocator(), llvm::BinaryStreamWriter::getOffset(), llvm::pdb::kInvalidStreamIndex, llvm::pdb::ModuleInfoHeader::ModDiStream, llvm::BinaryStreamWriter::padToAlignment(), llvm::Ref, llvm::pdb::stream_too_long, llvm::Error::success(), llvm::BinaryStreamWriter::writeBytes(), llvm::BinaryStreamWriter::writeCString(), llvm::BinaryStreamWriter::writeInteger(), and llvm::BinaryStreamWriter::writeObject().
finalize()
void DbiModuleDescriptorBuilder::finalize ()
Definition at line 105 of file DbiModuleDescriptorBuilder.cpp.
References llvm::pdb::ModuleInfoHeader::C11Bytes, llvm::pdb::ModuleInfoHeader::C13Bytes, llvm::pdb::ModuleInfoHeader::FileNameOffs, llvm::pdb::ModuleInfoHeader::Flags, getNextSymbolOffset(), llvm::pdb::kInvalidStreamIndex, llvm::pdb::ModuleInfoHeader::Mod, llvm::pdb::ModuleInfoHeader::ModDiStream, llvm::pdb::ModuleInfoHeader::NumFiles, llvm::pdb::ModuleInfoHeader::PdbFilePathNI, llvm::pdb::ModuleInfoHeader::SrcFileNameNI, and llvm::pdb::ModuleInfoHeader::SymBytes.
finalizeMsfLayout()
Error DbiModuleDescriptorBuilder::finalizeMsfLayout ()
Definition at line 122 of file DbiModuleDescriptorBuilder.cpp.
References llvm::msf::MSFBuilder::addStream(), calculateDiSymbolStreamSize(), llvm::pdb::kInvalidStreamIndex, llvm::pdb::ModuleInfoHeader::ModDiStream, and llvm::Error::success().
getModuleIndex()
unsigned llvm::pdb::DbiModuleDescriptorBuilder::getModuleIndex () const inline
Definition at line 65 of file DbiModuleDescriptorBuilder.h.
getModuleName()
StringRef llvm::pdb::DbiModuleDescriptorBuilder::getModuleName () const inline
Definition at line 62 of file DbiModuleDescriptorBuilder.h.
getNextSymbolOffset()
uint32_t llvm::pdb::DbiModuleDescriptorBuilder::getNextSymbolOffset () const inline
Return the offset within the module symbol stream of the next symbol record passed to addSymbol.
Add four to account for the signature.
Definition at line 75 of file DbiModuleDescriptorBuilder.h.
References finalize, llvm::pdb::SourceFiles, and llvm::codeview::Symbols.
Referenced by finalize().
getObjFileName()
StringRef llvm::pdb::DbiModuleDescriptorBuilder::getObjFileName () const inline
Definition at line 63 of file DbiModuleDescriptorBuilder.h.
getStreamIndex()
uint16_t DbiModuleDescriptorBuilder::getStreamIndex () const
Definition at line 49 of file DbiModuleDescriptorBuilder.cpp.
References llvm::pdb::ModuleInfoHeader::ModDiStream.
operator=()
DbiModuleDescriptorBuilder& llvm::pdb::DbiModuleDescriptorBuilder::operator= (const DbiModuleDescriptorBuilder &) delete
setFirstSectionContrib()
void DbiModuleDescriptorBuilder::setFirstSectionContrib (const SectionContrib & SC)
Definition at line 61 of file DbiModuleDescriptorBuilder.cpp.
References llvm::pdb::ModuleInfoHeader::SC, and llvm::PPCISD::SC.
setObjFileName()
void DbiModuleDescriptorBuilder::setObjFileName (StringRef Name)
Definition at line 53 of file DbiModuleDescriptorBuilder.cpp.
References Name.
setPdbFilePathNI()
void DbiModuleDescriptorBuilder::setPdbFilePathNI (uint32_t NI)
Definition at line 57 of file DbiModuleDescriptorBuilder.cpp.
source_files()
ArrayRef<std::string> llvm::pdb::DbiModuleDescriptorBuilder::source_files () const inline
Definition at line 67 of file DbiModuleDescriptorBuilder.h.
References llvm::makeArrayRef(), and llvm::pdb::SourceFiles.
Friends And Related Function Documentation
DbiStreamBuilder
friend class DbiStreamBuilder friend
Definition at line 38 of file DbiModuleDescriptorBuilder.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/DbiModuleDescriptorBuilder.h
lib/DebugInfo/PDB/Native/DbiModuleDescriptorBuilder.cpp