LLVM: llvm::NVPTXGenericMCSymbolRefExpr Class Reference
llvm::NVPTXGenericMCSymbolRefExpr Class Reference
A wrapper for MCSymbolRefExpr that tells the assembly printer that the symbol should be enclosed by generic().
#include "Target/NVPTX/NVPTXMCExpr.h"
Public Member Functions
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Accessors
const MCSymbolRefExpr * getSymbolExpr () const
getOpcode - Get the kind of this expression.
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const NVPTXGenericMCSymbolRefExpr * create (const MCSymbolRefExpr *SymExpr, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary, Constant, SymbolRef, Unary,
Target
}
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
Detailed Description
A wrapper for MCSymbolRefExpr that tells the assembly printer that the symbol should be enclosed by generic().
Definition at line 89 of file NVPTXMCExpr.h.
Member Function Documentation
classof()
static bool llvm::NVPTXGenericMCSymbolRefExpr::classof (const MCExpr * E) inline static
Definition at line 124 of file NVPTXMCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
create()
const NVPTXGenericMCSymbolRefExpr * NVPTXGenericMCSymbolRefExpr::create (const MCSymbolRefExpr * SymExpr, MCContext & Ctx) static
Definition at line 54 of file NVPTXMCExpr.cpp.
Referenced by ConvertDoubleToBytes().
evaluateAsRelocatableImpl()
bool llvm::NVPTXGenericMCSymbolRefExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 113 of file NVPTXMCExpr.h.
findAssociatedFragment()
MCFragment* llvm::NVPTXGenericMCSymbolRefExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 119 of file NVPTXMCExpr.h.
fixELFSymbolsInTLSFixups()
void llvm::NVPTXGenericMCSymbolRefExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 122 of file NVPTXMCExpr.h.
getSymbolExpr()
const MCSymbolRefExpr* llvm::NVPTXGenericMCSymbolRefExpr::getSymbolExpr () const inline
getOpcode - Get the kind of this expression.
Definition at line 108 of file NVPTXMCExpr.h.
References llvm::NVPTXFloatMCExpr::printImpl().
printImpl()
void NVPTXGenericMCSymbolRefExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 59 of file NVPTXMCExpr.cpp.
visitUsedExpr()
void llvm::NVPTXGenericMCSymbolRefExpr::visitUsedExpr (MCStreamer & Streamer) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 118 of file NVPTXMCExpr.h.
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXMCExpr.h
lib/Target/NVPTX/NVPTXMCExpr.cpp