LLVM: llvm::BranchFolder::MBFIWrapper Class Reference
llvm::BranchFolder::MBFIWrapper Class Reference
This class keeps track of branch frequencies of newly created blocks and tail-merged blocks.
#include "CodeGen/BranchFolding.h"
Public Member Functions
MBFIWrapper (const MachineBlockFrequencyInfo &I)
BlockFrequency getBlockFreq (const MachineBasicBlock *MBB) const
void setBlockFreq (const MachineBasicBlock *MBB, BlockFrequency F)
raw_ostream & printBlockFreq (raw_ostream &OS, const MachineBasicBlock *MBB) const
raw_ostream & printBlockFreq (raw_ostream &OS, const BlockFrequency Freq) const
void view (const Twine &Name, bool isSimple=true)
uint64_t getEntryFreq () const
const MachineBlockFrequencyInfo & getMBFI ()
Detailed Description
This class keeps track of branch frequencies of newly created blocks and tail-merged blocks.
Definition at line 138 of file BranchFolding.h.
Constructor & Destructor Documentation
MBFIWrapper()
llvm::BranchFolder::MBFIWrapper::MBFIWrapper (const MachineBlockFrequencyInfo & I) inline
Definition at line 140 of file BranchFolding.h.
References F(), isSimple(), and Name.
Member Function Documentation
getBlockFreq()
BlockFrequency BranchFolder::MBFIWrapper::getBlockFreq (const MachineBasicBlock * MBB) const
Definition at line 505 of file BranchFolding.cpp.
References I.
Referenced by ComputeCommonTailLength().
getEntryFreq()
uint64_t BranchFolder::MBFIWrapper::getEntryFreq () const
Definition at line 536 of file BranchFolding.cpp.
getMBFI()
const MachineBlockFrequencyInfo& llvm::BranchFolder::MBFIWrapper::getMBFI () inline
Definition at line 150 of file BranchFolding.h.
Referenced by ProfitableToMerge(), and salvageDebugInfoFromEmptyBlock().
printBlockFreq() [1/2]
raw_ostream & BranchFolder::MBFIWrapper::printBlockFreq (raw_ostream & OS, const MachineBasicBlock * MBB) const
Definition at line 520 of file BranchFolding.cpp.
printBlockFreq() [2/2]
raw_ostream & BranchFolder::MBFIWrapper::printBlockFreq (raw_ostream & OS, const BlockFrequency Freq) const
Definition at line 526 of file BranchFolding.cpp.
setBlockFreq()
void BranchFolder::MBFIWrapper::setBlockFreq (const MachineBasicBlock * MBB, BlockFrequency F)
Definition at line 514 of file BranchFolding.cpp.
References F().
Referenced by ComputeCommonTailLength().
view()
void BranchFolder::MBFIWrapper::view (const Twine & Name, bool isSimple = true)
Definition at line 531 of file BranchFolding.cpp.
The documentation for this class was generated from the following files:
lib/CodeGen/BranchFolding.h
lib/CodeGen/BranchFolding.cpp