LLVM: llvm::coverage::CounterMappingContext Class Reference
llvm::coverage::CounterMappingContext Class Reference
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Member Functions
CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues=None)
void setCounts (ArrayRef< uint64_t > Counts)
void dump (const Counter &C, raw_ostream &OS) const
void dump (const Counter &C) const
Expected< int64_t > evaluate (const Counter &C) const
Return the number of times that a region of code associated with this counter was executed.
Detailed Description
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
Definition at line 281 of file CoverageMapping.h.
Constructor & Destructor Documentation
CounterMappingContext()
llvm::coverage::CounterMappingContext::CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues = None) inline
Definition at line 286 of file CoverageMapping.h.
Member Function Documentation
dump() [1/2]
void CounterMappingContext::dump (const Counter & C, raw_ostream & OS) const
Definition at line 135 of file CoverageMapping.cpp.
References llvm::consumeError(), llvm::coverage::Counter::CounterValueReference, llvm::dump(), E, llvm::coverage::Counter::Expression, llvm::coverage::Counter::getCounterID(), llvm::coverage::Counter::getExpressionID(), llvm::coverage::Counter::getKind(), llvm::coverage::CounterExpression::Subtract, llvm::Expected< T >::takeError(), and llvm::coverage::Counter::Zero.
dump() [2/2]
void llvm::coverage::CounterMappingContext::dump (const Counter & C) const inline
Definition at line 293 of file CoverageMapping.h.
References llvm::dbgs(), and dump().
Referenced by dump().
evaluate()
Expected< int64_t > CounterMappingContext::evaluate (const Counter & C) const
Return the number of times that a region of code associated with this counter was executed.
Definition at line 165 of file CoverageMapping.cpp.
References llvm::argument_out_of_domain, assert(), llvm::consumeError(), llvm::coverage::Counter::CounterValueReference, E, llvm::StringRef::empty(), llvm::errorCodeToError(), evaluate(), llvm::coverage::Counter::Expression, llvm::coverage::CoverageMappingRecord::Expressions, llvm::coverage::CoverageMappingRecord::Filenames, llvm::coverage::CoverageMappingRecord::FunctionHash, llvm::coverage::CoverageMappingRecord::FunctionName, llvm::coverage::Counter::getCounterID(), llvm::coverage::Counter::getExpressionID(), llvm::getFuncNameWithoutPrefix(), llvm::IndexedInstrProfReader::getFunctionCounts(), llvm::coverage::Counter::getKind(), llvm::hash_combine_range(), llvm::hash_mismatch, llvm::hash_value(), llvm_unreachable, llvm::coverage::malformed, llvm::coverage::CoverageMappingRecord::MappingRegions, llvm::coverage::FunctionRecord::pushRegion(), setCounts(), llvm::coverage::CounterExpression::Subtract, llvm::Error::success(), llvm::InstrProfError::take(), llvm::Expected< T >::takeError(), llvm::unknown_function, and llvm::coverage::Counter::Zero.
Referenced by evaluate().
setCounts()
void llvm::coverage::CounterMappingContext::setCounts (ArrayRef< uint64_t > Counts) inline
Definition at line 290 of file CoverageMapping.h.
References C, and llvm::dump().
Referenced by evaluate().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMapping.h
lib/ProfileData/Coverage/CoverageMapping.cpp