LLVM: llvm::BitstreamCursor Class Reference
llvm::BitstreamCursor Class Reference
This represents a position within a bitcode file, implemented on top of a SimpleBitstreamCursor.
#include "llvm/Bitstream/BitstreamReader.h"
Public Types
enum { AF_DontPopBlockAtEnd = 1, AF_DontAutoprocessAbbrevs = 2 }
Flags that modify the behavior of advance().
Public Member Functions
BitstreamCursor ()=default
BitstreamCursor (ArrayRef< uint8_t > BitcodeBytes)
BitstreamCursor (StringRef BitcodeBytes)
BitstreamCursor (MemoryBufferRef BitcodeBytes)
unsigned getAbbrevIDWidth () const
Return the number of bits used to encode an abbrev #.
Expected< BitstreamEntry > advance (unsigned Flags=0)
Advance the current bitstream, returning the next entry in the stream.
Expected< BitstreamEntry > advanceSkippingSubblocks (unsigned Flags=0)
This is a convenience function for clients that don't expect any subblocks.
Expected< unsigned > ReadCode ()
Expected< unsigned > ReadSubBlockID ()
Having read the ENTER_SUBBLOCK code, read the BlockID for the block.
Error SkipBlock ()
Having read the ENTER_SUBBLOCK abbrevid and a BlockID, skip over the body of this block.
Error EnterSubBlock (unsigned BlockID, unsigned *NumWordsP=nullptr)
Having read the ENTER_SUBBLOCK abbrevid, and enter the block.
bool ReadBlockEnd ()
const BitCodeAbbrev * getAbbrev (unsigned AbbrevID)
Return the abbreviation for the specified AbbrevId.
Expected< unsigned > skipRecord (unsigned AbbrevID)
Read the current record and discard it, returning the code for the record.
Expected< unsigned > readRecord (unsigned AbbrevID, SmallVectorImpl< uint64_t > &Vals, StringRef *Blob=nullptr)
Error ReadAbbrevRecord ()
Expected< Optional< BitstreamBlockInfo > > ReadBlockInfoBlock (bool ReadBlockInfoNames=false)
Read and return a block info block from the bitstream.
void setBlockInfo (BitstreamBlockInfo *BI)
Set the block info to be used by this BitstreamCursor to interpret abbreviated records.
Static Public Attributes
static const size_t MaxChunkSize = sizeof(word_t) * 8
Detailed Description
This represents a position within a bitcode file, implemented on top of a SimpleBitstreamCursor.
Unlike iterators, BitstreamCursors are heavy-weight objects that should not be passed by value.
Definition at line 339 of file BitstreamReader.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Flags that modify the behavior of advance().
Enumerator
AF_DontPopBlockAtEnd
If this flag is used, the advance() method does not automatically pop the block scope when the end of a block is reached.
AF_DontAutoprocessAbbrevs
If this flag is used, abbrev entries are returned just like normal records.
Definition at line 388 of file BitstreamReader.h.
Constructor & Destructor Documentation
BitstreamCursor() [1/4]
llvm::BitstreamCursor::BitstreamCursor () default
BitstreamCursor() [2/4]
llvm::BitstreamCursor::BitstreamCursor (ArrayRef< uint8_t > BitcodeBytes) inline explicit
Definition at line 363 of file BitstreamReader.h.
BitstreamCursor() [3/4]
llvm::BitstreamCursor::BitstreamCursor (StringRef BitcodeBytes) inline explicit
Definition at line 365 of file BitstreamReader.h.
BitstreamCursor() [4/4]
llvm::BitstreamCursor::BitstreamCursor (MemoryBufferRef BitcodeBytes) inline explicit
Definition at line 367 of file BitstreamReader.h.
References llvm::SimpleBitstreamCursor::AtEndOfStream(), llvm::SimpleBitstreamCursor::canSkipToPos(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::SimpleBitstreamCursor::getBitcodeBytes(), llvm::SimpleBitstreamCursor::GetCurrentBitNo(), llvm::SimpleBitstreamCursor::getCurrentByteNo(), llvm::SimpleBitstreamCursor::getPointerToByte(), llvm::SimpleBitstreamCursor::JumpToBit(), llvm::SimpleBitstreamCursor::Read(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), llvm::SimpleBitstreamCursor::SizeInBytes(), and llvm::SimpleBitstreamCursor::skipToEnd().
Member Function Documentation
advance()
Expected<BitstreamEntry> llvm::BitstreamCursor::advance (unsigned Flags = 0) inline
Advance the current bitstream, returning the next entry in the stream.
Definition at line 399 of file BitstreamReader.h.
References llvm::bitc::DEFINE_ABBREV, llvm::bitc::END_BLOCK, llvm::bitc::ENTER_SUBBLOCK, llvm::Expected< T >::get(), llvm::BitstreamEntry::getEndBlock(), llvm::BitstreamEntry::getError(), llvm::BitstreamEntry::getSubBlock(), and llvm::Expected< T >::takeError().
Referenced by llvm::getBitcodeFileContents(), isBlock(), jumpToValueSymbolTable(), parseBlock(), llvm::remarks::BitstreamParserHelper::parseBlockInfoBlock(), and readTriple().
advanceSkippingSubblocks()
Expected<BitstreamEntry> llvm::BitstreamCursor::advanceSkippingSubblocks (unsigned Flags = 0) inline
This is a convenience function for clients that don't expect any subblocks.
This just skips over them automatically.
Definition at line 438 of file BitstreamReader.h.
References llvm::Expected< T >::get(), llvm::BitstreamEntry::Kind, and llvm::BitstreamEntry::SubBlock.
Referenced by llvm::MetadataLoader::MetadataLoaderImpl::upgradeDebugIntrinsics().
EnterSubBlock()
Error BitstreamCursor::EnterSubBlock (unsigned BlockID, unsigned * NumWordsP = nullptr)
Having read the ENTER_SUBBLOCK abbrevid, and enter the block.
Having read the ENTER_SUBBLOCK abbrevid, enter the block.
Definition at line 21 of file BitstreamReader.cpp.
References llvm::SimpleBitstreamCursor::AtEndOfStream(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::bitc::BlockSizeWidth, llvm::bitc::CodeLenWidth, llvm::createStringError(), llvm::Expected< T >::get(), llvm::BitstreamBlockInfo::getBlockInfo(), Info, MaxChunkSize, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SimpleBitstreamCursor::Read(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::SkipToFourByteBoundary(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by parseBlock().
getAbbrev()
const BitCodeAbbrev* llvm::BitstreamCursor::getAbbrev (unsigned AbbrevID) inline
Return the abbreviation for the specified AbbrevId.
Definition at line 524 of file BitstreamReader.h.
References llvm::bitc::FIRST_APPLICATION_ABBREV, and llvm::report_fatal_error().
Referenced by readRecord(), and skipRecord().
getAbbrevIDWidth()
unsigned llvm::BitstreamCursor::getAbbrevIDWidth () const inline
Return the number of bits used to encode an abbrev #.
Definition at line 385 of file BitstreamReader.h.
Referenced by jumpToValueSymbolTable().
ReadAbbrevRecord()
Error BitstreamCursor::ReadAbbrevRecord ()
Definition at line 345 of file BitstreamReader.cpp.
References llvm::Data, E, llvm::BitCodeAbbrevOp::Fixed, llvm::Expected< T >::get(), llvm::BitCodeAbbrevOp::hasEncodingData(), MaxChunkSize, llvm::SimpleBitstreamCursor::Read(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), llvm::report_fatal_error(), llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::BitCodeAbbrevOp::VBR.
ReadBlockEnd()
bool llvm::BitstreamCursor::ReadBlockEnd () inline
Definition at line 499 of file BitstreamReader.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
ReadBlockInfoBlock()
Expected< Optional< BitstreamBlockInfo > > BitstreamCursor::ReadBlockInfoBlock (bool ReadBlockInfoNames = false)
Read and return a block info block from the bitstream.
If an error was encountered, return None.
Parameters
ReadBlockInfoNames Whether to read block/record name information in the BlockInfo block. Only llvm-bcanalyzer uses this.
Definition at line 402 of file BitstreamReader.cpp.
Referenced by llvm::BitcodeAnalyzer::analyze(), llvm::remarks::BitstreamParserHelper::parseBlockInfoBlock(), and llvm::BitcodeAnalyzer::printStats().
ReadCode()
Expected<unsigned> llvm::BitstreamCursor::ReadCode () inline
Definition at line 455 of file BitstreamReader.h.
Referenced by llvm::BitcodeAnalyzer::analyze().
readRecord()
Expected< unsigned > BitstreamCursor::readRecord (unsigned AbbrevID, SmallVectorImpl< uint64_t > & Vals, StringRef * Blob = nullptr)
Definition at line 205 of file BitstreamReader.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::BitCodeAbbrevOp::Array, assert(), llvm::BitCodeAbbrevOp::Blob, llvm::SimpleBitstreamCursor::canSkipToPos(), llvm::BitCodeAbbrevOp::Char6, llvm::BitCodeAbbrevOp::DecodeChar6(), llvm::numbers::e, llvm::BitCodeAbbrevOp::Fixed, llvm::Expected< T >::get(), getAbbrev(), llvm::SimpleBitstreamCursor::GetCurrentBitNo(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::BitCodeAbbrev::getOperandInfo(), llvm::BitCodeAbbrevOp::isEncoding(), llvm::BitCodeAbbrevOp::isLiteral(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SimpleBitstreamCursor::Read(), readAbbreviatedField(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), llvm::report_fatal_error(), llvm::SimpleBitstreamCursor::skipToEnd(), llvm::SimpleBitstreamCursor::SkipToFourByteBoundary(), llvm::Expected< T >::takeError(), llvm::bitc::UNABBREV_RECORD, and llvm::BitCodeAbbrevOp::VBR.
Referenced by parseRecord().
ReadSubBlockID()
Expected<unsigned> llvm::BitstreamCursor::ReadSubBlockID () inline
Having read the ENTER_SUBBLOCK code, read the BlockID for the block.
Definition at line 461 of file BitstreamReader.h.
References llvm::bitc::BlockIDWidth.
Referenced by llvm::BitcodeAnalyzer::analyze().
setBlockInfo()
void llvm::BitstreamCursor::setBlockInfo (BitstreamBlockInfo * BI) inline
Set the block info to be used by this BitstreamCursor to interpret abbreviated records.
Definition at line 553 of file BitstreamReader.h.
Referenced by llvm::BitcodeAnalyzer::analyze(), and llvm::remarks::BitstreamParserHelper::parseBlockInfoBlock().
SkipBlock()
Error llvm::BitstreamCursor::SkipBlock () inline
Having read the ENTER_SUBBLOCK abbrevid and a BlockID, skip over the body of this block.
Definition at line 465 of file BitstreamReader.h.
References llvm::BitstreamBlockInfo::BlockInfo::BlockID, llvm::bitc::BlockSizeWidth, llvm::bitc::CodeLenWidth, llvm::createStringError(), llvm::Expected< T >::get(), llvm::Error::success(), and llvm::Expected< T >::takeError().
skipRecord()
Expected< unsigned > BitstreamCursor::skipRecord (unsigned AbbrevID)
Read the current record and discard it, returning the code for the record.
skipRecord - Read the current record and discard it.
Definition at line 92 of file BitstreamReader.cpp.
References llvm::BitCodeAbbrevOp::Array, assert(), llvm::BitCodeAbbrevOp::Blob, llvm::createStringError(), llvm::numbers::e, llvm::BitCodeAbbrevOp::Fixed, llvm::Expected< T >::get(), getAbbrev(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::BitCodeAbbrev::getOperandInfo(), llvm::BitCodeAbbrevOp::isLiteral(), MaxChunkSize, readAbbreviatedField(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), llvm::report_fatal_error(), llvm::Expected< T >::takeError(), and llvm::bitc::UNABBREV_RECORD.
Referenced by llvm::MetadataLoader::MetadataLoaderImpl::upgradeDebugIntrinsics().
Member Data Documentation
MaxChunkSize
const size_t llvm::BitstreamCursor::MaxChunkSize = sizeof(word_t) * 8 static
Definition at line 360 of file BitstreamReader.h.
Referenced by EnterSubBlock(), readAbbreviatedField(), ReadAbbrevRecord(), and skipRecord().
The documentation for this class was generated from the following files:
include/llvm/Bitstream/BitstreamReader.h
lib/Bitstream/Reader/BitstreamReader.cpp