LLVM: llvm::object::ResourceEntryRef Class Reference
llvm::object::ResourceEntryRef Class Reference
#include "llvm/Object/WindowsResource.h"
Public Member Functions
Error moveNext (bool &End)
bool checkTypeString () const
ArrayRef< UTF16 > getTypeString () const
uint16_t getTypeID () const
bool checkNameString () const
ArrayRef< UTF16 > getNameString () const
uint16_t getNameID () const
uint16_t getDataVersion () const
uint16_t getLanguage () const
uint16_t getMemoryFlags () const
uint16_t getMajorVersion () const
uint16_t getMinorVersion () const
uint32_t getCharacteristics () const
ArrayRef< uint8_t > getData () const
Friends
class WindowsResource
Detailed Description
Definition at line 98 of file WindowsResource.h.
Member Function Documentation
checkNameString()
bool llvm::object::ResourceEntryRef::checkNameString () const inline
Definition at line 104 of file WindowsResource.h.
Referenced by llvm::object::WindowsResourceParser::cleanUpManifests(), and llvm::object::makeDuplicateResourceError().
checkTypeString()
bool llvm::object::ResourceEntryRef::checkTypeString () const inline
Definition at line 101 of file WindowsResource.h.
Referenced by llvm::object::WindowsResourceParser::cleanUpManifests(), and llvm::object::makeDuplicateResourceError().
getCharacteristics()
uint32_t llvm::object::ResourceEntryRef::getCharacteristics () const inline
Definition at line 112 of file WindowsResource.h.
getData()
ArrayRef<uint8_t> llvm::object::ResourceEntryRef::getData () const inline
Definition at line 113 of file WindowsResource.h.
References llvm::Data.
getDataVersion()
uint16_t llvm::object::ResourceEntryRef::getDataVersion () const inline
Definition at line 107 of file WindowsResource.h.
getLanguage()
uint16_t llvm::object::ResourceEntryRef::getLanguage () const inline
Definition at line 108 of file WindowsResource.h.
Referenced by llvm::object::WindowsResourceParser::cleanUpManifests(), and llvm::object::makeDuplicateResourceError().
getMajorVersion()
uint16_t llvm::object::ResourceEntryRef::getMajorVersion () const inline
Definition at line 110 of file WindowsResource.h.
getMemoryFlags()
uint16_t llvm::object::ResourceEntryRef::getMemoryFlags () const inline
Definition at line 109 of file WindowsResource.h.
getMinorVersion()
uint16_t llvm::object::ResourceEntryRef::getMinorVersion () const inline
Definition at line 111 of file WindowsResource.h.
getNameID()
uint16_t llvm::object::ResourceEntryRef::getNameID () const inline
Definition at line 106 of file WindowsResource.h.
Referenced by llvm::object::WindowsResourceParser::cleanUpManifests(), and llvm::object::makeDuplicateResourceError().
getNameString()
ArrayRef<UTF16> llvm::object::ResourceEntryRef::getNameString () const inline
Definition at line 105 of file WindowsResource.h.
References Name.
Referenced by llvm::object::makeDuplicateResourceError().
getTypeID()
uint16_t llvm::object::ResourceEntryRef::getTypeID () const inline
Definition at line 103 of file WindowsResource.h.
Referenced by llvm::object::WindowsResourceParser::cleanUpManifests(), and llvm::object::makeDuplicateResourceError().
getTypeString()
ArrayRef<UTF16> llvm::object::ResourceEntryRef::getTypeString () const inline
Definition at line 102 of file WindowsResource.h.
Referenced by llvm::object::makeDuplicateResourceError().
moveNext()
Error llvm::object::ResourceEntryRef::moveNext (bool & End)
Definition at line 88 of file WindowsResource.cpp.
Friends And Related Function Documentation
WindowsResource
friend class WindowsResource friend
Definition at line 116 of file WindowsResource.h.
The documentation for this class was generated from the following files:
include/llvm/Object/WindowsResource.h
lib/Object/WindowsResource.cpp