LLVM: llvm::orc::IRSpeculationLayer Class Reference
llvm::orc::IRSpeculationLayer Class Reference
#include "llvm/ExecutionEngine/Orc/Speculation.h"
Public Types
using IRlikiesStrRef = Optional< DenseMap< StringRef, DenseSet< StringRef > >>
using ResultEval = std::function< IRlikiesStrRef(Function &)>
using TargetAndLikelies = DenseMap< SymbolStringPtr, SymbolNameSet >
Public Member Functions
IRSpeculationLayer (ExecutionSession &ES, IRCompileLayer &BaseLayer, Speculator &Spec, MangleAndInterner &Mangle, ResultEval Interpreter)
void emit (MaterializationResponsibility R, ThreadSafeModule TSM)
Emit should materialize the given IR.
Public Member Functions inherited from llvm::orc::IRLayer
IRLayer (ExecutionSession &ES, const IRMaterializationUnit::ManglingOptions *&MO)
virtual ~IRLayer ()
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this layer.
const IRMaterializationUnit::ManglingOptions *& getManglingOptions () const
Get the mangling options for this layer.
void setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit)
Sets the CloneToNewContextOnEmit flag (false by default).
bool getCloneToNewContextOnEmit () const
Returns the current value of the CloneToNewContextOnEmit flag.
virtual Error add (JITDylib &JD, ThreadSafeModule TSM, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Detailed Description
Definition at line 176 of file Speculation.h.
Member Typedef Documentation
IRlikiesStrRef
using llvm::orc::IRSpeculationLayer::IRlikiesStrRef = Optional<DenseMap<StringRef, DenseSet<StringRef> >>
Definition at line 178 of file Speculation.h.
ResultEval
using llvm::orc::IRSpeculationLayer::ResultEval = std::function<IRlikiesStrRef(Function &)>
Definition at line 179 of file Speculation.h.
TargetAndLikelies
using llvm::orc::IRSpeculationLayer::TargetAndLikelies = DenseMap<SymbolStringPtr, SymbolNameSet>
Definition at line 180 of file Speculation.h.
Constructor & Destructor Documentation
IRSpeculationLayer()
llvm::orc::IRSpeculationLayer::IRSpeculationLayer (ExecutionSession & ES, IRCompileLayer & BaseLayer, Speculator & Spec, MangleAndInterner & Mangle, ResultEval Interpreter) inline
Definition at line 182 of file Speculation.h.
References assert(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Member Function Documentation
emit()
void llvm::orc::IRSpeculationLayer::emit (MaterializationResponsibility R, ThreadSafeModule TSM) virtual
Emit should materialize the given IR.
Implements llvm::orc::IRLayer.
Definition at line 61 of file Speculation.cpp.
References assert(), llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::StructType::create(), llvm::IRBuilder< T, Inserter >::CreateBr(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateCondBr(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::orc::ThreadSafeContext::getContext(), llvm::orc::ThreadSafeModule::getContext(), llvm::Module::getContext(), llvm::Module::getFunctionList(), llvm::IRBuilderBase::GetInsertBlock(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::Type::getPointerTo(), llvm::orc::MaterializationResponsibility::getTargetJITDylib(), llvm::Type::getVoidTy(), llvm::GlobalValue::Local, llvm::Align::None(), llvm::GlobalObject::setAlignment(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::orc::ThreadSafeModule::withModuleDo().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Speculation.h
lib/ExecutionEngine/Orc/Speculation.cpp