LLVM: llvm::XCoreTargetStreamer Class Reference
llvm::XCoreTargetStreamer Class Reference abstract
#include "Target/XCore/XCoreTargetStreamer.h"
Public Member Functions
XCoreTargetStreamer (MCStreamer &S)
~XCoreTargetStreamer () override
virtual void emitCCTopData (StringRef Name)=0
virtual void emitCCTopFunction (StringRef Name)=0
virtual void emitCCBottomData (StringRef Name)=0
virtual void emitCCBottomFunction (StringRef Name)=0
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 15 of file XCoreTargetStreamer.h.
Constructor & Destructor Documentation
XCoreTargetStreamer()
XCoreTargetStreamer::XCoreTargetStreamer (MCStreamer & S)
Definition at line 77 of file XCoreMCTargetDesc.cpp.
References emitCCBottomData(), emitCCBottomFunction(), emitCCTopData(), emitCCTopFunction(), Name, and ~XCoreTargetStreamer().
~XCoreTargetStreamer()
XCoreTargetStreamer::~XCoreTargetStreamer () override default
Referenced by XCoreTargetStreamer().
Member Function Documentation
emitCCBottomData()
virtual void llvm::XCoreTargetStreamer::emitCCBottomData (StringRef Name) pure virtual
Referenced by XCoreTargetStreamer().
emitCCBottomFunction()
virtual void llvm::XCoreTargetStreamer::emitCCBottomFunction (StringRef Name) pure virtual
Referenced by XCoreTargetStreamer().
emitCCTopData()
virtual void llvm::XCoreTargetStreamer::emitCCTopData (StringRef Name) pure virtual
Referenced by XCoreTargetStreamer().
emitCCTopFunction()
virtual void llvm::XCoreTargetStreamer::emitCCTopFunction (StringRef Name) pure virtual
Referenced by XCoreTargetStreamer().
The documentation for this class was generated from the following files:
lib/Target/XCore/XCoreTargetStreamer.h
lib/Target/XCore/MCTargetDesc/XCoreMCTargetDesc.cpp