LLVM: llvm::PrettyStackTraceProgram Class Reference
llvm::PrettyStackTraceProgram Class Reference
PrettyStackTraceProgram - This object prints a specified program arguments to the stream as the stack trace when a crash occurs.
#include "llvm/Support/PrettyStackTrace.h"
Public Member Functions
PrettyStackTraceProgram (int argc, const char *const *argv)
void print (raw_ostream &OS) const override
print - Emit information about this stack frame to OS.
Public Member Functions inherited from llvm::PrettyStackTraceEntry
PrettyStackTraceEntry ()
virtual ~PrettyStackTraceEntry ()
const PrettyStackTraceEntry * getNextEntry () const
getNextEntry - Return the next entry in the list of frames.
Detailed Description
PrettyStackTraceProgram - This object prints a specified program arguments to the stream as the stack trace when a crash occurs.
Definition at line 84 of file PrettyStackTrace.h.
Constructor & Destructor Documentation
PrettyStackTraceProgram()
llvm::PrettyStackTraceProgram::PrettyStackTraceProgram (int argc, const char *const * argv) inline
Definition at line 88 of file PrettyStackTrace.h.
References llvm::EnablePrettyStackTrace(), llvm::PrettyStackTraceEntry::print(), llvm::RestorePrettyStackState(), and llvm::SavePrettyStackState().
Member Function Documentation
print()
void PrettyStackTraceProgram::print (raw_ostream & OS) const override virtual
print - Emit information about this stack frame to OS.
Implements llvm::PrettyStackTraceEntry.
Definition at line 238 of file PrettyStackTrace.cpp.
References llvm::numbers::e.
The documentation for this class was generated from the following files:
include/llvm/Support/PrettyStackTrace.h
lib/Support/PrettyStackTrace.cpp