LLVM: llvm::DwarfStringPool Class Reference
llvm::DwarfStringPool Class Reference
#include "CodeGen/AsmPrinter/DwarfStringPool.h"
Public Types
using EntryRef = DwarfStringPoolEntryRef
Public Member Functions
DwarfStringPool (BumpPtrAllocator &A, AsmPrinter &Asm, StringRef Prefix)
void emitStringOffsetsTableHeader (AsmPrinter &Asm, MCSection *OffsetSection, MCSymbol *StartSym)
void emit (AsmPrinter &Asm, MCSection *StrSection, MCSection *OffsetSection=nullptr, bool UseRelativeOffsets=false)
bool empty () const
unsigned size () const
unsigned getNumIndexedStrings () const
EntryRef getEntry (AsmPrinter &Asm, StringRef Str)
Get a reference to an entry in the string pool.
EntryRef getIndexedEntry (AsmPrinter &Asm, StringRef Str)
Same as getEntry, except that you can use EntryRef::getIndex to obtain a unique ID of this entry (e.g., for use in indexed forms like DW_FORM_strx).
Detailed Description
Definition at line 26 of file DwarfStringPool.h.
Member Typedef Documentation
EntryRef
using llvm::DwarfStringPool::EntryRef = DwarfStringPoolEntryRef
Definition at line 38 of file DwarfStringPool.h.
Constructor & Destructor Documentation
DwarfStringPool()
DwarfStringPool::DwarfStringPool (BumpPtrAllocator & A, AsmPrinter & Asm, StringRef Prefix)
Definition at line 21 of file DwarfStringPool.cpp.
References llvm::HexStyle::Asm, assert(), llvm::AsmPrinter::createTempSymbol(), I, llvm::DwarfStringPoolEntry::NotIndexed, and llvm::StringRef::size().
Member Function Documentation
emit()
void DwarfStringPool::emit (AsmPrinter & Asm, MCSection * StrSection, MCSection * OffsetSection = nullptr, bool UseRelativeOffsets = false)
Definition at line 77 of file DwarfStringPool.cpp.
References assert(), B, E, llvm::StringMapEntryStorage< ValueTy >::getValue(), llvm::DwarfStringPoolEntry::Offset, llvm::AsmPrinter::OutStreamer, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::sort().
Referenced by llvm::DwarfFile::emitStrings().
emitStringOffsetsTableHeader()
void DwarfStringPool::emitStringOffsetsTableHeader (AsmPrinter & Asm, MCSection * OffsetSection, MCSymbol * StartSym)
Definition at line 55 of file DwarfStringPool.cpp.
References llvm::AsmPrinter::emitInt16(), llvm::AsmPrinter::emitInt32(), llvm::AsmPrinter::getDwarfVersion(), getNumIndexedStrings(), and llvm::AsmPrinter::OutStreamer.
Referenced by llvm::DwarfDebug::endFunctionImpl().
empty()
bool llvm::DwarfStringPool::empty () const inline
Definition at line 49 of file DwarfStringPool.h.
References llvm::StringMapImpl::empty().
getEntry()
DwarfStringPool::EntryRef DwarfStringPool::getEntry (AsmPrinter & Asm, StringRef Str)
Get a reference to an entry in the string pool.
Definition at line 41 of file DwarfStringPool.cpp.
Referenced by llvm::DwarfUnit::addString(), llvm::DwarfDebug::enterNonTypeUnitContext(), and getNumIndexedStrings().
getIndexedEntry()
DwarfStringPool::EntryRef DwarfStringPool::getIndexedEntry (AsmPrinter & Asm, StringRef Str)
Same as getEntry, except that you can use EntryRef::getIndex to obtain a unique ID of this entry (e.g., for use in indexed forms like DW_FORM_strx).
Definition at line 47 of file DwarfStringPool.cpp.
Referenced by llvm::DwarfUnit::addString(), and getNumIndexedStrings().
getNumIndexedStrings()
unsigned llvm::DwarfStringPool::getNumIndexedStrings () const inline
Definition at line 53 of file DwarfStringPool.h.
References getEntry(), and getIndexedEntry().
Referenced by emitStringOffsetsTableHeader().
size()
unsigned llvm::DwarfStringPool::size () const inline
Definition at line 51 of file DwarfStringPool.h.
References llvm::StringMapImpl::size().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfStringPool.h
lib/CodeGen/AsmPrinter/DwarfStringPool.cpp