LLVM: llvm::LockFileManager Class Reference
llvm::LockFileManager Class Reference
Class that manages the creation of a lock file to aid implicit coordination between different processes.
#include "llvm/Support/LockFileManager.h"
Public Types
enum LockFileState { LFS_Owned, LFS_Shared, LFS_Error }
Describes the state of a lock file.
enum WaitForUnlockResult { Res_Success, Res_OwnerDied, Res_Timeout }
Describes the result of waiting for the owner to release the lock.
Public Member Functions
LockFileManager (StringRef FileName)
~LockFileManager ()
LockFileState getState () const
Determine the state of the lock file.
operator LockFileState () const
WaitForUnlockResult waitForUnlock (const unsigned MaxSeconds=40)
For a shared lock, wait until the owner releases the lock.
std::error_code unsafeRemoveLockFile ()
Remove the lock file.
std::string getErrorMessage () const
Get error message, or "" if there is no error.
void setError (const std::error_code &EC, StringRef ErrorMsg="")
Set error and error message.
Detailed Description
Class that manages the creation of a lock file to aid implicit coordination between different processes.
The implicit coordination works by creating a ".lock" file alongside the file that we're coordinating for, using the atomicity of the file system to ensure that only a single process can create that ".lock" file. When the lock file is removed, the owning process has finished the operation.
Definition at line 27 of file LockFileManager.h.
Member Enumeration Documentation
LockFileState
enum llvm::LockFileManager::LockFileState
Describes the state of a lock file.
Enumerator
LFS_Owned
The lock file has been created and is owned by this instance of the object.
LFS_Shared
The lock file already exists and is owned by some other instance.
LFS_Error
An error occurred while trying to create or find the lock file.
Definition at line 30 of file LockFileManager.h.
WaitForUnlockResult
enum llvm::LockFileManager::WaitForUnlockResult
Describes the result of waiting for the owner to release the lock.
Enumerator
Res_Success
The lock was released successfully.
Res_OwnerDied
Owner died while holding the lock.
Res_Timeout
Reached timeout while waiting for the owner to release the lock.
Definition at line 43 of file LockFileManager.h.
Constructor & Destructor Documentation
LockFileManager()
LockFileManager::LockFileManager (StringRef FileName)
Definition at line 156 of file LockFileManager.cpp.
References llvm::raw_fd_ostream::close(), llvm::sys::fs::create_link(), llvm::sys::fs::createUniqueFile(), llvm::raw_fd_ostream::error(), llvm::sys::fs::exists(), llvm::file_exists, getHostID(), llvm::raw_fd_ostream::has_error(), llvm::sys::fs::make_absolute(), llvm::sys::fs::remove(), setError(), llvm::StringRef::str(), and llvm::raw_string_ostream::str().
~LockFileManager()
LockFileManager::~LockFileManager ()
Definition at line 281 of file LockFileManager.cpp.
References llvm::sys::DontRemoveFileOnSignal(), getState(), LFS_Owned, and llvm::sys::fs::remove().
Member Function Documentation
getErrorMessage()
std::string LockFileManager::getErrorMessage () const
Get error message, or "" if there is no error.
Definition at line 269 of file LockFileManager.cpp.
References llvm::raw_string_ostream::str().
Referenced by operator LockFileState().
getState()
LockFileManager::LockFileState LockFileManager::getState () const
Determine the state of the lock file.
Definition at line 259 of file LockFileManager.cpp.
References LFS_Error, LFS_Owned, and LFS_Shared.
Referenced by operator LockFileState(), waitForUnlock(), and ~LockFileManager().
operator LockFileState()
llvm::LockFileManager::operator LockFileState () const inline
Definition at line 77 of file LockFileManager.h.
References getErrorMessage(), getState(), unsafeRemoveLockFile(), and waitForUnlock().
setError()
void llvm::LockFileManager::setError (const std::error_code & EC, StringRef ErrorMsg = "") inline
Set error and error message.
Definition at line 92 of file LockFileManager.h.
Referenced by LockFileManager().
unsafeRemoveLockFile()
std::error_code LockFileManager::unsafeRemoveLockFile ()
Remove the lock file.
This may delete a different lock file than the one previously read if there is a race.
Definition at line 351 of file LockFileManager.cpp.
References llvm::sys::fs::remove().
Referenced by operator LockFileState().
waitForUnlock()
LockFileManager::WaitForUnlockResult LockFileManager::waitForUnlock (const unsigned MaxSeconds = 40)
For a shared lock, wait until the owner releases the lock.
Total timeout for the file to appear is ~1.5 minutes.
Parameters
MaxSeconds the maximum wait time per iteration in seconds.
Definition at line 294 of file LockFileManager.cpp.
References llvm::sys::fs::access(), llvm::sys::fs::Exist, llvm::sys::fs::exists(), getState(), LFS_Shared, llvm::no_such_file_or_directory, Res_OwnerDied, Res_Success, and Res_Timeout.
Referenced by operator LockFileState().
The documentation for this class was generated from the following files:
include/llvm/Support/LockFileManager.h
lib/Support/LockFileManager.cpp