LLVM: llvm::WebAssemblyFrameLowering Class Reference
llvm::WebAssemblyFrameLowering Class Reference final
#include "Target/WebAssembly/WebAssemblyFrameLowering.h"
Public Member Functions
WebAssemblyFrameLowering ()
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool hasFP (const MachineFunction &MF) const override
Return true if the specified function should have a dedicated frame pointer register.
bool hasReservedCallFrame (const MachineFunction &MF) const override
Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
bool needsPrologForEH (const MachineFunction &MF) const
void writeSPToGlobal (unsigned SrcReg, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator &InsertStore, const DebugLoc &DL) const
Write SP back to __stack_pointer global.
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None(), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool isFPCloseToIncomingSP () const
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Static Public Attributes
static const size_t RedZoneSize = 128
Size of the red zone for the user stack (leaf functions can use this much space below the stack pointer without writing it back to __stack_pointer global).
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 23 of file WebAssemblyFrameLowering.h.
Constructor & Destructor Documentation
WebAssemblyFrameLowering()
llvm::WebAssemblyFrameLowering::WebAssemblyFrameLowering () inline
Definition at line 31 of file WebAssemblyFrameLowering.h.
References eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), hasFP(), hasReservedCallFrame(), I, needsPrologForEH(), and writeSPToGlobal().
Member Function Documentation
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator WebAssemblyFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 138 of file WebAssemblyFrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::erase(), llvm::MachineFunction::getSubtarget(), hasFP(), TII, and writeSPToGlobal().
Referenced by WebAssemblyFrameLowering().
emitEpilogue()
void WebAssemblyFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 225 of file WebAssemblyFrameLowering.cpp.
References llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasFP(), MRI, TII, and writeSPToGlobal().
Referenced by WebAssemblyFrameLowering().
emitPrologue()
void WebAssemblyFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 152 of file WebAssemblyFrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::countTrailingZeros(), llvm::MachineFunction::createExternalSymbolName(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), hasFP(), llvm::WebAssembly::isArgument(), MRI, TII, and writeSPToGlobal().
Referenced by WebAssemblyFrameLowering().
hasFP()
bool WebAssemblyFrameLowering::hasFP (const MachineFunction & MF) const override virtual
Return true if the specified function should have a dedicated frame pointer register.
Implements llvm::TargetFrameLowering.
Definition at line 53 of file WebAssemblyFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::MachineFrameInfo::isFrameAddressTaken().
Referenced by eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), llvm::WebAssemblyRegisterInfo::getFrameRegister(), hasReservedCallFrame(), and WebAssemblyFrameLowering().
hasReservedCallFrame()
bool WebAssemblyFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 75 of file WebAssemblyFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), hasFP(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by WebAssemblyFrameLowering().
needsPrologForEH()
bool WebAssemblyFrameLowering::needsPrologForEH (const MachineFunction & MF) const
Definition at line 91 of file WebAssemblyFrameLowering.cpp.
References assert(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasCalls(), llvm::Function::hasFnAttribute(), llvm::Function::hasPersonalityFn(), RedZoneSize, and llvm::Wasm.
Referenced by WebAssemblyFrameLowering().
writeSPToGlobal()
void WebAssemblyFrameLowering::writeSPToGlobal (unsigned SrcReg, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator & InsertStore, const DebugLoc & DL) const
Write SP back to __stack_pointer global.
Definition at line 125 of file WebAssemblyFrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineFunction::createExternalSymbolName(), llvm::MachineFunction::getSubtarget(), and TII.
Referenced by eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), and WebAssemblyFrameLowering().
Member Data Documentation
RedZoneSize
const size_t llvm::WebAssemblyFrameLowering::RedZoneSize = 128 static
Size of the red zone for the user stack (leaf functions can use this much space below the stack pointer without writing it back to __stack_pointer global).
Definition at line 29 of file WebAssemblyFrameLowering.h.
Referenced by needsPrologForEH().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyFrameLowering.h
lib/Target/WebAssembly/WebAssemblyFrameLowering.cpp