LLVM: llvm::MemSetBase< BaseCL > Class Template Reference
llvm::MemSetBase< BaseCL > Class Template Reference
Common base class for all memset intrinsics.
#include "llvm/IR/IntrinsicInst.h"
Public Member Functions
Value * getValue () const
const Use & getValueUse () const
Use & getValueUse ()
void setValue (Value *Val)
Detailed Description
template<class BaseCL>
class llvm::MemSetBase< BaseCL >
Common base class for all memset intrinsics.
Simply provides common methods.
Definition at line 448 of file IntrinsicInst.h.
Member Function Documentation
getValue()
template<class BaseCL> Value* llvm::MemSetBase< BaseCL >::getValue () const inline
Definition at line 453 of file IntrinsicInst.h.
Referenced by llvm::createAArch64StackTaggingPass(), llvm::expandMemSetAsLoop(), getMemSetPatternValue(), INITIALIZE_PASS(), isCallPromotable(), moveUp(), and llvm::sroa::AllocaSliceRewriter::visit().
getValueUse() [1/2]
template<class BaseCL> const Use& llvm::MemSetBase< BaseCL >::getValueUse () const inline
Definition at line 456 of file IntrinsicInst.h.
getValueUse() [2/2]
template<class BaseCL> Use& llvm::MemSetBase< BaseCL >::getValueUse () inline
Definition at line 459 of file IntrinsicInst.h.
setValue()
template<class BaseCL> void llvm::MemSetBase< BaseCL >::setValue (Value * Val) inline
Definition at line 461 of file IntrinsicInst.h.
The documentation for this class was generated from the following file:
include/llvm/IR/IntrinsicInst.h