LLVM: llvm::SIScheduler Class Reference
llvm::SIScheduler Class Reference
#include "Target/AMDGPU/SIMachineScheduler.h"
Public Member Functions
SIScheduler (SIScheduleDAGMI *DAG)
~SIScheduler ()=default
struct SIScheduleBlockResult scheduleVariant (SISchedulerBlockCreatorVariant BlockVariant, SISchedulerBlockSchedulerVariant ScheduleVariant)
Detailed Description
Definition at line 414 of file SIMachineScheduler.h.
Constructor & Destructor Documentation
SIScheduler()
llvm::SIScheduler::SIScheduler (SIScheduleDAGMI * DAG) inline
Definition at line 419 of file SIMachineScheduler.h.
~SIScheduler()
llvm::SIScheduler::~SIScheduler () default
Member Function Documentation
scheduleVariant()
struct SIScheduleBlockResult SIScheduler::scheduleVariant (SISchedulerBlockCreatorVariant BlockVariant, SISchedulerBlockSchedulerVariant ScheduleVariant)
Definition at line 1771 of file SIMachineScheduler.cpp.
References llvm::SIScheduleBlockScheduler::getBlocks(), llvm::SIScheduleBlock::getScheduledUnits(), llvm::SIScheduleBlockScheduler::getSGPRUsage(), llvm::SIScheduleBlockScheduler::getVGPRUsage(), llvm::SIScheduleBlockResult::MaxSGPRUsage, llvm::SIScheduleBlockResult::MaxVGPRUsage, llvm::SUnit::NodeNum, Scheduler, and llvm::SIScheduleBlockResult::SUs.
Referenced by llvm::SIScheduleDAGMI::schedule().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIMachineScheduler.h
lib/Target/AMDGPU/SIMachineScheduler.cpp