LLVM: llvm::pdb::DIAInjectedSource Class Reference
llvm::pdb::DIAInjectedSource Class Reference
#include "llvm/DebugInfo/PDB/DIA/DIAInjectedSource.h"
Public Member Functions
DIAInjectedSource (CComPtr< IDiaInjectedSource > DiaSourceFile)
uint32_t getCrc32 () const override
uint64_t getCodeByteSize () const override
std::string getFileName () const override
std::string getObjectFileName () const override
std::string getVirtualFileName () const override
uint32_t getCompression () const override
std::string getCode () const override
Public Member Functions inherited from llvm::pdb::IPDBInjectedSource
virtual ~IPDBInjectedSource ()
Detailed Description
Definition at line 19 of file DIAInjectedSource.h.
Constructor & Destructor Documentation
DIAInjectedSource()
DIAInjectedSource::DIAInjectedSource (CComPtr< IDiaInjectedSource > DiaSourceFile) explicit
Definition at line 18 of file DIAInjectedSource.cpp.
Member Function Documentation
getCode()
std::string DIAInjectedSource::getCode () const override virtual
Implements llvm::pdb::IPDBInjectedSource.
Definition at line 51 of file DIAInjectedSource.cpp.
References assert(), and llvm::AMDGPU::SDWA::DWORD.
getCodeByteSize()
uint64_t DIAInjectedSource::getCodeByteSize () const override virtual
Implements llvm::pdb::IPDBInjectedSource.
Definition at line 26 of file DIAInjectedSource.cpp.
References Size.
getCompression()
uint32_t DIAInjectedSource::getCompression () const override virtual
Implements llvm::pdb::IPDBInjectedSource.
Definition at line 44 of file DIAInjectedSource.cpp.
References llvm::AMDGPU::SDWA::DWORD, and llvm::pdb::PDB_SourceCompression::None.
getCrc32()
uint32_t DIAInjectedSource::getCrc32 () const override virtual
Implements llvm::pdb::IPDBInjectedSource.
Definition at line 21 of file DIAInjectedSource.cpp.
References llvm::AMDGPU::SDWA::DWORD.
getFileName()
std::string DIAInjectedSource::getFileName () const override virtual
Implements llvm::pdb::IPDBInjectedSource.
Definition at line 31 of file DIAInjectedSource.cpp.
References invokeBstrMethod().
getObjectFileName()
std::string DIAInjectedSource::getObjectFileName () const override virtual
Implements llvm::pdb::IPDBInjectedSource.
Definition at line 35 of file DIAInjectedSource.cpp.
References invokeBstrMethod().
getVirtualFileName()
std::string DIAInjectedSource::getVirtualFileName () const override virtual
Implements llvm::pdb::IPDBInjectedSource.
Definition at line 39 of file DIAInjectedSource.cpp.
References invokeBstrMethod().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/DIA/DIAInjectedSource.h
lib/DebugInfo/PDB/DIA/DIAInjectedSource.cpp