LLVM: llvm::DWARFDebugNames::NameIndex Class Reference
llvm::DWARFDebugNames::NameIndex Class Reference
Represents a single accelerator table within the DWARF v5 .debug_names section.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
NameIndex (const DWARFDebugNames &Section, uint64_t Base)
uint64_t getCUOffset (uint32_t CU) const
Reads offset of compilation unit CU. CU is 0-based.
uint32_t getCUCount () const
uint64_t getLocalTUOffset (uint32_t TU) const
Reads offset of local type unit TU, TU is 0-based.
uint32_t getLocalTUCount () const
uint64_t getForeignTUSignature (uint32_t TU) const
Reads signature of foreign type unit TU. TU is 0-based.
uint32_t getForeignTUCount () const
uint32_t getBucketArrayEntry (uint32_t Bucket) const
Reads an entry in the Bucket Array for the given Bucket.
uint32_t getBucketCount () const
uint32_t getHashArrayEntry (uint32_t Index) const
Reads an entry in the Hash Array for the given Index.
NameTableEntry getNameTableEntry (uint32_t Index) const
Reads an entry in the Name Table for the given Index.
uint32_t getNameCount () const
const DenseSet< Abbrev, AbbrevMapInfo > & getAbbrevs () const
Expected< Entry > getEntry (uint64_t *Offset) const
iterator_range< ValueIterator > equal_range (StringRef Key) const
Look up all entries in this Name Index matching Key.
NameIterator begin () const
NameIterator end () const
Error extract ()
uint64_t getUnitOffset () const
uint64_t getNextUnitOffset () const
void dump (ScopedPrinter &W) const
Friends
class DWARFDebugNames
Detailed Description
Represents a single accelerator table within the DWARF v5 .debug_names section.
Definition at line 385 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
NameIndex()
llvm::DWARFDebugNames::NameIndex::NameIndex (const DWARFDebugNames & Section, uint64_t Base) inline
Definition at line 417 of file DWARFAcceleratorTable.h.
References llvm::DWARFAcceleratorTable::Entry::getCUOffset().
Member Function Documentation
begin()
NameIterator llvm::DWARFDebugNames::NameIndex::begin () const inline
Definition at line 459 of file DWARFAcceleratorTable.h.
dump()
LLVM_DUMP_METHOD void DWARFDebugNames::NameIndex::dump (ScopedPrinter & W) const
Definition at line 740 of file DWARFAcceleratorTable.cpp.
References llvm::None, llvm::ScopedPrinter::startLine(), and llvm::Twine::utohexstr().
end()
NameIterator llvm::DWARFDebugNames::NameIndex::end () const inline
Definition at line 460 of file DWARFAcceleratorTable.h.
References llvm::DWARFAcceleratorTable::extract().
equal_range()
iterator_range< DWARFDebugNames::ValueIterator > DWARFDebugNames::NameIndex::equal_range (StringRef Key) const
Look up all entries in this Name Index matching Key.
Definition at line 772 of file DWARFAcceleratorTable.cpp.
References llvm::make_range(), and llvm::AppleAcceleratorTable::ValueIterator::ValueIterator().
Referenced by isVariableIndexable().
extract()
Error DWARFDebugNames::NameIndex::extract ()
Definition at line 483 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFDebugNames::Abbrev::Attributes, llvm::createStringError(), E, llvm::DWARFAcceleratorTable::Entry::Entry(), llvm::illegal_byte_sequence, llvm::invalid_argument, isSentinel(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::ARMBuildAttrs::Section, and llvm::Error::success().
Referenced by llvm::DWARFDebugNames::extract().
getAbbrevs()
const DenseSet<Abbrev, AbbrevMapInfo>& llvm::DWARFDebugNames::NameIndex::getAbbrevs () const inline
Definition at line 450 of file DWARFAcceleratorTable.h.
getBucketArrayEntry()
uint32_t DWARFDebugNames::NameIndex::getBucketArrayEntry (uint32_t Bucket) const
Reads an entry in the Bucket Array for the given Bucket.
The returned value is a (1-based) index into the Names, StringOffsets and EntryOffsets arrays. The input Bucket index is 0-based.
Definition at line 639 of file DWARFAcceleratorTable.cpp.
References assert(), and llvm::ARMBuildAttrs::Section.
getBucketCount()
uint32_t llvm::DWARFDebugNames::NameIndex::getBucketCount () const inline
Definition at line 436 of file DWARFAcceleratorTable.h.
getCUCount()
uint32_t llvm::DWARFDebugNames::NameIndex::getCUCount () const inline
Definition at line 422 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::Entry::getCUIndex(), llvm::DWARFDebugNames::Entry::getCUOffset(), and getNames().
getCUOffset()
uint64_t DWARFDebugNames::NameIndex::getCUOffset (uint32_t CU) const
Reads offset of compilation unit CU. CU is 0-based.
Definition at line 580 of file DWARFAcceleratorTable.cpp.
References assert(), and llvm::ARMBuildAttrs::Section.
Referenced by llvm::DWARFDebugNames::Entry::getCUOffset(), and getNames().
getEntry()
Expected< DWARFDebugNames::Entry > DWARFDebugNames::NameIndex::getEntry (uint64_t * Offset) const
Definition at line 600 of file DWARFAcceleratorTable.cpp.
References llvm::createStringError(), llvm::dwarf::DWARF32, E, llvm::DataExtractor::getULEB128(), llvm::illegal_byte_sequence, llvm::invalid_argument, llvm::io_error, llvm::DataExtractor::isValidOffset(), llvm::ARMBuildAttrs::Section, llvm::DWARFAcceleratorTable::Entry::Values, and llvm::dwarf::FormParams::Version.
Referenced by getNames().
getForeignTUCount()
uint32_t llvm::DWARFDebugNames::NameIndex::getForeignTUCount () const inline
Definition at line 430 of file DWARFAcceleratorTable.h.
Referenced by getNames().
getForeignTUSignature()
uint64_t DWARFDebugNames::NameIndex::getForeignTUSignature (uint32_t TU) const
Reads signature of foreign type unit TU. TU is 0-based.
Definition at line 592 of file DWARFAcceleratorTable.cpp.
References assert(), and llvm::ARMBuildAttrs::Section.
getHashArrayEntry()
uint32_t DWARFDebugNames::NameIndex::getHashArrayEntry (uint32_t Index) const
Reads an entry in the Hash Array for the given Index.
The input Index is 1-based.
Definition at line 645 of file DWARFAcceleratorTable.cpp.
References assert(), llvm::DWARFDebugNames::Abbrev::dump(), llvm::format(), llvm::DWARFDebugNames::NameTableEntry::getEntryOffset(), llvm::DWARFDebugNames::NameTableEntry::getIndex(), llvm::ScopedPrinter::getOStream(), llvm::DWARFDebugNames::NameTableEntry::getString(), llvm::DWARFDebugNames::NameTableEntry::getStringOffset(), llvm::handleAllErrors(), llvm::ScopedPrinter::printHex(), llvm::ScopedPrinter::printString(), llvm::ARMBuildAttrs::Section, llvm::ScopedPrinter::startLine(), llvm::Twine::utohexstr(), and llvm::RISCVFenceField::W.
getLocalTUCount()
uint32_t llvm::DWARFDebugNames::NameIndex::getLocalTUCount () const inline
Definition at line 426 of file DWARFAcceleratorTable.h.
Referenced by getNames().
getLocalTUOffset()
uint64_t DWARFDebugNames::NameIndex::getLocalTUOffset (uint32_t TU) const
Reads offset of local type unit TU, TU is 0-based.
Definition at line 586 of file DWARFAcceleratorTable.cpp.
References assert(), and llvm::ARMBuildAttrs::Section.
getNameCount()
uint32_t llvm::DWARFDebugNames::NameIndex::getNameCount () const inline
Definition at line 448 of file DWARFAcceleratorTable.h.
getNameTableEntry()
DWARFDebugNames::NameTableEntry DWARFDebugNames::NameIndex::getNameTableEntry (uint32_t Index) const
Reads an entry in the Name Table for the given Index.
The Name Table consists of two arrays – String Offsets and Entry Offsets. The returned offsets are relative to the starts of respective sections. Input Index is 1-based.
Definition at line 626 of file DWARFAcceleratorTable.cpp.
References assert(), and llvm::ARMBuildAttrs::Section.
Referenced by llvm::DWARFDebugNames::NameIterator::operator*().
getNextUnitOffset()
uint64_t llvm::DWARFDebugNames::NameIndex::getNextUnitOffset () const inline
Definition at line 464 of file DWARFAcceleratorTable.h.
References llvm::DWARFAcceleratorTable::dump().
Referenced by llvm::DWARFDebugNames::extract().
getUnitOffset()
uint64_t llvm::DWARFDebugNames::NameIndex::getUnitOffset () const inline
Definition at line 463 of file DWARFAcceleratorTable.h.
Referenced by getNames(), and isVariableIndexable().
Friends And Related Function Documentation
DWARFDebugNames
friend class DWARFDebugNames friend
Definition at line 467 of file DWARFAcceleratorTable.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp