LLVM: llvm::DWARFDebugRangeList Class Reference
llvm::DWARFDebugRangeList Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugRangeList.h"
Classes
struct RangeListEntry
Public Member Functions
DWARFDebugRangeList ()
void clear ()
void dump (raw_ostream &OS) const
Error extract (const DWARFDataExtractor &data, uint64_t *offset_ptr)
const std::vector< RangeListEntry > & getEntries ()
DWARFAddressRangesVector getAbsoluteRanges (llvm::Optional< object::SectionedAddress > BaseAddr) const
getAbsoluteRanges - Returns absolute address ranges defined by this range list.
Detailed Description
Definition at line 22 of file DWARFDebugRangeList.h.
Constructor & Destructor Documentation
DWARFDebugRangeList()
llvm::DWARFDebugRangeList::DWARFDebugRangeList () inline
Definition at line 67 of file DWARFDebugRangeList.h.
References clear(), dump(), and extract().
Member Function Documentation
clear()
void DWARFDebugRangeList::clear ()
Definition at line 19 of file DWARFDebugRangeList.cpp.
Referenced by DWARFDebugRangeList(), and extract().
dump()
void DWARFDebugRangeList::dump (raw_ostream & OS) const
Definition at line 60 of file DWARFDebugRangeList.cpp.
References llvm::format().
Referenced by llvm::DWARFContext::dump(), and DWARFDebugRangeList().
extract()
Error DWARFDebugRangeList::extract (const DWARFDataExtractor & data, uint64_t * offset_ptr)
Definition at line 25 of file DWARFDebugRangeList.cpp.
References clear(), llvm::createStringError(), llvm::DataExtractor::getAddressSize(), llvm::invalid_argument, and llvm::DataExtractor::isValidOffset().
Referenced by llvm::DWARFContext::dump(), DWARFDebugRangeList(), and llvm::DWARFUnit::extractRangeList().
getAbsoluteRanges()
DWARFAddressRangesVector DWARFDebugRangeList::getAbsoluteRanges (llvm::Optional< object::SectionedAddress > BaseAddr) const
getAbsoluteRanges - Returns absolute address ranges defined by this range list.
Has to be passed base address of the compile unit referencing this range list.
Definition at line 70 of file DWARFDebugRangeList.cpp.
References llvm::object::SectionedAddress::Address, E, llvm::DWARFAddressRange::HighPC, llvm::DWARFAddressRange::LowPC, llvm::DWARFAddressRange::SectionIndex, and llvm::object::SectionedAddress::SectionIndex.
Referenced by llvm::DWARFUnit::findRnglistFromOffset(), and getEntries().
getEntries()
const std::vector<RangeListEntry>& llvm::DWARFDebugRangeList::getEntries () inline
Definition at line 72 of file DWARFDebugRangeList.h.
References getAbsoluteRanges().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugRangeList.h
lib/DebugInfo/DWARF/DWARFDebugRangeList.cpp