LLVM: llvm::BinaryOperator Class Reference
llvm::BinaryOperator Class Reference
#include "llvm/IR/InstrTypes.h"
Public Member Functions
void * operator new (size_t s)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
DEFINE_HELPERS (Add, NSW) DEFINE_HELPERS(Add
NUW DEFINE_HELPERS (Sub, NSW) DEFINE_HELPERS(Sub
NUW NUW DEFINE_HELPERS (Mul, NSW) DEFINE_HELPERS(Mul
NUW NUW NUW DEFINE_HELPERS (Shl, NSW) DEFINE_HELPERS(Shl
NUW NUW NUW NUW DEFINE_HELPERS (SDiv, Exact) DEFINE_HELPERS(UDiv
NUW NUW NUW NUW Exact DEFINE_HELPERS (AShr, Exact) DEFINE_HELPERS(LShr
BinaryOps getOpcode () const
bool swapOperands ()
Exchange the two operands to this instruction.
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isIndirectTerminator () const
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode *>> &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode *>> &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void getAAMetadata (AAMDNodes &N, bool Merge=false) const
Fills the AAMDNodes structure with AA metadata from this instruction.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void setAAMetadata (const AAMDNodes &N)
Sets the metadata on this instruction from the AAMDNodes structure.
bool extractProfMetadata (uint64_t &TrueVal, uint64_t &FalseVal) const
Retrieve the raw weight values of a conditional branch or select.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setProfWeight (uint64_t W)
Sets the branch_weights metadata to W for CallInst.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool isExact () const
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const
Return true if this instruction may modify memory.
bool mayReadFromMemory () const
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const
Return true if this atomic instruction stores to memory.
bool mayThrow () const
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const
Return true if the instruction may have side effects.
bool isSafeToRemove () const
Return true if the instruction can be removed if the result is unused.
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
const Instruction * getNextNonDebugInstruction () const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction ()
const Instruction * getPrevNonDebugInstruction () const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction ()
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static BinaryOperator * Create (BinaryOps Op, Value *S1, Value *S2, const Twine &Name=Twine(), Instruction *InsertBefore=nullptr)
Construct a binary instruction, given the opcode and the two operands.
static BinaryOperator * Create (BinaryOps Op, Value *S1, Value *S2, const Twine &Name, BasicBlock *InsertAtEnd)
Construct a binary instruction, given the opcode and the two operands.
static BinaryOperator * CreateWithCopiedFlags (BinaryOps Opc, Value *V1, Value *V2, Instruction *CopyO, const Twine &Name="")
static BinaryOperator * CreateFAddFMF (Value *V1, Value *V2, Instruction *FMFSource, const Twine &Name="")
static BinaryOperator * CreateFSubFMF (Value *V1, Value *V2, Instruction *FMFSource, const Twine &Name="")
static BinaryOperator * CreateFMulFMF (Value *V1, Value *V2, Instruction *FMFSource, const Twine &Name="")
static BinaryOperator * CreateFDivFMF (Value *V1, Value *V2, Instruction *FMFSource, const Twine &Name="")
static BinaryOperator * CreateFRemFMF (Value *V1, Value *V2, Instruction *FMFSource, const Twine &Name="")
static BinaryOperator * CreateFNegFMF (Value *Op, Instruction *FMFSource, const Twine &Name="")
static BinaryOperator * CreateNSW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name="")
static BinaryOperator * CreateNSW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, BasicBlock *BB)
static BinaryOperator * CreateNSW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, Instruction *I)
static BinaryOperator * CreateNUW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name="")
static BinaryOperator * CreateNUW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, BasicBlock *BB)
static BinaryOperator * CreateNUW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, Instruction *I)
static BinaryOperator * CreateExact (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name="")
static BinaryOperator * CreateExact (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, BasicBlock *BB)
static BinaryOperator * CreateExact (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, Instruction *I)
NUW NUW NUW NUW Exact static Exact BinaryOperator * CreateNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=nullptr)
Helper functions to construct and inspect unary operations (NEG and NOT) via binary operators SUB and XOR:
static BinaryOperator * CreateNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateNSWNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=nullptr)
static BinaryOperator * CreateNSWNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateNUWNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=nullptr)
static BinaryOperator * CreateNUWNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateFNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=nullptr)
static BinaryOperator * CreateFNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateNot (Value *Op, const Twine &Name="", Instruction *InsertBefore=nullptr)
static BinaryOperator * CreateNot (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isIndirectTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator with indirect targets.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
BinaryOperator (BinaryOps iType, Value *S1, Value *S2, Type *Ty, const Twine &Name, Instruction *InsertBefore)
BinaryOperator (BinaryOps iType, Value *S1, Value *S2, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
BinaryOperator * cloneImpl () const
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
ilist_node_impl ()=default
Friends
class Instruction
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, true, true >
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Definition at line 188 of file InstrTypes.h.
Constructor & Destructor Documentation
BinaryOperator() [1/2]
BinaryOperator::BinaryOperator (BinaryOps iType, Value * S1, Value * S2, Type * Ty, const Twine & Name, Instruction * InsertBefore) protected
Definition at line 2236 of file Instructions.cpp.
References llvm::Value::setName().
Referenced by Create(), CreateFNeg(), CreateNeg(), and CreateNot().
BinaryOperator() [2/2]
BinaryOperator::BinaryOperator (BinaryOps iType, Value * S1, Value * S2, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) protected
Definition at line 2249 of file Instructions.cpp.
References llvm::MCID::Add, assert(), getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm_unreachable, and llvm::Value::setName().
Member Function Documentation
classof() [1/2]
static bool llvm::BinaryOperator::classof (const Instruction * I) inline static
Definition at line 414 of file InstrTypes.h.
References llvm::Instruction::isBinaryOp().
classof() [2/2]
static bool llvm::BinaryOperator::classof (const Value * V) inline static
Definition at line 417 of file InstrTypes.h.
cloneImpl()
BinaryOperator * BinaryOperator::cloneImpl () const protected
Definition at line 4117 of file Instructions.cpp.
References llvm::Instruction::getOpcode().
Create() [1/2]
BinaryOperator * BinaryOperator::Create (BinaryOps Op, Value * S1, Value * S2, const Twine & Name = Twine(), Instruction * InsertBefore = nullptr) static
Construct a binary instruction, given the opcode and the two operands.
Optionally (if InstBefore is specified) insert the instruction into a BasicBlock right before the specified instruction. The specified Instruction is allowed to be a dereferenced end iterator.
Definition at line 2330 of file Instructions.cpp.
References assert(), BinaryOperator(), llvm::Value::getType(), and Name.
Referenced by llvm::fuzzerop::binOpDescriptor(), buildNew(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), Create(), llvm::NoFolder::CreateBinOp(), llvm::IRBuilder< TargetFolder >::CreateBinOp(), llvm::CastInst::CreateBitOrPointerCast(), llvm::CastInst::CreateFPCast(), llvm::CastInst::CreateIntegerCast(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::CastInst::CreateSExtOrBitCast(), llvm::CastInst::CreateTruncOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateUnreachable(), llvm::CastInst::CreateZExtOrBitCast(), decomposeSimpleLinearExpr(), dropRedundantMaskingOfLeftShiftInput(), foldBitCastBitwiseLogic(), foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftOfShiftedLogic(), llvm::InstCombiner::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVecTruncToExtElt(), llvm::ConstantExpr::getAsInstruction(), getSignature(), isSafeAndProfitableToSinkLoad(), isSelect01(), LinearizeExprTree(), processSaturatingInst(), processUGT_ADDCST_ADD(), reassociateFCmps(), llvm::InstCombiner::reassociateShiftAmtsOfTwoSameDirectionShifts(), shouldMergeGEPs(), simplifyAssocCastAssoc(), SimplifyNVVMIntrinsic(), sinkAndCmp0Expression(), truncateIVUse(), updateOperand(), llvm::LoopVersioning::versionLoop(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitFPTrunc(), visitIVCast(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitTrunc(), and willNotOverflow().
Create() [2/2]
BinaryOperator * BinaryOperator::Create (BinaryOps Op, Value * S1, Value * S2, const Twine & Name, BasicBlock * InsertAtEnd) static
Construct a binary instruction, given the opcode and the two operands.
Also automatically insert this instruction to the end of the BasicBlock specified.
Definition at line 2338 of file Instructions.cpp.
References Create(), llvm::BasicBlock::getInstList(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
CreateExact() [1/3]
static BinaryOperator* llvm::BinaryOperator::CreateExact (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name = "") inline static
Definition at line 327 of file InstrTypes.h.
References llvm::Instruction::setIsExact().
CreateExact() [2/3]
static BinaryOperator* llvm::BinaryOperator::CreateExact (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, BasicBlock * BB) inline static
Definition at line 333 of file InstrTypes.h.
References llvm::Instruction::setIsExact().
CreateExact() [3/3]
static BinaryOperator* llvm::BinaryOperator::CreateExact (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, Instruction * I) inline static
Definition at line 339 of file InstrTypes.h.
References llvm::Instruction::setIsExact().
CreateFAddFMF()
static BinaryOperator* llvm::BinaryOperator::CreateFAddFMF (Value * V1, Value * V2, Instruction * FMFSource, const Twine & Name = "") inline static
Definition at line 258 of file InstrTypes.h.
Referenced by factorizeLerp(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFSub().
CreateFDivFMF()
static BinaryOperator* llvm::BinaryOperator::CreateFDivFMF (Value * V1, Value * V2, Instruction * FMFSource, const Twine & Name = "") inline static
Definition at line 273 of file InstrTypes.h.
Referenced by factorizeFAddFSub(), foldFDivConstantDividend(), foldFDivConstantDivisor(), foldFNegIntoConstant(), hoistFNegAboveFMulFDiv(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFPTrunc().
CreateFMulFMF()
static BinaryOperator* llvm::BinaryOperator::CreateFMulFMF (Value * V1, Value * V2, Instruction * FMFSource, const Twine & Name = "") inline static
Definition at line 268 of file InstrTypes.h.
Referenced by factorizeFAddFSub(), foldFDivConstantDivisor(), foldFNegIntoConstant(), hoistFNegAboveFMulFDiv(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFPTrunc(), and llvm::InstCombiner::visitFSub().
CreateFNeg() [1/2]
BinaryOperator * BinaryOperator::CreateFNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Definition at line 2386 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), Name, and zero().
Referenced by CreateNeg(), and llvm::InstCombiner::visitCallInst().
CreateFNeg() [2/2]
BinaryOperator * BinaryOperator::CreateFNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 2393 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), Name, and zero().
CreateFNegFMF()
static BinaryOperator* llvm::BinaryOperator::CreateFNegFMF (Value * Op, Instruction * FMFSource, const Twine & Name = "") inline static
Definition at line 283 of file InstrTypes.h.
References llvm::ConstantFP::getNegativeZero(), and llvm::Value::getType().
Referenced by llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFPTrunc(), and llvm::InstCombiner::visitFSub().
CreateFRemFMF()
static BinaryOperator* llvm::BinaryOperator::CreateFRemFMF (Value * V1, Value * V2, Instruction * FMFSource, const Twine & Name = "") inline static
Definition at line 278 of file InstrTypes.h.
CreateFSubFMF()
static BinaryOperator* llvm::BinaryOperator::CreateFSubFMF (Value * V1, Value * V2, Instruction * FMFSource, const Twine & Name = "") inline static
Definition at line 263 of file InstrTypes.h.
Referenced by llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFNeg().
CreateNeg() [1/2]
BinaryOperator * BinaryOperator::CreateNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Helper functions to construct and inspect unary operations (NEG and NOT) via binary operators SUB and XOR:
Create the NEG and NOT instructions out of SUB and XOR instructions.
Definition at line 2346 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), Name, and zero().
Referenced by llvm::NoFolder::CreateNeg(), CreateNeg(), llvm::IRBuilder< TargetFolder >::CreateNeg(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSDiv(), and llvm::InstCombiner::visitSub().
CreateNeg() [2/2]
BinaryOperator * BinaryOperator::CreateNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 2354 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), Name, and zero().
CreateNot() [1/2]
BinaryOperator * BinaryOperator::CreateNot (Value * Op, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Definition at line 2400 of file Instructions.cpp.
References BinaryOperator(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), and Name.
Referenced by canonicalizeICmpBool(), canonicalizeLowbitMask(), llvm::NoFolder::CreateNot(), llvm::IRBuilder< TargetFolder >::CreateNot(), foldAndToXor(), foldOrToXor(), foldXorToXor(), isSupportedGuardInstruction(), matchDeMorgansLaws(), OptimizeGlobalAddressOfMalloc(), processUMulZExtIdiom(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
CreateNot() [2/2]
BinaryOperator * BinaryOperator::CreateNot (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 2407 of file Instructions.cpp.
References BinaryOperator(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), and Name.
CreateNSW() [1/3]
static BinaryOperator* llvm::BinaryOperator::CreateNSW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name = "") inline static
Definition at line 289 of file InstrTypes.h.
References llvm::Instruction::setHasNoSignedWrap().
Referenced by llvm::InstCombiner::visitCallInst().
CreateNSW() [2/3]
static BinaryOperator* llvm::BinaryOperator::CreateNSW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, BasicBlock * BB) inline static
Definition at line 295 of file InstrTypes.h.
References llvm::Instruction::setHasNoSignedWrap().
CreateNSW() [3/3]
static BinaryOperator* llvm::BinaryOperator::CreateNSW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, Instruction * I) inline static
Definition at line 301 of file InstrTypes.h.
References llvm::Instruction::setHasNoSignedWrap().
CreateNSWNeg() [1/2]
BinaryOperator * BinaryOperator::CreateNSWNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Definition at line 2362 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
Referenced by llvm::NoFolder::CreateNSWNeg(), llvm::InstCombiner::visitSDiv(), and llvm::InstCombiner::visitSRem().
CreateNSWNeg() [2/2]
BinaryOperator * BinaryOperator::CreateNSWNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 2368 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
CreateNUW() [1/3]
static BinaryOperator* llvm::BinaryOperator::CreateNUW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name = "") inline static
Definition at line 308 of file InstrTypes.h.
References llvm::Instruction::setHasNoUnsignedWrap().
Referenced by simplifyAssocCastAssoc(), and llvm::InstCombiner::visitCallInst().
CreateNUW() [2/3]
static BinaryOperator* llvm::BinaryOperator::CreateNUW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, BasicBlock * BB) inline static
Definition at line 314 of file InstrTypes.h.
References llvm::Instruction::setHasNoUnsignedWrap().
CreateNUW() [3/3]
static BinaryOperator* llvm::BinaryOperator::CreateNUW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, Instruction * I) inline static
Definition at line 320 of file InstrTypes.h.
References llvm::Instruction::setHasNoUnsignedWrap().
CreateNUWNeg() [1/2]
BinaryOperator * BinaryOperator::CreateNUWNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Definition at line 2374 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
Referenced by llvm::NoFolder::CreateNUWNeg().
CreateNUWNeg() [2/2]
BinaryOperator * BinaryOperator::CreateNUWNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 2380 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
CreateWithCopiedFlags()
static BinaryOperator* llvm::BinaryOperator::CreateWithCopiedFlags (BinaryOps Opc, Value * V1, Value * V2, Instruction * CopyO, const Twine & Name = "") inline static
Definition at line 249 of file InstrTypes.h.
References llvm::Instruction::copyIRFlags().
Referenced by cheapToScalarize(), and llvm::InstCombiner::visitExtractElementInst().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::BinaryOperator::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
DEFINE_HELPERS() [1/6]
llvm::BinaryOperator::DEFINE_HELPERS (Add , NSW)
DEFINE_HELPERS() [2/6]
NUW llvm::BinaryOperator::DEFINE_HELPERS (Sub , NSW)
DEFINE_HELPERS() [3/6]
NUW NUW llvm::BinaryOperator::DEFINE_HELPERS (Mul , NSW)
DEFINE_HELPERS() [4/6]
NUW NUW NUW llvm::BinaryOperator::DEFINE_HELPERS (Shl , NSW)
DEFINE_HELPERS() [5/6]
NUW NUW NUW NUW llvm::BinaryOperator::DEFINE_HELPERS (SDiv , Exact)
DEFINE_HELPERS() [6/6]
NUW NUW NUW NUW Exact llvm::BinaryOperator::DEFINE_HELPERS (AShr , Exact)
getOpcode()
BinaryOps llvm::BinaryOperator::getOpcode () const inline
Definition at line 402 of file InstrTypes.h.
References llvm::Instruction::getOpcode().
Referenced by BinaryOperator(), buildMultiplyTree(), AAValueConstantRangeFloating::calculateBinaryOperator(), llvm::InstCombiner::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canShiftBinOpWithConstantRHS(), cheapToScalarize(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonIRemTransforms(), llvm::InstCombiner::commonShiftTransforms(), constantFoldUser(), llvm::createSeparateConstOffsetFromGEPPass(), detectPopcountIdiom(), dropRedundantMaskingOfLeftShiftInput(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), factorizeFAddFSub(), foldAndToXor(), foldBitCastBitwiseLogic(), foldICmpBitCast(), foldICmpShlOne(), foldLogicCastConstant(), foldOperationIntoPhiValue(), foldOrToXor(), foldSelectBinOpIdentity(), foldSelectShuffle(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedLogic(), foldToUnsignedSaturatedAdd(), llvm::InstCombiner::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVecTruncToExtElt(), foldXorToXor(), getAlternateBinop(), getBinOpsForFactorization(), GetLoopInvariantInsertPosition(), getMulHu(), getNegatibleInsts(), getParameterABIAttributes(), getSelectFoldableConstant(), getSelectFoldableOperands(), handlePhiDef(), hasZeroSignBit(), INITIALIZE_PASS(), insertValues(), isAddOfNonZero(), llvm::InductionDescriptor::isFPInductionPHI(), isGEPFoldable(), isImpliedCondAndOr(), llvm::isImpliedCondition(), llvm::CastInst::isIntegerCast(), isLoopIncrement(), llvm::CastInst::isLosslessCast(), llvm::CastInst::isNoopCast(), isSafeAndProfitableToSinkLoad(), LinearizeExprTree(), maintainNoSignedWrap(), matchDeMorgansLaws(), matchRotate(), narrowUDivURem(), NegateValue(), OptimizeExtractBits(), OptimizeNoopCopyExpression(), processBinOp(), processUDivOrURem(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), promotedOpIsNUW(), reassociateFCmps(), llvm::InstCombiner::reassociateShiftAmtsOfTwoSameDirectionShifts(), setLimitsForBinOp(), shouldMergeGEPs(), simplifyAssocCastAssoc(), SimplifyAssociativeBinOp(), SimplifyBSwap(), simplifyICmpWithBinOp(), simplifyValueKnownNonZero(), SinkShiftAndTruncate(), llvm::InstCombiner::visitAnd(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
operator new()
void* llvm::BinaryOperator::operator new (size_t s) inline
Definition at line 204 of file InstrTypes.h.
References DECLARE_TRANSPARENT_OPERAND_ACCESSORS.
swapOperands()
bool BinaryOperator::swapOperands ()
Exchange the two operands to this instruction.
This instruction is safe to use on any binary instruction and does not modify the semantics of the instruction. If the instruction cannot be reversed (ie, it's a Div), then return true.
Definition at line 2418 of file Instructions.cpp.
References llvm::Instruction::isCommutative(), and std::swap().
Referenced by LinearizeExprTree(), and simplifyAssocCastAssoc().
Friends And Related Function Documentation
Instruction
friend class Instruction friend
Definition at line 198 of file InstrTypes.h.
The documentation for this class was generated from the following files:
include/llvm/IR/InstrTypes.h
lib/IR/Instructions.cpp