LLVM: llvm::VEInstrInfo Class Reference
llvm::VEInstrInfo Class Reference
#include "Target/VE/VEInstrInfo.h"
Public Member Functions
VEInstrInfo (VESubtarget &ST)
const VERegisterInfo & getRegisterInfo () const
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
bool expandPostRAPseudo (MachineInstr &MI) const override
bool expandExtendStackPseudo (MachineInstr &MI) const
Detailed Description
Definition at line 26 of file VEInstrInfo.h.
Constructor & Destructor Documentation
VEInstrInfo()
VEInstrInfo::VEInstrInfo (VESubtarget & ST) explicit
Definition at line 37 of file VEInstrInfo.cpp.
Member Function Documentation
expandExtendStackPseudo()
bool VEInstrInfo::expandExtendStackPseudo (MachineInstr & MI) const
Definition at line 54 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::VECC::CC_IGE, llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::insert(), llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by expandPostRAPseudo(), and getRegisterInfo().
expandPostRAPseudo()
bool VEInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 41 of file VEInstrInfo.cpp.
References llvm::MachineInstr::eraseFromParent(), expandExtendStackPseudo(), and llvm::MachineInstr::getOpcode().
Referenced by getRegisterInfo().
getRegisterInfo()
const VERegisterInfo& llvm::VEInstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 38 of file VEInstrInfo.h.
References expandExtendStackPseudo(), expandPostRAPseudo(), and MI.
Referenced by llvm::VESubtarget::getRegisterInfo().
The documentation for this class was generated from the following files:
lib/Target/VE/VEInstrInfo.h
lib/Target/VE/VEInstrInfo.cpp