LLVM: llvm::AddressPool Class Reference
llvm::AddressPool Class Reference
#include "CodeGen/AsmPrinter/AddressPool.h"
Public Member Functions
AddressPool ()=default
unsigned getIndex (const MCSymbol *Sym, bool TLS=false)
Returns the index into the address pool with the given label/symbol.
void emit (AsmPrinter &Asm, MCSection *AddrSection)
bool isEmpty ()
bool hasBeenUsed () const
void resetUsedFlag ()
MCSymbol * getLabel ()
void setLabel (MCSymbol *Sym)
Detailed Description
Definition at line 23 of file AddressPool.h.
Constructor & Destructor Documentation
AddressPool()
llvm::AddressPool::AddressPool () default
Member Function Documentation
emit()
void AddressPool::emit (AsmPrinter & Asm, MCSection * AddrSection)
Definition at line 47 of file AddressPool.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::AsmPrinter::getDataLayout(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::AsmPrinter::getDwarfVersion(), llvm::AsmPrinter::getObjFileLowering(), llvm::DataLayout::getPointerSize(), I, isEmpty(), llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
getIndex()
unsigned AddressPool::getIndex (const MCSymbol * Sym, bool TLS = false)
Returns the index into the address pool with the given label/symbol.
Definition at line 19 of file AddressPool.cpp.
References llvm::HexStyle::Asm, llvm::AsmPrinter::createTempSymbol(), llvm::AsmPrinter::emitInt16(), llvm::AsmPrinter::emitInt8(), llvm::AsmPrinter::EmitLabelDifference(), llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getDwarfVersion(), llvm::DataLayout::getPointerSize(), llvm::AsmPrinter::OutStreamer, llvm::cl::Prefix, and llvm::ARMBuildAttrs::Section.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfUnit::addOpAddress(), emitLocList(), and emitRangeList().
getLabel()
MCSymbol* llvm::AddressPool::getLabel () inline
Definition at line 53 of file AddressPool.h.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase().
hasBeenUsed()
bool llvm::AddressPool::hasBeenUsed () const inline
Definition at line 49 of file AddressPool.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
isEmpty()
bool llvm::AddressPool::isEmpty () inline
Definition at line 47 of file AddressPool.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty().
Referenced by llvm::DwarfDebug::beginModule(), and emit().
resetUsedFlag()
void llvm::AddressPool::resetUsedFlag () inline
Definition at line 51 of file AddressPool.h.
Referenced by llvm::DwarfDebug::NonTypeUnitContext::~NonTypeUnitContext().
setLabel()
void llvm::AddressPool::setLabel (MCSymbol * Sym) inline
Definition at line 54 of file AddressPool.h.
References llvm::ARMBuildAttrs::Section.
Referenced by llvm::DwarfDebug::beginModule().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/AddressPool.h
lib/CodeGen/AsmPrinter/AddressPool.cpp