LLVM: llvm::codeview::SymbolRecordMapping Class Reference
llvm::codeview::SymbolRecordMapping Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecordMapping.h"
Public Member Functions
SymbolRecordMapping (BinaryStreamReader &Reader, CodeViewContainer Container)
SymbolRecordMapping (BinaryStreamWriter &Writer, CodeViewContainer Container)
Error visitSymbolBegin (CVSymbol &Record) override
Error visitSymbolEnd (CVSymbol &Record) override
Public Member Functions inherited from llvm::codeview::SymbolVisitorCallbacks
virtual ~SymbolVisitorCallbacks ()=default
virtual Error visitUnknownSymbol (CVSymbol &Record)
Action to take on unknown symbols. By default, they are ignored.
virtual Error visitSymbolBegin (CVSymbol &Record, uint32_t Offset)
Paired begin/end actions for all symbols.
Detailed Description
Definition at line 20 of file SymbolRecordMapping.h.
Constructor & Destructor Documentation
SymbolRecordMapping() [1/2]
llvm::codeview::SymbolRecordMapping::SymbolRecordMapping (BinaryStreamReader & Reader, CodeViewContainer Container) inline explicit
Definition at line 22 of file SymbolRecordMapping.h.
SymbolRecordMapping() [2/2]
llvm::codeview::SymbolRecordMapping::SymbolRecordMapping (BinaryStreamWriter & Writer, CodeViewContainer Container) inline explicit
Definition at line 25 of file SymbolRecordMapping.h.
References visitSymbolBegin(), and visitSymbolEnd().
Member Function Documentation
visitSymbolBegin()
Error SymbolRecordMapping::visitSymbolBegin (CVSymbol & Record) override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 36 of file SymbolRecordMapping.cpp.
References error, llvm::codeview::MaxRecordLength, and llvm::Error::success().
Referenced by SymbolRecordMapping(), and llvm::codeview::SymbolSerializer::visitSymbolBegin().
visitSymbolEnd()
Error SymbolRecordMapping::visitSymbolEnd (CVSymbol & Record) override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 41 of file SymbolRecordMapping.cpp.
References llvm::codeview::SectionSym::Alignment, llvm::codeview::alignOf(), llvm::codeview::InlineSiteSym::AnnotationData, llvm::codeview::DefRangeRegisterRelHeader::BasePointerOffset, llvm::codeview::BuildInfoSym::BuildId, llvm::codeview::FrameProcSym::BytesOfCalleeSavedRegisters, llvm::codeview::HeapAllocationSiteSym::CallInstructionSize, llvm::codeview::SectionSym::Characteristics, llvm::codeview::CoffGroupSym::Characteristics, llvm::codeview::ProcSym::CodeOffset, llvm::codeview::BlockSym::CodeOffset, llvm::codeview::LabelSym::CodeOffset, llvm::codeview::CallSiteInfoSym::CodeOffset, llvm::codeview::HeapAllocationSiteSym::CodeOffset, llvm::codeview::FrameCookieSym::CodeOffset, llvm::codeview::AnnotationSym::CodeOffset, llvm::codeview::ProcSym::CodeSize, llvm::codeview::BlockSym::CodeSize, llvm::codeview::FrameCookieSym::CookieKind, llvm::Data, llvm::codeview::DataSym::DataOffset, llvm::codeview::ThreadLocalDataSym::DataOffset, llvm::codeview::ProcSym::DbgEnd, llvm::codeview::ProcSym::DbgStart, llvm::codeview::ProcSym::End, llvm::codeview::Thunk32Sym::End, llvm::codeview::InlineSiteSym::End, llvm::codeview::BlockSym::End, error, llvm::codeview::Compile2Sym::ExtraStrings, llvm::codeview::EnvBlockSym::Fields, llvm::codeview::ProcSym::Flags, llvm::codeview::PublicSym32::Flags, llvm::codeview::LocalSym::Flags, llvm::codeview::DefRangeRegisterRelHeader::Flags, llvm::codeview::LabelSym::Flags, llvm::codeview::ExportSym::Flags, llvm::codeview::FileStaticSym::Flags, llvm::codeview::Compile2Sym::Flags, llvm::codeview::Compile3Sym::Flags, llvm::codeview::FrameProcSym::Flags, llvm::codeview::FrameCookieSym::Flags, llvm::codeview::ProcSym::FunctionType, llvm::codeview::DefRangeSym::Gaps, llvm::codeview::DefRangeSubfieldSym::Gaps, llvm::codeview::DefRangeRegisterSym::Gaps, llvm::codeview::DefRangeSubfieldRegisterSym::Gaps, llvm::codeview::DefRangeFramePointerRelSym::Gaps, llvm::codeview::DefRangeRegisterRelSym::Gaps, llvm::codeview::DefRangeRegisterSym::Hdr, llvm::codeview::DefRangeSubfieldRegisterSym::Hdr, llvm::codeview::DefRangeFramePointerRelSym::Hdr, llvm::codeview::DefRangeRegisterRelSym::Hdr, llvm::codeview::RegisterSym::Index, llvm::codeview::FileStaticSym::Index, llvm::codeview::CallerSym::Indices, llvm::codeview::InlineSiteSym::Inlinee, llvm::codeview::Thunk32Sym::Length, llvm::codeview::SectionSym::Length, llvm::codeview::Compile2Sym::Machine, llvm::codeview::Compile3Sym::Machine, mapLocalVariableAddrRange(), llvm::codeview::DefRangeRegisterHeader::MayHaveNoName, llvm::codeview::DefRangeSubfieldRegisterHeader::MayHaveNoName, llvm::codeview::FileStaticSym::ModFilenameOffset, llvm::codeview::ProcRefSym::Module, N, llvm::codeview::ProcSym::Name, llvm::codeview::Thunk32Sym::Name, llvm::codeview::SectionSym::Name, llvm::codeview::CoffGroupSym::Name, llvm::codeview::PublicSym32::Name, llvm::codeview::RegisterSym::Name, llvm::codeview::ProcRefSym::Name, llvm::codeview::LocalSym::Name, llvm::codeview::BlockSym::Name, llvm::codeview::LabelSym::Name, llvm::codeview::ObjNameSym::Name, llvm::codeview::ExportSym::Name, llvm::codeview::FileStaticSym::Name, llvm::codeview::UDTSym::Name, llvm::codeview::BPRelativeSym::Name, llvm::codeview::RegRelativeSym::Name, llvm::codeview::ConstantSym::Name, llvm::codeview::DataSym::Name, llvm::codeview::ThreadLocalDataSym::Name, llvm::codeview::UsingNamespaceSym::Name, llvm::codeview::ProcSym::Next, llvm::codeview::Thunk32Sym::Next, llvm::codeview::Thunk32Sym::Offset, llvm::codeview::CoffGroupSym::Offset, llvm::codeview::PublicSym32::Offset, llvm::codeview::DefRangeFramePointerRelHeader::Offset, llvm::codeview::DefRangeFramePointerRelFullScopeSym::Offset, llvm::codeview::BPRelativeSym::Offset, llvm::codeview::RegRelativeSym::Offset, llvm::codeview::DefRangeSubfieldSym::OffsetInParent, llvm::codeview::DefRangeSubfieldRegisterHeader::OffsetInParent, llvm::codeview::FrameProcSym::OffsetOfExceptionHandler, llvm::codeview::FrameProcSym::OffsetToPadding, llvm::codeview::ExportSym::Ordinal, llvm::codeview::FrameProcSym::PaddingFrameBytes, llvm::codeview::ProcSym::Parent, llvm::codeview::Thunk32Sym::Parent, llvm::codeview::InlineSiteSym::Parent, llvm::codeview::BlockSym::Parent, llvm::codeview::DefRangeSym::Program, llvm::codeview::DefRangeSubfieldSym::Program, llvm::codeview::Public, llvm::codeview::DefRangeSym::Range, llvm::codeview::DefRangeSubfieldSym::Range, llvm::codeview::DefRangeRegisterSym::Range, llvm::codeview::DefRangeSubfieldRegisterSym::Range, llvm::codeview::DefRangeFramePointerRelSym::Range, llvm::codeview::DefRangeRegisterRelSym::Range, llvm::codeview::RegisterSym::Register, llvm::codeview::DefRangeRegisterHeader::Register, llvm::codeview::DefRangeSubfieldRegisterHeader::Register, llvm::codeview::DefRangeRegisterRelHeader::Register, llvm::codeview::FrameCookieSym::Register, llvm::codeview::RegRelativeSym::Register, llvm::codeview::SectionSym::Rva, llvm::ARMBuildAttrs::Section, llvm::codeview::FrameProcSym::SectionIdOfExceptionHandler, llvm::codeview::SectionSym::SectionNumber, llvm::codeview::ProcSym::Segment, llvm::codeview::Thunk32Sym::Segment, llvm::codeview::CoffGroupSym::Segment, llvm::codeview::PublicSym32::Segment, llvm::codeview::BlockSym::Segment, llvm::codeview::LabelSym::Segment, llvm::codeview::CallSiteInfoSym::Segment, llvm::codeview::HeapAllocationSiteSym::Segment, llvm::codeview::DataSym::Segment, llvm::codeview::ThreadLocalDataSym::Segment, llvm::codeview::AnnotationSym::Segment, llvm::codeview::ObjNameSym::Signature, llvm::codeview::TrampolineSym::Size, llvm::codeview::CoffGroupSym::Size, llvm::codeview::AnnotationSym::Strings, llvm::Error::success(), llvm::codeview::ProcRefSym::SumName, llvm::codeview::ProcRefSym::SymOffset, llvm::codeview::TrampolineSym::TargetOffset, llvm::codeview::TrampolineSym::TargetSection, llvm::codeview::Thunk32Sym::Thunk, llvm::codeview::TrampolineSym::ThunkOffset, llvm::codeview::TrampolineSym::ThunkSection, llvm::codeview::FrameProcSym::TotalFrameBytes, llvm::codeview::TrampolineSym::Type, llvm::codeview::LocalSym::Type, llvm::codeview::CallSiteInfoSym::Type, llvm::codeview::HeapAllocationSiteSym::Type, llvm::codeview::UDTSym::Type, llvm::codeview::BPRelativeSym::Type, llvm::codeview::RegRelativeSym::Type, llvm::codeview::ConstantSym::Type, llvm::codeview::DataSym::Type, llvm::codeview::ThreadLocalDataSym::Type, llvm::codeview::ConstantSym::Value, llvm::codeview::Thunk32Sym::VariantData, llvm::codeview::Compile2Sym::Version, llvm::codeview::Compile3Sym::Version, llvm::codeview::Compile2Sym::VersionBackendBuild, llvm::codeview::Compile3Sym::VersionBackendBuild, llvm::codeview::Compile2Sym::VersionBackendMajor, llvm::codeview::Compile3Sym::VersionBackendMajor, llvm::codeview::Compile2Sym::VersionBackendMinor, llvm::codeview::Compile3Sym::VersionBackendMinor, llvm::codeview::Compile3Sym::VersionBackendQFE, llvm::codeview::Compile2Sym::VersionFrontendBuild, llvm::codeview::Compile3Sym::VersionFrontendBuild, llvm::codeview::Compile2Sym::VersionFrontendMajor, llvm::codeview::Compile3Sym::VersionFrontendMajor, llvm::codeview::Compile2Sym::VersionFrontendMinor, llvm::codeview::Compile3Sym::VersionFrontendMinor, llvm::codeview::Compile3Sym::VersionFrontendQFE, and visitKnownRecord().
Referenced by SymbolRecordMapping(), and llvm::codeview::SymbolSerializer::visitSymbolEnd().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/SymbolRecordMapping.h
lib/DebugInfo/CodeView/SymbolRecordMapping.cpp