LLVM: llvm::DiagnosticInfoOptimizationBase Class Reference
llvm::DiagnosticInfoOptimizationBase Class Reference abstract
Common features for diagnostics dealing with optimization remarks that are used by both IR and MIR passes.
#include "llvm/IR/DiagnosticInfo.h"
Classes
struct Argument
Used in the streaming interface as the general argument type.
struct setExtraArgs
When an instance of this is inserted into the stream, the arguments following will not appear in the remark printed in the compiler output (-Rpass) but only in the optimization record file (-fsave-optimization-record).
struct setIsVerbose
Used to set IsVerbose via the stream interface.
Public Member Functions
DiagnosticInfoOptimizationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const char *PassName, StringRef RemarkName, const Function &Fn, const DiagnosticLocation &Loc)
PassName is the name of the pass emitting this diagnostic.
void insert (StringRef S)
void insert (Argument A)
void insert (setIsVerbose V)
void insert (setExtraArgs EA)
void print (DiagnosticPrinter &DP) const override
virtual bool isEnabled () const =0
Return true if this optimization remark is enabled by one of of the LLVM command line flags (-pass-remarks, -pass-remarks-missed, or -pass-remarks-analysis).
StringRef getPassName () const
StringRef getRemarkName () const
std::string getMsg () const
Optional< uint64_t > getHotness () const
void setHotness (Optional< uint64_t > H)
bool isVerbose () const
ArrayRef< Argument > getArgs () const
bool isPassed () const
bool isMissed () const
bool isAnalysis () const
Public Member Functions inherited from llvm::DiagnosticInfoWithLocationBase
DiagnosticInfoWithLocationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const Function &Fn, const DiagnosticLocation &Loc)
Fn is the function where the diagnostic is being emitted.
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
const std::string getLocationStr () const
Return a string with the location information for this diagnostic in the format "file:line:col".
void getLocation (StringRef &RelativePath, unsigned &Line, unsigned &Column) const
Return location information for this diagnostic in three parts: the relative source file path, line number and column.
std::string getAbsolutePath () const
Return the absolute path tot the file.
const Function & getFunction () const
DiagnosticLocation getLocation () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Protected Attributes
const char * PassName
Name of the pass that triggers this report.
StringRef RemarkName
Textual identifier for the remark (single-word, camel-case).
Optional< uint64_t > Hotness
If profile information is available, this is the number of times the corresponding code was executed in a profile instrumentation run.
SmallVector< Argument, 4 > Args
Arguments collected via the streaming interface.
bool IsVerbose = false
The remark is expected to be noisy.
int FirstExtraArgIndex = -1
If positive, the index of the first argument that only appear in the optimization records and not in the remark printed in the compiler output.
Detailed Description
Common features for diagnostics dealing with optimization remarks that are used by both IR and MIR passes.
Definition at line 405 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoOptimizationBase()
llvm::DiagnosticInfoOptimizationBase::DiagnosticInfoOptimizationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const char * PassName, StringRef RemarkName, const Function & Fn, const DiagnosticLocation & Loc) inline
PassName is the name of the pass emitting this diagnostic.
RemarkName is a textual identifier for the remark (single-word, camel-case). Fn is the function where the diagnostic is being emitted. Loc is the location information to use in the diagnostic. If line table information is available, the diagnostic will include the source code location.
Definition at line 446 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::print().
Member Function Documentation
classof()
static bool llvm::DiagnosticInfoOptimizationBase::classof (const DiagnosticInfo * DI) inline static
Definition at line 479 of file DiagnosticInfo.h.
References llvm::DK_FirstMachineRemark, llvm::DK_FirstRemark, llvm::DK_LastMachineRemark, llvm::DK_LastRemark, and llvm::DiagnosticInfo::getKind().
getArgs()
ArrayRef<Argument> llvm::DiagnosticInfoOptimizationBase::getArgs () const inline
Definition at line 477 of file DiagnosticInfo.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
Referenced by toRemarkLocation().
getHotness()
Optional<uint64_t> llvm::DiagnosticInfoOptimizationBase::getHotness () const inline
Definition at line 472 of file DiagnosticInfo.h.
Referenced by llvm::OptimizationRemarkEmitter::emit(), and toRemarkLocation().
getMsg()
std::string DiagnosticInfoOptimizationBase::getMsg () const
Definition at line 362 of file DiagnosticInfo.cpp.
References Arg, Args, FirstExtraArgIndex, llvm::make_range(), and llvm::raw_string_ostream::str().
Referenced by print(), reportFastISelFailure(), and llvm::reportGISelFailure().
getPassName()
StringRef llvm::DiagnosticInfoOptimizationBase::getPassName () const inline
Definition at line 469 of file DiagnosticInfo.h.
Referenced by llvm::RemarkStreamer::emit(), llvm::MachineOptimizationRemark::isEnabled(), llvm::MachineOptimizationRemarkMissed::isEnabled(), llvm::MachineOptimizationRemarkAnalysis::isEnabled(), llvm::OptimizationRemark::isEnabled(), llvm::OptimizationRemarkMissed::isEnabled(), llvm::OptimizationRemarkAnalysis::isEnabled(), and toRemarkLocation().
getRemarkName()
StringRef llvm::DiagnosticInfoOptimizationBase::getRemarkName () const inline
Definition at line 470 of file DiagnosticInfo.h.
Referenced by toRemarkLocation().
insert() [1/4]
void DiagnosticInfoOptimizationBase::insert (StringRef S)
Definition at line 346 of file DiagnosticInfo.cpp.
References Args.
insert() [2/4]
void DiagnosticInfoOptimizationBase::insert (Argument A)
Definition at line 350 of file DiagnosticInfo.cpp.
References Args.
insert() [3/4]
void DiagnosticInfoOptimizationBase::insert (setIsVerbose V)
Definition at line 354 of file DiagnosticInfo.cpp.
References IsVerbose.
insert() [4/4]
void DiagnosticInfoOptimizationBase::insert (setExtraArgs EA)
Definition at line 358 of file DiagnosticInfo.cpp.
References Args, and FirstExtraArgIndex.
isAnalysis()
bool llvm::DiagnosticInfoOptimizationBase::isAnalysis () const inline
Definition at line 496 of file DiagnosticInfo.h.
References llvm::DK_MachineOptimizationRemarkAnalysis, llvm::DK_OptimizationRemarkAnalysis, and llvm::DiagnosticInfo::getKind().
isEnabled()
virtual bool llvm::DiagnosticInfoOptimizationBase::isEnabled () const pure virtual
Return true if this optimization remark is enabled by one of of the LLVM command line flags (-pass-remarks, -pass-remarks-missed, or -pass-remarks-analysis).
Note that this only handles the LLVM flags. We cannot access Clang flags from here (they are handled in BackendConsumer::OptimizationRemarkHandler).
Implemented in llvm::DiagnosticInfoOptimizationFailure, llvm::OptimizationRemarkAnalysis, llvm::OptimizationRemarkMissed, llvm::OptimizationRemark, llvm::MachineOptimizationRemarkAnalysis, llvm::MachineOptimizationRemarkMissed, and llvm::MachineOptimizationRemark.
isMissed()
bool llvm::DiagnosticInfoOptimizationBase::isMissed () const inline
Definition at line 491 of file DiagnosticInfo.h.
References llvm::DK_MachineOptimizationRemarkMissed, llvm::DK_OptimizationRemarkMissed, and llvm::DiagnosticInfo::getKind().
isPassed()
bool llvm::DiagnosticInfoOptimizationBase::isPassed () const inline
Definition at line 486 of file DiagnosticInfo.h.
References llvm::DK_MachineOptimizationRemark, llvm::DK_OptimizationRemark, and llvm::DiagnosticInfo::getKind().
isVerbose()
bool llvm::DiagnosticInfoOptimizationBase::isVerbose () const inline
Definition at line 475 of file DiagnosticInfo.h.
print()
void DiagnosticInfoOptimizationBase::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 225 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoWithLocationBase::getLocationStr(), getMsg(), and Hotness.
setHotness()
void llvm::DiagnosticInfoOptimizationBase::setHotness (Optional< uint64_t > H) inline
Definition at line 473 of file DiagnosticInfo.h.
References H.
Referenced by llvm::OptimizationRemarkEmitter::invalidate(), and llvm::DiagnosticInfoMIROptimization::MachineArgument::MachineArgument().
Member Data Documentation
Args
SmallVector<Argument, 4> llvm::DiagnosticInfoOptimizationBase::Args protected
Arguments collected via the streaming interface.
Definition at line 517 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoIROptimization::DiagnosticInfoIROptimization(), getMsg(), and insert().
FirstExtraArgIndex
int llvm::DiagnosticInfoOptimizationBase::FirstExtraArgIndex = -1 protected
If positive, the index of the first argument that only appear in the optimization records and not in the remark printed in the compiler output.
Definition at line 525 of file DiagnosticInfo.h.
Referenced by getMsg(), and insert().
Hotness
Optional<uint64_t> llvm::DiagnosticInfoOptimizationBase::Hotness protected
If profile information is available, this is the number of times the corresponding code was executed in a profile instrumentation run.
Definition at line 514 of file DiagnosticInfo.h.
Referenced by print().
IsVerbose
bool llvm::DiagnosticInfoOptimizationBase::IsVerbose = false protected
The remark is expected to be noisy.
Definition at line 520 of file DiagnosticInfo.h.
Referenced by insert().
PassName
const char* llvm::DiagnosticInfoOptimizationBase::PassName protected
Name of the pass that triggers this report.
If this matches the regular expression given in -Rpass=regexp, then the remark will be emitted.
Definition at line 505 of file DiagnosticInfo.h.
RemarkName
StringRef llvm::DiagnosticInfoOptimizationBase::RemarkName protected
Textual identifier for the remark (single-word, camel-case).
Can be used by external tools reading the output file for optimization remarks to identify the remark.
Definition at line 510 of file DiagnosticInfo.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp