LLVM: llvm::RuntimeDyldCheckerImpl Class Reference
llvm::RuntimeDyldCheckerImpl Class Reference
#include "ExecutionEngine/RuntimeDyld/RuntimeDyldCheckerImpl.h"
Public Member Functions
RuntimeDyldCheckerImpl (IsSymbolValidFunction IsSymbolValid, GetSymbolInfoFunction GetSymbolInfo, GetSectionInfoFunction GetSectionInfo, GetStubInfoFunction GetStubInfo, GetGOTInfoFunction GetGOTInfo, support::endianness Endianness, MCDisassembler *Disassembler, MCInstPrinter *InstPrinter, llvm::raw_ostream &ErrStream)
bool check (StringRef CheckExpr) const
bool checkAllRulesInBuffer (StringRef RulePrefix, MemoryBuffer *MemBuf) const
Friends
class RuntimeDyldChecker
class RuntimeDyldCheckerExprEval
Detailed Description
Definition at line 16 of file RuntimeDyldCheckerImpl.h.
Constructor & Destructor Documentation
RuntimeDyldCheckerImpl()
RuntimeDyldCheckerImpl::RuntimeDyldCheckerImpl (IsSymbolValidFunction IsSymbolValid, GetSymbolInfoFunction GetSymbolInfo, GetSectionInfoFunction GetSectionInfo, GetStubInfoFunction GetStubInfo, GetGOTInfoFunction GetGOTInfo, support::endianness Endianness, MCDisassembler * Disassembler, MCInstPrinter * InstPrinter, llvm::raw_ostream & ErrStream)
Definition at line 677 of file RuntimeDyldChecker.cpp.
Member Function Documentation
check()
bool RuntimeDyldCheckerImpl::check (StringRef CheckExpr) const
Definition at line 690 of file RuntimeDyldChecker.cpp.
References llvm::dbgs(), llvm::RuntimeDyldCheckerExprEval::evaluate(), LLVM_DEBUG, P, and llvm::StringRef::trim().
Referenced by checkAllRulesInBuffer().
checkAllRulesInBuffer()
bool RuntimeDyldCheckerImpl::checkAllRulesInBuffer (StringRef RulePrefix, MemoryBuffer * MemBuf) const
Definition at line 702 of file RuntimeDyldChecker.cpp.
References assert(), check(), llvm::errs(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferStart(), llvm_unreachable, llvm::logAllUnhandledErrors(), llvm::pointerToJITTargetAddress(), Size, llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::StringRef::substr(), llvm::ARMBuildAttrs::Symbol, and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
Friends And Related Function Documentation
RuntimeDyldChecker
friend class RuntimeDyldChecker friend
Definition at line 17 of file RuntimeDyldCheckerImpl.h.
RuntimeDyldCheckerExprEval
friend class RuntimeDyldCheckerExprEval friend
Definition at line 18 of file RuntimeDyldCheckerImpl.h.
The documentation for this class was generated from the following files:
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldCheckerImpl.h
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldChecker.cpp