LLVM: llvm::WinException Class Reference
llvm::WinException Class Reference
#include "CodeGen/AsmPrinter/WinException.h"
Public Member Functions
WinException (AsmPrinter *A)
~WinException () override
void endModule () override
Emit all exception information that should come after the content.
void beginFunction (const MachineFunction *MF) override
Gather pre-function exception information.
void markFunctionEnd () override
void endFunction (const MachineFunction *) override
Gather and emit post-function exception information.
void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym) override
Emit target-specific EH funclet machinery.
void endFunclet () override
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
~EHStreamer () override
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void endFragment ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::EHStreamer
static bool callToNoUnwindFunction (const MachineInstr *MI)
Return `true' if this is a call to a function marked `nounwind'.
Protected Types inherited from llvm::EHStreamer
using RangeMapType = DenseMap< MCSymbol *, PadRange >
Protected Member Functions inherited from llvm::EHStreamer
void computeActionsTable (const SmallVectorImpl< const LandingPadInfo *> &LandingPads, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
Compute the actions table and gather the first action index for each landing pad site.
void computePadMap (const SmallVectorImpl< const LandingPadInfo *> &LandingPads, RangeMapType &PadMap)
virtual void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, const SmallVectorImpl< const LandingPadInfo *> &LandingPads, const SmallVectorImpl< unsigned > &FirstActions)
Compute the call-site table.
MCSymbol * emitExceptionTable ()
Emit landing pads and actions.
virtual void emitTypeInfos (unsigned TTypeEncoding, MCSymbol *TTBaseLabel)
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
static bool isFilterEHSelector (int Selector)
static bool isCleanupEHSelector (int Selector)
static bool isCatchEHSelector (int Selector)
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Definition at line 27 of file WinException.h.
Constructor & Destructor Documentation
WinException()
WinException::WinException (AsmPrinter * A)
Definition at line 40 of file WinException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::getDataLayout(), llvm::DataLayout::getPointerSizeInBits(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isAArch64(), and llvm::AsmPrinter::TM.
~WinException()
WinException::~WinException () override
Definition at line 47 of file WinException.cpp.
Member Function Documentation
beginFunclet()
void WinException::beginFunclet (const MachineBasicBlock & MBB, MCSymbol * Sym) override virtual
Emit target-specific EH funclet machinery.
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 188 of file WinException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::EmitAlignment(), F(), llvm::MachineBasicBlock::getAlignment(), llvm::MachineFunction::getAlignment(), llvm::TargetLoweringObjectFile::getCFIPersonalitySymbol(), llvm::MachineFunction::getFunction(), getMCSymbolForMBB(), llvm::AsmPrinter::getObjFileLowering(), llvm::Function::getPersonalityFn(), llvm::Function::hasPersonalityFn(), llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::MachineBasicBlock::isCleanupFuncletEntry(), llvm::max(), llvm::AsmPrinter::MF, llvm::EHStreamer::MMI, llvm::AsmPrinter::OutStreamer, llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, llvm::Constant::stripPointerCasts(), and llvm::AsmPrinter::TM.
Referenced by beginFunction().
beginFunction()
void WinException::beginFunction (const MachineFunction * MF) override virtual
Gather pre-function exception information.
Assumes being emitted immediately after the function entry point.
Implements llvm::AsmPrinterHandler.
Definition at line 59 of file WinException.cpp.
References llvm::EHStreamer::Asm, beginFunclet(), llvm::classifyEHPersonality(), llvm::AsmPrinter::CurrentFnSym, llvm::GlobalValue::dropLLVMManglingEscape(), llvm::dwarf::DW_EH_PE_omit, llvm::dyn_cast(), F(), llvm::MachineFunction::front(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getLandingPads(), llvm::TargetLoweringObjectFile::getLSDAEncoding(), llvm::Value::getName(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetLoweringObjectFile::getPersonalityEncoding(), llvm::Function::getPersonalityFn(), llvm::MachineFunction::getWinEHFuncInfo(), llvm::MachineFunction::hasEHFunclets(), llvm::Function::hasPersonalityFn(), llvm::MachineFunction::hasWinCFI(), llvm::isNoOpWithoutInvoke(), llvm::AsmPrinter::MAI, llvm::MSVC_X86SEH, llvm::AsmPrinter::needsSEHMoves(), llvm::Function::needsUnwindTableEntry(), llvm::Constant::stripPointerCasts(), llvm::Unknown, and llvm::MCAsmInfo::usesWindowsCFI().
endFunclet()
void WinException::endFunclet () override virtual
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 239 of file WinException.cpp.
References llvm::EHStreamer::Asm, assert(), llvm::classifyEHPersonality(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::GlobalValue::dropLLVMManglingEscape(), llvm::WinEHFuncInfo::EHRegNodeEndOffset, F(), llvm::ISD::FrameIndex, llvm::TargetFrameLowering::getFrameIndexReference(), llvm::TargetFrameLowering::getFrameIndexReferencePreferSP(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::Value::getName(), llvm::MCContext::getOrCreateSymbol(), llvm::Function::getPersonalityFn(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::MachineFunction::getSubtarget(), llvm::AsmPrinter::getSymbol(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::MachineFunction::hasEHFunclets(), llvm::Function::hasPersonalityFn(), llvm::MachineBasicBlock::isCleanupFuncletEntry(), llvm::MachineBasicBlock::isEHFuncletEntry(), llvm::AsmPrinter::MAI, llvm::AsmPrinter::MF, llvm::MSVC_CXX, llvm::MSVC_Win64SEH, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, scan(), llvm::Constant::stripPointerCasts(), llvm::Unknown, llvm::MCAsmInfo::usesWindowsCFI(), llvm::MCSymbolRefExpr::VK_COFF_IMGREL32, and llvm::MCSymbolRefExpr::VK_None.
endFunction()
void WinException::endFunction (const MachineFunction * MF) override virtual
Gather and emit post-function exception information.
endFunction - Gather and emit post-function exception information.
Implements llvm::AsmPrinterHandler.
Definition at line 120 of file WinException.cpp.
References llvm::EHStreamer::Asm, llvm::classifyEHPersonality(), llvm::CoreCLR, llvm::EHStreamer::emitExceptionTable(), F(), llvm::MachineFunction::getFunction(), llvm::Function::getPersonalityFn(), llvm::MachineFunction::hasEHFunclets(), llvm::Function::hasPersonalityFn(), llvm::isFuncletEHPersonality(), llvm::MSVC_CXX, llvm::MSVC_Win64SEH, llvm::MSVC_X86SEH, llvm::AsmPrinter::OutStreamer, llvm::Constant::stripPointerCasts(), llvm::MachineFunction::tidyLandingPads(), and llvm::Unknown.
endModule()
void WinException::endModule () override virtual
Emit all exception information that should come after the content.
endModule - Emit all exception information that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 51 of file WinException.cpp.
References llvm::EHStreamer::Asm, F(), llvm::MachineModuleInfo::getModule(), llvm::AsmPrinter::getSymbol(), llvm::EHStreamer::MMI, and llvm::AsmPrinter::OutStreamer.
markFunctionEnd()
void WinException::markFunctionEnd () override virtual
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 112 of file WinException.cpp.
References llvm::EHStreamer::Asm, and llvm::AsmPrinter::OutStreamer.
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/WinException.h
lib/CodeGen/AsmPrinter/WinException.cpp