LLVM: llvm::SparcInstPrinter Class Reference
llvm::SparcInstPrinter Class Reference
#include "Target/Sparc/MCTargetDesc/SparcInstPrinter.h"
Public Member Functions
SparcInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
bool printSparcAliasInstr (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &OS)
bool isV9 (const MCSubtargetInfo &STI) const
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
void printOperand (const MCInst *MI, int opNum, const MCSubtargetInfo &STI, raw_ostream &OS)
void printMemOperand (const MCInst *MI, int opNum, const MCSubtargetInfo &STI, raw_ostream &OS, const char *Modifier=nullptr)
void printCCOperand (const MCInst *MI, int opNum, const MCSubtargetInfo &STI, raw_ostream &OS)
bool printGetPCX (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &OS)
void printMembarTag (const MCInst *MI, int opNum, const MCSubtargetInfo &STI, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 20 of file SparcInstPrinter.h.
Constructor & Destructor Documentation
SparcInstPrinter()
llvm::SparcInstPrinter::SparcInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 22 of file SparcInstPrinter.h.
References llvm::Address, getRegisterName(), isV9(), MI, llvm::RISCVFenceField::O, printAliasInstr(), printCCOperand(), printCustomAliasOperand(), printGetPCX(), printInst(), printInstruction(), printMembarTag(), printMemOperand(), printOperand(), printRegName(), and printSparcAliasInstr().
Member Function Documentation
getRegisterName()
static const char* llvm::SparcInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by llvm::SparcTargetAsmStreamer::emitSparcRegisterIgnore(), llvm::SparcTargetAsmStreamer::emitSparcRegisterScratch(), and SparcInstPrinter().
isV9()
bool SparcInstPrinter::isV9 (const MCSubtargetInfo & STI) const
Definition at line 37 of file SparcInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by SparcInstPrinter().
printAliasInstr()
bool llvm::SparcInstPrinter::printAliasInstr (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by SparcInstPrinter().
printCCOperand()
void SparcInstPrinter::printCCOperand (const MCInst * MI, int opNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 163 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and llvm::SPARCCondCodeToString().
Referenced by SparcInstPrinter().
printCustomAliasOperand()
void llvm::SparcInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by SparcInstPrinter().
printGetPCX()
bool SparcInstPrinter::printGetPCX (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 192 of file SparcInstPrinter.cpp.
References llvm_unreachable.
Referenced by SparcInstPrinter().
printInst()
void SparcInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 46 of file SparcInstPrinter.cpp.
Referenced by SparcInstPrinter().
printInstruction()
void llvm::SparcInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by SparcInstPrinter().
printMembarTag()
void SparcInstPrinter::printMembarTag (const MCInst * MI, int opNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 199 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and TagNames.
Referenced by SparcInstPrinter().
printMemOperand()
void SparcInstPrinter::printMemOperand (const MCInst * MI, int opNum, const MCSubtargetInfo & STI, raw_ostream & OS, const char * Modifier = nullptr)
Definition at line 140 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and printOperand().
Referenced by SparcInstPrinter().
printOperand()
void SparcInstPrinter::printOperand (const MCInst * MI, int opNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 108 of file SparcInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::MCExpr::print().
Referenced by SparcInstPrinter().
printRegName()
void SparcInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 41 of file SparcInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
Referenced by SparcInstPrinter().
printSparcAliasInstr()
bool SparcInstPrinter::printSparcAliasInstr (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 54 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), printMemOperand(), and printOperand().
Referenced by SparcInstPrinter().
The documentation for this class was generated from the following files:
lib/Target/Sparc/MCTargetDesc/SparcInstPrinter.h
lib/Target/Sparc/MCTargetDesc/SparcInstPrinter.cpp