LLVM: NodeArray Class Reference
NodeArray Class Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
NodeArray ()
NodeArray (Node **Elements_, size_t NumElements_)
bool empty () const
size_t size () const
Node ** begin () const
Node ** end () const
Node * operator[] (size_t Idx) const
void printWithComma (OutputStream &S) const
Detailed Description
Definition at line 212 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
NodeArray() [1/2]
NodeArray::NodeArray () inline
Definition at line 217 of file ItaniumDemangle.h.
NodeArray() [2/2]
NodeArray::NodeArray (Node ** Elements_, size_t NumElements_) inline
Definition at line 218 of file ItaniumDemangle.h.
Member Function Documentation
begin()
Node** NodeArray::begin () const inline
Definition at line 224 of file ItaniumDemangle.h.
empty()
bool NodeArray::empty () const inline
Definition at line 221 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseUnnamedTypeName(), ClosureTypeName::printDeclarator(), and NewExpr::printLeft().
end()
Node** NodeArray::end () const inline
Definition at line 225 of file ItaniumDemangle.h.
operator[]()
Node* NodeArray::operator[] (size_t Idx) const inline
Definition at line 227 of file ItaniumDemangle.h.
printWithComma()
void NodeArray::printWithComma (OutputStream & S) const inline
Definition at line 229 of file ItaniumDemangle.h.
References OutputStream::getCurrentPosition(), Node::print(), and OutputStream::setCurrentPosition().
Referenced by llvm::ItaniumPartialDemangler::getFunctionParameters(), ClosureTypeName::printDeclarator(), NodeArrayNode::printLeft(), EnableIfAttr::printLeft(), DynamicExceptionSpec::printLeft(), TemplateTemplateParamDecl::printLeft(), StructuredBindingName::printLeft(), CallExpr::printLeft(), NewExpr::printLeft(), ConversionExpr::printLeft(), InitListExpr::printLeft(), FunctionType::printRight(), and FunctionEncoding::printRight().
size()
size_t NodeArray::size () const inline
Definition at line 222 of file ItaniumDemangle.h.
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h