LLVM: llvm::codeview::PointerRecord Class Reference
llvm::codeview::PointerRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
PointerRecord ()=default
PointerRecord (TypeRecordKind Kind)
PointerRecord (TypeIndex ReferentType, uint32_t Attrs)
PointerRecord (TypeIndex ReferentType, PointerKind PK, PointerMode PM, PointerOptions PO, uint8_t Size)
PointerRecord (TypeIndex ReferentType, PointerKind PK, PointerMode PM, PointerOptions PO, uint8_t Size, const MemberPointerInfo &MPI)
TypeIndex getReferentType () const
PointerKind getPointerKind () const
PointerMode getMode () const
PointerOptions getOptions () const
uint8_t getSize () const
MemberPointerInfo getMemberInfo () const
bool isPointerToMember () const
bool isFlat () const
bool isConst () const
bool isVolatile () const
bool isUnaligned () const
bool isRestrict () const
bool isLValueReferenceThisPtr () const
bool isRValueReferenceThisPtr () const
void setAttrs (PointerKind PK, PointerMode PM, PointerOptions PO, uint8_t Size)
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex ReferentType
uint32_t Attrs = 0
Optional< MemberPointerInfo > MemberInfo
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Static Public Attributes
static const uint32_t PointerKindShift = 0
static const uint32_t PointerKindMask = 0x1F
static const uint32_t PointerModeShift = 5
static const uint32_t PointerModeMask = 0x07
static const uint32_t PointerOptionMask = 0x381f00
static const uint32_t PointerSizeShift = 13
static const uint32_t PointerSizeMask = 0xFF
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 269 of file TypeRecord.h.
Constructor & Destructor Documentation
PointerRecord() [1/5]
llvm::codeview::PointerRecord::PointerRecord () default
PointerRecord() [2/5]
llvm::codeview::PointerRecord::PointerRecord (TypeRecordKind Kind) inline explicit
Definition at line 287 of file TypeRecord.h.
PointerRecord() [3/5]
llvm::codeview::PointerRecord::PointerRecord (TypeIndex ReferentType, uint32_t Attrs) inline
Definition at line 289 of file TypeRecord.h.
PointerRecord() [4/5]
llvm::codeview::PointerRecord::PointerRecord (TypeIndex ReferentType, PointerKind PK, PointerMode PM, PointerOptions PO, uint8_t Size) inline
Definition at line 293 of file TypeRecord.h.
PointerRecord() [5/5]
llvm::codeview::PointerRecord::PointerRecord (TypeIndex ReferentType, PointerKind PK, PointerMode PM, PointerOptions PO, uint8_t Size, const MemberPointerInfo & MPI) inline
Definition at line 298 of file TypeRecord.h.
Member Function Documentation
getMemberInfo()
MemberPointerInfo llvm::codeview::PointerRecord::getMemberInfo () const inline
Definition at line 323 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getMode()
PointerMode llvm::codeview::PointerRecord::getMode () const inline
Definition at line 310 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getOptions()
PointerOptions llvm::codeview::PointerRecord::getOptions () const inline
Definition at line 315 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
getPointerKind()
PointerKind llvm::codeview::PointerRecord::getPointerKind () const inline
Definition at line 305 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getReferentType()
TypeIndex llvm::codeview::PointerRecord::getReferentType () const inline
Definition at line 303 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getSize()
uint8_t llvm::codeview::PointerRecord::getSize () const inline
Definition at line 319 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isConst()
bool llvm::codeview::PointerRecord::isConst () const inline
Definition at line 331 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, and llvm::codeview::Const.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isFlat()
bool llvm::codeview::PointerRecord::isFlat () const inline
Definition at line 330 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, and llvm::codeview::Flat32.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isLValueReferenceThisPtr()
bool llvm::codeview::PointerRecord::isLValueReferenceThisPtr () const inline
Definition at line 345 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, and llvm::codeview::LValueRefThisPointer.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isPointerToMember()
bool llvm::codeview::PointerRecord::isPointerToMember () const inline
Definition at line 325 of file TypeRecord.h.
References llvm::codeview::PointerToDataMember, and llvm::codeview::PointerToMemberFunction.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isRestrict()
bool llvm::codeview::PointerRecord::isRestrict () const inline
Definition at line 341 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, and llvm::codeview::Restrict.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isRValueReferenceThisPtr()
bool llvm::codeview::PointerRecord::isRValueReferenceThisPtr () const inline
Definition at line 349 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, and llvm::codeview::RValueRefThisPointer.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isUnaligned()
bool llvm::codeview::PointerRecord::isUnaligned () const inline
Definition at line 337 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, and llvm::codeview::Unaligned.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
isVolatile()
bool llvm::codeview::PointerRecord::isVolatile () const inline
Definition at line 333 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, and llvm::codeview::Volatile.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
setAttrs()
void llvm::codeview::PointerRecord::setAttrs (PointerKind PK, PointerMode PM, PointerOptions PO, uint8_t Size) inline
Definition at line 357 of file TypeRecord.h.
References Size.
Member Data Documentation
Attrs
uint32_t llvm::codeview::PointerRecord::Attrs = 0
Definition at line 354 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
MemberInfo
Optional<MemberPointerInfo> llvm::codeview::PointerRecord::MemberInfo
Definition at line 355 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
PointerKindMask
const uint32_t llvm::codeview::PointerRecord::PointerKindMask = 0x1F static
Definition at line 273 of file TypeRecord.h.
PointerKindShift
const uint32_t llvm::codeview::PointerRecord::PointerKindShift = 0 static
Definition at line 272 of file TypeRecord.h.
PointerModeMask
const uint32_t llvm::codeview::PointerRecord::PointerModeMask = 0x07 static
Definition at line 277 of file TypeRecord.h.
Referenced by getPointerMode().
PointerModeShift
const uint32_t llvm::codeview::PointerRecord::PointerModeShift = 5 static
Definition at line 276 of file TypeRecord.h.
Referenced by getPointerMode().
PointerOptionMask
const uint32_t llvm::codeview::PointerRecord::PointerOptionMask = 0x381f00 static
Definition at line 280 of file TypeRecord.h.
PointerSizeMask
const uint32_t llvm::codeview::PointerRecord::PointerSizeMask = 0xFF static
Definition at line 284 of file TypeRecord.h.
PointerSizeShift
const uint32_t llvm::codeview::PointerRecord::PointerSizeShift = 13 static
Definition at line 283 of file TypeRecord.h.
ReferentType
TypeIndex llvm::codeview::PointerRecord::ReferentType
Definition at line 353 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h