LLVM: llvm::RISCVInstPrinter Class Reference
llvm::RISCVInstPrinter Class Reference
#include "Target/RISCV/MCTargetDesc/RISCVInstPrinter.h"
Public Member Functions
RISCVInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
bool applyTargetSpecificCLOption (StringRef Opt) override
Customize the printer according to a command line option.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &O, unsigned RegNo) const override
Print the assembler register name.
void printOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O, const char *Modifier=nullptr)
void printCSRSystemRegister (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFenceArg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFRMArg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printAtomicMemOp (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
static const char * getRegisterName (unsigned RegNo, unsigned AltIdx)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 22 of file RISCVInstPrinter.h.
Constructor & Destructor Documentation
RISCVInstPrinter()
llvm::RISCVInstPrinter::RISCVInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 24 of file RISCVInstPrinter.h.
References llvm::Address, applyTargetSpecificCLOption(), getRegisterName(), MI, llvm::RISCVFenceField::O, printAliasInstr(), printAtomicMemOp(), printCSRSystemRegister(), printCustomAliasOperand(), printFenceArg(), printFRMArg(), printInst(), printInstruction(), printOperand(), and printRegName().
Member Function Documentation
applyTargetSpecificCLOption()
bool RISCVInstPrinter::applyTargetSpecificCLOption (StringRef Opt) override virtual
Customize the printer according to a command line option.
Returns
true if the option is recognized and applied.
Reimplemented from llvm::MCInstPrinter.
Definition at line 53 of file RISCVInstPrinter.cpp.
References ArchRegNames, and NoAliases.
Referenced by RISCVInstPrinter().
getRegisterName() [1/2]
const char * RISCVInstPrinter::getRegisterName (unsigned RegNo) static
Definition at line 153 of file RISCVInstPrinter.cpp.
References ArchRegNames.
Referenced by printRegName(), and RISCVInstPrinter().
getRegisterName() [2/2]
static const char* llvm::RISCVInstPrinter::getRegisterName (unsigned RegNo, unsigned AltIdx) static
printAliasInstr()
bool llvm::RISCVInstPrinter::printAliasInstr (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst(), and RISCVInstPrinter().
printAtomicMemOp()
void RISCVInstPrinter::printAtomicMemOp (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 141 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), and printRegName().
Referenced by RISCVInstPrinter().
printCSRSystemRegister()
void RISCVInstPrinter::printCSRSystemRegister (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 105 of file RISCVInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::AArch64SysReg::lookupSysRegByEncoding().
Referenced by RISCVInstPrinter().
printCustomAliasOperand()
void llvm::RISCVInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by RISCVInstPrinter().
printFenceArg()
void RISCVInstPrinter::printFenceArg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 116 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::RISCVFenceField::I, llvm::RISCVFenceField::O, llvm::RISCVFenceField::R, and llvm::RISCVFenceField::W.
Referenced by RISCVInstPrinter().
printFRMArg()
void RISCVInstPrinter::printFRMArg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 134 of file RISCVInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::RISCVFPRndMode::roundingModeToString().
Referenced by RISCVInstPrinter().
printInst()
void RISCVInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 66 of file RISCVInstPrinter.cpp.
References MI, llvm::MCInstPrinter::MRI, NoAliases, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
Referenced by RISCVInstPrinter().
printInstruction()
void llvm::RISCVInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst(), and RISCVInstPrinter().
printOperand()
void RISCVInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 85 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, llvm::MCExpr::print(), and printRegName().
Referenced by RISCVInstPrinter().
printRegName()
void RISCVInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 81 of file RISCVInstPrinter.cpp.
References getRegisterName().
Referenced by printAtomicMemOp(), printOperand(), and RISCVInstPrinter().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.h
lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.cpp