LLVM: llvm::CFLAndersAAResult Class Reference
llvm::CFLAndersAAResult Class Reference
#include "llvm/Analysis/CFLAndersAliasAnalysis.h"
Classes
class FunctionInfo
Public Member Functions
CFLAndersAAResult (std::function< const TargetLibraryInfo &(Function &F)> GetTLI)
CFLAndersAAResult (CFLAndersAAResult &&RHS)
~CFLAndersAAResult ()
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Handle invalidation events from the new pass manager.
void evict (const Function *Fn)
Evict the given function from cache.
const cflaa::AliasSummary * getAliasSummary (const Function &)
Get the alias summary for the given function Return nullptr if the summary is not found or not available.
AliasResult query (const MemoryLocation &, const MemoryLocation &)
AliasResult alias (const MemoryLocation &, const MemoryLocation &, AAQueryInfo &)
Public Member Functions inherited from llvm::AAResultBase< CFLAndersAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< CFLAndersAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
Definition at line 38 of file CFLAndersAliasAnalysis.h.
Constructor & Destructor Documentation
CFLAndersAAResult() [1/2]
CFLAndersAAResult::CFLAndersAAResult (std::function< const TargetLibraryInfo &(Function &F)> GetTLI) explicit
Definition at line 92 of file CFLAndersAliasAnalysis.cpp.
Referenced by llvm::CFLAndersAA::run().
CFLAndersAAResult() [2/2]
CFLAndersAAResult::CFLAndersAAResult (CFLAndersAAResult && RHS)
Definition at line 95 of file CFLAndersAliasAnalysis.cpp.
References ~CFLAndersAAResult().
~CFLAndersAAResult()
CFLAndersAAResult::~CFLAndersAAResult () default
Referenced by CFLAndersAAResult().
Member Function Documentation
alias()
AliasResult CFLAndersAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 880 of file CFLAndersAliasAnalysis.cpp.
References llvm::AAResultBase< DerivedT >::alias(), llvm::MayAlias, llvm::MustAlias, llvm::MemoryLocation::Ptr, and query().
evict()
void CFLAndersAAResult::evict (const Function * Fn)
Evict the given function from cache.
Definition at line 826 of file CFLAndersAliasAnalysis.cpp.
References assert().
getAliasSummary()
const AliasSummary * CFLAndersAAResult::getAliasSummary (const Function & Fn)
Get the alias summary for the given function Return nullptr if the summary is not found or not available.
Definition at line 840 of file CFLAndersAliasAnalysis.cpp.
invalidate()
bool llvm::CFLAndersAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 51 of file CFLAndersAliasAnalysis.h.
References query(), and scan().
query()
AliasResult CFLAndersAAResult::query (const MemoryLocation & LocA, const MemoryLocation & LocB)
Definition at line 848 of file CFLAndersAliasAnalysis.cpp.
References assert(), llvm::dbgs(), LLVM_DEBUG, llvm::MayAlias, llvm::NoAlias, llvm::cflaa::parentFunctionOfValue(), llvm::MemoryLocation::Ptr, and llvm::MemoryLocation::Size.
Referenced by alias().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CFLAndersAliasAnalysis.h
lib/Analysis/CFLAndersAliasAnalysis.cpp