LLVM: llvm::SystemZMCInstLower Class Reference
llvm::SystemZMCInstLower Class Reference
#include "Target/SystemZ/SystemZMCInstLower.h"
Public Member Functions
SystemZMCInstLower (MCContext &ctx, SystemZAsmPrinter &asmPrinter)
void lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand lowerOperand (const MachineOperand &MO) const
const MCExpr * getExpr (const MachineOperand &MO, MCSymbolRefExpr::VariantKind Kind) const
Detailed Description
Definition at line 24 of file SystemZMCInstLower.h.
Constructor & Destructor Documentation
SystemZMCInstLower()
SystemZMCInstLower::SystemZMCInstLower (MCContext & ctx, SystemZAsmPrinter & asmPrinter)
Definition at line 31 of file SystemZMCInstLower.cpp.
Member Function Documentation
getExpr()
const MCExpr * SystemZMCInstLower::getExpr (const MachineOperand & MO, MCSymbolRefExpr::VariantKind Kind) const
Definition at line 36 of file SystemZMCInstLower.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, and llvm::ARMBuildAttrs::Symbol.
Referenced by EmitNop(), and lowerOperand().
lower()
void SystemZMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 94 of file SystemZMCInstLower.cpp.
References llvm::MCInst::addOperand(), E, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), lowerOperand(), and llvm::MCInst::setOpcode().
lowerOperand()
MCOperand SystemZMCInstLower::lowerOperand (const MachineOperand & MO) const
Definition at line 79 of file SystemZMCInstLower.cpp.
References llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getExpr(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), getVariantKind(), llvm::MachineOperand::MO_Immediate, and llvm::MachineOperand::MO_Register.
Referenced by lower(), and llvm::SystemZAsmPrinter::PrintAsmOperand().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZMCInstLower.h
lib/Target/SystemZ/SystemZMCInstLower.cpp