LLVM: llvm::codeview::LineColumnExtractor Class Reference
llvm::codeview::LineColumnExtractor Class Reference
#include "llvm/DebugInfo/CodeView/DebugLinesSubsection.h"
Public Member Functions
Error operator() (BinaryStreamRef Stream, uint32_t &Len, LineColumnEntry &Item)
Public Attributes
const LineFragmentHeader * Header = nullptr
Detailed Description
Definition at line 70 of file DebugLinesSubsection.h.
Member Function Documentation
operator()()
Error LineColumnExtractor::operator() (BinaryStreamRef Stream, uint32_t & Len, LineColumnEntry & Item)
Definition at line 23 of file DebugLinesSubsection.cpp.
References llvm::codeview::LineBlockFragmentHeader::BlockSize, llvm::codeview::LineColumnEntry::Columns, llvm::codeview::corrupt_record, llvm::codeview::EC, llvm::codeview::LineFragmentHeader::Flags, Header, llvm::codeview::LF_HaveColumns, llvm::codeview::LineColumnEntry::LineNumbers, llvm::codeview::LineBlockFragmentHeader::NameIndex, llvm::codeview::LineColumnEntry::NameIndex, llvm::codeview::LineBlockFragmentHeader::NumLines, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), Size, and llvm::Error::success().
Member Data Documentation
Header
const LineFragmentHeader* llvm::codeview::LineColumnExtractor::Header = nullptr
Definition at line 75 of file DebugLinesSubsection.h.
Referenced by llvm::codeview::DebugLinesSubsectionRef::initialize(), and operator()().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugLinesSubsection.h
lib/DebugInfo/CodeView/DebugLinesSubsection.cpp