LLVM: llvm::MachineTraceMetrics Class Reference
llvm::MachineTraceMetrics Class Reference
#include "llvm/CodeGen/MachineTraceMetrics.h"
Classes
class Ensemble
A trace ensemble is a collection of traces selected using the same strategy, for example 'minimum resource height'.
struct FixedBlockInfo
Per-basic block information that doesn't depend on the trace through the block.
struct InstrCycles
InstrCycles represents the cycle height and depth of an instruction in a trace.
struct LiveInReg
A virtual register or regunit required by a basic block or its trace successors.
class Trace
A trace represents a plausible sequence of executed basic blocks that passes through the current basic block one.
struct TraceBlockInfo
Per-basic block information that relates to a specific trace through the block.
Public Types
enum Strategy { TS_MinInstrCount, TS_NumStrategies }
Strategies for selecting traces.
Public Member Functions
MachineTraceMetrics ()
void getAnalysisUsage (AnalysisUsage &) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
bool runOnMachineFunction (MachineFunction &) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void verifyAnalysis () const override
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
const FixedBlockInfo * getResources (const MachineBasicBlock *)
Get the fixed resource information about MBB. Compute it on demand.
ArrayRef< unsigned > getProcResourceCycles (unsigned MBBNum) const
Get the scaled number of cycles used per processor resource in MBB.
Ensemble * getEnsemble (Strategy)
Get the trace ensemble representing the given trace selection strategy.
void invalidate (const MachineBasicBlock *MBB)
Invalidate cached information about MBB.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Friends
class Ensemble
class Trace
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 87 of file MachineTraceMetrics.h.
Member Enumeration Documentation
Strategy
enum llvm::MachineTraceMetrics::Strategy
Strategies for selecting traces.
Enumerator
TS_MinInstrCount
Select the trace through a block that has the fewest instructions.
TS_NumStrategies
Definition at line 377 of file MachineTraceMetrics.h.
Constructor & Destructor Documentation
MachineTraceMetrics()
Machine Trace true MachineTraceMetrics::MachineTraceMetrics ()
Definition at line 55 of file MachineTraceMetrics.cpp.
References llvm::sys::path::begin(), and llvm::sys::path::end().
Member Function Documentation
getAnalysisUsage()
void MachineTraceMetrics::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 59 of file MachineTraceMetrics.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getEnsemble()
MachineTraceMetrics::Ensemble * MachineTraceMetrics::getEnsemble (MachineTraceMetrics::Strategy strategy)
Get the trace ensemble representing the given trace selection strategy.
The returned Ensemble object is owned by the MachineTraceMetrics analysis, and valid for the lifetime of the analysis pass.
Definition at line 384 of file MachineTraceMetrics.cpp.
References assert(), E, llvm_unreachable, TS_MinInstrCount, and TS_NumStrategies.
getProcResourceCycles()
ArrayRef< unsigned > MachineTraceMetrics::getProcResourceCycles (unsigned MBBNum) const
Get the scaled number of cycles used per processor resource in MBB.
This is an array with SchedModel.getNumProcResourceKinds() entries. The getResources() function above must have been called first.
These numbers have already been scaled by SchedModel.getResourceFactor().
Definition at line 145 of file MachineTraceMetrics.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::TargetSchedModel::getNumProcResourceKinds(), llvm::makeArrayRef(), and llvm::SmallVectorBase::size().
Referenced by llvm::MachineTraceMetrics::Ensemble::getLoopFor().
getResources()
const MachineTraceMetrics::FixedBlockInfo * MachineTraceMetrics::getResources (const MachineBasicBlock * MBB)
Get the fixed resource information about MBB. Compute it on demand.
Compute the resource usage in basic block MBB.
Definition at line 98 of file MachineTraceMetrics.cpp.
References assert(), llvm::MachineBasicBlock::getNumber(), llvm::TargetSchedModel::getNumProcResourceKinds(), llvm::TargetSchedModel::getResourceFactor(), llvm::TargetSchedModel::getWriteProcResBegin(), llvm::TargetSchedModel::getWriteProcResEnd(), llvm::MachineTraceMetrics::FixedBlockInfo::HasCalls, llvm::TargetSchedModel::hasInstrSchedModel(), llvm::MachineTraceMetrics::FixedBlockInfo::hasResources(), if(), InstrCount, llvm::MachineTraceMetrics::FixedBlockInfo::InstrCount, llvm::MCSchedClassDesc::isValid(), MI, llvm::TargetSchedModel::resolveSchedClass(), and llvm::PPCISD::SC.
Referenced by llvm::MachineTraceMetrics::Ensemble::getLoopFor(), and isExitingLoop().
invalidate()
void MachineTraceMetrics::invalidate (const MachineBasicBlock * MBB)
Invalidate cached information about MBB.
This must be called before MBB is erased, or the CFG is otherwise changed.
This invalidates per-block information about resource usage for MBB only, and it invalidates per-trace information for any trace that passes through MBB.
Call Ensemble::getTrace() again to update any trace handles.
Definition at line 397 of file MachineTraceMetrics.cpp.
References llvm::dbgs(), llvm::MachineBasicBlock::getNumber(), LLVM_DEBUG, llvm::printMBBReference(), and TS_NumStrategies.
releaseMemory()
void MachineTraceMetrics::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 80 of file MachineTraceMetrics.cpp.
References TS_NumStrategies.
runOnMachineFunction()
bool MachineTraceMetrics::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 66 of file MachineTraceMetrics.cpp.
References llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getNumBlockIDs(), llvm::TargetSchedModel::getNumProcResourceKinds(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetSchedModel::init(), llvm::SmallVectorImpl< T >::resize(), and llvm::ARM_MB::ST.
verifyAnalysis()
void MachineTraceMetrics::verifyAnalysis () const override virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented from llvm::Pass.
Definition at line 406 of file MachineTraceMetrics.cpp.
References assert(), Loops, loops, and TS_NumStrategies.
Friends And Related Function Documentation
Ensemble
friend class Ensemble friend
Definition at line 96 of file MachineTraceMetrics.h.
Referenced by isExitingLoop().
Trace
friend class Trace friend
Definition at line 97 of file MachineTraceMetrics.h.
Member Data Documentation
ID
char MachineTraceMetrics::ID = 0 static
Definition at line 99 of file MachineTraceMetrics.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineTraceMetrics.h
lib/CodeGen/MachineTraceMetrics.cpp