LLVM: llvm::LiveIntervals::HMEditor Class Reference
llvm::LiveIntervals::HMEditor Class Reference
Toolkit used by handleMove to trim or extend live intervals.
Public Member Functions
HMEditor (LiveIntervals &LIS, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI, SlotIndex OldIdx, SlotIndex NewIdx, bool UpdateFlags)
LiveRange * getRegUnitLI (unsigned Unit)
void updateAllRanges (MachineInstr *MI)
Update all live ranges touched by MI, assuming a move from OldIdx to NewIdx.
Detailed Description
Toolkit used by handleMove to trim or extend live intervals.
Definition at line 954 of file LiveIntervals.cpp.
Constructor & Destructor Documentation
HMEditor()
llvm::LiveIntervals::HMEditor::HMEditor (LiveIntervals & LIS, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI, SlotIndex OldIdx, SlotIndex NewIdx, bool UpdateFlags) inline
Definition at line 965 of file LiveIntervals.cpp.
Member Function Documentation
getRegUnitLI()
LiveRange* llvm::LiveIntervals::HMEditor::getRegUnitLI (unsigned Unit) inline
Definition at line 975 of file LiveIntervals.cpp.
References llvm::LiveIntervals::getCachedRegUnit(), llvm::LiveIntervals::getRegUnit(), and llvm::MachineRegisterInfo::isReservedRegUnit().
updateAllRanges()
void llvm::LiveIntervals::HMEditor::updateAllRanges (MachineInstr * MI) inline
Update all live ranges touched by MI, assuming a move from OldIdx to NewIdx.
Definition at line 983 of file LiveIntervals.cpp.
References llvm::LiveRange::advanceTo(), llvm::LaneBitmask::any(), assert(), llvm::LiveRange::begin(), llvm::MachineBasicBlock::begin(), llvm::copy(), llvm::dbgs(), llvm::VNInfo::def, E, llvm::sys::path::end(), llvm::LiveRange::end(), llvm::MachineBasicBlock::end(), llvm::LiveRange::find(), llvm::SlotIndex::getBaseIndex(), llvm::SlotIndex::getDeadSlot(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::SlotIndexes::getInstructionFromIndex(), llvm::SlotIndexes::getInstructionIndex(), llvm::LiveIntervals::getInterval(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::SlotIndexes::getMBBFromIndex(), llvm::SlotIndexes::getNextNonNullIndex(), llvm::LaneBitmask::getNone(), llvm::SlotIndex::getRegSlot(), llvm::LiveIntervals::getSlotIndexes(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::TargetRegisterInfo::hasRegUnit(), llvm::LiveInterval::hasSubRanges(), if(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SlotIndex::isEarlierEqualInstr(), llvm::SlotIndex::isEarlierInstr(), llvm::Register::isPhysicalRegister(), llvm::SlotIndex::isSameInstr(), llvm::MIBundleOperandIteratorBase< ValueT >::isValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, llvm::lower_bound(), llvm::max(), MI, llvm::mi_bundle_ops(), llvm::MachineInstr::operands(), llvm::PrintLaneMask(), llvm::printReg(), llvm::printRegUnit(), Reg, llvm::LiveRange::removeValNo(), llvm::LiveInterval::subranges(), SubReg, llvm::MachineRegisterInfo::use_nodbg_operands(), and llvm::LiveRange::verify().
Referenced by llvm::LiveIntervals::handleMove(), and llvm::LiveIntervals::handleMoveIntoBundle().
The documentation for this class was generated from the following file:
lib/CodeGen/LiveIntervals.cpp