LLVM: llvm::BTFTypeEnum Class Reference
llvm::BTFTypeEnum Class Reference
Handle enumerate type.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFTypeEnum (const DICompositeType *ETy, uint32_t NumValues)
uint32_t getSize ()
Get the size of this BTF type entry.
void completeType (BTFDebug &BDebug)
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
void emitType (MCStreamer &OS)
Emit types for this BTF type entry.
Public Member Functions inherited from llvm::BTFTypeBase
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
Additional Inherited Members
Protected Attributes inherited from llvm::BTFTypeBase
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
Handle enumerate type.
Definition at line 93 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFTypeEnum()
BTFTypeEnum::BTFTypeEnum (const DICompositeType * ETy, uint32_t NumValues)
Definition at line 154 of file BTFDebug.cpp.
References llvm::BTFTypeBase::BTFType, llvm::DIType::getSizeInBits(), llvm::BTF::CommonType::Info, llvm::BTFTypeBase::Kind, llvm::BTFTypeBase::roundupToBytes(), and llvm::BTF::CommonType::Size.
Member Function Documentation
completeType()
void BTFTypeEnum::completeType (BTFDebug & BDebug) virtual
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
Reimplemented from llvm::BTFTypeBase.
Definition at line 160 of file BTFDebug.cpp.
References llvm::BTFDebug::addString(), llvm::BTFTypeBase::BTFType, llvm::DICompositeType::getElements(), llvm::DIType::getName(), llvm::BTFTypeBase::IsCompleted, llvm::BTF::CommonType::NameOff, llvm::BTF::BTFEnum::NameOff, and llvm::BTF::BTFEnum::Val.
emitType()
void BTFTypeEnum::emitType (MCStreamer & OS) virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented from llvm::BTFTypeBase.
Definition at line 179 of file BTFDebug.cpp.
References llvm::MCStreamer::EmitIntValue(), and llvm::BTFTypeBase::emitType().
getSize()
uint32_t llvm::BTFTypeEnum::getSize () inline virtual
Get the size of this BTF type entry.
Reimplemented from llvm::BTFTypeBase.
Definition at line 99 of file BTFDebug.h.
References llvm::BTF::BTFEnumSize, llvm::BTFTypeBase::completeType(), llvm::BTFTypeBase::emitType(), and llvm::BTFTypeBase::getSize().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp