LLVM: llvm::EngineBuilder Class Reference
llvm::EngineBuilder Class Reference
Builder class for ExecutionEngines.
#include "llvm/ExecutionEngine/ExecutionEngine.h"
Public Member Functions
EngineBuilder ()
Default constructor for EngineBuilder.
EngineBuilder (std::unique_ptr< Module > M)
Constructor for EngineBuilder.
~EngineBuilder ()
EngineBuilder & setEngineKind (EngineKind::Kind w)
setEngineKind - Controls whether the user wants the interpreter, the JIT, or whichever engine works.
EngineBuilder & setMCJITMemoryManager (std::unique_ptr< RTDyldMemoryManager > mcjmm)
setMCJITMemoryManager - Sets the MCJIT memory manager to use.
EngineBuilder & setMemoryManager (std::unique_ptr< MCJITMemoryManager > MM)
EngineBuilder & setSymbolResolver (std::unique_ptr< LegacyJITSymbolResolver > SR)
EngineBuilder & setErrorStr (std::string *e)
setErrorStr - Set the error string to write to on error.
EngineBuilder & setOptLevel (CodeGenOpt::Level l)
setOptLevel - Set the optimization level for the JIT.
EngineBuilder & setTargetOptions (const TargetOptions &Opts)
setTargetOptions - Set the target options that the ExecutionEngine target is using.
EngineBuilder & setRelocationModel (Reloc::Model RM)
setRelocationModel - Set the relocation model that the ExecutionEngine target is using.
EngineBuilder & setCodeModel (CodeModel::Model M)
setCodeModel - Set the CodeModel that the ExecutionEngine target data is using.
EngineBuilder & setMArch (StringRef march)
setMArch - Override the architecture set by the Module's triple.
EngineBuilder & setMCPU (StringRef mcpu)
setMCPU - Target a specific cpu type.
EngineBuilder & setVerifyModules (bool Verify)
setVerifyModules - Set whether the JIT implementation should verify IR modules during compilation.
template<typename StringSequence >
EngineBuilder & setMAttrs (const StringSequence &mattrs)
setMAttrs - Set cpu-specific attributes.
LLVM_ATTRIBUTE_DEPRECATED (inline void setUseOrcMCJITReplacement(bool UseOrcMCJITReplacement), "ORCv1 utilities (including OrcMCJITReplacement) are deprecated. Please " "use ORCv2/LLJIT instead (see docs/ORCv2.rst)")
void setUseOrcMCJITReplacement (ORCv1DeprecationAcknowledgement, bool UseOrcMCJITReplacement)
void setEmulatedTLS (bool EmulatedTLS)
TargetMachine * selectTarget ()
TargetMachine * selectTarget (const Triple &TargetTriple, StringRef MArch, StringRef MCPU, const SmallVectorImpl< std::string > &MAttrs)
selectTarget - Pick a target either via -march or by guessing the native arch.
ExecutionEngine * create ()
ExecutionEngine * create (TargetMachine *TM)
Detailed Description
Builder class for ExecutionEngines.
Use this by stack-allocating a builder, chaining the various set* methods, and terminating it with a .create() call.
Definition at line 526 of file ExecutionEngine.h.
Constructor & Destructor Documentation
EngineBuilder() [1/2]
EngineBuilder::EngineBuilder ()
Default constructor for EngineBuilder.
Definition at line 473 of file ExecutionEngine.cpp.
EngineBuilder() [2/2]
EngineBuilder::EngineBuilder (std::unique_ptr< Module > M)
Constructor for EngineBuilder.
Definition at line 475 of file ExecutionEngine.cpp.
References ~EngineBuilder().
~EngineBuilder()
EngineBuilder::~EngineBuilder () default
Referenced by EngineBuilder().
Member Function Documentation
create() [1/2]
ExecutionEngine* llvm::EngineBuilder::create () inline
Definition at line 661 of file ExecutionEngine.h.
References DEFINE_SIMPLE_CONVERSION_FUNCTIONS, setUseOrcMCJITReplacement(), and llvm::SystemZISD::TM.
Referenced by LLVMCreateExecutionEngineForModule(), LLVMCreateInterpreterForModule(), LLVMCreateJITCompilerForModule(), and LLVMCreateMCJITCompilerForModule().
create() [2/2]
ExecutionEngine * EngineBuilder::create (TargetMachine * TM)
Definition at line 510 of file ExecutionEngine.cpp.
References llvm::ExecutionEngine::addModule(), llvm::errs(), llvm::TargetMachine::getTarget(), llvm::Target::hasJIT(), llvm::ExecutionEngine::InterpCtor, llvm::EngineKind::Interpreter, llvm::EngineKind::JIT, llvm::sys::DynamicLibrary::LoadLibraryPermanently(), llvm::ExecutionEngine::MCJITCtor, llvm::ExecutionEngine::OrcMCJITReplacementCtor, and llvm::ExecutionEngine::setVerifyModules().
LLVM_ATTRIBUTE_DEPRECATED()
llvm::EngineBuilder::LLVM_ATTRIBUTE_DEPRECATED (inline void setUseOrcMCJITReplacementbool UseOrcMCJITReplacement, "ORCv1 utilities (including OrcMCJITReplacement) are deprecated. Please " "use ORCv2/LLJIT instead (see docs/ORCv2.rst)")
selectTarget() [1/2]
TargetMachine * EngineBuilder::selectTarget ()
Definition at line 26 of file TargetSelect.cpp.
References llvm::EngineKind::Interpreter, llvm::Triple::setTriple(), and llvm::TT.
selectTarget() [2/2]
TargetMachine * EngineBuilder::selectTarget (const Triple & TargetTriple, StringRef MArch, StringRef MCPU, const SmallVectorImpl< std::string > & MAttrs)
selectTarget - Pick a target either via -march or by guessing the native arch.
Add any CPU features specified via -mcpu or -mattr.
Definition at line 39 of file TargetSelect.cpp.
References llvm::SubtargetFeatures::AddFeature(), assert(), llvm::Target::createTargetMachine(), llvm::SmallVectorBase::empty(), llvm::StringRef::empty(), llvm::TargetOptions::EmulatedTLS, llvm::Error, llvm::TargetOptions::ExplicitEmulatedTLS, llvm::find_if(), llvm::Triple::getArchTypeForLLVMName(), llvm::Target::getName(), llvm::sys::getProcessTriple(), llvm::SubtargetFeatures::getString(), llvm::Triple::getTriple(), I, llvm::TargetRegistry::lookupTarget(), llvm::TargetMachine::Options, llvm::Triple::setArch(), llvm::Triple::setTriple(), llvm::SmallVectorBase::size(), llvm::TargetRegistry::targets(), and llvm::Triple::UnknownArch.
setCodeModel()
EngineBuilder& llvm::EngineBuilder::setCodeModel (CodeModel::Model M) inline
setCodeModel - Set the CodeModel that the ExecutionEngine target data is using.
Defaults to target specific default "CodeModel::JITDefault".
Definition at line 605 of file ExecutionEngine.h.
Referenced by LLVMCreateMCJITCompilerForModule().
setEmulatedTLS()
void llvm::EngineBuilder::setEmulatedTLS (bool EmulatedTLS) inline
Definition at line 648 of file ExecutionEngine.h.
setEngineKind()
EngineBuilder& llvm::EngineBuilder::setEngineKind (EngineKind::Kind w) inline
setEngineKind - Controls whether the user wants the interpreter, the JIT, or whichever engine works.
This option defaults to EngineKind::Either.
Definition at line 556 of file ExecutionEngine.h.
Referenced by LLVMCreateExecutionEngineForModule(), LLVMCreateInterpreterForModule(), LLVMCreateJITCompilerForModule(), and LLVMCreateMCJITCompilerForModule().
setErrorStr()
EngineBuilder& llvm::EngineBuilder::setErrorStr (std::string * e) inline
setErrorStr - Set the error string to write to on error.
This option defaults to NULL.
Definition at line 576 of file ExecutionEngine.h.
References llvm::numbers::e.
Referenced by LLVMCreateExecutionEngineForModule(), LLVMCreateInterpreterForModule(), LLVMCreateJITCompilerForModule(), and LLVMCreateMCJITCompilerForModule().
setMArch()
EngineBuilder& llvm::EngineBuilder::setMArch (StringRef march) inline
setMArch - Override the architecture set by the Module's triple.
Definition at line 611 of file ExecutionEngine.h.
References llvm::StringRef::begin(), and llvm::StringRef::end().
setMAttrs()
template<typename StringSequence > EngineBuilder& llvm::EngineBuilder::setMAttrs (const StringSequence & mattrs) inline
setMAttrs - Set cpu-specific attributes.
Definition at line 631 of file ExecutionEngine.h.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorImpl< T >::clear(), and LLVM_ATTRIBUTE_DEPRECATED.
setMCJITMemoryManager()
EngineBuilder & EngineBuilder::setMCJITMemoryManager (std::unique_ptr< RTDyldMemoryManager > mcjmm)
setMCJITMemoryManager - Sets the MCJIT memory manager to use.
This allows clients to customize their memory allocation policies for the MCJIT. This is only appropriate for the MCJIT; setting this and configuring the builder to create anything other than MCJIT will cause a runtime error. If create() is called and is successful, the created engine takes ownership of the memory manager. This option defaults to NULL.
Definition at line 490 of file ExecutionEngine.cpp.
Referenced by LLVMCreateMCJITCompilerForModule().
setMCPU()
EngineBuilder& llvm::EngineBuilder::setMCPU (StringRef mcpu) inline
setMCPU - Target a specific cpu type.
Definition at line 617 of file ExecutionEngine.h.
References llvm::StringRef::begin(), and llvm::StringRef::end().
setMemoryManager()
EngineBuilder & EngineBuilder::setMemoryManager (std::unique_ptr< MCJITMemoryManager > MM)
Definition at line 499 of file ExecutionEngine.cpp.
setOptLevel()
EngineBuilder& llvm::EngineBuilder::setOptLevel (CodeGenOpt::Level l) inline
setOptLevel - Set the optimization level for the JIT.
This option defaults to CodeGenOpt::Default.
Definition at line 583 of file ExecutionEngine.h.
Referenced by LLVMCreateJITCompilerForModule(), and LLVMCreateMCJITCompilerForModule().
setRelocationModel()
EngineBuilder& llvm::EngineBuilder::setRelocationModel (Reloc::Model RM) inline
setRelocationModel - Set the relocation model that the ExecutionEngine target is using.
Defaults to target specific default "Reloc::Default".
Definition at line 597 of file ExecutionEngine.h.
References llvm::NVPTX::PTXCvtMode::RM.
setSymbolResolver()
EngineBuilder & EngineBuilder::setSymbolResolver (std::unique_ptr< LegacyJITSymbolResolver > SR)
Definition at line 505 of file ExecutionEngine.cpp.
setTargetOptions()
EngineBuilder& llvm::EngineBuilder::setTargetOptions (const TargetOptions & Opts) inline
setTargetOptions - Set the target options that the ExecutionEngine target is using.
Defaults to TargetOptions().
Definition at line 590 of file ExecutionEngine.h.
Referenced by LLVMCreateMCJITCompilerForModule().
setUseOrcMCJITReplacement()
void llvm::EngineBuilder::setUseOrcMCJITReplacement (ORCv1DeprecationAcknowledgement , bool UseOrcMCJITReplacement) inline
Definition at line 643 of file ExecutionEngine.h.
Referenced by create().
setVerifyModules()
EngineBuilder& llvm::EngineBuilder::setVerifyModules (bool Verify) inline
setVerifyModules - Set whether the JIT implementation should verify IR modules during compilation.
Definition at line 624 of file ExecutionEngine.h.
References Verify.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/ExecutionEngine.h
lib/ExecutionEngine/ExecutionEngine.cpp
lib/ExecutionEngine/TargetSelect.cpp