LLVM: llvm::Value Class Reference
llvm::Value Class Reference
LLVM Value Representation.
#include "llvm/IR/Value.h"
Public Types
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Attributes
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Friends
class ValueAsMetadata
class ValueHandleBase
Detailed Description
LLVM Value Representation.
This is a very important LLVM class. It is the base class of all values computed by a program that may be used as operands to other values. Value is the super class of other important classes such as Instruction and Function. All Values have a Type. Type is not a subclass of Value. Some values can have a name and they belong to some Module. Setting the name on the Value automatically updates the module's symbol table.
Every value has a "use list" that keeps track of which other Values are using this Value. A Value can also have an arbitrary number of ValueHandle objects that watch it and listen to RAUW and Destroy events. See llvm/IR/ValueHandle.h for details.
Definition at line 74 of file Value.h.
Member Typedef Documentation
const_use_iterator
using llvm::Value::const_use_iterator = use_iterator_impl<const Use>
Definition at line 353 of file Value.h.
const_user_iterator
using llvm::Value::const_user_iterator = user_iterator_impl<const User>
Definition at line 390 of file Value.h.
use_iterator
using llvm::Value::use_iterator = use_iterator_impl<Use>
Definition at line 352 of file Value.h.
user_iterator
using llvm::Value::user_iterator = user_iterator_impl<User>
Definition at line 389 of file Value.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned protected
The number of operands in the subclass.
This member is defined by this class, but not used for anything. Subclasses can use it to store their number of operands, if they have any.
This is stored here to save space in User on 64-bit hosts. Since most instances of Value have operands, 32-bit hosts aren't significantly affected.
Note, this should NOT be used directly by any class other than User. User uses this value to find the Use list.
Enumerator
NumUserOperandsBits
Definition at line 115 of file Value.h.
ValueTy
enum llvm::Value::ValueTy
Concrete subclass of this.
An enumeration for keeping track of the concrete subclass of Value that is actually instantiated. Values of this enumeration are kept in the Value classes SubclassID field. They are used for concrete type identification.
Definition at line 465 of file Value.h.
Constructor & Destructor Documentation
Value() [1/2]
Value::Value (Type * Ty, unsigned scid) protected
Definition at line 53 of file Value.cpp.
References assert(), llvm::MCID::Call, llvm::Type::isFirstClassType(), llvm::Type::isStructTy(), and llvm::Type::isVoidTy().
Referenced by llvm::cl::ValuesClass::apply(), llvm::BasicBlock::getContext(), llvm::getValueProfDataFromInst(), setBranchWeights(), and ValuesOverlap().
~Value()
Value::~Value () protected
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
As a size optimization, the destructor has been protected, and the caller should manually call deleteValue.
Definition at line 73 of file Value.cpp.
References assert(), llvm::dbgs(), getName(), llvm::ValueAsMetadata::handleDeletion(), isUsedByMetadata(), use_empty(), users(), and llvm::ValueHandleBase::ValueIsDeleted().
Value() [2/2]
llvm::Value::Value (const Value &) delete
Member Function Documentation
addUse()
void llvm::Value::addUse (Use & U) inline
This method should only be used by the Use class.
Definition at line 457 of file Value.h.
Referenced by llvm::Use::set(), and llvm::Use::swap().
assertModuleIsMaterialized()
void llvm::Value::assertModuleIsMaterialized () const inline
Definition at line 337 of file Value.h.
References assertModuleIsMaterializedImpl().
Referenced by use_begin(), use_empty(), user_back(), user_begin(), user_empty(), users(), and uses().
assertModuleIsMaterializedImpl()
void Value::assertModuleIsMaterializedImpl () const
Definition at line 352 of file Value.cpp.
References assert(), llvm::dyn_cast(), llvm::GlobalValue::getParent(), and llvm::Module::isMaterialized().
Referenced by assertModuleIsMaterialized(), and replaceUsesWithIf().
clearSubclassOptionalData()
void llvm::Value::clearSubclassOptionalData () inline
Clear the optional flags contained in this value.
Definition at line 496 of file Value.h.
References SubclassOptionalData.
Referenced by ClearSubclassDataAfterReassociation(), and LinearizeExprTree().
deleteValue()
void Value::deleteValue ()
Delete a pointer to a generic Value.
Definition at line 99 of file Value.cpp.
References llvm::StringMapEntry< ValueTy >::Destroy(), getValueID(), getValueName(), llvm_unreachable, Name, and setValueName().
Referenced by llvm::BitcodeReaderValueList::assignValue(), llvm::CloneFunction(), createAndInstr(), llvm::ilist_alloc_traits< Instruction >::deleteNode(), llvm::ilist_alloc_traits< MemoryAccess >::deleteNode(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), FoldCondBranchOnPHI(), FunctionNumber(), isOnlyReachableViaThisEdge(), okayForPHIOfOps(), llvm::ValueDeleter::operator()(), shouldRotateLoopExitingLatch(), and llvm::sroa::AllocaSliceRewriter::visit().
DoPHITranslation() [1/2]
const Value * Value::DoPHITranslation (const BasicBlock * CurBB, const BasicBlock * PredBB) const
Translate PHI node to its predecessor from the given basic block.
If this value is a PHI node with CurBB as its parent, return the value in the PHI node corresponding to PredBB. If not, return ourself. This is useful if you want to know the value something has in a predecessor block.
Definition at line 736 of file Value.cpp.
References llvm::dyn_cast(), and llvm::PHINode::getIncomingValueForBlock().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), DoPHITranslation(), foldOperationIntoPhiValue(), okayForPHIOfOps(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), and stripInBoundsOffsets().
DoPHITranslation() [2/2]
Value* llvm::Value::DoPHITranslation (const BasicBlock * CurBB, const BasicBlock * PredBB) inline
Definition at line 645 of file Value.h.
References DoPHITranslation().
dump()
LLVM_DUMP_METHOD void Value::dump () const
Support for debugging, callable in GDB: V->dump()
Definition at line 4466 of file AsmWriter.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
Referenced by analyzeLoopUnrollCost(), AreSequentialAccesses(), llvm::coro::Shape::buildFrom(), buildMultiplyTree(), Cleanup(), llvm::DbgValueLoc::dump(), llvm::GVNExpression::Expression::dump(), dump(), dumpIR(), emitSignedInt64(), fail(), getChainID(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::ExecutionEngine::InitializeMemory(), isPromotedResultSafe(), isUnconditionalBranch(), normalizePredicate(), llvm::GVN::run(), scaleWeights(), and sinkAndCmp0Expression().
getContext()
LLVMContext & Value::getContext () const
All values hold a context through their type.
Definition at line 744 of file Value.cpp.
References llvm::Type::getContext().
Referenced by llvm::GlobalVariable::addAttribute(), llvm::Function::addAttribute(), llvm::Function::addAttributes(), llvm::Function::addDereferenceableAttr(), llvm::Function::addDereferenceableOrNullAttr(), llvm::Function::addDereferenceableOrNullParamAttr(), llvm::Function::addDereferenceableParamAttr(), llvm::Function::addParamAttr(), llvm::Function::addParamAttrs(), llvm::LoopAccessInfo::addRuntimeChecks(), annotateAnyAllocSite(), annotateDereferenceableBytes(), annotateNonNullAndDereferenceable(), llvm::SelectInst::areInvalidOperands(), BitCastConstantVector(), BuildConstantFromSCEV(), canonicalizeSaturatedAdd(), CanShareConstantPoolEntry(), llvm::changeToUnreachable(), llvm::misexpect::checkFrontendInstrumentation(), llvm::Function::clearGC(), llvm::FenceInst::cloneImpl(), llvm::UnreachableInst::cloneImpl(), CloneLoop(), collectInsertionElements(), collectShuffleElements(), collectSingleShuffleElements(), combineLoadToOperationType(), llvm::ShuffleVectorInst::commute(), computeAddrSpace(), computeBytesPoppedByCalleeForSRet(), llvm::ComputeMultiple(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computeRecurrenceType(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), convert_i1_to_i8(), ConvertDoubleToBytes(), ConvertToSInt(), llvm::copyMetadataForLoad(), llvm::copyNonnullMetadata(), llvm::copyRangeMetadata(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::ARMConstantPoolConstant::Create(), llvm::CallBrInst::Create(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createCallInst(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::createFalkorMarkStridedAccessesPass(), llvm::InstCombiner::CreateNonTerminatorUnreachable(), llvm::createObjCARCOptPass(), CreatePrologue(), llvm::createSeparateConstOffsetFromGEPPass(), createUnreachableSwitchDefault(), despeculateCountZeros(), detectShiftUntilZeroIdiom(), emitSignedInt64(), evaluateInDifferentElementOrder(), expandBounds(), llvm::SCEVExpander::expandUnionPredicate(), llvm::SCEVExpander::expandWrapPredicate(), ExtractConstantBytes(), extractMDNode(), findBasePointer(), llvm::FindDbgAddrUses(), llvm::findDbgUsers(), llvm::findDbgValues(), fixupBranchWeights(), foldBitcastExtElt(), foldConstantInsEltIntoShuffle(), foldCtpop(), foldCttzCtlz(), foldICmpShlOne(), foldIdentityPaddedShuffles(), foldInsSequenceIntoSplat(), llvm::InstCombiner::FoldShiftByConstant(), llvm::formLCSSAForInstructions(), genLoopLimit(), llvm::ConstantAggregateZero::get(), llvm::ValueAsMetadata::get(), llvm::ConstantPointerNull::get(), llvm::ConstantExpr::get(), llvm::UndefValue::get(), getArrayElements(), getAsConstantIndexedAddress(), llvm::GlobalVariable::getAttributesAsList(), llvm::IRPosition::getAttrs(), getBoundsCheckCond(), getComparePred(), llvm::LazyValueInfo::getConstant(), getConstantAt(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::ValueAsMetadata::getContext(), getEdgeValueLocal(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getFCmp(), llvm::Function::getGC(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::ValueAsMetadata::getIfExists(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), getMemCmpLoad(), getName(), getNegativeIsTrueBoolVec(), llvm::CallBase::getNumSubclassExtraOperands(), llvm::getObjectSize(), getOffsetFromIndices(), getParentPad(), llvm::GlobalValue::getPartition(), getPoisonFor(), llvm::FastISel::getRegForValue(), getRelevantOperands(), GetRMWLibcall(), llvm::ConstantExpr::getSelect(), GetSortedValueDataFromCallTargets(), llvm::ConstantDataVector::getSplat(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::SITargetLowering::getTgtMemIntrinsic(), getType(), llvm::ConstantStruct::getTypeForElements(), getUnderlyingArgRegs(), getValueName(), handleBrSelExpect(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::Constant::handleOperandChange(), handleSwitchExpect(), hasSameExtUse(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::insertDebugValuesForPHIs(), insertLifetimeMarkersSurroundingCall(), insertSpills(), llvm::isBytewiseValue(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), llvm::slpvectorizer::BoUpSLP::isLoadCombineReductionCandidate(), isLoadInvariantInLoop(), isOrdered(), isReportingError(), isSupportedGuardInstruction(), llvm::LibCallSimplifier::LibCallSimplifier(), LLVMGetOperand(), LLVMSetParamAlignment(), lookThroughAnd(), llvm::BlockAddress::lookup(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerSubFn(), makeBitReverse(), llvm::makeGuardControlFlowExplicit(), makeStatepointExplicitImpl(), llvm::IRAttributeManifest::manifestAttrs(), matchesOr(), mayLoopAccessLocation(), llvm::MergeBasicBlockIntoOnlyPred(), mergeCleanupPad(), mergeInlinedArrayAllocas(), llvm::EscapeEnumerator::Next(), OptimizeGlobalAddressOfMalloc(), optimizeMemCmpConstantSize(), OptimizeNoopCopyExpression(), optimizeVectorResizeWithIntegerBitCasts(), parseOptionalLinkageAux(), llvm::CallBase::populateBundleOperandInfos(), processCallSite(), processCmp(), processUDivOrURem(), processUGT_ADDCST_ADD(), llvm::pgo::promoteIndirectCall(), llvm::remapInstruction(), llvm::Function::removeAttribute(), llvm::Function::removeAttributes(), llvm::Function::removeParamAttr(), llvm::Function::removeParamAttrs(), llvm::coro::replaceCoroFree(), llvm::replaceDbgValueForAlloca(), replaceExtractElements(), ReplaceFPIntrinsicWithCall(), ReplaceUsesOfWith(), rewriteDebugUsers(), RewriteUsesOfClonedInstructions(), llvm::salvageDebugInfoForDbgValues(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), llvm::FastISel::selectBinaryOp(), llvm::FastISel::selectFNeg(), llvm::MemIntrinsicBase< AnyMemIntrinsic >::setDestAlignment(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), llvm::Function::setEntryCount(), llvm::Function::setGC(), setNoClobberMetadata(), llvm::GlobalValue::setPartition(), llvm::setProfMetadata(), llvm::Instruction::setProfWeight(), llvm::Function::setPrologueData(), AAValueConstantRangeImpl::setRangeMetadataIfisBetterRange(), llvm::GlobalObject::setSection(), llvm::Function::setSectionPrefix(), setUsedInitializer(), setValueName(), shouldFixMainFunction(), ShrinkDemandedConstant(), shrinkFPConstant(), SimplifyICmpInst(), simplifyICmpWithBinOp(), simplifyNeonTbl1(), SimplifyRelativeLoad(), simplifyX86extrq(), simplifyX86pshufb(), simplifyX86vpermilvar(), simplifyX86vpermv(), llvm::SplitCriticalEdge(), splitGlobal(), splitMergedValStore(), SRAGlobal(), TryToShrinkGlobalToBoolean(), TryToSinkInstruction(), tryUnmergingGEPsAcrossIndirectBr(), turnGuardIntoBranch(), TurnSwitchRangeIntoICmp(), llvm::UnrollLoop(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), updateBranchWeights(), llvm::CallInst::updateProfWeight(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::UpgradeGlobalVariable(), llvm::UpgradeIntrinsicCall(), llvm::ValueHandleBase::ValueIsDeleted(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitAllocSite(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitPtrToInt(), llvm::Interpreter::visitReturnInst(), llvm::InstCombiner::visitShuffleVectorInst(), willNotOverflow(), wrapConstantAsMetadata(), and X86ChooseCmpImmediateOpcode().
getName()
StringRef Value::getName () const
Return a constant reference to the value's name.
This guaranteed to return the same reference as long as the value is not modified. If the value has a name, this does a hashtable lookup, so it's not free.
Definition at line 215 of file Value.cpp.
References assert(), llvm::StringMapEntry< ValueTy >::Create(), llvm::StringRef::empty(), llvm::StringRef::find_first_of(), getContext(), llvm::StringMapEntry< ValueTy >::getKey(), getSymTab(), getType(), getValueName(), hasName(), llvm::Twine::isTriviallyEmpty(), llvm::max(), NonGlobalValueMaxNameSize, llvm::StringRef::npos, llvm::StringMapEntryStorage< ValueTy >::setValue(), setValueName(), llvm::StringRef::size(), llvm::ARM_MB::ST, llvm::StringRef::substr(), and llvm::Twine::toStringRef().
Referenced by AddAliasScopeMetadata(), llvm::SSAUpdaterBulk::AddAvailableValue(), AddCalls(), addForcedAttributes(), addMappingsFromTLI(), llvm::SSAUpdaterBulk::AddUse(), llvm::X86FrameLowering::adjustForHiPEPrologue(), analyzeParsePointLiveness(), llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), assertBranchOrSelectConditionHoisted(), assureFPCallStub(), llvm::WinException::beginFunction(), llvm::CFGMST< Edge, BBInfo >::buildEdges(), buildFrameType(), llvm::BlockFrequencyInfo::calculate(), llvm::BranchProbabilityInfo::calculate(), calculateCXXStateNumbers(), calculateSEHStateNumbers(), llvm::Interpreter::callExternalFunction(), llvm::canConstantFoldCallTo(), canCreateThunkFor(), CanGenerateTest(), llvm::InstCombiner::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeLowbitMask(), canonicalizeSaturatedAdd(), CanPropagatePredecessorsForPHIs(), llvm::canRenameComdatFunc(), llvm::changeToInvokeAndSplitBasicBlock(), cheapToScalarize(), llvm::Attributor::checkForAllCallSites(), llvm::classifyEHPersonality(), llvm::CloneBasicBlock(), llvm::CloneFunction(), llvm::orc::cloneFunctionDecl(), llvm::orc::cloneGlobalAliasDecl(), llvm::orc::cloneGlobalVariableDecl(), cloneInstForMustTail(), CloneInstructionInExitBlock(), llvm::JumpThreadingPass::CloneInstructions(), CloneLoopBlocks(), collectCallSiteParameters(), llvm::colorEHFunclets(), combineInstructionsOverFunction(), llvm::InstCombiner::combineLoadToNewType(), llvm::InstCombiner::commonShiftTransforms(), compareNames(), computeAddrSpace(), llvm::ConstantFoldCall(), ConstructSSAForLoadSet(), llvm::convertToDeclaration(), ConvertToSInt(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), llvm::createBlockExtractorPass(), llvm::OpenMPIRBuilder::CreateCancel(), createCloneDeclaration(), llvm::createConstantHoistingPass(), createFPFnStub(), llvm::createGCInfoPrinter(), createHWLoopAnalysis(), llvm::createPGOFuncNameMetadata(), createPowWithIntegerExponent(), CreatePrologue(), createReplacementInstr(), llvm::createSampleProfileLoaderPass(), llvm::createScalarizerPass(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), CreateVarArgHelper(), createWrapper(), llvm::VPBlockBase::deleteCFG(), deleteDeadInstruction(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::NVPTXAsmPrinter::doFinalization(), doPromotion(), llvm::GVNExpression::Expression::dump(), llvm::DomTreeUpdater::dump(), llvm::AliasSetTracker::dump(), llvm::CFGMST< Edge, BBInfo >::dumpEdges(), dumpIR(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), llvm::orc::IRSpeculationLayer::emit(), EmitCamlGlobal(), llvm::AsmPrinter::EmitDebugValue(), llvm::EmitGEPOffset(), llvm::ExecutionEngine::emitGlobals(), llvm::AMDGPUAsmPrinter::EmitGlobalVariable(), llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernel(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), enableCallSafepoints(), llvm::LazyValueInfo::enableDT(), llvm::WinException::endFunclet(), eraseDeadBBsAndChildren(), llvm::Evaluator::EvaluateBlock(), EvaluateStaticConstructor(), llvm::VPBasicBlock::execute(), findBaseDefiningValueCached(), findBasePointer(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::CodeExtractor::findInputsOutputs(), FindPredecessorAutoreleaseWithSafePath(), findReturnsToZap(), llvm::AMDGPULibCalls::fold(), FoldCondBranchOnPHI(), foldICmpBitCast(), foldICmpShlOne(), foldICmpWithHighBitMask(), foldICmpWithMinMax(), foldLogicCastConstant(), foldOperationIntoSelectOperand(), foldSelectICmpLshrAshr(), llvm::InstCombiner::FoldShiftByConstant(), foldSignedTruncationCheck(), FoldTwoEntryPHINode(), forceRenaming(), forEachUser(), llvm::formLCSSAForInstructions(), FunctionNumber(), getAllocationDataForFunction(), getArrayElements(), getBinOpsForFactorization(), llvm::bfi_detail::getBlockName(), getBranchHint(), getBranchInsertPoint(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), getChainID(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::Intrinsic::getDeclaration(), llvm::DeadArgumentEliminationPass::RetOrArg::getDescription(), getDescription(), getEdgeValueLocal(), getEncodedUnnamedAddr(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), getFromRangeMetadata(), llvm::MachineBasicBlock::getFullName(), llvm::GlobalValue::getGlobalIdentifier(), GetGlobalTypeString(), llvm::DOTGraphTraits< const Function * >::getGraphName(), GetHeapSROAValue(), llvm::getInlineCost(), getInnermostLoopFor(), getInstrName(), getIntToFPVal(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::ExecutionEngine::getMangledName(), getMaxBackedgeTakenCount(), getMCSymbolForMBB(), getMinVisibility(), getName(), llvm::StackSafetyInfo::FunctionInfo::getName(), llvm::MachineFunction::getName(), llvm::Mangler::getNameWithPrefix(), getOpenCLAlignment(), llvm::GetOrCreateFunctionComdat(), llvm::AArch64InstrInfo::getOutliningType(), getParentPad(), llvm::getPGOFuncName(), llvm::orc::OrcMCJITReplacement::getPointerToFunction(), getRetComponentType(), getRsrcReg(), llvm::getSamplerName(), getScalarIntrinsicDeclaration(), getSignature(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), GetSortedValueDataFromCallTargets(), getStartOrEndSlot(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), getSuccState(), llvm::getSurfaceName(), llvm::getTextureName(), getTypePartition(), getVarName(), llvm::LoopVectorizationCostModel::getVectorCallCost(), GlobalWasGeneratedByCompiler(), HandleByValArgument(), hasName(), hoist(), llvm::hoistRegion(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::InlineFunction(), llvm::DivergenceAnalysis::inRegion(), insertLifetimeMarkersSurroundingCall(), llvm::InsertPreheaderForLoop(), insertUniqueBackedgeBlock(), instrumentMaskedLoadOrStore(), llvm::InternalizePass::internalizeModule(), isAtomic(), isCalleeLoad(), isCallPromotable(), isDirectCall(), isEmptyFunction(), llvm::isFreeCall(), isFuncOrderCorrect(), isGCSafepointPoll(), llvm::HexagonTargetObjectFile::isGlobalInSmallSection(), isInPartition(), isInSymtab(), IsInterestingCmp(), isIntrinsicInline(), isKnownLibFunction(), isKnownTypeIdMember(), isLoadConditional(), llvm::TargetTransformInfoImplBase::isLoweredToCall(), llvm::ARMTTIImpl::isLoweredToCall(), isObjectDereferencedInBlock(), isOnlyReachableViaThisEdge(), isPromotedResultSafe(), isReassociableOp(), isReInterleaveMask(), isReportingError(), isSafeAndProfitableToSinkLoad(), isSafeToPromoteArgument(), isSortedByValueNo(), isTrivialLoopExitBlock(), isUnconditionalBranch(), isWrapperOnlyCall(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), llvm::log2(), lookupFunction(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::IntrinsicLowering::LowerToByteSwap(), makeStatepointExplicitImpl(), mangleTLIName(), mapBinOpcode(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::MarkBlockExecutable(), MarkBlocksLiveIn(), matchDeMorgansLaws(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), maybePrintComdat(), mayLoopAccessLocation(), llvm::MergeBlockIntoPredecessor(), mergeConstants(), moveUp(), nearest_common_dominator(), needsRuntimeRegistrationOfSectionRange(), llvm::TargetRegisterInfo::needsStackRealignment(), NegateValue(), normalizePBQPSpillWeight(), llvm::orc::BlockFreqQuery::operator()(), llvm::orc::SequenceBBQuery::operator()(), llvm::DiagnosticPrinterRawOStream::operator<<(), false::operator<<(), llvm::rdf::operator<<(), llvm::operator<<(), optimizeDoubleFP(), OptimizeGlobalAddressOfMalloc(), llvm::OptLevelChanger::OptLevelChanger(), llvm::AArch64::parseCPUArch(), llvm::ARM::parseCPUArch(), llvm::peelLoop(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateWithInsertion(), populateWorklist(), llvm::LinkDiagnosticInfo::print(), llvm::LegacyDivergenceAnalysis::print(), llvm::Trace::print(), llvm::ValueEnumerator::print(), llvm::MemoryDepChecker::Dependence::print(), llvm::CallGraphNode::print(), llvm::GPUDivergenceAnalysis::print(), llvm::MemoryPhi::print(), llvm::MachineBasicBlock::print(), llvm::DiagnosticInfoUnsupported::print(), llvm::BranchProbabilityInfo::printEdgeProbability(), printIRBlockReference(), llvm::MIRFormatter::printIRValue(), PrintLLVMName(), PrintLoopInfo(), printNode(), printNodeDOT(), processAShr(), llvm::JumpThreadingPass::ProcessBlock(), processGlobal(), processInternalGlobal(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), processOverflowIntrinsic(), processSaturatingInst(), processSDiv(), processSExt(), processSRem(), processUDivOrURem(), processUGT_ADDCST_ADD(), llvm::promoteLoopAccessesToScalars(), PushArgMD(), llvm::GVNHoist::rank(), llvm::Function::recalculateIntrinsicID(), llvm::ImportedFunctionsInliningStatistics::recordInline(), recoverFramePointer(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::Intrinsic::remangleIntrinsicFunction(), llvm::RemoveRedundantDbgInstrs(), rename(), replace(), ReplaceCallWith(), replaceDominatedUsesWith(), reportMayClobberedLoad(), RetagMask(), rewriteComdat(), RewriteHeapSROALoadUser(), rewriteMaterializableInstructions(), rewritePHIs(), RewriteUsesOfClonedInstructions(), llvm::LoopAccessInfoPrinterPass::run(), llvm::IRCEPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::StackSafetyPrinterPass::run(), llvm::AAEvaluator::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::PostDominatorTreePrinterPass::run(), llvm::PrintFunctionPass::run(), llvm::InlinerPass::run(), llvm::BlockFrequencyPrinterPass::run(), llvm::PhiValuesPrinterPass::run(), llvm::AssumptionPrinterPass::run(), llvm::DominanceFrontierPrinterPass::run(), llvm::BranchProbabilityPrinterPass::run(), llvm::DominatorTreePrinterPass::run(), llvm::PredicateInfoPrinterPass::run(), llvm::DDGAnalysisPrinterPass::run(), llvm::DevirtSCCRepeatedPass< PassT >::run(), llvm::DependenceAnalysisPrinterPass::run(), llvm::MemorySSAPrinterPass::run(), llvm::RegionInfoPrinterPass::run(), llvm::Float2IntPass::runImpl(), llvm::SLPVectorizerPass::runImpl(), llvm::JumpThreadingPass::runImpl(), llvm::runIPSCCP(), llvm::LegacyDivergenceAnalysis::runOnFunction(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::FPPassManager::runOnFunction(), llvm::DetectRoundChange::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), runSCCP(), llvm::InnerLoopVectorizer::scalarizeInstruction(), scaleWeights(), selectELFSectionForGlobal(), llvm::FastISel::selectInstruction(), selectJumpTableArmEncoding(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), selectWasmSectionForGlobal(), setCoroInfo(), llvm::BranchProbabilityInfo::setEdgeProbability(), shouldApply(), llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection(), shouldRotateLoopExitingLatch(), ShrinkDemandedConstant(), simplifyAllocaArraySize(), SimplifyBSwap(), SimplifyCondBranchToCondBranch(), SimplifyNVVMIntrinsic(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), sinkInstruction(), sinkNotIntoXor(), llvm::sinkRegion(), llvm::FunctionPass::skipFunction(), llvm::LoopPass::skipLoop(), llvm::RegionPass::skipRegion(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), speculateSelectInstLoads(), llvm::SplitBlock(), llvm::SplitBlockPredecessors(), splitCallSite(), llvm::SplitCriticalEdge(), llvm::DISubprogram::splitFlags(), splitGlobal(), llvm::SplitLandingPadPredecessors(), SRAGlobal(), StripSymtab(), suffixed_name_or(), llvm::JumpThreadingPass::ThreadEdge(), llvm::JumpThreadingPass::ThreadGuard(), toRemarkLocation(), transformCallee(), truncateIVUse(), llvm::JumpThreadingPass::TryThreadEdge(), tryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), TurnSwitchRangeIntoICmp(), TypeSizeToSizeIndex(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), llvm::updateIndexWPDForExports(), updateOperand(), UpdatePHINodes(), updatePredecessorProfileMetadata(), llvm::CallInst::updateProfWeight(), llvm::UpgradeARCRuntime(), llvm::UpgradeGlobalVariable(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), llvm::AMDGPULibCalls::useNative(), Verify(), llvm::misexpect::verifyMisExpect(), llvm::verifyModule(), llvm::LoopVersioning::versionLoop(), viewRegionInfo(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitGetElementPtrInst(), visitIVCast(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), willNotOverflow(), writeCFGToDotFile(), llvm::WriteIndexToFile(), llvm::OptLevelChanger::~OptLevelChanger(), ~Value(), and llvm::ValueSymbolTable::~ValueSymbolTable().
getNumUses()
unsigned Value::getNumUses () const
This method computes the number of uses of this Value.
This is a linear time operation. Use hasOneUse, hasNUses, or hasNUsesOrMore to check for specific values.
Definition at line 161 of file Value.cpp.
References use_begin(), and use_end().
Referenced by llvm::createSeparateConstOffsetFromGEPPass(), llvm::GVNExpression::Expression::dump(), llvm::IRPosition::getAttrs(), hasOneUse(), hasUsesOutsideLoop(), llvm::log2(), llvm::ValueEnumerator::print(), and relocationViaAlloca().
getPointerAlignment()
MaybeAlign Value::getPointerAlignment (const DataLayout & DL) const
Returns an alignment of the pointer value.
Returns an alignment which is either specified explicitly, e.g. via align attribute of a function argument, or guaranteed by DataLayout.
Definition at line 675 of file Value.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::DataLayout::getABITypeAlignment(), llvm::DataLayout::getFunctionPtrAlign(), llvm::DataLayout::getFunctionPtrAlignType(), llvm::ConstantInt::getLimitedValue(), llvm::DataLayout::getPreferredAlignment(), llvm::DataLayout::getPrefTypeAlignment(), getType(), llvm::DataLayout::Independent, llvm::Type::isSized(), llvm_unreachable, llvm::max(), llvm::DataLayout::MultipleOfFunctionAlign, and llvm::None.
Referenced by computeKnownBits(), llvm::ConstantFoldBinaryInstruction(), despeculateCountZeros(), llvm::IRPosition::getAttrs(), getBaseAlign(), and stripInBoundsOffsets().
getPointerDereferenceableBytes()
uint64_t Value::getPointerDereferenceableBytes (const DataLayout & DL, bool & CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
If CanBeNull is set by this function the pointer can either be null or be dereferenceable up to the returned number of bytes.
Definition at line 609 of file Value.cpp.
References assert(), llvm::ConstantInt::getLimitedValue(), getType(), llvm::DataLayout::getTypeStoreSize(), llvm::Type::isSized(), and llvm::AttributeList::ReturnIndex.
Referenced by llvm::IRPosition::getAttrs(), getMinimalExtentFrom(), isDereferenceableAndAlignedPointer(), llvm::CaptureTracker::isDereferenceableOrNull(), stripInBoundsOffsets(), and llvm::InstCombiner::visitBitCast().
getRawSubclassOptionalData()
unsigned llvm::Value::getRawSubclassOptionalData () const inline
Return the raw optional flags value contained in this value.
This should only be used when testing two Values for equivalence.
Definition at line 491 of file Value.h.
References SubclassOptionalData.
Referenced by llvm::FunctionComparator::cmpOperations(), and llvm::ConstantExprKeyType::operator==().
getSubclassDataFromValue()
unsigned short llvm::Value::getSubclassDataFromValue () const inline protected
Definition at line 714 of file Value.h.
Referenced by llvm::Function::dropAllReferences(), llvm::BasicBlock::getLandingPadInst(), llvm::ConstantExpr::getOpcode(), llvm::BasicBlock::hasAddressTaken(), llvm::Function::setPrologueData(), llvm::Function::stealArgumentListFrom(), and llvm::Function::~Function().
getType()
Type* llvm::Value::getType () const inline
All values are typed, get the type of this value.
Definition at line 246 of file Value.h.
References getContext().
Referenced by llvm::GetElementPtrInst::accumulateConstantOffset(), llvm::AliasSetTracker::add(), addArgumentReturnedAttrs(), addAssumeNonNull(), llvm::SSAUpdater::AddAvailableValue(), AddCalls(), llvm::AddOne(), llvm::RecurrenceDescriptor::AddReductionVar(), addStackMapLiveVars(), llvm::IVUsers::AddUsersImpl(), addVariantDeclaration(), llvm::detail::PtrUseVisitorBase::adjustOffsetForGEP(), llvm::AMDGPUAAResult::alias(), aliasSameBasePointerGEPs(), alwaysAvailable(), llvm::VNCoercion::analyzeLoadFromClobberingLoad(), llvm::VNCoercion::analyzeLoadFromClobberingStore(), annotateAnyAllocSite(), annotateDereferenceableBytes(), annotateNonNullAndDereferenceable(), annotateNonNullBasedOnAccess(), appendTypeSuffix(), ApplyX86MaskOn1BitsVec(), areExtractExts(), areExtractShuffleVectors(), llvm::SelectInst::areInvalidOperands(), areInverseVectorBitmasks(), AreSequentialAccesses(), areStridedAccessesIndependent(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), atomicSizeSupported(), BatchCommitValueTo(), llvm::BinaryOperator::BinaryOperator(), BitCastConstantVector(), buildClonedLoopBlocks(), BuildConstantFromSCEV(), buildFrameType(), buildGEP(), buildMultiplyTree(), buildNew(), llvm::InnerLoopVectorizer::buildScalarSteps(), BuildSubAggregate(), calcArraySize(), llvm::DomTreeUpdater::callbackDeleteBB(), canAlwaysEvaluateInType(), llvm::VNCoercion::canCoerceMustAliasedValueToLoad(), llvm::canConstantFoldCallTo(), CanDoGlobalSRA(), canEvaluateSExtd(), canEvaluateShiftedShift(), canEvaluateShuffled(), canEvaluateTruncated(), canEvaluateZExtd(), llvm::FastISel::canFoldAddIntoGEP(), canFoldIVIncExpr(), CanGenerateTest(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canNarrowShiftAmt(), canonicalizeBitCastExtElt(), llvm::InstCombiner::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeICmpBool(), canonicalizeLowbitMask(), canonicalizeSaturatedAdd(), llvm::canReplaceOperandWithVariable(), CanShareConstantPoolEntry(), canSinkInstructions(), canTrapImpl(), canVectorizeInst(), llvm::Evaluator::castCallResultIfNeeded(), llvm::CastInst::castIsValid(), castRequiresQueuePtr(), llvm::castToCStr(), CC_MipsO32_FP64(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), cheapToScalarize(), checkFunctionMemoryAccess(), llvm::FPMathOperator::classof(), llvm::ExtractValueInst::classof(), llvm::TypeFinder::clear(), clearAssumptionsOfUsers(), llvm::CloneAndPruneIntoFromInst(), cloneConstantExprWithNewAddressSpace(), llvm::AllocaInst::cloneImpl(), llvm::LoadInst::cloneImpl(), llvm::VAArgInst::cloneImpl(), llvm::TruncInst::cloneImpl(), llvm::ZExtInst::cloneImpl(), llvm::SExtInst::cloneImpl(), llvm::FPTruncInst::cloneImpl(), llvm::FPExtInst::cloneImpl(), llvm::UIToFPInst::cloneImpl(), llvm::SIToFPInst::cloneImpl(), llvm::FPToUIInst::cloneImpl(), llvm::FPToSIInst::cloneImpl(), llvm::IntToPtrInst::cloneImpl(), llvm::PtrToIntInst::cloneImpl(), llvm::BitCastInst::cloneImpl(), llvm::AddrSpaceCastInst::cloneImpl(), llvm::JumpThreadingPass::CloneInstructions(), cloneInstructionWithNewAddressSpace(), CloneLoop(), CloneLoopBlocks(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::FunctionComparator::cmpConstants(), llvm::FunctionComparator::cmpOperations(), collectBitParts(), collectInsertionElements(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), collectShuffleElements(), collectSingleShuffleElements(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::InstCombiner::combineLoadToNewType(), combineLoadToOperationType(), combineStoreToNewValue(), combineStoreToValueType(), llvm::InstCombiner::commonCastTransforms(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), llvm::ShuffleVectorInst::commute(), CompareValueComplexity(), llvm::ObjectSizeOffsetVisitor::compute(), llvm::ObjectSizeOffsetEvaluator::compute(), computeBytesPoppedByCalleeForSRet(), llvm::computeConstantRange(), computeKillSet(), computeKnownBits(), computeKnownBitsFromOperator(), computeLiveOutSeed(), llvm::computeMinimumValueSizes(), llvm::ComputeMultiple(), ComputeNumSignBitsImpl(), llvm::computeOverflowForSignedMul(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computePointerICmp(), ComputePostOrders(), computeRecurrenceType(), llvm::IndexedReference::computeRefCost(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), concatenateTwoVectors(), llvm::concatenateVectors(), concatSubVector(), ConnectProlog(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), constantFoldUser(), ConstructSSAForLoadSet(), contains(), llvm::ConvertDebugDeclareToDebugValue(), ConvertDoubleToBytes(), ConvertShiftToMul(), ConvertToSInt(), convertValue(), llvm::copyMetadataForLoad(), llvm::copyNonnullMetadata(), llvm::copyRangeMetadata(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::UnaryOperator::Create(), llvm::BinaryOperator::Create(), llvm::ConstantExprKeyType::create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), CreateAdd(), llvm::IRBuilder< TargetFolder >::CreateAlignedLoad(), llvm::IRBuilder< TargetFolder >::CreateAlignmentAssumption(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::IRBuilder< TargetFolder >::CreateAnd(), createAndInstr(), llvm::IRBuilder< TargetFolder >::CreateAShr(), llvm::IRBuilderBase::CreateBinaryIntrinsic(), llvm::CastInst::CreateBitOrPointerCast(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), llvm::IRBuilder< TargetFolder >::CreateBitOrPointerCast(), llvm::IRBuilder< TargetFolder >::CreateCall(), createCallInst(), llvm::TargetFolder::CreateCast(), createCast(), llvm::IRBuilder< TargetFolder >::CreateCast(), createCmpXchgInstFun(), llvm::IRBuilder< TargetFolder >::CreateConstrainedFPBinOp(), llvm::IRBuilder< TargetFolder >::CreateConstrainedFPCast(), llvm::IRBuilder< TargetFolder >::CreateConstrainedFPCmp(), llvm::createDeadArgHackingPass(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilder< TargetFolder >::CreateExtractInteger(), llvm::IRBuilderBase::CreateFAddReduce(), createFFSIntrinsic(), llvm::IRBuilderBase::CreateFMulReduce(), llvm::BinaryOperator::CreateFNeg(), llvm::BinaryOperator::CreateFNegFMF(), llvm::TargetFolder::CreateFPCast(), llvm::CastInst::CreateFPCast(), llvm::IRBuilder< TargetFolder >::CreateFPCast(), createFree(), llvm::CallInst::CreateFree(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), createGlobalFwdRef(), llvm::IRBuilderBase::CreateGlobalString(), llvm::TargetFolder::CreateIntCast(), llvm::IRBuilder< TargetFolder >::CreateIntCast(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilder< TargetFolder >::CreateInvoke(), llvm::IRBuilder< TargetFolder >::CreateIsNotNull(), llvm::IRBuilder< TargetFolder >::CreateIsNull(), llvm::IRBuilder< TargetFolder >::CreateLaunderInvariantGroup(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilder< TargetFolder >::CreateLoad(), llvm::IRBuilder< TargetFolder >::CreateLShr(), createMalloc(), createMaskedBitTest(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateMaskedStore(), createMaskInstrs(), llvm::IRBuilderBase::CreateMemCpy(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), llvm::createMemDerefPrinter(), llvm::IRBuilderBase::CreateMemMove(), createMemMoveLoop(), llvm::IRBuilderBase::CreateMemSet(), createMemSetLoop(), CreateMul(), CreateNeg(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNot(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUWNeg(), llvm::createObjCARCOptPass(), llvm::IRBuilder< TargetFolder >::CreateOr(), createOrdering(), llvm::InstCombiner::CreateOverflowTuple(), llvm::createPGOFuncNameVar(), llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::IRBuilder< TargetFolder >::CreatePointerBitCastOrAddrSpaceCast(), llvm::TargetFolder::CreatePointerCast(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilder< TargetFolder >::CreatePointerCast(), createPopcntIntrinsic(), createPowWithIntegerExponent(), llvm::IRBuilder< TargetFolder >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< TargetFolder >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< TargetFolder >::CreatePreserveUnionAccessIndex(), llvm::createPrivateGlobalForString(), createPrivateNonConstGlobalForString(), llvm::createProfileFileNameVar(), llvm::IRBuilder< TargetFolder >::CreatePtrDiff(), createRdxShuffleMask(), llvm::FunctionLoweringInfo::CreateRegs(), createReplacementInstr(), llvm::VPRecipeBuilder::createReplicateRegion(), createRetPHINode(), llvm::createScalarizerPass(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::TargetFolder::CreateSExtOrBitCast(), llvm::CastInst::CreateSExtOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateSExtOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateSExtOrTrunc(), llvm::createShadowStackGCLoweringPass(), llvm::IRBuilder< TargetFolder >::CreateShl(), llvm::createSimpleTargetReduction(), llvm::IRBuilder< TargetFolder >::CreateStripInvariantGroup(), llvm::TargetFolder::CreateTruncOrBitCast(), llvm::CastInst::CreateTruncOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateTruncOrBitCast(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::IRBuilder< TargetFolder >::CreateVectorSplat(), createWrapper(), llvm::IRBuilder< TargetFolder >::CreateXor(), llvm::TargetFolder::CreateZExtOrBitCast(), llvm::CastInst::CreateZExtOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateZExtOrBitCast(), llvm::IRBuilder< TargetFolder >::CreateZExtOrTrunc(), llvm::DecodePSHUFBMask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::decomposeBitTestICmp(), decomposeBitTestICmp(), decomposeSimpleLinearExpr(), deleteDeadInstruction(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), despeculateCountZeros(), llvm::DetatchDeadBlocks(), detectShiftUntilZeroIdiom(), determinePointerReadAttrs(), DivRemPairWorklistEntry::DivRemPairWorklistEntry(), doPromotion(), dropRedundantMaskingOfLeftShiftInput(), llvm::GVNExpression::Expression::dump(), eliminateRecursiveTailCall(), eliminateSwiftErrorArgument(), llvm::emitBinaryFloatFnCall(), emitBinaryFloatFnCallHelper(), emitDebugValueComment(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), llvm::EmitGEPOffset(), llvm::AsmPrinter::EmitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantStruct(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::emitMemCCpy(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), emitSetSwiftErrorValue(), emitSignedInt64(), llvm::emitSNPrintf(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::emitStpNCpy(), llvm::emitStrLCat(), llvm::emitStrLCpy(), llvm::emitStrNCat(), llvm::emitStrNCpy(), llvm::RISCVTargetLowering::emitTrailingFence(), llvm::PPCTargetLowering::emitTrailingFence(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::emitUnaryFloatFnCall(), emitUnaryFloatFnCallHelper(), llvm::emitVSNPrintf(), llvm::emitVSPrintf(), EmitX86ScalarSelect(), EmitX86Select(), llvm::ARMAsmPrinter::EmitXXStructor(), ensurePromotedGV(), ensureValueAvailableInSuccessor(), EqualityPropUnSafe(), llvm::slpvectorizer::BoUpSLP::eraseInstructions(), evaluateBitcastFromPtr(), llvm::Evaluator::EvaluateBlock(), EvaluateExpression(), evaluateFCmpRelation(), evaluateGEPOffsetExpression(), evaluateICmpRelation(), evaluateInDifferentElementOrder(), EvaluateStoreInto(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::VPlan::execute(), llvm::expandAtomicRMWToCmpXchg(), expandBounds(), llvm::SCEVExpander::expandCodeFor(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), ExtractConstantBytes(), llvm::extractConstantMask(), ExtractImmediate(), extractInteger(), extractValues(), extractVector(), llvm::FenceInst::FenceInst(), FindAllMemoryUses(), llvm::FindAvailableLoadedValue(), findBaseDefiningValue(), findBaseDefiningValueOfVector(), findBasePointer(), findDemandedEltsByAllUsers(), findDemandedEltsBySingleUser(), findFuncPointers(), llvm::CodeExtractor::findInputsOutputs(), llvm::FindInsertedValue(), findInsertPointAfter(), findLoadAlignment(), findMatchingInlineAsmOperand(), findReturnsToZap(), llvm::findScalarElement(), findStoreAlignment(), findUnwindDestinations(), FitWeights(), FixedPointIntrinsicToOpcode(), llvm::InnerLoopVectorizer::fixReduction(), fixupFPReturnAndCall(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::AMDGPULibCalls::fold(), foldAndOrOfEqualityCmpsWithConstants(), foldAnyOrAllBitsSet(), FoldBitCast(), foldBitCastBitwiseLogic(), foldBitcastExtElt(), foldConstantCastPair(), foldConstantInsEltIntoShuffle(), foldCttzCtlz(), foldFDivConstantDivisor(), foldGuardedRotateToFunnelShift(), foldICmpBitCast(), foldICmpShlOne(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), foldICmpWithMinMax(), foldICmpWithTruncSignExtendedVal(), foldICmpWithZextOrSext(), foldIdentityPaddedShuffles(), foldIdentityShuffles(), foldInsEltIntoSplat(), foldIsPowerOf2(), llvm::InstCombiner::FoldItoFPtoI(), foldLogicCastConstant(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldNoWrapAdd(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), foldSelectBinOpIdentity(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldSelectICmpLshrAshr(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedLogic(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), FoldTwoEntryPHINode(), foldUDivPow2Cst(), foldUDivShl(), foldUnsignedUnderflowCheck(), llvm::InstCombiner::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVectorCmp(), foldVecTruncToExtElt(), foldXorToXor(), forEachUser(), llvm::formLCSSAForInstructions(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), FunctionNumber(), generatePoisonChecks(), generatePoisonChecksForBinOp(), GenerateSignBits(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), genericValueTraversal(), genLoopLimit(), llvm::MemoryLocation::get(), llvm::ConstantFP::get(), llvm::ConstantAggregateZero::get(), llvm::ConstantArray::get(), llvm::ConstantVector::get(), llvm::ConstantPointerNull::get(), llvm::ConstantExpr::get(), llvm::UndefValue::get(), getAccessType(), getAddressForMemoryInput(), llvm::SITargetLowering::getAddrModeArguments(), llvm::ConstantExpr::getAddrSpaceCast(), getAdjustedPtr(), llvm::Constant::getAggregateElement(), getAISize(), getAlternateBinop(), llvm::IRTranslator::getAnalysisUsage(), GetAnyNonZeroConstInt(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), getArrayElements(), getAsConstantIndexedAddress(), llvm::ConstantExpr::getAsInstruction(), getAtomicOpAlign(), getAtomicOpSize(), llvm::IRPosition::getAttrs(), getBaseAlign(), getBaseType(), llvm::ConstantExpr::getBinOpAbsorber(), getBinOpsForFactorization(), llvm::ConstantExpr::getBitCast(), getBoundsCheckCond(), llvm::getCallsiteCost(), llvm::CastInst::getCastOpcode(), getChainID(), getCodeAddrSpace(), llvm::ConstantExpr::getCompare(), getCompareCC(), getComparePred(), GetCompareTy(), getConstantFromPool(), GetConstantInt(), llvm::VNCoercion::getConstantLoadValueForLoad(), llvm::SelectionDAG::getConstantPool(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), llvm::ExecutionEngine::getConstantValue(), llvm::BasicBlock::getContext(), llvm::Function::getContext(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::Intrinsic::getDeclaration(), llvm::DemandedBits::getDemandedBits(), llvm::Argument::getDereferenceableBytes(), llvm::Argument::getDereferenceableOrNullBytes(), llvm::BitCastOperator::getDestTy(), getEdgeValueLocal(), llvm::ConstantDataSequential::getElementType(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getFCmp(), getFCmpValue(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::ConstantExpr::getFNeg(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), getFrameType(), getFromRangeMetadata(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::GVNExpression::VariableExpression::getHashValue(), llvm::GVNExpression::ConstantExpression::getHashValue(), GetHeapSROAValue(), llvm::ConstantExpr::getICmp(), getIdentityValue(), getImplicitScaleFactor(), llvm::DataLayout::getIndexedOffsetInType(), getInductionVariable(), getInitializer(), llvm::getInlineCost(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionLatency(), llvm::ConstantExpr::getIntegerCast(), getIntrinsicForMaskedAtomicRMWBinOp(), getIntToFPVal(), llvm::ConstantExpr::getIntToPtr(), llvm::SCEVExpander::getIVIncOperand(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::InvokeInst::getLandingPadInst(), getLaneCopyOpcode(), llvm::MemoryDependenceResults::getLoadLoadClobberFullWidthSize(), llvm::VNCoercion::getLoadValueForLoad(), GetLoopInvariantInsertPosition(), llvm::getMallocType(), getMaskedTypeForICmpPair(), getMaxBackedgeTakenCount(), getMaxPointerSize(), getMemCmpLoad(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getMemSetPatternValue(), getMetadataTypeOrder(), getMinimumFPType(), llvm::GlobalsAAResult::getModRefBehavior(), llvm::AAResults::getModRefInfo(), getMulHu(), getName(), getNaturalGEPWithOffset(), getNaturalGEPWithType(), llvm::ConstantExpr::getNeg(), getNegatibleInsts(), getNewICmpValue(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), getNoopInput(), llvm::ConstantExpr::getNot(), getNumBytes(), llvm::ConstantDataSequential::getNumElements(), getOffsetFromIndices(), getOpenCLAlignment(), getOptimizationFlags(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::getOrderedReduction(), llvm::getOrEnforceKnownAlignment(), getOrInsertValueProfilingCall(), llvm::Argument::getParamAlign(), llvm::Argument::getParamAlignment(), llvm::Argument::getParamByValType(), getParameterABIAttributes(), getParentPad(), llvm::AtomicCmpXchgInst::getPointerAddressSpace(), llvm::AtomicRMWInst::getPointerAddressSpace(), llvm::PtrToIntInst::getPointerAddressSpace(), getPointerAlignment(), llvm::getPointerAtOffset(), llvm::GetPointerBaseWithConstantOffset(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), getPointerDereferenceableBytes(), GetPointerOperand(), getPointerOperands(), llvm::LoadInst::getPointerOperandType(), llvm::StoreInst::getPointerOperandType(), llvm::GEPOperator::getPointerOperandType(), llvm::PtrToIntOperator::getPointerOperandType(), llvm::GetElementPtrInst::getPointerOperandType(), llvm::LazyValueInfo::getPredicateAt(), llvm::getPtrStride(), llvm::ConstantExpr::getPtrToInt(), getRangeForAffineARHelper(), getReducedType(), getReductionIntrinsic(), llvm::FastISel::getRegForGEPIndex(), llvm::FastISel::getRegForValue(), getRelevantOperands(), getRetComponentType(), GetRMWLibcall(), llvm::getSafeVectorConstantForBinop(), getScalarIntrinsicDeclaration(), llvm::ScalarEvolution::getSCEV(), llvm::ConstantExpr::getSelect(), getSelectFoldableConstant(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSExtOrBitCast(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::getShuffleReduction(), llvm::ConstantExpr::getShuffleVector(), getSignature(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::ConstantExpr::getSIToFP(), llvm::MipsCCState::getSpecialCallingConvForCallee(), llvm::ConstantVector::getSplat(), llvm::ConstantDataVector::getSplat(), llvm::Constant::getSplatValue(), llvm::getSplatValue(), getSqrtCall(), llvm::AddrSpaceCastInst::getSrcAddressSpace(), llvm::BitCastOperator::getSrcTy(), llvm::SelectionDAG::getSrcValue(), llvm::InnerLoopVectorizer::getStepVector(), llvm::getStrideFromPointer(), llvm::GetStringLength(), getSubprogram(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), getTargetConstantBitsFromNode(), llvm::RISCVTargetLowering::getTgtMemIntrinsic(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), llvm::SITargetLowering::getTgtMemIntrinsic(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::X86TargetLowering::getTgtMemIntrinsic(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), getTrueOrFalseValue(), llvm::ConstantExpr::getTrunc(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::InlineAsm::getType(), DivRemPairWorklistEntry::getType(), llvm::AllocaInst::getType(), llvm::ConstantInt::getType(), llvm::GlobalValue::getType(), llvm::ValueAsMetadata::getType(), llvm::ConstantArray::getType(), llvm::ConstantStruct::getType(), llvm::ConstantVector::getType(), llvm::ConstantPointerNull::getType(), llvm::ConstantDataSequential::getType(), llvm::ConstantDataArray::getType(), llvm::ConstantDataVector::getType(), llvm::InsertElementInst::getType(), llvm::ShuffleVectorInst::getType(), llvm::ConstantStruct::getTypeForElements(), getTypePartition(), llvm::ConstantExpr::getUIToFP(), getUnderlyingArgRegs(), llvm::GetUnderlyingObject(), getUnderlyingObjectFromInt(), llvm::getUnderlyingObjectsForCodeGen(), getUniformBase(), llvm::getUniqueCastUse(), llvm::PPCTTIImpl::getUserCost(), llvm::X86TTIImpl::getUserCost(), llvm::GCNTTIImpl::getUserCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), llvm::SelectionDAGBuilder::getValue(), getValueFromICmpCondition(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), getVectorType(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), getX86MaskVec(), llvm::ConstantExpr::getZExt(), llvm::ConstantExpr::getZExtOrBitCast(), llvm::GlobalVariable::GlobalVariable(), GlobalWasGeneratedByCompiler(), HandleByValArgument(), HandleByValArgumentInit(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::ValueAsMetadata::handleDeletion(), handleMemIntrinsicPtrUse(), llvm::Constant::handleOperandChange(), llvm::ValueAsMetadata::handleRAUW(), llvm::Argument::hasByValAttr(), llvm::Argument::hasByValOrInAllocaAttr(), llvm::PHINode::hasConstantOrUndefValue(), llvm::Argument::hasInAllocaAttr(), llvm::Argument::hasNestAttr(), llvm::Argument::hasNoAliasAttr(), llvm::Argument::hasNoCaptureAttr(), llvm::Argument::hasNonNullAttr(), hasOnlyOneNonZeroIndex(), hasPositiveOperands(), hasProfileData(), hasSameArgumentList(), hasSameExtUse(), hasStoreUsersOnly(), llvm::Argument::hasStructRetAttr(), hasUndefContents(), hasZeroSignBit(), llvm::haveNoCommonBitsSet(), llvm::SCEVExpander::hoistIVInc(), HoistThenElseCodeToIf(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::CompositeType::indexValid(), AAValueConstantRangeFloating::initialize(), INITIALIZE_PASS(), llvm::MIRParserImpl::initializeConstantPool(), llvm::ExecutionEngine::InitializeMemory(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::InlineFunction(), llvm::RuntimePointerChecking::insert(), insertInteger(), insertLifetimeMarkersSurroundingCall(), InsertRootInitializers(), insertSinCosCall(), insertUniqueBackedgeBlock(), insertValues(), insertVector(), instrumentMaskedLoadOrStore(), llvm::MemoryDependenceResults::invalidateCachedPointerInfo(), inversePermutation(), isAtomic(), llvm::isBytewiseValue(), isCallPromotable(), llvm::LandingPadInst::isCatch(), isCompatibleIVType(), isCompatibleReplacement(), llvm::ShuffleVectorInst::isConcat(), llvm::isConsecutiveAccess(), isConstantFalse(), llvm::RISCVELFTargetObjectFile::isConstantInSmallSection(), llvm::LanaiTargetObjectFile::isConstantInSmallSection(), llvm::MipsTargetObjectFile::IsConstantInSmallSection(), isConstantIntVector(), isContiguous(), llvm::isDereferenceableAndAlignedInLoop(), llvm::isDereferenceableAndAlignedPointer(), isDereferenceableAndAlignedPointer(), isDivZero(), llvm::Constant::isElementWiseEqual(), isEqualImpl(), llvm::TargetLoweringBase::isExtFree(), llvm::TargetLoweringBase::isExtLoad(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::LandingPadInst::isFilter(), llvm::SystemZTTIImpl::isFoldableLoad(), llvm::InductionDescriptor::isFPInductionPHI(), isFuncOrArgAttr(), isGEPFoldable(), isGEPKnownNonNull(), isHighCostExpansion(), llvm::Instruction::isIdenticalToWhenDefined(), llvm::ShuffleVectorInst::isIdentityMask(), isImageOrSamplerVal(), llvm::isImpliedCondition(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), IsIncrementNUW(), isIndirectBrTarget(), llvm::InductionDescriptor::isInductionPHI(), llvm::CastInst::isIntegerCast(), isIntegerLoopHeaderPHI(), isInterestingPointer(), isIntExtFree(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverNaN(), isKnownNonEqual(), isKnownNonNullFromDominatingCondition(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), isKnownTypeIdMember(), llvm::isLegalToPromote(), llvm::slpvectorizer::BoUpSLP::isLoadCombineReductionCandidate(), isLoadConditional(), isLoadInvariantInLoop(), isLoopCounter(), llvm::CastInst::isLosslessCast(), IsMasked(), llvm::isMathLibCallNoop(), isMinMaxWithLoads(), isMulPowOf2(), IsNonLocalValue(), llvm::CastInst::isNoopCast(), isNoWrap(), IsNullTerminatedString(), isObjectDereferencedInBlock(), isObjectSize(), isOnlyReachableViaThisEdge(), isPointerBitcastEqualTo(), isPointerOperand(), isPointerValueDeadOnEntryToFunction(), llvm::objcarc::IsPotentialRetainableObjPtr(), isProfitableChain(), llvm::AArch64TargetLowering::isProfitableToHoist(), isPromotedInstructionLegal(), isPromotedResultSafe(), isReInterleaveMask(), isRepeatedByteSequence(), isReportingError(), llvm::ShuffleVectorInst::isReverseMask(), isSafeAndProfitableToSinkLoad(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), isSafeToEliminateVarargsCast(), llvm::isSafeToLoadUnconditionally(), llvm::isSafeToSpeculativelyExecute(), llvm::Instruction::isSameOperationAs(), isSelect01(), llvm::ShuffleVectorInst::isSelectMask(), isSExtLoad(), isShuffleEquivalentToSelect(), isShuffleExtractingFromLHS(), isSimpleEnoughPointerToCommit(), isSimpleEnoughValueToCommitHelper(), isSimpleIVUser(), llvm::ShuffleVectorInst::isSingleSourceMask(), llvm::isSplatValue(), isStrideMul(), llvm::ConstantDataSequential::isString(), isSupportedType(), isSwiftError(), llvm::ShuffleVectorInst::isTransposeMask(), isTruePredicate(), isUndefShift(), llvm::LoopVectorizationLegality::isUniform(), llvm::LoopAccessInfo::isUniform(), llvm::DemandedBits::isUseDead(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), isVectorReductionOp(), isZero(), llvm::ShuffleVectorInst::isZeroEltSplatMask(), llvm::AArch64TargetLowering::isZExtFree(), likeBitCastFromVector(), LinearizeExprTree(), LLVMBuildCall(), LLVMBuildGEP(), LLVMBuildInBoundsGEP(), LLVMBuildInvoke(), LLVMBuildLoad(), LLVMBuildStructGEP(), LLVMConstGEP(), LLVMConstInBoundsGEP(), LLVMConstRealGetDouble(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), llvm::LoadInst::LoadInst(), llvm::log2(), lookThroughCast(), llvm::WebAssemblyMCInstLower::lower(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), LowerBSWAP(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundle(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::FastISel::lowerCallTo(), llvm::AsmPrinter::lowerConstant(), LowerCTLZ(), LowerCTPOP(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerIsConstantIntrinsic(), LowerNegateToMultiply(), llvm::lowerObjectSizeCall(), llvm::X86CallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::MipsCallLowering::lowerReturn(), LowerRotate(), llvm::SelectionDAGBuilder::LowerStatepoint(), lowerStatepointMetaArgs(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::MachineMemOperand::MachineMemOperand(), llvm::MachinePointerInfo::MachinePointerInfo(), makeBitReverse(), makeStatepointExplicitImpl(), mapBinOpcode(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::MarkBlockExecutable(), MarkBlocksLiveIn(), llvm::matchDecomposedSelectPattern(), matchesOr(), matchPairwiseReductionAtLevel(), matchRotate(), matchUAddWithOverflowConstantEdgeCases(), matchVectorSplittingReduction(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue(), maybePrintCallAddrSpace(), maybePrintComdat(), maybeSetDSOLocal(), mayLoopAccessLocation(), mayUsePostIncMode(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), MergeAliasResults(), llvm::MergeBasicBlockIntoOnlyPred(), mergeConditionalStoreToAddress(), mergeEmptyReturnBlocks(), MightBeFoldableInst(), llvm::TargetTransformInfoImplBase::minRequiredElementSize(), moveUp(), MulWillOverflow(), llvm::InstDeleterIRStrategy::mutate(), narrowUDivURem(), needsFPFromSig(), NegateValue(), llvm::RandomIRBuilder::newSink(), llvm::RandomIRBuilder::newSource(), okayForPHIOfOps(), operandWithNewAddressSpaceOrCreateUndef(), operator new(), operator<<(), OptimizeAwayTrappingUsesOfValue(), optimizeBinaryDoubleFP(), optimizeDoubleFP(), OptimizeEmptyGlobalCXXDtors(), OptimizeExtractBits(), OptimizeGlobalAddressOfMalloc(), optimizeIntegerToVectorInsertions(), optimizeMemCmpConstantSize(), OptimizeNoopCopyExpression(), optimizeOnceStoredGlobal(), optimizeSQRT(), optimizeVectorResizeWithIntegerBitCasts(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), llvm::TargetLowering::ParseConstraints(), parseIRValue(), parsePredicateConstraint(), patchAndReplaceAllUsesWith(), performAtomicOp(), PerformHeapAllocSRoA(), performMaskedAtomicOp(), llvm::PHITransAddr::PHITranslateWithInsertion(), PhiTypeSorterFunc(), PickMostRelevantLoop(), llvm::PointerMayBeCaptured(), llvm::AMDGPUAAResult::pointsToConstantMemory(), llvm::CallBase::populateBundleOperandInfos(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), llvm::possiblyDemandedEltsInMask(), llvm::ARMConstantPoolValue::print(), llvm::ScalarEvolution::print(), printAsOperandImpl(), processAnd(), processAShr(), processBinOp(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCallSite(), processInternalGlobal(), processOverflowIntrinsic(), processPHI(), processSDiv(), processSelect(), processSExt(), processSRem(), processUDivOrURem(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::promoteCall(), promotedOpIsNUW(), llvm::promoteLoopAccessesToScalars(), promoteSingleBlockAlloca(), PropagateConstantsIntoArguments(), propagateMetadata(), propagateNaN(), llvm::InstCombiner::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::recognizeBSwapOrBitReverseIdiom(), ReduceSwitchRange(), llvm::DemandedBitsWrapperPass::releaseMemory(), llvm::removeAllNonTerminatorAndEHPadInstructions(), RemoveDeadConstant(), removeGlobalCtors(), llvm::CatchSwitchInst::removeHandler(), RemoveInstInputs(), llvm::MemoryDependenceResults::removeInstruction(), removeLifetimeIntrinsicUsers(), llvm::removeUnreachableBlocks(), llvm::replaceAllDbgUsesWith(), replaceAllUsesOfWithIn(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::replaceDbgUsesWithUndef(), replaceDominatedUsesWith(), llvm::InstCombiner::replacedSelectWithOperand(), ReplaceFPIntrinsicWithCall(), llvm::InstCombiner::replaceInstUsesWith(), llvm::replaceNonLocalUsesWith(), replaceSwiftErrorOps(), llvm::replaceSymbolicStrideSCEV(), replaceUnaryCall(), llvm::Constant::replaceUndefsWith(), ReplaceUsesOfWith(), replaceUsesOutsideBlock(), replaceUsesWithIf(), replaceWithConstant(), reportLoadElim(), reportMayClobberedLoad(), llvm::Record::resolveReferences(), RetagMask(), llvm::returnTypeIsEligibleForTailCall(), reuseTableCompare(), llvm::InnerLoopVectorizer::reverseVector(), RewriteHeapSROALoadUser(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), rewritePHIs(), rewriteSingleStoreAlloca(), RewriteUsesOfClonedInstructions(), llvm::LoopDataPrefetchPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::LoadAndStorePromoter::run(), llvm::InstCombiner::run(), llvm::SLPVectorizerPass::runImpl(), llvm::runIPSCCP(), runPartiallyInlineLibCalls(), runSCCP(), llvm::salvageDebugInfoImpl(), scalarConstantToHexString(), scalarizeBinOpOfSplats(), llvm::InnerLoopVectorizer::scalarizeInstruction(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), llvm::FastISel::selectBinaryOp(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectCast(), llvm::FastISel::selectExtractValue(), llvm::FastISel::selectFNeg(), llvm::FastISel::selectOperator(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), llvm::GlobalAlias::setAliasee(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::setCalledFunction(), llvm::CallBase::setCalledFunction(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::MemIntrinsicBase< AnyMemIntrinsic >::setDest(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), llvm::PHINode::setIncomingValue(), llvm::GlobalVariable::setInitializer(), llvm::MemIntrinsicBase< AnyMemIntrinsic >::setLength(), setLimitsForSelectPattern(), AAValueConstantRangeImpl::setRangeMetadataIfisBetterRange(), llvm::MemTransferBase< AnyMemIntrinsic >::setSource(), llvm::MemSetBase< AnyMemIntrinsic >::setValue(), shorter_filter(), llvm::AArch64TTIImpl::shouldConsiderAddressTypePromotion(), shouldConvertImpl(), llvm::HexagonTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::HexagonTargetLowering::shouldExpandAtomicLoadInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicLoadInIR(), llvm::ARMTargetLowering::shouldExpandAtomicLoadInIR(), llvm::SparcTargetLowering::shouldExpandAtomicRMWInIR(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicRMWInIR(), llvm::ARMTargetLowering::shouldExpandAtomicRMWInIR(), llvm::HexagonTargetLowering::shouldExpandAtomicStoreInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicStoreInIR(), llvm::ARMTargetLowering::shouldExpandAtomicStoreInIR(), shouldFixMainFunction(), shouldInstrumentReadWriteFromAddress(), shouldKeepFDivF32(), shouldMergeGEPs(), llvm::ARMTargetLowering::shouldSinkOperands(), llvm::AArch64TargetLowering::shouldSinkOperands(), ShrinkDemandedConstant(), shrinkFPConstant(), shrinkInsertElt(), shrinkSplatShuffle(), SimplifyAddInst(), simplifyAllocaArraySize(), SimplifyAndInst(), simplifyAndOfICmpsWithAdd(), simplifyAndOfICmpsWithSameOperands(), simplifyAndOrOfCmps(), simplifyAndOrOfFCmps(), simplifyAndOrOfICmpsWithConstants(), SimplifyAShrInst(), simplifyAssocCastAssoc(), simplifyBinaryIntrinsic(), SimplifyBSwap(), llvm::SimplifyCall(), SimplifyCastInst(), simplifyDiv(), simplifyDivRem(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SimplifyExtractElementInst(), SimplifyFAddInst(), SimplifyFDivInst(), SimplifyFMAFMul(), SimplifyFRemInst(), SimplifyFSubInst(), SimplifyGEPInst(), SimplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithBinOp(), llvm::SimplifyInsertElementInst(), SimplifyInsertValueInst(), llvm::SimplifyInstruction(), simplifyInvariantGroupIntrinsic(), SimplifyLShrInst(), SimplifyMulInst(), simplifyNeonTbl1(), simplifyNeonVld1(), SimplifyNVVMIntrinsic(), SimplifyOrInst(), simplifyOrOfICmpsWithAdd(), simplifyOrOfICmpsWithSameOperands(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), SimplifyPHINode(), simplifyRelocatesOffABase(), simplifyRem(), SimplifyRightShift(), SimplifySDivInst(), SimplifyShift(), SimplifyShlInst(), SimplifyShuffleVectorInst(), SimplifySRemInst(), SimplifySubInst(), simplifyUnsignedRangeCheck(), simplifyX86addcarry(), simplifyX86insertps(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86movmsk(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), SimplifyXorInst(), sink(), SinkCast(), SinkShiftAndTruncate(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::sortPtrAccesses(), speculatePHINodeLoads(), speculateSelectInstLoads(), splitCallSite(), llvm::SplitLandingPadPredecessors(), splitMergedValStore(), splitRetconCoroutine(), stripAndAccumulateConstantOffsets(), stripAndComputeConstantOffsets(), stripNonValidDataFromBody(), llvm::SubOne(), supportedAddressingMode(), swapMayExposeCSEOpportunities(), truncateIVUse(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryPromoteAllocaToVector(), tryToOptimizeStoreOfMallocToGlobal(), tryToRecognizePopCount(), tryToReplaceWithConstant(), tryToShorten(), TryToShrinkGlobalToBoolean(), TryToSinkInstruction(), tryToVectorizeHorReductionOrInstOperands(), tryUnmergingGEPsAcrossIndirectBr(), TurnSwitchRangeIntoICmp(), TypeSizeToSizeIndex(), UnpackFromArgumentSlot(), unpackLoadToAggregate(), unpackRegsToOrigType(), unpackStoreToAggregate(), llvm::UnreachableInst::UnreachableInst(), llvm::UnrollRuntimeLoopRemainder(), llvm::updateIndexWPDForExports(), updateOperand(), UpdatePHINodes(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), upgradeAbs(), llvm::UpgradeARCRuntime(), upgradeAVX512MaskToSelect(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::UpgradeGlobalVariable(), UpgradeIntrinsicFunction1(), upgradeMaskedCompare(), UpgradeMaskedLoad(), UpgradeMaskedStore(), UpgradeMaskToInt(), upgradePMULDQ(), UpgradeX86AddSubSatIntrinsics(), UpgradeX86ALIGNIntrinsics(), upgradeX86ConcatShift(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), upgradeX86Rotate(), upgradeX86vpcom(), UpgradeX86VPERMT2Intrinsics(), llvm::AMDGPULibCalls::useNative(), valueHasFloatPrecision(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), versionCallSite(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::Interpreter::visitAllocaInst(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitAllocSite(), llvm::InstCombiner::visitAnd(), llvm::ObjectSizeOffsetVisitor::visitArgument(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitBitCast(), llvm::Interpreter::visitBitCastInst(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitCallInst(), llvm::Interpreter::visitExtractElementInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::Interpreter::visitExtractValueInst(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitFAdd(), llvm::Interpreter::visitFCmpInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::Interpreter::visitFPExtInst(), llvm::Interpreter::visitFPToSIInst(), llvm::Interpreter::visitFPToUIInst(), llvm::InstCombiner::visitFPTrunc(), llvm::Interpreter::visitFPTruncInst(), llvm::InstCombiner::visitFSub(), llvm::ObjectSizeOffsetVisitor::visitGEPOperator(), llvm::InstCombiner::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::Interpreter::visitICmpInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitIntToPtr(), llvm::Interpreter::visitIntToPtrInst(), visitIVCast(), llvm::InstCombiner::visitLandingPadInst(), llvm::Interpreter::visitLoadInst(), llvm::InstCombiner::visitLoadInst(), llvm::Interpreter::visitLShr(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPHINode(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), llvm::InstCombiner::visitPtrToInt(), llvm::Interpreter::visitPtrToIntInst(), llvm::Interpreter::visitReturnInst(), llvm::InstCombiner::visitReturnInst(), llvm::InstCombiner::visitSDiv(), llvm::Interpreter::visitSelectInst(), llvm::InstCombiner::visitSExt(), llvm::Interpreter::visitSExtInst(), llvm::Interpreter::visitShl(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::Interpreter::visitSIToFPInst(), llvm::InstCombiner::visitSRem(), llvm::Interpreter::visitStoreInst(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::Interpreter::visitTruncInst(), llvm::InstCombiner::visitUDiv(), llvm::Interpreter::visitUIToFPInst(), llvm::Interpreter::visitUnaryOperator(), llvm::InstCombiner::visitURem(), llvm::Interpreter::visitVAArgInst(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::Interpreter::visitZExtInst(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), llvm::InnerLoopVectorizer::widenPHIInstruction(), willNotOverflow(), wrapConstantAsMetadata(), WriteAsOperandInternal(), WriteConstantInternal(), X86ChooseCmpImmediateOpcode(), llvm::reassociate::XorOpnd::XorOpnd(), and llvm::BasicBlock::~BasicBlock().
getValueID()
unsigned llvm::Value::getValueID () const inline
Return an ID for the concrete type of this object.
This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves. Also, note that for instructions, the Instruction's opcode is added to InstructionVal. So this means three things:
there is no value with code InstructionVal (no opcode==0).
there are more possible values for the value type than in ValueTy enum.
the InstructionVal enumerator must be the highest valued enumerator in
the ValueTy enum.
Definition at line 484 of file Value.h.
Referenced by alwaysAvailable(), llvm::GlobalIFunc::classof(), llvm::ConstantData::classof(), llvm::GlobalIndirectSymbol::classof(), llvm::GlobalAlias::classof(), llvm::Argument::classof(), llvm::Constant::classof(), llvm::MemoryAccess::classof(), llvm::InlineAsm::classof(), llvm::GlobalObject::classof(), llvm::MetadataAsValue::classof(), llvm::GlobalVariable::classof(), llvm::ConstantInt::classof(), llvm::MemoryUseOrDef::classof(), llvm::MemoryUse::classof(), llvm::ConstantFP::classof(), llvm::BasicBlock::classof(), llvm::ConstantAggregateZero::classof(), llvm::MemoryDef::classof(), llvm::ConstantAggregate::classof(), llvm::ConstantArray::classof(), llvm::ConstantStruct::classof(), llvm::ConstantVector::classof(), llvm::ConstantPointerNull::classof(), llvm::GlobalValue::classof(), llvm::MemoryPhi::classof(), llvm::ConstantDataSequential::classof(), llvm::Instruction::classof(), llvm::ConstantDataArray::classof(), llvm::Function::classof(), llvm::ConstantDataVector::classof(), llvm::ConstantTokenNone::classof(), llvm::BlockAddress::classof(), llvm::ConstantExpr::classof(), llvm::UndefValue::classof(), llvm::FunctionComparator::cmpConstants(), CompareValueComplexity(), deleteValue(), llvm::isa_impl< Constant, Value >::doit(), llvm::isa_impl< ConstantData, Value >::doit(), llvm::isa_impl< ConstantAggregate, Value >::doit(), llvm::isa_impl< Argument, Value >::doit(), llvm::isa_impl< InlineAsm, Value >::doit(), llvm::isa_impl< Instruction, Value >::doit(), llvm::isa_impl< BasicBlock, Value >::doit(), llvm::isa_impl< Function, Value >::doit(), llvm::isa_impl< GlobalVariable, Value >::doit(), llvm::isa_impl< GlobalAlias, Value >::doit(), llvm::isa_impl< GlobalIFunc, Value >::doit(), llvm::GlobalValue::eraseFromParent(), llvm::Constant::handleOperandChange(), and llvm::GlobalValue::removeFromParent().
getValueName()
ValueName * Value::getValueName () const
Definition at line 187 of file Value.cpp.
References assert(), getContext(), HasName, I, llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValueNames.
Referenced by deleteValue(), llvm::TargetIntrinsicInfo::getIntrinsicID(), getName(), hasName(), takeName(), and llvm::ValueSymbolTable::~ValueSymbolTable().
hasName()
bool llvm::Value::hasName () const inline
Definition at line 252 of file Value.h.
References getName(), getValueName(), HasName, Name, llvm::No, replaceAllUsesWith(), replaceNonMetadataUsesWith(), setName(), setValueName(), takeName(), and llvm::Yes.
Referenced by AddAliasScopeMetadata(), llvm::canConstantFoldCallTo(), llvm::CloneBasicBlock(), llvm::CloneFunction(), computeFunctionSummary(), llvm::ConstantFoldCall(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::DomTreeUpdater::dump(), externalize(), forEachUser(), FunctionNumber(), llvm::ModuleSummaryIndex::getGlobalValueSummary(), getInstrName(), llvm::ExecutionEngine::getMangledName(), getName(), llvm::Mangler::getNameWithPrefix(), llvm::GetOrCreateFunctionComdat(), getParentPad(), llvm::getSamplerName(), llvm::getSurfaceName(), llvm::getTextureName(), initSlots2BasicBlocks(), insertIfNamed(), instrumentMaskedLoadOrStore(), llvm::TargetTransformInfoImplBase::isLoweredToCall(), makeStatepointExplicitImpl(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), maybePrintCallAddrSpace(), maybePrintComdat(), false::operator<<(), OptimizeFunctions(), OptimizeGlobalAliases(), OptimizeGlobalVars(), llvm::LinkDiagnosticInfo::print(), llvm::ValueEnumerator::print(), llvm::AliasSet::print(), llvm::MemoryPhi::print(), llvm::MachineBasicBlock::print(), printIRBlockReference(), llvm::MIRFormatter::printIRValue(), printWithoutType(), llvm::ReplaceInstWithValue(), RetagMask(), llvm::FastISel::selectInstruction(), suffixed_name_or(), takeName(), llvm::UpgradeGlobalVariable(), writeTypeIdCompatibleVtableSummaryRecord(), and llvm::ValueSymbolTable::~ValueSymbolTable().
hasNUses()
bool Value::hasNUses (unsigned N) const
Return true if this Value has exactly N users.
Definition at line 132 of file Value.cpp.
References llvm::hasNItems(), use_begin(), and use_end().
Referenced by llvm::slpvectorizer::BoUpSLP::canMapToVector(), canonicalizeSaturatedAdd(), createRdxShuffleMask(), hasOneUse(), mergeConditionalStores(), SpeculativelyExecuteBB(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitXor().
hasNUsesOrMore()
bool Value::hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
This is logically equivalent to getNumUses() >= N.
Definition at line 136 of file Value.cpp.
References llvm::hasNItemsOrMore(), use_begin(), and use_end().
Referenced by CanDoGlobalSRA(), canonicalizeSaturatedAdd(), Cleanup(), hasMoreThanOneUseOtherThanLLVMUsed(), hasOneUse(), isBroadcastShuffle(), isLoopIncrement(), processUMulZExtIdiom(), llvm::BasicBlock::removePredecessor(), replaceConstantExprOp(), and llvm::InstCombiner::visitXor().
hasOneUse()
bool llvm::Value::hasOneUse () const inline
Return true if there is exactly one user of this value.
This is specialized because it is a common request and does not require traversing the whole use list.
Definition at line 433 of file Value.h.
References E, getNumUses(), hasNUses(), hasNUsesOrMore(), I, isUsedInBasicBlock(), N, use_begin(), and use_end().
Referenced by canEvaluateShifted(), canEvaluateShuffled(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canNotEvaluateInType(), canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), canSinkInstructions(), canTailPredicateInstruction(), canTransformAccumulatorRecursion(), CC_MipsO32_FP64(), cheapToScalarize(), checkForNegativeOperand(), collectInsertionElements(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), collectValuesToDemote(), combineLoadToOperationType(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), ConvertToSInt(), createAndInstr(), createPowWithIntegerExponent(), createRdxShuffleMask(), DeadPHICycle(), decomposeSimpleLinearExpr(), despeculateCountZeros(), dropRedundantMaskingOfLeftShiftInput(), emitGlobalConstantImpl(), findBuildAggregate(), findInitTrampolineFromAlloca(), FindSingleUseIdentifiedObject(), foldAndToXor(), foldBitcastExtElt(), FoldCondBranchOnPHI(), foldICmpBitCast(), foldICmpShlOne(), foldICmpWithMinMax(), foldIdentityExtractShuffle(), foldInsSequenceIntoSplat(), foldNoWrapAdd(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), foldOrToXor(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), foldSelectShuffle(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldUnsignedUnderflowCheck(), foldVectorCmp(), foldVecTruncToExtElt(), foldXorToXor(), GenerateSignBits(), llvm::ARMTTIImpl::getArithmeticInstrCost(), getBinOpsForFactorization(), llvm::AArch64TTIImpl::getCastInstrCost(), getCompareCC(), getComparePred(), getIntToFPVal(), llvm::SystemZTTIImpl::getMemoryOpCost(), getNegatibleInsts(), getRelevantOperands(), getTypePartition(), llvm::HexagonTTIImpl::getUserCost(), hasSameExtUse(), llvm::FastISel::hasTrivialKill(), hasUseOtherThanLLVMUsed(), hasUsesOutsideLoop(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), llvm::TargetLoweringBase::isExtLoad(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), llvm::SystemZTTIImpl::isFoldableLoad(), isFormingBranchFromSelectProfitable(), isGEPFoldable(), IsInterestingCmp(), isKnownTypeIdMember(), llvm::RecurrenceDescriptor::isMinMaxSelectCmpPattern(), isMulPowOf2(), isOnlyReachableViaThisEdge(), llvm::AArch64TargetLowering::isProfitableToHoist(), isPromotedInstructionLegal(), isReInterleaveMask(), isSafeAndProfitableToSinkLoad(), IsSafeComputationToRemove(), LinearizeExprTree(), lookThroughAnd(), matchDeMorgansLaws(), matchUAddWithOverflowConstantEdgeCases(), narrowUDivURem(), llvm::InstCombiner::OptimizePointerDifference(), processUGT_ADDCST_ADD(), llvm::recognizeBSwapOrBitReverseIdiom(), removeEmptyCleanup(), replaceAllUsesOfWithIn(), replaceExtractElements(), llvm::InstCombiner::run(), llvm::SLPVectorizerPass::runImpl(), shouldBeDeferred(), ShouldBreakUpSubtract(), shouldMergeGEPs(), ShrinkDemandedConstant(), SimplifyBSwap(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SimplifyIndirectBrOnSelect(), simplifyValueKnownNonZero(), sinkAndCmp0Expression(), sinkNotIntoXor(), sinkSelectOperand(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), supportedAddressingMode(), llvm::FastISel::tryToFoldLoad(), TryToSinkInstruction(), llvm::JumpThreadingPass::TryToUnfoldSelect(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitInsertValueInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitLShr(), visitMaskedMerge(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
hasSameSubclassOptionalData()
bool llvm::Value::hasSameSubclassOptionalData (const Value * V) const inline
Check the optional flags for equality.
Definition at line 501 of file Value.h.
References SubclassOptionalData.
hasValueHandle()
bool llvm::Value::hasValueHandle () const inline
Return true if there is a value handle associated with this value.
Definition at line 506 of file Value.h.
Referenced by annotateAnyAllocSite(), llvm::MemorySSAUpdater::removeMemoryAccess(), and llvm::SSAUpdaterBulk::RewriteAllUses().
isSwiftError()
bool Value::isSwiftError () const
Return true if this value is a swifterror value.
swifterror values can be either a function argument or an alloca with a swifterror attribute.
Definition at line 765 of file Value.cpp.
References Arg, assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::dyn_cast(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getPointerIntoBucketsArray(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::isPointerIntoBucketsArray(), llvm::AllocaInst::isSwiftError(), List, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and llvm::LLVMContextImpl::ValueHandles.
Referenced by llvm::AllocaInst::cloneImpl(), combineLoadToOperationType(), combineStoreToValueType(), GlobalWasGeneratedByCompiler(), isAtomic(), isUsedByMetadata(), removeBitcastsFromLoadStoreOnMinMax(), and llvm::HWAddressSanitizerPass::run().
isUsedByMetadata()
bool llvm::Value::isUsedByMetadata () const inline
Return true if there is metadata referencing this value.
Definition at line 509 of file Value.h.
References isSwiftError(), IsUsedByMD, and stripPointerCasts().
Referenced by contains(), llvm::FindDbgAddrUses(), llvm::findDbgUsers(), llvm::findDbgValues(), getStartOrEndSlot(), llvm::hoistAllInstructionsInto(), llvm::replaceAllDbgUsesWith(), and ~Value().
isUsedInBasicBlock()
bool Value::isUsedInBasicBlock (const BasicBlock * BB) const
Check if this value is used in the specified basic block.
Definition at line 140 of file Value.cpp.
References llvm::BasicBlock::begin(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::is_contained(), user_begin(), and user_end().
Referenced by FindAllMemoryUses(), and hasOneUse().
materialized_use_begin() [1/2]
use_iterator llvm::Value::materialized_use_begin () inline
Definition at line 355 of file Value.h.
Referenced by materialized_uses(), and use_begin().
materialized_use_begin() [2/2]
const_use_iterator llvm::Value::materialized_use_begin () const inline
Definition at line 356 of file Value.h.
materialized_use_empty()
bool llvm::Value::materialized_use_empty () const inline
Definition at line 348 of file Value.h.
Referenced by contains().
materialized_user_begin() [1/2]
user_iterator llvm::Value::materialized_user_begin () inline
Definition at line 392 of file Value.h.
Referenced by materialized_users(), user_back(), and user_begin().
materialized_user_begin() [2/2]
const_user_iterator llvm::Value::materialized_user_begin () const inline
Definition at line 393 of file Value.h.
materialized_users() [1/2]
iterator_range<user_iterator> llvm::Value::materialized_users () inline
Definition at line 414 of file Value.h.
References llvm::make_range(), materialized_user_begin(), and user_end().
Referenced by forEachUser(), and users().
materialized_users() [2/2]
iterator_range<const_user_iterator> llvm::Value::materialized_users () const inline
Definition at line 417 of file Value.h.
References llvm::make_range(), materialized_user_begin(), and user_end().
materialized_uses() [1/2]
iterator_range<use_iterator> llvm::Value::materialized_uses () inline
Definition at line 369 of file Value.h.
References llvm::make_range(), materialized_use_begin(), and use_end().
Referenced by uses().
materialized_uses() [2/2]
iterator_range<const_use_iterator> llvm::Value::materialized_uses () const inline
Definition at line 372 of file Value.h.
References llvm::make_range(), materialized_use_begin(), and use_end().
mutateType()
void llvm::Value::mutateType (Type * Ty) inline
Mutate the type of this Value to be of the specified type.
Note that this is an extremely dangerous operation which can create completely invalid IR very easily. It is strongly recommended that you recreate IR objects with the right types instead of mutating them in place.
Definition at line 663 of file Value.h.
References llvm::MCID::Compare, reverseUseList(), and sortUseList().
Referenced by isCallPromotable(), isPromotedResultSafe(), llvm::CallBase::mutateFunctionType(), operator<<(), replaceAllUsesOfWithIn(), and wrapConstantAsMetadata().
operator=()
Value& llvm::Value::operator= (const Value &) delete
print() [1/2]
void Value::print (raw_ostream & O, bool IsForDebug = false) const
Implement operator<< on Value.
Definition at line 4316 of file AsmWriter.cpp.
References getModuleFromVal(), isReferencingMDNode(), and print().
Referenced by llvm::MIRPrinter::convert(), createCast(), llvm::createMemDepPrinter(), ensurePromotedGV(), llvm::IRTranslator::getAnalysisUsage(), isCallPromotable(), llvm::operator<<(), llvm::ValueEnumerator::print(), llvm::AccelTableBase::HashData::print(), print(), llvm::AliasSet::print(), llvm::InstCombiner::run(), scaleCaseProbality(), shouldConvert(), and llvm::VerifierSupport::VerifierSupport().
print() [2/2]
void Value::print (raw_ostream & O, ModuleSlotTracker & MST, bool IsForDebug = false) const
Definition at line 4327 of file AsmWriter.cpp.
References F(), llvm::ModuleSlotTracker::getMachine(), getModuleFromVal(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ModuleSlotTracker::incorporateFunction(), llvm_unreachable, print(), llvm::RISCVFenceField::W, and WriteConstantInternal().
printAsOperand() [1/2]
void Value::printAsOperand (raw_ostream & O, bool PrintType = true, const Module * M = nullptr) const
Print the name of this Value out to the specified raw_ostream.
This is useful when you just want to print 'int reg126', not the instruction that generated it. If you specify a Module for context, then even constanst get pretty-printed; for example, the type of a null pointer is printed symbolically.
Definition at line 4393 of file AsmWriter.cpp.
References getModuleFromVal(), Machine, printAsOperandImpl(), and printWithoutType().
Referenced by llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), llvm::MIRPrinter::convert(), ConvertDoubleToBytes(), llvm::createMemDepPrinter(), llvm::GVNExpression::Expression::dump(), llvm::ScheduleDAGInstrs::Value2SUsMap::dump(), llvm::VPlan::dump(), llvm::AsmPrinter::EmitDebugValue(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::LazyValueInfo::enableDT(), fail(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::AsmPrinter::lowerConstant(), mayUsePostIncMode(), patchAndReplaceAllUsesWith(), llvm::IVUsers::print(), llvm::SCEV::print(), llvm::AliasSet::print(), llvm::MachineMemOperand::print(), llvm::MachineOperand::print(), llvm::MemoryPhi::print(), llvm::VPBlendRecipe::print(), llvm::ScalarEvolution::print(), llvm::GVNExpression::BasicExpression::printInternal(), llvm::GVNExpression::CallExpression::printInternal(), llvm::GVNExpression::LoadExpression::printInternal(), llvm::GVNExpression::StoreExpression::printInternal(), llvm::MIRFormatter::printIRValue(), llvm::printLoop(), PrintModRefResults(), PrintResults(), reportLoadElim(), reportMayClobberedLoad(), setFastFlags(), SinkInstruction(), splitRetconCoroutine(), and llvm::VerifierSupport::VerifierSupport().
printAsOperand() [2/2]
void Value::printAsOperand (raw_ostream & O, bool PrintType, ModuleSlotTracker & MST) const
Definition at line 4408 of file AsmWriter.cpp.
References llvm::ModuleSlotTracker::getMachine(), llvm::ModuleSlotTracker::getModule(), printAsOperandImpl(), and printWithoutType().
replaceAllUsesWith()
void Value::replaceAllUsesWith (Value * V)
Change all uses of this to point to a new Value.
Go through the uses list for this definition and make each use point to "V" instead of "this". After this completes, 'this's use list is guaranteed to be empty.
Definition at line 430 of file Value.cpp.
Referenced by AddCalls(), AddReachableCodeToWorklist(), llvm::MemorySSAUpdater::applyInsertUpdates(), AreSequentialAccesses(), atomicSizeSupported(), buildClonedLoopBlocks(), calcArraySize(), llvm::DomTreeUpdater::callbackDeleteBB(), canCreateAliasFor(), canCreateThunkFor(), llvm::changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), Cleanup(), CleanupConstantGlobalUsers(), llvm::CloneAndPruneIntoFromInst(), collectFunctionUsers(), combineLoadToOperationType(), ComputePostOrders(), ConvertShiftToMul(), llvm::convertToDeclaration(), ConvertToSInt(), llvm::createAMDGPUPrintfRuntimeBinding(), createCallInst(), createCloneDeclaration(), llvm::createCodeGenPreparePass(), llvm::createDeadArgHackingPass(), CreateGCRelocates(), llvm::createObjCARCOptPass(), createOrdering(), createResumeEntryBlock(), llvm::createScalarizerPass(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), cse(), deleteDeadInstruction(), llvm::DemotePHIToStack(), despeculateCountZeros(), llvm::DetatchDeadBlocks(), doPromotion(), llvm::GVNExpression::Expression::dump(), llvm::EliminateDuplicatePHINodes(), eliminateSwiftErrorArgument(), eraseDeadBBsAndChildren(), llvm::objcarc::EraseInstruction(), llvm::expandAtomicRMWToCmpXchg(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::CodeExtractor::findInputsOutputs(), findPHIToPartitionLoops(), llvm::SanitizerStatReport::finish(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), foldAnyOrAllBitsSet(), foldGuardedRotateToFunnelShift(), FoldTwoEntryPHINode(), FunctionNumber(), getChainID(), llvm::VNCoercion::getLoadValueForLoad(), GetLoopInvariantInsertPosition(), getMulHu(), getNegatibleInsts(), getOrInsertValueProfilingCall(), GetPointerOperand(), getReducedType(), getRetComponentType(), GetRMWLibcall(), getScalarIntrinsicDeclaration(), getSignature(), getStartOrEndSlot(), handleNoSuspendCoroutine(), llvm::Constant::handleOperandChange(), hasName(), hasProfileData(), hasSameExtUse(), hasZeroSignBit(), llvm::hoistRegion(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::InlineFunction(), InsertRootInitializers(), insertValues(), instrumentMaskedLoadOrStore(), isCallPromotable(), isKnownTypeIdMember(), isOnlyReachableViaThisEdge(), isPromotedResultSafe(), llvm::log2(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), lowerExpectIntrinsic(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerLoadRelative(), LowerRotate(), lowerSubFn(), llvm::IntrinsicLowering::LowerToByteSwap(), makeBitReverse(), mapBinOpcode(), MarkBlocksLiveIn(), maybeSetDSOLocal(), llvm::MergeBasicBlockIntoOnlyPred(), mergeCleanupPad(), mergeEmptyReturnBlocks(), mergeInlinedArrayAllocas(), llvm::InstDeleterIRStrategy::mutate(), operator<<(), optimizeDivRem(), OptimizeEmptyGlobalCXXDtors(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), OptimizeGlobalAddressOfMalloc(), OptimizeGlobalAliases(), OptimizeNoopCopyExpression(), optimizeSQRT(), patchAndReplaceAllUsesWith(), performMaskedAtomicOp(), processAnd(), processAShr(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCmp(), processInternalGlobal(), processOverflowIntrinsic(), processPHI(), processSaturatingInst(), processSDiv(), processSelect(), processSExt(), processSRem(), processUDivOrURem(), promotedOpIsNUW(), promoteSingleBlockAlloca(), PropagateConstantReturn(), PropagateConstantsIntoArguments(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::removeAllNonTerminatorAndEHPadInstructions(), removeGlobalCtors(), llvm::PHINode::removeIncomingValue(), llvm::BasicBlock::removePredecessor(), llvm::removeUnreachableBlocks(), llvm::removeUnwindEdge(), replace(), replaceAliasWithAliasee(), replaceAllInstructionUsesWith(), replaceAndRecursivelySimplifyImpl(), llvm::AMDGPULibCalls::replaceCall(), ReplaceCallWith(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::replaceCreatedSSACopys(), replaceFrameSize(), llvm::InstCombiner::replaceInstUsesWith(), llvm::ReplaceInstWithValue(), replacePrepare(), replaceSwiftErrorOps(), ReplaceUsesOfWith(), reportLoadElim(), reportMayClobberedLoad(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), RetagMask(), reuseTableCompare(), RewriteHeapSROALoadUser(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), rewritePHINodesForExitAndUnswitchedBlocks(), rewritePHIs(), rewriteSingleStoreAlloca(), llvm::LoadAndStorePromoter::run(), llvm::InstCombiner::run(), llvm::Attributor::run(), llvm::runIPSCCP(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), shouldFixMainFunction(), shouldKeepFDivF32(), simplifyAndDCEInstruction(), simplifyCommonValuePhi(), SimplifyIndirectBrOnSelect(), llvm::simplifyLoopAfterUnroll(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), simplifyRelocatesOffABase(), simplifySuspendPoint(), sink(), speculatePHINodeLoads(), speculateSelectInstLoads(), splitCallSite(), splitGlobal(), llvm::SplitLandingPadPredecessors(), splitRetconCoroutine(), SRAGlobal(), truncateIVUse(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryCSEWithPredecessor(), tryPromoteAllocaToVector(), tryToOptimizeStoreOfMallocToGlobal(), tryToRecognizePopCount(), tryToReplaceWithConstant(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::UnrollAndJamLoop(), llvm::UpgradeARCRuntime(), llvm::AMDGPULibCalls::useNative(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitExtractElementInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), willNotOverflow(), llvm::BasicBlock::~BasicBlock(), and llvm::slpvectorizer::BoUpSLP::~BoUpSLP().
replaceNonMetadataUsesWith()
void Value::replaceNonMetadataUsesWith (Value * V)
Change non-metadata uses of this to point to a new Value.
Go through the uses list for this definition and make each use point to "V" instead of "this". This function skips metadata entries in the list.
Definition at line 434 of file Value.cpp.
Referenced by hasName().
replaceUsesOutsideBlock()
void Value::replaceUsesOutsideBlock (Value * V, BasicBlock * BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
'This's use list is expected to have at least one element. Unlike replaceAllUsesWith() this function does not support basic block values or constant users.
Definition at line 440 of file Value.cpp.
References assert(), contains(), llvm::dyn_cast(), getType(), llvm::Use::getUser(), I, and replaceUsesWithIf().
Referenced by createFFSIntrinsic(), llvm::InstCombiner::replacedSelectWithOperand(), and replaceUsesWithIf().
replaceUsesWithIf()
void llvm::Value::replaceUsesWithIf (Value * New, llvm::function_ref< bool(Use &U)> ShouldReplace) inline
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
Unlike replaceAllUsesWith() this function does not support basic block values or constant users.
Definition at line 301 of file Value.h.
References assert(), assertModuleIsMaterializedImpl(), E, getType(), replaceUsesOutsideBlock(), llvm::Use::set(), use_begin(), and use_end().
Referenced by INITIALIZE_PASS(), llvm::MemorySSAUpdater::insertDef(), isDirectCall(), replaceUsesOutsideBlock(), RetagMask(), and sinkInstruction().
reverseUseList()
void Value::reverseUseList ()
Reverse the use-list.
Definition at line 746 of file Value.cpp.
Referenced by mutateType().
setName()
void Value::setName (const Twine & Name)
Change the name of the value.
Choose a new unique name if the provided name is taken.
Parameters
Name The new name; or "" if the value's name should be removed.
Definition at line 286 of file Value.cpp.
References F().
Referenced by llvm::GetElementPtrInst::accumulateConstantOffset(), AddCalls(), llvm::AllocaInst::AllocaInst(), annotateAnyAllocSite(), llvm::Argument::Argument(), llvm::BinaryOperator::BinaryOperator(), llvm::CloneBasicBlock(), llvm::CloneFunction(), cloneInstForMustTail(), CloneInstructionInExitBlock(), llvm::JumpThreadingPass::CloneInstructions(), llvm::CloneModule(), llvm::CmpInst::CmpInst(), llvm::LandingPadInst::Create(), llvm::CallBrInst::Create(), llvm::createAArch64StackTaggingPass(), llvm::CallInst::CreateFree(), createMemMoveLoop(), llvm::OpenMPIRBuilder::CreateParallel(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), createWrapper(), doPromotion(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), eliminateRecursiveTailCall(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitSCEVChecks(), externalize(), llvm::FenceInst::FenceInst(), llvm::CodeExtractor::findInputsOutputs(), llvm::InnerLoopVectorizer::fixupIVUsers(), FoldCondBranchOnPHI(), forceRenaming(), llvm::FreezeInst::FreezeInst(), FunctionNumber(), generateUnsignedDivisionCode(), llvm::BasicBlock::getContext(), llvm::InvokeInst::getLandingPadInst(), hasName(), INITIALIZE_PASS(), llvm::IRBuilderDefaultInserter::InsertHelper(), instrumentMaskedLoadOrStore(), llvm::ShuffleVectorInst::isConcat(), isKnownTypeIdMember(), isOnlyReachableViaThisEdge(), isSupportedGuardInstruction(), llvm::ExtractElementInst::isValidOperands(), llvm::LoadInst::LoadInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::makeGuardControlFlowExplicit(), makeStatepointExplicitImpl(), NegateValue(), optimizeDivRem(), llvm::peelLoop(), llvm::CallBase::populateBundleOperandInfos(), postDominates(), rematerializeLiveValues(), llvm::CatchSwitchInst::removeHandler(), rename(), ReplaceCallWith(), RetagMask(), rewriteComdat(), rewriteMaterializableInstructions(), llvm::InnerLoopVectorizer::scalarizeInstruction(), selectJumpTableArmEncoding(), shouldFixMainFunction(), shouldRotateLoopExitingLatch(), llvm::ShuffleVectorInst::ShuffleVectorInst(), sinkInstruction(), splitBlockIfNotFirst(), llvm::SplitLandingPadPredecessors(), StripSymtab(), SwitchToLookupTable(), takeName(), turnGuardIntoBranch(), llvm::UnaryOperator::UnaryOperator(), unpackLoadToAggregate(), llvm::UnrollRuntimeLoopRemainder(), llvm::UpgradeARCRuntime(), llvm::VAArgInst::VAArgInst(), llvm::LoopVersioning::versionLoop(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
setValueName()
void Value::setValueName (ValueName * VN)
Definition at line 198 of file Value.cpp.
References assert(), getContext(), HasName, llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValueNames.
Referenced by deleteValue(), getName(), hasName(), rewriteComdat(), takeName(), and llvm::ValueSymbolTable::~ValueSymbolTable().
setValueSubclassData()
void llvm::Value::setValueSubclassData (unsigned short D) inline protected
Definition at line 715 of file Value.h.
References D.
Referenced by llvm::Function::classof(), llvm::ConstantExpr::classof(), computeAddrSpace(), llvm::ConstantExpr::ConstantExpr(), llvm::Function::dropAllReferences(), llvm::BasicBlock::getLandingPadInst(), llvm::CmpInst::makeCmpResultType(), llvm::Function::setPrologueData(), llvm::Function::stealArgumentListFrom(), and llvm::Function::~Function().
sortUseList()
template<class Compare > void llvm::Value::sortUseList (Compare Cmp)
Sort the use-list.
Sorts the Value's use-list by Cmp using a stable mergesort. Cmp is expected to compare two Use references.
Definition at line 746 of file Value.h.
References assert(), and I.
Referenced by mutateType().
stripAndAccumulateConstantOffsets() [1/2]
const Value * Value::stripAndAccumulateConstantOffsets (const DataLayout & DL, APInt & Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Only 'getelementptr' instructions (GEPs) with constant indices are accumulated but other instructions, e.g., casts, are stripped away as well. The accumulated constant offset is added to Offset and the base pointer is returned.
The APInt Offset has to have a bit-width equal to the IntPtr type for the address space of 'this' pointer value, e.g., use DataLayout::getIndexTypeSizeInBits(Ty).
If AllowNonInbounds is true, constant offsets in GEPs are stripped and accumulated even if the GEP is not "inbounds".
If this is called on a non-pointer value, it returns 'this' and the Offset is not modified.
Note that this function will never return a nullptr. It will also never manipulate the Offset in a way that would not match the difference between the underlying value and the returned one. Thus, if no constant offset was found, the returned value is the underlying one and Offset is unchanged.
Definition at line 551 of file Value.cpp.
References assert(), GEP, llvm::APInt::getBitWidth(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::APInt::getMinSignedBits(), llvm::Operator::getOpcode(), getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Type::isPtrOrPtrVectorTy(), and llvm::APInt::sextOrTrunc().
Referenced by llvm::GetPointerBaseWithConstantOffset(), stripAndAccumulateConstantOffsets(), stripAndAccumulateInBoundsConstantOffsets(), stripAndComputeConstantOffsets(), and stripInBoundsConstantOffsets().
stripAndAccumulateConstantOffsets() [2/2]
Value* llvm::Value::stripAndAccumulateConstantOffsets (const DataLayout & DL, APInt & Offset, bool AllowNonInbounds) inline
Definition at line 593 of file Value.h.
References stripAndAccumulateConstantOffsets().
stripAndAccumulateInBoundsConstantOffsets() [1/2]
const Value* llvm::Value::stripAndAccumulateInBoundsConstantOffsets (const DataLayout & DL, APInt & Offset) const inline
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Definition at line 602 of file Value.h.
References stripAndAccumulateConstantOffsets().
Referenced by llvm::IRPosition::getAttrs(), llvm::GlobalIndirectSymbol::getBaseObject(), llvm::isConsecutiveAccess(), propagateMetadata(), and llvm::InstCombiner::visitGetElementPtrInst().
stripAndAccumulateInBoundsConstantOffsets() [2/2]
Value* llvm::Value::stripAndAccumulateInBoundsConstantOffsets (const DataLayout & DL, APInt & Offset) inline
Definition at line 607 of file Value.h.
References stripAndAccumulateConstantOffsets(), and stripInBoundsOffsets().
stripInBoundsConstantOffsets() [1/2]
const Value * Value::stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Returns the original pointer value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 542 of file Value.cpp.
Referenced by llvm::CodeExtractorAnalysisCache::CodeExtractorAnalysisCache(), FixedPointIntrinsicToOpcode(), llvm::CodeExtractor::isLegalToShrinkwrapLifetimeMarkers(), llvm::FastISel::selectIntrinsicCall(), stripInBoundsConstantOffsets(), and stripPointerCastsAndInvariantGroups().
stripInBoundsConstantOffsets() [2/2]
Value* llvm::Value::stripInBoundsConstantOffsets () inline
Definition at line 564 of file Value.h.
References stripAndAccumulateConstantOffsets(), and stripInBoundsConstantOffsets().
stripInBoundsOffsets() [1/2]
const Value * Value::stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Returns the original pointer value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 605 of file Value.cpp.
Referenced by getTypePartition(), shouldInstrumentReadWriteFromAddress(), stripAndAccumulateInBoundsConstantOffsets(), stripInBoundsOffsets(), and llvm::sroa::AllocaSliceRewriter::visit().
stripInBoundsOffsets() [2/2]
Value* llvm::Value::stripInBoundsOffsets () inline
Definition at line 618 of file Value.h.
References DoPHITranslation(), getPointerAlignment(), getPointerDereferenceableBytes(), and stripInBoundsOffsets().
stripPointerCasts() [1/2]
const Value * Value::stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Returns the original uncasted value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 530 of file Value.cpp.
Referenced by AddCalls(), llvm::MachineFunction::addLandingPad(), annotateAnyAllocSite(), canSinkInstructions(), llvm::Attributor::changeUseAfterManifest(), checkWFAlloc(), checkWFDealloc(), checkWFRetconPrototype(), llvm::classifyEHPersonality(), compareNames(), llvm::ObjectSizeOffsetVisitor::compute(), llvm::ObjectSizeOffsetEvaluator::compute(), computePointerICmp(), ConvertDoubleToBytes(), llvm::createObjCARCOptPass(), despeculateCountZeros(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), emitUnaryFloatFnCallHelper(), enforceKnownAlignment(), llvm::objcarc::EraseInstruction(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), llvm::ExtractTypeInfo(), findArgumentCopyElisionCandidates(), llvm::FindAvailablePtrLoadStore(), findBasePointer(), llvm::findDevirtualizableCallsForTypeTest(), findInitTrampoline(), findInitTrampolineFromAlloca(), findSafeStoreForStoreStrongContraction(), FindUsedValues(), findUsedValues(), FixedPointIntrinsicToOpcode(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), genericValueTraversal(), getCalledFunction(), llvm::AbstractCallSite::getCalledFunction(), llvm::getConstantDataArrayInfo(), llvm::MemIntrinsicBase< AnyMemIntrinsic >::getDest(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getKnownConstant(), llvm::InstrProfIncrementInst::getName(), llvm::InstrProfValueProfileInst::getName(), getOpenCLAlignment(), getParentPad(), llvm::CoroIdInst::getPromise(), llvm::objcarc::GetRCIdentityRoot(), llvm::objcarc::getreturnRVOperand(), llvm::MemTransferBase< AnyMemIntrinsic >::getSource(), GetStringLengthH(), getSuccState(), hasNoAliasAttr(), hasUndefContents(), llvm::InlineFunction(), InsertRootInitializers(), isKnownNonConstant(), isObjectSizeLessThanOrEq(), isOverwrite(), llvm::isPointerOffset(), isPossibleIndirectCallTarget(), llvm::isSafeToLoadUnconditionally(), isUsedByMetadata(), isZero(), llvm::BlockAddress::lookup(), moveUp(), OptimizeEmptyGlobalCXXDtors(), optimizeOnceStoredGlobal(), llvm::JumpThreadingPass::ProcessBlock(), removePartiallyOverlappedStores(), replacePrepare(), llvm::FastISel::selectPatchpoint(), shouldFixMainFunction(), llvm::Constant::stripPointerCasts(), stripPointerCasts(), tryToMoveFreeBeforeNullTest(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InstCombiner::visitLandingPadInst().
stripPointerCasts() [2/2]
Value* llvm::Value::stripPointerCasts () inline
Definition at line 522 of file Value.h.
References stripPointerCasts(), and stripPointerCastsAndAliases().
stripPointerCastsAndAliases() [1/2]
const Value * Value::stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Returns the original uncasted value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 534 of file Value.cpp.
Referenced by stripPointerCasts(), and stripPointerCastsAndAliases().
stripPointerCastsAndAliases() [2/2]
Value* llvm::Value::stripPointerCastsAndAliases () inline
Definition at line 532 of file Value.h.
References stripPointerCastsAndAliases(), and stripPointerCastsSameRepresentation().
stripPointerCastsAndInvariantGroups() [1/2]
const Value * Value::stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Returns the original uncasted value. If this is called on a non-pointer value, it returns 'this'. This function should be used only in Alias analysis.
Definition at line 546 of file Value.cpp.
Referenced by aliasSameBasePointerGEPs(), MergeAliasResults(), stripPointerCastsAndInvariantGroups(), and stripPointerCastsSameRepresentation().
stripPointerCastsAndInvariantGroups() [2/2]
Value* llvm::Value::stripPointerCastsAndInvariantGroups () inline
Definition at line 554 of file Value.h.
References stripInBoundsConstantOffsets(), and stripPointerCastsAndInvariantGroups().
stripPointerCastsSameRepresentation() [1/2]
const Value * Value::stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Returns the original uncasted value with the same representation. If this is called on a non-pointer value, it returns 'this'.
Definition at line 538 of file Value.cpp.
Referenced by llvm::LazyValueInfo::getPredicateAt(), llvm::PointerMayBeCaptured(), stripPointerCastsAndAliases(), and stripPointerCastsSameRepresentation().
stripPointerCastsSameRepresentation() [2/2]
Value* llvm::Value::stripPointerCastsSameRepresentation () inline
Definition at line 543 of file Value.h.
References stripPointerCastsAndInvariantGroups(), and stripPointerCastsSameRepresentation().
takeName()
void Value::takeName (Value * V)
Transfer the name from V to this value.
After taking V's name, sets V's name to empty.
Note
It is an error to call V->takeName(V).
Definition at line 292 of file Value.cpp.
References assert(), getSymTab(), getValueName(), hasName(), setName(), llvm::StringMapEntryStorage< ValueTy >::setValue(), setValueName(), and llvm::ARM_MB::ST.
Referenced by annotateAnyAllocSite(), buildClonedLoopBlocks(), canCreateAliasFor(), canCreateThunkFor(), llvm::changeToCall(), llvm::InstCombiner::computeOverflow(), ConvertShiftToMul(), llvm::convertToDeclaration(), ConvertToSInt(), llvm::createAArch64StackTaggingPass(), llvm::createDeadArgHackingPass(), llvm::createScalarizerPass(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), decomposeSimpleLinearExpr(), doPromotion(), eliminateRecursiveTailCall(), foldICmpBitCast(), foldOperationIntoPhiValue(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), FoldTwoEntryPHINode(), forceRenaming(), getBinOpsForFactorization(), llvm::VNCoercion::getLoadValueForLoad(), getMinVisibility(), getReducedType(), getRetComponentType(), getScalarIntrinsicDeclaration(), getSignature(), HandleInlinedEHPad(), hasName(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::InlineFunction(), InsertRootInitializers(), insertValues(), instrumentMaskedLoadOrStore(), isGEPFoldable(), isKnownTypeIdMember(), isSelect01(), isZeroLengthArray(), LowerNegateToMultiply(), OptimizeGlobalAliases(), llvm::Attributor::registerFunctionSignatureRewrite(), removeGlobalCtors(), llvm::removeUnwindEdge(), replaceAliasWithAliasee(), llvm::ReplaceInstWithValue(), replaceSwiftErrorOps(), replaceUnaryCall(), reportLoadElim(), reportMayClobberedLoad(), RetagMask(), rewritePHIs(), setUsedInitializer(), shouldKeepFDivF32(), ShrinkDemandedConstant(), simplifyAllocaArraySize(), simplifyAssocCastAssoc(), SimplifyBSwap(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), simplifyRelocatesOffABase(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), TryToShrinkGlobalToBoolean(), unifyBitWidth(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitTrunc(), and llvm::InstCombiner::visitXor().
use_begin() [1/2]
use_iterator llvm::Value::use_begin () inline
Definition at line 359 of file Value.h.
References assertModuleIsMaterialized(), and materialized_use_begin().
Referenced by AddCalls(), llvm::MemorySSAUpdater::applyInsertUpdates(), createCallInst(), eliminateSwiftErrorAlloca(), getNumUses(), getSignature(), hasNUses(), hasNUsesOrMore(), hasOneUse(), isDirectCall(), isEligibleForMerging(), isMulPowOf2(), LLVMGetFirstUse(), lookThroughAnd(), lowerLoadRelative(), lowerObjCCall(), OptimizeGlobalAddressOfMalloc(), predictValueUseListOrder(), llvm::ValueEnumerator::print(), llvm::MemorySSAUpdater::removeMemoryAccess(), replaceAllPrepares(), replaceDominatedUsesWith(), replaceLoopInvariantUses(), llvm::replaceNonLocalUsesWith(), replacePrepare(), replaceUsesWithIf(), RewriteUsesOfClonedInstructions(), and llvm::InstCombiner::run().
use_begin() [2/2]
const_use_iterator llvm::Value::use_begin () const inline
Definition at line 363 of file Value.h.
References assertModuleIsMaterialized(), and materialized_use_begin().
use_empty()
bool llvm::Value::use_empty () const inline
Definition at line 343 of file Value.h.
References assertModuleIsMaterialized().
Referenced by AddCalls(), AddReachableCodeToWorklist(), annotateAnyAllocSite(), llvm::attributesPermitTailCall(), llvm::DomTreeUpdater::callbackDeleteBB(), canCreateAliasFor(), combineLoadToOperationType(), ComputePostOrders(), containsProfilingIntrinsics(), ConvertToSInt(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::createDeadArgHackingPass(), llvm::createDwarfEHPass(), llvm::createObjCARCOptPass(), createRetPHINode(), DCEInstruction(), DeadPHICycle(), deleteDeadInstruction(), deleteIfDead(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), despeculateCountZeros(), llvm::DetatchDeadBlocks(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::AsmPrinter::doFinalization(), doPromotion(), llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), llvm::InstCombiner::eraseInstFromFunction(), llvm::objcarc::EraseInstruction(), FixedPointIntrinsicToOpcode(), llvm::IRPosition::getAttrs(), getMaxBackedgeTakenCount(), llvm::lto::LTO::getMaxTasks(), getMinVisibility(), getRetComponentType(), getScalarIntrinsicDeclaration(), getSignature(), hasAddressTakenAndUsed(), hasProfileData(), hasSameExtUse(), hasUseOtherThanLLVMUsed(), hasUsesOutsideLoop(), llvm::hoistRegion(), llvm::InlineFunction(), isBroadcastShuffle(), isCallableFunction(), isDirectCall(), llvm::isInstructionTriviallyDead(), isLoadInvariantInLoop(), IsNonLocalValue(), isOnlyReachableViaThisEdge(), isOnlyUsedInEntryBlock(), isPromotedInstructionLegal(), isReportingError(), isSafeToEliminateVarargsCast(), isSafeToPromoteArgument(), isUsedOutsideOfDefiningBlock(), LinearizeExprTree(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerLoadRelative(), lowerObjCCall(), LowerRotate(), makeStatepointExplicitImpl(), MarkBlocksLiveIn(), mergeConstants(), mustPreserveGV(), OptimizeAwayTrappingUsesOfLoads(), OptimizeExtractBits(), OptimizeGlobalAddressOfMalloc(), optimizeGlobalsInModule(), optimizeMemCmpConstantSize(), passingValueIsAlwaysUndefined(), patchAndReplaceAllUsesWith(), performMaskedAtomicOp(), predictValueUseListOrder(), processInternalGlobal(), llvm::promoteLoopAccessesToScalars(), promoteSingleBlockAlloca(), PropagateConstantsIntoArguments(), propagateMetadata(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::StatepointLoweringState::relocCallVisited(), llvm::removeAllNonTerminatorAndEHPadInstructions(), RemoveDeadConstant(), llvm::LazyCallGraph::removeDeadFunction(), removeDeadUsersOfConstant(), removeEmptyCleanup(), llvm::MemorySSA::removeFromLookups(), removeGlobalCtors(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::removeUnreachableBlocks(), ReplaceCallWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::LazyCallGraph::RefSCC::replaceNodeFunction(), RewriteUsesOfClonedInstructions(), RewriteUsesOfLoadForHeapSRoA(), llvm::GlobalDCEPass::run(), llvm::InlinerPass::run(), llvm::LoadAndStorePromoter::run(), llvm::InstCombiner::run(), llvm::JumpThreadingPass::runImpl(), llvm::runIPSCCP(), llvm::StatepointLoweringState::scheduleRelocCall(), llvm::FastISel::selectIntrinsicCall(), llvm::FastISel::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), simplifyAndDCEInstruction(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SinkCast(), sinkCmpExpression(), AllocaSlices::SliceBuilder::SliceBuilder(), speculatePHINodeLoads(), speculateSelectInstLoads(), splitCallSite(), splitGlobal(), splitGlobals(), llvm::SplitLandingPadPredecessors(), SRAGlobal(), llvm::Function::stealArgumentListFrom(), stripDeadPrototypes(), StripSymbolNames(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), TryToShrinkGlobalToBoolean(), updateOperand(), llvm::UpgradeARCRuntime(), useFuncSeen(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::PtrUseVisitor< SliceBuilder >::visitGetElementPtrInst(), llvm::VPReplicateRecipe::VPReplicateRecipe(), willNotOverflow(), llvm::BasicBlock::~BasicBlock(), and ~Value().
use_end() [1/2]
use_iterator llvm::Value::use_end () inline
Definition at line 367 of file Value.h.
Referenced by AddCalls(), createCallInst(), eliminateSwiftErrorAlloca(), getNumUses(), getSignature(), hasNUses(), hasNUsesOrMore(), hasOneUse(), isDirectCall(), isEligibleForMerging(), LLVMGetFirstUse(), lowerLoadRelative(), lowerObjCCall(), materialized_uses(), predictValueUseListOrder(), replaceAllPrepares(), replaceDominatedUsesWith(), replaceLoopInvariantUses(), llvm::replaceNonLocalUsesWith(), replacePrepare(), replaceUsesWithIf(), and RewriteUsesOfClonedInstructions().
use_end() [2/2]
const_use_iterator llvm::Value::use_end () const inline
Definition at line 368 of file Value.h.
user_back() [1/2]
User* llvm::Value::user_back () inline
Definition at line 406 of file Value.h.
References assertModuleIsMaterialized(), and materialized_user_begin().
Referenced by llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), doPromotion(), emitGlobalConstantImpl(), findInitTrampolineFromAlloca(), getRetComponentType(), OptimizeGlobalAddressOfMalloc(), removeDeadUsersOfConstant(), llvm::runIPSCCP(), SRAGlobal(), StripSymbolNames(), TryToShrinkGlobalToBoolean(), llvm::InstCombiner::visitInsertValueInst(), and llvm::BasicBlock::~BasicBlock().
user_back() [2/2]
const User* llvm::Value::user_back () const inline
Definition at line 410 of file Value.h.
References assertModuleIsMaterialized(), and materialized_user_begin().
user_begin() [1/2]
user_iterator llvm::Value::user_begin () inline
Definition at line 396 of file Value.h.
References assertModuleIsMaterialized(), and materialized_user_begin().
Referenced by addAllGlobalValueUsers(), annotateNonNullAndDereferenceable(), areAllUsesEqual(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canPaddingBeAccessed(), canSinkInstructions(), canTailPredicateInstruction(), llvm::GraphTraits< Inverse< MemoryAccess * > >::child_begin(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), combineLoadToOperationType(), ConstantPropUsersOf(), ConvertToSInt(), llvm::ScalarEvolution::delinearize(), llvm::CodeExtractor::findInputsOutputs(), foldOperationIntoPhiValue(), GenerateSignBits(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::getMallocType(), llvm::SystemZTTIImpl::getMemoryOpCost(), getOutliningPenalty(), getTypePartition(), llvm::AliasSet::getUniqueInstruction(), hasProfileData(), hasSameExtUse(), llvm::FastISel::hasTrivialKill(), hasUsesOutsideLoop(), INITIALIZE_PASS(), llvm::isAllocaPromotable(), llvm::SystemZTTIImpl::isFoldableLoad(), isIgnorableInst(), isKnownTypeIdMember(), llvm::RecurrenceDescriptor::isMinMaxSelectCmpPattern(), isPromotedInstructionLegal(), isReInterleaveMask(), isUsedInBasicBlock(), isZeroLengthArray(), LinearizeExprTree(), MarkBlocksLiveIn(), moveUp(), operator new(), OptimizeAwayTrappingUsesOfLoads(), OptimizeAwayTrappingUsesOfValue(), OptimizeEmptyGlobalCXXDtors(), OptimizeExtractBits(), passingValueIsAlwaysUndefined(), processUMulZExtIdiom(), promoteSingleBlockAlloca(), removeLifetimeIntrinsicUsers(), replaceAllUsesOfWithIn(), replaceConstantExprOp(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), RewriteHeapSROALoadUser(), rewriteSingleStoreAlloca(), RewriteUsesOfLoadForHeapSRoA(), llvm::InstCombiner::run(), sink(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), sinkLastInstruction(), supportedAddressingMode(), llvm::UpgradeARCRuntime(), llvm::UpgradeCallsToIntrinsic(), and llvm::PredicateInfo::~PredicateInfo().
user_begin() [2/2]
const_user_iterator llvm::Value::user_begin () const inline
Definition at line 400 of file Value.h.
References assertModuleIsMaterialized(), and materialized_user_begin().
user_empty()
bool llvm::Value::user_empty () const inline
Definition at line 384 of file Value.h.
References assertModuleIsMaterialized().
Referenced by canSinkInstructions(), llvm::IRPosition::getAttrs(), llvm::AliasSet::getUniqueInstruction(), hasUsesOutsideLoop(), INITIALIZE_PASS(), isValidCandidateForColdCC(), and sinkLastInstruction().
user_end() [1/2]
user_iterator llvm::Value::user_end () inline
Definition at line 404 of file Value.h.
Referenced by addAllGlobalValueUsers(), annotateNonNullAndDereferenceable(), areAllUsesEqual(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canPaddingBeAccessed(), llvm::GraphTraits< Inverse< MemoryAccess * > >::child_end(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), combineLoadToOperationType(), ConstantPropUsersOf(), llvm::ScalarEvolution::delinearize(), llvm::CodeExtractor::findInputsOutputs(), foldOperationIntoPhiValue(), llvm::getMallocType(), llvm::AliasSet::getUniqueInstruction(), hasProfileData(), INITIALIZE_PASS(), llvm::isAllocaPromotable(), isReInterleaveMask(), isUsedInBasicBlock(), isZeroLengthArray(), MarkBlocksLiveIn(), materialized_users(), moveUp(), operator new(), OptimizeAwayTrappingUsesOfLoads(), OptimizeAwayTrappingUsesOfValue(), OptimizeEmptyGlobalCXXDtors(), OptimizeExtractBits(), processUMulZExtIdiom(), promoteSingleBlockAlloca(), removeLifetimeIntrinsicUsers(), replaceAllUsesOfWithIn(), replaceConstantExprOp(), RewriteHeapSROALoadUser(), rewriteSingleStoreAlloca(), RewriteUsesOfLoadForHeapSRoA(), sink(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), llvm::UpgradeARCRuntime(), llvm::UpgradeCallsToIntrinsic(), and llvm::PredicateInfo::~PredicateInfo().
user_end() [2/2]
const_user_iterator llvm::Value::user_end () const inline
Definition at line 405 of file Value.h.
users() [1/2]
iterator_range<user_iterator> llvm::Value::users () inline
Definition at line 420 of file Value.h.
References assertModuleIsMaterialized(), and materialized_users().
Referenced by addAllGlobalValueUsers(), addNoRecurseAttrsTopDown(), llvm::InstCombineWorklist::AddUsersToWorkList(), allCallersPassValidPointerForArgument(), AllGlobalLoadUsesSimpleEnoughForHeapSRA(), allNonInstructionUsersCanBeMadeInstructions(), allUsersAreInFunction(), AllUsesOfLoadedValueWillTrapIfNull(), AllUsesOfValueWillTrapIfNull(), annotateAnyAllocSite(), llvm::MemorySSAUpdater::applyInsertUpdates(), BlockIsSimpleEnoughToThreadThrough(), calcArraySize(), calculateCXXStateNumbers(), calculateSEHStateNumbers(), llvm::canFreelyInvertAllUsersOf(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), llvm::canTrackGlobalVariableInterprocedurally(), ChangeCalleesToFastCall(), changeCallSitesToColdCC(), cheapToScalarize(), clearAssumptionsOfUsers(), llvm::InnerLoopVectorizer::clearReductionWrapFlags(), llvm::CloneAndPruneIntoFromInst(), cloneConstantExprWithNewAddressSpace(), collectCallers(), collectFunctionUsers(), combineLoadToOperationType(), completeEphemeralValues(), ComputePostOrders(), ConvertToSInt(), llvm::createAMDGPUPrintfRuntimeBinding(), createCallInst(), createCast(), llvm::createCodeGenPreparePass(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::createDefUseEdges(), llvm::createObjCARCOptPass(), createRetBitCast(), createRetPHINode(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), llvm::InstCombiner::dominatesAllUses(), doPromotion(), llvm::LazyValueInfo::enableDT(), eraseDeadBBsAndChildren(), llvm::slpvectorizer::BoUpSLP::eraseInstructions(), llvm::CodeExtractor::findAllocas(), llvm::FindDbgAddrUses(), llvm::findDbgUsers(), llvm::findDbgValues(), findInitTrampolineFromAlloca(), findInnerReductionPhi(), llvm::CodeExtractor::findInputsOutputs(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), findReturnsToZap(), FindSingleUseIdentifiedObject(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), foldICmpWithDominatingICmp(), foldOperationIntoPhiValue(), getCleanupRetUnwindDest(), getFirstNonAllocaInTheEntryBlock(), GetLoopInvariantInsertPosition(), llvm::HexagonTargetObjectFile::getLutUsedFunction(), llvm::GlobalsAAResult::getModRefBehavior(), getModuleFromVal(), getNegatibleInsts(), getNumGlobalVariableUses(), getParentPad(), GetPointerOperand(), getPreferredExtendForValue(), getRangeForAffineARHelper(), getRelevantOperands(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::getRelocates(), getSignature(), getTypePartition(), llvm::getUniqueCastUse(), getUnwindDestToken(), getUnwindDestTokenHelper(), GlobalUsersSafeToSRA(), hasBranchUse(), hasCFUser(), hasChangeableCC(), hasExceptionPointerOrCodeUser(), hasLifetimeMarkers(), llvm::hasOutsideLoopUser(), hasProfileData(), hasSameExtUse(), hasStoreUsersOnly(), hasUsersIn(), hasUsesOutsideLoop(), hasZeroSignBit(), INITIALIZE_PASS(), llvm::DivergenceAnalysis::inRegion(), insertSinCosCall(), insertSpills(), llvm::isAllocaPromotable(), isAllocSiteRemovable(), llvm::Loop::isAuxiliaryInductionVariable(), isBroadcastShuffle(), isCallPromotable(), isContiguous(), llvm::Function::isDefTriviallyDead(), isEmptyFunction(), isEphemeralValueOf(), isFuncOrArgAttr(), isFuncOrderCorrect(), isGOTEquivalentCandidate(), isHighCostExpansion(), isIgnorableInst(), llvm::isInlineViable(), isKnownNonNullFromDominatingCondition(), isLoadInvariantInLoop(), isLocalAlloca(), isLoopIncrement(), isNotUsedOrFreeInLoop(), isOnlyUsedInComparisonWithZero(), isOnlyUsedInEntryBlock(), isOnlyUsedInEqualityComparison(), llvm::isOnlyUsedInZeroEqualityComparison(), llvm::isOverflowIntrinsicNoWrap(), isPointerValueDeadOnEntryToFunction(), isProfitableChain(), isSafeAndProfitableToSinkLoad(), llvm::TargetFrameLowering::isSafeForNoCSROpt(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), isSafeSROAGEP(), llvm::isSafeToDestroyConstant(), isTargetConstant(), isUsedByLifetimeMarker(), isUsedOutsideOfDefiningBlock(), isValidCandidateForColdCC(), isVectorReductionOp(), LoadUsesSimpleEnoughForHeapSRA(), localAllocaNeedsStackSave(), llvm::log2(), llvm::LowerDbgDeclare(), makeAllConstantUsesInstructions(), mapBinOpcode(), mapWasmLandingPadIndex(), MarkBlocksLiveIn(), matchUAddWithOverflowConstantEdgeCases(), mergeInlinedArrayAllocas(), moveUp(), mustExecuteUBIfPoisonOnPathTo(), llvm::InnerLoopVectorizer::needsScalarInduction(), negateICmpIfUsedByBranchOrSelectOnly(), NegateValue(), okayForPHIOfOps(), OnlyUsedBy(), llvm::onlyUsedByLifetimeMarkers(), optimizeDoubleFP(), performMaskedAtomicOp(), llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), llvm::AlignmentFromAssumptionsPass::processAssumption(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::promoteLoopAccessesToScalars(), promoteSingleBlockAlloca(), PushDefUseChildren(), pushIVUsers(), PushLoopPHIs(), relocationViaAlloca(), llvm::safestack::StackColoring::removeAllMarkers(), RemoveAttribute(), RemoveInstInputs(), replaceAndRecursivelySimplifyImpl(), llvm::coro::replaceCoroFree(), replaceExtractElements(), ReplaceUsesOfWith(), reportMayClobberedLoad(), rewriteNonInstructionUses(), llvm::StackProtector::runOnFunction(), setCannotDuplicate(), shouldBeDeferred(), llvm::AArch64TTIImpl::shouldConsiderAddressTypePromotion(), simplifyAllocaArraySize(), simplifyAndDCEInstruction(), simplifyRelocatesOffABase(), sinkAndCmp0Expression(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::Solve(), splitGlobal(), SRAGlobal(), swapMayExposeCSEOpportunities(), SwitchToLookupTable(), truncateIVUse(), tryPromoteAllocaToVector(), tryToElideArgumentCopy(), TryToShrinkGlobalToBoolean(), tryUnmergingGEPsAcrossIndirectBr(), usedInGlobalVarDef(), usedInOneFunc(), useFuncSeen(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::LoopVersioning::versionLoop(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitShuffleVectorInst(), willNotOverflow(), and ~Value().
users() [2/2]
iterator_range<const_user_iterator> llvm::Value::users () const inline
Definition at line 424 of file Value.h.
References assertModuleIsMaterialized(), and materialized_users().
uses() [1/2]
iterator_range<use_iterator> llvm::Value::uses () inline
Definition at line 375 of file Value.h.
References assertModuleIsMaterialized(), and materialized_uses().
Referenced by addIntrinsicToSummary(), llvm::IVUsers::AddUsersImpl(), AllUsesDominatedByBlock(), analyzeGlobalAux(), areFunctionArgsABICompatible(), canFoldIVIncExpr(), llvm::Attributor::changeValueAfterManifest(), llvm::Attributor::checkForAllCallSites(), llvm::Attributor::checkForAllUses(), llvm::createDeadArgHackingPass(), determinePointerReadAttrs(), llvm::GVNExpression::Expression::dump(), llvm::detail::PtrUseVisitorBase::enqueueUsers(), FindAllMemoryUses(), findCallsAtConstantOffset(), findDemandedEltsByAllUsers(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), findLoadCallsAtConstantOffset(), findProfitablePHIs(), findUses(), llvm::formLCSSAForInstructions(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), llvm::IRPosition::getAttrs(), GetCaseResults(), getCombineLoadStoreParts(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::GlobalsAAResult::getModRefBehavior(), getParentPad(), getRetComponentType(), getStartOrEndSlot(), llvm::Function::hasAddressTaken(), hasSameExtUse(), hasUsesOutsideLoop(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), isKnownTypeIdMember(), isPossibleIndirectCallTarget(), isPromotedResultSafe(), isSafeAndProfitableToSpeculateAroundPHI(), llvm::isSafeToMoveBefore(), isSafeToPromoteArgument(), isSafeToSpeculatePHIUsers(), IsStoredObjCPointer(), llvm::Instruction::isUsedOutsideOfBlock(), llvm::AArch64TargetLowering::isZExtFree(), llvm::PredicateInfoClasses::ValueDFS_Compare::localComesBefore(), llvm::LowerDbgDeclare(), llvm::LoopInfo::movementPreservesLCSSAForm(), NewGVN::ValueDFS::operator<(), operator<<(), llvm::PointerMayBeCaptured(), predictValueUseListOrderImpl(), llvm::ValueEnumerator::print(), promoteArguments(), PropagateConstantsIntoArguments(), PushArgMD(), replaceAllInstructionUsesWith(), replacePrepare(), llvm::ARMTargetLowering::shouldSinkOperands(), sinkInstruction(), truncateIVUse(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::sroa::AllocaSliceRewriter::visit(), and visitPHIUsersAndDepsInPostOrder().
uses() [2/2]
iterator_range<const_use_iterator> llvm::Value::uses () const inline
Definition at line 379 of file Value.h.
References assertModuleIsMaterialized(), and materialized_uses().
Friends And Related Function Documentation
ValueAsMetadata
friend class ValueAsMetadata friend
Definition at line 80 of file Value.h.
ValueHandleBase
friend class ValueHandleBase friend
Definition at line 81 of file Value.h.
Member Data Documentation
HasDescriptor
unsigned llvm::Value::HasDescriptor protected
Definition at line 122 of file Value.h.
Referenced by llvm::User::getDescriptor(), llvm::CallBase::hasDescriptor(), llvm::User::operator delete(), and llvm::User::operator new().
HasHungOffUses
unsigned llvm::Value::HasHungOffUses protected
Definition at line 121 of file Value.h.
Referenced by llvm::User::allocHungoffUses(), llvm::User::getDescriptor(), llvm::User::getOperandList(), llvm::User::growHungoffUses(), llvm::User::Op(), llvm::User::operator delete(), llvm::User::operator new(), llvm::User::setNumHungOffUseOperands(), and llvm::User::User().
HasName
unsigned llvm::Value::HasName protected
Definition at line 120 of file Value.h.
Referenced by getValueName(), hasName(), and setValueName().
IsUsedByMD
unsigned llvm::Value::IsUsedByMD protected
Definition at line 119 of file Value.h.
Referenced by llvm::ValueAsMetadata::get(), llvm::ValueAsMetadata::handleRAUW(), and isUsedByMetadata().
MaxAlignmentExponent
const unsigned llvm::Value::MaxAlignmentExponent = 29 static
The maximum alignment for instructions.
This is the greatest alignment value supported by load, store, and alloca instructions, and global values.
Definition at line 654 of file Value.h.
Referenced by getAttrFromCode().
MaximumAlignment
const unsigned llvm::Value::MaximumAlignment = 1u << MaxAlignmentExponent static
Definition at line 655 of file Value.h.
Referenced by emitSignedInt64(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), forEachUser(), llvm::getOrEnforceKnownAlignment(), getParentPad(), isContiguous(), parseOptionalLinkageAux(), llvm::GlobalObject::setAlignment(), llvm::AllocaInst::setAlignment(), llvm::LoadInst::setAlignment(), and llvm::StoreInst::setAlignment().
NumUserOperands
unsigned llvm::Value::NumUserOperands protected
Definition at line 116 of file Value.h.
Referenced by llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::User::getOperandUse(), llvm::User::Op(), llvm::User::op_end(), llvm::User::operator delete(), llvm::User::operator new(), llvm::User::setGlobalVariableNumOperands(), llvm::User::setNumHungOffUseOperands(), llvm::User::setOperand(), and llvm::User::User().
SubclassOptionalData
unsigned char llvm::Value::SubclassOptionalData protected
Hold subclass data that can be dropped.
This member is similar to SubclassData, however it is for holding information which may be used to aid optimization, but which may be cleared to zero without affecting conservative interpretation.
Definition at line 92 of file Value.h.
Referenced by llvm::SelectInst::areInvalidOperands(), llvm::BinaryConstantExpr::BinaryConstantExpr(), clearSubclassOptionalData(), llvm::Instruction::clone(), llvm::GetElementPtrConstantExpr::Create(), llvm::ConstantExprKeyType::create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), llvm::CallInst::CreateFree(), llvm::FenceInst::FenceInst(), llvm::ConstantExpr::getAsInstruction(), llvm::FPMathOperator::getFastMathFlags(), llvm::GEPOperator::getInRangeIndex(), llvm::InvokeInst::getLandingPadInst(), getRawSubclassOptionalData(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::ConstantExpr::getWithOperands(), llvm::FPMathOperator::hasAllowContract(), llvm::FPMathOperator::hasAllowReassoc(), llvm::FPMathOperator::hasAllowReciprocal(), llvm::FPMathOperator::hasApproxFunc(), llvm::FPMathOperator::hasNoInfs(), llvm::FPMathOperator::hasNoNaNs(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::FPMathOperator::hasNoSignedZeros(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), hasSameSubclassOptionalData(), llvm::ShuffleVectorInst::isConcat(), llvm::PossiblyExactOperator::isExact(), llvm::FPMathOperator::isFast(), llvm::Instruction::isIdenticalTo(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), llvm::GEPOperator::isInBounds(), and llvm::CallBase::populateBundleOperandInfos().
The documentation for this class was generated from the following files:
include/llvm/IR/Value.h
lib/IR/AsmWriter.cpp
lib/IR/Value.cpp