LLVM: llvm::MemDepResult Class Reference
llvm::MemDepResult Class Reference
A memory dependence query can return one of three different answers.
#include "llvm/Analysis/MemoryDependenceAnalysis.h"
Public Member Functions
MemDepResult ()=default
bool isClobber () const
Tests if this MemDepResult represents a query that is an instruction clobber dependency.
bool isDef () const
Tests if this MemDepResult represents a query that is an instruction definition dependency.
bool isNonLocal () const
Tests if this MemDepResult represents a query that is transparent to the start of the block, but where a non-local hasn't been done.
bool isNonFuncLocal () const
Tests if this MemDepResult represents a query that is transparent to the start of the function.
bool isUnknown () const
Tests if this MemDepResult represents a query which cannot and/or will not be computed.
Instruction * getInst () const
If this is a normal dependency, returns the instruction that is depended on.
bool operator== (const MemDepResult &M) const
bool operator!= (const MemDepResult &M) const
bool operator< (const MemDepResult &M) const
bool operator> (const MemDepResult &M) const
Static Public Member Functions
static MemDepResult getDef (Instruction *Inst)
get methods: These are static ctor methods for creating various MemDepResult kinds.
static MemDepResult getClobber (Instruction *Inst)
static MemDepResult getNonLocal ()
static MemDepResult getNonFuncLocal ()
static MemDepResult getUnknown ()
Friends
class MemoryDependenceResults
Detailed Description
A memory dependence query can return one of three different answers.
Definition at line 49 of file MemoryDependenceAnalysis.h.
Constructor & Destructor Documentation
MemDepResult()
llvm::MemDepResult::MemDepResult () default
Referenced by getClobber(), getDef(), getNonFuncLocal(), getNonLocal(), and getUnknown().
Member Function Documentation
getClobber()
static MemDepResult llvm::MemDepResult::getClobber (Instruction * Inst) inline static
Definition at line 135 of file MemoryDependenceAnalysis.h.
References assert(), and MemDepResult().
Referenced by GetLocation(), and llvm::MemoryDependenceResults::getSimplePointerDependencyFrom().
getDef()
static MemDepResult llvm::MemDepResult::getDef (Instruction * Inst) inline static
get methods: These are static ctor methods for creating various MemDepResult kinds.
Definition at line 131 of file MemoryDependenceAnalysis.h.
References assert(), and MemDepResult().
Referenced by llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), GetLocation(), and llvm::MemoryDependenceResults::getSimplePointerDependencyFrom().
getInst()
Instruction* llvm::MemDepResult::getInst () const inline
If this is a normal dependency, returns the instruction that is depended on.
Otherwise, returns null.
Definition at line 177 of file MemoryDependenceAnalysis.h.
References llvm_unreachable.
Referenced by llvm::GVN::ValueTable::add(), eliminateDeadStores(), llvm::MemoryDependenceResults::getDependency(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), handleFree(), hasUndefContents(), moveUp(), llvm::MemoryDependenceResults::removeInstruction(), and reportMayClobberedLoad().
getNonFuncLocal()
static MemDepResult llvm::MemDepResult::getNonFuncLocal () inline static
Definition at line 142 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by llvm::MemoryDependenceResults::getDependency(), GetLocation(), and llvm::MemoryDependenceResults::getSimplePointerDependencyFrom().
getNonLocal()
static MemDepResult llvm::MemDepResult::getNonLocal () inline static
Definition at line 139 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by llvm::MemoryDependenceResults::getDependency(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), GetLocation(), and llvm::MemoryDependenceResults::getSimplePointerDependencyFrom().
getUnknown()
static MemDepResult llvm::MemDepResult::getUnknown () inline static
Definition at line 145 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by llvm::MemoryDependenceResults::getDependency(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), GetLocation(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), and llvm::MemoryDependenceResults::getSimplePointerDependencyFrom().
isClobber()
bool llvm::MemDepResult::isClobber () const inline
Tests if this MemDepResult represents a query that is an instruction clobber dependency.
Definition at line 151 of file MemoryDependenceAnalysis.h.
Referenced by eliminateDeadStores(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), handleFree(), hasUndefContents(), moveUp(), patchAndReplaceAllUsesWith(), and reportMayClobberedLoad().
isDef()
bool llvm::MemDepResult::isDef () const inline
Tests if this MemDepResult represents a query that is an instruction definition dependency.
Definition at line 155 of file MemoryDependenceAnalysis.h.
Referenced by llvm::GVN::ValueTable::add(), eliminateDeadStores(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), handleFree(), hasUndefContents(), patchAndReplaceAllUsesWith(), and reportMayClobberedLoad().
isNonFuncLocal()
bool llvm::MemDepResult::isNonFuncLocal () const inline
Tests if this MemDepResult represents a query that is transparent to the start of the function.
Definition at line 165 of file MemoryDependenceAnalysis.h.
isNonLocal()
bool llvm::MemDepResult::isNonLocal () const inline
Tests if this MemDepResult represents a query that is transparent to the start of the block, but where a non-local hasn't been done.
Definition at line 159 of file MemoryDependenceAnalysis.h.
Referenced by llvm::GVN::ValueTable::add(), llvm::createMemDepPrinter(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), handleFree(), patchAndReplaceAllUsesWith(), llvm::GVN::ValueTable::phiTranslate(), and SortNonLocalDepInfoCache().
isUnknown()
bool llvm::MemDepResult::isUnknown () const inline
Tests if this MemDepResult represents a query which cannot and/or will not be computed.
Definition at line 171 of file MemoryDependenceAnalysis.h.
Referenced by llvm::MemoryDependenceResults::getPointerDependencyFrom().
operator!=()
bool llvm::MemDepResult::operator!= (const MemDepResult & M) const inline
Definition at line 192 of file MemoryDependenceAnalysis.h.
operator<()
bool llvm::MemDepResult::operator< (const MemDepResult & M) const inline
Definition at line 193 of file MemoryDependenceAnalysis.h.
operator==()
bool llvm::MemDepResult::operator== (const MemDepResult & M) const inline
Definition at line 191 of file MemoryDependenceAnalysis.h.
operator>()
bool llvm::MemDepResult::operator> (const MemDepResult & M) const inline
Definition at line 194 of file MemoryDependenceAnalysis.h.
Friends And Related Function Documentation
MemoryDependenceResults
friend class MemoryDependenceResults friend
Definition at line 197 of file MemoryDependenceAnalysis.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/MemoryDependenceAnalysis.h