LLVM: llvm::formatv_object_base Class Reference
llvm::formatv_object_base Class Reference
#include "llvm/Support/FormatVariadic.h"
Classes
struct create_adapters
Public Member Functions
formatv_object_base (StringRef Fmt, std::size_t ParamCount)
formatv_object_base (formatv_object_base const &rhs)=delete
formatv_object_base (formatv_object_base &&rhs)
void format (raw_ostream &S) const
std::string str () const
template<unsigned N>
SmallString< N > sstr () const
template<unsigned N>
operator SmallString< N > () const
operator std::string () const
Static Public Member Functions
static std::vector< ReplacementItem > parseFormatString (StringRef Fmt)
static Optional< ReplacementItem > parseReplacementItem (StringRef Spec)
Static Protected Member Functions
static bool consumeFieldLayout (StringRef &Spec, AlignStyle &Where, size_t &Align, char &Pad)
static std::pair< ReplacementItem, StringRef > splitLiteralAndReplacement (StringRef Fmt)
Protected Attributes
StringRef Fmt
std::vector< detail::format_adapter * > Adapters
std::vector< ReplacementItem > Replacements
Detailed Description
Definition at line 64 of file FormatVariadic.h.
Constructor & Destructor Documentation
formatv_object_base() [1/3]
llvm::formatv_object_base::formatv_object_base (StringRef Fmt, std::size_t ParamCount) inline
Definition at line 91 of file FormatVariadic.h.
formatv_object_base() [2/3]
llvm::formatv_object_base::formatv_object_base (formatv_object_base const & rhs) delete
formatv_object_base() [3/3]
llvm::formatv_object_base::formatv_object_base (formatv_object_base && rhs) inline
Definition at line 98 of file FormatVariadic.h.
References Adapters.
Member Function Documentation
consumeFieldLayout()
bool formatv_object_base::consumeFieldLayout (StringRef & Spec, AlignStyle & Where, size_t & Align, char & Pad) static protected
Definition at line 26 of file FormatVariadic.cpp.
References llvm::StringRef::consumeInteger(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::Failed(), llvm::Right, llvm::StringRef::size(), and translateLocChar().
Referenced by parseReplacementItem().
format()
void llvm::formatv_object_base::format (raw_ostream & S) const inline
Definition at line 105 of file FormatVariadic.h.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::Empty, llvm::FmtAlign::format(), llvm::Literal, and llvm::RISCVFenceField::W.
Referenced by llvm::raw_ostream::operator<<().
operator SmallString< N >()
template<unsigned N> llvm::formatv_object_base::operator SmallString< N > () const inline
Definition at line 143 of file FormatVariadic.h.
operator std::string()
llvm::formatv_object_base::operator std::string () const inline
Definition at line 145 of file FormatVariadic.h.
parseFormatString()
std::vector< ReplacementItem > formatv_object_base::parseFormatString (StringRef Fmt) static
Definition at line 144 of file FormatVariadic.cpp.
References llvm::Empty, llvm::StringRef::empty(), I, Replacements, splitLiteralAndReplacement(), and llvm::ReplacementItem::Type.
parseReplacementItem()
Optional< ReplacementItem > formatv_object_base::parseReplacementItem (StringRef Spec) static
Definition at line 57 of file FormatVariadic.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), consumeFieldLayout(), llvm::StringRef::consumeInteger(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::front(), llvm::Right, and llvm::StringRef::trim().
Referenced by splitLiteralAndReplacement().
splitLiteralAndReplacement()
std::pair< ReplacementItem, StringRef > formatv_object_base::splitLiteralAndReplacement (StringRef Fmt) static protected
Definition at line 92 of file FormatVariadic.cpp.
References assert(), C, llvm::StringRef::drop_front(), llvm::StringRef::find_first_of(), From, llvm::StringRef::npos, parseReplacementItem(), llvm::Right, llvm::StringRef::size(), llvm::StringRef::slice(), llvm::StringRef::substr(), and llvm::StringRef::take_while().
Referenced by parseFormatString().
sstr()
template<unsigned N> SmallString<N> llvm::formatv_object_base::sstr () const inline
Definition at line 136 of file FormatVariadic.h.
str()
std::string llvm::formatv_object_base::str () const inline
Definition at line 128 of file FormatVariadic.h.
References llvm::raw_ostream::flush().
Member Data Documentation
Adapters
std::vector<detail::format_adapter *> llvm::formatv_object_base::Adapters protected
Definition at line 81 of file FormatVariadic.h.
Referenced by formatv_object_base().
Fmt
StringRef llvm::formatv_object_base::Fmt protected
Definition at line 80 of file FormatVariadic.h.
Replacements
std::vector<ReplacementItem> llvm::formatv_object_base::Replacements protected
Definition at line 82 of file FormatVariadic.h.
Referenced by parseFormatString().
The documentation for this class was generated from the following files:
include/llvm/Support/FormatVariadic.h
lib/Support/FormatVariadic.cpp