LLVM: llvm::FunctionType Class Reference
llvm::FunctionType Class Reference
Class to represent function types.
#include "llvm/IR/DerivedTypes.h"
Public Types
using param_iterator = Type::subtype_iterator
Public Types inherited from llvm::Type
enum TypeID {
VoidTyID = 0, HalfTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, LabelTyID,
MetadataTyID, X86_MMXTyID, TokenTyID, IntegerTyID,
FunctionTyID, StructTyID, ArrayTyID, PointerTyID,
VectorTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type *const *
using subtype_reverse_iterator = std::reverse_iterator< subtype_iterator >
Public Member Functions
FunctionType (const FunctionType &)=delete
FunctionType & operator= (const FunctionType &)=delete
bool isVarArg () const
Type * getReturnType () const
param_iterator param_begin () const
param_iterator param_end () const
ArrayRef< Type * > params () const
Type * getParamType (unsigned i) const
Parameter type accessors.
unsigned getNumParams () const
Return the number of fixed parameters this function type requires.
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isFloatingPointTy () const
Return true if this is one of the six floating-point types.
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
Return true if this is X86 MMX.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type *> *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
Type * getSequentialElementType () const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
bool getVectorIsScalable () const
unsigned getVectorNumElements () const
ElementCount getVectorElementCount () const
Type * getVectorElementType () const
Type * getPointerElementType () const
Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static FunctionType * get (Type *Result, ArrayRef< Type *> Params, bool isVarArg)
This static method is the primary way of constructing a FunctionType.
static FunctionType * get (Type *Result, bool isVarArg)
Create a FunctionType taking no parameters.
static bool isValidReturnType (Type *RetTy)
Return true if the specified type is valid as a return type.
static bool isValidArgumentType (Type *ArgTy)
Return true if the specified type is valid as an argument type.
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static Type * getTokenTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy >
static Type * getScalarTy (LLVMContext &C)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Additional Inherited Members
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Static Protected Member Functions inherited from llvm::Type
static bool isSequentialType (TypeID TyID)
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Detailed Description
Class to represent function types.
Definition at line 108 of file DerivedTypes.h.
Member Typedef Documentation
param_iterator
using llvm::FunctionType::param_iterator = Type::subtype_iterator
Definition at line 131 of file DerivedTypes.h.
Constructor & Destructor Documentation
FunctionType()
llvm::FunctionType::FunctionType (const FunctionType &) delete
Member Function Documentation
classof()
static bool llvm::FunctionType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 147 of file DerivedTypes.h.
References llvm::Type::FunctionTyID, and llvm::Type::getTypeID().
get() [1/2]
FunctionType * FunctionType::get (Type * Result, ArrayRef< Type *> Params, bool isVarArg) static
This static method is the primary way of constructing a FunctionType.
Definition at line 301 of file Type.cpp.
References llvm::LLVMContextImpl::Alloc, llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::LLVMContextImpl::FunctionTypes, llvm::Type::getContext(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert_as(), llvm::LLVMContext::pImpl, and llvm::ArrayRef< T >::size().
Referenced by AddCalls(), addVariantDeclaration(), annotateAnyAllocSite(), appendToGlobalArray(), buildFrameType(), llvm::CloneFunction(), llvm::SanitizerStatReport::create(), llvm::createAMDGPUPrintfRuntimeBinding(), createCallInst(), llvm::createDeadArgHackingPass(), createDevirtTriggerFunc(), llvm::MIRParserImpl::createDummyFunction(), llvm::createDwarfEHPass(), createEmptyFunction(), llvm::createSanitizerCtorAndInitFunctions(), llvm::createX86RetpolineThunksPass(), llvm::declareSanitizerInitFunction(), doPromotion(), llvm::orc::IRSpeculationLayer::emit(), emitGetSwiftErrorValue(), EmitInlineAsm(), emitLibCall(), emitSetSwiftErrorValue(), llvm::CodeExtractor::findInputsOutputs(), llvm::SanitizerStatReport::finish(), forEachUser(), FunctionNumber(), getDefaultPersonalityFn(), llvm::AMDGPUMangledLibFunc::getFunctionType(), llvm::Module::getOrInsertFunction(), getOrInsertGlobal(), getOrInsertValueProfilingCall(), getRetComponentType(), GetRMWLibcall(), getSignature(), llvm::Intrinsic::getType(), INITIALIZE_PASS(), insertCall(), InsertSafepointPoll(), insertUseHolderAfter(), instrumentMaskedLoadOrStore(), LLVMFunctionType(), makeStatepointExplicitImpl(), needsRuntimeRegistrationOfSectionRange(), parseOptionalLinkageAux(), prepareForSplit(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), ReplaceCallWith(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), selectJumpTableArmEncoding(), shouldFixMainFunction(), shouldKeepInEntry(), TypeSizeToSizeIndex(), UpgradeIntrinsicFunction1(), llvm::AMDGPULibCalls::useNative(), and wrapConstantAsMetadata().
get() [2/2]
FunctionType * FunctionType::get (Type * Result, bool isVarArg) static
Create a FunctionType taking no parameters.
Definition at line 327 of file Type.cpp.
References llvm::None.
getNumParams()
unsigned llvm::FunctionType::getNumParams () const inline
Return the number of fixed parameters this function type requires.
This does not consider varargs.
Definition at line 144 of file DerivedTypes.h.
References llvm::Type::NumContainedTys.
Referenced by annotateAnyAllocSite(), CC_Lanai32_VarArg(), llvm::FunctionComparator::cmpTypes(), computeAddrSpace(), llvm::CallInst::CreateFree(), createWrapper(), emitSignedInt64(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), getAllocationDataForFunction(), getAttrKindEncoding(), llvm::TargetTransformInfoImplBase::getCallCost(), llvm::InvokeInst::getLandingPadInst(), llvm::Mangler::getNameWithPrefix(), getParameterABIAttributes(), getRetComponentType(), getSuccPad(), INITIALIZE_PASS(), llvm::InlineFunction(), isFuncOrArgAttr(), llvm::isLegalToPromote(), llvm::isLibFreeFunction(), llvm::HexagonTargetLowering::LowerCall(), llvm::CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerFormalArguments(), maybePrintComdat(), llvm::CallBase::populateBundleOperandInfos(), PrintLLVMName(), llvm::promoteCall(), PushArgMD(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::FastISel::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setCallee(), shouldFixMainFunction(), UpgradeX86IntrinsicFunction(), UpgradeX86IntrinsicsWith8BitMask(), llvm::InlineAsm::Verify(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and wrapConstantAsMetadata().
getParamType()
Type* llvm::FunctionType::getParamType (unsigned i) const inline
Parameter type accessors.
Definition at line 140 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by annotateAnyAllocSite(), annotateNonNullAndDereferenceable(), canCreateThunkFor(), CC_RISCV(), llvm::FunctionComparator::cmpTypes(), llvm::CallInst::CreateFree(), llvm::IRBuilder< TargetFolder >::CreateLaunderInvariantGroup(), llvm::IRBuilder< TargetFolder >::CreateStripInvariantGroup(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), getAllocationDataForFunction(), getAttrKindEncoding(), llvm::InvokeInst::getLandingPadInst(), getParameterABIAttributes(), getSignature(), getSuccPad(), INITIALIZE_PASS(), isFuncOrArgAttr(), llvm::isLibFreeFunction(), lookupFunction(), llvm::SITargetLowering::LowerFormalArguments(), maybePrintComdat(), needsFPStubFromParams(), llvm::CallBase::populateBundleOperandInfos(), PushArgMD(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), UpgradePTESTIntrinsic(), UpgradeX86IntrinsicFunction(), UpgradeX86IntrinsicsWith8BitMask(), and whichFPParamVariantNeeded().
getReturnType()
Type* llvm::FunctionType::getReturnType () const inline
Definition at line 129 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by AddCalls(), annotateAnyAllocSite(), CC_RISCV(), checkWFRetconPrototype(), llvm::CallInst::classof(), llvm::InvokeInst::classof(), llvm::CallBrInst::classof(), llvm::CloneFunction(), llvm::FunctionComparator::cmpTypes(), llvm::computeSignatureVTs(), llvm::createDeadArgHackingPass(), createWrapper(), doPromotion(), getAllocationDataForFunction(), getAttrKindEncoding(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), getParameterABIAttributes(), getRetComponentType(), getSignature(), INITIALIZE_PASS(), isFuncOrArgAttr(), llvm::isLibFreeFunction(), lookupFunction(), llvm::Intrinsic::matchIntrinsicSignature(), maybePrintCallAddrSpace(), llvm::CallBase::mutateFunctionType(), needsFPReturnHelper(), llvm::CallBase::populateBundleOperandInfos(), PrintLLVMName(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::CallBase::setCalledFunction(), shouldFixMainFunction(), UpgradeIntrinsicFunction1(), and llvm::InlineAsm::Verify().
isValidArgumentType()
bool FunctionType::isValidArgumentType (Type * ArgTy) static
Return true if the specified type is valid as an argument type.
Definition at line 336 of file Type.cpp.
References llvm::Type::isFirstClassType().
Referenced by parseOptionalLinkageAux().
isValidReturnType()
bool FunctionType::isValidReturnType (Type * RetTy) static
Return true if the specified type is valid as a return type.
Definition at line 331 of file Type.cpp.
References llvm::Type::isFunctionTy(), llvm::Type::isLabelTy(), and llvm::Type::isMetadataTy().
Referenced by computeAddrSpace(), FunctionNumber(), and parseOptionalLinkageAux().
isVarArg()
bool llvm::FunctionType::isVarArg () const inline
Definition at line 128 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by AddCalls(), addVariantDeclaration(), annotateAnyAllocSite(), llvm::Interpreter::callFunction(), llvm::CloneFunction(), llvm::FunctionComparator::cmpTypes(), llvm::computeSignatureVTs(), llvm::createDeadArgHackingPass(), llvm::CallInst::CreateFree(), createWrapper(), doPromotion(), eliminateTailRecursion(), emitSignedInt64(), llvm::Evaluator::EvaluateBlock(), getAttrKindEncoding(), getComparePred(), llvm::InvokeInst::getLandingPadInst(), llvm::Mangler::getNameWithPrefix(), getParameterABIAttributes(), getParentPad(), getRetComponentType(), getSignature(), INITIALIZE_PASS(), llvm::CodeExtractor::isEligible(), llvm::CallLowering::lowerCall(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), maybePrintCallAddrSpace(), maybePrintComdat(), llvm::CallBase::populateBundleOperandInfos(), PrintLLVMName(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::Intrinsic::remangleIntrinsicFunction(), llvm::DeadArgumentEliminationPass::run(), llvm::MCJIT::runFunction(), llvm::orc::OrcMCJITReplacement::runFunction(), llvm::FastISel::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setCallee(), shouldFixMainFunction(), llvm::InlineAsm::Verify(), and wrapConstantAsMetadata().
operator=()
FunctionType& llvm::FunctionType::operator= (const FunctionType &) delete
param_begin()
param_iterator llvm::FunctionType::param_begin () const inline
Definition at line 133 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by annotateAnyAllocSite(), llvm::createDeadArgHackingPass(), createWrapper(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), llvm::AMDGPULibFunc::getOrInsertFunction(), getSignature(), INITIALIZE_PASS(), LLVMGetParamTypes(), LowerADJUST_TRAMPOLINE(), and PrintLLVMName().
param_end()
param_iterator llvm::FunctionType::param_end () const inline
Definition at line 134 of file DerivedTypes.h.
References llvm::Type::ContainedTys, and llvm::Type::NumContainedTys.
Referenced by annotateAnyAllocSite(), llvm::createDeadArgHackingPass(), createWrapper(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), llvm::AMDGPULibFunc::getOrInsertFunction(), getSignature(), INITIALIZE_PASS(), LLVMGetParamTypes(), LowerADJUST_TRAMPOLINE(), and PrintLLVMName().
params()
ArrayRef<Type *> llvm::FunctionType::params () const inline
Definition at line 135 of file DerivedTypes.h.
References llvm::makeArrayRef().
Referenced by AddCalls(), llvm::computeSignatureVTs(), getSignature(), isCallPromotable(), lookupFunction(), llvm::Intrinsic::matchIntrinsicSignature(), UpgradeIntrinsicFunction1(), and wrapConstantAsMetadata().
The documentation for this class was generated from the following files:
include/llvm/IR/DerivedTypes.h
lib/IR/Type.cpp