LLVM: llvm::MachineLoopInfo Class Reference
llvm::MachineLoopInfo Class Reference
#include "llvm/CodeGen/MachineLoopInfo.h"
Public Types
using iterator = LoopInfoBase< MachineBasicBlock, MachineLoop >::iterator
The iterator interface to the top-level loops in the current function.
Public Member Functions
MachineLoopInfo ()
MachineLoopInfo (MachineDominatorTree &MDT)
MachineLoopInfo (const MachineLoopInfo &)=delete
MachineLoopInfo & operator= (const MachineLoopInfo &)=delete
LoopInfoBase< MachineBasicBlock, MachineLoop > & getBase ()
MachineBasicBlock * findLoopPreheader (MachineLoop *L, bool SpeculativePreheader=false) const
Find the block that either is the loop preheader, or could speculatively be used as the preheader.
iterator begin () const
iterator end () const
bool empty () const
MachineLoop * getLoopFor (const MachineBasicBlock *BB) const
Return the innermost loop that BB lives in.
const MachineLoop * operator[] (const MachineBasicBlock *BB) const
Same as getLoopFor.
unsigned getLoopDepth (const MachineBasicBlock *BB) const
Return the loop nesting level of the specified block.
bool isLoopHeader (const MachineBasicBlock *BB) const
True if the block is a loop header node.
bool runOnMachineFunction (MachineFunction &F) override
Calculate the natural loop information.
void calculate (MachineDominatorTree &MDT)
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
MachineLoop * removeLoop (iterator I)
This removes the specified top-level loop from this loop info object.
void changeLoopFor (MachineBasicBlock *BB, MachineLoop *L)
Change the top-level loop that contains BB to the specified loop.
void changeTopLevelLoop (MachineLoop *OldLoop, MachineLoop *NewLoop)
Replace the specified loop in the top-level loops list with the indicated loop.
void addTopLevelLoop (MachineLoop *New)
This adds the specified loop to the collection of top-level loops.
void removeBlock (MachineBasicBlock *BB)
This method completely removes BB from all data structures, including all of the Loop objects it is nested in and our mapping from MachineBasicBlocks to loops.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Friends
class LoopBase< MachineBasicBlock, MachineLoop >
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 84 of file MachineLoopInfo.h.
Member Typedef Documentation
iterator
using llvm::MachineLoopInfo::iterator = LoopInfoBase<MachineBasicBlock, MachineLoop>::iterator
The iterator interface to the top-level loops in the current function.
Definition at line 111 of file MachineLoopInfo.h.
Constructor & Destructor Documentation
MachineLoopInfo() [1/3]
MachineLoopInfo::MachineLoopInfo ()
Definition at line 31 of file MachineLoopInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, and llvm::initializeMachineLoopInfoPass().
MachineLoopInfo() [2/3]
llvm::MachineLoopInfo::MachineLoopInfo (MachineDominatorTree & MDT) inline explicit
Definition at line 93 of file MachineLoopInfo.h.
MachineLoopInfo() [3/3]
llvm::MachineLoopInfo::MachineLoopInfo (const MachineLoopInfo &) delete
Member Function Documentation
addTopLevelLoop()
void llvm::MachineLoopInfo::addTopLevelLoop (MachineLoop * New) inline
This adds the specified loop to the collection of top-level loops.
Definition at line 163 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop().
begin()
iterator llvm::MachineLoopInfo::begin () const inline
Definition at line 112 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::begin().
calculate()
void MachineLoopInfo::calculate (MachineDominatorTree & MDT)
Definition at line 47 of file MachineLoopInfo.cpp.
References llvm::MachineDominatorTree::getBase(), and releaseMemory().
Referenced by runOnMachineFunction().
changeLoopFor()
void llvm::MachineLoopInfo::changeLoopFor (MachineBasicBlock * BB, MachineLoop * L) inline
Change the top-level loop that contains BB to the specified loop.
This should be used by transformations that restructure the loop hierarchy tree.
Definition at line 152 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::changeLoopFor().
changeTopLevelLoop()
void llvm::MachineLoopInfo::changeTopLevelLoop (MachineLoop * OldLoop, MachineLoop * NewLoop) inline
Replace the specified loop in the top-level loops list with the indicated loop.
Definition at line 158 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::changeTopLevelLoop().
empty()
bool llvm::MachineLoopInfo::empty () const inline
Definition at line 114 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::empty().
end()
iterator llvm::MachineLoopInfo::end () const inline
Definition at line 113 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::end().
findLoopPreheader()
MachineBasicBlock * MachineLoopInfo::findLoopPreheader (MachineLoop * L, bool SpeculativePreheader = false) const
Find the block that either is the loop preheader, or could speculatively be used as the preheader.
This is e.g. useful to place loop setup code. Code that cannot be speculated should not be placed here. SpeculativePreheader is controlling whether it also tries to find the speculative preheader if the regular preheader is not present.
Definition at line 115 of file MachineLoopInfo.cpp.
References llvm::LoopBase< BlockT, LoopT >::getHeader(), getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::MachineBasicBlock::hasAddressTaken(), P, llvm::MachineBasicBlock::pred_size(), llvm::MachineBasicBlock::predecessors(), and llvm::MachineBasicBlock::successors().
Referenced by llvm::createHexagonHardwareLoops(), and IsSafeToMove().
getAnalysisUsage()
void MachineLoopInfo::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 52 of file MachineLoopInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getBase()
LoopInfoBase<MachineBasicBlock, MachineLoop>& llvm::MachineLoopInfo::getBase () inline
Definition at line 100 of file MachineLoopInfo.h.
Referenced by ComputeCommonTailLength().
getLoopDepth()
unsigned llvm::MachineLoopInfo::getLoopDepth (const MachineBasicBlock * BB) const inline
Return the loop nesting level of the specified block.
Definition at line 128 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopDepth().
Referenced by isTerminalReg().
getLoopFor()
MachineLoop* llvm::MachineLoopInfo::getLoopFor (const MachineBasicBlock * BB) const inline
Return the innermost loop that BB lives in.
If a basic block is in no loop (for example the entry node), null is returned.
Definition at line 118 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor().
Referenced by allPhiOperandsUndefined(), ComputeCommonTailLength(), emitBasicBlockLoopComments(), llvm::SystemZPostRASchedStrategy::enterMBB(), findLoopPreheader(), getLayoutSuccessorProbThreshold(), llvm::MachineTraceMetrics::Ensemble::getLoopFor(), mergeOperations(), sortBlocks(), and VisitGlobalVariableForEmission().
isLoopHeader()
bool llvm::MachineLoopInfo::isLoopHeader (const MachineBasicBlock * BB) const inline
True if the block is a loop header node.
Definition at line 133 of file MachineLoopInfo.h.
References F(), and llvm::LoopInfoBase< BlockT, LoopT >::isLoopHeader().
Referenced by performSink(), and VisitGlobalVariableForEmission().
operator=()
MachineLoopInfo& llvm::MachineLoopInfo::operator= (const MachineLoopInfo &) delete
operator[]()
const MachineLoop* llvm::MachineLoopInfo::operator[] (const MachineBasicBlock * BB) const inline
Same as getLoopFor.
Definition at line 123 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor().
releaseMemory()
void llvm::MachineLoopInfo::releaseMemory () inline override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 141 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::releaseMemory().
Referenced by calculate().
removeBlock()
void llvm::MachineLoopInfo::removeBlock (MachineBasicBlock * BB) inline
This method completely removes BB from all data structures, including all of the Loop objects it is nested in and our mapping from MachineBasicBlocks to loops.
Definition at line 170 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::removeBlock().
Referenced by llvm::BranchFolder::BranchFolder().
removeLoop()
MachineLoop* llvm::MachineLoopInfo::removeLoop (iterator I) inline
This removes the specified top-level loop from this loop info object.
The loop is not deleted, as it will presumably be inserted into another loop.
Definition at line 147 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::removeLoop().
runOnMachineFunction()
bool MachineLoopInfo::runOnMachineFunction (MachineFunction & F) override virtual
Calculate the natural loop information.
Implements llvm::MachineFunctionPass.
Definition at line 42 of file MachineLoopInfo.cpp.
References calculate().
Friends And Related Function Documentation
LoopBase< MachineBasicBlock, MachineLoop >
friend class LoopBase< MachineBasicBlock, MachineLoop > friend
Definition at line 85 of file MachineLoopInfo.h.
Member Data Documentation
ID
char MachineLoopInfo::ID = 0 static
Definition at line 90 of file MachineLoopInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineLoopInfo.h
lib/CodeGen/MachineLoopInfo.cpp