LLVM: llvm::StringMatcher Class Reference
llvm::StringMatcher Class Reference
Given a list of strings and code to execute when they match, output a simple switch tree to classify the input string.
#include "llvm/TableGen/StringMatcher.h"
Public Types
using StringPair = std::pair< std::string, std::string >
Public Member Functions
StringMatcher (StringRef strVariableName, const std::vector< StringPair > &matches, raw_ostream &os)
void Emit (unsigned Indent=0, bool IgnoreDuplicates=false) const
Emit - Top level entry point.
Detailed Description
Given a list of strings and code to execute when they match, output a simple switch tree to classify the input string.
If a match is found, the code in Matches[i].second is executed; control must not exit this code fragment. If nothing matches, execution falls through.
Definition at line 30 of file StringMatcher.h.
Member Typedef Documentation
StringPair
using llvm::StringMatcher::StringPair = std::pair<std::string, std::string>
Definition at line 32 of file StringMatcher.h.
Constructor & Destructor Documentation
StringMatcher()
llvm::StringMatcher::StringMatcher (StringRef strVariableName, const std::vector< StringPair > & matches, raw_ostream & os) inline
Definition at line 40 of file StringMatcher.h.
References Emit().
Member Function Documentation
Emit()
void StringMatcher::Emit (unsigned Indent = 0, bool IgnoreDuplicates = false) const
Emit - Top level entry point.
Definition at line 131 of file StringMatcher.cpp.
References llvm::numbers::e, E, first, and llvm::raw_ostream::indent().
Referenced by StringMatcher().
The documentation for this class was generated from the following files:
include/llvm/TableGen/StringMatcher.h
lib/TableGen/StringMatcher.cpp