LLVM: llvm::VirtRegMap Class Reference
llvm::VirtRegMap Class Reference
#include "llvm/CodeGen/VirtRegMap.h"
Public Types
enum { NO_PHYS_REG = 0, NO_STACK_SLOT = (1L << 30)-1, MAX_STACK_SLOT = (1L << 18)-1 }
Public Member Functions
VirtRegMap ()
VirtRegMap (const VirtRegMap &)=delete
VirtRegMap & operator= (const VirtRegMap &)=delete
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
MachineFunction & getMachineFunction () const
MachineRegisterInfo & getRegInfo () const
const TargetRegisterInfo & getTargetRegInfo () const
void grow ()
bool hasPhys (Register virtReg) const
returns true if the specified virtual register is mapped to a physical register
Register getPhys (Register virtReg) const
returns the physical register mapped to the specified virtual register
void assignVirt2Phys (Register virtReg, MCPhysReg physReg)
creates a mapping for the specified virtual register to the specified physical register
void clearVirt (Register virtReg)
clears the specified virtual register's, physical register mapping
void clearAllVirt ()
clears all virtual to physical register mappings
bool hasPreferredPhys (Register VirtReg)
returns true if VirtReg is assigned to its preferred physreg.
bool hasKnownPreference (Register VirtReg)
returns true if VirtReg has a known preferred register.
void setIsSplitFromReg (Register virtReg, unsigned SReg)
records virtReg is a split live interval from SReg.
unsigned getPreSplitReg (Register virtReg) const
returns the live interval virtReg is split from.
unsigned getOriginal (unsigned VirtReg) const
getOriginal - Return the original virtual register that VirtReg descends from through splitting.
bool isAssignedReg (Register virtReg) const
returns true if the specified virtual register is not mapped to a stack slot or rematerialized.
int getStackSlot (Register virtReg) const
returns the stack slot mapped to the specified virtual register
int assignVirt2StackSlot (Register virtReg)
create a mapping for the specifed virtual register to the next available stack slot
void assignVirt2StackSlot (Register virtReg, int SS)
create a mapping for the specified virtual register to the specified stack slot
void print (raw_ostream &OS, const Module *M=nullptr) const override
print - Print out the internal state of the pass.
void dump () const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 33 of file VirtRegMap.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NO_PHYS_REG
NO_STACK_SLOT
MAX_STACK_SLOT
Definition at line 35 of file VirtRegMap.h.
Constructor & Destructor Documentation
VirtRegMap() [1/2]
llvm::VirtRegMap::VirtRegMap () inline
Definition at line 70 of file VirtRegMap.h.
References operator=(), and runOnMachineFunction().
VirtRegMap() [2/2]
llvm::VirtRegMap::VirtRegMap (const VirtRegMap &) delete
Member Function Documentation
assignVirt2Phys()
void VirtRegMap::assignVirt2Phys (Register virtReg, MCPhysReg physReg)
creates a mapping for the specified virtual register to the specified physical register
Definition at line 83 of file VirtRegMap.cpp.
References assert(), llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::MachineFunction::getFrameInfo(), getRegInfo(), llvm::TargetRegisterInfo::getSpillAlignment(), llvm::TargetRegisterInfo::getSpillSize(), llvm::Register::id(), llvm::Register::isPhysicalRegister(), llvm::Register::isVirtual(), NO_PHYS_REG, Size, and llvm::X86AS::SS.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), llvm::LiveRegMatrix::assign(), getPhys(), and isACalleeSavedRegister().
assignVirt2StackSlot() [1/2]
int VirtRegMap::assignVirt2StackSlot (Register virtReg)
create a mapping for the specifed virtual register to the next available stack slot
Definition at line 119 of file VirtRegMap.cpp.
References assert(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::Register::id(), llvm::Register::isVirtual(), and NO_STACK_SLOT.
Referenced by getStackSlot().
assignVirt2StackSlot() [2/2]
void VirtRegMap::assignVirt2StackSlot (Register virtReg, int SS)
create a mapping for the specified virtual register to the specified stack slot
Definition at line 127 of file VirtRegMap.cpp.
References assert(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::Register::id(), llvm::Register::isVirtual(), NO_STACK_SLOT, and llvm::X86AS::SS.
clearAllVirt()
void llvm::VirtRegMap::clearAllVirt () inline
clears all virtual to physical register mappings
Definition at line 121 of file VirtRegMap.h.
References llvm::IndexedMap< T, ToIndexT >::clear(), grow(), hasKnownPreference(), and hasPreferredPhys().
Referenced by isACalleeSavedRegister().
clearVirt()
void llvm::VirtRegMap::clearVirt (Register virtReg) inline
clears the specified virtual register's, physical register mapping
Definition at line 113 of file VirtRegMap.h.
References assert(), llvm::Register::id(), llvm::Register::isVirtual(), and NO_PHYS_REG.
Referenced by llvm::LiveRegMatrix::unassign().
dump()
LLVM_DUMP_METHOD void VirtRegMap::dump () const
Definition at line 159 of file VirtRegMap.cpp.
References llvm::dbgs(), getAnalysisUsage(), llvm::MachineFunctionPass::getSetProperties(), ID, llvm::MachineFunctionPass::MachineFunctionPass(), MI, MRI, llvm::MachineFunctionProperties::NoVRegs, print(), rewrite(), runOnMachineFunction(), llvm::MachineFunctionProperties::set(), TII, and TRI.
Referenced by getStackSlot().
getAnalysisUsage()
void llvm::VirtRegMap::getAnalysisUsage (AnalysisUsage & AU) const inline override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 79 of file VirtRegMap.h.
References llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by dump().
getMachineFunction()
MachineFunction& llvm::VirtRegMap::getMachineFunction () const inline
Definition at line 84 of file VirtRegMap.h.
References assert().
Referenced by llvm::AllocationOrder::AllocationOrder(), findNextInsertLocation(), llvm::RegAllocBase::init(), and llvm::SplitEditor::reset().
getOriginal()
unsigned llvm::VirtRegMap::getOriginal (unsigned VirtReg) const inline
getOriginal - Return the original virtual register that VirtReg descends from through splitting.
A register that was not created by splitting is its own original. This operation is idempotent.
Definition at line 148 of file VirtRegMap.h.
References getPreSplitReg().
Referenced by llvm::SplitEditor::dump(), llvm::SplitAnalysis::isOriginalEndpoint(), and isRematerializable().
getPhys()
Register llvm::VirtRegMap::getPhys (Register virtReg) const inline
returns the physical register mapped to the specified virtual register
Definition at line 102 of file VirtRegMap.h.
References assert(), assignVirt2Phys(), llvm::Register::id(), and llvm::Register::isVirtual().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), getRC32(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), hasPhys(), hasPreferredPhys(), llvm::LiveDebugVariables::splitRegister(), and llvm::LiveRegMatrix::unassign().
getPreSplitReg()
unsigned llvm::VirtRegMap::getPreSplitReg (Register virtReg) const inline
returns the live interval virtReg is split from.
Definition at line 140 of file VirtRegMap.h.
References llvm::Register::id().
Referenced by getOriginal().
getRegInfo()
MachineRegisterInfo& llvm::VirtRegMap::getRegInfo () const inline
Definition at line 89 of file VirtRegMap.h.
Referenced by assignVirt2Phys(), llvm::RegAllocBase::init(), and isACalleeSavedRegister().
getStackSlot()
int llvm::VirtRegMap::getStackSlot (Register virtReg) const inline
returns the stack slot mapped to the specified virtual register
Definition at line 166 of file VirtRegMap.h.
References assert(), assignVirt2StackSlot(), dump(), llvm::Register::id(), llvm::Register::isVirtual(), print(), and llvm::X86AS::SS.
Referenced by isAssignedReg(), and llvm::LiveDebugVariables::splitRegister().
getTargetRegInfo()
const TargetRegisterInfo& llvm::VirtRegMap::getTargetRegInfo () const inline
Definition at line 90 of file VirtRegMap.h.
References grow().
Referenced by llvm::AllocationOrder::AllocationOrder(), and llvm::RegAllocBase::init().
grow()
void VirtRegMap::grow ()
Definition at line 76 of file VirtRegMap.cpp.
References llvm::MachineRegisterInfo::getNumVirtRegs(), and llvm::MachineFunction::getRegInfo().
Referenced by clearAllVirt(), and getTargetRegInfo().
hasKnownPreference()
bool VirtRegMap::hasKnownPreference (Register VirtReg)
returns true if VirtReg has a known preferred register.
This returns false if VirtReg has a preference that is a virtual register that hasn't been assigned yet.
Definition at line 110 of file VirtRegMap.cpp.
References llvm::MachineRegisterInfo::getRegAllocationHint(), hasPhys(), llvm::Register::isPhysicalRegister(), and llvm::Register::isVirtualRegister().
Referenced by clearAllVirt().
hasPhys()
bool llvm::VirtRegMap::hasPhys (Register virtReg) const inline
returns true if the specified virtual register is mapped to a physical register
Definition at line 96 of file VirtRegMap.h.
References getPhys(), and NO_PHYS_REG.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), llvm::LiveRegMatrix::assign(), getRC32(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), and hasKnownPreference().
hasPreferredPhys()
bool VirtRegMap::hasPreferredPhys (Register VirtReg)
returns true if VirtReg is assigned to its preferred physreg.
Definition at line 101 of file VirtRegMap.cpp.
References getPhys(), llvm::MachineRegisterInfo::getSimpleHint(), llvm::Register::isValid(), and llvm::Register::isVirtual().
Referenced by clearAllVirt().
isAssignedReg()
bool llvm::VirtRegMap::isAssignedReg (Register virtReg) const inline
returns true if the specified virtual register is not mapped to a stack slot or rematerialized.
Definition at line 155 of file VirtRegMap.h.
References getStackSlot(), llvm::Register::id(), NO_PHYS_REG, and NO_STACK_SLOT.
Referenced by llvm::LiveDebugVariables::splitRegister().
operator=()
VirtRegMap& llvm::VirtRegMap::operator= (const VirtRegMap &) delete
Referenced by VirtRegMap().
print()
void VirtRegMap::print (raw_ostream & OS, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 137 of file VirtRegMap.cpp.
References llvm::numbers::e, llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), llvm::Register::index2VirtReg(), NO_PHYS_REG, NO_STACK_SLOT, llvm::printReg(), and Reg.
Referenced by dump(), getStackSlot(), and llvm::operator<<().
runOnMachineFunction()
bool VirtRegMap::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 62 of file VirtRegMap.cpp.
References MRI, TII, and TRI.
Referenced by dump(), and VirtRegMap().
setIsSplitFromReg()
void llvm::VirtRegMap::setIsSplitFromReg (Register virtReg, unsigned SReg) inline
records virtReg is a split live interval from SReg.
Definition at line 135 of file VirtRegMap.h.
References llvm::Register::id().
Member Data Documentation
ID
char VirtRegMap::ID = 0 static
Definition at line 68 of file VirtRegMap.h.
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/VirtRegMap.h
lib/CodeGen/VirtRegMap.cpp