LLVM: llvm::xray::CustomEventRecord Class Reference
llvm::xray::CustomEventRecord Class Reference
#include "llvm/XRay/FDRRecords.h"
Public Member Functions
CustomEventRecord ()
CustomEventRecord (uint64_t S, uint64_t T, uint16_t C, std::string D)
int32_t size () const
uint64_t tsc () const
uint16_t cpu () const
StringRef data () const
Error apply (RecordVisitor &V) override
Public Member Functions inherited from llvm::xray::MetadataRecord
MetadataRecord (RecordKind T, MetadataType M)
MetadataType metadataType () const
virtual ~MetadataRecord ()=default
Public Member Functions inherited from llvm::xray::Record
Record (const Record &)=delete
Record (Record &&)=delete
Record & operator= (const Record &)=delete
Record & operator= (Record &&)=delete
Record (RecordKind T)
RecordKind getRecordType () const
virtual ~Record ()=default
Static Public Member Functions
static bool classof (const Record *R)
Static Public Member Functions inherited from llvm::xray::MetadataRecord
static bool classof (const Record *R)
Static Public Member Functions inherited from llvm::xray::Record
static StringRef kindToString (RecordKind K)
Friends
class RecordInitializer
Additional Inherited Members
Public Types inherited from llvm::xray::MetadataRecord
enum MetadataType : unsigned {
MetadataType::Unknown, MetadataType::BufferExtents, MetadataType::WallClockTime, MetadataType::NewCPUId,
MetadataType::TSCWrap, MetadataType::CustomEvent, MetadataType::CallArg, MetadataType::PIDEntry,
MetadataType::NewBuffer, MetadataType::EndOfBuffer, MetadataType::TypedEvent
}
Public Types inherited from llvm::xray::Record
enum RecordKind {
RecordKind::RK_Metadata, RecordKind::RK_Metadata_BufferExtents, RecordKind::RK_Metadata_WallClockTime, RecordKind::RK_Metadata_NewCPUId,
RecordKind::RK_Metadata_TSCWrap, RecordKind::RK_Metadata_CustomEvent, RecordKind::RK_Metadata_CustomEventV5, RecordKind::RK_Metadata_CallArg,
RecordKind::RK_Metadata_PIDEntry, RecordKind::RK_Metadata_NewBuffer, RecordKind::RK_Metadata_EndOfBuffer, RecordKind::RK_Metadata_TypedEvent,
RecordKind::RK_Metadata_LastMetadata, RecordKind::RK_Function
}
Static Protected Attributes inherited from llvm::xray::MetadataRecord
static constexpr int kMetadataBodySize = 15
Detailed Description
Definition at line 206 of file FDRRecords.h.
Constructor & Destructor Documentation
CustomEventRecord() [1/2]
llvm::xray::CustomEventRecord::CustomEventRecord () inline
Definition at line 214 of file FDRRecords.h.
CustomEventRecord() [2/2]
llvm::xray::CustomEventRecord::CustomEventRecord (uint64_t S, uint64_t T, uint16_t C, std::string D) inline explicit
Definition at line 218 of file FDRRecords.h.
Member Function Documentation
apply()
Error llvm::xray::CustomEventRecord::apply (RecordVisitor & V) override virtual
Implements llvm::xray::Record.
Definition at line 22 of file FDRRecords.cpp.
References llvm::xray::RecordVisitor::visit().
classof()
static bool llvm::xray::CustomEventRecord::classof (const Record * R) inline static
Definition at line 230 of file FDRRecords.h.
References llvm::xray::Record::getRecordType(), and llvm::xray::Record::RK_Metadata_CustomEvent.
cpu()
uint16_t llvm::xray::CustomEventRecord::cpu () const inline
Definition at line 225 of file FDRRecords.h.
Referenced by llvm::xray::RecordPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), and llvm::xray::TraceExpander::visit().
data()
StringRef llvm::xray::CustomEventRecord::data () const inline
Definition at line 226 of file FDRRecords.h.
References llvm::xray::Record::apply(), and llvm::Data.
Referenced by llvm::xray::RecordPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), and llvm::xray::TraceExpander::visit().
size()
int32_t llvm::xray::CustomEventRecord::size () const inline
Definition at line 223 of file FDRRecords.h.
References Size.
Referenced by llvm::xray::RecordPrinter::visit(), and llvm::xray::FDRTraceWriter::visit().
tsc()
uint64_t llvm::xray::CustomEventRecord::tsc () const inline
Definition at line 224 of file FDRRecords.h.
Referenced by llvm::xray::RecordPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), and llvm::xray::TraceExpander::visit().
Friends And Related Function Documentation
RecordInitializer
friend class RecordInitializer friend
Definition at line 211 of file FDRRecords.h.
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecords.h
lib/XRay/FDRRecords.cpp