LLVM: llvm::object::Decompressor Class Reference
llvm::object::Decompressor Class Reference
Decompressor helps to handle decompression of compressed sections.
#include "llvm/Object/Decompressor.h"
Public Member Functions
template<class T >
Error resizeAndDecompress (T &Out)
Resize the buffer and uncompress section data into it.
Error decompress (MutableArrayRef< char > Buffer)
Uncompress section data to raw buffer provided.
uint64_t getDecompressedSize ()
Return memory buffer size required for decompression.
Static Public Member Functions
static Expected< Decompressor > create (StringRef Name, StringRef Data, bool IsLE, bool Is64Bit)
Create decompressor object.
static bool isCompressed (const object::SectionRef &Section)
Return true if section is compressed, including gnu-styled case.
static bool isCompressedELFSection (uint64_t Flags, StringRef Name)
Return true if section is a ELF compressed one.
static bool isGnuStyle (StringRef Name)
Return true if section name matches gnu style compressed one.
Detailed Description
Decompressor helps to handle decompression of compressed sections.
Definition at line 20 of file Decompressor.h.
Member Function Documentation
create()
Expected< Decompressor > Decompressor::create (StringRef Name, StringRef Data, bool IsLE, bool Is64Bit) static
Create decompressor object.
Parameters
Name Section name.
Data Section content.
IsLE Flag determines if Data is in little endian form.
Is64Bit Flag determines if object is 64 bit.
Definition at line 20 of file Decompressor.cpp.
References llvm::createError(), D, and llvm::zlib::isAvailable().
decompress()
Error Decompressor::decompress (MutableArrayRef< char > Buffer)
Uncompress section data to raw buffer provided.
Parameters
Buffer Destination buffer.
Definition at line 95 of file Decompressor.cpp.
References llvm::MutableArrayRef< T >::data(), Size, llvm::ArrayRef< T >::size(), and llvm::zlib::uncompress().
Referenced by resizeAndDecompress().
getDecompressedSize()
uint64_t llvm::object::Decompressor::getDecompressedSize () inline
Return memory buffer size required for decompression.
Definition at line 42 of file Decompressor.h.
References isCompressed(), isCompressedELFSection(), isGnuStyle(), and llvm::ARMBuildAttrs::Section.
isCompressed()
bool Decompressor::isCompressed (const object::SectionRef & Section) static
Return true if section is compressed, including gnu-styled case.
Definition at line 79 of file Decompressor.cpp.
References llvm::consumeError(), llvm::object::SectionRef::getName(), llvm::object::SectionRef::isCompressed(), and llvm::Expected< T >::takeError().
Referenced by getDecompressedSize().
isCompressedELFSection()
bool Decompressor::isCompressedELFSection (uint64_t Flags, StringRef Name) static
Return true if section is a ELF compressed one.
Definition at line 91 of file Decompressor.cpp.
References llvm::ELF::SHF_COMPRESSED.
Referenced by getDecompressedSize().
isGnuStyle()
bool Decompressor::isGnuStyle (StringRef Name) static
Return true if section name matches gnu style compressed one.
Definition at line 75 of file Decompressor.cpp.
References llvm::StringRef::startswith().
Referenced by getDecompressedSize().
resizeAndDecompress()
template<class T > Error llvm::object::Decompressor::resizeAndDecompress (T & Out) inline
Resize the buffer and uncompress section data into it.
Parameters
Out Destination buffer.
Definition at line 32 of file Decompressor.h.
References decompress().
The documentation for this class was generated from the following files:
include/llvm/Object/Decompressor.h
lib/Object/Decompressor.cpp