LLVM: llvm::TargetSchedModel Class Reference
llvm::TargetSchedModel Class Reference
Provide an instruction scheduling machine model to CodeGen passes.
#include "llvm/CodeGen/TargetSchedule.h"
Public Types
using ProcResIter = const MCWriteProcResEntry *
Public Member Functions
TargetSchedModel ()
void init (const TargetSubtargetInfo *TSInfo)
Initialize the machine model for instruction scheduling.
const MCSchedClassDesc * resolveSchedClass (const MachineInstr *MI) const
Return the MCSchedClassDesc for this instruction.
const TargetSubtargetInfo * getSubtargetInfo () const
TargetSubtargetInfo getter.
const TargetInstrInfo * getInstrInfo () const
TargetInstrInfo getter.
bool hasInstrSchedModel () const
Return true if this machine model includes an instruction-level scheduling model.
const MCSchedModel * getMCSchedModel () const
bool hasInstrItineraries () const
Return true if this machine model includes cycle-to-cycle itinerary data.
const InstrItineraryData * getInstrItineraries () const
bool hasInstrSchedModelOrItineraries () const
Return true if this machine model includes an instruction-level scheduling model or cycle-to-cycle itinerary data.
unsigned getProcessorID () const
Identify the processor corresponding to the current subtarget.
unsigned getIssueWidth () const
Maximum number of micro-ops that may be scheduled per cycle.
bool mustBeginGroup (const MachineInstr *MI, const MCSchedClassDesc *SC=nullptr) const
Return true if new group must begin.
bool mustEndGroup (const MachineInstr *MI, const MCSchedClassDesc *SC=nullptr) const
Return true if current group must end.
unsigned getNumMicroOps (const MachineInstr *MI, const MCSchedClassDesc *SC=nullptr) const
Return the number of issue slots required for this MI.
unsigned getNumProcResourceKinds () const
Get the number of kinds of resources for this target.
const MCProcResourceDesc * getProcResource (unsigned PIdx) const
Get a processor resource by ID for convenience.
const char * getResourceName (unsigned PIdx) const
ProcResIter getWriteProcResBegin (const MCSchedClassDesc *SC) const
ProcResIter getWriteProcResEnd (const MCSchedClassDesc *SC) const
unsigned getResourceFactor (unsigned ResIdx) const
Multiply the number of units consumed for a resource by this factor to normalize it relative to other resources.
unsigned getMicroOpFactor () const
Multiply number of micro-ops by this factor to normalize it relative to other resources.
unsigned getLatencyFactor () const
Multiply cycle count by this factor to normalize it relative to other resources.
unsigned getMicroOpBufferSize () const
Number of micro-ops that may be buffered for OOO execution.
int getResourceBufferSize (unsigned PIdx) const
Number of resource units that may be buffered for OOO execution.
unsigned computeOperandLatency (const MachineInstr *DefMI, unsigned DefOperIdx, const MachineInstr *UseMI, unsigned UseOperIdx) const
Compute operand latency based on the available machine model.
unsigned computeInstrLatency (const MachineInstr *MI, bool UseDefaultDefLatency=true) const
Compute the instruction latency based on the available machine model.
unsigned computeInstrLatency (const MCInst &Inst) const
unsigned computeInstrLatency (unsigned Opcode) const
unsigned computeOutputLatency (const MachineInstr *DefMI, unsigned DefOperIdx, const MachineInstr *DepMI) const
Output dependency latency of a pair of defs of the same register.
double computeReciprocalThroughput (const MachineInstr *MI) const
Compute the reciprocal throughput of the given instruction.
double computeReciprocalThroughput (const MCInst &MI) const
double computeReciprocalThroughput (unsigned Opcode) const
Detailed Description
Provide an instruction scheduling machine model to CodeGen passes.
Definition at line 31 of file TargetSchedule.h.
Member Typedef Documentation
ProcResIter
using llvm::TargetSchedModel::ProcResIter = const MCWriteProcResEntry *
Definition at line 130 of file TargetSchedule.h.
Constructor & Destructor Documentation
TargetSchedModel()
llvm::TargetSchedModel::TargetSchedModel () inline
Definition at line 50 of file TargetSchedule.h.
References init(), MI, and resolveSchedClass().
Member Function Documentation
computeInstrLatency() [1/3]
unsigned TargetSchedModel::computeInstrLatency (const MachineInstr * MI, bool UseDefaultDefLatency = true) const
Compute the instruction latency based on the available machine model.
Compute and return the expected latency of this instruction independent of a particular use. computeOperandLatency is the preferred API, but this is occasionally useful to help estimate instruction cost.
If UseDefaultDefLatency is false and no new machine sched model is present this method falls back to TII->getInstrLatency with an empty instruction itinerary (this is so we preserve the previous behavior of the if converter after moving it to TargetSchedModel).
Definition at line 273 of file TargetSchedule.cpp.
References computeOutputLatency(), llvm::TargetInstrInfo::defaultDefLatency(), llvm::TargetInstrInfo::getInstrLatency(), hasInstrItineraries(), hasInstrSchedModel(), llvm::MachineInstr::isBundle(), llvm::MCSchedClassDesc::isValid(), and resolveSchedClass().
computeInstrLatency() [2/3]
unsigned TargetSchedModel::computeInstrLatency (const MCInst & Inst) const
Definition at line 266 of file TargetSchedule.cpp.
References capLatency(), llvm::MCSchedModel::computeInstrLatency(), llvm::MCInst::getOpcode(), and hasInstrSchedModel().
computeInstrLatency() [3/3]
unsigned TargetSchedModel::computeInstrLatency (unsigned Opcode) const
Definition at line 260 of file TargetSchedule.cpp.
References assert(), capLatency(), llvm::MCSchedModel::computeInstrLatency(), llvm::MCInstrInfo::get(), llvm::MCInstrDesc::getSchedClass(), and hasInstrSchedModel().
computeOperandLatency()
unsigned TargetSchedModel::computeOperandLatency (const MachineInstr * DefMI, unsigned DefOperIdx, const MachineInstr * UseMI, unsigned UseOperIdx) const
Compute operand latency based on the available machine model.
Compute and return the latency of the given data dependent def and use when the operand indices are already known. UseMI may be NULL for an unknown user.
Definition at line 184 of file TargetSchedule.cpp.
References capLatency(), llvm::MCSchedModel::computeInstrLatency(), llvm::MCWriteLatencyEntry::Cycles, llvm::TargetInstrInfo::defaultDefLatency(), llvm::errs(), findDefIdx(), findUseIdx(), llvm::MachineInstr::getDesc(), llvm::TargetInstrInfo::getInstrLatency(), llvm::MachineInstr::getOperand(), llvm::InstrItineraryData::getOperandCycle(), llvm::TargetInstrInfo::getOperandLatency(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::MCInstrDesc::getSchedClass(), llvm::MCSubtargetInfo::getWriteLatencyEntry(), hasInstrItineraries(), hasInstrSchedModel(), llvm::MCSchedModel::isComplete(), llvm::MachineOperand::isImplicit(), llvm::MCOperandInfo::isOptionalDef(), llvm::MachineInstr::isTransient(), llvm::MCSchedClassDesc::isValid(), llvm::Latency, llvm_unreachable, llvm::max(), llvm::MCSchedClassDesc::NumReadAdvanceEntries, llvm::MCInstrDesc::OpInfo, resolveSchedClass(), and llvm::MCWriteLatencyEntry::WriteResourceID.
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), getResourceBufferSize(), pushDepHeight(), llvm::MachineTraceMetrics::Ensemble::updateDepth(), and updatePhysDepsUpwards().
computeOutputLatency()
unsigned TargetSchedModel::computeOutputLatency (const MachineInstr * DefMI, unsigned DefOperIdx, const MachineInstr * DepMI) const
Output dependency latency of a pair of defs of the same register.
This is typically one cycle.
Definition at line 290 of file TargetSchedule.cpp.
References llvm::MCProcResourceDesc::BufferSize, llvm::MachineInstr::getMF(), llvm::MachineInstr::getOperand(), llvm::MCSchedModel::getProcResource(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MCSubtargetInfo::getWriteProcResBegin(), llvm::MCSubtargetInfo::getWriteProcResEnd(), hasInstrSchedModel(), llvm::MCSchedModel::isOutOfOrder(), llvm::TargetInstrInfo::isPredicated(), llvm::MCSchedClassDesc::isValid(), llvm::MachineInstr::readsRegister(), Reg, resolveSchedClass(), and TRI.
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDeps(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), computeInstrLatency(), and getResourceBufferSize().
computeReciprocalThroughput() [1/3]
double TargetSchedModel::computeReciprocalThroughput (const MachineInstr * MI) const
Compute the reciprocal throughput of the given instruction.
Definition at line 325 of file TargetSchedule.cpp.
References llvm::MachineInstr::getDesc(), getInstrItineraries(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::MCInstrDesc::getSchedClass(), hasInstrItineraries(), hasInstrSchedModel(), and resolveSchedClass().
Referenced by computeReciprocalThroughput(), and getResourceBufferSize().
computeReciprocalThroughput() [2/3]
double TargetSchedModel::computeReciprocalThroughput (const MCInst & MI) const
Definition at line 354 of file TargetSchedule.cpp.
References computeReciprocalThroughput(), llvm::MCInst::getOpcode(), llvm::MCSchedModel::getReciprocalThroughput(), and hasInstrSchedModel().
computeReciprocalThroughput() [3/3]
double TargetSchedModel::computeReciprocalThroughput (unsigned Opcode) const
Definition at line 339 of file TargetSchedule.cpp.
References llvm::MCInstrInfo::get(), getInstrItineraries(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::MCInstrDesc::getSchedClass(), llvm::MCSchedModel::getSchedClassDesc(), hasInstrItineraries(), hasInstrSchedModel(), llvm::MCSchedClassDesc::isValid(), and llvm::MCSchedClassDesc::isVariant().
getInstrInfo()
const TargetInstrInfo* llvm::TargetSchedModel::getInstrInfo () const inline
TargetInstrInfo getter.
Definition at line 66 of file TargetSchedule.h.
References hasInstrSchedModel().
getInstrItineraries()
const InstrItineraryData* llvm::TargetSchedModel::getInstrItineraries () const inline
Definition at line 83 of file TargetSchedule.h.
References hasInstrItineraries().
Referenced by computeReciprocalThroughput(), and llvm::TargetInstrInfo::hasLowDefLatency().
getIssueWidth()
unsigned llvm::TargetSchedModel::getIssueWidth () const inline
Maximum number of micro-ops that may be scheduled per cycle.
Definition at line 99 of file TargetSchedule.h.
References getNumMicroOps(), llvm::MCSchedModel::IssueWidth, mustBeginGroup(), mustEndGroup(), and llvm::PPCISD::SC.
Referenced by llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::VLIWResourceModel::reserveResources(), and llvm::VLIWResourceModel::VLIWResourceModel().
getLatencyFactor()
unsigned llvm::TargetSchedModel::getLatencyFactor () const inline
Multiply cycle count by this factor to normalize it relative to other resources.
This is the number of resource units per cycle.
Definition at line 156 of file TargetSchedule.h.
Referenced by llvm::SchedBoundary::getExecutedCount().
getMCSchedModel()
const MCSchedModel* llvm::TargetSchedModel::getMCSchedModel () const inline
Definition at line 75 of file TargetSchedule.h.
References hasInstrItineraries().
getMicroOpBufferSize()
unsigned llvm::TargetSchedModel::getMicroOpBufferSize () const inline
Number of micro-ops that may be buffered for OOO execution.
Definition at line 161 of file TargetSchedule.h.
References llvm::MCSchedModel::MicroOpBufferSize.
getMicroOpFactor()
unsigned llvm::TargetSchedModel::getMicroOpFactor () const inline
Multiply number of micro-ops by this factor to normalize it relative to other resources.
Definition at line 150 of file TargetSchedule.h.
Referenced by llvm::SchedBoundary::getCriticalCount(), and llvm::SchedRemainder::init().
getNumMicroOps()
unsigned TargetSchedModel::getNumMicroOps (const MachineInstr * MI, const MCSchedClassDesc * SC = nullptr) const
Return the number of issue slots required for this MI.
Definition at line 107 of file TargetSchedule.cpp.
References llvm::MachineInstr::getDesc(), llvm::InstrItineraryData::getNumMicroOps(), llvm::TargetInstrInfo::getNumMicroOps(), llvm::MCInstrDesc::getSchedClass(), hasInstrItineraries(), hasInstrSchedModel(), llvm::MachineInstr::isTransient(), llvm::MCSchedClassDesc::isValid(), llvm::MCSchedClassDesc::NumMicroOps, and resolveSchedClass().
Referenced by getIssueWidth(), llvm::SchedRemainder::init(), and llvm::ConvergingVLIWScheduler::releaseBottomNode().
getNumProcResourceKinds()
unsigned llvm::TargetSchedModel::getNumProcResourceKinds () const inline
Get the number of kinds of resources for this target.
Definition at line 113 of file TargetSchedule.h.
References llvm::MCSchedModel::getNumProcResourceKinds().
Referenced by llvm::SystemZHazardRecognizer::dumpProcResourceCounters(), llvm::SystemZHazardRecognizer::dumpState(), llvm::MachineTraceMetrics::Ensemble::Ensemble(), llvm::MachineTraceMetrics::Ensemble::getLoopFor(), llvm::MachineTraceMetrics::getProcResourceCycles(), llvm::MachineTraceMetrics::Ensemble::getProcResourceDepths(), llvm::MachineTraceMetrics::Ensemble::getProcResourceHeights(), llvm::MachineTraceMetrics::getResources(), llvm::SchedRemainder::init(), llvm::SystemZHazardRecognizer::Reset(), and llvm::MachineTraceMetrics::runOnMachineFunction().
getProcessorID()
unsigned llvm::TargetSchedModel::getProcessorID () const inline
Identify the processor corresponding to the current subtarget.
Definition at line 96 of file TargetSchedule.h.
References llvm::MCSchedModel::getProcessorID().
getProcResource()
const MCProcResourceDesc* llvm::TargetSchedModel::getProcResource (unsigned PIdx) const inline
Get a processor resource by ID for convenience.
Definition at line 118 of file TargetSchedule.h.
References llvm::MCSchedModel::getProcResource().
Referenced by llvm::SystemZHazardRecognizer::dumpProcResourceCounters(), llvm::SystemZHazardRecognizer::dumpSU(), llvm::SystemZHazardRecognizer::EmitInstruction(), llvm::SystemZHazardRecognizer::emitInstruction(), llvm::ScheduleDAGInstrs::initSUnits(), and pushDepHeight().
getResourceBufferSize()
int llvm::TargetSchedModel::getResourceBufferSize (unsigned PIdx) const inline
Number of resource units that may be buffered for OOO execution.
Returns
The buffer size in resource units or -1 for unlimited.
Definition at line 165 of file TargetSchedule.h.
References llvm::MCProcResourceDesc::BufferSize, computeOperandLatency(), computeOutputLatency(), computeReciprocalThroughput(), DefMI, llvm::MCSchedModel::getProcResource(), and UseMI.
getResourceFactor()
unsigned llvm::TargetSchedModel::getResourceFactor (unsigned ResIdx) const inline
Multiply the number of units consumed for a resource by this factor to normalize it relative to other resources.
Definition at line 144 of file TargetSchedule.h.
Referenced by llvm::MachineTraceMetrics::getResources(), llvm::SchedRemainder::init(), and pushDepHeight().
getResourceName()
const char* llvm::TargetSchedModel::getResourceName (unsigned PIdx) const inline
Definition at line 123 of file TargetSchedule.h.
References llvm::MCSchedModel::getProcResource(), and llvm::MCProcResourceDesc::Name.
getSubtargetInfo()
const TargetSubtargetInfo* llvm::TargetSchedModel::getSubtargetInfo () const inline
TargetSubtargetInfo getter.
Definition at line 63 of file TargetSchedule.h.
getWriteProcResBegin()
ProcResIter llvm::TargetSchedModel::getWriteProcResBegin (const MCSchedClassDesc * SC) const inline
Definition at line 134 of file TargetSchedule.h.
References llvm::MCSubtargetInfo::getWriteProcResBegin().
Referenced by llvm::SystemZHazardRecognizer::dumpSU(), llvm::SystemZHazardRecognizer::EmitInstruction(), llvm::SystemZHazardRecognizer::emitInstruction(), llvm::MachineTraceMetrics::getResources(), llvm::SchedRemainder::init(), llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::ScheduleDAGInstrs::initSUnits(), and llvm::SystemZHazardRecognizer::resourcesCost().
getWriteProcResEnd()
ProcResIter llvm::TargetSchedModel::getWriteProcResEnd (const MCSchedClassDesc * SC) const inline
Definition at line 138 of file TargetSchedule.h.
References llvm::MCSubtargetInfo::getWriteProcResEnd().
Referenced by llvm::SystemZHazardRecognizer::dumpSU(), llvm::SystemZHazardRecognizer::EmitInstruction(), llvm::SystemZHazardRecognizer::emitInstruction(), llvm::MachineTraceMetrics::getResources(), llvm::SchedRemainder::init(), llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::ScheduleDAGInstrs::initSUnits(), and llvm::SystemZHazardRecognizer::resourcesCost().
hasInstrItineraries()
bool TargetSchedModel::hasInstrItineraries () const
Return true if this machine model includes cycle-to-cycle itinerary data.
This models scheduling at each stage in the processor pipeline.
Definition at line 43 of file TargetSchedule.cpp.
References EnableSchedItins, and llvm::InstrItineraryData::isEmpty().
Referenced by computeInstrLatency(), computeOperandLatency(), computeReciprocalThroughput(), getInstrItineraries(), getMCSchedModel(), getNumMicroOps(), and hasInstrSchedModelOrItineraries().
hasInstrSchedModel()
bool TargetSchedModel::hasInstrSchedModel () const
Return true if this machine model includes an instruction-level scheduling model.
This is more detailed than the course grain IssueWidth and default latency properties, but separate from the per-cycle itinerary data.
Definition at line 39 of file TargetSchedule.cpp.
References EnableSchedModel, and llvm::MCSchedModel::hasInstrSchedModel().
Referenced by computeInstrLatency(), computeOperandLatency(), computeOutputLatency(), computeReciprocalThroughput(), getInstrInfo(), getNumMicroOps(), llvm::MachineTraceMetrics::getResources(), llvm::SystemZHazardRecognizer::getSchedClass(), llvm::ScheduleDAGInstrs::getSchedClass(), hasInstrSchedModelOrItineraries(), llvm::SchedRemainder::init(), llvm::ScheduleDAGInstrs::initSUnits(), mustBeginGroup(), and mustEndGroup().
hasInstrSchedModelOrItineraries()
bool llvm::TargetSchedModel::hasInstrSchedModelOrItineraries () const inline
Return true if this machine model includes an instruction-level scheduling model or cycle-to-cycle itinerary data.
Definition at line 91 of file TargetSchedule.h.
References hasInstrItineraries(), and hasInstrSchedModel().
init()
void TargetSchedModel::init (const TargetSubtargetInfo * TSInfo)
Initialize the machine model for instruction scheduling.
The machine model API keeps a copy of the top-level MCSchedModel table indices and may query TargetSubtargetInfo and TargetInstrInfo to resolve dynamic properties.
Definition at line 63 of file TargetSchedule.cpp.
References llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MCSchedModel::getNumProcResourceKinds(), llvm::MCSchedModel::getProcResource(), llvm::MCSubtargetInfo::getSchedModel(), llvm::MCSubtargetInfo::initInstrItins(), llvm::MCSchedModel::IssueWidth, lcm(), llvm::MCProcResourceDesc::NumUnits, and llvm::SmallVectorImpl< T >::resize().
Referenced by llvm::GCNHazardRecognizer::GCNHazardRecognizer(), llvm::ConvergingVLIWScheduler::initialize(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ScheduleDAGInstrs::ScheduleDAGInstrs(), llvm::SIInstrInfo::SIInstrInfo(), llvm::SystemZPostRASchedStrategy::SystemZPostRASchedStrategy(), and TargetSchedModel().
mustBeginGroup()
bool TargetSchedModel::mustBeginGroup (const MachineInstr * MI, const MCSchedClassDesc * SC = nullptr) const
Return true if new group must begin.
Returns true only if instruction is specified as single issue.
Definition at line 85 of file TargetSchedule.cpp.
References llvm::MCSchedClassDesc::BeginGroup, hasInstrSchedModel(), llvm::MCSchedClassDesc::isValid(), and resolveSchedClass().
Referenced by getIssueWidth().
mustEndGroup()
bool TargetSchedModel::mustEndGroup (const MachineInstr * MI, const MCSchedClassDesc * SC = nullptr) const
Return true if current group must end.
Definition at line 96 of file TargetSchedule.cpp.
References llvm::MCSchedClassDesc::EndGroup, hasInstrSchedModel(), llvm::MCSchedClassDesc::isValid(), and resolveSchedClass().
Referenced by getIssueWidth().
resolveSchedClass()
const MCSchedClassDesc * TargetSchedModel::resolveSchedClass (const MachineInstr * MI) const
Return the MCSchedClassDesc for this instruction.
Some SchedClasses require evaluation of predicates that depend on instruction operands or flags.
Definition at line 133 of file TargetSchedule.cpp.
References assert(), llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getSchedClass(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSchedClassDesc::isValid(), llvm::MCSchedClassDesc::isVariant(), and llvm::TargetSubtargetInfo::resolveSchedClass().
Referenced by capLatency(), computeInstrLatency(), computeOperandLatency(), computeOutputLatency(), computeReciprocalThroughput(), llvm::SystemZHazardRecognizer::emitInstruction(), getNumMicroOps(), llvm::MachineTraceMetrics::getResources(), llvm::SystemZHazardRecognizer::getSchedClass(), llvm::ScheduleDAGInstrs::getSchedClass(), mustBeginGroup(), mustEndGroup(), and TargetSchedModel().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TargetSchedule.h
lib/CodeGen/TargetSchedule.cpp