LLVM: llvm::codeview::TypeVisitorCallbacks Class Reference
llvm::codeview::TypeVisitorCallbacks Class Reference
#include "llvm/DebugInfo/CodeView/TypeVisitorCallbacks.h"
Public Member Functions
virtual ~TypeVisitorCallbacks ()=default
virtual Error visitUnknownType (CVType &Record)
Action to take on unknown types. By default, they are ignored.
virtual Error visitTypeBegin (CVType &Record)
Paired begin/end actions for all types.
virtual Error visitTypeBegin (CVType &Record, TypeIndex Index)
virtual Error visitTypeEnd (CVType &Record)
virtual Error visitUnknownMember (CVMemberRecord &Record)
virtual Error visitMemberBegin (CVMemberRecord &Record)
virtual Error visitMemberEnd (CVMemberRecord &Record)
Detailed Description
Definition at line 18 of file TypeVisitorCallbacks.h.
Constructor & Destructor Documentation
~TypeVisitorCallbacks()
virtual llvm::codeview::TypeVisitorCallbacks::~TypeVisitorCallbacks () virtual default
Member Function Documentation
visitMemberBegin()
virtual Error llvm::codeview::TypeVisitorCallbacks::visitMemberBegin (CVMemberRecord & Record) inline virtual
Reimplemented in llvm::codeview::FieldListDeserializer, llvm::codeview::TypeVisitorCallbackPipeline, llvm::codeview::TypeDumpVisitor, and llvm::codeview::TypeRecordMapping.
Definition at line 41 of file TypeVisitorCallbacks.h.
References llvm::Error::success().
Referenced by visitMemberRecord().
visitMemberEnd()
virtual Error llvm::codeview::TypeVisitorCallbacks::visitMemberEnd (CVMemberRecord & Record) inline virtual
Reimplemented in llvm::codeview::FieldListDeserializer, llvm::codeview::TypeVisitorCallbackPipeline, llvm::codeview::TypeDumpVisitor, and llvm::codeview::TypeRecordMapping.
Definition at line 45 of file TypeVisitorCallbacks.h.
References llvm::Error::success().
Referenced by visitMemberRecord().
visitTypeBegin() [1/2]
virtual Error llvm::codeview::TypeVisitorCallbacks::visitTypeBegin (CVType & Record) inline virtual
Paired begin/end actions for all types.
Receives all record data, including the fixed-length record prefix. visitTypeBegin() should return the type of the Record, or an error if it cannot be determined. Exactly one of the two visitTypeBegin methods will be called, depending on whether records are being visited sequentially or randomly. An implementation should be prepared to handle both (or assert if it can't handle random access visitation).
Reimplemented in llvm::codeview::TypeDeserializer, llvm::codeview::TypeDumpVisitor, llvm::codeview::TypeVisitorCallbackPipeline, and llvm::codeview::TypeRecordMapping.
Definition at line 31 of file TypeVisitorCallbacks.h.
References llvm::Error::success().
Referenced by llvm::codeview::TypeRecordMapping::TypeRecordMapping(), and visitMemberRecord().
visitTypeBegin() [2/2]
virtual Error llvm::codeview::TypeVisitorCallbacks::visitTypeBegin (CVType & Record, TypeIndex Index) inline virtual
Reimplemented in llvm::codeview::TypeDeserializer, llvm::codeview::TypeDumpVisitor, llvm::codeview::TypeVisitorCallbackPipeline, and llvm::codeview::TypeRecordMapping.
Definition at line 32 of file TypeVisitorCallbacks.h.
References llvm::Error::success().
visitTypeEnd()
virtual Error llvm::codeview::TypeVisitorCallbacks::visitTypeEnd (CVType & Record) inline virtual
Reimplemented in llvm::codeview::TypeDeserializer, llvm::codeview::TypeVisitorCallbackPipeline, llvm::codeview::TypeDumpVisitor, and llvm::codeview::TypeRecordMapping.
Definition at line 35 of file TypeVisitorCallbacks.h.
References llvm::Error::success().
Referenced by visitMemberRecord().
visitUnknownMember()
virtual Error llvm::codeview::TypeVisitorCallbacks::visitUnknownMember (CVMemberRecord & Record) inline virtual
Reimplemented in llvm::codeview::TypeDumpVisitor, and llvm::codeview::TypeVisitorCallbackPipeline.
Definition at line 37 of file TypeVisitorCallbacks.h.
References llvm::Error::success().
Referenced by visitMemberRecord().
visitUnknownType()
virtual Error llvm::codeview::TypeVisitorCallbacks::visitUnknownType (CVType & Record) inline virtual
Action to take on unknown types. By default, they are ignored.
Reimplemented in llvm::codeview::TypeDumpVisitor.
Definition at line 23 of file TypeVisitorCallbacks.h.
References llvm::Error::success().
Referenced by visitMemberRecord().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeVisitorCallbacks.h