LLVM: llvm::orc::IRCompileLayer Class Reference
llvm::orc::IRCompileLayer Class Reference
#include "llvm/ExecutionEngine/Orc/IRCompileLayer.h"
Classes
class IRCompiler
Public Types
using NotifyCompiledFunction = std::function< void(VModuleKey K, ThreadSafeModule TSM)>
Public Member Functions
IRCompileLayer (ExecutionSession &ES, ObjectLayer &BaseLayer, std::unique_ptr< IRCompiler > Compile)
IRCompiler & getCompiler ()
void setNotifyCompiled (NotifyCompiledFunction NotifyCompiled)
void emit (MaterializationResponsibility R, ThreadSafeModule TSM) override
Emit should materialize the given IR.
Public Member Functions inherited from llvm::orc::IRLayer
IRLayer (ExecutionSession &ES, const IRMaterializationUnit::ManglingOptions *&MO)
virtual ~IRLayer ()
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this layer.
const IRMaterializationUnit::ManglingOptions *& getManglingOptions () const
Get the mangling options for this layer.
void setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit)
Sets the CloneToNewContextOnEmit flag (false by default).
bool getCloneToNewContextOnEmit () const
Returns the current value of the CloneToNewContextOnEmit flag.
virtual Error add (JITDylib &JD, ThreadSafeModule TSM, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Detailed Description
Definition at line 30 of file IRCompileLayer.h.
Member Typedef Documentation
NotifyCompiledFunction
using llvm::orc::IRCompileLayer::NotifyCompiledFunction = std::function<void(VModuleKey K, ThreadSafeModule TSM)>
Definition at line 49 of file IRCompileLayer.h.
Constructor & Destructor Documentation
IRCompileLayer()
llvm::orc::IRCompileLayer::IRCompileLayer (ExecutionSession & ES, ObjectLayer & BaseLayer, std::unique_ptr< IRCompiler > Compile)
Definition at line 16 of file IRCompileLayer.cpp.
Member Function Documentation
emit()
void llvm::orc::IRCompileLayer::emit (MaterializationResponsibility R, ThreadSafeModule TSM) override virtual
Emit should materialize the given IR.
Implements llvm::orc::IRLayer.
Definition at line 28 of file IRCompileLayer.cpp.
References assert(), llvm::orc::ObjectLayer::emit(), llvm::orc::MaterializationResponsibility::failMaterialization(), llvm::orc::IRLayer::getExecutionSession(), llvm::orc::MaterializationResponsibility::getVModuleKey(), llvm::Lock, llvm::orc::ExecutionSession::reportError(), and llvm::orc::ThreadSafeModule::withModuleDo().
Referenced by getCompiler().
getCompiler()
IRCompiler& llvm::orc::IRCompileLayer::getCompiler () inline
Definition at line 54 of file IRCompileLayer.h.
References emit(), and setNotifyCompiled().
setNotifyCompiled()
void llvm::orc::IRCompileLayer::setNotifyCompiled (NotifyCompiledFunction NotifyCompiled)
Definition at line 23 of file IRCompileLayer.cpp.
References llvm::Lock.
Referenced by getCompiler().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IRCompileLayer.h
lib/ExecutionEngine/Orc/IRCompileLayer.cpp