LLVM: llvm::DFAPacketizer Class Reference
llvm::DFAPacketizer Class Reference
#include "llvm/CodeGen/DFAPacketizer.h"
Public Member Functions
DFAPacketizer (const InstrItineraryData *InstrItins, Automaton< uint64_t > a, ArrayRef< unsigned > ItinActions)
void clearResources ()
void setTrackResources (bool Track)
bool canReserveResources (const MCInstrDesc *MID)
void reserveResources (const MCInstrDesc *MID)
bool canReserveResources (MachineInstr &MI)
void reserveResources (MachineInstr &MI)
unsigned getUsedResources (unsigned InstIdx)
const InstrItineraryData * getInstrItins () const
Detailed Description
Definition at line 49 of file DFAPacketizer.h.
Constructor & Destructor Documentation
DFAPacketizer()
llvm::DFAPacketizer::DFAPacketizer (const InstrItineraryData * InstrItins, Automaton< uint64_t > a, ArrayRef< unsigned > ItinActions) inline
Definition at line 58 of file DFAPacketizer.h.
References llvm::Automaton< ActionT >::enableTranscription().
Member Function Documentation
canReserveResources() [1/2]
bool DFAPacketizer::canReserveResources (const MCInstrDesc * MID)
Definition at line 57 of file DFAPacketizer.cpp.
References llvm::Automaton< ActionT >::canAdd(), and llvm::MCInstrDesc::getSchedClass().
Referenced by canReserveResources(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::HexagonHazardRecognizer::getHazardType(), llvm::VLIWResourceModel::isResourceAvailable(), llvm::VLIWPacketizerList::PacketizeMIs(), and setTrackResources().
canReserveResources() [2/2]
bool DFAPacketizer::canReserveResources (MachineInstr & MI)
Definition at line 75 of file DFAPacketizer.cpp.
References canReserveResources(), and llvm::MachineInstr::getDesc().
clearResources()
void llvm::DFAPacketizer::clearResources () inline
Definition at line 66 of file DFAPacketizer.h.
References llvm::Automaton< ActionT >::reset().
Referenced by llvm::HexagonHazardRecognizer::AdvanceCycle(), llvm::VLIWPacketizerList::endPacket(), llvm::VLIWResourceModel::reserveResources(), llvm::HexagonHazardRecognizer::Reset(), llvm::VLIWResourceModel::reset(), llvm::VLIWResourceModel::resetDFA(), and llvm::VLIWResourceModel::VLIWResourceModel().
getInstrItins()
const InstrItineraryData* llvm::DFAPacketizer::getInstrItins () const inline
Definition at line 102 of file DFAPacketizer.h.
getUsedResources()
unsigned DFAPacketizer::getUsedResources (unsigned InstIdx)
Definition at line 87 of file DFAPacketizer.cpp.
References assert(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), and llvm::Automaton< ActionT >::getNfaPaths().
Referenced by llvm::VLIWPacketizerList::endPacket(), and setTrackResources().
reserveResources() [1/2]
void DFAPacketizer::reserveResources (const MCInstrDesc * MID)
Definition at line 66 of file DFAPacketizer.cpp.
References llvm::Automaton< ActionT >::add(), and llvm::MCInstrDesc::getSchedClass().
Referenced by llvm::VLIWPacketizerList::addToPacket(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::VLIWResourceModel::reserveResources(), reserveResources(), and setTrackResources().
reserveResources() [2/2]
void DFAPacketizer::reserveResources (MachineInstr & MI)
Definition at line 82 of file DFAPacketizer.cpp.
References llvm::MachineInstr::getDesc(), and reserveResources().
setTrackResources()
void llvm::DFAPacketizer::setTrackResources (bool Track) inline
Definition at line 73 of file DFAPacketizer.h.
References canReserveResources(), llvm::Automaton< ActionT >::enableTranscription(), getUsedResources(), MI, and reserveResources().
Referenced by llvm::VLIWPacketizerList::VLIWPacketizerList().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DFAPacketizer.h
lib/CodeGen/DFAPacketizer.cpp