LLVM: llvm::object::MachOUniversalBinary::ObjectForArch Class Reference
llvm::object::MachOUniversalBinary::ObjectForArch Class Reference
#include "llvm/Object/MachOUniversal.h"
Public Member Functions
ObjectForArch (const MachOUniversalBinary *Parent, uint32_t Index)
void clear ()
bool operator== (const ObjectForArch &Other) const
ObjectForArch getNext () const
uint32_t getCPUType () const
uint32_t getCPUSubType () const
uint64_t getOffset () const
uint64_t getSize () const
uint32_t getAlign () const
uint32_t getReserved () const
std::string getArchFlagName () const
Expected< std::unique_ptr< MachOObjectFile > > getAsObjectFile () const
Expected< std::unique_ptr< Archive > > getAsArchive () const
Detailed Description
Definition at line 36 of file MachOUniversal.h.
Constructor & Destructor Documentation
ObjectForArch()
MachOUniversalBinary::ObjectForArch::ObjectForArch (const MachOUniversalBinary * Parent, uint32_t Index)
Definition at line 41 of file MachOUniversal.cpp.
References llvm::StringRef::begin(), clear(), llvm::MachO::FAT_MAGIC, llvm::object::Binary::getData(), llvm::object::MachOUniversalBinary::getMagic(), and llvm::object::MachOUniversalBinary::getNumberOfObjects().
Referenced by llvm::object::MachOUniversalBinary::begin_objects(), llvm::object::MachOUniversalBinary::end_objects(), and getNext().
Member Function Documentation
clear()
void llvm::object::MachOUniversalBinary::ObjectForArch::clear () inline
Definition at line 47 of file MachOUniversal.h.
Referenced by ObjectForArch().
getAlign()
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getAlign () const inline
Definition at line 81 of file MachOUniversal.h.
References llvm::MachO::fat_arch::align, llvm::MachO::fat_arch_64::align, llvm::MachO::FAT_MAGIC, and llvm::object::MachOUniversalBinary::getMagic().
getArchFlagName()
std::string llvm::object::MachOUniversalBinary::ObjectForArch::getArchFlagName () const inline
Definition at line 93 of file MachOUniversal.h.
References llvm::MachO::fat_arch::cpusubtype, llvm::MachO::fat_arch_64::cpusubtype, llvm::MachO::fat_arch::cputype, llvm::MachO::fat_arch_64::cputype, llvm::MachO::FAT_MAGIC, llvm::object::MachOObjectFile::getArchTriple(), getAsArchive(), getAsObjectFile(), and llvm::object::MachOUniversalBinary::getMagic().
getAsArchive()
Expected< std::unique_ptr< Archive > > MachOUniversalBinary::ObjectForArch::getAsArchive () const
Definition at line 84 of file MachOUniversal.cpp.
References llvm::object::Archive::create(), llvm::MachO::FAT_MAGIC, llvm::object::Binary::getData(), llvm::object::Binary::getFileName(), llvm::object::MachOUniversalBinary::getMagic(), llvm::MachO::fat_arch::offset, llvm::MachO::fat_arch_64::offset, llvm::report_fatal_error(), llvm::MachO::fat_arch::size, llvm::MachO::fat_arch_64::size, and llvm::StringRef::substr().
Referenced by getArchFlagName().
getAsObjectFile()
Expected< std::unique_ptr< MachOObjectFile > > MachOUniversalBinary::ObjectForArch::getAsObjectFile () const
Definition at line 63 of file MachOUniversal.cpp.
References llvm::MachO::fat_arch::cputype, llvm::MachO::fat_arch_64::cputype, llvm::object::ObjectFile::createMachOObjectFile(), llvm::MachO::FAT_MAGIC, llvm::object::Binary::getData(), llvm::object::Binary::getFileName(), llvm::object::MachOUniversalBinary::getMagic(), llvm::MachO::fat_arch::offset, llvm::MachO::fat_arch_64::offset, llvm::report_fatal_error(), llvm::MachO::fat_arch::size, llvm::MachO::fat_arch_64::size, and llvm::StringRef::substr().
Referenced by getArchFlagName().
getCPUSubType()
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getCPUSubType () const inline
Definition at line 63 of file MachOUniversal.h.
References llvm::MachO::fat_arch::cpusubtype, llvm::MachO::fat_arch_64::cpusubtype, llvm::MachO::FAT_MAGIC, and llvm::object::MachOUniversalBinary::getMagic().
getCPUType()
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getCPUType () const inline
Definition at line 57 of file MachOUniversal.h.
References llvm::MachO::fat_arch::cputype, llvm::MachO::fat_arch_64::cputype, llvm::MachO::FAT_MAGIC, and llvm::object::MachOUniversalBinary::getMagic().
getNext()
ObjectForArch llvm::object::MachOUniversalBinary::ObjectForArch::getNext () const inline
Definition at line 56 of file MachOUniversal.h.
References ObjectForArch().
Referenced by llvm::object::MachOUniversalBinary::object_iterator::operator++().
getOffset()
uint64_t llvm::object::MachOUniversalBinary::ObjectForArch::getOffset () const inline
Definition at line 69 of file MachOUniversal.h.
References llvm::MachO::FAT_MAGIC, llvm::object::MachOUniversalBinary::getMagic(), llvm::MachO::fat_arch::offset, and llvm::MachO::fat_arch_64::offset.
getReserved()
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getReserved () const inline
Definition at line 87 of file MachOUniversal.h.
References llvm::MachO::FAT_MAGIC, llvm::object::MachOUniversalBinary::getMagic(), and llvm::MachO::fat_arch_64::reserved.
getSize()
uint64_t llvm::object::MachOUniversalBinary::ObjectForArch::getSize () const inline
Definition at line 75 of file MachOUniversal.h.
References llvm::MachO::FAT_MAGIC, llvm::object::MachOUniversalBinary::getMagic(), llvm::MachO::fat_arch::size, and llvm::MachO::fat_arch_64::size.
operator==()
bool llvm::object::MachOUniversalBinary::ObjectForArch::operator== (const ObjectForArch & Other) const inline
Definition at line 52 of file MachOUniversal.h.
The documentation for this class was generated from the following files:
include/llvm/Object/MachOUniversal.h
lib/Object/MachOUniversal.cpp