LLVM: llvm::MachineModuleInfoImpl Class Reference
llvm::MachineModuleInfoImpl Class Reference
This class can be derived from and used by targets to hold private target-specific information for each Module.
#include "llvm/CodeGen/MachineModuleInfo.h"
Public Types
using StubValueTy = PointerIntPair< MCSymbol *, 1, bool >
using SymbolListTy = std::vector< std::pair< MCSymbol *, StubValueTy > >
Public Member Functions
virtual ~MachineModuleInfoImpl ()
Static Protected Member Functions
static SymbolListTy getSortedStubs (DenseMap< MCSymbol *, StubValueTy > &)
Return the entries from a DenseMap in a deterministic sorted orer.
Detailed Description
This class can be derived from and used by targets to hold private target-specific information for each Module.
Objects of type are accessed/created with MMI::getInfo and destroyed when the MachineModuleInfo is destroyed.
Definition at line 60 of file MachineModuleInfo.h.
Member Typedef Documentation
StubValueTy
using llvm::MachineModuleInfoImpl::StubValueTy = PointerIntPair<MCSymbol *, 1, bool>
Definition at line 62 of file MachineModuleInfo.h.
SymbolListTy
using llvm::MachineModuleInfoImpl::SymbolListTy = std::vector<std::pair<MCSymbol *, StubValueTy> >
Definition at line 63 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
~MachineModuleInfoImpl()
MachineModuleInfoImpl::~MachineModuleInfoImpl () virtual default
Member Function Documentation
getSortedStubs()
MachineModuleInfoImpl::SymbolListTy MachineModuleInfoImpl::getSortedStubs (DenseMap< MCSymbol *, StubValueTy > & Map) static protected
Return the entries from a DenseMap in a deterministic sorted orer.
Clears the map.
Definition at line 34 of file MachineModuleInfoImpls.cpp.
References llvm::array_pod_sort(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), List, and SortSymbolPair().
Referenced by llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MachineModuleInfoCOFF::GetGVStubList(), and llvm::MachineModuleInfoMachO::GetThreadLocalGVStubList().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfo.h
lib/CodeGen/MachineModuleInfo.cpp
lib/CodeGen/MachineModuleInfoImpls.cpp