LLVM: llvm::JamCRC Class Reference
llvm::JamCRC Class Reference
#include "llvm/Support/CRC.h"
Public Member Functions
JamCRC (uint32_t Init=0xFFFFFFFFU)
void update (ArrayRef< uint8_t > Data)
uint32_t getCRC () const
Detailed Description
Definition at line 45 of file CRC.h.
Constructor & Destructor Documentation
JamCRC()
llvm::JamCRC::JamCRC (uint32_t Init = 0xFFFFFFFFU) inline
Definition at line 47 of file CRC.h.
References llvm::Data, and update().
Member Function Documentation
getCRC()
uint32_t llvm::JamCRC::getCRC () const inline
Definition at line 52 of file CRC.h.
Referenced by llvm::pdb::hashBufferV8(), llvm::pdb::hashTypeRecord(), and INITIALIZE_PASS().
update()
void JamCRC::update (ArrayRef< uint8_t > Data)
Definition at line 103 of file CRC.cpp.
References llvm::crc32().
Referenced by llvm::pdb::PDBFileBuilder::addInjectedSource(), llvm::pdb::hashBufferV8(), llvm::pdb::hashTypeRecord(), INITIALIZE_PASS(), and JamCRC().
The documentation for this class was generated from the following files:
include/llvm/Support/CRC.h
lib/Support/CRC.cpp