LLVM: llvm::LazyCallGraph::postorder_ref_scc_iterator Class Reference
llvm::LazyCallGraph::postorder_ref_scc_iterator Class Reference
A post-order depth-first RefSCC iterator over the call graph.
#include "llvm/Analysis/LazyCallGraph.h"
Public Member Functions
bool operator== (const postorder_ref_scc_iterator &Arg) const
reference operator* () const
postorder_ref_scc_iterator & operator++ ()
Public Member Functions inherited from llvm::iterator_facade_base< postorder_ref_scc_iterator, std::forward_iterator_tag, RefSCC >
postorder_ref_scc_iterator operator+ (std::ptrdiff_t n) const
postorder_ref_scc_iterator operator- (std::ptrdiff_t n) const
postorder_ref_scc_iterator & operator++ ()
postorder_ref_scc_iterator operator++ (int)
postorder_ref_scc_iterator & operator-- ()
postorder_ref_scc_iterator operator-- (int)
bool operator!= (const postorder_ref_scc_iterator &RHS) const
bool operator> (const postorder_ref_scc_iterator &RHS) const
bool operator<= (const postorder_ref_scc_iterator &RHS) const
bool operator>= (const postorder_ref_scc_iterator &RHS) const
RefSCC * operator-> ()
RefSCC * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Friends
class LazyCallGraph
class LazyCallGraph::Node
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< postorder_ref_scc_iterator, std::forward_iterator_tag, RefSCC >
enum
Detailed Description
A post-order depth-first RefSCC iterator over the call graph.
This iterator walks the cached post-order sequence of RefSCCs. However, it trades stability for flexibility. It is restricted to a forward iterator but will survive mutations which insert new RefSCCs and continue to point to the same RefSCC even if it moves in the post-order sequence.
Definition at line 886 of file LazyCallGraph.h.
Member Function Documentation
operator*()
reference llvm::LazyCallGraph::postorder_ref_scc_iterator::operator* () const inline
Definition at line 919 of file LazyCallGraph.h.
operator++()
postorder_ref_scc_iterator& llvm::LazyCallGraph::postorder_ref_scc_iterator::operator++ () inline
Definition at line 922 of file LazyCallGraph.h.
References assert(), llvm::LazyCallGraph::LazyCallGraph(), and llvm::LazyCallGraph::operator=().
operator==()
bool llvm::LazyCallGraph::postorder_ref_scc_iterator::operator== (const postorder_ref_scc_iterator & Arg) const inline
Definition at line 915 of file LazyCallGraph.h.
Friends And Related Function Documentation
LazyCallGraph
friend class LazyCallGraph friend
Definition at line 889 of file LazyCallGraph.h.
LazyCallGraph::Node
friend class LazyCallGraph::Node friend
Definition at line 890 of file LazyCallGraph.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/LazyCallGraph.h