LLVM: llvm::LowerAtomicPass Class Reference
llvm::LowerAtomicPass Class Reference
A pass that lowers atomic intrinsic into non-atomic intrinsics.
#include "llvm/Transforms/Scalar/LowerAtomic.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LowerAtomicPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A pass that lowers atomic intrinsic into non-atomic intrinsics.
Definition at line 22 of file LowerAtomic.h.
Member Function Documentation
run()
PreservedAnalyses LowerAtomicPass::run (Function & F, FunctionAnalysisManager &)
Definition at line 147 of file LowerAtomic.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::PassRegistry::getPassRegistry(), llvm::initializeLowerAtomicLegacyPassPass(), lowerAtomics(), llvm::PreservedAnalyses::none(), and runOnFunction().
Referenced by llvm::WebAssemblyTargetMachine::getSubtargetImpl().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LowerAtomic.h
lib/Transforms/Scalar/LowerAtomic.cpp