LLVM: llvm::codeview::MemberPointerInfo Class Reference
llvm::codeview::MemberPointerInfo Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
MemberPointerInfo ()=default
MemberPointerInfo (TypeIndex ContainingType, PointerToMemberRepresentation Representation)
TypeIndex getContainingType () const
PointerToMemberRepresentation getRepresentation () const
Public Attributes
TypeIndex ContainingType
PointerToMemberRepresentation Representation
Detailed Description
Definition at line 106 of file TypeRecord.h.
Constructor & Destructor Documentation
MemberPointerInfo() [1/2]
llvm::codeview::MemberPointerInfo::MemberPointerInfo () default
MemberPointerInfo() [2/2]
llvm::codeview::MemberPointerInfo::MemberPointerInfo (TypeIndex ContainingType, PointerToMemberRepresentation Representation) inline
Definition at line 110 of file TypeRecord.h.
Member Function Documentation
getContainingType()
TypeIndex llvm::codeview::MemberPointerInfo::getContainingType () const inline
Definition at line 114 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getRepresentation()
PointerToMemberRepresentation llvm::codeview::MemberPointerInfo::getRepresentation () const inline
Definition at line 115 of file TypeRecord.h.
Referenced by isInheritanceKind(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
ContainingType
TypeIndex llvm::codeview::MemberPointerInfo::ContainingType
Definition at line 119 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypePointer::getClassParentId(), and llvm::codeview::TypeRecordMapping::visitMemberEnd().
Representation
PointerToMemberRepresentation llvm::codeview::MemberPointerInfo::Representation
Definition at line 120 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h