LLVM: llvm::codeview::FuncIdRecord Class Reference
llvm::codeview::FuncIdRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
FuncIdRecord ()=default
FuncIdRecord (TypeRecordKind Kind)
FuncIdRecord (TypeIndex ParentScope, TypeIndex FunctionType, StringRef Name)
TypeIndex getParentScope () const
TypeIndex getFunctionType () const
StringRef getName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex ParentScope
TypeIndex FunctionType
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 615 of file TypeRecord.h.
Constructor & Destructor Documentation
FuncIdRecord() [1/3]
llvm::codeview::FuncIdRecord::FuncIdRecord () default
FuncIdRecord() [2/3]
llvm::codeview::FuncIdRecord::FuncIdRecord (TypeRecordKind Kind) inline explicit
Definition at line 618 of file TypeRecord.h.
FuncIdRecord() [3/3]
llvm::codeview::FuncIdRecord::FuncIdRecord (TypeIndex ParentScope, TypeIndex FunctionType, StringRef Name) inline
Definition at line 619 of file TypeRecord.h.
Member Function Documentation
getFunctionType()
TypeIndex llvm::codeview::FuncIdRecord::getFunctionType () const inline
Definition at line 624 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getName()
StringRef llvm::codeview::FuncIdRecord::getName () const inline
Definition at line 625 of file TypeRecord.h.
References Name.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getParentScope()
TypeIndex llvm::codeview::FuncIdRecord::getParentScope () const inline
Definition at line 623 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
FunctionType
TypeIndex llvm::codeview::FuncIdRecord::FunctionType
Definition at line 628 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Name
StringRef llvm::codeview::FuncIdRecord::Name
Definition at line 629 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
ParentScope
TypeIndex llvm::codeview::FuncIdRecord::ParentScope
Definition at line 627 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h