LLVM: llvm::RISCVMachineFunctionInfo Class Reference
llvm::RISCVMachineFunctionInfo Class Reference
RISCVMachineFunctionInfo - This class is derived from MachineFunctionInfo and contains private RISCV-specific information for each MachineFunction.
#include "Target/RISCV/RISCVMachineFunctionInfo.h"
Public Member Functions
RISCVMachineFunctionInfo (MachineFunction &MF)
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
unsigned getVarArgsSaveSize () const
void setVarArgsSaveSize (int Size)
int getMoveF64FrameIndex ()
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
RISCVMachineFunctionInfo - This class is derived from MachineFunctionInfo and contains private RISCV-specific information for each MachineFunction.
Definition at line 23 of file RISCVMachineFunctionInfo.h.
Constructor & Destructor Documentation
RISCVMachineFunctionInfo()
llvm::RISCVMachineFunctionInfo::RISCVMachineFunctionInfo (MachineFunction & MF) inline
Definition at line 35 of file RISCVMachineFunctionInfo.h.
Member Function Documentation
getMoveF64FrameIndex()
int llvm::RISCVMachineFunctionInfo::getMoveF64FrameIndex () inline
Definition at line 43 of file RISCVMachineFunctionInfo.h.
References llvm::MachineFrameInfo::CreateStackObject(), and llvm::MachineFunction::getFrameInfo().
getVarArgsFrameIndex()
int llvm::RISCVMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 37 of file RISCVMachineFunctionInfo.h.
getVarArgsSaveSize()
unsigned llvm::RISCVMachineFunctionInfo::getVarArgsSaveSize () const inline
Definition at line 40 of file RISCVMachineFunctionInfo.h.
setVarArgsFrameIndex()
void llvm::RISCVMachineFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 38 of file RISCVMachineFunctionInfo.h.
Referenced by CC_RISCV_FastCC().
setVarArgsSaveSize()
void llvm::RISCVMachineFunctionInfo::setVarArgsSaveSize (int Size) inline
Definition at line 41 of file RISCVMachineFunctionInfo.h.
References Size.
Referenced by CC_RISCV_FastCC().
The documentation for this class was generated from the following file:
lib/Target/RISCV/RISCVMachineFunctionInfo.h