LLVM: llvm::AMDGPU::HSAMD::V3::MetadataVerifier Class Reference
llvm::AMDGPU::HSAMD::V3::MetadataVerifier Class Reference
Verifier for AMDGPU HSA metadata.
#include "llvm/BinaryFormat/AMDGPUMetadataVerifier.h"
Public Member Functions
MetadataVerifier (bool Strict)
Construct a MetadataVerifier, specifying whether it will operate in Strict mode.
bool verify (msgpack::DocNode &HSAMetadataRoot)
Verify given HSA metadata.
Detailed Description
Verifier for AMDGPU HSA metadata.
Operates in two modes:
In strict mode, metadata must already be well-typed.
In non-strict mode, metadata is coerced into expected types when possible.
Definition at line 33 of file AMDGPUMetadataVerifier.h.
Constructor & Destructor Documentation
MetadataVerifier()
llvm::AMDGPU::HSAMD::V3::MetadataVerifier::MetadataVerifier (bool Strict) inline
Construct a MetadataVerifier, specifying whether it will operate in Strict mode.
Definition at line 56 of file AMDGPUMetadataVerifier.h.
References verify().
Member Function Documentation
verify()
bool llvm::AMDGPU::HSAMD::V3::MetadataVerifier::verify (msgpack::DocNode & HSAMetadataRoot)
Verify given HSA metadata.
Returns
True when successful, false when metadata is invalid.
Definition at line 284 of file AMDGPUMetadataVerifier.cpp.
References llvm::msgpack::DocNode::getMap(), llvm::msgpack::DocNode::isMap(), and llvm::msgpack::String.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitHSAMetadata(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), and MetadataVerifier().
The documentation for this class was generated from the following files:
include/llvm/BinaryFormat/AMDGPUMetadataVerifier.h
lib/BinaryFormat/AMDGPUMetadataVerifier.cpp