LLVM: llvm::AttributeImpl Class Reference
llvm::AttributeImpl Class Reference
#include "IR/AttributeImpl.h"
Public Member Functions
AttributeImpl (const AttributeImpl &)=delete
AttributeImpl & operator= (const AttributeImpl &)=delete
virtual ~AttributeImpl ()
bool isEnumAttribute () const
bool isIntAttribute () const
bool isStringAttribute () const
bool isTypeAttribute () const
bool hasAttribute (Attribute::AttrKind A) const
bool hasAttribute (StringRef Kind) const
Attribute::AttrKind getKindAsEnum () const
uint64_t getValueAsInt () const
StringRef getKindAsString () const
StringRef getValueAsString () const
Type * getValueAsType () const
bool operator< (const AttributeImpl &AI) const
Used when sorting the attributes.
void Profile (FoldingSetNodeID &ID) const
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, uint64_t Val)
static void Profile (FoldingSetNodeID &ID, StringRef Kind, StringRef Values)
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, Type *Ty)
Protected Types
enum AttrEntryKind { EnumAttrEntry, IntAttrEntry, StringAttrEntry, TypeAttrEntry }
Protected Member Functions
AttributeImpl (AttrEntryKind KindID)
Detailed Description
Definition at line 38 of file AttributeImpl.h.
Member Enumeration Documentation
AttrEntryKind
enum llvm::AttributeImpl::AttrEntryKind protected
Enumerator
EnumAttrEntry
IntAttrEntry
StringAttrEntry
TypeAttrEntry
Definition at line 42 of file AttributeImpl.h.
Constructor & Destructor Documentation
AttributeImpl() [1/2]
llvm::AttributeImpl::AttributeImpl (AttrEntryKind KindID) inline protected
Definition at line 49 of file AttributeImpl.h.
References operator=(), and ~AttributeImpl().
AttributeImpl() [2/2]
llvm::AttributeImpl::AttributeImpl (const AttributeImpl &) delete
~AttributeImpl()
AttributeImpl::~AttributeImpl () virtual default
Referenced by AttributeImpl(), and llvm::Attribute::operator<().
Member Function Documentation
getKindAsEnum()
Attribute::AttrKind AttributeImpl::getKindAsEnum () const
Definition at line 519 of file Attributes.cpp.
References assert(), llvm::Attribute::isEnumAttribute(), llvm::Attribute::isIntAttribute(), and llvm::Attribute::isTypeAttribute().
Referenced by llvm::Attribute::getKindAsEnum(), isTypeAttribute(), operator<(), and Profile().
getKindAsString()
StringRef AttributeImpl::getKindAsString () const
Definition at line 529 of file Attributes.cpp.
References assert(), and llvm::Attribute::isStringAttribute().
Referenced by llvm::Attribute::getKindAsString(), isTypeAttribute(), operator<(), and Profile().
getValueAsInt()
uint64_t AttributeImpl::getValueAsInt () const
Definition at line 524 of file Attributes.cpp.
References assert(), and llvm::Attribute::isIntAttribute().
Referenced by llvm::Attribute::getAlignment(), llvm::Attribute::getAllocSizeArgs(), llvm::Attribute::getDereferenceableBytes(), llvm::Attribute::getDereferenceableOrNullBytes(), llvm::Attribute::getStackAlignment(), llvm::Attribute::getValueAsInt(), isTypeAttribute(), operator<(), and Profile().
getValueAsString()
StringRef AttributeImpl::getValueAsString () const
Definition at line 534 of file Attributes.cpp.
References assert(), and llvm::Attribute::isStringAttribute().
Referenced by llvm::Attribute::getAsString(), llvm::Attribute::getValueAsString(), isTypeAttribute(), operator<(), and Profile().
getValueAsType()
Type * AttributeImpl::getValueAsType () const
Definition at line 539 of file Attributes.cpp.
References assert(), and llvm::Attribute::isTypeAttribute().
Referenced by llvm::Attribute::getValueAsType(), isTypeAttribute(), and Profile().
hasAttribute() [1/2]
bool AttributeImpl::hasAttribute (Attribute::AttrKind A) const
Definition at line 509 of file Attributes.cpp.
References A, llvm::Attribute::getKindAsEnum(), and llvm::Attribute::isStringAttribute().
Referenced by llvm::Attribute::hasAttribute(), llvm::AttributeSetNode::hasAttribute(), and isTypeAttribute().
hasAttribute() [2/2]
bool AttributeImpl::hasAttribute (StringRef Kind) const
Definition at line 514 of file Attributes.cpp.
References llvm::Attribute::getKindAsString(), and llvm::Attribute::isStringAttribute().
isEnumAttribute()
bool llvm::AttributeImpl::isEnumAttribute () const inline
Definition at line 58 of file AttributeImpl.h.
References EnumAttrEntry.
Referenced by llvm::Attribute::isEnumAttribute(), operator<(), and Profile().
isIntAttribute()
bool llvm::AttributeImpl::isIntAttribute () const inline
Definition at line 59 of file AttributeImpl.h.
References IntAttrEntry.
Referenced by llvm::Attribute::isIntAttribute(), operator<(), and Profile().
isStringAttribute()
bool llvm::AttributeImpl::isStringAttribute () const inline
Definition at line 60 of file AttributeImpl.h.
References StringAttrEntry.
Referenced by llvm::Attribute::isStringAttribute(), operator<(), and Profile().
isTypeAttribute()
bool llvm::AttributeImpl::isTypeAttribute () const inline
Definition at line 61 of file AttributeImpl.h.
References getKindAsEnum(), getKindAsString(), getValueAsInt(), getValueAsString(), getValueAsType(), hasAttribute(), operator<(), and TypeAttrEntry.
Referenced by llvm::Attribute::isTypeAttribute(), and operator<().
operator<()
bool AttributeImpl::operator< (const AttributeImpl & AI) const
Used when sorting the attributes.
Definition at line 544 of file Attributes.cpp.
References assert(), getKindAsEnum(), llvm::Attribute::getKindAsEnum(), getKindAsString(), llvm::Attribute::getKindAsString(), getValueAsInt(), llvm::Attribute::getValueAsInt(), getValueAsString(), llvm::Attribute::getValueAsString(), isEnumAttribute(), llvm::Attribute::isEnumAttribute(), isIntAttribute(), llvm::Attribute::isIntAttribute(), isStringAttribute(), llvm::Attribute::isStringAttribute(), isTypeAttribute(), and llvm::Attribute::isTypeAttribute().
Referenced by isTypeAttribute().
operator=()
AttributeImpl& llvm::AttributeImpl::operator= (const AttributeImpl &) delete
Referenced by AttributeImpl().
Profile() [1/4]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID) const inline
Definition at line 77 of file AttributeImpl.h.
References getKindAsEnum(), getKindAsString(), getValueAsInt(), getValueAsString(), getValueAsType(), isEnumAttribute(), isIntAttribute(), and isStringAttribute().
Referenced by llvm::AttributeListImpl::end(), and llvm::AttributeSetNode::Profile().
Profile() [2/4]
static void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind, uint64_t Val) inline static
Definition at line 88 of file AttributeImpl.h.
References llvm::FoldingSetNodeID::AddInteger().
Profile() [3/4]
static void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, StringRef Kind, StringRef Values) inline static
Definition at line 94 of file AttributeImpl.h.
References llvm::FoldingSetNodeID::AddString(), and llvm::StringRef::empty().
Profile() [4/4]
static void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind, Type * Ty) inline static
Definition at line 99 of file AttributeImpl.h.
References llvm::FoldingSetNodeID::AddInteger(), and llvm::FoldingSetNodeID::AddPointer().
The documentation for this class was generated from the following files:
lib/IR/AttributeImpl.h
lib/IR/Attributes.cpp