LLVM: llvm::orc::BlockFreqQuery Class Reference
llvm::orc::BlockFreqQuery Class Reference
#include "llvm/ExecutionEngine/Orc/SpeculateAnalyses.h"
Public Member Functions
ResultTy operator() (Function &F)
Additional Inherited Members
Public Types inherited from llvm::orc::SpeculateQuery
using ResultTy = Optional< DenseMap< StringRef, DenseSet< StringRef > >>
Protected Member Functions inherited from llvm::orc::SpeculateQuery
void findCalles (const BasicBlock *, DenseSet< StringRef > &)
bool isStraightLine (const Function &F)
Detailed Description
Definition at line 37 of file SpeculateAnalyses.h.
Member Function Documentation
operator()()
BlockFreqQuery::ResultTy llvm::orc::BlockFreqQuery::operator() (Function & F)
Definition at line 88 of file SpeculateAnalyses.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::AMDGPUISD::BFI, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::empty(), llvm::SmallVectorTemplateCommon< T >::end(), F(), llvm::orc::SpeculateQuery::findCalles(), llvm::FindFunctionBackedges(), first, llvm::Function::getBasicBlockList(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::Value::getName(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::is_contained(), llvm::BranchProbabilityInfo::isEdgeHot(), llvm::None, llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::PassBuilder::registerFunctionAnalyses(), llvm::SmallVectorBase::size(), llvm::sort(), llvm::succ_begin(), llvm::succ_end(), and true.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/SpeculateAnalyses.h
lib/ExecutionEngine/Orc/SpeculateAnalyses.cpp