LLVM: llvm::jitlink::InProcessMemoryManager Class Reference
llvm::jitlink::InProcessMemoryManager Class Reference
A JITLinkMemoryManager that allocates in-process memory.
#include "llvm/ExecutionEngine/JITLink/JITLinkMemoryManager.h"
Public Member Functions
Expected< std::unique_ptr< Allocation > > allocate (const SegmentsRequestMap &Request) override
Create an Allocation object.
Public Member Functions inherited from llvm::jitlink::JITLinkMemoryManager
virtual ~JITLinkMemoryManager ()
Additional Inherited Members
Public Types inherited from llvm::jitlink::JITLinkMemoryManager
using ProtectionFlags = sys::Memory::ProtectionFlags
using SegmentsRequestMap = DenseMap< unsigned, SegmentRequest >
Detailed Description
A JITLinkMemoryManager that allocates in-process memory.
Definition at line 89 of file JITLinkMemoryManager.h.
Member Function Documentation
allocate()
Expected< std::unique_ptr< JITLinkMemoryManager::Allocation > > llvm::jitlink::InProcessMemoryManager::allocate (const SegmentsRequestMap & Request) override virtual
Create an Allocation object.
Implements llvm::jitlink::JITLinkMemoryManager.
Definition at line 20 of file JITLinkMemoryManager.cpp.
References llvm::alignTo(), llvm::sys::Memory::allocateMappedMemory(), assert(), llvm::errorCodeToError(), llvm::sys::Process::getPageSizeEstimate(), llvm::inconvertibleErrorCode(), llvm::sys::Memory::InvalidateInstructionCache(), llvm::isPowerOf2_64(), llvm::max(), llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, llvm::sys::Memory::protectMappedMemory(), llvm::sys::Memory::releaseMappedMemory(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLinkMemoryManager.h
lib/ExecutionEngine/JITLink/JITLinkMemoryManager.cpp