LLVM: llvm::yaml::BinaryRef Class Reference
llvm::yaml::BinaryRef Class Reference
Specialized YAMLIO scalar type for representing a binary blob.
#include "llvm/ObjectYAML/YAML.h"
Public Member Functions
BinaryRef ()=default
BinaryRef (ArrayRef< uint8_t > Data)
BinaryRef (StringRef Data)
ArrayRef< uint8_t >::size_type binary_size () const
The number of bytes that are represented by this BinaryRef.
void writeAsBinary (raw_ostream &OS, uint64_t N=UINT64_MAX) const
Write the contents (regardless of whether it is binary or a hex string) as binary to the given raw_ostream.
void writeAsHex (raw_ostream &OS) const
Write the contents (regardless of whether it is binary or a hex string) as hex to the given raw_ostream.
Friends
bool operator== (const BinaryRef &LHS, const BinaryRef &RHS)
Detailed Description
Specialized YAMLIO scalar type for representing a binary blob.
A typical use case would be to represent the content of a section in a binary file. This class has custom YAMLIO traits for convenient reading and writing. It renders as a string of hex digits in a YAML file. For example, it might render as DEADBEEFCAFEBABE (YAML does not require the quotation marks, so for simplicity when outputting they are omitted). When reading, any string whose content is an even number of hex digits will be accepted. For example, all of the following are acceptable: DEADBEEF, "DeADbEeF", "\x44EADBEEF" (Note: '' == 'D')
A significant advantage of using this class is that it never allocates temporary strings or buffers for any of its functionality.
Example:
The YAML mapping:
Foo: DEADBEEFCAFEBABE
Could be modeled in YAMLIO by the struct:
struct FooHolder {
  BinaryRef Foo;
};
namespace llvm {
namespace yaml {
template <>
struct MappingTraits<FooHolder> {
  static void mapping(IO &IO, FooHolder &FH) {
    IO.mapRequired("Foo", FH.Foo);
  }
};
} // end namespace yaml
} // end namespace llvm
Definition at line 63 of file YAML.h.
Constructor & Destructor Documentation
BinaryRef() [1/3]
llvm::yaml::BinaryRef::BinaryRef () default
BinaryRef() [2/3]
llvm::yaml::BinaryRef::BinaryRef (ArrayRef< uint8_t > Data) inline
Definition at line 75 of file YAML.h.
BinaryRef() [3/3]
llvm::yaml::BinaryRef::BinaryRef (StringRef Data) inline
Definition at line 76 of file YAML.h.
Member Function Documentation
binary_size()
ArrayRef<uint8_t>::size_type llvm::yaml::BinaryRef::binary_size () const inline
The number of bytes that are represented by this BinaryRef.
This is the number of bytes that writeAsBinary() will write.
Definition at line 80 of file YAML.h.
References N, llvm::ArrayRef< T >::size(), UINT64_MAX, writeAsBinary(), and writeAsHex().
Referenced by isMips64EL(), layout(), layoutCOFF(), llvm::yaml::MappingTraits< COFFYAML::Section >::mapping(), streamMapping(), streamValidate(), llvm::yaml::MappingTraits< MachOYAML::Section >::validate(), writeAsHex(), writeCOFF(), and writeContent().
writeAsBinary()
void yaml::BinaryRef::writeAsBinary (raw_ostream & OS, uint64_t N = UINT64_MAX) const
Write the contents (regardless of whether it is binary or a hex string) as binary to the given raw_ostream.
N can be used to specify the maximum number of bytes.
Definition at line 40 of file YAML.cpp.
References llvm::ArrayRef< T >::data(), E, llvm::hexDigitValue(), I, N, llvm::ArrayRef< T >::size(), and llvm::raw_ostream::write().
Referenced by binary_size(), isMips64EL(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::map(), writeCOFF(), writeContent(), and writeLimits().
writeAsHex()
void yaml::BinaryRef::writeAsHex (raw_ostream & OS) const
Write the contents (regardless of whether it is binary or a hex string) as hex to the given raw_ostream.
For example, a possible output could be DEADBEEFCAFEBABE.
Definition at line 55 of file YAML.cpp.
References binary_size(), llvm::ArrayRef< T >::data(), llvm::hexdigit(), llvm::ArrayRef< T >::size(), and llvm::raw_ostream::write().
Referenced by binary_size().
Friends And Related Function Documentation
operator==
bool operator== (const BinaryRef & LHS, const BinaryRef & RHS) friend
Definition at line 98 of file YAML.h.
The documentation for this class was generated from the following files:
include/llvm/ObjectYAML/YAML.h
lib/ObjectYAML/YAML.cpp