LLVM: llvm::VESubtarget Class Reference
llvm::VESubtarget Class Reference
#include "Target/VE/VESubtarget.h"
Public Member Functions
VESubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
const VEInstrInfo * getInstrInfo () const override
const TargetFrameLowering * getFrameLowering () const override
const VERegisterInfo * getRegisterInfo () const override
const VETargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool enableMachineScheduler () const override
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
VESubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
int getAdjustedFrameSize (int stackSize) const
Given a actual stack size as determined by FrameInfo, this function returns adjusted framesize which includes space for register window spills and arguments.
bool isTargetLinux () const
Detailed Description
Definition at line 31 of file VESubtarget.h.
Constructor & Destructor Documentation
VESubtarget()
VESubtarget::VESubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
Definition at line 41 of file VESubtarget.cpp.
Member Function Documentation
enableMachineScheduler()
bool VESubtarget::enableMachineScheduler () const override
Definition at line 99 of file VESubtarget.cpp.
Referenced by getSelectionDAGInfo().
getAdjustedFrameSize()
int VESubtarget::getAdjustedFrameSize (int stackSize) const
Given a actual stack size as determined by FrameInfo, this function returns adjusted framesize which includes space for register window spills and arguments.
Definition at line 47 of file VESubtarget.cpp.
References llvm::alignTo().
Referenced by llvm::VEFrameLowering::emitPrologue(), and getSelectionDAGInfo().
getFrameLowering()
const TargetFrameLowering* llvm::VESubtarget::getFrameLowering () const inline override
Definition at line 45 of file VESubtarget.h.
getInstrInfo()
const VEInstrInfo* llvm::VESubtarget::getInstrInfo () const inline override
Definition at line 44 of file VESubtarget.h.
Referenced by llvm::VEFrameLowering::emitPrologue().
getRegisterInfo()
const VERegisterInfo* llvm::VESubtarget::getRegisterInfo () const inline override
Definition at line 48 of file VESubtarget.h.
References llvm::VEInstrInfo::getRegisterInfo().
Referenced by llvm::VEFrameLowering::emitPrologue(), and llvm::VETargetLowering::VETargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo* llvm::VESubtarget::getSelectionDAGInfo () const inline override
Definition at line 52 of file VESubtarget.h.
References enableMachineScheduler(), getAdjustedFrameSize(), initializeSubtargetDependencies(), and ParseSubtargetFeatures().
getTargetLowering()
const VETargetLowering* llvm::VESubtarget::getTargetLowering () const inline override
Definition at line 51 of file VESubtarget.h.
initializeSubtargetDependencies()
VESubtarget & VESubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 28 of file VESubtarget.cpp.
References ParseSubtargetFeatures().
Referenced by getSelectionDAGInfo().
isTargetLinux()
bool llvm::VESubtarget::isTargetLinux () const inline
Definition at line 68 of file VESubtarget.h.
References llvm::Triple::isOSLinux().
ParseSubtargetFeatures()
void llvm::VESubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
Referenced by getSelectionDAGInfo(), and initializeSubtargetDependencies().
The documentation for this class was generated from the following files:
lib/Target/VE/VESubtarget.h
lib/Target/VE/VESubtarget.cpp