LLVM: llvm::DwarfCompileUnit Class Reference
llvm::DwarfCompileUnit Class Reference final
#include "CodeGen/AsmPrinter/DwarfCompileUnit.h"
Classes
struct BaseTypeRef
struct GlobalExpr
A pair of GlobalVariable and DIExpression.
Public Types
using InlinedEntity = DbgValueHistoryMap::InlinedEntity
Find abstract variable associated with Var.
Public Member Functions
DwarfCompileUnit (unsigned UID, const DICompileUnit *Node, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU, UnitKind Kind=UnitKind::Full)
bool hasRangeLists () const
unsigned getUniqueID () const
DwarfCompileUnit * getSkeleton () const
bool includeMinimalInlineScopes () const
void initStmtList ()
void applyStmtList (DIE &D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
DIE * getOrCreateGlobalVariableDIE (const DIGlobalVariable *GV, ArrayRef< GlobalExpr > GlobalExprs)
Get or create global variable DIE.
DIE * getOrCreateCommonBlock (const DICommonBlock *CB, ArrayRef< GlobalExpr > GlobalExprs)
void addLocationAttribute (DIE *ToDIE, const DIGlobalVariable *GV, ArrayRef< GlobalExpr > GlobalExprs)
void addLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
addLabelAddress - Add a dwarf label attribute data and value using either DW_FORM_addr or DW_FORM_GNU_addr_index.
void addLocalLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
addLocalLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr only.
DwarfCompileUnit & getCU () override
unsigned getOrCreateSourceID (const DIFile *File) override
Look up the source ID for the given file.
void addImportedEntity (const DIImportedEntity *IE)
void addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
void attachLowHighPC (DIE &D, const MCSymbol *Begin, const MCSymbol *End)
DIE & updateSubprogramScopeDIE (const DISubprogram *SP)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc and DW_AT_high_pc attributes.
void constructScopeDIE (LexicalScope *Scope, SmallVectorImpl< DIE *> &FinalChildren)
void addScopeRangeList (DIE &ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
void attachRangesOrLowHighPC (DIE &D, SmallVector< RangeSpan, 2 > Ranges)
void attachRangesOrLowHighPC (DIE &D, const SmallVectorImpl< InsnRange > &Ranges)
DIE * constructInlinedScopeDIE (LexicalScope *Scope)
This scope represents inlined body of a function.
DIE * constructLexicalScopeDIE (LexicalScope *Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
DIE * constructVariableDIE (DbgVariable &DV, bool Abstract=false)
constructVariableDIE - Construct a DIE for the given DbgVariable.
DIE * constructVariableDIE (DbgVariable &DV, const LexicalScope &Scope, DIE *&ObjectPointer)
DIE * constructLabelDIE (DbgLabel &DL, const LexicalScope &Scope)
Construct a DIE for the given DbgLabel.
DIE * createScopeChildrenDIE (LexicalScope *Scope, SmallVectorImpl< DIE *> &Children, bool *HasNonScopeChildren=nullptr)
A helper function to create children of a Scope DIE.
void createBaseTypeDIEs ()
DIE & constructSubprogramScopeDIE (const DISubprogram *Sub, LexicalScope *Scope)
Construct a DIE for this subprogram scope.
DIE * createAndAddScopeChildren (LexicalScope *Scope, DIE &ScopeDIE)
void constructAbstractSubprogramScopeDIE (LexicalScope *Scope)
dwarf::Tag getDwarf5OrGNUTag (dwarf::Tag Tag) const
This takes a DWARF 5 tag and returns it or a GNU analog.
dwarf::Attribute getDwarf5OrGNUAttr (dwarf::Attribute Attr) const
This takes a DWARF 5 attribute and returns it or a GNU analog.
dwarf::LocationAtom getDwarf5OrGNULocationAtom (dwarf::LocationAtom Loc) const
This takes a DWARF 5 location atom and either returns it or a GNU analog.
DIE & constructCallSiteEntryDIE (DIE &ScopeDIE, const DISubprogram *CalleeSP, bool IsTail, const MCSymbol *PCAddr, const MCExpr *PCOffset, unsigned CallReg)
Construct a call site entry DIE describing a call within Scope to a callee described by CalleeSP.
void constructCallSiteParmEntryDIEs (DIE &CallSiteDIE, SmallVector< DbgCallSiteParam, 4 > &Params)
Construct call site parameter DIEs for the CallSiteDIE.
DIE * constructImportedEntityDIE (const DIImportedEntity *Module)
Construct import_module DIE.
void finishSubprogramDefinition (const DISubprogram *SP)
void finishEntityDefinition (const DbgEntity *Entity)
DbgEntity * getExistingAbstractEntity (const DINode *Node)
void createAbstractEntity (const DINode *Node, LexicalScope *Scope)
void setSkeleton (DwarfCompileUnit &Skel)
Set the skeleton unit associated with this unit.
unsigned getHeaderSize () const override
Compute the size of a header for this unit, not including the initial length field.
unsigned getLength ()
void emitHeader (bool UseOffsets) override
Emit the header for this unit, not including the initial length field.
void addAddrTableBase ()
Add the DW_AT_addr_base attribute to the unit DIE.
MCSymbol * getLabelBegin () const
MCSymbol * getMacroLabelBegin () const
void addGlobalName (StringRef Name, const DIE &Die, const DIScope *Context) override
Add a new global name to the compile unit.
void addGlobalNameForTypeUnit (StringRef Name, const DIScope *Context)
Add a new global name present in a type unit to this compile unit.
void addGlobalType (const DIType *Ty, const DIE &Die, const DIScope *Context) override
Add a new global type to the compile unit.
void addGlobalTypeUnitType (const DIType *Ty, const DIScope *Context)
Add a new global type present in a type unit to this compile unit.
const StringMap< const DIE * > & getGlobalNames () const
const StringMap< const DIE * > & getGlobalTypes () const
void addVariableAddress (const DbgVariable &DV, DIE &Die, MachineLocation Location)
Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
void addAddress (DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
Add an address attribute to a die based on the location provided.
void addComplexAddress (const DbgVariable &DV, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable (navigating the extra location information encoded in the type) based on the starting location.
void addLocationList (DIE &Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
void applyVariableAttributes (const DbgVariable &Var, DIE &VariableDie)
void addExpr (DIELoc &Die, dwarf::Form Form, const MCExpr *Expr)
Add a Dwarf expression attribute data and value.
void addAddressExpr (DIE &Die, dwarf::Attribute Attribute, const MCExpr *Expr)
Add an attribute containing an address expression to Die.
void applySubprogramAttributesToDefinition (const DISubprogram *SP, DIE &SPDie)
void applyLabelAttributes (const DbgLabel &Label, DIE &LabelDie)
const SmallVectorImpl< RangeSpan > & getRanges () const
getRanges - Get the list of ranges for this unit.
SmallVector< RangeSpan, 2 > takeRanges ()
void setBaseAddress (const MCSymbol *Base)
const MCSymbol * getBaseAddress () const
uint64_t getDWOId () const
void setDWOId (uint64_t DwoId)
bool hasDwarfPubSections () const
void addBaseTypeRef (DIEValueList &Die, int64_t Idx)
Public Member Functions inherited from llvm::DwarfUnit
AsmPrinter * getAsmPrinter () const
MCSymbol * getEndLabel () const
uint16_t getLanguage () const
const DICompileUnit * getCUNode () const
uint16_t getDwarfVersion () const
bool hasContent () const
Return true if this compile unit has something to write out.
std::string getParentContextString (const DIScope *Context) const
Get string containing language specific context for a global name.
DIE * getDIE (const DINode *D) const
Returns the DIE map slot for the specified debug variable.
DIELoc * getDIELoc ()
Returns a fresh newly allocated DIELoc.
void insertDIE (const DINode *Desc, DIE *D)
Insert DIE into the map.
void insertDIE (DIE *D)
void addFlag (DIE &Die, dwarf::Attribute Attribute)
Add a flag that is true to the DIE.
void addUInt (DIEValueList &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
Add an unsigned integer attribute data and value.
void addUInt (DIEValueList &Block, dwarf::Form Form, uint64_t Integer)
void addSInt (DIEValueList &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
Add an signed integer attribute data and value.
void addSInt (DIELoc &Die, Optional< dwarf::Form > Form, int64_t Integer)
void addString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
DIEValueList::value_iterator addLabel (DIEValueList &Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol *Label)
Add a Dwarf label attribute data and value.
void addLabel (DIELoc &Die, dwarf::Form Form, const MCSymbol *Label)
void addSectionOffset (DIE &Die, dwarf::Attribute Attribute, uint64_t Integer)
Add an offset into a section attribute data and value.
void addOpAddress (DIELoc &Die, const MCSymbol *Sym)
Add a dwarf op address data and value using the form given and an op of either DW_FORM_addr or DW_FORM_GNU_addr_index.
void addLabelDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
Add a label delta attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIE &Entry)
Add a DIE attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIEEntry Entry)
Add a DIE attribute data and value.
void addDIETypeSignature (DIE &Die, uint64_t Signature)
Add a type's DW_AT_signature and set the declaration flag.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIELoc *Loc)
Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIEBlock *Block)
Add block data.
void addSourceLine (DIE &Die, unsigned Line, const DIFile *File)
Add location information to specified debug information entry.
void addSourceLine (DIE &Die, const DILocalVariable *V)
void addSourceLine (DIE &Die, const DIGlobalVariable *G)
void addSourceLine (DIE &Die, const DISubprogram *SP)
void addSourceLine (DIE &Die, const DILabel *L)
void addSourceLine (DIE &Die, const DIType *Ty)
void addSourceLine (DIE &Die, const DIObjCProperty *Ty)
void addConstantValue (DIE &Die, const MachineOperand &MO, const DIType *Ty)
Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const ConstantInt *CI, const DIType *Ty)
void addConstantValue (DIE &Die, const APInt &Val, const DIType *Ty)
void addConstantValue (DIE &Die, const APInt &Val, bool Unsigned)
void addConstantValue (DIE &Die, uint64_t Val, const DIType *Ty)
void addConstantValue (DIE &Die, bool Unsigned, uint64_t Val)
void addConstantFPValue (DIE &Die, const MachineOperand &MO)
Add constant value entry in variable DIE.
void addConstantFPValue (DIE &Die, const ConstantFP *CFP)
void addLinkageName (DIE &Die, StringRef LinkageName)
Add a linkage name, if it isn't empty.
void addTemplateParams (DIE &Buffer, DINodeArray TParams)
Add template parameters in buffer.
void addThrownTypes (DIE &Die, DINodeArray ThrownTypes)
Add thrown types.
void addType (DIE &Entity, const DIType *Ty, dwarf::Attribute Attribute=dwarf::DW_AT_type)
Add a new type attribute to the specified entity.
DIE * getOrCreateNameSpace (const DINamespace *NS)
DIE * getOrCreateModule (const DIModule *M)
DIE * getOrCreateSubprogramDIE (const DISubprogram *SP, bool Minimal=false)
void applySubprogramAttributes (const DISubprogram *SP, DIE &SPDie, bool SkipSPAttributes=false)
DIE * createTypeDIE (const DIScope *Context, DIE &ContextDIE, const DIType *Ty)
Creates type DIE with specific context.
DIE * getOrCreateTypeDIE (const MDNode *TyNode)
Find existing DIE or create new DIE for the given type.
DIE * getOrCreateContextDIE (const DIScope *Context)
Get context owner's DIE.
void constructContainingTypeDIEs ()
Construct DIEs for types that contain vtables.
void constructSubprogramArguments (DIE &Buffer, DITypeRefArray Args)
Construct function argument DIEs.
DIE & createAndAddDIE (unsigned Tag, DIE &Parent, const DINode *N=nullptr)
Create a DIE with the given Tag, add the DIE to its parent, and call insertDIE if MD is not null.
bool useSegmentedStringOffsetsTable () const
void addStringOffsetsStart ()
Add the DW_AT_str_offsets_base attribute to the unit DIE.
void addRnglistsBase ()
Add the DW_AT_rnglists_base attribute to the unit DIE.
void constructTypeDIE (DIE &Buffer, const DICompositeType *CTy)
DIE::value_iterator addSectionDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addSectionDelta - Add a label delta attribute data and value.
DIE::value_iterator addSectionLabel (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label, const MCSymbol *Sec)
Add a Dwarf section label attribute data and value.
Optional< MD5::MD5Result > getMD5AsBytes (const DIFile *File) const
If the File has an MD5 checksum, return it as an MD5Result allocated in the MCContext.
DIE * createTypeDIE (const DICompositeType *Ty)
Get context owner's DIE.
Public Member Functions inherited from llvm::DIEUnit
DIEUnit (uint16_t Version, uint8_t AddrSize, dwarf::Tag UnitTag)
DIEUnit (const DIEUnit &RHS)=delete
DIEUnit (DIEUnit &&RHS)=delete
void operator= (const DIEUnit &RHS)=delete
void operator= (const DIEUnit &&RHS)=delete
void setSection (MCSection *Section)
Set the section that this DIEUnit will be emitted into.
MCSection * getSection () const
Return the section that this DIEUnit will be emitted into.
void setDebugSectionOffset (unsigned O)
unsigned getDebugSectionOffset () const
void setLength (uint64_t L)
uint64_t getLength () const
uint16_t getDwarfVersion () const
uint16_t getAddressSize () const
DIE & getUnitDie ()
const DIE & getUnitDie () const
Public Attributes
std::vector< BaseTypeRef > ExprRefedBaseTypes
Additional Inherited Members
Protected Member Functions inherited from llvm::DwarfUnit
DwarfUnit (dwarf::Tag, const DICompileUnit *Node, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
bool applySubprogramDefinitionAttributes (const DISubprogram *SP, DIE &SPDie)
bool shareAcrossDWOCUs () const
bool isShareableAcrossCUs (const DINode *D) const
Check whether the DIE for this MDNode can be shared across CUs.
~DwarfUnit ()
DIE * getOrCreateStaticMemberDIE (const DIDerivedType *DT)
Create new static data member DIE.
void emitCommonHeader (bool UseOffsets, dwarf::UnitType UT)
Emit the common part of the header for this unit.
Protected Member Functions inherited from llvm::DIEUnit
virtual ~DIEUnit ()=default
The size in bytes of an address for this unit.
Protected Attributes inherited from llvm::DwarfUnit
const DICompileUnit * CUNode
MDNode for the compile unit.
BumpPtrAllocator DIEValueAllocator
AsmPrinter * Asm
Target of Dwarf emission.
MCSymbol * EndLabel = nullptr
Emitted at the end of the CU and used to compute the CU Length field.
DwarfDebug * DD
DwarfFile * DU
DIE * IndexTyDie
An anonymous type for index type. Owned by DIEUnit.
DenseMap< const MDNode *, DIE * > MDNodeToDieMap
Tracks the mapping of unit level debug information variables to debug information entries.
std::vector< DIEBlock * > DIEBlocks
A list of all the DIEBlocks in use.
std::vector< DIELoc * > DIELocs
A list of all the DIELocs in use.
DenseMap< DIE *, const DINode * > ContainingTypeMap
This map is used to keep track of subprogram DIEs that need DW_AT_containing_type attribute.
Detailed Description
Definition at line 45 of file DwarfCompileUnit.h.
Member Typedef Documentation
InlinedEntity
using llvm::DwarfCompileUnit::InlinedEntity = DbgValueHistoryMap::InlinedEntity
Find abstract variable associated with Var.
Definition at line 270 of file DwarfCompileUnit.h.
Constructor & Destructor Documentation
DwarfCompileUnit()
DwarfCompileUnit::DwarfCompileUnit (unsigned UID, const DICompileUnit * Node, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU, UnitKind Kind = UnitKind::Full)
Definition at line 68 of file DwarfCompileUnit.cpp.
Member Function Documentation
addAddress()
void DwarfCompileUnit::addAddress (DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Add an address attribute to a die based on the location provided.
Definition at line 1190 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfExpression::addExpression(), llvm::DwarfExpression::addMachineRegExpression(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DIEValueAllocator, llvm::DIEDwarfExpression::finalize(), llvm::MachineLocation::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineLocation::isIndirect(), llvm::AsmPrinter::MF, llvm::DwarfExpression::setMemoryLocationKind(), llvm::DwarfExpression::TagOffset, and TRI.
Referenced by addVariableAddress(), constructCallSiteEntryDIE(), constructCallSiteParmEntryDIEs(), and updateSubprogramScopeDIE().
addAddressExpr()
void DwarfCompileUnit::addAddressExpr (DIE & Die, dwarf::Attribute Attribute, const MCExpr * Expr)
Add an attribute containing an address expression to Die.
Definition at line 1288 of file DwarfCompileUnit.cpp.
References llvm::DIEValueList::addValue(), and llvm::DwarfUnit::DIEValueAllocator.
Referenced by constructCallSiteEntryDIE().
addAddrTableBase()
void DwarfCompileUnit::addAddrTableBase ()
Add the DW_AT_addr_base attribute to the unit DIE.
Definition at line 1315 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::DwarfDebug::getAddressPool(), llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfAddrSection(), llvm::DwarfUnit::getDwarfVersion(), llvm::AddressPool::getLabel(), llvm::AsmPrinter::getObjFileLowering(), and llvm::DIEUnit::getUnitDie().
addBaseTypeRef()
void DwarfCompileUnit::addBaseTypeRef (DIEValueList & Die, int64_t Idx)
Definition at line 1324 of file DwarfCompileUnit.cpp.
References llvm::DIEValueList::addValue(), and llvm::DwarfUnit::DIEValueAllocator.
addComplexAddress()
void DwarfCompileUnit::addComplexAddress (const DbgVariable & DV, DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable (navigating the extra location information encoded in the type) based on the starting location.
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable given the extra address information encoded in the DbgVariable, starting from the starting location.
Add the DWARF information to the die.
Definition at line 1215 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfExpression::addExpression(), llvm::DwarfExpression::addFragmentOffset(), llvm::DwarfExpression::addMachineRegExpression(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, llvm::DwarfExpression::beginEntryValueExpression(), llvm::DwarfUnit::DIEValueAllocator, llvm::DIEDwarfExpression::finalize(), llvm::MachineLocation::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::DbgVariable::getSingleExpression(), llvm::MachineFunction::getSubtarget(), llvm::DIExpression::isEntryValue(), llvm::MachineLocation::isIndirect(), llvm::AsmPrinter::MF, llvm::DwarfExpression::setEntryValueFlag(), llvm::DwarfExpression::setMemoryLocationKind(), llvm::DwarfExpression::TagOffset, and TRI.
Referenced by addVariableAddress().
addExpr()
void DwarfCompileUnit::addExpr (DIELoc & Die, dwarf::Form Form, const MCExpr * Expr)
Add a Dwarf expression attribute data and value.
Definition at line 1283 of file DwarfCompileUnit.cpp.
References llvm::DIEValueList::addValue(), and llvm::DwarfUnit::DIEValueAllocator.
Referenced by addLocationAttribute().
addGlobalName()
void DwarfCompileUnit::addGlobalName (StringRef Name, const DIE & Die, const DIScope * Context) override virtual
Add a new global name to the compile unit.
addGlobalName - Add a new global name to the compile unit.
Implements llvm::DwarfUnit.
Definition at line 1140 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), hasDwarfPubSections(), and llvm::StringRef::str().
Referenced by applySubprogramAttributesToDefinition(), getOrCreateCommonBlock(), and getOrCreateGlobalVariableDIE().
addGlobalNameForTypeUnit()
void DwarfCompileUnit::addGlobalNameForTypeUnit (StringRef Name, const DIScope * Context)
Add a new global name present in a type unit to this compile unit.
Definition at line 1148 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), llvm::DIEUnit::getUnitDie(), hasDwarfPubSections(), and llvm::StringRef::str().
Referenced by llvm::DwarfTypeUnit::addGlobalName().
addGlobalType()
void DwarfCompileUnit::addGlobalType (const DIType * Ty, const DIE & Die, const DIScope * Context) override virtual
Add a new global type to the compile unit.
Add a new global type to the unit.
Implements llvm::DwarfUnit.
Definition at line 1161 of file DwarfCompileUnit.cpp.
References llvm::DIType::getName(), llvm::DwarfUnit::getParentContextString(), hasDwarfPubSections(), and llvm::StringRef::str().
addGlobalTypeUnitType()
void DwarfCompileUnit::addGlobalTypeUnitType (const DIType * Ty, const DIScope * Context)
Add a new global type present in a type unit to this compile unit.
Definition at line 1169 of file DwarfCompileUnit.cpp.
References llvm::DIType::getName(), llvm::DwarfUnit::getParentContextString(), llvm::DIEUnit::getUnitDie(), hasDwarfPubSections(), and llvm::StringRef::str().
Referenced by llvm::DwarfTypeUnit::addGlobalType().
addImportedEntity()
void llvm::DwarfCompileUnit::addImportedEntity (const DIImportedEntity * IE) inline
Definition at line 167 of file DwarfCompileUnit.h.
References addRange(), assert(), and llvm::DIImportedEntity::getScope().
addLabelAddress()
void DwarfCompileUnit::addLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLabelAddress - Add a dwarf label attribute data and value using either DW_FORM_addr or DW_FORM_GNU_addr_index.
addLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr or DW_FORM_GNU_addr_index.
Definition at line 78 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::addArangeLabel(), addLocalLabelAddress(), llvm::DIEValueList::addValue(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::DwarfDebug::getAddressPool(), llvm::DwarfDebug::getDwarfVersion(), llvm::AddressPool::getIndex(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by constructCallSiteEntryDIE(), and finishEntityDefinition().
addLocalLabelAddress()
void DwarfCompileUnit::addLocalLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLocalLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr only.
Definition at line 94 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::addArangeLabel(), llvm::DIEValueList::addValue(), llvm::DwarfUnit::DD, and llvm::DwarfUnit::DIEValueAllocator.
Referenced by addLabelAddress().
addLocationAttribute()
void DwarfCompileUnit::addLocationAttribute (DIE * ToDIE, const DIGlobalVariable * GV, ArrayRef< GlobalExpr > GlobalExprs)
Definition at line 185 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::addAccelName(), llvm::DwarfDebug::addArangeLabel(), llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addConstantValue(), addExpr(), llvm::DwarfUnit::addLinkageName(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, assert(), llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::DIExpression::extractAddressClass(), llvm::AArch64CC::GE, llvm::DwarfDebug::getAddressPool(), llvm::AsmPrinter::getDataLayout(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::DIExpression::getElement(), llvm::AddressPool::getIndex(), llvm::DIGlobalVariable::getLinkageName(), llvm::DIVariable::getName(), llvm::AsmPrinter::getObjFileLowering(), llvm::DataLayout::getPointerSize(), llvm::AsmPrinter::getSymbol(), llvm::TargetMachine::getTargetTriple(), llvm::GlobalValue::hasDLLImportStorageClass(), llvm::DIExpression::isConstant(), llvm::Triple::isNVPTX(), llvm::GlobalValue::isThreadLocal(), llvm::TargetLoweringObjectFile::supportDebugThreadLocalLocation(), llvm::AsmPrinter::TM, llvm::DwarfDebug::tuneForGDB(), llvm::DwarfDebug::useAllLinkageNames(), llvm::TargetMachine::useEmulatedTLS(), llvm::DwarfDebug::useGNUTLSOpcode(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by getOrCreateCommonBlock(), and getOrCreateGlobalVariableDIE().
addLocationList()
void DwarfCompileUnit::addLocationList (DIE & Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
Definition at line 1246 of file DwarfCompileUnit.cpp.
References llvm::DIEValueList::addValue(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, and llvm::DwarfDebug::getDwarfVersion().
Referenced by constructLabelDIE().
addRange()
void DwarfCompileUnit::addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
Definition at line 330 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm::RangeSpan::End, llvm::DwarfDebug::getPrevCU(), llvm::MCSymbol::getSection(), and llvm::DwarfDebug::setPrevCU().
Referenced by addScopeRangeList().
addScopeRangeList()
void DwarfCompileUnit::addScopeRangeList (DIE & ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
Definition at line 477 of file DwarfCompileUnit.cpp.
References addRange(), llvm::DwarfUnit::addSectionDelta(), llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::DwarfUnit::DU, llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfRangesSection(), llvm::DwarfDebug::getDwarfVersion(), llvm::AsmPrinter::getObjFileLowering(), and List.
Referenced by attachRangesOrLowHighPC().
addVariableAddress()
void DwarfCompileUnit::addVariableAddress (const DbgVariable & DV, DIE & Die, MachineLocation Location)
Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
Definition at line 1181 of file DwarfCompileUnit.cpp.
References addAddress(), addComplexAddress(), and llvm::DbgVariable::hasComplexAddress().
Referenced by constructLabelDIE().
applyLabelAttributes()
void DwarfCompileUnit::applyLabelAttributes (const DbgLabel & Label, DIE & LabelDie)
Definition at line 1273 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::StringRef::empty(), llvm::DbgLabel::getLabel(), llvm::DbgLabel::getName(), and Name.
Referenced by constructLabelDIE(), and finishEntityDefinition().
applyStmtList()
void DwarfCompileUnit::applyStmtList (DIE & D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
Definition at line 371 of file DwarfCompileUnit.cpp.
References llvm::DIEValueList::addValue(), and llvm::DwarfUnit::DIEValueAllocator.
applySubprogramAttributesToDefinition()
void DwarfCompileUnit::applySubprogramAttributesToDefinition (const DISubprogram * SP, DIE & SPDie)
Definition at line 1294 of file DwarfCompileUnit.cpp.
References addGlobalName(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfUnit::constructTypeDIE(), Context, D, llvm::DwarfUnit::DD, llvm::DIScope::getName(), llvm::DIScope::getScope(), includeMinimalInlineScopes(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by constructAbstractSubprogramScopeDIE(), and finishSubprogramDefinition().
applyVariableAttributes()
void DwarfCompileUnit::applyVariableAttributes (const DbgVariable & Var, DIE & VariableDie)
Definition at line 1256 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addType(), llvm::DwarfUnit::addUInt(), llvm::StringRef::empty(), llvm::DbgVariable::getName(), llvm::DbgVariable::getType(), llvm::DbgVariable::getVariable(), llvm::DbgVariable::isArtificial(), and Name.
Referenced by constructLabelDIE(), and finishEntityDefinition().
attachLowHighPC()
void DwarfCompileUnit::attachLowHighPC (DIE & D, const MCSymbol * Begin, const MCSymbol * End)
Definition at line 375 of file DwarfCompileUnit.cpp.
Referenced by attachRangesOrLowHighPC(), and updateSubprogramScopeDIE().
attachRangesOrLowHighPC() [1/2]
void DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, SmallVector< RangeSpan, 2 > Ranges)
Definition at line 510 of file DwarfCompileUnit.cpp.
References addScopeRangeList(), attachLowHighPC(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::RangeSpan::Begin, llvm::DwarfUnit::DD, llvm::RangeSpan::End, llvm::SmallVectorTemplateCommon< T >::front(), llvm::SmallVectorBase::size(), and llvm::DwarfDebug::useRangesSection().
Referenced by attachRangesOrLowHighPC(), constructInlinedScopeDIE(), and constructLexicalScopeDIE().
attachRangesOrLowHighPC() [2/2]
void DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, const SmallVectorImpl< InsnRange > & Ranges)
Definition at line 520 of file DwarfCompileUnit.cpp.
References attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::DebugHandlerBase::getLabelAfterInsn(), llvm::DebugHandlerBase::getLabelBeforeInsn(), List, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorBase::size().
constructAbstractSubprogramScopeDIE()
void DwarfCompileUnit::constructAbstractSubprogramScopeDIE (LexicalScope * Scope)
Definition at line 868 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addUInt(), applySubprogramAttributesToDefinition(), llvm::DwarfUnit::createAndAddDIE(), createAndAddScopeChildren(), llvm::DwarfUnit::DD, llvm::dwarf::DW_INL_inlined, llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::LexicalScope::getScopeNode(), llvm::DIEUnit::getUnitDie(), includeMinimalInlineScopes(), llvm::DwarfDebug::lookupCU(), and llvm::None.
Referenced by llvm::DwarfDebug::shareAcrossDWOCUs().
constructCallSiteEntryDIE()
DIE & DwarfCompileUnit::constructCallSiteEntryDIE (DIE & ScopeDIE, const DISubprogram * CalleeSP, bool IsTail, const MCSymbol * PCAddr, const MCExpr * PCOffset, unsigned CallReg)
Construct a call site entry DIE describing a call within Scope to a callee described by CalleeSP.
IsTail specifies whether the call is a tail call. PCAddr (used for GDB + DWARF 4 tuning) points to the PC value after the call instruction. PCOffset (used for cases other than GDB + DWARF 4 tuning) must be non-zero for non-tail calls (in the case of non-gdb tuning, since for GDB + DWARF 5 tuning we still generate PC info for tail calls) or be the function-local offset to PC value after the call instruction. CallReg is a register location for an indirect call. For direct calls the CallReg is set to 0.
Definition at line 959 of file DwarfCompileUnit.cpp.
References addAddress(), addAddressExpr(), llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addFlag(), addLabelAddress(), assert(), llvm::DwarfUnit::createAndAddDIE(), llvm::DwarfUnit::DD, getDwarf5OrGNUAttr(), getDwarf5OrGNUTag(), llvm::DwarfDebug::getDwarfVersion(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), and llvm::DwarfDebug::tuneForGDB().
Referenced by collectCallSiteParameters().
constructCallSiteParmEntryDIEs()
void DwarfCompileUnit::constructCallSiteParmEntryDIEs (DIE & CallSiteDIE, SmallVector< DbgCallSiteParam, 4 > & Params)
Construct call site parameter DIEs for the CallSiteDIE.
The Params were collected by the collectCallSiteParameters. Note: The order of parameters does not matter, since debuggers recognize call site parameters by the DW_AT_location attribute.
Definition at line 994 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addBlock(), llvm::DIE::addChild(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DIEValueAllocator, llvm::DwarfDebug::emitDebugLocValue(), llvm::DIEDwarfExpression::finalize(), llvm::DIE::get(), getDwarf5OrGNUAttr(), getDwarf5OrGNUTag(), llvm::DwarfUnit::insertDIE(), and llvm::DwarfExpression::setCallSiteParamValueFlag().
Referenced by collectCallSiteParameters().
constructImportedEntityDIE()
DIE * DwarfCompileUnit::constructImportedEntityDIE (const DIImportedEntity * Module)
Construct import_module DIE.
Definition at line 1018 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), assert(), llvm::DwarfUnit::DIEValueAllocator, llvm::StringRef::empty(), llvm::DIE::get(), llvm::DwarfUnit::getDIE(), llvm::DIImportedEntity::getEntity(), llvm::DIImportedEntity::getFile(), llvm::DIImportedEntity::getLine(), llvm::DIImportedEntity::getName(), getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateModule(), llvm::DwarfUnit::getOrCreateNameSpace(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DINode::getTag(), llvm::DwarfUnit::insertDIE(), and Name.
Referenced by collectCallSiteParameters(), and createScopeChildrenDIE().
constructInlinedScopeDIE()
DIE * DwarfCompileUnit::constructInlinedScopeDIE (LexicalScope * Scope)
This scope represents inlined body of a function.
Construct DIE to represent this concrete inlined copy of the function.
Definition at line 532 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfDebug::addSubprogramNames(), llvm::DwarfUnit::addUInt(), assert(), attachRangesOrLowHighPC(), llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::SIInstrFlags::DS, llvm::DIE::get(), llvm::getDISubprogram(), llvm::DwarfDebug::getDwarfVersion(), llvm::LexicalScope::getInlinedAt(), getOrCreateSourceID(), llvm::LexicalScope::getRanges(), llvm::LexicalScope::getScopeNode(), and llvm::None.
Referenced by constructScopeDIE().
constructLabelDIE()
DIE * DwarfCompileUnit::constructLabelDIE (DbgLabel & DL, const LexicalScope & Scope)
Construct a DIE for the given DbgLabel.
Definition at line 586 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addConstantFPValue(), llvm::DwarfUnit::addConstantValue(), llvm::DwarfExpression::addExpression(), llvm::DwarfExpression::addFragmentOffset(), addLocationList(), llvm::DwarfExpression::addMachineRegExpression(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addUInt(), llvm::DwarfExpression::addUnsignedConstant(), addVariableAddress(), llvm::SmallVectorImpl< T >::append(), llvm::DIExpression::appendOffset(), applyLabelAttributes(), applyVariableAttributes(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::DIExpression::elements_begin(), llvm::DIExpression::elements_end(), llvm::DIExpression::extractAddressClass(), llvm::DIEDwarfExpression::finalize(), llvm::DIE::get(), llvm::DbgVariable::getDebugLocListIndex(), llvm::DbgVariable::getDebugLocListTagOffset(), llvm::DbgVariable::getFrameIndexExprs(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::AsmPrinter::getFunctionFrameSymbol(), llvm::DbgLabel::getLabel(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::DbgVariable::getSingleExpression(), llvm::MachineFunction::getSubtarget(), llvm::DbgVariable::getTag(), llvm::DbgLabel::getTag(), llvm::TargetMachine::getTargetTriple(), llvm::DbgVariable::getType(), llvm::DbgVariable::getValueLoc(), llvm::DbgVariable::getVariable(), llvm::DbgVariable::hasFrameIndexExprs(), llvm::DwarfUnit::insertDIE(), llvm::LexicalScope::isAbstractScope(), llvm::Triple::isNVPTX(), llvm::AsmPrinter::MF, llvm::DbgEntity::setDIE(), llvm::DwarfExpression::setMemoryLocationKind(), llvm::DwarfExpression::TagOffset, llvm::AsmPrinter::TM, and llvm::DwarfDebug::tuneForGDB().
Referenced by createScopeChildrenDIE().
constructLexicalScopeDIE()
DIE * DwarfCompileUnit::constructLexicalScopeDIE (LexicalScope * Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
Definition at line 566 of file DwarfCompileUnit.cpp.
References attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::DIE::get(), llvm::LexicalScope::getRanges(), llvm::LexicalScope::isAbstractScope(), and llvm::DwarfDebug::isLexicalScopeDIENull().
Referenced by constructScopeDIE().
constructScopeDIE()
void DwarfCompileUnit::constructScopeDIE (LexicalScope * Scope, SmallVectorImpl< DIE *> & FinalChildren)
Definition at line 423 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), assert(), constructInlinedScopeDIE(), constructLexicalScopeDIE(), createScopeChildrenDIE(), llvm::DwarfUnit::DD, llvm::SIInstrFlags::DS, llvm::SmallVectorTemplateCommon< T >::end(), llvm::LexicalScope::getInlinedAt(), llvm::LexicalScope::getParent(), llvm::LexicalScope::getScopeNode(), I, llvm::SmallVectorImpl< T >::insert(), llvm::DwarfDebug::isLexicalScopeDIENull(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by createScopeChildrenDIE().
constructSubprogramScopeDIE()
DIE & DwarfCompileUnit::constructSubprogramScopeDIE (const DISubprogram * Sub, LexicalScope * Scope)
Construct a DIE for this subprogram scope.
Definition at line 827 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), llvm::DwarfUnit::addDIEEntry(), assert(), createAndAddScopeChildren(), llvm::DwarfUnit::DIEValueAllocator, llvm::DIE::get(), llvm::LexicalScope::getInlinedAt(), includeMinimalInlineScopes(), llvm::LexicalScope::isAbstractScope(), llvm::DITypeRefArray::size(), and updateSubprogramScopeDIE().
constructVariableDIE() [1/2]
DIE * DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, bool Abstract = false)
constructVariableDIE - Construct a DIE for the given DbgVariable.
Definition at line 580 of file DwarfCompileUnit.cpp.
References D, and llvm::DbgEntity::setDIE().
Referenced by constructVariableDIE(), and createScopeChildrenDIE().
constructVariableDIE() [2/2]
DIE * DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, const LexicalScope & Scope, DIE *& ObjectPointer)
Definition at line 707 of file DwarfCompileUnit.cpp.
References constructVariableDIE(), llvm::LexicalScope::isAbstractScope(), and llvm::DbgVariable::isObjectPointer().
createAbstractEntity()
void DwarfCompileUnit::createAbstractEntity (const DINode * Node, LexicalScope * Scope)
Definition at line 1092 of file DwarfCompileUnit.cpp.
createAndAddScopeChildren()
DIE * DwarfCompileUnit::createAndAddScopeChildren (LexicalScope * Scope, DIE & ScopeDIE)
Definition at line 855 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), createScopeChildrenDIE(), and I.
Referenced by constructAbstractSubprogramScopeDIE(), and constructSubprogramScopeDIE().
createBaseTypeDIEs()
void DwarfCompileUnit::createBaseTypeDIEs ()
Definition at line 1329 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChildFront(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addUInt(), llvm::dwarf::AttributeEncodingString(), llvm::DwarfUnit::DIEValueAllocator, ExprRefedBaseTypes, llvm::DIE::get(), llvm::DIEUnit::getUnitDie(), llvm::None, llvm::reverse(), and llvm::Twine::toStringRef().
Referenced by llvm::DwarfDebug::endModule().
createScopeChildrenDIE()
DIE * DwarfCompileUnit::createScopeChildrenDIE (LexicalScope * Scope, SmallVectorImpl< DIE *> & Children, bool * HasNonScopeChildren = nullptr)
A helper function to create children of a Scope DIE.
Definition at line 791 of file DwarfCompileUnit.cpp.
References assert(), constructImportedEntityDIE(), constructLabelDIE(), constructScopeDIE(), constructVariableDIE(), llvm::DwarfUnit::DU, llvm::SmallVectorBase::empty(), llvm::LexicalScope::getChildren(), llvm::DwarfFile::getScopeLabels(), llvm::LexicalScope::getScopeNode(), llvm::DwarfFile::getScopeVariables(), llvm::ARM_PROC::IE, includeMinimalInlineScopes(), llvm::AArch64CC::LS, llvm::SmallVectorTemplateBase< T >::push_back(), and sortLocalVars().
Referenced by constructScopeDIE(), and createAndAddScopeChildren().
emitHeader()
void DwarfCompileUnit::emitHeader (bool UseOffsets) override virtual
Emit the header for this unit, not including the initial length field.
Implements llvm::DwarfUnit.
Definition at line 1107 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, llvm::AsmPrinter::createTempSymbol(), llvm::DwarfUnit::DD, llvm::DwarfUnit::emitCommonHeader(), llvm::AsmPrinter::emitInt64(), llvm::DwarfDebug::getDwarfVersion(), getDWOId(), llvm::AsmPrinter::OutStreamer, llvm::DwarfDebug::useSectionsAsReferences(), and llvm::DwarfDebug::useSplitDwarf().
finishEntityDefinition()
void DwarfCompileUnit::finishEntityDefinition (const DbgEntity * Entity)
Label may be used to generate DW_AT_low_pc, so put it outside if/else block.
Definition at line 1060 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), addLabelAddress(), applyLabelAttributes(), applyVariableAttributes(), llvm::dyn_cast(), llvm::DbgEntity::getDIE(), llvm::DbgEntity::getEntity(), getExistingAbstractEntity(), llvm::DbgLabel::getSymbol(), and llvm_unreachable.
Referenced by llvm::DwarfDebug::beginModule().
finishSubprogramDefinition()
void DwarfCompileUnit::finishSubprogramDefinition (const DISubprogram * SP)
Definition at line 1046 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), applySubprogramAttributesToDefinition(), assert(), D, llvm::DwarfUnit::getDIE(), includeMinimalInlineScopes(), and lookup().
Referenced by llvm::DwarfDebug::beginModule().
getBaseAddress()
const MCSymbol* llvm::DwarfCompileUnit::getBaseAddress () const inline
Definition at line 356 of file DwarfCompileUnit.h.
Referenced by emitRangeList().
getCU()
DwarfCompileUnit& llvm::DwarfCompileUnit::getCU () inline override virtual
Implements llvm::DwarfUnit.
Definition at line 163 of file DwarfCompileUnit.h.
References File.
Referenced by getOrCreateCommonBlock().
getDwarf5OrGNUAttr()
dwarf::Attribute DwarfCompileUnit::getDwarf5OrGNUAttr (dwarf::Attribute Attr) const
This takes a DWARF 5 attribute and returns it or a GNU analog.
Definition at line 926 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm_unreachable, and useGNUAnalogForDwarf5Feature().
Referenced by collectCallSiteParameters(), constructCallSiteEntryDIE(), and constructCallSiteParmEntryDIEs().
getDwarf5OrGNULocationAtom()
dwarf::LocationAtom DwarfCompileUnit::getDwarf5OrGNULocationAtom (dwarf::LocationAtom Loc) const
This takes a DWARF 5 location atom and either returns it or a GNU analog.
Definition at line 948 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm_unreachable, and useGNUAnalogForDwarf5Feature().
getDwarf5OrGNUTag()
dwarf::Tag DwarfCompileUnit::getDwarf5OrGNUTag (dwarf::Tag Tag) const
This takes a DWARF 5 tag and returns it or a GNU analog.
Definition at line 912 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm_unreachable, llvm::Tag, and useGNUAnalogForDwarf5Feature().
Referenced by constructCallSiteEntryDIE(), and constructCallSiteParmEntryDIEs().
getDWOId()
uint64_t llvm::DwarfCompileUnit::getDWOId () const inline
Definition at line 358 of file DwarfCompileUnit.h.
Referenced by emitHeader().
getExistingAbstractEntity()
DbgEntity * DwarfCompileUnit::getExistingAbstractEntity (const DINode * Node)
Definition at line 1084 of file DwarfCompileUnit.cpp.
Referenced by finishEntityDefinition().
getGlobalNames()
const StringMap<const DIE *>& llvm::DwarfCompileUnit::getGlobalNames () const inline
Definition at line 317 of file DwarfCompileUnit.h.
Referenced by computeIndexValue().
getGlobalTypes()
const StringMap<const DIE *>& llvm::DwarfCompileUnit::getGlobalTypes () const inline
Definition at line 318 of file DwarfCompileUnit.h.
Referenced by computeIndexValue().
getHeaderSize()
unsigned llvm::DwarfCompileUnit::getHeaderSize () const inline override virtual
Compute the size of a header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 277 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::getHeaderSize().
getLabelBegin()
MCSymbol* llvm::DwarfCompileUnit::getLabelBegin () const inline
Definition at line 294 of file DwarfCompileUnit.h.
References assert(), and llvm::object::getSection().
Referenced by computeIndexValue().
getLength()
unsigned llvm::DwarfCompileUnit::getLength () inline
Definition at line 284 of file DwarfCompileUnit.h.
Referenced by computeIndexValue().
getMacroLabelBegin()
MCSymbol* llvm::DwarfCompileUnit::getMacroLabelBegin () const inline
Definition at line 299 of file DwarfCompileUnit.h.
References Context, and Name.
Referenced by emitRangeList().
getOrCreateCommonBlock()
DIE * DwarfCompileUnit::getOrCreateCommonBlock (const DICommonBlock * CB, ArrayRef< GlobalExpr > GlobalExprs)
Definition at line 311 of file DwarfCompileUnit.cpp.
References addGlobalName(), addLocationAttribute(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::createAndAddDIE(), llvm::StringRef::empty(), getCU(), llvm::DICommonBlock::getDecl(), llvm::DwarfUnit::getDIE(), llvm::DICommonBlock::getFile(), llvm::DICommonBlock::getLineNo(), llvm::DICommonBlock::getName(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DICommonBlock::getScope(), and Name.
Referenced by getOrCreateGlobalVariableDIE().
getOrCreateGlobalVariableDIE()
DIE * DwarfCompileUnit::getOrCreateGlobalVariableDIE (const DIGlobalVariable * GV, ArrayRef< GlobalExpr > GlobalExprs)
Get or create global variable DIE.
Definition at line 122 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addFlag(), addGlobalName(), addLocationAttribute(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addTemplateParams(), llvm::DwarfUnit::addType(), llvm::DwarfUnit::addUInt(), assert(), llvm::DwarfUnit::createAndAddDIE(), llvm::dyn_cast(), llvm::DIVariable::getAlignInBytes(), llvm::DwarfUnit::getDIE(), llvm::DIGlobalVariable::getDisplayName(), llvm::DIVariable::getName(), getOrCreateCommonBlock(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DIVariable::getScope(), llvm::DIGlobalVariable::getStaticDataMemberDeclaration(), llvm::DINode::getTag(), llvm::DIGlobalVariable::getTemplateParams(), llvm::DIVariable::getType(), llvm::DIGlobalVariable::isDefinition(), and llvm::DIGlobalVariable::isLocalToUnit().
Referenced by llvm::DwarfDebug::beginModule(), and constructImportedEntityDIE().
getOrCreateSourceID()
unsigned DwarfCompileUnit::getOrCreateSourceID (const DIFile * File) override virtual
Look up the source ID for the given file.
If none currently exists, create a new ID and insert it in the line table.
Implements llvm::DwarfUnit.
Definition at line 108 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::DwarfUnit::getMD5AsBytes(), llvm::DIScope::getSource(), getUniqueID(), llvm::None, and llvm::AsmPrinter::OutStreamer.
Referenced by constructInlinedScopeDIE(), emitRangeList(), and llvm::DwarfUnit::getMD5AsBytes().
getRanges()
const SmallVectorImpl<RangeSpan>& llvm::DwarfCompileUnit::getRanges () const inline
getRanges - Get the list of ranges for this unit.
Definition at line 352 of file DwarfCompileUnit.h.
Referenced by llvm::DwarfDebug::beginModule().
getSkeleton()
DwarfCompileUnit* llvm::DwarfCompileUnit::getSkeleton () const inline
Definition at line 115 of file DwarfCompileUnit.h.
References llvm::Skeleton.
Referenced by llvm::DwarfDebug::beginModule(), computeIndexValue(), emitRangeList(), and forBothCUs().
getUniqueID()
unsigned llvm::DwarfCompileUnit::getUniqueID () const inline
Definition at line 113 of file DwarfCompileUnit.h.
Referenced by llvm::DwarfDebug::beginFunctionImpl(), emitRangeList(), getOrCreateSourceID(), and initStmtList().
hasDwarfPubSections()
bool DwarfCompileUnit::hasDwarfPubSections () const
Definition at line 1122 of file DwarfCompileUnit.cpp.
References llvm::Apple, llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DICompileUnit::Default, llvm::DwarfDebug::getAccelTableKind(), llvm::DwarfDebug::getDwarfVersion(), llvm::DICompileUnit::getNameTableKind(), llvm::DICompileUnit::GNU, includeMinimalInlineScopes(), llvm::DICompileUnit::isDebugDirectivesOnly(), llvm_unreachable, llvm::DICompileUnit::None, and llvm::DwarfDebug::tuneForGDB().
Referenced by addGlobalName(), addGlobalNameForTypeUnit(), addGlobalType(), addGlobalTypeUnitType(), collectCallSiteParameters(), and computeIndexValue().
hasRangeLists()
bool llvm::DwarfCompileUnit::hasRangeLists () const inline
Definition at line 112 of file DwarfCompileUnit.h.
Referenced by llvm::DwarfDebug::beginModule().
includeMinimalInlineScopes()
bool DwarfCompileUnit::includeMinimalInlineScopes () const
Definition at line 1310 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm::DwarfUnit::getCUNode(), llvm::DICompileUnit::getEmissionKind(), llvm::DICompileUnit::LineTablesOnly, and llvm::DwarfDebug::useSplitDwarf().
Referenced by applySubprogramAttributesToDefinition(), constructAbstractSubprogramScopeDIE(), constructSubprogramScopeDIE(), createScopeChildrenDIE(), finishSubprogramDefinition(), hasDwarfPubSections(), and updateSubprogramScopeDIE().
initStmtList()
void DwarfCompileUnit::initStmtList ()
Definition at line 347 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfLineSection(), llvm::AsmPrinter::getObjFileLowering(), getUniqueID(), llvm::DIEUnit::getUnitDie(), llvm::DICompileUnit::isDebugDirectivesOnly(), llvm::AsmPrinter::OutStreamer, and llvm::DwarfDebug::useSectionsAsReferences().
Referenced by collectCallSiteParameters().
setBaseAddress()
void llvm::DwarfCompileUnit::setBaseAddress (const MCSymbol * Base) inline
Definition at line 355 of file DwarfCompileUnit.h.
setDWOId()
void llvm::DwarfCompileUnit::setDWOId (uint64_t DwoId) inline
Definition at line 359 of file DwarfCompileUnit.h.
Referenced by llvm::DwarfDebug::beginModule().
setSkeleton()
void llvm::DwarfCompileUnit::setSkeleton (DwarfCompileUnit & Skel) inline
Set the skeleton unit associated with this unit.
Definition at line 275 of file DwarfCompileUnit.h.
takeRanges()
SmallVector<RangeSpan, 2> llvm::DwarfCompileUnit::takeRanges () inline
Definition at line 353 of file DwarfCompileUnit.h.
Referenced by llvm::DwarfDebug::beginModule().
updateSubprogramScopeDIE()
DIE & DwarfCompileUnit::updateSubprogramScopeDIE (const DISubprogram * SP)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc and DW_AT_high_pc attributes.
If there are global variables in this scope then create and insert DIEs for these variables.
Definition at line 392 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addFlag(), llvm::DwarfDebug::addSubprogramNames(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, attachLowHighPC(), llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::TargetOptions::DisableFramePointerElim(), llvm::DwarfDebug::getCurrentFunction(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::AsmPrinter::getFunctionBegin(), llvm::AsmPrinter::getFunctionEnd(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::getTargetTriple(), includeMinimalInlineScopes(), llvm::Triple::isNVPTX(), llvm::Register::isPhysicalRegister(), llvm::AsmPrinter::MF, llvm::TargetMachine::Options, and llvm::DwarfDebug::useAppleExtensionAttributes().
Referenced by constructSubprogramScopeDIE().
Member Data Documentation
ExprRefedBaseTypes
std::vector<BaseTypeRef> llvm::DwarfCompileUnit::ExprRefedBaseTypes
Definition at line 140 of file DwarfCompileUnit.h.
Referenced by createBaseTypeDIEs().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfCompileUnit.h
lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp