LLVM: llvm::LanaiInstrInfo Class Reference
llvm::LanaiInstrInfo Class Reference
#include "Target/Lanai/LanaiInstrInfo.h"
Public Member Functions
LanaiInstrInfo ()
virtual const LanaiRegisterInfo & getRegisterInfo () const
bool areMemAccessesTriviallyDisjoint (const MachineInstr &MIa, const MachineInstr &MIb) const override
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
unsigned isLoadFromStackSlotPostFE (const MachineInstr &MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator Position, const DebugLoc &DL, MCRegister DestinationRegister, MCRegister SourceRegister, bool KillSource) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator Position, unsigned SourceRegister, bool IsKill, int FrameIndex, const TargetRegisterClass *RegisterClass, const TargetRegisterInfo *RegisterInfo) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator Position, unsigned DestinationRegister, int FrameIndex, const TargetRegisterClass *RegisterClass, const TargetRegisterInfo *RegisterInfo) const override
bool expandPostRAPseudo (MachineInstr &MI) const override
bool getMemOperandWithOffset (const MachineInstr &LdSt, const MachineOperand *&BaseOp, int64_t &Offset, const TargetRegisterInfo *TRI) const override
bool getMemOperandWithOffsetWidth (const MachineInstr &LdSt, const MachineOperand *&BaseOp, int64_t &Offset, unsigned &Width, const TargetRegisterInfo *TRI) const
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TrueBlock, MachineBasicBlock *&FalseBlock, SmallVectorImpl< MachineOperand > &Condition, bool AllowModify) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
bool analyzeCompare (const MachineInstr &MI, unsigned &SrcReg, unsigned &SrcReg2, int &CmpMask, int &CmpValue) const override
bool optimizeCompareInstr (MachineInstr &CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo *MRI) const override
bool analyzeSelect (const MachineInstr &MI, SmallVectorImpl< MachineOperand > &Cond, unsigned &TrueOp, unsigned &FalseOp, bool &Optimizable) const override
MachineInstr * optimizeSelect (MachineInstr &MI, SmallPtrSetImpl< MachineInstr *> &SeenMIs, bool PreferFalse) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Condition) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TrueBlock, MachineBasicBlock *FalseBlock, ArrayRef< MachineOperand > Condition, const DebugLoc &DL, int *BytesAdded=nullptr) const override
Detailed Description
Definition at line 25 of file LanaiInstrInfo.h.
Constructor & Destructor Documentation
LanaiInstrInfo()
LanaiInstrInfo::LanaiInstrInfo ()
Definition at line 30 of file LanaiInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool LanaiInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TrueBlock, MachineBasicBlock *& FalseBlock, SmallVectorImpl< MachineOperand > & Condition, bool AllowModify) const override
Definition at line 562 of file LanaiInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineOperand::CreateImm(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::isLayoutSuccessor(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by getRegisterInfo().
analyzeCompare()
bool LanaiInstrInfo::analyzeCompare (const MachineInstr & MI, unsigned & SrcReg, unsigned & SrcReg2, int & CmpMask, int & CmpValue) const override
Definition at line 177 of file LanaiInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by getRegisterInfo().
analyzeSelect()
bool LanaiInstrInfo::analyzeSelect (const MachineInstr & MI, SmallVectorImpl< MachineOperand > & Cond, unsigned & TrueOp, unsigned & FalseOp, bool & Optimizable) const override
Definition at line 438 of file LanaiInstrInfo.cpp.
Referenced by getRegisterInfo().
areMemAccessesTriviallyDisjoint()
bool LanaiInstrInfo::areMemAccessesTriviallyDisjoint (const MachineInstr & MIa, const MachineInstr & MIb) const override
Definition at line 88 of file LanaiInstrInfo.cpp.
References assert(), getMemOperandWithOffsetWidth(), getRegisterInfo(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineOperand::isIdenticalTo(), llvm::max(), llvm::MachineInstr::mayLoadOrStore(), and TRI.
Referenced by getRegisterInfo().
copyPhysReg()
void LanaiInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator Position, const DebugLoc & DL, MCRegister DestinationRegister, MCRegister SourceRegister, bool KillSource) const override
Definition at line 34 of file LanaiInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::getKillRegState(), and llvm_unreachable.
Referenced by getRegisterInfo().
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > LanaiInstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 163 of file LanaiInstrInfo.cpp.
Referenced by getRegisterInfo().
expandPostRAPseudo()
bool LanaiInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 119 of file LanaiInstrInfo.cpp.
Referenced by getRegisterInfo().
getMemOperandWithOffset()
bool LanaiInstrInfo::getMemOperandWithOffset (const MachineInstr & LdSt, const MachineOperand *& BaseOp, int64_t & Offset, const TargetRegisterInfo * TRI) const override
Definition at line 798 of file LanaiInstrInfo.cpp.
References getMemOperandWithOffsetWidth(), and llvm::MachineInstr::getOpcode().
Referenced by getRegisterInfo().
getMemOperandWithOffsetWidth()
bool LanaiInstrInfo::getMemOperandWithOffsetWidth (const MachineInstr & LdSt, const MachineOperand *& BaseOp, int64_t & Offset, unsigned & Width, const TargetRegisterInfo * TRI) const
Definition at line 757 of file LanaiInstrInfo.cpp.
References llvm::LPAC::ADD, llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
Referenced by areMemAccessesTriviallyDisjoint(), getMemOperandWithOffset(), and getRegisterInfo().
getRegisterInfo()
virtual const LanaiRegisterInfo& llvm::LanaiInstrInfo::getRegisterInfo () const inline virtual
Definition at line 34 of file LanaiInstrInfo.h.
References analyzeBranch(), analyzeCompare(), analyzeSelect(), areMemAccessesTriviallyDisjoint(), copyPhysReg(), decomposeMachineOperandsTargetFlags(), expandPostRAPseudo(), llvm::ISD::FrameIndex, getMemOperandWithOffset(), getMemOperandWithOffsetWidth(), getSerializableDirectMachineOperandTargetFlags(), isLoadFromStackSlot(), isLoadFromStackSlotPostFE(), isStoreToStackSlot(), loadRegFromStackSlot(), MI, MRI, optimizeCompareInstr(), removeBranch(), storeRegToStackSlot(), and TRI.
Referenced by areMemAccessesTriviallyDisjoint(), llvm::LanaiSubtarget::getRegisterInfo(), and optimizeCompareInstr().
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > LanaiInstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 168 of file LanaiInstrInfo.cpp.
References llvm::makeArrayRef(), llvm::LanaiII::MO_ABS_HI, llvm::LanaiII::MO_ABS_LO, and llvm::AArch64II::MO_NO_FLAG.
Referenced by getRegisterInfo().
insertBranch()
unsigned LanaiInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TrueBlock, MachineBasicBlock * FalseBlock, ArrayRef< MachineOperand > Condition, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 660 of file LanaiInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), llvm::ArrayRef< T >::empty(), and llvm::ArrayRef< T >::size().
isLoadFromStackSlot()
unsigned LanaiInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 717 of file LanaiInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), and llvm::MachineOperand::isImm().
Referenced by getRegisterInfo(), and isLoadFromStackSlotPostFE().
isLoadFromStackSlotPostFE()
unsigned LanaiInstrInfo::isLoadFromStackSlotPostFE (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 728 of file LanaiInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T >::front(), llvm::MachineInstr::getOpcode(), isLoadFromStackSlot(), and Reg.
Referenced by getRegisterInfo().
isStoreToStackSlot()
unsigned LanaiInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 746 of file LanaiInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), and llvm::MachineOperand::isImm().
Referenced by getRegisterInfo().
loadRegFromStackSlot()
void LanaiInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator Position, unsigned DestinationRegister, int FrameIndex, const TargetRegisterClass * RegisterClass, const TargetRegisterInfo * RegisterInfo) const override
Definition at line 69 of file LanaiInstrInfo.cpp.
References llvm::LPAC::ADD, llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), and llvm_unreachable.
Referenced by getRegisterInfo().
optimizeCompareInstr()
bool LanaiInstrInfo::optimizeCompareInstr (MachineInstr & CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo * MRI) const override
Definition at line 283 of file LanaiInstrInfo.cpp.
References llvm::MachineInstr::addRegisterDefined(), B, llvm::MachineBasicBlock::begin(), llvm::MachineOperand::clobbersPhysReg(), E, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), flagSettingOpcodeVariant(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getOppositeCondition(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MachineRegisterInfo::getUniqueVRegDef(), I, llvm::LPCC::ICC_CC, llvm::LPCC::ICC_CS, llvm::LPCC::ICC_EQ, llvm::LPCC::ICC_F, llvm::LPCC::ICC_GE, llvm::LPCC::ICC_GT, llvm::LPCC::ICC_HI, llvm::LPCC::ICC_LE, llvm::LPCC::ICC_LS, llvm::LPCC::ICC_LT, llvm::LPCC::ICC_MI, llvm::LPCC::ICC_NE, llvm::LPCC::ICC_PL, llvm::LPCC::ICC_T, llvm::LPCC::ICC_VC, llvm::LPCC::ICC_VS, llvm::MachineOperand::isDef(), isRedundantFlagInstr(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), MI, llvm::MachineInstr::modifiesRegister(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineInstr::readsRegister(), llvm::MachineInstr::setDesc(), SI, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), TRI, and llvm::LPCC::UNKNOWN.
Referenced by getRegisterInfo().
optimizeSelect()
MachineInstr * LanaiInstrInfo::optimizeSelect (MachineInstr & MI, SmallPtrSetImpl< MachineInstr *> & SeenMIs, bool PreferFalse) const override
Definition at line 493 of file LanaiInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), canFoldIntoSelect(), llvm::MachineInstr::clearKillInfo(), llvm::MachineInstrBuilder::copyImplicitOps(), DefMI, llvm::numbers::e, llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getOppositeCondition(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SmallPtrSetImpl< PtrType >::insert(), MI, MRI, llvm::ISD::SELECT, llvm::MachineOperand::setImplicit(), and llvm::MachineInstr::tieOperands().
removeBranch()
unsigned LanaiInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 692 of file LanaiInstrInfo.cpp.
References assert(), llvm::MachineBasicBlock::begin(), and llvm::MachineBasicBlock::end().
Referenced by getRegisterInfo().
reverseBranchCondition()
bool LanaiInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Condition) const override
Definition at line 646 of file LanaiInstrInfo.cpp.
References assert(), getOppositeCondition(), and llvm::SmallVectorBase::size().
storeRegToStackSlot()
void LanaiInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator Position, unsigned SourceRegister, bool IsKill, int FrameIndex, const TargetRegisterClass * RegisterClass, const TargetRegisterInfo * RegisterInfo) const override
Definition at line 49 of file LanaiInstrInfo.cpp.
References llvm::LPAC::ADD, llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getKillRegState(), and llvm_unreachable.
Referenced by getRegisterInfo().
The documentation for this class was generated from the following files:
lib/Target/Lanai/LanaiInstrInfo.h
lib/Target/Lanai/LanaiInstrInfo.cpp