LLVM: llvm::RuntimeDyldCOFF Class Reference
llvm::RuntimeDyldCOFF Class Reference
#include "ExecutionEngine/RuntimeDyld/RuntimeDyldCOFF.h"
Public Member Functions
std::unique_ptr< RuntimeDyld::LoadedObjectInfo > loadObject (const object::ObjectFile &Obj) override
bool isCompatibleFile (const object::ObjectFile &Obj) const override
Public Member Functions inherited from llvm::RuntimeDyldImpl
RuntimeDyldImpl (RuntimeDyld::MemoryManager &MemMgr, JITSymbolResolver &Resolver)
virtual ~RuntimeDyldImpl ()
void setProcessAllSections (bool ProcessAllSections)
uint64_t getSectionLoadAddress (unsigned SectionID) const
uint8_t * getSectionAddress (unsigned SectionID) const
StringRef getSectionContent (unsigned SectionID) const
uint8_t * getSymbolLocalAddress (StringRef Name) const
unsigned getSymbolSectionID (StringRef Name) const
JITEvaluatedSymbol getSymbol (StringRef Name) const
std::map< StringRef, JITEvaluatedSymbol > getSymbolTable () const
void resolveRelocations ()
void resolveLocalRelocations ()
void reassignSectionAddress (unsigned SectionID, uint64_t Addr)
void mapSectionAddress (const void *LocalAddress, uint64_t TargetAddress)
bool hasError ()
void clearError ()
StringRef getErrorString ()
void setNotifyStubEmitted (NotifyStubEmittedFunction NotifyStubEmitted)
virtual void registerEHFrames ()
void deregisterEHFrames ()
virtual Error finalizeLoad (const ObjectFile &ObjImg, ObjSectionToIDMap &SectionMap)
Static Public Member Functions
static std::unique_ptr< RuntimeDyldCOFF > create (Triple::ArchType Arch, RuntimeDyld::MemoryManager &MemMgr, JITSymbolResolver &Resolver)
Static Public Member Functions inherited from llvm::RuntimeDyldImpl
static void finalizeAsync (std::unique_ptr< RuntimeDyldImpl > This, unique_function< void(Error)> OnEmitted, std::unique_ptr< MemoryBuffer > UnderlyingBuffer)
Protected Member Functions
RuntimeDyldCOFF (RuntimeDyld::MemoryManager &MemMgr, JITSymbolResolver &Resolver)
uint64_t getSymbolOffset (const SymbolRef &Sym)
Protected Member Functions inherited from llvm::RuntimeDyldImpl
virtual unsigned getMaxStubSize () const =0
virtual unsigned getStubAlignment ()=0
void writeInt16BE (uint8_t *Addr, uint16_t Value)
void writeInt32BE (uint8_t *Addr, uint32_t Value)
void writeInt64BE (uint8_t *Addr, uint64_t Value)
virtual void setMipsABI (const ObjectFile &Obj)
uint64_t readBytesUnaligned (uint8_t *Src, unsigned Size) const
Endian-aware read Read the least significant Size bytes from Src.
void writeBytesUnaligned (uint64_t Value, uint8_t *Dst, unsigned Size) const
Endian-aware write.
virtual Expected< JITSymbolFlags > getJITSymbolFlags (const SymbolRef &Sym)
Generate JITSymbolFlags from a libObject symbol.
virtual uint64_t modifyAddressBasedOnFlags (uint64_t Addr, JITSymbolFlags Flags) const
Modify the given target address based on the given symbol flags.
Error emitCommonSymbols (const ObjectFile &Obj, CommonSymbolList &CommonSymbols, uint64_t CommonSize, uint32_t CommonAlign)
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
Expected< unsigned > emitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode)
Emits section data from the object file to the MemoryManager.
Expected< unsigned > findOrEmitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode, ObjSectionToIDMap &LocalSections)
Find Section in LocalSections.
void addRelocationForSection (const RelocationEntry &RE, unsigned SectionID)
void addRelocationForSymbol (const RelocationEntry &RE, StringRef SymbolName)
uint8_t * createStubFunction (uint8_t *Addr, unsigned AbiVariant=0)
Emits long jump instruction to Addr.
void resolveRelocationList (const RelocationList &Relocs, uint64_t Value)
Resolves relocations from Relocs list with address from Value.
virtual void resolveRelocation (const RelocationEntry &RE, uint64_t Value)=0
A object file specific relocation resolver.
virtual Expected< relocation_iterator > processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile &Obj, ObjSectionToIDMap &ObjSectionToID, StubMap &Stubs)=0
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
void applyExternalSymbolRelocations (const StringMap< JITEvaluatedSymbol > ExternalSymbolMap)
Error resolveExternalSymbols ()
Resolve relocations to external symbols.
Error computeTotalAllocSize (const ObjectFile &Obj, uint64_t &CodeSize, uint32_t &CodeAlign, uint64_t &RODataSize, uint32_t &RODataAlign, uint64_t &RWDataSize, uint32_t &RWDataAlign)
unsigned computeGOTSize (const ObjectFile &Obj)
unsigned computeSectionStubBufSize (const ObjectFile &Obj, const SectionRef &Section)
Expected< ObjSectionToIDMap > loadObjectImpl (const object::ObjectFile &Obj)
virtual size_t getGOTEntrySize ()
virtual bool relocationNeedsGot (const RelocationRef &R) const
virtual bool relocationNeedsStub (const RelocationRef &R) const
Additional Inherited Members
Protected Types inherited from llvm::RuntimeDyldImpl
typedef SmallVector< SectionEntry, 64 > SectionList
typedef unsigned SID
typedef std::map< SectionRef, unsigned > ObjSectionToIDMap
typedef std::vector< SymbolRef > CommonSymbolList
typedef SmallVector< RelocationEntry, 64 > RelocationList
typedef std::map< RelocationValueRef, uintptr_t > StubMap
using NotifyStubEmittedFunction = RuntimeDyld::NotifyStubEmittedFunction
Protected Attributes inherited from llvm::RuntimeDyldImpl
RuntimeDyld::MemoryManager & MemMgr
JITSymbolResolver & Resolver
SectionList Sections
RTDyldSymbolTable GlobalSymbolTable
std::unordered_map< unsigned, RelocationList > Relocations
StringMap< RelocationList > ExternalSymbolRelocations
Triple::ArchType Arch
bool IsTargetLittleEndian
bool IsMipsO32ABI
bool IsMipsN32ABI
bool IsMipsN64ABI
bool ProcessAllSections
sys::Mutex lock
NotifyStubEmittedFunction NotifyStubEmitted
bool HasError
std::string ErrorStr
Static Protected Attributes inherited from llvm::RuntimeDyldImpl
static const unsigned AbsoluteSymbolSection = ~0U
Detailed Description
Definition at line 26 of file RuntimeDyldCOFF.h.
Constructor & Destructor Documentation
RuntimeDyldCOFF()
llvm::RuntimeDyldCOFF::RuntimeDyldCOFF (RuntimeDyld::MemoryManager & MemMgr, JITSymbolResolver & Resolver) inline protected
Definition at line 38 of file RuntimeDyldCOFF.h.
References getSymbolOffset().
Member Function Documentation
create()
std::unique_ptr< RuntimeDyldCOFF > llvm::RuntimeDyldCOFF::create (Triple::ArchType Arch, RuntimeDyld::MemoryManager & MemMgr, JITSymbolResolver & Resolver) static
Definition at line 48 of file RuntimeDyldCOFF.cpp.
References llvm::Triple::aarch64, llvm_unreachable, llvm::Triple::thumb, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by llvm::createRuntimeDyldCOFF().
getSymbolOffset()
uint64_t llvm::RuntimeDyldCOFF::getSymbolOffset (const SymbolRef & Sym) protected
Definition at line 76 of file RuntimeDyldCOFF.cpp.
References llvm::object::SymbolRef::getValue().
Referenced by llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), and RuntimeDyldCOFF().
isCompatibleFile()
bool llvm::RuntimeDyldCOFF::isCompatibleFile (const object::ObjectFile & Obj) const override virtual
Implements llvm::RuntimeDyldImpl.
Definition at line 81 of file RuntimeDyldCOFF.cpp.
References llvm::object::Binary::isCOFF().
loadObject()
std::unique_ptr< RuntimeDyld::LoadedObjectInfo > llvm::RuntimeDyldCOFF::loadObject (const object::ObjectFile & Obj) override virtual
Implements llvm::RuntimeDyldImpl.
Definition at line 65 of file RuntimeDyldCOFF.cpp.
References llvm::logAllUnhandledErrors().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldCOFF.h
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldCOFF.cpp