LLVM: llvm::MCDwarfLineEntry Class Reference
llvm::MCDwarfLineEntry Class Reference
Instances of this class represent the line information for the dwarf line table entries.
#include "llvm/MC/MCDwarf.h"
Public Member Functions
MCDwarfLineEntry (MCSymbol *label, const MCDwarfLoc loc)
MCSymbol * getLabel () const
Public Member Functions inherited from llvm::MCDwarfLoc
unsigned getFileNum () const
Get the FileNum of this MCDwarfLoc.
unsigned getLine () const
Get the Line of this MCDwarfLoc.
unsigned getColumn () const
Get the Column of this MCDwarfLoc.
unsigned getFlags () const
Get the Flags of this MCDwarfLoc.
unsigned getIsa () const
Get the Isa of this MCDwarfLoc.
unsigned getDiscriminator () const
Get the Discriminator of this MCDwarfLoc.
void setFileNum (unsigned fileNum)
Set the FileNum of this MCDwarfLoc.
void setLine (unsigned line)
Set the Line of this MCDwarfLoc.
void setColumn (unsigned column)
Set the Column of this MCDwarfLoc.
void setFlags (unsigned flags)
Set the Flags of this MCDwarfLoc.
void setIsa (unsigned isa)
Set the Isa of this MCDwarfLoc.
void setDiscriminator (unsigned discriminator)
Set the Discriminator of this MCDwarfLoc.
Static Public Member Functions
static void Make (MCObjectStreamer *MCOS, MCSection *Section)
Detailed Description
Instances of this class represent the line information for the dwarf line table entries.
Which is created after a machine instruction is assembled and uses an address from a temporary label created at the current address in the current section and the info from the last .loc directive seen as stored in the context.
Definition at line 153 of file MCDwarf.h.
Constructor & Destructor Documentation
MCDwarfLineEntry()
llvm::MCDwarfLineEntry::MCDwarfLineEntry (MCSymbol * label, const MCDwarfLoc loc) inline
Definition at line 162 of file MCDwarf.h.
Member Function Documentation
getLabel()
MCSymbol* llvm::MCDwarfLineEntry::getLabel () const inline
Definition at line 165 of file MCDwarf.h.
References llvm::ARMBuildAttrs::Section.
Make()
void MCDwarfLineEntry::Make (MCObjectStreamer * MCOS, MCSection * Section) static
Definition at line 87 of file MCDwarf.cpp.
References llvm::MCContext::clearDwarfLocSeen(), llvm::MCContext::createTempSymbol(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCStreamer::getContext(), llvm::MCContext::getCurrentDwarfLoc(), llvm::MCContext::getDwarfCompileUnitID(), llvm::MCContext::getDwarfLocSeen(), and llvm::MCContext::getMCDwarfLineTable().
Referenced by llvm::MCObjectStreamer::EmitBytes(), llvm::MCObjectStreamer::EmitDwarfLocDirective(), llvm::MCObjectStreamer::EmitInstruction(), and llvm::MCObjectStreamer::EmitValueImpl().
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp