LLVM: llvm::xray::Record Class Reference
llvm::xray::Record Class Reference abstract
#include "llvm/XRay/FDRRecords.h"
Public Types
enum RecordKind {
RecordKind::RK_Metadata, RecordKind::RK_Metadata_BufferExtents, RecordKind::RK_Metadata_WallClockTime, RecordKind::RK_Metadata_NewCPUId,
RecordKind::RK_Metadata_TSCWrap, RecordKind::RK_Metadata_CustomEvent, RecordKind::RK_Metadata_CustomEventV5, RecordKind::RK_Metadata_CallArg,
RecordKind::RK_Metadata_PIDEntry, RecordKind::RK_Metadata_NewBuffer, RecordKind::RK_Metadata_EndOfBuffer, RecordKind::RK_Metadata_TypedEvent,
RecordKind::RK_Metadata_LastMetadata, RecordKind::RK_Function
}
Public Member Functions
Record (const Record &)=delete
Record (Record &&)=delete
Record & operator= (const Record &)=delete
Record & operator= (Record &&)=delete
Record (RecordKind T)
RecordKind getRecordType () const
virtual Error apply (RecordVisitor &V)=0
virtual ~Record ()=default
Static Public Member Functions
static StringRef kindToString (RecordKind K)
Detailed Description
Definition at line 31 of file FDRRecords.h.
Member Enumeration Documentation
RecordKind
enum llvm::xray::Record::RecordKind strong
Enumerator
RK_Metadata
RK_Metadata_BufferExtents
RK_Metadata_WallClockTime
RK_Metadata_NewCPUId
RK_Metadata_TSCWrap
RK_Metadata_CustomEvent
RK_Metadata_CustomEventV5
RK_Metadata_CallArg
RK_Metadata_PIDEntry
RK_Metadata_NewBuffer
RK_Metadata_EndOfBuffer
RK_Metadata_TypedEvent
RK_Metadata_LastMetadata
RK_Function
Definition at line 33 of file FDRRecords.h.
Constructor & Destructor Documentation
Record() [1/3]
llvm::xray::Record::Record (const Record &) delete
Record() [2/3]
llvm::xray::Record::Record (Record &&) delete
Record() [3/3]
llvm::xray::Record::Record (RecordKind T) inline explicit
Definition at line 60 of file FDRRecords.h.
~Record()
virtual llvm::xray::Record::~Record () virtual default
Referenced by getRecordType().
Member Function Documentation
apply()
virtual Error llvm::xray::Record::apply (RecordVisitor & V) pure virtual
Implemented in llvm::xray::FunctionRecord, llvm::xray::EndBufferRecord, llvm::xray::NewBufferRecord, llvm::xray::PIDRecord, llvm::xray::CallArgRecord, llvm::xray::TypedEventRecord, llvm::xray::CustomEventRecordV5, llvm::xray::CustomEventRecord, llvm::xray::TSCWrapRecord, llvm::xray::NewCPUIDRecord, llvm::xray::WallclockRecord, and llvm::xray::BufferExtents.
Referenced by llvm::xray::CallArgRecord::arg(), llvm::xray::CustomEventRecord::data(), llvm::xray::CustomEventRecordV5::data(), llvm::xray::TypedEventRecord::data(), llvm::xray::FunctionRecord::delta(), llvm::xray::EndBufferRecord::EndBufferRecord(), getRecordType(), llvm::xray::WallclockRecord::nanos(), llvm::xray::PIDRecord::pid(), llvm::xray::BufferExtents::size(), llvm::xray::NewBufferRecord::tid(), llvm::xray::NewCPUIDRecord::tsc(), and llvm::xray::TSCWrapRecord::tsc().
getRecordType()
RecordKind llvm::xray::Record::getRecordType () const inline
Definition at line 62 of file FDRRecords.h.
References apply(), and ~Record().
Referenced by llvm::xray::MetadataRecord::classof(), llvm::xray::BufferExtents::classof(), llvm::xray::WallclockRecord::classof(), llvm::xray::NewCPUIDRecord::classof(), llvm::xray::TSCWrapRecord::classof(), llvm::xray::CustomEventRecord::classof(), llvm::xray::CustomEventRecordV5::classof(), llvm::xray::TypedEventRecord::classof(), llvm::xray::CallArgRecord::classof(), llvm::xray::PIDRecord::classof(), llvm::xray::NewBufferRecord::classof(), llvm::xray::EndBufferRecord::classof(), and llvm::xray::FunctionRecord::classof().
kindToString()
StringRef llvm::xray::Record::kindToString (RecordKind K) static
Definition at line 31 of file FDRRecords.cpp.
References RK_Function, RK_Metadata, RK_Metadata_BufferExtents, RK_Metadata_CallArg, RK_Metadata_CustomEvent, RK_Metadata_CustomEventV5, RK_Metadata_EndOfBuffer, RK_Metadata_LastMetadata, RK_Metadata_NewBuffer, RK_Metadata_NewCPUId, RK_Metadata_PIDEntry, RK_Metadata_TSCWrap, RK_Metadata_TypedEvent, and RK_Metadata_WallClockTime.
operator=() [1/2]
Record& llvm::xray::Record::operator= (const Record &) delete
operator=() [2/2]
Record& llvm::xray::Record::operator= (Record &&) delete
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecords.h
lib/XRay/FDRRecords.cpp