LLVM: llvm::FileCheckPatternContext Class Reference
llvm::FileCheckPatternContext Class Reference
Class holding the Pattern global state, shared by all patterns: tables holding values of variables and whether they are defined or not at any given time in the matching process.
#include "Support/FileCheckImpl.h"
Public Member Functions
Expected< StringRef > getPatternVarValue (StringRef VarName)
Error defineCmdlineVariables (std::vector< std::string > &CmdlineDefines, SourceMgr &SM)
Defines string and numeric variables from definitions given on the command line, passed as a vector of [#]VAR=VAL strings in CmdlineDefines.
void createLineVariable ()
Create pseudo variable.
void clearLocalVars ()
Undefines local variables (variables whose name does not start with a '$' sign), i.e.
Friends
class Pattern
Detailed Description
Class holding the Pattern global state, shared by all patterns: tables holding values of variables and whether they are defined or not at any given time in the matching process.
Definition at line 244 of file FileCheckImpl.h.
Member Function Documentation
clearLocalVars()
void FileCheckPatternContext::clearLocalVars ()
Undefines local variables (variables whose name does not start with a '$' sign), i.e.
removes them from GlobalVariableTable and from GlobalNumericVariableTable and also clears the value of numeric variables.
Definition at line 1891 of file FileCheck.cpp.
References llvm::SmallVectorTemplateBase< T >::push_back().
createLineVariable()
void FileCheckPatternContext::createLineVariable ()
Create pseudo variable.
Value is set when pattern are being matched.
Definition at line 1104 of file FileCheck.cpp.
References assert().
defineCmdlineVariables()
Error FileCheckPatternContext::defineCmdlineVariables (std::vector< std::string > & CmdlineDefines, SourceMgr & SM)
Defines string and numeric variables from definitions given on the command line, passed as a vector of [#]VAR=VAL strings in CmdlineDefines.
Returns
an error list containing diagnostics against SM for all definition parsing failures, if any, or Success otherwise.
Definition at line 1752 of file FileCheck.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), assert(), llvm::StringRef::empty(), llvm::ErrorDiagnostic::get(), llvm::MemoryBuffer::getMemBufferCopy(), I, llvm::joinErrors(), Name, llvm::None, llvm::StringRef::npos, llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parseVariable(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::StringRef::split(), llvm::StringRef::substr(), llvm::Error::success(), and llvm::Expected< T >::takeError().
getPatternVarValue()
Expected< StringRef > FileCheckPatternContext::getPatternVarValue (StringRef VarName)
Returns
the value of string variable VarName or an error if no such variable has been defined.
Definition at line 817 of file FileCheck.cpp.
References llvm::StringRef::data(), llvm::SourceMgr::DK_Error, llvm::StringRef::empty(), llvm::SMLoc::getFromPointer(), llvm::StringRef::npos, llvm::SourceMgr::PrintMessage(), llvm::StringRef::startswith(), llvm::StringRef::substr(), and llvm::tgtok::VarName.
Friends And Related Function Documentation
Pattern
friend class Pattern friend
Definition at line 245 of file FileCheckImpl.h.
The documentation for this class was generated from the following files:
lib/Support/FileCheckImpl.h
lib/Support/FileCheck.cpp