LLVM: llvm::vfs::RedirectingFileSystem::Entry Class Reference
llvm::vfs::RedirectingFileSystem::Entry Class Reference
A single file or directory in the VFS.
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
Entry (EntryKind K, StringRef Name)
virtual ~Entry ()=default
StringRef getName () const
EntryKind getKind () const
Detailed Description
A single file or directory in the VFS.
Definition at line 578 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
Entry()
llvm::vfs::RedirectingFileSystem::Entry::Entry (EntryKind K, StringRef Name) inline
Definition at line 583 of file VirtualFileSystem.h.
~Entry()
virtual llvm::vfs::RedirectingFileSystem::Entry::~Entry () virtual default
Member Function Documentation
getKind()
EntryKind llvm::vfs::RedirectingFileSystem::Entry::getKind () const inline
Definition at line 587 of file VirtualFileSystem.h.
Referenced by llvm::vfs::RedirectingFileSystem::RedirectingDirectoryEntry::classof(), llvm::vfs::RedirectingFileSystem::RedirectingFileEntry::classof(), llvm::vfs::RedirectingFileSystem::dumpEntry(), and getVFSEntries().
getName()
StringRef llvm::vfs::RedirectingFileSystem::Entry::getName () const inline
Definition at line 586 of file VirtualFileSystem.h.
Referenced by llvm::vfs::RedirectingFileSystem::dumpEntry().
The documentation for this class was generated from the following file:
include/llvm/Support/VirtualFileSystem.h