LLVM: llvm::HexagonBlockRanges::InstrIndexMap Class Reference
llvm::HexagonBlockRanges::InstrIndexMap Class Reference
#include "Target/Hexagon/HexagonBlockRanges.h"
Public Member Functions
InstrIndexMap (MachineBasicBlock &B)
MachineInstr * getInstr (IndexType Idx) const
IndexType getIndex (MachineInstr *MI) const
MachineBasicBlock & getBlock () const
IndexType getPrevIndex (IndexType Idx) const
IndexType getNextIndex (IndexType Idx) const
void replaceInstr (MachineInstr *OldMI, MachineInstr *NewMI)
Public Attributes
IndexType First
IndexType Last
Friends
raw_ostream & operator<< (raw_ostream &OS, const InstrIndexMap &Map)
Detailed Description
Definition at line 122 of file HexagonBlockRanges.h.
Constructor & Destructor Documentation
InstrIndexMap()
HexagonBlockRanges::InstrIndexMap::InstrIndexMap (MachineBasicBlock & B)
Definition at line 157 of file HexagonBlockRanges.cpp.
References assert(), llvm::HexagonBlockRanges::IndexType::First, First, getIndex(), llvm::tgtok::In, Last, and llvm::HexagonBlockRanges::IndexType::None.
Member Function Documentation
getBlock()
MachineBasicBlock& llvm::HexagonBlockRanges::InstrIndexMap::getBlock () const inline
Definition at line 128 of file HexagonBlockRanges.h.
References llvm::operator<<().
Referenced by llvm::HexagonBlockRanges::computeDeadMap(), and llvm::HexagonBlockRanges::expandToSubRegs().
getIndex()
HexagonBlockRanges::IndexType HexagonBlockRanges::InstrIndexMap::getIndex (MachineInstr * MI) const
Definition at line 176 of file HexagonBlockRanges.cpp.
References I, and llvm::HexagonBlockRanges::IndexType::None.
Referenced by llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::HexagonBlockRanges::expandToSubRegs(), InstrIndexMap(), and llvm::operator<<().
getInstr()
MachineInstr * HexagonBlockRanges::InstrIndexMap::getInstr (IndexType Idx) const
Definition at line 171 of file HexagonBlockRanges.cpp.
References F().
getNextIndex()
HexagonBlockRanges::IndexType HexagonBlockRanges::InstrIndexMap::getNextIndex (IndexType Idx) const
Definition at line 196 of file HexagonBlockRanges.cpp.
References assert(), llvm::HexagonBlockRanges::IndexType::Entry, llvm::HexagonBlockRanges::IndexType::Exit, llvm::HexagonBlockRanges::IndexType::First, Last, and llvm::HexagonBlockRanges::IndexType::None.
Referenced by llvm::HexagonBlockRanges::computeDeadMap().
getPrevIndex()
HexagonBlockRanges::IndexType HexagonBlockRanges::InstrIndexMap::getPrevIndex (IndexType Idx) const
Definition at line 184 of file HexagonBlockRanges.cpp.
References assert(), llvm::HexagonBlockRanges::IndexType::Entry, llvm::HexagonBlockRanges::IndexType::Exit, First, Last, and llvm::HexagonBlockRanges::IndexType::None.
Referenced by llvm::HexagonBlockRanges::computeDeadMap().
replaceInstr()
void HexagonBlockRanges::InstrIndexMap::replaceInstr (MachineInstr * OldMI, MachineInstr * NewMI)
Definition at line 206 of file HexagonBlockRanges.cpp.
References I.
Friends And Related Function Documentation
operator<<
raw_ostream& operator<< (raw_ostream & OS, const InstrIndexMap & Map) friend
Member Data Documentation
First
IndexType llvm::HexagonBlockRanges::InstrIndexMap::First
Definition at line 135 of file HexagonBlockRanges.h.
Referenced by getPrevIndex(), and InstrIndexMap().
Last
IndexType llvm::HexagonBlockRanges::InstrIndexMap::Last
Definition at line 135 of file HexagonBlockRanges.h.
Referenced by getNextIndex(), getPrevIndex(), InstrIndexMap(), and llvm::operator<<().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonBlockRanges.h
lib/Target/Hexagon/HexagonBlockRanges.cpp