LLVM: llvm::codeview::DebugFrameDataSubsectionRef Class Reference
llvm::codeview::DebugFrameDataSubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugFrameDataSubsection.h"
Public Member Functions
DebugFrameDataSubsectionRef ()
Error initialize (BinaryStreamReader Reader)
Error initialize (BinaryStreamRef Stream)
FixedStreamArray< FrameData >::Iterator begin () const
FixedStreamArray< FrameData >::Iterator end () const
const support::ulittle32_t * getRelocPtr () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 20 of file DebugFrameDataSubsection.h.
Constructor & Destructor Documentation
DebugFrameDataSubsectionRef()
llvm::codeview::DebugFrameDataSubsectionRef::DebugFrameDataSubsectionRef () inline
Definition at line 22 of file DebugFrameDataSubsection.h.
Member Function Documentation
begin()
FixedStreamArray<FrameData>::Iterator llvm::codeview::DebugFrameDataSubsectionRef::begin () const inline
Definition at line 31 of file DebugFrameDataSubsection.h.
classof()
static bool llvm::codeview::DebugFrameDataSubsectionRef::classof (const DebugSubsection * S) inline static
Definition at line 24 of file DebugFrameDataSubsection.h.
References llvm::codeview::FrameData, initialize(), and llvm::codeview::DebugSubsection::kind().
end()
FixedStreamArray<FrameData>::Iterator llvm::codeview::DebugFrameDataSubsectionRef::end () const inline
Definition at line 32 of file DebugFrameDataSubsection.h.
getRelocPtr()
const support::ulittle32_t* llvm::codeview::DebugFrameDataSubsectionRef::getRelocPtr () const inline
Definition at line 34 of file DebugFrameDataSubsection.h.
initialize() [1/2]
Error DebugFrameDataSubsectionRef::initialize (BinaryStreamReader Reader)
Definition at line 15 of file DebugFrameDataSubsection.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::corrupt_record, llvm::codeview::EC, llvm::codeview::FrameData, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), and llvm::Error::success().
Referenced by classof(), llvm::pdb::DbiStream::getECName(), initialize(), and llvm::codeview::visitDebugSubsection().
initialize() [2/2]
Error DebugFrameDataSubsectionRef::initialize (BinaryStreamRef Stream)
Definition at line 31 of file DebugFrameDataSubsection.cpp.
References initialize().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugFrameDataSubsection.h
lib/DebugInfo/CodeView/DebugFrameDataSubsection.cpp