LLVM: llvm::codeview::SymbolSerializer Class Reference
llvm::codeview::SymbolSerializer Class Reference
#include "llvm/DebugInfo/CodeView/SymbolSerializer.h"
Public Member Functions
SymbolSerializer (BumpPtrAllocator &Storage, CodeViewContainer Container)
Error visitSymbolBegin (CVSymbol &Record) override
Error visitSymbolEnd (CVSymbol &Record) override
Public Member Functions inherited from llvm::codeview::SymbolVisitorCallbacks
virtual ~SymbolVisitorCallbacks ()=default
virtual Error visitUnknownSymbol (CVSymbol &Record)
Action to take on unknown symbols. By default, they are ignored.
virtual Error visitSymbolBegin (CVSymbol &Record, uint32_t Offset)
Paired begin/end actions for all symbols.
Static Public Member Functions
template<typename SymType >
static CVSymbol writeOneSymbol (SymType &Sym, BumpPtrAllocator &Storage, CodeViewContainer Container)
Detailed Description
Definition at line 28 of file SymbolSerializer.h.
Constructor & Destructor Documentation
SymbolSerializer()
SymbolSerializer::SymbolSerializer (BumpPtrAllocator & Storage, CodeViewContainer Container)
Definition at line 21 of file SymbolSerializer.cpp.
Member Function Documentation
visitSymbolBegin()
Error SymbolSerializer::visitSymbolBegin (CVSymbol & Record) override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 26 of file SymbolSerializer.cpp.
References assert(), llvm::codeview::EC, llvm::Optional< T >::hasValue(), llvm::codeview::CVRecord< Kind >::kind(), llvm::BinaryStreamWriter::setOffset(), llvm::Error::success(), and llvm::codeview::SymbolRecordMapping::visitSymbolBegin().
Referenced by writeOneSymbol().
visitSymbolEnd()
Error SymbolSerializer::visitSymbolEnd (CVSymbol & Record) override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 41 of file SymbolSerializer.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::codeview::EC, llvm::BinaryStreamWriter::getOffset(), llvm::Optional< T >::hasValue(), llvm::codeview::CVRecord< Kind >::RecordData, llvm::Optional< T >::reset(), llvm::BinaryStreamWriter::setOffset(), llvm::Error::success(), llvm::codeview::SymbolRecordMapping::visitSymbolEnd(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by writeOneSymbol().
writeOneSymbol()
template<typename SymType > static CVSymbol llvm::codeview::SymbolSerializer::writeOneSymbol (SymType & Sym, BumpPtrAllocator & Storage, CodeViewContainer Container) inline static
Definition at line 52 of file SymbolSerializer.h.
References llvm::consumeError(), llvm::cl::Prefix, visitSymbolBegin(), and visitSymbolEnd().
Referenced by llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::toCodeViewSymbol().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/SymbolSerializer.h
lib/DebugInfo/CodeView/SymbolSerializer.cpp