LLVM: llvm::ReversePostOrderTraversal< GraphT, GT > Class Template Reference
llvm::ReversePostOrderTraversal< GraphT, GT > Class Template Reference
#include "llvm/ADT/PostOrderIterator.h"
Public Types
using rpo_iterator = typename std::vector< NodeRef >::reverse_iterator
using const_rpo_iterator = typename std::vector< NodeRef >::const_reverse_iterator
Public Member Functions
ReversePostOrderTraversal (GraphT G)
rpo_iterator begin ()
const_rpo_iterator begin () const
rpo_iterator end ()
const_rpo_iterator end () const
Detailed Description
template<class GraphT, class GT = GraphTraits<GraphT>>
class llvm::ReversePostOrderTraversal< GraphT, GT >
Definition at line 287 of file PostOrderIterator.h.
Member Typedef Documentation
const_rpo_iterator
template<class GraphT, class GT = GraphTraits<GraphT>> using llvm::ReversePostOrderTraversal< GraphT, GT >::const_rpo_iterator = typename std::vector<NodeRef>::const_reverse_iterator
Definition at line 298 of file PostOrderIterator.h.
rpo_iterator
template<class GraphT, class GT = GraphTraits<GraphT>> using llvm::ReversePostOrderTraversal< GraphT, GT >::rpo_iterator = typename std::vector<NodeRef>::reverse_iterator
Definition at line 297 of file PostOrderIterator.h.
Constructor & Destructor Documentation
ReversePostOrderTraversal()
template<class GraphT, class GT = GraphTraits<GraphT>> llvm::ReversePostOrderTraversal< GraphT, GT >::ReversePostOrderTraversal (GraphT G) inline
Definition at line 300 of file PostOrderIterator.h.
Member Function Documentation
begin() [1/2]
template<class GraphT, class GT = GraphTraits<GraphT>> rpo_iterator llvm::ReversePostOrderTraversal< GraphT, GT >::begin () inline
Definition at line 303 of file PostOrderIterator.h.
Referenced by collectRegDefs(), llvm::createSIWholeQuadModePass(), processDbgDeclares(), and UpdateCPSRUse().
begin() [2/2]
template<class GraphT, class GT = GraphTraits<GraphT>> const_rpo_iterator llvm::ReversePostOrderTraversal< GraphT, GT >::begin () const inline
Definition at line 304 of file PostOrderIterator.h.
end() [1/2]
template<class GraphT, class GT = GraphTraits<GraphT>> rpo_iterator llvm::ReversePostOrderTraversal< GraphT, GT >::end () inline
Definition at line 305 of file PostOrderIterator.h.
Referenced by collectRegDefs(), llvm::createSIWholeQuadModePass(), and UpdateCPSRUse().
end() [2/2]
template<class GraphT, class GT = GraphTraits<GraphT>> const_rpo_iterator llvm::ReversePostOrderTraversal< GraphT, GT >::end () const inline
Definition at line 306 of file PostOrderIterator.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/PostOrderIterator.h