LLVM: llvm::FaultMapParser::FunctionInfoAccessor Class Reference
llvm::FaultMapParser::FunctionInfoAccessor Class Reference
#include "llvm/CodeGen/FaultMaps.h"
Public Member Functions
FunctionInfoAccessor ()=default
FunctionInfoAccessor (const uint8_t *P, const uint8_t *E)
FunctionAddrType getFunctionAddr () const
NumFaultingPCsType getNumFaultingPCs () const
FunctionFaultInfoAccessor getFunctionFaultInfoAt (uint32_t Index) const
FunctionInfoAccessor getNextFunctionInfo () const
Detailed Description
Definition at line 141 of file FaultMaps.h.
Constructor & Destructor Documentation
FunctionInfoAccessor() [1/2]
llvm::FaultMapParser::FunctionInfoAccessor::FunctionInfoAccessor () default
FunctionInfoAccessor() [2/2]
llvm::FaultMapParser::FunctionInfoAccessor::FunctionInfoAccessor (const uint8_t * P, const uint8_t * E) inline explicit
Definition at line 161 of file FaultMaps.h.
Member Function Documentation
getFunctionAddr()
FunctionAddrType llvm::FaultMapParser::FunctionInfoAccessor::getFunctionAddr () const inline
Definition at line 164 of file FaultMaps.h.
References E.
Referenced by llvm::operator<<().
getFunctionFaultInfoAt()
FunctionFaultInfoAccessor llvm::FaultMapParser::FunctionInfoAccessor::getFunctionFaultInfoAt (uint32_t Index) const inline
Definition at line 172 of file FaultMaps.h.
References assert(), and Size.
Referenced by llvm::operator<<().
getNextFunctionInfo()
FunctionInfoAccessor llvm::FaultMapParser::FunctionInfoAccessor::getNextFunctionInfo () const inline
Definition at line 179 of file FaultMaps.h.
References assert(), and Size.
Referenced by llvm::operator<<().
getNumFaultingPCs()
NumFaultingPCsType llvm::FaultMapParser::FunctionInfoAccessor::getNumFaultingPCs () const inline
Definition at line 168 of file FaultMaps.h.
References E.
Referenced by llvm::operator<<().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/FaultMaps.h