LLVM: llvm::pdb::TpiStream Class Reference
llvm::pdb::TpiStream Class Reference
#include "llvm/DebugInfo/PDB/Native/TpiStream.h"
Public Member Functions
TpiStream (PDBFile &File, std::unique_ptr< msf::MappedBlockStream > Stream)
~TpiStream ()
Error reload ()
PdbRaw_TpiVer getTpiVersion () const
uint32_t TypeIndexBegin () const
uint32_t TypeIndexEnd () const
uint32_t getNumTypeRecords () const
uint16_t getTypeHashStreamIndex () const
uint16_t getTypeHashStreamAuxIndex () const
uint32_t getHashKeySize () const
uint32_t getNumHashBuckets () const
FixedStreamArray< support::ulittle32_t > getHashValues () const
FixedStreamArray< codeview::TypeIndexOffset > getTypeIndexOffsets () const
HashTable< support::ulittle32_t > & getHashAdjusters ()
codeview::CVTypeRange types (bool *HadError) const
const codeview::CVTypeArray & typeArray () const
codeview::LazyRandomTypeCollection & typeCollection ()
Expected< codeview::TypeIndex > findFullDeclForForwardRef (codeview::TypeIndex ForwardRefTI) const
std::vector< codeview::TypeIndex > findRecordsByName (StringRef Name) const
codeview::CVType getType (codeview::TypeIndex Index)
BinarySubstreamRef getTypeRecordsSubstream () const
Error commit ()
void buildHashMap ()
bool supportsTypeLookup () const
Friends
class TpiStreamBuilder
Detailed Description
Definition at line 33 of file TpiStream.h.
Constructor & Destructor Documentation
TpiStream()
TpiStream::TpiStream (PDBFile & File, std::unique_ptr< msf::MappedBlockStream > Stream)
Definition at line 36 of file TpiStream.cpp.
References ~TpiStream().
~TpiStream()
TpiStream::~TpiStream () default
Referenced by TpiStream().
Member Function Documentation
buildHashMap()
void TpiStream::buildHashMap ()
Definition at line 144 of file TpiStream.cpp.
References llvm::FixedStreamArray< T >::empty(), llvm::pdb::TpiStreamHeader::NumHashBuckets, llvm::pdb::TpiStreamHeader::TypeIndexBegin, and llvm::pdb::TpiStreamHeader::TypeIndexEnd.
Referenced by findFullDeclForForwardRef(), and findRecordsByName().
commit()
Error TpiStream::commit ()
Definition at line 246 of file TpiStream.cpp.
References llvm::Error::success().
findFullDeclForForwardRef()
Expected< TypeIndex > TpiStream::findFullDeclForForwardRef (codeview::TypeIndex ForwardRefTI) const
Definition at line 180 of file TpiStream.cpp.
References buildHashMap(), F(), llvm::codeview::TagRecord::getName(), llvm::codeview::TagRecord::getUniqueName(), llvm::pdb::hashTagRecord(), llvm::codeview::TagRecord::hasUniqueName(), llvm::codeview::isUdtForwardRef(), llvm::codeview::CVRecord< Kind >::kind(), llvm::pdb::TpiStreamHeader::NumHashBuckets, supportsTypeLookup(), and llvm::Expected< T >::takeError().
findRecordsByName()
std::vector< TypeIndex > TpiStream::findRecordsByName (StringRef Name) const
Definition at line 160 of file TpiStream.cpp.
References buildHashMap(), llvm::codeview::computeTypeName(), llvm::pdb::hashStringV1(), llvm::pdb::TpiStreamHeader::NumHashBuckets, and supportsTypeLookup().
getHashAdjusters()
HashTable< support::ulittle32_t > & TpiStream::getHashAdjusters ()
Definition at line 238 of file TpiStream.cpp.
getHashKeySize()
uint32_t TpiStream::getHashKeySize () const
Definition at line 142 of file TpiStream.cpp.
References llvm::pdb::TpiStreamHeader::HashKeySize.
getHashValues()
FixedStreamArray< support::ulittle32_t > TpiStream::getHashValues () const
Definition at line 230 of file TpiStream.cpp.
getNumHashBuckets()
uint32_t TpiStream::getNumHashBuckets () const
Definition at line 141 of file TpiStream.cpp.
References llvm::pdb::TpiStreamHeader::NumHashBuckets.
getNumTypeRecords()
uint32_t TpiStream::getNumTypeRecords () const
Definition at line 129 of file TpiStream.cpp.
References TypeIndexBegin(), and TypeIndexEnd().
Referenced by reload().
getTpiVersion()
PdbRaw_TpiVer TpiStream::getTpiVersion () const
Definition at line 120 of file TpiStream.cpp.
References llvm::pdb::TpiStreamHeader::Version.
getType()
codeview::CVType TpiStream::getType (codeview::TypeIndex Index)
Definition at line 221 of file TpiStream.cpp.
References assert(), and llvm::codeview::TypeIndex::isSimple().
getTypeHashStreamAuxIndex()
uint16_t TpiStream::getTypeHashStreamAuxIndex () const
Definition at line 137 of file TpiStream.cpp.
References llvm::pdb::TpiStreamHeader::HashAuxStreamIndex.
getTypeHashStreamIndex()
uint16_t TpiStream::getTypeHashStreamIndex () const
Definition at line 133 of file TpiStream.cpp.
References llvm::pdb::TpiStreamHeader::HashStreamIndex.
getTypeIndexOffsets()
FixedStreamArray< TypeIndexOffset > TpiStream::getTypeIndexOffsets () const
Definition at line 234 of file TpiStream.cpp.
Referenced by reload().
getTypeRecordsSubstream()
BinarySubstreamRef TpiStream::getTypeRecordsSubstream () const
Definition at line 226 of file TpiStream.cpp.
reload()
Error TpiStream::reload ()
Definition at line 41 of file TpiStream.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::consumeError(), llvm::pdb::corrupt_file, llvm::codeview::EC, getNumTypeRecords(), getTypeIndexOffsets(), llvm::pdb::TpiStreamHeader::HashAdjBuffer, llvm::pdb::TpiStreamHeader::HashKeySize, llvm::pdb::TpiStreamHeader::HashStreamIndex, llvm::pdb::TpiStreamHeader::HashValueBuffer, llvm::pdb::TpiStreamHeader::HeaderSize, llvm::AArch64CC::HS, llvm::pdb::TpiStreamHeader::IndexOffsetBuffer, llvm::pdb::kInvalidStreamIndex, llvm::pdb::TpiStreamHeader::EmbeddedBuf::Length, llvm::pdb::MaxTpiHashBuckets, llvm::pdb::MinTpiHashBuckets, llvm::pdb::TpiStreamHeader::NumHashBuckets, llvm::pdb::TpiStreamHeader::EmbeddedBuf::Off, llvm::pdb::PdbTpiV80, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), llvm::BinaryStreamReader::readSubstream(), llvm::pdb::PDBFile::safelyCreateIndexedStream(), llvm::BinarySubstreamRef::size(), llvm::BinarySubstreamRef::StreamData, llvm::Error::success(), llvm::pdb::TpiStreamHeader::TypeRecordBytes, and llvm::pdb::TpiStreamHeader::Version.
supportsTypeLookup()
bool TpiStream::supportsTypeLookup () const
Definition at line 177 of file TpiStream.cpp.
Referenced by findFullDeclForForwardRef(), and findRecordsByName().
typeArray()
const codeview::CVTypeArray& llvm::pdb::TpiStream::typeArray () const inline
Definition at line 56 of file TpiStream.h.
typeCollection()
codeview::LazyRandomTypeCollection& llvm::pdb::TpiStream::typeCollection () inline
Definition at line 58 of file TpiStream.h.
References getType(), Name, and llvm::codeview::Pdb.
Referenced by llvm::pdb::NativeTypeFunctionSig::~NativeTypeFunctionSig().
TypeIndexBegin()
uint32_t TpiStream::TypeIndexBegin () const
Definition at line 125 of file TpiStream.cpp.
References llvm::pdb::TpiStreamHeader::TypeIndexBegin.
Referenced by getNumTypeRecords().
TypeIndexEnd()
uint32_t TpiStream::TypeIndexEnd () const
Definition at line 127 of file TpiStream.cpp.
References llvm::pdb::TpiStreamHeader::TypeIndexEnd.
Referenced by getNumTypeRecords().
types()
CVTypeRange TpiStream::types (bool * HadError) const
Definition at line 242 of file TpiStream.cpp.
References llvm::VarStreamArray< ValueType, Extractor >::begin(), llvm::VarStreamArray< ValueType, Extractor >::end(), and llvm::make_range().
Friends And Related Function Documentation
TpiStreamBuilder
friend class TpiStreamBuilder friend
Definition at line 34 of file TpiStream.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/TpiStream.h
lib/DebugInfo/PDB/Native/TpiStream.cpp