LLVM: llvm::MipsSEFrameLowering Class Reference
llvm::MipsSEFrameLowering Class Reference
#include "Target/Mips/MipsSEFrameLowering.h"
Public Member Functions
MipsSEFrameLowering (const MipsSubtarget &STI)
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
Public Member Functions inherited from llvm::MipsFrameLowering
MipsFrameLowering (const MipsSubtarget &sti, Align Alignment)
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool hasBP (const MachineFunction &MF) const
bool isFPCloseToIncomingSP () const override
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
bool enableShrinkWrapping (const MachineFunction &MF) const override
Returns true if the target will correctly handle shrink wrapping.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align::None(), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::MipsFrameLowering
static const MipsFrameLowering * create (const MipsSubtarget &ST)
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Protected Member Functions inherited from llvm::MipsFrameLowering
uint64_t estimateStackSize (const MachineFunction &MF) const
Protected Attributes inherited from llvm::MipsFrameLowering
const MipsSubtarget & STI
Detailed Description
Definition at line 21 of file MipsSEFrameLowering.h.
Constructor & Destructor Documentation
MipsSEFrameLowering()
MipsSEFrameLowering::MipsSEFrameLowering (const MipsSubtarget & STI) explicit
Definition at line 398 of file MipsSEFrameLowering.cpp.
Referenced by llvm::createMipsSEFrameLowering().
Member Function Documentation
determineCalleeSaves()
void MipsSEFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 861 of file MipsSEFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::MipsFunctionInfo::createISRRegFI(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::MipsFrameLowering::estimateStackSize(), expand(), llvm::MipsSubtarget::getABI(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterInfo::getSpillAlignment(), llvm::TargetRegisterInfo::getSpillSize(), llvm::MachineFunction::getSubtarget(), llvm::MipsFrameLowering::hasBP(), llvm::MipsFrameLowering::hasFP(), llvm::MipsSubtarget::hasMSA(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MipsSubtarget::isGP64bit(), llvm::isIntN(), llvm::MipsFunctionInfo::isISR(), RA, setAliasRegs(), llvm::MipsFrameLowering::STI, and TRI.
emitEpilogue()
void MipsSEFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 688 of file MipsSEFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MipsABIInfo::ArePtrs64bit(), llvm::BuildMI(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::MachineBasicBlock::end(), llvm::DebugLoc::get(), llvm::MipsSubtarget::getABI(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MipsABIInfo::GetEhDataReg(), llvm::MipsFunctionInfo::getEhDataRegFI(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::MipsABIInfo::GetFramePtr(), llvm::MachineFunction::getFunction(), llvm::MipsABIInfo::GetGPRMoveOp(), llvm::MachineFunction::getInfo(), llvm::MipsSubtarget::getInstrInfo(), llvm::MipsFunctionInfo::getISRRegFI(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MipsABIInfo::GetNullPtr(), llvm::MipsSubtarget::getRegisterInfo(), llvm::MipsABIInfo::GetStackPtr(), llvm::MachineFrameInfo::getStackSize(), llvm::Function::hasFnAttribute(), llvm::MipsFrameLowering::hasFP(), llvm::MipsInstrInfo::loadRegFromStackSlot(), llvm::MipsFrameLowering::STI, and TII.
emitPrologue()
void MipsSEFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 401 of file MipsSEFrameLowering.cpp.
References llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::MachineFrameInfo::adjustsStack(), llvm::ISD::AND, llvm::MipsABIInfo::ArePtrs64bit(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::StringSwitch< T, R >::Case(), contains(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::StringSwitch< T, R >::Default(), E, llvm::MachineBasicBlock::end(), llvm::AArch64ISD::EXT, llvm::MachineInstr::FrameSetup, llvm::DebugLoc::get(), llvm::MipsSubtarget::getABI(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MipsABIInfo::GetEhDataReg(), llvm::MipsFunctionInfo::getEhDataRegFI(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFrameInfo(), llvm::MipsABIInfo::GetFramePtr(), llvm::MachineFunction::getFunction(), llvm::MipsABIInfo::GetGPRMoveOp(), llvm::MachineFunction::getInfo(), llvm::MipsSubtarget::getInstrInfo(), llvm::MipsFunctionInfo::getISRRegFI(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFunction::getMMI(), llvm::MipsABIInfo::GetNullPtr(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MipsABIInfo::GetPtrAddiuOp(), llvm::MachineFunction::getRegInfo(), llvm::MCContext::getRegisterInfo(), llvm::MipsSubtarget::getRegisterInfo(), llvm::MipsSubtarget::getRelocationModel(), llvm::MipsABIInfo::GetStackPtr(), llvm::MachineFrameInfo::getStackSize(), llvm::Attribute::getValueAsString(), llvm::MipsFrameLowering::hasBP(), llvm::Function::hasFnAttribute(), llvm::MipsFrameLowering::hasFP(), llvm::MipsSubtarget::hasMips32r2(), llvm::MipsSubtarget::hasMips64(), I, llvm::MipsSubtarget::isABI_N64(), llvm::MipsSubtarget::isABI_O32(), llvm::isInt< 16 >(), llvm::MipsSubtarget::isLittle(), llvm::MachineBasicBlock::isLiveIn(), llvm::MipsABIInfo::IsN64(), MRI, Reg, llvm::report_fatal_error(), llvm::MachineInstrBuilder::setMIFlag(), llvm::Reloc::Static, llvm::MipsFrameLowering::STI, llvm::MipsInstrInfo::storeRegToStack(), std::swap(), TII, and llvm::MipsSubtarget::useSoftFloat().
getFrameIndexReference()
int MipsSEFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
Returns the displacement from the frame register to the stack frame of the specified index, along with the frame register used (in output arg FrameReg).
The offset is returned directly, and the base register is returned via FrameReg.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 777 of file MipsSEFrameLowering.cpp.
References llvm::MipsSubtarget::getABI(), llvm::MipsABIInfo::GetBasePtr(), llvm::MachineFunction::getFrameInfo(), llvm::MipsABIInfo::GetFramePtr(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getOffsetAdjustment(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::MipsABIInfo::GetStackPtr(), llvm::MachineFrameInfo::getStackSize(), llvm::MipsFrameLowering::hasBP(), llvm::MipsFrameLowering::hasFP(), llvm::MachineFrameInfo::isFixedObjectIndex(), spillCalleeSavedRegisters(), and llvm::MipsFrameLowering::STI.
hasReservedCallFrame()
bool MipsSEFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 843 of file MipsSEFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::isInt< 16 >().
spillCalleeSavedRegisters()
bool MipsSEFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 793 of file MipsSEFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MipsABIInfo::ArePtrs64bit(), llvm::BuildMI(), llvm::numbers::e, llvm::MachineInstr::FrameSetup, llvm::MCInstrInfo::get(), llvm::MipsSubtarget::getABI(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MipsSubtarget::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::Function::hasFnAttribute(), llvm::MachineFrameInfo::isReturnAddressTaken(), llvm::MipsISD::MFHI, llvm::MipsISD::MFLO, RA, Reg, llvm::MipsFrameLowering::STI, llvm::TargetInstrInfo::storeRegToStackSlot(), and TII.
Referenced by getFrameIndexReference().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsSEFrameLowering.h
lib/Target/Mips/MipsSEFrameLowering.cpp