LLVM: llvm::AppleAcceleratorTable::ValueIterator Class Reference
llvm::AppleAcceleratorTable::ValueIterator Class Reference
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
ValueIterator (const AppleAcceleratorTable &AccelTable, uint64_t DataOffset)
Construct a new iterator for the entries at DataOffset.
ValueIterator ()=default
End marker.
const Entry & operator* () const
ValueIterator & operator++ ()
ValueIterator operator++ (int)
Friends
bool operator== (const ValueIterator &A, const ValueIterator &B)
bool operator!= (const ValueIterator &A, const ValueIterator &B)
Detailed Description
Definition at line 143 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
ValueIterator() [1/2]
AppleAcceleratorTable::ValueIterator::ValueIterator (const AppleAcceleratorTable & AccelTable, uint64_t DataOffset)
Construct a new iterator for the entries at DataOffset.
Definition at line 304 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFAcceleratorTable::AccelSection, assert(), llvm::DataExtractor::getU32(), and llvm::DataExtractor::isValidOffsetForDataOfSize().
ValueIterator() [2/2]
llvm::AppleAcceleratorTable::ValueIterator::ValueIterator () default
End marker.
Referenced by llvm::AppleAcceleratorTable::equal_range(), and llvm::DWARFDebugNames::NameIndex::equal_range().
Member Function Documentation
operator*()
const Entry& llvm::AppleAcceleratorTable::ValueIterator::operator* () const inline
Definition at line 158 of file DWARFAcceleratorTable.h.
operator++() [1/2]
ValueIterator& llvm::AppleAcceleratorTable::ValueIterator::operator++ () inline
Definition at line 159 of file DWARFAcceleratorTable.h.
operator++() [2/2]
ValueIterator llvm::AppleAcceleratorTable::ValueIterator::operator++ (int) inline
Definition at line 160 of file DWARFAcceleratorTable.h.
References I.
Friends And Related Function Documentation
operator!=
bool operator!= (const ValueIterator & A, const ValueIterator & B) friend
Definition at line 168 of file DWARFAcceleratorTable.h.
operator==
bool operator== (const ValueIterator & A, const ValueIterator & B) friend
Definition at line 165 of file DWARFAcceleratorTable.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp