LLVM: llvm::mca::DefaultResourceStrategy Class Reference
llvm::mca::DefaultResourceStrategy Class Reference final
Default resource allocation strategy used by processor resource groups and processor resources with multiple units.
#include "llvm/MCA/HardwareUnits/ResourceManager.h"
Public Member Functions
DefaultResourceStrategy (uint64_t UnitMask)
virtual ~DefaultResourceStrategy ()=default
uint64_t select (uint64_t ReadyMask) override
Selects a processor resource unit from a ReadyMask.
void used (uint64_t Mask) override
Called by the ResourceManager when a processor resource group, or a processor resource with multiple units has become unavailable.
Public Member Functions inherited from llvm::mca::ResourceStrategy
ResourceStrategy ()
virtual ~ResourceStrategy ()
Detailed Description
Default resource allocation strategy used by processor resource groups and processor resources with multiple units.
Definition at line 68 of file ResourceManager.h.
Constructor & Destructor Documentation
DefaultResourceStrategy()
llvm::mca::DefaultResourceStrategy::DefaultResourceStrategy (uint64_t UnitMask) inline
Definition at line 121 of file ResourceManager.h.
References llvm::BitmaskEnumDetail::Mask(), llvm::mca::ResourceStrategy::select(), and llvm::mca::ResourceStrategy::used().
~DefaultResourceStrategy()
virtual llvm::mca::DefaultResourceStrategy::~DefaultResourceStrategy () virtual default
Member Function Documentation
select()
uint64_t llvm::mca::DefaultResourceStrategy::select (uint64_t ReadyMask) override virtual
Selects a processor resource unit from a ReadyMask.
Implements llvm::mca::ResourceStrategy.
Definition at line 34 of file ResourceManager.cpp.
References llvm::mca::selectImpl().
used()
void llvm::mca::DefaultResourceStrategy::used (uint64_t ResourceMask) override virtual
Called by the ResourceManager when a processor resource group, or a processor resource with multiple units has become unavailable.
The default strategy uses this information to bias its selection logic.
Reimplemented from llvm::mca::ResourceStrategy.
Definition at line 51 of file ResourceManager.cpp.
References llvm::BitmaskEnumDetail::Mask().
The documentation for this class was generated from the following files:
include/llvm/MCA/HardwareUnits/ResourceManager.h
lib/MCA/HardwareUnits/ResourceManager.cpp