LLVM: llvm::AMDGPUAA Class Reference
llvm::AMDGPUAA Class Reference
Analysis pass providing a never-invalidated alias analysis result.
#include "Target/AMDGPU/AMDGPUAliasAnalysis.h"
Public Types
using Result = AMDGPUAAResult
Public Member Functions
AMDGPUAAResult run (Function &F, AnalysisManager< Function > &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< AMDGPUAA >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUAA >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Analysis pass providing a never-invalidated alias analysis result.
Definition at line 58 of file AMDGPUAliasAnalysis.h.
Member Typedef Documentation
Result
using llvm::AMDGPUAA::Result = AMDGPUAAResult
Definition at line 64 of file AMDGPUAliasAnalysis.h.
Member Function Documentation
run()
AMDGPUAAResult llvm::AMDGPUAA::run (Function & F, AnalysisManager< Function > & AM) inline
Definition at line 66 of file AMDGPUAliasAnalysis.h.
References llvm::AMDGPUAAResult::AMDGPUAAResult(), llvm::Module::getDataLayout(), llvm::GlobalValue::getParent(), and llvm::Module::getTargetTriple().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPUAliasAnalysis.h