LLVM: llvm::Comdat Class Reference
llvm::Comdat Class Reference
#include "llvm/IR/Comdat.h"
Public Types
enum SelectionKind {
Any, ExactMatch, Largest, NoDuplicates,
SameSize
}
Public Member Functions
Comdat (const Comdat &)=delete
Comdat (Comdat &&C)
SelectionKind getSelectionKind () const
void setSelectionKind (SelectionKind Val)
StringRef getName () const
void print (raw_ostream &OS, bool IsForDebug=false) const
void dump () const
Friends
class Module
Detailed Description
Definition at line 31 of file Comdat.h.
Member Enumeration Documentation
SelectionKind
enum llvm::Comdat::SelectionKind
Enumerator
Any
The linker may choose any COMDAT.
ExactMatch
The data referenced by the COMDAT must be the same.
Largest
The linker will choose the largest COMDAT.
NoDuplicates
No other Module may specify this COMDAT.
SameSize
The data referenced by the COMDAT must be the same size.
Definition at line 33 of file Comdat.h.
Constructor & Destructor Documentation
Comdat() [1/2]
llvm::Comdat::Comdat (const Comdat &) delete
Comdat() [2/2]
Comdat::Comdat (Comdat && C)
Definition at line 22 of file Comdat.cpp.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void Comdat::dump () const
Definition at line 4481 of file AsmWriter.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
Referenced by setSelectionKind().
getName()
StringRef Comdat::getName () const
Definition at line 26 of file Comdat.cpp.
References Name.
Referenced by canRenameComdat(), checkMachOComdat(), copyComdat(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::AsmPrinter::emitXRayTable(), getComdatGVForCOFF(), getELFComdat(), getMinVisibility(), getWasmComdat(), maybePrintComdat(), and setSelectionKind().
getSelectionKind()
SelectionKind llvm::Comdat::getSelectionKind () const inline
Definition at line 44 of file Comdat.h.
Referenced by canRenameComdat(), copyComdat(), getELFComdat(), getEncodedComdatSelectionKind(), getMinVisibility(), getWasmComdat(), and LLVMGetComdatSelectionKind().
print()
void Comdat::print (raw_ostream & OS, bool IsForDebug = false) const
Definition at line 4265 of file AsmWriter.cpp.
References Any, ComdatPrefix, ExactMatch, getName(), Largest, NoDuplicates, PrintLLVMName(), and SameSize.
Referenced by maybePrintComdat(), and setSelectionKind().
setSelectionKind()
void llvm::Comdat::setSelectionKind (SelectionKind Val) inline
Definition at line 45 of file Comdat.h.
References dump(), getName(), and print().
Referenced by AddCalls(), canRenameComdat(), copyComdat(), getArrayElements(), llvm::GetOrCreateFunctionComdat(), instrumentMaskedLoadOrStore(), LLVMSetComdatSelectionKind(), and rewriteComdat().
Friends And Related Function Documentation
Module
friend class Module friend
Definition at line 51 of file Comdat.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Comdat.h
lib/IR/AsmWriter.cpp
lib/IR/Comdat.cpp