LLVM: llvm::LiveIntervalUnion Class Reference
llvm::LiveIntervalUnion Class Reference
Union of live intervals that are strong candidates for coalescing into a single register (either physical or virtual depending on the context).
#include "llvm/CodeGen/LiveIntervalUnion.h"
Classes
class Array
class Query
Query interferences between a single live virtual register and a live interval union.
Public Types
using SegmentIter = LiveSegments::iterator
using ConstSegmentIter = LiveSegments::const_iterator
Const version of SegmentIter.
using Allocator = LiveSegments::Allocator
using Map = LiveSegments
Public Member Functions
LiveIntervalUnion (Allocator &a)
SegmentIter begin ()
SegmentIter end ()
SegmentIter find (SlotIndex x)
ConstSegmentIter begin () const
ConstSegmentIter end () const
ConstSegmentIter find (SlotIndex x) const
bool empty () const
SlotIndex startIndex () const
SlotIndex endIndex () const
const Map & getMap () const
unsigned getTag () const
getTag - Return an opaque tag representing the current state of the union.
bool changedSince (unsigned tag) const
changedSince - Return true if the union change since getTag returned tag.
void unify (LiveInterval &VirtReg, const LiveRange &Range)
void extract (LiveInterval &VirtReg, const LiveRange &Range)
void clear ()
void print (raw_ostream &OS, const TargetRegisterInfo *TRI) const
void verify (LiveVirtRegBitSet &VisitedVRegs)
Detailed Description
Union of live intervals that are strong candidates for coalescing into a single register (either physical or virtual depending on the context).
We expect the constituent live intervals to be disjoint, although we may eventually make exceptions to handle value-based interference.
Definition at line 42 of file LiveIntervalUnion.h.
Member Typedef Documentation
Allocator
using llvm::LiveIntervalUnion::Allocator = LiveSegments::Allocator
Definition at line 58 of file LiveIntervalUnion.h.
ConstSegmentIter
using llvm::LiveIntervalUnion::ConstSegmentIter = LiveSegments::const_iterator
Const version of SegmentIter.
Definition at line 55 of file LiveIntervalUnion.h.
Map
using llvm::LiveIntervalUnion::Map = LiveSegments
Definition at line 81 of file LiveIntervalUnion.h.
SegmentIter
using llvm::LiveIntervalUnion::SegmentIter = LiveSegments::iterator
Definition at line 52 of file LiveIntervalUnion.h.
Constructor & Destructor Documentation
LiveIntervalUnion()
llvm::LiveIntervalUnion::LiveIntervalUnion (Allocator & a) inline explicit
Definition at line 65 of file LiveIntervalUnion.h.
Referenced by llvm::LiveIntervalUnion::Array::clear().
Member Function Documentation
begin() [1/2]
SegmentIter llvm::LiveIntervalUnion::begin () inline
Definition at line 69 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::begin().
begin() [2/2]
ConstSegmentIter llvm::LiveIntervalUnion::begin () const inline
Definition at line 72 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::begin().
changedSince()
bool llvm::LiveIntervalUnion::changedSince (unsigned tag) const inline
changedSince - Return true if the union change since getTag returned tag.
Definition at line 88 of file LiveIntervalUnion.h.
References extract(), and unify().
Referenced by llvm::LiveIntervalUnion::Query::init().
clear()
void llvm::LiveIntervalUnion::clear () inline
Definition at line 97 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::clear(), print(), TRI, and verify().
Referenced by llvm::LiveIntervalUnion::Array::size(), and llvm::LiveIntervalUnion::Array::~Array().
empty()
bool llvm::LiveIntervalUnion::empty () const inline
Definition at line 76 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::empty().
Referenced by print().
end() [1/2]
SegmentIter llvm::LiveIntervalUnion::end () inline
Definition at line 70 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::end().
end() [2/2]
ConstSegmentIter llvm::LiveIntervalUnion::end () const inline
Definition at line 73 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::end().
endIndex()
SlotIndex llvm::LiveIntervalUnion::endIndex () const inline
Definition at line 78 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::stop().
extract()
void LiveIntervalUnion::extract (LiveInterval & VirtReg, const LiveRange & Range)
Definition at line 56 of file LiveIntervalUnion.cpp.
References llvm::LiveRange::advanceTo(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo(), assert(), llvm::LiveRange::begin(), llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::find(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::start(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::value().
Referenced by changedSince().
find() [1/2]
SegmentIter llvm::LiveIntervalUnion::find (SlotIndex x) inline
Definition at line 71 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::find().
find() [2/2]
ConstSegmentIter llvm::LiveIntervalUnion::find (SlotIndex x) const inline
Definition at line 74 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::find().
getMap()
const Map& llvm::LiveIntervalUnion::getMap () const inline
Definition at line 82 of file LiveIntervalUnion.h.
getTag()
unsigned llvm::LiveIntervalUnion::getTag () const inline
getTag - Return an opaque tag representing the current state of the union.
Definition at line 85 of file LiveIntervalUnion.h.
print()
void LiveIntervalUnion::print (raw_ostream & OS, const TargetRegisterInfo * TRI) const
Definition at line 82 of file LiveIntervalUnion.cpp.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::begin(), empty(), llvm::printReg(), SI, and TRI.
Referenced by clear().
startIndex()
SlotIndex llvm::LiveIntervalUnion::startIndex () const inline
Definition at line 77 of file LiveIntervalUnion.h.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::start().
unify()
void LiveIntervalUnion::unify (LiveInterval & VirtReg, const LiveRange & Range)
Definition at line 29 of file LiveIntervalUnion.cpp.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo(), llvm::LiveRange::begin(), llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::IntervalMap< KeyT, ValT, N, Traits >::find(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid().
Referenced by changedSince().
verify()
void LiveIntervalUnion::verify (LiveVirtRegBitSet & VisitedVRegs)
Definition at line 96 of file LiveIntervalUnion.cpp.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::begin(), llvm::SparseBitVector< ElementSize >::set(), and SI.
Referenced by clear().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveIntervalUnion.h
lib/CodeGen/LiveIntervalUnion.cpp