LLVM: llvm::vfs::detail::InMemoryNode Class Reference
llvm::vfs::detail::InMemoryNode Class Reference abstract
The in memory file system is a tree of Nodes.
Public Member Functions
InMemoryNode (llvm::StringRef FileName, InMemoryNodeKind Kind)
virtual ~InMemoryNode ()=default
StringRef getFileName () const
Get the filename of this node (the name without the directory part).
InMemoryNodeKind getKind () const
virtual std::string toString (unsigned Indent) const =0
Detailed Description
The in memory file system is a tree of Nodes.
Every node can either be a file , hardlink or a directory.
Definition at line 532 of file VirtualFileSystem.cpp.
Constructor & Destructor Documentation
InMemoryNode()
llvm::vfs::detail::InMemoryNode::InMemoryNode (llvm::StringRef FileName, InMemoryNodeKind Kind) inline
Definition at line 537 of file VirtualFileSystem.cpp.
~InMemoryNode()
virtual llvm::vfs::detail::InMemoryNode::~InMemoryNode () virtual default
Member Function Documentation
getFileName()
StringRef llvm::vfs::detail::InMemoryNode::getFileName () const inline
Get the filename of this node (the name without the directory part).
Definition at line 542 of file VirtualFileSystem.cpp.
getKind()
InMemoryNodeKind llvm::vfs::detail::InMemoryNode::getKind () const inline
Definition at line 543 of file VirtualFileSystem.cpp.
References llvm::toString().
Referenced by llvm::vfs::detail::InMemoryFile::classof(), and llvm::vfs::detail::InMemoryDirectory::classof().
toString()
virtual std::string llvm::vfs::detail::InMemoryNode::toString (unsigned Indent) const pure virtual
Implemented in llvm::vfs::detail::InMemoryDirectory, and llvm::vfs::detail::InMemoryFile.
The documentation for this class was generated from the following file:
lib/Support/VirtualFileSystem.cpp