LLVM: llvm::mca::InstRef Class Reference
llvm::mca::InstRef Class Reference
An InstRef contains both a SourceMgr index and Instruction pair.
#include "llvm/MCA/Instruction.h"
Public Member Functions
InstRef ()
InstRef (unsigned Index, Instruction *I)
bool operator== (const InstRef &Other) const
bool operator!= (const InstRef &Other) const
bool operator< (const InstRef &Other) const
unsigned getSourceIndex () const
Instruction * getInstruction ()
const Instruction * getInstruction () const
operator bool () const
Returns true if this references a valid instruction.
void invalidate ()
Invalidate this reference.
void print (raw_ostream &OS) const
Detailed Description
An InstRef contains both a SourceMgr index and Instruction pair.
The index is used as a unique identifier for the instruction. MCA will make use of this index as a key throughout MCA.
Definition at line 562 of file Instruction.h.
Constructor & Destructor Documentation
InstRef() [1/2]
llvm::mca::InstRef::InstRef () inline
Definition at line 566 of file Instruction.h.
InstRef() [2/2]
llvm::mca::InstRef::InstRef (unsigned Index, Instruction * I) inline
Definition at line 567 of file Instruction.h.
Member Function Documentation
getInstruction() [1/2]
Instruction* llvm::mca::InstRef::getInstruction () inline
Definition at line 576 of file Instruction.h.
Referenced by llvm::mca::Scheduler::analyzeDataDependencies(), llvm::mca::RetireControlUnit::consumeCurrentToken(), llvm::mca::Scheduler::cycleEvent(), llvm::mca::RetireControlUnit::dispatch(), llvm::mca::Scheduler::dispatch(), llvm::mca::LSUnit::dispatch(), llvm::mca::DispatchStage::DispatchStage(), llvm::mca::InstructionTables::execute(), llvm::mca::RetireStage::execute(), llvm::mca::ExecuteStage::execute(), llvm::mca::RetireControlUnit::getCurrentToken(), llvm::mca::LSUnitBase::hasDependentUsers(), llvm::mca::ExecuteStage::isAvailable(), llvm::mca::DispatchStage::isAvailable(), llvm::mca::Scheduler::isAvailable(), llvm::mca::LSUnit::isAvailable(), llvm::mca::LSUnitBase::isPending(), llvm::mca::LSUnitBase::isReady(), llvm::mca::Scheduler::issueInstruction(), llvm::mca::LSUnitBase::isWaiting(), llvm::mca::Scheduler::mustIssueImmediately(), llvm::mca::RetireStage::notifyInstructionRetired(), llvm::mca::ExecuteStage::notifyReservedOrReleasedBuffers(), llvm::mca::MemoryGroup::onGroupIssued(), llvm::mca::LSUnitBase::onInstructionExecuted(), llvm::mca::LSUnit::onInstructionExecuted(), llvm::mca::MemoryGroup::onInstructionIssued(), llvm::mca::LSUnitBase::onInstructionIssued(), llvm::mca::LSUnitBase::onInstructionRetired(), llvm::mca::Scheduler::select(), and llvm::mca::verifyInstructionEliminated().
getInstruction() [2/2]
const Instruction* llvm::mca::InstRef::getInstruction () const inline
Definition at line 577 of file Instruction.h.
getSourceIndex()
unsigned llvm::mca::InstRef::getSourceIndex () const inline
Definition at line 575 of file Instruction.h.
Referenced by llvm::mca::DefaultSchedulerStrategy::compare(), llvm::mca::DispatchStage::DispatchStage(), llvm::mca::Scheduler::isAvailable(), llvm::mca::MemoryGroup::onGroupIssued(), and llvm::mca::LSUnitBase::onInstructionRetired().
invalidate()
void llvm::mca::InstRef::invalidate () inline
Invalidate this reference.
Definition at line 583 of file Instruction.h.
Referenced by llvm::mca::EntryStage::execute(), llvm::mca::Scheduler::issueInstruction(), and llvm::mca::Scheduler::select().
operator bool()
llvm::mca::InstRef::operator bool () const inline explicit
Returns true if this references a valid instruction.
Definition at line 580 of file Instruction.h.
operator!=()
bool llvm::mca::InstRef::operator!= (const InstRef & Other) const inline
Definition at line 570 of file Instruction.h.
operator<()
bool llvm::mca::InstRef::operator< (const InstRef & Other) const inline
Definition at line 571 of file Instruction.h.
operator==()
bool llvm::mca::InstRef::operator== (const InstRef & Other) const inline
Definition at line 569 of file Instruction.h.
print()
void llvm::mca::InstRef::print (raw_ostream & OS) const inline
Definition at line 586 of file Instruction.h.
Referenced by llvm::mca::operator<<().
The documentation for this class was generated from the following file:
include/llvm/MCA/Instruction.h