LLVM: llvm::MachineInstr Class Reference
llvm::MachineInstr Class Reference
Representation of each machine instruction.
#include "llvm/CodeGen/MachineInstr.h"
Public Types
enum CommentFlag { ReloadReuse = 0x1, NoSchedComment = 0x2, TAsmComments = 0x4 }
Flags to specify different kinds of comments to output in assembly code.
enum MIFlag {
NoFlags = 0, FrameSetup = 1 << 0, FrameDestroy = 1 << 1, BundledPred = 1 << 2,
BundledSucc = 1 << 3, FmNoNans = 1 << 4, FmNoInfs = 1 << 5, FmNsz = 1 << 6,
FmArcp = 1 << 7, FmContract = 1 << 8, FmAfn = 1 << 9, FmReassoc = 1 << 10,
NoUWrap = 1 << 11, NoSWrap = 1 << 12, IsExact = 1 << 13, NoFPExcept = 1 << 14
}
enum QueryType { IgnoreBundle, AnyInBundle, AllInBundle }
API for querying MachineInstr properties.
enum MICheckType { CheckDefs, CheckKillDead, IgnoreDefs, IgnoreVRegDefs }
using mmo_iterator = ArrayRef< MachineMemOperand * >::iterator
using mop_iterator = MachineOperand *
iterator/begin/end - Iterate over all operands of a machine instruction.
using const_mop_iterator = const MachineOperand *
Public Member Functions
MachineInstr (const MachineInstr &)=delete
MachineInstr & operator= (const MachineInstr &)=delete
~MachineInstr ()=delete
const MachineBasicBlock * getParent () const
MachineBasicBlock * getParent ()
const MachineFunction * getMF () const
Return the function that contains the basic block that this instruction belongs to.
MachineFunction * getMF ()
uint8_t getAsmPrinterFlags () const
Return the asm printer flags bitvector.
void clearAsmPrinterFlags ()
Clear the AsmPrinter bitvector.
bool getAsmPrinterFlag (CommentFlag Flag) const
Return whether an AsmPrinter flag is set.
void setAsmPrinterFlag (uint8_t Flag)
Set a flag for the AsmPrinter.
void clearAsmPrinterFlag (CommentFlag Flag)
Clear specific AsmPrinter flags.
uint16_t getFlags () const
Return the MI flags bitvector.
bool getFlag (MIFlag Flag) const
Return whether an MI flag is set.
void setFlag (MIFlag Flag)
Set a MI flag.
void setFlags (unsigned flags)
void clearFlag (MIFlag Flag)
clearFlag - Clear a MI flag.
bool isInsideBundle () const
Return true if MI is in a bundle (but not the first MI in a bundle).
bool isBundled () const
Return true if this instruction part of a bundle.
bool isBundledWithPred () const
Return true if this instruction is part of a bundle, and it is not the first instruction in the bundle.
bool isBundledWithSucc () const
Return true if this instruction is part of a bundle, and it is not the last instruction in the bundle.
void bundleWithPred ()
Bundle this instruction with its predecessor.
void bundleWithSucc ()
Bundle this instruction with its successor.
void unbundleFromPred ()
Break bundle above this instruction.
void unbundleFromSucc ()
Break bundle below this instruction.
const DebugLoc & getDebugLoc () const
Returns the debug location id of this MachineInstr.
const DILocalVariable * getDebugVariable () const
Return the debug variable referenced by this DBG_VALUE instruction.
const DIExpression * getDebugExpression () const
Return the complex address expression referenced by this DBG_VALUE instruction.
const DILabel * getDebugLabel () const
Return the debug label referenced by this DBG_LABEL instruction.
void emitError (StringRef Msg) const
Emit an error referring to the source location of this instruction.
const MCInstrDesc & getDesc () const
Returns the target instruction descriptor of this MachineInstr.
unsigned getOpcode () const
Returns the opcode of this MachineInstr.
unsigned getNumOperands () const
Retuns the total number of operands.
const MachineOperand & getOperand (unsigned i) const
MachineOperand & getOperand (unsigned i)
unsigned getNumDefs () const
Returns the total number of definitions.
bool hasImplicitDef () const
Returns true if the instruction has implicit definition.
unsigned getNumImplicitOperands () const
Returns the implicit operands number.
bool isOperandSubregIdx (unsigned OpIdx) const
Return true if operand OpIdx is a subregister index.
unsigned getNumExplicitOperands () const
Returns the number of non-implicit operands.
unsigned getNumExplicitDefs () const
Returns the number of non-implicit definitions.
mop_iterator operands_begin ()
mop_iterator operands_end ()
const_mop_iterator operands_begin () const
const_mop_iterator operands_end () const
iterator_range< mop_iterator > operands ()
iterator_range< const_mop_iterator > operands () const
iterator_range< mop_iterator > explicit_operands ()
iterator_range< const_mop_iterator > explicit_operands () const
iterator_range< mop_iterator > implicit_operands ()
iterator_range< const_mop_iterator > implicit_operands () const
iterator_range< mop_iterator > defs ()
Returns a range over all explicit operands that are register definitions.
iterator_range< const_mop_iterator > defs () const
Returns a range over all explicit operands that are register definitions.
iterator_range< mop_iterator > uses ()
Returns a range that includes all operands that are register uses.
iterator_range< const_mop_iterator > uses () const
Returns a range that includes all operands that are register uses.
iterator_range< mop_iterator > explicit_uses ()
iterator_range< const_mop_iterator > explicit_uses () const
unsigned getOperandNo (const_mop_iterator I) const
Returns the number of the operand iterator I points to.
ArrayRef< MachineMemOperand * > memoperands () const
Access to memory operands of the instruction.
mmo_iterator memoperands_begin () const
Access to memory operands of the instruction.
mmo_iterator memoperands_end () const
Access to memory operands of the instruction.
bool memoperands_empty () const
Return true if we don't have any memory operands which described the memory access done by this instruction.
bool hasOneMemOperand () const
Return true if this instruction has exactly one MachineMemOperand.
unsigned getNumMemOperands () const
Return the number of memory operands.
MCSymbol * getPreInstrSymbol () const
Helper to extract a pre-instruction symbol if one has been added.
MCSymbol * getPostInstrSymbol () const
Helper to extract a post-instruction symbol if one has been added.
MDNode * getHeapAllocMarker () const
Helper to extract a heap alloc marker if one has been added.
bool hasProperty (unsigned MCFlag, QueryType Type=AnyInBundle) const
Return true if the instruction (or in the case of a bundle, the instructions inside the bundle) has the specified property.
bool isPreISelOpcode (QueryType Type=IgnoreBundle) const
Return true if this is an instruction that should go through the usual legalization steps.
bool isVariadic (QueryType Type=IgnoreBundle) const
Return true if this instruction can have a variable number of operands.
bool hasOptionalDef (QueryType Type=IgnoreBundle) const
Set if this instruction has an optional definition, e.g.
bool isPseudo (QueryType Type=IgnoreBundle) const
Return true if this is a pseudo instruction that doesn't correspond to a real machine instruction.
bool isReturn (QueryType Type=AnyInBundle) const
bool isEHScopeReturn (QueryType Type=AnyInBundle) const
Return true if this is an instruction that marks the end of an EH scope, i.e., a catchpad or a cleanuppad instruction.
bool isCall (QueryType Type=AnyInBundle) const
bool isBarrier (QueryType Type=AnyInBundle) const
Returns true if the specified instruction stops control flow from executing the instruction immediately following it.
bool isTerminator (QueryType Type=AnyInBundle) const
Returns true if this instruction part of the terminator for a basic block.
bool isBranch (QueryType Type=AnyInBundle) const
Returns true if this is a conditional, unconditional, or indirect branch.
bool isIndirectBranch (QueryType Type=AnyInBundle) const
Return true if this is an indirect branch, such as a branch through a register.
bool isConditionalBranch (QueryType Type=AnyInBundle) const
Return true if this is a branch which may fall through to the next instruction or may transfer control flow to some other block.
bool isUnconditionalBranch (QueryType Type=AnyInBundle) const
Return true if this is a branch which always transfers control flow to some other block.
bool isPredicable (QueryType Type=AllInBundle) const
Return true if this instruction has a predicate operand that controls execution.
bool isCompare (QueryType Type=IgnoreBundle) const
Return true if this instruction is a comparison.
bool isMoveImmediate (QueryType Type=IgnoreBundle) const
Return true if this instruction is a move immediate (including conditional moves) instruction.
bool isMoveReg (QueryType Type=IgnoreBundle) const
Return true if this instruction is a register move.
bool isBitcast (QueryType Type=IgnoreBundle) const
Return true if this instruction is a bitcast instruction.
bool isSelect (QueryType Type=IgnoreBundle) const
Return true if this instruction is a select instruction.
bool isNotDuplicable (QueryType Type=AnyInBundle) const
Return true if this instruction cannot be safely duplicated.
bool isConvergent (QueryType Type=AnyInBundle) const
Return true if this instruction is convergent.
bool hasDelaySlot (QueryType Type=AnyInBundle) const
Returns true if the specified instruction has a delay slot which must be filled by the code generator.
bool canFoldAsLoad (QueryType Type=IgnoreBundle) const
Return true for instructions that can be folded as memory operands in other instructions.
bool isRegSequenceLike (QueryType Type=IgnoreBundle) const
Return true if this instruction behaves the same way as the generic REG_SEQUENCE instructions.
bool isExtractSubregLike (QueryType Type=IgnoreBundle) const
Return true if this instruction behaves the same way as the generic EXTRACT_SUBREG instructions.
bool isInsertSubregLike (QueryType Type=IgnoreBundle) const
Return true if this instruction behaves the same way as the generic INSERT_SUBREG instructions.
bool mayLoad (QueryType Type=AnyInBundle) const
Return true if this instruction could possibly read memory.
bool mayStore (QueryType Type=AnyInBundle) const
Return true if this instruction could possibly modify memory.
bool mayLoadOrStore (QueryType Type=AnyInBundle) const
Return true if this instruction could possibly read or modify memory.
bool mayRaiseFPException () const
Return true if this instruction could possibly raise a floating-point exception.
bool isCommutable (QueryType Type=IgnoreBundle) const
Return true if this may be a 2- or 3-address instruction (of the form "X = op Y, Z, ..."), which produces the same result if Y and Z are exchanged.
bool isConvertibleTo3Addr (QueryType Type=IgnoreBundle) const
Return true if this is a 2-address instruction which can be changed into a 3-address instruction if needed.
bool usesCustomInsertionHook (QueryType Type=IgnoreBundle) const
Return true if this instruction requires custom insertion support when the DAG scheduler is inserting it into a machine basic block.
bool hasPostISelHook (QueryType Type=IgnoreBundle) const
Return true if this instruction requires adjustment after instruction selection by calling a target hook.
bool isRematerializable (QueryType Type=AllInBundle) const
Returns true if this instruction is a candidate for remat.
bool isAsCheapAsAMove (QueryType Type=AllInBundle) const
Returns true if this instruction has the same cost (or less) than a move instruction.
bool hasExtraSrcRegAllocReq (QueryType Type=AnyInBundle) const
Returns true if this instruction source operands have special register allocation requirements that are not captured by the operand register classes.
bool hasExtraDefRegAllocReq (QueryType Type=AnyInBundle) const
Returns true if this instruction def operands have special register allocation requirements that are not captured by the operand register classes.
bool isIdenticalTo (const MachineInstr &Other, MICheckType Check=CheckDefs) const
Return true if this instruction is identical to Other.
MachineInstr * removeFromParent ()
Unlink 'this' from the containing basic block, and return it without deleting it.
MachineInstr * removeFromBundle ()
Unlink this instruction from its basic block and return it without deleting it.
void eraseFromParent ()
Unlink 'this' from the containing basic block and delete it.
void eraseFromParentAndMarkDBGValuesForRemoval ()
Unlink 'this' from the containing basic block and delete it.
void eraseFromBundle ()
Unlink 'this' form its basic block and delete it.
bool isEHLabel () const
bool isGCLabel () const
bool isAnnotationLabel () const
bool isLabel () const
Returns true if the MachineInstr represents a label.
bool isCFIInstruction () const
bool isPosition () const
bool isDebugValue () const
bool isDebugLabel () const
bool isDebugInstr () const
bool isIndirectDebugValue () const
A DBG_VALUE is indirect iff the first operand is a register and the second operand is an immediate.
bool isDebugEntryValue () const
A DBG_VALUE is an entry value iff its debug expression contains the DW_OP_LLVM_entry_value operation.
bool isUndefDebugValue () const
Return true if the instruction is a debug value which describes a part of a variable as unavailable.
bool isPHI () const
bool isKill () const
bool isImplicitDef () const
bool isInlineAsm () const
bool isMSInlineAsm () const
FIXME: Seems like a layering violation that the AsmDialect, which is X86 specific, be attached to a generic MachineInstr.
bool isStackAligningInlineAsm () const
InlineAsm::AsmDialect getInlineAsmDialect () const
bool isInsertSubreg () const
bool isSubregToReg () const
bool isRegSequence () const
bool isBundle () const
bool isCopy () const
bool isFullCopy () const
bool isExtractSubreg () const
bool isCopyLike () const
Return true if the instruction behaves like a copy.
bool isIdentityCopy () const
Return true is the instruction is an identity copy.
bool isMetaInstruction () const
Return true if this instruction doesn't produce any output in the form of executable instructions.
bool isTransient () const
Return true if this is a transient instruction that is either very likely to be eliminated during register allocation (such as copy-like instructions), or if this instruction doesn't have an execution-time cost.
unsigned getBundleSize () const
Return the number of instructions inside the MI bundle, excluding the bundle header.
bool readsRegister (Register Reg, const TargetRegisterInfo *TRI=nullptr) const
Return true if the MachineInstr reads the specified register.
bool readsVirtualRegister (Register Reg) const
Return true if the MachineInstr reads the specified virtual register.
std::pair< bool, bool > readsWritesVirtualRegister (Register Reg, SmallVectorImpl< unsigned > *Ops=nullptr) const
Return a pair of bools (reads, writes) indicating if this instruction reads or writes Reg.
bool killsRegister (Register Reg, const TargetRegisterInfo *TRI=nullptr) const
Return true if the MachineInstr kills the specified register.
bool definesRegister (Register Reg, const TargetRegisterInfo *TRI=nullptr) const
Return true if the MachineInstr fully defines the specified register.
bool modifiesRegister (Register Reg, const TargetRegisterInfo *TRI) const
Return true if the MachineInstr modifies (fully define or partially define) the specified register.
bool registerDefIsDead (Register Reg, const TargetRegisterInfo *TRI=nullptr) const
Returns true if the register is dead in this machine instruction.
bool hasRegisterImplicitUseOperand (Register Reg) const
Returns true if the MachineInstr has an implicit-use operand of exactly the given register (not considering sub/super-registers).
int findRegisterUseOperandIdx (Register Reg, bool isKill=false, const TargetRegisterInfo *TRI=nullptr) const
Returns the operand index that is a use of the specific register or -1 if it is not found.
MachineOperand * findRegisterUseOperand (Register Reg, bool isKill=false, const TargetRegisterInfo *TRI=nullptr)
Wrapper for findRegisterUseOperandIdx, it returns a pointer to the MachineOperand rather than an index.
const MachineOperand * findRegisterUseOperand (Register Reg, bool isKill=false, const TargetRegisterInfo *TRI=nullptr) const
int findRegisterDefOperandIdx (Register Reg, bool isDead=false, bool Overlap=false, const TargetRegisterInfo *TRI=nullptr) const
Returns the operand index that is a def of the specified register or -1 if it is not found.
MachineOperand * findRegisterDefOperand (Register Reg, bool isDead=false, bool Overlap=false, const TargetRegisterInfo *TRI=nullptr)
Wrapper for findRegisterDefOperandIdx, it returns a pointer to the MachineOperand rather than an index.
const MachineOperand * findRegisterDefOperand (Register Reg, bool isDead=false, bool Overlap=false, const TargetRegisterInfo *TRI=nullptr) const
int findFirstPredOperandIdx () const
Find the index of the first operand in the operand list that is used to represent the predicate.
int findInlineAsmFlagIdx (unsigned OpIdx, unsigned *GroupNo=nullptr) const
Find the index of the flag word operand that corresponds to operand OpIdx on an inline asm instruction.
const TargetRegisterClass * getRegClassConstraint (unsigned OpIdx, const TargetInstrInfo *TII, const TargetRegisterInfo *TRI) const
Compute the static register class constraint for operand OpIdx.
const TargetRegisterClass * getRegClassConstraintEffectForVReg (Register Reg, const TargetRegisterClass *CurRC, const TargetInstrInfo *TII, const TargetRegisterInfo *TRI, bool ExploreBundle=false) const
Applies the constraints (def/use) implied by this MI on Reg to the given CurRC.
const TargetRegisterClass * getRegClassConstraintEffect (unsigned OpIdx, const TargetRegisterClass *CurRC, const TargetInstrInfo *TII, const TargetRegisterInfo *TRI) const
Applies the constraints (def/use) implied by the OpIdx operand to the given CurRC.
void tieOperands (unsigned DefIdx, unsigned UseIdx)
Add a tie between the register operands at DefIdx and UseIdx.
unsigned findTiedOperandIdx (unsigned OpIdx) const
Given the index of a tied register operand, find the operand it is tied to.
bool isRegTiedToUseOperand (unsigned DefOpIdx, unsigned *UseOpIdx=nullptr) const
Given the index of a register def operand, check if the register def is tied to a source operand, due to either two-address elimination or inline assembly constraints.
bool isRegTiedToDefOperand (unsigned UseOpIdx, unsigned *DefOpIdx=nullptr) const
Return true if the use operand of the specified index is tied to a def operand.
void clearKillInfo ()
Clears kill flags on all operands.
void substituteRegister (Register FromReg, Register ToReg, unsigned SubIdx, const TargetRegisterInfo &RegInfo)
Replace all occurrences of FromReg with ToReg:SubIdx, properly composing subreg indices where necessary.
bool addRegisterKilled (Register IncomingReg, const TargetRegisterInfo *RegInfo, bool AddIfNotFound=false)
We have determined MI kills a register.
void clearRegisterKills (Register Reg, const TargetRegisterInfo *RegInfo)
Clear all kill flags affecting Reg.
bool addRegisterDead (Register Reg, const TargetRegisterInfo *RegInfo, bool AddIfNotFound=false)
We have determined MI defined a register without a use.
void clearRegisterDeads (Register Reg)
Clear all dead flags on operands defining register Reg.
void setRegisterDefReadUndef (Register Reg, bool IsUndef=true)
Mark all subregister defs of register Reg with the undef flag.
void addRegisterDefined (Register Reg, const TargetRegisterInfo *RegInfo=nullptr)
We have determined MI defines a register.
void setPhysRegsDeadExcept (ArrayRef< Register > UsedRegs, const TargetRegisterInfo &TRI)
Mark every physreg used by this instruction as dead except those in the UsedRegs list.
bool isSafeToMove (AAResults *AA, bool &SawStore) const
Return true if it is safe to move this instruction.
bool mayAlias (AAResults *AA, const MachineInstr &Other, bool UseTBAA) const
Returns true if this instruction's memory access aliases the memory access of Other.
bool hasOrderedMemoryRef () const
Return true if this instruction may have an ordered or volatile memory reference, or if the information describing the memory reference is not available.
bool isDereferenceableInvariantLoad (AAResults *AA) const
Return true if this load instruction never traps and points to a memory location whose value doesn't change during the execution of this function.
unsigned isConstantValuePHI () const
If the specified instruction is a PHI that always merges together the same virtual register, return the register, otherwise return 0.
bool hasUnmodeledSideEffects () const
Return true if this instruction has side effects that are not modeled by mayLoad / mayStore, etc.
bool isLoadFoldBarrier () const
Returns true if it is illegal to fold a load across this instruction.
bool allDefsAreDead () const
Return true if all the defs of this instruction are dead.
Optional< unsigned > getSpillSize (const TargetInstrInfo *TII) const
Return a valid size if the instruction is a spill instruction.
Optional< unsigned > getFoldedSpillSize (const TargetInstrInfo *TII) const
Return a valid size if the instruction is a folded spill instruction.
Optional< unsigned > getRestoreSize (const TargetInstrInfo *TII) const
Return a valid size if the instruction is a restore instruction.
Optional< unsigned > getFoldedRestoreSize (const TargetInstrInfo *TII) const
Return a valid size if the instruction is a folded restore instruction.
void copyImplicitOps (MachineFunction &MF, const MachineInstr &MI)
Copy implicit register operands from specified instruction to this instruction.
void addOperand (MachineFunction &MF, const MachineOperand &Op)
Add the specified operand to the instruction.
void addOperand (const MachineOperand &Op)
Add an operand without providing an MF reference.
void setDesc (const MCInstrDesc &tid)
Replace the instruction descriptor (thus opcode) of the current instruction with a new one.
void setDebugLoc (DebugLoc dl)
Replace current source information with new such.
void RemoveOperand (unsigned OpNo)
Erase an operand from an instruction, leaving it with one fewer operand than it started with.
void dropMemRefs (MachineFunction &MF)
Clear this MachineInstr's memory reference descriptor list.
void setMemRefs (MachineFunction &MF, ArrayRef< MachineMemOperand *> MemRefs)
Assign this MachineInstr's memory reference descriptor list.
void addMemOperand (MachineFunction &MF, MachineMemOperand *MO)
Add a MachineMemOperand to the machine instruction.
void cloneMemRefs (MachineFunction &MF, const MachineInstr &MI)
Clone another MachineInstr's memory reference descriptor list and replace ours with it.
void cloneMergedMemRefs (MachineFunction &MF, ArrayRef< const MachineInstr *> MIs)
Clone the merge of multiple MachineInstrs' memory reference descriptors list and replace ours with it.
void setPreInstrSymbol (MachineFunction &MF, MCSymbol *Symbol)
Set a symbol that will be emitted just prior to the instruction itself.
void setPostInstrSymbol (MachineFunction &MF, MCSymbol *Symbol)
Set a symbol that will be emitted just after the instruction itself.
void cloneInstrSymbols (MachineFunction &MF, const MachineInstr &MI)
Clone another MachineInstr's pre- and post- instruction symbols and replace ours with it.
void setHeapAllocMarker (MachineFunction &MF, MDNode *MD)
Set a marker on instructions that denotes where we should create and emit heap alloc site labels.
uint16_t mergeFlagsWith (const MachineInstr &Other) const
Return the MIFlags which represent both MachineInstrs.
void copyIRFlags (const Instruction &I)
Copy all flags to MachineInst MIFlags.
void untieRegOperand (unsigned OpIdx)
Break any tie involving OpIdx.
void addImplicitDefUseOperands (MachineFunction &MF)
Add all implicit def and use operands to this instruction.
void collectDebugValues (SmallVectorImpl< MachineInstr *> &DbgValues)
Scan instructions immediately following MI and collect any matching DBG_VALUEs.
void changeDebugValuesDefReg (Register Reg)
Find all DBG_VALUEs that point to the register def in this instruction and point them to Reg instead.
unsigned getIntrinsicID () const
Returns the Intrinsic::ID for this instruction.
LLT getTypeToPrint (unsigned OpIdx, SmallBitVector &PrintedTypes, const MachineRegisterInfo &MRI) const
Debugging supportDetermine the generic type to be printed (if needed) on uses and defs.
bool hasComplexRegisterTies () const
Return true when an instruction has tied register that can't be determined by the instruction's descriptor.
void print (raw_ostream &OS, bool IsStandalone=true, bool SkipOpers=false, bool SkipDebugLoc=false, bool AddNewLine=true, const TargetInstrInfo *TII=nullptr) const
Print this MI to OS.
void print (raw_ostream &OS, ModuleSlotTracker &MST, bool IsStandalone=true, bool SkipOpers=false, bool SkipDebugLoc=false, bool AddNewLine=true, const TargetInstrInfo *TII=nullptr) const
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MachineInstr, MachineBasicBlock, ilist_sentinel_tracking< true > >
MachineInstr * getPrevNode ()
const MachineInstr * getPrevNode () const
Get the previous node, or nullptr for the list head.
MachineInstr * getNextNode ()
Get the next node, or nullptr for the list tail.
const MachineInstr * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static uint16_t copyFlagsFromInstruction (const Instruction &I)
Friends
struct ilist_traits< MachineInstr >
struct ilist_callback_traits< MachineBasicBlock >
class MachineFunction
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< MachineInstr, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MachineInstr, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MachineInstr, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MachineInstr, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< MachineInstr, MachineBasicBlock, ilist_sentinel_tracking< true > >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >
ilist_node_impl ()=default
Detailed Description
Representation of each machine instruction.
This class isn't a POD type, but it must have a trivial destructor. When a MachineFunction is deleted, all the contained MachineInstrs are deallocated without having their destructor called.
Definition at line 63 of file MachineInstr.h.
Member Typedef Documentation
const_mop_iterator
using llvm::MachineInstr::const_mop_iterator = const MachineOperand *
Definition at line 484 of file MachineInstr.h.
mmo_iterator
using llvm::MachineInstr::mmo_iterator = ArrayRef<MachineMemOperand *>::iterator
Definition at line 67 of file MachineInstr.h.
mop_iterator
using llvm::MachineInstr::mop_iterator = MachineOperand *
iterator/begin/end - Iterate over all operands of a machine instruction.
Definition at line 483 of file MachineInstr.h.
Member Enumeration Documentation
CommentFlag
enum llvm::MachineInstr::CommentFlag
Flags to specify different kinds of comments to output in assembly code.
These flags carry semantic information not otherwise easily derivable from the IR text.
Enumerator
ReloadReuse
NoSchedComment
TAsmComments
Definition at line 73 of file MachineInstr.h.
MICheckType
enum llvm::MachineInstr::MICheckType
Enumerator
CheckDefs
CheckKillDead
IgnoreDefs
IgnoreVRegDefs
Definition at line 991 of file MachineInstr.h.
MIFlag
enum llvm::MachineInstr::MIFlag
Enumerator
NoFlags
FrameSetup
FrameDestroy
BundledPred
BundledSucc
FmNoNans
FmNoInfs
FmNsz
FmArcp
FmContract
FmAfn
FmReassoc
NoUWrap
NoSWrap
IsExact
NoFPExcept
Definition at line 79 of file MachineInstr.h.
QueryType
enum llvm::MachineInstr::QueryType
API for querying MachineInstr properties.
They are the same as MCInstrDesc queries but they are bundle aware.
Enumerator
IgnoreBundle
AnyInBundle
AllInBundle
Definition at line 624 of file MachineInstr.h.
Constructor & Destructor Documentation
MachineInstr()
llvm::MachineInstr::MachineInstr (const MachineInstr &) delete
~MachineInstr()
llvm::MachineInstr::~MachineInstr () delete
Member Function Documentation
addImplicitDefUseOperands()
void MachineInstr::addImplicitDefUseOperands (MachineFunction & MF)
Add all implicit def and use operands to this instruction.
Definition at line 102 of file MachineInstr.cpp.
References addOperand(), llvm::MachineRegisterInfo::addRegOperandToUseList(), llvm::MachineFunction::allocateOperandArray(), assert(), llvm::MachineOperand::CreateReg(), getDebugLoc(), getDesc(), llvm::MCInstrDesc::getImplicitDefs(), llvm::MCInstrDesc::getImplicitUses(), llvm::MCInstrDesc::getNumImplicitDefs(), llvm::MCInstrDesc::getNumImplicitUses(), llvm::MCInstrDesc::getNumOperands(), getNumOperands(), getParent(), llvm::DebugLoc::hasTrivialDestructor(), llvm::MCInstrDesc::ImplicitDefs, llvm::MCInstrDesc::ImplicitUses, MI, MRI, operands(), llvm::MachineRegisterInfo::removeRegOperandFromUseList(), and setFlags().
Referenced by llvm::SIInstrInfo::FoldImmediate(), hoistAndMergeSGPRInits(), llvm::SIInstrInfo::moveToVALU(), shouldUseAndMask(), and untieRegOperand().
addMemOperand()
void MachineInstr::addMemOperand (MachineFunction & MF, MachineMemOperand * MO)
Add a MachineMemOperand to the machine instruction.
This function should be used only occasionally. The setMemRefs function is the primary method for setting up a MachineInstr's MemRefs list.
Definition at line 374 of file MachineInstr.cpp.
References llvm::SmallVectorImpl< T >::append(), memoperands_begin(), memoperands_end(), llvm::SmallVectorTemplateBase< T >::push_back(), and setMemRefs().
Referenced by llvm::MachineInstrBuilder::addMemOperand(), computeBytesPoppedByCalleeForSRet(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::TargetInstrInfo::foldMemoryOperand(), and setDebugLoc().
addOperand() [1/2]
void MachineInstr::addOperand (MachineFunction & MF, const MachineOperand & Op)
Add the specified operand to the instruction.
addOperand - Add the specified operand to the instruction.
If it is an implicit operand, it is added to the end of the operand list. If it is an explicit operand it is added at the end of the explicit operand list (before the first implicit operand).
MF must be the machine function that was used to allocate this instruction.
MachineInstrBuilder provides a more convenient interface for creating instructions and adding operands.
If it is an implicit operand, it is added to the end of the operand list. If it is an explicit operand it is added at the end of the explicit operand list (before the first implicit operand).
Definition at line 199 of file MachineInstr.cpp.
References llvm::MachineRegisterInfo::addRegOperandToUseList(), llvm::MachineFunction::allocateOperandArray(), assert(), llvm::MachineFunction::deallocateOperandArray(), llvm::MCOI::EARLY_CLOBBER, llvm::MCInstrDesc::getNumOperands(), getNumOperands(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), isInlineAsm(), isReg(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isUse(), llvm::MCInstrDesc::isVariadic(), llvm::MachineOperand::MO_MCSymbol, llvm::MachineOperand::MO_Metadata, moveOperands(), llvm::MachineOperand::setIsEarlyClobber(), llvm::MCOI::TIED_TO, and tieOperands().
Referenced by llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addBlockAddress(), llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineInstrBuilder::addCImm(), llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addFPImm(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), addImplicitDefUseOperands(), llvm::MachineInstrBuilder::addIntrinsicID(), llvm::MachineInstrBuilder::addJumpTableIndex(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMetadata(), addOperand(), llvm::MachineInstrBuilder::addPredicate(), llvm::MachineInstrBuilder::addReg(), addRegisterDead(), addRegisterDefined(), addRegisterKilled(), llvm::MachineInstrBuilder::addRegMask(), llvm::MachineInstrBuilder::addShuffleMask(), llvm::MachineInstrBuilder::addSym(), llvm::MachineInstrBuilder::addTargetIndex(), appendEndToFunction(), llvm::SIInstrInfo::buildExtractSubRegOrImm(), convertImplicitDefToConstZero(), copyExtraImplicitOps(), copyImplicitOps(), createPHIsForSelects(), llvm::createSIWholeQuadModePass(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::HexagonFrameLowering::emitPrologue(), enableAllocFrameElim(), fixupGlobalSaddr(), llvm::HexagonFrameLowering::getAlignaInstr(), getLeaOP(), getLogicalBitOpcode(), getVectorSHLImm(), llvm::LiveVariables::HandleVirtRegDef(), imposeStackOrdering(), INITIALIZE_PASS(), isConstant(), isCopy(), isRegTiedToDefOperand(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::SIInstrInfo::moveToVALU(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::rewriteT2FrameIndex(), and swapMIOperands().
addOperand() [2/2]
void MachineInstr::addOperand (const MachineOperand & Op)
Add an operand without providing an MF reference.
This only works for instructions that are inserted in a basic block.
MachineInstrBuilder and the two-argument addOperand(MF, MO) should be preferred.
Definition at line 176 of file MachineInstr.cpp.
References addOperand(), assert(), llvm::MachineBasicBlock::getParent(), and getParent().
addRegisterDead()
bool MachineInstr::addRegisterDead (Register Reg, const TargetRegisterInfo * RegInfo, bool AddIfNotFound = false)
We have determined MI defined a register without a use.
Look for the operand that defines it and mark it as IsDead. If AddIfNotFound is true, add a implicit operand if it's not found. Returns true if the operand exists / is added.
Definition at line 1864 of file MachineInstr.cpp.
References addOperand(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::MachineOperand::CreateReg(), llvm::numbers::e, llvm::SmallVectorBase::empty(), findInlineAsmFlagIdx(), getNumOperands(), getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), isInlineAsm(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MCRegisterInfo::isSubRegister(), llvm::MCRegisterInfo::isSuperRegister(), llvm::MCRegAliasIterator::isValid(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveOperand(), and llvm::MachineOperand::setIsDead().
Referenced by llvm::LiveVariables::addVirtualRegisterDead(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::LiveVariables::HandleVirtRegDef(), isEFLAGSLive(), isFullCopyOf(), isRegTiedToDefOperand(), and llvm::LiveIntervals::shrinkToUses().
addRegisterDefined()
void MachineInstr::addRegisterDefined (Register Reg, const TargetRegisterInfo * RegInfo = nullptr)
We have determined MI defines a register.
Make sure there is an operand defining Reg.
Definition at line 1933 of file MachineInstr.cpp.
References addOperand(), llvm::MachineOperand::CreateReg(), findRegisterDefOperand(), llvm::Register::isPhysicalRegister(), and operands().
Referenced by canInstrSubstituteCmpInstr(), llvm::SparcInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), isCoalescable(), isRegTiedToDefOperand(), llvm::LanaiInstrInfo::optimizeCompareInstr(), and setPhysRegsDeadExcept().
addRegisterKilled()
bool MachineInstr::addRegisterKilled (Register IncomingReg, const TargetRegisterInfo * RegInfo, bool AddIfNotFound = false)
We have determined MI kills a register.
Look for the operand that uses it and mark it as IsKill. If AddIfNotFound is true, add a implicit operand if it's not found. Returns true if the operand exists / is added.
Definition at line 1785 of file MachineInstr.cpp.
References addOperand(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::MachineOperand::CreateReg(), llvm::numbers::e, llvm::SmallVectorBase::empty(), findInlineAsmFlagIdx(), getNumOperands(), getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDebug(), isInlineAsm(), llvm::MachineOperand::isKill(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), isRegTiedToDefOperand(), llvm::MCRegisterInfo::isSubRegister(), llvm::MCRegisterInfo::isSuperRegister(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::MCRegAliasIterator::isValid(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveOperand(), and llvm::MachineOperand::setIsKill().
Referenced by addExclusiveRegPair(), llvm::LiveIntervals::addKillFlags(), llvm::LiveVariables::addVirtualRegisterKilled(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::SparcInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::LiveVariables::HandleVirtRegDef(), INITIALIZE_PASS(), isCoalescable(), isRegTiedToDefOperand(), and replaceDominatedUses().
allDefsAreDead()
bool MachineInstr::allDefsAreDead () const
Return true if all the defs of this instruction are dead.
allDefsAreDead - Return true if all the defs of this instruction are dead.
Definition at line 1386 of file MachineInstr.cpp.
References operands().
Referenced by llvm::LiveRangeEdit::eraseVirtReg(), INITIALIZE_PASS(), isFullCopyOf(), isRegTiedToDefOperand(), and llvm::LiveIntervals::shrinkToUses().
bundleWithPred()
void MachineInstr::bundleWithPred ()
Bundle this instruction with its predecessor.
This can be an unbundled instruction, or it can be the first instruction in a bundle.
Definition at line 732 of file MachineInstr.cpp.
References assert(), BundledPred, BundledSucc, llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >::getIterator(), isBundledWithPred(), and setFlag().
Referenced by llvm::MachineFunction::CloneMachineInstrBundle(), llvm::createR600ExpandSpecialInstrsPass(), llvm::SplitEditor::dump(), getMopState(), llvm::MIBundleBuilder::insert(), isBundledWithSucc(), and llvm::MIBundleBuilder::MIBundleBuilder().
bundleWithSucc()
void MachineInstr::bundleWithSucc ()
Bundle this instruction with its successor.
This can be an unbundled instruction, or it can be the last instruction in a bundle.
Definition at line 741 of file MachineInstr.cpp.
References assert(), BundledPred, BundledSucc, llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >::getIterator(), isBundledWithSucc(), and setFlag().
Referenced by llvm::MIBundleBuilder::insert(), and isBundledWithSucc().
canFoldAsLoad()
bool llvm::MachineInstr::canFoldAsLoad (QueryType Type = IgnoreBundle) const inline
Return true for instructions that can be folded as memory operands in other instructions.
The most common use for this is instructions that are simple loads from memory that don't modify the loaded value in any way, but it can also be used for instructions that can be expressed as constant-pool loads, such as V_SETALLONES on x86, to allow them to be folded when it is beneficial. This should only be set on instructions that return a value in their only virtual register definition.
Definition at line 802 of file MachineInstr.h.
References llvm::MCID::FoldableAsLoad, and hasProperty().
Referenced by llvm::LiveRangeEdit::eraseVirtReg(), llvm::TargetInstrInfo::foldMemoryOperand(), getNewSource(), isCopyFeedingInvariantStore(), and isFullCopyOf().
changeDebugValuesDefReg()
void MachineInstr::changeDebugValuesDefReg (Register Reg)
Find all DBG_VALUEs that point to the register def in this instruction and point them to Reg instead.
Definition at line 2122 of file MachineInstr.cpp.
References getOperand(), llvm::MachineOperand::getReg(), isReg(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::MachineRegisterInfo::use_operands().
Referenced by untieRegOperand().
clearAsmPrinterFlag()
void llvm::MachineInstr::clearAsmPrinterFlag (CommentFlag Flag) inline
Clear specific AsmPrinter flags.
Definition at line 302 of file MachineInstr.h.
clearAsmPrinterFlags()
void llvm::MachineInstr::clearAsmPrinterFlags () inline
Clear the AsmPrinter bitvector.
Definition at line 289 of file MachineInstr.h.
clearFlag()
void llvm::MachineInstr::clearFlag (MIFlag Flag) inline
clearFlag - Clear a MI flag.
Definition at line 328 of file MachineInstr.h.
Referenced by moveInstrOut(), llvm::MachineBasicBlock::remove_instr(), unbundleFromPred(), and unbundleFromSucc().
clearKillInfo()
void MachineInstr::clearKillInfo ()
Clears kill flags on all operands.
clearKillInfo - Clears kill flags on all operands.
Definition at line 1132 of file MachineInstr.cpp.
References operands().
Referenced by isRegTiedToDefOperand(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), and llvm::rdf::Liveness::resetKills().
clearRegisterDeads()
void MachineInstr::clearRegisterDeads (Register Reg)
Clear all dead flags on operands defining register Reg.
Definition at line 1917 of file MachineInstr.cpp.
References operands(), and Reg.
Referenced by getCompareSourceReg(), isAddWithImmediate(), isCallerPreservedOrConstPhysReg(), isRegTiedToDefOperand(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), and llvm::PPCInstrInfo::optimizeCompareInstr().
clearRegisterKills()
void MachineInstr::clearRegisterKills (Register Reg, const TargetRegisterInfo * RegInfo)
Clear all kill flags affecting Reg.
If RegInfo is provided, this includes all aliasing registers.
Definition at line 1851 of file MachineInstr.cpp.
References llvm::Register::isPhysicalRegister(), operands(), and llvm::TargetRegisterInfo::regsOverlap().
Referenced by llvm::LiveIntervals::addKillFlags(), isNopCopy(), isRegTiedToDefOperand(), and updateDefinedRegisters().
cloneInstrSymbols()
void MachineInstr::cloneInstrSymbols (MachineFunction & MF, const MachineInstr & MI)
Clone another MachineInstr's pre- and post- instruction symbols and replace ours with it.
Definition at line 506 of file MachineInstr.cpp.
References assert(), getHeapAllocMarker(), getMF(), getPostInstrSymbol(), getPreInstrSymbol(), setHeapAllocMarker(), setPostInstrSymbol(), and setPreInstrSymbol().
Referenced by computeBytesPoppedByCalleeForSRet(), and setDebugLoc().
cloneMemRefs()
void MachineInstr::cloneMemRefs (MachineFunction & MF, const MachineInstr & MI)
Clone another MachineInstr's memory reference descriptor list and replace ours with it.
Note that *this may be the incoming MI!
Prefer this API whenever possible as it can avoid allocations in common cases.
Definition at line 382 of file MachineInstr.cpp.
References assert(), getHeapAllocMarker(), getMF(), getPostInstrSymbol(), getPreInstrSymbol(), memoperands(), and setMemRefs().
Referenced by llvm::MachineInstrBuilder::cloneMemRefs(), cloneMergedMemRefs(), fixupGlobalSaddr(), and setDebugLoc().
cloneMergedMemRefs()
void MachineInstr::cloneMergedMemRefs (MachineFunction & MF, ArrayRef< const MachineInstr *> MIs)
Clone the merge of multiple MachineInstrs' memory reference descriptors list and replace ours with it.
Note that *this may be one of the incoming MIs!
Prefer this API whenever possible as it can avoid allocations in common cases.
Definition at line 416 of file MachineInstr.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), cloneMemRefs(), dropMemRefs(), llvm::ArrayRef< T >::empty(), getMF(), hasIdenticalMMOs(), llvm::make_pointee_range(), memoperands(), memoperands_begin(), memoperands_empty(), memoperands_end(), setMemRefs(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::MachineInstrBuilder::cloneMergedMemRefs(), and setDebugLoc().
collectDebugValues()
void MachineInstr::collectDebugValues (SmallVectorImpl< MachineInstr *> & DbgValues)
Scan instructions immediately following MI and collect any matching DBG_VALUEs.
Definition at line 2105 of file MachineInstr.cpp.
References llvm::MachineBasicBlock::end(), getOperand(), getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), MI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by emitSelectPseudo(), untieRegOperand(), and llvm::WebAssemblyDebugValueManager::WebAssemblyDebugValueManager().
copyFlagsFromInstruction()
uint16_t MachineInstr::copyFlagsFromInstruction (const Instruction & I) static
Definition at line 526 of file MachineInstr.cpp.
References llvm::FastMathFlags::allowContract(), llvm::FastMathFlags::allowReassoc(), llvm::FastMathFlags::allowReciprocal(), llvm::FastMathFlags::approxFunc(), llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), and llvm::X86II::OB.
Referenced by copyIRFlags(), llvm::IRTranslator::getAnalysisUsage(), getOffsetFromIndices(), and setDebugLoc().
copyImplicitOps()
void MachineInstr::copyImplicitOps (MachineFunction & MF, const MachineInstr & MI)
Copy implicit register operands from specified instruction to this instruction.
copyImplicitOps - Copy implicit register operands from specified instruction to this instruction.
Definition at line 1398 of file MachineInstr.cpp.
References addOperand(), llvm::numbers::e, getDesc(), llvm::MCInstrDesc::getNumOperands(), getNumOperands(), getOperand(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isRegMask().
Referenced by llvm::MachineInstrBuilder::copyImplicitOps(), enableAllocFrameElim(), fixupGlobalSaddr(), llvm::HexagonFrameLowering::getFrameIndexReference(), INITIALIZE_PASS(), InsertLDR_STR(), and isRegTiedToDefOperand().
copyIRFlags()
void MachineInstr::copyIRFlags (const Instruction & I)
Copy all flags to MachineInst MIFlags.
Definition at line 564 of file MachineInstr.cpp.
References AllInBundle, AnyInBundle, assert(), copyFlagsFromInstruction(), llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >::getIterator(), isBundledWithPred(), and llvm::BitmaskEnumDetail::Mask().
Referenced by getOffsetFromIndices(), and setDebugLoc().
definesRegister()
bool llvm::MachineInstr::definesRegister (Register Reg, const TargetRegisterInfo * TRI = nullptr) const inline
Return true if the MachineInstr fully defines the specified register.
If TargetRegisterInfo is passed, then it also checks if there is a def of a super-register. NOTE: It's ignoring subreg indices on virtual registers.
Definition at line 1218 of file MachineInstr.h.
References findRegisterDefOperandIdx(), and TRI.
Referenced by addLiveInRegs(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), checkAndUpdateCPSRKill(), checkAndUpdateEFLAGSKill(), checkCCKill(), convertToNonFlagSettingOpc(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), getImplicitSPRUseForDPRUse(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), imposeStackOrdering(), isCompareZero(), isNopCopy(), isSafeToMove(), llvm::ARMBaseInstrInfo::isSchedulingBoundary(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), and llvm::rewriteT2FrameIndex().
defs() [1/2]
iterator_range<mop_iterator> llvm::MachineInstr::defs () inline
Returns a range over all explicit operands that are register definitions.
Implicit definition are not included!
Definition at line 514 of file MachineInstr.h.
References getNumExplicitDefs(), llvm::make_range(), and operands_begin().
Referenced by addRegsToSet(), llvm::biasPhysReg(), llvm::createSIWholeQuadModePass(), llvm::SplitEditor::dump(), findSingleRegDef(), INITIALIZE_PASS(), instModifiesReg(), isCrossCopy(), isValidClauseInst(), llvm::WebAssemblyMCInstLower::lower(), llvm::PeelSingleBlockLoop(), llvm::GCNUpwardRPTracker::recede(), and false::Chain::str().
defs() [2/2]
iterator_range<const_mop_iterator> llvm::MachineInstr::defs () const inline
Returns a range over all explicit operands that are register definitions.
Implicit definition are not included!
Definition at line 519 of file MachineInstr.h.
References getNumExplicitDefs(), llvm::make_range(), and operands_begin().
dropMemRefs()
void MachineInstr::dropMemRefs (MachineFunction & MF)
Clear this MachineInstr's memory reference descriptor list.
This resets the memrefs to their most conservative state. This should be used only as a last resort since it greatly pessimizes our knowledge of the memory access performed by the instruction.
Definition at line 355 of file MachineInstr.cpp.
References getHeapAllocMarker(), getPostInstrSymbol(), getPreInstrSymbol(), and memoperands_empty().
Referenced by cloneMergedMemRefs(), INITIALIZE_PASS(), setDebugLoc(), and setMemRefs().
dump()
LLVM_DUMP_METHOD void MachineInstr::dump () const
Definition at line 1448 of file MachineInstr.cpp.
References llvm::dbgs(), and print().
Referenced by llvm::HexagonPacketizerList::canPromoteToDotCur(), llvm::HexagonPacketizerList::cleanUpDotCur(), collectRegDefs(), computeBranchTargetAndInversion(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::AArch64TargetLowering::EmitInstrWithCustomInserter(), findPotentialBlockers(), findVCMPToFoldIntoVPST(), fixupRegionExits(), getBufferFormatWithCompCount(), GetDSubRegs(), getINCDECFromLEA(), getNewValueJumpOpcode(), getReassignedChan(), getRegClassForUnfoldedLoad(), getUnderlyingObjects(), INITIALIZE_PASS(), llvm::SMSchedule::insert(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), isDataInvariant(), isDataInvariantLoad(), isEFLAGSLive(), isIntersect(), llvm::HexagonInstrInfo::isLateInstrFeedsEarlyInstr(), isNopCopy(), isPHIRegionIndex(), isRegTiedToDefOperand(), makeImplicit(), moveAndTeeForMultiUse(), moveForSingleUse(), llvm::AggressiveAntiDepBreaker::Observe(), packCmovGroup(), rematerializeCheapDef(), removeRedundantBlockingStores(), llvm::HexagonInstrInfo::reversePredSense(), swapMIOperands(), and updateOperandRegConstraints().
emitError()
void MachineInstr::emitError (StringRef Msg) const
Emit an error referring to the source location of this instruction.
This should only be used for inline assembly that is somehow impossible to compile. Other errors should have been handled much earlier.
If this method returns, the caller should try to recover from the error.
Definition at line 1992 of file MachineInstr.cpp.
References llvm::LLVMContext::emitError(), llvm::Module::getContext(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::getModule(), getNumOperands(), llvm::MDNode::getNumOperands(), getOperand(), llvm::MDNode::getOperand(), getParent(), and llvm::report_fatal_error().
Referenced by llvm::RegAllocBase::allocatePhysRegs(), getDebugLoc(), isCoalescable(), and llvm::LowerARMMachineInstrToMCInst().
eraseFromBundle()
void MachineInstr::eraseFromBundle ()
Unlink 'this' form its basic block and delete it.
If the instruction is part of a bundle, the other instructions in the bundle remain bundled.
Definition at line 694 of file MachineInstr.cpp.
References assert(), llvm::MachineBasicBlock::erase_instr(), and getParent().
Referenced by VerifyLowRegs().
eraseFromParent()
void MachineInstr::eraseFromParent ()
Unlink 'this' from the containing basic block and delete it.
If this instruction is the header of a bundle, the whole bundle is erased. This function can not be used for instructions inside a bundle, use eraseFromBundle() to erase individual bundled instructions.
Definition at line 669 of file MachineInstr.cpp.
References assert(), llvm::MachineBasicBlock::erase(), and getParent().
Referenced by addExclusiveRegPair(), llvm::analyzeArguments(), llvm::MipsInstrInfo::analyzeBranch(), llvm::CombinerHelper::applyCombineConcatVectors(), llvm::CombinerHelper::applyCombineCopy(), llvm::CombinerHelper::applyCombineIndexedLoadStore(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::CombinerHelper::applyElideBrByInvertingCond(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AArch64InstrInfo::buildOutlinedFrame(), canInstrSubstituteCmpInstr(), llvm::TailDuplicator::canTailDuplicate(), canTurnIntoCOPY(), changeFCMPPredToAArch64CC(), llvm::createMemLibcall(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::createR600ExpandSpecialInstrsPass(), llvm::createSIWholeQuadModePass(), llvm::createXCoreFrameToArgsOffsetEliminationPass(), definesFullReg(), dumpMachineInstrRangeWithSlotIndex(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), emitBuildPairF64Pseudo(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitIndirectDst(), emitIndirectSrc(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64TargetLowering::EmitLoweredCatchPad(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostSt(), emitReadCycleWidePseudo(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSplitF64Pseudo(), emitXBegin(), llvm::TargetLoweringBase::emitXRayCustomEvent(), llvm::TargetLoweringBase::emitXRayTypedEvent(), llvm::rdf::DeadCodeElimination::erase(), eraseDeadBBsAndChildren(), eraseFromParentAndMarkDBGValuesForRemoval(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::SIInstrInfo::expandMovDPP64(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::R600InstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorBuildVector(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorImplicitDef(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::LegalizerHelper::fewerElementsVectorSelect(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), findIntrinsicID(), findStartOfTree(), findUncondBrI(), llvm::fixStackStores(), fixupGlobalSaddr(), llvm::foldFrameOffset(), llvm::SystemZInstrInfo::FoldImmediate(), llvm::PPCInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), foldImmediates(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldVGPRCopyIntoRegSequence(), for(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), getAdjustedCmp(), getBufferStoreFormatOpcode(), getCmpForPseudo(), getCompareSourceReg(), getDSShaderTypeValue(), GetDSubRegs(), GetInitialOffset(), getInsertVecEltOpInfo(), getLaneCopyOpcode(), getLogicalBitOpcode(), getMappedOp(), getMemsetValue(), getNewSource(), getNewValueJumpOpcode(), getOModValue(), getRegClassForUnfoldedLoad(), getRegsUsedByPHIs(), getRetpolineSymbol(), getStartOrEndSlot(), getSubOpcode(), getUnconditionalBrDisp(), getV_CMPOpcode(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), getVectorSHLImm(), llvm::MipsTargetLowering::HandleByVal(), HandleVRSaveUpdate(), hasOneNonDBGUseInst(), hasUseAfterLoop(), INITIALIZE_PASS(), llvm::X86FrameLowering::inlineStackProbe(), insertCopy(), isBackwardPropagatableCopy(), isCallerPreservedOrConstPhysReg(), isCompareZero(), isConstant(), isCopyFeedingInvariantStore(), isDefInSubRange(), isFpMulInstruction(), isFullCopyOf(), isFullUndefDef(), isIdentityValue(), isLiveOut(), isLoadStoreThatCanHandleDisplacement(), isNopCopy(), isPHIRegionIndex(), isRegUsedByPhiNodes(), isSimpleIndexCalc(), isVirtualRegisterOperand(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV16(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFDIVFastIntrin(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::X86LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIsAddrSpace(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizePreloadedArgIntrin(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::LegalizerHelper::libcall(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerBitCount(), llvm::LegalizerHelper::lowerBitreverse(), llvm::LegalizerHelper::lowerBswap(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerFCopySign(), llvm::LegalizerHelper::lowerFMad(), llvm::LegalizerHelper::lowerFMinNumMaxNum(), LowerFPToInt(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::LegalizerHelper::lowerInsert(), llvm::LegalizerHelper::lowerIntrinsicRound(), llvm::LegalizerHelper::lowerMinMax(), llvm::LegalizerHelper::lowerReadRegister(), llvm::LegalizerHelper::lowerSADDO_SSUBO(), llvm::AMDGPURegisterBankInfo::lowerScalarMinMax(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::LegalizerHelper::lowerSITOFP(), llvm::LegalizerHelper::lowerUITOFP(), llvm::LegalizerHelper::lowerUnmergeValues(), makeImplicit(), matchSwap(), Mips16WhichOp8uOr16simm(), llvm::LegalizerHelper::moreElementsVector(), llvm::SIInstrInfo::moveToVALU(), MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarMul(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::LegalizerHelper::narrowScalarShift(), llvm::LegalizerHelper::narrowScalarShiftByConstant(), operator<<(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::LegalizerHelper::reduceLoadStoreWidth(), rematerializeCheapDef(), RemoveDeadAddBetweenLEAAndJT(), llvm::FastISel::removeDeadCode(), RemoveVRSaveCode(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::rewriteAArch64FrameIndex(), salvageDebugInfoFromEmptyBlock(), SelectMSA3OpIntrinsic(), llvm::FastISel::selectPatchpoint(), llvm::AMDGPUInstructionSelector::setupMF(), shouldUseAndMask(), splitMBB(), llvm::SystemZInstrInfo::SystemZInstrInfo(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::CombinerHelper::tryCombineMemCpyFamily(), tryOptimizeLEAtoMOV(), and llvm::LegalizerHelper::widenScalar().
eraseFromParentAndMarkDBGValuesForRemoval()
void MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval ()
Unlink 'this' from the containing basic block and delete it.
For all definitions mark their uses in DBG_VALUE nodes as undefined. Otherwise like eraseFromParent().
Definition at line 674 of file MachineInstr.cpp.
References assert(), eraseFromParent(), llvm::MachineBasicBlock::getParent(), getParent(), llvm::MachineFunction::getRegInfo(), llvm::Register::isVirtual(), llvm::MachineRegisterInfo::markUsesInDebugValueAsUndef(), operands(), and Reg.
Referenced by llvm::Combiner::combineMachineInstrs(), INITIALIZE_PASS(), llvm::Legalizer::legalizeMachineFunction(), and llvm::InstructionSelect::runOnMachineFunction().
explicit_operands() [1/2]
iterator_range<mop_iterator> llvm::MachineInstr::explicit_operands () inline
Definition at line 498 of file MachineInstr.h.
References getNumExplicitOperands(), llvm::make_range(), and operands_begin().
Referenced by addRegsToSet(), getVariantKind(), implicit_operands(), and usesExtendedRegister().
explicit_operands() [2/2]
iterator_range<const_mop_iterator> llvm::MachineInstr::explicit_operands () const inline
Definition at line 502 of file MachineInstr.h.
References getNumExplicitOperands(), llvm::make_range(), and operands_begin().
explicit_uses() [1/2]
iterator_range<mop_iterator> llvm::MachineInstr::explicit_uses () inline
Definition at line 532 of file MachineInstr.h.
References getNumExplicitDefs(), getNumExplicitOperands(), llvm::make_range(), and operands_begin().
Referenced by addRegsToSet(), findStartOfTree(), llvm::SIInstrInfo::hasVGPRUses(), llvm::WebAssemblyMCInstLower::lower(), moveAndTeeForMultiUse(), and operator<<().
explicit_uses() [2/2]
iterator_range<const_mop_iterator> llvm::MachineInstr::explicit_uses () const inline
Definition at line 536 of file MachineInstr.h.
References getNumExplicitDefs(), getNumExplicitOperands(), llvm::make_range(), and operands_begin().
findFirstPredOperandIdx()
int MachineInstr::findFirstPredOperandIdx () const
Find the index of the first operand in the operand list that is used to represent the predicate.
findFirstPredOperandIdx() - Find the index of the first operand in the operand list that is used to represent the predicate.
It returns -1 if none is found.
Definition at line 1020 of file MachineInstr.cpp.
References llvm::numbers::e, getDesc(), getNumOperands(), llvm::MCInstrDesc::isPredicable(), llvm::MCOperandInfo::isPredicate(), and llvm::MCInstrDesc::OpInfo.
Referenced by llvm::ARMBaseInstrInfo::commuteInstructionImpl(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), findRegisterDefOperand(), llvm::ARMFrameLowering::getCalleeSaves(), llvm::getInstrPredicate(), llvm::ARMBaseInstrInfo::getPredicate(), llvm::ARMBaseInstrInfo::isPredicated(), llvm::R600InstrInfo::isPredicated(), llvm::ARMBaseInstrInfo::PredicateInstruction(), and llvm::R600InstrInfo::PredicateInstruction().
findInlineAsmFlagIdx()
int MachineInstr::findInlineAsmFlagIdx (unsigned OpIdx, unsigned * GroupNo = nullptr) const
Find the index of the flag word operand that corresponds to operand OpIdx on an inline asm instruction.
Returns -1 if getOperand(OpIdx) does not belong to an inline asm operand group.
If GroupNo is not NULL, it will receive the number of the operand group containing OpIdx.
The flag operand is an immediate that can be decoded with methods like InlineAsm::hasRegClassConstraint().
Definition at line 783 of file MachineInstr.cpp.
References assert(), llvm::numbers::e, llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), getNumOperands(), getOperand(), llvm::MachineOperand::isImm(), isInlineAsm(), and llvm::InlineAsm::MIOp_FirstOperand.
Referenced by addRegisterDead(), addRegisterKilled(), findRegisterDefOperand(), and getRegClassConstraint().
findRegisterDefOperand() [1/2]
MachineOperand* llvm::MachineInstr::findRegisterDefOperand (Register Reg, bool isDead = false, bool Overlap = false, const TargetRegisterInfo * TRI = nullptr) inline
Wrapper for findRegisterDefOperandIdx, it returns a pointer to the MachineOperand rather than an index.
Definition at line 1276 of file MachineInstr.h.
References findRegisterDefOperandIdx(), getOperand(), and TRI.
Referenced by addRegisterDefined(), findRegisterDefOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::LiveVariables::HandleVirtRegDef(), llvm::X86InstrInfo::hasReassociableOperands(), isDataInvariant(), isDataInvariantLoad(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::setSpecialOperandAttr(), transferDeadCC(), and UpdateCPSRUse().
findRegisterDefOperand() [2/2]
const MachineOperand* llvm::MachineInstr::findRegisterDefOperand (Register Reg, bool isDead = false, bool Overlap = false, const TargetRegisterInfo * TRI = nullptr) const inline
Definition at line 1284 of file MachineInstr.h.
References findFirstPredOperandIdx(), findInlineAsmFlagIdx(), findRegisterDefOperand(), findTiedOperandIdx(), getRegClassConstraint(), getRegClassConstraintEffect(), getRegClassConstraintEffectForVReg(), tieOperands(), TII, and TRI.
findRegisterDefOperandIdx()
int MachineInstr::findRegisterDefOperandIdx (Register Reg, bool isDead = false, bool Overlap = false, const TargetRegisterInfo * TRI = nullptr) const
Returns the operand index that is a def of the specified register or -1 if it is not found.
findRegisterDefOperandIdx() - Returns the operand index that is a def of the specified register or -1 if it is not found.
If isDead is true, defs that are not dead are skipped. If Overlap is true, then it also looks for defs that merely overlap the specified register. If TargetRegisterInfo is non-null, then it also checks if there is a def of a super-register. This may also return a register mask operand when Overlap is true.
If isDead is true, defs that are not dead are skipped. If TargetRegisterInfo is non-null, then it also checks if there is a def of a super-register.
Definition at line 992 of file MachineInstr.cpp.
References llvm::MachineOperand::clobbersPhysReg(), llvm::numbers::e, getNumOperands(), getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MCRegisterInfo::isSubRegister(), Reg, and llvm::TargetRegisterInfo::regsOverlap().
Referenced by addSegmentsWithValNo(), canFoldIntoCSel(), CriticalPathStep(), llvm::R600InstrInfo::definesAddressRegister(), definesRegister(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), findRegisterDefOperand(), findRegisterUseOperand(), getMaddPatterns(), llvm::HexagonInstrInfo::getOperandLatency(), modifiesRegister(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), and registerDefIsDead().
findRegisterUseOperand() [1/2]
MachineOperand* llvm::MachineInstr::findRegisterUseOperand (Register Reg, bool isKill = false, const TargetRegisterInfo * TRI = nullptr) inline
Wrapper for findRegisterUseOperandIdx, it returns a pointer to the MachineOperand rather than an index.
Definition at line 1250 of file MachineInstr.h.
References findRegisterUseOperandIdx(), getOperand(), isKill(), and TRI.
Referenced by findRegisterUseOperand(), getRegClassForUnfoldedLoad(), isCopy(), isEFLAGSLive(), llvm::AggressiveAntiDepBreaker::Observe(), regOverlapsSet(), and UpdateCPSRUse().
findRegisterUseOperand() [2/2]
const MachineOperand* llvm::MachineInstr::findRegisterUseOperand (Register Reg, bool isKill = false, const TargetRegisterInfo * TRI = nullptr) const inline
Definition at line 1256 of file MachineInstr.h.
References findRegisterDefOperandIdx(), findRegisterUseOperand(), isKill(), and TRI.
findRegisterUseOperandIdx()
int MachineInstr::findRegisterUseOperandIdx (Register Reg, bool isKill = false, const TargetRegisterInfo * TRI = nullptr) const
Returns the operand index that is a use of the specific register or -1 if it is not found.
findRegisterUseOperandIdx() - Returns the MachineOperand that is a use of the specific register or -1 if it is not found.
It further tightens the search criteria to a use that kills the register if isKill is true.
Definition at line 943 of file MachineInstr.cpp.
References llvm::numbers::e, getNumOperands(), getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), and llvm::TargetRegisterInfo::regsOverlap().
Referenced by findCondCodeUsedByInstr(), findRegisterUseOperand(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), llvm::HexagonInstrInfo::getOperandLatency(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::CoalescerPair::isCoalescable(), isVirtualRegisterOperand(), killsRegister(), readsRegister(), registerDefIsDead(), llvm::PPCInstrInfo::replaceInstrOperandWithImm(), and llvm::R600InstrInfo::usesAddressRegister().
findTiedOperandIdx()
unsigned MachineInstr::findTiedOperandIdx (unsigned OpIdx) const
Given the index of a tied register operand, find the operand it is tied to.
Defs are tied to uses and vice versa. Returns the index of the tied operand which must exist.
Definition at line 1075 of file MachineInstr.cpp.
References assert(), llvm::numbers::e, llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), getNumOperands(), getOperand(), llvm::MachineOperand::isImm(), isInlineAsm(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isTied(), llvm::MachineOperand::isUse(), llvm::InlineAsm::isUseOperandTiedToDef(), llvm_unreachable, llvm::InlineAsm::MIOp_FirstOperand, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase::size().
Referenced by findRegisterDefOperand(), findSingleRegDef(), hasComplexRegisterTies(), isCoalescable(), isRegTiedToDefOperand(), isRegTiedToUseOperand(), operator<<(), llvm::MIPrinter::print(), print(), untieRegOperand(), and llvm::SIInstrInfo::verifyInstruction().
getAsmPrinterFlag()
bool llvm::MachineInstr::getAsmPrinterFlag (CommentFlag Flag) const inline
Return whether an AsmPrinter flag is set.
Definition at line 292 of file MachineInstr.h.
Referenced by emitComments().
getAsmPrinterFlags()
uint8_t llvm::MachineInstr::getAsmPrinterFlags () const inline
Return the asm printer flags bitvector.
Definition at line 286 of file MachineInstr.h.
Referenced by llvm::X86AsmPrinter::EmitInstruction().
getBundleSize()
unsigned MachineInstr::getBundleSize () const
Return the number of instructions inside the MI bundle, excluding the bundle header.
Return the number of instructions inside the MI bundle, not counting the header instruction.
This is the number of instructions that MachineBasicBlock::iterator skips, 0 for unbundled instructions.
Definition at line 919 of file MachineInstr.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >::getIterator(), I, and Size.
Referenced by INITIALIZE_PASS(), and isTransient().
getDebugExpression()
const DIExpression * MachineInstr::getDebugExpression () const
Return the complex address expression referenced by this DBG_VALUE instruction.
Definition at line 821 of file MachineInstr.cpp.
References assert(), llvm::MachineOperand::getMetadata(), getOperand(), and isDebugValue().
Referenced by AssignProtectedObjSet(), collectRegDefs(), computeExprForSpill(), emitDebugValueComment(), llvm::DbgVariableLocation::extractFromMachineInstruction(), getDebugLoc(), getDebugLocValue(), handleNewDebugValue(), INITIALIZE_PASS(), llvm::DbgVariable::initializeDbgValue(), isDebugEntryValue(), isDescribedByReg(), isRegOtherThanSPAndFP(), llvm::SelectionDAGISel::runOnMachineFunction(), and validThroughout().
getDebugLabel()
const DILabel * MachineInstr::getDebugLabel () const
Return the debug label referenced by this DBG_LABEL instruction.
Definition at line 811 of file MachineInstr.cpp.
References assert(), llvm::MachineOperand::getMetadata(), getOperand(), and isDebugLabel().
Referenced by llvm::MachineInstrBuilder::addMetadata(), emitDebugLabelComment(), and getDebugLoc().
getDebugLoc()
const DebugLoc& llvm::MachineInstr::getDebugLoc () const inline
Returns the debug location id of this MachineInstr.
Definition at line 400 of file MachineInstr.h.
References emitError(), getDebugExpression(), getDebugLabel(), and getDebugVariable().
Referenced by addExclusiveRegPair(), addImplicitDefUseOperands(), addRegsToSet(), addSegmentsWithValNo(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), allPhiOperandsUndefined(), llvm::analyzeArguments(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::BTFDebug::beginInstruction(), llvm::CodeViewDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::buildDbgValueForSpill(), buildEXP(), llvm::SIInstrInfo::buildShrunkInst(), llvm::SITargetLowering::bundleInstWithWaitcnt(), callWaitsOnFunctionReturn(), canTurnIntoCOPY(), changeFCMPPredToAArch64CC(), llvm::X86InstrInfo::classifyLEAReg(), collectRegDefs(), CombineCVTAToLocal(), llvm::PPCInstrInfo::commuteInstructionImpl(), computeExprForSpill(), llvm::constrainOperandRegClass(), ContainsReg(), convertImplicitDefToConstZero(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::createGCNDPPCombinePass(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::createSIAddIMGInitPass(), llvm::createSIWholeQuadModePass(), llvm::createX86FixupBWInsts(), llvm::createX86FixupSetCC(), definesFullReg(), doesNotGeneratecode(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::VERegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBuildPairF64Pseudo(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), emitIndirectDst(), emitIndirectSrc(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostSt(), emitReadCycleWidePseudo(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSplitF64Pseudo(), emitXBegin(), llvm::TargetLoweringBase::emitXRayCustomEvent(), llvm::TargetLoweringBase::emitXRayTypedEvent(), eraseDeadBBsAndChildren(), expandLoadStackGuard(), expandMOV32r1(), ExpandMOVImmSExti8(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), llvm::HexagonInstrInfo::expandVGatherPseudo(), extractRsrcPtr(), findIncDecAfter(), findPotentialBlockers(), findStartOfTree(), findVCMPToFoldIntoVPST(), llvm::fixStackStores(), fixupGlobalSaddr(), fixupRegionExits(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), foldVGPRCopyIntoRegSequence(), for(), forceReg(), FuseInst(), FuseTwoAddrInst(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), genFusedMultiply(), genMaddR(), genNeg(), getAdjustedCmp(), getBufferFormatWithCompCount(), llvm::ARMFrameLowering::getCalleeSaves(), getCmpForPseudo(), getCompareSourceReg(), getDSShaderTypeValue(), GetDSubRegs(), llvm::HexagonHazardRecognizer::getHazardType(), getINCDECFromLEA(), GetInitialOffset(), getLaneCopyOpcode(), getLogicalBitOpcode(), getMappedOp(), getNewSource(), getNewValueJumpOpcode(), getPostIndexedLoadStoreOpcode(), getRegClassFromGRPhysReg(), getRegsUsedByPHIs(), getRetpolineSymbol(), getSubOpcode(), getTag(), llvm::BPFTargetLowering::getTargetNodeName(), getUnconditionalBrDisp(), getV_CMPOpcode(), getVectorSHLImm(), giveUpWithRemarks(), llvm::MipsTargetLowering::HandleByVal(), HandleVRSaveUpdate(), hasUseAfterLoop(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), llvm::DbgVariable::initializeDbgValue(), insertCopy(), insertDivByZeroTrap(), InsertFPConstInst(), InsertFPImmInst(), insertNoopInBundle(), insertNopBeforeInstruction(), insertPHI(), InsertSPConstInst(), InsertSPImmInst(), llvm::IRTranslator::IRTranslator(), isConstant(), isCopy(), llvm::isCopyMulResult(), isEFLAGSLive(), isFpMulInstruction(), isFullCopyOf(), isIdenticalTo(), isIdentityValue(), isInRage(), isLiveOut(), IsMovepDestinationRegPair(), isPHIRegionIndex(), isRegOtherThanSPAndFP(), IsSafeAndProfitableToMove(), isSimpleIf(), isStackPtrRelative(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), loadM0FromVGPR(), loadSRsrcFromVGPR(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), LowerFPToInt(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), makeImplicit(), MakeM0Inst(), matchSwap(), Mips16WhichOp8uOr16simm(), moveAndTeeForMultiUse(), llvm::SIInstrInfo::moveToVALU(), operator<<(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), performSink(), llvm::MIPrinter::print(), print(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::TargetInstrInfo::reassociateOps(), llvm::X86InstrInfo::reMaterialize(), llvm::ARMBaseInstrInfo::reMaterialize(), RemoveDeadAddBetweenLEAAndJT(), ReplaceFrameIndex(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::reportGISelFailure(), llvm::rewriteAArch64FrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AMDGPUInstructionSelector::select(), selectCopy(), llvm::ARMBaseInstrInfo::setExecutionDomain(), setM0ToIndexFromSGPR(), llvm::AMDGPUInstructionSelector::setupMF(), shouldUseAndMask(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), splitMBB(), llvm::SystemZInstrInfo::SystemZInstrInfo(), tryOptimizeLEAtoMOV(), tryToFoldACImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), updateOperand(), validThroughout(), and VerifyLowRegs().
getDebugVariable()
const DILocalVariable * MachineInstr::getDebugVariable () const
Return the debug variable referenced by this DBG_VALUE instruction.
Definition at line 816 of file MachineInstr.cpp.
References assert(), llvm::MachineOperand::getMetadata(), getOperand(), and isDebugValue().
Referenced by llvm::MachineInstrBuilder::addMetadata(), llvm::buildDbgValueForSpill(), collectRegDefs(), computeExprForSpill(), emitDebugValueComment(), getDebugLoc(), INITIALIZE_PASS(), llvm::DbgVariable::initializeDbgValue(), isRegOtherThanSPAndFP(), and llvm::SelectionDAGISel::runOnMachineFunction().
getDesc()
const MCInstrDesc& llvm::MachineInstr::getDesc () const inline
Returns the target instruction descriptor of this MachineInstr.
Definition at line 423 of file MachineInstr.h.
Referenced by llvm::addFrameReference(), addImplicitDefUseOperands(), addLiveInRegs(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), addRegsToSet(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), AnyAliasLiveIn(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::buildDbgValueForSpill(), llvm::HexagonPacketizerList::canPromoteToDotNew(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), llvm::DFAPacketizer::canReserveResources(), llvm::ResourceManager::canReserveResources(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), commuteVPTERNLOG(), computeBytesPoppedByCalleeForSRet(), llvm::TargetSchedModel::computeOperandLatency(), llvm::TargetSchedModel::computeReciprocalThroughput(), llvm::constrainSelectedInstRegOperands(), convertTailJumpOpcode(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), copyExtraImplicitOps(), copyImplicitOps(), llvm::createBreakFalseDeps(), llvm::createHexagonHardwareLoops(), CriticalPathStep(), definesFullReg(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitDirectiveRelocJalr(), llvm::X86AsmPrinter::EmitInstruction(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::TargetLoweringBase::emitXRayCustomEvent(), llvm::TargetLoweringBase::emitXRayTypedEvent(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::MipsSEInstrInfo::expandPostRAPseudo(), llvm::Mips16InstrInfo::expandPostRAPseudo(), llvm::MipsInstrInfo::findCommutedOpIndices(), llvm::SIInstrInfo::findCommutedOpIndices(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::TargetInstrInfo::findCommutedOpIndices(), findFirstPredOperandIdx(), llvm::findFirstVPTPredOperandIdx(), findPotentialBlockers(), findStartOfTree(), llvm::PPCInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::X86InstrInfo::foldMemoryOperandImpl(), FuseTwoAddrInst(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), llvm::LegalizerInfo::getAction(), llvm::HexagonInstrInfo::getAddrMode(), getAddrOffset(), llvm::Localizer::getAnalysisUsage(), llvm::RISCVInstrInfo::getBranchDestBlock(), llvm::HexagonInstrInfo::getCExtOpNum(), llvm::SIInstrInfo::getClampMask(), llvm::X86::getCondFromBranch(), llvm::X86::getCondFromCMov(), llvm::X86::getCondFromSETCC(), GetDSubRegs(), llvm::ARMBaseInstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomainCustom(), llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs(), llvm::X86InstrInfo::getFMA3OpcodeToCommuteOperands(), getFPReg(), llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), llvm::ARMHazardRecognizer::getHazardType(), getINCDECFromLEA(), llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs(), llvm::ScheduleDAG::getInstrDesc(), llvm::PPCInstrInfo::getInstrLatency(), llvm::TargetInstrInfo::getInstrLatency(), llvm::HexagonInstrInfo::getInstrTimingClassLatency(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::ARCInstrInfo::getInstSizeInBytes(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getLDMVariableDefsSize(), getLSMultipleTransferSize(), llvm::HexagonInstrInfo::getMaxValue(), llvm::HexagonInstrInfo::getMemAccessSize(), llvm::X86InstrInfo::getMemOperandWithOffset(), getMemoryOpOffset(), llvm::HexagonInstrInfo::getMinValue(), getNewSource(), getNewValueJumpOpcode(), llvm::HexagonInstrInfo::getNonExtOpcode(), llvm::TargetSchedModel::getNumMicroOps(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::TargetInstrInfo::getNumMicroOps(), getNumMicroOpsSwiftLdSt(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), llvm::RISCVInstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), getPostIncrementOperand(), getRegClassConstraint(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::HexagonInstrInfo::getSize(), getTargetMBB(), getTruncatedShiftCount(), llvm::HexagonInstrInfo::getType(), getTypeToPrint(), getUnconditionalBrDisp(), getUnderlyingObjects(), llvm::HexagonInstrInfo::getUnits(), getX86SSEConditionCode(), hasComplexRegisterTies(), llvm::MipsInstrInfo::HasForbiddenSlot(), llvm::SIInstrInfo::hasFPClamp(), llvm::SIInstrInfo::hasIntClamp(), llvm::X86InstrInfo::hasLockPrefix(), llvm::TargetInstrInfo::hasLowDefLatency(), llvm::HexagonInstrInfo::hasNonExtEquivalent(), hasProperty(), hasRAWHazard(), llvm::HexagonPacketizerList::ignorePseudoInstruction(), INITIALIZE_PASS(), insertPHI(), llvm::HexagonInstrInfo::isAccumulator(), llvm::HexagonInstrInfo::isAddrModeWithOffset(), isAddWithImmediate(), llvm::SIInstrInfo::isBufferSMRD(), isCoalescable(), llvm::HexagonInstrInfo::isComplex(), llvm::HexagonInstrInfo::isConstExtended(), isControlFlow(), isCopy(), isCopyFeedingInvariantStore(), isCrossCopy(), llvm::HexagonInstrInfo::isDependent(), llvm::SIInstrInfo::isDisableWQM(), llvm::SIInstrInfo::isDOT(), llvm::SIInstrInfo::isDPP(), llvm::SIInstrInfo::isDS(), llvm::HexagonInstrInfo::isEarlySourceInstr(), llvm::SIInstrInfo::isEXP(), llvm::HexagonInstrInfo::isExtendable(), llvm::HexagonInstrInfo::isExtended(), llvm::rdf::TargetOperandInfo::isFixedReg(), llvm::SIInstrInfo::isFixedSize(), llvm::SIInstrInfo::isFLAT(), llvm::SIInstrInfo::isFoldableCopy(), llvm::SIInstrInfo::isFPAtomic(), isFpMulInstruction(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), llvm::SIInstrInfo::isGather4(), llvm::AArch64InstrInfo::isGPRCopy(), llvm::AArch64InstrInfo::isGPRZero(), isHighLatencyCPSR(), llvm::SIInstrInfo::isImmOperandLegal(), isImmValidForOpcode(), llvm::SIInstrInfo::isInlineConstant(), llvm::HexagonInstrInfo::isLateResultInstr(), llvm::SIInstrInfo::isMAI(), llvm::SIInstrInfo::isMIMG(), llvm::SIInstrInfo::isMTBUF(), llvm::SIInstrInfo::isMUBUF(), isMulPowOf2(), llvm::HexagonInstrInfo::isNewValue(), llvm::HexagonInstrInfo::isNewValueStore(), llvm::HexagonInstrInfo::isOperandExtended(), llvm::SIInstrInfo::isOperandLegal(), llvm::SIInstrInfo::isPacked(), llvm::ARCInstrInfo::isPostIncrement(), llvm::ARMBaseInstrInfo::isPredicable(), llvm::HexagonInstrInfo::isPredicable(), llvm::TargetInstrInfo::isPredicable(), llvm::HexagonInstrInfo::isPredicated(), llvm::HexagonInstrInfo::isPredicatedNew(), llvm::HexagonInstrInfo::isPredicatedTrue(), llvm::ARCInstrInfo::isPreIncrement(), llvm::SIInstrInfo::isReallyTriviallyReMaterializable(), isRegOtherThanSPAndFP(), llvm::SIInstrInfo::isSALU(), llvm::SIInstrInfo::isScalarStore(), llvm::SIInstrInfo::isScalarUnit(), llvm::HexagonInstrInfo::isSchedulingBoundary(), llvm::SIInstrInfo::isSDWA(), llvm::SIInstrInfo::isSegmentSpecificFLAT(), llvm::SIInstrInfo::isSGPRSpill(), isSimpleBD12Move(), isSimpleMove(), llvm::SIInstrInfo::isSMRD(), llvm::HexagonInstrInfo::isSolo(), llvm::SIInstrInfo::isSOP1(), llvm::SIInstrInfo::isSOP2(), llvm::SIInstrInfo::isSOPC(), llvm::SIInstrInfo::isSOPK(), llvm::SIInstrInfo::isSOPP(), llvm::HexagonInstrInfo::isTC1(), llvm::HexagonInstrInfo::isTC2(), llvm::HexagonInstrInfo::isTC2Early(), llvm::HexagonInstrInfo::isTC4x(), llvm::TargetInstrInfo::isTriviallyReMaterializable(), llvm::SIInstrInfo::isVALU(), llvm::SIInstrInfo::isVGPRSpill(), llvm::SIInstrInfo::isVINTRP(), isVirtualRegisterOperand(), llvm::SIInstrInfo::isVOP1(), llvm::SIInstrInfo::isVOP2(), llvm::SIInstrInfo::isVOP3(), llvm::SIInstrInfo::isVOP3P(), llvm::SIInstrInfo::isVOPC(), llvm::SIInstrInfo::isWQM(), llvm::WebAssemblyMCInstLower::lower(), MakeM0Inst(), llvm::HexagonInstrInfo::mayBeCurLoad(), llvm::HexagonInstrInfo::mayBeNewStore(), llvm::SIInstrInfo::moveToVALU(), oneUseDominatesOtherUses(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), performCustomAdjustments(), llvm::TargetInstrInfo::PredicateInstruction(), RemoveDeadAddBetweenLEAAndJT(), llvm::DFAPacketizer::reserveResources(), llvm::ResourceManager::reserveResources(), llvm::SystemZHazardRecognizer::Reset(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::TargetSchedModel::resolveSchedClass(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), rewriteP2Align(), llvm::rewriteT2FrameIndex(), llvm::MipsInstrInfo::SafeInForbiddenSlot(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::SIInstrInfo::sopkIsZext(), stripExtraCopyOperands(), tieOpsIfNeeded(), tryAddToFoldList(), tryToFoldACImm(), updateOperand(), updateOperandRegConstraints(), usedAsAddr(), llvm::SIInstrInfo::usesFPDPRounding(), llvm::SIInstrInfo::usesLGKM_CNT(), llvm::SIInstrInfo::usesVM_CNT(), llvm::SystemZInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), VerifyLowRegs(), and VisitGlobalVariableForEmission().
getFlag()
bool llvm::MachineInstr::getFlag (MIFlag Flag) const inline
Return whether an MI flag is set.
Definition at line 312 of file MachineInstr.h.
Referenced by llvm::BTFDebug::beginInstruction(), llvm::CodeViewDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), canRenameUpToDef(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), FuseInst(), getOModValue(), isAddWithImmediate(), isBundledWithPred(), isBundledWithSucc(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), isInsideBundle(), llvm::isKnownNeverNaN(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::LegalizerHelper::lowerFMinNumMaxNum(), mayRaiseFPException(), llvm::MIPrinter::print(), llvm::MachineBasicBlock::print(), print(), and transferMIFlag().
getFlags()
uint16_t llvm::MachineInstr::getFlags () const inline
Return the MI flags bitvector.
Definition at line 307 of file MachineInstr.h.
Referenced by llvm::GISelInstProfileBuilder::addNodeID(), createPHIsForSelects(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), for(), IsMovepDestinationRegPair(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV16(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFDIVFastIntrin(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerFCopySign(), llvm::LegalizerHelper::lowerFMad(), llvm::LegalizerHelper::lowerFMinNumMaxNum(), llvm::LegalizerHelper::lowerIntrinsicRound(), mergeFlagsWith(), and VerifyLowRegs().
getFoldedRestoreSize()
Optional< unsigned > MachineInstr::getFoldedRestoreSize (const TargetInstrInfo * TII) const
Return a valid size if the instruction is a folded restore instruction.
Definition at line 2190 of file MachineInstr.cpp.
References llvm::MachineFunction::getFrameInfo(), getMF(), getSpillSlotSize(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), and llvm::None.
Referenced by emitComments(), and isRegTiedToDefOperand().
getFoldedSpillSize()
Optional< unsigned > MachineInstr::getFoldedSpillSize (const TargetInstrInfo * TII) const
Return a valid size if the instruction is a folded spill instruction.
Definition at line 2171 of file MachineInstr.cpp.
References llvm::MachineFunction::getFrameInfo(), getMF(), getSpillSlotSize(), llvm::TargetInstrInfo::hasStoreToStackSlot(), and llvm::None.
Referenced by emitComments(), INITIALIZE_PASS(), and isRegTiedToDefOperand().
getHeapAllocMarker()
MDNode* llvm::MachineInstr::getHeapAllocMarker () const inline
Helper to extract a heap alloc marker if one has been added.
Definition at line 612 of file MachineInstr.h.
Referenced by cloneInstrSymbols(), cloneMemRefs(), dropMemRefs(), llvm::MIPrinter::print(), print(), setHeapAllocMarker(), setMemRefs(), setPostInstrSymbol(), and setPreInstrSymbol().
getInlineAsmDialect()
InlineAsm::AsmDialect MachineInstr::getInlineAsmDialect () const
Definition at line 777 of file MachineInstr.cpp.
References assert(), llvm::InlineAsm::Extra_AsmDialect, llvm::MachineOperand::getImm(), getOperand(), isInlineAsm(), and llvm::InlineAsm::MIOp_ExtraInfo.
Referenced by llvm::X86AsmPrinter::EmitFunctionBodyEnd(), EmitGCCInlineAsmStr(), isMSInlineAsm(), print(), and llvm::X86AsmPrinter::PrintAsmMemoryOperand().
getIntrinsicID()
unsigned llvm::MachineInstr::getIntrinsicID () const inline
Returns the Intrinsic::ID for this instruction.
Precondition
Must have an intrinsic ID operand.
Definition at line 1664 of file MachineInstr.h.
References llvm::MachineOperand::getIntrinsicID(), getNumExplicitDefs(), getOperand(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), getDSShaderTypeValue(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappingsIntrinsic(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappingsIntrinsicWSideEffects(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), getLogicalBitOpcode(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::X86LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), and llvm::CombinerHelper::tryCombineMemCpyFamily().
getMF() [1/2]
const MachineFunction * MachineInstr::getMF () const
Return the function that contains the basic block that this instruction belongs to.
Note: this is undefined behaviour if the instruction does not have a parent.
Definition at line 655 of file MachineInstr.cpp.
References llvm::MachineBasicBlock::getParent(), and getParent().
Referenced by addExclusiveRegPair(), llvm::MipsRegisterBankInfo::applyMappingImpl(), attemptDebugCopyProp(), llvm::BTFDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), canFoldCopy(), cloneInstrSymbols(), cloneMemRefs(), cloneMergedMemRefs(), collectCallSiteParameters(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::TargetSchedModel::computeOutputLatency(), llvm::AArch64InstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), dumpMachineInstrRangeWithSlotIndex(), emitComments(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::TargetLoweringBase::emitXRayCustomEvent(), llvm::TargetLoweringBase::emitXRayTypedEvent(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), getFoldedRestoreSize(), getFoldedSpillSize(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), getFunctionReturns(), getImmedFromMO(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::RISCVInstrInfo::getInstSizeInBytes(), getMF(), getParent(), getRegClassConstraint(), getRestoreSize(), llvm::TargetInstrInfo::getSPAdjust(), getSpillSize(), llvm::GISelKnownBits::inferPtrAlignment(), INITIALIZE_PASS(), isAmbiguous(), isCallerPreservedOrConstPhysReg(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), isCopyFeedingInvariantStore(), isIntersect(), isInvariantStore(), isLibCallInTailPosition(), isVirtualRegisterOperand(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), lookupCandidateBaseReg(), llvm::LegalizerHelper::lowerBitCount(), llvm::LegalizerHelper::lowerDynStackAlloc(), mayAlias(), performSink(), llvm::MIPrinter::print(), llvm::RegisterBankInfo::OperandsMapper::print(), llvm::printMBBReference(), llvm::TargetInstrInfo::reassociateOps(), llvm::AsmPrinter::recordSled(), llvm::GCNRPTracker::reset(), llvm::RegScavenger::scavengeRegister(), llvm::CoalescerPair::setRegisters(), UpdatePredRedefs(), llvm::RegisterBankInfo::InstructionMapping::verify(), VisitGlobalVariableForEmission(), and llvm::LegalizerHelper::widenScalar().
getMF() [2/2]
MachineFunction* llvm::MachineInstr::getMF () inline
Definition at line 280 of file MachineInstr.h.
References getMF().
getNumDefs()
unsigned llvm::MachineInstr::getNumDefs () const inline
Returns the total number of definitions.
Definition at line 441 of file MachineInstr.h.
References getNumExplicitDefs(), and llvm::MCInstrDesc::getNumImplicitDefs().
Referenced by addRegsToSet(), llvm::X86InstrInfo::hasReassociableOperands(), and isCallerPreservedOrConstPhysReg().
getNumExplicitDefs()
unsigned MachineInstr::getNumExplicitDefs () const
Returns the number of non-implicit definitions.
Definition at line 718 of file MachineInstr.cpp.
References E, llvm::MCInstrDesc::getNumDefs(), getNumOperands(), getOperand(), I, llvm::MachineOperand::isDef(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), and llvm::MCInstrDesc::isVariadic().
Referenced by llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::AMDGPURegisterBankInfo::applyMappingImage(), defs(), llvm::TargetInstrInfo::describeLoadedValue(), explicit_uses(), llvm::AMDGPURegisterBankInfo::getImageMapping(), getIntrinsicID(), getNumDefs(), llvm::X86InstrInfo::hasReassociableOperands(), isOperandSubregIdx(), and uses().
getNumExplicitOperands()
unsigned MachineInstr::getNumExplicitOperands () const
Returns the number of non-implicit operands.
Definition at line 699 of file MachineInstr.cpp.
References E, llvm::MCInstrDesc::getNumOperands(), getNumOperands(), getOperand(), I, llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), and llvm::MCInstrDesc::isVariadic().
Referenced by llvm::SystemZInstrInfo::analyzeCompare(), llvm::SIInstrInfo::buildExtractSubRegOrImm(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::constrainSelectedInstRegOperands(), createPHIsForSelects(), llvm::createSIWholeQuadModePass(), llvm::createX86FixupBWInsts(), llvm::SIInstrInfo::expandMovDPP64(), explicit_operands(), explicit_uses(), fixupCalleeSaveRestoreStackOffset(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::RISCVInstrInfo::getBranchDestBlock(), llvm::AArch64InstrInfo::getMemOpBaseRegImmOfsOffsetOperand(), llvm::RISCVInstrInfo::getMemOperandWithOffsetWidth(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), llvm::PPCInstrInfo::getMemOperandWithOffsetWidth(), getNumImplicitOperands(), getRegClassFromGRPhysReg(), getRegSeqInit(), getTypeToPrint(), getUnconditionalBrDisp(), getVectorSHLImm(), hasImplicitDef(), llvm::X86InstrInfo::hasReassociableOperands(), INITIALIZE_PASS(), isAddWithImmediate(), isCompareZero(), isOperandSubregIdx(), performCustomAdjustments(), and llvm::SIInstrInfo::verifyInstruction().
getNumImplicitOperands()
unsigned llvm::MachineInstr::getNumImplicitOperands () const inline
Returns the implicit operands number.
Definition at line 457 of file MachineInstr.h.
References getNumExplicitOperands(), and getNumOperands().
getNumMemOperands()
unsigned llvm::MachineInstr::getNumMemOperands () const inline
Return the number of memory operands.
Definition at line 585 of file MachineInstr.h.
References memoperands().
getNumOperands()
unsigned llvm::MachineInstr::getNumOperands () const inline
Retuns the total number of operands.
Definition at line 429 of file MachineInstr.h.
Referenced by addExclusiveRegPair(), addImplicitDefUseOperands(), addLiveInRegs(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), addOperand(), addRegisterDead(), addRegisterKilled(), addRegsToSet(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::HexagonSubtarget::adjustSchedDependency(), allPhiOperandsUndefined(), llvm::AArch64InstrInfo::analyzeCompare(), llvm::LiveRangeEdit::anyRematerializable(), appendEndToFunction(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::SwingSchedulerDAG::applyInstrChange(), llvm::AMDGPURegisterBankInfo::applyMappingImage(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), AssignProtectedObjSet(), BBIsJumpedOver(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::EHStreamer::callToNoUnwindFunction(), callWaitsOnFunctionReturn(), canCombine(), llvm::HexagonInstrInfo::canExecuteInBundle(), canFoldCopy(), canFoldIntoSelect(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), canTurnIntoCOPY(), NoAutoPaddingScope::changeAndComment(), clobbersCTR(), llvm::ARMBaseInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), commuteVPTERNLOG(), llvm::HexagonEvaluator::composeWithSubRegIndex(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), copyExtraImplicitOps(), copyImplicitOps(), llvm::createBreakFalseDeps(), llvm::createHexagonHardwareLoops(), llvm::createMemLibcall(), llvm::createSIAddIMGInitPass(), llvm::createX86FixupBWInsts(), CriticalPathStep(), definesFullReg(), llvm::ARMBaseInstrInfo::DefinesPredicate(), llvm::HexagonInstrInfo::DefinesPredicate(), llvm::PPCInstrInfo::DefinesPredicate(), llvm::BPFRegisterInfo::eliminateFrameIndex(), emitDebugLabelComment(), emitDebugValueComment(), emitDirectiveRelocJalr(), emitError(), EmitGCCInlineAsmStr(), llvm::X86AsmPrinter::EmitInstruction(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), emitKill(), EmitMSInlineAsmStr(), llvm::TargetLoweringBase::emitPatchPoint(), emitXBegin(), llvm::TargetLoweringBase::emitXRayCustomEvent(), llvm::TargetLoweringBase::emitXRayTypedEvent(), eraseGPOpnd(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::BitTracker::MachineEvaluator::evaluate(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), findCorrespondingPred(), findFirstPredOperandIdx(), findIncDecAfter(), findInlineAsmFlagIdx(), findRegisterDefOperandIdx(), findRegisterUseOperandIdx(), findSingleRegDef(), findSRegBaseAndIndex(), findTiedOperandIdx(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), llvm::SwingSchedulerDAG::fixupRegisterOverlaps(), llvm::PPCInstrInfo::FoldImmediate(), foldPatchpoint(), foldVGPRCopyIntoRegSequence(), FuseInst(), FuseTwoAddrInst(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), getBufferFormatWithCompCount(), getCallTargetRegOpnd(), getCompareSourceReg(), getDebugLocValue(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::AMDGPURegisterBankInfo::getDefaultMappingSOP(), llvm::AMDGPURegisterBankInfo::getDefaultMappingVOP(), llvm::PPCInstrInfo::getDefMIPostRA(), getFPReg(), getFrameIndexOperandNum(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::HexagonHazardRecognizer::getHazardType(), llvm::AMDGPURegisterBankInfo::getImageMapping(), getInitPhiReg(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::PPCInstrInfo::getInstrLatency(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), llvm::RegisterBankInfo::getInstrMappingImpl(), getInstrVecReg(), getLaneCopyOpcode(), llvm::ARMBaseInstrInfo::getLDMVariableDefsSize(), getLogicalBitOpcode(), getLoopPhiReg(), getLSMultipleTransferSize(), llvm::LanaiInstrInfo::getMemOperandWithOffsetWidth(), getNewValueJumpOpcode(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::rdf::DataFlowGraph::getNextShadow(), getNumExplicitDefs(), getNumExplicitOperands(), getNumImplicitOperands(), llvm::ARMBaseInstrInfo::getNumMicroOps(), getOperand(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), getPHIDeps(), getPHINumInputs(), getPhiRegs(), getPHISrcRegOpIdx(), getRegClassFromGRPhysReg(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::getRegSequenceSubReg(), getRegsUsedByPHIs(), llvm::HexagonInstrInfo::getSize(), getStoreValueOperand(), getTag(), getTypeFromTypeIdx(), getUnconditionalBrDisp(), getVectorSHLImm(), getX86SSEConditionCode(), llvm::LiveVariables::HandleVirtRegDef(), HandleVRSaveUpdate(), hasComplexRegisterTies(), HashMachineInstr(), hasImplicitDef(), llvm::X86InstrInfo::hasLiveCondCodeDef(), hasRegisterDependency(), hasRegisterImplicitUseOperand(), hasVectorOperands(), llvm::HexagonLowerToMC(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), InsertLDR_STR(), llvm::Mips16RegisterInfo::intRegClass(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), isAmbiguous(), isBackwardPropagatableCopy(), isBinary(), isCallerPreservedOrConstPhysReg(), llvm::WebAssembly::isChild(), isCoalescable(), isConstantValuePHI(), isCopyFeedingInvariantStore(), isCSRestore(), isDbgValueDescribedByReg(), isDebug(), isDescribedByReg(), llvm::SIInstrInfo::isFoldableCopy(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), isFullCopyOf(), isFullUndefDef(), isIdenticalTo(), isIdentityValue(), isImmValidForOpcode(), isImplicitlyDef(), isInvariantStore(), llvm::ARMBaseInstrInfo::isLDMBaseRegInList(), isLEA(), llvm::isLeaMem(), llvm::SMSchedule::isLoopCarriedDefOfUse(), llvm::isMem(), isNopCopy(), isNullary(), llvm::SIInstrInfo::isOperandLegal(), isPreISelGenericFloatingPointOpcode(), llvm::SIInstrInfo::isReallyTriviallyReMaterializable(), isRegOtherThanSPAndFP(), llvm::AMDGPURegisterBankInfo::isSALUMapping(), llvm::PPCInstrInfo::isSignOrZeroExtended(), llvm::ARMBaseInstrInfo::isSwiftFastImmShift(), llvm::HexagonInstrInfo::isToBeScheduledASAP(), isTwoAddrUse(), isVirtualRegisterOperand(), llvm::SIInstrInfo::legalizeOperands(), lookupCandidateBaseReg(), llvm::XCoreMCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::MSP430MCInstLower::Lower(), llvm::ARCMCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::MipsMCInstLower::LowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerSparcMachineInstrToMCInst(), llvm::LegalizerHelper::lowerUnmergeValues(), llvm::LowerVEMachineInstrToMCInst(), MakeM0Inst(), llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >::match(), llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::match(), matchSwap(), llvm::LegalizerHelper::moreElementsVector(), llvm::LegalizerHelper::moreElementsVectorPhi(), llvm::SIInstrInfo::moveToVALU(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::AggressiveAntiDepBreaker::Observe(), false::IntervalSorter::operator()(), operator<<(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeLoadInstr(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), optimizeVcndVcmpPair(), llvm::SMSchedule::orderDependence(), parseOperands(), llvm::PatchPointOpers::PatchPointOpers(), performSink(), llvm::TargetInstrInfo::PredicateInstruction(), llvm::MIPrinter::print(), print(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::printMemOperand(), llvm::MipsAsmPrinter::printRegisterList(), llvm::ARMBaseInstrInfo::produceSameValue(), readsWritesVirtualRegister(), removeKillInfo(), RemoveOperand(), removeOperands(), llvm::LiveVariables::removeVirtualRegisterDead(), llvm::LiveVariables::removeVirtualRegisterKilled(), llvm::LiveVariables::removeVirtualRegistersKilled(), llvm::PPCInstrInfo::replaceInstrWithLI(), llvm::MachineBasicBlock::replacePhiUsesWith(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), resultTests(), llvm::rewriteT2FrameIndex(), llvm::DetectRoundChange::runOnMachineFunction(), shrinkScalarCompare(), simpleLibcall(), sizeOfSPAdjustment(), llvm::StackMapOpers::StackMapOpers(), stripExtraCopyOperands(), swapMIOperands(), llvm::SystemZInstrInfo::SystemZInstrInfo(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), llvm::LegalizationArtifactCombiner::tryCombineMerges(), llvm::tryFoldSPUpdateIntoPushPop(), tryToFoldACImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), updateOperand(), UpdateOperandRegClass(), updateOperandRegConstraints(), usedAsAddr(), llvm::HexagonSubtarget::usePredicatedCalls(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::ValueIsNewPHI(), llvm::RegisterBankInfo::InstructionMapping::verify(), llvm::SystemZInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), VerifyLowRegs(), llvm::MachineRegisterInfo::verifyUseList(), VisitGlobalVariableForEmission(), and llvm::LegalizerHelper::widenScalar().
getOpcode()
unsigned llvm::MachineInstr::getOpcode () const inline
Returns the opcode of this MachineInstr.
Definition at line 426 of file MachineInstr.h.
References llvm::MCInstrDesc::Opcode.
Referenced by addExclusiveRegPair(), llvm::R600InstrInfo::addFlag(), llvm::GISelInstProfileBuilder::addNodeID(), addRegsToSet(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::GCNSubtarget::adjustSchedDependency(), llvm::GISelCSEInfo::analyze(), llvm::analyzeArguments(), llvm::MipsInstrInfo::analyzeBranch(), llvm::LanaiInstrInfo::analyzeCompare(), llvm::AArch64InstrInfo::analyzeCompare(), llvm::HexagonInstrInfo::analyzeCompare(), llvm::ARMBaseInstrInfo::analyzeCompare(), llvm::PPCInstrInfo::analyzeCompare(), llvm::X86InstrInfo::analyzeCompare(), AnyAliasLiveIn(), appendEndToFunction(), llvm::HexagonSubtarget::HVXMemLatencyMutation::apply(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::CombinerHelper::applyCombineIndexedLoadStore(), llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::CombinerHelper::applyPtrAddImmedChain(), areCandidatesToMergeOrPair(), areCombinableOperations(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), AssignProtectedObjSet(), BBHasFallthrough(), BBIsJumpedOver(), llvm::BTFDebug::beginInstruction(), branchTargetOperand(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), callWaitsOnFunctionReturn(), llvm::R600InstrInfo::canBeConsideredALU(), canCombine(), canCompareBeNewValueJump(), canDefBePartOfLOH(), llvm::HexagonInstrInfo::canExecuteInBundle(), canFoldIntoCSel(), canInstrSubstituteCmpInstr(), llvm::X86InstrInfo::canMakeTailCallConditional(), cannotCoexistAsymm(), llvm::SIInstrInfo::canShrink(), canTurnIntoCOPY(), llvm::HexagonInstrInfo::changeAddrMode_abs_io(), llvm::HexagonInstrInfo::changeAddrMode_io_abs(), llvm::HexagonInstrInfo::changeAddrMode_io_rr(), llvm::HexagonInstrInfo::changeAddrMode_rr_io(), llvm::HexagonInstrInfo::changeAddrMode_rr_ur(), llvm::HexagonInstrInfo::changeAddrMode_ur_rr(), changeFCMPPredToAArch64CC(), changesVGPRIndexingMode(), CheckXWPInstr(), classifyFirst(), llvm::R600InstrInfo::clearFlag(), llvm::ARMBaseInstrInfo::commuteInstructionImpl(), llvm::SIInstrInfo::commuteInstructionImpl(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::SystemZInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::SIInstrInfo::commuteOpcode(), computeBranchTargetAndInversion(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), ConsecutiveInstr(), llvm::constrainSelectedInstRegOperands(), ContainsReg(), conversionLibcall(), convertImplicitDefToConstZero(), convertTailJumpOpcode(), llvm::PPCInstrInfo::convertToImmediateForm(), convertToNonFlagSettingOpc(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::createGCNDPPCombinePass(), llvm::createMemLibcall(), createPHIsForCMOVsInSinkBB(), llvm::createR600ExpandSpecialInstrsPass(), llvm::createSIAddIMGInitPass(), llvm::createSIModeRegisterPass(), llvm::createSIWholeQuadModePass(), llvm::createX86FixupBWInsts(), llvm::TargetInstrInfo::defaultDefLatency(), llvm::R600InstrInfo::DefinesPredicate(), llvm::AArch64InstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), doesNotGeneratecode(), llvm::HexagonInstrInfo::doesNotReturn(), llvm::CombinerHelper::dominates(), dumpMachineInstrRangeWithSlotIndex(), llvm::SystemZHazardRecognizer::dumpSU(), llvm::SparcFrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::VEFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), emitBuildPairF64Pseudo(), EmitHiLo(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::WebAssemblyAsmPrinter::EmitInstruction(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::PPCHazardRecognizer970::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::Mips16TargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::SparcTargetLowering::EmitInstrWithCustomInserter(), llvm::RISCVTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64TargetLowering::EmitInstrWithCustomInserter(), llvm::SystemZTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::HexagonFrameLowering::emitPrologue(), emitReadCycleWidePseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSplitF64Pseudo(), llvm::TargetLoweringBase::emitXRayCustomEvent(), llvm::TargetLoweringBase::emitXRayTypedEvent(), enableAllocFrameElim(), eraseDeadBBsAndChildren(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::evaluate(), llvm::SIInstrInfo::expandMovDPP64(), ExpandMOVImmSExti8(), llvm::BPFInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::R600InstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SystemZInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandVGatherPseudo(), llvm::PPCInstrInfo::expandVSXMemPseudo(), expandXorFP(), llvm::LegalizerHelper::fewerElementsVector(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::MipsInstrInfo::findCommutedOpIndices(), llvm::PPCInstrInfo::findCommutedOpIndices(), llvm::X86InstrInfo::findCommutedOpIndices(), findCondCodeUsedByInstr(), findFirstPredicateSetterFrom(), findIncDecAfter(), findPotentialBlockers(), findSingleRegDef(), findSRegBaseAndIndex(), findStartOfTree(), findUncondBrI(), llvm::R600InstrInfo::fitsConstReadLimitations(), fixupCalleeSaveRestoreStackOffset(), fixupGlobalSaddr(), llvm::foldFrameOffset(), llvm::SystemZInstrInfo::FoldImmediate(), llvm::PPCInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), foldImmediates(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), followSubRegDef(), for(), frameIndexMayFold(), fuseInstructionPair(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), llvm::LegalizerInfo::getAction(), getAdjustedCmp(), llvm::HexagonFrameLowering::getAlignaInstr(), getAssignFnsForCC(), llvm::AMDGPU::getBaseWithConstantOffset(), llvm::AVRInstrInfo::getBranchDestBlock(), llvm::AArch64InstrInfo::getBranchDestBlock(), llvm::SIInstrInfo::getBranchDestBlock(), llvm::SystemZInstrInfo::getBranchInfo(), getBRccForPseudo(), getBufferFormatWithCompCount(), llvm::ARMFrameLowering::getCalleeSaves(), getCmpForPseudo(), getComparePred(), getCompareSourceReg(), llvm::HexagonInstrInfo::getCompoundCandidateGroup(), llvm::HexagonInstrInfo::getCompoundOpcode(), llvm::X86::getCondFromBranch(), llvm::X86::getCondFromCMov(), llvm::X86::getCondFromSETCC(), llvm::getConstantFPVRegVal(), llvm::getConstantVRegValWithLookThrough(), getCopyRewriter(), llvm::getDefIgnoringCopies(), llvm::PPCInstrInfo::getDefMIPostRA(), llvm::HexagonInstrInfo::getDotCurOp(), llvm::HexagonInstrInfo::getDotNewOp(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), llvm::HexagonInstrInfo::getDotNewPredOp(), llvm::HexagonInstrInfo::getDotOldOp(), GetDSubRegs(), llvm::HexagonInstrInfo::getDuplexCandidateGroup(), llvm::HexagonInstrInfo::getEquivalentHWInstr(), llvm::ARMBaseInstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomainCustom(), llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs(), llvm::R600InstrInfo::getFlagOp(), llvm::X86InstrInfo::getFMA3OpcodeToCommuteOperands(), getFMAPatterns(), llvm::SIRegisterInfo::getFrameIndexInstrOffset(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::ARMHazardRecognizer::getHazardType(), llvm::HexagonHazardRecognizer::getHazardType(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::GCNHazardRecognizer::getHazardType(), getImmedFromMO(), getINCDECFromLEA(), llvm::HexagonInstrInfo::getIncrementValue(), llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs(), getInsertVecEltOpInfo(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getInstSizeInBytes(), llvm::AVRInstrInfo::getInstSizeInBytes(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::PPCInstrInfo::getInstSizeInBytes(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::getITInstrPredicate(), getLaneCopyOpcode(), getLeaOP(), getLoadInfo(), getLoadStoreOffsetAlign(), getLogicalBitOpcode(), getLSMultipleTransferSize(), getMaddPatterns(), getMappedOp(), llvm::LanaiInstrInfo::getMemOperandWithOffset(), llvm::SIInstrInfo::getMemOperandWithOffset(), llvm::LanaiInstrInfo::getMemOperandWithOffsetWidth(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), getMemoryOpOffset(), llvm::AArch64InstrInfo::getMemScale(), llvm::SIRegisterInfo::getMUBUFInstrOffset(), llvm::SIInstrInfo::getNamedImmOperand(), llvm::SIInstrInfo::getNamedOperand(), getNewValueJumpOpcode(), llvm::HexagonInstrInfo::getNonDotCurOp(), llvm::HexagonInstrInfo::getNonExtOpcode(), getNonPseudoCallIndirectOpcode(), llvm::ARMBaseInstrInfo::getNumMicroOps(), getNumMicroOpsSwiftLdSt(), llvm::SIInstrInfo::getNumWaitStates(), getOffsetONFromFION(), getOModValue(), llvm::getOpcodeDef(), llvm::R600InstrInfo::getOperandIdx(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::SIInstrInfo::getOpRegClass(), llvm::AArch64InstrInfo::getOutliningCandidateInfo(), llvm::AArch64InstrInfo::getOutliningType(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::X86InstrInfo::getPartialRegUpdateClearance(), getPostIndexedLoadStoreOpcode(), llvm::HexagonInstrInfo::getPseudoInstrPair(), getReassignedChan(), getRegClassForUnfoldedLoad(), getRegClassFromGRPhysReg(), llvm::HexagonInstrInfo::getRegForm(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), getRetpolineSymbol(), getShiftTypeForInst(), llvm::HexagonInstrInfo::getSize(), llvm::X86InstrInfo::getSPAdjust(), llvm::TargetInstrInfo::getSPAdjust(), getSrcFromCopy(), llvm::R600InstrInfo::getSrcs(), getStartOrEndSlot(), getStoreOffset(), getStoreTarget(), getSubOpcode(), getTypeFromTypeIdx(), getUnconditionalBrDisp(), llvm::X86InstrInfo::getUndefRegClearance(), getUnderlyingObjects(), llvm::SIInstrInfo::getVALUOp(), getVariantKind(), getVectorSHLImm(), llvm::getVRegSubRegDef(), getWinAllocaAmount(), handleMiddleInst(), llvm::LiveIntervals::handleMove(), llvm::GISelCSEInfo::handleRecordedInst(), handleUse(), hasArgumentDef(), llvm::X86InstrInfo::hasHighOperandLatency(), HashMachineInstr(), llvm::HexagonInstrInfo::hasNonExtEquivalent(), llvm::HexagonInstrInfo::hasPseudoInstrPair(), llvm::TargetInstrInfo::hasReassociableSibling(), llvm::SIInstrInfo::hasUnwantedEffectsWhenEXECEmpty(), hasVulnerableLoad(), llvm::HexagonLowerToMC(), hoistAndMergeSGPRInits(), llvm::GISelKnownBits::inferPtrAlignment(), INITIALIZE_PASS(), llvm::SMSchedule::insert(), insertCopy(), insertCSRRestores(), InsertFPConstInst(), InsertFPImmInst(), InsertLDR_STR(), InsertSPConstInst(), InsertSPImmInst(), llvm::BTFDebug::InstLower(), llvm::rdf::CopyPropagation::interpretAsCopy(), llvm::Mips16RegisterInfo::intRegClass(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), llvm::isAArch64FrameOffsetLegal(), isAddConstantOp(), llvm::PPCInstrInfo::isADDIInstrEligibleForFolding(), llvm::AArch64InstrInfo::isAddImmediate(), llvm::ARMBaseInstrInfo::isAddImmediate(), llvm::PPCInstrInfo::isADDInstrEligibleForFolding(), llvm::HexagonInstrInfo::isAddrModeWithOffset(), isAddWithImmediate(), llvm::isAESPair(), isAmbiguous(), isAnnotationLabel(), isArtifact(), llvm::AArch64InstrInfo::isAsCheapAsAMove(), llvm::RISCVInstrInfo::isAsCheapAsAMove(), llvm::AArch64InstrInfo::isAssociativeAndCommutative(), llvm::PPCInstrInfo::isAssociativeAndCommutative(), llvm::X86InstrInfo::isAssociativeAndCommutative(), llvm::InstructionSelector::isBaseWithConstantOffset(), llvm::SIInstrInfo::isBasicBlockPrologue(), llvm::PPCInstrInfo::isBDNZ(), llvm::AMDGPUAsmPrinter::isBlockOnlyReachableByFallthrough(), isBranchRetTrap(), isBRccPseudo(), llvm::SIInstrInfo::isBufferSMRD(), isBundle(), isCallerPreservedOrConstPhysReg(), isCandidateLoad(), isCandidateStore(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), isCFIInstruction(), isCMOVPseudo(), llvm::AArch64InstrInfo::isCoalescableExtInstr(), llvm::X86InstrInfo::isCoalescableExtInstr(), llvm::PPCInstrInfo::isCoalescableExtInstr(), isCombineInstrCandidateFP(), isCompareZero(), isConstant(), isCopy(), isCopy(), isCopyFeedingInvariantStore(), llvm::ARMBaseInstrInfo::isCopyInstrImpl(), llvm::AArch64InstrInfo::isCopyInstrImpl(), isCopyLike(), isCopyToExec(), isCrossCopy(), isCSRestore(), isCVTAToLocalCombinationCandidate(), isDataInvariant(), isDataInvariantLoad(), llvm::HexagonInstrInfo::isDeallocRet(), isDebugLabel(), isDebugValue(), isDefConvertible(), isDirectJump(), llvm::HexagonInstrInfo::isDotCurInst(), isEFLAGSLive(), isEHLabel(), isEligibleForITBlock(), isEndCF(), llvm::HexagonInstrInfo::isExtendable(), isExtractSubreg(), llvm::AArch64InstrInfo::isFalkorShiftExtFast(), isFirstInstructionInSequence(), llvm::HexagonInstrInfo::isFloat(), llvm::SIInstrInfo::isFoldableCopy(), isFpMulInstruction(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::TargetInstrInfo::isFrameInstr(), llvm::PPCRegisterInfo::isFrameOffsetLegal(), llvm::TargetInstrInfo::isFrameSetup(), isFullCopyOf(), isFuncletReturnInstr(), isGCLabel(), llvm::AArch64InstrInfo::isGPRCopy(), llvm::AArch64InstrInfo::isGPRZero(), isGreaterThanNBitTFRI(), isHardwareLoop(), isHighLatencyCPSR(), llvm::SIInstrInfo::isHighLatencyInstruction(), isIdenticalTo(), isIdentityValue(), llvm::PPCInstrInfo::isImmInstrEligibleForFolding(), llvm::SIInstrInfo::isImmOperandLegal(), isImplicitDef(), isImplicitlyDef(), isIncrementOrDecrement(), llvm::HexagonInstrInfo::isIndirectCall(), llvm::HexagonInstrInfo::isIndirectL4Return(), isInlineAsm(), isInlineConstantIfFolded(), isInsertSubreg(), llvm::HexagonInstrInfo::isJumpR(), llvm::HexagonInstrInfo::isJumpWithinBranchRange(), isKill(), llvm::isKnownNeverNaN(), llvm::HexagonInstrInfo::isLateResultInstr(), isLEA(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::isLiteralsPair(), isLiveOut(), isLoadAbsSet(), isLoadAndTestAsCmp(), llvm::RISCVInstrInfo::isLoadFromStackSlot(), llvm::MipsSEInstrInfo::isLoadFromStackSlot(), llvm::ARCInstrInfo::isLoadFromStackSlot(), llvm::LanaiInstrInfo::isLoadFromStackSlot(), llvm::XCoreInstrInfo::isLoadFromStackSlot(), llvm::SparcInstrInfo::isLoadFromStackSlot(), llvm::HexagonInstrInfo::isLoadFromStackSlot(), llvm::AArch64InstrInfo::isLoadFromStackSlot(), llvm::AVRInstrInfo::isLoadFromStackSlot(), llvm::ARMBaseInstrInfo::isLoadFromStackSlot(), llvm::X86InstrInfo::isLoadFromStackSlot(), llvm::PPCInstrInfo::isLoadFromStackSlot(), llvm::LanaiInstrInfo::isLoadFromStackSlotPostFE(), llvm::X86InstrInfo::isLoadFromStackSlotPostFE(), isLoadStoreThatCanHandleDisplacement(), isLogicalOpOnExec(), llvm::HexagonInstrInfo::isLoopN(), llvm::isLoopStart(), llvm::SIInstrInfo::isLowLatencyInstruction(), isMatchingStore(), llvm::HexagonInstrInfo::isMemOp(), isMemoryOp(), isMergeableLdStUpdate(), isMetaInstruction(), isMla(), IsMovepDestinationRegPair(), isMul(), isNonFoldablePartialRegisterLoad(), llvm::SIInstrInfo::isNonUniformBranchInstr(), llvm::SIInstrInfo::isOperandLegal(), isOptimizeCompareCandidate(), isORCopyInst(), llvm::AArch64InstrInfo::isPairableLdStInst(), isPairedLdSt(), isPermlane(), isPHI(), isPhysicalRegCopy(), llvm::R600InstrInfo::isPredicable(), llvm::SystemZInstrInfo::isPredicable(), llvm::HexagonInstrInfo::isPredicable(), isPreISelGenericFloatingPointOpcode(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), isPromotableLoadFromStore(), isPromotableZeroStoreInst(), isPushPop(), isReadOrWriteToDSPReg(), llvm::WebAssemblyInstrInfo::isReallyTriviallyReMaterializable(), llvm::SIInstrInfo::isReallyTriviallyReMaterializable(), llvm::X86InstrInfo::isReallyTriviallyReMaterializable(), llvm::PPCInstrInfo::isReallyTriviallyReMaterializable(), isRedundantFlagInstr(), llvm::R600InstrInfo::isRegisterLoad(), llvm::R600InstrInfo::isRegisterStore(), isRegSequence(), llvm::VLIWResourceModel::isResourceAvailable(), IsSafeAndProfitableToMove(), isSafeToFoldImmIntoCopy(), isSafeToMove(), llvm::HexagonInstrInfo::isSaveCalleeSavedRegsCall(), isSchedBarrier(), llvm::AArch64InstrInfo::isSchedulingBoundary(), llvm::SIInstrInfo::isSchedulingBoundary(), isSecondInstructionInSequence(), llvm::AArch64InstrInfo::isSEHInstruction(), isSelectPseudo(), isSendMsgTraceDataOrGDS(), isSExtLoad(), llvm::HexagonInstrInfo::isSignExtendingLoad(), isSignExtendingOp(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isSimpleIf(), isSimpleIndexCalc(), llvm::HexagonPacketizerList::isSoloInstruction(), llvm::HexagonInstrInfo::isSpillPredRegOp(), isStackPtrRelative(), llvm::SystemZInstrInfo::isStackSlotCopy(), llvm::RISCVInstrInfo::isStoreToStackSlot(), llvm::MipsSEInstrInfo::isStoreToStackSlot(), llvm::LanaiInstrInfo::isStoreToStackSlot(), llvm::ARCInstrInfo::isStoreToStackSlot(), llvm::XCoreInstrInfo::isStoreToStackSlot(), llvm::AArch64InstrInfo::isStoreToStackSlot(), llvm::SparcInstrInfo::isStoreToStackSlot(), llvm::HexagonInstrInfo::isStoreToStackSlot(), llvm::AVRInstrInfo::isStoreToStackSlot(), llvm::ARMBaseInstrInfo::isStoreToStackSlot(), llvm::X86InstrInfo::isStoreToStackSlot(), llvm::PPCInstrInfo::isStoreToStackSlot(), llvm::X86InstrInfo::isStoreToStackSlotPostFE(), isSubregToReg(), isSuitableForMask(), isSystemInstr(), isTagStore(), llvm::HexagonInstrInfo::isToBeScheduledASAP(), isTransformable(), isTransient(), llvm::R600InstrInfo::isTransOnly(), llvm::TargetInstrInfo::isTriviallyReMaterializable(), isUncheckedLoadOrStoreOpcode(), IsUnconditionalJump(), llvm::X86InstrInfo::isUnconditionalTailCall(), llvm::AArch64InstrInfo::isUnscaledLdSt(), isUseDefConvertible(), isValidClauseInst(), llvm::isVCTP(), llvm::HexagonInstrInfo::isVecALU(), llvm::R600InstrInfo::isVector(), llvm::R600InstrInfo::isVectorOnly(), isVRegCompatibleReg(), llvm::HexagonInstrInfo::isZeroExtendingLoad(), isZeroExtendingOp(), isZExtLoad(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::AArch64LegalizerInfo::legalizeCustom(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::legalizeInstrStep(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::Legalizer::legalizeMachineFunction(), llvm::AMDGPULegalizerInfo::legalizeMinNumMaxNum(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::LegalizerHelper::libcall(), llvm::Localizer::Localizer(), llvm::XCoreMCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::MSP430MCInstLower::Lower(), llvm::ARCMCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::AArch64MCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::LegalizerHelper::lower(), llvm::LowerARMMachineInstrToMCInst(), llvm::LegalizerHelper::lowerBitCount(), llvm::LegalizerHelper::lowerFMinNumMaxNum(), LowerFPToInt(), llvm::AVRMCInstLower::lowerInstruction(), llvm::LegalizerHelper::lowerMinMax(), llvm::MipsMCInstLower::LowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerRISCVMachineInstrToMCInst(), llvm::LegalizerHelper::lowerSADDO_SSUBO(), llvm::AMDGPURegisterBankInfo::lowerScalarMinMax(), llvm::LowerSparcMachineInstrToMCInst(), llvm::LowerVEMachineInstrToMCInst(), makeImplicit(), MakeM0Inst(), llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >::match(), llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::match(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineCopy(), llvm::CombinerHelper::matchCombineExtendingLoads(), llvm::CombinerHelper::matchCombineIndexedLoadStore(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::CombinerHelper::matchElideBrByInvertingCond(), MatchingStackOffset(), llvm::CombinerHelper::matchPtrAddImmedChain(), matchSwap(), mayCombineMisaligned(), llvm::mayOptimizeThumb2Instruction(), llvm::SIInstrInfo::mayReadEXEC(), llvm::WebAssembly::mayThrow(), llvm::LegalizerHelper::moreElementsVector(), moveAndTeeForMultiUse(), llvm::SIInstrInfo::moveToVALU(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarMul(), llvm::LegalizerHelper::narrowScalarShift(), llvm::LegalizerHelper::narrowScalarShiftByConstant(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), needsStackFrame(), offsetMinAlign(), llvm::rdf::operator<<(), operator<<(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), optimizeVcndVcmpPair(), performCustomAdjustments(), llvm::HexagonInstrInfo::predCanBeUsedAsDotNew(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::ARMBaseInstrInfo::predictBranchSizeForIfCvt(), llvm::GCNHazardRecognizer::PreEmitNoopsCommon(), preservesValueOf(), llvm::MIPrinter::print(), print(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), printConstant(), llvm::MipsAsmPrinter::printMemOperand(), llvm::ARMBaseInstrInfo::produceSameValue(), profitImm(), query(), llvm::R600InstrInfo::readsLDSSrcReg(), readsVCCZ(), llvm::TargetInstrInfo::reassociateOps(), llvm::GISelCSEInfo::recordNewInstruction(), llvm::StackMaps::recordPatchPoint(), llvm::StackMaps::recordStackMap(), llvm::StackMaps::recordStatepoint(), llvm::LegalizerHelper::reduceLoadStoreWidth(), regIsPICBase(), llvm::R600SchedStrategy::releaseBottomNode(), llvm::X86InstrInfo::reMaterialize(), llvm::ARMBaseInstrInfo::reMaterialize(), RemoveDeadAddBetweenLEAAndJT(), removeModOperands(), removeRedundantBlockingStores(), removeTerminatorBit(), llvm::X86InstrInfo::replaceBranchWithTailCall(), ReplaceFrameIndex(), llvm::VLIWResourceModel::reserveResources(), llvm::HexagonInstrInfo::reversePredSense(), llvm::rewriteAArch64FrameIndex(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), rewriteP2Align(), llvm::rewriteT2FrameIndex(), llvm::InstructionSelect::runOnMachineFunction(), llvm::InsertNOPLoad::runOnMachineFunction(), llvm::DetectRoundChange::runOnMachineFunction(), llvm::FixAllFDIVSQRT::runOnMachineFunction(), llvm::AMDGPUInstructionSelector::select(), selectCopy(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::MipsRegisterBankInfo::setRegBank(), sForm(), llvm::AArch64InstrInfo::shouldClusterMemOps(), shouldPreventUndefRegUpdateMemFold(), shouldReadExec(), shouldUseAndMask(), shrinkScalarCompare(), shrinkScalarLogicOp(), simpleLibcall(), llvm::SIScheduleDAGMI::SIScheduleDAGMI(), sizeOfSPAdjustment(), llvm::SITargetLowering::splitKillBlock(), splitMBB(), supportLoadFromLiteral(), swapMIOperands(), tieOpsIfNeeded(), tryAddToFoldList(), tryChangeVGPRtoSGPRinCopy(), llvm::LegalizationArtifactCombiner::tryCombineAnyExt(), llvm::LegalizationArtifactCombiner::tryCombineExtract(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), llvm::CombinerHelper::tryCombineMemCpyFamily(), llvm::LegalizationArtifactCombiner::tryCombineMerges(), llvm::LegalizationArtifactCombiner::tryCombineSExt(), llvm::LegalizationArtifactCombiner::tryCombineTrunc(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), tryConstantFoldOp(), llvm::LegalizationArtifactCombiner::tryFoldImplicitDef(), tryFoldInst(), llvm::tryFoldSPUpdateIntoPushPop(), tryToFindRegisterToRename(), tryToFoldACImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), UpdateCPSRUse(), updateDefinedRegisters(), updateKillStatus(), updateOperand(), llvm::HexagonPacketizerList::useCalleesSP(), llvm::HexagonPacketizerList::useCallersSP(), usedAsAddr(), llvm::R600InstrInfo::usesTextureCache(), llvm::R600InstrInfo::usesVertexCache(), verifyCFIntrinsic(), llvm::RISCVInstrInfo::verifyInstruction(), llvm::MipsInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), VerifyLowRegs(), VisitGlobalVariableForEmission(), llvm::LegalizerHelper::widenScalar(), and X86SelectAddress().
getOperand() [1/2]
const MachineOperand& llvm::MachineInstr::getOperand (unsigned i) const inline
Definition at line 431 of file MachineInstr.h.
References assert(), and getNumOperands().
Referenced by llvm::AArch64CallLowering::AArch64CallLowering(), addExclusiveRegPair(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), addRegisterDead(), addRegisterKilled(), addRegsToSet(), addSegmentsWithValNo(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), adjustDefLatency(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::HexagonSubtarget::adjustSchedDependency(), allPhiOperandsUndefined(), llvm::analyzeArguments(), llvm::MipsInstrInfo::analyzeBranch(), llvm::LanaiInstrInfo::analyzeCompare(), llvm::AArch64InstrInfo::analyzeCompare(), llvm::SystemZInstrInfo::analyzeCompare(), llvm::HexagonInstrInfo::analyzeCompare(), llvm::ARMBaseInstrInfo::analyzeCompare(), llvm::PPCInstrInfo::analyzeCompare(), llvm::X86InstrInfo::analyzeCompare(), AnyAliasLiveIn(), llvm::LiveRangeEdit::anyRematerializable(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::CombinerHelper::applyCombineConcatVectors(), llvm::CombinerHelper::applyCombineCopy(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::CombinerHelper::applyCombineIndexedLoadStore(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::RegisterBankInfo::applyDefaultMapping(), llvm::CombinerHelper::applyElideBrByInvertingCond(), llvm::SwingSchedulerDAG::applyInstrChange(), llvm::AMDGPURegisterBankInfo::applyMappingImage(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingWideLoad(), llvm::CombinerHelper::applyPtrAddImmedChain(), areCombinableOperations(), llvm::HexagonInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), AssignProtectedObjSet(), attemptDebugCopyProp(), BBHasFallthrough(), BBIsJumpedOver(), llvm::BTFDebug::beginInstruction(), llvm::biasPhysReg(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::SIInstrInfo::buildExtractSubRegOrImm(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::SIInstrInfo::buildShrunkInst(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), calculateSetFPREG(), llvm::EHStreamer::callToNoUnwindFunction(), callWaitsOnFunctionReturn(), canBeExpandedToORR(), canCombine(), canCompareBeNewValueJump(), canDefBePartOfLOH(), llvm::HexagonInstrInfo::canExecuteInBundle(), canFoldCopy(), canFoldIntoCSel(), canFoldIntoSelect(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::HexagonPacketizerList::canPromoteToDotCur(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), canTurnIntoCOPY(), NoAutoPaddingScope::changeAndComment(), changeDebugValuesDefReg(), changeFCMPPredToAArch64CC(), checkRegOnlyPHIInputs(), CheckXWPInstr(), llvm::X86InstrInfo::classifyLEAReg(), llvm::HexagonPacketizerList::cleanUpDotCur(), clearKillFlags(), clobbersCTR(), llvm::WebAssemblyDebugValueManager::clone(), collectDebugValues(), llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), CombineCVTAToLocal(), llvm::WebAssemblyInstrInfo::commuteInstructionImpl(), llvm::ARMBaseInstrInfo::commuteInstructionImpl(), llvm::SIInstrInfo::commuteInstructionImpl(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), commuteVPTERNLOG(), CompareMBBNumbers(), llvm::HexagonEvaluator::composeWithSubRegIndex(), computeBranchTargetAndInversion(), computeExprForSpill(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), llvm::TargetSchedModel::computeOperandLatency(), llvm::TargetSchedModel::computeOutputLatency(), ConsecutiveInstr(), llvm::InstructionSelector::constrainOperandRegToRegClass(), llvm::AMDGPURegisterBankInfo::constrainOpWithReadfirstlane(), llvm::constrainSelectedInstRegOperands(), conversionLibcall(), ConvertDoubleToBytes(), convertImplicitDefToConstZero(), convertTailJumpOpcode(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), copyExtraImplicitOps(), copyHint(), copyImplicitOps(), llvm::R600InstrInfo::copyPhysReg(), llvm::createBreakFalseDeps(), llvm::createCopyConstrainDAGMutation(), llvm::LiveRangeCalc::createDeadDefs(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::CreateEmptyPHI(), llvm::createHexagonHardwareLoops(), llvm::createMemLibcall(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::createR600ExpandSpecialInstrsPass(), llvm::createSIWholeQuadModePass(), llvm::createX86FixupBWInsts(), llvm::createX86FixupSetCC(), llvm::createXCoreFrameToArgsOffsetEliminationPass(), CriticalPathStep(), definesFullReg(), llvm::ARMBaseInstrInfo::DefinesPredicate(), llvm::HexagonInstrInfo::DefinesPredicate(), llvm::PPCInstrInfo::DefinesPredicate(), llvm::AArch64InstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), llvm::CombinerHelper::dominates(), dominatesAllUsesOf(), dumpMachineInstrRangeWithSlotIndex(), llvm::SparcFrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::VEFrameLowering::eliminateCallFramePseudoInstr(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::VERegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBuildPairF64Pseudo(), llvm::AsmPrinter::emitCFIInstruction(), emitDebugValueComment(), emitDirectiveRelocJalr(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AVRFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), emitError(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AsmPrinter::emitFrameAlloc(), llvm::X86AsmPrinter::EmitFunctionBodyEnd(), EmitGCCInlineAsmStr(), EmitHiLo(), llvm::AsmPrinter::emitImplicitDef(), emitIncrement(), emitIndirectDst(), emitIndirectSrc(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMAsmPrinter::EmitJumpTableAddrs(), llvm::ARMAsmPrinter::EmitJumpTableInsts(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), emitKill(), emitLoadM0FromVGPRLoop(), EmitMSInlineAsmStr(), EmitNop(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostSt(), llvm::AVRFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), emitReadCycleWidePseudo(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSplitF64Pseudo(), llvm::X86FrameLowering::emitSPUpdate(), emitXBegin(), llvm::TargetLoweringBase::emitXRayCustomEvent(), llvm::TargetLoweringBase::emitXRayTypedEvent(), eraseDeadBBsAndChildren(), eraseGPOpnd(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::evaluate(), Expand2AddrUndef(), expandLoadStackGuard(), expandMOV32r1(), llvm::SIInstrInfo::expandMovDPP64(), ExpandMOVImmSExti8(), expandNOVLXLoad(), expandNOVLXStore(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::R600InstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SystemZInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), expandSHXDROT(), llvm::HexagonInstrInfo::expandVGatherPseudo(), llvm::PPCInstrInfo::expandVSXMemPseudo(), llvm::CallLowering::ValueHandler::extendRegister(), llvm::DbgVariableLocation::extractFromMachineInstruction(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorBuildVector(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorImplicitDef(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::LegalizerHelper::fewerElementsVectorSelect(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), llvm::MipsInstrInfo::findCommutedOpIndices(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::TargetInstrInfo::findCommutedOpIndices(), findCondCodeUsedByInstr(), findCorrespondingPred(), findDefIdx(), findIncDecAfter(), findInlineAsmFlagIdx(), findIntrinsicID(), findPotentialBlockers(), findRegisterDefOperand(), findRegisterDefOperandIdx(), findRegisterUseOperand(), findRegisterUseOperandIdx(), findSingleRegDef(), findSRegBaseAndIndex(), findStartOfTree(), findTiedOperandIdx(), findUncondBrI(), findUseIdx(), findVCMPToFoldIntoVPST(), llvm::fixStackStores(), fixupCalleeSaveRestoreStackOffset(), fixupGlobalSaddr(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), llvm::SwingSchedulerDAG::fixupRegisterOverlaps(), llvm::foldFrameOffset(), llvm::PPCInstrInfo::foldFrameOffset(), llvm::SystemZInstrInfo::FoldImmediate(), llvm::PPCInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), foldImmediates(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::SIInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), foldVGPRCopyIntoRegSequence(), followSubRegDef(), for(), FuseInst(), FuseTwoAddrInst(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), genFusedMultiply(), genMaddR(), genNeg(), getAbsSetOperand(), llvm::getAddressFromInstr(), getAdjustedCmp(), llvm::HexagonFrameLowering::getAlignaInstr(), llvm::Localizer::getAnalysisUsage(), llvm::RegBankSelect::getAnalysisUsage(), getAssignFnsForCC(), llvm::HexagonInstrInfo::getBaseAndOffset(), llvm::ARCInstrInfo::getBaseAndOffsetPosition(), llvm::HexagonInstrInfo::getBaseAndOffsetPosition(), getBaseOperand(), llvm::AMDGPU::getBaseWithConstantOffset(), llvm::RISCVInstrInfo::getBranchDestBlock(), llvm::AVRInstrInfo::getBranchDestBlock(), llvm::AArch64InstrInfo::getBranchDestBlock(), llvm::SIInstrInfo::getBranchDestBlock(), llvm::SystemZInstrInfo::getBranchInfo(), getBufferFormatWithCompCount(), getBufferStoreFormatOpcode(), llvm::HexagonInstrInfo::getBundleNoShuf(), llvm::ARMFrameLowering::getCalleeSaves(), getCallOpcode(), getCallTargetRegOpnd(), getCmpForPseudo(), getComparePred(), getCompareSourceReg(), llvm::HexagonInstrInfo::getCompoundCandidateGroup(), llvm::HexagonInstrInfo::getCompoundOpcode(), llvm::X86::getCondFromBranch(), llvm::X86::getCondFromCMov(), llvm::X86::getCondFromSETCC(), llvm::getConstantFPVRegVal(), llvm::getConstantVRegValWithLookThrough(), getCopyRegClasses(), getDebugExpression(), getDebugLabel(), getDebugLocValue(), getDebugVariable(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::AMDGPURegisterBankInfo::getDefaultMappingSOP(), llvm::AMDGPURegisterBankInfo::getDefaultMappingVOP(), llvm::getDefIgnoringCopies(), llvm::PPCInstrInfo::getDefMIPostRA(), getDispOperand(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), getDSShaderTypeValue(), GetDSubRegs(), llvm::HexagonInstrInfo::getDuplexCandidateGroup(), llvm::X86InstrInfo::getExecutionDomainCustom(), llvm::TargetInstrInfo::getExtractSubregInputs(), llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs(), llvm::R600InstrInfo::getFlagOp(), getFMAPatterns(), getFPReg(), llvm::X86InstrInfo::getFrameAdjustment(), llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), getFrameIndexOperandNum(), llvm::MSP430InstrInfo::getFramePoppedByCallee(), llvm::ARMBaseInstrInfo::getFramePred(), llvm::TargetInstrInfo::getFrameSize(), llvm::TargetInstrInfo::getFrameTotalSize(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), llvm::SystemZInstrInfo::getFusedCompare(), llvm::HexagonHazardRecognizer::getHazardType(), llvm::StackMapOpers::getID(), llvm::AMDGPURegisterBankInfo::getImageMapping(), GetImm(), getImmedFromMO(), getImmOrMaterializedImm(), getINCDECFromLEA(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::getIncomingBlock(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::getIncomingValue(), llvm::HexagonInstrInfo::getIncrementValue(), getInitPhiReg(), getInlineAsmDialect(), llvm::TargetInstrInfo::getInsertSubregInputs(), llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs(), getInsertVecEltOpInfo(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::PPCInstrInfo::getInstrLatency(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::getInstrPredicate(), getInstrVecReg(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::ARCInstrInfo::getInstSizeInBytes(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getInstSizeInBytes(), llvm::AVRInstrInfo::getInstSizeInBytes(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::PPCInstrInfo::getInstSizeInBytes(), llvm::SIInstrInfo::getInstSizeInBytes(), getIntrinsicID(), llvm::GISelKnownBits::getKnownBits(), getLaneCopyOpcode(), getLdStBaseOp(), getLdStOffsetOp(), getLdStRegOp(), getLeaOP(), getLoadInfo(), getLoadStoreBaseOp(), getLoadStoreOffsetAlign(), getLoadStoreRegOp(), getLogicalBitOpcode(), getLoopPhiReg(), getMaddPatterns(), getMappedOp(), llvm::AArch64InstrInfo::getMemOpBaseRegImmOfsOffsetOperand(), llvm::X86InstrInfo::getMemOperandWithOffset(), llvm::LanaiInstrInfo::getMemOperandWithOffsetWidth(), llvm::RISCVInstrInfo::getMemOperandWithOffsetWidth(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), llvm::PPCInstrInfo::getMemOperandWithOffsetWidth(), getMemOpKey(), getMemoryOpOffset(), getMemsetValue(), llvm::SIRegisterInfo::getMUBUFInstrOffset(), llvm::SIInstrInfo::getNamedImmOperand(), llvm::SIInstrInfo::getNamedOperand(), getNewSource(), getNewValueJumpOpcode(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::PatchPointOpers::getNumCallArgs(), getNumExplicitDefs(), getNumExplicitOperands(), getNumMicroOpsSwiftLdSt(), llvm::StackMapOpers::getNumPatchBytes(), llvm::SIInstrInfo::getNumWaitStates(), getOffsetFromIndices(), getOModValue(), llvm::PPCInstrInfo::getOperandLatency(), llvm::HexagonInstrInfo::getOperandLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::getOperandNo(), llvm::SIInstrInfo::getOpRegClass(), llvm::SIInstrInfo::getOpSize(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::X86InstrInfo::getPartialRegUpdateClearance(), getPHIDeps(), getPHIDestReg(), getPHIPred(), getPhiRegs(), getPHISourceReg(), getPHISrcRegOpIdx(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::GetPHIValue(), getPostIncrementOperand(), getPostIndexedLoadStoreOpcode(), llvm::ARMBaseInstrInfo::getPredicate(), getReassignedChan(), llvm::MachineInstrBuilder::getReg(), llvm::RegisterBankInfo::getRegBankFromConstraints(), getRegClassConstraint(), getRegClassConstraintEffect(), getRegClassConstraintEffectForVReg(), getRegClassesForCopy(), getRegClassForUnfoldedLoad(), getRegClassFromGRPhysReg(), getRegSeqInit(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::getRegSequenceSubReg(), getRegsUsedByPHIs(), getRegUnits(), getRetpolineSymbol(), getShiftTypeForInst(), getShuffleComment(), getSingleDef(), llvm::HexagonInstrInfo::getSize(), llvm::X86InstrInfo::getSPAdjust(), getSrcFromCopy(), llvm::R600InstrInfo::getSrcs(), getStartOrEndSlot(), getStoreOffset(), getStoreTarget(), getStoreValueOperand(), getSubOpcode(), getTag(), getTargetMBB(), getTruncatedShiftCount(), getTypeFromTypeIdx(), getTypeToPrint(), getUnconditionalBrDisp(), llvm::X86InstrInfo::getUndefRegClearance(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::GetUndefVal(), getUnderlyingObjects(), getV_CMPOpcode(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::SIInstrInfo::getVALUOp(), getVariantKind(), getVectorSHLImm(), llvm::getVPTInstrPredicate(), llvm::getVRegSubRegDef(), getWinAllocaAmount(), llvm::MipsTargetLowering::HandleByVal(), handleMiddleInst(), handleUse(), llvm::LiveVariables::HandleVirtRegDef(), HandleVRSaveUpdate(), hasComplexRegisterTies(), HashMachineInstr(), hasImplicitDef(), llvm::X86InstrInfo::hasLiveCondCodeDef(), hasOneNonDBGUseInst(), hasRAWHazard(), llvm::TargetInstrInfo::hasReassociableOperands(), llvm::TargetInstrInfo::hasReassociableSibling(), hasRegisterDependency(), hasRegisterImplicitUseOperand(), hasUnmodeledSideEffects(), hasUseAfterLoop(), hasVectorOperands(), hasVulnerableLoad(), llvm::HexagonLowerToMC(), hoistAndMergeSGPRInits(), llvm::HexagonInstrInfo::immediateExtend(), llvm::GISelKnownBits::inferPtrAlignment(), INITIALIZE_PASS(), llvm::SIInstrInfo::insertBranch(), insertCopy(), insertCSRRestores(), insertDivByZeroTrap(), InsertFPConstInst(), InsertFPImmInst(), InsertLDR_STR(), insertPHI(), llvm::SIInstrInfo::insertSelect(), InsertSPConstInst(), InsertSPImmInst(), llvm::BTFDebug::InstLower(), llvm::rdf::CopyPropagation::interpretAsCopy(), llvm::Mips16RegisterInfo::intRegClass(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), llvm::isAArch64FrameOffsetLegal(), isAddConstantOp(), llvm::PPCInstrInfo::isADDIInstrEligibleForFolding(), llvm::AArch64InstrInfo::isAddImmediate(), llvm::ARMBaseInstrInfo::isAddImmediate(), llvm::ARMBaseInstrInfo::isAddrMode3OpImm(), llvm::ARMBaseInstrInfo::isAddrMode3OpMinusReg(), isAddWithImmediate(), llvm::ARMBaseInstrInfo::isAm2ScaledReg(), isAmbiguous(), llvm::AArch64InstrInfo::isAsCheapAsAMove(), llvm::RISCVInstrInfo::isAsCheapAsAMove(), isBackwardPropagatableCopy(), llvm::InstructionSelector::isBaseWithConstantOffset(), llvm::PPCInstrInfo::isBDNZ(), isCallerPreservedOrConstPhysReg(), isCandidateLoad(), isCandidateStore(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), llvm::WebAssembly::isChild(), llvm::rdf::TargetOperandInfo::isClobbering(), llvm::CoalescerPair::isCoalescable(), isCoalescable(), llvm::AArch64InstrInfo::isCoalescableExtInstr(), llvm::X86InstrInfo::isCoalescableExtInstr(), llvm::PPCInstrInfo::isCoalescableExtInstr(), isCompareZero(), isConstant(), isConstantValuePHI(), llvm::HexagonInstrInfo::isConstExtended(), isConvergent(), isCopy(), isCopyFeedingInvariantStore(), llvm::TargetInstrInfo::isCopyInstr(), llvm::MipsSEInstrInfo::isCopyInstrImpl(), llvm::ARMBaseInstrInfo::isCopyInstrImpl(), llvm::Mips16InstrInfo::isCopyInstrImpl(), llvm::AArch64InstrInfo::isCopyInstrImpl(), llvm::X86InstrInfo::isCopyInstrImpl(), isCopyToExec(), isCopyToReg(), isCrossCopy(), isCSRestore(), isCVTAToLocalCombinationCandidate(), isDbgValueDescribedByReg(), isDebug(), isDefInSubRange(), isDescribedByReg(), isEFLAGSLive(), llvm::AArch64InstrInfo::isFalkorShiftExtFast(), llvm::rdf::TargetOperandInfo::isFixedReg(), isFpMulInstruction(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::PPCRegisterInfo::isFrameOffsetLegal(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), isFullCopy(), isFullCopyOf(), isFullExecCopy(), isFullUndefDef(), llvm::AArch64InstrInfo::isGPRCopy(), llvm::AArch64InstrInfo::isGPRZero(), isGreaterThanNBitTFRI(), isIdenticalTo(), isIdentityCopy(), isIdentityValue(), llvm::PPCInstrInfo::isImmInstrEligibleForFolding(), isImmValidForOpcode(), isImplicitlyDef(), isIncrementOrDecrement(), isIndirectDebugValue(), llvm::SIInstrInfo::isInlineConstant(), isIntersect(), llvm::ARMBaseInstrInfo::isLDMBaseRegInList(), llvm::ARMBaseInstrInfo::isLdstScaledReg(), llvm::ARMBaseInstrInfo::isLdstScaledRegNotPlusLsl2(), llvm::ARMBaseInstrInfo::isLdstSoMinusReg(), isLEA(), llvm::isLeaMem(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::SIInstrInfo::isLiteralConstant(), isLiveOut(), isLoadAndTestAsCmp(), llvm::RISCVInstrInfo::isLoadFromStackSlot(), llvm::MipsSEInstrInfo::isLoadFromStackSlot(), llvm::ARCInstrInfo::isLoadFromStackSlot(), llvm::LanaiInstrInfo::isLoadFromStackSlot(), llvm::XCoreInstrInfo::isLoadFromStackSlot(), llvm::SparcInstrInfo::isLoadFromStackSlot(), llvm::HexagonInstrInfo::isLoadFromStackSlot(), llvm::AArch64InstrInfo::isLoadFromStackSlot(), llvm::AVRInstrInfo::isLoadFromStackSlot(), llvm::ARMBaseInstrInfo::isLoadFromStackSlot(), llvm::X86InstrInfo::isLoadFromStackSlot(), isLoadStoreThatCanHandleDisplacement(), isLocalCopy(), isLogicalOpOnExec(), llvm::SMSchedule::isLoopCarriedDefOfUse(), llvm::isMem(), isMemoryOp(), IsMovepDestinationRegPair(), isNonFoldablePartialRegisterLoad(), isNopCopy(), llvm::SIInstrInfo::isOperandLegal(), isOperandSubregIdx(), isORCopyInst(), isPhysicalRegCopy(), llvm::R600InstrInfo::isPredicable(), llvm::ARMBaseInstrInfo::isPredicated(), llvm::R600InstrInfo::isPredicated(), isPreISelGenericFloatingPointOpcode(), llvm::X86InstrInfo::isReallyTriviallyReMaterializable(), isRedundantFlagInstr(), isRegOtherThanSPAndFP(), isRegTiedToDefOperand(), isRegTiedToUseOperand(), isRelevantAddressingMode(), isRematerializable(), IsSafeAndProfitableToMove(), isSafeToFoldImmIntoCopy(), llvm::AMDGPURegisterBankInfo::isSALUMapping(), llvm::AArch64InstrInfo::isSchedulingBoundary(), isSecondInstructionInSequence(), isSendMsgTraceDataOrGDS(), isSExtLoad(), isSignExtendingOp(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isSimpleBD12Move(), isSimpleIf(), isSimpleIndexCalc(), isSimpleMove(), isStackAligningInlineAsm(), isStackPtrRelative(), llvm::SystemZInstrInfo::isStackSlotCopy(), llvm::RISCVInstrInfo::isStoreToStackSlot(), llvm::MipsSEInstrInfo::isStoreToStackSlot(), llvm::LanaiInstrInfo::isStoreToStackSlot(), llvm::ARCInstrInfo::isStoreToStackSlot(), llvm::XCoreInstrInfo::isStoreToStackSlot(), llvm::AArch64InstrInfo::isStoreToStackSlot(), llvm::SparcInstrInfo::isStoreToStackSlot(), llvm::HexagonInstrInfo::isStoreToStackSlot(), llvm::AVRInstrInfo::isStoreToStackSlot(), llvm::ARMBaseInstrInfo::isStoreToStackSlot(), llvm::X86InstrInfo::isStoreToStackSlot(), isSuitableForMask(), llvm::ARMBaseInstrInfo::isSwiftFastImmShift(), llvm::HexagonInstrInfo::isToBeScheduledASAP(), llvm::PPCInstrInfo::isTOCSaveMI(), isTransformable(), isTwoAddrUse(), isUncheckedLoadOrStoreOpcode(), IsUnconditionalJump(), isUndefDebugValue(), isValidCopy(), llvm::PPCInstrInfo::isValidToBeChangedReg(), llvm::SIInstrInfo::isVGPRCopy(), isVirtualRegisterOperand(), isVRegCompatibleReg(), isZeroExtendingOp(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFceil(), llvm::AMDGPULegalizerInfo::legalizeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV16(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFDIVFastIntrin(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::MipsLegalizerInfo::legalizeIntrinsic(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeIsAddrSpace(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeLoad(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::AMDGPULegalizerInfo::legalizePreloadedArgIntrin(), llvm::AMDGPULegalizerInfo::legalizeRawBufferStore(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::LegalizerHelper::libcall(), loadM0FromVGPR(), llvm::Localizer::Localizer(), llvm::TargetRegisterInfo::lookThruCopyLike(), lookupCandidateBaseReg(), llvm::XCoreMCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::ARCMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerBitCount(), llvm::LegalizerHelper::lowerBitreverse(), llvm::LegalizerHelper::lowerBswap(), llvm::X86CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::LegalizerHelper::lowerDynStackAlloc(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerFCopySign(), llvm::LegalizerHelper::lowerFMad(), llvm::LegalizerHelper::lowerFMinNumMaxNum(), LowerFPToInt(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::LegalizerHelper::lowerInsert(), llvm::LegalizerHelper::lowerIntrinsicRound(), llvm::LegalizerHelper::lowerMinMax(), llvm::MipsMCInstLower::LowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LegalizerHelper::lowerReadRegister(), lowerRIEfLow(), lowerRIHigh(), lowerRILow(), llvm::LegalizerHelper::lowerSADDO_SSUBO(), llvm::AMDGPURegisterBankInfo::lowerScalarMinMax(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::LegalizerHelper::lowerSITOFP(), llvm::LowerSparcMachineInstrToMCInst(), lowerSubvectorLoad(), lowerSubvectorStore(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::LegalizerHelper::lowerUITOFP(), llvm::LegalizerHelper::lowerUnmergeValues(), llvm::LowerVEMachineInstrToMCInst(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), makeImplicit(), MakeM0Inst(), llvm::MachineRegisterInfo::markUsesInDebugValueAsUndef(), llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >::match(), llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::match(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineCopy(), llvm::CombinerHelper::matchCombineExtendingLoads(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::CombinerHelper::matchElideBrByInvertingCond(), MatchingStackOffset(), llvm::CombinerHelper::matchPtrAddImmedChain(), matchSwap(), mayLoad(), llvm::SIInstrInfo::mayReadEXEC(), mayStore(), llvm::WebAssembly::mayThrow(), Mips16WhichOp8uOr16simm(), llvm::LegalizerHelper::moreElementsVector(), llvm::LegalizerHelper::moreElementsVectorPhi(), moveAndTeeForMultiUse(), moveForSingleUse(), llvm::SIInstrInfo::moveToVALU(), MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarMul(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::LegalizerHelper::narrowScalarShift(), llvm::LegalizerHelper::narrowScalarShiftByConstant(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::AggressiveAntiDepBreaker::Observe(), oneUseDominatesOtherUses(), false::IntervalSorter::operator()(), operator<<(), optimizeCall(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::X86InstrInfo::optimizeLoadInstr(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::SMSchedule::orderDependence(), parseOperands(), llvm::PatchPointOpers::PatchPointOpers(), llvm::PeelSingleBlockLoop(), performCustomAdjustments(), performSink(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::TargetInstrInfo::PredicateInstruction(), preservesValueOf(), llvm::MIPrinter::print(), print(), llvm::SystemZAsmPrinter::PrintAsmMemoryOperand(), llvm::AVRAsmPrinter::PrintAsmMemoryOperand(), llvm::HexagonAsmPrinter::PrintAsmMemoryOperand(), llvm::ARMAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::AVRAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::X86AsmPrinter::PrintAsmOperand(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), llvm::AsmPrinter::PrintAsmOperand(), printConstant(), llvm::MipsAsmPrinter::printFCCOperand(), llvm::AVRAsmPrinter::printOperand(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), llvm::ARMBaseInstrInfo::produceSameValue(), profitImm(), pushDepHeight(), query(), queryCallee(), readsVCCZ(), readsWritesVirtualRegister(), llvm::TargetInstrInfo::reassociateOps(), llvm::MachineRegisterInfo::recomputeRegClass(), llvm::StackMaps::recordStackMap(), llvm::LegalizerHelper::reduceLoadStoreWidth(), regOverlapsSet(), llvm::R600SchedStrategy::releaseBottomNode(), llvm::X86InstrInfo::reMaterialize(), llvm::ARMBaseInstrInfo::reMaterialize(), llvm::TargetInstrInfo::reMaterialize(), removeCopies(), RemoveDeadAddBetweenLEAAndJT(), removeKillInfo(), llvm::LiveVariables::removeVirtualRegisterDead(), llvm::LiveVariables::removeVirtualRegisterKilled(), llvm::LiveVariables::removeVirtualRegistersKilled(), llvm::RegBankSelect::RepairingPlacement::RepairingPlacement(), llvm::X86InstrInfo::replaceBranchWithTailCall(), replaceDominatedUses(), replaceFI(), ReplaceFrameIndex(), llvm::PPCInstrInfo::replaceInstrOperandWithImm(), llvm::MachineBasicBlock::replacePhiUsesWith(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), resultTests(), llvm::rewriteAArch64FrameIndex(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), rewriteP2Align(), llvm::rewriteT2FrameIndex(), llvm::InstructionSelect::runOnMachineFunction(), llvm::DetectRoundChange::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::AMDGPUInstructionSelector::select(), selectCopy(), selectFCMPOpc(), selectMergeValues(), SelectMSA3OpIntrinsic(), selectSelectOpc(), llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic(), selectSubregisterCopy(), selectUnmergeValues(), llvm::setDirectAddressInInstr(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::X86InstrInfo::setFrameAdjustment(), llvm::R600InstrInfo::setImmOperand(), setM0ToIndexFromSGPR(), setPhiPred(), llvm::MipsRegisterBankInfo::setRegBank(), llvm::AMDGPUInstructionSelector::setupMF(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::HexagonRegisterInfo::shouldCoalesce(), llvm::SystemZRegisterInfo::shouldCoalesce(), shouldPreventUndefRegUpdateMemFold(), shouldUseAndMask(), shrinkScalarCompare(), shrinkScalarLogicOp(), simpleLibcall(), sizeToSubRegIndex(), smallData(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), splitBlock(), splitEdge(), splitMBB(), false::Chain::str(), swapMIOperands(), llvm::SystemZInstrInfo::SystemZInstrInfo(), llvm::TailDuplicator::tailDuplicateAndUpdate(), tieOperands(), tieOpsIfNeeded(), tryAddToFoldList(), tryChangeVGPRtoSGPRinCopy(), llvm::LegalizationArtifactCombiner::tryCombineAnyExt(), llvm::LegalizationArtifactCombiner::tryCombineExtract(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), llvm::CombinerHelper::tryCombineMemCpyFamily(), llvm::LegalizationArtifactCombiner::tryCombineMerges(), llvm::LegalizationArtifactCombiner::tryCombineSExt(), llvm::LegalizationArtifactCombiner::tryCombineTrunc(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), tryConstantFoldOp(), llvm::LegalizationArtifactCombiner::tryFoldImplicitDef(), tryFoldInst(), llvm::tryFoldSPUpdateIntoPushPop(), tryOptimizeLEAtoMOV(), tryToFindRegisterToRename(), tryToFoldACImm(), llvm::HexagonPacketizerList::undoChangedOffset(), llvm::X86InstrInfo::unfoldMemoryOperand(), unstackifyVRegsUsedInSplitBB(), unsupportedBinOp(), untieRegOperand(), llvm::AntiDepBreaker::UpdateDbgValue(), llvm::updateDbgValueForSpill(), updateDefinedRegisters(), updateLiveIn(), llvm::HexagonPacketizerList::updateOffset(), updateOperand(), UpdateOperandRegClass(), updateOperandRegConstraints(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), llvm::HexagonPacketizerList::useCalleesSP(), llvm::HexagonPacketizerList::useCallersSP(), usedAsAddr(), llvm::HexagonSubtarget::usePredicatedCalls(), UseReg(), validThroughout(), llvm::RegisterBankInfo::InstructionMapping::verify(), llvm::MachineFunction::verify(), verifyCFIntrinsic(), verifyInsExtInstruction(), llvm::RISCVInstrInfo::verifyInstruction(), llvm::SystemZInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), VerifyLowRegs(), llvm::MachineRegisterInfo::verifyUseList(), VisitGlobalVariableForEmission(), llvm::LegalizerHelper::widenScalar(), llvm::X86CallLowering::X86CallLowering(), and X86SelectAddress().
getOperand() [2/2]
MachineOperand& llvm::MachineInstr::getOperand (unsigned i) inline
Definition at line 435 of file MachineInstr.h.
References assert(), and getNumOperands().
getOperandNo()
unsigned llvm::MachineInstr::getOperandNo (const_mop_iterator I) const inline
Returns the number of the operand iterator I points to.
Definition at line 542 of file MachineInstr.h.
References operands_begin().
Referenced by addRegsToSet(), llvm::ScheduleDAGInstrs::addSchedBarrierDeps(), dominatesAllUsesOf(), findStartOfTree(), llvm::Localizer::getAnalysisUsage(), getDataDeps(), hoistAndMergeSGPRInits(), isCandidateStore(), isCrossCopy(), llvm::SIInstrInfo::isInlineConstant(), isKImmOperand(), isKUImmOperand(), operator<<(), tryChangeVGPRtoSGPRinCopy(), tryFoldInst(), tryToFoldACImm(), updateOperand(), updatePhysDepsDownwards(), and updatePhysDepsUpwards().
getParent() [1/2]
const MachineBasicBlock* llvm::MachineInstr::getParent () const inline
Definition at line 271 of file MachineInstr.h.
Referenced by addExclusiveRegPair(), llvm::addFrameReference(), addImplicitDefUseOperands(), addLiveInRegs(), llvm::GISelInstProfileBuilder::addNodeID(), addOperand(), addRegsToSet(), addSegmentsWithValNo(), llvm::LiveIntervals::addSegmentToEndOfBlock(), llvm::HexagonPacketizerList::addToPacket(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::GCNSubtarget::adjustSchedDependency(), BlockSplitInfo::allInstrsInSameMBB(), llvm::RegAllocBase::allocatePhysRegs(), llvm::CombinerHelper::applyCombineConcatVectors(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingWideLoad(), BBHasFallthrough(), llvm::CodeViewDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), branchMaxOffsets(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::X86InstrInfo::breakPartialRegDependency(), buildEXP(), llvm::SIInstrInfo::buildShrunkInst(), llvm::SITargetLowering::bundleInstWithWaitcnt(), callWaitsOnFunctionReturn(), canCombine(), canInstrSubstituteCmpInstr(), llvm::X86InstrInfo::canMakeTailCallConditional(), cannotCoexistAsymm(), canRenameUpToDef(), canTurnIntoCOPY(), changeFCMPPredToAArch64CC(), checkEFLAGSLive(), llvm::X86InstrInfo::classifyLEAReg(), llvm::WebAssemblyDebugValueManager::clone(), collectCallSiteParameters(), collectDebugValues(), CombineCVTAToLocal(), llvm::WebAssemblyInstrInfo::commuteInstructionImpl(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::SystemZInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), CompareMBBNumbers(), computeBranchTargetAndInversion(), llvm::const_mi_bundle_ops(), llvm::constrainOperandRegClass(), llvm::InstructionSelector::constrainOperandRegToRegClass(), llvm::constrainSelectedInstRegOperands(), ContainsReg(), convertImplicitDefToConstZero(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), createBBSelectReg(), llvm::createGCNDPPCombinePass(), llvm::createSIWholeQuadModePass(), llvm::createX86FixupSetCC(), CriticalPathStep(), definesFullReg(), doesModifyCalleeSavedReg(), llvm::CombinerHelper::dominates(), llvm::MachineDominatorTree::dominates(), dominatesAllUsesOf(), dumpMachineInstrRangeWithSlotIndex(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::VERegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::AsmPrinter::emitCFIInstruction(), emitError(), EmitHiLo(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), EmitNop(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::DebugHandlerBase::endInstruction(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvBefore(), eraseFromBundle(), eraseFromParent(), eraseFromParentAndMarkDBGValuesForRemoval(), eraseGPOpnd(), llvm::BitTracker::MachineEvaluator::evaluate(), llvm::execMayBeModifiedBeforeAnyUse(), llvm::execMayBeModifiedBeforeUse(), llvm::VEInstrInfo::expandExtendStackPseudo(), expandLoadStackGuard(), expandMOV32r1(), llvm::SIInstrInfo::expandMovDPP64(), ExpandMOVImmSExti8(), llvm::MipsSEInstrInfo::expandPostRAPseudo(), llvm::Mips16InstrInfo::expandPostRAPseudo(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::R600InstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandVGatherPseudo(), expandXorFP(), extractRsrcPtr(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::findCMPToFoldIntoCBZ(), findIncDecAfter(), findOnlyInterestingUse(), findPotentialBlockers(), findSingleRegDef(), findSingleRegUse(), llvm::SIInstrInfo::fixImplicitOperands(), fixupCalleeSaveRestoreStackOffset(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), llvm::PPCInstrInfo::foldFrameOffset(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), foldVGPRCopyIntoRegSequence(), for(), forAllMIsUntilDef(), forceReg(), llvm::RegBankSelect::InstrInsertPoint::frequency(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), getAdjustedCmp(), llvm::Localizer::getAnalysisUsage(), llvm::RegBankSelect::getAnalysisUsage(), getBufferFormatWithCompCount(), getBundledUseMI(), getCmpForPseudo(), getCompareSourceReg(), getConstantFromPool(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::AMDGPURegisterBankInfo::getDefaultMappingSOP(), llvm::AMDGPURegisterBankInfo::getDefaultMappingVOP(), llvm::PPCInstrInfo::getDefMIPostRA(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), getDSShaderTypeValue(), GetDSubRegs(), getFMAPatterns(), getFoldableImm(), llvm::ARMHazardRecognizer::getHazardType(), llvm::HexagonHazardRecognizer::getHazardType(), getImmedFromMO(), getImplicitSPRUseForDPRUse(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), getInsertVecEltOpInfo(), llvm::SIInstrInfo::getInstBundleSize(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::SIInstrInfo::getInstrLatency(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), llvm::MachineTraceMetrics::Trace::getInstrSlack(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::ARCInstrInfo::getInstSizeInBytes(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getInstSizeInBytes(), llvm::AVRInstrInfo::getInstSizeInBytes(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::PPCInstrInfo::getInstSizeInBytes(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::ReachingDefAnalysis::getInstWithUseBefore(), getLaneCopyOpcode(), llvm::getLiveRegsAfter(), getLiveRegsAt(), llvm::getLiveRegsBefore(), getLoadStoreOffsetAlign(), getLoadStoreOffsetSizeInBits(), getLogicalBitOpcode(), llvm::PPCInstrInfo::getMachineCombinerPatterns(), getMaddPatterns(), getMappedOp(), getMatchingEHPad(), llvm::SIInstrInfo::getMemOperandWithOffset(), getMemsetValue(), getMF(), getMFIfAvailable(), getNewSource(), getNewValueJumpOpcode(), llvm::ARMBasicBlockUtils::getOffsetOf(), llvm::PPCInstrInfo::getOperandLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::SIInstrInfo::getOpRegClass(), llvm::SIInstrInfo::getOpSize(), llvm::RISCVInstrInfo::getOutliningType(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), getPostIndexedLoadStoreOpcode(), llvm::ReachingDefAnalysis::getReachingDef(), llvm::ReachingDefAnalysis::getReachingLocalUses(), llvm::ReachingDefAnalysis::getReachingMIDef(), getRegClassConstraint(), getRegClassFromGRPhysReg(), getShiftTypeForInst(), getSingleDef(), llvm::HexagonInstrInfo::getSize(), llvm::X86InstrInfo::getSPAdjust(), llvm::LiveIntervals::getSpillWeight(), getSubOpcode(), GetSymbolRef(), llvm::BPFTargetLowering::getTargetNodeName(), getUnconditionalBrDisp(), getUnderlyingObjects(), getV_CMPOpcode(), llvm::SIInstrInfo::getVALUOp(), getVariantKind(), getVectorSHLImm(), getWaitStatesSince(), llvm::LiveIntervals::handleMove(), llvm::LiveVariables::HandleVirtRegDef(), HandleVRSaveUpdate(), llvm::HexagonInstrInfo::hasLoadFromStackSlot(), llvm::TargetInstrInfo::hasReassociableOperands(), llvm::TargetInstrInfo::hasReassociableSibling(), llvm::ReachingDefAnalysis::hasSameReachingDef(), llvm::HexagonInstrInfo::hasStoreToStackSlot(), hasUseAfterLoop(), hasVectorOperands(), llvm::SIInstrInfo::hasVGPRUses(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), insertCopy(), InsertFPConstInst(), InsertFPImmInst(), llvm::SlotIndexes::insertMachineInstrInMaps(), insertNoopInBundle(), insertNopBeforeInstruction(), insertPHI(), InsertSPConstInst(), InsertSPImmInst(), InstructionStoresToFI(), llvm::Mips16RegisterInfo::intRegClass(), isAddWithImmediate(), isAmbiguous(), llvm::AArch64InstrInfo::isAssociativeAndCommutative(), llvm::X86InstrInfo::isAssociativeAndCommutative(), llvm::ARMBasicBlockUtils::isBBInRange(), llvm::PPCInstrInfo::isBDNZ(), isCallerPreservedOrConstPhysReg(), llvm::CoalescerPair::isCoalescable(), isCombineInstrCandidateFP(), isCompareZero(), isConstant(), isCopy(), isCopyFeedingInvariantStore(), isCVTAToLocalCombinationCandidate(), llvm::MachineTraceMetrics::Trace::isDepInTrace(), isDereferenceableInvariantLoad(), isEFLAGSLive(), isFpMulInstruction(), isFullCopyOf(), isFullUndefDef(), isIdentityValue(), llvm::SIInstrInfo::isImmOperandLegal(), isIntersect(), llvm::SIInstrInfo::isLegalRegOperand(), isLibCallInTailPosition(), llvm::LiveVariables::VarInfo::isLiveIn(), isLoadStoreThatCanHandleDisplacement(), llvm::SMSchedule::isLoopCarried(), llvm::SMSchedule::isLoopCarriedDefOfUse(), IsMovepDestinationRegPair(), isNoReturnDef(), llvm::InstructionSelector::isObviouslySafeToFold(), llvm::SIInstrInfo::isOperandLegal(), isPHIRegionIndex(), llvm::CombinerHelper::isPredecessor(), llvm::ARMBaseInstrInfo::isPredicable(), llvm::R600InstrInfo::isPredicable(), llvm::ARMBaseInstrInfo::isPredicated(), isPreISelGenericFloatingPointOpcode(), isReachable(), llvm::ReachingDefAnalysis::isReachingDefLiveOut(), llvm::X86InstrInfo::isReallyTriviallyReMaterializable(), llvm::TargetInstrInfo::isReassociationCandidate(), isRegOtherThanSPAndFP(), llvm::ReachingDefAnalysis::isRegUsedAfter(), llvm::VLIWResourceModel::isResourceAvailable(), isSafeToMove(), llvm::AMDGPURegisterBankInfo::isSALUMapping(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isSimpleIf(), isSimpleIndexCalc(), isStackPtrRelative(), llvm::SystemZInstrInfo::isStackSlotCopy(), isTerminalReg(), IsUnconditionalJump(), llvm::SIInstrInfo::isVGPRCopy(), jumpTableFollowsTB(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvBefore(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::SIInstrInfo::legalizeOpWithMove(), loadSRsrcFromVGPR(), llvm::WebAssemblyMCInstLower::lower(), llvm::LowerARMMachineInstrToMCInst(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::CombinerHelper::matchElideBrByInvertingCond(), matchSwap(), memOpsHaveSameBasePtr(), llvm::mi_bundle_ops(), llvm::MIBundleOperandIteratorBase< const MachineOperand >::MIBundleOperandIteratorBase(), llvm::LegalizerHelper::moreElementsVectorPhi(), llvm::WebAssemblyDebugValueManager::move(), moveAndTeeForMultiUse(), moveInstrOut(), llvm::SIInstrInfo::moveToVALU(), llvm::LegalizerHelper::narrowScalar(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), oneUseDominatesOtherUses(), operator<<(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), packCmovGroup(), performSink(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::RegisterBankInfo::OperandsMapper::print(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::printMBBReference(), llvm::ARMAsmPrinter::printOperand(), llvm::ARMBaseInstrInfo::produceSameValue(), llvm::HexagonPacketizerList::producesStall(), profitImm(), llvm::rdf::DataFlowGraph::pushAllDefs(), pushDepHeight(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), RemoveDeadAddBetweenLEAAndJT(), removeFromBundle(), removeFromParent(), RemoveVRSaveCode(), llvm::RegBankSelect::RepairingPlacement::RepairingPlacement(), replaceFI(), ReplaceFrameIndex(), llvm::PPCInstrInfo::replaceInstrWithLI(), replaceRegUsesAfterLoop(), llvm::reportGISelFailure(), rescheduleCanonically(), llvm::SystemZHazardRecognizer::Reset(), llvm::GCNDownwardRPTracker::reset(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::SIRegisterInfo::resolveFrameIndex(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::rewriteAArch64FrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), llvm::MachineSSAUpdater::RewriteUse(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ScheduleDAGMILive::scheduleMI(), llvm::AMDGPUInstructionSelector::select(), selectCopy(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::MachineIRBuilder::setInstr(), setM0ToIndexFromSGPR(), llvm::AMDGPUInstructionSelector::setupMF(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::SIInstrInfo::shouldClusterMemOps(), llvm::HexagonRegisterInfo::shouldCoalesce(), llvm::SystemZRegisterInfo::shouldCoalesce(), llvm::ARMBaseRegisterInfo::shouldCoalesce(), llvm::ARMBaseInstrInfo::shouldSink(), shouldUseAndMask(), shrinkScalarCompare(), SinkingPreventsImplicitNullCheck(), splitBlock(), splitMBB(), swapMIOperands(), llvm::SystemZInstrInfo::SystemZInstrInfo(), llvm::TailDuplicator::tailDuplicateAndUpdate(), tieOpsIfNeeded(), tryAddToFoldList(), tryChangeVGPRtoSGPRinCopy(), tryFoldInst(), llvm::tryFoldSPUpdateIntoPushPop(), tryOptimizeLEAtoMOV(), tryToFindRegisterToRename(), tryToFoldACImm(), llvm::FastISel::tryToFoldLoad(), unstackifyVRegsUsedInSplitBB(), updateKillStatus(), updateOperand(), UpdateOperandRegClass(), updatePHIs(), updatePhysDepsDownwards(), llvm::R600InstrInfo::usesTextureCache(), llvm::R600InstrInfo::usesVertexCache(), validThroughout(), llvm::RegisterBankInfo::InstructionMapping::verify(), llvm::MachineFunction::verify(), verifyCFIntrinsic(), llvm::SIInstrInfo::verifyInstruction(), llvm::VirtRegAuxInfo::weightCalcHelper(), and llvm::LegalizerHelper::widenScalar().
getParent() [2/2]
MachineBasicBlock* llvm::MachineInstr::getParent () inline
Definition at line 272 of file MachineInstr.h.
References getMF().
getPostInstrSymbol()
MCSymbol* llvm::MachineInstr::getPostInstrSymbol () const inline
Helper to extract a post-instruction symbol if one has been added.
Definition at line 600 of file MachineInstr.h.
Referenced by cloneInstrSymbols(), cloneMemRefs(), dropMemRefs(), parseSymbolString(), llvm::MIPrinter::print(), print(), setHeapAllocMarker(), setMemRefs(), setPostInstrSymbol(), and setPreInstrSymbol().
getPreInstrSymbol()
MCSymbol* llvm::MachineInstr::getPreInstrSymbol () const inline
Helper to extract a pre-instruction symbol if one has been added.
Definition at line 588 of file MachineInstr.h.
Referenced by cloneInstrSymbols(), cloneMemRefs(), dropMemRefs(), llvm::MIPrinter::print(), print(), setHeapAllocMarker(), setMemRefs(), setPostInstrSymbol(), and setPreInstrSymbol().
getRegClassConstraint()
const TargetRegisterClass * MachineInstr::getRegClassConstraint (unsigned OpIdx, const TargetInstrInfo * TII, const TargetRegisterInfo * TRI) const
Compute the static register class constraint for operand OpIdx.
For normal instructions, this is derived from the MCInstrDesc. For inline assembly it is derived from the flag words.
Returns NULL if the static register class constraint cannot be determined.
Definition at line 831 of file MachineInstr.cpp.
References assert(), findInlineAsmFlagIdx(), getDesc(), llvm::MachineOperand::getImm(), llvm::InlineAsm::getKind(), getMF(), getOperand(), getParent(), llvm::TargetRegisterInfo::getPointerRegClass(), llvm::TargetInstrInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClass(), llvm::InlineAsm::hasRegClassConstraint(), isInlineAsm(), isReg(), isRegTiedToDefOperand(), llvm::InlineAsm::Kind_Mem, llvm::InlineAsm::Kind_RegDef, llvm::InlineAsm::Kind_RegDefEarlyClobber, and llvm::InlineAsm::Kind_RegUse.
Referenced by findRegisterDefOperand(), llvm::RegisterBankInfo::getRegBankFromConstraints(), getRegClassConstraintEffect(), getRegsUsedByPHIs(), isNopCopy(), llvm::TargetInstrInfo::reassociateOps(), UpdateOperandRegClass(), and llvm::SIInstrInfo::verifyInstruction().
getRegClassConstraintEffect()
const TargetRegisterClass * MachineInstr::getRegClassConstraintEffect (unsigned OpIdx, const TargetRegisterClass * CurRC, const TargetInstrInfo * TII, const TargetRegisterInfo * TRI) const
Applies the constraints (def/use) implied by the OpIdx operand to the given CurRC.
Returns the register class that satisfies both CurRC and the constraints set by OpIdx MI. Returns NULL if such a register class does not exist.
Precondition
CurRC must not be NULL.
The operand at OpIdx must be a register.
Definition at line 899 of file MachineInstr.cpp.
References assert(), llvm::TargetRegisterInfo::getCommonSubClass(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), getOperand(), getRegClassConstraint(), llvm::TargetRegisterInfo::getSubClassWithSubReg(), llvm::MachineOperand::getSubReg(), and llvm::MachineOperand::isReg().
Referenced by findRegisterDefOperand(), getRegClassConstraintEffectForVReg(), and llvm::MachineRegisterInfo::recomputeRegClass().
getRegClassConstraintEffectForVReg()
const TargetRegisterClass * MachineInstr::getRegClassConstraintEffectForVReg (Register Reg, const TargetRegisterClass * CurRC, const TargetInstrInfo * TII, const TargetRegisterInfo * TRI, bool ExploreBundle = false) const
Applies the constraints (def/use) implied by this MI on Reg to the given CurRC.
If ExploreBundle is set and MI is part of a bundle, all the instructions inside the bundle will be taken into account. In other words, this method accumulates all the constraints of the operand of this MI and the related bundle if MI is a bundle or inside a bundle.
Returns the register class that satisfies both CurRC and the constraints set by MI. Returns NULL if such a register class does not exist.
Precondition
CurRC must not be NULL.
Definition at line 870 of file MachineInstr.cpp.
References assert(), llvm::numbers::e, getOperand(), llvm::MachineOperand::getReg(), getRegClassConstraintEffect(), llvm::MachineOperand::isReg(), llvm::MIBundleOperandIteratorBase< ValueT >::isValid(), Reg, TII, and TRI.
Referenced by findRegisterDefOperand(), and getNumAllocatableRegsForConstraints().
getRestoreSize()
Optional< unsigned > MachineInstr::getRestoreSize (const TargetInstrInfo * TII) const
Return a valid size if the instruction is a restore instruction.
Definition at line 2179 of file MachineInstr.cpp.
References llvm::MachineFunction::getFrameInfo(), getMF(), llvm::TargetInstrInfo::isLoadFromStackSlotPostFE(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), memoperands_begin(), and llvm::None.
Referenced by emitComments(), INITIALIZE_PASS(), and isRegTiedToDefOperand().
getSpillSize()
Optional< unsigned > MachineInstr::getSpillSize (const TargetInstrInfo * TII) const
Return a valid size if the instruction is a spill instruction.
Definition at line 2160 of file MachineInstr.cpp.
References llvm::MachineFunction::getFrameInfo(), getMF(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::TargetInstrInfo::isStoreToStackSlotPostFE(), memoperands_begin(), and llvm::None.
Referenced by emitComments(), INITIALIZE_PASS(), and isRegTiedToDefOperand().
getTypeToPrint()
LLT MachineInstr::getTypeToPrint (unsigned OpIdx, SmallBitVector & PrintedTypes, const MachineRegisterInfo & MRI) const
Debugging supportDetermine the generic type to be printed (if needed) on uses and defs.
Definition at line 1423 of file MachineInstr.cpp.
References getDesc(), getNumExplicitOperands(), getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineOperand::isReg(), llvm::LLT::isValid(), isVariadic(), llvm::MCInstrDesc::OpInfo, and llvm::SmallBitVector::set().
Referenced by isRegTiedToDefOperand(), llvm::MIPrinter::print(), and print().
hasComplexRegisterTies()
bool MachineInstr::hasComplexRegisterTies () const
Return true when an instruction has tied register that can't be determined by the instruction's descriptor.
This is useful for MIR printing, to determine whether we need to print the ties or not.
Definition at line 1408 of file MachineInstr.cpp.
References E, findTiedOperandIdx(), getDesc(), getNumOperands(), getOperand(), llvm::MCInstrDesc::getOperandConstraint(), I, and llvm::MCOI::TIED_TO.
Referenced by isRegTiedToDefOperand(), llvm::MIPrinter::print(), and print().
hasDelaySlot()
bool llvm::MachineInstr::hasDelaySlot (QueryType Type = AnyInBundle) const inline
Returns true if the specified instruction has a delay slot which must be filled by the code generator.
Definition at line 790 of file MachineInstr.h.
References llvm::MCID::DelaySlot, and hasProperty().
Referenced by llvm::DwarfDebug::beginInstruction(), and hasUnoccupiedSlot().
hasExtraDefRegAllocReq()
bool llvm::MachineInstr::hasExtraDefRegAllocReq (QueryType Type = AnyInBundle) const inline
Returns true if this instruction def operands have special register allocation requirements that are not captured by the operand register classes.
e.g. ARM::LDRD's two def registers must be an even / odd pair, ARM::LDM registers have to be in ascending order. Post-register allocation passes should not attempt to change allocations for definitions of instructions with this flag.
Definition at line 987 of file MachineInstr.h.
References llvm::MCID::ExtraDefRegAllocReq, and hasProperty().
Referenced by CriticalPathStep(), and llvm::MachineOperand::isRenamable().
hasExtraSrcRegAllocReq()
bool llvm::MachineInstr::hasExtraSrcRegAllocReq (QueryType Type = AnyInBundle) const inline
Returns true if this instruction source operands have special register allocation requirements that are not captured by the operand register classes.
e.g. ARM::STRD's two source registers must be an even / odd pair, ARM::STM registers have to be in ascending order. Post-register allocation passes should not attempt to change allocations for sources of instructions with this flag.
Definition at line 977 of file MachineInstr.h.
References llvm::MCID::ExtraSrcRegAllocReq, and hasProperty().
Referenced by CriticalPathStep(), and llvm::MachineOperand::isRenamable().
hasImplicitDef()
bool llvm::MachineInstr::hasImplicitDef () const inline
Returns true if the instruction has implicit definition.
Definition at line 446 of file MachineInstr.h.
References E, getNumExplicitOperands(), getNumOperands(), getOperand(), I, llvm::MachineOperand::isDef(), and llvm::MachineOperand::isImplicit().
hasOneMemOperand()
bool llvm::MachineInstr::hasOneMemOperand () const inline
Return true if this instruction has exactly one MachineMemOperand.
Definition at line 582 of file MachineInstr.h.
References memoperands().
Referenced by llvm::SystemZInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::TargetInstrInfo::describeLoadedValue(), emitXBegin(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::RISCVInstrInfo::getMemOperandWithOffsetWidth(), llvm::PPCInstrInfo::getMemOperandWithOffsetWidth(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::ARMBaseInstrInfo::getOperandLatency(), getShiftTypeForInst(), getUnderlyingObjects(), INITIALIZE_PASS(), isConstant(), isMemoryOp(), IsSafeAndProfitableToMove(), isScalarLoadLegal(), lowerAlignmentHint(), mayAlias(), memOpsHaveSameBasePtr(), offsetsDoNotOverlap(), rewriteP2Align(), llvm::X86InstrInfo::unfoldMemoryOperand(), updateKillStatus(), VerifyLowRegs(), and X86SelectAddress().
hasOptionalDef()
bool llvm::MachineInstr::hasOptionalDef (QueryType Type = IgnoreBundle) const inline
Set if this instruction has an optional definition, e.g.
ARM instructions which can set condition code if 's' bit is set.
Definition at line 662 of file MachineInstr.h.
References llvm::MCID::HasOptionalDef, and hasProperty().
Referenced by isCopy(), and llvm::ARMBaseInstrInfo::optimizeSelect().
hasOrderedMemoryRef()
bool MachineInstr::hasOrderedMemoryRef () const
Return true if this instruction may have an ordered or volatile memory reference, or if the information describing the memory reference is not available.
hasOrderedMemoryRef - Return true if this instruction may have an ordered or volatile memory reference, or if the information describing the memory reference is not available.
Return false if it is known to have no ordered or volatile memory references.
Return false if it is known to have no ordered memory references.
Definition at line 1287 of file MachineInstr.cpp.
References llvm::any_of(), hasUnmodeledSideEffects(), isCall(), llvm::MachineMemOperand::isUnordered(), mayLoad(), mayStore(), memoperands(), and memoperands_empty().
Referenced by areCandidatesToMergeOrPair(), llvm::LanaiInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::AArch64InstrInfo::areMemAccessesTriviallyDisjoint(), llvm::RISCVInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::HexagonInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::SIInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::PPCInstrInfo::areMemAccessesTriviallyDisjoint(), getBufferFormatWithCompCount(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), isDependenceBarrier(), isGlobalMemoryObject(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isRegTiedToDefOperand(), isSafeToMove(), DeadCodeElimination::SetQueue< T >::push_back(), query(), and tryToFindRegisterToRename().
hasPostISelHook()
bool llvm::MachineInstr::hasPostISelHook (QueryType Type = IgnoreBundle) const inline
Return true if this instruction requires adjustment after instruction selection by calling a target hook.
For example, this can be used to fill in ARM 's' optional operand depending on whether the conditional flag register is used.
Definition at line 946 of file MachineInstr.h.
References llvm::MCID::HasPostISelHook, and hasProperty().
hasProperty()
bool llvm::MachineInstr::hasProperty (unsigned MCFlag, QueryType Type = AnyInBundle) const inline
Return true if the instruction (or in the case of a bundle, the instructions inside the bundle) has the specified property.
The first argument is the property being queried. The second argument indicates whether the query should look inside instruction bundles.
Definition at line 635 of file MachineInstr.h.
References assert(), getDesc(), llvm::MCInstrDesc::getFlags(), IgnoreBundle, isBundled(), and isBundledWithPred().
Referenced by canFoldAsLoad(), hasDelaySlot(), hasExtraDefRegAllocReq(), hasExtraSrcRegAllocReq(), hasOptionalDef(), hasPostISelHook(), hasUnmodeledSideEffects(), isAsCheapAsAMove(), isBarrier(), isBitcast(), isBranch(), isCall(), isCommutable(), isCompare(), isConvergent(), isConvertibleTo3Addr(), isEHScopeReturn(), isExtractSubregLike(), isIndirectBranch(), isInsertSubregLike(), isMoveImmediate(), isMoveReg(), isNotDuplicable(), isPredicable(), isPreISelOpcode(), isPseudo(), isRegSequenceLike(), isRematerializable(), isReturn(), isSelect(), isTerminator(), isVariadic(), mayLoad(), mayRaiseFPException(), mayStore(), and usesCustomInsertionHook().
hasRegisterImplicitUseOperand()
bool MachineInstr::hasRegisterImplicitUseOperand (Register Reg) const
Returns true if the MachineInstr has an implicit-use operand of exactly the given register (not considering sub/super-registers).
Definition at line 931 of file MachineInstr.cpp.
References llvm::numbers::e, getNumOperands(), getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), and Reg.
Referenced by registerDefIsDead(), and llvm::SIInstrInfo::verifyInstruction().
hasUnmodeledSideEffects()
bool MachineInstr::hasUnmodeledSideEffects () const
Return true if this instruction has side effects that are not modeled by mayLoad / mayStore, etc.
For all instructions, the property is encoded in MCInstrDesc::Flags (see MCInstrDesc::hasUnmodeledSideEffects(). The only exception is INLINEASM instruction, in which case the side effect property is encoded in one of its operands (see InlineAsm::Extra_HasSideEffect).
Definition at line 1368 of file MachineInstr.cpp.
References llvm::InlineAsm::Extra_HasSideEffects, llvm::MachineOperand::getImm(), getOperand(), hasProperty(), isInlineAsm(), llvm::InlineAsm::MIOp_ExtraInfo, and llvm::MCID::UnmodeledSideEffects.
Referenced by llvm::LanaiInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::AArch64InstrInfo::areMemAccessesTriviallyDisjoint(), llvm::RISCVInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::HexagonInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::SIInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::PPCInstrInfo::areMemAccessesTriviallyDisjoint(), CanMovePastDMB(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), hasOrderedMemoryRef(), INITIALIZE_PASS(), isCallerPreservedOrConstPhysReg(), isCompareZero(), isDependenceBarrier(), isGlobalMemoryObject(), isInvariantStore(), isLoadFoldBarrier(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), llvm::InstructionSelector::isObviouslySafeToFold(), isRegTiedToDefOperand(), isSafeToMove(), isUnsafeToMoveAcross(), isVirtualRegisterOperand(), DeadCodeElimination::SetQueue< T >::push_back(), query(), and regOverlapsSet().
implicit_operands() [1/2]
iterator_range<mop_iterator> llvm::MachineInstr::implicit_operands () inline
Definition at line 506 of file MachineInstr.h.
References llvm::sys::path::end(), explicit_operands(), llvm::make_range(), and operands_end().
Referenced by addRegsToSet(), ContainsReg(), copyFlagsToImplicitVCC(), llvm::createX86FixupBWInsts(), findImplicitSGPRRead(), llvm::SIInstrInfo::fixImplicitOperands(), getPostIndexedLoadStoreOpcode(), INITIALIZE_PASS(), isNopCopy(), llvm::InstructionSelector::isObviouslySafeToFold(), llvm::PPCInstrInfo::replaceInstrOperandWithImm(), and tryToFoldACImm().
implicit_operands() [2/2]
iterator_range<const_mop_iterator> llvm::MachineInstr::implicit_operands () const inline
Definition at line 509 of file MachineInstr.h.
References llvm::sys::path::end(), explicit_operands(), llvm::make_range(), and operands_end().
isAnnotationLabel()
bool llvm::MachineInstr::isAnnotationLabel () const inline
Definition at line 1041 of file MachineInstr.h.
References llvm::ISD::ANNOTATION_LABEL, and getOpcode().
Referenced by isLabel().
isAsCheapAsAMove()
bool llvm::MachineInstr::isAsCheapAsAMove (QueryType Type = AllInBundle) const inline
Returns true if this instruction has the same cost (or less) than a move instruction.
This is useful during certain types of optimizations (e.g., remat during two-address conversion or machine licm) where we would like to remat or hoist the instruction, but not if it costs more than moving the instruction into the appropriate register. Note, we are not marking copies from and to the same register class with this flag.
Definition at line 966 of file MachineInstr.h.
References llvm::MCID::CheapAsAMove, and hasProperty().
Referenced by llvm::AArch64InstrInfo::isAsCheapAsAMove(), llvm::RISCVInstrInfo::isAsCheapAsAMove(), llvm::TargetInstrInfo::isAsCheapAsAMove(), and shouldRematerialize().
isBarrier()
bool llvm::MachineInstr::isBarrier (QueryType Type = AnyInBundle) const inline
Returns true if the specified instruction stops control flow from executing the instruction immediately following it.
Examples include unconditional branches and return instructions.
Definition at line 689 of file MachineInstr.h.
References llvm::MCID::Barrier, and hasProperty().
Referenced by llvm::ScheduleDAGInstrs::addSchedBarrierDeps(), cannotCoexistAsymm(), llvm::ARMHazardRecognizer::getHazardType(), llvm::HexagonPacketizerList::hasControlDependence(), INITIALIZE_PASS(), isConditionalBranch(), isFpMulInstruction(), isUnconditionalBranch(), llvm::MSP430InstrInfo::isUnpredicatedTerminator(), llvm::X86InstrInfo::isUnpredicatedTerminator(), llvm::PPCInstrInfo::isUnpredicatedTerminator(), llvm::TargetInstrInfo::isUnpredicatedTerminator(), and ProfitableToMerge().
isBitcast()
bool llvm::MachineInstr::isBitcast (QueryType Type = IgnoreBundle) const inline
Return true if this instruction is a bitcast instruction.
Definition at line 760 of file MachineInstr.h.
References llvm::MCID::Bitcast, and hasProperty().
Referenced by getCopyRewriter().
isBranch()
bool llvm::MachineInstr::isBranch (QueryType Type = AnyInBundle) const inline
Returns true if this is a conditional, unconditional, or indirect branch.
Predicates below can be used to discriminate between these cases, and the TargetInstrInfo::AnalyzeBranch method can be used to get more information.
Definition at line 706 of file MachineInstr.h.
References llvm::MCID::Branch, and hasProperty().
Referenced by addLiveInRegs(), addRegsToSet(), cannotCoexistAsymm(), llvm::BitTracker::MachineEvaluator::evaluate(), getCmpForPseudo(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::PPCInstrInfo::getOperandLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), getRegClassForUnfoldedLoad(), llvm::HexagonPacketizerList::hasControlDependence(), INITIALIZE_PASS(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), isBranchRetTrap(), llvm::HexagonInstrInfo::isComplex(), llvm::HexagonInstrInfo::isCompoundBranchInstr(), isConditionalBranch(), isCopy(), llvm::rdf::TargetOperandInfo::isFixedReg(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::HexagonInstrInfo::isNewValueJump(), llvm::HexagonInstrInfo::isTailCall(), isUnconditionalBranch(), llvm::MSP430InstrInfo::isUnpredicatedTerminator(), llvm::X86InstrInfo::isUnpredicatedTerminator(), llvm::PPCInstrInfo::isUnpredicatedTerminator(), llvm::TargetInstrInfo::isUnpredicatedTerminator(), llvm::rdf::operator<<(), llvm::X86InstrInfo::optimizeCompareInstr(), DeadCodeElimination::SetQueue< T >::push_back(), regOverlapsSet(), splitBlock(), and llvm::BitTracker::visit().
isBundle()
bool llvm::MachineInstr::isBundle () const inline
Definition at line 1111 of file MachineInstr.h.
References getOpcode().
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::GCNSubtarget::adjustSchedDependency(), llvm::GCNHazardRecognizer::AdvanceCycle(), llvm::TailDuplicator::canTailDuplicate(), llvm::TargetSchedModel::computeInstrLatency(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::MipsInstrInfo::findCommutedOpIndices(), llvm::TargetInstrInfo::findCommutedOpIndices(), llvm::HexagonInstrInfo::getBranchingInstrs(), llvm::HexagonInstrInfo::getBundleNoShuf(), llvm::GCNHazardRecognizer::getHazardType(), llvm::SIInstrInfo::getInstrLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::HexagonInstrInfo::hasLoadFromStackSlot(), llvm::HexagonInstrInfo::hasStoreToStackSlot(), INITIALIZE_PASS(), isIdenticalTo(), IsMovepDestinationRegPair(), llvm::ARMBaseInstrInfo::isPredicable(), llvm::ARMBaseInstrInfo::isPredicated(), llvm::HexagonPacketizerList::isSoloInstruction(), llvm::TargetInstrInfo::PredicateInstruction(), llvm::GCNHazardRecognizer::PreEmitNoopsCommon(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), and UpdateCPSRUse().
isBundled()
bool llvm::MachineInstr::isBundled () const inline
Return true if this instruction part of a bundle.
This is true if either itself or its following instruction is marked "InsideBundle".
Definition at line 373 of file MachineInstr.h.
References isBundledWithPred(), and isBundledWithSucc().
Referenced by dumpMachineInstrRangeWithSlotIndex(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::LiveIntervals::handleMove(), hasProperty(), llvm::X86FrameLowering::inlineStackProbe(), and isValidClauseInst().
isBundledWithPred()
bool llvm::MachineInstr::isBundledWithPred () const inline
Return true if this instruction is part of a bundle, and it is not the first instruction in the bundle.
Definition at line 379 of file MachineInstr.h.
References BundledPred, and getFlag().
Referenced by bundleWithPred(), copyIRFlags(), hasProperty(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::MachineBasicBlock::insertAfterBundle(), isBundled(), moveInstrOut(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), unbundleFromPred(), and unbundleSingleMI().
isBundledWithSucc()
bool llvm::MachineInstr::isBundledWithSucc () const inline
Return true if this instruction is part of a bundle, and it is not the last instruction in the bundle.
Definition at line 383 of file MachineInstr.h.
References BundledSucc, bundleWithPred(), bundleWithSucc(), getFlag(), unbundleFromPred(), and unbundleFromSucc().
Referenced by bundleWithSucc(), hasUnoccupiedSlot(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::MachineBasicBlock::insertAfterBundle(), isBundled(), moveInstrOut(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), unbundleFromSucc(), and unbundleSingleMI().
isCall()
bool llvm::MachineInstr::isCall (QueryType Type = AnyInBundle) const inline
Definition at line 682 of file MachineInstr.h.
References llvm::MCID::Call, and hasProperty().
Referenced by llvm::MachineFunction::addCallArgsForwardingRegs(), addLiveInRegs(), llvm::ScheduleDAGInstrs::addSchedBarrierDeps(), llvm::DwarfDebug::beginInstruction(), callHasRegMask(), llvm::EHStreamer::callToNoUnwindFunction(), callWaitsOnFunctionReturn(), CanMovePastDMB(), cannotCoexistAsymm(), llvm::MachineFunction::copyCallSiteInfo(), CriticalPathStep(), llvm::MachineFunction::DeleteMachineInstr(), dumpMachineInstrRangeWithSlotIndex(), llvm::SystemZHazardRecognizer::emitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::MachineFunction::getFilterIDFor(), getFPReg(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::AArch64InstrInfo::getOutliningCandidateInfo(), llvm::AArch64InstrInfo::getOutliningType(), getRegClassForUnfoldedLoad(), getRegUnits(), llvm::X86InstrInfo::getSPAdjust(), llvm::HexagonPacketizerList::hasControlDependence(), llvm::HexagonPacketizerList::hasDeadDependence(), hasOrderedMemoryRef(), llvm::HexagonPacketizerList::hasRegMaskDependence(), llvm::SIInstrInfo::hasUnwantedEffectsWhenEXECEmpty(), hasYmmOrZmmReg(), INITIALIZE_PASS(), isCallerPreservedOrConstPhysReg(), isCallInstruction(), llvm::rdf::TargetOperandInfo::isClobbering(), isCoalescable(), isCompareZero(), llvm::HexagonInstrInfo::isComplex(), llvm::HexagonInstrInfo::isConstExtended(), isDependenceBarrier(), llvm::rdf::TargetOperandInfo::isFixedReg(), isGlobalMemoryObject(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), isLoadFoldBarrier(), llvm::AArch64InstrInfo::isMBBSafeToOutlineFrom(), isNoReturnDef(), llvm::HexagonInstrInfo::isPredicable(), IsSafeAndProfitableToMove(), isSafeToMove(), llvm::HexagonInstrInfo::isSchedulingBoundary(), llvm::ARMBaseInstrInfo::isSchedulingBoundary(), llvm::PPCInstrInfo::isSignOrZeroExtended(), llvm::TargetInstrInfo::isTailCall(), isVirtualRegisterOperand(), mayAlias(), llvm::SIInstrInfo::mayReadEXEC(), llvm::WebAssembly::mayThrow(), llvm::MachineFunction::moveCallSiteInfo(), needsStackFrame(), llvm::rdf::operator<<(), DeadCodeElimination::SetQueue< T >::push_back(), query(), regOverlapsSet(), llvm::HexagonRegisterInfo::shouldCoalesce(), llvm::TailDuplicator::shouldTailDuplicate(), tryToFindRegisterToRename(), and UpdateCPSRUse().
isCFIInstruction()
bool llvm::MachineInstr::isCFIInstruction () const inline
Definition at line 1050 of file MachineInstr.h.
References getOpcode().
Referenced by countsAsInstruction(), llvm::RISCVInstrInfo::getOutliningType(), getRegsUsedByPHIs(), llvm::HexagonPacketizerList::ignorePseudoInstruction(), INITIALIZE_PASS(), isPosition(), llvm::HexagonPacketizerList::isSoloInstruction(), llvm::MIPrinter::print(), print(), and llvm::TailDuplicator::shouldTailDuplicate().
isCommutable()
bool llvm::MachineInstr::isCommutable (QueryType Type = IgnoreBundle) const inline
Return true if this may be a 2- or 3-address instruction (of the form "X = op Y, Z, ..."), which produces the same result if Y and Z are exchanged.
If this flag is set, then the TargetInstrInfo::commuteInstruction method may be used to hack on the instruction.
Note that this flag may be set on instructions that are only commutable sometimes. In these cases, the call to commuteInstruction will fail. Also note that some instructions require non-trivial modification to commute them.
Definition at line 908 of file MachineInstr.h.
References llvm::MCID::Commutable, and hasProperty().
Referenced by addSegmentsWithValNo(), llvm::TargetInstrInfo::commuteInstruction(), foldImmediates(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), isCallerPreservedOrConstPhysReg(), isIdentityValue(), isLiveOut(), llvm::SIInstrInfo::legalizeOperandsVOP2(), matchSwap(), tieOpsIfNeeded(), and tryConstantFoldOp().
isCompare()
bool llvm::MachineInstr::isCompare (QueryType Type = IgnoreBundle) const inline
Return true if this instruction is a comparison.
Definition at line 743 of file MachineInstr.h.
References llvm::MCID::Compare, and hasProperty().
Referenced by llvm::SystemZInstrInfo::analyzeCompare(), getCompareSourceReg(), INITIALIZE_PASS(), isCompareZero(), llvm::HexagonInstrInfo::isEarlySourceInstr(), isVirtualRegisterOperand(), lowerRIHigh(), lowerRILow(), and matchSwap().
isConditionalBranch()
bool llvm::MachineInstr::isConditionalBranch (QueryType Type = AnyInBundle) const inline
Return true if this is a branch which may fall through to the next instruction or may transfer control flow to some other block.
The TargetInstrInfo::AnalyzeBranch method can be used to get more information about this branch.
Definition at line 720 of file MachineInstr.h.
References isBarrier(), isBranch(), and isIndirectBranch().
Referenced by llvm::HexagonInstrInfo::getDotNewPredJumpOp(), and isVirtualRegisterOperand().
isConstantValuePHI()
unsigned MachineInstr::isConstantValuePHI () const
If the specified instruction is a PHI that always merges together the same virtual register, return the register, otherwise return 0.
isConstantValuePHI - If the specified instruction is a PHI that always merges together the same virtual register, return the register, otherwise return 0.
Definition at line 1355 of file MachineInstr.cpp.
References assert(), llvm::numbers::e, getNumOperands(), getOperand(), llvm::MachineOperand::getReg(), getReg(), isPHI(), and Reg.
Referenced by llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), and isRegTiedToDefOperand().
isConvergent()
bool llvm::MachineInstr::isConvergent (QueryType Type = AnyInBundle) const inline
Return true if this instruction is convergent.
Convergent instructions can not be made control-dependent on any additional values.
Definition at line 779 of file MachineInstr.h.
References llvm::MCID::Convergent, llvm::InlineAsm::Extra_IsConvergent, llvm::MachineOperand::getImm(), getOperand(), hasProperty(), isInlineAsm(), and llvm::InlineAsm::MIOp_ExtraInfo.
Referenced by performSink(), and llvm::TailDuplicator::shouldTailDuplicate().
isConvertibleTo3Addr()
bool llvm::MachineInstr::isConvertibleTo3Addr (QueryType Type = IgnoreBundle) const inline
Return true if this is a 2-address instruction which can be changed into a 3-address instruction if needed.
Doing this transformation can be profitable in the register allocator, because it means that the instruction can use a 2-address form if possible, but degrade into a less efficient form if the source and dest register cannot be assigned to the same register. For example, this allows the x86 backend to turn a "shl reg, 3" instruction into an LEA instruction, which is the same speed as the shift but has bigger code size.
If this returns true, then the target must implement the TargetInstrInfo::convertToThreeAddress method for this instruction, which is allowed to fail if the transformation isn't valid for this specific instruction (e.g. shl reg, 4 on x86).
Definition at line 926 of file MachineInstr.h.
References llvm::MCID::ConvertibleTo3Addr, and hasProperty().
isCopy()
bool llvm::MachineInstr::isCopy () const inline
Definition at line 1115 of file MachineInstr.h.
References getOpcode().
Referenced by addSegmentsWithValNo(), llvm::HexagonSubtarget::adjustSchedDependency(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::biasPhysReg(), canFoldCopy(), computeBranchTargetAndInversion(), llvm::createCopyConstrainDAGMutation(), dumpMachineInstrRangeWithSlotIndex(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::HexagonEvaluator::evaluate(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), findSRegBaseAndIndex(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldVGPRCopyIntoRegSequence(), getFPReg(), getNewSource(), getRegClassFromGRPhysReg(), getRegUnits(), getSingleDef(), getVectorSHLImm(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), insertPHI(), isBackwardPropagatableCopy(), isCoalescable(), isCopyFeedingInvariantStore(), llvm::TargetInstrInfo::isCopyInstr(), isCopyLike(), isCopyLike(), isCopyToReg(), isDebug(), isDefInSubRange(), isFpMulInstruction(), isFullCopy(), isFullCopyOf(), isFullExecCopy(), isIdentityCopy(), llvm::SIInstrInfo::isInlineConstant(), isLocalCopy(), isNopCopy(), isUncheckedLoadOrStoreOpcode(), llvm::SIInstrInfo::isVGPRCopy(), isVirtualRegisterOperand(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::TargetRegisterInfo::lookThruCopyLike(), MIIsInTerminatorSequence(), llvm::SIInstrInfo::moveToVALU(), llvm::AArch64InstrInfo::optimizeCondBranch(), performSink(), regOverlapsSet(), llvm::GenericScheduler::reschedulePhysReg(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AMDGPUInstructionSelector::select(), selectCopy(), llvm::SystemZRegisterInfo::shouldCoalesce(), swapAntiDependences(), llvm::TailDuplicator::tailDuplicateAndUpdate(), tryToFoldACImm(), and llvm::VirtRegAuxInfo::weightCalcHelper().
isCopyLike()
bool llvm::MachineInstr::isCopyLike () const inline
Return true if the instruction behaves like a copy.
This does not include native copy instructions.
Definition at line 1129 of file MachineInstr.h.
References isCopy(), and isSubregToReg().
Referenced by definesFullReg(), llvm::ARMBaseInstrInfo::getOperandLatency(), INITIALIZE_PASS(), isCallerPreservedOrConstPhysReg(), isCoalescable(), isCopyFeedingInvariantStore(), isSplitEdge(), isTerminalReg(), llvm::TargetRegisterInfo::lookThruCopyLike(), llvm::SIInstrInfo::mayReadEXEC(), and regOverlapsSet().
isDebugEntryValue()
bool MachineInstr::isDebugEntryValue () const
A DBG_VALUE is an entry value iff its debug expression contains the DW_OP_LLVM_entry_value operation.
Definition at line 826 of file MachineInstr.cpp.
References getDebugExpression(), isDebugValue(), and llvm::DIExpression::isEntryValue().
Referenced by isIndirectDebugValue().
isDebugInstr()
bool llvm::MachineInstr::isDebugInstr () const inline
Definition at line 1059 of file MachineInstr.h.
References isDebugLabel(), and isDebugValue().
Referenced by addRegsToSet(), llvm::GCNHazardRecognizer::AdvanceCycle(), llvm::CodeViewDebug::beginInstruction(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), callWaitsOnFunctionReturn(), collectCallSiteParameters(), countsAsInstruction(), llvm::createBreakFalseDeps(), llvm::ARMHazardRecognizer::EmitInstruction(), llvm::PPCHazardRecognizer970::EmitInstruction(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::BitTracker::MachineEvaluator::evaluate(), findStartOfTree(), getDataDeps(), llvm::ARMHazardRecognizer::getHazardType(), llvm::PPCHazardRecognizer970::getHazardType(), getNewValueJumpOpcode(), llvm::X86InstrInfo::getOutliningCandidateInfo(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), getRegUnits(), getRetpolineSymbol(), getSchedRegions(), llvm::HexagonInstrInfo::getSize(), getStartOrEndSlot(), llvm::LiveVariables::HandleVirtRegDef(), llvm::HexagonPacketizerList::ignorePseudoInstruction(), INITIALIZE_PASS(), llvm::SlotIndexes::insertMachineInstrInMaps(), isCallerPreservedOrConstPhysReg(), isDefInSubRange(), isFullCopyOf(), isFullUndefDef(), isIdenticalTo(), IsSafeAndProfitableToMove(), isSafeToMove(), llvm::HexagonInstrInfo::isSchedulingBoundary(), llvm::ARMBaseInstrInfo::isSchedulingBoundary(), isVirtualRegisterOperand(), llvm::CriticalAntiDepBreaker::Observe(), query(), llvm::GCNUpwardRPTracker::recede(), removeRegisterOperands(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::rdf::Liveness::resetKills(), resultTests(), llvm::RegScavenger::unprocess(), UpdateCPSRUse(), and llvm::VirtRegAuxInfo::weightCalcHelper().
isDebugLabel()
bool llvm::MachineInstr::isDebugLabel () const inline
Definition at line 1058 of file MachineInstr.h.
References getOpcode().
Referenced by llvm::DbgLabelInstrMap::addInstr(), llvm::MachineInstrBuilder::addMetadata(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::MipsAsmPrinter::EmitInstruction(), getDebugLabel(), isDebugInstr(), and print().
isDebugValue()
bool llvm::MachineInstr::isDebugValue () const inline
Definition at line 1057 of file MachineInstr.h.
References getOpcode().
Referenced by llvm::MachineInstrBuilder::addMetadata(), addSegmentsWithValNo(), AssignProtectedObjSet(), llvm::ScheduleDAGInstrs::buildSchedGraph(), collectRegDefs(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::DbgVariableLocation::extractFromMachineInstruction(), getDebugExpression(), getDebugVariable(), getLoadStoreOffsetAlign(), getRegUnits(), getSingleDef(), INITIALIZE_PASS(), llvm::Mips16RegisterInfo::intRegClass(), isCoalescable(), isDbgValueDescribedByReg(), isDebugEntryValue(), isDebugInstr(), isDefBetween(), isDefInSubRange(), isDescribedByReg(), isFullCopyOf(), isFullUndefDef(), isIndirectDebugValue(), isRegOtherThanSPAndFP(), isUndefDebugValue(), isValidClauseInst(), llvm::MachineRegisterInfo::markUsesInDebugValueAsUndef(), MIIsInTerminatorSequence(), moveAndTeeForMultiUse(), needsReferenceType(), false::IntervalSorter::operator()(), print(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), and llvm::AntiDepBreaker::UpdateDbgValue().
isDereferenceableInvariantLoad()
bool MachineInstr::isDereferenceableInvariantLoad (AAResults * AA) const
Return true if this load instruction never traps and points to a memory location whose value doesn't change during the execution of this function.
isDereferenceableInvariantLoad - Return true if this instruction will never trap and is loading from a location whose value is invariant across a run of this function.
Examples include loading a value from the constant pool or from the argument area of a function (if it does not change). If the instruction does multiple loads, this returns true only if all of the loads are dereferenceable and invariant.
Definition at line 1309 of file MachineInstr.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), getParent(), mayLoad(), memoperands(), memoperands_empty(), and llvm::AAResults::pointsToConstantMemory().
Referenced by llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), isCallerPreservedOrConstPhysReg(), isCopyFeedingInvariantStore(), isDependenceBarrier(), isGlobalMemoryObject(), llvm::X86InstrInfo::isReallyTriviallyReMaterializable(), isRegTiedToDefOperand(), isSafeToMove(), and query().
isEHLabel()
bool llvm::MachineInstr::isEHLabel () const inline
Definition at line 1039 of file MachineInstr.h.
References llvm::ISD::EH_LABEL, and getOpcode().
Referenced by getRetpolineSymbol(), isLabel(), and llvm::HexagonPacketizerList::isSoloInstruction().
isEHScopeReturn()
bool llvm::MachineInstr::isEHScopeReturn (QueryType Type = AnyInBundle) const inline
Return true if this is an instruction that marks the end of an EH scope, i.e., a catchpad or a cleanuppad instruction.
Definition at line 678 of file MachineInstr.h.
References llvm::MCID::EHScopeReturn, and hasProperty().
isExtractSubreg()
bool llvm::MachineInstr::isExtractSubreg () const inline
Definition at line 1123 of file MachineInstr.h.
References getOpcode().
Referenced by llvm::TargetInstrInfo::getExtractSubregInputs(), insertPHI(), and isOperandSubregIdx().
isExtractSubregLike()
bool llvm::MachineInstr::isExtractSubregLike (QueryType Type = IgnoreBundle) const inline
Return true if this instruction behaves the same way as the generic EXTRACT_SUBREG instructions.
E.g., on ARM, rX, rY VMOVRRD dZ is equivalent to two EXTRACT_SUBREG: rX = EXTRACT_SUBREG dZ, ssub_0 rY = EXTRACT_SUBREG dZ, ssub_1
Note that for the optimizers to be able to take advantage of this property, TargetInstrInfo::getExtractSubregLikeInputs has to be override accordingly.
Definition at line 831 of file MachineInstr.h.
References llvm::MCID::ExtractSubreg, and hasProperty().
Referenced by getCopyRewriter(), llvm::TargetInstrInfo::getExtractSubregInputs(), and llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs().
isFullCopy()
bool llvm::MachineInstr::isFullCopy () const inline
Definition at line 1119 of file MachineInstr.h.
References getOperand(), llvm::MachineOperand::getSubReg(), and isCopy().
Referenced by addSegmentsWithValNo(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SIInstrInfo::foldMemoryOperandImpl(), llvm::CoalescerPair::isCoalescable(), isCoalescable(), isFullCopyOf(), isFullExecCopy(), isRematerializable(), and removeCopies().
isGCLabel()
bool llvm::MachineInstr::isGCLabel () const inline
Definition at line 1040 of file MachineInstr.h.
References getOpcode().
Referenced by isLabel().
isIdenticalTo()
bool MachineInstr::isIdenticalTo (const MachineInstr & Other, MICheckType Check = CheckDefs) const
Return true if this instruction is identical to Other.
Two instructions are identical if they have the same opcode and all their operands are identical (with respect to MachineOperand::isIdenticalTo()). Note that this means liveness related flags (dead, undef, kill) do not affect the notion of identical.
Definition at line 584 of file MachineInstr.cpp.
References assert(), CheckKillDead, llvm::numbers::e, getDebugLoc(), llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >::getIterator(), llvm::ilist_node_impl< OptionsT >::getIterator(), getNumOperands(), getOpcode(), getOperand(), llvm::MachineOperand::getReg(), IgnoreDefs, IgnoreVRegDefs, isBundle(), llvm::MachineOperand::isDead(), isDebugInstr(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), and llvm::Register::isVirtualRegister().
Referenced by INITIALIZE_PASS(), llvm::MachineInstrExpressionTrait::isEqual(), llvm::ARMBaseInstrInfo::produceSameValue(), and llvm::TargetInstrInfo::produceSameValue().
isIdentityCopy()
bool llvm::MachineInstr::isIdentityCopy () const inline
Return true is the instruction is an identity copy.
Definition at line 1134 of file MachineInstr.h.
References getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), and isCopy().
Referenced by llvm::VirtRegAuxInfo::weightCalcHelper().
isImplicitDef()
bool llvm::MachineInstr::isImplicitDef () const inline
Definition at line 1084 of file MachineInstr.h.
References getOpcode().
Referenced by llvm::HexagonPacketizerList::addToPacket(), llvm::GCNHazardRecognizer::AdvanceCycle(), allPhiOperandsUndefined(), llvm::HexagonPacketizerList::canPromoteToDotNew(), canTurnIntoCOPY(), definesFullReg(), getFPReg(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::HexagonPacketizerList::ignorePseudoInstruction(), INITIALIZE_PASS(), isCallerPreservedOrConstPhysReg(), isCopyFeedingInvariantStore(), isCrossCopy(), isFpMulInstruction(), isFullUndefDef(), isImplicitlyDef(), isVirtualRegisterOperand(), llvm::SIInstrInfo::legalizeGenericOperand(), MIIsInTerminatorSequence(), shouldPreventUndefRegUpdateMemFold(), and llvm::VirtRegAuxInfo::weightCalcHelper().
isIndirectBranch()
bool llvm::MachineInstr::isIndirectBranch (QueryType Type = AnyInBundle) const inline
Return true if this is an indirect branch, such as a branch through a register.
Definition at line 712 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::IndirectBranch.
Referenced by llvm::MipsInstrInfo::analyzeBranch(), blockEndsInUnreachable(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::rdf::DataFlowGraph::getNextShadow(), isConditionalBranch(), llvm::HexagonInstrInfo::isHVXMemWithAIndirect(), isUnconditionalBranch(), and llvm::TailDuplicator::shouldTailDuplicate().
isIndirectDebugValue()
bool llvm::MachineInstr::isIndirectDebugValue () const inline
A DBG_VALUE is indirect iff the first operand is a register and the second operand is an immediate.
Definition at line 1063 of file MachineInstr.h.
References getOperand(), isDebugEntryValue(), isDebugValue(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
Referenced by AssignProtectedObjSet(), computeExprForSpill(), llvm::DbgVariableLocation::extractFromMachineInstruction(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), INITIALIZE_PASS(), isRegOtherThanSPAndFP(), print(), and llvm::SelectionDAGISel::runOnMachineFunction().
isInlineAsm()
bool llvm::MachineInstr::isInlineAsm () const inline
Definition at line 1085 of file MachineInstr.h.
References getOpcode(), llvm::ISD::INLINEASM, and llvm::ISD::INLINEASM_BR.
Referenced by addOperand(), addRegisterDead(), addRegisterKilled(), llvm::RegAllocBase::allocatePhysRegs(), llvm::BTFDebug::beginInstruction(), cannotCoexistAsymm(), llvm::HexagonPacketizerList::canPromoteToDotCur(), llvm::HexagonPacketizerList::canPromoteToDotNew(), CriticalPathStep(), llvm::PPCRegisterInfo::eliminateFrameIndex(), EmitGCCInlineAsmStr(), llvm::LiveRangeEdit::eraseVirtReg(), findInlineAsmFlagIdx(), findStartOfTree(), findTiedOperandIdx(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), getFPReg(), llvm::GCNHazardRecognizer::getHazardType(), getInlineAsmDialect(), llvm::ARCInstrInfo::getInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), getOffsetONFromFION(), llvm::RISCVInstrInfo::getOutliningType(), getRegClassConstraint(), hasUnmodeledSideEffects(), llvm::SIInstrInfo::hasUnwantedEffectsWhenEXECEmpty(), llvm::HexagonPacketizerList::ignorePseudoInstruction(), isCallerPreservedOrConstPhysReg(), isCoalescable(), isConvergent(), llvm::rdf::TargetOperandInfo::isFixedReg(), isMSInlineAsm(), llvm::HexagonInstrInfo::isSchedulingBoundary(), llvm::HexagonPacketizerList::isSoloInstruction(), isStackAligningInlineAsm(), isUnsafeToMoveAcross(), isVirtualRegisterOperand(), mayLoad(), mayStore(), moveAndTeeForMultiUse(), llvm::GCNHazardRecognizer::PreEmitNoopsCommon(), print(), removeRegisterOperands(), llvm::MipsInstrInfo::SafeInForbiddenSlot(), tieOperands(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), and llvm::SIInstrInfo::verifyInstruction().
isInsertSubreg()
bool llvm::MachineInstr::isInsertSubreg () const inline
Definition at line 1099 of file MachineInstr.h.
References getOpcode().
Referenced by llvm::TargetInstrInfo::getInsertSubregInputs(), llvm::ARMBaseInstrInfo::getOperandLatency(), INITIALIZE_PASS(), insertPHI(), isCopyToReg(), and isOperandSubregIdx().
isInsertSubregLike()
bool llvm::MachineInstr::isInsertSubregLike (QueryType Type = IgnoreBundle) const inline
Return true if this instruction behaves the same way as the generic INSERT_SUBREG instructions.
E.g., on ARM, dX = VSETLNi32 dY, rZ, Imm is equivalent to a INSERT_SUBREG: dX = INSERT_SUBREG dY, rZ, translateImmToSubIdx(Imm)
Note that for the optimizers to be able to take advantage of this property, TargetInstrInfo::getInsertSubregLikeInputs has to be override accordingly.
Definition at line 845 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::InsertSubreg.
Referenced by getCopyRewriter(), llvm::TargetInstrInfo::getInsertSubregInputs(), and llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs().
isInsideBundle()
bool llvm::MachineInstr::isInsideBundle () const inline
Return true if MI is in a bundle (but not the first MI in a bundle).
A bundle looks like this before it's finalized:
| MI |
|
| MI * |
|
| MI * |
In this case, the first MI starts a bundle but is not inside a bundle, the next 2 MIs are considered "inside" the bundle.
After a bundle is finalized, it looks like this:
| Bundle |
|
| MI * |
|
| MI * |
|
| MI * |
The first instruction has the special opcode "BUNDLE". It's not "inside" a bundle, but the next three MIs are.
Definition at line 367 of file MachineInstr.h.
References BundledPred, and getFlag().
Referenced by llvm::BuildMI(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::MIPrinter::print(), llvm::MachineBasicBlock::print(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), and UpdateCPSRUse().
isKill()
bool llvm::MachineInstr::isKill () const inline
Definition at line 1083 of file MachineInstr.h.
References getOpcode(), and llvm::AMDGPUISD::KILL.
Referenced by llvm::GCNHazardRecognizer::AdvanceCycle(), CriticalPathStep(), findRegisterUseOperand(), llvm::X86InstrInfo::getOutliningCandidateInfo(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), isCallerPreservedOrConstPhysReg(), isCrossCopy(), isVirtualRegisterOperand(), llvm::CriticalAntiDepBreaker::Observe(), and registerDefIsDead().
isLabel()
bool llvm::MachineInstr::isLabel () const inline
Returns true if the MachineInstr represents a label.
Definition at line 1046 of file MachineInstr.h.
References isAnnotationLabel(), isEHLabel(), and isGCLabel().
Referenced by findStartOfTree(), isPosition(), and removeRegisterOperands().
isLoadFoldBarrier()
bool MachineInstr::isLoadFoldBarrier () const
Returns true if it is illegal to fold a load across this instruction.
Definition at line 1380 of file MachineInstr.cpp.
References hasUnmodeledSideEffects(), isCall(), and mayStore().
Referenced by isRegTiedToDefOperand(), and isVirtualRegisterOperand().
isMetaInstruction()
bool llvm::MachineInstr::isMetaInstruction () const inline
Return true if this instruction doesn't produce any output in the form of executable instructions.
Definition at line 1141 of file MachineInstr.h.
References llvm::ISD::EH_LABEL, getOpcode(), llvm::AMDGPUISD::KILL, llvm::ISD::LIFETIME_END, and llvm::ISD::LIFETIME_START.
Referenced by llvm::BTFDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), llvm::DebugHandlerBase::endInstruction(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getOutliningType(), INITIALIZE_PASS(), isRealInstruction(), isTransient(), isUnsafeToMoveAcross(), llvm::SIInstrInfo::mayReadEXEC(), and llvm::TailDuplicator::shouldTailDuplicate().
isMoveImmediate()
bool llvm::MachineInstr::isMoveImmediate (QueryType Type = IgnoreBundle) const inline
Return true if this instruction is a move immediate (including conditional moves) instruction.
Definition at line 749 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::MoveImm.
Referenced by llvm::biasPhysReg(), llvm::X86InstrInfo::describeLoadedValue(), llvm::SIInstrInfo::FoldImmediate(), foldImmediates(), getImmOrMaterializedImm(), getNewSource(), INITIALIZE_PASS(), isSafeToFoldImmIntoCopy(), llvm::SIInstrInfo::legalizeGenericOperand(), and llvm::GenericScheduler::reschedulePhysReg().
isMoveReg()
bool llvm::MachineInstr::isMoveReg (QueryType Type = IgnoreBundle) const inline
Return true if this instruction is a register move.
(including moving values from subreg to reg)
Definition at line 755 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::MoveReg.
Referenced by llvm::MipsSEInstrInfo::isCopyInstrImpl(), llvm::ARMBaseInstrInfo::isCopyInstrImpl(), llvm::Mips16InstrInfo::isCopyInstrImpl(), and llvm::X86InstrInfo::isCopyInstrImpl().
isMSInlineAsm()
bool llvm::MachineInstr::isMSInlineAsm () const inline
FIXME: Seems like a layering violation that the AsmDialect, which is X86 specific, be attached to a generic MachineInstr.
Definition at line 1092 of file MachineInstr.h.
References llvm::InlineAsm::AD_Intel, getInlineAsmDialect(), isInlineAsm(), and isStackAligningInlineAsm().
isNotDuplicable()
bool llvm::MachineInstr::isNotDuplicable (QueryType Type = AnyInBundle) const inline
Return true if this instruction cannot be safely duplicated.
For example, if the instruction has a unique labels attached to it, duplicating it would cause multiple definition errors.
Definition at line 772 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::NotDuplicable.
Referenced by llvm::TargetInstrInfo::duplicate(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), and llvm::TailDuplicator::shouldTailDuplicate().
isOperandSubregIdx()
bool llvm::MachineInstr::isOperandSubregIdx (unsigned OpIdx) const inline
Return true if operand OpIdx is a subregister index.
Definition at line 462 of file MachineInstr.h.
References assert(), getNumExplicitDefs(), getNumExplicitOperands(), getOperand(), getType(), isExtractSubreg(), isInsertSubreg(), isRegSequence(), isSubregToReg(), and llvm::MachineOperand::MO_Immediate.
Referenced by llvm::MIPrinter::print(), and print().
isPHI()
bool llvm::MachineInstr::isPHI () const inline
Definition at line 1079 of file MachineInstr.h.
References getOpcode().
Referenced by allPhiOperandsUndefined(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::SwingSchedulerDAG::applyInstrChange(), llvm::TailDuplicator::canTailDuplicate(), checkRegOnlyPHIInputs(), computeLiveOuts(), createBBSelectReg(), llvm::LiveRangeCalc::createDeadDefs(), dominatesAllUsesOf(), llvm::SMSchedule::finalizeSchedule(), fixupRegionExits(), llvm::Localizer::getAnalysisUsage(), llvm::RegBankSelect::getAnalysisUsage(), llvm::SwingSchedulerDAG::getDistance(), getPHIDeps(), getPHIDestReg(), getPHINumInputs(), getPHIPred(), getPhiRegs(), getPHISourceReg(), getRegsUsedByPHIs(), getUnderlyingObjects(), getZeroLatency(), llvm::LiveVariables::HandleVirtRegDef(), hasUseAfterLoop(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), llvm::RegBankSelect::InstrInsertPoint::InstrInsertPoint(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::InstrIsPHI(), llvm::SwingSchedulerDAG::isBackedge(), isCallerPreservedOrConstPhysReg(), isConstantValuePHI(), isCopyLike(), isDebug(), isIntersect(), llvm::SMSchedule::isLoopCarried(), llvm::SMSchedule::isLoopCarriedDefOfUse(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isPreISelGenericFloatingPointOpcode(), isSafeToMove(), llvm::isTriviallyDead(), llvm::SMSchedule::isValidSchedule(), isVirtualRegisterOperand(), isVRegCompatibleReg(), llvm::PeelSingleBlockLoop(), profitImm(), DeadCodeElimination::SetQueue< T >::push_back(), pushDepHeight(), llvm::RegBankSelect::RepairingPlacement::RepairingPlacement(), llvm::MachineSSAUpdater::RewriteUse(), llvm::AMDGPUInstructionSelector::select(), llvm::TailDuplicator::shouldTailDuplicate(), swapAntiDependences(), llvm::TailDuplicator::tailDuplicateAndUpdate(), and llvm::MachineTraceMetrics::Ensemble::updateDepth().
isPosition()
bool llvm::MachineInstr::isPosition () const inline
Definition at line 1055 of file MachineInstr.h.
References isCFIInstruction(), and isLabel().
Referenced by llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::RISCVInstrInfo::getOutliningType(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), llvm::HexagonInstrInfo::getSize(), isCallerPreservedOrConstPhysReg(), isFpMulInstruction(), isSafeToMove(), llvm::HexagonInstrInfo::isSchedulingBoundary(), llvm::ARMBaseInstrInfo::isSchedulingBoundary(), llvm::TargetInstrInfo::isSchedulingBoundary(), isVirtualRegisterOperand(), DeadCodeElimination::SetQueue< T >::push_back(), and query().
isPredicable()
bool llvm::MachineInstr::isPredicable (QueryType Type = AllInBundle) const inline
Return true if this instruction has a predicate operand that controls execution.
It may be set to 'always', or may be set to other values. There are various methods in TargetInstrInfo that can be used to control and modify the predicate in this instruction.
Definition at line 736 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::Predicable.
Referenced by AnyAliasLiveIn(), canFoldIntoSelect(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseInstrInfo::isPredicable(), llvm::MSP430InstrInfo::isUnpredicatedTerminator(), llvm::X86InstrInfo::isUnpredicatedTerminator(), llvm::TargetInstrInfo::isUnpredicatedTerminator(), llvm::TargetInstrInfo::PredicateInstruction(), RemoveDeadAddBetweenLEAAndJT(), and SinkingPreventsImplicitNullCheck().
isPreISelOpcode()
bool llvm::MachineInstr::isPreISelOpcode (QueryType Type = IgnoreBundle) const inline
Return true if this is an instruction that should go through the usual legalization steps.
Definition at line 648 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::PreISelOpcode.
Referenced by llvm::AMDGPUInstructionSelector::select(), and shouldReadExec().
isPseudo()
bool llvm::MachineInstr::isPseudo (QueryType Type = IgnoreBundle) const inline
Return true if this is a pseudo instruction that doesn't correspond to a real machine instruction.
Definition at line 668 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::Pseudo.
Referenced by canRenameUpToDef(), INITIALIZE_PASS(), insertNopBeforeInstruction(), isRealInstruction(), and llvm::ConvergingVLIWScheduler::SchedulingCost().
isRegSequence()
bool llvm::MachineInstr::isRegSequence () const inline
Definition at line 1107 of file MachineInstr.h.
References getOpcode().
Referenced by llvm::HexagonSubtarget::adjustSchedDependency(), foldVGPRCopyIntoRegSequence(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::ARMBaseInstrInfo::getOperandLatency(), getRegSeqInit(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::getRegSequenceSubReg(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), insertPHI(), isDebug(), isOperandSubregIdx(), swapAntiDependences(), and tryToFoldACImm().
isRegSequenceLike()
bool llvm::MachineInstr::isRegSequenceLike (QueryType Type = IgnoreBundle) const inline
Return true if this instruction behaves the same way as the generic REG_SEQUENCE instructions.
E.g., on ARM, dX VMOVDRR rY, rZ is equivalent to dX = REG_SEQUENCE rY, ssub_0, rZ, ssub_1.
Note that for the optimizers to be able to take advantage of this property, TargetInstrInfo::getRegSequenceLikeInputs has to be override accordingly.
Definition at line 816 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::RegSequence.
Referenced by getCopyRewriter(), llvm::TargetInstrInfo::getRegSequenceInputs(), and llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs().
isRegTiedToDefOperand()
bool llvm::MachineInstr::isRegTiedToDefOperand (unsigned UseOpIdx, unsigned * DefOpIdx = nullptr) const inline
Return true if the use operand of the specified index is tied to a def operand.
It also returns the def operand index by reference if DefOpIdx is not null.
Definition at line 1379 of file MachineInstr.h.
References addOperand(), addRegisterDead(), addRegisterDefined(), addRegisterKilled(), allDefsAreDead(), clearKillInfo(), clearRegisterDeads(), clearRegisterKills(), copyImplicitOps(), dump(), findTiedOperandIdx(), getFoldedRestoreSize(), getFoldedSpillSize(), getOperand(), getRestoreSize(), getSpillSize(), getTypeToPrint(), hasComplexRegisterTies(), hasOrderedMemoryRef(), hasUnmodeledSideEffects(), isConstantValuePHI(), isDereferenceableInvariantLoad(), isLoadFoldBarrier(), llvm::MachineOperand::isReg(), isSafeToMove(), llvm::MachineOperand::isTied(), llvm::MachineOperand::isUse(), mayAlias(), MI, MRI, llvm::Other, print(), setPhysRegsDeadExcept(), setRegisterDefReadUndef(), substituteRegister(), and UseTBAA.
Referenced by addRegisterKilled(), addSegmentsWithValNo(), llvm::AnalyzeVirtRegInBundle(), llvm::LiveRangeCalc::createDeadDefs(), dumpMachineInstrRangeWithSlotIndex(), getRegClassConstraint(), and isTwoAddrUse().
isRegTiedToUseOperand()
bool llvm::MachineInstr::isRegTiedToUseOperand (unsigned DefOpIdx, unsigned * UseOpIdx = nullptr) const inline
Given the index of a register def operand, check if the register def is tied to a source operand, due to either two-address elimination or inline assembly constraints.
Returns the first tied use operand index by reference if UseOpIdx is not null.
Definition at line 1366 of file MachineInstr.h.
References findTiedOperandIdx(), getOperand(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isTied().
Referenced by addSegmentsWithValNo(), llvm::constrainSelectedInstRegOperands(), CriticalPathStep(), llvm::SwingSchedulerDAG::fixupRegisterOverlaps(), isVirtualRegisterOperand(), llvm::AggressiveAntiDepBreaker::Observe(), and llvm::SIInstrInfo::verifyInstruction().
isRematerializable()
bool llvm::MachineInstr::isRematerializable (QueryType Type = AllInBundle) const inline
Returns true if this instruction is a candidate for remat.
This flag is deprecated, please don't use it anymore. If this flag is set, the isReallyTriviallyReMaterializable() method is called to verify the instruction is really rematable.
Definition at line 954 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::Rematerializable.
isReturn()
bool llvm::MachineInstr::isReturn (QueryType Type = AnyInBundle) const inline
Definition at line 672 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::Return.
Referenced by blockEndsInUnreachable(), callWaitsOnFunctionReturn(), CanMovePastDMB(), llvm::createMemLibcall(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::MipsAsmPrinter::EmitInstruction(), enableAllocFrameElim(), llvm::RISCVInstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), llvm::SIInstrInfo::hasUnwantedEffectsWhenEXECEmpty(), INITIALIZE_PASS(), isBranchRetTrap(), isCallInstruction(), llvm::HexagonInstrInfo::isComplex(), isCopy(), isEFLAGSLive(), llvm::rdf::TargetOperandInfo::isFixedReg(), isLibCallInTailPosition(), llvm::TargetInstrInfo::isTailCall(), DeadCodeElimination::SetQueue< T >::push_back(), and llvm::TailDuplicator::shouldTailDuplicate().
isSafeToMove()
bool MachineInstr::isSafeToMove (AAResults * AA, bool & SawStore) const
Return true if it is safe to move this instruction.
isSafeToMove - Return true if it is safe to move this instruction.
If SawStore is set to true, it means that there is a store (or call) between the instruction's location and its intended destination.
Definition at line 1162 of file MachineInstr.cpp.
References hasOrderedMemoryRef(), hasUnmodeledSideEffects(), isCall(), isDebugInstr(), isDereferenceableInvariantLoad(), isPHI(), isPosition(), isTerminator(), mayLoad(), mayRaiseFPException(), and mayStore().
Referenced by canFoldIntoSelect(), llvm::ARMBaseInstrInfo::commuteInstructionImpl(), definesFullReg(), llvm::LiveRangeEdit::eraseVirtReg(), findSinkableLocalRegDef(), isCopyFeedingInvariantStore(), isRegTiedToDefOperand(), llvm::isTriviallyDead(), MaySpeculate(), llvm::X86InstrInfo::optimizeLoadInstr(), performSink(), and regOverlapsSet().
isSelect()
bool llvm::MachineInstr::isSelect (QueryType Type = IgnoreBundle) const inline
Return true if this instruction is a select instruction.
Definition at line 765 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::Select.
Referenced by isVirtualRegisterOperand().
isStackAligningInlineAsm()
bool MachineInstr::isStackAligningInlineAsm () const
Definition at line 768 of file MachineInstr.cpp.
References llvm::InlineAsm::Extra_IsAlignStack, llvm::MachineOperand::getImm(), getOperand(), isInlineAsm(), and llvm::InlineAsm::MIOp_ExtraInfo.
Referenced by isMSInlineAsm().
isSubregToReg()
bool llvm::MachineInstr::isSubregToReg () const inline
Definition at line 1103 of file MachineInstr.h.
References getOpcode().
Referenced by isCopyLike(), isCopyToReg(), isOperandSubregIdx(), and llvm::TargetRegisterInfo::lookThruCopyLike().
isTerminator()
bool llvm::MachineInstr::isTerminator (QueryType Type = AnyInBundle) const inline
Returns true if this instruction part of the terminator for a basic block.
Typically this is things like return and branch instructions.
Various passes use this to insert code into the bottom of a basic block, but before control flow occurs.
Definition at line 698 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::Terminator.
Referenced by llvm::GCNSubtarget::adjustSchedDependency(), appendEndToFunction(), llvm::ScheduleDAGInstrs::buildSchedGraph(), cannotCoexistAsymm(), llvm::createSIWholeQuadModePass(), llvm::SystemZHazardRecognizer::emitInstruction(), llvm::RegBankSelect::getAnalysisUsage(), llvm::RISCVInstrInfo::getOutliningType(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), getRegClassForUnfoldedLoad(), INITIALIZE_PASS(), llvm::SIInstrInfo::isBasicBlockPrologue(), isCallerPreservedOrConstPhysReg(), IsSafeAndProfitableToMove(), isSafeToMove(), llvm::ARMBaseInstrInfo::isSchedulingBoundary(), llvm::TargetInstrInfo::isSchedulingBoundary(), llvm::RegBankSelect::InstrInsertPoint::isSplit(), llvm::MSP430InstrInfo::isUnpredicatedTerminator(), llvm::X86InstrInfo::isUnpredicatedTerminator(), llvm::PPCInstrInfo::isUnpredicatedTerminator(), llvm::TargetInstrInfo::isUnpredicatedTerminator(), parseSymbolString(), query(), regOverlapsSet(), and llvm::RegBankSelect::RepairingPlacement::RepairingPlacement().
isTransient()
bool llvm::MachineInstr::isTransient () const inline
Return true if this is a transient instruction that is either very likely to be eliminated during register allocation (such as copy-like instructions), or if this instruction doesn't have an execution-time cost.
Definition at line 1161 of file MachineInstr.h.
References getBundleSize(), getOpcode(), and isMetaInstruction().
Referenced by llvm::TargetSchedModel::computeOperandLatency(), llvm::createSIWholeQuadModePass(), llvm::TargetInstrInfo::defaultDefLatency(), llvm::HexagonInstrInfo::getInstrTimingClassLatency(), llvm::TargetSchedModel::getNumMicroOps(), IsMovepDestinationRegPair(), mayAlias(), tryToFindRegisterToRename(), updatePhysDepsUpwards(), llvm::SchedDFSImpl::visitPostorderNode(), and llvm::SchedDFSImpl::visitPreorder().
isUnconditionalBranch()
bool llvm::MachineInstr::isUnconditionalBranch (QueryType Type = AnyInBundle) const inline
Return true if this is a branch which always transfers control flow to some other block.
The TargetInstrInfo::AnalyzeBranch method can be used to get more information about this branch.
Definition at line 728 of file MachineInstr.h.
References isBarrier(), isBranch(), and isIndirectBranch().
Referenced by llvm::MipsInstrInfo::analyzeBranch(), llvm::RegBankSelect::getAnalysisUsage(), getUnconditionalBrDisp(), INITIALIZE_PASS(), and isSplitEdge().
isUndefDebugValue()
bool llvm::MachineInstr::isUndefDebugValue () const inline
Return true if the instruction is a debug value which describes a part of a variable as unavailable.
Definition at line 1075 of file MachineInstr.h.
References getOperand(), llvm::MachineOperand::getReg(), isDebugValue(), llvm::MachineOperand::isReg(), and llvm::Register::isValid().
Referenced by validThroughout().
isVariadic()
bool llvm::MachineInstr::isVariadic (QueryType Type = IgnoreBundle) const inline
Return true if this instruction can have a variable number of operands.
In this case, the variable operands will be after the normal operands but before the implicit definitions and uses (if any are present).
Definition at line 656 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::Variadic.
Referenced by llvm::createBreakFalseDeps(), llvm::SIInstrInfo::getOpRegClass(), getTypeToPrint(), and INITIALIZE_PASS().
killsRegister()
bool llvm::MachineInstr::killsRegister (Register Reg, const TargetRegisterInfo * TRI = nullptr) const inline
Return true if the MachineInstr kills the specified register.
If TargetRegisterInfo is passed, then it also checks if there is a kill of a super-register.
Definition at line 1209 of file MachineInstr.h.
References findRegisterUseOperandIdx(), and TRI.
Referenced by llvm::X86InstrInfo::breakPartialRegDependency(), checkEFLAGSLive(), ContainsReg(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), isPlainlyKilled(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::X86InstrInfo::optimizeCompareInstr(), UpdateCPSRUse(), and updateDefinedRegisters().
mayAlias()
bool MachineInstr::mayAlias (AAResults * AA, const MachineInstr & Other, bool UseTBAA) const
Returns true if this instruction's memory access aliases the memory access of Other.
Assumes any physical registers used to compute addresses have the same value for both instructions. Returns false if neither instruction writes to memory.
Parameters
AA Optional alias analysis, used to compare memory operands.
Other MachineInstr to check aliasing against.
UseTBAA Whether to pass TBAA information to alias analysis.
Definition at line 1191 of file MachineInstr.cpp.
References llvm::AAResults::alias(), llvm::TargetInstrInfo::areMemAccessesTriviallyDisjoint(), assert(), llvm::MachineMemOperand::getAAInfo(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), getMF(), llvm::MachineMemOperand::getOffset(), llvm::MachineMemOperand::getPseudoValue(), llvm::MachineMemOperand::getSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineMemOperand::getValue(), hasOneMemOperand(), llvm::max(), llvm::PseudoSourceValue::mayAlias(), mayStore(), memoperands_begin(), llvm::NoAlias, and llvm::MemoryLocation::UnknownSize.
Referenced by llvm::ScheduleDAGInstrs::addChainDependency(), isRegTiedToDefOperand(), and mayAlias().
mayLoad()
bool llvm::MachineInstr::mayLoad (QueryType Type = AnyInBundle) const inline
Return true if this instruction could possibly read memory.
Instructions with this flag set are not necessarily simple load instructions, they may load a value and modify it, for example.
Definition at line 856 of file MachineInstr.h.
References llvm::InlineAsm::Extra_MayLoad, llvm::MachineOperand::getImm(), getOperand(), hasProperty(), isInlineAsm(), llvm::MCID::MayLoad, and llvm::InlineAsm::MIOp_ExtraInfo.
Referenced by llvm::GCNSubtarget::adjustSchedDependency(), AnyAliasLiveIn(), llvm::HexagonSubtarget::HVXMemLatencyMutation::apply(), llvm::HexagonSubtarget::BankConflictMutation::apply(), llvm::HexagonInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::ScheduleDAGInstrs::buildSchedGraph(), callWaitsOnFunctionReturn(), CanMovePastDMB(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), llvm::TargetInstrInfo::defaultDefLatency(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::HexagonEvaluator::evaluate(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), llvm::ARCInstrInfo::getBaseAndOffsetPosition(), llvm::HexagonInstrInfo::getBaseAndOffsetPosition(), getBufferFormatWithCompCount(), llvm::TargetInstrInfo::getInstrLatency(), llvm::SIInstrInfo::getMemOperandWithOffset(), getNewSource(), llvm::ARMBaseInstrInfo::getOperandLatency(), getPostIncrementOperand(), getRegClassForUnfoldedLoad(), getUnderlyingObjects(), hasOrderedMemoryRef(), INITIALIZE_PASS(), isCallerPreservedOrConstPhysReg(), isCopyFeedingInvariantStore(), isDependenceBarrier(), isDereferenceableInvariantLoad(), isEFLAGSLive(), llvm::HexagonInstrInfo::isHVXMemWithAIndirect(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::SIInstrInfo::isLoadFromStackSlot(), llvm::ARMBaseInstrInfo::isLoadFromStackSlotPostFE(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isSafeToMove(), isValidClauseInst(), mayLoadFromGOTOrConstantPool(), mayLoadOrStore(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), packCmovGroup(), query(), llvm::HexagonHazardRecognizer::ShouldPreferAnother(), SinkingPreventsImplicitNullCheck(), and tryToFindRegisterToRename().
mayLoadOrStore()
bool llvm::MachineInstr::mayLoadOrStore (QueryType Type = AnyInBundle) const inline
Return true if this instruction could possibly read or modify memory.
Definition at line 879 of file MachineInstr.h.
References mayLoad(), and mayStore().
Referenced by AnyAliasLiveIn(), llvm::LanaiInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::AArch64InstrInfo::areMemAccessesTriviallyDisjoint(), llvm::RISCVInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::SIInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::PPCInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::TargetInstrInfo::areMemAccessesTriviallyDisjoint(), callWaitsOnFunctionReturn(), canMoveInstsAcrossMemOp(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMHazardRecognizer::getHazardType(), llvm::GCNHazardRecognizer::getHazardType(), llvm::AArch64InstrInfo::getMemOpBaseRegImmOfsOffsetOperand(), llvm::AArch64InstrInfo::getMemOperandWithOffset(), llvm::SIInstrInfo::getMemOperandWithOffset(), llvm::RISCVInstrInfo::getMemOperandWithOffsetWidth(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), llvm::PPCInstrInfo::getMemOperandWithOffsetWidth(), getMemOpKey(), llvm::AArch64InstrInfo::getOutliningCandidateInfo(), getShiftTypeForInst(), INITIALIZE_PASS(), isAddWithImmediate(), llvm::HexagonInstrInfo::isEarlySourceInstr(), isFirstInstructionInSequence(), llvm::PPCInstrInfo::isImmInstrEligibleForFolding(), isLoadStoreThatCanHandleDisplacement(), llvm::InstructionSelector::isObviouslySafeToFold(), mayAlias(), llvm::SIRegisterInfo::needsFrameBaseReg(), llvm::GCNHazardRecognizer::PreEmitNoopsCommon(), tryToFindRegisterToRename(), usedAsAddr(), and VerifyLowRegs().
mayRaiseFPException()
bool llvm::MachineInstr::mayRaiseFPException () const inline
Return true if this instruction could possibly raise a floating-point exception.
This is the case if the instruction is a floating-point instruction that can in principle raise an exception, as indicated by the MCID::MayRaiseFPException property, and at the same time, the instruction is used in a context where we expect floating-point exceptions are not disabled, as indicated by the NoFPExcept MI flag.
Definition at line 889 of file MachineInstr.h.
References getFlag(), hasProperty(), and llvm::MCID::MayRaiseFPException.
Referenced by llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), getCompareSourceReg(), isAddWithImmediate(), isCallerPreservedOrConstPhysReg(), isCompareZero(), isDependenceBarrier(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), llvm::InstructionSelector::isObviouslySafeToFold(), and isSafeToMove().
mayStore()
bool llvm::MachineInstr::mayStore (QueryType Type = AnyInBundle) const inline
Return true if this instruction could possibly modify memory.
Instructions with this flag set are not necessarily simple store instructions, they may store a modified value based on their operands, or may not actually modify anything, for example.
Definition at line 869 of file MachineInstr.h.
References llvm::InlineAsm::Extra_MayStore, llvm::MachineOperand::getImm(), getOperand(), hasProperty(), isInlineAsm(), llvm::MCID::MayStore, and llvm::InlineAsm::MIOp_ExtraInfo.
Referenced by llvm::SUnit::addPredBarrier(), addRegsToSet(), llvm::GCNSubtarget::adjustSchedDependency(), AnyAliasLiveIn(), llvm::HexagonSubtarget::HVXMemLatencyMutation::apply(), llvm::HexagonSubtarget::BankConflictMutation::apply(), llvm::ScheduleDAGInstrs::buildSchedGraph(), callWaitsOnFunctionReturn(), llvm::HexagonInstrInfo::canExecuteInBundle(), CanMovePastDMB(), cannotCoexistAsymm(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), canRenameUpToDef(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::createSIAddIMGInitPass(), llvm::createSIWholeQuadModePass(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), llvm::ARCInstrInfo::getBaseAndOffsetPosition(), llvm::HexagonInstrInfo::getBaseAndOffsetPosition(), getBufferFormatWithCompCount(), getInstrVecReg(), llvm::SIInstrInfo::getMemOperandWithOffset(), getUnderlyingObjects(), llvm::HexagonPacketizerList::hasDualStoreDependence(), hasOrderedMemoryRef(), hasRAWHazard(), llvm::SIInstrInfo::hasUnwantedEffectsWhenEXECEmpty(), INITIALIZE_PASS(), InstructionStoresToFI(), isCallerPreservedOrConstPhysReg(), isCopyFeedingInvariantStore(), isFullCopyOf(), llvm::HexagonInstrInfo::isHVXMemWithAIndirect(), isInvariantStore(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), isLoadFoldBarrier(), isLoadStoreThatCanHandleDisplacement(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), llvm::HexagonPacketizerList::isNewifiable(), isSafeToMove(), llvm::SIInstrInfo::isStoreToStackSlot(), llvm::ARMBaseInstrInfo::isStoreToStackSlotPostFE(), isValidClauseInst(), mayAlias(), mayAlias(), llvm::HexagonInstrInfo::mayBeNewStore(), mayLoadOrStore(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), DeadCodeElimination::SetQueue< T >::push_back(), query(), and llvm::SIInstrInfo::verifyInstruction().
memoperands()
ArrayRef<MachineMemOperand *> llvm::MachineInstr::memoperands () const inline
Access to memory operands of the instruction.
If there are none, that does not imply anything about whether the function accesses memory. Instead, the caller must behave conservatively.
Definition at line 549 of file MachineInstr.h.
References llvm::makeArrayRef().
Referenced by llvm::VLIWPacketizerList::alias(), AnyAliasLiveIn(), callWaitsOnFunctionReturn(), cloneMemRefs(), cloneMergedMemRefs(), createPHIsForSelects(), llvm::createX86FixupBWInsts(), llvm::TargetInstrInfo::describeLoadedValue(), emitXBegin(), llvm::HexagonInstrInfo::expandPostRAPseudo(), findIncDecAfter(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::LegalizerInfo::getAction(), getCompareSourceReg(), getNumMemOperands(), getStoreTarget(), getUnderlyingObjectsForInstr(), hasOneMemOperand(), hasOrderedMemoryRef(), INITIALIZE_PASS(), InstructionStoresToFI(), isDereferenceableInvariantLoad(), llvm::AArch64InstrInfo::isLdStPairSuppressed(), llvm::AArch64InstrInfo::isStridedAccess(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::SIInstrInfo::mayAccessFlatAddressSpace(), mayLoadFromGOTOrConstantPool(), memoperands_begin(), memoperands_empty(), memoperands_end(), llvm::MIPrinter::print(), print(), setHeapAllocMarker(), setPostInstrSymbol(), setPreInstrSymbol(), llvm::X86InstrInfo::unfoldMemoryOperand(), and VerifyLowRegs().
memoperands_begin()
mmo_iterator llvm::MachineInstr::memoperands_begin () const inline
Access to memory operands of the instruction.
If memoperands_begin() == memoperands_end(), that does not imply anything about whether the function accesses memory. Instead, the caller must behave conservatively.
Definition at line 567 of file MachineInstr.h.
References memoperands().
Referenced by addMemOperand(), llvm::SystemZInstrInfo::areMemAccessesTriviallyDisjoint(), cloneMergedMemRefs(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::PPCHazardRecognizer970::EmitInstruction(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), expandLoadStackGuard(), llvm::AArch64InstrInfo::expandPostRAPseudo(), findPotentialBlockers(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getBufferStoreFormatOpcode(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::RISCVInstrInfo::getMemOperandWithOffsetWidth(), llvm::PPCInstrInfo::getMemOperandWithOffsetWidth(), getMemsetValue(), llvm::ARMBaseInstrInfo::getNumLDMAddresses(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::ARMBaseInstrInfo::getOperandLatency(), getRestoreSize(), getRetpolineSymbol(), getShiftTypeForInst(), getSpillSize(), getStoreTarget(), getUnderlyingObjects(), getVectorSHLImm(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), llvm::TargetInstrInfo::hasStoreToStackSlot(), INITIALIZE_PASS(), InsertFPConstInst(), InsertFPImmInst(), InsertSPConstInst(), InsertSPImmInst(), isConstant(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isMemoryOp(), IsSafeAndProfitableToMove(), isScalarLoadLegal(), llvm::SIInstrInfo::isStackAccess(), isStackPtrRelative(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::LegalizerHelper::lower(), lowerAlignmentHint(), mayAlias(), memOpsHaveSameBasePtr(), llvm::LegalizerHelper::narrowScalar(), offsetsDoNotOverlap(), false::IntervalSorter::operator()(), llvm::LegalizerHelper::reduceLoadStoreWidth(), ReplaceFrameIndex(), rewriteP2Align(), llvm::AMDGPUInstructionSelector::select(), llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic(), llvm::AArch64InstrInfo::suppressLdStPair(), llvm::CombinerHelper::tryCombineMemCpyFamily(), updateKillStatus(), VerifyLowRegs(), and X86SelectAddress().
memoperands_empty()
bool llvm::MachineInstr::memoperands_empty () const inline
Return true if we don't have any memory operands which described the memory access done by this instruction.
If this is true, calling code must be conservative.
Definition at line 579 of file MachineInstr.h.
References memoperands().
Referenced by llvm::VLIWPacketizerList::alias(), AnyAliasLiveIn(), callWaitsOnFunctionReturn(), cloneMergedMemRefs(), dropMemRefs(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::PPCHazardRecognizer970::getHazardType(), getStoreTarget(), hasOrderedMemoryRef(), InstructionStoresToFI(), isDereferenceableInvariantLoad(), llvm::SIInstrInfo::isStackAccess(), llvm::SIInstrInfo::mayAccessFlatAddressSpace(), mayLoadFromGOTOrConstantPool(), llvm::MIPrinter::print(), print(), and llvm::AArch64InstrInfo::suppressLdStPair().
memoperands_end()
mmo_iterator llvm::MachineInstr::memoperands_end () const inline
Access to memory operands of the instruction.
If memoperands_begin() == memoperands_end(), that does not imply anything about whether the function accesses memory. Instead, the caller must behave conservatively.
Definition at line 574 of file MachineInstr.h.
References memoperands().
Referenced by addMemOperand(), cloneMergedMemRefs(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::ARMBaseInstrInfo::getNumLDMAddresses(), getRetpolineSymbol(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), llvm::TargetInstrInfo::hasStoreToStackSlot(), false::IntervalSorter::operator()(), and llvm::CombinerHelper::tryCombineMemCpyFamily().
mergeFlagsWith()
uint16_t MachineInstr::mergeFlagsWith (const MachineInstr & Other) const
Return the MIFlags which represent both MachineInstrs.
This should be used when merging two MachineInstrs into one. This routine does not modify the MIFlags of this MachineInstr.
Definition at line 520 of file MachineInstr.cpp.
References getFlags().
Referenced by setDebugLoc().
modifiesRegister()
bool llvm::MachineInstr::modifiesRegister (Register Reg, const TargetRegisterInfo * TRI) const inline
Return true if the MachineInstr modifies (fully define or partially define) the specified register.
NOTE: It's ignoring subreg indices on virtual registers.
Definition at line 1226 of file MachineInstr.h.
References findRegisterDefOperandIdx().
Referenced by addRegsToSet(), areCFlagsAccessedBetweenInstrs(), callWaitsOnFunctionReturn(), canInstrSubstituteCmpInstr(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), llvm::HexagonInstrInfo::DefinesPredicate(), doesModifyCalleeSavedReg(), llvm::SIRegisterInfo::findReachingDef(), getOModValue(), llvm::AArch64InstrInfo::getOutliningCandidateInfo(), llvm::RISCVInstrInfo::getOutliningType(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), INITIALIZE_PASS(), llvm::SIInstrInfo::isBasicBlockPrologue(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), isEndCF(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), isNopCopy(), llvm::SIInstrInfo::isSchedulingBoundary(), llvm::TargetInstrInfo::isSchedulingBoundary(), isUnsafeToMoveAcross(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::reMaterialize(), swapMIOperands(), and UseReg().
operands() [1/2]
iterator_range<mop_iterator> llvm::MachineInstr::operands () inline
Definition at line 492 of file MachineInstr.h.
References llvm::make_range(), operands_begin(), and operands_end().
Referenced by addDefsUsesToList(), addImplicitDefUseOperands(), llvm::LiveIntervals::addKillFlags(), llvm::GISelInstProfileBuilder::addNodeID(), addRegisterDefined(), llvm::ScheduleDAGInstrs::addSchedBarrierDeps(), addToListsIfDependent(), allDefsAreDead(), AnyAliasLiveIn(), appendEndToFunction(), callHasRegMask(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), canRenameUpToDef(), ClearKillFlags(), clearKillInfo(), clearRegisterDeads(), clearRegisterKills(), collectCallSiteParameters(), collectRegDefs(), collectVirtualRegUses(), llvm::ScheduleDAGMILive::collectVRegUses(), computeLiveOuts(), convertTailJumpOpcode(), llvm::createBreakFalseDeps(), definesFullReg(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::RegScavenger::enterBasicBlockEnd(), eraseFromParentAndMarkDBGValuesForRemoval(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::evaluate(), findIntrinsicID(), findSinkableLocalRegDef(), findSurvivorBackwards(), getCalledFunction(), getCompareSourceReg(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::ReachingDefAnalysis::getLocalLiveOutMIDef(), getLogicalBitOpcode(), getMopState(), getNewValueJumpOpcode(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::RISCVInstrInfo::getOutliningType(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), getPostIncrementOperand(), getPredicatedRegister(), getRegUnits(), getRetpolineSymbol(), getStartOrEndSlot(), handleNormalInst(), llvm::HexagonPacketizerList::hasDeadDependence(), llvm::HexagonPacketizerList::hasRegMaskDependence(), hasWriteToReadDep(), hasYmmOrZmmReg(), INITIALIZE_PASS(), instrDefsUsesSCC(), InstructionStoresToFI(), isBackwardPropagatableCopy(), llvm::HexagonPacketizerList::isCallDependent(), isCallerPreservedOrConstPhysReg(), isCoalescable(), isCopyFeedingInvariantStore(), llvm::ARMBaseInstrInfo::isCPSRDefined(), isCrossCopy(), llvm::HexagonInstrInfo::isExtended(), llvm::rdf::TargetOperandInfo::isFixedReg(), isHighLatencyCPSR(), isImplicitDependency(), isInvariantStore(), isNopCopy(), llvm::ReachingDefAnalysis::isReachingDefLiveOut(), IsSafeToMove(), isSafeToMove(), llvm::HexagonInstrInfo::isTailCall(), llvm::isTriviallyDead(), isVirtualRegisterOperand(), llvm::AArch64MCInstLower::Lower(), llvm::LowerARMMachineInstrToMCInst(), llvm::AVRMCInstLower::lowerInstruction(), llvm::LowerRISCVMachineInstrToMCInst(), MaySpeculate(), needsStackFrame(), llvm::rdf::operator<<(), performSink(), llvm::HexagonInstrInfo::predCanBeUsedAsDotNew(), profitImm(), DeadCodeElimination::SetQueue< T >::push_back(), regOverlapsSet(), llvm::rdf::Liveness::resetKills(), llvm::SIRegisterInfo::resolveFrameIndex(), scavengeFrameVirtualRegsInBlock(), llvm::RegScavenger::scavengeRegister(), setPhysRegsDeadExcept(), setRegisterDefReadUndef(), llvm::AMDGPUInstructionSelector::setupMF(), substituteRegister(), toggleKills(), unsupportedBinOp(), llvm::LiveIntervals::HMEditor::updateAllRanges(), UpdateCPSRDef(), and UpdateCPSRUse().
operands() [2/2]
iterator_range<const_mop_iterator> llvm::MachineInstr::operands () const inline
Definition at line 495 of file MachineInstr.h.
References llvm::make_range(), operands_begin(), and operands_end().
operands_begin() [1/2]
mop_iterator llvm::MachineInstr::operands_begin () inline
Definition at line 486 of file MachineInstr.h.
References Operands.
Referenced by NoAutoPaddingScope::changeAndComment(), computeBytesPoppedByCalleeForSRet(), defs(), llvm::LiveRangeEdit::eraseVirtReg(), explicit_operands(), explicit_uses(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getDataDeps(), getDwarfRegNum(), getOperandNo(), getUnderlyingObjects(), INITIALIZE_PASS(), MIIsInTerminatorSequence(), operands(), llvm::R600InstrInfo::readsLDSSrcReg(), llvm::StackMaps::recordPatchPoint(), llvm::StackMaps::recordStackMap(), llvm::StackMaps::recordStatepoint(), llvm::R600SchedStrategy::releaseBottomNode(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::R600SchedStrategy::schedNode(), llvm::MachineBasicBlock::SplitCriticalEdge(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), and uses().
operands_begin() [2/2]
const_mop_iterator llvm::MachineInstr::operands_begin () const inline
Definition at line 489 of file MachineInstr.h.
References Operands.
operands_end() [1/2]
mop_iterator llvm::MachineInstr::operands_end () inline
Definition at line 487 of file MachineInstr.h.
Referenced by NoAutoPaddingScope::changeAndComment(), computeBytesPoppedByCalleeForSRet(), llvm::LiveRangeEdit::eraseVirtReg(), findIntrinsicID(), getDataDeps(), getUnderlyingObjects(), implicit_operands(), INITIALIZE_PASS(), MIIsInTerminatorSequence(), operands(), llvm::rdf::operator<<(), llvm::R600InstrInfo::readsLDSSrcReg(), llvm::StackMaps::recordPatchPoint(), llvm::StackMaps::recordStackMap(), llvm::StackMaps::recordStatepoint(), llvm::R600SchedStrategy::releaseBottomNode(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::R600SchedStrategy::schedNode(), llvm::MachineBasicBlock::SplitCriticalEdge(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), and uses().
operands_end() [2/2]
const_mop_iterator llvm::MachineInstr::operands_end () const inline
Definition at line 490 of file MachineInstr.h.
operator=()
MachineInstr& llvm::MachineInstr::operator= (const MachineInstr &) delete
print() [1/2]
void MachineInstr::print (raw_ostream & OS, bool IsStandalone = true, bool SkipOpers = false, bool SkipDebugLoc = false, bool AddNewLine = true, const TargetInstrInfo * TII = nullptr) const
Print this MI to OS.
Don't print information that can be inferred from other instructions if IsStandalone is false. It is usually true when only a fragment of the function is printed. Only print the defs and the opcode if SkipOpers is true. Otherwise, also print operands if SkipDebugLoc is true. Otherwise, also print the debug loc, with a terminating newline. TII is used to print the opcode name. If it's not present, but the MI is in a function, the opcode will be printed using the function's TII.
Definition at line 1454 of file MachineInstr.cpp.
References F(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), getMFIfAvailable(), llvm::GlobalValue::getParent(), llvm::MachineFunction::getSubtarget(), and llvm::ModuleSlotTracker::incorporateFunction().
Referenced by callWaitsOnFunctionReturn(), dump(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), llvm::ScheduleDAGInstrs::getGraphNodeLabel(), getRegClassFromGRPhysReg(), getRetOpcode(), llvm::HexagonLowerToMC(), INITIALIZE_PASS(), isRegTiedToDefOperand(), llvm::LegalizerHelper::legalizeInstrStep(), llvm::MSP430MCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::AVRMCInstLower::lowerInstruction(), llvm::DiagnosticInfoMIROptimization::MachineArgument::MachineArgument(), llvm::operator<<(), llvm::SMSchedule::print(), llvm::MachineBasicBlock::print(), false::Chain::str(), and llvm::MachineFunction::verify().
print() [2/2]
void MachineInstr::print (raw_ostream & OS, ModuleSlotTracker & MST, bool IsStandalone = true, bool SkipOpers = false, bool SkipDebugLoc = false, bool AddNewLine = true, const TargetInstrInfo * TII = nullptr) const
Definition at line 1472 of file MachineInstr.cpp.
References llvm::InlineAsm::AD_ATT, llvm::InlineAsm::AD_Intel, assert(), llvm::InlineAsm::Constraint_es, llvm::InlineAsm::Constraint_i, llvm::InlineAsm::Constraint_m, llvm::InlineAsm::Constraint_o, llvm::InlineAsm::Constraint_Q, llvm::InlineAsm::Constraint_R, llvm::InlineAsm::Constraint_S, llvm::InlineAsm::Constraint_T, llvm::InlineAsm::Constraint_Um, llvm::InlineAsm::Constraint_Un, llvm::InlineAsm::Constraint_Uq, llvm::InlineAsm::Constraint_Us, llvm::InlineAsm::Constraint_Ut, llvm::InlineAsm::Constraint_Uv, llvm::InlineAsm::Constraint_Uy, llvm::InlineAsm::Constraint_v, llvm::InlineAsm::Constraint_X, llvm::InlineAsm::Constraint_Z, llvm::InlineAsm::Constraint_ZC, llvm::InlineAsm::Constraint_Zy, Context, llvm::dyn_cast(), llvm::numbers::e, llvm::InlineAsm::Extra_HasSideEffects, llvm::InlineAsm::Extra_IsAlignStack, llvm::InlineAsm::Extra_IsConvergent, llvm::InlineAsm::Extra_MayLoad, llvm::InlineAsm::Extra_MayStore, findTiedOperandIdx(), FmAfn, FmArcp, FmContract, FmNoInfs, FmNoNans, FmNsz, FmReassoc, FrameDestroy, FrameSetup, llvm::Function::getContext(), getDebugLoc(), getFlag(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), getHeapAllocMarker(), llvm::MachineOperand::getImm(), getInlineAsmDialect(), llvm::InlineAsm::getKind(), llvm::InlineAsm::getMemoryConstraintID(), llvm::MachineOperand::getMetadata(), getMFIfAvailable(), llvm::MCInstrInfo::getName(), llvm::InlineAsm::getNumOperandRegisters(), getNumOperands(), getOpcode(), getOperand(), getPostInstrSymbol(), getPreInstrSymbol(), llvm::TargetRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), getTypeToPrint(), hasComplexRegisterTies(), llvm::InlineAsm::hasRegClassConstraint(), isCFIInstruction(), isDebugLabel(), isDebugValue(), llvm::MachineOperand::isDef(), IsExact, llvm::MachineOperand::isImm(), llvm::InlineAsm::isImmKind(), llvm::MachineOperand::isImplicit(), isIndirectDebugValue(), isInlineAsm(), llvm::InlineAsm::isMemKind(), llvm::MachineOperand::isMetadata(), isOperandSubregIdx(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isTied(), llvm::InlineAsm::isUseOperandTiedToDef(), llvm::InlineAsm::Kind_Clobber, llvm::InlineAsm::Kind_Imm, llvm::InlineAsm::Kind_Mem, llvm::InlineAsm::Kind_RegDef, llvm::InlineAsm::Kind_RegDefEarlyClobber, llvm::InlineAsm::Kind_RegUse, memoperands(), memoperands_empty(), llvm::InlineAsm::MIOp_AsmString, llvm::InlineAsm::MIOp_ExtraInfo, llvm::InlineAsm::MIOp_FirstOperand, NoFPExcept, NoSWrap, NoUWrap, llvm::DebugLoc::print(), llvm::MachineOperand::print(), llvm::Metadata::printAsOperand(), llvm::MachineOperand::printSubRegIdx(), llvm::MachineOperand::printSymbol(), TRI, and tryToGetTargetInfo().
readsRegister()
bool llvm::MachineInstr::readsRegister (Register Reg, const TargetRegisterInfo * TRI = nullptr) const inline
Return true if the MachineInstr reads the specified register.
If TargetRegisterInfo is passed, then it also checks if there is a read of a super-register. This does not count partial redefines of virtual registers as reads: reg1024:6 = OP.
Definition at line 1188 of file MachineInstr.h.
References findRegisterUseOperandIdx(), and TRI.
Referenced by areCFlagsAccessedBetweenInstrs(), canInstrSubstituteCmpInstr(), checkAndUpdateCPSRKill(), checkAndUpdateEFLAGSKill(), checkCCKill(), llvm::TargetSchedModel::computeOutputLatency(), ContainsReg(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::createX86FixupSetCC(), CriticalPathStep(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::RegBankSelect::getAnalysisUsage(), llvm::HexagonInstrInfo::getCompoundOpcode(), getImplicitSPRUseForDPRUse(), llvm::AArch64InstrInfo::getOutliningCandidateInfo(), llvm::AArch64InstrInfo::getOutliningType(), llvm::X86InstrInfo::getOutliningType(), llvm::X86InstrInfo::getPartialRegUpdateClearance(), hasRAWHazard(), hasWriteToReadDep(), imposeStackOrdering(), INITIALIZE_PASS(), isCompareZero(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), isLiveOut(), isSafeToMove(), isUnsafeToMoveAcross(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::SIInstrInfo::mayReadEXEC(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), scavengeVReg(), llvm::ARMBaseInstrInfo::setExecutionDomain(), and tryFoldInst().
readsVirtualRegister()
bool llvm::MachineInstr::readsVirtualRegister (Register Reg) const inline
Return true if the MachineInstr reads the specified virtual register.
Take into account that a partial define is a read-modify-write operation.
Definition at line 1196 of file MachineInstr.h.
References readsWritesVirtualRegister(), and Reg.
Referenced by llvm::LiveRangeEdit::eraseVirtReg(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::X86InstrInfo::getPartialRegUpdateClearance(), isCoalescable(), and llvm::SplitEditor::leaveIntvAfter().
readsWritesVirtualRegister()
std::pair< bool, bool > MachineInstr::readsWritesVirtualRegister (Register Reg, SmallVectorImpl< unsigned > * Ops = nullptr) const
Return a pair of bools (reads, writes) indicating if this instruction reads or writes Reg.
readsWritesVirtualRegister - Return a pair of bools (reads, writes) indicating if this instruction reads or writes Reg.
This also considers partial defines. If Ops is not null, all operand indices for Reg are added.
This also considers partial defines.
Definition at line 963 of file MachineInstr.cpp.
References llvm::numbers::e, getNumOperands(), getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Reg.
Referenced by llvm::LiveRangeEdit::eraseVirtReg(), readsVirtualRegister(), and llvm::VirtRegAuxInfo::weightCalcHelper().
registerDefIsDead()
bool llvm::MachineInstr::registerDefIsDead (Register Reg, const TargetRegisterInfo * TRI = nullptr) const inline
Returns true if the register is dead in this machine instruction.
If TargetRegisterInfo is passed, then it also checks if there is a dead def of a super-register.
Definition at line 1233 of file MachineInstr.h.
References findRegisterDefOperandIdx(), findRegisterUseOperandIdx(), hasRegisterImplicitUseOperand(), isKill(), and TRI.
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDeps(), createPHIsForSelects(), llvm::X86InstrInfo::optimizeCompareInstr(), and transferDeadCC().
removeFromBundle()
MachineInstr * MachineInstr::removeFromBundle ()
Unlink this instruction from its basic block and return it without deleting it.
If the instruction is part of a bundle, the other instructions in the bundle remain bundled.
Definition at line 664 of file MachineInstr.cpp.
References assert(), getParent(), and llvm::MachineBasicBlock::remove_instr().
removeFromParent()
MachineInstr * MachineInstr::removeFromParent ()
Unlink 'this' from the containing basic block, and return it without deleting it.
This function can not be used on bundled instructions, use removeFromBundle() to remove individual instructions from a bundle.
Definition at line 659 of file MachineInstr.cpp.
References assert(), getParent(), and llvm::MachineBasicBlock::remove().
Referenced by eraseDeadBBsAndChildren(), findUncondBrI(), llvm::Localizer::getAnalysisUsage(), hasArgumentDef(), INITIALIZE_PASS(), isLoadStoreThatCanHandleDisplacement(), llvm::SIInstrInfo::legalizeOperands(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), and unstackifyVRegsUsedInSplitBB().
RemoveOperand()
void MachineInstr::RemoveOperand (unsigned OpNo)
Erase an operand from an instruction, leaving it with one fewer operand than it started with.
RemoveOperand - Erase an operand from an instruction, leaving it with one fewer operand than it started with.
Definition at line 295 of file MachineInstr.cpp.
References assert(), llvm::MachineFunction::createMIExtraInfo(), llvm::numbers::e, getNumOperands(), isReg(), moveOperands(), N, llvm::MachineRegisterInfo::removeRegOperandFromUseList(), llvm::ArrayRef< T >::size(), and untieRegOperand().
Referenced by addRegisterDead(), addRegisterKilled(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), appendEndToFunction(), llvm::SIInstrInfo::buildExtractSubRegOrImm(), llvm::createSIWholeQuadModePass(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), eraseGPOpnd(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), expandSHXDROT(), llvm::SIInstrInfo::FoldImmediate(), llvm::MipsInstrInfo::genInstrWithNewOpc(), getCompareSourceReg(), getLeaOP(), getRegsUsedByPHIs(), INITIALIZE_PASS(), isCompareZero(), llvm::SIInstrInfo::moveToVALU(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::PeelSingleBlockLoop(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), removeModOperands(), removeOperands(), llvm::PPCInstrInfo::replaceInstrOperandWithImm(), llvm::PPCInstrInfo::replaceInstrWithLI(), llvm::rewriteARMFrameIndex(), llvm::rewriteT2FrameIndex(), setDebugLoc(), llvm::ARMBaseInstrInfo::setExecutionDomain(), shrinkScalarCompare(), stripExtraCopyOperands(), swapMIOperands(), tieOpsIfNeeded(), tryConstantFoldOp(), tryFoldInst(), llvm::tryFoldSPUpdateIntoPushPop(), tryToFoldACImm(), updateOperand(), and X86SelectAddress().
setAsmPrinterFlag()
void llvm::MachineInstr::setAsmPrinterFlag (uint8_t Flag) inline
Set a flag for the AsmPrinter.
Definition at line 297 of file MachineInstr.h.
Referenced by performCustomAdjustments().
setDebugLoc()
void llvm::MachineInstr::setDebugLoc (DebugLoc dl) inline
Replace current source information with new such.
Avoid using this, the constructor argument is preferable.
Definition at line 1563 of file MachineInstr.h.
References addMemOperand(), assert(), cloneInstrSymbols(), cloneMemRefs(), cloneMergedMemRefs(), copyFlagsFromInstruction(), copyIRFlags(), dropMemRefs(), llvm::DebugLoc::hasTrivialDestructor(), I, mergeFlagsWith(), RemoveOperand(), setHeapAllocMarker(), setMemRefs(), setPostInstrSymbol(), setPreInstrSymbol(), and llvm::ARMBuildAttrs::Symbol.
Referenced by definesFullReg(), expandLoadStackGuard(), INITIALIZE_PASS(), isCopyFeedingInvariantStore(), isRegUsedByPhiNodes(), and performSink().
setDesc()
void llvm::MachineInstr::setDesc (const MCInstrDesc & tid) inline
Replace the instruction descriptor (thus opcode) of the current instruction with a new one.
Definition at line 1559 of file MachineInstr.h.
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::CombinerHelper::applyCombineExtendingLoads(), BBIsJumpedOver(), canInstrSubstituteCmpInstr(), canTurnIntoCOPY(), llvm::HexagonPacketizerList::cleanUpDotCur(), llvm::SIInstrInfo::commuteInstructionImpl(), convertImplicitDefToConstZero(), createPHIsForSelects(), llvm::createSIWholeQuadModePass(), llvm::HexagonPacketizerList::demoteToDotOld(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::LiveRangeEdit::eraseVirtReg(), Expand2AddrKreg(), Expand2AddrUndef(), expandLoadStackGuard(), expandMOV32r1(), ExpandMOVImmSExti8(), expandNOVLXLoad(), expandNOVLXStore(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::SystemZInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), expandSHXDROT(), llvm::PPCInstrInfo::expandVSXMemPseudo(), expandXorFP(), llvm::fixStackStores(), llvm::SystemZInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getCompareSourceReg(), getInsertVecEltOpInfo(), getLeaOP(), getLogicalBitOpcode(), getRegClassFromGRPhysReg(), getRetpolineSymbol(), getUnconditionalBrDisp(), getVectorSHLImm(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), InsertLDR_STR(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), isCompareZero(), isConstant(), isFullCopyOf(), IsMovepDestinationRegPair(), IsUnconditionalJump(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::LegalizerHelper::lowerBitCount(), matchSwap(), llvm::SIInstrInfo::moveToVALU(), mutateCopyOp(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), performCustomAdjustments(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::HexagonPacketizerList::promoteToDotCur(), llvm::HexagonPacketizerList::promoteToDotNew(), RemoveDeadAddBetweenLEAAndJT(), removeTerminatorBit(), llvm::PPCInstrInfo::replaceInstrWithLI(), llvm::HexagonInstrInfo::reversePredSense(), llvm::rewriteAArch64FrameIndex(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), selectCopy(), selectMergeValues(), selectUnmergeValues(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::AMDGPUInstructionSelector::setupMF(), shouldUseAndMask(), shrinkScalarCompare(), shrinkScalarLogicOp(), sizeToSubRegIndex(), llvm::SITargetLowering::splitKillBlock(), swapMIOperands(), llvm::SystemZInstrInfo::SystemZInstrInfo(), tieOpsIfNeeded(), tryAddToFoldList(), tryConstantFoldOp(), tryToFoldACImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), updateOperand(), llvm::LegalizerHelper::widenScalar(), and X86SelectAddress().
setFlag()
void llvm::MachineInstr::setFlag (MIFlag Flag) inline
Set a MI flag.
Definition at line 317 of file MachineInstr.h.
Referenced by bundleWithPred(), bundleWithSucc(), llvm::InstrEmitter::EmitDbgLabel(), FuseInst(), llvm::MIBundleBuilder::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineInstrBuilder::setMIFlag(), toString(), and transferMIFlag().
setFlags()
void llvm::MachineInstr::setFlags (unsigned flags) inline
Definition at line 321 of file MachineInstr.h.
References BundledPred, BundledSucc, and llvm::BitmaskEnumDetail::Mask().
Referenced by addImplicitDefUseOperands(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::lowerFCopySign(), and llvm::MachineInstrBuilder::setMIFlags().
setHeapAllocMarker()
void MachineInstr::setHeapAllocMarker (MachineFunction & MF, MDNode * MD)
Set a marker on instructions that denotes where we should create and emit heap alloc site labels.
This waits until after instruction selection and optimizations to create the label, so it should still work if the instruction is removed or duplicated.
Definition at line 497 of file MachineInstr.cpp.
References getHeapAllocMarker(), getPostInstrSymbol(), getPreInstrSymbol(), and memoperands().
Referenced by cloneInstrSymbols(), llvm::FastISel::lowerCallTo(), and setDebugLoc().
setMemRefs()
void MachineInstr::setMemRefs (MachineFunction & MF, ArrayRef< MachineMemOperand *> MemRefs)
Assign this MachineInstr's memory reference descriptor list.
Unlike other methods, this will allocate them into a new array associated with the provided MachineFunction.
Definition at line 363 of file MachineInstr.cpp.
References dropMemRefs(), llvm::ArrayRef< T >::empty(), getHeapAllocMarker(), getPostInstrSymbol(), and getPreInstrSymbol().
Referenced by addMemOperand(), cloneMemRefs(), cloneMergedMemRefs(), llvm::TargetInstrInfo::foldMemoryOperand(), setDebugLoc(), and llvm::MachineInstrBuilder::setMemRefs().
setPhysRegsDeadExcept()
void MachineInstr::setPhysRegsDeadExcept (ArrayRef< Register > UsedRegs, const TargetRegisterInfo & TRI)
Mark every physreg used by this instruction as dead except those in the UsedRegs list.
On instructions with register mask operands, also add implicit-def operands for all registers in UsedRegs.
Definition at line 1951 of file MachineInstr.cpp.
References addRegisterDefined(), llvm::ArrayRef< T >::begin(), E, llvm::ArrayRef< T >::end(), I, llvm::Register::isPhysical(), llvm::none_of(), operands(), and llvm::TargetRegisterInfo::regsOverlap().
Referenced by isRegTiedToDefOperand(), llvm::FastISel::lowerCallTo(), and llvm::FastISel::selectPatchpoint().
setPostInstrSymbol()
void MachineInstr::setPostInstrSymbol (MachineFunction & MF, MCSymbol * Symbol)
Set a symbol that will be emitted just after the instruction itself.
Setting this to a null pointer will remove any such symbol.
FIXME: This is not fully implemented yet.
Definition at line 482 of file MachineInstr.cpp.
References getHeapAllocMarker(), getPostInstrSymbol(), getPreInstrSymbol(), and memoperands().
Referenced by llvm::ModuloScheduleTestAnnotater::annotate(), cloneInstrSymbols(), isEFLAGSLive(), and setDebugLoc().
setPreInstrSymbol()
void MachineInstr::setPreInstrSymbol (MachineFunction & MF, MCSymbol * Symbol)
Set a symbol that will be emitted just prior to the instruction itself.
Setting this to a null pointer will remove any such symbol.
FIXME: This is not fully implemented yet.
Definition at line 467 of file MachineInstr.cpp.
References getHeapAllocMarker(), getPostInstrSymbol(), getPreInstrSymbol(), and memoperands().
Referenced by cloneInstrSymbols(), llvm::createX86RetpolineThunksPass(), llvm::X86InstrInfo::getSerializableDirectMachineOperandTargetFlags(), and setDebugLoc().
setRegisterDefReadUndef()
void MachineInstr::setRegisterDefReadUndef (Register Reg, bool IsUndef = true)
Mark all subregister defs of register Reg with the undef flag.
This function is used when we determined to have a subregister def in an otherwise undefined super register.
Definition at line 1925 of file MachineInstr.cpp.
References operands().
Referenced by llvm::RegisterOperands::adjustLaneLiveness(), isRegTiedToDefOperand(), and llvm::LiveIntervals::shrinkToUses().
substituteRegister()
void MachineInstr::substituteRegister (Register FromReg, Register ToReg, unsigned SubIdx, const TargetRegisterInfo & RegInfo)
Replace all occurrences of FromReg with ToReg:SubIdx, properly composing subreg indices where necessary.
Definition at line 1139 of file MachineInstr.cpp.
References llvm::TargetRegisterInfo::getSubReg(), llvm::Register::isPhysicalRegister(), and operands().
Referenced by llvm::LiveRangeEdit::eraseVirtReg(), INITIALIZE_PASS(), llvm::CoalescerPair::isCoalescable(), isRegTiedToDefOperand(), llvm::X86InstrInfo::reMaterialize(), llvm::ARMBaseInstrInfo::reMaterialize(), and llvm::TargetInstrInfo::reMaterialize().
tieOperands()
void MachineInstr::tieOperands (unsigned DefIdx, unsigned UseIdx)
Add a tie between the register operands at DefIdx and UseIdx.
tieOperands - Mark operands at DefIdx and UseIdx as tied to each other.
The tie will cause the register allocator to ensure that the two operands are assigned the same physical register.
Tied operands are managed automatically for explicit operands in the MCInstrDesc. This method is for exceptional cases like inline asm.
Use and def operands can be tied together, indicated by a non-zero TiedTo field. TiedTo can have these values:
0: Operand is not tied to anything. 1 to TiedMax-1: Tied to getOperand(TiedTo-1). TiedMax: Tied to an operand >= TiedMax-1.
The tied def must be one of the first TiedMax operands on a normal instruction. INLINEASM instructions allow more tied defs.
Definition at line 1050 of file MachineInstr.cpp.
References assert(), getOperand(), llvm::MachineOperand::isDef(), isInlineAsm(), llvm::MachineOperand::isTied(), llvm::MachineOperand::isUse(), and TiedMax.
Referenced by addOperand(), llvm::constrainSelectedInstRegOperands(), llvm::createSIAddIMGInitPass(), findRegisterDefOperand(), findSingleRegDef(), llvm::SystemZInstrInfo::FoldImmediate(), INITIALIZE_PASS(), isImplicitOperandIn(), matchSwap(), operator<<(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), shrinkScalarCompare(), shrinkScalarLogicOp(), llvm::SystemZInstrInfo::SystemZInstrInfo(), and tieOpsIfNeeded().
unbundleFromPred()
void MachineInstr::unbundleFromPred ()
Break bundle above this instruction.
Definition at line 750 of file MachineInstr.cpp.
References assert(), BundledPred, BundledSucc, clearFlag(), llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >::getIterator(), and isBundledWithPred().
Referenced by isBundledWithSucc(), moveInstrOut(), and unbundleSingleMI().
unbundleFromSucc()
void MachineInstr::unbundleFromSucc ()
Break bundle below this instruction.
Definition at line 759 of file MachineInstr.cpp.
References assert(), BundledPred, BundledSucc, clearFlag(), llvm::ilist_node_impl< ilist_detail::compute_node_options< MachineInstr, Options... >::type >::getIterator(), and isBundledWithSucc().
Referenced by isBundledWithSucc(), and unbundleSingleMI().
untieRegOperand()
void llvm::MachineInstr::untieRegOperand (unsigned OpIdx) inline
Break any tie involving OpIdx.
Definition at line 1643 of file MachineInstr.h.
References addImplicitDefUseOperands(), changeDebugValuesDefReg(), collectDebugValues(), findTiedOperandIdx(), getOperand(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isTied().
Referenced by llvm::createSIWholeQuadModePass(), findStartOfTree(), llvm::SIInstrInfo::FoldImmediate(), RemoveOperand(), shrinkScalarCompare(), and tryAddToFoldList().
uses() [1/2]
iterator_range<mop_iterator> llvm::MachineInstr::uses () inline
Returns a range that includes all operands that are register uses.
This may include unrelated operands which are not register uses.
Definition at line 525 of file MachineInstr.h.
References getNumExplicitDefs(), llvm::make_range(), operands_begin(), and operands_end().
Referenced by addRegsToSet(), AnyAliasLiveIn(), ContainsReg(), llvm::createSIWholeQuadModePass(), findSingleRegDef(), handleNormalInst(), INITIALIZE_PASS(), instReadsReg(), isCoalescable(), isCrossCopy(), isNopCopy(), isValidClauseInst(), loadSRsrcFromVGPR(), llvm::CombinerHelper::matchCombineConcatVectors(), split(), and false::Chain::str().
uses() [2/2]
iterator_range<const_mop_iterator> llvm::MachineInstr::uses () const inline
Returns a range that includes all operands that are register uses.
This may include unrelated operands which are not register uses.
Definition at line 529 of file MachineInstr.h.
References getNumExplicitDefs(), llvm::make_range(), operands_begin(), and operands_end().
usesCustomInsertionHook()
bool llvm::MachineInstr::usesCustomInsertionHook (QueryType Type = IgnoreBundle) const inline
Return true if this instruction requires custom insertion support when the DAG scheduler is inserting it into a machine basic block.
If this is true for the instruction, it basically means that it is a pseudo instruction used at SelectionDAG time that is expanded out into magic code by the target when MachineInstrs are formed.
If this is true, the TargetLoweringInfo::InsertAtEndOfBasicBlock method is used to insert this into the MachineBasicBlock.
Definition at line 938 of file MachineInstr.h.
References hasProperty(), and llvm::MCID::UsesCustomInserter.
Referenced by INITIALIZE_PASS().
Friends And Related Function Documentation
ilist_callback_traits< MachineBasicBlock >
friend struct ilist_callback_traits< MachineBasicBlock > friend
Definition at line 249 of file MachineInstr.h.
ilist_traits< MachineInstr >
friend struct ilist_traits< MachineInstr > friend
Definition at line 248 of file MachineInstr.h.
MachineFunction
friend class MachineFunction friend
Definition at line 263 of file MachineInstr.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineInstr.h
lib/CodeGen/MachineInstr.cpp