LLVM: llvm::orc::AsynchronousSymbolQuery Class Reference
llvm::orc::AsynchronousSymbolQuery Class Reference
A symbol query that returns results via a callback when results are ready.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
AsynchronousSymbolQuery (const SymbolLookupSet &Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete)
Create a query for the given symbols.
void notifySymbolMetRequiredState (const SymbolStringPtr &Name, JITEvaluatedSymbol Sym)
Notify the query that a requested symbol has reached the required state.
void dropSymbol (const SymbolStringPtr &Name)
Remove a symbol from the query.
bool isComplete () const
Returns true if all symbols covered by this query have been resolved.
void handleComplete ()
Call the NotifyComplete callback.
Friends
class ExecutionSession
class JITDylib
class JITSymbolResolverAdapter
Detailed Description
A symbol query that returns results via a callback when results are ready.
makes a callback when all symbols are available.
Definition at line 712 of file Core.h.
Constructor & Destructor Documentation
AsynchronousSymbolQuery()
llvm::orc::AsynchronousSymbolQuery::AsynchronousSymbolQuery (const SymbolLookupSet & Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete)
Create a query for the given symbols.
The NotifyComplete callback will be called once all queried symbols reach the given minimum state.
Definition at line 355 of file Core.cpp.
References assert(), llvm::orc::Resolved, and llvm::orc::SymbolLookupSet::size().
Member Function Documentation
dropSymbol()
void llvm::orc::AsynchronousSymbolQuery::dropSymbol (const SymbolStringPtr & Name) inline
Remove a symbol from the query.
This is used to drop weakly referenced symbols that are not found.
Definition at line 731 of file Core.h.
References assert().
handleComplete()
void llvm::orc::AsynchronousSymbolQuery::handleComplete ()
Call the NotifyComplete callback.
This should only be called if all symbols covered by the query have reached the specified state.
Definition at line 379 of file Core.cpp.
References assert().
isComplete()
bool llvm::orc::AsynchronousSymbolQuery::isComplete () const inline
Returns true if all symbols covered by this query have been resolved.
Definition at line 740 of file Core.h.
References Name.
notifySymbolMetRequiredState()
void llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState (const SymbolStringPtr & Name, JITEvaluatedSymbol Sym)
Notify the query that a requested symbol has reached the required state.
Definition at line 369 of file Core.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::orc::lookupWithLegacyFn().
Friends And Related Function Documentation
ExecutionSession
friend class ExecutionSession friend
Definition at line 713 of file Core.h.
JITDylib
friend class JITDylib friend
Definition at line 714 of file Core.h.
JITSymbolResolverAdapter
friend class JITSymbolResolverAdapter friend
Definition at line 715 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp