LLVM: llvm::PPCRegisterInfo Class Reference
llvm::PPCRegisterInfo Class Reference
#include "Target/PowerPC/PPCRegisterInfo.h"
Public Member Functions
PPCRegisterInfo (const PPCTargetMachine &TM)
unsigned getMappedIdxOpcForImmOpc (unsigned ImmOpcode) const
getMappedIdxOpcForImmOpc - Return the mapped index form load/store opcode for a given imm form load/store opcode ImmFormOpcode.
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
getPointerRegClass - Return the register class to use to hold pointers.
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC, const MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
const MCPhysReg * getCalleeSavedRegsViaCopy (const MachineFunction *MF) const
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
const uint32_t * getNoPreservedMask () const override
void adjustStackMapLiveOutMask (uint32_t *Mask) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool isCallerPreservedPhysReg (unsigned PhysReg, const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
We require the register scavenger.
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
bool requiresVirtualBaseRegisters (const MachineFunction &MF) const override
void lowerDynamicAlloc (MachineBasicBlock::iterator II) const
lowerDynamicAlloc - Generate the code for allocating an object in the current frame.
void lowerDynamicAreaOffset (MachineBasicBlock::iterator II) const
void lowerCRSpilling (MachineBasicBlock::iterator II, unsigned FrameIndex) const
lowerCRSpilling - Generate the code for spilling a CR register.
void lowerCRRestore (MachineBasicBlock::iterator II, unsigned FrameIndex) const
void lowerCRBitSpilling (MachineBasicBlock::iterator II, unsigned FrameIndex) const
void lowerCRBitRestore (MachineBasicBlock::iterator II, unsigned FrameIndex) const
void lowerVRSAVESpilling (MachineBasicBlock::iterator II, unsigned FrameIndex) const
void lowerVRSAVERestore (MachineBasicBlock::iterator II, unsigned FrameIndex) const
bool hasReservedSpillSlot (const MachineFunction &MF, unsigned Reg, int &FrameIdx) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool needsFrameBaseReg (MachineInstr *MI, int64_t Offset) const override
Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
void materializeFrameBaseRegister (MachineBasicBlock *MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const override
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx at the beginning of the basic block.
void resolveFrameIndex (MachineInstr &MI, unsigned BaseReg, int64_t Offset) const override
bool isFrameOffsetLegal (const MachineInstr *MI, unsigned BaseReg, int64_t Offset) const override
Register getFrameRegister (const MachineFunction &MF) const override
Register getBaseRegister (const MachineFunction &MF) const
bool hasBasePointer (const MachineFunction &MF) const
Static Public Member Functions
static const char * stripRegisterPrefix (const char *RegName)
stripRegisterPrefix - This method strips the character prefix from a register name so that only the number is left.
Detailed Description
Definition at line 57 of file PPCRegisterInfo.h.
Constructor & Destructor Documentation
PPCRegisterInfo()
PPCRegisterInfo::PPCRegisterInfo (const PPCTargetMachine & TM)
Definition at line 80 of file PPCRegisterInfo.cpp.
References llvm::ARM_MB::LD.
Member Function Documentation
adjustStackMapLiveOutMask()
void PPCRegisterInfo::adjustStackMapLiveOutMask (uint32_t * Mask) const override
Definition at line 266 of file PPCRegisterInfo.cpp.
References llvm::NVPTX::PTXCvtMode::RM.
Referenced by getMappedIdxOpcForImmOpc().
eliminateFrameIndex()
void PPCRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 1012 of file PPCRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::PPCISD::DYNALLOC, llvm::PPCISD::DYNAREAOFFSET, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::ISD::FrameIndex, llvm::DebugLoc::get(), getBaseRegister(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), getFrameRegister(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), getOffsetONFromFION(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::Function::hasFnAttribute(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, is64Bit(), llvm::MachineInstr::isInlineAsm(), llvm::isInt< 16 >(), llvm::PPCTargetMachine::isPPC64(), llvm::isUInt< 8 >(), llvm::RegState::Kill, lowerCRBitRestore(), lowerCRBitSpilling(), lowerCRRestore(), lowerCRSpilling(), lowerDynamicAlloc(), lowerDynamicAreaOffset(), lowerVRSAVERestore(), lowerVRSAVESpilling(), MI, offsetMinAlign(), llvm::MachineInstr::setDesc(), and TII.
Referenced by requiresVirtualBaseRegisters().
getBaseRegister()
Register PPCRegisterInfo::getBaseRegister (const MachineFunction & MF) const
Definition at line 1173 of file PPCRegisterInfo.cpp.
References getFrameRegister(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::TargetMachine::isPositionIndependent(), llvm::PPCTargetMachine::isPPC64(), and llvm::PPCSubtarget::isSVR4ABI().
Referenced by llvm::PPCFrameLowering::determineCalleeSaves(), eliminateFrameIndex(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), needsFrameBaseReg(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::replaceFPWithRealFP(), and requiresVirtualBaseRegisters().
getCalleeSavedRegs()
const MCPhysReg * PPCRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 142 of file PPCRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, llvm::CallingConv::Cold, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasSPE(), llvm::PPCSubtarget::hasVSX(), llvm::MachineRegisterInfo::isAllocatable(), llvm::PPCSubtarget::isDarwinABI(), and llvm::PPCTargetMachine::isPPC64().
Referenced by getMappedIdxOpcForImmOpc(), and llvm::PPCFrameLowering::replaceFPWithRealFP().
getCalleeSavedRegsViaCopy()
const MCPhysReg * PPCRegisterInfo::getCalleeSavedRegsViaCopy (const MachineFunction * MF) const
Definition at line 198 of file PPCRegisterInfo.cpp.
References assert(), llvm::CallingConv::CXX_FAST_TLS, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), getReservedRegs(), llvm::MachineFunction::getSubtarget(), llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCTargetMachine::isPPC64(), llvm::PPCFunctionInfo::isSplitCSR(), and llvm::BitVector::test().
Referenced by getMappedIdxOpcForImmOpc(), llvm::PPCTargetLowering::insertCopiesSplitCSR(), and truncateScalarIntegerArg().
getCallPreservedMask()
const uint32_t * PPCRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 223 of file PPCRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, assert(), llvm::CallingConv::Cold, llvm::MachineFunction::getSubtarget(), llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasSPE(), llvm::PPCSubtarget::hasVSX(), llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isDarwinABI(), and llvm::PPCTargetMachine::isPPC64().
Referenced by getMappedIdxOpcForImmOpc().
getFrameRegister()
Register PPCRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 1164 of file PPCRegisterInfo.cpp.
References llvm::PPCFrameLowering::hasFP(), and llvm::PPCTargetMachine::isPPC64().
Referenced by eliminateFrameIndex(), getBaseRegister(), and requiresVirtualBaseRegisters().
getLargestLegalSuperClass()
const TargetRegisterClass * PPCRegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC, const MachineFunction & MF) const override
Definition at line 452 of file PPCRegisterInfo.cpp.
References EnableGPRToVecSpills, llvm::TargetRegisterInfo::getLargestLegalSuperClass(), llvm::MachineFunction::getSubtarget(), llvm::PPCSubtarget::hasP8Vector(), llvm::PPCSubtarget::hasP9Vector(), llvm::PPCSubtarget::hasVSX(), and llvm::PPCTargetMachine::isELFv2ABI().
Referenced by getMappedIdxOpcForImmOpc().
getMappedIdxOpcForImmOpc()
unsigned llvm::PPCRegisterInfo::getMappedIdxOpcForImmOpc (unsigned ImmOpcode) const inline
getMappedIdxOpcForImmOpc - Return the mapped index form load/store opcode for a given imm form load/store opcode ImmFormOpcode.
FIXME: move this to PPCInstrInfo class.
Definition at line 67 of file PPCRegisterInfo.h.
References adjustStackMapLiveOutMask(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getCalleeSavedRegs(), getCalleeSavedRegsViaCopy(), getCallPreservedMask(), getLargestLegalSuperClass(), getNoPreservedMask(), getPointerRegClass(), getRegPressureLimit(), getReservedRegs(), isCallerPreservedPhysReg(), and llvm::BitmaskEnumDetail::Mask().
getNoPreservedMask()
const uint32_t * PPCRegisterInfo::getNoPreservedMask () const override
Definition at line 262 of file PPCRegisterInfo.cpp.
Referenced by llvm::PPCTargetLowering::emitEHSjLjSetJmp(), and getMappedIdxOpcForImmOpc().
getPointerRegClass()
const TargetRegisterClass * PPCRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
getPointerRegClass - Return the register class to use to hold pointers.
This is used for addressing modes.
Definition at line 126 of file PPCRegisterInfo.cpp.
References llvm::PPCTargetMachine::isPPC64().
Referenced by getMappedIdxOpcForImmOpc().
getRegPressureLimit()
unsigned PPCRegisterInfo::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const override
Definition at line 417 of file PPCRegisterInfo.cpp.
References llvm::TargetRegisterClass::getID(), and llvm::PPCFrameLowering::hasFP().
Referenced by getMappedIdxOpcForImmOpc().
getReservedRegs()
BitVector PPCRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 271 of file PPCRegisterInfo.cpp.
References assert(), llvm::sys::path::begin(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::PPCSubtarget::hasAltivec(), hasBasePointer(), llvm::MachineFunction::hasInlineAsm(), I, llvm::ARM_PROC::IE, llvm::PPCSubtarget::is32BitELFABI(), llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isDarwinABI(), llvm::TargetMachine::isPositionIndependent(), llvm::PPCTargetMachine::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), R2, llvm::NVPTX::PTXCvtMode::RM, and llvm::PPCFunctionInfo::usesTOCBasePtr().
Referenced by getCalleeSavedRegsViaCopy(), getMappedIdxOpcForImmOpc(), and isCallerPreservedPhysReg().
hasBasePointer()
bool PPCRegisterInfo::hasBasePointer (const MachineFunction & MF) const
Definition at line 1187 of file PPCRegisterInfo.cpp.
References AlwaysBasePointer, EnableBasePointer, and needsFrameBaseReg().
Referenced by llvm::PPCFrameLowering::canUseAsEpilogue(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), eliminateFrameIndex(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), getBaseRegister(), getReservedRegs(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::replaceFPWithRealFP(), and requiresVirtualBaseRegisters().
hasReservedSpillSlot()
bool PPCRegisterInfo::hasReservedSpillSlot (const MachineFunction & MF, unsigned Reg, int & FrameIdx) const override
Definition at line 942 of file PPCRegisterInfo.cpp.
References llvm::PPCFunctionInfo::getCRSpillFrameIndex(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::PPCTargetMachine::isPPC64(), and llvm::PPCSubtarget::isSVR4ABI().
Referenced by requiresVirtualBaseRegisters().
isCallerPreservedPhysReg()
bool PPCRegisterInfo::isCallerPreservedPhysReg (unsigned PhysReg, const MachineFunction & MF) const override
Definition at line 392 of file PPCRegisterInfo.cpp.
References assert(), llvm::MachineFunction::getFrameInfo(), getReservedRegs(), llvm::MachineFunction::getSubtarget(), llvm::Register::isPhysicalRegister(), llvm::PPCTargetMachine::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), StackPtrConst, and llvm::BitVector::test().
Referenced by getMappedIdxOpcForImmOpc().
isFrameOffsetLegal()
bool PPCRegisterInfo::isFrameOffsetLegal (const MachineInstr * MI, unsigned BaseReg, int64_t Offset) const override
Definition at line 1294 of file PPCRegisterInfo.cpp.
References assert(), llvm::MachineOperand::getImm(), getOffsetONFromFION(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isFI(), llvm::isInt< 16 >(), and offsetMinAlign().
Referenced by needsFrameBaseReg(), and requiresVirtualBaseRegisters().
lowerCRBitRestore()
void PPCRegisterInfo::lowerCRBitRestore (MachineBasicBlock::iterator II, unsigned FrameIndex) const
Definition at line 839 of file PPCRegisterInfo.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::erase(), llvm::DebugLoc::get(), llvm::getCRFromCRBit(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::RegState::Implicit, llvm::PPCTargetMachine::isPPC64(), llvm::RegState::Kill, llvm::PPCISD::MFOCRF, MI, Reg, and TII.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
lowerCRBitSpilling()
void PPCRegisterInfo::lowerCRBitSpilling (MachineBasicBlock::iterator II, unsigned FrameIndex) const
Definition at line 730 of file PPCRegisterInfo.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::erase(), llvm::ISD::FrameIndex, llvm::DebugLoc::get(), llvm::getCRFromCRBit(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::PPCSubtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::RegState::Implicit, llvm::MipsISD::Ins, llvm::PPCSubtarget::isISA3_0(), llvm::MachineOperand::isKill(), llvm::PPCTargetMachine::isPPC64(), llvm::RegState::Kill, llvm::MachineInstr::killsRegister(), MaxCRBitSpillDist, llvm::PPCISD::MFOCRF, MI, Reg, llvm::MachineBasicBlock::rend(), TII, TRI, and llvm::RegState::Undef.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
lowerCRRestore()
void PPCRegisterInfo::lowerCRRestore (MachineBasicBlock::iterator II, unsigned FrameIndex) const
Definition at line 687 of file PPCRegisterInfo.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::erase(), llvm::DebugLoc::get(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::PPCTargetMachine::isPPC64(), llvm::RegState::Kill, MI, Reg, and TII.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
lowerCRSpilling()
void PPCRegisterInfo::lowerCRSpilling (MachineBasicBlock::iterator II, unsigned FrameIndex) const
lowerCRSpilling - Generate the code for spilling a CR register.
Instead of reserving a whole register (R0), we scrounge for one here. This generates code like this:
mfcr rA ; Move the conditional register into GPR rA. rlwinm rA, rA, SB, 0, 31 ; Shift the bits left so they are in CR0's slot. stw rA, FI ; Store rA to the frame.
Definition at line 642 of file PPCRegisterInfo.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::erase(), llvm::ISD::FrameIndex, llvm::DebugLoc::get(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isKill(), llvm::PPCTargetMachine::isPPC64(), llvm::RegState::Kill, llvm::PPCISD::MFOCRF, MI, Reg, and TII.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
lowerDynamicAlloc()
void PPCRegisterInfo::lowerDynamicAlloc (MachineBasicBlock::iterator II) const
lowerDynamicAlloc - Generate the code for allocating an object in the current frame.
The sequence of code will be in the general form
addi R0, SP, #frameSize ; get the address of the previous frame stwxu R0, SP, Rnegsize ; add and update the SP with the negated size addi Rnew, SP, #maxCalFrameSize ; get the top of the allocation
Definition at line 493 of file PPCRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ISD::AND, assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::erase(), llvm::DebugLoc::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::isInt< 16 >(), llvm::MachineOperand::isKill(), llvm::PPCTargetMachine::isPPC64(), llvm::RegState::Kill, llvm::ARM_MB::LD, MI, Reg, and TII.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
lowerDynamicAreaOffset()
void PPCRegisterInfo::lowerDynamicAreaOffset (MachineBasicBlock::iterator II) const
Definition at line 611 of file PPCRegisterInfo.cpp.
References llvm::BuildMI(), llvm::MachineBasicBlock::erase(), llvm::DebugLoc::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), is64Bit(), llvm::PPCTargetMachine::isPPC64(), MI, and TII.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
lowerVRSAVERestore()
void PPCRegisterInfo::lowerVRSAVERestore (MachineBasicBlock::iterator II, unsigned FrameIndex) const
Definition at line 915 of file PPCRegisterInfo.cpp.
References llvm::addFrameReference(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::erase(), llvm::DebugLoc::get(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::RegState::Kill, MI, Reg, and TII.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
lowerVRSAVESpilling()
void PPCRegisterInfo::lowerVRSAVESpilling (MachineBasicBlock::iterator II, unsigned FrameIndex) const
Definition at line 889 of file PPCRegisterInfo.cpp.
References llvm::addFrameReference(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::erase(), llvm::ISD::FrameIndex, llvm::DebugLoc::get(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::getKillRegState(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isKill(), llvm::RegState::Kill, MI, Reg, and TII.
Referenced by eliminateFrameIndex(), and requiresVirtualBaseRegisters().
materializeFrameBaseRegister()
void PPCRegisterInfo::materializeFrameBaseRegister (MachineBasicBlock * MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const override
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx at the beginning of the basic block.
Definition at line 1249 of file PPCRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachineBasicBlock::end(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MipsISD::Ins, llvm::PPCTargetMachine::isPPC64(), MRI, and TII.
Referenced by needsFrameBaseReg(), and requiresVirtualBaseRegisters().
needsFrameBaseReg()
bool PPCRegisterInfo::needsFrameBaseReg (MachineInstr * MI, int64_t Offset) const override
Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
Used by LocalStackFrameAllocation to determine which frame index references it should create new base registers for.
Definition at line 1204 of file PPCRegisterInfo.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::PPCFrameLowering::determineFrameLayout(), getBaseRegister(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), isFrameOffsetLegal(), and materializeFrameBaseRegister().
Referenced by hasBasePointer(), and requiresVirtualBaseRegisters().
requiresFrameIndexScavenging()
bool PPCRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const override
Definition at line 347 of file PPCRegisterInfo.cpp.
References llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), Info, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), llvm::MachineFrameInfo::isFixedObjectIndex(), offsetMinAlignForOpcode(), and Reg.
Referenced by llvm::PPCFrameLowering::canUseAsEpilogue(), and requiresRegisterScavenging().
requiresRegisterScavenging()
bool llvm::PPCRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
We require the register scavenger.
Definition at line 98 of file PPCRegisterInfo.h.
References requiresFrameIndexScavenging().
requiresVirtualBaseRegisters()
bool llvm::PPCRegisterInfo::requiresVirtualBaseRegisters (const MachineFunction & MF) const inline override
Definition at line 108 of file PPCRegisterInfo.h.
References eliminateFrameIndex(), llvm::ISD::FrameIndex, getBaseRegister(), getFrameRegister(), hasBasePointer(), hasReservedSpillSlot(), isFrameOffsetLegal(), lowerCRBitRestore(), lowerCRBitSpilling(), lowerCRRestore(), lowerCRSpilling(), lowerDynamicAlloc(), lowerDynamicAreaOffset(), lowerVRSAVERestore(), lowerVRSAVESpilling(), materializeFrameBaseRegister(), MI, needsFrameBaseReg(), Reg, and resolveFrameIndex().
resolveFrameIndex()
void PPCRegisterInfo::resolveFrameIndex (MachineInstr & MI, unsigned BaseReg, int64_t Offset) const override
Definition at line 1270 of file PPCRegisterInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getNumOperands(), getOffsetONFromFION(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isFI(), MRI, and TII.
Referenced by requiresVirtualBaseRegisters().
stripRegisterPrefix()
static const char* llvm::PPCRegisterInfo::stripRegisterPrefix (const char * RegName) inline static
stripRegisterPrefix - This method strips the character prefix from a register name so that only the number is left.
Used by for linux asm.
Definition at line 152 of file PPCRegisterInfo.h.
Referenced by llvm::PPCInstPrinter::printOperand().
trackLivenessAfterRegAlloc()
bool llvm::PPCRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline override
Definition at line 104 of file PPCRegisterInfo.h.
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCRegisterInfo.h
lib/Target/PowerPC/PPCRegisterInfo.cpp