LLVM: llvm::object::MachOBindEntry Class Reference
llvm::object::MachOBindEntry Class Reference
MachOBindEntry encapsulates the current state in the decompression of binding opcodes.
#include "llvm/Object/MachO.h"
Public Types
enum Kind { Kind::Regular, Kind::Lazy, Kind::Weak }
Public Member Functions
MachOBindEntry (Error *Err, const MachOObjectFile *O, ArrayRef< uint8_t > Opcodes, bool is64Bit, MachOBindEntry::Kind)
int32_t segmentIndex () const
uint64_t segmentOffset () const
StringRef typeName () const
StringRef symbolName () const
uint32_t flags () const
int64_t addend () const
int ordinal () const
StringRef segmentName () const
StringRef sectionName () const
uint64_t address () const
bool operator== (const MachOBindEntry &) const
void moveNext ()
Friends
class MachOObjectFile
Detailed Description
MachOBindEntry encapsulates the current state in the decompression of binding opcodes.
This allows you to iterate through the compressed table of bindings using: Error Err; for (const llvm::object::MachOBindEntry &Entry : Obj->bindTable(&Err)) { } if (Err) { report error ...
Definition at line 211 of file MachO.h.
Member Enumeration Documentation
Kind
enum llvm::object::MachOBindEntry::Kind strong
Enumerator
Regular
Lazy
Weak
Definition at line 213 of file MachO.h.
Constructor & Destructor Documentation
MachOBindEntry()
MachOBindEntry::MachOBindEntry (Error * Err, const MachOObjectFile * O, ArrayRef< uint8_t > Opcodes, bool is64Bit, MachOBindEntry::Kind BK)
Definition at line 3454 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), and moveNext().
Member Function Documentation
addend()
int64_t MachOBindEntry::addend () const
Definition at line 3964 of file MachOObjectFile.cpp.
address()
uint64_t MachOBindEntry::address () const
Definition at line 3984 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::BindRebaseAddress(), and SegmentOffset().
flags()
uint32_t MachOBindEntry::flags () const
Definition at line 3966 of file MachOObjectFile.cpp.
moveNext()
void MachOBindEntry::moveNext ()
Definition at line 3470 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::begin(), llvm::MachO::BIND_IMMEDIATE_MASK, llvm::MachO::BIND_OPCODE_ADD_ADDR_ULEB, llvm::MachO::BIND_OPCODE_DO_BIND, llvm::MachO::BIND_OPCODE_DO_BIND_ADD_ADDR_IMM_SCALED, llvm::MachO::BIND_OPCODE_DO_BIND_ADD_ADDR_ULEB, llvm::MachO::BIND_OPCODE_DO_BIND_ULEB_TIMES_SKIPPING_ULEB, llvm::MachO::BIND_OPCODE_DONE, llvm::MachO::BIND_OPCODE_MASK, llvm::MachO::BIND_OPCODE_SET_ADDEND_SLEB, llvm::MachO::BIND_OPCODE_SET_DYLIB_ORDINAL_IMM, llvm::MachO::BIND_OPCODE_SET_DYLIB_ORDINAL_ULEB, llvm::MachO::BIND_OPCODE_SET_DYLIB_SPECIAL_IMM, llvm::MachO::BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB, llvm::MachO::BIND_OPCODE_SET_SYMBOL_TRAILING_FLAGS_IMM, llvm::MachO::BIND_OPCODE_SET_TYPE_IMM, llvm::MachO::BIND_SPECIAL_DYLIB_FLAT_LOOKUP, llvm::MachO::BIND_SYMBOL_FLAGS_NON_WEAK_DEFINITION, llvm::MachO::BIND_TYPE_TEXT_PCREL32, llvm::object::MachOObjectFile::BindEntryCheckSegAndOffsets(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::decodeSLEB128(), llvm::decodeULEB128(), llvm::ArrayRef< T >::end(), error, llvm::format(), llvm::object::MachOObjectFile::getLibraryCount(), Lazy, malformedError(), P, readULEB128(), SegmentOffset(), llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName, llvm::Twine::utohexstr(), and Weak.
Referenced by MachOBindEntry().
operator==()
bool MachOBindEntry::operator== (const MachOBindEntry & Other) const
Definition at line 3988 of file MachOObjectFile.cpp.
References assert(), and llvm::ArrayRef< T >::data().
ordinal()
int MachOBindEntry::ordinal () const
Definition at line 3968 of file MachOObjectFile.cpp.
sectionName()
StringRef MachOBindEntry::sectionName () const
Definition at line 3978 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::BindRebaseSectionName(), and SegmentOffset().
segmentIndex()
int32_t MachOBindEntry::segmentIndex () const
Definition at line 3946 of file MachOObjectFile.cpp.
segmentName()
StringRef MachOBindEntry::segmentName () const
Definition at line 3972 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::BindRebaseSegmentName().
segmentOffset()
uint64_t MachOBindEntry::segmentOffset () const
Definition at line 3948 of file MachOObjectFile.cpp.
References SegmentOffset().
symbolName()
StringRef MachOBindEntry::symbolName () const
Definition at line 3962 of file MachOObjectFile.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
typeName()
StringRef MachOBindEntry::typeName () const
Definition at line 3950 of file MachOObjectFile.cpp.
References llvm::MachO::BIND_TYPE_POINTER, llvm::MachO::BIND_TYPE_TEXT_ABSOLUTE32, and llvm::MachO::BIND_TYPE_TEXT_PCREL32.
Friends And Related Function Documentation
MachOObjectFile
friend class MachOObjectFile friend
Definition at line 235 of file MachO.h.
The documentation for this class was generated from the following files:
include/llvm/Object/MachO.h
lib/Object/MachOObjectFile.cpp