LLVM: llvm::xray::FunctionRecord Class Reference
llvm::xray::FunctionRecord Class Reference
#include "llvm/XRay/FDRRecords.h"
Public Member Functions
FunctionRecord ()
FunctionRecord (RecordTypes K, int32_t F, uint32_t D)
RecordTypes recordType () const
int32_t functionId () const
uint32_t delta () const
Error apply (RecordVisitor &V) override
Public Member Functions inherited from llvm::xray::Record
Record (const Record &)=delete
Record (Record &&)=delete
Record & operator= (const Record &)=delete
Record & operator= (Record &&)=delete
Record (RecordKind T)
RecordKind getRecordType () const
virtual ~Record ()=default
Static Public Member Functions
static bool classof (const Record *R)
Static Public Member Functions inherited from llvm::xray::Record
static StringRef kindToString (RecordKind K)
Friends
class RecordInitializer
Additional Inherited Members
Public Types inherited from llvm::xray::Record
enum RecordKind {
RecordKind::RK_Metadata, RecordKind::RK_Metadata_BufferExtents, RecordKind::RK_Metadata_WallClockTime, RecordKind::RK_Metadata_NewCPUId,
RecordKind::RK_Metadata_TSCWrap, RecordKind::RK_Metadata_CustomEvent, RecordKind::RK_Metadata_CustomEventV5, RecordKind::RK_Metadata_CallArg,
RecordKind::RK_Metadata_PIDEntry, RecordKind::RK_Metadata_NewBuffer, RecordKind::RK_Metadata_EndOfBuffer, RecordKind::RK_Metadata_TypedEvent,
RecordKind::RK_Metadata_LastMetadata, RecordKind::RK_Function
}
Detailed Description
Definition at line 372 of file FDRRecords.h.
Constructor & Destructor Documentation
FunctionRecord() [1/2]
llvm::xray::FunctionRecord::FunctionRecord () inline
Definition at line 381 of file FDRRecords.h.
FunctionRecord() [2/2]
llvm::xray::FunctionRecord::FunctionRecord (RecordTypes K, int32_t F, uint32_t D) inline explicit
Definition at line 383 of file FDRRecords.h.
Member Function Documentation
apply()
Error llvm::xray::FunctionRecord::apply (RecordVisitor & V) override virtual
Implements llvm::xray::Record.
Definition at line 27 of file FDRRecords.cpp.
References llvm::xray::RecordVisitor::visit().
classof()
static bool llvm::xray::FunctionRecord::classof (const Record * R) inline static
Definition at line 394 of file FDRRecords.h.
References llvm::xray::Record::getRecordType(), and llvm::xray::Record::RK_Function.
delta()
uint32_t llvm::xray::FunctionRecord::delta () const inline
Definition at line 390 of file FDRRecords.h.
References llvm::xray::Record::apply().
Referenced by llvm::xray::RecordPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), and llvm::xray::TraceExpander::visit().
functionId()
int32_t llvm::xray::FunctionRecord::functionId () const inline
Definition at line 389 of file FDRRecords.h.
References FuncId.
Referenced by llvm::xray::RecordPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), and llvm::xray::TraceExpander::visit().
recordType()
RecordTypes llvm::xray::FunctionRecord::recordType () const inline
Definition at line 388 of file FDRRecords.h.
Referenced by llvm::xray::RecordPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), and llvm::xray::TraceExpander::visit().
Friends And Related Function Documentation
RecordInitializer
friend class RecordInitializer friend
Definition at line 376 of file FDRRecords.h.
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecords.h
lib/XRay/FDRRecords.cpp