LLVM: llvm::WarnMissedTransformationsPass Class Reference
llvm::WarnMissedTransformationsPass Class Reference
#include "llvm/Transforms/Scalar/WarnMissedTransforms.h"
Public Member Functions
WarnMissedTransformationsPass ()
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< WarnMissedTransformationsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 24 of file WarnMissedTransforms.h.
Constructor & Destructor Documentation
WarnMissedTransformationsPass()
llvm::WarnMissedTransformationsPass::WarnMissedTransformationsPass () inline explicit
Definition at line 27 of file WarnMissedTransforms.h.
References llvm::createWarnMissedTransformationsPass(), F(), llvm::initializeWarnMissedTransformationsLegacyPass(), and run().
Member Function Documentation
run()
PreservedAnalyses WarnMissedTransformationsPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 93 of file WarnMissedTransforms.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::PreservedAnalyses::all(), F(), llvm::PassRegistry::getPassRegistry(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::Function::hasOptNone(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeWarnMissedTransformationsLegacyPass(), runOnFunction(), llvm::AnalysisUsage::setPreservesAll(), and warnAboutLeftoverTransformations().
Referenced by WarnMissedTransformationsPass().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/WarnMissedTransforms.h
lib/Transforms/Scalar/WarnMissedTransforms.cpp