LLVM: llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT > Class Template Reference
llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT > Class Template Reference
#include "llvm/Analysis/IntervalIterator.h"
Public Types
using iterator_category = std::forward_iterator_tag
Public Member Functions
IntervalIterator ()=default
IntervalIterator (Function *M, bool OwnMemory)
IntervalIterator (IntervalIterator &&x)
IntervalIterator (IntervalPartition &IP, bool OwnMemory)
~IntervalIterator ()
bool operator== (const IntervalIterator &x) const
bool operator!= (const IntervalIterator &x) const
const Interval * operator* () const
Interval * operator* ()
const Interval * operator-> () const
Interval * operator-> ()
IntervalIterator & operator++ ()
IntervalIterator operator++ (int)
Detailed Description
template<class NodeTy, class OrigContainer_t, class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>>
class llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >
Definition at line 89 of file IntervalIterator.h.
Member Typedef Documentation
iterator_category
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> using llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::iterator_category = std::forward_iterator_tag
Definition at line 97 of file IntervalIterator.h.
Constructor & Destructor Documentation
IntervalIterator() [1/4]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::IntervalIterator () default
IntervalIterator() [2/4]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::IntervalIterator (Function * M, bool OwnMemory) inline
Definition at line 101 of file IntervalIterator.h.
References llvm::Function::front(), and llvm_unreachable.
IntervalIterator() [3/4]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::IntervalIterator (IntervalIterator< NodeTy, OrigContainer_t, GT, IGT > && x) inline
Definition at line 108 of file IntervalIterator.h.
IntervalIterator() [4/4]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::IntervalIterator (IntervalPartition & IP, bool OwnMemory) inline
Definition at line 114 of file IntervalIterator.h.
References llvm::IntervalPartition::getRootInterval(), and llvm_unreachable.
~IntervalIterator()
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::~IntervalIterator () inline
Definition at line 121 of file IntervalIterator.h.
References llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator*().
Member Function Documentation
operator!=()
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> bool llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator!= (const IntervalIterator< NodeTy, OrigContainer_t, GT, IGT > & x) const inline
Definition at line 132 of file IntervalIterator.h.
operator*() [1/2]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> const Interval* llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator* () const inline
Definition at line 134 of file IntervalIterator.h.
Referenced by llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator->(), and llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::~IntervalIterator().
operator*() [2/2]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> Interval* llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator* () inline
Definition at line 135 of file IntervalIterator.h.
operator++() [1/2]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> IntervalIterator& llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++ () inline
Definition at line 139 of file IntervalIterator.h.
References assert(), llvm::getSourceGraphNode(), and llvm::succ_end().
operator++() [2/2]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> IntervalIterator llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++ (int) inline
Definition at line 162 of file IntervalIterator.h.
References llvm::addNodeToInterval(), assert(), llvm::Interval::contains(), E, llvm::getNodeHeader(), llvm::getSourceGraphNode(), I, llvm::Interval::isSuccessor(), llvm::sys::fs::remove(), llvm::succ_begin(), and llvm::Interval::Successors.
operator->() [1/2]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> const Interval* llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator-> () const inline
Definition at line 136 of file IntervalIterator.h.
References llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator*().
operator->() [2/2]
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> Interval* llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator-> () inline
Definition at line 137 of file IntervalIterator.h.
References llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator*().
operator==()
template<class NodeTy , class OrigContainer_t , class GT = GraphTraits<NodeTy *>, class IGT = GraphTraits<Inverse<NodeTy *>>> bool llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator== (const IntervalIterator< NodeTy, OrigContainer_t, GT, IGT > & x) const inline
Definition at line 129 of file IntervalIterator.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/IntervalIterator.h