LLVM: llvm::MCSubRegIndexIterator Class Reference
llvm::MCSubRegIndexIterator Class Reference
Iterator that enumerates the sub-registers of a Reg and the associated sub-register indices.
#include "llvm/MC/MCRegisterInfo.h"
Public Member Functions
MCSubRegIndexIterator (MCRegister Reg, const MCRegisterInfo *MCRI)
Constructs an iterator that traverses subregisters and their associated subregister indices.
MCRegister getSubReg () const
Returns current sub-register.
unsigned getSubRegIndex () const
Returns sub-register index of the current sub-register.
bool isValid () const
Returns true if this iterator is not yet at the end.
void operator++ ()
Moves to the next position.
Detailed Description
Iterator that enumerates the sub-registers of a Reg and the associated sub-register indices.
Definition at line 600 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
MCSubRegIndexIterator()
llvm::MCSubRegIndexIterator::MCSubRegIndexIterator (MCRegister Reg, const MCRegisterInfo * MCRI) inline
Constructs an iterator that traverses subregisters and their associated subregister indices.
Definition at line 607 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::get(), and llvm::MCRegisterDesc::SubRegIndices.
Member Function Documentation
getSubReg()
MCRegister llvm::MCSubRegIndexIterator::getSubReg () const inline
Returns current sub-register.
Definition at line 613 of file MCRegisterInfo.h.
Referenced by llvm::LivePhysRegs::available(), and llvm::rdf::Liveness::resetKills().
getSubRegIndex()
unsigned llvm::MCSubRegIndexIterator::getSubRegIndex () const inline
Returns sub-register index of the current sub-register.
Definition at line 618 of file MCRegisterInfo.h.
Referenced by llvm::LivePhysRegs::available(), llvm::HexagonBlockRanges::HexagonBlockRanges(), and llvm::rdf::Liveness::resetKills().
isValid()
bool llvm::MCSubRegIndexIterator::isValid () const inline
Returns true if this iterator is not yet at the end.
Definition at line 623 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::LivePhysRegs::available(), llvm::HexagonBlockRanges::expandToSubRegs(), llvm::HexagonBlockRanges::HexagonBlockRanges(), llvm::rdf::Liveness::resetKills(), and llvm::rdf::CopyPropagation::run().
operator++()
void llvm::MCSubRegIndexIterator::operator++ () inline
Moves to the next position.
Definition at line 626 of file MCRegisterInfo.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCRegisterInfo.h