LLVM: llvm::RuntimeDyldChecker::MemoryRegionInfo Class Reference
llvm::RuntimeDyldChecker::MemoryRegionInfo Class Reference
#include "llvm/ExecutionEngine/RuntimeDyldChecker.h"
Public Member Functions
MemoryRegionInfo ()=default
MemoryRegionInfo (StringRef Content, JITTargetAddress TargetAddress)
Constructor for symbols/sections with content.
MemoryRegionInfo (uint64_t Size, JITTargetAddress TargetAddress)
Constructor for zero-fill symbols/sections.
bool isZeroFill () const
Returns true if this is a zero-fill symbol/section.
void setContent (StringRef Content)
Set the content for this memory region.
void setZeroFill (uint64_t Size)
Set a zero-fill length for this memory region.
StringRef getContent () const
Returns the content for this section if there is any.
uint64_t getZeroFillLength () const
Returns the zero-fill length for this section.
void setTargetAddress (JITTargetAddress TargetAddress)
Set the target address for this region.
JITTargetAddress getTargetAddress () const
Return the target address for this region.
Detailed Description
Definition at line 76 of file RuntimeDyldChecker.h.
Constructor & Destructor Documentation
MemoryRegionInfo() [1/3]
llvm::RuntimeDyldChecker::MemoryRegionInfo::MemoryRegionInfo () default
MemoryRegionInfo() [2/3]
llvm::RuntimeDyldChecker::MemoryRegionInfo::MemoryRegionInfo (StringRef Content, JITTargetAddress TargetAddress) inline
Constructor for symbols/sections with content.
Definition at line 81 of file RuntimeDyldChecker.h.
MemoryRegionInfo() [3/3]
llvm::RuntimeDyldChecker::MemoryRegionInfo::MemoryRegionInfo (uint64_t Size, JITTargetAddress TargetAddress) inline
Constructor for zero-fill symbols/sections.
Definition at line 86 of file RuntimeDyldChecker.h.
Member Function Documentation
getContent()
StringRef llvm::RuntimeDyldChecker::MemoryRegionInfo::getContent () const inline
Returns the content for this section if there is any.
Definition at line 109 of file RuntimeDyldChecker.h.
References assert(), and isZeroFill().
getTargetAddress()
JITTargetAddress llvm::RuntimeDyldChecker::MemoryRegionInfo::getTargetAddress () const inline
Return the target address for this region.
Definition at line 127 of file RuntimeDyldChecker.h.
getZeroFillLength()
uint64_t llvm::RuntimeDyldChecker::MemoryRegionInfo::getZeroFillLength () const inline
Returns the zero-fill length for this section.
Definition at line 115 of file RuntimeDyldChecker.h.
References assert(), and isZeroFill().
isZeroFill()
bool llvm::RuntimeDyldChecker::MemoryRegionInfo::isZeroFill () const inline
Returns true if this is a zero-fill symbol/section.
Definition at line 90 of file RuntimeDyldChecker.h.
References assert().
Referenced by getContent(), and getZeroFillLength().
setContent()
void llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent (StringRef Content) inline
Set the content for this memory region.
Definition at line 96 of file RuntimeDyldChecker.h.
References assert(), llvm::StringRef::data(), and llvm::StringRef::size().
setTargetAddress()
void llvm::RuntimeDyldChecker::MemoryRegionInfo::setTargetAddress (JITTargetAddress TargetAddress) inline
Set the target address for this region.
Definition at line 121 of file RuntimeDyldChecker.h.
References assert().
setZeroFill()
void llvm::RuntimeDyldChecker::MemoryRegionInfo::setZeroFill (uint64_t Size) inline
Set a zero-fill length for this memory region.
Definition at line 103 of file RuntimeDyldChecker.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/RuntimeDyldChecker.h