LLVM: llvm::GVNExpression::VariableExpression Class Reference
llvm::GVNExpression::VariableExpression Class Reference final
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Member Functions
VariableExpression (Value *V)
VariableExpression ()=delete
VariableExpression (const VariableExpression &)=delete
VariableExpression & operator= (const VariableExpression &)=delete
Value * getVariableValue () const
void setVariableValue (Value *V)
bool equals (const Expression &Other) const override
hash_code getHashValue () const override
void printInternal (raw_ostream &OS, bool PrintEType) const override
Public Member Functions inherited from llvm::GVNExpression::Expression
Expression (ExpressionType ET=ET_Base, unsigned O=~2U)
Expression (const Expression &)=delete
Expression & operator= (const Expression &)=delete
virtual ~Expression ()
bool operator!= (const Expression &Other) const
bool operator== (const Expression &Other) const
hash_code getComputedHash () const
virtual bool exactlyEquals (const Expression &Other) const
unsigned getOpcode () const
void setOpcode (unsigned opcode)
ExpressionType getExpressionType () const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::Expression
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
Detailed Description
Definition at line 549 of file GVNExpression.h.
Constructor & Destructor Documentation
VariableExpression() [1/3]
llvm::GVNExpression::VariableExpression::VariableExpression (Value * V) inline
Definition at line 554 of file GVNExpression.h.
References llvm::GVNExpression::Expression::operator=().
VariableExpression() [2/3]
llvm::GVNExpression::VariableExpression::VariableExpression () delete
VariableExpression() [3/3]
llvm::GVNExpression::VariableExpression::VariableExpression (const VariableExpression &) delete
Member Function Documentation
classof()
static bool llvm::GVNExpression::VariableExpression::classof (const Expression * EB) inline static
Definition at line 559 of file GVNExpression.h.
References llvm::GVNExpression::ET_Variable, and llvm::GVNExpression::Expression::getExpressionType().
equals()
bool llvm::GVNExpression::VariableExpression::equals (const Expression & Other) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 566 of file GVNExpression.h.
References llvm::SystemZISD::OC.
getHashValue()
hash_code llvm::GVNExpression::VariableExpression::getHashValue () const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 571 of file GVNExpression.h.
References llvm::GVNExpression::Expression::getHashValue(), llvm::Value::getType(), and llvm::hash_combine().
getVariableValue()
Value* llvm::GVNExpression::VariableExpression::getVariableValue () const inline
Definition at line 563 of file GVNExpression.h.
operator=()
VariableExpression& llvm::GVNExpression::VariableExpression::operator= (const VariableExpression &) delete
printInternal()
void llvm::GVNExpression::VariableExpression::printInternal (raw_ostream & OS, bool PrintEType) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 577 of file GVNExpression.h.
References llvm::GVNExpression::Expression::printInternal().
setVariableValue()
void llvm::GVNExpression::VariableExpression::setVariableValue (Value * V) inline
Definition at line 564 of file GVNExpression.h.
The documentation for this class was generated from the following file:
include/llvm/Transforms/Scalar/GVNExpression.h