LLVM: llvm::SCEVTraversal< SV > Class Template Reference
llvm::SCEVTraversal< SV > Class Template Reference
Visit all nodes in the expression tree using worklist traversal.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
SCEVTraversal (SV &V)
void visitAll (const SCEV *Root)
Detailed Description
template<typename SV>
class llvm::SCEVTraversal< SV >
Visit all nodes in the expression tree using worklist traversal.
Visitor implements: // return true to follow this node. bool follow(const SCEV *S); // return true to terminate the search. bool isDone();
Definition at line 561 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVTraversal()
template<typename SV> llvm::SCEVTraversal< SV >::SCEVTraversal (SV & V) inline
Definition at line 572 of file ScalarEvolutionExpressions.h.
Member Function Documentation
visitAll()
template<typename SV> void llvm::SCEVTraversal< SV >::visitAll (const SCEV * Root) inline
Definition at line 574 of file ScalarEvolutionExpressions.h.
References llvm::SmallVectorBase::empty(), llvm::SCEVUDivExpr::getLHS(), llvm::SCEVUDivExpr::getRHS(), llvm::SCEV::getSCEVType(), llvm_unreachable, llvm::SmallVectorImpl< T >::pop_back_val(), push(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, and llvm::scZeroExtend.
Referenced by containsConstantInAddMulChain(), IsAvailableOnEntry(), sizeOfSCEV(), and llvm::visitAll().
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h