LLVM: llvm::VPBuilder::VPInsertPoint Class Reference
llvm::VPBuilder::VPInsertPoint Class Reference
InsertPoint - A saved insertion point.
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Public Member Functions
VPInsertPoint ()=default
Creates a new insertion point which doesn't point to anything.
VPInsertPoint (VPBasicBlock *InsertBlock, VPBasicBlock::iterator InsertPoint)
Creates a new insertion point at the given location.
bool isSet () const
Returns true if this insert point is set.
VPBasicBlock * getBlock () const
VPBasicBlock::iterator getPoint () const
Detailed Description
InsertPoint - A saved insertion point.
Definition at line 67 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
VPInsertPoint() [1/2]
llvm::VPBuilder::VPInsertPoint::VPInsertPoint () default
Creates a new insertion point which doesn't point to anything.
Referenced by llvm::VPBuilder::InsertPointGuard::~InsertPointGuard().
VPInsertPoint() [2/2]
llvm::VPBuilder::VPInsertPoint::VPInsertPoint (VPBasicBlock * InsertBlock, VPBasicBlock::iterator InsertPoint) inline
Creates a new insertion point at the given location.
Definition at line 76 of file LoopVectorizationPlanner.h.
Member Function Documentation
getBlock()
VPBasicBlock* llvm::VPBuilder::VPInsertPoint::getBlock () const inline
Definition at line 82 of file LoopVectorizationPlanner.h.
Referenced by llvm::VPBuilder::restoreIP().
getPoint()
VPBasicBlock::iterator llvm::VPBuilder::VPInsertPoint::getPoint () const inline
Definition at line 83 of file LoopVectorizationPlanner.h.
Referenced by llvm::VPBuilder::restoreIP().
isSet()
bool llvm::VPBuilder::VPInsertPoint::isSet () const inline
Returns true if this insert point is set.
Definition at line 80 of file LoopVectorizationPlanner.h.
Referenced by llvm::VPBuilder::restoreIP().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h