LLVM: llvm::DWARFDebugNames::NameTableEntry Class Reference
llvm::DWARFDebugNames::NameTableEntry Class Reference
A single entry in the Name Table (DWARF v5 sect.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
NameTableEntry (const DataExtractor &StrData, uint32_t Index, uint64_t StringOffset, uint64_t EntryOffset)
uint32_t getIndex () const
Return the index of this name in the parent Name Index.
uint64_t getStringOffset () const
Returns the offset of the name of the described entities.
const char * getString () const
Return the string referenced by this name table entry or nullptr if the string offset is not valid.
uint64_t getEntryOffset () const
Returns the offset of the first Entry in the list.
Detailed Description
A single entry in the Name Table (DWARF v5 sect.
6.1.1.4.6) of the Name Index.
Definition at line 353 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
NameTableEntry()
llvm::DWARFDebugNames::NameTableEntry::NameTableEntry (const DataExtractor & StrData, uint32_t Index, uint64_t StringOffset, uint64_t EntryOffset) inline
Definition at line 361 of file DWARFAcceleratorTable.h.
Member Function Documentation
getEntryOffset()
uint64_t llvm::DWARFDebugNames::NameTableEntry::getEntryOffset () const inline
Returns the offset of the first Entry in the list.
Definition at line 380 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::dump(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), and getNames().
getIndex()
uint32_t llvm::DWARFDebugNames::NameTableEntry::getIndex () const inline
Return the index of this name in the parent Name Index.
Definition at line 367 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), and getNames().
getString()
const char* llvm::DWARFDebugNames::NameTableEntry::getString () const inline
Return the string referenced by this name table entry or nullptr if the string offset is not valid.
Definition at line 374 of file DWARFAcceleratorTable.h.
References llvm::DataExtractor::getCStr().
Referenced by llvm::DWARFDebugNames::dump(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), and getNames().
getStringOffset()
uint64_t llvm::DWARFDebugNames::NameTableEntry::getStringOffset () const inline
Returns the offset of the name of the described entities.
Definition at line 370 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getHashArrayEntry().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h