LLVM: llvm::object::ImportDirectoryEntryRef Class Reference
llvm::object::ImportDirectoryEntryRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
ImportDirectoryEntryRef ()=default
ImportDirectoryEntryRef (const coff_import_directory_table_entry *Table, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const ImportDirectoryEntryRef &Other) const
void moveNext ()
imported_symbol_iterator imported_symbol_begin () const
imported_symbol_iterator imported_symbol_end () const
iterator_range< imported_symbol_iterator > imported_symbols () const
imported_symbol_iterator lookup_table_begin () const
imported_symbol_iterator lookup_table_end () const
iterator_range< imported_symbol_iterator > lookup_table_symbols () const
std::error_code getName (StringRef &Result) const
std::error_code getImportLookupTableRVA (uint32_t &Result) const
std::error_code getImportAddressTableRVA (uint32_t &Result) const
std::error_code getImportTableEntry (const coff_import_directory_table_entry *&Result) const
Detailed Description
Definition at line 1080 of file COFF.h.
Constructor & Destructor Documentation
ImportDirectoryEntryRef() [1/2]
llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef () default
ImportDirectoryEntryRef() [2/2]
llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef (const coff_import_directory_table_entry * Table, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 1083 of file COFF.h.
References getName(), llvm::object::operator==(), and Other.
Member Function Documentation
getImportAddressTableRVA()
std::error_code ImportDirectoryEntryRef::getImportAddressTableRVA (uint32_t & Result) const
Definition at line 1396 of file COFFObjectFile.cpp.
References llvm::object::DelayImportDirectoryEntryRef::operator==().
getImportLookupTableRVA()
std::error_code ImportDirectoryEntryRef::getImportLookupTableRVA (uint32_t & Result) const
Definition at line 1390 of file COFFObjectFile.cpp.
getImportTableEntry()
std::error_code ImportDirectoryEntryRef::getImportTableEntry (const coff_import_directory_table_entry *& Result) const
Definition at line 1307 of file COFFObjectFile.cpp.
References llvm::object::getObject().
getName()
std::error_code ImportDirectoryEntryRef::getName (StringRef & Result) const
Definition at line 1380 of file COFFObjectFile.cpp.
imported_symbol_begin()
imported_symbol_iterator ImportDirectoryEntryRef::imported_symbol_begin () const
Definition at line 1349 of file COFFObjectFile.cpp.
References importedSymbolBegin().
imported_symbol_end()
imported_symbol_iterator ImportDirectoryEntryRef::imported_symbol_end () const
Definition at line 1355 of file COFFObjectFile.cpp.
References importedSymbolEnd().
imported_symbols()
iterator_range< imported_symbol_iterator > ImportDirectoryEntryRef::imported_symbols () const
Definition at line 1361 of file COFFObjectFile.cpp.
References llvm::make_range().
lookup_table_begin()
imported_symbol_iterator ImportDirectoryEntryRef::lookup_table_begin () const
Definition at line 1365 of file COFFObjectFile.cpp.
References importedSymbolBegin().
lookup_table_end()
imported_symbol_iterator ImportDirectoryEntryRef::lookup_table_end () const
Definition at line 1370 of file COFFObjectFile.cpp.
References importedSymbolEnd().
lookup_table_symbols()
iterator_range< imported_symbol_iterator > ImportDirectoryEntryRef::lookup_table_symbols () const
Definition at line 1376 of file COFFObjectFile.cpp.
References llvm::make_range().
moveNext()
void ImportDirectoryEntryRef::moveNext ()
Definition at line 1299 of file COFFObjectFile.cpp.
operator==()
bool ImportDirectoryEntryRef::operator== (const ImportDirectoryEntryRef & Other) const
Definition at line 1295 of file COFFObjectFile.cpp.
Referenced by llvm::object::COFFObjectFile::mapDebugSectionName().
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp