LLVM: llvm::objcarc::ARCMDKindCache Class Reference
llvm::objcarc::ARCMDKindCache Class Reference
A cache of MDKinds used by various ARC optimizations.
#include "llvm/Analysis/ObjCARCAnalysisUtils.h"
Public Member Functions
void init (Module *Mod)
unsigned get (ARCMDKindID ID)
Detailed Description
A cache of MDKinds used by various ARC optimizations.
Definition at line 255 of file ObjCARCAnalysisUtils.h.
Member Function Documentation
get()
unsigned llvm::objcarc::ARCMDKindCache::get (ARCMDKindID ID) inline
Definition at line 275 of file ObjCARCAnalysisUtils.h.
References llvm::objcarc::CopyOnEscape, llvm::Module::getContext(), llvm::LLVMContext::getMDKindID(), llvm::objcarc::ImpreciseRelease, llvm_unreachable, and llvm::objcarc::NoObjCARCExceptions.
Referenced by llvm::objcarc::BottomUpPtrState::InitBottomUp(), and llvm::objcarc::TopDownPtrState::MatchWithRelease().
init()
void llvm::objcarc::ARCMDKindCache::init (Module * Mod) inline
Definition at line 268 of file ObjCARCAnalysisUtils.h.
References llvm::None.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ObjCARCAnalysisUtils.h