LLVM: llvm::LibCallsShrinkWrapPass Class Reference
llvm::LibCallsShrinkWrapPass Class Reference
#include "llvm/Transforms/Utils/LibCallsShrinkWrap.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Static Public Member Functions
static StringRef name ()
Static Public Member Functions inherited from llvm::PassInfoMixin< LibCallsShrinkWrapPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 18 of file LibCallsShrinkWrap.h.
Member Function Documentation
name()
static StringRef llvm::LibCallsShrinkWrapPass::name () inline static
Definition at line 20 of file LibCallsShrinkWrap.h.
References F(), and run().
run()
PreservedAnalyses llvm::LibCallsShrinkWrapPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 551 of file LibCallsShrinkWrap.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and runImpl().
Referenced by name().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/LibCallsShrinkWrap.h
lib/Transforms/Utils/LibCallsShrinkWrap.cpp