LLVM: llvm::AppleAccelTableStaticTypeData Class Reference
llvm::AppleAccelTableStaticTypeData Class Reference
Accelerator table data implementation for type accelerator tables with a DIE offset but no actual DIE pointer.
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
AppleAccelTableStaticTypeData (uint32_t Offset, uint16_t Tag, bool ObjCClassIsImplementation, uint32_t QualifiedNameHash)
void emit (AsmPrinter *Asm) const override
void print (raw_ostream &OS) const override
Public Member Functions inherited from llvm::AppleAccelTableStaticOffsetData
AppleAccelTableStaticOffsetData (uint32_t Offset)
Public Member Functions inherited from llvm::AccelTableData
virtual ~AccelTableData ()=default
bool operator< (const AccelTableData &Other) const
Static Public Attributes
static constexpr Atom Atoms []
Static Public Attributes inherited from llvm::AppleAccelTableStaticOffsetData
static constexpr Atom Atoms []
Protected Member Functions
uint64_t order () const override
Protected Attributes
uint32_t QualifiedNameHash
uint16_t Tag
bool ObjCClassIsImplementation
Protected Attributes inherited from llvm::AppleAccelTableStaticOffsetData
uint32_t Offset
Additional Inherited Members
Static Public Member Functions inherited from llvm::AppleAccelTableData
static uint32_t hash (StringRef Buffer)
Detailed Description
Accelerator table data implementation for type accelerator tables with a DIE offset but no actual DIE pointer.
Definition at line 378 of file AccelTable.h.
Constructor & Destructor Documentation
AppleAccelTableStaticTypeData()
llvm::AppleAccelTableStaticTypeData::AppleAccelTableStaticTypeData (uint32_t Offset, uint16_t Tag, bool ObjCClassIsImplementation, uint32_t QualifiedNameHash) inline
Definition at line 380 of file AccelTable.h.
Member Function Documentation
emit()
void AppleAccelTableStaticTypeData::emit (AsmPrinter * Asm) const override virtual
Reimplemented from llvm::AppleAccelTableStaticOffsetData.
Definition at line 609 of file AccelTable.cpp.
References llvm::AppleAccelTableOffsetData::Atoms, llvm::AppleAccelTableTypeData::Atoms, llvm::AppleAccelTableStaticOffsetData::Atoms, Atoms, llvm::AccelTableBase::BucketCount, llvm::dwarf::DW_FLAG_type_implementation, llvm::AsmPrinter::emitInt16(), llvm::AsmPrinter::emitInt32(), llvm::AsmPrinter::emitInt8(), llvm::format(), Magic, print(), llvm::Tag, and llvm::IndexedInstrProf::Version.
order()
uint64_t llvm::AppleAccelTableStaticTypeData::order () const inline override protected virtual
Reimplemented from llvm::AppleAccelTableStaticOffsetData.
Definition at line 398 of file AccelTable.h.
print()
void AppleAccelTableStaticTypeData::print (raw_ostream & OS) const override virtual
Reimplemented from llvm::AppleAccelTableStaticOffsetData.
Definition at line 704 of file AccelTable.cpp.
References llvm::format(), llvm::Tag, and llvm::dwarf::TagString().
Member Data Documentation
Atoms
constexpr AppleAccelTableData::Atom AppleAccelTableStaticTypeData::Atoms static
Initial value:
= {
      Atom(dwarf::DW_ATOM_die_offset, dwarf::DW_FORM_data4),
      Atom(dwarf::DW_ATOM_die_tag, dwarf::DW_FORM_data2),
      Atom(5, dwarf::DW_FORM_data1), Atom(6, dwarf::DW_FORM_data4)}
Definition at line 389 of file AccelTable.h.
Referenced by emit().
ObjCClassIsImplementation
bool llvm::AppleAccelTableStaticTypeData::ObjCClassIsImplementation protected
Definition at line 402 of file AccelTable.h.
QualifiedNameHash
uint32_t llvm::AppleAccelTableStaticTypeData::QualifiedNameHash protected
Definition at line 400 of file AccelTable.h.
Tag
uint16_t llvm::AppleAccelTableStaticTypeData::Tag protected
Definition at line 401 of file AccelTable.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp