LLVM: llvm::DIEString Class Reference
llvm::DIEString Class Reference
A container for string pool string values.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEString (DwarfStringPoolEntryRef S)
StringRef getString () const
Grab the string out of the object.
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit string value.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
SizeOf - Determine size of delta value in bytes.
void print (raw_ostream &O) const
Detailed Description
A container for string pool string values.
This class is used with the DW_FORM_strp and DW_FORM_GNU_str_index forms.
Definition at line 272 of file DIE.h.
Constructor & Destructor Documentation
DIEString()
llvm::DIEString::DIEString (DwarfStringPoolEntryRef S) inline
Definition at line 276 of file DIE.h.
Member Function Documentation
EmitValue()
void DIEString::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit string value.
Definition at line 557 of file DIE.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm_unreachable, and llvm::AsmPrinter::MAI.
getString()
StringRef llvm::DIEString::getString () const inline
Grab the string out of the object.
Definition at line 279 of file DIE.h.
References llvm::DwarfStringPoolEntryRef::getString(), llvm::RISCVFenceField::O, and print().
print()
LLVM_DUMP_METHOD void DIEString::print (raw_ostream & O) const
Definition at line 601 of file DIE.cpp.
SizeOf()
unsigned DIEString::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
SizeOf - Determine size of delta value in bytes.
Definition at line 581 of file DIE.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), LLVM_DUMP_METHOD, llvm_unreachable, and llvm::AsmPrinter::MAI.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp