LLVM: llvm::codeview::Line Class Reference
llvm::codeview::Line Class Reference
#include "llvm/DebugInfo/CodeView/Line.h"
Public Member Functions
Line (int32_t CodeOffset, uint32_t StartLine, uint32_t EndLine, uint16_t StartColumn, uint16_t EndColumn, bool IsStatement)
Line (int32_t CodeOffset, LineInfo LineInf, ColumnInfo ColumnInf)
LineInfo getLineInfo () const
ColumnInfo getColumnInfo () const
int32_t getCodeOffset () const
uint32_t getStartLine () const
uint32_t getLineDelta () const
uint32_t getEndLine () const
uint16_t getStartColumn () const
uint16_t getEndColumn () const
bool isStatement () const
bool isAlwaysStepInto () const
bool isNeverStepInto () const
Detailed Description
Definition at line 91 of file Line.h.
Constructor & Destructor Documentation
Line() [1/2]
llvm::codeview::Line::Line (int32_t CodeOffset, uint32_t StartLine, uint32_t EndLine, uint16_t StartColumn, uint16_t EndColumn, bool IsStatement) inline
Definition at line 98 of file Line.h.
Line() [2/2]
llvm::codeview::Line::Line (int32_t CodeOffset, LineInfo LineInf, ColumnInfo ColumnInf) inline
Definition at line 103 of file Line.h.
Member Function Documentation
getCodeOffset()
int32_t llvm::codeview::Line::getCodeOffset () const inline
Definition at line 110 of file Line.h.
References llvm::codeview::CodeOffset.
getColumnInfo()
ColumnInfo llvm::codeview::Line::getColumnInfo () const inline
Definition at line 108 of file Line.h.
getEndColumn()
uint16_t llvm::codeview::Line::getEndColumn () const inline
Definition at line 120 of file Line.h.
References llvm::codeview::ColumnInfo::getEndColumn().
getEndLine()
uint32_t llvm::codeview::Line::getEndLine () const inline
Definition at line 116 of file Line.h.
References llvm::codeview::LineInfo::getEndLine().
getLineDelta()
uint32_t llvm::codeview::Line::getLineDelta () const inline
Definition at line 114 of file Line.h.
References llvm::codeview::LineInfo::getLineDelta().
getLineInfo()
LineInfo llvm::codeview::Line::getLineInfo () const inline
Definition at line 106 of file Line.h.
getStartColumn()
uint16_t llvm::codeview::Line::getStartColumn () const inline
Definition at line 118 of file Line.h.
References llvm::codeview::ColumnInfo::getStartColumn().
getStartLine()
uint32_t llvm::codeview::Line::getStartLine () const inline
Definition at line 112 of file Line.h.
References llvm::codeview::LineInfo::getStartLine().
isAlwaysStepInto()
bool llvm::codeview::Line::isAlwaysStepInto () const inline
Definition at line 124 of file Line.h.
References llvm::codeview::LineInfo::isAlwaysStepInto().
isNeverStepInto()
bool llvm::codeview::Line::isNeverStepInto () const inline
Definition at line 126 of file Line.h.
References llvm::codeview::LineInfo::isNeverStepInto().
isStatement()
bool llvm::codeview::Line::isStatement () const inline
Definition at line 122 of file Line.h.
References llvm::codeview::LineInfo::isStatement().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/Line.h