LLVM: llvm::pdb::TpiStreamBuilder Class Reference
llvm::pdb::TpiStreamBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/TpiStreamBuilder.h"
Public Member Functions
TpiStreamBuilder (msf::MSFBuilder &Msf, uint32_t StreamIdx)
~TpiStreamBuilder ()
TpiStreamBuilder (const TpiStreamBuilder &)=delete
TpiStreamBuilder & operator= (const TpiStreamBuilder &)=delete
void setVersionHeader (PdbRaw_TpiVer Version)
void addTypeRecord (ArrayRef< uint8_t > Type, Optional< uint32_t > Hash)
Error finalizeMsfLayout ()
uint32_t getRecordCount () const
Error commit (const msf::MSFLayout &Layout, WritableBinaryStreamRef Buffer)
uint32_t calculateSerializedLength ()
Detailed Description
Definition at line 47 of file TpiStreamBuilder.h.
Constructor & Destructor Documentation
TpiStreamBuilder() [1/2]
TpiStreamBuilder::TpiStreamBuilder (msf::MSFBuilder & Msf, uint32_t StreamIdx) explicit
Definition at line 34 of file TpiStreamBuilder.cpp.
References ~TpiStreamBuilder().
~TpiStreamBuilder()
TpiStreamBuilder::~TpiStreamBuilder () default
Referenced by TpiStreamBuilder().
TpiStreamBuilder() [2/2]
llvm::pdb::TpiStreamBuilder::TpiStreamBuilder (const TpiStreamBuilder &) delete
Member Function Documentation
addTypeRecord()
void TpiStreamBuilder::addTypeRecord (ArrayRef< uint8_t > Type, Optional< uint32_t > Hash)
Definition at line 44 of file TpiStreamBuilder.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::codeview::TypeIndex::FirstNonSimpleIndex, H, llvm::pdb::TpiStreamHeader::HashAdjBuffer, llvm::pdb::TpiStreamHeader::HashAuxStreamIndex, llvm::pdb::TpiStreamHeader::HashKeySize, llvm::pdb::TpiStreamHeader::HashStreamIndex, llvm::pdb::TpiStreamHeader::HashValueBuffer, llvm::pdb::TpiStreamHeader::HeaderSize, llvm::pdb::TpiStreamHeader::IndexOffsetBuffer, llvm::pdb::kInvalidStreamIndex, llvm::pdb::TpiStreamHeader::EmbeddedBuf::Length, llvm::pdb::MaxTpiHashBuckets, llvm::pdb::TpiStreamHeader::NumHashBuckets, llvm::pdb::TpiStreamHeader::EmbeddedBuf::Off, llvm::ArrayRef< T >::size(), llvm::Error::success(), llvm::pdb::TpiStreamHeader::TypeIndexBegin, llvm::pdb::TpiStreamHeader::TypeIndexEnd, llvm::pdb::TpiStreamHeader::TypeRecordBytes, and llvm::pdb::TpiStreamHeader::Version.
calculateSerializedLength()
uint32_t TpiStreamBuilder::calculateSerializedLength ()
Definition at line 99 of file TpiStreamBuilder.cpp.
References assert().
Referenced by finalizeMsfLayout().
commit()
Error TpiStreamBuilder::commit (const msf::MSFLayout & Layout, WritableBinaryStreamRef Buffer)
Definition at line 143 of file TpiStreamBuilder.cpp.
References assert(), llvm::pdb::kInvalidStreamIndex, llvm::Error::success(), llvm::BinaryStreamWriter::writeBytes(), llvm::BinaryStreamWriter::writeObject(), and llvm::BinaryStreamWriter::writeStreamRef().
finalizeMsfLayout()
Error TpiStreamBuilder::finalizeMsfLayout ()
Definition at line 113 of file TpiStreamBuilder.cpp.
References llvm::msf::MSFBuilder::addStream(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), calculateSerializedLength(), H, I, llvm::support::little, llvm::pdb::MaxTpiHashBuckets, llvm::msf::MSFBuilder::setStreamSize(), and llvm::Error::success().
getRecordCount()
uint32_t llvm::pdb::TpiStreamBuilder::getRecordCount () const inline
Definition at line 60 of file TpiStreamBuilder.h.
References Allocator, finalize, llvm::pdb::kInvalidStreamIndex, and llvm::pdb::PdbTpiV80.
operator=()
TpiStreamBuilder& llvm::pdb::TpiStreamBuilder::operator= (const TpiStreamBuilder &) delete
setVersionHeader()
void TpiStreamBuilder::setVersionHeader (PdbRaw_TpiVer Version)
Definition at line 40 of file TpiStreamBuilder.cpp.
References llvm::IndexedInstrProf::Version.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/TpiStreamBuilder.h
lib/DebugInfo/PDB/Native/TpiStreamBuilder.cpp