LLVM: llvm::codeview::DebugSubsectionRecordBuilder Class Reference
llvm::codeview::DebugSubsectionRecordBuilder Class Reference
#include "llvm/DebugInfo/CodeView/DebugSubsectionRecord.h"
Public Member Functions
DebugSubsectionRecordBuilder (std::shared_ptr< DebugSubsection > Subsection, CodeViewContainer Container)
DebugSubsectionRecordBuilder (const DebugSubsectionRecord &Contents, CodeViewContainer Container)
Use this to copy existing subsections directly from source to destination.
uint32_t calculateSerializedLength ()
Error commit (BinaryStreamWriter &Writer) const
Detailed Description
Definition at line 54 of file DebugSubsectionRecord.h.
Constructor & Destructor Documentation
DebugSubsectionRecordBuilder() [1/2]
DebugSubsectionRecordBuilder::DebugSubsectionRecordBuilder (std::shared_ptr< DebugSubsection > Subsection, CodeViewContainer Container)
Definition at line 55 of file DebugSubsectionRecord.cpp.
DebugSubsectionRecordBuilder() [2/2]
DebugSubsectionRecordBuilder::DebugSubsectionRecordBuilder (const DebugSubsectionRecord & Contents, CodeViewContainer Container)
Use this to copy existing subsections directly from source to destination.
For example, line table subsections in an object file only need to be relocated before being copied into the PDB.
Definition at line 59 of file DebugSubsectionRecord.cpp.
Member Function Documentation
calculateSerializedLength()
uint32_t DebugSubsectionRecordBuilder::calculateSerializedLength ()
Definition at line 63 of file DebugSubsectionRecord.cpp.
References llvm::alignTo(), llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and llvm::codeview::DebugSubsectionRecord::getRecordData().
commit()
Error DebugSubsectionRecordBuilder::commit (BinaryStreamWriter & Writer) const
Definition at line 71 of file DebugSubsectionRecord.cpp.
References llvm::codeview::alignOf(), llvm::alignTo(), assert(), llvm::codeview::EC, llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), llvm::BinaryStreamWriter::getOffset(), llvm::codeview::DebugSubsectionRecord::getRecordData(), llvm::codeview::DebugSubsectionHeader::Kind, llvm::codeview::DebugSubsectionRecord::kind(), llvm::BinaryStreamWriter::padToAlignment(), llvm::Error::success(), llvm::BinaryStreamWriter::writeObject(), and llvm::BinaryStreamWriter::writeStreamRef().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSubsectionRecord.h
lib/DebugInfo/CodeView/DebugSubsectionRecord.cpp