LLVM: llvm::IntrusiveBackList< T > Class Template Reference
llvm::IntrusiveBackList< T > Class Template Reference
#include "llvm/CodeGen/DIE.h"
Classes
class const_iterator
class iterator
Public Member Functions
void push_back (T &N)
void push_front (T &N)
T & back ()
const T & back () const
T & front ()
const T & front () const
void takeNodes (IntrusiveBackList< T > &Other)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Static Public Member Functions
static iterator toIterator (T &N)
static const_iterator toIterator (const T &N)
Detailed Description
template<class T>
class llvm::IntrusiveBackList< T >
Definition at line 538 of file DIE.h.
Member Function Documentation
back() [1/2]
template<class T> T& llvm::IntrusiveBackList< T >::back () inline
Definition at line 544 of file DIE.h.
Referenced by llvm::DIE::addChild().
back() [2/2]
template<class T> const T& llvm::IntrusiveBackList< T >::back () const inline
Definition at line 545 of file DIE.h.
begin() [1/2]
template<class T> iterator llvm::IntrusiveBackList< T >::begin () inline
Definition at line 607 of file DIE.h.
Referenced by llvm::DIE::children(), and llvm::DIEValueList::values().
begin() [2/2]
template<class T> const_iterator llvm::IntrusiveBackList< T >::begin () const inline
Definition at line 610 of file DIE.h.
end() [1/2]
template<class T> iterator llvm::IntrusiveBackList< T >::end () inline
Definition at line 613 of file DIE.h.
Referenced by llvm::DIE::children(), and llvm::DIEValueList::values().
end() [2/2]
template<class T> const_iterator llvm::IntrusiveBackList< T >::end () const inline
Definition at line 614 of file DIE.h.
front() [1/2]
template<class T> T& llvm::IntrusiveBackList< T >::front () inline
Definition at line 546 of file DIE.h.
Referenced by llvm::DIE::addChildFront().
front() [2/2]
template<class T> const T& llvm::IntrusiveBackList< T >::front () const inline
Definition at line 549 of file DIE.h.
push_back()
template<class T> void llvm::IntrusiveBackList< T >::push_back (T & N) inline
Definition at line 542 of file DIE.h.
Referenced by llvm::DIE::addChild().
push_front()
template<class T> void llvm::IntrusiveBackList< T >::push_front (T & N) inline
Definition at line 543 of file DIE.h.
Referenced by llvm::DIE::addChildFront().
takeNodes()
template<class T> void llvm::IntrusiveBackList< T >::takeNodes (IntrusiveBackList< T > & Other) inline
Definition at line 553 of file DIE.h.
Referenced by llvm::DIEValueList::takeValues().
toIterator() [1/2]
template<class T> static iterator llvm::IntrusiveBackList< T >::toIterator (T & N) inline static
Definition at line 616 of file DIE.h.
toIterator() [2/2]
template<class T> static const_iterator llvm::IntrusiveBackList< T >::toIterator (const T & N) inline static
Definition at line 617 of file DIE.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/DIE.h