LLVM: llvm::codeview::StringsAndChecksums Class Reference
llvm::codeview::StringsAndChecksums Class Reference
#include "llvm/DebugInfo/CodeView/StringsAndChecksums.h"
Public Types
using StringsPtr = std::shared_ptr< DebugStringTableSubsection >
using ChecksumsPtr = std::shared_ptr< DebugChecksumsSubsection >
Public Member Functions
StringsAndChecksums ()=default
void setStrings (const StringsPtr &SP)
void setChecksums (const ChecksumsPtr &CP)
const StringsPtr & strings () const
const ChecksumsPtr & checksums () const
bool hasStrings () const
bool hasChecksums () const
Detailed Description
Definition at line 81 of file StringsAndChecksums.h.
Member Typedef Documentation
ChecksumsPtr
using llvm::codeview::StringsAndChecksums::ChecksumsPtr = std::shared_ptr<DebugChecksumsSubsection>
Definition at line 84 of file StringsAndChecksums.h.
StringsPtr
using llvm::codeview::StringsAndChecksums::StringsPtr = std::shared_ptr<DebugStringTableSubsection>
Definition at line 83 of file StringsAndChecksums.h.
Constructor & Destructor Documentation
StringsAndChecksums()
llvm::codeview::StringsAndChecksums::StringsAndChecksums () default
Member Function Documentation
checksums()
const ChecksumsPtr& llvm::codeview::StringsAndChecksums::checksums () const inline
Definition at line 93 of file StringsAndChecksums.h.
hasChecksums()
bool llvm::codeview::StringsAndChecksums::hasChecksums () const inline
Definition at line 96 of file StringsAndChecksums.h.
Referenced by llvm::CodeViewYAML::initializeStringsAndChecksums().
hasStrings()
bool llvm::codeview::StringsAndChecksums::hasStrings () const inline
Definition at line 95 of file StringsAndChecksums.h.
Referenced by llvm::CodeViewYAML::initializeStringsAndChecksums().
setChecksums()
void llvm::codeview::StringsAndChecksums::setChecksums (const ChecksumsPtr & CP) inline
Definition at line 90 of file StringsAndChecksums.h.
References llvm::HexagonISD::CP.
Referenced by llvm::CodeViewYAML::initializeStringsAndChecksums().
setStrings()
void llvm::codeview::StringsAndChecksums::setStrings (const StringsPtr & SP) inline
Definition at line 89 of file StringsAndChecksums.h.
Referenced by llvm::CodeViewYAML::initializeStringsAndChecksums().
strings()
const StringsPtr& llvm::codeview::StringsAndChecksums::strings () const inline
Definition at line 92 of file StringsAndChecksums.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/StringsAndChecksums.h