LLVM: llvm::orc::MaterializationUnit Class Reference
llvm::orc::MaterializationUnit Class Reference abstract
A MaterializationUnit represents a set of symbol definitions that can be materialized as a group, or individually discarded (when overriding definitions are encountered).
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, VModuleKey K)
virtual ~MaterializationUnit ()
virtual StringRef getName () const =0
Return the name of this materialization unit.
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
void doMaterialize (JITDylib &JD)
Called by materialization dispatchers (see ExecutionSession::DispatchMaterializationFunction) to trigger materialization of this MaterializationUnit.
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Protected Attributes
SymbolFlagsMap SymbolFlags
VModuleKey K
Detailed Description
A MaterializationUnit represents a set of symbol definitions that can be materialized as a group, or individually discarded (when overriding definitions are encountered).
MaterializationUnits are used when providing lazy definitions of symbols to JITDylibs. The JITDylib will call materialize when the address of a symbol is requested via the lookup method. The JITDylib will call discard if a stronger definition is added or already present.
Definition at line 550 of file Core.h.
Constructor & Destructor Documentation
MaterializationUnit()
llvm::orc::MaterializationUnit::MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, VModuleKey K) inline
Definition at line 552 of file Core.h.
~MaterializationUnit()
virtual llvm::orc::MaterializationUnit::~MaterializationUnit () inline virtual
Definition at line 555 of file Core.h.
References getName().
Member Function Documentation
doDiscard()
void llvm::orc::MaterializationUnit::doDiscard (const JITDylib & JD, const SymbolStringPtr & Name) inline
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Definition at line 574 of file Core.h.
Referenced by llvm::orc::JITDylib::dump().
doMaterialize()
void llvm::orc::MaterializationUnit::doMaterialize (JITDylib & JD) inline
Called by materialization dispatchers (see ExecutionSession::DispatchMaterializationFunction) to trigger materialization of this MaterializationUnit.
Definition at line 567 of file Core.h.
getName()
virtual StringRef llvm::orc::MaterializationUnit::getName () const pure virtual
Return the name of this materialization unit.
Useful for debugging output.
Implemented in llvm::orc::ReExportsMaterializationUnit, llvm::orc::AbsoluteSymbolsMaterializationUnit, llvm::orc::LazyReexportsMaterializationUnit, llvm::orc::BasicObjectLayerMaterializationUnit, and llvm::orc::IRMaterializationUnit.
Referenced by llvm::orc::operator<<().
getSymbols()
const SymbolFlagsMap& llvm::orc::MaterializationUnit::getSymbols () const inline
Return the set of symbols that this source provides.
Definition at line 562 of file Core.h.
Referenced by llvm::orc::JITDylib::dump(), and llvm::orc::operator<<().
Member Data Documentation
K
VModuleKey llvm::orc::MaterializationUnit::K protected
Definition at line 581 of file Core.h.
Referenced by llvm::orc::IRLayer::getCloneToNewContextOnEmit(), and llvm::orc::ObjectLayer::getExecutionSession().
SymbolFlags
SymbolFlagsMap llvm::orc::MaterializationUnit::SymbolFlags protected
Definition at line 580 of file Core.h.
Referenced by llvm::orc::ReExportsMaterializationUnit::getName(), llvm::orc::getObjectSymbolFlags(), and llvm::orc::IRMaterializationUnit::IRMaterializationUnit().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp