LLVM: llvm::codeview::DebugSubsectionRecord Class Reference
llvm::codeview::DebugSubsectionRecord Class Reference
#include "llvm/DebugInfo/CodeView/DebugSubsectionRecord.h"
Public Member Functions
DebugSubsectionRecord ()
DebugSubsectionRecord (DebugSubsectionKind Kind, BinaryStreamRef Data, CodeViewContainer Container)
uint32_t getRecordLength () const
DebugSubsectionKind kind () const
BinaryStreamRef getRecordData () const
Static Public Member Functions
static Error initialize (BinaryStreamRef Stream, DebugSubsectionRecord &Info, CodeViewContainer Container)
Detailed Description
Definition at line 35 of file DebugSubsectionRecord.h.
Constructor & Destructor Documentation
DebugSubsectionRecord() [1/2]
DebugSubsectionRecord::DebugSubsectionRecord () default
DebugSubsectionRecord() [2/2]
DebugSubsectionRecord::DebugSubsectionRecord (DebugSubsectionKind Kind, BinaryStreamRef Data, CodeViewContainer Container)
Definition at line 25 of file DebugSubsectionRecord.cpp.
Member Function Documentation
getRecordData()
BinaryStreamRef DebugSubsectionRecord::getRecordData () const
Definition at line 53 of file DebugSubsectionRecord.cpp.
Referenced by llvm::codeview::DebugSubsectionRecordBuilder::calculateSerializedLength(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::codeview::StringsAndChecksumsRef::setChecksums(), llvm::codeview::StringsAndChecksumsRef::StringsAndChecksumsRef(), and llvm::codeview::visitDebugSubsection().
getRecordLength()
uint32_t DebugSubsectionRecord::getRecordLength () const
Definition at line 47 of file DebugSubsectionRecord.cpp.
References llvm::BinaryStreamRefBase< RefType, StreamType >::getLength().
Referenced by llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord >::operator()().
initialize()
Error DebugSubsectionRecord::initialize (BinaryStreamRef Stream, DebugSubsectionRecord & Info, CodeViewContainer Container) static
Definition at line 30 of file DebugSubsectionRecord.cpp.
References llvm::codeview::EC, llvm::codeview::DebugSubsectionHeader::Kind, llvm::codeview::DebugSubsectionHeader::Length, llvm::BinaryStreamReader::readObject(), llvm::BinaryStreamReader::readStreamRef(), and llvm::Error::success().
Referenced by llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord >::operator()().
kind()
DebugSubsectionKind DebugSubsectionRecord::kind () const
Definition at line 51 of file DebugSubsectionRecord.cpp.
Referenced by llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::codeview::StringsAndChecksumsRef::setChecksums(), llvm::codeview::StringsAndChecksumsRef::StringsAndChecksumsRef(), and llvm::codeview::visitDebugSubsection().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSubsectionRecord.h
lib/DebugInfo/CodeView/DebugSubsectionRecord.cpp