LLVM: llvm::orc::RTDyldObjectLinkingLayer Class Reference
llvm::orc::RTDyldObjectLinkingLayer Class Reference
#include "llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h"
Public Types
using NotifyLoadedFunction = std::function< void(VModuleKey, const object::ObjectFile &Obj, const RuntimeDyld::LoadedObjectInfo &)>
Functor for receiving object-loaded notifications.
using NotifyEmittedFunction = std::function< void(VModuleKey, std::unique_ptr< MemoryBuffer >)>
Functor for receiving finalization notifications.
using GetMemoryManagerFunction = std::function< std::unique_ptr< RuntimeDyld::MemoryManager >()>
Public Member Functions
RTDyldObjectLinkingLayer (ExecutionSession &ES, GetMemoryManagerFunction GetMemoryManager)
Construct an ObjectLinkingLayer with the given NotifyLoaded, and NotifyEmitted functors.
~RTDyldObjectLinkingLayer ()
void emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O) override
Emit the object.
RTDyldObjectLinkingLayer & setNotifyLoaded (NotifyLoadedFunction NotifyLoaded)
Set the NotifyLoaded callback.
RTDyldObjectLinkingLayer & setNotifyEmitted (NotifyEmittedFunction NotifyEmitted)
Set the NotifyEmitted callback.
RTDyldObjectLinkingLayer & setProcessAllSections (bool ProcessAllSections)
Set the 'ProcessAllSections' flag.
RTDyldObjectLinkingLayer & setOverrideObjectFlagsWithResponsibilityFlags (bool OverrideObjectFlags)
Instructs this RTDyldLinkingLayer2 instance to override the symbol flags returned by RuntimeDyld for any given object file with the flags supplied by the MaterializationResponsibility instance.
RTDyldObjectLinkingLayer & setAutoClaimResponsibilityForObjectSymbols (bool AutoClaimObjectSymbols)
If set, this RTDyldObjectLinkingLayer instance will claim responsibility for any symbols provided by a given object file that were not already in the MaterializationResponsibility instance.
Public Member Functions inherited from llvm::orc::ObjectLayer
ObjectLayer (ExecutionSession &ES)
virtual ~ObjectLayer ()
ExecutionSession & getExecutionSession ()
Returns the execution session for this layer.
virtual Error add (JITDylib &JD, std::unique_ptr< MemoryBuffer > O, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Detailed Description
Definition at line 38 of file RTDyldObjectLinkingLayer.h.
Member Typedef Documentation
GetMemoryManagerFunction
using llvm::orc::RTDyldObjectLinkingLayer::GetMemoryManagerFunction = std::function<std::unique_ptr<RuntimeDyld::MemoryManager>()>
Definition at line 50 of file RTDyldObjectLinkingLayer.h.
NotifyEmittedFunction
using llvm::orc::RTDyldObjectLinkingLayer::NotifyEmittedFunction = std::function<void(VModuleKey, std::unique_ptr<MemoryBuffer>)>
Functor for receiving finalization notifications.
Definition at line 47 of file RTDyldObjectLinkingLayer.h.
NotifyLoadedFunction
using llvm::orc::RTDyldObjectLinkingLayer::NotifyLoadedFunction = std::function<void(VModuleKey, const object::ObjectFile &Obj, const RuntimeDyld::LoadedObjectInfo &)>
Functor for receiving object-loaded notifications.
Definition at line 43 of file RTDyldObjectLinkingLayer.h.
Constructor & Destructor Documentation
RTDyldObjectLinkingLayer()
llvm::orc::RTDyldObjectLinkingLayer::RTDyldObjectLinkingLayer (ExecutionSession & ES, GetMemoryManagerFunction GetMemoryManager)
Construct an ObjectLinkingLayer with the given NotifyLoaded, and NotifyEmitted functors.
Definition at line 78 of file RTDyldObjectLinkingLayer.cpp.
~RTDyldObjectLinkingLayer()
llvm::orc::RTDyldObjectLinkingLayer::~RTDyldObjectLinkingLayer ()
Definition at line 82 of file RTDyldObjectLinkingLayer.cpp.
References llvm::Lock.
Member Function Documentation
emit()
void llvm::orc::RTDyldObjectLinkingLayer::emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O) override virtual
Emit the object.
Implements llvm::orc::ObjectLayer.
Definition at line 88 of file RTDyldObjectLinkingLayer.cpp.
References assert(), llvm::object::ObjectFile::createObjectFile(), llvm::orc::MaterializationResponsibility::failMaterialization(), llvm::orc::ObjectLayer::getExecutionSession(), llvm::MemoryBuffer::getMemBuffer(), llvm::orc::MaterializationResponsibility::getVModuleKey(), llvm::jitLinkForORC(), llvm::Lock, llvm::orc::ExecutionSession::reportError(), and llvm::object::BasicSymbolRef::SF_Global.
setAutoClaimResponsibilityForObjectSymbols()
RTDyldObjectLinkingLayer& llvm::orc::RTDyldObjectLinkingLayer::setAutoClaimResponsibilityForObjectSymbols (bool AutoClaimObjectSymbols) inline
If set, this RTDyldObjectLinkingLayer instance will claim responsibility for any symbols provided by a given object file that were not already in the MaterializationResponsibility instance.
Setting this flag allows higher-level program representations (e.g. LLVM IR) to be added based on only a subset of the symbols they provide, without having to write intervening layers to scan and add the additional symbols. This trades diagnostic quality for convenience however: If all symbols are enumerated up-front then clashes can be detected and reported early (and usually deterministically). If this option is set, clashes for the additional symbols may not be detected until late, and detection may depend on the flow of control through JIT'd code. Use with care.
Definition at line 113 of file RTDyldObjectLinkingLayer.h.
References llvm::orc::Resolved.
setNotifyEmitted()
RTDyldObjectLinkingLayer& llvm::orc::RTDyldObjectLinkingLayer::setNotifyEmitted (NotifyEmittedFunction NotifyEmitted) inline
Set the NotifyEmitted callback.
Definition at line 71 of file RTDyldObjectLinkingLayer.h.
setNotifyLoaded()
RTDyldObjectLinkingLayer& llvm::orc::RTDyldObjectLinkingLayer::setNotifyLoaded (NotifyLoadedFunction NotifyLoaded) inline
Set the NotifyLoaded callback.
Definition at line 64 of file RTDyldObjectLinkingLayer.h.
setOverrideObjectFlagsWithResponsibilityFlags()
RTDyldObjectLinkingLayer& llvm::orc::RTDyldObjectLinkingLayer::setOverrideObjectFlagsWithResponsibilityFlags (bool OverrideObjectFlags) inline
Instructs this RTDyldLinkingLayer2 instance to override the symbol flags returned by RuntimeDyld for any given object file with the flags supplied by the MaterializationResponsibility instance.
This is a workaround to support symbol visibility in COFF, which does not use the libObject's SF_Exported flag. Use only when generating / adding COFF object files.
FIXME: We should be able to remove this if/when COFF properly tracks exported symbols.
Definition at line 96 of file RTDyldObjectLinkingLayer.h.
setProcessAllSections()
RTDyldObjectLinkingLayer& llvm::orc::RTDyldObjectLinkingLayer::setProcessAllSections (bool ProcessAllSections) inline
Set the 'ProcessAllSections' flag.
If set to true, all sections in each object file will be allocated using the memory manager, rather than just the sections required for execution.
This is kludgy, and may be removed in the future.
Definition at line 82 of file RTDyldObjectLinkingLayer.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h
lib/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.cpp