LLVM: llvm::FPMathOperator Class Reference
llvm::FPMathOperator Class Reference
Utility class for floating point operations which can have information about relaxed accuracy requirements attached to them.
#include "llvm/IR/Operator.h"
Public Member Functions
bool isFast () const
Test if this operation allows all non-strict floating-point transforms.
bool hasAllowReassoc () const
Test if this operation may be simplified with reassociative transforms.
bool hasNoNaNs () const
Test if this operation's arguments and results are assumed not-NaN.
bool hasNoInfs () const
Test if this operation's arguments and results are assumed not-infinite.
bool hasNoSignedZeros () const
Test if this operation can ignore the sign of zero.
bool hasAllowReciprocal () const
Test if this operation can use reciprocal multiply instead of division.
bool hasAllowContract () const
Test if this operation can be floating-point contracted (FMA).
bool hasApproxFunc () const
Test if this operation allows approximations of math library functions or intrinsics.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags.
float getFPAccuracy () const
Get the maximum error permitted by this operation in ULPs.
Public Member Functions inherited from llvm::Operator
Operator ()=delete
~Operator ()=delete
void * operator new (size_t s)=delete
unsigned getOpcode () const
Return the opcode for this Instruction or ConstantExpr.
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Operator
static unsigned getOpcode (const Value *V)
If V is an Instruction or ConstantExpr, return its opcode.
static bool classof (const Instruction *)
static bool classof (const ConstantExpr *)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class Instruction
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Utility class for floating point operations which can have information about relaxed accuracy requirements attached to them.
Definition at line 246 of file Operator.h.
Member Function Documentation
classof()
static bool llvm::FPMathOperator::classof (const Value * V) inline static
Definition at line 373 of file Operator.h.
References llvm::MCID::Call, llvm::Value::getType(), I, llvm::Type::isFPOrFPVectorTy(), and llvm::MCID::Select.
getFastMathFlags()
FastMathFlags llvm::FPMathOperator::getFastMathFlags () const inline
Convenience function for getting all the fast-math flags.
Definition at line 364 of file Operator.h.
References llvm::Value::SubclassOptionalData.
Referenced by shouldKeepFDivF32().
getFPAccuracy()
float FPMathOperator::getFPAccuracy () const
Get the maximum error permitted by this operation in ULPs.
An accuracy of 0.0 means that the operation should be performed with the default precision.
Definition at line 2429 of file Instructions.cpp.
References llvm::APFloat::convertToFloat(), llvm::Instruction::getMetadata(), llvm::MDNode::getOperand(), and llvm::ConstantFP::getValueAPF().
Referenced by shouldKeepFDivF32().
hasAllowContract()
bool llvm::FPMathOperator::hasAllowContract () const inline
Test if this operation can be floating-point contracted (FMA).
Definition at line 353 of file Operator.h.
References llvm::FastMathFlags::AllowContract, and llvm::Value::SubclassOptionalData.
Referenced by llvm::SDNodeFlags::copyFMF().
hasAllowReassoc()
bool llvm::FPMathOperator::hasAllowReassoc () const inline
Test if this operation may be simplified with reassociative transforms.
Definition at line 328 of file Operator.h.
References llvm::FastMathFlags::AllowReassoc, and llvm::Value::SubclassOptionalData.
Referenced by llvm::SDNodeFlags::copyFMF().
hasAllowReciprocal()
bool llvm::FPMathOperator::hasAllowReciprocal () const inline
Test if this operation can use reciprocal multiply instead of division.
Definition at line 348 of file Operator.h.
References llvm::FastMathFlags::AllowReciprocal, and llvm::Value::SubclassOptionalData.
Referenced by llvm::SDNodeFlags::copyFMF().
hasApproxFunc()
bool llvm::FPMathOperator::hasApproxFunc () const inline
Test if this operation allows approximations of math library functions or intrinsics.
Definition at line 359 of file Operator.h.
References llvm::FastMathFlags::ApproxFunc, and llvm::Value::SubclassOptionalData.
Referenced by llvm::SDNodeFlags::copyFMF().
hasNoInfs()
bool llvm::FPMathOperator::hasNoInfs () const inline
Test if this operation's arguments and results are assumed not-infinite.
Definition at line 338 of file Operator.h.
References llvm::FastMathFlags::NoInfs, and llvm::Value::SubclassOptionalData.
Referenced by llvm::SDNodeFlags::copyFMF().
hasNoNaNs()
bool llvm::FPMathOperator::hasNoNaNs () const inline
Test if this operation's arguments and results are assumed not-NaN.
Definition at line 333 of file Operator.h.
References llvm::FastMathFlags::NoNaNs, and llvm::Value::SubclassOptionalData.
Referenced by llvm::SDNodeFlags::copyFMF().
hasNoSignedZeros()
bool llvm::FPMathOperator::hasNoSignedZeros () const inline
Test if this operation can ignore the sign of zero.
Definition at line 343 of file Operator.h.
References llvm::FastMathFlags::NoSignedZeros, and llvm::Value::SubclassOptionalData.
Referenced by llvm::SDNodeFlags::copyFMF().
isFast()
bool llvm::FPMathOperator::isFast () const inline
Test if this operation allows all non-strict floating-point transforms.
Definition at line 317 of file Operator.h.
References llvm::FastMathFlags::AllowContract, llvm::FastMathFlags::AllowReassoc, llvm::FastMathFlags::AllowReciprocal, llvm::FastMathFlags::ApproxFunc, llvm::FastMathFlags::NoInfs, llvm::FastMathFlags::NoNaNs, llvm::FastMathFlags::NoSignedZeros, and llvm::Value::SubclassOptionalData.
Friends And Related Function Documentation
Instruction
friend class Instruction friend
Definition at line 248 of file Operator.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Operator.h
lib/IR/Instructions.cpp