LLVM: llvm::RuntimeDyldELF Class Reference
llvm::RuntimeDyldELF Class Reference
#include "ExecutionEngine/RuntimeDyld/RuntimeDyldELF.h"
Public Member Functions
RuntimeDyldELF (RuntimeDyld::MemoryManager &MemMgr, JITSymbolResolver &Resolver)
~RuntimeDyldELF () override
std::unique_ptr< RuntimeDyld::LoadedObjectInfo > loadObject (const object::ObjectFile &O) override
void resolveRelocation (const RelocationEntry &RE, uint64_t Value) override
A object file specific relocation resolver.
Expected< relocation_iterator > processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile &Obj, ObjSectionToIDMap &ObjSectionToID, StubMap &Stubs) override
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
bool isCompatibleFile (const object::ObjectFile &Obj) const override
void registerEHFrames () override
Error finalizeLoad (const ObjectFile &Obj, ObjSectionToIDMap &SectionMap) override
Public Member Functions inherited from llvm::RuntimeDyldImpl
RuntimeDyldImpl (RuntimeDyld::MemoryManager &MemMgr, JITSymbolResolver &Resolver)
virtual ~RuntimeDyldImpl ()
void setProcessAllSections (bool ProcessAllSections)
uint64_t getSectionLoadAddress (unsigned SectionID) const
uint8_t * getSectionAddress (unsigned SectionID) const
StringRef getSectionContent (unsigned SectionID) const
uint8_t * getSymbolLocalAddress (StringRef Name) const
unsigned getSymbolSectionID (StringRef Name) const
JITEvaluatedSymbol getSymbol (StringRef Name) const
std::map< StringRef, JITEvaluatedSymbol > getSymbolTable () const
void resolveRelocations ()
void resolveLocalRelocations ()
void reassignSectionAddress (unsigned SectionID, uint64_t Addr)
void mapSectionAddress (const void *LocalAddress, uint64_t TargetAddress)
bool hasError ()
void clearError ()
StringRef getErrorString ()
void setNotifyStubEmitted (NotifyStubEmittedFunction NotifyStubEmitted)
void deregisterEHFrames ()
Static Public Member Functions
static std::unique_ptr< RuntimeDyldELF > create (Triple::ArchType Arch, RuntimeDyld::MemoryManager &MemMgr, JITSymbolResolver &Resolver)
Static Public Member Functions inherited from llvm::RuntimeDyldImpl
static void finalizeAsync (std::unique_ptr< RuntimeDyldImpl > This, unique_function< void(Error)> OnEmitted, std::unique_ptr< MemoryBuffer > UnderlyingBuffer)
Protected Member Functions
size_t getGOTEntrySize () override
Protected Member Functions inherited from llvm::RuntimeDyldImpl
void writeInt16BE (uint8_t *Addr, uint16_t Value)
void writeInt32BE (uint8_t *Addr, uint32_t Value)
void writeInt64BE (uint8_t *Addr, uint64_t Value)
uint64_t readBytesUnaligned (uint8_t *Src, unsigned Size) const
Endian-aware read Read the least significant Size bytes from Src.
void writeBytesUnaligned (uint64_t Value, uint8_t *Dst, unsigned Size) const
Endian-aware write.
virtual Expected< JITSymbolFlags > getJITSymbolFlags (const SymbolRef &Sym)
Generate JITSymbolFlags from a libObject symbol.
virtual uint64_t modifyAddressBasedOnFlags (uint64_t Addr, JITSymbolFlags Flags) const
Modify the given target address based on the given symbol flags.
Error emitCommonSymbols (const ObjectFile &Obj, CommonSymbolList &CommonSymbols, uint64_t CommonSize, uint32_t CommonAlign)
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
Expected< unsigned > emitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode)
Emits section data from the object file to the MemoryManager.
Expected< unsigned > findOrEmitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode, ObjSectionToIDMap &LocalSections)
Find Section in LocalSections.
void addRelocationForSection (const RelocationEntry &RE, unsigned SectionID)
void addRelocationForSymbol (const RelocationEntry &RE, StringRef SymbolName)
uint8_t * createStubFunction (uint8_t *Addr, unsigned AbiVariant=0)
Emits long jump instruction to Addr.
void resolveRelocationList (const RelocationList &Relocs, uint64_t Value)
Resolves relocations from Relocs list with address from Value.
void applyExternalSymbolRelocations (const StringMap< JITEvaluatedSymbol > ExternalSymbolMap)
Error resolveExternalSymbols ()
Resolve relocations to external symbols.
Error computeTotalAllocSize (const ObjectFile &Obj, uint64_t &CodeSize, uint32_t &CodeAlign, uint64_t &RODataSize, uint32_t &RODataAlign, uint64_t &RWDataSize, uint32_t &RWDataAlign)
unsigned computeGOTSize (const ObjectFile &Obj)
unsigned computeSectionStubBufSize (const ObjectFile &Obj, const SectionRef &Section)
Expected< ObjSectionToIDMap > loadObjectImpl (const object::ObjectFile &Obj)
Protected Attributes
DenseMap< SID, SID > SectionToGOTMap
Protected Attributes inherited from llvm::RuntimeDyldImpl
RuntimeDyld::MemoryManager & MemMgr
JITSymbolResolver & Resolver
SectionList Sections
RTDyldSymbolTable GlobalSymbolTable
std::unordered_map< unsigned, RelocationList > Relocations
StringMap< RelocationList > ExternalSymbolRelocations
Triple::ArchType Arch
bool IsTargetLittleEndian
bool IsMipsO32ABI
bool IsMipsN32ABI
bool IsMipsN64ABI
bool ProcessAllSections
sys::Mutex lock
NotifyStubEmittedFunction NotifyStubEmitted
bool HasError
std::string ErrorStr
Additional Inherited Members
Protected Types inherited from llvm::RuntimeDyldImpl
typedef SmallVector< SectionEntry, 64 > SectionList
typedef unsigned SID
typedef std::map< SectionRef, unsigned > ObjSectionToIDMap
typedef std::vector< SymbolRef > CommonSymbolList
typedef SmallVector< RelocationEntry, 64 > RelocationList
typedef std::map< RelocationValueRef, uintptr_t > StubMap
using NotifyStubEmittedFunction = RuntimeDyld::NotifyStubEmittedFunction
Static Protected Attributes inherited from llvm::RuntimeDyldImpl
static const unsigned AbsoluteSymbolSection = ~0U
Detailed Description
Definition at line 26 of file RuntimeDyldELF.h.
Constructor & Destructor Documentation
RuntimeDyldELF()
llvm::RuntimeDyldELF::RuntimeDyldELF (RuntimeDyld::MemoryManager & MemMgr, JITSymbolResolver & Resolver)
Definition at line 223 of file RuntimeDyldELF.cpp.
~RuntimeDyldELF()
llvm::RuntimeDyldELF::~RuntimeDyldELF () override
Definition at line 226 of file RuntimeDyldELF.cpp.
Member Function Documentation
create()
std::unique_ptr< RuntimeDyldELF > llvm::RuntimeDyldELF::create (Triple::ArchType Arch, RuntimeDyld::MemoryManager & MemMgr, JITSymbolResolver & Resolver) static
Definition at line 240 of file RuntimeDyldELF.cpp.
References llvm::RuntimeDyldImpl::MemMgr, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, and llvm::RuntimeDyldImpl::Resolver.
Referenced by llvm::createRuntimeDyldELF().
finalizeLoad()
Error llvm::RuntimeDyldELF::finalizeLoad (const ObjectFile & Obj, ObjSectionToIDMap & SectionMap) override virtual
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 1852 of file RuntimeDyldELF.cpp.
References llvm::RuntimeDyld::MemoryManager::allocateDataSection(), assert(), llvm::StringMap< ValueTy, AllocatorTy >::clear(), llvm::consumeError(), llvm::numbers::e, getGOTEntrySize(), llvm::object::SectionRef::getName(), llvm::RuntimeDyldImpl::IsMipsN32ABI, llvm::RuntimeDyldImpl::IsMipsN64ABI, llvm::RuntimeDyldImpl::IsMipsO32ABI, llvm::RuntimeDyldImpl::MemMgr, Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), llvm::RuntimeDyldImpl::Sections, SectionToGOTMap, SI, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::toString().
getGOTEntrySize()
size_t llvm::RuntimeDyldELF::getGOTEntrySize () override protected virtual
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 1770 of file RuntimeDyldELF.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::RuntimeDyldImpl::addRelocationForSection(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::RuntimeDyldImpl::Arch, llvm::Triple::arm, E, llvm::RuntimeDyldImpl::IsMipsN32ABI, llvm::RuntimeDyldImpl::IsMipsN64ABI, llvm::RuntimeDyldImpl::IsMipsO32ABI, llvm_unreachable, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::RelocationValueRef::Offset, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::RelocationValueRef::SectionID, llvm::RuntimeDyldImpl::Sections, llvm::SmallVectorBase::size(), llvm::RelocationValueRef::SymbolName, llvm::Triple::systemz, llvm::Triple::thumb, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by finalizeLoad(), and llvm::RuntimeDyldELFMips::resolveRelocation().
isCompatibleFile()
bool llvm::RuntimeDyldELF::isCompatibleFile (const object::ObjectFile & Obj) const override virtual
Implements llvm::RuntimeDyldImpl.
Definition at line 1918 of file RuntimeDyldELF.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::RuntimeDyldImpl::Arch, llvm::object::RelocationRef::getType(), llvm::object::Binary::isELF(), and llvm::Triple::x86_64.
loadObject()
std::unique_ptr< RuntimeDyld::LoadedObjectInfo > llvm::RuntimeDyldELF::loadObject (const object::ObjectFile & O) override virtual
Implements llvm::RuntimeDyldImpl.
Definition at line 255 of file RuntimeDyldELF.cpp.
References llvm::Triple::aarch64_be, llvm::RelocationValueRef::Addend, llvm::RuntimeDyldImpl::Arch, assert(), llvm::dbgs(), llvm::numbers::e, E, llvm::ELF::EF_MIPS_ABI2, llvm::ELF::EF_MIPS_ABI_O32, llvm::StringRef::equals(), llvm::RuntimeDyldImpl::ErrorStr, llvm::RuntimeDyldImpl::findOrEmitSection(), llvm::format(), llvm::SectionEntry::getAddress(), llvm::SectionEntry::getAddressWithOffset(), llvm::Triple::getArchTypePrefix(), getBits(), llvm::object::ObjectFile::getFileFormatName(), llvm::SectionEntry::getLoadAddressWithOffset(), llvm::SectionEntry::getName(), llvm::object::SymbolRef::getSection(), llvm::object::SymbolRef::getType(), llvm::RuntimeDyldImpl::HasError, llvm::isInt< 32 >(), llvm::isInt< 8 >(), llvm::RuntimeDyldImpl::IsMipsN32ABI, llvm::RuntimeDyldImpl::IsMipsN64ABI, llvm::RuntimeDyldImpl::IsMipsO32ABI, LLVM_DEBUG, llvm_unreachable, llvm::RuntimeDyldImpl::loadObjectImpl(), llvm::logAllUnhandledErrors(), or32AArch64Imm(), llvm::or32le(), llvm::report_fatal_error(), llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), llvm::RelocationValueRef::SectionID, llvm::RuntimeDyldImpl::Sections, llvm::object::ObjectFile::sections(), llvm::Error::success(), llvm::RelocationValueRef::SymbolName, llvm::Expected< T >::takeError(), llvm::toString(), llvm::Triple::UnknownArch, write(), and llvm::write32AArch64Addr().
processRelocationRef()
Expected< relocation_iterator > llvm::RuntimeDyldELF::processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile & Obj, ObjSectionToIDMap & ObjSectionToID, StubMap & Stubs) override virtual
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
Returns
Iterator to the next relocation that needs to be parsed.
Implements llvm::RuntimeDyldImpl.
Definition at line 1109 of file RuntimeDyldELF.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::RelocationEntry::Addend, llvm::RelocationValueRef::Addend, llvm::RuntimeDyldImpl::addRelocationForSection(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::SectionEntry::advanceStubOffset(), llvm::RuntimeDyldImpl::Arch, llvm::Triple::arm, llvm::consumeError(), llvm::RuntimeDyldImpl::createStubFunction(), llvm::StringRef::data(), llvm::dbgs(), llvm::ELF::EF_PPC64_ABI, llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::RuntimeDyldImpl::findOrEmitSection(), llvm::raw_ostream::flush(), llvm::object::ELFRelocationRef::getAddend(), llvm::SectionEntry::getAddress(), llvm::SectionEntry::getAddressWithOffset(), llvm::object::ELFObjectFileBase::getPlatformFlags(), llvm::SectionEntry::getStubOffset(), llvm::RuntimeDyldImpl::GlobalSymbolTable, I, llvm::RuntimeDyldImpl::IsMipsN32ABI, llvm::RuntimeDyldImpl::IsMipsN64ABI, llvm::RuntimeDyldImpl::IsMipsO32ABI, LLVM_DEBUG, llvm_unreachable, llvm::logAllUnhandledErrors(), llvm::RISCVFenceField::O, llvm::RelocationValueRef::Offset, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::RuntimeDyldImpl::readBytesUnaligned(), llvm::RelocationEntry::RelType, llvm::report_fatal_error(), llvm::object::ObjectFile::section_end(), llvm::RelocationEntry::SectionID, llvm::RelocationValueRef::SectionID, llvm::RuntimeDyldImpl::Sections, llvm::ARMBuildAttrs::Symbol, llvm::object::SymbolicFile::symbol_end(), llvm::RelocationValueRef::SymbolName, llvm::RelocationEntry::SymOffset, and llvm::Expected< T >::takeError().
registerEHFrames()
void llvm::RuntimeDyldELF::registerEHFrames () override virtual
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 228 of file RuntimeDyldELF.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::numbers::e, llvm::RuntimeDyldImpl::MemMgr, llvm::RuntimeDyld::MemoryManager::registerEHFrames(), llvm::RuntimeDyldImpl::Sections, and llvm::SmallVectorBase::size().
resolveRelocation()
void llvm::RuntimeDyldELF::resolveRelocation (const RelocationEntry & RE, uint64_t Value) override virtual
A object file specific relocation resolver.
Parameters
RE The relocation to be resolved
Value Target symbol address to apply the relocation action
Implements llvm::RuntimeDyldImpl.
Reimplemented in llvm::RuntimeDyldELFMips.
Definition at line 927 of file RuntimeDyldELF.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::RelocationEntry::Addend, llvm::RelocationValueRef::Addend, llvm::RuntimeDyldImpl::addRelocationForSection(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::Address, llvm::SectionEntry::advanceStubOffset(), llvm::RuntimeDyldImpl::Arch, llvm::Triple::arm, llvm::Triple::armeb, llvm::Triple::bpfeb, llvm::Triple::bpfel, llvm::RuntimeDyldImpl::createStubFunction(), llvm::dbgs(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::SectionEntry::getAddress(), llvm::SectionEntry::getAddressWithOffset(), llvm::SectionEntry::getStubOffset(), llvm::RuntimeDyldImpl::GlobalSymbolTable, LLVM_DEBUG, llvm_unreachable, llvm::RelocationEntry::Offset, llvm::RelocationValueRef::Offset, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::RelocationEntry::RelType, llvm::RelocationEntry::SectionID, llvm::RelocationValueRef::SectionID, llvm::RuntimeDyldImpl::Sections, llvm::RelocationValueRef::SymbolName, llvm::RelocationEntry::SymOffset, llvm::Triple::systemz, llvm::Triple::thumb, llvm::Triple::thumbeb, llvm::Triple::x86, and llvm::Triple::x86_64.
Member Data Documentation
SectionToGOTMap
DenseMap<SID, SID> llvm::RuntimeDyldELF::SectionToGOTMap protected
Definition at line 142 of file RuntimeDyldELF.h.
Referenced by finalizeLoad(), and llvm::RuntimeDyldELFMips::resolveRelocation().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.h
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp