LLVM: llvm::NodeSet Class Reference
llvm::NodeSet Class Reference
A NodeSet contains a set of SUnit DAG nodes with additional information that assigns a priority to the set.
#include "llvm/CodeGen/MachinePipeliner.h"
Public Types
using iterator = SetVector< SUnit * >::const_iterator
Public Member Functions
NodeSet ()=default
NodeSet (iterator S, iterator E)
bool insert (SUnit *SU)
void insert (iterator S, iterator E)
template<typename UnaryPredicate >
bool remove_if (UnaryPredicate P)
unsigned count (SUnit *SU) const
bool hasRecurrence ()
unsigned size () const
bool empty () const
SUnit * getNode (unsigned i) const
void setRecMII (unsigned mii)
void setColocate (unsigned c)
void setExceedPressure (SUnit *SU)
bool isExceedSU (SUnit *SU)
int compareRecMII (NodeSet &RHS)
int getRecMII ()
void computeNodeSetInfo (SwingSchedulerDAG *SSD)
Summarize node functions for the entire node set.
unsigned getLatency ()
unsigned getMaxDepth ()
void clear ()
operator SetVector< SUnit * > & ()
bool operator> (const NodeSet &RHS) const
Sort the node sets by importance.
bool operator== (const NodeSet &RHS) const
bool operator!= (const NodeSet &RHS) const
iterator begin ()
iterator end ()
void print (raw_ostream &os) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
A NodeSet contains a set of SUnit DAG nodes with additional information that assigns a priority to the set.
Definition at line 317 of file MachinePipeliner.h.
Member Typedef Documentation
iterator
using llvm::NodeSet::iterator = SetVector<SUnit *>::const_iterator
Definition at line 328 of file MachinePipeliner.h.
Constructor & Destructor Documentation
NodeSet() [1/2]
llvm::NodeSet::NodeSet () default
NodeSet() [2/2]
llvm::NodeSet::NodeSet (iterator S, iterator E) inline
Definition at line 331 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::count(), llvm::numbers::e, and llvm::SetVector< T, Vector, Set >::size().
Member Function Documentation
begin()
iterator llvm::NodeSet::begin () inline
Definition at line 415 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::begin().
Referenced by node_eq().
clear()
void llvm::NodeSet::clear () inline
Definition at line 381 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::clear().
Referenced by computeLiveOuts().
compareRecMII()
int llvm::NodeSet::compareRecMII (NodeSet & RHS) inline
Definition at line 365 of file MachinePipeliner.h.
Referenced by computeLiveOuts(), and isIntersect().
computeNodeSetInfo()
void llvm::NodeSet::computeNodeSetInfo (SwingSchedulerDAG * SSD) inline
Summarize node functions for the entire node set.
Definition at line 370 of file MachinePipeliner.h.
References llvm::SwingSchedulerDAG::getDepth(), llvm::SwingSchedulerDAG::getMOV(), and llvm::max().
count()
unsigned llvm::NodeSet::count (SUnit * SU) const inline
Definition at line 347 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::count().
Referenced by isIntersect(), and llvm::SMSchedule::isValidSchedule().
dump()
LLVM_DUMP_METHOD void NodeSet::dump () const
Definition at line 2887 of file MachinePipeliner.cpp.
References llvm::dbgs(), and llvm::Pass::print().
empty()
bool llvm::NodeSet::empty () const inline
Definition at line 353 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::empty().
Referenced by computeLiveOuts(), and node_eq().
end()
iterator llvm::NodeSet::end () inline
Definition at line 416 of file MachinePipeliner.h.
References llvm::Pass::dump(), llvm::SetVector< T, Vector, Set >::end(), LLVM_DUMP_METHOD, and llvm::Pass::print().
Referenced by node_eq().
getLatency()
unsigned llvm::NodeSet::getLatency () inline
Definition at line 377 of file MachinePipeliner.h.
References llvm::Latency.
getMaxDepth()
unsigned llvm::NodeSet::getMaxDepth () inline
Definition at line 379 of file MachinePipeliner.h.
References MaxDepth.
getNode()
SUnit* llvm::NodeSet::getNode (unsigned i) const inline
Definition at line 355 of file MachinePipeliner.h.
Referenced by isIntersect().
getRecMII()
int llvm::NodeSet::getRecMII () inline
Definition at line 367 of file MachinePipeliner.h.
Referenced by isIntersect().
hasRecurrence()
bool llvm::NodeSet::hasRecurrence () inline
Definition at line 349 of file MachinePipeliner.h.
insert() [1/2]
bool llvm::NodeSet::insert (SUnit * SU) inline
Definition at line 339 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::insert().
Referenced by computeLiveOuts(), node_eq(), and nodes_for_root().
insert() [2/2]
void llvm::NodeSet::insert (iterator S, iterator E) inline
Definition at line 341 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::insert().
isExceedSU()
bool llvm::NodeSet::isExceedSU (SUnit * SU) inline
Definition at line 363 of file MachinePipeliner.h.
operator SetVector< SUnit * > &()
llvm::NodeSet::operator SetVector< SUnit *> & () inline
Definition at line 391 of file MachinePipeliner.h.
operator!=()
bool llvm::NodeSet::operator!= (const NodeSet & RHS) const inline
Definition at line 413 of file MachinePipeliner.h.
References llvm::operator==().
operator==()
bool llvm::NodeSet::operator== (const NodeSet & RHS) const inline
Definition at line 408 of file MachinePipeliner.h.
operator>()
bool llvm::NodeSet::operator> (const NodeSet & RHS) const inline
Sort the node sets by importance.
First, rank them by recurrence MII, then by mobility (least mobile done first), and finally by depth. Each node set may contain a colocate value which is used as the first tie breaker, if it's set.
Definition at line 397 of file MachinePipeliner.h.
print()
void NodeSet::print (raw_ostream & os) const
Definition at line 2861 of file MachinePipeliner.cpp.
References I, MaxDepth, and llvm::size().
remove_if()
template<typename UnaryPredicate > bool llvm::NodeSet::remove_if (UnaryPredicate P) inline
Definition at line 343 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::remove_if().
setColocate()
void llvm::NodeSet::setColocate (unsigned c) inline
Definition at line 359 of file MachinePipeliner.h.
Referenced by computeLiveOuts().
setExceedPressure()
void llvm::NodeSet::setExceedPressure (SUnit * SU) inline
Definition at line 361 of file MachinePipeliner.h.
setRecMII()
void llvm::NodeSet::setRecMII (unsigned mii) inline
Definition at line 357 of file MachinePipeliner.h.
Referenced by isIntersect().
size()
unsigned llvm::NodeSet::size () const inline
Definition at line 351 of file MachinePipeliner.h.
References llvm::SetVector< T, Vector, Set >::size().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePipeliner.h
lib/CodeGen/MachinePipeliner.cpp