LLVM: llvm::orc::OrcMips64 Class Reference
llvm::orc::OrcMips64 Class Reference
#include "llvm/ExecutionEngine/Orc/OrcABISupport.h"
Public Types
using IndirectStubsInfo = GenericIndirectStubsInfo< 32 >
using JITReentryFn = JITTargetAddress(*)(void *CallbackMgr, void *TrampolineId)
Static Public Member Functions
static void writeResolverCode (uint8_t *ResolveMem, JITReentryFn Reentry, void *CallbackMgr)
Write the resolver code into the given memory.
static void writeTrampolines (uint8_t *TrampolineMem, void *ResolverAddr, unsigned NumTrampolines)
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
static Error emitIndirectStubsBlock (IndirectStubsInfo &StubsInfo, unsigned MinStubs, void *InitialPtrVal)
Emit at least MinStubs worth of indirect call stubs, rounded out to the nearest page size.
Static Public Attributes
static const unsigned PointerSize = 8
static const unsigned TrampolineSize = 40
static const unsigned ResolverCodeSize = 0x120
Detailed Description
Definition at line 285 of file OrcABISupport.h.
Member Typedef Documentation
IndirectStubsInfo
using llvm::orc::OrcMips64::IndirectStubsInfo = GenericIndirectStubsInfo<32>
Definition at line 291 of file OrcABISupport.h.
JITReentryFn
using llvm::orc::OrcMips64::JITReentryFn = JITTargetAddress (*)(void *CallbackMgr, void *TrampolineId)
Definition at line 293 of file OrcABISupport.h.
Member Function Documentation
emitIndirectStubsBlock()
Error llvm::orc::OrcMips64::emitIndirectStubsBlock (IndirectStubsInfo & StubsInfo, unsigned MinStubs, void * InitialPtrVal) static
Emit at least MinStubs worth of indirect call stubs, rounded out to the nearest page size.
E.g. Asking for 4 stubs on Mips64, where stubs are 8-bytes, with 4k pages will return a block of 512 stubs (4096 / 8 = 512). Asking for 513 will return a block of 1024 (2-pages worth).
Definition at line 899 of file OrcABISupport.cpp.
References llvm::sys::Memory::allocateMappedMemory(), llvm::errorCodeToError(), llvm::sys::Process::getPageSizeEstimate(), I, llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, PageSize, llvm::sys::Memory::protectMappedMemory(), llvm::orc::GenericIndirectStubsInfo< StubSizeVal >::StubSize, and llvm::Error::success().
writeResolverCode()
void llvm::orc::OrcMips64::writeResolverCode (uint8_t * ResolveMem, JITReentryFn Reentry, void * CallbackMgr) static
Write the resolver code into the given memory.
The user is responsible for allocating the memory and setting permissions.
Definition at line 732 of file OrcABISupport.cpp.
writeTrampolines()
void llvm::orc::OrcMips64::writeTrampolines (uint8_t * TrampolineMem, void * ResolverAddr, unsigned NumTrampolines) static
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
Definition at line 875 of file OrcABISupport.cpp.
References I.
Member Data Documentation
PointerSize
const unsigned llvm::orc::OrcMips64::PointerSize = 8 static
Definition at line 287 of file OrcABISupport.h.
ResolverCodeSize
const unsigned llvm::orc::OrcMips64::ResolverCodeSize = 0x120 static
Definition at line 289 of file OrcABISupport.h.
TrampolineSize
const unsigned llvm::orc::OrcMips64::TrampolineSize = 40 static
Definition at line 288 of file OrcABISupport.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/OrcABISupport.h
lib/ExecutionEngine/Orc/OrcABISupport.cpp