LLVM: llvm::codeview::DebugSubsectionVisitor Class Reference
llvm::codeview::DebugSubsectionVisitor Class Reference abstract
#include "llvm/DebugInfo/CodeView/DebugSubsectionVisitor.h"
Public Member Functions
virtual ~DebugSubsectionVisitor ()=default
virtual Error visitUnknown (DebugUnknownSubsectionRef &Unknown)
virtual Error visitLines (DebugLinesSubsectionRef &Lines, const StringsAndChecksumsRef &State)=0
virtual Error visitFileChecksums (DebugChecksumsSubsectionRef &Checksums, const StringsAndChecksumsRef &State)=0
virtual Error visitInlineeLines (DebugInlineeLinesSubsectionRef &Inlinees, const StringsAndChecksumsRef &State)=0
virtual Error visitCrossModuleExports (DebugCrossModuleExportsSubsectionRef &CSE, const StringsAndChecksumsRef &State)=0
virtual Error visitCrossModuleImports (DebugCrossModuleImportsSubsectionRef &CSE, const StringsAndChecksumsRef &State)=0
virtual Error visitStringTable (DebugStringTableSubsectionRef &ST, const StringsAndChecksumsRef &State)=0
virtual Error visitSymbols (DebugSymbolsSubsectionRef &CSE, const StringsAndChecksumsRef &State)=0
virtual Error visitFrameData (DebugFrameDataSubsectionRef &FD, const StringsAndChecksumsRef &State)=0
virtual Error visitCOFFSymbolRVAs (DebugSymbolRVASubsectionRef &RVAs, const StringsAndChecksumsRef &State)=0
Detailed Description
Definition at line 35 of file DebugSubsectionVisitor.h.
Constructor & Destructor Documentation
~DebugSubsectionVisitor()
virtual llvm::codeview::DebugSubsectionVisitor::~DebugSubsectionVisitor () virtual default
Member Function Documentation
visitCOFFSymbolRVAs()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitCOFFSymbolRVAs (DebugSymbolRVASubsectionRef & RVAs, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitCrossModuleExports()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitCrossModuleExports (DebugCrossModuleExportsSubsectionRef & CSE, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitCrossModuleImports()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitCrossModuleImports (DebugCrossModuleImportsSubsectionRef & CSE, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitFileChecksums()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitFileChecksums (DebugChecksumsSubsectionRef & Checksums, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitFrameData()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitFrameData (DebugFrameDataSubsectionRef & FD, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitInlineeLines()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitInlineeLines (DebugInlineeLinesSubsectionRef & Inlinees, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitLines()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitLines (DebugLinesSubsectionRef & Lines, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitStringTable()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitStringTable (DebugStringTableSubsectionRef & ST, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitSymbols()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitSymbols (DebugSymbolsSubsectionRef & CSE, const StringsAndChecksumsRef & State) pure virtual
Referenced by llvm::codeview::visitDebugSubsection(), and visitUnknown().
visitUnknown()
virtual Error llvm::codeview::DebugSubsectionVisitor::visitUnknown (DebugUnknownSubsectionRef & Unknown) inline virtual
Definition at line 39 of file DebugSubsectionVisitor.h.
References CSE, llvm::codeview::Lines, llvm::ARM_MB::ST, llvm::Error::success(), visitCOFFSymbolRVAs(), visitCrossModuleExports(), visitCrossModuleImports(), llvm::codeview::visitDebugSubsection(), visitFileChecksums(), visitFrameData(), visitInlineeLines(), visitLines(), visitStringTable(), and visitSymbols().
Referenced by llvm::codeview::visitDebugSubsection().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/DebugSubsectionVisitor.h