LLVM: llvm::DwarfUnit Class Reference
llvm::DwarfUnit Class Reference abstract
This dwarf writer support class manages information associated with a source file.
#include "CodeGen/AsmPrinter/DwarfUnit.h"
Public Member Functions
AsmPrinter * getAsmPrinter () const
MCSymbol * getEndLabel () const
uint16_t getLanguage () const
const DICompileUnit * getCUNode () const
uint16_t getDwarfVersion () const
bool hasContent () const
Return true if this compile unit has something to write out.
std::string getParentContextString (const DIScope *Context) const
Get string containing language specific context for a global name.
virtual void addGlobalName (StringRef Name, const DIE &Die, const DIScope *Context)=0
Add a new global name to the compile unit.
virtual void addGlobalType (const DIType *Ty, const DIE &Die, const DIScope *Context)=0
Add a new global type to the compile unit.
DIE * getDIE (const DINode *D) const
Returns the DIE map slot for the specified debug variable.
DIELoc * getDIELoc ()
Returns a fresh newly allocated DIELoc.
void insertDIE (const DINode *Desc, DIE *D)
Insert DIE into the map.
void insertDIE (DIE *D)
void addFlag (DIE &Die, dwarf::Attribute Attribute)
Add a flag that is true to the DIE.
void addUInt (DIEValueList &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
Add an unsigned integer attribute data and value.
void addUInt (DIEValueList &Block, dwarf::Form Form, uint64_t Integer)
void addSInt (DIEValueList &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
Add an signed integer attribute data and value.
void addSInt (DIELoc &Die, Optional< dwarf::Form > Form, int64_t Integer)
void addString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
DIEValueList::value_iterator addLabel (DIEValueList &Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol *Label)
Add a Dwarf label attribute data and value.
void addLabel (DIELoc &Die, dwarf::Form Form, const MCSymbol *Label)
void addSectionOffset (DIE &Die, dwarf::Attribute Attribute, uint64_t Integer)
Add an offset into a section attribute data and value.
void addOpAddress (DIELoc &Die, const MCSymbol *Sym)
Add a dwarf op address data and value using the form given and an op of either DW_FORM_addr or DW_FORM_GNU_addr_index.
void addLabelDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
Add a label delta attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIE &Entry)
Add a DIE attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIEEntry Entry)
Add a DIE attribute data and value.
void addDIETypeSignature (DIE &Die, uint64_t Signature)
Add a type's DW_AT_signature and set the declaration flag.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIELoc *Loc)
Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIEBlock *Block)
Add block data.
void addSourceLine (DIE &Die, unsigned Line, const DIFile *File)
Add location information to specified debug information entry.
void addSourceLine (DIE &Die, const DILocalVariable *V)
void addSourceLine (DIE &Die, const DIGlobalVariable *G)
void addSourceLine (DIE &Die, const DISubprogram *SP)
void addSourceLine (DIE &Die, const DILabel *L)
void addSourceLine (DIE &Die, const DIType *Ty)
void addSourceLine (DIE &Die, const DIObjCProperty *Ty)
void addConstantValue (DIE &Die, const MachineOperand &MO, const DIType *Ty)
Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const ConstantInt *CI, const DIType *Ty)
void addConstantValue (DIE &Die, const APInt &Val, const DIType *Ty)
void addConstantValue (DIE &Die, const APInt &Val, bool Unsigned)
void addConstantValue (DIE &Die, uint64_t Val, const DIType *Ty)
void addConstantValue (DIE &Die, bool Unsigned, uint64_t Val)
void addConstantFPValue (DIE &Die, const MachineOperand &MO)
Add constant value entry in variable DIE.
void addConstantFPValue (DIE &Die, const ConstantFP *CFP)
void addLinkageName (DIE &Die, StringRef LinkageName)
Add a linkage name, if it isn't empty.
void addTemplateParams (DIE &Buffer, DINodeArray TParams)
Add template parameters in buffer.
void addThrownTypes (DIE &Die, DINodeArray ThrownTypes)
Add thrown types.
void addType (DIE &Entity, const DIType *Ty, dwarf::Attribute Attribute=dwarf::DW_AT_type)
Add a new type attribute to the specified entity.
DIE * getOrCreateNameSpace (const DINamespace *NS)
DIE * getOrCreateModule (const DIModule *M)
DIE * getOrCreateSubprogramDIE (const DISubprogram *SP, bool Minimal=false)
void applySubprogramAttributes (const DISubprogram *SP, DIE &SPDie, bool SkipSPAttributes=false)
DIE * createTypeDIE (const DIScope *Context, DIE &ContextDIE, const DIType *Ty)
Creates type DIE with specific context.
DIE * getOrCreateTypeDIE (const MDNode *TyNode)
Find existing DIE or create new DIE for the given type.
DIE * getOrCreateContextDIE (const DIScope *Context)
Get context owner's DIE.
void constructContainingTypeDIEs ()
Construct DIEs for types that contain vtables.
void constructSubprogramArguments (DIE &Buffer, DITypeRefArray Args)
Construct function argument DIEs.
DIE & createAndAddDIE (unsigned Tag, DIE &Parent, const DINode *N=nullptr)
Create a DIE with the given Tag, add the DIE to its parent, and call insertDIE if MD is not null.
bool useSegmentedStringOffsetsTable () const
virtual unsigned getHeaderSize () const
Compute the size of a header for this unit, not including the initial length field.
virtual void emitHeader (bool UseOffsets)=0
Emit the header for this unit, not including the initial length field.
void addStringOffsetsStart ()
Add the DW_AT_str_offsets_base attribute to the unit DIE.
void addRnglistsBase ()
Add the DW_AT_rnglists_base attribute to the unit DIE.
virtual DwarfCompileUnit & getCU ()=0
void constructTypeDIE (DIE &Buffer, const DICompositeType *CTy)
DIE::value_iterator addSectionDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addSectionDelta - Add a label delta attribute data and value.
DIE::value_iterator addSectionLabel (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label, const MCSymbol *Sec)
Add a Dwarf section label attribute data and value.
Optional< MD5::MD5Result > getMD5AsBytes (const DIFile *File) const
If the File has an MD5 checksum, return it as an MD5Result allocated in the MCContext.
DIE * createTypeDIE (const DICompositeType *Ty)
Get context owner's DIE.
Public Member Functions inherited from llvm::DIEUnit
DIEUnit (uint16_t Version, uint8_t AddrSize, dwarf::Tag UnitTag)
DIEUnit (const DIEUnit &RHS)=delete
DIEUnit (DIEUnit &&RHS)=delete
void operator= (const DIEUnit &RHS)=delete
void operator= (const DIEUnit &&RHS)=delete
void setSection (MCSection *Section)
Set the section that this DIEUnit will be emitted into.
MCSection * getSection () const
Return the section that this DIEUnit will be emitted into.
void setDebugSectionOffset (unsigned O)
unsigned getDebugSectionOffset () const
void setLength (uint64_t L)
uint64_t getLength () const
uint16_t getDwarfVersion () const
uint16_t getAddressSize () const
DIE & getUnitDie ()
const DIE & getUnitDie () const
Protected Member Functions
DwarfUnit (dwarf::Tag, const DICompileUnit *Node, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
bool applySubprogramDefinitionAttributes (const DISubprogram *SP, DIE &SPDie)
bool shareAcrossDWOCUs () const
bool isShareableAcrossCUs (const DINode *D) const
Check whether the DIE for this MDNode can be shared across CUs.
~DwarfUnit ()
DIE * getOrCreateStaticMemberDIE (const DIDerivedType *DT)
Create new static data member DIE.
virtual unsigned getOrCreateSourceID (const DIFile *File)=0
Look up the source ID for the given file.
void emitCommonHeader (bool UseOffsets, dwarf::UnitType UT)
Emit the common part of the header for this unit.
Protected Member Functions inherited from llvm::DIEUnit
virtual ~DIEUnit ()=default
The size in bytes of an address for this unit.
Protected Attributes
const DICompileUnit * CUNode
MDNode for the compile unit.
BumpPtrAllocator DIEValueAllocator
AsmPrinter * Asm
Target of Dwarf emission.
MCSymbol * EndLabel = nullptr
Emitted at the end of the CU and used to compute the CU Length field.
DwarfDebug * DD
DwarfFile * DU
DIE * IndexTyDie
An anonymous type for index type. Owned by DIEUnit.
DenseMap< const MDNode *, DIE * > MDNodeToDieMap
Tracks the mapping of unit level debug information variables to debug information entries.
std::vector< DIEBlock * > DIEBlocks
A list of all the DIEBlocks in use.
std::vector< DIELoc * > DIELocs
A list of all the DIELocs in use.
DenseMap< DIE *, const DINode * > ContainingTypeMap
This map is used to keep track of subprogram DIEs that need DW_AT_containing_type attribute.
Detailed Description
This dwarf writer support class manages information associated with a source file.
Definition at line 40 of file DwarfUnit.h.
Constructor & Destructor Documentation
DwarfUnit()
DwarfUnit::DwarfUnit (dwarf::Tag UnitTag, const DICompileUnit * Node, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU) protected
Definition at line 91 of file DwarfUnit.cpp.
~DwarfUnit()
DwarfUnit::~DwarfUnit () protected
Definition at line 104 of file DwarfUnit.cpp.
References DD, DIEBlocks, DIELocs, llvm::DwarfDebug::getDwarfVersion(), and getLanguage().
Referenced by getHeaderSize().
Member Function Documentation
addBlock() [1/2]
void DwarfUnit::addBlock (DIE & Die, dwarf::Attribute Attribute, DIELoc * Loc)
Add block data.
Definition at line 402 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), Asm, llvm::DIELoc::BestForm(), llvm::DIELoc::ComputeSize(), DD, DIELocs, DIEValueAllocator, and llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantValue(), llvm::DwarfCompileUnit::addLocationAttribute(), applySubprogramAttributes(), llvm::DwarfCompileUnit::constructCallSiteParmEntryDIEs(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructLabelDIE(), constructTypeDIE(), getDIELoc(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
addBlock() [2/2]
void DwarfUnit::addBlock (DIE & Die, dwarf::Attribute Attribute, DIEBlock * Block)
Add block data.
Definition at line 409 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), Asm, llvm::DIEBlock::BestForm(), llvm::DIEBlock::ComputeSize(), DIEBlocks, and DIEValueAllocator.
addConstantFPValue() [1/2]
void DwarfUnit::addConstantFPValue (DIE & Die, const MachineOperand & MO)
Add constant value entry in variable DIE.
Definition at line 510 of file DwarfUnit.cpp.
References Asm, assert(), llvm::APFloat::bitcastToAPInt(), DIEValueAllocator, llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::MachineOperand::getFPImm(), llvm::APInt::getRawData(), llvm::ConstantFP::getValueAPF(), llvm::MachineOperand::isFPImm(), and llvm::DataLayout::isLittleEndian().
Referenced by llvm::DwarfCompileUnit::constructLabelDIE(), getDIELoc(), and getOrCreateStaticMemberDIE().
addConstantFPValue() [2/2]
void DwarfUnit::addConstantFPValue (DIE & Die, const ConstantFP * CFP)
Definition at line 532 of file DwarfUnit.cpp.
References addConstantValue(), llvm::APFloat::bitcastToAPInt(), and llvm::ConstantFP::getValueAPF().
addConstantValue() [1/6]
void DwarfUnit::addConstantValue (DIE & Die, const MachineOperand & MO, const DIType * Ty)
Add constant value entry in variable DIE.
Definition at line 542 of file DwarfUnit.cpp.
References assert(), DD, llvm::MachineOperand::getImm(), llvm::MachineOperand::isImm(), and isUnsignedDIType().
Referenced by addConstantFPValue(), addConstantValue(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfCompileUnit::constructLabelDIE(), constructTypeDIE(), getDIELoc(), getOrCreateStaticMemberDIE(), and hasVectorBeenPadded().
addConstantValue() [2/6]
void DwarfUnit::addConstantValue (DIE & Die, const ConstantInt * CI, const DIType * Ty)
Definition at line 537 of file DwarfUnit.cpp.
References addConstantValue(), and llvm::ConstantInt::getValue().
addConstantValue() [3/6]
void DwarfUnit::addConstantValue (DIE & Die, const APInt & Val, const DIType * Ty)
Definition at line 560 of file DwarfUnit.cpp.
References addConstantValue(), DD, and isUnsignedDIType().
addConstantValue() [4/6]
void DwarfUnit::addConstantValue (DIE & Die, const APInt & Val, bool Unsigned)
Definition at line 564 of file DwarfUnit.cpp.
References addBlock(), addConstantValue(), addUInt(), Asm, DIEValueAllocator, llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::APInt::getRawData(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), and llvm::DataLayout::isLittleEndian().
addConstantValue() [5/6]
void DwarfUnit::addConstantValue (DIE & Die, uint64_t Val, const DIType * Ty)
Definition at line 549 of file DwarfUnit.cpp.
References addConstantValue(), DD, and isUnsignedDIType().
addConstantValue() [6/6]
void DwarfUnit::addConstantValue (DIE & Die, bool Unsigned, uint64_t Val)
Definition at line 553 of file DwarfUnit.cpp.
References addUInt().
addDIEEntry() [1/2]
void DwarfUnit::addDIEEntry (DIE & Die, dwarf::Attribute Attribute, DIE & Entry)
Add a DIE attribute data and value.
Definition at line 366 of file DwarfUnit.cpp.
Referenced by addType(), applySubprogramAttributes(), applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::finishEntityDefinition(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and getParentContextString().
addDIEEntry() [2/2]
void DwarfUnit::addDIEEntry (DIE & Die, dwarf::Attribute Attribute, DIEEntry Entry)
Add a DIE attribute data and value.
Definition at line 381 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), DIEValueAllocator, llvm::DIEEntry::getEntry(), llvm::DIE::getUnit(), and llvm::DIEUnit::getUnitDie().
addDIETypeSignature()
void DwarfUnit::addDIETypeSignature (DIE & Die, uint64_t Signature)
Add a type's DW_AT_signature and set the declaration flag.
Definition at line 370 of file DwarfUnit.cpp.
References addFlag(), llvm::DIEValueList::addValue(), and DIEValueAllocator.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), and getDIELoc().
addFlag()
void DwarfUnit::addFlag (DIE & Die, dwarf::Attribute Attribute)
Add a flag that is true to the DIE.
Definition at line 223 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), DD, DIEValueAllocator, and llvm::DwarfDebug::getDwarfVersion().
Referenced by addDIETypeSignature(), addRnglistsBase(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), collectCallSiteParameters(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), constructContainingTypeDIEs(), constructSubprogramArguments(), constructTypeDIE(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), hasVectorBeenPadded(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
addGlobalName()
virtual void llvm::DwarfUnit::addGlobalName (StringRef Name, const DIE & Die, const DIScope * Context) pure virtual
Add a new global name to the compile unit.
Implemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Referenced by llvm::DwarfTypeUnit::getHeaderSize(), and hasContent().
addGlobalType()
virtual void llvm::DwarfUnit::addGlobalType (const DIType * Ty, const DIE & Die, const DIScope * Context) pure virtual
Add a new global type to the compile unit.
Implemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Referenced by llvm::DwarfTypeUnit::getHeaderSize(), and hasContent().
addLabel() [1/2]
DIEValueList::value_iterator DwarfUnit::addLabel (DIEValueList & Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol * Label)
Add a Dwarf label attribute data and value.
Definition at line 292 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), and DIEValueAllocator.
Referenced by addLabel(), addOpAddress(), addSectionLabel(), and getDIELoc().
addLabel() [2/2]
void DwarfUnit::addLabel (DIELoc & Die, dwarf::Form Form, const MCSymbol * Label)
Definition at line 299 of file DwarfUnit.cpp.
References addLabel().
addLabelDelta()
void DwarfUnit::addLabelDelta (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Hi, const MCSymbol * Lo)
Add a label delta attribute data and value.
Definition at line 360 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), and DIEValueAllocator.
Referenced by getDIELoc().
addLinkageName()
void DwarfUnit::addLinkageName (DIE & Die, StringRef LinkageName)
Add a linkage name, if it isn't empty.
Definition at line 593 of file DwarfUnit.cpp.
References addString(), DD, llvm::GlobalValue::dropLLVMManglingEscape(), llvm::StringRef::empty(), and llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), applySubprogramDefinitionAttributes(), and getDIELoc().
addOpAddress()
void DwarfUnit::addOpAddress (DIELoc & Die, const MCSymbol * Sym)
Add a dwarf op address data and value using the form given and an op of either DW_FORM_addr or DW_FORM_GNU_addr_index.
Definition at line 342 of file DwarfUnit.cpp.
References addLabel(), addUInt(), DD, llvm::DwarfDebug::getAddressPool(), llvm::DwarfDebug::getDwarfVersion(), llvm::AddressPool::getIndex(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfCompileUnit::constructLabelDIE(), constructTypeDIE(), and getDIELoc().
addRnglistsBase()
void DwarfUnit::addRnglistsBase ()
Add the DW_AT_rnglists_base attribute to the unit DIE.
Definition at line 1723 of file DwarfUnit.cpp.
References addFlag(), addSectionLabel(), addString(), Asm, assert(), createTypeDIE(), D, DD, DU, llvm::StringRef::empty(), llvm::DwarfTypeUnit::getCU(), llvm::DwarfDebug::getDwarfVersion(), llvm::DIType::getName(), llvm::AsmPrinter::getObjFileLowering(), llvm::DwarfFile::getRnglistsTableBaseSym(), llvm::DIEUnit::getUnitDie(), and Name.
Referenced by getHeaderSize().
addSectionDelta()
DIE::value_iterator DwarfUnit::addSectionDelta (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Hi, const MCSymbol * Lo)
addSectionDelta - Add a label delta attribute data and value.
Definition at line 1673 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), DD, DIEValueAllocator, and llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfCompileUnit::addScopeRangeList(), addSectionLabel(), llvm::DwarfDebug::beginModule(), and getHeaderSize().
addSectionLabel()
DIE::value_iterator DwarfUnit::addSectionLabel (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label, const MCSymbol * Sec)
Add a Dwarf section label attribute data and value.
Definition at line 1682 of file DwarfUnit.cpp.
References addLabel(), addSectionDelta(), Asm, DD, llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::DwarfDebug::getDwarfVersion(), llvm::AsmPrinter::MAI, and llvm::DwarfDebug::useSplitDwarf().
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), addStringOffsetsStart(), getHeaderSize(), and llvm::DwarfCompileUnit::initStmtList().
addSectionOffset()
void DwarfUnit::addSectionOffset (DIE & Die, dwarf::Attribute Attribute, uint64_t Integer)
Add an offset into a section attribute data and value.
Definition at line 303 of file DwarfUnit.cpp.
References addUInt(), DD, and llvm::DwarfDebug::getDwarfVersion().
Referenced by getDIELoc(), and getMD5AsBytes().
addSInt() [1/2]
void DwarfUnit::addSInt (DIEValueList & Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
Add an signed integer attribute data and value.
Definition at line 246 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), llvm::DIEInteger::BestForm(), and DIEValueAllocator.
Referenced by addSInt(), constructTypeDIE(), and getDIELoc().
addSInt() [2/2]
void DwarfUnit::addSInt (DIELoc & Die, Optional< dwarf::Form > Form, int64_t Integer)
Definition at line 253 of file DwarfUnit.cpp.
References addSInt().
addSourceLine() [1/7]
void DwarfUnit::addSourceLine (DIE & Die, unsigned Line, const DIFile * File)
Add location information to specified debug information entry.
Definition at line 416 of file DwarfUnit.cpp.
References addUInt(), and llvm::None.
Referenced by addSourceLine(), llvm::DwarfCompileUnit::applyLabelAttributes(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateCommonBlock(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateStaticMemberDIE(), and getParentContextString().
addSourceLine() [2/7]
void DwarfUnit::addSourceLine (DIE & Die, const DILocalVariable * V)
Definition at line 425 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIVariable::getFile(), and llvm::DIVariable::getLine().
addSourceLine() [3/7]
void DwarfUnit::addSourceLine (DIE & Die, const DIGlobalVariable * G)
Definition at line 431 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIVariable::getFile(), and llvm::DIVariable::getLine().
addSourceLine() [4/7]
void DwarfUnit::addSourceLine (DIE & Die, const DISubprogram * SP)
Definition at line 437 of file DwarfUnit.cpp.
References addSourceLine(), assert(), and llvm::DIScope::getFile().
addSourceLine() [5/7]
void DwarfUnit::addSourceLine (DIE & Die, const DILabel * L)
Definition at line 443 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DILabel::getFile(), and llvm::DILabel::getLine().
addSourceLine() [6/7]
void DwarfUnit::addSourceLine (DIE & Die, const DIType * Ty)
Definition at line 449 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIScope::getFile(), and llvm::DIType::getLine().
addSourceLine() [7/7]
void DwarfUnit::addSourceLine (DIE & Die, const DIObjCProperty * Ty)
Definition at line 455 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIObjCProperty::getFile(), and llvm::DIObjCProperty::getLine().
addString()
void DwarfUnit::addString (DIE & Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
We always emit a reference to the string pool instead of immediate strings so that DIEs have more predictable sizes. In the case of split dwarf we emit an index into another table which gets us the static offset into the string table.
Definition at line 258 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), Asm, CUNode, DD, DIEValueAllocator, DU, llvm::DwarfStringPool::getEntry(), llvm::DwarfStringPool::getIndexedEntry(), llvm::DwarfFile::getStringPool(), llvm::DICompileUnit::isDebugDirectivesOnly(), llvm::DwarfDebug::useInlineStrings(), and useSegmentedStringOffsetsTable().
Referenced by addLinkageName(), addRnglistsBase(), llvm::DwarfCompileUnit::applyLabelAttributes(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::DwarfDebug::beginModule(), collectCallSiteParameters(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::createBaseTypeDIEs(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateCommonBlock(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateModule(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getParentContextString(), and hasVectorBeenPadded().
addStringOffsetsStart()
void DwarfUnit::addStringOffsetsStart ()
Add the DW_AT_str_offsets_base attribute to the unit DIE.
Definition at line 1716 of file DwarfUnit.cpp.
References addSectionLabel(), Asm, DU, llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfStrOffSection(), llvm::AsmPrinter::getObjFileLowering(), llvm::DwarfFile::getStringOffsetsStartSym(), and llvm::DIEUnit::getUnitDie().
Referenced by collectCallSiteParameters(), and getHeaderSize().
addTemplateParams()
void DwarfUnit::addTemplateParams (DIE & Buffer, DINodeArray TParams)
Add template parameters in buffer.
Definition at line 601 of file DwarfUnit.cpp.
Referenced by applySubprogramDefinitionAttributes(), constructTypeDIE(), getDIELoc(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
addThrownTypes()
void DwarfUnit::addThrownTypes (DIE & Die, DINodeArray ThrownTypes)
Add thrown types.
Definition at line 612 of file DwarfUnit.cpp.
References addType(), createAndAddDIE(), and llvm::TT.
Referenced by applySubprogramAttributes(), and getDIELoc().
addType()
void DwarfUnit::addType (DIE & Entity, const DIType * Ty, dwarf::Attribute Attribute = dwarf::DW_AT_type)
Add a new type attribute to the specified entity.
This takes and attribute parameter because DW_AT_friend attributes are also type references.
Definition at line 725 of file DwarfUnit.cpp.
References addDIEEntry(), assert(), and getOrCreateTypeDIE().
Referenced by addThrownTypes(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), constructContainingTypeDIEs(), constructSubprogramArguments(), constructTypeDIE(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateStaticMemberDIE(), getParentContextString(), and hasVectorBeenPadded().
addUInt() [1/2]
void DwarfUnit::addUInt (DIEValueList & Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
Add an unsigned integer attribute data and value.
Definition at line 232 of file DwarfUnit.cpp.
References llvm::DIEValueList::addValue(), assert(), llvm::DIEInteger::BestForm(), and DIEValueAllocator.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantValue(), llvm::DwarfCompileUnit::addLocationAttribute(), addOpAddress(), llvm::DwarfCompileUnit::addScopeRangeList(), addSectionOffset(), addSourceLine(), addUInt(), applySubprogramAttributes(), applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::DwarfDebug::beginModule(), collectCallSiteParameters(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLabelDIE(), constructSubprogramArguments(), constructTypeDIE(), llvm::DwarfCompileUnit::createBaseTypeDIEs(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateStaticMemberDIE(), getParentContextString(), hasVectorBeenPadded(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
addUInt() [2/2]
void DwarfUnit::addUInt (DIEValueList & Block, dwarf::Form Form, uint64_t Integer)
Definition at line 241 of file DwarfUnit.cpp.
References addUInt().
applySubprogramAttributes()
void DwarfUnit::applySubprogramAttributes (const DISubprogram * SP, DIE & SPDie, bool SkipSPAttributes = false)
Definition at line 1207 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addAccelType(), addBlock(), addDIEEntry(), addFlag(), addSourceLine(), addString(), addThrownTypes(), addType(), addUInt(), applySubprogramDefinitionAttributes(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, Asm, constructSubprogramArguments(), ContainingTypeMap, createAndAddDIE(), CUNode, DD, llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::StringRef::empty(), llvm::DISubrange::getCount(), llvm::DICompileUnit::getDebugInfoForProfiling(), getDIE(), getDIELoc(), llvm::DwarfDebug::getDwarfVersion(), llvm::AsmPrinter::getISAEncoding(), getLanguage(), llvm::DIScope::getName(), llvm::DIEUnit::getUnitDie(), IndexTyDie, llvm::isa(), llvm::AMDGPU::HSAMD::Kernel::Key::Language, Name, llvm::None, llvm::DITypeRefArray::size(), and llvm::DwarfDebug::useAppleExtensionAttributes().
Referenced by llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), getDIELoc(), and getOrCreateSubprogramDIE().
applySubprogramDefinitionAttributes()
bool DwarfUnit::applySubprogramDefinitionAttributes (const DISubprogram * SP, DIE & SPDie) protected
Definition at line 1164 of file DwarfUnit.cpp.
References addDIEEntry(), addLinkageName(), addTemplateParams(), addUInt(), assert(), DD, DU, llvm::StringRef::empty(), llvm::DwarfFile::getAbstractSPDies(), getDIE(), llvm::DIScope::getFile(), llvm::LinkageName, llvm::None, and llvm::DwarfDebug::useAllLinkageNames().
Referenced by applySubprogramAttributes().
constructContainingTypeDIEs()
void DwarfUnit::constructContainingTypeDIEs ()
Construct DIEs for types that contain vtables.
Definition at line 1449 of file DwarfUnit.cpp.
References addBlock(), addDIEEntry(), addFlag(), addSourceLine(), addString(), addType(), addUInt(), llvm::DIEValueList::addValue(), Asm, ContainingTypeMap, createAndAddDIE(), D, DD, DIEValueAllocator, llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::DIType::getAlignInBytes(), llvm::DebugHandlerBase::getBaseTypeSize(), llvm::AsmPrinter::getDataLayout(), getDIE(), llvm::DwarfDebug::getDwarfVersion(), llvm::DIType::getName(), llvm::DIType::getOffsetInBits(), llvm::DIType::getSizeInBits(), llvm::DINode::getTag(), llvm::DIType::isArtificial(), llvm::DataLayout::isLittleEndian(), llvm::DIType::isPrivate(), llvm::DIType::isProtected(), llvm::DIType::isPublic(), llvm::DIType::isVirtual(), Name, llvm::None, Size, and llvm::DwarfDebug::useDWARF2Bitfields().
Referenced by llvm::DwarfDebug::beginModule(), and getDIELoc().
constructSubprogramArguments()
void DwarfUnit::constructSubprogramArguments (DIE & Buffer, DITypeRefArray Args)
Construct function argument DIEs.
Definition at line 834 of file DwarfUnit.cpp.
References addFlag(), addType(), addUInt(), Arg, assert(), constructTypeDIE(), createAndAddDIE(), llvm::DISubroutineType::getCC(), getLanguage(), llvm::DIType::isArtificial(), llvm::DIType::isLValueReference(), llvm::DIType::isRValueReference(), llvm::AMDGPU::HSAMD::Kernel::Key::Language, N, and llvm::DITypeRefArray::size().
Referenced by applySubprogramAttributes(), and getDIELoc().
constructTypeDIE()
void DwarfUnit::constructTypeDIE (DIE & Buffer, const DICompositeType * CTy)
Definition at line 882 of file DwarfUnit.cpp.
References addBlock(), addConstantValue(), addDIEEntry(), addFlag(), addOpAddress(), addSInt(), addSourceLine(), addString(), addTemplateParams(), addType(), addUInt(), Asm, assert(), createAndAddDIE(), DD, DIEValueAllocator, llvm::StringRef::empty(), llvm::DIType::getAlignInBytes(), llvm::DICompositeType::getDiscriminator(), llvm::DICompositeType::getElements(), llvm::DIType::getExportSymbols(), llvm::DIType::getName(), llvm::DITemplateParameter::getName(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), llvm::DICompositeType::getRuntimeLang(), llvm::DIType::getSizeInBits(), llvm::AsmPrinter::getSymbol(), llvm::DINode::getTag(), llvm::DIE::getTag(), llvm::DICompositeType::getTemplateParams(), llvm::DITemplateParameter::getType(), llvm::DITemplateValueParameter::getValue(), llvm::DICompositeType::getVTableHolder(), llvm::DIType::isAppleBlockExtension(), llvm::DIType::isForwardDecl(), llvm::DIType::isObjcClassComplete(), llvm::DIType::isTypePassByReference(), llvm::DIType::isTypePassByValue(), isUnsignedDIType(), Name, llvm::None, Size, and llvm::Tag.
Referenced by llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), constructSubprogramArguments(), createTypeDIE(), getHeaderSize(), and getParentContextString().
createAndAddDIE()
DIE & DwarfUnit::createAndAddDIE (unsigned Tag, DIE & Parent, const DINode * N = nullptr)
Create a DIE with the given Tag, add the DIE to its parent, and call insertDIE if MD is not null.
Definition at line 395 of file DwarfUnit.cpp.
References llvm::DIE::addChild(), DIEValueAllocator, llvm::DIE::get(), and insertDIE().
Referenced by addThrownTypes(), applySubprogramAttributes(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), constructContainingTypeDIEs(), constructSubprogramArguments(), constructTypeDIE(), createTypeDIE(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateCommonBlock(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateModule(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and hasVectorBeenPadded().
createTypeDIE() [1/2]
DIE * DwarfUnit::createTypeDIE (const DIScope * Context, DIE & ContextDIE, const DIType * Ty)
Creates type DIE with specific context.
Definition at line 649 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addDwarfTypeUnitType(), constructTypeDIE(), createAndAddDIE(), DD, llvm::DwarfDebug::enterNonTypeUnitContext(), llvm::DwarfDebug::generateTypeUnits(), llvm::DwarfTypeUnit::getCU(), llvm::DIType::getRawName(), llvm::DINode::getTag(), llvm::DIType::isForwardDecl(), and X.
Referenced by addRnglistsBase(), getDIELoc(), getHeaderSize(), and getOrCreateTypeDIE().
createTypeDIE() [2/2]
DIE * DwarfUnit::createTypeDIE (const DICompositeType * Ty)
Get context owner's DIE.
Definition at line 633 of file DwarfUnit.cpp.
References constructTypeDIE(), Context, createAndAddDIE(), getDIE(), getOrCreateContextDIE(), llvm::DIType::getScope(), and llvm::DINode::getTag().
emitCommonHeader()
void DwarfUnit::emitCommonHeader (bool UseOffsets, dwarf::UnitType UT) protected
Emit the common part of the header for this unit.
Definition at line 1619 of file DwarfUnit.cpp.
References Asm, llvm::AsmPrinter::createTempSymbol(), DD, llvm::AsmPrinter::emitDwarfSymbolReference(), llvm::AsmPrinter::emitInt16(), llvm::AsmPrinter::emitInt32(), llvm::AsmPrinter::emitInt8(), llvm::AsmPrinter::EmitLabelDifference(), EndLabel, llvm::MCSection::getBeginSymbol(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::DwarfDebug::getDwarfVersion(), llvm::DwarfTypeUnit::getHeaderSize(), llvm::AsmPrinter::getObjFileLowering(), llvm::DIEUnit::getUnitDie(), llvm::AsmPrinter::MAI, llvm::AsmPrinter::OutStreamer, llvm::cl::Prefix, and llvm::DwarfDebug::useSectionsAsReferences().
Referenced by llvm::DwarfCompileUnit::emitHeader(), llvm::DwarfTypeUnit::emitHeader(), and getHeaderSize().
emitHeader()
virtual void llvm::DwarfUnit::emitHeader (bool UseOffsets) pure virtual
Emit the header for this unit, not including the initial length field.
Implemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Referenced by llvm::DwarfFile::emitUnit(), getHeaderSize(), and llvm::DwarfTypeUnit::setType().
getAsmPrinter()
AsmPrinter* llvm::DwarfUnit::getAsmPrinter () const inline
Definition at line 86 of file DwarfUnit.h.
References Asm.
getCU()
virtual DwarfCompileUnit& llvm::DwarfUnit::getCU () pure virtual
Implemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Referenced by getHeaderSize().
getCUNode()
const DICompileUnit* llvm::DwarfUnit::getCUNode () const inline
Definition at line 89 of file DwarfUnit.h.
References CUNode.
Referenced by llvm::DwarfDebug::beginModule(), computeIndexValue(), emitRangeList(), llvm::DwarfFile::emitUnit(), forBothCUs(), and llvm::DwarfCompileUnit::includeMinimalInlineScopes().
getDIE()
DIE * DwarfUnit::getDIE (const DINode * D) const
Returns the DIE map slot for the specified debug variable.
We delegate the request to DwarfDebug when the MDNode can be part of the type system, since DIEs for the type system can be shared across CUs and the mappings are kept in DwarfDebug.
Definition at line 205 of file DwarfUnit.cpp.
References DU, llvm::DwarfFile::getDIE(), isShareableAcrossCUs(), and MDNodeToDieMap.
Referenced by applySubprogramAttributes(), applySubprogramDefinitionAttributes(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), createTypeDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), llvm::DwarfCompileUnit::getOrCreateCommonBlock(), getOrCreateContextDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateModule(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), and hasContent().
getDIELoc()
DIELoc* llvm::DwarfUnit::getDIELoc () inline
Returns a fresh newly allocated DIELoc.
Definition at line 121 of file DwarfUnit.h.
References addBlock(), addConstantFPValue(), addConstantValue(), addDIEEntry(), addDIETypeSignature(), addFlag(), addLabel(), addLabelDelta(), addLinkageName(), addOpAddress(), addSectionOffset(), addSInt(), addSourceLine(), addString(), addTemplateParams(), addThrownTypes(), addType(), addUInt(), applySubprogramAttributes(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, constructContainingTypeDIEs(), constructSubprogramArguments(), createAndAddDIE(), createTypeDIE(), DIEValueAllocator, File, G, getOrCreateContextDIE(), getOrCreateModule(), getOrCreateNameSpace(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), llvm::MipsISD::Hi, insertDIE(), llvm::Integer, llvm::LinkageName, llvm::MipsISD::Lo, N, llvm::Tag, and Unsigned.
Referenced by applySubprogramAttributes().
getDwarfVersion()
uint16_t llvm::DwarfUnit::getDwarfVersion () const inline
Definition at line 91 of file DwarfUnit.h.
References llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfCompileUnit::addAddrTableBase().
getEndLabel()
MCSymbol* llvm::DwarfUnit::getEndLabel () const inline
Definition at line 87 of file DwarfUnit.h.
References EndLabel.
Referenced by llvm::DwarfFile::emitUnit().
getHeaderSize()
virtual unsigned llvm::DwarfUnit::getHeaderSize () const inline virtual
Compute the size of a header for this unit, not including the initial length field.
Reimplemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Definition at line 258 of file DwarfUnit.h.
References addRnglistsBase(), addSectionDelta(), addSectionLabel(), addStringOffsetsStart(), constructTypeDIE(), createTypeDIE(), D, emitCommonHeader(), emitHeader(), getCU(), llvm::DwarfDebug::getDwarfVersion(), getMD5AsBytes(), getOrCreateSourceID(), getOrCreateStaticMemberDIE(), and ~DwarfUnit().
Referenced by llvm::DwarfFile::computeSizeAndOffsetsForUnit(), llvm::DwarfCompileUnit::getHeaderSize(), and llvm::DwarfTypeUnit::getHeaderSize().
getLanguage()
uint16_t llvm::DwarfUnit::getLanguage () const inline
Definition at line 88 of file DwarfUnit.h.
References llvm::DICompileUnit::getSourceLanguage().
Referenced by applySubprogramAttributes(), computeIndexValue(), constructSubprogramArguments(), getParentContextString(), and ~DwarfUnit().
getMD5AsBytes()
Optional< MD5::MD5Result > DwarfUnit::getMD5AsBytes (const DIFile * File) const
If the File has an MD5 checksum, return it as an MD5Result allocated in the MCContext.
Definition at line 311 of file DwarfUnit.cpp.
References addSectionOffset(), Asm, assert(), llvm::MD5::MD5Result::Bytes, llvm::copy(), llvm::DIFile::CSK_MD5, DD, File, llvm::fromHex(), llvm::DwarfTypeUnit::getCU(), llvm::DIScope::getDirectory(), llvm::MCContext::getDwarfVersion(), llvm::DwarfDebug::getDwarfVersion(), llvm::MCDwarfDwoLineTable::getFile(), llvm::DIScope::getFilename(), llvm::DwarfCompileUnit::getOrCreateSourceID(), llvm::DIScope::getSource(), llvm::DIEUnit::getUnitDie(), llvm::None, and llvm::AsmPrinter::OutContext.
Referenced by emitRangeList(), getHeaderSize(), and llvm::DwarfCompileUnit::getOrCreateSourceID().
getOrCreateContextDIE()
DIE * DwarfUnit::getOrCreateContextDIE (const DIScope * Context)
Get context owner's DIE.
Definition at line 619 of file DwarfUnit.cpp.
References getDIE(), getOrCreateModule(), getOrCreateNameSpace(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), and llvm::DIEUnit::getUnitDie().
Referenced by collectCallSiteParameters(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), createTypeDIE(), getDIELoc(), llvm::DwarfCompileUnit::getOrCreateCommonBlock(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateModule(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and getOrCreateTypeDIE().
getOrCreateModule()
DIE * DwarfUnit::getOrCreateModule (const DIModule * M)
Definition at line 1108 of file DwarfUnit.cpp.
References llvm::DwarfTypeUnit::addGlobalName(), addString(), createAndAddDIE(), llvm::StringRef::empty(), llvm::DIModule::getConfigurationMacros(), getDIE(), llvm::DIModule::getIncludePath(), llvm::DIModule::getName(), getOrCreateContextDIE(), llvm::DIModule::getScope(), and llvm::DIModule::getSysRoot().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), getDIELoc(), and getOrCreateContextDIE().
getOrCreateNameSpace()
DIE * DwarfUnit::getOrCreateNameSpace (const DINamespace * NS)
Definition at line 1087 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addAccelNamespace(), addFlag(), llvm::DwarfTypeUnit::addGlobalName(), addString(), createAndAddDIE(), CUNode, DD, llvm::StringRef::empty(), getDIE(), llvm::DINamespace::getExportSymbols(), llvm::DINamespace::getName(), getOrCreateContextDIE(), llvm::DINamespace::getScope(), and Name.
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), getDIELoc(), and getOrCreateContextDIE().
getOrCreateSourceID()
virtual unsigned llvm::DwarfUnit::getOrCreateSourceID (const DIFile * File) protected pure virtual
Look up the source ID for the given file.
If none currently exists, create a new ID and insert it in the line table.
Implemented in llvm::DwarfCompileUnit.
Referenced by getHeaderSize().
getOrCreateStaticMemberDIE()
DIE * DwarfUnit::getOrCreateStaticMemberDIE (const DIDerivedType * DT) protected
Create new static data member DIE.
Definition at line 1572 of file DwarfUnit.cpp.
References addConstantFPValue(), addConstantValue(), addFlag(), addSourceLine(), addString(), addType(), addUInt(), assert(), createAndAddDIE(), llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::DIType::getAlignInBytes(), getDIE(), llvm::DIType::getName(), getOrCreateContextDIE(), llvm::DIType::getScope(), llvm::DINode::getTag(), llvm::DIE::getTag(), llvm::DIType::isPrivate(), llvm::DIType::isProtected(), llvm::DIType::isPublic(), and llvm::dwarf::isType().
Referenced by constructTypeDIE(), getHeaderSize(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
getOrCreateSubprogramDIE()
DIE * DwarfUnit::getOrCreateSubprogramDIE (const DISubprogram * SP, bool Minimal = false)
Definition at line 1132 of file DwarfUnit.cpp.
References applySubprogramAttributes(), createAndAddDIE(), getDIE(), getOrCreateContextDIE(), llvm::DIScope::getScope(), llvm::DIE::getUnit(), and llvm::DIEUnit::getUnitDie().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), getDIELoc(), getOrCreateContextDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
getOrCreateTypeDIE()
DIE * DwarfUnit::getOrCreateTypeDIE (const MDNode * TyNode)
Find existing DIE or create new DIE for the given type.
Definition at line 680 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addAccelType(), llvm::DwarfTypeUnit::addGlobalType(), assert(), Context, createTypeDIE(), CUNode, DD, llvm::dwarf::DW_FLAG_type_implementation, llvm::StringRef::empty(), getDIE(), llvm::DwarfDebug::getDwarfVersion(), llvm::DIType::getName(), getOrCreateContextDIE(), llvm::DIE::getTag(), llvm::DIE::getUnit(), and llvm::DIType::isForwardDecl().
Referenced by addType(), llvm::DwarfDebug::beginModule(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), getDIELoc(), getOrCreateContextDIE(), and getParentContextString().
getParentContextString()
std::string DwarfUnit::getParentContextString (const DIScope * Context) const
Get string containing language specific context for a global name.
Walks the metadata parent chain in a language specific manner (using the compile unit language) and returns it as a string. This is done at the metadata level because DIEs may not currently have been added to the parent context and walking the DIEs looking for names is more expensive than walking the metadata.
Definition at line 731 of file DwarfUnit.cpp.
References addDIEEntry(), addSourceLine(), addString(), addType(), addUInt(), constructTypeDIE(), DD, llvm::StringRef::empty(), llvm::DIType::getAlignInBytes(), llvm::DwarfDebug::getDwarfVersion(), llvm::DIBasicType::getEncoding(), getLanguage(), llvm::DIType::getName(), getOrCreateTypeDIE(), llvm::DIScope::getScope(), llvm::DIType::getSizeInBits(), llvm::DINode::getTag(), llvm::DIE::getTag(), llvm::DIType::isBigEndian(), llvm::dwarf::isCPlusPlus(), llvm::DIType::isForwardDecl(), llvm::DIType::isLittleEndian(), llvm::make_range(), Name, llvm::None, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateCommon< T >::rbegin(), llvm::SmallVectorTemplateCommon< T >::rend(), Size, and llvm::Tag.
Referenced by llvm::DwarfCompileUnit::addGlobalName(), llvm::DwarfCompileUnit::addGlobalNameForTypeUnit(), llvm::DwarfCompileUnit::addGlobalType(), llvm::DwarfCompileUnit::addGlobalTypeUnitType(), and hasContent().
hasContent()
bool llvm::DwarfUnit::hasContent () const inline
Return true if this compile unit has something to write out.
Definition at line 94 of file DwarfUnit.h.
References addGlobalName(), addGlobalType(), Context, D, getDIE(), getParentContextString(), llvm::DIEUnit::getUnitDie(), llvm::DIE::hasChildren(), and Name.
insertDIE() [1/2]
void DwarfUnit::insertDIE (const DINode * Desc, DIE * D)
Insert DIE into the map.
We delegate the request to DwarfDebug when the MDNode can be part of the type system, since DIEs for the type system can be shared across CUs and the mappings are kept in DwarfDebug.
Definition at line 211 of file DwarfUnit.cpp.
References DU, llvm::DwarfFile::insertDIE(), isShareableAcrossCUs(), and MDNodeToDieMap.
Referenced by llvm::DwarfCompileUnit::constructCallSiteParmEntryDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructLabelDIE(), createAndAddDIE(), and getDIELoc().
insertDIE() [2/2]
void DwarfUnit::insertDIE (DIE * D)
Definition at line 219 of file DwarfUnit.cpp.
References MDNodeToDieMap.
isShareableAcrossCUs()
bool DwarfUnit::isShareableAcrossCUs (const DINode * D) const protected
Check whether the DIE for this MDNode can be shared across CUs.
Definition at line 190 of file DwarfUnit.cpp.
References D, DD, llvm::DwarfDebug::generateTypeUnits(), and llvm::DwarfDebug::shareAcrossDWOCUs().
Referenced by getDIE(), and insertDIE().
shareAcrossDWOCUs()
bool llvm::DwarfUnit::shareAcrossDWOCUs () const protected
useSegmentedStringOffsetsTable()
bool llvm::DwarfUnit::useSegmentedStringOffsetsTable () const inline
Definition at line 252 of file DwarfUnit.h.
References llvm::DwarfDebug::useSegmentedStringOffsetsTable().
Referenced by addString().
Member Data Documentation
Asm
AsmPrinter* llvm::DwarfUnit::Asm protected
Target of Dwarf emission.
Definition at line 49 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfCompileUnit::addAddrTableBase(), addBlock(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), llvm::DwarfTypeUnit::addGlobalType(), llvm::DwarfCompileUnit::addLocationAttribute(), addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), addSectionLabel(), addString(), addStringOffsetsStart(), applySubprogramAttributes(), llvm::DwarfCompileUnit::constructCallSiteParmEntryDIEs(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructLabelDIE(), constructTypeDIE(), emitCommonHeader(), llvm::DwarfCompileUnit::emitHeader(), llvm::DwarfTypeUnit::emitHeader(), getAsmPrinter(), getMD5AsBytes(), llvm::DwarfCompileUnit::getOrCreateSourceID(), llvm::DwarfCompileUnit::initStmtList(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
ContainingTypeMap
DenseMap<DIE *, const DINode *> llvm::DwarfUnit::ContainingTypeMap protected
This map is used to keep track of subprogram DIEs that need DW_AT_containing_type attribute.
This attribute points to a DIE that corresponds to the MDNode mapped with the subprogram DIE.
Definition at line 74 of file DwarfUnit.h.
Referenced by applySubprogramAttributes(), and constructContainingTypeDIEs().
CUNode
const DICompileUnit* llvm::DwarfUnit::CUNode protected
MDNode for the compile unit.
Definition at line 43 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), addString(), applySubprogramAttributes(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), getCUNode(), getOrCreateNameSpace(), getOrCreateTypeDIE(), llvm::DwarfCompileUnit::hasDwarfPubSections(), llvm::DwarfCompileUnit::initStmtList(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
DD
DwarfDebug* llvm::DwarfUnit::DD protected
Definition at line 55 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), addBlock(), addConstantValue(), addFlag(), llvm::DwarfCompileUnit::addLabelAddress(), addLinkageName(), llvm::DwarfCompileUnit::addLocalLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfCompileUnit::addLocationList(), addOpAddress(), llvm::DwarfCompileUnit::addRange(), addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), addSectionDelta(), addSectionLabel(), addSectionOffset(), addString(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLabelDIE(), llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::DwarfCompileUnit::constructScopeDIE(), constructTypeDIE(), createTypeDIE(), emitCommonHeader(), llvm::DwarfCompileUnit::emitHeader(), llvm::DwarfTypeUnit::emitHeader(), llvm::DwarfCompileUnit::getDwarf5OrGNUAttr(), llvm::DwarfCompileUnit::getDwarf5OrGNULocationAtom(), llvm::DwarfCompileUnit::getDwarf5OrGNUTag(), getMD5AsBytes(), getOrCreateNameSpace(), getOrCreateTypeDIE(), getParentContextString(), llvm::DwarfCompileUnit::hasDwarfPubSections(), hasVectorBeenPadded(), llvm::DwarfCompileUnit::includeMinimalInlineScopes(), llvm::DwarfCompileUnit::initStmtList(), isShareableAcrossCUs(), llvm::DwarfCompileUnit::updateSubprogramScopeDIE(), and ~DwarfUnit().
DIEBlocks
std::vector<DIEBlock *> llvm::DwarfUnit::DIEBlocks protected
A list of all the DIEBlocks in use.
Definition at line 66 of file DwarfUnit.h.
Referenced by addBlock(), and ~DwarfUnit().
DIELocs
std::vector<DIELoc *> llvm::DwarfUnit::DIELocs protected
A list of all the DIELocs in use.
Definition at line 69 of file DwarfUnit.h.
Referenced by addBlock(), and ~DwarfUnit().
DIEValueAllocator
BumpPtrAllocator llvm::DwarfUnit::DIEValueAllocator protected
Definition at line 46 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfCompileUnit::addAddressExpr(), llvm::DwarfCompileUnit::addBaseTypeRef(), addBlock(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), addDIEEntry(), addDIETypeSignature(), llvm::DwarfCompileUnit::addExpr(), addFlag(), addLabel(), llvm::DwarfCompileUnit::addLabelAddress(), addLabelDelta(), llvm::DwarfCompileUnit::addLocalLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfCompileUnit::addLocationList(), addSectionDelta(), addSInt(), addString(), addUInt(), llvm::DwarfCompileUnit::applyStmtList(), llvm::DwarfCompileUnit::constructCallSiteParmEntryDIEs(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLabelDIE(), llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), constructTypeDIE(), createAndAddDIE(), llvm::DwarfCompileUnit::createBaseTypeDIEs(), getDIELoc(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
DU
DwarfFile* llvm::DwarfUnit::DU protected
Definition at line 56 of file DwarfUnit.h.
Referenced by addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), addString(), addStringOffsetsStart(), applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::createScopeChildrenDIE(), getDIE(), and insertDIE().
EndLabel
MCSymbol* llvm::DwarfUnit::EndLabel = nullptr protected
Emitted at the end of the CU and used to compute the CU Length field.
Definition at line 52 of file DwarfUnit.h.
Referenced by emitCommonHeader(), and getEndLabel().
IndexTyDie
DIE* llvm::DwarfUnit::IndexTyDie protected
An anonymous type for index type. Owned by DIEUnit.
Definition at line 59 of file DwarfUnit.h.
Referenced by applySubprogramAttributes().
MDNodeToDieMap
DenseMap<const MDNode *, DIE *> llvm::DwarfUnit::MDNodeToDieMap protected
Tracks the mapping of unit level debug information variables to debug information entries.
Definition at line 63 of file DwarfUnit.h.
Referenced by getDIE(), and insertDIE().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfUnit.h
lib/CodeGen/AsmPrinter/DwarfUnit.cpp