LLVM: llvm::xray::BlockVerifier Class Reference
llvm::xray::BlockVerifier Class Reference
#include "llvm/XRay/BlockVerifier.h"
Public Types
enum State : std::size_t {
State::Unknown, State::BufferExtents, State::NewBuffer, State::WallClockTime,
State::PIDEntry, State::NewCPUId, State::TSCWrap, State::CustomEvent,
State::TypedEvent, State::Function, State::CallArg, State::EndOfBuffer,
State::StateMax
}
Public Member Functions
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Error verify ()
void reset ()
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
Definition at line 23 of file BlockVerifier.h.
Member Enumeration Documentation
State
enum llvm::xray::BlockVerifier::State : std::size_t strong
Enumerator
Unknown
BufferExtents
NewBuffer
WallClockTime
PIDEntry
NewCPUId
TSCWrap
CustomEvent
TypedEvent
Function
CallArg
EndOfBuffer
StateMax
Definition at line 26 of file BlockVerifier.h.
Member Function Documentation
reset()
void llvm::xray::BlockVerifier::reset ()
Definition at line 201 of file BlockVerifier.cpp.
References llvm::Unknown.
verify()
Error llvm::xray::BlockVerifier::verify ()
Definition at line 182 of file BlockVerifier.cpp.
References llvm::NVPTXISD::CallArg, llvm::createStringError(), llvm::make_error_code(), and llvm::Error::success().
visit() [1/12]
Error llvm::xray::BlockVerifier::visit (BufferExtents &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 136 of file BlockVerifier.cpp.
visit() [2/12]
Error llvm::xray::BlockVerifier::visit (WallclockRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 140 of file BlockVerifier.cpp.
visit() [3/12]
Error llvm::xray::BlockVerifier::visit (NewCPUIDRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 144 of file BlockVerifier.cpp.
visit() [4/12]
Error llvm::xray::BlockVerifier::visit (TSCWrapRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 148 of file BlockVerifier.cpp.
visit() [5/12]
Error llvm::xray::BlockVerifier::visit (CustomEventRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 152 of file BlockVerifier.cpp.
visit() [6/12]
Error llvm::xray::BlockVerifier::visit (CallArgRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 164 of file BlockVerifier.cpp.
References llvm::NVPTXISD::CallArg.
visit() [7/12]
Error llvm::xray::BlockVerifier::visit (PIDRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 168 of file BlockVerifier.cpp.
visit() [8/12]
Error llvm::xray::BlockVerifier::visit (NewBufferRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 170 of file BlockVerifier.cpp.
visit() [9/12]
Error llvm::xray::BlockVerifier::visit (EndBufferRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 174 of file BlockVerifier.cpp.
visit() [10/12]
Error llvm::xray::BlockVerifier::visit (FunctionRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 178 of file BlockVerifier.cpp.
visit() [11/12]
Error llvm::xray::BlockVerifier::visit (CustomEventRecordV5 &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 156 of file BlockVerifier.cpp.
visit() [12/12]
Error llvm::xray::BlockVerifier::visit (TypedEventRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 160 of file BlockVerifier.cpp.
The documentation for this class was generated from the following files:
include/llvm/XRay/BlockVerifier.h
lib/XRay/BlockVerifier.cpp