LLVM: llvm::DWARFDebugFrame Class Reference
llvm::DWARFDebugFrame Class Reference
A parsed .debug_frame or .eh_frame section.
#include "llvm/DebugInfo/DWARF/DWARFDebugFrame.h"
Public Member Functions
DWARFDebugFrame (Triple::ArchType Arch, bool IsEH=false, uint64_t EHFrameAddress=0)
~DWARFDebugFrame ()
void dump (raw_ostream &OS, const MCRegisterInfo *MRI, Optional< uint64_t > Offset) const
Dump the section data into the given stream.
void parse (DWARFDataExtractor Data)
Parse the section from raw data.
bool empty () const
Return whether the section has any entries.
iterator begin () const
DWARF Frame entries accessors.
iterator end () const
iterator_range< iterator > entries () const
uint64_t getEHFrameAddress () const
Detailed Description
A parsed .debug_frame or .eh_frame section.
Definition at line 263 of file DWARFDebugFrame.h.
Constructor & Destructor Documentation
DWARFDebugFrame()
DWARFDebugFrame::DWARFDebugFrame (Triple::ArchType Arch, bool IsEH = false, uint64_t EHFrameAddress = 0)
Definition at line 327 of file DWARFDebugFrame.cpp.
References ~DWARFDebugFrame().
~DWARFDebugFrame()
DWARFDebugFrame::~DWARFDebugFrame () default
Referenced by DWARFDebugFrame().
Member Function Documentation
begin()
iterator llvm::DWARFDebugFrame::begin () const inline
DWARF Frame entries accessors.
Definition at line 297 of file DWARFDebugFrame.h.
dump()
void DWARFDebugFrame::dump (raw_ostream & OS, const MCRegisterInfo * MRI, Optional< uint64_t > Offset) const
Dump the section data into the given stream.
Definition at line 543 of file DWARFDebugFrame.cpp.
Referenced by llvm::DWARFContext::dump().
empty()
bool llvm::DWARFDebugFrame::empty () const inline
Return whether the section has any entries.
Definition at line 294 of file DWARFDebugFrame.h.
end()
iterator llvm::DWARFDebugFrame::end () const inline
Definition at line 298 of file DWARFDebugFrame.h.
entries()
iterator_range<iterator> llvm::DWARFDebugFrame::entries () const inline
Definition at line 299 of file DWARFDebugFrame.h.
getEHFrameAddress()
uint64_t llvm::DWARFDebugFrame::getEHFrameAddress () const inline
Definition at line 303 of file DWARFDebugFrame.h.
parse()
void DWARFDebugFrame::parse (DWARFDataExtractor Data)
Parse the section from raw data.
Data is assumed to contain the whole frame section contents to be parsed.
Definition at line 356 of file DWARFDebugFrame.cpp.
References llvm::dwarf::DW64_CIE_ID, llvm::dwarf::DW_CIE_ID, llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_omit, llvm::dwarf::DW_LENGTH_DWARF64, llvm::numbers::e, E, llvm::StringRef::empty(), llvm::DataExtractor::getAddressSize(), llvm::dwarf::CIE::getAugmentationString(), llvm::DataExtractor::getCStr(), llvm::DataExtractor::getData(), llvm::DWARFDataExtractor::getEncodedPointer(), llvm::dwarf::CIE::getFDEPointerEncoding(), llvm::dwarf::CIE::getLSDAPointerEncoding(), llvm::DWARFDataExtractor::getRelocatedAddress(), llvm::DWARFDataExtractor::getRelocatedValue(), llvm::DataExtractor::getSLEB128(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), llvm::DataExtractor::getUnsigned(), llvm::Optional< T >::hasValue(), llvm::DataExtractor::isValidOffset(), llvm::partition_point(), llvm::report_fatal_error(), ReportError(), llvm::DataExtractor::setAddressSize(), llvm::StringRef::size(), llvm::StringRef::slice(), llvm::toString(), and llvm::IndexedInstrProf::Version.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugFrame.h
lib/DebugInfo/DWARF/DWARFDebugFrame.cpp