LLVM: llvm::SectionMemoryManager::MemoryMapper Class Reference
llvm::SectionMemoryManager::MemoryMapper Class Reference abstract
Implementations of this interface are used by SectionMemoryManager to request pages from the operating system.
#include "llvm/ExecutionEngine/SectionMemoryManager.h"
Public Member Functions
virtual sys::MemoryBlock allocateMappedMemory (AllocationPurpose Purpose, size_t NumBytes, const sys::MemoryBlock *const NearBlock, unsigned Flags, std::error_code &EC)=0
This method attempts to allocate NumBytes bytes of virtual memory for Purpose.
virtual std::error_code protectMappedMemory (const sys::MemoryBlock &Block, unsigned Flags)=0
This method sets the protection flags for a block of memory to the state specified by Flags.
virtual std::error_code releaseMappedMemory (sys::MemoryBlock &M)=0
This method releases a block of memory that was allocated with the allocateMappedMemory method.
virtual ~MemoryMapper ()
Detailed Description
Implementations of this interface are used by SectionMemoryManager to request pages from the operating system.
Definition at line 52 of file SectionMemoryManager.h.
Constructor & Destructor Documentation
~MemoryMapper()
llvm::SectionMemoryManager::MemoryMapper::~MemoryMapper () virtual
Definition at line 235 of file SectionMemoryManager.cpp.
References llvm::sys::Memory::allocateMappedMemory(), llvm::sys::Memory::protectMappedMemory(), and llvm::sys::Memory::releaseMappedMemory().
Member Function Documentation
allocateMappedMemory()
virtual sys::MemoryBlock llvm::SectionMemoryManager::MemoryMapper::allocateMappedMemory (AllocationPurpose Purpose, size_t NumBytes, const sys::MemoryBlock *const NearBlock, unsigned Flags, std::error_code & EC) pure virtual
This method attempts to allocate NumBytes bytes of virtual memory for Purpose.
NearBlock may point to an existing allocation, in which case an attempt is made to allocate more memory near the existing block. The actual allocated address is not guaranteed to be near the requested address. Flags is used to set the initial protection flags for the block of the memory. EC [out] returns an object describing any error that occurs.
This method may allocate more than the number of bytes requested. The actual number of bytes allocated is indicated in the returned MemoryBlock.
The start of the allocated block must be aligned with the system allocation granularity (64K on Windows, page size on Linux). If the address following NearBlock is not so aligned, it will be rounded up to the next allocation granularity boundary.
a non-null MemoryBlock if the function was successful, otherwise a null MemoryBlock with EC describing the error.
Referenced by llvm::SectionMemoryManager::allocateCodeSection().
protectMappedMemory()
virtual std::error_code llvm::SectionMemoryManager::MemoryMapper::protectMappedMemory (const sys::MemoryBlock & Block, unsigned Flags) pure virtual
This method sets the protection flags for a block of memory to the state specified by Flags.
The behavior is not specified if the memory was not allocated using the allocateMappedMemory method. Block describes the memory block to be protected. Flags specifies the new protection state to be assigned to the block.
If Flags is MF_WRITE, the actual behavior varies with the operating system (i.e. MF_READ | MF_WRITE on Windows) and the target architecture (i.e. MF_WRITE -> MF_READ | MF_WRITE on i386).
error_success if the function was successful, or an error_code describing the failure if an error occurred.
Referenced by llvm::trimBlockToPageSize().
releaseMappedMemory()
virtual std::error_code llvm::SectionMemoryManager::MemoryMapper::releaseMappedMemory (sys::MemoryBlock & M) pure virtual
This method releases a block of memory that was allocated with the allocateMappedMemory method.
It should not be used to release any memory block allocated any other way. Block describes the memory to be released.
error_success if the function was successful, or an error_code describing the failure if an error occurred.
Referenced by llvm::SectionMemoryManager::~SectionMemoryManager().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/SectionMemoryManager.h
lib/ExecutionEngine/SectionMemoryManager.cpp