LLVM: llvm::SCEVUnionPredicate Class Reference
llvm::SCEVUnionPredicate Class Reference final
This class represents a composition of other SCEV predicates, and is the class that most clients will interact with.
#include "llvm/Analysis/ScalarEvolution.h"
Public Member Functions
SCEVUnionPredicate ()
Union predicates don't get cached so create a dummy set ID for it.
const SmallVectorImpl< const SCEVPredicate * > & getPredicates () const
void add (const SCEVPredicate *N)
Adds a predicate to this union.
ArrayRef< const SCEVPredicate * > getPredicatesForExpr (const SCEV *Expr)
Returns a reference to a vector containing all predicates which apply to Expr.
bool isAlwaysTrue () const override
Implementation of the SCEVPredicate interface.
bool implies (const SCEVPredicate *N) const override
Returns true if this predicate implies N.
void print (raw_ostream &OS, unsigned Depth) const override
Prints a textual representation of this predicate with an indentation of Depth.
const SCEV * getExpr () const override
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
unsigned getComplexity () const override
We estimate the complexity of a union predicate as the size number of predicates in the union.
Public Member Functions inherited from llvm::SCEVPredicate
SCEVPredicate (const FoldingSetNodeIDRef ID, SCEVPredicateKind Kind)
SCEV predicates.
SCEVPredicateKind getKind () const
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEVPredicate *P)
Methods for support type inquiry through isa, cast, and dyn_cast:
Additional Inherited Members
Public Types inherited from llvm::SCEVPredicate
enum SCEVPredicateKind { P_Union, P_Equal, P_Wrap }
Protected Member Functions inherited from llvm::SCEVPredicate
~SCEVPredicate ()=default
SCEVPredicate (const SCEVPredicate &)=default
SCEVPredicate & operator= (const SCEVPredicate &)=default
Protected Attributes inherited from llvm::SCEVPredicate
SCEVPredicateKind Kind
Detailed Description
This class represents a composition of other SCEV predicates, and is the class that most clients will interact with.
This is equivalent to a logical "AND" of all the predicates in the union.
NB! Unlike other SCEVPredicate sub-classes this class does not live in the ScalarEvolution::Preds folding set. This is why the add function is sound.
Definition at line 397 of file ScalarEvolution.h.
Constructor & Destructor Documentation
SCEVUnionPredicate()
SCEVUnionPredicate::SCEVUnionPredicate ()
Union predicates don't get cached so create a dummy set ID for it.
Definition at line 12392 of file ScalarEvolution.cpp.
Member Function Documentation
add()
void SCEVUnionPredicate::add (const SCEVPredicate * N)
Adds a predicate to this union.
Definition at line 12429 of file ScalarEvolution.cpp.
References assert(), llvm::SCEVPredicate::getExpr(), and implies().
Referenced by llvm::PredicatedScalarEvolution::addPredicate(), llvm::ScalarEvolution::forgetValue(), and llvm::PredicatedScalarEvolution::getAsAddRec().
classof()
static bool llvm::SCEVUnionPredicate::classof (const SCEVPredicate * P) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 433 of file ScalarEvolution.h.
References llvm::SCEVPredicate::getKind().
getComplexity()
unsigned llvm::SCEVUnionPredicate::getComplexity () const inline override virtual
We estimate the complexity of a union predicate as the size number of predicates in the union.
Reimplemented from llvm::SCEVPredicate.
Definition at line 430 of file ScalarEvolution.h.
References llvm::SmallVectorBase::size().
Referenced by isLoadConditional().
getExpr()
const SCEV * SCEVUnionPredicate::getExpr () const override virtual
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
Implements llvm::SCEVPredicate.
Definition at line 12422 of file ScalarEvolution.cpp.
getPredicates()
const SmallVectorImpl<const SCEVPredicate *>& llvm::SCEVUnionPredicate::getPredicates () const inline
Definition at line 411 of file ScalarEvolution.h.
References add(), llvm::Depth, llvm::HexagonMCInstrInfo::getExpr(), N, and llvm::SCEV::print().
Referenced by llvm::SCEVExpander::expandUnionPredicate(), and llvm::LoopVectorizationCostModel::runtimeChecksRequired().
getPredicatesForExpr()
ArrayRef< const SCEVPredicate * > SCEVUnionPredicate::getPredicatesForExpr (const SCEV * Expr)
Returns a reference to a vector containing all predicates which apply to Expr.
Definition at line 12401 of file ScalarEvolution.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::ScalarEvolution::getWrapPredicate().
implies()
bool SCEVUnionPredicate::implies (const SCEVPredicate * N) const override virtual
Returns true if this predicate implies N.
Implements llvm::SCEVPredicate.
Definition at line 12408 of file ScalarEvolution.cpp.
References llvm::all_of(), llvm::any_of(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SCEVPredicate::getExpr(), I, and llvm::SCEVPredicate::implies().
Referenced by add(), llvm::PredicatedScalarEvolution::addPredicate(), and llvm::ScalarEvolution::getWrapPredicate().
isAlwaysTrue()
bool SCEVUnionPredicate::isAlwaysTrue () const override virtual
Implementation of the SCEVPredicate interface.
Implements llvm::SCEVPredicate.
Definition at line 12395 of file ScalarEvolution.cpp.
References llvm::all_of(), I, and llvm::SCEVPredicate::isAlwaysTrue().
Referenced by llvm::LoopVersioning::annotateInstWithNoAlias(), and isLoadConditional().
print()
void SCEVUnionPredicate::print (raw_ostream & OS, unsigned Depth) const override virtual
Prints a textual representation of this predicate with an indentation of Depth.
Implements llvm::SCEVPredicate.
Definition at line 12424 of file ScalarEvolution.cpp.
Referenced by PrintLoopInfo().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolution.h
lib/Analysis/ScalarEvolution.cpp