LLVM: llvm::codeview::DebugCrossModuleExportsSubsectionRef Class Reference
llvm::codeview::DebugCrossModuleExportsSubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugCrossExSubsection.h"
Public Member Functions
DebugCrossModuleExportsSubsectionRef ()
Error initialize (BinaryStreamReader Reader)
Error initialize (BinaryStreamRef Stream)
Iterator begin () const
Iterator end () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 24 of file DebugCrossExSubsection.h.
Constructor & Destructor Documentation
DebugCrossModuleExportsSubsectionRef()
llvm::codeview::DebugCrossModuleExportsSubsectionRef::DebugCrossModuleExportsSubsectionRef () inline
Definition at line 29 of file DebugCrossExSubsection.h.
Member Function Documentation
begin()
Iterator llvm::codeview::DebugCrossModuleExportsSubsectionRef::begin () const inline
Definition at line 39 of file DebugCrossExSubsection.h.
classof()
static bool llvm::codeview::DebugCrossModuleExportsSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 32 of file DebugCrossExSubsection.h.
References llvm::codeview::CrossScopeExports, initialize(), and llvm::codeview::DebugSubsectionRef::kind().
end()
Iterator llvm::codeview::DebugCrossModuleExportsSubsectionRef::end () const inline
Definition at line 40 of file DebugCrossExSubsection.h.
initialize() [1/2]
Error DebugCrossModuleExportsSubsectionRef::initialize (BinaryStreamReader Reader)
Definition at line 18 of file DebugCrossExSubsection.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::corrupt_record, llvm::BinaryStreamReader::readArray(), and Size.
Referenced by classof(), initialize(), and llvm::codeview::visitDebugSubsection().
initialize() [2/2]
Error DebugCrossModuleExportsSubsectionRef::initialize (BinaryStreamRef Stream)
Definition at line 29 of file DebugCrossExSubsection.cpp.
References initialize().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugCrossExSubsection.h
lib/DebugInfo/CodeView/DebugCrossExSubsection.cpp