LLVM: llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst > Class Template Reference
llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst > Class Template Reference
#include "llvm/ADT/DenseMap.h"
Public Types
using difference_type = ptrdiff_t
using value_type = typename std::conditional< IsConst, const Bucket, Bucket >::type
using pointer = value_type *
using reference = value_type &
using iterator_category = std::forward_iterator_tag
Public Member Functions
DenseMapIterator ()=default
DenseMapIterator (pointer Pos, pointer E, const DebugEpochBase &Epoch, bool NoAdvance=false)
template<bool IsConstSrc, typename = typename std::enable_if<!IsConstSrc && IsConst>::type>
DenseMapIterator (const DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConstSrc > &I)
reference operator* () const
pointer operator-> () const
bool operator== (const ConstIterator &RHS) const
bool operator!= (const ConstIterator &RHS) const
DenseMapIterator & operator++ ()
DenseMapIterator operator++ (int)
Friends
class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, true >
class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, false >
Detailed Description
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst>
class llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >
Definition at line 55 of file DenseMap.h.
Member Typedef Documentation
difference_type
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> using llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::difference_type = ptrdiff_t
Definition at line 1166 of file DenseMap.h.
iterator_category
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> using llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::iterator_category = std::forward_iterator_tag
Definition at line 1171 of file DenseMap.h.
pointer
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> using llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::pointer = value_type *
Definition at line 1169 of file DenseMap.h.
reference
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> using llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::reference = value_type &
Definition at line 1170 of file DenseMap.h.
value_type
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> using llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::value_type = typename std::conditional<IsConst, const Bucket, Bucket>::type
Definition at line 1168 of file DenseMap.h.
Constructor & Destructor Documentation
DenseMapIterator() [1/3]
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::DenseMapIterator () default
DenseMapIterator() [2/3]
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::DenseMapIterator (pointer Pos, pointer E, const DebugEpochBase & Epoch, bool NoAdvance = false) inline
Definition at line 1180 of file DenseMap.h.
References assert().
DenseMapIterator() [3/3]
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> template<bool IsConstSrc, typename = typename std::enable_if<!IsConstSrc && IsConst>::type> llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::DenseMapIterator (const DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConstSrc > & I) inline
Definition at line 1198 of file DenseMap.h.
Member Function Documentation
operator!=()
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> bool llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator!= (const ConstIterator & RHS) const inline
Definition at line 1222 of file DenseMap.h.
References assert(), llvm::DebugEpochBase::HandleBase::getEpochAddress(), and llvm::DebugEpochBase::HandleBase::isHandleInSync().
operator*()
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> reference llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator* () const inline
Definition at line 1202 of file DenseMap.h.
References assert().
operator++() [1/2]
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> DenseMapIterator& llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator++ () inline
Definition at line 1230 of file DenseMap.h.
References assert().
operator++() [2/2]
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> DenseMapIterator llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator++ (int) inline
Definition at line 1241 of file DenseMap.h.
References assert(), llvm::pdb::Empty, llvm::detail::DenseMapPair< KeyT, ValueT >::getFirst(), and isEqual().
operator->()
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> pointer llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator-> () const inline
Definition at line 1208 of file DenseMap.h.
References assert().
operator==()
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> bool llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator== (const ConstIterator & RHS) const inline
Definition at line 1215 of file DenseMap.h.
References assert(), llvm::DebugEpochBase::HandleBase::getEpochAddress(), and llvm::DebugEpochBase::HandleBase::isHandleInSync().
Friends And Related Function Documentation
DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, false >
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> friend class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, false > friend
Definition at line 1161 of file DenseMap.h.
DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, true >
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> friend class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, true > friend
Definition at line 1160 of file DenseMap.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseMap.h