LLVM: llvm::StringRef Class Reference
llvm::StringRef Class Reference
StringRef - Represent a constant reference to a string, i.e.
#include "llvm/ADT/StringRef.h"
Public Types
using iterator = const char *
using const_iterator = const char *
using size_type = size_t
Public Member Functions
Iterators
iterator begin () const
iterator end () const
const unsigned char * bytes_begin () const
const unsigned char * bytes_end () const
iterator_range< const unsigned char * > bytes () const
String Operations
LLVM_NODISCARD const char * data () const
data - Get a pointer to the start of the string (which may not be null terminated).
LLVM_NODISCARD bool empty () const
empty - Check if the string is empty.
LLVM_NODISCARD size_t size () const
size - Get the string size.
LLVM_NODISCARD char front () const
front - Get the first character in the string.
LLVM_NODISCARD char back () const
back - Get the last character in the string.
template<typename Allocator >
LLVM_NODISCARD StringRef copy (Allocator &A) const
LLVM_NODISCARD bool equals (StringRef RHS) const
equals - Check for string equality, this is more efficient than compare() when the relative ordering of inequal strings isn't needed.
LLVM_NODISCARD bool equals_lower (StringRef RHS) const
equals_lower - Check for string equality, ignoring case.
LLVM_NODISCARD int compare (StringRef RHS) const
compare - Compare two strings; the result is -1, 0, or 1 if this string is lexicographically less than, equal to, or greater than the RHS.
LLVM_NODISCARD int compare_lower (StringRef RHS) const
compare_lower - Compare two strings, ignoring case.
LLVM_NODISCARD int compare_numeric (StringRef RHS) const
compare_numeric - Compare two strings, treating sequences of digits as numbers.
LLVM_NODISCARD unsigned edit_distance (StringRef Other, bool AllowReplacements=true, unsigned MaxEditDistance=0) const
Determine the edit distance between this string and another string.
LLVM_NODISCARD std::string str () const
str - Get the contents as an std::string.
LLVM_NODISCARD std::string lower () const
LLVM_NODISCARD std::string upper () const
Convert the given ASCII string to uppercase.
Operator Overloads
LLVM_NODISCARD char operator[] (size_t Index) const
template<typename T >
std::enable_if< std::is_same< T, std::string >::value, StringRef >::type & operator= (T &&Str)=delete
Disallow accidental assignment from a temporary std::string.
Type Conversions
operator std::string () const
String Predicates
LLVM_NODISCARD bool startswith (StringRef Prefix) const
Check if this string starts with the given Prefix.
LLVM_NODISCARD bool startswith_lower (StringRef Prefix) const
Check if this string starts with the given Prefix, ignoring case.
LLVM_NODISCARD bool endswith (StringRef Suffix) const
Check if this string ends with the given Suffix.
LLVM_NODISCARD bool endswith_lower (StringRef Suffix) const
Check if this string ends with the given Suffix, ignoring case.
String Searching
LLVM_NODISCARD size_t find (char C, size_t From=0) const
Search for the first character C in the string.
LLVM_NODISCARD size_t find_lower (char C, size_t From=0) const
Search for the first character C in the string, ignoring case.
LLVM_NODISCARD size_t find_if (function_ref< bool(char)> F, size_t From=0) const
Search for the first character satisfying the predicate F.
LLVM_NODISCARD size_t find_if_not (function_ref< bool(char)> F, size_t From=0) const
Search for the first character not satisfying the predicate F.
LLVM_NODISCARD size_t find (StringRef Str, size_t From=0) const
Search for the first string Str in the string.
LLVM_NODISCARD size_t find_lower (StringRef Str, size_t From=0) const
Search for the first string Str in the string, ignoring case.
LLVM_NODISCARD size_t rfind (char C, size_t From=npos) const
Search for the last character C in the string.
LLVM_NODISCARD size_t rfind_lower (char C, size_t From=npos) const
Search for the last character C in the string, ignoring case.
LLVM_NODISCARD size_t rfind (StringRef Str) const
Search for the last string Str in the string.
LLVM_NODISCARD size_t rfind_lower (StringRef Str) const
Search for the last string Str in the string, ignoring case.
LLVM_NODISCARD size_t find_first_of (char C, size_t From=0) const
Find the first character in the string that is C, or npos if not found.
LLVM_NODISCARD size_t find_first_of (StringRef Chars, size_t From=0) const
Find the first character in the string that is in Chars, or npos if not found.
LLVM_NODISCARD size_t find_first_not_of (char C, size_t From=0) const
Find the first character in the string that is not C or npos if not found.
LLVM_NODISCARD size_t find_first_not_of (StringRef Chars, size_t From=0) const
Find the first character in the string that is not in the string Chars, or npos if not found.
LLVM_NODISCARD size_t find_last_of (char C, size_t From=npos) const
Find the last character in the string that is C, or npos if not found.
LLVM_NODISCARD size_t find_last_of (StringRef Chars, size_t From=npos) const
Find the last character in the string that is in C, or npos if not found.
LLVM_NODISCARD size_t find_last_not_of (char C, size_t From=npos) const
Find the last character in the string that is not C, or npos if not found.
LLVM_NODISCARD size_t find_last_not_of (StringRef Chars, size_t From=npos) const
Find the last character in the string that is not in Chars, or npos if not found.
LLVM_NODISCARD bool contains (StringRef Other) const
Return true if the given string is a substring of *this, and false otherwise.
LLVM_NODISCARD bool contains (char C) const
Return true if the given character is contained in *this, and false otherwise.
LLVM_NODISCARD bool contains_lower (StringRef Other) const
Return true if the given string is a substring of *this, and false otherwise.
LLVM_NODISCARD bool contains_lower (char C) const
Return true if the given character is contained in *this, and false otherwise.
Helpful Algorithms
LLVM_NODISCARD size_t count (char C) const
Return the number of occurrences of C in the string.
size_t count (StringRef Str) const
Return the number of non-overlapped occurrences of Str in the string.
template<typename T >
std::enable_if< std::numeric_limits< T >::is_signed, bool >::type getAsInteger (unsigned Radix, T &Result) const
Parse the current string as an integer of the specified radix.
template<typename T >
std::enable_if<!std::numeric_limits< T >::is_signed, bool >::type getAsInteger (unsigned Radix, T &Result) const
template<typename T >
std::enable_if< std::numeric_limits< T >::is_signed, bool >::type consumeInteger (unsigned Radix, T &Result)
Parse the current string as an integer of the specified radix.
template<typename T >
std::enable_if<!std::numeric_limits< T >::is_signed, bool >::type consumeInteger (unsigned Radix, T &Result)
bool getAsInteger (unsigned Radix, APInt &Result) const
Parse the current string as an integer of the specified Radix, or of an autosensed radix if the Radix given is 0.
bool getAsDouble (double &Result, bool AllowInexact=true) const
Parse the current string as an IEEE double-precision floating point value.
Substring Operations
LLVM_NODISCARD StringRef substr (size_t Start, size_t N=npos) const
Return a reference to the substring from [Start, Start + N).
LLVM_NODISCARD StringRef take_front (size_t N=1) const
Return a StringRef equal to 'this' but with only the first N elements remaining.
LLVM_NODISCARD StringRef take_back (size_t N=1) const
Return a StringRef equal to 'this' but with only the last N elements remaining.
LLVM_NODISCARD StringRef take_while (function_ref< bool(char)> F) const
Return the longest prefix of 'this' such that every character in the prefix satisfies the given predicate.
LLVM_NODISCARD StringRef take_until (function_ref< bool(char)> F) const
Return the longest prefix of 'this' such that no character in the prefix satisfies the given predicate.
LLVM_NODISCARD StringRef drop_front (size_t N=1) const
Return a StringRef equal to 'this' but with the first N elements dropped.
LLVM_NODISCARD StringRef drop_back (size_t N=1) const
Return a StringRef equal to 'this' but with the last N elements dropped.
LLVM_NODISCARD StringRef drop_while (function_ref< bool(char)> F) const
Return a StringRef equal to 'this', but with all characters satisfying the given predicate dropped from the beginning of the string.
LLVM_NODISCARD StringRef drop_until (function_ref< bool(char)> F) const
Return a StringRef equal to 'this', but with all characters not satisfying the given predicate dropped from the beginning of the string.
bool consume_front (StringRef Prefix)
Returns true if this StringRef has the given prefix and removes that prefix.
bool consume_back (StringRef Suffix)
Returns true if this StringRef has the given suffix and removes that suffix.
LLVM_NODISCARD StringRef slice (size_t Start, size_t End) const
Return a reference to the substring from [Start, End).
LLVM_NODISCARD std::pair< StringRef, StringRef > split (char Separator) const
Split into two substrings around the first occurrence of a separator character.
LLVM_NODISCARD std::pair< StringRef, StringRef > split (StringRef Separator) const
Split into two substrings around the first occurrence of a separator string.
LLVM_NODISCARD std::pair< StringRef, StringRef > rsplit (StringRef Separator) const
Split into two substrings around the last occurrence of a separator string.
void split (SmallVectorImpl< StringRef > &A, StringRef Separator, int MaxSplit=-1, bool KeepEmpty=true) const
Split into substrings around the occurrences of a separator string.
void split (SmallVectorImpl< StringRef > &A, char Separator, int MaxSplit=-1, bool KeepEmpty=true) const
Split into substrings around the occurrences of a separator character.
LLVM_NODISCARD std::pair< StringRef, StringRef > rsplit (char Separator) const
Split into two substrings around the last occurrence of a separator character.
LLVM_NODISCARD StringRef ltrim (char Char) const
Return string with consecutive Char characters starting from the the left removed.
LLVM_NODISCARD StringRef ltrim (StringRef Chars=" \\\) const
Return string with consecutive characters in Chars starting from the left removed.
LLVM_NODISCARD StringRef rtrim (char Char) const
Return string with consecutive Char characters starting from the right removed.
LLVM_NODISCARD StringRef rtrim (StringRef Chars=" \\\) const
Return string with consecutive characters in Chars starting from the right removed.
LLVM_NODISCARD StringRef trim (char Char) const
Return string with consecutive Char characters starting from the left and right removed.
LLVM_NODISCARD StringRef trim (StringRef Chars=" \\\) const
Return string with consecutive characters in Chars starting from the left and right removed.
Static Public Attributes
static const size_t npos = ~size_t(0)
Constructors
StringRef ()=default
Construct an empty string ref.
StringRef (std::nullptr_t)=delete
Disable conversion from nullptr.
constexpr StringRef (const char *Str)
Construct a string ref from a cstring.
constexpr StringRef (const char *data, size_t length)
Construct a string ref from a pointer and length.
StringRef (const std::string &Str)
Construct a string ref from an std::string.
static StringRef withNullAsEmpty (const char *data)
Detailed Description
StringRef - Represent a constant reference to a string, i.e.
a character array and a length, which need not be null terminated.
This class does not own the string data, it is expected to be used in situations where the character data resides in some other buffer, whose lifetime extends past that of the StringRef. For this reason, it is not in general safe to store a StringRef.
Definition at line 54 of file StringRef.h.
Member Typedef Documentation
const_iterator
using llvm::StringRef::const_iterator = const char *
Definition at line 59 of file StringRef.h.
iterator
using llvm::StringRef::iterator = const char *
Definition at line 58 of file StringRef.h.
size_type
using llvm::StringRef::size_type = size_t
Definition at line 60 of file StringRef.h.
Constructor & Destructor Documentation
StringRef() [1/5]
llvm::StringRef::StringRef () default
Construct an empty string ref.
Referenced by copy(), rsplit(), split(), and withNullAsEmpty().
StringRef() [2/5]
llvm::StringRef::StringRef (std::nullptr_t) delete
Disable conversion from nullptr.
This prevents things like if (S == nullptr)
StringRef() [3/5]
constexpr llvm::StringRef::StringRef (const char * Str) inline
Construct a string ref from a cstring.
Definition at line 103 of file StringRef.h.
StringRef() [4/5]
constexpr llvm::StringRef::StringRef (const char * data, size_t length) inline
Construct a string ref from a pointer and length.
Definition at line 107 of file StringRef.h.
StringRef() [5/5]
llvm::StringRef::StringRef (const std::string & Str) inline
Construct a string ref from an std::string.
Definition at line 111 of file StringRef.h.
Member Function Documentation
back()
LLVM_NODISCARD char llvm::StringRef::back () const inline
back - Get the last character in the string.
Definition at line 162 of file StringRef.h.
References assert(), and empty().
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::CodeViewDebug::CodeViewDebug(), FindFirstMatchingPrefix(), llvm::opt::OptTable::findNearest(), getTypeNamePrefix(), llvm::MCSymbolXCOFF::getUnqualifiedName(), llvm::ConstantDataSequential::isCString(), optimizeDoubleFP(), llvm::parseCachePruningPolicy(), parseDuration(), llvm::Pattern::parsePattern(), parsePhysicalReg(), PrintCFIEscape(), PrintQuotedString(), llvm::sys::path::replace_path_prefix(), srcMgrDiagHandler(), truncateToSize(), and unescapeQuotedString().
begin()
iterator llvm::StringRef::begin () const inline
Definition at line 122 of file StringRef.h.
Referenced by annotateNonNullAndDereferenceable(), llvm::SmallString< 256 >::append(), llvm::sys::path::append(), llvm::pdb::NamedStreamMap::appendStringData(), llvm::SmallString< 256 >::assign(), llvm::MDString::begin(), bytes_begin(), chopOneUTF32(), llvm::detail::IEEEFloat::convertFromString(), llvm::detail::IEEEFloat::convertFromZeroExtendedInteger(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), copy(), CountNumNewlinesBetween(), llvm::sys::fs::createTemporaryFile(), decodeUTF8(), llvm::MCObjectStreamer::EmitBytes(), emitSignedInt64(), llvm::yaml::escape(), getAttrKindEncoding(), llvm::APInt::getBitsNeeded(), llvm::MemoryBufferRef::getBufferStart(), llvm::sys::detail::getHostCPUNameForPowerPC(), getHostID(), llvm::TGLexer::getLoc(), llvm::object::Archive::Symbol::getName(), llvm::object::Archive::getNumberOfSymbols(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::WasmObjectFile::getRelocationTypeName(), llvm::object::MachOObjectFile::getRelocationTypeName(), llvm::object::COFFObjectFile::getRelocationTypeName(), llvm::ConstantDataArray::getString(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::yaml::ScalarNode::getValue(), llvm::TextInstrProfReader::hasFormat(), llvm::hash_value(), llvm::pdb::hashStringV2(), llvm::detail::IEEEFloat::IEEEFloat(), llvm::Timer::init(), llvm::TGLexer::Lex(), llvm::pdb::NamedStreamMap::load(), llvm::MIToken::location(), llvm::sys::fs::make_absolute(), mangleCoveragePath(), llvm::object::MachOUniversalBinary::ObjectForArch::ObjectForArch(), llvm::SmallString< 256 >::operator+=(), llvm::sys::path::const_iterator::operator==(), llvm::sys::path::reverse_iterator::operator==(), llvm::object::Archive::Child::operator==(), llvm::opt::OptTable::OptTable(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::InlineAsm::ParseConstraints(), parseMaybeMangledName(), parsePhysicalReg(), printName(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::sys::path::replace_extension(), llvm::AsmLexer::setBuffer(), llvm::EngineBuilder::setMArch(), llvm::EngineBuilder::setMCPU(), llvm::TimerGroup::setName(), llvm::yaml::Document::skip(), llvm::Regex::sub(), llvm::object::Archive::symbol_begin(), llvm::TGLexer::TGLexer(), llvm::cl::tokenizeConfigFile(), llvm::APInt::ushl_sat(), and llvm::ValueSymbolTable::~ValueSymbolTable().
bytes()
iterator_range<const unsigned char *> llvm::StringRef::bytes () const inline
Definition at line 132 of file StringRef.h.
References bytes_begin(), bytes_end(), LLVM_NODISCARD, and llvm::make_range().
Referenced by llvm::ConstantFoldLoadFromConstPtr(), llvm::djbHash(), llvm::MCTargetStreamer::emitRawBytes(), and PrintQuotedString().
bytes_begin()
const unsigned char* llvm::StringRef::bytes_begin () const inline
Definition at line 126 of file StringRef.h.
References begin().
Referenced by llvm::arrayRefFromStringRef(), llvm::object::ELFFile< ELFT >::base(), bytes(), llvm::MDString::bytes_begin(), llvm::codeview::consume(), llvm::NVPTXTargetStreamer::emitRawBytes(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::DWARFFormValue::extractValue(), llvm::ConstantDataArray::getString(), loadTestingFormat(), promoteToConstantPool(), llvm::xray::readBinaryFormatHeader(), llvm::readPGOFuncNameStrings(), rotateSign(), and llvm::xxHash64().
bytes_end()
const unsigned char* llvm::StringRef::bytes_end () const inline
Definition at line 129 of file StringRef.h.
References end().
Referenced by llvm::arrayRefFromStringRef(), bytes(), llvm::MDString::bytes_end(), llvm::codeview::consume(), promoteToConstantPool(), llvm::readPGOFuncNameStrings(), rotateSign(), and llvm::xxHash64().
compare()
LLVM_NODISCARD int llvm::StringRef::compare (StringRef RHS) const inline
compare - Compare two strings; the result is -1, 0, or 1 if this string is lexicographically less than, equal to, or greater than the RHS.
Definition at line 195 of file StringRef.h.
References compare_lower(), compare_numeric(), edit_distance(), LLVM_NODISCARD, and llvm::Other.
Referenced by annotateNonNullAndDereferenceable(), llvm::FunctionComparator::cmpMem(), llvm::SmallString< 256 >::compare(), compareNames(), llvm::operator<(), llvm::operator<=(), llvm::operator>(), llvm::operator>=(), and llvm::opt::OptTable::suggestValueCompletions().
compare_lower()
int StringRef::compare_lower (StringRef RHS) const
compare_lower - Compare two strings, ignoring case.
compare_lower - Compare strings, ignoring case.
Definition at line 38 of file StringRef.cpp.
References ascii_strncasecmp().
Referenced by compare(), llvm::SmallString< 256 >::compare_lower(), equals_lower(), gsiRecordLess(), parseHexOcta(), and llvm::DetectRoundChange::runOnMachineFunction().
compare_numeric()
int StringRef::compare_numeric (StringRef RHS) const
compare_numeric - Compare two strings, treating sequences of digits as numbers.
compare_numeric - Compare strings, handle embedded numbers.
Definition at line 64 of file StringRef.cpp.
References E, I, and llvm::isDigit().
Referenced by compare(), and llvm::SmallString< 256 >::compare_numeric().
consume_back()
bool llvm::StringRef::consume_back (StringRef Suffix) inline
Returns true if this StringRef has the given suffix and removes that suffix.
Definition at line 681 of file StringRef.h.
References drop_back(), endswith(), LLVM_NODISCARD, and size().
Referenced by checkParametrizedPassName(), matchRegisterNameHelper(), llvm::orc::DumpObjects::operator()(), parseDevirtPassName(), parseRepeatPassName(), and llvm::VFABI::tryDemangleForVFABI().
consume_front()
bool llvm::StringRef::consume_front (StringRef Prefix) inline
Returns true if this StringRef has the given prefix and removes that prefix.
Definition at line 671 of file StringRef.h.
References drop_front(), size(), and startswith().
Referenced by llvm::Annotations::Annotations(), checkParametrizedPassName(), llvm::detail::HelperFunctions::consumeHexStyle(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::format_provider< T, typename std::enable_if< detail::use_integral_formatter< T >::value >::type >::format(), llvm::format_provider< T, typename std::enable_if< detail::use_double_formatter< T >::value >::type >::format(), llvm::Triple::getOSVersion(), isLoopPassName(), parseDevirtPassName(), parseMagic(), parseRepeatPassName(), llvm::MCContext::setGenDwarfRootFile(), and llvm::VFABI::tryDemangleForVFABI().
consumeInteger() [1/2]
template<typename T > std::enable_if<std::numeric_limits<T>::is_signed, bool>::type llvm::StringRef::consumeInteger (unsigned Radix, T & Result) inline
Parse the current string as an integer of the specified radix.
If Radix is specified as zero, this does radix autosensing using extended C rules: 0 is octal, 0x is hex, 0b is binary.
If the string does not begin with a number of the specified radix, this returns true to signify the error. The string is considered erroneous if empty or if it overflows T. The portion of the string representing the discovered numeric value is removed from the beginning of the string.
Definition at line 533 of file StringRef.h.
References llvm::consumeSignedInteger().
Referenced by llvm::formatv_object_base::consumeFieldLayout(), llvm::detail::HelperFunctions::consumeNumHexDigits(), llvm::format_provider< T, typename std::enable_if< detail::use_integral_formatter< T >::value >::type >::format(), llvm::formatv_object_base::parseReplacementItem(), popFront(), llvm::AMDGPUPALMetadata::setFromString(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
consumeInteger() [2/2]
template<typename T > std::enable_if<!std::numeric_limits<T>::is_signed, bool>::type llvm::StringRef::consumeInteger (unsigned Radix, T & Result) inline
Definition at line 544 of file StringRef.h.
References llvm::consumeUnsignedInteger(), getAsDouble(), getAsInteger(), LLVM_NODISCARD, lower(), and upper().
contains() [1/2]
LLVM_NODISCARD bool llvm::StringRef::contains (StringRef Other) const inline
Return true if the given string is a substring of *this, and false otherwise.
Definition at line 453 of file StringRef.h.
References find(), LLVM_NODISCARD, and npos.
Referenced by AddCalls(), llvm::object::getNameType(), llvm::GCNSubtarget::initializeSubtargetDependencies(), instrumentMaskedLoadOrStore(), llvm::object::isDecorated(), llvm::PassArgFilter< Args >::operator()(), llvm::gsym::operator<<(), llvm::UpgradeDataLayoutString(), useStringTable(), llvm::Function::viewCFG(), llvm::Function::viewCFGOnly(), writeCFGToDotFile(), and llvm::PrintIRInstrumentation::~PrintIRInstrumentation().
contains() [2/2]
LLVM_NODISCARD bool llvm::StringRef::contains (char C) const inline
Return true if the given character is contained in *this, and false otherwise.
Definition at line 458 of file StringRef.h.
References find_first_of(), LLVM_NODISCARD, and npos.
contains_lower() [1/2]
LLVM_NODISCARD bool llvm::StringRef::contains_lower (StringRef Other) const inline
Return true if the given string is a substring of *this, and false otherwise.
Definition at line 463 of file StringRef.h.
References find_lower(), LLVM_NODISCARD, and npos.
contains_lower() [2/2]
LLVM_NODISCARD bool llvm::StringRef::contains_lower (char C) const inline
Return true if the given character is contained in *this, and false otherwise.
Definition at line 470 of file StringRef.h.
References find_lower(), LLVM_NODISCARD, and npos.
copy()
template<typename Allocator > LLVM_NODISCARD StringRef llvm::StringRef::copy (Allocator & A) const inline
Definition at line 169 of file StringRef.h.
References begin(), llvm::copy(), empty(), end(), LLVM_NODISCARD, and StringRef().
Referenced by llvm::sampleprof::ProfileSymbolList::add(), and llvm::yaml::Document::parseBlockNode().
count() [1/2]
LLVM_NODISCARD size_t llvm::StringRef::count (char C) const inline
Return the number of occurrences of C in the string.
Definition at line 478 of file StringRef.h.
References llvm::numbers::e.
Referenced by llvm::SmallString< 256 >::count(), FindFirstMatchingPrefix(), llvm::HexagonInstrInfo::getInlineAsmLength(), llvm::yaml::MappingTraits< Argument >::mapping(), and llvm::InlineAsm::ConstraintInfo::Parse().
count() [2/2]
size_t StringRef::count (StringRef Str) const
Return the number of non-overlapped occurrences of Str in the string.
count - Return the number of non-overlapped occurrences of
Str in the string.
Definition at line 373 of file StringRef.cpp.
References llvm::numbers::e, equals(), N, size(), and substr().
data()
LLVM_NODISCARD const char* llvm::StringRef::data () const inline
data - Get a pointer to the start of the string (which may not be null terminated).
Definition at line 143 of file StringRef.h.
References LLVM_NODISCARD.
Referenced by llvm::SourceMgr::AddIncludeFile(), llvm::FoldingSetNodeID::AddString(), llvm::msgpack::Document::addString(), annotateAllFunctions(), llvm::CachedHashString::CachedHashString(), llvm::FileCheckString::CheckNext(), llvm::FileCheckString::CheckSame(), llvm::object::coffnamecpy(), llvm::zlib::compress(), llvm::ConvertUTF8toWide(), llvm::yaml::MappingTraits< T >::NormalizedTBD::copyString(), CopyStringRef(), llvm::zlib::crc32(), llvm::StringMapEntry< llvm::Comdat >::Create(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::X86Operand::CreateToken(), llvm::DWARFUnit::determineStringOffsetsTableContribution(), llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::DWARFDebugPubTable::dump(), llvm::DWARFListTableHeader::dump(), llvm::DWARFDebugLine::Prologue::dump(), llvm::DWARFDebugLoclists::dumpRawEntry(), edit_distance(), llvm::BitstreamWriter::emitBlob(), EmitFileEntry(), llvm::InstrProfRecordWriterTrait::EmitKey(), llvm::DWARFYAML::EmitPubSection(), llvm::RuntimeDyldImpl::emitSection(), encodeCnt(), llvm::cl::Option::error(), llvm::BitstreamWriter::ExitBlock(), llvm::AccelTableBase::finalize(), FindFirstMatchingPrefix(), llvm::pdb::DIASession::findSourceFiles(), FixedPointIntrinsicToOpcode(), llvm::json::fixUTF8(), llvm::RuntimeDyldCOFFAArch64::generateRelocationStub(), llvm::RuntimeDyldCOFFX86_64::generateRelocationStub(), llvm::irsymtab::storage::Str::get(), llvm::object::ArchiveMemberHeader::getAccessMode(), llvm::object::Archive::Child::getBuffer(), llvm::object::Archive::Child::getChildOffset(), llvm::DataExtractor::getCStr(), llvm::LTOModule::getDependentLibrary(), getFilename(), llvm::object::ArchiveMemberHeader::getGID(), llvm::sampleprof::FunctionSamples::getGUID(), llvm::DenseMapInfo< StringRef >::getHashValue(), llvm::HexagonInstrInfo::getInlineAsmLength(), getInstructionID(), llvm::object::ArchiveMemberHeader::getLastModified(), getMemBufferCopyImpl(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::Elf_Sym_Impl< ELFT >::getName(), llvm::sampleprof::FunctionSamples::getNameInModule(), llvm::object::Archive::Child::getNext(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), llvm::FileCheckPatternContext::getPatternVarValue(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::SparcTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ArchiveMemberHeader::getSize(), llvm::DataExtractor::getSLEB128(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU24(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::object::ArchiveMemberHeader::getUID(), llvm::AMDGPUMangledLibFunc::getUnmangledName(), gsiRecordLess(), llvm::SHA1::hash(), llvm::pdb::hashStringV1(), llvm::OpenMPIRBuilder::initialize(), llvm::MIRParserImpl::initializeJumpTableInfo(), llvm::ExecutionEngine::InitializeMemory(), llvm::yaml::ScalarTraits< char_16 >::input(), llvm::jitlink::MachOLinkGraphBuilder::isAltEntry(), isAsmComment(), llvm::DeclMapInfo::isEqual(), llvm::DenseMapInfo< StringRef >::isEqual(), isMips64EL(), isRootFile(), llvm::json::isUTF8(), llvm::jitlink::jitLink_MachO(), LLVMDITypeGetName(), LLVMGetAsString(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetNamedMetadataName(), LLVMGetStructName(), LLVMTargetMachineEmitToMemoryBuffer(), loadTestingFormat(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), llvm::TargetIntrinsicInfo::lookupName(), llvm::LegalizerHelper::lowerReadRegister(), llvm::remarks::magicToFormat(), llvm::LTOModule::makeBuffer(), llvm::codeview::CodeViewRecordIO::mapStringZ(), llvm::Regex::match(), llvm::Pattern::match(), llvm::MCInstPrinter::matchAliasPatterns(), llvm::sys::path::native(), llvm::MCJIT::notifyFreeingObject(), llvm::MCJIT::notifyObjectLoaded(), llvm::operator+=(), llvm::raw_ostream::operator<<(), llvm::remarks::ParsedStringTable::operator[](), optimizeMemCmpConstantSize(), llvm::remarks::ParsedStringTable::ParsedStringTable(), llvm::cl::ParseEnvironmentOptions(), llvm::remarks::parseFormat(), llvm::Pattern::parsePattern(), parseStrTab(), parseStrTabSize(), parseTypeIdSummaryRecord(), parseV2DirFileTables(), parseVersion(), parseWholeProgramDevirtResolution(), llvm::PassNameParser::passRegistered(), llvm::AsmLexer::peekTokens(), llvm::X86Operand::print(), llvm::ScopedPrinter::printBinary(), llvm::ScopedPrinter::printBinaryBlock(), llvm::BitcodeAnalyzer::printStats(), llvm::Pattern::printSubstitutions(), llvm::RuntimeDyldELF::processRelocationRef(), ProvideOption(), llvm::irsymtab::readBitcode(), llvm::FileCheck::readCheckFile(), readCoverageMappingData(), llvm::GCOVBuffer::readInt(), llvm::Regex::Regex(), llvm::report_fatal_error(), reportError(), llvm::StringSaver::save(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent(), llvm::jitlink::Block::setContent(), llvm::AMDGPUPALMetadata::setFromBlob(), llvm::X86Operand::setTokenValue(), sub(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::codeview::TypeServer2Record::TypeServer2Record(), llvm::zlib::uncompress(), llvm::MachO::InterfaceFile::undefineds(), llvm::SHA1::update(), llvm::MD5::update(), llvm::yaml::MappingTraits< ELFYAML::Symbol >::validate(), validateMagicNumber(), llvm::StringTableBuilder::write(), llvm::writeFileAtomically(), writeIdentificationBlock(), and writeUstarHeader().
drop_back()
LLVM_NODISCARD StringRef llvm::StringRef::drop_back (size_t N = 1) const inline
Return a StringRef equal to 'this' but with the last N elements dropped.
Definition at line 650 of file StringRef.h.
References assert(), LLVM_NODISCARD, N, size(), and substr().
Referenced by consume_back(), llvm::GlobPattern::create(), encodeCnt(), hasPrefix(), intToken(), llvm::ConstantDataSequential::isCString(), isReportingError(), makeCombineInst(), mapNameAndUniqueName(), llvm::yaml::Document::parseBlockNode(), llvm::parseCachePruningPolicy(), rtrim(), smallData(), and take_front().
drop_front()
LLVM_NODISCARD StringRef llvm::StringRef::drop_front (size_t N = 1) const inline
Return a StringRef equal to 'this' but with the first N elements dropped.
Definition at line 642 of file StringRef.h.
References assert(), LLVM_NODISCARD, N, size(), and substr().
Referenced by llvm::Annotations::Annotations(), chopOneUTF32(), consume_front(), llvm::formatv_object_base::consumeFieldLayout(), llvm::consumeSignedInteger(), llvm::GlobPattern::create(), llvm::DWARFGdbIndex::dump(), encodeCnt(), find_if(), find_lower(), FindCheckType(), FindFirstMatchingPrefix(), findTargetSubtable(), llvm::fromHex(), llvm::getFuncNameWithoutPrefix(), llvm::InstrProfSymtab::getOrigFuncName(), llvm::getTypeName(), isIFunc(), lexName(), ltrim(), MatchCoprocessorOperandName(), matchSVEPredicateVectorRegName(), llvm::PassInfoMixin< PromotePass >::name(), llvm::formatv_object_base::parseReplacementItem(), parseStrTab(), parseStrTabSize(), parseVersion(), popFront(), printSourceLine(), llvm::FileCheck::readCheckFile(), RefineErrorLoc(), llvm::MCContext::setGenDwarfRootFile(), llvm::formatv_object_base::splitLiteralAndReplacement(), take_back(), upgradeLoopTag(), and verifyAddrSpace().
drop_until()
LLVM_NODISCARD StringRef llvm::StringRef::drop_until (function_ref< bool(char)> F) const inline
Return a StringRef equal to 'this', but with all characters not satisfying the given predicate dropped from the beginning of the string.
Definition at line 665 of file StringRef.h.
References F(), find_if(), and substr().
drop_while()
LLVM_NODISCARD StringRef llvm::StringRef::drop_while (function_ref< bool(char)> F) const inline
Return a StringRef equal to 'this', but with all characters satisfying the given predicate dropped from the beginning of the string.
Definition at line 658 of file StringRef.h.
References F(), find_if_not(), LLVM_NODISCARD, and substr().
edit_distance()
unsigned StringRef::edit_distance (llvm::StringRef Other, bool AllowReplacements = true, unsigned MaxEditDistance = 0) const
Determine the edit distance between this string and another string.
Parameters
Other the string to compare this string against.
AllowReplacements whether to allow character replacements (change one character into another) as a single operation, rather than as two operations (an insertion and a removal).
MaxEditDistance If non-zero, the maximum edit distance that this routine is allowed to compute. If the edit distance will exceed that maximum, returns MaxEditDistance+1.
Returns
the minimum number of character insertions, removals, or (if AllowReplacements is true) replacements needed to transform one of the given strings into the other. If zero, the strings are identical.
Definition at line 95 of file StringRef.cpp.
References llvm::ComputeEditDistance(), data(), llvm::makeArrayRef(), and size().
Referenced by compare(), llvm::opt::OptTable::findNearest(), LookupNearestOption(), and llvm::Pattern::match().
empty()
LLVM_NODISCARD bool llvm::StringRef::empty () const inline
empty - Check if the string is empty.
Definition at line 147 of file StringRef.h.
References LLVM_NODISCARD.
Referenced by llvm::SubtargetFeatures::AddFeature(), llvm::CodeViewContext::addFile(), llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::InstrProfSymtab::addFuncName(), llvm::ExecutionEngine::addGlobalMapping(), llvm::DwarfUnit::addLinkageName(), llvm::DwarfUnit::addRnglistsBase(), llvm::DIEHash::addSLEB128(), llvm::CodeViewContext::addToStringTable(), annotateNonNullAndDereferenceable(), llvm::Annotations::Annotations(), llvm::DwarfCompileUnit::applyLabelAttributes(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfUnit::applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::APSInt::APSInt(), back(), llvm::BTFDebug::beginInstruction(), llvm::BinaryStreamError::BinaryStreamError(), branchDiv(), llvm::DICompositeType::buildODRType(), canDecodeBlob(), llvm::canRenameComdatFunc(), llvm::caseFoldingDjbHash(), checkFeature(), checkFunctionsAttributeConsistency(), checkParametrizedPassName(), chopOneUTF32(), CloneInstructionInExitBlock(), collectCallSiteParameters(), llvm::pdb::PDBFileBuilder::commit(), llvm::DIEHash::computeCUSignature(), llvm::ARM::computeDefaultTargetABI(), llvm::RISCVABI::computeTargetABI(), llvm::MipsABIInfo::computeTargetABI(), computeTargetABI(), llvm::ConstantFoldLoadFromConstPtr(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfUnit::constructTypeDIE(), llvm::formatv_object_base::consumeFieldLayout(), llvm::consumeSignedInteger(), llvm::consumeUnsignedInteger(), llvm::detail::IEEEFloat::convertFromString(), llvm::convertUTF8ToUTF16String(), copy(), llvm::yaml::MappingTraits< T >::NormalizedTBD::copyString(), CopyStringRef(), CountNumNewlinesBetween(), llvm::GlobPattern::create(), llvm::StructType::create(), llvm::vfs::RedirectingFileSystem::create(), llvm::sys::fs::create_directories(), createAArch64MCSubtargetInfo(), llvm::MDBuilder::createAnonymousAARoot(), llvm::ARM_MC::createARMMCSubtargetInfo(), llvm::DIBuilder::createBasicType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createMacro(), llvm::createProfileFileNameVar(), llvm::createSanitizerCtorAndInitFunctions(), createSparcMCSubtargetInfo(), llvm::sys::fs::createTemporaryFile(), llvm::DIBuilder::createUnspecifiedType(), createVEMCSubtargetInfo(), llvm::X86_MC::createX86MCSubtargetInfo(), llvm::declareSanitizerInitFunction(), decodeBase64StringEntry(), llvm::FileCheckPatternContext::defineCmdlineVariables(), llvm::DelimitedScope< Open, Close >::DelimitedScope(), llvm::GlobalValue::dropLLVMManglingEscape(), llvm::ELFYAML::dropUniqueSuffix(), llvm::jitlink::LinkGraph::dump(), llvm::MCInst::dump_pretty(), dumpAttribute(), llvm::DWARFDebugLoclists::dumpRawEntry(), EatNumber(), llvm::CodeGenCoverage::emit(), emitComments(), emitDebugLabelComment(), emitDebugValueComment(), emitDirectiveRelocJalr(), EmitGenDwarfAbbrev(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), emitOneV5FileEntry(), llvm::X86FrameLowering::emitPrologue(), emitRangeList(), llvm::ARMTargetStreamer::emitTargetAttributes(), llvm::LocationMetadata::empty(), llvm::WithColor::error(), llvm::cl::Option::error(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::coverage::CounterMappingContext::evaluate(), ExpandCryptoAEK(), llvm::DWARFFormValue::extractValue(), llvm::RuntimeDyldImpl::finalizeAsync(), find_if(), FindFirstMatchingPrefix(), FindFirstNonCommonLetter(), llvm::sampleprof::FunctionSamples::findFunctionSamplesAt(), llvm::CodeExtractor::findInputsOutputs(), llvm::opt::OptTable::findNearest(), llvm::pdb::DIASession::findSourceFiles(), FixedPointIntrinsicToOpcode(), llvm::format_provider< T, typename std::enable_if< detail::use_integral_formatter< T >::value >::type >::format(), llvm::format_provider< std::chrono::duration< Rep, Period > >::format(), llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type >::format(), llvm::format_provider< T, typename std::enable_if< detail::use_char_formatter< T >::value >::type >::format(), llvm::format_provider< Enum, typename std::enable_if< dwarf::EnumTraits< Enum >::value >::type >::format(), llvm::format_provider< llvm::json::Value >::format(), llvm::fromHex(), front(), FunctionNumber(), llvm::Attribute::get(), llvm::CodeInit::get(), getAddrSpace(), GetAEABIUnwindPersonalityName(), getARClassRegisterMask(), llvm::Triple::getARMCPUForArch(), getAsInteger(), llvm::getAsSignedInteger(), llvm::getAsUnsignedInteger(), getAttrKindEncoding(), GetAutoSenseRadix(), llvm::APInt::getBitsNeeded(), llvm::ARM::getCanonicalArchName(), llvm::DINode::getCanonicalMDString(), llvm::DIMacroNode::getCanonicalMDString(), llvm::DeclContextTree::getChildDeclContext(), getChompedLineBreaks(), llvm::MCContext::getCOFFSection(), getCommonClassOptions(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::getCPU(), llvm::MachineFunction::getDenormalMode(), getELFKindForNamedSection(), llvm::NonRelocatableStringpool::getEntry(), getFeatures(), getFilename(), llvm::DWARFDebugLine::Prologue::getFileNameByIndex(), llvm::InstrProfSymtab::getFuncNameOrExternalSymbol(), llvm::getFuncNameWithoutPrefix(), llvm::object::ArchiveMemberHeader::getGID(), llvm::GlobalValue::getGlobalIdentifier(), getGNUBinOpPrecedence(), getGPUOrDefault(), getItineraryLatency(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), getLinkageNameWithSpace(), llvm::getMemOPSizeRangeFromOption(), llvm::Value::getName(), llvm::jitlink::Symbol::getName(), getNameWithPrefixImpl(), getNodeVisualName(), llvm::DICompositeType::getODRTypeIfExists(), getOpEnabled(), getOpRefinementSteps(), llvm::cl::generic_parser_base::getOptionWidth(), llvm::DwarfCompileUnit::getOrCreateCommonBlock(), llvm::getOrCreateInitFunction(), llvm::DwarfUnit::getOrCreateModule(), llvm::DwarfUnit::getOrCreateNameSpace(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), llvm::MCContext::getOrCreateSymbol(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfUnit::getParentContextString(), getPassInfo(), getPassNameAndInstanceNum(), llvm::FileCheckPatternContext::getPatternVarValue(), getPrefixes(), getPrettyScopeName(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), llvm::SparcTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), getRegNum(), llvm::sampleprof::getRepInFormat(), llvm::TargetLibraryInfoImpl::getScalarizedFunction(), getSearchPaths(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), GetSymbolFromOperand(), getSymbolKindName(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::lto::getThinLTOOutputFile(), llvm::getTypeName(), llvm::object::ArchiveMemberHeader::getUID(), getUnicodeEncoding(), llvm::MCSymbolXCOFF::getUnqualifiedName(), llvm::yaml::ScalarNode::getValue(), getValueStr(), llvm::TargetLibraryInfoImpl::getVectorizedFunction(), llvm::VFABI::getVectorVariantNames(), llvm::yaml::Node::getVerbatimTag(), llvm::TargetLibraryInfoImpl::getWidestVF(), llvm::DWARFVerifier::handleAccelTables(), llvm::DWARFVerifier::handleDebugAbbrev(), HandlePrefixedOrGroupedOption(), llvm::sys::path::has_extension(), llvm::sys::path::has_filename(), llvm::sys::path::has_parent_path(), llvm::sys::path::has_relative_path(), llvm::sys::path::has_root_directory(), llvm::sys::path::has_root_name(), llvm::sys::path::has_root_path(), llvm::sys::path::has_stem(), llvm::cl::Option::hasArgStr(), llvm::IntelExpr::hasBaseReg(), hasConflictingReferenceFlags(), llvm::SubtargetFeatures::hasFlag(), llvm::IntelExpr::hasIndexReg(), llvm::MCAsmInfo::hasLinkerPrivateGlobalPrefix(), llvm::jitlink::Symbol::hasName(), llvm::IntelExpr::hasOffset(), hasPrefix(), llvm::object::Archive::hasSymbolTable(), llvm::HexagonGetLastSlot(), llvm::PassNameParser::ignorablePass(), llvm::vfs::VFSFromYamlDirIterImpl::increment(), incrementLoc(), llvm::OpenMPIRBuilder::initialize(), initializeRecordStreamer(), llvm::NVPTXSubtarget::initializeSubtargetDependencies(), llvm::MCSubtargetInfo::InitMCProcessorInfo(), llvm::StringSet< AllocatorTy >::insert(), llvm::gsym::GsymCreator::insertString(), llvm::MachineRegisterInfo::insertVRegByName(), instrumentMaskedLoadOrStore(), isCanonical(), llvm::SubtargetFeatures::isEnabled(), llvm::TargetLibraryInfoImpl::isFunctionVectorizable(), isIdentifierChar(), isInSymtab(), isLoopPassName(), isMips64EL(), isOperator(), isRepeatedByteSequence(), isReportingError(), isSDKVersionToken(), isValidEncoding(), llvm::MCAsmInfo::isValidUnquotedName(), llvm::ARMSubtarget::isXRaySupported(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), loadBinaryFormat(), loadTestingFormat(), LookupNearestOption(), llvm::yaml::MappingTraits< DWARFYAML::FormValue >::mapping(), llvm::yaml::MappingTraits< DWARFYAML::LineTableOpcode >::mapping(), llvm::codeview::CodeViewRecordIO::mapStringZVectorZ(), llvm::GlobPattern::match(), llvm::Pattern::match(), matchAsm(), maybePrintComdat(), llvm::Triple::normalize(), llvm::WithColor::note(), llvm::cl::SubCommand::operator bool(), llvm::gsym::operator<<(), llvm::operator<<(), llvm::jitlink::operator<<(), optimizeDoubleFP(), llvm::DWARFGdbIndex::parse(), llvm::DWARFDebugFrame::parse(), llvm::AMDGPULibFunc::parse(), llvm::MachO::PackedVersion::parse32(), llvm::MachO::PackedVersion::parse64(), llvm::PassBuilder::parseAAPipeline(), parseARMArch(), llvm::ARM_MC::ParseARMTriple(), llvm::remarks::ParsedStringTable::ParsedStringTable(), parseDuration(), llvm::formatv_object_base::parseFormatString(), parseHexOcta(), parseInt(), parseNamePrefix(), llvm::detail::HelperFunctions::parseNumericPrecision(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parsePattern(), llvm::formatv_object_base::parseReplacementItem(), llvm::MCSectionMachO::ParseSectionSpecifier(), parseSubArch(), parseV2DirFileTables(), llvm::Pattern::parseVariable(), parseVersionFromName(), pathHasTraversal(), popFront(), previousIsLoop(), llvm::MCExpr::print(), llvm::DWARFExpression::Operation::print(), llvm::MachineOperand::print(), llvm::MCInstPrinter::printAnnotation(), llvm::AArch64InstPrinter::printBarrierOption(), printCFI(), PrintCFIEscape(), printDwarfFileDirective(), printFile(), llvm::AMDGPUInstPrinter::printHwreg(), PrintLLVMName(), llvm::printLLVMNameWithoutPrefix(), printMetadataIdentifier(), llvm::cl::generic_parser_base::printOptionInfo(), PrintQuotedString(), llvm::MachineOperand::printStackObjectReference(), llvm::MCSectionMachO::PrintSwitchToSection(), printSymbolizedStackTrace(), llvm::codeview::printTypeIndex(), llvm::AttributeImpl::Profile(), llvm::pruneCache(), llvm::SymbolRemappingReader::read(), llvm::GCOVBuffer::readArcTag(), llvm::AppleAcceleratorTable::readAtoms(), llvm::irsymtab::readBitcode(), llvm::GCOVBuffer::readBlockTag(), llvm::FileCheck::readCheckFile(), llvm::GCOVBuffer::readEdgeTag(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readLineTag(), llvm::GCOVBuffer::readObjectTag(), llvm::GCOVBuffer::readProgramTag(), llvm::LessRecordRegister::RecordParts::RecordParts(), RefineErrorLoc(), llvm::WithColor::remark(), llvm::sys::path::replace_path_prefix(), llvm::HexagonMCChecker::reportBranchErrors(), llvm::cl::ResetAllOptionOccurrences(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), resolveFwdRef(), rewritesSort(), runOnFunction(), sanitizeFunctionName(), llvm::StringSaver::save(), llvm::Hexagon_MC::selectHexagonCPU(), llvm::MIPS_MC::selectMipsCPU(), llvm::EngineBuilder::selectTarget(), llvm::cl::Option::setArgStr(), llvm::MCContext::setGenDwarfRootFile(), llvm::jitlink::Symbol::setLinkage(), llvm::StructType::setName(), llvm::GlobalValue::setPartition(), setRequiredFeatureString(), llvm::GlobalObject::setSection(), llvm::setupOptimizationRemarks(), llvm::lto::setupStatsFile(), llvm::VFABI::setVectorVariantNames(), shouldAlwaysEmitCompleteClassType(), shouldEmitUdt(), shouldPrintOption(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), llvm::AMDGPU::SIModeRegisterDefaults::SIModeRegisterDefaults(), sortSubCommands(), split(), split(), llvm::DISubprogram::splitFlags(), srcMgrDiagHandler(), llvm::StripDebugInfo(), StripTypeNames(), llvm::Regex::sub(), sub(), llvm::to_hexString(), truncateToSize(), llvm::VFABI::tryDemangleForVFABI(), llvm::MCDwarfLineTableHeader::tryGetFile(), llvm::VersionTuple::tryParse(), llvm::MachO::InterfaceFile::undefineds(), llvm::ExecutionEngine::updateGlobalMapping(), llvm::UpgradeFramePointerAttributes(), UsesVectorABI(), llvm::APInt::ushl_sat(), llvm::yaml::MappingTraits< ELFYAML::Symbol >::validate(), llvm::InlineAsm::Verify(), llvm::WithColor::warning(), llvm::StringTableBuilder::write(), writeCOFF(), writeContent(), llvm::ThinLTOCodeGenerator::writeGeneratedObject(), writeSymbolTable(), and zero().
end()
iterator llvm::StringRef::end () const inline
Definition at line 124 of file StringRef.h.
Referenced by annotateNonNullAndDereferenceable(), llvm::SmallString< 256 >::append(), llvm::sys::path::append(), llvm::pdb::NamedStreamMap::appendStringData(), llvm::SmallString< 256 >::assign(), bytes_end(), llvm::FileCheckString::CheckNext(), llvm::FileCheckString::CheckSame(), chopOneUTF32(), llvm::detail::IEEEFloat::convertFromZeroExtendedInteger(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), copy(), llvm::MCObjectStreamer::EmitBytes(), emitSignedInt64(), llvm::MDString::end(), endswith(), endswith_lower(), llvm::yaml::escape(), getAttrKindEncoding(), llvm::MemoryBufferRef::getBufferEnd(), llvm::sys::detail::getHostCPUNameForPowerPC(), getHostID(), llvm::TGLexer::getLoc(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), llvm::SparcTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::WasmObjectFile::getRelocationTypeName(), llvm::object::MachOObjectFile::getRelocationTypeName(), llvm::object::COFFObjectFile::getRelocationTypeName(), llvm::ConstantDataArray::getString(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::yaml::ScalarNode::getValue(), llvm::hash_value(), llvm::pdb::hashStringV2(), llvm::detail::IEEEFloat::IEEEFloat(), llvm::Timer::init(), IsIdentifierChar(), llvm::AsmLexer::LexToken(), llvm::AsmLexer::LexUntilEndOfStatement(), llvm::line_iterator::line_iterator(), llvm::pdb::NamedStreamMap::load(), llvm::sys::fs::make_absolute(), mangleCoveragePath(), llvm::SmallString< 256 >::operator+=(), llvm::opt::OptTable::OptTable(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::InlineAsm::ParseConstraints(), parseMaybeMangledName(), parsePhysicalReg(), parseRegisterNumber(), printName(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::Regex::Regex(), llvm::sys::path::replace_extension(), llvm::AsmLexer::setBuffer(), llvm::EngineBuilder::setMArch(), llvm::EngineBuilder::setMCPU(), llvm::TimerGroup::setName(), llvm::Regex::sub(), llvm::cl::tokenizeConfigFile(), llvm::APInt::ushl_sat(), and llvm::ValueSymbolTable::~ValueSymbolTable().
endswith()
LLVM_NODISCARD bool llvm::StringRef::endswith (StringRef Suffix) const inline
Check if this string ends with the given Suffix.
Definition at line 288 of file StringRef.h.
References end(), endswith_lower(), and LLVM_NODISCARD.
Referenced by checkParametrizedPassName(), consume_back(), llvm::GlobPattern::create(), dumpTypeTagName(), encodeCnt(), llvm::StringSwitch< T, R >::EndsWith(), llvm::SmallString< 256 >::endswith(), llvm::ARM::getCanonicalArchName(), llvm::sys::detail::getHostCPUNameForARM(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), getVarName(), isAnonymous(), llvm::GlobPattern::match(), llvm::matchPassManager(), llvm::parseAnalysisUtilityPasses(), llvm::ARM::parseArchEndian(), parseSubArch(), shouldBeSls(), and shouldInstrumentReadWriteFromAddress().
endswith_lower()
bool StringRef::endswith_lower (StringRef Suffix) const
Check if this string ends with the given Suffix, ignoring case.
Definition at line 53 of file StringRef.cpp.
References ascii_strncasecmp(), and end().
Referenced by endswith(), and llvm::StringSwitch< T, R >::EndsWithLower().
equals()
LLVM_NODISCARD bool llvm::StringRef::equals (StringRef RHS) const inline
equals - Check for string equality, this is more efficient than compare() when the relative ordering of inequal strings isn't needed.
Definition at line 181 of file StringRef.h.
References LLVM_NODISCARD.
Referenced by llvm::TargetPassConfig::addMachinePasses(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::MachineBlockFrequencyInfo::calculate(), llvm::BlockFrequencyInfo::calculate(), llvm::BranchProbabilityInfo::calculate(), count(), llvm::createBlockExtractorPass(), llvm::SmallString< 256 >::equals(), llvm::findOptionMDForLoopID(), foldFPToIntToFP(), llvm::Triple::getARMCPUForArch(), llvm::FileInfo::getCoveragePath(), llvm::BasicBlock::getIrrLoopHeaderWeight(), getSummaryFromMD(), llvm::GetUnrollMetadata(), getVal(), llvm::getValueProfDataFromInst(), initializeOptionalHeader(), isCaseSensitivePath(), isGCSafepointPoll(), isKeyValuePair(), isSmallDataSection(), isTraversalComponent(), llvm::RuntimeDyldELF::loadObject(), llvm::log2(), makeStatepointExplicitImpl(), llvm::operator==(), outliningCandidatesSigningKeyConsensus(), outliningCandidatesSigningScopeConsensus(), llvm::CodeGenCoverage::parse(), llvm::SymbolRewriter::RewriteMapParser::parse(), parseBPFArch(), llvm::MIRParserImpl::parseRegisterInfo(), popFront(), rfind(), llvm::runFuzzerOnInputs(), ShouldSignReturnAddress(), and truncateToSize().
equals_lower()
LLVM_NODISCARD bool llvm::StringRef::equals_lower (StringRef RHS) const inline
equals_lower - Check for string equality, ignoring case.
Definition at line 188 of file StringRef.h.
References compare_lower(), and LLVM_NODISCARD.
Referenced by addNegOperand(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::StringSwitch< T, R >::CaseLower(), llvm::SmallString< 256 >::equals_lower(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTTIImpl::getUserCost(), insertNoDuplicates(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), matchSVEPredicateVectorRegName(), outliningCandidatesSigningKeyConsensus(), llvm::TextInstrProfReader::readHeader(), rfind_lower(), ShouldSignWithAKey(), and llvm::StrInStrNoCase().
find() [1/2]
LLVM_NODISCARD size_t llvm::StringRef::find (char C, size_t From = 0) const inline
Search for the first character C in the string.
Returns
The index of the first occurrence of C, or npos if not found.
Definition at line 306 of file StringRef.h.
References C, find_lower(), From, LLVM_NODISCARD, npos, and P.
Referenced by addNegOperand(), llvm::X86FrameLowering::adjustForHiPEPrologue(), annotateNonNullAndDereferenceable(), checkLinkerOptCommand(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), CommaSeparateAndAddOccurrence(), contains(), llvm::createSampleProfileLoaderPass(), emitComments(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::SmallString< 256 >::find(), find_first_of(), find_if_not(), llvm::opt::OptTable::findNearest(), llvm::ARM::getCanonicalArchName(), llvm::getConstantStringInfo(), llvm::DataExtractor::getCStr(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::getMemOPSizeRangeFromOption(), getObjCClassCategory(), getObjCMethodName(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::getTypeName(), llvm::yaml::ScalarNode::getValue(), hasObjCCategory(), llvm::MIRParserImpl::initializeJumpTableInfo(), instrumentMaskedLoadOrStore(), llvm::ConstantDataSequential::isCString(), isIFunc(), IsInterestingCmp(), llvm::objcarc::IsObjCIdentifiedObject(), isReportingError(), isSmallDataSection(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), llvm::Pattern::match(), llvm::matchPassManager(), MCAttrForString(), llvm::cl::SubCommand::operator bool(), ParseLine(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parsePattern(), parseRefinementStep(), printSourceLine(), printSymbolizedStackTrace(), llvm::object::replace(), sanitizeFunctionName(), setRequiredFeatureString(), shouldBeSls(), split(), UpgradeIntrinsicFunction1(), and llvm::sroa::AllocaSliceRewriter::visit().
find() [2/2]
size_t StringRef::find (StringRef Str, size_t From = 0) const
Search for the first string Str in the string.
find - Search for the first string
Returns
The index of the first occurrence of Str, or npos if not found.
Str in the string.
Returns
- The index of the first occurrence of
Str, or npos if not found.
Definition at line 133 of file StringRef.cpp.
References npos.
find_first_not_of() [1/2]
StringRef::size_type StringRef::find_first_not_of (char C, size_t From = 0) const
Find the first character in the string that is not C or npos if not found.
find_first_not_of - Find the first character in the string that is not
C or npos if not found.
Definition at line 250 of file StringRef.cpp.
References llvm::numbers::e, and npos.
Referenced by annotateNonNullAndDereferenceable(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::SmallString< 256 >::find_first_not_of(), find_first_of(), ltrim(), matchAsm(), ParseLine(), printName(), PrintNoMatch(), llvm::FileCheck::readCheckFile(), llvm::Regex::sub(), and llvm::sroa::AllocaSliceRewriter::visit().
find_first_not_of() [2/2]
StringRef::size_type StringRef::find_first_not_of (StringRef Chars, size_t From = 0) const
Find the first character in the string that is not in the string Chars, or npos if not found.
find_first_not_of - Find the first character in the string that is not in the string
Complexity: O(size() + Chars.size())
Chars, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 261 of file StringRef.cpp.
References llvm::numbers::e, npos, and size().
find_first_of() [1/2]
LLVM_NODISCARD size_t llvm::StringRef::find_first_of (char C, size_t From = 0) const inline
Find the first character in the string that is C, or npos if not found.
Same as find.
Definition at line 401 of file StringRef.h.
References find(), find_first_not_of(), From, and LLVM_NODISCARD.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), annotateNonNullAndDereferenceable(), contains(), CountNumNewlinesBetween(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::sys::fs::createTemporaryFile(), llvm::BTFDebug::endFunctionImpl(), llvm::SmallString< 256 >::find_first_of(), llvm::Value::getName(), llvm::InstrProfSymtab::getOrigFuncName(), llvm::yaml::ScalarNode::getValue(), hasWildcard(), llvm::Regex::isLiteralERE(), isLoopPassName(), llvm::yaml::Document::parseBlockNode(), ParseLine(), llvm::FileCheck::readCheckFile(), llvm::BinaryStreamReader::readCString(), llvm::formatv_object_base::splitLiteralAndReplacement(), and truncateToSize().
find_first_of() [2/2]
StringRef::size_type StringRef::find_first_of (StringRef Chars, size_t From = 0) const
Find the first character in the string that is in Chars, or npos if not found.
find_first_of - Find the first character in the string that is in
Complexity: O(size() + Chars.size())
Chars, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 236 of file StringRef.cpp.
References llvm::numbers::e, npos, and size().
find_if()
LLVM_NODISCARD size_t llvm::StringRef::find_if (function_ref< bool(char)> F, size_t From = 0) const inline
Search for the first character satisfying the predicate F.
Returns
The index of the first character satisfying F starting from From, or npos if not found.
Definition at line 328 of file StringRef.h.
References drop_front(), empty(), F(), From, front(), LLVM_NODISCARD, npos, and size().
Referenced by drop_until(), find_if_not(), find_lower(), and take_until().
find_if_not()
LLVM_NODISCARD size_t llvm::StringRef::find_if_not (function_ref< bool(char)> F, size_t From = 0) const inline
Search for the first character not satisfying the predicate F.
Returns
The index of the first character not satisfying F starting from From, or npos if not found.
Definition at line 343 of file StringRef.h.
References F(), find(), find_if(), find_lower(), From, and LLVM_NODISCARD.
Referenced by drop_while(), and take_while().
find_last_not_of() [1/2]
StringRef::size_type StringRef::find_last_not_of (char C, size_t From = npos) const
Find the last character in the string that is not C, or npos if not found.
find_last_not_of - Find the last character in the string that is not
C, or npos if not found.
Definition at line 291 of file StringRef.cpp.
References llvm::numbers::e, and npos.
Referenced by find_last_of(), and rtrim().
find_last_not_of() [2/2]
StringRef::size_type StringRef::find_last_not_of (StringRef Chars, size_t From = npos) const
Find the last character in the string that is not in Chars, or npos if not found.
find_last_not_of - Find the last character in the string that is not in
Complexity: O(size() + Chars.size())
Chars, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 302 of file StringRef.cpp.
References llvm::numbers::e, npos, and size().
find_last_of() [1/2]
LLVM_NODISCARD size_t llvm::StringRef::find_last_of (char C, size_t From = npos) const inline
Find the last character in the string that is C, or npos if not found.
Definition at line 427 of file StringRef.h.
References find_last_not_of(), From, LLVM_NODISCARD, and rfind().
Referenced by llvm::createAMDGPUPrintfRuntimeBinding(), llvm::sys::path::extension(), llvm::SmallString< 256 >::find_last_of(), llvm::SourceMgr::getLineAndColumn(), llvm::yaml::Node::getVerbatimTag(), ParseLine(), llvm::sys::path::replace_extension(), and llvm::sys::path::stem().
find_last_of() [2/2]
StringRef::size_type StringRef::find_last_of (StringRef Chars, size_t From = npos) const
Find the last character in the string that is in C, or npos if not found.
find_last_of - Find the last character in the string that is in
Complexity: O(size() + Chars.size())
C, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 277 of file StringRef.cpp.
References llvm::numbers::e, npos, and size().
find_lower() [1/2]
size_t StringRef::find_lower (char C, size_t From = 0) const
Search for the first character C in the string, ignoring case.
Returns
The index of the first occurrence of C, or npos if not found.
Definition at line 58 of file StringRef.cpp.
References D, find_if(), From, and llvm::toLower().
Referenced by contains_lower(), find(), find_if_not(), llvm::GCNSubtarget::initializeSubtargetDependencies(), and llvm::Pattern::match().
find_lower() [2/2]
size_t StringRef::find_lower (StringRef Str, size_t From = 0) const
Search for the first string Str in the string, ignoring case.
Returns
The index of the first occurrence of Str, or npos if not found.
Definition at line 182 of file StringRef.cpp.
References drop_front(), From, npos, size(), startswith_lower(), and substr().
front()
LLVM_NODISCARD char llvm::StringRef::front () const inline
front - Get the first character in the string.
Definition at line 155 of file StringRef.h.
References assert(), empty(), and LLVM_NODISCARD.
Referenced by llvm::Annotations::Annotations(), llvm::FileCheck::buildCheckPrefixRegex(), llvm::consumeSignedInteger(), find_if(), llvm::formLCSSAForInstructions(), llvm::fromHex(), getAddrSpace(), getAsInteger(), parseNamePrefix(), parsePhysicalReg(), llvm::formatv_object_base::parseReplacementItem(), popFront(), RefineErrorLoc(), rewritePHIs(), llvm::MCContext::setGenDwarfRootFile(), SimplifyCondBranchToCondBranch(), truncateToSize(), and unescapeQuotedString().
getAsDouble()
bool StringRef::getAsDouble (double & Result, bool AllowInexact = true) const
Parse the current string as an IEEE double-precision floating point value.
The string must be a well-formed double.
If AllowInexact is false, the function will fail if the string cannot be represented exactly. Otherwise, the function only fails in case of an overflow or underflow, or an invalid floating point representation.
Definition at line 589 of file StringRef.cpp.
References llvm::APFloat::convertFromString(), llvm::APFloat::convertToDouble(), llvm::errorToBool(), F(), llvm::APFloatBase::opInexact, llvm::APFloatBase::opOK, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by consumeInteger().
getAsInteger() [1/3]
template<typename T > std::enable_if<std::numeric_limits<T>::is_signed, bool>::type llvm::StringRef::getAsInteger (unsigned Radix, T & Result) const inline
Parse the current string as an integer of the specified radix.
If Radix is specified as zero, this does radix autosensing using extended C rules: 0 is octal, 0x is hex, 0b is binary.
If the string is invalid or if only a subset of the string is valid, this returns true to signify the error. The string is considered erroneous if empty or if it overflows T.
Definition at line 499 of file StringRef.h.
References llvm::getAsSignedInteger().
Referenced by addNegOperand(), adjustCallerStackProbeSize(), adjustMinLegalVectorWidth(), NoAutoPaddingScope::changeAndComment(), checkParametrizedPassName(), consumeInteger(), llvm::AsmPrinter::EmitDebugValue(), EmitGCCInlineAsmStr(), EmitMSInlineAsmStr(), llvm::AsmPrinter::emitPatchableFunctionEntries(), encodeCnt(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type >::format(), llvm::format_provider< llvm::json::Value >::format(), llvm::object::ArchiveMemberHeader::getAccessMode(), llvm::object::ArchiveMemberHeader::getGID(), getInt(), llvm::AMDGPU::getIntegerAttribute(), llvm::object::ArchiveMemberHeader::getLastModified(), llvm::getMemOPSizeRangeFromOption(), llvm::object::ArchiveMemberHeader::getName(), getPassNameAndInstanceNum(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), getRegNum(), llvm::object::COFFObjectFile::getSectionName(), llvm::object::ArchiveMemberHeader::getSize(), llvm::X86TargetLowering::getStackProbeSize(), getSubOpcode(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::object::ArchiveMemberHeader::getUID(), llvm::yaml::ScalarNode::getValue(), hasPrefix(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >::inputOne(), llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::inputOne(), intToken(), isFuncOrArgAttr(), llvm::Pattern::match(), matchSVEPredicateVectorRegName(), llvm::vfs::RedirectingFileSystemParser::parse(), llvm::parseCachePruningPolicy(), parseDevirtPassName(), parseDuration(), ParseHead(), ParseLine(), llvm::detail::HelperFunctions::parseNumericPrecision(), parsePredicateConstraint(), parseRepeatPassName(), parseSectionFlags(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::parseStatepointDirectivesFromAttrs(), printMCExpr(), llvm::cl::basic_parser_impl::printOptionName(), RefineErrorLoc(), llvm::StackProtector::runOnFunction(), llvm::Regex::sub(), llvm::to_integer(), WindowsRequiresStackProbe(), windowsRequiresStackProbe(), and llvm::writeArchive().
getAsInteger() [2/3]
template<typename T > std::enable_if<!std::numeric_limits<T>::is_signed, bool>::type llvm::StringRef::getAsInteger (unsigned Radix, T & Result) const inline
Definition at line 510 of file StringRef.h.
References llvm::getAsUnsignedInteger().
getAsInteger() [3/3]
bool StringRef::getAsInteger (unsigned Radix, APInt & Result) const
Parse the current string as an integer of the specified Radix, or of an autosensed radix if the Radix given is 0.
The current value in Result is discarded, and the storage is changed to be wide enough to store the parsed integer.
Returns
true if the string does not solely consist of a valid non-empty number in the appropriate base.
APInt::fromString is superficially similar but assumes the string is well-formed in the given radix.
Definition at line 514 of file StringRef.cpp.
References assert(), empty(), front(), GetAutoSenseRadix(), llvm::APInt::getBitWidth(), size(), substr(), and llvm::APInt::zext().
lower()
std::string StringRef::lower () const
Definition at line 108 of file StringRef.cpp.
References llvm::numbers::e, size(), and llvm::toLower().
Referenced by llvm::SubtargetFeatures::AddFeature(), llvm::pdb::PDBFileBuilder::addInjectedSource(), llvm::ARMCondCodeFromString(), llvm::ARMVectorCondCodeFromString(), CheckBaseRegAndIndexRegAndScale(), consumeInteger(), llvm::MipsTargetAsmStreamer::emitDirectiveCpLoad(), llvm::MipsTargetAsmStreamer::emitDirectiveCpLocal(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::MipsTargetAsmStreamer::emitFrame(), EmitHiLo(), llvm::SparcTargetAsmStreamer::emitSparcRegisterIgnore(), llvm::SparcTargetAsmStreamer::emitSparcRegisterScratch(), llvm::VETargetAsmStreamer::emitVERegisterIgnore(), llvm::VETargetAsmStreamer::emitVERegisterScratch(), GetAEABIUnwindPersonalityName(), getBankedRegisterMask(), getGNUBinOpPrecedence(), llvm::getMachineType(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), incrementLoc(), insertNoDuplicates(), llvm::IsCPSRDead< MCInst >(), isMatchingOrAlias(), makeCombineInst(), MatchCoprocessorOperandName(), matchSVEPredicateVectorRegName(), llvm::SymbolRewriter::RewriteMapParser::parse(), llvm::MipsAsmPrinter::printOperand(), llvm::printRegClassOrBank(), llvm::SparcInstPrinter::printRegName(), llvm::VEInstPrinter::printRegName(), llvm::ARCInstPrinter::printRegName(), llvm::XCoreInstPrinter::printRegName(), llvm::LanaiInstPrinter::printRegName(), llvm::MipsInstPrinter::printRegName(), and setRequiredFeatureString().
ltrim() [1/2]
LLVM_NODISCARD StringRef llvm::StringRef::ltrim (char Char) const inline
Return string with consecutive Char characters starting from the the left removed.
Definition at line 811 of file StringRef.h.
References drop_front(), find_first_not_of(), and LLVM_NODISCARD.
Referenced by llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::yaml::Document::parseBlockNode(), llvm::Pattern::parseNumericSubstitutionBlock(), popFront(), llvm::SymbolRemappingReader::read(), sub(), trim(), and llvm::VFABI::tryDemangleForVFABI().
ltrim() [2/2]
LLVM_NODISCARD StringRef llvm::StringRef::ltrim (StringRef Chars = " \t\n\v\f\r") const inline
Return string with consecutive characters in Chars starting from the left removed.
Definition at line 818 of file StringRef.h.
References drop_front(), find_first_not_of(), and LLVM_NODISCARD.
operator std::string()
llvm::StringRef::operator std::string () const inline
Definition at line 267 of file StringRef.h.
References LLVM_NODISCARD, and str().
operator=()
template<typename T > std::enable_if<std::is_same<T, std::string>::value, StringRef>::type& llvm::StringRef::operator= (T && Str) delete
Disallow accidental assignment from a temporary std::string.
The declaration here is extra complicated so that stringRef = {} and stringRef = "abc" continue to select the move assignment operator.
Referenced by operator[]().
operator[]()
LLVM_NODISCARD char llvm::StringRef::operator[] (size_t Index) const inline
Definition at line 249 of file StringRef.h.
References assert(), and operator=().
rfind() [1/2]
LLVM_NODISCARD size_t llvm::StringRef::rfind (char C, size_t From = npos) const inline
Search for the last character C in the string.
Returns
The index of the last occurrence of C, or npos if not found.
Definition at line 366 of file StringRef.h.
References From, LLVM_NODISCARD, npos, and rfind_lower().
Referenced by annotateNonNullAndDereferenceable(), llvm::ELFYAML::dropUniqueSuffix(), find_last_of(), llvm::getTypeName(), getTypeNamePrefix(), llvm::object::MachOObjectFile::guessLibraryShortName(), ParseHead(), llvm::SmallString< 256 >::rfind(), rsplit(), shouldBeSls(), splitUstar(), and llvm::sroa::AllocaSliceRewriter::visit().
rfind() [2/2]
size_t StringRef::rfind (StringRef Str) const
Search for the last string Str in the string.
rfind - Search for the last string
Returns
The index of the last occurrence of Str, or npos if not found.
Str in the string.
Returns
- The index of the last occurrence of
Str, or npos if not found.
Definition at line 208 of file StringRef.cpp.
References llvm::numbers::e, equals(), N, npos, size(), and substr().
rfind_lower() [1/2]
size_t StringRef::rfind_lower (char C, size_t From = npos) const
Search for the last character C in the string, ignoring case.
Returns
The index of the last occurrence of C, or npos if not found.
Definition at line 193 of file StringRef.cpp.
References From, npos, and llvm::toLower().
Referenced by rfind().
rfind_lower() [2/2]
size_t StringRef::rfind_lower (StringRef Str) const
Search for the last string Str in the string, ignoring case.
Returns
The index of the last occurrence of Str, or npos if not found.
Definition at line 220 of file StringRef.cpp.
References llvm::numbers::e, equals_lower(), N, npos, size(), and substr().
rsplit() [1/2]
LLVM_NODISCARD std::pair<StringRef, StringRef> llvm::StringRef::rsplit (StringRef Separator) const inline
Split into two substrings around the last occurrence of a separator string.
If Separator is in the string, then the result is a pair (LHS, RHS) such that (*this == LHS + Separator + RHS) is true and RHS is minimal. If Separator is not in the string, then the result is a pair (LHS, RHS) where (*this == LHS) and (RHS == "").
Parameters
Separator - The string to split on.
Returns
- The split substrings.
Definition at line 751 of file StringRef.h.
References LLVM_NODISCARD, npos, rfind(), size(), slice(), split(), and StringRef().
Referenced by getARClassRegisterMask(), llvm::ModuleSummaryIndex::getOriginalNameBeforePromote(), llvm::MCSymbolXCOFF::getUnqualifiedName(), llvm::HexagonGetLastSlot(), and rsplit().
rsplit() [2/2]
LLVM_NODISCARD std::pair<StringRef, StringRef> llvm::StringRef::rsplit (char Separator) const inline
Split into two substrings around the last occurrence of a separator character.
If Separator is in the string, then the result is a pair (LHS, RHS) such that (*this == LHS + Separator + RHS) is true and RHS is minimal. If Separator is not in the string, then the result is a pair (LHS, RHS) where (*this == LHS) and (RHS == "").
Parameters
Separator - The character to split on.
Returns
- The split substrings.
Definition at line 804 of file StringRef.h.
References LLVM_NODISCARD, rsplit(), and StringRef().
rtrim() [1/2]
LLVM_NODISCARD StringRef llvm::StringRef::rtrim (char Char) const inline
Return string with consecutive Char characters starting from the right removed.
Definition at line 825 of file StringRef.h.
References drop_back(), find_last_not_of(), and LLVM_NODISCARD.
Referenced by llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::object::ArchiveMemberHeader::getAccessMode(), llvm::object::ArchiveMemberHeader::getGID(), llvm::object::ArchiveMemberHeader::getLastModified(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::ArchiveMemberHeader::getRawLastModified(), llvm::object::ArchiveMemberHeader::getSize(), llvm::object::ArchiveMemberHeader::getUID(), and trim().
rtrim() [2/2]
LLVM_NODISCARD StringRef llvm::StringRef::rtrim (StringRef Chars = " \t\n\v\f\r") const inline
Return string with consecutive characters in Chars starting from the right removed.
Definition at line 832 of file StringRef.h.
References drop_back(), find_last_not_of(), and LLVM_NODISCARD.
size()
LLVM_NODISCARD size_t llvm::StringRef::size () const inline
size - Get the string size.
Definition at line 151 of file StringRef.h.
References LLVM_NODISCARD.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::BTFStringTable::addString(), llvm::FoldingSetNodeID::AddString(), llvm::msgpack::Document::addString(), altMacroString(), annotateNonNullAndDereferenceable(), llvm::Annotations::Annotations(), llvm::TarWriter::append(), llvm::RuntimeDyldImpl::applyExternalSymbolRelocations(), llvm::APSInt::APSInt(), argPlusPrefixesSize(), argPrefix(), llvm::CachedHashString::CachedHashString(), llvm::CachedHashStringRef::CachedHashStringRef(), llvm::canConstantFoldCallTo(), charTailAt(), llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), checkArchVersion(), CheckBaseRegAndIndexRegAndScale(), llvm::FunctionComparator::cmpMem(), llvm::object::coffnamecpy(), llvm::sys::unicode::columnWidthUTF8(), llvm::zlib::compress(), computeMemberData(), computeStringTable(), llvm::ConstantFoldLoadFromConstPtr(), consume_back(), consume_front(), llvm::formatv_object_base::consumeFieldLayout(), llvm::consumeUnsignedInteger(), llvm::detail::IEEEFloat::convertFromString(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), llvm::ConvertUTF8toWideInternal(), llvm::yaml::MappingTraits< T >::NormalizedTBD::copyString(), CopyStringRef(), count(), CountNumNewlinesBetween(), llvm::zlib::crc32(), llvm::object::ELFFile< ELFT >::create(), llvm::StringMapEntry< llvm::Comdat >::Create(), llvm::MachineFunction::createExternalSymbolName(), llvm::jitlink::LinkGraph::createSection(), llvm::X86Operand::CreateToken(), decodeBase64StringEntry(), llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), drop_back(), drop_front(), llvm::DWARFListTableBase< DWARFDebugRnglist >::dump(), dumpDWARFv5StringOffsetsSection(), dumpStringOffsetsSection(), dumpTypeTagName(), llvm::DWARFDebugPubTable::DWARFDebugPubTable(), llvm::DwarfStringPool::DwarfStringPool(), edit_distance(), llvm::BitstreamWriter::emitBlob(), EmitDebugSectionImpl(), llvm::AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectISA(), EmitFileEntry(), llvm::InstrProfRecordWriterTrait::EmitKeyDataLength(), llvm::DWARFYAML::EmitPubSection(), llvm::NVPTXTargetStreamer::emitRawBytes(), llvm::emitSourceFileHeader(), encodeBitmaskPerm(), llvm::CodeViewContext::encodeDefRange(), llvm::sys::path::end(), llvm::Regex::escape(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::BitstreamWriter::ExitBlock(), expand(), llvm::sys::path::extension(), find_first_not_of(), find_first_of(), find_if(), find_last_not_of(), find_last_of(), find_lower(), FindCheckType(), FindFirstMatchingPrefix(), llvm::opt::OptTable::findNearest(), llvm::AMDGPUTargetELFStreamer::finish(), llvm::json::fixUTF8(), formatPax(), llvm::fromHex(), llvm::ConstantDataArray::get(), llvm::DWARFUnit::getAddrOffsetSectionItem(), getAddrSpace(), llvm::ConstantDataSequential::getAsCString(), getAsInteger(), GetAutoSenseRadix(), llvm::APInt::getBitsNeeded(), llvm::MemoryBufferRef::getBufferSize(), llvm::object::ELFFile< ELFT >::getBufSize(), llvm::ARM::getCanonicalArchName(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), llvm::SparcTargetLowering::getConstraintType(), llvm::RISCVTargetLowering::getConstraintType(), llvm::MSP430TargetLowering::getConstraintType(), llvm::AVRTargetLowering::getConstraintType(), llvm::HexagonTargetLowering::getConstraintType(), llvm::SITargetLowering::getConstraintType(), llvm::ARMTargetLowering::getConstraintType(), llvm::SystemZTargetLowering::getConstraintType(), llvm::NVPTXTargetLowering::getConstraintType(), llvm::PPCTargetLowering::getConstraintType(), llvm::X86TargetLowering::getConstraintType(), llvm::TargetLowering::getConstraintType(), llvm::LTOModule::getDependentLibrary(), llvm::object::getElfArchType(), getEncodedUnnamedAddr(), llvm::NonRelocatableStringpool::getEntry(), llvm::object::ELFFile< ELFT >::getEntry(), llvm::Triple::getEnvironmentVersion(), getFilename(), llvm::getFuncNameWithoutPrefix(), getGNUBinOpPrecedence(), getHexUint(), llvm::object::MachOObjectFile::getIndirectName(), llvm::HexagonInstrInfo::getInlineAsmLength(), llvm::RISCVTargetLowering::getInlineAsmMemConstraint(), llvm::ARMTargetLowering::getInlineAsmMemConstraint(), llvm::SystemZTargetLowering::getInlineAsmMemConstraint(), getItaniumTypeName(), llvm::MDString::getLength(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::DWARFContext::getLineTableForUnit(), getMemBufferCopyImpl(), llvm::getMemOPSizeRangeFromOption(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::Elf_Sym_Impl< ELFT >::getName(), llvm::Value::getName(), llvm::WritableMemoryBuffer::getNewUninitMemBuffer(), llvm::object::Archive::Child::getNext(), getOptionPred(), llvm::cl::generic_parser_base::getOptionWidth(), llvm::cl::basic_parser_impl::getOptionWidth(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::MCContext::getOrCreateLSDASymbol(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), llvm::Triple::getOSVersion(), getPrefixes(), llvm::BPFTargetLowering::getRegForInlineAsmConstraint(), llvm::SparcTargetLowering::getRegForInlineAsmConstraint(), llvm::LanaiTargetLowering::getRegForInlineAsmConstraint(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::MSP430TargetLowering::getRegForInlineAsmConstraint(), llvm::AVRTargetLowering::getRegForInlineAsmConstraint(), llvm::HexagonTargetLowering::getRegForInlineAsmConstraint(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), llvm::ARMTargetLowering::getRegForInlineAsmConstraint(), llvm::SystemZTargetLowering::getRegForInlineAsmConstraint(), llvm::NVPTXTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), getRegNum(), llvm::object::ELFFile< ELFT >::getSectionContentsAsArray(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::object::Archive::Child::getSize(), llvm::DataExtractor::getSLEB128(), llvm::gsym::StringTable::getString(), llvm::ConstantDataArray::getString(), llvm::AsmToken::getStringContents(), llvm::DWARFUnit::getStringOffsetSectionItem(), llvm::X86TargetMachine::getSubtargetImpl(), getTime(), llvm::getTypeName(), getUnicodeEncoding(), llvm::AMDGPUMangledLibFunc::getUnmangledName(), llvm::yaml::ScalarNode::getValue(), getVarName(), llvm::CodeViewYAML::GlobalHash::GlobalHash(), gsiRecordLess(), llvm::object::MachOObjectFile::guessLibraryShortName(), llvm::DWARFVerifier::handleDebugInfo(), HandlePrefixedOrGroupedOption(), llvm::SHA1::hash(), llvm::pdb::hashStringV1(), llvm::identify_magic(), incrementLoc(), INITIALIZE_PASS(), llvm::ExecutionEngine::InitializeMemory(), llvm::yaml::ScalarTraits< FixedSizeHex< N > >::input(), llvm::yaml::ScalarTraits< FixedSizeString< N > >::input(), llvm::yaml::ScalarTraits< char_16 >::input(), llvm::yaml::ScalarTraits< uuid_t >::input(), llvm::codeview::DebugStringTableSubsection::insert(), insertNoDuplicates(), llvm::jitlink::MachOLinkGraphBuilder::isAltEntry(), isAsmComment(), llvm::TrigramIndex::isDefinitelyOut(), isIFunc(), llvm::XCoreTargetLowering::isLegalAddressingMode(), isMips64EL(), isOperator(), isRepeatedByteSequence(), isReportingError(), llvm::json::isUTF8(), llvm::jitlink::jitLink_MachO(), LLVMDITypeGetName(), LLVMGetAsString(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetNamedMetadataName(), LLVMTargetMachineEmitToMemoryBuffer(), loadTestingFormat(), llvm::gsym::FunctionInfo::lookup(), llvm::Function::lookupIntrinsicID(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), llvm::TargetIntrinsicInfo::lookupName(), lower(), LowerFPToInt(), llvm::MCGenDwarfLabelEntry::Make(), llvm::LTOModule::makeBuffer(), llvm::opt::DerivedArgList::MakeJoinedArg(), mapNameAndUniqueName(), llvm::codeview::CodeViewRecordIO::mapStringZ(), llvm::GlobPattern::match(), llvm::Regex::match(), llvm::Pattern::match(), llvm::MCInstPrinter::matchAliasPatterns(), MatchCoprocessorOperandName(), matchOption(), maybeLexHexadecimalLiteral(), maybeLexIndex(), maybeLexIndexAndName(), maybeLexIRBlock(), maybeLexIRValue(), maybeLexMachineBasicBlock(), maybeLexSubRegisterIndex(), MCAttrForString(), llvm::DWARFExpression::iterator::operator++(), llvm::operator+=(), llvm::gsym::operator<<(), llvm::operator<<(), llvm::raw_ostream::operator<<(), llvm::remarks::ParsedStringTable::operator[](), llvm::cl::applicator< MiscFlags >::opt(), optimizeDoubleFP(), optimizeMemCmpConstantSize(), llvm::DWARFDebugFrame::parse(), llvm::parseAnalysisUtilityPasses(), parseBackslash(), parseDuration(), ParseLine(), parseMagic(), llvm::Pattern::parsePattern(), parsePredicateConstraint(), parseRefinementStep(), parseRegisterNumber(), llvm::MCSectionMachO::ParseSectionSpecifier(), parseStrTab(), parseStrTabSize(), llvm::Pattern::parseVariable(), parseVersion(), llvm::AsmLexer::peekTokens(), llvm::ScopedPrinter::printBinary(), llvm::ScopedPrinter::printBinaryBlock(), printBSDMemberHeader(), printCFI(), PrintCFIEscape(), llvm::printEscapedString(), llvm::Pattern::printFuzzyMatch(), llvm::cl::generic_parser_base::printGenericOptionDiff(), PrintHelpOptionList(), printLine(), llvm::printLLVMNameWithoutPrefix(), printMCExpr(), printMetadataIdentifier(), PrintNoMatch(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::cl::basic_parser_impl::printOptionName(), PrintQuotedString(), printSourceLine(), promoteToConstantPool(), llvm::sys::path::rbegin(), llvm::sampleprof::ProfileSymbolList::read(), llvm::irsymtab::readBitcode(), llvm::FileCheck::readCheckFile(), llvm::sampleprof::SampleProfileReaderBinary::readString(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::sys::path::relative_path(), llvm::sys::path::remove_leading_dotslash(), llvm::object::replace(), llvm::sys::path::replace_extension(), llvm::sys::path::replace_path_prefix(), llvm::report_fatal_error(), rfind(), rfind_lower(), rsplit(), llvm::StringSaver::save(), llvm::object::ELFFile< ELFT >::sections(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent(), llvm::jitlink::Block::setContent(), llvm::AMDGPUPALMetadata::setFromBlob(), llvm::StructType::setName(), llvm::X86Operand::setTokenValue(), shouldBeSls(), llvm::DataExtractor::size(), SkipWord(), split(), llvm::formatv_object_base::splitLiteralAndReplacement(), splitUstar(), srcMgrDiagHandler(), llvm::sys::path::stem(), llvm::StrInStrNoCase(), llvm::Regex::sub(), take_back(), take_front(), llvm::toHex(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), truncateToSize(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), llvm::codeview::TypeServer2Record::TypeServer2Record(), llvm::zlib::uncompress(), llvm::MachO::InterfaceFile::undefineds(), unescapeQuotedString(), UnpackFromArgumentSlot(), llvm::SHA1::update(), llvm::MD5::update(), UpgradeIntrinsicFunction1(), upgradeLoopTag(), upper(), useStringTable(), llvm::APInt::ushl_sat(), verifyAddrSpace(), llvm::StringTableBuilder::write(), llvm::msgpack::Writer::write(), llvm::writeFileAtomically(), llvm::WriteIndexToFile(), writeStringRecord(), writeStringRef(), writeSymbolTable(), writeUstarHeader(), and llvm::xxHash64().
slice()
LLVM_NODISCARD StringRef llvm::StringRef::slice (size_t Start, size_t End) const inline
Return a reference to the substring from [Start, End).
Parameters
Start The index of the starting character in the substring; if the index is npos or greater than the length of the string then the empty substring will be returned.
End The index following the last character to include in the substring. If this is npos or exceeds the number of characters remaining in the string, the string suffix (starting with Start) will be returned. If this is less than Start, an empty string will be returned.
Definition at line 701 of file StringRef.h.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), addNegOperand(), canDecodeBlob(), llvm::object::ObjectFile::createMachOObjectFile(), getObjCClassCategory(), getObjCMethodName(), llvm::AsmToken::getStringContents(), llvm::object::MachOObjectFile::guessLibraryShortName(), llvm::yaml::ScalarTraits< uuid_t >::input(), insertNoDuplicates(), llvm::dwarf::CFIProgram::parse(), llvm::DWARFDebugFrame::parse(), parseDuration(), parsePredicateConstraint(), parseRegisterNumber(), printSourceLine(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readString(), rsplit(), shouldBeSls(), split(), llvm::formatv_object_base::splitLiteralAndReplacement(), llvm::Regex::sub(), and truncateToSize().
split() [1/4]
LLVM_NODISCARD std::pair<StringRef, StringRef> llvm::StringRef::split (char Separator) const inline
Split into two substrings around the first occurrence of a separator character.
If Separator is in the string, then the result is a pair (LHS, RHS) such that (*this == LHS + Separator + RHS) is true and RHS is maximal. If Separator is not in the string, then the result is a pair (LHS, RHS) where (*this == LHS) and (RHS == "").
Parameters
Separator The character to split on.
Returns
The split substrings.
Definition at line 718 of file StringRef.h.
References LLVM_NODISCARD, and StringRef().
Referenced by addForcedAttributes(), branchDiv(), checkParametrizedPassName(), llvm::MachO::Target::create(), llvm::FileCheckPatternContext::defineCmdlineVariables(), ExecGraphViewer(), ExpandCryptoAEK(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::extractName(), FindFirstNonCommonLetter(), llvm::opt::OptTable::findNearest(), findTargetSubtable(), llvm::Triple::getArchName(), llvm::codeview::getBytesAsCString(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), llvm::Triple::getEnvironmentName(), getFilename(), getFullyQualifiedName(), llvm::object::COFFObjectFile::getHintName(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForS390x(), llvm::AMDGPU::getIntegerPairAttribute(), getIntOperandFromRegisterString(), getIntOperandsFromRegisterString(), getOpEnabled(), getOpRefinementSteps(), llvm::Triple::getOSAndEnvironmentName(), llvm::Triple::getOSName(), getPassNameAndInstanceNum(), getSearchPaths(), llvm::codeview::getSymbolName(), llvm::VFABI::getVectorVariantNames(), llvm::Triple::getVendorName(), llvm::handleExecNameEncodedBEOpts(), llvm::handleExecNameEncodedOptimizerOpts(), llvm::HexagonGetLastSlot(), incrementLoc(), llvm::yaml::ScalarTraits< UUID >::input(), llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >::inputOne(), isThumbFunction(), LookupNearestOption(), llvm::Pattern::match(), llvm::Triple::normalize(), llvm::SpecialCaseList::parse(), llvm::PassBuilder::parseAAPipeline(), llvm::parseCachePruningPolicy(), parseCHRFilterFiles(), llvm::remarks::ParsedStringTable::ParsedStringTable(), parseNamePrefix(), llvm::MCSectionMachO::ParseSectionSpecifier(), previousIsLoop(), llvm::cl::Option::printHelpStr(), printSymbolizedStackTrace(), llvm::DebugCounter::push_back(), llvm::SymbolRemappingReader::read(), llvm::readPGOFuncNameStrings(), llvm::GCOVBuffer::readString(), rsplit(), llvm::setCurrentDebugTypes(), split(), llvm::SubtargetFeatures::Split(), llvm::Regex::sub(), llvm::opt::OptTable::suggestValueCompletions(), llvm::Triple::Triple(), UpgradeRetainReleaseMarker(), and UsesVectorABI().
split() [2/4]
LLVM_NODISCARD std::pair<StringRef, StringRef> llvm::StringRef::split (StringRef Separator) const inline
Split into two substrings around the first occurrence of a separator string.
If Separator is in the string, then the result is a pair (LHS, RHS) such that (*this == LHS + Separator + RHS) is true and RHS is maximal. If Separator is not in the string, then the result is a pair (LHS, RHS) where (*this == LHS) and (RHS == "").
Parameters
Separator - The string to split on.
Returns
- The split substrings.
Definition at line 733 of file StringRef.h.
References find(), LLVM_NODISCARD, npos, size(), slice(), and StringRef().
split() [3/4]
void StringRef::split (SmallVectorImpl< StringRef > & A, StringRef Separator, int MaxSplit = -1, bool KeepEmpty = true) const
Split into substrings around the occurrences of a separator string.
Each substring is stored in A. If MaxSplit is >= 0, at most MaxSplit splits are done and consequently <= MaxSplit + 1 elements are added to A. If KeepEmpty is false, empty strings are not added to A. They still count when considering MaxSplit An useful invariant is that Separator.join(A) == *this if MaxSplit == -1 and KeepEmpty == true
Parameters
A - Where to put the substrings.
Separator - The string to split on.
MaxSplit - The maximum number of times the string is split.
KeepEmpty - True if empty substring should be added.
Definition at line 314 of file StringRef.cpp.
References empty(), find(), npos, llvm::SmallVectorTemplateBase< T, bool >::push_back(), size(), and slice().
split() [4/4]
void StringRef::split (SmallVectorImpl< StringRef > & A, char Separator, int MaxSplit = -1, bool KeepEmpty = true) const
Split into substrings around the occurrences of a separator character.
Each substring is stored in A. If MaxSplit is >= 0, at most MaxSplit splits are done and consequently <= MaxSplit + 1 elements are added to A. If KeepEmpty is false, empty strings are not added to A. They still count when considering MaxSplit An useful invariant is that Separator.join(A) == *this if MaxSplit == -1 and KeepEmpty == true
Parameters
A - Where to put the substrings.
Separator - The string to split on.
MaxSplit - The maximum number of times the string is split.
KeepEmpty - True if empty substring should be added.
Definition at line 341 of file StringRef.cpp.
References empty(), find(), npos, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and slice().
startswith()
LLVM_NODISCARD bool llvm::StringRef::startswith (StringRef Prefix) const inline
Check if this string starts with the given Prefix.
Definition at line 277 of file StringRef.h.
References LLVM_NODISCARD, llvm::cl::Prefix, and startswith_lower().
Referenced by llvm::analyzeBuiltinArguments(), llvm::ARMBuildAttrs::AttrTypeFromString(), llvm::BTFDebug::beginInstruction(), llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), CheckBaseRegAndIndexRegAndScale(), checkParametrizedPassName(), llvm::CodeViewDebug::CodeViewDebug(), computeAddrSpace(), llvm::RISCVABI::computeTargetABI(), llvm::MipsABIInfo::computeTargetABI(), computeTargetABI(), consume_front(), llvm::GlobPattern::create(), llvm::coverage::BinaryCoverageReader::create(), createPowWithIntegerExponent(), llvm::createX86RetpolineThunksPass(), llvm::remarks::createYAMLParserFromMeta(), doesIgnoreDataTypeSuffix(), llvm::NVPTXAsmPrinter::doFinalization(), dumpTypeTagName(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::ARMTargetStreamer::emitTargetAttributes(), encodeCnt(), llvm::RuntimeDyldCheckerExprEval::evaluate(), findTargetSubtable(), forEachUser(), llvm::AArch64::getArchExtFeature(), GetAutoSenseRadix(), llvm::ARM::getCanonicalArchName(), getELFKindForNamedSection(), getELFSectionType(), llvm::Triple::getEnvironmentVersion(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::AMDGPUTargetObjectFile::getExplicitSectionGlobal(), llvm::getFuncNameWithoutPrefix(), getGNUBinOpPrecedence(), getName(), llvm::object::getNameType(), llvm::Mangler::getNameWithPrefix(), llvm::MCContext::getOrCreateLSDASymbol(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), llvm::Triple::getOSVersion(), llvm::FileCheckPatternContext::getPatternVarValue(), getPrefixes(), getRegularRegInfo(), llvm::jitlink::MachOLinkGraphBuilder::getScope(), llvm::object::COFFObjectFile::getSectionName(), getSignature(), llvm::object::ELFObjectFile< ELFT >::getSymbolFlags(), llvm::yaml::Node::getVerbatimTag(), GlobalWasGeneratedByCompiler(), llvm::object::MachOObjectFile::guessLibraryShortName(), HasAnyUnrollPragma(), hasPrefix(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), intToken(), llvm::LTOModule::isBitcodeForTarget(), llvm::object::isDecorated(), llvm::object::Decompressor::isGnuStyle(), isIFunc(), llvm::MCSectionCOFF::isImplicitlyDiscardable(), isInput(), isInSymtab(), IsInterestingCmp(), llvm::ARMTTIImpl::isLoweredToCall(), isObjCClass(), llvm::objcarc::IsObjCIdentifiedObject(), isRegOrImmWithInputMods(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), llvm::lto::LTO::LTO(), llvm::MCGenDwarfLabelEntry::Make(), llvm::LTOModule::makeBuffer(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), llvm::GlobPattern::match(), matchAsm(), matchOption(), matchSVEPredicateVectorRegName(), llvm::mayBeOldLoopAttachmentTag(), MaybePredicatedInst(), llvm::PassInfoMixin< PromotePass >::name(), llvm::Triple::normalize(), optimizeDoubleFP(), llvm::parseAnalysisUtilityPasses(), parseArch(), llvm::ARM::parseArchEndian(), parseARMArch(), llvm::Pattern::parsePattern(), parseSubArch(), parseVersionFromName(), printSymbolizedStackTrace(), processGlobal(), PushArgMD(), llvm::SymbolRemappingReader::read(), llvm::Function::recalculateIntrinsicID(), RefineErrorLoc(), llvm::MCContext::RemapDebugPaths(), llvm::object::replace(), llvm::XCoreTargetLowering::ReplaceNodeResults(), llvm::runFuzzerOnInputs(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), shouldAlwaysEmitCompleteClassType(), shouldBeSls(), ShouldUpgradeX86Intrinsic(), startswith(), llvm::StringSwitch< T, R >::StartsWith(), llvm::SmallString< 256 >::startswith(), startsWithDefaultPipelineAliasPrefix(), llvm::StripDebugInfo(), stripNegationPrefix(), StripSymtab(), StripTypeNames(), truncateToSize(), upgradeAVX512MaskToSelect(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), upgradeLoopTag(), llvm::UpgradeSectionAttributes(), UpgradeX86IntrinsicFunction(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), and llvm::PrintIRInstrumentation::~PrintIRInstrumentation().
startswith_lower()
bool StringRef::startswith_lower (StringRef Prefix) const
Check if this string starts with the given Prefix, ignoring case.
Definition at line 47 of file StringRef.cpp.
References ascii_strncasecmp().
Referenced by addNegOperand(), llvm::detail::HelperFunctions::consumeHexStyle(), ExpandCryptoAEK(), find_lower(), incrementLoc(), matchOption(), startswith(), and llvm::StringSwitch< T, R >::StartsWithLower().
str()
LLVM_NODISCARD std::string llvm::StringRef::str () const inline
str - Get the contents as an std::string.
Definition at line 239 of file StringRef.h.
References LLVM_NODISCARD.
Referenced by addData(), llvm::DwarfCompileUnit::addGlobalName(), llvm::DwarfCompileUnit::addGlobalNameForTypeUnit(), llvm::DwarfCompileUnit::addGlobalType(), llvm::DwarfCompileUnit::addGlobalTypeUnitType(), llvm::cacheAnnotationFromMD(), collectCallSiteParameters(), llvm::sys::path::convert_to_slash(), llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), llvm::MachO::Symbol::dump(), llvm::vfs::RedirectingFileSystem::dumpEntry(), llvm::AMDGPUAsmPrinter::EmitFunctionEntryLabel(), llvm::PMDataManager::emitInstrCountChangedRemark(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::BTFDebug::endFunctionImpl(), llvm::FileCollector::FileCollector(), findInputFile(), llvm::CodeExtractor::findInputsOutputs(), llvm::DiagnosticLocation::getAbsolutePath(), llvm::StringInit::getAsString(), llvm::CodeInit::getAsString(), llvm::FieldInit::getAsString(), llvm::bfi_detail::getBlockName(), llvm::FileInfo::getCoveragePath(), getDescription(), llvm::Check::FileCheckType::getDescription(), llvm::GlobalValue::getGlobalIdentifier(), llvm::DOTGraphTraits< const Function * >::getGraphName(), llvm::vfs::File::getName(), getNodeVisualName(), llvm::getPGOFuncName(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::pdb::PDBSymbolCompiland::getSourceFileName(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::Record::getValueAsBitOrUnset(), llvm::PerFunctionMIParsingState::getVRegInfoNamed(), llvm::MCContext::getXCOFFSection(), llvm::yaml::ScalarTraits< StringValue >::input(), llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >::inputOne(), llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >::inputOne(), llvm::yaml::CustomMappingTraits< std::set< ELFSymbol > >::inputOne(), llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::inputOne(), llvm::yaml::CustomMappingTraits< MapDocNode >::inputOne(), llvm::yaml::CustomMappingTraits< TypeIdSummaryMapTy >::inputOne(), llvm::MachineRegisterInfo::insertVRegByName(), LLVMGetFunctionAddress(), llvm::LockFileManager::LockFileManager(), llvm::object::makeDuplicateResourceError(), mangleCoveragePath(), normalizePBQPSpillWeight(), operator std::string(), llvm::cl::parser< std::string >::parse(), parseIRConstant(), pathHasTraversal(), llvm::CachedPathResolver::resolve(), RetagMask(), rewriteComdat(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::MCContext::setCompilationDir(), llvm::MCParsedAsmOperand::setConstraint(), llvm::vfs::RedirectingFileSystem::setExternalContentsPrefixDir(), llvm::vfs::YAMLVFSWriter::setOverlayDir(), smallData(), llvm::Twine::str(), suffixed_name_or(), truncateToSize(), llvm::UpgradeDataLayoutString(), llvm::writeFileAtomically(), llvm::LTOCodeGenerator::writeMergedModules(), and writeTimestampFile().
substr()
LLVM_NODISCARD StringRef llvm::StringRef::substr (size_t Start, size_t N = npos) const inline
Return a reference to the substring from [Start, Start + N).
Parameters
Start The index of the starting character in the substring; if the index is npos or greater than the length of the string then the empty substring will be returned.
N The number of characters to included in the substring. If N exceeds the number of characters remaining in the string, the string suffix (starting with Start) will be returned.
Definition at line 600 of file StringRef.h.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), addNegOperand(), annotateNonNullAndDereferenceable(), llvm::FileCheckString::Check(), llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), llvm::FileCheck::checkInput(), CommaSeparateAndAddOccurrence(), llvm::consumeUnsignedInteger(), count(), CountNumNewlinesBetween(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createSampleProfileLoaderPass(), llvm::gsym::FunctionInfo::decode(), decodeBase64StringEntry(), llvm::FileCheckPatternContext::defineCmdlineVariables(), drop_back(), drop_front(), drop_until(), drop_while(), llvm::GlobalValue::dropLLVMManglingEscape(), llvm::ELFYAML::dropUniqueSuffix(), dumpTypeTagName(), llvm::DWARFUnit::DWARFUnit(), EatNumber(), emitComments(), llvm::emitSourceFileHeader(), llvm::BTFDebug::endFunctionImpl(), llvm::RuntimeDyldCheckerExprEval::evaluate(), ExpandCryptoAEK(), llvm::sys::path::extension(), llvm::DWARFFormValue::extractValue(), find_lower(), FindFirstMatchingPrefix(), llvm::MCJIT::findModuleForSymbol(), llvm::symbolize::LLVMSymbolizer::flush(), llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type >::format(), getAddrSpace(), llvm::AArch64::getArchExtFeature(), llvm::object::MachOUniversalBinary::ObjectForArch::getAsArchive(), llvm::ConstantDataSequential::getAsCString(), getAsInteger(), llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile(), GetAutoSenseRadix(), llvm::ARM::getCanonicalArchName(), llvm::getConstantStringInfo(), llvm::TargetLowering::getConstraintType(), llvm::Triple::getEnvironmentVersion(), llvm::GlobalValue::getGlobalIdentifier(), getGNUBinOpPrecedence(), getHexUint(), llvm::getMemOPSizeRangeFromOption(), getName(), llvm::object::ArchiveMemberHeader::getName(), llvm::Value::getName(), getNameWithPrefixImpl(), getOpEnabled(), getOpRefinementSteps(), getOptionPred(), llvm::Triple::getOSVersion(), llvm::FileCheckPatternContext::getPatternVarValue(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), getRegNum(), llvm::object::COFFObjectFile::getSectionName(), llvm::jitlink::Symbol::getSymbolContent(), llvm::getTypeName(), getTypeNamePrefix(), llvm::yaml::ScalarNode::getValue(), getVarName(), llvm::yaml::Node::getVerbatimTag(), HandlePrefixedOrGroupedOption(), incrementLoc(), INITIALIZE_PASS(), insertNoDuplicates(), intToken(), isIFunc(), isLoopPassName(), isRegOrImmWithInputMods(), loadTestingFormat(), llvm::gsym::FunctionInfo::lookup(), llvm::lto::LTO::LTO(), llvm::MCGenDwarfLabelEntry::Make(), llvm::GlobPattern::match(), llvm::Pattern::match(), matchAsm(), matchOption(), llvm::matchPassManager(), llvm::cl::SubCommand::operator bool(), llvm::sys::path::parent_path(), llvm::parseAnalysisUtilityPasses(), llvm::yaml::Document::parseBlockNode(), ParseHead(), parseInt(), ParseLine(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parsePattern(), parseRefinementStep(), llvm::Pattern::parseVariable(), parseVersionFromName(), previousIsLoop(), PrintCFIEscape(), llvm::Pattern::printFuzzyMatch(), printMCExpr(), PrintNoMatch(), PrintQuotedString(), llvm::FileCheck::readCheckFile(), RefineErrorLoc(), llvm::sys::path::relative_path(), llvm::sys::path::remove_leading_dotslash(), llvm::sys::path::rend(), llvm::object::replace(), llvm::sys::path::replace_path_prefix(), llvm::cl::ResetAllOptionOccurrences(), rfind(), rfind_lower(), llvm::sys::path::root_path(), scan(), shouldBeSls(), llvm::jitlink::LinkGraph::splitBlock(), llvm::formatv_object_base::splitLiteralAndReplacement(), splitUstar(), srcMgrDiagHandler(), llvm::sys::path::stem(), llvm::StrInStrNoCase(), llvm::SubtargetFeatures::StripFlag(), stripNegationPrefix(), llvm::Regex::sub(), take_until(), take_while(), llvm::VersionTuple::tryParse(), unescapeQuotedString(), upgradeAVX512MaskToSelect(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), llvm::UpgradeSectionAttributes(), UpgradeX86IntrinsicFunction(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), and llvm::sroa::AllocaSliceRewriter::visit().
take_back()
LLVM_NODISCARD StringRef llvm::StringRef::take_back (size_t N = 1) const inline
Return a StringRef equal to 'this' but with only the last N elements remaining.
If N is greater than the length of the string, the entire string is returned.
Definition at line 619 of file StringRef.h.
References drop_front(), LLVM_NODISCARD, N, and size().
Referenced by llvm::codeview::consume(), encodeCnt(), and llvm::codeview::GloballyHashedType::hashType().
take_front()
LLVM_NODISCARD StringRef llvm::StringRef::take_front (size_t N = 1) const inline
Return a StringRef equal to 'this' but with only the first N elements remaining.
If N is greater than the length of the string, the entire string is returned.
Definition at line 609 of file StringRef.h.
References drop_back(), LLVM_NODISCARD, N, and size().
Referenced by emitNullTerminatedSymbolName(), mapNameAndUniqueName(), llvm::codeview::CodeViewRecordIO::mapStringZ(), and llvm::Pattern::parseVariable().
take_until()
LLVM_NODISCARD StringRef llvm::StringRef::take_until (function_ref< bool(char)> F) const inline
Return the longest prefix of 'this' such that no character in the prefix satisfies the given predicate.
Definition at line 635 of file StringRef.h.
References F(), find_if(), LLVM_NODISCARD, and substr().
take_while()
LLVM_NODISCARD StringRef llvm::StringRef::take_while (function_ref< bool(char)> F) const inline
Return the longest prefix of 'this' such that every character in the prefix satisfies the given predicate.
Definition at line 628 of file StringRef.h.
References F(), find_if_not(), LLVM_NODISCARD, and substr().
Referenced by llvm::Annotations::Annotations(), llvm::formatv_object_base::splitLiteralAndReplacement(), and llvm::VFABI::tryDemangleForVFABI().
trim() [1/2]
LLVM_NODISCARD StringRef llvm::StringRef::trim (char Char) const inline
Return string with consecutive Char characters starting from the left and right removed.
Definition at line 839 of file StringRef.h.
References LLVM_NODISCARD, ltrim(), and rtrim().
Referenced by llvm::RuntimeDyldCheckerImpl::check(), llvm::RuntimeDyldCheckerExprEval::evaluate(), ExpandCryptoAEK(), incrementLoc(), llvm::IsCPSRDead< MCInst >(), llvm::formatv_object_base::parseReplacementItem(), and RefineErrorLoc().
trim() [2/2]
LLVM_NODISCARD StringRef llvm::StringRef::trim (StringRef Chars = " \t\n\v\f\r") const inline
Return string with consecutive characters in Chars starting from the left and right removed.
Definition at line 846 of file StringRef.h.
References ltrim(), and rtrim().
upper()
std::string StringRef::upper () const
Convert the given ASCII string to uppercase.
Definition at line 116 of file StringRef.cpp.
References llvm::numbers::e, size(), and llvm::toUpper().
Referenced by consumeInteger(), isCaseSensitivePath(), makeCombineInst(), and llvm::AArch64SysReg::parseGenericRegister().
withNullAsEmpty()
static StringRef llvm::StringRef::withNullAsEmpty (const char * data) inline static
Definition at line 114 of file StringRef.h.
References StringRef().
Member Data Documentation
npos
const size_t StringRef::npos = ~size_t(0) static
Definition at line 56 of file StringRef.h.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), addNegOperand(), llvm::X86FrameLowering::adjustForHiPEPrologue(), annotateNonNullAndDereferenceable(), buildFixItLine(), llvm::FileCheckString::Check(), llvm::FileCheck::checkInput(), CommaSeparateAndAddOccurrence(), contains(), contains_lower(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createSampleProfileLoaderPass(), llvm::sys::fs::createTemporaryFile(), llvm::FileCheckPatternContext::defineCmdlineVariables(), llvm::ELFYAML::dropUniqueSuffix(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::sys::path::extension(), find(), find_first_not_of(), find_first_of(), find_if(), find_last_not_of(), find_last_of(), find_lower(), llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type >::format(), llvm::ARM::getCanonicalArchName(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), llvm::DataExtractor::getCStr(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::sys::detail::getHostCPUNameForS390x(), llvm::SourceMgr::getLineAndColumn(), llvm::Value::getName(), llvm::InstrProfSymtab::getOrigFuncName(), llvm::FileCheckPatternContext::getPatternVarValue(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::getTypeName(), getTypeNamePrefix(), llvm::yaml::ScalarNode::getValue(), llvm::object::MachOObjectFile::guessLibraryShortName(), hasConflictingReferenceFlags(), hasObjCCategory(), hasWildcard(), llvm::MIRParserImpl::initializeJumpTableInfo(), llvm::GCNSubtarget::initializeSubtargetDependencies(), instrumentMaskedLoadOrStore(), is_ns_word_char(), llvm::ConstantDataSequential::isCString(), isIFunc(), llvm::Regex::isLiteralERE(), isLoopPassName(), llvm::objcarc::IsObjCIdentifiedObject(), isReportingError(), isSmallDataSection(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), llvm::Pattern::match(), llvm::matchPassManager(), MCAttrForString(), llvm::cl::SubCommand::operator bool(), llvm::sys::path::reverse_iterator::operator++(), optimizeMemCmpConstantSize(), llvm::sys::path::parent_path(), ParseLine(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parsePattern(), parseRefinementStep(), llvm::Pattern::printFuzzyMatch(), printName(), printSourceLine(), llvm::BinaryStreamReader::readCString(), llvm::sys::path::remove_filename(), llvm::object::replace(), llvm::sys::path::replace_extension(), rfind(), rfind_lower(), rsplit(), sanitizeFunctionName(), setRequiredFeatureString(), split(), llvm::formatv_object_base::splitLiteralAndReplacement(), splitUstar(), llvm::sys::path::stem(), llvm::StrInStrNoCase(), UpgradeIntrinsicFunction1(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), and llvm::sroa::AllocaSliceRewriter::visit().
The documentation for this class was generated from the following files:
include/llvm/ADT/StringRef.h
lib/Support/StringRef.cpp