LLVM: llvm::PredicatedScalarEvolution Class Reference
llvm::PredicatedScalarEvolution Class Reference
An interface layer with SCEV used to manage how we see SCEV expressions for values in the context of existing predicates.
#include "llvm/Analysis/ScalarEvolution.h"
Public Member Functions
PredicatedScalarEvolution (ScalarEvolution &SE, Loop &L)
const SCEVUnionPredicate & getUnionPredicate () const
const SCEV * getSCEV (Value *V)
Returns the SCEV expression of V, in the context of the current SCEV predicate.
const SCEV * getBackedgeTakenCount ()
Get the (predicated) backedge count for the analyzed loop.
void addPredicate (const SCEVPredicate &Pred)
Adds a new predicate.
const SCEVAddRecExpr * getAsAddRec (Value *V)
Attempts to produce an AddRecExpr for V by adding additional SCEV predicates.
void setNoOverflow (Value *V, SCEVWrapPredicate::IncrementWrapFlags Flags)
Proves that V doesn't overflow by adding SCEV predicate.
bool hasNoOverflow (Value *V, SCEVWrapPredicate::IncrementWrapFlags Flags)
Returns true if we've proved that V doesn't wrap by means of a SCEV predicate.
ScalarEvolution * getSE () const
Returns the ScalarEvolution analysis used.
PredicatedScalarEvolution (const PredicatedScalarEvolution &)
We need to explicitly define the copy constructor because of FlagsMap.
void print (raw_ostream &OS, unsigned Depth) const
Print the SCEV mappings done by the Predicated Scalar Evolution.
bool areAddRecsEqualWithPreds (const SCEVAddRecExpr *AR1, const SCEVAddRecExpr *AR2) const
Check if AR1 and AR2 are equal, while taking into account Equal predicates in Preds.
Detailed Description
An interface layer with SCEV used to manage how we see SCEV expressions for values in the context of existing predicates.
We can add new predicates, but we cannot remove them.
This layer has multiple purposes:
provides a simple interface for SCEV versioning.
guarantees that the order of transformations applied on a SCEV expression for a single Value is consistent across two different getSCEV calls. This means that, for example, once we've obtained an AddRec expression for a certain value through expression rewriting, we will continue to get an AddRec expression for that Value.
lowers the number of expression rewrites.
Definition at line 1974 of file ScalarEvolution.h.
Constructor & Destructor Documentation
PredicatedScalarEvolution() [1/2]
PredicatedScalarEvolution::PredicatedScalarEvolution (ScalarEvolution & SE, Loop & L)
Definition at line 12447 of file ScalarEvolution.cpp.
PredicatedScalarEvolution() [2/2]
PredicatedScalarEvolution::PredicatedScalarEvolution (const PredicatedScalarEvolution & Init)
We need to explicitly define the copy constructor because of FlagsMap.
Definition at line 12548 of file ScalarEvolution.cpp.
References I.
Member Function Documentation
addPredicate()
void PredicatedScalarEvolution::addPredicate (const SCEVPredicate & Pred)
Adds a new predicate.
Definition at line 12479 of file ScalarEvolution.cpp.
References llvm::SCEVUnionPredicate::add(), and llvm::SCEVUnionPredicate::implies().
Referenced by getBackedgeTakenCount(), llvm::replaceSymbolicStrideSCEV(), and setNoOverflow().
areAddRecsEqualWithPreds()
bool PredicatedScalarEvolution::areAddRecsEqualWithPreds (const SCEVAddRecExpr * AR1, const SCEVAddRecExpr * AR2) const
Check if AR1 and AR2 are equal, while taking into account Equal predicates in Preds.
Definition at line 4948 of file ScalarEvolution.cpp.
References llvm::MCID::Add, assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::numbers::e, llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEV::FlagNW, GEP, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::isKnownPositive(), llvm::Loop::isLoopInvariant(), MatchBinaryOp(), llvm::SmallVectorTemplateBase< T >::push_back(), and rewrite().
Referenced by getCastsForInductionPHI().
getAsAddRec()
const SCEVAddRecExpr * PredicatedScalarEvolution::getAsAddRec (Value * V)
Attempts to produce an AddRecExpr for V by adding additional SCEV predicates.
If we can't transform the expression into an AddRecExpr we return nullptr and not add additional SCEV predicates to the current context.
Definition at line 12532 of file ScalarEvolution.cpp.
References llvm::SCEVUnionPredicate::add(), llvm::ScalarEvolution::convertSCEVToAddRecWithPredicates(), llvm::ScalarEvolution::getSCEV(), getSCEV(), and P.
Referenced by llvm::getPtrStride(), hasComputableBounds(), and llvm::InductionDescriptor::isInductionPHI().
getBackedgeTakenCount()
const SCEV * PredicatedScalarEvolution::getBackedgeTakenCount ()
Get the (predicated) backedge count for the analyzed loop.
Definition at line 12470 of file ScalarEvolution.cpp.
References addPredicate(), and llvm::ScalarEvolution::getPredicatedBackedgeTakenCount().
Referenced by llvm::InnerLoopVectorizer::getOrCreateTripCount(), and llvm::RuntimePointerChecking::insert().
getSCEV()
const SCEV * PredicatedScalarEvolution::getSCEV (Value * V)
Returns the SCEV expression of V, in the context of the current SCEV predicate.
The order of transformations applied on the expression of V returned by ScalarEvolution is guaranteed to be preserved, even when adding new predicates.
Definition at line 12451 of file ScalarEvolution.cpp.
References llvm::ScalarEvolution::getSCEV(), and llvm::ScalarEvolution::rewriteUsingPredicate().
Referenced by getAddressAccessSCEV(), getAsAddRec(), getCastsForInductionPHI(), hasNoOverflow(), llvm::InductionDescriptor::isInductionPHI(), isLoadConditional(), isNoWrap(), isNoWrapAddRec(), llvm::replaceSymbolicStrideSCEV(), setNoOverflow(), and llvm::InnerLoopVectorizer::widenInstruction().
getSE()
ScalarEvolution* llvm::PredicatedScalarEvolution::getSE () const inline
Returns the ScalarEvolution analysis used.
Definition at line 2006 of file ScalarEvolution.h.
References llvm::Depth, and llvm::SCEV::print().
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::InnerLoopVectorizer::fixVectorizedLoop(), getAddressAccessSCEV(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::getPtrStride(), hasComputableBounds(), llvm::RuntimePointerChecking::insert(), llvm::InductionDescriptor::isInductionPHI(), isLoadConditional(), isNoWrap(), isStrideMul(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), llvm::replaceSymbolicStrideSCEV(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::InnerLoopVectorizer::widenInstruction(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getUnionPredicate()
const SCEVUnionPredicate & PredicatedScalarEvolution::getUnionPredicate () const
Definition at line 12486 of file ScalarEvolution.cpp.
References llvm::ScalarEvolution::rewriteUsingPredicate().
Referenced by llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::InnerLoopVectorizer::emitSCEVChecks(), isLoadConditional(), llvm::LoopVersioning::LoopVersioning(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), and llvm::LoopVersioning::versionLoop().
hasNoOverflow()
bool PredicatedScalarEvolution::hasNoOverflow (Value * V, SCEVWrapPredicate::IncrementWrapFlags Flags)
Returns true if we've proved that V doesn't wrap by means of a SCEV predicate.
Definition at line 12516 of file ScalarEvolution.cpp.
References llvm::SCEVWrapPredicate::clearFlags(), llvm::SCEVWrapPredicate::getImpliedFlags(), getSCEV(), and llvm::SCEVWrapPredicate::IncrementAnyWrap.
Referenced by llvm::getPtrStride(), and isNoWrap().
print()
void PredicatedScalarEvolution::print (raw_ostream & OS, unsigned Depth) const
Print the SCEV mappings done by the Predicated Scalar Evolution.
The printed text is indented by Depth.
Definition at line 12556 of file ScalarEvolution.cpp.
References llvm::MCID::Add, B, llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::ScalarEvolution::getSCEV(), I, llvm::raw_ostream::indent(), and llvm::ScalarEvolution::isSCEVable().
setNoOverflow()
void PredicatedScalarEvolution::setNoOverflow (Value * V, SCEVWrapPredicate::IncrementWrapFlags Flags)
Proves that V doesn't overflow by adding SCEV predicate.
Definition at line 12500 of file ScalarEvolution.cpp.
References addPredicate(), llvm::SCEVWrapPredicate::clearFlags(), llvm::SCEVWrapPredicate::getImpliedFlags(), getSCEV(), llvm::ScalarEvolution::getWrapPredicate(), and llvm::SCEVWrapPredicate::setFlags().
Referenced by llvm::getPtrStride().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolution.h
lib/Analysis/ScalarEvolution.cpp