LLVM: llvm::DWARFDebugAbbrev Class Reference
llvm::DWARFDebugAbbrev Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
Public Member Functions
DWARFDebugAbbrev ()
const DWARFAbbreviationDeclarationSet * getAbbreviationDeclarationSet (uint64_t CUAbbrOffset) const
void dump (raw_ostream &OS) const
void parse () const
void extract (DataExtractor Data)
DWARFAbbreviationDeclarationSetMap::const_iterator begin () const
DWARFAbbreviationDeclarationSetMap::const_iterator end () const
Detailed Description
Definition at line 54 of file DWARFDebugAbbrev.h.
Constructor & Destructor Documentation
DWARFDebugAbbrev()
DWARFDebugAbbrev::DWARFDebugAbbrev ()
Definition at line 70 of file DWARFDebugAbbrev.cpp.
Member Function Documentation
begin()
DWARFAbbreviationDeclarationSetMap::const_iterator llvm::DWARFDebugAbbrev::begin () const inline
Definition at line 72 of file DWARFDebugAbbrev.h.
References parse().
dump()
void DWARFDebugAbbrev::dump (raw_ostream & OS) const
Definition at line 99 of file DWARFDebugAbbrev.cpp.
References llvm::format(), I, and parse().
Referenced by llvm::DWARFContext::dump().
end()
DWARFAbbreviationDeclarationSetMap::const_iterator llvm::DWARFDebugAbbrev::end () const inline
Definition at line 77 of file DWARFDebugAbbrev.h.
extract()
void DWARFDebugAbbrev::extract (DataExtractor Data)
Definition at line 77 of file DWARFDebugAbbrev.cpp.
References llvm::Data.
getAbbreviationDeclarationSet()
const DWARFAbbreviationDeclarationSet * DWARFDebugAbbrev::getAbbreviationDeclarationSet (uint64_t CUAbbrOffset) const
Definition at line 114 of file DWARFDebugAbbrev.cpp.
Referenced by llvm::DWARFUnit::getAbbreviations(), and llvm::DWARFVerifier::DieRangeInfo::intersects().
parse()
void DWARFDebugAbbrev::parse () const
Definition at line 82 of file DWARFDebugAbbrev.cpp.
References llvm::Data, llvm::DWARFAbbreviationDeclarationSet::extract(), I, and llvm::None.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h
lib/DebugInfo/DWARF/DWARFDebugAbbrev.cpp