LLVM: llvm::orc::RemoteObjectServerLayer< BaseLayerT, RPCEndpoint > Class Template Reference
llvm::orc::RemoteObjectServerLayer< BaseLayerT, RPCEndpoint > Class Template Reference
RemoteObjectServerLayer acts as a server and handling RPC calls for the object layer API from the given RPC connection.
#include "llvm/ExecutionEngine/Orc/RemoteObjectLayer.h"
Public Member Functions
LLVM_ATTRIBUTE_DEPRECATED (RemoteObjectServerLayer(BaseLayerT &BaseLayer, RPCEndpoint &Remote, std::function< void(Error)> ReportError), "ORCv1 layers (including RemoteObjectServerLayer) are deprecated. Please " "use " "ORCv2 (see docs/ORCv2.rst)")
Create a RemoteObjectServerLayer with the given base layer (which must be an object layer), RPC endpoint, and error reporter function.
RemoteObjectServerLayer (ORCv1DeprecationAcknowledgement, BaseLayerT &BaseLayer, RPCEndpoint &Remote, std::function< void(Error)> ReportError)
Public Member Functions inherited from llvm::orc::RemoteObjectLayer< RPCEndpoint >
RemoteObjectLayer (RPCEndpoint &Remote, std::function< void(Error)> ReportError)
Additional Inherited Members
Public Types inherited from llvm::orc::RemoteObjectLayerAPI
using ObjHandleT = remote::ResourceIdMgr::ResourceId
using BadSymbolHandleError = remote::ResourceNotFound< RemoteSymbolId >
using BadObjectHandleError = remote::ResourceNotFound< ObjHandleT >
Protected Types inherited from llvm::orc::RemoteObjectLayerAPI
using RemoteSymbolId = remote::ResourceIdMgr::ResourceId
using RemoteSymbol = std::pair< RemoteSymbolId, JITSymbolFlags >
Protected Member Functions inherited from llvm::orc::RemoteObjectLayer< RPCEndpoint >
RemoteSymbol nullRemoteSymbol ()
Convenience function for getting a null remote symbol value.
Error teeLog (Error Err)
Creates a StringError that contains a copy of Err's log message, then sends that StringError to ReportError.
Error badRemoteSymbolIdError (RemoteSymbolId Id)
Error badObjectHandleError (ObjHandleT H)
Expected< RemoteSymbol > jitSymbolToRemote (JITSymbol Sym)
Create a RemoteSymbol wrapping the given JITSymbol.
JITSymbol remoteToJITSymbol (Expected< RemoteSymbol > RemoteSymOrErr)
Convert an Expected<RemoteSymbol> to a JITSymbol.
Protected Attributes inherited from llvm::orc::RemoteObjectLayer< RPCEndpoint >
RPCEndpoint & Remote
std::function< void(Error)> ReportError
Static Protected Attributes inherited from llvm::orc::RemoteObjectLayerAPI
static const ObjHandleT InvalidObjectHandleId = 0
static const RemoteSymbolId NullSymbolId = 0
Detailed Description
template<typename BaseLayerT, typename RPCEndpoint>
class llvm::orc::RemoteObjectServerLayer< BaseLayerT, RPCEndpoint >
RemoteObjectServerLayer acts as a server and handling RPC calls for the object layer API from the given RPC connection.
This class can be composed on top of a 'real' object layer (e.g. RTDyldObjectLinkingLayer) to do the actual work of relocating objects and making them executable.
Definition at line 401 of file RemoteObjectLayer.h.
Constructor & Destructor Documentation
RemoteObjectServerLayer()
template<typename BaseLayerT , typename RPCEndpoint > llvm::orc::RemoteObjectServerLayer< BaseLayerT, RPCEndpoint >::RemoteObjectServerLayer (ORCv1DeprecationAcknowledgement , BaseLayerT & BaseLayer, RPCEndpoint & Remote, std::function< void(Error)> ReportError) inline
Definition at line 430 of file RemoteObjectLayer.h.
References llvm::AcknowledgeORCv1Deprecation, assert(), llvm::orc::createLambdaResolver(), H, llvm::AArch64CC::HI, llvm::cl::init(), lookup(), and Name.
Member Function Documentation
LLVM_ATTRIBUTE_DEPRECATED()
template<typename BaseLayerT , typename RPCEndpoint > llvm::orc::RemoteObjectServerLayer< BaseLayerT, RPCEndpoint >::LLVM_ATTRIBUTE_DEPRECATED (RemoteObjectServerLayer< BaseLayerT, RPCEndpoint >(BaseLayerT &BaseLayer, RPCEndpoint &Remote, std::function< void(Error)> ReportError) , "ORCv1 layers (including RemoteObjectServerLayer< BaseLayerT, RPCEndpoint >) are deprecated. Please " "use " "ORCv2 (see docs/ORCv2.rst)")
Create a RemoteObjectServerLayer with the given base layer (which must be an object layer), RPC endpoint, and error reporter function.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RemoteObjectLayer.h