LLVM: llvm::GVNExpression::UnknownExpression Class Reference
llvm::GVNExpression::UnknownExpression Class Reference final
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Member Functions
UnknownExpression (Instruction *I)
UnknownExpression ()=delete
UnknownExpression (const UnknownExpression &)=delete
UnknownExpression & operator= (const UnknownExpression &)=delete
Instruction * getInstruction () const
void setInstruction (Instruction *I)
bool equals (const Expression &Other) const override
hash_code getHashValue () const override
void printInternal (raw_ostream &OS, bool PrintEType) const override
Public Member Functions inherited from llvm::GVNExpression::Expression
Expression (ExpressionType ET=ET_Base, unsigned O=~2U)
Expression (const Expression &)=delete
Expression & operator= (const Expression &)=delete
virtual ~Expression ()
bool operator!= (const Expression &Other) const
bool operator== (const Expression &Other) const
hash_code getComputedHash () const
virtual bool exactlyEquals (const Expression &Other) const
unsigned getOpcode () const
void setOpcode (unsigned opcode)
ExpressionType getExpressionType () const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::Expression
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
Detailed Description
Definition at line 622 of file GVNExpression.h.
Constructor & Destructor Documentation
UnknownExpression() [1/3]
llvm::GVNExpression::UnknownExpression::UnknownExpression (Instruction * I) inline
Definition at line 627 of file GVNExpression.h.
References llvm::GVNExpression::Expression::operator=().
UnknownExpression() [2/3]
llvm::GVNExpression::UnknownExpression::UnknownExpression () delete
UnknownExpression() [3/3]
llvm::GVNExpression::UnknownExpression::UnknownExpression (const UnknownExpression &) delete
Member Function Documentation
classof()
static bool llvm::GVNExpression::UnknownExpression::classof (const Expression * EB) inline static
Definition at line 632 of file GVNExpression.h.
References llvm::GVNExpression::ET_Unknown, and llvm::GVNExpression::Expression::getExpressionType().
equals()
bool llvm::GVNExpression::UnknownExpression::equals (const Expression & Other) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 639 of file GVNExpression.h.
getHashValue()
hash_code llvm::GVNExpression::UnknownExpression::getHashValue () const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 644 of file GVNExpression.h.
References llvm::GVNExpression::Expression::getHashValue(), and llvm::hash_combine().
getInstruction()
Instruction* llvm::GVNExpression::UnknownExpression::getInstruction () const inline
Definition at line 636 of file GVNExpression.h.
operator=()
UnknownExpression& llvm::GVNExpression::UnknownExpression::operator= (const UnknownExpression &) delete
printInternal()
void llvm::GVNExpression::UnknownExpression::printInternal (raw_ostream & OS, bool PrintEType) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 649 of file GVNExpression.h.
References llvm::GVNExpression::Expression::printInternal().
setInstruction()
void llvm::GVNExpression::UnknownExpression::setInstruction (Instruction * I) inline
Definition at line 637 of file GVNExpression.h.
References I.
The documentation for this class was generated from the following file:
include/llvm/Transforms/Scalar/GVNExpression.h