LLVM: llvm::MSP430InstrInfo Class Reference
llvm::MSP430InstrInfo Class Reference
#include "Target/MSP430/MSP430InstrInfo.h"
Public Member Functions
MSP430InstrInfo (MSP430Subtarget &STI)
const TargetRegisterInfo & getRegisterInfo () const
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIdx, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
bool isUnpredicatedTerminator (const MachineInstr &MI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
int64_t getFramePoppedByCallee (const MachineInstr &I) const
Detailed Description
Definition at line 26 of file MSP430InstrInfo.h.
Constructor & Destructor Documentation
MSP430InstrInfo()
MSP430InstrInfo::MSP430InstrInfo (MSP430Subtarget & STI) explicit
Definition at line 32 of file MSP430InstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool MSP430InstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 175 of file MSP430InstrInfo.cpp.
copyPhysReg()
void MSP430InstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 90 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::getKillRegState(), and llvm_unreachable.
Referenced by getRegisterInfo().
getFramePoppedByCallee()
int64_t llvm::MSP430InstrInfo::getFramePoppedByCallee (const MachineInstr & I) const inline
Definition at line 72 of file MSP430InstrInfo.h.
References assert(), llvm::MachineOperand::getImm(), and llvm::MachineInstr::getOperand().
Referenced by llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr().
getInstSizeInBytes()
unsigned MSP430InstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
This returns the maximum number of bytes.
Definition at line 300 of file MSP430InstrInfo.cpp.
References llvm::ISD::EH_LABEL, llvm::MachineInstr::getDesc(), llvm::TargetInstrInfo::getInlineAsmLength(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MCInstrDesc::getSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::AMDGPUISD::KILL, and TII.
Referenced by getRegisterInfo().
getRegisterInfo()
const TargetRegisterInfo& llvm::MSP430InstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 36 of file MSP430InstrInfo.h.
References copyPhysReg(), llvm::ISD::FrameIndex, getInstSizeInBytes(), I, loadRegFromStackSlot(), MI, reverseBranchCondition(), storeRegToStackSlot(), and TRI.
Referenced by llvm::MSP430Subtarget::getRegisterInfo().
insertBranch()
unsigned MSP430InstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 265 of file MSP430InstrInfo.cpp.
isUnpredicatedTerminator()
bool MSP430InstrInfo::isUnpredicatedTerminator (const MachineInstr & MI) const override
Definition at line 163 of file MSP430InstrInfo.cpp.
References llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isPredicable(), llvm::HexagonMCInstrInfo::isPredicated(), and llvm::MachineInstr::isTerminator().
loadRegFromStackSlot()
void MSP430InstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIdx, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 63 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getDefRegState(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm_unreachable, and llvm::MachineMemOperand::MOLoad.
Referenced by getRegisterInfo().
removeBranch()
unsigned MSP430InstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 106 of file MSP430InstrInfo.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, and reverseBranchCondition().
reverseBranchCondition()
bool MSP430InstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 132 of file MSP430InstrInfo.cpp.
Referenced by getRegisterInfo(), and removeBranch().
storeRegToStackSlot()
void MSP430InstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 36 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm_unreachable, and llvm::MachineMemOperand::MOStore.
Referenced by getRegisterInfo().
The documentation for this class was generated from the following files:
lib/Target/MSP430/MSP430InstrInfo.h
lib/Target/MSP430/MSP430InstrInfo.cpp