LLVM: llvm::HexagonRegisterInfo Class Reference
llvm::HexagonRegisterInfo Class Reference
#include "Target/Hexagon/HexagonRegisterInfo.h"
Public Member Functions
HexagonRegisterInfo (unsigned HwMode)
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
Returns true since we may need scavenging for a temporary register when generating hardware loop instructions.
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
Returns true.
bool useFPForScavengingIndex (const MachineFunction &MF) const override
Returns true if the frame pointer is valid.
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC, LiveIntervals &LIS) const override
unsigned getRARegister () const
Register getFrameRegister (const MachineFunction &MF) const override
unsigned getFrameRegister () const
unsigned getStackRegister () const
unsigned getHexagonSubRegIndex (const TargetRegisterClass &RC, unsigned GenIdx) const
const MCPhysReg * getCallerSavedRegs (const MachineFunction *MF, const TargetRegisterClass *RC) const
unsigned getFirstCallerSavedNonParamReg () const
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
bool isEHReturnCalleeSaveReg (unsigned Reg) const
Detailed Description
Definition at line 29 of file HexagonRegisterInfo.h.
Constructor & Destructor Documentation
HexagonRegisterInfo()
HexagonRegisterInfo::HexagonRegisterInfo (unsigned HwMode)
Definition at line 44 of file HexagonRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void HexagonRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 185 of file HexagonRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::HexagonSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), MI, MRI, llvm::MachineInstr::RemoveOperand(), and llvm::MachineInstr::setDesc().
getCalleeSavedRegs()
const MCPhysReg * HexagonRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 107 of file HexagonRegisterInfo.cpp.
References llvm::MachineFunction::getInfo(), and R2.
Referenced by llvm::HexagonFrameLowering::determineCalleeSaves().
getCallerSavedRegs()
const MCPhysReg * HexagonRegisterInfo::getCallerSavedRegs (const MachineFunction * MF, const TargetRegisterClass * RC) const
Definition at line 55 of file HexagonRegisterInfo.cpp.
References llvm::dbgs(), llvm::Empty, llvm::TargetRegisterClass::getID(), llvm_unreachable, R2, R4, R6, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::NVPTX::PTXLdStInstCode::V4.
Referenced by needToReserveScavengingSpillSlots().
getCallPreservedMask()
const uint32_t * HexagonRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const override
Definition at line 129 of file HexagonRegisterInfo.cpp.
Referenced by llvm::HexagonTargetLowering::LowerCall().
getFirstCallerSavedNonParamReg()
unsigned HexagonRegisterInfo::getFirstCallerSavedNonParamReg () const
Definition at line 348 of file HexagonRegisterInfo.cpp.
References R6.
getFrameRegister() [1/2]
Register HexagonRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 294 of file HexagonRegisterInfo.cpp.
References getFrameRegister(), getStackRegister(), and llvm::HexagonFrameLowering::hasFP().
Referenced by llvm::HexagonInstrInfo::expandPostRAPseudo(), and llvm::HexagonTargetLowering::LowerFRAMEADDR().
getFrameRegister() [2/2]
unsigned HexagonRegisterInfo::getFrameRegister () const
Definition at line 303 of file HexagonRegisterInfo.cpp.
Referenced by getFrameRegister().
getHexagonSubRegIndex()
unsigned HexagonRegisterInfo::getHexagonSubRegIndex (const TargetRegisterClass & RC, unsigned GenIdx) const
Definition at line 313 of file HexagonRegisterInfo.cpp.
References assert(), llvm::TargetRegisterClass::getID(), llvm::TargetRegisterClass::getSuperClasses(), llvm_unreachable, llvm::Hexagon::ps_sub_hi, and llvm::Hexagon::ps_sub_lo.
getPointerRegClass()
const TargetRegisterClass * HexagonRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 343 of file HexagonRegisterInfo.cpp.
getRARegister()
unsigned HexagonRegisterInfo::getRARegister () const
Definition at line 289 of file HexagonRegisterInfo.cpp.
Referenced by llvm::HexagonTargetLowering::LowerINLINEASM(), and llvm::HexagonTargetLowering::LowerRETURNADDR().
getReservedRegs()
BitVector HexagonRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 135 of file HexagonRegisterInfo.cpp.
References llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::MachineFunction::getSubtarget(), llvm::HexagonSubtarget::hasReservedR19(), and llvm::BitVector::set().
getStackRegister()
unsigned HexagonRegisterInfo::getStackRegister () const
Definition at line 308 of file HexagonRegisterInfo.cpp.
Referenced by llvm::HexagonInstrInfo::getDuplexCandidateGroup(), getFrameRegister(), and llvm::HexagonTargetLowering::LowerCall().
isEHReturnCalleeSaveReg()
bool HexagonRegisterInfo::isEHReturnCalleeSaveReg (unsigned Reg) const
Definition at line 49 of file HexagonRegisterInfo.cpp.
References R2.
Referenced by llvm::HexagonFrameLowering::getFrameIndexReference().
requiresFrameIndexScavenging()
bool llvm::HexagonRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Returns true.
Spill code for predicate registers might need an extra register.
Definition at line 52 of file HexagonRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::HexagonRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Returns true since we may need scavenging for a temporary register when generating hardware loop instructions.
Definition at line 46 of file HexagonRegisterInfo.h.
shouldCoalesce()
bool HexagonRegisterInfo::shouldCoalesce (MachineInstr * MI, const TargetRegisterClass * SrcRC, unsigned SubReg, const TargetRegisterClass * DstRC, unsigned DstSubReg, const TargetRegisterClass * NewRC, LiveIntervals & LIS) const override
Definition at line 240 of file HexagonRegisterInfo.cpp.
References llvm::any_of(), E, llvm::TargetRegisterClass::getID(), llvm::SlotIndexes::getInstructionFromIndex(), llvm::LiveIntervals::getInterval(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::LiveIntervals::getSlotIndexes(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineInstr::isCall(), and llvm::HexagonSubtarget::useHVXOps().
trackLivenessAfterRegAlloc()
bool llvm::HexagonRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline override
Definition at line 59 of file HexagonRegisterInfo.h.
References MI, Reg, and SubReg.
useFPForScavengingIndex()
bool HexagonRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const override
Returns true if the frame pointer is valid.
Definition at line 337 of file HexagonRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonRegisterInfo.h
lib/Target/Hexagon/HexagonRegisterInfo.cpp