LLVM: llvm::GlobalAlias Class Reference
llvm::GlobalAlias Class Reference
#include "llvm/IR/GlobalAlias.h"
Public Member Functions
GlobalAlias (const GlobalAlias &)=delete
GlobalAlias & operator= (const GlobalAlias &)=delete
void removeFromParent ()
removeFromParent - This method unlinks 'this' from the containing module, but does not delete it.
void eraseFromParent ()
eraseFromParent - This method unlinks 'this' from the containing module and deletes it.
void setAliasee (Constant *Aliasee)
These methods retrieve and set alias target.
const Constant * getAliasee () const
Constant * getAliasee ()
Public Member Functions inherited from llvm::GlobalIndirectSymbol
GlobalIndirectSymbol (const GlobalIndirectSymbol &)=delete
GlobalIndirectSymbol & operator= (const GlobalIndirectSymbol &)=delete
void * operator new (size_t s)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Provide fast operand accessors.
void copyAttributesFrom (const GlobalValue *Src)
void setIndirectSymbol (Constant *Symbol)
These methods set and retrieve indirect symbol.
const Constant * getIndirectSymbol () const
Constant * getIndirectSymbol ()
const GlobalObject * getBaseObject () const
GlobalObject * getBaseObject ()
const GlobalObject * getBaseObject (const DataLayout &DL, APInt &Offset) const
GlobalObject * getBaseObject (const DataLayout &DL, APInt &Offset)
Public Member Functions inherited from llvm::GlobalValue
GlobalValue (const GlobalValue &)=delete
unsigned getAlignment () const
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
void setUnnamedAddr (UnnamedAddr Val)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
StringRef getSection () const
PointerType * getType () const
Global values are always pointers.
Type * getValueType () const
void setDSOLocal (bool Local)
bool isDSOLocal () const
bool hasPartition () const
StringRef getPartition () const
void setPartition (StringRef Part)
bool isDefinitionExact () const
Return true if the currently visible definition of this global (if any) is exactly the definition we will see at runtime.
bool hasExactDefinition () const
Return true if this global has an exact defintion.
bool isInterposable () const
Return true if this global's definition can be substituted with an arbitrary definition at link time.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
bool hasValidDeclarationLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool isWeakForLinker () const
std::string getGlobalIdentifier () const
Return the modified name for this global value suitable to be used as the key for a global lookup (e.g.
GUID getGUID () const
Return a 64-bit global unique ID constructed from global value name (i.e.
bool isDeclaration () const
Return true if the primary definition of this global value is outside of the current translation unit.
bool isDeclarationForLinker () const
bool isStrongDefinitionForLinker () const
Returns true if this global's definition will be the one chosen by the linker.
bool canIncreaseAlignment () const
const GlobalObject * getBaseObject () const
GlobalObject * getBaseObject ()
bool isAbsoluteSymbolRef () const
Returns whether this is a reference to an absolute symbol.
Optional< ConstantRange > getAbsoluteSymbolRange () const
If this is an absolute symbol reference, returns the range of the symbol, otherwise returns None.
void removeFromParent ()
This method unlinks 'this' from the containing module, but does not delete it.
void eraseFromParent ()
This method unlinks 'this' from the containing module and deletes it.
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
bool canBeOmittedFromSymbolTable () const
True if GV can be left out of the object symbol table.
bool isMaterializable () const
If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Error materialize ()
Make sure this GlobalValue is fully read.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefElement () const
Return true if this is a vector constant that includes any undefined elements.
bool containsConstantExpression () const
Return true if this is a vector constant that includes any constant expressions.
bool canTrap () const
Return true if evaluation of this constant could trap.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry.
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< GlobalAlias, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static GlobalAlias * create (Type *Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine &Name, Constant *Aliasee, Module *Parent)
If a parent module is specified, the alias is automatically inserted into the end of the specified module's alias list.
static GlobalAlias * create (Type *Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine &Name, Module *Parent)
static GlobalAlias * create (Type *Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine &Name, GlobalValue *Aliasee)
static GlobalAlias * create (LinkageTypes Linkage, const Twine &Name, GlobalValue *Aliasee)
static GlobalAlias * create (const Twine &Name, GlobalValue *Aliasee)
static bool isValidLinkage (LinkageTypes L)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalIndirectSymbol
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalValue
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isValidDeclarationLinkage (LinkageTypes Linkage)
static bool isInterposableLinkage (LinkageTypes Linkage)
Whether the definition of this global may be replaced by something non-equivalent at link time.
static bool isDiscardableIfUnused (LinkageTypes Linkage)
Whether the definition of this global may be discarded if it is not used in its compilation unit.
static bool isWeakForLinker (LinkageTypes Linkage)
Whether the definition of this global may be replaced at link time.
static StringRef dropLLVMManglingEscape (StringRef Name)
If the given string begins with the GlobalValue name mangling escape character '\1', drop it.
static std::string getGlobalIdentifier (StringRef Name, GlobalValue::LinkageTypes Linkage, StringRef FileName)
Return the modified name for a global value suitable to be used as the key for a global lookup (e.g.
static GUID getGUID (StringRef GlobalName)
Return a 64-bit global unique ID constructed from global value name (i.e.
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class SymbolTableListTraits< GlobalAlias >
Additional Inherited Members
Public Types inherited from llvm::GlobalValue
enum LinkageTypes {
ExternalLinkage = 0, AvailableExternallyLinkage, LinkOnceAnyLinkage, LinkOnceODRLinkage,
WeakAnyLinkage, WeakODRLinkage, AppendingLinkage, InternalLinkage,
PrivateLinkage, ExternalWeakLinkage, CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0, HiddenVisibility, ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0, DLLImportStorageClass = 1, DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0, GeneralDynamicTLSModel, LocalDynamicTLSModel, InitialExecTLSModel,
LocalExecTLSModel
}
enum UnnamedAddr { UnnamedAddr::None, UnnamedAddr::Local, UnnamedAddr::Global }
using GUID = uint64_t
Declare a type to represent a global unique identifier for a global value.
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< GlobalAlias, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< GlobalAlias, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< GlobalAlias, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< GlobalAlias, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< GlobalAlias, Options... >::type, true, true >
Protected Member Functions inherited from llvm::GlobalIndirectSymbol
GlobalIndirectSymbol (Type *Ty, ValueTy VTy, unsigned AddressSpace, LinkageTypes Linkage, const Twine &Name, Constant *Symbol)
Protected Member Functions inherited from llvm::GlobalValue
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
void setParent (Module *parent)
~GlobalValue ()
void copyAttributesFrom (const GlobalValue *Src)
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< GlobalAlias, Options... >::type >
ilist_node_impl ()=default
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::GlobalValue
Type * ValueType
unsigned Linkage: 4
unsigned Visibility: 2
unsigned UnnamedAddrVal: 2
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
unsigned HasLLVMReservedName: 1
True if the function's name starts with "llvm.".
unsigned IsDSOLocal: 1
If true then there is a definition within the same linkage unit and that definition cannot be runtime preempted.
unsigned HasPartition: 1
True if this symbol has a partition name assigned (see https://lld.llvm.org/Partitions.html).
Intrinsic::ID IntID
The intrinsic ID for this subclass (which must be a Function).
Module * Parent
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes inherited from llvm::GlobalValue
static const unsigned GlobalValueSubClassDataBits = 16
Detailed Description
Definition at line 27 of file GlobalAlias.h.
Constructor & Destructor Documentation
GlobalAlias()
llvm::GlobalAlias::GlobalAlias (const GlobalAlias &) delete
Member Function Documentation
classof()
static bool llvm::GlobalAlias::classof (const Value * V) inline static
Definition at line 86 of file GlobalAlias.h.
References llvm::Value::getValueID().
create() [1/5]
GlobalAlias * GlobalAlias::create (Type * Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine & Name, Constant * Aliasee, Module * Parent) static
If a parent module is specified, the alias is automatically inserted into the end of the specified module's alias list.
Definition at line 485 of file Globals.cpp.
Referenced by AddCalls(), canCreateAliasFor(), canRenameComdat(), llvm::orc::cloneGlobalAliasDecl(), llvm::CloneModule(), createMaskedBitTest(), forceRenaming(), instrumentMaskedLoadOrStore(), isKnownTypeIdMember(), LLVMAddAlias(), maybeSetDSOLocal(), RetagMask(), and selectJumpTableArmEncoding().
create() [2/5]
GlobalAlias * GlobalAlias::create (Type * Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine & Name, Module * Parent) static
Definition at line 491 of file Globals.cpp.
create() [3/5]
GlobalAlias * GlobalAlias::create (Type * Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine & Name, GlobalValue * Aliasee) static
Definition at line 497 of file Globals.cpp.
References llvm::GlobalValue::getParent().
create() [4/5]
GlobalAlias * GlobalAlias::create (LinkageTypes Linkage, const Twine & Name, GlobalValue * Aliasee) static
Definition at line 503 of file Globals.cpp.
References llvm::PointerType::getAddressSpace(), llvm::PointerType::getElementType(), llvm::GlobalValue::getType(), llvm::codeview::Link, and Name.
create() [5/5]
GlobalAlias * GlobalAlias::create (const Twine & Name, GlobalValue * Aliasee) static
Definition at line 510 of file Globals.cpp.
References llvm::GlobalValue::getLinkage(), and Name.
eraseFromParent()
void GlobalAlias::eraseFromParent ()
eraseFromParent - This method unlinks 'this' from the containing module and deletes it.
Definition at line 518 of file Globals.cpp.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::Module::getAliasList(), and llvm::GlobalValue::getParent().
Referenced by INITIALIZE_PASS().
getAliasee() [1/2]
const Constant* llvm::GlobalAlias::getAliasee () const inline
Definition at line 73 of file GlobalAlias.h.
References llvm::GlobalIndirectSymbol::getIndirectSymbol().
Referenced by llvm::orc::cloneGlobalAliasDecl(), forEachUser(), hasUsesToReplace(), OptimizeGlobalAliases(), and llvm::ObjectSizeOffsetVisitor::visitGlobalAlias().
getAliasee() [2/2]
Constant* llvm::GlobalAlias::getAliasee () inline
Definition at line 76 of file GlobalAlias.h.
References llvm::GlobalIndirectSymbol::getIndirectSymbol().
isValidLinkage()
static bool llvm::GlobalAlias::isValidLinkage (LinkageTypes L) inline static
Definition at line 80 of file GlobalAlias.h.
References llvm::GlobalValue::isExternalLinkage(), llvm::GlobalValue::isLinkOnceLinkage(), llvm::GlobalValue::isLocalLinkage(), and llvm::GlobalValue::isWeakLinkage().
Referenced by forEachUser(), and maybeSetDSOLocal().
operator=()
GlobalAlias& llvm::GlobalAlias::operator= (const GlobalAlias &) delete
removeFromParent()
void GlobalAlias::removeFromParent ()
removeFromParent - This method unlinks 'this' from the containing module, but does not delete it.
Definition at line 514 of file Globals.cpp.
References llvm::Module::getAliasList(), llvm::GlobalValue::getParent(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
setAliasee()
void GlobalAlias::setAliasee (Constant * Aliasee)
These methods retrieve and set alias target.
Definition at line 522 of file Globals.cpp.
References assert(), llvm::Module::getIFuncList(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::GlobalIndirectSymbol::GlobalIndirectSymbol(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), and llvm::GlobalIndirectSymbol::setIndirectSymbol().
Referenced by llvm::CloneModule().
Friends And Related Function Documentation
SymbolTableListTraits< GlobalAlias >
friend class SymbolTableListTraits< GlobalAlias > friend
Definition at line 29 of file GlobalAlias.h.
The documentation for this class was generated from the following files:
include/llvm/IR/GlobalAlias.h
lib/IR/Globals.cpp