LLVM: llvm::cflaa::CFLGraph Class Reference
llvm::cflaa::CFLGraph Class Reference
The Program Expression Graph (PEG) of CFL analysis CFLGraph is auxiliary data structure used by CFL-based alias analysis to describe flow-insensitive pointer-related behaviors.
#include "Analysis/CFLGraph.h"
Classes
struct Edge
struct NodeInfo
class ValueInfo
Public Types
using Node = InstantiatedValue
using EdgeList = std::vector< Edge >
using const_value_iterator = ValueMap::const_iterator
Public Member Functions
bool addNode (Node N, AliasAttrs Attr=AliasAttrs())
void addAttr (Node N, AliasAttrs Attr)
void addEdge (Node From, Node To, int64_t Offset=0)
const NodeInfo * getNode (Node N) const
AliasAttrs attrFor (Node N) const
iterator_range< const_value_iterator > value_mappings () const
Detailed Description
The Program Expression Graph (PEG) of CFL analysis CFLGraph is auxiliary data structure used by CFL-based alias analysis to describe flow-insensitive pointer-related behaviors.
Given an LLVM function, the main purpose of this graph is to abstract away unrelated facts and translate the rest into a form that can be easily digested by CFL analyses. Each Node in the graph is an InstantiatedValue, and each edge represent a pointer assignment between InstantiatedValue. Pointer references/dereferences are not explicitly stored in the graph: we implicitly assume that for each node (X, I) it has a dereference edge to (X, I+1) and a reference edge to (X, I-1).
Definition at line 57 of file CFLGraph.h.
Member Typedef Documentation
const_value_iterator
using llvm::cflaa::CFLGraph::const_value_iterator = ValueMap::const_iterator
Definition at line 110 of file CFLGraph.h.
EdgeList
using llvm::cflaa::CFLGraph::EdgeList = std::vector<Edge>
Definition at line 66 of file CFLGraph.h.
Node
using llvm::cflaa::CFLGraph::Node = InstantiatedValue
Definition at line 59 of file CFLGraph.h.
Member Function Documentation
addAttr()
void llvm::cflaa::CFLGraph::addAttr (Node N, AliasAttrs Attr) inline
Definition at line 120 of file CFLGraph.h.
References assert(), and Info.
addEdge()
void llvm::cflaa::CFLGraph::addEdge (Node From, Node To, int64_t Offset = 0) inline
Definition at line 126 of file CFLGraph.h.
References assert(), From, and llvm::cflaa::CFLGraph::Edge::Offset.
addNode()
bool llvm::cflaa::CFLGraph::addNode (Node N, AliasAttrs Attr = AliasAttrs()) inline
Definition at line 112 of file CFLGraph.h.
References assert(), llvm::cflaa::InstantiatedValue::DerefLevel, and llvm::cflaa::InstantiatedValue::Val.
attrFor()
AliasAttrs llvm::cflaa::CFLGraph::attrFor (Node N) const inline
Definition at line 143 of file CFLGraph.h.
References assert(), and Info.
getNode()
const NodeInfo* llvm::cflaa::CFLGraph::getNode (Node N) const inline
Definition at line 136 of file CFLGraph.h.
References llvm::cflaa::InstantiatedValue::DerefLevel, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::cflaa::InstantiatedValue::Val.
value_mappings()
iterator_range<const_value_iterator> llvm::cflaa::CFLGraph::value_mappings () const inline
Definition at line 149 of file CFLGraph.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
Referenced by buildAttrMap(), and initializeWorkList().
The documentation for this class was generated from the following file:
lib/Analysis/CFLGraph.h