LLVM: llvm::pdb::NativeEnumModules Class Reference
llvm::pdb::NativeEnumModules Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeEnumModules.h"
Public Member Functions
NativeEnumModules (NativeSession &Session, uint32_t Index=0)
uint32_t getChildCount () const override
std::unique_ptr< PDBSymbol > getChildAtIndex (uint32_t Index) const override
std::unique_ptr< PDBSymbol > getNext () override
void reset () override
Public Member Functions inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
virtual ~IPDBEnumChildren ()=default
Additional Inherited Members
Public Types inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
using ChildTypePtr = std::unique_ptr< PDBSymbol >
using MyType = IPDBEnumChildren< PDBSymbol >
Detailed Description
Definition at line 19 of file NativeEnumModules.h.
Constructor & Destructor Documentation
NativeEnumModules()
llvm::pdb::NativeEnumModules::NativeEnumModules (NativeSession & Session, uint32_t Index = 0)
Definition at line 22 of file NativeEnumModules.cpp.
Member Function Documentation
getChildAtIndex()
std::unique_ptr< PDBSymbol > llvm::pdb::NativeEnumModules::getChildAtIndex (uint32_t Index) const override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 30 of file NativeEnumModules.cpp.
References llvm::pdb::SymbolCache::getOrCreateCompiland(), and llvm::pdb::NativeSession::getSymbolCache().
Referenced by getNext().
getChildCount()
uint32_t llvm::pdb::NativeEnumModules::getChildCount () const override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 25 of file NativeEnumModules.cpp.
References llvm::pdb::SymbolCache::getNumCompilands(), and llvm::pdb::NativeSession::getSymbolCache().
Referenced by getNext().
getNext()
std::unique_ptr< PDBSymbol > llvm::pdb::NativeEnumModules::getNext () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 34 of file NativeEnumModules.cpp.
References getChildAtIndex(), and getChildCount().
reset()
void llvm::pdb::NativeEnumModules::reset () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 40 of file NativeEnumModules.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeEnumModules.h
lib/DebugInfo/PDB/Native/NativeEnumModules.cpp