LLVM: llvm::SUnitIterator Class Reference
llvm::SUnitIterator Class Reference
#include "llvm/CodeGen/ScheduleDAG.h"
Public Member Functions
bool operator== (const SUnitIterator &x) const
bool operator!= (const SUnitIterator &x) const
pointer operator* () const
pointer operator-> () const
SUnitIterator & operator++ ()
SUnitIterator operator++ (int)
unsigned getOperand () const
const SUnit * getNode () const
bool isCtrlDep () const
Tests if this is not an SDep::Data dependence.
bool isArtificialDep () const
const SDep & getSDep () const
Static Public Member Functions
static SUnitIterator begin (SUnit *N)
static SUnitIterator end (SUnit *N)
Detailed Description
Definition at line 617 of file ScheduleDAG.h.
Member Function Documentation
begin()
static SUnitIterator llvm::SUnitIterator::begin (SUnit * N) inline static
Definition at line 643 of file ScheduleDAG.h.
Referenced by llvm::GraphTraits< SUnit * >::child_begin().
end()
static SUnitIterator llvm::SUnitIterator::end (SUnit * N) inline static
Definition at line 644 of file ScheduleDAG.h.
References llvm::SUnit::Preds.
Referenced by llvm::GraphTraits< SUnit * >::child_end().
getNode()
const SUnit* llvm::SUnitIterator::getNode () const inline
Definition at line 649 of file ScheduleDAG.h.
getOperand()
unsigned llvm::SUnitIterator::getOperand () const inline
Definition at line 648 of file ScheduleDAG.h.
getSDep()
const SDep& llvm::SUnitIterator::getSDep () const inline
Definition at line 658 of file ScheduleDAG.h.
References llvm::SUnit::Preds.
isArtificialDep()
bool llvm::SUnitIterator::isArtificialDep () const inline
Definition at line 655 of file ScheduleDAG.h.
isCtrlDep()
bool llvm::SUnitIterator::isCtrlDep () const inline
Tests if this is not an SDep::Data dependence.
Definition at line 652 of file ScheduleDAG.h.
operator!=()
bool llvm::SUnitIterator::operator!= (const SUnitIterator & x) const inline
Definition at line 628 of file ScheduleDAG.h.
References llvm::SDep::operator==().
operator*()
pointer llvm::SUnitIterator::operator* () const inline
Definition at line 630 of file ScheduleDAG.h.
References llvm::SUnit::Preds.
operator++() [1/2]
SUnitIterator& llvm::SUnitIterator::operator++ () inline
Definition at line 635 of file ScheduleDAG.h.
operator++() [2/2]
SUnitIterator llvm::SUnitIterator::operator++ (int) inline
Definition at line 639 of file ScheduleDAG.h.
operator->()
pointer llvm::SUnitIterator::operator-> () const inline
Definition at line 633 of file ScheduleDAG.h.
References llvm::operator*().
operator==()
bool llvm::SUnitIterator::operator== (const SUnitIterator & x) const inline
Definition at line 625 of file ScheduleDAG.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/ScheduleDAG.h