LLVM: llvm::orc::IRTransformLayer Class Reference
llvm::orc::IRTransformLayer Class Reference
A layer that applies a transform to emitted modules.
#include "llvm/ExecutionEngine/Orc/IRTransformLayer.h"
Public Types
using TransformFunction = std::function< Expected< ThreadSafeModule >(ThreadSafeModule, const MaterializationResponsibility &R)>
Public Member Functions
IRTransformLayer (ExecutionSession &ES, IRLayer &BaseLayer, TransformFunction Transform=identityTransform)
void setTransform (TransformFunction Transform)
void emit (MaterializationResponsibility R, ThreadSafeModule TSM) override
Emit should materialize the given IR.
Public Member Functions inherited from llvm::orc::IRLayer
IRLayer (ExecutionSession &ES, const IRMaterializationUnit::ManglingOptions *&MO)
virtual ~IRLayer ()
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this layer.
const IRMaterializationUnit::ManglingOptions *& getManglingOptions () const
Get the mangling options for this layer.
void setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit)
Sets the CloneToNewContextOnEmit flag (false by default).
bool getCloneToNewContextOnEmit () const
Returns the current value of the CloneToNewContextOnEmit flag.
virtual Error add (JITDylib &JD, ThreadSafeModule TSM, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Static Public Member Functions
static ThreadSafeModule identityTransform (ThreadSafeModule TSM, const MaterializationResponsibility &R)
Detailed Description
A layer that applies a transform to emitted modules.
The transform function is responsible for locking the ThreadSafeContext before operating on the module.
Definition at line 28 of file IRTransformLayer.h.
Member Typedef Documentation
TransformFunction
using llvm::orc::IRTransformLayer::TransformFunction = std::function<Expected<ThreadSafeModule>(ThreadSafeModule, const MaterializationResponsibility &R)>
Definition at line 31 of file IRTransformLayer.h.
Constructor & Destructor Documentation
IRTransformLayer()
llvm::orc::IRTransformLayer::IRTransformLayer (ExecutionSession & ES, IRLayer & BaseLayer, TransformFunction Transform = identityTransform)
Definition at line 15 of file IRTransformLayer.cpp.
Member Function Documentation
emit()
void llvm::orc::IRTransformLayer::emit (MaterializationResponsibility R, ThreadSafeModule TSM) override virtual
Emit should materialize the given IR.
Implements llvm::orc::IRLayer.
Definition at line 20 of file IRTransformLayer.cpp.
References assert(), llvm::orc::IRLayer::emit(), llvm::orc::MaterializationResponsibility::failMaterialization(), llvm::orc::IRLayer::getExecutionSession(), and llvm::orc::ExecutionSession::reportError().
Referenced by setTransform().
identityTransform()
static ThreadSafeModule llvm::orc::IRTransformLayer::identityTransform (ThreadSafeModule TSM, const MaterializationResponsibility & R) inline static
Definition at line 43 of file IRTransformLayer.h.
setTransform()
void llvm::orc::IRTransformLayer::setTransform (TransformFunction Transform) inline
Definition at line 36 of file IRTransformLayer.h.
References emit().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IRTransformLayer.h
lib/ExecutionEngine/Orc/IRTransformLayer.cpp