LLVM: llvm::LICMPass Class Reference
llvm::LICMPass Class Reference
Performs Loop Invariant Code Motion Pass.
#include "llvm/Transforms/Scalar/LICM.h"
Public Member Functions
LICMPass ()
LICMPass (unsigned LicmMssaOptCap, unsigned LicmMssaNoAccForPromotionCap)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LICMPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Performs Loop Invariant Code Motion Pass.
Definition at line 46 of file LICM.h.
Constructor & Destructor Documentation
LICMPass() [1/2]
llvm::LICMPass::LICMPass () inline
Definition at line 51 of file LICM.h.
LICMPass() [2/2]
llvm::LICMPass::LICMPass (unsigned LicmMssaOptCap, unsigned LicmMssaNoAccForPromotionCap) inline
Definition at line 54 of file LICM.h.
References run().
Member Function Documentation
run()
PreservedAnalyses LICMPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 279 of file LICM.cpp.
References llvm::LoopStandardAnalysisResults::AA, llvm::PreservedAnalyses::all(), llvm::LoopStandardAnalysisResults::DT, F(), llvm::getLoopPassPreservedAnalyses(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::LoopStandardAnalysisResults::LI, LICM, llvm::LoopStandardAnalysisResults::MSSA, llvm::report_fatal_error(), llvm::LoopStandardAnalysisResults::SE, llvm::LoopStandardAnalysisResults::TLI, and llvm::LoopStandardAnalysisResults::TTI.
Referenced by LICMPass().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LICM.h
lib/Transforms/Scalar/LICM.cpp