LLVM: llvm::Mips16RegisterInfo Class Reference
llvm::Mips16RegisterInfo Class Reference
#include "Target/Mips/Mips16RegisterInfo.h"
Public Member Functions
Mips16RegisterInfo ()
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool useFPForScavengingIndex (const MachineFunction &MF) const override
bool saveScavengerRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator &UseMI, const TargetRegisterClass *RC, unsigned Reg) const override
const TargetRegisterClass * intRegClass (unsigned Size) const override
Return GPR register class.
Public Member Functions inherited from llvm::MipsRegisterInfo
MipsRegisterInfo ()
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind) const override
Code Generation virtual methods...
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Mips Callee Saved Registers.
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Stack Frame Processing Methods.
bool canRealignStack (const MachineFunction &MF) const override
Register getFrameRegister (const MachineFunction &MF) const override
Debug information queries.
Additional Inherited Members
Public Types inherited from llvm::MipsRegisterInfo
enum MipsPtrClass { MipsPtrClass::Default = 0, MipsPtrClass::GPR16MM = 1, MipsPtrClass::StackPointer = 2, MipsPtrClass::GlobalPointer = 3 }
Static Public Member Functions inherited from llvm::MipsRegisterInfo
static unsigned getPICCallReg ()
Get PIC indirect call register.
static const uint32_t * getMips16RetHelperMask ()
Detailed Description
Definition at line 21 of file Mips16RegisterInfo.h.
Constructor & Destructor Documentation
Mips16RegisterInfo()
Mips16RegisterInfo::Mips16RegisterInfo ()
Definition at line 40 of file Mips16RegisterInfo.cpp.
References requiresRegisterScavenging().
Member Function Documentation
intRegClass()
const TargetRegisterClass * Mips16RegisterInfo::intRegClass (unsigned Size) const override virtual
Return GPR register class.
Implements llvm::MipsRegisterInfo.
Definition at line 70 of file Mips16RegisterInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::errs(), llvm::ISD::FrameIndex, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isReg(), LLVM_DEBUG, llvm::Mips16InstrInfo::loadImmediate(), MI, TII, and llvm::Mips16InstrInfo::validImmediate().
requiresFrameIndexScavenging()
bool Mips16RegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const override
Definition at line 47 of file Mips16RegisterInfo.cpp.
References useFPForScavengingIndex().
Referenced by requiresRegisterScavenging().
requiresRegisterScavenging()
bool Mips16RegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const override
Definition at line 43 of file Mips16RegisterInfo.cpp.
References requiresFrameIndexScavenging().
Referenced by Mips16RegisterInfo().
saveScavengerRegister()
bool Mips16RegisterInfo::saveScavengerRegister (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator & UseMI, const TargetRegisterClass * RC, unsigned Reg) const override
Definition at line 57 of file Mips16RegisterInfo.cpp.
References llvm::TargetInstrInfo::copyPhysReg(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), and TII.
Referenced by useFPForScavengingIndex().
useFPForScavengingIndex()
bool Mips16RegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const override
Definition at line 52 of file Mips16RegisterInfo.cpp.
References saveScavengerRegister().
Referenced by requiresFrameIndexScavenging().
The documentation for this class was generated from the following files:
lib/Target/Mips/Mips16RegisterInfo.h
lib/Target/Mips/Mips16RegisterInfo.cpp