LLVM: llvm::AMDGPUInstrInfo Class Reference
llvm::AMDGPUInstrInfo Class Reference
#include "Target/AMDGPU/AMDGPUInstrInfo.h"
Public Member Functions
AMDGPUInstrInfo (const GCNSubtarget &st)
Static Public Member Functions
static bool isUniformMMO (const MachineMemOperand *MMO)
Detailed Description
Definition at line 29 of file AMDGPUInstrInfo.h.
Constructor & Destructor Documentation
AMDGPUInstrInfo()
AMDGPUInstrInfo::AMDGPUInstrInfo (const GCNSubtarget & st) explicit
Definition at line 28 of file AMDGPUInstrInfo.cpp.
Member Function Documentation
isUniformMMO()
bool AMDGPUInstrInfo::isUniformMMO (const MachineMemOperand * MMO) static
Definition at line 32 of file AMDGPUInstrInfo.cpp.
References Arg, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::dyn_cast(), llvm::MachineMemOperand::getAddrSpace(), llvm::Instruction::getMetadata(), llvm::MachineMemOperand::getValue(), I, and llvm::AMDGPU::isArgPassedInSGPR().
Referenced by llvm::SITargetLowering::isMemOpUniform(), isScalarLoadLegal(), and llvm::AMDGPUTargetLowering::shouldReduceLoadWidth().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUInstrInfo.h
lib/Target/AMDGPU/AMDGPUInstrInfo.cpp