LLVM: llvm::DICompileUnit Class Reference
llvm::DICompileUnit Class Reference
Compile unit.
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
enum DebugEmissionKind : unsigned {
NoDebug = 0, FullDebug, LineTablesOnly, DebugDirectivesOnly,
LastEmissionKind = DebugDirectivesOnly
}
enum DebugNameTableKind : unsigned { DebugNameTableKind::Default = 0, DebugNameTableKind::GNU = 1, DebugNameTableKind::None = 2, DebugNameTableKind::LastDebugNameTableKind = None }
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic, FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
DEFINE_MDNODE_GET_DISTINCT_TEMPORARY (DICompileUnit,(unsigned SourceLanguage, DIFile *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, DebugEmissionKind EmissionKind, DICompositeTypeArray EnumTypes, DIScopeArray RetainedTypes, DIGlobalVariableExpressionArray GlobalVariables, DIImportedEntityArray ImportedEntities, DIMacroNodeArray Macros, uint64_t DWOId, bool SplitDebugInlining, bool DebugInfoForProfiling, DebugNameTableKind NameTableKind, bool RangesBaseAddress),(SourceLanguage, File, Producer, IsOptimized, Flags, RuntimeVersion, SplitDebugFilename, EmissionKind, EnumTypes, RetainedTypes, GlobalVariables, ImportedEntities, Macros, DWOId, SplitDebugInlining, DebugInfoForProfiling,(unsigned) NameTableKind, RangesBaseAddress)) DEFINE_MDNODE_GET_DISTINCT_TEMPORARY(DICompileUnit
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool RangesBaseAddress TempDICompileUnit clone () const
unsigned getSourceLanguage () const
bool isOptimized () const
unsigned getRuntimeVersion () const
DebugEmissionKind getEmissionKind () const
bool isDebugDirectivesOnly () const
bool getDebugInfoForProfiling () const
DebugNameTableKind getNameTableKind () const
bool getRangesBaseAddress () const
StringRef getProducer () const
StringRef getFlags () const
StringRef getSplitDebugFilename () const
DICompositeTypeArray getEnumTypes () const
DIScopeArray getRetainedTypes () const
DIGlobalVariableExpressionArray getGlobalVariables () const
DIImportedEntityArray getImportedEntities () const
DIMacroNodeArray getMacros () const
uint64_t getDWOId () const
void setDWOId (uint64_t DwoId)
bool getSplitDebugInlining () const
void setSplitDebugInlining (bool SplitDebugInlining)
MDString * getRawProducer () const
MDString * getRawFlags () const
MDString * getRawSplitDebugFilename () const
Metadata * getRawEnumTypes () const
Metadata * getRawRetainedTypes () const
Metadata * getRawGlobalVariables () const
Metadata * getRawImportedEntities () const
Metadata * getRawMacros () const
void replaceEnumTypes (DICompositeTypeArray N)
Replace arrays.
void replaceRetainedTypes (DITypeArray N)
void replaceGlobalVariables (DIGlobalVariableExpressionArray N)
void replaceImportedEntities (DIImportedEntityArray N)
void replaceMacros (DIMacroNodeArray N)
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
Optional< StringRef > getSource () const
StringRef getName () const
DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
unsigned getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static Optional< DebugEmissionKind > getEmissionKind (StringRef Str)
static const char * emissionKindString (DebugEmissionKind EK)
static Optional< DebugNameTableKind > getNameTableKind (StringRef Str)
static const char * nameTableKindString (DebugNameTableKind PK)
static void get ()=delete
static void getIfExists ()=delete
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
unsigned Metadata * File
unsigned Metadata MDString * Producer
unsigned Metadata MDString bool IsOptimized
unsigned Metadata MDString bool MDString * Flags
unsigned Metadata MDString bool MDString unsigned RuntimeVersion
unsigned Metadata MDString bool MDString unsigned MDString * SplitDebugFilename
unsigned Metadata MDString bool MDString unsigned MDString unsigned EmissionKind
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata * EnumTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata * RetainedTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata * GlobalVariables
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata * ImportedEntities
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata * Macros
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t DWOId
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool SplitDebugInlining
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool DebugInfoForProfiling
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned NameTableKind
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool RangesBaseAddress
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool SourceLanguage
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool File
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool Producer
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool IsOptimized
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool Flags
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool RuntimeVersion
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool SplitDebugFilename
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool EmissionKind
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool EnumTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool RetainedTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool GlobalVariables
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool ImportedEntities
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool Macros
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool DWOId
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool SplitDebugInlining
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool DebugInfoForProfiling
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool NameTableKind
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata *> Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata *> Ops1, ArrayRef< Metadata *> Ops2=None)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata *> Ops1, ArrayRef< Metadata *> Ops2=None)
~MDNode ()=default
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Compile unit.
Definition at line 1115 of file DebugInfoMetadata.h.
Member Enumeration Documentation
DebugEmissionKind
enum llvm::DICompileUnit::DebugEmissionKind : unsigned
Enumerator
NoDebug
FullDebug
LineTablesOnly
DebugDirectivesOnly
LastEmissionKind
Definition at line 1120 of file DebugInfoMetadata.h.
DebugNameTableKind
enum llvm::DICompileUnit::DebugNameTableKind : unsigned strong
Enumerator
Default
GNU
None
LastDebugNameTableKind
Definition at line 1128 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DICompileUnit::classof (const Metadata * MD) inline static
Definition at line 1315 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool RangesBaseAddress TempDICompileUnit llvm::DICompileUnit::clone () const inline
Definition at line 1238 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET_DISTINCT_TEMPORARY()
llvm::DICompileUnit::DEFINE_MDNODE_GET_DISTINCT_TEMPORARY (DICompileUnit , (unsigned SourceLanguage, DIFile *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, DebugEmissionKind EmissionKind, DICompositeTypeArray EnumTypes, DIScopeArray RetainedTypes, DIGlobalVariableExpressionArray GlobalVariables, DIImportedEntityArray ImportedEntities, DIMacroNodeArray Macros, uint64_t DWOId, bool SplitDebugInlining, bool DebugInfoForProfiling, DebugNameTableKind NameTableKind, bool RangesBaseAddress) , (SourceLanguage, File, Producer, IsOptimized, Flags, RuntimeVersion, SplitDebugFilename, EmissionKind, EnumTypes, RetainedTypes, GlobalVariables, ImportedEntities, Macros, DWOId, SplitDebugInlining, DebugInfoForProfiling,(unsigned) NameTableKind, RangesBaseAddress))
emissionKindString()
const char * DICompileUnit::emissionKindString (DebugEmissionKind EK) static
Definition at line 561 of file DebugInfoMetadata.cpp.
get()
static void llvm::DICompileUnit::get () static delete
Referenced by llvm::DISubprogram::toSPFlags().
getDebugInfoForProfiling()
bool llvm::DICompileUnit::getDebugInfoForProfiling () const inline
Definition at line 1249 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::applySubprogramAttributes(), rotateSign(), and llvm::StripDebugInfo().
getDWOId()
uint64_t llvm::DICompileUnit::getDWOId () const inline
Definition at line 1276 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), rotateSign(), shouldKeepInEntry(), and llvm::StripDebugInfo().
getEmissionKind() [1/2]
Optional< DICompileUnit::DebugEmissionKind > DICompileUnit::getEmissionKind (StringRef Str) static
Definition at line 543 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and llvm::None.
Referenced by hasConflictingReferenceFlags(), llvm::DwarfCompileUnit::includeMinimalInlineScopes(), and rotateSign().
getEmissionKind() [2/2]
DebugEmissionKind llvm::DICompileUnit::getEmissionKind () const inline
Definition at line 1243 of file DebugInfoMetadata.h.
References llvm::lltok::EmissionKind.
Referenced by FunctionNumber().
getEnumTypes()
DICompositeTypeArray llvm::DICompileUnit::getEnumTypes () const inline
Definition at line 1261 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags(), llvm::DebugInfoFinder::processModule(), and rotateSign().
getFlags()
StringRef llvm::DICompileUnit::getFlags () const inline
Definition at line 1257 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), and llvm::StripDebugInfo().
getGlobalVariables()
DIGlobalVariableExpressionArray llvm::DICompileUnit::getGlobalVariables () const inline
Definition at line 1267 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags(), llvm::DebugInfoFinder::processModule(), and rotateSign().
getIfExists()
static void llvm::DICompileUnit::getIfExists () static delete
getImportedEntities()
DIImportedEntityArray llvm::DICompileUnit::getImportedEntities () const inline
Definition at line 1270 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), hasConflictingReferenceFlags(), llvm::DebugInfoFinder::processModule(), and rotateSign().
getMacros()
DIMacroNodeArray llvm::DICompileUnit::getMacros () const inline
Definition at line 1273 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags(), rotateSign(), and llvm::StripDebugInfo().
getNameTableKind() [1/2]
Optional< DICompileUnit::DebugNameTableKind > DICompileUnit::getNameTableKind (StringRef Str) static
Definition at line 553 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::Default, llvm::GNU, and llvm::None.
Referenced by llvm::DwarfDebug::addSubprogramNames(), computeIndexValue(), llvm::DwarfDebug::enterNonTypeUnitContext(), llvm::DwarfCompileUnit::hasDwarfPubSections(), rotateSign(), and llvm::StripDebugInfo().
getNameTableKind() [2/2]
DebugNameTableKind llvm::DICompileUnit::getNameTableKind () const inline
Definition at line 1250 of file DebugInfoMetadata.h.
References llvm::lltok::NameTableKind.
Referenced by FunctionNumber().
getProducer()
StringRef llvm::DICompileUnit::getProducer () const inline
Definition at line 1255 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), and llvm::StripDebugInfo().
getRangesBaseAddress()
bool llvm::DICompileUnit::getRangesBaseAddress () const inline
Definition at line 1253 of file DebugInfoMetadata.h.
Referenced by emitRangeList(), and llvm::StripDebugInfo().
getRawEnumTypes()
Metadata* llvm::DICompileUnit::getRawEnumTypes () const inline
Definition at line 1288 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags().
getRawFlags()
MDString* llvm::DICompileUnit::getRawFlags () const inline
Definition at line 1284 of file DebugInfoMetadata.h.
Referenced by rotateSign().
getRawGlobalVariables()
Metadata* llvm::DICompileUnit::getRawGlobalVariables () const inline
Definition at line 1290 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags().
getRawImportedEntities()
Metadata* llvm::DICompileUnit::getRawImportedEntities () const inline
Definition at line 1291 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags().
getRawMacros()
Metadata* llvm::DICompileUnit::getRawMacros () const inline
Definition at line 1292 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags().
getRawProducer()
MDString* llvm::DICompileUnit::getRawProducer () const inline
Definition at line 1283 of file DebugInfoMetadata.h.
Referenced by rotateSign().
getRawRetainedTypes()
Metadata* llvm::DICompileUnit::getRawRetainedTypes () const inline
Definition at line 1289 of file DebugInfoMetadata.h.
Referenced by hasConflictingReferenceFlags().
getRawSplitDebugFilename()
MDString* llvm::DICompileUnit::getRawSplitDebugFilename () const inline
Definition at line 1285 of file DebugInfoMetadata.h.
Referenced by rotateSign().
getRetainedTypes()
DIScopeArray llvm::DICompileUnit::getRetainedTypes () const inline
Definition at line 1264 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), hasConflictingReferenceFlags(), llvm::DebugInfoFinder::processModule(), and rotateSign().
getRuntimeVersion()
unsigned llvm::DICompileUnit::getRuntimeVersion () const inline
Definition at line 1242 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), rotateSign(), and llvm::StripDebugInfo().
getSourceLanguage()
unsigned llvm::DICompileUnit::getSourceLanguage () const inline
Definition at line 1240 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), llvm::DwarfUnit::getLanguage(), rotateSign(), and llvm::StripDebugInfo().
getSplitDebugFilename()
StringRef llvm::DICompileUnit::getSplitDebugFilename () const inline
Definition at line 1259 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), and llvm::StripDebugInfo().
getSplitDebugInlining()
bool llvm::DICompileUnit::getSplitDebugInlining () const inline
Definition at line 1278 of file DebugInfoMetadata.h.
Referenced by forBothCUs(), rotateSign(), and llvm::StripDebugInfo().
isDebugDirectivesOnly()
bool llvm::DICompileUnit::isDebugDirectivesOnly () const inline
Definition at line 1246 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::addString(), llvm::DwarfDebug::beginModule(), llvm::DwarfFile::emitUnit(), llvm::DwarfCompileUnit::hasDwarfPubSections(), and llvm::DwarfCompileUnit::initStmtList().
isOptimized()
bool llvm::DICompileUnit::isOptimized () const inline
Definition at line 1241 of file DebugInfoMetadata.h.
Referenced by collectCallSiteParameters(), rotateSign(), and llvm::StripDebugInfo().
nameTableKindString()
const char * DICompileUnit::nameTableKindString (DebugNameTableKind PK) static
Definition at line 571 of file DebugInfoMetadata.cpp.
References llvm::Default, llvm::GNU, and llvm::None.
replaceEnumTypes()
void llvm::DICompileUnit::replaceEnumTypes (DICompositeTypeArray N) inline
Replace arrays.
If this isUniqued() and not isResolved(), it will be RAUW'ed and deleted on a uniquing collision. In practice, uniquing collisions on DICompileUnit should be fairly rare.
Definition at line 1300 of file DebugInfoMetadata.h.
Referenced by llvm::DIBuilder::finalize().
replaceGlobalVariables()
void llvm::DICompileUnit::replaceGlobalVariables (DIGlobalVariableExpressionArray N) inline
Definition at line 1306 of file DebugInfoMetadata.h.
Referenced by llvm::DIBuilder::finalize().
replaceImportedEntities()
void llvm::DICompileUnit::replaceImportedEntities (DIImportedEntityArray N) inline
Definition at line 1309 of file DebugInfoMetadata.h.
Referenced by llvm::DIBuilder::finalize().
replaceMacros()
void llvm::DICompileUnit::replaceMacros (DIMacroNodeArray N) inline
Definition at line 1312 of file DebugInfoMetadata.h.
Referenced by llvm::DIBuilder::finalize().
replaceRetainedTypes()
void llvm::DICompileUnit::replaceRetainedTypes (DITypeArray N) inline
Definition at line 1303 of file DebugInfoMetadata.h.
Referenced by llvm::DIBuilder::finalize().
setDWOId()
void llvm::DICompileUnit::setDWOId (uint64_t DwoId) inline
Definition at line 1277 of file DebugInfoMetadata.h.
setSplitDebugInlining()
void llvm::DICompileUnit::setSplitDebugInlining (bool SplitDebugInlining) inline
Definition at line 1279 of file DebugInfoMetadata.h.
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1116 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 1117 of file DebugInfoMetadata.h.
Member Data Documentation
DebugInfoForProfiling [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool llvm::DICompileUnit::DebugInfoForProfiling
Definition at line 1226 of file DebugInfoMetadata.h.
DebugInfoForProfiling [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::DebugInfoForProfiling
Definition at line 1226 of file DebugInfoMetadata.h.
DWOId [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::DWOId
Definition at line 1226 of file DebugInfoMetadata.h.
DWOId [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::DWOId
Definition at line 1226 of file DebugInfoMetadata.h.
EmissionKind [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned llvm::DICompileUnit::EmissionKind
Definition at line 1226 of file DebugInfoMetadata.h.
EmissionKind [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::EmissionKind
Definition at line 1226 of file DebugInfoMetadata.h.
EnumTypes [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata* llvm::DICompileUnit::EnumTypes
Definition at line 1226 of file DebugInfoMetadata.h.
EnumTypes [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::EnumTypes
Definition at line 1226 of file DebugInfoMetadata.h.
File [1/2]
unsigned Metadata* llvm::DICompileUnit::File
Definition at line 1226 of file DebugInfoMetadata.h.
File [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::File
Definition at line 1226 of file DebugInfoMetadata.h.
Flags [1/2]
unsigned Metadata MDString bool MDString* llvm::DICompileUnit::Flags
Definition at line 1226 of file DebugInfoMetadata.h.
Flags [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::Flags
Definition at line 1226 of file DebugInfoMetadata.h.
GlobalVariables [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata* llvm::DICompileUnit::GlobalVariables
Definition at line 1226 of file DebugInfoMetadata.h.
GlobalVariables [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::GlobalVariables
Definition at line 1226 of file DebugInfoMetadata.h.
ImportedEntities [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata* llvm::DICompileUnit::ImportedEntities
Definition at line 1226 of file DebugInfoMetadata.h.
ImportedEntities [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::ImportedEntities
Definition at line 1226 of file DebugInfoMetadata.h.
IsOptimized [1/2]
unsigned Metadata MDString bool llvm::DICompileUnit::IsOptimized
Definition at line 1226 of file DebugInfoMetadata.h.
IsOptimized [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::IsOptimized
Definition at line 1226 of file DebugInfoMetadata.h.
Macros [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata* llvm::DICompileUnit::Macros
Definition at line 1226 of file DebugInfoMetadata.h.
Macros [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::Macros
Definition at line 1226 of file DebugInfoMetadata.h.
NameTableKind [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned llvm::DICompileUnit::NameTableKind
Definition at line 1226 of file DebugInfoMetadata.h.
NameTableKind [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::NameTableKind
Definition at line 1226 of file DebugInfoMetadata.h.
Producer [1/2]
unsigned Metadata MDString* llvm::DICompileUnit::Producer
Definition at line 1226 of file DebugInfoMetadata.h.
Producer [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::Producer
Definition at line 1226 of file DebugInfoMetadata.h.
RangesBaseAddress
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::RangesBaseAddress
Definition at line 1226 of file DebugInfoMetadata.h.
RetainedTypes [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata* llvm::DICompileUnit::RetainedTypes
Definition at line 1226 of file DebugInfoMetadata.h.
RetainedTypes [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::RetainedTypes
Definition at line 1226 of file DebugInfoMetadata.h.
RuntimeVersion [1/2]
unsigned Metadata MDString bool MDString unsigned llvm::DICompileUnit::RuntimeVersion
Definition at line 1226 of file DebugInfoMetadata.h.
RuntimeVersion [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::RuntimeVersion
Definition at line 1226 of file DebugInfoMetadata.h.
SourceLanguage
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::SourceLanguage
Definition at line 1226 of file DebugInfoMetadata.h.
SplitDebugFilename [1/2]
unsigned Metadata MDString bool MDString unsigned MDString* llvm::DICompileUnit::SplitDebugFilename
Definition at line 1226 of file DebugInfoMetadata.h.
SplitDebugFilename [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::SplitDebugFilename
Definition at line 1226 of file DebugInfoMetadata.h.
SplitDebugInlining [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool llvm::DICompileUnit::SplitDebugInlining
Definition at line 1226 of file DebugInfoMetadata.h.
SplitDebugInlining [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::SplitDebugInlining
Definition at line 1226 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp