LLVM: llvm::MCRegisterInfo::DiffListIterator Class Reference
llvm::MCRegisterInfo::DiffListIterator Class Reference
DiffListIterator - Base iterator class that can traverse the differentially encoded register and regunit lists in DiffLists.
#include "llvm/MC/MCRegisterInfo.h"
Public Member Functions
bool isValid () const
isValid - returns true if this iterator is not yet at the end.
MCRegister operator* () const
Dereference the iterator to get the value at the current position.
void operator++ ()
Pre-increment to move to the next position.
Protected Member Functions
DiffListIterator ()=default
Create an invalid iterator. Call init() to point to something useful.
void init (MCPhysReg InitVal, const MCPhysReg *DiffList)
init - Point the iterator to InitVal, decoding subsequent values from DiffList.
MCRegister advance ()
advance - Move to the next list position, return the applied differential.
Friends
template<class SubT >
class MCRegisterInfo::mc_difflist_iterator
Detailed Description
DiffListIterator - Base iterator class that can traverse the differentially encoded register and regunit lists in DiffLists.
Don't use this class directly, use one of the specialized sub-classes defined below.
Definition at line 189 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
DiffListIterator()
llvm::MCRegisterInfo::DiffListIterator::DiffListIterator () protected default
Create an invalid iterator. Call init() to point to something useful.
Member Function Documentation
advance()
MCRegister llvm::MCRegisterInfo::DiffListIterator::advance () inline protected
advance - Move to the next list position, return the applied differential.
This function does not detect the end of the list, that is the caller's responsibility (by checking for a 0 return value).
Definition at line 208 of file MCRegisterInfo.h.
References assert(), and D.
init()
void llvm::MCRegisterInfo::DiffListIterator::init (MCPhysReg InitVal, const MCPhysReg * DiffList) inline protected
init - Point the iterator to InitVal, decoding subsequent values from DiffList.
The iterator will initially point to InitVal, sub-classes are responsible for skipping the seed value if it is not part of the list.
Definition at line 200 of file MCRegisterInfo.h.
Referenced by llvm::MCRegisterInfo::mc_difflist_iterator< mc_subreg_iterator >::mc_difflist_iterator().
isValid()
bool llvm::MCRegisterInfo::DiffListIterator::isValid () const inline
isValid - returns true if this iterator is not yet at the end.
Definition at line 217 of file MCRegisterInfo.h.
References List.
Referenced by llvm::addLiveIns(), llvm::DwarfExpression::addMachineReg(), llvm::LivePhysRegs::addReg(), llvm::LiveRegUnits::addReg(), addRegUnits(), llvm::MCRegAliasIterator::advance(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::LiveRegUnits::available(), llvm::TargetRegisterInfo::checkAllSuperRegsMarked(), computeLiveOuts(), llvm::createBreakFalseDeps(), llvm::createGreedyRegisterAllocator(), llvm::createSIWholeQuadModePass(), CriticalPathStep(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::HexagonBlockRanges::expandToSubRegs(), llvm::finalizeBundle(), findHoistingInsertPosAndDeps(), llvm::SIRegisterInfo::findReachingDef(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foreachUnit(), llvm::RegScavenger::forward(), getDwarfRegNum(), getLiveLanesAt(), llvm::MCRegisterInfo::getMatchingSuperReg(), getMax32BitSubRegister(), getMOVL(), getNumAllocatableRegsForConstraints(), llvm::HexagonInstrInfo::getOperandLatency(), getPairedGPR(), llvm::MachineFrameInfo::getPristineRegs(), llvm::ReachingDefAnalysis::getReachingDef(), getRegUnits(), llvm::MCRegisterInfo::getSubReg(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::LiveVariables::HandleVirtRegDef(), hasPressureSet(), llvm::TargetRegisterInfo::hasRegUnit(), hasTiedDef(), INITIALIZE_PASS(), isACalleeSavedRegister(), isCallableFunction(), llvm::HexagonInstrInfo::isDependent(), isMinSize(), llvm::LiveRegMatrix::isPhysRegUsed(), llvm::MachineRegisterInfo::isReservedRegUnit(), llvm::MCSubRegIndexIterator::isValid(), llvm::MCRegUnitMaskIterator::isValid(), llvm::MCRegAliasIterator::isValid(), lowerRegToMasks(), llvm::rdf::RegisterAggr::makeRegRef(), llvm::TargetRegisterInfo::markSuperRegs(), llvm::MCRegAliasIterator::MCRegAliasIterator(), needsStackFrame(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::MCRegAliasIterator::operator*(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::LiveIntervals::print(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::TargetRegisterInfo::regsOverlap(), llvm::LiveIntervals::removeAllRegUnitsForPhysReg(), llvm::LiveRegUnits::removeReg(), llvm::rdf::Liveness::resetKills(), TrackDefUses(), llvm::LiveIntervals::HMEditor::updateAllRanges(), updateLiveIn(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), and UpdatePredRedefs().
operator*()
MCRegister llvm::MCRegisterInfo::DiffListIterator::operator* () const inline
Dereference the iterator to get the value at the current position.
Definition at line 220 of file MCRegisterInfo.h.
operator++()
void llvm::MCRegisterInfo::DiffListIterator::operator++ () inline
Pre-increment to move to the next position.
Definition at line 223 of file MCRegisterInfo.h.
Friends And Related Function Documentation
MCRegisterInfo::mc_difflist_iterator
template<class SubT > friend class MCRegisterInfo::mc_difflist_iterator friend
Definition at line 229 of file MCRegisterInfo.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCRegisterInfo.h