LLVM: llvm::BitcodeReaderValueList Class Reference
llvm::BitcodeReaderValueList Class Reference
#include "Bitcode/Reader/ValueList.h"
Public Member Functions
BitcodeReaderValueList (LLVMContext &C, size_t RefsUpperBound)
~BitcodeReaderValueList ()
unsigned size () const
void resize (unsigned N)
void push_back (Value *V, Type *Ty)
void clear ()
Value * operator[] (unsigned i) const
Value * back () const
void pop_back ()
bool empty () const
void shrinkTo (unsigned N)
Constant * getConstantFwdRef (unsigned Idx, Type *Ty)
Value * getValueFwdRef (unsigned Idx, Type *Ty, Type **FullTy=nullptr)
void assignValue (Value *V, unsigned Idx, Type *FullTy)
void resolveConstantForwardRefs ()
Once all constants are read, this method bulk resolves any forward references.
Detailed Description
Definition at line 28 of file ValueList.h.
Constructor & Destructor Documentation
BitcodeReaderValueList()
llvm::BitcodeReaderValueList::BitcodeReaderValueList (LLVMContext & C, size_t RefsUpperBound) inline
Definition at line 54 of file ValueList.h.
~BitcodeReaderValueList()
llvm::BitcodeReaderValueList::~BitcodeReaderValueList () inline
Definition at line 59 of file ValueList.h.
References assert().
Member Function Documentation
assignValue()
void BitcodeReaderValueList::assignValue (Value * V, unsigned Idx, Type * FullTy)
Definition at line 68 of file ValueList.cpp.
References assert(), llvm::Value::deleteValue(), and llvm::size().
Referenced by shrinkTo().
back()
Value* llvm::BitcodeReaderValueList::back () const inline
Definition at line 85 of file ValueList.h.
clear()
void llvm::BitcodeReaderValueList::clear () inline
Definition at line 74 of file ValueList.h.
References assert().
empty()
bool llvm::BitcodeReaderValueList::empty () const inline
Definition at line 90 of file ValueList.h.
getConstantFwdRef()
Constant * BitcodeReaderValueList::getConstantFwdRef (unsigned Idx, Type * Ty)
Definition at line 99 of file ValueList.cpp.
References C, Context, llvm::report_fatal_error(), and llvm::size().
Referenced by shrinkTo().
getValueFwdRef()
Value * BitcodeReaderValueList::getValueFwdRef (unsigned Idx, Type * Ty, Type ** FullTy = nullptr)
Definition at line 119 of file ValueList.cpp.
References llvm::size().
Referenced by shrinkTo().
operator[]()
Value* llvm::BitcodeReaderValueList::operator[] (unsigned i) const inline
Definition at line 80 of file ValueList.h.
References assert().
pop_back()
void llvm::BitcodeReaderValueList::pop_back () inline
Definition at line 86 of file ValueList.h.
push_back()
void llvm::BitcodeReaderValueList::push_back (Value * V, Type * Ty) inline
Definition at line 69 of file ValueList.h.
resize()
void llvm::BitcodeReaderValueList::resize (unsigned N) inline
Definition at line 65 of file ValueList.h.
resolveConstantForwardRefs()
void BitcodeReaderValueList::resolveConstantForwardRefs ()
Once all constants are read, this method bulk resolves any forward references.
The idea behind this is that we sometimes get constants (such as large arrays) which reference many forward ref constants. Replacing each of these causes a lot of thrashing when building/reuniquing the constant. Instead of doing this, we look at all the uses and rewrite all the place holders at once for any constant that uses a placeholder.
Definition at line 153 of file ValueList.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::Constant::destroyConstant(), E, llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), I, llvm::lower_bound(), llvm::User::op_begin(), llvm::User::op_end(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::sort(), and llvm::Value::user_begin().
Referenced by shrinkTo().
shrinkTo()
void llvm::BitcodeReaderValueList::shrinkTo (unsigned N) inline
Definition at line 92 of file ValueList.h.
References assert(), assignValue(), getConstantFwdRef(), getValueFwdRef(), resolveConstantForwardRefs(), and size().
size()
unsigned llvm::BitcodeReaderValueList::size () const inline
Definition at line 64 of file ValueList.h.
Referenced by shrinkTo().
The documentation for this class was generated from the following files:
lib/Bitcode/Reader/ValueList.h
lib/Bitcode/Reader/ValueList.cpp