LLVM: llvm::symbolize::SymbolizableModule Class Reference
llvm::symbolize::SymbolizableModule Class Reference abstract
#include "llvm/DebugInfo/Symbolize/SymbolizableModule.h"
Public Member Functions
virtual ~SymbolizableModule ()=default
virtual DILineInfo symbolizeCode (object::SectionedAddress ModuleOffset, FunctionNameKind FNKind, bool UseSymbolTable) const =0
virtual DIInliningInfo symbolizeInlinedCode (object::SectionedAddress ModuleOffset, FunctionNameKind FNKind, bool UseSymbolTable) const =0
virtual DIGlobal symbolizeData (object::SectionedAddress ModuleOffset) const =0
virtual std::vector< DILocal > symbolizeFrame (object::SectionedAddress ModuleOffset) const =0
virtual bool isWin32Module () const =0
virtual uint64_t getModulePreferredBase () const =0
Detailed Description
Definition at line 23 of file SymbolizableModule.h.
Constructor & Destructor Documentation
~SymbolizableModule()
virtual llvm::symbolize::SymbolizableModule::~SymbolizableModule () virtual default
Member Function Documentation
getModulePreferredBase()
virtual uint64_t llvm::symbolize::SymbolizableModule::getModulePreferredBase () const pure virtual
Implemented in llvm::symbolize::SymbolizableObjectFile.
Referenced by llvm::symbolize::LLVMSymbolizer::symbolizeData(), llvm::symbolize::LLVMSymbolizer::symbolizeFrame(), and llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode().
isWin32Module()
virtual bool llvm::symbolize::SymbolizableModule::isWin32Module () const pure virtual
Implemented in llvm::symbolize::SymbolizableObjectFile.
Referenced by llvm::symbolize::LLVMSymbolizer::DemangleName().
symbolizeCode()
virtual DILineInfo llvm::symbolize::SymbolizableModule::symbolizeCode (object::SectionedAddress ModuleOffset, FunctionNameKind FNKind, bool UseSymbolTable) const pure virtual
Implemented in llvm::symbolize::SymbolizableObjectFile.
symbolizeData()
virtual DIGlobal llvm::symbolize::SymbolizableModule::symbolizeData (object::SectionedAddress ModuleOffset) const pure virtual
Implemented in llvm::symbolize::SymbolizableObjectFile.
Referenced by llvm::symbolize::LLVMSymbolizer::symbolizeData().
symbolizeFrame()
virtual std::vector<DILocal> llvm::symbolize::SymbolizableModule::symbolizeFrame (object::SectionedAddress ModuleOffset) const pure virtual
Implemented in llvm::symbolize::SymbolizableObjectFile.
Referenced by llvm::symbolize::LLVMSymbolizer::symbolizeFrame().
symbolizeInlinedCode()
virtual DIInliningInfo llvm::symbolize::SymbolizableModule::symbolizeInlinedCode (object::SectionedAddress ModuleOffset, FunctionNameKind FNKind, bool UseSymbolTable) const pure virtual
Implemented in llvm::symbolize::SymbolizableObjectFile.
Referenced by llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/Symbolize/SymbolizableModule.h