LLVM: llvm::codeview::DataMemberRecord Class Reference
llvm::codeview::DataMemberRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
DataMemberRecord ()=default
DataMemberRecord (TypeRecordKind Kind)
DataMemberRecord (MemberAttributes Attrs, TypeIndex Type, uint64_t Offset, StringRef Name)
DataMemberRecord (MemberAccess Access, TypeIndex Type, uint64_t Offset, StringRef Name)
MemberAccess getAccess () const
TypeIndex getType () const
uint64_t getFieldOffset () const
StringRef getName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
MemberAttributes Attrs
TypeIndex Type
uint64_t FieldOffset = 0
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 789 of file TypeRecord.h.
Constructor & Destructor Documentation
DataMemberRecord() [1/4]
llvm::codeview::DataMemberRecord::DataMemberRecord () default
DataMemberRecord() [2/4]
llvm::codeview::DataMemberRecord::DataMemberRecord (TypeRecordKind Kind) inline explicit
Definition at line 792 of file TypeRecord.h.
DataMemberRecord() [3/4]
llvm::codeview::DataMemberRecord::DataMemberRecord (MemberAttributes Attrs, TypeIndex Type, uint64_t Offset, StringRef Name) inline
Definition at line 793 of file TypeRecord.h.
DataMemberRecord() [4/4]
llvm::codeview::DataMemberRecord::DataMemberRecord (MemberAccess Access, TypeIndex Type, uint64_t Offset, StringRef Name) inline
Definition at line 797 of file TypeRecord.h.
Member Function Documentation
getAccess()
MemberAccess llvm::codeview::DataMemberRecord::getAccess () const inline
Definition at line 802 of file TypeRecord.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
getFieldOffset()
uint64_t llvm::codeview::DataMemberRecord::getFieldOffset () const inline
Definition at line 804 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getName()
StringRef llvm::codeview::DataMemberRecord::getName () const inline
Definition at line 805 of file TypeRecord.h.
References Name.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
getType()
TypeIndex llvm::codeview::DataMemberRecord::getType () const inline
Definition at line 803 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitUnknownType().
Member Data Documentation
Attrs
MemberAttributes llvm::codeview::DataMemberRecord::Attrs
Definition at line 807 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
FieldOffset
uint64_t llvm::codeview::DataMemberRecord::FieldOffset = 0
Definition at line 809 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Name
StringRef llvm::codeview::DataMemberRecord::Name
Definition at line 810 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Type
TypeIndex llvm::codeview::DataMemberRecord::Type
Definition at line 808 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h