LLVM: llvm::pdb::PublicsStream Class Reference
llvm::pdb::PublicsStream Class Reference
#include "llvm/DebugInfo/PDB/Native/PublicsStream.h"
Public Member Functions
PublicsStream (std::unique_ptr< msf::MappedBlockStream > Stream)
~PublicsStream ()
Error reload ()
uint32_t getSymHash () const
uint16_t getThunkTableSection () const
uint32_t getThunkTableOffset () const
const GSIHashTable & getPublicsTable () const
FixedStreamArray< support::ulittle32_t > getAddressMap () const
FixedStreamArray< support::ulittle32_t > getThunkMap () const
FixedStreamArray< SectionOffset > getSectionOffsets () const
Detailed Description
Definition at line 27 of file PublicsStream.h.
Constructor & Destructor Documentation
PublicsStream()
PublicsStream::PublicsStream (std::unique_ptr< msf::MappedBlockStream > Stream)
Definition at line 40 of file PublicsStream.cpp.
References ~PublicsStream().
~PublicsStream()
PublicsStream::~PublicsStream () default
Referenced by PublicsStream().
Member Function Documentation
getAddressMap()
FixedStreamArray<support::ulittle32_t> llvm::pdb::PublicsStream::getAddressMap () const inline
Definition at line 37 of file PublicsStream.h.
getPublicsTable()
const GSIHashTable& llvm::pdb::PublicsStream::getPublicsTable () const inline
Definition at line 36 of file PublicsStream.h.
getSectionOffsets()
FixedStreamArray<SectionOffset> llvm::pdb::PublicsStream::getSectionOffsets () const inline
Definition at line 43 of file PublicsStream.h.
getSymHash()
uint32_t PublicsStream::getSymHash () const
Definition at line 45 of file PublicsStream.cpp.
References llvm::pdb::PublicsStreamHeader::SymHash.
getThunkMap()
FixedStreamArray<support::ulittle32_t> llvm::pdb::PublicsStream::getThunkMap () const inline
Definition at line 40 of file PublicsStream.h.
getThunkTableOffset()
uint32_t PublicsStream::getThunkTableOffset () const
Definition at line 49 of file PublicsStream.cpp.
References llvm::pdb::PublicsStreamHeader::OffThunkTable.
getThunkTableSection()
uint16_t PublicsStream::getThunkTableSection () const
Definition at line 46 of file PublicsStream.cpp.
References llvm::pdb::PublicsStreamHeader::ISectThunkTable.
reload()
Error PublicsStream::reload ()
Definition at line 58 of file PublicsStream.cpp.
References llvm::pdb::PublicsStreamHeader::AddrMap, llvm::BinaryStreamReader::bytesRemaining(), llvm::pdb::corrupt_file, E, llvm::joinErrors(), llvm::pdb::PublicsStreamHeader::NumSections, llvm::pdb::PublicsStreamHeader::NumThunks, llvm::pdb::GSIHashTable::read(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/PublicsStream.h
lib/DebugInfo/PDB/Native/PublicsStream.cpp