LLVM: llvm::RegisterBankInfo Class Reference
llvm::RegisterBankInfo Class Reference
Holds all the information related to register banks.
#include "llvm/CodeGen/GlobalISel/RegisterBankInfo.h"
Classes
class InstructionMapping
Helper class that represents how the value of an instruction may be mapped and what is the related cost of such mapping.
class OperandsMapper
Helper class used to get/create the virtual registers that will be used to replace the MachineOperand when applying a mapping.
struct PartialMapping
Helper struct that represents how a value is partially mapped into a register.
struct ValueMapping
Helper struct that represents how a value is mapped through different register banks.
Public Types
using InstructionMappings = SmallVector< const InstructionMapping *, 4 >
Convenient type to represent the alternatives for mapping an instruction.
Public Member Functions
const RegisterBank * getRegBankFromConstraints (const MachineInstr &MI, unsigned OpIdx, const TargetInstrInfo &TII, const MachineRegisterInfo &MRI) const
Get the register bank for the OpIdx-th operand of MI form the encoding constraints, if any.
virtual void applyMappingImpl (const OperandsMapper &OpdMapper) const
See applyMapping.
virtual ~RegisterBankInfo ()=default
const RegisterBank & getRegBank (unsigned ID) const
Get the register bank identified by ID.
const RegisterBank * getRegBank (Register Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI) const
Get the register bank of Reg.
unsigned getNumRegBanks () const
Get the total number of register banks.
virtual const RegisterBank & getRegBankFromRegClass (const TargetRegisterClass &RC, LLT Ty) const
Get a register bank that covers RC.
virtual unsigned copyCost (const RegisterBank &A, const RegisterBank &B, unsigned Size) const
Get the cost of a copy from B to A, or put differently, get the cost of A = COPY B.
bool cannotCopy (const RegisterBank &Dst, const RegisterBank &Src, unsigned Size) const
virtual unsigned getBreakDownCost (const ValueMapping &ValMapping, const RegisterBank *CurBank=nullptr) const
Get the cost of using ValMapping to decompose a register.
virtual const InstructionMapping & getInstrMapping (const MachineInstr &MI) const
Get the mapping of the different operands of MI on the register bank.
virtual InstructionMappings getInstrAlternativeMappings (const MachineInstr &MI) const
Get the alternative mappings for MI.
Static Public Member Functions
static void applyDefaultMapping (const OperandsMapper &OpdMapper)
Helper method to apply something that is like the default mapping.
static const TargetRegisterClass * constrainGenericRegister (Register Reg, const TargetRegisterClass &RC, MachineRegisterInfo &MRI)
Constrain the (possibly generic) virtual register Reg to RC.
Public Attributes
struct llvm::RegisterBankInfo::PartialMapping ScalarAddx2
VectorAdd
Get the possible mapping for MI.
Static Public Attributes
static const unsigned DefaultMappingID = UINT_MAX
Identifier used when the related instruction mapping instance is generated by target independent code.
static const unsigned InvalidMappingID = UINT_MAX - 1
Identifier used when the related instruction mapping instance is generated by the default constructor.
Protected Member Functions
RegisterBankInfo (RegisterBank **RegBanks, unsigned NumRegBanks)
Create a RegisterBankInfo that can accommodate up to NumRegBanks RegisterBank instances.
RegisterBankInfo ()
This constructor is meaningless.
RegisterBank & getRegBank (unsigned ID)
Get the register bank identified by ID.
const TargetRegisterClass & getMinimalPhysRegClass (Register Reg, const TargetRegisterInfo &TRI) const
Get the MinimalPhysRegClass for Reg.
const InstructionMapping & getInstrMappingImpl (const MachineInstr &MI) const
Try to get the mapping of MI.
const PartialMapping & getPartialMapping (unsigned StartIdx, unsigned Length, const RegisterBank &RegBank) const
Get the uniquely generated PartialMapping for the given arguments.
Methods to get a uniquely generated ValueMapping.
const ValueMapping & getValueMapping (unsigned StartIdx, unsigned Length, const RegisterBank &RegBank) const
The most common ValueMapping consists of a single PartialMapping.
const ValueMapping & getValueMapping (const PartialMapping *BreakDown, unsigned NumBreakDowns) const
Get the ValueMapping for the given arguments.
Methods to get a uniquely generated array of ValueMapping.
template<typename Iterator >
const ValueMapping * getOperandsMapping (Iterator Begin, Iterator End) const
Get the uniquely generated array of ValueMapping for the elements of between Begin and End.
const ValueMapping * getOperandsMapping (const SmallVectorImpl< const ValueMapping *> &OpdsMapping) const
Get the uniquely generated array of ValueMapping for the elements of OpdsMapping.
const ValueMapping * getOperandsMapping (std::initializer_list< const ValueMapping *> OpdsMapping) const
Get the uniquely generated array of ValueMapping for the given arguments.
Protected Attributes
RegisterBank ** RegBanks
Hold the set of supported register banks.
unsigned NumRegBanks
Total number of register banks.
DenseMap< unsigned, std::unique_ptr< const PartialMapping > > MapOfPartialMappings
Keep dynamically allocated PartialMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< const ValueMapping > > MapOfValueMappings
Keep dynamically allocated ValueMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< ValueMapping[]> > MapOfOperandsMappings
Keep dynamically allocated array of ValueMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< const InstructionMapping > > MapOfInstructionMappings
Keep dynamically allocated InstructionMapping in a separate map.
DenseMap< unsigned, const TargetRegisterClass * > PhysRegMinimalRCs
Getting the minimal register class of a physreg is expensive.
Methods to get a uniquely generated InstructionMapping.
const InstructionMapping & getInstructionMapping (unsigned ID, unsigned Cost, const ValueMapping *OperandsMapping, unsigned NumOperands) const
Method to get a uniquely generated InstructionMapping.
const InstructionMapping & getInvalidInstructionMapping () const
Method to get a uniquely generated invalid InstructionMapping.
Detailed Description
Holds all the information related to register banks.
Definition at line 39 of file RegisterBankInfo.h.
Member Typedef Documentation
InstructionMappings
using llvm::RegisterBankInfo::InstructionMappings = SmallVector<const InstructionMapping *, 4>
Convenient type to represent the alternatives for mapping an instruction.
Todo:
When we move to TableGen this should be an array ref.
Definition at line 275 of file RegisterBankInfo.h.
Constructor & Destructor Documentation
RegisterBankInfo() [1/2]
RegisterBankInfo::RegisterBankInfo (RegisterBank ** RegBanks, unsigned NumRegBanks) protected
Create a RegisterBankInfo that can accommodate up to NumRegBanks RegisterBank instances.
Definition at line 58 of file RegisterBankInfo.cpp.
RegisterBankInfo() [2/2]
llvm::RegisterBankInfo::RegisterBankInfo () inline protected
This constructor is meaningless.
It just provides a default constructor that can be used at link time when GlobalISel is not built. That way, targets can still inherit from this class without doing crazy gymnastic to avoid link time failures.
Note
That works because the constructor is inlined.
Definition at line 426 of file RegisterBankInfo.h.
References llvm_unreachable.
~RegisterBankInfo()
virtual llvm::RegisterBankInfo::~RegisterBankInfo () virtual default
Referenced by applyMappingImpl().
Member Function Documentation
applyDefaultMapping()
void RegisterBankInfo::applyDefaultMapping (const OperandsMapper & OpdMapper) static
Helper method to apply something that is like the default mapping.
Basically, that means that OpdMapper.getMI() is left untouched aside from the reassignment of the register operand that have been remapped.
The type of all the new registers that have been created by the mapper are properly remapped to the type of the original registers they replace. In other words, the semantic of the instruction does not change, only the register banks.
If the mapping of one of the operand spans several registers, this method will abort as this is not like a default mapping anymore.
Precondition
For OpIdx in {0..OpdMapper.getMI().getNumOperands()) the range OpdMapper.getVRegs(OpIdx) is empty or of size 1.
Definition at line 439 of file RegisterBankInfo.cpp.
References assert(), llvm::dbgs(), llvm::RegisterBankInfo::OperandsMapper::getInstrMapping(), llvm::RegisterBankInfo::OperandsMapper::getMI(), getMinimalPhysRegClass(), llvm::RegisterBankInfo::OperandsMapper::getMRI(), llvm::RegisterBankInfo::InstructionMapping::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), LLVM_DEBUG, MRI, llvm::RegisterBankInfo::ValueMapping::NumBreakDowns, llvm::printReg(), Reg, llvm::MachineOperand::setReg(), and llvm::MachineRegisterInfo::setType().
Referenced by llvm::applyMapping(), llvm::AMDGPURegisterBankInfo::applyMappingImage(), llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::X86RegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), and getInvalidInstructionMapping().
applyMappingImpl()
virtual void llvm::RegisterBankInfo::applyMappingImpl (const OperandsMapper & OpdMapper) const inline virtual
See applyMapping.
Reimplemented in llvm::AMDGPURegisterBankInfo, llvm::X86RegisterBankInfo, and llvm::MipsRegisterBankInfo.
Definition at line 567 of file RegisterBankInfo.h.
References llvm_unreachable, and ~RegisterBankInfo().
Referenced by llvm::applyMapping().
cannotCopy()
bool llvm::RegisterBankInfo::cannotCopy (const RegisterBank & Dst, const RegisterBank & Src, unsigned Size) const inline
Returns
true if emitting a copy from Src to Dst is impossible.
Definition at line 623 of file RegisterBankInfo.h.
References copyCost(), and llvm::max().
Referenced by getInstrMappingImpl().
constrainGenericRegister()
const TargetRegisterClass * RegisterBankInfo::constrainGenericRegister (Register Reg, const TargetRegisterClass & RC, MachineRegisterInfo & MRI) static
Constrain the (possibly generic) virtual register Reg to RC.
Precondition
Reg is a virtual register that either has a bank or a class.
Returns
The constrained register class, or nullptr if there is none.
Note
This is a generic variant of MachineRegisterInfo::constrainRegClass
Use MachineRegisterInfo::constrainRegAttrs instead for any non-isel purpose, including non-select passes of GlobalISel
Definition at line 132 of file RegisterBankInfo.cpp.
References llvm::MachineRegisterInfo::constrainRegClass(), llvm::RegisterBank::covers(), llvm::MachineRegisterInfo::getRegClassOrRegBank(), and llvm::MachineRegisterInfo::setRegClass().
Referenced by llvm::AMDGPURegisterBankInfo::buildVCopy(), llvm::AMDGPURegisterBankInfo::constrainOpWithReadfirstlane(), llvm::constrainRegToClass(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), findIntrinsicID(), getBreakDownCost(), getDSShaderTypeValue(), getInsertVecEltOpInfo(), getLaneCopyOpcode(), getLogicalBitOpcode(), getV_CMPOpcode(), getVectorSHLImm(), isConstant(), selectCopy(), selectSubregisterCopy(), llvm::AMDGPUInstructionSelector::setupMF(), shouldUseAndMask(), and sizeToSubRegIndex().
copyCost()
virtual unsigned llvm::RegisterBankInfo::copyCost (const RegisterBank & A, const RegisterBank & B, unsigned Size) const inline virtual
Get the cost of a copy from B to A, or put differently, get the cost of A = COPY B.
Since register banks may cover different size, Size specifies what will be the size in bits that will be copied around.
Note
Since this is a copy, both registers have the same size.
Reimplemented in llvm::AMDGPURegisterBankInfo, and llvm::AArch64RegisterBankInfo.
Definition at line 613 of file RegisterBankInfo.h.
References B.
Referenced by cannotCopy(), llvm::AArch64RegisterBankInfo::copyCost(), llvm::AMDGPURegisterBankInfo::copyCost(), and llvm::RegBankSelect::getAnalysisUsage().
getBreakDownCost()
virtual unsigned llvm::RegisterBankInfo::getBreakDownCost (const ValueMapping & ValMapping, const RegisterBank * CurBank = nullptr) const inline virtual
Get the cost of using ValMapping to decompose a register.
This is similar to copyCost, except for cases where multiple copy-like operations need to be inserted. If the register is used as a source operand and already has a bank assigned, CurBank is non-null.
Reimplemented in llvm::AMDGPURegisterBankInfo.
Definition at line 632 of file RegisterBankInfo.h.
References constrainGenericRegister(), and llvm::max().
Referenced by llvm::RegBankSelect::getAnalysisUsage().
getInstrAlternativeMappings()
RegisterBankInfo::InstructionMappings RegisterBankInfo::getInstrAlternativeMappings (const MachineInstr & MI) const virtual
Get the alternative mappings for MI.
Alternative in the sense different from getInstrMapping.
Reimplemented in llvm::AMDGPURegisterBankInfo, llvm::AArch64RegisterBankInfo, and llvm::X86RegisterBankInfo.
Definition at line 434 of file RegisterBankInfo.cpp.
Referenced by llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappingsIntrinsic(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappingsIntrinsicWSideEffects(), and getInstrMapping().
getInstrMapping()
const RegisterBankInfo::InstructionMapping & RegisterBankInfo::getInstrMapping (const MachineInstr & MI) const virtual
Get the mapping of the different operands of MI on the register bank.
This mapping should be the direct translation of MI. In other words, when MI is mapped with the returned mapping, only the register banks of the operands of MI need to be updated. In particular, neither the opcode nor the type of MI needs to be updated for this direct mapping.
The target independent implementation gives a mapping based on the register classes for the target specific opcode. It uses the ID RegisterBankInfo::DefaultMappingID for that mapping. Make sure you do not use that ID for the alternative mapping for MI. See getInstrAlternativeMappings for the alternative mappings.
For instance, if MI is a vector add, the mapping should not be a scalarization of the add.
Postcondition
returnedVal.verify(MI).
Note
If returnedVal does not verify MI, this would probably mean that the target does not support that instruction.
Reimplemented in llvm::AMDGPURegisterBankInfo, llvm::AArch64RegisterBankInfo, llvm::X86RegisterBankInfo, llvm::ARMRegisterBankInfo, and llvm::MipsRegisterBankInfo.
Definition at line 406 of file RegisterBankInfo.cpp.
References assert(), getInstrAlternativeMappings(), getInstrMappingImpl(), llvm::RegisterBankInfo::InstructionMapping::isValid(), llvm_unreachable, MI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::RegBankSelect::getAnalysisUsage().
getInstrMappingImpl()
const RegisterBankInfo::InstructionMapping & RegisterBankInfo::getInstrMappingImpl (const MachineInstr & MI) const protected
Try to get the mapping of MI.
See getInstrMapping for more details on what a mapping represents.
Unlike getInstrMapping the returned InstructionMapping may be invalid (isValid() == false). This means that the target independent code is not smart enough to get the mapping of MI and thus, the target has to provide the information for MI.
This implementation is able to get the mapping of:
Target specific instructions by looking at the encoding constraints.
Any instruction if all the register operands have already been assigned a register, a register class, or a register bank.
Copies and phis if at least one of the operands has been assigned a register, a register class, or a register bank. In other words, this method will likely fail to find a mapping for any generic opcode that has not been lowered by target specific code.
Definition at line 162 of file RegisterBankInfo.cpp.
References assert(), cannotCopy(), DefaultMappingID, llvm::TargetSubtargetInfo::getInstrInfo(), getInstructionMapping(), getInvalidInstructionMapping(), llvm::MachineInstr::getMF(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), getOperandsMapping(), llvm::MachineOperand::getReg(), getRegBank(), getRegBankFromConstraints(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::getSizeInBits(), llvm::MachineFunction::getSubtarget(), getValueMapping(), isCopyLike(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegSequence(), MRI, Reg, Size, TII, and TRI.
Referenced by llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), getInstrMapping(), and getRegBank().
getInstructionMapping()
const InstructionMapping& llvm::RegisterBankInfo::getInstructionMapping (unsigned ID, unsigned Cost, const ValueMapping * OperandsMapping, unsigned NumOperands) const inline
Method to get a uniquely generated InstructionMapping.
Definition at line 525 of file RegisterBankInfo.h.
Referenced by llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::AMDGPURegisterBankInfo::getDefaultMappingSOP(), llvm::AMDGPURegisterBankInfo::getDefaultMappingVOP(), llvm::AMDGPURegisterBankInfo::getImageMapping(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), getInstrMappingImpl(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), and isPreISelGenericFloatingPointOpcode().
getInvalidInstructionMapping()
const InstructionMapping& llvm::RegisterBankInfo::getInvalidInstructionMapping () const inline
Method to get a uniquely generated invalid InstructionMapping.
Definition at line 533 of file RegisterBankInfo.h.
References applyDefaultMapping(), getRegBankFromConstraints(), MRI, and TII.
Referenced by llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), and getInstrMappingImpl().
getMinimalPhysRegClass()
const TargetRegisterClass & RegisterBankInfo::getMinimalPhysRegClass (Register Reg, const TargetRegisterInfo & TRI) const protected
Get the MinimalPhysRegClass for Reg.
Precondition
Reg is a physical register.
Definition at line 101 of file RegisterBankInfo.cpp.
References assert(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::Register::isPhysicalRegister(), PhysRegMinimalRCs, and Reg.
Referenced by applyDefaultMapping(), and getRegBank().
getNumRegBanks()
unsigned llvm::RegisterBankInfo::getNumRegBanks () const inline
Get the total number of register banks.
Definition at line 588 of file RegisterBankInfo.h.
References NumRegBanks.
Referenced by llvm::PerTargetMIParsingState::getMMOTargetFlag(), and getRegBank().
getOperandsMapping() [1/3]
template<typename Iterator > const RegisterBankInfo::ValueMapping * RegisterBankInfo::getOperandsMapping (Iterator Begin, Iterator End) const protected
Get the uniquely generated array of ValueMapping for the elements of between Begin and End.
Elements that are nullptr will be replaced by invalid ValueMapping (ValueMapping::isValid == false).
Precondition
The pointers on ValueMapping between Begin and End must uniquely identify a ValueMapping. Otherwise, there is no guarantee that the return instance will be unique, i.e., another OperandsMapping could have the same content.
Definition at line 332 of file RegisterBankInfo.cpp.
Referenced by llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::AMDGPURegisterBankInfo::getDefaultMappingSOP(), llvm::AMDGPURegisterBankInfo::getDefaultMappingVOP(), llvm::AMDGPURegisterBankInfo::getImageMapping(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), getInstrMappingImpl(), getOperandsMapping(), and getRegBank().
getOperandsMapping() [2/3]
const RegisterBankInfo::ValueMapping * RegisterBankInfo::getOperandsMapping (const SmallVectorImpl< const ValueMapping *> & OpdsMapping) const protected
Get the uniquely generated array of ValueMapping for the elements of OpdsMapping.
Elements of OpdsMapping that are nullptr will be replaced by invalid ValueMapping (ValueMapping::isValid == false).
Definition at line 361 of file RegisterBankInfo.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), and getOperandsMapping().
getOperandsMapping() [3/3]
const ValueMapping* llvm::RegisterBankInfo::getOperandsMapping (std::initializer_list< const ValueMapping *> OpdsMapping) const protected
Get the uniquely generated array of ValueMapping for the given arguments.
Arguments that are nullptr will be replaced by invalid ValueMapping (ValueMapping::isValid == false).
getPartialMapping()
const RegisterBankInfo::PartialMapping & RegisterBankInfo::getPartialMapping (unsigned StartIdx, unsigned Length, const RegisterBank & RegBank) const protected
Get the uniquely generated PartialMapping for the given arguments.
Definition at line 280 of file RegisterBankInfo.cpp.
References hashPartialMapping(), and MapOfPartialMappings.
Referenced by getRegBank(), and getValueMapping().
getRegBank() [1/3]
RegisterBank& llvm::RegisterBankInfo::getRegBank (unsigned ID) inline protected
Get the register bank identified by ID.
Definition at line 431 of file RegisterBankInfo.h.
References assert(), getInstrMappingImpl(), getMinimalPhysRegClass(), getNumRegBanks(), getOperandsMapping(), getPartialMapping(), getValueMapping(), llvm::RegisterBankInfo::PartialMapping::Length, MI, Reg, llvm::RegisterBankInfo::PartialMapping::RegBank, llvm::RegisterBankInfo::PartialMapping::StartIdx, and TRI.
Referenced by llvm::AArch64RegisterBankInfo::AArch64RegisterBankInfo(), llvm::AMDGPURegisterBankInfo::AMDGPURegisterBankInfo(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::ARMRegisterBankInfo::ARMRegisterBankInfo(), changeFCMPPredToAArch64CC(), llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), llvm::AMDGPURegisterBankInfo::constrainOpWithReadfirstlane(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::InstructionSelector::executeMatchTable(), findIntrinsicID(), llvm::RegBankSelect::getAnalysisUsage(), getInsertVecEltOpInfo(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), getInstrMappingImpl(), getLaneCopyOpcode(), getLogicalBitOpcode(), llvm::PerTargetMIParsingState::getMMOTargetFlag(), getRegBank(), llvm::ARMRegisterBankInfo::getRegBankFromRegClass(), llvm::MipsRegisterBankInfo::getRegBankFromRegClass(), llvm::X86RegisterBankInfo::getRegBankFromRegClass(), llvm::AArch64RegisterBankInfo::getRegBankFromRegClass(), llvm::AMDGPURegisterBankInfo::getRegBankID(), getRegClassesForCopy(), getVectorSHLImm(), isAmbiguous(), isConstant(), isPreISelGenericFloatingPointOpcode(), llvm::AMDGPURegisterBankInfo::isSALUMapping(), selectCopy(), selectMergeValues(), selectSelectOpc(), selectUnmergeValues(), llvm::MipsRegisterBankInfo::setRegBank(), sizeToSubRegIndex(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), unsupportedBinOp(), and llvm::X86RegisterBankInfo::X86RegisterBankInfo().
getRegBank() [2/3]
const RegisterBank& llvm::RegisterBankInfo::getRegBank (unsigned ID) const inline
Get the register bank identified by ID.
Definition at line 575 of file RegisterBankInfo.h.
References getRegBank().
getRegBank() [3/3]
const RegisterBank * RegisterBankInfo::getRegBank (Register Reg, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI) const
Get the register bank of Reg.
If Reg has not been assigned a register, a register class, or a register bank, then this returns nullptr.
Precondition
Reg != 0 (NoRegister)
Definition at line 83 of file RegisterBankInfo.cpp.
References assert(), llvm::PointerUnion< PTs >::dyn_cast(), getMinimalPhysRegClass(), getRegBankFromRegClass(), llvm::MachineRegisterInfo::getRegClassOrRegBank(), llvm::MachineRegisterInfo::getType(), and llvm::Register::isPhysicalRegister().
getRegBankFromConstraints()
const RegisterBank * RegisterBankInfo::getRegBankFromConstraints (const MachineInstr & MI, unsigned OpIdx, const TargetInstrInfo & TII, const MachineRegisterInfo & MRI) const
Get the register bank for the OpIdx-th operand of MI form the encoding constraints, if any.
Returns
A register bank that covers the register class of the related encoding constraints or nullptr if MI did not provide enough information to deduce it.
Definition at line 112 of file RegisterBankInfo.cpp.
References assert(), llvm::RegisterBank::covers(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getRegBankFromRegClass(), llvm::MachineInstr::getRegClassConstraint(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::MachineRegisterInfo::getType(), and Reg.
Referenced by getInstrMappingImpl(), and getInvalidInstructionMapping().
getRegBankFromRegClass()
virtual const RegisterBank& llvm::RegisterBankInfo::getRegBankFromRegClass (const TargetRegisterClass & RC, LLT Ty) const inline virtual
Get a register bank that covers RC.
Precondition
RC is a user-defined register class (as opposed as one generated by TableGen).
Note
The mapping RC -> RegBank could be built while adding the coverage for the register banks. However, we do not do it, because, at least for now, we only need this information for register classes that are used in the description of instruction. In other words, there are just a handful of them and we do not want to waste space.
Todo:
This should be TableGen'ed.
Reimplemented in llvm::AMDGPURegisterBankInfo, llvm::AArch64RegisterBankInfo, llvm::X86RegisterBankInfo, llvm::ARMRegisterBankInfo, and llvm::MipsRegisterBankInfo.
Definition at line 603 of file RegisterBankInfo.h.
References llvm_unreachable.
Referenced by llvm::InstructionSelector::executeMatchTable(), getRegBank(), and getRegBankFromConstraints().
getValueMapping() [1/2]
const RegisterBankInfo::ValueMapping & RegisterBankInfo::getValueMapping (unsigned StartIdx, unsigned Length, const RegisterBank & RegBank) const protected
The most common ValueMapping consists of a single PartialMapping.
Feature a method for that.
Definition at line 297 of file RegisterBankInfo.cpp.
References getPartialMapping().
Referenced by llvm::AMDGPURegisterBankInfo::getInstrMapping(), getInstrMappingImpl(), and getRegBank().
getValueMapping() [2/2]
const RegisterBankInfo::ValueMapping & RegisterBankInfo::getValueMapping (const PartialMapping * BreakDown, unsigned NumBreakDowns) const protected
Get the ValueMapping for the given arguments.
Definition at line 314 of file RegisterBankInfo.cpp.
References hashValueMapping(), and MapOfValueMappings.
Member Data Documentation
DefaultMappingID
const unsigned RegisterBankInfo::DefaultMappingID = UINT_MAX static
Identifier used when the related instruction mapping instance is generated by target independent code.
Make sure not to use that identifier to avoid possible collision.
Definition at line 651 of file RegisterBankInfo.h.
Referenced by llvm::applyMapping(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), getInstrMappingImpl(), llvm::X86GenRegisterBankInfo::getPartialMappingIdx(), and isPreISelGenericFloatingPointOpcode().
InvalidMappingID
const unsigned RegisterBankInfo::InvalidMappingID = UINT_MAX - 1 static
Identifier used when the related instruction mapping instance is generated by the default constructor.
Make sure not to use that identifier.
Definition at line 656 of file RegisterBankInfo.h.
Referenced by hashInstructionMapping(), and llvm::RegisterBankInfo::InstructionMapping::isValid().
MapOfInstructionMappings
DenseMap<unsigned, std::unique_ptr<const InstructionMapping> > llvm::RegisterBankInfo::MapOfInstructionMappings mutable protected
Keep dynamically allocated InstructionMapping in a separate map.
This shouldn't be needed when everything gets TableGen'ed.
Definition at line 410 of file RegisterBankInfo.h.
Referenced by hashInstructionMapping().
MapOfOperandsMappings
DenseMap<unsigned, std::unique_ptr<ValueMapping[]> > llvm::RegisterBankInfo::MapOfOperandsMappings mutable protected
Keep dynamically allocated array of ValueMapping in a separate map.
This shouldn't be needed when everything gets TableGen'ed.
Definition at line 405 of file RegisterBankInfo.h.
MapOfPartialMappings
DenseMap<unsigned, std::unique_ptr<const PartialMapping> > llvm::RegisterBankInfo::MapOfPartialMappings mutable protected
Keep dynamically allocated PartialMapping in a separate map.
This shouldn't be needed when everything gets TableGen'ed.
Definition at line 395 of file RegisterBankInfo.h.
Referenced by getPartialMapping().
MapOfValueMappings
DenseMap<unsigned, std::unique_ptr<const ValueMapping> > llvm::RegisterBankInfo::MapOfValueMappings mutable protected
Keep dynamically allocated ValueMapping in a separate map.
This shouldn't be needed when everything gets TableGen'ed.
Definition at line 400 of file RegisterBankInfo.h.
Referenced by getValueMapping().
NumRegBanks
unsigned llvm::RegisterBankInfo::NumRegBanks protected
Total number of register banks.
Definition at line 390 of file RegisterBankInfo.h.
Referenced by getNumRegBanks().
PhysRegMinimalRCs
DenseMap<unsigned, const TargetRegisterClass *> llvm::RegisterBankInfo::PhysRegMinimalRCs mutable protected
Getting the minimal register class of a physreg is expensive.
Cache this information as we get it.
Definition at line 414 of file RegisterBankInfo.h.
Referenced by getMinimalPhysRegClass().
RegBanks
RegisterBank** llvm::RegisterBankInfo::RegBanks protected
Hold the set of supported register banks.
Definition at line 387 of file RegisterBankInfo.h.
ScalarAddx2
struct llvm::RegisterBankInfo::PartialMapping llvm::RegisterBankInfo::ScalarAddx2
VectorAdd
llvm::RegisterBankInfo::VectorAdd
Get the possible mapping for MI.
A mapping defines where the different operands may live and at what cost. For instance, let us consider: v0(16) = G_ADD <2 x i8> v1, v2 The possible mapping could be:
{/*ID
Definition at line 694 of file RegisterBankInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/RegisterBankInfo.h
lib/CodeGen/GlobalISel/RegisterBankInfo.cpp