LLVM: llvm::Triple Class Reference
llvm::Triple Class Reference
Triple - Helper class for working with autoconf configuration names.
#include "llvm/ADT/Triple.h"
Public Types
enum ArchType {
UnknownArch, arm, armeb, aarch64,
aarch64_be, aarch64_32, arc, avr,
bpfel, bpfeb, hexagon, mips,
mipsel, mips64, mips64el, msp430,
ppc, ppc64, ppc64le, r600,
amdgcn, riscv32, riscv64, sparc,
sparcv9, sparcel, systemz, tce,
tcele, thumb, thumbeb, x86,
x86_64, xcore, nvptx, nvptx64,
le32, le64, amdil, amdil64,
hsail, hsail64, spir, spir64,
kalimba, shave, lanai, wasm32,
wasm64, renderscript32, renderscript64, ve,
LastArchType = ve
}
enum SubArchType {
NoSubArch, ARMSubArch_v8_5a, ARMSubArch_v8_4a, ARMSubArch_v8_3a,
ARMSubArch_v8_2a, ARMSubArch_v8_1a, ARMSubArch_v8, ARMSubArch_v8r,
ARMSubArch_v8m_baseline, ARMSubArch_v8m_mainline, ARMSubArch_v8_1m_mainline, ARMSubArch_v7,
ARMSubArch_v7em, ARMSubArch_v7m, ARMSubArch_v7s, ARMSubArch_v7k,
ARMSubArch_v7ve, ARMSubArch_v6, ARMSubArch_v6m, ARMSubArch_v6k,
ARMSubArch_v6t2, ARMSubArch_v5, ARMSubArch_v5te, ARMSubArch_v4t,
KalimbaSubArch_v3, KalimbaSubArch_v4, KalimbaSubArch_v5, MipsSubArch_r6,
PPCSubArch_spe
}
enum VendorType {
UnknownVendor, Apple, PC, SCEI,
BGP, BGQ, Freescale, IBM,
ImaginationTechnologies, MipsTechnologies, NVIDIA, CSR,
Myriad, AMD, Mesa, SUSE,
OpenEmbedded, LastVendorType = OpenEmbedded
}
enum OSType {
UnknownOS, Ananas, CloudABI, Darwin,
DragonFly, FreeBSD, Fuchsia, IOS,
KFreeBSD, Linux, Lv2, MacOSX,
NetBSD, OpenBSD, Solaris, Win32,
Haiku, Minix, RTEMS, NaCl,
CNK, AIX, CUDA, NVCL,
AMDHSA, PS4, ELFIAMCU, TvOS,
WatchOS, Mesa3D, Contiki, AMDPAL,
HermitCore, Hurd, WASI, Emscripten,
LastOSType = Emscripten
}
enum EnvironmentType {
UnknownEnvironment, GNU, GNUABIN32, GNUABI64,
GNUEABI, GNUEABIHF, GNUX32, CODE16,
EABI, EABIHF, Android, Musl,
MuslEABI, MuslEABIHF, MSVC, Itanium,
Cygnus, CoreCLR, Simulator, MacABI,
LastEnvironmentType = MacABI
}
enum ObjectFormatType {
UnknownObjectFormat, COFF, ELF, MachO,
Wasm, XCOFF
}
Public Member Functions
Constructors
Triple ()
Default constructor is the same as an empty string and leaves all triple fields unknown.
Triple (const Twine &Str)
Construct a triple from the string representation provided.
Triple (const Twine &ArchStr, const Twine &VendorStr, const Twine &OSStr)
Construct a triple from string representations of the architecture, vendor, and OS.
Triple (const Twine &ArchStr, const Twine &VendorStr, const Twine &OSStr, const Twine &EnvironmentStr)
Construct a triple from string representations of the architecture, vendor, OS, and environment.
bool operator== (const Triple &Other) const
bool operator!= (const Triple &Other) const
Typed Component Access
ArchType getArch () const
getArch - Get the parsed architecture type of this triple.
SubArchType getSubArch () const
getSubArch - get the parsed subarchitecture type for this triple.
VendorType getVendor () const
getVendor - Get the parsed vendor type of this triple.
OSType getOS () const
getOS - Get the parsed operating system type of this triple.
bool hasEnvironment () const
hasEnvironment - Does this triple have the optional environment (fourth) component?
EnvironmentType getEnvironment () const
getEnvironment - Get the parsed environment type of this triple.
void getEnvironmentVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
Parse the version number from the OS name component of the triple, if present.
ObjectFormatType getObjectFormat () const
getFormat - Get the object format for this triple.
void getOSVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
getOSVersion - Parse the version number from the OS name component of the triple, if present.
unsigned getOSMajorVersion () const
getOSMajorVersion - Return just the major version number, this is specialized because it is a common query.
bool getMacOSXVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
getMacOSXVersion - Parse the version number as with getOSVersion and then translate generic "darwin" versions to the corresponding OS X versions.
void getiOSVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
getiOSVersion - Parse the version number as with getOSVersion.
void getWatchOSVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
getWatchOSVersion - Parse the version number as with getOSVersion.
Direct Component Access
const std::string & str () const
const std::string & getTriple () const
StringRef getArchName () const
getArchName - Get the architecture (first) component of the triple.
StringRef getVendorName () const
getVendorName - Get the vendor (second) component of the triple.
StringRef getOSName () const
getOSName - Get the operating system (third) component of the triple.
StringRef getEnvironmentName () const
getEnvironmentName - Get the optional environment (fourth) component of the triple, or "" if empty.
StringRef getOSAndEnvironmentName () const
getOSAndEnvironmentName - Get the operating system and optional environment components as a single string (separated by a '-' if the environment component is present).
Convenience Predicates
bool isArch64Bit () const
Test whether the architecture is 64-bit.
bool isArch32Bit () const
Test whether the architecture is 32-bit.
bool isArch16Bit () const
Test whether the architecture is 16-bit.
bool isOSVersionLT (unsigned Major, unsigned Minor=0, unsigned Micro=0) const
isOSVersionLT - Helper function for doing comparisons against version numbers included in the target triple.
bool isOSVersionLT (const Triple &Other) const
bool isMacOSXVersionLT (unsigned Major, unsigned Minor=0, unsigned Micro=0) const
isMacOSXVersionLT - Comparison function for checking OS X version compatibility, which handles supporting skewed version numbering schemes used by the "darwin" triples.
bool isMacOSX () const
isMacOSX - Is this a Mac OS X triple.
bool isiOS () const
Is this an iOS triple.
bool isTvOS () const
Is this an Apple tvOS triple.
bool isWatchOS () const
Is this an Apple watchOS triple.
bool isWatchABI () const
bool isOSDarwin () const
isOSDarwin - Is this a "Darwin" OS (macOS, iOS, tvOS or watchOS).
bool isSimulatorEnvironment () const
bool isMacCatalystEnvironment () const
bool isOSNetBSD () const
bool isOSOpenBSD () const
bool isOSFreeBSD () const
bool isOSFuchsia () const
bool isOSDragonFly () const
bool isOSSolaris () const
bool isOSIAMCU () const
bool isOSUnknown () const
bool isGNUEnvironment () const
bool isOSContiki () const
bool isOSHaiku () const
Tests whether the OS is Haiku.
bool isOSWindows () const
Tests whether the OS is Windows.
bool isKnownWindowsMSVCEnvironment () const
Checks if the environment is MSVC.
bool isWindowsMSVCEnvironment () const
Checks if the environment could be MSVC.
bool isWindowsCoreCLREnvironment () const
bool isWindowsItaniumEnvironment () const
bool isWindowsCygwinEnvironment () const
bool isWindowsGNUEnvironment () const
bool isOSCygMing () const
Tests for either Cygwin or MinGW OS.
bool isOSMSVCRT () const
Is this a "Windows" OS targeting a "MSVCRT.dll" environment.
bool isOSNaCl () const
Tests whether the OS is NaCl (Native Client)
bool isOSLinux () const
Tests whether the OS is Linux.
bool isOSKFreeBSD () const
Tests whether the OS is kFreeBSD.
bool isOSHurd () const
Tests whether the OS is Hurd.
bool isOSWASI () const
Tests whether the OS is WASI.
bool isOSEmscripten () const
Tests whether the OS is Emscripten.
bool isOSGlibc () const
Tests whether the OS uses glibc.
bool isOSAIX () const
Tests whether the OS is AIX.
bool isOSBinFormatELF () const
Tests whether the OS uses the ELF binary format.
bool isOSBinFormatCOFF () const
Tests whether the OS uses the COFF binary format.
bool isOSBinFormatMachO () const
Tests whether the environment is MachO.
bool isOSBinFormatWasm () const
Tests whether the OS uses the Wasm binary format.
bool isOSBinFormatXCOFF () const
Tests whether the OS uses the XCOFF binary format.
bool isPS4CPU () const
Tests whether the target is the PS4 CPU.
bool isPS4 () const
Tests whether the target is the PS4 platform.
bool isAndroid () const
Tests whether the target is Android.
bool isAndroidVersionLT (unsigned Major) const
bool isMusl () const
Tests whether the environment is musl-libc.
bool isSPIR () const
Tests whether the target is SPIR (32- or 64-bit).
bool isNVPTX () const
Tests whether the target is NVPTX (32- or 64-bit).
bool isThumb () const
Tests whether the target is Thumb (little and big endian).
bool isARM () const
Tests whether the target is ARM (little and big endian).
bool isAArch64 () const
Tests whether the target is AArch64 (little and big endian).
bool isMIPS32 () const
Tests whether the target is MIPS 32-bit (little and big endian).
bool isMIPS64 () const
Tests whether the target is MIPS 64-bit (little and big endian).
bool isMIPS () const
Tests whether the target is MIPS (little and big endian, 32- or 64-bit).
bool isPPC64 () const
Tests whether the target is 64-bit PowerPC (little and big endian).
bool isRISCV () const
Tests whether the target is RISC-V (32- and 64-bit).
bool isX86 () const
Tests whether the target is x86 (32- or 64-bit).
bool isVE () const
Tests whether the target is VE.
bool supportsCOMDAT () const
Tests whether the target supports comdat.
bool hasDefaultEmulatedTLS () const
Tests whether the target uses emulated TLS as default.
Mutators
void setArch (ArchType Kind)
setArch - Set the architecture (first) component of the triple to a known type.
void setVendor (VendorType Kind)
setVendor - Set the vendor (second) component of the triple to a known type.
void setOS (OSType Kind)
setOS - Set the operating system (third) component of the triple to a known type.
void setEnvironment (EnvironmentType Kind)
setEnvironment - Set the environment (fourth) component of the triple to a known type.
void setObjectFormat (ObjectFormatType Kind)
setObjectFormat - Set the object file format
void setTriple (const Twine &Str)
setTriple - Set all components to the new triple Str.
void setArchName (StringRef Str)
setArchName - Set the architecture (first) component of the triple by name.
void setVendorName (StringRef Str)
setVendorName - Set the vendor (second) component of the triple by name.
void setOSName (StringRef Str)
setOSName - Set the operating system (third) component of the triple by name.
void setEnvironmentName (StringRef Str)
setEnvironmentName - Set the optional environment (fourth) component of the triple by name.
void setOSAndEnvironmentName (StringRef Str)
setOSAndEnvironmentName - Set the operating system and optional environment components with a single string.
Helpers to build variants of a particular triple.
llvm::Triple get32BitArchVariant () const
Form a triple with a 32-bit variant of the current architecture.
llvm::Triple get64BitArchVariant () const
Form a triple with a 64-bit variant of the current architecture.
llvm::Triple getBigEndianArchVariant () const
Form a triple with a big endian variant of the current architecture.
llvm::Triple getLittleEndianArchVariant () const
Form a triple with a little endian variant of the current architecture.
StringRef getARMCPUForArch (StringRef Arch=StringRef()) const
Get the (LLVM) name of the minimum ARM CPU for the arch we are targeting.
bool isLittleEndian () const
Tests whether the target triple is little endian.
bool isCompatibleWith (const Triple &Other) const
Test whether target triples are compatible.
std::string merge (const Triple &Other) const
Merge target triples.
Static Public Member Functions
Static helpers for IDs.
static StringRef getArchTypeName (ArchType Kind)
getArchTypeName - Get the canonical name for the Kind architecture.
static StringRef getArchTypePrefix (ArchType Kind)
getArchTypePrefix - Get the "prefix" canonical name for the Kind architecture.
static StringRef getVendorTypeName (VendorType Kind)
getVendorTypeName - Get the canonical name for the Kind vendor.
static StringRef getOSTypeName (OSType Kind)
getOSTypeName - Get the canonical name for the Kind operating system.
static StringRef getEnvironmentTypeName (EnvironmentType Kind)
getEnvironmentTypeName - Get the canonical name for the Kind environment.
Static helpers for converting alternate architecture names.
static ArchType getArchTypeForLLVMName (StringRef Str)
getArchTypeForLLVMName - The canonical type for the given LLVM architecture name (e.g., "x86").
Normalization
std::string normalize () const
Return the normalized form of this triple's string.
static std::string normalize (StringRef Str)
normalize - Turn an arbitrary machine specification into the canonical triple form (or something sensible that the Triple class understands if nothing better can reasonably be done).
Detailed Description
Triple - Helper class for working with autoconf configuration names.
For historical reasons, we also call these 'triples' (they used to contain exactly three fields).
Configuration names are strings in the canonical form: ARCHITECTURE-VENDOR-OPERATING_SYSTEM or ARCHITECTURE-VENDOR-OPERATING_SYSTEM-ENVIRONMENT
This class is used for clients which want to support arbitrary configuration names, but also want to implement certain special behavior for particular configurations. This class isolates the mapping from the components of the configuration name to well known IDs.
At its core the Triple class is designed to be a wrapper for a triple string; the constructor does not change or normalize the triple string. Clients that need to handle the non-canonical triples that users often specify should use the normalize method.
See autoconf/config.guess for a glimpse into what configuration names look like in practice.
Definition at line 43 of file Triple.h.
Member Enumeration Documentation
ArchType
enum llvm::Triple::ArchType
Enumerator
UnknownArch
arm
armeb
aarch64
aarch64_be
aarch64_32
arc
avr
bpfel
bpfeb
hexagon
mips
mipsel
mips64
mips64el
msp430
ppc
ppc64
ppc64le
r600
amdgcn
riscv32
riscv64
sparc
sparcv9
sparcel
systemz
tce
tcele
thumb
thumbeb
x86
x86_64
xcore
nvptx
nvptx64
le32
le64
amdil
amdil64
hsail
hsail64
spir
spir64
kalimba
shave
lanai
wasm32
wasm64
renderscript32
renderscript64
ve
LastArchType
Definition at line 45 of file Triple.h.
EnvironmentType
enum llvm::Triple::EnvironmentType
Enumerator
UnknownEnvironment
GNU
GNUABIN32
GNUABI64
GNUEABI
GNUEABIHF
GNUX32
CODE16
EABI
EABIHF
Android
Musl
MuslEABI
MuslEABIHF
MSVC
Itanium
Cygnus
CoreCLR
Simulator
MacABI
LastEnvironmentType
Definition at line 197 of file Triple.h.
ObjectFormatType
enum llvm::Triple::ObjectFormatType
Enumerator
UnknownObjectFormat
COFF
ELF
MachO
Wasm
XCOFF
Definition at line 222 of file Triple.h.
OSType
enum llvm::Triple::OSType
Enumerator
UnknownOS
Ananas
CloudABI
Darwin
DragonFly
FreeBSD
Fuchsia
IOS
KFreeBSD
Linux
Lv2
MacOSX
NetBSD
OpenBSD
Solaris
Win32
Haiku
Minix
RTEMS
NaCl
CNK
AIX
CUDA
NVCL
AMDHSA
PS4
ELFIAMCU
TvOS
WatchOS
Mesa3D
Contiki
AMDPAL
HermitCore
Hurd
WASI
Emscripten
LastOSType
Definition at line 157 of file Triple.h.
SubArchType
enum llvm::Triple::SubArchType
Enumerator
NoSubArch
ARMSubArch_v8_5a
ARMSubArch_v8_4a
ARMSubArch_v8_3a
ARMSubArch_v8_2a
ARMSubArch_v8_1a
ARMSubArch_v8
ARMSubArch_v8r
ARMSubArch_v8m_baseline
ARMSubArch_v8m_mainline
ARMSubArch_v8_1m_mainline
ARMSubArch_v7
ARMSubArch_v7em
ARMSubArch_v7m
ARMSubArch_v7s
ARMSubArch_v7k
ARMSubArch_v7ve
ARMSubArch_v6
ARMSubArch_v6m
ARMSubArch_v6k
ARMSubArch_v6t2
ARMSubArch_v5
ARMSubArch_v5te
ARMSubArch_v4t
KalimbaSubArch_v3
KalimbaSubArch_v4
KalimbaSubArch_v5
MipsSubArch_r6
PPCSubArch_spe
Definition at line 101 of file Triple.h.
VendorType
enum llvm::Triple::VendorType
Enumerator
UnknownVendor
Apple
PC
SCEI
BGP
BGQ
Freescale
IBM
ImaginationTechnologies
MipsTechnologies
NVIDIA
CSR
Myriad
AMD
Mesa
SUSE
OpenEmbedded
LastVendorType
Definition at line 136 of file Triple.h.
Constructor & Destructor Documentation
Triple() [1/4]
llvm::Triple::Triple () inline
Default constructor is the same as an empty string and leaves all triple fields unknown.
Definition at line 259 of file Triple.h.
Referenced by setArchName(), and setTriple().
Triple() [2/4]
Triple::Triple (const Twine & Str) explicit
Construct a triple from the string representation provided.
This stores the string representation and parses the various pieces into enum members.
Definition at line 730 of file Triple.cpp.
References llvm::StringSwitch< T, R >::Cases(), llvm::StringSwitch< T, R >::Default(), getDefaultFormat(), GNU, GNUABI64, GNUABIN32, parseArch(), parseEnvironment(), parseFormat(), parseOS(), parseSubArch(), parseVendor(), llvm::SmallVectorBase::size(), llvm::StringRef::split(), llvm::StringSwitch< T, R >::StartsWith(), UnknownEnvironment, and UnknownObjectFormat.
Triple() [3/4]
Triple::Triple (const Twine & ArchStr, const Twine & VendorStr, const Twine & OSStr)
Construct a triple from string representations of the architecture, vendor, and OS.
This joins each argument into a canonical string representation and parses them into enum members. It leaves the environment unknown and omits it from the string representation.
Definition at line 770 of file Triple.cpp.
References getDefaultFormat().
Triple() [4/4]
Triple::Triple (const Twine & ArchStr, const Twine & VendorStr, const Twine & OSStr, const Twine & EnvironmentStr)
Construct a triple from string representations of the architecture, vendor, OS, and environment.
This joins each argument into a canonical string representation and parses them into enum members.
Definition at line 785 of file Triple.cpp.
References getDefaultFormat(), and UnknownObjectFormat.
Member Function Documentation
get32BitArchVariant()
Triple Triple::get32BitArchVariant () const
Form a triple with a 32-bit variant of the current architecture.
This can be used to move across "families" of architectures where useful.
Returns
A new triple with a 32-bit architecture or an unknown architecture if no such variant can be found.
Definition at line 1310 of file Triple.cpp.
References aarch64, aarch64_32, aarch64_be, amdgcn, amdil, amdil64, arc, arm, armeb, avr, bpfeb, bpfel, getArch(), hexagon, hsail, hsail64, kalimba, lanai, le32, le64, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, renderscript32, renderscript64, riscv32, riscv64, setArch(), shave, sparc, sparcel, sparcv9, spir, spir64, systemz, llvm::T, tce, tcele, thumb, thumbeb, UnknownArch, ve, wasm32, wasm64, x86, x86_64, and xcore.
Referenced by llvm::sys::getProcessTriple(), and hasDefaultEmulatedTLS().
get64BitArchVariant()
Triple Triple::get64BitArchVariant () const
Form a triple with a 64-bit variant of the current architecture.
This can be used to move across "families" of architectures where useful.
Returns
A new triple with a 64-bit architecture or an unknown architecture if no such variant can be found.
Definition at line 1375 of file Triple.cpp.
References aarch64, aarch64_32, aarch64_be, amdgcn, amdil, amdil64, arc, arm, armeb, avr, bpfeb, bpfel, getArch(), hexagon, hsail, hsail64, kalimba, lanai, le32, le64, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, renderscript32, renderscript64, riscv32, riscv64, setArch(), shave, sparc, sparcel, sparcv9, spir, spir64, systemz, llvm::T, tce, tcele, thumb, thumbeb, UnknownArch, ve, wasm32, wasm64, x86, x86_64, and xcore.
Referenced by llvm::sys::getProcessTriple(), and hasDefaultEmulatedTLS().
getArch()
ArchType llvm::Triple::getArch () const inline
getArch - Get the parsed architecture type of this triple.
Definition at line 297 of file Triple.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::AArch64TargetMachine::AArch64TargetMachine(), adjustFixupValue(), adjustInlineAsm(), llvm::AMDGPUMCAsmInfo::AMDGPUMCAsmInfo(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), calcArraySize(), canReuseBoundaryAlignFragment(), llvm::LTOCodeGenerator::compile(), computeDataLayout(), computeFSAdditions(), computeTargetABI(), createAArch64MCAsmInfo(), createAMDGPUMCInstPrinter(), createAMDGPUMCRegisterInfo(), createAMDGPUMCSubtargetInfo(), createELFStreamer(), llvm::orc::createLocalCompileCallbackManager(), llvm::orc::createLocalIndirectStubsManagerBuilder(), llvm::orc::createLocalLazyCallThroughManager(), llvm::X86TargetMachine::createPassConfig(), createPPCMCAsmInfo(), createPPCMCRegisterInfo(), createSparcMCSubtargetInfo(), createTLOF(), createX86MCAsmInfo(), createX86MCRegisterInfo(), darwinHasSinCos(), emitDarwinBCHeaderAndTrailer(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::X86_MC::X86MCInstrAnalysis::findPltEntries(), FixedPointIntrinsicToOpcode(), llvm::AMDGPUSubtarget::get(), get32BitArchVariant(), get64BitArchVariant(), getBigEndianArchVariant(), getBitcodeFileMachine(), getCOFFSectionFlags(), getDataLayoutString(), getDefaultFormat(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::X86_MC::getDwarfRegFlavour(), getEffectiveRelocModel(), getGPUOrDefault(), getiOSVersion(), getLittleEndianArchVariant(), llvm::DataLayout::getManglingComponent(), llvm::AMDGPUMCAsmInfo::getMaxInstLength(), llvm::AMDGPU::IsaInfo::getMaxWorkGroupsPerCU(), llvm::AMDGPU::getMCReg(), getShadowMapping(), llvm::GCNTargetMachine::getTargetTransformInfo(), llvm::handleExecNameEncodedBEOpts(), hasSinCosPiStret(), llvm::TargetLoweringObjectFileELF::Initialize(), initialize(), INITIALIZE_PASS(), llvm::GCNSubtarget::initializeSubtargetDependencies(), isAArch64(), isArch16Bit(), isArch32Bit(), isArch64Bit(), isARM(), isCompatibleWith(), isLittleEndian(), isMIPS32(), isMIPS64(), isNVPTX(), llvm::PPCTargetMachine::isPPC64(), isPPC64(), isPS4CPU(), isRISCV(), isSPIR(), isThumb(), isVE(), isX86(), loadBinaryFormat(), llvm::TargetRegistry::lookupTarget(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), parseBitcodeFileImpl(), llvm::X86_MC::ParseX86Triple(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::PPCSubtarget::PPCSubtarget(), llvm::MCSectionELF::PrintSwitchToSection(), RetagMask(), selectJumpTableArmEncoding(), llvm::FastISel::selectXRayCustomEvent(), llvm::FastISel::selectXRayTypedEvent(), llvm::TargetMachine::shouldAssumeDSOLocal(), llvm::AMDGPU::shouldEmitConstantsToTextSection(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), TypeSizeToSizeIndex(), useCompactUnwind(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
getArchName()
StringRef Triple::getArchName () const
getArchName - Get the architecture (first) component of the triple.
Definition at line 994 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by llvm::ARM::computeDefaultTargetABI(), createARMAsmBackend(), llvm::createX86_64AsmBackend(), dumpUUID(), getARMCPUForArch(), getTriple(), llvm::ARMSubtarget::isXRaySupported(), llvm::MachO::mapToArchitecture(), llvm::ARM_MC::ParseARMTriple(), setEnvironmentName(), setOSAndEnvironmentName(), setOSName(), and setVendorName().
getArchTypeForLLVMName()
Triple::ArchType Triple::getArchTypeForLLVMName (StringRef Str) static
getArchTypeForLLVMName - The canonical type for the given LLVM architecture name (e.g., "x86").
Definition at line 264 of file Triple.cpp.
References aarch64, aarch64_32, aarch64_be, amdgcn, amdil, amdil64, arc, arm, armeb, avr, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), hexagon, hsail, hsail64, kalimba, lanai, le32, le64, mips, mips64, mips64el, mipsel, msp430, Name, nvptx, nvptx64, parseBPFArch(), ppc, ppc64, ppc64le, r600, renderscript32, renderscript64, riscv32, riscv64, shave, sparc, sparcel, sparcv9, spir, spir64, llvm::StringSwitch< T, R >::StartsWith(), systemz, tce, tcele, thumb, thumbeb, UnknownArch, ve, wasm32, wasm64, x86, x86_64, and xcore.
Referenced by hasDefaultEmulatedTLS(), llvm::TargetRegistry::lookupTarget(), and llvm::EngineBuilder::selectTarget().
getArchTypeName()
StringRef Triple::getArchTypeName (ArchType Kind) static
getArchTypeName - Get the canonical name for the Kind architecture.
Definition at line 19 of file Triple.cpp.
References aarch64, aarch64_32, aarch64_be, amdgcn, amdil, amdil64, arc, arm, armeb, avr, bpfeb, bpfel, hexagon, hsail, hsail64, kalimba, lanai, le32, le64, llvm_unreachable, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, renderscript32, renderscript64, riscv32, riscv64, shave, sparc, sparcel, sparcv9, spir, spir64, systemz, tce, tcele, thumb, thumbeb, UnknownArch, ve, wasm32, wasm64, x86, x86_64, and xcore.
Referenced by hasDefaultEmulatedTLS(), and setArch().
getArchTypePrefix()
StringRef Triple::getArchTypePrefix (ArchType Kind) static
getArchTypePrefix - Get the "prefix" canonical name for the Kind architecture.
This is the prefix used by the architecture specific builtins, and is suitable for passing to
See also
Intrinsic::getIntrinsicForGCCBuiltin().
Returns
- The architecture prefix, or 0 if none is defined.
Definition at line 79 of file Triple.cpp.
References aarch64, aarch64_32, aarch64_be, amdgcn, amdil, amdil64, arc, arm, armeb, avr, bpfeb, bpfel, hexagon, hsail, hsail64, kalimba, lanai, le32, le64, mips, mips64, mips64el, mipsel, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, riscv32, riscv64, shave, sparc, sparcel, sparcv9, spir, spir64, systemz, thumb, thumbeb, ve, wasm32, wasm64, x86, x86_64, and xcore.
Referenced by hasDefaultEmulatedTLS(), and llvm::RuntimeDyldELF::loadObject().
getARMCPUForArch()
StringRef Triple::getARMCPUForArch (StringRef Arch = StringRef()) const
Get the (LLVM) name of the minimum ARM CPU for the arch we are targeting.
Parameters
Arch the architecture name (e.g., "armv7s"). If it is an empty string then the triple's arch name is used.
Definition at line 1605 of file Triple.cpp.
References EABI, EABIHF, llvm::StringRef::empty(), llvm::StringRef::equals(), FreeBSD, getArchName(), llvm::ARM::getCanonicalArchName(), llvm::ARM::getDefaultCPU(), getEnvironment(), getOS(), GNUEABI, GNUEABIHF, IOS, llvm_unreachable, MacOSX, MuslEABIHF, NaCl, NetBSD, OpenBSD, TvOS, WatchOS, and Win32.
Referenced by hasDefaultEmulatedTLS().
getBigEndianArchVariant()
Triple Triple::getBigEndianArchVariant () const
Form a triple with a big endian variant of the current architecture.
This can be used to move across "families" of architectures where useful.
Returns
A new triple with a big endian architecture or an unknown architecture if no such variant can be found.
Definition at line 1440 of file Triple.cpp.
References aarch64, aarch64_be, amdgcn, amdil, amdil64, arm, avr, bpfeb, bpfel, getArch(), hexagon, hsail, hsail64, isLittleEndian(), kalimba, le32, le64, llvm_unreachable, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc64, ppc64le, r600, renderscript32, renderscript64, riscv32, riscv64, setArch(), shave, sparc, sparcel, spir, spir64, llvm::T, tce, tcele, thumb, UnknownArch, ve, wasm32, wasm64, x86, x86_64, and xcore.
Referenced by hasDefaultEmulatedTLS().
getEnvironment()
EnvironmentType llvm::Triple::getEnvironment () const inline
getEnvironment - Get the parsed environment type of this triple.
Definition at line 315 of file Triple.h.
References getEnvironmentVersion().
Referenced by llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), computeDataLayout(), llvm::ARM::computeDefaultTargetABI(), llvm::MipsABIInfo::computeTargetABI(), llvm::createX86_64AsmBackend(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), getARMCPUForArch(), getEnvironmentVersion(), isAndroid(), isCompatibleWith(), isGNUEnvironment(), isKnownWindowsMSVCEnvironment(), isMacCatalystEnvironment(), isMusl(), isSimulatorEnvironment(), llvm::X86Subtarget::isTarget64BitILP32(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::ARMSubtarget::isTargetAEABI(), llvm::ARMSubtarget::isTargetEHABICompatible(), llvm::ARMSubtarget::isTargetGNUAEABI(), llvm::ARMBaseTargetMachine::isTargetHardFloat(), llvm::ARMSubtarget::isTargetMuslAEABI(), isWindowsCoreCLREnvironment(), isWindowsCygwinEnvironment(), isWindowsGNUEnvironment(), isWindowsItaniumEnvironment(), isWindowsMSVCEnvironment(), llvm::MachO::mapToPlatformKind(), llvm::X86_MC::ParseX86Triple(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), and llvm::X86RegisterInfo::X86RegisterInfo().
getEnvironmentName()
StringRef Triple::getEnvironmentName () const
getEnvironmentName - Get the optional environment (fourth) component of the triple, or "" if empty.
Definition at line 1009 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by getEnvironmentVersion(), getTriple(), hasEnvironment(), and setOSName().
getEnvironmentTypeName()
StringRef Triple::getEnvironmentTypeName (EnvironmentType Kind) static
getEnvironmentTypeName - Get the canonical name for the Kind environment.
Definition at line 222 of file Triple.cpp.
References Android, CODE16, CoreCLR, Cygnus, EABI, EABIHF, GNU, GNUABI64, GNUABIN32, GNUEABI, GNUEABIHF, GNUX32, Itanium, llvm_unreachable, MacABI, MSVC, Musl, MuslEABI, MuslEABIHF, Simulator, and UnknownEnvironment.
Referenced by getEnvironmentVersion(), hasDefaultEmulatedTLS(), setEnvironment(), and setObjectFormat().
getEnvironmentVersion()
void Triple::getEnvironmentVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
Parse the version number from the OS name component of the triple, if present.
For example, "fooos1.2.3" would return (1, 2, 3).
If an entry is not defined, it will be returned as 0.
Definition at line 1055 of file Triple.cpp.
References getEnvironment(), getEnvironmentName(), getEnvironmentTypeName(), parseVersionFromName(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by getEnvironment(), initialize(), and isAndroidVersionLT().
getiOSVersion()
void Triple::getiOSVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
getiOSVersion - Parse the version number as with getOSVersion.
This should only be called with IOS or generic triples.
Definition at line 1119 of file Triple.cpp.
References aarch64, Darwin, getArch(), getOS(), getOSVersion(), IOS, llvm_unreachable, MacOSX, TvOS, and WatchOS.
Referenced by llvm::MCStreamer::EmitVersionForTarget(), getOSMajorVersion(), and llvm::AArch64Subtarget::supportsAddressTopByteIgnored().
getLittleEndianArchVariant()
Triple Triple::getLittleEndianArchVariant () const
Form a triple with a little endian variant of the current architecture.
This can be used to move across "families" of architectures where useful.
Returns
A new triple with a little endian architecture or an unknown architecture if no such variant can be found.
Definition at line 1495 of file Triple.cpp.
References aarch64, aarch64_be, armeb, bpfeb, bpfel, getArch(), isLittleEndian(), lanai, llvm_unreachable, mips, mips64, mips64el, mipsel, ppc, ppc64, ppc64le, setArch(), sparc, sparcel, sparcv9, systemz, llvm::T, tce, tcele, thumbeb, and UnknownArch.
Referenced by hasDefaultEmulatedTLS().
getMacOSXVersion()
bool Triple::getMacOSXVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
getMacOSXVersion - Parse the version number as with getOSVersion and then translate generic "darwin" versions to the corresponding OS X versions.
This may also be called with IOS triples but the OS X version number is just set to a constant 10.4.0 in that case. Returns true if successful.
Definition at line 1078 of file Triple.cpp.
References Darwin, getOS(), getOSVersion(), IOS, llvm_unreachable, MacOSX, TvOS, and WatchOS.
Referenced by llvm::MCStreamer::EmitVersionForTarget(), and getOSMajorVersion().
getObjectFormat()
ObjectFormatType llvm::Triple::getObjectFormat () const inline
getFormat - Get the object format for this triple.
Definition at line 327 of file Triple.h.
References getOSVersion().
Referenced by createARMAsmBackend(), llvm::jitlink::createEHFrameRecorderPass(), llvm::Target::createMCObjectStreamer(), getSectionNameForBitcode(), getSectionNameForCommandline(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), isCompatibleWith(), isOSBinFormatCOFF(), isOSBinFormatELF(), isOSBinFormatMachO(), isOSBinFormatWasm(), isOSBinFormatXCOFF(), and llvm::ARMTargetLowering::isReadOnly().
getOS()
OSType llvm::Triple::getOS () const inline
getOS - Get the parsed operating system type of this triple.
Definition at line 306 of file Triple.h.
Referenced by adjustFixupValue(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), buildPCRelGlobalAddress(), llvm::ARM::computeDefaultTargetABI(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createARMAsmBackend(), llvm::createAVRAsmBackend(), llvm::createHexagonAsmBackend(), llvm::createLanaiAsmBackend(), llvm::orc::createLocalCompileCallbackManager(), llvm::orc::createLocalIndirectStubsManagerBuilder(), llvm::orc::createLocalLazyCallThroughManager(), llvm::createMipsELFObjectWriter(), llvm::createRISCVAsmBackend(), llvm::createSparcAsmBackend(), llvm::createSystemZMCAsmBackend(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), llvm::AMDGPUAsmPrinter::doFinalization(), llvm::AMDGPUAsmPrinter::EmitEndOfAsmFile(), llvm::AMDGPUAsmPrinter::EmitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::EmitFunctionEntryLabel(), llvm::AMDGPUAsmPrinter::EmitGlobalVariable(), llvm::AMDGPUAsmPrinter::EmitStartOfAsmFile(), getARMCPUForArch(), getDataLayoutString(), getFixupKindNumBytes(), getGPUOrDefault(), getiOSVersion(), getMacOSXVersion(), getOSVersion(), getWatchOSVersion(), llvm::AMDGPU::IsaInfo::hasCodeObjectV3(), initialize(), llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::AMDGPUSubtarget::isAmdPalOS(), isCompatibleWith(), isiOS(), isMacOSX(), isMacOSXVersionLT(), llvm::AMDGPUSubtarget::isMesa3DOS(), isOSAIX(), isOSContiki(), isOSDragonFly(), isOSEmscripten(), isOSFreeBSD(), isOSFuchsia(), isOSGlibc(), isOSHaiku(), isOSHurd(), isOSIAMCU(), isOSKFreeBSD(), isOSLinux(), isOSNaCl(), isOSNetBSD(), isOSOpenBSD(), isOSSolaris(), isOSUnknown(), isOSWASI(), isOSWindows(), isPS4(), isPS4CPU(), isSDKVersionToken(), isTvOS(), isWatchOS(), llvm::MachO::mapToPlatformKind(), llvm::NVPTXTargetMachine::NVPTXTargetMachine(), llvm::PPCInstPrinter::printTLSCall(), and llvm::AMDGPU::shouldEmitConstantsToTextSection().
getOSAndEnvironmentName()
StringRef Triple::getOSAndEnvironmentName () const
getOSAndEnvironmentName - Get the operating system and optional environment components as a single string (separated by a '-' if the environment component is present).
Definition at line 1015 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by getTriple(), setArchName(), and setVendorName().
getOSMajorVersion()
unsigned llvm::Triple::getOSMajorVersion () const inline
getOSMajorVersion - Return just the major version number, this is specialized because it is a common query.
Definition at line 339 of file Triple.h.
References getiOSVersion(), getMacOSXVersion(), getOSVersion(), and getWatchOSVersion().
Referenced by llvm::MCStreamer::EmitVersionForTarget(), and llvm::PPCSubtarget::PPCSubtarget().
getOSName()
StringRef Triple::getOSName () const
getOSName - Get the operating system (third) component of the triple.
Definition at line 1003 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by getOSVersion(), getTriple(), isSDKVersionToken(), and setEnvironmentName().
getOSTypeName()
StringRef Triple::getOSTypeName (OSType Kind) static
getOSTypeName - Get the canonical name for the Kind operating system.
Definition at line 178 of file Triple.cpp.
References AIX, AMDHSA, AMDPAL, Ananas, CloudABI, CNK, Contiki, CUDA, Darwin, DragonFly, ELFIAMCU, Emscripten, FreeBSD, Fuchsia, Haiku, HermitCore, Hurd, IOS, KFreeBSD, Linux, llvm_unreachable, Lv2, MacOSX, Mesa3D, Minix, NaCl, NetBSD, NVCL, OpenBSD, PS4, RTEMS, Solaris, TvOS, UnknownOS, WASI, WatchOS, and Win32.
Referenced by getOSVersion(), hasDefaultEmulatedTLS(), and setOS().
getOSVersion()
void Triple::getOSVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
getOSVersion - Parse the version number from the OS name component of the triple, if present.
For example, "fooos1.2.3" would return (1, 2, 3).
If an entry is not defined, it will be returned as 0.
Definition at line 1065 of file Triple.cpp.
References llvm::StringRef::consume_front(), getOS(), getOSName(), getOSTypeName(), MacOSX, parseVersionFromName(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by getiOSVersion(), getMacOSXVersion(), getObjectFormat(), getOSMajorVersion(), getWatchOSVersion(), and isOSVersionLT().
getSubArch()
SubArchType llvm::Triple::getSubArch () const inline
getSubArch - get the parsed subarchitecture type for this triple.
Definition at line 300 of file Triple.h.
Referenced by llvm::ARMAsmPrinter::getISAEncoding(), isCompatibleWith(), llvm::ARMBaseTargetMachine::isTargetHardFloat(), isWatchABI(), llvm::PPCSubtarget::PPCSubtarget(), llvm::MIPS_MC::selectMipsCPU(), and llvm::object::ELFObjectFileBase::setARMSubArch().
getTriple()
const std::string& llvm::Triple::getTriple () const inline
Definition at line 368 of file Triple.h.
References getArchName(), getEnvironmentName(), getOSAndEnvironmentName(), getOSName(), getVendorName(), isArch16Bit(), isArch32Bit(), and isArch64Bit().
Referenced by llvm::orc::JITTargetMachineBuilder::createTargetMachine(), llvm::TargetRegistry::lookupTarget(), and llvm::EngineBuilder::selectTarget().
getVendor()
VendorType llvm::Triple::getVendor () const inline
getVendor - Get the parsed vendor type of this triple.
Definition at line 303 of file Triple.h.
Referenced by llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), getShadowMapping(), llvm::PPCSubtarget::isBGQ(), isCompatibleWith(), isPS4(), isPS4CPU(), and merge().
getVendorName()
StringRef Triple::getVendorName () const
getVendorName - Get the vendor (second) component of the triple.
Definition at line 998 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by getTriple(), setArchName(), setEnvironmentName(), setOSAndEnvironmentName(), and setOSName().
getVendorTypeName()
StringRef Triple::getVendorTypeName (VendorType Kind) static
getVendorTypeName - Get the canonical name for the Kind vendor.
Definition at line 153 of file Triple.cpp.
References AMD, Apple, BGP, BGQ, CSR, Freescale, IBM, ImaginationTechnologies, llvm_unreachable, Mesa, MipsTechnologies, Myriad, NVIDIA, OpenEmbedded, PC, SCEI, SUSE, and UnknownVendor.
Referenced by hasDefaultEmulatedTLS(), and setVendor().
getWatchOSVersion()
void Triple::getWatchOSVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
getWatchOSVersion - Parse the version number as with getOSVersion.
This should only be called with WatchOS or generic triples.
Definition at line 1145 of file Triple.cpp.
References Darwin, getOS(), getOSVersion(), IOS, llvm_unreachable, MacOSX, and WatchOS.
Referenced by llvm::MCStreamer::EmitVersionForTarget(), and getOSMajorVersion().
hasDefaultEmulatedTLS()
bool llvm::Triple::hasDefaultEmulatedTLS () const inline
Tests whether the target uses emulated TLS as default.
Definition at line 750 of file Triple.h.
References get32BitArchVariant(), get64BitArchVariant(), getArchTypeForLLVMName(), getArchTypeName(), getArchTypePrefix(), getARMCPUForArch(), getBigEndianArchVariant(), getEnvironmentTypeName(), getLittleEndianArchVariant(), getOSTypeName(), getVendorTypeName(), isAndroid(), isCompatibleWith(), isLittleEndian(), isOSOpenBSD(), isWindowsCygwinEnvironment(), merge(), llvm::Other, setArch(), setArchName(), setEnvironment(), setEnvironmentName(), setObjectFormat(), setOS(), setOSAndEnvironmentName(), setOSName(), setTriple(), setVendor(), and setVendorName().
Referenced by llvm::TargetMachine::useEmulatedTLS().
hasEnvironment()
bool llvm::Triple::hasEnvironment () const inline
hasEnvironment - Does this triple have the optional environment (fourth) component?
Definition at line 310 of file Triple.h.
References getEnvironmentName().
Referenced by setOSName().
isAArch64()
bool llvm::Triple::isAArch64 () const inline
Tests whether the target is AArch64 (little and big endian).
Definition at line 705 of file Triple.h.
References aarch64, aarch64_be, and getArch().
Referenced by RetagMask(), TypeSizeToSizeIndex(), and llvm::WinException::WinException().
isAndroid()
bool llvm::Triple::isAndroid () const inline
Tests whether the target is Android.
Definition at line 662 of file Triple.h.
References Android, and getEnvironment().
Referenced by createELFStreamer(), darwinHasSinCos(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), getShadowMapping(), hasDefaultEmulatedTLS(), hasStackGuardSlotTLS(), initialize(), isAndroidVersionLT(), isOSGlibc(), llvm::AArch64Subtarget::isTargetAndroid(), llvm::ARMSubtarget::isTargetAndroid(), llvm::X86Subtarget::isTargetAndroid(), llvm::AArch64::isX18ReservedByDefault(), RetagMask(), and llvm::HWAddressSanitizerPass::run().
isAndroidVersionLT()
bool llvm::Triple::isAndroidVersionLT (unsigned Major) const inline
Definition at line 664 of file Triple.h.
References assert(), getEnvironmentVersion(), isAndroid(), and isArch64Bit().
Referenced by darwinHasSinCos(), getShadowMapping(), hasStackGuardSlotTLS(), initialize(), and llvm::HWAddressSanitizerPass::run().
isArch16Bit()
bool Triple::isArch16Bit () const
Test whether the architecture is 16-bit.
Note that this tests for 16-bit pointer width, and nothing else.
Definition at line 1306 of file Triple.cpp.
References getArch(), and getArchPointerBitWidth().
Referenced by getTriple().
isArch32Bit()
bool Triple::isArch32Bit () const
Test whether the architecture is 32-bit.
Note that this tests for 32-bit pointer width, and nothing else.
Definition at line 1302 of file Triple.cpp.
References getArch(), and getArchPointerBitWidth().
Referenced by computeDataLayout(), llvm::createAArch64leAsmBackend(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), getEffectivePPCCodeModel(), llvm::sys::getProcessTriple(), getTriple(), and llvm::AArch64Subtarget::isTargetILP32().
isArch64Bit()
bool Triple::isArch64Bit () const
Test whether the architecture is 64-bit.
Note that this tests for 64-bit pointer width, and nothing else. Note that we intentionally expose only three predicates, 64-bit, 32-bit, and 16-bit. The inner details of pointer width for particular architectures is not summed up in the triple, and so only a coarse grained predicate system is provided.
Definition at line 1298 of file Triple.cpp.
References getArch(), and getArchPointerBitWidth().
Referenced by computeDataLayout(), llvm::RISCVABI::computeTargetABI(), llvm::createMipsELFObjectWriter(), llvm::createRISCVAsmBackend(), createRISCVMCSubtargetInfo(), llvm::createWebAssemblyAsmBackend(), darwinHasSinCos(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), getEffectivePPCCodeModel(), getFixupKindNumBytes(), llvm::WebAssemblyRegisterInfo::getFrameRegister(), llvm::sys::getProcessTriple(), getTriple(), llvm::WebAssemblySubtarget::hasAddr64(), isAndroidVersionLT(), llvm::RISCVMCAsmInfo::RISCVMCAsmInfo(), llvm::RISCVFeatures::validate(), llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo(), and llvm::X86RegisterInfo::X86RegisterInfo().
isARM()
bool llvm::Triple::isARM () const inline
Tests whether the target is ARM (little and big endian).
Definition at line 700 of file Triple.h.
References arm, armeb, and getArch().
Referenced by getShadowMapping(), and llvm::MCSectionELF::PrintSwitchToSection().
isCompatibleWith()
bool Triple::isCompatibleWith (const Triple & Other) const
Test whether target triples are compatible.
Definition at line 1572 of file Triple.cpp.
References Apple, arm, armeb, getArch(), getEnvironment(), getObjectFormat(), getOS(), getSubArch(), getVendor(), llvm::Other, thumb, and thumbeb.
Referenced by hasDefaultEmulatedTLS().
isGNUEnvironment()
bool llvm::Triple::isGNUEnvironment () const inline
Definition at line 522 of file Triple.h.
References getEnvironment(), GNU, GNUABI64, GNUABIN32, GNUEABI, GNUEABIHF, and GNUX32.
Referenced by darwinHasSinCos(), hasBcmp(), and initialize().
isiOS()
bool llvm::Triple::isiOS () const inline
Is this an iOS triple.
Note: This identifies tvOS as a variant of iOS. If that ever changes, i.e., if the two operating systems diverge or their version numbers get out of sync, that will need to be changed. watchOS has completely different version numbers so it is not included.
Definition at line 463 of file Triple.h.
References getOS(), IOS, and isTvOS().
Referenced by darwinHasSinCos(), getShadowMapping(), hasSinCosPiStret(), initialize(), isOSDarwin(), llvm::AArch64Subtarget::isTargetIOS(), llvm::ARMSubtarget::isTargetIOS(), llvm::AArch64Subtarget::supportsAddressTopByteIgnored(), and useCompactUnwind().
isKnownWindowsMSVCEnvironment()
bool llvm::Triple::isKnownWindowsMSVCEnvironment () const inline
Checks if the environment is MSVC.
Definition at line 544 of file Triple.h.
References getEnvironment(), isOSWindows(), and MSVC.
Referenced by initialize(), and isWindowsMSVCEnvironment().
isLittleEndian()
bool Triple::isLittleEndian () const
Tests whether the target triple is little endian.
Returns
true if the triple is little endian, false otherwise.
Definition at line 1527 of file Triple.cpp.
References aarch64, aarch64_32, amdgcn, amdil, amdil64, arm, avr, bpfel, getArch(), hexagon, hsail, hsail64, kalimba, le32, le64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc64le, r600, renderscript32, renderscript64, riscv32, riscv64, shave, sparcel, spir, spir64, tcele, thumb, ve, wasm32, wasm64, x86, x86_64, and xcore.
Referenced by getBigEndianArchVariant(), getFixupKindNumBytes(), getLittleEndianArchVariant(), hasDefaultEmulatedTLS(), lowerMSASplatZExt(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), and truncateVecElts().
isMacCatalystEnvironment()
bool llvm::Triple::isMacCatalystEnvironment () const inline
Definition at line 490 of file Triple.h.
References getEnvironment(), and MacABI.
Referenced by llvm::MCStreamer::EmitVersionForTarget().
isMacOSX()
bool llvm::Triple::isMacOSX () const inline
isMacOSX - Is this a Mac OS X triple.
For legacy reasons, we support both "darwin" and "osx" as OS X triples.
Definition at line 454 of file Triple.h.
References Darwin, getOS(), and MacOSX.
Referenced by computeTargetABI(), darwinHasSinCos(), llvm::MCStreamer::EmitVersionForTarget(), hasSinCosPiStret(), initialize(), llvm::PPCSubtarget::isDarwin(), isMacOSXVersionLT(), isOSDarwin(), useCompactUnwind(), and llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
isMacOSXVersionLT()
bool llvm::Triple::isMacOSXVersionLT (unsigned Major, unsigned Minor = 0, unsigned Micro = 0) const inline
isMacOSXVersionLT - Comparison function for checking OS X version compatibility, which handles supporting skewed version numbering schemes used by the "darwin" triples.
Definition at line 439 of file Triple.h.
References assert(), getOS(), isMacOSX(), isOSVersionLT(), and MacOSX.
Referenced by darwinHasSinCos(), hasSinCosPiStret(), initialize(), useCompactUnwind(), and llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
isMIPS()
bool llvm::Triple::isMIPS () const inline
Tests whether the target is MIPS (little and big endian, 32- or 64-bit).
Definition at line 720 of file Triple.h.
References isMIPS32(), and isMIPS64().
Referenced by initialize(), and useCompactUnwind().
isMIPS32()
bool llvm::Triple::isMIPS32 () const inline
Tests whether the target is MIPS 32-bit (little and big endian).
Definition at line 710 of file Triple.h.
References getArch(), mips, and mipsel.
Referenced by getShadowMapping(), isMIPS(), and llvm::MIPS_MC::selectMipsCPU().
isMIPS64()
bool llvm::Triple::isMIPS64 () const inline
Tests whether the target is MIPS 64-bit (little and big endian).
Definition at line 715 of file Triple.h.
References getArch(), mips64, and mips64el.
Referenced by llvm::MipsABIInfo::computeTargetABI(), getShadowMapping(), isMIPS(), and llvm::MipsMCAsmInfo::MipsMCAsmInfo().
isMusl()
bool llvm::Triple::isMusl () const inline
Tests whether the environment is musl-libc.
Definition at line 678 of file Triple.h.
References getEnvironment(), Musl, MuslEABI, and MuslEABIHF.
Referenced by hasBcmp(), initialize(), and llvm::PPCSubtarget::PPCSubtarget().
isNVPTX()
bool llvm::Triple::isNVPTX () const inline
Tests whether the target is NVPTX (32- or 64-bit).
Definition at line 690 of file Triple.h.
References getArch(), nvptx, and nvptx64.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfCompileUnit::constructLabelDIE(), llvm::DwarfDebug::DwarfDebug(), initialize(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
isOSAIX()
bool llvm::Triple::isOSAIX () const inline
Tests whether the OS is AIX.
Definition at line 619 of file Triple.h.
References AIX, and getOS().
Referenced by createPPCAsmPrinterPass(), createTLOF(), getDefaultFormat(), getEffectivePPCCodeModel(), llvm::PPCSubtarget::isAIXABI(), llvm::PPCInstPrinter::printInst(), and llvm::AsmPrinter::SetupMachineFunction().
isOSBinFormatCOFF()
bool llvm::Triple::isOSBinFormatCOFF () const inline
Tests whether the OS uses the COFF binary format.
Definition at line 629 of file Triple.h.
References COFF, and getObjectFormat().
Referenced by adjustFixupValue(), computeDataLayout(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), llvm::createAArch64ObjectTargetStreamer(), createTLOF(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), llvm::createX86ObjectTargetStreamer(), llvm::AsmPrinter::doFinalization(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::AsmPrinter::EmitFunctionBody(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::DataLayout::getManglingComponent(), llvm::GetOrCreateFunctionComdat(), llvm::AArch64Subtarget::isTargetCOFF(), llvm::ARMSubtarget::isTargetCOFF(), llvm::X86Subtarget::isTargetCOFF(), llvm::AArch64MCInstLower::LowerSymbolOperand(), and llvm::TargetMachine::shouldAssumeDSOLocal().
isOSBinFormatELF()
bool llvm::Triple::isOSBinFormatELF () const inline
Tests whether the OS uses the ELF binary format.
Definition at line 624 of file Triple.h.
References ELF, and getObjectFormat().
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), adjustFixupValue(), appendEndToFunction(), canReuseBoundaryAlignFragment(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), llvm::createAArch64ObjectTargetStreamer(), createARMAsmBackend(), llvm::createARMObjectTargetStreamer(), llvm::createLanaiAsmBackend(), createMCStreamer(), llvm::createMSP430ObjectTargetStreamer(), createObjectTargetStreamer(), createRISCVObjectTargetStreamer(), createTLOF(), createX86MCAsmInfo(), llvm::AsmPrinter::doFinalization(), llvm::DwarfDebug::DwarfDebug(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::AsmPrinter::emitXRayTable(), getEffectiveAArch64CodeModel(), getEffectivePPCCodeModel(), getEffectiveRelocModel(), llvm::GetOrCreateFunctionComdat(), llvm::AArch64RegisterInfo::getTLSCallPreservedMask(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::SystemZSubtarget::isTargetELF(), llvm::MipsSubtarget::isTargetELF(), llvm::PPCSubtarget::isTargetELF(), llvm::AArch64Subtarget::isTargetELF(), llvm::ARMSubtarget::isTargetELF(), llvm::X86Subtarget::isTargetELF(), llvm::AArch64MCInstLower::LowerSymbolOperand(), MatchingStackOffset(), mayTailCallThisCC(), llvm::TargetMachine::shouldAssumeDSOLocal(), and TypeSizeToSizeIndex().
isOSBinFormatMachO()
bool llvm::Triple::isOSBinFormatMachO () const inline
Tests whether the environment is MachO.
Definition at line 634 of file Triple.h.
References getObjectFormat(), and MachO.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), computeAccelTableKind(), computeDataLayout(), llvm::ARM::computeDefaultTargetABI(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), createARMMCAsmInfo(), createARMMCRelocationInfo(), createTLOF(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), createX86MCAsmInfo(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::MCStreamer::EmitVersionForTarget(), llvm::AsmPrinter::emitXRayTable(), getEffectiveRelocModel(), llvm::ARMAsmPrinter::getISAEncoding(), llvm::DataLayout::getManglingComponent(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::ARMBaseTargetMachine::isTargetHardFloat(), llvm::PPCSubtarget::isTargetMachO(), llvm::AArch64Subtarget::isTargetMachO(), llvm::ARMSubtarget::isTargetMachO(), llvm::X86Subtarget::isTargetMachO(), MatchingStackOffset(), mayTailCallThisCC(), llvm::TargetMachine::shouldAssumeDSOLocal(), supportsCOMDAT(), and llvm::X86TargetMachine::X86TargetMachine().
isOSBinFormatWasm()
bool llvm::Triple::isOSBinFormatWasm () const inline
Tests whether the OS uses the Wasm binary format.
Definition at line 639 of file Triple.h.
References getObjectFormat(), and Wasm.
Referenced by llvm::TargetMachine::shouldAssumeDSOLocal().
isOSBinFormatXCOFF()
bool llvm::Triple::isOSBinFormatXCOFF () const inline
Tests whether the OS uses the XCOFF binary format.
Definition at line 644 of file Triple.h.
References getObjectFormat(), and XCOFF.
Referenced by createObjectTargetStreamer(), llvm::createPPCAsmBackend(), createPPCMCAsmInfo(), llvm::AsmPrinter::EmitConstantPool(), llvm::AsmPrinter::EmitJumpTableInfo(), and llvm::TargetMachine::shouldAssumeDSOLocal().
isOSContiki()
bool llvm::Triple::isOSContiki () const inline
Definition at line 529 of file Triple.h.
References Contiki, and getOS().
Referenced by llvm::X86TargetLowering::getSafeStackPointerLocation().
isOSCygMing()
bool llvm::Triple::isOSCygMing () const inline
Tests for either Cygwin or MinGW OS.
Definition at line 571 of file Triple.h.
References isWindowsCygwinEnvironment(), and isWindowsGNUEnvironment().
Referenced by createX86MCAsmInfo(), llvm::X86_MC::getDwarfRegFlavour(), initialize(), llvm::X86Subtarget::isTargetCygMing(), and llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference().
isOSDarwin()
bool llvm::Triple::isOSDarwin () const inline
isOSDarwin - Is this a "Darwin" OS (macOS, iOS, tvOS or watchOS).
Definition at line 482 of file Triple.h.
References isiOS(), isMacOSX(), and isWatchOS().
Referenced by llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::LTOCodeGenerator::compile(), computeDataLayout(), computeTargetABI(), createARMMCAsmInfo(), llvm::X86TargetMachine::createPassConfig(), llvm::createPPCAsmBackend(), createTLOF(), darwinHasSinCos(), llvm::X86FrameLowering::emitEpilogue(), llvm::MCStreamer::EmitVersionForTarget(), getDataLayoutString(), getDefaultFormat(), llvm::X86_MC::getDwarfRegFlavour(), getEffectiveRelocModel(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::AArch64RegisterInfo::getTLSCallPreservedMask(), hasSinCosPiStret(), llvm::AArch64Subtarget::isTargetDarwin(), llvm::ARMSubtarget::isTargetDarwin(), llvm::X86Subtarget::isTargetDarwin(), llvm::AArch64::isX18ReservedByDefault(), llvm::AArch64MCInstLower::LowerSymbolOperand(), needsRuntimeRegistrationOfSectionRange(), parseBitcodeFileImpl(), Passv64i1ArgInRegs(), llvm::PPCInstPrinter::printTLSCall(), llvm::StackProtector::runOnFunction(), shouldLowerMemFuncForSize(), and useCompactUnwind().
isOSDragonFly()
bool llvm::Triple::isOSDragonFly () const inline
Definition at line 510 of file Triple.h.
References DragonFly, and getOS().
Referenced by llvm::X86Subtarget::isTargetDragonFly().
isOSEmscripten()
bool llvm::Triple::isOSEmscripten () const inline
Tests whether the OS is Emscripten.
Definition at line 607 of file Triple.h.
References Emscripten, and getOS().
Referenced by callingConvSupported(), llvm::createWebAssemblyAsmBackend(), GetCtorAndDtorPriority(), getEffectiveRelocModel(), and getShadowMapping().
isOSFreeBSD()
bool llvm::Triple::isOSFreeBSD () const inline
Definition at line 502 of file Triple.h.
References FreeBSD, and getOS().
Referenced by createTLOF(), getShadowMapping(), hasBcmp(), llvm::TargetLoweringObjectFileELF::Initialize(), initialize(), llvm::X86Subtarget::isTargetFreeBSD(), needsRuntimeRegistrationOfSectionRange(), and llvm::PPCSubtarget::PPCSubtarget().
isOSFuchsia()
bool llvm::Triple::isOSFuchsia () const inline
Definition at line 506 of file Triple.h.
References Fuchsia, and getOS().
Referenced by createTLOF(), darwinHasSinCos(), for(), getEffectiveAArch64CodeModel(), getShadowMapping(), hasStackGuardSlotTLS(), llvm::AArch64Subtarget::isTargetFuchsia(), llvm::X86Subtarget::isTargetFuchsia(), llvm::AArch64::isX18ReservedByDefault(), and needsRuntimeRegistrationOfSectionRange().
isOSGlibc()
bool llvm::Triple::isOSGlibc () const inline
Tests whether the OS uses glibc.
Definition at line 612 of file Triple.h.
References getOS(), Hurd, isAndroid(), KFreeBSD, and Linux.
Referenced by hasStackGuardSlotTLS(), and llvm::X86Subtarget::isTargetGlibc().
isOSHaiku()
bool llvm::Triple::isOSHaiku () const inline
Tests whether the OS is Haiku.
Definition at line 534 of file Triple.h.
References getOS(), and Haiku.
isOSHurd()
bool llvm::Triple::isOSHurd () const inline
Tests whether the OS is Hurd.
Definition at line 597 of file Triple.h.
References getOS(), and Hurd.
isOSIAMCU()
bool llvm::Triple::isOSIAMCU () const inline
Definition at line 516 of file Triple.h.
References ELFIAMCU, and getOS().
Referenced by computeDataLayout(), createTLOF(), llvm::createX86_32AsmBackend(), and llvm::X86Subtarget::isTargetMCU().
isOSKFreeBSD()
bool llvm::Triple::isOSKFreeBSD () const inline
Tests whether the OS is kFreeBSD.
Definition at line 592 of file Triple.h.
References getOS(), and KFreeBSD.
Referenced by llvm::X86Subtarget::isTargetKFreeBSD().
isOSLinux()
bool llvm::Triple::isOSLinux () const inline
Tests whether the OS is Linux.
Definition at line 587 of file Triple.h.
References getOS(), and Linux.
Referenced by createTLOF(), FixedPointIntrinsicToOpcode(), getShadowMapping(), hasBcmp(), initialize(), llvm::VESubtarget::isTargetLinux(), llvm::SparcSubtarget::isTargetLinux(), llvm::PPCSubtarget::isTargetLinux(), llvm::AArch64Subtarget::isTargetLinux(), llvm::ARMSubtarget::isTargetLinux(), llvm::X86Subtarget::isTargetLinux(), needsRuntimeRegistrationOfSectionRange(), llvm::FastISel::selectXRayCustomEvent(), and llvm::FastISel::selectXRayTypedEvent().
isOSMSVCRT()
bool llvm::Triple::isOSMSVCRT () const inline
Is this a "Windows" OS targeting a "MSVCRT.dll" environment.
Definition at line 576 of file Triple.h.
References isWindowsGNUEnvironment(), isWindowsItaniumEnvironment(), and isWindowsMSVCEnvironment().
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), computeBytesPoppedByCalleeForSRet(), getMOVL(), isSortedByValueNo(), llvm::X86TargetLowering::useStackGuardXorFP(), and llvm::X86TargetLowering::X86TargetLowering().
isOSNaCl()
bool llvm::Triple::isOSNaCl () const inline
Tests whether the OS is NaCl (Native Client)
Definition at line 582 of file Triple.h.
References getOS(), and NaCl.
Referenced by computeDataLayout(), createMCStreamer(), createTLOF(), llvm::X86Subtarget::isTarget64BitILP32(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::MipsSubtarget::isTargetNaCl(), llvm::ARMSubtarget::isTargetNaCl(), llvm::X86Subtarget::isTargetNaCl(), and llvm::ARM_MC::ParseARMTriple().
isOSNetBSD()
bool llvm::Triple::isOSNetBSD () const inline
Definition at line 494 of file Triple.h.
References getOS(), and NetBSD.
Referenced by llvm::ARM::computeDefaultTargetABI(), getShadowMapping(), llvm::ARMSubtarget::isTargetNetBSD(), needsRuntimeRegistrationOfSectionRange(), and llvm::PPCSubtarget::PPCSubtarget().
isOSOpenBSD()
bool llvm::Triple::isOSOpenBSD () const inline
Definition at line 498 of file Triple.h.
References getOS(), and OpenBSD.
Referenced by llvm::ARM::computeDefaultTargetABI(), CreatePrologue(), darwinHasSinCos(), hasDefaultEmulatedTLS(), and llvm::PPCSubtarget::PPCSubtarget().
isOSSolaris()
bool llvm::Triple::isOSSolaris () const inline
Definition at line 512 of file Triple.h.
References getOS(), and Solaris.
Referenced by createTLOF(), hasBcmp(), llvm::X86Subtarget::isTargetSolaris(), needsRuntimeRegistrationOfSectionRange(), and useCompactUnwind().
isOSUnknown()
bool llvm::Triple::isOSUnknown () const inline
Definition at line 520 of file Triple.h.
References getOS(), and UnknownOS.
isOSVersionLT() [1/2]
bool llvm::Triple::isOSVersionLT (unsigned Major, unsigned Minor = 0, unsigned Micro = 0) const inline
isOSVersionLT - Helper function for doing comparisons against version numbers included in the target triple.
Definition at line 415 of file Triple.h.
References getOSVersion().
Referenced by darwinHasSinCos(), hasSinCosPiStret(), initialize(), isMacOSXVersionLT(), isOSVersionLT(), and merge().
isOSVersionLT() [2/2]
bool llvm::Triple::isOSVersionLT (const Triple & Other) const inline
Definition at line 430 of file Triple.h.
References getOSVersion(), and isOSVersionLT().
isOSWASI()
bool llvm::Triple::isOSWASI () const inline
Tests whether the OS is WASI.
Definition at line 602 of file Triple.h.
References getOS(), and WASI.
isOSWindows()
bool llvm::Triple::isOSWindows () const inline
Tests whether the OS is Windows.
Definition at line 539 of file Triple.h.
References getOS(), and Win32.
Referenced by llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::AArch64Subtarget::ClassifyGlobalReference(), computeDataLayout(), llvm::ARM::computeDefaultTargetABI(), createARMAsmBackend(), createARMMCAsmInfo(), llvm::Target::createMCObjectStreamer(), llvm::X86TargetMachine::createPassConfig(), createTLOF(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), llvm::AsmPrinter::doInitialization(), llvm::X86FrameLowering::emitEpilogue(), llvm::AsmPrinter::EmitFunctionBody(), getDefaultFormat(), getEffectiveAArch64CodeModel(), getEffectiveRelocModel(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::DataLayout::getManglingComponent(), getShadowMapping(), initialize(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), isKnownWindowsMSVCEnvironment(), llvm::X86Subtarget::isOSWindows(), llvm::ARMBaseTargetMachine::isTargetHardFloat(), llvm::AArch64Subtarget::isTargetWindows(), llvm::ARMSubtarget::isTargetWindows(), isWindowsCoreCLREnvironment(), isWindowsCygwinEnvironment(), isWindowsGNUEnvironment(), isWindowsItaniumEnvironment(), isWindowsMSVCEnvironment(), llvm::AArch64::isX18ReservedByDefault(), MatchingStackOffset(), mayTailCallThisCC(), needsRuntimeRegistrationOfSectionRange(), llvm::ARM_MC::ParseARMTriple(), llvm::TargetMachine::shouldAssumeDSOLocal(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86RegisterInfo::X86RegisterInfo().
isPPC64()
bool llvm::Triple::isPPC64 () const inline
Tests whether the target is 64-bit PowerPC (little and big endian).
Definition at line 725 of file Triple.h.
References getArch(), ppc64, and ppc64le.
Referenced by darwinHasSinCos(), getFixupKindNumBytes(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), initialize(), and llvm::TargetMachine::shouldAssumeDSOLocal().
isPS4()
bool llvm::Triple::isPS4 () const inline
Tests whether the target is the PS4 platform.
Definition at line 656 of file Triple.h.
References getOS(), getVendor(), PS4, and SCEI.
Referenced by llvm::X86TargetMachine::X86TargetMachine().
isPS4CPU()
bool llvm::Triple::isPS4CPU () const inline
Tests whether the target is the PS4 CPU.
Definition at line 649 of file Triple.h.
References getArch(), getOS(), getVendor(), PS4, SCEI, and x86_64.
Referenced by darwinHasSinCos(), llvm::DwarfDebug::DwarfDebug(), getShadowMapping(), llvm::X86Subtarget::isTargetPS4(), and needsRuntimeRegistrationOfSectionRange().
isRISCV()
bool llvm::Triple::isRISCV () const inline
Tests whether the target is RISC-V (32- and 64-bit).
Definition at line 730 of file Triple.h.
References getArch(), riscv32, and riscv64.
isSimulatorEnvironment()
bool llvm::Triple::isSimulatorEnvironment () const inline
Definition at line 486 of file Triple.h.
References getEnvironment(), and Simulator.
Referenced by llvm::MachO::mapToPlatformKind().
isSPIR()
bool llvm::Triple::isSPIR () const inline
Tests whether the target is SPIR (32- or 64-bit).
Definition at line 685 of file Triple.h.
References getArch(), spir, and spir64.
isThumb()
bool llvm::Triple::isThumb () const inline
Tests whether the target is Thumb (little and big endian).
Definition at line 695 of file Triple.h.
References getArch(), thumb, and thumbeb.
Referenced by llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::getISAEncoding(), getShadowMapping(), llvm::ARM_MC::ParseARMTriple(), llvm::MCSectionELF::PrintSwitchToSection(), and llvm::object::ELFObjectFileBase::setARMSubArch().
isTvOS()
bool llvm::Triple::isTvOS () const inline
Is this an Apple tvOS triple.
Definition at line 468 of file Triple.h.
References getOS(), and TvOS.
Referenced by llvm::MCStreamer::EmitVersionForTarget(), and isiOS().
isVE()
bool llvm::Triple::isVE () const inline
Tests whether the target is VE.
Definition at line 740 of file Triple.h.
References getArch(), and ve.
isWatchABI()
bool llvm::Triple::isWatchABI () const inline
Definition at line 477 of file Triple.h.
References ARMSubArch_v7k, and getSubArch().
Referenced by llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::ARM::computeDefaultTargetABI(), darwinHasSinCos(), llvm::ARMSubtarget::isTargetWatchABI(), and useCompactUnwind().
isWatchOS()
bool llvm::Triple::isWatchOS () const inline
Is this an Apple watchOS triple.
Definition at line 473 of file Triple.h.
References getOS(), and WatchOS.
Referenced by llvm::MCStreamer::EmitVersionForTarget(), getShadowMapping(), initialize(), isOSDarwin(), and llvm::ARMSubtarget::isTargetWatchOS().
isWindowsCoreCLREnvironment()
bool llvm::Triple::isWindowsCoreCLREnvironment () const inline
Definition at line 554 of file Triple.h.
References CoreCLR, getEnvironment(), and isOSWindows().
Referenced by createX86MCAsmInfo(), and llvm::X86Subtarget::isTargetWindowsCoreCLR().
isWindowsCygwinEnvironment()
bool llvm::Triple::isWindowsCygwinEnvironment () const inline
Definition at line 562 of file Triple.h.
References Cygnus, getEnvironment(), and isOSWindows().
Referenced by llvm::emitLinkerFlagsForGlobalCOFF(), hasDefaultEmulatedTLS(), isOSCygMing(), and llvm::X86Subtarget::isTargetWindowsCygwin().
isWindowsGNUEnvironment()
bool llvm::Triple::isWindowsGNUEnvironment () const inline
Definition at line 566 of file Triple.h.
References getEnvironment(), GNU, and isOSWindows().
Referenced by llvm::emitLinkerFlagsForGlobalCOFF(), isOSCygMing(), isOSMSVCRT(), llvm::X86Subtarget::isTargetWindowsGNU(), and llvm::TargetMachine::shouldAssumeDSOLocal().
isWindowsItaniumEnvironment()
bool llvm::Triple::isWindowsItaniumEnvironment () const inline
Definition at line 558 of file Triple.h.
References getEnvironment(), isOSWindows(), and Itanium.
Referenced by createX86MCAsmInfo(), getCOFFStaticStructorSection(), llvm::X86TargetLowering::getSDagStackGuard(), llvm::X86TargetLowering::getSSPStackGuardCheck(), llvm::TargetLoweringObjectFileCOFF::Initialize(), llvm::X86TargetLowering::insertSSPDeclarations(), isOSMSVCRT(), and llvm::X86Subtarget::isTargetWindowsItanium().
isWindowsMSVCEnvironment()
bool llvm::Triple::isWindowsMSVCEnvironment () const inline
Checks if the environment could be MSVC.
Definition at line 549 of file Triple.h.
References getEnvironment(), isKnownWindowsMSVCEnvironment(), isOSWindows(), and UnknownEnvironment.
Referenced by computeUsesMSVCFloatingPoint(), createAArch64MCAsmInfo(), createARMMCAsmInfo(), createX86MCAsmInfo(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::emitLinkerFlagsForUsedCOFF(), getCOFFStaticStructorSection(), llvm::ARMTargetLowering::getSDagStackGuard(), llvm::X86TargetLowering::getSDagStackGuard(), llvm::ARMTargetLowering::getSSPStackGuardCheck(), llvm::X86TargetLowering::getSSPStackGuardCheck(), llvm::TargetLoweringObjectFileCOFF::Initialize(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), isOSMSVCRT(), and llvm::X86Subtarget::isTargetWindowsMSVC().
isX86()
bool llvm::Triple::isX86 () const inline
Tests whether the target is x86 (32- or 64-bit).
Definition at line 735 of file Triple.h.
References getArch(), x86, and x86_64.
Referenced by initialize(), and useCompactUnwind().
merge()
std::string Triple::merge (const Triple & Other) const
Merge target triples.
Definition at line 1596 of file Triple.cpp.
References Apple, getVendor(), isOSVersionLT(), and str().
Referenced by hasDefaultEmulatedTLS().
normalize() [1/2]
std::string Triple::normalize (StringRef Str) static
normalize - Turn an arbitrary machine specification into the canonical triple form (or something sensible that the Triple class understands if nothing better can reasonably be done).
In particular, it handles the common case in which otherwise valid components are in the wrong order.
Definition at line 799 of file Triple.cpp.
References Android, llvm::array_lengthof(), assert(), COFF, llvm::numbers::e, llvm::StringRef::empty(), llvm::empty(), getObjectFormatTypeName(), GNUEABI, llvm_unreachable, parseArch(), parseEnvironment(), parseFormat(), parseOS(), parseVendor(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorBase::size(), llvm::StringRef::split(), startswith(), llvm::StringRef::startswith(), llvm::Twine::str(), SUSE, std::swap(), UnknownArch, UnknownEnvironment, UnknownObjectFormat, UnknownOS, UnknownVendor, and Win32.
normalize() [2/2]
std::string llvm::Triple::normalize () const inline
Return the normalized form of this triple's string.
Definition at line 290 of file Triple.h.
References normalize().
Referenced by llvm::sys::getProcessTriple(), LLVMNormalizeTargetTriple(), normalize(), and operator!=().
operator!=()
bool llvm::Triple::operator!= (const Triple & Other) const inline
Definition at line 275 of file Triple.h.
References normalize(), and llvm::Other.
operator==()
bool llvm::Triple::operator== (const Triple & Other) const inline
Definition at line 268 of file Triple.h.
setArch()
void Triple::setArch (ArchType Kind)
setArch - Set the architecture (first) component of the triple to a known type.
Definition at line 1173 of file Triple.cpp.
References getArchTypeName(), and setArchName().
Referenced by get32BitArchVariant(), get64BitArchVariant(), getBigEndianArchVariant(), getLittleEndianArchVariant(), hasDefaultEmulatedTLS(), llvm::DWARFContext::loadRegisterInfo(), llvm::TargetRegistry::lookupTarget(), llvm::object::ObjectFile::makeTriple(), and llvm::EngineBuilder::selectTarget().
setArchName()
void Triple::setArchName (StringRef Str)
setArchName - Set the architecture (first) component of the triple by name.
Definition at line 1201 of file Triple.cpp.
References getOSAndEnvironmentName(), getVendorName(), setTriple(), and Triple().
Referenced by hasDefaultEmulatedTLS(), setArch(), and llvm::object::ELFObjectFileBase::setARMSubArch().
setEnvironment()
void Triple::setEnvironment (EnvironmentType Kind)
setEnvironment - Set the environment (fourth) component of the triple to a known type.
Definition at line 1185 of file Triple.cpp.
References getDefaultFormat(), getEnvironmentTypeName(), getObjectFormatTypeName(), setEnvironmentName(), and str().
Referenced by hasDefaultEmulatedTLS().
setEnvironmentName()
void Triple::setEnvironmentName (StringRef Str)
setEnvironmentName - Set the optional environment (fourth) component of the triple by name.
Definition at line 1224 of file Triple.cpp.
References getArchName(), getOSName(), getVendorName(), and setTriple().
Referenced by hasDefaultEmulatedTLS(), setEnvironment(), and setObjectFormat().
setObjectFormat()
void Triple::setObjectFormat (ObjectFormatType Kind)
setObjectFormat - Set the object file format
Definition at line 1193 of file Triple.cpp.
References getEnvironmentTypeName(), getObjectFormatTypeName(), setEnvironmentName(), str(), and UnknownEnvironment.
Referenced by hasDefaultEmulatedTLS(), and llvm::object::ObjectFile::makeTriple().
setOS()
void Triple::setOS (OSType Kind)
setOS - Set the operating system (third) component of the triple to a known type.
Definition at line 1181 of file Triple.cpp.
References getOSTypeName(), and setOSName().
Referenced by hasDefaultEmulatedTLS(), and llvm::DWARFContext::loadRegisterInfo().
setOSAndEnvironmentName()
void Triple::setOSAndEnvironmentName (StringRef Str)
setOSAndEnvironmentName - Set the operating system and optional environment components with a single string.
Definition at line 1229 of file Triple.cpp.
References getArchName(), getVendorName(), and setTriple().
Referenced by hasDefaultEmulatedTLS().
setOSName()
void Triple::setOSName (StringRef Str)
setOSName - Set the operating system (third) component of the triple by name.
Definition at line 1216 of file Triple.cpp.
References getArchName(), getEnvironmentName(), getVendorName(), hasEnvironment(), and setTriple().
Referenced by hasDefaultEmulatedTLS(), and setOS().
setTriple()
void Triple::setTriple (const Twine & Str)
setTriple - Set all components to the new triple Str.
Definition at line 1169 of file Triple.cpp.
References Triple().
Referenced by hasDefaultEmulatedTLS(), llvm::object::ObjectFile::makeTriple(), llvm::EngineBuilder::selectTarget(), setArchName(), setEnvironmentName(), setOSAndEnvironmentName(), setOSName(), and setVendorName().
setVendor()
void Triple::setVendor (VendorType Kind)
setVendor - Set the vendor (second) component of the triple to a known type.
Definition at line 1177 of file Triple.cpp.
References getVendorTypeName(), and setVendorName().
Referenced by hasDefaultEmulatedTLS(), and llvm::DWARFContext::loadRegisterInfo().
setVendorName()
void Triple::setVendorName (StringRef Str)
setVendorName - Set the vendor (second) component of the triple by name.
Definition at line 1212 of file Triple.cpp.
References getArchName(), getOSAndEnvironmentName(), and setTriple().
Referenced by hasDefaultEmulatedTLS(), and setVendor().
str()
const std::string& llvm::Triple::str () const inline
Definition at line 366 of file Triple.h.
Referenced by llvm::orc::createLocalCompileCallbackManager(), llvm::orc::createLocalLazyCallThroughManager(), llvm::AsmPrinter::doInitialization(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::sys::getProcessTriple(), llvm::DWARFContext::loadRegisterInfo(), merge(), setEnvironment(), and setObjectFormat().
supportsCOMDAT()
bool llvm::Triple::supportsCOMDAT () const inline
Tests whether the target supports comdat.
Definition at line 745 of file Triple.h.
References isOSBinFormatMachO().
The documentation for this class was generated from the following files:
include/llvm/ADT/Triple.h
lib/Support/Triple.cpp