LLVM: llvm::object::COFFSymbolRef Class Reference
llvm::object::COFFSymbolRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
COFFSymbolRef ()=default
COFFSymbolRef (const coff_symbol16 *CS)
COFFSymbolRef (const coff_symbol32 *CS)
const void * getRawPtr () const
const coff_symbol_generic * getGeneric () const
bool isBigObj () const
const char * getShortName () const
const StringTableOffset & getStringTableOffset () const
uint32_t getValue () const
int32_t getSectionNumber () const
uint16_t getType () const
uint8_t getStorageClass () const
uint8_t getNumberOfAuxSymbols () const
uint8_t getBaseType () const
uint8_t getComplexType () const
template<typename T >
const T * getAux () const
const coff_aux_section_definition * getSectionDefinition () const
const coff_aux_weak_external * getWeakExternal () const
bool isAbsolute () const
bool isExternal () const
bool isCommon () const
bool isUndefined () const
bool isWeakExternal () const
bool isFunctionDefinition () const
bool isFunctionLineInfo () const
bool isAnyUndefined () const
bool isFileRecord () const
bool isSection () const
bool isSectionDefinition () const
bool isCLRToken () const
Friends
bool operator< (COFFSymbolRef A, COFFSymbolRef B)
Detailed Description
Definition at line 280 of file COFF.h.
Constructor & Destructor Documentation
COFFSymbolRef() [1/3]
llvm::object::COFFSymbolRef::COFFSymbolRef () default
COFFSymbolRef() [2/3]
llvm::object::COFFSymbolRef::COFFSymbolRef (const coff_symbol16 * CS) inline
Definition at line 283 of file COFF.h.
COFFSymbolRef() [3/3]
llvm::object::COFFSymbolRef::COFFSymbolRef (const coff_symbol32 * CS) inline
Definition at line 284 of file COFF.h.
Member Function Documentation
getAux()
template<typename T > const T* llvm::object::COFFSymbolRef::getAux () const inline
Definition at line 354 of file COFF.h.
getBaseType()
uint8_t llvm::object::COFFSymbolRef::getBaseType () const inline
Definition at line 348 of file COFF.h.
References getType().
getComplexType()
uint8_t llvm::object::COFFSymbolRef::getComplexType () const inline
Definition at line 350 of file COFF.h.
References getType(), and llvm::COFF::SCT_COMPLEX_TYPE_SHIFT.
Referenced by llvm::object::COFFObjectFile::getSymbolType().
getGeneric()
const coff_symbol_generic* llvm::object::COFFSymbolRef::getGeneric () const inline
Definition at line 290 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::getSymbolName().
getNumberOfAuxSymbols()
uint8_t llvm::object::COFFSymbolRef::getNumberOfAuxSymbols () const inline
Definition at line 343 of file COFF.h.
References assert().
Referenced by llvm::object::COFFObjectFile::getSymbolAuxData().
getRawPtr()
const void* llvm::object::COFFSymbolRef::getRawPtr () const inline
Definition at line 286 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::getSymbolAuxData(), and llvm::object::COFFObjectFile::getSymbolIndex().
getSectionDefinition()
const coff_aux_section_definition* llvm::object::COFFSymbolRef::getSectionDefinition () const inline
Definition at line 359 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_STATIC.
getSectionNumber()
int32_t llvm::object::COFFSymbolRef::getSectionNumber () const inline
Definition at line 322 of file COFF.h.
References assert(), and llvm::COFF::MaxNumberOfSections16.
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolFlags(), llvm::object::COFFObjectFile::getSymbolSection(), llvm::object::COFFObjectFile::getSymbolSectionID(), and llvm::object::COFFObjectFile::getSymbolType().
getShortName()
const char* llvm::object::COFFSymbolRef::getShortName () const inline
Definition at line 308 of file COFF.h.
getStorageClass()
uint8_t llvm::object::COFFSymbolRef::getStorageClass () const inline
Definition at line 338 of file COFF.h.
References assert().
getStringTableOffset()
const StringTableOffset& llvm::object::COFFSymbolRef::getStringTableOffset () const inline
Definition at line 312 of file COFF.h.
References assert().
getType()
uint16_t llvm::object::COFFSymbolRef::getType () const inline
Definition at line 333 of file COFF.h.
References assert().
getValue()
uint32_t llvm::object::COFFSymbolRef::getValue () const inline
Definition at line 317 of file COFF.h.
References assert().
Referenced by llvm::object::COFFObjectFile::getCommonSymbolSizeImpl(), llvm::object::COFFObjectFile::getSymbolAlignment(), and llvm::object::COFFObjectFile::getSymbolValueImpl().
getWeakExternal()
const coff_aux_weak_external* llvm::object::COFFSymbolRef::getWeakExternal () const inline
Definition at line 366 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_WEAK_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags().
isAbsolute()
bool llvm::object::COFFSymbolRef::isAbsolute () const inline
Definition at line 373 of file COFF.h.
isAnyUndefined()
bool llvm::object::COFFSymbolRef::isAnyUndefined () const inline
Definition at line 405 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), and llvm::object::COFFObjectFile::getSymbolType().
isBigObj()
bool llvm::object::COFFSymbolRef::isBigObj () const inline
Definition at line 300 of file COFF.h.
References llvm_unreachable.
isCLRToken()
bool llvm::object::COFFSymbolRef::isCLRToken () const inline
Definition at line 429 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_CLR_TOKEN.
isCommon()
bool llvm::object::COFFSymbolRef::isCommon () const inline
Definition at line 381 of file COFF.h.
References llvm::COFF::IMAGE_SYM_UNDEFINED.
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
isExternal()
bool llvm::object::COFFSymbolRef::isExternal () const inline
Definition at line 377 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags().
isFileRecord()
bool llvm::object::COFFSymbolRef::isFileRecord () const inline
Definition at line 409 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_FILE.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
isFunctionDefinition()
bool llvm::object::COFFSymbolRef::isFunctionDefinition () const inline
Definition at line 395 of file COFF.h.
References getBaseType(), llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::COFF::IMAGE_SYM_TYPE_NULL, and llvm::COFF::isReservedSectionNumber().
isFunctionLineInfo()
bool llvm::object::COFFSymbolRef::isFunctionLineInfo () const inline
Definition at line 401 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_FUNCTION.
isSection()
bool llvm::object::COFFSymbolRef::isSection () const inline
Definition at line 413 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_SECTION.
isSectionDefinition()
bool llvm::object::COFFSymbolRef::isSectionDefinition () const inline
Definition at line 417 of file COFF.h.
References llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, and llvm::COFF::IMAGE_SYM_CLASS_STATIC.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
isUndefined()
bool llvm::object::COFFSymbolRef::isUndefined () const inline
Definition at line 386 of file COFF.h.
References llvm::COFF::IMAGE_SYM_UNDEFINED.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags().
isWeakExternal()
bool llvm::object::COFFSymbolRef::isWeakExternal () const inline
Definition at line 391 of file COFF.h.
References llvm::COFF::IMAGE_SYM_CLASS_WEAK_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags().
Friends And Related Function Documentation
operator<
bool operator< (COFFSymbolRef A, COFFSymbolRef B) friend
Definition at line 296 of file COFF.h.
The documentation for this class was generated from the following file:
include/llvm/Object/COFF.h