LLVM: llvm::PSetIterator Class Reference
llvm::PSetIterator Class Reference
Iterate over the pressure sets affected by the given physical or virtual register.
#include "llvm/CodeGen/MachineRegisterInfo.h"
Public Member Functions
PSetIterator ()=default
PSetIterator (unsigned RegUnit, const MachineRegisterInfo *MRI)
bool isValid () const
unsigned getWeight () const
unsigned operator* () const
void operator++ ()
Detailed Description
Iterate over the pressure sets affected by the given physical or virtual register.
If Reg is physical, it must be a register unit (from MCRegUnitIterator).
Definition at line 1170 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
PSetIterator() [1/2]
llvm::PSetIterator::PSetIterator () default
PSetIterator() [2/2]
llvm::PSetIterator::PSetIterator (unsigned RegUnit, const MachineRegisterInfo * MRI) inline
Definition at line 1177 of file MachineRegisterInfo.h.
References llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassPressureSets(), llvm::TargetRegisterInfo::getRegClassWeight(), llvm::TargetRegisterInfo::getRegUnitPressureSets(), llvm::TargetRegisterInfo::getRegUnitWeight(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::Register::isVirtualRegister(), and llvm::RegClassWeight::RegWeight.
Member Function Documentation
getWeight()
unsigned llvm::PSetIterator::getWeight () const inline
Definition at line 1194 of file MachineRegisterInfo.h.
Referenced by llvm::PressureDiff::addPressureChange(), decreaseSetPressure(), llvm::GCNRegPressure::inc(), llvm::RegPressureTracker::increaseRegPressure(), increaseSetPressure(), and llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
isValid()
bool llvm::PSetIterator::isValid () const inline
Definition at line 1192 of file MachineRegisterInfo.h.
Referenced by llvm::PressureDiff::addPressureChange(), decreaseSetPressure(), llvm::RegPressureTracker::increaseRegPressure(), increaseSetPressure(), and llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
operator*()
unsigned llvm::PSetIterator::operator* () const inline
Definition at line 1196 of file MachineRegisterInfo.h.
operator++()
void llvm::PSetIterator::operator++ () inline
Definition at line 1198 of file MachineRegisterInfo.h.
References assert(), and llvm::MachineRegisterInfo::getPressureSets().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineRegisterInfo.h