LLVM: llvm::MapResolver Class Reference
llvm::MapResolver Class Reference final
Resolve arbitrary mappings.
#include "llvm/TableGen/Record.h"
Public Member Functions
MapResolver (Record *CurRec=nullptr)
void set (Init *Key, Init *Value)
Init * resolve (Init *VarName) override
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Public Member Functions inherited from llvm::Resolver
Resolver (Record *CurRec)
virtual ~Resolver ()
Record * getCurrentRecord () const
virtual bool keepUnsetBits () const
bool isFinal () const
void setFinal (bool Final)
Detailed Description
Resolve arbitrary mappings.
Definition at line 1898 of file Record.h.
Constructor & Destructor Documentation
MapResolver()
llvm::MapResolver::MapResolver (Record * CurRec = nullptr) inline explicit
Definition at line 1910 of file Record.h.
Member Function Documentation
resolve()
Init * MapResolver::resolve (Init * VarName) override virtual
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Implements llvm::Resolver.
Definition at line 2407 of file Record.cpp.
References I, llvm::Init::resolveReferences(), and llvm::tgtok::VarName.
set()
void llvm::MapResolver::set (Init * Key, Init * Value) inline
Definition at line 1912 of file Record.h.
References llvm::tgtok::VarName.
Referenced by ForeachApply(), llvm::VarDefInit::Profile(), and QualifiedNameOfImplicitName().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp