LLVM: llvm::NameAnonGlobalPass Class Reference
llvm::NameAnonGlobalPass Class Reference
Simple pass that provides a name to every anonymous globals.
#include "llvm/Transforms/Utils/NameAnonGlobals.h"
Public Member Functions
NameAnonGlobalPass ()=default
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< NameAnonGlobalPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Simple pass that provides a name to every anonymous globals.
Definition at line 23 of file NameAnonGlobals.h.
Constructor & Destructor Documentation
NameAnonGlobalPass()
llvm::NameAnonGlobalPass::NameAnonGlobalPass () default
Member Function Documentation
run()
PreservedAnalyses NameAnonGlobalPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 103 of file NameAnonGlobals.cpp.
References llvm::PreservedAnalyses::all(), INITIALIZE_PASS_BEGIN(), llvm::nameUnamedGlobals(), and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/NameAnonGlobals.h
lib/Transforms/Utils/NameAnonGlobals.cpp