LLVM: llvm::MCRegUnitRootIterator Class Reference
llvm::MCRegUnitRootIterator Class Reference
MCRegUnitRootIterator enumerates the root registers of a register unit.
#include "llvm/MC/MCRegisterInfo.h"
Public Member Functions
MCRegUnitRootIterator ()=default
MCRegUnitRootIterator (unsigned RegUnit, const MCRegisterInfo *MCRI)
unsigned operator* () const
Dereference to get the current root register.
bool isValid () const
Check if the iterator is at the end of the list.
void operator++ ()
Preincrement to move to the next root register.
Detailed Description
MCRegUnitRootIterator enumerates the root registers of a register unit.
Definition at line 738 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
MCRegUnitRootIterator() [1/2]
llvm::MCRegUnitRootIterator::MCRegUnitRootIterator () default
MCRegUnitRootIterator() [2/2]
llvm::MCRegUnitRootIterator::MCRegUnitRootIterator (unsigned RegUnit, const MCRegisterInfo * MCRI) inline
Definition at line 745 of file MCRegisterInfo.h.
References assert().
Member Function Documentation
isValid()
bool llvm::MCRegUnitRootIterator::isValid () const inline
Check if the iterator is at the end of the list.
Definition at line 757 of file MCRegisterInfo.h.
Referenced by llvm::LiveRegUnits::addRegsInMask(), llvm::MCRegAliasIterator::advance(), llvm::createBreakFalseDeps(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::MachineRegisterInfo::isReservedRegUnit(), llvm::MCRegAliasIterator::MCRegAliasIterator(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::LiveIntervals::print(), llvm::printRegUnit(), and llvm::LiveRegUnits::removeRegsNotPreserved().
operator*()
unsigned llvm::MCRegUnitRootIterator::operator* () const inline
Dereference to get the current root register.
Definition at line 752 of file MCRegisterInfo.h.
operator++()
void llvm::MCRegUnitRootIterator::operator++ () inline
Preincrement to move to the next root register.
Definition at line 762 of file MCRegisterInfo.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/MC/MCRegisterInfo.h