LLVM: llvm::ImportedFunctionsInliningStatistics Class Reference
llvm::ImportedFunctionsInliningStatistics Class Reference
Calculate and dump ThinLTO specific inliner stats.
#include "llvm/Transforms/Utils/ImportedFunctionsInliningStatistics.h"
Public Member Functions
ImportedFunctionsInliningStatistics ()=default
ImportedFunctionsInliningStatistics (const ImportedFunctionsInliningStatistics &)=delete
void setModuleInfo (const Module &M)
Set information like AllFunctions, ImportedFunctions, ModuleName.
void recordInline (const Function &Caller, const Function &Callee)
Record inline of.
void dump (bool Verbose)
Dump stats computed with InlinerStatistics class.
Detailed Description
Calculate and dump ThinLTO specific inliner stats.
The main statistics are: (1) Number of inlined imported functions, (2) Number of imported functions inlined into importing module (indirect), (3) Number of non imported functions inlined into importing module (indirect). The difference between first and the second is that first stat counts all performed inlines on imported functions, but the second one only the functions that have been eventually inlined to a function in the importing module (by a chain of inlines). Because llvm uses bottom-up inliner, it is possible to e.g. import function A, B and then inline B to A, and after this A might be too big to be inlined into some other function that calls it. It calculates this statistic by building graph, where the nodes are functions, and edges are performed inlines and then by marking the edges starting from not imported function.
If Verbose is set to true, then it also dumps statistics per each inlined function, sorted by the greatest inlines count like
number of performed inlines
number of performed inlines to importing module
Definition at line 44 of file ImportedFunctionsInliningStatistics.h.
Constructor & Destructor Documentation
ImportedFunctionsInliningStatistics() [1/2]
llvm::ImportedFunctionsInliningStatistics::ImportedFunctionsInliningStatistics () default
ImportedFunctionsInliningStatistics() [2/2]
llvm::ImportedFunctionsInliningStatistics::ImportedFunctionsInliningStatistics (const ImportedFunctionsInliningStatistics &) delete
Member Function Documentation
dump()
void ImportedFunctionsInliningStatistics::dump (bool Verbose)
Dump stats computed with InlinerStatistics class.
If
Parameters
Verbose is true then separate statistics for every inlined function will be printed.
Definition at line 85 of file ImportedFunctionsInliningStatistics.cpp.
Referenced by llvm::LegacyInlinerBase::doFinalization(), and llvm::InlinerPass::~InlinerPass().
recordInline()
void ImportedFunctionsInliningStatistics::recordInline (const Function & Caller, const Function & Callee)
Record inline of.
Parameters
Callee to
Caller for statistis.
Definition at line 34 of file ImportedFunctionsInliningStatistics.cpp.
References assert(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), and llvm::Value::getName().
Referenced by InlineCallIfPossible(), and llvm::InlinerPass::run().
setModuleInfo()
void ImportedFunctionsInliningStatistics::setModuleInfo (const Module & M)
Set information like AllFunctions, ImportedFunctions, ModuleName.
Definition at line 61 of file ImportedFunctionsInliningStatistics.cpp.
References llvm::Module::functions(), llvm::Module::getName(), llvm::GlobalObject::hasMetadata(), and llvm::GlobalValue::isDeclaration().
Referenced by llvm::LegacyInlinerBase::doInitialization(), and llvm::InlinerPass::run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/ImportedFunctionsInliningStatistics.h
lib/Transforms/Utils/ImportedFunctionsInliningStatistics.cpp