LLVM: llvm::DbgEntity Class Reference
llvm::DbgEntity Class Reference
This class is defined as the common parent of DbgVariable and DbgLabel such that it could levarage polymorphism to extract common code for DbgVariable and DbgLabel.
#include "CodeGen/AsmPrinter/DwarfDebug.h"
Public Types
enum DbgEntityKind { DbgVariableKind, DbgLabelKind }
Public Member Functions
DbgEntity (const DINode *N, const DILocation *IA, unsigned ID)
virtual ~DbgEntity ()
void setDIE (DIE &D)
const DINode * getEntity () const
Accessors.
const DILocation * getInlinedAt () const
DIE * getDIE () const
unsigned getDbgEntityID () const
Static Public Member Functions
static bool classof (const DbgEntity *N)
Detailed Description
This class is defined as the common parent of DbgVariable and DbgLabel such that it could levarage polymorphism to extract common code for DbgVariable and DbgLabel.
Definition at line 69 of file DwarfDebug.h.
Member Enumeration Documentation
DbgEntityKind
enum llvm::DbgEntity::DbgEntityKind
Enumerator
DbgVariableKind
DbgLabelKind
Definition at line 76 of file DwarfDebug.h.
Constructor & Destructor Documentation
DbgEntity()
llvm::DbgEntity::DbgEntity (const DINode * N, const DILocation * IA, unsigned ID) inline
Definition at line 81 of file DwarfDebug.h.
~DbgEntity()
virtual llvm::DbgEntity::~DbgEntity () inline virtual
Definition at line 83 of file DwarfDebug.h.
Member Function Documentation
classof()
static bool llvm::DbgEntity::classof (const DbgEntity * N) inline static
Definition at line 95 of file DwarfDebug.h.
References DbgLabelKind, DbgVariableKind, and getDbgEntityID().
getDbgEntityID()
unsigned llvm::DbgEntity::getDbgEntityID () const inline
Definition at line 90 of file DwarfDebug.h.
Referenced by classof(), llvm::DbgVariable::classof(), and llvm::DbgLabel::classof().
getDIE()
DIE* llvm::DbgEntity::getDIE () const inline
Definition at line 89 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::finishEntityDefinition().
getEntity()
const DINode* llvm::DbgEntity::getEntity () const inline
Accessors.
Definition at line 87 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::finishEntityDefinition(), llvm::DbgLabel::getLabel(), and llvm::DbgVariable::getVariable().
getInlinedAt()
const DILocation* llvm::DbgEntity::getInlinedAt () const inline
Definition at line 88 of file DwarfDebug.h.
Referenced by llvm::DbgVariable::addMMIEntry().
setDIE()
void llvm::DbgEntity::setDIE (DIE & D) inline
Definition at line 93 of file DwarfDebug.h.
References D.
Referenced by llvm::DwarfCompileUnit::constructLabelDIE(), and llvm::DwarfCompileUnit::constructVariableDIE().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/DwarfDebug.h