LLVM: llvm::DWARFObject Class Reference
llvm::DWARFObject Class Reference abstract
#include "llvm/DebugInfo/DWARF/DWARFObject.h"
Public Member Functions
virtual ~DWARFObject ()=default
virtual StringRef getFileName () const
virtual const object::ObjectFile * getFile () const
virtual ArrayRef< SectionName > getSectionNames () const
virtual bool isLittleEndian () const =0
virtual uint8_t getAddressSize () const
virtual void forEachInfoSections (function_ref< void(const DWARFSection &)> F) const
virtual void forEachTypesSections (function_ref< void(const DWARFSection &)> F) const
virtual StringRef getAbbrevSection () const
virtual const DWARFSection & getLocSection () const
virtual const DWARFSection & getLoclistsSection () const
virtual StringRef getArangesSection () const
virtual const DWARFSection & getFrameSection () const
virtual const DWARFSection & getEHFrameSection () const
virtual const DWARFSection & getLineSection () const
virtual StringRef getLineStrSection () const
virtual StringRef getStrSection () const
virtual const DWARFSection & getRangesSection () const
virtual const DWARFSection & getRnglistsSection () const
virtual StringRef getMacinfoSection () const
virtual StringRef getMacinfoDWOSection () const
virtual const DWARFSection & getPubnamesSection () const
virtual const DWARFSection & getPubtypesSection () const
virtual const DWARFSection & getGnuPubnamesSection () const
virtual const DWARFSection & getGnuPubtypesSection () const
virtual const DWARFSection & getStrOffsetsSection () const
virtual void forEachInfoDWOSections (function_ref< void(const DWARFSection &)> F) const
virtual void forEachTypesDWOSections (function_ref< void(const DWARFSection &)> F) const
virtual StringRef getAbbrevDWOSection () const
virtual const DWARFSection & getLineDWOSection () const
virtual const DWARFSection & getLocDWOSection () const
virtual const DWARFSection & getLoclistsDWOSection () const
virtual StringRef getStrDWOSection () const
virtual const DWARFSection & getStrOffsetsDWOSection () const
virtual const DWARFSection & getRangesDWOSection () const
virtual const DWARFSection & getRnglistsDWOSection () const
virtual const DWARFSection & getAddrSection () const
virtual const DWARFSection & getAppleNamesSection () const
virtual const DWARFSection & getAppleTypesSection () const
virtual const DWARFSection & getAppleNamespacesSection () const
virtual const DWARFSection & getNamesSection () const
virtual const DWARFSection & getAppleObjCSection () const
virtual StringRef getCUIndexSection () const
virtual StringRef getGdbIndexSection () const
virtual StringRef getTUIndexSection () const
virtual Optional< RelocAddrEntry > find (const DWARFSection &Sec, uint64_t Pos) const =0
Detailed Description
Definition at line 25 of file DWARFObject.h.
Constructor & Destructor Documentation
~DWARFObject()
virtual llvm::DWARFObject::~DWARFObject () virtual default
Member Function Documentation
find()
virtual Optional<RelocAddrEntry> llvm::DWARFObject::find (const DWARFSection & Sec, uint64_t Pos) const pure virtual
Referenced by getTUIndexSection().
forEachInfoDWOSections()
virtual void llvm::DWARFObject::forEachInfoDWOSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 58 of file DWARFObject.h.
forEachInfoSections()
virtual void llvm::DWARFObject::forEachInfoSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 36 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
forEachTypesDWOSections()
virtual void llvm::DWARFObject::forEachTypesDWOSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 60 of file DWARFObject.h.
forEachTypesSections()
virtual void llvm::DWARFObject::forEachTypesSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 38 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
getAbbrevDWOSection()
virtual StringRef llvm::DWARFObject::getAbbrevDWOSection () const inline virtual
Definition at line 61 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugAbbrev().
getAbbrevSection()
virtual StringRef llvm::DWARFObject::getAbbrevSection () const inline virtual
Definition at line 39 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugAbbrev().
getAddressSize()
virtual uint8_t llvm::DWARFObject::getAddressSize () const inline virtual
Definition at line 34 of file DWARFObject.h.
References llvm_unreachable.
getAddrSection()
virtual const DWARFSection& llvm::DWARFObject::getAddrSection () const inline virtual
Definition at line 71 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForDWOSection(), and llvm::DWARFUnitVector::addUnitsForSection().
getAppleNamespacesSection()
virtual const DWARFSection& llvm::DWARFObject::getAppleNamespacesSection () const inline virtual
Definition at line 74 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleAccelTables().
getAppleNamesSection()
virtual const DWARFSection& llvm::DWARFObject::getAppleNamesSection () const inline virtual
Definition at line 72 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleAccelTables().
getAppleObjCSection()
virtual const DWARFSection& llvm::DWARFObject::getAppleObjCSection () const inline virtual
Definition at line 78 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleAccelTables(), and llvm::DWARFVerifier::handleDebugAbbrev().
getAppleTypesSection()
virtual const DWARFSection& llvm::DWARFObject::getAppleTypesSection () const inline virtual
Definition at line 73 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleAccelTables().
getArangesSection()
virtual StringRef llvm::DWARFObject::getArangesSection () const inline virtual
Definition at line 42 of file DWARFObject.h.
Referenced by llvm::DWARFDebugAranges::generate().
getCUIndexSection()
virtual StringRef llvm::DWARFObject::getCUIndexSection () const inline virtual
Definition at line 79 of file DWARFObject.h.
getEHFrameSection()
virtual const DWARFSection& llvm::DWARFObject::getEHFrameSection () const inline virtual
Definition at line 44 of file DWARFObject.h.
getFile()
virtual const object::ObjectFile* llvm::DWARFObject::getFile () const inline virtual
Definition at line 31 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::DWARFVerifier().
getFileName()
virtual StringRef llvm::DWARFObject::getFileName () const inline virtual
Definition at line 30 of file DWARFObject.h.
References llvm_unreachable.
getFrameSection()
virtual const DWARFSection& llvm::DWARFObject::getFrameSection () const inline virtual
Definition at line 43 of file DWARFObject.h.
getGdbIndexSection()
virtual StringRef llvm::DWARFObject::getGdbIndexSection () const inline virtual
Definition at line 80 of file DWARFObject.h.
getGnuPubnamesSection()
virtual const DWARFSection& llvm::DWARFObject::getGnuPubnamesSection () const inline virtual
Definition at line 54 of file DWARFObject.h.
getGnuPubtypesSection()
virtual const DWARFSection& llvm::DWARFObject::getGnuPubtypesSection () const inline virtual
Definition at line 55 of file DWARFObject.h.
getLineDWOSection()
virtual const DWARFSection& llvm::DWARFObject::getLineDWOSection () const inline virtual
Definition at line 62 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForDWOSection().
getLineSection()
virtual const DWARFSection& llvm::DWARFObject::getLineSection () const inline virtual
Definition at line 45 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForSection(), llvm::DWARFVerifier::handleDebugAbbrev(), and llvm::DWARFVerifier::handleDebugInfo().
getLineStrSection()
virtual StringRef llvm::DWARFObject::getLineStrSection () const inline virtual
Definition at line 46 of file DWARFObject.h.
getLocDWOSection()
virtual const DWARFSection& llvm::DWARFObject::getLocDWOSection () const inline virtual
Definition at line 63 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForDWOSection().
getLoclistsDWOSection()
virtual const DWARFSection& llvm::DWARFObject::getLoclistsDWOSection () const inline virtual
Definition at line 64 of file DWARFObject.h.
Referenced by llvm::DWARFUnit::DWARFUnit(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
getLoclistsSection()
virtual const DWARFSection& llvm::DWARFObject::getLoclistsSection () const inline virtual
Definition at line 41 of file DWARFObject.h.
Referenced by llvm::DWARFUnit::DWARFUnit(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
getLocSection()
virtual const DWARFSection& llvm::DWARFObject::getLocSection () const inline virtual
Definition at line 40 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForSection(), and llvm::DWARFVerifier::handleDebugAbbrev().
getMacinfoDWOSection()
virtual StringRef llvm::DWARFObject::getMacinfoDWOSection () const inline virtual
Definition at line 51 of file DWARFObject.h.
getMacinfoSection()
virtual StringRef llvm::DWARFObject::getMacinfoSection () const inline virtual
Definition at line 50 of file DWARFObject.h.
getNamesSection()
virtual const DWARFSection& llvm::DWARFObject::getNamesSection () const inline virtual
Definition at line 77 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleAccelTables().
getPubnamesSection()
virtual const DWARFSection& llvm::DWARFObject::getPubnamesSection () const inline virtual
Definition at line 52 of file DWARFObject.h.
getPubtypesSection()
virtual const DWARFSection& llvm::DWARFObject::getPubtypesSection () const inline virtual
Definition at line 53 of file DWARFObject.h.
getRangesDWOSection()
virtual const DWARFSection& llvm::DWARFObject::getRangesDWOSection () const inline virtual
Definition at line 69 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForDWOSection().
getRangesSection()
virtual const DWARFSection& llvm::DWARFObject::getRangesSection () const inline virtual
Definition at line 48 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForSection(), llvm::DWARFVerifier::handleDebugAbbrev(), and llvm::DWARFVerifier::handleDebugInfo().
getRnglistsDWOSection()
virtual const DWARFSection& llvm::DWARFObject::getRnglistsDWOSection () const inline virtual
Definition at line 70 of file DWARFObject.h.
Referenced by llvm::DWARFUnit::tryExtractDIEsIfNeeded().
getRnglistsSection()
virtual const DWARFSection& llvm::DWARFObject::getRnglistsSection () const inline virtual
Definition at line 49 of file DWARFObject.h.
Referenced by llvm::DWARFUnit::tryExtractDIEsIfNeeded().
getSectionNames()
virtual ArrayRef<SectionName> llvm::DWARFObject::getSectionNames () const inline virtual
Definition at line 32 of file DWARFObject.h.
References isLittleEndian().
Referenced by llvm::DWARFFormValue::dumpAddressSection().
getStrDWOSection()
virtual StringRef llvm::DWARFObject::getStrDWOSection () const inline virtual
Definition at line 65 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForDWOSection().
getStrOffsetsDWOSection()
virtual const DWARFSection& llvm::DWARFObject::getStrOffsetsDWOSection () const inline virtual
Definition at line 66 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForDWOSection().
getStrOffsetsSection()
virtual const DWARFSection& llvm::DWARFObject::getStrOffsetsSection () const inline virtual
Definition at line 56 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForSection(), llvm::DWARFVerifier::handleDebugAbbrev(), and llvm::DWARFVerifier::handleDebugInfo().
getStrSection()
virtual StringRef llvm::DWARFObject::getStrSection () const inline virtual
Definition at line 47 of file DWARFObject.h.
Referenced by llvm::DWARFUnitVector::addUnitsForSection(), llvm::DWARFVerifier::handleAccelTables(), llvm::DWARFVerifier::handleDebugAbbrev(), and llvm::DWARFVerifier::handleDebugInfo().
getTUIndexSection()
virtual StringRef llvm::DWARFObject::getTUIndexSection () const inline virtual
Definition at line 81 of file DWARFObject.h.
References find().
isLittleEndian()
virtual bool llvm::DWARFObject::isLittleEndian () const pure virtual
Referenced by llvm::DWARFUnitVector::addUnitsForSection(), and getSectionNames().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFObject.h