LLVM: llvm::MCWinCOFFObjectTargetWriter Class Reference
llvm::MCWinCOFFObjectTargetWriter Class Reference abstract
#include "llvm/MC/MCWinCOFFObjectWriter.h"
Public Member Functions
virtual ~MCWinCOFFObjectTargetWriter ()=default
virtual Triple::ObjectFormatType getFormat () const
unsigned getMachine () const
virtual unsigned getRelocType (MCContext &Ctx, const MCValue &Target, const MCFixup &Fixup, bool IsCrossSection, const MCAsmBackend &MAB) const =0
virtual bool recordRelocation (const MCFixup &) const
Public Member Functions inherited from llvm::MCObjectTargetWriter
virtual ~MCObjectTargetWriter ()=default
Static Public Member Functions
static bool classof (const MCObjectTargetWriter *W)
Protected Member Functions
MCWinCOFFObjectTargetWriter (unsigned Machine_)
Detailed Description
Definition at line 23 of file MCWinCOFFObjectWriter.h.
Constructor & Destructor Documentation
MCWinCOFFObjectTargetWriter()
MCWinCOFFObjectTargetWriter::MCWinCOFFObjectTargetWriter (unsigned Machine_) protected
Definition at line 1090 of file WinCOFFObjectWriter.cpp.
~MCWinCOFFObjectTargetWriter()
virtual llvm::MCWinCOFFObjectTargetWriter::~MCWinCOFFObjectTargetWriter () virtual default
Member Function Documentation
classof()
static bool llvm::MCWinCOFFObjectTargetWriter::classof (const MCObjectTargetWriter * W) inline static
Definition at line 35 of file MCWinCOFFObjectWriter.h.
References llvm::Triple::COFF, and llvm::MCObjectTargetWriter::getFormat().
getFormat()
virtual Triple::ObjectFormatType llvm::MCWinCOFFObjectTargetWriter::getFormat () const inline virtual
Implements llvm::MCObjectTargetWriter.
Definition at line 34 of file MCWinCOFFObjectWriter.h.
References llvm::Triple::COFF.
getMachine()
unsigned llvm::MCWinCOFFObjectTargetWriter::getMachine () const inline
Definition at line 39 of file MCWinCOFFObjectWriter.h.
References Fixup, and getRelocType().
getRelocType()
virtual unsigned llvm::MCWinCOFFObjectTargetWriter::getRelocType (MCContext & Ctx, const MCValue & Target, const MCFixup & Fixup, bool IsCrossSection, const MCAsmBackend & MAB) const pure virtual
Referenced by getMachine().
recordRelocation()
virtual bool llvm::MCWinCOFFObjectTargetWriter::recordRelocation (const MCFixup &) const inline virtual
Definition at line 43 of file MCWinCOFFObjectWriter.h.
References llvm::createWinCOFFObjectWriter().
The documentation for this class was generated from the following files:
include/llvm/MC/MCWinCOFFObjectWriter.h
lib/MC/WinCOFFObjectWriter.cpp