LLVM: llvm::MCSectionELF Class Reference
llvm::MCSectionELF Class Reference final
This represents a section on linux, lots of unix variants and some bare metal systems.
#include "llvm/MC/MCSectionELF.h"
Public Member Functions
bool ShouldOmitSectionDirective (StringRef Name, const MCAsmInfo &MAI) const
Decides whether a '.section' directive should be printed before the section name.
StringRef getSectionName () const
unsigned getType () const
unsigned getFlags () const
unsigned getEntrySize () const
void setFlags (unsigned F)
const MCSymbolELF * getGroup () const
void PrintSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const override
bool UseCodeAlign () const override
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
bool isVirtualSection () const override
Check whether this section is "virtual", that is has no actual object file contents.
bool isUnique () const
unsigned getUniqueID () const
const MCSection * getAssociatedSection () const
const MCSymbol * getAssociatedSymbol () const
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
SectionKind getKind () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
unsigned getAlignment () const
void setAlignment (Align Value)
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
MCSection::FragmentListType & getFragmentList ()
const MCSection::FragmentListType & getFragmentList () const
const MCDummyFragment & getDummyFragment () const
MCDummyFragment & getDummyFragment ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
MCSection::iterator getSubsectionInsertionPoint (unsigned Subsection)
void dump () const
void addPendingLabel (MCSymbol *label, unsigned Subsection=0)
Add a pending label for the requested subsection.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0, unsigned Subsection=0)
Associate all pending labels in a subsection with a fragment.
void flushPendingLabels ()
Associate all pending labels with empty data fragments.
Static Public Member Functions
static bool classof (const MCSection *S)
Static Public Member Functions inherited from llvm::MCSection
static FragmentListType MCSection::* getSublistAccess (MCFragment *)
Support for MCFragment::getNextNode().
Friends
class MCContext
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant {
SV_COFF = 0, SV_ELF, SV_MachO, SV_Wasm,
SV_XCOFF
}
enum BundleLockStateType { NotBundleLocked, BundleLocked, BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
using FragmentListType = iplist< MCFragment >
using const_iterator = FragmentListType::const_iterator
using iterator = FragmentListType::iterator
using const_reverse_iterator = FragmentListType::const_reverse_iterator
using reverse_iterator = FragmentListType::reverse_iterator
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, SectionKind K, MCSymbol *Begin)
~MCSection ()
Protected Attributes inherited from llvm::MCSection
SectionVariant Variant
SectionKind Kind
Detailed Description
This represents a section on linux, lots of unix variants and some bare metal systems.
Definition at line 27 of file MCSectionELF.h.
Member Function Documentation
classof()
static bool llvm::MCSectionELF::classof (const MCSection * S) inline static
Definition at line 89 of file MCSectionELF.h.
References llvm::MCSection::getVariant(), and llvm::MCSection::SV_ELF.
getAssociatedSection()
const MCSection* llvm::MCSectionELF::getAssociatedSection () const inline
Definition at line 86 of file MCSectionELF.h.
References llvm::MCSymbol::getSection().
Referenced by isIFunc().
getAssociatedSymbol()
const MCSymbol* llvm::MCSectionELF::getAssociatedSymbol () const inline
Definition at line 87 of file MCSectionELF.h.
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), isIFunc(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
getEntrySize()
unsigned llvm::MCSectionELF::getEntrySize () const inline
Definition at line 73 of file MCSectionELF.h.
Referenced by isIFunc().
getFlags()
unsigned llvm::MCSectionELF::getFlags () const inline
Definition at line 72 of file MCSectionELF.h.
Referenced by llvm::MCELFStreamer::EmitLabel(), llvm::MCELFStreamer::EmitLabelAtPos(), isIFunc(), and UseCodeAlign().
getGroup()
const MCSymbolELF* llvm::MCSectionELF::getGroup () const inline
Definition at line 75 of file MCSectionELF.h.
References isVirtualSection(), PrintSwitchToSection(), and UseCodeAlign().
Referenced by GetAEABIUnwindPersonalityName(), llvm::MCObjectFileInfo::getStackSizesSection(), isIFunc(), and llvm::MCContext::renameELFSection().
getSectionName()
StringRef llvm::MCSectionELF::getSectionName () const inline
Definition at line 70 of file MCSectionELF.h.
References AMDGPU::ElfNote::SectionName.
Referenced by llvm::BTFDebug::beginFunctionImpl(), GetAEABIUnwindPersonalityName(), isIFunc(), PrintSwitchToSection(), and llvm::MCContext::renameELFSection().
getType()
unsigned llvm::MCSectionELF::getType () const inline
Definition at line 71 of file MCSectionELF.h.
References Type.
Referenced by isIFunc(), and isVirtualSection().
getUniqueID()
unsigned llvm::MCSectionELF::getUniqueID () const inline
Definition at line 84 of file MCSectionELF.h.
Referenced by GetAEABIUnwindPersonalityName(), and llvm::MCContext::renameELFSection().
isUnique()
bool llvm::MCSectionELF::isUnique () const inline
Definition at line 83 of file MCSectionELF.h.
Referenced by PrintSwitchToSection(), and ShouldOmitSectionDirective().
isVirtualSection()
bool MCSectionELF::isVirtualSection () const override virtual
Check whether this section is "virtual", that is has no actual object file contents.
Implements llvm::MCSection.
Definition at line 196 of file MCSectionELF.cpp.
References getType(), and llvm::ELF::SHT_NOBITS.
Referenced by getGroup().
PrintSwitchToSection()
void MCSectionELF::PrintSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, const MCExpr * Subsection) const override virtual
Implements llvm::MCSection.
Definition at line 53 of file MCSectionELF.cpp.
References assert(), llvm::Triple::getArch(), llvm::MCAsmInfo::getCommentString(), llvm::MCSymbol::getName(), getSectionName(), llvm::Triple::hexagon, llvm::Triple::isARM(), llvm::Triple::isThumb(), isUnique(), llvm::MCExpr::print(), printName(), llvm::report_fatal_error(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_ARM_PURECODE, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_HEX_GPREL, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_TLS, llvm::ELF::SHF_WRITE, ShouldOmitSectionDirective(), llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_LLVM_CALL_GRAPH_PROFILE, llvm::ELF::SHT_LLVM_DEPENDENT_LIBRARIES, llvm::ELF::SHT_LLVM_LINKER_OPTIONS, llvm::ELF::SHT_LLVM_ODRTAB, llvm::ELF::SHT_LLVM_SYMPART, llvm::ELF::SHT_MIPS_DWARF, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PREINIT_ARRAY, llvm::ELF::SHT_PROGBITS, llvm::ELF::SHT_X86_64_UNWIND, llvm::MCAsmInfo::usesSunStyleELFSectionSwitchSyntax(), llvm::Twine::utohexstr(), llvm::Triple::xcore, llvm::ELF::XCORE_SHF_CP_SECTION, and llvm::ELF::XCORE_SHF_DP_SECTION.
Referenced by getGroup().
setFlags()
void llvm::MCSectionELF::setFlags (unsigned F) inline
Definition at line 74 of file MCSectionELF.h.
References F().
Referenced by isIFunc().
ShouldOmitSectionDirective()
bool MCSectionELF::ShouldOmitSectionDirective (StringRef Name, const MCAsmInfo & MAI) const
Decides whether a '.section' directive should be printed before the section name.
Definition at line 22 of file MCSectionELF.cpp.
References isUnique(), and llvm::MCAsmInfo::shouldOmitSectionDirective().
Referenced by PrintSwitchToSection().
UseCodeAlign()
bool MCSectionELF::UseCodeAlign () const override virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implements llvm::MCSection.
Definition at line 192 of file MCSectionELF.cpp.
References getFlags(), and llvm::ELF::SHF_EXECINSTR.
Referenced by llvm::MipsTargetELFStreamer::finish(), and getGroup().
Friends And Related Function Documentation
MCContext
friend class MCContext friend
Definition at line 51 of file MCSectionELF.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSectionELF.h
lib/MC/MCSectionELF.cpp