LLVM: llvm::pdb::NativeTypeFunctionSig Class Reference
llvm::pdb::NativeTypeFunctionSig Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeTypeFunctionSig.h"
Public Member Functions
NativeTypeFunctionSig (NativeSession &Session, SymIndexId Id, codeview::TypeIndex TI, codeview::ProcedureRecord Proc)
NativeTypeFunctionSig (NativeSession &Session, SymIndexId Id, codeview::TypeIndex TI, codeview::MemberFunctionRecord MemberFunc)
~NativeTypeFunctionSig () override
void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const override
SymIndexId getClassParentId () const override
PDB_CallingConv getCallingConvention () const override
uint32_t getCount () const override
SymIndexId getTypeId () const override
int32_t getThisAdjust () const override
bool hasConstructor () const override
bool isConstType () const override
bool isConstructorVirtualBase () const override
bool isCxxReturnUdt () const override
bool isUnalignedType () const override
bool isVolatileType () const override
Public Member Functions inherited from llvm::pdb::NativeRawSymbol
NativeRawSymbol (NativeSession &PDBSession, PDB_SymType Tag, SymIndexId SymbolId)
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByVA (uint64_t VA) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLines () const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByVA (uint64_t VA, uint32_t Length) const override
void getDataBytes (SmallVector< uint8_t, 32 > &Bytes) const override
void getFrontEndVersion (VersionInfo &Version) const override
void getBackEndVersion (VersionInfo &Version) const override
PDB_MemberAccess getAccess () const override
uint32_t getAddressOffset () const override
uint32_t getAddressSection () const override
uint32_t getAge () const override
SymIndexId getArrayIndexTypeId () const override
uint32_t getBaseDataOffset () const override
uint32_t getBaseDataSlot () const override
SymIndexId getBaseSymbolId () const override
PDB_BuiltinType getBuiltinType () const override
uint32_t getBitPosition () const override
std::string getCompilerName () const override
uint32_t getCountLiveRanges () const override
PDB_Lang getLanguage () const override
SymIndexId getLexicalParentId () const override
std::string getLibraryName () const override
uint32_t getLiveRangeStartAddressOffset () const override
uint32_t getLiveRangeStartAddressSection () const override
uint32_t getLiveRangeStartRelativeVirtualAddress () const override
codeview::RegisterId getLocalBasePointerRegisterId () const override
SymIndexId getLowerBoundId () const override
uint32_t getMemorySpaceKind () const override
std::string getName () const override
uint32_t getNumberOfAcceleratorPointerTags () const override
uint32_t getNumberOfColumns () const override
uint32_t getNumberOfModifiers () const override
uint32_t getNumberOfRegisterIndices () const override
uint32_t getNumberOfRows () const override
std::string getObjectFileName () const override
uint32_t getOemId () const override
SymIndexId getOemSymbolId () const override
uint32_t getOffsetInUdt () const override
PDB_Cpu getPlatform () const override
uint32_t getRank () const override
codeview::RegisterId getRegisterId () const override
uint32_t getRegisterType () const override
uint32_t getRelativeVirtualAddress () const override
uint32_t getSamplerSlot () const override
uint32_t getSignature () const override
uint32_t getSizeInUdt () const override
uint32_t getSlot () const override
std::string getSourceFileName () const override
std::unique_ptr< IPDBLineNumber > getSrcLineOnTypeDefn () const override
uint32_t getStride () const override
SymIndexId getSubTypeId () const override
std::string getSymbolsFileName () const override
SymIndexId getSymIndexId () const override
uint32_t getTargetOffset () const override
uint32_t getTargetRelativeVirtualAddress () const override
uint64_t getTargetVirtualAddress () const override
uint32_t getTargetSection () const override
uint32_t getTextureSlot () const override
uint32_t getTimeStamp () const override
uint32_t getToken () const override
uint32_t getUavSlot () const override
std::string getUndecoratedName () const override
std::string getUndecoratedNameEx (PDB_UndnameFlags Flags) const override
SymIndexId getUnmodifiedTypeId () const override
SymIndexId getUpperBoundId () const override
Variant getValue () const override
uint32_t getVirtualBaseDispIndex () const override
uint32_t getVirtualBaseOffset () const override
SymIndexId getVirtualTableShapeId () const override
std::unique_ptr< PDBSymbolTypeBuiltin > getVirtualBaseTableType () const override
PDB_DataKind getDataKind () const override
PDB_SymType getSymTag () const override
codeview::GUID getGuid () const override
int32_t getOffset () const override
int32_t getVirtualBasePointerOffset () const override
PDB_LocType getLocationType () const override
PDB_Machine getMachineType () const override
codeview::ThunkOrdinal getThunkOrdinal () const override
uint64_t getLength () const override
uint64_t getLiveRangeLength () const override
uint64_t getVirtualAddress () const override
PDB_UdtType getUdtKind () const override
bool hasCustomCallingConvention () const override
bool hasFarReturn () const override
bool isCode () const override
bool isCompilerGenerated () const override
bool isEditAndContinueEnabled () const override
bool isFunction () const override
bool getAddressTaken () const override
bool getNoStackOrdering () const override
bool hasAlloca () const override
bool hasAssignmentOperator () const override
bool hasCTypes () const override
bool hasCastOperator () const override
bool hasDebugInfo () const override
bool hasEH () const override
bool hasEHa () const override
bool hasInlAsm () const override
bool hasInlineAttribute () const override
bool hasInterruptReturn () const override
bool hasFramePointer () const override
bool hasLongJump () const override
bool hasManagedCode () const override
bool hasNestedTypes () const override
bool hasNoInlineAttribute () const override
bool hasNoReturnAttribute () const override
bool hasOptimizedCodeDebugInfo () const override
bool hasOverloadedOperator () const override
bool hasSEH () const override
bool hasSecurityChecks () const override
bool hasSetJump () const override
bool hasStrictGSCheck () const override
bool isAcceleratorGroupSharedLocal () const override
bool isAcceleratorPointerTagLiveRange () const override
bool isAcceleratorStubFunction () const override
bool isAggregated () const override
bool isIntroVirtualFunction () const override
bool isCVTCIL () const override
bool isDataAligned () const override
bool isHLSLData () const override
bool isHotpatchable () const override
bool isIndirectVirtualBaseClass () const override
bool isInterfaceUdt () const override
bool isIntrinsic () const override
bool isLTCG () const override
bool isLocationControlFlowDependent () const override
bool isMSILNetmodule () const override
bool isMatrixRowMajor () const override
bool isManagedCode () const override
bool isMSILCode () const override
bool isMultipleInheritance () const override
bool isNaked () const override
bool isNested () const override
bool isOptimizedAway () const override
bool isPacked () const override
bool isPointerBasedOnSymbolValue () const override
bool isPointerToDataMember () const override
bool isPointerToMemberFunction () const override
bool isPureVirtual () const override
bool isRValueReference () const override
bool isRefUdt () const override
bool isReference () const override
bool isRestrictedType () const override
bool isReturnValue () const override
bool isSafeBuffers () const override
bool isScoped () const override
bool isSdl () const override
bool isSingleInheritance () const override
bool isSplitted () const override
bool isStatic () const override
bool hasPrivateSymbols () const override
bool isUnreached () const override
bool isValueUdt () const override
bool isVirtual () const override
bool isVirtualBaseClass () const override
bool isVirtualInheritance () const override
bool wasInlined () const override
std::string getUnused () const override
Public Member Functions inherited from llvm::pdb::IPDBRawSymbol
virtual ~IPDBRawSymbol ()
Protected Member Functions
void initialize () override
Additional Inherited Members
Protected Attributes inherited from llvm::pdb::NativeRawSymbol
NativeSession & Session
PDB_SymType Tag
SymIndexId SymbolId
Detailed Description
Definition at line 24 of file NativeTypeFunctionSig.h.
Constructor & Destructor Documentation
NativeTypeFunctionSig() [1/2]
NativeTypeFunctionSig::NativeTypeFunctionSig (NativeSession & Session, SymIndexId Id, codeview::TypeIndex TI, codeview::ProcedureRecord Proc)
Definition at line 76 of file NativeTypeFunctionSig.cpp.
References llvm::pdb::FunctionSig.
NativeTypeFunctionSig() [2/2]
NativeTypeFunctionSig::NativeTypeFunctionSig (NativeSession & Session, SymIndexId Id, codeview::TypeIndex TI, codeview::MemberFunctionRecord MemberFunc)
Definition at line 83 of file NativeTypeFunctionSig.cpp.
~NativeTypeFunctionSig()
NativeTypeFunctionSig::~NativeTypeFunctionSig () override
Definition at line 99 of file NativeTypeFunctionSig.cpp.
References llvm::cantFail(), llvm::pdb::NativeSession::getPDBFile(), llvm::pdb::PDBFile::getPDBTpiStream(), llvm::codeview::LazyRandomTypeCollection::getType(), llvm::pdb::NativeRawSymbol::Session, and llvm::pdb::TpiStream::typeCollection().
Member Function Documentation
dump()
void NativeTypeFunctionSig::dump (raw_ostream & OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 108 of file NativeTypeFunctionSig.cpp.
References llvm::pdb::NativeRawSymbol::dump(), llvm::pdb::dumpSymbolField(), llvm::pdb::dumpSymbolIdField(), getCallingConvention(), getCount(), getThisAdjust(), getTypeId(), hasConstructor(), isConstructorVirtualBase(), isConstType(), isCxxReturnUdt(), isUnalignedType(), isVolatileType(), llvm::pdb::LexicalParent, llvm::pdb::NativeRawSymbol::Session, and llvm::pdb::Type.
findChildren()
std::unique_ptr< IPDBEnumSymbols > NativeTypeFunctionSig::findChildren (PDB_SymType Type) const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 134 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::ArgListRecord::ArgIndices, llvm::pdb::FunctionArg, and llvm::pdb::NativeRawSymbol::Session.
getCallingConvention()
PDB_CallingConv NativeTypeFunctionSig::getCallingConvention () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 151 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::ProcedureRecord::CallConv, llvm::codeview::MemberFunctionRecord::CallConv, MemberFunc, and Proc.
Referenced by dump().
getClassParentId()
SymIndexId NativeTypeFunctionSig::getClassParentId () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 144 of file NativeTypeFunctionSig.cpp.
getCount()
uint32_t NativeTypeFunctionSig::getCount () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 155 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::ProcedureRecord::getParameterCount(), llvm::codeview::MemberFunctionRecord::getParameterCount(), MemberFunc, and Proc.
Referenced by dump().
getThisAdjust()
int32_t NativeTypeFunctionSig::getThisAdjust () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 168 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::MemberFunctionRecord::getThisPointerAdjustment(), and MemberFunc.
Referenced by dump().
getTypeId()
SymIndexId NativeTypeFunctionSig::getTypeId () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 160 of file NativeTypeFunctionSig.cpp.
References llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::codeview::ProcedureRecord::getReturnType(), llvm::codeview::MemberFunctionRecord::getReturnType(), llvm::pdb::NativeSession::getSymbolCache(), MemberFunc, Proc, and llvm::pdb::NativeRawSymbol::Session.
Referenced by dump().
hasConstructor()
bool NativeTypeFunctionSig::hasConstructor () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 172 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::MemberFunctionRecord::getOptions(), MemberFunc, and llvm::pdb::None.
Referenced by dump().
initialize()
void NativeTypeFunctionSig::initialize () override protected virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 89 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::ProcedureRecord::ArgumentList, llvm::codeview::MemberFunctionRecord::ArgumentList, llvm::codeview::MemberFunctionRecord::ClassType, llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::pdb::NativeSession::getSymbolCache(), MemberFunc, Proc, and llvm::pdb::NativeRawSymbol::Session.
isConstructorVirtualBase()
bool NativeTypeFunctionSig::isConstructorVirtualBase () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 182 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::MemberFunctionRecord::getOptions(), MemberFunc, and llvm::pdb::None.
Referenced by dump().
isConstType()
bool NativeTypeFunctionSig::isConstType () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 180 of file NativeTypeFunctionSig.cpp.
Referenced by dump().
isCxxReturnUdt()
bool NativeTypeFunctionSig::isCxxReturnUdt () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 191 of file NativeTypeFunctionSig.cpp.
References llvm::codeview::ProcedureRecord::getOptions(), llvm::codeview::MemberFunctionRecord::getOptions(), MemberFunc, llvm::pdb::None, and Proc.
Referenced by dump().
isUnalignedType()
bool NativeTypeFunctionSig::isUnalignedType () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 197 of file NativeTypeFunctionSig.cpp.
Referenced by dump().
isVolatileType()
bool NativeTypeFunctionSig::isVolatileType () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 199 of file NativeTypeFunctionSig.cpp.
Referenced by dump().
Member Data Documentation
MemberFunc
codeview::MemberFunctionRecord llvm::pdb::NativeTypeFunctionSig::MemberFunc
Definition at line 60 of file NativeTypeFunctionSig.h.
Referenced by getCallingConvention(), getCount(), getThisAdjust(), getTypeId(), hasConstructor(), initialize(), isConstructorVirtualBase(), and isCxxReturnUdt().
Proc
codeview::ProcedureRecord llvm::pdb::NativeTypeFunctionSig::Proc
Definition at line 61 of file NativeTypeFunctionSig.h.
Referenced by getCallingConvention(), getCount(), getTypeId(), initialize(), and isCxxReturnUdt().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeTypeFunctionSig.h
lib/DebugInfo/PDB/Native/NativeTypeFunctionSig.cpp