LLVM: llvm::safestack::StackColoring Class Reference
llvm::safestack::StackColoring Class Reference
Compute live ranges of allocas.
#include "CodeGen/SafeStackColoring.h"
Classes
struct LiveRange
This class represents a set of interesting instructions where an alloca is live.
Public Member Functions
StackColoring (Function &F, ArrayRef< AllocaInst *> Allocas)
void run ()
void removeAllMarkers ()
const LiveRange & getLiveRange (AllocaInst *AI)
Returns a set of "interesting" instructions where the given alloca is live.
LiveRange getFullLiveRange ()
Returns a live range that represents an alloca that is live throughout the entire function.
Detailed Description
Compute live ranges of allocas.
Live ranges are represented as sets of "interesting" instructions, which are defined as instructions that may start or end an alloca's lifetime. These are:
lifetime.start and lifetime.end intrinsics
first instruction of any basic block Interesting instructions are numbered in the depth-first walk of the CFG, and in the program order inside each basic block.
Definition at line 37 of file SafeStackColoring.h.
Constructor & Destructor Documentation
StackColoring()
llvm::safestack::StackColoring::StackColoring (Function & F, ArrayRef< AllocaInst *> Allocas) inline
Definition at line 118 of file SafeStackColoring.h.
References getLiveRange(), removeAllMarkers(), and run().
Member Function Documentation
getFullLiveRange()
LiveRange llvm::safestack::StackColoring::getFullLiveRange () inline
Returns a live range that represents an alloca that is live throughout the entire function.
Definition at line 131 of file SafeStackColoring.h.
References llvm::safestack::StackColoring::LiveRange::AddRange(), assert(), and llvm::safestack::StackColoring::LiveRange::SetMaximum().
Referenced by run().
getLiveRange()
const StackColoring::LiveRange & StackColoring::getLiveRange (AllocaInst * AI)
Returns a set of "interesting" instructions where the given alloca is live.
Not all instructions in a function are interesting: we pick a set that is large enough for LiveRange::Overlaps to be correct.
Definition at line 41 of file SafeStackColoring.cpp.
References assert(), I, llvm::Instruction::isLifetimeStartOrEnd(), and IT.
Referenced by StackColoring().
removeAllMarkers()
bool StackColoring::removeAllMarkers ()
Definition at line 56 of file SafeStackColoring.cpp.
References llvm::dbgs(), llvm::depth_first(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::Instruction::eraseFromParent(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::User::getOperand(), I, IT, LLVM_DEBUG, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::BitVector::reset(), llvm::BitVector::resize(), llvm::BitVector::set(), llvm::BitVector::test(), and llvm::Value::users().
Referenced by StackColoring().
run()
void StackColoring::run ()
Definition at line 283 of file SafeStackColoring.cpp.
References ClColoring, getFullLiveRange(), I, LLVM_DEBUG, and llvm::BitVector::test().
Referenced by StackColoring().
The documentation for this class was generated from the following files:
lib/CodeGen/SafeStackColoring.h
lib/CodeGen/SafeStackColoring.cpp
lib/CodeGen/StackColoring.cpp