LLVM: llvm::MipsSERegisterInfo Class Reference
llvm::MipsSERegisterInfo Class Reference
#include "Target/Mips/MipsSERegisterInfo.h"
Public Member Functions
MipsSERegisterInfo ()
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
const TargetRegisterClass * intRegClass (unsigned Size) const override
Return GPR register class.
Public Member Functions inherited from llvm::MipsRegisterInfo
MipsRegisterInfo ()
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind) const override
Code Generation virtual methods...
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Mips Callee Saved Registers.
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Stack Frame Processing Methods.
bool canRealignStack (const MachineFunction &MF) const override
Register getFrameRegister (const MachineFunction &MF) const override
Debug information queries.
Additional Inherited Members
Public Types inherited from llvm::MipsRegisterInfo
enum MipsPtrClass { MipsPtrClass::Default = 0, MipsPtrClass::GPR16MM = 1, MipsPtrClass::StackPointer = 2, MipsPtrClass::GlobalPointer = 3 }
Static Public Member Functions inherited from llvm::MipsRegisterInfo
static unsigned getPICCallReg ()
Get PIC indirect call register.
static const uint32_t * getMips16RetHelperMask ()
Detailed Description
Definition at line 22 of file MipsSERegisterInfo.h.
Constructor & Destructor Documentation
MipsSERegisterInfo()
MipsSERegisterInfo::MipsSERegisterInfo ()
Definition at line 41 of file MipsSERegisterInfo.cpp.
References requiresRegisterScavenging().
Member Function Documentation
intRegClass()
const TargetRegisterClass * MipsSERegisterInfo::intRegClass (unsigned Size) const override virtual
Return GPR register class.
Implements llvm::MipsRegisterInfo.
Definition at line 54 of file MipsSERegisterInfo.cpp.
References assert().
requiresFrameIndexScavenging()
bool MipsSERegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const override
Definition at line 49 of file MipsSERegisterInfo.cpp.
Referenced by requiresRegisterScavenging().
requiresRegisterScavenging()
bool MipsSERegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const override
Definition at line 44 of file MipsSERegisterInfo.cpp.
References requiresFrameIndexScavenging().
Referenced by MipsSERegisterInfo().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsSERegisterInfo.h
lib/Target/Mips/MipsSERegisterInfo.cpp