LLVM: llvm::MCRegAliasIterator Class Reference
llvm::MCRegAliasIterator Class Reference
MCRegAliasIterator enumerates all registers aliasing Reg.
#include "llvm/MC/MCRegisterInfo.h"
Public Member Functions
MCRegAliasIterator (MCRegister Reg, const MCRegisterInfo *MCRI, bool IncludeSelf)
bool isValid () const
MCRegister operator* () const
void advance ()
void operator++ ()
Detailed Description
MCRegAliasIterator enumerates all registers aliasing Reg.
If IncludeSelf is set, Reg itself is included in the list. This iterator does not guarantee any ordering or that entries are unique.
Definition at line 772 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
MCRegAliasIterator()
llvm::MCRegAliasIterator::MCRegAliasIterator (MCRegister Reg, const MCRegisterInfo * MCRI, bool IncludeSelf) inline
Definition at line 783 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegUnitRootIterator::isValid(), and SI.
Member Function Documentation
advance()
void llvm::MCRegAliasIterator::advance () inline
Definition at line 804 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegUnitRootIterator::isValid(), and SI.
isValid()
bool llvm::MCRegAliasIterator::isValid () const inline
Definition at line 797 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by addLiveInRegs(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), addRegAndItsAliases(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), AnyAliasLiveIn(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::calculateDbgEntityHistory(), CheckForLiveRegDef(), collectRegDefs(), llvm::createLanaiDelaySlotFillerPass(), llvm::createSparcDelaySlotFillerPass(), CriticalPathStep(), llvm::MachineRegisterInfo::disableCalleeSavedRegister(), findDeadCallerSavedReg(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::RegScavenger::getRegsAvailable(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::CCState::HandleByVal(), INITIALIZE_PASS(), InstructionStoresToFI(), isCallableFunction(), isCallerPreservedOrConstPhysReg(), isCoalescable(), llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::MachineRegisterInfo::isPhysRegModified(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::CCState::IsShadowAllocatedReg(), needToReserveScavengingSpillSlots(), llvm::HexagonMCChecker::reportBranchErrors(), llvm::AMDGPURegisterInfo::reserveRegisterTuples(), llvm::R600RegisterInfo::reserveRegisterTuples(), llvm::rdf::Liveness::resetKills(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::RegScavenger::scavengeRegister(), setAliasRegs(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::CriticalAntiDepBreaker::StartBlock(), and llvm::AggressiveAntiDepBreaker::StartBlock().
operator*()
MCRegister llvm::MCRegAliasIterator::operator* () const inline
Definition at line 799 of file MCRegisterInfo.h.
References assert(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and SI.
operator++()
void llvm::MCRegAliasIterator::operator++ () inline
Definition at line 822 of file MCRegisterInfo.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/MC/MCRegisterInfo.h