LLVM: llvm::MemorySSAAnnotatedWriter Class Reference
llvm::MemorySSAAnnotatedWriter Class Reference
An assembly annotator class to print Memory SSA information in comments.
Public Member Functions
MemorySSAAnnotatedWriter (const MemorySSA *M)
void emitBasicBlockStartAnnot (const BasicBlock *BB, formatted_raw_ostream &OS) override
emitBasicBlockStartAnnot - This may be implemented to emit a string right after the basic block label, but before the first instruction in the block.
void emitInstructionAnnot (const Instruction *I, formatted_raw_ostream &OS) override
emitInstructionAnnot - This may be implemented to emit a string right before an instruction is emitted.
Public Member Functions inherited from llvm::AssemblyAnnotationWriter
virtual ~AssemblyAnnotationWriter ()
virtual void emitFunctionAnnot (const Function *, formatted_raw_ostream &)
emitFunctionAnnot - This may be implemented to emit a string right before the start of a function.
virtual void emitBasicBlockEndAnnot (const BasicBlock *, formatted_raw_ostream &)
emitBasicBlockEndAnnot - This may be implemented to emit a string right after the basic block.
virtual void printInfoComment (const Value &, formatted_raw_ostream &)
printInfoComment - This may be implemented to emit a comment to the right of an instruction or global value.
Friends
class MemorySSA
Detailed Description
An assembly annotator class to print Memory SSA information in comments.
Definition at line 99 of file MemorySSA.cpp.
Constructor & Destructor Documentation
MemorySSAAnnotatedWriter()
llvm::MemorySSAAnnotatedWriter::MemorySSAAnnotatedWriter (const MemorySSA * M) inline
Definition at line 105 of file MemorySSA.cpp.
Member Function Documentation
emitBasicBlockStartAnnot()
void llvm::MemorySSAAnnotatedWriter::emitBasicBlockStartAnnot (const BasicBlock * , formatted_raw_ostream &) inline override virtual
emitBasicBlockStartAnnot - This may be implemented to emit a string right after the basic block label, but before the first instruction in the block.
Reimplemented from llvm::AssemblyAnnotationWriter.
Definition at line 107 of file MemorySSA.cpp.
References llvm::MemorySSA::getMemoryAccess().
emitInstructionAnnot()
void llvm::MemorySSAAnnotatedWriter::emitInstructionAnnot (const Instruction * , formatted_raw_ostream &) inline override virtual
emitInstructionAnnot - This may be implemented to emit a string right before an instruction is emitted.
Reimplemented from llvm::AssemblyAnnotationWriter.
Definition at line 113 of file MemorySSA.cpp.
References assert(), C, llvm::lltok::equal, llvm::MemoryLocation::get(), llvm::MemorySSA::getMemoryAccess(), llvm::MemoryUseOrDef::getMemoryInst(), llvm::operator==(), and llvm::Other.
Friends And Related Function Documentation
MemorySSA
friend class MemorySSA friend
Definition at line 100 of file MemorySSA.cpp.
The documentation for this class was generated from the following file:
lib/Analysis/MemorySSA.cpp