LLVM: llvm::DbgLabelInstrMap Class Reference
llvm::DbgLabelInstrMap Class Reference
For each inlined instance of a source-level label, keep the corresponding DBG_LABEL instruction.
#include "llvm/CodeGen/DbgEntityHistoryCalculator.h"
Public Types
using InlinedEntity = std::pair< const DINode *, const DILocation * >
using InstrMap = MapVector< InlinedEntity, const MachineInstr * >
Public Member Functions
void addInstr (InlinedEntity Label, const MachineInstr &MI)
bool empty () const
void clear ()
InstrMap::const_iterator begin () const
InstrMap::const_iterator end () const
Detailed Description
For each inlined instance of a source-level label, keep the corresponding DBG_LABEL instruction.
The DBG_LABEL instruction could be used to generate a temporary (assembler) label before it.
Definition at line 104 of file DbgEntityHistoryCalculator.h.
Member Typedef Documentation
InlinedEntity
using llvm::DbgLabelInstrMap::InlinedEntity = std::pair<const DINode *, const DILocation *>
Definition at line 106 of file DbgEntityHistoryCalculator.h.
InstrMap
using llvm::DbgLabelInstrMap::InstrMap = MapVector<InlinedEntity, const MachineInstr *>
Definition at line 107 of file DbgEntityHistoryCalculator.h.
Member Function Documentation
addInstr()
void DbgLabelInstrMap::addInstr (InlinedEntity Label, const MachineInstr & MI)
Definition at line 92 of file DbgEntityHistoryCalculator.cpp.
References assert(), llvm::MachineInstr::isDebugLabel(), and MI.
Referenced by llvm::calculateDbgEntityHistory().
begin()
InstrMap::const_iterator llvm::DbgLabelInstrMap::begin () const inline
Definition at line 117 of file DbgEntityHistoryCalculator.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::begin().
clear()
void llvm::DbgLabelInstrMap::clear () inline
Definition at line 116 of file DbgEntityHistoryCalculator.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear().
Referenced by llvm::DebugHandlerBase::endFunction().
empty()
bool llvm::DbgLabelInstrMap::empty () const inline
Definition at line 115 of file DbgEntityHistoryCalculator.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::empty().
Referenced by llvm::DebugHandlerBase::beginFunction().
end()
InstrMap::const_iterator llvm::DbgLabelInstrMap::end () const inline
Definition at line 118 of file DbgEntityHistoryCalculator.h.
References llvm::calculateDbgEntityHistory(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), and TRI.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DbgEntityHistoryCalculator.h
lib/CodeGen/AsmPrinter/DbgEntityHistoryCalculator.cpp