LLVM: llvm::codeview::TypeCollection Class Reference
llvm::codeview::TypeCollection Class Reference abstract
#include "llvm/DebugInfo/CodeView/TypeCollection.h"
Public Member Functions
virtual ~TypeCollection ()=default
bool empty ()
virtual Optional< TypeIndex > getFirst ()=0
virtual Optional< TypeIndex > getNext (TypeIndex Prev)=0
virtual CVType getType (TypeIndex Index)=0
virtual StringRef getTypeName (TypeIndex Index)=0
virtual bool contains (TypeIndex Index)=0
virtual uint32_t size ()=0
virtual uint32_t capacity ()=0
template<typename TFunc >
void ForEachRecord (TFunc Func)
Detailed Description
Definition at line 19 of file TypeCollection.h.
Constructor & Destructor Documentation
~TypeCollection()
virtual llvm::codeview::TypeCollection::~TypeCollection () virtual default
Member Function Documentation
capacity()
virtual uint32_t llvm::codeview::TypeCollection::capacity () pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by empty().
contains()
virtual bool llvm::codeview::TypeCollection::contains (TypeIndex Index) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by empty().
empty()
bool llvm::codeview::TypeCollection::empty () inline
Definition at line 23 of file TypeCollection.h.
References capacity(), contains(), getFirst(), getNext(), getType(), getTypeName(), and size().
Referenced by llvm::codeview::TypeTableCollection::getFirst(), llvm::codeview::AppendingTypeTableBuilder::getFirst(), llvm::codeview::MergingTypeTableBuilder::getFirst(), and llvm::codeview::GlobalTypeTableBuilder::getFirst().
ForEachRecord()
template<typename TFunc > void llvm::codeview::TypeCollection::ForEachRecord (TFunc Func) inline
Definition at line 34 of file TypeCollection.h.
References getFirst(), getNext(), getType(), llvm::Optional< T >::hasValue(), and N.
Referenced by llvm::codeview::LocallyHashedType::hashTypeCollection(), and llvm::codeview::GloballyHashedType::hashTypeCollection().
getFirst()
virtual Optional<TypeIndex> llvm::codeview::TypeCollection::getFirst () pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by empty(), ForEachRecord(), and visitMemberRecord().
getNext()
virtual Optional<TypeIndex> llvm::codeview::TypeCollection::getNext (TypeIndex Prev) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by empty(), ForEachRecord(), and visitMemberRecord().
getType()
virtual CVType llvm::codeview::TypeCollection::getType (TypeIndex Index) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by llvm::codeview::computeTypeName(), empty(), ForEachRecord(), and visitMemberRecord().
getTypeName()
virtual StringRef llvm::codeview::TypeCollection::getTypeName (TypeIndex Index) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by empty(), and llvm::codeview::printTypeIndex().
size()
virtual uint32_t llvm::codeview::TypeCollection::size () pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by empty(), and llvm::codeview::TypeDumpVisitor::visitTypeBegin().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeCollection.h