LLVM: llvm::orc::ObjectTransformLayer Class Reference
llvm::orc::ObjectTransformLayer Class Reference
#include "llvm/ExecutionEngine/Orc/ObjectTransformLayer.h"
Public Types
using TransformFunction = std::function< Expected< std::unique_ptr< MemoryBuffer > >(std::unique_ptr< MemoryBuffer >)>
Public Member Functions
ObjectTransformLayer (ExecutionSession &ES, ObjectLayer &BaseLayer, TransformFunction Transform=TransformFunction())
void emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O) override
Emit should materialize the given IR.
void setTransform (TransformFunction Transform)
Public Member Functions inherited from llvm::orc::ObjectLayer
ObjectLayer (ExecutionSession &ES)
virtual ~ObjectLayer ()
ExecutionSession & getExecutionSession ()
Returns the execution session for this layer.
virtual Error add (JITDylib &JD, std::unique_ptr< MemoryBuffer > O, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Detailed Description
Definition at line 25 of file ObjectTransformLayer.h.
Member Typedef Documentation
TransformFunction
using llvm::orc::ObjectTransformLayer::TransformFunction = std::function<Expected<std::unique_ptr<MemoryBuffer> >(std::unique_ptr<MemoryBuffer>)>
Definition at line 29 of file ObjectTransformLayer.h.
Constructor & Destructor Documentation
ObjectTransformLayer()
llvm::orc::ObjectTransformLayer::ObjectTransformLayer (ExecutionSession & ES, ObjectLayer & BaseLayer, TransformFunction Transform = TransformFunction())
Definition at line 15 of file ObjectTransformLayer.cpp.
Member Function Documentation
emit()
void llvm::orc::ObjectTransformLayer::emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O) override virtual
Emit should materialize the given IR.
Implements llvm::orc::ObjectLayer.
Definition at line 20 of file ObjectTransformLayer.cpp.
References assert(), llvm::orc::ObjectLayer::emit(), llvm::orc::MaterializationResponsibility::failMaterialization(), llvm::orc::ObjectLayer::getExecutionSession(), and llvm::orc::ExecutionSession::reportError().
setTransform()
void llvm::orc::ObjectTransformLayer::setTransform (TransformFunction Transform) inline
Definition at line 37 of file ObjectTransformLayer.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ObjectTransformLayer.h
lib/ExecutionEngine/Orc/ObjectTransformLayer.cpp