LLVM: llvm::DebugInfoFinder Class Reference
llvm::DebugInfoFinder Class Reference
Utility to find all debug info in a module.
#include "llvm/IR/DebugInfo.h"
Public Types
using compile_unit_iterator = SmallVectorImpl< DICompileUnit * >::const_iterator
using subprogram_iterator = SmallVectorImpl< DISubprogram * >::const_iterator
using global_variable_expression_iterator = SmallVectorImpl< DIGlobalVariableExpression * >::const_iterator
using type_iterator = SmallVectorImpl< DIType * >::const_iterator
using scope_iterator = SmallVectorImpl< DIScope * >::const_iterator
Public Member Functions
void processModule (const Module &M)
Process entire module and collect debug info anchors.
void processInstruction (const Module &M, const Instruction &I)
Process a single instruction and collect debug info anchors.
void processDeclare (const Module &M, const DbgDeclareInst *DDI)
Process DbgDeclareInst.
void processValue (const Module &M, const DbgValueInst *DVI)
Process DbgValueInst.
void processLocation (const Module &M, const DILocation *Loc)
Process debug info location.
void reset ()
Clear all lists.
iterator_range< compile_unit_iterator > compile_units () const
iterator_range< subprogram_iterator > subprograms () const
iterator_range< global_variable_expression_iterator > global_variables () const
iterator_range< type_iterator > types () const
iterator_range< scope_iterator > scopes () const
unsigned compile_unit_count () const
unsigned global_variable_count () const
unsigned subprogram_count () const
unsigned type_count () const
unsigned scope_count () const
Detailed Description
Utility to find all debug info in a module.
DebugInfoFinder tries to list all debug info MDNodes used in a module. To list debug info MDNodes used by an instruction, DebugInfoFinder uses processDeclare, processValue and processLocation to handle DbgDeclareInst, DbgValueInst and DbgLoc attached to instructions. processModule will go through all DICompileUnits in llvm.dbg.cu and list debug info MDNodes used by the CUs.
Definition at line 64 of file DebugInfo.h.
Member Typedef Documentation
compile_unit_iterator
using llvm::DebugInfoFinder::compile_unit_iterator = SmallVectorImpl<DICompileUnit *>::const_iterator
Definition at line 96 of file DebugInfo.h.
global_variable_expression_iterator
using llvm::DebugInfoFinder::global_variable_expression_iterator = SmallVectorImpl<DIGlobalVariableExpression *>::const_iterator
Definition at line 99 of file DebugInfo.h.
scope_iterator
using llvm::DebugInfoFinder::scope_iterator = SmallVectorImpl<DIScope *>::const_iterator
Definition at line 101 of file DebugInfo.h.
subprogram_iterator
using llvm::DebugInfoFinder::subprogram_iterator = SmallVectorImpl<DISubprogram *>::const_iterator
Definition at line 97 of file DebugInfo.h.
type_iterator
using llvm::DebugInfoFinder::type_iterator = SmallVectorImpl<DIType *>::const_iterator
Definition at line 100 of file DebugInfo.h.
Member Function Documentation
compile_unit_count()
unsigned llvm::DebugInfoFinder::compile_unit_count () const inline
Definition at line 123 of file DebugInfo.h.
Referenced by llvm::CloneFunctionInto().
compile_units()
iterator_range<compile_unit_iterator> llvm::DebugInfoFinder::compile_units () const inline
Definition at line 103 of file DebugInfo.h.
References llvm::make_range().
Referenced by llvm::CloneFunctionInto(), printFile(), and StripSymbolNames().
global_variable_count()
unsigned llvm::DebugInfoFinder::global_variable_count () const inline
Definition at line 124 of file DebugInfo.h.
global_variables()
iterator_range<global_variable_expression_iterator> llvm::DebugInfoFinder::global_variables () const inline
Definition at line 111 of file DebugInfo.h.
References llvm::make_range().
Referenced by printFile().
processDeclare()
void DebugInfoFinder::processDeclare (const Module & M, const DbgDeclareInst * DDI)
Process DbgDeclareInst.
Definition at line 197 of file DebugInfo.cpp.
References llvm::dyn_cast(), llvm::DbgVariableIntrinsic::getVariable(), and N.
processInstruction()
void DebugInfoFinder::processInstruction (const Module & M, const Instruction & I)
Process a single instruction and collect debug info anchors.
Definition at line 106 of file DebugInfo.cpp.
References llvm::Instruction::getDebugLoc().
Referenced by llvm::CloneBasicBlock().
processLocation()
void DebugInfoFinder::processLocation (const Module & M, const DILocation * Loc)
Process debug info location.
Definition at line 117 of file DebugInfo.cpp.
References D, llvm::DIScope::getScope(), llvm::DIType::getScope(), llvm::Ref, and llvm::ARM_MB::ST.
processModule()
void DebugInfoFinder::processModule (const Module & M)
Process entire module and collect debug info anchors.
Definition at line 62 of file DebugInfo.cpp.
References llvm::Module::debug_compile_units(), F(), llvm::Module::functions(), llvm::DICompileUnit::getEnumTypes(), llvm::DICompileUnit::getGlobalVariables(), llvm::DICompileUnit::getImportedEntities(), llvm::DICompileUnit::getRetainedTypes(), I, and llvm::Import.
Referenced by INITIALIZE_PASS(), and StripSymbolNames().
processValue()
void DebugInfoFinder::processValue (const Module & M, const DbgValueInst * DVI)
Process DbgValueInst.
Definition at line 213 of file DebugInfo.cpp.
References llvm::dyn_cast(), llvm::MDNode::getNumOperands(), llvm::DbgVariableIntrinsic::getVariable(), and N.
reset()
void DebugInfoFinder::reset ()
Clear all lists.
Definition at line 53 of file DebugInfo.cpp.
scope_count()
unsigned llvm::DebugInfoFinder::scope_count () const inline
Definition at line 127 of file DebugInfo.h.
scopes()
iterator_range<scope_iterator> llvm::DebugInfoFinder::scopes () const inline
Definition at line 119 of file DebugInfo.h.
References llvm::make_range().
subprogram_count()
unsigned llvm::DebugInfoFinder::subprogram_count () const inline
Definition at line 125 of file DebugInfo.h.
subprograms()
iterator_range<subprogram_iterator> llvm::DebugInfoFinder::subprograms () const inline
Definition at line 107 of file DebugInfo.h.
References llvm::make_range().
Referenced by llvm::CloneFunctionInto(), printFile(), and StripSymbolNames().
type_count()
unsigned llvm::DebugInfoFinder::type_count () const inline
Definition at line 126 of file DebugInfo.h.
types()
iterator_range<type_iterator> llvm::DebugInfoFinder::types () const inline
Definition at line 115 of file DebugInfo.h.
References llvm::make_range().
Referenced by llvm::CloneFunctionInto(), and printFile().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfo.h
lib/IR/DebugInfo.cpp