LLVM: llvm::LLLexer Class Reference
llvm::LLLexer Class Reference
#include "AsmParser/LLLexer.h"
Public Types
typedef SMLoc LocTy
Public Member Functions
LLLexer (StringRef StartBuf, SourceMgr &SM, SMDiagnostic &, LLVMContext &C)
lltok::Kind Lex ()
LocTy getLoc () const
lltok::Kind getKind () const
const std::string & getStrVal () const
Type * getTyVal () const
unsigned getUIntVal () const
const APSInt & getAPSIntVal () const
const APFloat & getAPFloatVal () const
void setIgnoreColonInIdentifiers (bool val)
bool Error (LocTy ErrorLoc, const Twine &Msg) const
bool Error (const Twine &Msg) const
void Warning (LocTy WarningLoc, const Twine &Msg) const
void Warning (const Twine &Msg) const
Detailed Description
Definition at line 28 of file LLLexer.h.
Member Typedef Documentation
LocTy
typedef SMLoc llvm::LLLexer::LocTy
Definition at line 56 of file LLLexer.h.
Constructor & Destructor Documentation
LLLexer()
LLLexer::LLLexer (StringRef StartBuf, SourceMgr & SM, SMDiagnostic & Err, LLVMContext & C) explicit
Definition at line 159 of file LLLexer.cpp.
Member Function Documentation
Error() [1/2]
bool LLLexer::Error (LocTy ErrorLoc, const Twine & Msg) const
Definition at line 28 of file LLLexer.cpp.
References llvm::SourceMgr::DK_Error, and llvm::SourceMgr::GetMessage().
Referenced by llvm::LLParser::getContext(), and setIgnoreColonInIdentifiers().
Error() [2/2]
bool llvm::LLLexer::Error (const Twine & Msg) const inline
Definition at line 70 of file LLLexer.h.
References Error(), getLoc(), and Warning().
Referenced by Error().
getAPFloatVal()
const APFloat& llvm::LLLexer::getAPFloatVal () const inline
Definition at line 63 of file LLLexer.h.
Referenced by FunctionNumber().
getAPSIntVal()
const APSInt& llvm::LLLexer::getAPSIntVal () const inline
Definition at line 62 of file LLLexer.h.
Referenced by createGlobalFwdRef(), FunctionNumber(), and parseOptionalLinkageAux().
getKind()
lltok::Kind llvm::LLLexer::getKind () const inline
Definition at line 58 of file LLLexer.h.
Referenced by createGlobalFwdRef(), FunctionNumber(), llvm::LLParser::getContext(), maybeSetDSOLocal(), parseOptionalLinkageAux(), and llvm::LLParser::parseStandaloneConstantValue().
getLoc()
LocTy llvm::LLLexer::getLoc () const inline
Definition at line 57 of file LLLexer.h.
References llvm::SMLoc::getFromPointer().
Referenced by Error(), FunctionNumber(), llvm::LLParser::getContext(), maybeSetDSOLocal(), parseOptionalLinkageAux(), llvm::LLParser::parseStandaloneConstantValue(), llvm::LLParser::Run(), and Warning().
getStrVal()
const std::string& llvm::LLLexer::getStrVal () const inline
Definition at line 59 of file LLLexer.h.
Referenced by createGlobalFwdRef(), FunctionNumber(), maybeSetDSOLocal(), and parseOptionalLinkageAux().
getTyVal()
Type* llvm::LLLexer::getTyVal () const inline
Definition at line 60 of file LLLexer.h.
Referenced by parseOptionalLinkageAux().
getUIntVal()
unsigned llvm::LLLexer::getUIntVal () const inline
Definition at line 61 of file LLLexer.h.
Referenced by FunctionNumber(), maybeSetDSOLocal(), and parseOptionalLinkageAux().
Lex()
lltok::Kind llvm::LLLexer::Lex () inline
Definition at line 52 of file LLLexer.h.
Referenced by createGlobalFwdRef(), FunctionNumber(), llvm::LLParser::getContext(), if(), maybeSetDSOLocal(), parseOptionalLinkageAux(), llvm::LLParser::parseStandaloneConstantValue(), llvm::LLParser::parseTypeAtBeginning(), and llvm::LLParser::Run().
setIgnoreColonInIdentifiers()
void llvm::LLLexer::setIgnoreColonInIdentifiers (bool val) inline
Definition at line 65 of file LLLexer.h.
References Error().
Warning() [1/2]
void LLLexer::Warning (LocTy WarningLoc, const Twine & Msg) const
Definition at line 33 of file LLLexer.cpp.
References llvm::SourceMgr::DK_Warning, and llvm::SourceMgr::PrintMessage().
Referenced by Error().
Warning() [2/2]
void llvm::LLLexer::Warning (const Twine & Msg) const inline
Definition at line 73 of file LLLexer.h.
References getLoc(), and Warning().
Referenced by Warning().
The documentation for this class was generated from the following files:
lib/AsmParser/LLLexer.h
lib/AsmParser/LLLexer.cpp