LLVM: llvm::BranchFolder Class Reference
llvm::BranchFolder Class Reference
#include "CodeGen/BranchFolding.h"
Classes
class MBFIWrapper
This class keeps track of branch frequencies of newly created blocks and tail-merged blocks.
Public Member Functions
BranchFolder (bool defaultEnableTailMerge, bool CommonHoist, MBFIWrapper &FreqInfo, const MachineBranchProbabilityInfo &ProbInfo, ProfileSummaryInfo *PSI, unsigned MinTailLength=0)
bool OptimizeFunction (MachineFunction &MF, const TargetInstrInfo *tii, const TargetRegisterInfo *tri, MachineModuleInfo *mmi, MachineLoopInfo *mli=nullptr, bool AfterPlacement=false)
Perhaps branch folding, tail merging and other CFG optimizations on the given function.
Detailed Description
Definition at line 35 of file BranchFolding.h.
Constructor & Destructor Documentation
BranchFolder()
BranchFolder::BranchFolder (bool defaultEnableTailMerge, bool CommonHoist, MBFIWrapper & FreqInfo, const MachineBranchProbabilityInfo & ProbInfo, ProfileSummaryInfo * PSI, unsigned MinTailLength = 0) explicit
Definition at line 143 of file BranchFolding.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, llvm::dbgs(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::erase(), llvm::MachineFunction::eraseCallSiteInfo(), FlagEnableTailMerge, llvm::for_each(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::IgnoreBundle, LLVM_DEBUG, MI, llvm::MachineBasicBlock::pred_empty(), llvm::MachineLoopInfo::removeBlock(), llvm::MachineBasicBlock::removeSuccessor(), llvm::MachineBasicBlock::succ_empty(), llvm::MachineBasicBlock::succ_end(), and TailMergeSize.
Member Function Documentation
OptimizeFunction()
bool BranchFolder::OptimizeFunction (MachineFunction & MF, const TargetInstrInfo * tii, const TargetRegisterInfo * tri, MachineModuleInfo * mmi, MachineLoopInfo * mli = nullptr, bool AfterPlacement = false)
Perhaps branch folding, tail merging and other CFG optimizations on the given function.
Block placement changes the layout and may create new tail merging opportunities.
Definition at line 183 of file BranchFolding.cpp.
References llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::invalidateLiveness(), llvm::TargetRegisterInfo::trackLivenessAfterRegAlloc(), and llvm::MachineRegisterInfo::tracksLiveness().
Referenced by INITIALIZE_PASS().
The documentation for this class was generated from the following files:
lib/CodeGen/BranchFolding.h
lib/CodeGen/BranchFolding.cpp