LLVM: llvm::TargetLibraryInfo Class Reference
llvm::TargetLibraryInfo Class Reference
Provides information about what library functions are available for the current target.
#include "llvm/Analysis/TargetLibraryInfo.h"
Public Member Functions
TargetLibraryInfo (const TargetLibraryInfoImpl &Impl, Optional< const Function *> F=None)
TargetLibraryInfo (const TargetLibraryInfo &TLI)
TargetLibraryInfo (TargetLibraryInfo &&TLI)
TargetLibraryInfo & operator= (const TargetLibraryInfo &TLI)
TargetLibraryInfo & operator= (TargetLibraryInfo &&TLI)
bool getLibFunc (StringRef funcName, LibFunc &F) const
Searches for a particular function name.
bool getLibFunc (const Function &FDecl, LibFunc &F) const
bool getLibFunc (ImmutableCallSite CS, LibFunc &F) const
If a callsite does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
void disableAllFunctions () LLVM_ATTRIBUTE_UNUSED
Disables all builtins.
void setUnavailable (LibFunc F) LLVM_ATTRIBUTE_UNUSED
Forces a function to be marked as unavailable.
TargetLibraryInfoImpl::AvailabilityState getState (LibFunc F) const
bool has (LibFunc F) const
Tests whether a library function is available.
bool isFunctionVectorizable (StringRef F, unsigned VF) const
bool isFunctionVectorizable (StringRef F) const
StringRef getVectorizedFunction (StringRef F, unsigned VF) const
bool hasOptimizedCodeGen (LibFunc F) const
Tests if the function is both available and a candidate for optimized code generation.
StringRef getName (LibFunc F) const
Attribute::AttrKind getExtAttrForI32Param (bool Signed=true) const
Returns extension attribute kind to be used for i32 parameters corresponding to C-level int or unsigned int.
Attribute::AttrKind getExtAttrForI32Return (bool Signed=true) const
Returns extension attribute kind to be used for i32 return values corresponding to C-level int or unsigned int.
unsigned getWCharSize (const Module &M) const
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
bool invalidate (Module &, const PreservedAnalyses &, ModuleAnalysisManager::Invalidator &)
Handle invalidation from the pass manager.
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
unsigned getWidestVF (StringRef ScalarF) const
Returns the largest vectorization factor used in the list of vector functions.
Friends
class TargetLibraryAnalysis
class TargetLibraryInfoWrapperPass
Detailed Description
Provides information about what library functions are available for the current target.
This both allows optimizations to handle them specially and frontends to disable such optimizations through -fno-builtin etc.
Definition at line 212 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
TargetLibraryInfo() [1/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfoImpl & Impl, Optional< const Function *> F = None) inline explicit
Definition at line 224 of file TargetLibraryInfo.h.
References F().
TargetLibraryInfo() [2/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfo & TLI) inline
Definition at line 248 of file TargetLibraryInfo.h.
TargetLibraryInfo() [3/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (TargetLibraryInfo && TLI) inline
Definition at line 250 of file TargetLibraryInfo.h.
Member Function Documentation
disableAllFunctions()
void llvm::TargetLibraryInfo::disableAllFunctions () inline
Disables all builtins.
This can be used for options like -fno-builtin.
Definition at line 285 of file TargetLibraryInfo.h.
References llvm::BitVector::set().
getExtAttrForI32Param()
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Param (bool Signed = true) const inline
Returns extension attribute kind to be used for i32 parameters corresponding to C-level int or unsigned int.
May be zeroext, signext, or none.
Definition at line 359 of file TargetLibraryInfo.h.
References llvm::Attribute::None, and Signed.
Referenced by getOrInsertValueProfilingCall(), and shouldKeepInEntry().
getExtAttrForI32Return()
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Return (bool Signed = true) const inline
Returns extension attribute kind to be used for i32 return values corresponding to C-level int or unsigned int.
May be zeroext, signext, or none.
Definition at line 370 of file TargetLibraryInfo.h.
References llvm::Attribute::None, and Signed.
getLibFunc() [1/3]
bool llvm::TargetLibraryInfo::getLibFunc (StringRef funcName, LibFunc & F) const inline
Searches for a particular function name.
If it is one of the known library functions, return true and set F to the corresponding value.
Definition at line 267 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getLibFunc().
Referenced by llvm::callsGCLeafFunction(), llvm::canConstantFoldCallTo(), getAllocationDataForFunction(), llvm::MemoryLocation::getForArgument(), llvm::getIntrinsicForCallSite(), llvm::PPCTTIImpl::getUserCost(), hasAnalyzableMemoryWrite(), llvm::inferLibFuncAttributes(), llvm::isFreeCall(), isKnownLibFunction(), isLocallyOpenedFile(), llvm::isMathLibCallNoop(), isWriteOnlyParam(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), llvm::FortifiedLibCallSimplifier::optimizeCall(), optimizeCall(), and runPartiallyInlineLibCalls().
getLibFunc() [2/3]
bool llvm::TargetLibraryInfo::getLibFunc (const Function & FDecl, LibFunc & F) const inline
Definition at line 271 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getLibFunc().
getLibFunc() [3/3]
bool llvm::TargetLibraryInfo::getLibFunc (ImmutableCallSite CS, LibFunc & F) const inline
If a callsite does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
Definition at line 277 of file TargetLibraryInfo.h.
References llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), and llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isNoBuiltin().
getName()
StringRef llvm::TargetLibraryInfo::getName (LibFunc F) const inline
Definition at line 346 of file TargetLibraryInfo.h.
References assert(), F(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitPutChar(), llvm::emitPutS(), and llvm::getFloatFnName().
getState()
TargetLibraryInfoImpl::AvailabilityState llvm::TargetLibraryInfo::getState (LibFunc F) const inline
Definition at line 294 of file TargetLibraryInfo.h.
getVectorizedFunction()
StringRef llvm::TargetLibraryInfo::getVectorizedFunction (StringRef F, unsigned VF) const inline
Definition at line 310 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getVectorizedFunction().
Referenced by addMappingsFromTLI().
getWCharSize()
unsigned llvm::TargetLibraryInfo::getWCharSize (const Module & M) const inline
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
This queries the 'wchar_size' metadata.
Definition at line 377 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getWCharSize().
getWidestVF()
unsigned llvm::TargetLibraryInfo::getWidestVF (StringRef ScalarF) const inline
Returns the largest vectorization factor used in the list of vector functions.
Definition at line 396 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getWidestVF().
Referenced by addMappingsFromTLI().
has()
bool llvm::TargetLibraryInfo::has (LibFunc F) const inline
Tests whether a library function is available.
Definition at line 301 of file TargetLibraryInfo.h.
Referenced by llvm::callsGCLeafFunction(), CanCombineFCOPYSIGN_EXTEND_ROUND(), llvm::canConstantFoldCallTo(), deleteDeadInstruction(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), getAllocationDataForFunction(), llvm::MemoryLocation::getForArgument(), hasAnalyzableMemoryWrite(), llvm::hasFloatFn(), llvm::inferLibFuncAttributes(), llvm::isFreeCall(), isLocallyOpenedFile(), isWriteOnlyParam(), and runPartiallyInlineLibCalls().
hasOptimizedCodeGen()
bool llvm::TargetLibraryInfo::hasOptimizedCodeGen (LibFunc F) const inline
Tests if the function is both available and a candidate for optimized code generation.
Definition at line 316 of file TargetLibraryInfo.h.
Referenced by llvm::PPCTTIImpl::getUserCost(), and llvm::maybeMarkSanitizerLibraryCallNoBuiltin().
invalidate() [1/2]
bool llvm::TargetLibraryInfo::invalidate (Module & , const PreservedAnalyses & , ModuleAnalysisManager::Invalidator &) inline
Handle invalidation from the pass manager.
If we try to invalidate this info, just return false. It cannot become invalid even if the module or function changes.
Definition at line 385 of file TargetLibraryInfo.h.
invalidate() [2/2]
bool llvm::TargetLibraryInfo::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Definition at line 389 of file TargetLibraryInfo.h.
isFunctionVectorizable() [1/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F, unsigned VF) const inline
Definition at line 304 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
Referenced by addMappingsFromTLI(), llvm::LoopVectorizationCostModel::getVectorCallCost(), isKnownLibFunction(), and llvm::MemoryDepChecker::Dependence::print().
isFunctionVectorizable() [2/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F) const inline
Definition at line 307 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
operator=() [1/2]
TargetLibraryInfo& llvm::TargetLibraryInfo::operator= (const TargetLibraryInfo & TLI) inline
Definition at line 252 of file TargetLibraryInfo.h.
operator=() [2/2]
TargetLibraryInfo& llvm::TargetLibraryInfo::operator= (TargetLibraryInfo && TLI) inline
Definition at line 257 of file TargetLibraryInfo.h.
setUnavailable()
void llvm::TargetLibraryInfo::setUnavailable (LibFunc F) inline
Forces a function to be marked as unavailable.
Definition at line 290 of file TargetLibraryInfo.h.
References F(), and llvm::BitVector::set().
Friends And Related Function Documentation
TargetLibraryAnalysis
friend class TargetLibraryAnalysis friend
Definition at line 213 of file TargetLibraryInfo.h.
TargetLibraryInfoWrapperPass
friend class TargetLibraryInfoWrapperPass friend
Definition at line 214 of file TargetLibraryInfo.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetLibraryInfo.h