LLVM: llvm::IRCEPass Class Reference
llvm::IRCEPass Class Reference
#include "llvm/Transforms/Scalar/InductiveRangeCheckElimination.h"
Public Member Functions
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< IRCEPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 22 of file InductiveRangeCheckElimination.h.
Member Function Documentation
run()
PreservedAnalyses IRCEPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 1750 of file InductiveRangeCheckElimination.cpp.
References llvm::LPPassManager::addLoop(), llvm::LPMUpdater::addSiblingLoops(), llvm::PreservedAnalyses::all(), assert(), B, Context, llvm::dbgs(), llvm::LoopStandardAnalysisResults::DT, llvm::SmallVectorBase::empty(), llvm::errs(), F(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::BasicBlock::getContext(), llvm::ConstantInt::getFalse(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopPassPreservedAnalyses(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::ScalarEvolution::getMinusSCEV(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::ScalarEvolution::getSCEV(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), llvm::Optional< T >::getValue(), llvm::Optional< T >::hasValue(), IntersectSignedRange(), IntersectUnsignedRange(), llvm::LoopStandardAnalysisResults::LI, LLVM_DEBUG, LoopSizeCutoff, llvm::LoopBase< BlockT, LoopT >::print(), PrintChangedLoops, PrintRangeChecks, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LoopStandardAnalysisResults::SE, and llvm::SmallVectorBase::size().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/InductiveRangeCheckElimination.h
lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp