LLVM: llvm::MachineOptimizationRemarkEmitterPass Class Reference
llvm::MachineOptimizationRemarkEmitterPass Class Reference
The analysis pass.
#include "llvm/CodeGen/MachineOptimizationRemarkEmitter.h"
Public Member Functions
MachineOptimizationRemarkEmitterPass ()
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
MachineOptimizationRemarkEmitter & getORE ()
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
The analysis pass.
Note that this pass shouldn't generally be marked as preserved by other passes. It's holding onto BFI, so if the pass does not preserve BFI, BFI could be freed.
Definition at line 212 of file MachineOptimizationRemarkEmitter.h.
Constructor & Destructor Documentation
MachineOptimizationRemarkEmitterPass()
MachineOptimizationRemarkEmitterPass::MachineOptimizationRemarkEmitterPass ()
Definition at line 65 of file MachineOptimizationRemarkEmitter.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineOptimizationRemarkEmitterPassPass().
Member Function Documentation
getAnalysisUsage()
void MachineOptimizationRemarkEmitterPass::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 84 of file MachineOptimizationRemarkEmitter.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), ID, and llvm::AnalysisUsage::setPreservesAll().
getORE()
MachineOptimizationRemarkEmitter& llvm::MachineOptimizationRemarkEmitterPass::getORE () inline
Definition at line 222 of file MachineOptimizationRemarkEmitter.h.
References assert().
runOnMachineFunction()
bool MachineOptimizationRemarkEmitterPass::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 71 of file MachineOptimizationRemarkEmitter.cpp.
References llvm::Function::getContext(), llvm::LLVMContext::getDiagnosticsHotnessRequested(), and llvm::MachineFunction::getFunction().
Member Data Documentation
ID
char MachineOptimizationRemarkEmitterPass::ID = 0 static
Definition at line 227 of file MachineOptimizationRemarkEmitter.h.
Referenced by getAnalysisUsage().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineOptimizationRemarkEmitter.h
lib/CodeGen/MachineOptimizationRemarkEmitter.cpp