LLVM: llvm::UnwindOpcodeAssembler Class Reference
llvm::UnwindOpcodeAssembler Class Reference
#include "Target/ARM/MCTargetDesc/ARMUnwindOpAsm.h"
Public Member Functions
UnwindOpcodeAssembler ()
void Reset ()
Reset the unwind opcode assembler.
void setPersonality (const MCSymbol *Per)
Set the personality.
void EmitRegSave (uint32_t RegSave)
Emit unwind opcodes for .save directives.
void EmitVFPRegSave (uint32_t VFPRegSave)
Emit unwind opcodes for .vsave directives.
void EmitSetSP (uint16_t Reg)
Emit unwind opcodes to copy address from source register to $sp.
void EmitSPOffset (int64_t Offset)
Emit unwind opcodes to add $sp with an offset.
void EmitRaw (const SmallVectorImpl< uint8_t > &Opcodes)
Emit unwind raw opcodes.
void Finalize (unsigned &PersonalityIndex, SmallVectorImpl< uint8_t > &Result)
Finalize the unwind opcode sequence for EmitBytes()
Detailed Description
Definition at line 25 of file ARMUnwindOpAsm.h.
Constructor & Destructor Documentation
UnwindOpcodeAssembler()
llvm::UnwindOpcodeAssembler::UnwindOpcodeAssembler () inline
Definition at line 32 of file ARMUnwindOpAsm.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Member Function Documentation
EmitRaw()
void llvm::UnwindOpcodeAssembler::EmitRaw (const SmallVectorImpl< uint8_t > & Opcodes) inline
Emit unwind raw opcodes.
Definition at line 62 of file ARMUnwindOpAsm.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), Finalize(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Size, and llvm::SmallVectorBase::size().
EmitRegSave()
void UnwindOpcodeAssembler::EmitRegSave (uint32_t RegSave)
Emit unwind opcodes for .save directives.
Definition at line 66 of file ARMUnwindOpAsm.cpp.
References llvm::countTrailingOnes(), llvm::BitmaskEnumDetail::Mask(), llvm::ARM::EHABI::UNWIND_OPCODE_POP_REG_MASK, llvm::ARM::EHABI::UNWIND_OPCODE_POP_REG_MASK_R4, llvm::ARM::EHABI::UNWIND_OPCODE_POP_REG_RANGE_R4, and llvm::ARM::EHABI::UNWIND_OPCODE_POP_REG_RANGE_R4_R14.
Referenced by setPersonality().
EmitSetSP()
void UnwindOpcodeAssembler::EmitSetSP (uint16_t Reg)
Emit unwind opcodes to copy address from source register to $sp.
Definition at line 127 of file ARMUnwindOpAsm.cpp.
References llvm::ARM::EHABI::UNWIND_OPCODE_SET_VSP.
Referenced by setPersonality().
EmitSPOffset()
void UnwindOpcodeAssembler::EmitSPOffset (int64_t Offset)
Emit unwind opcodes to add $sp with an offset.
Definition at line 132 of file ARMUnwindOpAsm.cpp.
References llvm::encodeULEB128(), llvm::ARM::EHABI::UNWIND_OPCODE_DEC_VSP, llvm::ARM::EHABI::UNWIND_OPCODE_INC_VSP, and llvm::ARM::EHABI::UNWIND_OPCODE_INC_VSP_ULEB128.
Referenced by setPersonality().
EmitVFPRegSave()
void UnwindOpcodeAssembler::EmitVFPRegSave (uint32_t VFPRegSave)
Emit unwind opcodes for .vsave directives.
Definition at line 104 of file ARMUnwindOpAsm.cpp.
References llvm::countLeadingOnes(), llvm::countLeadingZeros(), llvm::ARM::EHABI::UNWIND_OPCODE_POP_VFP_REG_RANGE_FSTMFDD, and llvm::ARM::EHABI::UNWIND_OPCODE_POP_VFP_REG_RANGE_FSTMFDD_D16.
Referenced by setPersonality().
Finalize()
void UnwindOpcodeAssembler::Finalize (unsigned & PersonalityIndex, SmallVectorImpl< uint8_t > & Result)
Finalize the unwind opcode sequence for EmitBytes()
Definition at line 155 of file ARMUnwindOpAsm.cpp.
References llvm::ARM::EHABI::AEABI_UNWIND_CPP_PR0, llvm::ARM::EHABI::AEABI_UNWIND_CPP_PR1, assert(), llvm::sys::path::end(), llvm::ARM::EHABI::NUM_PERSONALITY_INDEX, and llvm::SmallVectorImpl< T >::resize().
Referenced by EmitRaw().
Reset()
void llvm::UnwindOpcodeAssembler::Reset () inline
Reset the unwind opcode assembler.
Definition at line 37 of file ARMUnwindOpAsm.h.
References llvm::SmallVectorImpl< T >::clear(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
setPersonality()
void llvm::UnwindOpcodeAssembler::setPersonality (const MCSymbol * Per) inline
Set the personality.
Definition at line 45 of file ARMUnwindOpAsm.h.
References EmitRegSave(), EmitSetSP(), EmitSPOffset(), EmitVFPRegSave(), and Reg.
The documentation for this class was generated from the following files:
lib/Target/ARM/MCTargetDesc/ARMUnwindOpAsm.h
lib/Target/ARM/MCTargetDesc/ARMUnwindOpAsm.cpp