LLVM: llvm::MCValue Class Reference
llvm::MCValue Class Reference
This represents an "assembler immediate".
#include "llvm/MC/MCValue.h"
Public Member Functions
MCValue ()=default
int64_t getConstant () const
const MCSymbolRefExpr * getSymA () const
const MCSymbolRefExpr * getSymB () const
uint32_t getRefKind () const
bool isAbsolute () const
Is this an absolute (as opposed to relocatable) value.
void print (raw_ostream &OS) const
Print the value to the stream OS.
void dump () const
Print the value to stderr.
MCSymbolRefExpr::VariantKind getAccessVariant () const
Static Public Member Functions
static MCValue get (const MCSymbolRefExpr *SymA, const MCSymbolRefExpr *SymB=nullptr, int64_t Val=0, uint32_t RefKind=0)
static MCValue get (int64_t Val)
Detailed Description
This represents an "assembler immediate".
In its most general form, this can hold ":Kind:(SymbolA - SymbolB + imm64)". Not all targets supports relocations of this general form, but we need to represent this anyway.
In general both SymbolA and SymbolB will also have a modifier analogous to the top-level Kind. Current targets are not expected to make use of both though. The choice comes down to whether relocation modifiers apply to the closest symbol or the whole expression.
Note that this class must remain a simple POD value class, because we need it to live in unions etc.
Definition at line 39 of file MCValue.h.
Constructor & Destructor Documentation
MCValue()
llvm::MCValue::MCValue () default
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MCValue::dump () const
Print the value to stderr.
Definition at line 41 of file MCValue.cpp.
References llvm::dbgs(), and print().
Referenced by isAbsolute().
get() [1/2]
static MCValue llvm::MCValue::get (const MCSymbolRefExpr * SymA, const MCSymbolRefExpr * SymB = nullptr, int64_t Val = 0, uint32_t RefKind = 0) inline static
Definition at line 62 of file MCValue.h.
Referenced by llvm::LanaiMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::AArch64MCExpr::evaluateAsRelocatableImpl(), and llvm::RISCVAsmBackend::shouldInsertFixupForCodeAlign().
get() [2/2]
static MCValue llvm::MCValue::get (int64_t Val) inline static
Definition at line 73 of file MCValue.h.
getAccessVariant()
MCSymbolRefExpr::VariantKind MCValue::getAccessVariant () const
Definition at line 46 of file MCValue.cpp.
References B, llvm::MCSymbolRefExpr::getKind(), getSymA(), getSymB(), llvm_unreachable, and llvm::MCSymbolRefExpr::VK_None.
Referenced by getAccessVariant(), getFixupSection(), getPLTReloc(), llvm::AVRELFObjectWriter::getRelocType(), getRelocType32(), and isAbsolute().
getConstant()
int64_t llvm::MCValue::getConstant () const inline
Definition at line 46 of file MCValue.h.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), canGoAfterDWARF(), canUseLocalRelocation(), covertDoubleImmToSingleImm(), llvm::AVRMCExpr::evaluateAsConstant(), llvm::RISCVMCExpr::evaluateAsConstant(), llvm::PPCMCExpr::evaluateAsConstant(), llvm::LanaiMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::AArch64MCExpr::evaluateAsRelocatableImpl(), llvm::RISCVAsmBackend::evaluateTargetFixup(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), llvm::X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), handleIndirectSymViaGOTPCRel(), incrementLoc(), isIFunc(), isShiftedUIntAtAnyPosition(), and print().
getRefKind()
uint32_t llvm::MCValue::getRefKind () const inline
Definition at line 49 of file MCValue.h.
Referenced by adjustFixupValue(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), isNonILP32reloc(), llvm::MCAssembler::isThumbFunc(), and print().
getSymA()
const MCSymbolRefExpr* llvm::MCValue::getSymA () const inline
Definition at line 47 of file MCValue.h.
Referenced by llvm::AVRAsmBackend::adjustFixupValue(), llvm::ARMAsmBackend::adjustFixupValue(), canGoAfterDWARF(), canUseLocalRelocation(), covertDoubleImmToSingleImm(), llvm::LanaiMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::RISCVMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::AArch64MCExpr::evaluateAsRelocatableImpl(), llvm::RISCVAsmBackend::evaluateTargetFixup(), llvm::MCAssembler::Finish(), getAccessVariant(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), llvm::MCAsmLayout::getBaseSymbol(), getFixupKindLog2Size(), getFixupKindNumBytes(), getFixupOffset(), getFixupSection(), llvm::RISCVMCExpr::getPCRelHiFixup(), getRelocType(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), handleIndirectSymViaGOTPCRel(), incrementLoc(), isFixupTargetValid(), isIFunc(), isNonILP32reloc(), isShiftedUIntAtAnyPosition(), llvm::MCAssembler::isThumbFunc(), print(), and llvm::ARMAsmBackend::shouldForceRelocation().
getSymB()
const MCSymbolRefExpr* llvm::MCValue::getSymB () const inline
Definition at line 48 of file MCValue.h.
Referenced by canGoAfterDWARF(), canUseLocalRelocation(), covertDoubleImmToSingleImm(), llvm::LanaiMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::RISCVMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::AArch64MCExpr::evaluateAsRelocatableImpl(), llvm::RISCVAsmBackend::evaluateTargetFixup(), getAccessVariant(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), llvm::MCAsmLayout::getBaseSymbol(), getFixupKindLog2Size(), getFixupOffset(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), handleIndirectSymViaGOTPCRel(), incrementLoc(), isFixupTargetValid(), isIFunc(), isNonILP32reloc(), isShiftedUIntAtAnyPosition(), llvm::MCAssembler::isThumbFunc(), and print().
isAbsolute()
bool llvm::MCValue::isAbsolute () const inline
Is this an absolute (as opposed to relocatable) value.
Definition at line 52 of file MCValue.h.
References dump(), getAccessVariant(), and print().
Referenced by canUseLocalRelocation(), llvm::AVRMCExpr::evaluateAsConstant(), llvm::RISCVMCExpr::evaluateAsConstant(), llvm::PPCMCExpr::evaluateAsConstant(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), getFixupKindSize(), getFixupOffset(), getRelocType(), handleIndirectSymViaGOTPCRel(), print(), and llvm::RISCVAsmBackend::shouldForceRelocation().
print()
void MCValue::print (raw_ostream & OS) const
Print the value to the stream OS.
Definition at line 18 of file MCValue.cpp.
References getConstant(), getRefKind(), getSymA(), getSymB(), and isAbsolute().
Referenced by dump(), getAccessVariant(), and isAbsolute().
The documentation for this class was generated from the following files:
include/llvm/MC/MCValue.h
lib/MC/MCValue.cpp