LLVM: llvm::jitlink::Addressable Class Reference
llvm::jitlink::Addressable Class Reference
Base class for Addressable entities (externals, absolutes, blocks).
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Member Functions
Addressable (const Addressable &)=delete
Addressable & operator= (const Addressable &)=default
Addressable (Addressable &&)=delete
Addressable & operator= (Addressable &&)=default
JITTargetAddress getAddress () const
void setAddress (JITTargetAddress Address)
bool isDefined () const
Returns true if this is a defined addressable, in which case you can downcast this to a .
bool isAbsolute () const
Protected Member Functions
Addressable (JITTargetAddress Address, bool IsDefined)
Addressable (JITTargetAddress Address)
Friends
class LinkGraph
Detailed Description
Base class for Addressable entities (externals, absolutes, blocks).
Definition at line 101 of file JITLink.h.
Constructor & Destructor Documentation
Addressable() [1/4]
llvm::jitlink::Addressable::Addressable (JITTargetAddress Address, bool IsDefined) inline protected
Definition at line 105 of file JITLink.h.
Addressable() [2/4]
llvm::jitlink::Addressable::Addressable (JITTargetAddress Address) inline protected
Definition at line 108 of file JITLink.h.
References assert().
Addressable() [3/4]
llvm::jitlink::Addressable::Addressable (const Addressable &) delete
Addressable() [4/4]
llvm::jitlink::Addressable::Addressable (Addressable &&) delete
Member Function Documentation
getAddress()
JITTargetAddress llvm::jitlink::Addressable::getAddress () const inline
Definition at line 120 of file JITLink.h.
References llvm::Address.
Referenced by llvm::jitlink::BlockAddressMap::addBlock(), llvm::jitlink::BlockAddressMap::addBlockWithoutChecking(), llvm::jitlink::Symbol::getAddress(), llvm::jitlink::BlockAddressMap::getBlockCovering(), llvm::jitlink::BlockAddressMap::includeNonNull(), llvm::jitlink::MachOJITLinker_arm64::MachOJITLinker_arm64(), llvm::jitlink::MachOJITLinker_x86_64::MachOJITLinker_x86_64(), llvm::jitlink::operator<<(), llvm::jitlink::printEdge(), llvm::jitlink::SectionRange::SectionRange(), and llvm::jitlink::LinkGraph::splitBlock().
isAbsolute()
bool llvm::jitlink::Addressable::isAbsolute () const inline
Definition at line 126 of file JITLink.h.
References llvm::Address.
Referenced by llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isExternal(), llvm::jitlink::LinkGraph::makeExternal(), llvm::jitlink::Symbol::setLinkage(), and llvm::jitlink::Symbol::setScope().
isDefined()
bool llvm::jitlink::Addressable::isDefined () const inline
Returns true if this is a defined addressable, in which case you can downcast this to a .
Definition at line 125 of file JITLink.h.
Referenced by llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), llvm::jitlink::Symbol::isExternal(), and llvm::jitlink::Symbol::setScope().
operator=() [1/2]
Addressable& llvm::jitlink::Addressable::operator= (const Addressable &) default
operator=() [2/2]
Addressable& llvm::jitlink::Addressable::operator= (Addressable &&) default
setAddress()
void llvm::jitlink::Addressable::setAddress (JITTargetAddress Address) inline
Definition at line 121 of file JITLink.h.
Referenced by llvm::jitlink::LinkGraph::splitBlock().
Friends And Related Function Documentation
LinkGraph
friend class LinkGraph friend
Definition at line 102 of file JITLink.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h