LLVM: llvm::GlobalObject Class Reference
llvm::GlobalObject Class Reference
#include "llvm/IR/GlobalObject.h"
Public Types
enum VCallVisibility { VCallVisibilityPublic = 0, VCallVisibilityLinkageUnit = 1, VCallVisibilityTranslationUnit = 2 }
Public Types inherited from llvm::GlobalValue
enum LinkageTypes {
ExternalLinkage = 0, AvailableExternallyLinkage, LinkOnceAnyLinkage, LinkOnceODRLinkage,
WeakAnyLinkage, WeakODRLinkage, AppendingLinkage, InternalLinkage,
PrivateLinkage, ExternalWeakLinkage, CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0, HiddenVisibility, ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0, DLLImportStorageClass = 1, DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0, GeneralDynamicTLSModel, LocalDynamicTLSModel, InitialExecTLSModel,
LocalExecTLSModel
}
enum UnnamedAddr { UnnamedAddr::None, UnnamedAddr::Local, UnnamedAddr::Global }
using GUID = uint64_t
Declare a type to represent a global unique identifier for a global value.
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
GlobalObject (const GlobalObject &)=delete
unsigned getAlignment () const
LLVM_ATTRIBUTE_DEPRECATED (void setAlignment(unsigned Align), "Please use `void setAlignment(MaybeAlign Align)`")
FIXME: Remove this setter once the migration to MaybeAlign is over.
void setAlignment (MaybeAlign Align)
unsigned getGlobalObjectSubClassData () const
void setGlobalObjectSubClassData (unsigned Val)
bool hasSection () const
Check if this global has a custom object file section.
StringRef getSection () const
Get the custom section of this global if it has one.
void setSection (StringRef S)
Change the section for this global.
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
void setComdat (Comdat *C)
bool hasMetadata () const
Check if this has any metadata.
bool hasMetadata (unsigned KindID) const
Check if this has any metadata of the given kind.
bool hasMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode *>> &MDs) const
Appends all attachments for the global to MDs, sorting by attachment ID.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void copyMetadata (const GlobalObject *Src, unsigned Offset)
Copy metadata from Src, adjusting offsets by Offset.
void addTypeMetadata (unsigned Offset, Metadata *TypeID)
void addVCallVisibilityMetadata (VCallVisibility Visibility)
VCallVisibility getVCallVisibility () const
void clearMetadata ()
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode *> &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode *> &MDs) const
void setMetadata (unsigned KindID, MDNode *MD)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *MD)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Public Member Functions inherited from llvm::GlobalValue
GlobalValue (const GlobalValue &)=delete
unsigned getAlignment () const
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
void setUnnamedAddr (UnnamedAddr Val)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
StringRef getSection () const
PointerType * getType () const
Global values are always pointers.
Type * getValueType () const
void setDSOLocal (bool Local)
bool isDSOLocal () const
bool hasPartition () const
StringRef getPartition () const
void setPartition (StringRef Part)
bool isDefinitionExact () const
Return true if the currently visible definition of this global (if any) is exactly the definition we will see at runtime.
bool hasExactDefinition () const
Return true if this global has an exact defintion.
bool isInterposable () const
Return true if this global's definition can be substituted with an arbitrary definition at link time.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
bool hasValidDeclarationLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool isWeakForLinker () const
std::string getGlobalIdentifier () const
Return the modified name for this global value suitable to be used as the key for a global lookup (e.g.
GUID getGUID () const
Return a 64-bit global unique ID constructed from global value name (i.e.
bool isDeclaration () const
Return true if the primary definition of this global value is outside of the current translation unit.
bool isDeclarationForLinker () const
bool isStrongDefinitionForLinker () const
Returns true if this global's definition will be the one chosen by the linker.
bool canIncreaseAlignment () const
const GlobalObject * getBaseObject () const
GlobalObject * getBaseObject ()
bool isAbsoluteSymbolRef () const
Returns whether this is a reference to an absolute symbol.
Optional< ConstantRange > getAbsoluteSymbolRange () const
If this is an absolute symbol reference, returns the range of the symbol, otherwise returns None.
void removeFromParent ()
This method unlinks 'this' from the containing module, but does not delete it.
void eraseFromParent ()
This method unlinks 'this' from the containing module and deletes it.
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
bool canBeOmittedFromSymbolTable () const
True if GV can be left out of the object symbol table.
bool isMaterializable () const
If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Error materialize ()
Make sure this GlobalValue is fully read.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefElement () const
Return true if this is a vector constant that includes any undefined elements.
bool containsConstantExpression () const
Return true if this is a vector constant that includes any constant expressions.
bool canTrap () const
Return true if evaluation of this constant could trap.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry.
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalValue
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isValidDeclarationLinkage (LinkageTypes Linkage)
static bool isInterposableLinkage (LinkageTypes Linkage)
Whether the definition of this global may be replaced by something non-equivalent at link time.
static bool isDiscardableIfUnused (LinkageTypes Linkage)
Whether the definition of this global may be discarded if it is not used in its compilation unit.
static bool isWeakForLinker (LinkageTypes Linkage)
Whether the definition of this global may be replaced at link time.
static StringRef dropLLVMManglingEscape (StringRef Name)
If the given string begins with the GlobalValue name mangling escape character '\1', drop it.
static std::string getGlobalIdentifier (StringRef Name, GlobalValue::LinkageTypes Linkage, StringRef FileName)
Return the modified name for a global value suitable to be used as the key for a global lookup (e.g.
static GUID getGUID (StringRef GlobalName)
Return a 64-bit global unique ID constructed from global value name (i.e.
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Types
enum { LastAlignmentBit = 4, HasMetadataHashEntryBit, HasSectionHashEntryBit, GlobalObjectBits }
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions
GlobalObject (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace=0)
void copyAttributesFrom (const GlobalObject *Src)
Protected Member Functions inherited from llvm::GlobalValue
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
void setParent (Module *parent)
~GlobalValue ()
void copyAttributesFrom (const GlobalValue *Src)
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
Comdat * ObjComdat
Protected Attributes inherited from llvm::GlobalValue
Type * ValueType
unsigned Linkage: 4
unsigned Visibility: 2
unsigned UnnamedAddrVal: 2
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
unsigned HasLLVMReservedName: 1
True if the function's name starts with "llvm.".
unsigned IsDSOLocal: 1
If true then there is a definition within the same linkage unit and that definition cannot be runtime preempted.
unsigned HasPartition: 1
True if this symbol has a partition name assigned (see https://lld.llvm.org/Partitions.html).
Intrinsic::ID IntID
The intrinsic ID for this subclass (which must be a Function).
Module * Parent
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes
static const unsigned GlobalObjectSubClassDataBits
Static Protected Attributes inherited from llvm::GlobalValue
static const unsigned GlobalValueSubClassDataBits = 16
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Detailed Description
Definition at line 30 of file GlobalObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
LastAlignmentBit
HasMetadataHashEntryBit
HasSectionHashEntryBit
GlobalObjectBits
Definition at line 55 of file GlobalObject.h.
VCallVisibility
enum llvm::GlobalObject::VCallVisibility
Enumerator
VCallVisibilityPublic
VCallVisibilityLinkageUnit
VCallVisibilityTranslationUnit
Definition at line 35 of file GlobalObject.h.
Constructor & Destructor Documentation
GlobalObject() [1/2]
llvm::GlobalObject::GlobalObject (Type * Ty, ValueTy VTy, Use * Ops, unsigned NumOps, LinkageTypes Linkage, const Twine & Name, unsigned AddressSpace = 0) inline protected
Definition at line 46 of file GlobalObject.h.
References llvm::GlobalValue::setGlobalValueSubClassData().
GlobalObject() [2/2]
llvm::GlobalObject::GlobalObject (const GlobalObject &) delete
Member Function Documentation
addMetadata() [1/2]
void GlobalObject::addMetadata (unsigned KindID, MDNode & MD)
Add a metadata attachment.
Definition at line 1393 of file Metadata.cpp.
References llvm::MDNode::getContext(), llvm::LLVMContextImpl::GlobalObjectMetadata, and llvm::LLVMContext::pImpl.
Referenced by llvm::CloneFunctionInto(), llvm::CloneModule(), llvm::createDeadArgHackingPass(), hasMetadata(), parseOptionalLinkageAux(), and wrapConstantAsMetadata().
addMetadata() [2/2]
void GlobalObject::addMetadata (StringRef Kind, MDNode & MD)
Definition at line 1400 of file Metadata.cpp.
References llvm::MDNode::getContext().
addTypeMetadata()
void GlobalObject::addTypeMetadata (unsigned Offset, Metadata * TypeID)
Definition at line 1494 of file Metadata.cpp.
References llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDTuple::get(), llvm::MDNode::getContext(), and llvm::Type::getInt64Ty().
Referenced by hasMetadata().
addVCallVisibilityMetadata()
void GlobalObject::addVCallVisibilityMetadata (VCallVisibility Visibility)
Definition at line 1503 of file Metadata.cpp.
References llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDNode::getContext(), and llvm::Type::getInt64Ty().
Referenced by hasMetadata().
classof()
static bool llvm::GlobalObject::classof (const Value * V) inline static
Definition at line 189 of file GlobalObject.h.
References llvm::tgtok::Bit, clearMetadata(), llvm::GlobalValue::getGlobalValueSubClassData(), llvm::Value::getValueID(), HasMetadataHashEntryBit, llvm::BitmaskEnumDetail::Mask(), and llvm::GlobalValue::setGlobalValueSubClassData().
clearMetadata()
void GlobalObject::clearMetadata ()
Definition at line 1426 of file Metadata.cpp.
References llvm::MDNode::getContext(), llvm::LLVMContextImpl::GlobalObjectMetadata, and llvm::LLVMContext::pImpl.
Referenced by classof(), llvm::GlobalVariable::dropAllReferences(), and wrapConstantAsMetadata().
copyAttributesFrom()
void GlobalObject::copyAttributesFrom (const GlobalObject * Src) protected
Definition at line 130 of file Globals.cpp.
References llvm::GlobalValue::copyAttributesFrom(), getAlignment(), and getSection().
Referenced by llvm::GlobalVariable::copyAttributesFrom(), llvm::Function::copyAttributesFrom(), and hasMetadata().
copyMetadata()
void GlobalObject::copyMetadata (const GlobalObject * Src, unsigned Offset)
Copy metadata from Src, adjusting offsets by Offset.
Definition at line 1453 of file Metadata.cpp.
References llvm::ArrayRef< T >::begin(), llvm::copy(), llvm::dyn_cast(), E, llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), getAllMetadata(), llvm::MDNode::getContext(), and llvm::ArrayRef< T >::size().
Referenced by hasMetadata().
eraseMetadata()
bool GlobalObject::eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
Returns
true if any metadata was removed.
Definition at line 1404 of file Metadata.cpp.
References llvm::MDNode::getContext(), llvm::LLVMContextImpl::GlobalObjectMetadata, llvm::LLVMContext::pImpl, and llvm::SPII::Store.
Referenced by hasMetadata().
getAlignment()
unsigned llvm::GlobalObject::getAlignment () const inline
Definition at line 73 of file GlobalObject.h.
References llvm::Data, llvm::decodeMaybeAlign(), llvm::GlobalValue::getGlobalValueSubClassData(), LLVM_ATTRIBUTE_DEPRECATED(), and setAlignment().
Referenced by AddCalls(), canCreateAliasFor(), copyAttributesFrom(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::AMDGPUAsmPrinter::EmitGlobalVariable(), forceRenaming(), getAlignment(), getArrayElements(), llvm::DataLayout::getPreferredAlignment(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), maybePrintComdat(), replace(), RetagMask(), SRAGlobal(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
getAllMetadata()
void GlobalObject::getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode *>> & MDs) const
Appends all attachments for the global to MDs, sorting by attachment ID.
Attachments with the same ID appear in insertion order.
Definition at line 1416 of file Metadata.cpp.
References llvm::MDNode::getContext(), llvm::LLVMContextImpl::GlobalObjectMetadata, and llvm::LLVMContext::pImpl.
Referenced by llvm::CloneFunctionInto(), copyMetadata(), getRetComponentType(), hasMetadata(), hasMetadataOtherThanDebugLoc(), llvm::SlotTracker::initializeIndexIfNeeded(), maybePrintComdat(), and wrapConstantAsMetadata().
getComdat() [1/2]
const Comdat* llvm::GlobalObject::getComdat () const inline
Definition at line 120 of file GlobalObject.h.
References ObjComdat.
Referenced by AddCalls(), canCreateThunkFor(), canRenameComdat(), copyComdat(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::AsmPrinter::emitXRayTable(), llvm::GetOrCreateFunctionComdat(), getRetComponentType(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileXCOFF::getSectionForJumpTable(), hasComdat(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), LLVMGetComdat(), maybePrintComdat(), optimizeGlobalsInModule(), and rewriteComdat().
getComdat() [2/2]
Comdat* llvm::GlobalObject::getComdat () inline
Definition at line 121 of file GlobalObject.h.
References ObjComdat.
getGlobalObjectSubClassData()
unsigned llvm::GlobalObject::getGlobalObjectSubClassData () const inline
Definition at line 85 of file GlobalObject.h.
References llvm::GlobalValue::getGlobalValueSubClassData(), and GlobalObjectBits.
Referenced by setGlobalObjectSubClassData().
getMetadata() [1/4]
MDNode * GlobalObject::getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
These functions require that the function have at most a single attachment of the given kind, and return nullptr if such an attachment is missing.
Definition at line 1443 of file Metadata.cpp.
References llvm::MDNode::getContext(), llvm::LLVMContextImpl::GlobalObjectMetadata, and llvm::LLVMContext::pImpl.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), computeVariableSummary(), llvm::WebAssemblyAsmPrinter::EmitFunctionBodyStart(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), forEachUser(), getAssociatedSymbol(), llvm::AbstractCallSite::getCallbackUses(), llvm::getPGOFuncNameMetadata(), hasMetadata(), llvm::GlobalValue::isAbsoluteSymbolRef(), and splitGlobal().
getMetadata() [2/4]
MDNode * GlobalObject::getMetadata (StringRef Kind) const
Definition at line 1449 of file Metadata.cpp.
References llvm::MDNode::getContext().
getMetadata() [3/4]
void GlobalObject::getMetadata (unsigned KindID, SmallVectorImpl< MDNode *> & MDs) const
Appends all attachments with the given ID to MDs in insertion order.
If the global has no attachments with the given ID, or if ID is invalid, leaves MDs unchanged.
Definition at line 1381 of file Metadata.cpp.
References llvm::MDNode::getContext(), llvm::LLVMContextImpl::GlobalObjectMetadata, and llvm::LLVMContext::pImpl.
getMetadata() [4/4]
void GlobalObject::getMetadata (StringRef Kind, SmallVectorImpl< MDNode *> & MDs) const
Definition at line 1387 of file Metadata.cpp.
References llvm::MDNode::getContext().
getSection()
StringRef llvm::GlobalObject::getSection () const inline
Get the custom section of this global if it has one.
If this global does not have a custom section, this will be empty and the default object file section (.text, .data, etc) will be used.
Definition at line 109 of file GlobalObject.h.
References hasSection(), and setSection().
Referenced by AddCalls(), callsShareTOCBase(), llvm::FunctionComparator::compareSignature(), copyAttributesFrom(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), getArrayElements(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::AMDGPUTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), getOutliningPenalty(), instrumentMaskedLoadOrStore(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), maybePrintComdat(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection().
getVCallVisibility()
GlobalObject::VCallVisibility GlobalObject::getVCallVisibility () const
Definition at line 1510 of file Metadata.cpp.
References assert().
Referenced by hasMetadata().
hasComdat()
bool llvm::GlobalObject::hasComdat () const inline
Definition at line 119 of file GlobalObject.h.
References getComdat().
Referenced by callsShareTOCBase(), llvm::canRenameComdatFunc(), computeVariableSummary(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::AsmPrinter::emitXRayTable(), forEachUser(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), instrumentMaskedLoadOrStore(), llvm::needsComdatForCounter(), llvm::LegacyInlinerBase::removeDeadFunctions(), llvm::AlwaysInlinerPass::run(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), and shouldRecordFunctionAddr().
hasMetadata() [1/3]
bool llvm::GlobalObject::hasMetadata () const inline
Check if this has any metadata.
Definition at line 125 of file GlobalObject.h.
Referenced by emitSignedInt64(), llvm::ImportedFunctionsInliningStatistics::setModuleInfo(), and llvm::stripDebugInfo().
hasMetadata() [2/3]
bool llvm::GlobalObject::hasMetadata (unsigned KindID) const inline
Check if this has any metadata of the given kind.
Definition at line 128 of file GlobalObject.h.
References getMetadata().
hasMetadata() [3/3]
bool llvm::GlobalObject::hasMetadata (StringRef Kind) const inline
Definition at line 131 of file GlobalObject.h.
References addMetadata(), addTypeMetadata(), addVCallVisibilityMetadata(), copyAttributesFrom(), copyMetadata(), eraseMetadata(), getAllMetadata(), getMetadata(), getVCallVisibility(), setMetadata(), and llvm::GlobalValue::Visibility.
hasSection()
bool llvm::GlobalObject::hasSection () const inline
Check if this global has a custom object file section.
This is more efficient than calling getSection() and checking for an empty string.
Definition at line 101 of file GlobalObject.h.
References llvm::GlobalValue::getGlobalValueSubClassData(), and HasSectionHashEntryBit.
Referenced by llvm::FunctionComparator::compareSignature(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::getLutUsedFunction(), getOutliningPenalty(), llvm::DataLayout::getPreferredAlignment(), getSection(), instrumentMaskedLoadOrStore(), llvm::RISCVInstrInfo::isFunctionSafeToOutlineFrom(), llvm::AArch64InstrInfo::isFunctionSafeToOutlineFrom(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isKnownTypeIdMember(), isSuitableForBSS(), isUnmergeableGlobal(), maybePrintComdat(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::AVRTargetObjectFile::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection().
LLVM_ATTRIBUTE_DEPRECATED()
llvm::GlobalObject::LLVM_ATTRIBUTE_DEPRECATED (void setAlignmentunsigned Align, "Please use `void setAlignment(MaybeAlign Align)`")
FIXME: Remove this setter once the migration to MaybeAlign is over.
Referenced by getAlignment().
setAlignment()
void GlobalObject::setAlignment (MaybeAlign Align)
Definition at line 116 of file Globals.cpp.
References assert(), llvm::encode(), llvm::GlobalValue::getAlignment(), llvm::GlobalValue::getGlobalValueSubClassData(), llvm::Value::MaximumAlignment, and llvm::GlobalValue::setGlobalValueSubClassData().
Referenced by canCreateAliasFor(), despeculateCountZeros(), llvm::orc::IRSpeculationLayer::emit(), forceRenaming(), FunctionNumber(), getAlignment(), llvm::OpenMPIRBuilder::initialize(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isKnownTypeIdMember(), maybeSetDSOLocal(), replace(), selectJumpTableArmEncoding(), and SRAGlobal().
setComdat()
void llvm::GlobalObject::setComdat (Comdat * C) inline
Definition at line 122 of file GlobalObject.h.
References C.
Referenced by canCreateThunkFor(), canRenameComdat(), copyComdat(), llvm::createDeadArgHackingPass(), llvm::createX86RetpolineThunksPass(), FunctionNumber(), llvm::GetOrCreateFunctionComdat(), getRetComponentType(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), LLVMSetComdat(), maybeSetDSOLocal(), rewriteComdat(), llvm::HWAddressSanitizerPass::run(), and llvm::ModuleSanitizerCoveragePass::run().
setGlobalObjectSubClassData()
void llvm::GlobalObject::setGlobalObjectSubClassData (unsigned Val) inline
Definition at line 90 of file GlobalObject.h.
References assert(), getGlobalObjectSubClassData(), llvm::GlobalValue::getGlobalValueSubClassData(), and llvm::GlobalValue::setGlobalValueSubClassData().
setMetadata() [1/2]
void GlobalObject::setMetadata (unsigned KindID, MDNode * MD)
Set a particular kind of metadata attachment.
Sets the given attachment to MD, erasing it if MD is nullptr or replacing it if it already exists.
Definition at line 1433 of file Metadata.cpp.
Referenced by llvm::createPGOFuncNameMetadata(), hasMetadata(), instrumentMaskedLoadOrStore(), and selectJumpTableArmEncoding().
setMetadata() [2/2]
void GlobalObject::setMetadata (StringRef Kind, MDNode * MD)
Definition at line 1439 of file Metadata.cpp.
References llvm::MDNode::getContext(), and setMetadata().
setSection()
void GlobalObject::setSection (StringRef S)
Change the section for this global.
Setting the section to the empty string tells LLVM to choose an appropriate default object file section.
Definition at line 215 of file Globals.cpp.
References llvm::StringRef::empty(), llvm::Value::getContext(), llvm::LLVMContextImpl::GlobalObjectSections, llvm::GlobalValue::hasSection(), llvm::LLVMContext::pImpl, llvm::UniqueStringSaver::save(), and llvm::LLVMContextImpl::Saver.
Referenced by AddCalls(), assureFPCallStub(), createFPFnStub(), llvm::EmbedBitcodeInModule(), FunctionNumber(), getSection(), instrumentMaskedLoadOrStore(), maybeSetDSOLocal(), needsRuntimeRegistrationOfSectionRange(), and setUsedInitializer().
Member Data Documentation
GlobalObjectSubClassDataBits
const unsigned llvm::GlobalObject::GlobalObjectSubClassDataBits static protected
Initial value:
=
      GlobalValueSubClassDataBits - GlobalObjectBits
Definition at line 62 of file GlobalObject.h.
ObjComdat
Comdat* llvm::GlobalObject::ObjComdat protected
Definition at line 54 of file GlobalObject.h.
Referenced by getComdat().
The documentation for this class was generated from the following files:
include/llvm/IR/GlobalObject.h
lib/IR/Globals.cpp
lib/IR/Metadata.cpp