LLVM: llvm::codeview::DebugStringTableSubsectionRef Class Reference
llvm::codeview::DebugStringTableSubsectionRef Class Reference
Represents a read-only view of a CodeView string table.
#include "llvm/DebugInfo/CodeView/DebugStringTableSubsection.h"
Public Member Functions
DebugStringTableSubsectionRef ()
Error initialize (BinaryStreamRef Contents)
Error initialize (BinaryStreamReader &Reader)
Expected< StringRef > getString (uint32_t Offset) const
bool valid () const
BinaryStreamRef getBuffer () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Represents a read-only view of a CodeView string table.
This is a very simple flat buffer consisting of null-terminated strings, where strings are retrieved by their offset in the buffer. DebugStringTableSubsectionRef does not own the underlying storage for the buffer.
Definition at line 31 of file DebugStringTableSubsection.h.
Constructor & Destructor Documentation
DebugStringTableSubsectionRef()
DebugStringTableSubsectionRef::DebugStringTableSubsectionRef ()
Definition at line 22 of file DebugStringTableSubsection.cpp.
References llvm::codeview::StringTable.
Member Function Documentation
classof()
static bool llvm::codeview::DebugStringTableSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 35 of file DebugStringTableSubsection.h.
References getString(), initialize(), llvm::codeview::DebugSubsectionRef::kind(), and llvm::codeview::StringTable.
getBuffer()
BinaryStreamRef llvm::codeview::DebugStringTableSubsectionRef::getBuffer () const inline
Definition at line 46 of file DebugStringTableSubsection.h.
getString()
Expected< StringRef > DebugStringTableSubsectionRef::getString (uint32_t Offset) const
Definition at line 35 of file DebugStringTableSubsection.cpp.
References llvm::codeview::EC, llvm::BinaryStreamReader::readCString(), and llvm::BinaryStreamReader::setOffset().
Referenced by classof().
initialize() [1/2]
Error DebugStringTableSubsectionRef::initialize (BinaryStreamRef Contents)
Definition at line 25 of file DebugStringTableSubsection.cpp.
References llvm::Error::success().
Referenced by classof(), and llvm::codeview::visitDebugSubsection().
initialize() [2/2]
Error DebugStringTableSubsectionRef::initialize (BinaryStreamReader & Reader)
Definition at line 30 of file DebugStringTableSubsection.cpp.
References llvm::BinaryStreamReader::readStreamRef().
valid()
bool llvm::codeview::DebugStringTableSubsectionRef::valid () const inline
Definition at line 44 of file DebugStringTableSubsection.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::valid().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugStringTableSubsection.h
lib/DebugInfo/CodeView/DebugStringTableSubsection.cpp