LLVM: llvm::MipsRegInfoRecord Class Reference
llvm::MipsRegInfoRecord Class Reference
#include "Target/Mips/MipsOptionRecord.h"
Public Member Functions
MipsRegInfoRecord (MipsELFStreamer *S, MCContext &Context)
~MipsRegInfoRecord () override=default
void EmitMipsOptionRecord () override
void SetPhysRegUsed (unsigned Reg, const MCRegisterInfo *MCRegInfo)
Public Member Functions inherited from llvm::MipsOptionRecord
virtual ~MipsOptionRecord ()=default
Detailed Description
Definition at line 38 of file MipsOptionRecord.h.
Constructor & Destructor Documentation
MipsRegInfoRecord()
llvm::MipsRegInfoRecord::MipsRegInfoRecord (MipsELFStreamer * S, MCContext & Context) inline
Definition at line 40 of file MipsOptionRecord.h.
References Context, llvm::MipsOptionRecord::EmitMipsOptionRecord(), llvm::MCRegisterInfo::getRegClass(), llvm::MCContext::getRegisterInfo(), Reg, and TRI.
~MipsRegInfoRecord()
llvm::MipsRegInfoRecord::~MipsRegInfoRecord () override default
Member Function Documentation
EmitMipsOptionRecord()
void MipsRegInfoRecord::EmitMipsOptionRecord () override virtual
Implements llvm::MipsOptionRecord.
Definition at line 22 of file MipsOptionRecord.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::MipsELFStreamer::EmitIntValue(), llvm::MipsTargetStreamer::getABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCContext::getELFSection(), llvm::MCStreamer::getTargetStreamer(), llvm::MipsABIInfo::IsN32(), llvm::MipsABIInfo::IsN64(), llvm::ELF::ODK_REGINFO, llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::MCAssembler::registerSection(), llvm::MCSection::setAlignment(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_MIPS_NOSTRIP, llvm::ELF::SHT_MIPS_OPTIONS, llvm::ELF::SHT_MIPS_REGINFO, and llvm::MipsELFStreamer::SwitchSection().
SetPhysRegUsed()
void MipsRegInfoRecord::SetPhysRegUsed (unsigned Reg, const MCRegisterInfo * MCRegInfo)
Definition at line 73 of file MipsOptionRecord.cpp.
References llvm::MCRegisterClass::contains(), llvm::MCRegisterInfo::getEncodingValue(), SubReg, and llvm::MCRegisterInfo::subregs_inclusive().
Referenced by llvm::MipsELFStreamer::EmitInstruction().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsOptionRecord.h
lib/Target/Mips/MCTargetDesc/MipsOptionRecord.cpp