LLVM: llvm::codeview::ArrayRecord Class Reference
llvm::codeview::ArrayRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
ArrayRecord ()=default
ArrayRecord (TypeRecordKind Kind)
ArrayRecord (TypeIndex ElementType, TypeIndex IndexType, uint64_t Size, StringRef Name)
TypeIndex getElementType () const
TypeIndex getIndexType () const
uint64_t getSize () const
StringRef getName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex ElementType
TypeIndex IndexType
uint64_t Size = 0
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 401 of file TypeRecord.h.
Constructor & Destructor Documentation
ArrayRecord() [1/3]
llvm::codeview::ArrayRecord::ArrayRecord () default
ArrayRecord() [2/3]
llvm::codeview::ArrayRecord::ArrayRecord (TypeRecordKind Kind) inline explicit
Definition at line 404 of file TypeRecord.h.
ArrayRecord() [3/3]
llvm::codeview::ArrayRecord::ArrayRecord (TypeIndex ElementType, TypeIndex IndexType, uint64_t Size, StringRef Name) inline
Definition at line 405 of file TypeRecord.h.
Member Function Documentation
getElementType()
TypeIndex llvm::codeview::ArrayRecord::getElementType () const inline
Definition at line 410 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getIndexType()
TypeIndex llvm::codeview::ArrayRecord::getIndexType () const inline
Definition at line 411 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getName()
StringRef llvm::codeview::ArrayRecord::getName () const inline
Definition at line 413 of file TypeRecord.h.
References Name.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getSize()
uint64_t llvm::codeview::ArrayRecord::getSize () const inline
Definition at line 412 of file TypeRecord.h.
References Size.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
ElementType
TypeIndex llvm::codeview::ArrayRecord::ElementType
Definition at line 415 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
IndexType
TypeIndex llvm::codeview::ArrayRecord::IndexType
Definition at line 416 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Name
StringRef llvm::codeview::ArrayRecord::Name
Definition at line 418 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
Size
uint64_t llvm::codeview::ArrayRecord::Size = 0
Definition at line 417 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h