LLVM: llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize > Class Template Reference
llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize > Class Template Reference
Interface implemented by fragments that contain encoded instructions and/or data and also have fixups registered.
#include "llvm/MC/MCFragment.h"
Public Types
using const_fixup_iterator = SmallVectorImpl< MCFixup >::const_iterator
using fixup_iterator = SmallVectorImpl< MCFixup >::iterator
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB, FT_BoundaryAlign, FT_SymbolId, FT_CVInlineLines,
FT_CVDefRange, FT_Dummy
}
Public Member Functions
SmallVectorImpl< MCFixup > & getFixups ()
const SmallVectorImpl< MCFixup > & getFixups () const
fixup_iterator fixup_begin ()
const_fixup_iterator fixup_begin () const
fixup_iterator fixup_end ()
const_fixup_iterator fixup_end () const
Public Member Functions inherited from llvm::MCEncodedFragmentWithContents< ContentsSize >
SmallVectorImpl< char > & getContents ()
const SmallVectorImpl< char > & getContents () const
Public Member Functions inherited from llvm::MCEncodedFragment
bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
void setAlignToBundleEnd (bool V)
uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment.
void setBundlePadding (uint8_t N)
Set the padding size for this fragment.
const MCSubtargetInfo * getSubtargetInfo () const
Retrieve the MCSubTargetInfo in effect when the instruction was encoded.
void setHasInstructions (const MCSubtargetInfo &STI)
Record that the fragment contains instructions with the MCSubtargetInfo in effect when the instruction was encoded.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragment
static bool classof (const MCFragment *F)
Protected Member Functions
MCEncodedFragmentWithFixups (MCFragment::FragmentType FType, bool HasInstructions, MCSection *Sec)
Protected Member Functions inherited from llvm::MCEncodedFragmentWithContents< ContentsSize >
MCEncodedFragmentWithContents (MCFragment::FragmentType FType, bool HasInstructions, MCSection *Sec)
Protected Member Functions inherited from llvm::MCEncodedFragment
MCEncodedFragment (MCFragment::FragmentType FType, bool HasInstructions, MCSection *Sec)
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
ilist_node_impl ()=default
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< MCFragment, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< MCFragment, Options... >::type, true, true >
Protected Attributes inherited from llvm::MCEncodedFragment
const MCSubtargetInfo * STI = nullptr
The MCSubtargetInfo in effect when the instruction was encoded.
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions
Detailed Description
template<unsigned ContentsSize, unsigned FixupsSize>
class llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >
Interface implemented by fragments that contain encoded instructions and/or data and also have fixups registered.
Definition at line 192 of file MCFragment.h.
Member Typedef Documentation
const_fixup_iterator
template<unsigned ContentsSize, unsigned FixupsSize> using llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::const_fixup_iterator = SmallVectorImpl<MCFixup>::const_iterator
Definition at line 207 of file MCFragment.h.
fixup_iterator
template<unsigned ContentsSize, unsigned FixupsSize> using llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_iterator = SmallVectorImpl<MCFixup>::iterator
Definition at line 208 of file MCFragment.h.
Constructor & Destructor Documentation
MCEncodedFragmentWithFixups()
template<unsigned ContentsSize, unsigned FixupsSize> llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::MCEncodedFragmentWithFixups (MCFragment::FragmentType FType, bool HasInstructions, MCSection * Sec) inline protected
Definition at line 199 of file MCFragment.h.
Member Function Documentation
classof()
template<unsigned ContentsSize, unsigned FixupsSize> static bool llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::classof (const MCFragment * F) inline static
Definition at line 219 of file MCFragment.h.
fixup_begin() [1/2]
template<unsigned ContentsSize, unsigned FixupsSize> fixup_iterator llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_begin () inline
Definition at line 213 of file MCFragment.h.
Referenced by llvm::MCAssembler::writeSectionData().
fixup_begin() [2/2]
template<unsigned ContentsSize, unsigned FixupsSize> const_fixup_iterator llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_begin () const inline
Definition at line 214 of file MCFragment.h.
fixup_end() [1/2]
template<unsigned ContentsSize, unsigned FixupsSize> fixup_iterator llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_end () inline
Definition at line 216 of file MCFragment.h.
Referenced by llvm::MCAssembler::writeSectionData().
fixup_end() [2/2]
template<unsigned ContentsSize, unsigned FixupsSize> const_fixup_iterator llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_end () const inline
Definition at line 217 of file MCFragment.h.
getFixups() [1/2]
template<unsigned ContentsSize, unsigned FixupsSize> SmallVectorImpl<MCFixup>& llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups () inline
Definition at line 210 of file MCFragment.h.
Referenced by CheckBundleSubtargets(), llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCObjectStreamer::EmitDTPRel32Value(), llvm::MCObjectStreamer::EmitDTPRel64Value(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::MCWasmStreamer::EmitIdent(), llvm::MCELFStreamer::EmitIdent(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), llvm::MCObjectStreamer::EmitRelocDirective(), llvm::MCObjectStreamer::EmitTPRel32Value(), llvm::MCObjectStreamer::EmitTPRel64Value(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::CodeViewContext::encodeDefRange(), llvm::MCAssembler::Finish(), GetAEABIUnwindPersonalityName(), llvm::MCELFStreamer::MCELFStreamer(), and needPadding().
getFixups() [2/2]
template<unsigned ContentsSize, unsigned FixupsSize> const SmallVectorImpl<MCFixup>& llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups () const inline
Definition at line 211 of file MCFragment.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h