LLVM: llvm::RegionPass Class Reference
llvm::RegionPass Class Reference abstract
A pass that runs on each Region in a function.
#include "llvm/Analysis/RegionPass.h"
Public Member Functions
RegionPass (char &pid)
To be implemented by every RegionPass
virtual bool runOnRegion (Region *R, RGPassManager &RGM)=0
Run the pass on a specific Region.
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
Get a pass to print the LLVM IR in the region.
virtual bool doInitialization (Region *R, RGPassManager &RGM)
virtual bool doFinalization ()
PassManager API
void preparePassManager (PMStack &PMS) override
Check if available pass managers are suitable for this pass or not.
void assignPassManager (PMStack &PMS, PassManagerType PMT=PMT_RegionPassManager) override
Assign pass manager to manage this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Member Functions
bool skipRegion (Region &R) const
Optional passes call this function to check whether the pass should be skipped.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
A pass that runs on each Region in a function.
RegionPass is managed by RGPassManager.
Definition at line 33 of file RegionPass.h.
Constructor & Destructor Documentation
RegionPass()
llvm::RegionPass::RegionPass (char & pid) inline explicit
Definition at line 35 of file RegionPass.h.
References createPrinterPass(), llvm::Pass::doFinalization(), llvm::Pass::doInitialization(), llvm::RISCVFenceField::O, and runOnRegion().
Member Function Documentation
assignPassManager()
void RegionPass::assignPassManager (PMStack & PMS, PassManagerType PMT = PMT_RegionPassManager) override virtual
Assign pass manager to manage this pass.
Reimplemented from llvm::Pass.
Definition at line 239 of file RegionPass.cpp.
References llvm::PMDataManager::add(), llvm::PMTopLevelManager::addIndirectPassManager(), assert(), llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_RegionPassManager, llvm::PMStack::pop(), llvm::PMDataManager::populateInheritedAnalysis(), llvm::PMStack::push(), llvm::RGPassManager::RGPassManager(), llvm::PMTopLevelManager::schedulePass(), llvm::PMStack::top(), and llvm::PMDataManager::TPM.
Referenced by doFinalization().
createPrinterPass()
Pass * RegionPass::createPrinterPass (raw_ostream & O, const std::string & Banner) const override virtual
Get a pass to print the LLVM IR in the region.
Get the printer pass.
Parameters
O The output stream to print the Region.
Banner The banner to separate different printed passes.
Returns
The pass to print the LLVM IR in the region.
Implements llvm::Pass.
Definition at line 276 of file RegionPass.cpp.
Referenced by RegionPass().
doFinalization()
virtual bool llvm::RegionPass::doFinalization () inline virtual
Definition at line 64 of file RegionPass.h.
References assignPassManager(), llvm::PMT_RegionPassManager, and preparePassManager().
Referenced by llvm::RGPassManager::runOnFunction().
doInitialization()
virtual bool llvm::RegionPass::doInitialization (Region * R, RGPassManager & RGM) inline virtual
Definition at line 63 of file RegionPass.h.
Referenced by llvm::RGPassManager::runOnFunction().
getPotentialPassManagerType()
PassManagerType llvm::RegionPass::getPotentialPassManagerType () const inline override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 76 of file RegionPass.h.
References llvm::PMT_RegionPassManager, and skipRegion().
preparePassManager()
void RegionPass::preparePassManager (PMStack &) override virtual
Check if available pass managers are suitable for this pass or not.
Reimplemented from llvm::Pass.
Definition at line 222 of file RegionPass.cpp.
References llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_RegionPassManager, llvm::PMStack::pop(), llvm::PMDataManager::preserveHigherLevelAnalysis(), and llvm::PMStack::top().
Referenced by doFinalization().
runOnRegion()
virtual bool llvm::RegionPass::runOnRegion (Region * R, RGPassManager & RGM) pure virtual
Run the pass on a specific Region.
Accessing regions not contained in the current region is not allowed.
Parameters
R The region this pass is run on.
RGM The RegionPassManager that manages this Pass.
Returns
True if the pass modifies this Region.
Referenced by RegionPass(), and llvm::RGPassManager::runOnFunction().
skipRegion()
bool RegionPass::skipRegion (Region & R) const protected
Optional passes call this function to check whether the pass should be skipped.
This is the case when optimization bisect is over the limit.
Definition at line 285 of file RegionPass.cpp.
References llvm::dbgs(), F(), llvm::Function::getContext(), getDescription(), llvm::RegionBase< Tr >::getEntry(), llvm::Function::getEntryBlock(), llvm::Value::getName(), llvm::LLVMContext::getOptPassGate(), llvm::RGPassManager::getPassName(), llvm::Function::hasOptNone(), llvm::OptPassGate::isEnabled(), LLVM_DEBUG, and llvm::OptPassGate::shouldRunPass().
Referenced by getPotentialPassManagerType().
The documentation for this class was generated from the following files:
include/llvm/Analysis/RegionPass.h
lib/Analysis/RegionPass.cpp