LLVM: llvm::WeakVH Class Reference
llvm::WeakVH Class Reference
A nullable Value handle that is nullable.
#include "llvm/IR/ValueHandle.h"
Public Member Functions
WeakVH ()
WeakVH (Value *P)
WeakVH (const WeakVH &RHS)
WeakVH & operator= (const WeakVH &RHS)=default
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
operator Value * () const
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert, Callback, Weak, WeakTracking }
This indicates what sub class the handle actually is.
Protected Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (const ValueHandleBase &RHS)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
Value * getValPtr () const
void RemoveFromUseList ()
Remove this ValueHandle from its current use list.
void clearValPtr ()
Clear the underlying pointer without clearing the use list.
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
A nullable Value handle that is nullable.
This is a value handle that points to a value, and nulls itself out if that value is deleted.
Definition at line 140 of file ValueHandle.h.
Constructor & Destructor Documentation
WeakVH() [1/3]
llvm::WeakVH::WeakVH () inline
Definition at line 142 of file ValueHandle.h.
WeakVH() [2/3]
llvm::WeakVH::WeakVH (Value * P) inline
Definition at line 143 of file ValueHandle.h.
WeakVH() [3/3]
llvm::WeakVH::WeakVH (const WeakVH & RHS) inline
Definition at line 144 of file ValueHandle.h.
References llvm::ValueHandleBase::operator=().
Member Function Documentation
operator Value *()
llvm::WeakVH::operator Value * () const inline
Definition at line 156 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
operator=() [1/3]
WeakVH& llvm::WeakVH::operator= (const WeakVH & RHS) default
operator=() [2/3]
Value* llvm::WeakVH::operator= (Value * RHS) inline
Definition at line 149 of file ValueHandle.h.
References llvm::ValueHandleBase::operator=().
operator=() [3/3]
Value* llvm::WeakVH::operator= (const ValueHandleBase & RHS) inline
Definition at line 152 of file ValueHandle.h.
References llvm::ValueHandleBase::operator=().
The documentation for this class was generated from the following file:
include/llvm/IR/ValueHandle.h