LLVM: llvm::DebugLocStream Class Reference
llvm::DebugLocStream Class Reference
Byte stream of .debug_loc entries.
#include "CodeGen/AsmPrinter/DebugLocStream.h"
Classes
struct Entry
class EntryBuilder
Builder for DebugLocStream entries.
struct List
class ListBuilder
Builder for DebugLocStream lists.
Public Member Functions
DebugLocStream (bool GenerateComments)
size_t getNumLists () const
const List & getList (size_t LI) const
ArrayRef< List > getLists () const
MCSymbol * getSym () const
void setSym (MCSymbol *Sym)
BufferByteStreamer getStreamer ()
ArrayRef< Entry > getEntries (const List &L) const
ArrayRef< char > getBytes (const Entry &E) const
ArrayRef< std::string > getComments (const Entry &E) const
Detailed Description
Byte stream of .debug_loc entries.
Stores a unified stream of .debug_loc entries. There's List for each variable/inlined-at pair, and an Entry for each DebugLocEntry.
FIXME: Do we need all these temp symbols? FIXME: Why not output directly to the output stream?
Definition at line 31 of file DebugLocStream.h.
Constructor & Destructor Documentation
DebugLocStream()
llvm::DebugLocStream::DebugLocStream (bool GenerateComments) inline
Definition at line 59 of file DebugLocStream.h.
Member Function Documentation
getBytes()
ArrayRef<char> llvm::DebugLocStream::getBytes (const Entry & E) const inline
Definition at line 116 of file DebugLocStream.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getNumBytes(), and llvm::makeArrayRef().
Referenced by llvm::DwarfDebug::emitDebugLocEntryLocation().
getComments()
ArrayRef<std::string> llvm::DebugLocStream::getComments (const Entry & E) const inline
Definition at line 121 of file DebugLocStream.h.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), E, llvm::SmallVectorTemplateCommon< T >::front(), getNumBytes(), llvm::makeArrayRef(), and llvm::SmallVectorBase::size().
Referenced by llvm::DwarfDebug::emitDebugLocEntry().
getEntries()
ArrayRef<Entry> llvm::DebugLocStream::getEntries (const List & L) const inline
Definition at line 110 of file DebugLocStream.h.
References llvm::DebugLocStream::List::EntryOffset, and llvm::makeArrayRef().
Referenced by emitLocList().
getList()
const List& llvm::DebugLocStream::getList (size_t LI) const inline
Definition at line 61 of file DebugLocStream.h.
Referenced by llvm::DIELocList::EmitValue().
getLists()
ArrayRef<List> llvm::DebugLocStream::getLists () const inline
Definition at line 62 of file DebugLocStream.h.
Referenced by llvm::DwarfDebug::beginModule(), emitLocList(), and emitLoclistsTableHeader().
getNumLists()
size_t llvm::DebugLocStream::getNumLists () const inline
Definition at line 60 of file DebugLocStream.h.
References llvm::SmallVectorBase::size().
getStreamer()
BufferByteStreamer llvm::DebugLocStream::getStreamer () inline
Definition at line 106 of file DebugLocStream.h.
Referenced by llvm::DebugLocStream::EntryBuilder::getStreamer().
getSym()
MCSymbol* llvm::DebugLocStream::getSym () const inline
Definition at line 63 of file DebugLocStream.h.
Referenced by llvm::DwarfDebug::beginModule(), and emitLoclistsTableHeader().
setSym()
void llvm::DebugLocStream::setSym (MCSymbol * Sym) inline
Definition at line 66 of file DebugLocStream.h.
References llvm::HexStyle::Asm, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorBase::size().
Referenced by llvm::DwarfDebug::beginModule().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DebugLocStream.h
lib/CodeGen/AsmPrinter/DebugLocStream.cpp