LLVM: llvm::AVRRegisterInfo Class Reference
llvm::AVRRegisterInfo Class Reference
Utilities relating to AVR registers.
#include "Target/AVR/AVRRegisterInfo.h"
Public Member Functions
AVRRegisterInfo ()
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const override
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC, const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=NULL) const override
Stack Frame Processing Methods.
Register getFrameRegister (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
void splitReg (unsigned Reg, unsigned &LoReg, unsigned &HiReg) const
Splits a 16-bit DREGS register into the lo/hi register pair.
bool trackLivenessAfterRegAlloc (const MachineFunction &) const override
bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC, LiveIntervals &LIS) const override
Detailed Description
Utilities relating to AVR registers.
Definition at line 24 of file AVRRegisterInfo.h.
Constructor & Destructor Documentation
AVRRegisterInfo()
llvm::AVRRegisterInfo::AVRRegisterInfo ()
Definition at line 33 of file AVRRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void llvm::AVRRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = NULL) const override
Stack Frame Processing Methods.
Definition at line 128 of file AVRRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineBasicBlock::end(), llvm::foldFrameOffset(), llvm::ISD::FrameIndex, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::AVRSubtarget::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AVRSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFrameInfo::getStackSize(), llvm::AVRTargetMachine::getSubtargetImpl(), llvm::MachineFunction::getTarget(), llvm::RegState::Kill, LLVM_FALLTHROUGH, MI, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIsDead(), TII, and llvm::SystemZISD::TM.
getCalleeSavedRegs()
const uint16_t * llvm::AVRRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = 0) const override
Definition at line 36 of file AVRRegisterInfo.cpp.
References llvm::CallingConv::AVR_INTR, llvm::CallingConv::AVR_SIGNAL, llvm::Function::getCallingConv(), and llvm::MachineFunction::getFunction().
getCallPreservedMask()
const uint32_t * llvm::AVRRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 45 of file AVRRegisterInfo.cpp.
References llvm::CallingConv::AVR_INTR, and llvm::CallingConv::AVR_SIGNAL.
getFrameRegister()
Register llvm::AVRRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 248 of file AVRRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
getLargestLegalSuperClass()
const TargetRegisterClass * llvm::AVRRegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC, const MachineFunction & MF) const override
Definition at line 83 of file AVRRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MVT::i16, llvm::MVT::i8, llvm::TargetRegisterInfo::isTypeLegalForClass(), llvm_unreachable, and TRI.
getPointerRegClass()
const TargetRegisterClass * llvm::AVRRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 259 of file AVRRegisterInfo.cpp.
getReservedRegs()
BitVector llvm::AVRRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 52 of file AVRRegisterInfo.cpp.
References llvm::BitVector::set().
shouldCoalesce()
bool llvm::AVRRegisterInfo::shouldCoalesce (MachineInstr * MI, const TargetRegisterClass * SrcRC, unsigned SubReg, const TargetRegisterClass * DstRC, unsigned DstSubReg, const TargetRegisterClass * NewRC, LiveIntervals & LIS) const override
Definition at line 276 of file AVRRegisterInfo.cpp.
References getRegClass(), and llvm::TargetRegisterInfo::shouldCoalesce().
Referenced by trackLivenessAfterRegAlloc().
splitReg()
void llvm::AVRRegisterInfo::splitReg (unsigned Reg, unsigned & LoReg, unsigned & HiReg) const
Splits a 16-bit DREGS register into the lo/hi register pair.
Parameters
Reg A 16-bit register to split.
Definition at line 267 of file AVRRegisterInfo.cpp.
References assert(), and contains().
trackLivenessAfterRegAlloc()
bool llvm::AVRRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction &) const inline override
Definition at line 54 of file AVRRegisterInfo.h.
References shouldCoalesce(), and SubReg.
The documentation for this class was generated from the following files:
lib/Target/AVR/AVRRegisterInfo.h
lib/Target/AVR/AVRRegisterInfo.cpp