LLVM: llvm::TargetFolder Class Reference
llvm::TargetFolder Class Reference
TargetFolder - Create constants with target dependent folding.
#include "llvm/Analysis/TargetFolder.h"
Public Member Functions
TargetFolder (const DataLayout &DL)
Constant * CreateAdd (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFAdd (Constant *LHS, Constant *RHS) const
Constant * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFSub (Constant *LHS, Constant *RHS) const
Constant * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFMul (Constant *LHS, Constant *RHS) const
Constant * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateFDiv (Constant *LHS, Constant *RHS) const
Constant * CreateURem (Constant *LHS, Constant *RHS) const
Constant * CreateSRem (Constant *LHS, Constant *RHS) const
Constant * CreateFRem (Constant *LHS, Constant *RHS) const
Constant * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateAnd (Constant *LHS, Constant *RHS) const
Constant * CreateOr (Constant *LHS, Constant *RHS) const
Constant * CreateXor (Constant *LHS, Constant *RHS) const
Constant * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const
Constant * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFNeg (Constant *C) const
Constant * CreateNot (Constant *C) const
Constant * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant *> IdxList) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value *> IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant *> IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value *> IdxList) const
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const
Constant * CreatePointerCast (Constant *C, Type *DestTy) const
Constant * CreateFPCast (Constant *C, Type *DestTy) const
Constant * CreateBitCast (Constant *C, Type *DestTy) const
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const
Constant * CreateICmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Constant * CreateSelect (Constant *C, Constant *True, Constant *False) const
Constant * CreateExtractElement (Constant *Vec, Constant *Idx) const
Constant * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const
Constant * CreateShuffleVector (Constant *V1, Constant *V2, Constant *Mask) const
Constant * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const
Constant * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const
Detailed Description
TargetFolder - Create constants with target dependent folding.
Definition at line 31 of file TargetFolder.h.
Constructor & Destructor Documentation
TargetFolder()
llvm::TargetFolder::TargetFolder (const DataLayout & DL) inline explicit
Definition at line 42 of file TargetFolder.h.
Member Function Documentation
CreateAdd()
Constant* llvm::TargetFolder::CreateAdd (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 48 of file TargetFolder.h.
References llvm::ConstantExpr::getAdd().
CreateAnd()
Constant* llvm::TargetFolder::CreateAnd (Constant * LHS, Constant * RHS) const inline
Definition at line 97 of file TargetFolder.h.
References llvm::ConstantExpr::getAnd().
CreateAShr()
Constant* llvm::TargetFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 94 of file TargetFolder.h.
References llvm::ConstantExpr::getAShr().
CreateBinOp()
Constant* llvm::TargetFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline
Definition at line 107 of file TargetFolder.h.
References llvm::ConstantExpr::get().
CreateBitCast()
Constant* llvm::TargetFolder::CreateBitCast (Constant * C, Type * DestTy) const inline
Definition at line 192 of file TargetFolder.h.
References CreateCast().
CreateCast()
Constant* llvm::TargetFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline
Definition at line 170 of file TargetFolder.h.
References llvm::ConstantExpr::getCast(), and llvm::Value::getType().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateExtractElement()
Constant* llvm::TargetFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline
Definition at line 245 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractElement().
CreateExtractValue()
Constant* llvm::TargetFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline
Definition at line 259 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractValue().
CreateFAdd()
Constant* llvm::TargetFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline
Definition at line 52 of file TargetFolder.h.
References llvm::ConstantExpr::getFAdd().
CreateFCmp()
Constant* llvm::TargetFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline
Definition at line 232 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare().
CreateFDiv()
Constant* llvm::TargetFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline
Definition at line 75 of file TargetFolder.h.
References llvm::ConstantExpr::getFDiv().
CreateFMul()
Constant* llvm::TargetFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline
Definition at line 66 of file TargetFolder.h.
References llvm::ConstantExpr::getFMul().
CreateFNeg()
Constant* llvm::TargetFolder::CreateFNeg (Constant * C) const inline
Definition at line 120 of file TargetFolder.h.
References llvm::ConstantExpr::getFNeg().
CreateFPCast()
Constant* llvm::TargetFolder::CreateFPCast (Constant * C, Type * DestTy) const inline
Definition at line 187 of file TargetFolder.h.
References llvm::ConstantExpr::getFPCast(), and llvm::Value::getType().
CreateFRem()
Constant* llvm::TargetFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline
Definition at line 84 of file TargetFolder.h.
References llvm::ConstantExpr::getFRem().
CreateFSub()
Constant* llvm::TargetFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline
Definition at line 59 of file TargetFolder.h.
References llvm::ConstantExpr::getFSub().
CreateGetElementPtr() [1/3]
Constant* llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant *> IdxList) const inline
Definition at line 135 of file TargetFolder.h.
References llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [2/3]
Constant* llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline
Definition at line 139 of file TargetFolder.h.
References llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [3/3]
Constant* llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value *> IdxList) const inline
Definition at line 145 of file TargetFolder.h.
References llvm::ConstantExpr::getGetElementPtr().
CreateICmp()
Constant* llvm::TargetFolder::CreateICmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline
Definition at line 228 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare().
CreateInBoundsGetElementPtr() [1/3]
Constant* llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant *> IdxList) const inline
Definition at line 150 of file TargetFolder.h.
References llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [2/3]
Constant* llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline
Definition at line 154 of file TargetFolder.h.
References llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [3/3]
Constant* llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value *> IdxList) const inline
Definition at line 161 of file TargetFolder.h.
References llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInsertElement()
Constant* llvm::TargetFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline
Definition at line 249 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertElement().
CreateInsertValue()
Constant* llvm::TargetFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline
Definition at line 264 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertValue().
CreateIntCast()
Constant* llvm::TargetFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline
Definition at line 176 of file TargetFolder.h.
References llvm::ConstantExpr::getIntegerCast(), and llvm::Value::getType().
CreateIntToPtr()
Constant* llvm::TargetFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline
Definition at line 195 of file TargetFolder.h.
References CreateCast().
CreateLShr()
Constant* llvm::TargetFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 91 of file TargetFolder.h.
References llvm::ConstantExpr::getLShr().
CreateMul()
Constant* llvm::TargetFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 62 of file TargetFolder.h.
References llvm::ConstantExpr::getMul().
CreateNeg()
Constant* llvm::TargetFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 116 of file TargetFolder.h.
References llvm::ConstantExpr::getNeg().
CreateNot()
Constant* llvm::TargetFolder::CreateNot (Constant * C) const inline
Definition at line 123 of file TargetFolder.h.
References llvm::ConstantExpr::getNot().
CreateOr()
Constant* llvm::TargetFolder::CreateOr (Constant * LHS, Constant * RHS) const inline
Definition at line 100 of file TargetFolder.h.
References llvm::ConstantExpr::getOr().
CreatePointerBitCastOrAddrSpaceCast()
Constant* llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline
Definition at line 217 of file TargetFolder.h.
References llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), and llvm::Value::getType().
CreatePointerCast()
Constant* llvm::TargetFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline
Definition at line 182 of file TargetFolder.h.
References llvm::ConstantExpr::getPointerCast(), and llvm::Value::getType().
CreatePtrToInt()
Constant* llvm::TargetFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline
Definition at line 198 of file TargetFolder.h.
References CreateCast().
CreateSDiv()
Constant* llvm::TargetFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 72 of file TargetFolder.h.
References llvm::ConstantExpr::getSDiv().
CreateSelect()
Constant* llvm::TargetFolder::CreateSelect (Constant * C, Constant * True, Constant * False) const inline
Definition at line 241 of file TargetFolder.h.
References llvm::ConstantExpr::getSelect().
CreateSExtOrBitCast()
Constant* llvm::TargetFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 206 of file TargetFolder.h.
References llvm::ConstantExpr::getSExtOrBitCast(), and llvm::Value::getType().
CreateShl()
Constant* llvm::TargetFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 87 of file TargetFolder.h.
References llvm::ConstantExpr::getShl().
CreateShuffleVector()
Constant* llvm::TargetFolder::CreateShuffleVector (Constant * V1, Constant * V2, Constant * Mask) const inline
Definition at line 254 of file TargetFolder.h.
References llvm::ConstantExpr::getShuffleVector().
CreateSRem()
Constant* llvm::TargetFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline
Definition at line 81 of file TargetFolder.h.
References llvm::ConstantExpr::getSRem().
CreateSub()
Constant* llvm::TargetFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 55 of file TargetFolder.h.
References llvm::ConstantExpr::getSub().
CreateTruncOrBitCast()
Constant* llvm::TargetFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 211 of file TargetFolder.h.
References llvm::ConstantExpr::getTruncOrBitCast(), and llvm::Value::getType().
CreateUDiv()
Constant* llvm::TargetFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 69 of file TargetFolder.h.
References llvm::ConstantExpr::getUDiv().
CreateUnOp()
Constant* llvm::TargetFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline
Definition at line 127 of file TargetFolder.h.
References llvm::ConstantExpr::get().
CreateURem()
Constant* llvm::TargetFolder::CreateURem (Constant * LHS, Constant * RHS) const inline
Definition at line 78 of file TargetFolder.h.
References llvm::ConstantExpr::getURem().
CreateXor()
Constant* llvm::TargetFolder::CreateXor (Constant * LHS, Constant * RHS) const inline
Definition at line 103 of file TargetFolder.h.
References llvm::ConstantExpr::getXor().
CreateZExtOrBitCast()
Constant* llvm::TargetFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 201 of file TargetFolder.h.
References llvm::Value::getType(), and llvm::ConstantExpr::getZExtOrBitCast().
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetFolder.h