LLVM: llvm::vfs::YAMLVFSWriter Class Reference
llvm::vfs::YAMLVFSWriter Class Reference
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
YAMLVFSWriter ()=default
void addFileMapping (StringRef VirtualPath, StringRef RealPath)
void setCaseSensitivity (bool CaseSensitive)
void setUseExternalNames (bool UseExtNames)
void setOverlayDir (StringRef OverlayDirectory)
const std::vector< YAMLVFSEntry > & getMappings () const
void write (llvm::raw_ostream &OS)
Detailed Description
Definition at line 777 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
YAMLVFSWriter()
llvm::vfs::YAMLVFSWriter::YAMLVFSWriter () default
Member Function Documentation
addFileMapping()
void YAMLVFSWriter::addFileMapping (StringRef VirtualPath, StringRef RealPath)
Definition at line 1897 of file VirtualFileSystem.cpp.
References assert(), llvm::StringRef::back(), llvm::sys::path::begin(), llvm::StringRef::empty(), llvm::ArrayRef< T >::empty(), llvm::sys::path::end(), llvm::yaml::escape(), llvm::sys::path::filename(), llvm::ArrayRef< T >::front(), llvm::Optional< T >::getValue(), llvm::Optional< T >::hasValue(), llvm::sys::path::is_absolute(), Mappings, llvm::StringRef::npos, llvm::sys::path::parent_path(), pathHasTraversal(), llvm::vfs::YAMLVFSEntry::RPath, llvm::SmallVectorBase::size(), llvm::StringRef::size(), llvm::ArrayRef< T >::slice(), llvm::StringRef::slice(), llvm::StringRef::substr(), llvm::vfs::YAMLVFSEntry::VPath, and write().
getMappings()
const std::vector<YAMLVFSEntry>& llvm::vfs::YAMLVFSWriter::getMappings () const inline
Definition at line 800 of file VirtualFileSystem.h.
References Mappings, and write().
Referenced by llvm::FileCollector::copyFiles().
setCaseSensitivity()
void llvm::vfs::YAMLVFSWriter::setCaseSensitivity (bool CaseSensitive) inline
Definition at line 789 of file VirtualFileSystem.h.
Referenced by llvm::FileCollector::writeMapping().
setOverlayDir()
void llvm::vfs::YAMLVFSWriter::setOverlayDir (StringRef OverlayDirectory) inline
Definition at line 795 of file VirtualFileSystem.h.
References llvm::StringRef::str().
Referenced by llvm::FileCollector::writeMapping().
setUseExternalNames()
void llvm::vfs::YAMLVFSWriter::setUseExternalNames (bool UseExtNames) inline
Definition at line 793 of file VirtualFileSystem.h.
Referenced by llvm::FileCollector::writeMapping().
write()
void YAMLVFSWriter::write (llvm::raw_ostream & OS)
Definition at line 2047 of file VirtualFileSystem.cpp.
References Mappings, llvm::sort(), and llvm::vfs::YAMLVFSEntry::VPath.
Referenced by llvm::FileCollector::writeMapping().
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualFileSystem.h
lib/Support/VirtualFileSystem.cpp