LLVM: llvm::DWARFListTableHeader Class Reference
llvm::DWARFListTableHeader Class Reference
A class representing the header of a list table such as the range list table in the .debug_rnglists section.
#include "llvm/DebugInfo/DWARF/DWARFListTable.h"
Public Member Functions
DWARFListTableHeader (StringRef SectionName, StringRef ListTypeString)
void clear ()
uint64_t getHeaderOffset () const
uint8_t getAddrSize () const
uint64_t getLength () const
uint16_t getVersion () const
StringRef getSectionName () const
StringRef getListTypeString () const
dwarf::DwarfFormat getFormat () const
void dump (raw_ostream &OS, DIDumpOptions DumpOpts={}) const
Optional< uint64_t > getOffsetEntry (uint32_t Index) const
Error extract (DWARFDataExtractor Data, uint64_t *OffsetPtr)
Extract the table header and the array of offsets.
uint64_t length () const
Returns the length of the table, including the length field, or 0 if the length has not been determined (e.g.
Static Public Member Functions
static uint8_t getHeaderSize (dwarf::DwarfFormat Format)
Return the size of the table header including the length but not including the offsets.
Detailed Description
A class representing the header of a list table such as the range list table in the .debug_rnglists section.
Definition at line 56 of file DWARFListTable.h.
Constructor & Destructor Documentation
DWARFListTableHeader()
llvm::DWARFListTableHeader::DWARFListTableHeader (StringRef SectionName, StringRef ListTypeString) inline
Definition at line 91 of file DWARFListTable.h.
Member Function Documentation
clear()
void llvm::DWARFListTableHeader::clear () inline
Definition at line 94 of file DWARFListTable.h.
Referenced by llvm::DWARFListTableBase< DWARFDebugRnglist >::clear().
dump()
void DWARFListTableHeader::dump (raw_ostream & OS, DIDumpOptions DumpOpts = {}) const
Definition at line 89 of file DWARFListTable.cpp.
References llvm::StringRef::data(), llvm::format(), getHeaderSize(), and llvm::DIDumpOptions::Verbose.
Referenced by dumpLoclistsSection().
extract()
Error DWARFListTableHeader::extract (DWARFDataExtractor Data, uint64_t * OffsetPtr)
Extract the table header and the array of offsets.
Definition at line 18 of file DWARFListTable.cpp.
References assert(), llvm::createStringError(), llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DW_LENGTH_lo_reserved, llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, getHeaderSize(), llvm::DWARFDataExtractor::getRelocatedValue(), llvm::DataExtractor::getU64(), llvm::dwarf::getUnitLengthFieldByteSize(), llvm::invalid_argument, llvm::DataExtractor::isValidOffsetForDataOfSize(), and length().
Referenced by dumpLoclistsSection(), and llvm::DWARFListTableBase< DWARFDebugRnglist >::extractHeaderAndOffsets().
getAddrSize()
uint8_t llvm::DWARFListTableHeader::getAddrSize () const inline
Definition at line 99 of file DWARFListTable.h.
Referenced by dumpLoclistsSection(), and llvm::DWARFListTableBase< DWARFDebugRnglist >::getAddrSize().
getFormat()
dwarf::DwarfFormat llvm::DWARFListTableHeader::getFormat () const inline
Definition at line 104 of file DWARFListTable.h.
References llvm::Format.
Referenced by llvm::DWARFListTableBase< DWARFDebugRnglist >::getFormat().
getHeaderOffset()
uint64_t llvm::DWARFListTableHeader::getHeaderOffset () const inline
Definition at line 98 of file DWARFListTable.h.
Referenced by dumpLoclistsSection(), and llvm::DWARFListTableBase< DWARFDebugRnglist >::getHeaderOffset().
getHeaderSize()
static uint8_t llvm::DWARFListTableHeader::getHeaderSize (dwarf::DwarfFormat Format) inline static
Return the size of the table header including the length but not including the offsets.
Definition at line 108 of file DWARFListTable.h.
References llvm::dump(), llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, and llvm_unreachable.
Referenced by dump(), extract(), llvm::DWARFListTableBase< DWARFDebugRnglist >::getHeaderSize(), parseListTableHeader(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
getLength()
uint64_t llvm::DWARFListTableHeader::getLength () const inline
Definition at line 100 of file DWARFListTable.h.
getListTypeString()
StringRef llvm::DWARFListTableHeader::getListTypeString () const inline
Definition at line 103 of file DWARFListTable.h.
getOffsetEntry()
Optional<uint64_t> llvm::DWARFListTableHeader::getOffsetEntry (uint32_t Index) const inline
Definition at line 119 of file DWARFListTable.h.
References llvm::Data, extract, and llvm::None.
Referenced by llvm::DWARFListTableBase< DWARFDebugRnglist >::getOffsetEntry().
getSectionName()
StringRef llvm::DWARFListTableHeader::getSectionName () const inline
Definition at line 102 of file DWARFListTable.h.
References AMDGPU::ElfNote::SectionName.
getVersion()
uint16_t llvm::DWARFListTableHeader::getVersion () const inline
Definition at line 101 of file DWARFListTable.h.
Referenced by dumpLoclistsSection().
length()
uint64_t DWARFListTableHeader::length () const
Returns the length of the table, including the length field, or 0 if the length has not been determined (e.g.
because the table has not yet been parsed, or there was a problem in parsing).
Definition at line 112 of file DWARFListTable.cpp.
References llvm::dwarf::getUnitLengthFieldByteSize().
Referenced by dumpLoclistsSection(), extract(), and llvm::DWARFListTableBase< DWARFDebugRnglist >::length().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFListTable.h
lib/DebugInfo/DWARF/DWARFListTable.cpp