LLVM: llvm::MachineMemOperand Class Reference
llvm::MachineMemOperand Class Reference
A description of a memory reference used in the backend.
#include "llvm/CodeGen/MachineMemOperand.h"
Public Types
enum Flags : uint16_t {
MONone = 0, MOLoad = 1u << 0, MOStore = 1u << 1, MOVolatile = 1u << 2,
MONonTemporal = 1u << 3, MODereferenceable = 1u << 4, MOInvariant = 1u << 5, MOTargetFlag1 = 1u << 6,
MOTargetFlag2 = 1u << 7, MOTargetFlag3 = 1u << 8
}
Flags values. These may be or'd together.
Public Member Functions
MachineMemOperand (MachinePointerInfo PtrInfo, Flags flags, uint64_t s, uint64_t a, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr, SyncScope::ID SSID=SyncScope::System, AtomicOrdering Ordering=AtomicOrdering::NotAtomic, AtomicOrdering FailureOrdering=AtomicOrdering::NotAtomic)
Construct a MachineMemOperand object with the specified PtrInfo, flags, size, and base alignment.
const MachinePointerInfo & getPointerInfo () const
const Value * getValue () const
Return the base address of the memory access.
const PseudoSourceValue * getPseudoValue () const
const void * getOpaqueValue () const
Flags getFlags () const
Return the raw flags of the source value,.
void setFlags (Flags f)
Bitwise OR the current flags with the given flags.
int64_t getOffset () const
For normal values, this is a byte offset added to the base address.
unsigned getAddrSpace () const
uint64_t getSize () const
Return the size in bytes of the memory reference.
uint64_t getSizeInBits () const
Return the size in bits of the memory reference.
uint64_t getAlignment () const
Return the minimum known alignment in bytes of the actual memory reference.
uint64_t getBaseAlignment () const
Return the minimum known alignment in bytes of the base address, without the offset.
AAMDNodes getAAInfo () const
Return the AA tags for the memory reference.
const MDNode * getRanges () const
Return the range tag for the memory reference.
SyncScope::ID getSyncScopeID () const
Returns the synchronization scope ID for this memory operation.
AtomicOrdering getOrdering () const
Return the atomic ordering requirements for this memory operation.
AtomicOrdering getFailureOrdering () const
For cmpxchg atomic operations, return the atomic ordering requirements when store does not occur.
bool isLoad () const
bool isStore () const
bool isVolatile () const
bool isNonTemporal () const
bool isDereferenceable () const
bool isInvariant () const
bool isAtomic () const
Returns true if this operation has an atomic ordering requirement of unordered or higher, false otherwise.
bool isUnordered () const
Returns true if this memory operation doesn't have any ordering constraints other than normal aliasing.
void refineAlignment (const MachineMemOperand *MMO)
Update this MachineMemOperand to reflect the alignment of MMO, if it has a greater alignment.
void setValue (const Value *NewSV)
Change the SourceValue for this MachineMemOperand.
void setValue (const PseudoSourceValue *NewSV)
void setOffset (int64_t NewOffset)
void Profile (FoldingSetNodeID &ID) const
Profile - Gather unique data for the object.
void print (raw_ostream &OS, ModuleSlotTracker &MST, SmallVectorImpl< StringRef > &SSNs, const LLVMContext &Context, const MachineFrameInfo *MFI, const TargetInstrInfo *TII) const
Support for operator<<.
Friends
bool operator== (const MachineMemOperand &LHS, const MachineMemOperand &RHS)
bool operator!= (const MachineMemOperand &LHS, const MachineMemOperand &RHS)
Detailed Description
A description of a memory reference used in the backend.
Instead of holding a StoreInst or LoadInst, this class holds the address Value of the reference along with a byte size and offset. This allows it to describe lowered loads and stores. Also, the special PseudoSourceValue objects can be used to represent loads and stores to memory locations that aren't explicit in the regular LLVM IR.
Definition at line 126 of file MachineMemOperand.h.
Member Enumeration Documentation
Flags
enum llvm::MachineMemOperand::Flags : uint16_t
Flags values. These may be or'd together.
Enumerator
MONone
MOLoad
The memory access reads data.
MOStore
The memory access writes data.
MOVolatile
The memory access is volatile.
MONonTemporal
The memory access is non-temporal.
MODereferenceable
The memory access is dereferenceable (i.e., doesn't trap).
MOInvariant
The memory access always returns the same value (or traps).
MOTargetFlag1
MOTargetFlag2
MOTargetFlag3
Definition at line 129 of file MachineMemOperand.h.
Constructor & Destructor Documentation
MachineMemOperand()
MachineMemOperand::MachineMemOperand (MachinePointerInfo PtrInfo, Flags flags, uint64_t s, uint64_t a, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr, SyncScope::ID SSID = SyncScope::System, AtomicOrdering Ordering = AtomicOrdering::NotAtomic, AtomicOrdering FailureOrdering = AtomicOrdering::NotAtomic)
Construct a MachineMemOperand object with the specified PtrInfo, flags, size, and base alignment.
For atomic operations the synchronization scope and atomic ordering requirements must also be specified. For cmpxchg atomic operations the atomic ordering requirements when store does not occur must also be specified.
Definition at line 1006 of file MachineOperand.cpp.
References assert(), llvm::PointerUnion< PTs >::get(), getBaseAlignment(), getFailureOrdering(), getOrdering(), getSyncScopeID(), llvm::Value::getType(), llvm::PointerUnion< PTs >::is(), isLoad(), llvm::PointerUnion< PTs >::isNull(), isStore(), and llvm::MachinePointerInfo::V.
Member Function Documentation
getAAInfo()
AAMDNodes llvm::MachineMemOperand::getAAInfo () const inline
Return the AA tags for the memory reference.
Definition at line 235 of file MachineMemOperand.h.
Referenced by llvm::MemSDNode::getAAInfo(), llvm::MachineFunction::getMachineMemOperand(), getStoreTarget(), getUnderlyingObjects(), llvm::MachineInstr::mayAlias(), llvm::VLIWPacketizerList::PacketizeMIs(), print(), and updateKillStatus().
getAddrSpace()
unsigned llvm::MachineMemOperand::getAddrSpace () const inline
Definition at line 218 of file MachineMemOperand.h.
References llvm::MachinePointerInfo::getAddrSpace().
Referenced by llvm::TargetLoweringBase::allowsMemoryAccess(), llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), llvm::InstructionSelector::executeMatchTable(), isConstant(), isScalarLoadLegal(), llvm::AMDGPUInstrInfo::isUniformMMO(), and print().
getAlignment()
uint64_t MachineMemOperand::getAlignment () const
Return the minimum known alignment in bytes of the actual memory reference.
getAlignment - Return the minimum known alignment in bytes of the actual memory reference.
Definition at line 1055 of file MachineOperand.cpp.
References getBaseAlignment(), getOffset(), and llvm::MinAlign().
Referenced by llvm::TargetLoweringBase::allowsMemoryAccess(), llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), llvm::InstructionSelector::executeMatchTable(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), llvm::MemSDNode::getAlignment(), isMemoryOp(), isScalarLoadLegal(), and lowerAlignmentHint().
getBaseAlignment()
uint64_t llvm::MachineMemOperand::getBaseAlignment () const inline
Return the minimum known alignment in bytes of the base address, without the offset.
Definition at line 232 of file MachineMemOperand.h.
Referenced by getAlignment(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemSDNode::getOriginalAlignment(), MachineMemOperand(), print(), Profile(), refineAlignment(), and llvm::CombinerHelper::tryCombineMemCpyFamily().
getFailureOrdering()
AtomicOrdering llvm::MachineMemOperand::getFailureOrdering () const inline
For cmpxchg atomic operations, return the atomic ordering requirements when store does not occur.
Definition at line 254 of file MachineMemOperand.h.
Referenced by llvm::MachineFunction::getMachineMemOperand(), MachineMemOperand(), print(), and llvm::LegalizerHelper::reduceLoadStoreWidth().
getFlags()
Flags llvm::MachineMemOperand::getFlags () const inline
Return the raw flags of the source value,.
See also
Flags.
Definition at line 209 of file MachineMemOperand.h.
Referenced by llvm::TargetLoweringBase::allowsMemoryAccess(), llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), buildMUBUFOffsetLoadStore(), combineLoad(), combineStore(), ConstantAddressBlock(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), ExtendUsesToFormExtLoad(), foldBitcastedFPLogic(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), getLoadExtOrTrunc(), llvm::MachineFunction::getMachineMemOperand(), GetPromotionOpcode(), getVectorCompareInfo(), isWordAligned(), lowerFP_TO_SINT_STORE(), LowerSTORE(), LowerStore(), LowerTruncateVectorStore(), numVectorEltsOrZero(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformTruncatingStoreCombine(), PerformVMOVRRDCombine(), print(), Profile(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), refineAlignment(), llvm::SparcTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), SkipLoadExtensionForVMULL(), splitStores(), splitStoreSplat(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), widenCtPop(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getOffset()
int64_t llvm::MachineMemOperand::getOffset () const inline
For normal values, this is a byte offset added to the base address.
For PseudoSourceValue::FPRel values, this is the FrameIndex number.
Definition at line 216 of file MachineMemOperand.h.
References llvm::MachinePointerInfo::Offset.
Referenced by llvm::SystemZInstrInfo::areMemAccessesTriviallyDisjoint(), combineKnownAdjacentMMOs(), llvm::PPCHazardRecognizer970::EmitInstruction(), getAlignment(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemSDNode::getSrcValueOffset(), getUnderlyingObjects(), llvm::MachineInstr::mayAlias(), llvm::VLIWPacketizerList::PacketizeMIs(), print(), Profile(), and updateKillStatus().
getOpaqueValue()
const void* llvm::MachineMemOperand::getOpaqueValue () const inline
Definition at line 206 of file MachineMemOperand.h.
References llvm::PointerUnion< PTs >::getOpaqueValue(), and llvm::MachinePointerInfo::V.
Referenced by Profile().
getOrdering()
AtomicOrdering llvm::MachineMemOperand::getOrdering () const inline
Return the atomic ordering requirements for this memory operation.
For cmpxchg atomic operations, return the atomic ordering requirements when store occurs.
Definition at line 248 of file MachineMemOperand.h.
Referenced by llvm::MachineFunction::getMachineMemOperand(), llvm::MemSDNode::getOrdering(), MachineMemOperand(), print(), llvm::LegalizerHelper::reduceLoadStoreWidth(), and ReplaceCMP_SWAP_128Results().
getPointerInfo()
const MachinePointerInfo& llvm::MachineMemOperand::getPointerInfo () const inline
Definition at line 191 of file MachineMemOperand.h.
Referenced by buildMUBUFOffsetLoadStore(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getLoad(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetMemSDNode(), llvm::SelectionDAG::getTruncStore(), isStackPtrRelative(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getPseudoValue()
const PseudoSourceValue* llvm::MachineMemOperand::getPseudoValue () const inline
Definition at line 202 of file MachineMemOperand.h.
References llvm::PointerUnion< PTs >::dyn_cast(), and llvm::MachinePointerInfo::V.
Referenced by llvm::SystemZInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineInstr::mayAlias(), false::IntervalSorter::operator()(), and print().
getRanges()
const MDNode* llvm::MachineMemOperand::getRanges () const inline
Return the range tag for the memory reference.
Definition at line 238 of file MachineMemOperand.h.
Referenced by llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemSDNode::getRanges(), and print().
getSize()
uint64_t llvm::MachineMemOperand::getSize () const inline
Return the size in bytes of the memory reference.
Definition at line 221 of file MachineMemOperand.h.
References Size.
Referenced by llvm::SystemZInstrInfo::areMemAccessesTriviallyDisjoint(), combineKnownAdjacentMMOs(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::PPCHazardRecognizer970::EmitInstruction(), llvm::InstructionSelector::executeMatchTable(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), getBufferStoreFormatOpcode(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::MachineFunction::getMachineMemOperand(), getStoreTarget(), getVectorSHLImm(), isScalarLoadLegal(), llvm::MachineInstr::mayAlias(), llvm::MemSDNode::MemSDNode(), llvm::VLIWPacketizerList::PacketizeMIs(), print(), refineAlignment(), truncateScalarIntegerArg(), and updateKillStatus().
getSizeInBits()
uint64_t llvm::MachineMemOperand::getSizeInBits () const inline
Return the size in bits of the memory reference.
Definition at line 224 of file MachineMemOperand.h.
References getAlignment().
Referenced by llvm::InstructionSelector::executeMatchTable(), and llvm::LegalizerHelper::lower().
getSyncScopeID()
SyncScope::ID llvm::MachineMemOperand::getSyncScopeID () const inline
Returns the synchronization scope ID for this memory operation.
Definition at line 241 of file MachineMemOperand.h.
Referenced by llvm::MachineFunction::getMachineMemOperand(), llvm::MemSDNode::getSyncScopeID(), MachineMemOperand(), and print().
getValue()
const Value* llvm::MachineMemOperand::getValue () const inline
Return the base address of the memory access.
This may either be a normal LLVM IR Value, or one of the special values used in CodeGen. Special values are those obtained via PseudoSourceValue::getFixedStack(int), PseudoSourceValue::getStack, and other PseudoSourceValue member functions which return objects which stand for frame/stack pointer relative references and other special references which are not representable in the high-level IR.
Definition at line 200 of file MachineMemOperand.h.
References llvm::PointerUnion< PTs >::dyn_cast(), and llvm::MachinePointerInfo::V.
Referenced by llvm::SystemZInstrInfo::areMemAccessesTriviallyDisjoint(), canLowerToLDG(), ConstantAddressBlock(), llvm::PPCHazardRecognizer970::EmitInstruction(), getCodeAddrSpace(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::MachineFunction::getMachineMemOperand(), getStoreTarget(), getUnderlyingObjects(), isConstant(), llvm::SITargetLowering::isMemOpHasNoClobberedMemOperand(), llvm::AVR::isProgramMemoryAccess(), llvm::AMDGPUInstrInfo::isUniformMMO(), llvm::MachineInstr::mayAlias(), memOpHasNoClobbered(), llvm::VLIWPacketizerList::PacketizeMIs(), print(), and updateKillStatus().
isAtomic()
bool llvm::MachineMemOperand::isAtomic () const inline
Returns true if this operation has an atomic ordering requirement of unordered or higher, false otherwise.
Definition at line 267 of file MachineMemOperand.h.
References llvm::NotAtomic.
Referenced by llvm::AtomicSDNode::AtomicSDNode(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), INITIALIZE_PASS(), llvm::MemSDNode::isAtomic(), isMemoryOp(), and isScalarLoadLegal().
isDereferenceable()
bool llvm::MachineMemOperand::isDereferenceable () const inline
Definition at line 262 of file MachineMemOperand.h.
Referenced by llvm::MemSDNode::MemSDNode(), and print().
isInvariant()
bool llvm::MachineMemOperand::isInvariant () const inline
Definition at line 263 of file MachineMemOperand.h.
Referenced by isScalarLoadLegal(), llvm::MemSDNode::MemSDNode(), and print().
isLoad()
bool llvm::MachineMemOperand::isLoad () const inline
Definition at line 258 of file MachineMemOperand.h.
Referenced by MachineMemOperand(), print(), and llvm::MemSDNode::readMem().
isNonTemporal()
bool llvm::MachineMemOperand::isNonTemporal () const inline
Definition at line 261 of file MachineMemOperand.h.
Referenced by llvm::MemSDNode::MemSDNode(), and print().
isStore()
bool llvm::MachineMemOperand::isStore () const inline
Definition at line 259 of file MachineMemOperand.h.
Referenced by MachineMemOperand(), print(), and llvm::MemSDNode::writeMem().
isUnordered()
bool llvm::MachineMemOperand::isUnordered () const inline
Returns true if this memory operation doesn't have any ordering constraints other than normal aliasing.
Volatile and (ordered) atomic memory operations can't be reordered.
Definition at line 272 of file MachineMemOperand.h.
References isVolatile(), llvm::NotAtomic, and llvm::Unordered.
Referenced by llvm::MachineInstr::hasOrderedMemoryRef(), and llvm::MemSDNode::isUnordered().
isVolatile()
bool llvm::MachineMemOperand::isVolatile () const inline
Definition at line 260 of file MachineMemOperand.h.
Referenced by llvm::SystemZInstrInfo::foldMemoryOperandImpl(), INITIALIZE_PASS(), isMemoryOp(), isScalarLoadLegal(), llvm::MemSDNode::MemSDNode(), print(), and llvm::CombinerHelper::tryCombineMemCpyFamily().
print()
void MachineMemOperand::print (raw_ostream & OS, ModuleSlotTracker & MST, SmallVectorImpl< StringRef > & SSNs, const LLVMContext & Context, const MachineFrameInfo * MFI, const TargetInstrInfo * TII) const
Support for operator<<.
Definition at line 1059 of file MachineOperand.cpp.
References assert(), llvm::PseudoSourceValue::ConstantPool, llvm::PseudoSourceValue::ExternalSymbolCallEntry, llvm::PseudoSourceValue::FixedStack, llvm::ISD::FrameIndex, getAAInfo(), getAddrSpace(), getBaseAlignment(), getFailureOrdering(), getFlags(), llvm::TargetInstrInfo::getMIRFormatter(), getOffset(), getOrdering(), getPseudoValue(), getRanges(), getSize(), getSyncScopeID(), getTargetMMOFlagName(), getValue(), llvm::PseudoSourceValue::GlobalValueCallEntry, llvm::PseudoSourceValue::GOT, isDereferenceable(), isInvariant(), isLoad(), isNonTemporal(), isStore(), isVolatile(), llvm::PseudoSourceValue::JumpTable, MOTargetFlag1, MOTargetFlag2, MOTargetFlag3, llvm::AAMDNodes::NoAlias, llvm::NotAtomic, llvm::Metadata::printAsOperand(), llvm::Value::printAsOperand(), llvm::MIRFormatter::printCustomPseudoSourceValue(), printFrameIndex(), llvm::MIRFormatter::printIRValue(), llvm::printLLVMNameWithoutPrefix(), llvm::MachineOperand::printOperandOffset(), printSyncScope(), llvm::AAMDNodes::Scope, llvm::PseudoSourceValue::Stack, llvm::AAMDNodes::TBAA, llvm::toIRString(), and llvm::MemoryLocation::UnknownSize.
Referenced by printMemOperand().
Profile()
void MachineMemOperand::Profile (FoldingSetNodeID & ID) const
Profile - Gather unique data for the object.
Definition at line 1030 of file MachineOperand.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::FoldingSetNodeID::AddPointer(), getBaseAlignment(), getFlags(), getOffset(), and getOpaqueValue().
refineAlignment()
void MachineMemOperand::refineAlignment (const MachineMemOperand * MMO)
Update this MachineMemOperand to reflect the alignment of MMO, if it has a greater alignment.
This must only be used when the new alignment applies to all users of this MachineMemOperand.
Definition at line 1038 of file MachineOperand.cpp.
References assert(), getBaseAlignment(), getFlags(), getSize(), and llvm::Log2_32().
Referenced by llvm::MemSDNode::refineAlignment().
setFlags()
void llvm::MachineMemOperand::setFlags (Flags f) inline
Bitwise OR the current flags with the given flags.
Definition at line 212 of file MachineMemOperand.h.
setOffset()
void llvm::MachineMemOperand::setOffset (int64_t NewOffset) inline
Definition at line 288 of file MachineMemOperand.h.
References Context, llvm::MachinePointerInfo::Offset, print(), and TII.
Referenced by combineKnownAdjacentMMOs(), and getBufferOffsetForMMO().
setValue() [1/2]
void llvm::MachineMemOperand::setValue (const Value * NewSV) inline
Change the SourceValue for this MachineMemOperand.
This should only be used when an object is being relocated and all references to it are being updated.
Definition at line 286 of file MachineMemOperand.h.
References llvm::MachinePointerInfo::V.
setValue() [2/2]
void llvm::MachineMemOperand::setValue (const PseudoSourceValue * NewSV) inline
Definition at line 287 of file MachineMemOperand.h.
References llvm::MachinePointerInfo::V.
Friends And Related Function Documentation
operator!=
bool operator!= (const MachineMemOperand & LHS, const MachineMemOperand & RHS) friend
Definition at line 314 of file MachineMemOperand.h.
operator==
bool operator== (const MachineMemOperand & LHS, const MachineMemOperand & RHS) friend
Definition at line 301 of file MachineMemOperand.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineMemOperand.h
lib/CodeGen/MachineOperand.cpp