LLVM: llvm::ConstantInt Class Reference
llvm::ConstantInt Class Reference final
This is the shared class of boolean and integer constants.
#include "llvm/IR/Constants.h"
Public Member Functions
ConstantInt (const ConstantInt &)=delete
const APInt & getValue () const
Return the constant as an APInt value reference.
unsigned getBitWidth () const
getBitWidth - Return the bitwidth of this constant.
uint64_t getZExtValue () const
Return the constant as a 64-bit unsigned integer value after it has been zero extended as appropriate for the type of this constant.
int64_t getSExtValue () const
Return the constant as a 64-bit integer value after it has been sign extended as appropriate for the type of this constant.
bool equalsInt (uint64_t V) const
A helper method that can be used to determine if the constant contained within is equal to a constant.
IntegerType * getType () const
getType - Specialize the getType() method to always return an IntegerType, which reduces the amount of casting needed in parts of the compiler.
bool isNegative () const
bool isZero () const
This is just a convenience method to make client code smaller for a common code.
bool isOne () const
This is just a convenience method to make client code smaller for a common case.
bool isMinusOne () const
This function will return true iff every bit in this constant is set to true.
bool isMaxValue (bool isSigned) const
This function will return true iff this constant represents the largest value that may be represented by the constant's type.
bool isMinValue (bool isSigned) const
This function will return true iff this constant represents the smallest value that may be represented by this constant's type.
bool uge (uint64_t Num) const
This function will return true iff this constant represents a value with active bits bigger than 64 bits or a value greater than the given uint64_t value.
uint64_t getLimitedValue (uint64_t Limit=~0ULL) const
getLimitedValue - If the value is smaller than the specified limit, return it, otherwise return the limit value.
Public Member Functions inherited from llvm::ConstantData
ConstantData (const ConstantData &)=delete
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefElement () const
Return true if this is a vector constant that includes any undefined elements.
bool containsConstantExpression () const
Return true if this is a vector constant that includes any constant expressions.
bool canTrap () const
Return true if evaluation of this constant could trap.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry.
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
MaybeAlign getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static ConstantInt * getTrue (LLVMContext &Context)
static ConstantInt * getFalse (LLVMContext &Context)
static Constant * getTrue (Type *Ty)
static Constant * getFalse (Type *Ty)
static Constant * get (Type *Ty, uint64_t V, bool isSigned=false)
If Ty is a vector type, return a Constant with a splat of the given value.
static ConstantInt * get (IntegerType *Ty, uint64_t V, bool isSigned=false)
Return a ConstantInt with the specified integer value for the specified type.
static ConstantInt * getSigned (IntegerType *Ty, int64_t V)
Return a ConstantInt with the specified value for the specified type.
static Constant * getSigned (Type *Ty, int64_t V)
static ConstantInt * get (LLVMContext &Context, const APInt &V)
Return a ConstantInt with the specified value and an implied Type.
static ConstantInt * get (IntegerType *Ty, StringRef Str, uint8_t radix)
Return a ConstantInt constructed from the string strStart with the given radix.
static Constant * get (Type *Ty, const APInt &V)
If Ty is a vector type, return a Constant with a splat of the given value.
static bool isValueValidForType (Type *Ty, uint64_t V)
This static method returns true if the type Ty is big enough to represent the value V.
static bool isValueValidForType (Type *Ty, int64_t V)
static bool classof (const Value *V)
Methods to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::ConstantData
static bool classof (const Value *V)
Methods to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class Constant
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::ConstantData
ConstantData (Type *Ty, ValueTy VT)
void * operator new (size_t s)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This is the shared class of boolean and integer constants.
This class represents both boolean and integral constants. Class for constant integers.
Definition at line 83 of file Constants.h.
Constructor & Destructor Documentation
ConstantInt()
llvm::ConstantInt::ConstantInt (const ConstantInt &) delete
Member Function Documentation
classof()
static bool llvm::ConstantInt::classof (const Value * V) inline static
Methods to support type inquiry through isa, cast, and dyn_cast.
Definition at line 255 of file Constants.h.
References llvm::Value::getValueID().
equalsInt()
bool llvm::ConstantInt::equalsInt (uint64_t V) const inline
A helper method that can be used to determine if the constant contained within is equal to a constant.
This only works for very small values, because this is all that can be represented with all types. Determine if this constant's value is same as an unsigned char.
Definition at line 164 of file Constants.h.
Referenced by llvm::InstructionSelector::executeMatchTable(), and getVectorType().
get() [1/5]
Constant * ConstantInt::get (Type * Ty, uint64_t V, bool isSigned = false) static
If Ty is a vector type, return a Constant with a splat of the given value.
Otherwise return a ConstantInt for the given value.
Definition at line 704 of file Constants.cpp.
References C, llvm::Type::getScalarType(), and llvm::ConstantVector::getSplat().
Referenced by AddCalls(), llvm::Module::addModuleFlag(), llvm::AddOne(), llvm::GlobalObject::addTypeMetadata(), llvm::GlobalObject::addVCallVisibilityMetadata(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), annotateNonNullAndDereferenceable(), llvm::annotateValueSite(), AreSequentialAccesses(), BitCastConstantVector(), bitTrackingDCE(), llvm::MachineIRBuilder::buildConstant(), calcArraySize(), calculateOffsetDiff(), llvm::canConstantFoldCallTo(), CanGenerateTest(), canonicalizeSaturatedAdd(), Cleanup(), CloneLoopBlocks(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), collectInsertionElements(), collectShuffleElements(), collectSingleShuffleElements(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), llvm::ShuffleVectorInst::commute(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::ComputeMultiple(), computePointerICmp(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), ConnectProlog(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), ConvertShiftToMul(), ConvertToSInt(), llvm::GlobalObject::copyMetadata(), llvm::copyNonnullMetadata(), llvm::SanitizerStatReport::create(), llvm::createAArch64StackTaggingPass(), createAccessTag(), llvm::IRBuilder< TargetFolder >::CreateAlignmentAssumption(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::IRBuilder< TargetFolder >::CreateAnd(), createAndInstr(), llvm::IRBuilder< TargetFolder >::CreateAShr(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MDBuilder::createBranchWeights(), llvm::MDBuilder::createCallbackEncoding(), llvm::IRBuilder< TargetFolder >::CreateConstGEP1_32(), llvm::IRBuilder< TargetFolder >::CreateConstGEP1_64(), llvm::IRBuilder< TargetFolder >::CreateConstGEP2_32(), llvm::IRBuilder< TargetFolder >::CreateConstGEP2_64(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< TargetFolder >::CreateConstInBoundsGEP2_64(), createFFSIntrinsic(), llvm::MDBuilder::createFunctionEntryCount(), llvm::IRBuilder< TargetFolder >::CreateGlobalStringPtr(), createHWLoopAnalysis(), llvm::DIBuilder::createInheritance(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::orc::createIRTypedAddress(), llvm::IRBuilder< TargetFolder >::CreateLShr(), createMalloc(), createMaskedBitTest(), createMaskInstrs(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), llvm::MDBuilder::createMisExpect(), llvm::IRBuilder< TargetFolder >::CreateOr(), llvm::OpenMPIRBuilder::CreateParallel(), createPowWithIntegerExponent(), llvm::IRBuilder< TargetFolder >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< TargetFolder >::CreatePreserveStructAccessIndex(), createPrivateGlobalForSourceLoc(), llvm::MDBuilder::createRange(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), llvm::IRBuilder< TargetFolder >::CreateShl(), createStringMetadata(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::IRBuilder< TargetFolder >::CreateVectorSplat(), llvm::createXCoreISelDag(), llvm::IRBuilder< TargetFolder >::CreateXor(), decomposeBitTestICmp(), decomposeSimpleLinearExpr(), despeculateCountZeros(), DisableAllLoopOptsOnLoop(), doPromotion(), dropRedundantMaskingOfLeftShiftInput(), eliminateDeadStores(), llvm::orc::IRSpeculationLayer::emit(), llvm::emitFWrite(), llvm::EmitGEPOffset(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), emitPostSt(), llvm::emitStrChr(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), evaluateBitcastFromPtr(), EvaluateConstantChrecAtConstant(), evaluateGEPOffsetExpression(), evaluateInDifferentElementOrder(), llvm::VPlan::execute(), ExpandBVWithShuffles(), ExtractConstantBytes(), FactorOutConstant(), llvm::FastISel::fastEmit_ri_(), llvm::CodeExtractor::findInputsOutputs(), llvm::SanitizerStatReport::finish(), llvm::InnerLoopVectorizer::fixupIVUsers(), foldAndOrOfEqualityCmpsWithConstants(), foldAnyOrAllBitsSet(), FoldBitCast(), foldConstantInsEltIntoShuffle(), foldCtpop(), foldCttzCtlz(), foldICmpBitCast(), foldICmpShlOne(), foldICmpWithMinMax(), foldICmpWithTruncSignExtendedVal(), foldIdentityPaddedShuffles(), foldInsEltIntoIdentityShuffle(), foldInsSequenceIntoSplat(), foldIsPowerOf2(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldNoWrapAdd(), foldOperationIntoPhiValue(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedLogic(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), foldUnsignedUnderflowCheck(), FunctionNumber(), generatePoisonChecks(), generatePoisonChecksForBinOp(), getAISize(), llvm::ConstantExpr::getAlignOf(), getAllocaSizeInBytes(), llvm::Constant::getAllOnesValue(), getAlternateBinop(), llvm::IRTranslator::getAnalysisUsage(), GetAnyNonZeroConstInt(), llvm::AAValueConstantRange::getAssumedConstantInt(), llvm::IRPosition::getAttrs(), llvm::ConstantExpr::getBinOpIdentity(), getBinOpsForFactorization(), getBoundsCheckCond(), getComparePred(), llvm::LazyValueInfo::getConstant(), llvm::ScalarEvolution::getConstant(), llvm::SelectionDAG::getConstant(), GetConstantInt(), llvm::LazyValueInfo::getConstantOnEdge(), getContiguousRangeOfSetBits(), getEdgeValueLocal(), llvm::ConstantDataSequential::getElementAsConstant(), getFalse(), getFCmpValue(), llvm::getFlippedStrictnessPredicateAndConstant(), getFoldedAlignOf(), getFoldedSizeOf(), getImplicitScaleFactor(), llvm::coro::Shape::getIndex(), llvm::IRBuilderBase::getInt(), llvm::IRBuilderBase::getInt1(), llvm::IRBuilderBase::getInt16(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt8(), llvm::Constant::getIntegerValue(), llvm::IRBuilderBase::getIntN(), getKeyValMD(), getLogBase2(), getMaxBackedgeTakenCount(), AAValueConstantRangeImpl::getMDNodeForConstantRange(), llvm::VNCoercion::getMemInstValueForLoadHelper(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), getMulHu(), getNegativeIsTrueBoolVec(), llvm::Constant::getNullValue(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getOffsetFromIndices(), llvm::ConstantExpr::getOffsetOf(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::getPredForICmpCode(), getRangeForAffineARHelper(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), llvm::FastISel::getRegForValue(), GetRMWLibcall(), llvm::getSafeVectorConstantForBinop(), llvm::ConstantExpr::getSizeOf(), llvm::InstrProfIncrementInst::getStep(), llvm::InnerLoopVectorizer::getStepVector(), llvm::VNCoercion::getStoreValueForLoadHelper(), getTrue(), getUnconditionalBrDisp(), getVectorType(), GlobalWasGeneratedByCompiler(), hasOnlyOneNonZeroIndex(), hasPositiveOperands(), hasSameExtUse(), llvm::OpenMPIRBuilder::initialize(), INITIALIZE_PASS(), llvm::InlineFunction(), insertCall(), insertLifetimeMarkersSurroundingCall(), insertSinCosCall(), insertSpills(), instrumentMaskedLoadOrStore(), isAtomic(), llvm::isBytewiseValue(), isDINode(), isDivZero(), isGEPFoldable(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), IsInterestingCmp(), isKnownTypeIdMember(), IsNonLocalValue(), isOnlyReachableViaThisEdge(), isPromotedInstructionLegal(), isPromotedResultSafe(), isReportingError(), isSelect01(), IsSmallObject(), isSupportedGuardInstruction(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LibCallSimplifier::LibCallSimplifier(), LLVMConstInt(), LLVMConstIntOfArbitraryPrecision(), LLVMConstIntOfString(), LLVMConstIntOfStringAndSize(), llvm::XCoreInstrInfo::loadImmediate(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBSWAP(), LowerBUILD_VECTORAsVariablePermute(), LowerCTLZ(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::lowerObjectSizeCall(), lowerUINT_TO_FP_vec(), llvm::fuzzerop::makeConstantsWithType(), llvm::coro::LowererBase::makeSubFnCall(), mapBinOpcode(), MarkBlocksLiveIn(), MatchBinaryOp(), matchesOr(), matchUAddWithOverflowConstantEdgeCases(), mayUsePostIncMode(), llvm::MergeBasicBlockIntoOnlyPred(), MulWillOverflow(), needsRuntimeRegistrationOfSectionRange(), optimizeMemCmpConstantSize(), PerformHeapAllocSRoA(), performMaskedAtomicOp(), PickMostRelevantLoop(), postDominates(), processAShr(), processCmp(), processSExt(), processUGT_ADDCST_ADD(), PushArgMD(), ReduceSwitchRange(), replaceAllUsesOfWithIn(), llvm::InstCombiner::replacedSelectWithOperand(), replaceExtractElements(), replaceFrameSize(), replaceGEPIdxWithZero(), llvm::ARMTargetLowering::ReplaceNodeResults(), ReplaceUsesOfWith(), RetagMask(), reuseTableCompare(), llvm::CGProfilePass::run(), llvm::LoopDataPrefetchPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::InstCombiner::run(), SegmentOffset(), selectJumpTableArmEncoding(), llvm::LoopVectorizeHints::setAlreadyVectorized(), shouldKeepInEntry(), shouldMergeGEPs(), ShrinkDemandedConstant(), SimplifyBSwap(), SimplifyCondBranchToCondBranch(), simplifyDivRem(), SimplifyFCmpInst(), SimplifyGEPInst(), SimplifyICmpInst(), llvm::SimplifyInstruction(), SimplifyRelativeLoad(), simplifyX86extrq(), simplifyX86immShift(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), splitGlobal(), splitMergedValStore(), stripAndComputeConstantOffsets(), llvm::SubOne(), SwitchToLookupTable(), tryMergeRange(), tryToOptimizeStoreOfMallocToGlobal(), tryToShorten(), TryToShrinkGlobalToBoolean(), tryUnmergingGEPsAcrossIndirectBr(), TurnSwitchRangeIntoICmp(), TypeSizeToSizeIndex(), unifyBitWidth(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::UnrollRuntimeLoopRemainder(), updateOperand(), llvm::CallInst::updateProfWeight(), llvm::UpgradeIntrinsicCall(), llvm::UpgradeModuleFlags(), upgradePMULDQ(), validExtractValueIndex(), validInsertValueIndex(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::InstCombiner::visitAdd(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitAllocSite(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitUDiv(), llvm::InstCombiner::visitURem(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::InnerLoopVectorizer::widenPHIInstruction(), llvm::LegalizerHelper::widenScalar(), and llvm::BasicBlock::~BasicBlock().
get() [2/5]
ConstantInt * ConstantInt::get (IntegerType * Ty, uint64_t V, bool isSigned = false) static
Return a ConstantInt with the specified integer value for the specified type.
If the type is wider than 64 bits, the value will be zero-extended to fit the type, unless isSigned is true, in which case the value will be interpreted as a 64-bit signed integer and sign-extended to fit the type. Get a ConstantInt for a specific value.
Definition at line 714 of file Constants.cpp.
References llvm::IntegerType::getBitWidth(), and llvm::Type::getContext().
get() [3/5]
ConstantInt * ConstantInt::get (LLVMContext & Context, const APInt & V) static
Return a ConstantInt with the specified value and an implied Type.
The type is the integer type that corresponds to the bit width of the value.
Definition at line 691 of file Constants.cpp.
References assert(), llvm::IntegerType::get(), llvm::APInt::getBitWidth(), llvm::LLVMContextImpl::IntConstants, and llvm::LLVMContext::pImpl.
get() [4/5]
ConstantInt * ConstantInt::get (IntegerType * Ty, StringRef Str, uint8_t radix) static
Return a ConstantInt constructed from the string strStart with the given radix.
Definition at line 738 of file Constants.cpp.
References llvm::IntegerType::getBitWidth(), llvm::Type::getContext(), and llvm_unreachable.
get() [5/5]
Constant * ConstantInt::get (Type * Ty, const APInt & V) static
If Ty is a vector type, return a Constant with a splat of the given value.
Otherwise return a ConstantInt for the given value.
Definition at line 726 of file Constants.cpp.
References assert(), C, llvm::Type::getContext(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and getType().
getBitWidth()
unsigned llvm::ConstantInt::getBitWidth () const inline
getBitWidth - Return the bitwidth of this constant.
Definition at line 142 of file Constants.h.
References llvm::APInt::getBitWidth().
Referenced by aliasSameBasePointerGEPs(), llvm::MachineIRBuilder::buildConstant(), emitGlobalConstantLargeInt(), foldICmpWithMinMax(), llvm::SelectionDAG::getConstant(), getImmedFromMO(), handleBrSelExpect(), hasOnlyOneNonZeroIndex(), isAddFoldable(), isKnownNonZeroFromAssume(), isPromotedInstructionLegal(), llvm::TargetLowering::LowerAsmOperandForConstraint(), matchesOr(), processUGT_ADDCST_ADD(), and processUMulZExtIdiom().
getFalse() [1/2]
ConstantInt * ConstantInt::getFalse (LLVMContext & Context) static
Definition at line 667 of file Constants.cpp.
References get(), llvm::Type::getInt1Ty(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TheFalseVal.
Referenced by allPredecessorsComeFromSameSource(), canonicalizeSaturatedAdd(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), detectShiftUntilZeroIdiom(), llvm::SCEVExpander::expandWrapPredicate(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), forceIndeterminateEdge(), FunctionNumber(), getBoundsCheckCond(), llvm::ValueLatticeElement::getCompare(), getConstantAt(), getFalse(), getFalse(), llvm::IRBuilderBase::getFalse(), getFirstNonAllocaInTheEntryBlock(), getPoisonFor(), isKnownTypeIdMember(), isOnlyReachableViaThisEdge(), isSupportedGuardInstruction(), lowerIsConstantIntrinsic(), OptimizeGlobalAddressOfMalloc(), performMaskedAtomicOp(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processOverflowIntrinsic(), processUGT_ADDCST_ADD(), removeDoneExport(), llvm::InstCombiner::replacedSelectWithOperand(), ReplaceUsesOfWith(), reuseTableCompare(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::IRCEPass::run(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SimplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), SimplifyIndirectBrOnSelect(), simplifyUnsignedRangeCheck(), TryToShrinkGlobalToBoolean(), turnGuardIntoBranch(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::InstCombiner::visitBranchInst(), and willNotOverflow().
getFalse() [2/2]
Constant * ConstantInt::getFalse (Type * Ty) static
Definition at line 682 of file Constants.cpp.
References assert(), llvm::Type::getContext(), getFalse(), llvm::ConstantVector::getSplat(), and llvm::Type::isIntOrIntVectorTy().
getLimitedValue()
uint64_t llvm::ConstantInt::getLimitedValue (uint64_t Limit = ~0ULL) const inline
getLimitedValue - If the value is smaller than the specified limit, return it, otherwise return the limit value.
This causes the value to saturate to the limit.
Returns
the min of the value of the constant and the specified value Get the constant's value with a saturation limit
Definition at line 250 of file Constants.h.
References llvm::APInt::getLimitedValue().
Referenced by canEvaluateShifted(), canEvaluateShuffled(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), foldICmpWithMinMax(), llvm::ConstantSDNode::getLimitedValue(), getNegativeIsTrueBoolVec(), llvm::Value::getPointerAlignment(), llvm::Value::getPointerDereferenceableBytes(), hasSameExtUse(), simplifyNeonVld1(), and AllocaSlices::SliceBuilder::SliceBuilder().
getSExtValue()
int64_t llvm::ConstantInt::getSExtValue () const inline
Return the constant as a 64-bit integer value after it has been sign extended as appropriate for the type of this constant.
Note that this method can assert if the value does not fit in 64 bits. Return the sign extended value.
Definition at line 156 of file Constants.h.
References llvm::APInt::getSExtValue().
Referenced by annotateNonNullAndDereferenceable(), llvm::BTFDebug::BTFDebug(), canFoldIVIncExpr(), CC_MipsO32_FP64(), evaluateGEPOffsetExpression(), getComparePred(), llvm::InductionDescriptor::getConsecutiveDirection(), getImmedFromMO(), getOffsetFromIndex(), llvm::getOptionalIntLoopAttribute(), llvm::ConstantSDNode::getSExtValue(), llvm::IndexedReference::hasSpacialReuse(), llvm::IndexedReference::hasTemporalReuse(), hasUsesOutsideLoop(), hasVectorBeenPadded(), INITIALIZE_PASS(), isAddFoldable(), isConstant(), isDINode(), isIndexInRangeOfArrayType(), llvm::InductionDescriptor::isInductionPHI(), isMulPowOf2(), isPromotedInstructionLegal(), isStackPtrRelative(), llvm::log2(), matchesOr(), optimizeMemCmpConstantSize(), llvm::salvageDebugInfoImpl(), SimplifyRelativeLoad(), and X86ChooseCmpImmediateOpcode().
getSigned() [1/2]
ConstantInt * ConstantInt::getSigned (IntegerType * Ty, int64_t V) static
Return a ConstantInt with the specified value for the specified type.
The value V will be canonicalized to a an unsigned APInt. Accessing it with either getSExtValue() or getZExtValue() will yield a correctly sized and signed value for the type Ty. Get a ConstantInt for a specific signed value.
Definition at line 718 of file Constants.cpp.
Referenced by llvm::SCEVExpander::expandCodeFor(), generateUnsignedDivisionCode(), getComparePred(), getSignedIntOrFpConstant(), INITIALIZE_PASS(), insertLifetimeMarkersSurroundingCall(), mayUsePostIncMode(), llvm::InstCombiner::visitLShr(), and llvm::InstCombiner::visitOr().
getSigned() [2/2]
Constant * ConstantInt::getSigned (Type * Ty, int64_t V) static
Definition at line 722 of file Constants.cpp.
getTrue() [1/2]
ConstantInt * ConstantInt::getTrue (LLVMContext & Context) static
Definition at line 660 of file Constants.cpp.
References get(), llvm::Type::getInt1Ty(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TheTrueVal.
Referenced by AddCalls(), llvm::LoopAccessInfo::addRuntimeChecks(), allPredecessorsComeFromSameSource(), assertBranchOrSelectConditionHoisted(), llvm::canConstantFoldCallTo(), canonicalizeSaturatedAdd(), CloneLoop(), computeKnownBitsFromOperator(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCompareInstruction(), llvm::InstCombiner::CreateNonTerminatorUnreachable(), despeculateCountZeros(), detectShiftUntilZeroIdiom(), EqualityPropUnSafe(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), FunctionNumber(), llvm::ValueLatticeElement::getCompare(), getConstantAt(), getTrue(), getTrue(), llvm::IRBuilderBase::getTrue(), isKnownTypeIdMember(), isOnlyReachableViaThisEdge(), isSupportedGuardInstruction(), lowerIsConstantIntrinsic(), lowerSubFn(), lowerWidenableCondition(), MarkBlocksLiveIn(), OptimizeGlobalAddressOfMalloc(), llvm::parseWidenableBranch(), performMaskedAtomicOp(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processUGT_ADDCST_ADD(), llvm::InstCombiner::replacedSelectWithOperand(), ReplaceUsesOfWith(), reuseTableCompare(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::IRCEPass::run(), llvm::SelectionDAGBuilder::ShouldEmitAsBranches(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), SimplifyICmpInst(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), SimplifyIndirectBrOnSelect(), simplifyUnsignedRangeCheck(), TurnSwitchRangeIntoICmp(), unifyReturnBlockSet(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), and llvm::InstCombiner::visitCallInst().
getTrue() [2/2]
Constant * ConstantInt::getTrue (Type * Ty) static
Definition at line 674 of file Constants.cpp.
References assert(), llvm::Type::getContext(), llvm::ConstantVector::getSplat(), getTrue(), and llvm::Type::isIntOrIntVectorTy().
getType()
IntegerType* llvm::ConstantInt::getType () const inline
getType - Specialize the getType() method to always return an IntegerType, which reduces the amount of casting needed in parts of the compiler.
Definition at line 171 of file Constants.h.
References llvm::Value::getType().
Referenced by calculateOffsetDiff(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::createMemCpyLoopKnownSize(), emitGlobalConstantLargeInt(), EvaluateConstantChrecAtConstant(), FoldCondBranchOnPHI(), foldICmpWithMinMax(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldUnsignedUnderflowCheck(), get(), GetConstantInt(), getNegativeIsTrueBoolVec(), llvm::SCEVConstant::getType(), hasZeroSignBit(), INITIALIZE_PASS(), isContiguous(), llvm::InductionDescriptor::isInductionPHI(), isSafeAndProfitableToSpeculateAroundPHI(), ShrinkDemandedConstant(), SwitchToLookupTable(), tryMergeRange(), tryUnmergingGEPsAcrossIndirectBr(), updateOperand(), and updatePredecessorProfileMetadata().
getValue()
const APInt& llvm::ConstantInt::getValue () const inline
Return the constant as an APInt value reference.
This allows clients to obtain a full-precision copy of the value. Return the constant's value.
Definition at line 137 of file Constants.h.
Referenced by llvm::GEPOperator::accumulateConstantOffset(), llvm::DwarfUnit::addConstantValue(), aliasSameBasePointerGEPs(), annotateAnyAllocSite(), calcArraySize(), calculateOffsetDiff(), canEvaluateShifted(), checkMDProf(), llvm::FunctionComparator::cmpMem(), llvm::computeKnownBitsFromRangeMetadata(), llvm::ComputeMultiple(), llvm::GISelKnownBits::computeNumSignBits(), computePointerICmp(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), ConstantIntSortPredicate(), llvm::BitTracker::MachineEvaluator::eIMM(), emitDebugValueComment(), emitGlobalConstantLargeInt(), llvm::Evaluator::EvaluateBlock(), EvaluateConstantChrecAtConstant(), ExtractConstantBytes(), foldICmpWithMinMax(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldUnsignedUnderflowCheck(), GenerateSignBits(), llvm::SCEVConstant::getAPInt(), llvm::ConstantSDNode::getAPIntValue(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), getBoundsCheckCond(), GetBranchWeights(), llvm::SelectionDAG::getConstant(), getConstantTripCount(), llvm::getConstantVRegValWithLookThrough(), llvm::Function::getEntryCount(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), getMaskedICmpType(), llvm::ARMTTIImpl::getMemcpyCost(), llvm::MDNode::getMostGenericRange(), getMulHu(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getParentPad(), getPredicateResult(), getRangeForAffineARHelper(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), getValueFromICmpCondition(), getVectorType(), handlePhiDef(), hasUndefContents(), llvm::SwitchInstProfUpdateWrapper::init(), AAValueConstantRangeImpl::isBetterRange(), isContiguous(), isImpliedCondMatchingImmOperands(), isIndexInRangeOfArrayType(), isKnownNonZeroFromAssume(), isLoopIncrement(), llvm::AArch64TargetLowering::isMaskAndCmp0FoldingBeneficial(), isObjectSizeLessThanOrEq(), isPromotedInstructionLegal(), isSafeAndProfitableToSpeculateAroundPHI(), isStackPtrRelative(), isSupportedGuardInstruction(), llvm::HexagonTargetLowering::LowerBITCAST(), matchesOr(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarShift(), false::next_type(), processAnd(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), rangeMetadataExcludesValue(), setBranchWeights(), ShrinkDemandedConstant(), SimplifyBSwap(), simplifyDiv(), simplifyX86extrq(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::SwitchCG::sortAndRangeify(), SwitchToLookupTable(), tryMergeRange(), tryUnmergingGEPsAcrossIndirectBr(), UpdatePDTWorklist(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::ObjectSizeOffsetVisitor::visitCallSite(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), and llvm::LegalizerHelper::widenScalar().
getZExtValue()
uint64_t llvm::ConstantInt::getZExtValue () const inline
Return the constant as a 64-bit unsigned integer value after it has been zero extended as appropriate for the type of this constant.
Note that this method can assert if the value does not fit in 64 bits. Return the zero extended value.
Definition at line 148 of file Constants.h.
References llvm::APInt::getZExtValue().
Referenced by llvm::GEPOperator::accumulateConstantOffset(), aliasSameBasePointerGEPs(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), annotateAnyAllocSite(), annotateNonNullAndDereferenceable(), BatchCommitValueTo(), llvm::cacheAnnotationFromMD(), CC_MipsO32_FP64(), llvm::misexpect::checkFrontendInstrumentation(), collectInsertionElements(), computeBytesPoppedByCalleeForSRet(), llvm::ComputeMultiple(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::createMemCpyLoopKnownSize(), llvm::NVPTXAsmPrinter::doFinalization(), evaluateGEPOffsetExpression(), EvaluateStoreInto(), ExpandBVWithShuffles(), findGlobalCtors(), FixedPointIntrinsicToOpcode(), FoldCondBranchOnPHI(), foldVecTruncToExtElt(), getAllocaSizeInBytes(), llvm::IRPosition::getAttrs(), llvm::AMDGPU::getBaseWithConstantOffset(), getCompareCC(), getComparePred(), getConstantTripCount(), GetCtorAndDtorPriority(), llvm::DOTGraphTraits< const Function * >::getEdgeAttributes(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::ScalarEvolution::getGEPExpr(), getImmedFromMO(), getImplicitScaleFactor(), getLeaOP(), getMemCmpLoad(), llvm::MDNode::getMostGenericAlignmentOrDereferenceable(), getOffsetFromIndex(), getOrInsertValueProfilingCall(), getRangeForAffineARHelper(), getShiftTypeForInst(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::GCNTTIImpl::getTgtMemIntrinsic(), llvm::GCNTTIImpl::getUserCost(), llvm::getValueProfDataFromInst(), getVarName(), getVectorSHLImm(), llvm::ConstantSDNode::getZExtValue(), handleBrSelExpect(), hasUndefContents(), hasZeroSignBit(), llvm::CompositeType::indexValid(), INITIALIZE_PASS(), insertBoundsCheck(), isGEPKnownNonNull(), isMulPowOf2(), isReportingError(), isSafeSROAGEP(), matchPairwiseReduction(), matchVectorSplittingReduction(), mayUsePostIncMode(), moveUp(), needsRuntimeRegistrationOfSectionRange(), OptimizeGlobalAddressOfMalloc(), llvm::FunctionLoweringInfo::set(), shouldUseAndMask(), ShrinkDemandedConstant(), SimplifyShuffleVectorInst(), AllocaSlices::SliceBuilder::SliceBuilder(), TryToShrinkGlobalToBoolean(), UpdatePDTWorklist(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), llvm::Interpreter::visitAllocaInst(), and llvm::InstCombiner::visitTrunc().
isMaxValue()
bool llvm::ConstantInt::isMaxValue (bool isSigned) const inline
This function will return true iff this constant represents the largest value that may be represented by the constant's type.
Returns
true iff this is the largest value that may be represented by this type. Determine if the value is maximal.
Definition at line 217 of file Constants.h.
References llvm::APInt::isMaxSignedValue(), and llvm::APInt::isMaxValue().
isMinusOne()
bool llvm::ConstantInt::isMinusOne () const inline
This function will return true iff every bit in this constant is set to true.
Returns
true iff this constant's bits are all set to true. Determine if the value is all ones.
Definition at line 208 of file Constants.h.
References llvm::APInt::isAllOnesValue().
Referenced by detectPopcountIdiom(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::Evaluator::EvaluateBlock(), llvm::InductionDescriptor::getConsecutiveDirection(), llvm::ConstantSDNode::isAllOnesValue(), isOnlyReachableViaThisEdge(), and llvm::InstCombiner::simplifyRangeCheck().
isMinValue()
bool llvm::ConstantInt::isMinValue (bool isSigned) const inline
This function will return true iff this constant represents the smallest value that may be represented by this constant's type.
Returns
true if this is the smallest value that may be represented by this type. Determine if the value is minimal.
Definition at line 229 of file Constants.h.
References llvm::APInt::isMinSignedValue(), and llvm::APInt::isMinValue().
Referenced by foldUnsignedUnderflowCheck().
isNegative()
bool llvm::ConstantInt::isNegative () const inline
Definition at line 187 of file Constants.h.
References llvm::APInt::isNegative().
Referenced by GenerateSignBits(), getMinFromExprs(), and populateDependencyMatrix().
isOne()
bool llvm::ConstantInt::isOne () const inline
This is just a convenience method to make client code smaller for a common case.
It also correctly performs the comparison without the potential for an assertion from getZExtValue(). Determine if the value is one.
Definition at line 200 of file Constants.h.
References llvm::APInt::isOneValue().
Referenced by llvm::ConstantFoldCastInstruction(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), getCompareCC(), llvm::InductionDescriptor::getConsecutiveDirection(), llvm::GlobalsMetadata::GlobalsMetadata(), llvm::Loop::isCanonical(), IsConstantOne(), llvm::ConstantSDNode::isOne(), llvm::LoopVectorizationLegality::isUniform(), processSelect(), and updatePredecessorProfileMetadata().
isValueValidForType() [1/2]
bool ConstantInt::isValueValidForType (Type * Ty, uint64_t V) static
This static method returns true if the type Ty is big enough to represent the value V.
This can be used to avoid having the get method assert when V is larger than Ty can represent. Note that there are two versions of this method, one for unsigned and one for signed integers. Although ConstantInt canonicalizes everything to an unsigned integer, the signed version avoids callers having to convert a signed quantity to the appropriate unsigned type before calling the method.
Returns
true if V is a valid value for type Ty Determine if the value is in range for the given type.
Definition at line 1349 of file Constants.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::isIntegerTy(), and llvm::isUIntN().
Referenced by GetCtorAndDtorPriority(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), and mayUsePostIncMode().
isValueValidForType() [2/2]
bool ConstantInt::isValueValidForType (Type * Ty, int64_t V) static
Definition at line 1356 of file Constants.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::isIntegerTy(), and llvm::isIntN().
isZero()
bool llvm::ConstantInt::isZero () const inline
This is just a convenience method to make client code smaller for a common code.
It also correctly performs the comparison without the potential for an assertion from getZExtValue().
Definition at line 192 of file Constants.h.
References llvm::APInt::isNullValue().
Referenced by llvm::GEPOperator::accumulateConstantOffset(), annotateNonNullAndDereferenceable(), llvm::CodeViewDebug::CodeViewDebug(), createFFSIntrinsic(), llvm::createMemCpyLoopKnownSize(), evaluateFCmpRelation(), evaluateGEPOffsetExpression(), evaluateICmpRelation(), llvm::SCEVExpander::expandUnionPredicate(), FactorOutConstant(), foldAndOrOfEqualityCmpsWithConstants(), foldICmpBitCast(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldUnsignedUnderflowCheck(), GEPToVectorIndex(), getCompareCC(), getComparePred(), getImplicitScaleFactor(), getMaskedICmpType(), getOffsetFromIndex(), getOffsetFromIndices(), getRangeForAffineARHelper(), llvm::SITargetLowering::getTgtMemIntrinsic(), hasOnlyOneNonZeroIndex(), llvm::IndexedReference::hasTemporalReuse(), INITIALIZE_PASS(), InstructionDereferencesPointer(), llvm::Loop::isCanonical(), llvm::isGEPBasedOnPointerToString(), isMulPowOf2(), llvm::ConstantSDNode::isNullValue(), isSimpleEnoughPointerToCommit(), isVectorReductionOp(), llvm::LibCallSimplifier::LibCallSimplifier(), llvm::HexagonTargetLowering::LowerBITCAST(), mayDivideByZero(), populateDependencyMatrix(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), and llvm::InstCombiner::simplifyRangeCheck().
uge()
bool llvm::ConstantInt::uge (uint64_t Num) const inline
This function will return true iff this constant represents a value with active bits bigger than 64 bits or a value greater than the given uint64_t value.
Returns
true iff this constant is greater or equal to the given number. Determine if the value is greater or equal to the given number.
Definition at line 241 of file Constants.h.
References llvm::APInt::uge().
Friends And Related Function Documentation
Constant
friend class Constant friend
Definition at line 84 of file Constants.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Constants.h
lib/IR/Constants.cpp