LLVM: llvm::orc::AbsoluteSymbolsMaterializationUnit Class Reference
llvm::orc::AbsoluteSymbolsMaterializationUnit Class Reference
A MaterializationUnit implementation for pre-existing absolute symbols.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
AbsoluteSymbolsMaterializationUnit (SymbolMap Symbols, VModuleKey K)
StringRef getName () const override
Return the name of this materialization unit.
Public Member Functions inherited from llvm::orc::MaterializationUnit
MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, VModuleKey K)
virtual ~MaterializationUnit ()
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
void doMaterialize (JITDylib &JD)
Called by materialization dispatchers (see ExecutionSession::DispatchMaterializationFunction) to trigger materialization of this MaterializationUnit.
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Additional Inherited Members
Protected Attributes inherited from llvm::orc::MaterializationUnit
SymbolFlagsMap SymbolFlags
VModuleKey K
Detailed Description
A MaterializationUnit implementation for pre-existing absolute symbols.
All symbols will be resolved and marked ready as soon as the unit is materialized.
Definition at line 605 of file Core.h.
Constructor & Destructor Documentation
AbsoluteSymbolsMaterializationUnit()
llvm::orc::AbsoluteSymbolsMaterializationUnit::AbsoluteSymbolsMaterializationUnit (SymbolMap Symbols, VModuleKey K)
Definition at line 551 of file Core.cpp.
Member Function Documentation
getName()
StringRef llvm::orc::AbsoluteSymbolsMaterializationUnit::getName () const override virtual
Return the name of this materialization unit.
Useful for debugging output.
Implements llvm::orc::MaterializationUnit.
Definition at line 556 of file Core.cpp.
References assert(), llvm::cantFail(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::orc::MaterializationResponsibility::notifyEmitted(), and llvm::orc::MaterializationResponsibility::notifyResolved().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp