LLVM: llvm::coverage::CoverageMappingWriter Class Reference
llvm::coverage::CoverageMappingWriter Class Reference
Writer for instrumentation based coverage mapping data.
#include "llvm/ProfileData/Coverage/CoverageMappingWriter.h"
Public Member Functions
CoverageMappingWriter (ArrayRef< unsigned > VirtualFileMapping, ArrayRef< CounterExpression > Expressions, MutableArrayRef< CounterMappingRegion > MappingRegions)
void write (raw_ostream &OS)
Write encoded coverage mapping data to the given output stream.
Detailed Description
Writer for instrumentation based coverage mapping data.
Definition at line 40 of file CoverageMappingWriter.h.
Constructor & Destructor Documentation
CoverageMappingWriter()
llvm::coverage::CoverageMappingWriter::CoverageMappingWriter (ArrayRef< unsigned > VirtualFileMapping, ArrayRef< CounterExpression > Expressions, MutableArrayRef< CounterMappingRegion > MappingRegions) inline
Definition at line 46 of file CoverageMappingWriter.h.
References llvm::coverage::CoverageFilenamesSectionWriter::write().
Member Function Documentation
write()
void CoverageMappingWriter::write (raw_ostream & OS)
Write encoded coverage mapping data to the given output stream.
Definition at line 127 of file CoverageMappingWriter.cpp.
References llvm::all_of(), assert(), llvm::coverage::CounterMappingRegion::CodeRegion, E, llvm::encodeULEB128(), llvm::coverage::Counter::EncodingCounterTagAndExpansionRegionTagBits, llvm::coverage::Counter::EncodingTagBits, llvm::coverage::CounterMappingRegion::endLoc(), llvm::coverage::CounterMappingRegion::ExpansionRegion, Expressions, llvm::coverage::CounterMappingRegion::FileID, llvm::coverage::CounterMappingRegion::GapRegion, I, if(), llvm::coverage::Counter::isZero(), llvm::coverage::CounterMappingRegion::Kind, llvm::max(), llvm::coverage::CounterMappingRegion::SkippedRegion, llvm::stable_sort(), llvm::coverage::CounterMappingRegion::startLoc(), and writeCounter().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingWriter.h
lib/ProfileData/Coverage/CoverageMappingWriter.cpp