LLVM: llvm::ValueEnumerator Class Reference
llvm::ValueEnumerator Class Reference
#include "Bitcode/Writer/ValueEnumerator.h"
Public Types
using TypeList = std::vector< Type * >
using ValueList = std::vector< std::pair< const Value *, unsigned > >
using IndexAndAttrSet = std::pair< unsigned, AttributeSet >
Attribute groups as encoded in bitcode are almost AttributeSets, but they include the AttributeList index, so we have to track that in our map.
Public Member Functions
ValueEnumerator (const Module &M, bool ShouldPreserveUseListOrder)
ValueEnumerator (const ValueEnumerator &)=delete
ValueEnumerator & operator= (const ValueEnumerator &)=delete
void dump () const
void print (raw_ostream &OS, const ValueMapType &Map, const char *Name) const
void print (raw_ostream &OS, const MetadataMapType &Map, const char *Name) const
unsigned getValueID (const Value *V) const
unsigned getMetadataID (const Metadata *MD) const
unsigned getMetadataOrNullID (const Metadata *MD) const
unsigned numMDs () const
bool shouldPreserveUseListOrder () const
unsigned getTypeID (Type *T) const
unsigned getInstructionID (const Instruction *I) const
void setInstructionID (const Instruction *I)
unsigned getAttributeListID (AttributeList PAL) const
unsigned getAttributeGroupID (IndexAndAttrSet Group) const
void getFunctionConstantRange (unsigned &Start, unsigned &End) const
getFunctionConstantRange - Return the range of values that corresponds to function-local constants.
const ValueList & getValues () const
bool hasMDs () const
Check whether the current block has any metadata to emit.
ArrayRef< const Metadata * > getMDStrings () const
Get the MDString metadata for this block.
ArrayRef< const Metadata * > getNonMDStrings () const
Get the non-MDString metadata for this block.
const TypeList & getTypes () const
const std::vector< const BasicBlock * > & getBasicBlocks () const
const std::vector< AttributeList > & getAttributeLists () const
const std::vector< IndexAndAttrSet > & getAttributeGroups () const
const ComdatSetType & getComdats () const
unsigned getComdatID (const Comdat *C) const
unsigned getGlobalBasicBlockID (const BasicBlock *BB) const
getGlobalBasicBlockID - This returns the function-specific ID for the specified basic block.
void incorporateFunction (const Function &F)
incorporateFunction/purgeFunction - If you'd like to deal with a function, use these two methods to get its data into the ValueEnumerator!
void purgeFunction ()
uint64_t computeBitsRequiredForTypeIndicies () const
Public Attributes
UseListOrderStack UseListOrders
Detailed Description
Definition at line 44 of file ValueEnumerator.h.
Member Typedef Documentation
IndexAndAttrSet
using llvm::ValueEnumerator::IndexAndAttrSet = std::pair<unsigned, AttributeSet>
Attribute groups as encoded in bitcode are almost AttributeSets, but they include the AttributeList index, so we have to track that in our map.
Definition at line 53 of file ValueEnumerator.h.
TypeList
using llvm::ValueEnumerator::TypeList = std::vector<Type *>
Definition at line 46 of file ValueEnumerator.h.
ValueList
using llvm::ValueEnumerator::ValueList = std::vector<std::pair<const Value *, unsigned> >
Definition at line 49 of file ValueEnumerator.h.
Constructor & Destructor Documentation
ValueEnumerator() [1/2]
ValueEnumerator::ValueEnumerator (const Module & M, bool ShouldPreserveUseListOrder)
Definition at line 320 of file ValueEnumerator.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::dyn_cast(), llvm::numbers::e, F(), llvm::AttributeList::FunctionIndex, llvm::Type::getMetadataTy(), llvm::Module::globals(), I, predictUseListOrder(), second, and UseListOrders.
ValueEnumerator() [2/2]
llvm::ValueEnumerator::ValueEnumerator (const ValueEnumerator &) delete
Member Function Documentation
computeBitsRequiredForTypeIndicies()
uint64_t ValueEnumerator::computeBitsRequiredForTypeIndicies () const
Definition at line 1039 of file ValueEnumerator.cpp.
References getTypes(), llvm::Log2_32_Ceil(), and llvm::size().
Referenced by emitSignedInt64(), getAttrKindEncoding(), and getComdats().
dump()
LLVM_DUMP_METHOD void ValueEnumerator::dump () const
Definition at line 467 of file ValueEnumerator.cpp.
References llvm::dbgs(), and print().
getAttributeGroupID()
unsigned llvm::ValueEnumerator::getAttributeGroupID (IndexAndAttrSet Group) const inline
Definition at line 183 of file ValueEnumerator.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by getAttrKindEncoding().
getAttributeGroups()
const std::vector<IndexAndAttrSet>& llvm::ValueEnumerator::getAttributeGroups () const inline
Definition at line 221 of file ValueEnumerator.h.
Referenced by getAttrKindEncoding().
getAttributeListID()
unsigned llvm::ValueEnumerator::getAttributeListID (AttributeList PAL) const inline
Definition at line 176 of file ValueEnumerator.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::AttributeList::isEmpty().
Referenced by emitSignedInt64(), and getStringEncoding().
getAttributeLists()
const std::vector<AttributeList>& llvm::ValueEnumerator::getAttributeLists () const inline
Definition at line 219 of file ValueEnumerator.h.
Referenced by getAttrKindEncoding().
getBasicBlocks()
const std::vector<const BasicBlock*>& llvm::ValueEnumerator::getBasicBlocks () const inline
Definition at line 215 of file ValueEnumerator.h.
Referenced by emitSignedInt64().
getComdatID()
unsigned ValueEnumerator::getComdatID (const Comdat * C) const
Definition at line 447 of file ValueEnumerator.cpp.
References assert(), and llvm::UniqueVector< T >::idFor().
Referenced by getComdats(), and getStringEncoding().
getComdats()
const ComdatSetType& llvm::ValueEnumerator::getComdats () const inline
Definition at line 225 of file ValueEnumerator.h.
References C, computeBitsRequiredForTypeIndicies(), F(), getComdatID(), getGlobalBasicBlockID(), incorporateFunction(), purgeFunction(), and llvm::ARM_MB::ST.
Referenced by getEncodedUnnamedAddr().
getFunctionConstantRange()
void llvm::ValueEnumerator::getFunctionConstantRange (unsigned & Start, unsigned & End) const inline
getFunctionConstantRange - Return the range of values that corresponds to function-local constants.
Definition at line 193 of file ValueEnumerator.h.
Referenced by emitSignedInt64().
getGlobalBasicBlockID()
unsigned ValueEnumerator::getGlobalBasicBlockID (const BasicBlock * BB) const
getGlobalBasicBlockID - This returns the function-specific ID for the specified basic block.
This is relatively expensive information, so it should only be used by rare constructs such as address-of-label.
Definition at line 1030 of file ValueEnumerator.cpp.
References llvm::BasicBlock::getParent(), and IncorporateFunctionInfoGlobalBBIDs().
Referenced by emitSignedInt64(), and getComdats().
getInstructionID()
unsigned ValueEnumerator::getInstructionID (const Instruction * I) const
Definition at line 441 of file ValueEnumerator.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by getTypeID().
getMDStrings()
ArrayRef<const Metadata *> llvm::ValueEnumerator::getMDStrings () const inline
Get the MDString metadata for this block.
Definition at line 204 of file ValueEnumerator.h.
References llvm::makeArrayRef().
getMetadataID()
unsigned llvm::ValueEnumerator::getMetadataID (const Metadata * MD) const inline
Definition at line 153 of file ValueEnumerator.h.
References assert(), and getMetadataOrNullID().
Referenced by getOptimizationFlags(), getValueID(), and rotateSign().
getMetadataOrNullID()
unsigned llvm::ValueEnumerator::getMetadataOrNullID (const Metadata * MD) const inline
Definition at line 159 of file ValueEnumerator.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by emitSignedInt64(), getMetadataID(), getOptimizationFlags(), and rotateSign().
getNonMDStrings()
ArrayRef<const Metadata *> llvm::ValueEnumerator::getNonMDStrings () const inline
Get the non-MDString metadata for this block.
Definition at line 209 of file ValueEnumerator.h.
References llvm::makeArrayRef().
getTypeID()
unsigned llvm::ValueEnumerator::getTypeID (Type * T) const inline
Definition at line 167 of file ValueEnumerator.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getInstructionID(), I, and setInstructionID().
Referenced by emitSignedInt64(), getAttrKindEncoding(), getOptimizationFlags(), getStringEncoding(), and print().
getTypes()
const TypeList& llvm::ValueEnumerator::getTypes () const inline
Definition at line 213 of file ValueEnumerator.h.
Referenced by computeBitsRequiredForTypeIndicies(), emitSignedInt64(), and getAttrKindEncoding().
getValueID()
unsigned ValueEnumerator::getValueID (const Value * V) const
Definition at line 457 of file ValueEnumerator.cpp.
References assert(), llvm::ValueMap< KeyT, ValueT, Config >::end(), llvm::ValueMap< KeyT, ValueT, Config >::find(), getMetadataID(), and I.
Referenced by emitSignedInt64(), getMetadataTypeOrder(), getOptimizationFlags(), getStringEncoding(), print(), and writeTypeIdCompatibleVtableSummaryRecord().
getValues()
const ValueList& llvm::ValueEnumerator::getValues () const inline
Definition at line 198 of file ValueEnumerator.h.
Referenced by emitSignedInt64().
hasMDs()
bool llvm::ValueEnumerator::hasMDs () const inline
Check whether the current block has any metadata to emit.
Definition at line 201 of file ValueEnumerator.h.
incorporateFunction()
void ValueEnumerator::incorporateFunction (const Function & F)
incorporateFunction/purgeFunction - If you'd like to deal with a function, use these two methods to get its data into the ValueEnumerator!
Definition at line 943 of file ValueEnumerator.cpp.
References llvm::Function::args(), assert(), llvm::ValueMap< KeyT, ValueT, Config >::count(), llvm::numbers::e, I, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorBase::size().
Referenced by emitSignedInt64(), and getComdats().
numMDs()
unsigned llvm::ValueEnumerator::numMDs () const inline
Definition at line 163 of file ValueEnumerator.h.
operator=()
ValueEnumerator& llvm::ValueEnumerator::operator= (const ValueEnumerator &) delete
print() [1/2]
void ValueEnumerator::print (raw_ostream & OS, const ValueMapType & Map, const char * Name) const
Definition at line 475 of file ValueEnumerator.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::errs(), llvm::Value::getName(), llvm::Value::getNumUses(), llvm::Value::hasName(), I, llvm::Value::print(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::Value::use_begin(), and llvm::Value::uses().
Referenced by dump().
print() [2/2]
void ValueEnumerator::print (raw_ostream & OS, const MetadataMapType & Map, const char * Name) const
Definition at line 503 of file ValueEnumerator.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::ValueSymbolTable::begin(), C, llvm::numbers::e, E, llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::ValueSymbolTable::end(), F(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::find_if(), first, llvm::NamedMDNode::getNumOperands(), llvm::NamedMDNode::getOperand(), getTypeID(), llvm::ValueAsMetadata::getValue(), getValueID(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MDNode::isDistinct(), isIntOrIntVectorValue(), N, llvm::Module::named_metadata(), llvm::MDNode::op_begin(), llvm::MDNode::op_end(), llvm::MDNode::operands(), llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::Metadata::print(), push(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::stable_sort(), and VI.
purgeFunction()
void ValueEnumerator::purgeFunction ()
Remove purged values from the ValueMap.
Definition at line 1005 of file ValueEnumerator.cpp.
References llvm::numbers::e, llvm::ValueMap< KeyT, ValueT, Config >::erase(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase().
Referenced by emitSignedInt64(), and getComdats().
setInstructionID()
void ValueEnumerator::setInstructionID (const Instruction * I)
Definition at line 453 of file ValueEnumerator.cpp.
References I.
Referenced by emitSignedInt64(), and getTypeID().
shouldPreserveUseListOrder()
bool llvm::ValueEnumerator::shouldPreserveUseListOrder () const inline
Definition at line 165 of file ValueEnumerator.h.
Referenced by emitSignedInt64(), and writeIdentificationBlock().
Member Data Documentation
UseListOrders
UseListOrderStack llvm::ValueEnumerator::UseListOrders
Definition at line 55 of file ValueEnumerator.h.
Referenced by emitSignedInt64(), and ValueEnumerator().
The documentation for this class was generated from the following files:
lib/Bitcode/Writer/ValueEnumerator.h
lib/Bitcode/Writer/ValueEnumerator.cpp