LLVM: llvm::LoopVectorizationCostModel Class Reference
llvm::LoopVectorizationCostModel Class Reference
LoopVectorizationCostModel - estimates the expected speedups due to vectorization.
Classes
struct RegisterUsage
A struct that represents some properties of the register usage of a loop.
Public Types
enum InstWidening {
CM_Unknown, CM_Widen, CM_Widen_Reverse, CM_Interleave,
CM_GatherScatter, CM_Scalarize
}
Decision that was taken during cost calculation for memory instruction.
Public Member Functions
LoopVectorizationCostModel (ScalarEpilogueLowering SEL, Loop *L, PredicatedScalarEvolution &PSE, LoopInfo *LI, LoopVectorizationLegality *Legal, const TargetTransformInfo &TTI, const TargetLibraryInfo *TLI, DemandedBits *DB, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, const Function *F, const LoopVectorizeHints *Hints, InterleavedAccessInfo &IAI)
Optional< unsigned > computeMaxVF ()
bool runtimeChecksRequired ()
VectorizationFactor selectVectorizationFactor (unsigned MaxVF)
void selectUserVectorizationFactor (unsigned UserVF)
Setup cost-based decisions for user vectorization factor.
std::pair< unsigned, unsigned > getSmallestAndWidestTypes ()
unsigned selectInterleaveCount (unsigned VF, unsigned LoopCost)
void setCostBasedWideningDecision (unsigned VF)
Memory access instruction may be vectorized in more than one way.
SmallVector< RegisterUsage, 8 > calculateRegisterUsage (ArrayRef< unsigned > VFs)
void collectValuesToIgnore ()
Collect values we want to ignore in the cost model.
const MapVector< Instruction *, uint64_t > & getMinimalBitwidths () const
bool isProfitableToScalarize (Instruction *I, unsigned VF) const
bool isUniformAfterVectorization (Instruction *I, unsigned VF) const
Returns true if I is known to be uniform after vectorization.
bool isScalarAfterVectorization (Instruction *I, unsigned VF) const
Returns true if I is known to be scalar after vectorization.
bool canTruncateToMinimalBitwidth (Instruction *I, unsigned VF) const
void setWideningDecision (Instruction *I, unsigned VF, InstWidening W, unsigned Cost)
Save vectorization decision W and Cost taken by the cost model for instruction I and vector width VF.
void setWideningDecision (const InterleaveGroup< Instruction > *Grp, unsigned VF, InstWidening W, unsigned Cost)
Save vectorization decision W and Cost taken by the cost model for interleaving group Grp and vector width VF.
InstWidening getWideningDecision (Instruction *I, unsigned VF)
Return the cost model decision for the given instruction I and vector width VF.
unsigned getWideningCost (Instruction *I, unsigned VF)
Return the vectorization cost for the given instruction I and vector width VF.
bool isOptimizableIVTruncate (Instruction *I, unsigned VF)
Return True if instruction I is an optimizable truncate whose operand is an induction variable.
void collectInstsToScalarize (unsigned VF)
Collects the instructions to scalarize for each predicated instruction in the loop.
void collectUniformsAndScalars (unsigned VF)
Collect Uniform and Scalar values for the given VF.
bool isLegalMaskedStore (Type *DataType, Value *Ptr, MaybeAlign Alignment)
Returns true if the target machine supports masked store operation for the given DataType and kind of access to Ptr.
bool isLegalMaskedLoad (Type *DataType, Value *Ptr, MaybeAlign Alignment)
Returns true if the target machine supports masked load operation for the given DataType and kind of access to Ptr.
bool isLegalMaskedScatter (Type *DataType, MaybeAlign Alignment)
Returns true if the target machine supports masked scatter operation for the given DataType.
bool isLegalMaskedGather (Type *DataType, MaybeAlign Alignment)
Returns true if the target machine supports masked gather operation for the given DataType.
bool isLegalGatherOrScatter (Value *V)
Returns true if the target machine can represent V as a masked gather or scatter operation.
bool isScalarWithPredication (Instruction *I, unsigned VF=1)
Returns true if I is an instruction that will be scalarized with predication.
bool isPredicatedInst (Instruction *I)
bool memoryInstructionCanBeWidened (Instruction *I, unsigned VF=1)
Returns true if I is a memory instruction with consecutive memory access that can be widened.
bool interleavedAccessCanBeWidened (Instruction *I, unsigned VF=1)
Returns true if I is a memory instruction in an interleaved-group of memory accesses that can be vectorized with wide vector loads/stores and shuffles.
bool isAccessInterleaved (Instruction *Instr)
Check if Instr belongs to any interleaved access group.
const InterleaveGroup< Instruction > * getInterleavedAccessGroup (Instruction *Instr)
Get the interleaved access group that Instr belongs to.
bool requiresScalarEpilogue () const
Returns true if an interleaved group requires a scalar iteration to handle accesses with gaps, and there is nothing preventing us from creating a scalar epilogue.
bool isScalarEpilogueAllowed () const
Returns true if a scalar epilogue is not allowed due to optsize or a loop hint annotation.
bool foldTailByMasking () const
Returns true if all loop blocks should be masked to fold tail loop.
bool blockNeedsPredication (BasicBlock *BB)
unsigned getVectorIntrinsicCost (CallInst *CI, unsigned VF)
Estimate cost of an intrinsic call instruction CI if it were vectorized with factor VF.
unsigned getVectorCallCost (CallInst *CI, unsigned VF, bool &NeedToScalarize)
Estimate cost of a call instruction CI if it were vectorized with factor VF.
Public Attributes
Loop * TheLoop
The loop that we evaluate.
PredicatedScalarEvolution & PSE
Predicated scalar evolution analysis.
LoopInfo * LI
Loop Info analysis.
LoopVectorizationLegality * Legal
Vectorization legality.
const TargetTransformInfo & TTI
Vector target information.
const TargetLibraryInfo * TLI
Target Library Info.
DemandedBits * DB
Demanded bits analysis.
AssumptionCache * AC
Assumption cache.
OptimizationRemarkEmitter * ORE
Interface to emit optimization remarks.
const Function * TheFunction
const LoopVectorizeHints * Hints
Loop Vectorize Hint.
InterleavedAccessInfo & InterleaveInfo
The interleave access information contains groups of interleaved accesses with the same stride and close to each other.
SmallPtrSet< const Value *, 16 > ValuesToIgnore
Values to ignore in the cost model.
SmallPtrSet< const Value *, 16 > VecValuesToIgnore
Values to ignore in the cost model when VF > 1.
Detailed Description
LoopVectorizationCostModel - estimates the expected speedups due to vectorization.
In many cases vectorization is not profitable. This can happen because of a number of reasons. In this class we mainly attempt to predict the expected speedup/slowdowns due to the supported instruction set. We use the TargetTransformInfo to query the different backends for the cost of different operations.
Definition at line 960 of file LoopVectorize.cpp.
Member Enumeration Documentation
InstWidening
enum llvm::LoopVectorizationCostModel::InstWidening
Decision that was taken during cost calculation for memory instruction.
Enumerator
CM_Unknown
CM_Widen
CM_Widen_Reverse
CM_Interleave
CM_GatherScatter
CM_Scalarize
Definition at line 1097 of file LoopVectorize.cpp.
Constructor & Destructor Documentation
LoopVectorizationCostModel()
llvm::LoopVectorizationCostModel::LoopVectorizationCostModel (ScalarEpilogueLowering SEL, Loop * L, PredicatedScalarEvolution & PSE, LoopInfo * LI, LoopVectorizationLegality * Legal, const TargetTransformInfo & TTI, const TargetLibraryInfo * TLI, DemandedBits * DB, AssumptionCache * AC, OptimizationRemarkEmitter * ORE, const Function * F, const LoopVectorizeHints * Hints, InterleavedAccessInfo & IAI) inline
Definition at line 962 of file LoopVectorize.cpp.
Member Function Documentation
blockNeedsPredication()
bool llvm::LoopVectorizationCostModel::blockNeedsPredication (BasicBlock * BB) inline
Definition at line 1296 of file LoopVectorize.cpp.
References llvm::LoopVectorizationLegality::blockNeedsPredication(), llvm::CM_ScalarEpilogueAllowed, llvm::dyn_cast(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::InnerLoopVectorizer::Legal, and llvm::make_filter_range().
calculateRegisterUsage()
SmallVector< LoopVectorizationCostModel::RegisterUsage, 8 > LoopVectorizationCostModel::calculateRegisterUsage (ArrayRef< unsigned > VFs)
Returns
Returns information about the register usages of the loop for the given vectorization factors.
Definition at line 5359 of file LoopVectorize.cpp.
References assert(), llvm::LoopBlocksDFS::beginRPO(), llvm::dbgs(), DFS(), llvm::dyn_cast(), llvm::numbers::e, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::LoopBlocksDFS::endRPO(), llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), llvm::SmallPtrSetImpl< PtrType >::find(), llvm::find(), llvm::LoopVectorizationLegality::getMaxSafeDepDistBytes(), llvm::TargetTransformInfo::getRegisterBitWidth(), llvm::TargetTransformInfo::getRegisterClassForType(), llvm::TargetTransformInfo::getRegisterClassName(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::InnerLoopVectorizer::Legal, llvm::InnerLoopVectorizer::LI, List, LLVM_DEBUG, llvm::LoopVectorizationCostModel::RegisterUsage::LoopInvariantRegs, llvm::make_range(), llvm::max(), llvm::LoopVectorizationCostModel::RegisterUsage::MaxLocalUsers, NumberOfStoresToPredicate, llvm::LoopBlocksDFS::perform(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::RegUsage, llvm::SmallVectorBase::size(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size(), llvm::SmallPtrSetImplBase::size(), llvm::ArrayRef< T >::size(), llvm::InnerLoopVectorizer::TTI, and llvm::InnerLoopVectorizer::VF.
canTruncateToMinimalBitwidth()
bool llvm::LoopVectorizationCostModel::canTruncateToMinimalBitwidth (Instruction * I, unsigned VF) const inline
Returns
True if instruction I can be truncated to a smaller bitwidth for vectorization factor VF.
Definition at line 1090 of file LoopVectorize.cpp.
collectInstsToScalarize()
void LoopVectorizationCostModel::collectInstsToScalarize (unsigned VF)
Collects the instructions to scalarize for each predicated instruction in the loop.
Definition at line 5572 of file LoopVectorize.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), C, llvm::InnerLoopVectorizer::Cost, llvm::dbgs(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), ForceTargetInstructionCost, llvm::TargetTransformInfo::getCFInstrCost(), llvm::Instruction::getParent(), getReciprocalPredBlockProb(), llvm::TargetTransformInfo::getScalarizationOverhead(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::VectorType::isValidElementType(), llvm::Type::isVoidTy(), LLVM_DEBUG, llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), ToVectorTy(), llvm::InnerLoopVectorizer::TTI, and llvm::InnerLoopVectorizer::VF.
collectUniformsAndScalars()
void llvm::LoopVectorizationCostModel::collectUniformsAndScalars (unsigned VF) inline
Collect Uniform and Scalar values for the given VF.
The sets depend on CM decision for Load/Store instructions that may be vectorized as interleave, gather-scatter or scalarized.
Definition at line 1192 of file LoopVectorize.cpp.
collectValuesToIgnore()
void LoopVectorizationCostModel::collectValuesToIgnore ()
Collect values we want to ignore in the cost model.
Definition at line 6421 of file LoopVectorize.cpp.
References llvm::InnerLoopVectorizer::AC, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::CodeMetrics::collectEphemeralValues(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::RecurrenceDescriptor::getCastInsts(), llvm::InductionDescriptor::getCastInsts(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::LoopVectorizationLegality::getReductionVars(), llvm::InnerLoopVectorizer::Induction, llvm::InnerLoopVectorizer::Legal, and Reduction.
Referenced by llvm::LoopVectorizePass::processLoop().
computeMaxVF()
Optional< unsigned > LoopVectorizationCostModel::computeMaxVF ()
Returns
An upper bound for the vectorization factor, or None if vectorization and interleaving should be avoided up front.
Definition at line 4917 of file LoopVectorize.cpp.
References assert(), llvm::CM_ScalarEpilogueAllowed, llvm::CM_ScalarEpilogueNotAllowedLowTripLoop, llvm::CM_ScalarEpilogueNotAllowedOptSize, llvm::CM_ScalarEpilogueNotNeededUsePredicate, llvm::computeMinimumValueSizes(), llvm::dbgs(), llvm::LoopVectorizationLegality::getMaxSafeRegisterWidth(), llvm::TargetTransformInfo::getMinimumVF(), llvm::TargetTransformInfo::getNumberOfRegisters(), llvm::TargetTransformInfo::getRegisterBitWidth(), llvm::LoopVectorizationLegality::getRuntimePointerChecking(), llvm::PredicatedScalarEvolution::getSE(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::TargetTransformInfo::hasBranchDivergence(), llvm::isPowerOf2_32(), llvm::InnerLoopVectorizer::Legal, LLVM_DEBUG, MaximizeBandwidth, llvm::RuntimePointerChecking::Need, llvm::None, llvm::InnerLoopVectorizer::ORE, llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), llvm::InnerLoopVectorizer::PSE, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reportVectorizationFailure(), llvm::TargetTransformInfo::shouldMaximizeVectorBandwidth(), llvm::InnerLoopVectorizer::TTI, useMaskedInterleavedAccesses(), and llvm::AArch64CC::VS.
foldTailByMasking()
bool llvm::LoopVectorizationCostModel::foldTailByMasking () const inline
Returns true if all loop blocks should be masked to fold tail loop.
Definition at line 1294 of file LoopVectorize.cpp.
Referenced by llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), llvm::InnerLoopVectorizer::fixReduction(), and llvm::InnerLoopVectorizer::getOrCreateVectorTripCount().
getInterleavedAccessGroup()
const InterleaveGroup<Instruction>* llvm::LoopVectorizationCostModel::getInterleavedAccessGroup (Instruction * Instr) inline
Get the interleaved access group that Instr belongs to.
Definition at line 1276 of file LoopVectorize.cpp.
Referenced by llvm::InnerLoopVectorizer::vectorizeInterleaveGroup().
getMinimalBitwidths()
const MapVector<Instruction *, uint64_t>& llvm::LoopVectorizationCostModel::getMinimalBitwidths () const inline
Returns
The smallest bitwidth each instruction can be represented with. The vector equivalents of these instructions should be truncated to this type.
Definition at line 1036 of file LoopVectorize.cpp.
Referenced by llvm::InnerLoopVectorizer::truncateToMinimalBitwidths().
getSmallestAndWidestTypes()
std::pair< unsigned, unsigned > LoopVectorizationCostModel::getSmallestAndWidestTypes ()
Returns
The size (in bits) of the smallest and widest types in the code that needs to be vectorized. We ignore values that remain scalar such as 64 bit loop indices.
Definition at line 5131 of file LoopVectorize.cpp.
References llvm::RecurrenceDescriptor::getRecurrenceType(), llvm::LoopVectorizationLegality::getReductionVars(), llvm::Type::getScalarType(), llvm::DataLayout::getTypeSizeInBits(), I, llvm::Type::isPointerTy(), llvm::LoopVectorizationLegality::isReductionVariable(), llvm::InnerLoopVectorizer::Legal, llvm::max(), and llvm::ARM_MB::ST.
Referenced by determineVPlanVF().
getVectorCallCost()
unsigned LoopVectorizationCostModel::getVectorCallCost (CallInst * CI, unsigned VF, bool & NeedToScalarize)
Estimate cost of a call instruction CI if it were vectorized with factor VF.
Return the cost of the instruction, including scalarization overhead if it's needed. The flag NeedToScalarize shows if the call needs to be scalarized - i.e. either vector version isn't available, or is too expensive.
Definition at line 3257 of file LoopVectorize.cpp.
References llvm::CallBase::arg_operands(), llvm::InnerLoopVectorizer::Cost, F(), llvm::CallBase::getCalledFunction(), llvm::TargetTransformInfo::getCallInstrCost(), llvm::Value::getName(), llvm::Value::getType(), llvm::TargetLibraryInfo::isFunctionVectorizable(), llvm::CallBase::isNoBuiltin(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::InnerLoopVectorizer::TLI, ToVectorTy(), and llvm::InnerLoopVectorizer::TTI.
getVectorIntrinsicCost()
unsigned LoopVectorizationCostModel::getVectorIntrinsicCost (CallInst * CI, unsigned VF)
Estimate cost of an intrinsic call instruction CI if it were vectorized with factor VF.
Return the cost of the instruction, including scalarization overhead if it's needed.
Definition at line 3301 of file LoopVectorize.cpp.
References llvm::CallBase::arg_operands(), assert(), llvm::TargetTransformInfo::getIntrinsicInstrCost(), llvm::Value::getType(), llvm::getVectorIntrinsicIDForCall(), Operands, llvm::InnerLoopVectorizer::TLI, llvm::InnerLoopVectorizer::TTI, and llvm::InnerLoopVectorizer::VF.
getWideningCost()
unsigned llvm::LoopVectorizationCostModel::getWideningCost (Instruction * I, unsigned VF) inline
Return the vectorization cost for the given instruction I and vector width VF.
Definition at line 1151 of file LoopVectorize.cpp.
References assert().
getWideningDecision()
InstWidening llvm::LoopVectorizationCostModel::getWideningDecision (Instruction * I, unsigned VF) inline
Return the cost model decision for the given instruction I and vector width VF.
Return CM_Unknown if this instruction did not pass through the cost modeling.
Definition at line 1134 of file LoopVectorize.cpp.
References assert(), and EnableVPlanNativePath.
Referenced by llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
interleavedAccessCanBeWidened()
bool LoopVectorizationCostModel::interleavedAccessCanBeWidened (Instruction * I, unsigned VF = 1)
Returns true if I is a memory instruction in an interleaved-group of memory accesses that can be vectorized with wide vector loads/stores and shuffles.
Definition at line 4636 of file LoopVectorize.cpp.
References assert(), llvm::LoopVectorizationLegality::blockNeedsPredication(), llvm::Module::getDataLayout(), llvm::getLoadStoreAlignment(), getMemInstValueType(), llvm::Instruction::getModule(), llvm::Instruction::getParent(), hasIrregularType(), I, llvm::TargetTransformInfo::isLegalMaskedLoad(), llvm::TargetTransformInfo::isLegalMaskedStore(), llvm::LoopVectorizationLegality::isMaskRequired(), llvm::InnerLoopVectorizer::Legal, llvm::InnerLoopVectorizer::TTI, and useMaskedInterleavedAccesses().
isAccessInterleaved()
bool llvm::LoopVectorizationCostModel::isAccessInterleaved (Instruction * Instr) inline
Check if Instr belongs to any interleaved access group.
Definition at line 1270 of file LoopVectorize.cpp.
isLegalGatherOrScatter()
bool llvm::LoopVectorizationCostModel::isLegalGatherOrScatter (Value * V) inline
Returns true if the target machine can represent V as a masked gather or scatter operation.
Definition at line 1229 of file LoopVectorize.cpp.
References llvm::getLoadStoreAlignment(), getMemInstValueType(), I, llvm::InnerLoopVectorizer::LI, and SI.
isLegalMaskedGather()
bool llvm::LoopVectorizationCostModel::isLegalMaskedGather (Type * DataType, MaybeAlign Alignment) inline
Returns true if the target machine supports masked gather operation for the given DataType.
Definition at line 1223 of file LoopVectorize.cpp.
References llvm::TargetTransformInfo::isLegalMaskedGather(), and llvm::InnerLoopVectorizer::TTI.
isLegalMaskedLoad()
bool llvm::LoopVectorizationCostModel::isLegalMaskedLoad (Type * DataType, Value * Ptr, MaybeAlign Alignment) inline
Returns true if the target machine supports masked load operation for the given DataType and kind of access to Ptr.
Definition at line 1210 of file LoopVectorize.cpp.
References llvm::LoopVectorizationLegality::isConsecutivePtr(), llvm::TargetTransformInfo::isLegalMaskedLoad(), llvm::InnerLoopVectorizer::Legal, and llvm::InnerLoopVectorizer::TTI.
isLegalMaskedScatter()
bool llvm::LoopVectorizationCostModel::isLegalMaskedScatter (Type * DataType, MaybeAlign Alignment) inline
Returns true if the target machine supports masked scatter operation for the given DataType.
Definition at line 1217 of file LoopVectorize.cpp.
References llvm::TargetTransformInfo::isLegalMaskedScatter(), and llvm::InnerLoopVectorizer::TTI.
isLegalMaskedStore()
bool llvm::LoopVectorizationCostModel::isLegalMaskedStore (Type * DataType, Value * Ptr, MaybeAlign Alignment) inline
Returns true if the target machine supports masked store operation for the given DataType and kind of access to Ptr.
Definition at line 1203 of file LoopVectorize.cpp.
References llvm::LoopVectorizationLegality::isConsecutivePtr(), llvm::TargetTransformInfo::isLegalMaskedStore(), llvm::InnerLoopVectorizer::Legal, and llvm::InnerLoopVectorizer::TTI.
isOptimizableIVTruncate()
bool llvm::LoopVectorizationCostModel::isOptimizableIVTruncate (Instruction * I, unsigned VF) inline
Return True if instruction I is an optimizable truncate whose operand is an induction variable.
Such a truncate will be removed by adding a new induction variable with the destination type.
Definition at line 1162 of file LoopVectorize.cpp.
References llvm::dyn_cast(), llvm::LoopVectorizationLegality::getPrimaryInduction(), I, llvm::LoopVectorizationLegality::isInductionPhi(), llvm::TargetTransformInfo::isTruncateFree(), llvm::InnerLoopVectorizer::Legal, ToVectorTy(), and llvm::InnerLoopVectorizer::TTI.
isPredicatedInst()
bool llvm::LoopVectorizationCostModel::isPredicatedInst (Instruction * I) inline
Definition at line 1250 of file LoopVectorize.cpp.
References llvm::Instruction::getParent(), I, llvm::LoopVectorizationLegality::isMaskRequired(), and llvm::InnerLoopVectorizer::Legal.
isProfitableToScalarize()
bool llvm::LoopVectorizationCostModel::isProfitableToScalarize (Instruction * I, unsigned VF) const inline
Returns
True if it is more profitable to scalarize instruction I for vectorization factor VF.
Definition at line 1042 of file LoopVectorize.cpp.
References assert(), and EnableVPlanNativePath.
Referenced by llvm::InnerLoopVectorizer::shouldScalarizeInstruction().
isScalarAfterVectorization()
bool llvm::LoopVectorizationCostModel::isScalarAfterVectorization (Instruction * I, unsigned VF) const inline
Returns true if I is known to be scalar after vectorization.
Definition at line 1073 of file LoopVectorize.cpp.
References assert(), and EnableVPlanNativePath.
Referenced by llvm::InnerLoopVectorizer::shouldScalarizeInstruction().
isScalarEpilogueAllowed()
bool llvm::LoopVectorizationCostModel::isScalarEpilogueAllowed () const inline
Returns true if a scalar epilogue is not allowed due to optsize or a loop hint annotation.
Definition at line 1289 of file LoopVectorize.cpp.
References llvm::CM_ScalarEpilogueAllowed.
Referenced by llvm::InnerLoopVectorizer::vectorizeInterleaveGroup().
isScalarWithPredication()
bool LoopVectorizationCostModel::isScalarWithPredication (Instruction * I, unsigned VF = 1)
Returns true if I is an instruction that will be scalarized with predication.
Such instructions include conditional stores and instructions that may divide by zero. If a non-zero VF has been calculated, we check if I will be scalarized predication for that VF.
Definition at line 4601 of file LoopVectorize.cpp.
References assert(), llvm::getLoadStoreAlignment(), llvm::getLoadStorePointerOperand(), getMemInstValueType(), llvm::Instruction::getOpcode(), llvm::Instruction::getParent(), I, llvm::LoopVectorizationLegality::isMaskRequired(), llvm::InnerLoopVectorizer::Legal, llvm::SPII::Load, mayDivideByZero(), and llvm::SPII::Store.
isUniformAfterVectorization()
bool llvm::LoopVectorizationCostModel::isUniformAfterVectorization (Instruction * I, unsigned VF) const inline
Returns true if I is known to be uniform after vectorization.
Definition at line 1057 of file LoopVectorize.cpp.
References assert(), and EnableVPlanNativePath.
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::InnerLoopVectorizer::fixLCSSAPHIs(), llvm::InnerLoopVectorizer::getOrCreateScalarValue(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
memoryInstructionCanBeWidened()
bool LoopVectorizationCostModel::memoryInstructionCanBeWidened (Instruction * I, unsigned VF = 1)
Returns true if I is a memory instruction with consecutive memory access that can be widened.
Definition at line 4673 of file LoopVectorize.cpp.
References llvm::all_of(), assert(), llvm::SetVector< T, Vector, Set >::begin(), llvm::SetVector< T, Vector, Set >::count(), llvm::dbgs(), llvm::dyn_cast(), llvm::SetVector< T, Vector, Set >::end(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::SmallPtrSetImpl< PtrType >::find(), llvm::Module::getDataLayout(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::getLoadStorePointerOperand(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), hasIrregularType(), I, llvm::InnerLoopVectorizer::Induction, llvm::SetVector< T, Vector, Set >::insert(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::LoopVectorizationLegality::isConsecutivePtr(), llvm::LoopVectorizationLegality::isFirstOrderRecurrence(), llvm::InnerLoopVectorizer::Legal, llvm::InnerLoopVectorizer::LI, LLVM_DEBUG, OP, llvm::User::operand_values(), SI, llvm::SetVector< T, Vector, Set >::size(), and llvm::InnerLoopVectorizer::VF.
requiresScalarEpilogue()
bool llvm::LoopVectorizationCostModel::requiresScalarEpilogue () const inline
Returns true if an interleaved group requires a scalar iteration to handle accesses with gaps, and there is nothing preventing us from creating a scalar epilogue.
Definition at line 1283 of file LoopVectorize.cpp.
Referenced by llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), and llvm::InnerLoopVectorizer::getOrCreateVectorTripCount().
runtimeChecksRequired()
bool LoopVectorizationCostModel::runtimeChecksRequired ()
Returns
True if runtime checks are required for vectorization, and false otherwise.
Definition at line 4883 of file LoopVectorize.cpp.
References llvm::dbgs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::LoopVectorizationLegality::getLAI(), llvm::SCEVUnionPredicate::getPredicates(), llvm::LoopVectorizationLegality::getRuntimePointerChecking(), llvm::LoopAccessInfo::getSymbolicStrides(), llvm::PredicatedScalarEvolution::getUnionPredicate(), llvm::InnerLoopVectorizer::Legal, LLVM_DEBUG, llvm::RuntimePointerChecking::Need, llvm::InnerLoopVectorizer::ORE, llvm::InnerLoopVectorizer::PSE, and llvm::reportVectorizationFailure().
selectInterleaveCount()
unsigned LoopVectorizationCostModel::selectInterleaveCount (unsigned VF, unsigned LoopCost)
Returns
The desired interleave count. If interleave count has been specified by metadata it will be returned. Otherwise, the interleave count is computed and returned. VF and LoopCost are the selected vectorization factor and the cost of the selected VF.
Definition at line 5186 of file LoopVectorize.cpp.
References assert(), llvm::dbgs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::TargetTransformInfo::enableAggressiveInterleaving(), EnableIndVarRegisterHeur, EnableLoadStoreRuntimeInterleave, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), F(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), ForceTargetMaxScalarInterleaveFactor, ForceTargetMaxVectorInterleaveFactor, ForceTargetNumScalarRegs, ForceTargetNumVectorRegs, llvm::TargetTransformInfo::getMaxInterleaveFactor(), llvm::LoopVectorizationLegality::getMaxSafeDepDistBytes(), llvm::TargetTransformInfo::getNumberOfRegisters(), llvm::LoopVectorizationLegality::getNumLoads(), llvm::LoopVectorizationLegality::getNumStores(), llvm::LoopVectorizationLegality::getReductionVars(), llvm::TargetTransformInfo::getRegisterClassName(), llvm::LoopVectorizationLegality::getRuntimePointerChecking(), llvm::PredicatedScalarEvolution::getSE(), getSmallBestKnownTC(), llvm::InnerLoopVectorizer::Legal, LLVM_DEBUG, llvm::LoopVectorizationCostModel::RegisterUsage::LoopInvariantRegs, llvm::max(), llvm::LoopVectorizationCostModel::RegisterUsage::MaxLocalUsers, MaxNestedScalarReductionIC, llvm::RuntimePointerChecking::Need, llvm::PowerOf2Floor(), llvm::InnerLoopVectorizer::PSE, SmallLoopCost, TinyTripCountInterleaveThreshold, and llvm::InnerLoopVectorizer::TTI.
Referenced by llvm::LoopVectorizePass::processLoop().
selectUserVectorizationFactor()
void llvm::LoopVectorizationCostModel::selectUserVectorizationFactor (unsigned UserVF) inline
Setup cost-based decisions for user vectorization factor.
Definition at line 990 of file LoopVectorize.cpp.
References llvm::InnerLoopVectorizer::VF.
selectVectorizationFactor()
VectorizationFactor LoopVectorizationCostModel::selectVectorizationFactor (unsigned MaxVF)
Returns
The most profitable vectorization factor and the cost of that VF. This method checks every power of two up to MaxVF. If UserVF is not ZERO then this vectorization factor will be selected if vectorization is possible.
Definition at line 5080 of file LoopVectorize.cpp.
References C, llvm::InnerLoopVectorizer::Cost, llvm::dbgs(), EnableCondStoresVectorization, llvm::LoopVectorizeHints::FK_Enabled, LLVM_DEBUG, llvm::max(), llvm::InnerLoopVectorizer::ORE, and llvm::reportVectorizationFailure().
setCostBasedWideningDecision()
void LoopVectorizationCostModel::setCostBasedWideningDecision (unsigned VF)
Memory access instruction may be vectorized in more than one way.
Form of instruction after vectorization depends on cost. This function takes cost-based decisions for Load/Store instructions and collects them in a map. This decisions map is used for building the lists of loop-uniform and loop-scalar instructions. The calculated cost is saved with widening decision in order to avoid redundant calculations.
Definition at line 6000 of file LoopVectorize.cpp.
References llvm::MCID::Add, assert(), llvm::LoopVectorizationLegality::blockNeedsPredication(), llvm::MCID::Call, llvm::InnerLoopVectorizer::Cost, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::IntegerType::get(), llvm::VectorType::get(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::TargetTransformInfo::getCFInstrCost(), llvm::TargetTransformInfo::getCmpSelInstrCost(), llvm::SelectInst::getCondition(), llvm::Type::getContext(), llvm::Type::getInt1Ty(), llvm::getLoadStorePointerOperand(), getMemInstValueType(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::TargetTransformInfo::getOperandInfo(), llvm::Instruction::getParent(), getReciprocalPredBlockProb(), llvm::TargetTransformInfo::getScalarizationOverhead(), llvm::PredicatedScalarEvolution::getSE(), llvm::TargetTransformInfo::getShuffleCost(), llvm::BranchInst::getSuccessor(), llvm::Value::getType(), llvm::getVectorIntrinsicIDForCall(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::BranchInst::isConditional(), llvm::LoopVectorizationLegality::isConsecutivePtr(), llvm::LoopVectorizationLegality::isFirstOrderRecurrence(), isStrideMul(), llvm::LoopVectorizationLegality::isUniform(), llvm::Type::isVectorTy(), largestIntegerVectorType(), llvm::InnerLoopVectorizer::Legal, LLVM_FALLTHROUGH, llvm::SPII::Load, llvm::max(), N, llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OK_UniformValue, llvm::TargetTransformInfo::OP_None, llvm::User::operand_values(), Operands, llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::TargetTransformInfo::prefersVectorizedAddressing(), llvm::InnerLoopVectorizer::PSE, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MCID::Select, SI, llvm::TargetTransformInfo::SK_ExtractSubvector, smallestIntegerVectorType(), llvm::SPII::Store, llvm::InnerLoopVectorizer::TLI, ToVectorTy(), llvm::InnerLoopVectorizer::TTI, and llvm::InnerLoopVectorizer::VF.
setWideningDecision() [1/2]
void llvm::LoopVectorizationCostModel::setWideningDecision (Instruction * I, unsigned VF, InstWidening W, unsigned Cost) inline
Save vectorization decision W and Cost taken by the cost model for instruction I and vector width VF.
Definition at line 1108 of file LoopVectorize.cpp.
References assert().
setWideningDecision() [2/2]
void llvm::LoopVectorizationCostModel::setWideningDecision (const InterleaveGroup< Instruction > * Grp, unsigned VF, InstWidening W, unsigned Cost) inline
Save vectorization decision W and Cost taken by the cost model for interleaving group Grp and vector width VF.
Broadcast this decicion to all instructions inside the group. But the cost will be assigned to one instruction only.
Definition at line 1116 of file LoopVectorize.cpp.
References assert(), llvm::InterleaveGroup< InstTy >::getFactor(), llvm::InterleaveGroup< InstTy >::getInsertPos(), llvm::InterleaveGroup< InstTy >::getMember(), and I.
Member Data Documentation
AC
AssumptionCache* llvm::LoopVectorizationCostModel::AC
Assumption cache.
Definition at line 1500 of file LoopVectorize.cpp.
DB
DemandedBits* llvm::LoopVectorizationCostModel::DB
Demanded bits analysis.
Definition at line 1497 of file LoopVectorize.cpp.
Hints
const LoopVectorizeHints* llvm::LoopVectorizationCostModel::Hints
Loop Vectorize Hint.
Definition at line 1508 of file LoopVectorize.cpp.
Referenced by llvm::InnerLoopVectorizer::emitMemRuntimeChecks().
InterleaveInfo
InterleavedAccessInfo& llvm::LoopVectorizationCostModel::InterleaveInfo
The interleave access information contains groups of interleaved accesses with the same stride and close to each other.
Definition at line 1512 of file LoopVectorize.cpp.
Legal
LoopVectorizationLegality* llvm::LoopVectorizationCostModel::Legal
Vectorization legality.
Definition at line 1488 of file LoopVectorize.cpp.
LI
LoopInfo* llvm::LoopVectorizationCostModel::LI
Loop Info analysis.
Definition at line 1485 of file LoopVectorize.cpp.
ORE
OptimizationRemarkEmitter* llvm::LoopVectorizationCostModel::ORE
Interface to emit optimization remarks.
Definition at line 1503 of file LoopVectorize.cpp.
PSE
PredicatedScalarEvolution& llvm::LoopVectorizationCostModel::PSE
Predicated scalar evolution analysis.
Definition at line 1482 of file LoopVectorize.cpp.
TheFunction
const Function* llvm::LoopVectorizationCostModel::TheFunction
Definition at line 1505 of file LoopVectorize.cpp.
TheLoop
Loop* llvm::LoopVectorizationCostModel::TheLoop
The loop that we evaluate.
Definition at line 1479 of file LoopVectorize.cpp.
TLI
const TargetLibraryInfo* llvm::LoopVectorizationCostModel::TLI
Target Library Info.
Definition at line 1494 of file LoopVectorize.cpp.
TTI
const TargetTransformInfo& llvm::LoopVectorizationCostModel::TTI
Vector target information.
Definition at line 1491 of file LoopVectorize.cpp.
ValuesToIgnore
SmallPtrSet<const Value *, 16> llvm::LoopVectorizationCostModel::ValuesToIgnore
Values to ignore in the cost model.
Definition at line 1515 of file LoopVectorize.cpp.
VecValuesToIgnore
SmallPtrSet<const Value *, 16> llvm::LoopVectorizationCostModel::VecValuesToIgnore
Values to ignore in the cost model when VF > 1.
Definition at line 1518 of file LoopVectorize.cpp.
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorize.cpp