LLVM: llvm::pdb::NativeEnumGlobals Class Reference
llvm::pdb::NativeEnumGlobals Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeEnumGlobals.h"
Public Member Functions
NativeEnumGlobals (NativeSession &Session, std::vector< codeview::SymbolKind > Kinds)
uint32_t getChildCount () const override
std::unique_ptr< PDBSymbol > getChildAtIndex (uint32_t Index) const override
std::unique_ptr< PDBSymbol > getNext () override
void reset () override
Public Member Functions inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
virtual ~IPDBEnumChildren ()=default
Additional Inherited Members
Public Types inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
using ChildTypePtr = std::unique_ptr< PDBSymbol >
using MyType = IPDBEnumChildren< PDBSymbol >
Detailed Description
Definition at line 23 of file NativeEnumGlobals.h.
Constructor & Destructor Documentation
NativeEnumGlobals()
NativeEnumGlobals::NativeEnumGlobals (NativeSession & Session, std::vector< codeview::SymbolKind > Kinds)
Definition at line 23 of file NativeEnumGlobals.cpp.
References llvm::cantFail(), llvm::pdb::GlobalsStream::getGlobalsTable(), llvm::pdb::NativeSession::getPDBFile(), llvm::pdb::PDBFile::getPDBGlobalsStream(), llvm::pdb::PDBFile::getPDBSymbolStream(), llvm::X86AS::GS, llvm::is_contained(), llvm::codeview::CVRecord< Kind >::kind(), and llvm::X86AS::SS.
Member Function Documentation
getChildAtIndex()
std::unique_ptr< PDBSymbol > NativeEnumGlobals::getChildAtIndex (uint32_t Index) const override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 41 of file NativeEnumGlobals.cpp.
References llvm::pdb::SymbolCache::getOrCreateGlobalSymbolByOffset(), llvm::pdb::SymbolCache::getSymbolById(), and llvm::pdb::NativeSession::getSymbolCache().
Referenced by getNext().
getChildCount()
uint32_t NativeEnumGlobals::getChildCount () const override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 36 of file NativeEnumGlobals.cpp.
getNext()
std::unique_ptr< PDBSymbol > NativeEnumGlobals::getNext () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 50 of file NativeEnumGlobals.cpp.
References getChildAtIndex().
reset()
void NativeEnumGlobals::reset () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 54 of file NativeEnumGlobals.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeEnumGlobals.h
lib/DebugInfo/PDB/Native/NativeEnumGlobals.cpp