LLVM: llvm::MCDwarfLineAddr Class Reference
llvm::MCDwarfLineAddr Class Reference
#include "llvm/MC/MCDwarf.h"
Static Public Member Functions
static void Encode (MCContext &Context, MCDwarfLineTableParams Params, int64_t LineDelta, uint64_t AddrDelta, raw_ostream &OS)
Utility function to encode a Dwarf pair of LineDelta and AddrDeltas.
static bool FixedEncode (MCContext &Context, MCDwarfLineTableParams Params, int64_t LineDelta, uint64_t AddrDelta, raw_ostream &OS, uint32_t *Offset, uint32_t *Size)
Utility function to encode a Dwarf pair of LineDelta and AddrDeltas using fixed length operands.
static void Emit (MCStreamer *MCOS, MCDwarfLineTableParams Params, int64_t LineDelta, uint64_t AddrDelta)
Utility function to emit the encoding to a streamer.
Detailed Description
Definition at line 378 of file MCDwarf.h.
Member Function Documentation
Emit()
void MCDwarfLineAddr::Emit (MCStreamer * MCOS, MCDwarfLineTableParams Params, int64_t LineDelta, uint64_t AddrDelta) static
Utility function to emit the encoding to a streamer.
Definition at line 644 of file MCDwarf.cpp.
References Context, llvm::MCStreamer::EmitBytes(), Encode(), llvm::MCStreamer::getContext(), and llvm::raw_svector_ostream::str().
Referenced by llvm::MCObjectStreamer::EmitDwarfAdvanceLineAddr(), and emitDwarfSetLineAddr().
Encode()
void MCDwarfLineAddr::Encode (MCContext & Context, MCDwarfLineTableParams Params, int64_t LineDelta, uint64_t AddrDelta, raw_ostream & OS) static
Utility function to encode a Dwarf pair of LineDelta and AddrDeltas.
Definition at line 660 of file MCDwarf.cpp.
References assert(), llvm::MCDwarfLineTableParams::DWARF2LineBase, llvm::MCDwarfLineTableParams::DWARF2LineOpcodeBase, llvm::MCDwarfLineTableParams::DWARF2LineRange, llvm::encodeSLEB128(), llvm::encodeULEB128(), if(), INT64_MAX, ScaleAddrDelta(), and SpecialAddr().
Referenced by Emit(), and needPadding().
FixedEncode()
bool MCDwarfLineAddr::FixedEncode (MCContext & Context, MCDwarfLineTableParams Params, int64_t LineDelta, uint64_t AddrDelta, raw_ostream & OS, uint32_t * Offset, uint32_t * Size) static
Utility function to encode a Dwarf pair of LineDelta and AddrDeltas using fixed length operands.
Definition at line 742 of file MCDwarf.cpp.
References llvm::encodeSLEB128(), llvm::encodeULEB128(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), INT64_MAX, llvm::raw_ostream::tell(), and llvm::raw_ostream::write_zeros().
Referenced by needPadding().
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp