LLVM: llvm::yaml::Scanner Class Reference
llvm::yaml::Scanner Class Reference
Scans YAML tokens from a MemoryBuffer.
Public Member Functions
Scanner (StringRef Input, SourceMgr &SM, bool ShowColors=true, std::error_code *EC=nullptr)
Scanner (MemoryBufferRef Buffer, SourceMgr &SM_, bool ShowColors=true, std::error_code *EC=nullptr)
Token & peekNext ()
Parse the next token and return it without popping it.
Token getNext ()
Parse the next token and pop it from the queue.
void printError (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine &Message, ArrayRef< SMRange > Ranges=None)
void setError (const Twine &Message, StringRef::iterator Position)
void setError (const Twine &Message)
bool failed ()
Returns true if an error occurred while parsing.
Detailed Description
Scans YAML tokens from a MemoryBuffer.
Definition at line 252 of file YAMLParser.cpp.
Constructor & Destructor Documentation
Scanner() [1/2]
Scanner::Scanner (StringRef Input, SourceMgr & SM, bool ShowColors = true, std::error_code * EC = nullptr)
Definition at line 756 of file YAMLParser.cpp.
Scanner() [2/2]
Scanner::Scanner (MemoryBufferRef Buffer, SourceMgr & SM_, bool ShowColors = true, std::error_code * EC = nullptr)
Definition at line 762 of file YAMLParser.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), llvm::MemoryBufferRef::getBufferEnd(), llvm::MemoryBufferRef::getBufferStart(), and llvm::MemoryBuffer::getMemBuffer().
Member Function Documentation
failed()
bool llvm::yaml::Scanner::failed () inline
Returns true if an error occurred while parsing.
Definition at line 290 of file YAMLParser.cpp.
References llvm::Failed(), and llvm::cl::init().
getNext()
Token Scanner::getNext ()
Parse the next token and pop it from the queue.
Definition at line 811 of file YAMLParser.cpp.
References llvm::AllocatorList< T, AllocatorT >::empty(), peekNext(), llvm::AllocatorList< T, AllocatorT >::pop_front(), llvm::AllocatorList< T, AllocatorT >::resetAlloc(), and llvm::MipsISD::Ret.
Referenced by llvm::yaml::dumpTokens(), and llvm::yaml::scanTokens().
peekNext()
Token & Scanner::peekNext ()
Parse the next token and return it without popping it.
Definition at line 784 of file YAMLParser.cpp.
References assert(), llvm::AllocatorList< T, AllocatorT >::begin(), llvm::AllocatorList< T, AllocatorT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::AllocatorList< T, AllocatorT >::empty(), llvm::AllocatorList< T, AllocatorT >::front(), llvm::is_contained(), and llvm::AllocatorList< T, AllocatorT >::push_back().
Referenced by getNext().
printError()
void llvm::yaml::Scanner::printError (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine & Message, ArrayRef< SMRange > Ranges = None) inline
Definition at line 265 of file YAMLParser.cpp.
References llvm::None, and llvm::SourceMgr::PrintMessage().
setError() [1/2]
void llvm::yaml::Scanner::setError (const Twine & Message, StringRef::iterator Position) inline
Definition at line 270 of file YAMLParser.cpp.
Referenced by is_ns_word_char().
setError() [2/2]
void llvm::yaml::Scanner::setError (const Twine & Message) inline
Definition at line 285 of file YAMLParser.cpp.
References llvm::yaml::Node::setError().
The documentation for this class was generated from the following file:
lib/Support/YAMLParser.cpp