LLVM: llvm::SMLoc Class Reference
llvm::SMLoc Class Reference
Represents a location in source code.
#include "llvm/Support/SMLoc.h"
Public Member Functions
SMLoc ()=default
bool isValid () const
bool operator== (const SMLoc &RHS) const
bool operator!= (const SMLoc &RHS) const
const char * getPointer () const
Static Public Member Functions
static SMLoc getFromPointer (const char *Ptr)
Detailed Description
Represents a location in source code.
Definition at line 23 of file SMLoc.h.
Constructor & Destructor Documentation
SMLoc()
llvm::SMLoc::SMLoc () default
Member Function Documentation
getFromPointer()
static SMLoc llvm::SMLoc::getFromPointer (const char * Ptr) inline static
Definition at line 36 of file SMLoc.h.
Referenced by addNegOperand(), llvm::FileCheckString::CheckNext(), llvm::FileCheckString::CheckSame(), llvm::X86Operand::CreateToken(), EmitGCCInlineAsmStr(), encodeCnt(), llvm::ErrorDiagnostic::get(), llvm::AsmToken::getEndLoc(), llvm::LLLexer::getLoc(), llvm::AsmToken::getLoc(), llvm::MCAsmLexer::getLoc(), llvm::TGLexer::getLoc(), llvm::SourceMgr::GetMessage(), llvm::FileCheckPatternContext::getPatternVarValue(), incrementLoc(), llvm::MIRParserImpl::initializeJumpTableInfo(), isAltmacroString(), IsIdentifierChar(), matchRegisterNameHelper(), matchSVEPredicateVectorRegName(), llvm::Pattern::parsePattern(), llvm::PrintError(), printMCExpr(), llvm::Pattern::printSubstitutions(), llvm::PrintWarning(), llvm::FileCheck::readCheckFile(), RefineErrorLoc(), llvm::AsmLexer::setBuffer(), shouldBeSls(), and sub().
getPointer()
const char* llvm::SMLoc::getPointer () const inline
Definition at line 34 of file SMLoc.h.
Referenced by addNegOperand(), buildFixItLine(), llvm::X86Operand::CreateToken(), llvm::SourceMgr::FindBufferContainingLoc(), getGNUBinOpPrecedence(), llvm::SourceMgr::getLineAndColumn(), llvm::TGLexer::getLoc(), llvm::SourceMgr::GetMessage(), incrementLoc(), llvm::MIRParserImpl::initializeJumpTableInfo(), isAltmacroString(), isOperator(), isValidEncoding(), matchRegisterNameHelper(), llvm::SMFixIt::operator<(), llvm::SMDiagnostic::print(), printMCExpr(), RefineErrorLoc(), and rewritesSort().
isValid()
bool llvm::SMLoc::isValid () const inline
Definition at line 29 of file SMLoc.h.
Referenced by llvm::SourceMgr::GetMessage(), getPrefixes(), llvm::SMRange::isValid(), parseHexOcta(), llvm::SourceMgr::PrintMessage(), llvm::SMFixIt::SMFixIt(), and llvm::SMRange::SMRange().
operator!=()
bool llvm::SMLoc::operator!= (const SMLoc & RHS) const inline
Definition at line 32 of file SMLoc.h.
operator==()
bool llvm::SMLoc::operator== (const SMLoc & RHS) const inline
Definition at line 31 of file SMLoc.h.
The documentation for this class was generated from the following file:
include/llvm/Support/SMLoc.h