LLVM: llvm::MachObjectWriter Class Reference
llvm::MachObjectWriter Class Reference
#include "llvm/MC/MCMachObjectWriter.h"
Public Member Functions
MachObjectWriter (std::unique_ptr< MCMachObjectTargetWriter > MOTW, raw_pwrite_stream &OS, bool IsLittleEndian)
const MCSymbol & findAliasedSymbol (const MCSymbol &Sym) const
void writeHeader (MachO::HeaderFileType Type, unsigned NumLoadCommands, unsigned LoadCommandsSize, bool SubsectionsViaSymbols)
void writeSegmentLoadCommand (StringRef Name, unsigned NumSections, uint64_t VMAddr, uint64_t VMSize, uint64_t SectionDataStartOffset, uint64_t SectionDataSize, uint32_t MaxProt, uint32_t InitProt)
Write a segment load command.
void writeSection (const MCAsmLayout &Layout, const MCSection &Sec, uint64_t VMAddr, uint64_t FileOffset, unsigned Flags, uint64_t RelocationsStart, unsigned NumRelocations)
void writeSymtabLoadCommand (uint32_t SymbolOffset, uint32_t NumSymbols, uint32_t StringTableOffset, uint32_t StringTableSize)
void writeDysymtabLoadCommand (uint32_t FirstLocalSymbol, uint32_t NumLocalSymbols, uint32_t FirstExternalSymbol, uint32_t NumExternalSymbols, uint32_t FirstUndefinedSymbol, uint32_t NumUndefinedSymbols, uint32_t IndirectSymbolOffset, uint32_t NumIndirectSymbols)
void writeNlist (MachSymbolData &MSD, const MCAsmLayout &Layout)
void writeLinkeditLoadCommand (uint32_t Type, uint32_t DataOffset, uint32_t DataSize)
void writeLinkerOptionsLoadCommand (const std::vector< std::string > &Options)
void addRelocation (const MCSymbol *RelSymbol, const MCSection *Sec, MachO::any_relocation_info &MRE)
void recordScatteredRelocation (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, unsigned Log2Size, uint64_t &FixedValue)
void recordTLVPRelocation (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, uint64_t &FixedValue)
void recordRelocation (MCAssembler &Asm, const MCAsmLayout &Layout, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, uint64_t &FixedValue) override
Record a relocation entry.
void bindIndirectSymbols (MCAssembler &Asm)
void computeSymbolTable (MCAssembler &Asm, std::vector< MachSymbolData > &LocalSymbolData, std::vector< MachSymbolData > &ExternalSymbolData, std::vector< MachSymbolData > &UndefinedSymbolData)
Compute the symbol table data.
void computeSectionAddresses (const MCAssembler &Asm, const MCAsmLayout &Layout)
void executePostLayoutBinding (MCAssembler &Asm, const MCAsmLayout &Layout) override
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
bool isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler &Asm, const MCSymbol &A, const MCSymbol &B, bool InSet) const override
bool isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler &Asm, const MCSymbol &SymA, const MCFragment &FB, bool InSet, bool IsPCRel) const override
uint64_t writeObject (MCAssembler &Asm, const MCAsmLayout &Layout) override
Write the object file and returns the number of bytes written.
Lifetime management Methods
void reset () override
lifetime management
Utility Methods
bool isFixupKindPCRel (const MCAssembler &Asm, unsigned Kind)
SectionAddrMap & getSectionAddressMap ()
uint64_t getSectionAddress (const MCSection *Sec) const
uint64_t getSymbolAddress (const MCSymbol &S, const MCAsmLayout &Layout) const
uint64_t getFragmentAddress (const MCFragment *Fragment, const MCAsmLayout &Layout) const
uint64_t getPaddingSize (const MCSection *SD, const MCAsmLayout &Layout) const
bool doesSymbolRequireExternRelocation (const MCSymbol &S)
Target Writer Proxy Accessors
bool is64Bit () const
bool isX86_64 () const
Public Member Functions inherited from llvm::MCObjectWriter
MCObjectWriter (const MCObjectWriter &)=delete
MCObjectWriter & operator= (const MCObjectWriter &)=delete
virtual ~MCObjectWriter ()
bool isSymbolRefDifferenceFullyResolved (const MCAssembler &Asm, const MCSymbolRefExpr *A, const MCSymbolRefExpr *B, bool InSet) const
Check whether the difference (A - B) between two symbol references is fully resolved.
virtual void emitAddrsigSection ()
Tell the object writer to emit an address-significance table during writeObject().
virtual void addAddrsigSymbol (const MCSymbol *Sym)
Record the given symbol in the address-significance table to be written diring writeObject().
Public Attributes
support::endian::Writer W
Additional Inherited Members
Protected Member Functions inherited from llvm::MCObjectWriter
MCObjectWriter ()=default
Detailed Description
Definition at line 83 of file MCMachObjectWriter.h.
Constructor & Destructor Documentation
MachObjectWriter()
llvm::MachObjectWriter::MachObjectWriter (std::unique_ptr< MCMachObjectTargetWriter > MOTW, raw_pwrite_stream & OS, bool IsLittleEndian) inline
Definition at line 128 of file MCMachObjectWriter.h.
Member Function Documentation
addRelocation()
void llvm::MachObjectWriter::addRelocation (const MCSymbol * RelSymbol, const MCSection * Sec, MachO::any_relocation_info & MRE) inline
Definition at line 229 of file MCMachObjectWriter.h.
References llvm::HexStyle::Asm, B, llvm::createMachObjectWriter(), Fixup, P, and llvm::MCMachObjectTargetWriter::recordRelocation().
Referenced by canUseLocalRelocation(), getARMFixupKindMachOInfo(), getFixupKindLog2Size(), and getFixupOffset().
bindIndirectSymbols()
void MachObjectWriter::bindIndirectSymbols (MCAssembler & Asm)
Definition at line 477 of file MachObjectWriter.cpp.
References llvm::MCSymbol::getName(), llvm::MCSectionMachO::getType(), llvm::MCAssembler::indirect_symbol_begin(), llvm::MCAssembler::indirect_symbol_end(), llvm::MCAssembler::registerSymbol(), llvm::report_fatal_error(), llvm::MachO::S_LAZY_SYMBOL_POINTERS, llvm::MachO::S_NON_LAZY_SYMBOL_POINTERS, llvm::MachO::S_SYMBOL_STUBS, llvm::MachO::S_THREAD_LOCAL_VARIABLE_POINTERS, llvm::ARMBuildAttrs::Section, and llvm::ARMBuildAttrs::Symbol.
Referenced by executePostLayoutBinding().
computeSectionAddresses()
void MachObjectWriter::computeSectionAddresses (const MCAssembler & Asm, const MCAsmLayout & Layout)
strictly be necessary.
Definition at line 642 of file MachObjectWriter.cpp.
References llvm::alignTo(), getPaddingSize(), llvm::MCAsmLayout::getSectionAddressSize(), and llvm::MCAsmLayout::getSectionOrder().
Referenced by executePostLayoutBinding().
computeSymbolTable()
void MachObjectWriter::computeSymbolTable (MCAssembler & Asm, std::vector< MachSymbolData > & LocalSymbolData, std::vector< MachSymbolData > & ExternalSymbolData, std::vector< MachSymbolData > & UndefinedSymbolData)
Compute the symbol table data.
computeSymbolTable - Compute the symbol table data
Definition at line 541 of file MachObjectWriter.cpp.
References llvm::StringTableBuilder::add(), assert(), llvm::MCAssembler::begin(), llvm::MCAssembler::end(), llvm::support::endian::Writer::Endian, llvm::StringTableBuilder::finalize(), llvm::StringTableBuilder::getOffset(), llvm::MCAssembler::isSymbolLinkerVisible(), llvm::support::little, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::ARMBuildAttrs::Section, llvm::sort(), llvm::ARMBuildAttrs::Symbol, llvm::MCAssembler::symbols(), and W.
Referenced by writeObject().
doesSymbolRequireExternRelocation()
bool MachObjectWriter::doesSymbolRequireExternRelocation (const MCSymbol & S)
Definition at line 55 of file MachObjectWriter.cpp.
References llvm::MCSymbol::isUndefined(), operator<(), and llvm::ARMBuildAttrs::Symbol.
Referenced by getARMFixupKindMachOInfo(), getFixupKindLog2Size(), and getFixupOffset().
executePostLayoutBinding()
void MachObjectWriter::executePostLayoutBinding (MCAssembler & Asm, const MCAsmLayout & Layout) override virtual
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
This routine is called by the assembler after layout and relaxation is complete.
Implements llvm::MCObjectWriter.
Definition at line 657 of file MachObjectWriter.cpp.
References bindIndirectSymbols(), and computeSectionAddresses().
findAliasedSymbol()
const MCSymbol & MachObjectWriter::findAliasedSymbol (const MCSymbol & Sym) const
Definition at line 326 of file MachObjectWriter.cpp.
References llvm::dyn_cast(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isVariable(), and llvm::Ref.
Referenced by getFixupKindLog2Size(), isSymbolRefDifferenceFullyResolvedImpl(), and writeNlist().
getFragmentAddress()
uint64_t MachObjectWriter::getFragmentAddress (const MCFragment * Fragment, const MCAsmLayout & Layout) const
Definition at line 81 of file MachObjectWriter.cpp.
References llvm::MCAsmLayout::getFragmentOffset(), llvm::MCFragment::getParent(), and getSectionAddress().
Referenced by canUseLocalRelocation(), and getFixupKindLog2Size().
getPaddingSize()
uint64_t MachObjectWriter::getPaddingSize (const MCSection * SD, const MCAsmLayout & Layout) const
Definition at line 120 of file MachObjectWriter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::MCSection::getAlignment(), llvm::MCSection::getLayoutOrder(), getSectionAddress(), llvm::MCAsmLayout::getSectionAddressSize(), llvm::MCAsmLayout::getSectionOrder(), llvm::MCSection::isVirtualSection(), and llvm::offsetToAlignment().
Referenced by computeSectionAddresses(), and writeObject().
getSectionAddress()
uint64_t llvm::MachObjectWriter::getSectionAddress (const MCSection * Sec) const inline
Definition at line 151 of file MCMachObjectWriter.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by getARMFixupKindMachOInfo(), getFixupKindLog2Size(), getFixupOffset(), getFragmentAddress(), getPaddingSize(), getSymbolAddress(), and writeObject().
getSectionAddressMap()
SectionAddrMap& llvm::MachObjectWriter::getSectionAddressMap () inline
Definition at line 149 of file MCMachObjectWriter.h.
Referenced by getARMFixupKindMachOInfo(), getFixupKindLog2Size(), and getFixupOffset().
getSymbolAddress()
uint64_t MachObjectWriter::getSymbolAddress (const MCSymbol & S, const MCAsmLayout & Layout) const
Definition at line 87 of file MachObjectWriter.cpp.
References llvm::Address, C, llvm::MCExpr::evaluateAsRelocatable(), llvm::MCValue::getConstant(), llvm::MCSymbol::getFragment(), llvm::MCSymbol::getName(), llvm::MCFragment::getParent(), getSectionAddress(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isUndefined(), llvm::MCSymbol::isVariable(), and llvm::report_fatal_error().
Referenced by canUseLocalRelocation(), getARMFixupKindMachOInfo(), getFixupKindLog2Size(), getFixupOffset(), and writeNlist().
is64Bit()
bool llvm::MachObjectWriter::is64Bit () const inline
Definition at line 168 of file MCMachObjectWriter.h.
Referenced by writeLinkerOptionsLoadCommand(), writeNlist(), and writeObject().
isFixupKindPCRel()
bool MachObjectWriter::isFixupKindPCRel (const MCAssembler & Asm, unsigned Kind)
Definition at line 74 of file MachObjectWriter.cpp.
References llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCFixupKindInfo::Flags, llvm::MCAssembler::getBackend(), and llvm::MCAsmBackend::getFixupKindInfo().
Referenced by canUseLocalRelocation(), getARMFixupKindMachOInfo(), getFixupKindLog2Size(), and getFixupOffset().
isSymbolRefDifferenceFullyResolvedImpl() [1/2]
bool MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler & Asm, const MCSymbol & A, const MCSymbol & B, bool InSet) const override virtual
Reimplemented from llvm::MCObjectWriter.
Definition at line 665 of file MachObjectWriter.cpp.
References llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), and llvm::MCSymbol::isVariable().
isSymbolRefDifferenceFullyResolvedImpl() [2/2]
bool MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler & Asm, const MCSymbol & SymA, const MCFragment & FB, bool InSet, bool IsPCRel) const override virtual
Reimplemented from llvm::MCObjectWriter.
Definition at line 677 of file MachObjectWriter.cpp.
References findAliasedSymbol(), llvm::MCFragment::getAtom(), llvm::MCSymbol::getFragment(), llvm::MCFragment::getParent(), llvm::MCSymbol::getSection(), llvm::MCAssembler::getSubsectionsViaSymbols(), llvm::MCSymbol::isInSection(), llvm::MCSymbol::isTemporary(), and isX86_64().
isX86_64()
bool llvm::MachObjectWriter::isX86_64 () const inline
Definition at line 169 of file MCMachObjectWriter.h.
References llvm::MachO::CPU_TYPE_X86_64, and Name.
Referenced by isSymbolRefDifferenceFullyResolvedImpl().
recordRelocation()
void MachObjectWriter::recordRelocation (MCAssembler & Asm, const MCAsmLayout & Layout, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, uint64_t & FixedValue) override virtual
Record a relocation entry.
This routine is called by the assembler after layout and relaxation, and post layout binding. The implementation is responsible for storing information about the relocation so that it can be emitted during writeObject().
Implements llvm::MCObjectWriter.
Definition at line 462 of file MachObjectWriter.cpp.
References llvm::MCAssembler::getContext(), llvm::MCFixup::getLoc(), isFixupTargetValid(), and llvm::MCContext::reportError().
recordScatteredRelocation()
void llvm::MachObjectWriter::recordScatteredRelocation (const MCAssembler & Asm, const MCAsmLayout & Layout, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, unsigned Log2Size, uint64_t & FixedValue)
recordTLVPRelocation()
void llvm::MachObjectWriter::recordTLVPRelocation (const MCAssembler & Asm, const MCAsmLayout & Layout, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, uint64_t & FixedValue)
reset()
void MachObjectWriter::reset () override virtual
lifetime management
Reimplemented from llvm::MCObjectWriter.
Definition at line 45 of file MachObjectWriter.cpp.
References llvm::StringTableBuilder::clear(), and llvm::MCObjectWriter::reset().
writeDysymtabLoadCommand()
void MachObjectWriter::writeDysymtabLoadCommand (uint32_t FirstLocalSymbol, uint32_t NumLocalSymbols, uint32_t FirstExternalSymbol, uint32_t NumExternalSymbols, uint32_t FirstUndefinedSymbol, uint32_t NumUndefinedSymbols, uint32_t IndirectSymbolOffset, uint32_t NumIndirectSymbols)
Definition at line 278 of file MachObjectWriter.cpp.
Referenced by writeObject().
writeHeader()
void MachObjectWriter::writeHeader (MachO::HeaderFileType Type, unsigned NumLoadCommands, unsigned LoadCommandsSize, bool SubsectionsViaSymbols)
Definition at line 133 of file MachObjectWriter.cpp.
References llvm::MachO::MH_SUBSECTIONS_VIA_SYMBOLS.
Referenced by writeObject().
writeLinkeditLoadCommand()
void MachObjectWriter::writeLinkeditLoadCommand (uint32_t Type, uint32_t DataOffset, uint32_t DataSize)
Definition at line 407 of file MachObjectWriter.cpp.
Referenced by writeObject().
writeLinkerOptionsLoadCommand()
void MachObjectWriter::writeLinkerOptionsLoadCommand (const std::vector< std::string > & Options)
Definition at line 430 of file MachObjectWriter.cpp.
References ComputeLinkerOptionsLoadCommandSize(), is64Bit(), and Size.
Referenced by writeObject().
writeNlist()
void MachObjectWriter::writeNlist (MachSymbolData & MSD, const MCAsmLayout & Layout)
Definition at line 338 of file MachObjectWriter.cpp.
References llvm::Address, llvm::Data, findAliasedSymbol(), llvm::MCSymbol::getCommonSize(), getSymbolAddress(), if(), is64Bit(), llvm::MCSymbol::isAbsolute(), llvm::MCSymbol::isCommon(), llvm::MCSymbol::isDefined(), llvm::MCSymbol::isExternal(), llvm::MCSymbol::isPrivateExtern(), llvm::MCSymbol::isUndefined(), llvm::MachO::N_ABS, llvm::MachO::N_EXT, llvm::MachO::N_INDR, llvm::MachO::N_PEXT, llvm::MachO::N_SECT, llvm::MachO::N_UNDF, llvm::support::endian::Writer::OS, llvm::ARMBuildAttrs::Symbol, W, and llvm::support::endian::Writer::write().
writeObject()
uint64_t MachObjectWriter::writeObject (MCAssembler & Asm, const MCAsmLayout & Layout) override virtual
Write the object file and returns the number of bytes written.
This routine is called by the assembler after layout and relaxation is complete, fixups have been evaluated and applied, and relocations generated.
Implements llvm::MCObjectWriter.
Definition at line 754 of file MachObjectWriter.cpp.
References llvm::Address, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::alignTo(), assert(), ComputeLinkerOptionsLoadCommandSize(), computeSymbolTable(), llvm::Data, llvm::MCAsmLayout::getAssembler(), llvm::MCAssembler::getDataRegions(), llvm::MCLOHContainer::getEmitSize(), getLCFromMCVM(), llvm::MCAssembler::getLinkerOptions(), llvm::MCAssembler::getLOHContainer(), getPaddingSize(), getSectionAddress(), llvm::MCAsmLayout::getSectionAddressSize(), llvm::MCAsmLayout::getSectionFileSize(), llvm::StringTableBuilder::getSize(), llvm::MCAssembler::getVersionInfo(), is64Bit(), llvm::make_range(), llvm::max(), llvm::MachO::MH_OBJECT, llvm::offsetToAlignment(), llvm::support::endian::Writer::OS, llvm::MachO::S_ATTR_SOME_INSTRUCTIONS, llvm::ARMBuildAttrs::Section, Size, llvm::MCAssembler::size(), llvm::raw_ostream::tell(), llvm::MachO::VM_PROT_EXECUTE, llvm::MachO::VM_PROT_READ, llvm::MachO::VM_PROT_WRITE, W, llvm::support::endian::Writer::write(), llvm::raw_ostream::write_zeros(), writeDysymtabLoadCommand(), writeHeader(), writeLinkeditLoadCommand(), writeLinkerOptionsLoadCommand(), writeSection(), writeSegmentLoadCommand(), and writeSymtabLoadCommand().
writeSection()
void MachObjectWriter::writeSection (const MCAsmLayout & Layout, const MCSection & Sec, uint64_t VMAddr, uint64_t FileOffset, unsigned Flags, uint64_t RelocationsStart, unsigned NumRelocations)
Definition at line 214 of file MachObjectWriter.cpp.
References assert(), llvm::MCAsmLayout::getSectionAddressSize(), llvm::MCAsmLayout::getSectionFileSize(), llvm::MCSectionMachO::isVirtualSection(), llvm::ARMBuildAttrs::Section, and llvm::COFF::SectionSize.
Referenced by writeObject().
writeSegmentLoadCommand()
void MachObjectWriter::writeSegmentLoadCommand (StringRef Name, unsigned NumSections, uint64_t VMAddr, uint64_t VMSize, uint64_t SectionDataStartOffset, uint64_t SectionDataSize, uint32_t MaxProt, uint32_t InitProt)
Write a segment load command.
writeSegmentLoadCommand - Write a segment load command.
Parameters
NumSections The number of sections in this segment.
SectionDataSize The total size of the sections.
Definition at line 174 of file MachObjectWriter.cpp.
Referenced by writeObject().
writeSymtabLoadCommand()
void MachObjectWriter::writeSymtabLoadCommand (uint32_t SymbolOffset, uint32_t NumSymbols, uint32_t StringTableOffset, uint32_t StringTableSize)
Definition at line 259 of file MachObjectWriter.cpp.
Referenced by writeObject().
Member Data Documentation
W
support::endian::Writer llvm::MachObjectWriter::W
Definition at line 133 of file MCMachObjectWriter.h.
Referenced by computeSymbolTable(), llvm::MCLOHDirective::emit(), writeNlist(), and writeObject().
The documentation for this class was generated from the following files:
include/llvm/MC/MCMachObjectWriter.h
lib/MC/MachObjectWriter.cpp