LLVM: DbgValueLocation Class Reference
DbgValueLocation Class Reference
Describes a location by number along with some flags about the original usage of the location.
Public Member Functions
DbgValueLocation (unsigned LocNo, bool WasIndirect)
DbgValueLocation ()
unsigned locNo () const
bool wasIndirect () const
bool isUndef () const
DbgValueLocation changeLocNo (unsigned NewLocNo) const
Friends
bool operator== (const DbgValueLocation &LHS, const DbgValueLocation &RHS)
bool operator!= (const DbgValueLocation &LHS, const DbgValueLocation &RHS)
Detailed Description
Describes a location by number along with some flags about the original usage of the location.
Definition at line 101 of file LiveDebugVariables.cpp.
Constructor & Destructor Documentation
DbgValueLocation() [1/2]
DbgValueLocation::DbgValueLocation (unsigned LocNo, bool WasIndirect) inline
Definition at line 103 of file LiveDebugVariables.cpp.
References assert().
DbgValueLocation() [2/2]
DbgValueLocation::DbgValueLocation () inline
Definition at line 109 of file LiveDebugVariables.cpp.
Member Function Documentation
changeLocNo()
DbgValueLocation DbgValueLocation::changeLocNo (unsigned NewLocNo) const inline
Definition at line 118 of file LiveDebugVariables.cpp.
Referenced by llvm::LiveDebugVariables::splitRegister(), and llvm::LiveDebugVariables::~LiveDebugVariables().
isUndef()
bool DbgValueLocation::isUndef () const inline
Definition at line 116 of file LiveDebugVariables.cpp.
References UndefLocNo.
Referenced by findNextInsertLocation(), and llvm::LiveDebugVariables::splitRegister().
locNo()
unsigned DbgValueLocation::locNo () const inline
Definition at line 111 of file LiveDebugVariables.cpp.
References UndefLocNo.
Referenced by findNextInsertLocation(), and llvm::LiveDebugVariables::splitRegister().
wasIndirect()
bool DbgValueLocation::wasIndirect () const inline
Definition at line 115 of file LiveDebugVariables.cpp.
Referenced by findNextInsertLocation().
Friends And Related Function Documentation
operator!=
bool operator!= (const DbgValueLocation & LHS, const DbgValueLocation & RHS) friend
Definition at line 127 of file LiveDebugVariables.cpp.
operator==
bool operator== (const DbgValueLocation & LHS, const DbgValueLocation & RHS) friend
Definition at line 122 of file LiveDebugVariables.cpp.
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugVariables.cpp