LLVM: llvm::MSP430MCCodeEmitter Class Reference
llvm::MSP430MCCodeEmitter Class Reference
Public Member Functions
MSP430MCCodeEmitter (MCContext &ctx, MCInstrInfo const &MCII)
void encodeInstruction (const MCInst &MI, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const override
EncodeInstruction - Encode the given Inst to bytes on the output stream OS.
Public Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter (const MCCodeEmitter &)=delete
MCCodeEmitter & operator= (const MCCodeEmitter &)=delete
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
virtual void emitPrefix (const MCInst &Inst, raw_ostream &OS, const MCSubtargetInfo &STI) const
Emit the prefixes of given instruction on the output stream.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Detailed Description
Definition at line 35 of file MSP430MCCodeEmitter.cpp.
Constructor & Destructor Documentation
MSP430MCCodeEmitter()
llvm::MSP430MCCodeEmitter::MSP430MCCodeEmitter (MCContext & ctx, MCInstrInfo const & MCII) inline
Definition at line 74 of file MSP430MCCodeEmitter.cpp.
References encodeInstruction().
Referenced by llvm::createMSP430MCCodeEmitter().
Member Function Documentation
encodeInstruction()
void llvm::MSP430MCCodeEmitter::encodeInstruction (const MCInst & Inst, raw_ostream & OS, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const override virtual
EncodeInstruction - Encode the given Inst to bytes on the output stream OS.
Implements llvm::MCCodeEmitter.
Definition at line 82 of file MSP430MCCodeEmitter.cpp.
References assert(), MSP430CC::COND_E, MSP430CC::COND_GE, MSP430CC::COND_HS, MSP430CC::COND_L, MSP430CC::COND_LO, MSP430CC::COND_N, MSP430CC::COND_NE, llvm::MCFixup::create(), llvm::MSP430::fixup_10_pcrel, llvm::MSP430::fixup_16_byte, llvm::MSP430::fixup_16_pcrel_byte, llvm::FixupKind(), llvm::MCInstrInfo::get(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getLoc(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCContext::getRegisterInfo(), llvm::MCInstrDesc::getSize(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::support::little, llvm_unreachable, MI, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, Size, and llvm::support::endian::write().
Referenced by MSP430MCCodeEmitter().
The documentation for this class was generated from the following file:
lib/Target/MSP430/MCTargetDesc/MSP430MCCodeEmitter.cpp