LLVM: llvm::pdb::DIADataStream Class Reference
llvm::pdb::DIADataStream Class Reference
#include "llvm/DebugInfo/PDB/DIA/DIADataStream.h"
Public Member Functions
DIADataStream (CComPtr< IDiaEnumDebugStreamData > DiaStreamData)
uint32_t getRecordCount () const override
std::string getName () const override
llvm::Optional< RecordType > getItemAtIndex (uint32_t Index) const override
bool getNext (RecordType &Record) override
void reset () override
Public Member Functions inherited from llvm::pdb::IPDBDataStream
virtual ~IPDBDataStream ()
Additional Inherited Members
Public Types inherited from llvm::pdb::IPDBDataStream
using RecordType = SmallVector< uint8_t, 32 >
Detailed Description
Definition at line 17 of file DIADataStream.h.
Constructor & Destructor Documentation
DIADataStream()
DIADataStream::DIADataStream (CComPtr< IDiaEnumDebugStreamData > DiaStreamData) explicit
Definition at line 15 of file DIADataStream.cpp.
Member Function Documentation
getItemAtIndex()
llvm::Optional< DIADataStream::RecordType > DIADataStream::getItemAtIndex (uint32_t Index) const override virtual
Implements llvm::pdb::IPDBDataStream.
Definition at line 28 of file DIADataStream.cpp.
References llvm::AMDGPU::SDWA::DWORD, and llvm::SmallVectorImpl< T >::resize().
getName()
std::string DIADataStream::getName () const override virtual
Implements llvm::pdb::IPDBDataStream.
Definition at line 23 of file DIADataStream.cpp.
References invokeBstrMethod().
getNext()
bool DIADataStream::getNext (RecordType & Record) override virtual
Implements llvm::pdb::IPDBDataStream.
Definition at line 41 of file DIADataStream.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::AMDGPU::SDWA::DWORD, and llvm::SmallVectorImpl< T >::resize().
getRecordCount()
uint32_t DIADataStream::getRecordCount () const override virtual
Implements llvm::pdb::IPDBDataStream.
Definition at line 18 of file DIADataStream.cpp.
reset()
void DIADataStream::reset () override virtual
Implements llvm::pdb::IPDBDataStream.
Definition at line 56 of file DIADataStream.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/DIA/DIADataStream.h
lib/DebugInfo/PDB/DIA/DIADataStream.cpp