LLVM: llvm::DWARFDebugNames Class Reference
llvm::DWARFDebugNames Class Reference
.debug_names section consists of one or more units.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Classes
struct Abbrev
Abbreviation describing the encoding of Name Index entries.
struct AttributeEncoding
Index attribute and its encoding.
class Entry
DWARF v5-specific implementation of an Accelerator Entry.
struct Header
DWARF v5 Name Index header.
class NameIndex
Represents a single accelerator table within the DWARF v5 .debug_names section.
class NameIterator
class NameTableEntry
A single entry in the Name Table (DWARF v5 sect.
class SentinelError
Error returned by NameIndex::getEntry to report it has reached the end of the entry list.
class ValueIterator
Public Types
using const_iterator = SmallVector< NameIndex, 0 >::const_iterator
Public Member Functions
DWARFDebugNames (const DWARFDataExtractor &AccelSection, DataExtractor StringSection)
Error extract () override
void dump (raw_ostream &OS) const override
iterator_range< ValueIterator > equal_range (StringRef Key) const
Look up all entries in the accelerator table matching Key.
const_iterator begin () const
const_iterator end () const
const NameIndex * getCUNameIndex (uint64_t CUOffset)
Return the Name Index covering the compile unit at CUOffset, or nullptr if there is no Name Index covering that unit.
Public Member Functions inherited from llvm::DWARFAcceleratorTable
DWARFAcceleratorTable (const DWARFDataExtractor &AccelSection, DataExtractor StringSection)
virtual ~DWARFAcceleratorTable ()
DWARFAcceleratorTable (const DWARFAcceleratorTable &)=delete
void operator= (const DWARFAcceleratorTable &)=delete
Additional Inherited Members
Protected Attributes inherited from llvm::DWARFAcceleratorTable
DWARFDataExtractor AccelSection
DataExtractor StringSection
Detailed Description
.debug_names section consists of one or more units.
Each unit starts with a header, which is followed by a list of compilation units, local and foreign type units.
These may be followed by an (optional) hash lookup table, which consists of an array of buckets and hashes similar to the apple tables above. The only difference is that the hashes array is 1-based, and consequently an empty bucket is denoted by 0 and not UINT32_MAX.
Next is the name table, which consists of an array of names and array of entry offsets. This is different from the apple tables, which store names next to the actual entries.
The structure of the entries is described by an abbreviations table, which comes after the name table. Unlike the apple tables, which have a uniform entry structure described in the header, each .debug_names entry may have different index attributes (DW_IDX_???) attached to it.
The last segment consists of a list of entries, which is a 0-terminated list referenced by the name table and interpreted with the help of the abbreviation table.
Definition at line 224 of file DWARFAcceleratorTable.h.
Member Typedef Documentation
const_iterator
using llvm::DWARFDebugNames::const_iterator = SmallVector<NameIndex, 0>::const_iterator
Definition at line 588 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
DWARFDebugNames()
llvm::DWARFDebugNames::DWARFDebugNames (const DWARFDataExtractor & AccelSection, DataExtractor StringSection) inline
Definition at line 578 of file DWARFAcceleratorTable.h.
References llvm::DWARFAcceleratorTable::dump(), and llvm::DWARFAcceleratorTable::extract().
Member Function Documentation
begin()
const_iterator llvm::DWARFDebugNames::begin () const inline
Definition at line 589 of file DWARFAcceleratorTable.h.
References llvm::SmallVectorTemplateCommon< T >::begin().
dump()
LLVM_DUMP_METHOD void DWARFDebugNames::dump (raw_ostream & OS) const override virtual
Implements llvm::DWARFAcceleratorTable.
Definition at line 776 of file DWARFAcceleratorTable.cpp.
References llvm::caseFoldingDjbHash(), llvm::consumeError(), llvm::DWARFDebugNames::NameTableEntry::getEntryOffset(), llvm::DWARFDebugNames::NameTableEntry::getString(), llvm::None, and llvm::RISCVFenceField::W.
Referenced by llvm::DWARFContext::dump().
end()
const_iterator llvm::DWARFDebugNames::end () const inline
Definition at line 590 of file DWARFAcceleratorTable.h.
References llvm::SmallVectorTemplateCommon< T >::end().
equal_range()
iterator_range< DWARFDebugNames::ValueIterator > DWARFDebugNames::equal_range (StringRef Key) const
Look up all entries in the accelerator table matching Key.
Definition at line 874 of file DWARFAcceleratorTable.cpp.
References llvm::make_range(), and llvm::DWARFDebugNames::ValueIterator::ValueIterator().
extract()
Error DWARFDebugNames::extract () override virtual
Implements llvm::DWARFAcceleratorTable.
Definition at line 759 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFAcceleratorTable::AccelSection, E, llvm::DWARFDebugNames::NameIndex::extract(), llvm::DWARFDebugNames::NameIndex::getNextUnitOffset(), llvm::DataExtractor::isValidOffset(), and llvm::Error::success().
getCUNameIndex()
const DWARFDebugNames::NameIndex * DWARFDebugNames::getCUNameIndex (uint64_t CUOffset)
Return the Name Index covering the compile unit at CUOffset, or nullptr if there is no Name Index covering that unit.
Definition at line 881 of file DWARFAcceleratorTable.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp