LLVM: llvm::SCEVPredicate Class Reference
llvm::SCEVPredicate Class Reference abstract
This class represents an assumption made using SCEV expressions which can be checked at run-time.
#include "llvm/Analysis/ScalarEvolution.h"
Public Types
enum SCEVPredicateKind { P_Union, P_Equal, P_Wrap }
Public Member Functions
SCEVPredicate (const FoldingSetNodeIDRef ID, SCEVPredicateKind Kind)
SCEV predicates.
SCEVPredicateKind getKind () const
virtual unsigned getComplexity () const
Returns the estimated complexity of this predicate.
virtual bool isAlwaysTrue () const =0
Returns true if the predicate is always true.
virtual bool implies (const SCEVPredicate *N) const =0
Returns true if this predicate implies N.
virtual void print (raw_ostream &OS, unsigned Depth=0) const =0
Prints a textual representation of this predicate with an indentation of Depth.
virtual const SCEV * getExpr () const =0
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Protected Member Functions
~SCEVPredicate ()=default
SCEVPredicate (const SCEVPredicate &)=default
SCEVPredicate & operator= (const SCEVPredicate &)=default
Protected Attributes
SCEVPredicateKind Kind
Friends
struct FoldingSetTrait< SCEVPredicate >
Detailed Description
This class represents an assumption made using SCEV expressions which can be checked at run-time.
Definition at line 198 of file ScalarEvolution.h.
Member Enumeration Documentation
SCEVPredicateKind
enum llvm::SCEVPredicate::SCEVPredicateKind
Enumerator
P_Union
P_Equal
P_Wrap
Definition at line 206 of file ScalarEvolution.h.
Constructor & Destructor Documentation
~SCEVPredicate()
llvm::SCEVPredicate::~SCEVPredicate () protected default
SCEVPredicate() [1/2]
llvm::SCEVPredicate::SCEVPredicate (const SCEVPredicate &) protected default
SCEVPredicate() [2/2]
SCEVPredicate::SCEVPredicate (const FoldingSetNodeIDRef ID, SCEVPredicateKind Kind)
SCEV predicates.
Definition at line 12310 of file ScalarEvolution.cpp.
Member Function Documentation
getComplexity()
virtual unsigned llvm::SCEVPredicate::getComplexity () const inline virtual
Returns the estimated complexity of this predicate.
This is roughly measured in the number of run-time checks required.
Reimplemented in llvm::SCEVUnionPredicate.
Definition at line 221 of file ScalarEvolution.h.
References llvm::Depth, llvm::HexagonMCInstrInfo::getExpr(), N, and llvm::SCEV::print().
getExpr()
virtual const SCEV* llvm::SCEVPredicate::getExpr () const pure virtual
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
Implemented in llvm::SCEVUnionPredicate, llvm::SCEVWrapPredicate, and llvm::SCEVEqualPredicate.
Referenced by llvm::SCEVUnionPredicate::add(), and llvm::SCEVUnionPredicate::implies().
getKind()
SCEVPredicateKind llvm::SCEVPredicate::getKind () const inline
Definition at line 217 of file ScalarEvolution.h.
Referenced by llvm::SCEVEqualPredicate::classof(), llvm::SCEVWrapPredicate::classof(), llvm::SCEVUnionPredicate::classof(), and llvm::SCEVExpander::expandCodeForPredicate().
implies()
virtual bool llvm::SCEVPredicate::implies (const SCEVPredicate * N) const pure virtual
Returns true if this predicate implies N.
Implemented in llvm::SCEVUnionPredicate, llvm::SCEVWrapPredicate, and llvm::SCEVEqualPredicate.
Referenced by llvm::SCEVUnionPredicate::implies().
isAlwaysTrue()
virtual bool llvm::SCEVPredicate::isAlwaysTrue () const pure virtual
Returns true if the predicate is always true.
This means that no assumptions were made and nothing needs to be checked at run-time.
Implemented in llvm::SCEVUnionPredicate, llvm::SCEVWrapPredicate, and llvm::SCEVEqualPredicate.
Referenced by llvm::SCEVUnionPredicate::isAlwaysTrue().
operator=()
SCEVPredicate& llvm::SCEVPredicate::operator= (const SCEVPredicate &) protected default
print()
virtual void llvm::SCEVPredicate::print (raw_ostream & OS, unsigned Depth = 0) const pure virtual
Prints a textual representation of this predicate with an indentation of Depth.
Implemented in llvm::SCEVUnionPredicate, llvm::SCEVWrapPredicate, and llvm::SCEVEqualPredicate.
Referenced by llvm::operator<<().
Friends And Related Function Documentation
FoldingSetTrait< SCEVPredicate >
friend struct FoldingSetTrait< SCEVPredicate > friend
Definition at line 199 of file ScalarEvolution.h.
Member Data Documentation
Kind
SCEVPredicateKind llvm::SCEVPredicate::Kind protected
Definition at line 209 of file ScalarEvolution.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolution.h
lib/Analysis/ScalarEvolution.cpp