LLVM: llvm::InitLLVM Class Reference
llvm::InitLLVM Class Reference
#include "llvm/Support/InitLLVM.h"
Public Member Functions
InitLLVM (int &Argc, const char **&Argv, bool InstallPipeSignalExitHandler=true)
InitLLVM (int &Argc, char **&Argv, bool InstallPipeSignalExitHandler=true)
~InitLLVM ()
Detailed Description
Definition at line 34 of file InitLLVM.h.
Constructor & Destructor Documentation
InitLLVM() [1/2]
InitLLVM::InitLLVM (int & Argc, const char **& Argv, bool InstallPipeSignalExitHandler = true)
Definition at line 24 of file InitLLVM.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::sys::DefaultOneShotPipeSignalHandler(), llvm::errorCodeToError(), llvm::sys::windows::GetCommandLineArguments(), llvm::install_out_of_memory_new_handler(), llvm::sys::PrintStackTraceOnErrorSignal(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::sys::SetOneShotPipeSignalFunction(), and llvm::SmallVectorBase::size().
InitLLVM() [2/2]
llvm::InitLLVM::InitLLVM (int & Argc, char **& Argv, bool InstallPipeSignalExitHandler = true) inline
Definition at line 38 of file InitLLVM.h.
References ~InitLLVM().
~InitLLVM()
InitLLVM::~InitLLVM ()
Definition at line 56 of file InitLLVM.cpp.
References llvm::llvm_shutdown().
Referenced by InitLLVM().
The documentation for this class was generated from the following files:
include/llvm/Support/InitLLVM.h
lib/Support/InitLLVM.cpp