LLVM: llvm::SCEVConstant Class Reference
llvm::SCEVConstant Class Reference
This class represents a constant integer value.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
ConstantInt * getValue () const
const APInt & getAPInt () const
Type * getType () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy, unsigned short ExpressionSize)
SCEV (const SCEV &)=delete
SCEV & operator= (const SCEV &)=delete
unsigned getSCEVType () const
Type * getType () const
Return the LLVM type of this SCEV expression.
bool isZero () const
Return true if the expression is a constant zero.
bool isOne () const
Return true if the expression is a constant one.
bool isAllOnesValue () const
Return true if the expression is a constant all-ones value.
bool isNonConstantNegative () const
Return true if the specified scev is negated, but not a constant.
unsigned short getExpressionSize () const
void print (raw_ostream &OS) const
Print out the internal representation of this scalar to the specified stream.
void dump () const
This method is used for debugging.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class ScalarEvolution
Additional Inherited Members
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0, FlagNW = (1 << 0), FlagNUW = (1 << 1), FlagNSW = (1 << 2),
NoWrapMask = (1 << 3) - 1
}
NoWrapFlags are bitfield indices into SubclassData.
Protected Attributes inherited from llvm::SCEV
const unsigned short ExpressionSize
unsigned short SubclassData = 0
This field is initialized to zero and may be used in subclasses to store miscellaneous information.
Detailed Description
This class represents a constant integer value.
Definition at line 47 of file ScalarEvolutionExpressions.h.
Member Function Documentation
classof()
static bool llvm::SCEVConstant::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 62 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), and llvm::scConstant.
getAPInt()
const APInt& llvm::SCEVConstant::getAPInt () const inline
Definition at line 57 of file ScalarEvolutionExpressions.h.
References getValue(), and llvm::ConstantInt::getValue().
Referenced by llvm::InterleavedAccessInfo::analyzeInterleaving(), areStridedAccessesIndependent(), canFoldIVIncExpr(), CompareSCEVComplexity(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), extractConstantWithoutWrapping(), FactorOutConstant(), gcd(), getConstantPart(), getExactSDiv(), getMemSetPatternValue(), GetPointerOperand(), llvm::getPtrStride(), getStoreStride(), hasHugeExpression(), llvm::TargetTransformInfoImplBase::isConstantStridedAccessLessThan(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::SCEV::isNonConstantNegative(), isRemainderZero(), llvm::FullDependence::isSplitable(), minAPInt(), SolveQuadraticAddRecRange(), and llvm::ScalarEvolution::verify().
getType()
Type* llvm::SCEVConstant::getType () const inline
Definition at line 59 of file ScalarEvolutionExpressions.h.
References llvm::ConstantInt::getType().
Referenced by mayUsePostIncMode().
getValue()
ConstantInt* llvm::SCEVConstant::getValue () const inline
Definition at line 56 of file ScalarEvolutionExpressions.h.
Referenced by canFoldIVIncExpr(), llvm::SCEVExpander::expandUnionPredicate(), getAPInt(), getConstantTripCount(), getMinFromExprs(), GetPointerOperand(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::IndexedReference::hasSpacialReuse(), llvm::IndexedReference::hasTemporalReuse(), hasUsesOutsideLoop(), llvm::InductionDescriptor::isInductionPHI(), mayUsePostIncMode(), populateDependencyMatrix(), and llvm::SCEVExpander::setChainedPhi().
Friends And Related Function Documentation
ScalarEvolution
friend class ScalarEvolution friend
Definition at line 48 of file ScalarEvolutionExpressions.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h