LLVM: llvm::symbolize::LLVMSymbolizer Class Reference
llvm::symbolize::LLVMSymbolizer Class Reference
#include "llvm/DebugInfo/Symbolize/Symbolize.h"
Classes
struct Options
Public Member Functions
LLVMSymbolizer ()=default
LLVMSymbolizer (const Options &Opts)
~LLVMSymbolizer ()
Expected< DILineInfo > symbolizeCode (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< DILineInfo > symbolizeCode (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< DIInliningInfo > symbolizeInlinedCode (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< DIGlobal > symbolizeData (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< std::vector< DILocal > > symbolizeFrame (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
void flush ()
Static Public Member Functions
static std::string DemangleName (const std::string &Name, const SymbolizableModule *DbiModuleDescriptor)
Detailed Description
Definition at line 36 of file Symbolize.h.
Constructor & Destructor Documentation
LLVMSymbolizer() [1/2]
llvm::symbolize::LLVMSymbolizer::LLVMSymbolizer () default
LLVMSymbolizer() [2/2]
llvm::symbolize::LLVMSymbolizer::LLVMSymbolizer (const Options & Opts) inline
Definition at line 52 of file Symbolize.h.
~LLVMSymbolizer()
llvm::symbolize::LLVMSymbolizer::~LLVMSymbolizer () inline
Definition at line 54 of file Symbolize.h.
References Context, Info, and Name.
Member Function Documentation
DemangleName()
std::string llvm::symbolize::LLVMSymbolizer::DemangleName (const std::string & Name, const SymbolizableModule * DbiModuleDescriptor) static
Definition at line 604 of file Symbolize.cpp.
References llvm::symbolize::SymbolizableModule::isWin32Module(), llvm::itaniumDemangle(), llvm::microsoftDemangle(), llvm::MSDF_NoAccessSpecifier, llvm::MSDF_NoCallingConvention, llvm::MSDF_NoMemberType, llvm::MSDF_NoReturnType, Name, and llvm::sys::fs::status().
Referenced by symbolizeData(), and symbolizeInlinedCode().
flush()
void llvm::symbolize::LLVMSymbolizer::flush ()
Definition at line 166 of file Symbolize.cpp.
References llvm::sys::path::append(), llvm::arrayRefFromStringRef(), llvm::consumeError(), llvm::crc32(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::empty(), llvm::sys::path::extension(), llvm::ErrorOr< T >::get(), llvm::MemoryBuffer::getFileOrSTDIN(), llvm::object::MachOObjectFile::getUuid(), llvm::object::Binary::isLittleEndian(), llvm::sys::fs::make_absolute(), memcmp, Name, P, llvm::object::ELFFile< ELFT >::program_headers(), llvm::ELF::PT_NOTE, llvm::sys::path::relative_path(), llvm::sys::path::remove_filename(), llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), llvm::ArrayRef< T >::size(), llvm::SmallString< InternalLen >::str(), llvm::StringRef::substr(), and llvm::Expected< T >::takeError().
symbolizeCode() [1/2]
Expected< DILineInfo > llvm::symbolize::LLVMSymbolizer::symbolizeCode (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 62 of file Symbolize.cpp.
References Context, llvm::DWARFContext::create(), llvm::DWARFContext::defaultErrorHandler(), llvm::object::Binary::getFileName(), I, and llvm::Expected< T >::takeError().
symbolizeCode() [2/2]
Expected< DILineInfo > llvm::symbolize::LLVMSymbolizer::symbolizeCode (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 79 of file Symbolize.cpp.
References llvm::Expected< T >::takeError().
symbolizeData()
Expected< DIGlobal > llvm::symbolize::LLVMSymbolizer::symbolizeData (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 118 of file Symbolize.cpp.
References llvm::object::SectionedAddress::Address, llvm::symbolize::LLVMSymbolizer::Options::Demangle, DemangleName(), llvm::symbolize::SymbolizableModule::getModulePreferredBase(), Info, llvm::DIGlobal::Name, llvm::symbolize::LLVMSymbolizer::Options::RelativeAddresses, and llvm::symbolize::SymbolizableModule::symbolizeData().
symbolizeFrame()
Expected< std::vector< DILocal > > llvm::symbolize::LLVMSymbolizer::symbolizeFrame (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 144 of file Symbolize.cpp.
References llvm::object::SectionedAddress::Address, llvm::symbolize::SymbolizableModule::getModulePreferredBase(), Info, llvm::symbolize::LLVMSymbolizer::Options::RelativeAddresses, and llvm::symbolize::SymbolizableModule::symbolizeFrame().
symbolizeInlinedCode()
Expected< DIInliningInfo > llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 88 of file Symbolize.cpp.
References llvm::object::SectionedAddress::Address, llvm::symbolize::LLVMSymbolizer::Options::Demangle, DemangleName(), llvm::DILineInfo::FunctionName, llvm::symbolize::SymbolizableModule::getModulePreferredBase(), llvm::DIInliningInfo::getMutableFrame(), llvm::DIInliningInfo::getNumberOfFrames(), Info, llvm::symbolize::LLVMSymbolizer::Options::PrintFunctions, llvm::symbolize::LLVMSymbolizer::Options::RelativeAddresses, llvm::symbolize::SymbolizableModule::symbolizeInlinedCode(), and llvm::symbolize::LLVMSymbolizer::Options::UseSymbolTable.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/Symbolize.h
lib/DebugInfo/Symbolize/Symbolize.cpp