LLVM: llvm::ARMConstantPoolSymbol Class Reference
llvm::ARMConstantPoolSymbol Class Reference
ARMConstantPoolSymbol - ARM-specific constantpool values for external symbols.
#include "Target/ARM/ARMConstantPoolValue.h"
Public Member Functions
StringRef getSymbol () const
int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool hasSameValue (ARMConstantPoolValue *ACPV) override
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const ARMConstantPoolSymbol *A) const
Public Member Functions inherited from llvm::ARMConstantPoolValue
~ARMConstantPoolValue () override
ARMCP::ARMCPModifier getModifier () const
StringRef getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
bool isPromotedGlobal () const
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
getType - get type of this MachineConstantPoolValue.
Static Public Member Functions
static ARMConstantPoolSymbol * Create (LLVMContext &C, StringRef s, unsigned ID, unsigned char PCAdj)
static bool classof (const ARMConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::ARMConstantPoolValue
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolSymbol - ARM-specific constantpool values for external symbols.
Definition at line 212 of file ARMConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void ARMConstantPoolSymbol::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 249 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::addSelectionDAGCSEId(), and llvm::FoldingSetNodeID::AddString().
classof()
static bool llvm::ARMConstantPoolSymbol::classof (const ARMConstantPoolValue * ACPV) inline static
Definition at line 236 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::isExtSymbol().
Create()
ARMConstantPoolSymbol * ARMConstantPoolSymbol::Create (LLVMContext & C, StringRef s, unsigned ID, unsigned char PCAdj) static
Definition at line 233 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::no_modifier.
Referenced by addExclusiveRegPair(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), and llvm::ARMTargetLowering::CCAssignFnForReturn().
equals()
bool llvm::ARMConstantPoolSymbol::equals (const ARMConstantPoolSymbol * A) const inline
Definition at line 240 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::equals().
getExistingMachineCPValue()
int ARMConstantPoolSymbol::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 239 of file ARMConstantPoolValue.cpp.
References llvm::HexagonISD::CP.
getSymbol()
StringRef llvm::ARMConstantPoolSymbol::getSymbol () const inline
Definition at line 223 of file ARMConstantPoolValue.h.
References llvm::HexagonISD::CP, llvm::RISCVFenceField::O, and print().
hasSameValue()
bool ARMConstantPoolSymbol::hasSameValue (ARMConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 244 of file ARMConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::ARMConstantPoolValue::hasSameValue().
print()
void ARMConstantPoolSymbol::print (raw_ostream & O) const override virtual
print - Implement operator<<
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 254 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::ARMConstantPoolValue(), llvm::ARMCP::CPMachineBasicBlock, and llvm::ARMConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMConstantPoolValue.h
lib/Target/ARM/ARMConstantPoolValue.cpp