LLVM: llvm::MDTuple Class Reference
llvm::MDTuple Class Reference
Tuple of metadata.
#include "llvm/IR/Metadata.h"
Public Member Functions
unsigned getHash () const
Get the hash, if any.
TempMDTuple clone () const
Return a (temporary) clone of this.
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata *> MDs)
Return a distinct node.
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata *> MDs)
Return a temporary node.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata *> MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata *> Ops1, ArrayRef< Metadata *> Ops2=None)
~MDNode ()=default
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Tuple of metadata.
This is the simple MDNode arbitrary tuple. Nodes are uniqued by default based on their operands.
Definition at line 1114 of file Metadata.h.
Member Function Documentation
classof()
static bool llvm::MDTuple::classof (const Metadata * MD) inline static
Definition at line 1169 of file Metadata.h.
References llvm::Metadata::getMetadataID().
clone()
TempMDTuple llvm::MDTuple::clone () const inline
Return a (temporary) clone of this.
Definition at line 1167 of file Metadata.h.
get()
static MDTuple* llvm::MDTuple::get (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Definition at line 1141 of file Metadata.h.
References getImpl(), and llvm::Metadata::Uniqued.
Referenced by llvm::GlobalObject::addTypeMetadata(), llvm::DIBuilder::finalize(), FunctionNumber(), llvm::MDNode::get(), getKeyValMD(), llvm::ProfileSummary::getMD(), llvm::DIBuilder::getOrCreateArray(), llvm::DIBuilder::getOrCreateMacroArray(), StripSymbolNames(), llvm::DISubprogram::toSPFlags(), llvm::upgradeInstructionLoopAttachment(), and upgradeLoopArgument().
getDistinct()
static MDTuple* llvm::MDTuple::getDistinct (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Return a distinct node.
Return a distinct node – i.e., a node that is not uniqued.
Definition at line 1152 of file Metadata.h.
References llvm::Metadata::Distinct, and getImpl().
Referenced by FunctionNumber(), and llvm::MDNode::getDistinct().
getHash()
unsigned llvm::MDTuple::getHash () const inline
Get the hash, if any.
Definition at line 1139 of file Metadata.h.
References llvm::Metadata::SubclassData32.
getIfExists()
static MDTuple* llvm::MDTuple::getIfExists (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Definition at line 1145 of file Metadata.h.
References getImpl(), and llvm::Metadata::Uniqued.
Referenced by llvm::MDNode::getIfExists().
getTemporary()
static TempMDTuple llvm::MDTuple::getTemporary (LLVMContext & Context, ArrayRef< Metadata *> MDs) inline static
Return a temporary node.
For use in constructing cyclic MDNode structures. A temporary MDNode is not uniqued, may be RAUW'd, and must be manually deleted with deleteTemporary.
Definition at line 1161 of file Metadata.h.
References getImpl(), and llvm::Metadata::Temporary.
Referenced by CloneAliasScopeMetadata(), llvm::MDNode::getTemporary(), and LLVMTemporaryMDNode().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1115 of file Metadata.h.
MDNode
friend class MDNode friend
Definition at line 1116 of file Metadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/IR/Metadata.cpp