LLVM: llvm::jitlink::Edge Class Reference
llvm::jitlink::Edge Class Reference
Represents fixups and constraints in the LinkGraph.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Types
enum GenericEdgeKind : Kind { Invalid, FirstKeepAlive, KeepAlive = FirstKeepAlive, FirstRelocation }
using Kind = uint8_t
using OffsetT = uint32_t
using AddendT = int64_t
Public Member Functions
Edge (Kind K, OffsetT Offset, Symbol &Target, AddendT Addend)
OffsetT getOffset () const
void setOffset (OffsetT Offset)
Kind getKind () const
void setKind (Kind K)
bool isRelocation () const
Kind getRelocation () const
bool isKeepAlive () const
Symbol & getTarget () const
void setTarget (Symbol &Target)
AddendT getAddend () const
void setAddend (AddendT Addend)
Detailed Description
Represents fixups and constraints in the LinkGraph.
Definition at line 57 of file JITLink.h.
Member Typedef Documentation
AddendT
using llvm::jitlink::Edge::AddendT = int64_t
Definition at line 69 of file JITLink.h.
Kind
using llvm::jitlink::Edge::Kind = uint8_t
Definition at line 59 of file JITLink.h.
OffsetT
using llvm::jitlink::Edge::OffsetT = uint32_t
Definition at line 68 of file JITLink.h.
Member Enumeration Documentation
GenericEdgeKind
enum llvm::jitlink::Edge::GenericEdgeKind : Kind
Enumerator
Invalid
FirstKeepAlive
KeepAlive
FirstRelocation
Definition at line 61 of file JITLink.h.
Constructor & Destructor Documentation
Edge()
llvm::jitlink::Edge::Edge (Kind K, OffsetT Offset, Symbol & Target, AddendT Addend) inline
Definition at line 71 of file JITLink.h.
Member Function Documentation
getAddend()
AddendT llvm::jitlink::Edge::getAddend () const inline
Definition at line 86 of file JITLink.h.
Referenced by llvm::jitlink::MachOJITLinker_arm64::MachOJITLinker_arm64(), llvm::jitlink::MachOJITLinker_x86_64::MachOJITLinker_x86_64(), and llvm::jitlink::printEdge().
getKind()
Kind llvm::jitlink::Edge::getKind () const inline
Definition at line 76 of file JITLink.h.
Referenced by llvm::jitlink::MachOJITLinker_arm64::MachOJITLinker_arm64(), and llvm::jitlink::MachOJITLinker_x86_64::MachOJITLinker_x86_64().
getOffset()
OffsetT llvm::jitlink::Edge::getOffset () const inline
Definition at line 74 of file JITLink.h.
Referenced by llvm::jitlink::MachOJITLinker_arm64::MachOJITLinker_arm64(), llvm::jitlink::MachOJITLinker_x86_64::MachOJITLinker_x86_64(), and llvm::jitlink::printEdge().
getRelocation()
Kind llvm::jitlink::Edge::getRelocation () const inline
Definition at line 79 of file JITLink.h.
References assert().
getTarget()
Symbol& llvm::jitlink::Edge::getTarget () const inline
Definition at line 84 of file JITLink.h.
Referenced by llvm::jitlink::MachOJITLinker_arm64::MachOJITLinker_arm64(), llvm::jitlink::MachOJITLinker_x86_64::MachOJITLinker_x86_64(), and llvm::jitlink::printEdge().
isKeepAlive()
bool llvm::jitlink::Edge::isKeepAlive () const inline
Definition at line 83 of file JITLink.h.
isRelocation()
bool llvm::jitlink::Edge::isRelocation () const inline
Definition at line 78 of file JITLink.h.
setAddend()
void llvm::jitlink::Edge::setAddend (AddendT Addend) inline
Definition at line 87 of file JITLink.h.
References llvm::jitlink::getGenericEdgeKindName().
setKind()
void llvm::jitlink::Edge::setKind (Kind K) inline
Definition at line 77 of file JITLink.h.
setOffset()
void llvm::jitlink::Edge::setOffset (OffsetT Offset) inline
Definition at line 75 of file JITLink.h.
setTarget()
void llvm::jitlink::Edge::setTarget (Symbol & Target) inline
Definition at line 85 of file JITLink.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h