LLVM: llvm::pdb::IPDBSourceFile Class Reference
llvm::pdb::IPDBSourceFile Class Reference abstract
IPDBSourceFile defines an interface used to represent source files whose information are stored in the PDB.
#include "llvm/DebugInfo/PDB/IPDBSourceFile.h"
Public Member Functions
virtual ~IPDBSourceFile ()
void dump (raw_ostream &OS, int Indent) const
virtual std::string getFileName () const =0
virtual uint32_t getUniqueId () const =0
virtual std::string getChecksum () const =0
virtual PDB_Checksum getChecksumType () const =0
virtual std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > getCompilands () const =0
Detailed Description
IPDBSourceFile defines an interface used to represent source files whose information are stored in the PDB.
Definition at line 23 of file IPDBSourceFile.h.
Constructor & Destructor Documentation
~IPDBSourceFile()
IPDBSourceFile::~IPDBSourceFile () virtual default
Member Function Documentation
dump()
void IPDBSourceFile::dump (raw_ostream & OS, int Indent) const
Definition at line 22 of file IPDBSourceFile.cpp.
References llvm::format_hex_no_prefix(), getChecksum(), getChecksumType(), getFileName(), llvm::raw_ostream::indent(), and llvm::pdb::None.
getChecksum()
virtual std::string llvm::pdb::IPDBSourceFile::getChecksum () const pure virtual
Implemented in llvm::pdb::DIASourceFile.
Referenced by dump().
getChecksumType()
virtual PDB_Checksum llvm::pdb::IPDBSourceFile::getChecksumType () const pure virtual
Implemented in llvm::pdb::DIASourceFile.
Referenced by dump().
getCompilands()
virtual std::unique_ptr<IPDBEnumChildren<PDBSymbolCompiland> > llvm::pdb::IPDBSourceFile::getCompilands () const pure virtual
Implemented in llvm::pdb::DIASourceFile.
getFileName()
virtual std::string llvm::pdb::IPDBSourceFile::getFileName () const pure virtual
Implemented in llvm::pdb::DIASourceFile.
Referenced by dump().
getUniqueId()
virtual uint32_t llvm::pdb::IPDBSourceFile::getUniqueId () const pure virtual
Implemented in llvm::pdb::DIASourceFile.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/IPDBSourceFile.h
lib/DebugInfo/PDB/IPDBSourceFile.cpp