LLVM: llvm::codeview::ContinuationRecordBuilder Class Reference
llvm::codeview::ContinuationRecordBuilder Class Reference
#include "llvm/DebugInfo/CodeView/ContinuationRecordBuilder.h"
Public Member Functions
ContinuationRecordBuilder ()
~ContinuationRecordBuilder ()
void begin (ContinuationRecordKind RecordKind)
template<typename RecordType >
void writeMemberType (RecordType &Record)
std::vector< CVType > end (TypeIndex Index)
Detailed Description
Definition at line 34 of file ContinuationRecordBuilder.h.
Constructor & Destructor Documentation
ContinuationRecordBuilder()
ContinuationRecordBuilder::ContinuationRecordBuilder ()
Definition at line 46 of file ContinuationRecordBuilder.cpp.
~ContinuationRecordBuilder()
ContinuationRecordBuilder::~ContinuationRecordBuilder ()
Definition at line 49 of file ContinuationRecordBuilder.cpp.
Member Function Documentation
begin()
void ContinuationRecordBuilder::begin (ContinuationRecordKind RecordKind)
Definition at line 51 of file ContinuationRecordBuilder.cpp.
References assert(), llvm::cantFail(), llvm::AppendingBinaryByteStream::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::codeview::FieldList, llvm::BinaryStreamWriter::getLength(), llvm::BinaryStreamWriter::getOffset(), getTypeLeafKind(), llvm::Optional< T >::hasValue(), llvm::cl::Prefix, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::BinaryStreamWriter::setOffset(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), and llvm::BinaryStreamWriter::writeObject().
Referenced by getCommonClassOptions(), and shouldAlwaysEmitCompleteClassType().
end()
std::vector< CVType > ContinuationRecordBuilder::end (TypeIndex Index)
Definition at line 173 of file ContinuationRecordBuilder.cpp.
References llvm::cantFail(), getTypeLeafKind(), llvm::makeArrayRef(), llvm::cl::Prefix, llvm::SmallVectorBase::size(), and llvm::codeview::TypeRecordMapping::visitTypeEnd().
Referenced by llvm::codeview::AppendingTypeTableBuilder::insertRecord(), llvm::codeview::MergingTypeTableBuilder::insertRecord(), and llvm::codeview::GlobalTypeTableBuilder::insertRecord().
writeMemberType()
template<typename RecordType > void ContinuationRecordBuilder::writeMemberType (RecordType & Record)
Definition at line 78 of file ContinuationRecordBuilder.cpp.
References addPadding(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::BinaryStreamWriter::bytesRemaining(), llvm::cantFail(), ContinuationLength, llvm::Data, llvm::AppendingBinaryByteStream::data(), llvm::MutableArrayRef< T >::data(), llvm::codeview::TypeIndex::getIndex(), llvm::BinaryStreamWriter::getLength(), llvm::BinaryStreamWriter::getOffset(), llvm::Optional< T >::hasValue(), llvm::AppendingBinaryByteStream::insert(), llvm::codeview::CVMemberRecord::Kind, llvm::codeview::MaxRecordLength, MaxSegmentLength, llvm::cl::Prefix, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::codeview::RecordPrefix::RecordLen, llvm::BinaryStreamWriter::setOffset(), llvm::ArrayRef< T >::size(), llvm::MutableArrayRef< T >::slice(), llvm::MutableArrayRef< T >::take_back(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::BinaryStreamWriter::writeEnum().
Referenced by getCommonClassOptions(), shouldAlwaysEmitCompleteClassType(), and llvm::CodeViewYAML::detail::MemberRecordImpl< T >::writeTo().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/ContinuationRecordBuilder.h
lib/DebugInfo/CodeView/ContinuationRecordBuilder.cpp