LLVM: llvm::MCSectionXCOFF Class Reference
llvm::MCSectionXCOFF Class Reference final
#include "llvm/MC/MCSectionXCOFF.h"
Public Member Functions
~MCSectionXCOFF ()
StringRef getSectionName () const
XCOFF::StorageMappingClass getMappingClass () const
XCOFF::StorageClass getStorageClass () const
XCOFF::SymbolType getCSectType () const
MCSymbolXCOFF * getQualNameSymbol () const
void PrintSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const override
bool UseCodeAlign () const override
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
bool isVirtualSection () const override
Check whether this section is "virtual", that is has no actual object file contents.
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
SectionKind getKind () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
unsigned getAlignment () const
void setAlignment (Align Value)
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
MCSection::FragmentListType & getFragmentList ()
const MCSection::FragmentListType & getFragmentList () const
const MCDummyFragment & getDummyFragment () const
MCDummyFragment & getDummyFragment ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
MCSection::iterator getSubsectionInsertionPoint (unsigned Subsection)
void dump () const
void addPendingLabel (MCSymbol *label, unsigned Subsection=0)
Add a pending label for the requested subsection.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0, unsigned Subsection=0)
Associate all pending labels in a subsection with a fragment.
void flushPendingLabels ()
Associate all pending labels with empty data fragments.
Static Public Member Functions
static bool classof (const MCSection *S)
Static Public Member Functions inherited from llvm::MCSection
static FragmentListType MCSection::* getSublistAccess (MCFragment *)
Support for MCFragment::getNextNode().
Friends
class MCContext
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant {
SV_COFF = 0, SV_ELF, SV_MachO, SV_Wasm,
SV_XCOFF
}
enum BundleLockStateType { NotBundleLocked, BundleLocked, BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
using FragmentListType = iplist< MCFragment >
using const_iterator = FragmentListType::const_iterator
using iterator = FragmentListType::iterator
using const_reverse_iterator = FragmentListType::const_reverse_iterator
using reverse_iterator = FragmentListType::reverse_iterator
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, SectionKind K, MCSymbol *Begin)
~MCSection ()
Protected Attributes inherited from llvm::MCSection
SectionVariant Variant
SectionKind Kind
Detailed Description
Definition at line 33 of file MCSectionXCOFF.h.
Constructor & Destructor Documentation
~MCSectionXCOFF()
MCSectionXCOFF::~MCSectionXCOFF () default
Member Function Documentation
classof()
static bool llvm::MCSectionXCOFF::classof (const MCSection * S) inline static
Definition at line 57 of file MCSectionXCOFF.h.
References llvm::MCSection::getVariant(), and llvm::MCSection::SV_XCOFF.
getCSectType()
XCOFF::SymbolType llvm::MCSectionXCOFF::getCSectType () const inline
Definition at line 64 of file MCSectionXCOFF.h.
References Type.
Referenced by PrintSwitchToSection().
getMappingClass()
XCOFF::StorageMappingClass llvm::MCSectionXCOFF::getMappingClass () const inline
Definition at line 62 of file MCSectionXCOFF.h.
Referenced by PrintSwitchToSection().
getQualNameSymbol()
MCSymbolXCOFF* llvm::MCSectionXCOFF::getQualNameSymbol () const inline
Definition at line 65 of file MCSectionXCOFF.h.
References isVirtualSection(), PrintSwitchToSection(), and UseCodeAlign().
getSectionName()
StringRef llvm::MCSectionXCOFF::getSectionName () const inline
Definition at line 61 of file MCSectionXCOFF.h.
References Name.
getStorageClass()
XCOFF::StorageClass llvm::MCSectionXCOFF::getStorageClass () const inline
Definition at line 63 of file MCSectionXCOFF.h.
References StorageClass.
isVirtualSection()
bool MCSectionXCOFF::isVirtualSection () const override virtual
Check whether this section is "virtual", that is has no actual object file contents.
Implements llvm::MCSection.
Definition at line 73 of file MCSectionXCOFF.cpp.
References llvm::XCOFF::XTY_CM.
Referenced by getQualNameSymbol().
PrintSwitchToSection()
void MCSectionXCOFF::PrintSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, const MCExpr * Subsection) const override virtual
Implements llvm::MCSection.
Definition at line 19 of file MCSectionXCOFF.cpp.
References assert(), getCSectType(), llvm::MCSection::getKind(), getMappingClass(), llvm::MCSymbol::getName(), llvm::report_fatal_error(), llvm::XCOFF::XMC_BS, llvm::XCOFF::XMC_DS, llvm::XCOFF::XMC_PR, llvm::XCOFF::XMC_RO, llvm::XCOFF::XMC_RW, llvm::XCOFF::XMC_TC, llvm::XCOFF::XMC_TC0, and llvm::XCOFF::XTY_CM.
Referenced by getQualNameSymbol().
UseCodeAlign()
bool MCSectionXCOFF::UseCodeAlign () const override virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implements llvm::MCSection.
Definition at line 71 of file MCSectionXCOFF.cpp.
References llvm::MCSection::getKind(), and llvm::SectionKind::isText().
Referenced by getQualNameSymbol().
Friends And Related Function Documentation
MCContext
friend class MCContext friend
Definition at line 34 of file MCSectionXCOFF.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSectionXCOFF.h
lib/MC/MCSectionXCOFF.cpp