LLVM: llvm::MachO::Target Class Reference
llvm::MachO::Target Class Reference
#include "llvm/TextAPI/MachO/Target.h"
Public Member Functions
Target ()=default
Target (Architecture Arch, PlatformKind Platform)
Target (const llvm::Triple &Triple)
operator std::string () const
Static Public Member Functions
static llvm::Expected< Target > create (StringRef Target)
Public Attributes
Architecture Arch
PlatformKind Platform
Detailed Description
Definition at line 24 of file Target.h.
Constructor & Destructor Documentation
Target() [1/3]
llvm::MachO::Target::Target () default
Target() [2/3]
llvm::MachO::Target::Target (Architecture Arch, PlatformKind Platform) inline
Definition at line 27 of file Target.h.
Target() [3/3]
llvm::MachO::Target::Target (const llvm::Triple & Triple) inline explicit
Definition at line 29 of file Target.h.
References create().
Member Function Documentation
create()
Expected< Target > llvm::MachO::Target::create (StringRef Target) static
Definition at line 20 of file Target.cpp.
References llvm::MachO::bridgeOS, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::MachO::getArchitectureFromName(), llvm::MachO::iOS, llvm::MachO::iOSSimulator, llvm::MachO::macCatalyst, llvm::MachO::macOS, Platform, llvm::StringRef::split(), llvm::MachO::tvOS, llvm::MachO::tvOSSimulator, llvm::MachO::unknown, llvm::MachO::watchOS, and llvm::MachO::watchOSSimulator.
Referenced by Target().
operator std::string()
llvm::MachO::Target::operator std::string () const
Definition at line 50 of file Target.cpp.
References Arch, llvm::MachO::getArchitectureName(), llvm::MachO::getPlatformName(), and Platform.
Member Data Documentation
Arch
Architecture llvm::MachO::Target::Arch
Definition at line 36 of file Target.h.
Referenced by llvm::MachO::mapToArchitectureSet(), operator std::string(), llvm::MachO::operator!=(), llvm::MachO::operator<(), llvm::MachO::operator==(), and llvm::MachO::Symbol::targets().
Platform
PlatformKind llvm::MachO::Target::Platform
Definition at line 37 of file Target.h.
Referenced by create(), llvm::MachO::mapToPlatformSet(), operator std::string(), llvm::MachO::operator!=(), llvm::MachO::operator<(), and llvm::MachO::operator==().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/MachO/Target.h
lib/TextAPI/MachO/Target.cpp