LLVM: llvm::mca::Context Class Reference
llvm::mca::Context Class Reference
#include "llvm/MCA/Context.h"
Public Member Functions
Context (const MCRegisterInfo &R, const MCSubtargetInfo &S)
Context (const Context &C)=delete
Context & operator= (const Context &C)=delete
const MCRegisterInfo & getMCRegisterInfo () const
const MCSubtargetInfo & getMCSubtargetInfo () const
void addHardwareUnit (std::unique_ptr< HardwareUnit > H)
std::unique_ptr< Pipeline > createDefaultPipeline (const PipelineOptions &Opts, SourceMgr &SrcMgr)
Construct a basic pipeline for simulating an out-of-order pipeline.
Detailed Description
Definition at line 50 of file Context.h.
Constructor & Destructor Documentation
Context() [1/2]
llvm::mca::Context::Context (const MCRegisterInfo & R, const MCSubtargetInfo & S) inline
Definition at line 56 of file Context.h.
References C, and Context.
Context() [2/2]
llvm::mca::Context::Context (const Context & C) delete
Member Function Documentation
addHardwareUnit()
void llvm::mca::Context::addHardwareUnit (std::unique_ptr< HardwareUnit > H) inline
Definition at line 63 of file Context.h.
References llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SrcMgr.
Referenced by createDefaultPipeline().
createDefaultPipeline()
std::unique_ptr< Pipeline > llvm::mca::Context::createDefaultPipeline (const PipelineOptions & Opts, SourceMgr & SrcMgr)
Construct a basic pipeline for simulating an out-of-order pipeline.
This pipeline consists of Fetch, Dispatch, Execute, and Retire stages.
Definition at line 31 of file Context.cpp.
References addHardwareUnit(), llvm::mca::PipelineOptions::AssumeNoAlias, llvm::mca::PipelineOptions::DecodersThroughput, llvm::mca::PipelineOptions::DispatchWidth, llvm::mca::PipelineOptions::EnableBottleneckAnalysis, llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::PipelineOptions::LoadQueueSize, llvm::mca::PipelineOptions::MicroOpQueueSize, llvm::mca::PipelineOptions::RegisterFileSize, llvm::SrcMgr, and llvm::mca::PipelineOptions::StoreQueueSize.
getMCRegisterInfo()
const MCRegisterInfo& llvm::mca::Context::getMCRegisterInfo () const inline
Definition at line 60 of file Context.h.
References MRI.
getMCSubtargetInfo()
const MCSubtargetInfo& llvm::mca::Context::getMCSubtargetInfo () const inline
Definition at line 61 of file Context.h.
operator=()
Context& llvm::mca::Context::operator= (const Context & C) delete
The documentation for this class was generated from the following files:
include/llvm/MCA/Context.h
lib/MCA/Context.cpp