LLVM: llvm::FunctionCallee Class Reference
llvm::FunctionCallee Class Reference
A handy container for a FunctionType+Callee-pointer pair, which can be passed around as a single entity.
#include "llvm/IR/DerivedTypes.h"
Public Member Functions
template<typename T , typename U = decltype(&T::getFunctionType)>
FunctionCallee (T *Fn)
FunctionCallee (FunctionType *FnTy, Value *Callee)
FunctionCallee (std::nullptr_t)
FunctionCallee ()=default
FunctionType * getFunctionType ()
Value * getCallee ()
operator bool ()
Detailed Description
A handy container for a FunctionType+Callee-pointer pair, which can be passed around as a single entity.
This assists in replacing the use of PointerType::getElementType() to access the function's type, since that's slated for removal as part of the [opaque pointer types] project.
Definition at line 170 of file DerivedTypes.h.
Constructor & Destructor Documentation
FunctionCallee() [1/4]
template<typename T , typename U = decltype(&T::getFunctionType)> llvm::FunctionCallee::FunctionCallee (T * Fn) inline
Definition at line 175 of file DerivedTypes.h.
References Callee.
FunctionCallee() [2/4]
llvm::FunctionCallee::FunctionCallee (FunctionType * FnTy, Value * Callee) inline
Definition at line 178 of file DerivedTypes.h.
References assert().
FunctionCallee() [3/4]
llvm::FunctionCallee::FunctionCallee (std::nullptr_t) inline
Definition at line 183 of file DerivedTypes.h.
FunctionCallee() [4/4]
llvm::FunctionCallee::FunctionCallee () default
Member Function Documentation
getCallee()
Value* llvm::FunctionCallee::getCallee () inline
Definition at line 189 of file DerivedTypes.h.
References Callee.
Referenced by llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), llvm::IRBuilder< TargetFolder >::CreateCall(), llvm::IRBuilder< TargetFolder >::CreateCallBr(), createCallInst(), llvm::IRBuilder< TargetFolder >::CreateInvoke(), llvm::OpenMPIRBuilder::CreateParallel(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), emitUnaryFloatFnCallHelper(), llvm::getCopyDeclaration(), llvm::Intrinsic::getDeclaration(), INITIALIZE_PASS(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), lowerObjCCall(), makeStatepointExplicitImpl(), llvm::EscapeEnumerator::Next(), and llvm::CallBase::setCalledFunction().
getFunctionType()
FunctionType* llvm::FunctionCallee::getFunctionType () inline
Definition at line 187 of file DerivedTypes.h.
Referenced by annotateAnyAllocSite(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), llvm::IRBuilder< TargetFolder >::CreateCall(), llvm::IRBuilder< TargetFolder >::CreateCallBr(), createCallInst(), llvm::IRBuilder< TargetFolder >::CreateInvoke(), and llvm::CallBase::setCalledFunction().
operator bool()
llvm::FunctionCallee::operator bool () inline explicit
Definition at line 191 of file DerivedTypes.h.
References Callee.
The documentation for this class was generated from the following file:
include/llvm/IR/DerivedTypes.h