LLVM: llvm::GISelCSEAnalysisWrapper Class Reference
llvm::GISelCSEAnalysisWrapper Class Reference
Simple wrapper that does the following.
#include "llvm/CodeGen/GlobalISel/CSEInfo.h"
Public Member Functions
GISelCSEInfo & get (std::unique_ptr< CSEConfigBase > CSEOpt, bool ReCompute=false)
Takes a CSEConfigBase object that defines what opcodes get CSEd.
void setMF (MachineFunction &MFunc)
void setComputed (bool Computed)
void releaseMemory ()
Detailed Description
Simple wrapper that does the following.
1) Lazily evaluate the MachineFunction to compute CSEable instructions. 2) Allows configuration of which instructions are CSEd through CSEConfig object. Provides a method called get which takes a CSEConfig object.
Definition at line 200 of file CSEInfo.h.
Member Function Documentation
get()
GISelCSEInfo & GISelCSEAnalysisWrapper::get (std::unique_ptr< CSEConfigBase > CSEOpt, bool ReCompute = false)
Takes a CSEConfigBase object that defines what opcodes get CSEd.
If CSEConfig is already set, and the CSE Analysis has been preserved, it will not use the new CSEOpt(use Recompute to force using the new CSEOpt).
Definition at line 369 of file CSEInfo.cpp.
References Info.
Referenced by llvm::IRTranslator::runOnMachineFunction().
releaseMemory()
void llvm::GISelCSEAnalysisWrapper::releaseMemory () inline
Definition at line 214 of file CSEInfo.h.
References llvm::GISelCSEInfo::releaseMemory().
Referenced by llvm::GISelCSEAnalysisWrapperPass::releaseMemory().
setComputed()
void llvm::GISelCSEAnalysisWrapper::setComputed (bool Computed) inline
Definition at line 213 of file CSEInfo.h.
Referenced by llvm::GISelCSEAnalysisWrapperPass::releaseMemory().
setMF()
void llvm::GISelCSEAnalysisWrapper::setMF (MachineFunction & MFunc) inline
Definition at line 212 of file CSEInfo.h.
Referenced by llvm::GISelCSEAnalysisWrapperPass::runOnMachineFunction().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CSEInfo.h
lib/CodeGen/GlobalISel/CSEInfo.cpp