LLVM: llvm::PMStack Class Reference
llvm::PMStack Class Reference
PMStack - This class implements a stack data structure of PMDataManager pointers.
#include "llvm/IR/LegacyPassManagers.h"
Public Types
typedef std::vector< PMDataManager * >::const_reverse_iterator iterator
Public Member Functions
iterator begin () const
iterator end () const
void pop ()
PMDataManager * top () const
void push (PMDataManager *PM)
bool empty () const
void dump () const
Detailed Description
PMStack - This class implements a stack data structure of PMDataManager pointers.
Top level pass managers (see PassManager.cpp) maintain active Pass Managers using PMStack. Each Pass implements assignPassManager() to connect itself with appropriate manager. assignPassManager() walks PMStack to find suitable manager.
Definition at line 138 of file LegacyPassManagers.h.
Member Typedef Documentation
iterator
typedef std::vector<PMDataManager *>::const_reverse_iterator llvm::PMStack::iterator
Definition at line 140 of file LegacyPassManagers.h.
Member Function Documentation
begin()
iterator llvm::PMStack::begin () const inline
Definition at line 141 of file LegacyPassManagers.h.
Referenced by llvm::PMDataManager::populateInheritedAnalysis().
dump()
LLVM_DUMP_METHOD void PMStack::dump () const
Definition at line 1766 of file LegacyPassManager.cpp.
References llvm::dbgs().
empty()
bool llvm::PMStack::empty () const inline
Definition at line 147 of file LegacyPassManagers.h.
References llvm::dump().
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
end()
iterator llvm::PMStack::end () const inline
Definition at line 142 of file LegacyPassManagers.h.
Referenced by llvm::PMDataManager::populateInheritedAnalysis().
pop()
void PMStack::pop ()
Definition at line 1733 of file LegacyPassManager.cpp.
References llvm::PMDataManager::initializeAnalysisInfo().
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
push()
void PMStack::push (PMDataManager * PM)
Definition at line 1742 of file LegacyPassManager.cpp.
References assert(), llvm::empty(), llvm::PMDataManager::getDepth(), getDepth(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_FunctionPassManager, llvm::PMT_ModulePassManager, llvm::PMDataManager::setDepth(), and llvm::PMDataManager::setTopLevelManager().
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), and llvm::FunctionPass::assignPassManager().
top()
PMDataManager* llvm::PMStack::top () const inline
Definition at line 145 of file LegacyPassManagers.h.
References push().
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassManagers.h
lib/IR/LegacyPassManager.cpp