LLVM: llvm::Module Class Reference
llvm::Module Class Reference
A Module instance is used to store all the information related to an LLVM module.
#include "llvm/IR/Module.h"
Classes
class debug_compile_units_iterator
An iterator for DICompileUnits that skips those marked NoDebug.
struct ModuleFlagEntry
Public Member Functions
void dropTriviallyDeadConstantArrays ()
Destroy ConstantArrays in LLVMContext if they are not used.
bool getRtLibUseGOT () const
Returns true if PLT should be avoided for RTLib calls.
void setRtLibUseGOT ()
Set that PLT should be avoid for RTLib calls.
void setOwnedMemoryBuffer (std::unique_ptr< MemoryBuffer > MB)
Take ownership of the given memory buffer.
Constructors
Module (StringRef ModuleID, LLVMContext &C)
The Module constructor.
~Module ()
The module destructor. This will dropAllReferences.
Module Level Accessors
const std::string & getModuleIdentifier () const
Get the module identifier which is, essentially, the name of the module.
unsigned getInstructionCount ()
Returns the number of non-debug IR instructions in the module.
const std::string & getSourceFileName () const
Get the module's original source file name.
StringRef getName () const
Get a short "name" for the module.
const std::string & getDataLayoutStr () const
Get the data layout string for the module's target platform.
const DataLayout & getDataLayout () const
Get the data layout for the module's target platform.
const std::string & getTargetTriple () const
Get the target triple which is a string describing the target host.
LLVMContext & getContext () const
Get the global data context.
const std::string & getModuleInlineAsm () const
Get any module-scope inline assembly blocks.
std::unique_ptr< RandomNumberGenerator > createRNG (const Pass *P) const
Get a RandomNumberGenerator salted for use with this module.
bool shouldEmitInstrCountChangedRemark ()
Return true if size-info optimization remark is enabled, false otherwise.
Module Level Mutators
void setModuleIdentifier (StringRef ID)
Set the module identifier.
void setSourceFileName (StringRef Name)
Set the module's original source file name.
void setDataLayout (StringRef Desc)
Set the data layout.
void setDataLayout (const DataLayout &Other)
void setTargetTriple (StringRef T)
Set the target triple.
void setModuleInlineAsm (StringRef Asm)
Set the module-scope inline assembly blocks.
void appendModuleInlineAsm (StringRef Asm)
Append to the module-scope inline assembly blocks.
Generic Value Accessors
GlobalValue * getNamedValue (StringRef Name) const
Return the global value in the module with the specified name, of arbitrary type.
unsigned getMDKindID (StringRef Name) const
Return a unique non-zero ID for the specified metadata kind.
void getMDKindNames (SmallVectorImpl< StringRef > &Result) const
Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
void getOperandBundleTags (SmallVectorImpl< StringRef > &Result) const
Populate client supplied SmallVector with the bundle tags registered in this LLVMContext.
StructType * getTypeByName (StringRef Name) const
Return the type with the specified name, or null if there is none by that name.
std::vector< StructType * > getIdentifiedStructTypes () const
Function Accessors
FunctionCallee getOrInsertFunction (StringRef Name, FunctionType *T, AttributeList AttributeList)
Look up the specified function in the module symbol table.
FunctionCallee getOrInsertFunction (StringRef Name, FunctionType *T)
template<typename... ArgsTy>
FunctionCallee getOrInsertFunction (StringRef Name, AttributeList AttributeList, Type *RetTy, ArgsTy... Args)
Look up the specified function in the module symbol table.
template<typename... ArgsTy>
FunctionCallee getOrInsertFunction (StringRef Name, Type *RetTy, ArgsTy... Args)
Same as above, but without the attributes.
template<typename... ArgsTy>
FunctionCallee getOrInsertFunction (StringRef Name, AttributeList AttributeList, FunctionType *Invalid, ArgsTy... Args)=delete
Function * getFunction (StringRef Name) const
Look up the specified function in the module symbol table.
Global Variable Accessors
GlobalVariable * getGlobalVariable (StringRef Name) const
Look up the specified global variable in the module symbol table.
GlobalVariable * getGlobalVariable (StringRef Name, bool AllowInternal) const
getGlobalVariable - Look up the specified global variable in the module symbol table.
GlobalVariable * getGlobalVariable (StringRef Name, bool AllowInternal=false)
const GlobalVariable * getNamedGlobal (StringRef Name) const
Return the global variable in the module with the specified name, of arbitrary type.
GlobalVariable * getNamedGlobal (StringRef Name)
Constant * getOrInsertGlobal (StringRef Name, Type *Ty, function_ref< GlobalVariable *()> CreateGlobalCallback)
Look up the specified global in the module symbol table.
Constant * getOrInsertGlobal (StringRef Name, Type *Ty)
Look up the specified global in the module symbol table.
Global Alias Accessors
GlobalAlias * getNamedAlias (StringRef Name) const
Return the global alias in the module with the specified name, of arbitrary type.
Global IFunc Accessors
GlobalIFunc * getNamedIFunc (StringRef Name) const
Return the global ifunc in the module with the specified name, of arbitrary type.
Named Metadata Accessors
NamedMDNode * getNamedMetadata (const Twine &Name) const
Return the first NamedMDNode in the module with the specified name.
NamedMDNode * getOrInsertNamedMetadata (StringRef Name)
Return the named MDNode in the module with the specified name.
void eraseNamedMetadata (NamedMDNode *NMD)
Remove the given NamedMDNode from this module and delete it.
Comdat Accessors
Comdat * getOrInsertComdat (StringRef Name)
Return the Comdat in the module with the specified name.
Module Flags Accessors
void getModuleFlagsMetadata (SmallVectorImpl< ModuleFlagEntry > &Flags) const
Returns the module flags in the provided vector.
Metadata * getModuleFlag (StringRef Key) const
Return the corresponding value if Key appears in module flags, otherwise return null.
NamedMDNode * getModuleFlagsMetadata () const
Returns the NamedMDNode in the module that represents module-level flags.
NamedMDNode * getOrInsertModuleFlagsMetadata ()
Returns the NamedMDNode in the module that represents module-level flags.
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata *Val)
Add a module-level flag to the module-level flags metadata.
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Constant *Val)
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, uint32_t Val)
void addModuleFlag (MDNode *Node)
Materialization
void setMaterializer (GVMaterializer *GVM)
Sets the GVMaterializer to GVM.
GVMaterializer * getMaterializer () const
Retrieves the GVMaterializer, if any, for this Module.
bool isMaterialized () const
llvm::Error materialize (GlobalValue *GV)
Make sure the GlobalValue is fully read.
llvm::Error materializeAll ()
Make sure all GlobalValues in this Module are fully read and clear the Materializer.
llvm::Error materializeMetadata ()
Global Variable Iteration
global_iterator global_begin ()
const_global_iterator global_begin () const
global_iterator global_end ()
const_global_iterator global_end () const
bool global_empty () const
iterator_range< global_iterator > globals ()
iterator_range< const_global_iterator > globals () const
Function Iteration
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
iterator_range< iterator > functions ()
iterator_range< const_iterator > functions () const
Alias Iteration
alias_iterator alias_begin ()
const_alias_iterator alias_begin () const
alias_iterator alias_end ()
const_alias_iterator alias_end () const
size_t alias_size () const
bool alias_empty () const
iterator_range< alias_iterator > aliases ()
iterator_range< const_alias_iterator > aliases () const
IFunc Iteration
ifunc_iterator ifunc_begin ()
const_ifunc_iterator ifunc_begin () const
ifunc_iterator ifunc_end ()
const_ifunc_iterator ifunc_end () const
size_t ifunc_size () const
bool ifunc_empty () const
iterator_range< ifunc_iterator > ifuncs ()
iterator_range< const_ifunc_iterator > ifuncs () const
Named Metadata Iteration
named_metadata_iterator named_metadata_begin ()
const_named_metadata_iterator named_metadata_begin () const
named_metadata_iterator named_metadata_end ()
const_named_metadata_iterator named_metadata_end () const
size_t named_metadata_size () const
bool named_metadata_empty () const
iterator_range< named_metadata_iterator > named_metadata ()
iterator_range< const_named_metadata_iterator > named_metadata () const
debug_compile_units_iterator debug_compile_units_begin () const
debug_compile_units_iterator debug_compile_units_end () const
iterator_range< debug_compile_units_iterator > debug_compile_units () const
Return an iterator for all DICompileUnits listed in this Module's llvm.dbg.cu named metadata node and aren't explicitly marked as NoDebug.
Utility functions for printing and dumping Module objects
void print (raw_ostream &OS, AssemblyAnnotationWriter *AAW, bool ShouldPreserveUseListOrder=false, bool IsForDebug=false) const
Print the module to an output stream with an optional AssemblyAnnotationWriter.
void dump () const
Dump the module to stderr (for debugging).
void dropAllReferences ()
This function causes all the subinstructions to "let go" of all references that they are maintaining.
Utility functions for querying Debug information.
unsigned getNumberRegisterParameters () const
Returns the Number of Register ParametersDwarf Version by checking module flags.
unsigned getDwarfVersion () const
Returns the Dwarf Version by checking module flags.
unsigned getCodeViewFlag () const
Returns the CodeView Version by checking module flags.
Utility functions for querying and setting PIC level
PICLevel::Level getPICLevel () const
Returns the PIC level (small or large model)
void setPICLevel (PICLevel::Level PL)
Set the PIC level (small or large model)
Utility functions for querying and setting PIE level
PIELevel::Level getPIELevel () const
Returns the PIE level (small or large model)
void setPIELevel (PIELevel::Level PL)
Set the PIE level (small or large model)
Utility function for querying and setting code model
Optional< CodeModel::Model > getCodeModel () const
Returns the code model (tiny, small, kernel, medium or large model)
void setCodeModel (CodeModel::Model CL)
Set the code model (tiny, small, kernel, medium or large)
Utility functions for querying and setting PGO summary
void setProfileSummary (Metadata *M, ProfileSummary::Kind Kind)
Attach profile summary metadata to this module.
Metadata * getProfileSummary (bool IsCS)
Returns profile summary metadata.
Utility functions for querying and setting the build SDK version
void setSDKVersion (const VersionTuple &V)
Attach a build SDK version metadata to this module.
VersionTuple getSDKVersion () const
Get the build SDK version metadata.
Types And Enumerations
enum ModFlagBehavior {
Error = 1, Warning = 2, Require = 3, Override = 4,
Append = 5, AppendUnique = 6, Max = 7, ModFlagBehaviorFirstVal = Error,
ModFlagBehaviorLastVal = Max
}
This enumeration defines the supported behaviors of module flags.
using GlobalListType = SymbolTableList< GlobalVariable >
The type for the list of global variables.
using FunctionListType = SymbolTableList< Function >
The type for the list of functions.
using AliasListType = SymbolTableList< GlobalAlias >
The type for the list of aliases.
using IFuncListType = SymbolTableList< GlobalIFunc >
The type for the list of ifuncs.
using NamedMDListType = ilist< NamedMDNode >
The type for the list of named metadata.
using ComdatSymTabType = StringMap< Comdat >
The type of the comdat "symbol" table.
using global_iterator = GlobalListType::iterator
The Global Variable iterator.
using const_global_iterator = GlobalListType::const_iterator
The Global Variable constant iterator.
using iterator = FunctionListType::iterator
The Function iterators.
using const_iterator = FunctionListType::const_iterator
The Function constant iterator.
using reverse_iterator = FunctionListType::reverse_iterator
The Function reverse iterator.
using const_reverse_iterator = FunctionListType::const_reverse_iterator
The Function constant reverse iterator.
using alias_iterator = AliasListType::iterator
The Global Alias iterators.
using const_alias_iterator = AliasListType::const_iterator
The Global Alias constant iterator.
using ifunc_iterator = IFuncListType::iterator
The Global IFunc iterators.
using const_ifunc_iterator = IFuncListType::const_iterator
The Global IFunc constant iterator.
using named_metadata_iterator = NamedMDListType::iterator
The named metadata iterators.
using const_named_metadata_iterator = NamedMDListType::const_iterator
The named metadata constant iterators.
static bool isValidModFlagBehavior (Metadata *MD, ModFlagBehavior &MFB)
Checks if Metadata represents a valid ModFlagBehavior, and stores the converted result in MFB.
Member Variables
class Constant
Direct access to the globals list, functions list, and symbol table
static GlobalListType Module::* getSublistAccess (GlobalVariable *)
static FunctionListType Module::* getSublistAccess (Function *)
static AliasListType Module::* getSublistAccess (GlobalAlias *)
static IFuncListType Module::* getSublistAccess (GlobalIFunc *)
static NamedMDListType Module::* getSublistAccess (NamedMDNode *)
const GlobalListType & getGlobalList () const
Get the Module's list of global variables (constant).
GlobalListType & getGlobalList ()
Get the Module's list of global variables.
const FunctionListType & getFunctionList () const
Get the Module's list of functions (constant).
FunctionListType & getFunctionList ()
Get the Module's list of functions.
const AliasListType & getAliasList () const
Get the Module's list of aliases (constant).
AliasListType & getAliasList ()
Get the Module's list of aliases.
const IFuncListType & getIFuncList () const
Get the Module's list of ifuncs (constant).
IFuncListType & getIFuncList ()
Get the Module's list of ifuncs.
const NamedMDListType & getNamedMDList () const
Get the Module's list of named metadata (constant).
NamedMDListType & getNamedMDList ()
Get the Module's list of named metadata.
const ValueSymbolTable & getValueSymbolTable () const
Get the symbol table of global variable and function identifiers.
ValueSymbolTable & getValueSymbolTable ()
Get the Module's symbol table of global variable and function identifiers.
const ComdatSymTabType & getComdatSymbolTable () const
Get the Module's symbol table for COMDATs (constant).
ComdatSymTabType & getComdatSymbolTable ()
Get the Module's symbol table for COMDATs.
Convenience iterators
using global_object_iterator = concat_iterator< GlobalObject, iterator, global_iterator >
using const_global_object_iterator = concat_iterator< const GlobalObject, const_iterator, const_global_iterator >
using global_value_iterator = concat_iterator< GlobalValue, iterator, global_iterator, alias_iterator, ifunc_iterator >
using const_global_value_iterator = concat_iterator< const GlobalValue, const_iterator, const_global_iterator, const_alias_iterator, const_ifunc_iterator >
iterator_range< global_object_iterator > global_objects ()
iterator_range< const_global_object_iterator > global_objects () const
iterator_range< global_value_iterator > global_values ()
iterator_range< const_global_value_iterator > global_values () const
Detailed Description
A Module instance is used to store all the information related to an LLVM module.
Modules are the top level container of all other LLVM Intermediate Representation (IR) objects. Each module directly contains a list of globals variables, a list of functions, a list of libraries (or other modules) this module depends on, a symbol table, and various data about the target's characteristics.
A module maintains a GlobalValRefMap object that is used to hold all constant references to global variables in the module. When a global variable is destroyed, it should have no entries in the GlobalValueRefMap. The main container class for the LLVM Intermediate Representation.
Definition at line 66 of file Module.h.
Member Typedef Documentation
alias_iterator
using llvm::Module::alias_iterator = AliasListType::iterator
The Global Alias iterators.
Definition at line 99 of file Module.h.
AliasListType
using llvm::Module::AliasListType = SymbolTableList<GlobalAlias>
The type for the list of aliases.
Definition at line 75 of file Module.h.
ComdatSymTabType
using llvm::Module::ComdatSymTabType = StringMap<Comdat>
The type of the comdat "symbol" table.
Definition at line 81 of file Module.h.
const_alias_iterator
using llvm::Module::const_alias_iterator = AliasListType::const_iterator
The Global Alias constant iterator.
Definition at line 101 of file Module.h.
const_global_iterator
using llvm::Module::const_global_iterator = GlobalListType::const_iterator
The Global Variable constant iterator.
Definition at line 86 of file Module.h.
const_global_object_iterator
using llvm::Module::const_global_object_iterator = concat_iterator<const GlobalObject, const_iterator, const_global_iterator>
Definition at line 661 of file Module.h.
const_global_value_iterator
using llvm::Module::const_global_value_iterator = concat_iterator<const GlobalValue, const_iterator, const_global_iterator, const_alias_iterator, const_ifunc_iterator>
Definition at line 671 of file Module.h.
const_ifunc_iterator
using llvm::Module::const_ifunc_iterator = IFuncListType::const_iterator
The Global IFunc constant iterator.
Definition at line 106 of file Module.h.
const_iterator
using llvm::Module::const_iterator = FunctionListType::const_iterator
The Function constant iterator.
Definition at line 91 of file Module.h.
const_named_metadata_iterator
using llvm::Module::const_named_metadata_iterator = NamedMDListType::const_iterator
The named metadata constant iterators.
Definition at line 111 of file Module.h.
const_reverse_iterator
using llvm::Module::const_reverse_iterator = FunctionListType::const_reverse_iterator
The Function constant reverse iterator.
Definition at line 96 of file Module.h.
FunctionListType
using llvm::Module::FunctionListType = SymbolTableList<Function>
The type for the list of functions.
Definition at line 73 of file Module.h.
global_iterator
using llvm::Module::global_iterator = GlobalListType::iterator
The Global Variable iterator.
Definition at line 84 of file Module.h.
global_object_iterator
using llvm::Module::global_object_iterator = concat_iterator<GlobalObject, iterator, global_iterator>
Definition at line 658 of file Module.h.
global_value_iterator
using llvm::Module::global_value_iterator = concat_iterator<GlobalValue, iterator, global_iterator, alias_iterator, ifunc_iterator>
Definition at line 668 of file Module.h.
GlobalListType
using llvm::Module::GlobalListType = SymbolTableList<GlobalVariable>
The type for the list of global variables.
Definition at line 71 of file Module.h.
ifunc_iterator
using llvm::Module::ifunc_iterator = IFuncListType::iterator
The Global IFunc iterators.
Definition at line 104 of file Module.h.
IFuncListType
using llvm::Module::IFuncListType = SymbolTableList<GlobalIFunc>
The type for the list of ifuncs.
Definition at line 77 of file Module.h.
iterator
using llvm::Module::iterator = FunctionListType::iterator
The Function iterators.
Definition at line 89 of file Module.h.
named_metadata_iterator
using llvm::Module::named_metadata_iterator = NamedMDListType::iterator
The named metadata iterators.
Definition at line 109 of file Module.h.
NamedMDListType
using llvm::Module::NamedMDListType = ilist<NamedMDNode>
The type for the list of named metadata.
Definition at line 79 of file Module.h.
reverse_iterator
using llvm::Module::reverse_iterator = FunctionListType::reverse_iterator
The Function reverse iterator.
Definition at line 94 of file Module.h.
Member Enumeration Documentation
ModFlagBehavior
enum llvm::Module::ModFlagBehavior
This enumeration defines the supported behaviors of module flags.
Enumerator
Error
Emits an error if two values disagree, otherwise the resulting value is that of the operands.
Warning
Emits a warning if two values disagree.
The result value will be the operand for the flag from the first module being linked.
Require
Adds a requirement that another module flag be present and have a specified value after linking is performed.
The value must be a metadata pair, where the first element of the pair is the ID of the module flag to be restricted, and the second element of the pair is the value the module flag should be restricted to. This behavior can be used to restrict the allowable results (via triggering of an error) of linking IDs with the Override behavior.
Override
Uses the specified value, regardless of the behavior or value of the other module.
If both modules specify Override, but the values differ, an error will be emitted.
Append
Appends the two values, which are required to be metadata nodes.
AppendUnique
Appends the two values, which are required to be metadata nodes.
However, duplicate entries in the second list are dropped during the append operation.
Max
Takes the max of the two values, which are required to be integers.
ModFlagBehaviorFirstVal
ModFlagBehaviorLastVal
Definition at line 114 of file Module.h.
Constructor & Destructor Documentation
Module()
Module::Module (StringRef ModuleID, LLVMContext & C) explicit
The Module constructor.
Note that there is no default constructor. You must provide a name for the module upon construction.
Definition at line 73 of file Module.cpp.
~Module()
Module::~Module ()
The module destructor. This will dropAllReferences.
Definition at line 80 of file Module.cpp.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::clear(), and dropAllReferences().
Member Function Documentation
addModuleFlag() [1/4]
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata * Val)
Add a module-level flag to the module-level flags metadata.
addModuleFlag - Add a module-level flag to the module-level flags metadata.
It will create the module-level flags named metadata if it doesn't already exist.
Definition at line 337 of file Module.cpp.
References llvm::NamedMDNode::addOperand(), llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm::Type::getInt32Ty(), getOrInsertModuleFlagsMetadata(), and Int32Ty.
Referenced by addModuleFlag(), llvm::orc::cloneModuleFlagsMetadata(), getNamedGlobal(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::CGProfilePass::run(), setCodeModel(), setPICLevel(), setPIELevel(), setProfileSummary(), setRtLibUseGOT(), setSDKVersion(), llvm::UpgradeModuleFlags(), and UpgradeRetainReleaseMarker().
addModuleFlag() [2/4]
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Constant * Val)
Definition at line 345 of file Module.cpp.
References addModuleFlag(), and llvm::ConstantAsMetadata::get().
addModuleFlag() [3/4]
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, uint32_t Val)
Definition at line 349 of file Module.cpp.
References addModuleFlag(), llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), and Int32Ty.
addModuleFlag() [4/4]
void Module::addModuleFlag (MDNode * Node)
Definition at line 354 of file Module.cpp.
alias_begin() [1/2]
alias_iterator llvm::Module::alias_begin () inline
Definition at line 621 of file Module.h.
Referenced by aliases(), getMinVisibility(), LLVMGetFirstGlobalAlias(), LLVMGetLastGlobalAlias(), LLVMGetPreviousGlobalAlias(), and OptimizeGlobalAliases().
alias_begin() [2/2]
const_alias_iterator llvm::Module::alias_begin () const inline
Definition at line 622 of file Module.h.
alias_empty()
bool llvm::Module::alias_empty () const inline
Definition at line 626 of file Module.h.
alias_end() [1/2]
alias_iterator llvm::Module::alias_end () inline
Definition at line 623 of file Module.h.
Referenced by aliases(), getMinVisibility(), LLVMGetFirstGlobalAlias(), LLVMGetLastGlobalAlias(), LLVMGetNextGlobalAlias(), and OptimizeGlobalAliases().
alias_end() [2/2]
const_alias_iterator llvm::Module::alias_end () const inline
Definition at line 624 of file Module.h.
alias_size()
size_t llvm::Module::alias_size () const inline
Definition at line 625 of file Module.h.
Referenced by llvm::NVPTXAsmPrinter::doInitialization().
aliases() [1/2]
iterator_range<alias_iterator> llvm::Module::aliases () inline
Definition at line 628 of file Module.h.
References alias_begin(), alias_end(), and llvm::make_range().
Referenced by dropAllReferences(), llvm::filterDeadComdatFunctions(), findPartitions(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), global_values(), llvm::nameUnamedGlobals(), orderModule(), rewriteComdat(), and llvm::TypeFinder::run().
aliases() [2/2]
iterator_range<const_alias_iterator> llvm::Module::aliases () const inline
Definition at line 631 of file Module.h.
References alias_begin(), alias_end(), and llvm::make_range().
appendModuleInlineAsm()
void llvm::Module::appendModuleInlineAsm (StringRef Asm) inline
Append to the module-scope inline assembly blocks.
A trailing newline is added if the input doesn't have one.
Definition at line 296 of file Module.h.
References llvm::HexStyle::Asm, getIdentifiedStructTypes(), getMDKindID(), getMDKindNames(), getNamedValue(), getOperandBundleTags(), getOrInsertFunction(), getTypeByName(), and Name.
begin() [1/2]
iterator llvm::Module::begin () inline
Definition at line 599 of file Module.h.
Referenced by llvm::PMDataManager::emitInstrCountChangedRemark(), FindCXAAtExit(), functions(), getMinVisibility(), INITIALIZE_PASS_BEGIN(), LLVMGetFirstFunction(), LLVMGetLastFunction(), LLVMGetPreviousFunction(), OptimizeFunctions(), removeUseSoftFloat(), llvm::HotColdSplitting::run(), llvm::DeadArgumentEliminationPass::run(), stripDeadPrototypes(), useFuncSeen(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit(), and writeIdentificationBlock().
begin() [2/2]
const_iterator llvm::Module::begin () const inline
Definition at line 600 of file Module.h.
createRNG()
std::unique_ptr< RandomNumberGenerator > Module::createRNG (const Pass * P) const
Get a RandomNumberGenerator salted for use with this module.
The RNG can be seeded via -rng-seed=<uint64> and is salted with the ModuleID and the provided pass salt. The returned RNG should not be shared across threads or passes.
A unique RNG per pass ensures a reproducible random stream even when other randomness consuming passes are added or removed. In addition, the random stream will be reproducible across LLVM versions when the pass does not change.
Definition at line 92 of file Module.cpp.
References llvm::sys::path::filename(), getModuleIdentifier(), and llvm::Pass::getPassName().
Referenced by getModuleInlineAsm().
debug_compile_units()
iterator_range<debug_compile_units_iterator> llvm::Module::debug_compile_units () const inline
Return an iterator for all DICompileUnits listed in this Module's llvm.dbg.cu named metadata node and aren't explicitly marked as NoDebug.
Definition at line 751 of file Module.h.
References llvm::collectUsedGlobalVariables(), dropAllReferences(), dropTriviallyDeadConstantArrays(), dump(), getCodeModel(), getCodeViewFlag(), getDwarfVersion(), getNamedMetadata(), getNumberRegisterParameters(), getPICLevel(), getPIELevel(), getProfileSummary(), getRtLibUseGOT(), getSDKVersion(), llvm::make_range(), llvm::AArch64CC::PL, print(), setCodeModel(), setOwnedMemoryBuffer(), setPICLevel(), setPIELevel(), setProfileSummary(), setRtLibUseGOT(), and setSDKVersion().
Referenced by llvm::DwarfDebug::beginModule(), llvm::NVPTXAsmPrinter::doInitialization(), INITIALIZE_PASS(), llvm::MachineModuleInfoWrapperPass::MachineModuleInfoWrapperPass(), llvm::DebugInfoFinder::processModule(), and llvm::MachineModuleAnalysis::run().
debug_compile_units_begin()
debug_compile_units_iterator llvm::Module::debug_compile_units_begin () const inline
Definition at line 738 of file Module.h.
References getNamedMetadata().
Referenced by llvm::DwarfDebug::beginModule().
debug_compile_units_end()
debug_compile_units_iterator llvm::Module::debug_compile_units_end () const inline
Definition at line 743 of file Module.h.
References getNamedMetadata().
Referenced by llvm::DwarfDebug::beginModule().
dropAllReferences()
void Module::dropAllReferences ()
This function causes all the subinstructions to "let go" of all references that they are maintaining.
This allows one to 'delete' a whole class at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is delete'd for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 455 of file Module.cpp.
References aliases(), llvm::Function::dropAllReferences(), F(), globals(), and ifuncs().
Referenced by debug_compile_units(), and ~Module().
dropTriviallyDeadConstantArrays()
void Module::dropTriviallyDeadConstantArrays ()
Destroy ConstantArrays in LLVMContext if they are not used.
ConstantArrays constructed during linking can cause quadratic memory explosion. Releasing all unused constants can cause a 20% LTO compile-time slowdown for a large application.
NOTE: Constants are currently owned by LLVMContext. This can then only be called where all uses of the LLVMContext are understood.
Definition at line 159 of file LLVMContextImpl.cpp.
References Context, llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), and llvm::LLVMContext::pImpl.
Referenced by debug_compile_units(), and llvm::IRMover::move().
dump()
LLVM_DUMP_METHOD void Module::dump () const
Dump the module to stderr (for debugging).
Definition at line 4474 of file AsmWriter.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
Referenced by debug_compile_units().
empty()
bool llvm::Module::empty () const inline
Definition at line 608 of file Module.h.
Referenced by llvm::symbolize::SymbolizableObjectFile::create(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), and llvm::IRMutationStrategy::mutate().
end() [1/2]
iterator llvm::Module::end () inline
Definition at line 601 of file Module.h.
Referenced by llvm::PMDataManager::emitInstrCountChangedRemark(), FindCXAAtExit(), functions(), getMinVisibility(), INITIALIZE_PASS_BEGIN(), LLVMGetFirstFunction(), LLVMGetLastFunction(), LLVMGetNextFunction(), OptimizeFunctions(), removeUseSoftFloat(), llvm::DeadArgumentEliminationPass::run(), stripDeadPrototypes(), useFuncSeen(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit(), and writeIdentificationBlock().
end() [2/2]
const_iterator llvm::Module::end () const inline
Definition at line 602 of file Module.h.
eraseNamedMetadata()
void Module::eraseNamedMetadata (NamedMDNode * NMD)
Remove the given NamedMDNode from this module and delete it.
eraseNamedMetadata - Remove the given NamedMDNode from this module and delete it.
Definition at line 272 of file Module.cpp.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::ilist_node_impl< OptionsT >::getIterator(), and llvm::NamedMDNode::getName().
Referenced by getNamedGlobal(), and UpgradeRetainReleaseMarker().
functions() [1/2]
iterator_range<iterator> llvm::Module::functions () inline
Definition at line 610 of file Module.h.
References begin(), end(), and llvm::make_range().
Referenced by collectFunctionUsers(), llvm::filterDeadComdatFunctions(), findPartitions(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), global_objects(), global_values(), inferAllPrototypeAttributes(), llvm::DebugInfoFinder::processModule(), rewriteComdat(), llvm::ForceFunctionAttrsPass::run(), NewPMDebugifyPass::run(), NewPMCheckDebugifyPass::run(), llvm::PrintModulePass::run(), llvm::ImportedFunctionsInliningStatistics::setModuleInfo(), and shouldKeepInEntry().
functions() [2/2]
iterator_range<const_iterator> llvm::Module::functions () const inline
Definition at line 613 of file Module.h.
References begin(), end(), and llvm::make_range().
getAliasList() [1/2]
const AliasListType& llvm::Module::getAliasList () const inline
Get the Module's list of aliases (constant).
Definition at line 542 of file Module.h.
Referenced by llvm::GlobalAlias::eraseFromParent(), llvm::GlobalIndirectSymbol::getBaseObject(), maybeSetDSOLocal(), OptimizeGlobalAliases(), and llvm::GlobalAlias::removeFromParent().
getAliasList() [2/2]
AliasListType& llvm::Module::getAliasList () inline
Get the Module's list of aliases.
Definition at line 544 of file Module.h.
getCodeModel()
Optional< CodeModel::Model > Module::getCodeModel () const
Returns the code model (tiny, small, kernel, medium or large model)
Definition at line 532 of file Module.cpp.
References getModuleFlag(), and llvm::None.
Referenced by llvm::lto::Config::addSaveTemps(), and debug_compile_units().
getCodeViewFlag()
unsigned Module::getCodeViewFlag () const
Returns the CodeView Version by checking module flags.
Returns zero if not present in module.
Definition at line 484 of file Module.cpp.
References getModuleFlag().
Referenced by debug_compile_units(), llvm::X86FrameLowering::emitPrologue(), and llvm::X86AsmPrinter::runOnMachineFunction().
getComdatSymbolTable() [1/2]
const ComdatSymTabType& llvm::Module::getComdatSymbolTable () const inline
Get the Module's symbol table for COMDATs (constant).
Definition at line 574 of file Module.h.
Referenced by createGlobalFwdRef(), getMinVisibility(), llvm::InternalizePass::internalizeModule(), and rewriteComdat().
getComdatSymbolTable() [2/2]
ComdatSymTabType& llvm::Module::getComdatSymbolTable () inline
Get the Module's symbol table for COMDATs.
Definition at line 576 of file Module.h.
getContext()
LLVMContext& llvm::Module::getContext () const inline
Get the global data context.
Returns
LLVMContext - a container for LLVM's global information
Definition at line 245 of file Module.h.
References Context.
Referenced by AddCalls(), llvm::LTOCodeGenerator::addModule(), llvm::RegAllocBase::allocatePhysRegs(), llvm::AMDGPUMachineModuleInfo::AMDGPUMachineModuleInfo(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), annotateAllFunctions(), llvm::annotateValueSite(), appendToGlobalArray(), appendToUsedList(), assureFPCallStub(), llvm::CloneModule(), collectFunctionUsers(), llvm::createAMDGPUPrintfRuntimeBinding(), createDevirtTriggerFunc(), llvm::MIRParserImpl::createDummyFunction(), createEmptyFunction(), createFPFnStub(), createFree(), CreateGCRelocates(), llvm::createIRLevelProfileFlagVar(), llvm::createPGOFuncNameVar(), createPrivateGlobalForSourceLoc(), llvm::createPrivateGlobalForString(), createPrivateNonConstGlobalForString(), llvm::createProfileFileNameVar(), llvm::createSampleProfileLoaderPass(), llvm::createSanitizerCtorAndInitFunctions(), llvm::createThreadSanitizerLegacyPassPass(), createWrapper(), llvm::createX86RetpolineThunksPass(), llvm::declareSanitizerInitFunction(), doImportingForModule(), llvm::EmbedBitcodeInModule(), llvm::orc::IRSpeculationLayer::emit(), llvm::MachineInstr::emitError(), EmitGCCInlineAsmStr(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::emitMemCpyChk(), EmitMSInlineAsmStr(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::CodeExtractor::findInputsOutputs(), llvm::SanitizerStatReport::finish(), fixupFPReturnAndCall(), llvm::objcarc::ARCMDKindCache::get(), getChainID(), llvm::getCopyDeclaration(), GetCtorAndDtorPriority(), llvm::Intrinsic::getDeclaration(), getDefaultPersonalityFn(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), llvm::AMDGPUMangledLibFunc::getFunctionType(), llvm::TargetLoweringBase::getIRStackGuard(), getMinVisibility(), llvm::getOrCreateInitFunction(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), llvm::AMDGPULibFunc::getOrInsertFunction(), getOrInsertGlobal(), getOrInsertValueProfilingCall(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), getSignature(), llvm::InstrProfIncrementInst::getStep(), getSubprogram(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), llvm::FunctionImporter::importFunctions(), INITIALIZE_PASS(), llvm::omp::types::initializeTypes(), insertLifetimeMarkersSurroundingCall(), InsertSafepointPoll(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), llvm::TargetLoweringBase::insertSSPDeclarations(), insertUseHolderAfter(), instrumentMaskedLoadOrStore(), instrumentOneFunc(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), isPromotedResultSafe(), llvm::log2(), MarkBlocksLiveIn(), llvm::IRMutator::mutateModule(), needsRuntimeRegistrationOfSectionRange(), PushArgMD(), llvm::CGProfilePass::run(), llvm::ScalarizerPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::legacy::PassManagerImpl::run(), llvm::Float2IntPass::runImpl(), llvm::SanitizerStatReport::SanitizerStatReport(), llvm::setIrrLoopHeaderMetadata(), llvm::setProfMetadata(), llvm::VFABI::setVectorVariantNames(), shouldEmitInstrCountChangedRemark(), llvm::ModulePass::skipModule(), llvm::CallGraphSCCPass::skipSCC(), srcMgrDiagHandler(), llvm::stripNonLineTableDebugInfo(), StripSymbolNames(), SwitchToLookupTable(), llvm::lto::thinBackend(), llvm::UpgradeDebugInfo(), llvm::UpgradeModuleFlags(), UpgradeRetainReleaseMarker(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getDataLayout()
const DataLayout & Module::getDataLayout () const
Get the data layout for the module's target platform.
Definition at line 369 of file Module.cpp.
Referenced by AddAlignmentAssumptions(), addBoundsChecking(), AddCalls(), llvm::LoopAccessInfo::addRuntimeChecks(), llvm::IVUsers::AddUsersImpl(), allCallersPassValidPointerForArgument(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::GlobalsAAResult::analyzeModule(), llvm::orc::LLJIT::applyDataLayout(), buildFrameType(), llvm::AAResults::callCapturesBefore(), llvm::objcarc::CanAlterRefCount(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), llvm::objcarc::CanUse(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneFunction(), llvm::CloneModule(), llvm::FunctionComparator::cmpOperations(), llvm::FunctionComparator::cmpTypes(), collectFunctionUsers(), combineInstructionsOverFunction(), computeAddrSpace(), llvm::computeLegalValueVTs(), computeRecurrenceType(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCall(), llvm::copyMetadataForLoad(), llvm::SanitizerStatReport::create(), llvm::Function::Create(), llvm::IRBuilder< TargetFolder >::CreateAlloca(), llvm::createAMDGPUFunctionInliningPass(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createCodeGenPreparePass(), llvm::createConstantPropagationPass(), createGlobalFwdRef(), createHWLoopAnalysis(), llvm::createLegacyPMBasicAAResult(), createMaskInstrs(), llvm::createMemDerefPrinter(), llvm::createThreadSanitizerLegacyPassPass(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::AMDGPUAAWrapperPass::doInitialization(), llvm::objcarc::ObjCARCAAWrapperPass::doInitialization(), doPromotion(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), eliminateDeadStores(), eliminateTailRecursion(), llvm::AsmPrinter::EmitAlignment(), llvm::emitCalloc(), EmitCamlGlobal(), llvm::AsmPrinter::EmitDebugValue(), llvm::AsmPrinter::emitGlobalGOTEquivs(), llvm::AMDGPUAsmPrinter::EmitGlobalVariable(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::LazyValueInfo::eraseBlock(), llvm::FindAvailablePtrLoadStore(), findFuncPointers(), findLoadCallsAtConstantOffset(), findPHIToPartitionLoops(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), llvm::MCJIT::generateCodeForModule(), llvm::MemoryLocation::get(), getAlignment(), getAllocaSizeInBytes(), llvm::IRTranslator::getAnalysisUsage(), getAtomicOpAlign(), getAtomicOpSize(), llvm::getBestSimplifyQuery(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), llvm::LLParser::getContext(), GetCtorAndDtorPriority(), llvm::AsmPrinter::getDataLayout(), llvm::MachineFunction::getDataLayout(), llvm::ScalarEvolution::getDataLayout(), getDataLayoutStr(), llvm::DemandedBits::getDemandedBits(), getEdgeValueLocal(), llvm::AMDGPUSubtarget::getExplicitKernArgSize(), getFirstNonAllocaInTheEntryBlock(), llvm::getGEPInductionOperand(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::getInlineCost(), getIntrinsicForMaskedAtomicRMWBinOp(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::MemoryDependenceResults::getLoadLoadClobberFullWidthSize(), llvm::ExecutionEngine::getMangledName(), getMinVisibility(), llvm::GlobalsAAResult::getModRefBehavior(), llvm::Mangler::getNameWithPrefix(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), getOrInsertGlobal(), llvm::getPointerAtOffset(), GetPointerOperand(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateOnEdge(), llvm::getPtrStride(), llvm::SCEVExpander::getRelatedExistingExpansion(), GetRMWLibcall(), getScalarIntrinsicDeclaration(), llvm::TargetLoweringObjectFile::getSectionForJumpTable(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::MipsTargetMachine::getTargetTransformInfo(), llvm::TargetMachine::getTargetTransformInfo(), llvm::HexagonTargetLowering::getTgtMemIntrinsic(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), getTypePartition(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), getVectorType(), GlobalWasGeneratedByCompiler(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::CallLowering::handleAssignments(), HandleByValArgument(), HandleByValArgumentInit(), handleEndBlock(), handleFree(), hasProfileData(), hasUndefContents(), llvm::hoistRegion(), llvm::DataLayout::init(), INITIALIZE_PASS(), llvm::InlineFunction(), insertIfNamed(), insertLifetimeMarkersSurroundingCall(), instrumentMaskedLoadOrStore(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::orc::IRMaterializationUnit::IRMaterializationUnit(), llvm::isAllocaPromotable(), isAlwaysLive(), isAtomic(), llvm::isDereferenceableAndAlignedInLoop(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isIgnorableInst(), llvm::InductionDescriptor::isInductionPHI(), llvm::isLegalToPromote(), isLoadConditional(), isLoadInvariantInLoop(), isObjectDereferencedInBlock(), isOnlyReachableViaThisEdge(), IsOperandAMemoryOperand(), isPointerValueDeadOnEntryToFunction(), llvm::AArch64TargetLowering::isProfitableToHoist(), isPromotedResultSafe(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), llvm::isSafeToSpeculativelyExecute(), IsSmallObject(), llvm::LoopVectorizationLegality::isUniform(), isZero(), llvm::AArch64TargetLowering::isZExtFree(), llvm::LibCallSimplifier::LibCallSimplifier(), llvm::X86CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::CallLowering::lowerCall(), lowerConstantIntrinsics(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), MarkBlocksLiveIn(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), maybePrintCallAddrSpace(), maybePrintComdat(), mayUsePostIncMode(), memOpsHaveSameBasePtr(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), mergeInlinedArrayAllocas(), mightWriteIntoAllocaPtr(), moveUp(), operator<<(), OptimizeGlobalVars(), patchAndReplaceAllUsesWith(), performGlobalAddressCombine(), llvm::PointerMayBeCaptured(), postDominates(), llvm::MemoryDepChecker::Dependence::print(), llvm::JumpThreadingPass::ProcessBlock(), processInternalGlobal(), llvm::promoteLoopAccessesToScalars(), ReduceLoopStrength(), relocationViaAlloca(), llvm::replaceAllDbgUsesWith(), replaceAndRecursivelySimplifyImpl(), replaceFrameSize(), ReplaceUsesOfWith(), reportMayClobberedLoad(), RetagMask(), llvm::returnTypeIsEligibleForTailCall(), llvm::LoopFusePass::run(), llvm::LoopRotatePass::run(), llvm::NewGVNPass::run(), llvm::IndVarSimplifyPass::run(), llvm::GlobalOptPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::LoopIdiomRecognizePass::run(), llvm::IPSCCPPass::run(), llvm::EarlyCSEPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::InstSimplifyPass::run(), llvm::SCCPPass::run(), llvm::AAEvaluator::run(), llvm::AMDGPUAA::run(), llvm::objcarc::ObjCARCAA::run(), llvm::LazyValueAnalysis::run(), llvm::BasicAA::run(), llvm::TargetIRAnalysis::run(), llvm::SLPVectorizerPass::runImpl(), llvm::NaryReassociatePass::runImpl(), llvm::ConstantHoistingPass::runImpl(), runImpl(), llvm::LazyValueInfoWrapperPass::runOnFunction(), llvm::BasicAAWrapperPass::runOnFunction(), llvm::IRTranslator::runOnMachineFunction(), selectELFSectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), llvm::HexagonTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::HexagonTargetObjectFile::shouldPutJumpTableInFunctionSection(), llvm::simplifyCFG(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), simplifyX86vpermv(), AllocaSlices::SliceBuilder::SliceBuilder(), splitGlobal(), splitMergedValStore(), splitRetconCoroutine(), StackMallocSizeClass(), llvm::LazyValueInfo::threadEdge(), llvm::JumpThreadingPass::ThreadGuard(), TryToShrinkGlobalToBoolean(), tryToVectorizeHorReductionOrInstOperands(), TypeSizeToSizeIndex(), llvm::UnrollRuntimeLoopRemainder(), llvm::updateIndexWPDForExports(), llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::updatePointer(), valueCoversEntireFragment(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), llvm::LoopVersioning::versionLoop(), visitIVCast(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getDataLayoutStr()
const std::string& llvm::Module::getDataLayoutStr () const inline
Get the data layout string for the module's target platform.
This is equivalent to getDataLayout()->getStringRepresentation().
Definition at line 232 of file Module.h.
References getDataLayout(), and llvm::DataLayout::getStringRepresentation().
Referenced by getStringEncoding().
getDwarfVersion()
unsigned Module::getDwarfVersion () const
Returns the Dwarf Version by checking module flags.
Definition at line 477 of file Module.cpp.
References getModuleFlag().
Referenced by debug_compile_units(), and llvm::DwarfDebug::DwarfDebug().
getFunction()
Function * Module::getFunction (StringRef Name) const
Look up the specified function in the module symbol table.
If it does not exist, return null.
Definition at line 174 of file Module.cpp.
References getNamedValue().
Referenced by addMappingsFromTLI(), assureFPCallStub(), containsProfilingIntrinsics(), llvm::createAMDGPUPrintfRuntimeBinding(), createDevirtTriggerFunc(), explicifyGuards(), FindCXAAtExit(), llvm::sampleprof::FunctionSamples::findInlinedFunctions(), llvm::MCJIT::findModuleForSymbol(), llvm::getOrCreateInitFunction(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), getOrInsertFunction(), getSignature(), llvm::AArch64TargetLowering::getSSPStackGuardCheck(), llvm::ARMTargetLowering::getSSPStackGuardCheck(), llvm::X86TargetLowering::getSSPStackGuardCheck(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), llvm::VFABI::getVectorVariantNames(), hasReturnsTwiceAttr(), llvm::inferLibFuncAttributes(), InsertSafepointPoll(), instrumentMaskedLoadOrStore(), isDirectCall(), isEmptyFunction(), lowerGuardIntrinsic(), lowerWidenableCondition(), needsRuntimeRegistrationOfSectionRange(), llvm::MIRParserImpl::parseMachineFunction(), prepareForSplit(), replaceAllPrepares(), replaceDevirtTrigger(), rewriteComdat(), llvm::JumpThreadingPass::runImpl(), llvm::ScalarEvolution::ScalarEvolution(), shouldKeepInEntry(), splitGlobals(), llvm::stripNonLineTableDebugInfo(), StripSymbolNames(), unswitchBestCondition(), and llvm::UpgradeARCRuntime().
getFunctionList() [1/2]
const FunctionListType& llvm::Module::getFunctionList () const inline
Get the Module's list of functions (constant).
Definition at line 534 of file Module.h.
Referenced by computeAddrSpace(), createCloneDeclaration(), llvm::AsmPrinter::doInitialization(), doPromotion(), llvm::orc::IRSpeculationLayer::emit(), getRetComponentType(), PushArgMD(), llvm::Attributor::registerFunctionSignatureRewrite(), and llvm::CallGraph::removeFunctionFromModule().
getFunctionList() [2/2]
FunctionListType& llvm::Module::getFunctionList () inline
Get the Module's list of functions.
Definition at line 536 of file Module.h.
getGlobalList() [1/2]
const GlobalListType& llvm::Module::getGlobalList () const inline
Get the Module's list of global variables (constant).
Definition at line 525 of file Module.h.
Referenced by llvm::NVPTXAsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::GlobalVariable::eraseFromParent(), llvm::GlobalVariable::GlobalVariable(), maybeSetDSOLocal(), OptimizeGlobalAddressOfMalloc(), llvm::GlobalVariable::removeFromParent(), removeGlobalCtors(), SRAGlobal(), TryToShrinkGlobalToBoolean(), and llvm::updateIndexWPDForExports().
getGlobalList() [2/2]
GlobalListType& llvm::Module::getGlobalList () inline
Get the Module's list of global variables.
Definition at line 527 of file Module.h.
getGlobalVariable() [1/3]
GlobalVariable* llvm::Module::getGlobalVariable (StringRef Name) const inline
Look up the specified global variable in the module symbol table.
If it does not exist, return null. If AllowInternal is set to true, this function will return types that have InternalLinkage. By default, these types are not returned.
Definition at line 391 of file Module.h.
Referenced by appendToUsedList(), llvm::collectUsedGlobalVariables(), llvm::EmbedBitcodeInModule(), findGlobalCtors(), llvm::MCJIT::findModuleForSymbol(), getGlobalVariable(), getNamedGlobal(), llvm::AArch64TargetLowering::getSDagStackGuard(), llvm::ARMTargetLowering::getSDagStackGuard(), llvm::X86TargetLowering::getSDagStackGuard(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), mergeConstants(), needsRuntimeRegistrationOfSectionRange(), rewriteComdat(), and StripSymbolNames().
getGlobalVariable() [2/3]
GlobalVariable * Module::getGlobalVariable (StringRef Name, bool AllowLocal) const
getGlobalVariable - Look up the specified global variable in the module symbol table.
If it does not exist, return null. The type argument should be the underlying type of the global, i.e., it should not have the top-level PointerType, which represents the address of the global. If AllowLocal is set to true, this function will return types that have an local. By default, these types are not returned.
Definition at line 189 of file Module.cpp.
References getNamedValue().
getGlobalVariable() [3/3]
GlobalVariable* llvm::Module::getGlobalVariable (StringRef Name, bool AllowInternal = false) inline
Definition at line 397 of file Module.h.
References getGlobalVariable().
getIdentifiedStructTypes()
std::vector< StructType * > Module::getIdentifiedStructTypes () const
Definition at line 434 of file Module.cpp.
References llvm::TypeFinder::begin(), llvm::TypeFinder::end(), llvm::MipsISD::Ret, and llvm::TypeFinder::run().
Referenced by appendModuleInlineAsm().
getIFuncList() [1/2]
const IFuncListType& llvm::Module::getIFuncList () const inline
Get the Module's list of ifuncs (constant).
Definition at line 551 of file Module.h.
Referenced by llvm::GlobalIFunc::eraseFromParent(), maybeSetDSOLocal(), llvm::GlobalIFunc::removeFromParent(), and llvm::GlobalAlias::setAliasee().
getIFuncList() [2/2]
IFuncListType& llvm::Module::getIFuncList () inline
Get the Module's list of ifuncs.
Definition at line 553 of file Module.h.
getInstructionCount()
unsigned Module::getInstructionCount ()
Returns the number of non-debug IR instructions in the module.
This is equivalent to the sum of the IR instruction counts of each function contained in the module.
Definition at line 491 of file Module.cpp.
References F().
Referenced by llvm::FPPassManager::doFinalization(), and getModuleIdentifier().
getMaterializer()
GVMaterializer* llvm::Module::getMaterializer () const inline
Retrieves the GVMaterializer, if any, for this Module.
Definition at line 508 of file Module.h.
Referenced by isMaterialized().
getMDKindID()
unsigned Module::getMDKindID (StringRef Name) const
Return a unique non-zero ID for the specified metadata kind.
getMDKindID - Return a unique non-zero ID for the specified metadata kind.
This ID is uniqued across modules in the current LLVMContext.
Definition at line 119 of file Module.cpp.
References llvm::LLVMContext::getMDKindID().
Referenced by appendModuleInlineAsm(), and parseOptionalLinkageAux().
getMDKindNames()
void Module::getMDKindNames (SmallVectorImpl< StringRef > & Result) const
Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
getMDKindNames - Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
ID #0 is not used, so it is filled in as an empty string.
Definition at line 126 of file Module.cpp.
References llvm::LLVMContext::getMDKindNames().
Referenced by appendModuleInlineAsm().
getModuleFlag()
Metadata * Module::getModuleFlag (StringRef Key) const
Return the corresponding value if Key appears in module flags, otherwise return null.
Definition at line 310 of file Module.cpp.
References getModuleFlagsMetadata().
Referenced by llvm::buildModuleSummaryIndex(), llvm::CodeViewDebug::CodeViewDebug(), llvm::createObjCARCContractPass(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), llvm::X86TargetLowering::expandIndirectJTBranch(), getCodeModel(), getCodeViewFlag(), llvm::getDebugMetadataVersionFromModule(), getDwarfVersion(), getMOVL(), getNamedGlobal(), getNumberRegisterParameters(), getPICLevel(), getPIELevel(), getProfileSummary(), getRetpolineSymbol(), getRtLibUseGOT(), getSDKVersion(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::TargetLibraryInfoImpl::getWCharSize(), INITIALIZE_PASS(), IsCallReturnTwice(), isEmptyFunction(), llvm::lowertypetests::isJumpTableCanonical(), and writeTypeIdCompatibleVtableSummaryRecord().
getModuleFlagsMetadata() [1/2]
void Module::getModuleFlagsMetadata (SmallVectorImpl< ModuleFlagEntry > & Flags) const
Returns the module flags in the provided vector.
getModuleFlagsMetadata - Returns the module flags in the provided vector.
Definition at line 290 of file Module.cpp.
References getModuleFlagsMetadata(), isValidModFlagBehavior(), llvm::NamedMDNode::operands(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::orc::cloneModuleFlagsMetadata(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::RISCVELFTargetObjectFile::getModuleMetadata(), GetObjCImageInfo(), and llvm::UpgradeModuleFlags().
getModuleFlagsMetadata() [2/2]
NamedMDNode * Module::getModuleFlagsMetadata () const
Returns the NamedMDNode in the module that represents module-level flags.
getModuleFlagsMetadata - Returns the NamedMDNode in the module that represents module-level flags.
This method returns null if there are no module-level flags.
Definition at line 323 of file Module.cpp.
References getNamedMetadata().
Referenced by getModuleFlag(), getModuleFlagsMetadata(), getNamedGlobal(), and isValidModFlagBehavior().
getModuleIdentifier()
const std::string& llvm::Module::getModuleIdentifier () const inline
Get the module identifier which is, essentially, the name of the module.
Returns
the module identifier as a string
Definition at line 211 of file Module.h.
References getInstructionCount().
Referenced by llvm::CloneModule(), createRNG(), llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::FPPassManager::doFinalization(), doImportingForModule(), EmitCamlGlobal(), llvm::ThinLTOCodeGenerator::emitImports(), extractSubModule(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), getDebugLocString(), GetGlobalTypeString(), llvm::orc::IRMaterializationUnit::getName(), llvm::ModuleSummaryIndex::hasExportedFunctions(), llvm::FunctionImporter::importFunctions(), instrumentMaskedLoadOrStore(), llvm::ThinLTOCodeGenerator::internalize(), llvm::LazyCallGraph::LazyCallGraph(), normalizePBQPSpillWeight(), llvm::orc::SimpleCompiler::operator()(), llvm::DiagnosticPrinterRawOStream::operator<<(), llvm::ThinLTOCodeGenerator::promote(), rewriteComdat(), llvm::LazyCallGraphPrinterPass::run(), llvm::LazyCallGraphDOTPrinterPass::run(), and llvm::VerifierSupport::VerifierSupport().
getModuleInlineAsm()
const std::string& llvm::Module::getModuleInlineAsm () const inline
Get any module-scope inline assembly blocks.
Returns
a string containing the module-scope inline assembly blocks.
Definition at line 249 of file Module.h.
References createRNG(), and P.
Referenced by llvm::buildModuleSummaryIndex(), llvm::CloneModule(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::AsmPrinter::doInitialization(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), getStringEncoding(), INITIALIZE_PASS(), initializeRecordStreamer(), and llvm::BitcodeWriter::writeSymtab().
getName()
StringRef llvm::Module::getName () const inline
Get a short "name" for the module.
This is useful for debugging or logging. It is essentially a convenience wrapper around getModuleIdentifier().
Definition at line 228 of file Module.h.
Referenced by llvm::orc::cloneToNewContext(), llvm::FPPassManager::doFinalization(), dumpIR(), getDescription(), llvm::HWAddressSanitizerPass::run(), llvm::ThinLTOCodeGenerator::run(), llvm::StackSafetyGlobalPrinterPass::run(), llvm::ProfileSummaryPrinterPass::run(), llvm::ImportedFunctionsInliningStatistics::setModuleInfo(), and shouldApply().
getNamedAlias()
GlobalAlias * Module::getNamedAlias (StringRef Name) const
Return the global alias in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 239 of file Module.cpp.
References getNamedValue().
Referenced by getNamedGlobal(), and rewriteComdat().
getNamedGlobal() [1/2]
const GlobalVariable* llvm::Module::getNamedGlobal (StringRef Name) const inline
Return the global variable in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 406 of file Module.h.
References getGlobalVariable().
Referenced by appendToGlobalArray(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::orc::getConstructors(), llvm::orc::getDestructors(), getNamedGlobal(), INITIALIZE_PASS(), llvm::isIRPGOFlagSet(), llvm::InstrProfiling::run(), and llvm::ExecutionEngine::runStaticConstructorsDestructors().
getNamedGlobal() [2/2]
GlobalVariable* llvm::Module::getNamedGlobal (StringRef Name) inline
Definition at line 409 of file Module.h.
References addModuleFlag(), llvm::Module::ModuleFlagEntry::Behavior, eraseNamedMetadata(), getModuleFlag(), getModuleFlagsMetadata(), getNamedAlias(), getNamedGlobal(), getNamedIFunc(), getNamedMetadata(), getOrInsertComdat(), getOrInsertGlobal(), getOrInsertModuleFlagsMetadata(), getOrInsertNamedMetadata(), llvm::Module::ModuleFlagEntry::Key, setMaterializer(), and llvm::Module::ModuleFlagEntry::Val.
getNamedIFunc()
GlobalIFunc * Module::getNamedIFunc (StringRef Name) const
Return the global ifunc in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 243 of file Module.cpp.
References getNamedValue().
Referenced by getNamedGlobal().
getNamedMDList() [1/2]
const NamedMDListType& llvm::Module::getNamedMDList () const inline
Get the Module's list of named metadata (constant).
Definition at line 560 of file Module.h.
getNamedMDList() [2/2]
NamedMDListType& llvm::Module::getNamedMDList () inline
Get the Module's list of named metadata.
Definition at line 562 of file Module.h.
getNamedMetadata()
NamedMDNode * Module::getNamedMetadata (const Twine & Name) const
Return the first NamedMDNode in the module with the specified name.
getNamedMetadata - Return the first NamedMDNode in the module with the specified name.
This method returns null if a NamedMDNode with the specified name is not found.
Definition at line 250 of file Module.cpp.
References lookup(), and llvm::Twine::toStringRef().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::cacheAnnotationFromMD(), llvm::CodeViewDebug::CodeViewDebug(), debug_compile_units(), debug_compile_units_begin(), debug_compile_units_end(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), getModuleFlagsMetadata(), getNamedGlobal(), getStringIdTypeIdx(), getSubprogram(), getSymbolName(), llvm::GlobalsMetadata::GlobalsMetadata(), parseVersion(), PushArgMD(), llvm::AMDGPUPALMetadata::readFromIR(), shouldKeepInEntry(), and UpgradeRetainReleaseMarker().
getNamedValue()
GlobalValue * Module::getNamedValue (StringRef Name) const
Return the global value in the module with the specified name, of arbitrary type.
getNamedValue - Return the first global value in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 113 of file Module.cpp.
References getValueSymbolTable(), and llvm::ValueSymbolTable::lookup().
Referenced by appendModuleInlineAsm(), llvm::buildModuleSummaryIndex(), llvm::coro::declaresIntrinsics(), llvm::RecordStreamer::flushSymverDirectives(), forceRenaming(), FunctionNumber(), getComdatGVForCOFF(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), getFunction(), getGlobalVariable(), getMinVisibility(), getNamedAlias(), getNamedIFunc(), getOrInsertFunction(), getOrInsertGlobal(), llvm::TargetLoweringBase::getSDagStackGuard(), INITIALIZE_PASS(), llvm::RISCVInstrInfo::insertOutlinedCall(), llvm::AArch64InstrInfo::insertOutlinedCall(), llvm::X86InstrInfo::insertOutlinedCall(), llvm::TargetLoweringBase::insertSSPDeclarations(), maybeSetDSOLocal(), llvm::objcarc::ModuleHasARC(), parseGlobalValue(), llvm::LinkDiagnosticInfo::print(), llvm::VFABI::setVectorVariantNames(), and transformCallee().
getNumberRegisterParameters()
unsigned Module::getNumberRegisterParameters () const
Returns the Number of Register ParametersDwarf Version by checking module flags.
Definition at line 469 of file Module.cpp.
References getModuleFlag().
Referenced by debug_compile_units().
getOperandBundleTags()
void Module::getOperandBundleTags (SmallVectorImpl< StringRef > & Result) const
Populate client supplied SmallVector with the bundle tags registered in this LLVMContext.
The bundle tags are ordered by increasing bundle IDs.
See also
LLVMContext::getOperandBundleTagID
Definition at line 130 of file Module.cpp.
References llvm::LLVMContext::getOperandBundleTags().
Referenced by appendModuleInlineAsm().
getOrInsertComdat()
Comdat * Module::getOrInsertComdat (StringRef Name)
Return the Comdat in the module with the specified name.
It is created if it didn't already exist.
Definition at line 498 of file Module.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::insert(), and llvm::Entry::Name.
Referenced by AddCalls(), canRenameComdat(), copyComdat(), createGlobalFwdRef(), llvm::createIRLevelProfileFlagVar(), llvm::createProfileFileNameVar(), llvm::createX86RetpolineThunksPass(), getNamedGlobal(), instrumentMaskedLoadOrStore(), needsRuntimeRegistrationOfSectionRange(), RetagMask(), rewriteComdat(), llvm::HWAddressSanitizerPass::run(), and llvm::ModuleSanitizerCoveragePass::run().
getOrInsertFunction() [1/5]
FunctionCallee Module::getOrInsertFunction (StringRef Name, FunctionType * T, AttributeList AttributeList)
Look up the specified function in the module symbol table.
Four possibilities:
If it does not exist, add a prototype for the function and return it.
Otherwise, if the existing function has the correct prototype, return the existing function.
Finally, the function exists but has the wrong prototype: return the function with a constantexpr cast to the right prototype.
In all cases, the returned value is a FunctionCallee wrapper around the 'FunctionType T' passed in, as well as a 'Value' either of the Function or the bitcast to the function.
Definition at line 143 of file Module.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, F(), llvm::PointerType::get(), llvm::GlobalValue::getAddressSpace(), llvm::ConstantExpr::getBitCast(), getNamedValue(), llvm::DataLayout::getProgramAddressSpace(), llvm::GlobalValue::getType(), llvm::Function::isIntrinsic(), Name, llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), and llvm::Function::setAttributes().
Referenced by appendModuleInlineAsm(), llvm::SanitizerStatReport::create(), llvm::createAMDGPUPrintfRuntimeBinding(), createFree(), createMalloc(), createPrivateNonConstGlobalForString(), CreatePrologue(), llvm::createSanitizerCtorAndInitFunctions(), llvm::createThreadSanitizerLegacyPassPass(), llvm::declareSanitizerInitFunction(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), emitUnaryFloatFnCallHelper(), eraseDeadBBsAndChildren(), llvm::SanitizerStatReport::finish(), fixupFPReturnAndCall(), llvm::getCopyDeclaration(), llvm::Intrinsic::getDeclaration(), getDefaultPersonalityFn(), getOrInsertFunction(), llvm::AMDGPULibFunc::getOrInsertFunction(), getOrInsertGlobal(), getOrInsertValueProfilingCall(), GetRMWLibcall(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), INITIALIZE_PASS(), insertCall(), insertSinCosCall(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), insertUseHolderAfter(), instrumentMaskedLoadOrStore(), isReportingError(), lowerObjCCall(), makeStatepointExplicitImpl(), MarkBlocksLiveIn(), PushArgMD(), ReplaceCallWith(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), and shouldKeepInEntry().
getOrInsertFunction() [2/5]
FunctionCallee Module::getOrInsertFunction (StringRef Name, FunctionType * T)
Definition at line 167 of file Module.cpp.
References getOrInsertFunction().
getOrInsertFunction() [3/5]
template<typename... ArgsTy> FunctionCallee llvm::Module::getOrInsertFunction (StringRef Name, AttributeList AttributeList, Type * RetTy, ArgsTy... Args) inline
Look up the specified function in the module symbol table.
If it does not exist, add a prototype for the function and return it. This function guarantees to return a constant of pointer to the specified function type or a ConstantExpr BitCast of that type if the named function has a different type. This version of the method takes a list of function arguments, which makes it easier for clients to use.
Definition at line 357 of file Module.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::FunctionType::get(), and getOrInsertFunction().
getOrInsertFunction() [4/5]
template<typename... ArgsTy> FunctionCallee llvm::Module::getOrInsertFunction (StringRef Name, Type * RetTy, ArgsTy... Args) inline
Same as above, but without the attributes.
Definition at line 368 of file Module.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, getFunction(), getOrInsertFunction(), and llvm::Invalid.
getOrInsertFunction() [5/5]
template<typename... ArgsTy> FunctionCallee llvm::Module::getOrInsertFunction (StringRef Name, AttributeList AttributeList, FunctionType * Invalid, ArgsTy... Args) delete
getOrInsertGlobal() [1/2]
Constant * Module::getOrInsertGlobal (StringRef Name, Type * Ty, function_ref< GlobalVariable *()> CreateGlobalCallback)
Look up the specified global in the module symbol table.
getOrInsertGlobal - Look up the specified global in the module symbol table.
If it does not exist, invoke a callback to create a declaration of the global and return it. The global is constantexpr casted to the expected type if necessary.
If it does not exist, add a declaration of the global and return it.
Else, the global exists but has the wrong type: return the function with a constantexpr cast to the right type.
Finally, if the existing global is the correct declaration, return the existing global.
Definition at line 204 of file Module.cpp.
References assert(), llvm::PointerType::get(), llvm::ConstantExpr::getBitCast(), getNamedValue(), llvm::Type::getPointerAddressSpace(), and llvm::GlobalValue::getType().
Referenced by AddCalls(), eraseDeadBBsAndChildren(), getGlobalVariableI32(), llvm::TargetLoweringBase::getIRStackGuard(), getNamedGlobal(), getOrInsertGlobal(), getOrInsertGlobal(), INITIALIZE_PASS(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), instrumentMaskedLoadOrStore(), llvm::HWAddressSanitizerPass::run(), and llvm::ModuleSanitizerCoveragePass::run().
getOrInsertGlobal() [2/2]
Constant * Module::getOrInsertGlobal (StringRef Name, Type * Ty)
Look up the specified global in the module symbol table.
If required, this overload constructs the global variable using its constructor's defaults.
Definition at line 225 of file Module.cpp.
References llvm::GlobalValue::ExternalLinkage, and getOrInsertGlobal().
getOrInsertModuleFlagsMetadata()
NamedMDNode * Module::getOrInsertModuleFlagsMetadata ()
Returns the NamedMDNode in the module that represents module-level flags.
getOrInsertModuleFlagsMetadata - Returns the NamedMDNode in the module that represents module-level flags.
If module-level flags aren't found, it creates the named metadata that contains them.
Definition at line 330 of file Module.cpp.
References getOrInsertNamedMetadata().
Referenced by addModuleFlag(), and getNamedGlobal().
getOrInsertNamedMetadata()
NamedMDNode * Module::getOrInsertNamedMetadata (StringRef Name)
Return the named MDNode in the module with the specified name.
getOrInsertNamedMetadata - Return the first named MDNode in the module with the specified name.
This method returns a new NamedMDNode if a NamedMDNode with the specified name is not found.
Definition at line 259 of file Module.cpp.
References Name, and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
Referenced by llvm::CloneFunctionInto(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::DIBuilder::createCompileUnit(), getNamedGlobal(), getOrInsertModuleFlagsMetadata(), and StripSymbolNames().
getPICLevel()
PICLevel::Level Module::getPICLevel () const
Returns the PIC level (small or large model)
Definition at line 504 of file Module.cpp.
References getModuleFlag(), and llvm::PICLevel::NotPIC.
Referenced by llvm::lto::Config::addSaveTemps(), debug_compile_units(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), GetSymbolRef(), llvm::SparcTargetLowering::makeAddress(), and mayUseP9Setb().
getPIELevel()
PIELevel::Level Module::getPIELevel () const
Returns the PIE level (small or large model)
Definition at line 518 of file Module.cpp.
References llvm::PIELevel::Default, and getModuleFlag().
Referenced by debug_compile_units(), llvm::TargetMachine::getTLSModel(), and llvm::TargetMachine::shouldAssumeDSOLocal().
getProfileSummary()
Metadata * Module::getProfileSummary (bool IsCS)
Returns profile summary metadata.
When IsCS is true, use the context sensitive profile summary.
Definition at line 557 of file Module.cpp.
References getModuleFlag().
Referenced by llvm::createSampleProfileLoaderPass(), debug_compile_units(), getEntryForPercentile(), and llvm::HotColdSplitting::run().
getRtLibUseGOT()
bool Module::getRtLibUseGOT () const
Returns true if PLT should be avoided for RTLib calls.
Definition at line 566 of file Module.cpp.
References getModuleFlag().
Referenced by llvm::X86Subtarget::classifyGlobalFunctionReference(), convertTailJumpOpcode(), debug_compile_units(), llvm::inferLibFuncAttributes(), and llvm::TargetMachine::shouldAssumeDSOLocal().
getSDKVersion()
VersionTuple Module::getSDKVersion () const
Get the build SDK version metadata.
An empty version is returned if no such metadata is attached.
Definition at line 589 of file Module.cpp.
References getModuleFlag(), and llvm::None.
Referenced by debug_compile_units(), and llvm::AsmPrinter::doInitialization().
getSourceFileName()
const std::string& llvm::Module::getSourceFileName () const inline
Get the module's original source file name.
When compiling from bitcode, this is taken from a bitcode record where it was recorded. For other compiles it is the same as the ModuleID, which would contain the source file name.
Definition at line 222 of file Module.h.
Referenced by llvm::CloneModule(), llvm::AsmPrinter::doInitialization(), llvm::getPGOFuncName(), llvm::thinLTOInternalizeModule(), and llvm::WriteIndexToFile().
getSublistAccess() [1/5]
static GlobalListType Module::* llvm::Module::getSublistAccess (GlobalVariable *) inline static
Definition at line 529 of file Module.h.
getSublistAccess() [2/5]
static FunctionListType Module::* llvm::Module::getSublistAccess (Function *) inline static
Definition at line 537 of file Module.h.
getSublistAccess() [3/5]
static AliasListType Module::* llvm::Module::getSublistAccess (GlobalAlias *) inline static
Definition at line 546 of file Module.h.
getSublistAccess() [4/5]
static IFuncListType Module::* llvm::Module::getSublistAccess (GlobalIFunc *) inline static
Definition at line 555 of file Module.h.
getSublistAccess() [5/5]
static NamedMDListType Module::* llvm::Module::getSublistAccess (NamedMDNode *) inline static
Definition at line 564 of file Module.h.
getTargetTriple()
const std::string& llvm::Module::getTargetTriple () const inline
Get the target triple which is a string describing the target host.
Returns
a string containing the target triple.
Definition at line 241 of file Module.h.
Referenced by AddCalls(), llvm::ModuleSymbolTable::addModule(), llvm::lto::Config::addSaveTemps(), llvm::GlobalValue::canIncreaseAlignment(), llvm::CloneModule(), llvm::CodeViewDebug::CodeViewDebug(), llvm::createAArch64StackTaggingPass(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createIRLevelProfileFlagVar(), llvm::createProfileFileNameVar(), CreateVarArgHelper(), llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::AMDGPUAAWrapperPass::doInitialization(), llvm::EmbedBitcodeInModule(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), GetCtorAndDtorPriority(), getDefaultPersonalityFn(), getOrInsertGlobal(), getStringEncoding(), llvm::LTOModule::getTargetTriple(), INITIALIZE_PASS(), insertSinCosCall(), instrumentMaskedLoadOrStore(), llvm::ThinLTOCodeGenerator::internalize(), isCallingConvCCompatible(), llvm::needsComdatForCounter(), llvm::ThinLTOCodeGenerator::optimize(), llvm::ThinLTOCodeGenerator::promote(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::InstrProfiling::run(), llvm::AMDGPUAA::run(), llvm::TargetLibraryAnalysis::run(), selectJumpTableArmEncoding(), shouldInstrumentReadWriteFromAddress(), llvm::WriteBitcodeToFile(), and llvm::ValueSymbolTable::~ValueSymbolTable().
getTypeByName()
StructType * Module::getTypeByName (StringRef Name) const
Return the type with the specified name, or null if there is none by that name.
Definition at line 528 of file Type.cpp.
References llvm::Type::getContext(), llvm::LLVMContextImpl::NamedStructTypes, and llvm::LLVMContext::pImpl.
Referenced by appendModuleInlineAsm().
getValueSymbolTable() [1/2]
const ValueSymbolTable& llvm::Module::getValueSymbolTable () const inline
Get the symbol table of global variable and function identifiers.
Definition at line 569 of file Module.h.
Referenced by createGlobalFwdRef(), llvm::createSampleProfileLoaderPass(), llvm::AMDGPULibFunc::getFunction(), getNamedValue(), and llvm::AMDGPULibFunc::getOrInsertFunction().
getValueSymbolTable() [2/2]
ValueSymbolTable& llvm::Module::getValueSymbolTable () inline
Get the Module's symbol table of global variable and function identifiers.
Definition at line 571 of file Module.h.
global_begin() [1/2]
global_iterator llvm::Module::global_begin () inline
Definition at line 582 of file Module.h.
Referenced by llvm::CloneModule(), getMinVisibility(), globals(), LLVMGetFirstGlobal(), LLVMGetLastGlobal(), LLVMGetPreviousGlobal(), makeVisible(), mergeConstants(), OptimizeGlobalVars(), splitGlobals(), stripDeadPrototypes(), and StripSymbolNames().
global_begin() [2/2]
const_global_iterator llvm::Module::global_begin () const inline
Definition at line 583 of file Module.h.
global_empty()
bool llvm::Module::global_empty () const inline
Definition at line 586 of file Module.h.
global_end() [1/2]
global_iterator llvm::Module::global_end () inline
Definition at line 584 of file Module.h.
Referenced by llvm::CloneModule(), getMinVisibility(), globals(), LLVMGetFirstGlobal(), LLVMGetLastGlobal(), LLVMGetNextGlobal(), makeVisible(), maybeSetDSOLocal(), mergeConstants(), OptimizeGlobalVars(), splitGlobals(), stripDeadPrototypes(), and StripSymbolNames().
global_end() [2/2]
const_global_iterator llvm::Module::global_end () const inline
Definition at line 585 of file Module.h.
global_objects() [1/2]
iterator_range< Module::global_object_iterator > Module::global_objects ()
Definition at line 384 of file Module.cpp.
References functions(), and globals().
Referenced by AddCalls(), llvm::ExecutionEngine::clearGlobalMappingsFromModule(), and llvm::nameUnamedGlobals().
global_objects() [2/2]
iterator_range< Module::const_global_object_iterator > Module::global_objects () const
Definition at line 388 of file Module.cpp.
References functions(), and globals().
global_values() [1/2]
iterator_range< Module::global_value_iterator > Module::global_values ()
Definition at line 392 of file Module.cpp.
References aliases(), functions(), globals(), and ifuncs().
Referenced by llvm::ModuleSymbolTable::addModule(), dropDeadSymbols(), llvm::RecordStreamer::flushSymverDirectives(), llvm::orc::IRMaterializationUnit::IRMaterializationUnit(), and llvm::orc::SymbolLinkagePromoter::operator()().
global_values() [2/2]
iterator_range< Module::const_global_value_iterator > Module::global_values () const
Definition at line 396 of file Module.cpp.
References aliases(), functions(), globals(), and ifuncs().
globals() [1/2]
iterator_range<global_iterator> llvm::Module::globals () inline
Definition at line 588 of file Module.h.
References global_begin(), global_end(), and llvm::make_range().
Referenced by llvm::BTFDebug::beginInstruction(), llvm::DwarfDebug::beginModule(), llvm::AsmPrinter::computeGlobalGOTEquivs(), llvm::AsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doInitialization(), dropAllReferences(), eliminateAvailableExternally(), llvm::ExecutionEngine::emitGlobals(), llvm::filterDeadComdatFunctions(), findPartitions(), getStringEncoding(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), getSymbolName(), global_objects(), global_values(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), internalizeGVsAfterImport(), isEmptyFunction(), isZeroLengthArray(), optimizeGlobalsInModule(), orderModule(), predictUseListOrder(), rewriteComdat(), llvm::TypeFinder::run(), llvm::stripNonLineTableDebugInfo(), StripSymbolNames(), llvm::updateIndexWPDForExports(), llvm::UpgradeSectionAttributes(), llvm::ValueEnumerator::ValueEnumerator(), and llvm::WriteIndexToFile().
globals() [2/2]
iterator_range<const_global_iterator> llvm::Module::globals () const inline
Definition at line 591 of file Module.h.
References global_begin(), global_end(), and llvm::make_range().
ifunc_begin() [1/2]
ifunc_iterator llvm::Module::ifunc_begin () inline
Definition at line 639 of file Module.h.
Referenced by ifuncs(), LLVMGetFirstGlobalIFunc(), LLVMGetLastGlobalIFunc(), and LLVMGetPreviousGlobalIFunc().
ifunc_begin() [2/2]
const_ifunc_iterator llvm::Module::ifunc_begin () const inline
Definition at line 640 of file Module.h.
ifunc_empty()
bool llvm::Module::ifunc_empty () const inline
Definition at line 644 of file Module.h.
ifunc_end() [1/2]
ifunc_iterator llvm::Module::ifunc_end () inline
Definition at line 641 of file Module.h.
Referenced by ifuncs(), LLVMGetFirstGlobalIFunc(), LLVMGetLastGlobalIFunc(), and LLVMGetNextGlobalIFunc().
ifunc_end() [2/2]
const_ifunc_iterator llvm::Module::ifunc_end () const inline
Definition at line 642 of file Module.h.
ifunc_size()
size_t llvm::Module::ifunc_size () const inline
Definition at line 643 of file Module.h.
ifuncs() [1/2]
iterator_range<ifunc_iterator> llvm::Module::ifuncs () inline
Definition at line 646 of file Module.h.
References ifunc_begin(), ifunc_end(), and llvm::make_range().
Referenced by dropAllReferences(), global_values(), and orderModule().
ifuncs() [2/2]
iterator_range<const_ifunc_iterator> llvm::Module::ifuncs () const inline
Definition at line 649 of file Module.h.
References ifunc_begin(), ifunc_end(), and llvm::make_range().
isMaterialized()
bool llvm::Module::isMaterialized () const inline
Definition at line 509 of file Module.h.
References getMaterializer(), materialize(), materializeAll(), and materializeMetadata().
Referenced by llvm::Value::assertModuleIsMaterializedImpl(), llvm::BitcodeWriter::writeModule(), and llvm::BitcodeWriter::writeThinLinkBitcode().
isValidModFlagBehavior()
bool Module::isValidModFlagBehavior (Metadata * MD, ModFlagBehavior & MFB) static
Checks if Metadata represents a valid ModFlagBehavior, and stores the converted result in MFB.
Definition at line 277 of file Module.cpp.
References getModuleFlagsMetadata(), ModFlagBehaviorFirstVal, and ModFlagBehaviorLastVal.
Referenced by getModuleFlagsMetadata().
materialize()
Error Module::materialize (GlobalValue * GV)
Make sure the GlobalValue is fully read.
Definition at line 410 of file Module.cpp.
References llvm::Error::success().
Referenced by isMaterialized(), and llvm::GlobalValue::materialize().
materializeAll()
Error Module::materializeAll ()
Make sure all GlobalValues in this Module are fully read and clear the Materializer.
Definition at line 417 of file Module.cpp.
References llvm::Error::success().
Referenced by llvm::MCJIT::emitObject(), and isMaterialized().
materializeMetadata()
Error Module::materializeMetadata ()
Definition at line 424 of file Module.cpp.
References llvm::Error::success().
Referenced by isMaterialized().
named_metadata() [1/2]
iterator_range<named_metadata_iterator> llvm::Module::named_metadata () inline
Definition at line 693 of file Module.h.
References llvm::make_range(), named_metadata_begin(), and named_metadata_end().
Referenced by llvm::ValueEnumerator::print(), and rotateSign().
named_metadata() [2/2]
iterator_range<const_named_metadata_iterator> llvm::Module::named_metadata () const inline
Definition at line 696 of file Module.h.
References llvm::make_range(), named_metadata_begin(), and named_metadata_end().
named_metadata_begin() [1/2]
named_metadata_iterator llvm::Module::named_metadata_begin () inline
Definition at line 680 of file Module.h.
Referenced by LLVMGetFirstNamedMetadata(), LLVMGetLastNamedMetadata(), LLVMGetPreviousNamedMetadata(), named_metadata(), llvm::StripDebugInfo(), and llvm::stripNonLineTableDebugInfo().
named_metadata_begin() [2/2]
const_named_metadata_iterator llvm::Module::named_metadata_begin () const inline
Definition at line 681 of file Module.h.
named_metadata_empty()
bool llvm::Module::named_metadata_empty () const inline
Definition at line 691 of file Module.h.
Referenced by rotateSign().
named_metadata_end() [1/2]
named_metadata_iterator llvm::Module::named_metadata_end () inline
Definition at line 685 of file Module.h.
Referenced by LLVMGetFirstNamedMetadata(), LLVMGetLastNamedMetadata(), LLVMGetNextNamedMetadata(), named_metadata(), llvm::StripDebugInfo(), and llvm::stripNonLineTableDebugInfo().
named_metadata_end() [2/2]
const_named_metadata_iterator llvm::Module::named_metadata_end () const inline
Definition at line 686 of file Module.h.
named_metadata_size()
size_t llvm::Module::named_metadata_size () const inline
Definition at line 690 of file Module.h.
print()
void Module::print (raw_ostream & OS, AssemblyAnnotationWriter * AAW, bool ShouldPreserveUseListOrder = false, bool IsForDebug = false) const
Print the module to an output stream with an optional AssemblyAnnotationWriter.
If ShouldPreserveUseListOrder, then include uselistorder directives so that use-lists can be recreated when reading the assembly.
Definition at line 4233 of file AsmWriter.cpp.
References llvm::RISCVFenceField::W.
Referenced by debug_compile_units(), llvm::CallGraphSCCPass::getAnalysisUsage(), llvm::operator<<(), llvm::yaml::BlockScalarTraits< Module >::output(), and llvm::PrintModulePass::run().
rbegin() [1/2]
reverse_iterator llvm::Module::rbegin () inline
Definition at line 603 of file Module.h.
Referenced by predictUseListOrder().
rbegin() [2/2]
const_reverse_iterator llvm::Module::rbegin () const inline
Definition at line 604 of file Module.h.
rend() [1/2]
reverse_iterator llvm::Module::rend () inline
Definition at line 605 of file Module.h.
Referenced by predictUseListOrder().
rend() [2/2]
const_reverse_iterator llvm::Module::rend () const inline
Definition at line 606 of file Module.h.
setCodeModel()
void Module::setCodeModel (CodeModel::Model CL)
Set the code model (tiny, small, kernel, medium or large)
Definition at line 542 of file Module.cpp.
References addModuleFlag(), and llvm::Error.
Referenced by debug_compile_units().
setDataLayout() [1/2]
void Module::setDataLayout (StringRef Desc)
Set the data layout.
Definition at line 363 of file Module.cpp.
References llvm::DataLayout::reset().
Referenced by llvm::orc::LLJIT::applyDataLayout(), LLVMTargetMachineEmit(), and setSourceFileName().
setDataLayout() [2/2]
void Module::setDataLayout (const DataLayout & Other)
Definition at line 367 of file Module.cpp.
References llvm::Other.
setMaterializer()
void Module::setMaterializer (GVMaterializer * GVM)
Sets the GVMaterializer to GVM.
This module must not yet have a Materializer. To reset the materializer for a module that already has one, call materializeAll first. Destroying this module will destroy its materializer without materializing any more GlobalValues. Without destroying the Module, there is no way to detach or destroy a materializer without materializing all the GVs it controls, to avoid leaving orphan unmaterialized GVs.
Definition at line 403 of file Module.cpp.
References assert().
Referenced by getNamedGlobal().
setModuleIdentifier()
void llvm::Module::setModuleIdentifier (StringRef ID) inline
Set the module identifier.
Definition at line 274 of file Module.h.
Referenced by extractSubModule().
setModuleInlineAsm()
void llvm::Module::setModuleInlineAsm (StringRef Asm) inline
Set the module-scope inline assembly blocks.
A trailing newline is added if the input doesn't have one.
Definition at line 288 of file Module.h.
References llvm::HexStyle::Asm.
Referenced by INITIALIZE_PASS(), and makeVisible().
setOwnedMemoryBuffer()
void Module::setOwnedMemoryBuffer (std::unique_ptr< MemoryBuffer > MB)
Take ownership of the given memory buffer.
Definition at line 562 of file Module.cpp.
Referenced by debug_compile_units().
setPICLevel()
void Module::setPICLevel (PICLevel::Level PL)
Set the PIC level (small or large model)
Definition at line 514 of file Module.cpp.
References addModuleFlag().
Referenced by debug_compile_units().
setPIELevel()
void Module::setPIELevel (PIELevel::Level PL)
Set the PIE level (small or large model)
Definition at line 528 of file Module.cpp.
References addModuleFlag().
Referenced by debug_compile_units().
setProfileSummary()
void Module::setProfileSummary (Metadata * M, ProfileSummary::Kind Kind)
Attach profile summary metadata to this module.
Definition at line 550 of file Module.cpp.
References addModuleFlag(), llvm::Error, and llvm::ProfileSummary::PSK_CSInstr.
Referenced by annotateAllFunctions(), llvm::createSampleProfileLoaderPass(), and debug_compile_units().
setRtLibUseGOT()
void Module::setRtLibUseGOT ()
Set that PLT should be avoid for RTLib calls.
Definition at line 571 of file Module.cpp.
References addModuleFlag().
Referenced by debug_compile_units().
setSDKVersion()
void Module::setSDKVersion (const VersionTuple & V)
Attach a build SDK version metadata to this module.
Definition at line 575 of file Module.cpp.
References addModuleFlag(), llvm::ConstantDataArray::get(), llvm::VersionTuple::getMajor(), llvm::VersionTuple::getMinor(), llvm::VersionTuple::getSubminor(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Warning.
Referenced by debug_compile_units().
setSourceFileName()
void llvm::Module::setSourceFileName (StringRef Name) inline
Set the module's original source file name.
Definition at line 277 of file Module.h.
References Name, llvm::Other, and setDataLayout().
setTargetTriple()
void llvm::Module::setTargetTriple (StringRef T) inline
Set the target triple.
Definition at line 284 of file Module.h.
References llvm::T.
Referenced by llvm::LTOModule::setTargetTriple().
shouldEmitInstrCountChangedRemark()
bool llvm::Module::shouldEmitInstrCountChangedRemark () inline
Return true if size-info optimization remark is enabled, false otherwise.
Definition at line 264 of file Module.h.
References getContext(), llvm::LLVMContext::getDiagHandlerPtr(), and llvm::DiagnosticHandler::isAnalysisRemarkEnabled().
Referenced by llvm::FPPassManager::doFinalization(), INITIALIZE_PASS(), llvm::LPPassManager::runOnFunction(), and llvm::FPPassManager::runOnFunction().
size()
size_t llvm::Module::size () const inline
Definition at line 607 of file Module.h.
Referenced by llvm::PhysicalRegisterUsageInfo::doInitialization(), findPartitions(), hasProfileData(), llvm::ThinLTOCodeGenerator::run(), and runAttributorOnModule().
Friends And Related Function Documentation
Constant
friend class Constant friend
Definition at line 193 of file Module.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Module.h
lib/IR/AsmWriter.cpp
lib/IR/LLVMContextImpl.cpp
lib/IR/Module.cpp
lib/IR/Type.cpp