LLVM: llvm::ARMConstantPoolMBB Class Reference
llvm::ARMConstantPoolMBB Class Reference
ARMConstantPoolMBB - ARM-specific constantpool value of a machine basic block.
#include "Target/ARM/ARMConstantPoolValue.h"
Public Member Functions
const MachineBasicBlock * getMBB () const
int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool hasSameValue (ARMConstantPoolValue *ACPV) override
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const ARMConstantPoolMBB *A) const
Public Member Functions inherited from llvm::ARMConstantPoolValue
~ARMConstantPoolValue () override
ARMCP::ARMCPModifier getModifier () const
StringRef getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
bool isPromotedGlobal () const
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
getType - get type of this MachineConstantPoolValue.
Static Public Member Functions
static ARMConstantPoolMBB * Create (LLVMContext &C, const MachineBasicBlock *mbb, unsigned ID, unsigned char PCAdj)
static bool classof (const ARMConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::ARMConstantPoolValue
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolMBB - ARM-specific constantpool value of a machine basic block.
Definition at line 247 of file ARMConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void ARMConstantPoolMBB::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 290 of file ARMConstantPoolValue.cpp.
References llvm::FoldingSetNodeID::AddPointer(), and llvm::ARMConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::ARMConstantPoolMBB::classof (const ARMConstantPoolValue * ACPV) inline static
Definition at line 272 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::isMachineBasicBlock().
Create()
ARMConstantPoolMBB * ARMConstantPoolMBB::Create (LLVMContext & C, const MachineBasicBlock * mbb, unsigned ID, unsigned char PCAdj) static
Definition at line 272 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::no_modifier.
Referenced by llvm::ARMTargetLowering::ReplaceNodeResults().
equals()
bool llvm::ARMConstantPoolMBB::equals (const ARMConstantPoolMBB * A) const inline
Definition at line 276 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::equals().
getExistingMachineCPValue()
int ARMConstantPoolMBB::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 279 of file ARMConstantPoolValue.cpp.
References llvm::HexagonISD::CP.
getMBB()
const MachineBasicBlock* llvm::ARMConstantPoolMBB::getMBB () const inline
Definition at line 259 of file ARMConstantPoolValue.h.
References llvm::HexagonISD::CP, llvm::RISCVFenceField::O, and print().
hasSameValue()
bool ARMConstantPoolMBB::hasSameValue (ARMConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 284 of file ARMConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::ARMConstantPoolValue::hasSameValue().
print()
void ARMConstantPoolMBB::print (raw_ostream & O) const override virtual
print - Implement operator<<
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 295 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::print(), and llvm::printMBBReference().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMConstantPoolValue.h
lib/Target/ARM/ARMConstantPoolValue.cpp