LLVM: llvm::LegalizerHelper Class Reference
llvm::LegalizerHelper Class Reference
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
Public Types
enum LegalizeResult { AlreadyLegal, Legalized, UnableToLegalize }
Public Member Functions
LegalizerHelper (MachineFunction &MF, GISelChangeObserver &Observer, MachineIRBuilder &B)
LegalizerHelper (MachineFunction &MF, const LegalizerInfo &LI, GISelChangeObserver &Observer, MachineIRBuilder &B)
LegalizeResult legalizeInstrStep (MachineInstr &MI)
Replace MI by a sequence of legal instructions that can implement the same operation.
LegalizeResult libcall (MachineInstr &MI)
Legalize an instruction by emiting a runtime library call instead.
LegalizeResult narrowScalar (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
Legalize an instruction by reducing the width of the underlying scalar type.
LegalizeResult widenScalar (MachineInstr &MI, unsigned TypeIdx, LLT WideTy)
Legalize an instruction by performing the operation on a wider scalar type (for example a 16-bit addition can be safely performed at 32-bits precision, ignoring the unused bits).
LegalizeResult lower (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
Legalize an instruction by splitting it into simpler parts, hopefully understood by the target.
LegalizeResult fewerElementsVector (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
Legalize a vector instruction by splitting into multiple components, each acting on the same scalar type as the original but with fewer elements.
LegalizeResult moreElementsVector (MachineInstr &MI, unsigned TypeIdx, LLT MoreTy)
Legalize a vector instruction by increasing the number of vector elements involved and ignoring the added elements later.
const LegalizerInfo & getLegalizerInfo () const
Expose LegalizerInfo so the clients can re-use.
LegalizeResult fewerElementsVectorImplicitDef (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult fewerElementsVectorBasic (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
Legalize a simple vector instruction where all operands are the same type by splitting into multiple components.
LegalizeResult fewerElementsVectorMultiEltType (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
Legalize a instruction with a vector type where each operand may have a different element type.
LegalizeResult fewerElementsVectorCasts (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult fewerElementsVectorCmp (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult fewerElementsVectorSelect (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult fewerElementsVectorPhi (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult moreElementsVectorPhi (MachineInstr &MI, unsigned TypeIdx, LLT MoreTy)
LegalizeResult fewerElementsVectorUnmergeValues (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult fewerElementsVectorBuildVector (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult reduceLoadStoreWidth (MachineInstr &MI, unsigned TypeIdx, LLT NarrowTy)
LegalizeResult narrowScalarShiftByConstant (MachineInstr &MI, const APInt &Amt, LLT HalfTy, LLT ShiftAmtTy)
LegalizeResult narrowScalarShift (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult narrowScalarMul (MachineInstr &MI, LLT Ty)
LegalizeResult narrowScalarExtract (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult narrowScalarInsert (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult narrowScalarBasic (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult narrowScalarSelect (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult lowerBitCount (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult lowerU64ToF32BitOps (MachineInstr &MI)
LegalizeResult lowerUITOFP (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult lowerSITOFP (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult lowerFPTOUI (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult lowerMinMax (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult lowerFCopySign (MachineInstr &MI, unsigned TypeIdx, LLT Ty)
LegalizeResult lowerFMinNumMaxNum (MachineInstr &MI)
LegalizeResult lowerFMad (MachineInstr &MI)
LegalizeResult lowerIntrinsicRound (MachineInstr &MI)
LegalizeResult lowerUnmergeValues (MachineInstr &MI)
LegalizeResult lowerShuffleVector (MachineInstr &MI)
LegalizeResult lowerDynStackAlloc (MachineInstr &MI)
LegalizeResult lowerExtract (MachineInstr &MI)
LegalizeResult lowerInsert (MachineInstr &MI)
LegalizeResult lowerSADDO_SSUBO (MachineInstr &MI)
LegalizeResult lowerBswap (MachineInstr &MI)
LegalizeResult lowerBitreverse (MachineInstr &MI)
LegalizeResult lowerReadRegister (MachineInstr &MI)
Public Attributes
MachineIRBuilder & MIRBuilder
Expose MIRBuilder so clients can set their own RecordInsertInstruction functions.
Detailed Description
Definition at line 36 of file LegalizerHelper.h.
Member Enumeration Documentation
LegalizeResult
enum llvm::LegalizerHelper::LegalizeResult
Enumerator
AlreadyLegal
Instruction was already legal and no change was made to the MachineFunction.
Legalized
Instruction has been legalized and the MachineFunction changed.
UnableToLegalize
Some kind of error has occurred and we could not legalize this instruction.
Definition at line 38 of file LegalizerHelper.h.
Constructor & Destructor Documentation
LegalizerHelper() [1/2]
LegalizerHelper::LegalizerHelper (MachineFunction & MF, GISelChangeObserver & Observer, MachineIRBuilder & B)
Definition at line 66 of file LegalizerHelper.cpp.
References MIRBuilder, llvm::MachineIRBuilder::setChangeObserver(), and llvm::MachineIRBuilder::setMF().
LegalizerHelper() [2/2]
LegalizerHelper::LegalizerHelper (MachineFunction & MF, const LegalizerInfo & LI, GISelChangeObserver & Observer, MachineIRBuilder & B)
Definition at line 75 of file LegalizerHelper.cpp.
References MIRBuilder, llvm::MachineIRBuilder::setChangeObserver(), and llvm::MachineIRBuilder::setMF().
Member Function Documentation
fewerElementsVector()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVector (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Legalize a vector instruction by splitting into multiple components, each acting on the same scalar type as the original but with fewer elements.
Definition at line 2984 of file LegalizerHelper.cpp.
References fewerElementsVectorBasic(), fewerElementsVectorBuildVector(), fewerElementsVectorCasts(), fewerElementsVectorCmp(), fewerElementsVectorImplicitDef(), fewerElementsVectorMultiEltType(), fewerElementsVectorPhi(), fewerElementsVectorSelect(), fewerElementsVectorUnmergeValues(), llvm::MachineInstr::getOpcode(), MIRBuilder, reduceLoadStoreWidth(), llvm::MachineIRBuilder::setInstr(), and UnableToLegalize.
Referenced by legalizeInstrStep().
fewerElementsVectorBasic()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorBasic (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Legalize a simple vector instruction where all operands are the same type by splitting into multiple components.
Definition at line 2354 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildUndef(), E, llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), I, llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), Size, and UnableToLegalize.
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorBuildVector()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorBuildVector (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2838 of file LegalizerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildUndef(), llvm::SmallVectorImpl< T >::clear(), Concat, llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), I, Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::LLT::vector().
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorCasts()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorCasts (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2543 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::MachineInstr::getFlags(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), I, llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineInstr::setFlags(), UnableToLegalize, and llvm::LLT::vector().
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorCmp()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorCmp (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2592 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildFCmp(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::MachineInstr::getFlags(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), I, llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineInstr::setFlags(), UnableToLegalize, and llvm::LLT::vector().
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorImplicitDef()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorImplicitDef (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2325 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), Size, and UnableToLegalize.
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorMultiEltType()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorMultiEltType (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Legalize a instruction with a vector type where each operand may have a different element type.
All type indexes must have the same number of elements.
Definition at line 2459 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::SmallVectorImpl< T >::clear(), E, llvm::MachineInstr::eraseFromParent(), getNarrowTypeBreakDown(), llvm::LLT::getNumElements(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarType(), I, llvm::MachineIRBuilder::insertInstr(), llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalarOrVector(), llvm::SmallVectorBase::size(), and UnableToLegalize.
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorPhi()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorPhi (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2731 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), llvm::SmallVectorImpl< T >::clear(), E, llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineOperand::getMBB(), getNarrowTypeBreakDown(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), I, Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineIRBuilder::setInsertPt(), and UnableToLegalize.
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorSelect()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorSelect (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2659 of file LegalizerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), Size, UnableToLegalize, and llvm::LLT::vector().
Referenced by fewerElementsVector(), and getLegalizerInfo().
fewerElementsVectorUnmergeValues()
LegalizerHelper::LegalizeResult LegalizerHelper::fewerElementsVectorUnmergeValues (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2798 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineInstr::eraseFromParent(), getGCDType(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, Legalized, MIRBuilder, MRI, and UnableToLegalize.
Referenced by fewerElementsVector(), and getLegalizerInfo().
getLegalizerInfo()
const LegalizerInfo& llvm::LegalizerHelper::getLegalizerInfo () const inline
Expose LegalizerInfo so the clients can re-use.
Definition at line 96 of file LegalizerHelper.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::createLibcall(), llvm::createMemLibcall(), fewerElementsVectorBasic(), fewerElementsVectorBuildVector(), fewerElementsVectorCasts(), fewerElementsVectorCmp(), fewerElementsVectorImplicitDef(), fewerElementsVectorMultiEltType(), fewerElementsVectorPhi(), fewerElementsVectorSelect(), fewerElementsVectorUnmergeValues(), lowerBitCount(), lowerBitreverse(), lowerBswap(), lowerDynStackAlloc(), lowerExtract(), lowerFCopySign(), lowerFMad(), lowerFMinNumMaxNum(), lowerFPTOUI(), lowerInsert(), lowerIntrinsicRound(), lowerMinMax(), lowerReadRegister(), lowerSADDO_SSUBO(), lowerShuffleVector(), lowerSITOFP(), lowerU64ToF32BitOps(), lowerUITOFP(), lowerUnmergeValues(), MI, MIRBuilder, moreElementsVectorPhi(), narrowScalarBasic(), narrowScalarExtract(), narrowScalarInsert(), narrowScalarMul(), narrowScalarSelect(), narrowScalarShift(), narrowScalarShiftByConstant(), reduceLoadStoreWidth(), and Reg.
legalizeInstrStep()
LegalizerHelper::LegalizeResult LegalizerHelper::legalizeInstrStep (MachineInstr & MI)
Replace MI by a sequence of legal instructions that can implement the same operation.
Note that this means MI may be deleted, so any iterator steps should be performed before calling this function. Helper should be initialized to the MachineFunction containing MI.
Considered as an opaque blob, the legal code will use and define the same registers as MI.
Definition at line 83 of file LegalizerHelper.cpp.
References AlreadyLegal, assert(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::LegalizeActions::Custom, llvm::dbgs(), llvm::LegalizeActions::FewerElements, fewerElementsVector(), llvm::LegalizerInfo::getAction(), llvm::MachineInstr::getOpcode(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), I, llvm::LLT::isValid(), llvm::LLT::isVector(), llvm::LegalizeActions::Legal, llvm::LegalizerInfo::legalizeCustom(), Legalized, llvm::LegalizerInfo::legalizeIntrinsic(), libcall(), LLVM_DEBUG, llvm::Lower, lower(), MIRBuilder, llvm::LegalizeActions::MoreElements, moreElementsVector(), llvm::LegalizeActions::NarrowScalar, narrowScalar(), llvm::MachineInstr::print(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::LLT::scalar(), llvm::LLT::scalarOrVector(), UnableToLegalize, llvm::LegalizeActions::WidenScalar, and widenScalar().
Referenced by llvm::Legalizer::legalizeMachineFunction().
libcall()
LegalizerHelper::LegalizeResult LegalizerHelper::libcall (MachineInstr & MI)
Legalize an instruction by emiting a runtime library call instead.
Definition at line 490 of file LegalizerHelper.cpp.
References conversionLibcall(), llvm::dbgs(), llvm::MachineInstr::eraseFromParent(), llvm::IntegerType::get(), llvm::Function::getContext(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::MachineFunction::getFunction(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), llvm::MachineRegisterInfo::getType(), Legalized, LLVM_DEBUG, MIRBuilder, llvm::MachineIRBuilder::setInstr(), simpleLibcall(), Size, and UnableToLegalize.
Referenced by legalizeInstrStep().
lower()
LegalizerHelper::LegalizeResult LegalizerHelper::lower (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Legalize an instruction by splitting it into simpler parts, hopefully understood by the target.
Definition at line 1939 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildMul(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildSExt(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildStore(), llvm::MachineIRBuilder::buildSub(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineIRBuilder::buildZExt(), llvm::MachineInstr::eraseFromParent(), llvm::Function::getContext(), llvm::Type::getDoubleTy(), llvm::MachineInstr::getFlags(), llvm::Type::getFloatTy(), llvm::Type::getFP128Ty(), llvm::MachineFunction::getFunction(), llvm::Type::getHalfTy(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineMemOperand::getSizeInBits(), llvm::ConstantFP::getZeroValueForNegation(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_ULT, llvm::MachineOperand::isImm(), llvm::isPowerOf2_32(), llvm::LLT::isScalar(), llvm::LLT::isVector(), Legalized, llvm_unreachable, llvm::Lower, lowerBitCount(), lowerBitreverse(), lowerBswap(), lowerDynStackAlloc(), lowerExtract(), lowerFCopySign(), lowerFMad(), lowerFMinNumMaxNum(), lowerFPTOUI(), lowerInsert(), lowerIntrinsicRound(), lowerMinMax(), lowerReadRegister(), lowerSADDO_SSUBO(), lowerShuffleVector(), lowerSITOFP(), lowerUITOFP(), lowerUnmergeValues(), llvm::MachineInstr::memoperands_begin(), MIRBuilder, MRI, llvm::NextPowerOf2(), llvm::PowerOf2Floor(), llvm::LLT::scalar(), llvm::MachineIRBuilder::setInstr(), and UnableToLegalize.
Referenced by legalizeInstrStep().
lowerBitCount()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerBitCount (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3724 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildSelect(), llvm::LegalizeActions::Custom, llvm::MachineInstr::eraseFromParent(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getMF(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::CmpInst::ICMP_EQ, llvm::LegalizeActions::Legal, Legalized, MIRBuilder, llvm::PowerOf2Ceil(), llvm::LLT::scalar(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), TII, and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
lowerBitreverse()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerBitreverse (MachineInstr & MI)
Definition at line 4442 of file LegalizerHelper.cpp.
References llvm::ISD::BSWAP, llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::APInt::getSplat(), Legalized, MIRBuilder, MRI, Size, and SwapN().
Referenced by getLegalizerInfo(), and lower().
lowerBswap()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerBswap (MachineInstr & MI)
Definition at line 4396 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildShl(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstrBuilder::getInstr(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBytes(), Legalized, llvm::BitmaskEnumDetail::Mask(), MIRBuilder, MRI, and llvm::MachineOperand::setReg().
Referenced by getLegalizerInfo(), and lower().
lowerDynStackAlloc()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerDynStackAlloc (MachineInstr & MI)
Definition at line 4253 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildCast(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getMF(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), MIRBuilder, MRI, and llvm::LLT::scalar().
Referenced by getLegalizerInfo(), and lower().
lowerExtract()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerExtract (MachineInstr & MI)
Definition at line 4288 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildBitcast(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::LLT::isScalar(), llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::LLT::scalar(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
lowerFCopySign()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerFCopySign (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 4045 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineIRBuilder::buildZExt(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getFlags(), llvm::APInt::getLowBitsSet(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::APInt::getSignMask(), Legalized, MIRBuilder, MRI, and llvm::MachineInstr::setFlags().
Referenced by getLegalizerInfo(), and lower().
lowerFMad()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerFMad (MachineInstr & MI)
Definition at line 4123 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildFAdd(), llvm::MachineIRBuilder::buildFMul(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), Legalized, MIRBuilder, and MRI.
Referenced by getLegalizerInfo(), llvm::AMDGPULegalizerInfo::legalizeFMad(), and lower().
lowerFMinNumMaxNum()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerFMinNumMaxNum (MachineInstr & MI)
Definition at line 4093 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildFCanonicalize(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::FmNoNans, llvm::MachineInstr::getFlag(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getReg(), llvm::isKnownNeverSNaN(), Legalized, MIRBuilder, and MRI.
Referenced by getLegalizerInfo(), llvm::AMDGPULegalizerInfo::legalizeMinNumMaxNum(), and lower().
lowerFPTOUI()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerFPTOUI (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3970 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFCmp(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFPTOSI(), llvm::MachineIRBuilder::buildFSub(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildXor(), llvm::MachineInstr::eraseFromParent(), llvm::AArch64ISD::FCMP, llvm::CmpInst::FCMP_ULT, llvm::APInt::getNullValue(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::APInt::getSignMask(), llvm::LLT::getSizeInBits(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), Legalized, MIRBuilder, MRI, llvm::APFloatBase::rmNearestTiesToEven, llvm::LLT::scalar(), Threshold, and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
lowerInsert()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerInsert (MachineInstr & MI)
Definition at line 4320 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildBitcast(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildZExt(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::LLT::isScalar(), llvm::LLT::isVector(), Legalized, llvm::BitmaskEnumDetail::Mask(), MIRBuilder, MRI, llvm::LLT::scalar(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
lowerIntrinsicRound()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerIntrinsicRound (MachineInstr & MI)
Definition at line 4137 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildFAdd(), llvm::MachineIRBuilder::buildFCmp(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildIntrinsicTrunc(), llvm::MachineIRBuilder::buildSITOFP(), llvm::LLT::changeElementSize(), llvm::MachineInstr::eraseFromParent(), llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), Legalized, MIRBuilder, and MRI.
Referenced by getLegalizerInfo(), and lower().
lowerMinMax()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerMinMax (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 4029 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), Legalized, minMaxToCompare(), MIRBuilder, and MRI.
Referenced by getLegalizerInfo(), and lower().
lowerReadRegister()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerReadRegister (MachineInstr & MI)
Definition at line 4473 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildCopy(), llvm::StringRef::data(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getMetadata(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetLowering::getRegisterByName(), llvm::MDString::getString(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::Register::isValid(), Legalized, MIRBuilder, MRI, and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
lowerSADDO_SSUBO()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerSADDO_SSUBO (MachineInstr & MI)
Definition at line 4360 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildSub(), llvm::MachineIRBuilder::buildXor(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, Legalized, MIRBuilder, and MRI.
Referenced by getLegalizerInfo(), and lower().
lowerShuffleVector()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerShuffleVector (MachineInstr & MI)
Definition at line 4197 of file LegalizerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildExtractVectorElement(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getShuffleMask(), llvm::LLT::isScalar(), llvm::Register::isValid(), llvm::LLT::isVector(), Legalized, llvm::BitmaskEnumDetail::Mask(), MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalar(), llvm::ArrayRef< T >::size(), UnableToLegalize, and llvm::RegState::Undef.
Referenced by getLegalizerInfo(), and lower().
lowerSITOFP()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerSITOFP (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3924 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildAShr(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFNeg(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildUITOFP(), llvm::MachineIRBuilder::buildXor(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::CmpInst::ICMP_NE, Legalized, MIRBuilder, MRI, llvm::LLT::scalar(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
lowerU64ToF32BitOps()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerU64ToF32BitOps (MachineInstr & MI)
Definition at line 3839 of file LegalizerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildCTLZ_ZERO_UNDEF(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildSub(), llvm::MachineIRBuilder::buildTrunc(), C, E, llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, Legalized, MIRBuilder, MRI, and llvm::LLT::scalar().
Referenced by getLegalizerInfo(), and lowerUITOFP().
lowerUITOFP()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerUITOFP (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3895 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), Legalized, lowerU64ToF32BitOps(), MIRBuilder, MRI, llvm::LLT::scalar(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
lowerUnmergeValues()
LegalizerHelper::LegalizeResult LegalizerHelper::lowerUnmergeValues (MachineInstr & MI)
Definition at line 4164 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildBitcast(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineInstr::eraseFromParent(), llvm::LLT::getElementType(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), I, llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, llvm::LLT::scalar(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and lower().
moreElementsVector()
LegalizerHelper::LegalizeResult LegalizerHelper::moreElementsVector (MachineInstr & MI, unsigned TypeIdx, LLT MoreTy)
Legalize a vector instruction by increasing the number of vector elements involved and ignoring the added elements later.
Definition at line 3303 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), B, llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMul(), llvm::MachineIRBuilder::buildUAddo(), llvm::MachineIRBuilder::buildUMulH(), llvm::MachineIRBuilder::buildZExt(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), getReg(), llvm::LLT::getSizeInBits(), I, llvm::LegalityPredicates::isVector(), Legalized, MIRBuilder, moreElementsVectorPhi(), MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalar(), llvm::MachineIRBuilder::setInstr(), llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), and UnableToLegalize.
Referenced by legalizeInstrStep().
moreElementsVectorPhi()
LegalizerHelper::LegalizeResult LegalizerHelper::moreElementsVectorPhi (MachineInstr & MI, unsigned TypeIdx, LLT MoreTy)
Definition at line 3284 of file LegalizerHelper.cpp.
References assert(), E, llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), I, Legalized, MIRBuilder, and llvm::MachineIRBuilder::setInsertPt().
Referenced by getLegalizerInfo(), and moreElementsVector().
narrowScalar()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalar (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Legalize an instruction by reducing the width of the underlying scalar type.
Definition at line 597 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildAnyExtOrTrunc(), llvm::MachineIRBuilder::buildAShr(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildIntToPtr(), llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildPtrToInt(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildSExt(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildStore(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineIRBuilder::buildUAdde(), llvm::MachineIRBuilder::buildUAddo(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineIRBuilder::buildXor(), llvm::MachineIRBuilder::buildZExt(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), Concat, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::dbgs(), llvm::ArrayRef< T >::drop_front(), E, llvm::MachineInstr::eraseFromParent(), llvm::LLT::getAddressSpace(), llvm::MachineOperand::getCImm(), llvm::MachineIRBuilder::getDataLayout(), llvm::LLT::getElementType(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineOperand::getImm(), llvm::MachineIRBuilder::getInsertPt(), llvm::MachineIRBuilder::getMBB(), llvm::MachineOperand::getMBB(), llvm::LLT::getNumElements(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getPredicate(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getScalarType(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::ICmpInst::getUnsignedPredicate(), llvm::ConstantInt::getValue(), llvm::greatestCommonDivisor(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::MachineOperand::isImm(), llvm::DataLayout::isNonIntegralAddressSpace(), llvm::LLT::isPointer(), llvm::LLT::isScalar(), llvm::LLT::isVector(), Legalized, LLVM_DEBUG, llvm::APInt::lshr(), llvm::MachineInstr::memoperands_begin(), Merge, MI, MIRBuilder, narrowScalarBasic(), narrowScalarExtract(), narrowScalarInsert(), narrowScalarMul(), narrowScalarSelect(), narrowScalarShift(), llvm::SmallVectorTemplateBase< T >::push_back(), reduceLoadStoreWidth(), llvm::SmallVectorImpl< T >::resize(), llvm::LLT::scalar(), llvm::MachineOperand::setImm(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineIRBuilder::setInstr(), llvm::MachineOperand::setReg(), llvm::SmallVectorBase::size(), llvm::APInt::trunc(), and UnableToLegalize.
Referenced by llvm::MipsRegisterBankInfo::applyMappingImpl(), and legalizeInstrStep().
narrowScalarBasic()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalarBasic (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3637 of file LegalizerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildInstr(), E, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, Legalized, llvm_unreachable, MIRBuilder, MRI, llvm::SmallVectorBase::size(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and narrowScalar().
narrowScalarExtract()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalarExtract (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3497 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalar(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and narrowScalar().
narrowScalarInsert()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalarInsert (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3562 of file LegalizerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), Legalized, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalar(), llvm::SmallVectorBase::size(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and narrowScalar().
narrowScalarMul()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalarMul (MachineInstr & MI, LLT Ty)
Definition at line 3462 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildMerge(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), Legalized, MIRBuilder, MRI, and UnableToLegalize.
Referenced by getLegalizerInfo(), and narrowScalar().
narrowScalarSelect()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalarSelect (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3678 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildSelect(), E, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, llvm::LLT::isVector(), Legalized, llvm_unreachable, MIRBuilder, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MCID::Select, llvm::SmallVectorBase::size(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and narrowScalar().
narrowScalarShift()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalarShift (MachineInstr & MI, unsigned TypeIdx, LLT Ty)
Definition at line 3174 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAShr(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildSub(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getCImm(), llvm::MachineInstr::getOpcode(), llvm::getOpcodeDef(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::ConstantInt::getValue(), llvm::MipsISD::Hi, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::LLT::isVector(), Legalized, llvm_unreachable, llvm::MipsISD::Lo, MIRBuilder, MRI, narrowScalarShiftByConstant(), llvm::LLT::scalar(), and UnableToLegalize.
Referenced by getLegalizerInfo(), and narrowScalar().
narrowScalarShiftByConstant()
LegalizerHelper::LegalizeResult LegalizerHelper::narrowScalarShiftByConstant (MachineInstr & MI, const APInt & Amt, LLT HalfTy, LLT ShiftAmtTy)
Definition at line 3085 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAShr(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SrcOp::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MipsISD::Hi, llvm::APInt::isNullValue(), Legalized, llvm::MipsISD::Lo, MIRBuilder, MRI, Register, and llvm::APInt::ugt().
Referenced by getLegalizerInfo(), and narrowScalarShift().
reduceLoadStoreWidth()
LegalizerHelper::LegalizeResult LegalizerHelper::reduceLoadStoreWidth (MachineInstr & MI, unsigned TypeIdx, LLT NarrowTy)
Definition at line 2897 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildStore(), E, llvm::MachineInstr::eraseFromParent(), llvm::MachineMemOperand::getFailureOrdering(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), getNarrowTypeBreakDown(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineMemOperand::getOrdering(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::LLT::isValid(), Legalized, llvm::MachineIRBuilder::materializePtrAdd(), llvm::MachineInstr::memoperands_begin(), MIRBuilder, MRI, llvm::NotAtomic, llvm::LLT::scalar(), llvm::SmallVectorBase::size(), and UnableToLegalize.
Referenced by fewerElementsVector(), getLegalizerInfo(), and narrowScalar().
widenScalar()
LegalizerHelper::LegalizeResult LegalizerHelper::widenScalar (MachineInstr & MI, unsigned TypeIdx, LLT WideTy)
Legalize an instruction by performing the operation on a wider scalar type (for example a 16-bit addition can be safely performed at 32-bits precision, ignoring the unused bits).
Definition at line 1429 of file LegalizerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineIRBuilder::buildZExt(), llvm::MachineIRBuilder::buildZExtOrTrunc(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::APFloat::convert(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), E, llvm::MachineInstr::eraseFromParent(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::APInt::getAllOnesValue(), llvm::MachineIRBuilder::getBoolExtOp(), llvm::MachineOperand::getCImm(), llvm::Function::getContext(), llvm::LLT::getElementType(), llvm::LegalizerInfo::getExtOpcodeForWideningConstant(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineOperand::getFPImm(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getInsertPt(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineIRBuilder::getMBB(), llvm::MachineOperand::getMBB(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getMF(), llvm::LLT::getNumElements(), llvm::MachineInstr::getNumOperands(), llvm::APInt::getOneBitSet(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getType(), llvm::ConstantInt::getValue(), llvm::ConstantFP::getValueAPF(), llvm::APInt::getZExtValue(), I, llvm::CmpInst::ICMP_NE, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), llvm::isPowerOf2_32(), llvm::CmpInst::isSigned(), llvm::LegalityPredicates::isVector(), Legalized, llvm::BitmaskEnumDetail::Mask(), MIRBuilder, llvm::APFloatBase::rmNearestTiesToEven, llvm::MachineOperand::setCImm(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setFPImm(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineIRBuilder::setInstr(), llvm::MachineOperand::setReg(), llvm::APInt::sext(), TII, UnableToLegalize, llvm::LLT::vector(), and llvm::APInt::zext().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), and legalizeInstrStep().
Member Data Documentation
MIRBuilder
MachineIRBuilder& llvm::LegalizerHelper::MIRBuilder
Expose MIRBuilder so clients can set their own RecordInsertInstruction functions.
Definition at line 93 of file LegalizerHelper.h.
Referenced by fewerElementsVector(), fewerElementsVectorBasic(), fewerElementsVectorBuildVector(), fewerElementsVectorCasts(), fewerElementsVectorCmp(), fewerElementsVectorImplicitDef(), fewerElementsVectorMultiEltType(), fewerElementsVectorPhi(), fewerElementsVectorSelect(), fewerElementsVectorUnmergeValues(), getGCDType(), getLegalizerInfo(), legalizeInstrStep(), llvm::Legalizer::legalizeMachineFunction(), LegalizerHelper(), libcall(), lower(), lowerBitCount(), lowerBitreverse(), lowerBswap(), lowerDynStackAlloc(), lowerExtract(), lowerFCopySign(), lowerFMad(), lowerFMinNumMaxNum(), lowerFPTOUI(), lowerInsert(), lowerIntrinsicRound(), lowerMinMax(), lowerReadRegister(), lowerSADDO_SSUBO(), lowerShuffleVector(), lowerSITOFP(), lowerU64ToF32BitOps(), lowerUITOFP(), lowerUnmergeValues(), moreElementsVector(), moreElementsVectorPhi(), narrowScalar(), narrowScalarBasic(), narrowScalarExtract(), narrowScalarInsert(), narrowScalarMul(), narrowScalarSelect(), narrowScalarShift(), narrowScalarShiftByConstant(), reduceLoadStoreWidth(), and widenScalar().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/LegalizerHelper.h
lib/CodeGen/GlobalISel/LegalizerHelper.cpp