LLVM: llvm::MDAttachmentMap Class Reference
llvm::MDAttachmentMap Class Reference
Map-like storage for metadata attachments.
#include "IR/LLVMContextImpl.h"
Public Member Functions
bool empty () const
size_t size () const
MDNode * lookup (unsigned ID) const
Get a particular attachment (if any).
void set (unsigned ID, MDNode &MD)
Set an attachment to a particular node.
bool erase (unsigned ID)
Remove an attachment.
void getAll (SmallVectorImpl< std::pair< unsigned, MDNode *>> &Result) const
Copy out all the attachments.
template<class PredTy >
void remove_if (PredTy shouldRemove)
Erase matching attachments.
Detailed Description
Map-like storage for metadata attachments.
Definition at line 1175 of file LLVMContextImpl.h.
Member Function Documentation
empty()
bool llvm::MDAttachmentMap::empty () const inline
Definition at line 1179 of file LLVMContextImpl.h.
References llvm::SmallVectorBase::empty().
erase()
bool MDAttachmentMap::erase (unsigned ID)
Remove an attachment.
Remove the attachment at ID, if any.
Definition at line 1114 of file Metadata.cpp.
References E, llvm::empty(), and I.
getAll()
void MDAttachmentMap::getAll (SmallVectorImpl< std::pair< unsigned, MDNode *>> & Result) const
Copy out all the attachments.
Copies all the current attachments into Result, sorting by attachment ID. This function does not clear Result.
Definition at line 1142 of file Metadata.cpp.
References llvm::array_pod_sort().
lookup()
MDNode * MDAttachmentMap::lookup (unsigned ID) const
Get a particular attachment (if any).
Definition at line 1135 of file Metadata.cpp.
References I.
remove_if()
template<class PredTy > void llvm::MDAttachmentMap::remove_if (PredTy shouldRemove) inline
Erase matching attachments.
Erases all attachments matching the shouldRemove predicate.
Definition at line 1205 of file LLVMContextImpl.h.
References llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallVectorImpl< T >::erase(), and llvm::remove_if().
set()
void MDAttachmentMap::set (unsigned ID, MDNode & MD)
Set an attachment to a particular node.
Set the ID attachment to MD, replacing the current attachment at ID (if anyway).
Definition at line 1104 of file Metadata.cpp.
References I.
size()
size_t llvm::MDAttachmentMap::size () const inline
Definition at line 1180 of file LLVMContextImpl.h.
References lookup(), and llvm::SmallVectorBase::size().
The documentation for this class was generated from the following files:
lib/IR/LLVMContextImpl.h
lib/IR/Metadata.cpp