LLVM: llvm::TimePassesHandler Class Reference
llvm::TimePassesHandler Class Reference
This class implements -time-passes functionality for new pass manager.
#include "llvm/IR/PassTimingInfo.h"
Public Member Functions
TimePassesHandler (bool Enabled=TimePassesIsEnabled)
~TimePassesHandler ()
Destructor handles the print action if it has not been handled before.
void print ()
Prints out timing information and then resets the timers.
TimePassesHandler (const TimePassesHandler &)=delete
void operator= (const TimePassesHandler &)=delete
void registerCallbacks (PassInstrumentationCallbacks &PIC)
void setOutStream (raw_ostream &OutStream)
Set a custom output stream for subsequent reporting.
Detailed Description
This class implements -time-passes functionality for new pass manager.
It provides the pass-instrumentation callbacks that measure the pass execution time. They collect timing info into individual timers as passes are being run. At the end of its life-time it prints the resulting timing report.
Definition at line 49 of file PassTimingInfo.h.
Constructor & Destructor Documentation
TimePassesHandler() [1/2]
llvm::TimePassesHandler::TimePassesHandler (bool Enabled = TimePassesIsEnabled)
Definition at line 184 of file PassTimingInfo.cpp.
Referenced by ~TimePassesHandler().
~TimePassesHandler()
llvm::TimePassesHandler::~TimePassesHandler () inline
Destructor handles the print action if it has not been handled before.
Definition at line 78 of file PassTimingInfo.h.
References LLVM_DUMP_METHOD, operator=(), print(), registerCallbacks(), setOutStream(), and TimePassesHandler().
TimePassesHandler() [2/2]
llvm::TimePassesHandler::TimePassesHandler (const TimePassesHandler &) delete
Member Function Documentation
operator=()
void llvm::TimePassesHandler::operator= (const TimePassesHandler &) delete
Referenced by ~TimePassesHandler().
print()
void llvm::TimePassesHandler::print ()
Prints out timing information and then resets the timers.
Definition at line 191 of file PassTimingInfo.cpp.
References assert(), llvm::CreateInfoOutputFile(), llvm::dbgs(), llvm::Timer::hasTriggered(), I, llvm::Timer::isRunning(), LLVM_DUMP_METHOD, llvm::TimerGroup::print(), and llvm::Timer::startTimer().
Referenced by ~TimePassesHandler().
registerCallbacks()
void llvm::TimePassesHandler::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 262 of file PassTimingInfo.cpp.
References P, llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback(), and llvm::PassInstrumentationCallbacks::registerBeforePassCallback().
Referenced by ~TimePassesHandler().
setOutStream()
void llvm::TimePassesHandler::setOutStream (raw_ostream & OutStream)
Set a custom output stream for subsequent reporting.
Definition at line 187 of file PassTimingInfo.cpp.
Referenced by ~TimePassesHandler().
The documentation for this class was generated from the following files:
include/llvm/IR/PassTimingInfo.h
lib/IR/PassTimingInfo.cpp