LLVM: llvm::FunctionAnalysisManagerCGSCCProxy::Result Class Reference
llvm::FunctionAnalysisManagerCGSCCProxy::Result Class Reference
#include "llvm/Analysis/CGSCCPassManager.h"
Public Member Functions
Result (FunctionAnalysisManager &FAM)
FunctionAnalysisManager & getManager ()
Accessor for the analysis manager.
bool invalidate (LazyCallGraph::SCC &C, const PreservedAnalyses &PA, CGSCCAnalysisManager::Invalidator &Inv)
Detailed Description
Definition at line 382 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
Result()
llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result (FunctionAnalysisManager & FAM) inline explicit
Definition at line 384 of file CGSCCPassManager.h.
Member Function Documentation
getManager()
FunctionAnalysisManager& llvm::FunctionAnalysisManagerCGSCCProxy::Result::getManager () inline
Accessor for the analysis manager.
Definition at line 387 of file CGSCCPassManager.h.
References C, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs >::Result::invalidate(), and llvm::RequireAnalysisPass< AnalysisT, IRUnitT, AnalysisManagerT, ExtraArgTs >::run().
invalidate()
bool llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate (LazyCallGraph::SCC & C, const PreservedAnalyses & PA, CGSCCAnalysisManager::Invalidator & Inv)
Definition at line 240 of file CGSCCPassManager.cpp.
References llvm::PreservedAnalyses::abandon(), llvm::PreservedAnalyses::allAnalysesInSetPreserved(), llvm::PreservedAnalyses::areAllPreserved(), F(), llvm::PreservedAnalyses::getChecker(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate(), and N.
The documentation for this class was generated from the following files:
include/llvm/Analysis/CGSCCPassManager.h
lib/Analysis/CGSCCPassManager.cpp