LLVM: llvm::orc::ExecutionSession Class Reference
llvm::orc::ExecutionSession Class Reference
An ExecutionSession represents a running JIT program.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Types
using ErrorReporter = std::function< void(Error)>
For reporting errors.
using DispatchMaterializationFunction = std::function< void(JITDylib &JD, std::unique_ptr< MaterializationUnit > MU)>
For dispatching MaterializationUnit::materialize calls.
using LegacyAsyncLookupFunction = std::function< SymbolNameSet(std::shared_ptr< AsynchronousSymbolQuery > Q, SymbolNameSet Names)>
Public Member Functions
ExecutionSession (std::shared_ptr< SymbolStringPool > SSP=nullptr)
Construct an ExecutionSession.
SymbolStringPtr intern (StringRef SymName)
Add a symbol name to the SymbolStringPool and return a pointer to it.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Returns a shared_ptr to the SymbolStringPool for this ExecutionSession.
template<typename Func >
auto runSessionLocked (Func &&F) -> decltype(F())
Run the given lambda with the session mutex locked.
JITDylib * getJITDylibByName (StringRef Name)
Return a pointer to the "name" JITDylib.
JITDylib & createJITDylib (std::string Name)
Add a new JITDylib to this ExecutionSession.
VModuleKey allocateVModule ()
Allocate a module key for a new module to add to the JIT.
void releaseVModule (VModuleKey Key)
Return a module key to the ExecutionSession so that it can be re-used.
ExecutionSession & setErrorReporter (ErrorReporter ReportError)
Set the error reporter function.
void reportError (Error Err)
Report a error for this execution session.
ExecutionSession & setDispatchMaterialization (DispatchMaterializationFunction DispatchMaterialization)
Set the materialization dispatch function.
void legacyFailQuery (AsynchronousSymbolQuery &Q, Error Err)
Expected< SymbolMap > legacyLookup (LegacyAsyncLookupFunction AsyncLookup, SymbolNameSet Names, SymbolState RequiredState, RegisterDependenciesFunction RegisterDependencies)
A legacy lookup function for JITSymbolResolverAdapter.
void lookup (LookupKind K, const JITDylibSearchOrder &SearchOrder, SymbolLookupSet Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete, RegisterDependenciesFunction RegisterDependencies)
Search the given JITDylib list for the given symbols.
Expected< SymbolMap > lookup (const JITDylibSearchOrder &SearchOrder, const SymbolLookupSet &Symbols, LookupKind K=LookupKind::Static, SymbolState RequiredState=SymbolState::Ready, RegisterDependenciesFunction RegisterDependencies=NoDependenciesToRegister)
Blocking version of lookup above.
Expected< JITEvaluatedSymbol > lookup (const JITDylibSearchOrder &SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Expected< JITEvaluatedSymbol > lookup (ArrayRef< JITDylib *> SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Expected< JITEvaluatedSymbol > lookup (ArrayRef< JITDylib *> SearchOrder, StringRef Symbol)
Convenience version of blocking lookup.
void dispatchMaterialization (JITDylib &JD, std::unique_ptr< MaterializationUnit > MU)
Materialize the given unit.
void dump (raw_ostream &OS)
Dump the state of all the JITDylibs in this session.
Friends
class JITDylib
Detailed Description
An ExecutionSession represents a running JIT program.
Definition at line 1058 of file Core.h.
Member Typedef Documentation
DispatchMaterializationFunction
using llvm::orc::ExecutionSession::DispatchMaterializationFunction = std::function<void(JITDylib &JD, std::unique_ptr<MaterializationUnit> MU)>
For dispatching MaterializationUnit::materialize calls.
Definition at line 1068 of file Core.h.
ErrorReporter
using llvm::orc::ExecutionSession::ErrorReporter = std::function<void(Error)>
For reporting errors.
Definition at line 1064 of file Core.h.
LegacyAsyncLookupFunction
using llvm::orc::ExecutionSession::LegacyAsyncLookupFunction = std::function<SymbolNameSet(std::shared_ptr<AsynchronousSymbolQuery> Q, SymbolNameSet Names)>
Definition at line 1130 of file Core.h.
Constructor & Destructor Documentation
ExecutionSession()
llvm::orc::ExecutionSession::ExecutionSession (std::shared_ptr< SymbolStringPool > SSP = nullptr)
Construct an ExecutionSession.
SymbolStringPools may be shared between ExecutionSessions.
Definition at line 1880 of file Core.cpp.
Member Function Documentation
allocateVModule()
VModuleKey llvm::orc::ExecutionSession::allocateVModule () inline
Allocate a module key for a new module to add to the JIT.
Definition at line 1099 of file Core.h.
createJITDylib()
JITDylib & llvm::orc::ExecutionSession::createJITDylib (std::string Name)
Add a new JITDylib to this ExecutionSession.
The JITDylib Name is required to be unique. Clients should verify that names are not being re-used (e.g. by calling getJITDylibByName) if names are based on user input.
Definition at line 1893 of file Core.cpp.
References assert(), getJITDylibByName(), JITDylib, and runSessionLocked().
dispatchMaterialization()
void llvm::orc::ExecutionSession::dispatchMaterialization (JITDylib & JD, std::unique_ptr< MaterializationUnit > MU) inline
Materialize the given unit.
Definition at line 1196 of file Core.h.
References llvm::dbgs(), llvm::dump(), llvm::orc::JITDylib::getName(), and LLVM_DEBUG.
Referenced by dump().
dump()
void llvm::orc::ExecutionSession::dump (raw_ostream & OS)
Dump the state of all the JITDylibs in this session.
Definition at line 2165 of file Core.cpp.
References assert(), dispatchMaterialization(), llvm::Lock, and runSessionLocked().
getJITDylibByName()
JITDylib * llvm::orc::ExecutionSession::getJITDylibByName (StringRef Name)
Return a pointer to the "name" JITDylib.
Ownership of JITDylib remains within Execution Session
Definition at line 1884 of file Core.cpp.
References Name, and runSessionLocked().
Referenced by createJITDylib().
getSymbolStringPool()
std::shared_ptr<SymbolStringPool> llvm::orc::ExecutionSession::getSymbolStringPool () const inline
Returns a shared_ptr to the SymbolStringPool for this ExecutionSession.
Definition at line 1079 of file Core.h.
intern()
SymbolStringPtr llvm::orc::ExecutionSession::intern (StringRef SymName) inline
Add a symbol name to the SymbolStringPool and return a pointer to it.
Definition at line 1076 of file Core.h.
Referenced by llvm::orc::getObjectSymbolFlags(), llvm::orc::JITSymbolResolverAdapter::getResponsibilitySet(), llvm::orc::JITSymbolResolverAdapter::lookup(), lookup(), and llvm::orc::MangleAndInterner::operator()().
legacyFailQuery()
void llvm::orc::ExecutionSession::legacyFailQuery (AsynchronousSymbolQuery & Q, Error Err)
Definition at line 1902 of file Core.cpp.
Referenced by llvm::orc::JITSymbolResolverAdapter::lookup(), and llvm::orc::lookupWithLegacyFn().
legacyLookup()
Expected< SymbolMap > llvm::orc::ExecutionSession::legacyLookup (LegacyAsyncLookupFunction AsyncLookup, SymbolNameSet Names, SymbolState RequiredState, RegisterDependenciesFunction RegisterDependencies)
A legacy lookup function for JITSymbolResolverAdapter.
Do not use – this will be removed soon.
Definition at line 1917 of file Core.cpp.
References _, runSessionLocked(), and llvm::Error::success().
lookup() [1/5]
void llvm::orc::ExecutionSession::lookup (LookupKind K, const JITDylibSearchOrder & SearchOrder, SymbolLookupSet Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete, RegisterDependenciesFunction RegisterDependencies)
Search the given JITDylib list for the given symbols.
SearchOrder lists the JITDylibs to search. For each dylib, the associated boolean indicates whether the search should match against non-exported (hidden visibility) symbols in that dylib (true means match against non-exported symbols, false means do not match).
The NotifyComplete callback will be called once all requested symbols reach the required state.
If all symbols are found, the RegisterDependencies function will be called while the session lock is held. This gives clients a chance to register dependencies for on the queried symbols for any symbols they are materializing (if a MaterializationResponsibility instance is present, this can be implemented by calling MaterializationResponsibility::addDependencies). If there are no dependenant symbols for this query (e.g. it is being made by a top level client to get an address to call) then the value NoDependenciesToRegister can be used.
Definition at line 1984 of file Core.cpp.
References assert(), llvm::dbgs(), LLVM_DEBUG, and runSessionLocked().
Referenced by llvm::orc::LazyCallThroughManager::callThroughToSymbol(), and lookup().
lookup() [2/5]
Expected< SymbolMap > llvm::orc::ExecutionSession::lookup (const JITDylibSearchOrder & SearchOrder, const SymbolLookupSet & Symbols, LookupKind K = LookupKind::Static, SymbolState RequiredState = SymbolState::Ready, RegisterDependenciesFunction RegisterDependencies = NoDependenciesToRegister)
Blocking version of lookup above.
Returns the resolved symbol map. If WaitUntilReady is true (the default), will not return until all requested symbols are ready (or an error occurs). If WaitUntilReady is false, will return as soon as all requested symbols are resolved, or an error occurs. If WaitUntilReady is false and an error occurs after resolution, the function will return a success value, but the error will be reported via reportErrors.
Definition at line 2087 of file Core.cpp.
References _, lookup(), and llvm::Error::success().
lookup() [3/5]
Expected< JITEvaluatedSymbol > llvm::orc::ExecutionSession::lookup (const JITDylibSearchOrder & SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Searches each of the JITDylibs in the search order in turn for the given symbol.
Definition at line 2141 of file Core.cpp.
References assert(), lookup(), llvm::orc::NoDependenciesToRegister, llvm::orc::Ready, and llvm::orc::Static.
lookup() [4/5]
Expected< JITEvaluatedSymbol > llvm::orc::ExecutionSession::lookup (ArrayRef< JITDylib *> SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Searches each of the JITDylibs in the search order in turn for the given symbol. The search will not find non-exported symbols.
Definition at line 2155 of file Core.cpp.
References lookup(), and llvm::orc::makeJITDylibSearchOrder().
lookup() [5/5]
Expected< JITEvaluatedSymbol > llvm::orc::ExecutionSession::lookup (ArrayRef< JITDylib *> SearchOrder, StringRef Symbol)
Convenience version of blocking lookup.
Searches each of the JITDylibs in the search order in turn for the given symbol. The search will not find non-exported symbols.
Definition at line 2161 of file Core.cpp.
References intern(), and lookup().
releaseVModule()
void llvm::orc::ExecutionSession::releaseVModule (VModuleKey Key) inline
Return a module key to the ExecutionSession so that it can be re-used.
This should only be done once all resources associated with the original key have been released.
Definition at line 1106 of file Core.h.
reportError()
void llvm::orc::ExecutionSession::reportError (Error Err) inline
Report a error for this execution session.
Unhandled errors can be sent here to log them.
Definition at line 1118 of file Core.h.
Referenced by llvm::orc::LazyCallThroughManager::callThroughToSymbol(), llvm::orc::ObjectTransformLayer::emit(), llvm::orc::IRTransformLayer::emit(), llvm::orc::IRCompileLayer::emit(), llvm::orc::RTDyldObjectLinkingLayer::emit(), and llvm::orc::LazyReexportsMaterializationUnit::getName().
runSessionLocked()
template<typename Func > auto llvm::orc::ExecutionSession::runSessionLocked (Func && F) -> decltype(F()) inline
Run the given lambda with the session mutex locked.
Definition at line 1082 of file Core.h.
References F(), llvm::Lock, and Name.
Referenced by createJITDylib(), dump(), getJITDylibByName(), llvm::orc::IRMaterializationUnit::getName(), legacyLookup(), lookup(), and llvm::orc::MaterializationResponsibility::replace().
setDispatchMaterialization()
ExecutionSession& llvm::orc::ExecutionSession::setDispatchMaterialization (DispatchMaterializationFunction DispatchMaterialization) inline
Set the materialization dispatch function.
Definition at line 1121 of file Core.h.
setErrorReporter()
ExecutionSession& llvm::orc::ExecutionSession::setErrorReporter (ErrorReporter ReportError) inline
Set the error reporter function.
Definition at line 1110 of file Core.h.
Friends And Related Function Documentation
JITDylib
friend class JITDylib friend
Definition at line 1060 of file Core.h.
Referenced by createJITDylib().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp