LLVM: llvm::DomTreeNodeBase< NodeT > Class Template Reference
llvm::DomTreeNodeBase< NodeT > Class Template Reference
Base class for the actual dominator tree node.
#include "llvm/CodeGen/LiveRangeCalc.h"
Public Types
using iterator = typename std::vector< DomTreeNodeBase * >::iterator
using const_iterator = typename std::vector< DomTreeNodeBase * >::const_iterator
Public Member Functions
DomTreeNodeBase (NodeT *BB, DomTreeNodeBase *iDom)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
NodeT * getBlock () const
DomTreeNodeBase * getIDom () const
unsigned getLevel () const
const std::vector< DomTreeNodeBase * > & getChildren () const
std::unique_ptr< DomTreeNodeBase > addChild (std::unique_ptr< DomTreeNodeBase > C)
size_t getNumChildren () const
void clearAllChildren ()
bool compare (const DomTreeNodeBase *Other) const
void setIDom (DomTreeNodeBase *NewIDom)
unsigned getDFSNumIn () const
getDFSNumIn/getDFSNumOut - These return the DFS visitation order for nodes in the dominator tree.
unsigned getDFSNumOut () const
Friends
class PostDominatorTree
class DominatorTreeBase< NodeT, false >
class DominatorTreeBase< NodeT, true >
struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, false > >
struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, true > >
Detailed Description
template<class NodeT>
class llvm::DomTreeNodeBase< NodeT >
Base class for the actual dominator tree node.
Definition at line 37 of file LiveRangeCalc.h.
Member Typedef Documentation
const_iterator
template<class NodeT> using llvm::DomTreeNodeBase< NodeT >::const_iterator = typename std::vector<DomTreeNodeBase *>::const_iterator
Definition at line 74 of file GenericDomTree.h.
iterator
template<class NodeT> using llvm::DomTreeNodeBase< NodeT >::iterator = typename std::vector<DomTreeNodeBase *>::iterator
Definition at line 72 of file GenericDomTree.h.
Constructor & Destructor Documentation
DomTreeNodeBase()
template<class NodeT> llvm::DomTreeNodeBase< NodeT >::DomTreeNodeBase (NodeT * BB, DomTreeNodeBase< NodeT > * iDom) inline
Definition at line 69 of file GenericDomTree.h.
Member Function Documentation
addChild()
template<class NodeT> std::unique_ptr<DomTreeNodeBase> llvm::DomTreeNodeBase< NodeT >::addChild (std::unique_ptr< DomTreeNodeBase< NodeT > > C) inline
Definition at line 87 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BasicBlock, IsPostDom >::addNewBlock(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), and llvm::DominatorTreeBase< BasicBlock, IsPostDom >::setNewRoot().
begin() [1/2]
template<class NodeT> iterator llvm::DomTreeNodeBase< NodeT >::begin () inline
Definition at line 76 of file GenericDomTree.h.
Referenced by llvm::ForwardDominanceFrontierBase< BasicBlock >::calculate(), llvm::DomTreeGraphTraitsBase< const VPDomTreeNode, VPDomTreeNode::const_iterator >::child_begin(), llvm::MachineDomTreeGraphTraitsBase< const MachineDomTreeNode, MachineDomTreeNode::const_iterator >::child_begin(), computeDomSubtreeCost(), llvm::CodeExtractor::findInputsOutputs(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::getDescendants(), SinkInstruction(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers().
begin() [2/2]
template<class NodeT> const_iterator llvm::DomTreeNodeBase< NodeT >::begin () const inline
Definition at line 78 of file GenericDomTree.h.
clearAllChildren()
template<class NodeT> void llvm::DomTreeNodeBase< NodeT >::clearAllChildren () inline
Definition at line 95 of file GenericDomTree.h.
compare()
template<class NodeT> bool llvm::DomTreeNodeBase< NodeT >::compare (const DomTreeNodeBase< NodeT > * Other) const inline
Definition at line 97 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BasicBlock, IsPostDom >::compare().
end() [1/2]
template<class NodeT> iterator llvm::DomTreeNodeBase< NodeT >::end () inline
Definition at line 77 of file GenericDomTree.h.
Referenced by llvm::ForwardDominanceFrontierBase< BasicBlock >::calculate(), llvm::DomTreeGraphTraitsBase< const VPDomTreeNode, VPDomTreeNode::const_iterator >::child_end(), llvm::MachineDomTreeGraphTraitsBase< const MachineDomTreeNode, MachineDomTreeNode::const_iterator >::child_end(), computeDomSubtreeCost(), llvm::CodeExtractor::findInputsOutputs(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::getDescendants(), SinkInstruction(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers().
end() [2/2]
template<class NodeT> const_iterator llvm::DomTreeNodeBase< NodeT >::end () const inline
Definition at line 79 of file GenericDomTree.h.
getBlock()
template<class NodeT> NodeT* llvm::DomTreeNodeBase< NodeT >::getBlock () const inline
Definition at line 81 of file GenericDomTree.h.
Referenced by llvm::LoopInfoBase< BasicBlock, Loop >::analyze(), llvm::MemorySSAUpdater::applyInsertUpdates(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), llvm::IDFCalculatorBase< BasicBlock, IsPostDom >::calculate(), llvm::ForwardDominanceFrontierBase< BasicBlock >::calculate(), CloneLoopBlocks(), cloneLoopBlocks(), llvm::cloneLoopWithPreheader(), llvm::DomTreeNodeBase< VPBlockBase >::compare(), computeBlocksDominatingExits(), computeDomSubtreeCost(), containsUnconditionalCallSafepoint(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::getDescendants(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasProperSupport(), llvm::SSAUpdaterBulk::HasValueForBlock(), llvm::hoistRegion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), isProfitableChain(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::isVirtualRoot(), llvm::peelLoop(), preheader(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), llvm::UnrollRuntimeLoopRemainder(), UpdateAnalysisInformation(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty(), and visitDomSubTree().
getChildren()
template<class NodeT> const std::vector<DomTreeNodeBase *>& llvm::DomTreeNodeBase< NodeT >::getChildren () const inline
Definition at line 85 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BasicBlock, IsPostDom >::eraseNode(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
getDFSNumIn()
template<class NodeT> unsigned llvm::DomTreeNodeBase< NodeT >::getDFSNumIn () const inline
getDFSNumIn/getDFSNumOut - These return the DFS visitation order for nodes in the dominator tree.
They are only guaranteed valid if updateDFSNumbers() has been called.
Definition at line 137 of file GenericDomTree.h.
Referenced by llvm::IDFCalculatorBase< BasicBlock, IsPostDom >::calculate(), llvm::PredicateInfoClasses::ValueDFS_Compare::comparePHIRelated(), llvm::OrderedInstructions::dfsBefore(), llvm::PredicateInfoClasses::ValueDFS_Compare::localComesBefore(), NewGVN::ValueDFS::operator<(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers().
getDFSNumOut()
template<class NodeT> unsigned llvm::DomTreeNodeBase< NodeT >::getDFSNumOut () const inline
Definition at line 138 of file GenericDomTree.h.
Referenced by llvm::PredicateInfoClasses::ValueDFS_Compare::localComesBefore(), NewGVN::ValueDFS::operator<(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers().
getIDom()
template<class NodeT> DomTreeNodeBase* llvm::DomTreeNodeBase< NodeT >::getIDom () const inline
Definition at line 82 of file GenericDomTree.h.
Referenced by llvm::MemorySSAUpdater::applyInsertUpdates(), CloneLoopBlocks(), cloneLoopBlocks(), llvm::cloneLoopWithPreheader(), computeBlocksDominatingExits(), containsUnconditionalCallSafepoint(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::dominates(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::eraseNode(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode(), llvm::SSAUpdaterBulk::HasValueForBlock(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isSimplifiedLoopNest(), mayUsePostIncMode(), llvm::peelLoop(), preheader(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::Split(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels().
getLevel()
template<class NodeT> unsigned llvm::DomTreeNodeBase< NodeT >::getLevel () const inline
Definition at line 83 of file GenericDomTree.h.
Referenced by llvm::IDFCalculatorBase< BasicBlock, IsPostDom >::calculate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::dominates(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertionInfo::Compare::operator()(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA(), llvm::DominatorTreeBase< BasicBlock, IsPostDom >::Split(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels().
getNumChildren()
template<class NodeT> size_t llvm::DomTreeNodeBase< NodeT >::getNumChildren () const inline
Definition at line 93 of file GenericDomTree.h.
Referenced by llvm::DomTreeNodeBase< VPBlockBase >::compare(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode().
setIDom()
template<class NodeT> void llvm::DomTreeNodeBase< NodeT >::setIDom (DomTreeNodeBase< NodeT > * NewIDom) inline
Definition at line 117 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BasicBlock, IsPostDom >::changeImmediateDominator(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion().
Friends And Related Function Documentation
DominatorTreeBase< NodeT, false >
template<class NodeT> friend class DominatorTreeBase< NodeT, false > friend
Definition at line 56 of file GenericDomTree.h.
DominatorTreeBase< NodeT, true >
template<class NodeT> friend class DominatorTreeBase< NodeT, true > friend
Definition at line 57 of file GenericDomTree.h.
DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, false > >
template<class NodeT> friend struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, false > > friend
Definition at line 58 of file GenericDomTree.h.
DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, true > >
template<class NodeT> friend struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, true > > friend
Definition at line 59 of file GenericDomTree.h.
PostDominatorTree
template<class NodeT> friend class PostDominatorTree friend
Definition at line 55 of file GenericDomTree.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveRangeCalc.h
include/llvm/Support/GenericDomTree.h