LLVM: llvm::mca::DispatchStage Class Reference
llvm::mca::DispatchStage Class Reference final
#include "llvm/MCA/Stages/DispatchStage.h"
Public Member Functions
DispatchStage (const MCSubtargetInfo &Subtarget, const MCRegisterInfo &MRI, unsigned MaxDispatchWidth, RetireControlUnit &R, RegisterFile &F)
bool isAvailable (const InstRef &IR) const override
Returns true if it can execute IR during this cycle.
bool hasWorkToComplete () const override
Returns true if some instructions are still executing this stage.
Error cycleStart () override
Called once at the start of each cycle.
Error execute (InstRef &IR) override
The primary action that this stage performs on instruction IR.
void dump () const
Public Member Functions inherited from llvm::mca::Stage
Stage ()
virtual ~Stage ()
virtual Error cycleEnd ()
Called once at the end of each cycle.
void setNextInSequence (Stage *NextStage)
bool checkNextStage (const InstRef &IR) const
Error moveToTheNextStage (InstRef &IR)
Called when an instruction is ready to move the next pipeline stage.
void addListener (HWEventListener *Listener)
Add a listener to receive callbacks during the execution of this stage.
template<typename EventT >
void notifyEvent (const EventT &Event) const
Notify listeners of a particular hardware event.
Additional Inherited Members
Protected Member Functions inherited from llvm::mca::Stage
const std::set< HWEventListener * > & getListeners () const
Detailed Description
Definition at line 50 of file DispatchStage.h.
Constructor & Destructor Documentation
DispatchStage()
llvm::mca::DispatchStage::DispatchStage (const MCSubtargetInfo & Subtarget, const MCRegisterInfo & MRI, unsigned MaxDispatchWidth, RetireControlUnit & R, RegisterFile & F)
Definition at line 28 of file DispatchStage.cpp.
References llvm::mca::RegisterFile::addRegisterRead(), llvm::mca::RegisterFile::addRegisterWrite(), assert(), llvm::mca::Stage::checkNextStage(), llvm::dbgs(), llvm::mca::RetireControlUnit::dispatch(), llvm::mca::Instruction::dispatch(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::mca::InstrDesc::EndGroup, llvm::mca::InstructionBase::getDefs(), llvm::mca::InstructionBase::getDesc(), llvm::mca::InstRef::getInstruction(), llvm::mca::InstructionBase::getNumMicroOps(), llvm::mca::RegisterFile::getNumRegisterFiles(), llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::InstRef::getSourceIndex(), llvm::mca::InstructionBase::getUses(), IR, llvm::mca::RetireControlUnit::isAvailable(), llvm::mca::RegisterFile::isAvailable(), llvm::mca::Instruction::isEliminated(), llvm::mca::InstructionBase::isOptimizableMove(), llvm::MCSchedModel::IssueWidth, LLVM_DEBUG, llvm::mca::Stage::moveToTheNextStage(), llvm::mca::HWStallEvent::RegisterFileStall, llvm::ISD::RegisterMask, llvm::mca::HWStallEvent::RetireControlUnitStall, llvm::mca::Instruction::setEliminated(), and llvm::mca::RegisterFile::tryEliminateMove().
Member Function Documentation
cycleStart()
Error llvm::mca::DispatchStage::cycleStart () override virtual
Called once at the start of each cycle.
This can be used as a setup phase to prepare for the executions during the cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 138 of file DispatchStage.cpp.
References assert(), llvm::mca::RegisterFile::cycleStart(), and llvm::mca::RegisterFile::getNumRegisterFiles().
Referenced by hasWorkToComplete().
dump()
void llvm::mca::DispatchStage::dump () const
Definition at line 181 of file DispatchStage.cpp.
References llvm::mca::RetireControlUnit::dump(), and llvm::mca::RegisterFile::dump().
Referenced by hasWorkToComplete().
execute()
Error llvm::mca::DispatchStage::execute (InstRef & IR) override virtual
The primary action that this stage performs on instruction IR.
Implements llvm::mca::Stage.
Definition at line 175 of file DispatchStage.cpp.
References assert().
Referenced by hasWorkToComplete().
hasWorkToComplete()
bool llvm::mca::DispatchStage::hasWorkToComplete () const inline override virtual
Returns true if some instructions are still executing this stage.
Implements llvm::mca::Stage.
Definition at line 77 of file DispatchStage.h.
References cycleStart(), dump(), and execute().
isAvailable()
bool llvm::mca::DispatchStage::isAvailable (const InstRef & IR) const override virtual
Returns true if it can execute IR during this cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 158 of file DispatchStage.cpp.
References llvm::mca::InstrDesc::BeginGroup, llvm::mca::InstructionBase::getDesc(), llvm::mca::InstRef::getInstruction(), llvm::mca::InstructionBase::getNumMicroOps(), and llvm::cl::Required.
The documentation for this class was generated from the following files:
include/llvm/MCA/Stages/DispatchStage.h
lib/MCA/Stages/DispatchStage.cpp