LLVM: llvm::LiveRange Class Reference
llvm::LiveRange Class Reference
This class represents the liveness of a register, stack slot, etc.
#include "llvm/CodeGen/LiveInterval.h"
Classes
struct Segment
This represents a simple continuous liveness interval for a value.
Public Types
using Segments = SmallVector< Segment, 2 >
using VNInfoList = SmallVector< VNInfo *, 2 >
using SegmentSet = std::set< Segment >
using iterator = Segments::iterator
using const_iterator = Segments::const_iterator
using vni_iterator = VNInfoList::iterator
using const_vni_iterator = VNInfoList::const_iterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
vni_iterator vni_begin ()
vni_iterator vni_end ()
const_vni_iterator vni_begin () const
const_vni_iterator vni_end () const
LiveRange (bool UseSegmentSet=false)
Constructs a new LiveRange object.
LiveRange (const LiveRange &Other, BumpPtrAllocator &Allocator)
Constructs a new LiveRange object by copying segments and valnos from another LiveRange.
void assign (const LiveRange &Other, BumpPtrAllocator &Allocator)
Copies values numbers and live segments from Other into this range.
iterator advanceTo (iterator I, SlotIndex Pos)
advanceTo - Advance the specified iterator to point to the Segment containing the specified position, or end() if the position is past the end of the range.
const_iterator advanceTo (const_iterator I, SlotIndex Pos) const
iterator find (SlotIndex Pos)
find - Return an iterator pointing to the first segment that ends after Pos, or end().
const_iterator find (SlotIndex Pos) const
void clear ()
size_t size () const
bool hasAtLeastOneValue () const
bool containsOneValue () const
unsigned getNumValNums () const
VNInfo * getValNumInfo (unsigned ValNo)
getValNumInfo - Returns pointer to the specified val#.
const VNInfo * getValNumInfo (unsigned ValNo) const
bool containsValue (const VNInfo *VNI) const
containsValue - Returns true if VNI belongs to this range.
VNInfo * getNextValue (SlotIndex def, VNInfo::Allocator &VNInfoAllocator)
getNextValue - Create a new value number and return it.
VNInfo * createDeadDef (SlotIndex Def, VNInfo::Allocator &VNIAlloc)
createDeadDef - Make sure the range has a value defined at Def.
VNInfo * createDeadDef (VNInfo *VNI)
Create a def of value VNI.
VNInfo * createValueCopy (const VNInfo *orig, VNInfo::Allocator &VNInfoAllocator)
Create a copy of the given value.
void RenumberValues ()
RenumberValues - Renumber all values in order of appearance and remove unused values.
VNInfo * MergeValueNumberInto (VNInfo *V1, VNInfo *V2)
MergeValueNumberInto - This method is called when two value numbers are found to be equivalent.
void MergeSegmentsInAsValue (const LiveRange &RHS, VNInfo *LHSValNo)
Merge all of the live segments of a specific val# in RHS into this live range as the specified value number.
void MergeValueInAsValue (const LiveRange &RHS, const VNInfo *RHSValNo, VNInfo *LHSValNo)
MergeValueInAsValue - Merge all of the segments of a specific val# in RHS into this live range as the specified value number.
bool empty () const
SlotIndex beginIndex () const
beginIndex - Return the lowest numbered slot covered.
SlotIndex endIndex () const
endNumber - return the maximum point of the range of the whole, exclusive.
bool expiredAt (SlotIndex index) const
bool liveAt (SlotIndex index) const
const Segment * getSegmentContaining (SlotIndex Idx) const
Return the segment that contains the specified index, or null if there is none.
Segment * getSegmentContaining (SlotIndex Idx)
Return the live segment that contains the specified index, or null if there is none.
VNInfo * getVNInfoAt (SlotIndex Idx) const
getVNInfoAt - Return the VNInfo that is live at Idx, or NULL.
VNInfo * getVNInfoBefore (SlotIndex Idx) const
getVNInfoBefore - Return the VNInfo that is live up to but not necessarilly including Idx, or NULL.
iterator FindSegmentContaining (SlotIndex Idx)
Return an iterator to the segment that contains the specified index, or end() if there is none.
const_iterator FindSegmentContaining (SlotIndex Idx) const
bool overlaps (const LiveRange &other) const
overlaps - Return true if the intersection of the two live ranges is not empty.
bool overlaps (const LiveRange &Other, const CoalescerPair &CP, const SlotIndexes &) const
overlaps - Return true if the two ranges have overlapping segments that are not coalescable according to CP.
bool overlaps (SlotIndex Start, SlotIndex End) const
overlaps - Return true if the live range overlaps an interval specified by [Start, End).
bool overlapsFrom (const LiveRange &Other, const_iterator StartPos) const
overlapsFrom - Return true if the intersection of the two live ranges is not empty.
bool covers (const LiveRange &Other) const
Returns true if all segments of the Other live range are completely covered by this live range.
iterator addSegment (Segment S)
Add the specified Segment to this range, merging segments as appropriate.
std::pair< VNInfo *, bool > extendInBlock (ArrayRef< SlotIndex > Undefs, SlotIndex StartIdx, SlotIndex Kill)
Attempt to extend a value defined after StartIdx to include Use.
VNInfo * extendInBlock (SlotIndex StartIdx, SlotIndex Kill)
Simplified version of the above "extendInBlock", which assumes that no register lanes are undefined by <def,read-undef> operands.
void join (LiveRange &Other, const int *ValNoAssignments, const int *RHSValNoAssignments, SmallVectorImpl< VNInfo *> &NewVNInfo)
join - Join two live ranges (this, and other) together.
bool isLocal (SlotIndex Start, SlotIndex End) const
True iff this segment is a single segment that lies between the specified boundaries, exclusively.
void removeSegment (SlotIndex Start, SlotIndex End, bool RemoveDeadValNo=false)
Remove the specified segment from this range.
void removeSegment (Segment S, bool RemoveDeadValNo=false)
iterator removeSegment (iterator I)
Remove segment pointed to by iterator I from this range.
LiveQueryResult Query (SlotIndex Idx) const
Query Liveness at Idx.
void removeValNo (VNInfo *ValNo)
removeValNo - Remove all the segments defined by the specified value#.
bool isZeroLength (SlotIndexes *Indexes) const
Returns true if the live range is zero length, i.e.
bool isLiveAtIndexes (ArrayRef< SlotIndex > Slots) const
bool operator< (const LiveRange &other) const
bool isUndefIn (ArrayRef< SlotIndex > Undefs, SlotIndex Begin, SlotIndex End) const
Returns true if there is an explicit "undef" between Begin End.
void flushSegmentSet ()
Flush segment set into the regular segment vector.
template<typename Range , typename OutputIt >
bool findIndexesLiveAt (Range &&R, OutputIt O) const
Stores indexes from the input index sequence R at which this LiveRange is live to the output O iterator.
void print (raw_ostream &OS) const
void dump () const
void verify () const
Walk the range and assert if any invariants fail to hold.
Public Attributes
Segments segments
VNInfoList valnos
std::unique_ptr< SegmentSet > segmentSet
Protected Member Functions
void append (const LiveRange::Segment S)
Append a segment to the list of segments.
Friends
class LiveRangeUpdater
Detailed Description
This class represents the liveness of a register, stack slot, etc.
It manages an ordered list of Segment objects. The Segments are organized in a static single assignment form: At places where a new value is defined or different values reach a CFG join a new segment with a new value number is used.
Definition at line 156 of file LiveInterval.h.
Member Typedef Documentation
const_iterator
using llvm::LiveRange::const_iterator = Segments::const_iterator
Definition at line 212 of file LiveInterval.h.
const_vni_iterator
using llvm::LiveRange::const_vni_iterator = VNInfoList::const_iterator
Definition at line 221 of file LiveInterval.h.
iterator
using llvm::LiveRange::iterator = Segments::iterator
Definition at line 211 of file LiveInterval.h.
Segments
using llvm::LiveRange::Segments = SmallVector<Segment, 2>
Definition at line 199 of file LiveInterval.h.
SegmentSet
using llvm::LiveRange::SegmentSet = std::set<Segment>
Definition at line 208 of file LiveInterval.h.
vni_iterator
using llvm::LiveRange::vni_iterator = VNInfoList::iterator
Definition at line 220 of file LiveInterval.h.
VNInfoList
using llvm::LiveRange::VNInfoList = SmallVector<VNInfo *, 2>
Definition at line 200 of file LiveInterval.h.
Constructor & Destructor Documentation
LiveRange() [1/2]
llvm::LiveRange::LiveRange (bool UseSegmentSet = false) inline
Constructs a new LiveRange object.
Definition at line 230 of file LiveInterval.h.
LiveRange() [2/2]
llvm::LiveRange::LiveRange (const LiveRange & Other, BumpPtrAllocator & Allocator) inline
Constructs a new LiveRange object by copying segments and valnos from another LiveRange.
Definition at line 236 of file LiveInterval.h.
References assert(), and segmentSet.
Member Function Documentation
addSegment()
LiveRange::iterator LiveRange::addSegment (Segment S)
Add the specified Segment to this range, merging segments as appropriate.
This returns an iterator to the inserted segment (which may have grown since it was inserted).
Definition at line 548 of file LiveInterval.cpp.
References llvm::sys::path::end().
Referenced by addSegmentsWithValNo(), llvm::LiveIntervals::addSegmentToEndOfBlock(), allPhiOperandsUndefined(), createSegmentsForValues(), llvm::LiveRangeEdit::eraseVirtReg(), and llvm::CoalescerPair::isCoalescable().
advanceTo() [1/2]
iterator llvm::LiveRange::advanceTo (iterator I, SlotIndex Pos) inline
advanceTo - Advance the specified iterator to point to the Segment containing the specified position, or end() if the position is past the end of the range.
If no Segment contains this position, but the position is in a hole, this method returns an iterator pointing to the Segment immediately after the hole.
Definition at line 262 of file LiveInterval.h.
References assert(), llvm::sys::path::end(), and I.
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::LiveIntervalUnion::extract(), llvm::LiveIntervals::HMEditor::updateAllRanges(), and llvm::LiveDebugVariables::~LiveDebugVariables().
advanceTo() [2/2]
const_iterator llvm::LiveRange::advanceTo (const_iterator I, SlotIndex Pos) const inline
Definition at line 270 of file LiveInterval.h.
References assert(), llvm::sys::path::end(), llvm::find(), and I.
append()
void LiveRange::append (const LiveRange::Segment S) protected
Append a segment to the list of segments.
Definition at line 558 of file LiveInterval.cpp.
References assert(), and llvm::LiveRange::Segment::start.
assign()
void llvm::LiveRange::assign (const LiveRange & Other, BumpPtrAllocator & Allocator) inline
Copies values numbers and live segments from Other into this range.
Definition at line 243 of file LiveInterval.h.
References assert(), llvm::LiveRange::Segment::end, llvm::VNInfo::id, llvm::SmallVectorTemplateBase< T, bool >::push_back(), segments, segmentSet, llvm::LiveRange::Segment::start, llvm::LiveRange::Segment::valno, and valnos.
Referenced by isDefInSubRange(), and isFullUndefDef().
begin() [1/2]
iterator llvm::LiveRange::begin () inline
Definition at line 214 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::LiveRangeUpdater::add(), llvm::LiveIntervals::addKillFlags(), allPhiOperandsUndefined(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::SplitAnalysis::clear(), llvm::SplitAnalysis::countLiveBlocks(), llvm::createCopyConstrainDAGMutation(), llvm::LiveIntervalUnion::extract(), llvm::LiveRangeUpdater::flush(), llvm::CoalescerPair::isCoalescable(), isDefInSubRange(), llvm::SplitAnalysis::isOriginalEndpoint(), overlaps(), overlapsFrom(), llvm::LiveRangeUpdater::print(), regOverlapsSet(), llvm::LiveIntervals::shrinkToUses(), llvm::LiveIntervalUnion::unify(), llvm::LiveIntervals::HMEditor::updateAllRanges(), and llvm::LiveDebugVariables::~LiveDebugVariables().
begin() [2/2]
const_iterator llvm::LiveRange::begin () const inline
Definition at line 217 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
beginIndex()
SlotIndex llvm::LiveRange::beginIndex () const inline
beginIndex - Return the lowest numbered slot covered.
Definition at line 376 of file LiveInterval.h.
References assert(), llvm::empty(), and llvm::SmallVectorTemplateCommon< T, typename >::front().
Referenced by llvm::createCopyConstrainDAGMutation(), llvm::createGreedyRegisterAllocator(), operator<(), llvm::LiveInterval::operator<(), overlaps(), llvm::SystemZRegisterInfo::shouldCoalesce(), and llvm::LiveDebugVariables::~LiveDebugVariables().
clear()
void llvm::LiveRange::clear () inline
Definition at line 291 of file LiveInterval.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::LiveRangeCalc::calculate(), llvm::createGreedyRegisterAllocator(), getStartOrEndSlot(), and subRangeLiveAt().
containsOneValue()
bool llvm::LiveRange::containsOneValue () const inline
Definition at line 302 of file LiveInterval.h.
References llvm::SmallVectorBase::size().
containsValue()
bool llvm::LiveRange::containsValue (const VNInfo * VNI) const inline
containsValue - Returns true if VNI belongs to this range.
Definition at line 316 of file LiveInterval.h.
References llvm::VNInfo::id.
covers()
bool LiveRange::covers (const LiveRange & Other) const
Returns true if all segments of the Other live range are completely covered by this live range.
Adjacent live ranges do not affect the covering:the liverange [1,5](5,10] covers (3,7].
Definition at line 494 of file LiveInterval.cpp.
References llvm::sys::path::begin(), llvm::empty(), empty(), llvm::sys::path::const_iterator::end, llvm::sys::path::end(), llvm::LiveRange::Segment::end, I, llvm::VNInfo::id, llvm::VNInfo::markUnused(), llvm::RISCVFenceField::O, segments, and llvm::LiveRange::Segment::start.
createDeadDef() [1/2]
VNInfo * LiveRange::createDeadDef (SlotIndex Def, VNInfo::Allocator & VNIAlloc)
createDeadDef - Make sure the range has a value defined at Def.
If one already exists, return it. Otherwise allocate a new value and add liveness for a dead def.
Definition at line 370 of file LiveInterval.cpp.
Referenced by addSegmentsWithValNo(), allPhiOperandsUndefined(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), createDeadDef(), llvm::SplitEditor::dump(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), and llvm::LiveIntervals::print().
createDeadDef() [2/2]
VNInfo * LiveRange::createDeadDef (VNInfo * VNI)
Create a def of value VNI.
Return VNI. If there already exists a definition at VNI->def, the value defined there must be VNI.
Definition at line 378 of file LiveInterval.cpp.
References llvm::VNInfo::def.
createValueCopy()
VNInfo* llvm::LiveRange::createValueCopy (const VNInfo * orig, VNInfo::Allocator & VNInfoAllocator) inline
Create a copy of the given value.
The new value will be identical except for the Value number.
Definition at line 340 of file LiveInterval.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::size(), llvm::NVPTX::PTXLdStInstCode::V2, and llvm::VNInfo::VNInfo().
dump()
LLVM_DUMP_METHOD void LiveRange::dump () const
Definition at line 1055 of file LiveInterval.cpp.
References llvm::dbgs().
empty()
bool llvm::LiveRange::empty () const inline
Definition at line 373 of file LiveInterval.h.
References llvm::SmallVectorBase::empty().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::LiveRangeCalc::calculate(), llvm::LiveRegMatrix::checkInterference(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::LiveRegMatrix::checkRegUnitInterference(), llvm::SplitAnalysis::clear(), computeWeight(), llvm::SplitAnalysis::countLiveBlocks(), covers(), llvm::createGreedyRegisterAllocator(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::LiveIntervalUnion::extract(), getStartOrEndSlot(), isACalleeSavedRegister(), isDefInSubRange(), llvm::SplitAnalysis::isOriginalEndpoint(), overlaps(), llvm::LiveIntervals::print(), llvm::LiveInterval::removeEmptySubRanges(), llvm::LiveIntervalUnion::unify(), and llvm::LiveDebugVariables::~LiveDebugVariables().
end() [1/2]
iterator llvm::LiveRange::end () inline
Definition at line 215 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::LiveRangeUpdater::add(), llvm::LiveIntervals::addKillFlags(), allPhiOperandsUndefined(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::SplitAnalysis::clear(), llvm::SplitAnalysis::countLiveBlocks(), llvm::createCopyConstrainDAGMutation(), llvm::LiveIntervalUnion::extract(), getNumAllocatableRegsForConstraints(), getStartOrEndSlot(), llvm::CoalescerPair::isCoalescable(), isDefInSubRange(), llvm::SplitAnalysis::isOriginalEndpoint(), isPlainlyKilled(), overlaps(), overlapsFrom(), llvm::LiveRangeUpdater::print(), regOverlapsSet(), llvm::LiveIntervals::shrinkToUses(), llvm::LiveIntervalUnion::unify(), llvm::LiveIntervals::HMEditor::updateAllRanges(), and llvm::LiveDebugVariables::~LiveDebugVariables().
end() [2/2]
const_iterator llvm::LiveRange::end () const inline
Definition at line 218 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
endIndex()
SlotIndex llvm::LiveRange::endIndex () const inline
endNumber - return the maximum point of the range of the whole, exclusive.
Definition at line 383 of file LiveInterval.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), and llvm::empty().
Referenced by allPhiOperandsUndefined(), llvm::createCopyConstrainDAGMutation(), llvm::createGreedyRegisterAllocator(), and llvm::SystemZRegisterInfo::shouldCoalesce().
expiredAt()
bool llvm::LiveRange::expiredAt (SlotIndex index) const inline
Definition at line 388 of file LiveInterval.h.
Referenced by regJustKilledBefore().
extendInBlock() [1/2]
std::pair< VNInfo *, bool > LiveRange::extendInBlock (ArrayRef< SlotIndex > Undefs, SlotIndex StartIdx, SlotIndex Kill)
Attempt to extend a value defined after StartIdx to include Use.
Both StartIdx and Use should be in the same basic block. In case of subranges, an extension could be prevented by an explicit "undef" caused by a <def,read-undef> on a non-overlapping lane. The list of location of such "undefs" should be provided in Undefs. The return value is a pair: the first element is VNInfo of the value that was extended (possibly nullptr), the second is a boolean value indicating whether an "undef" was encountered. If this range is live before Use in the basic block that starts at StartIdx, and there is no intervening "undef", extend it to be live up to Use, and return the pair {value, false}. If there is no segment before Use and there is no "undef" between StartIdx and Use, return {nullptr, false}. If there is an "undef" before Use, return {nullptr, true}.
Definition at line 564 of file LiveInterval.cpp.
Referenced by createSegmentsForValues(), and llvm::LiveRangeCalc::extend().
extendInBlock() [2/2]
VNInfo * LiveRange::extendInBlock (SlotIndex StartIdx, SlotIndex Kill)
Simplified version of the above "extendInBlock", which assumes that no register lanes are undefined by <def,read-undef> operands.
If this range is live before Use in the basic block that starts at StartIdx, extend it to be live up to Use, and return the value. If there is no segment before Use, return nullptr.
Definition at line 573 of file LiveInterval.cpp.
find() [1/2]
LiveRange::iterator LiveRange::find (SlotIndex Pos)
find - Return an iterator pointing to the first segment that ends after Pos, or end().
This is the same as advanceTo(begin(), Pos), but faster when searching large ranges.
If Pos is contained in a Segment, that segment is returned. If Pos is in a hole, the following Segment is returned. If Pos is beyond endIndex, end() is returned.
Definition at line 350 of file LiveInterval.cpp.
References llvm::sys::path::begin(), llvm::empty(), llvm::sys::path::end(), I, and llvm::size().
Referenced by llvm::LiveRangeUpdater::add(), llvm::LiveIntervals::addKillFlags(), llvm::createCopyConstrainDAGMutation(), getNumAllocatableRegsForConstraints(), getStartOrEndSlot(), llvm::SplitAnalysis::isOriginalEndpoint(), isPlainlyKilled(), overlaps(), regOverlapsSet(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
find() [2/2]
const_iterator llvm::LiveRange::find (SlotIndex Pos) const inline
Definition at line 287 of file LiveInterval.h.
References llvm::find().
findIndexesLiveAt()
template<typename Range , typename OutputIt > bool llvm::LiveRange::findIndexesLiveAt (Range && R, OutputIt O) const inline
Stores indexes from the input index sequence R at which this LiveRange is live to the output O iterator.
R is a range of ascending sorted random access iterators to the input indexes. Indexes stored at O are ascending sorted so it can be used directly in the subsequent search (for example for subranges). Returns true if found at least one index.
Definition at line 619 of file LiveInterval.h.
References llvm::sys::path::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::copy(), llvm::dump(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::lower_bound(), print(), llvm::upper_bound(), and llvm::verify().
FindSegmentContaining() [1/2]
iterator llvm::LiveRange::FindSegmentContaining (SlotIndex Idx) inline
Return an iterator to the segment that contains the specified index, or end() if there is none.
Definition at line 427 of file LiveInterval.h.
References llvm::sys::path::end(), llvm::find(), and I.
Referenced by llvm::CoalescerPair::isCoalescable(), moveAndTeeForMultiUse(), and llvm::LiveIntervals::shrinkToUses().
FindSegmentContaining() [2/2]
const_iterator llvm::LiveRange::FindSegmentContaining (SlotIndex Idx) const inline
Definition at line 432 of file LiveInterval.h.
References llvm::sys::path::end(), llvm::find(), and I.
flushSegmentSet()
void LiveRange::flushSegmentSet ()
Flush segment set into the regular segment vector.
The method is to be called after the live range has been created, if use of the segment set was activated in the constructor of the live range.
Definition at line 804 of file LiveInterval.cpp.
References assert(), and llvm::verify().
Referenced by llvm::LiveIntervals::print().
getNextValue()
VNInfo* llvm::LiveRange::getNextValue (SlotIndex def, VNInfo::Allocator & VNInfoAllocator) inline
getNextValue - Create a new value number and return it.
MIIdx specifies the instruction that defines the value number.
Definition at line 322 of file LiveInterval.h.
References createDeadDef(), llvm::tgtok::Def, llvm::VNInfo::def, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::size(), and llvm::VNInfo::VNInfo().
Referenced by llvm::LiveIntervals::addSegmentToEndOfBlock(), allPhiOperandsUndefined(), and llvm::LiveRangeEdit::eraseVirtReg().
getNumValNums()
unsigned llvm::LiveRange::getNumValNums () const inline
Definition at line 304 of file LiveInterval.h.
References llvm::SmallVectorBase::size().
Referenced by llvm::ConnectedVNInfoEqClasses::Classify(), and isFullCopyOf().
getSegmentContaining() [1/2]
const Segment* llvm::LiveRange::getSegmentContaining (SlotIndex Idx) const inline
Return the segment that contains the specified index, or null if there is none.
Definition at line 399 of file LiveInterval.h.
References llvm::sys::path::end(), and I.
Referenced by llvm::createSIWholeQuadModePass(), llvm::RegPressureTracker::getLastUsedLanes(), llvm::RegPressureTracker::getLiveThroughAt(), removeDeadSegment(), and llvm::LiveIntervals::shrinkToUses().
getSegmentContaining() [2/2]
Segment* llvm::LiveRange::getSegmentContaining (SlotIndex Idx) inline
Return the live segment that contains the specified index, or null if there is none.
Definition at line 406 of file LiveInterval.h.
References llvm::sys::path::end(), and I.
getValNumInfo() [1/2]
VNInfo* llvm::LiveRange::getValNumInfo (unsigned ValNo) inline
getValNumInfo - Returns pointer to the specified val#.
Definition at line 308 of file LiveInterval.h.
Referenced by getStartOrEndSlot().
getValNumInfo() [2/2]
const VNInfo* llvm::LiveRange::getValNumInfo (unsigned ValNo) const inline
Definition at line 311 of file LiveInterval.h.
getVNInfoAt()
VNInfo* llvm::LiveRange::getVNInfoAt (SlotIndex Idx) const inline
getVNInfoAt - Return the VNInfo that is live at Idx, or NULL.
Definition at line 412 of file LiveInterval.h.
References llvm::sys::path::end(), and I.
Referenced by addSegmentsWithValNo(), allPhiOperandsUndefined(), llvm::LiveRangeEdit::anyRematerializable(), llvm::LiveRangeEdit::checkRematerializable(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::SplitEditor::dump(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvBefore(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::SIRegisterInfo::findReachingDef(), hasOneUse(), isFullCopyOf(), isFullUndefDef(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvBefore(), moveAndTeeForMultiUse(), llvm::LiveIntervals::removePhysRegDefAt(), llvm::LiveIntervals::removeVRegDefAt(), and replaceDominatedUses().
getVNInfoBefore()
VNInfo* llvm::LiveRange::getVNInfoBefore (SlotIndex Idx) const inline
getVNInfoBefore - Return the VNInfo that is live up to but not necessarilly including Idx, or NULL.
Use this to find the reaching def used by an instruction at this SlotIndex position.
Definition at line 420 of file LiveInterval.h.
References llvm::sys::path::end(), llvm::SlotIndex::getPrevSlot(), and I.
Referenced by addSegmentsWithValNo(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::createCopyConstrainDAGMutation(), getVRegDef(), llvm::LiveIntervals::hasPHIKill(), llvm::InsertPointAnalysis::InsertPointAnalysis(), isFullCopyOf(), oneUseDominatesOtherUses(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
hasAtLeastOneValue()
bool llvm::LiveRange::hasAtLeastOneValue () const inline
Definition at line 300 of file LiveInterval.h.
References llvm::SmallVectorBase::empty().
Referenced by isPlainlyKilled(), and llvm::LiveIntervals::repairIntervalsInRange().
isLiveAtIndexes()
bool LiveRange::isLiveAtIndexes (ArrayRef< SlotIndex > Slots) const
Definition at line 814 of file LiveInterval.cpp.
References llvm::ArrayRef< T >::begin(), llvm::sys::path::end(), llvm::ArrayRef< T >::end(), and llvm::find().
Referenced by getStartOrEndSlot(), and llvm::VirtRegAuxInfo::weightCalcHelper().
isLocal()
bool llvm::LiveRange::isLocal (SlotIndex Start, SlotIndex End) const inline
True iff this segment is a single segment that lies between the specified boundaries, exclusively.
Vregs live across a backedge are not considered local. The boundaries are expected to lie within an extended basic block, so vregs that are not live out should contain no holes.
Definition at line 509 of file LiveInterval.h.
References llvm::SlotIndex::getBaseIndex(), and llvm::SlotIndex::getBoundaryIndex().
Referenced by llvm::createCopyConstrainDAGMutation().
isUndefIn()
bool llvm::LiveRange::isUndefIn (ArrayRef< SlotIndex > Undefs, SlotIndex Begin, SlotIndex End) const inline
Returns true if there is an explicit "undef" between Begin End.
Definition at line 598 of file LiveInterval.h.
References llvm::any_of(), llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
isZeroLength()
bool llvm::LiveRange::isZeroLength (SlotIndexes * Indexes) const inline
Returns true if the live range is zero length, i.e.
no live segments span instructions. It doesn't pay to spill such a range.
Definition at line 577 of file LiveInterval.h.
References llvm::LiveRange::Segment::end, llvm::SlotIndex::getBaseIndex(), llvm::SlotIndexes::getNextNonNullIndex(), and llvm::LiveRange::Segment::start.
Referenced by llvm::VirtRegAuxInfo::weightCalcHelper().
join()
void LiveRange::join (LiveRange & Other, const int * ValNoAssignments, const int * RHSValNoAssignments, SmallVectorImpl< VNInfo *> & NewVNInfo)
join - Join two live ranges (this, and other) together.
This applies mappings to the value numbers in the LHS/RHS ranges as specified. If the ranges are not joinable, this aborts.
Definition at line 641 of file LiveInterval.cpp.
References llvm::LiveRangeUpdater::add(), assert(), llvm::sys::path::begin(), E, llvm::empty(), llvm::sys::path::end(), I, llvm::VNInfo::id, llvm::SmallVectorTemplateBase< T, bool >::push_back(), segments, llvm::SmallVectorBase::size(), llvm::LiveRange::Segment::valno, and llvm::verify().
Referenced by isDefInSubRange().
liveAt()
bool llvm::LiveRange::liveAt (SlotIndex index) const inline
Definition at line 392 of file LiveInterval.h.
References llvm::sys::path::end(), and llvm::find().
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), allPhiOperandsUndefined(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), getLiveLanesAt(), llvm::RegPressureTracker::getLiveLanesAt(), llvm::LiveIntervals::isLiveInToMBB(), llvm::LiveIntervals::isLiveOutOfMBB(), rematerializeCheapDef(), and replaceDominatedUses().
MergeSegmentsInAsValue()
void LiveRange::MergeSegmentsInAsValue (const LiveRange & RHS, VNInfo * LHSValNo)
Merge all of the live segments of a specific val# in RHS into this live range as the specified value number.
Merge all of the segments in RHS into this live range as the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, it will replace the value numbers of the overlaped live segments with the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, but only if the overlapping segments have the specified value number.
Definition at line 724 of file LiveInterval.cpp.
References llvm::LiveRangeUpdater::add(), llvm::LiveRange::Segment::end, segments, and llvm::LiveRange::Segment::start.
Referenced by getStartOrEndSlot().
MergeValueInAsValue()
void LiveRange::MergeValueInAsValue (const LiveRange & RHS, const VNInfo * RHSValNo, VNInfo * LHSValNo)
MergeValueInAsValue - Merge all of the segments of a specific val# in RHS into this live range as the specified value number.
MergeValueInAsValue - Merge all of the live segments of a specific val# in RHS into this live range as the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, but only if the overlapping segments have the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, it will replace the value numbers of the overlaped segments with the specified value number.
Definition at line 736 of file LiveInterval.cpp.
References llvm::LiveRangeUpdater::add(), llvm::LiveRange::Segment::end, segments, llvm::LiveRange::Segment::start, and llvm::LiveRange::Segment::valno.
MergeValueNumberInto()
VNInfo * LiveRange::MergeValueNumberInto (VNInfo * V1, VNInfo * V2)
MergeValueNumberInto - This method is called when two value numbers are found to be equivalent.
MergeValueNumberInto - This method is called when two value nubmers are found to be equivalent.
This eliminates V1, replacing all segments with the V1 value number with the V2 value number. This can cause merging of V1/V2 values numbers and compaction of the value space.
Definition at line 749 of file LiveInterval.cpp.
References assert(), llvm::sys::path::begin(), llvm::VNInfo::copyFrom(), llvm::sys::path::end(), llvm::LiveRange::Segment::end, llvm::VNInfo::id, std::swap(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by addSegmentsWithValNo(), and llvm::CoalescerPair::isCoalescable().
operator<()
bool llvm::LiveRange::operator< (const LiveRange & other) const inline
Definition at line 590 of file LiveInterval.h.
References beginIndex().
overlaps() [1/3]
bool llvm::LiveRange::overlaps (const LiveRange & other) const inline
overlaps - Return true if the intersection of the two live ranges is not empty.
Definition at line 439 of file LiveInterval.h.
References begin(), llvm::HexagonISD::CP, empty(), and llvm::Other.
Referenced by addSegmentsWithValNo(), llvm::LiveRegMatrix::checkRegUnitInterference(), isACalleeSavedRegister(), isTerminalReg(), and false::IntervalSorter::operator()().
overlaps() [2/3]
bool LiveRange::overlaps (const LiveRange & Other, const CoalescerPair & CP, const SlotIndexes & Indexes) const
overlaps - Return true if the two ranges have overlapping segments that are not coalescable according to CP.
Overlapping segments where one range is defined by a coalescable copy are allowed.
Definition at line 445 of file LiveInterval.cpp.
References assert(), beginIndex(), llvm::empty(), empty(), llvm::sys::path::end(), end(), find(), llvm::find(), llvm::SlotIndexes::getInstructionFromIndex(), llvm::ARM_PROC::IE, llvm::SlotIndex::isBlock(), llvm::CoalescerPair::isCoalescable(), llvm::max(), and std::swap().
overlaps() [3/3]
bool LiveRange::overlaps (SlotIndex Start, SlotIndex End) const
overlaps - Return true if the live range overlaps an interval specified by [Start, End).
Definition at line 488 of file LiveInterval.cpp.
overlapsFrom()
bool LiveRange::overlapsFrom (const LiveRange & Other, const_iterator StartPos) const
overlapsFrom - Return true if the intersection of the two live ranges is not empty.
The specified iterator is a hint that we can begin scanning the Other range starting at I.
Definition at line 404 of file LiveInterval.cpp.
References assert(), llvm::sys::path::begin(), begin(), llvm::empty(), llvm::sys::path::end(), end(), std::swap(), and llvm::upper_bound().
print()
void LiveRange::print (raw_ostream & OS) const
Definition at line 1010 of file LiveInterval.cpp.
References assert(), llvm::VNInfo::def, llvm::numbers::e, llvm::empty(), llvm::VNInfo::isPHIDef(), and llvm::VNInfo::isUnused().
Referenced by llvm::operator<<().
Query()
LiveQueryResult llvm::LiveRange::Query (SlotIndex Idx) const inline
Query Liveness at Idx.
The sub-instruction slot of Idx doesn't matter, only the instruction it refers to is considered.
Definition at line 532 of file LiveInterval.h.
References llvm::VNInfo::def, E, llvm::sys::path::end(), llvm::find(), llvm::SlotIndex::getBaseIndex(), I, llvm::SlotIndex::isEarlierInstr(), and llvm::SlotIndex::isSameInstr().
Referenced by addSegmentsWithValNo(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::createSIWholeQuadModePass(), definesFullReg(), llvm::RegisterOperands::detectDeadDefs(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::LiveRangeEdit::eraseVirtReg(), hasOneUse(), isFullCopyOf(), isRematerializable(), llvm::LiveIntervals::pruneValue(), llvm::LiveIntervals::shrinkToUses(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
removeSegment() [1/3]
void LiveRange::removeSegment (SlotIndex Start, SlotIndex End, bool RemoveDeadValNo = false)
Remove the specified segment from this range.
Note that the segment must be a single Segment in its entirety.
Note that the segment must be in a single Segment in its entirety.
Definition at line 583 of file LiveInterval.cpp.
Referenced by allPhiOperandsUndefined(), moveForSingleUse(), llvm::LiveIntervals::pruneValue(), removeDeadSegment(), and llvm::LiveIntervals::shrinkToUses().
removeSegment() [2/3]
void llvm::LiveRange::removeSegment (Segment S, bool RemoveDeadValNo = false) inline
Definition at line 519 of file LiveInterval.h.
References llvm::LiveRange::Segment::end, and llvm::LiveRange::Segment::start.
removeSegment() [3/3]
iterator llvm::LiveRange::removeSegment (iterator I) inline
Remove segment pointed to by iterator I from this range.
This does not remove dead value numbers.
Definition at line 525 of file LiveInterval.h.
References llvm::SmallVectorImpl< T >::erase().
removeValNo()
void LiveRange::removeValNo (VNInfo * ValNo)
removeValNo - Remove all the segments defined by the specified value#.
Also remove the value# from value# list.
Definition at line 632 of file LiveInterval.cpp.
References llvm::empty(), llvm::sys::path::end(), llvm::remove_if(), and llvm::LiveRange::Segment::valno.
Referenced by allPhiOperandsUndefined(), llvm::LiveIntervals::removePhysRegDefAt(), llvm::LiveIntervals::removeVRegDefAt(), stripValuesNotDefiningMask(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
RenumberValues()
void LiveRange::RenumberValues ()
RenumberValues - Renumber all values in order of appearance and remove unused values.
RenumberValues - Renumber all values in order of appearance and delete the remaining unused values.
Definition at line 531 of file LiveInterval.cpp.
References assert(), llvm::SmallPtrSetImplBase::clear(), llvm::VNInfo::id, llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::VNInfo::isUnused().
Referenced by llvm::LiveRangeEdit::eliminateDeadDefs(), and llvm::SplitEditor::finish().
size()
size_t llvm::LiveRange::size () const inline
Definition at line 296 of file LiveInterval.h.
References llvm::SmallVectorBase::size().
Referenced by llvm::LiveIntervalUnion::Query::collectInterferingVRegs().
verify()
void LiveRange::verify () const
Walk the range and assert if any invariants fail to hold.
Note that this is a no-op when asserts are disabled.
Definition at line 1069 of file LiveInterval.cpp.
References assert(), llvm::sys::path::begin(), E, llvm::sys::path::end(), and I.
Referenced by llvm::LiveRangeUpdater::flush(), isDefInSubRange(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
vni_begin() [1/2]
vni_iterator llvm::LiveRange::vni_begin () inline
Definition at line 223 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by isFullCopyOf(), isRematerializable(), and llvm::LiveIntervals::shrinkToUses().
vni_begin() [2/2]
const_vni_iterator llvm::LiveRange::vni_begin () const inline
Definition at line 226 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
vni_end() [1/2]
vni_iterator llvm::LiveRange::vni_end () inline
Definition at line 224 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by isFullCopyOf(), isRematerializable(), and llvm::LiveIntervals::shrinkToUses().
vni_end() [2/2]
const_vni_iterator llvm::LiveRange::vni_end () const inline
Definition at line 227 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Friends And Related Function Documentation
LiveRangeUpdater
friend class LiveRangeUpdater friend
Definition at line 667 of file LiveInterval.h.
Member Data Documentation
segments
Segments llvm::LiveRange::segments
Definition at line 202 of file LiveInterval.h.
Referenced by llvm::LiveRangeUpdater::add(), addSegmentsWithValNo(), assign(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), covers(), llvm::LiveRangeUpdater::flush(), llvm::CoalescerPair::isCoalescable(), join(), MergeSegmentsInAsValue(), MergeValueInAsValue(), and llvm::LiveIntervals::shrinkToUses().
segmentSet
std::unique_ptr<SegmentSet> llvm::LiveRange::segmentSet
Definition at line 209 of file LiveInterval.h.
Referenced by llvm::LiveRangeUpdater::add(), assign(), and LiveRange().
valnos
VNInfoList llvm::LiveRange::valnos
Definition at line 203 of file LiveInterval.h.
Referenced by addSegmentsWithValNo(), assign(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::SplitAnalysis::clear(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), llvm::LiveIntervals::hasPHIKill(), isDefInSubRange(), llvm::LiveIntervals::shrinkToUses(), and stripValuesNotDefiningMask().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveInterval.h
lib/CodeGen/LiveInterval.cpp