LLVM: llvm::IRBuilder< T, Inserter > Class Template Reference
llvm::IRBuilder< T, Inserter > Class Template Reference
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
#include "llvm/IR/IRBuilder.h"
Public Member Functions
IRBuilder (LLVMContext &C, const T &F, Inserter I=Inserter(), MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (LLVMContext &C, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, const T &F, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (Instruction *IP, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, const T &F, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
const T & getFolder ()
Get the constant folder being used.
template<typename InstTy >
InstTy * Insert (InstTy *I, const Twine &Name="") const
Insert and return the specified instruction.
Constant * Insert (Constant *C, const Twine &="") const
No-op overload to handle constants.
ReturnInst * CreateRetVoid ()
Create a 'ret void' instruction.
ReturnInst * CreateRet (Value *V)
Create a 'ret <val>' instruction.
ReturnInst * CreateAggregateRet (Value *const *retVals, unsigned N)
Create a sequence of N insertvalue instructions, with one Value from the retVals array each, that build a aggregate return value one value at a time, and a ret instruction to return the resulting aggregate value.
BranchInst * CreateBr (BasicBlock *Dest)
Create an unconditional 'br label X' instruction.
BranchInst * CreateCondBr (Value *Cond, BasicBlock *True, BasicBlock *False, MDNode *BranchWeights=nullptr, MDNode *Unpredictable=nullptr)
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
BranchInst * CreateCondBr (Value *Cond, BasicBlock *True, BasicBlock *False, Instruction *MDSrc)
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
SwitchInst * CreateSwitch (Value *V, BasicBlock *Dest, unsigned NumCases=10, MDNode *BranchWeights=nullptr, MDNode *Unpredictable=nullptr)
Create a switch instruction with the specified value, default dest, and with a hint for the number of cases that will be added (for efficient allocation).
IndirectBrInst * CreateIndirectBr (Value *Addr, unsigned NumDests=10)
Create an indirect branch instruction with the specified address operand, with an optional hint for the number of destinations that will be added (for efficient allocation).
InvokeInst * CreateInvoke (FunctionType *Ty, Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
Create an invoke instruction.
InvokeInst * CreateInvoke (FunctionType *Ty, Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> Args=None, const Twine &Name="")
InvokeInst * CreateInvoke (FunctionCallee Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
InvokeInst * CreateInvoke (FunctionCallee Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> Args=None, const Twine &Name="")
InvokeInst * CreateInvoke (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
InvokeInst * CreateInvoke (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> Args=None, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionType *Ty, Value *Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args=None, const Twine &Name="")
Create a callbr instruction.
CallBrInst * CreateCallBr (FunctionType *Ty, Value *Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionCallee Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args=None, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionCallee Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
ResumeInst * CreateResume (Value *Exn)
CleanupReturnInst * CreateCleanupRet (CleanupPadInst *CleanupPad, BasicBlock *UnwindBB=nullptr)
CatchSwitchInst * CreateCatchSwitch (Value *ParentPad, BasicBlock *UnwindBB, unsigned NumHandlers, const Twine &Name="")
CatchPadInst * CreateCatchPad (Value *ParentPad, ArrayRef< Value *> Args, const Twine &Name="")
CleanupPadInst * CreateCleanupPad (Value *ParentPad, ArrayRef< Value *> Args=None, const Twine &Name="")
CatchReturnInst * CreateCatchRet (CatchPadInst *CatchPad, BasicBlock *BB)
UnreachableInst * CreateUnreachable ()
Value * CreateAdd (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSub (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateMul (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateUDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactUDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactSDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateURem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSRem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateShl (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, const APInt &RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, uint64_t RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateLShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAnd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateAnd (ArrayRef< Value *> Ops)
Value * CreateOr (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateOr (ArrayRef< Value *> Ops)
Value * CreateXor (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateFAdd (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFAddFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFSub (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFSubFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFMul (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFMulFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFDiv (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFDivFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFRem (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFRemFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateConstrainedFPBinOp (Intrinsic::ID ID, Value *L, Value *R, Instruction *FMFSource=nullptr, const Twine &Name="", MDNode *FPMathTag=nullptr, Optional< fp::RoundingMode > Rounding=None, Optional< fp::ExceptionBehavior > Except=None)
Value * CreateNeg (Value *V, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWNeg (Value *V, const Twine &Name="")
Value * CreateNUWNeg (Value *V, const Twine &Name="")
Value * CreateFNeg (Value *V, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFNegFMF (Value *V, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateNot (Value *V, const Twine &Name="")
Value * CreateUnOp (Instruction::UnaryOps Opc, Value *V, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateNAryOp (unsigned Opc, ArrayRef< Value *> Ops, const Twine &Name="", MDNode *FPMathTag=nullptr)
Create either a UnaryOperator or BinaryOperator depending on Opc.
AllocaInst * CreateAlloca (Type *Ty, unsigned AddrSpace, Value *ArraySize=nullptr, const Twine &Name="")
AllocaInst * CreateAlloca (Type *Ty, Value *ArraySize=nullptr, const Twine &Name="")
LoadInst * CreateLoad (Type *Ty, Value *Ptr, const char *Name)
Provided to resolve 'CreateLoad(Ty, Ptr, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
LoadInst * CreateLoad (Type *Ty, Value *Ptr, const Twine &Name="")
LoadInst * CreateLoad (Type *Ty, Value *Ptr, bool isVolatile, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, const char *Name)
LoadInst * CreateLoad (Value *Ptr, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, bool isVolatile, const Twine &Name="")
StoreInst * CreateStore (Value *Val, Value *Ptr, bool isVolatile=false)
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, unsigned Align, const char *Name)
Provided to resolve 'CreateAlignedLoad(Ptr, Align, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, MaybeAlign Align, const char *Name)
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, unsigned Align, const Twine &Name="")
FIXME: Remove this function once transition to Align is over.
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, MaybeAlign Align, const Twine &Name="")
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, unsigned Align, bool isVolatile, const Twine &Name="")
FIXME: Remove this function once transition to Align is over.
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, MaybeAlign Align, bool isVolatile, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, const char *Name)
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, bool isVolatile, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, MaybeAlign Align, const char *Name)
LoadInst * CreateAlignedLoad (Value *Ptr, MaybeAlign Align, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, MaybeAlign Align, bool isVolatile, const Twine &Name="")
StoreInst * CreateAlignedStore (Value *Val, Value *Ptr, unsigned Align, bool isVolatile=false)
StoreInst * CreateAlignedStore (Value *Val, Value *Ptr, MaybeAlign Align, bool isVolatile=false)
FenceInst * CreateFence (AtomicOrdering Ordering, SyncScope::ID SSID=SyncScope::System, const Twine &Name="")
AtomicCmpXchgInst * CreateAtomicCmpXchg (Value *Ptr, Value *Cmp, Value *New, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SyncScope::ID SSID=SyncScope::System)
AtomicRMWInst * CreateAtomicRMW (AtomicRMWInst::BinOp Op, Value *Ptr, Value *Val, AtomicOrdering Ordering, SyncScope::ID SSID=SyncScope::System)
Value * CreateGEP (Value *Ptr, ArrayRef< Value *> IdxList, const Twine &Name="")
Value * CreateGEP (Type *Ty, Value *Ptr, ArrayRef< Value *> IdxList, const Twine &Name="")
Value * CreateInBoundsGEP (Value *Ptr, ArrayRef< Value *> IdxList, const Twine &Name="")
Value * CreateInBoundsGEP (Type *Ty, Value *Ptr, ArrayRef< Value *> IdxList, const Twine &Name="")
Value * CreateGEP (Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateGEP (Type *Ty, Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateInBoundsGEP (Type *Ty, Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateConstGEP1_32 (Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstGEP1_32 (Type *Ty, Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_32 (Type *Ty, Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstGEP2_32 (Type *Ty, Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_32 (Type *Ty, Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstGEP1_64 (Type *Ty, Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_64 (Type *Ty, Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstGEP2_64 (Type *Ty, Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_64 (Type *Ty, Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateStructGEP (Type *Ty, Value *Ptr, unsigned Idx, const Twine &Name="")
Value * CreateStructGEP (Value *Ptr, unsigned Idx, const Twine &Name="")
Constant * CreateGlobalStringPtr (StringRef Str, const Twine &Name="", unsigned AddressSpace=0)
Same as CreateGlobalString, but return a pointer with "i8*" type instead of a pointer to array of i8.
Value * CreateTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a ZExt or Trunc from the integer value V to DestTy.
Value * CreateSExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a SExt or Trunc from the integer value V to DestTy.
Value * CreateFPToUI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPToSI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateUIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePtrToInt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntToPtr (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateTruncOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateCast (Instruction::CastOps Op, Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerBitCastOrAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntCast (Value *V, Type *DestTy, bool isSigned, const Twine &Name="")
Value * CreateBitOrPointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPCast (Value *V, Type *DestTy, const Twine &Name="")
CallInst * CreateConstrainedFPCast (Intrinsic::ID ID, Value *V, Type *DestTy, Instruction *FMFSource=nullptr, const Twine &Name="", MDNode *FPMathTag=nullptr, Optional< fp::RoundingMode > Rounding=None, Optional< fp::ExceptionBehavior > Except=None)
Value * CreateIntCast (Value *, Type *, const char *)=delete
Value * CreateICmpEQ (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpNE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOEQ (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOGT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOGE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOLT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOLE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpONE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpORD (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUNO (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUEQ (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUGT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUGE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpULT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpULE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUNE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateICmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpS (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateConstrainedFPCmp (Intrinsic::ID ID, CmpInst::Predicate P, Value *L, Value *R, const Twine &Name="", Optional< fp::ExceptionBehavior > Except=None)
PHINode * CreatePHI (Type *Ty, unsigned NumReservedValues, const Twine &Name="")
CallInst * CreateCall (FunctionType *FTy, Value *Callee, ArrayRef< Value *> Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionType *FTy, Value *Callee, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionCallee Callee, ArrayRef< Value *> Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionCallee Callee, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (Value *Callee, ArrayRef< Value *> Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (Value *Callee, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateConstrainedFPCall (Function *Callee, ArrayRef< Value *> Args, const Twine &Name="", Optional< fp::RoundingMode > Rounding=None, Optional< fp::ExceptionBehavior > Except=None)
Value * CreateSelect (Value *C, Value *True, Value *False, const Twine &Name="", Instruction *MDFrom=nullptr)
VAArgInst * CreateVAArg (Value *List, Type *Ty, const Twine &Name="")
Value * CreateExtractElement (Value *Vec, Value *Idx, const Twine &Name="")
Value * CreateExtractElement (Value *Vec, uint64_t Idx, const Twine &Name="")
Value * CreateInsertElement (Value *Vec, Value *NewElt, Value *Idx, const Twine &Name="")
Value * CreateInsertElement (Value *Vec, Value *NewElt, uint64_t Idx, const Twine &Name="")
Value * CreateShuffleVector (Value *V1, Value *V2, Value *Mask, const Twine &Name="")
Value * CreateShuffleVector (Value *V1, Value *V2, ArrayRef< uint32_t > IntMask, const Twine &Name="")
Value * CreateExtractValue (Value *Agg, ArrayRef< unsigned > Idxs, const Twine &Name="")
Value * CreateInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const Twine &Name="")
LandingPadInst * CreateLandingPad (Type *Ty, unsigned NumClauses, const Twine &Name="")
Value * CreateFreeze (Value *V, const Twine &Name="")
Value * CreateIsNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is null.
Value * CreateIsNotNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is not null.
Value * CreatePtrDiff (Value *LHS, Value *RHS, const Twine &Name="")
Return the i64 difference between two pointer values, dividing out the size of the pointed-to objects.
Value * CreateLaunderInvariantGroup (Value *Ptr)
Create a launder.invariant.group intrinsic call.
Value * CreateStripInvariantGroup (Value *Ptr)
Create a strip.invariant.group intrinsic call.
Value * CreateVectorSplat (unsigned NumElts, Value *V, const Twine &Name="")
Return a vector value that contains.
Value * CreateExtractInteger (const DataLayout &DL, Value *From, IntegerType *ExtractedTy, uint64_t Offset, const Twine &Name)
Return a value that has been extracted from a larger integer type.
Value * CreatePreserveArrayAccessIndex (Type *ElTy, Value *Base, unsigned Dimension, unsigned LastIndex, MDNode *DbgInfo)
Value * CreatePreserveUnionAccessIndex (Value *Base, unsigned FieldIndex, MDNode *DbgInfo)
Value * CreatePreserveStructAccessIndex (Type *ElTy, Value *Base, unsigned Index, unsigned FieldIndex, MDNode *DbgInfo)
CallInst * CreateAlignmentAssumption (const DataLayout &DL, Value *PtrValue, unsigned Alignment, Value *OffsetValue=nullptr, Value **TheCheck=nullptr)
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
CallInst * CreateAlignmentAssumption (const DataLayout &DL, Value *PtrValue, Value *Alignment, Value *OffsetValue=nullptr, Value **TheCheck=nullptr)
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
Public Member Functions inherited from llvm::IRBuilderBase
IRBuilderBase (LLVMContext &context, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetCurrentDebugLocation (DebugLoc L)
Set location information used by debugging information.
const DebugLoc & getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
void clearFastMathFlags ()
Clear the fast-math flags.
void setDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void setFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
void setIsFPConstrained (bool IsCon)
Enable/Disable use of constrained floating point math.
bool getIsFPConstrained ()
Query for the use of constrained floating point math.
void setDefaultConstrainedExcept (fp::ExceptionBehavior NewExcept)
Set the exception handling to be used with constrained floating point.
void setDefaultConstrainedRounding (fp::RoundingMode NewRounding)
Set the rounding mode handling to be used with constrained floating point.
fp::ExceptionBehavior getDefaultConstrainedExcept ()
Get the exception handling used with constrained floating point.
fp::RoundingMode getDefaultConstrainedRounding ()
Get the rounding mode handling used with constrained floating point.
void setConstrainedFPFunctionAttr ()
void setConstrainedFPCallAttr (CallInst *I)
GlobalVariable * CreateGlobalString (StringRef Str, const Twine &Name="", unsigned AddressSpace=0)
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getInt128Ty ()
Fetch the type representing a 128-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout &DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, MaybeAlign Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, MaybeAlign Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemSet(Value *Ptr, Value *Val, uint64_t Size, unsigned Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead of this one")
Create and insert an element unordered-atomic memset of the region of memory starting at the given pointer to the given value.
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, uint64_t Size, Align Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemSet(Value *Ptr, Value *Val, Value *Size, unsigned Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead of this one")
FIXME: Remove this function once transition to Align is over.
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, Value *Size, Align Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemCpy(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign instead")
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemCpy (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemCpy(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign instead")
FIXME: Remove this function once transition to Align is over.
CallInst * CreateMemCpy (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memcpy between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemMove(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign")
Create and insert a memmove between the specified pointers.
CallInst * CreateMemMove (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMemMove(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes MaybeAlign")
FIXME: Remove this function once transition to Align is over.
CallInst * CreateMemMove (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memmove between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateFAddReduce (Value *Acc, Value *Src)
Create a vector fadd reduction intrinsic of the source vector.
CallInst * CreateFMulReduce (Value *Acc, Value *Src)
Create a vector fmul reduction intrinsic of the source vector.
CallInst * CreateAddReduce (Value *Src)
Create a vector int add reduction intrinsic of the source vector.
CallInst * CreateMulReduce (Value *Src)
Create a vector int mul reduction intrinsic of the source vector.
CallInst * CreateAndReduce (Value *Src)
Create a vector int AND reduction intrinsic of the source vector.
CallInst * CreateOrReduce (Value *Src)
Create a vector int OR reduction intrinsic of the source vector.
CallInst * CreateXorReduce (Value *Src)
Create a vector int XOR reduction intrinsic of the source vector.
CallInst * CreateIntMaxReduce (Value *Src, bool IsSigned=false)
Create a vector integer max reduction intrinsic of the source vector.
CallInst * CreateIntMinReduce (Value *Src, bool IsSigned=false)
Create a vector integer min reduction intrinsic of the source vector.
CallInst * CreateFPMaxReduce (Value *Src, bool NoNaN=false)
Create a vector float max reduction intrinsic of the source vector.
CallInst * CreateFPMinReduce (Value *Src, bool NoNaN=false)
Create a vector float min reduction intrinsic of the source vector.
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateInvariantStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a call to invariant.start intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, unsigned Align, Value *Mask, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, unsigned Align, Value *Mask)
Create a call to Masked Store intrinsic.
CallInst * CreateMaskedGather (Value *Ptrs, unsigned Align, Value *Mask=nullptr, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Gather intrinsic.
CallInst * CreateMaskedScatter (Value *Val, Value *Ptrs, unsigned Align, Value *Mask=nullptr)
Create a call to Masked Scatter intrinsic.
CallInst * CreateAssumption (Value *Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Value *> CallArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< Use > CallArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Conveninence function for the common case when CallArgs are filled in using makeArrayRef(CS.arg_begin(), CS.arg_end()); Use needs to be .get()'ed to get the Value pointer.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value *> InvokeArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< Use > InvokeArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value *> DeoptArgs, ArrayRef< Value *> GCArgs, const Twine &Name="")
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
CallInst * CreateUnaryIntrinsic (Intrinsic::ID ID, Value *V, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 1 operand which is mangled on its type.
CallInst * CreateBinaryIntrinsic (Intrinsic::ID ID, Value *LHS, Value *RHS, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 2 operands which is mangled on the first type.
CallInst * CreateIntrinsic (Intrinsic::ID ID, ArrayRef< Type *> Types, ArrayRef< Value *> Args, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with args, mangled using Types.
CallInst * CreateMinNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minnum intrinsic.
CallInst * CreateMaxNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maxnum intrinsic.
CallInst * CreateMinimum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minimum intrinsic.
CallInst * CreateMaximum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maximum intrinsic.
Additional Inherited Members
Protected Attributes inherited from llvm::IRBuilderBase
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
MDNode * DefaultFPMathTag
FastMathFlags FMF
bool IsFPConstrained
fp::ExceptionBehavior DefaultConstrainedExcept
fp::RoundingMode DefaultConstrainedRounding
ArrayRef< OperandBundleDef > DefaultOperandBundles
Detailed Description
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter>
class llvm::IRBuilder< T, Inserter >
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
Note that the builder does not expose the full generality of LLVM instructions. For access to extra instruction properties, use the mutators (e.g. setVolatile) on the instructions after they have been created. Convenience state exists to specify fast-math flags and fp-math tags.
The first template argument specifies a class to use for creating constants. This defaults to creating minimally folded constants. The second template argument allows clients to specify custom insertion hooks that are called on every newly created insertion.
Definition at line 866 of file IRBuilder.h.
Constructor & Destructor Documentation
IRBuilder() [1/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (LLVMContext & C, const T & F, Inserter I = Inserter(), MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 870 of file IRBuilder.h.
IRBuilder() [2/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (LLVMContext & C, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 876 of file IRBuilder.h.
IRBuilder() [3/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, const T & F, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 880 of file IRBuilder.h.
IRBuilder() [4/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 886 of file IRBuilder.h.
IRBuilder() [5/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (Instruction * IP, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 892 of file IRBuilder.h.
IRBuilder() [6/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, const T & F, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 898 of file IRBuilder.h.
IRBuilder() [7/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 905 of file IRBuilder.h.
Member Function Documentation
CreateAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAdd (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1211 of file IRBuilder.h.
Referenced by llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), createFFSIntrinsic(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::InnerLoopVectorizer::emitTransformedIndex(), evaluateGEPOffsetExpression(), foldAndOrOfEqualityCmpsWithConstants(), foldICmpWithTruncSignExtendedVal(), foldUDivShl(), GetCtorAndDtorPriority(), getMulHu(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), getOrInsertValueProfilingCall(), llvm::InnerLoopVectorizer::getStepVector(), GlobalWasGeneratedByCompiler(), insertSinCosCall(), instrumentMaskedLoadOrStore(), isCallPromotable(), IsNonLocalValue(), isReportingError(), LowerAtomicRMWInst(), LowerCTPOP(), performAtomicOp(), RetagMask(), shouldKeepInEntry(), TurnSwitchRangeIntoICmp(), TypeSizeToSizeIndex(), unifyBitWidth(), llvm::UnrollRuntimeLoopRemainder(), llvm::ObjectSizeOffsetEvaluator::visitGEPOperator(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
CreateAddrSpaceCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAddrSpaceCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2106 of file IRBuilder.h.
Referenced by GetRMWLibcall(), INITIALIZE_PASS(), and simplifyInvariantGroupIntrinsic().
CreateAggregateRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ReturnInst* llvm::IRBuilder< T, Inserter >::CreateAggregateRet (Value *const * retVals, unsigned N) inline
Create a sequence of N insertvalue instructions, with one Value from the retVals array each, that build a aggregate return value one value at a time, and a ret instruction to return the resulting aggregate value.
This is a convenience function for code that uses aggregate return values as a vehicle for having multiple return values.
Definition at line 963 of file IRBuilder.h.
CreateAlignedLoad() [1/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, unsigned Align, const char * Name) inline
Provided to resolve 'CreateAlignedLoad(Ptr, Align, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
FIXME: Remove this function once transition to Align is over. Use the version that takes MaybeAlign instead of this one.
Definition at line 1707 of file IRBuilder.h.
Referenced by GetRMWLibcall(), getScalarIntrinsicDeclaration(), INITIALIZE_PASS(), lowerLoadRelative(), simplifyNeonVld1(), TypeSizeToSizeIndex(), unpackLoadToAggregate(), UpgradeMaskedLoad(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateAlignedLoad() [2/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, MaybeAlign Align, const char * Name) inline
Definition at line 1711 of file IRBuilder.h.
CreateAlignedLoad() [3/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, unsigned Align, const Twine & Name = "") inline
FIXME: Remove this function once transition to Align is over.
Use the version that takes MaybeAlign instead of this one.
Definition at line 1719 of file IRBuilder.h.
CreateAlignedLoad() [4/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, MaybeAlign Align, const Twine & Name = "") inline
Definition at line 1723 of file IRBuilder.h.
CreateAlignedLoad() [5/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, unsigned Align, bool isVolatile, const Twine & Name = "") inline
FIXME: Remove this function once transition to Align is over.
Use the version that takes MaybeAlign instead of this one.
Definition at line 1731 of file IRBuilder.h.
CreateAlignedLoad() [6/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, MaybeAlign Align, bool isVolatile, const Twine & Name = "") inline
Definition at line 1735 of file IRBuilder.h.
CreateAlignedLoad() [7/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, const char * Name) inline
Definition at line 1743 of file IRBuilder.h.
CreateAlignedLoad() [8/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, const Twine & Name = "") inline
Definition at line 1748 of file IRBuilder.h.
CreateAlignedLoad() [9/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, bool isVolatile, const Twine & Name = "") inline
Definition at line 1754 of file IRBuilder.h.
CreateAlignedLoad() [10/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, MaybeAlign Align, const char * Name) inline
Definition at line 1760 of file IRBuilder.h.
CreateAlignedLoad() [11/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, MaybeAlign Align, const Twine & Name = "") inline
Definition at line 1765 of file IRBuilder.h.
CreateAlignedLoad() [12/12]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, MaybeAlign Align, bool isVolatile, const Twine & Name = "") inline
Definition at line 1771 of file IRBuilder.h.
CreateAlignedStore() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> StoreInst* llvm::IRBuilder< T, Inserter >::CreateAlignedStore (Value * Val, Value * Ptr, unsigned Align, bool isVolatile = false) inline
Definition at line 1777 of file IRBuilder.h.
Referenced by combineStoreToNewValue(), GetRMWLibcall(), getScalarIntrinsicDeclaration(), INITIALIZE_PASS(), TypeSizeToSizeIndex(), unpackStoreToAggregate(), UpgradeMaskedStore(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateAlignedStore() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> StoreInst* llvm::IRBuilder< T, Inserter >::CreateAlignedStore (Value * Val, Value * Ptr, MaybeAlign Align, bool isVolatile = false) inline
Definition at line 1783 of file IRBuilder.h.
CreateAlignmentAssumption() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption (const DataLayout & DL, Value * PtrValue, unsigned Alignment, Value * OffsetValue = nullptr, Value ** TheCheck = nullptr) inline
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
An optional offset can be provided, and if it is provided, the offset must be subtracted from the provided pointer to get the pointer with the specified alignment.
It may be sometimes useful to do some other logic based on this alignment check, thus it can be stored into 'TheCheck'.
Definition at line 2834 of file IRBuilder.h.
CreateAlignmentAssumption() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption (const DataLayout & DL, Value * PtrValue, Value * Alignment, Value * OffsetValue = nullptr, Value ** TheCheck = nullptr) inline
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
An optional offset can be provided, and if it is provided, the offset must be subtracted from the provided pointer to get the pointer with the specified alignment.
It may be sometimes useful to do some other logic based on this alignment check, thus it can be stored into 'TheCheck'.
This overload handles the condition where the Alignment is dependent on an existing value rather than a static value.
Definition at line 2861 of file IRBuilder.h.
CreateAlloca() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AllocaInst* llvm::IRBuilder< T, Inserter >::CreateAlloca (Type * Ty, unsigned AddrSpace, Value * ArraySize = nullptr, const Twine & Name = "") inline
Definition at line 1656 of file IRBuilder.h.
Referenced by eliminateSwiftErrorArgument(), handleNoSuspendCoroutine(), INITIALIZE_PASS(), lowerLocalAllocas(), replaceSwiftErrorOps(), simplifyAllocaArraySize(), and StackMallocSizeClass().
CreateAlloca() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AllocaInst* llvm::IRBuilder< T, Inserter >::CreateAlloca (Type * Ty, Value * ArraySize = nullptr, const Twine & Name = "") inline
Definition at line 1661 of file IRBuilder.h.
CreateAnd() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAnd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1361 of file IRBuilder.h.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), annotateNonNullAndDereferenceable(), ApplyX86MaskOn1BitsVec(), canonicalizeSaturatedAdd(), checkForNegativeOperand(), createMaskedBitTest(), createMaskInstrs(), foldAnyOrAllBitsSet(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), generateLoopLatchCheck(), getMulHu(), getSignature(), hasZeroSignBit(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), llvm::log2(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::makeGuardControlFlowExplicit(), normalizePredicate(), performAtomicOp(), performMaskedAtomicOp(), processUMulZExtIdiom(), RetagMask(), llvm::setWidenableBranchCond(), TypeSizeToSizeIndex(), llvm::UnrollRuntimeLoopRemainder(), upgradeMaskedMove(), upgradePMULDQ(), visitMaskedMerge(), and llvm::widenWidenableBranch().
CreateAnd() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAnd (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 1371 of file IRBuilder.h.
CreateAnd() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAnd (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 1375 of file IRBuilder.h.
CreateAnd() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAnd (ArrayRef< Value *> Ops) inline
Definition at line 1379 of file IRBuilder.h.
CreateAShr() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAShr (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1341 of file IRBuilder.h.
Referenced by foldSelectICmpLshrAshr(), generateSignedDivisionCode(), generateSignedRemainderCode(), getMulHu(), RetagMask(), simplifyX86immShift(), simplifyX86varShift(), and upgradePMULDQ().
CreateAShr() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAShr (Value * LHS, const APInt & RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1351 of file IRBuilder.h.
CreateAShr() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateAShr (Value * LHS, uint64_t RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1356 of file IRBuilder.h.
CreateAtomicCmpXchg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AtomicCmpXchgInst* llvm::IRBuilder< T, Inserter >::CreateAtomicCmpXchg (Value * Ptr, Value * Cmp, Value * New, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SyncScope::ID SSID = SyncScope::System) inline
Definition at line 1794 of file IRBuilder.h.
Referenced by atomicSizeSupported(), createCmpXchgInstFun(), GetRMWLibcall(), and performMaskedAtomicOp().
CreateAtomicRMW()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AtomicRMWInst* llvm::IRBuilder< T, Inserter >::CreateAtomicRMW (AtomicRMWInst::BinOp Op, Value * Ptr, Value * Val, AtomicOrdering Ordering, SyncScope::ID SSID = SyncScope::System) inline
Definition at line 1802 of file IRBuilder.h.
Referenced by atomicSizeSupported(), getOrInsertValueProfilingCall(), and performMaskedAtomicOp().
CreateBinOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 1551 of file IRBuilder.h.
Referenced by buildNonAtomicBinOp(), llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), createRdxShuffleMask(), createReplacementInstr(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::InnerLoopVectorizer::fixReduction(), foldLogicCastConstant(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), foldShiftOfShiftedLogic(), getMulHu(), llvm::getOrderedReduction(), getReducedType(), llvm::getShuffleReduction(), llvm::InnerLoopVectorizer::getStepVector(), hasZeroSignBit(), INITIALIZE_PASS(), mapBinOpcode(), matchDeMorgansLaws(), llvm::VPRecipeBase::moveAfter(), narrowUDivURem(), processOverflowIntrinsic(), promotedOpIsNUW(), SimplifyBSwap(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), and llvm::InnerLoopVectorizer::vectorizeInterleaveGroup().
CreateBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2101 of file IRBuilder.h.
Referenced by AddCalls(), llvm::LoopAccessInfo::addRuntimeChecks(), annotateNonNullAndDereferenceable(), ApplyX86MaskOn1BitsVec(), atomicSizeSupported(), canonicalizeBitCastExtElt(), llvm::castToCStr(), combineStoreToNewValue(), createCast(), createCmpXchgInstFun(), llvm::createMemCpyLoopUnknownSize(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::coro::Shape::emitDealloc(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), EmitX86ScalarSelect(), foldBitCastBitwiseLogic(), foldBitcastExtElt(), foldICmpBitCast(), foldVecTruncToExtElt(), getAllocaSizeInBytes(), getMulHu(), GetRMWLibcall(), getScalarIntrinsicDeclaration(), getSuccState(), getX86MaskVec(), handleNoSuspendCoroutine(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::log2(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerLoadRelative(), lowerSubFn(), needsRuntimeRegistrationOfSectionRange(), optimizeMemCmpConstantSize(), optimizeVectorResizeWithIntegerBitCasts(), simplifyInvariantGroupIntrinsic(), simplifyNeonVld1(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86movmsk(), splitRetconCoroutine(), TypeSizeToSizeIndex(), unifyBitWidth(), UpgradeMaskedLoad(), UpgradeMaskedStore(), upgradePMULDQ(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), UpgradeX86VPERMT2Intrinsics(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateBitOrPointerCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2179 of file IRBuilder.h.
Referenced by llvm::InnerLoopVectorizer::createBitOrPointerCast(), createOrdering(), GetRMWLibcall(), and isGEPFoldable().
CreateBr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> BranchInst* llvm::IRBuilder< T, Inserter >::CreateBr (BasicBlock * Dest) inline
Create an unconditional 'br label X' instruction.
Definition at line 971 of file IRBuilder.h.
Referenced by llvm::orc::IRSpeculationLayer::emit(), FoldTwoEntryPHINode(), getSignature(), INITIALIZE_PASS(), isUnconditionalBranch(), performMaskedAtomicOp(), RemoveSwitchAfterSelectConversion(), removeUndefIntroducingPredecessor(), setBranchWeights(), shouldKeepInEntry(), SimplifyIndirectBrOnSelect(), and SwitchToLookupTable().
CreateCall() [1/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateCall (FunctionType * FTy, Value * Callee, ArrayRef< Value *> Args = None, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2419 of file IRBuilder.h.
Referenced by AddCalls(), callIntrinsic(), CanGenerateTest(), llvm::SanitizerStatReport::create(), llvm::createAArch64StackTaggingPass(), createFFSIntrinsic(), CreateGCRelocates(), createOrdering(), createPopcntIntrinsic(), createPowWithIntegerExponent(), CreatePrologue(), llvm::orc::IRSpeculationLayer::emit(), llvm::AArch64TargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::coro::Shape::emitDealloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitGetSwiftErrorValue(), emitLibCall(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), emitSetSwiftErrorValue(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::PPCTargetLowering::emitTrailingFence(), emitUnaryFloatFnCallHelper(), getAllocaSizeInBytes(), GetCtorAndDtorPriority(), getDeclareIntrin(), getIntrinsicForMaskedAtomicRMWBinOp(), getIntToFPVal(), GetRMWLibcall(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), getSignature(), getSqrtCall(), getStackGuard(), getSuccState(), GlobalWasGeneratedByCompiler(), INITIALIZE_PASS(), insertSinCosCall(), insertValues(), instrumentMaskedLoadOrStore(), instrumentOneFunc(), isAtomic(), isCallPromotable(), isIndirectBrTarget(), IsInterestingCmp(), isInterestingPointerSubtraction(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerLocalAllocas(), llvm::ARMTargetLowering::makeDMB(), llvm::makeGuardControlFlowExplicit(), needsRuntimeRegistrationOfSectionRange(), optimizeBinaryDoubleFP(), optimizeDoubleFP(), optimizeTrigReflections(), postDominates(), processUMulZExtIdiom(), promotedOpIsNUW(), replaceUnaryCall(), RetagMask(), llvm::LoopDataPrefetchPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::ModuleSanitizerCoveragePass::run(), shouldKeepFDivF32(), shouldKeepInEntry(), SimplifyBSwap(), tryToRecognizePopCount(), TypeSizeToSizeIndex(), upgradeAVX512MaskToSelect(), UpgradeX86AddSubSatIntrinsics(), upgradeX86ConcatShift(), UpgradeX86MaskedShift(), upgradeX86Rotate(), UpgradeX86VPERMT2Intrinsics(), llvm::AMDGPULibCalls::useNative(), and UseTlsOffset().
CreateCall() [2/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateCall (FunctionType * FTy, Value * Callee, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2430 of file IRBuilder.h.
CreateCall() [3/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateCall (FunctionCallee Callee, ArrayRef< Value *> Args = None, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2441 of file IRBuilder.h.
CreateCall() [4/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateCall (FunctionCallee Callee, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2447 of file IRBuilder.h.
CreateCall() [5/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateCall (Value * Callee, ArrayRef< Value *> Args = None, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2455 of file IRBuilder.h.
CreateCall() [6/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateCall (Value * Callee, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2463 of file IRBuilder.h.
CreateCallBr() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst* llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionType * Ty, Value * Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args = None, const Twine & Name = "") inline
Create a callbr instruction.
Definition at line 1071 of file IRBuilder.h.
CreateCallBr() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst* llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionType * Ty, Value * Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 1079 of file IRBuilder.h.
CreateCallBr() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst* llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionCallee Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args = None, const Twine & Name = "") inline
Definition at line 1090 of file IRBuilder.h.
CreateCallBr() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst* llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionCallee Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock *> IndirectDests, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 1097 of file IRBuilder.h.
CreateCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateCast (Instruction::CastOps Op, Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2138 of file IRBuilder.h.
Referenced by createReplacementInstr(), foldICmpWithZextOrSext(), foldOperationIntoSelectOperand(), getScalarIntrinsicDeclaration(), INITIALIZE_PASS(), performMaskedAtomicOp(), shrinkInsertElt(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
CreateCatchPad()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CatchPadInst* llvm::IRBuilder< T, Inserter >::CreateCatchPad (Value * ParentPad, ArrayRef< Value *> Args, const Twine & Name = "") inline
Definition at line 1122 of file IRBuilder.h.
CreateCatchRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CatchReturnInst* llvm::IRBuilder< T, Inserter >::CreateCatchRet (CatchPadInst * CatchPad, BasicBlock * BB) inline
Definition at line 1133 of file IRBuilder.h.
CreateCatchSwitch()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CatchSwitchInst* llvm::IRBuilder< T, Inserter >::CreateCatchSwitch (Value * ParentPad, BasicBlock * UnwindBB, unsigned NumHandlers, const Twine & Name = "") inline
Definition at line 1115 of file IRBuilder.h.
CreateCleanupPad()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CleanupPadInst* llvm::IRBuilder< T, Inserter >::CreateCleanupPad (Value * ParentPad, ArrayRef< Value *> Args = None, const Twine & Name = "") inline
Definition at line 1127 of file IRBuilder.h.
CreateCleanupRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CleanupReturnInst* llvm::IRBuilder< T, Inserter >::CreateCleanupRet (CleanupPadInst * CleanupPad, BasicBlock * UnwindBB = nullptr) inline
Definition at line 1110 of file IRBuilder.h.
CreateCondBr() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> BranchInst* llvm::IRBuilder< T, Inserter >::CreateCondBr (Value * Cond, BasicBlock * True, BasicBlock * False, MDNode * BranchWeights = nullptr, MDNode * Unpredictable = nullptr) inline
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
Definition at line 977 of file IRBuilder.h.
Referenced by ConnectEpilog(), ConnectProlog(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), CreatePrologue(), llvm::orc::IRSpeculationLayer::emit(), getSignature(), INITIALIZE_PASS(), performMaskedAtomicOp(), shouldKeepInEntry(), SwitchToLookupTable(), TurnSwitchRangeIntoICmp(), and llvm::UnrollRuntimeLoopRemainder().
CreateCondBr() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> BranchInst* llvm::IRBuilder< T, Inserter >::CreateCondBr (Value * Cond, BasicBlock * True, BasicBlock * False, Instruction * MDSrc) inline
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
Copy branch meta data if available.
Definition at line 986 of file IRBuilder.h.
CreateConstGEP1_32() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32 (Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1866 of file IRBuilder.h.
Referenced by getAllocaSizeInBytes(), INITIALIZE_PASS(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), RetagMask(), TypeSizeToSizeIndex(), and UseTlsOffset().
CreateConstGEP1_32() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32 (Type * Ty, Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1870 of file IRBuilder.h.
CreateConstGEP1_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64 (Type * Ty, Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1916 of file IRBuilder.h.
CreateConstGEP1_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64 (Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1926 of file IRBuilder.h.
CreateConstGEP2_32()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstGEP2_32 (Type * Ty, Value * Ptr, unsigned Idx0, unsigned Idx1, const Twine & Name = "") inline
Definition at line 1890 of file IRBuilder.h.
CreateConstGEP2_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64 (Type * Ty, Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1945 of file IRBuilder.h.
Referenced by INITIALIZE_PASS().
CreateConstGEP2_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64 (Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1958 of file IRBuilder.h.
CreateConstInBoundsGEP1_32()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32 (Type * Ty, Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1880 of file IRBuilder.h.
CreateConstInBoundsGEP1_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64 (Type * Ty, Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1930 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable().
CreateConstInBoundsGEP1_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64 (Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1940 of file IRBuilder.h.
CreateConstInBoundsGEP2_32()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32 (Type * Ty, Value * Ptr, unsigned Idx0, unsigned Idx1, const Twine & Name = "") inline
Definition at line 1903 of file IRBuilder.h.
Referenced by lowerSubFn().
CreateConstInBoundsGEP2_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64 (Type * Ty, Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1963 of file IRBuilder.h.
Referenced by getOrInsertValueProfilingCall().
CreateConstInBoundsGEP2_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64 (Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1976 of file IRBuilder.h.
CreateConstrainedFPBinOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp (Intrinsic::ID ID, Value * L, Value * R, Instruction * FMFSource = nullptr, const Twine & Name = "", MDNode * FPMathTag = nullptr, Optional< fp::RoundingMode > Rounding = None, Optional< fp::ExceptionBehavior > Except = None) inline
Definition at line 1561 of file IRBuilder.h.
CreateConstrainedFPCall()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateConstrainedFPCall (Function * Callee, ArrayRef< Value *> Args, const Twine & Name = "", Optional< fp::RoundingMode > Rounding = None, Optional< fp::ExceptionBehavior > Except = None) inline
Definition at line 2471 of file IRBuilder.h.
CreateConstrainedFPCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateConstrainedFPCast (Intrinsic::ID ID, Value * V, Type * DestTy, Instruction * FMFSource = nullptr, const Twine & Name = "", MDNode * FPMathTag = nullptr, Optional< fp::RoundingMode > Rounding = None, Optional< fp::ExceptionBehavior > Except = None) inline
Definition at line 2199 of file IRBuilder.h.
CreateConstrainedFPCmp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst* llvm::IRBuilder< T, Inserter >::CreateConstrainedFPCmp (Intrinsic::ID ID, CmpInst::Predicate P, Value * L, Value * R, const Twine & Name = "", Optional< fp::ExceptionBehavior > Except = None) inline
Definition at line 2394 of file IRBuilder.h.
CreateExactSDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateExactSDiv (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1286 of file IRBuilder.h.
CreateExactUDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateExactUDiv (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1272 of file IRBuilder.h.
CreateExtractElement() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateExtractElement (Value * Vec, Value * Idx, const Twine & Name = "") inline
Definition at line 2520 of file IRBuilder.h.
Referenced by EmitX86ScalarSelect(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPBasicBlock::execute(), extractValues(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), foldICmpBitCast(), getMulHu(), llvm::InnerLoopVectorizer::getOrCreateScalarValue(), llvm::getOrderedReduction(), llvm::getShuffleReduction(), INITIALIZE_PASS(), insertSinCosCall(), instrumentMaskedLoadOrStore(), isAtomic(), isReInterleaveMask(), shouldKeepFDivF32(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), and upgradeMaskedMove().
CreateExtractElement() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateExtractElement (Value * Vec, uint64_t Idx, const Twine & Name = "") inline
Definition at line 2528 of file IRBuilder.h.
CreateExtractInteger()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateExtractInteger (const DataLayout & DL, Value * From, IntegerType * ExtractedTy, uint64_t Offset, const Twine & Name) inline
Return a value that has been extracted from a larger integer type.
Definition at line 2694 of file IRBuilder.h.
CreateExtractValue()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateExtractValue (Value * Agg, ArrayRef< unsigned > Idxs, const Twine & Name = "") inline
Definition at line 2562 of file IRBuilder.h.
Referenced by atomicSizeSupported(), createCast(), createCmpXchgInstFun(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), generatePoisonChecksForBinOp(), GetRMWLibcall(), getSignature(), INITIALIZE_PASS(), insertSinCosCall(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), optimizeBinaryDoubleFP(), OptimizeNoopCopyExpression(), performMaskedAtomicOp(), processUMulZExtIdiom(), simplifyX86addcarry(), TypeSizeToSizeIndex(), and unpackStoreToAggregate().
CreateFAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFAdd (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1426 of file IRBuilder.h.
Referenced by llvm::log2(), LowerAtomicRMWInst(), optimizeBinaryDoubleFP(), and performAtomicOp().
CreateFAddFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFAddFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1439 of file IRBuilder.h.
Referenced by factorizeFAddFSub().
CreateFCmp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmp (CmpInst::Predicate P, Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2367 of file IRBuilder.h.
Referenced by llvm::createMinMaxOp(), foldVectorCmp(), getFCmpValue(), and reassociateFCmps().
CreateFCmpOEQ()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpOEQ (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2286 of file IRBuilder.h.
CreateFCmpOGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpOGE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2296 of file IRBuilder.h.
Referenced by getMulHu().
CreateFCmpOGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpOGT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2291 of file IRBuilder.h.
Referenced by createRdxShuffleMask().
CreateFCmpOLE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpOLE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2306 of file IRBuilder.h.
CreateFCmpOLT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpOLT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2301 of file IRBuilder.h.
Referenced by createRdxShuffleMask().
CreateFCmpONE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpONE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2311 of file IRBuilder.h.
CreateFCmpORD()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpORD (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2316 of file IRBuilder.h.
CreateFCmpS()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpS (CmpInst::Predicate P, Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2382 of file IRBuilder.h.
CreateFCmpUEQ()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpUEQ (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2326 of file IRBuilder.h.
CreateFCmpUGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpUGE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2336 of file IRBuilder.h.
CreateFCmpUGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpUGT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2331 of file IRBuilder.h.
CreateFCmpULE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpULE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2346 of file IRBuilder.h.
CreateFCmpULT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpULT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2341 of file IRBuilder.h.
CreateFCmpUNE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpUNE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2351 of file IRBuilder.h.
CreateFCmpUNO()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFCmpUNO (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2321 of file IRBuilder.h.
CreateFDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFDiv (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1501 of file IRBuilder.h.
Referenced by createPowWithIntegerExponent(), llvm::AMDGPULibCalls::fold(), getMulHu(), llvm::log2(), shouldKeepFDivF32(), and llvm::InstCombiner::visitFDiv().
CreateFDivFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFDivFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1514 of file IRBuilder.h.
CreateFence()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> FenceInst* llvm::IRBuilder< T, Inserter >::CreateFence (AtomicOrdering Ordering, SyncScope::ID SSID = SyncScope::System, const Twine & Name = "") inline
Definition at line 1787 of file IRBuilder.h.
Referenced by llvm::RISCVTargetLowering::emitLeadingFence(), llvm::TargetLoweringBase::emitLeadingFence(), llvm::RISCVTargetLowering::emitTrailingFence(), and llvm::TargetLoweringBase::emitTrailingFence().
CreateFMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFMul (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1476 of file IRBuilder.h.
Referenced by buildMultiplyTree(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), createPowWithIntegerExponent(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::AMDGPULibCalls::fold(), getIntToFPVal(), getMulHu(), getPow(), llvm::InnerLoopVectorizer::getStepVector(), llvm::log2(), and optimizeBinaryDoubleFP().
CreateFMulFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFMulFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1489 of file IRBuilder.h.
Referenced by factorizeLerp().
CreateFNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFNeg (Value * V, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 1598 of file IRBuilder.h.
Referenced by canonicalizeSaturatedAdd(), getMulHu(), and optimizeTrigReflections().
CreateFNegFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFNegFMF (Value * V, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1608 of file IRBuilder.h.
Referenced by hoistFNegAboveFMulFDiv().
CreateFPCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFPCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2191 of file IRBuilder.h.
CreateFPExt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFPExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2084 of file IRBuilder.h.
Referenced by optimizeDoubleFP().
CreateFPToSI()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFPToSI (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2054 of file IRBuilder.h.
Referenced by getMulHu(), and llvm::log2().
CreateFPToUI()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFPToUI (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2047 of file IRBuilder.h.
Referenced by getMulHu().
CreateFPTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFPTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2075 of file IRBuilder.h.
CreateFreeze()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFreeze (Value * V, const Twine & Name = "") inline
Definition at line 2584 of file IRBuilder.h.
CreateFRem()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFRem (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1526 of file IRBuilder.h.
CreateFRemFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFRemFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1539 of file IRBuilder.h.
CreateFSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFSub (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1451 of file IRBuilder.h.
Referenced by LowerAtomicRMWInst(), and performAtomicOp().
CreateFSubFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateFSubFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1464 of file IRBuilder.h.
Referenced by factorizeFAddFSub(), and factorizeLerp().
CreateGEP() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateGEP (Value * Ptr, ArrayRef< Value *> IdxList, const Twine & Name = "") inline
Definition at line 1808 of file IRBuilder.h.
Referenced by AddCalls(), annotateNonNullAndDereferenceable(), createMaskedBitTest(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), doPromotion(), llvm::InnerLoopVectorizer::emitTransformedIndex(), getScalarIntrinsicDeclaration(), hasSameExtUse(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isGEPFoldable(), IsNonLocalValue(), isReportingError(), llvm::LibCallSimplifier::LibCallSimplifier(), lowerLoadRelative(), moveUp(), TypeSizeToSizeIndex(), unifyBitWidth(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), and llvm::InnerLoopVectorizer::widenGEP().
CreateGEP() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateGEP (Type * Ty, Value * Ptr, ArrayRef< Value *> IdxList, const Twine & Name = "") inline
Definition at line 1813 of file IRBuilder.h.
CreateGEP() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateGEP (Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1847 of file IRBuilder.h.
CreateGEP() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateGEP (Type * Ty, Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1851 of file IRBuilder.h.
CreateGlobalStringPtr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Constant* llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr (StringRef Str, const Twine & Name = "", unsigned AddressSpace = 0) inline
Same as CreateGlobalString, but return a pointer with "i8*" type instead of a pointer to array of i8.
Definition at line 1992 of file IRBuilder.h.
Referenced by CreatePrologue(), and shouldKeepInEntry().
CreateICmp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmp (CmpInst::Predicate P, Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2356 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), canonicalizeSaturatedAdd(), createFFSIntrinsic(), createMinMax(), llvm::createMinMaxOp(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), foldAndOrOfEqualityCmpsWithConstants(), foldICmpWithLowBitMaskedVal(), foldICmpWithTruncSignExtendedVal(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldVectorCmp(), generatePoisonChecks(), generatePoisonChecksForBinOp(), getNewICmpValue(), INITIALIZE_PASS(), mapBinOpcode(), promotedOpIsNUW(), llvm::LoopPredicationPass::run(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), upgradeAbs(), upgradeIntMinMax(), upgradeMaskedCompare(), and upgradeX86vpcom().
CreateICmpEQ()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpEQ (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2246 of file IRBuilder.h.
Referenced by ConvertTwoCaseSwitch(), createOrdering(), CreatePrologue(), llvm::orc::IRSpeculationLayer::emit(), llvm::HexagonTargetLowering::emitStoreConditional(), foldAnyOrAllBitsSet(), foldIsPowerOf2(), getMulHu(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), getSignature(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isKnownTypeIdMember(), LowerAtomicCmpXchgInst(), and performMaskedAtomicOp().
CreateICmpNE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpNE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2250 of file IRBuilder.h.
Referenced by CanGenerateTest(), llvm::createAMDGPUPrintfRuntimeBinding(), createMaskedBitTest(), llvm::createMemCpyLoopUnknownSize(), foldIsPowerOf2(), getSignature(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), optimizeMemCmpConstantSize(), performMaskedAtomicOp(), and TypeSizeToSizeIndex().
CreateICmpSGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpSGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2274 of file IRBuilder.h.
Referenced by canonicalizeSaturatedAdd(), and instrumentMaskedLoadOrStore().
CreateICmpSGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpSGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2270 of file IRBuilder.h.
Referenced by createRdxShuffleMask(), performAtomicOp(), and simplifyX86pack().
CreateICmpSLE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpSLE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2282 of file IRBuilder.h.
Referenced by performAtomicOp().
CreateICmpSLT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpSLT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2278 of file IRBuilder.h.
Referenced by canonicalizeSaturatedAdd(), createRdxShuffleMask(), getBoundsCheckCond(), LowerAtomicRMWInst(), shouldKeepInEntry(), simplifyX86movmsk(), and simplifyX86pack().
CreateICmpUGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpUGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2258 of file IRBuilder.h.
Referenced by foldUnsignedUnderflowCheck(), getMulHu(), and TypeSizeToSizeIndex().
CreateICmpUGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpUGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2254 of file IRBuilder.h.
Referenced by createRdxShuffleMask(), foldUnsignedUnderflowCheck(), performAtomicOp(), and TypeSizeToSizeIndex().
CreateICmpULE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpULE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2266 of file IRBuilder.h.
Referenced by foldUnsignedUnderflowCheck(), isKnownTypeIdMember(), llvm::VPRecipeBase::moveAfter(), moveUp(), and performAtomicOp().
CreateICmpULT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateICmpULT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2262 of file IRBuilder.h.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), ConnectProlog(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), createRdxShuffleMask(), foldSignedTruncationCheck(), foldUnsignedUnderflowCheck(), getBoundsCheckCond(), LowerAtomicRMWInst(), llvm::lowerObjectSizeCall(), mayLoopAccessLocation(), SwitchToLookupTable(), TurnSwitchRangeIntoICmp(), and llvm::UnrollRuntimeLoopRemainder().
CreateInBoundsGEP() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP (Value * Ptr, ArrayRef< Value *> IdxList, const Twine & Name = "") inline
Definition at line 1827 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), createReplacementInstr(), INITIALIZE_PASS(), isCallPromotable(), IsNonLocalValue(), llvm::LibCallSimplifier::LibCallSimplifier(), optimizeMemCmpConstantSize(), shouldKeepInEntry(), unifyBitWidth(), unpackLoadToAggregate(), unpackStoreToAggregate(), and llvm::InnerLoopVectorizer::widenGEP().
CreateInBoundsGEP() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP (Type * Ty, Value * Ptr, ArrayRef< Value *> IdxList, const Twine & Name = "") inline
Definition at line 1832 of file IRBuilder.h.
CreateInBoundsGEP() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP (Type * Ty, Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1858 of file IRBuilder.h.
CreateIndirectBr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> IndirectBrInst* llvm::IRBuilder< T, Inserter >::CreateIndirectBr (Value * Addr, unsigned NumDests = 10) inline
Create an indirect branch instruction with the specified address operand, with an optional hint for the number of destinations that will be added (for efficient allocation).
Definition at line 1010 of file IRBuilder.h.
CreateInsertElement() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateInsertElement (Value * Vec, Value * NewElt, Value * Idx, const Twine & Name = "") inline
Definition at line 2533 of file IRBuilder.h.
Referenced by canonicalizeInsertSplat(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), getMulHu(), getScalarIntrinsicDeclaration(), hoistInsEltConst(), INITIALIZE_PASS(), insertValues(), optimizeIntegerToVectorInsertions(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), shouldKeepFDivF32(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), and upgradeMaskedMove().
CreateInsertElement() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateInsertElement (Value * Vec, Value * NewElt, uint64_t Idx, const Twine & Name = "") inline
Definition at line 2542 of file IRBuilder.h.
CreateInsertValue()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const Twine & Name = "") inline
Definition at line 2570 of file IRBuilder.h.
Referenced by createCast(), createOrdering(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), GetRMWLibcall(), getSignature(), INITIALIZE_PASS(), LowerAtomicCmpXchgInst(), performMaskedAtomicOp(), processOverflowIntrinsic(), simplifyX86addcarry(), splitRetconCoroutine(), and unpackLoadToAggregate().
CreateIntCast() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateIntCast (Value * V, Type * DestTy, bool isSigned, const Twine & Name = "") inline
Definition at line 2170 of file IRBuilder.h.
Referenced by createOrdering(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitPutChar(), evaluateGEPOffsetExpression(), getReducedType(), GlobalWasGeneratedByCompiler(), hasZeroSignBit(), insertSinCosCall(), instrumentMaskedLoadOrStore(), IsNonLocalValue(), isReportingError(), llvm::LibCallSimplifier::LibCallSimplifier(), llvm::IntrinsicLowering::LowerIntrinsicCall(), optimizeMemCmpConstantSize(), simplifyAllocaArraySize(), TypeSizeToSizeIndex(), upgradeX86ConcatShift(), and upgradeX86Rotate().
CreateIntCast() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateIntCast (Value * , Type * , const char *) delete
CreateIntToPtr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateIntToPtr (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2096 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), createCast(), createMaskInstrs(), createOrdering(), llvm::createSeparateConstOffsetFromGEPPass(), getSignature(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isAtomic(), IsNonLocalValue(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), RetagMask(), and TypeSizeToSizeIndex().
CreateInvoke() [1/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst* llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionType * Ty, Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Create an invoke instruction.
Definition at line 1015 of file IRBuilder.h.
Referenced by INITIALIZE_PASS().
CreateInvoke() [2/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst* llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionType * Ty, Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value *> Args = None, const Twine & Name = "") inline
Definition at line 1024 of file IRBuilder.h.
CreateInvoke() [3/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst* llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionCallee Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 1032 of file IRBuilder.h.
CreateInvoke() [4/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst* llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionCallee Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value *> Args = None, const Twine & Name = "") inline
Definition at line 1040 of file IRBuilder.h.
CreateInvoke() [5/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst* llvm::IRBuilder< T, Inserter >::CreateInvoke (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value *> Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 1049 of file IRBuilder.h.
CreateInvoke() [6/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst* llvm::IRBuilder< T, Inserter >::CreateInvoke (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value *> Args = None, const Twine & Name = "") inline
Definition at line 1060 of file IRBuilder.h.
CreateIsNotNull()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateIsNotNull (Value * Arg, const Twine & Name = "") inline
Return an i1 value testing if Arg is not null.
Definition at line 2599 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), ConnectEpilog(), foldAnyOrAllBitsSet(), foldSelectICmpAndAnd(), llvm::UnrollRuntimeLoopRemainder(), and upgradeMaskedMove().
CreateIsNull()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateIsNull (Value * Arg, const Twine & Name = "") inline
Return an i1 value testing if Arg is null.
Definition at line 2593 of file IRBuilder.h.
CreateLandingPad()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LandingPadInst* llvm::IRBuilder< T, Inserter >::CreateLandingPad (Type * Ty, unsigned NumClauses, const Twine & Name = "") inline
Definition at line 2579 of file IRBuilder.h.
CreateLaunderInvariantGroup()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup (Value * Ptr) inline
Create a launder.invariant.group intrinsic call.
If Ptr type is different from pointer to i8, it's casted to pointer to i8 in the same address space before call and casted back to Ptr type after call.
Definition at line 2625 of file IRBuilder.h.
Referenced by simplifyInvariantGroupIntrinsic().
CreateLoad() [1/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateLoad (Type * Ty, Value * Ptr, const char * Name) inline
Provided to resolve 'CreateLoad(Ty, Ptr, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
Definition at line 1669 of file IRBuilder.h.
Referenced by AddCalls(), annotateNonNullAndDereferenceable(), createMaskedBitTest(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), CreatePrologue(), createResumeEntryBlock(), doPromotion(), llvm::orc::IRSpeculationLayer::emit(), emitSetAndGetSwiftErrorValueAround(), ensurePromotedGV(), GetCtorAndDtorPriority(), getMulHu(), getOrInsertValueProfilingCall(), getSignature(), getStackGuard(), getSuccState(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isReportingError(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), lowerSubFn(), needsRuntimeRegistrationOfSectionRange(), optimizeMemCmpConstantSize(), performMaskedAtomicOp(), RetagMask(), llvm::HWAddressSanitizerPass::run(), shouldKeepInEntry(), and TypeSizeToSizeIndex().
CreateLoad() [2/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateLoad (Type * Ty, Value * Ptr, const Twine & Name = "") inline
Definition at line 1673 of file IRBuilder.h.
CreateLoad() [3/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateLoad (Type * Ty, Value * Ptr, bool isVolatile, const Twine & Name = "") inline
Definition at line 1677 of file IRBuilder.h.
CreateLoad() [4/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateLoad (Value * Ptr, const char * Name) inline
Definition at line 1683 of file IRBuilder.h.
CreateLoad() [5/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateLoad (Value * Ptr, const Twine & Name = "") inline
Definition at line 1688 of file IRBuilder.h.
CreateLoad() [6/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst* llvm::IRBuilder< T, Inserter >::CreateLoad (Value * Ptr, bool isVolatile, const Twine & Name = "") inline
Definition at line 1693 of file IRBuilder.h.
CreateLShr() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateLShr (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1321 of file IRBuilder.h.
Referenced by llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), foldBitcastExtElt(), foldICmpWithHighBitMask(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), getMul64(), getShiftedValue(), GlobalWasGeneratedByCompiler(), hasZeroSignBit(), INITIALIZE_PASS(), instrumentMaskedLoadOrStore(), isKnownTypeIdMember(), LowerBSWAP(), LowerCTLZ(), LowerCTPOP(), performMaskedAtomicOp(), promotedOpIsNUW(), ReduceSwitchRange(), RetagMask(), simplifyX86immShift(), simplifyX86varShift(), SwitchToLookupTable(), and TypeSizeToSizeIndex().
CreateLShr() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateLShr (Value * LHS, const APInt & RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1331 of file IRBuilder.h.
CreateLShr() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateLShr (Value * LHS, uint64_t RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1336 of file IRBuilder.h.
CreateMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateMul (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1245 of file IRBuilder.h.
Referenced by buildMultiplyTree(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::InnerLoopVectorizer::emitTransformedIndex(), generatedUnsignedRemainderCode(), getMul64(), getMulHu(), llvm::InnerLoopVectorizer::getStepVector(), INITIALIZE_PASS(), isCallPromotable(), isGEPFoldable(), IsNonLocalValue(), unifyBitWidth(), upgradePMULDQ(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), and llvm::ObjectSizeOffsetEvaluator::visitCallSite().
CreateNAryOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNAryOp (unsigned Opc, ArrayRef< Value *> Ops, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Create either a UnaryOperator or BinaryOperator depending on Opc.
Correct number of operands must be passed accordingly.
Definition at line 1636 of file IRBuilder.h.
Referenced by llvm::InnerLoopVectorizer::widenInstruction().
CreateNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNeg (Value * V, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1580 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), foldUnsignedUnderflowCheck(), getMulHu(), mapBinOpcode(), unifyBitWidth(), and upgradeAbs().
CreateNot()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNot (Value * V, const Twine & Name = "") inline
Definition at line 1617 of file IRBuilder.h.
Referenced by canonicalizeICmpBool(), canonicalizeSaturatedAdd(), llvm::createAMDGPUPrintfRuntimeBinding(), createMaskInstrs(), LowerAtomicRMWInst(), LowerCTLZ(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::VPRecipeBase::moveAfter(), performAtomicOp(), SimplifyCondBranchToCondBranch(), sinkNotIntoXor(), TypeSizeToSizeIndex(), and visitMaskedMerge().
CreateNSWAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNSWAdd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1220 of file IRBuilder.h.
CreateNSWMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNSWMul (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1254 of file IRBuilder.h.
CreateNSWNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNSWNeg (Value * V, const Twine & Name = "") inline
Definition at line 1590 of file IRBuilder.h.
CreateNSWSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNSWSub (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1237 of file IRBuilder.h.
CreateNUWAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNUWAdd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1224 of file IRBuilder.h.
Referenced by foldNoWrapAdd().
CreateNUWMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNUWMul (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1258 of file IRBuilder.h.
CreateNUWNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNUWNeg (Value * V, const Twine & Name = "") inline
Definition at line 1594 of file IRBuilder.h.
CreateNUWSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateNUWSub (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1241 of file IRBuilder.h.
CreateOr() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateOr (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1387 of file IRBuilder.h.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), buildOrChain(), canonicalizeSaturatedAdd(), checkForNegativeOperand(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), foldAndOrOfEqualityCmpsWithConstants(), foldLogOpOfMaskedICmps(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), getBoundsCheckCond(), getMulHu(), GlobalWasGeneratedByCompiler(), INITIALIZE_PASS(), isKnownTypeIdMember(), llvm::log2(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTLZ(), performAtomicOp(), performMaskedAtomicOp(), ReduceSwitchRange(), RetagMask(), and TypeSizeToSizeIndex().
CreateOr() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateOr (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 1397 of file IRBuilder.h.
CreateOr() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateOr (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 1401 of file IRBuilder.h.
CreateOr() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateOr (ArrayRef< Value *> Ops) inline
Definition at line 1405 of file IRBuilder.h.
CreatePHI()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> PHINode* llvm::IRBuilder< T, Inserter >::CreatePHI (Type * Ty, unsigned NumReservedValues, const Twine & Name = "") inline
Definition at line 2411 of file IRBuilder.h.
Referenced by llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), createRetPHINode(), llvm::VPPredInstPHIRecipe::execute(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), getScalarIntrinsicDeclaration(), getSignature(), isKnownTypeIdMember(), performMaskedAtomicOp(), shouldKeepInEntry(), speculatePHIs(), splitRetconCoroutine(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
CreatePointerBitCastOrAddrSpaceCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreatePointerBitCastOrAddrSpaceCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2156 of file IRBuilder.h.
CreatePointerCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreatePointerCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2147 of file IRBuilder.h.
Referenced by llvm::createAArch64StackTaggingPass(), createOrdering(), getAllocaSizeInBytes(), GlobalWasGeneratedByCompiler(), hasSameExtUse(), instrumentMaskedLoadOrStore(), isAtomic(), IsInterestingCmp(), isInterestingPointerSubtraction(), IsNonLocalValue(), postDominates(), RetagMask(), TypeSizeToSizeIndex(), llvm::AMDGPULibCalls::useNative(), and UseTlsOffset().
CreatePreserveArrayAccessIndex()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex (Type * ElTy, Value * Base, unsigned Dimension, unsigned LastIndex, MDNode * DbgInfo) inline
Definition at line 2717 of file IRBuilder.h.
CreatePreserveStructAccessIndex()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex (Type * ElTy, Value * Base, unsigned Index, unsigned FieldIndex, MDNode * DbgInfo) inline
Definition at line 2766 of file IRBuilder.h.
CreatePreserveUnionAccessIndex()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreatePreserveUnionAccessIndex (Value * Base, unsigned FieldIndex, MDNode * DbgInfo) inline
Definition at line 2747 of file IRBuilder.h.
CreatePtrDiff()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreatePtrDiff (Value * LHS, Value * RHS, const Twine & Name = "") inline
Return the i64 difference between two pointer values, dividing out the size of the pointed-to objects.
This is intended to implement C-style pointer subtraction. As such, the pointers must be appropriately aligned for their element types and pointing into the same object.
Definition at line 2610 of file IRBuilder.h.
CreatePtrToInt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreatePtrToInt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2091 of file IRBuilder.h.
Referenced by createCast(), createMaskInstrs(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::orc::IRSpeculationLayer::emit(), FitWeights(), GetCtorAndDtorPriority(), INITIALIZE_PASS(), instrumentOneFunc(), isKnownTypeIdMember(), IsNonLocalValue(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), mayLoopAccessLocation(), and RetagMask().
CreateResume()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ResumeInst* llvm::IRBuilder< T, Inserter >::CreateResume (Value * Exn) inline
Definition at line 1106 of file IRBuilder.h.
CreateRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ReturnInst* llvm::IRBuilder< T, Inserter >::CreateRet (Value * V) inline
Create a 'ret <val>' instruction.
Definition at line 952 of file IRBuilder.h.
Referenced by INITIALIZE_PASS(), llvm::InlineFunction(), llvm::makeGuardControlFlowExplicit(), needsRuntimeRegistrationOfSectionRange(), shouldKeepInEntry(), SimplifyCondBranchToTwoReturns(), splitRetconCoroutine(), and SwitchToLookupTable().
CreateRetVoid()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ReturnInst* llvm::IRBuilder< T, Inserter >::CreateRetVoid () inline
Create a 'ret void' instruction.
Definition at line 947 of file IRBuilder.h.
Referenced by llvm::createX86RetpolineThunksPass(), INITIALIZE_PASS(), llvm::makeGuardControlFlowExplicit(), needsRuntimeRegistrationOfSectionRange(), shouldKeepInEntry(), and SimplifyCondBranchToTwoReturns().
CreateSDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSDiv (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1276 of file IRBuilder.h.
Referenced by llvm::expandDivisionUpTo32Bits(), and llvm::expandDivisionUpTo64Bits().
CreateSelect()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSelect (Value * C, Value * True, Value * False, const Twine & Name = "", Instruction * MDFrom = nullptr) inline
Definition at line 2498 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), canonicalizeSaturatedAdd(), ConvertTwoCaseSwitch(), createMinMax(), llvm::createMinMaxOp(), createRdxShuffleMask(), EmitX86ScalarSelect(), EmitX86Select(), FoldTwoEntryPHINode(), getMulHu(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), getScalarIntrinsicDeclaration(), hasZeroSignBit(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), llvm::lowerObjectSizeCall(), moveUp(), performAtomicOp(), promotedOpIsNUW(), SimplifyCondBranchToTwoReturns(), simplifyX86pack(), SpeculativelyExecuteBB(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), upgradeAbs(), upgradeIntMinMax(), upgradeMaskedMove(), and llvm::ObjectSizeOffsetEvaluator::visitSelectInst().
CreateSExt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2013 of file IRBuilder.h.
Referenced by llvm::createAMDGPUPrintfRuntimeBinding(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::InnerLoopVectorizer::fixReduction(), foldNoWrapAdd(), getIntrinsicForMaskedAtomicRMWBinOp(), getIntToFPVal(), getMulHu(), operator<<(), promotedOpIsNUW(), TypeSizeToSizeIndex(), UpgradeMaskToInt(), upgradeX86vpcom(), and visitIVCast().
CreateSExtOrBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSExtOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2120 of file IRBuilder.h.
CreateSExtOrTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Create a SExt or Trunc from the integer value V to DestTy.
Return the value untouched if the type of V is already DestTy.
Definition at line 2034 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), insertValues(), isGEPFoldable(), mapBinOpcode(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), unifyBitWidth(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
CreateShl() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateShl (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1300 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), canonicalizeLowbitMask(), createMaskedBitTest(), createMaskInstrs(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), getShiftedValue(), INITIALIZE_PASS(), isKnownTypeIdMember(), llvm::log2(), LowerBSWAP(), performMaskedAtomicOp(), ReduceSwitchRange(), RetagMask(), simplifyValueKnownNonZero(), simplifyX86immShift(), simplifyX86varShift(), TypeSizeToSizeIndex(), unifyBitWidth(), and upgradePMULDQ().
CreateShl() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateShl (Value * LHS, const APInt & RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1309 of file IRBuilder.h.
CreateShl() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateShl (Value * LHS, uint64_t RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1315 of file IRBuilder.h.
CreateShuffleVector() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateShuffleVector (Value * V1, Value * V2, Value * Mask, const Twine & Name = "") inline
Definition at line 2547 of file IRBuilder.h.
Referenced by ApplyX86MaskOn1BitsVec(), concatenateTwoVectors(), concatSubVector(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), foldSelectShuffle(), llvm::getShuffleReduction(), getX86MaskVec(), INITIALIZE_PASS(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), reorderSubVector(), llvm::InnerLoopVectorizer::reverseVector(), simplifyNeonTbl1(), simplifyX86insertps(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86vpermilvar(), simplifyX86vpermv(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), UpgradeX86ALIGNIntrinsics(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), and llvm::InnerLoopVectorizer::vectorizeInterleaveGroup().
CreateShuffleVector() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateShuffleVector (Value * V1, Value * V2, ArrayRef< uint32_t > IntMask, const Twine & Name = "") inline
Definition at line 2556 of file IRBuilder.h.
CreateSIToFP()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSIToFP (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2068 of file IRBuilder.h.
Referenced by getMulHu(), and llvm::log2().
CreateSRem()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSRem (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1295 of file IRBuilder.h.
Referenced by llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), and generatePoisonChecksForBinOp().
CreateStore()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> StoreInst* llvm::IRBuilder< T, Inserter >::CreateStore (Value * Val, Value * Ptr, bool isVolatile = false) inline
Definition at line 1698 of file IRBuilder.h.
Referenced by atomicSizeSupported(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), createResumeEntryBlock(), llvm::orc::IRSpeculationLayer::emit(), emitSetAndGetSwiftErrorValueAround(), getAllocaSizeInBytes(), getOrInsertValueProfilingCall(), getSignature(), getSuccState(), INITIALIZE_PASS(), isReportingError(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), RetagMask(), shouldKeepInEntry(), splitRetconCoroutine(), and TypeSizeToSizeIndex().
CreateStripInvariantGroup()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup (Value * Ptr) inline
Create a strip.invariant.group intrinsic call.
If Ptr type is different from pointer to i8, it's casted to pointer to i8 in the same address space before call and casted back to Ptr type after call.
Definition at line 2652 of file IRBuilder.h.
Referenced by simplifyInvariantGroupIntrinsic().
CreateStructGEP() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateStructGEP (Type * Ty, Value * Ptr, unsigned Idx, const Twine & Name = "") inline
Definition at line 1981 of file IRBuilder.h.
Referenced by createResumeEntryBlock(), getSuccState(), INITIALIZE_PASS(), shouldKeepInEntry(), and updateCoroFrame().
CreateStructGEP() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateStructGEP (Value * Ptr, unsigned Idx, const Twine & Name = "") inline
Definition at line 1986 of file IRBuilder.h.
CreateSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateSub (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1228 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), checkForNegativeOperand(), createFFSIntrinsic(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::VPlan::execute(), generatedUnsignedRemainderCode(), generateSignedDivisionCode(), generateSignedRemainderCode(), getBoundsCheckCond(), getIntrinsicForMaskedAtomicRMWBinOp(), getMulHu(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), isKnownTypeIdMember(), LowerAtomicRMWInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::lowerObjectSizeCall(), moveUp(), optimizeMemCmpConstantSize(), performAtomicOp(), ReduceSwitchRange(), simplifyValueKnownNonZero(), SwitchToLookupTable(), and unifyBitWidth().
CreateSwitch()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> SwitchInst* llvm::IRBuilder< T, Inserter >::CreateSwitch (Value * V, BasicBlock * Dest, unsigned NumCases = 10, MDNode * BranchWeights = nullptr, MDNode * Unpredictable = nullptr) inline
Create a switch instruction with the specified value, default dest, and with a hint for the number of cases that will be added (for efficient allocation).
Definition at line 1000 of file IRBuilder.h.
Referenced by createResumeEntryBlock(), FitWeights(), and getSignature().
CreateTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2005 of file IRBuilder.h.
Referenced by createMaskInstrs(), dropRedundantMaskingOfLeftShiftInput(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), evaluateGEPOffsetExpression(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::InnerLoopVectorizer::fixReduction(), foldBitcastExtElt(), getAllocaSizeInBytes(), getIntrinsicForMaskedAtomicRMWBinOp(), getMul64(), getMulHu(), INITIALIZE_PASS(), IsNonLocalValue(), isReportingError(), operator<<(), performMaskedAtomicOp(), promotedOpIsNUW(), shrinkSplatShuffle(), simplifyX86pack(), SwitchToLookupTable(), truncateIVUse(), TypeSizeToSizeIndex(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
CreateTruncOrBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateTruncOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2129 of file IRBuilder.h.
Referenced by llvm::ARMTargetLowering::emitLoadLinked(), and llvm::SCEVExpander::replaceCongruentIVs().
CreateUDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateUDiv (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1262 of file IRBuilder.h.
Referenced by llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), generatedUnsignedRemainderCode(), and generateSignedDivisionCode().
CreateUIToFP()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateUIToFP (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2061 of file IRBuilder.h.
Referenced by getMulHu().
CreateUnOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateUnOp (Instruction::UnaryOps Opc, Value * V, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 1623 of file IRBuilder.h.
CreateUnreachable()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> UnreachableInst* llvm::IRBuilder< T, Inserter >::CreateUnreachable () inline
Definition at line 1137 of file IRBuilder.h.
Referenced by CreatePrologue(), createResumeEntryBlock(), llvm::VPBasicBlock::execute(), llvm::VPlan::execute(), getSignature(), performMaskedAtomicOp(), removeUndefIntroducingPredecessor(), and TryToMergeLandingPad().
CreateURem()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateURem (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1290 of file IRBuilder.h.
Referenced by llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), generatePoisonChecksForBinOp(), generateSignedRemainderCode(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), and llvm::UnrollRuntimeLoopRemainder().
CreateVAArg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> VAArgInst* llvm::IRBuilder< T, Inserter >::CreateVAArg (Value * List, Type * Ty, const Twine & Name = "") inline
Definition at line 2516 of file IRBuilder.h.
CreateVectorSplat()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateVectorSplat (unsigned NumElts, Value * V, const Twine & Name = "") inline
Return a vector value that contains.
V broadcasted to NumElts elements.
Definition at line 2679 of file IRBuilder.h.
Referenced by llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::getBroadcastInstrs(), getScalarIntrinsicDeclaration(), llvm::InnerLoopVectorizer::getStepVector(), simplifyX86immShift(), upgradeX86ConcatShift(), upgradeX86Rotate(), and llvm::InnerLoopVectorizer::widenGEP().
CreateXor() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateXor (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1413 of file IRBuilder.h.
Referenced by canonicalizeICmpBool(), createMaskInstrs(), foldAndToXor(), foldOrToXor(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldXorToXor(), generateSignedDivisionCode(), generateSignedRemainderCode(), getMulHu(), hasZeroSignBit(), LowerAtomicRMWInst(), performAtomicOp(), RetagMask(), and TypeSizeToSizeIndex().
CreateXor() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateXor (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 1418 of file IRBuilder.h.
CreateXor() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateXor (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 1422 of file IRBuilder.h.
CreateZExt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateZExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2009 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::InnerLoopVectorizer::fixReduction(), foldAnyOrAllBitsSet(), foldNoWrapAdd(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldUDivShl(), getIntToFPVal(), getMul64(), getMulHu(), hasZeroSignBit(), INITIALIZE_PASS(), isIndirectBrTarget(), moveUp(), operator<<(), optimizeMemCmpConstantSize(), performMaskedAtomicOp(), processUMulZExtIdiom(), promotedOpIsNUW(), RetagMask(), simplifyX86addcarry(), TypeSizeToSizeIndex(), and visitIVCast().
CreateZExtOrBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateZExtOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2111 of file IRBuilder.h.
Referenced by llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), and llvm::log2().
CreateZExtOrTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value* llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Create a ZExt or Trunc from the integer value V to DestTy.
Return the value untouched if the type of V is already DestTy.
Definition at line 2019 of file IRBuilder.h.
Referenced by annotateNonNullAndDereferenceable(), canonicalizeSaturatedAdd(), createFFSIntrinsic(), createMaskedBitTest(), foldSelectICmpAnd(), foldSelectICmpAndOr(), insertValues(), instrumentOneFunc(), llvm::lowerObjectSizeCall(), mapBinOpcode(), simplifyX86movmsk(), SwitchToLookupTable(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), and llvm::ObjectSizeOffsetEvaluator::visitCallSite().
getFolder()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> const T& llvm::IRBuilder< T, Inserter >::getFolder () inline
Get the constant folder being used.
Definition at line 913 of file IRBuilder.h.
Insert() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> template<typename InstTy > InstTy* llvm::IRBuilder< T, Inserter >::Insert (InstTy * I, const Twine & Name = "") const inline
Insert and return the specified instruction.
Definition at line 917 of file IRBuilder.h.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), canonicalizeSaturatedAdd(), dropRedundantMaskingOfLeftShiftInput(), INITIALIZE_PASS(), isReportingError(), llvm::InnerLoopVectorizer::scalarizeInstruction(), and llvm::InnerLoopVectorizer::widenGEP().
Insert() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Constant* llvm::IRBuilder< T, Inserter >::Insert (Constant * C, const Twine & = "") const inline
No-op overload to handle constants.
Definition at line 924 of file IRBuilder.h.
The documentation for this class was generated from the following file:
include/llvm/IR/IRBuilder.h