LLVM: llvm::xray::BlockIndexer Class Reference
llvm::xray::BlockIndexer Class Reference
#include "llvm/XRay/BlockIndexer.h"
Classes
struct Block
Public Types
using Index = DenseMap< std::pair< uint64_t, int32_t >, std::vector< Block > >
Public Member Functions
BlockIndexer (Index &I)
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Error flush ()
The flush() function will clear out the current state of the visitor, to allow for explicitly flushing a block's records to the currently recognized thread and process combination.
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
Definition at line 26 of file BlockIndexer.h.
Member Typedef Documentation
Index
using llvm::xray::BlockIndexer::Index = DenseMap<std::pair<uint64_t, int32_t>, std::vector<Block> >
Definition at line 36 of file BlockIndexer.h.
Constructor & Destructor Documentation
BlockIndexer()
llvm::xray::BlockIndexer::BlockIndexer (Index & I) inline explicit
Definition at line 44 of file BlockIndexer.h.
References flush(), and visit().
Member Function Documentation
flush()
Error llvm::xray::BlockIndexer::flush ()
The flush() function will clear out the current state of the visitor, to allow for explicitly flushing a block's records to the currently recognized thread and process combination.
Definition at line 82 of file BlockIndexer.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::xray::BlockIndexer::Block::ProcessID, llvm::xray::BlockIndexer::Block::Records, llvm::Error::success(), llvm::xray::BlockIndexer::Block::ThreadID, and llvm::xray::BlockIndexer::Block::WallclockTime.
Referenced by BlockIndexer(), and visit().
visit() [1/12]
Error llvm::xray::BlockIndexer::visit (BufferExtents &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 18 of file BlockIndexer.cpp.
References llvm::Error::success().
Referenced by BlockIndexer().
visit() [2/12]
Error llvm::xray::BlockIndexer::visit (WallclockRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 20 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, llvm::Error::success(), and llvm::xray::BlockIndexer::Block::WallclockTime.
visit() [3/12]
Error llvm::xray::BlockIndexer::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 26 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [4/12]
Error llvm::xray::BlockIndexer::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 31 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [5/12]
Error llvm::xray::BlockIndexer::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 36 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [6/12]
Error llvm::xray::BlockIndexer::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 51 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [7/12]
Error llvm::xray::BlockIndexer::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 56 of file BlockIndexer.cpp.
References llvm::xray::PIDRecord::pid(), llvm::xray::BlockIndexer::Block::ProcessID, llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [8/12]
Error llvm::xray::BlockIndexer::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 62 of file BlockIndexer.cpp.
References E, flush(), llvm::xray::BlockIndexer::Block::Records, llvm::Error::success(), llvm::xray::BlockIndexer::Block::ThreadID, and llvm::xray::NewBufferRecord::tid().
visit() [9/12]
Error llvm::xray::BlockIndexer::visit (EndBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 72 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [10/12]
Error llvm::xray::BlockIndexer::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 77 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [11/12]
Error llvm::xray::BlockIndexer::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 41 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
visit() [12/12]
Error llvm::xray::BlockIndexer::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 46 of file BlockIndexer.cpp.
References llvm::xray::BlockIndexer::Block::Records, and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/XRay/BlockIndexer.h
lib/XRay/BlockIndexer.cpp