LLVM: llvm::MipsCCState Class Reference
llvm::MipsCCState Class Reference
#include "Target/Mips/MipsCCState.h"
Public Types
enum SpecialCallingConvType { Mips16RetHelperConv, NoSpecialCallingConv }
Public Member Functions
MipsCCState (CallingConv::ID CC, bool isVarArg, MachineFunction &MF, SmallVectorImpl< CCValAssign > &locs, LLVMContext &C, SpecialCallingConvType SpecialCC=NoSpecialCallingConv)
void AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn, std::vector< TargetLowering::ArgListEntry > &FuncArgs, const char *Func)
void AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)=delete
void AnalyzeCallOperands (const SmallVectorImpl< MVT > &Outs, SmallVectorImpl< ISD::ArgFlagsTy > &Flags, CCAssignFn Fn)=delete
void AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
void AnalyzeCallResult (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn, const Type *RetTy, const char *Func)
void AnalyzeReturn (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
bool CheckReturn (const SmallVectorImpl< ISD::OutputArg > &ArgsFlags, CCAssignFn Fn)
bool WasOriginalArgF128 (unsigned ValNo)
bool WasOriginalArgFloat (unsigned ValNo)
bool WasOriginalArgVectorFloat (unsigned ValNo) const
bool WasOriginalRetVectorFloat (unsigned ValNo) const
bool IsCallOperandFixed (unsigned ValNo)
SpecialCallingConvType getSpecialCallingConv ()
Public Member Functions inherited from llvm::CCState
CCState (CallingConv::ID CC, bool isVarArg, MachineFunction &MF, SmallVectorImpl< CCValAssign > &locs, LLVMContext &C)
void addLoc (const CCValAssign &V)
LLVMContext & getContext () const
MachineFunction & getMachineFunction () const
CallingConv::ID getCallingConv () const
bool isVarArg () const
unsigned getNextStackOffset () const
getNextStackOffset - Return the next stack offset such that all stack slots satisfy their alignment requirements.
unsigned getAlignedCallFrameSize () const
getAlignedCallFrameSize - Return the size of the call frame needed to be able to store all arguments and such that the alignment requirement of each of the arguments is satisfied.
bool isAllocated (unsigned Reg) const
isAllocated - Return true if the specified register (or an alias) is allocated.
void AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
AnalyzeFormalArguments - Analyze an array of argument values, incorporating info about the formals into this state.
void AnalyzeArguments (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
The function will invoke AnalyzeFormalArguments.
void AnalyzeReturn (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
AnalyzeReturn - Analyze the returned values of a return, incorporating info about the result values into this state.
bool CheckReturn (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
CheckReturn - Analyze the return values of a function, returning true if the return can be performed without sret-demotion, and false otherwise.
void AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
AnalyzeCallOperands - Analyze the outgoing arguments to a call, incorporating info about the passed values into this state.
void AnalyzeCallOperands (SmallVectorImpl< MVT > &ArgVTs, SmallVectorImpl< ISD::ArgFlagsTy > &Flags, CCAssignFn Fn)
AnalyzeCallOperands - Same as above except it takes vectors of types and argument flags.
void AnalyzeArguments (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
The function will invoke AnalyzeCallOperands.
void AnalyzeCallResult (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
AnalyzeCallResult - Analyze the return values of a call, incorporating info about the passed values into this state.
bool IsShadowAllocatedReg (unsigned Reg) const
A shadow allocated register is a register that was allocated but wasn't added to the location list (Locs).
void AnalyzeCallResult (MVT VT, CCAssignFn Fn)
AnalyzeCallResult - Same as above except it's specialized for calls which produce a single value.
unsigned getFirstUnallocated (ArrayRef< MCPhysReg > Regs) const
getFirstUnallocated - Return the index of the first unallocated register in the set, or Regs.size() if they are all allocated.
unsigned AllocateReg (unsigned Reg)
AllocateReg - Attempt to allocate one register.
unsigned AllocateReg (unsigned Reg, unsigned ShadowReg)
Version of AllocateReg with extra register to be shadowed.
unsigned AllocateReg (ArrayRef< MCPhysReg > Regs)
AllocateReg - Attempt to allocate one of the specified registers.
unsigned AllocateRegBlock (ArrayRef< MCPhysReg > Regs, unsigned RegsRequired)
AllocateRegBlock - Attempt to allocate a block of RegsRequired consecutive registers.
unsigned AllocateReg (ArrayRef< MCPhysReg > Regs, const MCPhysReg *ShadowRegs)
Version of AllocateReg with list of registers to be shadowed.
unsigned AllocateStack (unsigned Size, unsigned Alignment)
AllocateStack - Allocate a chunk of stack space with the specified size and alignment.
void ensureMaxAlignment (Align Alignment)
unsigned AllocateStack (unsigned Size, unsigned Align, unsigned ShadowReg)
Version of AllocateStack with extra register to be shadowed.
unsigned AllocateStack (unsigned Size, unsigned Align, ArrayRef< MCPhysReg > ShadowRegs)
Version of AllocateStack with list of extra registers to be shadowed.
void HandleByVal (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, int MinSize, int MinAlign, ISD::ArgFlagsTy ArgFlags)
Allocate space on the stack large enough to pass an argument by value.
unsigned getInRegsParamsCount () const
unsigned getInRegsParamsProcessed () const
void getInRegsParamInfo (unsigned InRegsParamRecordIndex, unsigned &BeginReg, unsigned &EndReg) const
void addInRegsParamInfo (unsigned RegBegin, unsigned RegEnd)
bool nextInRegsParam ()
void clearByValRegsInfo ()
void rewindByValRegsInfo ()
SmallVectorImpl< CCValAssign > & getPendingLocs ()
SmallVectorImpl< ISD::ArgFlagsTy > & getPendingArgFlags ()
void getRemainingRegParmsForType (SmallVectorImpl< MCPhysReg > &Regs, MVT VT, CCAssignFn Fn)
Compute the remaining unused register parameters that would be used for the given value type.
void analyzeMustTailForwardedRegisters (SmallVectorImpl< ForwardedRegister > &Forwards, ArrayRef< MVT > RegParmTypes, CCAssignFn Fn)
Compute the set of registers that need to be preserved and forwarded to any musttail calls.
template<class T >
void AnalyzeArgumentsSecondPass (const SmallVectorImpl< T > &Args, CCAssignFn Fn)
The function runs an additional analysis pass over function arguments.
Static Public Member Functions
static SpecialCallingConvType getSpecialCallingConvForCallee (const SDNode *Callee, const MipsSubtarget &Subtarget)
Determine the SpecialCallingConvType for the given callee.
Static Public Member Functions inherited from llvm::CCState
static bool resultsCompatible (CallingConv::ID CalleeCC, CallingConv::ID CallerCC, MachineFunction &MF, LLVMContext &C, const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn CalleeFn, CCAssignFn CallerFn)
Returns true if the results of the two calling conventions are compatible.
Detailed Description
Definition at line 20 of file MipsCCState.h.
Member Enumeration Documentation
SpecialCallingConvType
enum llvm::MipsCCState::SpecialCallingConvType
Enumerator
Mips16RetHelperConv
NoSpecialCallingConv
Definition at line 22 of file MipsCCState.h.
Constructor & Destructor Documentation
MipsCCState()
llvm::MipsCCState::MipsCCState (CallingConv::ID CC, bool isVarArg, MachineFunction & MF, SmallVectorImpl< CCValAssign > & locs, LLVMContext & C, SpecialCallingConvType SpecialCC = NoSpecialCallingConv) inline
Definition at line 83 of file MipsCCState.h.
Member Function Documentation
AnalyzeCallOperands() [1/3]
void llvm::MipsCCState::AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > & Outs, CCAssignFn Fn, std::vector< TargetLowering::ArgListEntry > & FuncArgs, const char * Func) inline
Definition at line 89 of file MipsCCState.h.
References llvm::CCState::AnalyzeCallOperands(), and llvm::SmallVectorImpl< T >::clear().
AnalyzeCallOperands() [2/3]
void llvm::MipsCCState::AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > & Outs, CCAssignFn Fn) delete
AnalyzeCallOperands() [3/3]
void llvm::MipsCCState::AnalyzeCallOperands (const SmallVectorImpl< MVT > & Outs, SmallVectorImpl< ISD::ArgFlagsTy > & Flags, CCAssignFn Fn) delete
AnalyzeCallResult()
void llvm::MipsCCState::AnalyzeCallResult (const SmallVectorImpl< ISD::InputArg > & Ins, CCAssignFn Fn, const Type * RetTy, const char * Func) inline
Definition at line 119 of file MipsCCState.h.
References llvm::CCState::AnalyzeCallResult(), and llvm::SmallVectorImpl< T >::clear().
AnalyzeFormalArguments()
void llvm::MipsCCState::AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > & Ins, CCAssignFn Fn) inline
Definition at line 110 of file MipsCCState.h.
References llvm::CCState::AnalyzeFormalArguments(), and llvm::SmallVectorImpl< T >::clear().
AnalyzeReturn()
void llvm::MipsCCState::AnalyzeReturn (const SmallVectorImpl< ISD::OutputArg > & Outs, CCAssignFn Fn) inline
Definition at line 130 of file MipsCCState.h.
References llvm::CCState::AnalyzeReturn(), and llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::MipsCallLowering::lowerReturn(), and UnpackFromArgumentSlot().
CheckReturn()
bool llvm::MipsCCState::CheckReturn (const SmallVectorImpl< ISD::OutputArg > & ArgsFlags, CCAssignFn Fn) inline
Definition at line 140 of file MipsCCState.h.
References llvm::CCState::CheckReturn(), llvm::SmallVectorImpl< T >::clear(), and llvm::MCID::Return.
Referenced by UnpackFromArgumentSlot().
getSpecialCallingConv()
SpecialCallingConvType llvm::MipsCCState::getSpecialCallingConv () inline
Definition at line 162 of file MipsCCState.h.
getSpecialCallingConvForCallee()
MipsCCState::SpecialCallingConvType MipsCCState::getSpecialCallingConvForCallee (const SDNode * Callee, const MipsSubtarget & Subtarget) static
Determine the SpecialCallingConvType for the given callee.
Definition at line 70 of file MipsCCState.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_size(), llvm::ISD::OutputArg::ArgVT, assert(), F(), G, llvm::MachineFunction::getFunction(), llvm::CCState::getMachineFunction(), llvm::Function::getReturnType(), llvm::Value::getType(), llvm::Function::hasFnAttribute(), llvm::MipsSubtarget::inMips16HardFloat(), llvm::MipsISD::Ins, llvm::Type::isFloatingPointTy(), llvm::Type::isVectorTy(), Mips16RetHelperConv, NoSpecialCallingConv, originalEVTTypeIsVectorFloat(), originalTypeIsF128(), originalTypeIsVectorFloat(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::size(), and llvm::TargetLoweringBase::ArgListEntry::Ty.
IsCallOperandFixed()
bool llvm::MipsCCState::IsCallOperandFixed (unsigned ValNo) inline
Definition at line 161 of file MipsCCState.h.
WasOriginalArgF128()
bool llvm::MipsCCState::WasOriginalArgF128 (unsigned ValNo) inline
Definition at line 151 of file MipsCCState.h.
WasOriginalArgFloat()
bool llvm::MipsCCState::WasOriginalArgFloat (unsigned ValNo) inline
Definition at line 152 of file MipsCCState.h.
WasOriginalArgVectorFloat()
bool llvm::MipsCCState::WasOriginalArgVectorFloat (unsigned ValNo) const inline
Definition at line 155 of file MipsCCState.h.
Referenced by CC_MipsO32().
WasOriginalRetVectorFloat()
bool llvm::MipsCCState::WasOriginalRetVectorFloat (unsigned ValNo) const inline
Definition at line 158 of file MipsCCState.h.
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsCCState.h
lib/Target/Mips/MipsCCState.cpp