LLVM: llvm::OProfileWrapper Class Reference
llvm::OProfileWrapper Class Reference
#include "llvm/ExecutionEngine/OProfileWrapper.h"
Public Member Functions
OProfileWrapper ()
OProfileWrapper (op_open_agent_ptr_t OpenAgentImpl, op_close_agent_ptr_t CloseAgentImpl, op_write_native_code_ptr_t WriteNativeCodeImpl, op_write_debug_line_info_ptr_t WriteDebugLineInfoImpl, op_unload_native_code_ptr_t UnloadNativeCodeImpl, op_major_version_ptr_t MajorVersionImpl, op_major_version_ptr_t MinorVersionImpl, IsOProfileRunningPtrT MockIsOProfileRunningImpl=0)
bool op_open_agent ()
int op_close_agent ()
int op_write_native_code (const char *name, uint64_t addr, void const *code, const unsigned int size)
int op_write_debug_line_info (void const *code, size_t num_entries, struct debug_line_info const *info)
int op_unload_native_code (uint64_t addr)
int op_major_version ()
int op_minor_version ()
bool isAgentAvailable ()
Detailed Description
Definition at line 28 of file OProfileWrapper.h.
Constructor & Destructor Documentation
OProfileWrapper() [1/2]
llvm::OProfileWrapper::OProfileWrapper ()
Definition at line 40 of file OProfileWrapper.cpp.
References llvm::dbgs(), error, LLVM_DEBUG, llvm::sys::DynamicLibrary::LoadLibraryPermanently(), and llvm::sys::DynamicLibrary::SearchForAddressOfSymbol().
OProfileWrapper() [2/2]
llvm::OProfileWrapper::OProfileWrapper (op_open_agent_ptr_t OpenAgentImpl, op_close_agent_ptr_t CloseAgentImpl, op_write_native_code_ptr_t WriteNativeCodeImpl, op_write_debug_line_info_ptr_t WriteDebugLineInfoImpl, op_unload_native_code_ptr_t UnloadNativeCodeImpl, op_major_version_ptr_t MajorVersionImpl, op_major_version_ptr_t MinorVersionImpl, IsOProfileRunningPtrT MockIsOProfileRunningImpl = 0) inline
Definition at line 66 of file OProfileWrapper.h.
References info, initialize(), isAgentAvailable(), name, op_close_agent(), op_major_version(), op_minor_version(), op_open_agent(), op_unload_native_code(), op_write_debug_line_info(), op_write_native_code(), and llvm::size().
Member Function Documentation
isAgentAvailable()
bool llvm::OProfileWrapper::isAgentAvailable ()
Definition at line 207 of file OProfileWrapper.cpp.
Referenced by OProfileWrapper().
op_close_agent()
int llvm::OProfileWrapper::op_close_agent ()
Definition at line 193 of file OProfileWrapper.cpp.
References initialize().
Referenced by OProfileWrapper().
op_major_version()
int llvm::OProfileWrapper::op_major_version ()
Definition at line 237 of file OProfileWrapper.cpp.
References initialize().
Referenced by OProfileWrapper().
op_minor_version()
int llvm::OProfileWrapper::op_minor_version ()
Definition at line 247 of file OProfileWrapper.cpp.
References initialize().
Referenced by OProfileWrapper().
op_open_agent()
bool llvm::OProfileWrapper::op_open_agent ()
Definition at line 181 of file OProfileWrapper.cpp.
References initialize().
Referenced by OProfileWrapper().
op_unload_native_code()
int llvm::OProfileWrapper::op_unload_native_code (uint64_t addr)
Definition at line 257 of file OProfileWrapper.cpp.
References initialize().
Referenced by OProfileWrapper().
op_write_debug_line_info()
int llvm::OProfileWrapper::op_write_debug_line_info (void const * code, size_t num_entries, struct debug_line_info const * info)
Definition at line 224 of file OProfileWrapper.cpp.
References initialize().
Referenced by OProfileWrapper().
op_write_native_code()
int llvm::OProfileWrapper::op_write_native_code (const char * name, uint64_t addr, void const * code, const unsigned int size)
Definition at line 211 of file OProfileWrapper.cpp.
References initialize().
Referenced by OProfileWrapper().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/OProfileWrapper.h
lib/ExecutionEngine/OProfileJIT/OProfileWrapper.cpp