LLVM: llvm::json::ObjectKey Class Reference
llvm::json::ObjectKey Class Reference
ObjectKey is a used to capture keys in Object.
#include "llvm/Support/JSON.h"
Public Member Functions
ObjectKey (const char *S)
ObjectKey (std::string S)
ObjectKey (llvm::StringRef S)
ObjectKey (const llvm::SmallVectorImpl< char > &V)
ObjectKey (const llvm::formatv_object_base &V)
ObjectKey (const ObjectKey &C)
ObjectKey (ObjectKey &&C)
ObjectKey & operator= (const ObjectKey &C)
ObjectKey & operator= (ObjectKey &&)=default
operator llvm::StringRef () const
std::string str () const
Detailed Description
ObjectKey is a used to capture keys in Object.
Like Value but:
only strings are allowed
it's optimized for the string literal case (Owned == nullptr) Like Value, strings must be UTF-8. See isUTF8 documentation for details.
Definition at line 492 of file JSON.h.
Constructor & Destructor Documentation
ObjectKey() [1/7]
llvm::json::ObjectKey::ObjectKey (const char * S) inline
Definition at line 494 of file JSON.h.
ObjectKey() [2/7]
llvm::json::ObjectKey::ObjectKey (std::string S) inline
Definition at line 495 of file JSON.h.
References assert(), llvm::Data, llvm::json::fixUTF8(), llvm::json::isUTF8(), LLVM_UNLIKELY, and string.
ObjectKey() [3/7]
llvm::json::ObjectKey::ObjectKey (llvm::StringRef S) inline
Definition at line 502 of file JSON.h.
References assert(), llvm::Data, llvm::json::fixUTF8(), llvm::json::isUTF8(), and LLVM_UNLIKELY.
ObjectKey() [4/7]
llvm::json::ObjectKey::ObjectKey (const llvm::SmallVectorImpl< char > & V) inline
Definition at line 508 of file JSON.h.
References string.
ObjectKey() [5/7]
llvm::json::ObjectKey::ObjectKey (const llvm::formatv_object_base & V) inline
Definition at line 510 of file JSON.h.
ObjectKey() [6/7]
llvm::json::ObjectKey::ObjectKey (const ObjectKey & C) inline
Definition at line 512 of file JSON.h.
References C.
ObjectKey() [7/7]
llvm::json::ObjectKey::ObjectKey (ObjectKey && C) inline
Definition at line 513 of file JSON.h.
Member Function Documentation
operator llvm::StringRef()
llvm::json::ObjectKey::operator llvm::StringRef () const inline
Definition at line 525 of file JSON.h.
References llvm::Data.
operator=() [1/2]
ObjectKey& llvm::json::ObjectKey::operator= (const ObjectKey & C) inline
Definition at line 514 of file JSON.h.
References llvm::Data.
operator=() [2/2]
ObjectKey& llvm::json::ObjectKey::operator= (ObjectKey &&) default
str()
std::string llvm::json::ObjectKey::str () const inline
Definition at line 526 of file JSON.h.
References llvm::Data.
The documentation for this class was generated from the following file:
include/llvm/Support/JSON.h