LLVM: llvm::raw_svector_ostream Class Reference
llvm::raw_svector_ostream Class Reference
A raw_ostream that writes to an SmallVector or SmallString.
#include "llvm/Support/raw_ostream.h"
Public Member Functions
raw_svector_ostream (SmallVectorImpl< char > &O)
Construct a new raw_svector_ostream.
~raw_svector_ostream () override=default
void flush ()=delete
StringRef str ()
Return a StringRef for the vector contents.
Public Member Functions inherited from llvm::raw_pwrite_stream
raw_pwrite_stream (bool Unbuffered=false)
void pwrite (const char *Ptr, size_t Size, uint64_t Offset)
Public Member Functions inherited from llvm::raw_ostream
raw_ostream (bool unbuffered=false)
raw_ostream (const raw_ostream &)=delete
void operator= (const raw_ostream &)=delete
virtual ~raw_ostream ()
uint64_t tell () const
tell - Return the current offset with the file.
void SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
void SetBufferSize (size_t Size)
Set the stream to be buffered, using the specified buffer size.
size_t GetBufferSize () const
void SetUnbuffered ()
Set the stream to be unbuffered.
size_t GetNumBytesInBuffer () const
void flush ()
raw_ostream & operator<< (char C)
raw_ostream & operator<< (unsigned char C)
raw_ostream & operator<< (signed char C)
raw_ostream & operator<< (StringRef Str)
raw_ostream & operator<< (const char *Str)
raw_ostream & operator<< (const std::string &Str)
raw_ostream & operator<< (const SmallVectorImpl< char > &Str)
raw_ostream & operator<< (unsigned long N)
raw_ostream & operator<< (long N)
raw_ostream & operator<< (unsigned long long N)
raw_ostream & operator<< (long long N)
raw_ostream & operator<< (const void *P)
raw_ostream & operator<< (unsigned int N)
raw_ostream & operator<< (int N)
raw_ostream & operator<< (double N)
raw_ostream & write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
raw_ostream & operator<< (Colors C)
raw_ostream & write_uuid (const uuid_t UUID)
raw_ostream & write_escaped (StringRef Str, bool UseHexEscapes=false)
Output Str, turning '\', '', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
raw_ostream & write (unsigned char C)
raw_ostream & write (const char *Ptr, size_t Size)
raw_ostream & operator<< (const format_object_base &Fmt)
raw_ostream & operator<< (const FormattedString &)
raw_ostream & operator<< (const FormattedNumber &)
raw_ostream & operator<< (const formatv_object_base &)
raw_ostream & operator<< (const FormattedBytes &)
raw_ostream & indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
raw_ostream & write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
virtual raw_ostream & changeColor (enum Colors Color, bool Bold=false, bool BG=false)
Changes the foreground color of text that will be output from this point forward.
virtual raw_ostream & resetColor ()
Resets the colors to terminal defaults.
virtual raw_ostream & reverseColor ()
Reverses the foreground and background colors.
virtual bool is_displayed () const
This function determines if this stream is connected to a "tty" or "console" window.
virtual bool has_colors () const
This function determines if this stream is displayed and supports colors.
virtual void enable_colors (bool)
Additional Inherited Members
Public Types inherited from llvm::raw_ostream
enum Colors {
Colors::BLACK = 0, Colors::RED, Colors::GREEN, Colors::YELLOW,
Colors::BLUE, Colors::MAGENTA, Colors::CYAN, Colors::WHITE,
Colors::SAVEDCOLOR, Colors::RESET
}
using uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Static Public Attributes inherited from llvm::raw_ostream
static const Colors BLACK = Colors::BLACK
static const Colors RED = Colors::RED
static const Colors GREEN = Colors::GREEN
static const Colors YELLOW = Colors::YELLOW
static const Colors BLUE = Colors::BLUE
static const Colors MAGENTA = Colors::MAGENTA
static const Colors CYAN = Colors::CYAN
static const Colors WHITE = Colors::WHITE
static const Colors SAVEDCOLOR = Colors::SAVEDCOLOR
static const Colors RESET = Colors::RESET
Protected Member Functions inherited from llvm::raw_ostream
void SetBuffer (char *BufferStart, size_t Size)
Use the provided buffer as the raw_ostream buffer.
virtual size_t preferred_buffer_size () const
Return an efficient buffer size for the underlying output mechanism.
const char * getBufferStart () const
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Detailed Description
A raw_ostream that writes to an SmallVector or SmallString.
This is a simple adaptor class. This class does not encounter output errors. raw_svector_ostream operates without a buffer, delegating all memory management to the SmallString. Thus the SmallString is always up-to-date, may be used directly and there is no need to call flush().
Definition at line 543 of file raw_ostream.h.
Constructor & Destructor Documentation
raw_svector_ostream()
llvm::raw_svector_ostream::raw_svector_ostream (SmallVectorImpl< char > & O) inline explicit
Construct a new raw_svector_ostream.
Parameters
O The vector to write to; this should generally have at least 128 bytes free to avoid any extraneous memory overhead.
Definition at line 559 of file raw_ostream.h.
~raw_svector_ostream()
llvm::raw_svector_ostream::~raw_svector_ostream () override default
Member Function Documentation
flush()
void llvm::raw_svector_ostream::flush () delete
str()
StringRef llvm::raw_svector_ostream::str () inline
Return a StringRef for the vector contents.
Definition at line 568 of file raw_ostream.h.
References llvm::SmallVectorTemplateCommon< T, typename >::data(), and llvm::SmallVectorBase::size().
Referenced by llvm::ModuloScheduleTestAnnotater::annotate(), llvm::ComputeASanStackFrameDescription(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::MCDwarfLineAddr::Emit(), llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), emitDebugLabelComment(), emitDebugValueComment(), EmitGCCInlineAsmStr(), llvm::AsmPrinter::emitImplicitDef(), llvm::MCTargetStreamer::emitRawBytes(), llvm::MCStreamer::EmitSLEB128IntValue(), llvm::MCStreamer::EmitULEB128IntValue(), llvm::MCTargetStreamer::emitValue(), llvm::opt::Arg::getAsString(), llvm::ExecutionEngine::getConstantValue(), getFixupKindSize(), getGNUBinOpPrecedence(), getItaniumTypeName(), llvm::AMDGPUMangledLibFunc::getName(), getOpenCLAlignment(), getPrefixes(), isOperator(), LLVMDisasmInstruction(), LLVMTargetMachineEmitToMemoryBuffer(), llvm::ExecutionEngine::LoadValueFromMemory(), mangleTLIName(), printDwarfFileDirective(), printFPOReg(), llvm::Pattern::printSubstitutions(), llvm::ARMAsmBackend::relaxInstruction(), llvm::opt::Arg::render(), llvm::report_fatal_error(), llvm::NVPTXAsmPrinter::runOnMachineFunction(), llvm::StructType::setName(), llvm::UpgradeSectionAttributes(), VisitGlobalVariableForEmission(), and llvm::yaml::yaml2ObjectFile().
The documentation for this class was generated from the following files:
include/llvm/Support/raw_ostream.h
lib/Support/raw_ostream.cpp