LLVM: llvm::R600TTIImpl Class Reference
llvm::R600TTIImpl Class Reference final
#include "Target/AMDGPU/AMDGPUTargetTransformInfo.h"
Public Member Functions
R600TTIImpl (const AMDGPUTargetMachine *TM, const Function &F)
const R600Subtarget * getST () const
const AMDGPUTargetLowering * getTLI () const
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
unsigned getHardwareNumberOfRegisters (bool Vec) const
unsigned getNumberOfRegisters (bool Vec) const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth () const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeMemChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getCFInstrCost (unsigned Opcode)
int getVectorInstrCost (unsigned Opcode, Type *ValTy, unsigned Index)
Public Member Functions inherited from llvm::BasicTTIImplBase< R600TTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast) const
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
bool shouldBuildLookupTables ()
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI)
int getInstructionLatency (const Instruction *I)
virtual Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
virtual Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
virtual unsigned getCacheLineSize () const
virtual unsigned getPrefetchDistance () const
virtual unsigned getMinPrefetchStride () const
virtual unsigned getMaxPrefetchIterationsAhead () const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
Estimate the overhead of scalarizing an instruction.
unsigned getScalarizationOverhead (Type *VecTy, ArrayRef< const Value * > Args)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
Estimate the overhead of scalarizing an instructions unique non-constant operands.
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >(), const Instruction *CxtI=nullptr)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF=1)
Get intrinsic cost based on arguments.
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=std::numeric_limits< unsigned >::max())
Get intrinsic cost based on argument types.
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned Opcode, Type *Ty, bool IsPairwise)
Try to calculate arithmetic and shuffle op costs for reduction operations.
unsigned getMinMaxReductionCost (Type *Ty, Type *CondTy, bool IsPairwise, bool)
Try to calculate op costs for min/max reduction operations.
unsigned getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< R600TTIImpl >
unsigned getCallCost (const Function *F, int NumArgs, const User *U)
unsigned getCallCost (const Function *F, ArrayRef< const Value * > Arguments, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getUserCost (const User *U, ArrayRef< const Value * > Operands)
int getInstructionLatency (const Instruction *I)
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value *> Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
unsigned getMemcpyCost (const Instruction *I)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &)
bool isLegalAddImmediate (int64_t Imm)
bool isLegalICmpImmediate (int64_t Imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2)
bool canMacroFuseCmp ()
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo)
bool shouldFavorPostInc () const
bool shouldFavorBackedgeIndex (const Loop *L) const
bool isLegalMaskedStore (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedLoad (Type *DataType, MaybeAlign Alignment)
bool isLegalNTStore (Type *DataType, Align Alignment)
bool isLegalNTLoad (Type *DataType, Align Alignment)
bool isLegalMaskedScatter (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedGather (Type *DataType, MaybeAlign Alignment)
bool isLegalMaskedCompressStore (Type *DataType)
bool isLegalMaskedExpandLoad (Type *DataType)
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace)
bool prefersVectorizedAddressing ()
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool LSRWithInstrQueries ()
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA ()
bool isTypeLegal (Type *Ty)
bool shouldBuildLookupTables ()
bool shouldBuildLookupTablesForConstant (Constant *C)
bool useColdCCForColdCall (Function &F)
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value *> Args, unsigned VF)
bool supportsEfficientVectorElementLoadStore ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization ()
bool enableMaskedInterleavedAccessVectorization ()
bool isFPVectorizationPotentiallyUnsafe ()
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast)
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit)
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
int getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth ()
bool shouldMaximizeVectorBandwidth (bool OptSize) const
unsigned getMinimumVF (unsigned ElemWidth) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader)
unsigned getCacheLineSize () const
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride () const
unsigned getMaxPrefetchIterationsAhead () const
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value *> Args, const Instruction *CxtI=nullptr)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Ty, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, const Instruction *I)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type *> Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value *> Args, FastMathFlags FMF, unsigned VF)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type *> Tys)
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned, Type *, bool)
unsigned getMinMaxReductionCost (Type *, Type *, bool, bool)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type *> Tys)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type *> &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument *> &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool useReductionIntrinsic (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< R600TTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
virtual ~BasicTTIImplBase ()=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< R600TTIImpl >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned)
bool isStridedAccess (const SCEV *Ptr)
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr)
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance)
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 233 of file AMDGPUTargetTransformInfo.h.
Constructor & Destructor Documentation
R600TTIImpl()
llvm::R600TTIImpl::R600TTIImpl (const AMDGPUTargetMachine * TM, const Function & F) inline explicit
Definition at line 244 of file AMDGPUTargetTransformInfo.h.
Member Function Documentation
getCFInstrCost()
unsigned R600TTIImpl::getCFInstrCost (unsigned Opcode)
Definition at line 935 of file AMDGPUTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCFInstrCost(), and llvm::MipsISD::Ret.
getHardwareNumberOfRegisters()
unsigned R600TTIImpl::getHardwareNumberOfRegisters (bool Vec) const
Definition at line 871 of file AMDGPUTargetTransformInfo.cpp.
getLoadStoreVecRegBitWidth()
unsigned R600TTIImpl::getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
Definition at line 887 of file AMDGPUTargetTransformInfo.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_BUFFER_0, AMDGPUAS::CONSTANT_BUFFER_15, AMDGPUAS::GLOBAL_ADDRESS, llvm_unreachable, AMDGPUAS::LOCAL_ADDRESS, AMDGPUAS::PARAM_D_ADDRESS, AMDGPUAS::PARAM_I_ADDRESS, AMDGPUAS::PRIVATE_ADDRESS, and AMDGPUAS::REGION_ADDRESS.
getMaxInterleaveFactor()
unsigned R600TTIImpl::getMaxInterleaveFactor (unsigned VF)
Definition at line 926 of file AMDGPUTargetTransformInfo.cpp.
getMinVectorRegisterBitWidth()
unsigned R600TTIImpl::getMinVectorRegisterBitWidth () const
Definition at line 883 of file AMDGPUTargetTransformInfo.cpp.
getNumberOfRegisters()
unsigned R600TTIImpl::getNumberOfRegisters (bool Vec) const
Definition at line 875 of file AMDGPUTargetTransformInfo.cpp.
getRegisterBitWidth()
unsigned R600TTIImpl::getRegisterBitWidth (bool Vector) const
Definition at line 879 of file AMDGPUTargetTransformInfo.cpp.
getST()
const R600Subtarget* llvm::R600TTIImpl::getST () const inline
Definition at line 250 of file AMDGPUTargetTransformInfo.h.
getTLI()
const AMDGPUTargetLowering* llvm::R600TTIImpl::getTLI () const inline
Definition at line 251 of file AMDGPUTargetTransformInfo.h.
References llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCFInstrCost(), llvm::TargetTransformInfoImplBase::getLoadStoreVecRegBitWidth(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMaxInterleaveFactor(), llvm::TargetTransformInfoImplBase::getMinVectorRegisterBitWidth(), llvm::TargetTransformInfoImplBase::getNumberOfRegisters(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getRegisterBitWidth(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getVectorInstrCost(), llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoadChain(), llvm::TargetTransformInfoImplBase::isLegalToVectorizeStoreChain(), and llvm::Vector.
getUnrollingPreferences()
void R600TTIImpl::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP)
Definition at line 969 of file AMDGPUTargetTransformInfo.cpp.
getVectorInstrCost()
int R600TTIImpl::getVectorInstrCost (unsigned Opcode, Type * ValTy, unsigned Index)
Definition at line 946 of file AMDGPUTargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::DL, llvm::DataLayout::getTypeSizeInBits(), and llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getVectorInstrCost().
isLegalToVectorizeLoadChain()
bool R600TTIImpl::isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
Definition at line 914 of file AMDGPUTargetTransformInfo.cpp.
isLegalToVectorizeMemChain()
bool R600TTIImpl::isLegalToVectorizeMemChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
Definition at line 905 of file AMDGPUTargetTransformInfo.cpp.
References AMDGPUAS::PRIVATE_ADDRESS.
isLegalToVectorizeStoreChain()
bool R600TTIImpl::isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
Definition at line 920 of file AMDGPUTargetTransformInfo.cpp.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUTargetTransformInfo.h
lib/Target/AMDGPU/AMDGPUTargetTransformInfo.cpp