LLVM: llvm::Resolver Class Reference
llvm::Resolver Class Reference abstract
Interface for looking up the initializer for a variable name, used by Init::resolveReferences.
#include "llvm/TableGen/Record.h"
Public Member Functions
Resolver (Record *CurRec)
virtual ~Resolver ()
Record * getCurrentRecord () const
virtual Init * resolve (Init *VarName)=0
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
virtual bool keepUnsetBits () const
bool isFinal () const
void setFinal (bool Final)
Detailed Description
Interface for looking up the initializer for a variable name, used by Init::resolveReferences.
Definition at line 1870 of file Record.h.
Constructor & Destructor Documentation
Resolver()
llvm::Resolver::Resolver (Record * CurRec) inline explicit
Definition at line 1875 of file Record.h.
~Resolver()
virtual llvm::Resolver::~Resolver () inline virtual
Definition at line 1876 of file Record.h.
Member Function Documentation
getCurrentRecord()
Record* llvm::Resolver::getCurrentRecord () const inline
Definition at line 1878 of file Record.h.
References llvm::tgtok::VarName.
Referenced by llvm::UnOpInit::resolveReferences(), llvm::BinOpInit::resolveReferences(), llvm::TernOpInit::resolveReferences(), llvm::CondOpInit::resolveReferences(), and llvm::FieldInit::resolveReferences().
isFinal()
bool llvm::Resolver::isFinal () const inline
Definition at line 1892 of file Record.h.
Referenced by llvm::UnOpInit::resolveReferences(), and llvm::ShadowResolver::ShadowResolver().
keepUnsetBits()
virtual bool llvm::Resolver::keepUnsetBits () const inline virtual
Reimplemented in llvm::RecordResolver.
Definition at line 1887 of file Record.h.
Referenced by llvm::BitsInit::resolveReferences().
resolve()
virtual Init* llvm::Resolver::resolve (Init * VarName) pure virtual
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Implemented in llvm::HasReferenceResolver, llvm::TrackUnresolvedResolver, llvm::ShadowResolver, llvm::RecordValResolver, llvm::RecordResolver, and llvm::MapResolver.
Referenced by llvm::VarInit::resolveReferences().
setFinal()
void llvm::Resolver::setFinal (bool Final) inline
Definition at line 1894 of file Record.h.
Referenced by llvm::Record::resolveReferences().
The documentation for this class was generated from the following file:
include/llvm/TableGen/Record.h