LLVM: llvm::DGEdge< NodeType, EdgeType > Class Template Reference
llvm::DGEdge< NodeType, EdgeType > Class Template Reference
Represent an edge in the directed graph.
#include "llvm/ADT/DirectedGraph.h"
Public Member Functions
DGEdge ()=delete
DGEdge (NodeType &N)
Create an edge pointing to the given node N.
DGEdge (const DGEdge< NodeType, EdgeType > &E)
DGEdge< NodeType, EdgeType > & operator= (const DGEdge< NodeType, EdgeType > &E)
bool operator== (const EdgeType &E) const
Static polymorphism: delegate implementation (via isEqualTo) to the derived class.
bool operator!= (const EdgeType &E) const
const NodeType & getTargetNode () const
Retrieve the target node this edge connects to.
NodeType & getTargetNode ()
void setTargetNode (const NodeType &N)
Set the target node this edge connects to.
Protected Member Functions
bool isEqualTo (const EdgeType &E) const
EdgeType & getDerived ()
const EdgeType & getDerived () const
Protected Attributes
NodeType & TargetNode
Detailed Description
template<class NodeType, class EdgeType>
class llvm::DGEdge< NodeType, EdgeType >
Represent an edge in the directed graph.
The edge contains the target node it connects to.
Definition at line 27 of file DirectedGraph.h.
Constructor & Destructor Documentation
DGEdge() [1/3]
template<class NodeType, class EdgeType> llvm::DGEdge< NodeType, EdgeType >::DGEdge () delete
DGEdge() [2/3]
template<class NodeType, class EdgeType> llvm::DGEdge< NodeType, EdgeType >::DGEdge (NodeType & N) inline explicit
Create an edge pointing to the given node N.
Definition at line 31 of file DirectedGraph.h.
DGEdge() [3/3]
template<class NodeType, class EdgeType> llvm::DGEdge< NodeType, EdgeType >::DGEdge (const DGEdge< NodeType, EdgeType > & E) inline explicit
Definition at line 32 of file DirectedGraph.h.
Member Function Documentation
getDerived() [1/2]
template<class NodeType, class EdgeType> EdgeType& llvm::DGEdge< NodeType, EdgeType >::getDerived () inline protected
Definition at line 59 of file DirectedGraph.h.
Referenced by llvm::DGEdge< NodeType, EdgeType >::operator==(), and llvm::DGNode< NodeType, EdgeType >::operator==().
getDerived() [2/2]
template<class NodeType, class EdgeType> const EdgeType& llvm::DGEdge< NodeType, EdgeType >::getDerived () const inline protected
Definition at line 60 of file DirectedGraph.h.
getTargetNode() [1/2]
template<class NodeType, class EdgeType> const NodeType& llvm::DGEdge< NodeType, EdgeType >::getTargetNode () const inline
Retrieve the target node this edge connects to.
Definition at line 45 of file DirectedGraph.h.
References llvm::DGEdge< NodeType, EdgeType >::TargetNode.
Referenced by llvm::GraphTraits< DDGNode * >::DDGGetTargetNode(), llvm::GraphTraits< const DDGNode * >::DDGGetTargetNode(), llvm::DGEdge< NodeType, EdgeType >::getTargetNode(), and llvm::operator<<().
getTargetNode() [2/2]
template<class NodeType, class EdgeType> NodeType& llvm::DGEdge< NodeType, EdgeType >::getTargetNode () inline
Definition at line 46 of file DirectedGraph.h.
References llvm::DGEdge< NodeType, EdgeType >::getTargetNode().
isEqualTo()
template<class NodeType, class EdgeType> bool llvm::DGEdge< NodeType, EdgeType >::isEqualTo (const EdgeType & E) const inline protected
Definition at line 56 of file DirectedGraph.h.
References E.
operator!=()
template<class NodeType, class EdgeType> bool llvm::DGEdge< NodeType, EdgeType >::operator!= (const EdgeType & E) const inline
Definition at line 42 of file DirectedGraph.h.
References llvm::DGEdge< NodeType, EdgeType >::operator==().
operator=()
template<class NodeType, class EdgeType> DGEdge<NodeType, EdgeType>& llvm::DGEdge< NodeType, EdgeType >::operator= (const DGEdge< NodeType, EdgeType > & E) inline
Definition at line 34 of file DirectedGraph.h.
References llvm::DGEdge< NodeType, EdgeType >::TargetNode.
Referenced by llvm::DDGEdge::operator=().
operator==()
template<class NodeType, class EdgeType> bool llvm::DGEdge< NodeType, EdgeType >::operator== (const EdgeType & E) const inline
Static polymorphism: delegate implementation (via isEqualTo) to the derived class.
Definition at line 41 of file DirectedGraph.h.
References llvm::DGEdge< NodeType, EdgeType >::getDerived().
Referenced by llvm::DGEdge< NodeType, EdgeType >::operator!=(), and llvm::DGNode< NodeType, EdgeType >::operator!=().
setTargetNode()
template<class NodeType, class EdgeType> void llvm::DGEdge< NodeType, EdgeType >::setTargetNode (const NodeType & N) inline
Set the target node this edge connects to.
Definition at line 52 of file DirectedGraph.h.
References N, and llvm::DGEdge< NodeType, EdgeType >::TargetNode.
Member Data Documentation
TargetNode
template<class NodeType, class EdgeType> NodeType& llvm::DGEdge< NodeType, EdgeType >::TargetNode protected
Definition at line 65 of file DirectedGraph.h.
Referenced by llvm::DGEdge< NodeType, EdgeType >::getTargetNode(), llvm::DGEdge< NodeType, EdgeType >::operator=(), and llvm::DGEdge< NodeType, EdgeType >::setTargetNode().
The documentation for this class was generated from the following file:
include/llvm/ADT/DirectedGraph.h