LLVM: llvm::BufferByteStreamer Class Reference
llvm::BufferByteStreamer Class Reference final
#include "CodeGen/AsmPrinter/ByteStreamer.h"
Public Member Functions
BufferByteStreamer (SmallVectorImpl< char > &Buffer, std::vector< std::string > &Comments, bool GenerateComments)
void EmitInt8 (uint8_t Byte, const Twine &Comment) override
void EmitSLEB128 (uint64_t DWord, const Twine &Comment) override
void EmitULEB128 (uint64_t DWord, const Twine &Comment, unsigned PadTo) override
Public Attributes
const bool GenerateComments
Only verbose textual output needs comments.
Additional Inherited Members
Protected Member Functions inherited from llvm::ByteStreamer
~ByteStreamer ()=default
ByteStreamer (const ByteStreamer &)=default
ByteStreamer ()=default
Detailed Description
Definition at line 73 of file ByteStreamer.h.
Constructor & Destructor Documentation
BufferByteStreamer()
llvm::BufferByteStreamer::BufferByteStreamer (SmallVectorImpl< char > & Buffer, std::vector< std::string > & Comments, bool GenerateComments) inline
Definition at line 84 of file ByteStreamer.h.
Member Function Documentation
EmitInt8()
void llvm::BufferByteStreamer::EmitInt8 (uint8_t Byte, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 88 of file ByteStreamer.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Twine::str().
EmitSLEB128()
void llvm::BufferByteStreamer::EmitSLEB128 (uint64_t DWord, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 93 of file ByteStreamer.h.
References llvm::encodeSLEB128(), and llvm::Twine::str().
EmitULEB128()
void llvm::BufferByteStreamer::EmitULEB128 (uint64_t DWord, const Twine & Comment, unsigned PadTo) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 105 of file ByteStreamer.h.
References llvm::encodeULEB128(), and llvm::Twine::str().
Member Data Documentation
GenerateComments
const bool llvm::BufferByteStreamer::GenerateComments
Only verbose textual output needs comments.
This will be set to true for that case, and false otherwise. If false, comments passed in to the emit methods will be ignored.
Definition at line 82 of file ByteStreamer.h.
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/ByteStreamer.h