LLVM: llvm::CGProfilePass Class Reference
llvm::CGProfilePass Class Reference
#include "llvm/Transforms/Instrumentation/CGProfile.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< CGProfilePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 19 of file CGProfile.h.
Member Function Documentation
run()
PreservedAnalyses CGProfilePass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 26 of file CGProfile.cpp.
References llvm::Module::addModuleFlag(), llvm::PreservedAnalyses::all(), llvm::Module::Append, llvm::AMDGPUISD::BFI, Context, llvm::InstrProfSymtab::create(), llvm::MDBuilder::createConstant(), E, F(), llvm::ConstantInt::get(), llvm::ValueAsMetadata::get(), llvm::MDNode::get(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), llvm::Module::getContext(), llvm::InstrProfSymtab::getFunction(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::Type::getInt64Ty(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::getValueProfDataFromInst(), I, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isIndirectCall(), llvm::TargetTransformInfo::isLoweredToCall(), and llvm::SaturatingAdd().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/CGProfile.h
lib/Transforms/Instrumentation/CGProfile.cpp