LLVM: llvm::InsertNOPLoad Class Reference
llvm::InsertNOPLoad Class Reference
#include "Target/Sparc/LeonPasses.h"
Public Member Functions
InsertNOPLoad ()
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::LEONMachineFunctionPass
LEONMachineFunctionPass (char &ID)
int GetRegIndexForOperand (MachineInstr &MI, int OperandIndex)
void clearUsedRegisterList ()
void markRegisterUsed (int registerIndex)
int getUnusedFPRegister (MachineRegisterInfo &MRI)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::LEONMachineFunctionPass
const SparcSubtarget * Subtarget = nullptr
const int LAST_OPERAND = -1
std::vector< int > UsedRegisters
Detailed Description
Definition at line 45 of file LeonPasses.h.
Constructor & Destructor Documentation
InsertNOPLoad()
InsertNOPLoad::InsertNOPLoad ()
Definition at line 38 of file LeonPasses.cpp.
Member Function Documentation
getPassName()
StringRef llvm::InsertNOPLoad::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 52 of file LeonPasses.h.
runOnMachineFunction()
bool InsertNOPLoad::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 40 of file LeonPasses.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), E, llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::DebugLoc::get(), llvm::SparcSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineFunction::getSubtarget(), llvm::DetectRoundChange::ID, MI, Modified, llvm::LEONMachineFunctionPass::Subtarget, and TII.
Member Data Documentation
ID
char InsertNOPLoad::ID = 0 static
Definition at line 47 of file LeonPasses.h.
Referenced by llvm::LEONMachineFunctionPass::LEONMachineFunctionPass().
The documentation for this class was generated from the following files:
lib/Target/Sparc/LeonPasses.h
lib/Target/Sparc/LeonPasses.cpp