LLVM: llvm::AMDGPURegisterBankInfo Class Reference
llvm::AMDGPURegisterBankInfo Class Reference
#include "Target/AMDGPU/AMDGPURegisterBankInfo.h"
Classes
struct OpRegBankEntry
Public Member Functions
bool buildVCopy (MachineIRBuilder &B, Register DstReg, Register SrcReg) const
bool collectWaterfallOperands (SmallSet< Register, 4 > &SGPROperandRegs, MachineInstr &MI, MachineRegisterInfo &MRI, ArrayRef< unsigned > OpIndices) const
bool executeInWaterfallLoop (MachineIRBuilder &B, iterator_range< MachineBasicBlock::iterator > Range, SmallSet< Register, 4 > &SGPROperandRegs, MachineRegisterInfo &MRI) const
Legalize instruction MI where operands in OpIndices must be SGPRs.
bool executeInWaterfallLoop (MachineIRBuilder &B, MachineInstr &MI, MachineRegisterInfo &MRI, ArrayRef< unsigned > OpIndices) const
bool executeInWaterfallLoop (MachineInstr &MI, MachineRegisterInfo &MRI, ArrayRef< unsigned > OpIndices) const
void constrainOpWithReadfirstlane (MachineInstr &MI, MachineRegisterInfo &MRI, unsigned OpIdx) const
bool applyMappingWideLoad (MachineInstr &MI, const AMDGPURegisterBankInfo::OperandsMapper &OpdMapper, MachineRegisterInfo &MRI) const
bool applyMappingImage (MachineInstr &MI, const AMDGPURegisterBankInfo::OperandsMapper &OpdMapper, MachineRegisterInfo &MRI, int RSrcIdx) const
void lowerScalarMinMax (MachineIRBuilder &B, MachineInstr &MI) const
Register handleD16VData (MachineIRBuilder &B, MachineRegisterInfo &MRI, Register Reg) const
Handle register layout difference for f16 images for some subtargets.
std::pair< Register, unsigned > splitBufferOffsets (MachineIRBuilder &B, Register Offset) const
MachineInstr * selectStoreIntrinsic (MachineIRBuilder &B, MachineInstr &MI) const
void applyMappingImpl (const OperandsMapper &OpdMapper) const override
See RegisterBankInfo::applyMapping.
const RegisterBankInfo::InstructionMapping & getInstrMappingForLoad (const MachineInstr &MI) const
unsigned getRegBankID (Register Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI, unsigned Default=AMDGPU::VGPRRegBankID) const
const ValueMapping * getSGPROpMapping (Register Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI) const
const ValueMapping * getVGPROpMapping (Register Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI) const
const ValueMapping * getAGPROpMapping (Register Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI) const
void split64BitValueForMapping (MachineIRBuilder &B, SmallVector< Register, 2 > &Regs, LLT HalfTy, Register Reg) const
Split 64-bit value Reg into two 32-bit halves and populate them into Regs.
template<unsigned NumOps>
InstructionMappings addMappingFromTable (const MachineInstr &MI, const MachineRegisterInfo &MRI, const std::array< unsigned, NumOps > RegSrcOpIdx, ArrayRef< OpRegBankEntry< NumOps >> Table) const
RegisterBankInfo::InstructionMappings getInstrAlternativeMappingsIntrinsic (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
RegisterBankInfo::InstructionMappings getInstrAlternativeMappingsIntrinsicWSideEffects (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isSALUMapping (const MachineInstr &MI) const
const InstructionMapping & getDefaultMappingSOP (const MachineInstr &MI) const
const InstructionMapping & getDefaultMappingVOP (const MachineInstr &MI) const
const InstructionMapping & getDefaultMappingAllVGPR (const MachineInstr &MI) const
const InstructionMapping & getImageMapping (const MachineRegisterInfo &MRI, const MachineInstr &MI, int RsrcIdx) const
AMDGPURegisterBankInfo (const GCNSubtarget &STI)
unsigned copyCost (const RegisterBank &A, const RegisterBank &B, unsigned Size) const override
Get the cost of a copy from B to A, or put differently, get the cost of A = COPY B.
unsigned getBreakDownCost (const ValueMapping &ValMapping, const RegisterBank *CurBank=nullptr) const override
Get the cost of using ValMapping to decompose a register.
const RegisterBank & getRegBankFromRegClass (const TargetRegisterClass &RC, LLT) const override
Get a register bank that covers RC.
InstructionMappings getInstrAlternativeMappings (const MachineInstr &MI) const override
Get the alternative mappings for MI.
const InstructionMapping & getInstrMapping (const MachineInstr &MI) const override
This function must return a legal mapping, because AMDGPURegisterBankInfo::getInstrAlternativeMappings() is not called in RegBankSelect::Mode::Fast.
template<unsigned NumOps>
RegisterBankInfo::InstructionMappings addMappingFromTable (const MachineInstr &MI, const MachineRegisterInfo &MRI, const std::array< unsigned, NumOps > RegSrcOpIdx, ArrayRef< OpRegBankEntry< NumOps >> Table) const
Public Member Functions inherited from llvm::RegisterBankInfo
const RegisterBank * getRegBankFromConstraints (const MachineInstr &MI, unsigned OpIdx, const TargetInstrInfo &TII, const MachineRegisterInfo &MRI) const
Get the register bank for the OpIdx-th operand of MI form the encoding constraints, if any.
virtual ~RegisterBankInfo ()=default
const RegisterBank & getRegBank (unsigned ID) const
Get the register bank identified by ID.
const RegisterBank * getRegBank (Register Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI) const
Get the register bank of Reg.
unsigned getNumRegBanks () const
Get the total number of register banks.
bool cannotCopy (const RegisterBank &Dst, const RegisterBank &Src, unsigned Size) const
const InstructionMapping & getInstructionMapping (unsigned ID, unsigned Cost, const ValueMapping *OperandsMapping, unsigned NumOperands) const
Method to get a uniquely generated InstructionMapping.
const InstructionMapping & getInvalidInstructionMapping () const
Method to get a uniquely generated invalid InstructionMapping.
Public Attributes
const GCNSubtarget & Subtarget
const SIRegisterInfo * TRI
const SIInstrInfo * TII
Public Attributes inherited from llvm::RegisterBankInfo
struct llvm::RegisterBankInfo::PartialMapping ScalarAddx2
VectorAdd
Get the possible mapping for MI.
Additional Inherited Members
Public Types inherited from llvm::RegisterBankInfo
using InstructionMappings = SmallVector< const InstructionMapping *, 4 >
Convenient type to represent the alternatives for mapping an instruction.
Static Public Member Functions inherited from llvm::RegisterBankInfo
static void applyDefaultMapping (const OperandsMapper &OpdMapper)
Helper method to apply something that is like the default mapping.
static const TargetRegisterClass * constrainGenericRegister (Register Reg, const TargetRegisterClass &RC, MachineRegisterInfo &MRI)
Constrain the (possibly generic) virtual register Reg to RC.
Static Public Attributes inherited from llvm::RegisterBankInfo
static const unsigned DefaultMappingID = UINT_MAX
Identifier used when the related instruction mapping instance is generated by target independent code.
static const unsigned InvalidMappingID = UINT_MAX - 1
Identifier used when the related instruction mapping instance is generated by the default constructor.
Protected Member Functions inherited from llvm::RegisterBankInfo
RegisterBankInfo (RegisterBank **RegBanks, unsigned NumRegBanks)
Create a RegisterBankInfo that can accommodate up to NumRegBanks RegisterBank instances.
RegisterBankInfo ()
This constructor is meaningless.
RegisterBank & getRegBank (unsigned ID)
Get the register bank identified by ID.
const TargetRegisterClass & getMinimalPhysRegClass (Register Reg, const TargetRegisterInfo &TRI) const
Get the MinimalPhysRegClass for Reg.
const InstructionMapping & getInstrMappingImpl (const MachineInstr &MI) const
Try to get the mapping of MI.
const PartialMapping & getPartialMapping (unsigned StartIdx, unsigned Length, const RegisterBank &RegBank) const
Get the uniquely generated PartialMapping for the given arguments.
const ValueMapping & getValueMapping (unsigned StartIdx, unsigned Length, const RegisterBank &RegBank) const
The most common ValueMapping consists of a single PartialMapping.
const ValueMapping & getValueMapping (const PartialMapping *BreakDown, unsigned NumBreakDowns) const
Get the ValueMapping for the given arguments.
template<typename Iterator >
const ValueMapping * getOperandsMapping (Iterator Begin, Iterator End) const
Get the uniquely generated array of ValueMapping for the elements of between Begin and End.
const ValueMapping * getOperandsMapping (const SmallVectorImpl< const ValueMapping *> &OpdsMapping) const
Get the uniquely generated array of ValueMapping for the elements of OpdsMapping.
const ValueMapping * getOperandsMapping (std::initializer_list< const ValueMapping *> OpdsMapping) const
Get the uniquely generated array of ValueMapping for the given arguments.
Protected Attributes inherited from llvm::RegisterBankInfo
RegisterBank ** RegBanks
Hold the set of supported register banks.
unsigned NumRegBanks
Total number of register banks.
DenseMap< unsigned, std::unique_ptr< const PartialMapping > > MapOfPartialMappings
Keep dynamically allocated PartialMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< const ValueMapping > > MapOfValueMappings
Keep dynamically allocated ValueMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< ValueMapping[]> > MapOfOperandsMappings
Keep dynamically allocated array of ValueMapping in a separate map.
DenseMap< unsigned, std::unique_ptr< const InstructionMapping > > MapOfInstructionMappings
Keep dynamically allocated InstructionMapping in a separate map.
DenseMap< unsigned, const TargetRegisterClass * > PhysRegMinimalRCs
Getting the minimal register class of a physreg is expensive.
Detailed Description
Definition at line 42 of file AMDGPURegisterBankInfo.h.
Constructor & Destructor Documentation
AMDGPURegisterBankInfo()
AMDGPURegisterBankInfo::AMDGPURegisterBankInfo (const GCNSubtarget & STI)
Definition at line 134 of file AMDGPURegisterBankInfo.cpp.
References assert(), and llvm::RegisterBankInfo::getRegBank().
Member Function Documentation
addMappingFromTable() [1/2]
template<unsigned NumOps> InstructionMappings llvm::AMDGPURegisterBankInfo::addMappingFromTable (const MachineInstr & MI, const MachineRegisterInfo & MRI, const std::array< unsigned, NumOps > RegSrcOpIdx, ArrayRef< OpRegBankEntry< NumOps >> Table) const
addMappingFromTable() [2/2]
template<unsigned NumOps> RegisterBankInfo::InstructionMappings llvm::AMDGPURegisterBankInfo::addMappingFromTable (const MachineInstr & MI, const MachineRegisterInfo & MRI, const std::array< unsigned, NumOps > RegSrcOpIdx, ArrayRef< OpRegBankEntry< NumOps >> Table) const
Definition at line 239 of file AMDGPURegisterBankInfo.cpp.
References E, llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getNumExplicitDefs(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineOperand::getReg(), llvm::getSizeInBits(), getValueMapping(), I, MRI, Operands, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, and TRI.
applyMappingImage()
bool AMDGPURegisterBankInfo::applyMappingImage (MachineInstr & MI, const AMDGPURegisterBankInfo::OperandsMapper & OpdMapper, MachineRegisterInfo & MRI, int RSrcIdx) const
Definition at line 1186 of file AMDGPURegisterBankInfo.cpp.
References llvm::RegisterBankInfo::applyDefaultMapping(), executeInWaterfallLoop(), llvm::MachineInstr::getNumExplicitDefs(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), I, llvm::MachineOperand::isReg(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by applyMappingImpl().
applyMappingImpl()
void AMDGPURegisterBankInfo::applyMappingImpl (const OperandsMapper & OpdMapper) const override virtual
See RegisterBankInfo::applyMapping.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 1468 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), llvm::RegisterBankInfo::applyDefaultMapping(), applyMappingImage(), applyMappingWideLoad(), assert(), B, llvm::RegisterBankInfo::ValueMapping::BreakDown, llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildAShr(), llvm::MachineIRBuilder::buildBitcast(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildExtractVectorElement(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildSExtOrTrunc(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildTrunc(), buildVCopy(), llvm::MachineIRBuilder::buildZExt(), llvm::MachineIRBuilder::buildZExtOrTrunc(), collectWaterfallOperands(), constrainOpWithReadfirstlane(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), E, llvm::MachineInstr::eraseFromParent(), executeInWaterfallLoop(), llvm::MipsISD::Ext, llvm::MachineBasicBlock::getFirstTerminator(), getHalfSizedType(), llvm::RegisterBank::getID(), llvm::RegisterBankInfo::OperandsMapper::getInstrMapping(), llvm::MachineInstr::getIntrinsicID(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineIRBuilder::getMBB(), llvm::MachineOperand::getMBB(), llvm::RegisterBankInfo::OperandsMapper::getMI(), llvm::RegisterBankInfo::OperandsMapper::getMRI(), llvm::LLT::getNumElements(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineInstrBuilder::getReg(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), llvm::MipsISD::Hi, I, llvm::LLT::isScalar(), llvm::LegalizerHelper::Legalized, llvm_unreachable, llvm::MipsISD::Lo, llvm::AMDGPU::lookupRsrcIntrinsic(), lowerScalarMinMax(), llvm::make_range(), MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::RegisterBankInfo::PartialMapping::RegBank, llvm::LLT::scalar(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineIRBuilder::setInstr(), llvm::MachineOperand::setReg(), llvm::MachineRegisterInfo::setRegBank(), setRegsToType(), Signed, split64BitValueForMapping(), substituteSimpleCopyRegs(), TRI, llvm::LLT::vector(), and llvm::LegalizerHelper::widenScalar().
applyMappingWideLoad()
bool AMDGPURegisterBankInfo::applyMappingWideLoad (MachineInstr & MI, const AMDGPURegisterBankInfo::OperandsMapper & OpdMapper, MachineRegisterInfo & MRI) const
Definition at line 1113 of file AMDGPURegisterBankInfo.cpp.
References assert(), B, llvm::RegisterBankInfo::ValueMapping::BreakDown, llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtractVectorElement(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::numbers::e, llvm::RegisterBankInfo::OperandsMapper::getInstrMapping(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), getOtherVRegDef(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarType(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), llvm::LegalizerHelper::Legalized, llvm::RISCVFenceField::O, llvm::RegisterBankInfo::PartialMapping::RegBank, llvm::LLT::scalar(), llvm::MachineIRBuilder::setChangeObserver(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineOperand::setReg(), llvm::MachineRegisterInfo::setRegBank(), llvm::MachineRegisterInfo::setType(), and llvm::LLT::vector().
Referenced by applyMappingImpl().
buildVCopy()
bool AMDGPURegisterBankInfo::buildVCopy (MachineIRBuilder & B, Register DstReg, Register SrcReg) const
Definition at line 1435 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineIRBuilder::getMRI(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), and MRI.
Referenced by applyMappingImpl().
collectWaterfallOperands()
bool AMDGPURegisterBankInfo::collectWaterfallOperands (SmallSet< Register, 4 > & SGPROperandRegs, MachineInstr & MI, MachineRegisterInfo & MRI, ArrayRef< unsigned > OpIndices) const
Definition at line 1035 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::SmallSet< T, N, C >::empty(), llvm::RegisterBank::getID(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isUse(), Reg, and TRI.
Referenced by applyMappingImpl(), and executeInWaterfallLoop().
constrainOpWithReadfirstlane()
void AMDGPURegisterBankInfo::constrainOpWithReadfirstlane (MachineInstr & MI, MachineRegisterInfo & MRI, unsigned OpIdx) const
Definition at line 1073 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addReg(), assert(), B, llvm::MachineIRBuilder::buildInstr(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::MachineRegisterInfo::getType(), Reg, llvm::MachineOperand::setReg(), llvm::MachineRegisterInfo::setType(), and TRI.
Referenced by applyMappingImpl().
copyCost()
unsigned AMDGPURegisterBankInfo::copyCost (const RegisterBank & A, const RegisterBank & B, unsigned Size) const override virtual
Get the cost of a copy from B to A, or put differently, get the cost of A = COPY B.
Since register banks may cover different size, Size specifies what will be the size in bits that will be copied around.
Note
Since this is a copy, both registers have the same size.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 157 of file AMDGPURegisterBankInfo.cpp.
References llvm::RegisterBankInfo::copyCost(), llvm::RegisterBank::getID(), isVectorRegisterBank(), and llvm::max().
executeInWaterfallLoop() [1/3]
bool AMDGPURegisterBankInfo::executeInWaterfallLoop (MachineIRBuilder & B, iterator_range< MachineBasicBlock::iterator > Range, SmallSet< Register, 4 > & SGPROperandRegs, MachineRegisterInfo & MRI) const
Legalize instruction MI where operands in OpIndices must be SGPRs.
If any of the required SGPR operands are VGPRs, perform a waterfall loop to execute the instruction for each unique combination of values in all lanes in the wave. The block will be split such that rest of the instructions are moved to a new block.
Essentially performs this loop: Save Execution Mask For (Lane : Wavefront) { Enable Lane, Disable all other lanes SGPR = read SGPR value for current lane from VGPR VGPRResult[Lane] = use_op SGPR } Restore Execution Mask
There is additional complexity to try for compare values to identify the unique values used.
Definition at line 734 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMerge(), llvm::BuildMI(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineIRBuilder::buildUnmerge(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::SmallSet< T, N, C >::count(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::tgtok::Def, llvm::MachineBasicBlock::end(), llvm::MachineIRBuilder::getDL(), llvm::MachineIRBuilder::getMBB(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstrBuilder::getReg(), getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::SIRegisterInfo::getWaveMaskRegClass(), I, llvm::MachineFunction::insert(), llvm::LLT::isVector(), llvm::GCNSubtarget::isWave32(), llvm::RegState::Kill, llvm::make_range(), Merge, MI, MRI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalar(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineIRBuilder::setInstr(), llvm::MachineIRBuilder::setMBB(), llvm::MachineRegisterInfo::setRegBank(), llvm::MachineRegisterInfo::setRegClass(), llvm::MachineRegisterInfo::setSimpleHint(), llvm::MachineRegisterInfo::setType(), llvm::MachineBasicBlock::splice(), Subtarget, TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), TRI, and llvm::zip().
Referenced by applyMappingImage(), applyMappingImpl(), executeInWaterfallLoop(), and selectStoreIntrinsic().
executeInWaterfallLoop() [2/3]
bool AMDGPURegisterBankInfo::executeInWaterfallLoop (MachineIRBuilder & B, MachineInstr & MI, MachineRegisterInfo & MRI, ArrayRef< unsigned > OpIndices) const
Definition at line 1050 of file AMDGPURegisterBankInfo.cpp.
References collectWaterfallOperands(), executeInWaterfallLoop(), llvm::ilist_node_impl< OptionsT >::getIterator(), I, and llvm::make_range().
executeInWaterfallLoop() [3/3]
bool AMDGPURegisterBankInfo::executeInWaterfallLoop (MachineInstr & MI, MachineRegisterInfo & MRI, ArrayRef< unsigned > OpIndices) const
Definition at line 1065 of file AMDGPURegisterBankInfo.cpp.
References B, and executeInWaterfallLoop().
getAGPROpMapping()
const RegisterBankInfo::ValueMapping * AMDGPURegisterBankInfo::getAGPROpMapping (Register Reg, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI) const
Definition at line 2439 of file AMDGPURegisterBankInfo.cpp.
References llvm::getSizeInBits(), getValueMapping(), and Size.
Referenced by getInstrMapping().
getBreakDownCost()
unsigned AMDGPURegisterBankInfo::getBreakDownCost (const ValueMapping & ValMapping, const RegisterBank * CurBank = nullptr) const override virtual
Get the cost of using ValMapping to decompose a register.
This is similar to copyCost, except for cases where multiple copy-like operations need to be inserted. If the register is used as a source operand and already has a bank assigned, CurBank is non-null.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 191 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::RegisterBankInfo::ValueMapping::BreakDown, llvm::RegisterBankInfo::PartialMapping::Length, llvm::RegisterBankInfo::ValueMapping::NumBreakDowns, llvm::RegisterBankInfo::PartialMapping::RegBank, and llvm::RegisterBankInfo::PartialMapping::StartIdx.
getDefaultMappingAllVGPR()
const RegisterBankInfo::InstructionMapping & AMDGPURegisterBankInfo::getDefaultMappingAllVGPR (const MachineInstr & MI) const
Definition at line 2291 of file AMDGPURegisterBankInfo.cpp.
References E, llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::getSizeInBits(), getValueMapping(), I, llvm::MachineOperand::isReg(), MRI, Size, and TRI.
Referenced by getInstrMapping().
getDefaultMappingSOP()
const RegisterBankInfo::InstructionMapping & AMDGPURegisterBankInfo::getDefaultMappingSOP (const MachineInstr & MI) const
Definition at line 2241 of file AMDGPURegisterBankInfo.cpp.
References llvm::numbers::e, llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::getSizeInBits(), getValueMapping(), MRI, Size, and TRI.
Referenced by getInstrMapping().
getDefaultMappingVOP()
const RegisterBankInfo::InstructionMapping & AMDGPURegisterBankInfo::getDefaultMappingVOP (const MachineInstr & MI) const
Definition at line 2255 of file AMDGPURegisterBankInfo.cpp.
References llvm::numbers::e, llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getRegBankID(), llvm::MachineFunction::getRegInfo(), llvm::getSizeInBits(), getValueMapping(), llvm::MachineOperand::isIntrinsicID(), llvm::MachineOperand::isReg(), MRI, Size, and TRI.
Referenced by getInstrMapping().
getImageMapping()
const RegisterBankInfo::InstructionMapping & AMDGPURegisterBankInfo::getImageMapping (const MachineRegisterInfo & MRI, const MachineInstr & MI, int RsrcIdx) const
Definition at line 2310 of file AMDGPURegisterBankInfo.cpp.
References llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getNumExplicitDefs(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineOperand::getReg(), getRegBankID(), llvm::getSizeInBits(), getValueMapping(), I, llvm::MachineOperand::isReg(), Size, and TRI.
Referenced by getInstrMapping().
getInstrAlternativeMappings()
RegisterBankInfo::InstructionMappings AMDGPURegisterBankInfo::getInstrAlternativeMappings (const MachineInstr & MI) const override virtual
Get the alternative mappings for MI.
Alternative in the sense different from getInstrMapping.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 417 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::RegisterBankInfo::getInstrAlternativeMappings(), getInstrAlternativeMappingsIntrinsic(), getInstrAlternativeMappingsIntrinsicWSideEffects(), llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), llvm::MachineRegisterInfo::getType(), getValueMapping(), isScalarLoadLegal(), LLVM_FALLTHROUGH, AMDGPUAS::LOCAL_ADDRESS, llvm::makeArrayRef(), MI, MRI, AMDGPUAS::PRIVATE_ADDRESS, llvm::SmallVectorTemplateBase< T, bool >::push_back(), AMDGPUAS::REGION_ADDRESS, Size, and TRI.
getInstrAlternativeMappingsIntrinsic()
RegisterBankInfo::InstructionMappings AMDGPURegisterBankInfo::getInstrAlternativeMappingsIntrinsic (const MachineInstr & MI, const MachineRegisterInfo & MRI) const
Definition at line 276 of file AMDGPURegisterBankInfo.cpp.
References llvm::RegisterBankInfo::getInstrAlternativeMappings(), llvm::MachineInstr::getIntrinsicID(), llvm::makeArrayRef(), MI, and MRI.
Referenced by getInstrAlternativeMappings().
getInstrAlternativeMappingsIntrinsicWSideEffects()
RegisterBankInfo::InstructionMappings AMDGPURegisterBankInfo::getInstrAlternativeMappingsIntrinsicWSideEffects (const MachineInstr & MI, const MachineRegisterInfo & MRI) const
Definition at line 316 of file AMDGPURegisterBankInfo.cpp.
References llvm::RegisterBankInfo::getInstrAlternativeMappings(), llvm::MachineInstr::getIntrinsicID(), llvm::makeArrayRef(), MI, and MRI.
Referenced by getInstrAlternativeMappings().
getInstrMapping()
const RegisterBankInfo::InstructionMapping & AMDGPURegisterBankInfo::getInstrMapping (const MachineInstr & MI) const override virtual
This function must return a legal mapping, because AMDGPURegisterBankInfo::getInstrAlternativeMappings() is not called in RegBankSelect::Mode::Fast.
Any mapping that would cause a VGPR to SGPR generated is illegal.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 2453 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::numbers::e, E, getAGPROpMapping(), getDefaultMappingAllVGPR(), getDefaultMappingSOP(), getDefaultMappingVOP(), llvm::RegisterBank::getID(), getImageMapping(), getInstrMappingForLoad(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getIntrinsicID(), llvm::RegisterBankInfo::getInvalidInstructionMapping(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), getRegBankID(), llvm::MachineFunction::getRegInfo(), getSGPROpMapping(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::RegisterBankInfo::getValueMapping(), getValueMapping(), getVGPROpMapping(), llvm::GCNSubtarget::hasScalarCompareEq64(), llvm::GCNSubtarget::hasScalarMulHiInsts(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegSequence(), isSALUMapping(), llvm::RegisterBankInfo::InstructionMapping::isValid(), LLVM_FALLTHROUGH, llvm::AMDGPU::lookupRsrcIntrinsic(), MRI, Reg, regBankBoolUnion(), regBankUnion(), Size, Subtarget, TRI, and llvm::LLT::vector().
getInstrMappingForLoad()
const RegisterBankInfo::InstructionMapping & AMDGPURegisterBankInfo::getInstrMappingForLoad (const MachineInstr & MI) const
Definition at line 2349 of file AMDGPURegisterBankInfo.cpp.
References llvm::LLT::getAddressSpace(), llvm::RegisterBankInfo::getInstructionMapping(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::MachineFunction::getRegInfo(), llvm::LLT::getSizeInBits(), llvm::getSizeInBits(), llvm::MachineRegisterInfo::getType(), getValueMapping(), isScalarLoadLegal(), AMDGPUAS::LOCAL_ADDRESS, MRI, AMDGPUAS::PRIVATE_ADDRESS, AMDGPUAS::REGION_ADDRESS, Size, and TRI.
Referenced by getInstrMapping().
getRegBankFromRegClass()
const RegisterBank & AMDGPURegisterBankInfo::getRegBankFromRegClass (const TargetRegisterClass & RC, LLT Ty) const override virtual
Get a register bank that covers RC.
Precondition
RC is a user-defined register class (as opposed as one generated by TableGen).
Note
The mapping RC -> RegBank could be built while adding the coverage for the register banks. However, we do not do it, because, at least for now, we only need this information for register classes that are used in the description of instruction. In other words, there are just a handful of them and we do not want to waste space.
Todo:
This should be TableGen'ed.
Reimplemented from llvm::RegisterBankInfo.
Definition at line 217 of file AMDGPURegisterBankInfo.cpp.
References llvm::SIRegisterInfo::isAGPRClass(), llvm::SIRegisterInfo::isSGPRClass(), llvm::LLT::isValid(), llvm::LLT::scalar(), and TRI.
Referenced by shouldUseAndMask().
getRegBankID()
unsigned AMDGPURegisterBankInfo::getRegBankID (Register Reg, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI, unsigned Default = AMDGPU::VGPRRegBankID) const
Definition at line 2389 of file AMDGPURegisterBankInfo.cpp.
References llvm::Default, llvm::RegisterBank::getID(), and llvm::RegisterBankInfo::getRegBank().
Referenced by getDefaultMappingVOP(), getImageMapping(), getInstrMapping(), and getSGPROpMapping().
getSGPROpMapping()
const RegisterBankInfo::ValueMapping * AMDGPURegisterBankInfo::getSGPROpMapping (Register Reg, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI) const
Definition at line 2420 of file AMDGPURegisterBankInfo.cpp.
References getRegBankID(), llvm::getSizeInBits(), getValueMapping(), and Size.
Referenced by getInstrMapping().
getVGPROpMapping()
const RegisterBankInfo::ValueMapping * AMDGPURegisterBankInfo::getVGPROpMapping (Register Reg, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI) const
Definition at line 2431 of file AMDGPURegisterBankInfo.cpp.
References llvm::getSizeInBits(), getValueMapping(), and Size.
Referenced by getInstrMapping().
handleD16VData()
Register AMDGPURegisterBankInfo::handleD16VData (MachineIRBuilder & B, MachineRegisterInfo & MRI, Register Reg) const
Handle register layout difference for f16 images for some subtargets.
Definition at line 1258 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildUnmerge(), E, llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstrBuilder::getReg(), llvm::MachineRegisterInfo::getType(), llvm::GCNSubtarget::hasUnpackedD16VMem(), I, llvm::LLT::isVector(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::LLT::scalar(), Subtarget, and llvm::LLT::vector().
isSALUMapping()
bool AMDGPURegisterBankInfo::isSALUMapping (const MachineInstr & MI) const
Definition at line 2225 of file AMDGPURegisterBankInfo.cpp.
References llvm::numbers::e, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::isReg(), MRI, Reg, and TRI.
Referenced by getInstrMapping().
lowerScalarMinMax()
void AMDGPURegisterBankInfo::lowerScalarMinMax (MachineIRBuilder & B, MachineInstr & MI) const
Definition at line 1230 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineInstr::eraseFromParent(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), minMaxToCompare(), llvm::LLT::scalar(), and llvm::MachineRegisterInfo::setRegBank().
Referenced by applyMappingImpl().
selectStoreIntrinsic()
MachineInstr * AMDGPURegisterBankInfo::selectStoreIntrinsic (MachineIRBuilder & B, MachineInstr & MI) const
Definition at line 1358 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::constrainSelectedInstRegOperands(), executeInWaterfallLoop(), extractDLC(), extractGLC(), extractSLC(), llvm::MachineOperand::getImm(), llvm::MachineIRBuilder::getMRI(), llvm::AMDGPU::getMUBUFOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), isZero(), llvm::MachineInstr::memoperands_begin(), MRI, llvm::report_fatal_error(), llvm::MachineIRBuilder::setInstr(), Size, splitBufferOffsets(), TII, and TRI.
split64BitValueForMapping()
void AMDGPURegisterBankInfo::split64BitValueForMapping (MachineIRBuilder & B, SmallVector< Register, 2 > & Regs, LLT HalfTy, Register Reg) const
Split 64-bit value Reg into two 32-bit halves and populate them into Regs.
This appropriately sets the regbank of the new registers.
Definition at line 675 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::getMRI(), llvm::RegisterBankInfo::getRegBank(), llvm::LLT::getSizeInBits(), MRI, llvm::SmallVectorTemplateBase< T >::push_back(), and TRI.
Referenced by applyMappingImpl().
splitBufferOffsets()
std::pair< Register, unsigned > AMDGPURegisterBankInfo::splitBufferOffsets (MachineIRBuilder & B, Register Offset) const
Definition at line 1297 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildConstant(), getBaseWithConstantOffset(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstrBuilder::getReg(), and llvm::LLT::scalar().
Referenced by selectStoreIntrinsic().
Member Data Documentation
Subtarget
const GCNSubtarget& llvm::AMDGPURegisterBankInfo::Subtarget
Definition at line 44 of file AMDGPURegisterBankInfo.h.
Referenced by executeInWaterfallLoop(), getInstrMapping(), and handleD16VData().
TII
const SIInstrInfo* llvm::AMDGPURegisterBankInfo::TII
Definition at line 46 of file AMDGPURegisterBankInfo.h.
Referenced by executeInWaterfallLoop(), and selectStoreIntrinsic().
TRI
const SIRegisterInfo* llvm::AMDGPURegisterBankInfo::TRI
Definition at line 45 of file AMDGPURegisterBankInfo.h.
Referenced by addMappingFromTable(), applyMappingImpl(), collectWaterfallOperands(), constrainOpWithReadfirstlane(), executeInWaterfallLoop(), getDefaultMappingAllVGPR(), getDefaultMappingSOP(), getDefaultMappingVOP(), getImageMapping(), getInstrAlternativeMappings(), getInstrMapping(), getInstrMappingForLoad(), getRegBankFromRegClass(), isSALUMapping(), selectStoreIntrinsic(), and split64BitValueForMapping().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPURegisterBankInfo.h
lib/Target/AMDGPU/AMDGPURegisterBankInfo.cpp