LLVM: llvm::AMDGPUMachineFunction Class Reference
llvm::AMDGPUMachineFunction Class Reference
#include "Target/AMDGPU/AMDGPUMachineFunction.h"
Public Member Functions
AMDGPUMachineFunction (const MachineFunction &MF)
uint64_t getExplicitKernArgSize () const
unsigned getMaxKernArgAlign () const
unsigned getLDSSize () const
AMDGPU::SIModeRegisterDefaults getMode () const
bool isEntryFunction () const
bool hasNoSignedZerosFPMath () const
bool isMemoryBound () const
bool needsWaveLimiter () const
unsigned allocateLDSGlobal (const DataLayout &DL, const GlobalValue &GV)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Protected Attributes
uint64_t ExplicitKernArgSize
Align MaxKernArgAlign
unsigned LDSSize
Number of bytes in the LDS that are being used.
AMDGPU::SIModeRegisterDefaults Mode
bool IsEntryFunction
bool NoSignedZerosFPMath
bool MemoryBound
bool WaveLimiter
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 20 of file AMDGPUMachineFunction.h.
Constructor & Destructor Documentation
AMDGPUMachineFunction()
AMDGPUMachineFunction::AMDGPUMachineFunction (const MachineFunction & MF)
Definition at line 16 of file AMDGPUMachineFunction.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, ExplicitKernArgSize, F(), llvm::AMDGPUSubtarget::get(), llvm::Function::getCallingConv(), llvm::AMDGPUSubtarget::getExplicitKernArgSize(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), llvm::Attribute::getValueAsString(), llvm::Attribute::isStringAttribute(), MaxKernArgAlign, MemoryBound, llvm::CallingConv::SPIR_KERNEL, llvm::ARM_MB::ST, and WaveLimiter.
Member Function Documentation
allocateLDSGlobal()
unsigned AMDGPUMachineFunction::allocateLDSGlobal (const DataLayout & DL, const GlobalValue & GV)
TODO: We should sort these to minimize wasted space due to alignment padding. Currently the padding is decided by the first encountered use during lowering.
Definition at line 45 of file AMDGPUMachineFunction.cpp.
References llvm::alignTo(), llvm::DataLayout::getABITypeAlignment(), llvm::GlobalValue::getAlignment(), llvm::DataLayout::getTypeAllocSize(), llvm::GlobalValue::getValueType(), and LDSSize.
Referenced by llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), and needsWaveLimiter().
getExplicitKernArgSize()
uint64_t llvm::AMDGPUMachineFunction::getExplicitKernArgSize () const inline
Definition at line 50 of file AMDGPUMachineFunction.h.
References ExplicitKernArgSize.
Referenced by llvm::AMDGPUTargetLowering::getImplicitParameterOffset().
getLDSSize()
unsigned llvm::AMDGPUMachineFunction::getLDSSize () const inline
Definition at line 56 of file AMDGPUMachineFunction.h.
References LDSSize.
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::R600AsmPrinter::getPassName(), llvm::SIRegisterInfo::getRegPressureLimit(), hasAnyNonFlatUseOfReg(), llvm::SIMachineFunctionInfo::limitOccupancy(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
getMaxKernArgAlign()
unsigned llvm::AMDGPUMachineFunction::getMaxKernArgAlign () const inline
Definition at line 54 of file AMDGPUMachineFunction.h.
References llvm::Align::value().
getMode()
AMDGPU::SIModeRegisterDefaults llvm::AMDGPUMachineFunction::getMode () const inline
Definition at line 60 of file AMDGPUMachineFunction.h.
References Mode.
Referenced by getOModValue(), getSplatConstantFP(), hasAnyNonFlatUseOfReg(), hasFP32Denormals(), hasFP64FP16Denormals(), isClampZeroToOne(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeMinNumMaxNum(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), and llvm::SITargetLowering::shouldEmitPCReloc().
hasNoSignedZerosFPMath()
bool llvm::AMDGPUMachineFunction::hasNoSignedZerosFPMath () const inline
Definition at line 68 of file AMDGPUMachineFunction.h.
References NoSignedZerosFPMath.
isEntryFunction()
bool llvm::AMDGPUMachineFunction::isEntryFunction () const inline
Definition at line 64 of file AMDGPUMachineFunction.h.
References IsEntryFunction.
Referenced by llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPR(), buildEpilogReload(), llvm::SIRegisterInfo::canRealignStack(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SIFrameLowering::emitEpilogue(), llvm::AMDGPUAsmPrinter::EmitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::EmitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::EmitFunctionEntryLabel(), llvm::SIFrameLowering::emitPrologue(), llvm::SITargetLowering::finalizeLowering(), llvm::SIFrameLowering::hasFP(), llvm::SIInstrInfo::insertReturn(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SITargetLowering::LowerReturn(), parseTexFail(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIRegisterInfo::requiresRegisterScavenging(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::SITargetLowering::shouldEmitPCReloc(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), and llvm::SITargetLowering::supportSplitCSR().
isMemoryBound()
bool llvm::AMDGPUMachineFunction::isMemoryBound () const inline
Definition at line 72 of file AMDGPUMachineFunction.h.
References MemoryBound.
Referenced by llvm::AMDGPUAsmPrinter::doFinalization().
needsWaveLimiter()
bool llvm::AMDGPUMachineFunction::needsWaveLimiter () const inline
Definition at line 76 of file AMDGPUMachineFunction.h.
References allocateLDSGlobal(), and WaveLimiter.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction().
Member Data Documentation
ExplicitKernArgSize
uint64_t llvm::AMDGPUMachineFunction::ExplicitKernArgSize protected
Definition at line 26 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and getExplicitKernArgSize().
IsEntryFunction
bool llvm::AMDGPUMachineFunction::IsEntryFunction protected
Definition at line 37 of file AMDGPUMachineFunction.h.
Referenced by isEntryFunction().
LDSSize
unsigned llvm::AMDGPUMachineFunction::LDSSize protected
Number of bytes in the LDS that are being used.
Definition at line 30 of file AMDGPUMachineFunction.h.
Referenced by allocateLDSGlobal(), and getLDSSize().
MaxKernArgAlign
Align llvm::AMDGPUMachineFunction::MaxKernArgAlign protected
Definition at line 27 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
MemoryBound
bool llvm::AMDGPUMachineFunction::MemoryBound protected
Definition at line 42 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and isMemoryBound().
Mode
AMDGPU::SIModeRegisterDefaults llvm::AMDGPUMachineFunction::Mode protected
Definition at line 33 of file AMDGPUMachineFunction.h.
Referenced by getMode(), and llvm::GCNTargetMachine::parseMachineFunctionInfo().
NoSignedZerosFPMath
bool llvm::AMDGPUMachineFunction::NoSignedZerosFPMath protected
Definition at line 39 of file AMDGPUMachineFunction.h.
Referenced by hasNoSignedZerosFPMath().
WaveLimiter
bool llvm::AMDGPUMachineFunction::WaveLimiter protected
Definition at line 45 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and needsWaveLimiter().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUMachineFunction.h
lib/Target/AMDGPU/AMDGPUMachineFunction.cpp