LLVM: llvm::sys::UnicodeCharSet Class Reference
llvm::sys::UnicodeCharSet Class Reference
Holds a reference to an ordered array of UnicodeCharRange and allows to quickly check if a code point is contained in the set represented by this array.
#include "llvm/Support/UnicodeCharRanges.h"
Public Types
typedef ArrayRef< UnicodeCharRange > CharRanges
Public Member Functions
UnicodeCharSet (CharRanges Ranges)
Constructs a UnicodeCharSet instance from an array of UnicodeCharRanges.
bool contains (uint32_t C) const
Returns true if the character set contains the Unicode code point C.
Detailed Description
Holds a reference to an ordered array of UnicodeCharRange and allows to quickly check if a code point is contained in the set represented by this array.
Definition at line 38 of file UnicodeCharRanges.h.
Member Typedef Documentation
CharRanges
typedef ArrayRef<UnicodeCharRange> llvm::sys::UnicodeCharSet::CharRanges
Definition at line 40 of file UnicodeCharRanges.h.
Constructor & Destructor Documentation
UnicodeCharSet()
llvm::sys::UnicodeCharSet::UnicodeCharSet (CharRanges Ranges) inline
Constructs a UnicodeCharSet instance from an array of UnicodeCharRanges.
Array pointed by Ranges should have the lifetime at least as long as the UnicodeCharSet instance, and should not change. Array is validated by the constructor, so it makes sense to create as few UnicodeCharSet instances per each array of ranges, as possible.
Definition at line 57 of file UnicodeCharRanges.h.
References assert().
Member Function Documentation
contains()
bool llvm::sys::UnicodeCharSet::contains (uint32_t C) const inline
Returns true if the character set contains the Unicode code point C.
Definition at line 64 of file UnicodeCharRanges.h.
References C, llvm::dbgs(), E, I, LLVM_DEBUG, and llvm::write_hex().
Referenced by llvm::sys::unicode::charWidth(), and llvm::sys::unicode::isPrintable().
The documentation for this class was generated from the following file:
include/llvm/Support/UnicodeCharRanges.h