LLVM: llvm::DWARFAcceleratorTable::Entry Class Reference
llvm::DWARFAcceleratorTable::Entry Class Reference abstract
An abstract class representing a single entry in the accelerator tables.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
virtual Optional< uint64_t > getCUOffset () const =0
Returns the Offset of the Compilation Unit associated with this Accelerator Entry or None if the Compilation Unit offset is not recorded in this Accelerator Entry.
virtual Optional< dwarf::Tag > getTag () const =0
Returns the Tag of the Debug Info Entry associated with this Accelerator Entry or None if the Tag is not recorded in this Accelerator Entry.
ArrayRef< DWARFFormValue > getValues () const
Returns the raw values of fields in the Accelerator Entry.
Protected Member Functions
Entry ()=default
Entry (const Entry &)=default
Entry (Entry &&)=default
Entry & operator= (const Entry &)=default
Entry & operator= (Entry &&)=default
~Entry ()=default
Protected Attributes
SmallVector< DWARFFormValue, 3 > Values
Detailed Description
An abstract class representing a single entry in the accelerator tables.
Definition at line 38 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
Entry() [1/3]
llvm::DWARFAcceleratorTable::Entry::Entry () protected default
Referenced by llvm::DWARFDebugNames::NameIndex::extract().
Entry() [2/3]
llvm::DWARFAcceleratorTable::Entry::Entry (const Entry &) protected default
Entry() [3/3]
llvm::DWARFAcceleratorTable::Entry::Entry (Entry &&) protected default
~Entry()
llvm::DWARFAcceleratorTable::Entry::~Entry () protected default
Member Function Documentation
getCUOffset()
virtual Optional<uint64_t> llvm::DWARFAcceleratorTable::Entry::getCUOffset () const pure virtual
Returns the Offset of the Compilation Unit associated with this Accelerator Entry or None if the Compilation Unit offset is not recorded in this Accelerator Entry.
Implemented in llvm::DWARFDebugNames::Entry, and llvm::AppleAcceleratorTable::Entry.
Referenced by llvm::DWARFDebugNames::NameIndex::NameIndex().
getTag()
virtual Optional<dwarf::Tag> llvm::DWARFAcceleratorTable::Entry::getTag () const pure virtual
Returns the Tag of the Debug Info Entry associated with this Accelerator Entry or None if the Tag is not recorded in this Accelerator Entry.
Implemented in llvm::DWARFDebugNames::Entry, and llvm::AppleAcceleratorTable::Entry.
getValues()
ArrayRef<DWARFFormValue> llvm::DWARFAcceleratorTable::Entry::getValues () const inline
Returns the raw values of fields in the Accelerator Entry.
In general, these can only be interpreted with the help of the metadata in the owning Accelerator Table.
Definition at line 66 of file DWARFAcceleratorTable.h.
References Values.
operator=() [1/2]
Entry& llvm::DWARFAcceleratorTable::Entry::operator= (const Entry &) protected default
Referenced by llvm::DWARFAcceleratorTable::DWARFAcceleratorTable().
operator=() [2/2]
Entry& llvm::DWARFAcceleratorTable::Entry::operator= (Entry &&) protected default
Member Data Documentation
Values
SmallVector<DWARFFormValue, 3> llvm::DWARFAcceleratorTable::Entry::Values protected
Definition at line 40 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getEntry(), and getValues().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h