LLVM: llvm::orc::SymbolLookupSet Class Reference
llvm::orc::SymbolLookupSet Class Reference
A set of symbols to look up, each associated with a SymbolLookupFlags value.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Types
using value_type = std::pair< SymbolStringPtr, SymbolLookupFlags >
using UnderlyingVector = std::vector< value_type >
using iterator = UnderlyingVector::iterator
using const_iterator = UnderlyingVector::const_iterator
Public Member Functions
SymbolLookupSet ()=default
SymbolLookupSet (SymbolStringPtr Name, SymbolLookupFlags Flags=SymbolLookupFlags::RequiredSymbol)
SymbolLookupSet (std::initializer_list< SymbolStringPtr > Names, SymbolLookupFlags Flags=SymbolLookupFlags::RequiredSymbol)
Construct a SymbolLookupSet from an initializer list of SymbolStringPtrs.
SymbolLookupSet (const SymbolNameSet &Names, SymbolLookupFlags Flags=SymbolLookupFlags::RequiredSymbol)
Construct a SymbolLookupSet from a SymbolNameSet with the given Flags used for each value.
SymbolLookupSet (ArrayRef< SymbolStringPtr > Names, SymbolLookupFlags Flags=SymbolLookupFlags::RequiredSymbol)
Construct a SymbolLookupSet from a vector of symbols with the given Flags used for each value.
void add (SymbolStringPtr Name, SymbolLookupFlags Flags=SymbolLookupFlags::RequiredSymbol)
Add an element to the set.
bool empty () const
UnderlyingVector::size_type size () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void remove (UnderlyingVector::size_type I)
Removes the Ith element of the vector, replacing it with the last element.
void remove (iterator I)
Removes the element pointed to by the given iterator.
template<typename PredFn >
void remove_if (PredFn &&Pred)
Removes all elements matching the given predicate, which must be callable as bool(const SymbolStringPtr &, SymbolLookupFlags Flags).
template<typename BodyFn >
auto forEachWithRemoval (BodyFn &&Body) -> typename std::enable_if< std::is_same< decltype(Body(std::declval< const SymbolStringPtr &>(), std::declval< SymbolLookupFlags >())), bool >::value >::type
Loop over the elements of this SymbolLookupSet, applying the Body function to each one.
template<typename BodyFn >
auto forEachWithRemoval (BodyFn &&Body) -> typename std::enable_if< std::is_same< decltype(Body(std::declval< const SymbolStringPtr &>(), std::declval< SymbolLookupFlags >())), Expected< bool >>::value, Error >::type
Loop over the elements of this SymbolLookupSet, applying the Body function to each one.
SymbolNameVector getSymbolNames () const
Construct a SymbolNameVector from this instance by dropping the Flags values.
void sortByAddress ()
Sort the lookup set by pointer value.
void sortByName ()
Sort the lookup set lexicographically.
void removeDuplicates ()
Remove any duplicate elements.
bool containsDuplicates ()
Returns true if this set contains any duplicates.
Detailed Description
A set of symbols to look up, each associated with a SymbolLookupFlags value.
This class is backed by a vector and optimized for fast insertion, deletion and iteration. It does not guarantee a stable order between operations, and will not automatically detect duplicate elements (they can be manually checked by calling the validate method).
Definition at line 115 of file Core.h.
Member Typedef Documentation
const_iterator
using llvm::orc::SymbolLookupSet::const_iterator = UnderlyingVector::const_iterator
Definition at line 120 of file Core.h.
iterator
using llvm::orc::SymbolLookupSet::iterator = UnderlyingVector::iterator
Definition at line 119 of file Core.h.
UnderlyingVector
using llvm::orc::SymbolLookupSet::UnderlyingVector = std::vector<value_type>
Definition at line 118 of file Core.h.
value_type
using llvm::orc::SymbolLookupSet::value_type = std::pair<SymbolStringPtr, SymbolLookupFlags>
Definition at line 117 of file Core.h.
Constructor & Destructor Documentation
SymbolLookupSet() [1/5]
llvm::orc::SymbolLookupSet::SymbolLookupSet () default
SymbolLookupSet() [2/5]
llvm::orc::SymbolLookupSet::SymbolLookupSet (SymbolStringPtr Name, SymbolLookupFlags Flags = SymbolLookupFlags::RequiredSymbol) inline explicit
Definition at line 124 of file Core.h.
References add().
SymbolLookupSet() [3/5]
llvm::orc::SymbolLookupSet::SymbolLookupSet (std::initializer_list< SymbolStringPtr > Names, SymbolLookupFlags Flags = SymbolLookupFlags::RequiredSymbol) inline explicit
Construct a SymbolLookupSet from an initializer list of SymbolStringPtrs.
Definition at line 131 of file Core.h.
References add(), and Name.
SymbolLookupSet() [4/5]
llvm::orc::SymbolLookupSet::SymbolLookupSet (const SymbolNameSet & Names, SymbolLookupFlags Flags = SymbolLookupFlags::RequiredSymbol) inline explicit
Construct a SymbolLookupSet from a SymbolNameSet with the given Flags used for each value.
Definition at line 141 of file Core.h.
References add(), Name, and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::size().
SymbolLookupSet() [5/5]
llvm::orc::SymbolLookupSet::SymbolLookupSet (ArrayRef< SymbolStringPtr > Names, SymbolLookupFlags Flags = SymbolLookupFlags::RequiredSymbol) inline explicit
Construct a SymbolLookupSet from a vector of symbols with the given Flags used for each value.
If the ArrayRef contains duplicates it is up to the client to remove these before using this instance for lookup.
Definition at line 153 of file Core.h.
References add(), Name, and llvm::ArrayRef< T >::size().
Member Function Documentation
add()
void llvm::orc::SymbolLookupSet::add (SymbolStringPtr Name, SymbolLookupFlags Flags = SymbolLookupFlags::RequiredSymbol) inline
Add an element to the set.
The client is responsible for checking that duplicates are not added.
Definition at line 163 of file Core.h.
Referenced by llvm::orc::ReExportsMaterializationUnit::getName(), llvm::orc::ObjectLinkingLayerJITLinkContext::lookup(), and llvm::orc::CtorDtorRunner::run().
begin() [1/2]
iterator llvm::orc::SymbolLookupSet::begin () inline
Definition at line 170 of file Core.h.
begin() [2/2]
const_iterator llvm::orc::SymbolLookupSet::begin () const inline
Definition at line 172 of file Core.h.
containsDuplicates()
bool llvm::orc::SymbolLookupSet::containsDuplicates () inline
Returns true if this set contains any duplicates.
This should only be used in assertions.
Definition at line 285 of file Core.h.
References first, and I.
Referenced by llvm::orc::CtorDtorRunner::run().
empty()
bool llvm::orc::SymbolLookupSet::empty () const inline
Definition at line 168 of file Core.h.
Referenced by llvm::orc::buildSimpleReexportsAliasMap(), llvm::orc::ReExportsMaterializationUnit::getName(), and llvm::orc::JITDylib::lookupFlags().
end() [1/2]
iterator llvm::orc::SymbolLookupSet::end () inline
Definition at line 171 of file Core.h.
end() [2/2]
const_iterator llvm::orc::SymbolLookupSet::end () const inline
Definition at line 173 of file Core.h.
forEachWithRemoval() [1/2]
template<typename BodyFn > auto llvm::orc::SymbolLookupSet::forEachWithRemoval (BodyFn && Body) -> typename std::enable_if< std::is_same<decltype(Body(std::declval<const SymbolStringPtr &>(), std::declval<SymbolLookupFlags>())), bool>::value>::type inline
Loop over the elements of this SymbolLookupSet, applying the Body function to each one.
Body must be callable as bool(const SymbolStringPtr &, SymbolLookupFlags). If Body returns true then the element just passed in is removed from the set. If Body returns false then the element is retained.
Definition at line 205 of file Core.h.
References I, and Name.
forEachWithRemoval() [2/2]
template<typename BodyFn > auto llvm::orc::SymbolLookupSet::forEachWithRemoval (BodyFn && Body) -> typename std::enable_if< std::is_same<decltype(Body(std::declval<const SymbolStringPtr &>(), std::declval<SymbolLookupFlags>())), Expected<bool>>::value, Error>::type inline
Loop over the elements of this SymbolLookupSet, applying the Body function to each one.
Body must be callable as Expected<bool>(const SymbolStringPtr &, SymbolLookupFlags). If Body returns a failure value, the loop exits immediately. If Body returns true then the element just passed in is removed from the set. If Body returns false then the element is retained.
Definition at line 227 of file Core.h.
References I, Name, and llvm::Error::success().
getSymbolNames()
SymbolNameVector llvm::orc::SymbolLookupSet::getSymbolNames () const inline
Construct a SymbolNameVector from this instance by dropping the Flags values.
Definition at line 249 of file Core.h.
Referenced by llvm::orc::buildSimpleReexportsAliasMap().
remove() [1/2]
void llvm::orc::SymbolLookupSet::remove (UnderlyingVector::size_type I) inline
Removes the Ith element of the vector, replacing it with the last element.
Definition at line 176 of file Core.h.
References I, and std::swap().
remove() [2/2]
void llvm::orc::SymbolLookupSet::remove (iterator I) inline
Removes the element pointed to by the given iterator.
This iterator and all subsequent ones (including end()) are invalidated.
Definition at line 183 of file Core.h.
References llvm::sys::path::begin(), and I.
remove_if()
template<typename PredFn > void llvm::orc::SymbolLookupSet::remove_if (PredFn && Pred) inline
Removes all elements matching the given predicate, which must be callable as bool(const SymbolStringPtr &, SymbolLookupFlags Flags).
Definition at line 187 of file Core.h.
References I, and Name.
removeDuplicates()
void llvm::orc::SymbolLookupSet::removeDuplicates () inline
Remove any duplicate elements.
If a SymbolLookupSet is not duplicate-free by construction, this method can be used to turn it into a proper set.
Definition at line 276 of file Core.h.
size()
UnderlyingVector::size_type llvm::orc::SymbolLookupSet::size () const inline
Definition at line 169 of file Core.h.
Referenced by llvm::orc::AsynchronousSymbolQuery::AsynchronousSymbolQuery().
sortByAddress()
void llvm::orc::SymbolLookupSet::sortByAddress () inline
Sort the lookup set by pointer value.
This sort is fast but sensitive to allocation order and so should not be used where a consistent order is required.
Definition at line 260 of file Core.h.
References llvm::sort().
sortByName()
void llvm::orc::SymbolLookupSet::sortByName () inline
Sort the lookup set lexicographically.
This sort is slow but the order is unaffected by allocation order.
Definition at line 268 of file Core.h.
References llvm::sort().
Referenced by llvm::orc::buildSimpleReexportsAliasMap().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Core.h