LLVM: llvm::ModuloScheduleExpander Class Reference
llvm::ModuloScheduleExpander Class Reference
The ModuloScheduleExpander takes a ModuloSchedule and expands it in-place, rewriting the old loop and inserting prologs and epilogs as required.
#include "llvm/CodeGen/ModuloSchedule.h"
Public Types
using InstrChangesTy = DenseMap< MachineInstr *, std::pair< unsigned, int64_t > >
Public Member Functions
ModuloScheduleExpander (MachineFunction &MF, ModuloSchedule &S, LiveIntervals &LIS, InstrChangesTy InstrChanges)
Create a new ModuloScheduleExpander.
void expand ()
Performs the actual expansion.
void cleanup ()
Performs final cleanup after expansion.
MachineBasicBlock * getRewrittenKernel ()
Returns the newly rewritten kernel block, or nullptr if this was optimized away.
Detailed Description
The ModuloScheduleExpander takes a ModuloSchedule and expands it in-place, rewriting the old loop and inserting prologs and epilogs as required.
Definition at line 153 of file ModuloSchedule.h.
Member Typedef Documentation
InstrChangesTy
using llvm::ModuloScheduleExpander::InstrChangesTy = DenseMap<MachineInstr *, std::pair<unsigned, int64_t> >
Definition at line 155 of file ModuloSchedule.h.
Constructor & Destructor Documentation
ModuloScheduleExpander()
llvm::ModuloScheduleExpander::ModuloScheduleExpander (MachineFunction & MF, ModuloSchedule & S, LiveIntervals & LIS, InstrChangesTy InstrChanges) inline
Create a new ModuloScheduleExpander.
InstrChanges Modifications to make to instructions with memory operands. FIXME: InstrChanges is opaque and is an implementation detail of an optimization in MachinePipeliner that crosses abstraction boundaries.
Definition at line 255 of file ModuloSchedule.h.
References cleanup(), and expand().
Member Function Documentation
cleanup()
void ModuloScheduleExpander::cleanup ()
Performs final cleanup after expansion.
Definition at line 182 of file ModuloSchedule.cpp.
References llvm::MachineBasicBlock::addSuccessor(), llvm::dbgs(), llvm::MachineBasicBlock::dump(), I, LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineBasicBlock::push_back(), llvm::HexagonInstrInfo::removeBranch(), llvm::MachineBasicBlock::replaceSuccessor(), TII, and llvm::MachineBasicBlock::transferSuccessors().
Referenced by parseSymbolString(), llvm::SwingSchedulerDAG::schedule(), and llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander().
expand()
void ModuloScheduleExpander::expand ()
Performs the actual expansion.
Definition at line 67 of file ModuloSchedule.cpp.
References llvm::HexagonInstrInfo::analyzeLoopForPipelining(), assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::dbgs(), llvm::numbers::e, E, llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), I, llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), LLVM_DEBUG, llvm::max(), MI, MRI, llvm::MachineBasicBlock::push_back(), Reg, llvm::MachineBasicBlock::replaceSuccessor(), TII, llvm::MachineBasicBlock::transferSuccessors(), and UseMI.
Referenced by parseSymbolString(), llvm::SwingSchedulerDAG::schedule(), and llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander().
getRewrittenKernel()
MachineBasicBlock* llvm::ModuloScheduleExpander::getRewrittenKernel () inline
Returns the newly rewritten kernel block, or nullptr if this was optimized away.
Definition at line 268 of file ModuloSchedule.h.
Referenced by llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ModuloSchedule.h
lib/CodeGen/ModuloSchedule.cpp