LLVM: llvm::BitcodeAnalyzer Class Reference
llvm::BitcodeAnalyzer Class Reference
#include "llvm/Bitcode/BitcodeAnalyzer.h"
Public Member Functions
BitcodeAnalyzer (StringRef Buffer, Optional< StringRef > BlockInfoBuffer=None)
Error analyze (Optional< BCDumpOptions > O=None, Optional< StringRef > CheckHash=None)
Analyze the bitcode file.
void printStats (BCDumpOptions O, Optional< StringRef > Filename=None)
Print stats about the bitcode file.
Detailed Description
Definition at line 49 of file BitcodeAnalyzer.h.
Constructor & Destructor Documentation
BitcodeAnalyzer()
BitcodeAnalyzer::BitcodeAnalyzer (StringRef Buffer, Optional< StringRef > BlockInfoBuffer = None)
Definition at line 540 of file BitcodeAnalyzer.cpp.
Member Function Documentation
analyze()
Error BitcodeAnalyzer::analyze (Optional< BCDumpOptions > O = None, Optional< StringRef > CheckHash = None)
Analyze the bitcode file.
Definition at line 547 of file BitcodeAnalyzer.cpp.
References analyzeHeader(), llvm::SimpleBitstreamCursor::AtEndOfStream(), llvm::bitc::BLOCKINFO_BLOCK_ID, llvm::bitc::ENTER_SUBBLOCK, llvm::Expected< T >::get(), H, llvm::BitstreamCursor::ReadBlockInfoBlock(), llvm::BitstreamCursor::ReadCode(), llvm::BitstreamCursor::ReadSubBlockID(), reportError(), llvm::BitstreamCursor::setBlockInfo(), and llvm::Expected< T >::takeError().
printStats()
void BitcodeAnalyzer::printStats (BCDumpOptions O, Optional< StringRef > Filename = None)
Print stats about the bitcode file.
Definition at line 613 of file BitcodeAnalyzer.cpp.
References llvm::bitc::BLOCKINFO_BLOCK_ID, llvm::ClangSerializedASTBitstream, llvm::ClangSerializedDiagnosticsBitstream, llvm::StringRef::data(), llvm::numbers::e, E, llvm::format(), llvm::Expected< T >::get(), llvm::SimpleBitstreamCursor::getBitcodeBytes(), GetBlockName(), GetCodeName(), llvm::SimpleBitstreamCursor::GetCurrentBitNo(), llvm::Optional< T >::hasValue(), llvm::BCDumpOptions::Histogram, I, llvm::LLVMBitstreamRemarks, llvm::LLVMIRBitstream, llvm::RISCVFenceField::O, llvm::BCDumpOptions::OS, printSize(), llvm::BitstreamCursor::ReadBlockInfoBlock(), reportError(), llvm::reverse(), second, llvm::ArrayRef< T >::size(), llvm::stable_sort(), Stats, llvm::Expected< T >::takeError(), and llvm::UnknownBitstream.
The documentation for this class was generated from the following files:
include/llvm/Bitcode/BitcodeAnalyzer.h
lib/Bitcode/Reader/BitcodeAnalyzer.cpp