LLVM: llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator Class Reference
llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator Class Reference
Public Member Functions
PHI_iterator (PHINode *P)
PHI_iterator (PHINode *P, bool)
PHI_iterator & operator++ ()
bool operator== (const PHI_iterator &x) const
bool operator!= (const PHI_iterator &x) const
Value * getIncomingValue ()
BasicBlock * getIncomingBlock ()
Detailed Description
template<>
class llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator
Definition at line 231 of file SSAUpdater.cpp.
Constructor & Destructor Documentation
PHI_iterator() [1/2]
llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::PHI_iterator (PHINode * P) inline explicit
Definition at line 237 of file SSAUpdater.cpp.
PHI_iterator() [2/2]
llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::PHI_iterator (PHINode * P, bool) inline
Definition at line 239 of file SSAUpdater.cpp.
Member Function Documentation
getIncomingBlock()
BasicBlock* llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::getIncomingBlock () inline
Definition at line 247 of file SSAUpdater.cpp.
References llvm::PHINode::getIncomingBlock().
getIncomingValue()
Value* llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::getIncomingValue () inline
Definition at line 246 of file SSAUpdater.cpp.
References llvm::PHINode::getIncomingValue().
operator!=()
bool llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::operator!= (const PHI_iterator & x) const inline
Definition at line 244 of file SSAUpdater.cpp.
References llvm::operator==().
operator++()
PHI_iterator& llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::operator++ () inline
Definition at line 242 of file SSAUpdater.cpp.
operator==()
bool llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::operator== (const PHI_iterator & x) const inline
Definition at line 243 of file SSAUpdater.cpp.
The documentation for this class was generated from the following file:
lib/Transforms/Utils/SSAUpdater.cpp