LLVM: llvm::GCNIterativeScheduler::BuildDAG Class Reference
llvm::GCNIterativeScheduler::BuildDAG Class Reference
Public Member Functions
BuildDAG (const Region &R, GCNIterativeScheduler &_Sch)
~BuildDAG ()
ArrayRef< const SUnit * > getTopRoots () const
ArrayRef< SUnit * > getBottomRoots () const
Detailed Description
Definition at line 143 of file GCNIterativeScheduler.cpp.
Constructor & Destructor Documentation
BuildDAG()
llvm::GCNIterativeScheduler::BuildDAG::BuildDAG (const Region & R, GCNIterativeScheduler & _Sch) inline
Definition at line 149 of file GCNIterativeScheduler.cpp.
References llvm::ScheduleDAGMI::AA, llvm::ScheduleDAGInstrs::BB, llvm::GCNIterativeScheduler::Region::Begin, llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::GCNIterativeScheduler::Region::End, llvm::ScheduleDAGMI::findRootsAndBiasEdges(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::GCNIterativeScheduler::Region::NumRegionInstrs, and llvm::ScheduleDAGInstrs::Topo.
~BuildDAG()
llvm::GCNIterativeScheduler::BuildDAG::~BuildDAG () inline
Definition at line 161 of file GCNIterativeScheduler.cpp.
Member Function Documentation
getBottomRoots()
ArrayRef<SUnit*> llvm::GCNIterativeScheduler::BuildDAG::getBottomRoots () const inline
Definition at line 169 of file GCNIterativeScheduler.cpp.
Referenced by llvm::GCNIterativeScheduler::scheduleILP().
getTopRoots()
ArrayRef<const SUnit *> llvm::GCNIterativeScheduler::BuildDAG::getTopRoots () const inline
Definition at line 166 of file GCNIterativeScheduler.cpp.
Referenced by llvm::GCNIterativeScheduler::scheduleMinReg(), and llvm::GCNIterativeScheduler::tryMaximizeOccupancy().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/GCNIterativeScheduler.cpp