LLVM: llvm::GVN::ValueTable Class Reference
llvm::GVN::ValueTable Class Reference
This class holds the mapping between values and value numbers.
#include "llvm/Transforms/Scalar/GVN.h"
Public Member Functions
ValueTable ()
ValueTable (const ValueTable &Arg)
ValueTable (ValueTable &&Arg)
~ValueTable ()
ValueTable & operator= (const ValueTable &Arg)
uint32_t lookupOrAdd (Value *V)
lookup_or_add - Returns the value number for the specified value, assigning it a new number if it did not have one before.
uint32_t lookup (Value *V, bool Verify=true) const
Returns the value number of the specified value.
uint32_t lookupOrAddCmp (unsigned Opcode, CmpInst::Predicate Pred, Value *LHS, Value *RHS)
Returns the value number of the given comparison, assigning it a new number if it did not have one before.
uint32_t phiTranslate (const BasicBlock *BB, const BasicBlock *PhiBlock, uint32_t Num, GVN &Gvn)
Wrap phiTranslateImpl to provide caching functionality.
void eraseTranslateCacheEntry (uint32_t Num, const BasicBlock &CurrBlock)
Erase stale entry from phiTranslate cache so phiTranslate can be computed again.
bool exists (Value *V) const
Returns true if a value number exists for the specified value.
void add (Value *V, uint32_t num)
add - Insert a value into the table with a specified value number.
void clear ()
Remove all entries from the ValueTable.
void erase (Value *v)
Remove a value from the value numbering.
void setAliasAnalysis (AliasAnalysis *A)
AliasAnalysis * getAliasAnalysis () const
void setMemDep (MemoryDependenceResults *M)
void setDomTree (DominatorTree *D)
uint32_t getNextUnusedValueNumber ()
void verifyRemoved (const Value *) const
verifyRemoved - Verify that the value is removed from all internal data structures.
Detailed Description
This class holds the mapping between values and value numbers.
It is used as an efficient mechanism to determine the expression-wise equivalence of two values.
Definition at line 89 of file GVN.h.
Constructor & Destructor Documentation
ValueTable() [1/3]
GVN::ValueTable::ValueTable () default
Referenced by llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue().
ValueTable() [2/3]
GVN::ValueTable::ValueTable (const ValueTable & Arg) default
ValueTable() [3/3]
GVN::ValueTable::ValueTable (ValueTable && Arg) default
~ValueTable()
GVN::ValueTable::~ValueTable () default
Referenced by llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue().
Member Function Documentation
add()
void GVN::ValueTable::add (Value * V, uint32_t num)
add - Insert a value into the table with a specified value number.
Definition at line 371 of file GVN.cpp.
References C, llvm::dyn_cast(), llvm::numbers::e, llvm::CallBase::getArgOperand(), llvm::NonLocalDepEntry::getBB(), llvm::MemDepResult::getInst(), llvm::CallBase::getNumArgOperands(), llvm::Instruction::getParent(), llvm::NonLocalDepEntry::getResult(), llvm::MemDepResult::isDef(), and llvm::MemDepResult::isNonLocal().
clear()
void GVN::ValueTable::clear ()
Remove all entries from the ValueTable.
Definition at line 580 of file GVN.cpp.
References Expressions.
erase()
void GVN::ValueTable::erase (Value * v)
Remove a value from the value numbering.
Definition at line 592 of file GVN.cpp.
eraseTranslateCacheEntry()
void GVN::ValueTable::eraseTranslateCacheEntry (uint32_t Num, const BasicBlock & CurrBlock)
Erase stale entry from phiTranslate cache so phiTranslate can be computed again.
Definition at line 1740 of file GVN.cpp.
References if(), and llvm::predecessors().
exists()
bool GVN::ValueTable::exists (Value * V) const
Returns true if a value number exists for the specified value.
Definition at line 479 of file GVN.cpp.
getAliasAnalysis()
AliasAnalysis* llvm::GVN::ValueTable::getAliasAnalysis () const inline
Definition at line 147 of file GVN.h.
getNextUnusedValueNumber()
uint32_t llvm::GVN::ValueTable::getNextUnusedValueNumber () inline
Definition at line 150 of file GVN.h.
lookup()
uint32_t GVN::ValueTable::lookup (Value * V, bool Verify = true) const
Returns the value number of the specified value.
Fails if the value has not yet been numbered.
Definition at line 559 of file GVN.cpp.
References assert(), and VI.
lookupOrAdd()
uint32_t GVN::ValueTable::lookupOrAdd (Value * V)
lookup_or_add - Returns the value number for the specified value, assigning it a new number if it did not have one before.
Definition at line 483 of file GVN.cpp.
References llvm::MCID::Add, llvm::MCID::Call, llvm::numbers::e, llvm::Instruction::getOpcode(), if(), llvm::MCID::Select, and VI.
Referenced by llvm::InsnInfo::insert(), llvm::LoadInfo::insert(), llvm::StoreInfo::insert(), and llvm::CallInfo::insert().
lookupOrAddCmp()
uint32_t GVN::ValueTable::lookupOrAddCmp (unsigned Opcode, CmpInst::Predicate Predicate, Value * LHS, Value * RHS)
Returns the value number of the given comparison, assigning it a new number if it did not have one before.
Useful when we deduced the result of a comparison, but don't immediately have an instruction realizing that comparison to hand.
Definition at line 572 of file GVN.cpp.
operator=()
GVN::ValueTable & GVN::ValueTable::operator= (const ValueTable & Arg) default
Referenced by llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue().
phiTranslate()
uint32_t GVN::ValueTable::phiTranslate (const BasicBlock * BB, const BasicBlock * PhiBlock, uint32_t Num, GVN & Gvn)
Wrap phiTranslateImpl to provide caching functionality.
Definition at line 1638 of file GVN.cpp.
References assert(), llvm::MCID::Call, llvm::GVN::Expression::commutative, llvm::dyn_cast(), Expressions, llvm::Instruction::getParent(), llvm::CmpInst::getSwappedPredicate(), llvm::MemDepResult::isNonLocal(), lookup(), llvm::GVN::Expression::opcode, llvm::SmallVectorBase::size(), std::swap(), and llvm::GVN::Expression::varargs.
setAliasAnalysis()
void llvm::GVN::ValueTable::setAliasAnalysis (AliasAnalysis * A) inline
Definition at line 146 of file GVN.h.
setDomTree()
void llvm::GVN::ValueTable::setDomTree (DominatorTree * D) inline
Definition at line 149 of file GVN.h.
References D.
setMemDep()
void llvm::GVN::ValueTable::setMemDep (MemoryDependenceResults * M) inline
Definition at line 148 of file GVN.h.
verifyRemoved()
void GVN::ValueTable::verifyRemoved (const Value * V) const
verifyRemoved - Verify that the value is removed from all internal data structures.
Definition at line 602 of file GVN.cpp.
References assert(), E, and I.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/GVN.h
lib/Transforms/Scalar/GVN.cpp