LLVM: llvm::GlobalsMetadata Class Reference
llvm::GlobalsMetadata Class Reference
Frontend-provided metadata for global variables.
#include "llvm/Transforms/Instrumentation/AddressSanitizer.h"
Classes
struct Entry
Public Member Functions
GlobalsMetadata ()=default
Create a default uninitialized GlobalsMetadata instance.
GlobalsMetadata (Module &M)
Create an initialized GlobalsMetadata instance.
Entry get (GlobalVariable *G) const
Returns metadata entry for a given global.
bool invalidate (Module &, const PreservedAnalyses &, ModuleAnalysisManager::Invalidator &)
Handle invalidation from the pass manager.
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Detailed Description
Frontend-provided metadata for global variables.
Definition at line 36 of file AddressSanitizer.h.
Constructor & Destructor Documentation
GlobalsMetadata() [1/2]
llvm::GlobalsMetadata::GlobalsMetadata () default
Create a default uninitialized GlobalsMetadata instance.
GlobalsMetadata() [2/2]
GlobalsMetadata::GlobalsMetadata (Module & M)
Create an initialized GlobalsMetadata instance.
Definition at line 1126 of file AddressSanitizer.cpp.
References assert(), llvm::dyn_cast(), E, llvm::Module::getNamedMetadata(), llvm::GlobalsMetadata::Entry::IsBlacklisted, llvm::GlobalsMetadata::Entry::IsDynInit, llvm::ConstantInt::isOne(), llvm::GlobalsMetadata::Entry::Name, Name, llvm::NamedMDNode::operands(), llvm::LocationMetadata::parse(), and llvm::GlobalsMetadata::Entry::SourceLoc.
Member Function Documentation
get()
Entry llvm::GlobalsMetadata::get (GlobalVariable * G) const inline
Returns metadata entry for a given global.
Definition at line 54 of file AddressSanitizer.h.
References G.
invalidate() [1/2]
bool llvm::GlobalsMetadata::invalidate (Module & , const PreservedAnalyses & , ModuleAnalysisManager::Invalidator &) inline
Handle invalidation from the pass manager.
These results are never invalidated.
Definition at line 61 of file AddressSanitizer.h.
invalidate() [2/2]
bool llvm::GlobalsMetadata::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Definition at line 65 of file AddressSanitizer.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/AddressSanitizer.h
lib/Transforms/Instrumentation/AddressSanitizer.cpp