LLVM: llvm::DIInliningInfo Class Reference
llvm::DIInliningInfo Class Reference
A format-neutral container for inlined code description.
#include "llvm/DebugInfo/DIContext.h"
Public Member Functions
DIInliningInfo ()=default
const DILineInfo & getFrame (unsigned Index) const
DILineInfo * getMutableFrame (unsigned Index)
uint32_t getNumberOfFrames () const
void addFrame (const DILineInfo &Frame)
void resize (unsigned i)
Detailed Description
A format-neutral container for inlined code description.
Definition at line 81 of file DIContext.h.
Constructor & Destructor Documentation
DIInliningInfo()
llvm::DIInliningInfo::DIInliningInfo () default
Member Function Documentation
addFrame()
void llvm::DIInliningInfo::addFrame (const DILineInfo & Frame) inline
Definition at line 101 of file DIContext.h.
References llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::pdb::PDBContext::getInliningInfoForAddress(), llvm::DWARFContext::getInliningInfoForAddress(), and llvm::symbolize::SymbolizableObjectFile::symbolizeInlinedCode().
getFrame()
const DILineInfo& llvm::DIInliningInfo::getFrame (unsigned Index) const inline
Definition at line 87 of file DIContext.h.
References assert(), and llvm::SmallVectorBase::size().
Referenced by llvm::symbolize::DIPrinter::operator<<().
getMutableFrame()
DILineInfo* llvm::DIInliningInfo::getMutableFrame (unsigned Index) inline
Definition at line 92 of file DIContext.h.
References assert(), and llvm::SmallVectorBase::size().
Referenced by llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode().
getNumberOfFrames()
uint32_t llvm::DIInliningInfo::getNumberOfFrames () const inline
Definition at line 97 of file DIContext.h.
References llvm::SmallVectorBase::size().
Referenced by llvm::symbolize::DIPrinter::operator<<(), llvm::symbolize::SymbolizableObjectFile::symbolizeInlinedCode(), and llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode().
resize()
void llvm::DIInliningInfo::resize (unsigned i) inline
Definition at line 105 of file DIContext.h.
References llvm::SmallVectorImpl< T >::resize().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DIContext.h