LLVM: llvm::DIEUnit Class Reference
llvm::DIEUnit Class Reference
Represents a compile or type unit.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEUnit (uint16_t Version, uint8_t AddrSize, dwarf::Tag UnitTag)
DIEUnit (const DIEUnit &RHS)=delete
DIEUnit (DIEUnit &&RHS)=delete
void operator= (const DIEUnit &RHS)=delete
void operator= (const DIEUnit &&RHS)=delete
void setSection (MCSection *Section)
Set the section that this DIEUnit will be emitted into.
virtual const MCSymbol * getCrossSectionRelativeBaseAddress () const
MCSection * getSection () const
Return the section that this DIEUnit will be emitted into.
void setDebugSectionOffset (unsigned O)
unsigned getDebugSectionOffset () const
void setLength (uint64_t L)
uint64_t getLength () const
uint16_t getDwarfVersion () const
uint16_t getAddressSize () const
DIE & getUnitDie ()
const DIE & getUnitDie () const
Protected Member Functions
virtual ~DIEUnit ()=default
The size in bytes of an address for this unit.
Detailed Description
Represents a compile or type unit.
Definition at line 845 of file DIE.h.
Constructor & Destructor Documentation
~DIEUnit()
virtual llvm::DIEUnit::~DIEUnit () protected virtual default
The size in bytes of an address for this unit.
DIEUnit() [1/3]
DIEUnit::DIEUnit (uint16_t Version, uint8_t AddrSize, dwarf::Tag UnitTag)
Definition at line 316 of file DIE.cpp.
References assert().
DIEUnit() [2/3]
llvm::DIEUnit::DIEUnit (const DIEUnit & RHS) delete
DIEUnit() [3/3]
llvm::DIEUnit::DIEUnit (DIEUnit && RHS) delete
Member Function Documentation
getAddressSize()
uint16_t llvm::DIEUnit::getAddressSize () const inline
Definition at line 890 of file DIE.h.
getCrossSectionRelativeBaseAddress()
virtual const MCSymbol* llvm::DIEUnit::getCrossSectionRelativeBaseAddress () const inline virtual
Definition at line 877 of file DIE.h.
getDebugSectionOffset()
unsigned llvm::DIEUnit::getDebugSectionOffset () const inline
Definition at line 886 of file DIE.h.
Referenced by computeIndexValue(), and llvm::DIE::getDebugSectionOffset().
getDwarfVersion()
uint16_t llvm::DIEUnit::getDwarfVersion () const inline
Definition at line 889 of file DIE.h.
References llvm::IndexedInstrProf::Version.
getLength()
uint64_t llvm::DIEUnit::getLength () const inline
Definition at line 888 of file DIE.h.
getSection()
MCSection* llvm::DIEUnit::getSection () const inline
Return the section that this DIEUnit will be emitted into.
Returns
Section pointer which can be NULL.
Definition at line 884 of file DIE.h.
References llvm::ARMBuildAttrs::Section.
Referenced by llvm::DwarfTypeUnit::addGlobalType(), computeIndexValue(), and llvm::DwarfFile::emitUnit().
getUnitDie() [1/2]
DIE& llvm::DIEUnit::getUnitDie () inline
Definition at line 891 of file DIE.h.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), llvm::DwarfUnit::addDIEEntry(), llvm::DwarfCompileUnit::addGlobalNameForTypeUnit(), llvm::DwarfCompileUnit::addGlobalTypeUnitType(), llvm::DwarfUnit::addRnglistsBase(), llvm::DwarfUnit::addStringOffsetsStart(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfDebug::beginModule(), collectCallSiteParameters(), llvm::DwarfFile::computeSizeAndOffsetsForUnit(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::createBaseTypeDIEs(), llvm::DwarfUnit::emitCommonHeader(), emitRangeList(), llvm::DwarfFile::emitUnit(), llvm::DwarfUnit::getMD5AsBytes(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::CompileUnit::getOutputUnitDIE(), llvm::DwarfUnit::hasContent(), and llvm::DwarfCompileUnit::initStmtList().
getUnitDie() [2/2]
const DIE& llvm::DIEUnit::getUnitDie () const inline
Definition at line 892 of file DIE.h.
operator=() [1/2]
void llvm::DIEUnit::operator= (const DIEUnit & RHS) delete
operator=() [2/2]
void llvm::DIEUnit::operator= (const DIEUnit && RHS) delete
setDebugSectionOffset()
void llvm::DIEUnit::setDebugSectionOffset (unsigned O) inline
Definition at line 885 of file DIE.h.
References llvm::RISCVFenceField::O.
setLength()
void llvm::DIEUnit::setLength (uint64_t L) inline
Definition at line 887 of file DIE.h.
setSection()
void llvm::DIEUnit::setSection (MCSection * Section) inline
Set the section that this DIEUnit will be emitted into.
This function is used by some clients to set the section. Not all clients that emit DWARF use this section variable.
Definition at line 872 of file DIE.h.
References assert(), and llvm::ARMBuildAttrs::Section.
Referenced by emitRangeList().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp