LLVM: llvm::TBAAVerifier Class Reference
llvm::TBAAVerifier Class Reference
Verify that the TBAA Metadatas are valid.
#include "llvm/IR/Verifier.h"
Public Member Functions
TBAAVerifier (VerifierSupport *Diagnostic=nullptr)
bool visitTBAAMetadata (Instruction &I, const MDNode *MD)
Visit an instruction and return true if it is valid, return false if an invalid TBAA is attached.
Detailed Description
Verify that the TBAA Metadatas are valid.
Definition at line 39 of file Verifier.h.
Constructor & Destructor Documentation
TBAAVerifier()
llvm::TBAAVerifier::TBAAVerifier (VerifierSupport * Diagnostic = nullptr) inline
Definition at line 75 of file Verifier.h.
References llvm::createVerifierPass(), F(), llvm::verifyFunction(), llvm::verifyModule(), and visitTBAAMetadata().
Member Function Documentation
visitTBAAMetadata()
bool TBAAVerifier::visitTBAAMetadata (Instruction & I, const MDNode * MD)
Visit an instruction and return true if it is valid, return false if an invalid TBAA is attached.
Definition at line 5414 of file Verifier.cpp.
References AssertTBAA, llvm::VerifierSupport::CheckFailed(), llvm::APInt::getBitWidth(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), I, INITIALIZE_PASS, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Invalid, isNewFormatTBAATypeNode(), and IsRootTBAANode().
Referenced by TBAAVerifier().
The documentation for this class was generated from the following files:
include/llvm/IR/Verifier.h
lib/IR/Verifier.cpp