LLVM: llvm::ARCInstrInfo Class Reference
llvm::ARCInstrInfo Class Reference
#include "Target/ARC/ARCInstrInfo.h"
Public Member Functions
ARCInstrInfo ()
const ARCRegisterInfo & getRegisterInfo () const
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
If the specified machine instruction is a direct load from a stack slot, return the virtual or physical register number of the destination along with the FrameIndex of the loaded stack slot.
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
If the specified machine instruction is a direct store to a stack slot, return the virtual or physical register number of the source reg along with the FrameIndex of the loaded stack slot.
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
Analyze the branching code at the end of MBB, returning true if it cannot be understood (e.g.
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &dl, int *BytesAdded=nullptr) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &dl, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
Return the inverse opcode of the specified Branch instruction.
bool isPostIncrement (const MachineInstr &MI) const override
bool isPreIncrement (const MachineInstr &MI) const
virtual bool getBaseAndOffsetPosition (const MachineInstr &MI, unsigned &BasePos, unsigned &OffsetPos) const override
MachineBasicBlock::iterator loadImmediate (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned Reg, uint64_t Value) const
Detailed Description
Definition at line 26 of file ARCInstrInfo.h.
Constructor & Destructor Documentation
ARCInstrInfo()
ARCInstrInfo::ARCInstrInfo ()
Definition at line 46 of file ARCInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool ARCInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Analyze the branching code at the end of MBB, returning true if it cannot be understood (e.g.
it's a switch dispatch or isn't implemented for a target). Upon success, this returns false and returns with the following information in various cases:
If this block ends with no branches (it just falls through to its succ) just return false, leaving TBB/FBB null.
If this block ends with only an unconditional branch, it sets TBB to be the destination block.
If this block ends with a conditional branch and it falls through to a successor block, it sets TBB to be the branch destination block and a list of operands that evaluate the condition. These operands can be passed to other TargetInstrInfo methods to create new branches.
If this block ends with a conditional branch followed by an unconditional branch, it returns the 'true' destination in TBB, the 'false' destination in FBB, and a list of operands that evaluate the condition. These operands can be passed to other TargetInstrInfo methods to create new branches.
Note that RemoveBranch and InsertBranch must be implemented to support cases where this method returns success.
If AllowModify is true, then this routine is allowed to modify the basic block (e.g. delete instructions after the unconditional branch).
Definition at line 170 of file ARCInstrInfo.cpp.
Referenced by getRegisterInfo().
copyPhysReg()
void ARCInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & dl, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 281 of file ARCInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), and llvm::getKillRegState().
getBaseAndOffsetPosition()
bool ARCInstrInfo::getBaseAndOffsetPosition (const MachineInstr & MI, unsigned & BasePos, unsigned & OffsetPos) const override virtual
Definition at line 424 of file ARCInstrInfo.cpp.
References llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), isPostIncrement(), isPreIncrement(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoad(), and llvm::MachineInstr::mayStore().
getInstSizeInBytes()
unsigned ARCInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
Definition at line 403 of file ARCInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MCInstrDesc::getSize(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), and llvm::MachineInstr::isInlineAsm().
Referenced by getRegisterInfo().
getRegisterInfo()
const ARCRegisterInfo& llvm::ARCInstrInfo::getRegisterInfo () const inline
Definition at line 33 of file ARCInstrInfo.h.
References analyzeBranch(), llvm::ISD::FrameIndex, getInstSizeInBytes(), isLoadFromStackSlot(), isStoreToStackSlot(), and MI.
Referenced by llvm::ARCSubtarget::getRegisterInfo().
insertBranch()
unsigned ARCInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & dl, int * BytesAdded = nullptr) const override
Definition at line 370 of file ARCInstrInfo.cpp.
isLoadFromStackSlot()
unsigned ARCInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
If the specified machine instruction is a direct load from a stack slot, return the virtual or physical register number of the destination along with the FrameIndex of the loaded stack slot.
If not, return 0. This predicate must return 0 if the instruction has any side effects other than loading from the stack slot.
Definition at line 68 of file ARCInstrInfo.cpp.
References llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), isLoad(), and isZeroImm().
Referenced by getRegisterInfo().
isPostIncrement()
bool ARCInstrInfo::isPostIncrement (const MachineInstr & MI) const override
Definition at line 412 of file ARCInstrInfo.cpp.
References F(), llvm::MachineInstr::getDesc(), PostInc, TSF_AddModeMask, TSF_AddrModeOff, and llvm::MCInstrDesc::TSFlags.
Referenced by getBaseAndOffsetPosition().
isPreIncrement()
bool ARCInstrInfo::isPreIncrement (const MachineInstr & MI) const
Definition at line 418 of file ARCInstrInfo.cpp.
References F(), llvm::MachineInstr::getDesc(), PreInc, TSF_AddModeMask, TSF_AddrModeOff, and llvm::MCInstrDesc::TSFlags.
Referenced by getBaseAndOffsetPosition().
isStoreToStackSlot()
unsigned ARCInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
If the specified machine instruction is a direct store to a stack slot, return the virtual or physical register number of the source reg along with the FrameIndex of the loaded stack slot.
If not, return 0. This predicate must return 0 if the instruction has any side effects other than storing to the stack slot.
Definition at line 87 of file ARCInstrInfo.cpp.
References llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), isStore(), and isZeroImm().
Referenced by getRegisterInfo().
loadImmediate()
MachineBasicBlock::iterator ARCInstrInfo::loadImmediate (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned Reg, uint64_t Value) const
Definition at line 358 of file ARCInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineInstrBuilder::getInstr(), and llvm_unreachable.
loadRegFromStackSlot()
void ARCInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 322 of file ARCInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::BuildMI(), llvm::dbgs(), llvm::RegState::Define, llvm::MachineBasicBlock::findDebugLoc(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getSpillSize(), LLVM_DEBUG, llvm::MachineMemOperand::MOLoad, and llvm::printReg().
removeBranch()
unsigned ARCInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 254 of file ARCInstrInfo.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), I, llvm::isCondBranchOpcode(), and llvm::isUncondBranchOpcode().
reverseBranchCondition()
bool ARCInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Return the inverse opcode of the specified Branch instruction.
Definition at line 350 of file ARCInstrInfo.cpp.
storeRegToStackSlot()
void ARCInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 293 of file ARCInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::BuildMI(), llvm::dbgs(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getSpillSize(), LLVM_DEBUG, llvm::MachineMemOperand::MOStore, and llvm::printReg().
The documentation for this class was generated from the following files:
lib/Target/ARC/ARCInstrInfo.h
lib/Target/ARC/ARCInstrInfo.cpp