LLVM: llvm::R600SchedStrategy Class Reference
llvm::R600SchedStrategy Class Reference final
#include "Target/AMDGPU/R600MachineScheduler.h"
Public Member Functions
R600SchedStrategy ()=default
~R600SchedStrategy () override=default
void initialize (ScheduleDAGMI *dag) override
Initialize the strategy after building the DAG for a new region.
SUnit * pickNode (bool &IsTopNode) override
Pick the next node to schedule, or return NULL.
void schedNode (SUnit *SU, bool IsTopNode) override
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual void dumpPolicy () const
virtual bool shouldTrackPressure () const
Check if pressure tracking is needed before building the DAG and initializing this strategy.
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void registerRoots ()
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
Detailed Description
Definition at line 27 of file R600MachineScheduler.h.
Constructor & Destructor Documentation
R600SchedStrategy()
llvm::R600SchedStrategy::R600SchedStrategy () default
~R600SchedStrategy()
llvm::R600SchedStrategy::~R600SchedStrategy () override default
Member Function Documentation
initialize()
void R600SchedStrategy::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Definition at line 27 of file R600MachineScheduler.cpp.
References assert(), llvm::R600Subtarget::getTexVTXClauseSize(), llvm::R600Subtarget::hasCaymanISA(), llvm::ScheduleDAGMI::hasVRegLiveness(), and llvm::ARM_MB::ST.
pickNode()
SUnit * R600SchedStrategy::pickNode (bool & IsTopNode) override virtual
Pick the next node to schedule, or return NULL.
Set IsTopNode to true to schedule the node at the top of the unscheduled region. Otherwise it will be scheduled at the bottom.
Implements llvm::MachineSchedStrategy.
Definition at line 57 of file R600MachineScheduler.cpp.
References llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::empty(), getWFCountLimitedByGPR(), llvm::SUnit::isScheduled, LLVM_DEBUG, llvm::size(), and llvm::ScheduleDAG::SUnits.
releaseBottomNode()
void R600SchedStrategy::releaseBottomNode (SUnit * SU) override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 193 of file R600MachineScheduler.cpp.
References assert(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::TargetRegisterClass::contains(), llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::numbers::e, E, llvm::empty(), llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::SUnit::getInstr(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::R600InstrInfo::getOperandIdx(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), llvm::R600InstrInfo::isALUInstr(), llvm::R600InstrInfo::isCubeOp(), llvm::MachineOperand::isDef(), llvm::R600InstrInfo::isLDSInstr(), isPhysicalRegCopy(), llvm::R600InstrInfo::isReductionOp(), llvm::MachineOperand::isReg(), llvm::R600InstrInfo::isTransOnly(), llvm::MachineOperand::isUndef(), llvm::R600InstrInfo::isVector(), llvm::R600InstrInfo::isVectorOnly(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MI, llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::R600InstrInfo::readsLDSSrcReg(), Reg, llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
releaseTopNode()
void R600SchedStrategy::releaseTopNode (SUnit * SU) override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 189 of file R600MachineScheduler.cpp.
References llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), and LLVM_DEBUG.
schedNode()
void R600SchedStrategy::schedNode (SUnit * SU, bool IsTopNode) override virtual
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
Implements llvm::MachineSchedStrategy.
Definition at line 142 of file R600MachineScheduler.cpp.
References llvm::dbgs(), E, llvm::SUnit::getInstr(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), LLVM_DEBUG, llvm::MachineInstr::operands_begin(), and llvm::MachineInstr::operands_end().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/R600MachineScheduler.h
lib/Target/AMDGPU/R600MachineScheduler.cpp