LLVM: llvm::PassNameParser Class Reference
llvm::PassNameParser Class Reference
#include "llvm/IR/LegacyPassNameParser.h"
Public Member Functions
PassNameParser (cl::Option &O)
~PassNameParser () override
void initialize ()
virtual bool ignorablePassImpl (const PassInfo *P) const
bool ignorablePass (const PassInfo *P) const
void passRegistered (const PassInfo *P) override
Callback functions - These functions are invoked whenever a pass is loaded or removed from the current executable.
void passEnumerate (const PassInfo *P) override
passEnumerate - Callback function invoked when someone calls enumeratePasses on this PassRegistrationListener object.
void printOptionInfo (const cl::Option &O, size_t GlobalWidth) const override
Public Member Functions inherited from llvm::PassRegistrationListener
PassRegistrationListener ()=default
virtual ~PassRegistrationListener ()=default
void enumeratePasses ()
enumeratePasses - Iterate over the registered passes, calling the passEnumerate callback on each PassInfo object.
Public Member Functions inherited from llvm::cl::parser< const PassInfo *>
parser (Option &O)
unsigned getNumOptions () const override
StringRef getOption (unsigned N) const override
StringRef getDescription (unsigned N) const override
const GenericOptionValue & getOptionValue (unsigned N) const override
bool parse (Option &O, StringRef ArgName, StringRef Arg, const PassInfo * &V)
void addLiteralOption (StringRef Name, const DT &V, StringRef HelpStr)
addLiteralOption - Add an entry to the mapping table.
void removeLiteralOption (StringRef Name)
removeLiteralOption - Remove the specified option.
Public Member Functions inherited from llvm::cl::generic_parser_base
generic_parser_base (Option &O)
virtual ~generic_parser_base ()=default
virtual size_t getOptionWidth (const Option &O) const
void printGenericOptionDiff (const Option &O, const GenericOptionValue &V, const GenericOptionValue &Default, size_t GlobalWidth) const
template<class AnyOptionValue >
void printOptionDiff (const Option &O, const AnyOptionValue &V, const AnyOptionValue &Default, size_t GlobalWidth) const
void initialize ()
void getExtraOptionNames (SmallVectorImpl< StringRef > &OptionNames)
enum ValueExpected getValueExpectedFlagDefault () const
unsigned findOption (StringRef Name)
Additional Inherited Members
Public Types inherited from llvm::cl::parser< const PassInfo *>
using parser_data_type = const PassInfo *
Protected Attributes inherited from llvm::cl::parser< const PassInfo *>
SmallVector< OptionInfo, 8 > Values
Protected Attributes inherited from llvm::cl::generic_parser_base
Option & Owner
Detailed Description
Definition at line 41 of file LegacyPassNameParser.h.
Constructor & Destructor Documentation
PassNameParser()
PassNameParser::PassNameParser (cl::Option & O)
Definition at line 217 of file Pass.cpp.
References llvm::PassRegistry::addRegistrationListener(), llvm::PassRegistry::getPassRegistry(), llvm::PassInfo::getTypeInfo(), llvm::PassInfo::isCFGOnlyPass(), P, passEnumerate(), and ~PassNameParser().
~PassNameParser()
PassNameParser::~PassNameParser () override default
Referenced by PassNameParser().
Member Function Documentation
ignorablePass()
bool llvm::PassNameParser::ignorablePass (const PassInfo * P) const inline
Definition at line 59 of file LegacyPassNameParser.h.
References llvm::StringRef::empty(), llvm::PassInfo::getNormalCtor(), llvm::PassInfo::getPassArgument(), and ignorablePassImpl().
Referenced by passRegistered().
ignorablePassImpl()
virtual bool llvm::PassNameParser::ignorablePassImpl (const PassInfo * P) const inline virtual
Reimplemented in llvm::FilteredPassNameParser< Filter >.
Definition at line 57 of file LegacyPassNameParser.h.
Referenced by ignorablePass().
initialize()
void llvm::PassNameParser::initialize () inline
Definition at line 47 of file LegacyPassNameParser.h.
References llvm::PassRegistrationListener::enumeratePasses(), and llvm::cl::generic_parser_base::initialize().
passEnumerate()
void llvm::PassNameParser::passEnumerate (const PassInfo *) inline override virtual
passEnumerate - Callback function invoked when someone calls enumeratePasses on this PassRegistrationListener object.
Reimplemented from llvm::PassRegistrationListener.
Definition at line 77 of file LegacyPassNameParser.h.
References passRegistered().
Referenced by PassNameParser().
passRegistered()
void llvm::PassNameParser::passRegistered (const PassInfo *) inline override virtual
Callback functions - These functions are invoked whenever a pass is loaded or removed from the current executable.
Reimplemented from llvm::PassRegistrationListener.
Definition at line 68 of file LegacyPassNameParser.h.
References llvm::cl::parser< const PassInfo *>::addLiteralOption(), llvm::StringRef::data(), llvm::errs(), llvm::cl::generic_parser_base::findOption(), llvm::cl::parser< const PassInfo *>::getNumOptions(), llvm::PassInfo::getPassArgument(), llvm::PassInfo::getPassName(), ignorablePass(), llvm_unreachable, and P.
Referenced by passEnumerate().
printOptionInfo()
void llvm::PassNameParser::printOptionInfo (const cl::Option & O, size_t GlobalWidth) const inline override virtual
Reimplemented from llvm::cl::generic_parser_base.
Definition at line 81 of file LegacyPassNameParser.h.
References llvm::array_pod_sort(), llvm::cl::generic_parser_base::printOptionInfo(), and llvm::cl::parser< DataType >::Values.
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassNameParser.h
lib/IR/Pass.cpp