LLVM: llvm::MCObjectStreamer Class Reference
llvm::MCObjectStreamer Class Reference abstract
Streaming object file generation interface.
#include "llvm/MC/MCObjectStreamer.h"
Public Member Functions
void reset () override
state management
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
void EmitFrames (MCAsmBackend *MAB)
void EmitCFISections (bool EH, bool Debug) override
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment (const MCSubtargetInfo *STI=nullptr)
Get a data fragment to write into, creating a new one if the current fragment is not a data fragment.
void visitUsedSymbol (const MCSymbol &Sym) override
void flushPendingLabels ()
Create a data fragment for any pending labels across all Sections and Subsections.
MCAssembler & getAssembler ()
MCAssembler * getAssemblerPtr () override
MCStreamer Interface
void EmitLabel (MCSymbol *Symbol, SMLoc Loc=SMLoc()) override
Emit a label for Symbol into the current section.
virtual void EmitLabelAtPos (MCSymbol *Symbol, SMLoc Loc, MCFragment *F, uint64_t Offset)
void EmitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
Emit an assignment of Value to Symbol.
void EmitValueImpl (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc()) override
Emit the expression Value into the output as a native integer of the given Size bytes.
void EmitULEB128Value (const MCExpr *Value) override
void EmitSLEB128Value (const MCExpr *Value) override
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
Emit an weak reference from Alias to Symbol.
void ChangeSection (MCSection *Section, const MCExpr *Subsection) override
Update streamer for a new active section.
void EmitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
Emit the given Instruction into the current section.
virtual void EmitInstToFragment (const MCInst &Inst, const MCSubtargetInfo &)
Emit an instruction to a special fragment, because this instruction can change its size during relaxation.
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
void EmitBytes (StringRef Data) override
Emit the bytes in Data into the output.
void EmitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
void EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0) override
Emit nops until the byte alignment ByteAlignment is reached.
void emitValueToOffset (const MCExpr *Offset, unsigned char Value, SMLoc Loc) override
Emit some number of copies of Value until the byte offset Offset is reached.
void EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
void EmitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize)
void EmitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void EmitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc) override
This implements the CodeView '.cv_loc' assembler directive.
void EmitCVLinetableDirective (unsigned FunctionId, const MCSymbol *Begin, const MCSymbol *End) override
This implements the CodeView '.cv_linetable' assembler directive.
void EmitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym) override
This implements the CodeView '.cv_inline_linetable' assembler directive.
void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, StringRef FixedSizePortion) override
This implements the CodeView '.cv_def_range' assembler directive.
void EmitCVStringTableDirective () override
This implements the CodeView '.cv_stringtable' assembler directive.
void EmitCVFileChecksumsDirective () override
This implements the CodeView '.cv_filechecksums' assembler directive.
void EmitCVFileChecksumOffsetDirective (unsigned FileNo) override
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
void EmitDTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
void EmitDTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
void EmitTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
void EmitTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
void EmitGPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
void EmitGPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
bool EmitRelocDirective (const MCExpr &Offset, StringRef Name, const MCExpr *Expr, SMLoc Loc, const MCSubtargetInfo &STI) override
Emit a .reloc directive.
void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc()) override
Emit Size bytes worth of the value specified by FillValue.
void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc()) override
Emit NumValues copies of Size bytes.
void EmitFileDirective (StringRef Filename) override
Switch to a new logical file.
void EmitAddrsig () override
void EmitAddrsigSym (const MCSymbol *Sym) override
void FinishImpl () override
Streamer specific finalization.
void emitAbsoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) override
Emit the absolute difference between two symbols if possible.
void emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) override
Emit the absolute difference between two symbols encoded with ULEB128.
bool mayHaveInstructions (MCSection &Sec) const override
Public Member Functions inherited from llvm::MCStreamer
MCStreamer (const MCStreamer &)=delete
MCStreamer & operator= (const MCStreamer &)=delete
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
MCContext & getContext () const
void setUseAssemblerInfoForParsing (bool v)
bool getUseAssemblerInfoForParsing ()
MCTargetStreamer * getTargetStreamer ()
void setAllowAutoPadding (bool v)
bool getAllowAutoPadding () const
WinEH::FrameInfo * EnsureValidWinFrameInfo (SMLoc Loc)
Retreive the current frame info if one is available and it is not yet closed.
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
bool hasUnfinishedDwarfFrameInfo ()
unsigned getNumWinFrameInfos ()
ArrayRef< std::unique_ptr< WinEH::FrameInfo > > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual void EmitIdent (StringRef IdentString)
Emit the "identifiers" directive.
unsigned EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual Expected< unsigned > tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual void emitDwarfFile0Directive (StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, unsigned CUID=0)
Specify the "root" file of the compilation, using the ".file 0" extension.
virtual void EmitCFIBKeyFrame ()
virtual bool EmitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind)
Associate a filename with a specified logical file number, and also specify that file's checksum information.
virtual bool EmitCVFuncIdDirective (unsigned FunctionId)
Introduces a function id for use with .cv_loc.
virtual bool EmitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc)
Introduces an inline call site id for use with .cv_loc.
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeRegisterRelHeader DRHdr)
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr)
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeRegisterHeader DRHdr)
virtual void EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, codeview::DefRangeFramePointerRelHeader DRHdr)
virtual void EmitCVFPOData (const MCSymbol *ProcSym, SMLoc Loc={})
This implements the CodeView '.cv_fpo_data' assembler directive.
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void EmitCFIStartProc (bool IsSimple, SMLoc Loc=SMLoc())
void EmitCFIEndProc ()
virtual void EmitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void EmitCFIDefCfaOffset (int64_t Offset)
virtual void EmitCFIDefCfaRegister (int64_t Register)
virtual void EmitCFIOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFIRememberState ()
virtual void EmitCFIRestoreState ()
virtual void EmitCFISameValue (int64_t Register)
virtual void EmitCFIRestore (int64_t Register)
virtual void EmitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void EmitCFIEscape (StringRef Values)
virtual void EmitCFIReturnColumn (int64_t Register)
virtual void EmitCFIGnuArgsSize (int64_t Size)
virtual void EmitCFISignalFrame ()
virtual void EmitCFIUndefined (int64_t Register)
virtual void EmitCFIRegister (int64_t Register1, int64_t Register2)
virtual void EmitCFIWindowSave ()
virtual void EmitCFINegateRAState ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProc (SMLoc Loc=SMLoc())
virtual void EmitWinCFIFuncletOrFuncEnd (SMLoc Loc=SMLoc())
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
virtual void EmitWinCFIStartChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushReg (MCRegister Register, SMLoc Loc=SMLoc())
virtual void EmitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIAllocStack (unsigned Size, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushFrame (bool Code, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProlog (SMLoc Loc=SMLoc())
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except, SMLoc Loc=SMLoc())
virtual void EmitWinEHHandlerData (SMLoc Loc=SMLoc())
virtual void emitCGProfileEntry (const MCSymbolRefExpr *From, const MCSymbolRefExpr *To, uint64_t Count)
MCSection * getAssociatedPDataSection (const MCSection *TextSec)
Get the .pdata section used for the given section.
MCSection * getAssociatedXDataSection (const MCSection *TextSec)
Get the .xdata section used for the given section.
virtual void EmitSyntaxDirective ()
void EmitRawText (const Twine &String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
void Finish ()
Finish emission of machine code.
virtual bool isVerboseAsm () const
Return true if this streamer supports verbose assembly and if it is enabled.
virtual bool hasRawTextSupport () const
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
virtual void AddComment (const Twine &T, bool EOL=true)
Add a textual comment.
virtual raw_ostream & GetCommentOS ()
Return a raw_ostream that comments can be written to.
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
Print T and prefix it with the comment string (normally #) and optionally a tab.
virtual void addExplicitComment (const Twine &T)
Add explicit comment T.
virtual void emitExplicitComments ()
Emit added explicit comments.
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
Return the current section that the streamer is emitting code to.
MCSection * getCurrentSectionOnly () const
MCSectionSubPair getPreviousSection () const
Return the previous section that the streamer is emitting code to.
unsigned GetSymbolOrder (const MCSymbol *Sym) const
Returns an index to represent the order a symbol was emitted in.
void PushSection ()
Save the current and previous section on the section stack.
bool PopSection ()
Restore the current and previous section from the section stack.
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
void SwitchSectionNoChange (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
virtual void InitSections (bool NoExecStack)
Create the default sections and set the initial one.
MCSymbol * endSection (MCSection *Section)
void AssignFragment (MCSymbol *Symbol, MCFragment *Fragment)
Sets the symbol's section.
virtual void EmitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void EmitAssemblerFlag (MCAssemblerFlag Flag)
Note in the output the specified Flag.
virtual void EmitLinkerOptions (ArrayRef< std::string > Kind)
Emit the given list Options of strings as linker options into the output.
virtual void EmitDataRegion (MCDataRegionType Kind)
Note in the output the specified region Kind.
virtual void EmitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Specify the Mach-O minimum deployment target version.
virtual void EmitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Emit/Specify Mach-O build version command.
void EmitVersionForTarget (const Triple &Target, const VersionTuple &SDKVersion)
virtual void EmitThumbFunc (MCSymbol *Func)
Note in the output that the specified Func is a Thumb mode function (ARM target only).
virtual bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute)=0
Add the given Attribute to Symbol.
virtual void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue)
Set the DescValue for the Symbol.
virtual void BeginCOFFSymbolDef (const MCSymbol *Symbol)
Start emitting COFF symbol definition.
virtual void EmitCOFFSymbolStorageClass (int StorageClass)
Emit the storage class of the symbol.
virtual void EmitCOFFSymbolType (int Type)
Emit the type of the symbol.
virtual void EndCOFFSymbolDef ()
Marks the end of the symbol definition.
virtual void EmitCOFFSafeSEH (MCSymbol const *Symbol)
virtual void EmitCOFFSymbolIndex (MCSymbol const *Symbol)
Emits the symbol table index of a Symbol into the current section.
virtual void EmitCOFFSectionIndex (MCSymbol const *Symbol)
Emits a COFF section index.
virtual void EmitCOFFSecRel32 (MCSymbol const *Symbol, uint64_t Offset)
Emits a COFF section relative relocation.
virtual void EmitCOFFImgRel32 (MCSymbol const *Symbol, int64_t Offset)
Emits a COFF image relative relocation.
virtual void EmitXCOFFLocalCommonSymbol (MCSymbol *LabelSym, uint64_t Size, MCSymbol *CsectSym, unsigned ByteAlignment)
Emits an lcomm directive with XCOFF csect information.
virtual void emitELFSize (MCSymbol *Symbol, const MCExpr *Value)
Emit an ELF .size directive.
virtual void emitELFSymverDirective (StringRef AliasName, const MCSymbol *Aliasee)
Emit an ELF .symver directive.
virtual void EmitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment)=0
Emit a common symbol.
virtual void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment)
Emit a local common (.lcomm) symbol.
virtual void EmitZerofill (MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, unsigned ByteAlignment=0, SMLoc Loc=SMLoc())=0
Emit the zerofill section and an optional symbol.
virtual void EmitTBSSSymbol (MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0)
Emit a thread local bss (.tbss) symbol.
virtual void EmitBinaryData (StringRef Data)
Functionally identical to EmitBytes.
void EmitValue (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
virtual void EmitIntValue (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
virtual void EmitIntValueInHex (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
void EmitULEB128IntValue (uint64_t Value, unsigned PadTo=0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void EmitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void EmitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
void EmitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
virtual void EmitCodePaddingBasicBlockStart (const MCCodePaddingContext &Context)
virtual void EmitCodePaddingBasicBlockEnd (const MCCodePaddingContext &Context)
Protected Member Functions
MCObjectStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
~MCObjectStreamer ()
bool changeSectionImpl (MCSection *Section, const MCExpr *Subsection)
void addPendingLabel (MCSymbol *label)
Assign a label to the current Section and Subsection even though a fragment is not yet present.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0)
If any labels have been emitted but not assigned fragments in the current Section and Subsection, ensure that they get assigned, either to fragment F if possible or to a new data fragment.
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void EmitRawTextImpl (StringRef String)
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
bool checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc)
Returns true if the the .cv_loc directive is in the right section.
Detailed Description
Streaming object file generation interface.
This class provides an implementation of the MCStreamer interface which is suitable for use with the assembler backend. Specific object file formats are expected to subclass this interface to implement directives specific to that file format or custom semantics expected by the object writer implementation.
Definition at line 35 of file MCObjectStreamer.h.
Constructor & Destructor Documentation
MCObjectStreamer()
MCObjectStreamer::MCObjectStreamer (MCContext & Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter) protected
Definition at line 25 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::setAllowAutoPadding().
~MCObjectStreamer()
MCObjectStreamer::~MCObjectStreamer () protected
Definition at line 37 of file MCObjectStreamer.cpp.
Member Function Documentation
addPendingLabel()
void MCObjectStreamer::addPendingLabel (MCSymbol * label) protected
Assign a label to the current Section and Subsection even though a fragment is not yet present.
Use flushPendingLabels(F) to associate a fragment with this label.
Definition at line 48 of file MCObjectStreamer.cpp.
References llvm::MCSection::addPendingLabel(), llvm::find(), and llvm::MCStreamer::getCurrentSectionOnly().
Referenced by EmitLabel(), EmitLabelAtPos(), and insert().
ChangeSection()
void MCObjectStreamer::ChangeSection (MCSection * , const MCExpr *) override virtual
Update streamer for a new active section.
This is called by PopSection and SwitchSection, if the current section changes.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWasmStreamer.
Definition at line 335 of file MCObjectStreamer.cpp.
References changeSectionImpl().
Referenced by llvm::MCWasmStreamer::ChangeSection(), and getAssembler().
changeSectionImpl()
bool MCObjectStreamer::changeSectionImpl (MCSection * Section, const MCExpr * Subsection) protected
Definition at line 340 of file MCObjectStreamer.cpp.
References assert(), llvm::MCContext::clearDwarfLocSeen(), getAssembler(), getAssemblerPtr(), llvm::MCStreamer::getContext(), llvm::MCSection::getSubsectionInsertionPoint(), llvm::MCAssembler::registerSection(), and llvm::report_fatal_error().
Referenced by llvm::MCELFStreamer::ChangeSection(), ChangeSection(), and insert().
emitAbsoluteSymbolDiff()
void MCObjectStreamer::emitAbsoluteSymbolDiff (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Size) override virtual
Emit the absolute difference between two symbols if possible.
Emit the absolute difference between Hi and Lo, as long as we can compute it. Currently, that requires that both symbols are in the same data fragment and that the target has not specified that diff expressions require relocations to be emitted. Otherwise, do nothing and return false.
Precondition
Offset of Hi is greater than the offset Lo.
Reimplemented from llvm::MCStreamer.
Definition at line 144 of file MCObjectStreamer.cpp.
References absoluteSymbolDiff(), llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::EmitIntValue(), and getAssembler().
Referenced by llvm::CodeViewContext::emitFileChecksums(), llvm::CodeViewContext::emitLineTableForFunction(), and llvm::CodeViewContext::emitStringTable().
emitAbsoluteSymbolDiffAsULEB128()
void MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol * Hi, const MCSymbol * Lo) override virtual
Emit the absolute difference between two symbols encoded with ULEB128.
Reimplemented from llvm::MCStreamer.
Definition at line 154 of file MCObjectStreamer.cpp.
References absoluteSymbolDiff(), llvm::MCStreamer::emitAbsoluteSymbolDiffAsULEB128(), llvm::MCStreamer::EmitULEB128IntValue(), and getAssembler().
EmitAddrsig()
void MCObjectStreamer::EmitAddrsig () override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 745 of file MCObjectStreamer.cpp.
References llvm::MCObjectWriter::emitAddrsigSection(), getAssembler(), and llvm::MCAssembler::getWriter().
EmitAddrsigSym()
void MCObjectStreamer::EmitAddrsigSym (const MCSymbol * Sym) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 749 of file MCObjectStreamer.cpp.
References llvm::MCObjectWriter::addAddrsigSymbol(), getAssembler(), llvm::MCAssembler::getWriter(), and llvm::MCAssembler::registerSymbol().
EmitAssignment()
void MCObjectStreamer::EmitAssignment (MCSymbol * Symbol, const MCExpr * Value) override virtual
Emit an assignment of Value to Symbol.
This corresponds to an assembler statement such as: symbol = value
The assignment generates no code, but has the side effect of binding the value in the current context. For the assembly streamer, this prints the binding into the .s file.
Parameters
Symbol - The symbol being assigned to.
Value - The value for the symbol.
Reimplemented from llvm::MCStreamer.
Definition at line 359 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitAssignment(), getAssembler(), and llvm::MCAssembler::registerSymbol().
Referenced by canGoAfterDWARF(), llvm::CodeViewContext::emitFileChecksums(), and getAssembler().
EmitBundleAlignMode()
void MCObjectStreamer::EmitBundleAlignMode (unsigned AlignPow2) override virtual
Set the bundle alignment mode from now on in the section.
The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
Reimplemented from llvm::MCStreamer.
Definition at line 434 of file MCObjectStreamer.cpp.
References llvm_unreachable.
Referenced by getAssembler().
EmitBundleLock()
void MCObjectStreamer::EmitBundleLock (bool AlignToEnd) override virtual
The following instructions are a bundle-locked group.
Parameters
AlignToEnd - If true, the bundle-locked group will be aligned to the end of a bundle.
Reimplemented from llvm::MCStreamer.
Definition at line 438 of file MCObjectStreamer.cpp.
References llvm_unreachable.
Referenced by getAssembler().
EmitBundleUnlock()
void MCObjectStreamer::EmitBundleUnlock () override virtual
Ends a bundle-locked group.
Reimplemented from llvm::MCStreamer.
Definition at line 442 of file MCObjectStreamer.cpp.
References llvm_unreachable.
Referenced by getAssembler().
EmitBytes()
void MCObjectStreamer::EmitBytes (StringRef Data) override virtual
Emit the bytes in Data into the output.
This is used to implement assembler directives such as .byte, .ascii, etc.
Reimplemented from llvm::MCStreamer.
Definition at line 570 of file MCObjectStreamer.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), DF, llvm::StringRef::end(), flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCStreamer::getCurrentSectionOnly(), getOrCreateDataFragment(), llvm::MCDwarfLineEntry::Make(), and llvm::SmallVectorBase::size().
Referenced by llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectISA(), llvm::CodeViewContext::emitFileChecksums(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::MCELFStreamer::EmitIdent(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), llvm::AMDGPUTargetELFStreamer::finish(), GetAEABIUnwindPersonalityName(), and getAssembler().
EmitCFISections()
void MCObjectStreamer::EmitCFISections (bool EH, bool Debug) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 222 of file MCObjectStreamer.cpp.
References Debug, and llvm::MCStreamer::EmitCFISections().
Referenced by isIntegratedAssemblerRequired().
EmitCodeAlignment()
void MCObjectStreamer::EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit = 0) override virtual
Emit nops until the byte alignment ByteAlignment is reached.
This used to align code where the alignment bytes may be executed. This can emit different bytes for different sizes to optimize execution.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented from llvm::MCStreamer.
Definition at line 591 of file MCObjectStreamer.cpp.
References EmitValueToAlignment(), and getCurrentFragment().
Referenced by getAssembler(), llvm::MCELFStreamer::InitSections(), and llvm::MCWinCOFFStreamer::InitSections().
EmitCVDefRangeDirective()
void MCObjectStreamer::EmitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol *>> Ranges, StringRef FixedSizePortion) override virtual
This implements the CodeView '.cv_def_range' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 548 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitCVDefRangeDirective(), llvm::CodeViewContext::emitDefRange(), flushPendingLabels(), llvm::MCStreamer::getContext(), and llvm::MCContext::getCVContext().
EmitCVFileChecksumOffsetDirective()
void MCObjectStreamer::EmitCVFileChecksumOffsetDirective (unsigned FileNo) override virtual
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 566 of file MCObjectStreamer.cpp.
References llvm::CodeViewContext::emitFileChecksumOffset(), llvm::MCStreamer::getContext(), and llvm::MCContext::getCVContext().
Referenced by llvm::CodeViewContext::emitLineTableForFunction().
EmitCVFileChecksumsDirective()
void MCObjectStreamer::EmitCVFileChecksumsDirective () override virtual
This implements the CodeView '.cv_filechecksums' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 562 of file MCObjectStreamer.cpp.
References llvm::CodeViewContext::emitFileChecksums(), llvm::MCStreamer::getContext(), and llvm::MCContext::getCVContext().
EmitCVInlineLinetableDirective()
void MCObjectStreamer::EmitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol * FnStartSym, const MCSymbol * FnEndSym) override virtual
This implements the CodeView '.cv_inline_linetable' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 538 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitCVInlineLinetableDirective(), llvm::CodeViewContext::emitInlineLineTableForFunction(), llvm::MCStreamer::getContext(), and llvm::MCContext::getCVContext().
EmitCVLinetableDirective()
void MCObjectStreamer::EmitCVLinetableDirective (unsigned FunctionId, const MCSymbol * FnStart, const MCSymbol * FnEnd) override virtual
This implements the CodeView '.cv_linetable' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 530 of file MCObjectStreamer.cpp.
Referenced by getAssembler().
EmitCVLocDirective()
void MCObjectStreamer::EmitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc) override virtual
This implements the CodeView '.cv_loc' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 514 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::checkCVLocSection(), llvm::MCContext::createTempSymbol(), EmitLabel(), llvm::MCStreamer::getContext(), llvm::MCContext::getCVContext(), and llvm::CodeViewContext::recordCVLoc().
Referenced by getAssembler().
EmitCVStringTableDirective()
void MCObjectStreamer::EmitCVStringTableDirective () override virtual
This implements the CodeView '.cv_stringtable' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 559 of file MCObjectStreamer.cpp.
References llvm::CodeViewContext::emitStringTable(), llvm::MCStreamer::getContext(), and llvm::MCContext::getCVContext().
EmitDTPRel32Value()
void MCObjectStreamer::EmitDTPRel32Value (const MCExpr * Value) override virtual
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
This is used to implement assembler directives such as .dtprelword on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 604 of file MCObjectStreamer.cpp.
References llvm::MCFixup::create(), DF, llvm::FK_DTPRel_4, flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
EmitDTPRel64Value()
void MCObjectStreamer::EmitDTPRel64Value (const MCExpr * Value) override virtual
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
This is used to implement assembler directives such as .dtpreldword on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 614 of file MCObjectStreamer.cpp.
References llvm::MCFixup::create(), DF, llvm::FK_DTPRel_8, flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
EmitDwarfAdvanceFrameAddr()
void MCObjectStreamer::EmitDwarfAdvanceFrameAddr (const MCSymbol * LastLabel, const MCSymbol * Label)
Definition at line 503 of file MCObjectStreamer.cpp.
References buildSymbolDiff(), llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), getAssemblerPtr(), and insert().
Referenced by getAssembler().
EmitDwarfAdvanceLineAddr()
void MCObjectStreamer::EmitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol * LastLabel, const MCSymbol * Label, unsigned PointerSize)
Definition at line 484 of file MCObjectStreamer.cpp.
References buildSymbolDiff(), llvm::MCDwarfLineAddr::Emit(), emitDwarfSetLineAddr(), getAssemblerPtr(), and insert().
Referenced by EmitDwarfLineTable(), and getAssembler().
EmitDwarfLocDirective()
void MCObjectStreamer::EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override virtual
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 446 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitDwarfLocDirective(), llvm::MCStreamer::getCurrentSectionOnly(), and llvm::MCDwarfLineEntry::Make().
Referenced by getAssembler().
EmitFileDirective()
void MCObjectStreamer::EmitFileDirective (StringRef Filename) override virtual
Switch to a new logical file.
This is used to implement the '.file "foo.c"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 741 of file MCObjectStreamer.cpp.
References llvm::MCAssembler::addFileName(), and getAssembler().
emitFill() [1/2]
void MCObjectStreamer::emitFill (const MCExpr & NumBytes, uint64_t FillValue, SMLoc Loc = SMLoc()) override virtual
Emit Size bytes worth of the value specified by FillValue.
This is used to implement assembler directives such as .space or .skip.
Parameters
NumBytes - The number of bytes to emit.
FillValue - The value to use when filling bytes.
Loc - The location of the expression for error reporting.
Reimplemented from llvm::MCStreamer.
Definition at line 702 of file MCObjectStreamer.cpp.
References assert(), DF, flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCStreamer::getCurrentSectionOnly(), getOrCreateDataFragment(), insert(), and llvm::SmallVectorBase::size().
Referenced by GetAEABIUnwindPersonalityName().
emitFill() [2/2]
void MCObjectStreamer::emitFill (const MCExpr & NumValues, int64_t Size, int64_t Expr, SMLoc Loc = SMLoc()) override virtual
Emit NumValues copies of Size bytes.
Each Size bytes is taken from the lowest order 4 bytes of Expr expression.
This is used to implement assembler directives such as .fill.
Parameters
NumValues - The number of copies of Size bytes to emit.
Size - The size (in bytes) of each repeated value.
Expr - The expression from which Size bytes are used.
Reimplemented from llvm::MCStreamer.
Definition at line 711 of file MCObjectStreamer.cpp.
References assert(), DF, llvm::SourceMgr::DK_Warning, llvm::numbers::e, llvm::MCStreamer::EmitIntValue(), flushPendingLabels(), getAssemblerPtr(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), getOrCreateDataFragment(), llvm::MCContext::getSourceManager(), insert(), llvm::SourceMgr::PrintMessage(), Size, and llvm::SmallVectorBase::size().
EmitFrames()
void MCObjectStreamer::EmitFrames (MCAsmBackend * MAB)
Definition at line 174 of file MCObjectStreamer.cpp.
References llvm::MCDwarfFrameEmitter::Emit(), and llvm::MCStreamer::getNumFrameInfos().
Referenced by llvm::MCWasmStreamer::FinishImpl(), llvm::MCELFStreamer::FinishImpl(), and isIntegratedAssemblerRequired().
EmitGPRel32Value()
void MCObjectStreamer::EmitGPRel32Value (const MCExpr * Value) override virtual
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
This is used to implement assembler directives such as .gprel32 on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 644 of file MCObjectStreamer.cpp.
References llvm::MCFixup::create(), DF, llvm::FK_GPRel_4, flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
EmitGPRel64Value()
void MCObjectStreamer::EmitGPRel64Value (const MCExpr * Value) override virtual
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
This is used to implement assembler directives such as .gpdword on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 654 of file MCObjectStreamer.cpp.
References llvm::MCFixup::create(), DF, llvm::FK_GPRel_4, flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
EmitInstruction()
void MCObjectStreamer::EmitInstruction (const MCInst & Inst, const MCSubtargetInfo & STI) override virtual
Emit the given Instruction into the current section.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer, and llvm::HexagonMCELFStreamer.
Definition at line 368 of file MCObjectStreamer.cpp.
References llvm::MCAsmBackend::alignBranchesBegin(), llvm::MCAsmBackend::alignBranchesEnd(), llvm::MCStreamer::EmitInstruction(), EmitInstToFragment(), getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCAssembler::getRelaxAll(), llvm::MCSection::isBundleLocked(), llvm::MCAssembler::isBundlingEnabled(), llvm::MCDwarfLineEntry::Make(), llvm::MCAsmBackend::mayNeedRelaxation(), llvm::MCAsmBackend::relaxInstruction(), and llvm::MCSection::setHasInstructions().
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::HexagonMCELFStreamer::EmitInstruction(), llvm::MipsELFStreamer::EmitInstruction(), GetAEABIUnwindPersonalityName(), and getAssembler().
EmitInstToFragment()
void MCObjectStreamer::EmitInstToFragment (const MCInst & Inst, const MCSubtargetInfo & STI) virtual
Emit an instruction to a special fragment, because this instruction can change its size during relaxation.
Definition at line 412 of file MCObjectStreamer.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MCCodeEmitter::encodeInstruction(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getAssembler(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCAssembler::getEmitter(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), llvm::AMDGPUISD::IF, insert(), and llvm_unreachable.
Referenced by llvm::MCELFStreamer::EmitIdent(), llvm::MCWasmStreamer::EmitIdent(), EmitInstruction(), and getAssembler().
EmitLabel()
void MCObjectStreamer::EmitLabel (MCSymbol * Symbol, SMLoc Loc = SMLoc()) override virtual
Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 270 of file MCObjectStreamer.cpp.
References addPendingLabel(), llvm::MCStreamer::EmitLabel(), F(), getAssembler(), getCurrentFragment(), llvm::MCAssembler::registerSymbol(), llvm::MCSymbol::setFragment(), and llvm::MCSymbol::setOffset().
Referenced by canGoAfterDWARF(), llvm::MCDwarfFrameEmitter::Emit(), llvm::MCDwarfLineTable::EmitCU(), EmitCVLocDirective(), llvm::CodeViewContext::emitFileChecksums(), llvm::MCELFStreamer::EmitLabel(), llvm::MCWinCOFFStreamer::EmitLabel(), llvm::CodeViewContext::emitLineTableForFunction(), llvm::CodeViewContext::emitStringTable(), EmitValueImpl(), getAssembler(), and llvm::MCDwarfLineEntry::Make().
EmitLabelAtPos()
void MCObjectStreamer::EmitLabelAtPos (MCSymbol * Symbol, SMLoc Loc, MCFragment * F, uint64_t Offset) virtual
Reimplemented in llvm::MCELFStreamer.
Definition at line 294 of file MCObjectStreamer.cpp.
References addPendingLabel(), assert(), DF, llvm::MCStreamer::EmitLabel(), F(), getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCFragment::getParent(), llvm::MCAssembler::registerSymbol(), llvm::MCSymbol::setFragment(), and llvm::MCSymbol::setOffset().
Referenced by llvm::MCELFStreamer::EmitLabelAtPos(), and getAssembler().
EmitRelocDirective()
bool MCObjectStreamer::EmitRelocDirective (const MCExpr & Offset, StringRef Name, const MCExpr * Expr, SMLoc Loc, const MCSubtargetInfo & STI) override virtual
Emit a .reloc directive.
Returns true if the relocation could not be emitted because Name is not known.
Reimplemented from llvm::MCStreamer.
Definition at line 663 of file MCObjectStreamer.cpp.
References llvm::MCFixup::create(), llvm::MCSymbolRefExpr::create(), DF, llvm::SmallVectorImpl< T >::emplace_back(), flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCStreamer::getContext(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), llvm::MCExpr::getKind(), llvm::MCSymbol::getOffset(), getOrCreateDataFragment(), llvm::MCSymbolRefExpr::getSymbol(), llvm::Optional< T >::hasValue(), llvm::MCSymbol::isDefined(), llvm_unreachable, llvm::SmallVectorBase::size(), and llvm::MCExpr::SymbolRef.
EmitSLEB128Value()
void MCObjectStreamer::EmitSLEB128Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 321 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitSLEB128IntValue(), getAssemblerPtr(), and insert().
Referenced by getAssembler().
EmitTPRel32Value()
void MCObjectStreamer::EmitTPRel32Value (const MCExpr * Value) override virtual
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
This is used to implement assembler directives such as .tprelword on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 624 of file MCObjectStreamer.cpp.
References llvm::MCFixup::create(), DF, llvm::FK_TPRel_4, flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
EmitTPRel64Value()
void MCObjectStreamer::EmitTPRel64Value (const MCExpr * Value) override virtual
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
This is used to implement assembler directives such as .tpreldword on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 634 of file MCObjectStreamer.cpp.
References llvm::MCFixup::create(), DF, llvm::FK_TPRel_8, flushPendingLabels(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase::size().
EmitULEB128Value()
void MCObjectStreamer::EmitULEB128Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 312 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitULEB128IntValue(), getAssemblerPtr(), and insert().
Referenced by getAssembler().
EmitValueImpl()
void MCObjectStreamer::EmitValueImpl (const MCExpr * Value, unsigned Size, SMLoc Loc = SMLoc()) override virtual
Emit the expression Value into the output as a native integer of the given Size bytes.
This is used to implement assembler directives such as .word, .quad, etc.
Parameters
Value - The value to emit.
Size - The size of the integer (in bytes) to emit. This must match a native machine width.
Loc - The location of the expression for error reporting.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWasmStreamer, and llvm::MipsELFStreamer.
Definition at line 228 of file MCObjectStreamer.cpp.
References llvm::MCDwarfFrameInfo::Begin, llvm::MCFixup::create(), llvm::MCContext::createTempSymbol(), DF, llvm::MCStreamer::EmitIntValue(), EmitLabel(), llvm::MCStreamer::EmitValueImpl(), llvm::MCDwarfFrameInfo::End, flushPendingLabels(), getAssemblerPtr(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), llvm::MCFixup::getKindForSize(), getOrCreateDataFragment(), llvm::isIntN(), llvm::isUIntN(), llvm::MCDwarfLineEntry::Make(), llvm::MCContext::reportError(), llvm::SmallVectorImpl< T >::resize(), Size, and llvm::SmallVectorBase::size().
Referenced by llvm::CodeViewContext::emitFileChecksumOffset(), llvm::MCWasmStreamer::EmitValueImpl(), llvm::MCELFStreamer::EmitValueImpl(), and getAssembler().
EmitValueToAlignment()
void MCObjectStreamer::EmitValueToAlignment (unsigned ByteAlignment, int64_t Value = 0, unsigned ValueSize = 1, unsigned MaxBytesToEmit = 0) override virtual
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
If the number of bytes need to emit for the alignment is not a multiple of ValueSize, then the contents of the emitted fill bytes is undefined.
This used to implement the .align assembler directive.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
Value - The value to use when filling bytes.
ValueSize - The size of the integer (in bytes) to emit for Value. This must match a native machine width.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWasmStreamer.
Definition at line 577 of file MCObjectStreamer.cpp.
References llvm::LCOMM::ByteAlignment, llvm::MCSection::getAlignment(), llvm::MCStreamer::getCurrentSectionOnly(), insert(), and llvm::MCSection::setAlignment().
Referenced by llvm::MCDwarfFrameEmitter::Emit(), EmitCodeAlignment(), llvm::MCXCOFFStreamer::EmitCommonSymbol(), llvm::CodeViewContext::emitFileChecksums(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::CodeViewContext::emitStringTable(), llvm::MCWasmStreamer::EmitValueToAlignment(), llvm::MCELFStreamer::EmitValueToAlignment(), and getAssembler().
emitValueToOffset()
void MCObjectStreamer::emitValueToOffset (const MCExpr * Offset, unsigned char Value, SMLoc Loc) override virtual
Emit some number of copies of Value until the byte offset Offset is reached.
This is used to implement assembler directives such as .org.
Parameters
Offset - The offset to reach. This may be an expression, but the expression must be associated with the current section.
Value - The value to use when filling bytes.
Reimplemented from llvm::MCStreamer.
Definition at line 597 of file MCObjectStreamer.cpp.
References insert().
Referenced by getAssembler().
EmitWeakReference()
void MCObjectStreamer::EmitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) override virtual
Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWasmStreamer.
Definition at line 330 of file MCObjectStreamer.cpp.
References llvm::report_fatal_error().
Referenced by getAssembler().
FinishImpl()
void MCObjectStreamer::FinishImpl () override virtual
Streamer specific finalization.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 754 of file MCObjectStreamer.cpp.
References llvm::MCDwarfLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCAssembler::Finish(), flushPendingLabels(), getAssembler(), llvm::MCStreamer::getContext(), and llvm::MCContext::RemapDebugPaths().
Referenced by llvm::MCWinCOFFStreamer::FinishImpl(), llvm::MCWasmStreamer::FinishImpl(), and llvm::MCELFStreamer::FinishImpl().
flushPendingLabels() [1/2]
void MCObjectStreamer::flushPendingLabels (MCFragment * F, uint64_t FOffset = 0) protected
If any labels have been emitted but not assigned fragments in the current Section and Subsection, ensure that they get assigned, either to fragment F if possible or to a new data fragment.
Optionally, one can provide an offset FOffset as a symbol offset within the fragment.
Definition at line 72 of file MCObjectStreamer.cpp.
References llvm::MCSection::addPendingLabel(), assert(), llvm::MCSection::flushPendingLabels(), and llvm::MCStreamer::getCurrentSectionOnly().
flushPendingLabels() [2/2]
void MCObjectStreamer::flushPendingLabels ()
Create a data fragment for any pending labels across all Sections and Subsections.
Definition at line 93 of file MCObjectStreamer.cpp.
References llvm::MCSection::addPendingLabel(), assert(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCContext::reportError(), and llvm::ARMBuildAttrs::Section.
Referenced by EmitBytes(), EmitCVDefRangeDirective(), EmitDTPRel32Value(), EmitDTPRel64Value(), emitFill(), EmitGPRel32Value(), EmitGPRel64Value(), EmitRelocDirective(), EmitTPRel32Value(), EmitTPRel64Value(), EmitValueImpl(), FinishImpl(), insert(), and llvm::MCELFStreamer::MCELFStreamer().
getAssembler()
MCAssembler& llvm::MCObjectStreamer::getAssembler () inline
Definition at line 111 of file MCObjectStreamer.h.
References llvm::LCOMM::ByteAlignment, ChangeSection(), llvm::Data, EmitAssignment(), EmitBundleAlignMode(), EmitBundleLock(), EmitBundleUnlock(), EmitBytes(), EmitCodeAlignment(), EmitCVLinetableDirective(), EmitCVLocDirective(), EmitDwarfAdvanceFrameAddr(), EmitDwarfAdvanceLineAddr(), EmitDwarfLocDirective(), EmitInstruction(), EmitInstToFragment(), EmitLabel(), EmitLabelAtPos(), EmitSLEB128Value(), EmitULEB128Value(), EmitValueImpl(), EmitValueToAlignment(), emitValueToOffset(), EmitWeakReference(), getAssemblerPtr(), Size, and llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer(), llvm::AVRELFStreamer::AVRELFStreamer(), llvm::MCELFStreamer::ChangeSection(), llvm::MCWasmStreamer::ChangeSection(), changeSectionImpl(), CheckBundleSubtargets(), llvm::createELFStreamer(), llvm::MipsELFStreamer::createPendingLabelRelocs(), llvm::createWasmStreamer(), llvm::createXCOFFStreamer(), emitAbsoluteSymbolDiff(), emitAbsoluteSymbolDiffAsULEB128(), EmitAddrsig(), EmitAddrsigSym(), llvm::MCWinCOFFStreamer::EmitAssemblerFlag(), llvm::MCELFStreamer::EmitAssemblerFlag(), llvm::MCWasmStreamer::EmitAssemblerFlag(), EmitAssignment(), llvm::MCELFStreamer::EmitBundleAlignMode(), llvm::MCELFStreamer::EmitBundleLock(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::MCELFStreamer::emitCGProfileEntry(), llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolIndex(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolStorageClass(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolType(), llvm::MCXCOFFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveNaN2008(), llvm::MipsTargetELFStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic2(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder(), llvm::MCELFStreamer::emitELFSymverDirective(), EmitFileDirective(), llvm::MipsTargetELFStreamer::emitFrame(), llvm::MCWasmStreamer::EmitIdent(), llvm::MCELFStreamer::EmitIdent(), EmitInstruction(), llvm::MCXCOFFStreamer::EmitInstToData(), llvm::MCWinCOFFStreamer::EmitInstToData(), EmitInstToFragment(), EmitLabel(), llvm::MipsTargetELFStreamer::emitLabel(), EmitLabelAtPos(), llvm::MCELFStreamer::EmitLocalCommonSymbol(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MCXCOFFStreamer::EmitSymbolAttribute(), llvm::MCWinCOFFStreamer::EmitSymbolAttribute(), llvm::MCELFStreamer::EmitSymbolAttribute(), llvm::MCWasmStreamer::EmitSymbolAttribute(), llvm::MCELFStreamer::EmitWeakReference(), llvm::MCWasmStreamer::EmitWeakReference(), llvm::MipsTargetELFStreamer::finish(), llvm::MCELFStreamer::FinishImpl(), FinishImpl(), GetAbsDifference(), hasVariantSymbol(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::HexagonMCELFStreamer::HexagonMCEmitLocalCommonSymbol(), llvm::MCELFStreamer::MCELFStreamer(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer(), and llvm::MipsTargetELFStreamer::setUsesMicroMips().
getAssemblerPtr()
MCAssembler * MCObjectStreamer::getAssemblerPtr () override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 42 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::getUseAssemblerInfoForParsing().
Referenced by changeSectionImpl(), EmitDwarfAdvanceFrameAddr(), EmitDwarfAdvanceLineAddr(), emitFill(), EmitSLEB128Value(), EmitULEB128Value(), EmitValueImpl(), and getAssembler().
getCurrentFragment()
MCFragment * MCObjectStreamer::getCurrentFragment () const
Definition at line 185 of file MCObjectStreamer.cpp.
References assert(), llvm::sys::path::begin(), and llvm::MCStreamer::getCurrentSectionOnly().
Referenced by canReuseBoundaryAlignFragment(), CheckBundleSubtargets(), EmitCodeAlignment(), llvm::MCELFStreamer::EmitIdent(), EmitLabel(), getOrCreateDataFragment(), and isIntegratedAssemblerRequired().
getOrCreateDataFragment()
MCDataFragment * MCObjectStreamer::getOrCreateDataFragment (const MCSubtargetInfo * STI = nullptr)
Get a data fragment to write into, creating a new one if the current fragment is not a data fragment.
Optionally a STI can be passed in so that a new fragment is created if the Subtarget differs from the current fragment.
Definition at line 209 of file MCObjectStreamer.cpp.
References CanReuseDataFragment(), F(), getCurrentFragment(), and insert().
Referenced by CheckBundleSubtargets(), llvm::MCELFStreamer::EmitBundleUnlock(), EmitBytes(), llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), EmitDTPRel32Value(), EmitDTPRel64Value(), emitFill(), EmitGPRel32Value(), EmitGPRel64Value(), llvm::MCWasmStreamer::EmitIdent(), llvm::MCXCOFFStreamer::EmitInstToData(), llvm::MCWinCOFFStreamer::EmitInstToData(), EmitRelocDirective(), EmitTPRel32Value(), EmitTPRel64Value(), EmitValueImpl(), and insert().
insert()
void llvm::MCObjectStreamer::insert (MCFragment * F) inline
Definition at line 77 of file MCObjectStreamer.h.
References addPendingLabel(), changeSectionImpl(), F(), flushPendingLabels(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCSection::getFragmentList(), getOrCreateDataFragment(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::ARMBuildAttrs::Section, llvm::MCFragment::setParent(), and visitUsedSymbol().
Referenced by canReuseBoundaryAlignFragment(), CheckBundleSubtargets(), EmitDwarfAdvanceFrameAddr(), EmitDwarfAdvanceLineAddr(), emitFill(), EmitInstToFragment(), EmitSLEB128Value(), llvm::CodeViewContext::emitStringTable(), EmitULEB128Value(), EmitValueToAlignment(), emitValueToOffset(), and getOrCreateDataFragment().
isIntegratedAssemblerRequired()
bool llvm::MCObjectStreamer::isIntegratedAssemblerRequired () const inline override virtual
Object streamers require the integrated assembler.
Reimplemented from llvm::MCStreamer.
Definition at line 70 of file MCObjectStreamer.h.
References Debug, EmitCFISections(), EmitFrames(), and getCurrentFragment().
mayHaveInstructions()
bool MCObjectStreamer::mayHaveInstructions (MCSection & Sec) const override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 364 of file MCObjectStreamer.cpp.
References llvm::MCSection::hasInstructions().
reset()
void MCObjectStreamer::reset () override virtual
state management
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 163 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::reset().
Referenced by llvm::MCELFStreamer::reset(), llvm::MCWinCOFFStreamer::reset(), and llvm::MCWasmStreamer::reset().
visitUsedSymbol()
void MCObjectStreamer::visitUsedSymbol (const MCSymbol & Sym) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 218 of file MCObjectStreamer.cpp.
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), and insert().
The documentation for this class was generated from the following files:
include/llvm/MC/MCObjectStreamer.h
lib/MC/MCObjectStreamer.cpp