LLVM: llvm::OptBisect Class Reference
llvm::OptBisect Class Reference
This class implements a mechanism to disable passes and individual optimizations at compile time based on a command line option (-opt-bisect-limit) in order to perform a bisecting search for optimization-related problems.
#include "llvm/IR/OptBisect.h"
Public Member Functions
OptBisect ()
Default constructor, initializes the OptBisect state based on the -opt-bisect-limit command line argument.
virtual ~OptBisect ()=default
bool shouldRunPass (const Pass *P, StringRef IRDescription) override
Checks the bisect limit to determine if the specified pass should run.
bool isEnabled () const override
isEnabled should return true before calling shouldRunPass
Public Member Functions inherited from llvm::OptPassGate
virtual ~OptPassGate ()=default
Detailed Description
This class implements a mechanism to disable passes and individual optimizations at compile time based on a command line option (-opt-bisect-limit) in order to perform a bisecting search for optimization-related problems.
Definition at line 43 of file OptBisect.h.
Constructor & Destructor Documentation
OptBisect()
OptBisect::OptBisect ()
Default constructor, initializes the OptBisect state based on the -opt-bisect-limit command line argument.
By default, bisection is disabled.
Clients should not instantiate this class directly. All access should go through LLVMContext.
Definition at line 31 of file OptBisect.cpp.
References llvm::max(), and OptBisectLimit.
~OptBisect()
virtual llvm::OptBisect::~OptBisect () virtual default
Member Function Documentation
isEnabled()
bool llvm::OptBisect::isEnabled () const inline override virtual
isEnabled should return true before calling shouldRunPass
Reimplemented from llvm::OptPassGate.
Definition at line 70 of file OptBisect.h.
shouldRunPass()
bool OptBisect::shouldRunPass (const Pass * P, StringRef IRDescription) override virtual
Checks the bisect limit to determine if the specified pass should run.
If the bisect limit is set to -1, the function prints a message describing the pass and the bisect number assigned to it and return true. Otherwise, the function prints a message with the bisect number assigned to the pass and indicating whether or not the pass will be run and return true if the bisect limit has not yet been exceeded or false if it has.
Most passes should not call this routine directly. Instead, they are called through helper routines provided by the pass base classes. For instance, function passes should call FunctionPass::skipFunction().
Reimplemented from llvm::OptPassGate.
Definition at line 42 of file OptBisect.cpp.
References assert(), llvm::Pass::getPassName(), OptBisectLimit, and printPassMessage().
The documentation for this class was generated from the following files:
include/llvm/IR/OptBisect.h
lib/IR/OptBisect.cpp