LLVM: llvm::SpecialCaseList::Matcher Class Reference
llvm::SpecialCaseList::Matcher Class Reference
Represents a set of regular expressions.
#include "llvm/Support/SpecialCaseList.h"
Public Member Functions
bool insert (std::string Regexp, unsigned LineNumber, std::string &REError)
unsigned match (StringRef Query) const
Detailed Description
Represents a set of regular expressions.
Regular expressions which are "literal" (i.e. no regex metacharacters) are stored in Strings. The reason for doing so is efficiency; StringMap is much faster at matching literal strings than Regex.
Definition at line 119 of file SpecialCaseList.h.
Member Function Documentation
insert()
bool llvm::SpecialCaseList::Matcher::insert (std::string Regexp, unsigned LineNumber, std::string & REError)
Definition at line 29 of file SpecialCaseList.cpp.
References llvm::TrigramIndex::insert(), llvm::Regex::isLiteralERE(), and llvm::Regex::isValid().
match()
unsigned llvm::SpecialCaseList::Matcher::match (StringRef Query) const
Definition at line 61 of file SpecialCaseList.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), if(), and llvm::TrigramIndex::isDefinitelyOut().
The documentation for this class was generated from the following files:
include/llvm/Support/SpecialCaseList.h
lib/Support/SpecialCaseList.cpp