LLVM: llvm::VPInterleavedAccessInfo Class Reference
llvm::VPInterleavedAccessInfo Class Reference
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPInterleavedAccessInfo (VPlan &Plan, InterleavedAccessInfo &IAI)
~VPInterleavedAccessInfo ()
InterleaveGroup< VPInstruction > * getInterleaveGroup (VPInstruction *Instr) const
Get the interleave group that Instr belongs to.
Detailed Description
Definition at line 1637 of file VPlan.h.
Constructor & Destructor Documentation
VPInterleavedAccessInfo()
VPInterleavedAccessInfo::VPInterleavedAccessInfo (VPlan & Plan, InterleavedAccessInfo & IAI)
Definition at line 801 of file VPlan.cpp.
References llvm::VPlan::getEntry().
~VPInterleavedAccessInfo()
llvm::VPInterleavedAccessInfo::~VPInterleavedAccessInfo () inline
Definition at line 1659 of file VPlan.h.
References I, and llvm::SmallPtrSetImpl< PtrType >::insert().
Member Function Documentation
getInterleaveGroup()
InterleaveGroup<VPInstruction>* llvm::VPInterleavedAccessInfo::getInterleaveGroup (VPInstruction * Instr) const inline
Get the interleave group that Instr belongs to.
Returns
nullptr if doesn't have such group.
Definition at line 1672 of file VPlan.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::count(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by areConsecutiveOrMatch().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp