LLVM: llvm::BitstreamBlockInfo Class Reference
llvm::BitstreamBlockInfo Class Reference
This class maintains the abbreviations read from a block info block.
#include "llvm/Bitstream/BitstreamReader.h"
Classes
struct BlockInfo
This contains information emitted to BLOCKINFO_BLOCK blocks.
Public Member Functions
const BlockInfo * getBlockInfo (unsigned BlockID) const
If there is block info for the specified ID, return it, otherwise return null.
BlockInfo & getOrCreateBlockInfo (unsigned BlockID)
Detailed Description
This class maintains the abbreviations read from a block info block.
Definition at line 37 of file BitstreamReader.h.
Member Function Documentation
getBlockInfo()
const BlockInfo* llvm::BitstreamBlockInfo::getBlockInfo (unsigned BlockID) const inline
If there is block info for the specified ID, return it, otherwise return null.
Definition at line 54 of file BitstreamReader.h.
References llvm::BitstreamBlockInfo::BlockInfo::BlockID, and llvm::numbers::e.
Referenced by llvm::BitstreamCursor::EnterSubBlock(), GetBlockName(), GetCodeName(), and getOrCreateBlockInfo().
getOrCreateBlockInfo()
BlockInfo& llvm::BitstreamBlockInfo::getOrCreateBlockInfo (unsigned BlockID) inline
Definition at line 66 of file BitstreamReader.h.
References llvm::BitstreamBlockInfo::BlockInfo::BlockID, and getBlockInfo().
The documentation for this class was generated from the following file:
include/llvm/Bitstream/BitstreamReader.h