LLVM: llvm::jitlink::JITLinkError Class Reference
llvm::jitlink::JITLinkError Class Reference
Base class for errors originating in JIT linker, e.g.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Member Functions
JITLinkError (Twine ErrMsg)
void log (raw_ostream &OS) const override
Print an error message to an output stream.
const std::string & getErrorMessage () const
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
Public Member Functions inherited from llvm::ErrorInfo< JITLinkError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual std::string message () const
Return the error message as a string.
template<typename ErrorInfoT >
bool isA () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< JITLinkError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
Base class for errors originating in JIT linker, e.g.
missing relocation support.
Definition at line 42 of file JITLink.h.
Constructor & Destructor Documentation
JITLinkError()
llvm::jitlink::JITLinkError::JITLinkError (Twine ErrMsg) inline
Definition at line 46 of file JITLink.h.
References log().
Member Function Documentation
convertToErrorCode()
std::error_code llvm::jitlink::JITLinkError::convertToErrorCode () const override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 55 of file JITLink.cpp.
Referenced by getErrorMessage().
getErrorMessage()
const std::string& llvm::jitlink::JITLinkError::getErrorMessage () const inline
Definition at line 49 of file JITLink.h.
References convertToErrorCode().
log()
void llvm::jitlink::JITLinkError::log (raw_ostream & OS) const override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 53 of file JITLink.cpp.
Referenced by JITLinkError().
Member Data Documentation
ID
char llvm::jitlink::JITLinkError::ID = 0 static
Definition at line 44 of file JITLink.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLink.h
lib/ExecutionEngine/JITLink/JITLink.cpp