LLVM: llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size > Class Template Reference
llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size > Class Template Reference
#include "llvm/ADT/EnumeratedArray.h"
Public Member Functions
EnumeratedArray ()=default
EnumeratedArray (ValueType V)
const ValueType & operator[] (const Enumeration Index) const
ValueType & operator[] (const Enumeration Index)
Detailed Description
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)>
class llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >
Definition at line 23 of file EnumeratedArray.h.
Constructor & Destructor Documentation
EnumeratedArray() [1/2]
template<typename ValueType , typename Enumeration , Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray () default
EnumeratedArray() [2/2]
template<typename ValueType , typename Enumeration , Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray (ValueType V) inline
Definition at line 26 of file EnumeratedArray.h.
References Size, and llvm::BitmaskEnumDetail::Underlying().
Member Function Documentation
operator[]() [1/2]
template<typename ValueType , typename Enumeration , Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> const ValueType& llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::operator[] (const Enumeration Index) const inline
Definition at line 31 of file EnumeratedArray.h.
References assert(), and llvm::BitmaskEnumDetail::Underlying().
operator[]() [2/2]
template<typename ValueType , typename Enumeration , Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> ValueType& llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::operator[] (const Enumeration Index) inline
Definition at line 36 of file EnumeratedArray.h.
References Size, and llvm::BitmaskEnumDetail::Underlying().
The documentation for this class was generated from the following file:
include/llvm/ADT/EnumeratedArray.h