LLVM: llvm::mca::SourceMgr Class Reference
llvm::mca::SourceMgr Class Reference
#include "llvm/MCA/SourceMgr.h"
Public Types
using const_iterator = ArrayRef< UniqueInst >::const_iterator
Public Member Functions
SourceMgr (ArrayRef< UniqueInst > S, unsigned Iter)
unsigned getNumIterations () const
unsigned size () const
bool hasNext () const
void updateNext ()
SourceRef peekNext () const
const_iterator begin () const
const_iterator end () const
Detailed Description
Definition at line 28 of file SourceMgr.h.
Member Typedef Documentation
const_iterator
using llvm::mca::SourceMgr::const_iterator = ArrayRef<UniqueInst>::const_iterator
Definition at line 49 of file SourceMgr.h.
Constructor & Destructor Documentation
SourceMgr()
llvm::mca::SourceMgr::SourceMgr (ArrayRef< UniqueInst > S, unsigned Iter) inline
Definition at line 36 of file SourceMgr.h.
Member Function Documentation
begin()
const_iterator llvm::mca::SourceMgr::begin () const inline
Definition at line 50 of file SourceMgr.h.
References llvm::ArrayRef< T >::begin().
end()
const_iterator llvm::mca::SourceMgr::end () const inline
Definition at line 51 of file SourceMgr.h.
References llvm::ArrayRef< T >::end().
getNumIterations()
unsigned llvm::mca::SourceMgr::getNumIterations () const inline
Definition at line 39 of file SourceMgr.h.
hasNext()
bool llvm::mca::SourceMgr::hasNext () const inline
Definition at line 41 of file SourceMgr.h.
References llvm::ArrayRef< T >::size().
Referenced by llvm::mca::EntryStage::isAvailable(), and peekNext().
peekNext()
SourceRef llvm::mca::SourceMgr::peekNext () const inline
Definition at line 44 of file SourceMgr.h.
References assert(), hasNext(), and llvm::ArrayRef< T >::size().
Referenced by llvm::mca::EntryStage::isAvailable().
size()
unsigned llvm::mca::SourceMgr::size () const inline
Definition at line 40 of file SourceMgr.h.
References llvm::ArrayRef< T >::size().
updateNext()
void llvm::mca::SourceMgr::updateNext () inline
Definition at line 42 of file SourceMgr.h.
Referenced by llvm::mca::EntryStage::isAvailable().
The documentation for this class was generated from the following file:
include/llvm/MCA/SourceMgr.h