LLVM: llvm::jitlink::LinkGraph Class Reference
llvm::jitlink::LinkGraph Class Reference
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Classes
class nested_collection_iterator
Public Types
using external_symbol_iterator = ExternalSymbolSet::iterator
using section_iterator = pointee_iterator< SectionList::iterator >
using const_section_iterator = pointee_iterator< SectionList::const_iterator >
using defined_symbol_iterator = nested_collection_iterator< const_section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols >
using const_defined_symbol_iterator = nested_collection_iterator< const_section_iterator, Section::const_symbol_iterator, const Symbol *, getSectionConstSymbols >
using block_iterator = nested_collection_iterator< const_section_iterator, Section::block_iterator, Block *, getSectionBlocks >
using const_block_iterator = nested_collection_iterator< const_section_iterator, Section::const_block_iterator, const Block *, getSectionConstBlocks >
using SplitBlockCache = Optional< SmallVector< Symbol *, 8 > >
Cache type for the splitBlock function.
Public Member Functions
LinkGraph (std::string Name, unsigned PointerSize, support::endianness Endianness)
const std::string & getName ()
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
unsigned getPointerSize () const
Returns the pointer size for use in this graph.
support::endianness getEndianness () const
Returns the endianness of content in this graph.
Section & createSection (StringRef Name, sys::Memory::ProtectionFlags Prot)
Create a section with the given name, protection flags, and alignment.
Block & createContentBlock (Section &Parent, StringRef Content, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a content block.
Block & createZeroFillBlock (Section &Parent, uint64_t Size, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a zero-fill block.
Block & splitBlock (Block &B, size_t SplitIndex, SplitBlockCache *Cache=nullptr)
Splits block B at the given index which must be greater than zero.
Symbol & addExternalSymbol (StringRef Name, uint64_t Size, Linkage L)
Add an external symbol.
Symbol & addAbsoluteSymbol (StringRef Name, JITTargetAddress Address, uint64_t Size, Linkage L, Scope S, bool IsLive)
Add an absolute symbol.
Symbol & addCommonSymbol (StringRef Name, Scope S, Section &Section, JITTargetAddress Address, uint64_t Size, uint64_t Alignment, bool IsLive)
Convenience method for adding a weak zero-fill symbol.
Symbol & addAnonymousSymbol (Block &Content, JITTargetAddress Offset, JITTargetAddress Size, bool IsCallable, bool IsLive)
Add an anonymous symbol.
Symbol & addDefinedSymbol (Block &Content, JITTargetAddress Offset, StringRef Name, JITTargetAddress Size, Linkage L, Scope S, bool IsCallable, bool IsLive)
Add a named symbol.
iterator_range< section_iterator > sections ()
Section * findSectionByName (StringRef Name)
Returns the section with the given name if it exists, otherwise returns null.
iterator_range< block_iterator > blocks ()
iterator_range< const_block_iterator > blocks () const
iterator_range< external_symbol_iterator > external_symbols ()
iterator_range< external_symbol_iterator > absolute_symbols ()
iterator_range< defined_symbol_iterator > defined_symbols ()
iterator_range< const_defined_symbol_iterator > defined_symbols () const
void makeExternal (Symbol &Sym)
Turn a defined symbol into an external one.
void removeExternalSymbol (Symbol &Sym)
Removes an external symbol. Also removes the underlying Addressable.
void removeAbsoluteSymbol (Symbol &Sym)
Remove an absolute symbol. Also removes the underlying Addressable.
void removeDefinedSymbol (Symbol &Sym)
Removes defined symbols. Does not remove the underlying block.
void removeBlock (Block &B)
Remove a block.
void dump (raw_ostream &OS, std::function< StringRef(Edge::Kind)> EdegKindToName=std::function< StringRef(Edge::Kind)>())
Dump the graph.
Detailed Description
Definition at line 653 of file JITLink.h.
Member Typedef Documentation
block_iterator
using llvm::jitlink::LinkGraph::block_iterator = nested_collection_iterator<const_section_iterator, Section::block_iterator, Block *, getSectionBlocks>
Definition at line 773 of file JITLink.h.
const_block_iterator
using llvm::jitlink::LinkGraph::const_block_iterator = nested_collection_iterator<const_section_iterator, Section::const_block_iterator, const Block *, getSectionConstBlocks>
Definition at line 778 of file JITLink.h.
const_defined_symbol_iterator
using llvm::jitlink::LinkGraph::const_defined_symbol_iterator = nested_collection_iterator<const_section_iterator, Section::const_symbol_iterator, const Symbol *, getSectionConstSymbols>
Definition at line 769 of file JITLink.h.
const_section_iterator
using llvm::jitlink::LinkGraph::const_section_iterator = pointee_iterator<SectionList::const_iterator>
Definition at line 712 of file JITLink.h.
defined_symbol_iterator
using llvm::jitlink::LinkGraph::defined_symbol_iterator = nested_collection_iterator<const_section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols>
Definition at line 764 of file JITLink.h.
external_symbol_iterator
using llvm::jitlink::LinkGraph::external_symbol_iterator = ExternalSymbolSet::iterator
Definition at line 709 of file JITLink.h.
section_iterator
using llvm::jitlink::LinkGraph::section_iterator = pointee_iterator<SectionList::iterator>
Definition at line 711 of file JITLink.h.
SplitBlockCache
using llvm::jitlink::LinkGraph::SplitBlockCache = Optional<SmallVector<Symbol *, 8> >
Cache type for the splitBlock function.
Definition at line 816 of file JITLink.h.
Constructor & Destructor Documentation
LinkGraph()
llvm::jitlink::LinkGraph::LinkGraph (std::string Name, unsigned PointerSize, support::endianness Endianness) inline
Definition at line 780 of file JITLink.h.
Member Function Documentation
absolute_symbols()
iterator_range<external_symbol_iterator> llvm::jitlink::LinkGraph::absolute_symbols () inline
Definition at line 931 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::modifyPassConfig(), and llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved().
addAbsoluteSymbol()
Symbol& llvm::jitlink::LinkGraph::addAbsoluteSymbol (StringRef Name, JITTargetAddress Address, uint64_t Size, Linkage L, Scope S, bool IsLive) inline
Add an absolute symbol.
Definition at line 861 of file JITLink.h.
References Allocator.
addAnonymousSymbol()
Symbol& llvm::jitlink::LinkGraph::addAnonymousSymbol (Block & Content, JITTargetAddress Offset, JITTargetAddress Size, bool IsCallable, bool IsLive) inline
Add an anonymous symbol.
Definition at line 883 of file JITLink.h.
References Allocator, and llvm::jitlink::Block::getSection().
addCommonSymbol()
Symbol& llvm::jitlink::LinkGraph::addCommonSymbol (StringRef Name, Scope S, Section & Section, JITTargetAddress Address, uint64_t Size, uint64_t Alignment, bool IsLive) inline
Convenience method for adding a weak zero-fill symbol.
Definition at line 871 of file JITLink.h.
References Allocator.
addDefinedSymbol()
Symbol& llvm::jitlink::LinkGraph::addDefinedSymbol (Block & Content, JITTargetAddress Offset, StringRef Name, JITTargetAddress Size, Linkage L, Scope S, bool IsCallable, bool IsLive) inline
Add a named symbol.
Definition at line 893 of file JITLink.h.
References Allocator, and llvm::jitlink::Block::getSection().
addExternalSymbol()
Symbol& llvm::jitlink::LinkGraph::addExternalSymbol (StringRef Name, uint64_t Size, Linkage L) inline
Add an external symbol.
Some formats (e.g. ELF) allow Symbols to have sizes. For Symbols whose size is not known, you should substitute '0'. For external symbols Linkage determines whether the symbol must be present during lookup: Externals with strong linkage must be found or an error will be emitted. Externals with weak linkage are permitted to be undefined, in which case they are assigned a value of 0.
Definition at line 852 of file JITLink.h.
References Allocator.
blocks() [1/2]
iterator_range<block_iterator> llvm::jitlink::LinkGraph::blocks () inline
Definition at line 917 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::jitlink::prune(), and llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
blocks() [2/2]
iterator_range<const_block_iterator> llvm::jitlink::LinkGraph::blocks () const inline
Definition at line 922 of file JITLink.h.
References llvm::make_range().
createContentBlock()
Block& llvm::jitlink::LinkGraph::createContentBlock (Section & Parent, StringRef Content, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a content block.
Definition at line 803 of file JITLink.h.
createSection()
Section& llvm::jitlink::LinkGraph::createSection (StringRef Name, sys::Memory::ProtectionFlags Prot) inline
Create a section with the given name, protection flags, and alignment.
Definition at line 796 of file JITLink.h.
References llvm::ARMBuildAttrs::Section, and llvm::StringRef::size().
createZeroFillBlock()
Block& llvm::jitlink::LinkGraph::createZeroFillBlock (Section & Parent, uint64_t Size, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a zero-fill block.
Definition at line 810 of file JITLink.h.
defined_symbols() [1/2]
iterator_range<defined_symbol_iterator> llvm::jitlink::LinkGraph::defined_symbols () inline
Definition at line 935 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::jitlink::markAllSymbolsLive(), llvm::orc::ObjectLinkingLayerJITLinkContext::modifyPassConfig(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), and llvm::jitlink::prune().
defined_symbols() [2/2]
iterator_range<const_defined_symbol_iterator> llvm::jitlink::LinkGraph::defined_symbols () const inline
Definition at line 940 of file JITLink.h.
References llvm::make_range().
dump()
void llvm::jitlink::LinkGraph::dump (raw_ostream & OS, std::function< StringRef(Edge::Kind)> EdegKindToName = std::function<StringRef(Edge::Kind)>())
Dump the graph.
If supplied, the EdgeKindToName function will be used to name edge kinds in the debug output. Otherwise raw edge kind numbers will be displayed.
Definition at line 231 of file JITLink.cpp.
References E, llvm::StringRef::empty(), llvm::format(), llvm::jitlink::getGenericEdgeKindName(), llvm::jitlink::printEdge(), and llvm::to_string().
external_symbols()
iterator_range<external_symbol_iterator> llvm::jitlink::LinkGraph::external_symbols () inline
Definition at line 927 of file JITLink.h.
References llvm::make_range().
findSectionByName()
Section* llvm::jitlink::LinkGraph::findSectionByName (StringRef Name) inline
Returns the section with the given name if it exists, otherwise returns null.
Definition at line 910 of file JITLink.h.
References llvm::jitlink::Section::getName(), and Name.
Referenced by llvm::jitlink::createEHFrameRecorderPass(), llvm::jitlink::EHFrameSplitter::operator()(), and llvm::jitlink::EHFrameEdgeFixer::operator()().
getEndianness()
support::endianness llvm::jitlink::LinkGraph::getEndianness () const inline
Returns the endianness of content in this graph.
Definition at line 793 of file JITLink.h.
References llvm::msgpack::Endianness.
getName()
const std::string& llvm::jitlink::LinkGraph::getName () inline
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
Definition at line 787 of file JITLink.h.
References Name.
getPointerSize()
unsigned llvm::jitlink::LinkGraph::getPointerSize () const inline
Returns the pointer size for use in this graph.
Definition at line 790 of file JITLink.h.
makeExternal()
void llvm::jitlink::LinkGraph::makeExternal (Symbol & Sym) inline
Turn a defined symbol into an external one.
Definition at line 947 of file JITLink.h.
References assert(), llvm::jitlink::Symbol::getAddressable(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Block::getSection(), llvm::jitlink::Addressable::isAbsolute(), and llvm::jitlink::Symbol::isDefined().
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::modifyPassConfig().
removeAbsoluteSymbol()
void llvm::jitlink::LinkGraph::removeAbsoluteSymbol (Symbol & Sym) inline
Remove an absolute symbol. Also removes the underlying Addressable.
Definition at line 973 of file JITLink.h.
References assert(), llvm::jitlink::Symbol::isAbsolute(), and llvm::jitlink::Symbol::isDefined().
removeBlock()
void llvm::jitlink::LinkGraph::removeBlock (Block & B) inline
Remove a block.
Definition at line 992 of file JITLink.h.
References Allocator, llvm::dump(), llvm::msgpack::Endianness, function, llvm::jitlink::Block::getSection(), and Name.
Referenced by llvm::jitlink::prune().
removeDefinedSymbol()
void llvm::jitlink::LinkGraph::removeDefinedSymbol (Symbol & Sym) inline
Removes defined symbols. Does not remove the underlying block.
Definition at line 985 of file JITLink.h.
References assert(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Block::getSection(), and llvm::jitlink::Symbol::isDefined().
Referenced by llvm::jitlink::prune().
removeExternalSymbol()
void llvm::jitlink::LinkGraph::removeExternalSymbol (Symbol & Sym) inline
Removes an external symbol. Also removes the underlying Addressable.
Definition at line 962 of file JITLink.h.
References assert(), llvm::jitlink::Symbol::isAbsolute(), and llvm::jitlink::Symbol::isDefined().
sections()
iterator_range<section_iterator> llvm::jitlink::LinkGraph::sections () inline
Definition at line 903 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::jitlink::EHFrameEdgeFixer::operator()().
splitBlock()
Block & llvm::jitlink::LinkGraph::splitBlock (Block & B, size_t SplitIndex, SplitBlockCache * Cache = nullptr)
Splits block B at the given index which must be greater than zero.
If SplitIndex == B.getSize() then this function is a no-op and returns B. If SplitIndex < B.getSize() then this function returns a new block covering the range [ 0, SplitIndex), and B is modified to cover the range [ SplitIndex, B.size()).
The optional Cache parameter can be used to speed up repeated calls to splitBlock for a single block. If the value is None the cache will be treated as uninitialized and splitBlock will populate it. Otherwise it is assumed to contain the list of Symbols pointing at B, sorted in descending order of offset.
Notes:
The newly introduced block will have a new ordinal which will be higher than any other ordinals in the section. Clients are responsible for re-assigning block ordinals to restore a compatible order if needed.
The cache is not automatically updated if new symbols are introduced between calls to splitBlock. Any newly introduced symbols may be added to the cache manually (descending offset order must be preserved), or the cache can be set to None and rebuilt by splitBlock on the next call.
Definition at line 152 of file JITLink.cpp.
References assert(), B, E, llvm::jitlink::Block::edges(), llvm::jitlink::Addressable::getAddress(), llvm::jitlink::Block::getAlignment(), llvm::jitlink::Block::getAlignmentOffset(), llvm::jitlink::Block::getContent(), llvm::jitlink::Symbol::getOffset(), llvm::jitlink::Block::getSection(), llvm::jitlink::Block::getSize(), I, llvm::jitlink::Block::isZeroFill(), llvm::None, llvm::jitlink::Block::removeEdge(), llvm::jitlink::Addressable::setAddress(), llvm::jitlink::Block::setAlignmentOffset(), llvm::jitlink::Block::setContent(), llvm::sort(), llvm::StringRef::substr(), and llvm::jitlink::Section::symbols().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLink.h
lib/ExecutionEngine/JITLink/JITLink.cpp