LLVM: llvm::LoopDeletionPass Class Reference
llvm::LoopDeletionPass Class Reference
#include "llvm/Transforms/Scalar/LoopDeletion.h"
Public Member Functions
LoopDeletionPass ()=default
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopDeletionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 24 of file LoopDeletion.h.
Constructor & Destructor Documentation
LoopDeletionPass()
llvm::LoopDeletionPass::LoopDeletionPass () default
Member Function Documentation
run()
PreservedAnalyses LoopDeletionPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 209 of file LoopDeletion.cpp.
References llvm::PreservedAnalyses::all(), llvm::dbgs(), Deleted, deleteLoopIfDead(), llvm::LoopStandardAnalysisResults::DT, llvm::Loop::dump(), llvm::getLoopAnalysisUsage(), llvm::getLoopPassPreservedAnalyses(), llvm::Loop::getName(), llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeLoopDeletionLegacyPassPass(), llvm::LoopStandardAnalysisResults::LI, LLVM_DEBUG, llvm::LPMUpdater::markLoopAsDeleted(), llvm::LoopStandardAnalysisResults::SE, and llvm::Unmodified.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopDeletion.h
lib/Transforms/Scalar/LoopDeletion.cpp