LLVM: llvm::pdb::ModuleDebugStreamRef Class Reference
llvm::pdb::ModuleDebugStreamRef Class Reference
#include "llvm/DebugInfo/PDB/Native/ModuleDebugStream.h"
Public Member Functions
ModuleDebugStreamRef (const DbiModuleDescriptor &Module, std::unique_ptr< msf::MappedBlockStream > Stream)
ModuleDebugStreamRef (ModuleDebugStreamRef &&Other)=default
ModuleDebugStreamRef (const ModuleDebugStreamRef &Other)=default
~ModuleDebugStreamRef ()
Error reload ()
uint32_t signature () const
iterator_range< codeview::CVSymbolArray::Iterator > symbols (bool *HadError) const
const codeview::CVSymbolArray & getSymbolArray () const
const codeview::CVSymbolArray getSymbolArrayForScope (uint32_t ScopeBegin) const
BinarySubstreamRef getSymbolsSubstream () const
BinarySubstreamRef getC11LinesSubstream () const
BinarySubstreamRef getC13LinesSubstream () const
BinarySubstreamRef getGlobalRefsSubstream () const
ModuleDebugStreamRef & operator= (ModuleDebugStreamRef &&Other)=delete
codeview::CVSymbol readSymbolAtOffset (uint32_t Offset) const
iterator_range< DebugSubsectionIterator > subsections () const
codeview::DebugSubsectionArray getSubsectionsArray () const
bool hasDebugSubsections () const
Error commit ()
Expected< codeview::DebugChecksumsSubsectionRef > findChecksumsSubsection () const
Detailed Description
Definition at line 28 of file ModuleDebugStream.h.
Constructor & Destructor Documentation
ModuleDebugStreamRef() [1/3]
llvm::pdb::ModuleDebugStreamRef::ModuleDebugStreamRef (const DbiModuleDescriptor & Module, std::unique_ptr< msf::MappedBlockStream > Stream)
ModuleDebugStreamRef() [2/3]
llvm::pdb::ModuleDebugStreamRef::ModuleDebugStreamRef (ModuleDebugStreamRef && Other) default
ModuleDebugStreamRef() [3/3]
llvm::pdb::ModuleDebugStreamRef::ModuleDebugStreamRef (const ModuleDebugStreamRef & Other) default
~ModuleDebugStreamRef()
ModuleDebugStreamRef::~ModuleDebugStreamRef () default
Member Function Documentation
commit()
Error ModuleDebugStreamRef::commit ()
Definition at line 130 of file ModuleDebugStream.cpp.
References llvm::Error::success().
Referenced by getSubsectionsArray().
findChecksumsSubsection()
Expected< codeview::DebugChecksumsSubsectionRef > ModuleDebugStreamRef::findChecksumsSubsection () const
Definition at line 133 of file ModuleDebugStream.cpp.
References llvm::codeview::EC, llvm::codeview::DebugChecksumsSubsectionRef::initialize(), and llvm::X86AS::SS.
Referenced by getSubsectionsArray().
getC11LinesSubstream()
BinarySubstreamRef ModuleDebugStreamRef::getC11LinesSubstream () const
Definition at line 98 of file ModuleDebugStream.cpp.
Referenced by getSymbolArray().
getC13LinesSubstream()
BinarySubstreamRef ModuleDebugStreamRef::getC13LinesSubstream () const
Definition at line 102 of file ModuleDebugStream.cpp.
Referenced by getSymbolArray().
getGlobalRefsSubstream()
BinarySubstreamRef ModuleDebugStreamRef::getGlobalRefsSubstream () const
Definition at line 106 of file ModuleDebugStream.cpp.
Referenced by getSymbolArray().
getSubsectionsArray()
codeview::DebugSubsectionArray llvm::pdb::ModuleDebugStreamRef::getSubsectionsArray () const inline
Definition at line 59 of file ModuleDebugStream.h.
References commit(), findChecksumsSubsection(), and hasDebugSubsections().
getSymbolArray()
const codeview::CVSymbolArray& llvm::pdb::ModuleDebugStreamRef::getSymbolArray () const inline
Definition at line 45 of file ModuleDebugStream.h.
References getC11LinesSubstream(), getC13LinesSubstream(), getGlobalRefsSubstream(), getSymbolArrayForScope(), getSymbolsSubstream(), operator=(), readSymbolAtOffset(), and subsections().
getSymbolArrayForScope()
const codeview::CVSymbolArray ModuleDebugStreamRef::getSymbolArrayForScope (uint32_t ScopeBegin) const
Definition at line 90 of file ModuleDebugStream.cpp.
References llvm::codeview::limitSymbolArrayToScope().
Referenced by getSymbolArray().
getSymbolsSubstream()
BinarySubstreamRef ModuleDebugStreamRef::getSymbolsSubstream () const
Definition at line 94 of file ModuleDebugStream.cpp.
Referenced by getSymbolArray().
hasDebugSubsections()
bool ModuleDebugStreamRef::hasDebugSubsections () const
Definition at line 126 of file ModuleDebugStream.cpp.
Referenced by getSubsectionsArray().
operator=()
ModuleDebugStreamRef& llvm::pdb::ModuleDebugStreamRef::operator= (ModuleDebugStreamRef && Other) delete
Referenced by getSymbolArray().
readSymbolAtOffset()
CVSymbol ModuleDebugStreamRef::readSymbolAtOffset (uint32_t Offset) const
Definition at line 115 of file ModuleDebugStream.cpp.
References assert().
Referenced by getSymbolArray().
reload()
Error ModuleDebugStreamRef::reload ()
Definition at line 37 of file ModuleDebugStream.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::pdb::corrupt_file, E, llvm::codeview::EC, llvm::pdb::kInvalidStreamIndex, llvm::Mod, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readSubstream(), llvm::BinaryStreamReader::setOffset(), and llvm::Error::success().
signature()
uint32_t llvm::pdb::ModuleDebugStreamRef::signature () const inline
Definition at line 40 of file ModuleDebugStream.h.
References symbols().
subsections()
iterator_range< ModuleDebugStreamRef::DebugSubsectionIterator > ModuleDebugStreamRef::subsections () const
Definition at line 122 of file ModuleDebugStream.cpp.
References llvm::make_range().
Referenced by getSymbolArray().
symbols()
iterator_range< codeview::CVSymbolArray::Iterator > ModuleDebugStreamRef::symbols (bool * HadError) const
Definition at line 111 of file ModuleDebugStream.cpp.
References llvm::make_range().
Referenced by signature().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/ModuleDebugStream.h
lib/DebugInfo/PDB/Native/ModuleDebugStream.cpp