LLVM: llvm::codeview::DebugLinesSubsectionRef Class Reference
llvm::codeview::DebugLinesSubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugLinesSubsection.h"
Public Member Functions
DebugLinesSubsectionRef ()
Error initialize (BinaryStreamReader Reader)
Iterator begin () const
Iterator end () const
const LineFragmentHeader * header () const
bool hasColumnInfo () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Friends
class LineColumnExtractor
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 78 of file DebugLinesSubsection.h.
Constructor & Destructor Documentation
DebugLinesSubsectionRef()
DebugLinesSubsectionRef::DebugLinesSubsectionRef ()
Definition at line 53 of file DebugLinesSubsection.cpp.
Member Function Documentation
begin()
Iterator llvm::codeview::DebugLinesSubsectionRef::begin () const inline
Definition at line 93 of file DebugLinesSubsection.h.
classof()
static bool llvm::codeview::DebugLinesSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 87 of file DebugLinesSubsection.h.
References initialize(), llvm::codeview::DebugSubsectionRef::kind(), and llvm::codeview::Lines.
end()
Iterator llvm::codeview::DebugLinesSubsectionRef::end () const inline
Definition at line 94 of file DebugLinesSubsection.h.
hasColumnInfo()
bool DebugLinesSubsectionRef::hasColumnInfo () const
Definition at line 67 of file DebugLinesSubsection.cpp.
References llvm::codeview::LineFragmentHeader::Flags, and llvm::codeview::LF_HaveColumns.
header()
const LineFragmentHeader* llvm::codeview::DebugLinesSubsectionRef::header () const inline
Definition at line 96 of file DebugLinesSubsection.h.
initialize()
Error DebugLinesSubsectionRef::initialize (BinaryStreamReader Reader)
Definition at line 56 of file DebugLinesSubsection.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::EC, llvm::VarStreamArray< ValueType, Extractor >::getExtractor(), llvm::codeview::LineColumnExtractor::Header, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), and llvm::Error::success().
Referenced by llvm::codeview::visitDebugSubsection().
Friends And Related Function Documentation
LineColumnExtractor
friend class LineColumnExtractor friend
Definition at line 79 of file DebugLinesSubsection.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugLinesSubsection.h
lib/DebugInfo/CodeView/DebugLinesSubsection.cpp