LLVM: llvm::ResourceManager Class Reference
llvm::ResourceManager Class Reference
#include "llvm/CodeGen/MachinePipeliner.h"
Public Member Functions
ResourceManager (const TargetSubtargetInfo *ST)
void initProcResourceVectors (const MCSchedModel &SM, SmallVectorImpl< uint64_t > &Masks)
bool canReserveResources (const MCInstrDesc *MID) const
Check if the resources occupied by a MCInstrDesc are available in the current state.
void reserveResources (const MCInstrDesc *MID)
Reserve the resources occupied by a MCInstrDesc and change the current state to reflect that change.
bool canReserveResources (const MachineInstr &MI) const
Check if the resources occupied by a machine instruction are available in the current state.
void reserveResources (const MachineInstr &MI)
Reserve the resources occupied by a machine instruction and change the current state to reflect that change.
void clearResources ()
Reset the state.
Detailed Description
Definition at line 428 of file MachinePipeliner.h.
Constructor & Destructor Documentation
ResourceManager()
llvm::ResourceManager::ResourceManager (const TargetSubtargetInfo * ST) inline
Definition at line 443 of file MachinePipeliner.h.
References llvm::TargetInstrInfo::CreateTargetScheduleState(), llvm::TargetSubtargetInfo::getInstrInfo(), and MI.
Member Function Documentation
canReserveResources() [1/2]
bool ResourceManager::canReserveResources (const MCInstrDesc * MID) const
Check if the resources occupied by a MCInstrDesc are available in the current state.
Definition at line 2933 of file MachinePipeliner.cpp.
References llvm::MCWriteProcResEntry::Cycles, llvm::dbgs(), E, llvm::format(), llvm::MCInstrDesc::getSchedClass(), I, llvm::MCInstrDesc::isPseudo(), llvm::MCSchedClassDesc::isValid(), LLVM_DEBUG, llvm::MCProcResourceDesc::Name, llvm::MCProcResourceDesc::NumUnits, llvm::MCWriteProcResEntry::ProcResourceIdx, and SwpDebugResource.
Referenced by getUnderlyingObjects().
canReserveResources() [2/2]
bool ResourceManager::canReserveResources (const MachineInstr & MI) const
Check if the resources occupied by a machine instruction are available in the current state.
Definition at line 3014 of file MachinePipeliner.cpp.
References llvm::MachineInstr::getDesc().
clearResources()
void ResourceManager::clearResources ()
Reset the state.
Definition at line 3022 of file MachinePipeliner.cpp.
initProcResourceVectors()
void ResourceManager::initProcResourceVectors (const MCSchedModel & SM, SmallVectorImpl< uint64_t > & Masks)
Definition at line 2891 of file MachinePipeliner.cpp.
References assert(), llvm::dbgs(), E, llvm::format(), llvm::MCSchedModel::getNumProcResourceKinds(), llvm::MCSchedModel::getProcResource(), I, LLVM_DEBUG, llvm::MCProcResourceDesc::Name, llvm::MCProcResourceDesc::NumUnits, llvm::SmallVectorImpl< T >::resize(), llvm::MCProcResourceDesc::SubUnitsIdxBegin, and SwpShowResMask.
reserveResources() [1/2]
void ResourceManager::reserveResources (const MCInstrDesc * MID)
Reserve the resources occupied by a MCInstrDesc and change the current state to reflect that change.
Definition at line 2974 of file MachinePipeliner.cpp.
References llvm::dbgs(), llvm::format(), llvm::MCInstrDesc::getSchedClass(), llvm::MCInstrDesc::isPseudo(), llvm::MCSchedClassDesc::isValid(), LLVM_DEBUG, llvm::make_range(), llvm::MCProcResourceDesc::Name, llvm::MCProcResourceDesc::NumUnits, and SwpDebugResource.
Referenced by getUnderlyingObjects().
reserveResources() [2/2]
void ResourceManager::reserveResources (const MachineInstr & MI)
Reserve the resources occupied by a machine instruction and change the current state to reflect that change.
Definition at line 3018 of file MachinePipeliner.cpp.
References llvm::MachineInstr::getDesc().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePipeliner.h
lib/CodeGen/MachinePipeliner.cpp