LLVM: llvm::MCELFObjectTargetWriter Class Reference
llvm::MCELFObjectTargetWriter Class Reference abstract
#include "llvm/MC/MCELFObjectWriter.h"
Public Member Functions
virtual ~MCELFObjectTargetWriter ()=default
virtual Triple::ObjectFormatType getFormat () const
virtual unsigned getRelocType (MCContext &Ctx, const MCValue &Target, const MCFixup &Fixup, bool IsPCRel) const =0
virtual bool needsRelocateWithSymbol (const MCSymbol &Sym, unsigned Type) const
virtual void sortRelocs (const MCAssembler &Asm, std::vector< ELFRelocationEntry > &Relocs)
virtual void addTargetSectionFlags (MCContext &Ctx, MCSectionELF &Sec)
uint8_t getRType (uint32_t Type) const
uint8_t getRType2 (uint32_t Type) const
uint8_t getRType3 (uint32_t Type) const
uint8_t getRSsym (uint32_t Type) const
unsigned setRType (unsigned Value, unsigned Type) const
unsigned setRType2 (unsigned Value, unsigned Type) const
unsigned setRType3 (unsigned Value, unsigned Type) const
unsigned setRSsym (unsigned Value, unsigned Type) const
Accessors
uint8_t getOSABI () const
uint8_t getABIVersion () const
uint16_t getEMachine () const
bool hasRelocationAddend () const
bool is64Bit () const
Public Member Functions inherited from llvm::MCObjectTargetWriter
virtual ~MCObjectTargetWriter ()=default
Static Public Member Functions
static bool classof (const MCObjectTargetWriter *W)
static uint8_t getOSABI (Triple::OSType OSType)
Protected Member Functions
MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend_, uint8_t ABIVersion_=0)
Detailed Description
Definition at line 54 of file MCELFObjectWriter.h.
Constructor & Destructor Documentation
MCELFObjectTargetWriter()
MCELFObjectTargetWriter::MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend_, uint8_t ABIVersion_ = 0) protected
Definition at line 13 of file MCELFObjectTargetWriter.cpp.
~MCELFObjectTargetWriter()
virtual llvm::MCELFObjectTargetWriter::~MCELFObjectTargetWriter () virtual default
Member Function Documentation
addTargetSectionFlags()
void MCELFObjectTargetWriter::addTargetSectionFlags (MCContext & Ctx, MCSectionELF & Sec) virtual
Definition at line 30 of file MCELFObjectTargetWriter.cpp.
classof()
static bool llvm::MCELFObjectTargetWriter::classof (const MCObjectTargetWriter * W) inline static
Definition at line 69 of file MCELFObjectWriter.h.
References llvm::Triple::ELF, and llvm::MCObjectTargetWriter::getFormat().
getABIVersion()
uint8_t llvm::MCELFObjectTargetWriter::getABIVersion () const inline
Definition at line 101 of file MCELFObjectWriter.h.
getEMachine()
uint16_t llvm::MCELFObjectTargetWriter::getEMachine () const inline
Definition at line 102 of file MCELFObjectWriter.h.
getFormat()
virtual Triple::ObjectFormatType llvm::MCELFObjectTargetWriter::getFormat () const inline virtual
Implements llvm::MCObjectTargetWriter.
Definition at line 68 of file MCELFObjectWriter.h.
References llvm::Triple::ELF.
getOSABI() [1/2]
static uint8_t llvm::MCELFObjectTargetWriter::getOSABI (Triple::OSType OSType) inline static
Definition at line 73 of file MCELFObjectWriter.h.
References llvm::HexStyle::Asm, llvm::Triple::CloudABI, llvm::ELF::ELFOSABI_CLOUDABI, llvm::ELF::ELFOSABI_FREEBSD, llvm::ELF::ELFOSABI_NONE, llvm::ELF::ELFOSABI_STANDALONE, Fixup, llvm::Triple::FreeBSD, getRelocType(), llvm::Triple::HermitCore, and llvm::Triple::PS4.
getOSABI() [2/2]
uint8_t llvm::MCELFObjectTargetWriter::getOSABI () const inline
Definition at line 100 of file MCELFObjectWriter.h.
Referenced by adjustFixupValue(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createARMAsmBackend(), llvm::createHexagonAsmBackend(), llvm::createMipsELFObjectWriter(), llvm::AVRAsmBackend::createObjectTargetWriter(), llvm::createRISCVAsmBackend(), llvm::createSystemZMCAsmBackend(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), and getFixupKindNumBytes().
getRelocType()
virtual unsigned llvm::MCELFObjectTargetWriter::getRelocType (MCContext & Ctx, const MCValue & Target, const MCFixup & Fixup, bool IsPCRel) const pure virtual
Implemented in llvm::AVRELFObjectWriter.
getRSsym()
uint8_t llvm::MCELFObjectTargetWriter::getRSsym (uint32_t Type) const inline
Definition at line 128 of file MCELFObjectWriter.h.
References R_SSYM_SHIFT.
getRType()
uint8_t llvm::MCELFObjectTargetWriter::getRType (uint32_t Type) const inline
Definition at line 119 of file MCELFObjectWriter.h.
References R_TYPE_SHIFT.
getRType2()
uint8_t llvm::MCELFObjectTargetWriter::getRType2 (uint32_t Type) const inline
Definition at line 122 of file MCELFObjectWriter.h.
References R_TYPE2_SHIFT.
getRType3()
uint8_t llvm::MCELFObjectTargetWriter::getRType3 (uint32_t Type) const inline
Definition at line 125 of file MCELFObjectWriter.h.
References R_TYPE3_SHIFT.
hasRelocationAddend()
bool llvm::MCELFObjectTargetWriter::hasRelocationAddend () const inline
Definition at line 103 of file MCELFObjectWriter.h.
is64Bit()
bool llvm::MCELFObjectTargetWriter::is64Bit () const inline
Definition at line 104 of file MCELFObjectWriter.h.
needsRelocateWithSymbol()
bool MCELFObjectTargetWriter::needsRelocateWithSymbol (const MCSymbol & Sym, unsigned Type) const virtual
Definition at line 20 of file MCELFObjectTargetWriter.cpp.
setRSsym()
unsigned llvm::MCELFObjectTargetWriter::setRSsym (unsigned Value, unsigned Type) const inline
Definition at line 142 of file MCELFObjectWriter.h.
References llvm::createELFDwoObjectWriter(), llvm::createELFObjectWriter(), R_SSYM_MASK, and R_SSYM_SHIFT.
setRType()
unsigned llvm::MCELFObjectTargetWriter::setRType (unsigned Value, unsigned Type) const inline
Definition at line 133 of file MCELFObjectWriter.h.
References R_TYPE_MASK, and R_TYPE_SHIFT.
setRType2()
unsigned llvm::MCELFObjectTargetWriter::setRType2 (unsigned Value, unsigned Type) const inline
Definition at line 136 of file MCELFObjectWriter.h.
References R_TYPE2_MASK, and R_TYPE2_SHIFT.
setRType3()
unsigned llvm::MCELFObjectTargetWriter::setRType3 (unsigned Value, unsigned Type) const inline
Definition at line 139 of file MCELFObjectWriter.h.
References R_TYPE3_MASK, and R_TYPE3_SHIFT.
sortRelocs()
void MCELFObjectTargetWriter::sortRelocs (const MCAssembler & Asm, std::vector< ELFRelocationEntry > & Relocs) virtual
Definition at line 26 of file MCELFObjectTargetWriter.cpp.
The documentation for this class was generated from the following files:
include/llvm/MC/MCELFObjectWriter.h
lib/MC/MCELFObjectTargetWriter.cpp