LLVM: llvm::ARMHazardRecognizer Class Reference
llvm::ARMHazardRecognizer Class Reference
ARMHazardRecognizer handles special constraints that are not expressed in the scheduling itinerary.
#include "Target/ARM/ARMHazardRecognizer.h"
Public Member Functions
ARMHazardRecognizer (const InstrItineraryData *ItinData, const ScheduleDAG *DAG)
HazardType getHazardType (SUnit *SU, int Stalls) override
getHazardType - Return the hazard type of emitting this node.
void Reset () override
Reset - This callback is invoked when a new block of instructions is about to be schedule.
void EmitInstruction (SUnit *SU) override
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
void AdvanceCycle () override
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
void RecedeCycle () override
RecedeCycle - This callback is invoked whenever the next bottom-up instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
Public Member Functions inherited from llvm::ScoreboardHazardRecognizer
ScoreboardHazardRecognizer (const InstrItineraryData *II, const ScheduleDAG *DAG, const char *ParentDebugType="")
bool atIssueLimit () const override
atIssueLimit - Return true if no more instructions may be issued in this cycle.
Public Member Functions inherited from llvm::ScheduleHazardRecognizer
ScheduleHazardRecognizer ()=default
virtual ~ScheduleHazardRecognizer ()
unsigned getMaxLookAhead () const
bool isEnabled () const
virtual void EmitInstruction (MachineInstr *)
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
virtual unsigned PreEmitNoops (SUnit *)
PreEmitNoops - This callback is invoked prior to emitting an instruction.
virtual unsigned PreEmitNoops (MachineInstr *)
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
virtual bool ShouldPreferAnother (SUnit *)
ShouldPreferAnother - This callback may be invoked if getHazardType returns NoHazard.
virtual void EmitNoop ()
EmitNoop - This callback is invoked when a noop was added to the instruction stream.
Additional Inherited Members
Public Types inherited from llvm::ScheduleHazardRecognizer
enum HazardType { NoHazard, Hazard, NoopHazard }
Protected Attributes inherited from llvm::ScheduleHazardRecognizer
unsigned MaxLookAhead = 0
MaxLookAhead - Indicate the number of cycles in the scoreboard state.
Detailed Description
ARMHazardRecognizer handles special constraints that are not expressed in the scheduling itinerary.
This is only used during postRA scheduling. The ARM preRA scheduler uses an unspecialized instance of the ScoreboardHazardRecognizer.
Definition at line 29 of file ARMHazardRecognizer.h.
Constructor & Destructor Documentation
ARMHazardRecognizer()
llvm::ARMHazardRecognizer::ARMHazardRecognizer (const InstrItineraryData * ItinData, const ScheduleDAG * DAG) inline
Definition at line 34 of file ARMHazardRecognizer.h.
References AdvanceCycle(), EmitInstruction(), getHazardType(), RecedeCycle(), and Reset().
Member Function Documentation
AdvanceCycle()
void ARMHazardRecognizer::AdvanceCycle () override virtual
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
This should increment the internal state of the hazard recognizer so that previously "Hazard" instructions will now not be hazards.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 91 of file ARMHazardRecognizer.cpp.
References llvm::ScoreboardHazardRecognizer::AdvanceCycle().
Referenced by ARMHazardRecognizer().
EmitInstruction()
void ARMHazardRecognizer::EmitInstruction (SUnit *) override virtual
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 81 of file ARMHazardRecognizer.cpp.
References llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::SUnit::getInstr(), llvm::MachineInstr::isDebugInstr(), and MI.
Referenced by ARMHazardRecognizer().
getHazardType()
ScheduleHazardRecognizer::HazardType ARMHazardRecognizer::getHazardType (SUnit * m, int Stalls) override virtual
getHazardType - Return the hazard type of emitting this node.
There are three possible results. Either:
NoHazard: it is legal to issue this instruction on this cycle.
Hazard: issuing this instruction would stall the machine. If some other instruction is available, issue it first.
NoopHazard: issuing this instruction would break the program. If some other instruction can be issued, do so, otherwise issue a noop.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 34 of file ARMHazardRecognizer.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::ARMBaseInstrInfo::canCauseFpMLxStall(), DefMI, llvm::ARMII::DomainGeneral, llvm::ARMII::DomainMask, llvm::MachineInstr::getDesc(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::SUnit::getInstr(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::ARMBaseInstrInfo::getRegisterInfo(), llvm::ARMBaseInstrInfo::getSubtarget(), llvm::MachineFunction::getSubtarget(), llvm::ARMSubtarget::hasMuxedUnits(), hasRAWHazard(), llvm::ScheduleHazardRecognizer::Hazard, I, llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isDebugInstr(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::MachineInstr::mayLoadOrStore(), MI, TII, and llvm::MCInstrDesc::TSFlags.
Referenced by ARMHazardRecognizer().
RecedeCycle()
void ARMHazardRecognizer::RecedeCycle () override virtual
RecedeCycle - This callback is invoked whenever the next bottom-up instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 98 of file ARMHazardRecognizer.cpp.
References llvm_unreachable.
Referenced by ARMHazardRecognizer().
Reset()
void ARMHazardRecognizer::Reset () override virtual
Reset - This callback is invoked when a new block of instructions is about to be schedule.
The hazard state should be set to an initialized state.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 75 of file ARMHazardRecognizer.cpp.
References llvm::ScoreboardHazardRecognizer::Reset().
Referenced by ARMHazardRecognizer().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMHazardRecognizer.h
lib/Target/ARM/ARMHazardRecognizer.cpp