LLVM: llvm::AVRELFObjectWriter Class Reference
llvm::AVRELFObjectWriter Class Reference
Writes AVR machine code into an ELF32 object file.
Public Member Functions
AVRELFObjectWriter (uint8_t OSABI)
virtual ~AVRELFObjectWriter ()
unsigned getRelocType (MCContext &Ctx, const MCValue &Target, const MCFixup &Fixup, bool IsPCRel) const override
Public Member Functions inherited from llvm::MCELFObjectTargetWriter
virtual ~MCELFObjectTargetWriter ()=default
virtual Triple::ObjectFormatType getFormat () const
virtual bool needsRelocateWithSymbol (const MCSymbol &Sym, unsigned Type) const
virtual void sortRelocs (const MCAssembler &Asm, std::vector< ELFRelocationEntry > &Relocs)
virtual void addTargetSectionFlags (MCContext &Ctx, MCSectionELF &Sec)
uint8_t getRType (uint32_t Type) const
uint8_t getRType2 (uint32_t Type) const
uint8_t getRType3 (uint32_t Type) const
uint8_t getRSsym (uint32_t Type) const
unsigned setRType (unsigned Value, unsigned Type) const
unsigned setRType2 (unsigned Value, unsigned Type) const
unsigned setRType3 (unsigned Value, unsigned Type) const
unsigned setRSsym (unsigned Value, unsigned Type) const
uint8_t getOSABI () const
uint8_t getABIVersion () const
uint16_t getEMachine () const
bool hasRelocationAddend () const
bool is64Bit () const
Public Member Functions inherited from llvm::MCObjectTargetWriter
virtual ~MCObjectTargetWriter ()=default
Additional Inherited Members
Static Public Member Functions inherited from llvm::MCELFObjectTargetWriter
static bool classof (const MCObjectTargetWriter *W)
static uint8_t getOSABI (Triple::OSType OSType)
Protected Member Functions inherited from llvm::MCELFObjectTargetWriter
MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend_, uint8_t ABIVersion_=0)
Detailed Description
Writes AVR machine code into an ELF32 object file.
Definition at line 23 of file AVRELFObjectWriter.cpp.
Constructor & Destructor Documentation
AVRELFObjectWriter()
llvm::AVRELFObjectWriter::AVRELFObjectWriter (uint8_t OSABI)
Definition at line 35 of file AVRELFObjectWriter.cpp.
~AVRELFObjectWriter()
virtual llvm::AVRELFObjectWriter::~AVRELFObjectWriter () inline virtual
Definition at line 27 of file AVRELFObjectWriter.cpp.
References Fixup, and getRelocType().
Member Function Documentation
getRelocType()
unsigned llvm::AVRELFObjectWriter::getRelocType (MCContext & Ctx, const MCValue & Target, const MCFixup & Fixup, bool IsPCRel) const override virtual
Implements llvm::MCELFObjectTargetWriter.
Definition at line 38 of file AVRELFObjectWriter.cpp.
References llvm::AVR::fixup_13_pcrel, llvm::AVR::fixup_16, llvm::AVR::fixup_16_pm, llvm::AVR::fixup_32, llvm::AVR::fixup_6, llvm::AVR::fixup_6_adiw, llvm::AVR::fixup_7_pcrel, llvm::AVR::fixup_8, llvm::AVR::fixup_8_hi8, llvm::AVR::fixup_8_hlo8, llvm::AVR::fixup_8_lo8, llvm::AVR::fixup_call, llvm::AVR::fixup_diff16, llvm::AVR::fixup_diff32, llvm::AVR::fixup_diff8, llvm::AVR::fixup_hh8_ldi, llvm::AVR::fixup_hh8_ldi_neg, llvm::AVR::fixup_hh8_ldi_pm, llvm::AVR::fixup_hh8_ldi_pm_neg, llvm::AVR::fixup_hi8_ldi, llvm::AVR::fixup_hi8_ldi_gs, llvm::AVR::fixup_hi8_ldi_neg, llvm::AVR::fixup_hi8_ldi_pm, llvm::AVR::fixup_hi8_ldi_pm_neg, llvm::AVR::fixup_ldi, llvm::AVR::fixup_lds_sts_16, llvm::AVR::fixup_lo8_ldi, llvm::AVR::fixup_lo8_ldi_gs, llvm::AVR::fixup_lo8_ldi_neg, llvm::AVR::fixup_lo8_ldi_pm, llvm::AVR::fixup_lo8_ldi_pm_neg, llvm::AVR::fixup_ms8_ldi, llvm::AVR::fixup_ms8_ldi_neg, llvm::AVR::fixup_port5, llvm::AVR::fixup_port6, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::MCValue::getAccessVariant(), llvm::MCFixup::getKind(), llvm_unreachable, llvm::MCSymbolRefExpr::VK_AVR_DIFF16, llvm::MCSymbolRefExpr::VK_AVR_DIFF32, llvm::MCSymbolRefExpr::VK_AVR_DIFF8, llvm::MCSymbolRefExpr::VK_AVR_HI8, llvm::MCSymbolRefExpr::VK_AVR_HLO8, llvm::MCSymbolRefExpr::VK_AVR_LO8, llvm::MCSymbolRefExpr::VK_AVR_NONE, and llvm::MCSymbolRefExpr::VK_None.
Referenced by ~AVRELFObjectWriter().
The documentation for this class was generated from the following file:
lib/Target/AVR/MCTargetDesc/AVRELFObjectWriter.cpp