LLVM: llvm::MemSDNode Class Reference
llvm::MemSDNode Class Reference
This is an abstract virtual class for memory operations.
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Member Functions
MemSDNode (unsigned Opc, unsigned Order, const DebugLoc &dl, SDVTList VTs, EVT memvt, MachineMemOperand *MMO)
bool readMem () const
bool writeMem () const
unsigned getOriginalAlignment () const
Returns alignment and volatility of the memory access.
unsigned getAlignment () const
unsigned getRawSubclassData () const
Return the SubclassData value, without HasDebugValue.
bool isVolatile () const
bool isNonTemporal () const
bool isDereferenceable () const
bool isInvariant () const
int64_t getSrcValueOffset () const
AAMDNodes getAAInfo () const
Returns the AA info that describes the dereference.
const MDNode * getRanges () const
Returns the Ranges that describes the dereference.
SyncScope::ID getSyncScopeID () const
Returns the synchronization scope ID for this memory operation.
AtomicOrdering getOrdering () const
Return the atomic ordering requirements for this memory operation.
bool isAtomic () const
Return true if the memory operation ordering is Unordered or higher.
bool isUnordered () const
Returns true if the memory operation doesn't imply any ordering constraints on surrounding memory operations beyond the normal memory aliasing rules.
bool isSimple () const
Returns true if the memory operation is neither atomic or volatile.
EVT getMemoryVT () const
Return the type of the in-memory value.
MachineMemOperand * getMemOperand () const
Return a MachineMemOperand object describing the memory reference performed by operation.
const MachinePointerInfo & getPointerInfo () const
unsigned getAddressSpace () const
Return the address space for the associated pointer.
void refineAlignment (const MachineMemOperand *NewMMO)
Update this MemSDNode's MachineMemOperand information to reflect the alignment of NewMMO, if it has a greater alignment.
const SDValue & getChain () const
const SDValue & getBasePtr () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
Return the SelectionDAG opcode value for this node.
bool isTargetOpcode () const
Test if this node has a target-specific opcode (in the <target>ISD namespace).
bool isTargetStrictFPOpcode () const
Test if this node has a target-specific opcode that may raise FP exceptions (in the <target>ISD namespace and greater than FIRST_TARGET_STRICTFP_OPCODE).
bool isTargetMemoryOpcode () const
Test if this node has a target-specific memory-referencing opcode (in the <target>ISD namespace and greater than FIRST_TARGET_MEMORY_OPCODE).
bool isUndef () const
Return true if the type of the node type undefined.
bool isMemIntrinsic () const
Test if this node is a memory intrinsic (with valid pointer information).
bool isStrictFPOpcode ()
Test if this node is a strict floating point pseudo-op.
bool isMachineOpcode () const
Test if this node has a post-isel opcode, directly corresponding to a MachineInstr opcode.
unsigned getMachineOpcode () const
This may only be called if isMachineOpcode returns true.
bool getHasDebugValue () const
void setHasDebugValue (bool b)
bool isDivergent () const
bool use_empty () const
Return true if there are no uses of this node.
bool hasOneUse () const
Return true if there is exactly one use of this node.
size_t use_size () const
Return the number of uses of this node.
int getNodeId () const
Return the unique node id.
void setNodeId (int Id)
Set unique node id.
unsigned getIROrder () const
Return the node ordering.
void setIROrder (unsigned Order)
Set the node ordering.
const DebugLoc & getDebugLoc () const
Return the source location info.
void setDebugLoc (DebugLoc dl)
Set source location info.
use_iterator use_begin () const
Provide iteration support to walk over all uses of an SDNode.
iterator_range< use_iterator > uses ()
iterator_range< use_iterator > uses () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
Return true if there are exactly NUSES uses of the indicated value.
bool hasAnyUseOfValue (unsigned Value) const
Return true if there are any use of the indicated value.
bool isOnlyUserOf (const SDNode *N) const
Return true if this node is the only use of N.
bool isOperandOf (const SDNode *N) const
Return true if this node is an operand of N.
bool isPredecessorOf (const SDNode *N) const
Return true if this node is a predecessor of N.
bool hasPredecessor (const SDNode *N) const
Return true if N is a predecessor of this node.
unsigned getNumOperands () const
Return the number of values used by this operation.
uint64_t getConstantOperandVal (unsigned Num) const
Helper method returns the integer value of a ConstantSDNode operand.
const APInt & getConstantOperandAPInt (unsigned Num) const
Helper method returns the APInt of a ConstantSDNode operand.
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< SDUse > ops () const
iterator_range< value_op_iterator > op_values () const
SDVTList getVTList () const
SDNode * getGluedNode () const
If this node has a glue operand, return the node to which the glue operand points.
SDNode * getGluedUser () const
If this node has a glue value with a user, return the user (there is at most one).
const SDNodeFlags getFlags () const
void setFlags (SDNodeFlags NewFlags)
bool isFast ()
void intersectFlagsWith (const SDNodeFlags Flags)
Clear any flags in this node that aren't also set in Flags.
unsigned getNumValues () const
Return the number of values defined/returned by this operator.
EVT getValueType (unsigned ResNo) const
Return the type of a specified result.
MVT getSimpleValueType (unsigned ResNo) const
Return the type of a specified result as a simple type.
TypeSize getValueSizeInBits (unsigned ResNo) const
Returns MVT::getSizeInBits(getValueType(ResNo)).
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=nullptr) const
Return the opcode of this operation for printing.
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printr (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printrFull (raw_ostream &O, const SelectionDAG *G=nullptr) const
Print a SelectionDAG node and all children down to the leaves.
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=nullptr, unsigned depth=100) const
Print a SelectionDAG node and children up to depth "depth." The given SelectionDAG allows target-specific nodes to be printed in human-readable form.
void dump () const
Dump this node, for debugging.
void dumpr () const
Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
Dump this node, for debugging.
void dumpr (const SelectionDAG *G) const
Dump (recursively) this node and its use-def subgraph.
void dumprFull (const SelectionDAG *G=nullptr) const
printrFull to dbgs().
void dumprWithDepth (const SelectionDAG *G=nullptr, unsigned depth=100) const
printrWithDepth to dbgs().
void Profile (FoldingSetNodeID &ID) const
Gather unique data for the node.
void addUse (SDUse &U)
This method should only be used by the SDUse class.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< SDNode, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static bool hasPredecessorHelper (const SDNode *N, SmallPtrSetImpl< const SDNode *> &Visited, SmallVectorImpl< const SDNode *> &Worklist, unsigned int MaxSteps=0, bool TopologicalPrune=false)
Returns true if N is a predecessor of any node in Worklist.
static bool areOnlyUsersOf (ArrayRef< const SDNode *> Nodes, const SDNode *N)
Return true if all the users of N are contained in Nodes.
static constexpr size_t getMaxNumOperands ()
Return the maximum number of operands that a SDNode can hold.
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Protected Attributes
MachineMemOperand * MMO
Memory reference information.
Protected Attributes inherited from llvm::SDNode
union {
char RawSDNodeBits [sizeof(uint16_t)]
SDNodeBitfields SDNodeBits
ConstantSDNodeBitfields ConstantSDNodeBits
MemSDNodeBitfields MemSDNodeBits
LSBaseSDNodeBitfields LSBaseSDNodeBits
LoadSDNodeBitfields LoadSDNodeBits
StoreSDNodeBitfields StoreSDNodeBits
};
Additional Inherited Members
Public Types inherited from llvm::SDNode
using op_iterator = SDUse *
using value_iterator = const EVT *
Public Attributes inherited from llvm::SDNode
uint16_t PersistentId
Unique and persistent id per SDNode in the DAG.
Protected Types inherited from llvm::SDNode
enum { NumSDNodeBits = 3 }
enum { NumMemSDNodeBits = NumSDNodeBits + 4 }
enum { NumLSBaseSDNodeBits = NumMemSDNodeBits + 3 }
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< SDNode, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< SDNode, Options... >::type, true, true >
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs)
Create an SDNode.
void DropOperands ()
Release the operands and set this node to have zero operands.
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< SDNode, Options... >::type >
ilist_node_impl ()=default
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Detailed Description
This is an abstract virtual class for memory operations.
Definition at line 1286 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
MemSDNode()
MemSDNode::MemSDNode (unsigned Opc, unsigned Order, const DebugLoc & dl, SDVTList VTs, EVT memvt, MachineMemOperand * MMO)
Definition at line 8975 of file SelectionDAG.cpp.
References assert(), llvm::TypeSize::getKnownMinSize(), llvm::MachineMemOperand::getSize(), llvm::EVT::getStoreSize(), llvm::MachineMemOperand::isDereferenceable(), llvm::MachineMemOperand::isInvariant(), llvm::MachineMemOperand::isNonTemporal(), llvm::MachineMemOperand::isVolatile(), llvm::SDNode::MemSDNodeBits, and MMO.
Member Function Documentation
classof()
static bool llvm::MemSDNode::classof (const SDNode * N) inline static
Definition at line 1392 of file SelectionDAGNodes.h.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_FADD, llvm::ISD::ATOMIC_LOAD_FSUB, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::SDNode::getOpcode(), llvm::SDNode::isMemIntrinsic(), llvm::SDNode::isTargetMemoryOpcode(), llvm::ISD::LOAD, llvm::ISD::MGATHER, llvm::ISD::MLOAD, llvm::ISD::MSCATTER, llvm::ISD::MSTORE, llvm::ISD::PREFETCH, and llvm::ISD::STORE.
getAAInfo()
AAMDNodes llvm::MemSDNode::getAAInfo () const inline
Returns the AA info that describes the dereference.
Definition at line 1338 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getAAInfo().
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), ExtendUsesToFormExtLoad(), foldBitcastedFPLogic(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), getLoadExtOrTrunc(), GetPromotionOpcode(), getVectorCompareInfo(), LowerSTORE(), numVectorEltsOrZero(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), PerformSTORECombine(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), truncateScalarIntegerArg(), and widenCtPop().
getAddressSpace()
unsigned llvm::MemSDNode::getAddressSpace () const inline
Return the address space for the associated pointer.
Definition at line 1374 of file SelectionDAGNodes.h.
Referenced by ConstantAddressBlock(), findMemSDNode(), getLoadExtOrTrunc(), getSPDenormModeValue(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), LowerTruncateVectorStore(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), pickOpcodeForVT(), llvm::AMDGPUTargetLowering::shouldReduceLoadWidth(), ShrinkLoadReplaceStoreWithStore(), and simplifyDivRem().
getAlignment()
unsigned llvm::MemSDNode::getAlignment () const inline
Definition at line 1306 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getAlignment().
Referenced by CombineBaseUpdate(), combineBVOfConsecutiveLoads(), combineLoad(), combineShuffle(), combineStore(), ConstantAddressBlock(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), ExtendUsesToFormExtLoad(), foldBitcastedFPLogic(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), getLoadExtOrTrunc(), getParamsForOneTrueMaskedElt(), GetPromotionOpcode(), getSPDenormModeValue(), getVectorCompareInfo(), isWordAligned(), LowerF128Load(), LowerF128Store(), lowerFP_TO_SINT_STORE(), llvm::HexagonTargetLowering::LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), llvm::HexagonTargetLowering::LowerStore(), llvm::MipsTargetLowering::lowerSTORE(), LowerSTORE(), LowerStore(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), numVectorEltsOrZero(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformTruncatingStoreCombine(), PerformVDUPCombine(), PerformVMOVRRDCombine(), ReorganizeVector(), ReplaceLoadVector(), llvm::SparcTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), SkipLoadExtensionForVMULL(), splitStores(), splitStoreSplat(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), stripTruncAndExt(), truncateScalarIntegerArg(), widenCtPop(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getBasePtr()
const SDValue& llvm::MemSDNode::getBasePtr () const inline
Definition at line 1387 of file SelectionDAGNodes.h.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and llvm::ISD::STORE.
Referenced by llvm::PPCTargetLowering::expandVSXStoreForLE(), getSPDenormModeValue(), isConsecutiveLSLoc(), matchLSNode(), pickOpcodeForVT(), llvm::AArch64TargetLowering::shouldReduceLoadWidth(), ShrinkLoadReplaceStoreWithStore(), and simplifyDivRem().
getChain()
const SDValue& llvm::MemSDNode::getChain () const inline
Definition at line 1386 of file SelectionDAGNodes.h.
References llvm::SDValue::getOperand().
Referenced by llvm::SelectionDAG::areNonVolatileConsecutiveLoads(), llvm::AVRDAGToDAGISel::select< ISD::LOAD >(), llvm::AVRDAGToDAGISel::select< ISD::STORE >(), callingConvSupported(), CollectOpsToWiden(), combineBVOfConsecutiveLoads(), combineBVOfVecSExt(), combineLoad(), combineMaskedLoadConstantMask(), combineMaskedStore(), combineShiftAnd1ToBitTest(), combineShuffle(), combineSIntToFP(), combineStore(), combineTargetShuffle(), ConstantAddressBlock(), llvm::createR600ISelDag(), earlyExpandDIVFIX(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), findConsecutiveLoad(), foldBitcastedFPLogic(), foldExtendedSignBitTest(), FoldIntToFPToInt(), GeneratePerfectShuffle(), getAL(), getContiguousRangeOfSetBits(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedMaskedLoad(), llvm::SelectionDAG::getIndexedMaskedStore(), llvm::SelectionDAG::getIndexedStore(), getLoadExtOrTrunc(), getNormalLoadInput(), GetPromotionOpcode(), getShiftAmountTyForConstant(), getSPDenormModeValue(), getVectorCompareInfo(), isFusableLoadOpStorePattern(), isOpcWithIntImmediate(), isValidIndexedLoad(), isVectorElementSwap(), isWordAligned(), LowerF128Load(), LowerF128Store(), lowerFP_TO_SINT_STORE(), llvm::MipsTargetLowering::lowerLOAD(), LowerMLOAD(), LowerMSTORE(), LowerPredicateLoad(), LowerPredicateStore(), lowerShuffleAsBroadcast(), LowerSTORE(), LowerStore(), LowerTruncateVectorStore(), lowerUnalignedIntStore(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), mayUseP9Setb(), MergeInputChains(), numVectorEltsOrZero(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformTruncatingStoreCombine(), PerformVMOVRRDCombine(), pickOpcodeForVT(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), ReorganizeVector(), ReplaceCMP_SWAP_128Results(), llvm::SparcTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), ShrinkLoadReplaceStoreWithStore(), SkipLoadExtensionForVMULL(), splitStores(), splitStoreSplat(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), truncateScalarIntegerArg(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), tryToFoldExtOfMaskedLoad(), widenCtPop(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getMemOperand()
MachineMemOperand* llvm::MemSDNode::getMemOperand () const inline
Return a MachineMemOperand object describing the memory reference performed by operation.
Definition at line 1367 of file SelectionDAGNodes.h.
Referenced by adjustLoadValueTypeImpl(), llvm::AVRDAGToDAGISel::select< ISD::LOAD >(), llvm::AVRDAGToDAGISel::select< ISD::STORE >(), callingConvSupported(), canLowerToLDG(), chainLoadsAndStoresForMemcpy(), CollectOpsToWiden(), CombineBaseUpdate(), combineBVOfVecSExt(), combineLoad(), combineMaskedLoadConstantMask(), combineMaskedStore(), combineShiftAnd1ToBitTest(), combineStore(), combineTargetShuffle(), CombineVLDDUP(), ConstantAddressBlock(), createLoadLR(), llvm::createR600ISelDag(), createStoreLR(), earlyExpandDIVFIX(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), foldBitcastedFPLogic(), foldExtendedSignBitTest(), FoldIntToFPToInt(), fp16SrcZerosHighBits(), GeneratePerfectShuffle(), getBufferOffsetForMMO(), getCodeAddrSpace(), getContiguousRangeOfSetBits(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedMaskedLoad(), llvm::SelectionDAG::getIndexedMaskedStore(), llvm::SelectionDAG::getIndexedStore(), getLoadExtOrTrunc(), getNormalLoadInput(), GetPromotionOpcode(), getReductionSDNode(), getScatterNode(), getShiftAmountTyForConstant(), getSPDenormModeValue(), getVectorCompareInfo(), gwsIntrinToOpcode(), llvm::SITargetLowering::isMemOpHasNoClobberedMemOperand(), llvm::SITargetLowering::isMemOpUniform(), llvm::AVR::isProgramMemoryAccess(), isVectorElementSwap(), isWordAligned(), lowerAtomicArith(), lowerFP_TO_SINT_STORE(), LowerINTRINSIC_W_CHAIN(), LowerMLOAD(), LowerMSTORE(), llvm::NVPTXTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerPredicateStore(), lowerShuffleAsBroadcast(), LowerSTORE(), LowerStore(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), mayUseP9Setb(), MergeInputChains(), numVectorEltsOrZero(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformTruncatingStoreCombine(), PerformVDUPCombine(), PerformVMOVRRDCombine(), pickOpcodeForVT(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), ReplaceCMP_SWAP_128Results(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::SparcTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::AMDGPUTargetLowering::shouldReduceLoadWidth(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), SkipLoadExtensionForVMULL(), splitStores(), splitStoreSplat(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), stripTruncAndExt(), truncateScalarIntegerArg(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), tryToFoldExtOfMaskedLoad(), widenCtPop(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getMemoryVT()
EVT llvm::MemSDNode::getMemoryVT () const inline
Return the type of the in-memory value.
Definition at line 1363 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), adjustLoadValueTypeImpl(), allUsesTruncate(), llvm::AVRDAGToDAGISel::select< ISD::LOAD >(), callingConvSupported(), chainLoadsAndStoresForMemcpy(), checkValueWidth(), CollectOpsToWiden(), combineLoad(), combineMaskedLoadConstantMask(), combineMaskedStore(), combineShiftAnd1ToBitTest(), combineStore(), combineTargetShuffle(), CombineVLDDUP(), llvm::SelectionDAG::computeKnownBits(), ConstantAddressBlock(), createLoadLR(), llvm::createR600ISelDag(), createStoreLR(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), earlyExpandDIVFIX(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), findConsecutiveLoad(), foldExtendedSignBitTest(), fp16SrcZerosHighBits(), GeneratePerfectShuffle(), getAL(), getBufferOffsetForMMO(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedMaskedLoad(), llvm::SelectionDAG::getIndexedMaskedStore(), llvm::SelectionDAG::getIndexedStore(), getLoadExtOrTrunc(), getNormalLoadInput(), getParamsForOneTrueMaskedElt(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), getReductionSDNode(), getScatterNode(), getShiftAmountTyForConstant(), getSPDenormModeValue(), getVectorCompareInfo(), isOpcWithIntImmediate(), isValidIndexedLoad(), isVectorElementSwap(), isWordAligned(), LowerINTRINSIC_W_CHAIN(), llvm::MSP430TargetLowering::LowerJumpTable(), llvm::MipsTargetLowering::lowerLOAD(), LowerLOAD(), LowerMLOAD(), LowerMSTORE(), llvm::NVPTXTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerStore(), llvm::MipsTargetLowering::lowerSTORE(), LowerSTORE(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), mayUseP9Setb(), MergeInputChains(), numVectorEltsOrZero(), PerformANDCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformTruncatingStoreCombine(), PerformVDUPCombine(), pickOpcodeForVT(), ReorganizeVector(), ReplaceCMP_SWAP_128Results(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::SparcTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), selectI64Imm(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::AArch64TargetLowering::shouldReduceLoadWidth(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), stripTruncAndExt(), truncateScalarIntegerArg(), tryToFoldExtOfExtload(), tryToFoldExtOfMaskedLoad(), usePartialVectorLoads(), widenCtPop(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getOrdering()
AtomicOrdering llvm::MemSDNode::getOrdering () const inline
Return the atomic ordering requirements for this memory operation.
For cmpxchg atomic operations, return the atomic ordering requirements when store occurs.
Definition at line 1349 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getOrdering().
Referenced by lowerAtomicArith(), and pickOpcodeForVT().
getOriginalAlignment()
unsigned llvm::MemSDNode::getOriginalAlignment () const inline
Returns alignment and volatility of the memory access.
Definition at line 1303 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getBaseAlignment().
Referenced by PerformSplittingToNarrowingStores(), and PerformSplittingToWideningLoad().
getPointerInfo()
const MachinePointerInfo& llvm::MemSDNode::getPointerInfo () const inline
Definition at line 1369 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getPointerInfo().
Referenced by AddNodeIDCustom(), combineBVOfConsecutiveLoads(), combineLoad(), combineShuffle(), combineStore(), ConstantAddressBlock(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), ExtendUsesToFormExtLoad(), foldBitcastedFPLogic(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), getLoadExtOrTrunc(), GetPromotionOpcode(), getVectorCompareInfo(), isDispSafeForFrameIndex(), isWordAligned(), LowerF128Load(), lowerFP_TO_SINT_STORE(), LowerSTORE(), LowerStore(), numVectorEltsOrZero(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), PerformSTORECombine(), PerformTruncatingStoreCombine(), PerformVMOVRRDCombine(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), llvm::SparcTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), SkipLoadExtensionForVMULL(), splitStores(), splitStoreSplat(), splitVectorStore(), stripTruncAndExt(), truncateScalarIntegerArg(), and widenCtPop().
getRanges()
const MDNode* llvm::MemSDNode::getRanges () const inline
Returns the Ranges that describes the dereference.
Definition at line 1341 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getRanges().
Referenced by llvm::SelectionDAG::computeKnownBits(), and truncateScalarIntegerArg().
getRawSubclassData()
unsigned llvm::MemSDNode::getRawSubclassData () const inline
Return the SubclassData value, without HasDebugValue.
This contains an encoding of the volatile flag, as well as bits used by subclasses. This function should only be used to compute a FoldingSetNodeID value. The HasDebugValue bit is masked out because CSE map needs to match nodes with debug info with nodes without debug info. Same is about isDivergent bit.
Definition at line 1316 of file SelectionDAGNodes.h.
References llvm::Data.
Referenced by AddNodeIDCustom(), and llvm::SelectionDAG::getIndexedStore().
getSrcValueOffset()
int64_t llvm::MemSDNode::getSrcValueOffset () const inline
Definition at line 1335 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getOffset().
Referenced by numVectorEltsOrZero(), and ShrinkLoadReplaceStoreWithStore().
getSyncScopeID()
SyncScope::ID llvm::MemSDNode::getSyncScopeID () const inline
Returns the synchronization scope ID for this memory operation.
Definition at line 1344 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getSyncScopeID().
Referenced by lowerAtomicArith().
isAtomic()
bool llvm::MemSDNode::isAtomic () const inline
Return true if the memory operation ordering is Unordered or higher.
Definition at line 1352 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::isAtomic().
Referenced by numVectorEltsOrZero(), and ShrinkLoadReplaceStoreWithStore().
isDereferenceable()
bool llvm::MemSDNode::isDereferenceable () const inline
Definition at line 1331 of file SelectionDAGNodes.h.
Referenced by truncateScalarIntegerArg().
isInvariant()
bool llvm::MemSDNode::isInvariant () const inline
Definition at line 1332 of file SelectionDAGNodes.h.
Referenced by canLowerToLDG(), getLoadExtOrTrunc(), llvm::AMDGPUTargetLowering::shouldReduceLoadWidth(), and truncateScalarIntegerArg().
isNonTemporal()
bool llvm::MemSDNode::isNonTemporal () const inline
Definition at line 1330 of file SelectionDAGNodes.h.
Referenced by combineLoad(), combineStore(), isFusableLoadOpStorePattern(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), ShrinkLoadReplaceStoreWithStore(), and truncateScalarIntegerArg().
isSimple()
bool llvm::MemSDNode::isSimple () const inline
Returns true if the memory operation is neither atomic or volatile.
Definition at line 1360 of file SelectionDAGNodes.h.
References isAtomic(), and isVolatile().
Referenced by llvm::SelectionDAG::areNonVolatileConsecutiveLoads(), combineShiftAnd1ToBitTest(), combineShuffle(), combineSIntToFP(), combineStore(), ExtendUsesToFormExtLoad(), hasSingleUsesFromRoot(), isCalleeLoad(), isSlicingProfitable(), numVectorEltsOrZero(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), scalarizeBinOpOfSplats(), scalarizeExtractedBinop(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), simplifyDivRem(), splitVectorStore(), tryToFoldExtOfExtload(), and widenCtPop().
isUnordered()
bool llvm::MemSDNode::isUnordered () const inline
Returns true if the memory operation doesn't imply any ordering constraints on surrounding memory operations beyond the normal memory aliasing rules.
Definition at line 1357 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::isUnordered().
isVolatile()
bool llvm::MemSDNode::isVolatile () const inline
Definition at line 1329 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::areNonVolatileConsecutiveLoads(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), getLoadExtOrTrunc(), isWordAligned(), LowerTruncateVectorStore(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), pickOpcodeForVT(), ReplaceCMP_SWAP_128Results(), splitStores(), and truncateScalarIntegerArg().
readMem()
bool llvm::MemSDNode::readMem () const inline
Definition at line 1299 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::isLoad().
Referenced by pickOpcodeForVT().
refineAlignment()
void llvm::MemSDNode::refineAlignment (const MachineMemOperand * NewMMO) inline
Update this MemSDNode's MachineMemOperand information to reflect the alignment of NewMMO, if it has a greater alignment.
This must only be used when the new alignment applies to all users of this MachineMemOperand.
Definition at line 1382 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::refineAlignment().
writeMem()
bool llvm::MemSDNode::writeMem () const inline
Definition at line 1300 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::isStore().
Referenced by pickOpcodeForVT().
Member Data Documentation
MMO
MachineMemOperand* llvm::MemSDNode::MMO protected
Memory reference information.
Definition at line 1293 of file SelectionDAGNodes.h.
Referenced by MemSDNode().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAGNodes.h
lib/CodeGen/SelectionDAG/SelectionDAG.cpp