LLVM: llvm::LibCallSimplifier Class Reference
llvm::LibCallSimplifier Class Reference
LibCallSimplifier - This class implements a collection of optimizations that replace well formed calls to library functions with a more optimal form.
#include "llvm/Transforms/Utils/SimplifyLibCalls.h"
Public Member Functions
LibCallSimplifier (const DataLayout &DL, const TargetLibraryInfo *TLI, OptimizationRemarkEmitter &ORE, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI, function_ref< void(Instruction *, Value *)> Replacer=&replaceAllUsesWithDefault, function_ref< void(Instruction *)> Eraser=&eraseFromParentDefault)
Value * optimizeCall (CallInst *CI)
optimizeCall - Take the given call instruction and return a more optimal value to replace the instruction with or 0 if a more optimal form can't be found.
Detailed Description
LibCallSimplifier - This class implements a collection of optimizations that replace well formed calls to library functions with a more optimal form.
For example, replacing 'printf("Hello!")' with 'puts("Hello!")'.
Definition at line 100 of file SimplifyLibCalls.h.
Constructor & Destructor Documentation
LibCallSimplifier()
LibCallSimplifier::LibCallSimplifier (const DataLayout & DL, const TargetLibraryInfo * TLI, OptimizationRemarkEmitter & ORE, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI, function_ref< void(Instruction *, Value *)> Replacer = &replaceAllUsesWithDefault, function_ref< void(Instruction *)> Eraser = &eraseFromParentDefault)
Definition at line 3185 of file SimplifyLibCalls.cpp.
References annotateDereferenceableBytes(), llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), B, llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::dyn_cast(), llvm::emitMemCCpy(), llvm::emitMemCpyChk(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::emitStpCpy(), llvm::emitStpNCpy(), llvm::emitStrCat(), llvm::emitStrCpy(), llvm::emitStrLCat(), llvm::emitStrLCpy(), llvm::emitStrLen(), llvm::emitStrNCat(), llvm::emitStrNCpy(), llvm::emitVSNPrintf(), llvm::emitVSPrintf(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getAttributes(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::IRBuilderBase::getInt8Ty(), llvm::DataLayout::getIntPtrType(), llvm::Instruction::getModule(), llvm::GetStringLength(), I, llvm::ConstantInt::isZero(), llvm::None, llvm::Align::None(), llvm::MipsISD::Ret, and llvm::CallBase::setAttributes().
Member Function Documentation
optimizeCall()
Value * LibCallSimplifier::optimizeCall (CallInst * CI)
optimizeCall - Take the given call instruction and return a more optimal value to replace the instruction with or 0 if a more optimal form can't be found.
Note that the returned value may be equal to the instruction being optimized. In this case all other instructions that use the given instruction were modified and the given instruction is dead. The call must not be an indirect call.
Definition at line 3047 of file SimplifyLibCalls.cpp.
References llvm::dyn_cast(), EnableUnsafeFPShrink, llvm::CallBase::getCalledFunction(), llvm::CallBase::getOperandBundlesAsDefs(), ignoreCallingConv(), isCallingConvCCompatible(), llvm::Instruction::isFast(), llvm::CallBase::isNoBuiltin(), and llvm::log2().
Referenced by isSafeToEliminateVarargsCast().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/SimplifyLibCalls.h
lib/Transforms/Utils/SimplifyLibCalls.cpp