LLVM: llvm::InlineFunctionInfo Class Reference
llvm::InlineFunctionInfo Class Reference
This class captures the data input to the InlineFunction call, and records the auxiliary results produced by it.
#include "llvm/Transforms/Utils/Cloning.h"
Public Member Functions
InlineFunctionInfo (CallGraph *cg=nullptr, std::function< AssumptionCache &(Function &)> *GetAssumptionCache=nullptr, ProfileSummaryInfo *PSI=nullptr, BlockFrequencyInfo *CallerBFI=nullptr, BlockFrequencyInfo *CalleeBFI=nullptr)
void reset ()
Public Attributes
CallGraph * CG
If non-null, InlineFunction will update the callgraph to reflect the changes it makes.
std::function< AssumptionCache &(Function &)> * GetAssumptionCache
ProfileSummaryInfo * PSI
BlockFrequencyInfo * CallerBFI
BlockFrequencyInfo * CalleeBFI
SmallVector< AllocaInst *, 4 > StaticAllocas
InlineFunction fills this in with all static allocas that get copied into the caller.
SmallVector< WeakTrackingVH, 8 > InlinedCalls
InlineFunction fills this in with callsites that were inlined from the callee.
SmallVector< CallSite, 8 > InlinedCallSites
All of the new call sites inlined into the caller.
Detailed Description
This class captures the data input to the InlineFunction call, and records the auxiliary results produced by it.
Definition at line 173 of file Cloning.h.
Constructor & Destructor Documentation
InlineFunctionInfo()
llvm::InlineFunctionInfo::InlineFunctionInfo (CallGraph * cg = nullptr, std::function< AssumptionCache &(Function &)> * GetAssumptionCache = nullptr, ProfileSummaryInfo * PSI = nullptr, BlockFrequencyInfo * CallerBFI = nullptr, BlockFrequencyInfo * CalleeBFI = nullptr) inline explicit
Definition at line 175 of file Cloning.h.
Member Function Documentation
reset()
void llvm::InlineFunctionInfo::reset () inline
Definition at line 206 of file Cloning.h.
References Callee, llvm::SmallVectorImpl< T >::clear(), llvm::cloneLoopWithPreheader(), llvm::DuplicateInstructionsInSplitBetween(), llvm::InlineFunction(), llvm::remapInstructionsInBlocks(), and llvm::updateProfileCallee().
Referenced by llvm::InlineFunction().
Member Data Documentation
CalleeBFI
BlockFrequencyInfo * llvm::InlineFunctionInfo::CalleeBFI
Definition at line 189 of file Cloning.h.
Referenced by llvm::InlineFunction().
CallerBFI
BlockFrequencyInfo* llvm::InlineFunctionInfo::CallerBFI
Definition at line 189 of file Cloning.h.
Referenced by llvm::InlineFunction().
CG
CallGraph* llvm::InlineFunctionInfo::CG
If non-null, InlineFunction will update the callgraph to reflect the changes it makes.
Definition at line 186 of file Cloning.h.
Referenced by llvm::InlineFunction(), and UpdateCallGraphAfterInlining().
GetAssumptionCache
std::function<AssumptionCache &(Function &)>* llvm::InlineFunctionInfo::GetAssumptionCache
Definition at line 187 of file Cloning.h.
Referenced by AddAlignmentAssumptions(), HandleByValArgument(), and llvm::InlineFunction().
InlinedCalls
SmallVector<WeakTrackingVH, 8> llvm::InlineFunctionInfo::InlinedCalls
InlineFunction fills this in with callsites that were inlined from the callee.
This is only filled in if CG is non-null.
Definition at line 197 of file Cloning.h.
Referenced by UpdateCallGraphAfterInlining().
InlinedCallSites
SmallVector<CallSite, 8> llvm::InlineFunctionInfo::InlinedCallSites
All of the new call sites inlined into the caller.
'InlineFunction' fills this in by scanning the inlined instructions, and only if CG is null. If CG is non-null, instead the value handle InlinedCalls above is used.
Definition at line 204 of file Cloning.h.
Referenced by llvm::InlineFunction(), and llvm::InlinerPass::run().
PSI
ProfileSummaryInfo* llvm::InlineFunctionInfo::PSI
Definition at line 188 of file Cloning.h.
Referenced by llvm::InlineFunction().
StaticAllocas
SmallVector<AllocaInst *, 4> llvm::InlineFunctionInfo::StaticAllocas
InlineFunction fills this in with all static allocas that get copied into the caller.
Definition at line 193 of file Cloning.h.
Referenced by HandleByValArgument(), llvm::InlineFunction(), and mergeInlinedArrayAllocas().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Utils/Cloning.h