LLVM: llvm::LiveIntervalUnion::Query Class Reference
llvm::LiveIntervalUnion::Query Class Reference
Query interferences between a single live virtual register and a live interval union.
#include "llvm/CodeGen/LiveIntervalUnion.h"
Public Member Functions
Query ()=default
Query (const LiveRange &LR, const LiveIntervalUnion &LIU)
Query (const Query &)=delete
Query & operator= (const Query &)=delete
void init (unsigned NewUserTag, const LiveRange &NewLR, const LiveIntervalUnion &NewLiveUnion)
bool checkInterference ()
unsigned collectInterferingVRegs (unsigned MaxInterferingRegs=std::numeric_limits< unsigned >::max())
bool isSeenInterference (LiveInterval *VirtReg) const
NDEBUG.
bool seenAllInterferences () const
const SmallVectorImpl< LiveInterval * > & interferingVRegs () const
Detailed Description
Query interferences between a single live virtual register and a live interval union.
Definition at line 109 of file LiveIntervalUnion.h.
Constructor & Destructor Documentation
Query() [1/3]
llvm::LiveIntervalUnion::Query::Query () default
Referenced by Query().
Query() [2/3]
llvm::LiveIntervalUnion::Query::Query (const LiveRange & LR, const LiveIntervalUnion & LIU) inline
Definition at line 133 of file LiveIntervalUnion.h.
References operator=(), and Query().
Query() [3/3]
llvm::LiveIntervalUnion::Query::Query (const Query &) delete
Member Function Documentation
checkInterference()
bool llvm::LiveIntervalUnion::Query::checkInterference () inline
Definition at line 149 of file LiveIntervalUnion.h.
References collectInterferingVRegs(), isSeenInterference(), and llvm::max().
Referenced by llvm::LiveRegMatrix::checkInterference().
collectInterferingVRegs()
unsigned LiveIntervalUnion::Query::collectInterferingVRegs (unsigned MaxInterferingRegs = std::numeric_limits<unsigned>::max())
Definition at line 118 of file LiveIntervalUnion.cpp.
References assert(), and llvm::LiveRange::size().
Referenced by checkInterference(), llvm::createGreedyRegisterAllocator(), hasTiedDef(), and isSeenInterference().
init()
void llvm::LiveIntervalUnion::Query::init (unsigned NewUserTag, const LiveRange & NewLR, const LiveIntervalUnion & NewLiveUnion) inline
Definition at line 138 of file LiveIntervalUnion.h.
References llvm::LiveIntervalUnion::changedSince().
Referenced by llvm::LiveRegMatrix::query(), and llvm::LiveIntervalUnion::Array::~Array().
interferingVRegs()
const SmallVectorImpl<LiveInterval*>& llvm::LiveIntervalUnion::Query::interferingVRegs () const inline
Definition at line 163 of file LiveIntervalUnion.h.
Referenced by llvm::createGreedyRegisterAllocator(), and hasTiedDef().
isSeenInterference()
bool LiveIntervalUnion::Query::isSeenInterference (LiveInterval * VirtReg) const
NDEBUG.
Definition at line 104 of file LiveIntervalUnion.cpp.
References collectInterferingVRegs(), and llvm::is_contained().
Referenced by checkInterference().
operator=()
Query& llvm::LiveIntervalUnion::Query::operator= (const Query &) delete
Referenced by Query().
seenAllInterferences()
bool llvm::LiveIntervalUnion::Query::seenAllInterferences () const inline
Definition at line 160 of file LiveIntervalUnion.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveIntervalUnion.h
lib/CodeGen/LiveIntervalUnion.cpp