LLVM: llvm::VPWidenRecipe Class Reference
llvm::VPWidenRecipe Class Reference
VPWidenRecipe is a recipe for producing a copy of vector type for each Instruction in its ingredients independently, in order.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenRecipe (Instruction *I)
~VPWidenRecipe () override=default
void execute (VPTransformState &State) override
Produce widened copies of all Ingredients.
bool appendInstruction (Instruction *Instr)
Augment the recipe to include Instr, if it lies at its End.
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenGEPSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Detailed Description
VPWidenRecipe is a recipe for producing a copy of vector type for each Instruction in its ingredients independently, in order.
This recipe covers most of the traditional vectorization cases where each ingredient transforms into a vectorized version of itself.
Definition at line 728 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenRecipe()
llvm::VPWidenRecipe::VPWidenRecipe (Instruction * I) inline
Definition at line 735 of file VPlan.h.
References llvm::ilist_node_impl< OptionsT >::getIterator().
~VPWidenRecipe()
llvm::VPWidenRecipe::~VPWidenRecipe () override default
Member Function Documentation
appendInstruction()
bool llvm::VPWidenRecipe::appendInstruction (Instruction * Instr) inline
Augment the recipe to include Instr, if it lies at its End.
Definition at line 751 of file VPlan.h.
References llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::RISCVFenceField::O, and print().
classof()
static bool llvm::VPWidenRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 743 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID().
execute()
void VPWidenRecipe::execute (VPTransformState & State) override virtual
Produce widened copies of all Ingredients.
Implements llvm::VPRecipeBase.
Definition at line 7355 of file LoopVectorize.cpp.
References llvm::make_range().
print()
void VPWidenRecipe::print (raw_ostream & O, const Twine & Indent) const override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 673 of file VPlan.cpp.
References llvm::make_range().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp