LLVM: llvm::AnalysisUsage Class Reference
llvm::AnalysisUsage Class Reference
Represent the analysis usage information of a pass.
#include "llvm/PassAnalysisSupport.h"
Public Types
using VectorType = SmallVectorImpl< AnalysisID >
Public Member Functions
AnalysisUsage ()=default
AnalysisUsage & addPreserved (StringRef Arg)
Add the Pass with the specified argument string to the set of analyses preserved by this pass.
void setPreservesAll ()
Set by analyses that do not transform their input at all.
bool getPreservesAll () const
Determine whether a pass said it does not transform its input at all.
void setPreservesCFG ()
This function should be called by the pass, iff they do not:
const VectorType & getRequiredSet () const
const VectorType & getRequiredTransitiveSet () const
const VectorType & getPreservedSet () const
const VectorType & getUsedSet () const
AnalysisUsage & addRequiredID (const void *ID)
AnalysisUsage & addRequiredID (char &ID)
template<class PassClass >
AnalysisUsage & addRequired ()
AnalysisUsage & addRequiredTransitiveID (char &ID)
template<class PassClass >
AnalysisUsage & addRequiredTransitive ()
AnalysisUsage & addPreservedID (const void *ID)
AnalysisUsage & addPreservedID (char &ID)
template<class PassClass >
AnalysisUsage & addPreserved ()
Add the specified Pass class to the set of analyses preserved by this pass.
AnalysisUsage & addUsedIfAvailableID (const void *ID)
AnalysisUsage & addUsedIfAvailableID (char &ID)
template<class PassClass >
AnalysisUsage & addUsedIfAvailable ()
Add the specified Pass class to the set of analyses used by this pass.
Detailed Description
Represent the analysis usage information of a pass.
This tracks analyses that the pass REQUIRES (must be available when the pass runs), REQUIRES TRANSITIVE (must be available throughout the lifetime of the pass), and analyses that the pass PRESERVES (the pass does not invalidate the results of these analyses). This information is provided by a pass to the Pass infrastructure through the getAnalysisUsage virtual function.
Definition at line 42 of file PassAnalysisSupport.h.
Member Typedef Documentation
VectorType
using llvm::AnalysisUsage::VectorType = SmallVectorImpl<AnalysisID>
Definition at line 44 of file PassAnalysisSupport.h.
Constructor & Destructor Documentation
AnalysisUsage()
llvm::AnalysisUsage::AnalysisUsage () default
Member Function Documentation
addPreserved() [1/2]
template<class PassClass > AnalysisUsage& llvm::AnalysisUsage::addPreserved () inline
Add the specified Pass class to the set of analyses preserved by this pass.
Definition at line 88 of file PassAnalysisSupport.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by addUsedIfAvailable(), llvm::LoopVersioning::annotateInstWithNoAlias(), collectSupportedLoops(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::createAArch64ConditionalCompares(), llvm::createAArch64ConditionOptimizerPass(), llvm::createGreedyRegisterAllocator(), createHWLoopAnalysis(), llvm::createPrologEpilogInserterPass(), llvm::MachineModuleInfo::deleteMachineFunctionFor(), doCallSiteSplitting(), llvm::GVNExpression::Expression::dump(), eliminateLoadsAcrossLoops(), eliminateTailRecursion(), formLCSSAOnAllLoops(), llvm::InstructionSelect::getAnalysisUsage(), llvm::InjectTLIMappingsLegacy::getAnalysisUsage(), llvm::MipsDAGToDAGISel::getAnalysisUsage(), llvm::Legalizer::getAnalysisUsage(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::InstructionCombiningPass::getAnalysisUsage(), llvm::SelectionDAGISel::getAnalysisUsage(), llvm::CallGraphSCCPass::getAnalysisUsage(), llvm::MachinePipeliner::getAnalysisUsage(), llvm::StackProtector::getAnalysisUsage(), llvm::LiveIntervals::getAnalysisUsage(), llvm::GVNHoistLegacyPass::getAnalysisUsage(), llvm::gvn::GVNLegacyPass::getAnalysisUsage(), llvm::sroa::SROALegacyPass::getAnalysisUsage(), llvm::getLoopAnalysisUsage(), llvm::getSelectionDAGFallbackAnalysisUsage(), INITIALIZE_PASS_BEGIN(), llvm::CoalescerPair::isCoalescable(), isDebug(), isImplicitlyDef(), mayUsePostIncMode(), optimizeDivRem(), parseCHRFilterFiles(), patchAndReplaceAllUsesWith(), llvm::SinkingPass::run(), llvm::LoopRotatePass::run(), llvm::BDCEPass::run(), llvm::LoopSimplifyCFGPass::run(), llvm::GuardWideningPass::run(), llvm::DSEPass::run(), llvm::UnreachableBlockElimPass::run(), llvm::ADCEPass::run(), llvm::EarlyCSEPass::run(), llvm::SCCPPass::run(), llvm::SimplifyCFGPass::run(), llvm::InternalizePass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::ReassociatePass::run(), runImpl(), runOnFunction(), llvm::simplifyLoop(), simplifyLoopInst(), and llvm::AntiDepBreaker::~AntiDepBreaker().
addPreserved() [2/2]
AnalysisUsage & AnalysisUsage::addPreserved (StringRef Arg)
Add the Pass with the specified argument string to the set of analyses preserved by this pass.
If no such Pass exists, do nothing. This can be useful when a pass is trivially preserved, but may not be linked in. Be careful about spelling!
Definition at line 262 of file Pass.cpp.
References llvm::PassInfo::getTypeInfo(), and llvm::Pass::lookupPassInfo().
addPreservedID() [1/2]
AnalysisUsage& llvm::AnalysisUsage::addPreservedID (const void * ID) inline
Add the specified ID to the set of analyses preserved by this pass.
Definition at line 78 of file PassAnalysisSupport.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by formLCSSAOnAllLoops(), llvm::UnifyFunctionExitNodes::getAnalysisUsage(), llvm::LiveIntervals::getAnalysisUsage(), llvm::gvn::GVNLegacyPass::getAnalysisUsage(), llvm::getLoopAnalysisUsage(), llvm::CoalescerPair::isCoalescable(), mayUsePostIncMode(), and llvm::simplifyLoop().
addPreservedID() [2/2]
AnalysisUsage& llvm::AnalysisUsage::addPreservedID (char & ID) inline
Definition at line 82 of file PassAnalysisSupport.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
addRequired()
template<class PassClass > AnalysisUsage& llvm::AnalysisUsage::addRequired () inline
Definition at line 65 of file PassAnalysisSupport.h.
References addRequiredID(), and addRequiredTransitiveID().
Referenced by llvm::AMDGPULibCalls::AMDGPULibCalls(), llvm::LoopVersioning::annotateInstWithNoAlias(), collectSupportedLoops(), computeBranchTargetAndInversion(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::createAArch64ConditionalCompares(), llvm::createAArch64ConditionOptimizerPass(), llvm::createAMDGPUFunctionInliningPass(), llvm::createDwarfEHPass(), llvm::createFalkorMarkStridedAccessesPass(), llvm::createFunctionInliningPass(), llvm::createGCInfoPrinter(), llvm::createGreedyRegisterAllocator(), createHWLoopAnalysis(), llvm::createObjCARCOptPass(), llvm::createPrologEpilogInserterPass(), llvm::createSystemZLDCleanupPass(), llvm::createX86FlagsCopyLoweringPass(), llvm::MachineModuleInfo::deleteMachineFunctionFor(), doCallSiteSplitting(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::AliasSetTracker::dump(), eliminateLoadsAcrossLoops(), eliminateTailRecursion(), llvm::LazyValueInfo::enableDT(), formLCSSAOnAllLoops(), llvm::getAAResultsAnalysisUsage(), llvm::InjectTLIMappingsLegacy::getAnalysisUsage(), llvm::InstructionSelect::getAnalysisUsage(), llvm::LegacyDivergenceAnalysis::getAnalysisUsage(), llvm::LegacyInlinerBase::getAnalysisUsage(), llvm::MachineBlockFrequencyInfo::getAnalysisUsage(), llvm::Legalizer::getAnalysisUsage(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::BreakFalseDeps::getAnalysisUsage(), llvm::InstructionCombiningPass::getAnalysisUsage(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::SCEVAAWrapperPass::getAnalysisUsage(), llvm::ModuleSummaryIndexWrapperPass::getAnalysisUsage(), llvm::LazyMachineBlockFrequencyInfoPass::getAnalysisUsage(), llvm::StackSafetyInfoWrapperPass::getAnalysisUsage(), llvm::SelectionDAGISel::getAnalysisUsage(), llvm::CallGraphSCCPass::getAnalysisUsage(), llvm::Localizer::getAnalysisUsage(), llvm::MachinePipeliner::getAnalysisUsage(), llvm::DemandedBitsWrapperPass::getAnalysisUsage(), llvm::LazyBranchProbabilityInfoPass::getAnalysisUsage(), llvm::MachineRegionInfoPass::getAnalysisUsage(), llvm::MachineDominanceFrontier::getAnalysisUsage(), llvm::MachineTraceMetrics::getAnalysisUsage(), llvm::RGPassManager::getAnalysisUsage(), llvm::LPPassManager::getAnalysisUsage(), llvm::StackProtector::getAnalysisUsage(), llvm::StackSafetyGlobalInfoWrapperPass::getAnalysisUsage(), llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::LazyBlockFrequencyInfoPass::getAnalysisUsage(), llvm::CFLAndersAAWrapperPass::getAnalysisUsage(), llvm::ExecutionDomainFix::getAnalysisUsage(), llvm::CFLSteensAAWrapperPass::getAnalysisUsage(), llvm::WebAssemblyExceptionInfo::getAnalysisUsage(), llvm::DOTGraphTraitsModuleViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::MachineLoopInfo::getAnalysisUsage(), llvm::BlockFrequencyInfoWrapperPass::getAnalysisUsage(), llvm::GlobalsAAWrapperPass::getAnalysisUsage(), llvm::LazyValueInfoWrapperPass::getAnalysisUsage(), llvm::DominanceFrontierWrapperPass::getAnalysisUsage(), llvm::DOTGraphTraitsModulePrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::IVUsersWrapperPass::getAnalysisUsage(), llvm::MachineOptimizationRemarkEmitterPass::getAnalysisUsage(), llvm::BranchProbabilityInfoWrapperPass::getAnalysisUsage(), llvm::BasicAAWrapperPass::getAnalysisUsage(), llvm::PredicateInfoPrinterLegacyPass::getAnalysisUsage(), llvm::LiveIntervals::getAnalysisUsage(), llvm::NVPTXAsmPrinter::getAnalysisUsage(), llvm::AsmPrinter::getAnalysisUsage(), llvm::AAEvalLegacyPass::getAnalysisUsage(), llvm::MemoryDependenceWrapperPass::getAnalysisUsage(), llvm::IRTranslator::getAnalysisUsage(), llvm::RegBankSelect::getAnalysisUsage(), llvm::LoopAccessLegacyAnalysis::getAnalysisUsage(), llvm::MemorySSAPrinterLegacyPass::getAnalysisUsage(), llvm::RegionInfoPass::getAnalysisUsage(), llvm::GVNHoistLegacyPass::getAnalysisUsage(), llvm::AAResultsWrapperPass::getAnalysisUsage(), llvm::gvn::GVNLegacyPass::getAnalysisUsage(), llvm::sroa::SROALegacyPass::getAnalysisUsage(), GetCtorAndDtorPriority(), llvm::GCOVOptions::getDefault(), getInductionVariable(), llvm::LazyBlockFrequencyInfoPass::getLazyBFIAnalysisUsage(), llvm::LazyBranchProbabilityInfoPass::getLazyBPIAnalysisUsage(), llvm::getLoopAnalysisUsage(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), llvm::CoalescerPair::isCoalescable(), isDebug(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), isImplicitlyDef(), IsInRanges(), isLEA(), mayUsePostIncMode(), optimizeDivRem(), parseCHRFilterFiles(), patchAndReplaceAllUsesWith(), replaceDevirtTrigger(), llvm::BoundsCheckingPass::run(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::SinkingPass::run(), llvm::PromotePass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::LoopRotatePass::run(), llvm::BDCEPass::run(), llvm::InferFunctionAttrsPass::run(), llvm::GlobalOptPass::run(), llvm::LoopSimplifyCFGPass::run(), llvm::WarnMissedTransformationsPass::run(), llvm::GuardWideningPass::run(), llvm::ArgumentPromotionPass::run(), llvm::DSEPass::run(), llvm::RewriteStatepointsForGC::run(), llvm::ADCEPass::run(), llvm::IPSCCPPass::run(), llvm::EarlyCSEPass::run(), llvm::LoopSinkPass::run(), llvm::SCCPPass::run(), llvm::SimplifyCFGPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::BitcodeWriterPass::run(), llvm::AttributorPass::run(), runImpl(), llvm::simplifyLoop(), simplifyLoopInst(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander(), and llvm::AntiDepBreaker::~AntiDepBreaker().
addRequiredID() [1/2]
AnalysisUsage & AnalysisUsage::addRequiredID (const void * ID)
Add the specified ID to the required set of the usage info for a pass.
Definition at line 269 of file Pass.cpp.
References llvm::cl::Required.
Referenced by addRequired(), eliminateLoadsAcrossLoops(), llvm::getLoopAnalysisUsage(), mayUsePostIncMode(), and llvm::SafepointIRVerifierPass::run().
addRequiredID() [2/2]
AnalysisUsage & AnalysisUsage::addRequiredID (char & ID)
Definition at line 274 of file Pass.cpp.
References llvm::cl::Required.
addRequiredTransitive()
template<class PassClass > AnalysisUsage& llvm::AnalysisUsage::addRequiredTransitive () inline
Definition at line 71 of file PassAnalysisSupport.h.
References addRequiredTransitiveID().
Referenced by llvm::CallGraphWrapperPass::dump(), llvm::PredicateInfoPrinterLegacyPass::getAnalysisUsage(), llvm::LiveIntervals::getAnalysisUsage(), llvm::MemoryDependenceWrapperPass::getAnalysisUsage(), llvm::RegionInfoPass::getAnalysisUsage(), llvm::DependenceAnalysisWrapperPass::getAnalysisUsage(), llvm::MemorySSAWrapperPass::getAnalysisUsage(), llvm::LoopInfoWrapperPass::getAnalysisUsage(), llvm::ScalarEvolutionWrapperPass::getAnalysisUsage(), and llvm::LiveRegMatrix::LiveRegMatrix().
addRequiredTransitiveID()
AnalysisUsage & AnalysisUsage::addRequiredTransitiveID (char & ID)
Definition at line 279 of file Pass.cpp.
References llvm::cl::Required.
Referenced by addRequired(), addRequiredTransitive(), and llvm::LiveIntervals::getAnalysisUsage().
addUsedIfAvailable()
template<class PassClass > AnalysisUsage& llvm::AnalysisUsage::addUsedIfAvailable () inline
Add the specified Pass class to the set of analyses used by this pass.
Definition at line 107 of file PassAnalysisSupport.h.
References addPreserved(), Arg, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::getAAResultsAnalysisUsage(), llvm::BasicAAWrapperPass::getAnalysisUsage(), and llvm::AAResultsWrapperPass::getAnalysisUsage().
addUsedIfAvailableID() [1/2]
AnalysisUsage& llvm::AnalysisUsage::addUsedIfAvailableID (const void * ID) inline
Add the specified ID to the set of analyses used by this pass if they are available..
Definition at line 97 of file PassAnalysisSupport.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
addUsedIfAvailableID() [2/2]
AnalysisUsage& llvm::AnalysisUsage::addUsedIfAvailableID (char & ID) inline
Definition at line 101 of file PassAnalysisSupport.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
getPreservedSet()
const VectorType& llvm::AnalysisUsage::getPreservedSet () const inline
Definition at line 138 of file PassAnalysisSupport.h.
Referenced by llvm::PMDataManager::dumpPreservedSet(), llvm::PMDataManager::preserveHigherLevelAnalysis(), llvm::PMDataManager::removeNotPreservedAnalysis(), and llvm::PMDataManager::verifyPreservedAnalysis().
getPreservesAll()
bool llvm::AnalysisUsage::getPreservesAll () const inline
Determine whether a pass said it does not transform its input at all.
Definition at line 123 of file PassAnalysisSupport.h.
References setPreservesCFG().
Referenced by llvm::PMDataManager::preserveHigherLevelAnalysis(), and llvm::PMDataManager::removeNotPreservedAnalysis().
getRequiredSet()
const VectorType& llvm::AnalysisUsage::getRequiredSet () const inline
Definition at line 134 of file PassAnalysisSupport.h.
Referenced by llvm::PMDataManager::collectRequiredAndUsedAnalyses(), llvm::PMDataManager::dumpRequiredSet(), llvm::PMDataManager::initializeAnalysisImpl(), and llvm::PMTopLevelManager::schedulePass().
getRequiredTransitiveSet()
const VectorType& llvm::AnalysisUsage::getRequiredTransitiveSet () const inline
Definition at line 135 of file PassAnalysisSupport.h.
Referenced by llvm::PMDataManager::collectRequiredAndUsedAnalyses(), and llvm::PMTopLevelManager::setLastUser().
getUsedSet()
const VectorType& llvm::AnalysisUsage::getUsedSet () const inline
Definition at line 139 of file PassAnalysisSupport.h.
Referenced by llvm::PMDataManager::collectRequiredAndUsedAnalyses(), and llvm::PMDataManager::dumpUsedSet().
setPreservesAll()
void llvm::AnalysisUsage::setPreservesAll () inline
Set by analyses that do not transform their input at all.
Definition at line 120 of file PassAnalysisSupport.h.
Referenced by llvm::createCostModelAnalysisPass(), llvm::createGCInfoPrinter(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::CallGraphWrapperPass::dump(), llvm::AliasSetTracker::dump(), llvm::RGPassManager::dumpPassStructure(), llvm::legacy::FunctionPassManagerImpl::dumpPassStructure(), llvm::LazyValueInfo::enableDT(), llvm::LegacyDivergenceAnalysis::getAnalysisUsage(), llvm::AMDGPUPerfHintAnalysis::getAnalysisUsage(), llvm::MachineBranchProbabilityInfo::getAnalysisUsage(), llvm::MachineBlockFrequencyInfo::getAnalysisUsage(), llvm::BreakFalseDeps::getAnalysisUsage(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::SCEVAAWrapperPass::getAnalysisUsage(), llvm::LazyMachineBlockFrequencyInfoPass::getAnalysisUsage(), llvm::ModuleSummaryIndexWrapperPass::getAnalysisUsage(), llvm::StackSafetyInfoWrapperPass::getAnalysisUsage(), llvm::CallGraphSCCPass::getAnalysisUsage(), llvm::ScopedNoAliasAAWrapperPass::getAnalysisUsage(), llvm::VirtRegMap::getAnalysisUsage(), llvm::ReachingDefAnalysis::getAnalysisUsage(), llvm::IntervalPartition::getAnalysisUsage(), llvm::TypeBasedAAWrapperPass::getAnalysisUsage(), llvm::MachinePostDominatorTree::getAnalysisUsage(), llvm::PostDominatorTreeWrapperPass::getAnalysisUsage(), llvm::objcarc::ObjCARCAAWrapperPass::getAnalysisUsage(), llvm::DemandedBitsWrapperPass::getAnalysisUsage(), llvm::LazyBranchProbabilityInfoPass::getAnalysisUsage(), llvm::AMDGPUAAWrapperPass::getAnalysisUsage(), llvm::MachineRegionInfoPass::getAnalysisUsage(), llvm::MachineDominanceFrontier::getAnalysisUsage(), llvm::MachineTraceMetrics::getAnalysisUsage(), llvm::RGPassManager::getAnalysisUsage(), llvm::LPPassManager::getAnalysisUsage(), llvm::GISelKnownBitsAnalysis::getAnalysisUsage(), llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::LazyBlockFrequencyInfoPass::getAnalysisUsage(), llvm::CFLAndersAAWrapperPass::getAnalysisUsage(), llvm::DummyCGSCCPass::getAnalysisUsage(), llvm::ExecutionDomainFix::getAnalysisUsage(), llvm::CFLSteensAAWrapperPass::getAnalysisUsage(), llvm::WebAssemblyExceptionInfo::getAnalysisUsage(), llvm::DOTGraphTraitsModuleViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::MachineLoopInfo::getAnalysisUsage(), llvm::OptimizationRemarkEmitterWrapperPass::getAnalysisUsage(), llvm::BlockFrequencyInfoWrapperPass::getAnalysisUsage(), llvm::GlobalsAAWrapperPass::getAnalysisUsage(), llvm::PhiValuesWrapperPass::getAnalysisUsage(), llvm::LazyValueInfoWrapperPass::getAnalysisUsage(), llvm::AMDGPUArgumentUsageInfo::getAnalysisUsage(), llvm::LCSSAVerificationPass::getAnalysisUsage(), llvm::DominanceFrontierWrapperPass::getAnalysisUsage(), llvm::ProfileSummaryInfoWrapperPass::getAnalysisUsage(), llvm::DOTGraphTraitsModulePrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage(), llvm::IVUsersWrapperPass::getAnalysisUsage(), llvm::MachineOptimizationRemarkEmitterPass::getAnalysisUsage(), llvm::GISelCSEAnalysisWrapperPass::getAnalysisUsage(), llvm::BranchProbabilityInfoWrapperPass::getAnalysisUsage(), llvm::BasicAAWrapperPass::getAnalysisUsage(), llvm::DominatorTreeWrapperPass::getAnalysisUsage(), llvm::PredicateInfoPrinterLegacyPass::getAnalysisUsage(), llvm::AsmPrinter::getAnalysisUsage(), llvm::legacy::FunctionPassManagerImpl::getAnalysisUsage(), llvm::CallGraphWrapperPass::getAnalysisUsage(), llvm::AAEvalLegacyPass::getAnalysisUsage(), llvm::FPPassManager::getAnalysisUsage(), llvm::legacy::PassManagerImpl::getAnalysisUsage(), llvm::MemoryDependenceWrapperPass::getAnalysisUsage(), llvm::LoopAccessLegacyAnalysis::getAnalysisUsage(), llvm::MemorySSAPrinterLegacyPass::getAnalysisUsage(), llvm::RegionInfoPass::getAnalysisUsage(), llvm::DependenceAnalysisWrapperPass::getAnalysisUsage(), llvm::MemorySSAWrapperPass::getAnalysisUsage(), llvm::AAResultsWrapperPass::getAnalysisUsage(), llvm::ExternalAAWrapperPass::getAnalysisUsage(), llvm::LoopInfoWrapperPass::getAnalysisUsage(), llvm::ScalarEvolutionWrapperPass::getAnalysisUsage(), GetCtorAndDtorPriority(), INITIALIZE_PASS(), llvm::LiveRegMatrix::LiveRegMatrix(), lowerSubFn(), llvm::WarnMissedTransformationsPass::run(), llvm::CalledValuePropagationPass::run(), llvm::CFGViewerPass::run(), llvm::SafepointIRVerifierPass::run(), llvm::BitcodeWriterPass::run(), llvm::PrintFunctionPass::run(), llvm::verifyModule(), and writeCFGToDotFile().
setPreservesCFG()
void AnalysisUsage::setPreservesCFG ()
This function should be called by the pass, iff they do not:
Add or remove basic blocks from the function
Modify terminator instructions in any way.
This function annotates the AnalysisUsage info object to say that analyses that only depend on the CFG are preserved by this pass.
Definition at line 256 of file Pass.cpp.
Referenced by BlockData::BlockData(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::createFalkorMarkStridedAccessesPass(), llvm::createGreedyRegisterAllocator(), llvm::createObjCARCOptPass(), llvm::createPrologEpilogInserterPass(), llvm::createSystemZLDCleanupPass(), formLCSSAOnAllLoops(), llvm::InjectTLIMappingsLegacy::getAnalysisUsage(), llvm::InstructionCombiningPass::getAnalysisUsage(), llvm::DemandedBitsWrapperPass::getAnalysisUsage(), llvm::LiveIntervals::getAnalysisUsage(), llvm::sroa::SROALegacyPass::getAnalysisUsage(), getPreservesAll(), llvm::X86InstrInfo::getSerializableDirectMachineOperandTargetFlags(), INITIALIZE_PASS(), llvm::CoalescerPair::isCoalescable(), isImplicitlyDef(), isSecondInstructionInSequence(), optimizeDivRem(), performSink(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::DCEPass::run(), llvm::SinkingPass::run(), llvm::PromotePass::run(), llvm::BDCEPass::run(), llvm::IndVarSimplifyPass::run(), llvm::GuardWideningPass::run(), llvm::DSEPass::run(), llvm::ADCEPass::run(), llvm::EarlyCSEPass::run(), llvm::LoopSinkPass::run(), llvm::SCCPPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::InternalizePass::run(), llvm::ReassociatePass::run(), runImpl(), setCannotDuplicate(), simplifyLoopInst(), and llvm::AntiDepBreaker::~AntiDepBreaker().
The documentation for this class was generated from the following files:
include/llvm/PassAnalysisSupport.h
lib/IR/Pass.cpp