LLVM: llvm::object::XCOFFSymbolRef Class Reference
llvm::object::XCOFFSymbolRef Class Reference
#include "llvm/Object/XCOFFObjectFile.h"
Public Member Functions
XCOFFSymbolRef (DataRefImpl SymEntDataRef, const XCOFFObjectFile *OwningObjectPtr)
XCOFF::StorageClass getStorageClass () const
uint8_t getNumberOfAuxEntries () const
const XCOFFCsectAuxEnt32 * getXCOFFCsectAuxEnt32 () const
uint16_t getType () const
int16_t getSectionNumber () const
bool hasCsectAuxEnt () const
bool isFunction () const
Detailed Description
Definition at line 351 of file XCOFFObjectFile.h.
Constructor & Destructor Documentation
XCOFFSymbolRef()
llvm::object::XCOFFSymbolRef::XCOFFSymbolRef (DataRefImpl SymEntDataRef, const XCOFFObjectFile * OwningObjectPtr) inline
Definition at line 356 of file XCOFFObjectFile.h.
References getType().
Member Function Documentation
getNumberOfAuxEntries()
uint8_t llvm::object::XCOFFSymbolRef::getNumberOfAuxEntries () const
Definition at line 721 of file XCOFFObjectFile.cpp.
getSectionNumber()
int16_t llvm::object::XCOFFSymbolRef::getSectionNumber () const
Definition at line 746 of file XCOFFObjectFile.cpp.
getStorageClass()
XCOFF::StorageClass llvm::object::XCOFFSymbolRef::getStorageClass () const
Definition at line 717 of file XCOFFObjectFile.cpp.
getType()
uint16_t llvm::object::XCOFFSymbolRef::getType () const
Definition at line 742 of file XCOFFObjectFile.cpp.
getXCOFFCsectAuxEnt32()
const XCOFFCsectAuxEnt32 * llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxEnt32 () const
Definition at line 725 of file XCOFFObjectFile.cpp.
References assert(), llvm::object::getWithOffset(), and llvm::XCOFF::SymbolTableEntrySize.
hasCsectAuxEnt()
bool llvm::object::XCOFFSymbolRef::hasCsectAuxEnt () const
Definition at line 750 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::C_EXT, llvm::XCOFF::C_HIDEXT, llvm::XCOFF::C_WEAKEXT, and llvm::PPCISD::SC.
isFunction()
bool llvm::object::XCOFFSymbolRef::isFunction () const
Definition at line 756 of file XCOFFObjectFile.cpp.
References llvm::object::FUNCTION_SYM, llvm::Expected< T >::get(), getType(), llvm::report_fatal_error(), SI, llvm::object::XCOFFCsectAuxEnt32::StorageMappingClass, llvm::XCOFF::STYP_TEXT, llvm::object::SYM_TYPE_MASK, llvm::object::XCOFFCsectAuxEnt32::SymbolAlignmentAndType, llvm::XCOFF::XMC_PR, and llvm::XCOFF::XTY_LD.
The documentation for this class was generated from the following files:
include/llvm/Object/XCOFFObjectFile.h
lib/Object/XCOFFObjectFile.cpp