LLVM: llvm::orc::OrcI386 Class Reference
llvm::orc::OrcI386 Class Reference
I386 support.
#include "llvm/ExecutionEngine/Orc/OrcABISupport.h"
Public Types
using IndirectStubsInfo = GenericIndirectStubsInfo< 8 >
using JITReentryFn = JITTargetAddress(*)(void *CallbackMgr, void *TrampolineId)
Static Public Member Functions
static void writeResolverCode (uint8_t *ResolveMem, JITReentryFn Reentry, void *CallbackMgr)
Write the resolver code into the given memory.
static void writeTrampolines (uint8_t *TrampolineMem, void *ResolverAddr, unsigned NumTrampolines)
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
static Error emitIndirectStubsBlock (IndirectStubsInfo &StubsInfo, unsigned MinStubs, void *InitialPtrVal)
Emit at least MinStubs worth of indirect call stubs, rounded out to the nearest page size.
Static Public Attributes
static const unsigned PointerSize = 4
static const unsigned TrampolineSize = 8
static const unsigned ResolverCodeSize = 0x4a
Detailed Description
I386 support.
I386 supports lazy JITing.
Definition at line 208 of file OrcABISupport.h.
Member Typedef Documentation
IndirectStubsInfo
using llvm::orc::OrcI386::IndirectStubsInfo = GenericIndirectStubsInfo<8>
Definition at line 214 of file OrcABISupport.h.
JITReentryFn
using llvm::orc::OrcI386::JITReentryFn = JITTargetAddress (*)(void *CallbackMgr, void *TrampolineId)
Definition at line 217 of file OrcABISupport.h.
Member Function Documentation
emitIndirectStubsBlock()
Error llvm::orc::OrcI386::emitIndirectStubsBlock (IndirectStubsInfo & StubsInfo, unsigned MinStubs, void * InitialPtrVal) static
Emit at least MinStubs worth of indirect call stubs, rounded out to the nearest page size.
E.g. Asking for 4 stubs on i386, where stubs are 8-bytes, with 4k pages will return a block of 512 stubs (4096 / 8 = 512). Asking for 513 will return a block of 1024 (2-pages worth).
Definition at line 475 of file OrcABISupport.cpp.
References llvm::sys::Memory::allocateMappedMemory(), llvm::errorCodeToError(), llvm::sys::Process::getPageSizeEstimate(), I, llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, PageSize, llvm::sys::Memory::protectMappedMemory(), llvm::orc::GenericIndirectStubsInfo< StubSizeVal >::StubSize, and llvm::Error::success().
writeResolverCode()
void llvm::orc::OrcI386::writeResolverCode (uint8_t * ResolveMem, JITReentryFn Reentry, void * CallbackMgr) static
Write the resolver code into the given memory.
The user is responsible for allocating the memory and setting permissions.
Definition at line 415 of file OrcABISupport.cpp.
writeTrampolines()
void llvm::orc::OrcI386::writeTrampolines (uint8_t * TrampolineMem, void * ResolverAddr, unsigned NumTrampolines) static
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
Definition at line 462 of file OrcABISupport.cpp.
References I, and llvm::orc::OrcAArch64::TrampolineSize.
Member Data Documentation
PointerSize
const unsigned llvm::orc::OrcI386::PointerSize = 4 static
Definition at line 210 of file OrcABISupport.h.
ResolverCodeSize
const unsigned llvm::orc::OrcI386::ResolverCodeSize = 0x4a static
Definition at line 212 of file OrcABISupport.h.
TrampolineSize
const unsigned llvm::orc::OrcI386::TrampolineSize = 8 static
Definition at line 211 of file OrcABISupport.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/OrcABISupport.h
lib/ExecutionEngine/Orc/OrcABISupport.cpp