LLVM: llvm::MDOperand Class Reference
llvm::MDOperand Class Reference
Tracking metadata reference owned by Metadata.
#include "llvm/IR/Metadata.h"
Public Member Functions
MDOperand ()=default
MDOperand (MDOperand &&)=delete
MDOperand (const MDOperand &)=delete
MDOperand & operator= (MDOperand &&)=delete
MDOperand & operator= (const MDOperand &)=delete
~MDOperand ()
Metadata * get () const
operator Metadata * () const
Metadata * operator-> () const
Metadata & operator* () const
void reset ()
void reset (Metadata *MD, Metadata *Owner)
Detailed Description
Tracking metadata reference owned by Metadata.
Similar to TrackingMDRef, but it's expected to be owned by an instance of Metadata, which has the option of registering itself for callbacks to re-unique itself.
In particular, this is used by MDNode.
Definition at line 719 of file Metadata.h.
Constructor & Destructor Documentation
MDOperand() [1/3]
llvm::MDOperand::MDOperand () default
MDOperand() [2/3]
llvm::MDOperand::MDOperand (MDOperand &&) delete
MDOperand() [3/3]
llvm::MDOperand::MDOperand (const MDOperand &) delete
~MDOperand()
llvm::MDOperand::~MDOperand () inline
Definition at line 728 of file Metadata.h.
Member Function Documentation
get()
Metadata* llvm::MDOperand::get () const inline
Definition at line 730 of file Metadata.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::get_hashable_data(), getAssociatedSymbol(), getOptionalBoolLoopAttribute(), llvm::simplify_type< MDOperand >::getSimplifiedValue(), llvm::simplify_type< const MDOperand >::getSimplifiedValue(), inlineLoopID(), and llvm::makeFollowupLoopID().
operator Metadata *()
llvm::MDOperand::operator Metadata * () const inline
Definition at line 731 of file Metadata.h.
operator*()
Metadata& llvm::MDOperand::operator* () const inline
Definition at line 733 of file Metadata.h.
operator->()
Metadata* llvm::MDOperand::operator-> () const inline
Definition at line 732 of file Metadata.h.
operator=() [1/2]
MDOperand& llvm::MDOperand::operator= (MDOperand &&) delete
operator=() [2/2]
MDOperand& llvm::MDOperand::operator= (const MDOperand &) delete
reset() [1/2]
void llvm::MDOperand::reset () inline
Definition at line 735 of file Metadata.h.
Referenced by llvm::MDNode::setOperand().
reset() [2/2]
void llvm::MDOperand::reset (Metadata * MD, Metadata * Owner) inline
Definition at line 739 of file Metadata.h.
References assert(), llvm::MetadataTracking::track(), and llvm::MetadataTracking::untrack().
The documentation for this class was generated from the following file:
include/llvm/IR/Metadata.h