LLVM: llvm::BinaryStream Class Reference
llvm::BinaryStream Class Reference abstract
An interface for accessing data in a stream-like format, but which discourages copying.
#include "llvm/Support/BinaryStream.h"
Public Member Functions
virtual ~BinaryStream ()=default
virtual llvm::support::endianness getEndian () const =0
virtual Error readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
virtual Error readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream, read as much as possible without copying any data.
virtual uint32_t getLength ()=0
Return the number of bytes of data in this stream.
virtual BinaryStreamFlags getFlags () const
Return the properties of this stream.
Protected Member Functions
Error checkOffsetForRead (uint32_t Offset, uint32_t DataSize)
Detailed Description
An interface for accessing data in a stream-like format, but which discourages copying.
Instead of specifying a buffer in which to copy data on a read, the API returns an ArrayRef to data owned by the stream's implementation. Since implementations may not necessarily store data in a single contiguous buffer (or even in memory at all), in such cases a it may be necessary for an implementation to cache such a buffer so that it can return it.
Definition at line 35 of file BinaryStream.h.
Constructor & Destructor Documentation
~BinaryStream()
virtual llvm::BinaryStream::~BinaryStream () virtual default
Member Function Documentation
checkOffsetForRead()
Error llvm::BinaryStream::checkOffsetForRead (uint32_t Offset, uint32_t DataSize) inline protected
Definition at line 59 of file BinaryStream.h.
References getLength(), llvm::invalid_offset, llvm::stream_too_short, and llvm::Error::success().
Referenced by llvm::WritableBinaryStream::checkOffsetForWrite(), llvm::msf::MappedBlockStream::getLength(), llvm::BinaryByteStream::readBytes(), llvm::msf::MappedBlockStream::readBytes(), llvm::BinaryByteStream::readLongestContiguousChunk(), and llvm::msf::MappedBlockStream::readLongestContiguousChunk().
getEndian()
virtual llvm::support::endianness llvm::BinaryStream::getEndian () const pure virtual
Implemented in llvm::FileBufferByteStream, llvm::AppendingBinaryByteStream, llvm::msf::WritableMappedBlockStream, llvm::MutableBinaryByteStream, llvm::msf::MappedBlockStream, llvm::BinaryByteStream, and llvm::BinaryItemStream< T, Traits >.
Referenced by llvm::BinaryStreamReader::readInteger(), and llvm::BinaryStreamWriter::writeInteger().
getFlags()
virtual BinaryStreamFlags llvm::BinaryStream::getFlags () const inline virtual
Return the properties of this stream.
Reimplemented in llvm::AppendingBinaryByteStream, and llvm::WritableBinaryStream.
Definition at line 56 of file BinaryStream.h.
References llvm::BSF_None.
Referenced by llvm::WritableBinaryStream::checkOffsetForWrite().
getLength()
virtual uint32_t llvm::BinaryStream::getLength () pure virtual
Return the number of bytes of data in this stream.
Implemented in llvm::FileBufferByteStream, llvm::AppendingBinaryByteStream, llvm::msf::WritableMappedBlockStream, llvm::MutableBinaryByteStream, llvm::BinaryItemStream< T, Traits >, llvm::msf::MappedBlockStream, and llvm::BinaryByteStream.
Referenced by checkOffsetForRead(), llvm::WritableBinaryStream::checkOffsetForWrite(), llvm::BinaryStreamWriter::getLength(), and llvm::BinaryStreamReader::getLength().
readBytes()
virtual Error llvm::BinaryStream::readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > & Buffer) pure virtual
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Implemented in llvm::FileBufferByteStream, llvm::AppendingBinaryByteStream, llvm::msf::WritableMappedBlockStream, llvm::MutableBinaryByteStream, llvm::msf::MappedBlockStream, llvm::BinaryByteStream, and llvm::BinaryItemStream< T, Traits >.
Referenced by llvm::BinaryStreamRef::readBytes().
readLongestContiguousChunk()
virtual Error llvm::BinaryStream::readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > & Buffer) pure virtual
Given an offset into the stream, read as much as possible without copying any data.
Implemented in llvm::FileBufferByteStream, llvm::AppendingBinaryByteStream, llvm::msf::WritableMappedBlockStream, llvm::MutableBinaryByteStream, llvm::msf::MappedBlockStream, llvm::BinaryItemStream< T, Traits >, and llvm::BinaryByteStream.
Referenced by llvm::BinaryStreamRef::readLongestContiguousChunk().
The documentation for this class was generated from the following file:
include/llvm/Support/BinaryStream.h