LLVM: llvm::codeview::SimpleTypeSerializer Class Reference
llvm::codeview::SimpleTypeSerializer Class Reference
#include "llvm/DebugInfo/CodeView/SimpleTypeSerializer.h"
Public Member Functions
SimpleTypeSerializer ()
~SimpleTypeSerializer ()
template<typename T >
ArrayRef< uint8_t > serialize (T &Record)
ArrayRef< uint8_t > serialize (const FieldListRecord &Record)=delete
Detailed Description
Definition at line 33 of file SimpleTypeSerializer.h.
Constructor & Destructor Documentation
SimpleTypeSerializer()
SimpleTypeSerializer::SimpleTypeSerializer ()
Definition at line 19 of file SimpleTypeSerializer.cpp.
~SimpleTypeSerializer()
SimpleTypeSerializer::~SimpleTypeSerializer ()
Definition at line 21 of file SimpleTypeSerializer.cpp.
Member Function Documentation
serialize() [1/2]
template<typename T > ArrayRef< uint8_t > SimpleTypeSerializer::serialize (T & Record)
Definition at line 24 of file SimpleTypeSerializer.cpp.
References addPadding(), llvm::cantFail(), llvm::BinaryStreamWriter::getOffset(), llvm::codeview::CVRecord< Kind >::kind(), llvm::support::little, llvm::cl::Prefix, llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeEnd(), and llvm::BinaryStreamWriter::writeObject().
Referenced by llvm::codeview::AppendingTypeTableBuilder::writeLeafType(), llvm::codeview::MergingTypeTableBuilder::writeLeafType(), and llvm::codeview::GlobalTypeTableBuilder::writeLeafType().
serialize() [2/2]
ArrayRef<uint8_t> llvm::codeview::SimpleTypeSerializer::serialize (const FieldListRecord & Record) delete
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/SimpleTypeSerializer.h
lib/DebugInfo/CodeView/SimpleTypeSerializer.cpp