LLVM: false::Chain Class Reference
false::Chain Class Reference
A Chain is a sequence of instructions that are linked together by an accumulation operand.
Public Member Functions
Chain (MachineInstr *MI, unsigned Idx, Color C)
void add (MachineInstr *MI, unsigned Idx, Color C)
Add a new instruction into the chain.
bool contains (MachineInstr &MI)
Return true if MI is a member of the chain.
unsigned size () const
Return the number of instructions in the chain.
void setKill (MachineInstr *MI, unsigned Idx, bool Immutable)
Inform the chain that its last active register (the dest register of LastInst) is killed by MI with no intervening uses or defs.
MachineInstr * getStart () const
Return the first instruction in the chain.
MachineInstr * getLast () const
Return the last instruction in the chain.
MachineInstr * getKill () const
Return the "kill" instruction (as set with setKill()) or NULL.
MachineBasicBlock::iterator end () const
Return an instruction that can be used as an iterator for the end of the chain.
MachineBasicBlock::iterator begin () const
bool isKillImmutable () const
Can the Kill instruction (assuming one exists) be modified?
Color getPreferredColor ()
Return the preferred color of this chain.
bool rangeOverlapsWith (const Chain &Other) const
Return true if this chain (StartInst..KillInst) overlaps with Other.
bool startsBefore (const Chain *Other) const
Return true if this chain starts before Other.
bool requiresFixup () const
Return true if the group will require a fixup MOV at the end.
std::string str () const
Return a simple string representation of the chain.
Public Attributes
MachineInstr * StartInst
The important (marker) instructions.
MachineInstr * LastInst
MachineInstr * KillInst
unsigned StartInstIdx
The index, from the start of the basic block, that each marker appears.
unsigned LastInstIdx
unsigned KillInstIdx
std::set< MachineInstr * > Insts
All instructions in the chain.
bool KillIsImmutable
True if KillInst cannot be modified.
Color LastColor
The "color" of LastInst.
Detailed Description
A Chain is a sequence of instructions that are linked together by an accumulation operand.
For example:
fmul def d0, ? fmla def d1, ?, ?, killed d0 fmla def d2, ?, ?, killed d1
There may be other instructions interleaved in the sequence that do not belong to the chain. These other instructions must not use the "chain" register at any point.
We currently only support chains where the "chain" operand is killed at each link in the chain for simplicity. A chain has three important instructions - Start, Last and Kill.
The start instruction is the first instruction in the chain.
Last is the final instruction in the chain.
Kill may or may not be defined. If defined, Kill is the instruction where the outgoing value of the Last instruction is killed. This information is important as if we know the outgoing value is killed with no intervening uses, we can safely change its register.
Without a kill instruction, we must assume the outgoing value escapes beyond our model and either must not change its register or must create a fixup FMOV to keep the old register value consistent.
Definition at line 185 of file AArch64A57FPLoadBalancing.cpp.
Constructor & Destructor Documentation
Chain()
false::Chain::Chain (MachineInstr * MI, unsigned Idx, Color C) inline
Definition at line 203 of file AArch64A57FPLoadBalancing.cpp.
Member Function Documentation
add()
void false::Chain::add (MachineInstr * MI, unsigned Idx, Color C) inline
Add a new instruction into the chain.
The instruction's dest operand has the given color.
Definition at line 212 of file AArch64A57FPLoadBalancing.cpp.
References assert(), C, and MI.
begin()
MachineBasicBlock::iterator false::Chain::begin () const inline
Definition at line 253 of file AArch64A57FPLoadBalancing.cpp.
Referenced by str().
contains()
bool false::Chain::contains (MachineInstr & MI) inline
Return true if MI is a member of the chain.
Definition at line 224 of file AArch64A57FPLoadBalancing.cpp.
end()
MachineBasicBlock::iterator false::Chain::end () const inline
Return an instruction that can be used as an iterator for the end of the chain.
This is the maximum of KillInst (if set) and LastInst.
Definition at line 250 of file AArch64A57FPLoadBalancing.cpp.
Referenced by str().
getKill()
MachineInstr* false::Chain::getKill () const inline
Return the "kill" instruction (as set with setKill()) or NULL.
Definition at line 247 of file AArch64A57FPLoadBalancing.cpp.
getLast()
MachineInstr* false::Chain::getLast () const inline
Return the last instruction in the chain.
Definition at line 245 of file AArch64A57FPLoadBalancing.cpp.
getPreferredColor()
Color false::Chain::getPreferredColor () inline
Return the preferred color of this chain.
Definition at line 259 of file AArch64A57FPLoadBalancing.cpp.
References OverrideBalance.
getStart()
MachineInstr* false::Chain::getStart () const inline
Return the first instruction in the chain.
Definition at line 243 of file AArch64A57FPLoadBalancing.cpp.
isKillImmutable()
bool false::Chain::isKillImmutable () const inline
Can the Kill instruction (assuming one exists) be modified?
Definition at line 256 of file AArch64A57FPLoadBalancing.cpp.
rangeOverlapsWith()
bool false::Chain::rangeOverlapsWith (const Chain & Other) const inline
Return true if this chain (StartInst..KillInst) overlaps with Other.
Definition at line 266 of file AArch64A57FPLoadBalancing.cpp.
requiresFixup()
bool false::Chain::requiresFixup () const inline
Return true if the group will require a fixup MOV at the end.
Definition at line 280 of file AArch64A57FPLoadBalancing.cpp.
Referenced by str().
setKill()
void false::Chain::setKill (MachineInstr * MI, unsigned Idx, bool Immutable) inline
Inform the chain that its last active register (the dest register of LastInst) is killed by MI with no intervening uses or defs.
Definition at line 233 of file AArch64A57FPLoadBalancing.cpp.
References assert(), and MI.
size()
unsigned false::Chain::size () const inline
Return the number of instructions in the chain.
Definition at line 227 of file AArch64A57FPLoadBalancing.cpp.
Referenced by str().
startsBefore()
bool false::Chain::startsBefore (const Chain * Other) const inline
Return true if this chain starts before Other.
Definition at line 275 of file AArch64A57FPLoadBalancing.cpp.
References StartInstIdx.
Referenced by str().
str()
std::string false::Chain::str () const inline
Return a simple string representation of the chain.
Definition at line 285 of file AArch64A57FPLoadBalancing.cpp.
References llvm::LiveRegUnits::accumulate(), llvm::LiveRegUnits::addLiveOuts(), assert(), llvm::LiveRegUnits::available(), B, llvm::AArch64Subtarget::balanceFPOps(), begin(), C, llvm::MachineOperand::clobbersPhysReg(), llvm::dbgs(), llvm::MachineInstr::defs(), E, llvm::MachineBasicBlock::end(), end(), F(), G, llvm::MachineFunction::getFunction(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), I, llvm::MachineOperand::isKill(), isMla(), isMul(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isTied(), LLVM_DEBUG, MI, MRI, llvm::MachineInstr::print(), llvm::printReg(), Reg, requiresFixup(), runOnBasicBlock(), llvm::MachineOperand::setReg(), size(), llvm::sort(), startsBefore(), llvm::LiveRegUnits::stepBackward(), str(), llvm::raw_string_ostream::str(), TransformAll, TRI, and llvm::MachineInstr::uses().
Referenced by str().
Member Data Documentation
Insts
std::set<MachineInstr*> false::Chain::Insts
All instructions in the chain.
Definition at line 193 of file AArch64A57FPLoadBalancing.cpp.
KillInst
MachineInstr * false::Chain::KillInst
Definition at line 188 of file AArch64A57FPLoadBalancing.cpp.
KillInstIdx
unsigned false::Chain::KillInstIdx
Definition at line 191 of file AArch64A57FPLoadBalancing.cpp.
KillIsImmutable
bool false::Chain::KillIsImmutable
True if KillInst cannot be modified.
If this is true, we cannot change LastInst's outgoing register. This will be true for tied values and regmasks.
Definition at line 197 of file AArch64A57FPLoadBalancing.cpp.
LastColor
Color false::Chain::LastColor
The "color" of LastInst.
This will be the preferred chain color, as changing intermediate nodes is easy but changing the last instruction can be more tricky.
Definition at line 201 of file AArch64A57FPLoadBalancing.cpp.
LastInst
MachineInstr * false::Chain::LastInst
Definition at line 188 of file AArch64A57FPLoadBalancing.cpp.
LastInstIdx
unsigned false::Chain::LastInstIdx
Definition at line 191 of file AArch64A57FPLoadBalancing.cpp.
StartInst
MachineInstr* false::Chain::StartInst
The important (marker) instructions.
Definition at line 188 of file AArch64A57FPLoadBalancing.cpp.
StartInstIdx
unsigned false::Chain::StartInstIdx
The index, from the start of the basic block, that each marker appears.
These are stored so we can do quick interval tests.
Definition at line 191 of file AArch64A57FPLoadBalancing.cpp.
Referenced by startsBefore().
The documentation for this class was generated from the following file:
lib/Target/AArch64/AArch64A57FPLoadBalancing.cpp