LLVM: llvm::ValueLatticeElement Class Reference
llvm::ValueLatticeElement Class Reference
#include "llvm/Analysis/ValueLattice.h"
Public Member Functions
ValueLatticeElement ()
~ValueLatticeElement ()
Custom destructor to ensure Range is properly destroyed, when the object is deallocated.
ValueLatticeElement (const ValueLatticeElement &Other)
Custom copy constructor, to ensure Range gets initialized when copying a constant range lattice element.
ValueLatticeElement & operator= (const ValueLatticeElement &Other)
Custom assignment operator, to ensure Range gets initialized when assigning a constant range lattice element.
bool isUndefined () const
bool isConstant () const
bool isNotConstant () const
bool isConstantRange () const
bool isOverdefined () const
Constant * getConstant () const
Constant * getNotConstant () const
const ConstantRange & getConstantRange () const
Optional< APInt > asConstantInteger () const
bool mergeIn (const ValueLatticeElement &RHS, const DataLayout &DL)
Updates this object to approximate both this object and RHS.
ConstantInt * getConstantInt () const
Constant * getCompare (CmpInst::Predicate Pred, Type *Ty, const ValueLatticeElement &Other) const
Compares this symbolic value with Other using Pred and returns either true, false or undef constants, or nullptr if the comparison cannot be evaluated.
Static Public Member Functions
static ValueLatticeElement get (Constant *C)
static ValueLatticeElement getNot (Constant *C)
static ValueLatticeElement getRange (ConstantRange CR)
static ValueLatticeElement getOverdefined ()
Detailed Description
Definition at line 26 of file ValueLattice.h.
Constructor & Destructor Documentation
ValueLatticeElement() [1/2]
llvm::ValueLatticeElement::ValueLatticeElement () inline
Definition at line 63 of file ValueLattice.h.
~ValueLatticeElement()
llvm::ValueLatticeElement::~ValueLatticeElement () inline
Custom destructor to ensure Range is properly destroyed, when the object is deallocated.
Definition at line 67 of file ValueLattice.h.
References Range.
ValueLatticeElement() [2/2]
llvm::ValueLatticeElement::ValueLatticeElement (const ValueLatticeElement & Other) inline
Custom copy constructor, to ensure Range gets initialized when copying a constant range lattice element.
Definition at line 82 of file ValueLattice.h.
References llvm::Other.
Member Function Documentation
asConstantInteger()
Optional<APInt> llvm::ValueLatticeElement::asConstantInteger () const inline
Definition at line 164 of file ValueLattice.h.
References assert(), ConstVal, getConstant(), getConstantRange(), getNotConstant(), llvm::ConstantRange::getSingleElement(), isConstant(), isConstantRange(), llvm::ConstantRange::isEmptySet(), isNotConstant(), isOverdefined(), isUndefined(), llvm::None, and Range.
Referenced by getEdgeValueLocal().
get()
static ValueLatticeElement llvm::ValueLatticeElement::get (Constant * C) inline static
Definition at line 119 of file ValueLattice.h.
References C.
Referenced by getEdgeValueLocal(), getValueFromICmpCondition(), and intersect().
getCompare()
Constant* llvm::ValueLatticeElement::getCompare (CmpInst::Predicate Pred, Type * Ty, const ValueLatticeElement & Other) const inline
Compares this symbolic value with Other using Pred and returns either true, false or undef constants, or nullptr if the comparison cannot be evaluated.
Definition at line 293 of file ValueLattice.h.
References contains(), llvm::UndefValue::get(), llvm::ConstantExpr::getCompare(), getConstant(), getConstantRange(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getInversePredicate(), llvm::ConstantInt::getTrue(), isConstant(), isConstantRange(), isUndefined(), llvm::ConstantRange::makeSatisfyingICmpRegion(), and llvm::operator<<().
getConstant()
Constant* llvm::ValueLatticeElement::getConstant () const inline
Definition at line 148 of file ValueLattice.h.
References assert(), ConstVal, and isConstant().
Referenced by asConstantInteger(), getCompare(), llvm::LazyValueInfo::getConstant(), getConstantInt(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getPredicateResult(), mergeIn(), and llvm::operator<<().
getConstantInt()
ConstantInt* llvm::ValueLatticeElement::getConstantInt () const inline
Definition at line 284 of file ValueLattice.h.
References assert(), getConstant(), and isConstant().
getConstantRange()
const ConstantRange& llvm::ValueLatticeElement::getConstantRange () const inline
Definition at line 158 of file ValueLattice.h.
References assert(), isConstantRange(), and Range.
Referenced by asConstantInteger(), getCompare(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getEdgeValueLocal(), getPredicateResult(), hasSingleValue(), intersect(), mergeIn(), and llvm::operator<<().
getNot()
static ValueLatticeElement llvm::ValueLatticeElement::getNot (Constant * C) inline static
Definition at line 125 of file ValueLattice.h.
Referenced by getFromRangeMetadata(), getValueFromICmpCondition(), and isObjectDereferencedInBlock().
getNotConstant()
Constant* llvm::ValueLatticeElement::getNotConstant () const inline
Definition at line 153 of file ValueLattice.h.
References assert(), ConstVal, and isNotConstant().
Referenced by asConstantInteger(), getPredicateResult(), mergeIn(), and llvm::operator<<().
getOverdefined()
static ValueLatticeElement llvm::ValueLatticeElement::getOverdefined () inline static
Definition at line 136 of file ValueLattice.h.
Referenced by constantFoldUser(), getEdgeValueLocal(), getFromRangeMetadata(), getValueFromICmpCondition(), getValueFromOverflowCondition(), intersect(), and isObjectDereferencedInBlock().
getRange()
static ValueLatticeElement llvm::ValueLatticeElement::getRange (ConstantRange CR) inline static
Definition at line 131 of file ValueLattice.h.
Referenced by constantFoldUser(), getEdgeValueLocal(), getFromRangeMetadata(), getValueFromICmpCondition(), getValueFromOverflowCondition(), and intersect().
isConstant()
bool llvm::ValueLatticeElement::isConstant () const inline
Definition at line 143 of file ValueLattice.h.
Referenced by asConstantInteger(), getCompare(), llvm::LazyValueInfo::getConstant(), getConstant(), getConstantInt(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getPredicateResult(), hasSingleValue(), mergeIn(), and operator=().
isConstantRange()
bool llvm::ValueLatticeElement::isConstantRange () const inline
Definition at line 145 of file ValueLattice.h.
Referenced by asConstantInteger(), getCompare(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getPredicateResult(), hasSingleValue(), intersect(), mergeIn(), llvm::operator<<(), and operator=().
isNotConstant()
bool llvm::ValueLatticeElement::isNotConstant () const inline
Definition at line 144 of file ValueLattice.h.
Referenced by asConstantInteger(), getNotConstant(), getPredicateResult(), mergeIn(), llvm::operator<<(), and operator=().
isOverdefined()
bool llvm::ValueLatticeElement::isOverdefined () const inline
Definition at line 146 of file ValueLattice.h.
Referenced by asConstantInteger(), getEdgeValueLocal(), intersect(), isObjectDereferencedInBlock(), mergeIn(), and llvm::operator<<().
isUndefined()
bool llvm::ValueLatticeElement::isUndefined () const inline
Definition at line 142 of file ValueLattice.h.
Referenced by asConstantInteger(), llvm::LazyValueInfo::enableDT(), getCompare(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), intersect(), mergeIn(), and llvm::operator<<().
mergeIn()
bool llvm::ValueLatticeElement::mergeIn (const ValueLatticeElement & RHS, const DataLayout & DL) inline
Updates this object to approximate both this object and RHS.
Returns true if this object has been changed.
Definition at line 240 of file ValueLattice.h.
References assert(), getConstant(), getConstantRange(), getNotConstant(), isConstant(), isConstantRange(), llvm::ConstantRange::isFullSet(), isNotConstant(), isOverdefined(), isUndefined(), and llvm::ConstantRange::unionWith().
Referenced by isObjectDereferencedInBlock().
operator=()
ValueLatticeElement& llvm::ValueLatticeElement::operator= (const ValueLatticeElement & Other) inline
Custom assignment operator, to ensure Range gets initialized when assigning a constant range lattice element.
Definition at line 88 of file ValueLattice.h.
References ConstVal, isConstant(), isConstantRange(), isNotConstant(), and Range.
Member Data Documentation
ConstVal
Constant* llvm::ValueLatticeElement::ConstVal
Definition at line 57 of file ValueLattice.h.
Referenced by asConstantInteger(), getConstant(), getNotConstant(), and operator=().
Range
ConstantRange llvm::ValueLatticeElement::Range
Definition at line 58 of file ValueLattice.h.
Referenced by asConstantInteger(), getConstantRange(), operator=(), and ~ValueLatticeElement().
The documentation for this class was generated from the following file:
include/llvm/Analysis/ValueLattice.h