LLVM: llvm::codeview::DebugStringTableSubsection Class Reference
llvm::codeview::DebugStringTableSubsection Class Reference
Represents a read-write view of a CodeView string table.
#include "llvm/DebugInfo/CodeView/DebugStringTableSubsection.h"
Public Member Functions
DebugStringTableSubsection ()
uint32_t insert (StringRef S)
uint32_t getIdForString (StringRef S) const
StringRef getStringForId (uint32_t Id) const
uint32_t calculateSerializedSize () const override
Error commit (BinaryStreamWriter &Writer) const override
uint32_t size () const
StringMap< uint32_t >::const_iterator begin () const
StringMap< uint32_t >::const_iterator end () const
std::vector< uint32_t > sortedIds () const
Public Member Functions inherited from llvm::codeview::DebugSubsection
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsection
static bool classof (const DebugSubsection *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsection
DebugSubsectionKind Kind
Detailed Description
Represents a read-write view of a CodeView string table.
DebugStringTableSubsection owns the underlying storage for the table, and is capable of serializing the string table into a format understood by DebugStringTableSubsectionRef.
Definition at line 56 of file DebugStringTableSubsection.h.
Constructor & Destructor Documentation
DebugStringTableSubsection()
DebugStringTableSubsection::DebugStringTableSubsection ()
Definition at line 44 of file DebugStringTableSubsection.cpp.
Member Function Documentation
begin()
StringMap<uint32_t>::const_iterator llvm::codeview::DebugStringTableSubsection::begin () const inline
Definition at line 78 of file DebugStringTableSubsection.h.
References llvm::StringMap< ValueTy, AllocatorTy >::begin().
calculateSerializedSize()
uint32_t DebugStringTableSubsection::calculateSerializedSize () const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 60 of file DebugStringTableSubsection.cpp.
classof()
static bool llvm::codeview::DebugStringTableSubsection::classof (const DebugSubsection * S) inline static
Definition at line 60 of file DebugStringTableSubsection.h.
References llvm::codeview::DebugSubsection::kind(), llvm::size(), and llvm::codeview::StringTable.
commit()
Error DebugStringTableSubsection::commit (BinaryStreamWriter & Writer) const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 64 of file DebugStringTableSubsection.cpp.
References llvm::BinaryStreamWriter::getOffset().
end()
StringMap<uint32_t>::const_iterator llvm::codeview::DebugStringTableSubsection::end () const inline
Definition at line 82 of file DebugStringTableSubsection.h.
References llvm::StringMap< ValueTy, AllocatorTy >::end().
getIdForString()
uint32_t DebugStringTableSubsection::getIdForString (StringRef S) const
Definition at line 97 of file DebugStringTableSubsection.cpp.
References assert(), llvm::StringMap< ValueTy, AllocatorTy >::end(), and llvm::StringMap< ValueTy, AllocatorTy >::find().
Referenced by llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset().
getStringForId()
StringRef DebugStringTableSubsection::getStringForId (uint32_t Id) const
Definition at line 103 of file DebugStringTableSubsection.cpp.
References assert().
insert()
uint32_t DebugStringTableSubsection::insert (StringRef S)
Definition at line 47 of file DebugStringTableSubsection.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::insert(), P, and llvm::StringRef::size().
size()
uint32_t DebugStringTableSubsection::size () const
Definition at line 86 of file DebugStringTableSubsection.cpp.
References llvm::StringMapImpl::size().
sortedIds()
std::vector< uint32_t > DebugStringTableSubsection::sortedIds () const
Definition at line 88 of file DebugStringTableSubsection.cpp.
References llvm::sort().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugStringTableSubsection.h
lib/DebugInfo/CodeView/DebugStringTableSubsection.cpp