LLVM: llvm::A57ChainingConstraint Class Reference
llvm::A57ChainingConstraint Class Reference
Add the accumulator chaining constraint to a PBQP graph.
#include "Target/AArch64/AArch64PBQPRegAlloc.h"
Public Member Functions
void apply (PBQPRAGraph &G) override
Public Member Functions inherited from llvm::PBQPRAConstraint
virtual ~PBQPRAConstraint ()=0
Detailed Description
Add the accumulator chaining constraint to a PBQP graph.
Definition at line 20 of file AArch64PBQPRegAlloc.h.
Member Function Documentation
apply()
void A57ChainingConstraint::apply (PBQPRAGraph & G) override virtual
Implements llvm::PBQPRAConstraint.
Definition at line 326 of file AArch64PBQPRegAlloc.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SetVector< T, Vector, Set >::clear(), llvm::dbgs(), llvm::MachineFunction::dump(), llvm::SmallVectorBase::empty(), llvm::PBQP::Graph< SolverT >::getMetadata(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, MI, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::Pass::print(), llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and regJustKilledBefore().
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64PBQPRegAlloc.h
lib/Target/AArch64/AArch64PBQPRegAlloc.cpp