LLVM: llvm::FunctionImportGlobalProcessing Class Reference
llvm::FunctionImportGlobalProcessing Class Reference
Class to handle necessary GlobalValue changes required by ThinLTO function importing, including linkage changes and any necessary renaming.
#include "llvm/Transforms/Utils/FunctionImportUtils.h"
Public Member Functions
FunctionImportGlobalProcessing (Module &M, const ModuleSummaryIndex &Index, SetVector< GlobalValue *> *GlobalsToImport=nullptr)
bool run ()
Detailed Description
Class to handle necessary GlobalValue changes required by ThinLTO function importing, including linkage changes and any necessary renaming.
Definition at line 25 of file FunctionImportUtils.h.
Constructor & Destructor Documentation
FunctionImportGlobalProcessing()
llvm::FunctionImportGlobalProcessing::FunctionImportGlobalProcessing (Module & M, const ModuleSummaryIndex & Index, SetVector< GlobalValue *> * GlobalsToImport = nullptr) inline
Definition at line 88 of file FunctionImportUtils.h.
References llvm::collectUsedGlobalVariables(), llvm::computeSyntheticCounts(), llvm::ModuleSummaryIndex::hasExportedFunctions(), llvm::renameModuleForThinLTO(), and run().
Member Function Documentation
run()
bool FunctionImportGlobalProcessing::run ()
Definition at line 316 of file FunctionImportUtils.cpp.
Referenced by FunctionImportGlobalProcessing(), and llvm::renameModuleForThinLTO().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/FunctionImportUtils.h
lib/Transforms/Utils/FunctionImportUtils.cpp