LLVM: llvm::ms_demangle::Demangler Class Reference
llvm::ms_demangle::Demangler Class Reference
#include "llvm/Demangle/MicrosoftDemangle.h"
Public Member Functions
Demangler ()=default
virtual ~Demangler ()=default
SymbolNode * parse (StringView &MangledName)
TagTypeNode * parseTagUniqueName (StringView &MangledName)
void dumpBackReferences ()
Public Attributes
bool Error = false
Detailed Description
Definition at line 140 of file MicrosoftDemangle.h.
Constructor & Destructor Documentation
Demangler()
llvm::ms_demangle::Demangler::Demangler () default
~Demangler()
virtual llvm::ms_demangle::Demangler::~Demangler () virtual default
Member Function Documentation
dumpBackReferences()
void Demangler::dumpBackReferences ()
Definition at line 2307 of file MicrosoftDemangle.cpp.
References I, initializeOutputStream(), llvm::ms_demangle::OF_Default, and llvm::ms_demangle::TypeNode::output().
Referenced by llvm::microsoftDemangle().
parse()
SymbolNode * Demangler::parse (StringView & MangledName)
Definition at line 799 of file MicrosoftDemangle.cpp.
References SI.
Referenced by llvm::microsoftDemangle().
parseTagUniqueName()
TagTypeNode * Demangler::parseTagUniqueName (StringView & MangledName)
Definition at line 825 of file MicrosoftDemangle.cpp.
References llvm::ms_demangle::ArenaAllocator::alloc(), assert(), C, llvm::ms_demangle::PointerTypeNode::ClassParent, llvm::ms_demangle::ConversionOperatorIdentifier, llvm::ms_demangle::Drop, I, llvm::ms_demangle::Identifier, initializeOutputStream(), INT64_MAX, llvm::ms_demangle::Node::kind(), llvm::ms_demangle::BackrefContext::Max, N, Name, llvm::ms_demangle::NamedIdentifierNode::Name, llvm::ms_demangle::NBB_Simple, llvm::ms_demangle::NBB_Template, Number, llvm::ms_demangle::OF_Default, llvm::ms_demangle::Node::output(), llvm::ms_demangle::PointerTypeNode::Pointee, llvm::ms_demangle::PointerType, llvm::ms_demangle::Q_None, llvm::ms_demangle::TypeNode::Quals, llvm::MipsISD::Ret, llvm::PPCISD::SC, llvm::ms_demangle::VariableSymbolNode::SC, startsWithDigit(), llvm::ms_demangle::StructorIdentifier, std::swap(), llvm::ms_demangle::IdentifierNode::TemplateParams, and llvm::ms_demangle::VariableSymbolNode::Type.
Member Data Documentation
Error
bool llvm::ms_demangle::Demangler::Error = false
Definition at line 152 of file MicrosoftDemangle.h.
Referenced by llvm::microsoftDemangle().
The documentation for this class was generated from the following files:
include/llvm/Demangle/MicrosoftDemangle.h
lib/Demangle/MicrosoftDemangle.cpp