LLVM: llvm::pdb::InfoStreamBuilder Class Reference
llvm::pdb::InfoStreamBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/InfoStreamBuilder.h"
Public Member Functions
InfoStreamBuilder (msf::MSFBuilder &Msf, NamedStreamMap &NamedStreams)
InfoStreamBuilder (const InfoStreamBuilder &)=delete
InfoStreamBuilder & operator= (const InfoStreamBuilder &)=delete
void setVersion (PdbRaw_ImplVer V)
void addFeature (PdbRaw_FeatureSig Sig)
void setHashPDBContentsToGUID (bool B)
void setSignature (uint32_t S)
void setAge (uint32_t A)
void setGuid (codeview::GUID G)
bool hashPDBContentsToGUID () const
uint32_t getAge () const
codeview::GUID getGuid () const
Optional< uint32_t > getSignature () const
uint32_t finalize ()
Error finalizeMsfLayout ()
Error commit (const msf::MSFLayout &Layout, WritableBinaryStreamRef Buffer) const
Detailed Description
Definition at line 30 of file InfoStreamBuilder.h.
Constructor & Destructor Documentation
InfoStreamBuilder() [1/2]
InfoStreamBuilder::InfoStreamBuilder (msf::MSFBuilder & Msf, NamedStreamMap & NamedStreams)
Definition at line 25 of file InfoStreamBuilder.cpp.
InfoStreamBuilder() [2/2]
llvm::pdb::InfoStreamBuilder::InfoStreamBuilder (const InfoStreamBuilder &) delete
Member Function Documentation
addFeature()
void InfoStreamBuilder::addFeature (PdbRaw_FeatureSig Sig)
Definition at line 34 of file InfoStreamBuilder.cpp.
commit()
Error InfoStreamBuilder::commit (const msf::MSFLayout & Layout, WritableBinaryStreamRef Buffer) const
Definition at line 58 of file InfoStreamBuilder.cpp.
References assert(), llvm::pdb::NamedStreamMap::commit(), E, llvm::codeview::EC, llvm::msf::MSFBuilder::getAllocator(), H, llvm::pdb::StreamPDB, llvm::Error::success(), and llvm::pdb::InfoStreamHeader::Version.
finalize()
uint32_t llvm::pdb::InfoStreamBuilder::finalize ()
finalizeMsfLayout()
Error InfoStreamBuilder::finalizeMsfLayout ()
Definition at line 49 of file InfoStreamBuilder.cpp.
References llvm::pdb::NamedStreamMap::calculateSerializedLength(), llvm::codeview::EC, llvm::msf::MSFBuilder::setStreamSize(), llvm::pdb::StreamPDB, and llvm::Error::success().
getAge()
uint32_t llvm::pdb::InfoStreamBuilder::getAge () const inline
Definition at line 49 of file InfoStreamBuilder.h.
getGuid()
codeview::GUID llvm::pdb::InfoStreamBuilder::getGuid () const inline
Definition at line 50 of file InfoStreamBuilder.h.
getSignature()
Optional<uint32_t> llvm::pdb::InfoStreamBuilder::getSignature () const inline
Definition at line 51 of file InfoStreamBuilder.h.
References finalize.
hashPDBContentsToGUID()
bool llvm::pdb::InfoStreamBuilder::hashPDBContentsToGUID () const inline
Definition at line 48 of file InfoStreamBuilder.h.
operator=()
InfoStreamBuilder& llvm::pdb::InfoStreamBuilder::operator= (const InfoStreamBuilder &) delete
setAge()
void InfoStreamBuilder::setAge (uint32_t A)
Definition at line 42 of file InfoStreamBuilder.cpp.
setGuid()
void InfoStreamBuilder::setGuid (codeview::GUID G)
Definition at line 46 of file InfoStreamBuilder.cpp.
References G.
setHashPDBContentsToGUID()
void InfoStreamBuilder::setHashPDBContentsToGUID (bool B)
Definition at line 38 of file InfoStreamBuilder.cpp.
References B.
setSignature()
void InfoStreamBuilder::setSignature (uint32_t S)
Definition at line 44 of file InfoStreamBuilder.cpp.
setVersion()
void InfoStreamBuilder::setVersion (PdbRaw_ImplVer V)
Definition at line 32 of file InfoStreamBuilder.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/InfoStreamBuilder.h
lib/DebugInfo/PDB/Native/InfoStreamBuilder.cpp