LLVM: llvm::MetadataLoader Class Reference
llvm::MetadataLoader Class Reference
Helper class that handles loading Metadatas and keeping them available.
#include "Bitcode/Reader/MetadataLoader.h"
Classes
class MetadataLoaderImpl
Public Member Functions
~MetadataLoader ()
MetadataLoader (BitstreamCursor &Stream, Module &TheModule, BitcodeReaderValueList &ValueList, bool IsImporting, std::function< Type *(unsigned)> getTypeByID)
MetadataLoader & operator= (MetadataLoader &&)
MetadataLoader (MetadataLoader &&)
Error parseModuleMetadata ()
Error parseFunctionMetadata ()
void setStripTBAA (bool StripTBAA=true)
Set the mode to strip TBAA metadata on load.
bool isStrippingTBAA ()
Return true if the Loader is stripping TBAA metadata.
bool hasFwdRefs () const
Metadata * getMetadataFwdRefOrLoad (unsigned Idx)
Return the given metadata, creating a replaceable forward reference if necessary.
DISubprogram * lookupSubprogramForFunction (Function *F)
Return the DISubprogram metadata for a Function if any, null otherwise.
Error parseMetadataAttachment (Function &F, const SmallVectorImpl< Instruction *> &InstructionList)
Parse a METADATA_ATTACHMENT block for a function.
Error parseMetadataKinds ()
Parse a METADATA_KIND block for the current module.
unsigned size () const
void shrinkTo (unsigned N)
void upgradeDebugIntrinsics (Function &F)
Perform bitcode upgrades on llvm.dbg.* calls.
Detailed Description
Helper class that handles loading Metadatas and keeping them available.
Definition at line 35 of file MetadataLoader.h.
Constructor & Destructor Documentation
~MetadataLoader()
MetadataLoader::~MetadataLoader () default
Referenced by MetadataLoader().
MetadataLoader() [1/2]
MetadataLoader::MetadataLoader (BitstreamCursor & Stream, Module & TheModule, BitcodeReaderValueList & ValueList, bool IsImporting, std::function< Type *(unsigned)> getTypeByID)
Definition at line 2132 of file MetadataLoader.cpp.
MetadataLoader() [2/2]
MetadataLoader::MetadataLoader (MetadataLoader && RHS)
Definition at line 2128 of file MetadataLoader.cpp.
References ~MetadataLoader().
Member Function Documentation
getMetadataFwdRefOrLoad()
Metadata * MetadataLoader::getMetadataFwdRefOrLoad (unsigned Idx)
Return the given metadata, creating a replaceable forward reference if necessary.
Definition at line 2147 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
hasFwdRefs()
bool MetadataLoader::hasFwdRefs () const
Definition at line 2143 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
isStrippingTBAA()
bool MetadataLoader::isStrippingTBAA ()
Return true if the Loader is stripping TBAA metadata.
Definition at line 2168 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
lookupSubprogramForFunction()
DISubprogram * MetadataLoader::lookupSubprogramForFunction (Function * F)
Return the DISubprogram metadata for a Function if any, null otherwise.
Definition at line 2151 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
operator=()
MetadataLoader & MetadataLoader::operator= (MetadataLoader && RHS)
Definition at line 2124 of file MetadataLoader.cpp.
parseFunctionMetadata()
Error llvm::MetadataLoader::parseFunctionMetadata () inline
Definition at line 52 of file MetadataLoader.h.
References F(), getMetadataFwdRefOrLoad(), hasFwdRefs(), isStrippingTBAA(), lookupSubprogramForFunction(), N, parseMetadataAttachment(), parseMetadataKinds(), setStripTBAA(), shrinkTo(), size(), and upgradeDebugIntrinsics().
parseMetadataAttachment()
Error MetadataLoader::parseMetadataAttachment (Function & F, const SmallVectorImpl< Instruction *> & InstructionList)
Parse a METADATA_ATTACHMENT block for a function.
Definition at line 2155 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
parseMetadataKinds()
Error MetadataLoader::parseMetadataKinds ()
Parse a METADATA_KIND block for the current module.
Definition at line 2160 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
parseModuleMetadata()
Error llvm::MetadataLoader::parseModuleMetadata () inline
Definition at line 49 of file MetadataLoader.h.
setStripTBAA()
void MetadataLoader::setStripTBAA (bool StripTBAA = true)
Set the mode to strip TBAA metadata on load.
Definition at line 2164 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
shrinkTo()
void MetadataLoader::shrinkTo (unsigned N)
Definition at line 2171 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
size()
unsigned MetadataLoader::size () const
Definition at line 2170 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
upgradeDebugIntrinsics()
void MetadataLoader::upgradeDebugIntrinsics (Function & F)
Perform bitcode upgrades on llvm.dbg.* calls.
Definition at line 2173 of file MetadataLoader.cpp.
Referenced by parseFunctionMetadata().
The documentation for this class was generated from the following files:
lib/Bitcode/Reader/MetadataLoader.h
lib/Bitcode/Reader/MetadataLoader.cpp