LLVM: llvm::MachineRegionInfo Class Reference
llvm::MachineRegionInfo Class Reference
#include "llvm/CodeGen/MachineRegionInfo.h"
Public Member Functions
MachineRegionInfo ()
~MachineRegionInfo () override
void updateStatistics (MachineRegion *R) final
void recalculate (MachineFunction &F, MachineDominatorTree *DT, MachinePostDominatorTree *PDT, MachineDominanceFrontier *DF)
Public Member Functions inherited from llvm::RegionInfoBase< RegionTraits< MachineFunction > >
RegionInfoBase (const RegionInfoBase &)=delete
RegionInfoBase & operator= (const RegionInfoBase &)=delete
void print (raw_ostream &OS) const
void dump () const
void releaseMemory ()
RegionT * getRegionFor (BlockT *BB) const
Get the smallest region that contains a BasicBlock.
void setRegionFor (BlockT *BB, RegionT *R)
Set the smallest region that surrounds a basic block.
RegionT * operator[] (BlockT *BB) const
A shortcut for getRegionFor().
BlockT * getMaxRegionExit (BlockT *BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
RegionT * getCommonRegion (RegionT *A, RegionT *B) const
Find the smallest region that contains two regions.
RegionT * getCommonRegion (BlockT *A, BlockT *B) const
Find the smallest region that contains two basic blocks.
RegionT * getCommonRegion (SmallVectorImpl< RegionT * > &Regions) const
Find the smallest region that contains a set of regions.
RegionT * getCommonRegion (SmallVectorImpl< BlockT * > &BBs) const
Find the smallest region that contains a set of basic blocks.
RegionT * getTopLevelRegion () const
void clearNodeCache ()
Clear the Node Cache for all Regions.
void verifyAnalysis () const
Additional Inherited Members
Static Public Attributes inherited from llvm::RegionInfoBase< RegionTraits< MachineFunction > >
static bool VerifyRegionInfo
static RegionT::PrintStyle printStyle
Protected Member Functions inherited from llvm::RegionInfoBase< RegionTraits< MachineFunction > >
void updateRegionTree (RegionInfoT &RI, TheRegionT *R)
Update refences to a RegionInfoT held by the RegionT managed here.
Detailed Description
Definition at line 73 of file MachineRegionInfo.h.
Constructor & Destructor Documentation
MachineRegionInfo()
MachineRegionInfo::MachineRegionInfo () explicit default
Referenced by llvm::MachineRegion::MachineRegion().
~MachineRegionInfo()
MachineRegionInfo::~MachineRegionInfo () override default
Referenced by llvm::MachineRegion::MachineRegion().
Member Function Documentation
recalculate()
void MachineRegionInfo::recalculate (MachineFunction & F, MachineDominatorTree * DT, MachinePostDominatorTree * PDT, MachineDominanceFrontier * DF)
Definition at line 59 of file MachineRegionInfo.cpp.
References DF, and llvm::MachineRegion::MachineRegion().
Referenced by llvm::MachineRegionInfoPass::runOnMachineFunction().
updateStatistics()
void MachineRegionInfo::updateStatistics (MachineRegion * R) final
Definition at line 51 of file MachineRegionInfo.cpp.
References llvm::RegionBase< Tr >::isSimple().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineRegionInfo.h
lib/CodeGen/MachineRegionInfo.cpp