LLVM: llvm::SystemZII::Branch Class Reference
llvm::SystemZII::Branch Class Reference
#include "Target/SystemZ/SystemZInstrInfo.h"
Public Member Functions
Branch (BranchType type, unsigned ccValid, unsigned ccMask, const MachineOperand *target)
bool isIndirect ()
bool hasMBBTarget ()
MachineBasicBlock * getMBBTarget ()
Public Attributes
BranchType Type
unsigned CCValid
unsigned CCMask
Detailed Description
Definition at line 111 of file SystemZInstrInfo.h.
Constructor & Destructor Documentation
Branch()
llvm::SystemZII::Branch::Branch (BranchType type, unsigned ccValid, unsigned ccMask, const MachineOperand * target) inline
Definition at line 125 of file SystemZInstrInfo.h.
Member Function Documentation
getMBBTarget()
MachineBasicBlock* llvm::SystemZII::Branch::getMBBTarget () inline
Definition at line 131 of file SystemZInstrInfo.h.
References llvm::MachineOperand::getMBB(), and hasMBBTarget().
Referenced by llvm::SystemZPostRASchedStrategy::enterMBB().
hasMBBTarget()
bool llvm::SystemZII::Branch::hasMBBTarget () inline
Definition at line 130 of file SystemZInstrInfo.h.
References llvm::MachineOperand::isMBB().
Referenced by getMBBTarget(), and llvm::SystemZInstrInfo::removeBranch().
isIndirect()
bool llvm::SystemZII::Branch::isIndirect () inline
Definition at line 129 of file SystemZInstrInfo.h.
References llvm::MachineOperand::isReg().
Referenced by llvm::SystemZPostRASchedStrategy::enterMBB().
Member Data Documentation
CCMask
unsigned llvm::SystemZII::Branch::CCMask
Definition at line 123 of file SystemZInstrInfo.h.
CCValid
unsigned llvm::SystemZII::Branch::CCValid
Definition at line 120 of file SystemZInstrInfo.h.
Type
BranchType llvm::SystemZII::Branch::Type
Definition at line 117 of file SystemZInstrInfo.h.
The documentation for this class was generated from the following file:
lib/Target/SystemZ/SystemZInstrInfo.h