LLVM: llvm::GCOVFile Class Reference
llvm::GCOVFile Class Reference
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
#include "llvm/ProfileData/GCOV.h"
Public Member Functions
GCOVFile ()=default
bool readGCNO (GCOVBuffer &Buffer)
readGCNO - Read GCNO buffer.
bool readGCDA (GCOVBuffer &Buffer)
readGCDA - Read GCDA buffer.
uint32_t getChecksum () const
void print (raw_ostream &OS) const
void dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
collectLineCounts - Collect line counts.
Detailed Description
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
Definition at line 245 of file GCOV.h.
Constructor & Destructor Documentation
GCOVFile()
llvm::GCOVFile::GCOVFile () default
Member Function Documentation
collectLineCounts()
void GCOVFile::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts.
This must be used after reading .gcno and .gcda files.
Definition at line 119 of file GCOV.cpp.
References llvm::FileInfo::setProgramCount(), and llvm::FileInfo::setRunCount().
dump()
LLVM_DUMP_METHOD void GCOVFile::dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
Definition at line 114 of file GCOV.cpp.
References llvm::dbgs(), and print().
getChecksum()
uint32_t llvm::GCOVFile::getChecksum () const inline
Definition at line 251 of file GCOV.h.
References llvm::dump(), print(), and llvm::IndexedInstrProf::Version.
print()
void GCOVFile::print (raw_ostream & OS) const
Definition at line 107 of file GCOV.cpp.
Referenced by branchDiv(), dump(), llvm::GCOVFunction::dump(), and llvm::GCOVBlock::dump().
readGCDA()
bool GCOVFile::readGCDA (GCOVBuffer & Buffer)
readGCDA - Read GCDA buffer.
It is required that readGCDA() can only be called after readGCNO().
Definition at line 55 of file GCOV.cpp.
References llvm::GCOVBuffer::advanceCursor(), assert(), llvm::NVPTXISD::Dummy, llvm::numbers::e, llvm::errs(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readGCDAFormat(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readObjectTag(), and llvm::GCOVBuffer::readProgramTag().
readGCNO()
bool GCOVFile::readGCNO (GCOVBuffer & Buffer)
readGCNO - Read GCNO buffer.
Definition at line 32 of file GCOV.cpp.
References llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readGCNOFormat(), llvm::GCOVBuffer::readGCOVVersion(), and llvm::GCOVBuffer::readInt().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/GCOV.h
lib/ProfileData/GCOV.cpp