LLVM: llvm::orc::rpc::SerializationTraits< ChannelT, JITSymbolFlags > Class Template Reference
llvm::orc::rpc::SerializationTraits< ChannelT, JITSymbolFlags > Class Template Reference
#include "llvm/ExecutionEngine/Orc/OrcRemoteTargetRPCAPI.h"
Static Public Member Functions
static Error serialize (ChannelT &C, const JITSymbolFlags &Flags)
static Error deserialize (ChannelT &C, JITSymbolFlags &Flags)
Detailed Description
template<typename ChannelT>
class llvm::orc::rpc::SerializationTraits< ChannelT, JITSymbolFlags >
Definition at line 85 of file OrcRemoteTargetRPCAPI.h.
Member Function Documentation
deserialize()
template<typename ChannelT > static Error llvm::orc::rpc::SerializationTraits< ChannelT, JITSymbolFlags >::deserialize (ChannelT & C, JITSymbolFlags & Flags) inline static
Definition at line 92 of file OrcRemoteTargetRPCAPI.h.
serialize()
template<typename ChannelT > static Error llvm::orc::rpc::SerializationTraits< ChannelT, JITSymbolFlags >::serialize (ChannelT & C, const JITSymbolFlags & Flags) inline static
Definition at line 88 of file OrcRemoteTargetRPCAPI.h.
References llvm::JITSymbolFlags::getRawFlagsValue(), llvm::JITSymbolFlags::getTargetFlags(), and llvm::orc::rpc::serializeSeq().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRemoteTargetRPCAPI.h