LLVM: llvm::CodeExtractor Class Reference
llvm::CodeExtractor Class Reference
Utility class for extracting code into a new function.
#include "llvm/Transforms/Utils/CodeExtractor.h"
Public Member Functions
CodeExtractor (ArrayRef< BasicBlock *> BBs, DominatorTree *DT=nullptr, bool AggregateArgs=false, BlockFrequencyInfo *BFI=nullptr, BranchProbabilityInfo *BPI=nullptr, AssumptionCache *AC=nullptr, bool AllowVarArgs=false, bool AllowAlloca=false, std::string Suffix="")
Create a code extractor for a sequence of blocks.
CodeExtractor (DominatorTree &DT, Loop &L, bool AggregateArgs=false, BlockFrequencyInfo *BFI=nullptr, BranchProbabilityInfo *BPI=nullptr, AssumptionCache *AC=nullptr, std::string Suffix="")
Create a code extractor for a loop body.
Function * extractCodeRegion (const CodeExtractorAnalysisCache &CEAC)
Perform the extraction, returning the new function.
bool isEligible () const
Test whether this code extractor is eligible.
void findInputsOutputs (ValueSet &Inputs, ValueSet &Outputs, const ValueSet &Allocas) const
Compute the set of input values and output values for the code.
bool isLegalToShrinkwrapLifetimeMarkers (const CodeExtractorAnalysisCache &CEAC, Instruction *AllocaAddr) const
Check if life time marker nodes can be hoisted/sunk into the outline region.
void findAllocas (const CodeExtractorAnalysisCache &CEAC, ValueSet &SinkCands, ValueSet &HoistCands, BasicBlock *&ExitBlock) const
Find the set of allocas whose life ranges are contained within the outlined region.
BasicBlock * findOrCreateBlockForHoisting (BasicBlock *CommonExitBlock)
Find or create a block within the outline region for placing hoisted code.
Static Public Member Functions
static bool verifyAssumptionCache (const Function &F, AssumptionCache *AC)
Verify that assumption cache isn't stale after a region is extracted.
Detailed Description
Utility class for extracting code into a new function.
This utility provides a simple interface for extracting some sequence of code into its own function, replacing it with a call to that function. It also provides various methods to query about the nature and result of such a transformation.
The rough algorithm used is: 1) Find both the inputs and outputs for the extracted region. 2) Pass the inputs as arguments, remapping them within the extracted function to arguments. 3) Add allocas for any scalar outputs, adding all of the outputs' allocas as arguments, and inserting stores to the arguments for any scalars.
Definition at line 85 of file CodeExtractor.h.
Constructor & Destructor Documentation
CodeExtractor() [1/2]
CodeExtractor::CodeExtractor (ArrayRef< BasicBlock *> BBs, DominatorTree * DT = nullptr, bool AggregateArgs = false, BlockFrequencyInfo * BFI = nullptr, BranchProbabilityInfo * BPI = nullptr, AssumptionCache * AC = nullptr, bool AllowVarArgs = false, bool AllowAlloca = false, std::string Suffix = "")
Create a code extractor for a sequence of blocks.
Given a sequence of basic blocks where the first block in the sequence dominates the rest, prepare a code extractor object for pulling this sequence out into its new function. When a DominatorTree is also given, extra checking and transformations are enabled. If AllowVarArgs is true, vararg functions can be extracted. This is safe, if all vararg handling code is extracted, including vastart. If AllowAlloca is true, then extraction of blocks containing alloca instructions would be possible, however code extractor won't validate whether extraction is legal.
Definition at line 244 of file CodeExtractor.cpp.
CodeExtractor() [2/2]
CodeExtractor::CodeExtractor (DominatorTree & DT, Loop & L, bool AggregateArgs = false, BlockFrequencyInfo * BFI = nullptr, BranchProbabilityInfo * BPI = nullptr, AssumptionCache * AC = nullptr, std::string Suffix = "")
Create a code extractor for a loop body.
Behaves just like the generic code sequence constructor, but uses the block sequence of the loop.
Definition at line 254 of file CodeExtractor.cpp.
Member Function Documentation
extractCodeRegion()
Function * CodeExtractor::extractCodeRegion (const CodeExtractorAnalysisCache & CEAC)
Perform the extraction, returning the new function.
Returns zero when called on a CodeExtractor instance where isEligible returns false.
Definition at line 1386 of file CodeExtractor.cpp.
References llvm::any_of(), assert(), llvm::BasicBlock::begin(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::numbers::e, llvm::SetVector< T, Vector, Set >::empty(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), eraseLifetimeMarkersOnInputs(), llvm::errs(), findAllocas(), llvm::findDbgUsers(), findInputsOutputs(), findOrCreateBlockForHoisting(), llvm::SetVector< T, Vector, Set >::getArrayRef(), llvm::BlockFrequencyInfo::getBlockFreq(), llvm::BasicBlock::getContext(), llvm::Instruction::getDebugLoc(), llvm::BranchProbabilityInfo::getEdgeProbability(), llvm::BlockFrequency::getFrequency(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getNumIncomingValues(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Function::getPersonalityFn(), llvm::BlockFrequencyInfo::getProfileCountFromFreq(), llvm::Function::getSubprogram(), llvm::BasicBlock::getTerminator(), llvm::Function::hasPersonalityFn(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), insertLifetimeMarkersSurroundingCall(), isEligible(), LLVM_DEBUG, llvm::PatternMatch::match(), llvm::Instruction::moveBefore(), llvm::none_of(), llvm::Function::PCT_Real, llvm::predecessors(), llvm::report_fatal_error(), llvm::BlockFrequencyInfo::setBlockFreq(), llvm::Function::setEntryCount(), llvm::PHINode::setIncomingBlock(), llvm::Function::setPersonalityFn(), SI, llvm::SmallPtrSetImplBase::size(), llvm::succ_begin(), llvm::succ_end(), llvm::AssumptionCache::unregisterAssumption(), verifyAssumptionCache(), and llvm::verifyFunction().
Referenced by llvm::createBlockExtractorPass(), llvm::OpenMPIRBuilder::CreateParallel(), hasProfileData(), and INITIALIZE_PASS().
findAllocas()
void CodeExtractor::findAllocas (const CodeExtractorAnalysisCache & CEAC, ValueSet & SinkCands, ValueSet & HoistCands, BasicBlock *& ExitBlock) const
Find the set of allocas whose life ranges are contained within the outlined region.
Allocas which have life_time markers contained in the outlined region should be pushed to the outlined function. The address bitcasts that are used by the lifetime markers are also candidates for shrink- wrapping. The instructions that need to be sunk are collected in 'Allocas'.
Definition at line 486 of file CodeExtractor.cpp.
References assert(), llvm::MCID::Bitcast, llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), definedInRegion(), E, llvm::SmallVectorBase::empty(), llvm::CodeExtractorAnalysisCache::getAllocas(), getCommonExitBlock(), llvm::BasicBlock::getParent(), getParent(), I, llvm::SetVector< T, Vector, Set >::insert(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), and llvm::Value::users().
Referenced by llvm::OpenMPIRBuilder::CreateParallel(), and extractCodeRegion().
findInputsOutputs()
void CodeExtractor::findInputsOutputs (ValueSet & Inputs, ValueSet & Outputs, const ValueSet & Allocas) const
Compute the set of input values and output values for the code.
These can be used either when performing the extraction or to evaluate the expected size of a call to the extracted function. Note that this work cannot be cached between the two as once we decide to extract a code sequence, that sequence is modified, including changing these sets, before extraction occurs. These modifications won't have any significant impact on the cost however.
Definition at line 598 of file CodeExtractor.cpp.
References llvm::Function::addFnAttr(), llvm::PHINode::addIncoming(), llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock(), llvm::Function::arg_begin(), llvm::DomTreeNodeBase< NodeT >::begin(), llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::CallingConv::Cold, llvm::MCID::Convergent, llvm::SetVector< T, Vector, Set >::count(), llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::GetElementPtrInst::Create(), llvm::PHINode::Create(), llvm::BranchInst::Create(), llvm::dbgs(), definedInCaller(), definedInRegion(), llvm::Function::doesNotThrow(), llvm::dyn_cast(), llvm::numbers::e, llvm::StringRef::empty(), llvm::DomTreeNodeBase< NodeT >::end(), llvm::Attribute::EndAttrKinds, llvm::BasicBlock::front(), GEP, llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::GlobalValue::getAddressSpace(), llvm::Function::getAttributes(), llvm::Function::getBasicBlockList(), llvm::BasicBlock::getContext(), llvm::Module::getContext(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHI(), llvm::AttributeList::getFnAttributes(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), getName(), llvm::Value::getName(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::Constant::getNullValue(), llvm::PHINode::getNumIncomingValues(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::Function::hasUWTable(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::GlobalValue::InternalLinkage, llvm::Function::isVarArg(), llvm::ISD::JumpTable, LLVM_DEBUG, llvm::NoAlias, llvm::Attribute::None, llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::PHINode::removeIncomingValue(), llvm::Value::replaceAllUsesWith(), llvm::User::replaceUsesOfWith(), llvm::reverse(), llvm::Function::setDoesNotThrow(), llvm::Function::setHasUWTable(), llvm::Value::setName(), llvm::SmallVectorBase::size(), llvm::SetVector< T, Vector, Set >::size(), llvm::SplitBlock(), llvm::StringRef::str(), use, llvm::Value::user_begin(), llvm::Value::user_end(), Users, and llvm::Value::users().
Referenced by llvm::OpenMPIRBuilder::CreateParallel(), extractCodeRegion(), and hasProfileData().
findOrCreateBlockForHoisting()
BasicBlock * CodeExtractor::findOrCreateBlockForHoisting (BasicBlock * CommonExitBlock)
Find or create a block within the outline region for placing hoisted code.
CommonExitBlock is block outside the outline region. It is the common successor of blocks inside the region. If there exists a single block inside the region that is the predecessor of CommonExitBlock, that block will be returned. Otherwise CommonExitBlock will be split and the original block will be added to the outline region.
Definition at line 385 of file CodeExtractor.cpp.
References assert(), llvm::BasicBlock::begin(), definedInRegion(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::BasicBlock::getFirstNonPHI(), llvm::IntrinsicInst::getIntrinsicID(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::BasicBlock::getTerminator(), I, Info, isLegalToShrinkwrapLifetimeMarkers(), llvm::pred_begin(), llvm::pred_end(), llvm::predecessors(), llvm::User::replaceUsesOfWith(), llvm::BasicBlock::splitBasicBlock(), and llvm::Value::users().
Referenced by extractCodeRegion().
isEligible()
bool CodeExtractor::isEligible () const
Test whether this code extractor is eligible.
Based on the blocks used when constructing the code extractor, determine whether it is eligible for extraction.
Checks that varargs handling (with vastart and vaend) is only done in the outlined blocks.
Definition at line 571 of file CodeExtractor.cpp.
References llvm::any_of(), Callee, F(), llvm::Function::getFunctionType(), llvm::BasicBlock::getParent(), I, and llvm::FunctionType::isVarArg().
Referenced by extractCodeRegion().
isLegalToShrinkwrapLifetimeMarkers()
bool CodeExtractor::isLegalToShrinkwrapLifetimeMarkers (const CodeExtractorAnalysisCache & CEAC, Instruction * AllocaAddr) const
Check if life time marker nodes can be hoisted/sunk into the outline region.
Returns true if it is safe to do the code motion.
Definition at line 371 of file CodeExtractor.cpp.
References llvm::CodeExtractorAnalysisCache::doesBlockContainClobberOfAddr(), getParent(), and llvm::Value::stripInBoundsConstantOffsets().
Referenced by findOrCreateBlockForHoisting().
verifyAssumptionCache()
bool CodeExtractor::verifyAssumptionCache (const Function & F, AssumptionCache * AC) static
Verify that assumption cache isn't stale after a region is extracted.
Returns false when verifier finds errors. AssumptionCache is passed as parameter to make this function stateless.
Definition at line 1612 of file CodeExtractor.cpp.
References llvm::AssumptionCache::assumptions(), F(), llvm::Instruction::getFunction(), and I.
Referenced by extractCodeRegion().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/CodeExtractor.h
lib/Transforms/Utils/CodeExtractor.cpp