LLVM: llvm::codeview::MemberFunctionRecord Class Reference
llvm::codeview::MemberFunctionRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
MemberFunctionRecord ()=default
MemberFunctionRecord (TypeRecordKind Kind)
MemberFunctionRecord (TypeIndex ReturnType, TypeIndex ClassType, TypeIndex ThisType, CallingConvention CallConv, FunctionOptions Options, uint16_t ParameterCount, TypeIndex ArgumentList, int32_t ThisPointerAdjustment)
TypeIndex getReturnType () const
TypeIndex getClassType () const
TypeIndex getThisType () const
CallingConvention getCallConv () const
FunctionOptions getOptions () const
uint16_t getParameterCount () const
TypeIndex getArgumentList () const
int32_t getThisPointerAdjustment () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex ReturnType
TypeIndex ClassType
TypeIndex ThisType
CallingConvention CallConv
FunctionOptions Options
uint16_t ParameterCount = 0
TypeIndex ArgumentList
int32_t ThisPointerAdjustment = 0
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 176 of file TypeRecord.h.
Constructor & Destructor Documentation
MemberFunctionRecord() [1/3]
llvm::codeview::MemberFunctionRecord::MemberFunctionRecord () default
MemberFunctionRecord() [2/3]
llvm::codeview::MemberFunctionRecord::MemberFunctionRecord (TypeRecordKind Kind) inline explicit
Definition at line 179 of file TypeRecord.h.
MemberFunctionRecord() [3/3]
llvm::codeview::MemberFunctionRecord::MemberFunctionRecord (TypeIndex ReturnType, TypeIndex ClassType, TypeIndex ThisType, CallingConvention CallConv, FunctionOptions Options, uint16_t ParameterCount, TypeIndex ArgumentList, int32_t ThisPointerAdjustment) inline
Definition at line 181 of file TypeRecord.h.
Member Function Documentation
getArgumentList()
TypeIndex llvm::codeview::MemberFunctionRecord::getArgumentList () const inline
Definition at line 197 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getCallConv()
CallingConvention llvm::codeview::MemberFunctionRecord::getCallConv () const inline
Definition at line 194 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getClassType()
TypeIndex llvm::codeview::MemberFunctionRecord::getClassType () const inline
Definition at line 192 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getOptions()
FunctionOptions llvm::codeview::MemberFunctionRecord::getOptions () const inline
Definition at line 195 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeFunctionSig::hasConstructor(), llvm::pdb::NativeTypeFunctionSig::isConstructorVirtualBase(), llvm::pdb::NativeTypeFunctionSig::isCxxReturnUdt(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getParameterCount()
uint16_t llvm::codeview::MemberFunctionRecord::getParameterCount () const inline
Definition at line 196 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeFunctionSig::getCount(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getReturnType()
TypeIndex llvm::codeview::MemberFunctionRecord::getReturnType () const inline
Definition at line 191 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeFunctionSig::getTypeId(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getThisPointerAdjustment()
int32_t llvm::codeview::MemberFunctionRecord::getThisPointerAdjustment () const inline
Definition at line 198 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeFunctionSig::getThisAdjust(), and llvm::codeview::TypeDumpVisitor::visitMemberEnd().
getThisType()
TypeIndex llvm::codeview::MemberFunctionRecord::getThisType () const inline
Definition at line 193 of file TypeRecord.h.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberEnd().
Member Data Documentation
ArgumentList
TypeIndex llvm::codeview::MemberFunctionRecord::ArgumentList
Definition at line 206 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeFunctionSig::initialize(), and llvm::codeview::TypeRecordMapping::visitMemberEnd().
CallConv
CallingConvention llvm::codeview::MemberFunctionRecord::CallConv
Definition at line 203 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeFunctionSig::getCallingConvention(), and llvm::codeview::TypeRecordMapping::visitMemberEnd().
ClassType
TypeIndex llvm::codeview::MemberFunctionRecord::ClassType
Definition at line 201 of file TypeRecord.h.
Referenced by llvm::pdb::NativeTypeFunctionSig::initialize(), and llvm::codeview::TypeRecordMapping::visitMemberEnd().
Options
FunctionOptions llvm::codeview::MemberFunctionRecord::Options
Definition at line 204 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
ParameterCount
uint16_t llvm::codeview::MemberFunctionRecord::ParameterCount = 0
Definition at line 205 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
ReturnType
TypeIndex llvm::codeview::MemberFunctionRecord::ReturnType
Definition at line 200 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
ThisPointerAdjustment
int32_t llvm::codeview::MemberFunctionRecord::ThisPointerAdjustment = 0
Definition at line 207 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
ThisType
TypeIndex llvm::codeview::MemberFunctionRecord::ThisType
Definition at line 202 of file TypeRecord.h.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h