LLVM: llvm::InstCombinePass Class Reference
llvm::InstCombinePass Class Reference
#include "llvm/Transforms/InstCombine/InstCombine.h"
Public Member Functions
InstCombinePass (bool ExpensiveCombines=true)
InstCombinePass (bool ExpensiveCombines, unsigned MaxIterations)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Static Public Member Functions
static StringRef name ()
Static Public Member Functions inherited from llvm::PassInfoMixin< InstCombinePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 25 of file InstCombine.h.
Constructor & Destructor Documentation
InstCombinePass() [1/2]
InstCombinePass::InstCombinePass (bool ExpensiveCombines = true) explicit
Definition at line 3627 of file InstructionCombining.cpp.
Referenced by name().
InstCombinePass() [2/2]
InstCombinePass::InstCombinePass (bool ExpensiveCombines, unsigned MaxIterations) explicit
Definition at line 3630 of file InstructionCombining.cpp.
Member Function Documentation
name()
static StringRef llvm::InstCombinePass::name () inline static
Definition at line 31 of file InstCombine.h.
References F(), InstCombinePass(), and run().
run()
PreservedAnalyses InstCombinePass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 3633 of file InstructionCombining.cpp.
References llvm::PreservedAnalyses::all(), llvm::AMDGPUISD::BFI, combineInstructionsOverFunction(), F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::GlobalValue::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::ProfileSummaryInfo::hasProfileSummary(), llvm::PreservedAnalyses::preserve(), and llvm::PreservedAnalyses::preserveSet().
Referenced by name().
The documentation for this class was generated from the following files:
include/llvm/Transforms/InstCombine/InstCombine.h
lib/Transforms/InstCombine/InstructionCombining.cpp