LLVM: llvm::CalledValuePropagationPass Class Reference
llvm::CalledValuePropagationPass Class Reference
#include "llvm/Transforms/IPO/CalledValuePropagation.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< CalledValuePropagationPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 27 of file CalledValuePropagation.h.
Member Function Documentation
run()
PreservedAnalyses CalledValuePropagationPass::run (Module & M, ModuleAnalysisManager &)
Definition at line 405 of file CalledValuePropagation.cpp.
References llvm::PreservedAnalyses::all(), llvm::PassRegistry::getPassRegistry(), llvm::initializeCalledValuePropagationLegacyPassPass(), runCVP(), and llvm::AnalysisUsage::setPreservesAll().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/CalledValuePropagation.h
lib/Transforms/IPO/CalledValuePropagation.cpp