LLVM: llvm::orc::ObjectLinkingLayer::Plugin Class Reference
llvm::orc::ObjectLinkingLayer::Plugin Class Reference
Plugin instances can be added to the ObjectLinkingLayer to receive callbacks when code is loaded or emitted, and when JITLink is being configured.
#include "llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h"
Public Member Functions
virtual ~Plugin ()
virtual void modifyPassConfig (MaterializationResponsibility &MR, const Triple &TT, jitlink::PassConfiguration &Config)
virtual void notifyLoaded (MaterializationResponsibility &MR)
virtual Error notifyEmitted (MaterializationResponsibility &MR)
virtual Error notifyRemovingModule (VModuleKey K)
virtual Error notifyRemovingAllModules ()
Detailed Description
Plugin instances can be added to the ObjectLinkingLayer to receive callbacks when code is loaded or emitted, and when JITLink is being configured.
Definition at line 60 of file ObjectLinkingLayer.h.
Constructor & Destructor Documentation
~Plugin()
llvm::orc::ObjectLinkingLayer::Plugin::~Plugin () virtual
Definition at line 329 of file ObjectLinkingLayer.cpp.
Member Function Documentation
modifyPassConfig()
virtual void llvm::orc::ObjectLinkingLayer::Plugin::modifyPassConfig (MaterializationResponsibility & MR, const Triple & TT, jitlink::PassConfiguration & Config) inline virtual
Reimplemented in llvm::orc::EHFrameRegistrationPlugin.
Definition at line 63 of file ObjectLinkingLayer.h.
notifyEmitted()
virtual Error llvm::orc::ObjectLinkingLayer::Plugin::notifyEmitted (MaterializationResponsibility & MR) inline virtual
Reimplemented in llvm::orc::EHFrameRegistrationPlugin.
Definition at line 67 of file ObjectLinkingLayer.h.
References llvm::Error::success().
notifyLoaded()
virtual void llvm::orc::ObjectLinkingLayer::Plugin::notifyLoaded (MaterializationResponsibility & MR) inline virtual
Definition at line 66 of file ObjectLinkingLayer.h.
notifyRemovingAllModules()
virtual Error llvm::orc::ObjectLinkingLayer::Plugin::notifyRemovingAllModules () inline virtual
Reimplemented in llvm::orc::EHFrameRegistrationPlugin.
Definition at line 73 of file ObjectLinkingLayer.h.
References llvm::Error::success().
notifyRemovingModule()
virtual Error llvm::orc::ObjectLinkingLayer::Plugin::notifyRemovingModule (VModuleKey K) inline virtual
Reimplemented in llvm::orc::EHFrameRegistrationPlugin.
Definition at line 70 of file ObjectLinkingLayer.h.
References llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h
lib/ExecutionEngine/Orc/ObjectLinkingLayer.cpp