LLVM: llvm::mca::ExecuteStage Class Reference
llvm::mca::ExecuteStage Class Reference final
#include "llvm/MCA/Stages/ExecuteStage.h"
Public Member Functions
ExecuteStage (Scheduler &S)
ExecuteStage (Scheduler &S, bool ShouldPerformBottleneckAnalysis)
bool hasWorkToComplete () const override
Returns true if some instructions are still executing this stage.
bool isAvailable (const InstRef &IR) const override
Returns true if it can execute IR during this cycle.
Error cycleStart () override
Called once at the start of each cycle.
Error cycleEnd () override
Called once at the end of each cycle.
Error execute (InstRef &IR) override
The primary action that this stage performs on instruction IR.
void notifyInstructionIssued (const InstRef &IR, MutableArrayRef< std::pair< ResourceRef, ResourceCycles >> Used) const
void notifyInstructionExecuted (const InstRef &IR) const
void notifyInstructionPending (const InstRef &IR) const
void notifyInstructionReady (const InstRef &IR) const
void notifyResourceAvailable (const ResourceRef &RR) const
void notifyReservedOrReleasedBuffers (const InstRef &IR, bool Reserved) const
Public Member Functions inherited from llvm::mca::Stage
Stage ()
virtual ~Stage ()
void setNextInSequence (Stage *NextStage)
bool checkNextStage (const InstRef &IR) const
Error moveToTheNextStage (InstRef &IR)
Called when an instruction is ready to move the next pipeline stage.
void addListener (HWEventListener *Listener)
Add a listener to receive callbacks during the execution of this stage.
template<typename EventT >
void notifyEvent (const EventT &Event) const
Notify listeners of a particular hardware event.
Additional Inherited Members
Protected Member Functions inherited from llvm::mca::Stage
const std::set< HWEventListener * > & getListeners () const
Detailed Description
Definition at line 28 of file ExecuteStage.h.
Constructor & Destructor Documentation
ExecuteStage() [1/2]
llvm::mca::ExecuteStage::ExecuteStage (Scheduler & S) inline
Definition at line 50 of file ExecuteStage.h.
ExecuteStage() [2/2]
llvm::mca::ExecuteStage::ExecuteStage (Scheduler & S, bool ShouldPerformBottleneckAnalysis) inline
Definition at line 51 of file ExecuteStage.h.
Member Function Documentation
cycleEnd()
Error llvm::mca::ExecuteStage::cycleEnd () override virtual
Called once at the end of each cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 122 of file ExecuteStage.cpp.
References llvm::mca::Scheduler::analyzeDataDependencies(), llvm::mca::Scheduler::analyzeResourcePressure(), llvm::dbgs(), llvm::format_hex(), llvm::mca::Scheduler::hadTokenStall(), LLVM_DEBUG, llvm::BitmaskEnumDetail::Mask(), llvm::mca::HWPressureEvent::MEMORY_DEPS, llvm::mca::Stage::notifyEvent(), llvm::mca::HWPressureEvent::REGISTER_DEPS, llvm::mca::HWPressureEvent::RESOURCES, and llvm::SmallVectorBase::size().
Referenced by hasWorkToComplete().
cycleStart()
Error llvm::mca::ExecuteStage::cycleStart () override virtual
Called once at the start of each cycle.
This can be used as a setup phase to prepare for the executions during the cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 93 of file ExecuteStage.cpp.
References llvm::mca::Scheduler::cycleEvent(), llvm::mca::Stage::moveToTheNextStage(), notifyInstructionExecuted(), notifyInstructionPending(), notifyInstructionReady(), and notifyResourceAvailable().
Referenced by hasWorkToComplete().
execute()
Error llvm::mca::ExecuteStage::execute (InstRef & IR) override virtual
The primary action that this stage performs on instruction IR.
Implements llvm::mca::Stage.
Definition at line 186 of file ExecuteStage.cpp.
References assert(), llvm::mca::Scheduler::dispatch(), llvm::mca::InstRef::getInstruction(), llvm::mca::InstructionBase::getNumMicroOps(), isAvailable(), llvm::mca::Instruction::isEliminated(), llvm::mca::Instruction::isPending(), llvm::mca::Scheduler::mustIssueImmediately(), notifyInstructionPending(), notifyInstructionReady(), notifyReservedOrReleasedBuffers(), and llvm::mca::Scheduler::sanityCheck().
Referenced by hasWorkToComplete().
hasWorkToComplete()
bool llvm::mca::ExecuteStage::hasWorkToComplete () const inline override virtual
Returns true if some instructions are still executing this stage.
Implements llvm::mca::Stage.
Definition at line 61 of file ExecuteStage.h.
References cycleEnd(), cycleStart(), execute(), isAvailable(), notifyInstructionExecuted(), notifyInstructionIssued(), notifyInstructionPending(), notifyInstructionReady(), notifyReservedOrReleasedBuffers(), and notifyResourceAvailable().
isAvailable()
bool llvm::mca::ExecuteStage::isAvailable (const InstRef & IR) const override virtual
Returns true if it can execute IR during this cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 43 of file ExecuteStage.cpp.
References llvm::mca::InstRef::getInstruction(), llvm::mca::InstructionBase::getNumMicroOps(), I, IR, llvm::mca::Scheduler::isAvailable(), llvm::mca::Instruction::isExecuted(), llvm::mca::Scheduler::issueInstruction(), llvm::mca::Stage::moveToTheNextStage(), notifyInstructionExecuted(), notifyInstructionIssued(), notifyInstructionPending(), notifyInstructionReady(), notifyReservedOrReleasedBuffers(), llvm::mca::Scheduler::select(), and llvm::mca::toHWStallEventType().
Referenced by execute(), and hasWorkToComplete().
notifyInstructionExecuted()
void llvm::mca::ExecuteStage::notifyInstructionExecuted (const InstRef & IR) const
Definition at line 227 of file ExecuteStage.cpp.
References llvm::dbgs(), llvm::mca::HWInstructionEvent::Executed, and LLVM_DEBUG.
Referenced by cycleStart(), hasWorkToComplete(), isAvailable(), and llvm::mca::verifyInstructionEliminated().
notifyInstructionIssued()
void llvm::mca::ExecuteStage::notifyInstructionIssued (const InstRef & IR, MutableArrayRef< std::pair< ResourceRef, ResourceCycles >> Used) const
Definition at line 252 of file ExecuteStage.cpp.
References assert(), llvm::dbgs(), llvm::mca::Scheduler::getResourceID(), and LLVM_DEBUG.
Referenced by hasWorkToComplete(), isAvailable(), and llvm::mca::verifyInstructionEliminated().
notifyInstructionPending()
void llvm::mca::ExecuteStage::notifyInstructionPending (const InstRef & IR) const
Definition at line 233 of file ExecuteStage.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::mca::HWInstructionEvent::Pending.
Referenced by cycleStart(), execute(), hasWorkToComplete(), isAvailable(), and llvm::mca::verifyInstructionEliminated().
notifyInstructionReady()
void llvm::mca::ExecuteStage::notifyInstructionReady (const InstRef & IR) const
Definition at line 239 of file ExecuteStage.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::mca::HWInstructionEvent::Ready.
Referenced by cycleStart(), execute(), hasWorkToComplete(), isAvailable(), and llvm::mca::verifyInstructionEliminated().
notifyReservedOrReleasedBuffers()
void llvm::mca::ExecuteStage::notifyReservedOrReleasedBuffers (const InstRef & IR, bool Reserved) const
Definition at line 272 of file ExecuteStage.cpp.
References llvm::countPopulation(), E, llvm::mca::InstructionBase::getDesc(), llvm::mca::InstRef::getInstruction(), llvm::mca::Stage::getListeners(), llvm::mca::Scheduler::getResourceID(), I, llvm::SmallVectorBase::size(), and llvm::mca::InstrDesc::UsedBuffers.
Referenced by execute(), hasWorkToComplete(), and isAvailable().
notifyResourceAvailable()
void llvm::mca::ExecuteStage::notifyResourceAvailable (const ResourceRef & RR) const
Definition at line 245 of file ExecuteStage.cpp.
References llvm::dbgs(), llvm::mca::Stage::getListeners(), and LLVM_DEBUG.
Referenced by cycleStart(), and hasWorkToComplete().
The documentation for this class was generated from the following files:
include/llvm/MCA/Stages/ExecuteStage.h
lib/MCA/Stages/ExecuteStage.cpp