LLVM: llvm::orc::SpeculateQuery Class Reference
llvm::orc::SpeculateQuery Class Reference
#include "llvm/ExecutionEngine/Orc/SpeculateAnalyses.h"
Public Types
using ResultTy = Optional< DenseMap< StringRef, DenseSet< StringRef > >>
Protected Member Functions
void findCalles (const BasicBlock *, DenseSet< StringRef > &)
bool isStraightLine (const Function &F)
Detailed Description
Definition at line 27 of file SpeculateAnalyses.h.
Member Typedef Documentation
ResultTy
using llvm::orc::SpeculateQuery::ResultTy = Optional<DenseMap<StringRef, DenseSet<StringRef> >>
Definition at line 33 of file SpeculateAnalyses.h.
Member Function Documentation
findCalles()
void llvm::orc::SpeculateQuery::findCalles (const BasicBlock * BB, DenseSet< StringRef > & CallesNames) protected
Definition at line 52 of file SpeculateAnalyses.cpp.
References assert(), getCalledFunction(), llvm::BasicBlock::getTerminator(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), and llvm::BasicBlock::instructionsWithoutDebug().
Referenced by llvm::orc::BlockFreqQuery::operator()(), and llvm::orc::SequenceBBQuery::operator()().
isStraightLine()
bool llvm::orc::SpeculateQuery::isStraightLine (const Function & F) protected
Definition at line 69 of file SpeculateAnalyses.cpp.
References llvm::all_of(), and llvm::Function::getBasicBlockList().
Referenced by llvm::orc::SequenceBBQuery::operator()().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/SpeculateAnalyses.h
lib/ExecutionEngine/Orc/SpeculateAnalyses.cpp