LLVM: llvm::TypeSize Class Reference
llvm::TypeSize Class Reference
#include "llvm/Support/TypeSize.h"
Public Member Functions
constexpr TypeSize (uint64_t MinSize, bool Scalable)
TypeSize operator* (unsigned RHS) const
TypeSize operator/ (unsigned RHS) const
uint64_t getFixedSize () const
uint64_t getKnownMinSize () const
bool isScalable () const
bool isByteSized () const
operator uint64_t () const
TypeSize operator* (uint64_t RHS) const
TypeSize operator* (int RHS) const
TypeSize operator* (int64_t RHS) const
TypeSize operator/ (uint64_t RHS) const
TypeSize operator/ (int RHS) const
TypeSize operator/ (int64_t RHS) const
Static Public Member Functions
static constexpr TypeSize Fixed (uint64_t Size)
static constexpr TypeSize Scalable (uint64_t MinSize)
Friends
bool operator== (const TypeSize &LHS, const TypeSize &RHS)
bool operator!= (const TypeSize &LHS, const TypeSize &RHS)
bool operator< (const TypeSize &LHS, const TypeSize &RHS)
bool operator> (const TypeSize &LHS, const TypeSize &RHS)
bool operator<= (const TypeSize &LHS, const TypeSize &RHS)
bool operator>= (const TypeSize &LHS, const TypeSize &RHS)
TypeSize operator* (const unsigned LHS, const TypeSize &RHS)
TypeSize operator* (const uint64_t LHS, const TypeSize &RHS)
TypeSize operator* (const int LHS, const TypeSize &RHS)
TypeSize operator* (const int64_t LHS, const TypeSize &RHS)
Detailed Description
Definition at line 50 of file TypeSize.h.
Constructor & Destructor Documentation
TypeSize()
constexpr llvm::TypeSize::TypeSize (uint64_t MinSize, bool Scalable) inline
Definition at line 56 of file TypeSize.h.
Member Function Documentation
Fixed()
static constexpr TypeSize llvm::TypeSize::Fixed (uint64_t Size) inline static
Definition at line 59 of file TypeSize.h.
Referenced by llvm::Type::getPrimitiveSizeInBits(), llvm::MVT::getSizeInBits(), and llvm::DataLayout::getTypeSizeInBits().
getFixedSize()
uint64_t llvm::TypeSize::getFixedSize () const inline
Definition at line 124 of file TypeSize.h.
References assert().
Referenced by getNoopInput(), and llvm::StackOffset::operator+=().
getKnownMinSize()
uint64_t llvm::TypeSize::getKnownMinSize () const inline
Definition at line 132 of file TypeSize.h.
Referenced by llvm::alignTo(), FindMemType(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::DataLayout::getTypeStoreSize(), getUniformBase(), llvm::CastInst::isBitCastable(), LowerSVEIntrinsicEXT(), llvm::MemSDNode::MemSDNode(), llvm::StackOffset::operator+=(), performLD1GatherCombine(), performST1ScatterCombine(), llvm::FunctionLoweringInfo::set(), and tryToElideArgumentCopy().
isByteSized()
bool llvm::TypeSize::isByteSized () const inline
Definition at line 142 of file TypeSize.h.
Referenced by llvm::EVT::isByteSized(), and llvm::MVT::isByteSized().
isScalable()
bool llvm::TypeSize::isScalable () const inline
Definition at line 137 of file TypeSize.h.
Referenced by llvm::alignTo(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::DataLayout::getTypeStoreSize(), and llvm::StackOffset::operator+=().
operator uint64_t()
llvm::TypeSize::operator uint64_t () const inline
Definition at line 150 of file TypeSize.h.
operator*() [1/4]
TypeSize llvm::TypeSize::operator* (unsigned RHS) const inline
Definition at line 109 of file TypeSize.h.
operator*() [2/4]
TypeSize llvm::TypeSize::operator* (uint64_t RHS) const inline
Definition at line 156 of file TypeSize.h.
operator*() [3/4]
TypeSize llvm::TypeSize::operator* (int RHS) const inline
Definition at line 160 of file TypeSize.h.
operator*() [4/4]
TypeSize llvm::TypeSize::operator* (int64_t RHS) const inline
Definition at line 164 of file TypeSize.h.
operator/() [1/4]
TypeSize llvm::TypeSize::operator/ (unsigned RHS) const inline
Definition at line 117 of file TypeSize.h.
operator/() [2/4]
TypeSize llvm::TypeSize::operator/ (uint64_t RHS) const inline
Definition at line 180 of file TypeSize.h.
operator/() [3/4]
TypeSize llvm::TypeSize::operator/ (int RHS) const inline
Definition at line 184 of file TypeSize.h.
operator/() [4/4]
TypeSize llvm::TypeSize::operator/ (int64_t RHS) const inline
Definition at line 188 of file TypeSize.h.
Scalable()
static constexpr TypeSize llvm::TypeSize::Scalable (uint64_t MinSize) inline static
Definition at line 63 of file TypeSize.h.
Referenced by llvm::MVT::getSizeInBits().
Friends And Related Function Documentation
operator!=
bool operator!= (const TypeSize & LHS, const TypeSize & RHS) friend
Definition at line 75 of file TypeSize.h.
operator* [1/4]
TypeSize operator* (const unsigned LHS, const TypeSize & RHS) friend
Definition at line 113 of file TypeSize.h.
operator* [2/4]
TypeSize operator* (const uint64_t LHS, const TypeSize & RHS) friend
Definition at line 168 of file TypeSize.h.
operator* [3/4]
TypeSize operator* (const int LHS, const TypeSize & RHS) friend
Definition at line 172 of file TypeSize.h.
operator* [4/4]
TypeSize operator* (const int64_t LHS, const TypeSize & RHS) friend
Definition at line 176 of file TypeSize.h.
operator<
bool operator< (const TypeSize & LHS, const TypeSize & RHS) friend
Definition at line 88 of file TypeSize.h.
operator<=
bool operator<= (const TypeSize & LHS, const TypeSize & RHS) friend
Definition at line 99 of file TypeSize.h.
operator==
bool operator== (const TypeSize & LHS, const TypeSize & RHS) friend
Definition at line 70 of file TypeSize.h.
operator>
bool operator> (const TypeSize & LHS, const TypeSize & RHS) friend
Definition at line 95 of file TypeSize.h.
operator>=
bool operator>= (const TypeSize & LHS, const TypeSize & RHS) friend
Definition at line 103 of file TypeSize.h.
The documentation for this class was generated from the following file:
include/llvm/Support/TypeSize.h