LLVM: llvm::jitlink::EHFrameSplitter Class Reference
llvm::jitlink::EHFrameSplitter Class Reference
A LinkGraph pass that splits blocks in an eh-frame section into sub-blocks representing individual eh-frames.
#include "ExecutionEngine/JITLink/EHFrameSupportImpl.h"
Public Member Functions
EHFrameSplitter (StringRef EHFrameSectionName)
Error operator() (LinkGraph &G)
Detailed Description
A LinkGraph pass that splits blocks in an eh-frame section into sub-blocks representing individual eh-frames.
EHFrameSplitter should not be run without EHFrameEdgeFixer, which is responsible for adding FDE-to-CIE edges.
Definition at line 28 of file EHFrameSupportImpl.h.
Constructor & Destructor Documentation
EHFrameSplitter()
llvm::jitlink::EHFrameSplitter::EHFrameSplitter (StringRef EHFrameSectionName)
Definition at line 20 of file EHFrameSupport.cpp.
Member Function Documentation
operator()()
Error llvm::jitlink::EHFrameSplitter::operator() (LinkGraph & G)
Definition at line 23 of file EHFrameSupport.cpp.
References B, llvm::dbgs(), llvm::jitlink::LinkGraph::findSectionByName(), llvm::jitlink::Symbol::getOffset(), LLVM_DEBUG, llvm::sort(), and llvm::Error::success().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/EHFrameSupportImpl.h
lib/ExecutionEngine/JITLink/EHFrameSupport.cpp