LLVM: llvm::HexagonMCExpr Class Reference
llvm::HexagonMCExpr Class Reference
#include "Target/Hexagon/MCTargetDesc/HexagonMCExpr.h"
Public Member Functions
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
MCExpr const * getExpr () const
void setMustExtend (bool Val=true)
bool mustExtend () const
void setMustNotExtend (bool Val=true)
bool mustNotExtend () const
void setS27_2_reloc (bool Val=true)
bool s27_2_reloc () const
void setSignMismatch (bool Val=true)
bool signMismatch () const
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static HexagonMCExpr * create (MCExpr const *Expr, MCContext &Ctx)
static bool classof (MCExpr const *E)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary, Constant, SymbolRef, Unary,
Target
}
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
Detailed Description
Definition at line 16 of file HexagonMCExpr.h.
Member Function Documentation
classof()
bool HexagonMCExpr::classof (MCExpr const * E) static
Definition at line 101 of file HexagonMCExpr.cpp.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
create()
HexagonMCExpr * HexagonMCExpr::create (MCExpr const * Expr, MCContext & Ctx) static
Definition at line 22 of file HexagonMCExpr.cpp.
Referenced by GetSymbolRef(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), makeCombineInst(), and ScaleVectorOffset().
evaluateAsRelocatableImpl()
bool HexagonMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 26 of file HexagonMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable().
findAssociatedFragment()
MCFragment * llvm::HexagonMCExpr::findAssociatedFragment () const override virtual
Implements llvm::MCTargetExpr.
Definition at line 36 of file HexagonMCExpr.cpp.
References llvm::MCExpr::findAssociatedFragment().
fixELFSymbolsInTLSFixups()
void HexagonMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 77 of file HexagonMCExpr.cpp.
References fixELFSymbolsInTLSFixupsImpl(), and getExpr().
getExpr()
MCExpr const * HexagonMCExpr::getExpr () const
Definition at line 82 of file HexagonMCExpr.cpp.
Referenced by fixELFSymbolsInTLSFixups().
mustExtend()
bool HexagonMCExpr::mustExtend () const
Definition at line 89 of file HexagonMCExpr.cpp.
Referenced by llvm::HexagonMCInstrInfo::mustExtend().
mustNotExtend()
bool HexagonMCExpr::mustNotExtend () const
Definition at line 94 of file HexagonMCExpr.cpp.
Referenced by llvm::HexagonMCInstrInfo::mustNotExtend().
printImpl()
void HexagonMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 109 of file HexagonMCExpr.cpp.
References llvm::MCExpr::print().
s27_2_reloc()
bool HexagonMCExpr::s27_2_reloc () const
Definition at line 96 of file HexagonMCExpr.cpp.
Referenced by llvm::HexagonMCInstrInfo::s27_2_reloc().
setMustExtend()
void HexagonMCExpr::setMustExtend (bool Val = true)
Definition at line 84 of file HexagonMCExpr.cpp.
References assert().
Referenced by llvm::HexagonMCInstrInfo::setMustExtend().
setMustNotExtend()
void HexagonMCExpr::setMustNotExtend (bool Val = true)
Definition at line 90 of file HexagonMCExpr.cpp.
References assert().
Referenced by llvm::HexagonMCInstrInfo::setMustNotExtend().
setS27_2_reloc()
void HexagonMCExpr::setS27_2_reloc (bool Val = true)
Definition at line 97 of file HexagonMCExpr.cpp.
Referenced by llvm::HexagonMCInstrInfo::setS27_2_reloc().
setSignMismatch()
void HexagonMCExpr::setSignMismatch (bool Val = true)
Definition at line 113 of file HexagonMCExpr.cpp.
signMismatch()
bool HexagonMCExpr::signMismatch () const
Definition at line 117 of file HexagonMCExpr.cpp.
visitUsedExpr()
void HexagonMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 32 of file HexagonMCExpr.cpp.
References llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonMCExpr.h
lib/Target/Hexagon/MCTargetDesc/HexagonMCExpr.cpp