LLVM: llvm::Use Class Reference
llvm::Use Class Reference
A Use represents the edge between a Value definition and its users.
#include "llvm/IR/Use.h"
Classes
struct PrevPointerTraits
Pointer traits for the Prev PointerIntPair.
struct UserRefPointerTraits
Pointer traits for the UserRef PointerIntPair.
Public Types
using UserRef = PointerIntPair< User *, 1, unsigned, UserRefPointerTraits >
Public Member Functions
Use (const Use &U)=delete
void swap (Use &RHS)
Provide a fast substitute to std::swap<Use> that also works with less standard-compliant compilers.
operator Value * () const
Value * get () const
User * getUser () const LLVM_READONLY
Returns the User that contains this Use.
void set (Value *Val)
Value * operator= (Value *RHS)
const Use & operator= (const Use &RHS)
Value * operator-> ()
const Value * operator-> () const
Use * getNext () const
unsigned getOperandNo () const
Return the operand # of this use in its User.
Static Public Member Functions
static Use * initTags (Use *Start, Use *Stop)
Initializes the waymarking tags on an array of Uses.
static void zap (Use *Start, const Use *Stop, bool del=false)
Destroys Use operands when the number of operands of a User changes.
Friends
class Value
Detailed Description
A Use represents the edge between a Value definition and its users.
This is notionally a two-dimensional linked list. It supports traversing all of the uses for a particular value definition. It also supports jumping directly to the used value when we arrive from the User's operands, and jumping directly to the User when we arrive from the Value's uses.
The pointer to the used Value is explicit, and the pointer to the User is implicit. The implicit pointer is found via a waymarking algorithm described in the programmer's manual:
http://www.llvm.org/docs/ProgrammersManual.html#the-waymarking-algorithm
This is essentially the single most memory intensive object in LLVM because of the number of uses in the system. At the same time, the constant time operations it allows are essential to many optimizations having reasonable time complexity.
Definition at line 55 of file Use.h.
Member Typedef Documentation
UserRef
using llvm::Use::UserRef = PointerIntPair<User *, 1, unsigned, UserRefPointerTraits>
Definition at line 77 of file Use.h.
Constructor & Destructor Documentation
Use()
llvm::Use::Use (const Use & U) delete
Member Function Documentation
get()
Value* llvm::Use::get () const inline
Definition at line 107 of file Use.h.
References getUser(), LLVM_READONLY, and operator=().
Referenced by llvm::Attributor::checkForAllCallSites(), createCallInst(), llvm::IRPosition::getAttrs(), llvm::simplify_type< Use >::getSimplifiedValue(), llvm::simplify_type< const Use >::getSimplifiedValue(), getStartOrEndSlot(), llvm::DivergenceAnalysis::isDivergentUse(), operandWithNewAddressSpaceOrCreateUndef(), processCallSite(), llvm::SSAUpdater::RewriteUse(), and ShrinkDemandedConstant().
getNext()
Use* llvm::Use::getNext () const inline
Definition at line 123 of file Use.h.
References getOperandNo(), and initTags().
getOperandNo()
unsigned llvm::Use::getOperandNo () const
Return the operand # of this use in its User.
Definition at line 47 of file Use.cpp.
References getUser(), and llvm::User::op_begin().
Referenced by allUsesTruncate(), createCallInst(), getNext(), isCompatibleReplacement(), isSimplePointerUseValidToReplace(), tryFoldInst(), and tryToFoldACImm().
getUser()
User * llvm::Use::getUser () const
Returns the User that contains this Use.
For an instruction operand, for example, this will return the instruction.
Definition at line 40 of file Use.cpp.
Referenced by llvm::MemorySSAUpdater::applyInsertUpdates(), llvm::Attributor::checkForAllCallSites(), contains(), createCallInst(), llvm::deleteDeadLoop(), llvm::DominatorTree::dominates(), llvm::MemorySSA::dominates(), eliminateSwiftErrorAlloca(), foldXorToXor(), get(), llvm::IRPosition::getAttrs(), GetCaseResults(), llvm::MemoryPhi::getIncomingBlock(), llvm::PHINode::getIncomingBlock(), getOperandNo(), getRetComponentType(), getSignature(), INITIALIZE_PASS(), llvm::MemorySSAUpdater::insertDef(), isDirectCall(), llvm::DivergenceAnalysis::isDivergentUse(), isProfitableForVectorization(), llvm::DominatorTree::isReachableFromEntry(), isSimplePointerUseValidToReplace(), OptimizeGlobalAddressOfMalloc(), PushArgMD(), llvm::MemorySSAUpdater::removeMemoryAccess(), replaceAllUsesOfWithIn(), llvm::replaceDbgValueForAlloca(), llvm::replaceNonLocalUsesWith(), replacePrepare(), llvm::Value::replaceUsesOutsideBlock(), RetagMask(), llvm::SSAUpdater::RewriteUse(), llvm::SSAUpdater::RewriteUseAfterInsertions(), RewriteUsesOfClonedInstructions(), runAttributorOnModule(), simplifyLoopInst(), sinkInstruction(), and llvm::sroa::AllocaSliceRewriter::visit().
initTags()
Use * llvm::Use::initTags (Use * Start, Use * Stop) static
Initializes the waymarking tags on an array of Uses.
This sets up the array of Uses such that getUser() can find the User from any of those Uses.
Definition at line 56 of file Use.cpp.
Referenced by getNext().
operator Value *()
llvm::Use::operator Value * () const inline
Definition at line 106 of file Use.h.
operator->() [1/2]
Value* llvm::Use::operator-> () inline
Definition at line 120 of file Use.h.
operator->() [2/2]
const Value* llvm::Use::operator-> () const inline
Definition at line 121 of file Use.h.
operator=() [1/2]
Value * llvm::Use::operator= (Value * RHS) inline
Definition at line 736 of file Value.h.
Referenced by get().
operator=() [2/2]
const Use & llvm::Use::operator= (const Use & RHS) inline
Definition at line 741 of file Value.h.
set()
void llvm::Use::set (Value * Val) inline
Definition at line 730 of file Value.h.
References llvm::Value::addUse().
Referenced by llvm::MemorySSAUpdater::applyInsertUpdates(), contains(), createCallInst(), llvm::deleteDeadLoop(), llvm::GVNExpression::Expression::dump(), eliminateSwiftErrorAlloca(), isDirectCall(), isProfitableForVectorization(), processCallSite(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), llvm::MemorySSAUpdater::removeMemoryAccess(), replaceDominatedUsesWith(), llvm::replaceNonLocalUsesWith(), llvm::Value::replaceUsesWithIf(), llvm::SSAUpdater::RewriteUse(), llvm::SSAUpdater::RewriteUseAfterInsertions(), simplifyLoopInst(), and sinkLastInstruction().
swap()
void llvm::Use::swap (Use & RHS)
Provide a fast substitute to std::swap<Use> that also works with less standard-compliant compilers.
Definition at line 16 of file Use.cpp.
References llvm::Value::addUse().
zap()
void llvm::Use::zap (Use * Start, const Use * Stop, bool del = false) static
Destroys Use operands when the number of operands of a User changes.
Definition at line 86 of file Use.cpp.
Referenced by llvm::User::growHungoffUses(), and llvm::User::operator delete().
Friends And Related Function Documentation
Value
friend class Value friend
Definition at line 104 of file Use.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Use.h
include/llvm/IR/Value.h
lib/IR/Use.cpp