LLVM: llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl Class Reference
llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl Class Reference
Public Member Functions
~WindowsManifestMergerImpl ()
Error merge (const MemoryBuffer &Manifest)
std::unique_ptr< MemoryBuffer > getMergedManifest ()
Detailed Description
Definition at line 35 of file WindowsManifestMerger.cpp.
Constructor & Destructor Documentation
~WindowsManifestMergerImpl()
llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::~WindowsManifestMergerImpl ()
Definition at line 617 of file WindowsManifestMerger.cpp.
Referenced by llvm::windows_manifest::isAvailable().
Member Function Documentation
getMergedManifest()
std::unique_ptr< MemoryBuffer > llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest ()
Definition at line 659 of file WindowsManifestMerger.cpp.
References assert(), checkAndStripPrefixes(), FROM_XML_CHAR, and llvm::MemoryBuffer::getMemBufferCopy().
Referenced by llvm::windows_manifest::isAvailable().
merge()
Error llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge (const MemoryBuffer & Manifest)
Definition at line 622 of file WindowsManifestMerger.cpp.
References E, llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), hasRecognizedNamespace(), isMergeableElement(), setAttributeNamespaces(), stripComments(), llvm::Error::success(), treeMerge(), and xmlStringsEqual().
Referenced by llvm::windows_manifest::isAvailable().
The documentation for this class was generated from the following file:
lib/WindowsManifest/WindowsManifestMerger.cpp