LLVM: llvm::AMDGPUMCCodeEmitter Class Reference
llvm::AMDGPUMCCodeEmitter Class Reference
#include "Target/AMDGPU/MCTargetDesc/AMDGPUMCCodeEmitter.h"
Public Member Functions
uint64_t getBinaryCodeForInstr (const MCInst &MI, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
virtual uint64_t getMachineOpValue (const MCInst &MI, const MCOperand &MO, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
virtual unsigned getSOPPBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
virtual unsigned getSDWASrcEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
virtual unsigned getSDWAVopcDstEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
virtual unsigned getAVOperandEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
Public Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter (const MCCodeEmitter &)=delete
MCCodeEmitter & operator= (const MCCodeEmitter &)=delete
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
virtual void emitPrefix (const MCInst &Inst, raw_ostream &OS, const MCSubtargetInfo &STI) const
Emit the prefixes of given instruction on the output stream.
virtual void encodeInstruction (const MCInst &Inst, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const =0
EncodeInstruction - Encode the given Inst to bytes on the output stream OS.
Protected Member Functions
AMDGPUMCCodeEmitter (const MCInstrInfo &mcii)
FeatureBitset computeAvailableFeatures (const FeatureBitset &FB) const
void verifyInstructionPredicates (const MCInst &MI, const FeatureBitset &AvailableFeatures) const
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Protected Attributes
const MCInstrInfo & MCII
Detailed Description
Definition at line 28 of file AMDGPUMCCodeEmitter.h.
Constructor & Destructor Documentation
AMDGPUMCCodeEmitter()
llvm::AMDGPUMCCodeEmitter::AMDGPUMCCodeEmitter (const MCInstrInfo & mcii) inline protected
Definition at line 34 of file AMDGPUMCCodeEmitter.h.
References getBinaryCodeForInstr(), and MI.
Member Function Documentation
computeAvailableFeatures()
FeatureBitset llvm::AMDGPUMCCodeEmitter::computeAvailableFeatures (const FeatureBitset & FB) const protected
Referenced by getAVOperandEncoding().
getAVOperandEncoding()
virtual unsigned llvm::AMDGPUMCCodeEmitter::getAVOperandEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline virtual
Definition at line 66 of file AMDGPUMCCodeEmitter.h.
References computeAvailableFeatures(), and verifyInstructionPredicates().
getBinaryCodeForInstr()
uint64_t llvm::AMDGPUMCCodeEmitter::getBinaryCodeForInstr (const MCInst & MI, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Referenced by AMDGPUMCCodeEmitter().
getMachineOpValue()
virtual uint64_t llvm::AMDGPUMCCodeEmitter::getMachineOpValue (const MCInst & MI, const MCOperand & MO, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline virtual
Definition at line 42 of file AMDGPUMCCodeEmitter.h.
getSDWASrcEncoding()
virtual unsigned llvm::AMDGPUMCCodeEmitter::getSDWASrcEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline virtual
Definition at line 54 of file AMDGPUMCCodeEmitter.h.
getSDWAVopcDstEncoding()
virtual unsigned llvm::AMDGPUMCCodeEmitter::getSDWAVopcDstEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline virtual
Definition at line 60 of file AMDGPUMCCodeEmitter.h.
getSOPPBrEncoding()
virtual unsigned llvm::AMDGPUMCCodeEmitter::getSOPPBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline virtual
Definition at line 48 of file AMDGPUMCCodeEmitter.h.
verifyInstructionPredicates()
void llvm::AMDGPUMCCodeEmitter::verifyInstructionPredicates (const MCInst & MI, const FeatureBitset & AvailableFeatures) const protected
Referenced by getAVOperandEncoding().
Member Data Documentation
MCII
const MCInstrInfo& llvm::AMDGPUMCCodeEmitter::MCII protected
Definition at line 32 of file AMDGPUMCCodeEmitter.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCCodeEmitter.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCCodeEmitter.cpp