LLVM: llvm::PrintIRInstrumentation Class Reference
llvm::PrintIRInstrumentation Class Reference
Instrumentation to print IR before/after passes.
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
PrintIRInstrumentation ()=default
~PrintIRInstrumentation ()
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Detailed Description
Instrumentation to print IR before/after passes.
Needs state to be able to print module after pass that invalidates IR unit (typically Loop or SCC).
Definition at line 33 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
PrintIRInstrumentation()
llvm::PrintIRInstrumentation::PrintIRInstrumentation () default
~PrintIRInstrumentation()
PrintIRInstrumentation::~PrintIRInstrumentation ()
Definition at line 146 of file StandardInstrumentations.cpp.
References assert(), llvm::StringRef::contains(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), llvm::forcePrintModuleIR(), llvm::formatv(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::shouldPrintAfterPass(), llvm::shouldPrintBeforePass(), and llvm::StringRef::startswith().
Member Function Documentation
registerCallbacks()
void PrintIRInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 221 of file StandardInstrumentations.cpp.
References llvm::forcePrintModuleIR(), P, llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforePassCallback(), llvm::shouldPrintAfterPass(), and llvm::shouldPrintBeforePass().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp