LLVM: llvm::GVNExpression::CallExpression Class Reference
llvm::GVNExpression::CallExpression Class Reference final
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Member Functions
CallExpression (unsigned NumOperands, CallInst *C, const MemoryAccess *MemoryLeader)
CallExpression ()=delete
CallExpression (const CallExpression &)=delete
CallExpression & operator= (const CallExpression &)=delete
~CallExpression () override
void printInternal (raw_ostream &OS, bool PrintEType) const override
Public Member Functions inherited from llvm::GVNExpression::MemoryExpression
MemoryExpression (unsigned NumOperands, enum ExpressionType EType, const MemoryAccess *MemoryLeader)
MemoryExpression ()=delete
MemoryExpression (const MemoryExpression &)=delete
MemoryExpression & operator= (const MemoryExpression &)=delete
hash_code getHashValue () const override
bool equals (const Expression &Other) const override
const MemoryAccess * getMemoryLeader () const
void setMemoryLeader (const MemoryAccess *ML)
Public Member Functions inherited from llvm::GVNExpression::BasicExpression
BasicExpression (unsigned NumOperands)
BasicExpression (unsigned NumOperands, ExpressionType ET)
BasicExpression ()=delete
BasicExpression (const BasicExpression &)=delete
BasicExpression & operator= (const BasicExpression &)=delete
~BasicExpression () override
void swapOperands (unsigned First, unsigned Second)
Swap two operands.
Value * getOperand (unsigned N) const
void setOperand (unsigned N, Value *V)
unsigned getNumOperands () const
op_iterator op_begin ()
op_iterator op_end ()
const_op_iterator op_begin () const
const_op_iterator op_end () const
iterator_range< op_iterator > operands ()
iterator_range< const_op_iterator > operands () const
void op_push_back (Value *Arg)
bool op_empty () const
void allocateOperands (RecyclerType &Recycler, BumpPtrAllocator &Allocator)
void deallocateOperands (RecyclerType &Recycler)
void setType (Type *T)
Type * getType () const
Public Member Functions inherited from llvm::GVNExpression::Expression
Expression (ExpressionType ET=ET_Base, unsigned O=~2U)
Expression (const Expression &)=delete
Expression & operator= (const Expression &)=delete
virtual ~Expression ()
bool operator!= (const Expression &Other) const
bool operator== (const Expression &Other) const
hash_code getComputedHash () const
virtual bool exactlyEquals (const Expression &Other) const
unsigned getOpcode () const
void setOpcode (unsigned opcode)
ExpressionType getExpressionType () const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::MemoryExpression
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::BasicExpression
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::Expression
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
Additional Inherited Members
Public Types inherited from llvm::GVNExpression::BasicExpression
using op_iterator = Value **
using const_op_iterator = Value *const *
Detailed Description
Definition at line 296 of file GVNExpression.h.
Constructor & Destructor Documentation
CallExpression() [1/3]
llvm::GVNExpression::CallExpression::CallExpression (unsigned NumOperands, CallInst * C, const MemoryAccess * MemoryLeader) inline
Definition at line 301 of file GVNExpression.h.
References llvm::GVNExpression::Expression::operator=().
CallExpression() [2/3]
llvm::GVNExpression::CallExpression::CallExpression () delete
CallExpression() [3/3]
llvm::GVNExpression::CallExpression::CallExpression (const CallExpression &) delete
~CallExpression()
llvm::GVNExpression::CallExpression::~CallExpression () override default
Member Function Documentation
classof()
static bool llvm::GVNExpression::CallExpression::classof (const Expression * EB) inline static
Definition at line 309 of file GVNExpression.h.
References llvm::GVNExpression::ET_Call, and llvm::GVNExpression::Expression::getExpressionType().
operator=()
CallExpression& llvm::GVNExpression::CallExpression::operator= (const CallExpression &) delete
printInternal()
void llvm::GVNExpression::CallExpression::printInternal (raw_ostream & OS, bool PrintEType) const inline override virtual
Reimplemented from llvm::GVNExpression::BasicExpression.
Definition at line 314 of file GVNExpression.h.
References llvm::Value::printAsOperand(), and llvm::GVNExpression::BasicExpression::printInternal().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/GVNExpression.h
lib/Transforms/Scalar/NewGVN.cpp