LLVM: llvm::BasicAAResult Class Reference
llvm::BasicAAResult Class Reference
This is the AA result object for the basic, local, and stateless alias analysis.
#include "llvm/Analysis/BasicAliasAnalysis.h"
Public Member Functions
BasicAAResult (const DataLayout &DL, const Function &F, const TargetLibraryInfo &TLI, AssumptionCache &AC, DominatorTree *DT=nullptr, LoopInfo *LI=nullptr, PhiValues *PV=nullptr)
BasicAAResult (const BasicAAResult &Arg)
BasicAAResult (BasicAAResult &&Arg)
bool invalidate (Function &Fn, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation events in the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
Checks to see if the specified callsite can clobber the specified memory object.
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
Chases pointers until we find a (constant global) or not.
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
Get the location associated with a pointer argument of a callsite.
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
Returns the behavior when calling the given call site.
FunctionModRefBehavior getModRefBehavior (const Function *Fn)
Returns the behavior when calling the given function.
Public Member Functions inherited from llvm::AAResultBase< DerivedT >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< DerivedT >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
This is the AA result object for the basic, local, and stateless alias analysis.
It implements the AA query interface in an entirely stateless manner. As one consequence, it is never invalidated due to IR changes. While it does retain some storage, that is used as an optimization and not to preserve information from query to query. However it does retain handles to various other analyses and must be recomputed when those analyses are.
Definition at line 54 of file BasicAliasAnalysis.h.
Constructor & Destructor Documentation
BasicAAResult() [1/3]
llvm::BasicAAResult::BasicAAResult (const DataLayout & DL, const Function & F, const TargetLibraryInfo & TLI, AssumptionCache & AC, DominatorTree * DT = nullptr, LoopInfo * LI = nullptr, PhiValues * PV = nullptr) inline
Definition at line 66 of file BasicAliasAnalysis.h.
Referenced by llvm::BasicAA::run().
BasicAAResult() [2/3]
llvm::BasicAAResult::BasicAAResult (const BasicAAResult & Arg) inline
Definition at line 73 of file BasicAliasAnalysis.h.
BasicAAResult() [3/3]
llvm::BasicAAResult::BasicAAResult (BasicAAResult && Arg) inline
Definition at line 76 of file BasicAliasAnalysis.h.
References alias(), llvm::Depth, getArgModRefInfo(), getModRefBehavior(), getModRefInfo(), invalidate(), llvm::operator!=(), llvm::operator==(), llvm::Other, pointsToConstantMemory(), SI, and llvm::NVPTX::PTXLdStInstCode::V2.
Member Function Documentation
alias()
AliasResult BasicAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 840 of file BasicAliasAnalysis.cpp.
References llvm::MemoryLocation::AATags, llvm::AAQueryInfo::AliasCache, assert(), llvm::SmallPtrSetImplBase::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), notDifferentParent(), llvm::MemoryLocation::Ptr, and llvm::MemoryLocation::Size.
Referenced by BasicAAResult(), and getModRefInfo().
getArgModRefInfo()
ModRefInfo BasicAAResult::getArgModRefInfo (const CallBase * Call, unsigned ArgIdx)
Get the location associated with a pointer argument of a callsite.
Definition at line 797 of file BasicAliasAnalysis.cpp.
References llvm::AAResultBase< DerivedT >::getArgModRefInfo(), isWriteOnlyParam(), llvm::Mod, llvm::NoModRef, llvm::CallBase::paramHasAttr(), and llvm::Ref.
Referenced by BasicAAResult().
getModRefBehavior() [1/2]
FunctionModRefBehavior BasicAAResult::getModRefBehavior (const CallBase * Call)
Returns the behavior when calling the given call site.
Definition at line 714 of file BasicAliasAnalysis.cpp.
References llvm::CallBase::doesNotAccessMemory(), llvm::CallBase::doesNotReadMemory(), llvm::FMRB_DoesNotAccessMemory, llvm::FMRB_DoesNotReadMemory, llvm::FMRB_OnlyAccessesArgumentPointees, llvm::FMRB_OnlyAccessesInaccessibleMem, llvm::FMRB_OnlyAccessesInaccessibleOrArgMem, llvm::FMRB_OnlyReadsMemory, llvm::FMRB_UnknownModRefBehavior, llvm::AAResultBase< DerivedT >::getBestAAResults(), llvm::CallBase::getCalledFunction(), llvm::AAResultBase< DerivedT >::AAResultsProxy::getModRefBehavior(), llvm::CallBase::hasOperandBundles(), llvm::CallBase::onlyAccessesArgMemory(), llvm::CallBase::onlyAccessesInaccessibleMemOrArgMem(), llvm::CallBase::onlyAccessesInaccessibleMemory(), and llvm::CallBase::onlyReadsMemory().
Referenced by BasicAAResult(), and getModRefInfo().
getModRefBehavior() [2/2]
FunctionModRefBehavior BasicAAResult::getModRefBehavior (const Function * F)
Returns the behavior when calling the given function.
For use when the call site is not known.
Definition at line 748 of file BasicAliasAnalysis.cpp.
References llvm::Function::doesNotAccessMemory(), llvm::Function::doesNotReadMemory(), llvm::FMRB_DoesNotAccessMemory, llvm::FMRB_DoesNotReadMemory, llvm::FMRB_OnlyAccessesArgumentPointees, llvm::FMRB_OnlyAccessesInaccessibleMem, llvm::FMRB_OnlyAccessesInaccessibleOrArgMem, llvm::FMRB_OnlyReadsMemory, llvm::FMRB_UnknownModRefBehavior, llvm::Function::onlyAccessesArgMemory(), llvm::Function::onlyAccessesInaccessibleMemOrArgMem(), llvm::Function::onlyAccessesInaccessibleMemory(), and llvm::Function::onlyReadsMemory().
getModRefInfo() [1/2]
ModRefInfo BasicAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Checks to see if the specified callsite can clobber the specified memory object.
Since we only look at local properties of this function, we really can't say much about this query. We do, however, use simple "address taken" analysis on local objects.
Definition at line 870 of file BasicAliasAnalysis.cpp.
References alias(), llvm::AAResultBase< DerivedT >::AAResultsProxy::alias(), assert(), llvm::clearMust(), llvm::CallBase::data_operands_begin(), llvm::CallBase::data_operands_end(), llvm::CallBase::doesNotAccessMemory(), llvm::CallBase::doesNotCapture(), llvm::CallBase::doesNotReadMemory(), llvm::AAResultBase< DerivedT >::getBestAAResults(), llvm::MemoryLocation::getForDest(), llvm::MemoryLocation::getForSource(), llvm::AAResultBase< DerivedT >::getModRefInfo(), llvm::CallBase::getNumArgOperands(), llvm::GetUnderlyingObject(), llvm::CallBase::isByValArgument(), llvm::AAQueryInfo::IsCapturedCache, isIntrinsicCall(), llvm::isMallocOrCallocLikeFn(), llvm::isModAndRefSet(), llvm::isNoModRef(), isNonEscapingLocalObject(), llvm::Mod, llvm::ModRef, llvm::MustAlias, llvm::NoAlias, llvm::NoModRef, notDifferentParent(), llvm::CallBase::onlyReadsMemory(), llvm::MemoryLocation::Ptr, llvm::Ref, llvm::setMod(), llvm::setMust(), and llvm::setRef().
Referenced by BasicAAResult().
getModRefInfo() [2/2]
ModRefInfo BasicAAResult::getModRefInfo (const CallBase * Call1, const CallBase * Call2, AAQueryInfo & AAQI)
Definition at line 1047 of file BasicAliasAnalysis.cpp.
References llvm::createModRefInfo(), getModRefBehavior(), llvm::AAResultBase< DerivedT >::getModRefInfo(), isIntrinsicCall(), llvm::isModSet(), llvm::Mod, llvm::NoModRef, and llvm::Ref.
invalidate()
bool BasicAAResult::invalidate (Function & Fn, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Handle invalidation events in the new pass manager.
Definition at line 98 of file BasicAliasAnalysis.cpp.
References llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
Referenced by BasicAAResult().
pointsToConstantMemory()
bool BasicAAResult::pointsToConstantMemory (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool OrLocal)
Chases pointers until we find a (constant global) or not.
Returns whether the given pointer value points to memory that is local to the function, with global constants being considered local to all functions.
Definition at line 654 of file BasicAliasAnalysis.cpp.
References assert(), llvm::SmallVectorBase::empty(), llvm::GetUnderlyingObject(), llvm::AAResultBase< DerivedT >::pointsToConstantMemory(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MemoryLocation::Ptr, llvm::SmallVectorTemplateBase< T >::push_back(), and SI.
Referenced by BasicAAResult().
The documentation for this class was generated from the following files:
include/llvm/Analysis/BasicAliasAnalysis.h
lib/Analysis/BasicAliasAnalysis.cpp