LLVM: llvm::sampleprof::SampleProfileReader Class Reference
llvm::sampleprof::SampleProfileReader Class Reference abstract
Sample-based profile reader.
#include "llvm/ProfileData/SampleProfReader.h"
Public Member Functions
SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
virtual ~SampleProfileReader ()=default
virtual std::error_code readHeader ()=0
Read and validate the file header.
std::error_code read ()
The interface to read sample profiles from the associated file.
virtual std::error_code readImpl ()=0
The implementaion to read sample profiles from the associated file.
void dumpFunctionProfile (StringRef FName, raw_ostream &OS=dbgs())
Print the profile for FName on stream OS.
virtual void collectFuncsFrom (const Module &M)
void dump (raw_ostream &OS=dbgs())
Print all the profiles on stream OS.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
FunctionSamples * getOrCreateSamplesFor (const Function &F)
Return the samples collected for function F, create empty FunctionSamples if it doesn't exist.
virtual FunctionSamples * getSamplesFor (StringRef Fname)
Return the samples collected for function F.
StringMap< FunctionSamples > & getProfiles ()
Return all the profiles.
void reportError (int64_t LineNumber, Twine Msg) const
Report a parse error message.
ProfileSummary & getSummary () const
Return the profile summary.
MemoryBuffer * getBuffer () const
SampleProfileFormat getFormat () const
Return the profile format.
virtual std::unique_ptr< ProfileSymbolList > getProfileSymbolList ()
virtual std::vector< StringRef > * getNameTable ()
It includes all the names that have samples either in outline instance or inline instance.
virtual bool dumpSectionInfo (raw_ostream &OS=dbgs())
Static Public Member Functions
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (const std::string Filename, LLVMContext &C, const std::string RemapFilename="")
Create a sample profile reader appropriate to the file format.
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (std::unique_ptr< MemoryBuffer > &B, LLVMContext &C, const std::string RemapFilename="")
Create a sample profile reader from the supplied memory buffer.
Protected Member Functions
void computeSummary ()
Compute summary for this profile.
Static Protected Member Functions
static std::unique_ptr< ProfileSummary > takeSummary (SampleProfileReader &Reader)
Take ownership of the summary of this reader.
Protected Attributes
StringMap< FunctionSamples > Profiles
Map every function to its associated profile.
LLVMContext & Ctx
LLVM context used to emit diagnostics.
std::unique_ptr< MemoryBuffer > Buffer
Memory buffer holding the profile file.
std::unique_ptr< ProfileSummary > Summary
Profile summary information.
std::unique_ptr< SampleProfileReaderItaniumRemapper > Remapper
SampleProfileFormat Format = SPF_None
The format of sample.
Detailed Description
Sample-based profile reader.
Each profile contains sample counts for all the functions executed. Inside each function, statements are annotated with the collected samples on all the instructions associated with that statement.
For this to produce meaningful data, the program needs to be compiled with some debug information (at minimum, line numbers: -gline-tables-only). Otherwise, it will be impossible to match IR instructions to the line numbers collected by the profiler.
From the profile file, we are interested in collecting the following information:
A list of functions included in the profile (mangled names).
For each function F:
The total number of samples collected in F.
The samples collected at each line in F. To provide some protection against source code shuffling, line numbers should be relative to the start of the function.
The reader supports two file formats: text and binary. The text format is useful for debugging and testing, while the binary format is more compact and I/O efficient. They can both be used interchangeably.
Definition at line 321 of file SampleProfReader.h.
Constructor & Destructor Documentation
SampleProfileReader()
llvm::sampleprof::SampleProfileReader::SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext & C, SampleProfileFormat Format = SPF_None) inline
Definition at line 323 of file SampleProfReader.h.
~SampleProfileReader()
virtual llvm::sampleprof::SampleProfileReader::~SampleProfileReader () virtual default
Member Function Documentation
collectFuncsFrom()
virtual void llvm::sampleprof::SampleProfileReader::collectFuncsFrom (const Module & M) inline virtual
Reimplemented in llvm::sampleprof::SampleProfileReaderCompactBinary, and llvm::sampleprof::SampleProfileReaderExtBinary.
Definition at line 347 of file SampleProfReader.h.
References llvm::dbgs(), and llvm::dump().
computeSummary()
void SampleProfileReader::computeSummary () protected
Compute summary for this profile.
Definition at line 1370 of file SampleProfReader.cpp.
References llvm::SampleProfileSummaryBuilder::addRecord(), llvm::ProfileSummaryBuilder::DefaultCutoffs, llvm::SampleProfileSummaryBuilder::getSummary(), I, Profiles, and Summary.
Referenced by llvm::sampleprof::SampleProfileReaderGCC::readFunctionProfiles(), and llvm::sampleprof::SampleProfileReaderText::readImpl().
create() [1/2]
ErrorOr< std::unique_ptr< SampleProfileReader > > SampleProfileReader::create (const std::string Filename, LLVMContext & C, const std::string RemapFilename = "") static
Create a sample profile reader appropriate to the file format.
Create a sample profile reader based on the format of the input file.
Create a remapper underlying if RemapFilename is not empty.
Parameters
Filename The file to open.
C The LLVM context to use to emit diagnostics.
RemapFilename The file used for profile remapping.
Returns
an error code indicating the status of the created reader.
Definition at line 1266 of file SampleProfReader.cpp.
References C, and setupMemoryBuffer().
Referenced by llvm::sampleprof::SampleProfileReaderItaniumRemapper::create().
create() [2/2]
ErrorOr< std::unique_ptr< SampleProfileReader > > SampleProfileReader::create (std::unique_ptr< MemoryBuffer > & B, LLVMContext & C, const std::string RemapFilename = "") static
Create a sample profile reader from the supplied memory buffer.
Create a sample profile reader based on the format of the input data.
Create a remapper underlying if RemapFilename is not empty.
Parameters
B The memory buffer to create the reader from (assumes ownership).
C The LLVM context to use to emit diagnostics.
RemapFilename The file used for profile remapping.
Returns
an error code indicating the status of the created reader.
Definition at line 1333 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::LLVMContext::diagnose(), llvm::sampleprof::FunctionSamples::Format, llvm::sampleprof::SampleProfileReaderText::hasFormat(), llvm::sampleprof::SampleProfileReaderRawBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderExtBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderCompactBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderGCC::hasFormat(), and llvm::unrecognized_format.
dump()
void SampleProfileReader::dump (raw_ostream & OS = dbgs())
Print all the profiles on stream OS.
Dump all the function profiles found on stream OS.
Definition at line 57 of file SampleProfReader.cpp.
References dumpFunctionProfile(), I, and Profiles.
dumpFunctionProfile()
void SampleProfileReader::dumpFunctionProfile (StringRef FName, raw_ostream & OS = dbgs())
Print the profile for FName on stream OS.
Dump the function profile for FName.
Parameters
FName Name of the function to print.
OS Stream to emit the output to.
Definition at line 51 of file SampleProfReader.cpp.
References Profiles.
Referenced by dump().
dumpSectionInfo()
virtual bool llvm::sampleprof::SampleProfileReader::dumpSectionInfo (raw_ostream & OS = dbgs()) inline virtual
Reimplemented in llvm::sampleprof::SampleProfileReaderExtBinaryBase.
Definition at line 420 of file SampleProfReader.h.
getBuffer()
MemoryBuffer* llvm::sampleprof::SampleProfileReader::getBuffer () const inline
Definition at line 408 of file SampleProfReader.h.
getFormat()
SampleProfileFormat llvm::sampleprof::SampleProfileReader::getFormat () const inline
Return the profile format.
Definition at line 411 of file SampleProfReader.h.
getNameTable()
virtual std::vector<StringRef>* llvm::sampleprof::SampleProfileReader::getNameTable () inline virtual
It includes all the names that have samples either in outline instance or inline instance.
Reimplemented in llvm::sampleprof::SampleProfileReaderBinary.
Definition at line 419 of file SampleProfReader.h.
getOrCreateSamplesFor()
FunctionSamples* llvm::sampleprof::SampleProfileReader::getOrCreateSamplesFor (const Function & F) inline
Return the samples collected for function F, create empty FunctionSamples if it doesn't exist.
Definition at line 363 of file SampleProfReader.h.
References llvm::sampleprof::FunctionSamples::getCanonicalFnName(), and llvm::sampleprof::getRepInFormat().
getProfiles()
StringMap<FunctionSamples>& llvm::sampleprof::SampleProfileReader::getProfiles () inline
Return all the profiles.
Definition at line 385 of file SampleProfReader.h.
Referenced by llvm::createSampleProfileLoaderPass().
getProfileSymbolList()
virtual std::unique_ptr<ProfileSymbolList> llvm::sampleprof::SampleProfileReader::getProfileSymbolList () inline virtual
Reimplemented in llvm::sampleprof::SampleProfileReaderExtBinary.
Definition at line 413 of file SampleProfReader.h.
getSamplesFor() [1/2]
FunctionSamples* llvm::sampleprof::SampleProfileReader::getSamplesFor (const Function & F) inline
Return the samples collected for function F.
Definition at line 353 of file SampleProfReader.h.
References llvm::sampleprof::FunctionSamples::getCanonicalFnName(), and llvm::sampleprof::SampleProfileReaderItaniumRemapper::getSamplesFor().
Referenced by llvm::createSampleProfileLoaderPass().
getSamplesFor() [2/2]
virtual FunctionSamples* llvm::sampleprof::SampleProfileReader::getSamplesFor (StringRef Fname) inline virtual
Return the samples collected for function F.
Definition at line 371 of file SampleProfReader.h.
References llvm::X86AS::FS, and llvm::sampleprof::getRepInFormat().
getSummary()
ProfileSummary& llvm::sampleprof::SampleProfileReader::getSummary () const inline
Return the profile summary.
Definition at line 406 of file SampleProfReader.h.
Referenced by llvm::createSampleProfileLoaderPass().
read()
std::error_code llvm::sampleprof::SampleProfileReader::read () inline
The interface to read sample profiles from the associated file.
Definition at line 333 of file SampleProfReader.h.
References llvm::dbgs(), and llvm::success.
readHeader()
virtual std::error_code llvm::sampleprof::SampleProfileReader::readHeader () pure virtual
Read and validate the file header.
Implemented in llvm::sampleprof::SampleProfileReaderGCC, llvm::sampleprof::SampleProfileReaderExtBinaryBase, llvm::sampleprof::SampleProfileReaderBinary, and llvm::sampleprof::SampleProfileReaderText.
readImpl()
virtual std::error_code llvm::sampleprof::SampleProfileReader::readImpl () pure virtual
The implementaion to read sample profiles from the associated file.
Implemented in llvm::sampleprof::SampleProfileReaderGCC, llvm::sampleprof::SampleProfileReaderCompactBinary, llvm::sampleprof::SampleProfileReaderExtBinaryBase, llvm::sampleprof::SampleProfileReaderBinary, and llvm::sampleprof::SampleProfileReaderText.
reportError()
void llvm::sampleprof::SampleProfileReader::reportError (int64_t LineNumber, Twine Msg) const inline
Report a parse error message.
Definition at line 388 of file SampleProfReader.h.
References B, C, and llvm::sampleprof::SampleProfileReaderItaniumRemapper::create().
Referenced by llvm::sampleprof::SampleProfileReaderText::readImpl(), and llvm::sampleprof::SampleProfileReaderGCC::readNumber().
takeSummary()
static std::unique_ptr<ProfileSummary> llvm::sampleprof::SampleProfileReader::takeSummary (SampleProfileReader & Reader) inline static protected
Take ownership of the summary of this reader.
Definition at line 441 of file SampleProfReader.h.
References Summary.
Member Data Documentation
Buffer
std::unique_ptr<MemoryBuffer> llvm::sampleprof::SampleProfileReader::Buffer protected
Memory buffer holding the profile file.
Definition at line 434 of file SampleProfReader.h.
Referenced by llvm::sampleprof::SampleProfileReaderBinary::readHeader(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readHeader(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readImpl(), llvm::sampleprof::SampleProfileReaderCompactBinary::readImpl(), and setupMemoryBuffer().
Ctx
LLVMContext& llvm::sampleprof::SampleProfileReader::Ctx protected
LLVM context used to emit diagnostics.
Definition at line 431 of file SampleProfReader.h.
Format
SampleProfileFormat llvm::sampleprof::SampleProfileReader::Format = SPF_None protected
The format of sample.
Definition at line 451 of file SampleProfReader.h.
Profiles
StringMap<FunctionSamples> llvm::sampleprof::SampleProfileReader::Profiles protected
Map every function to its associated profile.
The profile of every function executed at runtime is collected in the structure FunctionSamples. This maps function objects to their corresponding profiles.
Definition at line 420 of file SampleProfReader.h.
Referenced by computeSummary(), dump(), dumpFunctionProfile(), llvm::sampleprof::SampleProfileReaderText::readImpl(), and llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile().
Remapper
std::unique_ptr<SampleProfileReaderItaniumRemapper> llvm::sampleprof::SampleProfileReader::Remapper protected
Definition at line 448 of file SampleProfReader.h.
Summary
std::unique_ptr<ProfileSummary> llvm::sampleprof::SampleProfileReader::Summary protected
Profile summary information.
Definition at line 437 of file SampleProfReader.h.
Referenced by computeSummary(), llvm::sampleprof::SampleProfileReaderBinary::readSummary(), and takeSummary().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfReader.h
lib/ProfileData/SampleProfReader.cpp