LLVM: llvm::ilist_node_with_parent< NodeTy, ParentTy, Options > Class Template Reference
llvm::ilist_node_with_parent< NodeTy, ParentTy, Options > Class Template Reference
An ilist node that can access its parent list.
#include "llvm/ADT/ilist_node.h"
Public Member Functions
Adjacent Node Accessors
Get the previous node, or nullptr for the list head.
NodeTy * getPrevNode ()
const NodeTy * getPrevNode () const
Get the previous node, or nullptr for the list head.
NodeTy * getNextNode ()
Get the next node, or nullptr for the list tail.
const NodeTy * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Protected Member Functions
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >
ilist_node_impl ()=default
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< NodeTy, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< NodeTy, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< NodeTy, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< NodeTy, Options... >::type, true, true >
Detailed Description
template<typename NodeTy, typename ParentTy, class... Options>
class llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >
An ilist node that can access its parent list.
Requires NodeTy to have getParent() to find the parent node, and the ParentTy to have getSublistAccess() to get a reference to the list.
Definition at line 256 of file ilist_node.h.
Constructor & Destructor Documentation
ilist_node_with_parent()
template<typename NodeTy, typename ParentTy, class... Options> llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::ilist_node_with_parent () protected default
Member Function Documentation
getNextNode() [1/2]
template<typename NodeTy, typename ParentTy, class... Options> NodeTy* llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode () inline
Get the next node, or nullptr for the list tail.
Definition at line 288 of file ilist_node.h.
Referenced by bothUsedInPHI(), collectInstructionsInBetween(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createCodeGenPreparePass(), llvm::createMemLibcall(), DeleteBasicBlock(), emitSetAndGetSwiftErrorValueAround(), eraseDeadBBsAndChildren(), llvm::IRTranslator::getAnalysisUsage(), llvm::RegBankSelect::getAnalysisUsage(), llvm::IRPosition::getAttrs(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), getNextMachineInstr(), getParameterABIAttributes(), getParentPad(), getSignature(), hasCallsBetween(), hasSameExtUse(), INITIALIZE_PASS(), insertRelocationStores(), llvm::RegBankSelect::InstrInsertPoint::InstrInsertPoint(), isCallInstruction(), isKnownTypeIdMember(), isLibCallInTailPosition(), isLoadStoreThatCanHandleDisplacement(), llvm::isSafeToMoveBefore(), needPadding(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeSQRT(), postDominates(), rematerializeLiveValues(), RemoveDeadAddBetweenLEAAndJT(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::replaceDbgDeclare(), llvm::replaceDbgDeclareForAlloca(), RetagMask(), scaleWeights(), llvm::TargetLowering::CallLoweringInfo::setCallee(), simplifyRelocatesOffABase(), splitAround(), StackMallocSizeClass(), llvm::JumpThreadingPass::ThreadGuard(), TypeSizeToSizeIndex(), and updateCoroFrame().
getNextNode() [2/2]
template<typename NodeTy, typename ParentTy, class... Options> const NodeTy* llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode () const inline
Get the next node, or nullptr for the list tail.
Definition at line 297 of file ilist_node.h.
getPrevNode() [1/2]
template<typename NodeTy, typename ParentTy, class... Options> NodeTy* llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode () inline
Definition at line 274 of file ilist_node.h.
Referenced by canReuseBoundaryAlignFragment(), llvm::createSIWholeQuadModePass(), llvm::IRPosition::getAttrs(), getINCDECFromLEA(), llvm::BasicBlock::getTerminatingMustTailCall(), llvm::MCAsmLayout::invalidateFragmentsFrom(), llvm::RegBankSelect::InstrInsertPoint::isSplit(), llvm::MCAsmLayout::layoutFragment(), PrevCrossBBInst(), runOnFunction(), simplifySuspendPoint(), sinkLastInstruction(), and updateKillStatus().
getPrevNode() [2/2]
template<typename NodeTy, typename ParentTy, class... Options> const NodeTy* llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode () const inline
Get the previous node, or nullptr for the list head.
Definition at line 283 of file ilist_node.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ilist_node.h