LLVM: llvm::codeview::MergingTypeTableBuilder Class Reference
llvm::codeview::MergingTypeTableBuilder Class Reference
#include "llvm/DebugInfo/CodeView/MergingTypeTableBuilder.h"
Public Member Functions
MergingTypeTableBuilder (BumpPtrAllocator &Storage)
~MergingTypeTableBuilder ()
Optional< TypeIndex > getFirst () override
Optional< TypeIndex > getNext (TypeIndex Prev) override
CVType getType (TypeIndex Index) override
StringRef getTypeName (TypeIndex Index) override
bool contains (TypeIndex Index) override
uint32_t size () override
uint32_t capacity () override
void reset ()
TypeIndex nextTypeIndex () const
BumpPtrAllocator & getAllocator ()
ArrayRef< ArrayRef< uint8_t > > records () const
TypeIndex insertRecordAs (hash_code Hash, ArrayRef< uint8_t > &Record)
TypeIndex insertRecordBytes (ArrayRef< uint8_t > &Record)
TypeIndex insertRecord (ContinuationRecordBuilder &Builder)
template<typename T >
TypeIndex writeLeafType (T &Record)
Public Member Functions inherited from llvm::codeview::TypeCollection
virtual ~TypeCollection ()=default
bool empty ()
template<typename TFunc >
void ForEachRecord (TFunc Func)
Detailed Description
Definition at line 31 of file MergingTypeTableBuilder.h.
Constructor & Destructor Documentation
MergingTypeTableBuilder()
MergingTypeTableBuilder::MergingTypeTableBuilder (BumpPtrAllocator & Storage) explicit
Definition at line 34 of file MergingTypeTableBuilder.cpp.
References ~MergingTypeTableBuilder().
~MergingTypeTableBuilder()
MergingTypeTableBuilder::~MergingTypeTableBuilder () default
Referenced by MergingTypeTableBuilder().
Member Function Documentation
capacity()
uint32_t MergingTypeTableBuilder::capacity () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 72 of file MergingTypeTableBuilder.cpp.
contains()
bool MergingTypeTableBuilder::contains (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 63 of file MergingTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::isNoneType(), llvm::codeview::TypeIndex::isSimple(), and llvm::codeview::TypeIndex::toArrayIndex().
getAllocator()
BumpPtrAllocator& llvm::codeview::MergingTypeTableBuilder::getAllocator () inline
Definition at line 63 of file MergingTypeTableBuilder.h.
References insertRecord(), insertRecordAs(), insertRecordBytes(), and records().
getFirst()
Optional< TypeIndex > MergingTypeTableBuilder::getFirst () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 41 of file MergingTypeTableBuilder.cpp.
References llvm::codeview::TypeCollection::empty(), llvm::codeview::TypeIndex::FirstNonSimpleIndex, and llvm::codeview::None.
getNext()
Optional< TypeIndex > MergingTypeTableBuilder::getNext (TypeIndex Prev) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 48 of file MergingTypeTableBuilder.cpp.
References nextTypeIndex(), and llvm::codeview::None.
getType()
CVType MergingTypeTableBuilder::getType (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 54 of file MergingTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::toArrayIndex().
getTypeName()
StringRef MergingTypeTableBuilder::getTypeName (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 59 of file MergingTypeTableBuilder.cpp.
References llvm_unreachable.
insertRecord()
TypeIndex MergingTypeTableBuilder::insertRecord (ContinuationRecordBuilder & Builder)
Definition at line 116 of file MergingTypeTableBuilder.cpp.
References assert(), llvm::codeview::C, llvm::codeview::ContinuationRecordBuilder::end(), insertRecordBytes(), and nextTypeIndex().
Referenced by getAllocator().
insertRecordAs()
TypeIndex MergingTypeTableBuilder::insertRecordAs (hash_code Hash, ArrayRef< uint8_t > & Record)
Definition at line 90 of file MergingTypeTableBuilder.cpp.
References assert(), nextTypeIndex(), llvm::ArrayRef< T >::size(), stabilize(), and llvm::codeview::TypeIndex::toArrayIndex().
Referenced by getAllocator(), and insertRecordBytes().
insertRecordBytes()
TypeIndex MergingTypeTableBuilder::insertRecordBytes (ArrayRef< uint8_t > & Record)
Definition at line 111 of file MergingTypeTableBuilder.cpp.
References llvm::hash_value(), and insertRecordAs().
Referenced by getAllocator(), insertRecord(), and writeLeafType().
nextTypeIndex()
TypeIndex MergingTypeTableBuilder::nextTypeIndex () const
Definition at line 30 of file MergingTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::fromArrayIndex().
Referenced by getNext(), insertRecord(), and insertRecordAs().
records()
ArrayRef< ArrayRef< uint8_t > > MergingTypeTableBuilder::records () const
Definition at line 74 of file MergingTypeTableBuilder.cpp.
Referenced by getAllocator().
reset()
void MergingTypeTableBuilder::reset ()
Definition at line 78 of file MergingTypeTableBuilder.cpp.
size()
uint32_t MergingTypeTableBuilder::size () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 70 of file MergingTypeTableBuilder.cpp.
writeLeafType()
template<typename T > TypeIndex llvm::codeview::MergingTypeTableBuilder::writeLeafType (T & Record) inline
Definition at line 71 of file MergingTypeTableBuilder.h.
References llvm::Data, insertRecordBytes(), and llvm::codeview::SimpleTypeSerializer::serialize().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/MergingTypeTableBuilder.h
lib/DebugInfo/CodeView/MergingTypeTableBuilder.cpp