LLVM: llvm::AllocatorList< T, AllocatorT > Class Template Reference
llvm::AllocatorList< T, AllocatorT > Class Template Reference
A linked-list with a custom, local allocator.
#include "llvm/ADT/AllocatorList.h"
Public Types
using value_type = T
using pointer = T *
using reference = T &
using const_pointer = const T *
using const_reference = const T &
using size_type = typename list_type::size_type
using difference_type = typename list_type::difference_type
using iterator = IteratorImpl< T, typename list_type::iterator >
using reverse_iterator = IteratorImpl< T, typename list_type::reverse_iterator >
using const_iterator = IteratorImpl< const T, typename list_type::const_iterator >
using const_reverse_iterator = IteratorImpl< const T, typename list_type::const_reverse_iterator >
Public Member Functions
AllocatorList ()=default
AllocatorList (AllocatorList &&X)
AllocatorList (const AllocatorList &X)
AllocatorList & operator= (AllocatorList &&X)
AllocatorList & operator= (const AllocatorList &X)
~AllocatorList ()
void swap (AllocatorList &RHS)
bool empty ()
size_t size ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
T & back ()
T & front ()
const T & back () const
const T & front () const
template<class... Ts>
iterator emplace (iterator I, Ts &&... Vs)
iterator insert (iterator I, T &&V)
iterator insert (iterator I, const T &V)
template<class Iterator >
void insert (iterator I, Iterator First, Iterator Last)
iterator erase (iterator I)
iterator erase (iterator First, iterator Last)
void clear ()
void pop_back ()
void pop_front ()
void push_back (T &&V)
void push_front (T &&V)
void push_back (const T &V)
void push_front (const T &V)
template<class... Ts>
void emplace_back (Ts &&... Vs)
template<class... Ts>
void emplace_front (Ts &&... Vs)
void resetAlloc ()
Reset the underlying allocator.
Detailed Description
template<class T, class AllocatorT>
class llvm::AllocatorList< T, AllocatorT >
A linked-list with a custom, local allocator.
Expose a std::list-like interface that owns and uses a custom LLVM-style allocator (e.g., BumpPtrAllocator), leveraging simple_ilist for the implementation details.
Because this list owns the allocator, calling splice() with a different list isn't generally safe. As such, splice has been left out of the interface entirely.
Definition at line 34 of file AllocatorList.h.
Member Typedef Documentation
const_iterator
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::const_iterator = IteratorImpl<const T, typename list_type::const_iterator>
Definition at line 135 of file AllocatorList.h.
const_pointer
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::const_pointer = const T *
Definition at line 81 of file AllocatorList.h.
const_reference
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::const_reference = const T &
Definition at line 82 of file AllocatorList.h.
const_reverse_iterator
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::const_reverse_iterator = IteratorImpl<const T, typename list_type::const_reverse_iterator>
Definition at line 137 of file AllocatorList.h.
difference_type
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::difference_type = typename list_type::difference_type
Definition at line 84 of file AllocatorList.h.
iterator
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::iterator = IteratorImpl<T, typename list_type::iterator>
Definition at line 131 of file AllocatorList.h.
pointer
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::pointer = T *
Definition at line 79 of file AllocatorList.h.
reference
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::reference = T &
Definition at line 80 of file AllocatorList.h.
reverse_iterator
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::reverse_iterator = IteratorImpl<T, typename list_type::reverse_iterator>
Definition at line 133 of file AllocatorList.h.
size_type
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::size_type = typename list_type::size_type
Definition at line 83 of file AllocatorList.h.
value_type
template<class T, class AllocatorT> using llvm::AllocatorList< T, AllocatorT >::value_type = T
Definition at line 78 of file AllocatorList.h.
Constructor & Destructor Documentation
AllocatorList() [1/3]
template<class T, class AllocatorT> llvm::AllocatorList< T, AllocatorT >::AllocatorList () default
AllocatorList() [2/3]
template<class T, class AllocatorT> llvm::AllocatorList< T, AllocatorT >::AllocatorList (AllocatorList< T, AllocatorT > && X) inline
Definition at line 140 of file AllocatorList.h.
AllocatorList() [3/3]
template<class T, class AllocatorT> llvm::AllocatorList< T, AllocatorT >::AllocatorList (const AllocatorList< T, AllocatorT > & X) inline
Definition at line 143 of file AllocatorList.h.
~AllocatorList()
template<class T, class AllocatorT> llvm::AllocatorList< T, AllocatorT >::~AllocatorList () inline
Definition at line 159 of file AllocatorList.h.
Member Function Documentation
back() [1/2]
template<class T, class AllocatorT> T& llvm::AllocatorList< T, AllocatorT >::back () inline
Definition at line 182 of file AllocatorList.h.
back() [2/2]
template<class T, class AllocatorT> const T& llvm::AllocatorList< T, AllocatorT >::back () const inline
Definition at line 184 of file AllocatorList.h.
begin() [1/2]
template<class T, class AllocatorT> iterator llvm::AllocatorList< T, AllocatorT >::begin () inline
Definition at line 169 of file AllocatorList.h.
Referenced by llvm::AllocatorList< Token >::emplace_front(), llvm::yaml::Scanner::peekNext(), and llvm::AllocatorList< Token >::push_front().
begin() [2/2]
template<class T, class AllocatorT> const_iterator llvm::AllocatorList< T, AllocatorT >::begin () const inline
Definition at line 171 of file AllocatorList.h.
clear()
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::clear () inline
Definition at line 213 of file AllocatorList.h.
Referenced by llvm::AllocatorList< Token >::operator=(), llvm::yaml::Scanner::peekNext(), and llvm::AllocatorList< Token >::~AllocatorList().
emplace()
template<class T, class AllocatorT> template<class... Ts> iterator llvm::AllocatorList< T, AllocatorT >::emplace (iterator I, Ts &&... Vs) inline
Definition at line 187 of file AllocatorList.h.
Referenced by llvm::AllocatorList< Token >::emplace_back(), and llvm::AllocatorList< Token >::emplace_front().
emplace_back()
template<class T, class AllocatorT> template<class... Ts> void llvm::AllocatorList< T, AllocatorT >::emplace_back (Ts &&... Vs) inline
Definition at line 220 of file AllocatorList.h.
emplace_front()
template<class T, class AllocatorT> template<class... Ts> void llvm::AllocatorList< T, AllocatorT >::emplace_front (Ts &&... Vs) inline
Definition at line 223 of file AllocatorList.h.
empty()
template<class T, class AllocatorT> bool llvm::AllocatorList< T, AllocatorT >::empty () inline
Definition at line 166 of file AllocatorList.h.
Referenced by llvm::yaml::Scanner::getNext(), llvm::yaml::Scanner::peekNext(), and llvm::AllocatorList< Token >::resetAlloc().
end() [1/2]
template<class T, class AllocatorT> iterator llvm::AllocatorList< T, AllocatorT >::end () inline
Definition at line 170 of file AllocatorList.h.
Referenced by llvm::AllocatorList< Token >::emplace_back(), and llvm::AllocatorList< Token >::push_back().
end() [2/2]
template<class T, class AllocatorT> const_iterator llvm::AllocatorList< T, AllocatorT >::end () const inline
Definition at line 172 of file AllocatorList.h.
erase() [1/2]
template<class T, class AllocatorT> iterator llvm::AllocatorList< T, AllocatorT >::erase (iterator I) inline
Definition at line 204 of file AllocatorList.h.
erase() [2/2]
template<class T, class AllocatorT> iterator llvm::AllocatorList< T, AllocatorT >::erase (iterator First, iterator Last) inline
Definition at line 208 of file AllocatorList.h.
front() [1/2]
template<class T, class AllocatorT> T& llvm::AllocatorList< T, AllocatorT >::front () inline
Definition at line 183 of file AllocatorList.h.
Referenced by llvm::yaml::Scanner::peekNext().
front() [2/2]
template<class T, class AllocatorT> const T& llvm::AllocatorList< T, AllocatorT >::front () const inline
Definition at line 185 of file AllocatorList.h.
insert() [1/3]
template<class T, class AllocatorT> iterator llvm::AllocatorList< T, AllocatorT >::insert (iterator I, T && V) inline
Definition at line 191 of file AllocatorList.h.
Referenced by is_ns_word_char(), llvm::AllocatorList< Token >::push_back(), and llvm::AllocatorList< Token >::push_front().
insert() [2/3]
template<class T, class AllocatorT> iterator llvm::AllocatorList< T, AllocatorT >::insert (iterator I, const T & V) inline
Definition at line 194 of file AllocatorList.h.
insert() [3/3]
template<class T, class AllocatorT> template<class Iterator > void llvm::AllocatorList< T, AllocatorT >::insert (iterator I, Iterator First, Iterator Last) inline
Definition at line 199 of file AllocatorList.h.
operator=() [1/2]
template<class T, class AllocatorT> AllocatorList& llvm::AllocatorList< T, AllocatorT >::operator= (AllocatorList< T, AllocatorT > && X) inline
Definition at line 147 of file AllocatorList.h.
operator=() [2/2]
template<class T, class AllocatorT> AllocatorList& llvm::AllocatorList< T, AllocatorT >::operator= (const AllocatorList< T, AllocatorT > & X) inline
Definition at line 154 of file AllocatorList.h.
pop_back()
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::pop_back () inline
Definition at line 214 of file AllocatorList.h.
pop_front()
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::pop_front () inline
Definition at line 215 of file AllocatorList.h.
Referenced by llvm::yaml::Scanner::getNext().
push_back() [1/2]
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::push_back (T && V) inline
Definition at line 216 of file AllocatorList.h.
Referenced by is_ns_word_char(), and llvm::yaml::Scanner::peekNext().
push_back() [2/2]
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::push_back (const T & V) inline
Definition at line 218 of file AllocatorList.h.
push_front() [1/2]
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::push_front (T && V) inline
Definition at line 217 of file AllocatorList.h.
push_front() [2/2]
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::push_front (const T & V) inline
Definition at line 219 of file AllocatorList.h.
rbegin() [1/2]
template<class T, class AllocatorT> reverse_iterator llvm::AllocatorList< T, AllocatorT >::rbegin () inline
Definition at line 173 of file AllocatorList.h.
rbegin() [2/2]
template<class T, class AllocatorT> const_reverse_iterator llvm::AllocatorList< T, AllocatorT >::rbegin () const inline
Definition at line 175 of file AllocatorList.h.
rend() [1/2]
template<class T, class AllocatorT> reverse_iterator llvm::AllocatorList< T, AllocatorT >::rend () inline
Definition at line 174 of file AllocatorList.h.
rend() [2/2]
template<class T, class AllocatorT> const_reverse_iterator llvm::AllocatorList< T, AllocatorT >::rend () const inline
Definition at line 178 of file AllocatorList.h.
resetAlloc()
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::resetAlloc () inline
Reset the underlying allocator.
Precondition
empty()
Definition at line 230 of file AllocatorList.h.
Referenced by llvm::yaml::Scanner::getNext().
size()
template<class T, class AllocatorT> size_t llvm::AllocatorList< T, AllocatorT >::size () inline
Definition at line 167 of file AllocatorList.h.
swap()
template<class T, class AllocatorT> void llvm::AllocatorList< T, AllocatorT >::swap (AllocatorList< T, AllocatorT > & RHS) inline
Definition at line 161 of file AllocatorList.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/AllocatorList.h