LLVM: llvm::BlockFrequencyInfo Class Reference
llvm::BlockFrequencyInfo Class Reference
BlockFrequencyInfo pass uses BlockFrequencyInfoImpl implementation to estimate IR basic block frequencies.
#include "llvm/Analysis/BlockFrequencyInfo.h"
Public Member Functions
BlockFrequencyInfo ()
BlockFrequencyInfo (const Function &F, const BranchProbabilityInfo &BPI, const LoopInfo &LI)
BlockFrequencyInfo (const BlockFrequencyInfo &)=delete
BlockFrequencyInfo & operator= (const BlockFrequencyInfo &)=delete
BlockFrequencyInfo (BlockFrequencyInfo &&Arg)
BlockFrequencyInfo & operator= (BlockFrequencyInfo &&RHS)
~BlockFrequencyInfo ()
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &)
Handle invalidation explicitly.
const Function * getFunction () const
const BranchProbabilityInfo * getBPI () const
void view (StringRef="BlockFrequencyDAGs") const
Pop up a ghostview window with the current block frequency propagation rendered using dot.
BlockFrequency getBlockFreq (const BasicBlock *BB) const
getblockFreq - Return block frequency.
Optional< uint64_t > getBlockProfileCount (const BasicBlock *BB, bool AllowSynthetic=false) const
Returns the estimated profile count of BB.
Optional< uint64_t > getProfileCountFromFreq (uint64_t Freq) const
Returns the estimated profile count of Freq.
bool isIrrLoopHeader (const BasicBlock *BB)
Returns true if BB is an irreducible loop header block.
void setBlockFreq (const BasicBlock *BB, uint64_t Freq)
void setBlockFreqAndScale (const BasicBlock *ReferenceBB, uint64_t Freq, SmallPtrSetImpl< BasicBlock *> &BlocksToScale)
Set the frequency of ReferenceBB to Freq and scale the frequencies of the blocks in BlocksToScale such that their frequencies relative to ReferenceBB remain unchanged.
void calculate (const Function &F, const BranchProbabilityInfo &BPI, const LoopInfo &LI)
calculate - compute block frequency info for the given function.
raw_ostream & printBlockFreq (raw_ostream &OS, const BlockFrequency Freq) const
raw_ostream & printBlockFreq (raw_ostream &OS, const BasicBlock *BB) const
uint64_t getEntryFreq () const
void releaseMemory ()
void print (raw_ostream &OS) const
Detailed Description
BlockFrequencyInfo pass uses BlockFrequencyInfoImpl implementation to estimate IR basic block frequencies.
Definition at line 37 of file BlockFrequencyInfo.h.
Constructor & Destructor Documentation
BlockFrequencyInfo() [1/4]
BlockFrequencyInfo::BlockFrequencyInfo () default
BlockFrequencyInfo() [2/4]
BlockFrequencyInfo::BlockFrequencyInfo (const Function & F, const BranchProbabilityInfo & BPI, const LoopInfo & LI)
Definition at line 154 of file BlockFrequencyInfo.cpp.
References calculate().
BlockFrequencyInfo() [3/4]
llvm::BlockFrequencyInfo::BlockFrequencyInfo (const BlockFrequencyInfo &) delete
BlockFrequencyInfo() [4/4]
BlockFrequencyInfo::BlockFrequencyInfo (BlockFrequencyInfo && Arg)
Definition at line 160 of file BlockFrequencyInfo.cpp.
~BlockFrequencyInfo()
BlockFrequencyInfo::~BlockFrequencyInfo () default
Referenced by operator=().
Member Function Documentation
calculate()
void BlockFrequencyInfo::calculate (const Function & F, const BranchProbabilityInfo & BPI, const LoopInfo & LI)
calculate - compute block frequency info for the given function.
Definition at line 184 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI, llvm::dbgs(), llvm::StringRef::equals(), llvm::Value::getName(), llvm::GVDT_None, print(), PrintBlockFreq, PrintBlockFreqFuncName, view(), ViewBlockFreqFuncName, and ViewBlockFreqPropagationDAG.
Referenced by BlockFrequencyInfo(), and llvm::BlockFrequencyAnalysis::run().
getBlockFreq()
BlockFrequency BlockFrequencyInfo::getBlockFreq (const BasicBlock * BB) const
getblockFreq - Return block frequency.
Return 0 if we don't have the information. Please note that initial frequency is equal to ENTRY_FREQ. It means that we should not rely on the value itself, but only on the comparison to the other block frequencies. We do this to avoid using of floating points.
Definition at line 202 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI.
Referenced by adjustedSumFreq(), llvm::CFGMST< Edge, BBInfo >::buildEdges(), computeFunctionSummary(), llvm::CodeExtractor::extractCodeRegion(), findBBsToSinkInto(), llvm::InlineFunction(), isColdCallSite(), sinkLoopInvariantInstructions(), and updateCallerBFI().
getBlockProfileCount()
Optional< uint64_t > BlockFrequencyInfo::getBlockProfileCount (const BasicBlock * BB, bool AllowSynthetic = false) const
Returns the estimated profile count of BB.
This computes the relative block frequency of BB and multiplies it by the enclosing function's count (if available) and returns the value.
Definition at line 207 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI, getFunction(), and llvm::None.
Referenced by llvm::ProfileSummaryInfo::getProfileCount(), hasProfileData(), llvm::OptimizationRemarkEmitter::invalidate(), llvm::ProfileSummaryInfo::isColdBlock(), llvm::ProfileSummaryInfo::isHotBlock(), and llvm::ProfileSummaryInfo::isHotBlockNthPercentile().
getBPI()
const BranchProbabilityInfo * BlockFrequencyInfo::getBPI () const
Definition at line 264 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI, and printBlockFreq().
Referenced by llvm::BlockFrequencyInfoWrapperPass::runOnFunction().
getEntryFreq()
uint64_t BlockFrequencyInfo::getEntryFreq () const
Definition at line 279 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI.
Referenced by llvm::CFGMST< Edge, BBInfo >::buildEdges(), and computeFunctionSummary().
getFunction()
const Function * BlockFrequencyInfo::getFunction () const
Definition at line 260 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI.
Referenced by getBlockProfileCount(), llvm::GraphTraits< BlockFrequencyInfo * >::getEntryNode(), getProfileCountFromFreq(), llvm::GraphTraits< BlockFrequencyInfo * >::nodes_begin(), and llvm::GraphTraits< BlockFrequencyInfo * >::nodes_end().
getProfileCountFromFreq()
Optional< uint64_t > BlockFrequencyInfo::getProfileCountFromFreq (uint64_t Freq) const
Returns the estimated profile count of Freq.
This uses the frequency Freq and multiplies it by the enclosing function's count (if available) and returns the value.
Definition at line 216 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI, getFunction(), and llvm::None.
Referenced by llvm::CodeExtractor::extractCodeRegion().
invalidate()
bool BlockFrequencyInfo::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator &)
Handle invalidation explicitly.
Definition at line 175 of file BlockFrequencyInfo.cpp.
References llvm::PreservedAnalyses::getChecker().
isIrrLoopHeader()
bool BlockFrequencyInfo::isIrrLoopHeader (const BasicBlock * BB)
Returns true if BB is an irreducible loop header block.
Otherwise false.
Definition at line 222 of file BlockFrequencyInfo.cpp.
References assert(), and llvm::AMDGPUISD::BFI.
operator=() [1/2]
BlockFrequencyInfo& llvm::BlockFrequencyInfo::operator= (const BlockFrequencyInfo &) delete
operator=() [2/2]
BlockFrequencyInfo & BlockFrequencyInfo::operator= (BlockFrequencyInfo && RHS)
Definition at line 163 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI, releaseMemory(), and ~BlockFrequencyInfo().
print()
void BlockFrequencyInfo::print (raw_ostream & OS) const
Definition at line 285 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI, INITIALIZE_PASS_BEGIN(), and INITIALIZE_PASS_DEPENDENCY.
Referenced by calculate(), llvm::BlockFrequencyInfoWrapperPass::getBFI(), and llvm::BlockFrequencyPrinterPass::run().
printBlockFreq() [1/2]
raw_ostream & BlockFrequencyInfo::printBlockFreq (raw_ostream & OS, const BlockFrequency Freq) const
Definition at line 269 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI.
Referenced by getBPI().
printBlockFreq() [2/2]
raw_ostream & BlockFrequencyInfo::printBlockFreq (raw_ostream & OS, const BasicBlock * BB) const
Definition at line 274 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI.
releaseMemory()
void BlockFrequencyInfo::releaseMemory ()
Definition at line 283 of file BlockFrequencyInfo.cpp.
References llvm::AMDGPUISD::BFI.
Referenced by llvm::BlockFrequencyInfoWrapperPass::getBFI(), and operator=().
setBlockFreq()
void BlockFrequencyInfo::setBlockFreq (const BasicBlock * BB, uint64_t Freq)
Definition at line 227 of file BlockFrequencyInfo.cpp.
References assert(), and llvm::AMDGPUISD::BFI.
Referenced by llvm::CodeExtractor::extractCodeRegion(), llvm::InlineFunction(), and updateCallerBFI().
setBlockFreqAndScale()
void BlockFrequencyInfo::setBlockFreqAndScale (const BasicBlock * ReferenceBB, uint64_t Freq, SmallPtrSetImpl< BasicBlock *> & BlocksToScale)
Set the frequency of ReferenceBB to Freq and scale the frequencies of the blocks in BlocksToScale such that their frequencies relative to ReferenceBB remain unchanged.
Definition at line 232 of file BlockFrequencyInfo.cpp.
References assert(), llvm::AMDGPUISD::BFI, and llvm::APInt::udiv().
Referenced by updateCallerBFI().
view()
void BlockFrequencyInfo::view (StringRef title = "BlockFrequencyDAGs") const
Pop up a ghostview window with the current block frequency propagation rendered using dot.
Definition at line 256 of file BlockFrequencyInfo.cpp.
References ViewGraph().
Referenced by calculate().
The documentation for this class was generated from the following files:
include/llvm/Analysis/BlockFrequencyInfo.h
lib/Analysis/BlockFrequencyInfo.cpp