LLVM: llvm::HexagonBlockRanges::IndexRange Class Reference
llvm::HexagonBlockRanges::IndexRange Class Reference
#include "Target/Hexagon/HexagonBlockRanges.h"
Public Member Functions
IndexRange ()=default
IndexRange (IndexType Start, IndexType End, bool F=false, bool T=false)
IndexType start () const
IndexType end () const
bool operator< (const IndexRange &A) const
bool overlaps (const IndexRange &A) const
bool contains (const IndexRange &A) const
void merge (const IndexRange &A)
Public Attributes
bool Fixed = false
bool TiedEnd = false
Detailed Description
Definition at line 78 of file HexagonBlockRanges.h.
Constructor & Destructor Documentation
IndexRange() [1/2]
llvm::HexagonBlockRanges::IndexRange::IndexRange () default
IndexRange() [2/2]
llvm::HexagonBlockRanges::IndexRange::IndexRange (IndexType Start, IndexType End, bool F = false, bool T = false) inline
Definition at line 81 of file HexagonBlockRanges.h.
Member Function Documentation
contains()
bool HexagonBlockRanges::IndexRange::contains (const IndexRange & A) const
Definition at line 47 of file HexagonBlockRanges.cpp.
References E, end(), llvm::HexagonBlockRanges::IndexType::None, and start().
end()
IndexType llvm::HexagonBlockRanges::IndexRange::end () const inline
Definition at line 85 of file HexagonBlockRanges.h.
References second.
Referenced by contains(), merge(), llvm::operator<<(), overlaps(), llvm::HexagonBlockRanges::RangeList::subtract(), and llvm::HexagonBlockRanges::RangeList::unionize().
merge()
void HexagonBlockRanges::IndexRange::merge (const IndexRange & A)
Definition at line 58 of file HexagonBlockRanges.cpp.
References assert(), end(), Fixed, llvm::HexagonBlockRanges::IndexType::None, overlaps(), start(), and TiedEnd.
operator<()
bool llvm::HexagonBlockRanges::IndexRange::operator< (const IndexRange & A) const inline
Definition at line 87 of file HexagonBlockRanges.h.
References contains(), and start().
overlaps()
bool HexagonBlockRanges::IndexRange::overlaps (const IndexRange & A) const
Definition at line 34 of file HexagonBlockRanges.cpp.
References E, end(), start(), and TiedEnd.
Referenced by merge(), llvm::HexagonBlockRanges::RangeList::subtract(), and llvm::HexagonBlockRanges::RangeList::unionize().
start()
IndexType llvm::HexagonBlockRanges::IndexRange::start () const inline
Definition at line 84 of file HexagonBlockRanges.h.
References first.
Referenced by contains(), merge(), operator<(), llvm::operator<<(), overlaps(), and llvm::HexagonBlockRanges::RangeList::unionize().
Member Data Documentation
Fixed
bool llvm::HexagonBlockRanges::IndexRange::Fixed = false
Definition at line 95 of file HexagonBlockRanges.h.
Referenced by merge(), llvm::operator<<(), and llvm::HexagonBlockRanges::RangeList::unionize().
TiedEnd
bool llvm::HexagonBlockRanges::IndexRange::TiedEnd = false
Definition at line 96 of file HexagonBlockRanges.h.
Referenced by merge(), llvm::operator<<(), and overlaps().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonBlockRanges.h
lib/Target/Hexagon/HexagonBlockRanges.cpp