LLVM: llvm::MachineBlockFrequencyInfo Class Reference
llvm::MachineBlockFrequencyInfo Class Reference
MachineBlockFrequencyInfo pass uses BlockFrequencyInfoImpl implementation to estimate machine basic block frequencies.
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
Public Member Functions
MachineBlockFrequencyInfo ()
MachineBlockFrequencyInfo (MachineFunction &F, MachineBranchProbabilityInfo &MBPI, MachineLoopInfo &MLI)
~MachineBlockFrequencyInfo () override
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void calculate (const MachineFunction &F, const MachineBranchProbabilityInfo &MBPI, const MachineLoopInfo &MLI)
calculate - compute block frequency info for the given function.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
BlockFrequency getBlockFreq (const MachineBasicBlock *MBB) const
getblockFreq - Return block frequency.
Optional< uint64_t > getBlockProfileCount (const MachineBasicBlock *MBB) const
Optional< uint64_t > getProfileCountFromFreq (uint64_t Freq) const
bool isIrrLoopHeader (const MachineBasicBlock *MBB)
const MachineFunction * getFunction () const
const MachineBranchProbabilityInfo * getMBPI () const
void view (const Twine &Name, bool isSimple=true) const
Pop up a ghostview window with the current block frequency propagation rendered using dot.
raw_ostream & printBlockFreq (raw_ostream &OS, const BlockFrequency Freq) const
raw_ostream & printBlockFreq (raw_ostream &OS, const MachineBasicBlock *MBB) const
uint64_t getEntryFreq () const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
MachineBlockFrequencyInfo pass uses BlockFrequencyInfoImpl implementation to estimate machine basic block frequencies.
Definition at line 33 of file MachineBlockFrequencyInfo.h.
Constructor & Destructor Documentation
MachineBlockFrequencyInfo() [1/2]
MachineBlockFrequencyInfo::MachineBlockFrequencyInfo ()
Definition at line 171 of file MachineBlockFrequencyInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineBlockFrequencyInfoPass().
MachineBlockFrequencyInfo() [2/2]
MachineBlockFrequencyInfo::MachineBlockFrequencyInfo (MachineFunction & F, MachineBranchProbabilityInfo & MBPI, MachineLoopInfo & MLI) explicit
Definition at line 176 of file MachineBlockFrequencyInfo.cpp.
References calculate(), and ~MachineBlockFrequencyInfo().
~MachineBlockFrequencyInfo()
MachineBlockFrequencyInfo::~MachineBlockFrequencyInfo () override default
Referenced by MachineBlockFrequencyInfo().
Member Function Documentation
calculate()
void MachineBlockFrequencyInfo::calculate (const MachineFunction & F, const MachineBranchProbabilityInfo & MBPI, const MachineLoopInfo & MLI)
calculate - compute block frequency info for the given function.
Definition at line 192 of file MachineBlockFrequencyInfo.cpp.
References llvm::dbgs(), llvm::StringRef::equals(), llvm::MachineFunction::getName(), llvm::GVDT_None, PrintBlockFreqFuncName, PrintMachineBlockFreq, view(), and ViewMachineBlockFreqPropagationDAG.
Referenced by MachineBlockFrequencyInfo(), and runOnMachineFunction().
getAnalysisUsage()
void MachineBlockFrequencyInfo::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 185 of file MachineBlockFrequencyInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getBlockFreq()
BlockFrequency MachineBlockFrequencyInfo::getBlockFreq (const MachineBasicBlock * MBB) const
getblockFreq - Return block frequency.
Return 0 if we don't have the information. Please note that initial frequency is equal to 1024. It means that we should not rely on the value itself, but only on the comparison to the other block frequencies. We do this to avoid using of floating points.
Definition at line 228 of file MachineBlockFrequencyInfo.cpp.
Referenced by llvm::RegBankSelect::InstrInsertPoint::frequency(), llvm::RegBankSelect::MBBInsertPoint::frequency(), llvm::RegBankSelect::EdgeInsertPoint::frequency(), llvm::RegBankSelect::getAnalysisUsage(), llvm::LiveIntervals::getSpillWeight(), and giveUpWithRemarks().
getBlockProfileCount()
Optional< uint64_t > MachineBlockFrequencyInfo::getBlockProfileCount (const MachineBasicBlock * MBB) const
Definition at line 232 of file MachineBlockFrequencyInfo.cpp.
References F(), and llvm::None.
Referenced by machine_size_opts_detail::isColdBlock(), and machine_size_opts_detail::isHotBlockNthPercentile().
getEntryFreq()
uint64_t MachineBlockFrequencyInfo::getEntryFreq () const
Definition at line 270 of file MachineBlockFrequencyInfo.cpp.
Referenced by getNumAllocatableRegsForConstraints(), and llvm::LiveIntervals::getSpillWeight().
getFunction()
const MachineFunction * MachineBlockFrequencyInfo::getFunction () const
Definition at line 250 of file MachineBlockFrequencyInfo.cpp.
Referenced by llvm::GraphTraits< MachineBlockFrequencyInfo * >::getEntryNode(), llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_begin(), and llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_end().
getMBPI()
const MachineBranchProbabilityInfo * MachineBlockFrequencyInfo::getMBPI () const
Definition at line 254 of file MachineBlockFrequencyInfo.cpp.
getProfileCountFromFreq()
Optional< uint64_t > MachineBlockFrequencyInfo::getProfileCountFromFreq (uint64_t Freq) const
Definition at line 239 of file MachineBlockFrequencyInfo.cpp.
References F(), and llvm::None.
isIrrLoopHeader()
bool MachineBlockFrequencyInfo::isIrrLoopHeader (const MachineBasicBlock * MBB)
Definition at line 245 of file MachineBlockFrequencyInfo.cpp.
References assert().
printBlockFreq() [1/2]
raw_ostream & MachineBlockFrequencyInfo::printBlockFreq (raw_ostream & OS, const BlockFrequency Freq) const
Definition at line 259 of file MachineBlockFrequencyInfo.cpp.
printBlockFreq() [2/2]
raw_ostream & MachineBlockFrequencyInfo::printBlockFreq (raw_ostream & OS, const MachineBasicBlock * MBB) const
Definition at line 265 of file MachineBlockFrequencyInfo.cpp.
releaseMemory()
void MachineBlockFrequencyInfo::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 218 of file MachineBlockFrequencyInfo.cpp.
runOnMachineFunction()
bool MachineBlockFrequencyInfo::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 210 of file MachineBlockFrequencyInfo.cpp.
References calculate().
view()
void MachineBlockFrequencyInfo::view (const Twine & Name, bool isSimple = true) const
Pop up a ghostview window with the current block frequency propagation rendered using dot.
Definition at line 222 of file MachineBlockFrequencyInfo.cpp.
References ViewGraph().
Referenced by calculate().
Member Data Documentation
ID
Machine Block Frequency true char MachineBlockFrequencyInfo::ID = 0 static
Definition at line 38 of file MachineBlockFrequencyInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineBlockFrequencyInfo.h
lib/CodeGen/MachineBlockFrequencyInfo.cpp