LLVM: llvm::VNInfo Class Reference
llvm::VNInfo Class Reference
VNInfo - Value Number Information.
#include "llvm/CodeGen/LiveInterval.h"
Public Types
using Allocator = BumpPtrAllocator
Public Member Functions
VNInfo (unsigned i, SlotIndex d)
VNInfo constructor.
VNInfo (unsigned i, const VNInfo &orig)
VNInfo constructor, copies values from orig, except for the value number.
void copyFrom (VNInfo &src)
Copy from the parameter into this VNInfo.
bool isPHIDef () const
Returns true if this value is defined by a PHI instruction (or was, PHI instructions may have been eliminated).
bool isUnused () const
Returns true if this value is unused.
void markUnused ()
Mark this value as unused.
Public Attributes
unsigned id
The ID number of this value.
SlotIndex def
The index of the defining instruction.
Detailed Description
VNInfo - Value Number Information.
This class holds information about a machine level values, including definition and use points.
Definition at line 52 of file LiveInterval.h.
Member Typedef Documentation
Allocator
using llvm::VNInfo::Allocator = BumpPtrAllocator
Definition at line 54 of file LiveInterval.h.
Constructor & Destructor Documentation
VNInfo() [1/2]
llvm::VNInfo::VNInfo (unsigned i, SlotIndex d) inline
VNInfo constructor.
Definition at line 63 of file LiveInterval.h.
Referenced by llvm::LiveRange::createValueCopy(), and llvm::LiveRange::getNextValue().
VNInfo() [2/2]
llvm::VNInfo::VNInfo (unsigned i, const VNInfo & orig) inline
VNInfo constructor, copies values from orig, except for the value number.
Definition at line 66 of file LiveInterval.h.
Member Function Documentation
copyFrom()
void llvm::VNInfo::copyFrom (VNInfo & src) inline
Copy from the parameter into this VNInfo.
Definition at line 69 of file LiveInterval.h.
References def.
Referenced by llvm::LiveRange::MergeValueNumberInto().
isPHIDef()
bool llvm::VNInfo::isPHIDef () const inline
Returns true if this value is defined by a PHI instruction (or was, PHI instructions may have been eliminated).
PHI-defs begin at a block boundary, all other defs begin at register or EC slots.
Definition at line 77 of file LiveInterval.h.
References llvm::SlotIndex::isBlock().
Referenced by addSegmentsWithValNo(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::SplitAnalysis::clear(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), createSegmentsForValues(), llvm::createSIWholeQuadModePass(), definesFullReg(), llvm::LiveIntervals::hasPHIKill(), isDefInSubRange(), isFullCopyOf(), isRematerializable(), llvm::LiveRange::print(), llvm::LiveIntervals::shrinkToUses(), stripValuesNotDefiningMask(), and subRangeLiveAt().
isUnused()
bool llvm::VNInfo::isUnused () const inline
Returns true if this value is unused.
Definition at line 80 of file LiveInterval.h.
References llvm::SlotIndex::isValid().
Referenced by addSegmentsWithValNo(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::SplitAnalysis::clear(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), definesFullReg(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::SplitEditor::finish(), llvm::LiveIntervals::hasPHIKill(), isDefInSubRange(), isFullCopyOf(), isRematerializable(), llvm::LiveRange::print(), llvm::LiveRange::RenumberValues(), llvm::LiveIntervals::shrinkToUses(), stripValuesNotDefiningMask(), and subRangeLiveAt().
markUnused()
void llvm::VNInfo::markUnused () inline
Mark this value as unused.
Definition at line 83 of file LiveInterval.h.
Referenced by addSegmentsWithValNo(), llvm::LiveRange::covers(), isDefInSubRange(), and llvm::LiveIntervals::shrinkToUses().
Member Data Documentation
def
SlotIndex llvm::VNInfo::def
The index of the defining instruction.
Definition at line 60 of file LiveInterval.h.
Referenced by addSegmentsWithValNo(), allPhiOperandsUndefined(), llvm::LiveRangeEdit::checkRematerializable(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::SplitAnalysis::clear(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), copyFrom(), llvm::createCopyConstrainDAGMutation(), llvm::LiveRange::createDeadDef(), createSegmentsForValues(), llvm::createSIWholeQuadModePass(), definesFullReg(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::SplitEditor::dump(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvBefore(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::SIRegisterInfo::findReachingDef(), llvm::SplitEditor::finish(), llvm::LiveRange::getNextValue(), llvm::LiveIntervals::hasPHIKill(), llvm::InsertPointAnalysis::InsertPointAnalysis(), llvm::CoalescerPair::isCoalescable(), isDefInSubRange(), isFullCopyOf(), isFullUndefDef(), isRematerializable(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvBefore(), moveAndTeeForMultiUse(), llvm::LiveRange::print(), llvm::LiveRange::Query(), llvm::LiveIntervals::removeVRegDefAt(), llvm::LiveIntervals::shrinkToUses(), stripValuesNotDefiningMask(), subRangeLiveAt(), llvm::LiveIntervals::HMEditor::updateAllRanges(), and llvm::MachineFunction::verify().
id
unsigned llvm::VNInfo::id
The ID number of this value.
Definition at line 57 of file LiveInterval.h.
Referenced by llvm::LiveRange::assign(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::LiveRange::containsValue(), llvm::LiveRange::covers(), llvm::DistributeRange(), llvm::SplitEditor::dump(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvBefore(), llvm::ConnectedVNInfoEqClasses::getEqClass(), isFullCopyOf(), llvm::LiveRange::join(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvBefore(), llvm::LiveRange::MergeValueNumberInto(), llvm::operator<<(), llvm::LiveIntervals::print(), llvm::LiveRange::RenumberValues(), and llvm::MachineFunction::verify().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/LiveInterval.h