LLVM: llvm::DIEAbbrevData Class Reference
llvm::DIEAbbrevData Class Reference
Dwarf abbreviation data, describes one attribute of a Dwarf abbreviation.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEAbbrevData (dwarf::Attribute A, dwarf::Form F)
DIEAbbrevData (dwarf::Attribute A, int64_t V)
void Profile (FoldingSetNodeID &ID) const
Used to gather unique data for the abbreviation folding set.
dwarf::Attribute getAttribute () const
Accessors.
dwarf::Form getForm () const
int64_t getValue () const
Detailed Description
Dwarf abbreviation data, describes one attribute of a Dwarf abbreviation.
Definition at line 49 of file DIE.h.
Constructor & Destructor Documentation
DIEAbbrevData() [1/2]
llvm::DIEAbbrevData::DIEAbbrevData (dwarf::Attribute A, dwarf::Form F) inline
Definition at line 60 of file DIE.h.
Referenced by llvm::DIEAbbrev::AddAttribute(), and llvm::DIEAbbrev::AddImplicitConstAttribute().
DIEAbbrevData() [2/2]
llvm::DIEAbbrevData::DIEAbbrevData (dwarf::Attribute A, int64_t V) inline
Definition at line 62 of file DIE.h.
Member Function Documentation
getAttribute()
dwarf::Attribute llvm::DIEAbbrevData::getAttribute () const inline
Accessors.
Definition at line 67 of file DIE.h.
Referenced by llvm::DIEAbbrev::Emit(), and llvm::DIEAbbrev::print().
getForm()
dwarf::Form llvm::DIEAbbrevData::getForm () const inline
Definition at line 68 of file DIE.h.
Referenced by llvm::DIEAbbrev::Emit(), and llvm::DIEAbbrev::print().
getValue()
int64_t llvm::DIEAbbrevData::getValue () const inline
Definition at line 69 of file DIE.h.
References Profile().
Referenced by llvm::DIEAbbrev::Emit().
Profile()
void DIEAbbrevData::Profile (FoldingSetNodeID & ID) const
Used to gather unique data for the abbreviation folding set.
Profile - Used to gather unique data for the abbreviation folding set.
Definition at line 42 of file DIE.cpp.
References llvm::FoldingSetNodeID::AddInteger().
Referenced by llvm::DIEAbbrev::AddImplicitConstAttribute(), getValue(), and llvm::DIEAbbrev::Profile().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp