LLVM: llvm::SmallVectorMemoryBuffer Class Reference
llvm::SmallVectorMemoryBuffer Class Reference
SmallVector-backed MemoryBuffer instance.
#include "llvm/Support/SmallVectorMemoryBuffer.h"
Public Member Functions
SmallVectorMemoryBuffer (SmallVectorImpl< char > &&SV)
Construct an SmallVectorMemoryBuffer from the given SmallVector r-value.
SmallVectorMemoryBuffer (SmallVectorImpl< char > &&SV, StringRef Name)
Construct a named SmallVectorMemoryBuffer from the given SmallVector r-value and StringRef.
~SmallVectorMemoryBuffer () override
StringRef getBufferIdentifier () const override
Return an identifier for this buffer, typically the filename it was read from.
BufferKind getBufferKind () const override
Return information on the memory mechanism used to support the MemoryBuffer.
Public Member Functions inherited from llvm::MemoryBuffer
MemoryBuffer (const MemoryBuffer &)=delete
MemoryBuffer & operator= (const MemoryBuffer &)=delete
virtual ~MemoryBuffer ()
const char * getBufferStart () const
const char * getBufferEnd () const
size_t getBufferSize () const
StringRef getBuffer () const
MemoryBufferRef getMemBufferRef () const
Additional Inherited Members
Public Types inherited from llvm::MemoryBuffer
enum BufferKind { MemoryBuffer_Malloc, MemoryBuffer_MMap }
The kind of memory backing used to support the MemoryBuffer.
Static Public Member Functions inherited from llvm::MemoryBuffer
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFile (const Twine &Filename, int64_t FileSize=-1, bool RequiresNullTerminator=true, bool IsVolatile=false)
Open the specified file as a MemoryBuffer, returning a new MemoryBuffer if successful, otherwise returning null.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileAsStream (const Twine &Filename)
Read all of the specified file into a MemoryBuffer as a stream (i.e.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getOpenFileSlice (sys::fs::file_t FD, const Twine &Filename, uint64_t MapSize, int64_t Offset, bool IsVolatile=false)
Given an already-open file descriptor, map some slice of it into a MemoryBuffer.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getOpenFile (sys::fs::file_t FD, const Twine &Filename, uint64_t FileSize, bool RequiresNullTerminator=true, bool IsVolatile=false)
Given an already-open file descriptor, read the file and return a MemoryBuffer.
static std::unique_ptr< MemoryBuffer > getMemBuffer (StringRef InputData, StringRef BufferName="", bool RequiresNullTerminator=true)
Open the specified memory range as a MemoryBuffer.
static std::unique_ptr< MemoryBuffer > getMemBuffer (MemoryBufferRef Ref, bool RequiresNullTerminator=true)
static std::unique_ptr< MemoryBuffer > getMemBufferCopy (StringRef InputData, const Twine &BufferName="")
Open the specified memory range as a MemoryBuffer, copying the contents and taking ownership of it.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getSTDIN ()
Read all of stdin into a file buffer, and return it.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileOrSTDIN (const Twine &Filename, int64_t FileSize=-1, bool RequiresNullTerminator=true)
Open the specified file as a MemoryBuffer, or open stdin if the Filename is "-".
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileSlice (const Twine &Filename, uint64_t MapSize, uint64_t Offset, bool IsVolatile=false)
Map a subrange of the specified file as a MemoryBuffer.
Protected Member Functions inherited from llvm::MemoryBuffer
MemoryBuffer ()=default
void init (const char *BufStart, const char *BufEnd, bool RequiresNullTerminator)
init - Initialize this MemoryBuffer as a reference to externally allocated memory, memory that we know is already null terminated.
Static Protected Attributes inherited from llvm::MemoryBuffer
static constexpr sys::fs::mapped_file_region::mapmode Mapmode
Detailed Description
SmallVector-backed MemoryBuffer instance.
This class enables efficient construction of MemoryBuffers from SmallVector instances. This is useful for MCJIT and Orc, where object files are streamed into SmallVectors, then inspected using ObjectFile (which takes a MemoryBuffer).
Definition at line 29 of file SmallVectorMemoryBuffer.h.
Constructor & Destructor Documentation
SmallVectorMemoryBuffer() [1/2]
llvm::SmallVectorMemoryBuffer::SmallVectorMemoryBuffer (SmallVectorImpl< char > && SV) inline
Construct an SmallVectorMemoryBuffer from the given SmallVector r-value.
FIXME: It'd be nice for this to be a non-templated constructor taking a SmallVectorImpl here instead of a templated one taking a SmallVector<N>, but SmallVector's move-construction/assignment currently only take SmallVectors. If/when that is fixed we can simplify this constructor and the following one.
Definition at line 39 of file SmallVectorMemoryBuffer.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::MemoryBuffer::init().
SmallVectorMemoryBuffer() [2/2]
llvm::SmallVectorMemoryBuffer::SmallVectorMemoryBuffer (SmallVectorImpl< char > && SV, StringRef Name) inline
Construct a named SmallVectorMemoryBuffer from the given SmallVector r-value and StringRef.
Definition at line 46 of file SmallVectorMemoryBuffer.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MemoryBuffer::init(), and ~SmallVectorMemoryBuffer().
~SmallVectorMemoryBuffer()
SmallVectorMemoryBuffer::~SmallVectorMemoryBuffer () override
Definition at line 525 of file MemoryBuffer.cpp.
Referenced by SmallVectorMemoryBuffer().
Member Function Documentation
getBufferIdentifier()
StringRef llvm::SmallVectorMemoryBuffer::getBufferIdentifier () const inline override virtual
Return an identifier for this buffer, typically the filename it was read from.
Reimplemented from llvm::MemoryBuffer.
Definition at line 54 of file SmallVectorMemoryBuffer.h.
getBufferKind()
BufferKind llvm::SmallVectorMemoryBuffer::getBufferKind () const inline override virtual
Return information on the memory mechanism used to support the MemoryBuffer.
Implements llvm::MemoryBuffer.
Definition at line 56 of file SmallVectorMemoryBuffer.h.
References llvm::MemoryBuffer::MemoryBuffer_Malloc.
The documentation for this class was generated from the following files:
include/llvm/Support/SmallVectorMemoryBuffer.h
lib/Support/MemoryBuffer.cpp