LLVM: llvm::coverage::LineCoverageStats Class Reference
llvm::coverage::LineCoverageStats Class Reference
Coverage statistics for a single line.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Member Functions
LineCoverageStats (ArrayRef< const CoverageSegment *> LineSegments, const CoverageSegment *WrappedSegment, unsigned Line)
uint64_t getExecutionCount () const
bool hasMultipleRegions () const
bool isMapped () const
unsigned getLine () const
ArrayRef< const CoverageSegment * > getLineSegments () const
const CoverageSegment * getWrappedSegment () const
Friends
class LineCoverageIterator
Detailed Description
Coverage statistics for a single line.
Definition at line 601 of file CoverageMapping.h.
Constructor & Destructor Documentation
LineCoverageStats()
LineCoverageStats::LineCoverageStats (ArrayRef< const CoverageSegment *> LineSegments, const CoverageSegment * WrappedSegment, unsigned Line)
Definition at line 740 of file CoverageMapping.cpp.
References llvm::coverage::CoverageSegment::Count, llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::coverage::CoverageSegment::HasCount, I, llvm::coverage::CoverageSegment::IsGapRegion, llvm::coverage::CoverageSegment::IsRegionEntry, llvm::AArch64CC::LS, llvm::max(), and llvm::ArrayRef< T >::size().
Member Function Documentation
getExecutionCount()
uint64_t llvm::coverage::LineCoverageStats::getExecutionCount () const inline
Definition at line 616 of file CoverageMapping.h.
getLine()
unsigned llvm::coverage::LineCoverageStats::getLine () const inline
Definition at line 622 of file CoverageMapping.h.
getLineSegments()
ArrayRef<const CoverageSegment *> llvm::coverage::LineCoverageStats::getLineSegments () const inline
Definition at line 624 of file CoverageMapping.h.
getWrappedSegment()
const CoverageSegment* llvm::coverage::LineCoverageStats::getWrappedSegment () const inline
Definition at line 628 of file CoverageMapping.h.
hasMultipleRegions()
bool llvm::coverage::LineCoverageStats::hasMultipleRegions () const inline
Definition at line 618 of file CoverageMapping.h.
isMapped()
bool llvm::coverage::LineCoverageStats::isMapped () const inline
Definition at line 620 of file CoverageMapping.h.
Friends And Related Function Documentation
LineCoverageIterator
friend class LineCoverageIterator friend
Definition at line 609 of file CoverageMapping.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMapping.h
lib/ProfileData/Coverage/CoverageMapping.cpp