LLVM: llvm::DebugHandlerBase Class Reference
llvm::DebugHandlerBase Class Reference abstract
Base class for debug information backends.
#include "llvm/CodeGen/DebugHandlerBase.h"
Public Member Functions
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
void beginFunction (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunction (const MachineFunction *MF) override
Gather post-function debug information.
MCSymbol * getLabelBeforeInsn (const MachineInstr *MI)
Return Label preceding the instruction.
MCSymbol * getLabelAfterInsn (const MachineInstr *MI)
Return Label immediately following the instruction.
const MCExpr * getFunctionLocalOffsetAfterInsn (const MachineInstr *MI)
Return the function-local offset of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void setSymbolSize (const MCSymbol *Sym, uint64_t Size)=0
For symbols that have a size designated (e.g.
virtual void endModule ()=0
Emit all sections that should come after the content.
virtual void markFunctionEnd ()
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void endFragment ()
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
Static Public Member Functions
static uint64_t getBaseTypeSize (const DIType *Ty)
If this type is derived from a base type then return base type size.
Protected Member Functions
DebugHandlerBase (AsmPrinter *A)
void identifyScopeMarkers ()
Indentify instructions that are marking the beginning of or ending of a scope.
void requestLabelBeforeInsn (const MachineInstr *MI)
Ensure that a label will be emitted before MI.
void requestLabelAfterInsn (const MachineInstr *MI)
Ensure that a label will be emitted after MI.
virtual void beginFunctionImpl (const MachineFunction *MF)=0
virtual void endFunctionImpl (const MachineFunction *MF)=0
virtual void skippedNonDebugFunction ()
Protected Attributes
AsmPrinter * Asm
Target of debug info emission.
MachineModuleInfo * MMI
Collected machine module information.
DebugLoc PrevInstLoc
Previous instruction's location information.
MCSymbol * PrevLabel = nullptr
const MachineBasicBlock * PrevInstBB = nullptr
DebugLoc PrologEndLoc
This location indicates end of function prologue and beginning of function body.
const MachineInstr * CurMI = nullptr
If nonnull, stores the current machine instruction we're processing.
LexicalScopes LScopes
DbgValueHistoryMap DbgValues
History of DBG_VALUE and clobber instructions for each user variable.
DbgLabelInstrMap DbgLabels
Mapping of inlined labels and DBG_LABEL machine instruction.
DenseMap< const MachineInstr *, MCSymbol * > LabelsBeforeInsn
Maps instruction with label emitted before instruction.
DenseMap< const MachineInstr *, MCSymbol * > LabelsAfterInsn
Maps instruction with label emitted after instruction.
Detailed Description
Base class for debug information backends.
Common functionality related to tracking which variables and scopes are alive at a given PC live here.
Definition at line 53 of file DebugHandlerBase.h.
Constructor & Destructor Documentation
DebugHandlerBase()
DebugHandlerBase::DebugHandlerBase (AsmPrinter * A) protected
Definition at line 87 of file DebugHandlerBase.cpp.
Member Function Documentation
beginFunction()
void DebugHandlerBase::beginFunction (const MachineFunction * MF) override virtual
Gather pre-function debug information.
Every beginFunction(MF) call should be followed by an endFunction(MF) call.
Implements llvm::AsmPrinterHandler.
Definition at line 185 of file DebugHandlerBase.cpp.
References llvm::any_of(), Asm, assert(), beginFunctionImpl(), llvm::calculateDbgEntityHistory(), DbgLabels, DbgValues, llvm::DbgValueHistoryMap::dump(), llvm::DbgValueHistoryMap::empty(), llvm::DbgLabelInstrMap::empty(), llvm::LexicalScopes::empty(), llvm::DIExpression::fragmentsOverlap(), llvm::getDISubprogram(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getFunctionBegin(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::DILocalVariable::getScope(), llvm::MachineFunction::getSubtarget(), hasDebugInfo(), I, identifyScopeMarkers(), llvm::LexicalScopes::initialize(), llvm::DILocalVariable::isParameter(), LabelsBeforeInsn, LLVM_DEBUG, LScopes, llvm::AsmPrinter::MF, MI, MMI, PrevInstBB, PrevInstLoc, PrevLabel, requestLabelAfterInsn(), requestLabelBeforeInsn(), and skippedNonDebugFunction().
beginFunctionImpl()
virtual void llvm::DebugHandlerBase::beginFunctionImpl (const MachineFunction * MF) protected pure virtual
Implemented in llvm::DwarfDebug, llvm::CodeViewDebug, and llvm::BTFDebug.
Referenced by beginFunction().
beginInstruction()
void DebugHandlerBase::beginInstruction (const MachineInstr * MI) override virtual
Process beginning of an instruction.
Implements llvm::AsmPrinterHandler.
Reimplemented in llvm::DwarfDebug, llvm::CodeViewDebug, and llvm::BTFDebug.
Definition at line 279 of file DebugHandlerBase.cpp.
References Asm, assert(), llvm::MCContext::createTempSymbol(), CurMI, llvm::MachineModuleInfo::getContext(), llvm::MachineModuleInfo::hasDebugInfo(), I, LabelsBeforeInsn, MI, MMI, llvm::AsmPrinter::OutStreamer, and PrevLabel.
Referenced by llvm::BTFDebug::beginInstruction(), llvm::CodeViewDebug::beginInstruction(), and llvm::DwarfDebug::beginInstruction().
endFunction()
void DebugHandlerBase::endFunction (const MachineFunction * MF) override virtual
Gather post-function debug information.
Please note that some AsmPrinter implementations may not call beginFunction at all.
Implements llvm::AsmPrinterHandler.
Definition at line 337 of file DebugHandlerBase.cpp.
References llvm::DbgValueHistoryMap::clear(), llvm::DbgLabelInstrMap::clear(), DbgLabels, DbgValues, endFunctionImpl(), hasDebugInfo(), LabelsAfterInsn, LabelsBeforeInsn, and MMI.
endFunctionImpl()
virtual void llvm::DebugHandlerBase::endFunctionImpl (const MachineFunction * MF) protected pure virtual
Implemented in llvm::DwarfDebug, llvm::CodeViewDebug, and llvm::BTFDebug.
Referenced by endFunction().
endInstruction()
void DebugHandlerBase::endInstruction () override virtual
Process end of an instruction.
Implements llvm::AsmPrinterHandler.
Definition at line 305 of file DebugHandlerBase.cpp.
References Asm, assert(), llvm::MCContext::createTempSymbol(), CurMI, llvm::MachineModuleInfo::getContext(), llvm::MachineInstr::getParent(), llvm::MachineModuleInfo::hasDebugInfo(), I, llvm::MachineInstr::isMetaInstruction(), LabelsAfterInsn, MMI, llvm::AsmPrinter::OutStreamer, PrevInstBB, and PrevLabel.
getBaseTypeSize()
uint64_t DebugHandlerBase::getBaseTypeSize (const DIType * Ty) static
If this type is derived from a base type then return base type size.
Definition at line 143 of file DebugHandlerBase.cpp.
References assert(), llvm::dyn_cast(), llvm::DIType::getSizeInBits(), llvm::DINode::getTag(), and llvm::Tag.
Referenced by llvm::DwarfUnit::constructContainingTypeDIEs(), and shouldEmitUdt().
getFunctionLocalOffsetAfterInsn()
const MCExpr * DebugHandlerBase::getFunctionLocalOffsetAfterInsn (const MachineInstr * MI)
Return the function-local offset of an instruction.
A label for the instruction MI should exist (getLabelAfterInsn).
Definition at line 129 of file DebugHandlerBase.cpp.
References Asm, and llvm::AsmPrinter::OutContext.
Referenced by collectCallSiteParameters().
getLabelAfterInsn()
MCSymbol * DebugHandlerBase::getLabelAfterInsn (const MachineInstr * MI)
Return Label immediately following the instruction.
Definition at line 123 of file DebugHandlerBase.cpp.
References LabelsAfterInsn.
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), collectCallSiteParameters(), llvm::CodeViewDebug::endFunctionImpl(), llvm::DwarfDebug::isLexicalScopeDIENull(), shouldAlwaysEmitCompleteClassType(), and validThroughout().
getLabelBeforeInsn()
MCSymbol * DebugHandlerBase::getLabelBeforeInsn (const MachineInstr * MI)
Return Label preceding the instruction.
Definition at line 116 of file DebugHandlerBase.cpp.
References assert(), and LabelsBeforeInsn.
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::CodeViewDebug::endFunctionImpl(), needsReferenceType(), shouldAlwaysEmitCompleteClassType(), and validThroughout().
identifyScopeMarkers()
void DebugHandlerBase::identifyScopeMarkers () protected
Indentify instructions that are marking the beginning of or ending of a scope.
Definition at line 93 of file DebugHandlerBase.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::LexicalScope::getChildren(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::LexicalScope::getRanges(), llvm::LexicalScope::isAbstractScope(), LScopes, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), requestLabelAfterInsn(), and requestLabelBeforeInsn().
Referenced by beginFunction().
requestLabelAfterInsn()
void llvm::DebugHandlerBase::requestLabelAfterInsn (const MachineInstr * MI) inline protected
Ensure that a label will be emitted after MI.
Definition at line 105 of file DebugHandlerBase.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by beginFunction(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfDebug::beginInstruction(), and identifyScopeMarkers().
requestLabelBeforeInsn()
void llvm::DebugHandlerBase::requestLabelBeforeInsn (const MachineInstr * MI) inline protected
Ensure that a label will be emitted before MI.
Definition at line 100 of file DebugHandlerBase.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by beginFunction(), llvm::CodeViewDebug::beginFunctionImpl(), and identifyScopeMarkers().
skippedNonDebugFunction()
virtual void llvm::DebugHandlerBase::skippedNonDebugFunction () inline protected virtual
Reimplemented in llvm::DwarfDebug.
Definition at line 111 of file DebugHandlerBase.h.
References MI.
Referenced by beginFunction().
Member Data Documentation
Asm
AsmPrinter* llvm::DebugHandlerBase::Asm protected
Target of debug info emission.
Definition at line 58 of file DebugHandlerBase.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), beginFunction(), llvm::BTFDebug::beginFunctionImpl(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfDebug::beginFunctionImpl(), beginInstruction(), llvm::BTFDebug::beginInstruction(), llvm::CodeViewDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), llvm::DwarfDebug::beginModule(), llvm::BTFDebug::BTFDebug(), llvm::CodeViewDebug::CodeViewDebug(), collectCallSiteParameters(), computeIndexValue(), dwarfCCToCodeView(), llvm::DwarfDebug::DwarfDebug(), llvm::DwarfDebug::emitDebugLocEntryLocation(), llvm::DwarfDebug::emitInitialLocDirective(), emitNullTerminatedSymbolName(), emitRangeList(), llvm::CodeViewDebug::endFunctionImpl(), llvm::DwarfDebug::endFunctionImpl(), endInstruction(), llvm::CodeViewDebug::endModule(), getFunctionLocalOffsetAfterInsn(), needsReferenceType(), and validThroughout().
CurMI
const MachineInstr* llvm::DebugHandlerBase::CurMI = nullptr protected
If nonnull, stores the current machine instruction we're processing.
Definition at line 76 of file DebugHandlerBase.h.
Referenced by beginInstruction(), llvm::DwarfDebug::beginInstruction(), endInstruction(), and llvm::DwarfDebug::endModule().
DbgLabels
DbgLabelInstrMap llvm::DebugHandlerBase::DbgLabels protected
Mapping of inlined labels and DBG_LABEL machine instruction.
Definition at line 85 of file DebugHandlerBase.h.
Referenced by beginFunction(), and endFunction().
DbgValues
DbgValueHistoryMap llvm::DebugHandlerBase::DbgValues protected
History of DBG_VALUE and clobber instructions for each user variable.
Variables are listed in order of appearance.
Definition at line 82 of file DebugHandlerBase.h.
Referenced by beginFunction(), endFunction(), and validThroughout().
LabelsAfterInsn
DenseMap<const MachineInstr *, MCSymbol *> llvm::DebugHandlerBase::LabelsAfterInsn protected
Maps instruction with label emitted after instruction.
Definition at line 93 of file DebugHandlerBase.h.
Referenced by endFunction(), endInstruction(), and getLabelAfterInsn().
LabelsBeforeInsn
DenseMap<const MachineInstr *, MCSymbol *> llvm::DebugHandlerBase::LabelsBeforeInsn protected
Maps instruction with label emitted before instruction.
FIXME: Make this private from DwarfDebug, we have the necessary accessors for it.
Definition at line 90 of file DebugHandlerBase.h.
Referenced by beginFunction(), beginInstruction(), endFunction(), and getLabelBeforeInsn().
LScopes
LexicalScopes llvm::DebugHandlerBase::LScopes protected
Definition at line 78 of file DebugHandlerBase.h.
Referenced by beginFunction(), llvm::DwarfDebug::beginFunctionImpl(), llvm::CodeViewDebug::endFunctionImpl(), llvm::DwarfDebug::endFunctionImpl(), identifyScopeMarkers(), and validThroughout().
MMI
MachineModuleInfo* llvm::DebugHandlerBase::MMI protected
Collected machine module information.
Definition at line 61 of file DebugHandlerBase.h.
Referenced by beginFunction(), beginInstruction(), llvm::BTFDebug::beginInstruction(), llvm::CodeViewDebug::beginInstruction(), llvm::DwarfDebug::beginModule(), llvm::CodeViewDebug::CodeViewDebug(), llvm::DwarfDebug::DwarfDebug(), endFunction(), endInstruction(), llvm::CodeViewDebug::endModule(), llvm::DwarfDebug::endModule(), getStringIdTypeIdx(), getSymbolName(), and parseVersion().
PrevInstBB
const MachineBasicBlock* llvm::DebugHandlerBase::PrevInstBB = nullptr protected
Definition at line 69 of file DebugHandlerBase.h.
Referenced by beginFunction(), llvm::CodeViewDebug::beginInstruction(), llvm::DwarfDebug::beginInstruction(), and endInstruction().
PrevInstLoc
DebugLoc llvm::DebugHandlerBase::PrevInstLoc protected
Previous instruction's location information.
This is used to determine label location to indicate scope boundaries in debug info. We track the previous instruction's source location (if not line 0), whether it was a label, and its parent BB.
Definition at line 67 of file DebugHandlerBase.h.
Referenced by addLocIfNotPresent(), beginFunction(), llvm::BTFDebug::beginInstruction(), and llvm::DwarfDebug::beginInstruction().
PrevLabel
MCSymbol* llvm::DebugHandlerBase::PrevLabel = nullptr protected
Definition at line 68 of file DebugHandlerBase.h.
Referenced by beginFunction(), beginInstruction(), llvm::DwarfDebug::beginInstruction(), llvm::DwarfDebug::endFunctionImpl(), and endInstruction().
PrologEndLoc
DebugLoc llvm::DebugHandlerBase::PrologEndLoc protected
This location indicates end of function prologue and beginning of function body.
Definition at line 73 of file DebugHandlerBase.h.
Referenced by llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfDebug::beginFunctionImpl(), llvm::DwarfDebug::beginInstruction(), and llvm::DwarfDebug::emitInitialLocDirective().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DebugHandlerBase.h
lib/CodeGen/AsmPrinter/DebugHandlerBase.cpp