LLVM: llvm::VPBuilder Class Reference
llvm::VPBuilder Class Reference
VPlan-based builder utility analogous to IRBuilder.
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Classes
class InsertPointGuard
RAII object that stores the current insertion point and restores it when the object is destroyed.
class VPInsertPoint
InsertPoint - A saved insertion point.
Public Member Functions
VPBuilder ()
void clearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
VPBasicBlock * getInsertBlock () const
VPBasicBlock::iterator getInsertPoint () const
void restoreIP (VPInsertPoint IP)
Sets the current insert point to a previously-saved location.
void setInsertPoint (VPBasicBlock *TheBB)
This specifies that created VPInstructions should be appended to the end of the specified block.
void setInsertPoint (VPBasicBlock *TheBB, VPBasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
VPInstruction * insert (VPInstruction *I) const
Insert and return the specified instruction.
VPValue * createNaryOp (unsigned Opcode, ArrayRef< VPValue *> Operands, Instruction *Inst=nullptr)
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
VPValue * createNaryOp (unsigned Opcode, std::initializer_list< VPValue *> Operands, Instruction *Inst=nullptr)
VPValue * createNot (VPValue *Operand)
VPValue * createAnd (VPValue *LHS, VPValue *RHS)
VPValue * createOr (VPValue *LHS, VPValue *RHS)
Detailed Description
VPlan-based builder utility analogous to IRBuilder.
Definition at line 35 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
VPBuilder()
llvm::VPBuilder::VPBuilder () inline
Definition at line 54 of file LoopVectorizationPlanner.h.
Member Function Documentation
clearInsertionPoint()
void llvm::VPBuilder::clearInsertionPoint () inline
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 58 of file LoopVectorizationPlanner.h.
Referenced by restoreIP().
createAnd()
VPValue* llvm::VPBuilder::createAnd (VPValue * LHS, VPValue * RHS) inline
Definition at line 133 of file LoopVectorizationPlanner.h.
createNaryOp() [1/2]
VPValue* llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue *> Operands, Instruction * Inst = nullptr) inline
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
Definition at line 117 of file LoopVectorizationPlanner.h.
References llvm::VPValue::setUnderlyingValue().
Referenced by createNaryOp().
createNaryOp() [2/2]
VPValue* llvm::VPBuilder::createNaryOp (unsigned Opcode, std::initializer_list< VPValue *> Operands, Instruction * Inst = nullptr) inline
Definition at line 123 of file LoopVectorizationPlanner.h.
References createNaryOp().
createNot()
VPValue* llvm::VPBuilder::createNot (VPValue * Operand) inline
Definition at line 129 of file LoopVectorizationPlanner.h.
References llvm::VPInstruction::Not.
createOr()
VPValue* llvm::VPBuilder::createOr (VPValue * LHS, VPValue * RHS) inline
Definition at line 137 of file LoopVectorizationPlanner.h.
getInsertBlock()
VPBasicBlock* llvm::VPBuilder::getInsertBlock () const inline
Definition at line 63 of file LoopVectorizationPlanner.h.
getInsertPoint()
VPBasicBlock::iterator llvm::VPBuilder::getInsertPoint () const inline
Definition at line 64 of file LoopVectorizationPlanner.h.
insert()
VPInstruction* llvm::VPBuilder::insert (VPInstruction * I) const inline
Insert and return the specified instruction.
Definition at line 110 of file LoopVectorizationPlanner.h.
References I, and llvm::VPBasicBlock::insert().
restoreIP()
void llvm::VPBuilder::restoreIP (VPInsertPoint IP) inline
Sets the current insert point to a previously-saved location.
Definition at line 87 of file LoopVectorizationPlanner.h.
References clearInsertionPoint(), llvm::VPBuilder::VPInsertPoint::getBlock(), llvm::VPBuilder::VPInsertPoint::getPoint(), llvm::VPBuilder::VPInsertPoint::isSet(), and setInsertPoint().
Referenced by llvm::VPBuilder::InsertPointGuard::~InsertPointGuard().
setInsertPoint() [1/2]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB) inline
This specifies that created VPInstructions should be appended to the end of the specified block.
Definition at line 96 of file LoopVectorizationPlanner.h.
References assert(), and llvm::VPBasicBlock::end().
Referenced by restoreIP().
setInsertPoint() [2/2]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB, VPBasicBlock::iterator IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 104 of file LoopVectorizationPlanner.h.
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h