LLVM: llvm::pdb::NamedStreamMap Class Reference
llvm::pdb::NamedStreamMap Class Reference
#include "llvm/DebugInfo/PDB/Native/NamedStreamMap.h"
Public Member Functions
NamedStreamMap ()
Error load (BinaryStreamReader &Stream)
Error commit (BinaryStreamWriter &Writer) const
uint32_t calculateSerializedLength () const
uint32_t size () const
bool get (StringRef Stream, uint32_t &StreamNo) const
void set (StringRef Stream, uint32_t StreamNo)
uint32_t appendStringData (StringRef S)
StringRef getString (uint32_t Offset) const
uint32_t hashString (uint32_t Offset) const
StringMap< uint32_t > entries () const
Friends
class NamedStreamMapBuilder
Detailed Description
Definition at line 38 of file NamedStreamMap.h.
Constructor & Destructor Documentation
NamedStreamMap()
NamedStreamMap::NamedStreamMap ()
Definition at line 49 of file NamedStreamMap.cpp.
Member Function Documentation
appendStringData()
uint32_t NamedStreamMap::appendStringData (StringRef S)
Definition at line 117 of file NamedStreamMap.cpp.
References llvm::StringRef::begin(), and llvm::StringRef::end().
Referenced by llvm::pdb::NamedStreamMapTraits::lookupKeyToStorageKey().
calculateSerializedLength()
uint32_t NamedStreamMap::calculateSerializedLength () const
Definition at line 83 of file NamedStreamMap.cpp.
Referenced by llvm::pdb::InfoStreamBuilder::finalizeMsfLayout().
commit()
Error NamedStreamMap::commit (BinaryStreamWriter & Writer) const
Definition at line 66 of file NamedStreamMap.cpp.
References llvm::pdb::Data, llvm::Error::success(), llvm::BinaryStreamWriter::writeFixedString(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by llvm::pdb::InfoStreamBuilder::commit().
entries()
StringMap< uint32_t > NamedStreamMap::entries () const
Definition at line 108 of file NamedStreamMap.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::try_emplace().
Referenced by llvm::pdb::InfoStream::named_streams().
get()
bool NamedStreamMap::get (StringRef Stream, uint32_t & StreamNo) const
Definition at line 100 of file NamedStreamMap.cpp.
Referenced by llvm::pdb::InfoStream::getNamedStreamIndex(), and llvm::pdb::PDBFileBuilder::getNamedStreamIndex().
getString()
StringRef NamedStreamMap::getString (uint32_t Offset) const
Definition at line 91 of file NamedStreamMap.cpp.
References assert().
Referenced by hashString(), and llvm::pdb::NamedStreamMapTraits::storageKeyToLookupKey().
hashString()
uint32_t NamedStreamMap::hashString (uint32_t Offset) const
Definition at line 96 of file NamedStreamMap.cpp.
References getString(), and llvm::pdb::hashStringV1().
load()
Error NamedStreamMap::load (BinaryStreamReader & Stream)
Definition at line 51 of file NamedStreamMap.cpp.
References llvm::StringRef::begin(), llvm::pdb::corrupt_file, llvm::StringRef::end(), llvm::joinErrors(), llvm::BinaryStreamReader::readFixedString(), and llvm::BinaryStreamReader::readInteger().
Referenced by llvm::pdb::InfoStream::reload().
set()
void NamedStreamMap::set (StringRef Stream, uint32_t StreamNo)
Definition at line 124 of file NamedStreamMap.cpp.
Referenced by llvm::pdb::PDBFileBuilder::getGsiBuilder().
size()
uint32_t NamedStreamMap::size () const
Definition at line 89 of file NamedStreamMap.cpp.
Friends And Related Function Documentation
NamedStreamMapBuilder
friend class NamedStreamMapBuilder friend
Definition at line 39 of file NamedStreamMap.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NamedStreamMap.h
lib/DebugInfo/PDB/Native/NamedStreamMap.cpp