LLVM: llvm::DDGBuilder Class Reference
llvm::DDGBuilder Class Reference
Concrete implementation of a pure data dependence graph builder.
#include "llvm/Analysis/DDG.h"
Public Member Functions
DDGBuilder (DataDependenceGraph &G, DependenceInfo &D, const BasicBlockListType &BBs)
DDGNode & createRootNode () final override
Create the root node of the graph.
DDGNode & createFineGrainedNode (Instruction &I) final override
Create an atomic node in the graph given a single instruction.
DDGNode & createPiBlock (const NodeListType &L) final override
Create a pi-block node in the graph representing a group of nodes in an SCC of the graph.
DDGEdge & createDefUseEdge (DDGNode &Src, DDGNode &Tgt) final override
DDGEdge & createMemoryEdge (DDGNode &Src, DDGNode &Tgt) final override
DDGEdge & createRootedEdge (DDGNode &Src, DDGNode &Tgt) final override
const NodeListType & getNodesInPiBlock (const DDGNode &N) final override
bool shouldCreatePiBlocks () const final override
Return true if creation of pi-blocks are supported and desired, and false otherwise.
Public Member Functions inherited from llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >
AbstractDependenceGraphBuilder (DataDependenceGraph &G, DependenceInfo &D, const BasicBlockListType &BBs)
virtual ~AbstractDependenceGraphBuilder ()
void populate ()
The main entry to the graph construction algorithm.
void computeInstructionOrdinals ()
Compute ordinal numbers for each instruction and store them in a map for future look up.
void createFineGrainedNodes ()
Create fine grained nodes.
void createDefUseEdges ()
Analyze the def-use chains and create edges from the nodes containing definitions to the nodes containing the uses.
void createMemoryDependencyEdges ()
Analyze data dependencies that exist between memory loads or stores, in the graph nodes and create edges between them.
void createAndConnectRootNode ()
Create a root node and add edges such that each node in the graph is reachable from the root.
void createPiBlocks ()
Apply graph abstraction to groups of nodes that belong to a strongly connected component of the graph to create larger compound nodes called pi-blocks.
void sortNodesTopologically ()
Topologically sort the graph nodes.
Additional Inherited Members
Public Types inherited from llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >
using ClassesType = EquivalenceClasses< BasicBlock *>
using NodeListType = SmallVector< NodeType *, 4 >
Protected Types inherited from llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >
using BasicBlockListType = SmallVectorImpl< BasicBlock *>
using InstToNodeMap = DenseMap< Instruction *, NodeType *>
Map types to map instructions to nodes used when populating the graph.
using InstToOrdinalMap = DenseMap< Instruction *, size_t >
Map Types to map instruction/nodes to an ordinal number.
using NodeToOrdinalMap = DenseMap< NodeType *, size_t >
Protected Member Functions inherited from llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >
virtual EdgeType & createDefUseEdge (NodeType &Src, NodeType &Tgt)=0
Create a def-use edge going from Src to Tgt.
virtual EdgeType & createMemoryEdge (NodeType &Src, NodeType &Tgt)=0
Create a memory dependence edge going from Src to Tgt.
virtual EdgeType & createRootedEdge (NodeType &Src, NodeType &Tgt)=0
Create a rooted edge going from Src to Tgt .
virtual const NodeListType & getNodesInPiBlock (const NodeType &N)=0
Given a pi-block node, return a vector of all the nodes contained within it.
virtual void destroyEdge (EdgeType &E)
Deallocate memory of edge E.
virtual void destroyNode (NodeType &N)
Deallocate memory of node N.
size_t getOrdinal (Instruction &I)
Given an instruction I return its associated ordinal number.
size_t getOrdinal (NodeType &N)
Given a node N return its associated ordinal number.
Protected Attributes inherited from llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >
DataDependenceGraph & Graph
Reference to the graph that gets built by a concrete implementation of this builder.
DependenceInfo & DI
Dependence information used to create memory dependence edges in the graph.
const BasicBlockListType & BBList
The list of basic blocks to consider when building the graph.
InstToNodeMap IMap
A mapping from instructions to the corresponding nodes in the graph.
InstToOrdinalMap InstOrdinalMap
A mapping from each instruction to an ordinal number.
NodeToOrdinalMap NodeOrdinalMap
A mapping from nodes to an ordinal number.
Detailed Description
Concrete implementation of a pure data dependence graph builder.
This class provides custom implementation for the pure-virtual functions used in the generic dependence graph build algorithm.
For information about time complexity of the build algorithm see the comments near the declaration of AbstractDependenceGraphBuilder.
Definition at line 342 of file DDG.h.
Constructor & Destructor Documentation
DDGBuilder()
llvm::DDGBuilder::DDGBuilder (DataDependenceGraph & G, DependenceInfo & D, const BasicBlockListType & BBs) inline
Definition at line 344 of file DDG.h.
Member Function Documentation
createDefUseEdge()
DDGEdge& llvm::DDGBuilder::createDefUseEdge (DDGNode & Src, DDGNode & Tgt) inline final override
Definition at line 365 of file DDG.h.
References assert(), E, and llvm::DDGEdge::RegisterDefUse.
createFineGrainedNode()
DDGNode& llvm::DDGBuilder::createFineGrainedNode (Instruction & I) inline final override virtual
Create an atomic node in the graph given a single instruction.
Implements llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >.
Definition at line 353 of file DDG.h.
References assert(), and I.
createMemoryEdge()
DDGEdge& llvm::DDGBuilder::createMemoryEdge (DDGNode & Src, DDGNode & Tgt) inline final override
Definition at line 371 of file DDG.h.
References assert(), E, and llvm::DDGEdge::MemoryDependence.
createPiBlock()
DDGNode& llvm::DDGBuilder::createPiBlock (const NodeListType & L) inline final override virtual
Create a pi-block node in the graph representing a group of nodes in an SCC of the graph.
Implements llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >.
Definition at line 359 of file DDG.h.
References assert().
createRootedEdge()
DDGEdge& llvm::DDGBuilder::createRootedEdge (DDGNode & Src, DDGNode & Tgt) inline final override
Definition at line 377 of file DDG.h.
References assert(), E, and llvm::DDGEdge::Rooted.
createRootNode()
DDGNode& llvm::DDGBuilder::createRootNode () inline final override virtual
Create the root node of the graph.
Implements llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >.
Definition at line 347 of file DDG.h.
References assert(), and llvm::NVPTX::PTXCvtMode::RN.
getNodesInPiBlock()
const NodeListType& llvm::DDGBuilder::getNodesInPiBlock (const DDGNode & N) inline final override
Definition at line 385 of file DDG.h.
References assert(), llvm::dyn_cast(), E, G, N, and llvm::operator<<().
shouldCreatePiBlocks()
bool DDGBuilder::shouldCreatePiBlocks () const final override virtual
Return true if creation of pi-blocks are supported and desired, and false otherwise.
Reimplemented from llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >.
Definition at line 260 of file DDG.cpp.
References CreatePiBlocks.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DDG.h
lib/Analysis/DDG.cpp