LLVM: llvm::TimerGroup Class Reference
llvm::TimerGroup Class Reference
The TimerGroup class is used to group together related timers into a single report that is printed when the TimerGroup is destroyed.
#include "llvm/Support/Timer.h"
Public Member Functions
TimerGroup (StringRef Name, StringRef Description)
TimerGroup (StringRef Name, StringRef Description, const StringMap< TimeRecord > &Records)
~TimerGroup ()
void setName (StringRef NewName, StringRef NewDescription)
void print (raw_ostream &OS, bool ResetAfterPrint=false)
Print any started timers in this group, optionally resetting timers after printing them.
void clear ()
Clear all timers in this group.
const char * printJSONValues (raw_ostream &OS, const char *delim)
Static Public Member Functions
static void printAll (raw_ostream &OS)
This static method prints all timers.
static void clearAll ()
Clear out all timers.
static const char * printAllJSONValues (raw_ostream &OS, const char *delim)
Prints all timers as JSON key/value pairs.
static void ConstructTimerLists ()
Ensure global timer group lists are initialized.
static std::unique_ptr< TimerGroup > aquireDefaultGroup ()
This makes the default group unmanaged, and lets the user manage the group's lifetime.
Friends
class Timer
void PrintStatisticsJSON (raw_ostream &OS)
Print statistics in JSON format.
Detailed Description
The TimerGroup class is used to group together related timers into a single report that is printed when the TimerGroup is destroyed.
It is illegal to destroy a TimerGroup object before all of the Timers in it are gone. A TimerGroup can be specified for a newly created timer in its constructor.
Definition at line 170 of file Timer.h.
Constructor & Destructor Documentation
TimerGroup() [1/2]
TimerGroup::TimerGroup (StringRef Name, StringRef Description) explicit
Definition at line 233 of file Timer.cpp.
References TimerGroupList.
TimerGroup() [2/2]
TimerGroup::TimerGroup (StringRef Name, StringRef Description, const StringMap< TimeRecord > & Records) explicit
Definition at line 245 of file Timer.cpp.
References assert(), P, and llvm::StringMapImpl::size().
~TimerGroup()
TimerGroup::~TimerGroup ()
Definition at line 254 of file Timer.cpp.
References llvm::Timer::clear(), llvm::CreateInfoOutputFile(), llvm::format(), getDefaultTimerGroup(), llvm::TimeRecord::getMemUsed(), llvm::TimeRecord::getProcessTime(), llvm::TimeRecord::getSystemTime(), llvm::TimeRecord::getUserTime(), llvm::TimeRecord::getWallTime(), llvm::Timer::hasTriggered(), llvm::raw_ostream::indent(), llvm::Timer::isRunning(), llvm::make_range(), llvm::TimeRecord::print(), llvm::Record::print(), llvm::sort(), llvm::Timer::startTimer(), llvm::Timer::stopTimer(), and llvm::T.
Member Function Documentation
aquireDefaultGroup()
std::unique_ptr< TimerGroup > TimerGroup::aquireDefaultGroup () static
This makes the default group unmanaged, and lets the user manage the group's lifetime.
Definition at line 445 of file Timer.cpp.
References llvm::ManagedStatic< C, Creator, Deleter >::claim().
clear()
void TimerGroup::clear ()
Clear all timers in this group.
Definition at line 381 of file Timer.cpp.
References llvm::Timer::clear(), and llvm::T.
clearAll()
void TimerGroup::clearAll () static
Clear out all timers.
This is mostly used to disable automatic printing on shutdown, when timers have already been printed explicitly using printAll or printJSONValues.
Definition at line 394 of file Timer.cpp.
References assert(), llvm::format(), and llvm::None.
ConstructTimerLists()
void TimerGroup::ConstructTimerLists () static
Ensure global timer group lists are initialized.
This function is mostly used by the Statistic code to influence the construction and destruction order of the global timer lists.
Definition at line 441 of file Timer.cpp.
Referenced by llvm::TrackingStatistic::RegisterStatistic().
print()
void TimerGroup::print (raw_ostream & OS, bool ResetAfterPrint = false)
Print any started timers in this group, optionally resetting timers after printing them.
Definition at line 369 of file Timer.cpp.
Referenced by llvm::TimePassesHandler::print().
printAll()
void TimerGroup::printAll (raw_ostream & OS) static
This static method prints all timers.
Definition at line 387 of file Timer.cpp.
printAllJSONValues()
const char * TimerGroup::printAllJSONValues (raw_ostream & OS, const char * delim) static
Prints all timers as JSON key/value pairs.
Definition at line 434 of file Timer.cpp.
Referenced by llvm::PrintStatisticsJSON().
printJSONValues()
const char * TimerGroup::printJSONValues (raw_ostream & OS, const char * delim)
Definition at line 411 of file Timer.cpp.
References llvm::TimeRecord::getMemUsed(), llvm::TimeRecord::getSystemTime(), llvm::TimeRecord::getUserTime(), and llvm::TimeRecord::getWallTime().
setName()
void llvm::TimerGroup::setName (StringRef NewName, StringRef NewDescription) inline
Definition at line 204 of file Timer.h.
References llvm::StringRef::begin(), clear(), llvm::StringRef::end(), and llvm::TimeRecord::print().
Friends And Related Function Documentation
PrintStatisticsJSON
void PrintStatisticsJSON (raw_ostream & OS) friend
Print statistics in JSON format.
This does include all global timers (
See also
Timer, TimerGroup). Note that the timers are cleared after printing and will not be printed in human readable form or in a second call of PrintStatisticsJSON().
Timer
friend class Timer friend
Definition at line 239 of file Timer.h.
The documentation for this class was generated from the following files:
include/llvm/Support/Timer.h
lib/Support/Timer.cpp