LLVM: llvm::MCInstrInfo Class Reference
llvm::MCInstrInfo Class Reference
Interface to description of machine instruction set.
#include "llvm/MC/MCInstrInfo.h"
Public Member Functions
void InitMCInstrInfo (const MCInstrDesc *D, const unsigned *NI, const char *ND, unsigned NO)
Initialize MCInstrInfo, called by TableGen auto-generated routines.
unsigned getNumOpcodes () const
const MCInstrDesc & get (unsigned Opcode) const
Return the machine instruction descriptor that corresponds to the specified instruction opcode.
StringRef getName (unsigned Opcode) const
Returns the name for the instructions with the given opcode.
Detailed Description
Interface to description of machine instruction set.
Definition at line 23 of file MCInstrInfo.h.
Member Function Documentation
get()
const MCInstrDesc& llvm::MCInstrInfo::get (unsigned Opcode) const inline
Return the machine instruction descriptor that corresponds to the specified instruction opcode.
Definition at line 44 of file MCInstrInfo.h.
References assert().
Referenced by llvm::MachineBasicBlock::addLiveIn(), addSegmentsWithValNo(), allPhiOperandsUndefined(), llvm::analyzeArguments(), AnyAliasLiveIn(), llvm::CombinerHelper::applyCombineExtendingLoads(), buildEXP(), canClobberPhysRegDefs(), canClobberReachingPhysRegUse(), llvm::TailDuplicator::canTailDuplicate(), CheckForPhysRegDependency(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), CombineCVTAToLocal(), combineRestoreADD(), combineRestoreOR(), combineRestoreSETHIi(), ComputeCommonTailLength(), llvm::TargetSchedModel::computeInstrLatency(), llvm::MCSchedModel::computeInstrLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), llvm::TargetSchedModel::computeReciprocalThroughput(), llvm::constrainOperandRegClass(), llvm::FastISel::constrainOperandRegClass(), convertCalleeSaveRestoreToSPPrePostIncDec(), convertImplicitDefToConstZero(), createARMMCRelocationInfo(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), createLanaiElfRelocation(), createMCStreamer(), createMipsObjectTargetStreamer(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), createWinCOFFStreamer(), doesNotGeneratecode(), llvm::SplitEditor::dump(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBuildPairF64Pseudo(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), EmitCfiOffset(), llvm::InstrEmitter::EmitDbgLabel(), llvm::InstrEmitter::EmitDbgValue(), EmitDefCfaOffset(), EmitDefCfaRegister(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitFrameOffsetAdj(), emitIncrement(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::MachineRegisterInfo::EmitLiveInCopies(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostLd(), emitPostSt(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), emitReadCycleWidePseudo(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSplitF64Pseudo(), emitThumb2LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), emitXBegin(), llvm::MipsMCCodeEmitter::encodeInstruction(), llvm::MSP430MCCodeEmitter::encodeInstruction(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::X86_MC::X86MCInstrAnalysis::evaluateMemoryOperandAddress(), llvm::InstructionSelector::executeMatchTable(), expandLoadStackGuard(), expandMOV32r1(), ExpandMOVImmSExti8(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), expandXorFP(), llvm::FastISel::fastEmitInst_(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::FastISel::fastEmitInst_f(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrr(), llvm::finalizeBundle(), findNextInsertLocation(), findTemporariesForLR(), FixedPointIntrinsicToOpcode(), llvm::fixStackStores(), foldPatchpoint(), FuseInst(), FuseTwoAddrInst(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), genFusedMultiply(), genMaddR(), genNeg(), getComparePred(), getCondFromBranch(), llvm::HexagonMCInstrInfo::getDesc(), llvm::ARMTargetLowering::getExceptionSelectorRegister(), llvm::LLVMDisasmContext::getInstrInfo(), llvm::PPCMCCodeEmitter::getInstSizeInBytes(), getItineraryLatency(), getLatency(), llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::TargetMachine::getMCInstrInfo(), getNewSource(), getPhysicalRegisterVT(), llvm::AVRInstPrinter::getPrettyRegisterName(), llvm::MCSchedModel::getReciprocalThroughput(), getRegsUsedByPHIs(), getRetpolineSymbol(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::BPFTargetLowering::getTargetNodeName(), llvm::HexagonMCInstrInfo::getType(), getUnderlyingArgRegs(), llvm::MipsTargetLowering::HandleByVal(), HandleVRSaveUpdate(), HasConditionalBranch(), IfNeededExtSP(), IfNeededLDAWSP(), llvm::MipsFunctionInfo::initGlobalBaseReg(), INITIALIZE_PASS(), llvm::ResourcePriorityQueue::initNumRegDefsLeft(), llvm::SITargetLowering::insertCopiesSplitCSR(), llvm::AArch64TargetLowering::insertCopiesSplitCSR(), llvm::PPCTargetLowering::insertCopiesSplitCSR(), insertCopy(), insertCSRRestores(), insertCSRSaves(), insertDivByZeroTrap(), InsertLDR_STR(), InsertNewDef(), insertNopBeforeInstruction(), insertPHI(), InsertSEH(), llvm::MCInstrAnalysis::isBranch(), llvm::MCInstrAnalysis::isCall(), llvm::MCInstrAnalysis::isConditionalBranch(), llvm::isCopyMulResult(), isHardwareLoop(), llvm::MCInstrAnalysis::isIndirectBranch(), llvm::X86TargetLowering::isIntDivCheap(), isPCRel32Branch(), llvm::ResourcePriorityQueue::isResourceAvailable(), llvm::MCInstrAnalysis::isReturn(), isRIPRelative(), llvm::HexagonMCInstrInfo::isSolo(), llvm::MCInstrAnalysis::isTerminator(), llvm::MCInstrAnalysis::isUnconditionalBranch(), IsUnconditionalJump(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), LowerFPToInt(), MakeM0Inst(), mapWasmLandingPadIndex(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SelectionDAGISel::mayRaiseFPException(), mergeOperations(), Mips16WhichOp8uOr16simm(), llvm::PPCHazardRecognizer970::PPCHazardRecognizer970(), llvm::WebAssemblyInstPrinter::printInst(), llvm::X86InstPrinterCommon::printInstFlags(), printMasking(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::PPCInstPrinter::printOperand(), llvm::X86ATTInstPrinter::printVecCompareInstr(), llvm::X86IntelInstPrinter::printVecCompareInstr(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), ProcessSourceNode(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::TargetInstrInfo::reassociateOps(), replaceFI(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::ResourcePriorityQueue::reserveResources(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), RestoreSpillList(), rewritesSort(), llvm::UnreachableBlockElimPass::run(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MachinePipeliner::runOnMachineFunction(), llvm::SelectionDAGISel::SelectCodeCommon(), selectCopy(), llvm::FunctionLoweringInfo::set(), setCallTargetReg(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::ResourcePriorityQueue::SUSchedulingCost(), usedAsAddr(), llvm::LegalizerInfo::verify(), llvm::RISCVInstrInfo::verifyInstruction(), and llvm::mca::verifyOperands().
getName()
StringRef llvm::MCInstrInfo::getName (unsigned Opcode) const inline
Returns the name for the instructions with the given opcode.
Definition at line 50 of file MCInstrInfo.h.
References assert().
Referenced by fuseInstructionPair(), getInstructionID(), llvm::HexagonMCInstrInfo::getName(), llvm::MCInstPrinter::getOpcodeName(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::MachineInstr::print(), selectCopy(), llvm::LegalizerInfo::verify(), and llvm::mca::verifyOperands().
getNumOpcodes()
unsigned llvm::MCInstrInfo::getNumOpcodes () const inline
Definition at line 40 of file MCInstrInfo.h.
InitMCInstrInfo()
void llvm::MCInstrInfo::InitMCInstrInfo (const MCInstrDesc * D, const unsigned * NI, const char * ND, unsigned NO) inline
Initialize MCInstrInfo, called by TableGen auto-generated routines.
DO NOT USE.
Definition at line 32 of file MCInstrInfo.h.
References D.
The documentation for this class was generated from the following file:
include/llvm/MC/MCInstrInfo.h