LLVM: llvm::RegisterBank Class Reference
llvm::RegisterBank Class Reference
This class implements the register bank concept.
#include "llvm/CodeGen/GlobalISel/RegisterBank.h"
Public Member Functions
RegisterBank (unsigned ID, const char *Name, unsigned Size, const uint32_t *CoveredClasses, unsigned NumRegClasses)
unsigned getID () const
Get the identifier of this register bank.
const char * getName () const
Get a user friendly name of this register bank.
unsigned getSize () const
Get the maximal size in bits that fits in this register bank.
bool isValid () const
Check whether this instance is ready to be used.
bool verify (const TargetRegisterInfo &TRI) const
Check if this register bank is valid.
bool covers (const TargetRegisterClass &RC) const
Check whether this register bank covers RC.
bool operator== (const RegisterBank &OtherRB) const
Check whether OtherRB is the same as this.
bool operator!= (const RegisterBank &OtherRB) const
void dump (const TargetRegisterInfo *TRI=nullptr) const
Dump the register mask on dbgs() stream.
void print (raw_ostream &OS, bool IsForDebug=false, const TargetRegisterInfo *TRI=nullptr) const
Print the register mask on OS.
Detailed Description
This class implements the register bank concept.
Two instances of RegisterBank must have different ID. This property is enforced by the RegisterBankInfo class.
Definition at line 28 of file RegisterBank.h.
Constructor & Destructor Documentation
RegisterBank()
RegisterBank::RegisterBank (unsigned ID, const char * Name, unsigned Size, const uint32_t * CoveredClasses, unsigned NumRegClasses)
Definition at line 23 of file RegisterBank.cpp.
References llvm::BitVector::resize(), and llvm::BitVector::setBitsInMask().
Member Function Documentation
covers()
bool RegisterBank::covers (const TargetRegisterClass & RC) const
Check whether this register bank covers RC.
In other words, check if this register bank fully covers the registers that RC contains.
Precondition
isValid()
Definition at line 60 of file RegisterBank.cpp.
References assert(), llvm::TargetRegisterClass::getID(), isValid(), and llvm::BitVector::test().
Referenced by llvm::AArch64RegisterBankInfo::AArch64RegisterBankInfo(), llvm::ARMRegisterBankInfo::ARMRegisterBankInfo(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::RegisterBankInfo::getRegBankFromConstraints(), getSize(), and llvm::X86RegisterBankInfo::X86RegisterBankInfo().
dump()
LLVM_DUMP_METHOD void RegisterBank::dump (const TargetRegisterInfo * TRI = nullptr) const
Dump the register mask on dbgs() stream.
The dump is verbose.
Definition at line 81 of file RegisterBank.cpp.
References llvm::dbgs(), and print().
Referenced by operator!=().
getID()
unsigned llvm::RegisterBank::getID () const inline
Get the identifier of this register bank.
Definition at line 47 of file RegisterBank.h.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), canTurnIntoCOPY(), changeFCMPPredToAArch64CC(), llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), llvm::AMDGPURegisterBankInfo::copyCost(), findIntrinsicID(), getInsertVecEltOpInfo(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), getLaneCopyOpcode(), getLogicalBitOpcode(), getMinClassForRegBank(), llvm::AMDGPURegisterBankInfo::getRegBankID(), llvm::SIRegisterInfo::getRegClassForSizeOnBank(), getRegClassFromGRPhysReg(), getVectorSHLImm(), hashPartialMapping(), isConstant(), isValidCopy(), isVectorRegisterBank(), operator==(), print(), selectCopy(), selectMergeValues(), selectUnmergeValues(), llvm::AMDGPUInstructionSelector::setupMF(), and shouldUseAndMask().
getName()
const char* llvm::RegisterBank::getName () const inline
Get a user friendly name of this register bank.
Should be used only for debugging purposes.
Definition at line 51 of file RegisterBank.h.
Referenced by print(), and llvm::printRegClassOrBank().
getSize()
unsigned llvm::RegisterBank::getSize () const inline
Get the maximal size in bits that fits in this register bank.
Definition at line 54 of file RegisterBank.h.
References covers(), isValid(), operator==(), TRI, and verify().
Referenced by llvm::AArch64RegisterBankInfo::AArch64RegisterBankInfo(), llvm::ARMRegisterBankInfo::ARMRegisterBankInfo(), print(), and llvm::X86RegisterBankInfo::X86RegisterBankInfo().
isValid()
bool RegisterBank::isValid () const
Check whether this instance is ready to be used.
Definition at line 65 of file RegisterBank.cpp.
References llvm::BitVector::empty().
Referenced by covers(), getSize(), print(), and verify().
operator!=()
bool llvm::RegisterBank::operator!= (const RegisterBank & OtherRB) const inline
Definition at line 75 of file RegisterBank.h.
References dump(), operator==(), and print().
operator==()
bool RegisterBank::operator== (const RegisterBank & OtherRB) const
Check whether OtherRB is the same as this.
Definition at line 71 of file RegisterBank.cpp.
References assert(), and getID().
Referenced by getSize(), and operator!=().
print()
void RegisterBank::print (raw_ostream & OS, bool IsForDebug = false, const TargetRegisterInfo * TRI = nullptr) const
Print the register mask on OS.
If IsForDebug is false, then only the name of the register bank is printed. Otherwise, all the fields are printing. TRI is then used to print the name of the register classes that this register bank covers.
Definition at line 86 of file RegisterBank.cpp.
References assert(), llvm::BitVector::count(), llvm::BitVector::empty(), getID(), getName(), llvm::TargetRegisterInfo::getNumRegClasses(), getSize(), isValid(), and llvm::BitVector::size().
Referenced by dump(), operator!=(), and llvm::operator<<().
verify()
bool RegisterBank::verify (const TargetRegisterInfo & TRI) const
Check if this register bank is valid.
In other words, if it has been properly constructed.
Note
This method does not check anything when assertions are disabled.
Returns
True is the check was successful.
Definition at line 31 of file RegisterBank.cpp.
References assert(), and isValid().
Referenced by getSize().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/RegisterBank.h
lib/CodeGen/GlobalISel/RegisterBank.cpp