LLVM: llvm::ScheduleHazardRecognizer Class Reference
llvm::ScheduleHazardRecognizer Class Reference
HazardRecognizer - This determines whether or not an instruction can be issued this cycle, and whether or not a noop needs to be inserted to handle the hazard.
#include "llvm/CodeGen/ScheduleHazardRecognizer.h"
Public Types
enum HazardType { NoHazard, Hazard, NoopHazard }
Public Member Functions
ScheduleHazardRecognizer ()=default
virtual ~ScheduleHazardRecognizer ()
unsigned getMaxLookAhead () const
bool isEnabled () const
virtual bool atIssueLimit () const
atIssueLimit - Return true if no more instructions may be issued in this cycle.
virtual HazardType getHazardType (SUnit *m, int Stalls=0)
getHazardType - Return the hazard type of emitting this node.
virtual void Reset ()
Reset - This callback is invoked when a new block of instructions is about to be schedule.
virtual void EmitInstruction (SUnit *)
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
virtual void EmitInstruction (MachineInstr *)
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
virtual unsigned PreEmitNoops (SUnit *)
PreEmitNoops - This callback is invoked prior to emitting an instruction.
virtual unsigned PreEmitNoops (MachineInstr *)
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
virtual bool ShouldPreferAnother (SUnit *)
ShouldPreferAnother - This callback may be invoked if getHazardType returns NoHazard.
virtual void AdvanceCycle ()
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
virtual void RecedeCycle ()
RecedeCycle - This callback is invoked whenever the next bottom-up instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
virtual void EmitNoop ()
EmitNoop - This callback is invoked when a noop was added to the instruction stream.
Protected Attributes
unsigned MaxLookAhead = 0
MaxLookAhead - Indicate the number of cycles in the scoreboard state.
Detailed Description
HazardRecognizer - This determines whether or not an instruction can be issued this cycle, and whether or not a noop needs to be inserted to handle the hazard.
Definition at line 25 of file ScheduleHazardRecognizer.h.
Member Enumeration Documentation
HazardType
enum llvm::ScheduleHazardRecognizer::HazardType
Enumerator
NoHazard
Hazard
NoopHazard
Definition at line 37 of file ScheduleHazardRecognizer.h.
Constructor & Destructor Documentation
ScheduleHazardRecognizer()
llvm::ScheduleHazardRecognizer::ScheduleHazardRecognizer () default
~ScheduleHazardRecognizer()
ScheduleHazardRecognizer::~ScheduleHazardRecognizer () virtual default
Referenced by llvm::ScheduleDAGTopologicalSort::ScheduleDAGTopologicalSort().
Member Function Documentation
AdvanceCycle()
virtual void llvm::ScheduleHazardRecognizer::AdvanceCycle () inline virtual
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
This should increment the internal state of the hazard recognizer so that previously "Hazard" instructions will now not be hazards.
Reimplemented in llvm::ScoreboardHazardRecognizer, llvm::GCNHazardRecognizer, llvm::PPCHazardRecognizer970, llvm::HexagonHazardRecognizer, llvm::PPCDispatchGroupSBHazardRecognizer, and llvm::ARMHazardRecognizer.
Definition at line 104 of file ScheduleHazardRecognizer.h.
Referenced by EmitNoop().
atIssueLimit()
virtual bool llvm::ScheduleHazardRecognizer::atIssueLimit () const inline virtual
atIssueLimit - Return true if no more instructions may be issued in this cycle.
FIXME: remove this once MachineScheduler is the only client.
Reimplemented in llvm::ScoreboardHazardRecognizer, and llvm::GCNHazardRecognizer.
Definition at line 51 of file ScheduleHazardRecognizer.h.
EmitInstruction() [1/2]
virtual void llvm::ScheduleHazardRecognizer::EmitInstruction (SUnit *) inline virtual
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
Reimplemented in llvm::ScoreboardHazardRecognizer, llvm::SystemZHazardRecognizer, llvm::GCNHazardRecognizer, llvm::PPCHazardRecognizer970, llvm::HexagonHazardRecognizer, llvm::PPCDispatchGroupSBHazardRecognizer, and llvm::ARMHazardRecognizer.
Definition at line 71 of file ScheduleHazardRecognizer.h.
EmitInstruction() [2/2]
virtual void llvm::ScheduleHazardRecognizer::EmitInstruction (MachineInstr *) inline virtual
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
Reimplemented in llvm::GCNHazardRecognizer.
Definition at line 75 of file ScheduleHazardRecognizer.h.
EmitNoop()
virtual void llvm::ScheduleHazardRecognizer::EmitNoop () inline virtual
EmitNoop - This callback is invoked when a noop was added to the instruction stream.
Reimplemented in llvm::GCNHazardRecognizer, and llvm::PPCDispatchGroupSBHazardRecognizer.
Definition at line 113 of file ScheduleHazardRecognizer.h.
References AdvanceCycle().
getHazardType()
virtual HazardType llvm::ScheduleHazardRecognizer::getHazardType (SUnit * m, int Stalls = 0) inline virtual
getHazardType - Return the hazard type of emitting this node.
There are three possible results. Either:
NoHazard: it is legal to issue this instruction on this cycle.
Hazard: issuing this instruction would stall the machine. If some other instruction is available, issue it first.
NoopHazard: issuing this instruction would break the program. If some other instruction can be issued, do so, otherwise issue a noop.
Reimplemented in llvm::ScoreboardHazardRecognizer, llvm::SystemZHazardRecognizer, llvm::GCNHazardRecognizer, llvm::PPCHazardRecognizer970, llvm::HexagonHazardRecognizer, llvm::PPCDispatchGroupSBHazardRecognizer, and llvm::ARMHazardRecognizer.
Definition at line 60 of file ScheduleHazardRecognizer.h.
References NoHazard.
getMaxLookAhead()
unsigned llvm::ScheduleHazardRecognizer::getMaxLookAhead () const inline
Definition at line 43 of file ScheduleHazardRecognizer.h.
References MaxLookAhead.
Referenced by llvm::GCNHazardRecognizer::AdvanceCycle().
isEnabled()
bool llvm::ScheduleHazardRecognizer::isEnabled () const inline
Definition at line 45 of file ScheduleHazardRecognizer.h.
Referenced by llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
PreEmitNoops() [1/2]
virtual unsigned llvm::ScheduleHazardRecognizer::PreEmitNoops (SUnit *) inline virtual
PreEmitNoops - This callback is invoked prior to emitting an instruction.
It should return the number of noops to emit prior to the provided instruction. Note: This is only used during PostRA scheduling. EmitNoop is not called for these noops.
Reimplemented in llvm::GCNHazardRecognizer, and llvm::PPCDispatchGroupSBHazardRecognizer.
Definition at line 82 of file ScheduleHazardRecognizer.h.
Referenced by llvm::PPCDispatchGroupSBHazardRecognizer::PreEmitNoops().
PreEmitNoops() [2/2]
virtual unsigned llvm::ScheduleHazardRecognizer::PreEmitNoops (MachineInstr *) inline virtual
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
Reimplemented in llvm::GCNHazardRecognizer.
Definition at line 88 of file ScheduleHazardRecognizer.h.
RecedeCycle()
virtual void llvm::ScheduleHazardRecognizer::RecedeCycle () inline virtual
RecedeCycle - This callback is invoked whenever the next bottom-up instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
Reimplemented in llvm::ScoreboardHazardRecognizer, llvm::GCNHazardRecognizer, llvm::PPCDispatchGroupSBHazardRecognizer, and llvm::ARMHazardRecognizer.
Definition at line 109 of file ScheduleHazardRecognizer.h.
Reset()
virtual void llvm::ScheduleHazardRecognizer::Reset () inline virtual
Reset - This callback is invoked when a new block of instructions is about to be schedule.
The hazard state should be set to an initialized state.
Reimplemented in llvm::ScoreboardHazardRecognizer, llvm::SystemZHazardRecognizer, llvm::PPCHazardRecognizer970, llvm::HexagonHazardRecognizer, llvm::PPCDispatchGroupSBHazardRecognizer, and llvm::ARMHazardRecognizer.
Definition at line 67 of file ScheduleHazardRecognizer.h.
ShouldPreferAnother()
virtual bool llvm::ScheduleHazardRecognizer::ShouldPreferAnother (SUnit *) inline virtual
ShouldPreferAnother - This callback may be invoked if getHazardType returns NoHazard.
If, even though there is no hazard, it would be better to schedule another available instruction, this callback should return true.
Reimplemented in llvm::HexagonHazardRecognizer, and llvm::PPCDispatchGroupSBHazardRecognizer.
Definition at line 95 of file ScheduleHazardRecognizer.h.
Referenced by llvm::PPCDispatchGroupSBHazardRecognizer::ShouldPreferAnother().
Member Data Documentation
MaxLookAhead
unsigned llvm::ScheduleHazardRecognizer::MaxLookAhead = 0 protected
MaxLookAhead - Indicate the number of cycles in the scoreboard state.
Important to restore the state after backtracking. Additionally, MaxLookAhead=0 identifies a fake recognizer, allowing the client to bypass virtual calls. Currently the PostRA scheduler ignores it.
Definition at line 31 of file ScheduleHazardRecognizer.h.
Referenced by llvm::GCNHazardRecognizer::GCNHazardRecognizer(), getMaxLookAhead(), insertNoopInBundle(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ScheduleHazardRecognizer.h
lib/CodeGen/ScheduleDAG.cpp