LLVM: llvm::Any Class Reference
llvm::Any Class Reference
#include "llvm/ADT/Any.h"
Public Member Functions
Any ()=default
Any (const Any &Other)
template<typename T , typename std::enable_if< llvm::conjunction< llvm::negation< std::is_same< typename std::decay< T >::type, Any >>, llvm::negation< std::is_convertible< Any, typename std::decay< T >::type >>, std::is_copy_constructible< typename std::decay< T >::type >>::value, int >::type = 0>
Any (T &&Value)
Any (Any &&Other)
Any & swap (Any &Other)
Any & operator= (Any Other)
bool hasValue () const
void reset ()
Friends
template<class T >
T any_cast (const Any &Value)
template<class T >
T any_cast (Any &Value)
template<class T >
T any_cast (Any &&Value)
template<class T >
const T * any_cast (const Any *Value)
template<class T >
T * any_cast (Any *Value)
template<typename T >
bool any_isa (const Any &Value)
Detailed Description
Definition at line 26 of file Any.h.
Constructor & Destructor Documentation
Any() [1/4]
llvm::Any::Any () default
Any() [2/4]
llvm::Any::Any (const Any & Other) inline
Definition at line 56 of file Any.h.
References llvm::T.
Any() [3/4]
template<typename T , typename std::enable_if< llvm::conjunction< llvm::negation< std::is_same< typename std::decay< T >::type, Any >>, llvm::negation< std::is_convertible< Any, typename std::decay< T >::type >>, std::is_copy_constructible< typename std::decay< T >::type >>::value, int >::type = 0> llvm::Any::Any (T && Value) inline
Definition at line 79 of file Any.h.
Any() [4/4]
llvm::Any::Any (Any && Other) inline
Definition at line 84 of file Any.h.
Member Function Documentation
hasValue()
bool llvm::Any::hasValue () const inline
Definition at line 96 of file Any.h.
operator=()
Any& llvm::Any::operator= (Any Other) inline
Definition at line 91 of file Any.h.
reset()
void llvm::Any::reset () inline
Definition at line 98 of file Any.h.
References any_cast, and any_isa.
swap()
Any& llvm::Any::swap (Any & Other) inline
Definition at line 86 of file Any.h.
References std::swap().
Friends And Related Function Documentation
any_cast [1/5]
template<class T > T any_cast (const Any & Value) friend
Definition at line 122 of file Any.h.
Referenced by llvm::any_cast(), and reset().
any_cast [2/5]
template<class T > T any_cast (Any & Value) friend
Definition at line 128 of file Any.h.
any_cast [3/5]
template<class T > T any_cast (Any && Value) friend
Definition at line 134 of file Any.h.
any_cast [4/5]
template<class T > const T* any_cast (const Any * Value) friend
Definition at line 140 of file Any.h.
any_cast [5/5]
template<class T > T* any_cast (Any * Value) friend
Definition at line 149 of file Any.h.
any_isa
template<typename T > bool any_isa (const Any & Value) friend
Definition at line 114 of file Any.h.
Referenced by reset().
The documentation for this class was generated from the following file:
include/llvm/ADT/Any.h