LLVM: llvm::object::MachORebaseEntry Class Reference
llvm::object::MachORebaseEntry Class Reference
MachORebaseEntry encapsulates the current state in the decompression of rebasing opcodes.
#include "llvm/Object/MachO.h"
Public Member Functions
MachORebaseEntry (Error *Err, const MachOObjectFile *O, ArrayRef< uint8_t > opcodes, bool is64Bit)
int32_t segmentIndex () const
uint64_t segmentOffset () const
StringRef typeName () const
StringRef segmentName () const
StringRef sectionName () const
uint64_t address () const
bool operator== (const MachORebaseEntry &) const
void moveNext ()
Friends
class MachOObjectFile
Detailed Description
MachORebaseEntry encapsulates the current state in the decompression of rebasing opcodes.
This allows you to iterate through the compressed table of rebasing using: Error Err; for (const llvm::object::MachORebaseEntry &Entry : Obj->rebaseTable(&Err)) { } if (Err) { report error ...
Definition at line 167 of file MachO.h.
Constructor & Destructor Documentation
MachORebaseEntry()
MachORebaseEntry::MachORebaseEntry (Error * Err, const MachOObjectFile * O, ArrayRef< uint8_t > opcodes, bool is64Bit)
Definition at line 3106 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), and moveNext().
Member Function Documentation
address()
uint64_t MachORebaseEntry::address () const
Definition at line 3421 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::BindRebaseAddress(), and SegmentOffset().
moveNext()
void MachORebaseEntry::moveNext ()
Definition at line 3122 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::begin(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::decodeULEB128(), llvm::ArrayRef< T >::end(), error, llvm::format(), malformedError(), readULEB128(), llvm::MachO::REBASE_IMMEDIATE_MASK, llvm::MachO::REBASE_OPCODE_ADD_ADDR_IMM_SCALED, llvm::MachO::REBASE_OPCODE_ADD_ADDR_ULEB, llvm::MachO::REBASE_OPCODE_DO_REBASE_ADD_ADDR_ULEB, llvm::MachO::REBASE_OPCODE_DO_REBASE_IMM_TIMES, llvm::MachO::REBASE_OPCODE_DO_REBASE_ULEB_TIMES, llvm::MachO::REBASE_OPCODE_DO_REBASE_ULEB_TIMES_SKIPPING_ULEB, llvm::MachO::REBASE_OPCODE_DONE, llvm::MachO::REBASE_OPCODE_MASK, llvm::MachO::REBASE_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB, llvm::MachO::REBASE_OPCODE_SET_TYPE_IMM, llvm::MachO::REBASE_TYPE_TEXT_PCREL32, llvm::object::MachOObjectFile::RebaseEntryCheckSegAndOffsets(), SegmentOffset(), and llvm::Twine::utohexstr().
Referenced by MachORebaseEntry().
operator==()
bool MachORebaseEntry::operator== (const MachORebaseEntry & Other) const
Definition at line 3425 of file MachOObjectFile.cpp.
References assert(), and llvm::ArrayRef< T >::data().
sectionName()
StringRef MachORebaseEntry::sectionName () const
Definition at line 3415 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::BindRebaseSectionName(), and SegmentOffset().
segmentIndex()
int32_t MachORebaseEntry::segmentIndex () const
Definition at line 3391 of file MachOObjectFile.cpp.
segmentName()
StringRef MachORebaseEntry::segmentName () const
Definition at line 3409 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::BindRebaseSegmentName().
segmentOffset()
uint64_t MachORebaseEntry::segmentOffset () const
Definition at line 3393 of file MachOObjectFile.cpp.
References SegmentOffset().
typeName()
StringRef MachORebaseEntry::typeName () const
Definition at line 3395 of file MachOObjectFile.cpp.
References llvm::MachO::REBASE_TYPE_POINTER, llvm::MachO::REBASE_TYPE_TEXT_ABSOLUTE32, and llvm::MachO::REBASE_TYPE_TEXT_PCREL32.
Friends And Related Function Documentation
MachOObjectFile
friend class MachOObjectFile friend
Definition at line 184 of file MachO.h.
The documentation for this class was generated from the following files:
include/llvm/Object/MachO.h
lib/Object/MachOObjectFile.cpp