LLVM: lib/Analysis/CodeMetrics.cpp File Reference
CodeMetrics.cpp File Reference
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "code-metrics"
Functions
static void appendSpeculatableOperands (const Value *V, SmallPtrSetImpl< const Value *> &Visited, SmallVectorImpl< const Value *> &Worklist)
static void completeEphemeralValues (SmallPtrSetImpl< const Value *> &Visited, SmallVectorImpl< const Value *> &Worklist, SmallPtrSetImpl< const Value *> &EphValues)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "code-metrics"
Definition at line 23 of file CodeMetrics.cpp.
Function Documentation
appendSpeculatableOperands()
static void appendSpeculatableOperands (const Value * V, SmallPtrSetImpl< const Value *> & Visited, SmallVectorImpl< const Value *> & Worklist) static
Definition at line 28 of file CodeMetrics.cpp.
References llvm::dyn_cast(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isSafeToSpeculativelyExecute(), llvm::User::operands(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::CodeMetrics::collectEphemeralValues(), and completeEphemeralValues().
completeEphemeralValues()
static void completeEphemeralValues (SmallPtrSetImpl< const Value *> & Visited, SmallVectorImpl< const Value *> & Worklist, SmallPtrSetImpl< const Value *> & EphValues) static
Definition at line 41 of file CodeMetrics.cpp.
References llvm::all_of(), appendSpeculatableOperands(), assert(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, llvm::SmallVectorBase::size(), and llvm::Value::users().
Referenced by llvm::CodeMetrics::collectEphemeralValues().