LLVM: lib/IR/Comdat.cpp File Reference
Comdat.cpp File Reference
#include "llvm-c/Comdat.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/Module.h"
Functions
LLVMComdatRef LLVMGetOrInsertComdat (LLVMModuleRef M, const char *Name)
Return the Comdat in the module with the specified name.
LLVMComdatRef LLVMGetComdat (LLVMValueRef V)
Get the Comdat assigned to the given global object.
void LLVMSetComdat (LLVMValueRef V, LLVMComdatRef C)
Assign the Comdat to the given global object.
LLVMComdatSelectionKind LLVMGetComdatSelectionKind (LLVMComdatRef C)
void LLVMSetComdatSelectionKind (LLVMComdatRef C, LLVMComdatSelectionKind kind)
Function Documentation
LLVMGetComdat()
LLVMComdatRef LLVMGetComdat (LLVMValueRef V)
Get the Comdat assigned to the given global object.
See also
llvm::GlobalObject::getComdat()
Definition at line 32 of file Comdat.cpp.
References G, llvm::GlobalObject::getComdat(), and llvm::wrap().
LLVMGetComdatSelectionKind()
LLVMComdatSelectionKind LLVMGetComdatSelectionKind (LLVMComdatRef C)
Definition at line 42 of file Comdat.cpp.
References llvm::Comdat::Any, llvm::Comdat::ExactMatch, llvm::Comdat::getSelectionKind(), llvm::Comdat::Largest, llvm_unreachable, LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDuplicatesComdatSelectionKind, LLVMSameSizeComdatSelectionKind, llvm::Comdat::NoDuplicates, llvm::Comdat::SameSize, and llvm::unwrap().
LLVMGetOrInsertComdat()
LLVMComdatRef LLVMGetOrInsertComdat (LLVMModuleRef M, const char * Name)
Return the Comdat in the module with the specified name.
It is created if it didn't already exist.
See also
llvm::Module::getOrInsertComdat()
Definition at line 28 of file Comdat.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMSetComdat()
void LLVMSetComdat (LLVMValueRef V, LLVMComdatRef C)
Assign the Comdat to the given global object.
See also
llvm::GlobalObject::setComdat()
Definition at line 37 of file Comdat.cpp.
References G, llvm::GlobalObject::setComdat(), and llvm::unwrap().
LLVMSetComdatSelectionKind()
void LLVMSetComdatSelectionKind (LLVMComdatRef C, LLVMComdatSelectionKind kind)
Definition at line 58 of file Comdat.cpp.
References llvm::Comdat::Any, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDuplicatesComdatSelectionKind, LLVMSameSizeComdatSelectionKind, llvm::Comdat::NoDuplicates, llvm::Comdat::SameSize, llvm::Comdat::setSelectionKind(), and llvm::unwrap().