LLVM: lib/MC/ConstantPools.cpp File Reference
ConstantPools.cpp File Reference
#include "llvm/MC/ConstantPools.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/Casting.h"
Functions
static void emitConstantPool (MCStreamer &Streamer, MCSection *Section, ConstantPool &CP)
Function Documentation
emitConstantPool()
static void emitConstantPool (MCStreamer & Streamer, MCSection * Section, ConstantPool & CP) static
Definition at line 79 of file ConstantPools.cpp.
References llvm::ConstantPool::emitEntries(), llvm::ConstantPool::empty(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::AssemblerConstantPools::emitAll(), and llvm::AssemblerConstantPools::emitForCurrentSection().