LLVM: lib/Transforms/IPO/ConstantMerge.cpp File Reference
ConstantMerge.cpp File Reference
#include "llvm/Transforms/IPO/ConstantMerge.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Transforms/IPO.h"
#include <algorithm>
#include <cassert>
#include <utility>
Macros
#define DEBUG_TYPE "constmerge"
Enumerations
enum CanMerge { CanMerge::No, CanMerge::Yes }
Functions
STATISTIC (NumIdenticalMerged, "Number of identical global constants merged")
static void FindUsedValues (GlobalVariable *LLVMUsed, SmallPtrSetImpl< const GlobalValue *> &UsedValues)
Find values that are marked as llvm.used.
static bool IsBetterCanonical (const GlobalVariable &A, const GlobalVariable &B)
static bool hasMetadataOtherThanDebugLoc (const GlobalVariable *GV)
static void copyDebugLocMetadata (const GlobalVariable *From, GlobalVariable *To)
static unsigned getAlignment (GlobalVariable *GV)
static bool isUnmergeableGlobal (GlobalVariable *GV, const SmallPtrSetImpl< const GlobalValue *> &UsedGlobals)
static CanMerge makeMergeable (GlobalVariable *Old, GlobalVariable *New)
static void replace (Module &M, GlobalVariable *Old, GlobalVariable *New)
static bool mergeConstants (Module &M)
INITIALIZE_PASS (ConstantMergeLegacyPass, "constmerge", "Merge Duplicate Global Constants", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "constmerge"
Definition at line 41 of file ConstantMerge.cpp.
Enumeration Type Documentation
CanMerge
enum CanMerge strong
Enumerator
No
Yes
Definition at line 104 of file ConstantMerge.cpp.
Function Documentation
copyDebugLocMetadata()
static void copyDebugLocMetadata (const GlobalVariable * From, GlobalVariable * To) static
Definition at line 79 of file ConstantMerge.cpp.
References llvm::GlobalVariable::addDebugInfo(), and llvm::GlobalVariable::getDebugInfo().
Referenced by replace().
FindUsedValues()
static void FindUsedValues (GlobalVariable * LLVMUsed, SmallPtrSetImpl< const GlobalValue *> & UsedValues) static
Find values that are marked as llvm.used.
Definition at line 46 of file ConstantMerge.cpp.
References llvm::numbers::e, llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::Value::stripPointerCasts().
Referenced by mergeConstants().
getAlignment()
static unsigned getAlignment (GlobalVariable * GV) static
Definition at line 87 of file ConstantMerge.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::GlobalObject::getAlignment(), llvm::Module::getDataLayout(), llvm::GlobalValue::getParent(), and llvm::DataLayout::getPreferredAlignment().
Referenced by replace().
hasMetadataOtherThanDebugLoc()
static bool hasMetadataOtherThanDebugLoc (const GlobalVariable * GV) static
Definition at line 70 of file ConstantMerge.cpp.
References llvm::GlobalObject::getAllMetadata().
Referenced by llvm::Instruction::getAllMetadataOtherThanDebugLoc(), makeMergeable(), and mergeConstants().
INITIALIZE_PASS()
INITIALIZE_PASS (ConstantMergeLegacyPass , "constmerge" , "Merge Duplicate Global Constants" , false , false)
Definition at line 283 of file ConstantMerge.cpp.
IsBetterCanonical()
static bool IsBetterCanonical (const GlobalVariable & A, const GlobalVariable & B) static
Definition at line 59 of file ConstantMerge.cpp.
References llvm::GlobalValue::hasGlobalUnnamedAddr(), and llvm::GlobalValue::hasLocalLinkage().
Referenced by mergeConstants().
isUnmergeableGlobal()
static bool isUnmergeableGlobal (GlobalVariable * GV, const SmallPtrSetImpl< const GlobalValue *> & UsedGlobals) static
Definition at line 95 of file ConstantMerge.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getType(), llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::GlobalObject::hasSection(), and llvm::GlobalVariable::isConstant().
Referenced by mergeConstants().
makeMergeable()
static CanMerge makeMergeable (GlobalVariable * Old, GlobalVariable * New) static
Definition at line 105 of file ConstantMerge.cpp.
References assert(), llvm::GlobalValue::hasGlobalUnnamedAddr(), hasMetadataOtherThanDebugLoc(), No, llvm::GlobalValue::None, llvm::GlobalValue::setUnnamedAddr(), and Yes.
Referenced by mergeConstants().
mergeConstants()
static bool mergeConstants (Module & M) static
Definition at line 135 of file ConstantMerge.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::numbers::e, E, llvm::GlobalVariable::eraseFromParent(), FindUsedValues(), llvm::Module::getGlobalVariable(), llvm::GlobalVariable::getInitializer(), llvm::Value::getName(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalValue::hasLocalLinkage(), hasMetadataOtherThanDebugLoc(), IsBetterCanonical(), isUnmergeableGlobal(), llvm::GlobalValue::isWeakForLinker(), LLVM_DEBUG, makeMergeable(), No, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Constant::removeDeadConstantUsers(), llvm::replace(), llvm::SmallVectorBase::size(), and llvm::Value::use_empty().
Referenced by llvm::ConstantMergePass::run().
replace()
static void replace (Module & M, GlobalVariable * Old, GlobalVariable * New) static
Definition at line 116 of file ConstantMerge.cpp.
References assert(), copyDebugLocMetadata(), llvm::dbgs(), llvm::GlobalVariable::eraseFromParent(), llvm::GlobalObject::getAlignment(), getAlignment(), llvm::Value::getName(), llvm::GlobalValue::hasLocalLinkage(), LLVM_DEBUG, llvm::max(), llvm::Value::replaceAllUsesWith(), and llvm::GlobalObject::setAlignment().
Referenced by llvm::CodeViewDebug::CodeViewDebug(), llvm::sys::path::convert_to_slash(), getSignature(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), GetVBR(), isIgnorableInst(), lowerV8I16GeneralSingleInputShuffle(), llvm::sys::path::native(), llvm::LiveVariables::replaceKillInstruction(), simplifyAllocaArraySize(), llvm::UnrollLoop(), and llvm::sroa::AllocaSliceRewriter::visit().
STATISTIC()
STATISTIC (NumIdenticalMerged , "Number of identical global constants merged")