LLVM: lib/IR/ConstantRange.cpp File Reference
ConstantRange.cpp File Reference
#include "llvm/ADT/APInt.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
Functions
static ConstantRange makeExactMulNUWRegion (const APInt &V)
Exact mul nuw region for single element RHS.
static ConstantRange makeExactMulNSWRegion (const APInt &V)
Exact mul nsw region for single element RHS.
static ConstantRange getPreferredRange (const ConstantRange &CR1, const ConstantRange &CR2, ConstantRange::PreferredRangeType Type)
Function Documentation
getPreferredRange()
static ConstantRange getPreferredRange (const ConstantRange & CR1, const ConstantRange & CR2, ConstantRange::PreferredRangeType Type) static
Definition at line 427 of file ConstantRange.cpp.
References llvm::ConstantRange::isSignWrappedSet(), llvm::ConstantRange::isSizeStrictlySmallerThan(), llvm::ConstantRange::isWrappedSet(), llvm::ConstantRange::Signed, and llvm::ConstantRange::Unsigned.
Referenced by llvm::ConstantRange::intersectWith(), and llvm::ConstantRange::unionWith().
makeExactMulNSWRegion()
static ConstantRange makeExactMulNSWRegion (const APInt & V) static
Exact mul nsw region for single element RHS.
Definition at line 197 of file ConstantRange.cpp.
References llvm::ConstantRange::ConstantRange(), llvm::APInt::DOWN, llvm::APInt::getBitWidth(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::APInt::isAllOnesValue(), llvm::APInt::isNegative(), llvm::APInt::isOneValue(), llvm::LegalizeActions::Lower, llvm::APIntOps::RoundingSDiv(), and llvm::APInt::UP.
Referenced by llvm::ConstantRange::makeGuaranteedNoWrapRegion().
makeExactMulNUWRegion()
static ConstantRange makeExactMulNUWRegion (const APInt & V) static
Exact mul nuw region for single element RHS.
Definition at line 184 of file ConstantRange.cpp.
References llvm::APInt::DOWN, llvm::APInt::getBitWidth(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::ConstantRange::getNonEmpty(), llvm::APIntOps::RoundingUDiv(), and llvm::APInt::UP.
Referenced by llvm::ConstantRange::makeGuaranteedNoWrapRegion().