LLVM: lib/DebugInfo/CodeView/ContinuationRecordBuilder.cpp File Reference
ContinuationRecordBuilder.cpp File Reference
#include "llvm/DebugInfo/CodeView/ContinuationRecordBuilder.h"
#include "llvm/DebugInfo/CodeView/CodeViewTypes.def"
Macros
#define TYPE_RECORD(EnumName, EnumVal, Name)
#define TYPE_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName)
#define MEMBER_RECORD(EnumName, EnumVal, Name)
#define MEMBER_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName)
Functions
static void addPadding (BinaryStreamWriter &Writer)
static SegmentInjection InjectFieldList (TypeLeafKind::LF_FIELDLIST)
static SegmentInjection InjectMethodOverloadList (TypeLeafKind::LF_METHODLIST)
static TypeLeafKind getTypeLeafKind (ContinuationRecordKind CK)
Variables
static constexpr uint32_t ContinuationLength = sizeof(ContinuationRecord)
static constexpr uint32_t MaxSegmentLength
Macro Definition Documentation
MEMBER_RECORD
#define MEMBER_RECORD (EnumName, EnumVal, Name)
Value:
template void llvm::codeview::ContinuationRecordBuilder::writeMemberType(\
      Name##Record &Record);
Definition at line 247 of file ContinuationRecordBuilder.cpp.
MEMBER_RECORD_ALIAS
#define MEMBER_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName)
Definition at line 250 of file ContinuationRecordBuilder.cpp.
TYPE_RECORD
#define TYPE_RECORD (EnumName, EnumVal, Name)
Definition at line 245 of file ContinuationRecordBuilder.cpp.
TYPE_RECORD_ALIAS
#define TYPE_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName)
Definition at line 246 of file ContinuationRecordBuilder.cpp.
Function Documentation
addPadding()
static void addPadding (BinaryStreamWriter & Writer) static
Definition at line 21 of file ContinuationRecordBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::cantFail(), llvm::BinaryStreamWriter::getOffset(), InjectFieldList(), InjectMethodOverloadList(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by llvm::createX86PadShortFunctions(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
getTypeLeafKind()
static TypeLeafKind getTypeLeafKind (ContinuationRecordKind CK) inline static
Definition at line 41 of file ContinuationRecordBuilder.cpp.
References llvm::codeview::FieldList.
Referenced by llvm::codeview::ContinuationRecordBuilder::begin(), and llvm::codeview::ContinuationRecordBuilder::end().
InjectFieldList()
static SegmentInjection InjectFieldList (TypeLeafKind::LF_FIELDLIST) static
Referenced by addPadding().
InjectMethodOverloadList()
static SegmentInjection InjectMethodOverloadList (TypeLeafKind::LF_METHODLIST) static
Referenced by addPadding().
Variable Documentation
ContinuationLength
constexpr uint32_t ContinuationLength = sizeof(ContinuationRecord) static
Definition at line 37 of file ContinuationRecordBuilder.cpp.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberBegin(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
MaxSegmentLength
constexpr uint32_t MaxSegmentLength static
Initial value:
=
    MaxRecordLength - ContinuationLength
Definition at line 38 of file ContinuationRecordBuilder.cpp.
Referenced by llvm::codeview::ContinuationRecordBuilder::writeMemberType().