LLVM: lib/Transforms/Instrumentation/ControlHeightReduction.cpp File Reference
ControlHeightReduction.cpp File Reference
#include "llvm/Transforms/Instrumentation/ControlHeightReduction.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/RegionInfo.h"
#include "llvm/Analysis/RegionIterator.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <set>
#include <sstream>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "chr"
#define CHR_DEBUG(X) LLVM_DEBUG(X)
Functions
static void parseCHRFilterFiles ()
INITIALIZE_PASS_BEGIN (ControlHeightReductionLegacyPass, "chr", "Reduce control height in the hot paths", false, false) INITIALIZE_PASS_END(ControlHeightReductionLegacyPass
static raw_ostream LLVM_ATTRIBUTE_UNUSED & operator<< (raw_ostream &OS, const CHRStats &Stats)
static raw_ostream & operator<< (raw_ostream &OS, const CHRScope &Scope)
static bool shouldApply (Function &F, ProfileSummaryInfo &PSI)
static void LLVM_ATTRIBUTE_UNUSED dumpIR (Function &F, const char *Label, CHRStats *Stats)
static bool isHoistableInstructionType (Instruction *I)
static bool isHoistable (Instruction *I, DominatorTree &DT)
static std::set< Value * > getBaseValues (Value *V, DominatorTree &DT, DenseMap< Value *, std::set< Value *>> &Visited)
static bool checkHoistValue (Value *V, Instruction *InsertPoint, DominatorTree &DT, DenseSet< Instruction *> &Unhoistables, DenseSet< Instruction *> *HoistStops, DenseMap< Instruction *, bool > &Visited)
static bool checkMDProf (MDNode *MD, BranchProbability &TrueProb, BranchProbability &FalseProb)
static BranchProbability getCHRBiasThreshold ()
template<typename K , typename S , typename M >
static bool checkBias (K *Key, BranchProbability TrueProb, BranchProbability FalseProb, S &TrueSet, S &FalseSet, M &BiasMap)
static bool checkBiasedBranch (BranchInst *BI, Region *R, DenseSet< Region *> &TrueBiasedRegionsGlobal, DenseSet< Region *> &FalseBiasedRegionsGlobal, DenseMap< Region *, BranchProbability > &BranchBiasMap)
static bool checkBiasedSelect (SelectInst *SI, Region *R, DenseSet< SelectInst *> &TrueBiasedSelectsGlobal, DenseSet< SelectInst *> &FalseBiasedSelectsGlobal, DenseMap< SelectInst *, BranchProbability > &SelectBiasMap)
static Instruction * getBranchInsertPoint (RegInfo &RI)
static DenseSet< Value * > getCHRConditionValuesForRegion (RegInfo &RI)
static bool shouldSplit (Instruction *InsertPoint, DenseSet< Value *> &PrevConditionValues, DenseSet< Value *> &ConditionValues, DominatorTree &DT, DenseSet< Instruction *> &Unhoistables)
static void getSelectsInScope (CHRScope *Scope, DenseSet< Instruction *> &Output)
static bool hasAtLeastTwoBiasedBranches (CHRScope *Scope)
bool CHRScopeSorter (CHRScope *Scope1, CHRScope *Scope2)
static void hoistValue (Value *V, Instruction *HoistPoint, Region *R, HoistStopMapTy &HoistStopMap, DenseSet< Instruction *> &HoistedSet, DenseSet< PHINode *> &TrivialPHIs, DominatorTree &DT)
static void hoistScopeConditions (CHRScope *Scope, Instruction *HoistPoint, DenseSet< PHINode *> &TrivialPHIs, DominatorTree &DT)
static bool negateICmpIfUsedByBranchOrSelectOnly (ICmpInst *ICmp, Instruction *ExcludedUser, CHRScope *Scope)
static void insertTrivialPHIs (CHRScope *Scope, BasicBlock *EntryBlock, BasicBlock *ExitBlock, DenseSet< PHINode *> &TrivialPHIs)
static void LLVM_ATTRIBUTE_UNUSED assertCHRRegionsHaveBiasedBranchOrSelect (CHRScope *Scope)
static void LLVM_ATTRIBUTE_UNUSED assertBranchOrSelectConditionHoisted (CHRScope *Scope, BasicBlock *PreEntryBlock)
static void LLVM_ATTRIBUTE_UNUSED dumpScopes (SmallVectorImpl< CHRScope *> &Scopes, const char *Label)
Variables
static cl::opt< bool > ForceCHR ("force-chr", cl::init(false), cl::Hidden, cl::desc("Apply CHR for all functions"))
static cl::opt< double > CHRBiasThreshold ("chr-bias-threshold", cl::init(0.99), cl::Hidden, cl::desc("CHR considers a branch bias greater than this ratio as biased"))
static cl::opt< unsigned > CHRMergeThreshold ("chr-merge-threshold", cl::init(2), cl::Hidden, cl::desc("CHR merges a group of N branches/selects where N >= this value"))
static cl::opt< std::string > CHRModuleList ("chr-module-list", cl::init(""), cl::Hidden, cl::desc("Specify file to retrieve the list of modules to apply CHR to"))
static cl::opt< std::string > CHRFunctionList ("chr-function-list", cl::init(""), cl::Hidden, cl::desc("Specify file to retrieve the list of functions to apply CHR to"))
static StringSet CHRModules
static StringSet CHRFunctions
chr
Reduce control height in the hot paths
Reduce control height in the hot false
Macro Definition Documentation
CHR_DEBUG
#define CHR_DEBUG (X) LLVM_DEBUG(X)
Definition at line 46 of file ControlHeightReduction.cpp.
Referenced by assertBranchOrSelectConditionHoisted(), checkBiasedBranch(), checkBiasedSelect(), checkHoistValue(), dumpIR(), dumpScopes(), getBranchInsertPoint(), getSelectsInScope(), hasAtLeastTwoBiasedBranches(), hoistValue(), insertTrivialPHIs(), and shouldSplit().
DEBUG_TYPE
#define DEBUG_TYPE "chr"
Definition at line 44 of file ControlHeightReduction.cpp.
Referenced by assertBranchOrSelectConditionHoisted(), dumpScopes(), getBranchInsertPoint(), getSelectsInScope(), and hasAtLeastTwoBiasedBranches().
Function Documentation
assertBranchOrSelectConditionHoisted()
static void LLVM_ATTRIBUTE_UNUSED assertBranchOrSelectConditionHoisted (CHRScope * Scope, BasicBlock * PreEntryBlock) static
Definition at line 1666 of file ControlHeightReduction.cpp.
References assert(), assertCHRRegionsHaveBiasedBranchOrSelect(), llvm::AMDGPUISD::BFI, CHR_DEBUG, llvm::CloneBasicBlock(), llvm::RegionBase< Tr >::contains(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG_TYPE, llvm::User::dropAllReferences(), llvm::numbers::e, llvm::ValueMap< KeyT, ValueT, Config >::end(), llvm::Instruction::eraseFromParent(), F(), llvm::ValueMap< KeyT, ValueT, Config >::find(), getCHRBiasThreshold(), llvm::SelectInst::getCondition(), llvm::RegionBase< Tr >::getEntry(), llvm::RegionBase< Tr >::getExit(), llvm::BasicBlock::getInstList(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::BasicBlock::getSinglePredecessor(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), llvm::Optional< T >::getValue(), hoistScopeConditions(), I, insertTrivialPHIs(), llvm::BranchInst::isUnconditional(), llvm::BasicBlock::phis(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::RemapInstruction(), llvm::RF_IgnoreMissingLocals, llvm::RF_NoModuleLevelChanges, llvm::BranchInst::setCondition(), llvm::Instruction::setMetadata(), SI, llvm::SmallVectorBase::size(), llvm::SplitBlock(), Stats, and std::swap().
assertCHRRegionsHaveBiasedBranchOrSelect()
static void LLVM_ATTRIBUTE_UNUSED assertCHRRegionsHaveBiasedBranchOrSelect (CHRScope * Scope) static
Definition at line 1645 of file ControlHeightReduction.cpp.
References assert(), and SI.
Referenced by assertBranchOrSelectConditionHoisted().
checkBias()
template<typename K , typename S , typename M > static bool checkBias (K * Key, BranchProbability TrueProb, BranchProbability FalseProb, S & TrueSet, S & FalseSet, M & BiasMap) static
Definition at line 647 of file ControlHeightReduction.cpp.
References getCHRBiasThreshold(), and Threshold.
Referenced by checkBiasedBranch(), and checkBiasedSelect().
checkBiasedBranch()
static bool checkBiasedBranch (BranchInst * BI, Region * R, DenseSet< Region *> & TrueBiasedRegionsGlobal, DenseSet< Region *> & FalseBiasedRegionsGlobal, DenseMap< Region *, BranchProbability > & BranchBiasMap) static
Definition at line 665 of file ControlHeightReduction.cpp.
References assert(), checkBias(), checkMDProf(), CHR_DEBUG, llvm::dbgs(), llvm::RegionBase< Tr >::getExit(), llvm::Instruction::getMetadata(), llvm::BranchInst::getSuccessor(), llvm::BranchInst::isConditional(), and std::swap().
Referenced by getBranchInsertPoint().
checkBiasedSelect()
static bool checkBiasedSelect (SelectInst * SI, Region * R, DenseSet< SelectInst *> & TrueBiasedSelectsGlobal, DenseSet< SelectInst *> & FalseBiasedSelectsGlobal, DenseMap< SelectInst *, BranchProbability > & SelectBiasMap) static
Definition at line 696 of file ControlHeightReduction.cpp.
References checkBias(), checkMDProf(), CHR_DEBUG, llvm::dbgs(), and llvm::Instruction::getMetadata().
Referenced by getBranchInsertPoint().
checkHoistValue()
static bool checkHoistValue (Value * V, Instruction * InsertPoint, DominatorTree & DT, DenseSet< Instruction *> & Unhoistables, DenseSet< Instruction *> * HoistStops, DenseMap< Instruction *, bool > & Visited) static
Definition at line 557 of file ControlHeightReduction.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::begin(), CHR_DEBUG, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::end(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::Instruction::getParent(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), and isHoistable().
Referenced by getBranchInsertPoint(), hasAtLeastTwoBiasedBranches(), and shouldSplit().
checkMDProf()
static bool checkMDProf (MDNode * MD, BranchProbability & TrueProb, BranchProbability & FalseProb) static
Definition at line 610 of file ControlHeightReduction.cpp.
References assert(), llvm::BranchProbability::getBranchProbability(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), llvm::ConstantInt::getValue(), and llvm::APInt::getZExtValue().
Referenced by checkBiasedBranch(), and checkBiasedSelect().
CHRScopeSorter()
bool CHRScopeSorter (CHRScope * Scope1, CHRScope * Scope2)
Definition at line 1442 of file ControlHeightReduction.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::copy(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorBase::size(), and llvm::stable_sort().
dumpIR()
static void LLVM_ATTRIBUTE_UNUSED dumpIR (Function & F, const char * Label, CHRStats * Stats) static
Definition at line 457 of file ControlHeightReduction.cpp.
References assert(), CHR_DEBUG, llvm::dbgs(), llvm::Value::dump(), llvm::Module::getName(), llvm::Value::getName(), llvm::GlobalValue::getParent(), and print().
Referenced by dumpScopes().
dumpScopes()
static void LLVM_ATTRIBUTE_UNUSED dumpScopes (SmallVectorImpl< CHRScope *> & Scopes, const char * Label) static
Definition at line 1996 of file ControlHeightReduction.cpp.
References llvm::AMDGPUISD::BFI, CHR_DEBUG, llvm::dbgs(), DEBUG_TYPE, dumpIR(), llvm::SmallVectorBase::empty(), F(), runOnFunction(), shouldApply(), llvm::SmallVectorBase::size(), and Stats.
getBaseValues()
static std::set<Value *> getBaseValues (Value * V, DominatorTree & DT, DenseMap< Value *, std::set< Value *>> & Visited) static
Definition at line 517 of file ControlHeightReduction.cpp.
References I, and isHoistable().
Referenced by shouldSplit().
getBranchInsertPoint()
static Instruction* getBranchInsertPoint (RegInfo & RI) static
Definition at line 716 of file ControlHeightReduction.cpp.
References assert(), llvm::RegionBase< Tr >::begin(), llvm::MCID::Branch, checkBiasedBranch(), checkBiasedSelect(), checkHoistValue(), CHR_DEBUG, llvm::RegionBase< Tr >::contains(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), llvm::dbgs(), DEBUG_TYPE, llvm::dyn_cast(), E, llvm::RegionBase< Tr >::elements(), llvm::RegionBase< Tr >::end(), llvm::SelectInst::getCondition(), llvm::RegionBase< Tr >::getEntry(), llvm::RegionBase< Tr >::getExit(), llvm::Value::getName(), llvm::RegionBase< Tr >::getNameStr(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::RegionBase< Tr >::isTopLevelRegion(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::remove_if(), SI, llvm::SmallVectorBase::size(), and Stats.
Referenced by getSelectsInScope().
getCHRBiasThreshold()
static BranchProbability getCHRBiasThreshold () static
Definition at line 637 of file ControlHeightReduction.cpp.
References CHRBiasThreshold, and llvm::BranchProbability::getBranchProbability().
Referenced by assertBranchOrSelectConditionHoisted(), and checkBias().
getCHRConditionValuesForRegion()
static DenseSet<Value *> getCHRConditionValuesForRegion (RegInfo & RI) static
Definition at line 1046 of file ControlHeightReduction.cpp.
References llvm::SelectInst::getCondition(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and SI.
Referenced by getSelectsInScope().
getSelectsInScope()
static void getSelectsInScope (CHRScope * Scope, DenseSet< Instruction *> & Output) static
Definition at line 1128 of file ControlHeightReduction.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::begin(), CHR_DEBUG, llvm::dbgs(), DEBUG_TYPE, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), getBranchInsertPoint(), getCHRConditionValuesForRegion(), llvm::RegionBase< Tr >::getNameStr(), I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm_unreachable, llvm::SmallVectorTemplateBase< T >::push_back(), shouldSplit(), SI, llvm::SmallVectorBase::size(), and llvm::CallingConv::Tail.
hasAtLeastTwoBiasedBranches()
static bool hasAtLeastTwoBiasedBranches (CHRScope * Scope) static
Definition at line 1337 of file ControlHeightReduction.cpp.
References assert(), checkHoistValue(), CHR_DEBUG, CHRMergeThreshold, llvm::dbgs(), DEBUG_TYPE, llvm::SelectInst::getCondition(), llvm::RegionBase< Tr >::getEntry(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::SmallVectorTemplateBase< T >::push_back(), and SI.
hoistScopeConditions()
static void hoistScopeConditions (CHRScope * Scope, Instruction * HoistPoint, DenseSet< PHINode *> & TrivialPHIs, DominatorTree & DT) static
Definition at line 1503 of file ControlHeightReduction.cpp.
References llvm::SelectInst::getCondition(), llvm::RegionBase< Tr >::getEntry(), hoistValue(), and SI.
Referenced by assertBranchOrSelectConditionHoisted().
hoistValue()
static void hoistValue (Value * V, Instruction * HoistPoint, Region * R, HoistStopMapTy & HoistStopMap, DenseSet< Instruction *> & HoistedSet, DenseSet< PHINode *> & TrivialPHIs, DominatorTree & DT) static
Definition at line 1455 of file ControlHeightReduction.cpp.
References assert(), CHR_DEBUG, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::Instruction::getParent(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), isHoistableInstructionType(), and IT.
Referenced by hoistScopeConditions().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ControlHeightReductionLegacyPass , "chr" , "Reduce control height in the hot paths" , false , false)
Referenced by parseCHRFilterFiles().
insertTrivialPHIs()
static void insertTrivialPHIs (CHRScope * Scope, BasicBlock * EntryBlock, BasicBlock * ExitBlock, DenseSet< PHINode *> & TrivialPHIs) static
Definition at line 1578 of file ControlHeightReduction.cpp.
References llvm::PHINode::addIncoming(), CHR_DEBUG, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), llvm::PHINode::Create(), llvm::dbgs(), llvm::BasicBlock::front(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), LLVM_ATTRIBUTE_UNUSED, llvm::pred_begin(), llvm::pred_end(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), and Users.
Referenced by assertBranchOrSelectConditionHoisted().
isHoistable()
static bool isHoistable (Instruction * I, DominatorTree & DT) static
Definition at line 506 of file ControlHeightReduction.cpp.
References isHoistableInstructionType(), and llvm::isSafeToSpeculativelyExecute().
Referenced by checkHoistValue(), and getBaseValues().
isHoistableInstructionType()
static bool isHoistableInstructionType (Instruction * I) static
Definition at line 497 of file ControlHeightReduction.cpp.
References I.
Referenced by hoistValue(), and isHoistable().
negateICmpIfUsedByBranchOrSelectOnly()
static bool negateICmpIfUsedByBranchOrSelectOnly (ICmpInst * ICmp, Instruction * ExcludedUser, CHRScope * Scope) static
Definition at line 1529 of file ControlHeightReduction.cpp.
References assert(), llvm::CmpInst::getInversePredicate(), llvm::CmpInst::getPredicate(), llvm_unreachable, llvm::CmpInst::setPredicate(), SI, and llvm::Value::users().
operator<<() [1/2]
static raw_ostream LLVM_ATTRIBUTE_UNUSED& operator<< (raw_ostream & OS, const CHRStats & Stats) inline static
Definition at line 431 of file ControlHeightReduction.cpp.
operator<<() [2/2]
static raw_ostream& operator<< (raw_ostream & OS, const CHRScope & Scope) inline static
Definition at line 438 of file ControlHeightReduction.cpp.
parseCHRFilterFiles()
static void parseCHRFilterFiles () static
Definition at line 70 of file ControlHeightReduction.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), CHRFunctionList, CHRModuleList, llvm::errs(), F(), llvm::MemoryBuffer::getFile(), llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, INITIALIZE_PASS_END(), llvm::initializeControlHeightReductionLegacyPassPass(), llvm::StringSet< AllocatorTy >::insert(), runOnFunction(), and llvm::StringRef::split().
Referenced by llvm::ControlHeightReductionPass::ControlHeightReductionPass().
shouldApply()
static bool shouldApply (Function & F, ProfileSummaryInfo & PSI) static
Definition at line 443 of file ControlHeightReduction.cpp.
References assert(), CHRFunctionList, CHRFunctions, CHRModuleList, CHRModules, llvm::StringMap< ValueTy, AllocatorTy >::count(), ForceCHR, llvm::Module::getName(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::ProfileSummaryInfo::hasProfileSummary(), and llvm::ProfileSummaryInfo::isFunctionEntryHot().
Referenced by dumpScopes().
shouldSplit()
static bool shouldSplit (Instruction * InsertPoint, DenseSet< Value *> & PrevConditionValues, DenseSet< Value *> & ConditionValues, DominatorTree & DT, DenseSet< Instruction *> & Unhoistables) static
Definition at line 1065 of file ControlHeightReduction.cpp.
References assert(), checkHoistValue(), CHR_DEBUG, llvm::dbgs(), and getBaseValues().
Referenced by getSelectsInScope().
Variable Documentation
chr
chr
Definition at line 136 of file ControlHeightReduction.cpp.
CHRBiasThreshold
cl::opt<double> CHRBiasThreshold("chr-bias-threshold", cl::init(0.99), cl::Hidden, cl::desc("CHR considers a branch bias greater than this ratio as biased")) static
Referenced by getCHRBiasThreshold().
CHRFunctionList
cl::opt<std::string> CHRFunctionList("chr-function-list", cl::init(""), cl::Hidden, cl::desc("Specify file to retrieve the list of functions to apply CHR to")) static
Referenced by parseCHRFilterFiles(), and shouldApply().
CHRFunctions
StringSet CHRFunctions static
Definition at line 68 of file ControlHeightReduction.cpp.
Referenced by shouldApply().
CHRMergeThreshold
cl::opt<unsigned> CHRMergeThreshold("chr-merge-threshold", cl::init(2), cl::Hidden, cl::desc("CHR merges a group of N branches/selects where N >= this value")) static
Referenced by hasAtLeastTwoBiasedBranches().
CHRModuleList
cl::opt<std::string> CHRModuleList("chr-module-list", cl::init(""), cl::Hidden, cl::desc("Specify file to retrieve the list of modules to apply CHR to")) static
Referenced by parseCHRFilterFiles(), and shouldApply().
CHRModules
StringSet CHRModules static
Definition at line 67 of file ControlHeightReduction.cpp.
Referenced by shouldApply().
false
Reduce control height in the hot false
Definition at line 136 of file ControlHeightReduction.cpp.
ForceCHR
cl::opt<bool> ForceCHR("force-chr", cl::init(false), cl::Hidden, cl::desc("Apply CHR for all functions")) static
Referenced by shouldApply().
paths
Reduce control height in the hot paths
Definition at line 136 of file ControlHeightReduction.cpp.