LLVM: lib/Transforms/Coroutines/CoroEarly.cpp File Reference
CoroEarly.cpp File Reference
#include "CoroInternal.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "coro-early"
Functions
static void setCannotDuplicate (CoroIdInst *CoroId)
INITIALIZE_PASS (CoroEarlyLegacy, "coro-early", "Lower early coroutine intrinsics", false, false) Pass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-early"
Definition at line 22 of file CoroEarly.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (CoroEarlyLegacy , "coro-early" , "Lower early coroutine intrinsics" , false , false)
Definition at line 271 of file CoroEarly.cpp.
setCannotDuplicate()
static void setCannotDuplicate (CoroIdInst * CoroId) static
Definition at line 147 of file CoroEarly.cpp.
References llvm::Function::addFnAttr(), CORO_PRESPLIT_ATTR, llvm::coro::declaresIntrinsics(), llvm::CoroSubFnInst::DestroyIndex, F(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getIntrinsicID(), llvm::PassRegistry::getPassRegistry(), I, llvm::ARM_PROC::IE, llvm::initializeCoroEarlyLegacyPass(), llvm::inst_begin(), llvm::inst_end(), PREPARED_FOR_SPLIT, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::CoroSubFnInst::ResumeIndex, runOnFunction(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setCannotDuplicate(), llvm::AnalysisUsage::setPreservesCFG(), UNPREPARED_FOR_SPLIT, and llvm::Value::users().
Referenced by llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::setCannotDuplicate().