LLVM: lib/Transforms/Coroutines/CoroCleanup.cpp File Reference
CoroCleanup.cpp File Reference
#include "CoroInternal.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
Macros
#define DEBUG_TYPE "coro-cleanup"
Functions
static void simplifyCFG (Function &F)
static void lowerSubFn (IRBuilder<> &Builder, CoroSubFnInst *SubFn)
INITIALIZE_PASS (CoroCleanupLegacy, "coro-cleanup", "Lower all coroutine related intrinsics", false, false) Pass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-cleanup"
Definition at line 20 of file CoroCleanup.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (CoroCleanupLegacy , "coro-cleanup" , "Lower all coroutine related intrinsics" , false , false)
Definition at line 136 of file CoroCleanup.cpp.
lowerSubFn()
static void lowerSubFn (IRBuilder<> & Builder, CoroSubFnInst * SubFn) static
Definition at line 40 of file CoroCleanup.cpp.
References Context, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::coro::declaresIntrinsics(), E, F(), llvm::StructType::get(), llvm::ConstantTokenNone::get(), llvm::Value::getContext(), llvm::CoroSubFnInst::getFrame(), llvm::CoroSubFnInst::getIndex(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::PassRegistry::getPassRegistry(), llvm::Type::getPointerTo(), llvm::ConstantInt::getTrue(), I, llvm::initializeCoroCleanupLegacyPass(), llvm::inst_begin(), llvm::inst_end(), llvm::SPII::Load, llvm::Value::replaceAllUsesWith(), runOnFunction(), llvm::IRBuilderBase::SetInsertPoint(), llvm::AnalysisUsage::setPreservesAll(), and llvm::simplifyCFG().
simplifyCFG()
static void simplifyCFG (Function & F) static
Definition at line 31 of file CoroCleanup.cpp.
References llvm::legacy::FunctionPassManager::add(), llvm::createCFGSimplificationPass(), and llvm::GlobalValue::getParent().