LLVM: lib/ProfileData/Coverage/CoverageMappingReader.cpp File Reference
CoverageMappingReader.cpp File Reference
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/Error.h"
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/COFF.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <vector>
Macros
#define DEBUG_TYPE "coverage-mapping"
Functions
static Expected< bool > isCoverageMappingDummy (uint64_t Hash, StringRef Mapping)
template<typename T , support::endianness Endian>
static Error readCoverageMappingData (InstrProfSymtab &ProfileNames, StringRef Data, std::vector< BinaryCoverageReader::ProfileMappingRecord > &Records, std::vector< StringRef > &Filenames)
static Expected< std::unique_ptr< BinaryCoverageReader > > loadTestingFormat (StringRef Data)
static Expected< SectionRef > lookupSection (ObjectFile &OF, StringRef Name)
static Expected< std::unique_ptr< BinaryCoverageReader > > loadBinaryFormat (std::unique_ptr< Binary > Bin, StringRef Arch)
Variables
static const unsigned EncodingExpansionRegionBit
static const char * TestingFormatMagic = "llvmcovmtestdata"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coverage-mapping"
Definition at line 41 of file CoverageMappingReader.cpp.
Function Documentation
isCoverageMappingDummy()
static Expected<bool> isCoverageMappingDummy (uint64_t Hash, StringRef Mapping) static
Definition at line 376 of file CoverageMappingReader.cpp.
References llvm::coverage::RawCoverageMappingDummyChecker::isDummy().
loadBinaryFormat()
static Expected<std::unique_ptr<BinaryCoverageReader> > loadBinaryFormat (std::unique_ptr< Binary > Bin, StringRef Arch) static
Definition at line 680 of file CoverageMappingReader.cpp.
References llvm::support::big, llvm::InstrProfSymtab::create(), llvm::coverage::BinaryCoverageReader::createCoverageReaderFromBuffer(), E, llvm::StringRef::empty(), llvm::errorCodeToError(), llvm::Triple::getArch(), llvm::getInstrProfSectionName(), llvm::support::little, lookupSection(), and llvm::coverage::malformed.
loadTestingFormat()
static Expected<std::unique_ptr<BinaryCoverageReader> > loadTestingFormat (StringRef Data) static
Definition at line 623 of file CoverageMappingReader.cpp.
References llvm::Address, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::StringRef::bytes_begin(), llvm::InstrProfSymtab::create(), llvm::coverage::BinaryCoverageReader::createCoverageReaderFromBuffer(), llvm::StringRef::data(), llvm::decodeULEB128(), E, llvm::StringRef::empty(), llvm::support::little, llvm::coverage::malformed, N, llvm::offsetToAlignedAddr(), llvm::StringRef::size(), llvm::size(), llvm::StringRef::substr(), and llvm::coverage::truncated.
Referenced by llvm::coverage::BinaryCoverageReader::create().
lookupSection()
static Expected<SectionRef> lookupSection (ObjectFile & OF, StringRef Name) static
Definition at line 659 of file CoverageMappingReader.cpp.
References N, llvm::coverage::no_data_found, llvm::ARMBuildAttrs::Section, and llvm::Expected< T >::takeError().
Referenced by loadBinaryFormat().
readCoverageMappingData()
template<typename T , support::endianness Endian> static Error readCoverageMappingData (InstrProfSymtab & ProfileNames, StringRef Data, std::vector< BinaryCoverageReader::ProfileMappingRecord > & Records, std::vector< StringRef > & Filenames) static
Definition at line 560 of file CoverageMappingReader.cpp.
References llvm::coverage::CurrentVersion, llvm::StringRef::data(), E, llvm::coverage::unsupported_version, and llvm::IndexedInstrProf::Version.
Variable Documentation
EncodingExpansionRegionBit
const unsigned EncodingExpansionRegionBit static
Initial value:
= 1
                                                   << Counter::EncodingTagBits
Definition at line 147 of file CoverageMappingReader.cpp.
TestingFormatMagic
const char* TestingFormatMagic = "llvmcovmtestdata" static
Definition at line 587 of file CoverageMappingReader.cpp.