LLVM: lib/CodeGen/CriticalAntiDepBreaker.cpp File Reference
CriticalAntiDepBreaker.cpp File Reference
#include "CriticalAntiDepBreaker.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <map>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "post-RA-sched"
Functions
static const SDep * CriticalPathStep (const SUnit *SU)
CriticalPathStep - Return the next SUnit after SU on the bottom-up critical path.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "post-RA-sched"
Definition at line 42 of file CriticalAntiDepBreaker.cpp.
Function Documentation
CriticalPathStep()
static const SDep* CriticalPathStep (const SUnit * SU) static
CriticalPathStep - Return the next SUnit after SU on the bottom-up critical path.
Definition at line 145 of file CriticalAntiDepBreaker.cpp.
References llvm::SDep::Anti, assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::MachineOperand::clobbersPhysReg(), llvm::numbers::e, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SUnit::getDepth(), llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineInstr::getOperand(), llvm::RegisterClassInfo::getOrder(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::TargetInstrInfo::getRegClass(), llvm::MachineInstr::hasExtraSrcRegAllocReq(), I, llvm::MachineInstr::isCall(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isEarlyClobber(), llvm::MachineInstr::isInlineAsm(), llvm::MachineInstr::isKill(), llvm::TargetInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineInstr::isRegTiedToUseOperand(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegAliasIterator::isValid(), MI, P, llvm::SUnit::Preds, Reg, llvm::TargetRegisterInfo::regsOverlap(), llvm::BitVector::reset(), llvm::BitVector::set(), llvm::ArrayRef< T >::size(), and llvm::BitVector::test().