LLVM: lib/DebugInfo/CodeView/CVSymbolVisitor.cpp File Reference
CVSymbolVisitor.cpp File Reference
#include "llvm/DebugInfo/CodeView/CVSymbolVisitor.h"
#include "llvm/DebugInfo/CodeView/CodeViewError.h"
#include "llvm/DebugInfo/CodeView/SymbolVisitorCallbacks.h"
#include "llvm/DebugInfo/CodeView/CodeViewSymbols.def"
Macros
#define SYMBOL_RECORD(EnumName, EnumVal, Name)
#define SYMBOL_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName) SYMBOL_RECORD(EnumVal, EnumVal, AliasName)
Functions
template<typename T >
static Error visitKnownRecord (CVSymbol &Record, SymbolVisitorCallbacks &Callbacks)
static Error finishVisitation (CVSymbol &Record, SymbolVisitorCallbacks &Callbacks)
Macro Definition Documentation
SYMBOL_RECORD
#define SYMBOL_RECORD (EnumName, EnumVal, Name)
Value:
case EnumName: {                                                             \
    if (auto EC = visitKnownRecord<Name>(Record, Callbacks))                   \
      return EC;                                                               \
    break;                                                                     \
  }
SYMBOL_RECORD_ALIAS
#define SYMBOL_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName) SYMBOL_RECORD(EnumVal, EnumVal, AliasName)
Function Documentation
finishVisitation()
static Error finishVisitation (CVSymbol & Record, SymbolVisitorCallbacks & Callbacks) static
Definition at line 30 of file CVSymbolVisitor.cpp.
References llvm::codeview::EC, llvm::codeview::CVRecord< Kind >::kind(), llvm::Error::success(), llvm::codeview::SymbolVisitorCallbacks::visitSymbolEnd(), and llvm::codeview::SymbolVisitorCallbacks::visitUnknownSymbol().
Referenced by visitMemberRecord(), and llvm::codeview::CVSymbolVisitor::visitSymbolRecord().
visitKnownRecord()
template<typename T > static Error visitKnownRecord (CVSymbol & Record, SymbolVisitorCallbacks & Callbacks) static
Definition at line 21 of file CVSymbolVisitor.cpp.
References llvm::codeview::EC, llvm::codeview::CVRecord< Kind >::kind(), and llvm::Error::success().
Referenced by getSymbolKindName(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), llvm::codeview::SymbolRecordMapping::visitSymbolEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().