LLVM: lib/DebugInfo/CodeView/CVTypeVisitor.cpp File Reference
CVTypeVisitor.cpp File Reference
#include "llvm/DebugInfo/CodeView/CVTypeVisitor.h"
#include "llvm/DebugInfo/CodeView/CodeViewError.h"
#include "llvm/DebugInfo/CodeView/TypeCollection.h"
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
#include "llvm/DebugInfo/CodeView/TypeRecordMapping.h"
#include "llvm/DebugInfo/CodeView/TypeVisitorCallbackPipeline.h"
#include "llvm/Support/BinaryByteStream.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/DebugInfo/CodeView/CodeViewTypes.def"
Macros
#define MEMBER_RECORD(EnumName, EnumVal, Name)
#define MEMBER_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName) MEMBER_RECORD(EnumVal, EnumVal, AliasName)
#define TYPE_RECORD(EnumName, EnumVal, Name)
#define TYPE_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName)
#define TYPE_RECORD(EnumName, EnumVal, Name)
#define TYPE_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName) TYPE_RECORD(EnumVal, EnumVal, AliasName)
#define MEMBER_RECORD(EnumName, EnumVal, Name)
#define MEMBER_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName)
Functions
template<typename T >
static Error visitKnownRecord (CVType &Record, TypeVisitorCallbacks &Callbacks)
template<typename T >
static Error visitKnownMember (CVMemberRecord &Record, TypeVisitorCallbacks &Callbacks)
static Error visitMemberRecord (CVMemberRecord &Record, TypeVisitorCallbacks &Callbacks)
Macro Definition Documentation
MEMBER_RECORD [1/2]
#define MEMBER_RECORD (EnumName, EnumVal, Name)
Value:
case EnumName: {                                                             \
    if (auto EC = visitKnownMember<Name##Record>(Record, Callbacks))           \
      return EC;                                                               \
    break;                                                                     \
  }
MEMBER_RECORD [2/2]
#define MEMBER_RECORD (EnumName, EnumVal, Name)
MEMBER_RECORD_ALIAS [1/2]
#define MEMBER_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName) MEMBER_RECORD(EnumVal, EnumVal, AliasName)
MEMBER_RECORD_ALIAS [2/2]
#define MEMBER_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName)
TYPE_RECORD [1/2]
#define TYPE_RECORD (EnumName, EnumVal, Name)
TYPE_RECORD [2/2]
#define TYPE_RECORD (EnumName, EnumVal, Name)
Value:
case EnumName: {                                                             \
    if (auto EC = visitKnownRecord<Name##Record>(Record, Callbacks))           \
      return EC;                                                               \
    break;                                                                     \
  }
TYPE_RECORD_ALIAS [1/2]
#define TYPE_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName)
TYPE_RECORD_ALIAS [2/2]
#define TYPE_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName) TYPE_RECORD(EnumVal, EnumVal, AliasName)
Function Documentation
visitKnownMember()
template<typename T > static Error visitKnownMember (CVMemberRecord & Record, TypeVisitorCallbacks & Callbacks) static
Definition at line 33 of file CVTypeVisitor.cpp.
References llvm::codeview::EC, llvm::codeview::CVMemberRecord::Kind, and llvm::Error::success().
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
visitKnownRecord()
template<typename T > static Error visitKnownRecord (CVType & Record, TypeVisitorCallbacks & Callbacks) static
Definition at line 24 of file CVTypeVisitor.cpp.
References llvm::codeview::EC, llvm::codeview::CVRecord< Kind >::kind(), and llvm::Error::success().
visitMemberRecord()
static Error visitMemberRecord (CVMemberRecord & Record, TypeVisitorCallbacks & Callbacks) static
Definition at line 42 of file CVTypeVisitor.cpp.
References llvm::Data, llvm::codeview::EC, llvm::BinaryStreamReader::empty(), finishVisitation(), llvm::codeview::TypeCollection::getFirst(), llvm::codeview::TypeCollection::getNext(), llvm::codeview::TypeCollection::getType(), I, llvm::codeview::CVMemberRecord::Kind, llvm::codeview::CVRecord< Kind >::kind(), llvm::support::little, llvm::BinaryStreamReader::readEnum(), llvm::Sched::Source, llvm::Error::success(), llvm::codeview::VDS_BytesPresent, llvm::codeview::TypeVisitorCallbacks::visitMemberBegin(), llvm::codeview::TypeVisitorCallbacks::visitMemberEnd(), llvm::codeview::visitMemberRecord(), llvm::codeview::TypeVisitorCallbacks::visitTypeBegin(), llvm::codeview::TypeVisitorCallbacks::visitTypeEnd(), llvm::codeview::visitTypeRecord(), llvm::codeview::visitTypeStream(), llvm::codeview::TypeVisitorCallbacks::visitUnknownMember(), and llvm::codeview::TypeVisitorCallbacks::visitUnknownType().