LLVM: lib/MC/MCParser/DarwinAsmParser.cpp File Reference
DarwinAsmParser.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <string>
#include <system_error>
#include <utility>
Namespaces
llvm
This class represents lattice values for constants.
Functions
static bool isSDKVersionToken (const AsmToken &Tok)
static Triple::OSType getOSTypeFromMCVM (MCVersionMinType Type)
static Triple::OSType getOSTypeFromPlatform (MachO::PlatformType Type)
MCAsmParserExtension * llvm::createDarwinAsmParser ()
Function Documentation
getOSTypeFromMCVM()
static Triple::OSType getOSTypeFromMCVM (MCVersionMinType Type) static
Definition at line 1108 of file DarwinAsmParser.cpp.
References llvm::AsmToken::EndOfStatement, llvm::Triple::IOS, isSDKVersionToken(), llvm_unreachable, llvm::Triple::MacOSX, llvm::MCVM_IOSVersionMin, llvm::MCVM_OSXVersionMin, llvm::MCVM_TvOSVersionMin, llvm::MCVM_WatchOSVersionMin, parseVersion(), llvm::Triple::TvOS, and llvm::Triple::WatchOS.
getOSTypeFromPlatform()
static Triple::OSType getOSTypeFromPlatform (MachO::PlatformType Type) static
Definition at line 1144 of file DarwinAsmParser.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::AsmToken::Comma, llvm::StringSwitch< T, R >::Default(), llvm::AsmToken::EndOfStatement, llvm::Error, llvm::Triple::IOS, isSDKVersionToken(), llvm_unreachable, llvm::Triple::MacOSX, parseVersion(), llvm::MachO::PLATFORM_BRIDGEOS, llvm::MachO::PLATFORM_IOS, llvm::MachO::PLATFORM_IOSSIMULATOR, llvm::MachO::PLATFORM_MACCATALYST, llvm::MachO::PLATFORM_MACOS, llvm::MachO::PLATFORM_TVOS, llvm::MachO::PLATFORM_TVOSSIMULATOR, llvm::MachO::PLATFORM_WATCHOS, llvm::MachO::PLATFORM_WATCHOSSIMULATOR, llvm::Triple::TvOS, and llvm::Triple::WatchOS.
isSDKVersionToken()
static bool isSDKVersionToken (const AsmToken & Tok) static
Definition at line 1007 of file DarwinAsmParser.cpp.
References Arg, assert(), llvm::AsmToken::Comma, llvm::StringRef::empty(), llvm::AsmToken::EndOfStatement, llvm::AsmToken::getIdentifier(), llvm::Triple::getOS(), llvm::Triple::getOSName(), llvm::AsmToken::Identifier, llvm::AsmToken::Integer, llvm::AsmToken::is(), llvm::Note, parseVersion(), and llvm::Warning.
Referenced by getOSTypeFromMCVM(), and getOSTypeFromPlatform().