LLVM: lib/Support/DataExtractor.cpp File Reference
DataExtractor.cpp File Reference
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/SwapByteOrder.h"
Functions
static void unexpectedEndReached (Error *E)
static bool isError (Error *E)
template<typename T >
static T getU (uint64_t *offset_ptr, const DataExtractor *de, bool isLittleEndian, const char *Data, llvm::Error *Err)
template<typename T >
static T * getUs (uint64_t *offset_ptr, T *dst, uint32_t count, const DataExtractor *de, bool isLittleEndian, const char *Data, llvm::Error *Err)
Function Documentation
getU()
template<typename T > static T getU (uint64_t * offset_ptr, const DataExtractor * de, bool isLittleEndian, const char * Data, llvm::Error * Err) static
Definition at line 27 of file DataExtractor.cpp.
Referenced by llvm::ScaledNumbers::multiply64().
getUs()
template<typename T > static T* getUs (uint64_t * offset_ptr, T * dst, uint32_t count, const DataExtractor * de, bool isLittleEndian, const char * Data, llvm::Error * Err) static
Definition at line 49 of file DataExtractor.cpp.
isError()
static bool isError (Error * E) static
Definition at line 24 of file DataExtractor.cpp.
References E.
Referenced by llvm::DataExtractor::skip().
unexpectedEndReached()
static void unexpectedEndReached (Error * E) static
Definition at line 18 of file DataExtractor.cpp.
References llvm::createStringError(), and llvm::illegal_byte_sequence.
Referenced by llvm::DataExtractor::skip().