LLVM: lib/IR/DataLayout.cpp File Reference
DataLayout.cpp File Reference
#include "llvm/IR/DataLayout.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TypeSize.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <tuple>
#include <utility>
Functions
static std::pair< StringRef, StringRef > split (StringRef Str, char Separator)
Checked version of split, to ensure mandatory subparts.
static unsigned getInt (StringRef R)
Get an unsigned integer, including error checks.
static unsigned inBytes (unsigned Bits)
Convert bits into bytes. Assert if not a byte width multiple.
static unsigned getAddrSpace (StringRef R)
Variables
static const LayoutAlignElem DefaultAlignments []
Function Documentation
getAddrSpace()
static unsigned getAddrSpace (StringRef R) static
Definition at line 224 of file DataLayout.cpp.
References llvm::AGGREGATE_ALIGN, llvm::assumeAligned(), llvm::StringRef::empty(), llvm::FLOAT_ALIGN, llvm::StringRef::front(), getInt(), inBytes(), llvm::INTEGER_ALIGN, llvm::isPowerOf2_64(), llvm::isUInt< 16 >(), llvm_unreachable, llvm::report_fatal_error(), Size, llvm::StringRef::size(), split(), llvm::StringRef::substr(), and llvm::VECTOR_ALIGN.
Referenced by llvm::AMDGPUTargetLowering::isSDNodeAlwaysUniform(), llvm::SIInstrInfo::isStackAccess(), and llvm::AMDGPUInstructionSelector::select().
getInt()
static unsigned getInt (StringRef R) static
Get an unsigned integer, including error checks.
Definition at line 209 of file DataLayout.cpp.
References error, llvm::StringRef::getAsInteger(), and llvm::report_fatal_error().
Referenced by getAddrSpace(), llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::getInt(), llvm::UnderlyingObject::mayAlias(), and llvm::HexagonTargetLowering::shouldExpandAtomicRMWInIR().
inBytes()
static unsigned inBytes (unsigned Bits) static
Convert bits into bytes. Assert if not a byte width multiple.
Definition at line 218 of file DataLayout.cpp.
References llvm::report_fatal_error().
Referenced by getAddrSpace().
split()
static std::pair<StringRef, StringRef> split (StringRef Str, char Separator) static
Checked version of split, to ensure mandatory subparts.
Definition at line 198 of file DataLayout.cpp.
References assert(), llvm::StringRef::empty(), llvm::report_fatal_error(), and llvm::StringRef::split().
Referenced by getAddrSpace().
Variable Documentation
DefaultAlignments
const LayoutAlignElem DefaultAlignments[] static
Initial value:
= {
    {INTEGER_ALIGN, 1, Align(1), Align(1)},
    {INTEGER_ALIGN, 8, Align(1), Align(1)},
    {INTEGER_ALIGN, 16, Align(2), Align(2)},
    {INTEGER_ALIGN, 32, Align(4), Align(4)},
    {INTEGER_ALIGN, 64, Align(4), Align(8)},
    {FLOAT_ALIGN, 16, Align(2), Align(2)},
    {FLOAT_ALIGN, 32, Align(4), Align(4)},
    {FLOAT_ALIGN, 64, Align(8), Align(8)},
    {FLOAT_ALIGN, 128, Align(16), Align(16)},
    {VECTOR_ALIGN, 64, Align(8), Align(8)},
    {VECTOR_ALIGN, 128, Align(16), Align(16)},
    {AGGREGATE_ALIGN, 0, Align(1), Align(8)}
}
Definition at line 159 of file DataLayout.cpp.