LLVM: lib/DebugInfo/PDB/Native/DbiStream.cpp File Reference
DbiStream.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/DbiStream.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/DebugInfo/PDB/Native/DbiModuleDescriptor.h"
#include "llvm/DebugInfo/PDB/Native/ISectionContribVisitor.h"
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
#include "llvm/DebugInfo/PDB/Native/RawConstants.h"
#include "llvm/DebugInfo/PDB/Native/RawError.h"
#include "llvm/DebugInfo/PDB/Native/RawTypes.h"
#include "llvm/DebugInfo/PDB/PDBTypes.h"
#include "llvm/Object/COFF.h"
#include "llvm/Support/BinaryStreamArray.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Error.h"
#include <algorithm>
#include <cstddef>
#include <cstdint>
Functions
template<typename ContribType >
static Error loadSectionContribs (FixedStreamArray< ContribType > &Output, BinaryStreamReader &Reader)
Function Documentation
loadSectionContribs()
template<typename ContribType > static Error loadSectionContribs (FixedStreamArray< ContribType > & Output, BinaryStreamReader & Reader) static
Definition at line 34 of file DbiStream.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::EC, llvm::BinaryStreamReader::readArray(), and llvm::Error::success().