LLVM: lib/Transforms/Scalar/DCE.cpp File Reference
DCE.cpp File Reference
#include "llvm/Transforms/Scalar/DCE.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instruction.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/DebugCounter.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "dce"
Functions
STATISTIC (DIEEliminated, "Number of insts removed by DIE pass")
STATISTIC (DCEEliminated, "Number of insts removed")
DEBUG_COUNTER (DCECounter, "dce-transform", "Controls which instructions are eliminated")
INITIALIZE_PASS (DeadInstElimination, "die", "Dead Instruction Elimination", false, false) Pass *llvm
INITIALIZE_PASS (RedundantDbgInstElimination, "redundant-dbg-inst-elim", "Redundant Dbg Instruction Elimination", false, false) Pass *llvm
static bool DCEInstruction (Instruction *I, SmallSetVector< Instruction *, 16 > &WorkList, const TargetLibraryInfo *TLI)
static bool eliminateDeadCode (Function &F, TargetLibraryInfo *TLI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dce"
Definition at line 32 of file DCE.cpp.
Function Documentation
DCEInstruction()
static bool DCEInstruction (Instruction * I, SmallSetVector< Instruction *, 16 > & WorkList, const TargetLibraryInfo * TLI) static
Definition at line 122 of file DCE.cpp.
References llvm::numbers::e, llvm::Instruction::eraseFromParent(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::isInstructionTriviallyDead(), llvm::salvageDebugInfo(), llvm::User::setOperand(), llvm::DebugCounter::shouldExecute(), and llvm::Value::use_empty().
Referenced by eliminateDeadCode().
DEBUG_COUNTER()
DEBUG_COUNTER (DCECounter , "dce-transform" , "Controls which instructions are eliminated")
eliminateDeadCode()
static bool eliminateDeadCode (Function & F, TargetLibraryInfo * TLI) static
Definition at line 155 of file DCE.cpp.
References llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::count(), DCEInstruction(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::empty(), I, llvm::inst_begin(), llvm::inst_end(), and llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::pop_back_val().
Referenced by llvm::DCEPass::run().
INITIALIZE_PASS() [1/2]
INITIALIZE_PASS (DeadInstElimination , "die" , "Dead Instruction Elimination" , false , false)
Definition at line 78 of file DCE.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::initializeRedundantDbgInstEliminationPass(), llvm::RemoveRedundantDbgInstrs(), runOnFunction(), and llvm::AnalysisUsage::setPreservesCFG().
Referenced by llvm::DCEPass::run().
INITIALIZE_PASS() [2/2]
INITIALIZE_PASS (RedundantDbgInstElimination , "redundant-dbg-inst-elim" , "Redundant Dbg Instruction Elimination" , false , false)
Definition at line 111 of file DCE.cpp.
STATISTIC() [1/2]
STATISTIC (DIEEliminated , "Number of insts removed by DIE pass")
STATISTIC() [2/2]
STATISTIC (DCEEliminated , "Number of insts removed")