LLVM: lib/CodeGen/DeadMachineInstructionElim.cpp File Reference
DeadMachineInstructionElim.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "dead-mi-elimination"
Functions
STATISTIC (NumDeletes, "Number of dead instructions deleted")
INITIALIZE_PASS (DeadMachineInstructionElim, DEBUG_TYPE, "Remove dead machine instructions", false, false) bool DeadMachineInstructionElim
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dead-mi-elimination"
Definition at line 25 of file DeadMachineInstructionElim.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (DeadMachineInstructionElim , DEBUG_TYPE , "Remove dead machine instructions" , false , false)
Definition at line 56 of file DeadMachineInstructionElim.cpp.
References assert(), llvm::BitVector::clear(), llvm::BitVector::clearBitsNotInMask(), llvm::dbgs(), llvm::numbers::e, E, llvm::MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineOperand::getRegMask(), llvm::MachineRegisterInfo::getReservedRegs(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineRegisterInfo::isReserved(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegAliasIterator::isValid(), LLVM_DEBUG, llvm::make_range(), MI, llvm::MachineFunction::rbegin(), Reg, llvm::MachineFunction::rend(), llvm::BitVector::reset(), llvm::BitVector::set(), llvm::BitVector::test(), llvm::MachineRegisterInfo::use_nodbg_instructions(), and llvm::MachineRegisterInfo::use_nodbg_operands().
STATISTIC()
STATISTIC (NumDeletes , "Number of dead instructions deleted")