LLVM: lib/Transforms/Utils/Debugify.cpp File Reference
Debugify.cpp File Reference
#include "llvm/Transforms/Utils/Debugify.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
Functions
ModulePass * createDebugifyModulePass ()
FunctionPass * createDebugifyFunctionPass ()
ModulePass * createCheckDebugifyModulePass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap *StatsMap)
FunctionPass * createCheckDebugifyFunctionPass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap *StatsMap)
Variables
static RegisterPass< DebugifyModulePass > DM ("debugify", "Attach debug info to everything")
static RegisterPass< CheckDebugifyModulePass > CDM ("check-debugify", "Check debug info from -debugify")
static RegisterPass< DebugifyFunctionPass > DF ("debugify-function", "Attach debug info to a function")
static RegisterPass< CheckDebugifyFunctionPass > CDF ("check-debugify-function", "Check debug info from -debugify-function")
Function Documentation
createCheckDebugifyFunctionPass()
FunctionPass* createCheckDebugifyFunctionPass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap * StatsMap)
Definition at line 408 of file Debugify.cpp.
createCheckDebugifyModulePass()
ModulePass* createCheckDebugifyModulePass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap * StatsMap)
Definition at line 402 of file Debugify.cpp.
createDebugifyFunctionPass()
FunctionPass* createDebugifyFunctionPass ()
Definition at line 393 of file Debugify.cpp.
createDebugifyModulePass()
ModulePass* createDebugifyModulePass ()
Definition at line 391 of file Debugify.cpp.
Variable Documentation
CDF
RegisterPass<CheckDebugifyFunctionPass> CDF("check-debugify-function", "Check debug info from -debugify-function") static
Referenced by NewPMCheckDebugifyPass::run().
CDM
RegisterPass<CheckDebugifyModulePass> CDM("check-debugify", "Check debug info from -debugify") static
Referenced by NewPMCheckDebugifyPass::run().
DF
RegisterPass<DebugifyFunctionPass> DF("debugify-function", "Attach debug info to a function") static
Referenced by adjustFixupValue(), CheckBundleSubtargets(), llvm::RegionBase< RegionTraits< Function > >::clearNodeCache(), llvm::DILocation::cloneWithBaseDiscriminator(), llvm::MCFragment::dump(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCObjectStreamer::EmitDTPRel32Value(), llvm::MCObjectStreamer::EmitDTPRel64Value(), llvm::MCObjectStreamer::emitFill(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::MCXCOFFStreamer::EmitInstToData(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitLabelAtPos(), llvm::MCObjectStreamer::EmitRelocDirective(), llvm::MCObjectStreamer::EmitTPRel32Value(), llvm::MCObjectStreamer::EmitTPRel64Value(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::DILocation::encodeDiscriminator(), llvm::RISCVAsmBackend::evaluateTargetFixup(), GetAEABIUnwindPersonalityName(), llvm::MCAssembler::getAtom(), llvm::DominanceFrontierWrapperPass::getDominanceFrontier(), getFixupKindNumBytes(), getFixupKindSize(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::RISCVMCExpr::getPCRelHiFixup(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::ARMAsmBackend::hasNOP(), llvm::MCELFStreamer::MCELFStreamer(), llvm::RegionInfo::operator=(), llvm::MachineRegionInfo::recalculate(), llvm::RegionInfo::recalculate(), llvm::RISCVAsmBackend::requiresDiffExpressionRelocations(), llvm::MCAsmBackend::requiresDiffExpressionRelocations(), NewPMCheckDebugifyPass::run(), llvm::RegionInfoAnalysis::run(), llvm::RegionInfoPass::runOnFunction(), and llvm::MachineRegionInfoPass::runOnMachineFunction().
DM
RegisterPass<DebugifyModulePass> DM("debugify", "Attach debug info to everything") static
Referenced by llvm::PMDataManager::add(), llvm::rdf::DataFlowGraph::build(), llvm::pdb::UDTLayoutBase::initializeChildren(), llvm::rdf::DataFlowGraph::IsPreservingDef(), mayUseP9Setb(), NewPMCheckDebugifyPass::run(), and llvm::PMTopLevelManager::schedulePass().