LLVM: lib/DebugInfo/PDB/DIA/DIASectionContrib.cpp File Reference
DIASectionContrib.cpp File Reference
#include "llvm/DebugInfo/PDB/DIA/DIASectionContrib.h"
#include "llvm/DebugInfo/PDB/DIA/DIARawSymbol.h"
#include "llvm/DebugInfo/PDB/DIA/DIASession.h"
#include "llvm/DebugInfo/PDB/PDBSymbolCompiland.h"
Functions
template<typename ArgType >
ArgType PrivateGetDIAValue (IDiaSectionContrib *Section, HRESULT(__stdcall IDiaSectionContrib::*Method)(ArgType *))
Function Documentation
PrivateGetDIAValue()
template<typename ArgType > ArgType PrivateGetDIAValue (IDiaSectionContrib * Section, HRESULT(__stdcall IDiaSectionContrib::*)(ArgType *) Method)
Definition at line 32 of file DIASectionContrib.cpp.
Referenced by llvm::pdb::DIASectionContrib::getAddressOffset(), llvm::pdb::DIASectionContrib::getAddressSection(), llvm::pdb::DIASectionContrib::getCompilandId(), llvm::pdb::DIASectionContrib::getDataCrc32(), llvm::pdb::DIASectionContrib::getLength(), llvm::pdb::DIASectionContrib::getRelativeVirtualAddress(), llvm::pdb::DIASectionContrib::getRelocationsCrc32(), llvm::pdb::DIASectionContrib::getVirtualAddress(), llvm::pdb::DIASectionContrib::hasCode(), llvm::pdb::DIASectionContrib::hasCode16Bit(), llvm::pdb::DIASectionContrib::hasComdat(), llvm::pdb::DIASectionContrib::hasInitializedData(), llvm::pdb::DIASectionContrib::hasUninitializedData(), llvm::pdb::DIASectionContrib::isDiscardable(), llvm::pdb::DIASectionContrib::isExecutable(), llvm::pdb::DIASectionContrib::isNotCached(), llvm::pdb::DIASectionContrib::isNotPaged(), llvm::pdb::DIASectionContrib::isReadable(), llvm::pdb::DIASectionContrib::isRemoved(), llvm::pdb::DIASectionContrib::isShared(), and llvm::pdb::DIASectionContrib::isWritable().