LLVM: lib/IR/DIBuilder.cpp File Reference
DIBuilder.cpp File Reference
#include "llvm/IR/DIBuilder.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Functions
static DIScope * getNonCompileUnitScope (DIScope *N)
If N is compile unit return NULL otherwise return N.
static DIImportedEntity * createImportedModule (LLVMContext &C, dwarf::Tag Tag, DIScope *Context, Metadata *NS, DIFile *File, unsigned Line, StringRef Name, SmallVectorImpl< TrackingMDNodeRef > &AllImportedModules)
static ConstantAsMetadata * getConstantOrNull (Constant *C)
static DITemplateValueParameter * createTemplateValueParameterHelper (LLVMContext &VMContext, unsigned Tag, DIScope *Context, StringRef Name, DIType *Ty, Metadata *MD)
static DIType * createTypeWithFlags (const DIType *Ty, DINode::DIFlags FlagsToSet)
static void checkGlobalVariableScope (DIScope *Context)
static DILocalVariable * createLocalVariable (LLVMContext &VMContext, DenseMap< MDNode *, SmallVector< TrackingMDNodeRef, 1 >> &PreservedVariables, DIScope *Scope, StringRef Name, unsigned ArgNo, DIFile *File, unsigned LineNo, DIType *Ty, bool AlwaysPreserve, DINode::DIFlags Flags, uint32_t AlignInBits)
template<class... Ts>
static DISubprogram * getSubprogram (bool IsDistinct, Ts &&... Args)
static IRBuilder getIRBForDbgInsertion (const DILocation *DL, BasicBlock *InsertBB, Instruction *InsertBefore)
Return an IRBuilder for inserting dbg.declare and dbg.value intrinsics.
static Value * getDbgIntrinsicValueImpl (LLVMContext &VMContext, Value *V)
static Function * getDeclareIntrin (Module &M)
Variables
static cl::opt< bool > UseDbgAddr ("use-dbg-addr", llvm::cl::desc("Use llvm.dbg.addr for all local variables"), cl::init(false), cl::Hidden)
Function Documentation
checkGlobalVariableScope()
static void checkGlobalVariableScope (DIScope * Context) static
Definition at line 632 of file DIBuilder.cpp.
References assert(), and getNonCompileUnitScope().
Referenced by llvm::DIBuilder::createGlobalVariableExpression(), and llvm::DIBuilder::createTempGlobalVariableFwdDecl().
createImportedModule()
static DIImportedEntity* createImportedModule (LLVMContext & C, dwarf::Tag Tag, DIScope * Context, Metadata * NS, DIFile * File, unsigned Line, StringRef Name, SmallVectorImpl< TrackingMDNodeRef > & AllImportedModules) static
Definition at line 164 of file DIBuilder.cpp.
References assert(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MDNode::get(), and llvm::LLVMContext::pImpl.
Referenced by llvm::DIBuilder::createImportedDeclaration(), llvm::DIBuilder::createImportedModule(), LLVMDIBuilderCreateImportedModuleFromAlias(), LLVMDIBuilderCreateImportedModuleFromModule(), and LLVMDIBuilderCreateImportedModuleFromNamespace().
createLocalVariable()
static DILocalVariable* createLocalVariable (LLVMContext & VMContext, DenseMap< MDNode *, SmallVector< TrackingMDNodeRef, 1 >> & PreservedVariables, DIScope * Scope, StringRef Name, unsigned ArgNo, DIFile * File, unsigned LineNo, DIType * Ty, bool AlwaysPreserve, DINode::DIFlags Flags, uint32_t AlignInBits) static
Definition at line 672 of file DIBuilder.cpp.
References Context, and getNonCompileUnitScope().
Referenced by llvm::DIBuilder::createAutoVariable(), and llvm::DIBuilder::createParameterVariable().
createTemplateValueParameterHelper()
static DITemplateValueParameter* createTemplateValueParameterHelper (LLVMContext & VMContext, unsigned Tag, DIScope * Context, StringRef Name, DIType * Ty, Metadata * MD) static
Definition at line 414 of file DIBuilder.cpp.
References assert(), and llvm::MDNode::get().
Referenced by llvm::DIBuilder::createTemplateParameterPack(), llvm::DIBuilder::createTemplateTemplateParameter(), and llvm::DIBuilder::createTemplateValueParameter().
createTypeWithFlags()
static DIType* createTypeWithFlags (const DIType * Ty, DINode::DIFlags FlagsToSet) static
Definition at line 544 of file DIBuilder.cpp.
References llvm::DIType::cloneWithFlags(), llvm::DIType::getFlags(), and llvm::MDNode::replaceWithUniqued().
Referenced by llvm::DIBuilder::createArtificialType(), and llvm::DIBuilder::createObjectPointerType().
getConstantOrNull()
static ConstantAsMetadata* getConstantOrNull (Constant * C) static
Definition at line 346 of file DIBuilder.cpp.
References llvm::ConstantAsMetadata::get().
Referenced by llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createTemplateValueParameter(), and llvm::DIBuilder::createVariantMemberType().
getDbgIntrinsicValueImpl()
static Value* getDbgIntrinsicValueImpl (LLVMContext & VMContext, Value * V) static
Definition at line 912 of file DIBuilder.cpp.
References assert(), llvm::MetadataAsValue::get(), and llvm::ValueAsMetadata::get().
Referenced by getDeclareIntrin().
getDeclareIntrin()
static Function* getDeclareIntrin (Module & M) static
Definition at line 917 of file DIBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), B, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::MetadataAsValue::get(), getDbgIntrinsicValueImpl(), llvm::Intrinsic::getDeclaration(), getIRBForDbgInsertion(), llvm::DILocalVariable::getScope(), llvm::DILabel::getScope(), llvm::DILocalScope::getSubprogram(), and UseDbgAddr.
getIRBForDbgInsertion()
static IRBuilder getIRBForDbgInsertion (const DILocation * DL, BasicBlock * InsertBB, Instruction * InsertBefore) static
Return an IRBuilder for inserting dbg.declare and dbg.value intrinsics.
This abstracts over the various ways to specify an insert position.
Definition at line 900 of file DIBuilder.cpp.
References B, and llvm::MDNode::getContext().
Referenced by getDeclareIntrin().
getNonCompileUnitScope()
static DIScope* getNonCompileUnitScope (DIScope * N) static
If N is compile unit return NULL otherwise return N.
Definition at line 132 of file DIBuilder.cpp.
References N.
Referenced by checkGlobalVariableScope(), llvm::DIBuilder::createBitFieldMemberType(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createLabel(), llvm::DIBuilder::createLexicalBlock(), createLocalVariable(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createReplaceableCompositeType(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createVariantMemberType(), and llvm::DIBuilder::createVariantPart().
getSubprogram()
template<class... Ts> static DISubprogram* getSubprogram (bool IsDistinct, Ts &&... Args) static
Definition at line 748 of file DIBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::MDNode::get(), and llvm::MDNode::getDistinct().
Referenced by llvm::Function::classof(), llvm::DIBuilder::createMethod(), llvm::DILocalScope::DILocalScope(), llvm::Function::isDebugInfoForProfiling(), and LLVMGetSubprogram().
Variable Documentation
UseDbgAddr
cl::opt<bool> UseDbgAddr("use-dbg-addr", llvm::cl::desc("Use llvm.dbg.addr for all local variables"), cl::init(false), cl::Hidden) static
Referenced by getDeclareIntrin().