LLVM: lib/CodeGen/AsmPrinter/DIE.cpp File Reference
DIE.cpp File Reference
#include "llvm/CodeGen/DIE.h"
#include "DwarfCompileUnit.h"
#include "DwarfDebug.h"
#include "DwarfUnit.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/CodeGen/DIEValue.def"
Macros
#define DEBUG_TYPE "dwarfdebug"
#define HANDLE_DIEVALUE(T)
#define HANDLE_DIEVALUE(T)
#define HANDLE_DIEVALUE(T)
Functions
static LLVM_DUMP_METHOD void printValues (raw_ostream &O, const DIEValueList &Values, StringRef Type, unsigned Size, unsigned IndentCount)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dwarfdebug"
Definition at line 34 of file DIE.cpp.
HANDLE_DIEVALUE [1/3]
#define HANDLE_DIEVALUE (T)
Value:
case is##T:                                                                  \
    getDIE##T().EmitValue(AP, Form);                                           \
    break;
HANDLE_DIEVALUE [2/3]
#define HANDLE_DIEVALUE (T)
Value:
case is##T:                                                                  \
    return getDIE##T().SizeOf(AP, Form);
HANDLE_DIEVALUE [3/3]
#define HANDLE_DIEVALUE (T)
Value:
case is##T:                                                                  \
    getDIE##T().print(O);                                                      \
    break;
Function Documentation
printValues()
static LLVM_DUMP_METHOD void printValues (raw_ostream & O, const DIEValueList & Values, StringRef Type, unsigned Size, unsigned IndentCount) static
Definition at line 231 of file DIE.cpp.
References llvm::dwarf::FormEncodingString(), I, LLVM_DUMP_METHOD, and llvm::DIEValueList::values().
Referenced by llvm::DIELoc::print(), and llvm::DIEBlock::print().