LLVM: lib/CodeGen/AsmPrinter/DIEHash.cpp File Reference
DIEHash.cpp File Reference
#include "DIEHash.h"
#include "ByteStreamer.h"
#include "DwarfDebug.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/DIE.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/raw_ostream.h"
#include "DIEHashAttributes.def"
Macros
#define DEBUG_TYPE "dwarfdebug"
#define HANDLE_DIE_HASH_ATTR(NAME)
#define HANDLE_DIE_HASH_ATTR(NAME)
Functions
static StringRef getDIEStringAttr (const DIE &Die, uint16_t Attr)
Grabs the string in whichever attribute is passed in and returns a reference to it.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dwarfdebug"
Definition at line 28 of file DIEHash.cpp.
HANDLE_DIE_HASH_ATTR [1/2]
#define HANDLE_DIE_HASH_ATTR (NAME)
Value:
case dwarf::NAME:                                                            \
    Attrs.NAME = V;                                                            \
    break;
HANDLE_DIE_HASH_ATTR [2/2]
#define HANDLE_DIE_HASH_ATTR (NAME)
Value:
{                                                                            \
    if (Attrs.NAME)                                                           \
      hashAttribute(Attrs.NAME, Tag);                                         \
  }
Function Documentation
getDIEStringAttr()
static StringRef getDIEStringAttr (const DIE & Die, uint16_t Attr) static
Grabs the string in whichever attribute is passed in and returns a reference to it.
Definition at line 32 of file DIEHash.cpp.
References llvm::dbgs(), LLVM_DEBUG, llvm::makeArrayRef(), llvm::MD5::update(), and llvm::DIEValueList::values().
Referenced by llvm::DIEHash::addSLEB128().