LLVM: lib/ObjectYAML/DWARFVisitor.cpp File Reference
DWARFVisitor.cpp File Reference
#include "DWARFVisitor.h"
#include "llvm/ObjectYAML/DWARFYAML.h"
Functions
static unsigned getOffsetSize (const DWARFYAML::Unit &Unit)
static unsigned getRefSize (const DWARFYAML::Unit &Unit)
Function Documentation
getOffsetSize()
static unsigned getOffsetSize (const DWARFYAML::Unit & Unit) static
Definition at line 36 of file DWARFVisitor.cpp.
References llvm::DWARFYAML::InitialLength::isDWARF64(), and llvm::DWARFYAML::Unit::Length.
Referenced by getRefSize(), and llvm::DWARFYAML::VisitorImpl< const Data >::traverseDebugInfo().
getRefSize()
static unsigned getRefSize (const DWARFYAML::Unit & Unit) static
Definition at line 40 of file DWARFVisitor.cpp.
References llvm::DWARFYAML::Unit::AddrSize, getOffsetSize(), and llvm::DWARFYAML::Unit::Version.
Referenced by llvm::DWARFYAML::VisitorImpl< const Data >::traverseDebugInfo().