LLVM: lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp File Reference
DWARFAcceleratorTable.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFRelocMap.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DJB.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/Support/raw_ostream.h"
#include <cstddef>
#include <cstdint>
#include <utility>
Functions
static Atom formatAtom (unsigned Atom)
static constexpr DWARFDebugNames::AttributeEncoding sentinelAttrEnc ()
static bool isSentinel (const DWARFDebugNames::AttributeEncoding &AE)
static DWARFDebugNames::Abbrev sentinelAbbrev ()
static bool isSentinel (const DWARFDebugNames::Abbrev &Abbr)
Function Documentation
formatAtom()
static Atom formatAtom (unsigned Atom) static
Definition at line 40 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFAcceleratorTable::~DWARFAcceleratorTable().
Referenced by llvm::AppleAcceleratorTable::dump().
isSentinel() [1/2]
static bool isSentinel (const DWARFDebugNames::AttributeEncoding & AE) static
Examples:
/work/llvm-www-releases/10.0.0/docs_build/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 419 of file DWARFAcceleratorTable.cpp.
References sentinelAttrEnc().
Referenced by llvm::DWARFDebugNames::NameIndex::extract(), isEqualImpl(), llvm::ilist_node_base< true >::isKnownSentinel(), llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >::isSentinel(), and isSentinel().
isSentinel() [2/2]
static bool isSentinel (const DWARFDebugNames::Abbrev & Abbr) static
Definition at line 427 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFDebugNames::Abbrev::Code, llvm::createStringError(), llvm::illegal_byte_sequence, isSentinel(), llvm::ARMBuildAttrs::Section, sentinelAbbrev(), and llvm::Tag.
sentinelAbbrev()
static DWARFDebugNames::Abbrev sentinelAbbrev () static
Definition at line 423 of file DWARFAcceleratorTable.cpp.
Referenced by isSentinel().
sentinelAttrEnc()
static constexpr DWARFDebugNames::AttributeEncoding sentinelAttrEnc () static
Definition at line 415 of file DWARFAcceleratorTable.cpp.
Referenced by isSentinel().