LLVM: lib/DebugInfo/DWARF/DWARFDie.cpp File Reference
DWARFDie.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugRangeList.h"
#include "llvm/DebugInfo/DWARF/DWARFExpression.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <string>
#include <utility>
Functions
static void dumpApplePropertyAttribute (raw_ostream &OS, uint64_t Val)
static void dumpRanges (const DWARFObject &Obj, raw_ostream &OS, const DWARFAddressRangesVector &Ranges, unsigned AddressSize, unsigned Indent, const DIDumpOptions &DumpOpts)
static void dumpLocation (raw_ostream &OS, DWARFFormValue &FormValue, DWARFUnit *U, unsigned Indent, DIDumpOptions DumpOpts)
static void dumpTypeTagName (raw_ostream &OS, dwarf::Tag T)
Dump the name encoded in the type tag.
static void dumpArrayType (raw_ostream &OS, const DWARFDie &D)
static void dumpTypeName (raw_ostream &OS, const DWARFDie &D)
Recursively dump the DIE type name when applicable.
static void dumpAttribute (raw_ostream &OS, const DWARFDie &Die, uint64_t *OffsetPtr, dwarf::Attribute Attr, dwarf::Form Form, unsigned Indent, DIDumpOptions DumpOpts)
static unsigned dumpParentChain (DWARFDie Die, raw_ostream &OS, unsigned Indent, DIDumpOptions DumpOpts, unsigned Depth=0)
Helper to dump a DIE with all of its parents, but no siblings.
Function Documentation
dumpApplePropertyAttribute()
static void dumpApplePropertyAttribute (raw_ostream & OS, uint64_t Val) static
Definition at line 40 of file DWARFDie.cpp.
References llvm::dwarf::ApplePropertyString(), assert(), llvm::tgtok::Bit, llvm::countTrailingZeros(), and llvm::format().
Referenced by dumpAttribute().
dumpArrayType()
static void dumpArrayType (raw_ostream & OS, const DWARFDie & D) static
Definition at line 115 of file DWARFDie.cpp.
References C, llvm::DWARFDie::children(), llvm::DWARFDie::find(), llvm::DWARFDie::getDwarfUnit(), llvm::DWARFUnit::getUnitDIE(), llvm::dwarf::LanguageLowerBound(), and llvm::None.
Referenced by dumpTypeName().
dumpAttribute()
static void dumpAttribute (raw_ostream & OS, const DWARFDie & Die, uint64_t * OffsetPtr, dwarf::Attribute Attr, dwarf::Form Form, unsigned Indent, DIDumpOptions DumpOpts) static
Definition at line 233 of file DWARFDie.cpp.
References llvm::DILineInfoSpecifier::AbsoluteFilePath, llvm::Attribute, llvm::dwarf::AttributeValueString(), llvm::DWARFFormValue::createFromUnit(), llvm::DWARFFormValue::createFromUValue(), llvm::DWARFFormValue::dump(), dumpApplePropertyAttribute(), dumpLocation(), dumpRanges(), dumpTypeName(), llvm::StringRef::empty(), llvm::Enumerator, llvm::WithColor::error(), File, llvm::format(), llvm::formatv(), llvm::DWARFUnit::getAddressByteSize(), llvm::DWARFDie::getAddressRanges(), llvm::DWARFFormValue::getAsSectionOffset(), llvm::DWARFFormValue::getAsUnsignedConstant(), llvm::DWARFDie::getAttributeValueAsReferencedDie(), llvm::DWARFUnit::getCompilationDir(), llvm::DWARFUnit::getContext(), llvm::DWARFContext::getDWARFObj(), llvm::DWARFDie::getDwarfUnit(), llvm::DWARFFormValue::getForm(), llvm::DWARFContext::getLineTableForUnit(), llvm::DWARFDie::getLowAndHighPC(), llvm::DWARFDie::getName(), llvm::DWARFUnit::getRnglistOffset(), llvm::Optional< T >::getValue(), llvm::raw_ostream::indent(), llvm::DWARFDie::isValid(), llvm::LinkageName, llvm::AArch64CC::LT, llvm::DWARFAttribute::mayHaveLocationDescription(), Name, llvm::DIDumpOptions::ShowAddresses, llvm::DIDumpOptions::ShowForm, llvm::String, llvm::dwarf::toString(), and llvm::DIDumpOptions::Verbose.
Referenced by llvm::DWARFDie::dump().
dumpLocation()
static void dumpLocation (raw_ostream & OS, DWARFFormValue & FormValue, DWARFUnit * U, unsigned Indent, DIDumpOptions DumpOpts) static
Definition at line 72 of file DWARFDie.cpp.
References llvm::Data, llvm::ArrayRef< T >::data(), llvm::DWARFFormValue::dump(), llvm::DWARFLocationTable::dumpLocationList(), llvm::DWARFFormValue::FC_Block, llvm::DWARFFormValue::FC_Exprloc, llvm::DWARFFormValue::FC_SectionOffset, llvm::DWARFUnit::getAddressByteSize(), llvm::DWARFFormValue::getAsBlock(), llvm::DWARFFormValue::getAsSectionOffset(), llvm::DWARFUnit::getBaseAddress(), llvm::DWARFUnit::getContext(), llvm::DWARFContext::getDWARFObj(), llvm::DWARFFormValue::getForm(), llvm::DWARFUnit::getLocationTable(), llvm::DWARFUnit::getLoclistOffset(), llvm::DWARFContext::getRegisterInfo(), llvm::DWARFUnit::getVersion(), llvm::DWARFFormValue::isFormClass(), llvm::DWARFContext::isLittleEndian(), MRI, print(), and llvm::ArrayRef< T >::size().
Referenced by dumpAttribute().
dumpParentChain()
static unsigned dumpParentChain (DWARFDie Die, raw_ostream & OS, unsigned Indent, DIDumpOptions DumpOpts, unsigned Depth = 0) static
Helper to dump a DIE with all of its parents, but no siblings.
Definition at line 558 of file DWARFDie.cpp.
References llvm::Depth, llvm::DWARFDie::dump(), llvm::DWARFDie::getParent(), and llvm::DIDumpOptions::ParentRecurseDepth.
Referenced by llvm::DWARFDie::dump().
dumpRanges()
static void dumpRanges (const DWARFObject & Obj, raw_ostream & OS, const DWARFAddressRangesVector & Ranges, unsigned AddressSize, unsigned Indent, const DIDumpOptions & DumpOpts) static
Definition at line 58 of file DWARFDie.cpp.
References llvm::raw_ostream::indent(), and llvm::DIDumpOptions::ShowAddresses.
Referenced by dumpAttribute().
dumpTypeName()
static void dumpTypeName (raw_ostream & OS, const DWARFDie & D) static
Recursively dump the DIE type name when applicable.
Definition at line 162 of file DWARFDie.cpp.
References C, llvm::DWARFDie::children(), dumpArrayType(), dumpTypeTagName(), llvm::DWARFDie::getAttributeValueAsReferencedDie(), llvm::DWARFDie::getName(), llvm::DWARFDie::getTag(), llvm::DWARFDie::isValid(), llvm::LinkageName, and Name.
Referenced by dumpAttribute().
dumpTypeTagName()
static void dumpTypeTagName (raw_ostream & OS, dwarf::Tag T) static
Dump the name encoded in the type tag.
Definition at line 108 of file DWARFDie.cpp.
References llvm::StringRef::endswith(), llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::StringRef::substr(), and llvm::dwarf::TagString().
Referenced by dumpTypeName().