LLVM: lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp File Reference
DwarfCompileUnit.cpp File Reference
#include "DwarfCompileUnit.h"
#include "AddressPool.h"
#include "DwarfDebug.h"
#include "DwarfExpression.h"
#include "DwarfUnit.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/DIE.h"
#include "llvm/CodeGen/LexicalScopes.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/Casting.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iterator>
#include <memory>
#include <string>
#include <utility>
Functions
static dwarf::Tag GetCompileUnitType (UnitKind Kind, DwarfDebug *DW)
static SmallVector< const DIVariable *, 2 > dependencies (DbgVariable *Var)
Return all DIVariables that appear in count: expressions.
static SmallVector< DbgVariable *, 8 > sortLocalVars (SmallVectorImpl< DbgVariable *> &Input)
Sort local variables so that variables appearing inside of helper expressions come first.
static bool useGNUAnalogForDwarf5Feature (DwarfDebug *DD)
Whether to use the GNU analog for a DWARF5 tag, attribute, or location atom.
Function Documentation
dependencies()
static SmallVector<const DIVariable *, 2> dependencies (DbgVariable * Var) static
Return all DIVariables that appear in count: expressions.
Definition at line 717 of file DwarfCompileUnit.cpp.
References llvm::dyn_cast(), llvm::DbgVariable::getType(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by sortLocalVars().
GetCompileUnitType()
static dwarf::Tag GetCompileUnitType (UnitKind Kind, DwarfDebug * DW) static
Definition at line 55 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::getDwarfVersion(), and llvm::Skeleton.
sortLocalVars()
static SmallVector<DbgVariable *, 8> sortLocalVars (SmallVectorImpl< DbgVariable *> & Input) static
Sort local variables so that variables appearing inside of helper expressions come first.
Definition at line 735 of file DwarfCompileUnit.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, InlineBuckets, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), dependencies(), llvm::SmallVectorBase::empty(), llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, InlineBuckets, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::reverse().
Referenced by llvm::DwarfCompileUnit::createScopeChildrenDIE().
useGNUAnalogForDwarf5Feature()
static bool useGNUAnalogForDwarf5Feature (DwarfDebug * DD) static
Whether to use the GNU analog for a DWARF5 tag, attribute, or location atom.
Definition at line 908 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::getDwarfVersion(), and llvm::DwarfDebug::tuneForGDB().
Referenced by llvm::DwarfCompileUnit::getDwarf5OrGNUAttr(), llvm::DwarfCompileUnit::getDwarf5OrGNULocationAtom(), and llvm::DwarfCompileUnit::getDwarf5OrGNUTag().