LLVM: lib/DebugInfo/DWARF/DWARFVerifier.cpp File Reference
DWARFVerifier.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFVerifier.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/DebugInfo/DWARF/DWARFCompileUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/DebugInfo/DWARF/DWARFExpression.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFSection.h"
#include "llvm/Support/DJB.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include <map>
#include <set>
#include <vector>
Functions
static SmallVector< StringRef, 2 > getNames (const DWARFDie &DIE, bool IncludeLinkageName=true)
static bool isVariableIndexable (const DWARFDie &Die, DWARFContext &DCtx)
Function Documentation
getNames()
static SmallVector<StringRef, 2> getNames (const DWARFDie & DIE, bool IncludeLinkageName = true) static
Definition at line 1180 of file DWARFVerifier.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), error, llvm::formatv(), llvm::DWARFDebugNames::NameIndex::getCUCount(), llvm::DWARFDebugNames::NameIndex::getCUOffset(), llvm::DWARFDie::getDwarfUnit(), llvm::DWARFDebugNames::NameIndex::getEntry(), llvm::DWARFDebugNames::NameTableEntry::getEntryOffset(), llvm::DWARFDebugNames::NameIndex::getForeignTUCount(), llvm::DWARFDebugNames::NameTableEntry::getIndex(), llvm::DWARFDebugNames::NameIndex::getLocalTUCount(), llvm::DWARFDie::getName(), llvm::DWARFUnit::getOffset(), llvm::DWARFDebugNames::NameTableEntry::getString(), llvm::DWARFDie::getTag(), llvm::DWARFDebugNames::NameIndex::getUnitOffset(), llvm::handleAllErrors(), Info, llvm::is_contained(), llvm::LinkageName, llvm::make_range(), and llvm::ShortName.
Referenced by isVariableIndexable().
isVariableIndexable()
static bool isVariableIndexable (const DWARFDie & Die, DWARFContext & DCtx) static
Definition at line 1282 of file DWARFVerifier.cpp.
References llvm::any_of(), llvm::consumeError(), llvm::Data, E, llvm::DWARFDebugNames::NameIndex::equal_range(), error, llvm::DWARFDie::find(), llvm::DWARFDie::findRecursively(), llvm::formatv(), llvm::DWARFUnit::getAddressByteSize(), llvm::DWARFExpression::Operation::getCode(), llvm::DWARFDie::getDwarfUnit(), llvm::DWARFDie::getLocations(), getNames(), llvm::DWARFDie::getOffset(), llvm::DWARFUnit::getOffset(), llvm::DWARFDie::getTag(), llvm::DWARFDebugNames::NameIndex::getUnitOffset(), llvm::DWARFUnit::getVersion(), llvm::DWARFExpression::Operation::isError(), llvm::DWARFContext::isLittleEndian(), Name, llvm::none_of(), llvm::Expected< T >::takeError(), llvm::toString(), and llvm::toStringRef().