LLVM: lib/ObjectYAML/DWARFEmitter.cpp File Reference
DWARFEmitter.cpp File Reference
The DWARF component of yaml2obj.
#include "llvm/ObjectYAML/DWARFEmitter.h"
#include "DWARFVisitor.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ObjectYAML/DWARFYAML.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SwapByteOrder.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
Typedefs
using EmitFuncType = void(*)(raw_ostream &, const DWARFYAML::Data &)
Functions
template<typename T >
static void writeInteger (T Integer, raw_ostream &OS, bool IsLittleEndian)
static void writeVariableSizedInteger (uint64_t Integer, size_t Size, raw_ostream &OS, bool IsLittleEndian)
static void ZeroFillBytes (raw_ostream &OS, size_t Size)
static void writeInitialLength (const DWARFYAML::InitialLength &Length, raw_ostream &OS, bool IsLittleEndian)
static void EmitFileEntry (raw_ostream &OS, const DWARFYAML::File &File)
static void EmitDebugSectionImpl (const DWARFYAML::Data &DI, EmitFuncType EmitFunc, StringRef Sec, StringMap< std::unique_ptr< MemoryBuffer >> &OutputBuffers)
Detailed Description
The DWARF component of yaml2obj.
Provided as library code for tests.
Definition in file DWARFEmitter.cpp.
Typedef Documentation
EmitFuncType
using EmitFuncType = void (*)(raw_ostream &, const DWARFYAML::Data &)
Definition at line 295 of file DWARFEmitter.cpp.
Function Documentation
EmitDebugSectionImpl()
static void EmitDebugSectionImpl (const DWARFYAML::Data & DI, EmitFuncType EmitFunc, StringRef Sec, StringMap< std::unique_ptr< MemoryBuffer >> & OutputBuffers) static
Definition at line 298 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::Entry::AbbrCode, llvm::Data, llvm::raw_ostream::flush(), llvm::MemoryBufferRef::getBufferSize(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::getSLEB128Size(), llvm::getULEB128Size(), llvm::DWARFYAML::Unit::Length, llvm::DWARFYAML::InitialLength::setLength(), llvm::StringRef::size(), llvm::String, and llvm::DWARFYAML::Unit::Version.
Referenced by llvm::DWARFYAML::EmitDebugSections().
EmitFileEntry()
static void EmitFileEntry (raw_ostream & OS, const DWARFYAML::File & File) static
Definition at line 204 of file DWARFEmitter.cpp.
References llvm::StringRef::data(), llvm::DWARFYAML::File::DirIdx, llvm::encodeULEB128(), llvm::DWARFYAML::File::Length, llvm::DWARFYAML::File::ModTime, llvm::DWARFYAML::File::Name, llvm::StringRef::size(), and llvm::raw_ostream::write().
Referenced by llvm::DWARFYAML::EmitDebugLine().
writeInitialLength()
static void writeInitialLength (const DWARFYAML::InitialLength & Length, raw_ostream & OS, bool IsLittleEndian) static
Definition at line 64 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::InitialLength::isDWARF64(), llvm::DWARFYAML::InitialLength::TotalLength, llvm::DWARFYAML::InitialLength::TotalLength64, and writeInteger().
Referenced by llvm::DWARFYAML::EmitDebugAranges(), llvm::DWARFYAML::EmitDebugLine(), and llvm::DWARFYAML::EmitPubSection().
writeInteger()
template<typename T > static void writeInteger (T Integer, raw_ostream & OS, bool IsLittleEndian) static
Definition at line 38 of file DWARFEmitter.cpp.
References llvm::sys::IsLittleEndianHost, llvm::sys::swapByteOrder(), and llvm::raw_ostream::write().
Referenced by llvm::DWARFYAML::EmitDebugAranges(), llvm::DWARFYAML::EmitDebugLine(), llvm::DWARFYAML::EmitPubSection(), writeInitialLength(), and writeVariableSizedInteger().
writeVariableSizedInteger()
static void writeVariableSizedInteger (uint64_t Integer, size_t Size, raw_ostream & OS, bool IsLittleEndian) static
Definition at line 44 of file DWARFEmitter.cpp.
References assert(), and writeInteger().
Referenced by llvm::DWARFYAML::EmitDebugAranges(), and llvm::DWARFYAML::EmitDebugLine().
ZeroFillBytes()
static void ZeroFillBytes (raw_ostream & OS, size_t Size) static
Definition at line 58 of file DWARFEmitter.cpp.
References Size, and llvm::raw_ostream::write().
Referenced by llvm::DWARFYAML::EmitDebugAranges().