LLVM: lib/DebugInfo/DWARF/DWARFUnit.cpp File Reference
DWARFUnit.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h"
#include "llvm/DebugInfo/DWARF/DWARFCompileUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugRnglists.h"
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFTypeUnit.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/WithColor.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <utility>
#include <vector>
Functions
template<typename ListTableType >
static Expected< ListTableType > parseListTableHeader (DWARFDataExtractor &DA, uint64_t Offset, DwarfFormat Format)
static Expected< StrOffsetsContributionDescriptor > parseDWARF64StringOffsetsTableHeader (DWARFDataExtractor &DA, uint64_t Offset)
static Expected< StrOffsetsContributionDescriptor > parseDWARF32StringOffsetsTableHeader (DWARFDataExtractor &DA, uint64_t Offset)
static Expected< StrOffsetsContributionDescriptor > parseDWARFStringOffsetsTableHeader (DWARFDataExtractor &DA, llvm::dwarf::DwarfFormat Format, uint64_t Offset)
Function Documentation
parseDWARF32StringOffsetsTableHeader()
static Expected<StrOffsetsContributionDescriptor> parseDWARF32StringOffsetsTableHeader (DWARFDataExtractor & DA, uint64_t Offset) static
Definition at line 901 of file DWARFUnit.cpp.
References llvm::createStringError(), llvm::dwarf::DW_LENGTH_lo_reserved, llvm::dwarf::DWARF32, llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::invalid_argument, llvm::DataExtractor::isValidOffsetForDataOfSize(), and llvm::IndexedInstrProf::Version.
Referenced by parseDWARFStringOffsetsTableHeader().
parseDWARF64StringOffsetsTableHeader()
static Expected<StrOffsetsContributionDescriptor> parseDWARF64StringOffsetsTableHeader (DWARFDataExtractor & DA, uint64_t Offset) static
Definition at line 883 of file DWARFUnit.cpp.
References llvm::createStringError(), llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::invalid_argument, llvm::DataExtractor::isValidOffsetForDataOfSize(), Size, and llvm::IndexedInstrProf::Version.
Referenced by parseDWARFStringOffsetsTableHeader().
parseDWARFStringOffsetsTableHeader()
static Expected<StrOffsetsContributionDescriptor> parseDWARFStringOffsetsTableHeader (DWARFDataExtractor & DA, llvm::dwarf::DwarfFormat Format, uint64_t Offset) static
Definition at line 918 of file DWARFUnit.cpp.
References llvm::createStringError(), llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, llvm::invalid_argument, parseDWARF32StringOffsetsTableHeader(), parseDWARF64StringOffsetsTableHeader(), and llvm::StrOffsetsContributionDescriptor::validateContributionSize().
Referenced by llvm::DWARFUnit::determineStringOffsetsTableContribution(), and llvm::DWARFUnit::determineStringOffsetsTableContributionDWO().
parseListTableHeader()
template<typename ListTableType > static Expected<ListTableType> parseListTableHeader (DWARFDataExtractor & DA, uint64_t Offset, DwarfFormat Format) static
Definition at line 337 of file DWARFUnit.cpp.
References llvm::createStringError(), E, llvm::DWARFListTableHeader::getHeaderSize(), llvm::BTF::HeaderSize, and llvm::invalid_argument.