LLVM: lib/DebugInfo/DWARF/DWARFDebugLoc.cpp File Reference
DWARFDebugLoc.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFExpression.h"
#include "llvm/DebugInfo/DWARF/DWARFRelocMap.h"
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cinttypes>
#include <cstdint>
#include "llvm/BinaryFormat/Dwarf.def"
Macros
#define HANDLE_DW_LLE(ID, NAME)
Functions
static Error createResolverError (uint32_t Index, unsigned Kind)
static void dumpExpression (raw_ostream &OS, ArrayRef< uint8_t > Data, bool IsLittleEndian, unsigned AddressSize, const MCRegisterInfo *MRI, DWARFUnit *U)
Macro Definition Documentation
HANDLE_DW_LLE
#define HANDLE_DW_LLE (ID, NAME)
Value:
MaxEncodingStringLength = std::max(MaxEncodingStringLength,                  \
                                     dwarf::LocListEncodingString(ID).size());
Function Documentation
createResolverError()
static Error createResolverError (uint32_t Index, unsigned Kind) static
Definition at line 43 of file DWARFDebugLoc.cpp.
References llvm::object::SectionedAddress::Address, llvm::createStringError(), E, llvm::inconvertibleErrorCode(), llvm::invalid_argument, llvm::DWARFLocationEntry::Kind, llvm_unreachable, llvm::DWARFLocationEntry::Loc, llvm::dwarf::LocListEncodingString(), llvm::None, llvm::DWARFLocationEntry::SectionIndex, llvm::object::SectionedAddress::SectionIndex, llvm::DWARFLocationEntry::Value0, and llvm::DWARFLocationEntry::Value1.
dumpExpression()
static void dumpExpression (raw_ostream & OS, ArrayRef< uint8_t > Data, bool IsLittleEndian, unsigned AddressSize, const MCRegisterInfo * MRI, DWARFUnit * U) static
Definition at line 114 of file DWARFDebugLoc.cpp.
References llvm::dwarf::DWARF_VERSION, llvm::DWARFExpression::print(), and llvm::toStringRef().
Referenced by llvm::DWARFLocationTable::dumpLocationList().