LLVM: lib/MC/MCParser/ELFAsmParser.cpp File Reference
ELFAsmParser.cpp File Reference
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SMLoc.h"
#include <cassert>
#include <cstdint>
#include <utility>
Namespaces
llvm
This class represents lattice values for constants.
Functions
static unsigned parseSectionFlags (StringRef flagsStr, bool *UseLastGroup)
static bool hasPrefix (StringRef SectionName, StringRef Prefix)
static MCSymbolAttr MCAttrForString (StringRef Type)
MCAsmParserExtension * llvm::createELFAsmParser ()
Function Documentation
hasPrefix()
static bool hasPrefix (StringRef SectionName, StringRef Prefix) static
Definition at line 482 of file ELFAsmParser.cpp.
References llvm::AsmToken::Comma, llvm::StringRef::drop_back(), llvm::StringRef::empty(), llvm::AsmToken::EndOfStatement, llvm::StringRef::getAsInteger(), llvm::MCSection::getBeginSymbol(), llvm::AsmToken::Hash, llvm::MCAsmLexer::isNot(), parseSectionFlags(), AMDGPU::ElfNote::SectionName, llvm::MCSection::setBeginSymbol(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_TLS, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_LLVM_CALL_GRAPH_PROFILE, llvm::ELF::SHT_LLVM_DEPENDENT_LIBRARIES, llvm::ELF::SHT_LLVM_LINKER_OPTIONS, llvm::ELF::SHT_LLVM_ODRTAB, llvm::ELF::SHT_LLVM_SYMPART, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PREINIT_ARRAY, llvm::ELF::SHT_PROGBITS, llvm::ELF::SHT_X86_64_UNWIND, llvm::StringRef::startswith(), llvm::AsmToken::String, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName, and llvm::Warning.
MCAttrForString()
static MCSymbolAttr MCAttrForString (StringRef Type) static
Definition at line 667 of file ELFAsmParser.cpp.
References llvm::AsmToken::At, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), llvm::AsmToken::Comma, llvm::MCSymbolRefExpr::create(), llvm::Data, llvm::StringSwitch< T, R >::Default(), llvm::AsmToken::EndOfStatement, llvm::Error, llvm::StringRef::find(), From, llvm::AsmToken::Hash, llvm::AsmToken::Identifier, llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, llvm::MCSA_Invalid, Name, llvm::Note, llvm::StringRef::npos, llvm::AsmToken::Percent, llvm::ELF::SHT_NOTE, llvm::StringRef::size(), llvm::AsmToken::String, and llvm::MCSymbolRefExpr::VK_None.
parseSectionFlags()
static unsigned parseSectionFlags (StringRef flagsStr, bool * UseLastGroup) static
Definition at line 281 of file ELFAsmParser.cpp.
References llvm::AsmToken::At, llvm::AsmToken::Comma, llvm::MCAsmLexer::getAllowAtInIdentifier(), llvm::StringRef::getAsInteger(), llvm::AsmToken::Hash, llvm::AsmToken::Identifier, llvm::AsmToken::Integer, llvm::MCAsmLexer::is(), llvm::MCSymbol::isInSection(), llvm::MCAsmLexer::isNot(), llvm::isUInt< 32 >(), Name, llvm::AsmToken::Percent, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_ARM_PURECODE, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_HEX_GPREL, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_TLS, llvm::ELF::SHF_WRITE, llvm::AsmToken::String, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName, llvm::ELF::XCORE_SHF_CP_SECTION, and llvm::ELF::XCORE_SHF_DP_SECTION.
Referenced by hasPrefix().