LLVM: lib/ObjectYAML/ELFEmitter.cpp File Reference
ELFEmitter.cpp File Reference
The ELF component of yaml2obj.
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/ObjectYAML/ELFYAML.h"
#include "llvm/ObjectYAML/yaml2obj.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
llvm
This class represents lattice values for constants.
llvm::yaml
Functions
template<class T >
static size_t arrayDataSize (ArrayRef< T > A)
template<class T >
static void writeArrayData (raw_ostream &OS, ArrayRef< T > A)
template<class T >
static void zero (T &Obj)
template<class ELFT >
static void overrideFields (ELFYAML::Section *From, typename ELFT::Shdr &To)
static size_t findFirstNonGlobal (ArrayRef< ELFYAML::Symbol > Symbols)
static uint64_t writeContent (raw_ostream &OS, const Optional< yaml::BinaryRef > &Content, const Optional< llvm::yaml::Hex64 > &Size)
static bool isMips64EL (const ELFYAML::Object &Doc)
bool llvm::yaml::yaml2elf (ELFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
Detailed Description
The ELF component of yaml2obj.
Definition in file ELFEmitter.cpp.
Function Documentation
arrayDataSize()
template<class T > static size_t arrayDataSize (ArrayRef< T > A) static
Definition at line 224 of file ELFEmitter.cpp.
References llvm::ArrayRef< T >::size(), and llvm::T.
Referenced by writeArrayData(), and writeContent().
findFirstNonGlobal()
static size_t findFirstNonGlobal (ArrayRef< ELFYAML::Symbol > Symbols) static
Definition at line 504 of file ELFEmitter.cpp.
References I, llvm::ArrayRef< T >::size(), and llvm::ELF::STB_LOCAL.
Referenced by writeContent().
isMips64EL()
static bool isMips64EL (const ELFYAML::Object & Doc) static
Definition at line 784 of file ELFEmitter.cpp.
References llvm::ELFYAML::StackSizeEntry::Address, llvm::arrayRefFromStringRef(), llvm::ELFYAML::MipsABIFlags::ASEs, llvm::object::Elf_Mips_ABIFlags< ELFT >::ases, assert(), llvm::ELFYAML::VerneedEntry::AuxV, llvm::yaml::BinaryRef::binary_size(), llvm::ELFYAML::GnuHashSection::BloomFilter, llvm::ELFYAML::HashSection::Bucket, C, llvm::ELFYAML::HashSection::Chain, llvm::ELFYAML::FileHeader::Class, llvm::ELFYAML::StackSizesSection::Content, llvm::ELFYAML::DynamicSection::Content, llvm::ELFYAML::NoteSection::Content, llvm::ELFYAML::HashSection::Content, llvm::ELFYAML::GnuHashSection::Content, llvm::ELFYAML::VerneedSection::Content, llvm::ELFYAML::AddrsigSection::Content, llvm::ELFYAML::LinkerOptionsSection::Content, llvm::ELFYAML::DependentLibrariesSection::Content, llvm::ELFYAML::VerdefSection::Content, llvm::ELFYAML::RelrSection::Content, llvm::object::Elf_Mips_ABIFlags< ELFT >::cpr1_size, llvm::ELFYAML::MipsABIFlags::CPR1Size, llvm::object::Elf_Mips_ABIFlags< ELFT >::cpr2_size, llvm::ELFYAML::MipsABIFlags::CPR2Size, llvm::ELFYAML::FileHeader::Data, llvm::StringRef::data(), llvm::ELFYAML::NoteEntry::Desc, llvm::ELFYAML::dropUniqueSuffix(), E, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::EM_MIPS, llvm::StringRef::empty(), llvm::encodeULEB128(), llvm::ELFYAML::StackSizesSection::Entries, llvm::ELFYAML::DynamicSection::Entries, llvm::ELFYAML::SymverSection::Entries, llvm::ELFYAML::VerdefSection::Entries, llvm::ELFYAML::RelrSection::Entries, llvm::ELFYAML::SymtabShndxSection::Entries, llvm::ELFYAML::Section::EntSize, llvm::ELFYAML::VerneedEntry::File, llvm::ELFYAML::VernauxEntry::Flags, llvm::ELFYAML::VerdefEntry::Flags, llvm::ELFYAML::MipsABIFlags::Flags1, llvm::object::Elf_Mips_ABIFlags< ELFT >::flags1, llvm::ELFYAML::MipsABIFlags::Flags2, llvm::object::Elf_Mips_ABIFlags< ELFT >::flags2, llvm::object::Elf_Mips_ABIFlags< ELFT >::fp_abi, llvm::ELFYAML::MipsABIFlags::FpABI, llvm::object::Elf_Mips_ABIFlags< ELFT >::gpr_size, llvm::ELFYAML::MipsABIFlags::GPRSize, llvm::ELF::GRP_COMDAT, llvm::ELFYAML::VernauxEntry::Hash, llvm::ELFYAML::VerdefEntry::Hash, llvm::ELFYAML::GnuHashSection::HashBuckets, llvm::ELFYAML::GnuHashSection::HashValues, llvm::ELFYAML::GnuHashSection::Header, llvm::ELFYAML::Object::Header, I, if(), llvm::ELFYAML::AddrsigSymbol::Index, llvm::ELFYAML::VerneedSection::Info, llvm::ELFYAML::VerdefSection::Info, llvm::StringSet< AllocatorTy >::insert(), llvm::object::Elf_Mips_ABIFlags< ELFT >::isa_ext, llvm::object::Elf_Mips_ABIFlags< ELFT >::isa_level, llvm::object::Elf_Mips_ABIFlags< ELFT >::isa_rev, llvm::ELFYAML::MipsABIFlags::ISAExtension, llvm::ELFYAML::MipsABIFlags::ISALevel, llvm::ELFYAML::MipsABIFlags::ISARevision, llvm::ELFYAML::LinkerOption::Key, llvm::ELFYAML::DependentLibrariesSection::Libs, llvm::codeview::Link, llvm::ELFYAML::Section::Link, llvm_unreachable, llvm::AArch64CC::LO, llvm::ELFYAML::FileHeader::Machine, llvm::makeArrayRef(), llvm::ELFYAML::Group::Members, llvm::ELFYAML::Symbol::Name, llvm::ELFYAML::NoteEntry::Name, llvm::ELFYAML::Chunk::Name, llvm::ELFYAML::VernauxEntry::Name, llvm::ELFYAML::AddrsigSymbol::Name, llvm::AArch64CC::NE, llvm::None, llvm::ELFYAML::NoteSection::Notes, llvm::ELFYAML::LinkerOptionsSection::Options, llvm::ELFYAML::VernauxEntry::Other, llvm::ELFYAML::Fill::Pattern, llvm::ELFYAML::Object::ProgramHeaders, llvm::ELFYAML::RelocationSection::RelocatableSec, llvm::ELFYAML::RelocationSection::Relocations, reportError(), llvm::ELFYAML::SectionOrType::sectionNameOrType, llvm::ELFYAML::Fill::ShOffset, llvm::ELF::SHT_DYNAMIC, llvm::ELF::SHT_GROUP, llvm::ELF::SHT_MIPS_ABIFLAGS, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, llvm::ELFYAML::Group::Signature, llvm::ELFYAML::StackSizeEntry::Size, llvm::StringRef::size(), llvm::ArrayRef< T >::size(), llvm::ELFYAML::Fill::Size, llvm::ELFYAML::StackSizesSection::Size, llvm::ELFYAML::NoteSection::Size, llvm::ELFYAML::HashSection::Size, llvm::ELFYAML::AddrsigSection::Size, llvm::ELFYAML::AddrsigSection::Symbols, llvm::ELFYAML::DynamicEntry::Tag, llvm::raw_ostream::tell(), llvm::ELFYAML::NoteEntry::Type, llvm::ELFYAML::Section::Type, llvm::Twine::utohexstr(), llvm::ELFYAML::DynamicEntry::Val, llvm::ELFYAML::LinkerOption::Value, llvm::ELFYAML::VerdefEntry::VerNames, llvm::ELFYAML::VerneedSection::VerneedV, llvm::ELFYAML::VerneedEntry::Version, llvm::ELFYAML::VerdefEntry::Version, llvm::ELFYAML::MipsABIFlags::Version, llvm::object::Elf_Mips_ABIFlags< ELFT >::version, llvm::IndexedInstrProf::Version, llvm::ELFYAML::VerdefEntry::VersionNdx, llvm::raw_ostream::write(), llvm::raw_ostream::write_zeros(), writeArrayData(), llvm::yaml::BinaryRef::writeAsBinary(), writeContent(), and zero().
overrideFields()
template<class ELFT > static void overrideFields (ELFYAML::Section * From, typename ELFT::Shdr & To) static
Definition at line 357 of file ELFEmitter.cpp.
References llvm::ELFYAML::Section::ShFlags, llvm::ELFYAML::Section::ShName, llvm::ELFYAML::Section::ShOffset, llvm::ELFYAML::Section::ShSize, and llvm::Reloc::Static.
writeArrayData()
template<class T > static void writeArrayData (raw_ostream & OS, ArrayRef< T > A) static
Definition at line 228 of file ELFEmitter.cpp.
References arrayDataSize(), llvm::ArrayRef< T >::data(), and llvm::raw_ostream::write().
Referenced by isMips64EL(), and writeContent().
writeContent()
static uint64_t writeContent (raw_ostream & OS, const Optional< yaml::BinaryRef > & Content, const Optional< llvm::yaml::Hex64 > & Size) static
Definition at line 511 of file ELFEmitter.cpp.
References llvm::ELFYAML::Section::Address, llvm::ELFYAML::Section::AddressAlign, arrayDataSize(), assert(), llvm::yaml::BinaryRef::binary_size(), llvm::ELFYAML::Object::Chunks, llvm::ELFYAML::RawContentSection::Content, llvm::ELFYAML::dropUniqueSuffix(), llvm::StringRef::empty(), llvm::ArrayRef< T >::empty(), llvm::ELFYAML::Section::EntSize, F(), findFirstNonGlobal(), llvm::ELFYAML::Section::Flags, for(), llvm::StringTableBuilder::getOffset(), llvm::StringTableBuilder::getSize(), H, I, llvm::ELFYAML::RawContentSection::Info, llvm::codeview::Link, llvm::ELFYAML::Section::Link, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::makeArrayRef(), llvm::ELFYAML::Chunk::Name, reportError(), llvm::MipsISD::Ret, llvm::ELFYAML::SectionName::Section, llvm::ELFYAML::ProgramHeader::Sections, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_PROGBITS, llvm::ELF::SHT_STRTAB, llvm::ELF::SHT_SYMTAB, Size, llvm::ArrayRef< T >::size(), llvm::ELFYAML::RawContentSection::Size, llvm::Reloc::Static, llvm::ARMBuildAttrs::Symbol, llvm::ELFYAML::Section::Type, llvm::StringTableBuilder::write(), llvm::raw_ostream::write_zeros(), writeArrayData(), llvm::yaml::BinaryRef::writeAsBinary(), and zero().
Referenced by isMips64EL().
zero()
template<class T > static void zero (T & Obj) static
Definition at line 232 of file ELFEmitter.cpp.
References assert(), llvm::StringMap< NoneType, AllocatorTy >::count(), D, llvm::ELF::EI_ABIVERSION, llvm::ELF::EI_CLASS, llvm::ELF::EI_DATA, llvm::ELF::EI_MAG0, llvm::ELF::EI_MAG1, llvm::ELF::EI_MAG2, llvm::ELF::EI_MAG3, llvm::ELF::EI_OSABI, llvm::ELF::EI_VERSION, llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::StringRef::empty(), llvm::ELF::EV_CURRENT, llvm::StringSet< AllocatorTy >::insert(), llvm::ELFYAML::Chunk::RawContent, reportError(), llvm::ELF::SHT_NULL, llvm::to_integer(), and llvm::raw_ostream::write().
Referenced by adjustDown(), llvm::BinaryOperator::CreateFNeg(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUWNeg(), isMips64EL(), and writeContent().