LLVM: lib/Transforms/IPO/ElimAvailExtern.cpp File Reference
ElimAvailExtern.cpp File Reference
#include "llvm/Transforms/IPO/ElimAvailExtern.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
Macros
#define DEBUG_TYPE "elim-avail-extern"
Functions
STATISTIC (NumFunctions, "Number of functions removed")
STATISTIC (NumVariables, "Number of global variables removed")
static bool eliminateAvailableExternally (Module &M)
INITIALIZE_PASS (EliminateAvailableExternallyLegacyPass, "elim-avail-extern", "Eliminate Available Externally Globals", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "elim-avail-extern"
Definition at line 28 of file ElimAvailExtern.cpp.
Function Documentation
eliminateAvailableExternally()
static bool eliminateAvailableExternally (Module & M) static
Definition at line 33 of file ElimAvailExtern.cpp.
References llvm::Constant::destroyConstant(), llvm::GlobalValue::ExternalLinkage, F(), llvm::Module::globals(), and llvm::isSafeToDestroyConstant().
Referenced by llvm::EliminateAvailableExternallyPass::run().
INITIALIZE_PASS()
INITIALIZE_PASS (EliminateAvailableExternallyLegacyPass , "elim-avail-extern" , "Eliminate Available Externally Globals" , false , false)
Definition at line 97 of file ElimAvailExtern.cpp.
STATISTIC() [1/2]
STATISTIC (NumFunctions , "Number of functions removed")
STATISTIC() [2/2]
STATISTIC (NumVariables , "Number of global variables removed")