LLVM: lib/Transforms/Utils/EntryExitInstrumenter.cpp File Reference
EntryExitInstrumenter.cpp File Reference
#include "llvm/Transforms/Utils/EntryExitInstrumenter.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils.h"
Functions
static void insertCall (Function &CurFn, StringRef Func, Instruction *InsertionPt, DebugLoc DL)
static bool runOnFunction (Function &F, bool PostInlining)
INITIALIZE_PASS (EntryExitInstrumenter, "ee-instrument", "Instrument function entry/exit with calls to e.g. mcount() (pre inlining)", false, false) INITIALIZE_PASS(PostInlineEntryExitInstrumenter
post inline ee Instrument function entry exit with calls to e g mcount () " "(post inlining)"
Variables
post inline ee instrument
post inline ee Instrument function entry exit with calls to e g false
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (EntryExitInstrumenter , "ee-instrument" , "Instrument function entry/exit with calls to e.g. mcount() (pre inlining)" , false , false)
Referenced by runOnFunction().
insertCall()
static void insertCall (Function & CurFn, StringRef Func, Instruction * InsertionPt, DebugLoc DL) static
Definition at line 21 of file EntryExitInstrumenter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, C, llvm::CallInst::Create(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::ConstantExpr::getBitCast(), llvm::BasicBlock::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::Module::getOrInsertFunction(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Type::getVoidTy(), llvm::report_fatal_error(), and llvm::Instruction::setDebugLoc().
Referenced by runOnFunction().
mcount()
post inline ee Instrument function entry exit with calls to e g mcount ()
runOnFunction()
static bool runOnFunction (Function & F, bool PostInlining) static
Definition at line 66 of file EntryExitInstrumenter.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::Function::begin(), llvm::StringRef::empty(), F(), llvm::AttributeList::FunctionIndex, llvm::DebugLoc::get(), llvm::Instruction::getDebugLoc(), llvm::Function::getFnAttribute(), llvm::PassRegistry::getPassRegistry(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::Function::getSubprogram(), llvm::Attribute::getValueAsString(), INITIALIZE_PASS(), llvm::initializeEntryExitInstrumenterPass(), llvm::initializePostInlineEntryExitInstrumenterPass(), insertCall(), and llvm::Function::removeAttribute().
Referenced by addDiscriminators(), llvm::AMDGPULibCalls::AMDGPULibCalls(), llvm::LoopVersioning::annotateInstWithNoAlias(), atomicSizeSupported(), cloneConstantExprWithNewAddressSpace(), collectSupportedLoops(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), createCallInst(), llvm::createCodeGenPreparePass(), llvm::createConstantHoistingPass(), llvm::createConstantPropagationPass(), llvm::createCostModelAnalysisPass(), llvm::createDwarfEHPass(), llvm::createFalkorMarkStridedAccessesPass(), llvm::createGCInfoPrinter(), createHWLoopAnalysis(), llvm::createLoadStoreVectorizerPass(), llvm::createLoopSimplifyPass(), llvm::createLowerSwitchPass(), llvm::createMemDepPrinter(), llvm::createMemDerefPrinter(), llvm::createNaryReassociatePass(), llvm::createSampleProfileLoaderPass(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), llvm::MachineModuleInfo::deleteMachineFunctionFor(), doCallSiteSplitting(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::GVNExpression::Expression::dump(), llvm::AliasSetTracker::dump(), dumpScopes(), eliminateLoadsAcrossLoops(), eliminateTailRecursion(), enableCallSafepoints(), ensurePromotedGV(), eraseDeadBBsAndChildren(), explicifyGuards(), FindPredecessorAutoreleaseWithSafePath(), formLCSSAOnAllLoops(), llvm::FPPassManager::FPPassManager(), llvm::FunctionPass::FunctionPass(), llvm::AAResultsWrapperPass::getAAResults(), llvm::LazyBlockFrequencyInfoPass::getBFI(), llvm::BlockFrequencyInfoWrapperPass::getBFI(), llvm::BranchProbabilityInfoWrapperPass::getBPI(), GetCtorAndDtorPriority(), llvm::DominanceFrontierWrapperPass::getDominanceFrontier(), llvm::DominatorTreeWrapperPass::getDomTree(), llvm::LoopInfoWrapperPass::getLoopInfo(), getMulHu(), GetPointerOperand(), llvm::PostDominatorTreeWrapperPass::getPostDomTree(), llvm::RegionInfoPass::getRegionInfo(), llvm::SCEVAAWrapperPass::getResult(), llvm::StackSafetyInfoWrapperPass::getResult(), llvm::PhiValuesWrapperPass::getResult(), llvm::BasicAAWrapperPass::getResult(), llvm::ScalarEvolutionWrapperPass::getSE(), INITIALIZE_PASS(), llvm::InjectTLIMappingsLegacy::InjectTLIMappingsLegacy(), insertIfNamed(), InsertRootInitializers(), IsInRanges(), isMustExecuteIn(), isPromotedResultSafe(), isReInterleaveMask(), iterativelyFlattenCFG(), lowerGuardIntrinsic(), lowerSubFn(), lowerWidenableCondition(), MarkBlocksLiveIn(), llvm::operator<<(), optimizeDivRem(), parseCHRFilterFiles(), patchAndReplaceAllUsesWith(), PGOMemOPSizeOptImpl(), postDominates(), llvm::AlignmentFromAssumptionsPass::processAssumption(), replaceDevirtTrigger(), llvm::BoundsCheckingPass::run(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::LowerAtomicPass::run(), llvm::DCEPass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::PromotePass::run(), llvm::SinkingPass::run(), llvm::BDCEPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::EntryExitInstrumenterPass::run(), llvm::GuardWideningPass::run(), llvm::WarnMissedTransformationsPass::run(), llvm::DSEPass::run(), llvm::LowerExpectIntrinsicPass::run(), llvm::CFGViewerPass::run(), llvm::ADCEPass::run(), llvm::EarlyCSEPass::run(), llvm::LowerConstantIntrinsicsPass::run(), llvm::SCCPPass::run(), llvm::SafepointIRVerifierPass::run(), llvm::SimplifyCFGPass::run(), llvm::ReassociatePass::run(), llvm::PrintFunctionPass::run(), llvm::MemCpyOptPass::runImpl(), runImpl(), llvm::FPPassManager::runOnModule(), scalarizeMaskedCompressStore(), setCannotDuplicate(), setFastFlags(), llvm::simplifyLoop(), tryToUnrollAndJamLoop(), TypeSizeToSizeIndex(), unifyBitWidth(), unifyReturnBlockSet(), updatePredecessorProfileMetadata(), llvm::verifyModule(), writeCFGToDotFile(), and llvm::LazyValueInfoWrapperPass::~LazyValueInfoWrapperPass().
Variable Documentation
false
post inline ee Instrument function entry exit with calls to e g false
Definition at line 156 of file EntryExitInstrumenter.cpp.
instrument
post inline ee instrument
Definition at line 153 of file EntryExitInstrumenter.cpp.