LLVM: lib/Transforms/Utils/EscapeEnumerator.cpp File Reference
EscapeEnumerator.cpp File Reference
#include "llvm/Transforms/Utils/EscapeEnumerator.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Module.h"
Functions
static FunctionCallee getDefaultPersonalityFn (Module *M)
Function Documentation
getDefaultPersonalityFn()
static FunctionCallee getDefaultPersonalityFn (Module * M) static
Definition at line 21 of file EscapeEnumerator.cpp.
References C, llvm::FunctionType::get(), llvm::Module::getContext(), llvm::getDefaultEHPersonality(), llvm::getEHPersonalityName(), llvm::Type::getInt32Ty(), llvm::Module::getOrInsertFunction(), llvm::Module::getTargetTriple(), and llvm::T.
Referenced by llvm::EscapeEnumerator::Next().