LLVM: lib/ExecutionEngine/Interpreter/Execution.cpp File Reference
Execution.cpp File Reference
#include "Interpreter.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/IntrinsicLowering.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cmath>
Macros
#define DEBUG_TYPE "interpreter"
#define IMPLEMENT_BINARY_OPERATOR(OP, TY)
#define IMPLEMENT_INTEGER_ICMP(OP, TY)
#define IMPLEMENT_VECTOR_INTEGER_ICMP(OP, TY)
#define IMPLEMENT_POINTER_ICMP(OP)
#define IMPLEMENT_FCMP(OP, TY)
#define IMPLEMENT_VECTOR_FCMP_T(OP, TY)
#define IMPLEMENT_VECTOR_FCMP(OP)
#define IMPLEMENT_SCALAR_NANS(TY, X, Y)
#define MASK_VECTOR_NANS_T(X, Y, TZ, FLAG)
#define MASK_VECTOR_NANS(TY, X, Y, FLAG)
#define IMPLEMENT_UNORDERED(TY, X, Y)
#define IMPLEMENT_VECTOR_UNORDERED(TY, X, Y, FUNC)
#define INTEGER_VECTOR_OPERATION(OP)
#define INTEGER_VECTOR_FUNCTION(OP)
#define FLOAT_VECTOR_FUNCTION(OP, TY)
#define FLOAT_VECTOR_OP(OP)
#define IMPLEMENT_VAARG(TY) case Type::TY##TyID: Dest.TY##Val = Src.TY##Val; break
Functions
STATISTIC (NumDynamicInsts, "Number of dynamic instructions executed")
static void SetValue (Value *V, GenericValue Val, ExecutionContext &SF)
static void executeFNegInst (GenericValue &Dest, GenericValue Src, Type *Ty)
static void executeFAddInst (GenericValue &Dest, GenericValue Src1, GenericValue Src2, Type *Ty)
static void executeFSubInst (GenericValue &Dest, GenericValue Src1, GenericValue Src2, Type *Ty)
static void executeFMulInst (GenericValue &Dest, GenericValue Src1, GenericValue Src2, Type *Ty)
static void executeFDivInst (GenericValue &Dest, GenericValue Src1, GenericValue Src2, Type *Ty)
static void executeFRemInst (GenericValue &Dest, GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_EQ (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_NE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_ULT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_SLT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_UGT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_SGT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_ULE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_SLE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_UGE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeICMP_SGE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_OEQ (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_ONE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_OLE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_OGE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_OLT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_OGT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_UEQ (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_UNE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_ULE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_UGE (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_ULT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_UGT (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_ORD (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_UNO (GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeFCMP_BOOL (GenericValue Src1, GenericValue Src2, Type *Ty, const bool val)
static GenericValue executeCmpInst (unsigned predicate, GenericValue Src1, GenericValue Src2, Type *Ty)
static GenericValue executeSelectInst (GenericValue Src1, GenericValue Src2, GenericValue Src3, Type *Ty)
static unsigned getShiftAmount (uint64_t orgShiftAmount, llvm::APInt valueToShift)
Variables
static cl::opt< bool > PrintVolatile ("interpreter-print-volatile", cl::Hidden, cl::desc("make the interpreter print every volatile load and store"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "interpreter"
Definition at line 30 of file Execution.cpp.
FLOAT_VECTOR_FUNCTION
#define FLOAT_VECTOR_FUNCTION (OP, TY)
Value:
for (unsigned i = 0; i < R.AggregateVal.size(); ++i)          \
        R.AggregateVal[i].TY =                                      \
        Src1.AggregateVal[i].TY OP Src2.AggregateVal[i].TY;
FLOAT_VECTOR_OP
#define FLOAT_VECTOR_OP (OP)
Value:
{                                         \
  if (cast<VectorType>(Ty)->getElementType()->isFloatTy())            \
    FLOAT_VECTOR_FUNCTION(OP, FloatVal)                               \
  else {                                                              \
    if (cast<VectorType>(Ty)->getElementType()->isDoubleTy())         \
      FLOAT_VECTOR_FUNCTION(OP, DoubleVal)                            \
    else {                                                            \
      dbgs() << "Unhandled type for OP instruction: " << *Ty << "\n"; \
      llvm_unreachable(0);                                            \
    }                                                                 \
  }                                                                   \
}
Referenced by llvm::Interpreter::visitBinaryOperator().
IMPLEMENT_BINARY_OPERATOR
#define IMPLEMENT_BINARY_OPERATOR (OP, TY)
Value:
case Type::TY##TyID: \
     Dest.TY##Val = Src1.TY##Val OP Src2.TY##Val; \
     break
Definition at line 103 of file Execution.cpp.
Referenced by executeFAddInst(), executeFDivInst(), executeFMulInst(), and executeFSubInst().
IMPLEMENT_FCMP
#define IMPLEMENT_FCMP (OP, TY)
Value:
case Type::TY##TyID: \
     Dest.IntVal = APInt(1,Src1.TY##Val OP Src2.TY##Val); \
     break
Definition at line 357 of file Execution.cpp.
Referenced by executeFCMP_OEQ(), executeFCMP_OGE(), executeFCMP_OGT(), executeFCMP_OLE(), executeFCMP_OLT(), and executeFCMP_ONE().
IMPLEMENT_INTEGER_ICMP
#define IMPLEMENT_INTEGER_ICMP (OP, TY)
Value:
case Type::IntegerTyID:  \
      Dest.IntVal = APInt(1,Src1.IntVal.OP(Src2.IntVal)); \
      break;
Definition at line 167 of file Execution.cpp.
Referenced by executeICMP_EQ(), executeICMP_NE(), executeICMP_SGE(), executeICMP_SGT(), executeICMP_SLE(), executeICMP_SLT(), executeICMP_UGE(), executeICMP_UGT(), executeICMP_ULE(), and executeICMP_ULT().
IMPLEMENT_POINTER_ICMP
#define IMPLEMENT_POINTER_ICMP (OP)
Value:
case Type::PointerTyID: \
      Dest.IntVal = APInt(1,(void*)(intptr_t)Src1.PointerVal OP \
                            (void*)(intptr_t)Src2.PointerVal); \
      break;
Definition at line 185 of file Execution.cpp.
Referenced by executeICMP_EQ(), executeICMP_NE(), executeICMP_SGE(), executeICMP_SGT(), executeICMP_SLE(), executeICMP_SLT(), executeICMP_UGE(), executeICMP_UGT(), executeICMP_ULE(), and executeICMP_ULT().
IMPLEMENT_SCALAR_NANS
#define IMPLEMENT_SCALAR_NANS (TY, X, Y)
Value:
if (TY->isFloatTy()) {                                                    \
    if (X.FloatVal != X.FloatVal || Y.FloatVal != Y.FloatVal) {             \
      Dest.IntVal = APInt(1,false);                                         \
      return Dest;                                                          \
    }                                                                       \
  } else {                                                                  \
    if (X.DoubleVal != X.DoubleVal || Y.DoubleVal != Y.DoubleVal) {         \
      Dest.IntVal = APInt(1,false);                                         \
      return Dest;                                                          \
    }                                                                       \
  }
Definition at line 392 of file Execution.cpp.
Referenced by executeFCMP_ONE().
IMPLEMENT_UNORDERED
#define IMPLEMENT_UNORDERED (TY, X, Y)
Value:
if (TY->isFloatTy()) {                                                 \
    if (X.FloatVal != X.FloatVal || Y.FloatVal != Y.FloatVal) {          \
      Dest.IntVal = APInt(1,true);                                       \
      return Dest;                                                       \
    }                                                                    \
  } else if (X.DoubleVal != X.DoubleVal || Y.DoubleVal != Y.DoubleVal) { \
    Dest.IntVal = APInt(1,true);                                         \
    return Dest;                                                         \
  }
Definition at line 510 of file Execution.cpp.
Referenced by executeFCMP_UEQ(), executeFCMP_UGE(), executeFCMP_UGT(), executeFCMP_ULE(), executeFCMP_ULT(), and executeFCMP_UNE().
IMPLEMENT_VAARG
#define IMPLEMENT_VAARG (TY) case Type::TY##TyID: Dest.TY##Val = Src.TY##Val; break
Definition at line 1767 of file Execution.cpp.
Referenced by llvm::Interpreter::visitVAArgInst().
IMPLEMENT_VECTOR_FCMP
#define IMPLEMENT_VECTOR_FCMP (OP)
Value:
case Type::VectorTyID:                                            \
    if (cast<VectorType>(Ty)->getElementType()->isFloatTy()) {      \
      IMPLEMENT_VECTOR_FCMP_T(OP, Float);                           \
    } else {                                                        \
        IMPLEMENT_VECTOR_FCMP_T(OP, Double);                        \
    }
Definition at line 370 of file Execution.cpp.
Referenced by executeFCMP_OEQ(), executeFCMP_OGE(), executeFCMP_OGT(), executeFCMP_OLE(), executeFCMP_OLT(), and executeFCMP_ONE().
IMPLEMENT_VECTOR_FCMP_T
#define IMPLEMENT_VECTOR_FCMP_T (OP, TY)
Value:
assert(Src1.AggregateVal.size() == Src2.AggregateVal.size());     \
  Dest.AggregateVal.resize( Src1.AggregateVal.size() );             \
  for( uint32_t _i=0;_i<Src1.AggregateVal.size();_i++)              \
    Dest.AggregateVal[_i].IntVal = APInt(1,                         \
    Src1.AggregateVal[_i].TY##Val OP Src2.AggregateVal[_i].TY##Val);\
  break;
Definition at line 362 of file Execution.cpp.
IMPLEMENT_VECTOR_INTEGER_ICMP
#define IMPLEMENT_VECTOR_INTEGER_ICMP (OP, TY)
Value:
case Type::VectorTyID: {                                           \
    assert(Src1.AggregateVal.size() == Src2.AggregateVal.size());    \
    Dest.AggregateVal.resize( Src1.AggregateVal.size() );            \
    for( uint32_t _i=0;_i<Src1.AggregateVal.size();_i++)             \
      Dest.AggregateVal[_i].IntVal = APInt(1,                        \
      Src1.AggregateVal[_i].IntVal.OP(Src2.AggregateVal[_i].IntVal));\
  } break;
Definition at line 172 of file Execution.cpp.
Referenced by executeICMP_EQ(), executeICMP_NE(), executeICMP_SGE(), executeICMP_SGT(), executeICMP_SLE(), executeICMP_SLT(), executeICMP_UGE(), executeICMP_UGT(), executeICMP_ULE(), and executeICMP_ULT().
IMPLEMENT_VECTOR_UNORDERED
#define IMPLEMENT_VECTOR_UNORDERED (TY, X, Y, FUNC)
Value:
if (TY->isVectorTy()) {                                                      \
    GenericValue DestMask = Dest;                                              \
    Dest = FUNC(Src1, Src2, Ty);                                               \
    for (size_t _i = 0; _i < Src1.AggregateVal.size(); _i++)                   \
      if (DestMask.AggregateVal[_i].IntVal == true)                            \
        Dest.AggregateVal[_i].IntVal = APInt(1, true);                         \
    return Dest;                                                               \
  }
Definition at line 521 of file Execution.cpp.
Referenced by executeFCMP_UEQ(), executeFCMP_UGE(), executeFCMP_UGT(), executeFCMP_ULE(), executeFCMP_ULT(), and executeFCMP_UNE().
INTEGER_VECTOR_FUNCTION
#define INTEGER_VECTOR_FUNCTION (OP)
Value:
for (unsigned i = 0; i < R.AggregateVal.size(); ++i)           \
      R.AggregateVal[i].IntVal =                                   \
      Src1.AggregateVal[i].IntVal.OP(Src2.AggregateVal[i].IntVal);
Referenced by llvm::Interpreter::visitBinaryOperator().
INTEGER_VECTOR_OPERATION
#define INTEGER_VECTOR_OPERATION (OP)
Value:
for (unsigned i = 0; i < R.AggregateVal.size(); ++i)           \
      R.AggregateVal[i].IntVal =                                   \
      Src1.AggregateVal[i].IntVal OP Src2.AggregateVal[i].IntVal;
Referenced by llvm::Interpreter::visitBinaryOperator().
MASK_VECTOR_NANS
#define MASK_VECTOR_NANS (TY, X, Y, FLAG)
Value:
if (TY->isVectorTy()) {                                                   \
    if (cast<VectorType>(TY)->getElementType()->isFloatTy()) {              \
      MASK_VECTOR_NANS_T(X, Y, Float, FLAG)                                 \
    } else {                                                                \
      MASK_VECTOR_NANS_T(X, Y, Double, FLAG)                                \
    }                                                                       \
  }                                                                         \
Definition at line 417 of file Execution.cpp.
Referenced by executeFCMP_ONE(), executeFCMP_UEQ(), executeFCMP_UGE(), executeFCMP_UGT(), executeFCMP_ULE(), executeFCMP_ULT(), and executeFCMP_UNE().
MASK_VECTOR_NANS_T
#define MASK_VECTOR_NANS_T (X, Y, TZ, FLAG)
Value:
assert(X.AggregateVal.size() == Y.AggregateVal.size());                   \
  Dest.AggregateVal.resize( X.AggregateVal.size() );                        \
  for( uint32_t _i=0;_i<X.AggregateVal.size();_i++) {                       \
    if (X.AggregateVal[_i].TZ##Val != X.AggregateVal[_i].TZ##Val ||         \
        Y.AggregateVal[_i].TZ##Val != Y.AggregateVal[_i].TZ##Val)           \
      Dest.AggregateVal[_i].IntVal = APInt(1,FLAG);                         \
    else  {                                                                 \
      Dest.AggregateVal[_i].IntVal = APInt(1,!FLAG);                        \
    }                                                                       \
  }
Definition at line 405 of file Execution.cpp.
Function Documentation
executeCmpInst()
static GenericValue executeCmpInst (unsigned predicate, GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 698 of file Execution.cpp.
References llvm::dbgs(), executeFCMP_BOOL(), executeFCMP_OEQ(), executeFCMP_OGE(), executeFCMP_OGT(), executeFCMP_OLE(), executeFCMP_OLT(), executeFCMP_ONE(), executeFCMP_ORD(), executeFCMP_UEQ(), executeFCMP_UGE(), executeFCMP_UGT(), executeFCMP_ULE(), executeFCMP_ULT(), executeFCMP_UNE(), executeFCMP_UNO(), executeICMP_EQ(), executeICMP_NE(), executeICMP_SGE(), executeICMP_SGT(), executeICMP_SLE(), executeICMP_SLT(), executeICMP_UGE(), executeICMP_UGT(), executeICMP_ULE(), executeICMP_ULT(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by llvm::Interpreter::visitInsertValueInst().
executeFAddInst()
static void executeFAddInst (GenericValue & Dest, GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 108 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_BINARY_OPERATOR, and llvm_unreachable.
Referenced by llvm::Interpreter::visitBinaryOperator(), and llvm::Interpreter::visitInsertValueInst().
executeFCMP_BOOL()
static GenericValue executeFCMP_BOOL (GenericValue Src1, GenericValue Src2, Type * Ty, const bool val) static
Definition at line 648 of file Execution.cpp.
References llvm::GenericValue::AggregateVal, assert(), llvm::GenericValue::IntVal, and llvm::Type::isVectorTy().
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_OEQ()
static GenericValue executeFCMP_OEQ (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 378 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_FCMP, IMPLEMENT_VECTOR_FCMP, and llvm_unreachable.
Referenced by executeCmpInst(), executeFCMP_UEQ(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_OGE()
static GenericValue executeFCMP_OGE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 468 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_FCMP, IMPLEMENT_VECTOR_FCMP, and llvm_unreachable.
Referenced by executeCmpInst(), executeFCMP_UGE(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_OGT()
static GenericValue executeFCMP_OGT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 496 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_FCMP, IMPLEMENT_VECTOR_FCMP, and llvm_unreachable.
Referenced by executeCmpInst(), executeFCMP_UGT(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_OLE()
static GenericValue executeFCMP_OLE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 454 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_FCMP, IMPLEMENT_VECTOR_FCMP, and llvm_unreachable.
Referenced by executeCmpInst(), executeFCMP_ULE(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_OLT()
static GenericValue executeFCMP_OLT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 482 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_FCMP, IMPLEMENT_VECTOR_FCMP, and llvm_unreachable.
Referenced by executeCmpInst(), executeFCMP_ULT(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_ONE()
static GenericValue executeFCMP_ONE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 428 of file Execution.cpp.
References llvm::GenericValue::AggregateVal, llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_FCMP, IMPLEMENT_SCALAR_NANS, IMPLEMENT_VECTOR_FCMP, llvm::Type::isVectorTy(), llvm_unreachable, and MASK_VECTOR_NANS.
Referenced by executeCmpInst(), executeFCMP_UNE(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_ORD()
static GenericValue executeFCMP_ORD (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 586 of file Execution.cpp.
References llvm::GenericValue::AggregateVal, assert(), llvm::GenericValue::DoubleVal, llvm::GenericValue::FloatVal, llvm::GenericValue::IntVal, llvm::Type::isFloatTy(), and llvm::Type::isVectorTy().
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_UEQ()
static GenericValue executeFCMP_UEQ (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 531 of file Execution.cpp.
References executeFCMP_OEQ(), IMPLEMENT_UNORDERED, IMPLEMENT_VECTOR_UNORDERED, and MASK_VECTOR_NANS.
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_UGE()
static GenericValue executeFCMP_UGE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 559 of file Execution.cpp.
References executeFCMP_OGE(), IMPLEMENT_UNORDERED, IMPLEMENT_VECTOR_UNORDERED, and MASK_VECTOR_NANS.
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_UGT()
static GenericValue executeFCMP_UGT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 577 of file Execution.cpp.
References executeFCMP_OGT(), IMPLEMENT_UNORDERED, IMPLEMENT_VECTOR_UNORDERED, and MASK_VECTOR_NANS.
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_ULE()
static GenericValue executeFCMP_ULE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 550 of file Execution.cpp.
References executeFCMP_OLE(), IMPLEMENT_UNORDERED, IMPLEMENT_VECTOR_UNORDERED, and MASK_VECTOR_NANS.
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_ULT()
static GenericValue executeFCMP_ULT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 568 of file Execution.cpp.
References executeFCMP_OLT(), IMPLEMENT_UNORDERED, IMPLEMENT_VECTOR_UNORDERED, and MASK_VECTOR_NANS.
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_UNE()
static GenericValue executeFCMP_UNE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 541 of file Execution.cpp.
References executeFCMP_ONE(), IMPLEMENT_UNORDERED, IMPLEMENT_VECTOR_UNORDERED, and MASK_VECTOR_NANS.
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFCMP_UNO()
static GenericValue executeFCMP_UNO (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 617 of file Execution.cpp.
References llvm::GenericValue::AggregateVal, assert(), llvm::GenericValue::DoubleVal, llvm::GenericValue::FloatVal, llvm::GenericValue::IntVal, llvm::Type::isFloatTy(), and llvm::Type::isVectorTy().
Referenced by executeCmpInst(), and llvm::Interpreter::visitFCmpInst().
executeFDivInst()
static void executeFDivInst (GenericValue & Dest, GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 141 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_BINARY_OPERATOR, and llvm_unreachable.
Referenced by llvm::Interpreter::visitBinaryOperator(), and llvm::Interpreter::visitInsertValueInst().
executeFMulInst()
static void executeFMulInst (GenericValue & Dest, GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 130 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_BINARY_OPERATOR, and llvm_unreachable.
Referenced by llvm::Interpreter::visitBinaryOperator(), and llvm::Interpreter::visitInsertValueInst().
executeFNegInst()
static void executeFNegInst (GenericValue & Dest, GenericValue Src, Type * Ty) static
Definition at line 49 of file Execution.cpp.
References llvm::Type::DoubleTyID, llvm::GenericValue::DoubleVal, llvm::Type::FloatTyID, llvm::GenericValue::FloatVal, llvm::Type::getTypeID(), and llvm_unreachable.
Referenced by llvm::Interpreter::visitUnaryOperator().
executeFRemInst()
static void executeFRemInst (GenericValue & Dest, GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 152 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::DoubleTyID, llvm::GenericValue::DoubleVal, llvm::Type::FloatTyID, llvm::GenericValue::FloatVal, llvm::Type::getTypeID(), and llvm_unreachable.
Referenced by llvm::Interpreter::visitBinaryOperator(), and llvm::Interpreter::visitInsertValueInst().
executeFSubInst()
static void executeFSubInst (GenericValue & Dest, GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 119 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_BINARY_OPERATOR, and llvm_unreachable.
Referenced by llvm::Interpreter::visitBinaryOperator(), and llvm::Interpreter::visitInsertValueInst().
executeICMP_EQ()
static GenericValue executeICMP_EQ (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 191 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_NE()
static GenericValue executeICMP_NE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 205 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_SGE()
static GenericValue executeICMP_SGE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 317 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_SGT()
static GenericValue executeICMP_SGT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 261 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_SLE()
static GenericValue executeICMP_SLE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 289 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_SLT()
static GenericValue executeICMP_SLT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 233 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_UGE()
static GenericValue executeICMP_UGE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 303 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_UGT()
static GenericValue executeICMP_UGT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 247 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_ULE()
static GenericValue executeICMP_ULE (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 275 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeICMP_ULT()
static GenericValue executeICMP_ULT (GenericValue Src1, GenericValue Src2, Type * Ty) static
Definition at line 219 of file Execution.cpp.
References llvm::dbgs(), llvm::Type::getTypeID(), IMPLEMENT_INTEGER_ICMP, IMPLEMENT_POINTER_ICMP, IMPLEMENT_VECTOR_INTEGER_ICMP, and llvm_unreachable.
Referenced by executeCmpInst(), and llvm::Interpreter::visitICmpInst().
executeSelectInst()
static GenericValue executeSelectInst (GenericValue Src1, GenericValue Src2, GenericValue Src3, Type * Ty) static
Definition at line 843 of file Execution.cpp.
References llvm::GenericValue::AggregateVal, assert(), llvm::GenericValue::IntVal, and llvm::Type::isVectorTy().
Referenced by llvm::Interpreter::visitInsertValueInst(), and llvm::Interpreter::visitSelectInst().
getShiftAmount()
static unsigned getShiftAmount (uint64_t orgShiftAmount, llvm::APInt valueToShift) static
Definition at line 1178 of file Execution.cpp.
References llvm::APInt::getBitWidth(), and llvm::NextPowerOf2().
Referenced by llvm::Interpreter::visitAShr(), llvm::Interpreter::visitLShr(), and llvm::Interpreter::visitShl().
SetValue()
static void SetValue (Value * V, GenericValue Val, ExecutionContext & SF) static
Definition at line 41 of file Execution.cpp.
References llvm::ExecutionContext::Values.
Referenced by llvm::Interpreter::callFunction(), llvm::Interpreter::exitCalled(), llvm::TGParser::PopLocalScope(), QualifiedNameOfImplicitName(), llvm::Interpreter::visitAllocaInst(), llvm::Interpreter::visitAShr(), llvm::Interpreter::visitBinaryOperator(), llvm::Interpreter::visitBitCastInst(), llvm::Interpreter::visitCallSite(), llvm::Interpreter::visitExtractElementInst(), llvm::Interpreter::visitExtractValueInst(), llvm::Interpreter::visitFCmpInst(), llvm::Interpreter::visitFPExtInst(), llvm::Interpreter::visitFPToSIInst(), llvm::Interpreter::visitFPToUIInst(), llvm::Interpreter::visitFPTruncInst(), llvm::Interpreter::visitGetElementPtrInst(), llvm::Interpreter::visitICmpInst(), llvm::Interpreter::visitIndirectBrInst(), llvm::Interpreter::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::Interpreter::visitIntToPtrInst(), llvm::Interpreter::visitLoadInst(), llvm::Interpreter::visitLShr(), llvm::Interpreter::visitPtrToIntInst(), llvm::Interpreter::visitSelectInst(), llvm::Interpreter::visitSExtInst(), llvm::Interpreter::visitShl(), llvm::Interpreter::visitShuffleVectorInst(), llvm::Interpreter::visitSIToFPInst(), llvm::Interpreter::visitTruncInst(), llvm::Interpreter::visitUIToFPInst(), llvm::Interpreter::visitUnaryOperator(), llvm::Interpreter::visitVAArgInst(), and llvm::Interpreter::visitZExtInst().
STATISTIC()
STATISTIC (NumDynamicInsts , "Number of dynamic instructions executed")
Variable Documentation
PrintVolatile
cl::opt<bool> PrintVolatile("interpreter-print-volatile", cl::Hidden, cl::desc("make the interpreter print every volatile load and store")) static
Referenced by llvm::Interpreter::visitLoadInst(), and llvm::Interpreter::visitStoreInst().