LLVM: lib/CodeGen/ExpandPostRAPseudos.cpp File Reference
ExpandPostRAPseudos.cpp File Reference
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "postrapseudos"
Functions
INITIALIZE_PASS (ExpandPostRA, DEBUG_TYPE, "Post-RA pseudo instruction expansion pass", false, false) void ExpandPostRA
TransferImplicitOperands - MI is a pseudo-instruction, and the lowered replacement instructions immediately precede it.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "postrapseudos"
Definition at line 28 of file ExpandPostRAPseudos.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ExpandPostRA , DEBUG_TYPE , "Post-RA pseudo instruction expansion pass" , false , false)
TransferImplicitOperands - MI is a pseudo-instruction, and the lowered replacement instructions immediately precede it.
Copy any implicit operands from MI to the replacement instruction.
Definition at line 61 of file ExpandPostRAPseudos.cpp.
References llvm::MachineInstr::allDefsAreDead(), assert(), llvm::MachineFunction::begin(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::dbgs(), llvm::MachineFunction::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::eraseFromParent(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getName(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isKill(), llvm::Register::isPhysicalRegister(), llvm::MachineInstr::isPseudo(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::AMDGPUISD::KILL, LLVM_DEBUG, llvm_unreachable, MI, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), TII, and TRI.