LLVM: lib/Support/FileOutputBuffer.cpp File Reference
FileOutputBuffer.cpp File Reference
#include "llvm/Support/FileOutputBuffer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Memory.h"
#include "llvm/Support/Path.h"
#include <system_error>
#include <unistd.h>
Functions
static Expected< std::unique_ptr< InMemoryBuffer > > createInMemoryBuffer (StringRef Path, size_t Size, unsigned Mode)
static Expected< std::unique_ptr< FileOutputBuffer > > createOnDiskBuffer (StringRef Path, size_t Size, unsigned Mode)
Function Documentation
createInMemoryBuffer()
static Expected<std::unique_ptr<InMemoryBuffer> > createInMemoryBuffer (StringRef Path, size_t Size, unsigned Mode) static
Definition at line 118 of file FileOutputBuffer.cpp.
References llvm::sys::Memory::allocateMappedMemory(), llvm::errorCodeToError(), llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, Mode, and Size.
Referenced by llvm::FileOutputBuffer::create(), and createOnDiskBuffer().
createOnDiskBuffer()
static Expected<std::unique_ptr<FileOutputBuffer> > createOnDiskBuffer (StringRef Path, size_t Size, unsigned Mode) static
Definition at line 128 of file FileOutputBuffer.cpp.
References llvm::consumeError(), llvm::sys::fs::convertFDToNativeFile(), llvm::sys::fs::TempFile::create(), createInMemoryBuffer(), llvm::sys::fs::TempFile::discard(), llvm::errorCodeToError(), llvm::sys::fs::TempFile::FD, File, llvm::sys::fs::mapped_file_region::readwrite, llvm::sys::fs::resize_file(), Size, and llvm::Expected< T >::takeError().
Referenced by llvm::FileOutputBuffer::create().