LLVM: lib/Transforms/Scalar/Float2Int.cpp File Reference
Float2Int.cpp File Reference
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Scalar/Float2Int.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include <deque>
#include <functional>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "float2int"
Functions
static CmpInst::Predicate mapFCmpPred (CmpInst::Predicate P)
static Instruction::BinaryOps mapBinOpcode (unsigned Opcode)
FunctionPass * llvm::createFloat2IntPass ()
Variables
static cl::opt< unsigned > MaxIntegerBW ("float2int-max-integer-bw", cl::init(64), cl::Hidden, cl::desc("Max integer bitwidth to consider in float2int" "(default=64)"))
The largest integer type worth dealing with.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "float2int"
Definition at line 16 of file Float2Int.cpp.
Function Documentation
mapBinOpcode()
static Instruction::BinaryOps mapBinOpcode (unsigned Opcode) static
Definition at line 112 of file Float2Int.cpp.
References llvm::MCID::Add, assert(), llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::APFloatBase::cmpEqual, llvm::APFloat::compare(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::dbgs(), llvm::dyn_cast(), E, llvm::SmallPtrSetImpl< PtrType >::end(), llvm::Instruction::eraseFromParent(), F(), Fail, llvm::ConstantInt::get(), llvm::ConstantRange::getBitWidth(), llvm::Type::getFltSemantics(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::ConstantRange::getLower(), llvm::APInt::getMinSignedBits(), llvm::Value::getName(), llvm::APInt::getNullValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::PPC::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::ConstantRange::getUpper(), llvm::Instruction::hasNoSignedZeros(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::APFloat::isFinite(), llvm::ConstantRange::isFullSet(), llvm::APFloat::isNegative(), llvm::DominatorTree::isReachableFromEntry(), llvm::ConstantRange::isSignWrappedSet(), llvm::APFloat::isZero(), IT, LLVM_DEBUG, llvm_unreachable, mapFCmpPred(), llvm::max(), MaxIntegerBW, MI, llvm::RISCVFenceField::O, llvm::User::operands(), llvm::APFloatBase::opOK, P, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::reverse(), llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloat::roundToIntegral(), llvm::APFloatBase::semanticsPrecision(), Size, llvm::ConstantRange::unionWith(), llvm::Value::users(), and VI.
mapFCmpPred()
static CmpInst::Predicate mapFCmpPred (CmpInst::Predicate P) static
Definition at line 85 of file Float2Int.cpp.
References llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, and llvm::CmpInst::ICMP_SLT.
Referenced by mapBinOpcode().
Variable Documentation
MaxIntegerBW
cl::opt<unsigned> MaxIntegerBW("float2int-max-integer-bw", cl::init(64), cl::Hidden, cl::desc("Max integer bitwidth to consider in float2int" "(default=64)")) static
The largest integer type worth dealing with.
Referenced by mapBinOpcode().