LLVM: lib/CodeGen/FuncletLayout.cpp File Reference
FuncletLayout.cpp File Reference
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "funclet-layout"
Functions
INITIALIZE_PASS (FuncletLayout, DEBUG_TYPE, "Contiguously Lay Out Funclets", false, false) bool FuncletLayout
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "funclet-layout"
Definition at line 20 of file FuncletLayout.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (FuncletLayout , DEBUG_TYPE , "Contiguously Lay Out Funclets" , false , false)
Definition at line 40 of file FuncletLayout.cpp.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::getEHScopeMembership(), X, and Y.