LLVM: lib/Target/AMDGPU/GCNILPSched.cpp File Reference
GCNILPSched.cpp File Reference
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/Support/Debug.h"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "machine-scheduler"
Functions
static unsigned CalcNodeSethiUllmanNumber (const SUnit *SU, std::vector< unsigned > &SUNumbers)
CalcNodeSethiUllmanNumber - Compute Sethi Ullman number.
static unsigned closestSucc (const SUnit *SU)
closestSucc - Returns the scheduled cycle of the successor which is closest to the current cycle.
static unsigned calcMaxScratches (const SUnit *SU)
calcMaxScratches - Returns an cost estimate of the worse case requirement for scratch registers, i.e.
static int BUCompareLatency (const SUnit *left, const SUnit *right)
std::vector< const SUnit * > llvm::makeGCNILPScheduler (ArrayRef< const SUnit *> BotRoots, const ScheduleDAG &DAG)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 18 of file GCNILPSched.cpp.
Function Documentation
BUCompareLatency()
static int BUCompareLatency (const SUnit * left, const SUnit * right) static
Definition at line 133 of file GCNILPSched.cpp.
References llvm::abs(), assert(), C, calcMaxScratches(), closestSucc(), llvm::dbgs(), DisableSchedCriticalPath, DisableSchedCycles, DisableSchedHeight, E, llvm::SUnit::getDepth(), llvm::SUnit::getHeight(), I, llvm::SUnit::Latency, LLVM_DEBUG, MaxReorderWindow, llvm::SUnit::NodeNum, llvm::SUnit::NodeQueueId, and llvm::SUnit::Preds.
calcMaxScratches()
static unsigned calcMaxScratches (const SUnit * SU) static
calcMaxScratches - Returns an cost estimate of the worse case requirement for scratch registers, i.e.
number of data dependencies.
Definition at line 122 of file GCNILPSched.cpp.
References llvm::SDep::isCtrl(), and llvm::SUnit::Preds.
Referenced by BUCompareLatency().
CalcNodeSethiUllmanNumber()
static unsigned CalcNodeSethiUllmanNumber (const SUnit * SU, std::vector< unsigned > & SUNumbers) static
CalcNodeSethiUllmanNumber - Compute Sethi Ullman number.
Smaller number is the higher priority.
Definition at line 59 of file GCNILPSched.cpp.
References assert(), llvm::SDep::getSUnit(), llvm::SDep::isCtrl(), llvm::SUnit::NodeNum, llvm::SUnit::NumPreds, llvm::SUnit::NumSuccs, and llvm::SUnit::Preds.
closestSucc()
static unsigned closestSucc (const SUnit * SU) static
closestSucc - Returns the scheduled cycle of the successor which is closest to the current cycle.
Definition at line 107 of file GCNILPSched.cpp.
References llvm::SUnit::getHeight(), llvm::SDep::getSUnit(), llvm::SDep::isCtrl(), and llvm::SUnit::Succs.
Referenced by BUCompareLatency().