LLVM: lib/Target/AMDGPU/GCNRegPressure.cpp File Reference
GCNRegPressure.cpp File Reference
#include "GCNRegPressure.h"
#include "AMDGPUSubtarget.h"
#include "SIRegisterInfo.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/LiveInterval.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterPressure.h"
#include "llvm/CodeGen/SlotIndexes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
Macros
#define DEBUG_TYPE "machine-scheduler"
Functions
static LaneBitmask getDefRegMask (const MachineOperand &MO, const MachineRegisterInfo &MRI)
static LaneBitmask getUsedRegMask (const MachineOperand &MO, const MachineRegisterInfo &MRI, const LiveIntervals &LIS)
static SmallVector< RegisterMaskPair, 8 > collectVirtualRegUses (const MachineInstr &MI, const LiveIntervals &LIS, const MachineRegisterInfo &MRI)
static LLVM_DUMP_METHOD void reportMismatch (const GCNRPTracker::LiveRegSet &LISLR, const GCNRPTracker::LiveRegSet &TrackedLR, const TargetRegisterInfo *TRI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 32 of file GCNRegPressure.cpp.
Function Documentation
collectVirtualRegUses()
static SmallVector<RegisterMaskPair, 8> collectVirtualRegUses (const MachineInstr & MI, const LiveIntervals & LIS, const MachineRegisterInfo & MRI) static
Definition at line 230 of file GCNRegPressure.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::find_if(), getUsedRegMask(), I, llvm::Register::isVirtualRegister(), llvm::MachineInstr::operands(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, and llvm::NVPTX::PTXCvtMode::RM.
Referenced by llvm::GCNUpwardRPTracker::recede().
getDefRegMask()
static LaneBitmask getDefRegMask (const MachineOperand & MO, const MachineRegisterInfo & MRI) static
Definition at line 198 of file GCNRegPressure.cpp.
References assert(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and llvm::Register::isVirtualRegister().
Referenced by llvm::GCNDownwardRPTracker::advanceToNext(), and llvm::GCNUpwardRPTracker::recede().
getUsedRegMask()
static LaneBitmask getUsedRegMask (const MachineOperand & MO, const MachineRegisterInfo & MRI, const LiveIntervals & LIS) static
Definition at line 210 of file GCNRegPressure.cpp.
References assert(), llvm::LiveIntervals::getInstructionIndex(), llvm::LaneBitmask::getLane(), llvm::getLiveLaneMask(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::Register::isVirtualRegister(), MRI, SI, and SubReg.
Referenced by collectVirtualRegUses().
reportMismatch()
static LLVM_DUMP_METHOD void reportMismatch (const GCNRPTracker::LiveRegSet & LISLR, const GCNRPTracker::LiveRegSet & TrackedLR, const TargetRegisterInfo * TRI) static
Definition at line 444 of file GCNRegPressure.cpp.
References llvm::dbgs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, P, llvm::PrintLaneMask(), and llvm::printReg().
Referenced by llvm::GCNUpwardRPTracker::isValid().