LLVM: lib/Support/GlobPattern.cpp File Reference
GlobPattern.cpp File Reference
#include "llvm/Support/GlobPattern.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
Functions
static bool hasWildcard (StringRef S)
static Expected< BitVector > expand (StringRef S, StringRef Original)
static Expected< BitVector > scan (StringRef &S, StringRef Original)
Function Documentation
expand()
static Expected<BitVector> expand (StringRef S, StringRef Original) static
Definition at line 27 of file GlobPattern.cpp.
References llvm::StringRef::size().
Referenced by llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::SetTheory::evaluate(), llvm::SCEVExpander::expandCodeFor(), getMFHiLoOpc(), llvm::ModuloScheduleExpander::ModuloScheduleExpander(), llvm::PeelingModuloScheduleExpander::PeelingModuloScheduleExpander(), PickMostRelevantLoop(), and llvm::SCEVExpander::setChainedPhi().
hasWildcard()
static bool hasWildcard (StringRef S) static
Definition at line 21 of file GlobPattern.cpp.
References llvm::StringRef::find_first_of(), and llvm::StringRef::npos.
Referenced by llvm::GlobPattern::create().
scan()
static Expected<BitVector> scan (StringRef & S, StringRef Original) static
Definition at line 67 of file GlobPattern.cpp.
References llvm::StringRef::substr().
Referenced by llvm::GlobPattern::create(), llvm::WinException::endFunclet(), llvm::CFLSteensAAResult::ensureCached(), findmust(), llvm::CFLAndersAAResult::invalidate(), llvm::CFLSteensAAResult::invalidate(), and pluscount().