LLVM: lib/Transforms/IPO/GlobalOpt.cpp File Reference
GlobalOpt.cpp File Reference
#include "llvm/Transforms/IPO/GlobalOpt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/CtorUtils.h"
#include "llvm/Transforms/Utils/Evaluator.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include "llvm/Transforms/Utils/Local.h"
#include <cassert>
#include <cstdint>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "globalopt"
Functions
STATISTIC (NumMarked, "Number of globals marked constant")
STATISTIC (NumUnnamed, "Number of globals marked unnamed_addr")
STATISTIC (NumSRA, "Number of aggregate globals broken into scalars")
STATISTIC (NumHeapSRA, "Number of heap objects SRA'd")
STATISTIC (NumSubstitute,"Number of globals with initializers stored into them")
STATISTIC (NumDeleted, "Number of globals deleted")
STATISTIC (NumGlobUses, "Number of global uses devirtualized")
STATISTIC (NumLocalized, "Number of globals localized")
STATISTIC (NumShrunkToBool, "Number of global vars shrunk to booleans")
STATISTIC (NumFastCallFns, "Number of functions converted to fastcc")
STATISTIC (NumCtorsEvaluated, "Number of static ctors evaluated")
STATISTIC (NumNestRemoved, "Number of nest attributes removed")
STATISTIC (NumAliasesResolved, "Number of global aliases resolved")
STATISTIC (NumAliasesRemoved, "Number of global aliases eliminated")
STATISTIC (NumCXXDtorsRemoved, "Number of global C++ destructors removed")
STATISTIC (NumInternalFunc, "Number of internal functions")
STATISTIC (NumColdCC, "Number of functions marked coldcc")
static bool isLeakCheckerRoot (GlobalVariable *GV)
Is this global variable possibly used by a leak checker as a root? If so, we might not really want to eliminate the stores to it.
static bool IsSafeComputationToRemove (Value *V, function_ref< TargetLibraryInfo &(Function &)> GetTLI)
Given a value that is stored to a global but never read, determine whether it's safe to remove the store and the chain of computation that feeds the store.
static bool CleanupPointerRootUsers (GlobalVariable *GV, function_ref< TargetLibraryInfo &(Function &)> GetTLI)
This GV is a pointer root.
static bool CleanupConstantGlobalUsers (Value *V, Constant *Init, const DataLayout &DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI)
We just marked GV constant.
static bool isSafeSROAElementUse (Value *V)
Return true if the specified instruction is a safe user of a derived expression from a global that we want to SROA.
static bool isSafeSROAGEP (User *U)
Return true if the specified GEP is a safe user of a derived expression from a global that we want to SROA.
static bool GlobalUsersSafeToSRA (GlobalValue *GV)
Look at all uses of the global and decide whether it is safe for us to perform this transformation.
static bool CanDoGlobalSRA (GlobalVariable *GV)
static void transferSRADebugInfo (GlobalVariable *GV, GlobalVariable *NGV, uint64_t FragmentOffsetInBits, uint64_t FragmentSizeInBits, unsigned NumElements)
Copy over the debug info for a variable to its SRA replacements.
static GlobalVariable * SRAGlobal (GlobalVariable *GV, const DataLayout &DL)
Perform scalar replacement of aggregates on the specified global variable.
static bool AllUsesOfValueWillTrapIfNull (const Value *V, SmallPtrSetImpl< const PHINode *> &PHIs)
Return true if all users of the specified value will trap if the value is dynamically null.
static bool AllUsesOfLoadedValueWillTrapIfNull (const GlobalVariable *GV)
Return true if all uses of any loads from GV will trap if the loaded value is null.
static bool OptimizeAwayTrappingUsesOfValue (Value *V, Constant *NewV)
static bool OptimizeAwayTrappingUsesOfLoads (GlobalVariable *GV, Constant *LV, const DataLayout &DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI)
The specified global has only one non-null value stored into it.
static void ConstantPropUsersOf (Value *V, const DataLayout &DL, TargetLibraryInfo *TLI)
Walk the use list of V, constant folding all of the instructions that are foldable.
static GlobalVariable * OptimizeGlobalAddressOfMalloc (GlobalVariable *GV, CallInst *CI, Type *AllocTy, ConstantInt *NElements, const DataLayout &DL, TargetLibraryInfo *TLI)
This function takes the specified global variable, and transforms the program as if it always contained the result of the specified malloc.
static bool ValueIsOnlyUsedLocallyOrStoredToOneGlobal (const Instruction *V, const GlobalVariable *GV, SmallPtrSetImpl< const PHINode *> &PHIs)
Scan the use-list of V checking to make sure that there are no complex uses of V.
static void ReplaceUsesOfMallocWithGlobal (Instruction *Alloc, GlobalVariable *GV)
The Alloc pointer is stored into GV somewhere.
static bool LoadUsesSimpleEnoughForHeapSRA (const Value *V, SmallPtrSetImpl< const PHINode *> &LoadUsingPHIs, SmallPtrSetImpl< const PHINode *> &LoadUsingPHIsPerLoad)
Verify that all uses of V (a load, or a phi of a load) are simple enough to perform heap SRA on.
static bool AllGlobalLoadUsesSimpleEnoughForHeapSRA (const GlobalVariable *GV, Instruction *StoredVal)
If all users of values loaded from GV are simple enough to perform HeapSRA, return true.
static Value * GetHeapSROAValue (Value *V, unsigned FieldNo, DenseMap< Value *, std::vector< Value *>> &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned >> &PHIsToRewrite)
static void RewriteHeapSROALoadUser (Instruction *LoadUser, DenseMap< Value *, std::vector< Value *>> &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned >> &PHIsToRewrite)
Given a load instruction and a value derived from the load, rewrite the derived value to use the HeapSRoA'd load.
static void RewriteUsesOfLoadForHeapSRoA (LoadInst *Load, DenseMap< Value *, std::vector< Value *>> &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > &PHIsToRewrite)
We are performing Heap SRoA on a global.
static GlobalVariable * PerformHeapAllocSRoA (GlobalVariable *GV, CallInst *CI, Value *NElems, const DataLayout &DL, const TargetLibraryInfo *TLI)
CI is an allocation of an array of structures.
static bool tryToOptimizeStoreOfMallocToGlobal (GlobalVariable *GV, CallInst *CI, Type *AllocTy, AtomicOrdering Ordering, const DataLayout &DL, TargetLibraryInfo *TLI)
This function is called when we see a pointer global variable with a single value stored it that is a malloc or cast of malloc.
static bool optimizeOnceStoredGlobal (GlobalVariable *GV, Value *StoredOnceVal, AtomicOrdering Ordering, const DataLayout &DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI)
static bool TryToShrinkGlobalToBoolean (GlobalVariable *GV, Constant *OtherVal)
At this point, we have learned that the only two values ever stored into GV are its initializer and OtherVal.
static bool deleteIfDead (GlobalValue &GV, SmallPtrSetImpl< const Comdat *> &NotDiscardableComdats)
static bool isPointerValueDeadOnEntryToFunction (const Function *F, GlobalValue *GV, function_ref< DominatorTree &(Function &)> LookupDomTree)
static bool allNonInstructionUsersCanBeMadeInstructions (Constant *C)
C may have non-instruction users.
static void makeAllConstantUsesInstructions (Constant *C)
C may have non-instruction users, and allNonInstructionUsersCanBeMadeInstructions has returned true.
static bool processInternalGlobal (GlobalVariable *GV, const GlobalStatus &GS, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< DominatorTree &(Function &)> LookupDomTree)
Analyze the specified global variable and optimize it if possible.
static bool processGlobal (GlobalValue &GV, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< DominatorTree &(Function &)> LookupDomTree)
Analyze the specified global variable and optimize it if possible.
static void ChangeCalleesToFastCall (Function *F)
Walk all of the direct calls of the specified function, changing them to FastCC.
static AttributeList StripAttr (LLVMContext &C, AttributeList Attrs, Attribute::AttrKind A)
static void RemoveAttribute (Function *F, Attribute::AttrKind A)
static bool hasChangeableCC (Function *F)
Return true if this is a calling convention that we'd like to change.
static bool isColdCallSite (CallSite CS, BlockFrequencyInfo &CallerBFI)
Return true if the block containing the call site has a BlockFrequency of less than ColdCCRelFreq% of the entry block.
static bool isValidCandidateForColdCC (Function &F, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, const std::vector< Function *> &AllCallsCold)
static void changeCallSitesToColdCC (Function *F)
static bool hasOnlyColdCalls (Function &F, function_ref< BlockFrequencyInfo &(Function &)> GetBFI)
static bool OptimizeFunctions (Module &M, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< TargetTransformInfo &(Function &)> GetTTI, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< DominatorTree &(Function &)> LookupDomTree, SmallPtrSetImpl< const Comdat *> &NotDiscardableComdats)
static bool OptimizeGlobalVars (Module &M, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< DominatorTree &(Function &)> LookupDomTree, SmallPtrSetImpl< const Comdat *> &NotDiscardableComdats)
static Constant * EvaluateStoreInto (Constant *Init, Constant *Val, ConstantExpr *Addr, unsigned OpNo)
Evaluate a piece of a constantexpr store into a global initializer.
static void CommitValueTo (Constant *Val, Constant *Addr)
We have decided that Addr (which satisfies the predicate isSimpleEnoughPointerToCommit) should get Val as its value.
static void BatchCommitValueTo (const DenseMap< Constant *, Constant *> &Mem)
Given a map of address -> value, where addresses are expected to be some form of either a global or a constant GEP, set the initializer for the address to be the value.
static bool EvaluateStaticConstructor (Function *F, const DataLayout &DL, TargetLibraryInfo *TLI)
Evaluate static constructors in the function, if we can.
static int compareNames (Constant *const *A, Constant *const *B)
static void setUsedInitializer (GlobalVariable &V, const SmallPtrSetImpl< GlobalValue *> &Init)
static bool hasUseOtherThanLLVMUsed (GlobalAlias &GA, const LLVMUsed &U)
static bool hasMoreThanOneUseOtherThanLLVMUsed (GlobalValue &V, const LLVMUsed &U)
static bool mayHaveOtherReferences (GlobalAlias &GA, const LLVMUsed &U)
static bool hasUsesToReplace (GlobalAlias &GA, const LLVMUsed &U, bool &RenameTarget)
static bool OptimizeGlobalAliases (Module &M, SmallPtrSetImpl< const Comdat *> &NotDiscardableComdats)
static Function * FindCXAAtExit (Module &M, function_ref< TargetLibraryInfo &(Function &)> GetTLI)
static bool cxxDtorIsEmpty (const Function &Fn)
Returns whether the given function is an empty C++ destructor and can therefore be eliminated.
static bool OptimizeEmptyGlobalCXXDtors (Function *CXAAtExitFn)
static bool optimizeGlobalsInModule (Module &M, const DataLayout &DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< TargetTransformInfo &(Function &)> GetTTI, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< DominatorTree &(Function &)> LookupDomTree)
INITIALIZE_PASS_BEGIN (GlobalOptLegacyPass, "globalopt", "Global Variable Optimizer", false, false) INITIALIZE_PASS_END(GlobalOptLegacyPass
Variables
static cl::opt< bool > EnableColdCCStressTest ("enable-coldcc-stress-test", cl::desc("Enable stress test of coldcc by adding " "calling conv to all internal functions."), cl::init(false), cl::Hidden)
static cl::opt< int > ColdCCRelFreq ("coldcc-rel-freq", cl::Hidden, cl::init(2), cl::ZeroOrMore, cl::desc("Maximum block frequency, expressed as a percentage of caller's " "entry frequency, for a call site to be considered cold for enabling" "coldcc"))
globalopt
Global Variable Optimizer
Global Variable false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "globalopt"
Definition at line 76 of file GlobalOpt.cpp.
Function Documentation
AllGlobalLoadUsesSimpleEnoughForHeapSRA()
static bool AllGlobalLoadUsesSimpleEnoughForHeapSRA (const GlobalVariable * GV, Instruction * StoredVal) static
If all users of values loaded from GV are simple enough to perform HeapSRA, return true.
Definition at line 1120 of file GlobalOpt.cpp.
References llvm::SmallPtrSetImplBase::clear(), llvm::numbers::e, LoadUsesSimpleEnoughForHeapSRA(), op, and llvm::Value::users().
Referenced by tryToOptimizeStoreOfMallocToGlobal().
allNonInstructionUsersCanBeMadeInstructions()
static bool allNonInstructionUsersCanBeMadeInstructions (Constant * C) static
C may have non-instruction users.
Can all of those users be turned into instructions?
Definition at line 1877 of file GlobalOpt.cpp.
References llvm::Value::users().
Referenced by processInternalGlobal().
AllUsesOfLoadedValueWillTrapIfNull()
static bool AllUsesOfLoadedValueWillTrapIfNull (const GlobalVariable * GV) static
Return true if all uses of any loads from GV will trap if the loaded value is null.
Note that this also permits comparisons of the loaded value against null, as a special case.
Definition at line 676 of file GlobalOpt.cpp.
References AllUsesOfValueWillTrapIfNull(), and llvm::Value::users().
Referenced by tryToOptimizeStoreOfMallocToGlobal().
AllUsesOfValueWillTrapIfNull()
static bool AllUsesOfValueWillTrapIfNull (const Value * V, SmallPtrSetImpl< const PHINode *> & PHIs) static
Return true if all users of the specified value will trap if the value is dynamically null.
PHIs keeps track of any phi nodes we've seen to avoid reprocessing them.
Definition at line 627 of file GlobalOpt.cpp.
References I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::NullPointerIsDefined(), SI, and llvm::Value::users().
Referenced by AllUsesOfLoadedValueWillTrapIfNull().
BatchCommitValueTo()
static void BatchCommitValueTo (const DenseMap< Constant *, Constant *> & Mem) static
Given a map of address -> value, where addresses are expected to be some form of either a global or a constant GEP, set the initializer for the address to be the value.
This performs mostly the same function as CommitValueTo() and EvaluateStoreInto() but is optimized to be more efficient for the common case where the set of addresses are GEPs sharing the same underlying global, processing the GEPs in batches rather than individually.
To give an example, consider the following C++ code adapted from the clang regression tests: struct S { int n = 10; int m = 2 * n; S(int a) : n(a) {} };
template<typename T> struct U { T *r = T q = 42; U *p = this; };
U<S> e;
The global static constructor for 'e' will need to initialize 'r' and 'p' of the outer struct, while also initializing the inner 'q' structs 'n' and 'm' members. This batch algorithm will simply use general CommitValueTo() method to handle the complex nested S struct initialization of 'q', before processing the outermost members in a single batch. Using CommitValueTo() to handle member in the outer struct is inefficient when the struct/array is very large as we end up creating and destroy constant arrays for each initialization. For the above case, we expect the following IR to be generated:
struct.U = type { struct.S*, struct.S, struct.U* } struct.S = type { i32, i32 } = global struct.U { struct.S* gep inbounds (struct.U, struct.U* , i64 0, i32 1), struct.S { i32 42, i32 84 }, struct.U* } The struct.S { i32 42, i32 84 } inner initializer is treated as a complex constant expression, while the other two elements of are "simple".
Definition at line 2501 of file GlobalOpt.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), CommitValueTo(), llvm::numbers::e, llvm::SmallVectorBase::empty(), GEP, llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::Constant::getAggregateElement(), llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), I, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::GlobalVariable::setInitializer(), llvm::SmallVectorBase::size(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by EvaluateStaticConstructor().
CanDoGlobalSRA()
static bool CanDoGlobalSRA (GlobalVariable * GV) static
Definition at line 436 of file GlobalOpt.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::Value::getType(), GlobalUsersSafeToSRA(), and llvm::Value::hasNUsesOrMore().
Referenced by SRAGlobal().
ChangeCalleesToFastCall()
static void ChangeCalleesToFastCall (Function * F) static
Walk all of the direct calls of the specified function, changing them to FastCC.
Definition at line 2116 of file GlobalOpt.cpp.
References llvm::CallingConv::Fast, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setCallingConv(), and llvm::Value::users().
Referenced by OptimizeFunctions().
changeCallSitesToColdCC()
static void changeCallSitesToColdCC (Function * F) static
Definition at line 2215 of file GlobalOpt.cpp.
References llvm::CallingConv::Cold, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setCallingConv(), and llvm::Value::users().
Referenced by OptimizeFunctions().
CleanupConstantGlobalUsers()
static bool CleanupConstantGlobalUsers (Value * V, Constant * Init, const DataLayout & DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI) static
We just marked GV constant.
Loop over all users of the global, cleaning up the obvious ones. This is largely just a quick scan over the use list to clean up the easy and obvious cruft. This returns true if it made a change.
Definition at line 276 of file GlobalOpt.cpp.
References C, llvm::ConstantFoldInstruction(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), GEP, llvm::Constant::getNullValue(), llvm::ConstantExpr::getOpcode(), isSafeSROAElementUse(), llvm::isSafeToDestroyConstant(), MI, llvm::Value::replaceAllUsesWith(), SI, llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by OptimizeAwayTrappingUsesOfLoads(), and processInternalGlobal().
CleanupPointerRootUsers()
static bool CleanupPointerRootUsers (GlobalVariable * GV, function_ref< TargetLibraryInfo &(Function &)> GetTLI) static
This GV is a pointer root.
Loop over all users of the global and clean up any that obviously don't assign the global a value that isn't dynamically allocated.
Definition at line 190 of file GlobalOpt.cpp.
References C, llvm::SmallVectorImpl< T >::clear(), llvm::RegState::Dead, llvm::dyn_cast(), llvm::numbers::e, E, llvm::Instruction::eraseFromParent(), first, llvm::User::getOperand(), I, llvm::isAllocationFn(), llvm::GlobalVariable::isConstant(), IsSafeComputationToRemove(), llvm::isSafeToDestroyConstant(), llvm::SmallVectorTemplateBase< T >::push_back(), SI, llvm::SmallVectorBase::size(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by OptimizeAwayTrappingUsesOfLoads(), and processInternalGlobal().
CommitValueTo()
static void CommitValueTo (Constant * Val, Constant * Addr) static
We have decided that Addr (which satisfies the predicate isSimpleEnoughPointerToCommit) should get Val as its value.
Make it happen.
Definition at line 2448 of file GlobalOpt.cpp.
References assert(), EvaluateStoreInto(), and llvm::User::getOperand().
Referenced by BatchCommitValueTo().
compareNames()
static int compareNames (Constant *const * A, Constant *const * B) static
Definition at line 2610 of file GlobalOpt.cpp.
References llvm::StringRef::compare(), llvm::Value::getName(), and llvm::Value::stripPointerCasts().
Referenced by setUsedInitializer().
ConstantPropUsersOf()
static void ConstantPropUsersOf (Value * V, const DataLayout & DL, TargetLibraryInfo * TLI) static
Walk the use list of V, constant folding all of the instructions that are foldable.
Definition at line 828 of file GlobalOpt.cpp.
References llvm::ConstantFoldInstruction(), E, I, llvm::isInstructionTriviallyDead(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by OptimizeGlobalAddressOfMalloc().
cxxDtorIsEmpty()
static bool cxxDtorIsEmpty (const Function & Fn) static
Returns whether the given function is an empty C++ destructor and can therefore be eliminated.
Note that we assume that other optimization passes have already simplified the code so we simply check for 'ret'.
Definition at line 2869 of file GlobalOpt.cpp.
References llvm::Function::getEntryBlock(), I, and llvm::GlobalValue::isDeclaration().
Referenced by OptimizeEmptyGlobalCXXDtors().
deleteIfDead()
static bool deleteIfDead (GlobalValue & GV, SmallPtrSetImpl< const Comdat *> & NotDiscardableComdats) static
Definition at line 1773 of file GlobalOpt.cpp.
References C, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::RegState::Dead, llvm::GlobalValue::eraseFromParent(), F(), llvm::GlobalValue::getComdat(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::isDeclaration(), llvm::GlobalValue::isDiscardableIfUnused(), LLVM_DEBUG, llvm::Constant::removeDeadConstantUsers(), and llvm::Value::use_empty().
Referenced by OptimizeFunctions(), OptimizeGlobalAliases(), and OptimizeGlobalVars().
EvaluateStaticConstructor()
static bool EvaluateStaticConstructor (Function * F, const DataLayout & DL, TargetLibraryInfo * TLI) static
Evaluate static constructors in the function, if we can.
Return true if we can, false otherwise.
Definition at line 2587 of file GlobalOpt.cpp.
References BatchCommitValueTo(), llvm::dbgs(), llvm::Evaluator::EvaluateFunction(), llvm::Evaluator::getInvariants(), llvm::Evaluator::getMutatedMemory(), llvm::Value::getName(), and LLVM_DEBUG.
Referenced by optimizeGlobalsInModule().
EvaluateStoreInto()
static Constant* EvaluateStoreInto (Constant * Init, Constant * Val, ConstantExpr * Addr, unsigned OpNo) static
Evaluate a piece of a constantexpr store into a global initializer.
This returns 'Init' modified to reflect 'Val' stored into it. At this point, the GEP operands of Addr [0, OpNo) have been stepped into.
Definition at line 2405 of file GlobalOpt.cpp.
References assert(), llvm::numbers::e, llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::Constant::getAggregateElement(), llvm::SequentialType::getNumElements(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::Type::isArrayTy(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by CommitValueTo().
FindCXAAtExit()
static Function* FindCXAAtExit (Module & M, function_ref< TargetLibraryInfo &(Function &)> GetTLI) static
Definition at line 2840 of file GlobalOpt.cpp.
References llvm::Module::begin(), llvm::Module::end(), and llvm::Module::getFunction().
Referenced by optimizeGlobalsInModule().
GetHeapSROAValue()
static Value* GetHeapSROAValue (Value * V, unsigned FieldNo, DenseMap< Value *, std::vector< Value *>> & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned >> & PHIsToRewrite) static
Definition at line 1166 of file GlobalOpt.cpp.
References llvm::PHINode::Create(), llvm::PointerType::get(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::Type::getPointerElementType(), llvm::Value::getType(), and llvm::ARM_MB::ST.
Referenced by RewriteHeapSROALoadUser().
GlobalUsersSafeToSRA()
static bool GlobalUsersSafeToSRA (GlobalValue * GV) static
Look at all uses of the global and decide whether it is safe for us to perform this transformation.
Definition at line 420 of file GlobalOpt.cpp.
References isSafeSROAGEP(), and llvm::Value::users().
Referenced by CanDoGlobalSRA().
hasChangeableCC()
static bool hasChangeableCC (Function * F) static
Return true if this is a calling convention that we'd like to change.
The idea here is that we don't want to mess with the convention if the user explicitly requested something with performance implications like coldcc, GHC, or anyregcc.
Definition at line 2147 of file GlobalOpt.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::Function::getCallingConv(), llvm::CallInst::isMustTailCall(), llvm::Value::users(), and llvm::CallingConv::X86_ThisCall.
Referenced by hasOnlyColdCalls(), and OptimizeFunctions().
hasMoreThanOneUseOtherThanLLVMUsed()
static bool hasMoreThanOneUseOtherThanLLVMUsed (GlobalValue & V, const LLVMUsed & U) static
Definition at line 2718 of file GlobalOpt.cpp.
References assert(), llvm::Value::hasNUsesOrMore(), and N.
Referenced by hasUsesToReplace().
hasOnlyColdCalls()
static bool hasOnlyColdCalls (Function & F, function_ref< BlockFrequencyInfo &(Function &)> GetBFI) static
Definition at line 2228 of file GlobalOpt.cpp.
References llvm::Function::getIntrinsicID(), llvm::Function::hasAddressTaken(), hasChangeableCC(), llvm::GlobalValue::hasLocalLinkage(), I, isColdCallSite(), llvm::Function::isVarArg(), and llvm::Intrinsic::not_intrinsic.
Referenced by OptimizeFunctions().
hasUseOtherThanLLVMUsed()
static bool hasUseOtherThanLLVMUsed (GlobalAlias & GA, const LLVMUsed & U) static
Definition at line 2702 of file GlobalOpt.cpp.
References assert(), llvm::Value::hasOneUse(), and llvm::Value::use_empty().
Referenced by hasUsesToReplace().
hasUsesToReplace()
static bool hasUsesToReplace (GlobalAlias & GA, const LLVMUsed & U, bool & RenameTarget) static
Definition at line 2736 of file GlobalOpt.cpp.
References llvm::GlobalAlias::getAliasee(), llvm::GlobalValue::hasLocalLinkage(), hasMoreThanOneUseOtherThanLLVMUsed(), hasUseOtherThanLLVMUsed(), mayHaveOtherReferences(), llvm::MipsISD::Ret, and llvm::Constant::stripPointerCasts().
Referenced by OptimizeGlobalAliases().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (GlobalOptLegacyPass , "globalopt" , "Global Variable Optimizer" , false , false)
Referenced by llvm::GlobalOptPass::run().
isColdCallSite()
static bool isColdCallSite (CallSite CS, BlockFrequencyInfo & CallerBFI) static
Return true if the block containing the call site has a BlockFrequency of less than ColdCCRelFreq% of the entry block.
Definition at line 2178 of file GlobalOpt.cpp.
References ColdCCRelFreq, llvm::BlockFrequencyInfo::getBlockFreq(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCaller(), llvm::Function::getEntryBlock(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), and llvm::Instruction::getParent().
Referenced by hasOnlyColdCalls(), and isValidCandidateForColdCC().
isLeakCheckerRoot()
static bool isLeakCheckerRoot (GlobalVariable * GV) static
Is this global variable possibly used by a leak checker as a root? If so, we might not really want to eliminate the stores to it.
Definition at line 111 of file GlobalOpt.cpp.
References llvm::Type::ArrayTyID, E, llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::SmallVectorBase::empty(), llvm::SequentialType::getElementType(), llvm::Type::getTypeID(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::hasPrivateLinkage(), I, llvm::StructType::isOpaque(), llvm::Type::PointerTyID, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Type::StructTyID, and llvm::Type::VectorTyID.
Referenced by OptimizeAwayTrappingUsesOfLoads(), and processInternalGlobal().
isPointerValueDeadOnEntryToFunction()
static bool isPointerValueDeadOnEntryToFunction (const Function * F, GlobalValue * GV, function_ref< DominatorTree &(Function &)> LookupDomTree) static
Definition at line 1798 of file GlobalOpt.cpp.
References assert(), llvm::dyn_cast(), F(), llvm::Module::getDataLayout(), llvm::Operator::getOpcode(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::DataLayout::getTypeStoreSize(), llvm::StoreInst::getValueOperand(), I, llvm::none_of(), llvm::SmallVectorTemplateBase< T >::push_back(), SI, llvm::SmallVectorBase::size(), Threshold, and llvm::Value::users().
Referenced by processInternalGlobal().
IsSafeComputationToRemove()
static bool IsSafeComputationToRemove (Value * V, function_ref< TargetLibraryInfo &(Function &)> GetTLI) static
Given a value that is stored to a global but never read, determine whether it's safe to remove the store and the chain of computation that feeds the store.
Definition at line 159 of file GlobalOpt.cpp.
References GEP, llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::hasOneUse(), I, llvm::isAllocationFn(), and llvm::Instruction::mayHaveSideEffects().
Referenced by CleanupPointerRootUsers().
isSafeSROAElementUse()
static bool isSafeSROAElementUse (Value * V) static
Return true if the specified instruction is a safe user of a derived expression from a global that we want to SROA.
Definition at line 399 of file GlobalOpt.cpp.
References C, llvm::dyn_cast(), I, isSafeSROAGEP(), llvm::isSafeToDestroyConstant(), and SI.
Referenced by CleanupConstantGlobalUsers(), and isSafeSROAGEP().
isSafeSROAGEP()
static bool isSafeSROAGEP (User * U) static
Return true if the specified GEP is a safe user of a derived expression from a global that we want to SROA.
Definition at line 366 of file GlobalOpt.cpp.
References llvm::all_of(), llvm::dyn_cast(), E, llvm::gep_type_begin(), llvm::gep_type_end(), llvm::User::getNumOperands(), llvm::generic_gep_type_iterator< ItTy >::getOperand(), llvm::User::getOperand(), llvm::generic_gep_type_iterator< ItTy >::getSequentialNumElements(), llvm::ConstantInt::getZExtValue(), llvm::generic_gep_type_iterator< ItTy >::isBoundedSequential(), isSafeSROAElementUse(), llvm::generic_gep_type_iterator< ItTy >::isStruct(), and llvm::Value::users().
Referenced by GlobalUsersSafeToSRA(), and isSafeSROAElementUse().
isValidCandidateForColdCC()
static bool isValidCandidateForColdCC (Function & F, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, const std::vector< Function *> & AllCallsCold) static
Definition at line 2192 of file GlobalOpt.cpp.
References llvm::find(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), isColdCallSite(), llvm::Value::user_empty(), and llvm::Value::users().
Referenced by OptimizeFunctions().
LoadUsesSimpleEnoughForHeapSRA()
static bool LoadUsesSimpleEnoughForHeapSRA (const Value * V, SmallPtrSetImpl< const PHINode *> & LoadUsingPHIs, SmallPtrSetImpl< const PHINode *> & LoadUsingPHIsPerLoad) static
Verify that all uses of V (a load, or a phi of a load) are simple enough to perform heap SRA on.
This permits GEP's that index through the array and struct field, icmps of null, and PHIs.
Definition at line 1069 of file GlobalOpt.cpp.
References llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::Value::users().
Referenced by AllGlobalLoadUsesSimpleEnoughForHeapSRA().
makeAllConstantUsesInstructions()
static void makeAllConstantUsesInstructions (Constant * C) static
C may have non-instruction users, and allNonInstructionUsersCanBeMadeInstructions has returned true.
Convert the non-instruction users to instructions.
Definition at line 1903 of file GlobalOpt.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::Instruction::insertBefore(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::User::replaceUsesOfWith(), Users, and llvm::Value::users().
Referenced by processInternalGlobal().
mayHaveOtherReferences()
static bool mayHaveOtherReferences (GlobalAlias & GA, const LLVMUsed & U) static
Definition at line 2729 of file GlobalOpt.cpp.
References llvm::GlobalValue::hasLocalLinkage().
Referenced by hasUsesToReplace(), and OptimizeGlobalAliases().
OptimizeAwayTrappingUsesOfLoads()
static bool OptimizeAwayTrappingUsesOfLoads (GlobalVariable * GV, Constant * LV, const DataLayout & DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI) static
The specified global has only one non-null value stored into it.
If there are uses of the loaded value that would trap if the loaded value is dynamically null, then we know that they cannot be reachable with a null optimize away the load.
Definition at line 763 of file GlobalOpt.cpp.
References assert(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::dbgs(), E, llvm::GlobalVariable::eraseFromParent(), llvm::User::getOperand(), isLeakCheckerRoot(), LLVM_DEBUG, OptimizeAwayTrappingUsesOfValue(), llvm::Value::use_empty(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by optimizeOnceStoredGlobal().
OptimizeAwayTrappingUsesOfValue()
static bool OptimizeAwayTrappingUsesOfValue (Value * V, Constant * NewV) static
Definition at line 692 of file GlobalOpt.cpp.
References llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_size(), C, llvm::numbers::e, E, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgument(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledValue(), llvm::ConstantExpr::getCast(), llvm::Instruction::getFunction(), llvm::ConstantExpr::getGetElementPtr(), llvm::Value::getType(), I, llvm::NullPointerIsDefined(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setArgument(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setCalledFunction(), SI, llvm::SmallVectorBase::size(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by OptimizeAwayTrappingUsesOfLoads().
OptimizeEmptyGlobalCXXDtors()
static bool OptimizeEmptyGlobalCXXDtors (Function * CXAAtExitFn) static
Itanium C++ ABI p3.3.5:
After constructing a global (or local static) object, that will require destruction on exit, a termination function is registered as follows:
extern "C" int __cxa_atexit (void (*f)(void *), void *p, void *d);
This registration, e.g. __cxa_atexit(f,p,d), is intended to cause the call f(p) when DSO d is unloaded, before all such termination calls registered before this one. It returns zero if registration is successful, nonzero on failure.
Definition at line 2885 of file GlobalOpt.cpp.
References cxxDtorIsEmpty(), llvm::dyn_cast(), E, llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), I, llvm::Value::replaceAllUsesWith(), llvm::Value::stripPointerCasts(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by optimizeGlobalsInModule().
OptimizeFunctions()
static bool OptimizeFunctions (Module & M, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< TargetTransformInfo &(Function &)> GetTTI, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< DominatorTree &(Function &)> LookupDomTree, SmallPtrSetImpl< const Comdat *> & NotDiscardableComdats) static
Definition at line 2259 of file GlobalOpt.cpp.
References llvm::Module::begin(), ChangeCalleesToFastCall(), changeCallSitesToColdCC(), llvm::CallingConv::Cold, deleteIfDead(), E, EnableColdCCStressTest, llvm::Module::end(), llvm::CallingConv::Fast, llvm::Function::getAttributes(), llvm::Function::hasAddressTaken(), llvm::AttributeList::hasAttrSomewhere(), hasChangeableCC(), llvm::Function::hasFnAttribute(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), hasOnlyColdCalls(), llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::isDeclaration(), isValidCandidateForColdCC(), llvm::Function::isVarArg(), processGlobal(), RemoveAttribute(), llvm::removeUnreachableBlocks(), llvm::Function::setCallingConv(), llvm::GlobalValue::setLinkage(), and llvm::TargetTransformInfo::useColdCCForColdCall().
Referenced by optimizeGlobalsInModule().
OptimizeGlobalAddressOfMalloc()
static GlobalVariable* OptimizeGlobalAddressOfMalloc (GlobalVariable * GV, CallInst * CI, Type * AllocTy, ConstantInt * NElements, const DataLayout & DL, TargetLibraryInfo * TLI) static
This function takes the specified global variable, and transforms the program as if it always contained the result of the specified malloc.
Because it is always the result of the specified malloc, there is no reason to actually DO the malloc. Instead, turn the malloc into a global, and any loads of GV as uses of the new global.
Definition at line 850 of file GlobalOpt.cpp.
References ConstantPropUsersOf(), llvm::BinaryOperator::CreateNot(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::errs(), llvm::ArrayType::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::ConstantInt::getFalse(), llvm::Module::getGlobalList(), llvm::Type::getInt1Ty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::LoadInst::getOrdering(), llvm::GlobalValue::getParent(), llvm::CmpInst::getPredicate(), llvm::LoadInst::getSyncScopeID(), llvm::GlobalValue::getThreadLocalMode(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::Use::getUser(), llvm::GlobalValue::getValueType(), llvm::ConstantInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::GlobalValue::InternalLinkage, llvm::LoadInst::isUnordered(), LLVM_DEBUG, llvm_unreachable, llvm::None, llvm::Value::replaceAllUsesWith(), llvm::User::replaceUsesOfWith(), SI, llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Instruction::user_back(), and llvm::Value::user_back().
Referenced by tryToOptimizeStoreOfMallocToGlobal().
OptimizeGlobalAliases()
static bool OptimizeGlobalAliases (Module & M, SmallPtrSetImpl< const Comdat *> & NotDiscardableComdats) static
Definition at line 2769 of file GlobalOpt.cpp.
References llvm::Module::alias_begin(), llvm::Module::alias_end(), deleteIfDead(), llvm::dyn_cast(), E, llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::GlobalAlias::getAliasee(), llvm::Module::getAliasList(), llvm::ConstantExpr::getBitCast(), llvm::GlobalValue::getDLLStorageClass(), llvm::GlobalValue::getLinkage(), llvm::GlobalValue::getType(), llvm::GlobalValue::getVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), hasUsesToReplace(), I, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::isDeclaration(), llvm::GlobalValue::isDSOLocal(), llvm::GlobalValue::isInterposable(), mayHaveOtherReferences(), llvm::Constant::removeDeadConstantUsers(), llvm::Value::replaceAllUsesWith(), llvm::GlobalValue::setDLLStorageClass(), llvm::GlobalValue::setDSOLocal(), llvm::GlobalValue::setLinkage(), llvm::GlobalValue::setVisibility(), llvm::Constant::stripPointerCasts(), and llvm::Value::takeName().
Referenced by optimizeGlobalsInModule().
optimizeGlobalsInModule()
static bool optimizeGlobalsInModule (Module & M, const DataLayout & DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< TargetTransformInfo &(Function &)> GetTTI, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< DominatorTree &(Function &)> LookupDomTree) static
Definition at line 2928 of file GlobalOpt.cpp.
References C, llvm::SmallPtrSetImplBase::clear(), EvaluateStaticConstructor(), FindCXAAtExit(), llvm::GlobalObject::getComdat(), llvm::GlobalValue::getComdat(), llvm::Module::globals(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Function::isDefTriviallyDead(), llvm::GlobalValue::isDiscardableIfUnused(), OptimizeEmptyGlobalCXXDtors(), OptimizeFunctions(), OptimizeGlobalAliases(), llvm::optimizeGlobalCtorsList(), OptimizeGlobalVars(), and llvm::Value::use_empty().
Referenced by llvm::GlobalOptPass::run().
OptimizeGlobalVars()
static bool OptimizeGlobalVars (Module & M, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< DominatorTree &(Function &)> LookupDomTree, SmallPtrSetImpl< const Comdat *> & NotDiscardableComdats) static
Definition at line 2368 of file GlobalOpt.cpp.
References C, llvm::ConstantFoldConstant(), deleteIfDead(), E, llvm::Module::getDataLayout(), llvm::GlobalVariable::getInitializer(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::isDeclaration(), processGlobal(), llvm::GlobalVariable::setInitializer(), and llvm::GlobalValue::setLinkage().
Referenced by optimizeGlobalsInModule().
optimizeOnceStoredGlobal()
static bool optimizeOnceStoredGlobal (GlobalVariable * GV, Value * StoredOnceVal, AtomicOrdering Ordering, const DataLayout & DL, function_ref< TargetLibraryInfo &(Function &)> GetTLI) static
Definition at line 1581 of file GlobalOpt.cpp.
References llvm::extractMallocCall(), llvm::ConstantExpr::getBitCast(), llvm::GlobalVariable::getInitializer(), llvm::getMallocAllocatedType(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), llvm::NullPointerIsDefined(), OptimizeAwayTrappingUsesOfLoads(), llvm::Value::stripPointerCasts(), and tryToOptimizeStoreOfMallocToGlobal().
Referenced by processInternalGlobal().
PerformHeapAllocSRoA()
static GlobalVariable* PerformHeapAllocSRoA (GlobalVariable * GV, CallInst * CI, Value * NElems, const DataLayout & DL, const TargetLibraryInfo * TLI) static
CI is an allocation of an array of structures.
Break it up into multiple allocations of arrays of the fields.
As we process loads, if we can't immediately update all uses of the load, keep track of what scalarized loads are inserted for a given load.
Definition at line 1289 of file GlobalOpt.cpp.
References llvm::GlobalVariable::copyAttributesFrom(), llvm::CallInst::CreateMalloc(), llvm::dbgs(), llvm::numbers::e, llvm::ConstantInt::get(), llvm::PointerType::get(), llvm::CallBase::getArgOperand(), llvm::StructType::getElementType(), llvm::DataLayout::getIntPtrType(), llvm::getMallocAllocatedType(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::StructType::getNumElements(), llvm::CallBase::getOperandBundlesAsDefs(), llvm::GlobalValue::getParent(), llvm::Type::getPointerAddressSpace(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::GlobalValue::getThreadLocalMode(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::CmpInst::ICMP_SLT, llvm::GlobalValue::InternalLinkage, LLVM_DEBUG, ReplaceUsesOfMallocWithGlobal(), and llvm::ARM_MB::ST.
Referenced by tryToOptimizeStoreOfMallocToGlobal().
processGlobal()
static bool processGlobal (GlobalValue & GV, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< DominatorTree &(Function &)> LookupDomTree) static
Analyze the specified global variable and optimize it if possible.
If we make a change, return true.
Definition at line 2078 of file GlobalOpt.cpp.
References llvm::GlobalStatus::analyzeGlobal(), llvm::dyn_cast(), llvm::Value::getName(), llvm::GlobalValue::getUnnamedAddr(), llvm::GlobalValue::Global, llvm::X86AS::GS, llvm::GlobalValue::hasGlobalUnnamedAddr(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalStatus::IsCompared, llvm::GlobalValue::Local, processInternalGlobal(), llvm::GlobalValue::setUnnamedAddr(), and llvm::StringRef::startswith().
Referenced by OptimizeFunctions(), and OptimizeGlobalVars().
processInternalGlobal()
static bool processInternalGlobal (GlobalVariable * GV, const GlobalStatus & GS, function_ref< TargetLibraryInfo &(Function &)> GetTLI, function_ref< DominatorTree &(Function &)> LookupDomTree) static
Analyze the specified global variable and optimize it if possible.
If we make a change, return true.
Definition at line 1936 of file GlobalOpt.cpp.
References llvm::GlobalStatus::AccessingFunction, allNonInstructionUsersCanBeMadeInstructions(), llvm::BasicBlock::begin(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::dbgs(), llvm::Function::doesNotRecurse(), llvm::GlobalVariable::eraseFromParent(), llvm::PointerType::getAddressSpace(), llvm::DataLayout::getAllocaAddrSpace(), llvm::Module::getDataLayout(), llvm::Function::getEntryBlock(), llvm::GlobalVariable::getInitializer(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::GlobalValue::getValueType(), llvm::GlobalStatus::HasMultipleAccessingFunctions, llvm::GlobalStatus::InitializerStored, llvm::GlobalVariable::isExternallyInitialized(), isLeakCheckerRoot(), llvm::GlobalStatus::IsLoaded, isPointerValueDeadOnEntryToFunction(), llvm::Type::isSingleValueType(), LLVM_DEBUG, makeAllConstantUsesInstructions(), llvm::NotAtomic, optimizeOnceStoredGlobal(), llvm::GlobalStatus::Ordering, llvm::Value::replaceAllUsesWith(), llvm::GlobalVariable::setConstant(), llvm::GlobalVariable::setInitializer(), SRAGlobal(), llvm::GlobalStatus::StoredOnce, llvm::GlobalStatus::StoredOnceValue, TryToShrinkGlobalToBoolean(), and llvm::Value::use_empty().
Referenced by processGlobal().
RemoveAttribute()
static void RemoveAttribute (Function * F, Attribute::AttrKind A) static
Definition at line 2133 of file GlobalOpt.cpp.
References llvm::Function::getAttributes(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getAttributes(), llvm::Function::getContext(), llvm::Function::setAttributes(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setAttributes(), StripAttr(), and llvm::Value::users().
Referenced by OptimizeFunctions().
ReplaceUsesOfMallocWithGlobal()
static void ReplaceUsesOfMallocWithGlobal (Instruction * Alloc, GlobalVariable * GV) static
The Alloc pointer is stored into GV somewhere.
Transform all uses of the allocation into loads from the global and uses of the resultant pointer. Further, delete the store into GV. This assumes that these value pass the 'ValueIsOnlyUsedLocallyOrStoredToOneGlobal' predicate.
Definition at line 1025 of file GlobalOpt.cpp.
Referenced by PerformHeapAllocSRoA().
RewriteHeapSROALoadUser()
static void RewriteHeapSROALoadUser (Instruction * LoadUser, DenseMap< Value *, std::vector< Value *>> & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned >> & PHIsToRewrite) static
Given a load instruction and a value derived from the load, rewrite the derived value to use the HeapSRoA'd load.
Definition at line 1210 of file GlobalOpt.cpp.
References assert(), llvm::GetElementPtrInst::Create(), E, GetHeapSROAValue(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by RewriteUsesOfLoadForHeapSRoA().
RewriteUsesOfLoadForHeapSRoA()
static void RewriteUsesOfLoadForHeapSRoA (LoadInst * Load, DenseMap< Value *, std::vector< Value *>> & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > & PHIsToRewrite) static
We are performing Heap SRoA on a global.
Ptr is a value loaded from the global. Eliminate all uses of Ptr, making them use FieldGlobals instead. All uses of loaded values satisfy AllGlobalLoadUsesSimpleEnoughForHeapSRA.
Definition at line 1273 of file GlobalOpt.cpp.
References E, llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::Instruction::eraseFromParent(), RewriteHeapSROALoadUser(), llvm::Value::use_empty(), llvm::Value::user_begin(), and llvm::Value::user_end().
setUsedInitializer()
static void setUsedInitializer (GlobalVariable & V, const SmallPtrSetImpl< GlobalValue *> & Init) static
Definition at line 2616 of file GlobalOpt.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::array_pod_sort(), llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::collectUsedGlobalVariables(), compareNames(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallPtrSetImplBase::empty(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::GlobalVariable::eraseFromParent(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::Value::getContext(), llvm::Type::getInt8PtrTy(), llvm::GlobalValue::getParent(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::GlobalVariable::removeFromParent(), llvm::GlobalObject::setSection(), and llvm::Value::takeName().
SRAGlobal()
static GlobalVariable* SRAGlobal (GlobalVariable * GV, const DataLayout & DL) static
Perform scalar replacement of aggregates on the specified global variable.
This opens the door for other optimizations by exposing the behavior of the program in a more fine-grained way. We have determined that this transformation is safe already. We return the first global variable we insert so that the caller can reprocess it.
Definition at line 477 of file GlobalOpt.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), CanDoGlobalSRA(), llvm::GlobalVariable::copyAttributesFrom(), llvm::GetElementPtrInst::Create(), llvm::dbgs(), llvm::numbers::e, llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), GEP, llvm::DataLayout::getABITypeAlignment(), llvm::PointerType::getAddressSpace(), llvm::GlobalObject::getAlignment(), llvm::Value::getContext(), llvm::StructLayout::getElementOffset(), llvm::StructLayout::getElementOffsetInBits(), llvm::ConstantExpr::getGetElementPtr(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::DataLayout::getStructLayout(), llvm::GlobalValue::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeAllocSizeInBits(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::hasLocalLinkage(), llvm::tgtok::In, llvm::GlobalValue::InternalLinkage, llvm::GlobalVariable::isExternallyInitialized(), LLVM_DEBUG, llvm::MinAlign(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::GlobalObject::setAlignment(), llvm::GlobalVariable::setExternallyInitialized(), Size, transferSRADebugInfo(), llvm::Value::use_empty(), llvm::Value::user_back(), and llvm::Value::users().
Referenced by processInternalGlobal().
STATISTIC() [1/17]
STATISTIC (NumMarked , "Number of globals marked constant")
STATISTIC() [2/17]
STATISTIC (NumUnnamed , "Number of globals marked unnamed_addr")
STATISTIC() [3/17]
STATISTIC (NumSRA , "Number of aggregate globals broken into scalars")
STATISTIC() [4/17]
STATISTIC (NumHeapSRA , "Number of heap objects SRA'd")
STATISTIC() [5/17]
STATISTIC (NumSubstitute , "Number of globals with initializers stored into them")
STATISTIC() [6/17]
STATISTIC (NumDeleted , "Number of globals deleted")
STATISTIC() [7/17]
STATISTIC (NumGlobUses , "Number of global uses devirtualized")
STATISTIC() [8/17]
STATISTIC (NumLocalized , "Number of globals localized")
STATISTIC() [9/17]
STATISTIC (NumShrunkToBool , "Number of global vars shrunk to booleans")
STATISTIC() [10/17]
STATISTIC (NumFastCallFns , "Number of functions converted to fastcc")
STATISTIC() [11/17]
STATISTIC (NumCtorsEvaluated , "Number of static ctors evaluated")
STATISTIC() [12/17]
STATISTIC (NumNestRemoved , "Number of nest attributes removed")
STATISTIC() [13/17]
STATISTIC (NumAliasesResolved , "Number of global aliases resolved")
STATISTIC() [14/17]
STATISTIC (NumAliasesRemoved , "Number of global aliases eliminated")
STATISTIC() [15/17]
STATISTIC (NumCXXDtorsRemoved , "Number of global C++ destructors removed")
STATISTIC() [16/17]
STATISTIC (NumInternalFunc , "Number of internal functions")
STATISTIC() [17/17]
STATISTIC (NumColdCC , "Number of functions marked coldcc")
StripAttr()
static AttributeList StripAttr (LLVMContext & C, AttributeList Attrs, Attribute::AttrKind A) static
Definition at line 2125 of file GlobalOpt.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::AttributeList::hasAttrSomewhere(), and llvm::AttributeList::removeAttribute().
Referenced by RemoveAttribute().
transferSRADebugInfo()
static void transferSRADebugInfo (GlobalVariable * GV, GlobalVariable * NGV, uint64_t FragmentOffsetInBits, uint64_t FragmentSizeInBits, unsigned NumElements) static
Copy over the debug info for a variable to its SRA replacements.
Definition at line 451 of file GlobalOpt.cpp.
References llvm::GlobalVariable::addDebugInfo(), llvm::DIExpression::createFragmentExpression(), E, llvm::MDNode::get(), and llvm::GlobalVariable::getDebugInfo().
Referenced by SRAGlobal().
tryToOptimizeStoreOfMallocToGlobal()
static bool tryToOptimizeStoreOfMallocToGlobal (GlobalVariable * GV, CallInst * CI, Type * AllocTy, AtomicOrdering Ordering, const DataLayout & DL, TargetLibraryInfo * TLI) static
This function is called when we see a pointer global variable with a single value stored it that is a malloc or cast of malloc.
Definition at line 1482 of file GlobalOpt.cpp.
References AllGlobalLoadUsesSimpleEnoughForHeapSRA(), AllUsesOfLoadedValueWillTrapIfNull(), llvm::CallInst::CreateMalloc(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::DataLayout::getIntPtrType(), llvm::getMallocAllocatedType(), llvm::getMallocArraySize(), llvm::Value::getName(), llvm::StructType::getNumElements(), llvm::CallBase::getOperandBundlesAsDefs(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Type::isSized(), llvm::NotAtomic, OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::Value::replaceAllUsesWith(), and ValueIsOnlyUsedLocallyOrStoredToOneGlobal().
Referenced by optimizeOnceStoredGlobal().
TryToShrinkGlobalToBoolean()
static bool TryToShrinkGlobalToBoolean (GlobalVariable * GV, Constant * OtherVal) static
At this point, we have learned that the only two values ever stored into GV are its initializer and OtherVal.
See if we can shrink the global into a boolean and select between the two values whenever it is used. This exposes the values to other scalar optimizations.
Definition at line 1619 of file GlobalOpt.cpp.
References llvm::GlobalVariable::addDebugInfo(), assert(), llvm::GlobalVariable::copyAttributesFrom(), llvm::SelectInst::Create(), llvm::dbgs(), llvm::dyn_cast(), E, llvm::Instruction::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::ConstantInt::get(), llvm::MDNode::get(), llvm::PointerType::getAddressSpace(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::GlobalVariable::getDebugInfo(), llvm::Instruction::getDebugLoc(), llvm::PointerType::getElementType(), llvm::ConstantInt::getFalse(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt1Ty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::User::getOperand(), llvm::LoadInst::getOrdering(), llvm::GlobalValue::getParent(), llvm::LoadInst::getSyncScopeID(), llvm::GlobalValue::getThreadLocalMode(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSizeInBits(), llvm::GlobalValue::getValueType(), llvm::ConstantInt::getZExtValue(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::GlobalValue::InternalLinkage, llvm::Type::isFloatingPointTy(), llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), llvm::Type::isVectorTy(), LLVM_DEBUG, llvm::None, llvm::DIExpression::prependOpcodes(), llvm::Value::replaceAllUsesWith(), llvm::Instruction::setDebugLoc(), SI, llvm::Value::takeName(), llvm::Value::use_empty(), llvm::Value::user_back(), and llvm::Value::users().
Referenced by processInternalGlobal().
ValueIsOnlyUsedLocallyOrStoredToOneGlobal()
static bool ValueIsOnlyUsedLocallyOrStoredToOneGlobal (const Instruction * V, const GlobalVariable * GV, SmallPtrSetImpl< const PHINode *> & PHIs) static
Scan the use-list of V checking to make sure that there are no complex uses of V.
We permit simple things like dereferencing the pointer, but not storing through the address, unless it is to the specified global.
Definition at line 978 of file GlobalOpt.cpp.
References llvm::User::getNumOperands(), llvm::SmallPtrSetImpl< PtrType >::insert(), SI, and llvm::Value::users().
Referenced by tryToOptimizeStoreOfMallocToGlobal().
Variable Documentation
ColdCCRelFreq
cl::opt<int> ColdCCRelFreq("coldcc-rel-freq", cl::Hidden, cl::init(2), cl::ZeroOrMore, cl::desc("Maximum block frequency, expressed as a percentage of caller's " "entry frequency, for a call site to be considered cold for enabling" "coldcc")) static
Referenced by isColdCallSite().
EnableColdCCStressTest
cl::opt<bool> EnableColdCCStressTest("enable-coldcc-stress-test", cl::desc("Enable stress test of coldcc by adding " "calling conv to all internal functions."), cl::init(false), cl::Hidden) static
Referenced by OptimizeFunctions().
false
Global Variable false
Definition at line 3058 of file GlobalOpt.cpp.
globalopt
globalopt
Definition at line 3058 of file GlobalOpt.cpp.
Optimizer
Global Variable Optimizer
Definition at line 3058 of file GlobalOpt.cpp.