LLVM: lib/Transforms/Utils/GlobalStatus.cpp File Reference
GlobalStatus.cpp File Reference
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include <algorithm>
#include <cassert>
Functions
static AtomicOrdering strongerOrdering (AtomicOrdering X, AtomicOrdering Y)
Return the stronger of the two ordering.
static bool analyzeGlobalAux (const Value *V, GlobalStatus &GS, SmallPtrSetImpl< const Value *> &VisitedUsers)
Function Documentation
analyzeGlobalAux()
static bool analyzeGlobalAux (const Value * V, GlobalStatus & GS, SmallPtrSetImpl< const Value *> & VisitedUsers) static
Definition at line 61 of file GlobalStatus.cpp.
References llvm::GlobalStatus::AccessingFunction, assert(), C, F(), for(), llvm::GlobalStatus::GlobalStatus(), llvm::GlobalStatus::HasMultipleAccessingFunctions, llvm::GlobalStatus::HasNonInstructionUser, I, if(), llvm::GlobalStatus::InitializerStored, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::CallBase::isCallee(), llvm::GlobalStatus::IsCompared, llvm::GlobalStatus::IsLoaded, llvm::isSafeToDestroyConstant(), llvm::GlobalStatus::Ordering, SI, llvm::GlobalStatus::Stored, llvm::GlobalStatus::StoredOnce, llvm::GlobalStatus::StoredOnceValue, strongerOrdering(), and llvm::Value::uses().
Referenced by llvm::GlobalStatus::analyzeGlobal().
strongerOrdering()
static AtomicOrdering strongerOrdering (AtomicOrdering X, AtomicOrdering Y) static
Return the stronger of the two ordering.
If the two orderings are acquire and release, then return AcquireRelease.
Definition at line 34 of file GlobalStatus.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::max(), and llvm::Release.
Referenced by analyzeGlobalAux().