LLVM: lib/Transforms/IPO/GlobalDCE.cpp File Reference
GlobalDCE.cpp File Reference
#include "llvm/Transforms/IPO/GlobalDCE.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/TypeMetadataUtils.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/CtorUtils.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
Macros
#define DEBUG_TYPE "globaldce"
Functions
STATISTIC (NumAliases, "Number of global aliases removed")
STATISTIC (NumFunctions, "Number of functions removed")
STATISTIC (NumIFuncs, "Number of indirect functions removed")
STATISTIC (NumVariables, "Number of global variables removed")
STATISTIC (NumVFuncs, "Number of virtual functions removed")
INITIALIZE_PASS (GlobalDCELegacyPass, "globaldce", "Dead Global Elimination", false, false) ModulePass *llvm
static bool isEmptyFunction (Function *F)
Returns true if F is effectively empty.
Variables
static cl::opt< bool > ClEnableVFE ("enable-vfe", cl::Hidden, cl::init(true), cl::ZeroOrMore, cl::desc("Enable virtual function elimination"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "globaldce"
Definition at line 34 of file GlobalDCE.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (GlobalDCELegacyPass , "globaldce" , "Dead Global Elimination" , false , false)
Definition at line 79 of file GlobalDCE.cpp.
isEmptyFunction()
static bool isEmptyFunction (Function * F) static
Returns true if F is effectively empty.
Definition at line 88 of file GlobalDCE.cpp.
References llvm::SmallPtrSetImpl< PtrType >::begin(), C, Callee, llvm::SmallVectorImpl< T >::clear(), ClEnableVFE, llvm::dbgs(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::GlobalValue::getComdat(), llvm::Function::getEntryBlock(), llvm::Module::getFunction(), llvm::GlobalVariable::getInitializer(), llvm::Module::getModuleFlag(), llvm::Intrinsic::getName(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::getPointerAtOffset(), llvm::Module::globals(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::GlobalValue::isDeclaration(), LLVM_DEBUG, llvm::make_range(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MipsISD::Ret, llvm::Constant::stripPointerCasts(), llvm::Value::users(), llvm::GlobalObject::VCallVisibilityLinkageUnit, and llvm::GlobalObject::VCallVisibilityTranslationUnit.
Referenced by llvm::GlobalDCEPass::run().
STATISTIC() [1/5]
STATISTIC (NumAliases , "Number of global aliases removed")
STATISTIC() [2/5]
STATISTIC (NumFunctions , "Number of functions removed")
STATISTIC() [3/5]
STATISTIC (NumIFuncs , "Number of indirect functions removed")
STATISTIC() [4/5]
STATISTIC (NumVariables , "Number of global variables removed")
STATISTIC() [5/5]
STATISTIC (NumVFuncs , "Number of virtual functions removed")
Variable Documentation
ClEnableVFE
cl::opt<bool> ClEnableVFE("enable-vfe", cl::Hidden, cl::init(true), cl::ZeroOrMore, cl::desc("Enable virtual function elimination")) static
Referenced by isEmptyFunction().