LLVM: include/llvm/Support/GraphWriter.h File Reference
GraphWriter.h File Reference
#include "llvm/ADT/GraphTraits.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstddef>
#include <iterator>
#include <string>
#include <type_traits>
#include <vector>
Classes
class llvm::GraphWriter< GraphType >
Namespaces
llvm
This class represents lattice values for constants.
llvm::DOT
llvm::GraphProgram
Enumerations
enum llvm::GraphProgram::Name {
llvm::GraphProgram::DOT, llvm::GraphProgram::FDP, llvm::GraphProgram::NEATO, llvm::GraphProgram::TWOPI,
llvm::GraphProgram::CIRCO
}
Functions
std::string llvm::DOT::EscapeString (const std::string &Label)
StringRef llvm::DOT::getColorString (unsigned NodeNumber)
Get a color string for this node number.
bool llvm::DisplayGraph (StringRef Filename, bool wait=true, GraphProgram::Name program=GraphProgram::DOT)
template<typename GraphType >
raw_ostream & llvm::WriteGraph (raw_ostream &O, const GraphType &G, bool ShortNames=false, const Twine &Title="")
std::string llvm::createGraphFilename (const Twine &Name, int &FD)
template<typename GraphType >
*ViewGraph Emit a dot run run gv on the postscript *then cleanup For use from the debugger *void ViewGraph (const GraphType &G, const Twine &Name, bool ShortNames=false, const Twine &Title="", GraphProgram::Name Program=GraphProgram::DOT)
Variables
*ViewGraph Emit a dot graph
*ViewGraph Emit a dot run dot
*ViewGraph Emit a dot run run gv on the postscript file
Function Documentation
ViewGraph()
template<typename GraphType > * ViewGraph Emit a dot run run gv on the postscript * then cleanup For use from the debugger* void ViewGraph (const GraphType & G, const Twine & Name, bool ShortNames = false, const Twine & Title = "", GraphProgram::Name Program = GraphProgram::DOT)
Definition at line 366 of file GraphWriter.h.
References llvm::DisplayGraph(), and llvm::WriteGraph().
Referenced by annotateAllFunctions(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::DOTGraphTraitsModuleViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnModule(), llvm::EdgeBundles::view(), llvm::BlockFrequencyInfo::view(), llvm::MachineBlockFrequencyInfo::view(), llvm::MachineFunction::viewCFG(), llvm::Function::viewCFG(), llvm::MachineFunction::viewCFGOnly(), llvm::Function::viewCFGOnly(), llvm::DominatorTree::viewGraph(), llvm::ScheduleDAGMI::viewGraph(), llvm::SelectionDAG::viewGraph(), llvm::ScheduleDAG::viewGraph(), and viewRegionInfo().
Variable Documentation
dot
* ViewGraph Emit a dot run dot
Definition at line 362 of file GraphWriter.h.
Referenced by llvm::detail::IEEEFloat::convertFromZeroExtendedInteger(), and llvm::interpretDecimal().
file
* ViewGraph Emit a dot run run gv on the postscript file
Definition at line 362 of file GraphWriter.h.
Referenced by FunctionNumber(), and llvm::ScopedFatalErrorHandler::~ScopedFatalErrorHandler().
graph
* ViewGraph Emit a dot graph
Definition at line 362 of file GraphWriter.h.