LLVM: Transformation Utilities
Transformation Utilities
LLVM-C: C interface to LLVM » Transforms
Functions
void LLVMAddLowerSwitchPass (LLVMPassManagerRef PM)
See llvm::createLowerSwitchPass function.
void LLVMAddPromoteMemoryToRegisterPass (LLVMPassManagerRef PM)
See llvm::createPromoteMemoryToRegisterPass function.
void LLVMAddAddDiscriminatorsPass (LLVMPassManagerRef PM)
See llvm::createAddDiscriminatorsPass function.
Detailed Description
Function Documentation
LLVMAddAddDiscriminatorsPass()
void LLVMAddAddDiscriminatorsPass (LLVMPassManagerRef PM)
See llvm::createAddDiscriminatorsPass function.
Definition at line 58 of file Utils.cpp.
References llvm::createAddDiscriminatorsPass(), and llvm::unwrap().
LLVMAddLowerSwitchPass()
void LLVMAddLowerSwitchPass (LLVMPassManagerRef PM)
See llvm::createLowerSwitchPass function.
Definition at line 50 of file Utils.cpp.
References llvm::createLowerSwitchPass(), and llvm::unwrap().
LLVMAddPromoteMemoryToRegisterPass()
void LLVMAddPromoteMemoryToRegisterPass (LLVMPassManagerRef PM)
See llvm::createPromoteMemoryToRegisterPass function.
Definition at line 54 of file Utils.cpp.
References llvm::createPromoteMemoryToRegisterPass(), and llvm::unwrap().