LLVM: Constant Expressions
Constant Expressions
LLVM-C: C interface to LLVM » Core » Values » Constants
Functions in this group correspond to APIs on llvm::ConstantExpr.
Functions
LLVMOpcode LLVMGetConstOpcode (LLVMValueRef ConstantVal)
LLVMValueRef LLVMAlignOf (LLVMTypeRef Ty)
LLVMValueRef LLVMSizeOf (LLVMTypeRef Ty)
LLVMValueRef LLVMConstNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNSWNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNUWNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstFNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNot (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstExactUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstExactSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstURem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstAnd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstOr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstXor (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstICmp (LLVMIntPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFCmp (LLVMRealPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstShl (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstLShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstAShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstGEP (LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstGEP2 (LLVMTypeRef Ty, LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstInBoundsGEP (LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstInBoundsGEP2 (LLVMTypeRef Ty, LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstZExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstUIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPToUI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPToSI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstPtrToInt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstIntToPtr (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstAddrSpaceCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstZExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstTruncOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstPointerCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstIntCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType, LLVMBool isSigned)
LLVMValueRef LLVMConstFPCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSelect (LLVMValueRef ConstantCondition, LLVMValueRef ConstantIfTrue, LLVMValueRef ConstantIfFalse)
LLVMValueRef LLVMConstExtractElement (LLVMValueRef VectorConstant, LLVMValueRef IndexConstant)
LLVMValueRef LLVMConstInsertElement (LLVMValueRef VectorConstant, LLVMValueRef ElementValueConstant, LLVMValueRef IndexConstant)
LLVMValueRef LLVMConstShuffleVector (LLVMValueRef VectorAConstant, LLVMValueRef VectorBConstant, LLVMValueRef MaskConstant)
LLVMValueRef LLVMConstExtractValue (LLVMValueRef AggConstant, unsigned *IdxList, unsigned NumIdx)
LLVMValueRef LLVMConstInsertValue (LLVMValueRef AggConstant, LLVMValueRef ElementValueConstant, unsigned *IdxList, unsigned NumIdx)
LLVMValueRef LLVMBlockAddress (LLVMValueRef F, LLVMBasicBlockRef BB)
LLVMValueRef LLVMConstInlineAsm (LLVMTypeRef Ty, const char *AsmString, const char *Constraints, LLVMBool HasSideEffects, LLVMBool IsAlignStack)
Deprecated: Use LLVMGetInlineAsm instead.
Detailed Description
Functions in this group correspond to APIs on llvm::ConstantExpr.
See also
llvm::ConstantExpr.
Function Documentation
LLVMAlignOf()
LLVMValueRef LLVMAlignOf (LLVMTypeRef Ty)
Definition at line 1459 of file Core.cpp.
References llvm::ConstantExpr::getAlignOf(), llvm::unwrap(), and llvm::wrap().
LLVMBlockAddress()
LLVMValueRef LLVMBlockAddress (LLVMValueRef F, LLVMBasicBlockRef BB)
Definition at line 1814 of file Core.cpp.
References llvm::BlockAddress::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstAdd()
LLVMValueRef LLVMConstAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1488 of file Core.cpp.
References llvm::ConstantExpr::getAdd(), and llvm::wrap().
LLVMConstAddrSpaceCast()
LLVMValueRef LLVMConstAddrSpaceCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1721 of file Core.cpp.
References llvm::ConstantExpr::getAddrSpaceCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstAnd()
LLVMValueRef LLVMConstAnd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1596 of file Core.cpp.
References llvm::ConstantExpr::getAnd(), and llvm::wrap().
LLVMConstAShr()
LLVMValueRef LLVMConstAShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1635 of file Core.cpp.
References llvm::ConstantExpr::getAShr(), and llvm::wrap().
LLVMConstBitCast()
LLVMValueRef LLVMConstBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1716 of file Core.cpp.
References llvm::ConstantExpr::getBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstExactSDiv()
LLVMValueRef LLVMConstExactSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1570 of file Core.cpp.
References llvm::ConstantExpr::getExactSDiv(), and llvm::wrap().
LLVMConstExactUDiv()
LLVMValueRef LLVMConstExactUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1559 of file Core.cpp.
References llvm::ConstantExpr::getExactUDiv(), and llvm::wrap().
LLVMConstExtractElement()
LLVMValueRef LLVMConstExtractElement (LLVMValueRef VectorConstant, LLVMValueRef IndexConstant)
Definition at line 1770 of file Core.cpp.
References llvm::ConstantExpr::getExtractElement(), and llvm::wrap().
LLVMConstExtractValue()
LLVMValueRef LLVMConstExtractValue (LLVMValueRef AggConstant, unsigned * IdxList, unsigned NumIdx)
Definition at line 1792 of file Core.cpp.
References llvm::ConstantExpr::getExtractValue(), llvm::makeArrayRef(), and llvm::wrap().
LLVMConstFAdd()
LLVMValueRef LLVMConstFAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1505 of file Core.cpp.
References llvm::ConstantExpr::getFAdd(), and llvm::wrap().
LLVMConstFCmp()
LLVMValueRef LLVMConstFCmp (LLVMRealPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1618 of file Core.cpp.
References llvm::ConstantExpr::getFCmp(), and llvm::wrap().
LLVMConstFDiv()
LLVMValueRef LLVMConstFDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1576 of file Core.cpp.
References llvm::ConstantExpr::getFDiv(), and llvm::wrap().
LLVMConstFMul()
LLVMValueRef LLVMConstFMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1549 of file Core.cpp.
References llvm::ConstantExpr::getFMul(), and llvm::wrap().
LLVMConstFNeg()
LLVMValueRef LLVMConstFNeg (LLVMValueRef ConstantVal)
Definition at line 1480 of file Core.cpp.
References llvm::ConstantExpr::getFNeg(), and llvm::wrap().
LLVMConstFPCast()
LLVMValueRef LLVMConstFPCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1757 of file Core.cpp.
References llvm::ConstantExpr::getFPCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPExt()
LLVMValueRef LLVMConstFPExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1681 of file Core.cpp.
References llvm::ConstantExpr::getFPExtend(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPToSI()
LLVMValueRef LLVMConstFPToSI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1701 of file Core.cpp.
References llvm::ConstantExpr::getFPToSI(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPToUI()
LLVMValueRef LLVMConstFPToUI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1696 of file Core.cpp.
References llvm::ConstantExpr::getFPToUI(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPTrunc()
LLVMValueRef LLVMConstFPTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1676 of file Core.cpp.
References llvm::ConstantExpr::getFPTrunc(), llvm::unwrap(), and llvm::wrap().
LLVMConstFRem()
LLVMValueRef LLVMConstFRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1591 of file Core.cpp.
References llvm::ConstantExpr::getFRem(), and llvm::wrap().
LLVMConstFSub()
LLVMValueRef LLVMConstFSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1527 of file Core.cpp.
References llvm::ConstantExpr::getFSub(), and llvm::wrap().
LLVMConstGEP()
LLVMValueRef LLVMConstGEP (LLVMValueRef ConstantVal, LLVMValueRef * ConstantIndices, unsigned NumIndices)
Definition at line 1640 of file Core.cpp.
References llvm::ConstantExpr::getGetElementPtr(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::wrap().
LLVMConstGEP2()
LLVMValueRef LLVMConstGEP2 (LLVMTypeRef Ty, LLVMValueRef ConstantVal, LLVMValueRef * ConstantIndices, unsigned NumIndices)
LLVMConstICmp()
LLVMValueRef LLVMConstICmp (LLVMIntPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1611 of file Core.cpp.
References llvm::ConstantExpr::getICmp(), and llvm::wrap().
LLVMConstInBoundsGEP()
LLVMValueRef LLVMConstInBoundsGEP (LLVMValueRef ConstantVal, LLVMValueRef * ConstantIndices, unsigned NumIndices)
Definition at line 1650 of file Core.cpp.
References llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::wrap().
LLVMConstInBoundsGEP2()
LLVMValueRef LLVMConstInBoundsGEP2 (LLVMTypeRef Ty, LLVMValueRef ConstantVal, LLVMValueRef * ConstantIndices, unsigned NumIndices)
LLVMConstInlineAsm()
LLVMValueRef LLVMConstInlineAsm (LLVMTypeRef Ty, const char * AsmString, const char * Constraints, LLVMBool HasSideEffects, LLVMBool IsAlignStack)
Deprecated: Use LLVMGetInlineAsm instead.
Definition at line 1806 of file Core.cpp.
References llvm::InlineAsm::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstInsertElement()
LLVMValueRef LLVMConstInsertElement (LLVMValueRef VectorConstant, LLVMValueRef ElementValueConstant, LLVMValueRef IndexConstant)
Definition at line 1776 of file Core.cpp.
References llvm::ConstantExpr::getInsertElement(), and llvm::wrap().
LLVMConstInsertValue()
LLVMValueRef LLVMConstInsertValue (LLVMValueRef AggConstant, LLVMValueRef ElementValueConstant, unsigned * IdxList, unsigned NumIdx)
Definition at line 1798 of file Core.cpp.
References llvm::ConstantExpr::getInsertValue(), llvm::makeArrayRef(), and llvm::wrap().
LLVMConstIntCast()
LLVMValueRef LLVMConstIntCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType, LLVMBool isSigned)
Definition at line 1751 of file Core.cpp.
References llvm::ConstantExpr::getIntegerCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstIntToPtr()
LLVMValueRef LLVMConstIntToPtr (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1711 of file Core.cpp.
References llvm::ConstantExpr::getIntToPtr(), llvm::unwrap(), and llvm::wrap().
LLVMConstLShr()
LLVMValueRef LLVMConstLShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1630 of file Core.cpp.
References llvm::ConstantExpr::getLShr(), and llvm::wrap().
LLVMConstMul()
LLVMValueRef LLVMConstMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1532 of file Core.cpp.
References llvm::ConstantExpr::getMul(), and llvm::wrap().
LLVMConstNeg()
LLVMValueRef LLVMConstNeg (LLVMValueRef ConstantVal)
Definition at line 1467 of file Core.cpp.
References llvm::ConstantExpr::getNeg(), and llvm::wrap().
LLVMConstNot()
LLVMValueRef LLVMConstNot (LLVMValueRef ConstantVal)
Definition at line 1484 of file Core.cpp.
References llvm::ConstantExpr::getNot(), and llvm::wrap().
LLVMConstNSWAdd()
LLVMValueRef LLVMConstNSWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1493 of file Core.cpp.
References llvm::ConstantExpr::getNSWAdd(), and llvm::wrap().
LLVMConstNSWMul()
LLVMValueRef LLVMConstNSWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1537 of file Core.cpp.
References llvm::ConstantExpr::getNSWMul(), and llvm::wrap().
LLVMConstNSWNeg()
LLVMValueRef LLVMConstNSWNeg (LLVMValueRef ConstantVal)
Definition at line 1471 of file Core.cpp.
References llvm::ConstantExpr::getNSWNeg(), and llvm::wrap().
LLVMConstNSWSub()
LLVMValueRef LLVMConstNSWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1515 of file Core.cpp.
References llvm::ConstantExpr::getNSWSub(), and llvm::wrap().
LLVMConstNUWAdd()
LLVMValueRef LLVMConstNUWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1499 of file Core.cpp.
References llvm::ConstantExpr::getNUWAdd(), and llvm::wrap().
LLVMConstNUWMul()
LLVMValueRef LLVMConstNUWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1543 of file Core.cpp.
References llvm::ConstantExpr::getNUWMul(), and llvm::wrap().
LLVMConstNUWNeg()
LLVMValueRef LLVMConstNUWNeg (LLVMValueRef ConstantVal)
Definition at line 1475 of file Core.cpp.
References llvm::ConstantExpr::getNUWNeg(), and llvm::wrap().
LLVMConstNUWSub()
LLVMValueRef LLVMConstNUWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1521 of file Core.cpp.
References llvm::ConstantExpr::getNUWSub(), and llvm::wrap().
LLVMConstOr()
LLVMValueRef LLVMConstOr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1601 of file Core.cpp.
References llvm::ConstantExpr::getOr(), and llvm::wrap().
LLVMConstPointerCast()
LLVMValueRef LLVMConstPointerCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1745 of file Core.cpp.
References llvm::ConstantExpr::getPointerCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstPtrToInt()
LLVMValueRef LLVMConstPtrToInt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1706 of file Core.cpp.
References llvm::ConstantExpr::getPtrToInt(), llvm::unwrap(), and llvm::wrap().
LLVMConstSDiv()
LLVMValueRef LLVMConstSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1565 of file Core.cpp.
References llvm::ConstantExpr::getSDiv(), and llvm::wrap().
LLVMConstSelect()
LLVMValueRef LLVMConstSelect (LLVMValueRef ConstantCondition, LLVMValueRef ConstantIfTrue, LLVMValueRef ConstantIfFalse)
Definition at line 1762 of file Core.cpp.
References llvm::ConstantExpr::getSelect(), and llvm::wrap().
LLVMConstSExt()
LLVMValueRef LLVMConstSExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1666 of file Core.cpp.
References llvm::ConstantExpr::getSExt(), llvm::unwrap(), and llvm::wrap().
LLVMConstSExtOrBitCast()
LLVMValueRef LLVMConstSExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1733 of file Core.cpp.
References llvm::ConstantExpr::getSExtOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstShl()
LLVMValueRef LLVMConstShl (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1625 of file Core.cpp.
References llvm::ConstantExpr::getShl(), and llvm::wrap().
LLVMConstShuffleVector()
LLVMValueRef LLVMConstShuffleVector (LLVMValueRef VectorAConstant, LLVMValueRef VectorBConstant, LLVMValueRef MaskConstant)
Definition at line 1784 of file Core.cpp.
References llvm::ConstantExpr::getShuffleVector(), and llvm::wrap().
LLVMConstSIToFP()
LLVMValueRef LLVMConstSIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1691 of file Core.cpp.
References llvm::ConstantExpr::getSIToFP(), llvm::unwrap(), and llvm::wrap().
LLVMConstSRem()
LLVMValueRef LLVMConstSRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1586 of file Core.cpp.
References llvm::ConstantExpr::getSRem(), and llvm::wrap().
LLVMConstSub()
LLVMValueRef LLVMConstSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1510 of file Core.cpp.
References llvm::ConstantExpr::getSub(), and llvm::wrap().
LLVMConstTrunc()
LLVMValueRef LLVMConstTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1661 of file Core.cpp.
References llvm::ConstantExpr::getTrunc(), llvm::unwrap(), and llvm::wrap().
LLVMConstTruncOrBitCast()
LLVMValueRef LLVMConstTruncOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1739 of file Core.cpp.
References llvm::ConstantExpr::getTruncOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstUDiv()
LLVMValueRef LLVMConstUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1554 of file Core.cpp.
References llvm::ConstantExpr::getUDiv(), and llvm::wrap().
LLVMConstUIToFP()
LLVMValueRef LLVMConstUIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1686 of file Core.cpp.
References llvm::ConstantExpr::getUIToFP(), llvm::unwrap(), and llvm::wrap().
LLVMConstURem()
LLVMValueRef LLVMConstURem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1581 of file Core.cpp.
References llvm::ConstantExpr::getURem(), and llvm::wrap().
LLVMConstXor()
LLVMValueRef LLVMConstXor (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1606 of file Core.cpp.
References llvm::ConstantExpr::getXor(), and llvm::wrap().
LLVMConstZExt()
LLVMValueRef LLVMConstZExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1671 of file Core.cpp.
References llvm::ConstantExpr::getZExt(), llvm::unwrap(), and llvm::wrap().
LLVMConstZExtOrBitCast()
LLVMValueRef LLVMConstZExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1727 of file Core.cpp.
References llvm::ConstantExpr::getZExtOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMGetConstOpcode()
LLVMOpcode LLVMGetConstOpcode (LLVMValueRef ConstantVal)
Definition at line 1455 of file Core.cpp.
References getOpcode(), and map_to_llvmopcode().
LLVMSizeOf()
LLVMValueRef LLVMSizeOf (LLVMTypeRef Ty)
Definition at line 1463 of file Core.cpp.
References llvm::ConstantExpr::getSizeOf(), llvm::unwrap(), and llvm::wrap().