LLVM: Threading
Threading
LLVM-C: C interface to LLVM
Handle the structures needed to make LLVM safe for multithreading.
Functions
LLVMBool LLVMStartMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
void LLVMStopMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
LLVMBool LLVMIsMultithreaded (void)
Check whether LLVM is executing in thread-safe mode or not.
Detailed Description
Handle the structures needed to make LLVM safe for multithreading.
Function Documentation
LLVMIsMultithreaded()
LLVMBool LLVMIsMultithreaded (void)
Check whether LLVM is executing in thread-safe mode or not.
See also
llvm::llvm_is_multithreaded
Definition at line 4111 of file Core.cpp.
References llvm::llvm_is_multithreaded().
Referenced by LLVMStartMultithreaded().
LLVMStartMultithreaded()
LLVMBool LLVMStartMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
This function always returns LLVMIsMultithreaded().
Definition at line 4104 of file Core.cpp.
References LLVMIsMultithreaded().
LLVMStopMultithreaded()
void LLVMStopMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
Definition at line 4108 of file Core.cpp.