LLVM: PHI Nodes
PHI Nodes
LLVM-C: C interface to LLVM » Core » Instructions
Functions in this group only apply to instructions that map to llvm::PHINode instances.
Functions
void LLVMAddIncoming (LLVMValueRef PhiNode, LLVMValueRef *IncomingValues, LLVMBasicBlockRef *IncomingBlocks, unsigned Count)
Add an incoming value to the end of a PHI list.
unsigned LLVMCountIncoming (LLVMValueRef PhiNode)
Obtain the number of incoming basic blocks to a PHI node.
LLVMValueRef LLVMGetIncomingValue (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMValueRef.
LLVMBasicBlockRef LLVMGetIncomingBlock (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMBasicBlockRef.
Detailed Description
Functions in this group only apply to instructions that map to llvm::PHINode instances.
Function Documentation
LLVMAddIncoming()
void LLVMAddIncoming (LLVMValueRef PhiNode, LLVMValueRef * IncomingValues, LLVMBasicBlockRef * IncomingBlocks, unsigned Count)
Add an incoming value to the end of a PHI list.
Definition at line 2937 of file Core.cpp.
References llvm::PHINode::addIncoming(), I, and llvm::unwrap().
LLVMCountIncoming()
unsigned LLVMCountIncoming (LLVMValueRef PhiNode)
Obtain the number of incoming basic blocks to a PHI node.
Definition at line 2944 of file Core.cpp.
LLVMGetIncomingBlock()
LLVMBasicBlockRef LLVMGetIncomingBlock (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMBasicBlockRef.
Definition at line 2952 of file Core.cpp.
References llvm::wrap().
LLVMGetIncomingValue()
LLVMValueRef LLVMGetIncomingValue (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMValueRef.
Definition at line 2948 of file Core.cpp.
References llvm::wrap().