LLVM: Integer Types
Integer Types
LLVM-C: C interface to LLVM » Core » Types
Functions in this section operate on integer types.
Functions
LLVMTypeRef LLVMInt1TypeInContext (LLVMContextRef C)
Obtain an integer type from a context with specified bit width.
LLVMTypeRef LLVMInt8TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt16TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt32TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt64TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt128TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMIntTypeInContext (LLVMContextRef C, unsigned NumBits)
LLVMTypeRef LLVMInt1Type (void)
Obtain an integer type from the global context with a specified bit width.
LLVMTypeRef LLVMInt8Type (void)
LLVMTypeRef LLVMInt16Type (void)
LLVMTypeRef LLVMInt32Type (void)
LLVMTypeRef LLVMInt64Type (void)
LLVMTypeRef LLVMInt128Type (void)
LLVMTypeRef LLVMIntType (unsigned NumBits)
unsigned LLVMGetIntTypeWidth (LLVMTypeRef IntegerTy)
Detailed Description
Functions in this section operate on integer types.
Function Documentation
LLVMGetIntTypeWidth()
unsigned LLVMGetIntTypeWidth (LLVMTypeRef IntegerTy)
Definition at line 590 of file Core.cpp.
References getBitWidth().
LLVMInt128Type()
LLVMTypeRef LLVMInt128Type (void)
Definition at line 583 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt128TypeInContext().
LLVMInt128TypeInContext()
LLVMTypeRef LLVMInt128TypeInContext (LLVMContextRef C)
Definition at line 561 of file Core.cpp.
References llvm::Type::getInt128Ty(), and llvm::unwrap().
Referenced by LLVMInt128Type().
LLVMInt16Type()
LLVMTypeRef LLVMInt16Type (void)
Definition at line 574 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt16TypeInContext().
LLVMInt16TypeInContext()
LLVMTypeRef LLVMInt16TypeInContext (LLVMContextRef C)
Definition at line 552 of file Core.cpp.
References llvm::Type::getInt16Ty(), and llvm::unwrap().
Referenced by LLVMInt16Type().
LLVMInt1Type()
LLVMTypeRef LLVMInt1Type (void)
Obtain an integer type from the global context with a specified bit width.
Definition at line 568 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt1TypeInContext().
LLVMInt1TypeInContext()
LLVMTypeRef LLVMInt1TypeInContext (LLVMContextRef C)
Obtain an integer type from a context with specified bit width.
Definition at line 546 of file Core.cpp.
References llvm::Type::getInt1Ty(), and llvm::unwrap().
Referenced by LLVMInt1Type().
LLVMInt32Type()
LLVMTypeRef LLVMInt32Type (void)
Definition at line 577 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt32TypeInContext().
LLVMInt32TypeInContext()
LLVMTypeRef LLVMInt32TypeInContext (LLVMContextRef C)
Definition at line 555 of file Core.cpp.
References llvm::Type::getInt32Ty(), and llvm::unwrap().
Referenced by LLVMInt32Type().
LLVMInt64Type()
LLVMTypeRef LLVMInt64Type (void)
Definition at line 580 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt64TypeInContext().
LLVMInt64TypeInContext()
LLVMTypeRef LLVMInt64TypeInContext (LLVMContextRef C)
Definition at line 558 of file Core.cpp.
References llvm::Type::getInt64Ty(), and llvm::unwrap().
Referenced by LLVMInt64Type().
LLVMInt8Type()
LLVMTypeRef LLVMInt8Type (void)
Definition at line 571 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt8TypeInContext().
LLVMInt8TypeInContext()
LLVMTypeRef LLVMInt8TypeInContext (LLVMContextRef C)
Definition at line 549 of file Core.cpp.
References llvm::Type::getInt8Ty(), and llvm::unwrap().
Referenced by LLVMInt8Type().
LLVMIntType()
LLVMTypeRef LLVMIntType (unsigned NumBits)
Definition at line 586 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMIntTypeInContext().
LLVMIntTypeInContext()
LLVMTypeRef LLVMIntTypeInContext (LLVMContextRef C, unsigned NumBits)
Definition at line 564 of file Core.cpp.
References llvm::IntegerType::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMIntType().