LLVM: Scalar transformations
Scalar transformations
LLVM-C: C interface to LLVM » Transforms
Functions
void LLVMAddAggressiveDCEPass (LLVMPassManagerRef PM)
See llvm::createAggressiveDCEPass function.
void LLVMAddDCEPass (LLVMPassManagerRef PM)
See llvm::createDeadCodeEliminationPass function.
void LLVMAddBitTrackingDCEPass (LLVMPassManagerRef PM)
See llvm::createBitTrackingDCEPass function.
void LLVMAddAlignmentFromAssumptionsPass (LLVMPassManagerRef PM)
See llvm::createAlignmentFromAssumptionsPass function.
void LLVMAddCFGSimplificationPass (LLVMPassManagerRef PM)
See llvm::createCFGSimplificationPass function.
void LLVMAddDeadStoreEliminationPass (LLVMPassManagerRef PM)
See llvm::createDeadStoreEliminationPass function.
void LLVMAddScalarizerPass (LLVMPassManagerRef PM)
See llvm::createScalarizerPass function.
void LLVMAddMergedLoadStoreMotionPass (LLVMPassManagerRef PM)
See llvm::createMergedLoadStoreMotionPass function.
void LLVMAddGVNPass (LLVMPassManagerRef PM)
See llvm::createGVNPass function.
void LLVMAddNewGVNPass (LLVMPassManagerRef PM)
See llvm::createGVNPass function.
void LLVMAddIndVarSimplifyPass (LLVMPassManagerRef PM)
See llvm::createIndVarSimplifyPass function.
void LLVMAddInstructionCombiningPass (LLVMPassManagerRef PM)
See llvm::createInstructionCombiningPass function.
void LLVMAddJumpThreadingPass (LLVMPassManagerRef PM)
See llvm::createJumpThreadingPass function.
void LLVMAddLICMPass (LLVMPassManagerRef PM)
See llvm::createLICMPass function.
void LLVMAddLoopDeletionPass (LLVMPassManagerRef PM)
See llvm::createLoopDeletionPass function.
void LLVMAddLoopIdiomPass (LLVMPassManagerRef PM)
See llvm::createLoopIdiomPass function.
void LLVMAddLoopRotatePass (LLVMPassManagerRef PM)
See llvm::createLoopRotatePass function.
void LLVMAddLoopRerollPass (LLVMPassManagerRef PM)
See llvm::createLoopRerollPass function.
void LLVMAddLoopUnrollPass (LLVMPassManagerRef PM)
See llvm::createLoopUnrollPass function.
void LLVMAddLoopUnrollAndJamPass (LLVMPassManagerRef PM)
See llvm::createLoopUnrollAndJamPass function.
void LLVMAddLoopUnswitchPass (LLVMPassManagerRef PM)
See llvm::createLoopUnswitchPass function.
void LLVMAddLowerAtomicPass (LLVMPassManagerRef PM)
See llvm::createLowerAtomicPass function.
void LLVMAddMemCpyOptPass (LLVMPassManagerRef PM)
See llvm::createMemCpyOptPass function.
void LLVMAddPartiallyInlineLibCallsPass (LLVMPassManagerRef PM)
See llvm::createPartiallyInlineLibCallsPass function.
void LLVMAddReassociatePass (LLVMPassManagerRef PM)
See llvm::createReassociatePass function.
void LLVMAddSCCPPass (LLVMPassManagerRef PM)
See llvm::createSCCPPass function.
void LLVMAddScalarReplAggregatesPass (LLVMPassManagerRef PM)
See llvm::createSROAPass function.
void LLVMAddScalarReplAggregatesPassSSA (LLVMPassManagerRef PM)
See llvm::createSROAPass function.
void LLVMAddScalarReplAggregatesPassWithThreshold (LLVMPassManagerRef PM, int Threshold)
See llvm::createSROAPass function.
void LLVMAddSimplifyLibCallsPass (LLVMPassManagerRef PM)
See llvm::createSimplifyLibCallsPass function.
void LLVMAddTailCallEliminationPass (LLVMPassManagerRef PM)
See llvm::createTailCallEliminationPass function.
void LLVMAddConstantPropagationPass (LLVMPassManagerRef PM)
See llvm::createConstantPropagationPass function.
void LLVMAddDemoteMemoryToRegisterPass (LLVMPassManagerRef PM)
See llvm::demotePromoteMemoryToRegisterPass function.
void LLVMAddVerifierPass (LLVMPassManagerRef PM)
See llvm::createVerifierPass function.
void LLVMAddCorrelatedValuePropagationPass (LLVMPassManagerRef PM)
See llvm::createCorrelatedValuePropagationPass function.
void LLVMAddEarlyCSEPass (LLVMPassManagerRef PM)
See llvm::createEarlyCSEPass function.
void LLVMAddEarlyCSEMemSSAPass (LLVMPassManagerRef PM)
See llvm::createEarlyCSEPass function.
void LLVMAddLowerExpectIntrinsicPass (LLVMPassManagerRef PM)
See llvm::createLowerExpectIntrinsicPass function.
void LLVMAddLowerConstantIntrinsicsPass (LLVMPassManagerRef PM)
See llvm::createLowerConstantIntrinsicsPass function.
void LLVMAddTypeBasedAliasAnalysisPass (LLVMPassManagerRef PM)
See llvm::createTypeBasedAliasAnalysisPass function.
void LLVMAddScopedNoAliasAAPass (LLVMPassManagerRef PM)
See llvm::createScopedNoAliasAAPass function.
void LLVMAddBasicAliasAnalysisPass (LLVMPassManagerRef PM)
See llvm::createBasicAliasAnalysisPass function.
void LLVMAddUnifyFunctionExitNodesPass (LLVMPassManagerRef PM)
See llvm::createUnifyFunctionExitNodesPass function.
Detailed Description
Function Documentation
LLVMAddAggressiveDCEPass()
void LLVMAddAggressiveDCEPass (LLVMPassManagerRef PM)
See llvm::createAggressiveDCEPass function.
Definition at line 125 of file Scalar.cpp.
References llvm::createAggressiveDCEPass(), and llvm::unwrap().
LLVMAddAlignmentFromAssumptionsPass()
void LLVMAddAlignmentFromAssumptionsPass (LLVMPassManagerRef PM)
See llvm::createAlignmentFromAssumptionsPass function.
Definition at line 137 of file Scalar.cpp.
References llvm::createAlignmentFromAssumptionsPass(), and llvm::unwrap().
LLVMAddBasicAliasAnalysisPass()
void LLVMAddBasicAliasAnalysisPass (LLVMPassManagerRef PM)
See llvm::createBasicAliasAnalysisPass function.
Definition at line 286 of file Scalar.cpp.
References llvm::createBasicAAWrapperPass(), and llvm::unwrap().
LLVMAddBitTrackingDCEPass()
void LLVMAddBitTrackingDCEPass (LLVMPassManagerRef PM)
See llvm::createBitTrackingDCEPass function.
Definition at line 133 of file Scalar.cpp.
References llvm::createBitTrackingDCEPass(), and llvm::unwrap().
LLVMAddCFGSimplificationPass()
void LLVMAddCFGSimplificationPass (LLVMPassManagerRef PM)
See llvm::createCFGSimplificationPass function.
Definition at line 141 of file Scalar.cpp.
References llvm::createCFGSimplificationPass(), and llvm::unwrap().
LLVMAddConstantPropagationPass()
void LLVMAddConstantPropagationPass (LLVMPassManagerRef PM)
See llvm::createConstantPropagationPass function.
Definition at line 250 of file Scalar.cpp.
References llvm::createConstantPropagationPass(), and llvm::unwrap().
LLVMAddCorrelatedValuePropagationPass()
void LLVMAddCorrelatedValuePropagationPass (LLVMPassManagerRef PM)
See llvm::createCorrelatedValuePropagationPass function.
Definition at line 262 of file Scalar.cpp.
References llvm::createCorrelatedValuePropagationPass(), and llvm::unwrap().
LLVMAddDCEPass()
void LLVMAddDCEPass (LLVMPassManagerRef PM)
See llvm::createDeadCodeEliminationPass function.
Definition at line 129 of file Scalar.cpp.
References llvm::createDeadCodeEliminationPass(), and llvm::unwrap().
LLVMAddDeadStoreEliminationPass()
void LLVMAddDeadStoreEliminationPass (LLVMPassManagerRef PM)
See llvm::createDeadStoreEliminationPass function.
Definition at line 145 of file Scalar.cpp.
References llvm::createDeadStoreEliminationPass(), and llvm::unwrap().
LLVMAddDemoteMemoryToRegisterPass()
void LLVMAddDemoteMemoryToRegisterPass (LLVMPassManagerRef PM)
See llvm::demotePromoteMemoryToRegisterPass function.
Definition at line 254 of file Scalar.cpp.
References llvm::createDemoteRegisterToMemoryPass(), and llvm::unwrap().
LLVMAddEarlyCSEMemSSAPass()
void LLVMAddEarlyCSEMemSSAPass (LLVMPassManagerRef PM)
See llvm::createEarlyCSEPass function.
Definition at line 270 of file Scalar.cpp.
References llvm::createEarlyCSEPass(), and llvm::unwrap().
LLVMAddEarlyCSEPass()
void LLVMAddEarlyCSEPass (LLVMPassManagerRef PM)
See llvm::createEarlyCSEPass function.
Definition at line 266 of file Scalar.cpp.
References llvm::createEarlyCSEPass(), and llvm::unwrap().
LLVMAddGVNPass()
void LLVMAddGVNPass (LLVMPassManagerRef PM)
See llvm::createGVNPass function.
Definition at line 153 of file Scalar.cpp.
References llvm::createGVNPass(), and llvm::unwrap().
LLVMAddIndVarSimplifyPass()
void LLVMAddIndVarSimplifyPass (LLVMPassManagerRef PM)
See llvm::createIndVarSimplifyPass function.
Definition at line 165 of file Scalar.cpp.
References llvm::createIndVarSimplifyPass(), and llvm::unwrap().
LLVMAddInstructionCombiningPass()
void LLVMAddInstructionCombiningPass (LLVMPassManagerRef PM)
See llvm::createInstructionCombiningPass function.
Definition at line 3752 of file InstructionCombining.cpp.
References llvm::createInstructionCombiningPass(), and llvm::unwrap().
LLVMAddJumpThreadingPass()
void LLVMAddJumpThreadingPass (LLVMPassManagerRef PM)
See llvm::createJumpThreadingPass function.
Definition at line 169 of file Scalar.cpp.
References llvm::createJumpThreadingPass(), and llvm::unwrap().
LLVMAddLICMPass()
void LLVMAddLICMPass (LLVMPassManagerRef PM)
See llvm::createLICMPass function.
Definition at line 177 of file Scalar.cpp.
References llvm::createLICMPass(), and llvm::unwrap().
LLVMAddLoopDeletionPass()
void LLVMAddLoopDeletionPass (LLVMPassManagerRef PM)
See llvm::createLoopDeletionPass function.
Definition at line 181 of file Scalar.cpp.
References llvm::createLoopDeletionPass(), and llvm::unwrap().
LLVMAddLoopIdiomPass()
void LLVMAddLoopIdiomPass (LLVMPassManagerRef PM)
See llvm::createLoopIdiomPass function.
Definition at line 185 of file Scalar.cpp.
References llvm::createLoopIdiomPass(), and llvm::unwrap().
LLVMAddLoopRerollPass()
void LLVMAddLoopRerollPass (LLVMPassManagerRef PM)
See llvm::createLoopRerollPass function.
Definition at line 193 of file Scalar.cpp.
References llvm::createLoopRerollPass(), and llvm::unwrap().
LLVMAddLoopRotatePass()
void LLVMAddLoopRotatePass (LLVMPassManagerRef PM)
See llvm::createLoopRotatePass function.
Definition at line 189 of file Scalar.cpp.
References llvm::createLoopRotatePass(), and llvm::unwrap().
LLVMAddLoopUnrollAndJamPass()
void LLVMAddLoopUnrollAndJamPass (LLVMPassManagerRef PM)
See llvm::createLoopUnrollAndJamPass function.
Definition at line 201 of file Scalar.cpp.
References llvm::createLoopUnrollAndJamPass(), and llvm::unwrap().
LLVMAddLoopUnrollPass()
void LLVMAddLoopUnrollPass (LLVMPassManagerRef PM)
See llvm::createLoopUnrollPass function.
Definition at line 197 of file Scalar.cpp.
References llvm::createLoopUnrollPass(), and llvm::unwrap().
LLVMAddLoopUnswitchPass()
void LLVMAddLoopUnswitchPass (LLVMPassManagerRef PM)
See llvm::createLoopUnswitchPass function.
Definition at line 205 of file Scalar.cpp.
References llvm::createLoopUnswitchPass(), and llvm::unwrap().
LLVMAddLowerAtomicPass()
void LLVMAddLowerAtomicPass (LLVMPassManagerRef PM)
See llvm::createLowerAtomicPass function.
Definition at line 209 of file Scalar.cpp.
References llvm::createLowerAtomicPass(), and llvm::unwrap().
LLVMAddLowerConstantIntrinsicsPass()
void LLVMAddLowerConstantIntrinsicsPass (LLVMPassManagerRef PM)
See llvm::createLowerConstantIntrinsicsPass function.
Definition at line 290 of file Scalar.cpp.
References llvm::createLowerConstantIntrinsicsPass(), and llvm::unwrap().
LLVMAddLowerExpectIntrinsicPass()
void LLVMAddLowerExpectIntrinsicPass (LLVMPassManagerRef PM)
See llvm::createLowerExpectIntrinsicPass function.
Definition at line 294 of file Scalar.cpp.
References llvm::createLowerExpectIntrinsicPass(), and llvm::unwrap().
LLVMAddMemCpyOptPass()
void LLVMAddMemCpyOptPass (LLVMPassManagerRef PM)
See llvm::createMemCpyOptPass function.
Definition at line 213 of file Scalar.cpp.
References llvm::createMemCpyOptPass(), and llvm::unwrap().
LLVMAddMergedLoadStoreMotionPass()
void LLVMAddMergedLoadStoreMotionPass (LLVMPassManagerRef PM)
See llvm::createMergedLoadStoreMotionPass function.
Definition at line 161 of file Scalar.cpp.
References llvm::createMergedLoadStoreMotionPass(), and llvm::unwrap().
LLVMAddNewGVNPass()
void LLVMAddNewGVNPass (LLVMPassManagerRef PM)
See llvm::createGVNPass function.
Definition at line 157 of file Scalar.cpp.
References llvm::createNewGVNPass(), and llvm::unwrap().
LLVMAddPartiallyInlineLibCallsPass()
void LLVMAddPartiallyInlineLibCallsPass (LLVMPassManagerRef PM)
See llvm::createPartiallyInlineLibCallsPass function.
Definition at line 217 of file Scalar.cpp.
References llvm::createPartiallyInlineLibCallsPass(), and llvm::unwrap().
LLVMAddReassociatePass()
void LLVMAddReassociatePass (LLVMPassManagerRef PM)
See llvm::createReassociatePass function.
Definition at line 221 of file Scalar.cpp.
References llvm::createReassociatePass(), and llvm::unwrap().
LLVMAddScalarizerPass()
void LLVMAddScalarizerPass (LLVMPassManagerRef PM)
See llvm::createScalarizerPass function.
Definition at line 149 of file Scalar.cpp.
References llvm::createScalarizerPass(), and llvm::unwrap().
LLVMAddScalarReplAggregatesPass()
void LLVMAddScalarReplAggregatesPass (LLVMPassManagerRef PM)
See llvm::createSROAPass function.
Definition at line 229 of file Scalar.cpp.
References llvm::createSROAPass(), and llvm::unwrap().
LLVMAddScalarReplAggregatesPassSSA()
void LLVMAddScalarReplAggregatesPassSSA (LLVMPassManagerRef PM)
See llvm::createSROAPass function.
Definition at line 233 of file Scalar.cpp.
References llvm::createSROAPass(), and llvm::unwrap().
LLVMAddScalarReplAggregatesPassWithThreshold()
void LLVMAddScalarReplAggregatesPassWithThreshold (LLVMPassManagerRef PM, int Threshold)
See llvm::createSROAPass function.
Definition at line 237 of file Scalar.cpp.
References llvm::createSROAPass(), and llvm::unwrap().
LLVMAddSCCPPass()
void LLVMAddSCCPPass (LLVMPassManagerRef PM)
See llvm::createSCCPPass function.
Definition at line 225 of file Scalar.cpp.
References llvm::createSCCPPass(), and llvm::unwrap().
LLVMAddScopedNoAliasAAPass()
void LLVMAddScopedNoAliasAAPass (LLVMPassManagerRef PM)
See llvm::createScopedNoAliasAAPass function.
Definition at line 282 of file Scalar.cpp.
References llvm::createScopedNoAliasAAWrapperPass(), and llvm::unwrap().
LLVMAddSimplifyLibCallsPass()
void LLVMAddSimplifyLibCallsPass (LLVMPassManagerRef PM)
See llvm::createSimplifyLibCallsPass function.
Definition at line 242 of file Scalar.cpp.
LLVMAddTailCallEliminationPass()
void LLVMAddTailCallEliminationPass (LLVMPassManagerRef PM)
See llvm::createTailCallEliminationPass function.
Definition at line 246 of file Scalar.cpp.
References llvm::createTailCallEliminationPass(), and llvm::unwrap().
LLVMAddTypeBasedAliasAnalysisPass()
void LLVMAddTypeBasedAliasAnalysisPass (LLVMPassManagerRef PM)
See llvm::createTypeBasedAliasAnalysisPass function.
Definition at line 278 of file Scalar.cpp.
References llvm::createTypeBasedAAWrapperPass(), and llvm::unwrap().
LLVMAddUnifyFunctionExitNodesPass()
void LLVMAddUnifyFunctionExitNodesPass (LLVMPassManagerRef PM)
See llvm::createUnifyFunctionExitNodesPass function.
Definition at line 298 of file Scalar.cpp.
References llvm::createUnifyFunctionExitNodesPass(), and llvm::unwrap().
LLVMAddVerifierPass()
void LLVMAddVerifierPass (LLVMPassManagerRef PM)
See llvm::createVerifierPass function.
Definition at line 258 of file Scalar.cpp.
References llvm::createVerifierPass(), and llvm::unwrap().