LLVM: Interprocedural transformations
Interprocedural transformations
LLVM-C: C interface to LLVM » Transforms
Functions
void LLVMAddArgumentPromotionPass (LLVMPassManagerRef PM)
See llvm::createArgumentPromotionPass function.
void LLVMAddConstantMergePass (LLVMPassManagerRef PM)
See llvm::createConstantMergePass function.
void LLVMAddMergeFunctionsPass (LLVMPassManagerRef PM)
See llvm::createMergeFunctionsPass function.
void LLVMAddCalledValuePropagationPass (LLVMPassManagerRef PM)
See llvm::createCalledValuePropagationPass function.
void LLVMAddDeadArgEliminationPass (LLVMPassManagerRef PM)
See llvm::createDeadArgEliminationPass function.
void LLVMAddFunctionAttrsPass (LLVMPassManagerRef PM)
See llvm::createFunctionAttrsPass function.
void LLVMAddFunctionInliningPass (LLVMPassManagerRef PM)
See llvm::createFunctionInliningPass function.
void LLVMAddAlwaysInlinerPass (LLVMPassManagerRef PM)
See llvm::createAlwaysInlinerPass function.
void LLVMAddGlobalDCEPass (LLVMPassManagerRef PM)
See llvm::createGlobalDCEPass function.
void LLVMAddGlobalOptimizerPass (LLVMPassManagerRef PM)
See llvm::createGlobalOptimizerPass function.
void LLVMAddIPConstantPropagationPass (LLVMPassManagerRef PM)
See llvm::createIPConstantPropagationPass function.
void LLVMAddPruneEHPass (LLVMPassManagerRef PM)
See llvm::createPruneEHPass function.
void LLVMAddIPSCCPPass (LLVMPassManagerRef PM)
See llvm::createIPSCCPPass function.
void LLVMAddInternalizePass (LLVMPassManagerRef, unsigned AllButMain)
See llvm::createInternalizePass function.
void LLVMAddInternalizePassWithMustPreservePredicate (LLVMPassManagerRef PM, void *Context, LLVMBool(*MustPreserve)(LLVMValueRef, void *))
Create and add the internalize pass to the given pass manager with the provided preservation callback.
void LLVMAddStripDeadPrototypesPass (LLVMPassManagerRef PM)
See llvm::createStripDeadPrototypesPass function.
void LLVMAddStripSymbolsPass (LLVMPassManagerRef PM)
See llvm::createStripSymbolsPass function.
Detailed Description
Function Documentation
LLVMAddAlwaysInlinerPass()
void LLVMAddAlwaysInlinerPass (LLVMPassManagerRef PM)
See llvm::createAlwaysInlinerPass function.
Definition at line 93 of file IPO.cpp.
References llvm::createAlwaysInlinerLegacyPass(), and llvm::unwrap().
LLVMAddArgumentPromotionPass()
void LLVMAddArgumentPromotionPass (LLVMPassManagerRef PM)
See llvm::createArgumentPromotionPass function.
Definition at line 69 of file IPO.cpp.
References llvm::createArgumentPromotionPass(), and llvm::unwrap().
LLVMAddCalledValuePropagationPass()
void LLVMAddCalledValuePropagationPass (LLVMPassManagerRef PM)
See llvm::createCalledValuePropagationPass function.
Definition at line 73 of file IPO.cpp.
References llvm::createCalledValuePropagationPass(), and llvm::unwrap().
LLVMAddConstantMergePass()
void LLVMAddConstantMergePass (LLVMPassManagerRef PM)
See llvm::createConstantMergePass function.
Definition at line 77 of file IPO.cpp.
References llvm::createConstantMergePass(), and llvm::unwrap().
LLVMAddDeadArgEliminationPass()
void LLVMAddDeadArgEliminationPass (LLVMPassManagerRef PM)
See llvm::createDeadArgEliminationPass function.
Definition at line 81 of file IPO.cpp.
References llvm::createDeadArgEliminationPass(), and llvm::unwrap().
LLVMAddFunctionAttrsPass()
void LLVMAddFunctionAttrsPass (LLVMPassManagerRef PM)
See llvm::createFunctionAttrsPass function.
Definition at line 85 of file IPO.cpp.
References llvm::createPostOrderFunctionAttrsLegacyPass(), and llvm::unwrap().
LLVMAddFunctionInliningPass()
void LLVMAddFunctionInliningPass (LLVMPassManagerRef PM)
See llvm::createFunctionInliningPass function.
Definition at line 89 of file IPO.cpp.
References llvm::createFunctionInliningPass(), and llvm::unwrap().
LLVMAddGlobalDCEPass()
void LLVMAddGlobalDCEPass (LLVMPassManagerRef PM)
See llvm::createGlobalDCEPass function.
Definition at line 97 of file IPO.cpp.
References llvm::createGlobalDCEPass(), and llvm::unwrap().
LLVMAddGlobalOptimizerPass()
void LLVMAddGlobalOptimizerPass (LLVMPassManagerRef PM)
See llvm::createGlobalOptimizerPass function.
Definition at line 101 of file IPO.cpp.
References llvm::createGlobalOptimizerPass(), and llvm::unwrap().
LLVMAddInternalizePass()
void LLVMAddInternalizePass (LLVMPassManagerRef , unsigned AllButMain)
See llvm::createInternalizePass function.
Definition at line 121 of file IPO.cpp.
References llvm::createInternalizePass(), and llvm::unwrap().
LLVMAddInternalizePassWithMustPreservePredicate()
void LLVMAddInternalizePassWithMustPreservePredicate (LLVMPassManagerRef PM, void * Context, LLVMBool(*)(LLVMValueRef, void *) MustPreserve)
Create and add the internalize pass to the given pass manager with the provided preservation callback.
The context parameter is forwarded to the callback on each invocation. As such, it is the responsibility of the caller to extend its lifetime until execution of this pass has finished.
See also
llvm::createInternalizePass function.
Definition at line 128 of file IPO.cpp.
References llvm::createInternalizePass(), false, llvm::unwrap(), and llvm::wrap().
LLVMAddIPConstantPropagationPass()
void LLVMAddIPConstantPropagationPass (LLVMPassManagerRef PM)
See llvm::createIPConstantPropagationPass function.
Definition at line 105 of file IPO.cpp.
References llvm::createIPConstantPropagationPass(), and llvm::unwrap().
LLVMAddIPSCCPPass()
void LLVMAddIPSCCPPass (LLVMPassManagerRef PM)
See llvm::createIPSCCPPass function.
Definition at line 113 of file IPO.cpp.
References llvm::createIPSCCPPass(), and llvm::unwrap().
LLVMAddMergeFunctionsPass()
void LLVMAddMergeFunctionsPass (LLVMPassManagerRef PM)
See llvm::createMergeFunctionsPass function.
Definition at line 117 of file IPO.cpp.
References llvm::createMergeFunctionsPass(), and llvm::unwrap().
LLVMAddPruneEHPass()
void LLVMAddPruneEHPass (LLVMPassManagerRef PM)
See llvm::createPruneEHPass function.
Definition at line 109 of file IPO.cpp.
References llvm::createPruneEHPass(), and llvm::unwrap().
LLVMAddStripDeadPrototypesPass()
void LLVMAddStripDeadPrototypesPass (LLVMPassManagerRef PM)
See llvm::createStripDeadPrototypesPass function.
Definition at line 137 of file IPO.cpp.
References llvm::createStripDeadPrototypesPass(), and llvm::unwrap().
LLVMAddStripSymbolsPass()
void LLVMAddStripSymbolsPass (LLVMPassManagerRef PM)
See llvm::createStripSymbolsPass function.
Definition at line 141 of file IPO.cpp.
References llvm::createStripSymbolsPass(), and llvm::unwrap().