LLVM: Modules
Modules
LLVM-C: C interface to LLVM » Core
Modules represent the top-level structure in an LLVM program.
Functions
LLVMModuleRef LLVMModuleCreateWithName (const char *ModuleID)
Create a new, empty module in the global context.
LLVMModuleRef LLVMModuleCreateWithNameInContext (const char *ModuleID, LLVMContextRef C)
Create a new, empty module in a specific context.
LLVMModuleRef LLVMCloneModule (LLVMModuleRef M)
Return an exact copy of the specified module.
void LLVMDisposeModule (LLVMModuleRef M)
Destroy a module instance.
const char * LLVMGetModuleIdentifier (LLVMModuleRef M, size_t *Len)
Obtain the identifier of a module.
void LLVMSetModuleIdentifier (LLVMModuleRef M, const char *Ident, size_t Len)
Set the identifier of a module to a string Ident with length Len.
const char * LLVMGetSourceFileName (LLVMModuleRef M, size_t *Len)
Obtain the module's original source file name.
void LLVMSetSourceFileName (LLVMModuleRef M, const char *Name, size_t Len)
Set the original source file name of a module to a string Name with length Len.
const char * LLVMGetDataLayoutStr (LLVMModuleRef M)
Obtain the data layout for a module.
const char * LLVMGetDataLayout (LLVMModuleRef M)
void LLVMSetDataLayout (LLVMModuleRef M, const char *DataLayoutStr)
Set the data layout for a module.
const char * LLVMGetTarget (LLVMModuleRef M)
Obtain the target triple for a module.
void LLVMSetTarget (LLVMModuleRef M, const char *Triple)
Set the target triple for a module.
LLVMModuleFlagEntry * LLVMCopyModuleFlagsMetadata (LLVMModuleRef M, size_t *Len)
Returns the module flags as an array of flag-key-value triples.
void LLVMDisposeModuleFlagsMetadata (LLVMModuleFlagEntry *Entries)
Destroys module flags metadata entries.
LLVMModuleFlagBehavior LLVMModuleFlagEntriesGetFlagBehavior (LLVMModuleFlagEntry *Entries, unsigned Index)
Returns the flag behavior for a module flag entry at a specific index.
const char * LLVMModuleFlagEntriesGetKey (LLVMModuleFlagEntry *Entries, unsigned Index, size_t *Len)
Returns the key for a module flag entry at a specific index.
LLVMMetadataRef LLVMModuleFlagEntriesGetMetadata (LLVMModuleFlagEntry *Entries, unsigned Index)
Returns the metadata for a module flag entry at a specific index.
LLVMMetadataRef LLVMGetModuleFlag (LLVMModuleRef M, const char *Key, size_t KeyLen)
Add a module-level flag to the module-level flags metadata if it doesn't already exist.
void LLVMAddModuleFlag (LLVMModuleRef M, LLVMModuleFlagBehavior Behavior, const char *Key, size_t KeyLen, LLVMMetadataRef Val)
Add a module-level flag to the module-level flags metadata if it doesn't already exist.
void LLVMDumpModule (LLVMModuleRef M)
Dump a representation of a module to stderr.
LLVMBool LLVMPrintModuleToFile (LLVMModuleRef M, const char *Filename, char **ErrorMessage)
Print a representation of a module to a file.
char * LLVMPrintModuleToString (LLVMModuleRef M)
Return a string representation of the module.
const char * LLVMGetModuleInlineAsm (LLVMModuleRef M, size_t *Len)
Get inline assembly for a module.
void LLVMSetModuleInlineAsm2 (LLVMModuleRef M, const char *Asm, size_t Len)
Set inline assembly for a module.
void LLVMAppendModuleInlineAsm (LLVMModuleRef M, const char *Asm, size_t Len)
Append inline assembly to a module.
LLVMValueRef LLVMGetInlineAsm (LLVMTypeRef Ty, char *AsmString, size_t AsmStringSize, char *Constraints, size_t ConstraintsSize, LLVMBool HasSideEffects, LLVMBool IsAlignStack, LLVMInlineAsmDialect Dialect)
Create the specified uniqued inline asm string.
LLVMContextRef LLVMGetModuleContext (LLVMModuleRef M)
Obtain the context to which this module is associated.
LLVMTypeRef LLVMGetTypeByName (LLVMModuleRef M, const char *Name)
Obtain a Type from a module by its registered name.
LLVMNamedMDNodeRef LLVMGetFirstNamedMetadata (LLVMModuleRef M)
Obtain an iterator to the first NamedMDNode in a Module.
LLVMNamedMDNodeRef LLVMGetLastNamedMetadata (LLVMModuleRef M)
Obtain an iterator to the last NamedMDNode in a Module.
LLVMNamedMDNodeRef LLVMGetNextNamedMetadata (LLVMNamedMDNodeRef NamedMDNode)
Advance a NamedMDNode iterator to the next NamedMDNode.
LLVMNamedMDNodeRef LLVMGetPreviousNamedMetadata (LLVMNamedMDNodeRef NamedMDNode)
Decrement a NamedMDNode iterator to the previous NamedMDNode.
LLVMNamedMDNodeRef LLVMGetNamedMetadata (LLVMModuleRef M, const char *Name, size_t NameLen)
Retrieve a NamedMDNode with the given name, returning NULL if no such node exists.
LLVMNamedMDNodeRef LLVMGetOrInsertNamedMetadata (LLVMModuleRef M, const char *Name, size_t NameLen)
Retrieve a NamedMDNode with the given name, creating a new node if no such node exists.
const char * LLVMGetNamedMetadataName (LLVMNamedMDNodeRef NamedMD, size_t *NameLen)
Retrieve the name of a NamedMDNode.
unsigned LLVMGetNamedMetadataNumOperands (LLVMModuleRef M, const char *Name)
Obtain the number of operands for named metadata in a module.
void LLVMGetNamedMetadataOperands (LLVMModuleRef M, const char *Name, LLVMValueRef *Dest)
Obtain the named metadata operands for a module.
void LLVMAddNamedMetadataOperand (LLVMModuleRef M, const char *Name, LLVMValueRef Val)
Add an operand to named metadata.
const char * LLVMGetDebugLocDirectory (LLVMValueRef Val, unsigned *Length)
Return the directory of the debug location for this value, which must be an llvm::Instruction, llvm::GlobalVariable, or llvm::Function.
const char * LLVMGetDebugLocFilename (LLVMValueRef Val, unsigned *Length)
Return the filename of the debug location for this value, which must be an llvm::Instruction, llvm::GlobalVariable, or llvm::Function.
unsigned LLVMGetDebugLocLine (LLVMValueRef Val)
Return the line number of the debug location for this value, which must be an llvm::Instruction, llvm::GlobalVariable, or llvm::Function.
unsigned LLVMGetDebugLocColumn (LLVMValueRef Val)
Return the column number of the debug location for this value, which must be an llvm::Instruction.
LLVMValueRef LLVMAddFunction (LLVMModuleRef M, const char *Name, LLVMTypeRef FunctionTy)
Add a function to a module under a specified name.
LLVMValueRef LLVMGetNamedFunction (LLVMModuleRef M, const char *Name)
Obtain a Function value from a Module by its name.
LLVMValueRef LLVMGetFirstFunction (LLVMModuleRef M)
Obtain an iterator to the first Function in a Module.
LLVMValueRef LLVMGetLastFunction (LLVMModuleRef M)
Obtain an iterator to the last Function in a Module.
LLVMValueRef LLVMGetNextFunction (LLVMValueRef Fn)
Advance a Function iterator to the next Function.
LLVMValueRef LLVMGetPreviousFunction (LLVMValueRef Fn)
Decrement a Function iterator to the previous Function.
void LLVMSetModuleInlineAsm (LLVMModuleRef M, const char *Asm)
Deprecated: Use LLVMSetModuleInlineAsm2 instead.
Detailed Description
Modules represent the top-level structure in an LLVM program.
An LLVM module is effectively a translation unit or a collection of translation units merged together.
Function Documentation
LLVMAddFunction()
LLVMValueRef LLVMAddFunction (LLVMModuleRef M, const char * Name, LLVMTypeRef FunctionTy)
Add a function to a module under a specified name.
See also
llvm::Function::Create()
Definition at line 2254 of file Core.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddModuleFlag()
void LLVMAddModuleFlag (LLVMModuleRef M, LLVMModuleFlagBehavior Behavior, const char * Key, size_t KeyLen, LLVMMetadataRef Val)
Add a module-level flag to the module-level flags metadata if it doesn't already exist.
See also
Module::addModuleFlag()
Definition at line 381 of file Core.cpp.
References map_to_llvmModFlagBehavior(), and llvm::unwrap().
LLVMAddNamedMetadataOperand()
void LLVMAddNamedMetadataOperand (LLVMModuleRef M, const char * Name, LLVMValueRef Val)
Add an operand to named metadata.
See also
llvm::Module::getNamedMetadata()
llvm::MDNode::addOperand()
Definition at line 1208 of file Core.cpp.
References llvm::NamedMDNode::addOperand(), extractMDNode(), N, and llvm::unwrap().
LLVMAppendModuleInlineAsm()
void LLVMAppendModuleInlineAsm (LLVMModuleRef M, const char * Asm, size_t Len)
Append inline assembly to a module.
See also
Module::appendModuleInlineAsm()
Definition at line 436 of file Core.cpp.
References llvm::unwrap().
LLVMCloneModule()
LLVMModuleRef LLVMCloneModule (LLVMModuleRef M)
Return an exact copy of the specified module.
Definition at line 210 of file CloneModule.cpp.
References llvm::CloneModule(), llvm::release, llvm::unwrap(), and llvm::wrap().
LLVMCopyModuleFlagsMetadata()
LLVMModuleFlagEntry* LLVMCopyModuleFlagsMetadata (LLVMModuleRef M, size_t * Len)
Returns the module flags as an array of flag-key-value triples.
The caller is responsible for freeing this array by calling LLVMDisposeModuleFlagsMetadata.
See also
Module::getModuleFlagsMetadata()
Definition at line 332 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Behavior, LLVMOpaqueModuleFlagEntry::Key, LLVMOpaqueModuleFlagEntry::KeyLen, map_from_llvmModFlagBehavior(), LLVMOpaqueModuleFlagEntry::Metadata, llvm::safe_malloc(), llvm::SmallVectorBase::size(), llvm::unwrap(), and llvm::wrap().
LLVMDisposeModule()
void LLVMDisposeModule (LLVMModuleRef M)
Destroy a module instance.
This must be called for every created module or memory will be leaked.
Definition at line 239 of file Core.cpp.
References llvm::unwrap().
LLVMDisposeModuleFlagsMetadata()
void LLVMDisposeModuleFlagsMetadata (LLVMModuleFlagEntry * Entries)
Destroys module flags metadata entries.
Definition at line 349 of file Core.cpp.
LLVMDumpModule()
void LLVMDumpModule (LLVMModuleRef M)
Dump a representation of a module to stderr.
See also
Module::dump()
Definition at line 390 of file Core.cpp.
References llvm::errs(), and llvm::unwrap().
LLVMGetDataLayout()
const char* LLVMGetDataLayout (LLVMModuleRef M)
Definition at line 268 of file Core.cpp.
References LLVMGetDataLayoutStr().
LLVMGetDataLayoutStr()
const char* LLVMGetDataLayoutStr (LLVMModuleRef M)
Obtain the data layout for a module.
See also
Module::getDataLayoutStr()
LLVMGetDataLayout is DEPRECATED, as the name is not only incorrect, but match the name of another method on the module. Prefer the use of LLVMGetDataLayoutStr, which is not ambiguous.
Definition at line 264 of file Core.cpp.
References llvm::unwrap().
Referenced by LLVMGetDataLayout().
LLVMGetDebugLocColumn()
unsigned LLVMGetDebugLocColumn (LLVMValueRef Val)
Return the column number of the debug location for this value, which must be an llvm::Instruction.
See also
llvm::Instruction::getDebugLoc()
Definition at line 1288 of file Core.cpp.
References C, I, and llvm::unwrap().
LLVMGetDebugLocDirectory()
const char* LLVMGetDebugLocDirectory (LLVMValueRef Val, unsigned * Length)
Return the directory of the debug location for this value, which must be an llvm::Instruction, llvm::GlobalVariable, or llvm::Function.
See also
llvm::Instruction::getDebugLoc()
llvm::GlobalVariable::getDebugInfo()
llvm::Function::getSubprogram()
Definition at line 1218 of file Core.cpp.
References assert(), llvm::StringRef::data(), F(), I, llvm::SmallVectorBase::size(), llvm::StringRef::size(), and llvm::unwrap().
LLVMGetDebugLocFilename()
const char* LLVMGetDebugLocFilename (LLVMValueRef Val, unsigned * Length)
Return the filename of the debug location for this value, which must be an llvm::Instruction, llvm::GlobalVariable, or llvm::Function.
See also
llvm::Instruction::getDebugLoc()
llvm::GlobalVariable::getDebugInfo()
llvm::Function::getSubprogram()
Definition at line 1242 of file Core.cpp.
References assert(), llvm::StringRef::data(), F(), I, llvm::SmallVectorBase::size(), llvm::StringRef::size(), and llvm::unwrap().
LLVMGetDebugLocLine()
unsigned LLVMGetDebugLocLine (LLVMValueRef Val)
Return the line number of the debug location for this value, which must be an llvm::Instruction, llvm::GlobalVariable, or llvm::Function.
See also
llvm::Instruction::getDebugLoc()
llvm::GlobalVariable::getDebugInfo()
llvm::Function::getSubprogram()
Definition at line 1266 of file Core.cpp.
References assert(), F(), I, llvm::SmallVectorBase::size(), and llvm::unwrap().
LLVMGetFirstFunction()
LLVMValueRef LLVMGetFirstFunction (LLVMModuleRef M)
Obtain an iterator to the first Function in a Module.
See also
llvm::Module::begin()
Definition at line 2264 of file Core.cpp.
References llvm::Module::begin(), llvm::Module::end(), I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetFirstNamedMetadata()
LLVMNamedMDNodeRef LLVMGetFirstNamedMetadata (LLVMModuleRef M)
Obtain an iterator to the first NamedMDNode in a Module.
See also
llvm::Module::named_metadata_begin()
Definition at line 1130 of file Core.cpp.
References I, llvm::Mod, llvm::Module::named_metadata_begin(), llvm::Module::named_metadata_end(), llvm::unwrap(), and llvm::wrap().
LLVMGetInlineAsm()
LLVMValueRef LLVMGetInlineAsm (LLVMTypeRef Ty, char * AsmString, size_t AsmStringSize, char * Constraints, size_t ConstraintsSize, LLVMBool HasSideEffects, LLVMBool IsAlignStack, LLVMInlineAsmDialect Dialect)
Create the specified uniqued inline asm string.
See also
InlineAsm::get()
Definition at line 446 of file Core.cpp.
References llvm::InlineAsm::AD_ATT, llvm::InlineAsm::AD_Intel, llvm::InlineAsm::get(), LLVMInlineAsmDialectATT, LLVMInlineAsmDialectIntel, and llvm::wrap().
LLVMGetLastFunction()
LLVMValueRef LLVMGetLastFunction (LLVMModuleRef M)
Obtain an iterator to the last Function in a Module.
See also
llvm::Module::end()
Definition at line 2272 of file Core.cpp.
References llvm::Module::begin(), llvm::Module::end(), I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastNamedMetadata()
LLVMNamedMDNodeRef LLVMGetLastNamedMetadata (LLVMModuleRef M)
Obtain an iterator to the last NamedMDNode in a Module.
See also
llvm::Module::named_metadata_end()
Definition at line 1138 of file Core.cpp.
References I, llvm::Mod, llvm::Module::named_metadata_begin(), llvm::Module::named_metadata_end(), llvm::unwrap(), and llvm::wrap().
LLVMGetModuleContext()
LLVMContextRef LLVMGetModuleContext (LLVMModuleRef M)
Obtain the context to which this module is associated.
See also
Module::getContext()
Definition at line 468 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetModuleFlag()
LLVMMetadataRef LLVMGetModuleFlag (LLVMModuleRef M, const char * Key, size_t KeyLen)
Add a module-level flag to the module-level flags metadata if it doesn't already exist.
See also
Module::getModuleFlag()
Definition at line 376 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetModuleIdentifier()
const char* LLVMGetModuleIdentifier (LLVMModuleRef M, size_t * Len)
Obtain the identifier of a module.
Parameters
M Module to obtain identifier of
Len Out parameter which holds the length of the returned string.
Returns
The identifier of M.
See also
Module::getModuleIdentifier()
Definition at line 243 of file Core.cpp.
References llvm::unwrap().
LLVMGetModuleInlineAsm()
const char* LLVMGetModuleInlineAsm (LLVMModuleRef M, size_t * Len)
Get inline assembly for a module.
See also
Module::getModuleInlineAsm()
Definition at line 440 of file Core.cpp.
References llvm::unwrap().
LLVMGetNamedFunction()
LLVMValueRef LLVMGetNamedFunction (LLVMModuleRef M, const char * Name)
Obtain a Function value from a Module by its name.
The returned value corresponds to a llvm::Function value.
See also
llvm::Module::getFunction()
Definition at line 2260 of file Core.cpp.
References getFunction(), llvm::unwrap(), and llvm::wrap().
LLVMGetNamedMetadata()
LLVMNamedMDNodeRef LLVMGetNamedMetadata (LLVMModuleRef M, const char * Name, size_t NameLen)
Retrieve a NamedMDNode with the given name, returning NULL if no such node exists.
See also
llvm::Module::getNamedMetadata()
Definition at line 1162 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNamedMetadataName()
const char* LLVMGetNamedMetadataName (LLVMNamedMDNodeRef NamedMD, size_t * NameLen)
Retrieve the name of a NamedMDNode.
See also
llvm::NamedMDNode::getName()
Definition at line 1172 of file Core.cpp.
References llvm::StringRef::data(), llvm::NamedMDNode::getName(), and llvm::StringRef::size().
LLVMGetNamedMetadataNumOperands()
unsigned LLVMGetNamedMetadataNumOperands (LLVMModuleRef M, const char * Name)
Obtain the number of operands for named metadata in a module.
See also
llvm::Module::getNamedMetadata()
Definition at line 1191 of file Core.cpp.
References N, and llvm::unwrap().
LLVMGetNamedMetadataOperands()
void LLVMGetNamedMetadataOperands (LLVMModuleRef M, const char * Name, LLVMValueRef * Dest)
Obtain the named metadata operands for a module.
The passed LLVMValueRef pointer should refer to an array of LLVMValueRef at least LLVMGetNamedMetadataNumOperands long. This array will be populated with the LLVMValueRef instances. Each instance corresponds to a llvm::MDNode.
See also
llvm::Module::getNamedMetadata()
llvm::MDNode::getOperand()
Definition at line 1198 of file Core.cpp.
References Context, llvm::MetadataAsValue::get(), llvm::NamedMDNode::getNumOperands(), llvm::NamedMDNode::getOperand(), N, llvm::unwrap(), and llvm::wrap().
LLVMGetNextFunction()
LLVMValueRef LLVMGetNextFunction (LLVMValueRef Fn)
Advance a Function iterator to the next Function.
Returns NULL if the iterator was already at the end and there are no more functions.
Definition at line 2280 of file Core.cpp.
References llvm::Module::end(), llvm::GlobalValue::getParent(), I, and llvm::wrap().
LLVMGetNextNamedMetadata()
LLVMNamedMDNodeRef LLVMGetNextNamedMetadata (LLVMNamedMDNodeRef NamedMDNode)
Advance a NamedMDNode iterator to the next NamedMDNode.
Returns NULL if the iterator was already at the end and there are no more named metadata nodes.
Definition at line 1146 of file Core.cpp.
References llvm::NamedMDNode::getParent(), I, llvm::Module::named_metadata_end(), and llvm::wrap().
LLVMGetOrInsertNamedMetadata()
LLVMNamedMDNodeRef LLVMGetOrInsertNamedMetadata (LLVMModuleRef M, const char * Name, size_t NameLen)
Retrieve a NamedMDNode with the given name, creating a new node if no such node exists.
See also
llvm::Module::getOrInsertNamedMetadata()
Definition at line 1167 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMGetPreviousFunction()
LLVMValueRef LLVMGetPreviousFunction (LLVMValueRef Fn)
Decrement a Function iterator to the previous Function.
Returns NULL if the iterator was already at the beginning and there are no previous functions.
Definition at line 2288 of file Core.cpp.
References llvm::Module::begin(), llvm::GlobalValue::getParent(), I, and llvm::wrap().
LLVMGetPreviousNamedMetadata()
LLVMNamedMDNodeRef LLVMGetPreviousNamedMetadata (LLVMNamedMDNodeRef NamedMDNode)
Decrement a NamedMDNode iterator to the previous NamedMDNode.
Returns NULL if the iterator was already at the beginning and there are no previous named metadata nodes.
Definition at line 1154 of file Core.cpp.
References llvm::NamedMDNode::getParent(), I, llvm::Module::named_metadata_begin(), and llvm::wrap().
LLVMGetSourceFileName()
const char* LLVMGetSourceFileName (LLVMModuleRef M, size_t * Len)
Obtain the module's original source file name.
Parameters
M Module to obtain the name of
Len Out parameter which holds the length of the returned string
Returns
The original source file name of M
See also
Module::getSourceFileName()
Definition at line 253 of file Core.cpp.
References llvm::unwrap().
LLVMGetTarget()
const char* LLVMGetTarget (LLVMModuleRef M)
Obtain the target triple for a module.
See also
Module::getTargetTriple()
Definition at line 277 of file Core.cpp.
References llvm::unwrap().
LLVMGetTypeByName()
LLVMTypeRef LLVMGetTypeByName (LLVMModuleRef M, const char * Name)
Obtain a Type from a module by its registered name.
Definition at line 729 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMModuleCreateWithName()
LLVMModuleRef LLVMModuleCreateWithName (const char * ModuleID)
Create a new, empty module in the global context.
This is equivalent to calling LLVMModuleCreateWithNameInContext with LLVMGetGlobalContext() as the context parameter.
Every invocation should be paired with LLVMDisposeModule() or memory will be leaked.
Definition at line 230 of file Core.cpp.
References llvm::wrap().
LLVMModuleCreateWithNameInContext()
LLVMModuleRef LLVMModuleCreateWithNameInContext (const char * ModuleID, LLVMContextRef C)
Create a new, empty module in a specific context.
Every invocation should be paired with LLVMDisposeModule() or memory will be leaked.
Definition at line 234 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMModuleFlagEntriesGetFlagBehavior()
LLVMModuleFlagBehavior LLVMModuleFlagEntriesGetFlagBehavior (LLVMModuleFlagEntry * Entries, unsigned Index)
Returns the flag behavior for a module flag entry at a specific index.
See also
Module::ModuleFlagEntry::Behavior
Definition at line 354 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Behavior.
LLVMModuleFlagEntriesGetKey()
const char* LLVMModuleFlagEntriesGetKey (LLVMModuleFlagEntry * Entries, unsigned Index, size_t * Len)
Returns the key for a module flag entry at a specific index.
See also
Module::ModuleFlagEntry::Key
Definition at line 361 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Key, and LLVMOpaqueModuleFlagEntry::KeyLen.
LLVMModuleFlagEntriesGetMetadata()
LLVMMetadataRef LLVMModuleFlagEntriesGetMetadata (LLVMModuleFlagEntry * Entries, unsigned Index)
Returns the metadata for a module flag entry at a specific index.
See also
Module::ModuleFlagEntry::Val
Definition at line 369 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Metadata.
LLVMPrintModuleToFile()
LLVMBool LLVMPrintModuleToFile (LLVMModuleRef M, const char * Filename, char ** ErrorMessage)
Print a representation of a module to a file.
The ErrorMessage needs to be disposed with LLVMDisposeMessage. Returns 0 on success, 1 otherwise.
See also
Module::print()
Definition at line 395 of file Core.cpp.
References llvm::raw_fd_ostream::close(), E, llvm::raw_fd_ostream::error(), llvm::raw_fd_ostream::has_error(), llvm::sys::fs::OF_Text, and llvm::unwrap().
LLVMPrintModuleToString()
char* LLVMPrintModuleToString (LLVMModuleRef M)
Return a string representation of the module.
Use LLVMDisposeMessage to free the string.
See also
Module::print()
Definition at line 417 of file Core.cpp.
References llvm::raw_ostream::flush(), and llvm::unwrap().
LLVMSetDataLayout()
void LLVMSetDataLayout (LLVMModuleRef M, const char * DataLayoutStr)
Set the data layout for a module.
See also
Module::setDataLayout()
Definition at line 272 of file Core.cpp.
References llvm::unwrap().
LLVMSetModuleIdentifier()
void LLVMSetModuleIdentifier (LLVMModuleRef M, const char * Ident, size_t Len)
Set the identifier of a module to a string Ident with length Len.
Parameters
M The module to set identifier
Ident The string to set M's identifier to
Len Length of Ident
See also
Module::setModuleIdentifier()
Definition at line 249 of file Core.cpp.
References llvm::unwrap().
LLVMSetModuleInlineAsm()
void LLVMSetModuleInlineAsm (LLVMModuleRef M, const char * Asm)
Deprecated: Use LLVMSetModuleInlineAsm2 instead.
Definition at line 432 of file Core.cpp.
References llvm::unwrap().
LLVMSetModuleInlineAsm2()
void LLVMSetModuleInlineAsm2 (LLVMModuleRef M, const char * Asm, size_t Len)
Set inline assembly for a module.
See also
Module::setModuleInlineAsm()
Definition at line 428 of file Core.cpp.
References llvm::unwrap().
LLVMSetSourceFileName()
void LLVMSetSourceFileName (LLVMModuleRef M, const char * Name, size_t Len)
Set the original source file name of a module to a string Name with length Len.
Parameters
M The module to set the source file name of
Name The string to set M's source file name to
Len Length of Name
See also
Module::setSourceFileName()
Definition at line 259 of file Core.cpp.
References llvm::unwrap().
LLVMSetTarget()
void LLVMSetTarget (LLVMModuleRef M, const char * Triple)
Set the target triple for a module.
See also
Module::setTargetTriple()
Definition at line 281 of file Core.cpp.
References llvm::unwrap().