LLVM: Terminators
Terminators
LLVM-C: C interface to LLVM » Core » Instructions
Functions in this group only apply to instructions for which LLVMIsATerminatorInst returns true.
Functions
unsigned LLVMGetNumSuccessors (LLVMValueRef Term)
Return the number of successors that this terminator has.
LLVMBasicBlockRef LLVMGetSuccessor (LLVMValueRef Term, unsigned i)
Return the specified successor.
void LLVMSetSuccessor (LLVMValueRef Term, unsigned i, LLVMBasicBlockRef block)
Update the specified successor to point at the provided block.
LLVMBool LLVMIsConditional (LLVMValueRef Branch)
Return if a branch is conditional.
LLVMValueRef LLVMGetCondition (LLVMValueRef Branch)
Return the condition of a branch instruction.
void LLVMSetCondition (LLVMValueRef Branch, LLVMValueRef Cond)
Set the condition of a branch instruction.
LLVMBasicBlockRef LLVMGetSwitchDefaultDest (LLVMValueRef SwitchInstr)
Obtain the default destination basic block of a switch instruction.
Detailed Description
Functions in this group only apply to instructions for which LLVMIsATerminatorInst returns true.
Function Documentation
LLVMGetCondition()
LLVMValueRef LLVMGetCondition (LLVMValueRef Branch)
Return the condition of a branch instruction.
This only works on llvm::BranchInst instructions.
See also
llvm::BranchInst::getCondition
Definition at line 2905 of file Core.cpp.
References llvm::wrap().
LLVMGetNumSuccessors()
unsigned LLVMGetNumSuccessors (LLVMValueRef Term)
Return the number of successors that this terminator has.
See also
llvm::Instruction::getNumSuccessors
Definition at line 2887 of file Core.cpp.
LLVMGetSuccessor()
LLVMBasicBlockRef LLVMGetSuccessor (LLVMValueRef Term, unsigned i)
Return the specified successor.
See also
llvm::Instruction::getSuccessor
Definition at line 2891 of file Core.cpp.
References llvm::wrap().
LLVMGetSwitchDefaultDest()
LLVMBasicBlockRef LLVMGetSwitchDefaultDest (LLVMValueRef SwitchInstr)
Obtain the default destination basic block of a switch instruction.
This only works on llvm::SwitchInst instructions.
See also
llvm::SwitchInst::getDefaultDest()
Definition at line 2915 of file Core.cpp.
References llvm::wrap().
LLVMIsConditional()
LLVMBool LLVMIsConditional (LLVMValueRef Branch)
Return if a branch is conditional.
This only works on llvm::BranchInst instructions.
See also
llvm::BranchInst::isConditional
Definition at line 2901 of file Core.cpp.
References llvm::MCID::Branch.
LLVMSetCondition()
void LLVMSetCondition (LLVMValueRef Branch, LLVMValueRef Cond)
Set the condition of a branch instruction.
This only works on llvm::BranchInst instructions.
See also
llvm::BranchInst::setCondition
Definition at line 2909 of file Core.cpp.
LLVMSetSuccessor()
void LLVMSetSuccessor (LLVMValueRef Term, unsigned i, LLVMBasicBlockRef block)
Update the specified successor to point at the provided block.
See also
llvm::Instruction::setSuccessor
Definition at line 2895 of file Core.cpp.
References llvm::unwrap().