LLVM: Global Variables
Global Variables
LLVM-C: C interface to LLVM » Core » Values » Constants
This group contains functions that operate on global variable values.
Functions
LLVMValueRef LLVMAddGlobal (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMAddGlobalInAddressSpace (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name, unsigned AddressSpace)
LLVMValueRef LLVMGetNamedGlobal (LLVMModuleRef M, const char *Name)
LLVMValueRef LLVMGetFirstGlobal (LLVMModuleRef M)
LLVMValueRef LLVMGetLastGlobal (LLVMModuleRef M)
LLVMValueRef LLVMGetNextGlobal (LLVMValueRef GlobalVar)
LLVMValueRef LLVMGetPreviousGlobal (LLVMValueRef GlobalVar)
void LLVMDeleteGlobal (LLVMValueRef GlobalVar)
LLVMValueRef LLVMGetInitializer (LLVMValueRef GlobalVar)
void LLVMSetInitializer (LLVMValueRef GlobalVar, LLVMValueRef ConstantVal)
LLVMBool LLVMIsThreadLocal (LLVMValueRef GlobalVar)
void LLVMSetThreadLocal (LLVMValueRef GlobalVar, LLVMBool IsThreadLocal)
LLVMBool LLVMIsGlobalConstant (LLVMValueRef GlobalVar)
void LLVMSetGlobalConstant (LLVMValueRef GlobalVar, LLVMBool IsConstant)
LLVMThreadLocalMode LLVMGetThreadLocalMode (LLVMValueRef GlobalVar)
void LLVMSetThreadLocalMode (LLVMValueRef GlobalVar, LLVMThreadLocalMode Mode)
LLVMBool LLVMIsExternallyInitialized (LLVMValueRef GlobalVar)
void LLVMSetExternallyInitialized (LLVMValueRef GlobalVar, LLVMBool IsExtInit)
Detailed Description
This group contains functions that operate on global variable values.
See also
llvm::GlobalVariable
Function Documentation
LLVMAddGlobal()
LLVMValueRef LLVMAddGlobal (LLVMModuleRef M, LLVMTypeRef Ty, const char * Name)
Definition at line 2068 of file Core.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddGlobalInAddressSpace()
LLVMValueRef LLVMAddGlobalInAddressSpace (LLVMModuleRef M, LLVMTypeRef Ty, const char * Name, unsigned AddressSpace)
Definition at line 2073 of file Core.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::NotThreadLocal, llvm::unwrap(), and llvm::wrap().
LLVMDeleteGlobal()
void LLVMDeleteGlobal (LLVMValueRef GlobalVar)
Definition at line 2118 of file Core.cpp.
References llvm::lltok::GlobalVar.
LLVMGetFirstGlobal()
LLVMValueRef LLVMGetFirstGlobal (LLVMModuleRef M)
Definition at line 2086 of file Core.cpp.
References llvm::Module::global_begin(), llvm::Module::global_end(), I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetInitializer()
LLVMValueRef LLVMGetInitializer (LLVMValueRef GlobalVar)
Definition at line 2122 of file Core.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::lltok::GlobalVar, llvm::GlobalVariable::hasInitializer(), and llvm::wrap().
LLVMGetLastGlobal()
LLVMValueRef LLVMGetLastGlobal (LLVMModuleRef M)
Definition at line 2094 of file Core.cpp.
References llvm::Module::global_begin(), llvm::Module::global_end(), I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobal()
LLVMValueRef LLVMGetNamedGlobal (LLVMModuleRef M, const char * Name)
Definition at line 2082 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNextGlobal()
LLVMValueRef LLVMGetNextGlobal (LLVMValueRef GlobalVar)
Definition at line 2102 of file Core.cpp.
References llvm::GlobalValue::getParent(), llvm::Module::global_end(), llvm::lltok::GlobalVar, I, and llvm::wrap().
LLVMGetPreviousGlobal()
LLVMValueRef LLVMGetPreviousGlobal (LLVMValueRef GlobalVar)
Definition at line 2110 of file Core.cpp.
References llvm::GlobalValue::getParent(), llvm::Module::global_begin(), llvm::lltok::GlobalVar, I, and llvm::wrap().
LLVMGetThreadLocalMode()
LLVMThreadLocalMode LLVMGetThreadLocalMode (LLVMValueRef GlobalVar)
Definition at line 2150 of file Core.cpp.
References llvm::GlobalValue::GeneralDynamicTLSModel, llvm::GlobalValue::InitialExecTLSModel, llvm_unreachable, LLVMGeneralDynamicTLSModel, LLVMInitialExecTLSModel, LLVMLocalDynamicTLSModel, LLVMLocalExecTLSModel, LLVMNotThreadLocal, llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, and llvm::GlobalValue::NotThreadLocal.
LLVMIsExternallyInitialized()
LLVMBool LLVMIsExternallyInitialized (LLVMValueRef GlobalVar)
Definition at line 2189 of file Core.cpp.
References llvm::lltok::GlobalVar.
LLVMIsGlobalConstant()
LLVMBool LLVMIsGlobalConstant (LLVMValueRef GlobalVar)
Definition at line 2142 of file Core.cpp.
References llvm::lltok::GlobalVar, and isConstant().
LLVMIsThreadLocal()
LLVMBool LLVMIsThreadLocal (LLVMValueRef GlobalVar)
Definition at line 2134 of file Core.cpp.
References llvm::lltok::GlobalVar.
LLVMSetExternallyInitialized()
void LLVMSetExternallyInitialized (LLVMValueRef GlobalVar, LLVMBool IsExtInit)
Definition at line 2193 of file Core.cpp.
References llvm::lltok::GlobalVar.
LLVMSetGlobalConstant()
void LLVMSetGlobalConstant (LLVMValueRef GlobalVar, LLVMBool IsConstant)
Definition at line 2146 of file Core.cpp.
References llvm::lltok::GlobalVar.
LLVMSetInitializer()
void LLVMSetInitializer (LLVMValueRef GlobalVar, LLVMValueRef ConstantVal)
Definition at line 2129 of file Core.cpp.
References llvm::lltok::GlobalVar.
LLVMSetThreadLocal()
void LLVMSetThreadLocal (LLVMValueRef GlobalVar, LLVMBool IsThreadLocal)
Definition at line 2138 of file Core.cpp.
References llvm::lltok::GlobalVar.
LLVMSetThreadLocalMode()
void LLVMSetThreadLocalMode (LLVMValueRef GlobalVar, LLVMThreadLocalMode Mode)
Definition at line 2167 of file Core.cpp.
References llvm::GlobalValue::GeneralDynamicTLSModel, llvm::lltok::GlobalVar, llvm::GlobalValue::InitialExecTLSModel, LLVMGeneralDynamicTLSModel, LLVMInitialExecTLSModel, LLVMLocalDynamicTLSModel, LLVMLocalExecTLSModel, LLVMNotThreadLocal, llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, llvm::GlobalValue::NotThreadLocal, and llvm::GlobalValue::setThreadLocalMode().