LLVM: Function Types
Function Types
LLVM-C: C interface to LLVM » Core » Types
Functions
LLVMTypeRef LLVMFunctionType (LLVMTypeRef ReturnType, LLVMTypeRef *ParamTypes, unsigned ParamCount, LLVMBool IsVarArg)
Obtain a function type consisting of a specified signature.
LLVMBool LLVMIsFunctionVarArg (LLVMTypeRef FunctionTy)
Returns whether a function type is variadic.
LLVMTypeRef LLVMGetReturnType (LLVMTypeRef FunctionTy)
Obtain the Type this function Type returns.
unsigned LLVMCountParamTypes (LLVMTypeRef FunctionTy)
Obtain the number of parameters this function accepts.
void LLVMGetParamTypes (LLVMTypeRef FunctionTy, LLVMTypeRef *Dest)
Obtain the types of a function's parameters.
Detailed Description
Function Documentation
LLVMCountParamTypes()
unsigned LLVMCountParamTypes (LLVMTypeRef FunctionTy)
Obtain the number of parameters this function accepts.
Definition at line 657 of file Core.cpp.
LLVMFunctionType()
LLVMTypeRef LLVMFunctionType (LLVMTypeRef ReturnType, LLVMTypeRef * ParamTypes, unsigned ParamCount, LLVMBool IsVarArg)
Obtain a function type consisting of a specified signature.
The function is defined as a tuple of a return Type, a list of parameter types, and whether the function is variadic.
Definition at line 642 of file Core.cpp.
References llvm::FunctionType::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetParamTypes()
void LLVMGetParamTypes (LLVMTypeRef FunctionTy, LLVMTypeRef * Dest)
Obtain the types of a function's parameters.
The Dest parameter should point to a pre-allocated array of LLVMTypeRef at least LLVMCountParamTypes() large. On return, the first LLVMCountParamTypes() entries in the array will be populated with LLVMTypeRef instances.
Parameters
FunctionTy The function type to operate on.
Dest Memory address of an array to be filled with result.
Definition at line 661 of file Core.cpp.
References E, I, llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), and llvm::wrap().
LLVMGetReturnType()
LLVMTypeRef LLVMGetReturnType (LLVMTypeRef FunctionTy)
Obtain the Type this function Type returns.
Definition at line 653 of file Core.cpp.
References llvm::wrap().
LLVMIsFunctionVarArg()
LLVMBool LLVMIsFunctionVarArg (LLVMTypeRef FunctionTy)
Returns whether a function type is variadic.
Definition at line 649 of file Core.cpp.