LLVM: Initialization Routines
Initialization Routines
LLVM-C: C interface to LLVM
This module contains routines used to initialize the LLVM system.
Functions
void LLVMInitializeCore (LLVMPassRegistryRef R)
void LLVMInitializeTransformUtils (LLVMPassRegistryRef R)
LLVMInitializeTransformUtils - C binding for initializeTransformUtilsPasses.
void LLVMInitializeScalarOpts (LLVMPassRegistryRef R)
void LLVMInitializeObjCARCOpts (LLVMPassRegistryRef R)
void LLVMInitializeVectorization (LLVMPassRegistryRef R)
void LLVMInitializeInstCombine (LLVMPassRegistryRef R)
void LLVMInitializeAggressiveInstCombiner (LLVMPassRegistryRef R)
void LLVMInitializeIPO (LLVMPassRegistryRef R)
void LLVMInitializeInstrumentation (LLVMPassRegistryRef R)
LLVMInitializeInstrumentation - C binding for initializeInstrumentation.
void LLVMInitializeAnalysis (LLVMPassRegistryRef R)
void LLVMInitializeIPA (LLVMPassRegistryRef R)
void LLVMInitializeCodeGen (LLVMPassRegistryRef R)
void LLVMInitializeTarget (LLVMPassRegistryRef R)
Detailed Description
This module contains routines used to initialize the LLVM system.
Function Documentation
LLVMInitializeAggressiveInstCombiner()
void LLVMInitializeAggressiveInstCombiner (LLVMPassRegistryRef R)
Definition at line 408 of file AggressiveInstCombine.cpp.
References llvm::initializeAggressiveInstCombinerLegacyPassPass(), and llvm::unwrap().
LLVMInitializeAnalysis()
void LLVMInitializeAnalysis (LLVMPassRegistryRef R)
Definition at line 90 of file Analysis.cpp.
References llvm::initializeAnalysis(), and llvm::unwrap().
LLVMInitializeCodeGen()
void LLVMInitializeCodeGen (LLVMPassRegistryRef R)
Definition at line 119 of file CodeGen.cpp.
References llvm::initializeCodeGen(), and llvm::unwrap().
LLVMInitializeCore()
void LLVMInitializeCore (LLVMPassRegistryRef R)
Definition at line 55 of file Core.cpp.
References llvm::initializeCore(), and llvm::unwrap().
LLVMInitializeInstCombine()
void LLVMInitializeInstCombine (LLVMPassRegistryRef R)
Definition at line 3739 of file InstructionCombining.cpp.
References llvm::initializeInstructionCombiningPassPass(), and llvm::unwrap().
LLVMInitializeInstrumentation()
void LLVMInitializeInstrumentation (LLVMPassRegistryRef R)
LLVMInitializeInstrumentation - C binding for initializeInstrumentation.
Definition at line 126 of file Instrumentation.cpp.
References llvm::initializeInstrumentation(), and llvm::unwrap().
LLVMInitializeIPA()
void LLVMInitializeIPA (LLVMPassRegistryRef R)
Definition at line 94 of file Analysis.cpp.
References llvm::initializeAnalysis(), and llvm::unwrap().
LLVMInitializeIPO()
void LLVMInitializeIPO (LLVMPassRegistryRef R)
Definition at line 65 of file IPO.cpp.
References llvm::initializeIPO(), and llvm::unwrap().
LLVMInitializeObjCARCOpts()
void LLVMInitializeObjCARCOpts (LLVMPassRegistryRef R)
Definition at line 37 of file ObjCARC.cpp.
References llvm::initializeObjCARCOpts(), and llvm::unwrap().
LLVMInitializeScalarOpts()
void LLVMInitializeScalarOpts (LLVMPassRegistryRef R)
Definition at line 121 of file Scalar.cpp.
References llvm::initializeScalarOpts(), and llvm::unwrap().
LLVMInitializeTarget()
void LLVMInitializeTarget (LLVMPassRegistryRef R)
Definition at line 43 of file Target.cpp.
References llvm::initializeTarget(), and llvm::unwrap().
LLVMInitializeTransformUtils()
void LLVMInitializeTransformUtils (LLVMPassRegistryRef R)
LLVMInitializeTransformUtils - C binding for initializeTransformUtilsPasses.
Definition at line 46 of file Utils.cpp.
References llvm::initializeTransformUtils(), and llvm::unwrap().
LLVMInitializeVectorization()
void LLVMInitializeVectorization (LLVMPassRegistryRef R)
Definition at line 32 of file Vectorize.cpp.
References llvm::initializeVectorization(), and llvm::unwrap().