LLVM: lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp File Reference
GSIStreamBuilder.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/DebugInfo/CodeView/RecordName.h"
#include "llvm/DebugInfo/CodeView/SymbolDeserializer.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/DebugInfo/CodeView/SymbolSerializer.h"
#include "llvm/DebugInfo/MSF/MSFBuilder.h"
#include "llvm/DebugInfo/MSF/MSFCommon.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/DebugInfo/PDB/Native/GlobalsStream.h"
#include "llvm/DebugInfo/PDB/Native/Hash.h"
#include "llvm/Support/BinaryItemStream.h"
#include "llvm/Support/BinaryStreamWriter.h"
#include "llvm/Support/xxhash.h"
#include <algorithm>
#include <vector>
Classes
struct llvm::pdb::GSIHashStreamBuilder
struct llvm::pdb::GSIHashStreamBuilder::SymbolDenseMapInfo
Functions
static bool isAsciiString (StringRef S)
static bool gsiRecordLess (StringRef S1, StringRef S2)
static bool comparePubSymByAddrAndName (const std::pair< const CVSymbol *, const PublicSym32 *> &LS, const std::pair< const CVSymbol *, const PublicSym32 *> &RS)
static std::vector< ulittle32_t > computeAddrMap (ArrayRef< CVSymbol > Records)
Compute the address map.
static Error writeRecords (BinaryStreamWriter &Writer, ArrayRef< CVSymbol > Records)
Function Documentation
comparePubSymByAddrAndName()
static bool comparePubSymByAddrAndName (const std::pair< const CVSymbol *, const PublicSym32 *> & LS, const std::pair< const CVSymbol *, const PublicSym32 *> & RS) static
Definition at line 232 of file GSIStreamBuilder.cpp.
Referenced by computeAddrMap().
computeAddrMap()
static std::vector<ulittle32_t> computeAddrMap (ArrayRef< CVSymbol > Records) static
Compute the address map.
The address map is an array of symbol offsets sorted so that it can be binary searched by address.
Definition at line 245 of file GSIStreamBuilder.cpp.
References assert(), llvm::cantFail(), comparePubSymByAddrAndName(), llvm::ArrayRef< T >::size(), and llvm::stable_sort().
Referenced by writeRecords().
gsiRecordLess()
static bool gsiRecordLess (StringRef S1, StringRef S2) static
Definition at line 118 of file GSIStreamBuilder.cpp.
References llvm::StringRef::compare_lower(), llvm::StringRef::data(), isAsciiString(), LLVM_UNLIKELY, llvm::AArch64CC::LS, memcmp, and llvm::StringRef::size().
Referenced by llvm::pdb::GSIHashStreamBuilder::finalizeBuckets().
isAsciiString()
static bool isAsciiString (StringRef S) static
Definition at line 113 of file GSIStreamBuilder.cpp.
References llvm::all_of(), and C.
Referenced by gsiRecordLess().
writeRecords()
static Error writeRecords (BinaryStreamWriter & Writer, ArrayRef< CVSymbol > Records) static
Definition at line 306 of file GSIStreamBuilder.cpp.
References llvm::pdb::PublicsStreamHeader::AddrMap, computeAddrMap(), llvm::codeview::EC, llvm::pdb::PublicsStreamHeader::ISectThunkTable, llvm::support::little, llvm::makeArrayRef(), llvm::pdb::PublicsStreamHeader::NumSections, llvm::pdb::PublicsStreamHeader::NumThunks, llvm::pdb::PublicsStreamHeader::OffThunkTable, llvm::pdb::PublicsStreamHeader::Padding, llvm::BinaryItemStream< T, Traits >::setItems(), llvm::pdb::PublicsStreamHeader::SizeOfThunk, llvm::Error::success(), llvm::pdb::PublicsStreamHeader::SymHash, llvm::BinaryStreamWriter::writeArray(), llvm::BinaryStreamWriter::writeObject(), and llvm::BinaryStreamWriter::writeStreamRef().