LLVM: lib/Target/Hexagon/HexagonSplitConst32AndConst64.cpp File Reference
HexagonSplitConst32AndConst64.cpp File Reference
#include "HexagonSubtarget.h"
#include "HexagonTargetMachine.h"
#include "HexagonTargetObjectFile.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "xfer"
Functions
FunctionPass * llvm::createHexagonSplitConst32AndConst64 ()
void llvm::initializeHexagonSplitConst32AndConst64Pass (PassRegistry &)
INITIALIZE_PASS (HexagonSplitConst32AndConst64, "split-const-for-sdata", "Hexagon Split Const32s and Const64s", false, false) bool HexagonSplitConst32AndConst64
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "xfer"
Definition at line 30 of file HexagonSplitConst32AndConst64.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonSplitConst32AndConst64 , "split-const-for-sdata" , "Hexagon Split Const32s and Const64s" , false , false)
Definition at line 58 of file HexagonSplitConst32AndConst64.cpp.
References B, llvm::BuildMI(), llvm::HexagonISD::CONST32, E, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetRegisterInfo::getSubReg(), I, MI, TII, and TRI.