LLVM: lib/Target/Hexagon/MCTargetDesc/HexagonMCDuplexInfo.cpp File Reference
HexagonMCDuplexInfo.cpp File Reference
#include "MCTargetDesc/HexagonBaseInfo.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <map>
#include <utility>
Macros
#define DEBUG_TYPE "hexagon-mcduplex-info"
Functions
static void addOps (MCInst &subInstPtr, MCInst const &Inst, unsigned opNum)
static bool isStoreInst (unsigned opCode)
Variables
static const std::pair< unsigned, unsigned > opcodeData []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-mcduplex-info"
Definition at line 33 of file HexagonMCDuplexInfo.cpp.
Function Documentation
addOps()
static void addOps (MCInst & subInstPtr, MCInst const & Inst, unsigned opNum) inline static
Definition at line 663 of file HexagonMCDuplexInfo.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm_unreachable, R2, R4, and R6.
Referenced by llvm::HexagonMCInstrInfo::deriveSubInst().
isStoreInst()
static bool isStoreInst (unsigned opCode) static
Definition at line 1019 of file HexagonMCDuplexInfo.cpp.
Referenced by llvm::HexagonMCInstrInfo::getDuplexPossibilties().
Variable Documentation
opcodeData
const std::pair<unsigned, unsigned> opcodeData[] static
Definition at line 36 of file HexagonMCDuplexInfo.cpp.
Referenced by llvm::HexagonMCInstrInfo::isOrderedDuplexPair().