LLVM: lib/Target/Hexagon/HexagonSplitDouble.cpp File Reference
HexagonSplitDouble.cpp File Reference
#include "HexagonInstrInfo.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <limits>
#include <map>
#include <set>
#include <utility>
#include <vector>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "hsdr"
Functions
FunctionPass * llvm::createHexagonSplitDoubleRegs ()
void llvm::initializeHexagonSplitDoubleRegsPass (PassRegistry &)
INITIALIZE_PASS (HexagonSplitDoubleRegs, "hexagon-split-double", "Hexagon Split Double Registers", false, false) LLVM_DUMP_METHOD void HexagonSplitDoubleRegs
static int32_t profitImm (unsigned Imm)
Variables
static cl::opt< int > MaxHSDR ("max-hsdr", cl::Hidden, cl::init(-1), cl::desc("Maximum number of split partitions"))
static cl::opt< bool > MemRefsFixed ("hsdr-no-mem", cl::Hidden, cl::init(true), cl::desc("Do not split loads or stores"))
static cl::opt< bool > SplitAll ("hsdr-split-all", cl::Hidden, cl::init(false), cl::desc("Split all partitions"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hsdr"
Definition at line 9 of file HexagonSplitDouble.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonSplitDoubleRegs , "hexagon-split-double" , "Hexagon Split Double Registers" , false , false)
Definition at line 132 of file HexagonSplitDouble.cpp.
References llvm::dbgs(), DoubleRegs, F(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), I, llvm::Register::index2VirtReg(), llvm::MachineInstr::isDebugInstr(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, llvm::MachineInstr::mayLoadOrStore(), llvm::MachineInstr::memoperands(), MI, MRI, llvm::MachineInstr::operands(), llvm::printReg(), Reg, llvm::BitVector::set(), llvm::T, TRI, llvm::Register::virtReg2Index(), and llvm::Z.
profitImm()
static int32_t profitImm (unsigned Imm) inline static
Definition at line 308 of file HexagonSplitDouble.cpp.
References assert(), D, llvm::dbgs(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::MachineOperand::getImm(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MipsISD::Hi, llvm::MachineOperand::isImm(), llvm::MachineInstr::isPHI(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, LLVM_FALLTHROUGH, llvm::MipsISD::Lo, MRI, llvm::MachineInstr::operands(), P, llvm::X86II::TB, and llvm::RISCVFenceField::W.
Variable Documentation
MaxHSDR
cl::opt<int> MaxHSDR("max-hsdr", cl::Hidden, cl::init(-1), cl::desc("Maximum number of split partitions")) static
MemRefsFixed
cl::opt<bool> MemRefsFixed("hsdr-no-mem", cl::Hidden, cl::init(true), cl::desc("Do not split loads or stores")) static
SplitAll
cl::opt<bool> SplitAll("hsdr-split-all", cl::Hidden, cl::init(false), cl::desc("Split all partitions")) static