LLVM: lib/Target/Hexagon/HexagonOptimizeSZextends.cpp File Reference
HexagonOptimizeSZextends.cpp File Reference
#include "llvm/CodeGen/StackProtector.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsHexagon.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "Hexagon.h"
Namespaces
llvm
This class represents lattice values for constants.
Functions
FunctionPass * llvm::createHexagonOptimizeSZextends ()
void llvm::initializeHexagonOptimizeSZextendsPass (PassRegistry &)
INITIALIZE_PASS (HexagonOptimizeSZextends, "reargs", "Remove Sign and Zero Extends for Args", false, false) bool HexagonOptimizeSZextends
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonOptimizeSZextends , "reargs" , "Remove Sign and Zero Extends for Args" , false , false)
Definition at line 53 of file HexagonOptimizeSZextends.cpp.
References Arg, llvm::Function::args(), assert(), B, C, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), F(), llvm::BasicBlock::front(), llvm::Function::getAttributes(), llvm::Function::getEntryBlock(), llvm::EVT::getEVT(), llvm::Instruction::getOpcode(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantInt::getSExtValue(), llvm::Value::getType(), llvm::Use::getUser(), llvm::AttributeList::hasAttribute(), I, llvm::Instruction::insertBefore(), Intr, llvm::Value::replaceAllUsesWith(), runOnFunction(), SI, llvm::Value::user_begin(), and llvm::Value::user_end().