LLVM: lib/Target/Hexagon/HexagonMCInstLower.cpp File Reference
HexagonMCInstLower.cpp File Reference
#include "Hexagon.h"
#include "HexagonAsmPrinter.h"
#include "MCTargetDesc/HexagonMCExpr.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/IR/Constants.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Namespaces
llvm
This class represents lattice values for constants.
Functions
void llvm::HexagonLowerToMC (const MCInstrInfo &MCII, const MachineInstr *MI, MCInst &MCB, HexagonAsmPrinter &AP)
static MCOperand GetSymbolRef (const MachineOperand &MO, const MCSymbol *Symbol, HexagonAsmPrinter &Printer, bool MustExtend)
Function Documentation
GetSymbolRef()
static MCOperand GetSymbolRef (const MachineOperand & MO, const MCSymbol * Symbol, HexagonAsmPrinter & Printer, bool MustExtend) static
Definition at line 41 of file HexagonMCInstLower.cpp.
References llvm::HexagonMCExpr::create(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::HexagonII::HMOTF_ConstExtended, llvm::MachineOperand::isJTI(), llvm::HexagonII::MO_GDGOT, llvm::HexagonII::MO_GDPLT, llvm::HexagonII::MO_GOT, llvm::HexagonII::MO_GPREL, llvm::HexagonII::MO_HI16, llvm::HexagonII::MO_IE, llvm::HexagonII::MO_IEGOT, llvm::HexagonII::MO_LO16, llvm::HexagonII::MO_PCREL, llvm::HexagonII::MO_TPREL, llvm::AsmPrinter::OutContext, llvm::HexagonMCInstrInfo::setMustExtend(), llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_Hexagon_GD_GOT, llvm::MCSymbolRefExpr::VK_Hexagon_GD_PLT, llvm::MCSymbolRefExpr::VK_Hexagon_GPREL, llvm::MCSymbolRefExpr::VK_Hexagon_HI16, llvm::MCSymbolRefExpr::VK_Hexagon_IE, llvm::MCSymbolRefExpr::VK_Hexagon_IE_GOT, llvm::MCSymbolRefExpr::VK_Hexagon_LO16, llvm::MCSymbolRefExpr::VK_Hexagon_PCREL, llvm::MCSymbolRefExpr::VK_None, and llvm::MCSymbolRefExpr::VK_TPREL.
Referenced by llvm::ARMAsmPrinter::getISAEncoding(), llvm::HexagonLowerToMC(), and VisitGlobalVariableForEmission().