LLVM: lib/Target/Hexagon/HexagonCFGOptimizer.cpp File Reference
HexagonCFGOptimizer.cpp File Reference
#include "Hexagon.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <vector>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "hexagon_cfg"
Functions
FunctionPass * llvm::createHexagonCFGOptimizer ()
void llvm::initializeHexagonCFGOptimizerPass (PassRegistry &)
static bool IsConditionalBranch (int Opc)
static bool IsUnconditionalJump (int Opc)
INITIALIZE_PASS (HexagonCFGOptimizer, "hexagon-cfg", "Hexagon CFG Optimizer", false, false) FunctionPass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon_cfg"
Definition at line 25 of file HexagonCFGOptimizer.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonCFGOptimizer , "hexagon-cfg" , "Hexagon CFG Optimizer" , false , false)
Definition at line 244 of file HexagonCFGOptimizer.cpp.
IsConditionalBranch()
static bool IsConditionalBranch (int Opc) static
Definition at line 61 of file HexagonCFGOptimizer.cpp.
Referenced by IsUnconditionalJump().
IsUnconditionalJump()
static bool IsUnconditionalJump (int Opc) static
Definition at line 76 of file HexagonCFGOptimizer.cpp.
References llvm::MachineBasicBlock::addLiveIn(), assert(), llvm::MachineBasicBlock::back(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::MachineBasicBlock::canFallThrough(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineBasicBlock::erase(), llvm::MachineBasicBlock::front(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getSubtarget(), IsConditionalBranch(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::MachineBasicBlock::isSuccessor(), llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm_unreachable, MI, llvm::MachineBasicBlock::moveAfter(), llvm::MachineBasicBlock::pred_size(), llvm::MachineBasicBlock::predecessors(), llvm::MachineBasicBlock::removeLiveIn(), llvm::MachineBasicBlock::replaceSuccessor(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setMBB(), SI, llvm::MachineBasicBlock::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_size(), and TII.