LLVM: lib/Target/Hexagon/HexagonVExtract.cpp File Reference
HexagonVExtract.cpp File Reference
#include "Hexagon.h"
#include "HexagonInstrInfo.h"
#include "HexagonMachineFunctionInfo.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/PassSupport.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include <map>
Namespaces
llvm
This class represents lattice values for constants.
Functions
void llvm::initializeHexagonVExtractPass (PassRegistry &)
FunctionPass * llvm::createHexagonVExtract ()
INITIALIZE_PASS (HexagonVExtract, "hexagon-vextract", "Hexagon optimize vextract", false, false) unsigned HexagonVExtract
Variables
static cl::opt< unsigned > VExtractThreshold ("hexagon-vextract-threshold", cl::Hidden, cl::ZeroOrMore, cl::init(1), cl::desc("Threshold for triggering vextract replacement"))
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonVExtract , "hexagon-vextract" , "Hexagon optimize vextract" , false , false)
Definition at line 64 of file HexagonVExtract.cpp.
References add(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::BuildMI(), llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MDNode::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::HexagonSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getVRegDef(), llvm::max(), MI, MRI, P, llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineOperand::setImm(), and VExtractThreshold.
Variable Documentation
VExtractThreshold
cl::opt<unsigned> VExtractThreshold("hexagon-vextract-threshold", cl::Hidden, cl::ZeroOrMore, cl::init(1), cl::desc("Threshold for triggering vextract replacement")) static
Referenced by INITIALIZE_PASS().