LLVM: lib/Target/Hexagon/MCTargetDesc/HexagonMCChecker.cpp File Reference
HexagonMCChecker.cpp File Reference
#include "MCTargetDesc/HexagonMCChecker.h"
#include "MCTargetDesc/HexagonBaseInfo.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "MCTargetDesc/HexagonMCShuffler.h"
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/SourceMgr.h"
#include <cassert>
Functions
static bool isDuplexAGroup (unsigned Opcode)
static bool isNeitherAnorX (MCInstrInfo const &MCII, MCInst const &ID)
Variables
static cl::opt< bool > RelaxNVChecks ("relax-nv-checks", cl::init(false), cl::ZeroOrMore, cl::Hidden, cl::desc("Relax checks of new-value validity"))
Function Documentation
isDuplexAGroup()
static bool isDuplexAGroup (unsigned Opcode) static
Definition at line 227 of file HexagonMCChecker.cpp.
Referenced by isNeitherAnorX().
isNeitherAnorX()
static bool isNeitherAnorX (MCInstrInfo const & MCII, MCInst const & ID) static
Definition at line 260 of file HexagonMCChecker.cpp.
References llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::MCOperand::getInst(), llvm::MCInst::getLoc(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::HexagonMCInstrInfo::getType(), I, isDuplexAGroup(), llvm::HexagonMCInstrInfo::isFloat(), llvm::HexagonMCInstrInfo::isSoloAX(), llvm::HexagonMCChecker::reportError(), llvm::HexagonII::TypeALU32_2op, llvm::HexagonII::TypeALU32_3op, llvm::HexagonII::TypeALU32_ADDI, llvm::HexagonII::TypeALU64, llvm::HexagonII::TypeDUPLEX, llvm::HexagonII::TypeS_2op, and llvm::HexagonII::TypeS_3op.
Variable Documentation
RelaxNVChecks
cl::opt<bool> RelaxNVChecks("relax-nv-checks", cl::init(false), cl::ZeroOrMore, cl::Hidden, cl::desc("Relax checks of new-value validity")) static
Referenced by llvm::HexagonMCChecker::reportBranchErrors().