LLVM: lib/Target/Hexagon/HexagonEarlyIfConv.cpp File Reference
HexagonEarlyIfConv.cpp File Reference
#include "Hexagon.h"
#include "HexagonInstrInfo.h"
#include "HexagonSubtarget.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/Pass.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <iterator>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "hexagon-eif"
Functions
FunctionPass * llvm::createHexagonEarlyIfConversion ()
void llvm::initializeHexagonEarlyIfConversionPass (PassRegistry &Registry)
INITIALIZE_PASS (HexagonEarlyIfConversion, "hexagon-early-if", "Hexagon early if conversion", false, false) bool HexagonEarlyIfConversion
Variables
static cl::opt< bool > EnableHexagonBP ("enable-hexagon-br-prob", cl::Hidden, cl::init(true), cl::desc("Enable branch probability info"))
static cl::opt< unsigned > SizeLimit ("eif-limit", cl::init(6), cl::Hidden, cl::desc("Size limit in Hexagon early if-conversion"))
static cl::opt< bool > SkipExitBranches ("eif-no-loop-exit", cl::init(false), cl::Hidden, cl::desc("Do not convert branches that may exit the loop"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-eif"
Definition at line 90 of file HexagonEarlyIfConv.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonEarlyIfConversion , "hexagon-early-if" , "Hexagon early if conversion" , false , false)
Definition at line 227 of file HexagonEarlyIfConv.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), assert(), B, llvm::MachineBasicBlock::back(), llvm::LoopBase< BlockT, LoopT >::begin(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::count_if(), D, llvm::dbgs(), Deleted, llvm::numbers::e, E, llvm::MachineBasicBlock::empty(), llvm::LoopBase< BlockT, LoopT >::end(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MDNode::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineBasicBlock::hasAddressTaken(), llvm::MachineInstr::hasUnmodeledSideEffects(), HEXAGON_PACKET_SIZE, I, llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isCall(), llvm::MachineBasicBlock::isEHPad(), llvm::MachineInstr::isImplicitDef(), llvm::MachineInstr::isMetaInstruction(), llvm::MachineInstr::isPHI(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), llvm::ISD::LIFETIME_END, LLVM_DEBUG, llvm_unreachable, llvm::make_range(), llvm::MachineInstr::mayLoadOrStore(), llvm::MachineInstr::mayStore(), MI, MRI, N, llvm::MachineInstr::operands(), llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::MachineBasicBlock::pred_size(), llvm::printMBBReference(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RA, llvm::SmallVectorBase::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_size(), llvm::T, llvm::X86II::TB, and TRI.
Variable Documentation
EnableHexagonBP
cl::opt<bool> EnableHexagonBP("enable-hexagon-br-prob", cl::Hidden, cl::init(true), cl::desc("Enable branch probability info")) static
SizeLimit
cl::opt<unsigned> SizeLimit("eif-limit", cl::init(6), cl::Hidden, cl::desc("Size limit in Hexagon early if-conversion")) static
SkipExitBranches
cl::opt<bool> SkipExitBranches("eif-no-loop-exit", cl::init(false), cl::Hidden, cl::desc("Do not convert branches that may exit the loop")) static