LLVM: lib/Target/Hexagon/AsmParser/HexagonAsmParser.cpp File Reference
HexagonAsmParser.cpp File Reference
#include "HexagonTargetStreamer.h"
#include "MCTargetDesc/HexagonMCChecker.h"
#include "MCTargetDesc/HexagonMCELFStreamer.h"
#include "MCTargetDesc/HexagonMCExpr.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "MCTargetDesc/HexagonShuffler.h"
#include "TargetInfo/HexagonTargetInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>
#include "HexagonGenAsmMatcher.inc"
Macros
#define DEBUG_TYPE "mcasmparser"
#define GET_MATCHER_IMPLEMENTATION
#define GET_REGISTER_MATCHER
Auto-generated Match Functions
{
#define GET_ASSEMBLER_HEADER
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeHexagonAsmParser ()
Force static initialization.
static bool previousEqual (OperandVector &Operands, size_t Index, StringRef String)
static bool previousIsLoop (OperandVector &Operands, size_t Index)
static MCInst makeCombineInst (int opCode, MCOperand &Rdd, MCOperand &MO1, MCOperand &MO2)
Variables
static cl::opt< bool > WarnMissingParenthesis ("mwarn-missing-parenthesis", cl::desc("Warn for missing parenthesis around predicate registers"), cl::init(true))
static cl::opt< bool > ErrorMissingParenthesis ("merror-missing-parenthesis", cl::desc("Error for missing parenthesis around predicate registers"), cl::init(false))
static cl::opt< bool > WarnSignedMismatch ("mwarn-sign-mismatch", cl::desc("Warn for mismatching a signed and unsigned value"), cl::init(true))
static cl::opt< bool > WarnNoncontigiousRegister ("mwarn-noncontigious-register", cl::desc("Warn for register names that arent contigious"), cl::init(true))
static cl::opt< bool > ErrorNoncontigiousRegister ("merror-noncontigious-register", cl::desc("Error for register names that aren't contigious"), cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mcasmparser"
Definition at line 9 of file HexagonAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 153 of file HexagonAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 823 of file HexagonAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 824 of file HexagonAsmParser.cpp.
Function Documentation
LLVMInitializeHexagonAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeHexagonAsmParser ()
Force static initialization.
Definition at line 819 of file HexagonAsmParser.cpp.
References llvm::getTheHexagonTarget(), and X.
makeCombineInst()
static MCInst makeCombineInst (int opCode, MCOperand & Rdd, MCOperand & MO1, MCOperand & MO2) static
Definition at line 1223 of file HexagonAsmParser.cpp.
References llvm::HexagonII::Absolute, llvm::MCInst::addOperand(), assert(), llvm::MCInst::clear(), llvm::HexagonISD::CONST32, Context, llvm::HexagonMCExpr::create(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createReg(), llvm::MCBinaryExpr::createSub(), llvm::dbgs(), llvm::SourceMgr::DK_Error, llvm::StringRef::drop_back(), llvm::Error, llvm::errs(), llvm::format_hex(), llvm::HexagonMCInstrInfo::getDesc(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getExpr(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCAsmParser::getStreamer(), llvm::MCStreamer::hasRawTextSupport(), llvm::Hi_32(), llvm::object::is32bit(), llvm::MCOperand::isExpr(), llvm::isInt< 8 >(), llvm::MCInstrDesc::isPseudo(), llvm::MCSymbol::isUndefined(), LLVM_DEBUG, LLVM_FALLTHROUGH, llvm_unreachable, llvm::Lo_32(), llvm::StringRef::lower(), MatchRegisterAltName(), MatchRegisterName(), llvm::MCSA_Global, llvm::MCSA_Local, llvm::HexagonMCInstrInfo::mustExtend(), Name, llvm::MCStreamer::PopSection(), llvm::SMDiagnostic::print(), llvm::MCAsmParser::printError(), llvm::MCStreamer::PushSection(), R2, Reg, llvm::report_fatal_error(), llvm::MCOperand::setExpr(), llvm::HexagonMCInstrInfo::setMustExtend(), llvm::HexagonMCInstrInfo::setMustNotExtend(), llvm::MCInst::setOpcode(), llvm::MCOperand::setReg(), llvm::HexagonMCInstrInfo::setS27_2_reloc(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_PROGBITS, llvm::size(), llvm::raw_string_ostream::str(), Success, llvm::MCStreamer::SwitchSection(), llvm::StringRef::upper(), llvm::utohexstr(), and llvm::utostr().
previousEqual()
static bool previousEqual (OperandVector & Operands, size_t Index, StringRef String) static
Definition at line 827 of file HexagonAsmParser.cpp.
References llvm::getToken(), llvm::MCParsedAsmOperand::isToken(), and llvm::SmallVectorBase::size().
Referenced by previousIsLoop().
previousIsLoop()
static bool previousIsLoop (OperandVector & Operands, size_t Index) static
Definition at line 837 of file HexagonAsmParser.cpp.
References llvm::StringRef::empty(), llvm::AsmToken::getLoc(), llvm::AsmToken::getString(), previousEqual(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Register, llvm::StringRef::split(), llvm::String, and llvm::StringRef::substr().
Variable Documentation
ErrorMissingParenthesis
cl::opt<bool> ErrorMissingParenthesis("merror-missing-parenthesis", cl::desc("Error for missing parenthesis around predicate registers"), cl::init(false)) static
ErrorNoncontigiousRegister
cl::opt<bool> ErrorNoncontigiousRegister("merror-noncontigious-register", cl::desc("Error for register names that aren't contigious"), cl::init(false)) static
WarnMissingParenthesis
cl::opt<bool> WarnMissingParenthesis("mwarn-missing-parenthesis", cl::desc("Warn for missing parenthesis around predicate registers"), cl::init(true)) static
WarnNoncontigiousRegister
cl::opt<bool> WarnNoncontigiousRegister("mwarn-noncontigious-register", cl::desc("Warn for register names that arent contigious"), cl::init(true)) static
WarnSignedMismatch
cl::opt<bool> WarnSignedMismatch("mwarn-sign-mismatch", cl::desc("Warn for mismatching a signed and unsigned value"), cl::init(true)) static