LLVM: lib/Target/Hexagon/HexagonGenMux.cpp File Reference
HexagonGenMux.cpp File Reference
#include "HexagonInstrInfo.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MathExtras.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <limits>
#include <utility>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "hexmux"
Functions
FunctionPass * llvm::createHexagonGenMux ()
void llvm::initializeHexagonGenMuxPass (PassRegistry &Registry)
INITIALIZE_PASS (HexagonGenMux, "hexagon-gen-mux", "Hexagon generate mux instructions", false, false) void HexagonGenMux
Variables
static cl::opt< unsigned > MinPredDist ("hexagon-gen-mux-threshold", cl::Hidden, cl::init(0), cl::desc("Minimum distance between predicate definition and " "farther of the two predicated uses"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexmux"
Definition at line 22 of file HexagonGenMux.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonGenMux , "hexagon-gen-mux" , "Hexagon generate mux instructions" , false , false)
Definition at line 143 of file HexagonGenMux.cpp.
References B, llvm::MachineBasicBlock::begin(), D, E, llvm::MachineBasicBlock::end(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), I, llvm::MCInstrDesc::ImplicitDefs, llvm::MCInstrDesc::ImplicitUses, llvm::MachineOperand::isImm(), llvm::isInt< 8 >(), llvm::MachineOperand::isReg(), MI, llvm::MachineInstr::operands(), Reg, and llvm::BitVector::reset().
Variable Documentation
MinPredDist
cl::opt<unsigned> MinPredDist("hexagon-gen-mux-threshold", cl::Hidden, cl::init(0), cl::desc("Minimum distance between predicate definition and " "farther of the two predicated uses")) static