LLVM: lib/Analysis/IndirectCallPromotionAnalysis.cpp File Reference
IndirectCallPromotionAnalysis.cpp File Reference
#include "llvm/Analysis/IndirectCallPromotionAnalysis.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/IndirectCallVisitor.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include <string>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "pgo-icall-prom-analysis"
Variables
static cl::opt< unsigned > ICPRemainingPercentThreshold ("icp-remaining-percent-threshold", cl::init(30), cl::Hidden, cl::ZeroOrMore, cl::desc("The percentage threshold against remaining unpromoted indirect " "call count for the promotion"))
static cl::opt< unsigned > ICPTotalPercentThreshold ("icp-total-percent-threshold", cl::init(5), cl::Hidden, cl::ZeroOrMore, cl::desc("The percentage threshold against total " "count for the promotion"))
static cl::opt< unsigned > MaxNumPromotions ("icp-max-prom", cl::init(3), cl::Hidden, cl::ZeroOrMore, cl::desc("Max number of promotions for a single indirect " "call callsite"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pgo-icall-prom-analysis"
Definition at line 32 of file IndirectCallPromotionAnalysis.cpp.
Variable Documentation
ICPRemainingPercentThreshold
cl::opt<unsigned> ICPRemainingPercentThreshold("icp-remaining-percent-threshold", cl::init(30), cl::Hidden, cl::ZeroOrMore, cl::desc("The percentage threshold against remaining unpromoted indirect " "call count for the promotion")) static
Referenced by llvm::ICallPromotionAnalysis::ICallPromotionAnalysis().
ICPTotalPercentThreshold
cl::opt<unsigned> ICPTotalPercentThreshold("icp-total-percent-threshold", cl::init(5), cl::Hidden, cl::ZeroOrMore, cl::desc("The percentage threshold against total " "count for the promotion")) static
Referenced by llvm::ICallPromotionAnalysis::ICallPromotionAnalysis().
MaxNumPromotions
cl::opt<unsigned> MaxNumPromotions("icp-max-prom", cl::init(3), cl::Hidden, cl::ZeroOrMore, cl::desc("Max number of promotions for a single indirect " "call callsite")) static
Referenced by llvm::ICallPromotionAnalysis::getPromotionCandidatesForInstruction(), and llvm::ICallPromotionAnalysis::ICallPromotionAnalysis().