LLVM: lib/XRay/InstrumentationMap.cpp File Reference
InstrumentationMap.cpp File Reference
#include "llvm/XRay/InstrumentationMap.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/RelocationResolver.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/YAMLTraits.h"
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <system_error>
#include <vector>
Typedefs
using RelocMap = DenseMap< uint64_t, uint64_t >
Functions
static Error loadObj (StringRef Filename, object::OwningBinary< object::ObjectFile > &ObjFile, InstrumentationMap::SledContainer &Sleds, InstrumentationMap::FunctionAddressMap &FunctionAddresses, InstrumentationMap::FunctionAddressReverseMap &FunctionIds)
static Error loadYAML (sys::fs::file_t Fd, size_t FileSize, StringRef Filename, InstrumentationMap::SledContainer &Sleds, InstrumentationMap::FunctionAddressMap &FunctionAddresses, InstrumentationMap::FunctionAddressReverseMap &FunctionIds)
Typedef Documentation
RelocMap
using RelocMap = DenseMap<uint64_t, uint64_t>
Definition at line 51 of file InstrumentationMap.cpp.
Function Documentation
loadObj()
static Error loadObj (StringRef Filename, object::OwningBinary< object::ObjectFile > & ObjFile, InstrumentationMap::SledContainer & Sleds, InstrumentationMap::FunctionAddressMap & FunctionAddresses, InstrumentationMap::FunctionAddressReverseMap & FunctionIds) static
Definition at line 54 of file InstrumentationMap.cpp.
References llvm::Triple::aarch64, llvm::Address, C, llvm::consumeError(), llvm::xray::SledEntry::CUSTOM_EVENT, E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::xray::SledEntry::ENTRY, llvm::errorCodeToError(), llvm::xray::SledEntry::EXIT, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::find_if(), FuncId, llvm::object::ELFRelocationRef::getAddend(), llvm::object::ObjectFile::getArch(), llvm::object::OwningBinary< T >::getBinary(), llvm::object::SectionRef::getName(), llvm::object::getRelocationResolver, llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::object::Binary::isELF(), llvm::object::Binary::isMachO(), llvm::xray::SledEntry::LOG_ARGS_ENTER, llvm::make_error_code(), llvm::Triple::ppc64le, llvm::object::SectionRef::relocations(), llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), llvm::Error::success(), llvm::xray::SledEntry::TAIL, llvm::Expected< T >::takeError(), and llvm::Triple::x86_64.
Referenced by llvm::xray::loadInstrumentationMap().
loadYAML()
static Error loadYAML (sys::fs::file_t Fd, size_t FileSize, StringRef Filename, InstrumentationMap::SledContainer & Sleds, InstrumentationMap::FunctionAddressMap & FunctionAddresses, InstrumentationMap::FunctionAddressReverseMap & FunctionIds) static
Definition at line 188 of file InstrumentationMap.cpp.
References llvm::sys::fs::closeFile(), llvm::sys::fs::mapped_file_region::data(), llvm::tgtok::In, llvm::sys::fs::mapped_file_region::size(), llvm::Error::success(), and Y.
Referenced by llvm::xray::loadInstrumentationMap().