LLVM: lib/Transforms/InstCombine/InstCombineAndOrXor.cpp File Reference
InstCombineAndOrXor.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/Analysis/CmpInstAnalysis.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/PatternMatch.h"
Macros
#define DEBUG_TYPE "instcombine"
Enumerations
enum MaskedICmpType {
AMask_AllOnes = 1, AMask_NotAllOnes = 2, BMask_AllOnes = 4, BMask_NotAllOnes = 8,
Mask_AllZeros = 16, Mask_NotAllZeros = 32, AMask_Mixed = 64, AMask_NotMixed = 128,
BMask_Mixed = 256, BMask_NotMixed = 512
}
Classify (icmp eq (A & B), C) and (icmp ne (A & B), C) as matching patterns that can be simplified.
Functions
static unsigned getFCmpCode (FCmpInst::Predicate CC)
Similar to getICmpCode but for FCmpInst.
static Value * getNewICmpValue (unsigned Code, bool Sign, Value *LHS, Value *RHS, InstCombiner::BuilderTy &Builder)
This is the complement of getICmpCode, which turns an opcode and two operands into either a constant true or false, or a brand new ICmp instruction.
static Value * getFCmpValue (unsigned Code, Value *LHS, Value *RHS, InstCombiner::BuilderTy &Builder)
This is the complement of getFCmpCode, which turns an opcode and two operands into either a FCmp instruction, or a true/false constant.
static Value * SimplifyBSwap (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
Transform BITWISE_OP(BSWAP(A),BSWAP(B)) or BITWISE_OP(BSWAP(A), Constant) to BSWAP(BITWISE_OP(A, B))
static unsigned getMaskedICmpType (Value *A, Value *B, Value *C, ICmpInst::Predicate Pred)
Return the set of patterns (from MaskedICmpType) that (icmp SCC (A & B), C) satisfies.
static unsigned conjugateICmpMask (unsigned Mask)
Convert an analysis of a masked ICmp into its equivalent if all boolean operations had the opposite sense.
static bool decomposeBitTestICmp (Value *LHS, Value *RHS, CmpInst::Predicate &Pred, Value *&X, Value *&Y, Value *&Z)
static Optional< std::pair< unsigned, unsigned > > getMaskedTypeForICmpPair (Value *&A, Value *&B, Value *&C, Value *&D, Value *&E, ICmpInst *LHS, ICmpInst *RHS, ICmpInst::Predicate &PredL, ICmpInst::Predicate &PredR)
Handle (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E).
static Value * foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed (ICmpInst *LHS, ICmpInst *RHS, bool IsAnd, Value *A, Value *B, Value *C, Value *D, Value *E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, llvm::InstCombiner::BuilderTy &Builder)
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side is of type Mask_NotAllZeros and the right hand side is of type BMask_Mixed.
static Value * foldLogOpOfMaskedICmpsAsymmetric (ICmpInst *LHS, ICmpInst *RHS, bool IsAnd, Value *A, Value *B, Value *C, Value *D, Value *E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, unsigned LHSMask, unsigned RHSMask, llvm::InstCombiner::BuilderTy &Builder)
Try to fold (icmp(A & B) ==/!= 0) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side and the right hand side aren't of the common mask pattern type.
static Value * foldLogOpOfMaskedICmps (ICmpInst *LHS, ICmpInst *RHS, bool IsAnd, llvm::InstCombiner::BuilderTy &Builder)
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y).
static Value * foldAndOrOfEqualityCmpsWithConstants (ICmpInst *LHS, ICmpInst *RHS, bool JoinedByAnd, InstCombiner::BuilderTy &Builder)
static Value * foldSignedTruncationCheck (ICmpInst *ICmp0, ICmpInst *ICmp1, Instruction &CxtI, InstCombiner::BuilderTy &Builder)
General pattern: X & Y.
static Value * foldIsPowerOf2 (ICmpInst *Cmp0, ICmpInst *Cmp1, bool JoinedByAnd, InstCombiner::BuilderTy &Builder)
Reduce a pair of compares that check if a value has exactly 1 bit set.
static Value * foldUnsignedUnderflowCheck (ICmpInst *ZeroICmp, ICmpInst *UnsignedICmp, bool IsAnd, const SimplifyQuery &Q, InstCombiner::BuilderTy &Builder)
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
static Instruction * reassociateFCmps (BinaryOperator &BO, InstCombiner::BuilderTy &Builder)
This a limited reassociation for a special case (see above) where we are checking if two values are either both NAN (unordered) or not-NAN (ordered).
static Instruction * matchDeMorgansLaws (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
Match De Morgan's Laws: (~A & ~B) == (~(A | B)) (~A | ~B) == (~(A & B))
static Instruction * foldLogicCastConstant (BinaryOperator &Logic, CastInst *Cast, InstCombiner::BuilderTy &Builder)
Fold {and,or,xor} (cast X), C.
static Instruction * foldAndToXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static Instruction * foldOrToXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static bool canNarrowShiftAmt (Constant *C, unsigned BitWidth)
Return true if a constant shift amount is always less than the specified bit-width.
static Instruction * matchRotate (Instruction &Or)
Transform UB-safe variants of bitwise rotate to the funnel shift intrinsic.
static bool areInverseVectorBitmasks (Constant *C1, Constant *C2)
If all elements of two constant vectors are 0/-1 and inverses, return true.
static Instruction * foldXorToXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
A ^ B can be specified using other logic ops in a variety of patterns.
static Instruction * visitMaskedMerge (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
If we have a masked merge, in the canonical form of: (assuming that A only has one use.) | A | |B| ((x ^ y) & M) ^ y | D |.
static Instruction * sinkNotIntoXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 23 of file InstCombineAndOrXor.cpp.
Enumeration Type Documentation
MaskedICmpType
enum MaskedICmpType
Classify (icmp eq (A & B), C) and (icmp ne (A & B), C) as matching patterns that can be simplified.
One of A and B is considered the mask. The other is the value. This is described as the "AMask" or "BMask" part of the enum. If the enum contains only "Mask", then both A and B can be considered masks. If A is the mask, then it was proven that (A & C) == C. This is trivial if C == A or C == 0. If both A and C are constants, this proof is also easy. For the following explanations, we assume that A is the mask.
"AllOnes" declares that the comparison is true only if (A & B) == A or all bits of A are set in B. Example: (icmp eq (A & 3), 3) -> AMask_AllOnes
"AllZeros" declares that the comparison is true only if (A & B) == 0 or all bits of A are cleared in B. Example: (icmp eq (A & 3), 0) -> Mask_AllZeroes
"Mixed" declares that (A & B) == C and C might or might not contain any number of one bits and zero bits. Example: (icmp eq (A & 3), 1) -> AMask_Mixed
"Not" means that in above descriptions "==" should be replaced by "!=". Example: (icmp ne (A & 3), 3) -> AMask_NotAllOnes
If the mask A contains a single bit, then the following is equivalent: (icmp eq (A & B), A) equals (icmp ne (A & B), 0) (icmp ne (A & B), A) equals (icmp eq (A & B), 0)
Enumerator
AMask_AllOnes
AMask_NotAllOnes
BMask_AllOnes
BMask_NotAllOnes
Mask_AllZeros
Mask_NotAllZeros
AMask_Mixed
AMask_NotMixed
BMask_Mixed
BMask_NotMixed
Definition at line 215 of file InstCombineAndOrXor.cpp.
Function Documentation
areInverseVectorBitmasks()
static bool areInverseVectorBitmasks (Constant * C1, Constant * C2) static
If all elements of two constant vectors are 0/-1 and inverses, return true.
Definition at line 2090 of file InstCombineAndOrXor.cpp.
References B, llvm::ComputeNumSignBits(), llvm::Constant::getAggregateElement(), llvm::ConstantExpr::getNot(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Zero(), llvm::CmpInst::makeCmpResultType(), and llvm::PatternMatch::match().
canNarrowShiftAmt()
static bool canNarrowShiftAmt (Constant * C, unsigned BitWidth) static
Return true if a constant shift amount is always less than the specified bit-width.
If not, the shift could create poison in the narrower type.
Definition at line 1655 of file InstCombineAndOrXor.cpp.
References C, llvm::dyn_cast(), llvm::Constant::getAggregateElement(), getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), and X.
conjugateICmpMask()
static unsigned conjugateICmpMask (unsigned Mask) static
Convert an analysis of a masked ICmp into its equivalent if all boolean operations had the opposite sense.
Since each "NotXXX" flag (recording !=) is adjacent to the corresponding normal flag (recording ==), this just involves swapping those bits over.
Definition at line 279 of file InstCombineAndOrXor.cpp.
References AMask_AllOnes, AMask_Mixed, AMask_NotAllOnes, AMask_NotMixed, BMask_AllOnes, BMask_Mixed, BMask_NotAllOnes, BMask_NotMixed, Mask_AllZeros, and Mask_NotAllZeros.
Referenced by foldLogOpOfMaskedICmps(), and foldLogOpOfMaskedICmpsAsymmetric().
decomposeBitTestICmp()
static bool decomposeBitTestICmp (Value * LHS, Value * RHS, CmpInst::Predicate & Pred, Value *& X, Value *& Y, Value *& Z) static
Definition at line 293 of file InstCombineAndOrXor.cpp.
References llvm::decomposeBitTestICmp(), llvm::ConstantInt::get(), llvm::Value::getType(), and llvm::BitmaskEnumDetail::Mask().
foldAndOrOfEqualityCmpsWithConstants()
static Value* foldAndOrOfEqualityCmpsWithConstants (ICmpInst * LHS, ICmpInst * RHS, bool JoinedByAnd, InstCombiner::BuilderTy & Builder) static
Definition at line 804 of file InstCombineAndOrXor.cpp.
References llvm::MCID::Add, B, C, llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateOr(), D, llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::isKnownToBeAPowerOfTwo(), llvm::APInt::isNullValue(), llvm::APInt::isPowerOf2(), llvm::ConstantInt::isZero(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Value(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), std::swap(), llvm::APInt::ugt(), and X.
Referenced by foldUnsignedUnderflowCheck().
foldAndToXor()
static Instruction* foldAndToXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 1601 of file InstCombineAndOrXor.cpp.
References assert(), B, llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::hasOneUse(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombiner::visitAnd().
foldIsPowerOf2()
static Value* foldIsPowerOf2 (ICmpInst * Cmp0, ICmpInst * Cmp1, bool JoinedByAnd, InstCombiner::BuilderTy & Builder) static
Reduce a pair of compares that check if a value has exactly 1 bit set.
Definition at line 1023 of file InstCombineAndOrXor.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpNE(), llvm::ConstantInt::get(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), std::swap(), and X.
Referenced by foldUnsignedUnderflowCheck().
foldLogicCastConstant()
static Instruction* foldLogicCastConstant (BinaryOperator & Logic, CastInst * Cast, InstCombiner::BuilderTy & Builder) static
Fold {and,or,xor} (cast X), C.
Definition at line 1496 of file InstCombineAndOrXor.cpp.
References assert(), C, llvm::CastInst::Create(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::dyn_cast(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getSExt(), llvm::CastInst::getSrcTy(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::ConstantExpr::getZExt(), I, llvm::Instruction::isBitwiseLogicOp(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::MipsISD::Ret, and X.
foldLogOpOfMaskedICmps()
static Value* foldLogOpOfMaskedICmps (ICmpInst * LHS, ICmpInst * RHS, bool IsAnd, llvm::InstCombiner::BuilderTy & Builder) static
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y).
Definition at line 606 of file InstCombineAndOrXor.cpp.
References AMask_AllOnes, AMask_NotAllOnes, assert(), B, BMask_AllOnes, BMask_Mixed, BMask_NotAllOnes, C, conjugateICmpMask(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateOr(), D, llvm::dyn_cast(), E, foldLogOpOfMaskedICmpsAsymmetric(), llvm::ConstantInt::get(), getMaskedTypeForICmpPair(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getOr(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::ConstantExpr::getXor(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), llvm::BitmaskEnumDetail::Mask(), Mask_AllZeros, and Mask_NotAllZeros.
Referenced by foldUnsignedUnderflowCheck().
foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed()
static Value* foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed (ICmpInst * LHS, ICmpInst * RHS, bool IsAnd, Value * A, Value * B, Value * C, Value * D, Value * E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, llvm::InstCombiner::BuilderTy & Builder) static
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side is of type Mask_NotAllZeros and the right hand side is of type BMask_Mixed.
For example, (icmp (A & 12) != 0) & (icmp (A & 15) == 8) -> (icmp (A & 15) == 8).
Definition at line 441 of file InstCombineAndOrXor.cpp.
References assert(), B, C, llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateICmp(), D, llvm::dyn_cast(), E, llvm::ConstantInt::get(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::ConstantExpr::getXor(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, and llvm::ConstantInt::isZero().
Referenced by foldLogOpOfMaskedICmpsAsymmetric().
foldLogOpOfMaskedICmpsAsymmetric()
static Value* foldLogOpOfMaskedICmpsAsymmetric (ICmpInst * LHS, ICmpInst * RHS, bool IsAnd, Value * A, Value * B, Value * C, Value * D, Value * E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, unsigned LHSMask, unsigned RHSMask, llvm::InstCombiner::BuilderTy & Builder) static
Try to fold (icmp(A & B) ==/!= 0) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side and the right hand side aren't of the common mask pattern type.
Definition at line 571 of file InstCombineAndOrXor.cpp.
References assert(), BMask_Mixed, conjugateICmpMask(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), llvm::ICmpInst::isEquality(), and Mask_NotAllZeros.
Referenced by foldLogOpOfMaskedICmps().
foldOrToXor()
static Instruction* foldOrToXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 1627 of file InstCombineAndOrXor.cpp.
References assert(), B, llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::hasOneUse(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombiner::visitOr().
foldSignedTruncationCheck()
static Value* foldSignedTruncationCheck (ICmpInst * ICmp0, ICmpInst * ICmp1, Instruction & CxtI, InstCombiner::BuilderTy & Builder) static
General pattern: X & Y.
Where Y is checking that all the high bits (covered by a mask 4294967168) are uniform, i.e. arg & 4294967168 can be either 4294967168 or 0 Pattern can be one of: t = add i32 arg, 128 r = icmp ult i32 t, 256 Or t0 = shl i32 arg, 24 t1 = ashr i32 t0, 24 r = icmp eq i32 t1, arg Or t0 = trunc i32 arg to i8 t1 = sext i8 t0 to i32 r = icmp eq i32 t1, arg This pattern is a signed truncation check.
And X is checking that some bit in that same mask is zero. I.e. can be one of: r = icmp sgt i32 arg, -1 Or t = and i32 arg, 2147483648 r = icmp eq i32 t, 0
Since we are checking that all the bits in that mask are the same, and a particular bit is zero, what we are really checking is that all the masked bits are zero. So this should be transformed to: r = icmp ult i32 arg, 128
Definition at line 928 of file InstCombineAndOrXor.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateICmpULT(), llvm::decomposeBitTestICmp(), llvm::ConstantInt::get(), llvm::Value::getName(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::APInt::intersects(), llvm::APInt::isNullValue(), llvm::APInt::isPowerOf2(), llvm::APInt::isSubsetOf(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), llvm::APInt::shl(), llvm::APInt::ugt(), llvm::APIntOps::umin(), X, and llvm::APInt::zext().
Referenced by foldUnsignedUnderflowCheck().
foldUnsignedUnderflowCheck()
static Value* foldUnsignedUnderflowCheck (ICmpInst * ZeroICmp, ICmpInst * UnsignedICmp, bool IsAnd, const SimplifyQuery & Q, InstCombiner::BuilderTy & Builder) static
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
Definition at line 1054 of file InstCombineAndOrXor.cpp.
References llvm::SimplifyQuery::AC, assert(), B, llvm::IRBuilder< T, Inserter >::CreateICmpUGE(), llvm::IRBuilder< T, Inserter >::CreateICmpUGT(), llvm::IRBuilder< T, Inserter >::CreateICmpULE(), llvm::IRBuilder< T, Inserter >::CreateICmpULT(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::dyn_cast(), llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UNO, foldAndOrOfEqualityCmpsWithConstants(), foldIsPowerOf2(), foldLogOpOfMaskedICmps(), foldSignedTruncationCheck(), llvm::ConstantInt::get(), llvm::IntegerType::getBitWidth(), llvm::Type::getContext(), getFCmpCode(), getFCmpValue(), llvm::getICmpCode(), llvm::APInt::getLowBitsSet(), getNewICmpValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::isKnownNonZero(), llvm::ConstantInt::isMinValue(), llvm::APInt::isPowerOf2(), llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), llvm::ConstantInt::isZero(), llvm_unreachable, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), N, Other, llvm::predicatesFoldable(), llvm::APInt::sgt(), std::swap(), llvm::ICmpInst::swapOperands(), llvm::APInt::ugt(), X, and llvm::APInt::zext().
foldXorToXor()
static Instruction* foldXorToXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
A ^ B can be specified using other logic ops in a variety of patterns.
We can fold these early and efficiently by morphing an existing instruction.
Definition at line 2737 of file InstCombineAndOrXor.cpp.
References assert(), B, llvm::canFreelyInvertAllUsersOf(), llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::Constant::getAllOnesValue(), llvm::getICmpCode(), getNewICmpValue(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::Use::getUser(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::Type::isIntOrIntVectorTy(), llvm::CmpInst::isSigned(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::predicatesFoldable(), llvm::User::setOperand(), llvm::SimplifyBinOp(), llvm::ICmpInst::swapOperands(), X, and Y.
Referenced by llvm::InstCombiner::visitXor().
getFCmpCode()
static unsigned getFCmpCode (FCmpInst::Predicate CC) static
Similar to getICmpCode but for FCmpInst.
This encodes a fcmp predicate into a four bit mask.
Definition at line 27 of file InstCombineAndOrXor.cpp.
References assert(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, and llvm::CmpInst::FCMP_UNO.
Referenced by foldUnsignedUnderflowCheck().
getFCmpValue()
static Value* getFCmpValue (unsigned Code, Value * LHS, Value * RHS, InstCombiner::BuilderTy & Builder) static
This is the complement of getFCmpCode, which turns an opcode and two operands into either a FCmp instruction, or a true/false constant.
Definition at line 65 of file InstCombineAndOrXor.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_TRUE, llvm::ConstantInt::get(), llvm::Value::getType(), and llvm::CmpInst::makeCmpResultType().
Referenced by foldUnsignedUnderflowCheck().
getMaskedICmpType()
static unsigned getMaskedICmpType (Value * A, Value * B, Value * C, ICmpInst::Predicate Pred) static
Return the set of patterns (from MaskedICmpType) that (icmp SCC (A & B), C) satisfies.
Definition at line 230 of file InstCombineAndOrXor.cpp.
References AMask_AllOnes, AMask_Mixed, AMask_NotAllOnes, AMask_NotMixed, B, BMask_AllOnes, BMask_Mixed, BMask_NotAllOnes, BMask_NotMixed, C, llvm::dyn_cast(), llvm::ConstantExpr::getAnd(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::APInt::isPowerOf2(), llvm::ConstantInt::isZero(), Mask_AllZeros, and Mask_NotAllZeros.
Referenced by getMaskedTypeForICmpPair().
getMaskedTypeForICmpPair()
static Optional<std::pair<unsigned, unsigned> > getMaskedTypeForICmpPair (Value *& A, Value *& B, Value *& C, Value *& D, Value *& E, ICmpInst * LHS, ICmpInst * RHS, ICmpInst::Predicate & PredL, ICmpInst::Predicate & PredR) static
Handle (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E).
Return the pattern classes (from MaskedICmpType) for the left hand side and the right hand side as a pair. LHS and RHS are the left hand side and the right hand side ICmps and PredL and PredR are their predicates, respectively.
Definition at line 311 of file InstCombineAndOrXor.cpp.
References llvm::decomposeBitTestICmp(), llvm::Constant::getAllOnesValue(), getMaskedICmpType(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ICmpInst::isEquality(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, and R2.
Referenced by foldLogOpOfMaskedICmps().
getNewICmpValue()
static Value* getNewICmpValue (unsigned Code, bool Sign, Value * LHS, Value * RHS, InstCombiner::BuilderTy & Builder) static
This is the complement of getICmpCode, which turns an opcode and two operands into either a constant true or false, or a brand new ICmp instruction.
The sign is passed in to determine which kind of predicate to use in the new icmp instruction.
Definition at line 55 of file InstCombineAndOrXor.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::getPredForICmpCode(), and llvm::Value::getType().
Referenced by foldUnsignedUnderflowCheck(), and foldXorToXor().
matchDeMorgansLaws()
static Instruction* matchDeMorgansLaws (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Match De Morgan's Laws: (~A & ~B) == (~(A | B)) (~A | ~B) == (~(A & B))
Definition at line 1458 of file InstCombineAndOrXor.cpp.
References assert(), B, llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::BinaryOperator::CreateNot(), llvm::CastInst::getDestTy(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CastInst::getSrcTy(), llvm::Value::hasOneUse(), llvm::isFreeToInvert(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombiner::visitAnd(), and llvm::InstCombiner::visitOr().
matchRotate()
static Instruction* matchRotate (Instruction & Or) static
Transform UB-safe variants of bitwise rotate to the funnel shift intrinsic.
Definition at line 2028 of file InstCombineAndOrXor.cpp.
References llvm::CallInst::Create(), F(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::isPowerOf2_32(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), and X.
Referenced by foldGuardedRotateToFunnelShift(), and llvm::InstCombiner::visitOr().
reassociateFCmps()
static Instruction* reassociateFCmps (BinaryOperator & BO, InstCombiner::BuilderTy & Builder) static
This a limited reassociation for a special case (see above) where we are checking if two values are either both NAN (unordered) or not-NAN (ordered).
This could be handled more generally in '-reassociation', but it seems like an unlikely pattern for a large number of logic ops and fcmps.
Definition at line 1413 of file InstCombineAndOrXor.cpp.
References assert(), llvm::BinaryOperator::Create(), llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UNO, llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), std::swap(), X, and Y.
Referenced by llvm::InstCombiner::visitAnd(), and llvm::InstCombiner::visitOr().
SimplifyBSwap()
static Value* SimplifyBSwap (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Transform BITWISE_OP(BSWAP(A),BSWAP(B)) or BITWISE_OP(BSWAP(A), Constant) to BSWAP(BITWISE_OP(A, B))
Parameters
I Binary operator to transform.
Returns
Pointer to node that must replace the original binary operator, or null pointer if no transformation was made.
Definition at line 82 of file InstCombineAndOrXor.cpp.
References llvm::MCID::Add, assert(), llvm::APInt::byteSwap(), C, llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateCall(), F(), llvm::ConstantInt::get(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ICmpInst::getSignedPredicate(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), llvm::MipsISD::Hi, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, llvm::Instruction::isBitwiseLogicOp(), llvm::APInt::isMinSignedValue(), llvm::APInt::isMinValue(), llvm::APInt::isPowerOf2(), llvm::MipsISD::Lo, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::User::setOperand(), llvm::APInt::slt(), llvm::Value::takeName(), llvm::APInt::ult(), and X.
Referenced by llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitOr(), and llvm::InstCombiner::visitXor().
sinkNotIntoXor()
static Instruction* sinkNotIntoXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 2943 of file InstCombineAndOrXor.cpp.
References llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::Value::getName(), llvm::Value::hasOneUse(), llvm::isFreeToInvert(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::match(), std::swap(), X, and Y.
Referenced by llvm::InstCombiner::visitXor().
visitMaskedMerge()
static Instruction* visitMaskedMerge (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
If we have a masked merge, in the canonical form of: (assuming that A only has one use.) | A | |B| ((x ^ y) & M) ^ y | D |.
If M is inverted: | D | ((x ^ y) & ~M) ^ y We can canonicalize by swapping the final xor operand to eliminate the 'not' of the mask. ((x ^ y) & M) ^ x
If M is a constant, and D has one use, we transform to 'and' / 'or' ops because that shortens the dependency chain and improves analysis: (x & M) | (y & ~M)
Definition at line 2907 of file InstCombineAndOrXor.cpp.
References B, C, llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateNot(), D, llvm::Value::hasOneUse(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstCombiner::visitXor().