LLVM: lib/ProfileData/InstrProfWriter.cpp File Reference
InstrProfWriter.cpp File Reference
#include "llvm/ProfileData/InstrProfWriter.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/ProfileCommon.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/OnDiskHashTable.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstdint>
#include <memory>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "llvm/ProfileData/InstrProfData.inc"
Classes
struct PatchItem
class llvm::ProfOStream
class llvm::InstrProfRecordWriterTrait
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define VALUE_PROF_KIND(Enumerator, Value, Descr) #Enumerator,
Functions
static void setSummary (IndexedInstrProf::Summary *TheSummary, ProfileSummary &PS)
Variables
static const char * ValueProfKindStr []
Macro Definition Documentation
VALUE_PROF_KIND
#define VALUE_PROF_KIND (Enumerator, Value, Descr) #Enumerator,
Function Documentation
setSummary()
static void setSummary (IndexedInstrProf::Summary * TheSummary, ProfileSummary & PS) static
Definition at line 270 of file InstrProfWriter.cpp.
References llvm::IndexedInstrProf::allocSummary(), llvm::coverage::CurrentVersion, llvm::ProfileSummaryBuilder::DefaultCutoffs, llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::ProfileSummary::getDetailedSummary(), llvm::ProfileSummary::getMaxCount(), llvm::ProfileSummary::getMaxFunctionCount(), llvm::ProfileSummary::getMaxInternalCount(), llvm::ProfileSummary::getNumCounts(), llvm::ProfileSummary::getNumFunctions(), llvm::InstrProfSummaryBuilder::getSummary(), llvm::ProfileSummary::getTotalCount(), llvm::IndexedInstrProf::Header::HashOffset, llvm::IndexedInstrProf::HashType, llvm::IndexedInstrProf::Header::HashType, I, llvm::IndexedInstrProf::Magic, llvm::IndexedInstrProf::Header::Magic, N, llvm::IndexedInstrProf::Summary::NumCutoffEntries, llvm::IndexedInstrProf::Summary::NumSummaryFields, llvm::ProfOStream::OS, llvm::ProfOStream::patch(), llvm::InstrProfWriter::PF_IRLevel, llvm::InstrProfWriter::PF_IRLevelWithCS, llvm::IndexedInstrProf::Summary::set(), llvm::IndexedInstrProf::Summary::setEntry(), llvm::ArrayRef< T >::size(), llvm::ProfOStream::tell(), llvm::IndexedInstrProf::Header::Unused, llvm::IndexedInstrProf::Header::Version, and llvm::ProfOStream::write().
Variable Documentation
ValueProfKindStr
const char* ValueProfKindStr[] static
Initial value:
= {
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
}
Definition at line 393 of file InstrProfWriter.cpp.