LLVM: lib/Transforms/InstCombine/InstCombineCompares.cpp File Reference
InstCombineCompares.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
Macros
#define DEBUG_TYPE "instcombine"
Functions
STATISTIC (NumSel, "Number of select opts")
static bool addWithOverflow (APInt &Result, const APInt &In1, const APInt &In2, bool IsSigned=false)
Compute Result = In1+In2, returning true if the result overflowed for this type.
static bool subWithOverflow (APInt &Result, const APInt &In1, const APInt &In2, bool IsSigned=false)
Compute Result = In1-In2, returning true if the result overflowed for this type.
static bool hasBranchUse (ICmpInst &I)
Given an icmp instruction, return true if any use of this comparison is a branch on sign bit comparison.
static bool isSignTest (ICmpInst::Predicate &Pred, const APInt &C)
Returns true if the exploded icmp can be expressed as a signed comparison to zero and updates the predicate accordingly.
static void computeSignedMinMaxValuesFromKnownBits (const KnownBits &Known, APInt &Min, APInt &Max)
Given a signed integer type and a set of known zero and one bits, compute the maximum and minimum values that could have the specified known zero and known one bits, returning them in Min/Max.
static void computeUnsignedMinMaxValuesFromKnownBits (const KnownBits &Known, APInt &Min, APInt &Max)
Given an unsigned integer type and a set of known zero and one bits, compute the maximum and minimum values that could have the specified known zero and known one bits, returning them in Min/Max.
static Value * evaluateGEPOffsetExpression (User *GEP, InstCombiner &IC, const DataLayout &DL)
Return a value that can be used to compare the offset implied by a GEP to zero.
static bool canRewriteGEPAsOffset (Value *Start, Value *Base, const DataLayout &DL, SetVector< Value *> &Explored)
Returns true if we can rewrite Start as a GEP with pointer Base and some integer offset.
static void setInsertionPoint (IRBuilder<> &Builder, Value *V, bool Before=true)
static Value * rewriteGEPAsOffset (Value *Start, Value *Base, const DataLayout &DL, SetVector< Value *> &Explored)
Returns a re-written value of Start as an indexed GEP using Base as a pointer.
static std::pair< Value *, Value * > getAsConstantIndexedAddress (Value *V, const DataLayout &DL)
Looks through GEPs, IntToPtrInsts and PtrToIntInsts in order to express the input Value as a constant indexed GEP.
static Instruction * transformToIndexedCompare (GEPOperator *GEPLHS, Value *RHS, ICmpInst::Predicate Cond, const DataLayout &DL)
Converts (CMP GEPLHS, RHS) if this change would make RHS a constant.
static Instruction * processUGT_ADDCST_ADD (ICmpInst &I, Value *A, Value *B, ConstantInt *CI2, ConstantInt *CI1, InstCombiner &IC)
The caller has matched a pattern of the form: I = icmp ugt (add (add A, B), CI2), CI1 If this is of the form: sum = a + b if (sum+128 >u 255) Then replace it with llvm.sadd.with.overflow.i8.
static Instruction * foldICmpShlOne (ICmpInst &Cmp, Instruction *Shl, const APInt &C)
Fold icmp (shl 1, Y), C.
static Instruction * foldICmpBitCast (ICmpInst &Cmp, InstCombiner::BuilderTy &Builder)
static Value * foldICmpWithLowBitMaskedVal (ICmpInst &I, InstCombiner::BuilderTy &Builder)
Some comparisons can be simplified.
static Value * foldICmpWithTruncSignExtendedVal (ICmpInst &I, InstCombiner::BuilderTy &Builder)
Some comparisons can be simplified.
static Value * foldShiftIntoShiftInAnotherHandOfAndInICmp (ICmpInst &I, const SimplifyQuery SQ, InstCombiner::BuilderTy &Builder)
static Instruction * foldICmpWithMinMax (ICmpInst &Cmp)
Fold icmp Pred min|max(X, Y), X.
static Instruction * foldICmpWithZextOrSext (ICmpInst &ICmp, InstCombiner::BuilderTy &Builder)
static bool isNeutralValue (Instruction::BinaryOps BinaryOp, Value *RHS)
static Instruction * processUMulZExtIdiom (ICmpInst &I, Value *MulVal, Value *OtherVal, InstCombiner &IC)
Recognize and process idiom involving test for multiplication overflow.
static APInt getDemandedBitsLHSMask (ICmpInst &I, unsigned BitWidth)
When performing a comparison against a constant, it is possible that not all the bits in the LHS are demanded.
static bool swapMayExposeCSEOpportunities (const Value *Op0, const Value *Op1)
Check if the order of Op0 and Op1 as operands in an ICmpInst should be swapped.
static bool isChainSelectCmpBranch (const SelectInst *SI)
Return true when the instruction sequence within a block is select-cmp-br.
static ICmpInst * canonicalizeCmpWithConstant (ICmpInst &I)
If we have an icmp le or icmp ge instruction with a constant operand, turn it into the appropriate icmp lt or icmp gt instruction.
static Instruction * canonicalizeICmpBool (ICmpInst &I, InstCombiner::BuilderTy &Builder)
Integer compare with boolean values can always be turned into bitwise ops.
static Instruction * foldICmpWithHighBitMask (ICmpInst &Cmp, InstCombiner::BuilderTy &Builder)
static Instruction * foldVectorCmp (CmpInst &Cmp, InstCombiner::BuilderTy &Builder)
static Instruction * foldICmpOfUAddOv (ICmpInst &I)
static Instruction * foldFCmpReciprocalAndZero (FCmpInst &I, Instruction *LHSI, Constant *RHSC)
Fold (C / X) < 0.0 –> X < 0.0 if possible. Swap predicate if necessary.
static Instruction * foldFabsWithFcmpZero (FCmpInst &I)
Optimize fabs(X) compared with zero.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 31 of file InstCombineCompares.cpp.
Function Documentation
addWithOverflow()
static bool addWithOverflow (APInt & Result, const APInt & In1, const APInt & In2, bool IsSigned = false) static
Compute Result = In1+In2, returning true if the result overflowed for this type.
Definition at line 39 of file InstCombineCompares.cpp.
References llvm::APInt::sadd_ov(), and llvm::APInt::uadd_ov().
Referenced by foldICmpShlOne().
canonicalizeCmpWithConstant()
static ICmpInst* canonicalizeCmpWithConstant (ICmpInst & I) static
If we have an icmp le or icmp ge instruction with a constant operand, turn it into the appropriate icmp lt or icmp gt instruction.
This transform allows them to be folded in visitICmpInst.
Definition at line 5254 of file InstCombineCompares.cpp.
References llvm::dyn_cast(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::isCanonicalPredicate(), llvm::ICmpInst::isEquality(), and llvm::CmpInst::isIntPredicate().
canonicalizeICmpBool()
static Instruction* canonicalizeICmpBool (ICmpInst & I, InstCombiner::BuilderTy & Builder) static
Integer compare with boolean values can always be turned into bitwise ops.
Definition at line 5274 of file InstCombineCompares.cpp.
References assert(), B, llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::Type::isIntOrIntVectorTy(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), and std::swap().
canRewriteGEPAsOffset()
static bool canRewriteGEPAsOffset (Value * Start, Value * Base, const DataLayout & DL, SetVector< Value *> & Explored) static
Returns true if we can rewrite Start as a GEP with pointer Base and some integer offset.
The nodes that need to be re-written for this transformation will be added to Explored.
Definition at line 519 of file InstCombineCompares.cpp.
computeSignedMinMaxValuesFromKnownBits()
static void computeSignedMinMaxValuesFromKnownBits (const KnownBits & Known, APInt & Min, APInt & Max) static
Given a signed integer type and a set of known zero and one bits, compute the maximum and minimum values that could have the specified known zero and known one bits, returning them in Min/Max.
TODO: Move to method on KnownBits struct?
Definition at line 102 of file InstCombineCompares.cpp.
References assert(), llvm::APInt::clearSignBit(), llvm::KnownBits::getBitWidth(), llvm::APInt::getBitWidth(), llvm::KnownBits::One, llvm::APInt::setSignBit(), and llvm::KnownBits::Zero.
Referenced by llvm::InstCombiner::replacedSelectWithOperand().
computeUnsignedMinMaxValuesFromKnownBits()
static void computeUnsignedMinMaxValuesFromKnownBits (const KnownBits & Known, APInt & Min, APInt & Max) static
Given an unsigned integer type and a set of known zero and one bits, compute the maximum and minimum values that could have the specified known zero and known one bits, returning them in Min/Max.
TODO: Move to method on KnownBits struct?
Definition at line 124 of file InstCombineCompares.cpp.
References assert(), C, llvm::ConstantFoldCompareInstOperands(), llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorBase::empty(), GEP, llvm::ConstantInt::get(), llvm::Constant::getAggregateElement(), llvm::ConstantExpr::getAnd(), llvm::Type::getArrayElementType(), llvm::Type::getArrayNumElements(), llvm::KnownBits::getBitWidth(), llvm::APInt::getBitWidth(), llvm::ConstantExpr::getExtractValue(), llvm::GlobalVariable::getInitializer(), llvm::Type::getIntegerBitWidth(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::GetElementPtrInst::isInBounds(), isZero(), llvm::KnownBits::One, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::KnownBits::Zero.
Referenced by llvm::InstCombiner::replacedSelectWithOperand().
evaluateGEPOffsetExpression()
static Value* evaluateGEPOffsetExpression (User * GEP, InstCombiner & IC, const DataLayout & DL) static
Return a value that can be used to compare the offset implied by a GEP to zero.
For example, if we have &A[i], we want to return 'i' for "icmp ne i, 0". Note that, in general, indices can be complex, and scales are involved. The above expression would also be legal to codegen as "icmp ne (i*4), 0" (assuming A is a pointer to i32). This latter form is less amenable to optimization though, and we are allowed to generate the first by knowing that pointer arithmetic doesn't overflow.
If we can't emit an optimized form for this expression, this returns null.
Definition at line 425 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::dyn_cast(), llvm::numbers::e, llvm::gep_type_begin(), llvm::ConstantInt::get(), llvm::StructLayout::getElementOffset(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::Type::getIntegerBitWidth(), llvm::DataLayout::getIntPtrType(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::ConstantInt::getSExtValue(), llvm::DataLayout::getStructLayout(), llvm::generic_gep_type_iterator< ItTy >::getStructTypeOrNull(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ConstantInt::getZExtValue(), llvm::ConstantInt::isZero(), llvm::SignExtend64(), and Size.
foldFabsWithFcmpZero()
static Instruction* foldFabsWithFcmpZero (FCmpInst & I) static
Optimize fabs(X) compared with zero.
Definition at line 5970 of file InstCombineCompares.cpp.
References assert(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Instruction::hasNoNaNs(), I, llvm_unreachable, llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, llvm::User::setOperand(), llvm::CmpInst::setPredicate(), and X.
Referenced by llvm::InstCombiner::visitFCmpInst().
foldFCmpReciprocalAndZero()
static Instruction* foldFCmpReciprocalAndZero (FCmpInst & I, Instruction * LHSI, Constant * RHSC) static
Fold (C / X) < 0.0 –> X < 0.0 if possible. Swap predicate if necessary.
Definition at line 5923 of file InstCombineCompares.cpp.
References C, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::Instruction::hasNoInfs(), I, llvm::APFloat::isNegative(), llvm::APFloat::isZero(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombiner::visitFCmpInst().
foldICmpBitCast()
static Instruction* foldICmpBitCast (ICmpInst & Cmp, InstCombiner::BuilderTy & Builder) static
Definition at line 2725 of file InstCombineCompares.cpp.
References llvm::MCID::Add, llvm::MCID::Bitcast, llvm::APInt::byteSwap(), C, llvm::CmpInst::Create(), llvm::SelectInst::Create(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::APInt::getBitWidth(), llvm::APInt::getHighBitsSet(), llvm::ConstantExpr::getICmp(), llvm::IntrinsicInst::getIntrinsicID(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::ConstantExpr::getNot(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::CmpInst::getPredicate(), llvm::Constant::getSplatValue(), llvm::ConstantExpr::getSub(), llvm::Value::getType(), llvm::ConstantExpr::getXor(), llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::Instruction::hasNoSignedWrap(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::Constant::isAllOnesValue(), llvm::GlobalVariable::isConstant(), llvm::ICmpInst::isEquality(), llvm::Constant::isNullValue(), llvm::APInt::isNullValue(), llvm::APInt::isPowerOf2(), llvm::APInt::isSplat(), isVolatile(), llvm::ConstantInt::isZero(), LLVM_FALLTHROUGH, llvm::SPII::Load, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_ShuffleVector(), llvm::PatternMatch::m_SIToFP(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), llvm::MCID::Select, llvm::User::setOperand(), llvm::APInt::sgt(), llvm::Value::takeName(), llvm::APInt::trunc(), llvm::APInt::uge(), llvm::APInt::ule(), llvm::APInt::ult(), and X.
foldICmpOfUAddOv()
static Instruction* foldICmpOfUAddOv (ICmpInst & I) static
Definition at line 5426 of file InstCombineCompares.cpp.
References B, llvm::ExtractValueInst::Create(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZeroInt(), and llvm::PatternMatch::match().
foldICmpShlOne()
static Instruction* foldICmpShlOne (ICmpInst & Cmp, Instruction * Shl, const APInt & C) static
Fold icmp (shl 1, Y), C.
Definition at line 1961 of file InstCombineCompares.cpp.
References llvm::MCID::Add, addWithOverflow(), llvm::APInt::ashr(), assert(), C, llvm::APInt::countTrailingZeros(), llvm::object::Equal, llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::VectorType::get(), llvm::APInt::getBitWidth(), llvm::ConstantExpr::getCompare(), llvm::SelectInst::getCondition(), llvm::Value::getContext(), llvm::SelectInst::getFalseValue(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::ConstantExpr::getNeg(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignMask(), llvm::CmpInst::getSwappedPredicate(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APInt::isAllOnesValue(), llvm::ICmpInst::isEquality(), llvm::Instruction::isExact(), llvm::APInt::isMaxSignedValue(), llvm::APInt::isMaxValue(), llvm::APInt::isMinSignedValue(), llvm::APInt::isMinValue(), llvm::APInt::isNullValue(), llvm::APInt::isOneValue(), llvm::APInt::isPowerOf2(), llvm::isSignBitCheck(), llvm::CmpInst::isSigned(), llvm::APInt::isSignMask(), isSignTest(), llvm::APInt::isStrictlyPositive(), llvm::CmpInst::isUnsigned(), llvm::Type::isVectorTy(), llvm::CodeGenOpt::Less, llvm_unreachable, llvm::APInt::logBase2(), llvm::APInt::lshr(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::ConstantRange::makeExactICmpRegion(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), llvm::APInt::negate(), llvm::APInt::sdiv(), llvm::MCID::Select, llvm::APInt::shl(), SI, llvm::APInt::ssub_ov(), llvm::ConstantRange::subtract(), subWithOverflow(), std::swap(), llvm::APInt::trunc(), llvm::APInt::udiv(), llvm::APInt::ugt(), llvm::Upper, llvm::APInt::usub_ov(), X, and Y.
foldICmpWithHighBitMask()
static Instruction* foldICmpWithHighBitMask (ICmpInst & Cmp, InstCombiner::BuilderTy & Builder) static
Definition at line 5353 of file InstCombineCompares.cpp.
References llvm::CmpInst::Create(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), X, and Y.
foldICmpWithLowBitMaskedVal()
static Value* foldICmpWithLowBitMaskedVal (ICmpInst & I, InstCombiner::BuilderTy & Builder) static
Some comparisons can be simplified.
In this case, we are looking for comparisons that look like a check for a lossy truncation. Folds: icmp SrcPred (x & Mask), x to icmp DstPred x, Mask Where Mask is some pattern that produces all-ones in low bits: (-1 >> y) ((-1 << y) >> y) <- non-canonical, has extra uses ~(-1 << y) ((1 << y) + (-1)) <- non-canonical, has extra uses The Mask can be a constant, too. For some predicates, the operands are commutative. For others, x can only be on a specific side.
Definition at line 3278 of file InstCombineCompares.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::dyn_cast(), llvm::numbers::e, llvm::Constant::getAggregateElement(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isVectorTy(), llvm_unreachable, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::Constant::replaceUndefsWith(), X, and Y.
Referenced by foldShiftIntoShiftInAnotherHandOfAndInICmp().
foldICmpWithMinMax()
static Instruction* foldICmpWithMinMax (ICmpInst & Cmp) static
Fold icmp Pred min|max(X, Y), X.
Definition at line 4070 of file InstCombineCompares.cpp.
References B, C, D, llvm::ConstantInt::get(), getBitWidth(), llvm::ConstantInt::getBitWidth(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::APInt::isPowerOf2(), llvm::APInt::logBase2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_BitReverse(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_SMax(), llvm::PatternMatch::m_c_SMin(), llvm::PatternMatch::m_c_UMax(), llvm::PatternMatch::m_c_UMin(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_ZeroInt(), llvm::PatternMatch::m_ZExt(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), NC, llvm::User::setOperand(), std::swap(), Y, and llvm::APInt::zext().
foldICmpWithTruncSignExtendedVal()
static Value* foldICmpWithTruncSignExtendedVal (ICmpInst & I, InstCombiner::BuilderTy & Builder) static
Some comparisons can be simplified.
In this case, we are looking for comparisons that look like a check for a lossy signed truncation. Folds: (MaskedBits is a constant.) ((x << MaskedBits) a>> MaskedBits) SrcPred x Into: (add x, (1 << (KeptBits-1))) DstPred (1 << KeptBits) Where KeptBits = bitwidth(x) - MaskedBits
Definition at line 3396 of file InstCombineCompares.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::ConstantInt::get(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::APInt::lshr(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::APInt::shl(), T1, llvm::APInt::ugt(), and X.
Referenced by foldShiftIntoShiftInAnotherHandOfAndInICmp().
foldICmpWithZextOrSext()
static Instruction* foldICmpWithZextOrSext (ICmpInst & ICmp, InstCombiner::BuilderTy & Builder) static
Definition at line 4333 of file InstCombineCompares.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateCast(), llvm::dyn_cast(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getCast(), llvm::Type::getIntegerBitWidth(), llvm::ConstantExpr::getIntToPtr(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Type::getPointerAddressSpace(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::ICmpInst::getUnsignedPredicate(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::CmpInst::isSigned(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), X, and Y.
foldShiftIntoShiftInAnotherHandOfAndInICmp()
static Value* foldShiftIntoShiftInAnotherHandOfAndInICmp (ICmpInst & I, const SimplifyQuery SQ, InstCombiner::BuilderTy & Builder) static
Definition at line 3470 of file InstCombineCompares.cpp.
References llvm::APInt::abs(), llvm::SimplifyQuery::AC, llvm::MCID::Add, assert(), B, C, llvm::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::APInt::countTrailingZeros(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::SimplifyQuery::CxtI, D, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::dyn_cast(), F(), foldICmpWithLowBitMaskedVal(), foldICmpWithTruncSignExtendedVal(), llvm::ConstantInt::get(), llvm::Constant::getAllOnesValue(), llvm::APInt::getAllOnesValue(), llvm::KnownBits::getBitWidth(), llvm::APInt::getBitWidth(), llvm::Intrinsic::getDeclaration(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getFlippedStrictnessPredicate(), llvm::APInt::getLowBitsSet(), llvm::Instruction::getModule(), llvm::ConstantExpr::getNeg(), llvm::Constant::getNullValue(), llvm::Instruction::getOpcode(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::ICmpInst::getSignedPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::Constant::getUniqueInteger(), llvm::ICmpInst::getUnsignedPredicate(), llvm::SimplifyQuery::getWithInstruction(), llvm::ConstantExpr::getZExtOrBitCast(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::Instruction::isExact(), llvm::isKnownNonZero(), llvm::APInt::isMaxSignedValue(), llvm::APInt::isNegative(), llvm::Constant::isNullValue(), llvm::APInt::isNullValue(), llvm::APInt::isOneValue(), llvm::CmpInst::isSigned(), llvm::APInt::isSignMask(), llvm::CmpInst::isUnsigned(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), llvm::SimplifyAddInst(), std::swap(), T1, llvm::APInt::uge(), llvm::APInt::ule(), llvm::APInt::ult(), X, and Y.
foldVectorCmp()
static Instruction* foldVectorCmp (CmpInst & Cmp, InstCombiner::BuilderTy & Builder) static
Definition at line 5404 of file InstCombineCompares.cpp.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::UndefValue::get(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ShuffleVector(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by llvm::InstCombiner::visitFCmpInst().
getAsConstantIndexedAddress()
static std::pair<Value *, Value *> getAsConstantIndexedAddress (Value * V, const DataLayout & DL) static
Looks through GEPs, IntToPtrInsts and PtrToIntInsts in order to express the input Value as a constant indexed GEP.
Returns a pair containing the GEPs Pointer and Index.
Definition at line 763 of file InstCombineCompares.cpp.
References llvm::IntegerType::get(), llvm::ConstantExpr::getAdd(), llvm::Value::getContext(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::Constant::getNullValue(), llvm::GetElementPtrInst::getNumIndices(), llvm::User::getOperand(), llvm::ConstantExpr::getSExtOrBitCast(), llvm::Value::getType(), llvm::GetElementPtrInst::hasAllConstantIndices(), and llvm::GetElementPtrInst::isInBounds().
getDemandedBitsLHSMask()
static APInt getDemandedBitsLHSMask (ICmpInst & I, unsigned BitWidth) static
When performing a comparison against a constant, it is possible that not all the bits in the LHS are demanded.
This helper method computes the mask that IS demanded.
Definition at line 4792 of file InstCombineCompares.cpp.
References llvm::APInt::countTrailingOnes(), llvm::APInt::countTrailingZeros(), llvm::APInt::getAllOnesValue(), llvm::APInt::getBitsSetFrom(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::APInt::getSignMask(), llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::isSignBitCheck(), llvm::PatternMatch::m_APInt(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombiner::replacedSelectWithOperand().
hasBranchUse()
static bool hasBranchUse (ICmpInst & I) static
Given an icmp instruction, return true if any use of this comparison is a branch on sign bit comparison.
Definition at line 65 of file InstCombineCompares.cpp.
References llvm::Value::users().
Referenced by processUGT_ADDCST_ADD().
isChainSelectCmpBranch()
static bool isChainSelectCmpBranch (const SelectInst * SI) static
Return true when the instruction sequence within a block is select-cmp-br.
Definition at line 4879 of file InstCombineCompares.cpp.
References llvm::dyn_cast(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), and SI.
Referenced by llvm::InstCombiner::replacedSelectWithOperand().
isNeutralValue()
static bool isNeutralValue (Instruction::BinaryOps BinaryOp, Value * RHS) static
Definition at line 4469 of file InstCombineCompares.cpp.
References llvm::MCID::Add, llvm_unreachable, llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombiner::computeOverflow().
isSignTest()
static bool isSignTest (ICmpInst::Predicate & Pred, const APInt & C) static
Returns true if the exploded icmp can be expressed as a signed comparison to zero and updates the predicate accordingly.
The signedness of the comparison is preserved. TODO: Refactor with decomposeBitTestICmp()?
Definition at line 76 of file InstCombineCompares.cpp.
References llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::APInt::isAllOnesValue(), llvm::APInt::isNullValue(), llvm::APInt::isOneValue(), llvm::ICmpInst::isRelational(), and llvm::CmpInst::isSigned().
Referenced by foldICmpShlOne(), and processUGT_ADDCST_ADD().
processUGT_ADDCST_ADD()
static Instruction* processUGT_ADDCST_ADD (ICmpInst & I, Value * A, Value * B, ConstantInt * CI2, ConstantInt * CI1, InstCombiner & IC) static
The caller has matched a pattern of the form: I = icmp ugt (add (add A, B), CI2), CI1 If this is of the form: sum = a + b if (sum+128 >u 255) Then replace it with llvm.sadd.with.overflow.i8.
Definition at line 1255 of file InstCombineCompares.cpp.
References llvm::MCID::Add, assert(), B, llvm::InstCombiner::Builder, C, llvm::computeKnownBits(), llvm::InstCombiner::ComputeNumSignBits(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMinPopulation(), llvm::APInt::countTrailingZeros(), llvm::BinaryOperator::Create(), llvm::CmpInst::Create(), llvm::ExtractValueInst::Create(), llvm::ConstantRange::difference(), llvm::dyn_cast(), llvm::APInt::exactLogBase2(), F(), llvm::SelectPatternResult::Flavor, llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::VectorType::get(), llvm::Constant::getAllOnesValue(), llvm::ConstantInt::getBitWidth(), llvm::APInt::getBitWidth(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::ConstantInt::getFalse(), llvm::APInt::getHighBitsSet(), llvm::CmpInst::getInversePredicate(), llvm::APInt::getLowBitsSet(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::ConstantExpr::getNeg(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getNUWShl(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getOr(), llvm::Instruction::getParent(), llvm::CmpInst::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::ICmpInst::getSignedPredicate(), llvm::ConstantRange::getSingleElement(), llvm::BasicBlock::getSinglePredecessor(), llvm::CmpInst::getSwappedPredicate(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::ICmpInst::getUnsignedPredicate(), llvm::ConstantInt::getValue(), llvm::Type::getVectorNumElements(), hasBranchUse(), llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::Instruction::hasNoSignedWrap(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ConstantRange::intersectWith(), llvm::Instruction::isArithmeticShift(), llvm::GlobalVariable::isConstant(), llvm::ConstantRange::isEmptySet(), llvm::ICmpInst::isEquality(), llvm::isImpliedCondition(), llvm::isKnownPositive(), llvm::isKnownToBeAPowerOfTwo(), llvm::APInt::isMaxSignedValue(), llvm::APInt::isNegative(), llvm::APInt::isNullValue(), llvm::APInt::isOneValue(), llvm::APInt::isPowerOf2(), llvm::Instruction::isShift(), llvm::isSignBitCheck(), llvm::CmpInst::isSigned(), llvm::APInt::isSignMask(), isSignTest(), llvm::Type::isVectorTy(), llvm::APInt::lshr(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Br(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_IRem(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Signum(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::ConstantRange::makeAllowedICmpRegion(), llvm::ConstantRange::makeExactICmpRegion(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), llvm::KnownBits::One, P, llvm::InstCombiner::replaceInstUsesWith(), llvm::IRBuilderBase::SetInsertPoint(), llvm::User::setOperand(), llvm::APInt::shl(), llvm::SPF_SMIN, llvm::SubOne(), llvm::Value::users(), llvm::RISCVFenceField::W, X, Y, llvm::KnownBits::Zero, and llvm::APInt::zext().
processUMulZExtIdiom()
static Instruction* processUMulZExtIdiom (ICmpInst & I, Value * MulVal, Value * OtherVal, InstCombiner & IC) static
Recognize and process idiom involving test for multiplication overflow.
The caller has matched a pattern of the form: I = cmp u (mul(zext A, zext B), V The function checks if this is a test for overflow and if so replaces multiplication with call to 'mul.with.overflow' intrinsic.
Parameters
I Compare instruction.
MulVal Result of 'mult' instruction. It is one of the arguments of the compare instruction. Must be of integer type.
OtherVal The other argument of compare instruction.
Returns
Instruction which must replace the compare instruction, NULL if no replacement required.
Definition at line 4562 of file InstCombineCompares.cpp.
References llvm::InstCombineWorklist::Add(), assert(), B, llvm::InstCombiner::Builder, llvm::APInt::countLeadingZeros(), llvm::ExtractValueInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::dyn_cast(), llvm::APInt::eq(), F(), llvm::ConstantInt::getBitWidth(), llvm::APInt::getBitWidth(), llvm::Intrinsic::getDeclaration(), llvm::APInt::getMaxValue(), llvm::Instruction::getModule(), llvm::APInt::getOneBitSet(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasNUsesOrMore(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APInt::isPowerOf2(), llvm_unreachable, llvm::APInt::logBase2(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), llvm::IRBuilderBase::SetInsertPoint(), llvm::User::setOperand(), llvm::APInt::trunc(), llvm::Value::user_begin(), llvm::Value::user_end(), llvm::Value::users(), llvm::InstCombiner::Worklist, and llvm::APInt::zext().
rewriteGEPAsOffset()
static Value* rewriteGEPAsOffset (Value * Start, Value * Base, const DataLayout & DL, SetVector< Value *> & Explored) static
Returns a re-written value of Start as an indexed GEP using Base as a pointer.
Definition at line 643 of file InstCombineCompares.cpp.
setInsertionPoint()
static void setInsertionPoint (IRBuilder<> & Builder, Value * V, bool Before = true) static
Definition at line 618 of file InstCombineCompares.cpp.
References assert(), llvm::BasicBlock::getFirstInsertionPt(), I, and llvm::IRBuilderBase::SetInsertPoint().
STATISTIC()
STATISTIC (NumSel , "Number of select opts")
subWithOverflow()
static bool subWithOverflow (APInt & Result, const APInt & In1, const APInt & In2, bool IsSigned = false) static
Compute Result = In1-In2, returning true if the result overflowed for this type.
Definition at line 52 of file InstCombineCompares.cpp.
References llvm::APInt::ssub_ov(), and llvm::APInt::usub_ov().
Referenced by foldICmpShlOne().
swapMayExposeCSEOpportunities()
static bool swapMayExposeCSEOpportunities (const Value * Op0, const Value * Op1) static
Check if the order of Op0 and Op1 as operands in an ICmpInst should be swapped.
The decision is based on how many times these two operands are reused as subtract operands and their positions in those instructions. The rationale is that several architectures use the same instruction for both subtract and cmp. Thus, it is better if the order of those operands match.
Returns
true if Op0 and Op1 should be swapped.
Definition at line 4829 of file InstCombineCompares.cpp.
References llvm::Value::getType(), llvm::Type::isPointerTy(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::match(), and llvm::Value::users().
Referenced by llvm::InstCombiner::visitICmpInst().
transformToIndexedCompare()
static Instruction* transformToIndexedCompare (GEPOperator * GEPLHS, Value * RHS, ICmpInst::Predicate Cond, const DataLayout & DL) static
Converts (CMP GEPLHS, RHS) if this change would make RHS a constant.
We can look through PHIs, GEPs and casts in order to determine a common base between GEPLHS and RHS.
Definition at line 804 of file InstCombineCompares.cpp.