LLVM: lib/Analysis/InstructionSimplify.cpp File Reference
InstructionSimplify.cpp File Reference
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/CmpInstAnalysis.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Support/KnownBits.h"
#include <algorithm>
#include "llvm/IR/Instruction.def"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "instsimplify"
#define HANDLE_CAST_INST(num, opc, clas) case Instruction::opc:
Enumerations
enum { RecursionLimit = 3 }
Functions
STATISTIC (NumExpand, "Number of expansions")
STATISTIC (NumReassoc, "Number of reassociations")
static Value * SimplifyAndInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an And, see if we can fold the result.
static Value * simplifyUnOp (unsigned Opcode, Value *Op, const SimplifyQuery &Q, unsigned MaxRecurse)
Given the operand for a UnaryOperator, see if we can fold the result.
static Value * simplifyFPUnOp (unsigned Opcode, Value *Op, const FastMathFlags &FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given the operand for a UnaryOperator, see if we can fold the result.
static Value * SimplifyBinOp (unsigned Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a BinaryOperator, see if we can fold the result.
static Value * SimplifyBinOp (unsigned Opcode, Value *LHS, Value *RHS, const FastMathFlags &FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a BinaryOperator, see if we can fold the result.
static Value * SimplifyCmpInst (unsigned Predicate, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a CmpInst, see if we can fold the result.
static Value * SimplifyICmpInst (unsigned Predicate, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an ICmpInst, see if we can fold the result.
static Value * SimplifyOrInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Or, see if we can fold the result.
static Value * SimplifyXorInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a Xor, see if we can fold the result.
static Value * SimplifyCastInst (unsigned, Value *, Type *, const SimplifyQuery &, unsigned)
static Value * SimplifyGEPInst (Type *SrcTy, ArrayRef< Value * > Ops, const SimplifyQuery &Q, unsigned)
Given operands for an GetElementPtrInst, see if we can fold the result.
static Value * foldSelectWithBinaryOp (Value *Cond, Value *TrueVal, Value *FalseVal)
static Constant * getFalse (Type *Ty)
For a boolean type or a vector of boolean type, return false or a vector with every element false.
static Constant * getTrue (Type *Ty)
For a boolean type or a vector of boolean type, return true or a vector with every element true.
static bool isSameCompare (Value *V, CmpInst::Predicate Pred, Value *LHS, Value *RHS)
isSameCompare - Is V equivalent to the comparison "LHS Pred RHS"?
static Value * simplifyCmpSelCase (CmpInst::Predicate Pred, Value *LHS, Value *RHS, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse, Constant *TrueOrFalse)
Simplify comparison with true or false branch of select: sel = select i1 cond, i32 tv, i32 fv cmp = icmp sle i32 sel, rhs Compose new comparison by substituting sel with either tv or fv and see if it simplifies.
static Value * simplifyCmpSelTrueCase (CmpInst::Predicate Pred, Value *LHS, Value *RHS, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse)
Simplify comparison with true branch of select.
static Value * simplifyCmpSelFalseCase (CmpInst::Predicate Pred, Value *LHS, Value *RHS, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse)
Simplify comparison with false branch of select.
static Value * handleOtherCmpSelSimplifications (Value *TCmp, Value *FCmp, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse)
We know comparison with both branches of select can be simplified, but they are not equal.
static bool valueDominatesPHI (Value *V, PHINode *P, const DominatorTree *DT)
Does the given value dominate the specified phi node?
static Value * ExpandBinOp (Instruction::BinaryOps Opcode, Value *LHS, Value *RHS, Instruction::BinaryOps OpcodeToExpand, const SimplifyQuery &Q, unsigned MaxRecurse)
Simplify "A op (B op' C)" by distributing op over op', turning it into "(A op B) op' (A op C)".
static Value * SimplifyAssociativeBinOp (Instruction::BinaryOps Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Generic simplifications for associative binary operations.
static Value * ThreadBinOpOverSelect (Instruction::BinaryOps Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a binary operation with a select instruction as an operand, try to simplify the binop by seeing whether evaluating it on both branches of the select results in the same value.
static Value * ThreadCmpOverSelect (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a comparison with a select instruction, try to simplify the comparison by seeing whether both branches of the select result in the same value.
static Value * ThreadBinOpOverPHI (Instruction::BinaryOps Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a binary operation with an operand that is a PHI instruction, try to simplify the binop by seeing whether evaluating it on the incoming phi values yields the same result for every value.
static Value * ThreadCmpOverPHI (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a comparison with a PHI instruction, try to simplify the comparison by seeing whether comparing with all of the incoming phi values yields the same result every time.
static Constant * foldOrCommuteConstant (Instruction::BinaryOps Opcode, Value *&Op0, Value *&Op1, const SimplifyQuery &Q)
static Value * SimplifyAddInst (Value *Op0, Value *Op1, bool IsNSW, bool IsNUW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Add, see if we can fold the result.
static Constant * stripAndComputeConstantOffsets (const DataLayout &DL, Value *&V, bool AllowNonInbounds=false)
Compute the base pointer and cumulative constant offsets for V.
static Constant * computePointerDifference (const DataLayout &DL, Value *LHS, Value *RHS)
Compute the constant difference between two pointer values.
static Value * SimplifySubInst (Value *Op0, Value *Op1, bool isNSW, bool isNUW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a Sub, see if we can fold the result.
static Value * SimplifyMulInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a Mul, see if we can fold the result.
static Value * simplifyDivRem (Value *Op0, Value *Op1, bool IsDiv)
Check for common or similar folds of integer division or integer remainder.
static bool isICmpTrue (ICmpInst::Predicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given a predicate and two operands, return true if the comparison is true.
static bool isDivZero (Value *X, Value *Y, const SimplifyQuery &Q, unsigned MaxRecurse, bool IsSigned)
Return true if we can simplify X / Y to 0.
static Value * simplifyDiv (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
These are simplifications common to SDiv and UDiv.
static Value * simplifyRem (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
These are simplifications common to SRem and URem.
static Value * SimplifySDivInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an SDiv, see if we can fold the result.
static Value * SimplifyUDivInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a UDiv, see if we can fold the result.
static Value * SimplifySRemInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an SRem, see if we can fold the result.
static Value * SimplifyURemInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a URem, see if we can fold the result.
static bool isUndefShift (Value *Amount)
Returns true if a shift by Amount always yields undef.
static Value * SimplifyShift (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Shl, LShr or AShr, see if we can fold the result.
static Value * SimplifyRightShift (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, bool isExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Shl, LShr or AShr, see if we can fold the result.
static Value * SimplifyShlInst (Value *Op0, Value *Op1, bool isNSW, bool isNUW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Shl, see if we can fold the result.
static Value * SimplifyLShrInst (Value *Op0, Value *Op1, bool isExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an LShr, see if we can fold the result.
static Value * SimplifyAShrInst (Value *Op0, Value *Op1, bool isExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an AShr, see if we can fold the result.
static Value * simplifyUnsignedRangeCheck (ICmpInst *ZeroICmp, ICmpInst *UnsignedICmp, bool IsAnd, const SimplifyQuery &Q)
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
static Value * simplifyAndOfICmpsWithSameOperands (ICmpInst *Op0, ICmpInst *Op1)
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
static Value * simplifyOrOfICmpsWithSameOperands (ICmpInst *Op0, ICmpInst *Op1)
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
static Value * simplifyAndOrOfICmpsWithConstants (ICmpInst *Cmp0, ICmpInst *Cmp1, bool IsAnd)
Test if a pair of compares with a shared operand and 2 constants has an empty set intersection, full set union, or if one compare is a superset of the other.
static Value * simplifyAndOrOfICmpsWithZero (ICmpInst *Cmp0, ICmpInst *Cmp1, bool IsAnd)
static Value * simplifyAndOfICmpsWithAdd (ICmpInst *Op0, ICmpInst *Op1, const InstrInfoQuery &IIQ)
static Value * simplifyAndOfICmps (ICmpInst *Op0, ICmpInst *Op1, const SimplifyQuery &Q)
static Value * simplifyOrOfICmpsWithAdd (ICmpInst *Op0, ICmpInst *Op1, const InstrInfoQuery &IIQ)
static Value * simplifyOrOfICmps (ICmpInst *Op0, ICmpInst *Op1, const SimplifyQuery &Q)
static Value * simplifyAndOrOfFCmps (const TargetLibraryInfo *TLI, FCmpInst *LHS, FCmpInst *RHS, bool IsAnd)
static Value * simplifyAndOrOfCmps (const SimplifyQuery &Q, Value *Op0, Value *Op1, bool IsAnd)
static bool omitCheckForZeroBeforeMulWithOverflowInternal (Value *Op1, Value *X)
Check that the Op1 is in expected form, i.e.
static Value * omitCheckForZeroBeforeMulWithOverflow (Value *Op0, Value *Op1)
The .
static Value * omitCheckForZeroBeforeInvertedMulWithOverflow (Value *Op0, Value *NotOp1)
The .
static Type * GetCompareTy (Value *Op)
static Value * ExtractEquivalentCondition (Value *V, CmpInst::Predicate Pred, Value *LHS, Value *RHS)
Rummage around inside V looking for something equivalent to the comparison "LHS Pred RHS".
static Constant * computePointerICmp (const DataLayout &DL, const TargetLibraryInfo *TLI, const DominatorTree *DT, CmpInst::Predicate Pred, AssumptionCache *AC, const Instruction *CxtI, const InstrInfoQuery &IIQ, Value *LHS, Value *RHS)
static Value * simplifyICmpOfBools (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q)
Fold an icmp when its operands have i1 scalar type.
static Value * simplifyICmpWithZero (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q)
Try hard to fold icmp with zero RHS because this is a common case.
static Value * simplifyICmpWithConstant (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const InstrInfoQuery &IIQ)
static Value * simplifyICmpWithBinOp (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
TODO: A large part of this logic is duplicated in InstCombine's foldICmpBinOp().
static Value * simplifyICmpWithMinMax (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Simplify integer comparisons where at least one operand of the compare matches an integer min/max idiom.
static Value * SimplifyFCmpInst (unsigned Predicate, Value *LHS, Value *RHS, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an FCmpInst, see if we can fold the result.
static const Value * SimplifyWithOpReplaced (Value *V, Value *Op, Value *RepOp, const SimplifyQuery &Q, unsigned MaxRecurse)
See if V simplifies when its operand Op is replaced with RepOp.
static Value * simplifySelectBitTest (Value *TrueVal, Value *FalseVal, Value *X, const APInt *Y, bool TrueWhenUnset)
Try to simplify a select instruction when its condition operand is an integer comparison where one operand of the compare is a constant.
static Value * simplifySelectWithFakeICmpEq (Value *CmpLHS, Value *CmpRHS, ICmpInst::Predicate Pred, Value *TrueVal, Value *FalseVal)
An alternative way to test if a bit is set or not uses sgt/slt instead of eq/ne.
static Value * simplifySelectWithICmpCond (Value *CondVal, Value *TrueVal, Value *FalseVal, const SimplifyQuery &Q, unsigned MaxRecurse)
Try to simplify a select instruction when its condition operand is an integer comparison.
static Value * simplifySelectWithFCmp (Value *Cond, Value *T, Value *F, const SimplifyQuery &Q)
Try to simplify a select instruction when its condition operand is a floating-point comparison.
static Value * SimplifySelectInst (Value *Cond, Value *TrueVal, Value *FalseVal, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a SelectInst, see if we can fold the result.
static Value * SimplifyInsertValueInst (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const SimplifyQuery &Q, unsigned)
Given operands for an InsertValueInst, see if we can fold the result.
static Value * SimplifyExtractValueInst (Value *Agg, ArrayRef< unsigned > Idxs, const SimplifyQuery &, unsigned)
Given operands for an ExtractValueInst, see if we can fold the result.
static Value * SimplifyExtractElementInst (Value *Vec, Value *Idx, const SimplifyQuery &, unsigned)
Given operands for an ExtractElementInst, see if we can fold the result.
static Value * SimplifyPHINode (PHINode *PN, const SimplifyQuery &Q)
See if we can fold the given phi. If not, returns null.
static Value * foldIdentityShuffles (int DestElt, Value *Op0, Value *Op1, int MaskVal, Value *RootVec, unsigned MaxRecurse)
For the given destination element of a shuffle, peek through shuffles to match a root vector source operand that contains that element in the same vector lane (ie, the same mask index), so we can eliminate the shuffle(s).
static Value * SimplifyShuffleVectorInst (Value *Op0, Value *Op1, Constant *Mask, Type *RetTy, const SimplifyQuery &Q, unsigned MaxRecurse)
static Constant * foldConstant (Instruction::UnaryOps Opcode, Value *&Op, const SimplifyQuery &Q)
static Value * simplifyFNegInst (Value *Op, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given the operand for an FNeg, see if we can fold the result.
static Constant * propagateNaN (Constant *In)
static Constant * simplifyFPOp (ArrayRef< Value *> Ops)
Perform folds that are common to any floating-point operation.
static Value * SimplifyFAddInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an FAdd, see if we can fold the result.
static Value * SimplifyFSubInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an FSub, see if we can fold the result.
static Value * SimplifyFMAFMul (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
static Value * SimplifyFMulInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given the operands for an FMul, see if we can fold the result.
static Value * SimplifyFDivInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned)
static Value * SimplifyFRemInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned)
static bool IsIdempotent (Intrinsic::ID ID)
static Value * SimplifyRelativeLoad (Constant *Ptr, Constant *Offset, const DataLayout &DL)
static Value * simplifyUnaryIntrinsic (Function *F, Value *Op0, const SimplifyQuery &Q)
static Value * simplifyBinaryIntrinsic (Function *F, Value *Op0, Value *Op1, const SimplifyQuery &Q)
static Value * simplifyIntrinsic (CallBase *Call, const SimplifyQuery &Q)
static Value * SimplifyFreezeInst (Value *Op0)
Given operands for a Freeze, see if we can fold the result.
static bool replaceAndRecursivelySimplifyImpl (Instruction *I, Value *SimpleV, const TargetLibraryInfo *TLI, const DominatorTree *DT, AssumptionCache *AC, SmallSetVector< Instruction *, 8 > *UnsimplifiedUsers=nullptr)
Implementation of recursive simplification through an instruction's uses.
const SimplifyQuery llvm::getBestSimplifyQuery (Pass &, Function &)
const SimplifyQuery llvm::getBestSimplifyQuery (LoopStandardAnalysisResults &, const DataLayout &)
template<class T , class... TArgs>
const SimplifyQuery llvm::getBestSimplifyQuery (AnalysisManager< T, TArgs... > &, Function &)
template const SimplifyQuery llvm::getBestSimplifyQuery (AnalysisManager< Function > &, Function &)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instsimplify"
Definition at line 46 of file InstructionSimplify.cpp.
HANDLE_CAST_INST
#define HANDLE_CAST_INST (num, opc, clas) case Instruction::opc:
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RecursionLimit
Definition at line 48 of file InstructionSimplify.cpp.
Function Documentation
computePointerDifference()
static Constant* computePointerDifference (const DataLayout & DL, Value * LHS, Value * RHS) static
Compute the constant difference between two pointer values.
If the difference is not a constant, returns zero.
Definition at line 718 of file InstructionSimplify.cpp.
References llvm::ConstantExpr::getSub(), and stripAndComputeConstantOffsets().
Referenced by SimplifySubInst().
computePointerICmp()
static Constant* computePointerICmp (const DataLayout & DL, const TargetLibraryInfo * TLI, const DominatorTree * DT, CmpInst::Predicate Pred, AssumptionCache * AC, const Instruction * CxtI, const InstrInfoQuery & IIQ, Value * LHS, Value * RHS) static
Definition at line 2341 of file InstructionSimplify.cpp.
References A, llvm::all_of(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantExpr::getAdd(), GetCompareTy(), getFunction(), llvm::ConstantExpr::getICmp(), llvm::getObjectSize(), llvm::ICmpInst::getSignedPredicate(), llvm::Value::getType(), llvm::GetUnderlyingObjects(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isAllocLikeFn(), llvm::CmpInst::isFalseWhenEqual(), llvm::isKnownNonZero(), llvm::APInt::isNegative(), llvm::isNoAliasCall(), llvm::Constant::isNullValue(), llvm::CmpInst::isTrueWhenEqual(), MI, llvm::ObjectSizeOpts::NullIsUnknownSize, llvm::NullPointerIsDefined(), llvm::PointerMayBeCaptured(), stripAndComputeConstantOffsets(), llvm::Value::stripPointerCasts(), llvm::APInt::ult(), and llvm::InstrInfoQuery::UseInstrInfo.
Referenced by SimplifyICmpInst().
ExpandBinOp()
static Value* ExpandBinOp (Instruction::BinaryOps Opcode, Value * LHS, Value * RHS, Instruction::BinaryOps OpcodeToExpand, const SimplifyQuery & Q, unsigned MaxRecurse) static
Simplify "A op (B op' C)" by distributing op over op', turning it into "(A op B) op' (A op C)".
Here "op" is given by Opcode and "op'" is given by OpcodeToExpand, while "A" corresponds to LHS and "B op' C" to RHS. Also performs the transform "(A op' B) op C" -> "(A op C) op' (B op C)". Returns the simplified value, or null if no simplification was performed.
Definition at line 236 of file InstructionSimplify.cpp.
References A, B, C, llvm::User::getOperand(), llvm::Instruction::isCommutative(), llvm::RISCVFenceField::R, and llvm::SimplifyBinOp().
Referenced by SimplifyAndInst(), SimplifyMulInst(), and SimplifyOrInst().
ExtractEquivalentCondition()
static Value* ExtractEquivalentCondition (Value * V, CmpInst::Predicate Pred, Value * LHS, Value * RHS) static
Rummage around inside V looking for something equivalent to the comparison "LHS Pred RHS".
Return such a value if found, otherwise return null. Helper function for analyzing max/min idioms.
Definition at line 2295 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::SelectInst::getCondition(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), and SI.
Referenced by simplifyICmpWithMinMax().
foldConstant()
static Constant* foldConstant (Instruction::UnaryOps Opcode, Value *& Op, const SimplifyQuery & Q) static
Definition at line 4525 of file InstructionSimplify.cpp.
References C, llvm::ConstantFoldUnaryOpOperand(), and llvm::SimplifyQuery::DL.
Referenced by llvm::IRBuilder< TargetFolder >::CreateBinOp(), llvm::IRBuilder< TargetFolder >::CreateFAdd(), llvm::IRBuilder< TargetFolder >::CreateFAddFMF(), llvm::IRBuilder< TargetFolder >::CreateFDiv(), llvm::IRBuilder< TargetFolder >::CreateFDivFMF(), llvm::IRBuilder< TargetFolder >::CreateFMul(), llvm::IRBuilder< TargetFolder >::CreateFMulFMF(), llvm::IRBuilder< TargetFolder >::CreateFRem(), llvm::IRBuilder< TargetFolder >::CreateFRemFMF(), llvm::IRBuilder< TargetFolder >::CreateFSub(), llvm::IRBuilder< TargetFolder >::CreateFSubFMF(), llvm::IRBuilder< TargetFolder >::CreateSRem(), llvm::IRBuilder< TargetFolder >::CreateUnreachable(), llvm::IRBuilder< TargetFolder >::CreateURem(), llvm::IRBuilder< TargetFolder >::CreateXor(), and simplifyFNegInst().
foldIdentityShuffles()
static Value* foldIdentityShuffles (int DestElt, Value * Op0, Value * Op1, int MaskVal, Value * RootVec, unsigned MaxRecurse) static
For the given destination element of a shuffle, peek through shuffles to match a root vector source operand that contains that element in the same vector lane (ie, the same mask index), so we can eliminate the shuffle(s).
Definition at line 4371 of file InstructionSimplify.cpp.
References llvm::Value::getType(), and llvm::Type::getVectorNumElements().
Referenced by SimplifyShuffleVectorInst().
foldOrCommuteConstant()
static Constant* foldOrCommuteConstant (Instruction::BinaryOps Opcode, Value *& Op0, Value *& Op1, const SimplifyQuery & Q) static
Definition at line 601 of file InstructionSimplify.cpp.
References llvm::ConstantFoldBinaryOpOperands(), llvm::SimplifyQuery::DL, llvm::Instruction::isCommutative(), and std::swap().
Referenced by SimplifyAddInst(), SimplifyAndInst(), simplifyDiv(), SimplifyFAddInst(), SimplifyFDivInst(), SimplifyFMulInst(), SimplifyFRemInst(), SimplifyFSubInst(), SimplifyMulInst(), SimplifyOrInst(), simplifyRem(), SimplifyShift(), SimplifySubInst(), and SimplifyXorInst().
foldSelectWithBinaryOp()
static Value* foldSelectWithBinaryOp (Value * Cond, Value * TrueVal, Value * FalseVal) static
Definition at line 72 of file InstructionSimplify.cpp.
GetCompareTy()
static Type* GetCompareTy (Value * Op) static
Definition at line 2288 of file InstructionSimplify.cpp.
References llvm::Value::getType(), and llvm::CmpInst::makeCmpResultType().
Referenced by computePointerICmp(), SimplifyFCmpInst(), SimplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), simplifyICmpWithMinMax(), and simplifyICmpWithZero().
getFalse()
static Constant* getFalse (Type * Ty) static
For a boolean type or a vector of boolean type, return false or a vector with every element false.
Definition at line 116 of file InstructionSimplify.cpp.
References llvm::ConstantInt::getFalse().
Referenced by simplifyAndOfICmpsWithAdd(), simplifyAndOfICmpsWithSameOperands(), simplifyAndOrOfICmpsWithConstants(), SimplifyFCmpInst(), SimplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), and simplifyUnsignedRangeCheck().
getTrue()
static Constant* getTrue (Type * Ty) static
For a boolean type or a vector of boolean type, return true or a vector with every element true.
Definition at line 122 of file InstructionSimplify.cpp.
References llvm::ConstantInt::getTrue().
Referenced by simplifyAndOrOfICmpsWithConstants(), SimplifyFCmpInst(), SimplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), simplifyOrOfICmpsWithAdd(), simplifyOrOfICmpsWithSameOperands(), and simplifyUnsignedRangeCheck().
handleOtherCmpSelSimplifications()
static Value* handleOtherCmpSelSimplifications (Value * TCmp, Value * FCmp, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse) static
We know comparison with both branches of select can be simplified, but they are not equal.
This routine handles some logical simplifications.
Definition at line 181 of file InstructionSimplify.cpp.
isDivZero()
static bool isDivZero (Value * X, Value * Y, const SimplifyQuery & Q, unsigned MaxRecurse, bool IsSigned) static
Return true if we can simplify X / Y to 0.
Remainder can adapt that answer to simplify X % Y to X.
Definition at line 998 of file InstructionSimplify.cpp.
References llvm::APInt::abs(), C, llvm::ConstantInt::get(), llvm::Value::getType(), llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULT, isICmpTrue(), llvm::APInt::isMinSignedValue(), llvm::PatternMatch::m_APInt(), and llvm::PatternMatch::match().
Referenced by simplifyDiv(), and simplifyRem().
isICmpTrue()
static bool isICmpTrue (ICmpInst::Predicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given a predicate and two operands, return true if the comparison is true.
This is a helper for div/rem simplification where we return some other value when we can prove a relationship between the operands.
Definition at line 989 of file InstructionSimplify.cpp.
References C, llvm::Constant::isAllOnesValue(), and llvm::SimplifyICmpInst().
Referenced by isDivZero().
IsIdempotent()
static bool IsIdempotent (Intrinsic::ID ID) static
Definition at line 4933 of file InstructionSimplify.cpp.
References round().
Referenced by simplifyUnaryIntrinsic().
isSameCompare()
static bool isSameCompare (Value * V, CmpInst::Predicate Pred, Value * LHS, Value * RHS) static
isSameCompare - Is V equivalent to the comparison "LHS Pred RHS"?
Definition at line 127 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), and llvm::CmpInst::getSwappedPredicate().
isUndefShift()
static bool isUndefShift (Value * Amount) static
Returns true if a shift by Amount always yields undef.
Definition at line 1208 of file InstructionSimplify.cpp.
References C, llvm::dyn_cast(), E, llvm::Constant::getAggregateElement(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and I.
Referenced by SimplifyShift().
omitCheckForZeroBeforeInvertedMulWithOverflow()
static Value* omitCheckForZeroBeforeInvertedMulWithOverflow (Value * Op0, Value * NotOp1) static
The .
[us]mul.with.overflow intrinsic could have been folded from some other form of check, e.g. one that was using division; it may have been guarded against division-by-zero. We can drop that check now. Look for: Op0 = icmp eq i4 X, 0 Agg = tail call { i4, i1 } .[us]mul.with.overflow.i4(i4 X, i4 %???) Op1 = extractvalue { i4, i1 } Agg, 1 NotOp1 = xor i1 Op1, true or = or i1 Op0, NotOp1 We can just return NotOp1
Definition at line 1924 of file InstructionSimplify.cpp.
References llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), omitCheckForZeroBeforeMulWithOverflowInternal(), and X.
Referenced by SimplifyOrInst().
omitCheckForZeroBeforeMulWithOverflow()
static Value* omitCheckForZeroBeforeMulWithOverflow (Value * Op0, Value * Op1) static
The .
[us]mul.with.overflow intrinsic could have been folded from some other form of check, e.g. one that was using division; it may have been guarded against division-by-zero. We can drop that check now. Look for: Op0 = icmp ne i4 X, 0 Agg = tail call { i4, i1 } .[us]mul.with.overflow.i4(i4 X, i4 %???) Op1 = extractvalue { i4, i1 } Agg, 1 %??? = and i1 Op0, Op1 We can just return Op1
Definition at line 1901 of file InstructionSimplify.cpp.
References llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), omitCheckForZeroBeforeMulWithOverflowInternal(), and X.
Referenced by SimplifyAndInst().
omitCheckForZeroBeforeMulWithOverflowInternal()
static bool omitCheckForZeroBeforeMulWithOverflowInternal (Value * Op1, Value * X) static
Check that the Op1 is in expected form, i.e.
: Agg = tail call { i4, i1 } .[us]mul.with.overflow.i4(i4 X, i4 %???) Op1 = extractvalue { i4, i1 } Agg, 1
Definition at line 1874 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Specific(), and llvm::PatternMatch::match().
Referenced by omitCheckForZeroBeforeInvertedMulWithOverflow(), and omitCheckForZeroBeforeMulWithOverflow().
propagateNaN()
static Constant* propagateNaN (Constant * In) static
Definition at line 4552 of file InstructionSimplify.cpp.
References llvm::ConstantFP::getNaN(), llvm::Value::getType(), llvm::tgtok::In, and llvm::Constant::isNaN().
Referenced by simplifyFPOp().
replaceAndRecursivelySimplifyImpl()
static bool replaceAndRecursivelySimplifyImpl (Instruction * I, Value * SimpleV, const TargetLibraryInfo * TLI, const DominatorTree * DT, AssumptionCache * AC, SmallSetVector< Instruction *, 8 > * UnsimplifiedUsers = nullptr) static
Implementation of recursive simplification through an instruction's uses.
This is the common implementation of the recursive simplification routines. If we have a pre-simplified value in 'SimpleV', that is forcibly used to replace the instruction 'I'. Otherwise, we simply add 'I' to the list of instructions to process and attempt to simplify it using InstructionSimplify. Recursively visited users which could not be simplified themselves are to the optional UnsimplifiedUsers set for further processing by the caller.
This routine returns 'true' only when it simplifies something. The passed in simplified value does not count toward this.
Definition at line 5519 of file InstructionSimplify.cpp.
References llvm::Instruction::eraseFromParent(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::Instruction::getParent(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::Instruction::isEHPad(), llvm::Instruction::isTerminator(), llvm::Instruction::mayHaveSideEffects(), llvm::Value::replaceAllUsesWith(), llvm::JumpTable::Simplified, llvm::SimplifyInstruction(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::size(), and llvm::Value::users().
Referenced by llvm::recursivelySimplifyInstruction(), and llvm::replaceAndRecursivelySimplify().
SimplifyAddInst()
static Value* SimplifyAddInst (Value * Op0, Value * Op1, bool IsNSW, bool IsNUW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Add, see if we can fold the result.
If not, this returns null.
i1 add -> xor.
Definition at line 617 of file InstructionSimplify.cpp.
References llvm::MCID::Add, C, foldOrCommuteConstant(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), llvm::isKnownNegation(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), SimplifyAssociativeBinOp(), llvm::SimplifyXorInst(), and Y.
Referenced by llvm::SimplifyAddInst().
SimplifyAndInst()
static Value * SimplifyAndInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an And, see if we can fold the result.
If not, this returns null.
Definition at line 1944 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, C, llvm::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, ExpandBinOp(), foldOrCommuteConstant(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::Constant::getNullValue(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::APInt::intersects(), llvm::isKnownToBeAPowerOfTwo(), llvm::APInt::isSubsetOf(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), omitCheckForZeroBeforeMulWithOverflow(), simplifyAndOrOfCmps(), SimplifyAssociativeBinOp(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), X, and Y.
Referenced by llvm::SimplifyAndInst().
simplifyAndOfICmps()
static Value* simplifyAndOfICmps (ICmpInst * Op0, ICmpInst * Op1, const SimplifyQuery & Q) static
Definition at line 1698 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::IIQ, simplifyAndOfICmpsWithAdd(), simplifyAndOfICmpsWithSameOperands(), simplifyAndOrOfICmpsWithConstants(), simplifyAndOrOfICmpsWithZero(), simplifyUnsignedRangeCheck(), and X.
Referenced by simplifyAndOrOfCmps().
simplifyAndOfICmpsWithAdd()
static Value* simplifyAndOfICmpsWithAdd (ICmpInst * Op0, ICmpInst * Op1, const InstrInfoQuery & IIQ) static
Definition at line 1651 of file InstructionSimplify.cpp.
References getFalse(), llvm::User::getOperand(), llvm::Value::getType(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by simplifyAndOfICmps().
simplifyAndOfICmpsWithSameOperands()
static Value* simplifyAndOfICmpsWithSameOperands (ICmpInst * Op0, ICmpInst * Op1) static
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
Definition at line 1525 of file InstructionSimplify.cpp.
References A, B, getFalse(), llvm::CmpInst::getInversePredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::CmpInst::isFalseWhenEqual(), llvm::CmpInst::isImpliedTrueByMatchingCmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by simplifyAndOfICmps().
simplifyAndOrOfCmps()
static Value* simplifyAndOrOfCmps (const SimplifyQuery & Q, Value * Op0, Value * Op1, bool IsAnd) static
Definition at line 1835 of file InstructionSimplify.cpp.
References C, llvm::dyn_cast(), llvm::ConstantExpr::getCast(), llvm::Value::getType(), simplifyAndOfICmps(), simplifyAndOrOfFCmps(), simplifyOrOfICmps(), and llvm::SimplifyQuery::TLI.
Referenced by SimplifyAndInst(), and SimplifyOrInst().
simplifyAndOrOfFCmps()
static Value* simplifyAndOrOfFCmps (const TargetLibraryInfo * TLI, FCmpInst * LHS, FCmpInst * RHS, bool IsAnd) static
Definition at line 1797 of file InstructionSimplify.cpp.
References llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UNO, llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), and llvm::isKnownNeverNaN().
Referenced by simplifyAndOrOfCmps().
simplifyAndOrOfICmpsWithConstants()
static Value* simplifyAndOrOfICmpsWithConstants (ICmpInst * Cmp0, ICmpInst * Cmp1, bool IsAnd) static
Test if a pair of compares with a shared operand and 2 constants has an empty set intersection, full set union, or if one compare is a superset of the other.
Definition at line 1577 of file InstructionSimplify.cpp.
References getFalse(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), getTrue(), llvm::Value::getType(), llvm::PatternMatch::m_APInt(), llvm::ConstantRange::makeExactICmpRegion(), and llvm::PatternMatch::match().
Referenced by simplifyAndOfICmps(), and simplifyOrOfICmps().
simplifyAndOrOfICmpsWithZero()
static Value* simplifyAndOrOfICmpsWithZero (ICmpInst * Cmp0, ICmpInst * Cmp1, bool IsAnd) static
Definition at line 1614 of file InstructionSimplify.cpp.
References llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), X, and Y.
Referenced by simplifyAndOfICmps(), and simplifyOrOfICmps().
SimplifyAShrInst()
static Value* SimplifyAShrInst (Value * Op0, Value * Op1, bool isExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an AShr, see if we can fold the result.
If not, this returns null.
Definition at line 1383 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::ComputeNumSignBits(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::Constant::getAllOnesValue(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::SimplifyQuery::IIQ, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), SimplifyRightShift(), llvm::InstrInfoQuery::UseInstrInfo, and X.
Referenced by llvm::SimplifyAShrInst().
SimplifyAssociativeBinOp()
static Value* SimplifyAssociativeBinOp (Instruction::BinaryOps Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Generic simplifications for associative binary operations.
Returns the simpler value, or null if none was found.
Definition at line 294 of file InstructionSimplify.cpp.
References A, assert(), B, C, llvm::dyn_cast(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), llvm::SimplifyBinOp(), and llvm::RISCVFenceField::W.
Referenced by SimplifyAddInst(), SimplifyAndInst(), SimplifyMulInst(), SimplifyOrInst(), and SimplifyXorInst().
simplifyBinaryIntrinsic()
static Value* simplifyBinaryIntrinsic (Function * F, Value * Op0, Value * Op1, const SimplifyQuery & Q) static
Definition at line 5079 of file InstructionSimplify.cpp.
References C, llvm::SimplifyQuery::DL, llvm::ConstantFP::get(), llvm::ConstantStruct::get(), llvm::UndefValue::get(), llvm::Constant::getAllOnesValue(), llvm::ConstantFP::getInfinity(), llvm::Function::getIntrinsicID(), llvm::Constant::getNullValue(), llvm::Function::getReturnType(), llvm::Type::getStructElementType(), llvm::Value::getType(), llvm::APFloat::isInfinity(), llvm::APFloat::isNegative(), LLVM_FALLTHROUGH, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_NaN(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::maximum(), llvm::maxnum(), llvm::minimum(), llvm::minnum(), and SimplifyRelativeLoad().
Referenced by simplifyIntrinsic().
SimplifyBinOp() [1/2]
static Value * SimplifyBinOp (unsigned Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a BinaryOperator, see if we can fold the result.
If not, this returns null.
Definition at line 4846 of file InstructionSimplify.cpp.
References llvm::MCID::Add, llvm_unreachable, llvm::SimplifyAddInst(), llvm::SimplifyAndInst(), llvm::SimplifyAShrInst(), llvm::SimplifyFAddInst(), llvm::SimplifyFDivInst(), llvm::SimplifyFMulInst(), llvm::SimplifyFRemInst(), llvm::SimplifyFSubInst(), llvm::SimplifyLShrInst(), llvm::SimplifyMulInst(), llvm::SimplifyOrInst(), llvm::SimplifySDivInst(), llvm::SimplifyShlInst(), llvm::SimplifySRemInst(), llvm::SimplifySubInst(), llvm::SimplifyUDivInst(), llvm::SimplifyURemInst(), and llvm::SimplifyXorInst().
Referenced by llvm::SimplifyBinOp().
SimplifyBinOp() [2/2]
static Value * SimplifyBinOp (unsigned Opcode, Value * LHS, Value * RHS, const FastMathFlags & FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a BinaryOperator, see if we can fold the result.
If not, this returns null. Try to use FastMathFlags when folding the result.
Definition at line 4893 of file InstructionSimplify.cpp.
References llvm::SimplifyBinOp(), llvm::SimplifyFAddInst(), llvm::SimplifyFDivInst(), llvm::SimplifyFMulInst(), and llvm::SimplifyFSubInst().
SimplifyCastInst()
static Value * SimplifyCastInst (unsigned CastOpc, Value * Op, Type * Ty, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 4329 of file InstructionSimplify.cpp.
References C, llvm::ConstantFoldCastOperand(), llvm::SimplifyQuery::DL, llvm::DataLayout::getIntPtrType(), llvm::Value::getType(), llvm::CastInst::isEliminableCastPair(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::SimplifyCastInst().
SimplifyCmpInst()
static Value * SimplifyCmpInst (unsigned Predicate, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a CmpInst, see if we can fold the result.
Definition at line 4921 of file InstructionSimplify.cpp.
References llvm::CmpInst::isIntPredicate(), llvm::SimplifyFCmpInst(), and llvm::SimplifyICmpInst().
Referenced by llvm::SimplifyCmpInst().
simplifyCmpSelCase()
static Value* simplifyCmpSelCase (CmpInst::Predicate Pred, Value * LHS, Value * RHS, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse, Constant * TrueOrFalse) static
Simplify comparison with true or false branch of select: sel = select i1 cond, i32 tv, i32 fv cmp = icmp sle i32 sel, rhs Compose new comparison by substituting sel with either tv or fv and see if it simplifies.
Definition at line 145 of file InstructionSimplify.cpp.
simplifyCmpSelFalseCase()
static Value* simplifyCmpSelFalseCase (CmpInst::Predicate Pred, Value * LHS, Value * RHS, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse) static
Simplify comparison with false branch of select.
Definition at line 171 of file InstructionSimplify.cpp.
simplifyCmpSelTrueCase()
static Value* simplifyCmpSelTrueCase (CmpInst::Predicate Pred, Value * LHS, Value * RHS, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse) static
Simplify comparison with true branch of select.
Definition at line 162 of file InstructionSimplify.cpp.
simplifyDiv()
static Value* simplifyDiv (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
These are simplifications common to SDiv and UDiv.
Definition at line 1049 of file InstructionSimplify.cpp.
References C, foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::SimplifyQuery::IIQ, isDivZero(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), simplifyDivRem(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), llvm::APInt::umul_ov(), and X.
Referenced by SimplifySDivInst(), and SimplifyUDivInst().
simplifyDivRem()
static Value* simplifyDivRem (Value * Op0, Value * Op1, bool IsDiv) static
Check for common or similar folds of integer division or integer remainder.
This applies to all 4 opcodes (sdiv/udiv/srem/urem).
Definition at line 932 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::Constant::getAggregateElement(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isIntOrIntVectorTy(), llvm::Constant::isNullValue(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), and X.
Referenced by simplifyDiv(), and simplifyRem().
SimplifyExtractElementInst()
static Value* SimplifyExtractElementInst (Value * Vec, Value * Idx, const SimplifyQuery & , unsigned) static
Given operands for an ExtractElementInst, see if we can fold the result.
If not, this returns null.
Definition at line 4259 of file InstructionSimplify.cpp.
References llvm::ConstantFoldExtractElementInstruction(), llvm::findScalarElement(), llvm::UndefValue::get(), llvm::Value::getType(), llvm::Type::getVectorElementType(), and llvm::Type::getVectorNumElements().
Referenced by llvm::SimplifyExtractElementInst().
SimplifyExtractValueInst()
static Value* SimplifyExtractValueInst (Value * Agg, ArrayRef< unsigned > Idxs, const SimplifyQuery & , unsigned) static
Given operands for an ExtractValueInst, see if we can fold the result.
If not, this returns null.
Definition at line 4229 of file InstructionSimplify.cpp.
References llvm::ConstantFoldExtractValueInstruction(), llvm::dyn_cast(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::SimplifyExtractValueInst().
SimplifyFAddInst()
static Value* SimplifyFAddInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an FAdd, see if we can fold the result.
If not, this returns null.
Definition at line 4578 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), C, llvm::CannotBeNegativeZero(), foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_NegZeroFP(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), simplifyFPOp(), llvm::SimplifyQuery::TLI, and X.
Referenced by llvm::SimplifyFAddInst().
SimplifyFCmpInst()
static Value* SimplifyFCmpInst (unsigned Predicate, Value * LHS, Value * RHS, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an FCmpInst, see if we can fold the result.
If not, this returns null.
Definition at line 3517 of file InstructionSimplify.cpp.
References assert(), C, llvm::CannotBeOrderedLessThanZero(), llvm::APFloatBase::cmpGreaterThan, llvm::APFloatBase::cmpLessThan, llvm::APFloat::compare(), llvm::ConstantFoldCompareInstOperands(), llvm::SimplifyQuery::DL, llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::ConstantInt::get(), GetCompareTy(), getFalse(), getIntrinsicID(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::CmpInst::isFalseWhenEqual(), llvm::CmpInst::isFPPredicate(), llvm::APFloat::isInfinity(), llvm::isKnownNeverNaN(), llvm::APFloat::isNaN(), llvm::APFloat::isNegative(), llvm::APFloat::isNegZero(), llvm::CmpInst::isOrdered(), llvm::CmpInst::isTrueWhenEqual(), llvm::CmpInst::isUnordered(), llvm_unreachable, llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_NaN(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::maxnum(), llvm::FastMathFlags::noNaNs(), std::swap(), ThreadCmpOverPHI(), ThreadCmpOverSelect(), and llvm::SimplifyQuery::TLI.
Referenced by llvm::SimplifyFCmpInst().
SimplifyFDivInst()
static Value* SimplifyFDivInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned) static
Definition at line 4734 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), C, foldOrCommuteConstant(), llvm::ConstantFP::get(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_FNegNSZ(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), simplifyFPOp(), and X.
Referenced by llvm::SimplifyFDivInst().
SimplifyFMAFMul()
static Value* SimplifyFMAFMul (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 4670 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), C, llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), simplifyFPOp(), and X.
Referenced by llvm::SimplifyFMAFMul().
SimplifyFMulInst()
static Value* SimplifyFMulInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given the operands for an FMul, see if we can fold the result.
Definition at line 4704 of file InstructionSimplify.cpp.
References C, foldOrCommuteConstant(), and llvm::SimplifyFMAFMul().
Referenced by llvm::SimplifyFMulInst().
simplifyFNegInst()
static Value* simplifyFNegInst (Value * Op, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given the operand for an FNeg, see if we can fold the result.
If not, this returns null.
Definition at line 4534 of file InstructionSimplify.cpp.
References C, foldConstant(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
Referenced by llvm::SimplifyFNegInst(), simplifyFPUnOp(), and simplifyUnOp().
simplifyFPOp()
static Constant* simplifyFPOp (ArrayRef< Value *> Ops) static
Perform folds that are common to any floating-point operation.
This implies transforms based on undef/NaN because the operation itself makes no difference to the result.
Definition at line 4565 of file InstructionSimplify.cpp.
References llvm::any_of(), llvm::ConstantFP::getNaN(), getType(), llvm::PatternMatch::m_NaN(), llvm::PatternMatch::match(), and propagateNaN().
Referenced by SimplifyFAddInst(), SimplifyFDivInst(), SimplifyFMAFMul(), SimplifyFRemInst(), SimplifyFSubInst(), and simplifyIntrinsic().
simplifyFPUnOp()
static Value * simplifyFPUnOp (unsigned Opcode, Value * Op, const FastMathFlags & FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given the operand for a UnaryOperator, see if we can fold the result.
If not, this returns null. Try to use FastMathFlags when folding the result.
Definition at line 4824 of file InstructionSimplify.cpp.
References simplifyFNegInst(), and simplifyUnOp().
Referenced by llvm::SimplifyUnOp().
SimplifyFreezeInst()
static Value* SimplifyFreezeInst (Value * Op0) static
Given operands for a Freeze, see if we can fold the result.
Definition at line 5323 of file InstructionSimplify.cpp.
References llvm::isGuaranteedNotToBeUndefOrPoison().
Referenced by llvm::SimplifyFreezeInst().
SimplifyFRemInst()
static Value* SimplifyFRemInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned) static
Definition at line 4779 of file InstructionSimplify.cpp.
References C, foldOrCommuteConstant(), llvm::ConstantFP::getNegativeZero(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_NegZeroFP(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), and simplifyFPOp().
Referenced by llvm::SimplifyFRemInst().
SimplifyFSubInst()
static Value* SimplifyFSubInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an FSub, see if we can fold the result.
If not, this returns null.
Definition at line 4625 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), C, llvm::CannotBeNegativeZero(), foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_c_FAdd(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_NegZeroFP(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), simplifyFPOp(), llvm::SimplifyQuery::TLI, and X.
Referenced by llvm::SimplifyFSubInst().
SimplifyGEPInst()
static Value * SimplifyGEPInst (Type * SrcTy, ArrayRef< Value * > Ops, const SimplifyQuery & Q, unsigned) static
Given operands for an GetElementPtrInst, see if we can fold the result.
If not, this returns null.
Definition at line 4041 of file InstructionSimplify.cpp.
References llvm::all_of(), llvm::ArrayRef< T >::back(), C, llvm::ConstantFoldConstant(), llvm::SimplifyQuery::DL, llvm::ConstantInt::get(), llvm::VectorType::get(), llvm::PointerType::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getGetElementPtr(), llvm::GetElementPtrInst::getIndexedType(), llvm::DataLayout::getIndexSizeInBits(), llvm::ConstantExpr::getIntToPtr(), llvm::Constant::getNullValue(), llvm::DataLayout::getPointerSizeInBits(), getScalarSizeInBits(), getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeSizeInBits(), llvm::Type::isSized(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), P, llvm::RISCVFenceField::R, llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::SimplifyGEPInst().
SimplifyICmpInst()
static Value * SimplifyICmpInst (unsigned Predicate, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an ICmpInst, see if we can fold the result.
If not, this returns null.
Definition at line 3223 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, assert(), C, computePointerICmp(), llvm::ConstantFoldCompareInstOperands(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getCast(), GetCompareTy(), llvm::getConstantRangeFromMetadata(), llvm::Value::getContext(), llvm::ConstantInt::getFalse(), getFalse(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::ConstantExpr::getIntToPtr(), llvm::CmpInst::getInversePredicate(), llvm::InstrInfoQuery::getMetadata(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::ICmpInst::getSignedPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), getTrue(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::ICmpInst::getUnsignedPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::SimplifyQuery::IIQ, llvm::ICmpInst::isEquality(), llvm::CmpInst::isIntPredicate(), llvm::isKnownNonEqual(), llvm::Type::isPointerTy(), llvm::CmpInst::isTrueWhenEqual(), llvm_unreachable, llvm::ConstantRange::makeSatisfyingICmpRegion(), llvm::SimplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), std::swap(), ThreadCmpOverPHI(), ThreadCmpOverSelect(), llvm::SimplifyQuery::TLI, and llvm::InstrInfoQuery::UseInstrInfo.
Referenced by llvm::SimplifyICmpInst().
simplifyICmpOfBools()
static Value* simplifyICmpOfBools (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Fold an icmp when its operands have i1 scalar type.
For signed comparison, the values for an i1 are 0 and -1 respectively. This maps into a truth table of: LHS | RHS | LHS >=s RHS | LHS implies RHS 0 | 0 | 1 (0 >= 0) | 1 0 | 1 | 1 (0 >= -1) | 1 1 | 0 | 0 (-1 >= 0) | 0 1 | 1 | 1 (-1 >= -1) | 1
Definition at line 2528 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::DL, GetCompareTy(), getFalse(), getTrue(), llvm::Value::getType(), llvm::Optional< T >::getValueOr(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isImpliedCondition(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), and llvm::PatternMatch::match().
Referenced by SimplifyICmpInst().
simplifyICmpWithBinOp()
static Value* simplifyICmpWithBinOp (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
TODO: A large part of this logic is duplicated in InstCombine's foldICmpBinOp().
We should be able to share that and avoid the code duplication.
Definition at line 2705 of file InstructionSimplify.cpp.
References A, llvm::SimplifyQuery::AC, llvm::MCID::Add, assert(), B, C, llvm::computeKnownBits(), llvm::SimplifyQuery::CxtI, D, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::dyn_cast(), GetCompareTy(), llvm::Value::getContext(), llvm::ConstantInt::getFalse(), getFalse(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantInt::getTrue(), getTrue(), llvm::Value::getType(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::SimplifyQuery::IIQ, llvm::ICmpInst::isEquality(), llvm::InstrInfoQuery::isExact(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm::APInt::isOneValue(), llvm::APInt::isPowerOf2(), llvm::CmpInst::isSigned(), llvm::APInt::isSignMask(), llvm::CmpInst::isUnsigned(), LLVM_FALLTHROUGH, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::SimplifyICmpInst(), Y, and llvm::ARCCC::Z.
Referenced by SimplifyICmpInst().
simplifyICmpWithConstant()
static Value* simplifyICmpWithConstant (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const InstrInfoQuery & IIQ) static
Definition at line 2664 of file InstructionSimplify.cpp.
References C, llvm::computeConstantRange(), llvm::ConstantRange::contains(), GetCompareTy(), llvm::ConstantInt::getFalse(), llvm::ConstantInt::getTrue(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::ConstantRange::inverse(), llvm::ConstantRange::isEmptySet(), llvm::ConstantRange::isFullSet(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::ConstantRange::makeExactICmpRegion(), llvm::PatternMatch::match(), llvm::InstrInfoQuery::UseInstrInfo, and X.
Referenced by SimplifyICmpInst().
simplifyICmpWithMinMax()
static Value* simplifyICmpWithMinMax (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Simplify integer comparisons where at least one operand of the compare matches an integer min/max idiom.
Definition at line 3019 of file InstructionSimplify.cpp.
References A, B, llvm::CmpInst::BAD_ICMP_PREDICATE, C, D, ExtractEquivalentCondition(), GetCompareTy(), getFalse(), llvm::CmpInst::getInversePredicate(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, llvm::SimplifyICmpInst(), and std::swap().
Referenced by SimplifyICmpInst().
simplifyICmpWithZero()
static Value* simplifyICmpWithZero (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Try hard to fold icmp with zero RHS because this is a common case.
Definition at line 2602 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::computeKnownBits(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, GetCompareTy(), getFalse(), getTrue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::SimplifyQuery::IIQ, llvm::isKnownNonZero(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm_unreachable, llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), and llvm::InstrInfoQuery::UseInstrInfo.
Referenced by SimplifyICmpInst().
SimplifyInsertValueInst()
static Value* SimplifyInsertValueInst (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const SimplifyQuery & Q, unsigned) static
Given operands for an InsertValueInst, see if we can fold the result.
If not, this returns null.
Definition at line 4160 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInsertValueInstruction(), llvm::Value::getType(), llvm::PatternMatch::m_Undef(), and llvm::PatternMatch::match().
Referenced by llvm::SimplifyInsertValueInst().
simplifyIntrinsic()
static Value* simplifyIntrinsic (CallBase * Call, const SimplifyQuery & Q) static
Definition at line 5227 of file InstructionSimplify.cpp.
References F(), llvm::UndefValue::get(), llvm::CallBase::getArgOperand(), llvm::APInt::getBitWidth(), llvm::CallBase::getCalledFunction(), llvm::Function::getIntrinsicID(), llvm::CallBase::getNumArgOperands(), llvm::Function::getReturnType(), llvm::APInt::isNullValue(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Undef(), llvm::maskIsAllZeroOrUndef(), llvm::PatternMatch::match(), simplifyBinaryIntrinsic(), simplifyFPOp(), simplifyUnaryIntrinsic(), and llvm::APInt::urem().
Referenced by llvm::SimplifyCall().
SimplifyLShrInst()
static Value* SimplifyLShrInst (Value * Op0, Value * Op1, bool isExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an LShr, see if we can fold the result.
If not, this returns null.
Definition at line 1345 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), SimplifyRightShift(), llvm::APInt::uge(), X, and Y.
Referenced by llvm::SimplifyLShrInst().
SimplifyMulInst()
static Value* SimplifyMulInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a Mul, see if we can fold the result.
If not, this returns null.
Definition at line 872 of file InstructionSimplify.cpp.
References llvm::MCID::Add, C, ExpandBinOp(), foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::SimplifyQuery::IIQ, llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_IDiv(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SimplifyAndInst(), SimplifyAssociativeBinOp(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), llvm::InstrInfoQuery::UseInstrInfo, and X.
Referenced by llvm::SimplifyMulInst().
SimplifyOrInst()
static Value * SimplifyOrInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Or, see if we can fold the result.
If not, this returns null.
Definition at line 2100 of file InstructionSimplify.cpp.
References A, llvm::SimplifyQuery::AC, B, C, llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, ExpandBinOp(), foldOrCommuteConstant(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), llvm::APInt::isMask(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::MaskedValueIsZero(), llvm::PatternMatch::match(), N, omitCheckForZeroBeforeInvertedMulWithOverflow(), simplifyAndOrOfCmps(), SimplifyAssociativeBinOp(), ThreadBinOpOverPHI(), and ThreadBinOpOverSelect().
Referenced by llvm::SimplifyOrInst().
simplifyOrOfICmps()
static Value* simplifyOrOfICmps (ICmpInst * Op0, ICmpInst * Op1, const SimplifyQuery & Q) static
Definition at line 1771 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::IIQ, simplifyAndOrOfICmpsWithConstants(), simplifyAndOrOfICmpsWithZero(), simplifyOrOfICmpsWithAdd(), simplifyOrOfICmpsWithSameOperands(), simplifyUnsignedRangeCheck(), and X.
Referenced by simplifyAndOrOfCmps().
simplifyOrOfICmpsWithAdd()
static Value* simplifyOrOfICmpsWithAdd (ICmpInst * Op0, ICmpInst * Op1, const InstrInfoQuery & IIQ) static
Definition at line 1724 of file InstructionSimplify.cpp.
References llvm::User::getOperand(), getTrue(), llvm::Value::getType(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by simplifyOrOfICmps().
simplifyOrOfICmpsWithSameOperands()
static Value* simplifyOrOfICmpsWithSameOperands (ICmpInst * Op0, ICmpInst * Op1) static
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
Definition at line 1550 of file InstructionSimplify.cpp.
References A, B, llvm::CmpInst::getInversePredicate(), getTrue(), llvm::Value::getType(), llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::isImpliedTrueByMatchingCmp(), llvm::CmpInst::isTrueWhenEqual(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by simplifyOrOfICmps().
SimplifyPHINode()
static Value* SimplifyPHINode (PHINode * PN, const SimplifyQuery & Q) static
See if we can fold the given phi. If not, returns null.
Definition at line 4297 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::DT, llvm::UndefValue::get(), llvm::Value::getType(), llvm::PHINode::incoming_values(), and valueDominatesPHI().
Referenced by llvm::SCEVExpander::replaceCongruentIVs(), and llvm::SimplifyInstruction().
SimplifyRelativeLoad()
static Value* SimplifyRelativeLoad (Constant * Ptr, Constant * Offset, const DataLayout & DL) static
Definition at line 4950 of file InstructionSimplify.cpp.
References C, llvm::ConstantFoldLoadFromConstPtr(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::ConstantExpr::getGetElementPtr(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::User::getOperand(), llvm::Type::getPointerTo(), llvm::ConstantInt::getSExtValue(), Int32Ty, and llvm::IsConstantOffsetFromGlobal().
Referenced by simplifyBinaryIntrinsic().
simplifyRem()
static Value* simplifyRem (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
These are simplifications common to SRem and URem.
Definition at line 1107 of file InstructionSimplify.cpp.
References C, foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::SimplifyQuery::IIQ, isDivZero(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), simplifyDivRem(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), and llvm::InstrInfoQuery::UseInstrInfo.
Referenced by SimplifySRemInst(), and SimplifyURemInst().
SimplifyRightShift()
static Value* SimplifyRightShift (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, bool isExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Shl, LShr or AShr, see if we can fold the result.
If not, this returns null.
Definition at line 1286 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::computeKnownBits(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::match(), llvm::KnownBits::One, and SimplifyShift().
Referenced by SimplifyAShrInst(), and SimplifyLShrInst().
SimplifySDivInst()
static Value* SimplifySDivInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an SDiv, see if we can fold the result.
If not, this returns null.
Definition at line 1151 of file InstructionSimplify.cpp.
References llvm::Constant::getAllOnesValue(), llvm::Value::getType(), llvm::isKnownNegation(), and simplifyDiv().
Referenced by llvm::SimplifySDivInst().
simplifySelectBitTest()
static Value* simplifySelectBitTest (Value * TrueVal, Value * FalseVal, Value * X, const APInt * Y, bool TrueWhenUnset) static
Try to simplify a select instruction when its condition operand is an integer comparison where one operand of the compare is a constant.
Definition at line 3805 of file InstructionSimplify.cpp.
References C, llvm::APInt::isPowerOf2(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), and llvm::PatternMatch::match().
Referenced by simplifySelectWithFakeICmpEq(), and simplifySelectWithICmpCond().
SimplifySelectInst()
static Value* SimplifySelectInst (Value * Cond, Value * TrueVal, Value * FalseVal, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a SelectInst, see if we can fold the result.
If not, this returns null.
Definition at line 3978 of file InstructionSimplify.cpp.
simplifySelectWithFakeICmpEq()
static Value* simplifySelectWithFakeICmpEq (Value * CmpLHS, Value * CmpRHS, ICmpInst::Predicate Pred, Value * TrueVal, Value * FalseVal) static
An alternative way to test if a bit is set or not uses sgt/slt instead of eq/ne.
Definition at line 3840 of file InstructionSimplify.cpp.
References llvm::decomposeBitTestICmp(), llvm::CmpInst::ICMP_EQ, llvm::BitmaskEnumDetail::Mask(), simplifySelectBitTest(), and X.
Referenced by simplifySelectWithICmpCond().
simplifySelectWithFCmp()
static Value* simplifySelectWithFCmp (Value * Cond, Value * T, Value * F, const SimplifyQuery & Q) static
Try to simplify a select instruction when its condition operand is a floating-point comparison.
Definition at line 3947 of file InstructionSimplify.cpp.
simplifySelectWithICmpCond()
static Value* simplifySelectWithICmpCond (Value * CondVal, Value * TrueVal, Value * FalseVal, const SimplifyQuery & Q, unsigned MaxRecurse) static
Try to simplify a select instruction when its condition operand is an integer comparison.
Definition at line 3854 of file InstructionSimplify.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), simplifySelectBitTest(), simplifySelectWithFakeICmpEq(), SimplifyWithOpReplaced(), X, and Y.
SimplifyShift()
static Value* SimplifyShift (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Shl, LShr or AShr, see if we can fold the result.
If not, this returns null.
Definition at line 1236 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, C, llvm::computeKnownBits(), llvm::KnownBits::countMinTrailingZeros(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, foldOrCommuteConstant(), llvm::UndefValue::get(), llvm::KnownBits::getBitWidth(), llvm::APInt::getLimitedValue(), llvm::Constant::getNullValue(), llvm::Value::getType(), isUndefShift(), llvm::Log2_32_Ceil(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::KnownBits::One, ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), and X.
Referenced by SimplifyRightShift(), and SimplifyShlInst().
SimplifyShlInst()
static Value* SimplifyShlInst (Value * Op0, Value * Op1, bool isNSW, bool isNUW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Shl, see if we can fold the result.
If not, this returns null.
Definition at line 1313 of file InstructionSimplify.cpp.
References llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::SimplifyQuery::IIQ, llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), SimplifyShift(), llvm::InstrInfoQuery::UseInstrInfo, and X.
Referenced by llvm::SimplifyShlInst().
SimplifyShuffleVectorInst()
static Value* SimplifyShuffleVectorInst (Value * Op0, Value * Op1, Constant * Mask, Type * RetTy, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 4419 of file InstructionSimplify.cpp.
References llvm::all_of(), assert(), C, llvm::ShuffleVectorInst::commuteShuffleMask(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::find(), foldIdentityShuffles(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_InsertElement(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::SmallVectorBase::size(), and std::swap().
Referenced by llvm::SimplifyShuffleVectorInst().
SimplifySRemInst()
static Value* SimplifySRemInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an SRem, see if we can fold the result.
If not, this returns null.
Definition at line 1177 of file InstructionSimplify.cpp.
References llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), llvm::isKnownNegation(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), simplifyRem(), and X.
Referenced by llvm::SimplifySRemInst().
SimplifySubInst()
static Value* SimplifySubInst (Value * Op0, Value * Op1, bool isNSW, bool isNUW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a Sub, see if we can fold the result.
If not, this returns null.
Definition at line 737 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::MCID::Add, C, llvm::computeKnownBits(), computePointerDifference(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, foldOrCommuteConstant(), llvm::UndefValue::get(), llvm::ConstantExpr::getIntegerCast(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SimplifyBinOp(), llvm::SimplifyCastInst(), llvm::SimplifyXorInst(), llvm::RISCVFenceField::W, X, Y, and llvm::ARCCC::Z.
Referenced by llvm::SimplifySubInst().
SimplifyUDivInst()
static Value* SimplifyUDivInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a UDiv, see if we can fold the result.
If not, this returns null.
Definition at line 1166 of file InstructionSimplify.cpp.
References simplifyDiv().
Referenced by llvm::SimplifyUDivInst().
simplifyUnaryIntrinsic()
static Value* simplifyUnaryIntrinsic (Function * F, Value * Op0, const SimplifyQuery & Q) static
Definition at line 5006 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::CxtI, llvm::Function::getIntrinsicID(), llvm::Instruction::hasAllowReassoc(), IsIdempotent(), llvm::log2(), llvm::PatternMatch::m_BitReverse(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_SIToFP(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), round(), llvm::SignBitMustBeZero(), llvm::SimplifyQuery::TLI, and X.
Referenced by simplifyIntrinsic().
simplifyUnOp()
static Value * simplifyUnOp (unsigned Opcode, Value * Op, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given the operand for a UnaryOperator, see if we can fold the result.
If not, this returns null.
Definition at line 4811 of file InstructionSimplify.cpp.
References llvm_unreachable, and simplifyFNegInst().
Referenced by simplifyFPUnOp(), and llvm::SimplifyUnOp().
simplifyUnsignedRangeCheck()
static Value* simplifyUnsignedRangeCheck (ICmpInst * ZeroICmp, ICmpInst * UnsignedICmp, bool IsAnd, const SimplifyQuery & Q) static
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
Definition at line 1414 of file InstructionSimplify.cpp.
References A, llvm::SimplifyQuery::AC, B, llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::ConstantInt::getFalse(), getFalse(), llvm::User::getOperand(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), getTrue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::isKnownNonZero(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), X, and Y.
Referenced by simplifyAndOfICmps(), and simplifyOrOfICmps().
SimplifyURemInst()
static Value* SimplifyURemInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a URem, see if we can fold the result.
If not, this returns null.
Definition at line 1198 of file InstructionSimplify.cpp.
References simplifyRem().
Referenced by llvm::SimplifyURemInst().
SimplifyWithOpReplaced()
static const Value* SimplifyWithOpReplaced (Value * V, Value * Op, Value * RepOp, const SimplifyQuery & Q, unsigned MaxRecurse) static
See if V simplifies when its operand Op is replaced with RepOp.
Definition at line 3705 of file InstructionSimplify.cpp.
References B, C, llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldInstOperands(), llvm::ConstantFoldLoadFromConstPtr(), llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::numbers::e, GEP, llvm::User::getOperand(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), I, llvm::SimplifyQuery::IIQ, llvm::InstrInfoQuery::isExact(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SimplifyBinOp(), llvm::SimplifyCmpInst(), llvm::SimplifyGEPInst(), llvm::SmallVectorBase::size(), llvm::SimplifyQuery::TLI, and llvm::transform().
Referenced by simplifySelectWithICmpCond().
SimplifyXorInst()
static Value * SimplifyXorInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a Xor, see if we can fold the result.
If not, this returns null.
Definition at line 2244 of file InstructionSimplify.cpp.
References C, foldOrCommuteConstant(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), and SimplifyAssociativeBinOp().
Referenced by llvm::SimplifyXorInst().
STATISTIC() [1/2]
STATISTIC (NumExpand , "Number of expansions")
STATISTIC() [2/2]
STATISTIC (NumReassoc , "Number of reassociations")
stripAndComputeConstantOffsets()
static Constant* stripAndComputeConstantOffsets (const DataLayout & DL, Value *& V, bool AllowNonInbounds = false) static
Compute the base pointer and cumulative constant offsets for V.
This strips all constant offsets off of V, leaving it the base pointer, and accumulates the total constant offset applied in the returned constant. It returns 0 if V is not a pointer, and returns the constant '0' if there are no constant offsets applied.
This is very similar to GetPointerBaseWithConstantOffset except it doesn't follow non-inbounds geps. This allows it to remain usable for icmp ult/etc. folding.
Definition at line 696 of file InstructionSimplify.cpp.
References assert(), llvm::ConstantInt::get(), llvm::DataLayout::getIndexType(), llvm::APInt::getNullValue(), llvm::ConstantVector::getSplat(), llvm::Value::getType(), llvm::Type::isPtrOrPtrVectorTy(), llvm::APInt::sextOrTrunc(), and llvm::Value::stripAndAccumulateConstantOffsets().
Referenced by computePointerDifference(), and computePointerICmp().
ThreadBinOpOverPHI()
static Value* ThreadBinOpOverPHI (Instruction::BinaryOps Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a binary operation with an operand that is a PHI instruction, try to simplify the binop by seeing whether evaluating it on the incoming phi values yields the same result for every value.
If so returns the common value, otherwise returns null.
Definition at line 518 of file InstructionSimplify.cpp.
References assert(), llvm::SimplifyQuery::DT, llvm::PHINode::incoming_values(), llvm::SimplifyBinOp(), and valueDominatesPHI().
Referenced by SimplifyAndInst(), simplifyDiv(), SimplifyMulInst(), SimplifyOrInst(), simplifyRem(), and SimplifyShift().
ThreadBinOpOverSelect()
static Value* ThreadBinOpOverSelect (Instruction::BinaryOps Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a binary operation with a select instruction as an operand, try to simplify the binop by seeing whether evaluating it on both branches of the select results in the same value.
Returns the common value if so, otherwise returns null.
Definition at line 394 of file InstructionSimplify.cpp.
References assert(), llvm::dyn_cast(), llvm::SelectInst::getFalseValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::SelectInst::getTrueValue(), llvm::Instruction::isCommutative(), SI, llvm::JumpTable::Simplified, and llvm::SimplifyBinOp().
Referenced by SimplifyAndInst(), simplifyDiv(), SimplifyMulInst(), SimplifyOrInst(), simplifyRem(), and SimplifyShift().
ThreadCmpOverPHI()
static Value* ThreadCmpOverPHI (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a comparison with a PHI instruction, try to simplify the comparison by seeing whether comparing with all of the incoming phi values yields the same result every time.
If so returns the common result, otherwise returns null.
Definition at line 561 of file InstructionSimplify.cpp.
References assert(), llvm::SimplifyQuery::DT, llvm::numbers::e, llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::CmpInst::getSwappedPredicate(), llvm::BasicBlock::getTerminator(), llvm::SimplifyQuery::getWithInstruction(), llvm::SimplifyCmpInst(), std::swap(), and valueDominatesPHI().
Referenced by SimplifyFCmpInst(), and SimplifyICmpInst().
ThreadCmpOverSelect()
static Value* ThreadCmpOverSelect (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a comparison with a select instruction, try to simplify the comparison by seeing whether both branches of the select result in the same value.
Returns the common value if so, otherwise returns null. For example, if we have: tmp = select i1 cmp, i32 1, i32 2 cmp1 = icmp sle i32 tmp, 3 We can simplify cmp1 to true, because both branches of select are less than 3. We compose new comparison by substituting tmp with both branches of select and see if it can be simplified.
Definition at line 472 of file InstructionSimplify.cpp.
References assert(), llvm::CmpInst::getSwappedPredicate(), SI, and std::swap().
Referenced by SimplifyFCmpInst(), and SimplifyICmpInst().
valueDominatesPHI()
static bool valueDominatesPHI (Value * V, PHINode * P, const DominatorTree * DT) static
Does the given value dominate the specified phi node?
Definition at line 206 of file InstructionSimplify.cpp.
References llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::Function::getEntryBlock(), llvm::Instruction::getFunction(), llvm::Instruction::getParent(), and I.
Referenced by SimplifyPHINode(), ThreadBinOpOverPHI(), and ThreadCmpOverPHI().