LLVM: lib/Transforms/Scalar/InstSimplifyPass.cpp File Reference
InstSimplifyPass.cpp File Reference
#include "llvm/Transforms/Scalar/InstSimplifyPass.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "instsimplify"
Functions
STATISTIC (NumSimplified, "Number of redundant instructions removed")
static bool runImpl (Function &F, const SimplifyQuery &SQ, OptimizationRemarkEmitter *ORE)
INITIALIZE_PASS_BEGIN (InstSimplifyLegacyPass, "instsimplify", "Remove redundant instructions", false, false) INITIALIZE_PASS_END(InstSimplifyLegacyPass
Variables
instsimplify
Remove redundant instructions
Remove redundant false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instsimplify"
Definition at line 27 of file InstSimplifyPass.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (InstSimplifyLegacyPass , "instsimplify" , "Remove redundant instructions" , false , false)
Referenced by runImpl().
runImpl()
static bool runImpl (Function & F, const SimplifyQuery & SQ, OptimizationRemarkEmitter * ORE) static
Definition at line 31 of file InstSimplifyPass.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SimplifyQuery::DT, llvm::SmallPtrSetImplBase::empty(), F(), llvm::Module::getDataLayout(), llvm::GlobalValue::getParent(), llvm::PassRegistry::getPassRegistry(), I, INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeInstSimplifyLegacyPassPass(), llvm::isInstructionTriviallyDead(), llvm::DominatorTree::isReachableFromEntry(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), runOnFunction(), llvm::AnalysisUsage::setPreservesCFG(), llvm::SimplifyInstruction(), std::swap(), and llvm::SimplifyQuery::TLI.
Referenced by llvm::InstSimplifyPass::run().
STATISTIC()
STATISTIC (NumSimplified , "Number of redundant instructions removed")
Variable Documentation
false
Remove redundant false
Definition at line 123 of file InstSimplifyPass.cpp.
instructions
Remove redundant instructions
Definition at line 123 of file InstSimplifyPass.cpp.
instsimplify
instsimplify
Definition at line 123 of file InstSimplifyPass.cpp.