LLVM: lib/Transforms/InstCombine/InstCombinePHI.cpp File Reference
InstCombinePHI.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Utils/Local.h"
Classes
struct llvm::DenseMapInfo< LoweredPHIRecord >
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "instcombine"
Functions
static bool isSafeAndProfitableToSinkLoad (LoadInst *L)
Return true if we know that it is safe to sink the load out of the block that defines it.
static bool DeadPHICycle (PHINode *PN, SmallPtrSetImpl< PHINode *> &PotentiallyDeadPHIs)
Return true if this PHI node is only used by a PHI node cycle that is dead.
static bool PHIsEqualValue (PHINode *PN, Value *NonPhiInVal, SmallPtrSetImpl< PHINode *> &ValueEqualPHIs)
Return true if this phi node is always equal to NonPhiInVal.
static ConstantInt * GetAnyNonZeroConstInt (PHINode &PN)
Return an existing non-zero constant if this phi node has one, otherwise return constant 1.
Variables
static cl::opt< unsigned > MaxNumPhis ("instcombine-max-num-phis", cl::init(512), cl::desc("Maximum number phis to handle in intptr/ptrint folding"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 24 of file InstCombinePHI.cpp.
Function Documentation
DeadPHICycle()
static bool DeadPHICycle (PHINode * PN, SmallPtrSetImpl< PHINode *> & PotentiallyDeadPHIs) static
Return true if this PHI node is only used by a PHI node cycle that is dead.
Definition at line 844 of file InstCombinePHI.cpp.
References llvm::Value::hasOneUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallPtrSetImplBase::size(), llvm::Value::use_empty(), and llvm::Instruction::user_back().
Referenced by llvm::InstCombiner::visitPHINode().
GetAnyNonZeroConstInt()
static ConstantInt* GetAnyNonZeroConstInt (PHINode & PN) static
Return an existing non-zero constant if this phi node has one, otherwise return constant 1.
Definition at line 891 of file InstCombinePHI.cpp.
References assert(), llvm::ConstantInt::get(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::User::operands(), and llvm::operator<().
Referenced by llvm::InstCombiner::visitPHINode().
isSafeAndProfitableToSinkLoad()
static bool isSafeAndProfitableToSinkLoad (LoadInst * L) static
Return true if we know that it is safe to sink the load out of the block that defines it.
This means that it must be obvious the value of the load is not changed from the point of the load to the end of the block it is in.
Finally, it is safe, but not profitable, to sink a load targeting a non-address-taken alloca. Doing so will cause us to not promote the alloca to a register.
Definition at line 505 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::Instruction::andIRFlags(), C, llvm::combineMetadata(), llvm::Instruction::copyIRFlags(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::CmpInst::Create(), llvm::PHINode::Create(), llvm::CastInst::CreateZExtOrBitCast(), llvm::dyn_cast(), llvm::numbers::e, E, llvm::BasicBlock::end(), llvm::LoadInst::getAlignment(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getMetadata(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getNumSuccessors(), llvm::BinaryOperator::getOpcode(), llvm::CmpInst::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::LoadInst::getPointerAddressSpace(), llvm::CmpInst::getPredicate(), llvm::BasicBlock::getTerminator(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::ConstantExpr::getZExt(), llvm::GetElementPtrInst::hasAllConstantIndices(), llvm::Value::hasOneUse(), llvm::PHINode::incoming_values(), llvm::Instruction::isAtomic(), llvm::Type::isIntegerTy(), llvm::Instruction::isSameOperationAs(), llvm::LoadInst::isVolatile(), isVolatile(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Instruction::setMetadata(), llvm::User::setOperand(), SI, and llvm::Value::users().
PHIsEqualValue()
static bool PHIsEqualValue (PHINode * PN, Value * NonPhiInVal, SmallPtrSetImpl< PHINode *> & ValueEqualPHIs) static
Return true if this phi node is always equal to NonPhiInVal.
This happens with mutually cyclic phi nodes like: z = some value; x = phi (y, z); y = phi (x, z)
Definition at line 866 of file InstCombinePHI.cpp.
References llvm::PHINode::incoming_values(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::SmallPtrSetImplBase::size().
Referenced by llvm::InstCombiner::visitPHINode().
Variable Documentation
MaxNumPhis
cl::opt<unsigned> MaxNumPhis("instcombine-max-num-phis", cl::init(512), cl::desc("Maximum number phis to handle in intptr/ptrint folding")) static