LLVM: lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp File Reference
InstCombineSimplifyDemanded.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/KnownBits.h"
#include "InstCombineTables.inc"
Macros
#define DEBUG_TYPE "instcombine"
#define GET_AMDGPUImageDMaskIntrinsicTable_IMPL
Functions
static bool ShrinkDemandedConstant (Instruction *I, unsigned OpNo, const APInt &Demanded)
Check to see if the specified operand of the specified instruction is a constant integer.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 25 of file InstCombineSimplifyDemanded.cpp.
GET_AMDGPUImageDMaskIntrinsicTable_IMPL
#define GET_AMDGPUImageDMaskIntrinsicTable_IMPL
Definition at line 33 of file InstCombineSimplifyDemanded.cpp.
Function Documentation
ShrinkDemandedConstant()
static bool ShrinkDemandedConstant (Instruction * I, unsigned OpNo, const APInt & Demanded) static
Check to see if the specified operand of the specified instruction is a constant integer.
If so, check to see if there are any bits set in the constant that are not demanded. If so, shrink the constant and return true.
Definition at line 41 of file InstCombineSimplifyDemanded.cpp.
References llvm::MCID::Add, Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::APInt::ashr(), assert(), llvm::tgtok::Bit, C, llvm::MCID::Call, llvm::APInt::clearAllBits(), llvm::APInt::clearBit(), llvm::KnownBits::computeForAddSub(), llvm::computeKnownBits(), llvm::ComputeNumSignBits(), llvm::Instruction::copyMetadata(), llvm::APInt::countLeadingOnes(), llvm::APInt::countLeadingZeros(), llvm::KnownBits::countMinLeadingZeros(), llvm::countPopulation(), llvm::APInt::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::InsertElementInst::Create(), llvm::Depth, llvm::Instruction::dropPoisonGeneratingFlags(), llvm::dyn_cast(), E, llvm::SelectPatternResult::Flavor, GEP, llvm::gep_type_begin(), llvm::gep_type_end(), llvm::ConstantInt::get(), llvm::Use::get(), llvm::ConstantAggregateZero::get(), llvm::VectorType::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::APInt::getActiveBits(), llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::KnownBits::getBitWidth(), llvm::APInt::getBitWidth(), llvm::CallBase::getCalledFunction(), llvm::SelectInst::getCondition(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Function::getFunctionType(), llvm::APInt::getHighBitsSet(), llvm::Type::getInt32Ty(), llvm::Constant::getIntegerValue(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::APInt::getLimitedValue(), llvm::APInt::getLoBits(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::CallBase::getNumArgOperands(), llvm::SequentialType::getNumElements(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::User::getOperandUse(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignMask(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), llvm::KnownBits::hasConflict(), hasNoSignedWrap(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, if(), llvm::APInt::intersects(), llvm::Constant::isAllOnesValue(), llvm::APInt::isAllOnesValue(), llvm::Instruction::isIntDivRem(), llvm::Type::isIntOrIntVectorTy(), llvm::APInt::isMask(), llvm::KnownBits::isNonNegative(), llvm::Constant::isNullValue(), llvm::APInt::isNullValue(), llvm::APInt::isOneValue(), llvm::APInt::isPowerOf2(), llvm::Instruction::isShift(), llvm::APInt::isSignBitSet(), llvm::APInt::isSignMask(), llvm::APInt::isSubsetOf(), llvm::Type::isVectorTy(), llvm_unreachable, llvm::APInt::lshr(), llvm::APInt::lshrInPlace(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Value(), llvm::KnownBits::makeNonNegative(), llvm::PatternMatch::match(), llvm::Intrinsic::matchIntrinsicSignature(), llvm::matchSelectPattern(), llvm::KnownBits::One, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), RA, llvm::KnownBits::resetAll(), llvm::MCID::Select, llvm::APInt::setAllBits(), llvm::CallBase::setArgOperand(), llvm::APInt::setBit(), llvm::APInt::setBitsFrom(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::APInt::setHighBits(), llvm::Instruction::setIsExact(), llvm::APInt::setLowBits(), llvm::User::setOperand(), llvm::APInt::setSignBit(), llvm::KnownBits::sext(), llvm::APInt::shl(), llvm::SPF_UMAX, llvm::SPF_UMIN, llvm::SPF_UNKNOWN, llvm::Value::takeName(), llvm::APInt::trunc(), llvm::APInt::uge(), llvm::APInt::ult(), llvm::RegState::Undef, llvm::APInt::urem(), llvm::KnownBits::Zero, llvm::APInt::zext(), llvm::KnownBits::zextOrTrunc(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::TargetLowering::TargetLoweringOpt::CombineTo().