LLVM: lib/Object/IRObjectFile.cpp File Reference
IRObjectFile.cpp File Reference
#include "llvm/Object/IRObjectFile.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/IR/GVMaterializer.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
Functions
static ModuleSymbolTable::Symbol getSym (DataRefImpl &Symb)
Function Documentation
getSym()
static ModuleSymbolTable::Symbol getSym (DataRefImpl & Symb) static
Definition at line 37 of file IRObjectFile.cpp.
Referenced by checkScale(), llvm::object::IRObjectFile::getSymbolFlags(), and llvm::object::IRObjectFile::printSymbolName().