LLVM: lib/Demangle/ItaniumDemangle.cpp File Reference
ItaniumDemangle.cpp File Reference
#include "llvm/Demangle/Demangle.h"
#include "llvm/Demangle/ItaniumDemangle.h"
#include <cassert>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <numeric>
#include <utility>
#include <vector>
Typedefs
using Demangler = itanium_demangle::ManglingParser< DefaultAllocator >
Functions
static char * printNode (const Node *RootNode, char *Buf, size_t *N)
Typedef Documentation
Demangler
using Demangler = itanium_demangle::ManglingParser<DefaultAllocator>
Definition at line 326 of file ItaniumDemangle.cpp.
Function Documentation
printNode()
static char* printNode (const Node * RootNode, char * Buf, size_t * N) static
Definition at line 389 of file ItaniumDemangle.cpp.
References initializeOutputStream().
Referenced by llvm::ItaniumPartialDemangler::finishDemangle(), llvm::ItaniumPartialDemangler::getFunctionBaseName(), and llvm::ItaniumPartialDemangler::getFunctionName().