LLVM: lib/Target/Lanai/MCTargetDesc/LanaiInstPrinter.cpp File Reference
LanaiInstPrinter.cpp File Reference
#include "LanaiInstPrinter.h"
#include "LanaiMCExpr.h"
#include "LanaiAluCode.h"
#include "LanaiCondCode.h"
#include "MCTargetDesc/LanaiMCTargetDesc.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "LanaiGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
#define PRINT_ALIAS_INSTR
Functions
static bool usesGivenOffset (const MCInst *MI, int AddOffset)
static bool isPreIncrementForm (const MCInst *MI, int AddOffset)
static bool isPostIncrementForm (const MCInst *MI, int AddOffset)
static StringRef decIncOperator (const MCInst *MI)
static void printMemoryBaseRegister (raw_ostream &OS, const unsigned AluCode, const MCOperand &RegOp)
template<unsigned SizeInBits>
static void printMemoryImmediateOffset (const MCAsmInfo &MAI, const MCOperand &OffsetOp, raw_ostream &OS)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 28 of file LanaiInstPrinter.cpp.
PRINT_ALIAS_INSTR
#define PRINT_ALIAS_INSTR
Definition at line 31 of file LanaiInstPrinter.cpp.
Function Documentation
decIncOperator()
static StringRef decIncOperator (const MCInst * MI) static
Definition at line 65 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::LanaiInstPrinter::getRegisterName(), isPostIncrementForm(), and isPreIncrementForm().
isPostIncrementForm()
static bool isPostIncrementForm (const MCInst * MI, int AddOffset) static
Definition at line 60 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::LPAC::isPostOp(), and usesGivenOffset().
Referenced by decIncOperator().
isPreIncrementForm()
static bool isPreIncrementForm (const MCInst * MI, int AddOffset) static
Definition at line 55 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::LPAC::isPreOp(), and usesGivenOffset().
Referenced by decIncOperator().
printMemoryBaseRegister()
static void printMemoryBaseRegister (raw_ostream & OS, const unsigned AluCode, const MCOperand & RegOp) static
Definition at line 213 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCOperand::getReg(), llvm::LanaiInstPrinter::getRegisterName(), llvm::LPAC::isPostOp(), llvm::LPAC::isPreOp(), and llvm::MCOperand::isReg().
Referenced by llvm::LanaiInstPrinter::printMemRiOperand(), and llvm::LanaiInstPrinter::printMemSplsOperand().
printMemoryImmediateOffset()
template<unsigned SizeInBits> static void printMemoryImmediateOffset (const MCAsmInfo & MAI, const MCOperand & OffsetOp, raw_ostream & OS) static
Definition at line 226 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and llvm::MCExpr::print().
usesGivenOffset()
static bool usesGivenOffset (const MCInst * MI, int AddOffset) static
Definition at line 48 of file LanaiInstPrinter.cpp.
References llvm::LPAC::ADD, llvm::LPAC::encodeLanaiAluCode(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by isPostIncrementForm(), and isPreIncrementForm().