LLVM: lib/Target/Lanai/Disassembler/LanaiDisassembler.cpp File Reference
LanaiDisassembler.cpp File Reference
#include "LanaiDisassembler.h"
#include "LanaiAluCode.h"
#include "LanaiCondCode.h"
#include "LanaiInstrInfo.h"
#include "TargetInfo/LanaiTargetInfo.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "LanaiGenDisassemblerTables.inc"
Namespaces
llvm
This class represents lattice values for constants.
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
Target & llvm::getTheLanaiTarget ()
static MCDisassembler * createLanaiDisassembler (const Target &, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiDisassembler ()
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus decodeRiMemoryValue (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodeRrMemoryValue (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodeSplsValue (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodeBranch (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodePredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus decodeShiftImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t &Size, uint32_t &Insn)
static void PostOperandDecodeAdjust (MCInst &Instr, uint32_t Insn)
static bool tryAddingSymbolicOperand (int64_t Value, bool IsBranch, uint64_t Address, uint64_t Offset, uint64_t Width, MCInst &MI, const void *Decoder)
Variables
static const unsigned GPRDecoderTable []
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 27 of file LanaiDisassembler.cpp.
Function Documentation
createLanaiDisassembler()
static MCDisassembler* createLanaiDisassembler (const Target & , const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 33 of file LanaiDisassembler.cpp.
Referenced by LLVMInitializeLanaiDisassembler().
decodeBranch()
static DecodeStatus decodeBranch (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 219 of file LanaiDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
Referenced by llvm::LanaiDisassembler::LanaiDisassembler().
DecodeGPRRegisterClass()
DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 163 of file LanaiDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by llvm::LanaiDisassembler::LanaiDisassembler().
decodePredicateOperand()
static DecodeStatus decodePredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 235 of file LanaiDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::Success, and llvm::LPCC::UNKNOWN.
Referenced by llvm::LanaiDisassembler::LanaiDisassembler().
decodeRiMemoryValue()
static DecodeStatus decodeRiMemoryValue (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 174 of file LanaiDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
Referenced by llvm::LanaiDisassembler::LanaiDisassembler().
decodeRrMemoryValue()
static DecodeStatus decodeRrMemoryValue (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 186 of file LanaiDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
Referenced by llvm::LanaiDisassembler::LanaiDisassembler().
decodeShiftImm()
static DecodeStatus decodeShiftImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 227 of file LanaiDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by llvm::LanaiDisassembler::LanaiDisassembler().
decodeSplsValue()
static DecodeStatus decodeSplsValue (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 198 of file LanaiDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
Referenced by llvm::LanaiDisassembler::LanaiDisassembler().
LLVMInitializeLanaiDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiDisassembler ()
Definition at line 39 of file LanaiDisassembler.cpp.
References createLanaiDisassembler(), llvm::getTheLanaiTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
PostOperandDecodeAdjust()
static void PostOperandDecodeAdjust (MCInst & Instr, uint32_t Insn) static
Definition at line 90 of file LanaiDisassembler.cpp.
References llvm::LPAC::ADD, llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::isRMOpcode(), llvm::isRRMOpcode(), llvm::isSPLSOpcode(), llvm::LPAC::makePostOp(), llvm::LPAC::makePreOp(), llvm::MCOperand::setImm(), and llvm::MCOperand::setReg().
Referenced by llvm::LanaiDisassembler::getInstruction().
readInstruction32()
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t & Size, uint32_t & Insn) static
Definition at line 75 of file LanaiDisassembler.cpp.
References llvm::MCDisassembler::Fail, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.
Referenced by llvm::LanaiDisassembler::getInstruction().
tryAddingSymbolicOperand()
static bool tryAddingSymbolicOperand (int64_t Value, bool IsBranch, uint64_t Address, uint64_t Offset, uint64_t Width, MCInst & MI, const void * Decoder) static
Definition at line 210 of file LanaiDisassembler.cpp.
References llvm::MCDisassembler::tryAddingSymbolicOperand().
Variable Documentation
GPRDecoderTable
const unsigned GPRDecoderTable[] static
Initial value:
= {
    Lanai::R0,  Lanai::R1,  Lanai::PC,  Lanai::R3,  Lanai::SP,  Lanai::FP,
    Lanai::R6,  Lanai::R7,  Lanai::RV,  Lanai::R9,  Lanai::RR1, Lanai::RR2,
    Lanai::R12, Lanai::R13, Lanai::R14, Lanai::RCA, Lanai::R16, Lanai::R17,
    Lanai::R18, Lanai::R19, Lanai::R20, Lanai::R21, Lanai::R22, Lanai::R23,
    Lanai::R24, Lanai::R25, Lanai::R26, Lanai::R27, Lanai::R28, Lanai::R29,
    Lanai::R30, Lanai::R31}
Definition at line 155 of file LanaiDisassembler.cpp.