LLVM: lib/Target/Lanai/AsmParser/LanaiAsmParser.cpp File Reference
LanaiAsmParser.cpp File Reference
#include "LanaiAluCode.h"
#include "LanaiCondCode.h"
#include "LanaiInstrInfo.h"
#include "MCTargetDesc/LanaiMCExpr.h"
#include "TargetInfo/LanaiTargetInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <memory>
#include "LanaiGenAsmMatcher.inc"
Macros
#define GET_ASSEMBLER_HEADER
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
Functions
static unsigned MatchRegisterName (StringRef Name)
static unsigned AluWithPrePost (unsigned AluCode, bool PreOp, bool PostOp)
static int SizeForSuffix (StringRef T)
bool shouldBeSls (const LanaiOperand &Op)
static bool IsMemoryAssignmentError (const OperandVector &Operands)
static bool IsRegister (const MCParsedAsmOperand &op)
static bool MaybePredicatedInst (const OperandVector &Operands)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiAsmParser ()
Macro Definition Documentation
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 77 of file LanaiAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 1224 of file LanaiAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 1223 of file LanaiAsmParser.cpp.
Function Documentation
AluWithPrePost()
static unsigned AluWithPrePost (unsigned AluCode, bool PreOp, bool PostOp) static
Definition at line 797 of file LanaiAsmParser.cpp.
References llvm::Error, llvm::LPAC::makePostOp(), llvm::LPAC::makePreOp(), llvm::LPAC::stringToLanaiAluCode(), and llvm::LPAC::UNKNOWN.
Referenced by shouldBeSls().
IsMemoryAssignmentError()
static bool IsMemoryAssignmentError (const OperandVector & Operands) static
Definition at line 1101 of file LanaiAsmParser.cpp.
References llvm::MCConstantExpr::getValue(), llvm::LPAC::modifiesOp(), and llvm::SmallVectorBase::size().
Referenced by MaybePredicatedInst().
IsRegister()
static bool IsRegister (const MCParsedAsmOperand & op) static
Definition at line 1138 of file LanaiAsmParser.cpp.
References isReg(), and op.
Referenced by llvm::yaml::SIArgument::createArgument(), and MaybePredicatedInst().
LLVMInitializeLanaiAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiAsmParser ()
Definition at line 1227 of file LanaiAsmParser.cpp.
References llvm::getTheLanaiTarget().
MatchRegisterName()
static unsigned MatchRegisterName (StringRef Name) static
MaybePredicatedInst()
static bool MaybePredicatedInst (const OperandVector & Operands) static
Definition at line 1142 of file LanaiAsmParser.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::AsmToken::Comma, llvm::MCConstantExpr::create(), llvm::StringSwitch< T, R >::Default(), llvm::AsmToken::EndOfStatement, llvm::SmallVectorImpl< T >::erase(), llvm::Error, llvm::getToken(), llvm::LPCC::ICC_T, llvm::SmallVectorImpl< T >::insert(), IsMemoryAssignmentError(), IsRegister(), llvm::MatchOperand_Success, llvm::SmallVectorBase::size(), llvm::StringSwitch< T, R >::StartsWith(), and llvm::StringRef::startswith().
shouldBeSls()
bool shouldBeSls (const LanaiOperand & Op)
Definition at line 842 of file LanaiAsmParser.cpp.
References llvm::LPAC::ADD, AluWithPrePost(), llvm::MCConstantExpr::create(), llvm::dyn_cast(), llvm::StringRef::endswith(), llvm::Error, llvm::StringRef::find(), llvm::SMLoc::getFromPointer(), llvm::LanaiMCExpr::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::getToken(), llvm::MCConstantExpr::getValue(), llvm::AsmToken::LBrac, llvm::MatchOperand_NoMatch, llvm::MatchOperand_ParseFail, llvm::MatchOperand_Success, Name, parseImmediate(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::AsmToken::RBrac, llvm::StringRef::rfind(), llvm::StringRef::size(), llvm::StringRef::slice(), llvm::StringRef::startswith(), llvm::StringRef::substr(), llvm::LPCC::suffixToLanaiCondCode(), Type, llvm::LPCC::UNKNOWN, and llvm::LanaiMCExpr::VK_Lanai_None.
SizeForSuffix()
static int SizeForSuffix (StringRef T) static
Definition at line 816 of file LanaiAsmParser.cpp.
References llvm::StringSwitch< T, R >::Default(), llvm::StringSwitch< T, R >::EndsWith(), llvm::AsmToken::Minus, llvm::AsmToken::Plus, llvm::AsmToken::Star, and llvm::T.