LLVM: lib/Target/Lanai/LanaiInstrInfo.cpp File Reference
LanaiInstrInfo.cpp File Reference
#include "LanaiInstrInfo.h"
#include "LanaiAluCode.h"
#include "LanaiCondCode.h"
#include "MCTargetDesc/LanaiBaseInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "LanaiGenInstrInfo.inc"
Macros
#define GET_INSTRINFO_CTOR_DTOR
Functions
static LPCC::CondCode getOppositeCondition (LPCC::CondCode CC)
static bool isRedundantFlagInstr (MachineInstr *CmpI, unsigned SrcReg, unsigned SrcReg2, int ImmValue, MachineInstr *OI)
static unsigned flagSettingOpcodeVariant (unsigned OldOpcode)
static MachineInstr * canFoldIntoSelect (unsigned Reg, const MachineRegisterInfo &MRI)
Macro Definition Documentation
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 27 of file LanaiInstrInfo.cpp.
Function Documentation
canFoldIntoSelect()
static MachineInstr* canFoldIntoSelect (unsigned Reg, const MachineRegisterInfo & MRI) static
Definition at line 457 of file LanaiInstrInfo.cpp.
References llvm::numbers::e, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MachineOperand::isCPI(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isJTI(), llvm::Register::isPhysicalRegister(), llvm::MachineInstr::isPredicable(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isSafeToMove(), llvm::MachineOperand::isTied(), llvm::Register::isVirtualRegister(), and MI.
Referenced by llvm::LanaiInstrInfo::optimizeSelect().
flagSettingOpcodeVariant()
static unsigned flagSettingOpcodeVariant (unsigned OldOpcode) inline static
Definition at line 226 of file LanaiInstrInfo.cpp.
Referenced by llvm::LanaiInstrInfo::optimizeCompareInstr().
getOppositeCondition()
static LPCC::CondCode getOppositeCondition (LPCC::CondCode CC) static
Definition at line 123 of file LanaiInstrInfo.cpp.
References llvm::LPCC::ICC_CC, llvm::LPCC::ICC_CS, llvm::LPCC::ICC_EQ, llvm::LPCC::ICC_F, llvm::LPCC::ICC_GE, llvm::LPCC::ICC_GT, llvm::LPCC::ICC_HI, llvm::LPCC::ICC_LE, llvm::LPCC::ICC_LS, llvm::LPCC::ICC_LT, llvm::LPCC::ICC_MI, llvm::LPCC::ICC_NE, llvm::LPCC::ICC_PL, llvm::LPCC::ICC_T, llvm::LPCC::ICC_VC, llvm::LPCC::ICC_VS, and llvm_unreachable.
Referenced by llvm::AVRInstrInfo::getRegisterInfo(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::LanaiInstrInfo::optimizeSelect(), and llvm::LanaiInstrInfo::reverseBranchCondition().
isRedundantFlagInstr()
static bool isRedundantFlagInstr (MachineInstr * CmpI, unsigned SrcReg, unsigned SrcReg2, int ImmValue, MachineInstr * OI) inline static
Definition at line 205 of file LanaiInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by llvm::LanaiInstrInfo::optimizeCompareInstr().