LLVM: lib/DebugInfo/CodeView/LazyRandomTypeCollection.cpp File Reference
LazyRandomTypeCollection.cpp File Reference
#include "llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/DebugInfo/CodeView/CodeViewError.h"
#include "llvm/DebugInfo/CodeView/RecordName.h"
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iterator>
Functions
static void error (Error &&EC)
Function Documentation
error()
static void error (Error && EC) static
Definition at line 28 of file LazyRandomTypeCollection.cpp.
References assert(), llvm::consumeError(), and llvm::codeview::EC.
Referenced by llvm::codeview::LazyRandomTypeCollection::getOffsetOfType(), llvm::codeview::LazyRandomTypeCollection::getType(), and llvm::codeview::LazyRandomTypeCollection::reset().