LLVM: lib/CodeGen/SelectionDAG/LegalizeVectorOps.cpp File Reference
LegalizeVectorOps.cpp File Reference
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <utility>
#include "llvm/IR/ConstrainedOps.def"
Macros
#define DEBUG_TYPE "legalizevectorops"
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
Functions
static void createBSWAPShuffleMask (EVT VT, SmallVectorImpl< int > &ShuffleMask)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalizevectorops"
Definition at line 52 of file LegalizeVectorOps.cpp.
INSTRUCTION [1/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
INSTRUCTION [2/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
Function Documentation
createBSWAPShuffleMask()
static void createBSWAPShuffleMask (EVT VT, SmallVectorImpl< int > & ShuffleMask) static
Definition at line 1174 of file LegalizeVectorOps.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, E, llvm::TargetLoweringBase::Expand, llvm::ISD::FADD, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FSUB, llvm::APInt::getAllOnesValue(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::AArch64CC::HI, I, llvm::MVT::i8, llvm::SDNode::isStrictFPOpcode(), llvm::AArch64CC::LO, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, llvm::SmallVectorBase::size(), llvm::ISD::SRL, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FMUL, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::TokenFactor, llvm::ISD::XOR, and llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent.