LLVM: lib/CodeGen/GlobalISel/LegalizerHelper.cpp File Reference
LegalizerHelper.cpp File Reference
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
#include "llvm/CodeGen/GlobalISel/GISelChangeObserver.h"
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "legalizer"
Functions
static std::pair< int, int > getNarrowTypeBreakDown (LLT OrigTy, LLT NarrowTy, LLT &LeftoverTy)
Try to break down OrigTy into NarrowTy sized pieces.
static LLT getGCDType (LLT OrigTy, LLT TargetTy)
static RTLIB::Libcall getRTLibDesc (unsigned Opcode, unsigned Size)
static bool isLibCallInTailPosition (MachineInstr &MI)
True if an instruction is in tail position in its caller.
static LegalizerHelper::LegalizeResult simpleLibcall (MachineInstr &MI, MachineIRBuilder &MIRBuilder, unsigned Size, Type *OpType)
static RTLIB::Libcall getConvRTLibDesc (unsigned Opcode, Type *ToType, Type *FromType)
static LegalizerHelper::LegalizeResult conversionLibcall (MachineInstr &MI, MachineIRBuilder &MIRBuilder, Type *ToType, Type *FromType)
static CmpInst::Predicate minMaxToCompare (unsigned Opc)
static MachineInstrBuilder SwapN (unsigned N, DstOp Dst, MachineIRBuilder &B, MachineInstrBuilder Src, APInt Mask)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalizer"
Definition at line 28 of file LegalizerHelper.cpp.
Function Documentation
conversionLibcall()
static LegalizerHelper::LegalizeResult conversionLibcall (MachineInstr & MI, MachineIRBuilder & MIRBuilder, Type * ToType, Type * FromType) static
Definition at line 482 of file LegalizerHelper.cpp.
References llvm::createLibcall(), getConvRTLibDesc(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by llvm::LegalizerHelper::libcall().
getConvRTLibDesc()
static RTLIB::Libcall getConvRTLibDesc (unsigned Opcode, Type * ToType, Type * FromType) static
Definition at line 459 of file LegalizerHelper.cpp.
References llvm::RTLIB::getFPEXT(), llvm::RTLIB::getFPROUND(), llvm::RTLIB::getFPTOSINT(), llvm::RTLIB::getFPTOUINT(), llvm::RTLIB::getSINTTOFP(), llvm::RTLIB::getUINTTOFP(), llvm::MVT::getVT(), and llvm_unreachable.
Referenced by conversionLibcall().
getGCDType()
static LLT getGCDType (LLT OrigTy, LLT TargetTy) static
Definition at line 175 of file LegalizerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildConcatVectors(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), E, llvm::ArrayRef< T >::empty(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::greatestCommonDivisor(), I, llvm::LLT::isValid(), llvm::LLT::isVector(), llvm::LegalizerHelper::MIRBuilder, llvm::LLT::scalar(), llvm::LLT::scalarOrVector(), and llvm::ArrayRef< T >::size().
Referenced by llvm::LegalizerHelper::fewerElementsVectorUnmergeValues().
getNarrowTypeBreakDown()
static std::pair<int, int> getNarrowTypeBreakDown (LLT OrigTy, LLT NarrowTy, LLT & LeftoverTy) static
Try to break down OrigTy into NarrowTy sized pieces.
Returns the number of NarrowTy elements needed to reconstruct OrigTy, with any leftover piece as type LeftoverTy
Returns -1 in the first element of the pair if the breakdown is not satisfiable.
Definition at line 41 of file LegalizerHelper.cpp.
References assert(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::LLT::isValid(), llvm::LLT::isVector(), llvm::LLT::scalar(), llvm::LLT::scalarOrVector(), and Size.
Referenced by llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), and llvm::LegalizerHelper::reduceLoadStoreWidth().
getRTLibDesc()
static RTLIB::Libcall getRTLibDesc (unsigned Opcode, unsigned Size) static
Definition at line 240 of file LegalizerHelper.cpp.
References assert(), and llvm_unreachable.
Referenced by simpleLibcall().
isLibCallInTailPosition()
static bool isLibCallInTailPosition (MachineInstr & MI) static
True if an instruction is in tail position in its caller.
Intended for legalizing libcalls as tail calls when possible.
Definition at line 332 of file LegalizerHelper.cpp.
References F(), llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getMF(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getSubtarget(), llvm::AttributeList::hasAttribute(), llvm::MachineInstr::isReturn(), llvm::HexagonInstrInfo::isTailCall(), llvm::NoAlias, llvm::AttributeList::ReturnIndex, and TII.
Referenced by llvm::createMemLibcall().
minMaxToCompare()
static CmpInst::Predicate minMaxToCompare (unsigned Opc) static
Definition at line 4013 of file LegalizerHelper.cpp.
References llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by llvm::LegalizerHelper::lowerMinMax().
simpleLibcall()
static LegalizerHelper::LegalizeResult simpleLibcall (MachineInstr & MI, MachineIRBuilder & MIRBuilder, unsigned Size, Type * OpType) static
Definition at line 380 of file LegalizerHelper.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::createLibcall(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getRTLibDesc(), and Size.
Referenced by llvm::LegalizerHelper::libcall().
SwapN()
static MachineInstrBuilder SwapN (unsigned N, DstOp Dst, MachineIRBuilder & B, MachineInstrBuilder Src, APInt Mask) static
Definition at line 4431 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildShl(), llvm::DstOp::getLLTTy(), and llvm::MachineIRBuilder::getMRI().
Referenced by llvm::LegalizerHelper::lowerBitreverse().