LLVM: lib/CodeGen/GlobalISel/LegalizerInfo.cpp File Reference
LegalizerInfo.cpp File Reference
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/CodeGen/GlobalISel/GISelChangeObserver.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LowLevelTypeImpl.h"
#include "llvm/Support/MathExtras.h"
#include <algorithm>
#include <map>
Macros
#define DEBUG_TYPE "legalizer-info"
Functions
static bool hasNoSimpleLoops (const LegalizeRule &Rule, const LegalityQuery &Q, const std::pair< unsigned, LLT > &Mutation)
static bool mutationIsSane (const LegalizeRule &Rule, const LegalityQuery &Q, std::pair< unsigned, LLT > Mutation)
static LLT getTypeFromTypeIdx (const MachineInstr &MI, const MachineRegisterInfo &MRI, unsigned OpIdx, unsigned TypeIdx)
Helper function to get LLT for the given type index.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalizer-info"
Definition at line 38 of file LegalizerInfo.cpp.
Function Documentation
getTypeFromTypeIdx()
static LLT getTypeFromTypeIdx (const MachineInstr & MI, const MachineRegisterInfo & MRI, unsigned OpIdx, unsigned TypeIdx) static
Helper function to get LLT for the given type index.
Definition at line 392 of file LegalizerInfo.cpp.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getReg(), and llvm::MachineRegisterInfo::getType().
Referenced by llvm::LegalizerInfo::getAction().
hasNoSimpleLoops()
static bool hasNoSimpleLoops (const LegalizeRule & Rule, const LegalityQuery & Q, const std::pair< unsigned, LLT > & Mutation) static
Definition at line 102 of file LegalizerInfo.cpp.
References llvm::LegalizeActions::Custom, llvm::LegalizeActions::FewerElements, llvm::LegalizeRule::getAction(), llvm::LegalizeActions::Lower, llvm::LegalizeActions::MoreElements, and llvm::LegalityQuery::Types.
Referenced by llvm::LegalizeRuleSet::apply().
mutationIsSane()
static bool mutationIsSane (const LegalizeRule & Rule, const LegalityQuery & Q, std::pair< unsigned, LLT > Mutation) static
Definition at line 117 of file LegalizerInfo.cpp.
References llvm::LegalizeActions::Custom, llvm::LegalizeActions::FewerElements, llvm::LegalizeRule::getAction(), llvm::LLT::getNumElements(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getScalarType(), llvm::LLT::isVector(), LLVM_FALLTHROUGH, llvm::LegalizeActions::MoreElements, llvm::LegalizeActions::NarrowScalar, llvm::LegalityQuery::Types, and llvm::LegalizeActions::WidenScalar.
Referenced by llvm::LegalizeRuleSet::apply().