LLVM: lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp File Reference
LegalizeVectorTypes.cpp File Reference
#include "LegalizeTypes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/TypeSize.h"
#include "llvm/IR/ConstrainedOps.def"
Macros
#define DEBUG_TYPE "legalize-types"
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
Functions
static SDValue CollectOpsToWiden (SelectionDAG &DAG, const TargetLowering &TLI, SmallVectorImpl< SDValue > &ConcatOps, unsigned ConcatEnd, EVT VT, EVT MaxVT, EVT WidenVT)
static bool isSETCCOp (unsigned Opcode)
static bool isLogicalMaskOp (unsigned Opcode)
static EVT getSETCCOperandType (SDValue N)
static bool isSETCCorConvertedSETCC (SDValue N)
static EVT FindMemType (SelectionDAG &DAG, const TargetLowering &TLI, unsigned Width, EVT WidenVT, unsigned Align=0, unsigned WidenEx=0)
static SDValue BuildVectorFromScalar (SelectionDAG &DAG, EVT VecTy, SmallVectorImpl< SDValue > &LdOps, unsigned Start, unsigned End)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalize-types"
Definition at line 29 of file LegalizeVectorTypes.cpp.
INSTRUCTION [1/3]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
INSTRUCTION [2/3]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
INSTRUCTION [3/3]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
Function Documentation
BuildVectorFromScalar()
static SDValue BuildVectorFromScalar (SelectionDAG & DAG, EVT VecTy, SmallVectorImpl< SDValue > & LdOps, unsigned Start, unsigned End) static
Definition at line 4836 of file LegalizeVectorTypes.cpp.
CollectOpsToWiden()
static SDValue CollectOpsToWiden (SelectionDAG & DAG, const TargetLowering & TLI, SmallVectorImpl< SDValue > & ConcatOps, unsigned ConcatEnd, EVT VT, EVT MaxVT, EVT WidenVT) static
Definition at line 2891 of file LegalizeVectorTypes.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, assert(), llvm::ISD::BITCAST, llvm::EVT::bitsEq(), llvm::TargetLoweringBase::canOpTrap(), llvm::ISD::CONCAT_VECTORS, llvm::SmallVectorTemplateCommon< T >::data(), llvm::numbers::e, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MaskedLoadStoreSDNode::getAddressingMode(), llvm::MaskedLoadSDNode::getBasePtr(), llvm::MaskedGatherScatterSDNode::getBasePtr(), llvm::SelectionDAG::getBuildVector(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::LoadSDNode::getExtensionType(), llvm::MaskedLoadSDNode::getExtensionType(), llvm::SDNode::getFlags(), llvm::MaskedGatherScatterSDNode::getIndex(), llvm::MaskedGatherScatterSDNode::getIndexType(), llvm::MaskedLoadSDNode::getMask(), llvm::MaskedGatherScatterSDNode::getMask(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::MaskedLoadSDNode::getOffset(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MaskedLoadSDNode::getPassThru(), llvm::MaskedGatherSDNode::getPassThru(), llvm::EVT::getScalarType(), llvm::MaskedGatherScatterSDNode::getScale(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::EVT::getSizeInBits(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::DataLayout::isBigEndian(), llvm::MaskedLoadSDNode::isExpandingLoad(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm_unreachable, llvm::makeArrayRef(), llvm::BitmaskEnumDetail::Mask(), N, llvm::ISD::NON_EXTLOAD, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::SmallVectorBase::size(), llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::STRICT_UINT_TO_FP, llvm::ISD::TokenFactor, llvm::TargetLoweringBase::TypeExpandFloat, llvm::TargetLoweringBase::TypeExpandInteger, llvm::TargetLoweringBase::TypeLegal, llvm::TargetLoweringBase::TypePromoteFloat, llvm::TargetLoweringBase::TypePromoteInteger, llvm::TargetLoweringBase::TypeScalarizeVector, llvm::TargetLoweringBase::TypeSoftenFloat, llvm::TargetLoweringBase::TypeSplitVector, llvm::TargetLoweringBase::TypeWidenVector, llvm::SelectionDAG::UnrollVectorOp(), llvm::MVT::x86mmx, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
FindMemType()
static EVT FindMemType (SelectionDAG & DAG, const TargetLowering & TLI, unsigned Width, EVT WidenVT, unsigned Align = 0, unsigned WidenEx = 0) static
Definition at line 4767 of file LegalizeVectorTypes.cpp.
References llvm::MVT::FIRST_INTEGER_VALUETYPE, llvm::MVT::FIRST_VECTOR_VALUETYPE, llvm::SelectionDAG::getContext(), llvm::TypeSize::getKnownMinSize(), llvm::EVT::getSizeInBits(), llvm::TargetLoweringBase::getTypeAction(), llvm::EVT::getVectorElementType(), llvm::isPowerOf2_32(), llvm::EVT::isScalableVector(), llvm::MVT::LAST_INTEGER_VALUETYPE, llvm::MVT::LAST_VECTOR_VALUETYPE, llvm::TargetLoweringBase::TypeLegal, and llvm::TargetLoweringBase::TypePromoteInteger.
getSETCCOperandType()
static EVT getSETCCOperandType (SDValue N) inline static
Definition at line 3804 of file LegalizeVectorTypes.cpp.
References llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), and llvm::SDNode::isStrictFPOpcode().
isLogicalMaskOp()
static bool isLogicalMaskOp (unsigned Opcode) inline static
Definition at line 3792 of file LegalizeVectorTypes.cpp.
References llvm::ISD::AND, llvm::ISD::OR, and llvm::ISD::XOR.
Referenced by isSETCCorConvertedSETCC().
isSETCCOp()
static bool isSETCCOp (unsigned Opcode) inline static
Definition at line 3781 of file LegalizeVectorTypes.cpp.
References llvm::ISD::SETCC, llvm::ISD::STRICT_FSETCC, and llvm::ISD::STRICT_FSETCCS.
Referenced by isSETCCorConvertedSETCC().
isSETCCorConvertedSETCC()
static bool isSETCCorConvertedSETCC (SDValue N) inline static
Definition at line 3812 of file LegalizeVectorTypes.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::numbers::e, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ISD::isBuildVectorOfConstantSDNodes(), isLogicalMaskOp(), isSETCCOp(), llvm::SDNode::isStrictFPOpcode(), llvm::SDNode::isUndef(), llvm::BitmaskEnumDetail::Mask(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::TRUNCATE.