LLVM: lib/Transforms/Utils/LibCallsShrinkWrap.cpp File Reference
LibCallsShrinkWrap.cpp File Reference
#include "llvm/Transforms/Utils/LibCallsShrinkWrap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Classes
class false::LibCallsShrinkWrap
Namespaces
false
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "libcalls-shrinkwrap"
Functions
STATISTIC (NumWrappedOneCond, "Number of One-Condition Wrappers Inserted")
STATISTIC (NumWrappedTwoCond, "Number of Two-Condition Wrappers Inserted")
INITIALIZE_PASS_BEGIN (LibCallsShrinkWrapLegacyPass, "libcalls-shrinkwrap", "Conditionally eliminate dead library calls", false, false) INITIALIZE_PASS_END(LibCallsShrinkWrapLegacyPass
static bool runImpl (Function &F, const TargetLibraryInfo &TLI, DominatorTree *DT)
FunctionPass * llvm::createLibCallsShrinkWrapPass ()
Variables
libcalls shrinkwrap
libcalls Conditionally eliminate dead library calls
libcalls Conditionally eliminate dead library false
char & llvm::LibCallsShrinkWrapPassID = LibCallsShrinkWrapLegacyPass::ID
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "libcalls-shrinkwrap"
Definition at line 47 of file LibCallsShrinkWrap.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LibCallsShrinkWrapLegacyPass , "libcalls-shrinkwrap" , "Conditionally eliminate dead library calls" , false , false)
runImpl()
static bool runImpl (Function & F, const TargetLibraryInfo & TLI, DominatorTree * DT) static
Definition at line 523 of file LibCallsShrinkWrap.cpp.
References assert(), F(), llvm::CallingConv::Fast, llvm::Function::hasFnAttribute(), runOnFunction(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::verify().
Referenced by llvm::LibCallsShrinkWrapPass::run().
STATISTIC() [1/2]
STATISTIC (NumWrappedOneCond , "Number of One-Condition Wrappers Inserted")
STATISTIC() [2/2]
STATISTIC (NumWrappedTwoCond , "Number of Two-Condition Wrappers Inserted")
Variable Documentation
calls
libcalls Conditionally eliminate dead library calls
Definition at line 70 of file LibCallsShrinkWrap.cpp.
false
libcalls Conditionally eliminate dead library false
Definition at line 70 of file LibCallsShrinkWrap.cpp.
shrinkwrap
libcalls shrinkwrap
Definition at line 70 of file LibCallsShrinkWrap.cpp.