LLVM: lib/ToolDrivers/llvm-lib/LibDriver.cpp File Reference
LibDriver.cpp File Reference
#include "llvm/ToolDrivers/llvm-lib/LibDriver.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Object/ArchiveWriter.h"
#include "llvm/Object/COFF.h"
#include "llvm/Object/WindowsMachineFlag.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/raw_ostream.h"
#include "Options.inc"
Macros
#define OPTION(_1, _2, ID, _4, _5, _6, _7, _8, _9, _10, _11, _12) OPT_##ID,
#define PREFIX(NAME, VALUE) const char *const NAME[] = VALUE;
#define OPTION(X1, X2, ID, KIND, GROUP, ALIAS, X7, X8, X9, X10, X11, X12)
Enumerations
enum
Functions
static std::string getOutputPath (opt::InputArgList *Args, const NewArchiveMember &FirstMember)
static std::vector< StringRef > getSearchPaths (opt::InputArgList *Args, StringSaver &Saver)
static std::string findInputFile (StringRef File, ArrayRef< StringRef > Paths)
static void fatalOpenError (llvm::Error E, Twine File)
static void doList (opt::InputArgList &Args)
static COFF::MachineTypes getCOFFFileMachine (MemoryBufferRef MB)
static COFF::MachineTypes getBitcodeFileMachine (MemoryBufferRef MB)
static void appendFile (std::vector< NewArchiveMember > &Members, COFF::MachineTypes &LibMachine, std::string &LibMachineSource, MemoryBufferRef MB)
Macro Definition Documentation
OPTION [1/2]
#define OPTION (_1, _2, ID, _4, _5, _6, _7, _8, _9, _10, _11, _12) OPT_##ID,
Definition at line 38 of file LibDriver.cpp.
OPTION [2/2]
#define OPTION (X1, X2, ID, KIND, GROUP, ALIAS, X7, X8, X9, X10, X11, X12)
Value:
{X1, X2, X10,         X11,         OPT_##ID, opt::Option::KIND##Class,       \
   X9, X8, OPT_##GROUP, OPT_##ALIAS, X7,       X12},
Definition at line 38 of file LibDriver.cpp.
PREFIX
#define PREFIX (NAME, VALUE) const char *const NAME[] = VALUE;
Definition at line 43 of file LibDriver.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 36 of file LibDriver.cpp.
Function Documentation
appendFile()
static void appendFile (std::vector< NewArchiveMember > & Members, COFF::MachineTypes & LibMachine, std::string & LibMachineSource, MemoryBufferRef MB) static
Definition at line 191 of file LibDriver.cpp.
References llvm::file_magic::archive, llvm::file_magic::bitcode, llvm::file_magic::coff_object, llvm::errs(), llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferIdentifier(), llvm::identify_magic(), Magic, and llvm::file_magic::windows_resource.
doList()
static void doList (opt::InputArgList & Args) static
Definition at line 113 of file LibDriver.cpp.
References llvm::file_magic::archive, Arg, B, llvm::errorCodeToError(), fatalOpenError(), llvm::opt::ArgList::filtered(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), and llvm::identify_magic().
fatalOpenError()
static void fatalOpenError (llvm::Error E, Twine File) static
Definition at line 104 of file LibDriver.cpp.
References llvm::errs(), llvm::handleAllErrors(), and llvm::ErrorInfoBase::message().
Referenced by doList().
findInputFile()
static std::string findInputFile (StringRef File, ArrayRef< StringRef > Paths) static
Definition at line 94 of file LibDriver.cpp.
References llvm::sys::path::append(), llvm::sys::fs::exists(), llvm::StringRef::str(), and llvm::SmallString< InternalLen >::str().
getBitcodeFileMachine()
static COFF::MachineTypes getBitcodeFileMachine (MemoryBufferRef MB) static
Definition at line 167 of file LibDriver.cpp.
References llvm::Triple::aarch64, llvm::Triple::arm, llvm::errs(), llvm::Triple::getArch(), llvm::getBitcodeTargetTriple(), llvm::MemoryBufferRef::getBufferIdentifier(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::Triple::x86, and llvm::Triple::x86_64.
getCOFFFileMachine()
static COFF::MachineTypes getCOFFFileMachine (MemoryBufferRef MB) static
Definition at line 145 of file LibDriver.cpp.
References llvm::errs(), llvm::MemoryBufferRef::getBufferIdentifier(), llvm::object::COFFObjectFile::getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, and Machine.
getOutputPath()
static std::string getOutputPath (opt::InputArgList * Args, const NewArchiveMember & FirstMember) static
Definition at line 62 of file LibDriver.cpp.
References Arg, llvm::NewArchiveMember::Buf, llvm::opt::ArgList::getLastArg(), llvm::sys::path::replace_extension(), and llvm::SmallString< InternalLen >::str().
getSearchPaths()
static std::vector<StringRef> getSearchPaths (opt::InputArgList * Args, StringSaver & Saver) static
Definition at line 71 of file LibDriver.cpp.
References Arg, llvm::StringRef::empty(), llvm::opt::ArgList::filtered(), llvm::sys::Process::GetEnv(), llvm::Optional< T >::hasValue(), llvm::MipsISD::Ret, llvm::StringSaver::save(), and llvm::StringRef::split().