LLVM: lib/DebugInfo/GSYM/LineTable.cpp File Reference
LineTable.cpp File Reference
#include "llvm/DebugInfo/GSYM/LineTable.h"
#include "llvm/DebugInfo/GSYM/FileWriter.h"
#include "llvm/Support/DataExtractor.h"
Classes
struct DeltaInfo
Typedefs
typedef std::function< bool(const LineEntry &Row)> LineEntryCallback
Enumerations
enum LineTableOpCode {
EndSequence = 0x00, SetFile = 0x01, AdvancePC = 0x02, AdvanceLine = 0x03,
FirstSpecial = 0x04
}
Functions
bool operator< (const DeltaInfo &LHS, int64_t Delta)
static bool encodeSpecial (int64_t MinLineDelta, int64_t MaxLineDelta, int64_t LineDelta, uint64_t AddrDelta, uint8_t &SpecialOp)
static llvm::Error parse (DataExtractor &Data, uint64_t BaseAddr, LineEntryCallback const &Callback)
Typedef Documentation
LineEntryCallback
typedef std::function<bool(const LineEntry &Row)> LineEntryCallback
Definition at line 52 of file LineTable.cpp.
Enumeration Type Documentation
LineTableOpCode
enum LineTableOpCode
Enumerator
EndSequence
End of the line table.
SetFile
Set LineTableRow.file_idx, don't push a row.
AdvancePC
Increment LineTableRow.address, and push a row.
AdvanceLine
Set LineTableRow.file_line, don't push a row.
FirstSpecial
All special opcodes push a row.
Definition at line 16 of file LineTable.cpp.
Function Documentation
encodeSpecial()
static bool encodeSpecial (int64_t MinLineDelta, int64_t MaxLineDelta, int64_t LineDelta, uint64_t AddrDelta, uint8_t & SpecialOp) static
Definition at line 34 of file LineTable.cpp.
References FirstSpecial.
operator<()
bool operator< (const DeltaInfo & LHS, int64_t Delta) inline
Definition at line 30 of file LineTable.cpp.
References DeltaInfo::Delta.
Referenced by llvm::RegBankSelect::EdgeInsertPoint::canMaterialize(), llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), and llvm::SystemZPostRASchedStrategy::pickNode().
parse()
static llvm::Error parse (DataExtractor & Data, uint64_t BaseAddr, LineEntryCallback const & Callback) static
Definition at line 54 of file LineTable.cpp.
References llvm::gsym::LineEntry::Addr, AdvanceLine, AdvancePC, llvm::createStringError(), EndSequence, llvm::gsym::LineEntry::File, FirstSpecial, llvm::DataExtractor::getSLEB128(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), llvm::DataExtractor::isValidOffset(), llvm::gsym::LineEntry::Line, SetFile, and llvm::Error::success().
Referenced by llvm::DWARFDebugAbbrev::begin(), llvm::DWARFDebugAbbrev::dump(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), llvm::AMDGPULibFunc::getFunctionType(), llvm::DWARFDebugLine::Prologue::getMaxLineIncrementForSpecialOpcode(), nodeListToNodeArray(), llvm::SymbolRewriter::RewriteMapParser::parse(), llvm::object::parseCOFFModuleDefinition(), llvm::cl::parser< bool >::parser(), llvm::cl::parser< boolOrDefault >::parser(), llvm::cl::parser< int >::parser(), llvm::cl::parser< long >::parser(), llvm::cl::parser< long long >::parser(), llvm::cl::parser< unsigned >::parser(), llvm::cl::parser< unsigned long >::parser(), llvm::cl::parser< unsigned long long >::parser(), llvm::cl::parser< double >::parser(), llvm::cl::parser< float >::parser(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::resolveForwardTemplateRefs(), and toString().