LLVM: lib/Linker/LinkModules.cpp File Reference
LinkModules.cpp File Reference
#include "LinkDiagnosticInfo.h"
#include "llvm-c/Linker.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Linker/Linker.h"
#include "llvm/Support/Error.h"
Functions
static GlobalValue::VisibilityTypes getMinVisibility (GlobalValue::VisibilityTypes A, GlobalValue::VisibilityTypes B)
LLVMBool LLVMLinkModules2 (LLVMModuleRef Dest, LLVMModuleRef Src)
Function Documentation
getMinVisibility()
static GlobalValue::VisibilityTypes getMinVisibility (GlobalValue::VisibilityTypes A, GlobalValue::VisibilityTypes B) static
Definition at line 120 of file LinkModules.cpp.
References llvm::MCID::Add, llvm::Module::alias_begin(), llvm::Module::alias_end(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::SystemZICMP::Any, assert(), llvm::Module::begin(), C, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), llvm::Function::Create(), llvm::GlobalValue::DefaultVisibility, llvm::LLVMContext::diagnose(), llvm::DS_Error, llvm::dyn_cast(), E, llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::Module::end(), llvm::GlobalValue::eraseFromParent(), llvm::GlobalValue::ExternalLinkage, F(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::SetVector< T, Vector, Set >::getArrayRef(), llvm::GlobalValue::getBaseObject(), llvm::GlobalValue::getComdat(), llvm::Module::getComdatSymbolTable(), llvm::Module::getContext(), llvm::Module::getDataLayout(), llvm::PointerType::getElementType(), llvm::GlobalVariable::getInitializer(), llvm::GlobalValue::getMinUnnamedAddr(), llvm::IRMover::getModule(), llvm::Comdat::getName(), llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::GlobalValue::getParent(), llvm::Comdat::getSelectionKind(), llvm::DataLayout::getTypeAllocSize(), llvm::GlobalValue::getUnnamedAddr(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::getVisibility(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::handleAllErrors(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasDLLImportStorageClass(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasWeakLinkage(), llvm::GlobalValue::HiddenVisibility, I, llvm::StringSet< AllocatorTy >::insert(), llvm::SetVector< T, Vector, Set >::insert(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::GlobalValue::isDeclaration(), llvm::GlobalValue::isDeclarationForLinker(), llvm::GlobalValue::isWeakForLinker(), llvm_unreachable, llvm::max(), llvm::ErrorInfoBase::message(), llvm::IRMover::move(), llvm::GlobalValue::ProtectedVisibility, llvm::PPCISD::SC, llvm::GlobalVariable::setConstant(), llvm::GlobalValue::setUnnamedAddr(), llvm::GlobalValue::setVisibility(), llvm::SetVector< T, Vector, Set >::size(), llvm::Value::takeName(), and llvm::Value::use_empty().
LLVMLinkModules2()
LLVMBool LLVMLinkModules2 (LLVMModuleRef Dest, LLVMModuleRef Src)
Definition at line 602 of file LinkModules.cpp.
References D, llvm::Linker::linkModules(), and llvm::unwrap().