LLVM: lib/CodeGen/LiveRegUnits.cpp File Reference
LiveRegUnits.cpp File Reference
#include "llvm/CodeGen/LiveRegUnits.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
Functions
static void addBlockLiveIns (LiveRegUnits &LiveUnits, const MachineBasicBlock &MBB)
Add live-in registers of basic block MBB to LiveUnits.
static void addCalleeSavedRegs (LiveRegUnits &LiveUnits, const MachineFunction &MF)
Adds all callee saved registers to LiveUnits.
Function Documentation
addBlockLiveIns()
static void addBlockLiveIns (LiveRegUnits & LiveUnits, const MachineBasicBlock & MBB) static
Add live-in registers of basic block MBB to LiveUnits.
Definition at line 78 of file LiveRegUnits.cpp.
References llvm::LiveRegUnits::addRegMasked(), and llvm::MachineBasicBlock::liveins().
Referenced by llvm::LiveRegUnits::addLiveIns(), and llvm::LiveRegUnits::addLiveOuts().
addCalleeSavedRegs()
static void addCalleeSavedRegs (LiveRegUnits & LiveUnits, const MachineFunction & MF) static
Adds all callee saved registers to LiveUnits.
Definition at line 85 of file LiveRegUnits.cpp.
References llvm::LiveRegUnits::addReg(), llvm::LiveRegUnits::addUnits(), llvm::LiveRegUnits::empty(), llvm::LiveRegUnits::getBitVector(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getRegInfo(), Info, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), MRI, and llvm::LiveRegUnits::removeReg().
Referenced by llvm::LiveRegUnits::addLiveOuts().