LLVM: lib/CodeGen/LiveRangeCalc.cpp File Reference
LiveRangeCalc.cpp File Reference
#include "llvm/CodeGen/LiveRangeCalc.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/LiveInterval.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SlotIndexes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <tuple>
#include <utility>
Macros
#define DEBUG_TYPE "regalloc"
Functions
static void createDeadDef (SlotIndexes &Indexes, VNInfo::Allocator &Alloc, LiveRange &LR, const MachineOperand &MO)
Variables
static VNInfo UndefVNI (0xbad, SlotIndex())
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regalloc"
Definition at line 38 of file LiveRangeCalc.cpp.
Function Documentation
createDeadDef()
static void createDeadDef (SlotIndexes & Indexes, VNInfo::Allocator & Alloc, LiveRange & LR, const MachineOperand & MO) static
Definition at line 64 of file LiveRangeCalc.cpp.
References llvm::LiveRange::createDeadDef(), llvm::SlotIndexes::getInstructionIndex(), llvm::MachineOperand::getParent(), llvm::SlotIndex::getRegSlot(), llvm::MachineOperand::isEarlyClobber(), and MI.
Referenced by llvm::LiveRangeCalc::calculate(), llvm::LiveRangeCalc::createDeadDefs(), and llvm::LiveRange::getNextValue().
Variable Documentation
UndefVNI
VNInfo UndefVNI(0xbad, SlotIndex()) static
Referenced by llvm::LiveRangeCalc::calculateValues().