LLVM: lib/CodeGen/LiveDebugValues.cpp File Reference
LiveDebugValues.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/SparseBitVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/UniqueVector.h"
#include "llvm/CodeGen/LexicalScopes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <functional>
#include <queue>
#include <tuple>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "livedebugvalues"
Functions
STATISTIC (NumInserted, "Number of DBG_VALUE instructions inserted")
STATISTIC (NumRemoved, "Number of DBG_VALUE instructions removed")
static Register isDbgValueDescribedByReg (const MachineInstr &MI)
static bool isRegOtherThanSPAndFP (const MachineOperand &Op, const MachineInstr &MI, const TargetRegisterInfo *TRI)
If Op is a stack or frame register return true, otherwise return false.
INITIALIZE_PASS (LiveDebugValues, DEBUG_TYPE, "Live DEBUG_VALUE analysis", false, false) LiveDebugValues
Default construct and initialize the pass.
static void collectRegDefs (const MachineInstr &MI, DefinedRegsSet &Regs, const TargetRegisterInfo *TRI)
Collect all register defines (including aliases) for the given instruction.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "livedebugvalues"
Definition at line 78 of file LiveDebugValues.cpp.
Function Documentation
collectRegDefs()
static void collectRegDefs (const MachineInstr & MI, DefinedRegsSet & Regs, const TargetRegisterInfo * TRI) static
Collect all register defines (including aliases) for the given instruction.
Definition at line 1440 of file LiveDebugValues.cpp.
References assert(), llvm::ReversePostOrderTraversal< GraphT, GT >::begin(), llvm::MachineFunction::begin(), llvm::dbgs(), llvm::MachineInstr::dump(), llvm::ReversePostOrderTraversal< GraphT, GT >::end(), llvm::DIExpression::EntryValue, llvm::TargetFrameLowering::getCalleeSaves(), llvm::MachineInstr::getDebugExpression(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDebugVariable(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::Function::getSubprogram(), llvm::MachineFunction::getSubtarget(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineBasicBlock::insertAfterBundle(), llvm::MachineBasicBlock::instrs(), llvm::MachineInstr::isDebugValue(), llvm::MCRegAliasIterator::isValid(), llvm::join(), LLVM_DEBUG, llvm::AArch64CC::LS, MI, llvm::DICompileUnit::NoDebug, llvm::none_of(), llvm::MachineInstr::operands(), llvm::DIExpression::prepend(), TII, llvm::SystemZISD::TM, and TRI.
INITIALIZE_PASS()
INITIALIZE_PASS (LiveDebugValues , DEBUG_TYPE , "Live DEBUG_VALUE analysis" , false , false)
Default construct and initialize the pass.
Definition at line 594 of file LiveDebugValues.cpp.
References assert(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::MachineInstr::dump(), llvm::MachineBasicBlock::end(), llvm::PseudoSourceValue::FixedStack, llvm::DIExpression::fragmentsOverlap(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineInstr::getDebugExpression(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDebugVariable(), llvm::MachineInstr::getFoldedSpillSize(), llvm::DebugVariable::getFragmentOrDefault(), llvm::DebugVariable::getInlinedAt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getMF(), llvm::DIVariable::getName(), llvm::MachineBasicBlock::getNumber(), llvm::DIExpression::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::PassRegistry::getPassRegistry(), llvm::MachineOperand::getReg(), llvm::MachineInstr::getRestoreSize(), llvm::ilist_node_impl< OptionsT >::getReverseIterator(), llvm::MachineInstr::getSpillSize(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::DebugVariable::getVariable(), llvm::MachineInstr::hasOneMemOperand(), I, llvm::initializeLiveDebugValuesPass(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineInstr::isCall(), isCalleeSavedReg(), llvm::MachineOperand::isCImm(), isDbgValueDescribedByReg(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::DebugVariable::isDefaultFragment(), isDescribedByReg(), llvm::MachineOperand::isFPImm(), llvm::MachineInstr::isIdenticalTo(), llvm::MachineOperand::isImm(), llvm::MachineInstr::isIndirectDebugValue(), llvm::MachineOperand::isKill(), llvm::DILocalVariable::isParameter(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), isRegOtherThanSPAndFP(), llvm::MachineOperand::isUse(), llvm::MCRegAliasIterator::isValid(), llvm::DILocalVariable::isValidLocationForIntrinsic(), llvm::join(), llvm::PseudoSourceValue::kind(), LLVM_DEBUG, llvm_unreachable, llvm::AArch64CC::LS, llvm::MachineInstr::memoperands_begin(), MI, Name, llvm::None, llvm::MachineInstr::operands(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::predecessors(), llvm::MachineInstr::print(), llvm::printReg(), Reg, llvm::MachineBasicBlock::rend(), llvm::SparseBitVector< ElementSize >::set(), llvm::AnalysisUsage::setPreservesCFG(), TII, llvm::SystemZISD::TM, and TRI.
isDbgValueDescribedByReg()
static Register isDbgValueDescribedByReg (const MachineInstr & MI) static
Definition at line 85 of file LiveDebugValues.cpp.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isReg(), and Register.
Referenced by INITIALIZE_PASS(), and isRegOtherThanSPAndFP().
isRegOtherThanSPAndFP()
static bool isRegOtherThanSPAndFP (const MachineOperand & Op, const MachineInstr & MI, const TargetRegisterInfo * TRI) static
If Op is a stack or frame register return true, otherwise return false.
This is used to avoid basing the debug entry values on the registers, since we do not support it at the moment.
Definition at line 96 of file LiveDebugValues.cpp.
References llvm::DIExpression::ApplyOffset, assert(), llvm::BuildMI(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), clear(), llvm::SmallPtrSetImpl< PtrType >::count(), D, llvm::dbgs(), llvm::LexicalScopes::dominates(), llvm::dump(), llvm::SmallPtrSetImplBase::empty(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::empty(), llvm::MachineOperand::getCImm(), llvm::MachineInstr::getDebugExpression(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDebugVariable(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getFPImm(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MachineOperand::getImm(), llvm::DebugVariable::getInlinedAt(), llvm::LexicalScopes::getMachineBasicBlocks(), llvm::Metadata::getMetadataID(), llvm::DIVariable::getName(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::DebugVariable::getVariable(), llvm::MachineOperand::isCImm(), isConstant(), isDbgValueDescribedByReg(), llvm::MachineInstr::isDebugValue(), isDescribedByReg(), llvm::MachineOperand::isFPImm(), llvm::MachineOperand::isImm(), llvm::MachineInstr::isIndirectDebugValue(), llvm::MachineOperand::isReg(), llvm::join(), llvm_unreachable, llvm::AArch64CC::LS, MI, llvm::MachineFunctionProperties::NoVRegs, llvm::operator<(), llvm::operator==(), llvm::Other, llvm::DIExpression::prepend(), llvm::printReg(), Reg, llvm::MachineFunctionProperties::set(), TII, and TRI.
Referenced by INITIALIZE_PASS().
STATISTIC() [1/2]
STATISTIC (NumInserted , "Number of DBG_VALUE instructions inserted")
STATISTIC() [2/2]
STATISTIC (NumRemoved , "Number of DBG_VALUE instructions removed")