LLVM: lib/CodeGen/LivePhysRegs.cpp File Reference
LivePhysRegs.cpp File Reference
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/LiveRegUnits.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void addCalleeSavedRegs (LivePhysRegs &LiveRegs, const MachineFunction &MF)
Adds all callee saved registers to LiveRegs.
Function Documentation
addCalleeSavedRegs()
static void addCalleeSavedRegs (LivePhysRegs & LiveRegs, const MachineFunction & MF) static
Adds all callee saved registers to LiveRegs.
Definition at line 172 of file LivePhysRegs.cpp.
References llvm::LivePhysRegs::addReg(), llvm::LivePhysRegs::empty(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getRegInfo(), Info, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), MRI, and llvm::LivePhysRegs::removeReg().