LLVM: lib/AsmParser/LLParser.cpp File Reference
LLParser.cpp File Reference
#include "LLParser.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/AsmParser/SlotMapping.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstring>
#include <iterator>
#include <vector>
#include "llvm/IR/Metadata.def"
Macros
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS)
#define DECLARE_FIELD(NAME, TYPE, INIT) TYPE NAME INIT
#define NOP_FIELD(NAME, TYPE, INIT)
#define REQUIRE_FIELD(NAME, TYPE, INIT)
#define PARSE_MD_FIELD(NAME, TYPE, DEFAULT)
#define PARSE_MD_FIELDS()
#define GET_OR_DISTINCT(CLASS, ARGS) (IsDistinct ? CLASS::getDistinct ARGS : CLASS::get ARGS)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
Functions
static std::string getTypeString (Type *T)
static bool isValidVisibilityForLinkage (unsigned V, unsigned L)
static void maybeSetDSOLocal (bool DSOLocal, GlobalValue &GV)
static GlobalValue * createGlobalFwdRef (Module *M, PointerType *PTy, const std::string &Name)
* if (!EatIfPresent(lltok::kw_thread_local)) return false
ParseOptionalThreadLocal := /*empty.
if (Lex.getKind()==lltok::lparen)
if (!EatIfPresent(lltok::kw_addrspace)) return false
static unsigned parseOptionalLinkageAux (lltok::Kind Kind, bool &HasLinkage)
F (f)
FunctionNumber (functionNumber)
static void resolveFwdRef (ValueInfo *Fwd, ValueInfo &Resolved)
Variables
TLM = GlobalVariable::GeneralDynamicTLSModel
return false
unsigned DefaultAS
static const auto FwdVIRef = (GlobalValueSummaryMapTy::value_type *)-8
Macro Definition Documentation
DECLARE_FIELD
#define DECLARE_FIELD (NAME, TYPE, INIT) TYPE NAME INIT
GET_OR_DISTINCT
#define GET_OR_DISTINCT (CLASS, ARGS) (IsDistinct ? CLASS::getDistinct ARGS : CLASS::get ARGS)
Referenced by FunctionNumber().
HANDLE_SPECIALIZED_MDNODE_LEAF
#define HANDLE_SPECIALIZED_MDNODE_LEAF (CLASS)
Value:
if (Lex.getStrVal() == #CLASS)                                               \
    return Parse##CLASS(N, IsDistinct);
NOP_FIELD
#define NOP_FIELD (NAME, TYPE, INIT)
PARSE_MD_FIELD
#define PARSE_MD_FIELD (NAME, TYPE, DEFAULT)
Value:
if (Lex.getStrVal() == #NAME)                                                \
    return ParseMDField(#NAME, NAME);
PARSE_MD_FIELDS
#define PARSE_MD_FIELDS ()
Value:
VISIT_MD_FIELDS(DECLARE_FIELD, DECLARE_FIELD)                                \
  do {                                                                         \
    LocTy ClosingLoc;                                                          \
    if (ParseMDFieldsImpl([&]() -> bool {                                      \
      VISIT_MD_FIELDS(PARSE_MD_FIELD, PARSE_MD_FIELD)                          \
      return TokError(Twine("invalid field '") + Lex.getStrVal() + "'");       \
    }, ClosingLoc))                                                            \
      return true;                                                             \
    VISIT_MD_FIELDS(NOP_FIELD, REQUIRE_FIELD)                                  \
  } while (false)
Referenced by FunctionNumber().
REQUIRE_FIELD
#define REQUIRE_FIELD (NAME, TYPE, INIT)
Value:
if (!NAME.Seen)                                                              \
    return Error(ClosingLoc, "missing required field '" #NAME "'");
VISIT_MD_FIELDS [1/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(line, LineField,);                                                 \
  OPTIONAL(column, ColumnField, );                                             \
  REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(inlinedAt, MDField, );                                              \
  OPTIONAL(isImplicitCode, MDBoolField, (false));
VISIT_MD_FIELDS [2/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(tag, DwarfTagField,);                                              \
  OPTIONAL(header, MDStringField, );                                           \
  OPTIONAL(operands, MDFieldList, );
VISIT_MD_FIELDS [3/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(count, MDSignedOrMDField, (-1, -1, INT64_MAX, false));              \
  OPTIONAL(lowerBound, MDSignedField, );
VISIT_MD_FIELDS [4/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(name, MDStringField,);                                             \
  REQUIRED(value, MDSignedOrUnsignedField, );                                  \
  OPTIONAL(isUnsigned, MDBoolField, (false));
VISIT_MD_FIELDS [5/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(tag, DwarfTagField, (dwarf::DW_TAG_base_type));                     \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(size, MDUnsignedField, (0, UINT64_MAX));                            \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(encoding, DwarfAttEncodingField, );                                 \
  OPTIONAL(flags, DIFlagField, );
VISIT_MD_FIELDS [6/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(tag, DwarfTagField,);                                              \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(scope, MDField, );                                                  \
  REQUIRED(baseType, MDField, );                                               \
  OPTIONAL(size, MDUnsignedField, (0, UINT64_MAX));                            \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(offset, MDUnsignedField, (0, UINT64_MAX));                          \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(extraData, MDField, );                                              \
  OPTIONAL(dwarfAddressSpace, MDUnsignedField, (UINT32_MAX, UINT32_MAX));
VISIT_MD_FIELDS [7/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(tag, DwarfTagField,);                                              \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(scope, MDField, );                                                  \
  OPTIONAL(baseType, MDField, );                                               \
  OPTIONAL(size, MDUnsignedField, (0, UINT64_MAX));                            \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(offset, MDUnsignedField, (0, UINT64_MAX));                          \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(elements, MDField, );                                               \
  OPTIONAL(runtimeLang, DwarfLangField, );                                     \
  OPTIONAL(vtableHolder, MDField, );                                           \
  OPTIONAL(templateParams, MDField, );                                         \
  OPTIONAL(identifier, MDStringField, );                                       \
  OPTIONAL(discriminator, MDField, );
VISIT_MD_FIELDS [8/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(flags, DIFlagField,);                                              \
  OPTIONAL(cc, DwarfCCField, );                                                \
  REQUIRED(types, MDField, );
VISIT_MD_FIELDS [9/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(filename, MDStringField,);                                         \
  REQUIRED(directory, MDStringField, );                                        \
  OPTIONAL(checksumkind, ChecksumKindField, (DIFile::CSK_MD5));                \
  OPTIONAL(checksum, MDStringField, );                                         \
  OPTIONAL(source, MDStringField, );
VISIT_MD_FIELDS [10/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(language, DwarfLangField,);                                        \
  REQUIRED(file, MDField, (/* AllowNull */ false));                            \
  OPTIONAL(producer, MDStringField, );                                         \
  OPTIONAL(isOptimized, MDBoolField, );                                        \
  OPTIONAL(flags, MDStringField, );                                            \
  OPTIONAL(runtimeVersion, MDUnsignedField, (0, UINT32_MAX));                  \
  OPTIONAL(splitDebugFilename, MDStringField, );                               \
  OPTIONAL(emissionKind, EmissionKindField, );                                 \
  OPTIONAL(enums, MDField, );                                                  \
  OPTIONAL(retainedTypes, MDField, );                                          \
  OPTIONAL(globals, MDField, );                                                \
  OPTIONAL(imports, MDField, );                                                \
  OPTIONAL(macros, MDField, );                                                 \
  OPTIONAL(dwoId, MDUnsignedField, );                                          \
  OPTIONAL(splitDebugInlining, MDBoolField, = true);                           \
  OPTIONAL(debugInfoForProfiling, MDBoolField, = false);                       \
  OPTIONAL(nameTableKind, NameTableKindField, );                               \
  OPTIONAL(debugBaseAddress, MDBoolField, = false);
VISIT_MD_FIELDS [11/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(scope, MDField,);                                                  \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(linkageName, MDStringField, );                                      \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(type, MDField, );                                                   \
  OPTIONAL(isLocal, MDBoolField, );                                            \
  OPTIONAL(isDefinition, MDBoolField, (true));                                 \
  OPTIONAL(scopeLine, LineField, );                                            \
  OPTIONAL(containingType, MDField, );                                         \
  OPTIONAL(virtuality, DwarfVirtualityField, );                                \
  OPTIONAL(virtualIndex, MDUnsignedField, (0, UINT32_MAX));                    \
  OPTIONAL(thisAdjustment, MDSignedField, (0, INT32_MIN, INT32_MAX));          \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(spFlags, DISPFlagField, );                                          \
  OPTIONAL(isOptimized, MDBoolField, );                                        \
  OPTIONAL(unit, MDField, );                                                   \
  OPTIONAL(templateParams, MDField, );                                         \
  OPTIONAL(declaration, MDField, );                                            \
  OPTIONAL(retainedNodes, MDField, );                                          \
  OPTIONAL(thrownTypes, MDField, );
VISIT_MD_FIELDS [12/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(column, ColumnField, );
VISIT_MD_FIELDS [13/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(file, MDField, );                                                   \
  REQUIRED(discriminator, MDUnsignedField, (0, UINT32_MAX));
VISIT_MD_FIELDS [14/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(scope, MDField,);                                                  \
  OPTIONAL(declaration, MDField, );                                            \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );
VISIT_MD_FIELDS [15/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(scope, MDField,);                                                  \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(exportSymbols, MDBoolField, );
VISIT_MD_FIELDS [16/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(type, DwarfMacinfoTypeField,);                                     \
  OPTIONAL(line, LineField, );                                                 \
  REQUIRED(name, MDStringField, );                                             \
  OPTIONAL(value, MDStringField, );
VISIT_MD_FIELDS [17/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(type, DwarfMacinfoTypeField, (dwarf::DW_MACINFO_start_file));       \
  OPTIONAL(line, LineField, );                                                 \
  REQUIRED(file, MDField, );                                                   \
  OPTIONAL(nodes, MDField, );
VISIT_MD_FIELDS [18/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(scope, MDField,);                                                  \
  REQUIRED(name, MDStringField, );                                             \
  OPTIONAL(configMacros, MDStringField, );                                     \
  OPTIONAL(includePath, MDStringField, );                                      \
  OPTIONAL(sysroot, MDStringField, );
VISIT_MD_FIELDS [19/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(name, MDStringField,);                                             \
  REQUIRED(type, MDField, );
VISIT_MD_FIELDS [20/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(tag, DwarfTagField, (dwarf::DW_TAG_template_value_parameter));      \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(type, MDField, );                                                   \
  REQUIRED(value, MDField, );
VISIT_MD_FIELDS [21/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(name, MDStringField, (/* AllowEmpty */ false));                     \
  OPTIONAL(scope, MDField, );                                                  \
  OPTIONAL(linkageName, MDStringField, );                                      \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(type, MDField, );                                                   \
  OPTIONAL(isLocal, MDBoolField, );                                            \
  OPTIONAL(isDefinition, MDBoolField, (true));                                 \
  OPTIONAL(templateParams, MDField, );                                         \
  OPTIONAL(declaration, MDField, );                                            \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));
VISIT_MD_FIELDS [22/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(arg, MDUnsignedField, (0, UINT16_MAX));                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(type, MDField, );                                                   \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));
VISIT_MD_FIELDS [23/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  REQUIRED(name, MDStringField, );                                             \
  REQUIRED(file, MDField, );                                                   \
  REQUIRED(line, LineField, );
VISIT_MD_FIELDS [24/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(var, MDField,);                                                    \
  REQUIRED(expr, MDField, );
VISIT_MD_FIELDS [25/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
OPTIONAL(name, MDStringField,);                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(setter, MDStringField, );                                           \
  OPTIONAL(getter, MDStringField, );                                           \
  OPTIONAL(attributes, MDUnsignedField, (0, UINT32_MAX));                      \
  OPTIONAL(type, MDField, );
VISIT_MD_FIELDS [26/26]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
REQUIRED(tag, DwarfTagField,);                                              \
  REQUIRED(scope, MDField, );                                                  \
  OPTIONAL(entity, MDField, );                                                 \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(name, MDStringField, );
Function Documentation
createGlobalFwdRef()
static GlobalValue* createGlobalFwdRef (Module * M, PointerType * PTy, const std::string & Name) inline static
Definition at line 1364 of file LLParser.cpp.
References llvm::lltok::APSInt, C, llvm::Function::Create(), llvm::dyn_cast(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::GlobalValue::ExternalWeakLinkage, llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::PointerType::getAddressSpace(), llvm::LLLexer::getAPSIntVal(), llvm::Module::getComdatSymbolTable(), llvm::Module::getDataLayout(), llvm::PointerType::getElementType(), llvm::LLLexer::getKind(), llvm::APInt::getLimitedValue(), llvm::Module::getOrInsertComdat(), llvm::Type::getPointerTo(), llvm::DataLayout::getProgramAddressSpace(), llvm::LLLexer::getStrVal(), llvm::Value::getType(), getTypeString(), llvm::Module::getValueSymbolTable(), I, llvm::GlobalValue::InitialExecTLSModel, llvm::Type::isLabelTy(), llvm::APSInt::isSigned(), llvm::lltok::kw_initialexec, llvm::lltok::kw_localdynamic, llvm::lltok::kw_localexec, llvm::lltok::kw_thread_local, llvm::LLLexer::Lex(), llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, llvm::ValueSymbolTable::lookup(), Name, llvm::GlobalValue::NotThreadLocal, llvm::lltok::StringConstant, llvm::T, and TLM.
F()
F (f)
Referenced by llvm::AAEvaluator::AAEvaluator(), llvm::InstrProfRecord::accumulateCounts(), llvm::AAResults::addAADependencyID(), addArgumentAttrs(), addArgumentReturnedAttrs(), llvm::sampleprof::SampleRecord::addCalledTarget(), AddCalls(), addDiscriminators(), addEdge(), llvm::orc::JITTargetMachineBuilder::addFeatures(), llvm::MCAssembler::addFileName(), addIntrinsicToSummary(), llvm::MachineFunction::addLandingPad(), addNoAliasAttrs(), addNonConstUser(), addNonNullAttrs(), addNoRecurseAttrs(), addReadAttrs(), llvm::LoopVectorizationRequirements::addRuntimePointerChecks(), llvm::MachineOperand::addTargetFlag(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::CFLSteensAAResult::alias(), llvm::NVPTXTargetLowering::allowUnsafeFPMath(), allUsersAreInFunction(), llvm::AMDGPULibCalls::AMDGPULibCalls(), llvm::AMDGPULibFunc::AMDGPULibFunc(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::analyzeArguments(), llvm::CodeMetrics::analyzeBasicBlock(), analyzeGlobalAux(), annotateAllFunctions(), annotateDereferenceableBytes(), llvm::LoopVersioning::annotateInstWithNoAlias(), annotateNonNullBasedOnAccess(), appendToGlobalArray(), llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), assertBranchOrSelectConditionHoisted(), llvm::ThreadPool::async(), llvm::TaskQueue::async(), atomicSizeSupported(), llvm::DwarfCFIException::beginFragment(), llvm::WinException::beginFunclet(), llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::BitsToFloat(), llvm::BlockFrequencyPrinterPass::BlockFrequencyPrinterPass(), llvm::slpvectorizer::BoUpSLP::BoUpSLP(), branchMaxOffsets(), llvm::BranchProbabilityPrinterPass::BranchProbabilityPrinterPass(), llvm::buildModuleSummaryIndex(), llvm::lowertypetests::ByteArrayBuilder::ByteArrayBuilder(), calcArraySize(), llvm::BranchProbabilityInfo::calculate(), llvm::BlockFrequencyInfoImpl< llvm::BitTracker >::calculate(), calculateStateNumbersForInvokes(), llvm::call_once(), llvm::Interpreter::callFunction(), llvm::CallGraph::CallGraph(), callingConvSupported(), llvm::callsGCLeafFunction(), callsShareTOCBase(), llvm::EHStreamer::callToNoUnwindFunction(), CanConstantFold(), canCreateThunkFor(), canFoldIVIncExpr(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canonicalizeSaturatedAdd(), canRenameComdat(), canReuseBoundaryAlignFragment(), canThrow(), castToIncrementInst(), CC_RISCV_FastCC(), NoAutoPaddingScope::changeAndComment(), checkFeature(), llvm::MCSubtargetInfo::checkFeatures(), checkFunctionsAttributeConsistency(), checkWFAlloc(), checkWFDealloc(), checkWFRetconPrototype(), llvm::GraphTraits< ValueInfo >::child_begin(), llvm::GraphTraits< ValueInfo >::child_edge_begin(), llvm::GraphTraits< ValueInfo >::child_edge_end(), llvm::GraphTraits< ValueInfo >::child_end(), llvm::classifyEHPersonality(), llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::X86Subtarget::classifyGlobalFunctionReference(), llvm::Function::classof(), llvm::DILexicalBlockFile::classof(), llvm::rdf::DataFlowGraph::DefStack::clear_block(), clearFeature(), llvm::ScalarEvolution::clearFlags(), llvm::RegionBase< RegionTraits< Function > >::clearNodeCache(), llvm::CloneBasicBlock(), llvm::orc::cloneFunctionDecl(), CloneLoopBlocks(), cloneLoopBlocks(), llvm::cloneLoopWithPreheader(), llvm::CloneModule(), llvm::FunctionComparator::cmpConstants(), llvm::CodeViewDebug::CodeViewDebug(), collectComdatMembers(), llvm::sampleprof::SampleProfileReaderExtBinary::collectFuncsFrom(), llvm::sampleprof::SampleProfileReaderCompactBinary::collectFuncsFrom(), collectFunctionUsers(), collectSupportedLoops(), llvm::AMDGPU::Waitcnt::combined(), combineStore(), llvm::MachineDominanceFrontier::compare(), llvm::Hexagon_MC::completeHVXFeatures(), llvm::HexagonBlockRanges::computeDeadMap(), llvm::MCAssembler::computeFragmentSize(), llvm::computeLegalValueVTs(), llvm::ComputeLinearIndex(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::rdf::Liveness::computePhiInfo(), llvm::computeSignatureVTs(), llvm::computeSyntheticCounts(), llvm::ConstantFoldLoadFromConstPtr(), containsConstantInAddMulChain(), llvm::convertToDeclaration(), CouldBecomeSafePoint(), llvm::SanitizerStatReport::create(), llvm::InstrProfSymtab::create(), llvm::createAMDGPUPrintfRuntimeBinding(), createAndInstr(), llvm::createBlockExtractorPass(), llvm::MDBuilder::createCallees(), llvm::createCodeGenPreparePass(), llvm::createConstantPropagationPass(), llvm::createControlHeightReductionLegacyPass(), llvm::createCostModelAnalysisPass(), llvm::MIRParserImpl::createDummyFunction(), createEmptyFunction(), llvm::createFalkorMarkStridedAccessesPass(), llvm::createFileError(), createFree(), llvm::createGCInfoPrinter(), createHWLoopAnalysis(), llvm::createLegacyPMBasicAAResult(), llvm::createLoadStoreVectorizerPass(), llvm::createLoopSimplifyPass(), llvm::createLowerSwitchPass(), createMalloc(), llvm::createMemDepPrinter(), llvm::createMemDerefPrinter(), createMemMoveLoop(), createMemSetLoop(), llvm::createMustBeExecutedContextPrinter(), llvm::createNaryReassociatePass(), llvm::createObjCARCOptPass(), llvm::OpenMPIRBuilder::CreateParallel(), llvm::ARMBaseTargetMachine::createPassConfig(), llvm::createPGOIndirectCallPromotionLegacyPass(), createPHIsForCMOVsInSinkBB(), createPowWithIntegerExponent(), llvm::legacy::FunctionPassManagerImpl::createPrinterPass(), llvm::createSampleProfileLoaderPass(), llvm::createSeparateConstOffsetFromGEPPass(), llvm::createShadowStackGCLoweringPass(), llvm::createSystemZLDCleanupPass(), CreateVarArgHelper(), llvm::createX86RetpolineThunksPass(), llvm::DataDependenceGraph::DataDependenceGraph(), llvm::VerifierSupport::DebugInfoCheckFailed(), deduceFunctionAttributeInRPO(), deleteIfDead(), llvm::MachineModuleInfo::deleteMachineFunctionFor(), DeleteTriviallyDeadInstructions(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::DependenceAnalysisPrinterPass::DependenceAnalysisPrinterPass(), llvm::DependenceInfo::DependenceInfo(), llvm::DependenceInfo::depends(), llvm::HexagonFrameLowering::determineCalleeSaves(), determinePointerReadAttrs(), DisableAllLoopOptsOnLoop(), llvm::TargetOptions::DisableFramePointerElim(), llvm::ModuleSummaryIndex::discoverNodes(), doCallSiteSplitting(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::doesNotThrow(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::AsmPrinter::doFinalization(), llvm::FPPassManager::doFinalization(), llvm::X86AsmPrinter::doInitialization(), llvm::AsmPrinter::doInitialization(), llvm::DominatorTree::DominatorTree(), doPromotion(), llvm::StringRef::drop_until(), llvm::StringRef::drop_while(), llvm::Module::dropAllReferences(), llvm::GVNExpression::Expression::dump(), llvm::PredicateInfo::dump(), llvm::AliasSetTracker::dump(), llvm::BlockFrequencyInfoImplBase::dump(), dumpExampleDependence(), llvm::legacy::FunctionPassManagerImpl::dumpPassStructure(), llvm::ModuleSummaryIndex::dumpSCCs(), dumpScopes(), llvm::DWARFVerifier::DWARFVerifier(), llvm::EarlyCSEPass::EarlyCSEPass(), eliminateAvailableExternally(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), eliminateDeadStores(), eliminateRecursiveTailCall(), eliminateTailRecursion(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::InstrEmitter::EmitDbgLabel(), llvm::AsmPrinter::EmitDebugValue(), llvm::WebAssemblyAsmPrinter::EmitEndOfAsmFile(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::AsmPrinter::EmitFunctionBody(), llvm::WebAssemblyAsmPrinter::EmitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::EmitFunctionBodyStart(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), llvm::MCELFStreamer::EmitIdent(), llvm::PMDataManager::emitInstrCountChangedRemark(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitLabelAtPos(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::AsmPrinter::emitPatchableFunctionEntries(), EmitPersonality(), llvm::AArch64FrameLowering::emitPrologue(), llvm::emitPutChar(), llvm::emitPutS(), emitRangeList(), llvm::AArch64RegisterInfo::emitReservedArgRegCallError(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSignedInt64(), emitUnaryFloatFnCallHelper(), emitXBegin(), llvm::AsmPrinter::emitXRayTable(), enableAllocFrameElim(), llvm::HexagonFrameLowering::enableCalleeSaveSkip(), enableCallSafepoints(), llvm::LazyValueInfo::enableDT(), llvm::HexagonTTIImpl::enableInterleavedAccessVectorization(), llvm::MCSection::end(), llvm::GCModuleInfo::end(), llvm::WinException::endFunclet(), llvm::ARMException::endFunction(), llvm::WinException::endFunction(), llvm::WinCFGuard::endModule(), llvm::WinException::endModule(), ensurePromotedGV(), llvm::EntryExitInstrumenterPass::EntryExitInstrumenterPass(), llvm::enumerate(), eraseDeadBBsAndChildren(), llvm::GlobalsAAResult::FunctionInfo::eraseModRefInfoForGlobal(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::evaluate(), llvm::SparcTargetLowering::expandSelectCC(), explicifyGuards(), llvm::DWARFAbbreviationDeclaration::extract(), llvm::extractCallocCall(), extractSubModule(), llvm::filterDeadComdatFunctions(), Find(), llvm::rdf::IndexedSet< const uint32_t *>::find(), llvm::StringRef::find_if(), llvm::StringRef::find_if_not(), findCalledFunction(), llvm::findDevirtualizableCallsForTypeTest(), llvm::pdb::TpiStream::findFullDeclForForwardRef(), llvm::ExecutionEngine::FindFunctionNamed(), llvm::MCJIT::FindFunctionNamed(), llvm::AnalysisResolver::findImplPass(), llvm::MCJIT::findModuleForSymbol(), findPartitions(), findStrip(), findTRECandidate(), findUnwindDestinations(), llvm::SanitizerStatReport::finish(), fitsInFPType(), FixedPointIntrinsicToOpcode(), llvm::MCSection::flushPendingLabels(), foldCttzCtlz(), foldFPToIntToFP(), foldGuardedRotateToFunnelShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldVecTruncToExtElt(), forBothCUs(), forceRenaming(), llvm::codeview::forEachCodeViewRecord(), forEachUser(), formLCSSAOnAllLoops(), ForwardTemplateReference::ForwardTemplateReference(), llvm::FPPassManager::FPPassManager(), llvm::detail::frexp(), llvm::IRPosition::function(), llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), FunctionNumber(), llvm::FunctionPass::FunctionPass(), generateUnsignedDivisionCode(), llvm::AMDGPUSubtarget::get(), llvm::BlockAddress::get(), llvm::LazyCallGraph::get(), get64BitArgumentXMMs(), llvm::AAResultsWrapperPass::getAAResults(), llvm::InformationCache::getAAResultsForFunction(), llvm::HexagonMCInstrInfo::getAddrMode(), llvm::HexagonInstrInfo::getAddrMode(), GetAEABIUnwindPersonalityName(), llvm::HexagonFrameLowering::getAlignaInstr(), llvm::TargetMachine::getAllocaPointerSize(), llvm::Pass::getAnalysis(), llvm::AnalysisGetter::getAnalysis(), llvm::InformationCache::getAnalysisResultForFunction(), llvm::AMDGPUPerfHintAnalysis::getAnalysisUsage(), llvm::LegacyDivergenceAnalysis::getAnalysisUsage(), llvm::ExternalAAWrapperPass::getAnalysisUsage(), llvm::objcarc::GetARCInstKind(), getArrayElements(), llvm::StringRef::getAsDouble(), llvm::LTOModule::getAsmUndefinedRefs(), llvm::DWARFDie::getAttributeValueAsReferencedDie(), llvm::IRPosition::getAttrs(), llvm::getBestSimplifyQuery(), llvm::LazyMachineBlockFrequencyInfoPass::getBFI(), llvm::BlockFrequencyInfoWrapperPass::getBFI(), getBinOpsForFactorization(), llvm::getBitcodeFileContents(), llvm::MachineBlockFrequencyInfo::getBlockProfileCount(), llvm::LazyBranchProbabilityInfoPass::getBPI(), llvm::BranchProbabilityInfoWrapperPass::getBPI(), llvm::BranchProbabilityInfo::getBranchProbStackProtector(), llvm::vfs::FileSystem::getBufferForFile(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), getCallOpcode(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::BitTracker::MachineEvaluator::getCell(), llvm::HexagonInstrInfo::getCExtOpNum(), llvm::MachineFunctionPass::getClearedProperties(), llvm::ValueEnumerator::getComdats(), getCommonReturnValue(), getComparePred(), llvm::VNCoercion::getConstantMemInstValueForLoad(), llvm::VNCoercion::getConstantStoreValueForLoad(), llvm::ExecutionEngine::getConstantValue(), llvm::LLParser::getContext(), GetCtorAndDtorPriority(), llvm::IRPosition::getCtxI(), llvm::ExecutionEngine::getDataLayout(), llvm::GCOVOptions::getDefault(), GetDeoptBundleOperands(), llvm::DIScope::getDirectory(), llvm::DIVariable::getDirectory(), llvm::DIObjCProperty::getDirectory(), llvm::DominatorTreeWrapperPass::getDomTree(), getElementByteSizeValue(), llvm::Hexagon_MC::GetELFFlags(), llvm::orc::JITDylib::getExecutionSession(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::HexagonMCInstrInfo::getExtendableOp(), llvm::HexagonMCInstrInfo::getExtentAlignment(), llvm::HexagonMCInstrInfo::getExtentBits(), getFilename(), llvm::DIScope::getFilename(), llvm::DIVariable::getFilename(), llvm::DIObjCProperty::getFilename(), getFirstNonAllocaInTheEntryBlock(), llvm::Interpreter::getFirstVarArg(), llvm::MemoryLocation::getForArgument(), llvm::GCFunctionInfo::getFunction(), llvm::CallGraphNode::getFunction(), llvm::DependenceInfo::getFunction(), llvm::LazyCallGraph::Node::getFunction(), llvm::AMDGPULibFunc::getFunction(), llvm::MachineFunction::getFunction(), llvm::BlockFrequencyInfoImpl< llvm::BitTracker >::getFunction(), llvm::GCModuleInfo::getFunctionInfo(), getFunctionReturns(), GetGlobalTypeString(), llvm::X86RegisterInfo::getGPRsForTailCall(), llvm::sys::detail::getHostCPUNameForBPF(), llvm::AMDGPUSubtarget::getImplicitArgNumBytes(), llvm::Attributor::getInfoCache(), llvm::HexagonBlockRanges::InstrIndexMap::getInstr(), llvm::getInstrProfNameSeparator(), llvm::Module::getInstructionCount(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionLatency(), llvm::getIntrinsicForCallSite(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::getIntrinsicID(), llvm::CallBase::getIntrinsicID(), llvm::ARMTargetLowering::getJumpTableEncoding(), llvm::getKnownAlignment(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::LoopInfoWrapperPass::getLoopInfo(), llvm::DWARFDie::getLowAndHighPC(), llvm::LoopAnalysisManagerFunctionProxy::Result<>::getManager(), llvm::GCNSubtarget::getMaxNumSGPRs(), llvm::GCNSubtarget::getMaxNumVGPRs(), llvm::AArch64TargetLowering::getMaxSupportedInterleaveFactor(), llvm::HexagonInstrInfo::getMaxValue(), getMCSymbolForMBB(), llvm::HexagonMCInstrInfo::getMemAccessSize(), llvm::HexagonInstrInfo::getMemAccessSize(), getMemCmpLoad(), llvm::ARMTTIImpl::getMemcpyCost(), getMetadataTypeOrder(), llvm::HexagonInstrInfo::getMinValue(), getMinVisibility(), llvm::GlobalsAAResult::getModRefBehavior(), llvm::MachineModuleInfo::getModule(), getMOVL(), llvm::AMDGPU::SendMsg::getMsgOpId(), getMulHu(), llvm::LazyCallGraph::Node::getName(), llvm::TargetLibraryInfo::getName(), llvm::HexagonMCInstrInfo::getNewValueOp(), llvm::HexagonMCInstrInfo::getNewValueOp2(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::NVPTXTargetMachine::getObjFileLowering(), getOffsetFromIndices(), llvm::InformationCache::getOpcodeInstMapForFunction(), llvm::MipsTargetLowering::getOpndList(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::getOrCreateInitFunction(), llvm::LiveStacks::getOrCreateInterval(), llvm::MachineModuleInfo::getOrCreateMachineFunction(), llvm::CallGraph::getOrInsertFunction(), llvm::Module::getOrInsertFunction(), llvm::AMDGPULibFunc::getOrInsertFunction(), getParentPad(), llvm::ARMAsmPrinter::getPassName(), llvm::RISCVMCExpr::getPCRelHiFixup(), GetPointerOperand(), getPointerOperands(), llvm::ExecutionEngine::getPointerToGlobal(), llvm::orc::OrcMCJITReplacement::getPointerToNamedFunction(), llvm::PostDominatorTreeWrapperPass::getPostDomTree(), llvm::MachineBlockFrequencyInfo::getProfileCountFromFreq(), llvm::InformationCache::getReadOrWriteInstsForFunction(), llvm::vfs::RedirectingFileSystem::getRealPath(), llvm::rdf::Liveness::getRealUses(), getRecipEstimateForFunc(), getRedirectedFileStatus(), llvm::MachineRegionInfoPass::getRegionInfo(), llvm::RegionInfoPass::getRegionInfo(), llvm::Pass::getResolver(), llvm::SCEVAAWrapperPass::getResult(), llvm::StackSafetyInfoWrapperPass::getResult(), getRetComponentType(), llvm::CallBase::getReturnedArgOperand(), llvm::MachineDominatorTree::getRootNode(), llvm::TargetLibraryInfoImpl::getScalarizedFunction(), getSignature(), llvm::DIScope::getSource(), llvm::DIVariable::getSource(), llvm::DIObjCProperty::getSource(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::MipsCCState::getSpecialCallingConvForCallee(), llvm::DependenceInfo::getSplitIteration(), getStringEncoding(), getSubprogram(), llvm::MCSection::getSubsectionInsertionPoint(), llvm::ARCTargetMachine::getSubtargetImpl(), llvm::XCoreTargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::LanaiTargetMachine::getSubtargetImpl(), llvm::SystemZTargetMachine::getSubtargetImpl(), getSuccPad(), llvm::TargetMachine::getTargetIRAnalysis(), llvm::InformationCache::getTargetLibraryInfoForFunction(), llvm::BPFTargetLowering::getTargetNodeName(), llvm::BasicBlock::getTerminatingDeoptimizeCall(), llvm::coverage::InstantiationGroup::getTotalExecutionCount(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::getTreeFactory(), llvm::ImmutableSet< ValT, ValInfo >::Factory::getTreeFactory(), llvm::HexagonMCInstrInfo::getType(), llvm::HexagonInstrInfo::getType(), getUnderlyingObjects(), getUniformBase(), llvm::getUniqueModuleId(), llvm::UnifyFunctionExitNodes::getUnreachableBlock(), llvm::SystemZTTIImpl::getUnrollingPreferences(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getUnrollingPreferences(), llvm::PPCTTIImpl::getUserCost(), llvm::TargetTransformInfo::getUserCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), llvm::BasicBlock::getValueSymbolTable(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::TargetLibraryInfoImpl::getVectorizedFunction(), llvm::MCContext::getWasmSection(), llvm::InjectorIRStrategy::getWeight(), llvm::MCContext::getXCOFFSection(), llvm::lowertypetests::GlobalLayoutBuilder::GlobalLayoutBuilder(), GlobalWasGeneratedByCompiler(), llvm::object::MachOObjectFile::guessLibraryShortName(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::CallLowering::handleAssignments(), llvm::MipsTargetLowering::HandleByVal(), HandleCallsInBlockInlinedThroughInvoke(), handleMustTailForwardedRegisters(), hasAnalyzableMemoryWrite(), hasConflictingReferenceFlags(), llvm::WasmEHFuncInfo::hasEHPadUnwindDest(), HasNestArgument(), llvm::HexagonMCInstrInfo::hasNewValue(), llvm::HexagonMCInstrInfo::hasNewValue2(), llvm::DomTreeUpdater::hasPendingDeletedBB(), hasProfileData(), llvm::CallBase::hasRetAttr(), llvm::HexagonMCInstrInfo::hasTmpDst(), hasUndefContents(), llvm::HotColdSplitting::HotColdSplitting(), inferAllPrototypeAttributes(), inferAttrsFromFunctionBodies(), llvm::inferLibFuncAttributes(), INITIALIZE_PASS(), initializeCounts(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::SlotTracker::initializeIndexIfNeeded(), llvm::Attributor::initializeInformationCache(), llvm::CFLAndersAAWrapperPass::initializePass(), llvm::CFLSteensAAWrapperPass::initializePass(), llvm::PMDataManager::initSizeRemarkInfo(), llvm::InjectTLIMappingsLegacy::InjectTLIMappingsLegacy(), llvm::LegacyInlinerBase::inlineCalls(), llvm::InlineFunction(), llvm::rdf::IndexedSet< const uint32_t *>::insert(), llvm::MCObjectStreamer::insert(), llvm::slpvectorizer::BoUpSLP::BlockScheduling::ReadyList::insert(), llvm::HexagonFrameLowering::insertCFIInstructions(), insertCSRRestores(), insertIfNamed(), insertParsePoints(), InsertRootInitializers(), insertSinCosCall(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), insertUniqueBackedgeBlock(), llvm::BTFDebug::InstLower(), llvm::InstrProfiling::InstrProfiling(), InstrumentAllFunctions(), instrumentMaskedLoadOrStore(), llvm::InternalizePass::internalizeModule(), intersect(), llvm::TypeBasedAAResult::invalidate(), llvm::objcarc::ObjCARCAAResult::invalidate(), llvm::ProfileSummaryInfo::invalidate(), llvm::LazyValueInfo::invalidate(), llvm::DependenceInfo::invalidate(), llvm::MemoryDependenceResults::invalidate(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), llvm::MemorySSAAnalysis::Result::invalidate(), invokeFunctionPass(), llvm::HexagonMCInstrInfo::isAccumulator(), llvm::HexagonInstrInfo::isAccumulator(), llvm::HexagonInstrInfo::isAddrModeWithOffset(), isArgPassedInSGPR(), llvm::AMDGPU::isArgPassedInSGPR(), llvm::isAssumeLikeIntrinsic(), isBlockValidForExtraction(), isBswapIntrinsicCall(), isCallableFunction(), isCalleeLoad(), isCallPromotable(), llvm::SITargetLowering::isCanonicalized(), llvm::HexagonMCInstrInfo::isCofMax1(), llvm::HexagonMCInstrInfo::isCofRelax1(), llvm::HexagonMCInstrInfo::isCofRelax2(), isCompareZero(), llvm::HexagonInstrInfo::isConstExtended(), isContractable(), llvm::HexagonMCInstrInfo::isCVINew(), llvm::LazyCallGraph::Node::isDead(), isDebug(), llvm::GlobalValue::isDeclaration(), isDINode(), isDynamicConstant(), llvm::CodeExtractor::isEligible(), isEligibleForMerging(), llvm::DenseMapInfo< VTableSlotSummary >::isEqual(), llvm::DenseMapInfo< const Expression * >::isEqual(), isExecuteOnlyFunction(), llvm::HexagonMCInstrInfo::isExtendable(), llvm::HexagonInstrInfo::isExtendable(), llvm::HexagonMCInstrInfo::isExtended(), llvm::HexagonInstrInfo::isExtended(), llvm::HexagonMCInstrInfo::isExtentSigned(), llvm::HexagonMCInstrInfo::isFloat(), llvm::HexagonInstrInfo::isFloat(), isFuncOrderCorrect(), llvm::RISCVInstrInfo::isFunctionSafeToOutlineFrom(), llvm::AArch64InstrInfo::isFunctionSafeToOutlineFrom(), llvm::X86InstrInfo::isFunctionSafeToOutlineFrom(), llvm::TargetLibraryInfoImpl::isFunctionVectorizable(), isGEPKnownNonNull(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), isIndirectBrTarget(), IsInRanges(), llvm::isInTailCallPosition(), IsInterestingCmp(), isInterestingPointerSubtraction(), isKnownTypeIdMember(), isLibCallInTailPosition(), llvm::ARMBaseTargetMachine::isLittleEndian(), isLoadConditional(), llvm::MachineLoopInfo::isLoopHeader(), llvm::VETargetMachine::isMachineVerifierClean(), IsMasked(), llvm::GlobalValue::isMaterializable(), llvm::isMathLibCallNoop(), isMustExecuteIn(), llvm::HexagonMCInstrInfo::isNewValue(), llvm::HexagonInstrInfo::isNewValue(), llvm::HexagonInstrInfo::isNewValueStore(), llvm::isNoOpWithoutInvoke(), isNotExclusivelyConstantDerived(), isOnlyReachableViaThisEdge(), llvm::HexagonInstrInfo::isOperandExtended(), isOptimizingForSize(), isOptSize(), isPointerValueDeadOnEntryToFunction(), isPossibleIndirectCallTarget(), llvm::ARCInstrInfo::isPostIncrement(), llvm::HexagonInstrInfo::isPredicated(), llvm::HexagonMCInstrInfo::isPredicated(), llvm::HexagonMCInstrInfo::isPredicatedNew(), llvm::HexagonInstrInfo::isPredicatedNew(), llvm::HexagonMCInstrInfo::isPredicatedTrue(), llvm::HexagonInstrInfo::isPredicatedTrue(), llvm::HexagonMCInstrInfo::isPredicateLate(), llvm::HexagonInstrInfo::isPredicateLate(), llvm::HexagonInstrInfo::isPredictedTaken(), llvm::ARCInstrInfo::isPreIncrement(), llvm::AArch64TargetLowering::isProfitableToHoist(), isPromotedResultSafe(), isReassociableOp(), llvm::RecurrenceDescriptor::isReductionPHI(), isReInterleaveMask(), llvm::HexagonMCInstrInfo::isRestrictNoSlot1Store(), llvm::HexagonMCInstrInfo::isRestrictSlot1AOK(), isSecondInstructionInSequence(), llvm::HexagonMCInstrInfo::isSolo(), llvm::HexagonInstrInfo::isSolo(), llvm::HexagonMCInstrInfo::isSoloAX(), isSortedByValueNo(), llvm::isStatepoint(), llvm::TargetFrameLowering::isSupportedStackID(), isSupportedType(), isUnconditionalBranch(), llvm::LoopVectorizationLegality::isUniform(), llvm::AMDGPULibCalls::isUnsafeMath(), llvm::HexagonInstrInfo::isVecALU(), isWrapperOnlyCall(), iterativelyFlattenCFG(), jumpToValueSymbolTable(), llvm::MCAsmLayout::layoutFragment(), llvm::LazyCallGraph::LazyCallGraph(), LLVMAddAttributeAtIndex(), LLVMCreateMCJITCompilerForModule(), LLVMFindFunction(), LLVMGetAttributeCountAtIndex(), LLVMGetAttributesAtIndex(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), LLVMGetGC(), LLVMGetHostCPUFeatures(), LLVMGetIntrinsicID(), LLVMRemoveEnumAttributeAtIndex(), LLVMRemoveStringAttributeAtIndex(), LLVMSetGC(), LLVMViewFunctionCFG(), LLVMViewFunctionCFGOnly(), llvm::BitTracker::lookup(), lookupFunction(), llvm::TargetIntrinsicInfo::lookupName(), llvm::LoopPrinterPass::LoopPrinterPass(), llvm::LoopUnrollAndJamPass::LoopUnrollAndJamPass(), llvm::LoopUnrollPass::LoopUnrollPass(), llvm::X86CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::CallLowering::lowerCall(), llvm::LowerConstantIntrinsicsPass::LowerConstantIntrinsicsPass(), llvm::NVPTXTargetLowering::LowerFormalArguments(), LowerFPToInt(), lowerGuardIntrinsic(), llvm::ARMTargetLowering::lowerInterleavedStore(), LowerInterruptReturn(), lowerIntrinsics(), lowerLoadRelative(), llvm::AMDGPUTargetLowering::LowerOperation(), llvm::X86CallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::MipsCallLowering::lowerReturn(), lowerSubFn(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerWidenableCondition(), llvm::PatternMatch::m_Br(), llvm::make_scope_exit(), llvm::LTOModule::makeBuffer(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), llvm::rdf::RegisterAggr::makeRegRef(), llvm::orc::makeStub(), makeVisible(), llvm::Optional< uint64_t >::map(), llvm::map_range(), mapBinOpcode(), MarkBlocksLiveIn(), NodeArrayNode::match(), DotSuffix::match(), VendorExtQualType::match(), QualType::match(), ConversionOperatorType::match(), PostfixQualifiedType::match(), NameType::match(), ElaboratedTypeSpefType::match(), AbiTagAttr::match(), EnableIfAttr::match(), ObjCProtoName::match(), PointerType::match(), ReferenceType::match(), PointerToMemberType::match(), ArrayType::match(), FunctionType::match(), NoexceptSpec::match(), DynamicExceptionSpec::match(), FunctionEncoding::match(), LiteralOperator::match(), SpecialName::match(), CtorVtableSpecialName::match(), NestedName::match(), LocalName::match(), QualifiedName::match(), VectorType::match(), PixelVectorType::match(), SyntheticTemplateParamName::match(), TypeTemplateParamDecl::match(), NonTypeTemplateParamDecl::match(), TemplateTemplateParamDecl::match(), TemplateParamPackDecl::match(), ParameterPack::match(), TemplateArgumentPack::match(), ParameterPackExpansion::match(), TemplateArgs::match(), NameWithTemplateArgs::match(), GlobalQualifiedName::match(), StdQualifiedName::match(), ExpandedSpecialSubstitution::match(), SpecialSubstitution::match(), CtorDtorName::match(), DtorName::match(), UnnamedTypeName::match(), ClosureTypeName::match(), StructuredBindingName::match(), BinaryExpr::match(), ArraySubscriptExpr::match(), PostfixExpr::match(), ConditionalExpr::match(), MemberExpr::match(), EnclosingExpr::match(), CastExpr::match(), SizeofParamPackExpr::match(), llvm::PatternMatch::IntrinsicID_match::match(), CallExpr::match(), NewExpr::match(), DeleteExpr::match(), PrefixExpr::match(), FunctionParam::match(), ConversionExpr::match(), InitListExpr::match(), BracedExpr::match(), BracedRangeExpr::match(), FoldExpr::match(), ThrowExpr::match(), UUIDOfExpr::match(), BoolExpr::match(), StringLiteral::match(), LambdaExpr::match(), IntegerCastExpr::match(), IntegerLiteral::match(), FloatLiteralImpl< Float >::match(), matchPair(), matchRotate(), matchSVEPredicateVectorRegName(), llvm::HexagonInstrInfo::mayBeCurLoad(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), llvm::HexagonInstrInfo::mayBeNewStore(), mayTailCallThisCC(), llvm::WebAssembly::mayThrow(), mayUsePostIncMode(), llvm::BranchFolder::MBFIWrapper::MBFIWrapper(), llvm::MCAsmLayout::MCAsmLayout(), llvm::MemoryDependenceAnalysis::MemoryDependenceAnalysis(), llvm::MemoryDependenceResults::MemoryDependenceResults(), llvm::MemorySanitizerPass::MemorySanitizerPass(), llvm::MergedLoadStoreMotionPass::MergedLoadStoreMotionPass(), moveUp(), mustPreserveGV(), llvm::mustSuppressSpeculation(), llvm::IRMutationStrategy::mutate(), llvm::LibCallsShrinkWrapPass::name(), llvm::InstCombinePass::name(), needPadding(), needsFP(), needsRuntimeRegistrationOfSectionRange(), llvm::TargetRegisterInfo::needsStackRealignment(), needsWinCFI(), Node::Node(), node_eq(), normalizePBQPSpillWeight(), llvm::vfs::RedirectingFileSystem::openFileForRead(), llvm::sys::fs::openNativeFileForReadWrite(), operator new(), llvm::orc::BlockFreqQuery::operator()(), llvm::orc::CtorDtorIterator::operator*(), llvm::mapped_iterator< ItTy, FuncTy, FuncReturnTy >::operator*(), false::operator<<(), llvm::operator<<(), llvm::RegionInfo::operator=(), llvm::LoopInfo::operator=(), llvm::TargetIRAnalysis::operator=(), llvm::CallGraphWrapperPass::operator[](), optimizeDivRem(), llvm::optimizeGlobalCtorsList(), orderModule(), packCmovGroup(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::paramHasAttr(), llvm::CallBase::paramHasAttr(), parseCHRFilterFiles(), llvm::ARM::parseFPU(), llvm::MetadataLoader::parseFunctionMetadata(), parseGlobalValue(), llvm::MIRParserImpl::parseMachineFunction(), parseOptionalLinkageAux(), llvm::peelLoop(), PGOMemOPSizeOptImpl(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::PMDataManager::PMDataManager(), llvm::AMDGPUAAResult::pointsToConstantMemory(), llvm::LazyCallGraph::Node::populate(), llvm::PostDominatorTree::PostDominatorTree(), llvm::PPCTTIImpl::PPCTTIImpl(), llvm::PredicateInfoPrinterPass::PredicateInfoPrinterPass(), predictUseListOrder(), llvm::HexagonMCInstrInfo::prefersSlot3(), prepareForSplit(), llvm::Trace::print(), llvm::ValueEnumerator::print(), llvm::SubtargetFeatures::print(), llvm::PredicateInfo::print(), llvm::Value::print(), llvm::MachineBasicBlock::print(), llvm::MachineInstr::print(), PrintCFIEscape(), printIRBlockReference(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), llvm::DebugInfoFinder::processModule(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), promoteArguments(), llvm::pgo::promoteIndirectCall(), promoteIndirectCalls(), promoteToConstantPool(), PushArgMD(), queryCallee(), raise_relocation_error(), llvm::GCOVFunction::readGCNO(), llvm::object::readIRSymtab(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::AsmPrinter::recordSled(), llvm::Interpreter::Register(), llvm::AssumptionCache::registerAssumption(), llvm::DemandedBitsWrapperPass::releaseMemory(), llvm::LazyCallGraph::removeDeadFunction(), llvm::LegacyInlinerBase::removeDeadFunctions(), llvm::LazyCallGraph::removeEdge(), llvm::CallGraph::removeFunctionFromModule(), removeTailCallAttribute(), removeUseSoftFloat(), llvm::LegacyDivergenceAnalysis::removeValue(), llvm::MCContext::renameELFSection(), llvm::MemorySSA::renamePass(), replaceAllPrepares(), llvm::ARMTargetLowering::ReplaceNodeResults(), replaceUnaryCall(), llvm::MCELFStreamer::reset(), llvm::rdf::Liveness::resetKills(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::CallLowering::resultsCompatible(), RetagMask(), llvm::sys::RetryAfterSignal(), llvm::SyntheticCountsPropagation::run(), llvm::LoadStoreVectorizerPass::run(), llvm::PoisonCheckingPass::run(), llvm::ExpandReductionsPass::run(), llvm::CallSiteSplittingPass::run(), llvm::BoundsCheckingPass::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::MergeICmpsPass::run(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::CGProfilePass::run(), llvm::LibCallsShrinkWrapPass::run(), llvm::InjectTLIMappings::run(), llvm::IRCEPass::run(), llvm::LowerAtomicPass::run(), llvm::ForceFunctionAttrsPass::run(), llvm::LoopAccessInfoPrinterPass::run(), llvm::SinkingPass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::LoopFusePass::run(), llvm::DivRemPairsPass::run(), llvm::BreakCriticalEdgesPass::run(), llvm::PromotePass::run(), llvm::LoopUnrollAndJamPass::run(), llvm::NewGVNPass::run(), llvm::InferFunctionAttrsPass::run(), llvm::PartialInlinerPass::run(), llvm::LoopPredicationPass::run(), llvm::LoopRotatePass::run(), llvm::ScalarizerPass::run(), llvm::ControlHeightReductionPass::run(), llvm::BDCEPass::run(), llvm::Float2IntPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::IndVarSimplifyPass::run(), llvm::GlobalOptPass::run(), llvm::LoopDistributePass::run(), llvm::GuardWideningPass::run(), llvm::LoopLoadEliminationPass::run(), llvm::LoopIdiomRecognizePass::run(), llvm::ArgumentPromotionPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::AggressiveInstCombinePass::run(), llvm::AlignmentFromAssumptionsPass::run(), llvm::WarnMissedTransformationsPass::run(), llvm::DSEPass::run(), llvm::RewriteStatepointsForGC::run(), llvm::GlobalDCEPass::run(), llvm::LowerExpectIntrinsicPass::run(), llvm::CFGViewerPass::run(), llvm::UnreachableBlockElimPass::run(), llvm::IPSCCPPass::run(), llvm::SampleProfileLoaderPass::run(), llvm::ADCEPass::run(), llvm::rdf::CopyPropagation::run(), llvm::EarlyCSEPass::run(), llvm::LoopSinkPass::run(), llvm::ThinLTOBitcodeWriterPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::AlwaysInlinerPass::run(), llvm::InstCombinePass::run(), llvm::InstSimplifyPass::run(), llvm::LowerConstantIntrinsicsPass::run(), llvm::SCCPPass::run(), llvm::LCSSAPass::run(), llvm::PGOInstrumentationGenCreateVar::run(), llvm::InstrProfiling::run(), llvm::SafepointIRVerifierPass::run(), llvm::LoopFullUnrollPass::run(), llvm::SimplifyCFGPass::run(), llvm::MemCpyOptPass::run(), llvm::PGOInstrumentationGen::run(), llvm::ModuleSummaryIndexAnalysis::run(), llvm::MergedLoadStoreMotionPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::LoopSimplifyPass::run(), llvm::StackSafetyPrinterPass::run(), llvm::LICMPass::run(), llvm::AAEvaluator::run(), llvm::TailCallElimPass::run(), llvm::HotColdSplittingPass::run(), llvm::PGOInstrumentationUse::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::PostDominatorTreePrinterPass::run(), llvm::GVN::run(), llvm::SpeculativeExecutionPass::run(), llvm::SLPVectorizerPass::run(), llvm::PrintModulePass::run(), llvm::StackSafetyGlobalAnalysis::run(), llvm::PGOMemOPSizeOpt::run(), llvm::PrintFunctionPass::run(), llvm::CFLAndersAA::run(), llvm::JumpThreadingPass::run(), llvm::InlinerPass::run(), llvm::AddressSanitizerPass::run(), llvm::NaryReassociatePass::run(), llvm::SpeculateAroundPHIsPass::run(), llvm::DemandedBitsAnalysis::run(), llvm::CFLSteensAA::run(), llvm::ConstantHoistingPass::run(), llvm::DemandedBitsPrinterPass::run(), llvm::BlockFrequencyPrinterPass::run(), llvm::LazyValueAnalysis::run(), llvm::GlobalsAA::run(), llvm::LoopUnrollPass::run(), llvm::VerifierPass::run(), llvm::LoopVectorizePass::run(), llvm::AssumptionPrinterPass::run(), llvm::ProfileSummaryPrinterPass::run(), llvm::DominanceFrontierPrinterPass::run(), llvm::BranchProbabilityPrinterPass::run(), llvm::WholeProgramDevirtPass::run(), llvm::DominatorTreePrinterPass::run(), llvm::DominatorTreeVerifierPass::run(), llvm::FunctionToLoopPassAdaptor< LoopPassT >::run(), llvm::LoopCachePrinterPass::run(), llvm::PredicateInfoPrinterPass::run(), llvm::PredicateInfoVerifierPass::run(), llvm::GVNHoistPass::run(), llvm::DDGAnalysis::run(), llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run(), llvm::MemoryDependenceAnalysis::run(), llvm::DevirtSCCRepeatedPass< PassT >::run(), llvm::Attributor::run(), llvm::DependenceAnalysis::run(), llvm::MemorySSAAnalysis::run(), llvm::MemorySSAPrinterPass::run(), llvm::MemorySSAVerifierPass::run(), llvm::RegionInfoAnalysis::run(), llvm::RegionInfoPrinterPass::run(), llvm::RegionInfoVerifierPass::run(), llvm::AAManager::run(), llvm::LoopPrinterPass::run(), llvm::LoopVerifierPass::run(), llvm::LazyCallGraphAnalysis::run(), llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::run(), llvm::TargetIRAnalysis::run(), runAttributorOnModule(), runCVP(), llvm::MemCpyOptPass::runImpl(), llvm::SLPVectorizerPass::runImpl(), runImpl(), llvm::LegacyDivergenceAnalysis::runOnFunction(), llvm::UnifyFunctionExitNodes::runOnFunction(), runOnFunction(), llvm::LazyBranchProbabilityInfoPass::runOnFunction(), llvm::BasicAAWrapperPass::runOnFunction(), llvm::PredicateInfoPrinterLegacyPass::runOnFunction(), llvm::LazyMachineBlockFrequencyInfoPass::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::RegBankSelect::runOnMachineFunction(), llvm::ModuleSummaryIndexWrapperPass::runOnModule(), llvm::StackSafetyGlobalInfoWrapperPass::runOnModule(), llvm::GlobalsAAWrapperPass::runOnModule(), llvm::FPPassManager::runOnModule(), llvm::AMDGPUPerfHintAnalysis::runOnSCC(), llvm::orc::ExecutionSession::runSessionLocked(), llvm::MCJIT::runStaticConstructorsDestructors(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::SafepointIRVerifierPass::SafepointIRVerifierPass(), scalarizeMaskedCompressStore(), llvm::TargetLoweringObjectFile::SectionForGlobal(), selectELFSectionForGlobal(), selectI64Imm(), llvm::FastISel::selectInstruction(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), selectJumpTableArmEncoding(), selectWasmSectionForGlobal(), llvm::rdf::NodeAttrs::set_flags(), llvm::TargetLibraryInfoImpl::setAvailableWithName(), llvm::BranchFolder::MBFIWrapper::setBlockFreq(), setCannotDuplicate(), llvm::WebAssemblyFunctionInfo::setCFGStackified(), llvm::IRBuilderBase::setConstrainedFPFunctionAttr(), llvm::pdb::DbiStreamBuilder::setFlags(), llvm::MCSectionELF::setFlags(), llvm::MCInst::setFlags(), llvm::AMDGPUArgumentUsageInfo::setFuncArgInfo(), llvm::Value::setName(), llvm::MCJIT::setProcessAllSections(), llvm::setProfMetadata(), llvm::MachineOperand::setTargetFlags(), llvm::TargetLibraryInfo::setUnavailable(), llvm::AsmPrinter::SetupMachineFunction(), llvm::coro::Shape::Shape(), llvm::TargetMachine::shouldAssumeDSOLocal(), llvm::ARMTTIImpl::shouldExpandReduction(), shouldFixMainFunction(), llvm::shouldFuncOptimizeForSizeImpl(), llvm::shouldOptimizeForSize(), llvm::shouldOptimizeForSizeImpl(), ShouldSignReturnAddress(), ShouldSignWithAKey(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), SimplifyBSwap(), llvm::SimplifyCall(), llvm::SimplifyCFGPass::SimplifyCFGPass(), simplifyIntrinsic(), llvm::simplifyLoop(), llvm::sinkRegion(), sizeOfSCEV(), llvm::LoopPass::skipLoop(), llvm::RegionPass::skipRegion(), llvm::parallel::detail::TaskGroup::spawn(), llvm::SplitCriticalEdge(), llvm::DISubprogram::splitFlags(), llvm::SplitModule(), splitRetconCoroutine(), llvm::StackSafetyPrinterPass::StackSafetyPrinterPass(), stashEntryDbgValues(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), false::Chain::str(), stripDeadPrototypes(), llvm::StripDebugInfo(), StripSymbolNames(), stripTBAA(), sumEdgeCount(), swapAntiDependences(), llvm::StringRef::take_until(), llvm::StringRef::take_while(), llvm::TargetLibraryAnalysis::TargetLibraryAnalysis(), llvm::TargetLibraryInfo::TargetLibraryInfo(), llvm::TBAAVerifier::TBAAVerifier(), tieOpsIfNeeded(), transformCallee(), llvm::TruncInstCombine::TruncInstCombine(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), tryToElideArgumentCopy(), tryToFoldACImm(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), TypeSizeToSizeIndex(), unifyBitWidth(), unifyReturnBlockSet(), unpackRegsToOrigType(), llvm::AssumptionCache::unregisterAssumption(), llvm::OrcCBindingsStack::UnregisterJITEventListener(), llvm::UnrollRuntimeLoopRemainder(), unwrapLoop(), llvm::coro::updateCallGraph(), UpdateCallGraphAfterInlining(), updateNewSCCFunctionAnalyses(), UpdatePDTWorklist(), updatePredecessorProfileMetadata(), llvm::RegionInfoBase< RegionTraits< Function > >::updateRegionTree(), llvm::UpgradeIntrinsicCall(), llvm::NVPTXTargetLowering::useF32FTZ(), useFuncSeen(), llvm::HexagonSubtarget::usePredicatedCalls(), llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::validate(), llvm::ValueEnumerator::ValueEnumerator(), valueHasFloatPrecision(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::CodeExtractor::verifyAssumptionCache(), viewRegionInfo(), llvm::InstCombiner::visitAllocSite(), llvm::Interpreter::visitCallSite(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitInstruction(), llvm::DWARFDebugLoclists::visitLocationList(), llvm::WarnMissedTransformationsPass::WarnMissedTransformationsPass(), WarnSize(), WindowsRequiresStackProbe(), windowsRequiresStackProbe(), llvm::orc::ThreadSafeModule::withModuleDo(), llvm::orc::JITDylib::withSearchOrderDo(), wrapConstantAsMetadata(), writeCFGToDotFile(), writeContent(), writeIdentificationBlock(), llvm::MCAssembler::writeSectionData(), writeTypeIdCompatibleVtableSummaryRecord(), llvm::CallGraph::~CallGraph(), llvm::Evaluator::~Evaluator(), llvm::LazyValueInfoWrapperPass::~LazyValueInfoWrapperPass(), and llvm::MMIAddrLabelMap::~MMIAddrLabelMap().
FunctionNumber()
FunctionNumber (functionNumber)
Definition at line 2836 of file LLParser.cpp.
References llvm::MCID::Add, llvm::FastMathFlags::any(), llvm::lltok::APFloat, llvm::ValID::APFloatVal, llvm::GlobalValue::AppendingLinkage, llvm::lltok::APSInt, llvm::ValID::APSIntVal, llvm::SelectInst::areInvalidOperands(), llvm::Function::arg_begin(), llvm::Function::args(), assert(), attributes, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::GlobalValue::AvailableExternallyLinkage, B, llvm::lltok::bar, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::DICompositeType::buildODRType(), C, llvm::CastInst::castIsValid(), llvm::lltok::ChecksumKind, llvm::lltok::ComdatVar, llvm::lltok::comma, llvm::GlobalValue::CommonLinkage, llvm::ValID::ConstantStructElts, llvm::ValID::ConstantVal, llvm::AttrBuilder::contains(), Context, llvm::APFloat::convert(), llvm::count(), llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::ReturnInst::Create(), llvm::BranchInst::Create(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::Default, llvm::Value::deleteValue(), llvm::lltok::DIFlag, llvm::lltok::DISPFlag, llvm::dwarf::DW_ATE_hi_user, llvm::dwarf::DW_CC_hi_user, llvm::dwarf::DW_LANG_hi_user, llvm::dwarf::DW_MACINFO_invalid, llvm::dwarf::DW_MACINFO_vendor_ext, llvm::dwarf::DW_TAG_hi_user, llvm::dwarf::DW_TAG_invalid, llvm::dwarf::DW_VIRTUALITY_invalid, llvm::dwarf::DW_VIRTUALITY_max, llvm::lltok::DwarfAttEncoding, llvm::lltok::DwarfCC, llvm::lltok::DwarfLang, llvm::lltok::DwarfMacinfo, llvm::lltok::DwarfOp, llvm::lltok::DwarfTag, llvm::lltok::DwarfVirtuality, llvm::numbers::e, llvm::lltok::EmissionKind, llvm::Optional< T >::emplace(), llvm::SmallVectorBase::empty(), llvm::StringRef::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::lltok::Eof, llvm::lltok::equal, llvm::GlobalValue::eraseFromParent(), llvm::lltok::exclaim, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::APSInt::extOrTrunc(), F(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, file, llvm::sys::path::filename(), llvm::ValID::FTy, llvm::InlineAsm::get(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::MetadataAsValue::get(), llvm::AttributeSet::get(), llvm::ConstantFP::get(), llvm::AttributeList::get(), llvm::ValueAsMetadata::get(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::ConstantPointerNull::get(), llvm::PointerType::get(), llvm::MDString::get(), llvm::BlockAddress::get(), llvm::ConstantExpr::get(), llvm::MDTuple::get(), llvm::UndefValue::get(), GET_OR_DISTINCT, llvm::GlobalValue::getAddressSpace(), llvm::AttrBuilder::getAlignment(), llvm::LLLexer::getAPFloatVal(), llvm::LLLexer::getAPSIntVal(), llvm::dwarf::getAttributeEncoding(), llvm::dwarf::getCallingConvention(), llvm::ConstantExpr::getCast(), llvm::DIFile::getChecksumKind(), llvm::MDNode::getDistinct(), llvm::MDTuple::getDistinct(), llvm::DICompileUnit::getEmissionKind(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), llvm::DINode::getFlag(), llvm::DISubprogram::getFlag(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::GetElementPtrInst::getIndexedType(), llvm::ExtractValueInst::getIndexedType(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), llvm::BasicBlock::getInstList(), llvm::Type::getInt1Ty(), llvm::Type::getInt8Ty(), llvm::LLLexer::getKind(), llvm::Type::getLabelTy(), llvm::dwarf::getLanguage(), llvm::LLLexer::getLoc(), llvm::dwarf::getMacinfo(), llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::DICompileUnit::getNameTableKind(), llvm::Constant::getNullValue(), llvm::dwarf::getOperationEncoding(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarType(), llvm::ConstantExpr::getSelect(), llvm::APFloat::getSemantics(), llvm::ConstantExpr::getShuffleVector(), llvm::ConstantDataArray::getString(), llvm::LLLexer::getStrVal(), llvm::dwarf::getTag(), llvm::ConstantInt::getTrue(), getType(), llvm::Value::getType(), llvm::GlobalValue::getType(), getTypeString(), llvm::LLLexer::getUIntVal(), llvm::Function::getValueSymbolTable(), llvm::Type::getVectorNumElements(), llvm::dwarf::getVirtuality(), llvm::lltok::GlobalID, globals, llvm::lltok::GlobalVar, llvm::lltok::greater, llvm::AttrBuilder::hasAlignmentAttr(), llvm::AttributeList::hasAttribute(), llvm::Value::hasName(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEsingle(), INT64_MAX, INT64_MIN, llvm::GlobalValue::InternalLinkage, llvm::Type::isAggregateType(), llvm::Type::isArrayTy(), llvm::GlobalValue::isDeclaration(), llvm::PossiblyExactOperator::IsExact, llvm::Type::isFirstClassType(), llvm::Type::isFloatingPointTy(), llvm::Type::isFloatTy(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isFunctionTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isLabelTy(), llvm::Type::isMetadataTy(), llvm::Type::isPointerTy(), llvm::Type::isPtrOrPtrVectorTy(), llvm::Type::isSized(), llvm::Instruction::isTerminator(), llvm::Type::isTokenTy(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), llvm::FunctionType::isValidReturnType(), isValidVisibilityForLinkage(), llvm::ConstantFP::isValueValidForType(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::ValID::Kind, llvm::lltok::kw_add, llvm::lltok::kw_addrspacecast, llvm::lltok::kw_alignstack, llvm::lltok::kw_alloca, llvm::lltok::kw_and, llvm::lltok::kw_ashr, llvm::lltok::kw_asm, llvm::lltok::kw_atomicrmw, llvm::lltok::kw_bitcast, llvm::lltok::kw_blockaddress, llvm::lltok::kw_br, llvm::lltok::kw_c, llvm::lltok::kw_call, llvm::lltok::kw_callbr, llvm::lltok::kw_catchpad, llvm::lltok::kw_catchret, llvm::lltok::kw_catchswitch, llvm::lltok::kw_cleanuppad, llvm::lltok::kw_cleanupret, llvm::lltok::kw_cmpxchg, llvm::lltok::kw_comdat, llvm::lltok::kw_eq, llvm::lltok::kw_exact, llvm::lltok::kw_extractelement, llvm::lltok::kw_extractvalue, llvm::lltok::kw_fadd, llvm::lltok::kw_false, llvm::lltok::kw_fcmp, llvm::lltok::kw_fdiv, llvm::lltok::kw_fence, llvm::lltok::kw_fmul, llvm::lltok::kw_fneg, llvm::lltok::kw_fpext, llvm::lltok::kw_fptosi, llvm::lltok::kw_fptoui, llvm::lltok::kw_fptrunc, llvm::lltok::kw_freeze, llvm::lltok::kw_frem, llvm::lltok::kw_fsub, llvm::lltok::kw_gc, llvm::lltok::kw_getelementptr, llvm::lltok::kw_icmp, llvm::lltok::kw_inbounds, llvm::lltok::kw_indirectbr, llvm::lltok::kw_inrange, llvm::lltok::kw_insertelement, llvm::lltok::kw_insertvalue, llvm::lltok::kw_inteldialect, llvm::lltok::kw_inttoptr, llvm::lltok::kw_invoke, llvm::lltok::kw_landingpad, llvm::lltok::kw_load, llvm::lltok::kw_lshr, llvm::lltok::kw_mul, llvm::lltok::kw_musttail, llvm::lltok::kw_ne, llvm::lltok::kw_none, llvm::lltok::kw_notail, llvm::lltok::kw_nsw, llvm::lltok::kw_null, llvm::lltok::kw_nuw, llvm::lltok::kw_oeq, llvm::lltok::kw_oge, llvm::lltok::kw_ogt, llvm::lltok::kw_ole, llvm::lltok::kw_olt, llvm::lltok::kw_one, llvm::lltok::kw_or, llvm::lltok::kw_ord, llvm::lltok::kw_partition, llvm::lltok::kw_personality, llvm::lltok::kw_phi, llvm::lltok::kw_prefix, llvm::lltok::kw_prologue, llvm::lltok::kw_ptrtoint, llvm::lltok::kw_resume, llvm::lltok::kw_ret, llvm::lltok::kw_sdiv, llvm::lltok::kw_section, llvm::lltok::kw_select, llvm::lltok::kw_sext, llvm::lltok::kw_sge, llvm::lltok::kw_sgt, llvm::lltok::kw_shl, llvm::lltok::kw_shufflevector, llvm::lltok::kw_sideeffect, llvm::lltok::kw_sitofp, llvm::lltok::kw_sle, llvm::lltok::kw_slt, llvm::lltok::kw_srem, llvm::lltok::kw_store, llvm::lltok::kw_sub, llvm::lltok::kw_switch, llvm::lltok::kw_tail, llvm::lltok::kw_to, llvm::lltok::kw_true, llvm::lltok::kw_trunc, llvm::lltok::kw_udiv, llvm::lltok::kw_ueq, llvm::lltok::kw_uge, llvm::lltok::kw_ugt, llvm::lltok::kw_uitofp, llvm::lltok::kw_ule, llvm::lltok::kw_ult, llvm::lltok::kw_undef, llvm::lltok::kw_une, llvm::lltok::kw_uno, llvm::lltok::kw_unreachable, llvm::lltok::kw_urem, llvm::lltok::kw_uselistorder, llvm::lltok::kw_va_arg, llvm::lltok::kw_xor, llvm::lltok::kw_zeroinitializer, llvm::lltok::kw_zext, llvm::lltok::LabelID, llvm::lltok::LabelStr, llvm::DICompileUnit::LastDebugNameTableKind, llvm::DICompileUnit::LastEmissionKind, llvm::lltok::lbrace, llvm::lltok::less, llvm::LLLexer::Lex(), llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, llvm::ValID::Loc, llvm::lltok::LocalVar, llvm::lltok::LocalVarID, llvm::ValueSymbolTable::lookup(), llvm::lltok::lparen, llvm::lltok::lsquare, llvm::makeArrayRef(), maybeSetDSOLocal(), llvm::lltok::MetadataVar, N, Name, name, llvm::lltok::NameTableKind, llvm::nodes(), llvm::GlobalValue::None, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, P, PARSE_MD_FIELDS, parseField(), llvm::cl::Prefix, llvm::GlobalValue::PrivateLinkage, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::lltok::rbrace, llvm::AttrBuilder::removeAttribute(), llvm::Value::replaceAllUsesWith(), llvm::APFloatBase::rmNearestTiesToEven, llvm::lltok::rparen, llvm::lltok::rsquare, llvm::ARMBuildAttrs::Section, llvm::MCID::Select, llvm::GlobalObject::setAlignment(), llvm::Function::setAttributes(), llvm::Function::setCallingConv(), llvm::GlobalObject::setComdat(), llvm::GlobalValue::setDLLStorageClass(), llvm::Instruction::setFastMathFlags(), llvm::Function::setGC(), llvm::GlobalValue::setLinkage(), llvm::Value::setName(), llvm::GlobalValue::setPartition(), llvm::Function::setPersonalityFn(), llvm::Function::setPrefixData(), llvm::Function::setPrologueData(), llvm::GlobalObject::setSection(), llvm::GlobalValue::setUnnamedAddr(), llvm::GlobalValue::setVisibility(), llvm::SmallVectorBase::size(), llvm::size(), llvm::ARM_MB::ST, llvm::lltok::StringConstant, llvm::ValID::StrVal, llvm::ValID::StrVal2, llvm::ValID::t_APFloat, llvm::ValID::t_APSInt, llvm::ValID::t_Constant, llvm::ValID::t_ConstantStruct, llvm::ValID::t_EmptyArray, llvm::ValID::t_GlobalID, llvm::ValID::t_GlobalName, llvm::ValID::t_InlineAsm, llvm::ValID::t_LocalID, llvm::ValID::t_LocalName, llvm::ValID::t_None, llvm::ValID::t_Null, llvm::ValID::t_PackedConstantStruct, llvm::ValID::t_Undef, llvm::ValID::t_Zero, llvm::Tag, llvm::CallInst::TCK_MustTail, llvm::CallInst::TCK_None, llvm::CallInst::TCK_NoTail, llvm::CallInst::TCK_Tail, llvm::DISubprogram::toSPFlags(), UINT64_MAX, llvm::ValID::UIntVal, llvm::InlineAsm::Verify(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by llvm::LLParser::getContext(), llvm::MachineFunction::getFunctionNumber(), and PrintParentLoopComment().
getTypeString()
static std::string getTypeString (Type * T) static
Definition at line 56 of file LLParser.cpp.
References llvm::raw_string_ostream::str(), and llvm::T.
Referenced by createGlobalFwdRef(), and FunctionNumber().
if() [1/3]
* if (! EatIfPresentlltok::kw_thread_local)
ParseOptionalThreadLocal := /*empty.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), AddCalls(), allocset(), alwaysAvailable(), analyzeGlobalAux(), llvm::AnalyzeVirtRegInBundle(), llvm::HexagonSubtarget::CallMutation::apply(), AssignProtectedObjSet(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::pdb::DbiStreamBuilder::commit(), llvm::ARMBasicBlockUtils::computeBlockSize(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::createSIWholeQuadModePass(), llvm::TargetInstrInfo::defaultDefLatency(), demanglePointerCVQualifiers(), llvm::OrderedBasicBlock::dominates(), llvm::GVNExpression::Expression::dump(), llvm::MCDwarfLineAddr::Encode(), llvm::GVN::ValueTable::eraseTranslateCacheEntry(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::extractName(), llvm::PMDataManager::findAnalysisPass(), llvm::sampleprof::FunctionSamples::findFunctionSamplesAt(), llvm::LexicalScopes::findLexicalScope(), llvm::RuntimeDyldImpl::findOrEmitSection(), llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::gatherUnrollingPreferences(), llvm::IRTranslator::getAnalysisUsage(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::X86TTIImpl::getCastInstrCost(), getElementByteSizeValue(), getExpressionFrameOffset(), llvm::getInlineParams(), llvm::DWARFContext::getInliningInfoForAddress(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::LexicalScopes::getOrCreateAbstractScope(), getOtherIncomingValue(), getPoisonFor(), getRangeForAffineARHelper(), GetRangeFromMetadata(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::MachineTraceMetrics::getResources(), getSetupCost(), getSingleDef(), getTTResKindName(), llvm::AArch64TTIImpl::getUnrollingPreferences(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::getValueState(), llvm::TGLocalVarScope::getVar(), initializeOptionalHeader(), llvm::jitlink::MachOLinkGraphBuilder::isAltEntry(), isLoadConditional(), isMips64EL(), llvm::GVN::ValueTable::lookupOrAdd(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), llvm::SpecialCaseList::Matcher::match(), mayUsePostIncMode(), needsRuntimeRegistrationOfSectionRange(), okayForPHIOfOps(), llvm::DataLayout::operator==(), llvm::DWARFDebugLine::LineTable::parse(), parseNamePrefix(), llvm::FileInfo::printBranchInfo(), llvm::GVNHoist::rank(), resultTests(), llvm::SystemZPostRASchedStrategy::schedNode(), llvm::FastISel::selectExtractValue(), llvm::yaml::MappingTraits< const InterfaceFile * >::setFileTypeForInput(), ShrinkDemandedConstant(), simplifyTerminatorLeadingToRet(), srcMgrDiagHandler(), llvm::ExecutionEngine::StoreValueToMemory(), llvm::TargetPassConfig::TargetPassConfig(), translateImmediate(), llvm::mca::RegisterFile::tryEliminateMove(), tryToUnrollAndJamLoop(), llvm::CrashRecoveryContext::unregisterCleanup(), llvm::LiveIntervals::HMEditor::updateAllRanges(), llvm::coverage::CoverageMappingWriter::write(), and llvm::MachObjectWriter::writeNlist().
if() [2/3]
if (Lex. getKind() = = lltok::lparen)
Definition at line 1557 of file LLParser.cpp.
References llvm::LLLexer::Lex(), and llvm::lltok::rparen.
if() [3/3]
if (! EatIfPresentlltok::kw_addrspace)
isValidVisibilityForLinkage()
static bool isValidVisibilityForLinkage (unsigned V, unsigned L) static
Definition at line 846 of file LLParser.cpp.
References llvm::GlobalValue::DefaultVisibility, and llvm::GlobalValue::isLocalLinkage().
Referenced by FunctionNumber(), and maybeSetDSOLocal().
maybeSetDSOLocal()
static void maybeSetDSOLocal (bool DSOLocal, GlobalValue & GV) static
Definition at line 853 of file LLParser.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAllocSizeAttr(), llvm::AttrBuilder::addAttribute(), llvm::AttrBuilder::addStackAlignmentAttr(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::lltok::AttrGrpID, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, B, C, llvm::AttrBuilder::clear(), llvm::CallingConv::Cold, llvm::lltok::comma, llvm::ValID::ConstantVal, llvm::MCID::Convergent, llvm::GlobalAlias::create(), llvm::GlobalIFunc::create(), llvm::dyn_cast(), llvm::lltok::equal, llvm::GlobalValue::eraseFromParent(), llvm::GlobalValue::ExternalLinkage, llvm::AttributeSet::get(), llvm::Module::getAliasList(), llvm::Module::getGlobalList(), llvm::Module::getIFuncList(), llvm::LLLexer::getKind(), llvm::LLLexer::getLoc(), llvm::Module::getNamedValue(), llvm::LLLexer::getStrVal(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::LLLexer::getUIntVal(), llvm::GlobalValue::getValueType(), llvm::Module::global_end(), llvm::AttrBuilder::hasAttributes(), I, llvm::Type::isFunctionTy(), llvm::GlobalValue::isValidDeclarationLinkage(), llvm::PointerType::isValidElementType(), llvm::GlobalAlias::isValidLinkage(), isValidVisibilityForLinkage(), llvm::ISD::JumpTable, llvm::ValID::Kind, llvm::lltok::kw_addrspacecast, llvm::lltok::kw_alias, llvm::lltok::kw_align, llvm::lltok::kw_alignstack, llvm::lltok::kw_allocsize, llvm::lltok::kw_alwaysinline, llvm::lltok::kw_argmemonly, llvm::lltok::kw_attributes, llvm::lltok::kw_bitcast, llvm::lltok::kw_builtin, llvm::lltok::kw_byval, llvm::lltok::kw_cold, llvm::lltok::kw_convergent, llvm::lltok::kw_dereferenceable, llvm::lltok::kw_dereferenceable_or_null, llvm::lltok::kw_externally_initialized, llvm::lltok::kw_getelementptr, llvm::lltok::kw_ifunc, llvm::lltok::kw_immarg, llvm::lltok::kw_inaccessiblemem_or_argmemonly, llvm::lltok::kw_inaccessiblememonly, llvm::lltok::kw_inalloca, llvm::lltok::kw_inlinehint, llvm::lltok::kw_inreg, llvm::lltok::kw_inttoptr, llvm::lltok::kw_jumptable, llvm::lltok::kw_minsize, llvm::lltok::kw_naked, llvm::lltok::kw_nest, llvm::lltok::kw_noalias, llvm::lltok::kw_nobuiltin, llvm::lltok::kw_nocapture, llvm::lltok::kw_nocf_check, llvm::lltok::kw_noduplicate, llvm::lltok::kw_nofree, llvm::lltok::kw_noimplicitfloat, llvm::lltok::kw_noinline, llvm::lltok::kw_nonlazybind, llvm::lltok::kw_nonnull, llvm::lltok::kw_norecurse, llvm::lltok::kw_noredzone, llvm::lltok::kw_noreturn, llvm::lltok::kw_nosync, llvm::lltok::kw_nounwind, llvm::lltok::kw_optforfuzzing, llvm::lltok::kw_optnone, llvm::lltok::kw_optsize, llvm::lltok::kw_partition, llvm::lltok::kw_readnone, llvm::lltok::kw_readonly, llvm::lltok::kw_returned, llvm::lltok::kw_returns_twice, llvm::lltok::kw_safestack, llvm::lltok::kw_sanitize_address, llvm::lltok::kw_sanitize_hwaddress, llvm::lltok::kw_sanitize_memory, llvm::lltok::kw_sanitize_memtag, llvm::lltok::kw_sanitize_thread, llvm::lltok::kw_section, llvm::lltok::kw_shadowcallstack, llvm::lltok::kw_signext, llvm::lltok::kw_speculatable, llvm::lltok::kw_speculative_load_hardening, llvm::lltok::kw_sret, llvm::lltok::kw_ssp, llvm::lltok::kw_sspreq, llvm::lltok::kw_sspstrong, llvm::lltok::kw_strictfp, llvm::lltok::kw_swifterror, llvm::lltok::kw_swiftself, llvm::lltok::kw_uwtable, llvm::lltok::kw_willreturn, llvm::lltok::kw_writeonly, llvm::lltok::kw_zeroext, llvm::lltok::lbrace, llvm::LLLexer::Lex(), llvm_unreachable, llvm::lltok::MetadataVar, Name, llvm::GlobalValue::NotThreadLocal, llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::lltok::rbrace, llvm::Value::replaceAllUsesWith(), llvm::GlobalObject::setAlignment(), llvm::GlobalVariable::setAttributes(), llvm::GlobalObject::setComdat(), llvm::GlobalVariable::setConstant(), llvm::GlobalValue::setDLLStorageClass(), llvm::GlobalValue::setDSOLocal(), llvm::GlobalVariable::setExternallyInitialized(), llvm::GlobalVariable::setInitializer(), llvm::GlobalValue::setLinkage(), llvm::GlobalValue::setPartition(), llvm::GlobalObject::setSection(), llvm::GlobalValue::setThreadLocalMode(), llvm::GlobalValue::setUnnamedAddr(), llvm::GlobalValue::setVisibility(), llvm::iplist_impl< IntrusiveListT, TraitsT >::splice(), llvm::lltok::StringConstant, llvm::ValID::t_Constant, and TLM.
Referenced by FunctionNumber().
parseOptionalLinkageAux()
static unsigned parseOptionalLinkageAux (lltok::Kind Kind, bool & HasLinkage) static
Definition at line 1797 of file LLParser.cpp.
References llvm::CallingConv::AArch64_SVE_VectorCall, llvm::CallingConv::AArch64_VectorCall, llvm::Acquire, llvm::AcquireRelease, llvm::GlobalObject::addMetadata(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::CallingConv::AnyReg, llvm::GlobalValue::AppendingLinkage, llvm::lltok::APSInt, llvm::CallingConv::ARM_AAPCS, llvm::CallingConv::ARM_AAPCS_VFP, llvm::CallingConv::ARM_APCS, assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::GlobalValue::AvailableExternallyLinkage, llvm::CallingConv::AVR_INTR, llvm::CallingConv::AVR_SIGNAL, llvm::CallingConv::C, llvm::CallingConv::CFGuard_Check, llvm::CallingConv::Cold, llvm::lltok::comma, llvm::GlobalValue::CommonLinkage, llvm::StructType::create(), llvm::CallingConv::CXX_FAST_TLS, llvm::GlobalValue::DefaultStorageClass, llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::DLLExportStorageClass, llvm::GlobalValue::DLLImportStorageClass, llvm::lltok::dotdotdot, llvm::numbers::e, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, F(), llvm::CallingConv::Fast, llvm::FunctionType::get(), llvm::AttributeSet::get(), llvm::StructType::get(), llvm::ArrayType::get(), llvm::VectorType::get(), llvm::PointerType::get(), llvm::LLLexer::getAPSIntVal(), llvm::APInt::getBitWidth(), llvm::Type::getContext(), llvm::Value::getContext(), llvm::LLLexer::getKind(), llvm::LLLexer::getLoc(), llvm::Module::getMDKindID(), llvm::LLVMContext::getOrInsertSyncScopeID(), llvm::LLLexer::getStrVal(), llvm::LLLexer::getTyVal(), llvm::LLLexer::getUIntVal(), llvm::PointerType::getUnqual(), llvm::APInt::getZExtValue(), llvm::CallingConv::GHC, llvm::lltok::greater, llvm::CallingConv::HHVM, llvm::CallingConv::HHVM_C, llvm::GlobalValue::HiddenVisibility, llvm::CallingConv::Intel_OCL_BI, llvm::GlobalValue::InternalLinkage, isAtomic(), llvm::Type::isFirstClassType(), llvm::Type::isLabelTy(), llvm::Type::isMetadataTy(), llvm::isPowerOf2_32(), llvm::APSInt::isSigned(), llvm::FunctionType::isValidArgumentType(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::VectorType::isValidElementType(), llvm::PointerType::isValidElementType(), llvm::FunctionType::isValidReturnType(), llvm::LegalityPredicates::isVector(), llvm::Type::isVoidTy(), llvm::lltok::kw_aarch64_sve_vector_pcs, llvm::lltok::kw_aarch64_vector_pcs, llvm::lltok::kw_acq_rel, llvm::lltok::kw_acquire, llvm::lltok::kw_addrspace, llvm::lltok::kw_align, llvm::lltok::kw_alignstack, llvm::lltok::kw_amdgpu_cs, llvm::lltok::kw_amdgpu_es, llvm::lltok::kw_amdgpu_gs, llvm::lltok::kw_amdgpu_hs, llvm::lltok::kw_amdgpu_kernel, llvm::lltok::kw_amdgpu_ls, llvm::lltok::kw_amdgpu_ps, llvm::lltok::kw_amdgpu_vs, llvm::lltok::kw_anyregcc, llvm::lltok::kw_appending, llvm::lltok::kw_arm_aapcs_vfpcc, llvm::lltok::kw_arm_aapcscc, llvm::lltok::kw_arm_apcscc, llvm::lltok::kw_available_externally, llvm::lltok::kw_avr_intrcc, llvm::lltok::kw_avr_signalcc, llvm::lltok::kw_byval, llvm::lltok::kw_cc, llvm::lltok::kw_ccc, llvm::lltok::kw_cfguard_checkcc, llvm::lltok::kw_coldcc, llvm::lltok::kw_common, llvm::lltok::kw_cxx_fast_tlscc, llvm::lltok::kw_default, llvm::lltok::kw_dereferenceable, llvm::lltok::kw_dereferenceable_or_null, llvm::lltok::kw_dllexport, llvm::lltok::kw_dllimport, llvm::lltok::kw_dso_local, llvm::lltok::kw_dso_preemptable, llvm::lltok::kw_extern_weak, llvm::lltok::kw_external, llvm::lltok::kw_fastcc, llvm::lltok::kw_ghccc, llvm::lltok::kw_hhvm_ccc, llvm::lltok::kw_hhvmcc, llvm::lltok::kw_hidden, llvm::lltok::kw_intel_ocl_bicc, llvm::lltok::kw_internal, llvm::lltok::kw_linkonce, llvm::lltok::kw_linkonce_odr, llvm::lltok::kw_monotonic, llvm::lltok::kw_msp430_intrcc, llvm::lltok::kw_opaque, llvm::lltok::kw_preserve_allcc, llvm::lltok::kw_preserve_mostcc, llvm::lltok::kw_private, llvm::lltok::kw_protected, llvm::lltok::kw_ptx_device, llvm::lltok::kw_ptx_kernel, llvm::lltok::kw_release, llvm::lltok::kw_seq_cst, llvm::lltok::kw_spir_func, llvm::lltok::kw_spir_kernel, llvm::lltok::kw_swiftcc, llvm::lltok::kw_syncscope, llvm::lltok::kw_tailcc, llvm::lltok::kw_unordered, llvm::lltok::kw_vscale, llvm::lltok::kw_weak, llvm::lltok::kw_weak_odr, llvm::lltok::kw_webkit_jscc, llvm::lltok::kw_win64cc, llvm::lltok::kw_x, llvm::lltok::kw_x86_64_sysvcc, llvm::lltok::kw_x86_fastcallcc, llvm::lltok::kw_x86_intrcc, llvm::lltok::kw_x86_regcallcc, llvm::lltok::kw_x86_stdcallcc, llvm::lltok::kw_x86_thiscallcc, llvm::lltok::kw_x86_vectorcallcc, llvm::lltok::lbrace, llvm::lltok::less, llvm::LLLexer::Lex(), llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm::lltok::LocalVar, llvm::lltok::LocalVarID, llvm::lltok::lparen, llvm::lltok::lsquare, llvm::Value::MaximumAlignment, llvm::lltok::MetadataVar, llvm::Monotonic, llvm::CallingConv::MSP430_INTR, N, Name, llvm::None, llvm::CallingConv::PreserveAll, llvm::CallingConv::PreserveMost, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::ProtectedVisibility, llvm::CallingConv::PTX_Device, llvm::CallingConv::PTX_Kernel, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::lltok::rbrace, llvm::Release, llvm::lltok::rparen, llvm::lltok::rsquare, llvm::SequentiallyConsistent, llvm::StructType::setBody(), llvm::Instruction::setMetadata(), Size, llvm::SmallVectorBase::size(), llvm::CallingConv::SPIR_FUNC, llvm::CallingConv::SPIR_KERNEL, llvm::lltok::star, llvm::CallingConv::Swift, llvm::SyncScope::System, llvm::Tag, llvm::CallingConv::Tail, llvm::lltok::Type, llvm::Unordered, llvm::GlobalValue::WeakAnyLinkage, llvm::GlobalValue::WeakODRLinkage, llvm::CallingConv::WebKit_JS, llvm::CallingConv::Win64, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_INTR, llvm::CallingConv::X86_RegCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::CallingConv::X86_VectorCall.
Referenced by resolveFwdRef().
resolveFwdRef()
static void resolveFwdRef (ValueInfo * Fwd, ValueInfo & Resolved) static
Definition at line 7919 of file LLParser.cpp.
References llvm::FunctionSummary::FFlags::AlwaysInline, llvm::lltok::APSInt, llvm::FunctionSummary::ConstVCall::Args, assert(), llvm::GlobalValueSummary::GVFlags::CanAutoHide, llvm::CalleeInfo::Cold, llvm::lltok::colon, llvm::lltok::comma, llvm::CalleeInfo::Critical, llvm::GlobalValueSummary::GVFlags::DSOLocal, llvm::StringRef::empty(), llvm::GlobalValue::ExternalLinkage, llvm::X86AS::FS, FwdVIRef, llvm::GlobalValue::getGlobalIdentifier(), llvm::GlobalValue::getGUID(), llvm::ValueInfo::getRef(), llvm::X86AS::GS, llvm::FunctionSummary::VFuncId::GUID, llvm::CalleeInfo::Hot, I, llvm::GlobalValue::isLocalLinkage(), llvm::ValueInfo::isReadOnly(), llvm::ValueInfo::isWriteOnly(), llvm::lltok::kw_alias, llvm::lltok::kw_aliasee, llvm::lltok::kw_alwaysInline, llvm::lltok::kw_callee, llvm::lltok::kw_calls, llvm::lltok::kw_canAutoHide, llvm::lltok::kw_cold, llvm::lltok::kw_critical, llvm::lltok::kw_dsoLocal, llvm::lltok::kw_flags, llvm::lltok::kw_funcFlags, llvm::lltok::kw_function, llvm::lltok::kw_guid, llvm::lltok::kw_gv, llvm::lltok::kw_hot, llvm::lltok::kw_hotness, llvm::lltok::kw_insts, llvm::lltok::kw_linkage, llvm::lltok::kw_live, llvm::lltok::kw_module, llvm::lltok::kw_name, llvm::lltok::kw_noInline, llvm::lltok::kw_none, llvm::lltok::kw_noRecurse, llvm::lltok::kw_notEligibleToImport, llvm::lltok::kw_offset, llvm::lltok::kw_readNone, llvm::lltok::kw_readonly, llvm::lltok::kw_readOnly, llvm::lltok::kw_refs, llvm::lltok::kw_relbf, llvm::lltok::kw_returnDoesNotAlias, llvm::lltok::kw_summaries, llvm::lltok::kw_typeCheckedLoadConstVCalls, llvm::lltok::kw_typeCheckedLoadVCalls, llvm::lltok::kw_typeIdInfo, llvm::lltok::kw_typeTestAssumeConstVCalls, llvm::lltok::kw_typeTestAssumeVCalls, llvm::lltok::kw_typeTests, llvm::lltok::kw_unknown, llvm::lltok::kw_varFlags, llvm::lltok::kw_variable, llvm::lltok::kw_vFuncId, llvm::lltok::kw_virtFunc, llvm::lltok::kw_vTableFuncs, llvm::lltok::kw_writeonly, llvm::GlobalValueSummary::GVFlags::Linkage, llvm::GlobalValueSummary::GVFlags::Live, llvm::lltok::lparen, llvm::GlobalVarSummary::GVarFlags::MaybeReadOnly, llvm::GlobalVarSummary::GVarFlags::MaybeWriteOnly, Name, llvm::FunctionSummary::FFlags::NoInline, llvm::CalleeInfo::None, llvm::FunctionSummary::FFlags::NoRecurse, llvm::GlobalValueSummary::GVFlags::NotEligibleToImport, llvm::FunctionSummary::VFuncId::Offset, parseOptionalLinkageAux(), llvm::FunctionSummary::FFlags::ReadNone, llvm::FunctionSummary::FFlags::ReadOnly, llvm::FunctionSummary::FFlags::ReturnDoesNotAlias, llvm::lltok::rparen, llvm::ValueInfo::setReadOnly(), llvm::ValueInfo::setWriteOnly(), llvm::sort(), llvm::lltok::SummaryID, llvm::FunctionSummary::TypeIdInfo::TypeCheckedLoadConstVCalls, llvm::FunctionSummary::TypeIdInfo::TypeCheckedLoadVCalls, llvm::FunctionSummary::TypeIdInfo::TypeTestAssumeConstVCalls, llvm::FunctionSummary::TypeIdInfo::TypeTestAssumeVCalls, llvm::FunctionSummary::TypeIdInfo::TypeTests, llvm::CalleeInfo::Unknown, llvm::AArch64CC::VC, llvm::FunctionSummary::ConstVCall::VFunc, and VI.
Variable Documentation
DefaultAS
unsigned DefaultAS
Initial value:
{
  AddrSpace = DefaultAS
Definition at line 1568 of file LLParser.cpp.
Referenced by llvm::LLParser::getContext().
false
return false
Definition at line 1562 of file LLParser.cpp.
FwdVIRef
const auto FwdVIRef = (GlobalValueSummaryMapTy::value_type *)-8 static
Definition at line 7917 of file LLParser.cpp.
Referenced by resolveFwdRef().
TLM
TLM = GlobalVariable::GeneralDynamicTLSModel
Definition at line 1556 of file LLParser.cpp.
Referenced by createGlobalFwdRef(), llvm::LLParser::getContext(), and maybeSetDSOLocal().