LLVM: lib/CodeGen/LocalStackSlotAllocation.cpp File Reference
LocalStackSlotAllocation.cpp File Reference
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <tuple>
Macros
#define DEBUG_TYPE "localstackalloc"
Functions
STATISTIC (NumAllocations, "Number of frame indices allocated into local block")
STATISTIC (NumBaseRegisters, "Number of virtual frame base registers allocated")
STATISTIC (NumReplacements, "Number of frame indices references replaced")
INITIALIZE_PASS (LocalStackSlotPass, DEBUG_TYPE, "Local Stack Slot Allocation", false, false) bool LocalStackSlotPass
static bool lookupCandidateBaseReg (unsigned BaseReg, int64_t BaseOffset, int64_t FrameSizeAdjust, int64_t LocalFrameOffset, const MachineInstr &MI, const TargetRegisterInfo *TRI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "localstackalloc"
Definition at line 43 of file LocalStackSlotAllocation.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LocalStackSlotPass , DEBUG_TYPE , "Local Stack Slot Allocation" , false , false)
Definition at line 110 of file LocalStackSlotAllocation.cpp.
References AdjustStackOffset(), assert(), AssignProtectedObjSet(), llvm::assumeAligned(), llvm::SetVector< T, Vector, Set >::begin(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::numbers::e, E, llvm::SetVector< T, Vector, Set >::end(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getObjectSSPLayout(), llvm::TargetFrameLowering::getStackGrowthDirection(), llvm::MachineFrameInfo::getStackProtectorIndex(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasStackProtectorIndex(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineFrameInfo::isObjectPreAllocated(), LLVM_DEBUG, llvm_unreachable, llvm::MachineFrameInfo::mapLocalFrameObject(), llvm::max(), llvm::TargetRegisterInfo::requiresVirtualBaseRegisters(), llvm::SmallVectorImpl< T >::resize(), llvm::MachineFrameInfo::setLocalFrameMaxAlign(), llvm::MachineFrameInfo::setLocalFrameSize(), llvm::MachineFrameInfo::setUseLocalStackAllocationBlock(), llvm::MachineFrameInfo::SSPLK_AddrOf, llvm::MachineFrameInfo::SSPLK_LargeArray, llvm::MachineFrameInfo::SSPLK_None, llvm::MachineFrameInfo::SSPLK_SmallArray, llvm::TargetFrameLowering::StackGrowsDown, and TRI.
lookupCandidateBaseReg()
static bool lookupCandidateBaseReg (unsigned BaseReg, int64_t BaseOffset, int64_t FrameSizeAdjust, int64_t LocalFrameOffset, const MachineInstr & MI, const TargetRegisterInfo * TRI) inline static
Definition at line 269 of file LocalStackSlotAllocation.cpp.
References assert(), llvm::dbgs(), llvm::numbers::e, llvm::TargetRegisterInfo::getFrameIndexInstrOffset(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineOperand::getIndex(), llvm::MachineFrameInfo::getLocalFrameSize(), getMachineInstr(), llvm::MachineInstr::getMF(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::TargetRegisterInfo::getPointerRegClass(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetFrameLowering::getStackGrowthDirection(), llvm::MachineFrameInfo::getStackProtectorIndex(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasStackProtectorIndex(), llvm::MachineOperand::isFI(), llvm::TargetRegisterInfo::isFrameOffsetLegal(), llvm::MachineFrameInfo::isObjectPreAllocated(), LLVM_DEBUG, llvm::TargetRegisterInfo::materializeFrameBaseRegister(), MI, llvm::TargetRegisterInfo::needsFrameBaseReg(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::TargetRegisterInfo::resolveFrameIndex(), llvm::SmallVectorBase::size(), llvm::sort(), llvm::TargetFrameLowering::StackGrowsDown, and TRI.
STATISTIC() [1/3]
STATISTIC (NumAllocations , "Number of frame indices allocated into local block")
STATISTIC() [2/3]
STATISTIC (NumBaseRegisters , "Number of virtual frame base registers allocated")
STATISTIC() [3/3]
STATISTIC (NumReplacements , "Number of frame indices references replaced")