LLVM: lib/Support/LockFileManager.cpp File Reference
LockFileManager.cpp File Reference
#include "llvm/Support/LockFileManager.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/raw_ostream.h"
#include <cerrno>
#include <ctime>
#include <memory>
#include <sys/stat.h>
#include <sys/types.h>
#include <system_error>
#include <tuple>
Macros
#define USE_OSX_GETHOSTUUID 0
Functions
static std::error_code getHostID (SmallVectorImpl< char > &HostID)
Macro Definition Documentation
USE_OSX_GETHOSTUUID
#define USE_OSX_GETHOSTUUID 0
Definition at line 36 of file LockFileManager.cpp.
Function Documentation
getHostID()
static std::error_code getHostID (SmallVectorImpl< char > & HostID) static
Definition at line 78 of file LockFileManager.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::sys::DontRemoveFileOnSignal(), llvm::NVPTXISD::Dummy, llvm::StringRef::end(), Name, llvm::sys::fs::remove(), and llvm::sys::RemoveFileOnSignal().
Referenced by llvm::LockFileManager::LockFileManager().