LLVM: lib/Transforms/Vectorize/LoopVectorize.cpp File Reference
LoopVectorize.cpp File Reference
#include "llvm/Transforms/Vectorize/LoopVectorize.h"
#include "LoopVectorizationPlanner.h"
#include "VPRecipeBuilder.h"
#include "VPlan.h"
#include "VPlanHCFGBuilder.h"
#include "VPlanPredicator.h"
#include "VPlanTransforms.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/DemandedBits.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/LoopAccessAnalysis.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/LoopSimplify.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/LoopVersioning.h"
#include "llvm/Transforms/Utils/SizeOpts.h"
#include "llvm/Transforms/Vectorize/LoopVectorizationLegality.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <functional>
#include <iterator>
#include <limits>
#include <memory>
#include <string>
#include <tuple>
#include <utility>
Classes
class llvm::InnerLoopVectorizer
InnerLoopVectorizer vectorizes loops which contain only one basic block to a specified vectorization factor (VF).
class llvm::InnerLoopUnroller
class llvm::LoopVectorizationCostModel
LoopVectorizationCostModel - estimates the expected speedups due to vectorization.
struct llvm::LoopVectorizationCostModel::RegisterUsage
A struct that represents some properties of the register usage of a loop.
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define LV_NAME "loop-vectorize"
#define DEBUG_TYPE LV_NAME
Enumerations
enum llvm::ScalarEpilogueLowering { llvm::CM_ScalarEpilogueAllowed, llvm::CM_ScalarEpilogueNotAllowedOptSize, llvm::CM_ScalarEpilogueNotAllowedLowTripLoop, llvm::CM_ScalarEpilogueNotNeededUsePredicate }
Functions
STATISTIC (LoopsVectorized, "Number of loops vectorized")
STATISTIC (LoopsAnalyzed, "Number of loops analyzed for vectorization")
static Type * ToVectorTy (Type *Scalar, unsigned VF)
A helper function for converting Scalar types to vector types.
static Type * getMemInstValueType (Value *I)
A helper function that returns the type of loaded or stored value.
static bool hasIrregularType (Type *Ty, const DataLayout &DL, unsigned VF)
A helper function that returns true if the given type is irregular.
static unsigned getReciprocalPredBlockProb ()
A helper function that returns the reciprocal of the block probability of predicated blocks.
static Value * addFastMathFlag (Value *V)
A helper function that adds a 'fast' flag to floating-point operations.
static Value * addFastMathFlag (Value *V, FastMathFlags FMF)
static Constant * getSignedIntOrFpConstant (Type *Ty, int64_t C)
A helper function that returns an integer or floating-point constant with value C.
static Optional< unsigned > getSmallBestKnownTC (ScalarEvolution &SE, Loop *L)
Returns "best known" trip count for the specified loop L as defined by the following procedure: 1) Returns exact trip count if it is known.
static Instruction * getDebugLocFromInstOrOperands (Instruction *I)
Look for a meaningful debug location on the instruction or it's operands.
static void debugVectorizationFailure (const StringRef DebugMsg, Instruction *I)
Write a record DebugMsg about vectorization failure to the debug output stream.
static OptimizationRemarkAnalysis createLVAnalysis (const char *PassName, StringRef RemarkName, Loop *TheLoop, Instruction *I)
Create an analysis remark that explains why vectorization failed.
void llvm::reportVectorizationFailure (const StringRef DebugMsg, const StringRef OREMsg, const StringRef ORETag, OptimizationRemarkEmitter *ORE, Loop *TheLoop, Instruction *I=nullptr)
Reports a vectorization failure: print DebugMsg for debugging purposes along with the corresponding optimization remark RemarkName.
static std::string getDebugLocString (const Loop *L)
static bool isExplicitVecOuterLoop (Loop *OuterLp, OptimizationRemarkEmitter *ORE)
static void collectSupportedLoops (Loop &L, LoopInfo *LI, OptimizationRemarkEmitter *ORE, SmallVectorImpl< Loop *> &V)
static bool useMaskedInterleavedAccesses (const TargetTransformInfo &TTI)
static void cse (BasicBlock *BB)
Perform cse of induction variable instructions.
static Type * smallestIntegerVectorType (Type *T1, Type *T2)
static Type * largestIntegerVectorType (Type *T1, Type *T2)
static bool mayDivideByZero (Instruction &I)
A helper function for checking whether an integer division-related instruction may divide by zero (in which case it must be predicated if executed conditionally in the scalar code).
static const SCEV * getAddressAccessSCEV (Value *Ptr, LoopVectorizationLegality *Legal, PredicatedScalarEvolution &PSE, const Loop *TheLoop)
Gets Address Access SCEV after verifying that the access pattern is loop invariant except the induction variable dependence.
static bool isStrideMul (Instruction *I, LoopVectorizationLegality *Legal)
Pass * llvm::createLoopVectorizePass ()
Pass * llvm::createLoopVectorizePass (bool InterleaveOnlyWhenForced, bool VectorizeOnlyWhenForced)
static unsigned determineVPlanVF (const unsigned WidestVectorRegBits, LoopVectorizationCostModel &CM)
static void AddRuntimeUnrollDisableMetaData (Loop *L)
static ScalarEpilogueLowering getScalarEpilogueLowering (Function *F, Loop *L, LoopVectorizeHints &Hints, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI, TargetTransformInfo *TTI, TargetLibraryInfo *TLI, AssumptionCache *AC, LoopInfo *LI, ScalarEvolution *SE, DominatorTree *DT, LoopVectorizationLegality &LVL)
static bool processLoopInVPlanNativePath (Loop *L, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, LoopVectorizationLegality *LVL, TargetTransformInfo *TTI, TargetLibraryInfo *TLI, DemandedBits *DB, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI, LoopVectorizeHints &Hints)
Variables
static cl::opt< unsigned > TinyTripCountVectorThreshold ("vectorizer-min-trip-count", cl::init(16), cl::Hidden, cl::desc("Loops with a constant trip count that is smaller than this " "value are vectorized only if no scalar iteration overheads " "are incurred."))
Loops with a known constant trip count below this number are vectorized only if no scalar iteration overheads are incurred.
static cl::opt< bool > PreferPredicateOverEpilog ("prefer-predicate-over-epilog", cl::init(false), cl::Hidden, cl::desc("Indicate that an epilogue is undesired, predication should be " "used instead."))
static cl::opt< bool > MaximizeBandwidth ("vectorizer-maximize-bandwidth", cl::init(false), cl::Hidden, cl::desc("Maximize bandwidth when selecting vectorization factor which " "will be determined by the smallest type in loop."))
static cl::opt< bool > EnableInterleavedMemAccesses ("enable-interleaved-mem-accesses", cl::init(false), cl::Hidden, cl::desc("Enable vectorization on interleaved memory accesses in a loop"))
static cl::opt< bool > EnableMaskedInterleavedMemAccesses ("enable-masked-interleaved-mem-accesses", cl::init(false), cl::Hidden, cl::desc("Enable vectorization on masked interleaved memory accesses in a loop"))
An interleave-group may need masking if it resides in a block that needs predication, or in order to mask away gaps.
static cl::opt< unsigned > TinyTripCountInterleaveThreshold ("tiny-trip-count-interleave-threshold", cl::init(128), cl::Hidden, cl::desc("We don't interleave loops with a estimated constant trip count " "below this number"))
static cl::opt< unsigned > ForceTargetNumScalarRegs ("force-target-num-scalar-regs", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's number of scalar registers."))
static cl::opt< unsigned > ForceTargetNumVectorRegs ("force-target-num-vector-regs", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's number of vector registers."))
static cl::opt< unsigned > ForceTargetMaxScalarInterleaveFactor ("force-target-max-scalar-interleave", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's max interleave factor for " "scalar loops."))
static cl::opt< unsigned > ForceTargetMaxVectorInterleaveFactor ("force-target-max-vector-interleave", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's max interleave factor for " "vectorized loops."))
static cl::opt< unsigned > ForceTargetInstructionCost ("force-target-instruction-cost", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's expected cost for " "an instruction to a single constant value. Mostly " "useful for getting consistent testing."))
static cl::opt< unsigned > SmallLoopCost ("small-loop-cost", cl::init(20), cl::Hidden, cl::desc("The cost of a loop that is considered 'small' by the interleaver."))
static cl::opt< bool > LoopVectorizeWithBlockFrequency ("loop-vectorize-with-block-frequency", cl::init(true), cl::Hidden, cl::desc("Enable the use of the block frequency analysis to access PGO " "heuristics minimizing code growth in cold regions and being more " "aggressive in hot regions."))
static cl::opt< bool > EnableLoadStoreRuntimeInterleave ("enable-loadstore-runtime-interleave", cl::init(true), cl::Hidden, cl::desc("Enable runtime interleaving until load/store ports are saturated"))
static cl::opt< unsigned > NumberOfStoresToPredicate ("vectorize-num-stores-pred", cl::init(1), cl::Hidden, cl::desc("Max number of stores to be predicated behind an if."))
The number of stores in a loop that are allowed to need predication.
static cl::opt< bool > EnableIndVarRegisterHeur ("enable-ind-var-reg-heur", cl::init(true), cl::Hidden, cl::desc("Count the induction variable only once when interleaving"))
static cl::opt< bool > EnableCondStoresVectorization ("enable-cond-stores-vec", cl::init(true), cl::Hidden, cl::desc("Enable if predication of stores during vectorization."))
static cl::opt< unsigned > MaxNestedScalarReductionIC ("max-nested-scalar-reduction-interleave", cl::init(2), cl::Hidden, cl::desc("The maximum interleave count to use when interleaving a scalar " "reduction in a nested loop."))
cl::opt< bool > EnableVPlanNativePath ("enable-vplan-native-path", cl::init(false), cl::Hidden, cl::desc("Enable VPlan-native vectorization path with " "support for outer loop vectorization."))
cl::opt< bool > EnableVPlanPredication ("enable-vplan-predication", cl::init(false), cl::Hidden, cl::desc("Enable VPlan-native vectorization path predicator with " "support for outer loop vectorization."))
static cl::opt< bool > VPlanBuildStressTest ("vplan-build-stress-test", cl::init(false), cl::Hidden, cl::desc("Build VPlan for every supported loop nest in the function and bail " "out right after the build (stress test the VPlan H-CFG construction " "in the VPlan-native vectorization path)."))
static const char lv_name [] = "Loop Vectorization"
static const char *const LLVMLoopVectorizeFollowupAll
static const char *const LLVMLoopVectorizeFollowupVectorized
static const char *const LLVMLoopVectorizeFollowupEpilogue
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE LV_NAME
Definition at line 157 of file LoopVectorize.cpp.
Referenced by llvm::InnerLoopVectorizer::emitMemRuntimeChecks().
LV_NAME
#define LV_NAME "loop-vectorize"
Definition at line 156 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizePass::processLoop().
Function Documentation
addFastMathFlag() [1/2]
static Value* addFastMathFlag (Value * V) static
A helper function that adds a 'fast' flag to floating-point operations.
Definition at line 340 of file LoopVectorize.cpp.
References llvm::FastMathFlags::getFast().
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), and llvm::InnerLoopVectorizer::fixReduction().
addFastMathFlag() [2/2]
static Value* addFastMathFlag (Value * V, FastMathFlags FMF) static
Definition at line 346 of file LoopVectorize.cpp.
AddRuntimeUnrollDisableMetaData()
static void AddRuntimeUnrollDisableMetaData (Loop * L) static
Definition at line 6642 of file LoopVectorize.cpp.
References Context, llvm::dyn_cast(), llvm::MDString::get(), llvm::MDNode::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Loop::getLoopID(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MDNode::replaceOperandWith(), and llvm::Loop::setLoopID().
Referenced by llvm::LoopVectorizePass::processLoop().
collectSupportedLoops()
static void collectSupportedLoops (Loop & L, LoopInfo * LI, OptimizationRemarkEmitter * ORE, SmallVectorImpl< Loop *> & V) static
Definition at line 1565 of file LoopVectorize.cpp.
References llvm::InnerLoopVectorizer::AA, llvm::InnerLoopVectorizer::AC, llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::AMDGPUISD::BFI, llvm::InnerLoopVectorizer::DT, llvm::LoopBase< BlockT, LoopT >::empty(), EnableVPlanNativePath, F(), llvm::PassRegistry::getPassRegistry(), llvm::initializeLoopVectorizePass(), llvm::LoopVectorizePass::InterleaveOnlyWhenForced, isExplicitVecOuterLoop(), llvm::InnerLoopVectorizer::LI, llvm::InnerLoopVectorizer::ORE, llvm::LoopBlocksRPO::perform(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LoopVectorizePass::runImpl(), runOnFunction(), llvm::InnerLoopVectorizer::TLI, llvm::InnerLoopVectorizer::TTI, llvm::LoopVectorizePass::VectorizeOnlyWhenForced, and VPlanBuildStressTest.
Referenced by llvm::LoopVectorizePass::runImpl().
createLVAnalysis()
static OptimizationRemarkAnalysis createLVAnalysis (const char * PassName, StringRef RemarkName, Loop * TheLoop, Instruction * I) static
Create an analysis remark that explains why vectorization failed.
PassName is the name of the pass (e.g. can be AlwaysPrint). RemarkName is the identifier for the remark. If I is passed it is an instruction that prevents vectorization. Otherwise TheLoop is used for the location of the remark.
Returns
the remark object that can be streamed to.
Definition at line 861 of file LoopVectorize.cpp.
References llvm::Instruction::getDebugLoc(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Instruction::getParent(), and llvm::Loop::getStartLoc().
Referenced by llvm::reportVectorizationFailure().
cse()
static void cse (BasicBlock * BB) static
Perform cse of induction variable instructions.
Definition at line 3236 of file LoopVectorize.cpp.
References llvm::BasicBlock::begin(), E, llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), I, llvm::tgtok::In, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and llvm::Value::replaceAllUsesWith().
Referenced by llvm::InnerLoopVectorizer::fixVectorizedLoop().
debugVectorizationFailure()
static void debugVectorizationFailure (const StringRef DebugMsg, Instruction * I) static
Write a record DebugMsg about vectorization failure to the debug output stream.
If I is passed, it is an instruction that prevents vectorization.
Definition at line 843 of file LoopVectorize.cpp.
References llvm::dbgs(), and I.
Referenced by llvm::reportVectorizationFailure().
determineVPlanVF()
static unsigned determineVPlanVF (const unsigned WidestVectorRegBits, LoopVectorizationCostModel & CM) static
Definition at line 6446 of file LoopVectorize.cpp.
References llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes().
Referenced by llvm::LoopVectorizationPlanner::planInVPlanNativePath().
getAddressAccessSCEV()
static const SCEV* getAddressAccessSCEV (Value * Ptr, LoopVectorizationLegality * Legal, PredicatedScalarEvolution & PSE, const Loop * TheLoop) static
Gets Address Access SCEV after verifying that the access pattern is loop invariant except the induction variable dependence.
This SCEV can be sent to the Target in order to estimate the address calculation cost.
Definition at line 5760 of file LoopVectorize.cpp.
References llvm::dyn_cast(), llvm::PredicatedScalarEvolution::getSCEV(), llvm::PredicatedScalarEvolution::getSE(), and llvm::LoopVectorizationLegality::isInductionVariable().
Referenced by isStrideMul().
getDebugLocFromInstOrOperands()
static Instruction* getDebugLocFromInstOrOperands (Instruction * I) static
Look for a meaningful debug location on the instruction or it's operands.
Definition at line 803 of file LoopVectorize.cpp.
References llvm::Empty, llvm::Instruction::getDebugLoc(), I, llvm::User::op_begin(), and llvm::User::op_end().
Referenced by llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton().
getDebugLocString()
static std::string getDebugLocString (const Loop * L) static
Returns
string containing a file name and a line # for the given loop.
Definition at line 894 of file LoopVectorize.cpp.
References llvm::raw_ostream::flush(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Module::getModuleIdentifier(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), and llvm::Loop::getStartLoc().
Referenced by llvm::LoopVectorizePass::processLoop().
getMemInstValueType()
static Type* getMemInstValueType (Value * I) static
A helper function that returns the type of loaded or stored value.
Definition at line 307 of file LoopVectorize.cpp.
References assert(), and I.
Referenced by llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::LoopVectorizationCostModel::isLegalGatherOrScatter(), llvm::LoopVectorizationCostModel::isScalarWithPredication(), isStrideMul(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
getReciprocalPredBlockProb()
static unsigned getReciprocalPredBlockProb () static
A helper function that returns the reciprocal of the block probability of predicated blocks.
If we return X, we are assuming the predicated block will execute once for every X iterations of the loop header.
TODO: We should use actual block probability here, if available. Currently, we always assume predicated blocks have a 50% chance of executing.
Definition at line 337 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::collectInstsToScalarize(), isStrideMul(), and llvm::LoopVectorizationCostModel::setCostBasedWideningDecision().
getScalarEpilogueLowering()
static ScalarEpilogueLowering getScalarEpilogueLowering (Function * F, Loop * L, LoopVectorizeHints & Hints, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI, TargetTransformInfo * TTI, TargetLibraryInfo * TLI, AssumptionCache * AC, LoopInfo * LI, ScalarEvolution * SE, DominatorTree * DT, LoopVectorizationLegality & LVL) static
Definition at line 7510 of file LoopVectorize.cpp.
References llvm::AMDGPUISD::BFI, llvm::CM_ScalarEpilogueAllowed, llvm::CM_ScalarEpilogueNotAllowedOptSize, llvm::CM_ScalarEpilogueNotNeededUsePredicate, llvm::LoopVectorizeHints::FK_Disabled, llvm::LoopVectorizeHints::FK_Enabled, llvm::LoopVectorizeHints::getForce(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getLAI(), llvm::LoopVectorizeHints::getPredicate(), llvm::LoopVectorizationLegality::getPrimaryInduction(), llvm::Function::hasOptSize(), llvm::IRPass, PreferPredicateOverEpilog, llvm::TargetTransformInfo::preferPredicateOverEpilogue(), and llvm::shouldOptimizeForSize().
Referenced by llvm::LoopVectorizePass::processLoop(), and processLoopInVPlanNativePath().
getSignedIntOrFpConstant()
static Constant* getSignedIntOrFpConstant (Type * Ty, int64_t C) static
A helper function that returns an integer or floating-point constant with value C.
Definition at line 354 of file LoopVectorize.cpp.
References llvm::ConstantFP::get(), llvm::ConstantInt::getSigned(), and llvm::Type::isIntegerTy().
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps().
getSmallBestKnownTC()
static Optional<unsigned> getSmallBestKnownTC (ScalarEvolution & SE, Loop * L) static
Returns "best known" trip count for the specified loop L as defined by the following procedure: 1) Returns exact trip count if it is known.
2) Returns expected trip count according to profile data if any. 3) Returns upper bound estimate if it is known. 4) Returns None if all of the above failed.
Definition at line 365 of file LoopVectorize.cpp.
References llvm::getLoopEstimatedTripCount(), llvm::ScalarEvolution::getSmallConstantMaxTripCount(), llvm::ScalarEvolution::getSmallConstantTripCount(), LoopVectorizeWithBlockFrequency, and llvm::None.
Referenced by llvm::LoopVectorizePass::processLoop(), and llvm::LoopVectorizationCostModel::selectInterleaveCount().
hasIrregularType()
static bool hasIrregularType (Type * Ty, const DataLayout & DL, unsigned VF) static
A helper function that returns true if the given type is irregular.
The type is irregular if its allocated size doesn't equal the store size of an element of the corresponding vector type at the given vectorization factor.
Definition at line 318 of file LoopVectorize.cpp.
References llvm::VectorType::get(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeAllocSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), and llvm::DataLayout::getTypeStoreSize().
Referenced by llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), and llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened().
isExplicitVecOuterLoop()
static bool isExplicitVecOuterLoop (Loop * OuterLp, OptimizationRemarkEmitter * ORE) static
Definition at line 1537 of file LoopVectorize.cpp.
References assert(), llvm::dbgs(), llvm::LoopBase< BlockT, LoopT >::empty(), llvm::LoopVectorizeHints::FK_Undefined, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), and LLVM_DEBUG.
Referenced by collectSupportedLoops().
isStrideMul()
static bool isStrideMul (Instruction * I, LoopVectorizationLegality * Legal) static
Definition at line 5785 of file LoopVectorize.cpp.
References llvm::CallBase::arg_operands(), assert(), C, llvm::InnerLoopVectorizer::Cost, llvm::dyn_cast(), first, llvm::VectorType::get(), getAddressAccessSCEV(), llvm::TargetTransformInfo::getAddressComputationCost(), llvm::TargetTransformInfo::getGatherScatterOpCost(), llvm::TargetTransformInfo::getInterleavedMemoryOpCost(), llvm::getLoadStoreAddressSpace(), llvm::getLoadStoreAlignment(), llvm::getLoadStorePointerOperand(), llvm::TargetTransformInfo::getMaskedMemoryOpCost(), getMemInstValueType(), llvm::TargetTransformInfo::getMemoryOpCost(), llvm::TargetTransformInfo::getNumberOfParts(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::TargetTransformInfo::getOperandsScalarizationOverhead(), getReciprocalPredBlockProb(), llvm::TargetTransformInfo::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::PredicatedScalarEvolution::getSE(), llvm::TargetTransformInfo::getShuffleCost(), llvm::Value::getType(), llvm::StoreInst::getValueOperand(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::LoopVectorizationLegality::hasStride(), I, llvm::LoopVectorizationLegality::isConsecutivePtr(), llvm::LoopVectorizationLegality::isMaskRequired(), llvm::LoopVectorizationLegality::isUniform(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::InnerLoopVectorizer::Legal, llvm::SPII::Load, llvm::User::operands(), llvm::TargetTransformInfo::prefersVectorizedAddressing(), llvm::InnerLoopVectorizer::PSE, llvm::SmallVectorTemplateBase< T, bool >::push_back(), SI, llvm::TargetTransformInfo::SK_Broadcast, llvm::TargetTransformInfo::SK_Reverse, llvm::SPII::Store, llvm::TargetTransformInfo::supportsEfficientVectorElementLoadStore(), ToVectorTy(), llvm::InnerLoopVectorizer::TTI, and llvm::InnerLoopVectorizer::VF.
Referenced by llvm::LoopVectorizationCostModel::setCostBasedWideningDecision().
largestIntegerVectorType()
static Type* largestIntegerVectorType (Type * T1, Type * T2) static
Definition at line 3319 of file LoopVectorize.cpp.
References llvm::Type::getVectorElementType(), and T1.
Referenced by llvm::LoopVectorizationCostModel::setCostBasedWideningDecision().
mayDivideByZero()
static bool mayDivideByZero (Instruction & I) static
A helper function for checking whether an integer division-related instruction may divide by zero (in which case it must be predicated if executed conditionally in the scalar code).
TODO: It may be worthwhile to generalize and check isKnownNonZero(). Non-zero divisors that are non compile-time constants will not be converted into multiplication, so we will still end up scalarizing the division, but can do so w/o predication.
Definition at line 4195 of file LoopVectorize.cpp.
References assert(), llvm::dyn_cast(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), and llvm::ConstantInt::isZero().
Referenced by llvm::LoopVectorizationCostModel::isScalarWithPredication().
processLoopInVPlanNativePath()
static bool processLoopInVPlanNativePath (Loop * L, PredicatedScalarEvolution & PSE, LoopInfo * LI, DominatorTree * DT, LoopVectorizationLegality * LVL, TargetTransformInfo * TTI, TargetLibraryInfo * TLI, DemandedBits * DB, AssumptionCache * AC, OptimizationRemarkEmitter * ORE, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI, LoopVectorizeHints & Hints) static
Definition at line 7549 of file LoopVectorize.cpp.
References assert(), llvm::dbgs(), llvm::VectorizationFactor::Disabled(), llvm::InnerLoopVectorizer::DT, EnableVPlanNativePath, EnableVPlanPredication, llvm::LoopVectorizationPlanner::executePlan(), F(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getLAI(), llvm::Value::getName(), llvm::BasicBlock::getParent(), getScalarEpilogueLowering(), llvm::PredicatedScalarEvolution::getSE(), llvm::LoopVectorizeHints::getWidth(), LLVM_DEBUG, llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::LoopVectorizationPlanner::setBestPlan(), llvm::verifyFunction(), VPlanBuildStressTest, and llvm::VectorizationFactor::Width.
Referenced by llvm::LoopVectorizePass::processLoop().
smallestIntegerVectorType()
static Type* smallestIntegerVectorType (Type * T1, Type * T2) static
Definition at line 3314 of file LoopVectorize.cpp.
References llvm::Type::getVectorElementType(), and T1.
Referenced by llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), and llvm::InnerLoopVectorizer::truncateToMinimalBitwidths().
STATISTIC() [1/2]
STATISTIC (LoopsVectorized , "Number of loops vectorized")
STATISTIC() [2/2]
STATISTIC (LoopsAnalyzed , "Number of loops analyzed for vectorization")
ToVectorTy()
static Type* ToVectorTy (Type * Scalar, unsigned VF) static
A helper function for converting Scalar types to vector types.
If the incoming type is void, we return void. If the VF is 1, we return the scalar type.
Definition at line 300 of file LoopVectorize.cpp.
References llvm::VectorType::get(), and llvm::Type::isVoidTy().
Referenced by llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::isOptimizableIVTruncate(), isStrideMul(), and llvm::LoopVectorizationCostModel::setCostBasedWideningDecision().
useMaskedInterleavedAccesses()
static bool useMaskedInterleavedAccesses (const TargetTransformInfo & TTI) static
Definition at line 2133 of file LoopVectorize.cpp.
References llvm::TargetTransformInfo::enableMaskedInterleavedAccessVectorization(), and EnableMaskedInterleavedMemAccesses.
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizePass::processLoop(), and llvm::InnerLoopVectorizer::vectorizeInterleaveGroup().
Variable Documentation
EnableCondStoresVectorization
cl::opt<bool> EnableCondStoresVectorization("enable-cond-stores-vec", cl::init(true), cl::Hidden, cl::desc("Enable if predication of stores during vectorization.")) static
Referenced by llvm::LoopVectorizationCostModel::selectVectorizationFactor().
EnableIndVarRegisterHeur
cl::opt<bool> EnableIndVarRegisterHeur("enable-ind-var-reg-heur", cl::init(true), cl::Hidden, cl::desc("Count the induction variable only once when interleaving")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
EnableInterleavedMemAccesses
cl::opt<bool> EnableInterleavedMemAccesses("enable-interleaved-mem-accesses", cl::init(false), cl::Hidden, cl::desc("Enable vectorization on interleaved memory accesses in a loop")) static
Referenced by llvm::LoopVectorizePass::processLoop().
EnableLoadStoreRuntimeInterleave
cl::opt<bool> EnableLoadStoreRuntimeInterleave("enable-loadstore-runtime-interleave", cl::init(true), cl::Hidden, cl::desc("Enable runtime interleaving until load/store ports are saturated")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
EnableMaskedInterleavedMemAccesses
cl::opt<bool> EnableMaskedInterleavedMemAccesses("enable-masked-interleaved-mem-accesses", cl::init(false), cl::Hidden, cl::desc("Enable vectorization on masked interleaved memory accesses in a loop")) static
An interleave-group may need masking if it resides in a block that needs predication, or in order to mask away gaps.
Referenced by useMaskedInterleavedAccesses().
EnableVPlanNativePath
cl::opt<bool> EnableVPlanNativePath("enable-vplan-native-path", cl::init(false), cl::Hidden, cl::desc("Enable VPlan-native vectorization path with " "support for outer loop vectorization."))
Referenced by collectSupportedLoops(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::fixVectorizedLoop(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), llvm::LoopVectorizePass::run(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
EnableVPlanPredication
cl::opt<bool> EnableVPlanPredication("enable-vplan-predication", cl::init(false), cl::Hidden, cl::desc("Enable VPlan-native vectorization path predicator with " "support for outer loop vectorization."))
Referenced by processLoopInVPlanNativePath().
ForceTargetInstructionCost
cl::opt<unsigned> ForceTargetInstructionCost("force-target-instruction-cost", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's expected cost for " "an instruction to a single constant value. Mostly " "useful for getting consistent testing.")) static
Referenced by llvm::LoopVectorizationCostModel::collectInstsToScalarize().
ForceTargetMaxScalarInterleaveFactor
cl::opt<unsigned> ForceTargetMaxScalarInterleaveFactor("force-target-max-scalar-interleave", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's max interleave factor for " "scalar loops.")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
ForceTargetMaxVectorInterleaveFactor
cl::opt<unsigned> ForceTargetMaxVectorInterleaveFactor("force-target-max-vector-interleave", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's max interleave factor for " "vectorized loops.")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
ForceTargetNumScalarRegs
cl::opt<unsigned> ForceTargetNumScalarRegs("force-target-num-scalar-regs", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's number of scalar registers.")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
ForceTargetNumVectorRegs
cl::opt<unsigned> ForceTargetNumVectorRegs("force-target-num-vector-regs", cl::init(0), cl::Hidden, cl::desc("A flag that overrides the target's number of vector registers.")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
LLVMLoopVectorizeFollowupAll
const char* const LLVMLoopVectorizeFollowupAll static
Initial value:
=
    "llvm.loop.vectorize.followup_all"
Metadata attribute names
Definition at line 161 of file LoopVectorize.cpp.
Referenced by llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), and llvm::LoopVectorizePass::processLoop().
LLVMLoopVectorizeFollowupEpilogue
const char* const LLVMLoopVectorizeFollowupEpilogue static
Initial value:
=
    "llvm.loop.vectorize.followup_epilogue"
Definition at line 165 of file LoopVectorize.cpp.
LLVMLoopVectorizeFollowupVectorized
const char* const LLVMLoopVectorizeFollowupVectorized static
Initial value:
=
    "llvm.loop.vectorize.followup_vectorized"
Definition at line 163 of file LoopVectorize.cpp.
LoopVectorizeWithBlockFrequency
cl::opt<bool> LoopVectorizeWithBlockFrequency("loop-vectorize-with-block-frequency", cl::init(true), cl::Hidden, cl::desc("Enable the use of the block frequency analysis to access PGO " "heuristics minimizing code growth in cold regions and being more " "aggressive in hot regions.")) static
Referenced by getSmallBestKnownTC().
lv_name
const char lv_name[] = "Loop Vectorization" static
Definition at line 6384 of file LoopVectorize.cpp.
MaximizeBandwidth
cl::opt<bool> MaximizeBandwidth("vectorizer-maximize-bandwidth", cl::init(false), cl::Hidden, cl::desc("Maximize bandwidth when selecting vectorization factor which " "will be determined by the smallest type in loop.")) static
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF().
MaxNestedScalarReductionIC
cl::opt<unsigned> MaxNestedScalarReductionIC("max-nested-scalar-reduction-interleave", cl::init(2), cl::Hidden, cl::desc("The maximum interleave count to use when interleaving a scalar " "reduction in a nested loop.")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
NumberOfStoresToPredicate
cl::opt<unsigned> NumberOfStoresToPredicate("vectorize-num-stores-pred", cl::init(1), cl::Hidden, cl::desc("Max number of stores to be predicated behind an if.")) static
The number of stores in a loop that are allowed to need predication.
Referenced by llvm::LoopVectorizationCostModel::calculateRegisterUsage().
PreferPredicateOverEpilog
cl::opt<bool> PreferPredicateOverEpilog("prefer-predicate-over-epilog", cl::init(false), cl::Hidden, cl::desc("Indicate that an epilogue is undesired, predication should be " "used instead.")) static
Referenced by getScalarEpilogueLowering().
SmallLoopCost
cl::opt<unsigned> SmallLoopCost("small-loop-cost", cl::init(20), cl::Hidden, cl::desc("The cost of a loop that is considered 'small' by the interleaver.")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
TinyTripCountInterleaveThreshold
cl::opt<unsigned> TinyTripCountInterleaveThreshold("tiny-trip-count-interleave-threshold", cl::init(128), cl::Hidden, cl::desc("We don't interleave loops with a estimated constant trip count " "below this number")) static
Referenced by llvm::LoopVectorizationCostModel::selectInterleaveCount().
TinyTripCountVectorThreshold
cl::opt<unsigned> TinyTripCountVectorThreshold("vectorizer-min-trip-count", cl::init(16), cl::Hidden, cl::desc("Loops with a constant trip count that is smaller than this " "value are vectorized only if no scalar iteration overheads " "are incurred.")) static
Loops with a known constant trip count below this number are vectorized only if no scalar iteration overheads are incurred.
Referenced by llvm::LoopVectorizePass::processLoop().
VPlanBuildStressTest
cl::opt<bool> VPlanBuildStressTest("vplan-build-stress-test", cl::init(false), cl::Hidden, cl::desc("Build VPlan for every supported loop nest in the function and bail " "out right after the build (stress test the VPlan H-CFG construction " "in the VPlan-native vectorization path).")) static
Referenced by collectSupportedLoops(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), and processLoopInVPlanNativePath().