LLVM: lib/Transforms/Scalar/LoopUnswitch.cpp File Reference
LoopUnswitch.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/LoopPassManager.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <algorithm>
#include <cassert>
#include <map>
#include <set>
#include <tuple>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "loop-unswitch"
Enumerations
enum OperatorChain { OC_OpChainNone, OC_OpChainOr, OC_OpChainAnd, OC_OpChainMixed }
Operator chain lattice.
Functions
STATISTIC (NumBranches, "Number of branches unswitched")
STATISTIC (NumSwitches, "Number of switches unswitched")
STATISTIC (NumGuards, "Number of guards unswitched")
STATISTIC (NumSelects, "Number of selects unswitched")
STATISTIC (NumTrivial, "Number of unswitches that are trivial")
STATISTIC (NumSimplify, "Number of simplifications of unswitched code")
STATISTIC (TotalInsts, "Total number of instructions analyzed")
INITIALIZE_PASS_BEGIN (LoopUnswitch, "loop-unswitch", "Unswitch loops", false, false) INITIALIZE_PASS_END(LoopUnswitch
static Value * FindLIVLoopCondition (Value *Cond, Loop *L, bool &Changed, OperatorChain &ParentChain, DenseMap< Value *, Value *> &Cache, MemorySSAUpdater *MSSAU)
Cond is a condition that occurs in L.
static std::pair< Value *, OperatorChain > FindLIVLoopCondition (Value *Cond, Loop *L, bool &Changed, MemorySSAUpdater *MSSAU)
Cond is a condition that occurs in L.
static bool EqualityPropUnSafe (Value &LoopCond)
FIXME: Remove this workaround when freeze related patches are done.
static bool isTrivialLoopExitBlockHelper (Loop *L, BasicBlock *BB, BasicBlock *&ExitBB, std::set< BasicBlock *> &Visited)
Check to see if all paths from BB exit the loop with no side effects (including infinite loops).
static BasicBlock * isTrivialLoopExitBlock (Loop *L, BasicBlock *BB)
Return true if the specified block unconditionally leads to an exit from the specified loop, and has no side-effects in the process.
static Loop * CloneLoop (Loop *L, Loop *PL, ValueToValueMapTy &VM, LoopInfo *LI, LPPassManager *LPM)
Recursively clone the specified loop and all of its children, mapping the blocks with the specified map.
static void RemoveFromWorklist (Instruction *I, std::vector< Instruction *> &Worklist)
Remove all instances of I from the worklist vector specified.
static void ReplaceUsesOfWith (Instruction *I, Value *V, std::vector< Instruction *> &Worklist, Loop *L, LPPassManager *LPM, MemorySSAUpdater *MSSAU)
When we find that I really equals V, remove I from the program, replacing all uses with V and update the worklist.
Variables
static cl::opt< unsigned > Threshold ("loop-unswitch-threshold", cl::desc("Max loop size to unswitch"), cl::init(100), cl::Hidden)
loop unswitch
loop Unswitch loops
loop Unswitch false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-unswitch"
Definition at line 85 of file LoopUnswitch.cpp.
Enumeration Type Documentation
OperatorChain
enum OperatorChain
Operator chain lattice.
Enumerator
OC_OpChainNone
There is no operator.
OC_OpChainOr
There are only ORs.
OC_OpChainAnd
There are only ANDs.
OC_OpChainMixed
There are ANDs and ORs.
Definition at line 404 of file LoopUnswitch.cpp.
Function Documentation
CloneLoop()
static Loop* CloneLoop (Loop * L, Loop * PL, ValueToValueMapTy & VM, LoopInfo * LI, LPPassManager * LPM) static
Recursively clone the specified loop and all of its children, mapping the blocks with the specified map.
Definition at line 908 of file LoopUnswitch.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LPPassManager::addLoop(), llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop(), llvm::LoopInfoBase< BlockT, LoopT >::AllocateLoop(), llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates(), assert(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::DominatorTreeBase< BasicBlock, false >::Delete, E, llvm::Value::getContext(), llvm::Type::getInt1Ty(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Instruction::getParent(), llvm::BranchInst::getSuccessor(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), I, llvm::CmpInst::ICMP_EQ, llvm::DominatorTreeBase< BasicBlock, false >::Insert, llvm::BranchInst::isUnconditional(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Instruction::removeFromParent(), llvm::SplitCriticalEdge(), std::swap(), and llvm::Instruction::swapProfMetadata().
EqualityPropUnSafe()
static bool EqualityPropUnSafe (Value & LoopCond) static
FIXME: Remove this workaround when freeze related patches are done.
LoopUnswitch and Equality propagation in GVN have discrepancy about whether branch on undef/poison has undefine behavior. Here it is to rule out some common cases that we found such discrepancy already causing problems. Detail could be found in PR31652. Note if the func returns true, it is unsafe. But if it is false, it doesn't mean it is necessarily safe.
Definition at line 594 of file LoopUnswitch.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::SwitchInst::cases(), Context, llvm::dyn_cast(), E, FindLIVLoopCondition(), first, llvm::Constant::getAllOnesValue(), llvm::SwitchInst::getCondition(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Constant::getNullValue(), llvm::SwitchInst::getNumCases(), llvm::User::getOperand(), llvm::BasicBlock::getParent(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::LoopBase< BlockT, LoopT >::hasDedicatedExits(), llvm::Function::hasFnAttribute(), I, llvm::ICmpInst::isEquality(), llvm::SimpleLoopSafetyInfo::isGuaranteedToExecute(), llvm::Loop::isSafeToClone(), OC_OpChainAnd, OC_OpChainNone, OC_OpChainOr, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PPCISD::SC, and SI.
FindLIVLoopCondition() [1/2]
static Value* FindLIVLoopCondition (Value * Cond, Loop * L, bool & Changed, OperatorChain & ParentChain, DenseMap< Value *, Value *> & Cache, MemorySSAUpdater * MSSAU) static
Cond is a condition that occurs in L.
If it is invariant in the loop, or has an invariant piece, return the invariant. Otherwise, return null. NOTE: FindLIVLoopCondition will not return a partial LIV by walking up a mixed operator chain, as we can not reliably find a value which will simplify the operator chain. If the chain is AND-only or OR-only, we can use 0 or ~0 to simplify the chain.
NOTE: In case a partial LIV and a mixed operator chain, we may be able to simplify the condition itself to a loop variant condition, but at the cost of creating an entirely new loop.
Definition at line 422 of file LoopUnswitch.cpp.
Referenced by EqualityPropUnSafe().
FindLIVLoopCondition() [2/2]
static std::pair<Value *, OperatorChain> FindLIVLoopCondition (Value * Cond, Loop * L, bool & Changed, MemorySSAUpdater * MSSAU) static
Cond is a condition that occurs in L.
If it is invariant in the loop, or has an invariant piece, return the invariant along with the operator chain type. Otherwise, return null.
Definition at line 506 of file LoopUnswitch.cpp.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopUnswitch , "loop-unswitch" , "Unswitch loops" , false , false)
isTrivialLoopExitBlock()
static BasicBlock* isTrivialLoopExitBlock (Loop * L, BasicBlock * BB) static
Return true if the specified block unconditionally leads to an exit from the specified loop, and has no side-effects in the process.
If so, return the block that is exited to, otherwise return null.
Definition at line 869 of file LoopUnswitch.cpp.
References llvm::dbgs(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Value::getName(), isTrivialLoopExitBlockHelper(), and LLVM_DEBUG.
isTrivialLoopExitBlockHelper()
static bool isTrivialLoopExitBlockHelper (Loop * L, BasicBlock * BB, BasicBlock *& ExitBB, std::set< BasicBlock *> & Visited) static
Check to see if all paths from BB exit the loop with no side effects (including infinite loops).
If true, we return true and set ExitBB to the block we exit through.
Definition at line 834 of file LoopUnswitch.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), E, I, SI, llvm::succ_begin(), and llvm::succ_end().
Referenced by isTrivialLoopExitBlock().
RemoveFromWorklist()
static void RemoveFromWorklist (Instruction * I, std::vector< Instruction *> & Worklist) static
Remove all instances of I from the worklist vector specified.
Definition at line 1407 of file LoopUnswitch.cpp.
References I, and llvm::sys::fs::remove().
Referenced by ReplaceUsesOfWith().
ReplaceUsesOfWith()
static void ReplaceUsesOfWith (Instruction * I, Value * V, std::vector< Instruction *> & Worklist, Loop * L, LPPassManager * LPM, MemorySSAUpdater * MSSAU) static
When we find that I really equals V, remove I from the program, replacing all uses with V and update the worklist.
Definition at line 1416 of file LoopUnswitch.cpp.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock(), assert(), llvm::BasicBlock::begin(), llvm::SwitchInst::case_default(), llvm::LoopBase< BlockT, LoopT >::contains(), Context, llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::dbgs(), llvm::LPPassManager::deleteSimpleAnalysisValue(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::numbers::e, E, llvm::DomTreeUpdater::Eager, llvm::Instruction::eraseFromParent(), llvm::SwitchInst::findCaseDest(), llvm::SwitchInst::findCaseValue(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::getCaseSuccessor(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::ConstantInt::getFalse(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Type::getInt1Ty(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BasicBlock::getModule(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::CmpInst::getPredicate(), llvm::BasicBlock::getSinglePredecessor(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), I, llvm::CmpInst::ICMP_EQ, llvm::ICmpInst::isEquality(), llvm::isInstructionTriviallyDead(), llvm::Type::isIntegerTy(), LLVM_DEBUG, llvm::Instruction::mayHaveSideEffects(), llvm::MergeBlockIntoPredecessor(), RemoveFromWorklist(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::Value::replaceAllUsesWith(), llvm::LoopInfo::replacementPreservesLCSSAForm(), llvm::User::replaceUsesOfWith(), llvm::SimplifyInstruction(), llvm::SplitEdge(), llvm::succ_begin(), and llvm::Value::users().
STATISTIC() [1/7]
STATISTIC (NumBranches , "Number of branches unswitched")
STATISTIC() [2/7]
STATISTIC (NumSwitches , "Number of switches unswitched")
STATISTIC() [3/7]
STATISTIC (NumGuards , "Number of guards unswitched")
STATISTIC() [4/7]
STATISTIC (NumSelects , "Number of selects unswitched")
STATISTIC() [5/7]
STATISTIC (NumTrivial , "Number of unswitches that are trivial")
STATISTIC() [6/7]
STATISTIC (NumSimplify , "Number of simplifications of unswitched code")
STATISTIC() [7/7]
STATISTIC (TotalInsts , "Total number of instructions analyzed")
Variable Documentation
false
loop Unswitch false
Definition at line 396 of file LoopUnswitch.cpp.
loops
loop Unswitch loops
Definition at line 396 of file LoopUnswitch.cpp.
Threshold
cl::opt<unsigned> Threshold("loop-unswitch-threshold", cl::desc("Max loop size to unswitch"), cl::init(100), cl::Hidden) static
Referenced by checkBias(), computeImportForFunction(), ComputeImportForModule(), llvm::createX86PadShortFunctions(), llvm::emitThumbRegPlusImmediate(), llvm::BitstreamWriter::EmitVBR(), llvm::BitstreamWriter::EmitVBR64(), llvm::sampleprof::FunctionSamples::findInlinedFunctions(), llvm::HexagonFrameLowering::getAlignaInstr(), getBranchHint(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::InlineCost::getThreshold(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), hoistAndMergeSGPRInits(), IncorporateWeight(), isPointerValueDeadOnEntryToFunction(), llvm::LoopRotation(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::PatternMatch::m_SpecificInt_ICMP(), mayLoopAccessLocation(), llvm::InlineCost::operator bool(), llvm::LoopRotatePass::run(), llvm::SimplifyCFGPass::run(), selectCallee(), llvm::LLVMContext::setDiagnosticsHotnessThreshold(), and tryToUnrollLoop().
unswitch
loop unswitch
Definition at line 396 of file LoopUnswitch.cpp.