LLVM: lib/Transforms/Scalar/LoopStrengthReduce.cpp File Reference
LoopStrengthReduce.cpp File Reference
#include "llvm/Transforms/Scalar/LoopStrengthReduce.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/IVUsers.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ScalarEvolutionNormalization.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/OperandTraits.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <limits>
#include <map>
#include <numeric>
#include <utility>
Macros
#define DEBUG_TYPE "loop-reduce"
Functions
static void DoInitialMatch (const SCEV *S, Loop *L, SmallVectorImpl< const SCEV *> &Good, SmallVectorImpl< const SCEV *> &Bad, ScalarEvolution &SE)
Recursion helper for initialMatch.
static bool isAddRecSExtable (const SCEVAddRecExpr *AR, ScalarEvolution &SE)
Return true if the given addrec can be sign-extended without changing its value.
static bool isAddSExtable (const SCEVAddExpr *A, ScalarEvolution &SE)
Return true if the given add can be sign-extended without changing its value.
static bool isMulSExtable (const SCEVMulExpr *M, ScalarEvolution &SE)
Return true if the given mul can be sign-extended without changing its value.
static const SCEV * getExactSDiv (const SCEV *LHS, const SCEV *RHS, ScalarEvolution &SE, bool IgnoreSignificantBits=false)
Return an expression for LHS /s RHS, if it can be determined and if the remainder is known to be zero, or null otherwise.
static int64_t ExtractImmediate (const SCEV *&S, ScalarEvolution &SE)
If S involves the addition of a constant integer value, return that integer value, and mutate S to point to a new SCEV with that value excluded.
static GlobalValue * ExtractSymbol (const SCEV *&S, ScalarEvolution &SE)
If S involves the addition of a GlobalValue address, return that symbol, and mutate S to point to a new SCEV with that value excluded.
static bool isAddressUse (const TargetTransformInfo &TTI, Instruction *Inst, Value *OperandVal)
Returns true if the specified instruction is using the specified value as an address.
static MemAccessTy getAccessType (const TargetTransformInfo &TTI, Instruction *Inst, Value *OperandVal)
Return the type of the memory being accessed.
static bool isExistingPhi (const SCEVAddRecExpr *AR, ScalarEvolution &SE)
Return true if this AddRec is already a phi in its loop.
static bool isHighCostExpansion (const SCEV *S, SmallPtrSetImpl< const SCEV *> &Processed, ScalarEvolution &SE)
Check if expanding this expression is likely to incur significant cost.
static bool DeleteTriviallyDeadInstructions (SmallVectorImpl< WeakTrackingVH > &DeadInsts)
If any of the instructions in the specified set are trivially dead, delete them and see if this makes any of their operands subsequently dead.
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, const LSRUse &LU, const Formula &F)
Check if the addressing mode defined by F is completely folded in LU at isel time.
static unsigned getScalingFactorCost (const TargetTransformInfo &TTI, const LSRUse &LU, const Formula &F, const Loop &L)
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, Instruction *Fixup=nullptr)
static unsigned getSetupCost (const SCEV *Reg, unsigned Depth)
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale)
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula &F, const Loop &L)
static bool isLegalUse (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale)
Test whether we know how to expand the current formula.
static bool isLegalUse (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula &F)
static bool isAlwaysFoldable (const TargetTransformInfo &TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg)
static bool isAlwaysFoldable (const TargetTransformInfo &TTI, ScalarEvolution &SE, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const SCEV *S, bool HasBaseReg)
static User::op_iterator findIVOperand (User::op_iterator OI, User::op_iterator OE, Loop *L, ScalarEvolution &SE)
Helper for CollectChains that finds an IV operand (computed by an AddRec in this loop) within [OI,OE) or returns OE.
static Value * getWideOperand (Value *Oper)
IVChain logic must consistently peek base TruncInst operands, so wrap it in a convenient helper.
static bool isCompatibleIVType (Value *LVal, Value *RVal)
Return true if we allow an IV chain to include both types.
static const SCEV * getExprBase (const SCEV *S)
Return an approximation of this SCEV expression's "base", or NULL for any constant.
static bool isProfitableChain (IVChain &Chain, SmallPtrSetImpl< Instruction *> &Users, ScalarEvolution &SE)
Return true if the number of registers needed for the chain is estimated to be less than the number required for the individual IV users.
static bool canFoldIVIncExpr (const SCEV *IncExpr, Instruction *UserInst, Value *Operand, const TargetTransformInfo &TTI)
Return true if the IVInc can be folded into an addressing mode.
static const SCEV * CollectSubexprs (const SCEV *S, const SCEVConstant *C, SmallVectorImpl< const SCEV *> &Ops, const Loop *L, ScalarEvolution &SE, unsigned Depth=0)
Split S into subexpressions which can be pulled out into separate registers.
static bool mayUsePostIncMode (const TargetTransformInfo &TTI, LSRUse &LU, const SCEV *S, const Loop *L, ScalarEvolution &SE)
Return true if the SCEV represents a value that may end up as a post-increment operation.
static bool ReduceLoopStrength (Loop *L, IVUsers &IU, ScalarEvolution &SE, DominatorTree &DT, LoopInfo &LI, const TargetTransformInfo &TTI, AssumptionCache &AC, TargetLibraryInfo &LibInfo)
INITIALIZE_PASS_BEGIN (LoopStrengthReduce, "loop-reduce", "Loop Strength Reduction", false, false) INITIALIZE_PASS_END(LoopStrengthReduce
Variables
static const unsigned MaxIVUsers = 200
MaxIVUsers is an arbitrary threshold that provides an early opportunity for bail out.
static cl::opt< bool > EnablePhiElim ("enable-lsr-phielim", cl::Hidden, cl::init(true), cl::desc("Enable LSR phi elimination"))
static cl::opt< bool > InsnsCost ("lsr-insns-cost", cl::Hidden, cl::init(true), cl::desc("Add instruction count to a LSR cost model"))
static cl::opt< bool > LSRExpNarrow ("lsr-exp-narrow", cl::Hidden, cl::init(false), cl::desc("Narrow LSR complex solution using" " expectation of registers number"))
static cl::opt< bool > FilterSameScaledReg ("lsr-filter-same-scaled-reg", cl::Hidden, cl::init(true), cl::desc("Narrow LSR search space by filtering non-optimal formulae" " with the same ScaledReg and Scale"))
static cl::opt< bool > EnableBackedgeIndexing ("lsr-backedge-indexing", cl::Hidden, cl::init(true), cl::desc("Enable the generation of cross iteration indexed memops"))
static cl::opt< unsigned > ComplexityLimit ("lsr-complexity-limit", cl::Hidden, cl::init(std::numeric_limits< uint16_t >::max()), cl::desc("LSR search space complexity limit"))
static cl::opt< unsigned > SetupCostDepthLimit ("lsr-setupcost-depth-limit", cl::Hidden, cl::init(7), cl::desc("The limit on recursion depth for LSRs setup cost"))
static cl::opt< bool > StressIVChain ("stress-ivchain", cl::Hidden, cl::init(false), cl::desc("Stress test LSR IV chains"))
loop reduce
loop Loop Strength Reduction
loop Loop Strength false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-reduce"
Definition at line 125 of file LoopStrengthReduce.cpp.
Referenced by mayUsePostIncMode(), and ReduceLoopStrength().
Function Documentation
canFoldIVIncExpr()
static bool canFoldIVIncExpr (const SCEV * IncExpr, Instruction * UserInst, Value * Operand, const TargetTransformInfo & TTI) static
Return true if the IVInc can be folded into an addressing mode.
Definition at line 3119 of file LoopStrengthReduce.cpp.
References llvm::Address, assert(), llvm::codeview::Basic, C, llvm::TargetTransformInfo::canSaveCmp(), llvm::SCEVExpander::clearPostInc(), llvm::LoopBase< BlockT, LoopT >::contains(), D, llvm::dbgs(), llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SCEVExpander::expandCodeFor(), F(), llvm::find(), findIVOperand(), getAccessType(), llvm::ScalarEvolution::getAddExpr(), llvm::SCEVConstant::getAPInt(), llvm::BranchInst::getCondition(), llvm::Instruction::getDebugLoc(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueNumForOperand(), llvm::APInt::getMinSignedBits(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::ScalarEvolution::getSCEV(), llvm::ConstantInt::getSExtValue(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getUnknown(), llvm::SCEVConstant::getValue(), getWideOperand(), llvm::ScalarEvolution::hasComputableLoopEvolution(), llvm::SmallVectorImpl< T >::insert(), isAddressUse(), isAlwaysFoldable(), isCompatibleIVType(), llvm::Instruction::isEHPad(), isLegalUse(), llvm::ScalarEvolution::isLoopInvariant(), llvm::Type::isPointerTy(), llvm::isSafeToExpand(), llvm::ScalarEvolution::isSCEVable(), llvm::SCEV::isZero(), LLVM_DEBUG, N, llvm::normalizeForPostIncUse(), llvm::User::op_end(), llvm::User::operands(), P, Rewriter, llvm::IRBuilderBase::SetCurrentDebugLocation(), and llvm::Value::uses().
CollectSubexprs()
static const SCEV* CollectSubexprs (const SCEV * S, const SCEVConstant * C, SmallVectorImpl< const SCEV *> & Ops, const Loop * L, ScalarEvolution & SE, unsigned Depth = 0) static
Split S into subexpressions which can be pulled out into separate registers.
If C is non-null, multiply each subexpression by C.
Return remainder expression after factoring the subexpressions captured by Ops. If Ops is complete, return NULL.
Definition at line 3486 of file LoopStrengthReduce.cpp.
References llvm::MCID::Add, C, llvm::Depth, llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getMulExpr(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by mayUsePostIncMode().
DeleteTriviallyDeadInstructions()
static bool DeleteTriviallyDeadInstructions (SmallVectorImpl< WeakTrackingVH > & DeadInsts) static
If any of the instructions in the specified set are trivially dead, delete them and see if this makes any of their operands subsequently dead.
Definition at line 968 of file LoopStrengthReduce.cpp.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::Address, assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorTemplateCommon< T >::begin(), C, llvm::dump(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Instruction::eraseFromParent(), F(), Fixup, getScalingFactorCost(), llvm::hash_combine_range(), llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::Insns, isAMCompletelyFolded(), llvm::isEqual(), llvm::isInstructionTriviallyDead(), llvm::max(), llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::RISCVFenceField::O, llvm::User::operands(), llvm::Other, llvm::SmallVectorImpl< T >::pop_back_val(), print(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
Referenced by mayUsePostIncMode(), and ReduceLoopStrength().
DoInitialMatch()
static void DoInitialMatch (const SCEV * S, Loop * L, SmallVectorImpl< const SCEV *> & Good, SmallVectorImpl< const SCEV *> & Bad, ScalarEvolution & SE) static
Recursion helper for initialMatch.
Definition at line 390 of file LoopStrengthReduce.cpp.
References llvm::MCID::Add, assert(), dump(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::errs(), llvm::find_if(), llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::Constant::getAllOnesValue(), llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getSCEV(), getType(), llvm::is_contained(), isCanonical(), llvm::SCEV::isZero(), LLVM_DUMP_METHOD, llvm::make_range(), print(), llvm::ScalarEvolution::properlyDominates(), llvm::SmallVectorTemplateBase< T >::push_back(), and std::swap().
ExtractImmediate()
static int64_t ExtractImmediate (const SCEV *& S, ScalarEvolution & SE) static
If S involves the addition of a constant integer value, return that integer value, and mutate S to point to a new SCEV with that value excluded.
Definition at line 746 of file LoopStrengthReduce.cpp.
References llvm::MCID::Add, C, llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getConstant(), and llvm::Value::getType().
Referenced by isAlwaysFoldable(), and mayUsePostIncMode().
ExtractSymbol()
static GlobalValue* ExtractSymbol (const SCEV *& S, ScalarEvolution & SE) static
If S involves the addition of a GlobalValue address, return that symbol, and mutate S to point to a new SCEV with that value excluded.
Definition at line 772 of file LoopStrengthReduce.cpp.
References llvm::MCID::Add, llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), and llvm::ScalarEvolution::getConstant().
Referenced by isAlwaysFoldable(), and mayUsePostIncMode().
findIVOperand()
static User::op_iterator findIVOperand (User::op_iterator OI, User::op_iterator OE, Loop * L, ScalarEvolution & SE) static
Helper for CollectChains that finds an IV operand (computed by an AddRec in this loop) within [OI,OE) or returns OE.
If IVUsers mapped Instructions to IVStrideUses, we could partially skip this.
Definition at line 2719 of file LoopStrengthReduce.cpp.
References llvm::ScalarEvolution::getSCEV(), and llvm::ScalarEvolution::isSCEVable().
Referenced by canFoldIVIncExpr(), and isProfitableChain().
getAccessType()
static MemAccessTy getAccessType (const TargetTransformInfo & TTI, Instruction * Inst, Value * OperandVal) static
Return the type of the memory being accessed.
Definition at line 838 of file LoopStrengthReduce.cpp.
References llvm::IntegerType::get(), llvm::PointerType::get(), llvm::Type::getPointerAddressSpace(), llvm::TargetTransformInfo::getTgtMemIntrinsic(), llvm::Value::getType(), prefetch, llvm::MemIntrinsicInfo::PtrVal, SI, and UnknownAddressSpace.
Referenced by canFoldIVIncExpr().
getExactSDiv()
static const SCEV* getExactSDiv (const SCEV * LHS, const SCEV * RHS, ScalarEvolution & SE, bool IgnoreSignificantBits = false) static
Return an expression for LHS /s RHS, if it can be determined and if the remainder is known to be zero, or null otherwise.
If IgnoreSignificantBits is true, expressions like (X * Y) /s Y are simplified to Y, ignoring that the multiplication may overflow, which is useful when the result will be used in a context where the most significant bits are ignored.
Definition at line 659 of file LoopStrengthReduce.cpp.
References C, llvm::dyn_cast(), llvm::SCEVConstant::getAPInt(), llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEV::getType(), isAddRecSExtable(), llvm::APInt::isAllOnesValue(), RA, llvm::APInt::sdiv(), and llvm::APInt::srem().
Referenced by mayUsePostIncMode().
getExprBase()
static const SCEV* getExprBase (const SCEV * S) static
Return an approximation of this SCEV expression's "base", or NULL for any constant.
Returning the expression itself is conservative. Returning a deeper subexpression is more precise and valid as long as it isn't less complex than another subexpression. For expressions involving multiple unscaled values, we need to return the pointer-type SCEVUnknown. This avoids forming chains across objects, such as: PrevOper==a[i], IVOper==b[i], IVInc==b-a.
Since SCEVUnknown is the rightmost type, and pointers are the rightmost SCEVUnknown, we simply return the rightmost SCEV operand.
Definition at line 2766 of file LoopStrengthReduce.cpp.
References llvm::MCID::Add, E, llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getSCEV(), llvm::SCEV::getSCEVType(), getWideOperand(), I, isHighCostExpansion(), llvm::SCEVNAryExpr::op_begin(), llvm::SCEVNAryExpr::op_end(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scMulExpr, llvm::scSignExtend, llvm::scTruncate, and llvm::scZeroExtend.
Referenced by isProfitableChain().
getScalingFactorCost()
static unsigned getScalingFactorCost (const TargetTransformInfo & TTI, const LSRUse & LU, const Formula & F, const Loop & L) static
Definition at line 1759 of file LoopStrengthReduce.cpp.
References llvm::Address, assert(), llvm::codeview::Basic, llvm::TargetTransformInfo::getScalingFactorCost(), isAMCompletelyFolded(), llvm_unreachable, and llvm::max().
Referenced by DeleteTriviallyDeadInstructions(), llvm::X86TargetLowering::getInlineAsmMemConstraint(), llvm::AArch64TargetLowering::getMaxSupportedInterleaveFactor(), getSetupCost(), and llvm::ARMTargetLowering::isSelectSupported().
getSetupCost()
static unsigned getSetupCost (const SCEV * Reg, unsigned Depth) static
Definition at line 1216 of file LoopStrengthReduce.cpp.
References llvm::Address, assert(), C, llvm::TargetTransformInfo::canMacroFuseCmp(), llvm::SmallPtrSetImplBase::clear(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::count(), llvm::SmallPtrSetImpl< PtrType >::count(), dump(), llvm::numbers::e, llvm::errs(), Fixup, llvm::APInt::getMinSignedBits(), llvm::TargetTransformInfo::getNumberOfRegisters(), llvm::TargetTransformInfo::getRegisterClassForType(), getScalingFactorCost(), llvm::ScalarEvolution::hasComputableLoopEvolution(), if(), llvm::SmallPtrSetImpl< PtrType >::insert(), InsnsCost, isAMCompletelyFolded(), isExistingPhi(), llvm::TargetTransformInfo::isIndexedLoadLegal(), llvm::TargetTransformInfo::isIndexedStoreLegal(), llvm::ScalarEvolution::isLoopInvariant(), llvm::TargetTransformInfo::isLSRCostLess(), llvm::SCEV::isZero(), LLVM_DUMP_METHOD, llvm::max(), llvm::TargetTransformInfo::MIM_PostInc, llvm::RISCVFenceField::O, llvm::Other, print(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, SetupCostDepthLimit, llvm::TargetTransformInfo::shouldFavorBackedgeIndex(), llvm::TargetTransformInfo::shouldFavorPostInc(), llvm::sort(), llvm::SPII::Store, and std::swap().
getWideOperand()
static Value* getWideOperand (Value * Oper) static
IVChain logic must consistently peek base TruncInst operands, so wrap it in a convenient helper.
Definition at line 2738 of file LoopStrengthReduce.cpp.
Referenced by canFoldIVIncExpr(), getExprBase(), and isProfitableChain().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopStrengthReduce , "loop-reduce" , "Loop Strength Reduction" , false , false)
Referenced by llvm::LoopStrengthReducePass::run().
isAddRecSExtable()
static bool isAddRecSExtable (const SCEVAddRecExpr * AR, ScalarEvolution & SE) static
Return true if the given addrec can be sign-extended without changing its value.
Definition at line 631 of file LoopStrengthReduce.cpp.
References llvm::IntegerType::get(), llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVNAryExpr::getType(), and llvm::ScalarEvolution::getTypeSizeInBits().
Referenced by getExactSDiv().
isAddressUse()
static bool isAddressUse (const TargetTransformInfo & TTI, Instruction * Inst, Value * OperandVal) static
Returns true if the specified instruction is using the specified value as an address.
Definition at line 798 of file LoopStrengthReduce.cpp.
References llvm::TargetTransformInfo::getTgtMemIntrinsic(), prefetch, llvm::MemIntrinsicInfo::PtrVal, and SI.
Referenced by canFoldIVIncExpr().
isAddSExtable()
static bool isAddSExtable (const SCEVAddExpr * A, ScalarEvolution & SE) static
Return true if the given add can be sign-extended without changing its value.
Definition at line 639 of file LoopStrengthReduce.cpp.
References llvm::IntegerType::get(), llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVAddExpr::getType(), and llvm::ScalarEvolution::getTypeSizeInBits().
isAlwaysFoldable() [1/2]
static bool isAlwaysFoldable (const TargetTransformInfo & TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg) static
Definition at line 1796 of file LoopStrengthReduce.cpp.
References isAMCompletelyFolded().
Referenced by canFoldIVIncExpr(), and mayUsePostIncMode().
isAlwaysFoldable() [2/2]
static bool isAlwaysFoldable (const TargetTransformInfo & TTI, ScalarEvolution & SE, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const SCEV * S, bool HasBaseReg) static
Definition at line 1818 of file LoopStrengthReduce.cpp.
References add(), assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::sys::path::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), E, llvm::SmallVectorBase::empty(), llvm::sys::path::end(), llvm::SmallVectorTemplateCommon< T >::end(), ExtractImmediate(), ExtractSymbol(), isAMCompletelyFolded(), llvm::SCEV::isZero(), llvm::RISCVFenceField::O, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), and X.
isAMCompletelyFolded() [1/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, const LSRUse & LU, const Formula & F) static
Check if the addressing mode defined by F is completely folded in LU at isel time.
This includes address-mode folding and special icmp tricks. This function returns true if LU can accommodate what F defines and up to 1 base + 1 scaled + offset. In other words, if F has several base registers, this function may still return true. Therefore, users still need to account for additional base registers and/or unfolded offsets to derive an accurate cost model.
Definition at line 1742 of file LoopStrengthReduce.cpp.
References llvm::Address, Fixup, and llvm::TargetTransformInfo::LSRWithInstrQueries().
Referenced by DeleteTriviallyDeadInstructions(), getScalingFactorCost(), getSetupCost(), isAlwaysFoldable(), isAMCompletelyFolded(), isLegalUse(), and mayUsePostIncMode().
isAMCompletelyFolded() [2/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, Instruction * Fixup = nullptr) static
Definition at line 1629 of file LoopStrengthReduce.cpp.
References llvm::Address, llvm::codeview::Basic, llvm::TargetTransformInfo::isLegalAddressingMode(), llvm::TargetTransformInfo::isLegalICmpImmediate(), and llvm_unreachable.
isAMCompletelyFolded() [3/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale) static
Definition at line 1683 of file LoopStrengthReduce.cpp.
References isAMCompletelyFolded().
isAMCompletelyFolded() [4/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula & F, const Loop & L) static
Definition at line 1704 of file LoopStrengthReduce.cpp.
References assert(), and isAMCompletelyFolded().
isCompatibleIVType()
static bool isCompatibleIVType (Value * LVal, Value * RVal) static
Return true if we allow an IV chain to include both types.
Definition at line 2745 of file LoopStrengthReduce.cpp.
References llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and llvm::Type::isPointerTy().
Referenced by canFoldIVIncExpr(), and isProfitableChain().
isExistingPhi()
static bool isExistingPhi (const SCEVAddRecExpr * AR, ScalarEvolution & SE) static
Return true if this AddRec is already a phi in its loop.
Definition at line 884 of file LoopStrengthReduce.cpp.
References llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getSCEV(), llvm::SCEVNAryExpr::getType(), llvm::ScalarEvolution::isSCEVable(), and llvm::BasicBlock::phis().
Referenced by getSetupCost(), and isHighCostExpansion().
isHighCostExpansion()
static bool isHighCostExpansion (const SCEV * S, SmallPtrSetImpl< const SCEV *> & Processed, ScalarEvolution & SE) static
Check if expanding this expression is likely to incur significant cost.
This is tricky because SCEV doesn't track which expressions are actually computed by the current IR.
We currently allow expansion of IV increments that involve adds, multiplication by constants, and AddRecs from existing phis.
TODO: Allow UDivExpr if we can find an existing IV increment that is an obvious multiple of the UDivExpr.
Definition at line 904 of file LoopStrengthReduce.cpp.
References llvm::MCID::Add, llvm::dyn_cast(), llvm::Instruction::getOpcode(), llvm::ScalarEvolution::getSCEV(), llvm::SCEV::getSCEVType(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), isExistingPhi(), llvm::ScalarEvolution::isSCEVable(), llvm::scConstant, llvm::scSignExtend, llvm::scTruncate, llvm::scUnknown, llvm::scZeroExtend, and llvm::Value::users().
Referenced by getExprBase().
isLegalUse() [1/2]
static bool isLegalUse (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale) static
Test whether we know how to expand the current formula.
Definition at line 1721 of file LoopStrengthReduce.cpp.
References isAMCompletelyFolded().
Referenced by canFoldIVIncExpr(), isLegalUse(), and mayUsePostIncMode().
isLegalUse() [2/2]
static bool isLegalUse (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula & F) static
Definition at line 1735 of file LoopStrengthReduce.cpp.
References isLegalUse().
isMulSExtable()
static bool isMulSExtable (const SCEVMulExpr * M, ScalarEvolution & SE) static
Return true if the given mul can be sign-extended without changing its value.
Definition at line 647 of file LoopStrengthReduce.cpp.
References llvm::IntegerType::get(), llvm::ScalarEvolution::getContext(), llvm::SCEVNAryExpr::getNumOperands(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVNAryExpr::getType(), and llvm::ScalarEvolution::getTypeSizeInBits().
isProfitableChain()
static bool isProfitableChain (IVChain & Chain, SmallPtrSetImpl< Instruction *> & Users, ScalarEvolution & SE) static
Return true if the number of registers needed for the chain is estimated to be less than the number required for the individual IV users.
First prohibit any IV users that keep the IV live across increments (the Users set should be empty). Next count the number and type of increments in the chain.
Chaining IVs can lead to considerable code bloat if ISEL doesn't effectively use postinc addressing modes. Only consider it profitable it the increments can be computed in fewer registers when chained.
TODO: Consider IVInc free if it's already used in another chains.
Definition at line 2834 of file LoopStrengthReduce.cpp.
References assert(), llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::SmallPtrSetImplBase::clear(), llvm::dbgs(), llvm::dyn_cast(), llvm::SmallPtrSetImplBase::empty(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::find(), findIVOperand(), for(), llvm::DomTreeNodeBase< NodeT >::getBlock(), getExprBase(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getSCEV(), llvm::Value::getType(), getWideOperand(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::insert(), isCompatibleIVType(), llvm::ScalarEvolution::isLoopInvariant(), llvm::ScalarEvolution::isSCEVable(), llvm::SCEV::isZero(), LLVM_DEBUG, llvm::BasicBlock::phis(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::reverse(), and llvm::Value::users().
mayUsePostIncMode()
static bool mayUsePostIncMode (const TargetTransformInfo & TTI, LSRUse & LU, const SCEV * S, const Loop * L, ScalarEvolution & SE) static
Return true if the SCEV represents a value that may end up as a post-increment operation.
Definition at line 3544 of file LoopStrengthReduce.cpp.
References llvm::abs(), llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addPreservedID(), llvm::AnalysisUsage::addRequired(), llvm::AnalysisUsage::addRequiredID(), llvm::Address, llvm::SmallVectorImpl< T >::append(), llvm::array_lengthof(), assert(), llvm::codeview::Basic, llvm::sys::path::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::PHINode::blocks(), C, llvm::SmallPtrSetImplBase::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SCEVExpander::clear(), llvm::SmallSet< T, N, C >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::SCEVExpander::clearPostInc(), CollectSubexprs(), ComplexityLimit, llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallBitVector::count(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::count(), llvm::countTrailingZeros(), llvm::CastInst::Create(), llvm::dbgs(), DEBUG_TYPE, DeleteTriviallyDeadInstructions(), llvm::denormalizeForPostIncUse(), llvm::Depth, llvm::SCEVExpander::disableCanonicalMode(), dump(), llvm::dump(), llvm::dyn_cast(), llvm::numbers::e, E, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), llvm::IVUsers::empty(), llvm::LoopBase< BlockT, LoopT >::empty(), EnableBackedgeIndexing, llvm::SCEVExpander::enableLSRMode(), llvm::sys::path::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::errs(), llvm::SCEVExpander::expandCodeFor(), ExtractImmediate(), ExtractSymbol(), F(), FilterSameScaledReg, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), first, Fixup, for(), G, llvm::ConstantInt::get(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAnyExtendExpr(), llvm::PHINode::getBasicBlockIndex(), llvm::ConstantExpr::getCast(), llvm::CastInst::getCastOpcode(), llvm::ScalarEvolution::getConstant(), llvm::Module::getDataLayout(), llvm::ScalarEvolution::getEffectiveSCEVType(), getExactSDiv(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::BasicBlock::getFirstNonPHI(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::DomTreeNodeBase< NodeT >::getIDom(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::SCEVAddRecExpr::getLoop(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getModule(), llvm::ScalarEvolution::getMulExpr(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getNumSuccessors(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::PassRegistry::getPassRegistry(), llvm::Type::getScalarSizeInBits(), llvm::ScalarEvolution::getSCEV(), llvm::APInt::getSExtValue(), llvm::ConstantInt::getSigned(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::BasicBlock::getTerminator(), llvm::SCEVConstant::getType(), llvm::SCEV::getType(), llvm::SCEVNAryExpr::getType(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getUnknown(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), llvm::ScalarEvolution::hasComputableLoopEvolution(), I, if(), llvm::PHINode::incoming_values(), llvm::initializeLoopStrengthReducePass(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::is_contained(), isAlwaysFoldable(), isAMCompletelyFolded(), llvm::TargetTransformInfo::isIndexedLoadLegal(), llvm::TargetTransformInfo::isIndexedStoreLegal(), llvm::SCEVExpander::isInsertedInstruction(), llvm::BasicBlock::isLandingPad(), llvm::TargetTransformInfo::isLegalAddImmediate(), isLegalUse(), llvm::ScalarEvolution::isLoopInvariant(), llvm::Loop::isLoopSimplifyForm(), llvm::APInt::isNegative(), llvm::Type::isPointerTy(), llvm::TargetTransformInfo::isTruncateFree(), llvm::ConstantInt::isValueValidForType(), llvm::SCEV::isZero(), llvm::AArch64CC::LE, LLVM_DEBUG, LLVM_DUMP_METHOD, llvm::Log2_32(), Loops, llvm::LoopSimplifyID, LSRExpNarrow, llvm::TargetTransformInfo::MIM_PostInc, llvm::BasicBlock::moveBefore(), N, llvm::AArch64CC::NE, P, llvm::SmallVectorTemplateBase< T >::pop_back(), print(), llvm::Value::printAsOperand(), llvm::ScalarEvolution::properlyDominates(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::SmallVectorImpl< T >::reserve(), Rewriter, llvm::PPCISD::SC, llvm::SmallBitVector::set_bits(), llvm::SCEVExpander::setChainedPhi(), llvm::SCEVExpander::setDebugType(), llvm::PHINode::setIncomingValue(), llvm::SCEVExpander::setInsertPoint(), llvm::SCEVExpander::setIVIncInsertPos(), llvm::User::setOperand(), llvm::SCEVExpander::setPostInc(), llvm::TargetTransformInfo::shouldFavorBackedgeIndex(), llvm::TargetTransformInfo::shouldFavorPostInc(), llvm::SmallVectorBase::size(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::size(), llvm::sort(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), and std::swap().
ReduceLoopStrength()
static bool ReduceLoopStrength (Loop * L, IVUsers & IU, ScalarEvolution & SE, DominatorTree & DT, LoopInfo & LI, const TargetTransformInfo & TTI, AssumptionCache & AC, TargetLibraryInfo & LibInfo) static
Definition at line 5707 of file LoopStrengthReduce.cpp.
References DEBUG_TYPE, llvm::DeleteDeadPHIs(), DeleteTriviallyDeadInstructions(), EnablePhiElim, llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getModule(), llvm::BasicBlock::getParent(), llvm::Loop::isLoopSimplifyForm(), llvm::SCEVExpander::replaceCongruentIVs(), Rewriter, and llvm::SCEVExpander::setDebugType().
Referenced by llvm::LoopStrengthReducePass::run().
Variable Documentation
ComplexityLimit
cl::opt<unsigned> ComplexityLimit("lsr-complexity-limit", cl::Hidden, cl::init(std::numeric_limits< uint16_t >::max()), cl::desc("LSR search space complexity limit")) static
Referenced by mayUsePostIncMode().
EnableBackedgeIndexing
cl::opt<bool> EnableBackedgeIndexing("lsr-backedge-indexing", cl::Hidden, cl::init(true), cl::desc("Enable the generation of cross iteration indexed memops")) static
Referenced by mayUsePostIncMode().
EnablePhiElim
cl::opt<bool> EnablePhiElim("enable-lsr-phielim", cl::Hidden, cl::init(true), cl::desc("Enable LSR phi elimination")) static
Referenced by ReduceLoopStrength().
false
loop Loop Strength false
Definition at line 5774 of file LoopStrengthReduce.cpp.
FilterSameScaledReg
cl::opt<bool> FilterSameScaledReg("lsr-filter-same-scaled-reg", cl::Hidden, cl::init(true), cl::desc("Narrow LSR search space by filtering non-optimal formulae" " with the same ScaledReg and Scale")) static
Referenced by mayUsePostIncMode().
InsnsCost
cl::opt<bool> InsnsCost("lsr-insns-cost", cl::Hidden, cl::init(true), cl::desc("Add instruction count to a LSR cost model")) static
Referenced by getSetupCost().
LSRExpNarrow
cl::opt<bool> LSRExpNarrow("lsr-exp-narrow", cl::Hidden, cl::init(false), cl::desc("Narrow LSR complex solution using" " expectation of registers number")) static
Referenced by mayUsePostIncMode().
MaxIVUsers
const unsigned MaxIVUsers = 200 static
MaxIVUsers is an arbitrary threshold that provides an early opportunity for bail out.
This threshold is far beyond the number of users that LSR can conceivably solve, so it should not affect generated code, but catches the worst cases before LSR burns too much compile time and stack space.
Definition at line 131 of file LoopStrengthReduce.cpp.
reduce
loop reduce
Definition at line 5774 of file LoopStrengthReduce.cpp.
Referenced by llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleUpdateCosts(), and llvm::PBQP::RegAlloc::RegAllocSolverImpl::solve().
Reduction
loop Loop Strength Reduction
Definition at line 5774 of file LoopStrengthReduce.cpp.
Referenced by AreSequentialAccesses(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), and llvm::VPRecipeBuilder::tryToCreateRecipe().
SetupCostDepthLimit
cl::opt<unsigned> SetupCostDepthLimit("lsr-setupcost-depth-limit", cl::Hidden, cl::init(7), cl::desc("The limit on recursion depth for LSRs setup cost")) static
Referenced by getSetupCost().
StressIVChain
cl::opt<bool> StressIVChain("stress-ivchain", cl::Hidden, cl::init(false), cl::desc("Stress test LSR IV chains")) static