LLVM: lib/Transforms/IPO/LoopExtractor.cpp File Reference
LoopExtractor.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/CodeExtractor.h"
#include <fstream>
#include <set>
Classes
struct false::SingleLoopExtractor
SingleLoopExtractor - For bugpoint.
Namespaces
false
Macros
#define DEBUG_TYPE "loop-extract"
Functions
STATISTIC (NumExtracted, "Number of loops extracted")
INITIALIZE_PASS_BEGIN (LoopExtractor, "loop-extract", "Extract loops into new functions", false, false) INITIALIZE_PASS_END(LoopExtractor
INITIALIZE_PASS (SingleLoopExtractor, "loop-extract-single", "Extract at most one loop into a new function", false, false) Pass *llvm
Variables
loop extract
loop Extract loops into new functions
loop Extract loops into new false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-extract"
Definition at line 34 of file LoopExtractor.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (SingleLoopExtractor , "loop-extract-single" , "Extract at most one loop into a new function" , false , false)
Definition at line 78 of file LoopExtractor.cpp.
References llvm::numbers::e, llvm::LoopInfo::erase(), llvm::CodeExtractor::extractCodeRegion(), llvm::Function::getEntryBlock(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::Instruction::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Loop::isLoopSimplifyForm(), llvm::LPPassManager::markLoopAsDeleted(), and llvm::SmallVectorBase::size().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopExtractor , "loop-extract" , "Extract loops into new functions" , false , false)
STATISTIC()
STATISTIC (NumExtracted , "Number of loops extracted")
Variable Documentation
extract
loop extract
Definition at line 66 of file LoopExtractor.cpp.
Referenced by llvm::DWARFListType< RangeListEntry >::clear(), llvm::DWARFContext::dump(), llvm::mdconst::extract(), llvm::DWARFListTableBase< DWARFDebugRnglist >::extractHeaderAndOffsets(), llvm::DWARFListTableHeader::getOffsetEntry(), and llvm::BitTracker::RegisterCell::operator[]().
false
loop Extract loops into new false
Definition at line 66 of file LoopExtractor.cpp.
functions
loop Extract loops into new functions
Definition at line 66 of file LoopExtractor.cpp.