LLVM: lib/Transforms/Utils/LoopUtils.cpp File Reference
LoopUtils.cpp File Reference
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/MustExecute.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionAliasAnalysis.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "loop-utils"
Functions
static MDNode * createStringMetadata (Loop *TheLoop, StringRef Name, unsigned V)
Create MDNode for input string.
static Optional< bool > getOptionalBoolLoopAttribute (const Loop *TheLoop, StringRef Name)
static bool getBooleanLoopAttribute (const Loop *TheLoop, StringRef Name)
Variables
static const char * LLVMLoopDisableNonforced = "llvm.loop.disable_nonforced"
static const char * LLVMLoopDisableLICM = "llvm.licm.disable"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-utils"
Definition at line 46 of file LoopUtils.cpp.
Function Documentation
createStringMetadata()
static MDNode* createStringMetadata (Loop * TheLoop, StringRef Name, unsigned V) static
Create MDNode for input string.
Definition at line 200 of file LoopUtils.cpp.
References Context, llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), and llvm::Type::getInt32Ty().
getBooleanLoopAttribute()
static bool getBooleanLoopAttribute (const Loop * TheLoop, StringRef Name) static
Definition at line 284 of file LoopUtils.cpp.
References getOptionalBoolLoopAttribute(), and llvm::Optional< T >::getValueOr().
Referenced by llvm::hasDisableAllTransformsHint(), llvm::hasDisableLICMTransformsHint(), llvm::hasDistributeTransformation(), llvm::hasLICMVersioningTransformation(), llvm::hasUnrollAndJamTransformation(), llvm::hasUnrollTransformation(), and llvm::hasVectorizeTransformation().
getOptionalBoolLoopAttribute()
static Optional<bool> getOptionalBoolLoopAttribute (const Loop * TheLoop, StringRef Name) static
Definition at line 266 of file LoopUtils.cpp.
References llvm::findOptionMDForLoop(), llvm::MDOperand::get(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm_unreachable, and llvm::None.
Referenced by getBooleanLoopAttribute(), and llvm::hasVectorizeTransformation().
Variable Documentation
LLVMLoopDisableLICM
const char* LLVMLoopDisableLICM = "llvm.licm.disable" static
Definition at line 49 of file LoopUtils.cpp.
LLVMLoopDisableNonforced
const char* LLVMLoopDisableNonforced = "llvm.loop.disable_nonforced" static
Definition at line 48 of file LoopUtils.cpp.