LLVM: lib/Transforms/Scalar/LoopInstSimplify.cpp File Reference
LoopInstSimplify.cpp File Reference
#include "llvm/Transforms/Scalar/LoopInstSimplify.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/User.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include <algorithm>
#include <utility>
Macros
#define DEBUG_TYPE "loop-instsimplify"
Functions
STATISTIC (NumSimplified, "Number of redundant instructions simplified")
static bool simplifyLoopInst (Loop &L, DominatorTree &DT, LoopInfo &LI, AssumptionCache &AC, const TargetLibraryInfo &TLI, MemorySSAUpdater *MSSAU)
INITIALIZE_PASS_BEGIN (LoopInstSimplifyLegacyPass, "loop-instsimplify", "Simplify instructions in loops", false, false) INITIALIZE_PASS_END(LoopInstSimplifyLegacyPass
Variables
loop instsimplify
loop Simplify instructions in loops
loop Simplify instructions in false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-instsimplify"
Definition at line 47 of file LoopInstSimplify.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopInstSimplifyLegacyPass , "loop-instsimplify" , "Simplify instructions in loops" , false , false)
Referenced by llvm::LoopInstSimplifyPass::run().
simplifyLoopInst()
static bool simplifyLoopInst (Loop & L, DominatorTree & DT, LoopInfo & LI, AssumptionCache & AC, const TargetLibraryInfo & TLI, MemorySSAUpdater * MSSAU) static
Definition at line 51 of file LoopInstSimplify.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), assert(), llvm::SmallPtrSetImplBase::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImplBase::empty(), llvm::EnableMSSALoopDependency, llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopAnalysisUsage(), llvm::MemorySSA::getMemoryAccess(), llvm::MemorySSAUpdater::getMemorySSA(), llvm::BasicBlock::getModule(), llvm::BasicBlock::getParent(), llvm::PassRegistry::getPassRegistry(), llvm::Optional< T >::getPointer(), llvm::Use::getUser(), llvm::SimplifyQuery::getWithInstruction(), llvm::Optional< T >::hasValue(), I, llvm::initializeLoopInstSimplifyLegacyPassPass(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isInstructionTriviallyDead(), llvm::LoopBlocksRPO::perform(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::LoopInfo::replacementPreservesLCSSAForm(), llvm::Use::set(), llvm::AnalysisUsage::setPreservesCFG(), llvm::SimplifyInstruction(), std::swap(), llvm::VerifyMemorySSA, and llvm::MemorySSA::verifyMemorySSA().
Referenced by llvm::LoopInstSimplifyPass::run().
STATISTIC()
STATISTIC (NumSimplified , "Number of redundant instructions simplified")
Variable Documentation
false
loop Simplify instructions in false
Definition at line 252 of file LoopInstSimplify.cpp.
instsimplify
loop instsimplify
Definition at line 252 of file LoopInstSimplify.cpp.
loops
loop Simplify instructions in loops
Definition at line 252 of file LoopInstSimplify.cpp.