LLVM: lib/Transforms/Scalar/LowerWidenableCondition.cpp File Reference
LowerWidenableCondition.cpp File Reference
#include "llvm/Transforms/Scalar/LowerWidenableCondition.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/GuardUtils.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/GuardUtils.h"
Functions
static bool lowerWidenableCondition (Function &F)
INITIALIZE_PASS (LowerWidenableConditionLegacyPass, "lower-widenable-condition", "Lower the widenable condition to default true value", false, false) Pass *llvm
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LowerWidenableConditionLegacyPass , "lower-widenable-condition" , "Lower the widenable condition to default true value" , false , false)
Definition at line 72 of file LowerWidenableCondition.cpp.
lowerWidenableCondition()
static bool lowerWidenableCondition (Function & F) static
Definition at line 43 of file LowerWidenableCondition.cpp.
References llvm::SmallVectorBase::empty(), F(), llvm::Module::getFunction(), llvm::Intrinsic::getName(), llvm::GlobalValue::getParent(), llvm::ConstantInt::getTrue(), I, llvm::instructions(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T >::push_back(), and runOnFunction().
Referenced by llvm::LowerWidenableConditionPass::run().