LLVM: lib/Transforms/Scalar/LowerGuardIntrinsic.cpp File Reference
LowerGuardIntrinsic.cpp File Reference
#include "llvm/Transforms/Scalar/LowerGuardIntrinsic.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/GuardUtils.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/GuardUtils.h"
Functions
static bool lowerGuardIntrinsic (Function &F)
INITIALIZE_PASS (LowerGuardIntrinsicLegacyPass, "lower-guard-intrinsic", "Lower the guard intrinsic to normal control flow", false, false) Pass *llvm
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LowerGuardIntrinsicLegacyPass , "lower-guard-intrinsic" , "Lower the guard intrinsic to normal control flow" , false , false)
Definition at line 76 of file LowerGuardIntrinsic.cpp.
lowerGuardIntrinsic()
static bool lowerGuardIntrinsic (Function & F) static
Definition at line 43 of file LowerGuardIntrinsic.cpp.
References llvm::SmallVectorBase::empty(), F(), llvm::Intrinsic::getDeclaration(), llvm::Module::getFunction(), llvm::Intrinsic::getName(), llvm::GlobalValue::getParent(), llvm::Function::getReturnType(), I, llvm::instructions(), llvm::isGuard(), llvm::makeGuardControlFlowExplicit(), llvm::SmallVectorTemplateBase< T >::push_back(), runOnFunction(), and llvm::Function::setCallingConv().
Referenced by llvm::LowerGuardIntrinsicPass::run().