LLVM: lib/Transforms/Scalar/LowerAtomic.cpp File Reference
LowerAtomic.cpp File Reference
#include "llvm/Transforms/Scalar/LowerAtomic.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
Macros
#define DEBUG_TYPE "loweratomic"
Functions
static bool LowerAtomicCmpXchgInst (AtomicCmpXchgInst *CXI)
static bool LowerAtomicRMWInst (AtomicRMWInst *RMWI)
static bool LowerFenceInst (FenceInst *FI)
static bool LowerLoadInst (LoadInst *LI)
static bool LowerStoreInst (StoreInst *SI)
static bool runOnBasicBlock (BasicBlock &BB)
static bool lowerAtomics (Function &F)
INITIALIZE_PASS (LowerAtomicLegacyPass, "loweratomic", "Lower atomic intrinsics to non-atomic form", false, false) Pass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loweratomic"
Definition at line 22 of file LowerAtomic.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LowerAtomicLegacyPass , "loweratomic" , "Lower atomic intrinsics to non-atomic form" , false , false)
Definition at line 175 of file LowerAtomic.cpp.
LowerAtomicCmpXchgInst()
static bool LowerAtomicCmpXchgInst (AtomicCmpXchgInst * CXI) static
Definition at line 24 of file LowerAtomic.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateInsertValue(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::object::Equal, llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::AtomicCmpXchgInst::getCompareOperand(), llvm::AtomicCmpXchgInst::getNewValOperand(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::Value::getType(), and llvm::Value::replaceAllUsesWith().
Referenced by runOnBasicBlock().
LowerAtomicRMWInst()
static bool LowerAtomicRMWInst (AtomicRMWInst * RMWI) static
Definition at line 43 of file LowerAtomic.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFSub(), llvm::IRBuilder< T, Inserter >::CreateICmpSLT(), llvm::IRBuilder< T, Inserter >::CreateICmpULT(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::Instruction::eraseFromParent(), llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::AtomicRMWInst::getOperation(), llvm::AtomicRMWInst::getPointerOperand(), llvm::Value::getType(), llvm::AtomicRMWInst::getValOperand(), llvm_unreachable, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::Value::replaceAllUsesWith(), llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
Referenced by runOnBasicBlock().
lowerAtomics()
static bool lowerAtomics (Function & F) static
Definition at line 139 of file LowerAtomic.cpp.
References runOnBasicBlock().
Referenced by llvm::LowerAtomicPass::run().
LowerFenceInst()
static bool LowerFenceInst (FenceInst * FI) static
Definition at line 103 of file LowerAtomic.cpp.
References llvm::Instruction::eraseFromParent().
Referenced by runOnBasicBlock().
LowerLoadInst()
static bool LowerLoadInst (LoadInst * LI) static
Definition at line 108 of file LowerAtomic.cpp.
References llvm::NotAtomic, and llvm::LoadInst::setAtomic().
Referenced by runOnBasicBlock().
LowerStoreInst()
static bool LowerStoreInst (StoreInst * SI) static
Definition at line 113 of file LowerAtomic.cpp.
References llvm::NotAtomic, and llvm::StoreInst::setAtomic().
Referenced by runOnBasicBlock().
runOnBasicBlock()
static bool runOnBasicBlock (BasicBlock & BB) static
Definition at line 118 of file LowerAtomic.cpp.
References llvm::BasicBlock::begin(), llvm::BasicBlock::end(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), LowerFenceInst(), LowerLoadInst(), LowerStoreInst(), and SI.
Referenced by lowerAtomics().