LLVM: lib/Transforms/Utils/LowerInvoke.cpp File Reference
LowerInvoke.cpp File Reference
#include "llvm/Transforms/Utils/LowerInvoke.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils.h"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "lowerinvoke"
Functions
STATISTIC (NumInvokes, "Number of invokes replaced")
INITIALIZE_PASS (LowerInvokeLegacyPass, "lowerinvoke", "Lower invoke and unwind, for unwindless code generators", false, false) static bool runImpl(Function &F)
FunctionPass * llvm::createLowerInvokePass ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lowerinvoke"
Definition at line 27 of file LowerInvoke.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LowerInvokeLegacyPass , "lowerinvoke" , "Lower invoke and unwind, for unwindless code generators" , false , false) &
Definition at line 43 of file LowerInvoke.cpp.
References llvm::CallInst::Create(), llvm::BranchInst::Create(), F(), runImpl(), runOnFunction(), llvm::CallBase::setAttributes(), llvm::CallBase::setCallingConv(), llvm::Instruction::setDebugLoc(), and llvm::Value::takeName().
STATISTIC()
STATISTIC (NumInvokes , "Number of invokes replaced")