LLVM: lib/CodeGen/LowerEmuTLS.cpp File Reference
LowerEmuTLS.cpp File Reference
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "loweremutls"
Functions
INITIALIZE_PASS (LowerEmuTLS, DEBUG_TYPE, "Add __emutls_[vt]. variables for emultated TLS model", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loweremutls"
Definition at line 27 of file LowerEmuTLS.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LowerEmuTLS , DEBUG_TYPE , "Add __emutls_. variables for emultated TLS model" [vt], false , false)
Definition at line 56 of file LowerEmuTLS.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::SmallVectorImpl< T >::append(), assert(), C, llvm::StructType::create(), llvm::dyn_cast(), G, llvm::ConstantInt::get(), llvm::ConstantStruct::get(), llvm::ConstantPointerNull::get(), llvm::DataLayout::getABITypeAlignment(), llvm::GlobalObject::getAlignment(), llvm::Module::getContext(), llvm::Module::getDataLayout(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt8PtrTy(), llvm::DataLayout::getIntPtrType(), llvm::Value::getName(), llvm::Module::getNamedGlobal(), llvm::Module::getOrInsertGlobal(), llvm::Value::getType(), llvm::DataLayout::getTypeStoreSize(), llvm::PointerType::getUnqual(), llvm::GlobalValue::getValueType(), llvm::Module::globals(), llvm::GlobalVariable::hasInitializer(), llvm::ConstantInt::isZero(), llvm::max(), llvm::GlobalObject::setAlignment(), llvm::GlobalVariable::setConstant(), llvm::GlobalVariable::setInitializer(), and llvm::SystemZISD::TM.