LLVM: lib/LTO/LTOBackend.cpp File Reference
LTOBackend.cpp File Reference
#include "llvm/LTO/LTOBackend.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/RemarkStreamer.h"
#include "llvm/IR/Verifier.h"
#include "llvm/LTO/LTO.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Object/ModuleSymbolTable.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/StandardInstrumentations.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/SmallVectorMemoryBuffer.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/Scalar/LoopPassManager.h"
#include "llvm/Transforms/Utils/FunctionImportUtils.h"
#include "llvm/Transforms/Utils/SplitModule.h"
Functions
static LLVM_ATTRIBUTE_NORETURN void reportOpenError (StringRef Path, Twine Msg)
static Error finalizeOptimizationRemarks (std::unique_ptr< ToolOutputFile > DiagOutputFile)
static void dropDeadSymbols (Module &Mod, const GVSummaryMapTy &DefinedGlobals, const ModuleSummaryIndex &Index)
Function Documentation
dropDeadSymbols()
static void dropDeadSymbols (Module & Mod, const GVSummaryMapTy & DefinedGlobals, const ModuleSummaryIndex & Index) static
Definition at line 481 of file LTOBackend.cpp.
References llvm::convertToDeclaration(), llvm::Module::global_values(), llvm::ModuleSummaryIndex::isGlobalValueLive(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by llvm::lto::thinBackend().
finalizeOptimizationRemarks()
static Error finalizeOptimizationRemarks (std::unique_ptr< ToolOutputFile > DiagOutputFile) static
Definition at line 438 of file LTOBackend.cpp.
References llvm::Error::success().
Referenced by llvm::lto::backend(), and llvm::lto::thinBackend().
reportOpenError()
static LLVM_ATTRIBUTE_NORETURN void reportOpenError (StringRef Path, Twine Msg) static
Definition at line 51 of file LTOBackend.cpp.
References llvm::errs(), and llvm::raw_ostream::flush().
Referenced by llvm::lto::Config::addSaveTemps().