LLVM: lib/LTO/LTOModule.cpp File Reference
LTOModule.cpp File Reference
#include "llvm/LTO/legacy/LTOModule.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include <system_error>
Functions
static ErrorOr< std::unique_ptr< Module > > parseBitcodeFileImpl (MemoryBufferRef Buffer, LLVMContext &Context, bool ShouldBeLazy)
Function Documentation
parseBitcodeFileImpl()
static ErrorOr<std::unique_ptr<Module> > parseBitcodeFileImpl (MemoryBufferRef Buffer, LLVMContext & Context, bool ShouldBeLazy) static
Definition at line 169 of file LTOModule.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::object::arch_not_found, llvm::Target::createTargetMachine(), E, llvm::LLVMContext::emitError(), llvm::errorToErrorCode(), llvm::expectedToErrorOrAndEmitErrors(), llvm::Triple::getArch(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::sys::getDefaultTargetTriple(), llvm::ErrorOr< T >::getError(), llvm::getLazyBitcodeModule(), llvm::SubtargetFeatures::getString(), llvm::Triple::isOSDarwin(), llvm::TargetRegistry::lookupTarget(), llvm::make_error_code(), llvm::None, llvm::parseBitcodeFile(), llvm::MipsISD::Ret, llvm::Expected< T >::takeError(), llvm::Triple::x86, and llvm::Triple::x86_64.