LLVM: lib/CodeGen/MachineCopyPropagation.cpp File Reference
MachineCopyPropagation.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugCounter.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <iterator>
Macros
#define DEBUG_TYPE "machine-cp"
Functions
STATISTIC (NumDeletes, "Number of dead copies deleted")
STATISTIC (NumCopyForwards, "Number of copy uses forwarded")
STATISTIC (NumCopyBackwardPropagated, "Number of copy defs backward propagated")
DEBUG_COUNTER (FwdCounter, "machine-cp-fwd", "Controls which register COPYs are forwarded")
INITIALIZE_PASS (MachineCopyPropagation, DEBUG_TYPE, "Machine Copy Propagation Pass", false, false) void MachineCopyPropagation
static bool isNopCopy (const MachineInstr &PreviousCopy, unsigned Src, unsigned Def, const TargetRegisterInfo *TRI)
Return true if PreviousCopy did copy register Src to register Def.
static bool isBackwardPropagatableCopy (MachineInstr &MI, const MachineRegisterInfo &MRI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-cp"
Definition at line 77 of file MachineCopyPropagation.cpp.
Function Documentation
DEBUG_COUNTER()
DEBUG_COUNTER (FwdCounter , "machine-cp-fwd" , "Controls which register COPYs are forwarded")
INITIALIZE_PASS()
INITIALIZE_PASS (MachineCopyPropagation , DEBUG_TYPE , "Machine Copy Propagation Pass" , false , false)
Definition at line 307 of file MachineCopyPropagation.cpp.
References llvm::dbgs(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and LLVM_DEBUG.
isBackwardPropagatableCopy()
static bool isBackwardPropagatableCopy (MachineInstr & MI, const MachineRegisterInfo & MRI) static
Definition at line 733 of file MachineCopyPropagation.cpp.
References assert(), llvm::dbgs(), E, llvm::MachineInstr::eraseFromParent(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getName(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineInstr::isCopy(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRenamable(), llvm::MachineRegisterInfo::isReserved(), llvm::MachineOperand::isTied(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), LLVM_DEBUG, llvm::MachineInstr::operands(), llvm::printReg(), llvm::MachineBasicBlock::rbegin(), llvm::TargetRegisterInfo::regsOverlap(), llvm::MachineBasicBlock::rend(), llvm::MachineOperand::setIsRenamable(), llvm::MachineOperand::setReg(), and TRI.
isNopCopy()
static bool isNopCopy (const MachineInstr & PreviousCopy, unsigned Src, unsigned Def, const TargetRegisterInfo * TRI) static
Return true if PreviousCopy did copy register Src to register Def.
This fact may have been obscured by sub register usage or may not be true at all even though Src and Def are subregisters of the registers used in PreviousCopy. e.g. isNopCopy("ecx = COPY eax", AX, CX) == true isNopCopy("ecx = COPY eax", AH, CL) == false
Definition at line 333 of file MachineCopyPropagation.cpp.
References assert(), llvm::SetVector< T, Vector, Set >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineInstr::clearRegisterKills(), llvm::MachineOperand::clobbersPhysReg(), llvm::TargetRegisterClass::contains(), llvm::dbgs(), llvm::MachineInstr::definesRegister(), llvm::MachineInstr::dump(), E, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getName(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::getRegClassConstraint(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::TargetRegisterClass::getSuperClasses(), I, llvm::MachineInstr::implicit_operands(), llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRenamable(), llvm::MachineRegisterInfo::isReserved(), llvm::MCRegisterInfo::isSubRegister(), llvm::MachineOperand::isTied(), llvm::MachineOperand::isUndef(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, llvm::make_range(), llvm::MachineInstr::modifiesRegister(), llvm::MachineInstr::operands(), llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::TargetRegisterInfo::regsOverlap(), llvm::MachineOperand::setIsRenamable(), llvm::MachineOperand::setReg(), llvm::DebugCounter::shouldExecute(), llvm::MachineBasicBlock::succ_empty(), TRI, llvm::MachineRegisterInfo::updateDbgUsersToReg(), and llvm::MachineInstr::uses().
STATISTIC() [1/3]
STATISTIC (NumDeletes , "Number of dead copies deleted")
STATISTIC() [2/3]
STATISTIC (NumCopyForwards , "Number of copy uses forwarded")
STATISTIC() [3/3]
STATISTIC (NumCopyBackwardPropagated , "Number of copy defs backward propagated")