LLVM: lib/CodeGen/MachineRegisterInfo.cpp File Reference
MachineRegisterInfo.cpp File Reference
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/LowLevelType.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Functions
static const TargetRegisterClass * constrainRegClass (MachineRegisterInfo &MRI, unsigned Reg, const TargetRegisterClass *OldRC, const TargetRegisterClass *RC, unsigned MinNumRegs)
static const Function * getCalledFunction (const MachineInstr &MI)
static bool isNoReturnDef (const MachineOperand &MO)
Variables
static cl::opt< bool > EnableSubRegLiveness ("enable-subreg-liveness", cl::Hidden, cl::init(true), cl::desc("Enable subregister liveness tracking."))
Function Documentation
constrainRegClass()
static const TargetRegisterClass* constrainRegClass (MachineRegisterInfo & MRI, unsigned Reg, const TargetRegisterClass * OldRC, const TargetRegisterClass * RC, unsigned MinNumRegs) static
Definition at line 69 of file MachineRegisterInfo.cpp.
References llvm::TargetRegisterInfo::getCommonSubClass(), llvm::TargetRegisterClass::getNumRegs(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), and llvm::MachineRegisterInfo::setRegClass().
Referenced by llvm::MachineRegisterInfo::constrainRegClass().
getCalledFunction()
static const Function* getCalledFunction (const MachineInstr & MI) static
Definition at line 557 of file MachineRegisterInfo.cpp.
References llvm::dyn_cast(), and llvm::MachineInstr::operands().
Referenced by isNoReturnDef().
isNoReturnDef()
static bool isNoReturnDef (const MachineOperand & MO) static
Definition at line 568 of file MachineRegisterInfo.cpp.
References getCalledFunction(), llvm::MachineFunction::getFunction(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::Function::hasFnAttribute(), llvm::MachineInstr::isCall(), MI, and llvm::MachineBasicBlock::succ_empty().
Referenced by llvm::MachineRegisterInfo::isPhysRegModified().
Variable Documentation
EnableSubRegLiveness
cl::opt<bool> EnableSubRegLiveness("enable-subreg-liveness", cl::Hidden, cl::init(true), cl::desc("Enable subregister liveness tracking.")) static