LLVM: lib/Object/MachOObjectFile.cpp File Reference
MachOObjectFile.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/Object/Error.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/SymbolicFile.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SwapByteOrder.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <list>
#include <memory>
#include <string>
#include <system_error>
Classes
struct MachOElement
Functions
static Error malformedError (const Twine &Msg)
template<typename T >
static T getStruct (const MachOObjectFile &O, const char *P)
template<typename T >
static Expected< T > getStructOrErr (const MachOObjectFile &O, const char *P)
static const char * getSectionPtr (const MachOObjectFile &O, MachOObjectFile::LoadCommandInfo L, unsigned Sec)
static const char * getPtr (const MachOObjectFile &O, size_t Offset)
static MachO::nlist_base getSymbolTableEntryBase (const MachOObjectFile &O, DataRefImpl DRI)
static StringRef parseSegmentOrSectionName (const char *P)
static unsigned getCPUType (const MachOObjectFile &O)
static unsigned getCPUSubType (const MachOObjectFile &O)
static uint32_t getPlainRelocationAddress (const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationAddress (const MachO::any_relocation_info &RE)
static bool getPlainRelocationPCRel (const MachOObjectFile &O, const MachO::any_relocation_info &RE)
static bool getScatteredRelocationPCRel (const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationLength (const MachOObjectFile &O, const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationLength (const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationType (const MachOObjectFile &O, const MachO::any_relocation_info &RE)
static uint32_t getSectionFlags (const MachOObjectFile &O, DataRefImpl Sec)
static Expected< MachOObjectFile::LoadCommandInfo > getLoadCommandInfo (const MachOObjectFile &Obj, const char *Ptr, uint32_t LoadCommandIndex)
static Expected< MachOObjectFile::LoadCommandInfo > getFirstLoadCommandInfo (const MachOObjectFile &Obj)
static Expected< MachOObjectFile::LoadCommandInfo > getNextLoadCommandInfo (const MachOObjectFile &Obj, uint32_t LoadCommandIndex, const MachOObjectFile::LoadCommandInfo &L)
template<typename T >
static void parseHeader (const MachOObjectFile &Obj, T &Header, Error &Err)
static Error checkOverlappingElement (std::list< MachOElement > &Elements, uint64_t Offset, uint64_t Size, const char *Name)
template<typename Segment , typename Section >
static Error parseSegmentLoadCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, SmallVectorImpl< const char *> &Sections, bool &IsPageZeroSegment, uint32_t LoadCommandIndex, const char *CmdName, uint64_t SizeOfHeaders, std::list< MachOElement > &Elements)
static Error checkSymtabCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **SymtabLoadCmd, std::list< MachOElement > &Elements)
static Error checkDysymtabCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **DysymtabLoadCmd, std::list< MachOElement > &Elements)
static Error checkLinkeditDataCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, const char *CmdName, std::list< MachOElement > &Elements, const char *ElementName)
static Error checkDyldInfoCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, const char *CmdName, std::list< MachOElement > &Elements)
static Error checkDylibCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName)
static Error checkDylibIdCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd)
static Error checkDyldCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName)
static Error checkVersCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, const char *CmdName)
static Error checkNoteCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, std::list< MachOElement > &Elements)
static Error parseBuildVersionCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, SmallVectorImpl< const char *> &BuildTools, uint32_t LoadCommandIndex)
static Error checkRpathCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex)
static Error checkEncryptCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, uint64_t cryptoff, uint64_t cryptsize, const char **LoadCmd, const char *CmdName)
static Error checkLinkerOptCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex)
static Error checkSubCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName, size_t SizeOfCmd, const char *CmdStructName, uint32_t PathOffset, const char *PathFieldName)
static Error checkThreadCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName)
static Error checkTwoLevelHintsCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, std::list< MachOElement > &Elements)
static bool isLoadCommandObsolete (uint32_t cmd)
Function Documentation
checkDyldCommand()
static Error checkDyldCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName) static
Definition at line 778 of file MachOObjectFile.cpp.
References llvm::MachO::dylinker_command::cmdsize, D, for(), malformedError(), llvm::MachO::dylinker_command::name, P, and llvm::Error::success().
checkDyldInfoCommand()
static Error checkDyldInfoCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, const char * CmdName, std::list< MachOElement > & Elements) static
Definition at line 630 of file MachOObjectFile.cpp.
References llvm::MachO::dyld_info_command::cmdsize, malformedError(), llvm::MachO::dyld_info_command::rebase_off, and llvm::MachO::dyld_info_command::rebase_size.
checkDylibCommand()
static Error checkDylibCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName) static
Definition at line 729 of file MachOObjectFile.cpp.
References llvm::MachO::dylib_command::cmdsize, D, llvm::MachO::dylib_command::dylib, for(), malformedError(), llvm::MachO::dylib::name, P, and llvm::Error::success().
checkDylibIdCommand()
static Error checkDylibIdCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd) static
Definition at line 761 of file MachOObjectFile.cpp.
checkDysymtabCommand()
static Error checkDysymtabCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** DysymtabLoadCmd, std::list< MachOElement > & Elements) static
Definition at line 459 of file MachOObjectFile.cpp.
References llvm::MachO::dysymtab_command::cmdsize, malformedError(), llvm::MachO::dysymtab_command::ntoc, and llvm::MachO::dysymtab_command::tocoff.
checkEncryptCommand()
static Error checkEncryptCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, uint64_t cryptoff, uint64_t cryptsize, const char ** LoadCmd, const char * CmdName) static
Definition at line 909 of file MachOObjectFile.cpp.
References malformedError(), and llvm::Error::success().
checkLinkeditDataCommand()
static Error checkLinkeditDataCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, const char * CmdName, std::list< MachOElement > & Elements, const char * ElementName) static
Definition at line 592 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::cmdsize, llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, and malformedError().
checkLinkerOptCommand()
static Error checkLinkerOptCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex) static
Definition at line 933 of file MachOObjectFile.cpp.
References llvm::MachO::linker_option_command::cmdsize, llvm::MachO::linker_option_command::count, llvm::StringRef::find(), malformedError(), and llvm::Error::success().
checkNoteCommand()
static Error checkNoteCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, std::list< MachOElement > & Elements) static
Definition at line 825 of file MachOObjectFile.cpp.
References malformedError(), llvm::MachO::note_command::offset, and llvm::MachO::note_command::size.
checkOverlappingElement()
static Error checkOverlappingElement (std::list< MachOElement > & Elements, uint64_t Offset, uint64_t Size, const char * Name) static
Definition at line 244 of file MachOObjectFile.cpp.
References E, malformedError(), N, Size, and llvm::Error::success().
checkRpathCommand()
static Error checkRpathCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex) static
Definition at line 877 of file MachOObjectFile.cpp.
References llvm::MachO::rpath_command::cmdsize, for(), malformedError(), P, llvm::MachO::rpath_command::path, llvm::RISCVFenceField::R, and llvm::Error::success().
checkSubCommand()
static Error checkSubCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName, size_t SizeOfCmd, const char * CmdStructName, uint32_t PathOffset, const char * PathFieldName) static
Definition at line 973 of file MachOObjectFile.cpp.
References for(), malformedError(), P, and llvm::Error::success().
checkSymtabCommand()
static Error checkSymtabCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** SymtabLoadCmd, std::list< MachOElement > & Elements) static
Definition at line 401 of file MachOObjectFile.cpp.
References llvm::MachO::symtab_command::cmdsize, malformedError(), llvm::MachO::symtab_command::nsyms, and llvm::MachO::symtab_command::symoff.
checkThreadCommand()
static Error checkThreadCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName) static
Definition at line 1000 of file MachOObjectFile.cpp.
References llvm::MachO::ARM_THREAD_STATE, llvm::MachO::ARM_THREAD_STATE64, llvm::MachO::ARM_THREAD_STATE64_COUNT, llvm::MachO::ARM_THREAD_STATE_COUNT, llvm::MachO::thread_command::cmdsize, llvm::count(), llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_ARM64_32, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_X86_64, llvm::sys::path::end(), getCPUType(), llvm::sys::IsLittleEndianHost, malformedError(), llvm::MachO::PPC_THREAD_STATE, llvm::MachO::PPC_THREAD_STATE_COUNT, llvm::Error::success(), llvm::sys::swapByteOrder(), llvm::MachO::x86_EXCEPTION_STATE, llvm::MachO::x86_EXCEPTION_STATE64, llvm::MachO::x86_EXCEPTION_STATE64_COUNT, llvm::MachO::x86_EXCEPTION_STATE_COUNT, llvm::MachO::x86_FLOAT_STATE, llvm::MachO::x86_FLOAT_STATE_COUNT, llvm::MachO::x86_THREAD_STATE, llvm::MachO::x86_THREAD_STATE32, llvm::MachO::x86_THREAD_STATE32_COUNT, llvm::MachO::x86_THREAD_STATE64, llvm::MachO::x86_THREAD_STATE64_COUNT, and llvm::MachO::x86_THREAD_STATE_COUNT.
checkTwoLevelHintsCommand()
static Error checkTwoLevelHintsCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, std::list< MachOElement > & Elements) static
Definition at line 1191 of file MachOObjectFile.cpp.
References malformedError(), llvm::MachO::twolevel_hints_command::nhints, and llvm::MachO::twolevel_hints_command::offset.
checkVersCommand()
static Error checkVersCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, const char * CmdName) static
Definition at line 810 of file MachOObjectFile.cpp.
References malformedError(), and llvm::Error::success().
getCPUSubType()
static unsigned getCPUSubType (const MachOObjectFile & O) static
Definition at line 131 of file MachOObjectFile.cpp.
Referenced by llvm::object::MachOObjectFile::getValidArchs().
getCPUType()
static unsigned getCPUType (const MachOObjectFile & O) static
Definition at line 127 of file MachOObjectFile.cpp.
Referenced by checkThreadCommand(), llvm::object::MachOObjectFile::getFileFormatName(), llvm::object::MachOObjectFile::getValidArchs(), and llvm::object::MachOObjectFile::isRelocationScattered().
getFirstLoadCommandInfo()
static Expected<MachOObjectFile::LoadCommandInfo> getFirstLoadCommandInfo (const MachOObjectFile & Obj) static
Definition at line 202 of file MachOObjectFile.cpp.
References getLoadCommandInfo(), getPtr(), llvm::BTF::HeaderSize, and malformedError().
getLoadCommandInfo()
static Expected<MachOObjectFile::LoadCommandInfo> getLoadCommandInfo (const MachOObjectFile & Obj, const char * Ptr, uint32_t LoadCommandIndex) static
Definition at line 187 of file MachOObjectFile.cpp.
References malformedError().
Referenced by getFirstLoadCommandInfo(), and getNextLoadCommandInfo().
getNextLoadCommandInfo()
static Expected<MachOObjectFile::LoadCommandInfo> getNextLoadCommandInfo (const MachOObjectFile & Obj, uint32_t LoadCommandIndex, const MachOObjectFile::LoadCommandInfo & L) static
Definition at line 212 of file MachOObjectFile.cpp.
References getLoadCommandInfo(), llvm::BTF::HeaderSize, and malformedError().
getPlainRelocationAddress()
static uint32_t getPlainRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 136 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress(), and llvm::object::MachOObjectFile::isRelocationScattered().
getPlainRelocationLength()
static unsigned getPlainRelocationLength (const MachOObjectFile & O, const MachO::any_relocation_info & RE) static
Definition at line 157 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
getPlainRelocationPCRel()
static bool getPlainRelocationPCRel (const MachOObjectFile & O, const MachO::any_relocation_info & RE) static
Definition at line 145 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
getPlainRelocationType()
static unsigned getPlainRelocationType (const MachOObjectFile & O, const MachO::any_relocation_info & RE) static
Definition at line 169 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationType().
getPtr()
static const char* getPtr (const MachOObjectFile & O, size_t Offset) static
Definition at line 108 of file MachOObjectFile.cpp.
References assert().
Referenced by llvm::object::MachOObjectFile::begin_dices(), llvm::Error::dynamicClassID(), llvm::object::MachOObjectFile::end_dices(), llvm::object::MachOObjectFile::getDataInCodeTableEntry(), llvm::object::MachOObjectFile::getDyldInfoBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoExportsTrie(), llvm::object::MachOObjectFile::getDyldInfoLazyBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoRebaseOpcodes(), llvm::object::MachOObjectFile::getDyldInfoWeakBindOpcodes(), getFirstLoadCommandInfo(), llvm::object::MachOObjectFile::getIndirectSymbolTableEntry(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::MachOObjectFile::getRelocationSymbol(), llvm::object::MachOObjectFile::getSymbolByIndex(), llvm::object::MachOObjectFile::getSymbolIndex(), llvm::Error::isA(), llvm::Error::operator bool(), llvm::object::MachOObjectFile::symbol_end(), and llvm::Error::~Error().
getScatteredRelocationAddress()
static unsigned getScatteredRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 141 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress().
getScatteredRelocationLength()
static unsigned getScatteredRelocationLength (const MachO::any_relocation_info & RE) static
Definition at line 165 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
getScatteredRelocationPCRel()
static bool getScatteredRelocationPCRel (const MachO::any_relocation_info & RE) static
Definition at line 153 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
getSectionFlags()
static uint32_t getSectionFlags (const MachOObjectFile & O, DataRefImpl Sec) static
Definition at line 176 of file MachOObjectFile.cpp.
References llvm::MachO::section::flags, and llvm::MachO::section_64::flags.
Referenced by llvm::object::XCOFFObjectFile::getPointerToSymbolTable(), llvm::object::MachOObjectFile::getSectionType(), llvm::object::XCOFFObjectFile::isSectionBSS(), llvm::object::MachOObjectFile::isSectionBSS(), llvm::object::XCOFFObjectFile::isSectionData(), llvm::object::MachOObjectFile::isSectionData(), llvm::object::XCOFFObjectFile::isSectionText(), llvm::object::MachOObjectFile::isSectionText(), and llvm::object::MachOObjectFile::isSectionVirtual().
getSectionPtr()
static const char* getSectionPtr (const MachOObjectFile & O, MachOObjectFile::LoadCommandInfo L, unsigned Sec) static
Definition at line 94 of file MachOObjectFile.cpp.
References llvm::COFF::SectionSize.
Referenced by llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), and parseSegmentLoadCommand().
getStruct()
template<typename T > static T getStruct (const MachOObjectFile & O, const char * P) static
Definition at line 68 of file MachOObjectFile.cpp.
References llvm::sys::IsLittleEndianHost, llvm::report_fatal_error(), llvm::MachO::swapStruct(), and llvm::T.
getStructOrErr()
template<typename T > static Expected<T> getStructOrErr (const MachOObjectFile & O, const char * P) static
Definition at line 81 of file MachOObjectFile.cpp.
References llvm::sys::IsLittleEndianHost, malformedError(), llvm::MachO::swapStruct(), and llvm::T.
getSymbolTableEntryBase()
static MachO::nlist_base getSymbolTableEntryBase (const MachOObjectFile & O, DataRefImpl DRI) static
Definition at line 114 of file MachOObjectFile.cpp.
References llvm::RISCVFenceField::O, and P.
Referenced by llvm::object::MachOObjectFile::getIndirectName(), llvm::object::MachOObjectFile::getSymbolAlignment(), llvm::object::MachOObjectFile::getSymbolFlags(), llvm::object::MachOObjectFile::getSymbolName(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::object::MachOObjectFile::getSymbolSectionID(), and llvm::object::MachOObjectFile::getSymbolType().
isLoadCommandObsolete()
static bool isLoadCommandObsolete (uint32_t cmd) static
Definition at line 1230 of file MachOObjectFile.cpp.
malformedError()
static Error malformedError (const Twine & Msg) static
Definition at line 60 of file MachOObjectFile.cpp.
References llvm::object::parse_failed.
Referenced by checkDyldCommand(), checkDyldInfoCommand(), checkDylibCommand(), checkDysymtabCommand(), checkEncryptCommand(), checkLinkeditDataCommand(), checkLinkerOptCommand(), checkNoteCommand(), checkOverlappingElement(), checkRpathCommand(), checkSubCommand(), llvm::object::MachOObjectFile::checkSymbolTable(), checkSymtabCommand(), checkThreadCommand(), checkTwoLevelHintsCommand(), checkVersCommand(), getFirstLoadCommandInfo(), getLoadCommandInfo(), getNextLoadCommandInfo(), llvm::object::MachOObjectFile::getSection(), getStructOrErr(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::object::ExportEntry::moveNext(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), parseBuildVersionCommand(), and parseSegmentLoadCommand().
parseBuildVersionCommand()
static Error parseBuildVersionCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, SmallVectorImpl< const char *> & BuildTools, uint32_t LoadCommandIndex) static
Definition at line 854 of file MachOObjectFile.cpp.
References malformedError(), and llvm::MachO::build_version_command::ntools.
parseHeader()
template<typename T > static void parseHeader (const MachOObjectFile & Obj, T & Header, Error & Err) static
Definition at line 224 of file MachOObjectFile.cpp.
parseSegmentLoadCommand()
template<typename Segment , typename Section > static Error parseSegmentLoadCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, SmallVectorImpl< const char *> & Sections, bool & IsPageZeroSegment, uint32_t LoadCommandIndex, const char * CmdName, uint64_t SizeOfHeaders, std::list< MachOElement > & Elements) static
Definition at line 277 of file MachOObjectFile.cpp.
References getSectionPtr(), malformedError(), llvm::max(), llvm::MachO::MH_DSYM, llvm::MachO::MH_DYLIB_STUB, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachO::S_THREAD_LOCAL_ZEROFILL, llvm::MachO::S_ZEROFILL, llvm::ARMBuildAttrs::Section, and llvm::COFF::SectionSize.
parseSegmentOrSectionName()
static StringRef parseSegmentOrSectionName (const char * P) static
Definition at line 119 of file MachOObjectFile.cpp.
References P.
Referenced by llvm::object::MachOObjectFile::getSectionFinalSegmentName(), and llvm::object::MachOObjectFile::getSectionName().