LLVM: lib/CodeGen/MachineLICM.cpp File Reference
MachineLICM.cpp File Reference
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <limits>
#include <vector>
Macros
#define DEBUG_TYPE "machinelicm"
Enumerations
enum UseBFI { UseBFI::None, UseBFI::PGO, UseBFI::All }
Functions
STATISTIC (NumHoisted, "Number of machine instructions hoisted out of loops")
STATISTIC (NumLowRP, "Number of instructions hoisted in low reg pressure situation")
STATISTIC (NumHighLatency, "Number of high latency instructions hoisted")
STATISTIC (NumCSEed, "Number of hoisted machine instructions CSEed")
STATISTIC (NumPostRAHoisted, "Number of machine instructions hoisted out of loops post regalloc")
STATISTIC (NumStoreConst, "Number of stores of const phys reg hoisted out of loops")
STATISTIC (NumNotHoistedDueToHotness, "Number of instructions not hoisted due to block frequency")
INITIALIZE_PASS_BEGIN (MachineLICM, DEBUG_TYPE, "Machine Loop Invariant Code Motion", false, false) INITIALIZE_PASS_END(MachineLICM
Machine Loop Invariant Code false INITIALIZE_PASS_BEGIN (EarlyMachineLICM, "early-machinelicm", "Early Machine Loop Invariant Code Motion", false, false) INITIALIZE_PASS_END(EarlyMachineLICM
Machine Loop Invariant Code false early Early Machine Loop Invariant Code static false bool LoopIsOuterMostWithPredecessor (MachineLoop *CurLoop)
Test if the given loop is the outer-most loop that has a unique predecessor.
static bool InstructionStoresToFI (const MachineInstr *MI, int FI)
Return true if instruction stores to the specified frame.
static bool isOperandKill (const MachineOperand &MO, MachineRegisterInfo *MRI)
static bool mayLoadFromGOTOrConstantPool (MachineInstr &MI)
Return true if this machine instruction loads from global offset table or constant pool.
static bool isInvariantStore (const MachineInstr &MI, const TargetRegisterInfo *TRI, const MachineRegisterInfo *MRI)
static bool isCopyFeedingInvariantStore (const MachineInstr &MI, const MachineRegisterInfo *MRI, const TargetRegisterInfo *TRI)
Variables
static cl::opt< bool > AvoidSpeculation ("avoid-speculation", cl::desc("MachineLICM should avoid speculation"), cl::init(true), cl::Hidden)
static cl::opt< bool > HoistCheapInsts ("hoist-cheap-insts", cl::desc("MachineLICM should hoist even cheap instructions"), cl::init(false), cl::Hidden)
static cl::opt< bool > SinkInstsToAvoidSpills ("sink-insts-to-avoid-spills", cl::desc("MachineLICM should sink instructions into " "loops to avoid register spills"), cl::init(false), cl::Hidden)
static cl::opt< bool > HoistConstStores ("hoist-const-stores", cl::desc("Hoist invariant stores"), cl::init(true), cl::Hidden)
static cl::opt< unsigned > BlockFrequencyRatioThreshold ("block-freq-ratio-threshold", cl::desc("Do not hoist instructions if target" "block is N times hotter than the source."), cl::init(100), cl::Hidden)
static cl::opt< UseBFI > DisableHoistingToHotterBlocks ("disable-hoisting-to-hotter-blocks", cl::desc("Disable hoisting instructions to" " hotter blocks"), cl::init(UseBFI::None), cl::Hidden, cl::values(clEnumValN(UseBFI::None, "none", "disable the feature"), clEnumValN(UseBFI::PGO, "pgo", "enable the feature when using profile data"), clEnumValN(UseBFI::All, "all", "enable the feature with/wo profile data")))
DEBUG_TYPE
Machine Loop Invariant Code Motion
Machine Loop Invariant Code false
Machine Loop Invariant Code false early machinelicm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machinelicm"
Definition at line 58 of file MachineLICM.cpp.
Enumeration Type Documentation
UseBFI
enum UseBFI strong
Enumerator
None
PGO
All
Definition at line 87 of file MachineLICM.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN() [1/2]
INITIALIZE_PASS_BEGIN (MachineLICM , DEBUG_TYPE , "Machine Loop Invariant Code Motion" , false , false)
INITIALIZE_PASS_BEGIN() [2/2]
Machine Loop Invariant Code false INITIALIZE_PASS_BEGIN (EarlyMachineLICM , "early-machinelicm" , "Early Machine Loop Invariant Code Motion" , false , false)
InstructionStoresToFI()
static bool InstructionStoresToFI (const MachineInstr * MI, int FI) static
Return true if instruction stores to the specified frame.
Definition at line 410 of file MachineLICM.cpp.
References assert(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::tgtok::Def, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::MachineInstr::getParent(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineBasicBlock::isEHPad(), llvm::HexagonInstrInfo::isLoadFromStackSlot(), llvm::Register::isPhysicalRegister(), llvm::MCRegAliasIterator::isValid(), LLVM_DEBUG, llvm::MachineInstr::mayStore(), llvm::MachineInstr::memoperands(), llvm::MachineInstr::memoperands_empty(), MI, llvm::MachineInstr::operands(), llvm::printMBBReference(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::Sched::RegPressure, llvm::BitVector::set(), llvm::BitVector::setBitsNotInMask(), llvm::MachineBasicBlock::splice(), llvm::BitVector::test(), TII, and TRI.
isCopyFeedingInvariantStore()
static bool isCopyFeedingInvariantStore (const MachineInstr & MI, const MachineRegisterInfo * MRI, const TargetRegisterInfo * TRI) static
Definition at line 982 of file MachineLICM.cpp.
References All, assert(), AvoidSpeculation, BlockFrequencyRatioThreshold, llvm::MachineInstr::canFoldAsLoad(), llvm::dbgs(), DisableHoistingToHotterBlocks, llvm::numbers::e, llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineInstr::eraseFromParent(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDesc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineInstr::getMF(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), HoistCheapInsts, HoistConstStores, I, llvm::TargetRegisterInfo::isCallerPreservedPhysReg(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isCopyLike(), llvm::MachineOperand::isDef(), llvm::MachineInstr::isDereferenceableInvariantLoad(), isExitBlock(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isImplicitDef(), isInvariantStore(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isSafeToMove(), llvm::MachineOperand::isUse(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, llvm::MachineInstr::mayLoad(), mayLoadFromGOTOrConstantPool(), llvm::MachineInstr::mayStore(), MI, MRI, llvm::MachineInstr::operands(), PGO, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::printMBBReference(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::NVPTX::PTXCvtMode::RP, llvm::MachineInstr::setDebugLoc(), llvm::SmallVectorBase::size(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::SplitCriticalEdge(), Success, TII, TRI, llvm::MachineRegisterInfo::use_instructions(), and UseMI.
isInvariantStore()
static bool isInvariantStore (const MachineInstr & MI, const TargetRegisterInfo * TRI, const MachineRegisterInfo * MRI) static
Definition at line 948 of file MachineLICM.cpp.
References llvm::MachineInstr::getMF(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::TargetRegisterInfo::isCallerPreservedPhysReg(), llvm::Register::isVirtualRegister(), llvm::TargetRegisterInfo::lookThruCopyLike(), llvm::MachineInstr::mayStore(), MRI, llvm::MachineInstr::operands(), and Reg.
Referenced by isCopyFeedingInvariantStore().
isOperandKill()
static bool isOperandKill (const MachineOperand & MO, MachineRegisterInfo * MRI) static
Definition at line 836 of file MachineLICM.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MachineOperand::isKill(), llvm::MachineBasicBlock::pred_size(), and llvm::Sched::RegPressure.
LoopIsOuterMostWithPredecessor()
Machine Loop Invariant Code false early Early Machine Loop Invariant Code static false bool LoopIsOuterMostWithPredecessor (MachineLoop * CurLoop) static
Test if the given loop is the outer-most loop that has a unique predecessor.
Definition at line 325 of file MachineLICM.cpp.
References llvm::dbgs(), llvm::numbers::e, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getName(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::Function::hasProfileData(), LLVM_DEBUG, MRI, N, None, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::Sched::RegPressure, SinkInstsToAvoidSpills, llvm::ARM_MB::ST, TII, and TRI.
mayLoadFromGOTOrConstantPool()
static bool mayLoadFromGOTOrConstantPool (MachineInstr & MI) static
Return true if this machine instruction loads from global offset table or constant pool.
Definition at line 925 of file MachineLICM.cpp.
References assert(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::memoperands(), and llvm::MachineInstr::memoperands_empty().
Referenced by isCopyFeedingInvariantStore().
STATISTIC() [1/7]
STATISTIC (NumHoisted , "Number of machine instructions hoisted out of loops")
STATISTIC() [2/7]
STATISTIC (NumLowRP , "Number of instructions hoisted in low reg pressure situation")
STATISTIC() [3/7]
STATISTIC (NumHighLatency , "Number of high latency instructions hoisted")
STATISTIC() [4/7]
STATISTIC (NumCSEed , "Number of hoisted machine instructions CSEed")
STATISTIC() [5/7]
STATISTIC (NumPostRAHoisted , "Number of machine instructions hoisted out of loops post regalloc")
STATISTIC() [6/7]
STATISTIC (NumStoreConst , "Number of stores of const phys reg hoisted out of loops")
STATISTIC() [7/7]
STATISTIC (NumNotHoistedDueToHotness , "Number of instructions not hoisted due to block frequency")
Variable Documentation
AvoidSpeculation
cl::opt<bool> AvoidSpeculation("avoid-speculation", cl::desc("MachineLICM should avoid speculation"), cl::init(true), cl::Hidden) static
Referenced by isCopyFeedingInvariantStore().
BlockFrequencyRatioThreshold
cl::opt<unsigned> BlockFrequencyRatioThreshold("block-freq-ratio-threshold", cl::desc("Do not hoist instructions if target" "block is N times hotter than the source."), cl::init(100), cl::Hidden) static
Referenced by isCopyFeedingInvariantStore().
DEBUG_TYPE
DEBUG_TYPE
Definition at line 312 of file MachineLICM.cpp.
DisableHoistingToHotterBlocks
cl::opt<UseBFI> DisableHoistingToHotterBlocks("disable-hoisting-to-hotter-blocks", cl::desc("Disable hoisting instructions to" " hotter blocks"), cl::init(UseBFI::None), cl::Hidden, cl::values(clEnumValN(UseBFI::None, "none", "disable the feature"), clEnumValN(UseBFI::PGO, "pgo", "enable the feature when using profile data"), clEnumValN(UseBFI::All, "all", "enable the feature with/wo profile data"))) static
Referenced by isCopyFeedingInvariantStore().
false
Machine Loop Invariant Code false early Early Machine Loop Invariant Code false
Definition at line 312 of file MachineLICM.cpp.
HoistCheapInsts
cl::opt<bool> HoistCheapInsts("hoist-cheap-insts", cl::desc("MachineLICM should hoist even cheap instructions"), cl::init(false), cl::Hidden) static
Referenced by isCopyFeedingInvariantStore().
HoistConstStores
cl::opt<bool> HoistConstStores("hoist-const-stores", cl::desc("Hoist invariant stores"), cl::init(true), cl::Hidden) static
Referenced by isCopyFeedingInvariantStore().
machinelicm
Machine Loop Invariant Code false early machinelicm
Definition at line 321 of file MachineLICM.cpp.
Motion
Machine Loop Invariant Code false early Early Machine Loop Invariant Code Motion
Definition at line 312 of file MachineLICM.cpp.
SinkInstsToAvoidSpills
cl::opt<bool> SinkInstsToAvoidSpills("sink-insts-to-avoid-spills", cl::desc("MachineLICM should sink instructions into " "loops to avoid register spills"), cl::init(false), cl::Hidden) static
Referenced by LoopIsOuterMostWithPredecessor().