LLVM: lib/CodeGen/MacroFusion.cpp File Reference
MacroFusion.cpp File Reference
#include "llvm/CodeGen/MacroFusion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/ScheduleDAGMutation.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "machine-scheduler"
Functions
STATISTIC (NumFused, "Number of instr pairs fused")
static bool isHazard (const SDep &Dep)
static SUnit * getPredClusterSU (const SUnit &SU)
static bool hasLessThanNumFused (const SUnit &SU, unsigned FuseLimit)
static bool fuseInstructionPair (ScheduleDAGInstrs &DAG, SUnit &FirstSU, SUnit &SecondSU)
Variables
static cl::opt< bool > EnableMacroFusion ("misched-fusion", cl::Hidden, cl::desc("Enable scheduling for macro fusion."), cl::init(true))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 26 of file MacroFusion.cpp.
Function Documentation
fuseInstructionPair()
static bool fuseInstructionPair (ScheduleDAGInstrs & DAG, SUnit & FirstSU, SUnit & SecondSU) static
Definition at line 54 of file MacroFusion.cpp.
References llvm::ScheduleDAGInstrs::addEdge(), llvm::cl::apply(), llvm::SDep::Artificial, assert(), llvm::SDep::Cluster, llvm::dbgs(), llvm::ScheduleDAG::dumpNodeName(), llvm::ScheduleDAG::EntrySU, llvm::ScheduleDAG::ExitSU, llvm::SUnit::getInstr(), llvm::MCInstrInfo::getName(), llvm::MachineInstr::getOpcode(), llvm::MachineFunction::getSubtarget(), llvm::SDep::getSUnit(), hasLessThanNumFused(), llvm::SUnit::isBoundaryNode(), llvm::SDep::isCluster(), isHazard(), llvm::SUnit::isPred(), llvm::SUnit::isSucc(), llvm::SDep::isWeak(), LLVM_DEBUG, llvm::ScheduleDAG::MF, llvm::SUnit::Preds, llvm::SDep::setLatency(), llvm::shouldScheduleAdjacent(), SI, llvm::ARM_MB::ST, llvm::SUnit::Succs, llvm::ScheduleDAG::SUnits, TII, and llvm::ScheduleDAG::TII.
getPredClusterSU()
static SUnit* getPredClusterSU (const SUnit & SU) static
Definition at line 39 of file MacroFusion.cpp.
References llvm::SDep::getSUnit(), llvm::SDep::isCluster(), llvm::SUnit::Preds, and SI.
Referenced by hasLessThanNumFused().
hasLessThanNumFused()
static bool hasLessThanNumFused (const SUnit & SU, unsigned FuseLimit) static
Definition at line 47 of file MacroFusion.cpp.
References getPredClusterSU().
Referenced by fuseInstructionPair().
isHazard()
static bool isHazard (const SDep & Dep) static
Definition at line 35 of file MacroFusion.cpp.
References llvm::SDep::Anti, llvm::SDep::getKind(), and llvm::SDep::Output.
Referenced by fuseInstructionPair().
STATISTIC()
STATISTIC (NumFused , "Number of instr pairs fused")
Variable Documentation
EnableMacroFusion
cl::opt<bool> EnableMacroFusion("misched-fusion", cl::Hidden, cl::desc("Enable scheduling for macro fusion."), cl::init(true)) static
Referenced by llvm::createBranchMacroFusionDAGMutation(), and llvm::createMacroFusionDAGMutation().