LLVM: lib/Transforms/Scalar/MakeGuardsExplicit.cpp File Reference
MakeGuardsExplicit.cpp File Reference
#include "llvm/Transforms/Scalar/MakeGuardsExplicit.h"
#include "llvm/Analysis/GuardUtils.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/GuardUtils.h"
Functions
static void turnToExplicitForm (CallInst *Guard, Function *DeoptIntrinsic)
static bool explicifyGuards (Function &F)
INITIALIZE_PASS (MakeGuardsExplicitLegacyPass, "make-guards-explicit", "Lower the guard intrinsic to explicit control flow form", false, false) PreservedAnalyses MakeGuardsExplicitPass
Function Documentation
explicifyGuards()
static bool explicifyGuards (Function & F) static
Definition at line 68 of file MakeGuardsExplicit.cpp.
References llvm::SmallVectorBase::empty(), F(), llvm::Intrinsic::getDeclaration(), llvm::Module::getFunction(), llvm::Intrinsic::getName(), llvm::GlobalValue::getParent(), llvm::Function::getReturnType(), I, llvm::instructions(), llvm::isGuard(), llvm::SmallVectorTemplateBase< T >::push_back(), runOnFunction(), llvm::Function::setCallingConv(), and turnToExplicitForm().
Referenced by INITIALIZE_PASS().
INITIALIZE_PASS()
INITIALIZE_PASS (MakeGuardsExplicitLegacyPass , "make-guards-explicit" , "Lower the guard intrinsic to explicit control flow form" , false , false)
Definition at line 99 of file MakeGuardsExplicit.cpp.
References llvm::PreservedAnalyses::all(), explicifyGuards(), and llvm::PreservedAnalyses::none().
turnToExplicitForm()
static void turnToExplicitForm (CallInst * Guard, Function * DeoptIntrinsic) static
Definition at line 58 of file MakeGuardsExplicit.cpp.
References assert(), llvm::Instruction::eraseFromParent(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::isWidenableBranch(), and llvm::makeGuardControlFlowExplicit().
Referenced by explicifyGuards().