LLVM: lib/MC/MCAsmStreamer.cpp File Reference
MCAsmStreamer.cpp File Reference
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCCodeView.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegister.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/TargetRegistry.h"
#include <cctype>
Functions
static int64_t truncateToSize (int64_t Value, unsigned Bytes)
static const char * getVersionMinDirective (MCVersionMinType Type)
static void EmitSDKVersionSuffix (raw_ostream &OS, const VersionTuple &SDKVersion)
static const char * getPlatformName (MachO::PlatformType Type)
static char toOctal (int X)
static void PrintQuotedString (StringRef Data, raw_ostream &OS)
static void printDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, bool UseDwarfDirectory, raw_svector_ostream &OS)
static void PrintCFIEscape (llvm::formatted_raw_ostream &OS, StringRef Values)
Function Documentation
EmitSDKVersionSuffix()
static void EmitSDKVersionSuffix (raw_ostream & OS, const VersionTuple & SDKVersion) static
Definition at line 539 of file MCAsmStreamer.cpp.
References llvm::VersionTuple::empty(), llvm::VersionTuple::getMajor(), llvm::VersionTuple::getMinor(), llvm::VersionTuple::getSubminor(), and getVersionMinDirective().
Referenced by getPlatformName().
getPlatformName()
static const char* getPlatformName (MachO::PlatformType Type) static
Definition at line 562 of file MCAsmStreamer.cpp.
References assert(), llvm::LCOMM::ByteAlignment, E, llvm::MCStreamer::EmitAssignment(), EmitSDKVersionSuffix(), llvm::MCAsmInfo::getAssemblerDialect(), llvm::MCAsmInfo::getCOMMDirectiveAlignmentIsInBytes(), llvm::MCAsmInfo::getCommentString(), llvm::MCSection::getDummyFragment(), llvm::MCAsmInfo::getGlobalDirective(), llvm::MCAsmInfo::getLCOMMDirectiveAlignmentType(), llvm::MCSectionMachO::getSegmentName(), llvm::MCSection::getVariant(), llvm::MCAsmInfo::getWeakDirective(), llvm::MCAsmInfo::getWeakRefDirective(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::MCAsmInfo::hasNoDeadStrip(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), llvm::isPowerOf2_32(), llvm_unreachable, llvm::Log2_32(), llvm::LCOMM::Log2Alignment, llvm::MCSA_AltEntry, llvm::MCSA_Cold, llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, llvm::MCSA_Global, llvm::MCSA_Hidden, llvm::MCSA_IndirectSymbol, llvm::MCSA_Internal, llvm::MCSA_Invalid, llvm::MCSA_LazyReference, llvm::MCSA_LGlobal, llvm::MCSA_Local, llvm::MCSA_NoDeadStrip, llvm::MCSA_PrivateExtern, llvm::MCSA_Protected, llvm::MCSA_Reference, llvm::MCSA_SymbolResolver, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::MCSA_WeakReference, llvm::LCOMM::NoAlignment, llvm::MachO::PLATFORM_BRIDGEOS, llvm::MachO::PLATFORM_IOS, llvm::MachO::PLATFORM_IOSSIMULATOR, llvm::MachO::PLATFORM_MACCATALYST, llvm::MachO::PLATFORM_MACOS, llvm::MachO::PLATFORM_TVOS, llvm::MachO::PLATFORM_TVOSSIMULATOR, llvm::MachO::PLATFORM_WATCHOS, llvm::MachO::PLATFORM_WATCHOSSIMULATOR, llvm::MCExpr::print(), llvm::MCSymbol::print(), Size, StorageClass, and llvm::MCSection::SV_MachO.
getVersionMinDirective()
static const char* getVersionMinDirective (MCVersionMinType Type) static
Definition at line 529 of file MCAsmStreamer.cpp.
References llvm_unreachable, llvm::MCVM_IOSVersionMin, llvm::MCVM_OSXVersionMin, llvm::MCVM_TvOSVersionMin, and llvm::MCVM_WatchOSVersionMin.
Referenced by EmitSDKVersionSuffix().
PrintCFIEscape()
static void PrintCFIEscape (llvm::formatted_raw_ostream & OS, StringRef Values) static
Definition at line 1565 of file MCAsmStreamer.cpp.
References assert(), llvm::StringRef::back(), llvm::tgtok::Bit, llvm::MCInst::dump_pretty(), llvm::numbers::e, llvm::MCGenDwarfInfo::Emit(), llvm::MCStreamer::EmitCFIAdjustCfaOffset(), llvm::MCStreamer::EmitCFIBKeyFrame(), llvm::MCStreamer::EmitCFIDefCfaRegister(), llvm::MCStreamer::EmitCFIEscape(), llvm::MCStreamer::EmitCFIGnuArgsSize(), llvm::MCStreamer::EmitCFILsda(), llvm::MCStreamer::EmitCFINegateRAState(), llvm::MCStreamer::EmitCFIOffset(), llvm::MCStreamer::EmitCFIPersonality(), llvm::MCStreamer::EmitCFIRegister(), llvm::MCStreamer::EmitCFIRelOffset(), llvm::MCStreamer::EmitCFIRememberState(), llvm::MCStreamer::EmitCFIRestore(), llvm::MCStreamer::EmitCFIRestoreState(), llvm::MCStreamer::EmitCFIReturnColumn(), llvm::MCStreamer::EmitCFISameValue(), llvm::MCStreamer::EmitCFISignalFrame(), llvm::MCStreamer::EmitCFIUndefined(), llvm::MCStreamer::EmitCFIWindowSave(), llvm::MCStreamer::EmitWinCFIAllocStack(), llvm::MCStreamer::EmitWinCFIEndChained(), llvm::MCStreamer::EmitWinCFIEndProc(), llvm::MCStreamer::EmitWinCFIEndProlog(), llvm::MCStreamer::EmitWinCFIPushFrame(), llvm::MCStreamer::EmitWinCFIPushReg(), llvm::MCStreamer::EmitWinCFISaveReg(), llvm::MCStreamer::EmitWinCFISaveXMM(), llvm::MCStreamer::EmitWinCFISetFrame(), llvm::MCStreamer::EmitWinCFIStartChained(), llvm::MCStreamer::EmitWinCFIStartProc(), llvm::MCStreamer::EmitWinEHHandler(), llvm::MCStreamer::EmitWinEHHandlerData(), llvm::StringRef::empty(), llvm::encodeULEB128(), F(), llvm::format(), From, llvm::WinEH::FrameInfo::Function, llvm::MCFixup::getKind(), llvm::MCFixup::getOffset(), llvm::MCSymbol::getSection(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCFixup::getValue(), Info, llvm::MCAsmInfo::isLittleEndian(), llvm::MCFixupKindInfo::Name, Name, llvm::MCExpr::print(), llvm::MCSymbol::print(), Register, llvm::SmallVectorImpl< T >::resize(), Size, llvm::SmallVectorBase::size(), llvm::StringRef::size(), llvm::StringRef::substr(), llvm::MCFixupKindInfo::TargetOffset, and llvm::MCFixupKindInfo::TargetSize.
printDwarfFileDirective()
static void printDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, bool UseDwarfDirectory, raw_svector_ostream & OS) static
Definition at line 1213 of file MCAsmStreamer.cpp.
References llvm::sys::path::append(), assert(), llvm::codeview::DefRangeRegisterRelHeader::BasePointerOffset, llvm::lltok::ChecksumKind, Debug, llvm::MD5::MD5Result::digest(), DWARF2_FLAG_BASIC_BLOCK, DWARF2_FLAG_EPILOGUE_BEGIN, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, llvm::MCStreamer::EmitCFIDefCfa(), llvm::MCStreamer::EmitCFIDefCfaOffset(), llvm::MCStreamer::EmitCFIEndProcImpl(), llvm::MCStreamer::EmitCFISections(), llvm::MCStreamer::EmitCVFuncIdDirective(), llvm::MCStreamer::EmitCVInlineLinetableDirective(), llvm::MCStreamer::EmitCVInlineSiteIdDirective(), llvm::MCStreamer::EmitCVLinetableDirective(), llvm::MCStreamer::EmitDwarfLocDirective(), llvm::StringRef::empty(), llvm::codeview::DefRangeRegisterRelHeader::Flags, FuncId, llvm::Expected< T >::get(), llvm::MCAsmInfo::getCommentColumn(), llvm::MCAsmInfo::getCommentString(), llvm::MCStreamer::getDwarfLineTableSymbol(), llvm::MCRegisterInfo::getLLVMRegNum(), llvm::MCDwarfLineTable::getMCDwarfFiles(), llvm::MCAsmInfo::hasIdentDirective(), llvm::sys::path::is_absolute(), llvm::MCDwarfFrameInfo::IsSimple, MRI, llvm::codeview::DefRangeFramePointerRelHeader::Offset, llvm::codeview::DefRangeSubfieldRegisterHeader::OffsetInParent, llvm::formatted_raw_ostream::PadToColumn(), llvm::MCSymbol::print(), PrintQuotedString(), Register, llvm::codeview::DefRangeRegisterHeader::Register, llvm::codeview::DefRangeSubfieldRegisterHeader::Register, llvm::codeview::DefRangeRegisterRelHeader::Register, llvm::Sched::Source, llvm::raw_svector_ostream::str(), llvm::MCAsmInfo::supportsExtendedDwarfLocDirective(), llvm::Expected< T >::takeError(), llvm::toHex(), llvm::MCDwarfLineTable::tryGetFile(), and llvm::MCAsmInfo::useDwarfRegNumForCFI().
PrintQuotedString()
static void PrintQuotedString (StringRef Data, raw_ostream & OS) static
Definition at line 887 of file MCAsmStreamer.cpp.
References llvm::alignTo(), assert(), llvm::StringRef::back(), llvm::LCOMM::ByteAlignment, llvm::StringRef::bytes(), C, llvm::MCConstantExpr::create(), llvm::Data, llvm::numbers::e, llvm::MCStreamer::emitFill(), llvm::StringRef::empty(), llvm::format(), llvm::MCAsmInfo::getAsciiDirective(), llvm::MCAsmInfo::getAscizDirective(), llvm::MCAsmInfo::getData16bitsDirective(), llvm::MCAsmInfo::getData32bitsDirective(), llvm::MCAsmInfo::getData64bitsDirective(), llvm::MCAsmInfo::getData8bitsDirective(), llvm::MCAsmInfo::getDTPRel32Directive(), llvm::MCAsmInfo::getDTPRel64Directive(), llvm::MCAsmInfo::getGPRel32Directive(), llvm::MCAsmInfo::getGPRel64Directive(), llvm::MCAsmInfo::getTextAlignFillValue(), llvm::MCAsmInfo::getTPRel32Directive(), llvm::MCAsmInfo::getTPRel64Directive(), llvm::MCAsmInfo::getZeroDirective(), llvm::MCAsmInfo::hasSingleParameterDotFile(), I, llvm::MCAsmInfo::isLittleEndian(), llvm::isPowerOf2_32(), llvm::isPrint(), llvm_unreachable, llvm::Log2_32(), llvm::PowerOf2Floor(), llvm::MCExpr::print(), llvm::report_fatal_error(), Size, llvm::StringRef::size(), llvm::StringRef::substr(), truncateToSize(), llvm::MCAsmInfo::useDotAlignForAlignment(), and llvm::raw_ostream::write_hex().
Referenced by printDwarfFileDirective().
toOctal()
static char toOctal (int X) inline static
Definition at line 885 of file MCAsmStreamer.cpp.
truncateToSize()
static int64_t truncateToSize (int64_t Value, unsigned Bytes) inline static
Definition at line 390 of file MCAsmStreamer.cpp.
References llvm::SmallString< InternalLen >::append(), Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::StringRef::back(), llvm::SmallVectorImpl< T >::clear(), llvm::MCAsmInfo::doesSupportDataRegionDirectives(), llvm::MCStreamer::EmitLabel(), llvm::StringRef::empty(), llvm::ArrayRef< T >::empty(), llvm::StringRef::equals(), llvm::StringRef::find_first_of(), llvm::StringRef::front(), llvm::MCAsmInfo::getCode16Directive(), llvm::MCAsmInfo::getCode32Directive(), llvm::MCAsmInfo::getCode64Directive(), llvm::MCAsmInfo::getCommentString(), llvm::MCAsmInfo::getLabelSuffix(), llvm::MCAsmInfo::getSeparatorString(), llvm::Twine::getSingleStringRef(), llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, llvm::MCAF_SyntaxUnified, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT16, llvm::MCDR_DataRegionJT32, llvm::MCDR_DataRegionJT8, llvm::MCLOHDirectiveName(), llvm::MCLOHIdToName(), llvm::MCLOHIdToNbArgs(), llvm::MCSymbol::print(), llvm::MCSection::PrintSwitchToSection(), llvm::SmallVectorBase::size(), llvm::StringRef::size(), llvm::StringRef::slice(), llvm::StringRef::startswith(), llvm::StringRef::str(), and llvm::T.
Referenced by PrintQuotedString().