LLVM: lib/MC/MCELFStreamer.cpp File Reference
MCELFStreamer.cpp File Reference
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
Functions
static void setSectionAlignmentForBundling (const MCAssembler &Assembler, MCSection *Section)
static unsigned CombineSymbolTypes (unsigned T1, unsigned T2)
static void CheckBundleSubtargets (const MCSubtargetInfo *OldSTI, const MCSubtargetInfo *NewSTI)
Function Documentation
CheckBundleSubtargets()
static void CheckBundleSubtargets (const MCSubtargetInfo * OldSTI, const MCSubtargetInfo * NewSTI) static
Definition at line 506 of file MCELFStreamer.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MCSection::BundleLockedAlignToEnd, DF, llvm::numbers::e, llvm::MCCodeEmitter::encodeInstruction(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MCObjectStreamer::getAssembler(), llvm::MCSection::getBundleLockState(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCObjectStreamer::getCurrentFragment(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCAssembler::getEmitter(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), llvm::getOffset(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::MCAssembler::getRelaxAll(), llvm::MCEncodedFragment::getSubtargetInfo(), llvm::MCObjectStreamer::insert(), llvm::MCSection::isBundleGroupBeforeFirstInst(), llvm::MCAssembler::isBundlingEnabled(), llvm::report_fatal_error(), llvm::MCEncodedFragment::setAlignToBundleEnd(), llvm::MCSection::setBundleGroupBeforeFirstInst(), llvm::MCEncodedFragment::setHasInstructions(), and llvm::SmallVectorBase::size().
CombineSymbolTypes()
static unsigned CombineSymbolTypes (unsigned T1, unsigned T2) static
Definition at line 178 of file MCELFStreamer.cpp.
References llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_TLS, and T1.
Referenced by llvm::MCELFStreamer::EmitSymbolAttribute().
setSectionAlignmentForBundling()
static void setSectionAlignmentForBundling (const MCAssembler & Assembler, MCSection * Section) static
Definition at line 139 of file MCELFStreamer.cpp.
References llvm::MCSection::getAlignment(), llvm::MCAssembler::getBundleAlignSize(), llvm::MCSection::hasInstructions(), llvm::MCAssembler::isBundlingEnabled(), and llvm::MCSection::setAlignment().
Referenced by llvm::MCELFStreamer::ChangeSection(), and llvm::MCELFStreamer::FinishImpl().