LLVM: lib/MC/MCMachOStreamer.cpp File Reference
MCMachOStreamer.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCLinkerOptimizationHint.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolMachO.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <vector>
Functions
static bool canGoAfterDWARF (const MCSectionMachO &MSec)
Function Documentation
canGoAfterDWARF()
static bool canGoAfterDWARF (const MCSectionMachO & MSec) static
Definition at line 122 of file MCMachOStreamer.cpp.
References assert(), llvm::MCObjectStreamer::EmitAssignment(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCExpr::evaluateAsRelocatable(), llvm::MCSection::getBeginSymbol(), llvm::MCValue::getConstant(), llvm::MCSymbol::getName(), llvm::MCSectionMachO::getSectionName(), llvm::MCSectionMachO::getSegmentName(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbol::isExternal(), llvm::MCSymbol::isPrivateExtern(), llvm::MCSA_Global, llvm::MCSA_PrivateExtern, llvm::MCSA_WeakDefinition, llvm::ARMBuildAttrs::Section, llvm::MCSection::setBeginSymbol(), and llvm::ARMBuildAttrs::Symbol.