LLVM: lib/MC/MCObjectStreamer.cpp File Reference
MCObjectStreamer.cpp File Reference
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCCodeView.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SourceMgr.h"
Functions
static Optional< uint64_t > absoluteSymbolDiff (MCAssembler &Asm, const MCSymbol *Hi, const MCSymbol *Lo)
static bool CanReuseDataFragment (const MCDataFragment &F, const MCAssembler &Assembler, const MCSubtargetInfo *STI)
static const MCExpr * buildSymbolDiff (MCObjectStreamer &OS, const MCSymbol *A, const MCSymbol *B)
static void emitDwarfSetLineAddr (MCObjectStreamer &OS, MCDwarfLineTableParams Params, int64_t LineDelta, const MCSymbol *Label, int PointerSize)
Variables
static const char *const BundlingNotImplementedMsg
Function Documentation
absoluteSymbolDiff()
static Optional<uint64_t> absoluteSymbolDiff (MCAssembler & Asm, const MCSymbol * Hi, const MCSymbol * Lo) static
Definition at line 132 of file MCObjectStreamer.cpp.
References assert(), llvm::MCAssembler::getBackendPtr(), llvm::MCSymbol::getFragment(), llvm::MCSymbol::getOffset(), llvm::MCSymbol::isVariable(), llvm::None, and llvm::MCAsmBackend::requiresDiffExpressionRelocations().
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), and llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128().
buildSymbolDiff()
static const MCExpr* buildSymbolDiff (MCObjectStreamer & OS, const MCSymbol * A, const MCSymbol * B) static
Definition at line 459 of file MCObjectStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::create(), llvm::MCStreamer::getContext(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCObjectStreamer::EmitDwarfAdvanceFrameAddr(), and llvm::MCObjectStreamer::EmitDwarfAdvanceLineAddr().
CanReuseDataFragment()
static bool CanReuseDataFragment (const MCDataFragment & F, const MCAssembler & Assembler, const MCSubtargetInfo * STI) static
Definition at line 194 of file MCObjectStreamer.cpp.
References llvm::MCAssembler::getRelaxAll(), llvm::MCEncodedFragment::getSubtargetInfo(), llvm::MCFragment::hasInstructions(), and llvm::MCAssembler::isBundlingEnabled().
Referenced by llvm::MCObjectStreamer::getOrCreateDataFragment().
emitDwarfSetLineAddr()
static void emitDwarfSetLineAddr (MCObjectStreamer & OS, MCDwarfLineTableParams Params, int64_t LineDelta, const MCSymbol * Label, int PointerSize) static
Definition at line 470 of file MCObjectStreamer.cpp.
References llvm::MCDwarfLineAddr::Emit(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitSymbolValue(), and llvm::MCStreamer::EmitULEB128IntValue().
Referenced by llvm::MCObjectStreamer::EmitDwarfAdvanceLineAddr().
Variable Documentation
BundlingNotImplementedMsg
const char* const BundlingNotImplementedMsg static
Initial value:
=
  "Aligned bundling is not implemented for this object format"
Definition at line 430 of file MCObjectStreamer.cpp.