LLVM: lib/MC/MCObjectFileInfo.cpp File Reference
MCObjectFileInfo.cpp File Reference
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Triple.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSectionXCOFF.h"
Functions
static bool useCompactUnwind (const Triple &T)
Function Documentation
useCompactUnwind()
static bool useCompactUnwind (const Triple & T) static
Definition at line 25 of file MCObjectFileInfo.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::Triple::arm, llvm::Triple::bpfeb, llvm::Triple::bpfel, llvm::MCObjectFileInfo::BSSSection, llvm::XCOFF::C_HIDEXT, llvm::MCObjectFileInfo::COFFDebugSymbolsSection, llvm::MCObjectFileInfo::COFFDebugTypesSection, llvm::MCObjectFileInfo::COFFGlobalTypeHashesSection, llvm::MCObjectFileInfo::CommDirectiveSupportsAlignment, llvm::MCObjectFileInfo::CompactUnwindDwarfEHFrameOnly, llvm::MCObjectFileInfo::CompactUnwindSection, llvm::MCObjectFileInfo::ConstDataCoalSection, llvm::MCObjectFileInfo::ConstDataSection, llvm::MCObjectFileInfo::ConstTextCoalSection, llvm::MCObjectFileInfo::CStringSection, llvm::MCObjectFileInfo::DataBSSSection, llvm::MCObjectFileInfo::DataCoalSection, llvm::MCObjectFileInfo::DataCommonSection, llvm::MCObjectFileInfo::DataRelROSection, llvm::MCObjectFileInfo::DataSection, llvm::MCObjectFileInfo::DrectveSection, llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_pcrel, llvm::dwarf::DW_EH_PE_sdata4, llvm::dwarf::DW_EH_PE_sdata8, llvm::MCObjectFileInfo::DwarfAbbrevDWOSection, llvm::MCObjectFileInfo::DwarfAbbrevSection, llvm::MCObjectFileInfo::DwarfAccelNamespaceSection, llvm::MCObjectFileInfo::DwarfAccelNamesSection, llvm::MCObjectFileInfo::DwarfAccelObjCSection, llvm::MCObjectFileInfo::DwarfAccelTypesSection, llvm::MCObjectFileInfo::DwarfAddrSection, llvm::MCObjectFileInfo::DwarfARangesSection, llvm::MCObjectFileInfo::DwarfCUIndexSection, llvm::MCObjectFileInfo::DwarfDebugInlineSection, llvm::MCObjectFileInfo::DwarfDebugNamesSection, llvm::MCObjectFileInfo::DwarfFrameSection, llvm::MCObjectFileInfo::DwarfGnuPubNamesSection, llvm::MCObjectFileInfo::DwarfGnuPubTypesSection, llvm::MCObjectFileInfo::DwarfInfoDWOSection, llvm::MCObjectFileInfo::DwarfInfoSection, llvm::MCObjectFileInfo::DwarfLineDWOSection, llvm::MCObjectFileInfo::DwarfLineSection, llvm::MCObjectFileInfo::DwarfLineStrSection, llvm::MCObjectFileInfo::DwarfLocDWOSection, llvm::MCObjectFileInfo::DwarfLoclistsDWOSection, llvm::MCObjectFileInfo::DwarfLoclistsSection, llvm::MCObjectFileInfo::DwarfLocSection, llvm::MCObjectFileInfo::DwarfMacinfoDWOSection, llvm::MCObjectFileInfo::DwarfMacinfoSection, llvm::MCObjectFileInfo::DwarfPubNamesSection, llvm::MCObjectFileInfo::DwarfPubTypesSection, llvm::MCObjectFileInfo::DwarfRangesSection, llvm::MCObjectFileInfo::DwarfRnglistsDWOSection, llvm::MCObjectFileInfo::DwarfRnglistsSection, llvm::MCObjectFileInfo::DwarfStrDWOSection, llvm::MCObjectFileInfo::DwarfStrOffDWOSection, llvm::MCObjectFileInfo::DwarfStrOffSection, llvm::MCObjectFileInfo::DwarfStrSection, llvm::MCObjectFileInfo::DwarfSwiftASTSection, llvm::MCObjectFileInfo::DwarfTUIndexSection, llvm::MCObjectFileInfo::DwarfTypesDWOSection, llvm::MCObjectFileInfo::EHFrameSection, llvm::MCObjectFileInfo::EightByteConstantSection, llvm::MCObjectFileInfo::FaultMapSection, llvm::MCObjectFileInfo::FDECFIEncoding, llvm::MCObjectFileInfo::FourByteConstantSection, llvm::Triple::getArch(), llvm::MCContext::getAsmInfo(), llvm::SectionKind::getBSS(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCContext::getCOFFSection(), llvm::SectionKind::getData(), llvm::MCContext::getELFSection(), llvm::MCContext::getMachOSection(), llvm::SectionKind::getMergeable1ByteCString(), llvm::SectionKind::getMergeable2ByteCString(), llvm::SectionKind::getMergeableConst16(), llvm::SectionKind::getMergeableConst4(), llvm::SectionKind::getMergeableConst8(), llvm::SectionKind::getMetadata(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getReadOnlyWithRel(), llvm::SectionKind::getText(), llvm::SectionKind::getThreadBSS(), llvm::MCContext::getWasmSection(), llvm::MCContext::getXCOFFSection(), llvm::MCObjectFileInfo::GFIDsSection, llvm::MCObjectFileInfo::GLJMPSection, llvm::Triple::hexagon, llvm::COFF::IMAGE_SCN_CNT_CODE, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_LNK_INFO, llvm::COFF::IMAGE_SCN_LNK_REMOVE, llvm::COFF::IMAGE_SCN_MEM_16BIT, llvm::COFF::IMAGE_SCN_MEM_DISCARDABLE, llvm::COFF::IMAGE_SCN_MEM_EXECUTE, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, llvm::Triple::isiOS(), llvm::Triple::isMacOSX(), llvm::Triple::isMacOSXVersionLT(), llvm::Triple::isMIPS(), llvm::Triple::isOSDarwin(), llvm::Triple::isOSSolaris(), llvm::Triple::isWatchABI(), llvm::Triple::isX86(), llvm::CodeModel::Large, llvm::MCObjectFileInfo::LazySymbolPointerSection, llvm::MCObjectFileInfo::LSDASection, llvm::MCObjectFileInfo::MergeableConst16Section, llvm::MCObjectFileInfo::MergeableConst32Section, llvm::MCObjectFileInfo::MergeableConst4Section, llvm::MCObjectFileInfo::MergeableConst8Section, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::MCObjectFileInfo::NonLazySymbolPointerSection, llvm::MCObjectFileInfo::OmitDwarfIfHaveCompactUnwind, llvm::MCObjectFileInfo::PDataSection, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::MCObjectFileInfo::ReadOnlySection, llvm::MCObjectFileInfo::RemarksSection, llvm::MachO::S_16BYTE_LITERALS, llvm::MachO::S_4BYTE_LITERALS, llvm::MachO::S_8BYTE_LITERALS, llvm::MachO::S_ATTR_DEBUG, llvm::MachO::S_ATTR_LIVE_SUPPORT, llvm::MachO::S_ATTR_NO_TOC, llvm::MachO::S_ATTR_PURE_INSTRUCTIONS, llvm::MachO::S_ATTR_STRIP_STATIC_SYMS, llvm::MachO::S_COALESCED, llvm::MachO::S_CSTRING_LITERALS, llvm::MachO::S_LAZY_SYMBOL_POINTERS, llvm::MachO::S_NON_LAZY_SYMBOL_POINTERS, llvm::MachO::S_THREAD_LOCAL_INIT_FUNCTION_POINTERS, llvm::MachO::S_THREAD_LOCAL_REGULAR, llvm::MachO::S_THREAD_LOCAL_VARIABLE_POINTERS, llvm::MachO::S_THREAD_LOCAL_VARIABLES, llvm::MachO::S_THREAD_LOCAL_ZEROFILL, llvm::MachO::S_ZEROFILL, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_TLS, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_MIPS_DWARF, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_PROGBITS, llvm::ELF::SHT_X86_64_UNWIND, llvm::MCObjectFileInfo::SixteenByteConstantSection, llvm::MCObjectFileInfo::StackMapSection, llvm::MCObjectFileInfo::StackSizesSection, llvm::MCObjectFileInfo::SupportsCompactUnwindWithoutEHFrame, llvm::MCObjectFileInfo::SupportsWeakOmittedEHFrame, llvm::MCObjectFileInfo::SXDataSection, llvm::MCObjectFileInfo::TextCoalSection, llvm::MCObjectFileInfo::TextSection, llvm::MCObjectFileInfo::ThreadLocalPointerSection, llvm::Triple::thumb, llvm::MCObjectFileInfo::TLSBSSSection, llvm::MCObjectFileInfo::TLSDataSection, llvm::MCObjectFileInfo::TLSExtraDataSection, llvm::MCObjectFileInfo::TLSThreadInitSection, llvm::MCObjectFileInfo::TLSTLVSection, llvm::MCObjectFileInfo::UStringSection, llvm::Triple::x86_64, llvm::MCObjectFileInfo::XDataSection, llvm::XCOFF::XMC_PR, llvm::XCOFF::XMC_RO, llvm::XCOFF::XMC_RW, and llvm::XCOFF::XTY_SD.