LLVM: lib/MC/MCStreamer.cpp File Reference
MCStreamer.cpp File Reference
#include "llvm/MC/MCStreamer.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeView.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCRegister.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCWin64EH.h"
#include "llvm/MC/MCWinEH.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <utility>
Functions
template<typename T >
static void copyBytesForDefRange (SmallString< 20 > &BytePrefix, codeview::SymbolKind SymKind, const T &DefRangeHeader)
Only call this on endian-specific types like ulittle16_t and little32_t, or structs composed of them.
static MCSection * getWinCFISection (MCContext &Context, unsigned *NextWinCFIID, MCSection *MainCFISec, const MCSection *TextSec)
static unsigned encodeSEHRegNum (MCContext &Ctx, MCRegister Reg)
Function Documentation
copyBytesForDefRange()
template<typename T > static void copyBytesForDefRange (SmallString< 20 > & BytePrefix, codeview::SymbolKind SymKind, const T & DefRangeHeader) static
Only call this on endian-specific types like ulittle16_t and little32_t, or structs composed of them.
Definition at line 336 of file MCStreamer.cpp.
References llvm::SmallVectorImpl< char >::resize().
Referenced by llvm::MCStreamer::EmitCVDefRangeDirective().
encodeSEHRegNum()
static unsigned encodeSEHRegNum (MCContext & Ctx, MCRegister Reg) static
Definition at line 815 of file MCStreamer.cpp.
References llvm::MCContext::getRegisterInfo(), and llvm::MCRegisterInfo::getSEHRegNum().
Referenced by llvm::MCStreamer::EmitWinCFIPushReg(), llvm::MCStreamer::EmitWinCFISaveReg(), llvm::MCStreamer::EmitWinCFISaveXMM(), and llvm::MCStreamer::EmitWinCFISetFrame().
getWinCFISection()
static MCSection* getWinCFISection (MCContext & Context, unsigned * NextWinCFIID, MCSection * MainCFISec, const MCSection * TextSec) static
Definition at line 766 of file MCStreamer.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCContext::getAssociativeCOFFSection(), llvm::MCContext::getCOFFSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getTextSection(), llvm::MCAsmInfo::hasCOFFAssociativeComdats(), llvm::COFF::IMAGE_COMDAT_SELECT_ANY, and llvm::COFF::IMAGE_SCN_LNK_COMDAT.
Referenced by llvm::MCStreamer::getAssociatedPDataSection(), and llvm::MCStreamer::getAssociatedXDataSection().