LLVM: lib/MC/MCWin64EH.cpp File Reference
MCWin64EH.cpp File Reference
#include "llvm/MC/MCWin64EH.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Win64EH.h"
Functions
static uint8_t CountOfUnwindCodes (std::vector< WinEH::Instruction > &Insns)
static void EmitAbsDifference (MCStreamer &Streamer, const MCSymbol *LHS, const MCSymbol *RHS)
static void EmitUnwindCode (MCStreamer &streamer, const MCSymbol *begin, WinEH::Instruction &inst)
static void EmitSymbolRefWithOfs (MCStreamer &streamer, const MCSymbol *Base, const MCSymbol *Other)
static void EmitRuntimeFunction (MCStreamer &streamer, const WinEH::FrameInfo *info)
static void EmitUnwindInfo (MCStreamer &streamer, WinEH::FrameInfo *info)
static int64_t GetAbsDifference (MCStreamer &Streamer, const MCSymbol *LHS, const MCSymbol *RHS)
static uint32_t ARM64CountOfUnwindCodes (const std::vector< WinEH::Instruction > &Insns)
static void ARM64EmitUnwindCode (MCStreamer &streamer, const MCSymbol *begin, WinEH::Instruction &inst)
static MCSymbol * FindMatchingEpilog (const std::vector< WinEH::Instruction > &EpilogInstrs, const std::vector< MCSymbol *> &Epilogs, const WinEH::FrameInfo *info)
static void ARM64EmitUnwindInfo (MCStreamer &streamer, WinEH::FrameInfo *info)
static void ARM64EmitRuntimeFunction (MCStreamer &streamer, const WinEH::FrameInfo *info)
Function Documentation
ARM64CountOfUnwindCodes()
static uint32_t ARM64CountOfUnwindCodes (const std::vector< WinEH::Instruction > & Insns) static
Definition at line 268 of file MCWin64EH.cpp.
References I, llvm_unreachable, llvm::Win64EH::UOP_AddFP, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocMedium, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_SaveFPLR, llvm::Win64EH::UOP_SaveFPLRX, llvm::Win64EH::UOP_SaveFReg, llvm::Win64EH::UOP_SaveFRegP, llvm::Win64EH::UOP_SaveFRegPX, llvm::Win64EH::UOP_SaveFRegX, llvm::Win64EH::UOP_SaveReg, llvm::Win64EH::UOP_SaveRegP, llvm::Win64EH::UOP_SaveRegPX, llvm::Win64EH::UOP_SaveRegX, and llvm::Win64EH::UOP_SetFP.
Referenced by ARM64EmitUnwindInfo().
ARM64EmitRuntimeFunction()
static void ARM64EmitRuntimeFunction (MCStreamer & streamer, const WinEH::FrameInfo * info) static
Definition at line 645 of file MCWin64EH.cpp.
References llvm::WinEH::FrameInfo::Begin, llvm::MCSymbolRefExpr::create(), EmitSymbolRefWithOfs(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::WinEH::FrameInfo::Function, llvm::MCStreamer::getContext(), llvm::WinEH::FrameInfo::Symbol, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::ARM64UnwindEmitter::Emit().
ARM64EmitUnwindCode()
static void ARM64EmitUnwindCode (MCStreamer & streamer, const MCSymbol * begin, WinEH::Instruction & inst) static
Definition at line 332 of file MCWin64EH.cpp.
References assert(), llvm::MCStreamer::EmitIntValue(), llvm_unreachable, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::Instruction::Register, llvm::Win64EH::UOP_AddFP, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocMedium, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_SaveFPLR, llvm::Win64EH::UOP_SaveFPLRX, llvm::Win64EH::UOP_SaveFReg, llvm::Win64EH::UOP_SaveFRegP, llvm::Win64EH::UOP_SaveFRegPX, llvm::Win64EH::UOP_SaveFRegX, llvm::Win64EH::UOP_SaveReg, llvm::Win64EH::UOP_SaveRegP, llvm::Win64EH::UOP_SaveRegPX, llvm::Win64EH::UOP_SaveRegX, and llvm::Win64EH::UOP_SetFP.
Referenced by ARM64EmitUnwindInfo().
ARM64EmitUnwindInfo()
static void ARM64EmitUnwindInfo (MCStreamer & streamer, WinEH::FrameInfo * info) static
Definition at line 493 of file MCWin64EH.cpp.
References ARM64CountOfUnwindCodes(), ARM64EmitUnwindCode(), assert(), llvm::WinEH::FrameInfo::Begin, llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::WinEH::FrameInfo::EpilogMap, llvm::WinEH::FrameInfo::ExceptionHandler, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), FindMatchingEpilog(), llvm::WinEH::FrameInfo::FuncletOrFuncEnd, GetAbsDifference(), llvm::MCStreamer::getContext(), llvm::WinEH::FrameInfo::HandlesExceptions, I, llvm::WinEH::FrameInfo::Instructions, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), llvm::report_fatal_error(), llvm::WinEH::FrameInfo::Symbol, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::ARM64UnwindEmitter::Emit(), and llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo().
CountOfUnwindCodes()
static uint8_t CountOfUnwindCodes (std::vector< WinEH::Instruction > & Insns) static
Definition at line 24 of file MCWin64EH.cpp.
References I, llvm_unreachable, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_PushMachFrame, llvm::Win64EH::UOP_PushNonVol, llvm::Win64EH::UOP_SaveNonVol, llvm::Win64EH::UOP_SaveNonVolBig, llvm::Win64EH::UOP_SaveXMM128, llvm::Win64EH::UOP_SaveXMM128Big, and llvm::Win64EH::UOP_SetFPReg.
Referenced by EmitUnwindInfo().
EmitAbsDifference()
static void EmitAbsDifference (MCStreamer & Streamer, const MCSymbol * LHS, const MCSymbol * RHS) static
Definition at line 52 of file MCWin64EH.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::EmitValue(), and llvm::MCStreamer::getContext().
Referenced by EmitUnwindCode(), and EmitUnwindInfo().
EmitRuntimeFunction()
static void EmitRuntimeFunction (MCStreamer & streamer, const WinEH::FrameInfo * info) static
Definition at line 142 of file MCWin64EH.cpp.
References llvm::WinEH::FrameInfo::Begin, llvm::MCSymbolRefExpr::create(), EmitSymbolRefWithOfs(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::WinEH::FrameInfo::End, llvm::WinEH::FrameInfo::Function, llvm::MCStreamer::getContext(), llvm::WinEH::FrameInfo::Symbol, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), and EmitUnwindInfo().
EmitSymbolRefWithOfs()
static void EmitSymbolRefWithOfs (MCStreamer & streamer, const MCSymbol * Base, const MCSymbol * Other) static
Definition at line 129 of file MCWin64EH.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::getContext(), and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by ARM64EmitRuntimeFunction(), and EmitRuntimeFunction().
EmitUnwindCode()
static void EmitUnwindCode (MCStreamer & streamer, const MCSymbol * begin, WinEH::Instruction & inst) static
Definition at line 61 of file MCWin64EH.cpp.
References EmitAbsDifference(), llvm::MCStreamer::EmitIntValue(), llvm::WinEH::Instruction::Label, llvm_unreachable, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::Instruction::Register, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_PushMachFrame, llvm::Win64EH::UOP_PushNonVol, llvm::Win64EH::UOP_SaveNonVol, llvm::Win64EH::UOP_SaveNonVolBig, llvm::Win64EH::UOP_SaveXMM128, llvm::Win64EH::UOP_SaveXMM128Big, and llvm::Win64EH::UOP_SetFPReg.
Referenced by EmitUnwindInfo().
EmitUnwindInfo()
static void EmitUnwindInfo (MCStreamer & streamer, WinEH::FrameInfo * info) static
Definition at line 154 of file MCWin64EH.cpp.
References assert(), llvm::WinEH::FrameInfo::Begin, llvm::WinEH::FrameInfo::ChainedParent, CountOfUnwindCodes(), llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), EmitAbsDifference(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), EmitRuntimeFunction(), EmitUnwindCode(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::WinEH::FrameInfo::ExceptionHandler, llvm::MCStreamer::getContext(), llvm::WinEH::FrameInfo::HandlesExceptions, llvm::WinEH::FrameInfo::HandlesUnwind, llvm::WinEH::FrameInfo::Instructions, llvm::WinEH::FrameInfo::LastFrameInst, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::FrameInfo::PrologEnd, llvm::WinEH::Instruction::Register, llvm::WinEH::FrameInfo::Symbol, llvm::Win64EH::UNW_ChainInfo, llvm::Win64EH::UNW_ExceptionHandler, llvm::Win64EH::UNW_TerminateHandler, llvm::Win64EH::UOP_SetFPReg, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), and llvm::Win64EH::UnwindEmitter::EmitUnwindInfo().
FindMatchingEpilog()
static MCSymbol* FindMatchingEpilog (const std::vector< WinEH::Instruction > & EpilogInstrs, const std::vector< MCSymbol *> & Epilogs, const WinEH::FrameInfo * info) static
Definition at line 464 of file MCWin64EH.cpp.
References assert(), llvm::WinEH::FrameInfo::EpilogMap, llvm::Match, and Operation.
Referenced by ARM64EmitUnwindInfo().
GetAbsDifference()
static int64_t GetAbsDifference (MCStreamer & Streamer, const MCSymbol * LHS, const MCSymbol * RHS) static
Definition at line 251 of file MCWin64EH.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), and llvm::report_fatal_error().
Referenced by ARM64EmitUnwindInfo().