LLVM: lib/Analysis/MemorySSAUpdater.cpp File Reference
MemorySSAUpdater.cpp File Reference
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/IteratedDominanceFrontier.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormattedStream.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "memoryssa"
Functions
static void setMemoryPhiValueForBlock (MemoryPhi *MP, const BasicBlock *BB, MemoryAccess *NewDef)
static MemoryAccess * getNewDefiningAccessForClone (MemoryAccess *MA, const ValueToValueMapTy &VMap, PhiToDefMap &MPhiMap, bool CloneWasSimplified, MemorySSA *MSSA)
static MemoryAccess * onlySingleValue (MemoryPhi *MP)
If all arguments of a MemoryPHI are defined by the same incoming argument, return that argument.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memoryssa"
Definition at line 29 of file MemorySSAUpdater.cpp.
Function Documentation
getNewDefiningAccessForClone()
static MemoryAccess* getNewDefiningAccessForClone (MemoryAccess * MA, const ValueToValueMapTy & VMap, PhiToDefMap & MPhiMap, bool CloneWasSimplified, MemorySSA * MSSA) static
Definition at line 545 of file MemorySSAUpdater.cpp.
References assert(), llvm::sys::path::begin(), llvm::MemorySSA::createDefinedAccess(), llvm::MemorySSA::End, llvm::MemorySSA::getBlockAccesses(), llvm::MemorySSA::getBlockDefs(), llvm::MemorySSA::getMemoryAccess(), llvm::MemorySSA::insertIntoListsForBlock(), llvm::MemorySSA::isLiveOnEntryDef(), llvm::ValueMap< KeyT, ValueT, Config >::lookup(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
onlySingleValue()
static MemoryAccess* onlySingleValue (MemoryPhi * MP) static
If all arguments of a MemoryPHI are defined by the same incoming argument, return that argument.
Definition at line 1230 of file MemorySSAUpdater.cpp.
References Arg, and llvm::User::operands().
Referenced by llvm::MemorySSAUpdater::removeMemoryAccess().
setMemoryPhiValueForBlock()
static void setMemoryPhiValueForBlock (MemoryPhi * MP, const BasicBlock * BB, MemoryAccess * NewDef) static
Definition at line 289 of file MemorySSAUpdater.cpp.
References assert(), llvm::MemoryPhi::block_begin(), llvm::MemoryPhi::block_end(), llvm::MemoryPhi::getBasicBlockIndex(), and llvm::MemoryPhi::setIncomingValue().
Referenced by llvm::MemorySSAUpdater::insertDef().