LLVM: lib/Analysis/MemoryBuiltins.cpp File Reference
MemoryBuiltins.cpp File Reference
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/TargetFolder.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/Utils/Local.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <utility>
Classes
struct AllocFnsTy
Macros
#define DEBUG_TYPE "memory-builtins"
Enumerations
enum AllocType : uint8_t {
OpNewLike = 1<<0, MallocLike = 1<<1 | OpNewLike, CallocLike = 1<<2, ReallocLike = 1<<3,
StrDupLike = 1<<4, MallocOrCallocLike = MallocLike | CallocLike, AllocLike = MallocLike | CallocLike | StrDupLike, AnyAlloc = AllocLike | ReallocLike
}
Functions
static const Function * getCalledFunction (const Value *V, bool LookThroughBitCast, bool &IsNoBuiltin)
static Optional< AllocFnsTy > getAllocationDataForFunction (const Function *Callee, AllocType AllocTy, const TargetLibraryInfo *TLI)
Returns the allocation data for the given value if it's either a call to a known allocation function, or a call to a function with the allocsize attribute.
static Optional< AllocFnsTy > getAllocationData (const Value *V, AllocType AllocTy, const TargetLibraryInfo *TLI, bool LookThroughBitCast=false)
static Optional< AllocFnsTy > getAllocationData (const Value *V, AllocType AllocTy, function_ref< const TargetLibraryInfo &(Function &)> GetTLI, bool LookThroughBitCast=false)
static Optional< AllocFnsTy > getAllocationSize (const Value *V, const TargetLibraryInfo *TLI)
static bool hasNoAliasAttr (const Value *V, bool LookThroughBitCast)
static Value * computeArraySize (const CallInst *CI, const DataLayout &DL, const TargetLibraryInfo *TLI, bool LookThroughSExt=false)
static APInt getSizeWithOverflow (const SizeOffsetType &Data)
STATISTIC (ObjectVisitorArgument, "Number of arguments with unsolved size and offset")
STATISTIC (ObjectVisitorLoad, "Number of load instructions with unsolved size and offset")
Variables
static const std::pair< LibFunc, AllocFnsTy > AllocationFnData []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memory-builtins"
Definition at line 50 of file MemoryBuiltins.cpp.
Enumeration Type Documentation
AllocType
enum AllocType : uint8_t
Enumerator
OpNewLike
MallocLike
CallocLike
ReallocLike
StrDupLike
MallocOrCallocLike
AllocLike
AnyAlloc
Definition at line 52 of file MemoryBuiltins.cpp.
Function Documentation
computeArraySize()
static Value* computeArraySize (const CallInst * CI, const DataLayout & DL, const TargetLibraryInfo * TLI, bool LookThroughSExt = false) static
Definition at line 326 of file MemoryBuiltins.cpp.
References llvm::ComputeMultiple(), llvm::CallBase::getArgOperand(), llvm::getMallocAllocatedType(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::DataLayout::getTypeAllocSize(), llvm::Type::isSized(), and llvm::ARM_MB::ST.
Referenced by llvm::getMallocArraySize().
getAllocationData() [1/2]
static Optional<AllocFnsTy> getAllocationData (const Value * V, AllocType AllocTy, const TargetLibraryInfo * TLI, bool LookThroughBitCast = false) static
Definition at line 172 of file MemoryBuiltins.cpp.
References Callee, getAllocationDataForFunction(), getCalledFunction(), and llvm::None.
Referenced by llvm::isAllocationFn(), llvm::isAllocLikeFn(), llvm::isCallocLikeFn(), llvm::isMallocLikeFn(), llvm::isMallocOrCallocLikeFn(), llvm::isOpNewLikeFn(), llvm::isReallocLikeFn(), and llvm::isStrdupLikeFn().
getAllocationData() [2/2]
static Optional<AllocFnsTy> getAllocationData (const Value * V, AllocType AllocTy, function_ref< const TargetLibraryInfo &(Function &)> GetTLI, bool LookThroughBitCast = false) static
Definition at line 184 of file MemoryBuiltins.cpp.
References Callee, getAllocationDataForFunction(), getCalledFunction(), and llvm::None.
getAllocationDataForFunction()
static Optional<AllocFnsTy> getAllocationDataForFunction (const Function * Callee, AllocType AllocTy, const TargetLibraryInfo * TLI) static
Returns the allocation data for the given value if it's either a call to a known allocation function, or a call to a function with the allocsize attribute.
Definition at line 135 of file MemoryBuiltins.cpp.
References AllocationFnData, AllocFnsTy::AllocTy, llvm::sys::path::end(), llvm::find_if(), AllocFnsTy::FstParam, llvm::Type::getContext(), llvm::Function::getFunctionType(), llvm::Type::getInt8PtrTy(), llvm::TargetLibraryInfo::getLibFunc(), llvm::Value::getName(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), llvm::TargetLibraryInfo::has(), llvm::Type::isIntegerTy(), llvm::None, AllocFnsTy::NumParams, P, and AllocFnsTy::SndParam.
Referenced by getAllocationData(), getAllocationSize(), and llvm::isReallocLikeFn().
getAllocationSize()
static Optional<AllocFnsTy> getAllocationSize (const Value * V, const TargetLibraryInfo * TLI) static
Definition at line 196 of file MemoryBuiltins.cpp.
References AllocFnsTy::AllocTy, AnyAlloc, llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::Attribute, Callee, llvm::Data, AllocFnsTy::FstParam, getAllocationDataForFunction(), llvm::Attribute::getAllocSizeArgs(), getCalledFunction(), llvm::Function::getFnAttribute(), llvm::User::getNumOperands(), MallocLike, llvm::None, AllocFnsTy::NumParams, and AllocFnsTy::SndParam.
Referenced by llvm::ObjectSizeOffsetVisitor::visitCallSite(), and llvm::ObjectSizeOffsetEvaluator::visitCallSite().
getCalledFunction()
static const Function* getCalledFunction (const Value * V, bool LookThroughBitCast, bool & IsNoBuiltin) static
Definition at line 111 of file MemoryBuiltins.cpp.
References Callee, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isNoBuiltin(), and llvm::Value::stripPointerCasts().
Referenced by CreateGCRelocates(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::doesNotThrow(), llvm::orc::SpeculateQuery::findCalles(), getAllocationData(), getAllocationSize(), llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::getIntrinsicID(), llvm::CallBase::getIntrinsicID(), llvm::CallBase::getReturnedArgOperand(), llvm::CallBase::hasRetAttr(), llvm::isFreeCall(), llvm::StatepointBase< Function, Instruction, Value, CallBase >::paramHasAttr(), llvm::CallBase::paramHasAttr(), and llvm::InstCombiner::visitFDiv().
getSizeWithOverflow()
static APInt getSizeWithOverflow (const SizeOffsetType & Data) static
Definition at line 481 of file MemoryBuiltins.cpp.
Referenced by llvm::getObjectSize(), and llvm::ObjectSizeOffsetVisitor::visitSelectInst().
hasNoAliasAttr()
static bool hasNoAliasAttr (const Value * V, bool LookThroughBitCast) static
Definition at line 227 of file MemoryBuiltins.cpp.
References llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::hasRetAttr(), llvm::NoAlias, and llvm::Value::stripPointerCasts().
Referenced by llvm::isNoAliasFn().
STATISTIC() [1/2]
STATISTIC (ObjectVisitorArgument , "Number of arguments with unsolved size and offset")
STATISTIC() [2/2]
STATISTIC (ObjectVisitorLoad , "Number of load instructions with unsolved size and offset")
Variable Documentation
AllocationFnData
const std::pair<LibFunc, AllocFnsTy> AllocationFnData[] static
Definition at line 72 of file MemoryBuiltins.cpp.
Referenced by getAllocationDataForFunction().