LLVM: lib/Transforms/IPO/MergeFunctions.cpp File Reference
MergeFunctions.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/IR/ValueMap.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/MergeFunctions.h"
#include "llvm/Transforms/Utils/FunctionComparator.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <set>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "mergefunc"
Functions
STATISTIC (NumFunctionsMerged, "Number of functions merged")
STATISTIC (NumThunksWritten, "Number of thunks generated")
STATISTIC (NumAliasesWritten, "Number of aliases generated")
STATISTIC (NumDoubleWeak, "Number of new functions created")
INITIALIZE_PASS (MergeFunctionsLegacyPass, "mergefunc", "Merge Functions", false, false) ModulePass *llvm
static bool isEligibleForMerging (Function &F)
Check whether F is eligible for function merging.
static Value * createCast (IRBuilder<> &Builder, Value *V, Type *DestTy)
static bool canCreateThunkFor (Function *F)
Whether this function may be replaced by a forwarding thunk.
static bool canCreateAliasFor (Function *F)
static bool isFuncOrderCorrect (const Function *F, const Function *G)
Variables
static cl::opt< unsigned > NumFunctionsForSanityCheck ("mergefunc-sanity", cl::desc("How many functions in module could be used for " "MergeFunctions pass sanity check. " "'0' disables this check. Works only with '-debug' key."), cl::init(0), cl::Hidden)
static cl::opt< bool > MergeFunctionsPDI ("mergefunc-preserve-debug-info", cl::Hidden, cl::init(false), cl::desc("Preserve debug info in thunk when mergefunc " "transformations are made."))
static cl::opt< bool > MergeFunctionsAliases ("mergefunc-use-aliases", cl::Hidden, cl::init(false), cl::desc("Allow mergefunc to create aliases"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mergefunc"
Definition at line 136 of file MergeFunctions.cpp.
Function Documentation
canCreateAliasFor()
static bool canCreateAliasFor (Function * F) static
Definition at line 756 of file MergeFunctions.cpp.
References assert(), canCreateThunkFor(), llvm::ScaledNumbers::compare(), llvm::Function::copyAttributesFrom(), llvm::GlobalAlias::create(), llvm::Function::Create(), llvm::dbgs(), llvm::GlobalNumberState::erase(), llvm::Function::eraseFromParent(), G, llvm::GlobalValue::getAddressSpace(), llvm::GlobalObject::getAlignment(), llvm::ConstantExpr::getBitCast(), llvm::Function::getFunctionType(), llvm::GlobalValue::getLinkage(), llvm::GlobalValue::getParent(), llvm::GlobalValue::getType(), llvm::GlobalValue::getVisibility(), llvm::GlobalValue::Global, llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasGlobalUnnamedAddr(), llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasWeakLinkage(), I, llvm::GlobalValue::isDiscardableIfUnused(), llvm::GlobalValue::isInterposable(), LLVM_DEBUG, llvm::max(), MergeFunctionsAliases, MergeFunctionsPDI, llvm::GlobalValue::PrivateLinkage, llvm::Value::replaceAllUsesWith(), llvm::GlobalObject::setAlignment(), llvm::GlobalValue::setLinkage(), llvm::Value::takeName(), and llvm::Value::use_empty().
canCreateThunkFor()
static bool canCreateThunkFor (Function * F) static
Whether this function may be replaced by a forwarding thunk.
Definition at line 657 of file MergeFunctions.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::Function::args(), llvm::Function::copyAttributesFrom(), llvm::BasicBlock::Create(), llvm::Function::Create(), createCast(), llvm::dbgs(), llvm::Function::eraseFromParent(), F(), llvm::Function::front(), G, llvm::DebugLoc::get(), llvm::GlobalValue::getAddressSpace(), llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::GlobalObject::getComdat(), llvm::Function::getContext(), llvm::Function::getEntryBlock(), llvm::Function::getFunctionType(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), llvm::Function::getReturnType(), llvm::Function::getSubprogram(), H, llvm::Function::isVarArg(), llvm::Type::isVoidTy(), LLVM_DEBUG, MergeFunctionsPDI, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::CallBase::setAttributes(), llvm::CallBase::setCallingConv(), llvm::GlobalObject::setComdat(), llvm::Instruction::setDebugLoc(), llvm::CallInst::setTailCall(), llvm::BasicBlock::size(), llvm::Function::size(), and llvm::Value::takeName().
Referenced by canCreateAliasFor().
createCast()
static Value* createCast (IRBuilder<> & Builder, Value * V, Type * DestTy) static
Definition at line 485 of file MergeFunctions.cpp.
References Arg, assert(), llvm::BasicBlock::back(), llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::IRBuilder< T, Inserter >::CreateInsertValue(), llvm::IRBuilder< T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), llvm::dbgs(), E, llvm::BasicBlock::end(), llvm::Function::end(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::eraseFromParent(), G, llvm::UndefValue::get(), llvm::Type::getStructElementType(), llvm::Type::getStructNumElements(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), I, llvm::Type::isIntegerTy(), llvm::DILocalVariable::isParameter(), llvm::Type::isPointerTy(), llvm::Type::isStructTy(), LLVM_DEBUG, llvm::makeArrayRef(), llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_back(), llvm::Metadata::print(), llvm::Value::print(), SI, and llvm::Value::users().
Referenced by canCreateThunkFor().
INITIALIZE_PASS()
INITIALIZE_PASS (MergeFunctionsLegacyPass , "mergefunc" , "Merge Functions" , false , false)
Definition at line 318 of file MergeFunctions.cpp.
isEligibleForMerging()
static bool isEligibleForMerging (Function & F) static
Check whether F is eligible for function merging.
Definition at line 407 of file MergeFunctions.cpp.
References llvm::GlobalNumberState::clear(), llvm::dbgs(), F(), first, llvm::FunctionComparator::functionHash(), llvm::ConstantExpr::getBitCast(), llvm::GlobalValue::getType(), llvm::GlobalValue::hasAvailableExternallyLinkage(), I, llvm::ARM_PROC::IE, llvm::GlobalValue::isDeclaration(), LLVM_DEBUG, llvm::stable_sort(), llvm::Value::use_begin(), and llvm::Value::use_end().
isFuncOrderCorrect()
static bool isFuncOrderCorrect (const Function * F, const Function * G) static
Definition at line 885 of file MergeFunctions.cpp.
References assert(), llvm::dbgs(), F(), llvm::Value::getName(), llvm::GlobalValue::hasLocalLinkage(), I, llvm::GlobalValue::isInterposable(), LLVM_DEBUG, llvm::sys::fs::remove(), and llvm::Value::users().
STATISTIC() [1/4]
STATISTIC (NumFunctionsMerged , "Number of functions merged")
STATISTIC() [2/4]
STATISTIC (NumThunksWritten , "Number of thunks generated")
STATISTIC() [3/4]
STATISTIC (NumAliasesWritten , "Number of aliases generated")
STATISTIC() [4/4]
STATISTIC (NumDoubleWeak , "Number of new functions created")
Variable Documentation
MergeFunctionsAliases
cl::opt<bool> MergeFunctionsAliases("mergefunc-use-aliases", cl::Hidden, cl::init(false), cl::desc("Allow mergefunc to create aliases")) static
Referenced by canCreateAliasFor().
MergeFunctionsPDI
cl::opt<bool> MergeFunctionsPDI("mergefunc-preserve-debug-info", cl::Hidden, cl::init(false), cl::desc("Preserve debug info in thunk when mergefunc " "transformations are made.")) static
Referenced by canCreateAliasFor(), and canCreateThunkFor().
NumFunctionsForSanityCheck
cl::opt<unsigned> NumFunctionsForSanityCheck("mergefunc-sanity", cl::desc("How many functions in module could be used for " "MergeFunctions pass sanity check. " "'0' disables this check. Works only with '-debug' key."), cl::init(0), cl::Hidden) static
Referenced by llvm::MergeFunctionsPass::run().