LLVM: lib/Target/Mips/MicroMipsSizeReduction.cpp File Reference
MicroMipsSizeReduction.cpp File Reference
This pass is used to reduce the size of instructions where applicable.
#include "Mips.h"
#include "MipsInstrInfo.h"
#include "MipsSubtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "micromips-reduce-size"
#define MICROMIPS_SIZE_REDUCE_NAME "MicroMips instruction size reduce pass"
Enumerations
enum OperandTransfer
Order of operands to transfer.
enum ReduceType
Reduction type.
Functions
STATISTIC (NumReduced, "Number of instructions reduced (32-bit to 16-bit ones, " "or two instructions into one")
INITIALIZE_PASS (MicroMipsSizeReduce, DEBUG_TYPE, MICROMIPS_SIZE_REDUCE_NAME, false, false) static bool IsSP(const MachineOperand &MO)
static bool isMMThreeBitGPRegister (const MachineOperand &MO)
static bool isMMSourceRegister (const MachineOperand &MO)
static bool GetImm (MachineInstr *MI, unsigned Op, int64_t &Imm)
static bool AddiuspImmValue (int64_t Value)
static bool InRange (int64_t Value, unsigned short Shift, int LBound, int HBound)
static bool ImmInRange (MachineInstr *MI, const ReduceEntry &Entry)
static bool CheckXWPInstr (MachineInstr *MI, bool ReduceToLwp, const ReduceEntry &Entry)
static bool ConsecutiveRegisters (unsigned Reg1, unsigned Reg2)
static bool ConsecutiveInstr (MachineInstr *MI1, MachineInstr *MI2)
static bool IsMovepSrcRegister (unsigned Reg)
static bool IsMovepDestinationReg (unsigned Reg)
static bool IsMovepDestinationRegPair (unsigned R0, unsigned R1)
Detailed Description
This pass is used to reduce the size of instructions where applicable.
TODO: Implement microMIPS64 support.
Definition in file MicroMipsSizeReduction.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "micromips-reduce-size"
Definition at line 22 of file MicroMipsSizeReduction.cpp.
MICROMIPS_SIZE_REDUCE_NAME
#define MICROMIPS_SIZE_REDUCE_NAME "MicroMips instruction size reduce pass"
Definition at line 23 of file MicroMipsSizeReduction.cpp.
Enumeration Type Documentation
OperandTransfer
enum OperandTransfer
Order of operands to transfer.
Definition at line 32 of file MicroMipsSizeReduction.cpp.
ReduceType
enum ReduceType
Reduction type.
Definition at line 45 of file MicroMipsSizeReduction.cpp.
Function Documentation
AddiuspImmValue()
static bool AddiuspImmValue (int64_t Value) static
Definition at line 317 of file MicroMipsSizeReduction.cpp.
CheckXWPInstr()
static bool CheckXWPInstr (MachineInstr * MI, bool ReduceToLwp, const ReduceEntry & Entry) static
Definition at line 351 of file MicroMipsSizeReduction.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), ImmInRange(), and RA.
ConsecutiveInstr()
static bool ConsecutiveInstr (MachineInstr * MI1, MachineInstr * MI2) static
Definition at line 398 of file MicroMipsSizeReduction.cpp.
References ConsecutiveRegisters(), GetImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and MI.
ConsecutiveRegisters()
static bool ConsecutiveRegisters (unsigned Reg1, unsigned Reg2) static
Definition at line 378 of file MicroMipsSizeReduction.cpp.
References RA, Registers, llvm::SmallVectorBase::size(), T1, and llvm::X86II::T8.
Referenced by ConsecutiveInstr().
GetImm()
static bool GetImm (MachineInstr * MI, unsigned Op, int64_t & Imm) static
Definition at line 308 of file MicroMipsSizeReduction.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::isImm().
Referenced by ConsecutiveInstr(), and ImmInRange().
ImmInRange()
static bool ImmInRange (MachineInstr * MI, const ReduceEntry & Entry) static
Definition at line 337 of file MicroMipsSizeReduction.cpp.
References GetImm(), and InRange().
Referenced by CheckXWPInstr().
INITIALIZE_PASS()
INITIALIZE_PASS (MicroMipsSizeReduce , DEBUG_TYPE , MICROMIPS_SIZE_REDUCE_NAME , false , false) const &
Definition at line 282 of file MicroMipsSizeReduction.cpp.
InRange()
static bool InRange (int64_t Value, unsigned short Shift, int LBound, int HBound) static
Definition at line 327 of file MicroMipsSizeReduction.cpp.
Referenced by llvm::ConstantFoldGetElementPtr(), and ImmInRange().
isMMSourceRegister()
static bool isMMSourceRegister (const MachineOperand & MO) static
Definition at line 300 of file MicroMipsSizeReduction.cpp.
References llvm::MachineOperand::getReg(), and llvm::MachineOperand::isReg().
isMMThreeBitGPRegister()
static bool isMMThreeBitGPRegister (const MachineOperand & MO) static
Definition at line 293 of file MicroMipsSizeReduction.cpp.
References llvm::MachineOperand::getReg(), and llvm::MachineOperand::isReg().
Referenced by IsMovepDestinationRegPair().
IsMovepDestinationReg()
static bool IsMovepDestinationReg (unsigned Reg) static
Definition at line 585 of file MicroMipsSizeReduction.cpp.
Referenced by IsMovepDestinationRegPair().
IsMovepDestinationRegPair()
static bool IsMovepDestinationRegPair (unsigned R0, unsigned R1) static
Definition at line 596 of file MicroMipsSizeReduction.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::dbgs(), E, llvm::MachineFunction::end(), llvm::MachineBasicBlock::erase_instr(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getFlags(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isBundle(), isMMThreeBitGPRegister(), IsMovepDestinationReg(), IsMovepSrcRegister(), llvm::MachineInstr::isTransient(), LLVM_DEBUG, llvm_unreachable, MI, Modified, llvm::MachineInstr::setDesc(), and llvm::MachineInstrBuilder::setMIFlags().
IsMovepSrcRegister()
static bool IsMovepSrcRegister (unsigned Reg) static
Definition at line 573 of file MicroMipsSizeReduction.cpp.
Referenced by IsMovepDestinationRegPair().
STATISTIC()
STATISTIC (NumReduced)