LLVM: lib/Demangle/MicrosoftDemangleNodes.cpp File Reference
MicrosoftDemangleNodes.cpp File Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
#include "llvm/Demangle/DemangleConfig.h"
#include "llvm/Demangle/Utility.h"
#include <cctype>
#include <string>
Macros
#define OUTPUT_ENUM_CLASS_VALUE(Enum, Value, Desc)
Functions
static void outputSpaceIfNecessary (OutputStream &OS)
static void outputSingleQualifier (OutputStream &OS, Qualifiers Q)
static bool outputQualifierIfPresent (OutputStream &OS, Qualifiers Q, Qualifiers Mask, bool NeedSpace)
static void outputQualifiers (OutputStream &OS, Qualifiers Q, bool SpaceBefore, bool SpaceAfter)
static void outputCallingConvention (OutputStream &OS, CallingConv CC)
Macro Definition Documentation
OUTPUT_ENUM_CLASS_VALUE
#define OUTPUT_ENUM_CLASS_VALUE (Enum, Value, Desc)
Value:
case Enum::Value:                                                            \
    OS << Desc;                                                                \
    break;
Definition at line 22 of file MicrosoftDemangleNodes.cpp.
Referenced by llvm::ms_demangle::IntrinsicFunctionIdentifierNode::output(), llvm::ms_demangle::PrimitiveTypeNode::outputPre(), and llvm::ms_demangle::TagTypeNode::outputPre().
Function Documentation
outputCallingConvention()
static void outputCallingConvention (OutputStream & OS, CallingConv CC) static
Definition at line 79 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::Cdecl, llvm::ms_demangle::Clrcall, llvm::ms_demangle::Eabi, llvm::ms_demangle::Fastcall, outputSpaceIfNecessary(), llvm::ms_demangle::Pascal, llvm::ms_demangle::Regcall, llvm::ms_demangle::Stdcall, llvm::ms_demangle::Thiscall, and llvm::ms_demangle::Vectorcall.
Referenced by llvm::ms_demangle::FunctionSignatureNode::outputPre(), and llvm::ms_demangle::PointerTypeNode::outputPre().
outputQualifierIfPresent()
static bool outputQualifierIfPresent (OutputStream & OS, Qualifiers Q, Qualifiers Mask, bool NeedSpace) static
Definition at line 53 of file MicrosoftDemangleNodes.cpp.
References outputSingleQualifier().
Referenced by outputQualifiers().
outputQualifiers()
static void outputQualifiers (OutputStream & OS, Qualifiers Q, bool SpaceBefore, bool SpaceAfter) static
Definition at line 65 of file MicrosoftDemangleNodes.cpp.
References outputQualifierIfPresent(), llvm::ms_demangle::Q_Const, llvm::ms_demangle::Q_None, llvm::ms_demangle::Q_Restrict, and llvm::ms_demangle::Q_Volatile.
Referenced by llvm::ms_demangle::SpecialTableSymbolNode::output(), llvm::ms_demangle::PrimitiveTypeNode::outputPre(), llvm::ms_demangle::PointerTypeNode::outputPre(), llvm::ms_demangle::TagTypeNode::outputPre(), and llvm::ms_demangle::ArrayTypeNode::outputPre().
outputSingleQualifier()
static void outputSingleQualifier (OutputStream & OS, Qualifiers Q) static
Definition at line 37 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::Q_Const, llvm::ms_demangle::Q_Restrict, and llvm::ms_demangle::Q_Volatile.
Referenced by outputQualifierIfPresent().
outputSpaceIfNecessary()
static void outputSpaceIfNecessary (OutputStream & OS) static
Definition at line 28 of file MicrosoftDemangleNodes.cpp.
References C.
Referenced by llvm::ms_demangle::VariableSymbolNode::output(), llvm::ms_demangle::FunctionSymbolNode::output(), outputCallingConvention(), and llvm::ms_demangle::PointerTypeNode::outputPre().