LLVM: lib/ObjectYAML/MinidumpYAML.cpp File Reference
MinidumpYAML.cpp File Reference
#include "llvm/ObjectYAML/MinidumpYAML.h"
#include "llvm/Support/Allocator.h"
#include "llvm/BinaryFormat/MinidumpConstants.def"
Classes
struct llvm::yaml::ScalarTraits< FixedSizeHex< N > >
struct llvm::yaml::ScalarTraits< FixedSizeString< N > >
Namespaces
llvm
This class represents lattice values for constants.
llvm::yaml
Macros
#define HANDLE_MDMP_PROTECT(CODE, NAME, NATIVENAME) IO.bitSetCase(Protect, #NATIVENAME, MemoryProtection::NAME);
#define HANDLE_MDMP_MEMSTATE(CODE, NAME, NATIVENAME) IO.bitSetCase(State, #NATIVENAME, MemoryState::NAME);
#define HANDLE_MDMP_MEMTYPE(CODE, NAME, NATIVENAME) IO.bitSetCase(Type, #NATIVENAME, MemoryType::NAME);
#define HANDLE_MDMP_ARCH(CODE, NAME) IO.enumCase(Arch, #NAME, ProcessorArchitecture::NAME);
#define HANDLE_MDMP_PLATFORM(CODE, NAME) IO.enumCase(Plat, #NAME, OSPlatform::NAME);
#define HANDLE_MDMP_STREAM_TYPE(CODE, NAME) IO.enumCase(Type, #NAME, StreamType::NAME);
Functions
template<typename EndianType >
static void mapOptional (yaml::IO &IO, const char *Key, EndianType &Val, typename EndianType::value_type Default)
Perform an optional yaml-mapping of an endian-aware type EndianType.
template<typename MapType , typename EndianType >
static void mapRequiredAs (yaml::IO &IO, const char *Key, EndianType &Val)
Yaml-map an endian-aware type EndianType as some other type MapType.
template<typename MapType , typename EndianType >
static void mapOptionalAs (yaml::IO &IO, const char *Key, EndianType &Val, MapType Default)
Perform an optional yaml-mapping of an endian-aware type EndianType as some other type MapType.
template<typename EndianType >
static void mapRequiredHex (yaml::IO &IO, const char *Key, EndianType &Val)
Yaml-map an endian-aware type as an appropriately-sized hex value.
template<typename EndianType >
static void mapOptionalHex (yaml::IO &IO, const char *Key, EndianType &Val, typename EndianType::value_type Default)
Perform an optional yaml-mapping of an endian-aware type as an appropriately-sized hex value.
static void streamMapping (yaml::IO &IO, RawContentStream &Stream)
static StringRef streamValidate (RawContentStream &Stream)
static void streamMapping (yaml::IO &IO, MemoryInfoListStream &Stream)
static void streamMapping (yaml::IO &IO, MemoryListStream &Stream)
static void streamMapping (yaml::IO &IO, SystemInfoStream &Stream)
static void streamMapping (yaml::IO &IO, TextContentStream &Stream)
static void streamMapping (yaml::IO &IO, MinidumpYAML::ExceptionStream &Stream)
Macro Definition Documentation
HANDLE_MDMP_ARCH
#define HANDLE_MDMP_ARCH (CODE, NAME) IO.enumCase(Arch, #NAME, ProcessorArchitecture::NAME);
HANDLE_MDMP_MEMSTATE
#define HANDLE_MDMP_MEMSTATE (CODE, NAME, NATIVENAME) IO.bitSetCase(State, #NATIVENAME, MemoryState::NAME);
HANDLE_MDMP_MEMTYPE
#define HANDLE_MDMP_MEMTYPE (CODE, NAME, NATIVENAME) IO.bitSetCase(Type, #NATIVENAME, MemoryType::NAME);
HANDLE_MDMP_PLATFORM
#define HANDLE_MDMP_PLATFORM (CODE, NAME) IO.enumCase(Plat, #NAME, OSPlatform::NAME);
HANDLE_MDMP_PROTECT
#define HANDLE_MDMP_PROTECT (CODE, NAME, NATIVENAME) IO.bitSetCase(Protect, #NATIVENAME, MemoryProtection::NAME);
HANDLE_MDMP_STREAM_TYPE
#define HANDLE_MDMP_STREAM_TYPE (CODE, NAME) IO.enumCase(Type, #NAME, StreamType::NAME);
Function Documentation
mapOptional()
template<typename EndianType > static void mapOptional (yaml::IO & IO, const char * Key, EndianType & Val, typename EndianType::value_type Default) inline static
Perform an optional yaml-mapping of an endian-aware type EndianType.
The only purpose of this function is to avoid casting the Default value to the endian type;
Definition at line 20 of file MinidumpYAML.cpp.
Referenced by llvm::yaml::ScalarTraits< FixedSizeString< N > >::mustQuote(), and streamMapping().
mapOptionalAs()
template<typename MapType , typename EndianType > static void mapOptionalAs (yaml::IO & IO, const char * Key, EndianType & Val, MapType Default) inline static
Perform an optional yaml-mapping of an endian-aware type EndianType as some other type MapType.
Definition at line 37 of file MinidumpYAML.cpp.
mapOptionalHex()
template<typename EndianType > static void mapOptionalHex (yaml::IO & IO, const char * Key, EndianType & Val, typename EndianType::value_type Default) inline static
Perform an optional yaml-mapping of an endian-aware type as an appropriately-sized hex value.
Definition at line 62 of file MinidumpYAML.cpp.
References llvm::MinidumpYAML::Stream::~Stream().
Referenced by llvm::MinidumpYAML::Stream::create(), llvm::yaml::ScalarTraits< FixedSizeString< N > >::mustQuote(), and streamMapping().
mapRequiredAs()
template<typename MapType , typename EndianType > static void mapRequiredAs (yaml::IO & IO, const char * Key, EndianType & Val) inline static
Yaml-map an endian-aware type EndianType as some other type MapType.
Definition at line 27 of file MinidumpYAML.cpp.
mapRequiredHex()
template<typename EndianType > static void mapRequiredHex (yaml::IO & IO, const char * Key, EndianType & Val) inline static
Yaml-map an endian-aware type as an appropriately-sized hex value.
Definition at line 54 of file MinidumpYAML.cpp.
Referenced by llvm::MinidumpYAML::Stream::create(), llvm::yaml::ScalarTraits< FixedSizeString< N > >::mustQuote(), and streamMapping().
streamMapping() [1/6]
static void streamMapping (yaml::IO & IO, RawContentStream & Stream) static
Definition at line 290 of file MinidumpYAML.cpp.
References llvm::yaml::BinaryRef::binary_size(), llvm::MinidumpYAML::RawContentStream::Content, and llvm::MinidumpYAML::RawContentStream::Size.
Referenced by streamMapping().
streamMapping() [2/6]
static void streamMapping (yaml::IO & IO, MemoryInfoListStream & Stream) static
Definition at line 307 of file MinidumpYAML.cpp.
References llvm::MinidumpYAML::MemoryInfoListStream::Infos.
streamMapping() [3/6]
static void streamMapping (yaml::IO & IO, MemoryListStream & Stream) static
Definition at line 311 of file MinidumpYAML.cpp.
References llvm::MinidumpYAML::detail::ListStream< EntryT >::Entries, and streamMapping().
streamMapping() [4/6]
static void streamMapping (yaml::IO & IO, SystemInfoStream & Stream) static
Definition at line 319 of file MinidumpYAML.cpp.
References llvm::ARM, llvm::minidump::CPUInfo::Arm, llvm::minidump::SystemInfo::BuildNumber, llvm::minidump::SystemInfo::CPU, llvm::MinidumpYAML::SystemInfoStream::CSDVersion, llvm::MinidumpYAML::SystemInfoStream::Info, llvm::minidump::SystemInfo::MajorVersion, mapOptional(), mapOptionalHex(), llvm::minidump::SystemInfo::MinorVersion, llvm::minidump::SystemInfo::NumberOfProcessors, llvm::minidump::CPUInfo::Other, llvm::minidump::SystemInfo::PlatformId, llvm::minidump::SystemInfo::ProcessorArch, llvm::minidump::SystemInfo::ProcessorLevel, llvm::minidump::SystemInfo::ProcessorRevision, llvm::minidump::SystemInfo::ProductType, llvm::minidump::SystemInfo::Reserved, llvm::minidump::SystemInfo::SuiteMask, and llvm::minidump::CPUInfo::X86.
streamMapping() [5/6]
static void streamMapping (yaml::IO & IO, TextContentStream & Stream) static
Definition at line 349 of file MinidumpYAML.cpp.
References llvm::MinidumpYAML::detail::ListStream< EntryT >::Entries, mapOptionalHex(), mapRequiredHex(), llvm::minidump::MemoryDescriptor::StartOfMemoryRange, streamMapping(), and llvm::MinidumpYAML::TextContentStream::Text.
streamMapping() [6/6]
static void streamMapping (yaml::IO & IO, MinidumpYAML::ExceptionStream & Stream) static
Definition at line 374 of file MinidumpYAML.cpp.
References llvm::SmallString< InternalLen >::c_str(), llvm::MinidumpYAML::Stream::create(), llvm::MinidumpYAML::Stream::Exception, llvm::minidump::Exception::ExceptionAddress, llvm::minidump::Exception::ExceptionCode, llvm::minidump::Exception::ExceptionFlags, llvm::minidump::Exception::ExceptionInformation, llvm::minidump::Exception::ExceptionRecord, llvm::minidump::ExceptionStream::ExceptionRecord, llvm::tgtok::Field, llvm::minidump::Header::Flags, llvm::MinidumpYAML::Object::Header, llvm_unreachable, mapOptional(), mapOptionalHex(), mapRequiredHex(), llvm::minidump::Exception::MaxParameters, llvm::MinidumpYAML::ExceptionStream::MDExceptionStream, llvm::MinidumpYAML::Stream::MemoryInfoList, llvm::MinidumpYAML::Stream::MemoryList, llvm::MinidumpYAML::Stream::ModuleList, Name, llvm::minidump::Exception::NumberParameters, llvm::RISCVFenceField::O, llvm::MinidumpYAML::Stream::RawContent, llvm::minidump::Header::Signature, streamMapping(), llvm::MinidumpYAML::Object::Streams, streamValidate(), llvm::MinidumpYAML::Stream::SystemInfo, llvm::MinidumpYAML::Stream::TextContent, llvm::MinidumpYAML::ExceptionStream::ThreadContext, llvm::minidump::ExceptionStream::ThreadId, llvm::MinidumpYAML::Stream::ThreadList, llvm::Twine::toVector(), llvm::Type::Type(), llvm::RISCVFeatures::validate(), and llvm::minidump::Header::Version.
streamValidate()
static StringRef streamValidate (RawContentStream & Stream) static
Definition at line 295 of file MinidumpYAML.cpp.
References llvm::yaml::BinaryRef::binary_size(), llvm::MinidumpYAML::RawContentStream::Content, and llvm::MinidumpYAML::RawContentStream::Size.
Referenced by streamMapping().