LLVM: lib/ObjectYAML/MinidumpEmitter.cpp File Reference
MinidumpEmitter.cpp File Reference
#include "llvm/ObjectYAML/MinidumpYAML.h"
#include "llvm/ObjectYAML/yaml2obj.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
llvm
This class represents lattice values for constants.
llvm::yaml
Functions
static LocationDescriptor layout (BlobAllocator &File, yaml::BinaryRef Data)
static size_t layout (BlobAllocator &File, MinidumpYAML::ExceptionStream &S)
static void layout (BlobAllocator &File, MemoryListStream::entry_type &Range)
template<typename EntryT >
static size_t layout (BlobAllocator &File, MinidumpYAML::detail::ListStream< EntryT > &S)
static Directory layout (BlobAllocator &File, Stream &S)
bool llvm::yaml::yaml2minidump (MinidumpYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
Function Documentation
layout() [1/5]
static LocationDescriptor layout (BlobAllocator & File, yaml::BinaryRef Data) static
Definition at line 116 of file MinidumpEmitter.cpp.
References llvm::yaml::BinaryRef::binary_size().
Referenced by layout(), llvm::MCAssembler::setDWARFLinetableParams(), and llvm::yaml::yaml2minidump().
layout() [2/5]
static size_t layout (BlobAllocator & File, MinidumpYAML::ExceptionStream & S) static
Definition at line 121 of file MinidumpEmitter.cpp.
References layout(), llvm::MinidumpYAML::ExceptionStream::MDExceptionStream, llvm::MinidumpYAML::ExceptionStream::ThreadContext, and llvm::minidump::ExceptionStream::ThreadContext.
layout() [3/5]
static void layout (BlobAllocator & File, MemoryListStream::entry_type & Range) static
Definition at line 138 of file MinidumpEmitter.cpp.
References File, and layout().
layout() [4/5]
template<typename EntryT > static size_t layout (BlobAllocator & File, MinidumpYAML::detail::ListStream< EntryT > & S) static
Definition at line 155 of file MinidumpEmitter.cpp.
References E, llvm::MinidumpYAML::detail::ListStream< EntryT >::Entries, and layout().
layout() [5/5]
static Directory layout (BlobAllocator & File, Stream & S) static
Definition at line 172 of file MinidumpEmitter.cpp.
References llvm::arrayRefFromStringRef(), llvm::MinidumpYAML::SystemInfoStream::CSDVersion, llvm::minidump::SystemInfo::CSDVersionRVA, llvm::minidump::LocationDescriptor::DataSize, llvm::Optional< T >::getValueOr(), llvm::MinidumpYAML::SystemInfoStream::Info, llvm::MinidumpYAML::MemoryInfoListStream::Infos, llvm::MinidumpYAML::Stream::Kind, layout(), llvm::minidump::Directory::Location, llvm::makeArrayRef(), llvm::minidump::LocationDescriptor::RVA, llvm::MinidumpYAML::RawContentStream::Size, llvm::MinidumpYAML::Stream::Type, and llvm::minidump::Directory::Type.