LLVM: lib/CodeGen/MIRParser/MIParser.cpp File Reference
MIParser.cpp File Reference
#include "llvm/CodeGen/MIRParser/MIParser.h"
#include "MILexer.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/AsmParser/SlotMapping.h"
#include "llvm/CodeGen/GlobalISel/RegisterBank.h"
#include "llvm/CodeGen/GlobalISel/RegisterBankInfo.h"
#include "llvm/CodeGen/MIRFormatter.h"
#include "llvm/CodeGen/MIRPrinter.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LowLevelTypeImpl.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <string>
#include <utility>
Typedefs
typedef function_ref< bool(StringRef::iterator Loc, const Twine &)> ErrorCallbackType
Functions
static void mapValueToSlot (const Value *V, ModuleSlotTracker &MST, DenseMap< unsigned, const Value *> &Slots2Values)
static void initSlots2Values (const Function &F, DenseMap< unsigned, const Value *> &Slots2Values)
Creates the mapping from slot numbers to function's unnamed IR values.
static const char * toString (MIToken::TokenKind TokenKind)
static const char * printImplicitRegisterFlag (const MachineOperand &MO)
static std::string getRegisterName (const TargetRegisterInfo *TRI, unsigned Reg)
static bool isImplicitOperandIn (const MachineOperand &ImplicitOperand, ArrayRef< ParsedMachineOperand > Operands)
Return true if the parsed machine operands contain a given machine operand.
static bool parseIRConstant (StringRef::iterator Loc, StringRef StringValue, PerFunctionMIParsingState &PFS, const Constant *&C, ErrorCallbackType ErrCB)
static bool verifyScalarSize (uint64_t Size)
static bool verifyVectorElementCount (uint64_t NumElts)
static bool verifyAddrSpace (uint64_t AddrSpace)
static bool getHexUint (const MIToken &Token, APInt &Result)
static bool getUnsigned (const MIToken &Token, unsigned &Result, ErrorCallbackType ErrCB)
static bool parseGlobalValue (const MIToken &Token, PerFunctionMIParsingState &PFS, GlobalValue *&GV, ErrorCallbackType ErrCB)
static bool parseIRValue (const MIToken &Token, PerFunctionMIParsingState &PFS, const Value *&V, ErrorCallbackType ErrCB)
static void initSlots2BasicBlocks (const Function &F, DenseMap< unsigned, const BasicBlock *> &Slots2BasicBlocks)
static const BasicBlock * getIRBlockFromSlot (unsigned Slot, const DenseMap< unsigned, const BasicBlock *> &Slots2BasicBlocks)
Typedef Documentation
ErrorCallbackType
typedef function_ref<bool(StringRef::iterator Loc, const Twine &)> ErrorCallbackType
Definition at line 589 of file MIParser.cpp.
Function Documentation
getHexUint()
static bool getHexUint (const MIToken & Token, APInt & Result) static
Definition at line 1720 of file MIParser.cpp.
References assert(), llvm::MIToken::HexLiteral, llvm::MIToken::is(), llvm::MIToken::range(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by getUnsigned(), and parseIRValue().
getIRBlockFromSlot()
static const BasicBlock* getIRBlockFromSlot (unsigned Slot, const DenseMap< unsigned, const BasicBlock *> & Slots2BasicBlocks) static
Definition at line 3117 of file MIParser.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), error, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), initSlots2BasicBlocks(), Name, and llvm::MIToken::StringConstant.
getRegisterName()
static std::string getRegisterName (const TargetRegisterInfo * TRI, unsigned Reg) static
Definition at line 1125 of file MIParser.cpp.
References assert(), llvm::MCRegisterInfo::getName(), and llvm::Register::isPhysicalRegister().
Referenced by EmitHiLo(), isImplicitOperandIn(), llvm::MipsInstPrinter::MipsInstPrinter(), llvm::R600InstPrinter::printOperand(), llvm::VEInstPrinter::printRegName(), llvm::SparcInstPrinter::printRegName(), and llvm::AMDGPUInstPrinter::printRegOperand().
getUnsigned()
static bool getUnsigned (const MIToken & Token, unsigned & Result, ErrorCallbackType ErrCB) static
Definition at line 1737 of file MIParser.cpp.
References assert(), llvm::MachineOperand::CreateFI(), llvm::MachineOperand::CreateMBB(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), error, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MIToken::FixedStackObject, llvm::PerFunctionMIParsingState::FixedStackObjectSlots, llvm::APInt::getBitWidth(), getHexUint(), llvm::APInt::getLimitedValue(), llvm::MachineBasicBlock::getName(), llvm::APInt::getZExtValue(), llvm::MIToken::hasIntegerValue(), llvm::MIToken::HexLiteral, llvm::MIToken::integerValue(), llvm::MIToken::is(), llvm::MIToken::location(), llvm::MIToken::MachineBasicBlock, llvm::MIToken::MachineBasicBlockLabel, llvm::max(), llvm::PerFunctionMIParsingState::MBBSlots, Name, llvm::Number, llvm::parseMBBReference(), llvm::MIToken::StackObject, and llvm::PerFunctionMIParsingState::StackObjectSlots.
Referenced by llvm::DataExtractor::getAddress(), llvm::DataExtractor::getUnsigned(), isImplicitOperandIn(), parseGlobalValue(), parseIRValue(), llvm::DataExtractor::setAddressSize(), and toString().
initSlots2BasicBlocks()
static void initSlots2BasicBlocks (const Function & F, DenseMap< unsigned, const BasicBlock *> & Slots2BasicBlocks) static
Definition at line 3102 of file MIParser.cpp.
References llvm::GlobalValue::getParent(), llvm::Value::hasName(), llvm::ModuleSlotTracker::incorporateFunction(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by getIRBlockFromSlot().
initSlots2Values()
static void initSlots2Values (const Function & F, DenseMap< unsigned, const Value *> & Slots2Values) static
Creates the mapping from slot numbers to function's unnamed IR values.
Definition at line 356 of file MIParser.cpp.
References Arg, llvm::Function::args(), llvm::GlobalValue::getParent(), I, llvm::ModuleSlotTracker::incorporateFunction(), and mapValueToSlot().
Referenced by llvm::PerFunctionMIParsingState::getIRValue().
isImplicitOperandIn()
static bool isImplicitOperandIn (const MachineOperand & ImplicitOperand, ArrayRef< ParsedMachineOperand > Operands) static
Return true if the parsed machine operands contain a given machine operand.
Definition at line 1132 of file MIParser.cpp.
References assert(), llvm::ArrayRef< T >::back(), llvm::MIToken::colon, llvm::MIToken::comma, llvm::MachineOperand::CreateImm(), llvm::MachineOperand::CreateReg(), llvm::VRegInfo::D, llvm::RegState::Dead, llvm::RegState::Debug, llvm::RegState::Define, llvm::MIToken::dot, E, llvm::RegState::EarlyClobber, llvm::ArrayRef< T >::empty(), error, llvm::VRegInfo::Explicit, llvm::MachineInstr::FmAfn, llvm::MachineInstr::FmArcp, llvm::MachineInstr::FmContract, llvm::MachineInstr::FmNoInfs, llvm::MachineInstr::FmNoNans, llvm::MachineInstr::FmNsz, llvm::MachineInstr::FmReassoc, llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, llvm::VRegInfo::GENERIC, llvm::MCInstrDesc::getImplicitDefs(), llvm::MCInstrDesc::getImplicitUses(), llvm::PerTargetMIParsingState::getRegBank(), llvm::PerTargetMIParsingState::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), llvm::MachineFunction::getRegInfo(), llvm::PerTargetMIParsingState::getRegisterByName(), llvm::TargetSubtargetInfo::getRegisterInfo(), getRegisterName(), llvm::PerTargetMIParsingState::getSubRegIndex(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getType(), getUnsigned(), llvm::PerFunctionMIParsingState::getVRegInfo(), llvm::PerFunctionMIParsingState::getVRegInfoNamed(), I, llvm::MIToken::Identifier, llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, llvm::MCInstrDesc::ImplicitDefs, llvm::MCInstrDesc::ImplicitUses, llvm::MIToken::IntegerLiteral, llvm::RegState::InternalRead, llvm::MCInstrDesc::isCall(), llvm::MachineInstr::IsExact, llvm::MachineOperand::isIdenticalTo(), llvm::LLT::isValid(), llvm::Register::isVirtualRegister(), llvm::RegState::Kill, llvm::VRegInfo::Kind, llvm::MIToken::kw_afn, llvm::MIToken::kw_arcp, llvm::MIToken::kw_contract, llvm::MIToken::kw_dead, llvm::MIToken::kw_debug_use, llvm::MIToken::kw_def, llvm::MIToken::kw_early_clobber, llvm::MIToken::kw_exact, llvm::MIToken::kw_frame_destroy, llvm::MIToken::kw_frame_setup, llvm::MIToken::kw_implicit, llvm::MIToken::kw_implicit_define, llvm::MIToken::kw_internal, llvm::MIToken::kw_killed, llvm::MIToken::kw_ninf, llvm::MIToken::kw_nnan, llvm::MIToken::kw_nofpexcept, llvm::MIToken::kw_nsw, llvm::MIToken::kw_nsz, llvm::MIToken::kw_nuw, llvm::MIToken::kw_reassoc, llvm::MIToken::kw_renamable, llvm::MIToken::kw_tied_def, llvm::MIToken::kw_undef, llvm_unreachable, llvm::MIToken::lparen, llvm::PerFunctionMIParsingState::MF, MRI, Name, llvm::MIToken::NamedRegister, llvm::MIToken::NamedVirtualRegister, llvm::MachineInstr::NoFPExcept, llvm::VRegInfo::NORMAL, llvm::MachineInstr::NoSWrap, llvm::MachineInstr::NoUWrap, Operands, llvm::MIRFormatter::parseImmMnemonic(), llvm::PerTargetMIParsingState::parseInstrName(), printImplicitRegisterFlag(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::VRegInfo::RC, Reg, llvm::VRegInfo::REGBANK, llvm::VRegInfo::RegBank, llvm::RegState::Renamable, llvm::MIToken::rparen, llvm::MachineRegisterInfo::setRegClassOrRegBank(), llvm::MachineRegisterInfo::setType(), llvm::ArrayRef< T >::size(), SubReg, llvm::PerFunctionMIParsingState::Target, llvm::MachineInstr::tieOperands(), TRI, llvm::RegState::Undef, llvm::MIToken::underscore, llvm::VRegInfo::UNKNOWN, llvm::MIToken::VirtualRegister, and llvm::VRegInfo::VReg.
mapValueToSlot()
static void mapValueToSlot (const Value * V, ModuleSlotTracker & MST, DenseMap< unsigned, const Value *> & Slots2Values) static
Definition at line 347 of file MIParser.cpp.
References llvm::ModuleSlotTracker::getLocalSlot(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by initSlots2Values().
parseGlobalValue()
static bool parseGlobalValue (const MIToken & Token, PerFunctionMIParsingState & PFS, GlobalValue *& GV, ErrorCallbackType ErrCB) static
Definition at line 1845 of file MIParser.cpp.
References assert(), llvm::CmpInst::BAD_FCMP_PREDICATE, llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::StringSwitch< T, R >::Case(), llvm::MIToken::colon, llvm::MIToken::comma, llvm::MIToken::ConstantPoolItem, llvm::PerFunctionMIParsingState::ConstantPoolSlots, llvm::MCCFIInstruction::createAdjustCfaOffset(), llvm::MachineOperand::CreateBA(), llvm::MachineOperand::CreateCFIIndex(), llvm::MachineOperand::CreateCPI(), llvm::MCCFIInstruction::createDefCfa(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MachineOperand::CreateES(), llvm::MCCFIInstruction::createEscape(), llvm::MachineOperand::CreateGA(), llvm::MachineOperand::CreateImm(), llvm::MachineOperand::CreateIntrinsicID(), llvm::MachineOperand::CreateJTI(), llvm::MachineOperand::CreateMCSymbol(), llvm::MachineOperand::CreateMetadata(), llvm::MCCFIInstruction::createNegateRAState(), llvm::MCCFIInstruction::createOffset(), llvm::MachineOperand::CreatePredicate(), llvm::MCCFIInstruction::createRegister(), llvm::MachineOperand::CreateRegLiveOut(), llvm::MachineOperand::CreateRegMask(), llvm::MCCFIInstruction::createRelOffset(), llvm::MCCFIInstruction::createRememberState(), llvm::MCCFIInstruction::createRestore(), llvm::MCCFIInstruction::createRestoreState(), llvm::MCCFIInstruction::createSameValue(), llvm::MachineOperand::CreateShuffleMask(), llvm::MachineOperand::CreateTargetIndex(), llvm::MCCFIInstruction::createUndefined(), llvm::MCCFIInstruction::createWindowSave(), llvm::StringSwitch< T, R >::Default(), llvm::MIToken::dot, llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), error, llvm::MIToken::Error, llvm::MIToken::exclaim, llvm::MIToken::ExternalSymbol, F(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MIToken::FixedStackObject, llvm::BlockAddress::get(), llvm::MDNode::get(), llvm::dwarf::getAttributeEncoding(), llvm::PerTargetMIParsingState::getBitmaskTargetFlag(), llvm::PerTargetMIParsingState::getDirectTargetFlag(), llvm::APSInt::getExtValue(), llvm::MachineFunction::getFunction(), llvm::Module::getNamedValue(), llvm::dwarf::getOperationEncoding(), llvm::GlobalValue::getParent(), llvm::PerTargetMIParsingState::getRegMask(), llvm::PerTargetMIParsingState::getSubRegIndex(), llvm::PerTargetMIParsingState::getTargetIndex(), getUnsigned(), llvm::Function::getValueSymbolTable(), llvm::MIToken::GlobalValue, llvm::SlotMapping::GlobalValues, llvm::MIToken::HexLiteral, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::MIToken::Identifier, llvm::MIToken::IntegerLiteral, llvm::MIToken::IRBlock, llvm::PerFunctionMIParsingState::IRSlots, llvm::CmpInst::isFPPredicate(), llvm::CmpInst::isIntPredicate(), llvm::isPowerOf2_32(), llvm::MachineOperand::isReg(), llvm::MIToken::JumpTableIndex, llvm::PerFunctionMIParsingState::JumpTableSlots, llvm::MIToken::kind(), llvm::MIToken::kw_addrspace, llvm::MIToken::kw_align, llvm::MIToken::kw_blockaddress, llvm::MIToken::kw_cfi_aarch64_negate_ra_sign_state, llvm::MIToken::kw_cfi_adjust_cfa_offset, llvm::MIToken::kw_cfi_def_cfa, llvm::MIToken::kw_cfi_def_cfa_offset, llvm::MIToken::kw_cfi_def_cfa_register, llvm::MIToken::kw_cfi_escape, llvm::MIToken::kw_cfi_offset, llvm::MIToken::kw_cfi_register, llvm::MIToken::kw_cfi_rel_offset, llvm::MIToken::kw_cfi_remember_state, llvm::MIToken::kw_cfi_restore, llvm::MIToken::kw_cfi_restore_state, llvm::MIToken::kw_cfi_same_value, llvm::MIToken::kw_cfi_undefined, llvm::MIToken::kw_cfi_window_save, llvm::MIToken::kw_dead, llvm::MIToken::kw_debug_use, llvm::MIToken::kw_def, llvm::MIToken::kw_double, llvm::MIToken::kw_early_clobber, llvm::MIToken::kw_float, llvm::MIToken::kw_floatpred, llvm::MIToken::kw_fp128, llvm::MIToken::kw_half, llvm::MIToken::kw_implicit, llvm::MIToken::kw_implicit_define, llvm::MIToken::kw_internal, llvm::MIToken::kw_intpred, llvm::MIToken::kw_intrinsic, llvm::MIToken::kw_killed, llvm::MIToken::kw_liveout, llvm::MIToken::kw_ppc_fp128, llvm::MIToken::kw_renamable, llvm::MIToken::kw_shufflemask, llvm::MIToken::kw_target_flags, llvm::MIToken::kw_target_index, llvm::MIToken::kw_undef, llvm::MIToken::kw_x86_fp80, LLVM_FALLTHROUGH, llvm_unreachable, llvm::MIToken::location(), llvm::ValueSymbolTable::lookup(), llvm::Function::lookupIntrinsicID(), llvm::TargetIntrinsicInfo::lookupName(), llvm::MIToken::lparen, llvm::MIToken::MachineBasicBlock, llvm::BitmaskEnumDetail::Mask(), llvm::MIToken::MCSymbol, llvm::MIToken::md_diexpr, llvm::MIToken::md_dilocation, llvm::SlotMapping::MetadataNodes, llvm::PerFunctionMIParsingState::MF, llvm::MIToken::minus, Name, llvm::MIToken::NamedGlobalValue, llvm::MIToken::NamedIRBlock, llvm::MIToken::NamedRegister, llvm::MIToken::NamedVirtualRegister, llvm::Intrinsic::not_intrinsic, llvm::parseMDNode(), llvm::MIToken::plus, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MIToken::range(), Reg, llvm::MIToken::rparen, llvm::MachineOperand::setOffset(), llvm::MachineOperand::setTargetFlags(), llvm::MIToken::StackObject, llvm::MIToken::stringValue(), llvm::MIToken::SubRegisterIndex, llvm::ARMBuildAttrs::Symbol, llvm::PerFunctionMIParsingState::Target, TII, TRI, UINT64_MAX, llvm::MIToken::underscore, and llvm::MIToken::VirtualRegister.
Referenced by parseIRValue().
parseIRConstant()
static bool parseIRConstant (StringRef::iterator Loc, StringRef StringValue, PerFunctionMIParsingState & PFS, const Constant *& C, ErrorCallbackType ErrCB) static
Definition at line 1567 of file MIParser.cpp.
References llvm::StringRef::str().
Referenced by parseIRValue(), and verifyAddrSpace().
parseIRValue()
static bool parseIRValue (const MIToken & Token, PerFunctionMIParsingState & PFS, const Value *& V, ErrorCallbackType ErrCB) static
Definition at line 2713 of file MIParser.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::MachinePointerInfo::AddrSpace, assert(), C, llvm::StringSwitch< T, R >::Case(), llvm::MIToken::coloncolon, llvm::MIToken::comma, Context, llvm::StringSwitch< T, R >::Default(), error, llvm::MIToken::ExternalSymbol, llvm::MIToken::FixedStackObject, llvm::APInt::getBitWidth(), llvm::MachineFunction::getFunction(), getHexUint(), llvm::PerFunctionMIParsingState::getIRValue(), llvm::PerTargetMIParsingState::getMMOTargetFlag(), llvm::LLVMContext::getOrInsertSyncScopeID(), llvm::Value::getType(), getUnsigned(), llvm::Function::getValueSymbolTable(), llvm::APInt::getZExtValue(), llvm::MIToken::GlobalValue, llvm::MIToken::HexLiteral, llvm::MIToken::Identifier, llvm::MIToken::IntegerLiteral, llvm::MIToken::IRValue, llvm::Type::isPointerTy(), llvm::MIToken::kind(), llvm::MIToken::kw_addrspace, llvm::MIToken::kw_align, llvm::MIToken::kw_call_entry, llvm::MIToken::kw_constant_pool, llvm::MIToken::kw_custom, llvm::MIToken::kw_dereferenceable, llvm::MIToken::kw_got, llvm::MIToken::kw_heap_alloc_marker, llvm::MIToken::kw_invariant, llvm::MIToken::kw_jump_table, llvm::MIToken::kw_non_temporal, llvm::MIToken::kw_post_instr_symbol, llvm::MIToken::kw_pre_instr_symbol, llvm::MIToken::kw_stack, llvm::MIToken::kw_unknown_size, llvm::MIToken::kw_volatile, llvm::MIToken::lbrace, llvm_unreachable, llvm::MIToken::location(), llvm::ValueSymbolTable::lookup(), llvm::MIToken::lparen, llvm::MIToken::MCSymbol, llvm::MIToken::md_alias_scope, llvm::MIToken::md_noalias, llvm::MIToken::md_range, llvm::MIToken::md_tbaa, llvm::PerFunctionMIParsingState::MF, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MONonTemporal, llvm::Monotonic, llvm::MachineMemOperand::MOStore, llvm::MachineMemOperand::MOVolatile, llvm::MIToken::NamedGlobalValue, llvm::MIToken::NamedIRValue, llvm::AAMDNodes::NoAlias, llvm::NotAtomic, parseGlobalValue(), parseIRConstant(), llvm::parseMDNode(), llvm::MIToken::QuotedIRValue, llvm::MIToken::range(), llvm::Release, llvm::MIToken::rparen, llvm::AAMDNodes::Scope, llvm::SequentiallyConsistent, Size, llvm::MIToken::StackObject, llvm::MIToken::StringConstant, llvm::MIToken::stringValue(), llvm::ARMBuildAttrs::Symbol, llvm::SyncScope::System, llvm::PerFunctionMIParsingState::Target, llvm::AAMDNodes::TBAA, TII, llvm::MemoryLocation::UnknownSize, and llvm::Unordered.
Referenced by llvm::MIRFormatter::parseIRValue().
printImplicitRegisterFlag()
static const char* printImplicitRegisterFlag (const MachineOperand & MO) static
Definition at line 1120 of file MIParser.cpp.
References assert(), llvm::MachineOperand::isDef(), and llvm::MachineOperand::isImplicit().
Referenced by isImplicitOperandIn().
toString()
static const char* toString (MIToken::TokenKind TokenKind) static
Definition at line 591 of file MIParser.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineBasicBlock::addSuccessor(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::MachineInstr::BundledPred, llvm::MachineInstr::BundledSucc, llvm::MIToken::colon, llvm::MIToken::coloncolon, llvm::MIToken::comma, llvm::MachineOperand::CreateImm(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MIToken::Eof, llvm::MIToken::equal, error, llvm::LaneBitmask::getAll(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getName(), llvm::BranchProbability::getRaw(), getUnsigned(), llvm::Function::getValueSymbolTable(), llvm::guessSuccessors(), llvm::MIToken::HexLiteral, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineFunction::insert(), llvm::MIToken::IntegerLiteral, llvm::MIToken::IRBlock, llvm::MachineOperand::isReg(), llvm::MIToken::kw_address_taken, llvm::MIToken::kw_align, llvm::MIToken::kw_debug_location, llvm::MIToken::kw_heap_alloc_marker, llvm::MIToken::kw_landing_pad, llvm::MIToken::kw_liveins, llvm::MIToken::kw_post_instr_symbol, llvm::MIToken::kw_pre_instr_symbol, llvm::MIToken::kw_successors, llvm::MIToken::lbrace, llvm::ValueSymbolTable::lookup(), llvm::MIToken::lparen, llvm::MIToken::MachineBasicBlock, llvm::MIToken::MachineBasicBlockLabel, llvm::BitmaskEnumDetail::Mask(), llvm::PerFunctionMIParsingState::MBBSlots, llvm::PerFunctionMIParsingState::MF, MI, Name, llvm::MIToken::NamedRegister, llvm::MIToken::Newline, llvm::MachineBasicBlock::normalizeSuccProbs(), Operands, parse(), llvm::parseMBBReference(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MIToken::rbrace, Reg, llvm::MIToken::rparen, llvm::MachineInstr::setFlag(), llvm::MachineOperand::setIsDebug(), llvm::SmallVectorBase::size(), and llvm::toString().
verifyAddrSpace()
static bool verifyAddrSpace (uint64_t AddrSpace) static
Definition at line 1604 of file MIParser.cpp.
References llvm::all_of(), llvm::lltok::APSInt, assert(), llvm::MachineOperand::CreateCImm(), llvm::MachineOperand::CreateFPImm(), llvm::StringRef::drop_front(), error, llvm::MIToken::FloatingPointLiteral, llvm::DataLayout::getPointerSizeInBits(), llvm::MIToken::greater, llvm::MIToken::HexLiteral, llvm::MIToken::Identifier, llvm::MIToken::IntegerLiteral, llvm::MIToken::less, parseIRConstant(), llvm::LLT::pointer(), llvm::LLT::scalar(), llvm::StringRef::size(), llvm::LLT::vector(), verifyScalarSize(), and verifyVectorElementCount().
verifyScalarSize()
static bool verifyScalarSize (uint64_t Size) static
Definition at line 1596 of file MIParser.cpp.
References llvm::isUInt< 16 >(), and Size.
Referenced by verifyAddrSpace().
verifyVectorElementCount()
static bool verifyVectorElementCount (uint64_t NumElts) static
Definition at line 1600 of file MIParser.cpp.
References llvm::isUInt< 16 >().
Referenced by verifyAddrSpace().