LLVM: lib/Target/Mips/MipsConstantIslandPass.cpp File Reference
MipsConstantIslandPass.cpp File Reference
#include "Mips.h"
#include "Mips16InstrInfo.h"
#include "MipsMachineFunction.h"
#include "MipsSubtarget.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iterator>
#include <vector>
Macros
#define DEBUG_TYPE "mips-constant-islands"
Functions
STATISTIC (NumCPEs, "Number of constpool entries")
STATISTIC (NumSplit, "Number of uncond branches inserted")
STATISTIC (NumCBrFixed, "Number of cond branches fixed")
STATISTIC (NumUBrFixed, "Number of uncond branches fixed")
static unsigned int branchTargetOperand (MachineInstr *MI)
static unsigned int longformBranchOpcode (unsigned int Opcode)
static unsigned int branchMaxOffsets (unsigned int Opcode)
static bool BBHasFallthrough (MachineBasicBlock *MBB)
BBHasFallthrough - Return true if the specified basic block can fallthrough into the block immediately after it.
static bool CompareMBBNumbers (const MachineBasicBlock *LHS, const MachineBasicBlock *RHS)
CompareMBBNumbers - Little predicate function to sort the WaterList by MBB ID.
static bool BBIsJumpedOver (MachineBasicBlock *MBB)
BBIsJumpedOver - Return true of the specified basic block's only predecessor unconditionally branches to its only successor.
static unsigned getUnconditionalBrDisp (int Opc)
getUnconditionalBrDisp - Returns the maximum displacement that can fit in the specific unconditional branch instruction.
Variables
static cl::opt< bool > AlignConstantIslands ("mips-align-constant-islands", cl::Hidden, cl::init(true), cl::desc("Align constant islands in code"))
static cl::opt< int > ConstantIslandsSmallOffset ("mips-constant-islands-small-offset", cl::init(0), cl::desc("Make small offsets be this amount for testing purposes"), cl::Hidden)
static cl::opt< bool > NoLoadRelaxation ("mips-constant-islands-no-load-relaxation", cl::init(false), cl::desc("Don't relax loads to long loads - for testing purposes"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-constant-islands"
Definition at line 60 of file MipsConstantIslandPass.cpp.
Function Documentation
BBHasFallthrough()
bool ARMConstantIslands::BBHasFallthrough (MachineBasicBlock * MBB) static
BBHasFallthrough - Return true if the specified basic block can fallthrough into the block immediately after it.
Definition at line 589 of file MipsConstantIslandPass.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, AlignConstantIslands, assert(), llvm::MachineBasicBlock::begin(), llvm::tgtok::Bits, llvm::numbers::e, E, llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineOperand::getIndex(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), I, llvm_unreachable, MI, op, llvm::BasicBlockInfo::Size, llvm::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and TII.
Referenced by getUnconditionalBrDisp().
BBIsJumpedOver()
static bool BBIsJumpedOver (MachineBasicBlock * MBB) static
BBIsJumpedOver - Return true of the specified basic block's only predecessor unconditionally branches to its only successor.
Definition at line 1000 of file MipsConstantIslandPass.cpp.
References assert(), llvm::MachineBasicBlock::back(), llvm::dbgs(), llvm::numbers::e, llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isCPI(), LLVM_DEBUG, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_size(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIndex(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_size(), and TII.
Referenced by getUnconditionalBrDisp().
branchMaxOffsets()
static unsigned int branchMaxOffsets (unsigned int Opcode) static
Definition at line 134 of file MipsConstantIslandPass.cpp.
References llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addImm(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, AlignConstantIslands, assert(), llvm::tgtok::Bits, llvm::BuildMI(), ConstantIslandsSmallOffset, llvm::dbgs(), llvm::MachineBasicBlock::dump(), llvm::numbers::e, E, llvm::MachineBasicBlock::end(), F(), llvm::format(), llvm::MachineBasicBlock::getAlignment(), llvm::MachineFunction::getConstantPool(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getSubtarget(), getType(), llvm::DataLayout::getTypeAllocSize(), llvm::isPowerOf2_32(), LLVM_DEBUG, LLVM_DUMP_METHOD, llvm_unreachable, llvm::Log2(), llvm::Log2_32(), MI, llvm::neg(), llvm::MachineFunctionProperties::NoVRegs, llvm::BasicBlockInfo::Offset, llvm::MachineBasicBlock::push_back(), rc, llvm::report_fatal_error(), llvm::MachineFunctionProperties::set(), llvm::MachineBasicBlock::setAlignment(), Size, llvm::SmallVectorBase::size(), TII, and llvm::MipsSubtarget::useConstantIslands().
Referenced by getUnconditionalBrDisp().
branchTargetOperand()
static unsigned int branchTargetOperand (MachineInstr * MI) static
Definition at line 88 of file MipsConstantIslandPass.cpp.
References llvm::MachineInstr::getOpcode(), and llvm_unreachable.
Referenced by getUnconditionalBrDisp().
CompareMBBNumbers()
static bool CompareMBBNumbers (const MachineBasicBlock * LHS, const MachineBasicBlock * RHS) static
CompareMBBNumbers - Little predicate function to sort the WaterList by MBB ID.
Definition at line 819 of file MipsConstantIslandPass.cpp.
References llvm::MachineBasicBlock::addSuccessor(), llvm::BuildMI(), llvm::dbgs(), llvm::MachineBasicBlock::end(), llvm::format(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineOperand::getImm(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::insert(), LLVM_DEBUG, llvm::lower_bound(), MI, llvm::Align::None(), llvm::BasicBlockInfo::Offset, llvm::offsetToAlignment(), llvm::BasicBlockInfo::postOffset(), llvm::printMBBReference(), llvm::MachineFunction::RenumberBlocks(), Size, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessors().
getUnconditionalBrDisp()
static unsigned getUnconditionalBrDisp (int Opc) inline static
getUnconditionalBrDisp - Returns the maximum displacement that can fit in the specific unconditional branch instruction.
Definition at line 1148 of file MipsConstantIslandPass.cpp.
References llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addImm(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), B, llvm::MachineBasicBlock::back(), BBHasFallthrough(), BBIsJumpedOver(), llvm::MachineBasicBlock::begin(), branchMaxOffsets(), branchTargetOperand(), llvm::BuildMI(), C, llvm::MachineOperand::CreateCPI(), llvm::MachineOperand::CreateImm(), llvm::dbgs(), llvm::numbers::e, E, llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::find(), llvm::format(), llvm::ConstantInt::get(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::Type::getInt32Ty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineOperand::getMBB(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), I, llvm::MachineBasicBlock::insert(), Int32Ty, llvm::MachineOperand::isCPI(), llvm::MachineOperand::isImm(), llvm::MachineInstr::isUnconditionalBranch(), llvm::Literal, LLVM_DEBUG, llvm::Log2(), longformBranchOpcode(), MI, NoLoadRelaxation, llvm::BasicBlockInfo::postOffset(), llvm::printMBBReference(), llvm::MachineBasicBlock::setAlignment(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIndex(), llvm::MachineOperand::setMBB(), Size, TII, and llvm::Align::value().
longformBranchOpcode()
static unsigned int longformBranchOpcode (unsigned int Opcode) static
Definition at line 107 of file MipsConstantIslandPass.cpp.
References llvm_unreachable.
Referenced by getUnconditionalBrDisp().
STATISTIC() [1/4]
STATISTIC (NumCPEs , "Number of constpool entries")
STATISTIC() [2/4]
STATISTIC (NumSplit , "Number of uncond branches inserted")
STATISTIC() [3/4]
STATISTIC (NumCBrFixed , "Number of cond branches fixed")
STATISTIC() [4/4]
STATISTIC (NumUBrFixed , "Number of uncond branches fixed")
Variable Documentation
AlignConstantIslands
cl::opt<bool> AlignConstantIslands("mips-align-constant-islands", cl::Hidden, cl::init(true), cl::desc("Align constant islands in code")) static
Referenced by BBHasFallthrough(), and branchMaxOffsets().
ConstantIslandsSmallOffset
cl::opt<int> ConstantIslandsSmallOffset("mips-constant-islands-small-offset", cl::init(0), cl::desc("Make small offsets be this amount for testing purposes"), cl::Hidden) static
Referenced by branchMaxOffsets().
NoLoadRelaxation
cl::opt<bool> NoLoadRelaxation("mips-constant-islands-no-load-relaxation", cl::init(false), cl::desc("Don't relax loads to long loads - for testing purposes"), cl::Hidden) static
Referenced by getUnconditionalBrDisp().