LLVM: lib/Target/Mips/MipsCCState.cpp File Reference
MipsCCState.cpp File Reference
#include "MipsCCState.h"
#include "MipsSubtarget.h"
#include "llvm/IR/Module.h"
Functions
static bool isF128SoftLibCall (const char *CallSym)
This function returns true if CallSym is a long double emulation routine.
static bool originalTypeIsF128 (const Type *Ty, const char *Func)
This function returns true if Ty is fp128, {f128} or i128 which was originally a fp128.
static bool originalEVTTypeIsVectorFloat (EVT Ty)
Return true if the original type was vXfXX.
static bool originalTypeIsVectorFloat (const Type *Ty)
Return true if the original type was vXfXX / vXfXX.
Function Documentation
isF128SoftLibCall()
static bool isF128SoftLibCall (const char * CallSym) static
This function returns true if CallSym is a long double emulation routine.
Definition at line 16 of file MipsCCState.cpp.
References assert(), llvm::sys::path::begin(), and llvm::sys::path::end().
Referenced by originalTypeIsF128().
originalEVTTypeIsVectorFloat()
static bool originalEVTTypeIsVectorFloat (EVT Ty) static
Return true if the original type was vXfXX.
Definition at line 54 of file MipsCCState.cpp.
References llvm::EVT::getVectorElementType(), llvm::EVT::isFloatingPoint(), and llvm::EVT::isVector().
Referenced by llvm::MipsCCState::getSpecialCallingConvForCallee().
originalTypeIsF128()
static bool originalTypeIsF128 (const Type * Ty, const char * Func) static
This function returns true if Ty is fp128, {f128} or i128 which was originally a fp128.
Definition at line 40 of file MipsCCState.cpp.
References llvm::Type::getStructElementType(), llvm::Type::getStructNumElements(), isF128SoftLibCall(), llvm::Type::isFP128Ty(), llvm::Type::isIntegerTy(), and llvm::Type::isStructTy().
Referenced by llvm::MipsCCState::getSpecialCallingConvForCallee().
originalTypeIsVectorFloat()
static bool originalTypeIsVectorFloat (const Type * Ty) static
Return true if the original type was vXfXX / vXfXX.
Definition at line 62 of file MipsCCState.cpp.
References llvm::Type::isFPOrFPVectorTy(), and llvm::Type::isVectorTy().
Referenced by llvm::MipsCCState::getSpecialCallingConvForCallee().