LLVM: lib/Target/Mips/Mips16HardFloat.cpp File Reference
Mips16HardFloat.cpp File Reference
#include "MipsTargetMachine.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <string>
Macros
#define DEBUG_TYPE "mips16-hard-float"
Typedefs
using TypeID = Type::TypeID
Enumerations
enum FPReturnVariant {
FRet, DRet, CFRet, CDRet,
NoFPRet
}
enum FPParamVariant {
FSig, FFSig, FDSig, DSig,
DDSig, DFSig, NoSig
}
Functions
static void EmitInlineAsm (LLVMContext &C, BasicBlock *BB, StringRef AsmText)
static FPReturnVariant whichFPReturnVariant (Type *T)
static FPParamVariant whichFPParamVariantNeeded (Function &F)
static bool needsFPStubFromParams (Function &F)
static bool needsFPReturnHelper (Function &F)
static bool needsFPReturnHelper (FunctionType &FT)
static bool needsFPHelperFromSig (Function &F)
static std::string swapFPIntParams (FPParamVariant PV, Module *M, bool LE, bool ToFP)
static void assureFPCallStub (Function &F, Module *M, const MipsTargetMachine &TM)
static bool isIntrinsicInline (Function *F)
static bool fixupFPReturnAndCall (Function &F, Module *M, const MipsTargetMachine &TM)
static void createFPFnStub (Function *F, Module *M, FPParamVariant PV, const MipsTargetMachine &TM)
static void removeUseSoftFloat (Function &F)
Variables
const Type::TypeID FloatTyID = Type::FloatTyID
const Type::TypeID DoubleTyID = Type::DoubleTyID
static const char *const IntrinsicInline []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips16-hard-float"
Definition at line 24 of file Mips16HardFloat.cpp.
Typedef Documentation
TypeID
using TypeID = Type::TypeID
Definition at line 102 of file Mips16HardFloat.cpp.
Enumeration Type Documentation
FPParamVariant
enum FPParamVariant
Enumerator
FSig
FFSig
FDSig
DSig
DDSig
DFSig
NoSig
Definition at line 96 of file Mips16HardFloat.cpp.
FPReturnVariant
enum FPReturnVariant
Enumerator
FRet
DRet
CFRet
CDRet
NoFPRet
Definition at line 63 of file Mips16HardFloat.cpp.
Function Documentation
assureFPCallStub()
static void assureFPCallStub (Function & F, Module * M, const MipsTargetMachine & TM) static
Definition at line 256 of file Mips16HardFloat.cpp.
References llvm::Function::addFnAttr(), CDRet, CFRet, Context, llvm::BasicBlock::Create(), llvm::Function::Create(), DRet, EmitInlineAsm(), FRet, llvm::Module::getContext(), llvm::Module::getFunction(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::Function::getReturnType(), llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::isDeclaration(), llvm::MipsTargetMachine::isLittleEndian(), llvm::TargetMachine::isPositionIndependent(), llvm::AArch64CC::LE, Name, NoFPRet, llvm::GlobalObject::setSection(), swapFPIntParams(), whichFPParamVariantNeeded(), and whichFPReturnVariant().
Referenced by fixupFPReturnAndCall().
createFPFnStub()
static void createFPFnStub (Function * F, Module * M, FPParamVariant PV, const MipsTargetMachine & TM) static
Definition at line 446 of file Mips16HardFloat.cpp.
References llvm::Function::addFnAttr(), Context, llvm::BasicBlock::Create(), llvm::Function::Create(), EmitInlineAsm(), llvm::Function::getContext(), llvm::Module::getContext(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::GlobalValue::InternalLinkage, llvm::MipsTargetMachine::isLittleEndian(), llvm::TargetMachine::isPositionIndependent(), llvm::AArch64CC::LE, Name, llvm::GlobalObject::setSection(), and swapFPIntParams().
Referenced by removeUseSoftFloat().
EmitInlineAsm()
static void EmitInlineAsm (LLVMContext & C, BasicBlock * BB, StringRef AsmText) static
Definition at line 46 of file Mips16HardFloat.cpp.
References llvm::InlineAsm::AD_ATT, llvm::CallInst::Create(), llvm::InlineAsm::get(), llvm::FunctionType::get(), and llvm::Type::getVoidTy().
Referenced by assureFPCallStub(), createFPFnStub(), and llvm::AsmPrinter::emitDwarfAbbrevs().
fixupFPReturnAndCall()
static bool fixupFPReturnAndCall (Function & F, Module * M, const MipsTargetMachine & TM) static
Definition at line 377 of file Mips16HardFloat.cpp.
References llvm::AttributeList::addAttribute(), assureFPCallStub(), C, llvm::CallInst::Create(), llvm::AttributeList::FunctionIndex, llvm::Module::getContext(), llvm::Module::getOrInsertFunction(), llvm::Value::getType(), llvm::Type::getVoidTy(), I, isIntrinsicInline(), llvm::TargetMachine::isPositionIndependent(), Modified, Name, needsFPHelperFromSig(), needsFPReturnHelper(), NoFPRet, and whichFPReturnVariant().
Referenced by removeUseSoftFloat().
isIntrinsicInline()
static bool isIntrinsicInline (Function * F) static
Definition at line 370 of file Mips16HardFloat.cpp.
References llvm::sys::path::begin(), llvm::sys::path::end(), and llvm::Value::getName().
Referenced by fixupFPReturnAndCall().
needsFPHelperFromSig()
static bool needsFPHelperFromSig (Function & F) static
Definition at line 180 of file Mips16HardFloat.cpp.
References needsFPReturnHelper(), and needsFPStubFromParams().
Referenced by fixupFPReturnAndCall().
needsFPReturnHelper() [1/2]
static bool needsFPReturnHelper (Function & F) static
Definition at line 170 of file Mips16HardFloat.cpp.
References llvm::Function::getReturnType(), NoFPRet, and whichFPReturnVariant().
Referenced by fixupFPReturnAndCall(), and needsFPHelperFromSig().
needsFPReturnHelper() [2/2]
static bool needsFPReturnHelper (FunctionType & FT) static
Definition at line 175 of file Mips16HardFloat.cpp.
References llvm::FunctionType::getReturnType(), NoFPRet, and whichFPReturnVariant().
needsFPStubFromParams()
static bool needsFPStubFromParams (Function & F) static
Definition at line 156 of file Mips16HardFloat.cpp.
References llvm::Function::arg_size(), llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::Function::getFunctionType(), llvm::FunctionType::getParamType(), and llvm::Type::getTypeID().
Referenced by needsFPHelperFromSig().
removeUseSoftFloat()
static void removeUseSoftFloat (Function & F) static
Definition at line 484 of file Mips16HardFloat.cpp.
References llvm::AttrBuilder::addAttribute(), llvm::Function::addAttributes(), B, llvm::Module::begin(), createFPFnStub(), E, llvm::Module::end(), llvm::errs(), F(), fixupFPReturnAndCall(), llvm::AttributeList::FunctionIndex, llvm::Function::hasFnAttribute(), LLVM_DEBUG, Modified, NoSig, llvm::Function::removeAttributes(), llvm::SystemZISD::TM, and whichFPParamVariantNeeded().
swapFPIntParams()
static std::string swapFPIntParams (FPParamVariant PV, Module * M, bool LE, bool ToFP) static
Definition at line 186 of file Mips16HardFloat.cpp.
References DDSig, DFSig, DSig, FDSig, FFSig, FSig, MI, and NoSig.
Referenced by assureFPCallStub(), and createFPFnStub().
whichFPParamVariantNeeded()
static FPParamVariant whichFPParamVariantNeeded (Function & F) static
Definition at line 106 of file Mips16HardFloat.cpp.
References llvm::Function::arg_size(), DDSig, DFSig, DoubleTyID, DSig, FDSig, FFSig, FloatTyID, FSig, llvm::Function::getFunctionType(), llvm::FunctionType::getParamType(), llvm::Type::getTypeID(), llvm_unreachable, and NoSig.
Referenced by assureFPCallStub(), and removeUseSoftFloat().
whichFPReturnVariant()
static FPReturnVariant whichFPReturnVariant (Type * T) static
Definition at line 70 of file Mips16HardFloat.cpp.
References CDRet, CFRet, llvm::Type::DoubleTyID, DRet, llvm::Type::FloatTyID, FRet, llvm::StructType::getElementType(), llvm::StructType::getNumElements(), llvm::Type::getTypeID(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), NoFPRet, llvm::ARM_MB::ST, llvm::Type::StructTyID, and llvm::T.
Referenced by assureFPCallStub(), fixupFPReturnAndCall(), and needsFPReturnHelper().
Variable Documentation
DoubleTyID
const Type::TypeID DoubleTyID = Type::DoubleTyID
Definition at line 104 of file Mips16HardFloat.cpp.
Referenced by llvm::orc::OrcMCJITReplacement::runFunction(), and whichFPParamVariantNeeded().
FloatTyID
const Type::TypeID FloatTyID = Type::FloatTyID
Definition at line 103 of file Mips16HardFloat.cpp.
Referenced by llvm::orc::OrcMCJITReplacement::runFunction(), and whichFPParamVariantNeeded().
IntrinsicInline
const char* const IntrinsicInline[] static
Initial value:
= {
  "fabs", "fabsf",
  "llvm.ceil.f32", "llvm.ceil.f64",
  "llvm.copysign.f32", "llvm.copysign.f64",
  "llvm.cos.f32", "llvm.cos.f64",
  "llvm.exp.f32", "llvm.exp.f64",
  "llvm.exp2.f32", "llvm.exp2.f64",
  "llvm.fabs.f32", "llvm.fabs.f64",
  "llvm.floor.f32", "llvm.floor.f64",
  "llvm.fma.f32", "llvm.fma.f64",
  "llvm.log.f32", "llvm.log.f64",
  "llvm.log10.f32", "llvm.log10.f64",
  "llvm.nearbyint.f32", "llvm.nearbyint.f64",
  "llvm.pow.f32", "llvm.pow.f64",
  "llvm.powi.f32", "llvm.powi.f64",
  "llvm.rint.f32", "llvm.rint.f64",
  "llvm.round.f32", "llvm.round.f64",
  "llvm.sin.f32", "llvm.sin.f64",
  "llvm.sqrt.f32", "llvm.sqrt.f64",
  "llvm.trunc.f32", "llvm.trunc.f64",
}
Definition at line 348 of file Mips16HardFloat.cpp.