LLVM: lib/Target/Mips/MCTargetDesc/MipsAsmBackend.cpp File Reference
MipsAsmBackend.cpp File Reference
#include "MCTargetDesc/MipsAsmBackend.h"
#include "MCTargetDesc/MipsABIInfo.h"
#include "MCTargetDesc/MipsFixupKinds.h"
#include "MCTargetDesc/MipsMCExpr.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
Functions
static unsigned adjustFixupValue (const MCFixup &Fixup, uint64_t Value, MCContext &Ctx)
static bool needsMMLEByteOrder (unsigned Kind)
static unsigned calculateMMLEIndex (unsigned i)
Function Documentation
adjustFixupValue()
static unsigned adjustFixupValue (const MCFixup & Fixup, uint64_t Value, MCContext & Ctx) static
Definition at line 38 of file MipsAsmBackend.cpp.
References llvm::Mips::fixup_MICROMIPS_26_S1, llvm::Mips::fixup_MICROMIPS_GOT16, llvm::Mips::fixup_MICROMIPS_GOT_DISP, llvm::Mips::fixup_MICROMIPS_GOT_OFST, llvm::Mips::fixup_MICROMIPS_GOT_PAGE, llvm::Mips::fixup_MICROMIPS_GPOFF_HI, llvm::Mips::fixup_MICROMIPS_GPOFF_LO, llvm::Mips::fixup_MICROMIPS_HI16, llvm::Mips::fixup_MICROMIPS_HIGHER, llvm::Mips::fixup_MICROMIPS_HIGHEST, llvm::Mips::fixup_MICROMIPS_LO16, llvm::Mips::fixup_MICROMIPS_PC10_S1, llvm::Mips::fixup_MICROMIPS_PC16_S1, llvm::Mips::fixup_MICROMIPS_PC18_S3, llvm::Mips::fixup_MICROMIPS_PC19_S2, llvm::Mips::fixup_MICROMIPS_PC21_S1, llvm::Mips::fixup_MICROMIPS_PC26_S1, llvm::Mips::fixup_MICROMIPS_PC7_S1, llvm::Mips::fixup_MICROMIPS_SUB, llvm::Mips::fixup_Mips_26, llvm::Mips::fixup_Mips_CALL_HI16, llvm::Mips::fixup_Mips_CALL_LO16, llvm::Mips::fixup_Mips_GOT, llvm::Mips::fixup_Mips_GOT_DISP, llvm::Mips::fixup_Mips_GOT_HI16, llvm::Mips::fixup_Mips_GOT_LO16, llvm::Mips::fixup_Mips_GOT_OFST, llvm::Mips::fixup_Mips_GOT_PAGE, llvm::Mips::fixup_Mips_GPOFF_HI, llvm::Mips::fixup_Mips_GPOFF_LO, llvm::Mips::fixup_Mips_GPREL16, llvm::Mips::fixup_Mips_HI16, llvm::Mips::fixup_Mips_HIGHER, llvm::Mips::fixup_Mips_HIGHEST, llvm::Mips::fixup_Mips_LO16, llvm::Mips::fixup_Mips_PC16, llvm::Mips::fixup_MIPS_PC18_S3, llvm::Mips::fixup_MIPS_PC19_S2, llvm::Mips::fixup_MIPS_PC21_S2, llvm::Mips::fixup_MIPS_PC26_S2, llvm::Mips::fixup_MIPS_PCHI16, llvm::Mips::fixup_MIPS_PCLO16, llvm::Mips::fixup_Mips_SUB, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_DTPRel_4, llvm::FK_DTPRel_8, llvm::FK_GPRel_4, llvm::FK_TPRel_4, llvm::FK_TPRel_8, llvm::MCFixup::getKind(), llvm::MCFixup::getLoc(), llvm::isInt< 16 >(), llvm::MCContext::reportError(), and llvm::MCContext::reportFatalError().
Referenced by llvm::MipsAsmBackend::applyFixup().
calculateMMLEIndex()
static unsigned calculateMMLEIndex (unsigned i) static
Definition at line 234 of file MipsAsmBackend.cpp.
References assert().
Referenced by llvm::MipsAsmBackend::applyFixup().
needsMMLEByteOrder()
static bool needsMMLEByteOrder (unsigned Kind) static
Definition at line 227 of file MipsAsmBackend.cpp.
References llvm::Mips::fixup_MICROMIPS_26_S1, llvm::Mips::fixup_MICROMIPS_PC10_S1, and llvm::Mips::LastTargetFixupKind.
Referenced by llvm::MipsAsmBackend::applyFixup().