LLVM: lib/Target/Mips/MipsRegisterBankInfo.cpp File Reference
MipsRegisterBankInfo.cpp File Reference
This file implements the targeting of the RegisterBankInfo class for Mips.
#include "MipsRegisterBankInfo.h"
#include "MipsInstrInfo.h"
#include "MipsTargetMachine.h"
#include "llvm/CodeGen/GlobalISel/GISelChangeObserver.h"
#include "llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "MipsGenRegisterBank.inc"
Namespaces
llvm
This class represents lattice values for constants.
llvm::Mips
Macros
#define GET_TARGET_REGBANK_IMPL
Typedefs
using InstListTy = GISelWorkList< 4 >
Enumerations
enum llvm::Mips::PartialMappingIdx {
llvm::Mips::PMI_GPR, llvm::Mips::PMI_SPR, llvm::Mips::PMI_DPR, llvm::Mips::PMI_MSA,
llvm::Mips::PMI_Min = PMI_GPR
}
enum llvm::Mips::ValueMappingIdx {
llvm::Mips::InvalidIdx = 0, llvm::Mips::GPRIdx = 1, llvm::Mips::SPRIdx = 4, llvm::Mips::DPRIdx = 7,
llvm::Mips::MSAIdx = 10
}
Functions
static bool isFloatingPointOpcode (unsigned Opc)
static bool isFloatingPointOpcodeUse (unsigned Opc)
static bool isFloatingPointOpcodeDef (unsigned Opc)
static bool isAmbiguous (unsigned Opc)
static const MipsRegisterBankInfo::ValueMapping * getMSAMapping (const MachineFunction &MF)
static const MipsRegisterBankInfo::ValueMapping * getFprbMapping (unsigned Size)
static const MipsRegisterBankInfo::ValueMapping * getGprbOrCustomMapping (unsigned Size, unsigned &MappingID)
static void combineAwayG_UNMERGE_VALUES (LegalizationArtifactCombiner &ArtCombiner, MachineInstr &MI)
Variables
RegisterBankInfo::PartialMapping llvm::Mips::PartMappings []
RegisterBankInfo::ValueMapping llvm::Mips::ValueMappings []
static const unsigned CustomMappingID = 1
Detailed Description
This file implements the targeting of the RegisterBankInfo class for Mips.
Todo:
This should be generated by TableGen.
Definition in file MipsRegisterBankInfo.cpp.
Macro Definition Documentation
GET_TARGET_REGBANK_IMPL
#define GET_TARGET_REGBANK_IMPL
Definition at line 21 of file MipsRegisterBankInfo.cpp.
Typedef Documentation
InstListTy
using InstListTy = GISelWorkList<4>
Definition at line 612 of file MipsRegisterBankInfo.cpp.
Function Documentation
combineAwayG_UNMERGE_VALUES()
static void combineAwayG_UNMERGE_VALUES (LegalizationArtifactCombiner & ArtCombiner, MachineInstr & MI) static
Definition at line 654 of file MipsRegisterBankInfo.cpp.
References llvm::LegalizationArtifactCombiner::tryCombineMerges().
Referenced by llvm::MipsRegisterBankInfo::applyMappingImpl().
getFprbMapping()
static const MipsRegisterBankInfo::ValueMapping* getFprbMapping (unsigned Size) static
Definition at line 378 of file MipsRegisterBankInfo.cpp.
References llvm::Mips::DPRIdx, llvm::Mips::SPRIdx, and llvm::Mips::ValueMappings.
Referenced by llvm::MipsRegisterBankInfo::getInstrMapping().
getGprbOrCustomMapping()
static const MipsRegisterBankInfo::ValueMapping* getGprbOrCustomMapping (unsigned Size, unsigned & MappingID) static
Definition at line 388 of file MipsRegisterBankInfo.cpp.
References CustomMappingID, llvm::Mips::DPRIdx, llvm::Mips::GPRIdx, and llvm::Mips::ValueMappings.
Referenced by llvm::MipsRegisterBankInfo::getInstrMapping().
getMSAMapping()
static const MipsRegisterBankInfo::ValueMapping* getMSAMapping (const MachineFunction & MF) static
Definition at line 372 of file MipsRegisterBankInfo.cpp.
References assert(), llvm::MachineFunction::getSubtarget(), llvm::Mips::MSAIdx, and llvm::Mips::ValueMappings.
Referenced by llvm::MipsRegisterBankInfo::getInstrMapping().
isAmbiguous()
static bool isAmbiguous (unsigned Opc) static
Definition at line 159 of file MipsRegisterBankInfo.cpp.
References assert(), DefMI, llvm::SmallVectorBase::empty(), llvm::MachineInstr::getMF(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::TargetSubtargetInfo::getRegBankInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), llvm::Integer, isFloatingPointOpcodeDef(), isFloatingPointOpcodeUse(), llvm::Register::isPhysicalRegister(), llvm::LLT::isPointer(), llvm_unreachable, MI, MRI, llvm::SmallVectorImpl< T >::pop_back_val(), Reg, llvm::MipsISD::Ret, TRI, llvm::MachineRegisterInfo::use_instr_begin(), llvm::MachineRegisterInfo::use_instructions(), and UseMI.
isFloatingPointOpcode()
static bool isFloatingPointOpcode (unsigned Opc) static
Definition at line 109 of file MipsRegisterBankInfo.cpp.
Referenced by isFloatingPointOpcodeDef(), and isFloatingPointOpcodeUse().
isFloatingPointOpcodeDef()
static bool isFloatingPointOpcodeDef (unsigned Opc) static
Definition at line 146 of file MipsRegisterBankInfo.cpp.
References llvm::MipsISD::BuildPairF64, and isFloatingPointOpcode().
Referenced by isAmbiguous().
isFloatingPointOpcodeUse()
static bool isFloatingPointOpcodeUse (unsigned Opc) static
Definition at line 130 of file MipsRegisterBankInfo.cpp.
References llvm::MipsISD::ExtractElementF64, and isFloatingPointOpcode().
Referenced by isAmbiguous().
Variable Documentation
CustomMappingID
const unsigned CustomMappingID = 1 static
Definition at line 383 of file MipsRegisterBankInfo.cpp.
Referenced by getGprbOrCustomMapping(), and llvm::MipsRegisterBankInfo::getInstrMapping().