LLVM: lib/Target/Mips/MipsFastISel.cpp File Reference
MipsFastISel.cpp File Reference
This file defines the MIPS-specific support for the FastISel class.
#include "MCTargetDesc/MipsABIInfo.h"
#include "MCTargetDesc/MipsBaseInfo.h"
#include "MipsCCState.h"
#include "MipsISelLowering.h"
#include "MipsInstrInfo.h"
#include "MipsMachineFunction.h"
#include "MipsSubtarget.h"
#include "MipsTargetMachine.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/FastISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <array>
#include <cassert>
#include <cstdint>
#include "MipsGenFastISel.inc"
#include "MipsGenCallingConv.inc"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "mips-fastisel"
Functions
static bool CC_Mips (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State) LLVM_ATTRIBUTE_UNUSED
static bool CC_MipsO32_FP32 (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State)
static bool CC_MipsO32_FP64 (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State)
Variables
cl::opt< bool > EmitJalrReloc
Detailed Description
This file defines the MIPS-specific support for the FastISel class.
Some of the target-specific code is generated by tablegen in the file MipsGenFastISel.inc, which is #included here.
Definition in file MipsFastISel.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-fastisel"
Definition at line 74 of file MipsFastISel.cpp.
Function Documentation
CC_Mips()
static bool CC_Mips (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State) static
CC_MipsO32_FP32()
static bool CC_MipsO32_FP32 (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State) static
Definition at line 278 of file MipsFastISel.cpp.
References llvm_unreachable.
CC_MipsO32_FP64()
static bool CC_MipsO32_FP64 (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State) static
Definition at line 284 of file MipsFastISel.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMemOperand(), llvm::Address, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::ISD::AND, assert(), llvm::APFloat::bitcastToAPInt(), llvm::BuildMI(), llvm::MipsISD::BuildPairF64, C, CC_MipsO32(), llvm::dbgs(), llvm::RegState::Define, llvm::dyn_cast(), llvm::numbers::e, emitCmp(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MVT::f32, llvm::MVT::f64, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_UNE, llvm::gep_type_begin(), llvm::BranchInst::getCondition(), llvm::StructLayout::getElementOffset(), llvm::MachinePointerInfo::getFixedStack(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::MachineFrameInfo::getObjectSize(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::CmpInst::getPredicate(), llvm::ConstantInt::getSExtValue(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::generic_gep_type_iterator< ItTy >::getStructTypeOrNull(), llvm::BranchInst::getSuccessor(), llvm::AllocaInst::getType(), llvm::Value::getType(), llvm::ConstantFP::getValueAPF(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), llvm::GlobalValue::hasInternalLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasOneUse(), llvm::MipsISD::Hi, I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, isAtomic(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::isInt< 16 >(), llvm::MVT::isInteger(), llvm::EVT::isSimple(), llvm::GlobalValue::isThreadLocal(), llvm::isUInt< 16 >(), llvm::CmpInst::isUnsigned(), llvm::MVT::isVector(), llvm::Type::isVectorTy(), llvm::Left, LLVM_DEBUG, llvm_unreachable, llvm::MipsISD::Lo, llvm::MipsII::MO_ABS_LO, llvm::MipsII::MO_GOT, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::User::op_begin(), llvm::User::op_end(), llvm::ISD::OR, llvm::MVT::Other, P, llvm::Right, SI, llvm::MVT::SimpleTy, std::swap(), TII, and llvm::ISD::XOR.
Variable Documentation
EmitJalrReloc
cl::opt<bool> EmitJalrReloc