LLVM: lib/Target/Mips/MCTargetDesc/MipsMCCodeEmitter.cpp File Reference
MipsMCCodeEmitter.cpp File Reference
#include "MipsMCCodeEmitter.h"
#include "MCTargetDesc/MipsFixupKinds.h"
#include "MCTargetDesc/MipsMCExpr.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include "MipsGenInstrInfo.inc"
#include "MipsGenMCCodeEmitter.inc"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "mccodeemitter"
#define GET_INSTRMAP_INFO
Functions
MCCodeEmitter * llvm::createMipsMCCodeEmitterEB (const MCInstrInfo &MCII, const MCRegisterInfo &MRI, MCContext &Ctx)
MCCodeEmitter * llvm::createMipsMCCodeEmitterEL (const MCInstrInfo &MCII, const MCRegisterInfo &MRI, MCContext &Ctx)
static void LowerLargeShift (MCInst &Inst)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mccodeemitter"
Definition at line 36 of file MipsMCCodeEmitter.cpp.
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO
Definition at line 38 of file MipsMCCodeEmitter.cpp.
Function Documentation
LowerLargeShift()
static void LowerLargeShift (MCInst & Inst) static
Definition at line 60 of file MipsMCCodeEmitter.cpp.
References assert(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCContext::getRegisterInfo(), llvm::MCOperand::isImm(), llvm_unreachable, llvm::MCOperand::setImm(), llvm::MCInst::setOpcode(), and llvm::MCOperand::setReg().
Referenced by llvm::MipsMCCodeEmitter::encodeInstruction().