LLVM: lib/Target/Mips/TargetInfo/MipsTargetInfo.cpp File Reference
MipsTargetInfo.cpp File Reference
#include "TargetInfo/MipsTargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsTargetInfo ()
Function Documentation
LLVMInitializeMipsTargetInfo()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsTargetInfo ()
Definition at line 30 of file MipsTargetInfo.cpp.
References B, llvm::getTheMips64elTarget(), llvm::getTheMips64Target(), llvm::getTheMipselTarget(), llvm::getTheMipsTarget(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, X, and Y.