LLVM: lib/Target/Mips/MipsDelaySlotFiller.cpp File Reference
MipsDelaySlotFiller.cpp File Reference
#include "MCTargetDesc/MipsMCNaCl.h"
#include "Mips.h"
#include "MipsInstrInfo.h"
#include "MipsRegisterInfo.h"
#include "MipsSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <memory>
#include <utility>
Macros
#define DEBUG_TYPE "mips-delay-slot-filler"
Enumerations
enum CompactBranchPolicy { CB_Never, CB_Optimal, CB_Always }
Functions
STATISTIC (FilledSlots, "Number of delay slots filled")
STATISTIC (UsefulSlots, "Number of delay slots filled with instructions that" " are not NOP.")
static bool hasUnoccupiedSlot (const MachineInstr *MI)
INITIALIZE_PASS (MipsDelaySlotFiller, DEBUG_TYPE, "Fill delay slot for MIPS", false, false) static void insertDelayFiller(Iter Filler
This function inserts clones of Filler into predecessor blocks.
for (BB2BrMap::const_iterator I=BrMap.begin();I !=BrMap.end();++I)
static void addLiveInRegs (Iter Filler, MachineBasicBlock &MBB)
This function adds registers Filler defines to MBB's live-in register list.
static int getEquivalentCallShort (int Opcode)
Variables
static cl::opt< bool > DisableDelaySlotFiller ("disable-mips-delay-filler", cl::init(false), cl::desc("Fill all delay slots with NOPs."), cl::Hidden)
static cl::opt< bool > DisableForwardSearch ("disable-mips-df-forward-search", cl::init(true), cl::desc("Disallow MIPS delay filler to search forward."), cl::Hidden)
static cl::opt< bool > DisableSuccBBSearch ("disable-mips-df-succbb-search", cl::init(true), cl::desc("Disallow MIPS delay filler to search successor basic blocks."), cl::Hidden)
static cl::opt< bool > DisableBackwardSearch ("disable-mips-df-backward-search", cl::init(false), cl::desc("Disallow MIPS delay filler to search backward."), cl::Hidden)
static cl::opt< CompactBranchPolicy > MipsCompactBranchPolicy ("mips-compact-branches", cl::Optional, cl::init(CB_Optimal), cl::desc("MIPS Specific: Compact branch policy."), cl::values(clEnumValN(CB_Never, "never", "Do not use compact branches if possible."), clEnumValN(CB_Optimal, "optimal", "Use compact branches where appropiate (default)."), clEnumValN(CB_Always, "always", "Always use compact branches if possible.")))
const BB2BrMap & BrMap
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-delay-slot-filler"
Definition at line 53 of file MipsDelaySlotFiller.cpp.
Referenced by getEquivalentCallShort(), and hasUnoccupiedSlot().
Enumeration Type Documentation
CompactBranchPolicy
enum CompactBranchPolicy
Enumerator
CB_Never
The policy 'never' may in some circumstances or for some ISAs not be absolutely adhered to.
CB_Optimal
Optimal is the default and will produce compact branches when delay slots cannot be filled.
CB_Always
'always' may in some circumstances may not be absolutely adhered to there may not be a corresponding compact form of a branch.
Definition at line 83 of file MipsDelaySlotFiller.cpp.
Function Documentation
addLiveInRegs()
static void addLiveInRegs (Iter Filler, MachineBasicBlock & MBB) static
This function adds registers Filler defines to MBB's live-in register list.
Definition at line 325 of file MipsDelaySlotFiller.cpp.
References llvm::MachineBasicBlock::addLiveIn(), assert(), llvm::MachineInstr::definesRegister(), E, llvm::BitVector::flip(), llvm::TargetRegisterInfo::getAllocatableSet(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::cl::init(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isCall(), llvm::MachineOperand::isDef(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineOperand::isReg(), llvm::MCRegAliasIterator::isValid(), MI, RA, llvm::BitVector::reset(), llvm::BitVector::set(), llvm::BitVector::set_bits(), SI, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::BitVector::test(), and TRI.
for()
for (BB2BrMap::const_iterator I = BrMap.begin(); I != BrMap.end(); ++I)
Definition at line 314 of file MipsDelaySlotFiller.cpp.
References llvm::MIBundleBuilder::append(), llvm::MachineFunction::CloneMachineInstr(), and I.
getEquivalentCallShort()
static int getEquivalentCallShort (int Opcode) static
Definition at line 578 of file MipsDelaySlotFiller.cpp.
References llvm::MachineBasicBlock::begin(), llvm::BuildMI(), CB_Always, CB_Never, llvm::dbgs(), DEBUG_TYPE, DisableDelaySlotFiller, llvm::MachineBasicBlock::end(), llvm::MipsInstrInfo::getEquivalentCompactForm(), llvm::MipsSubtarget::getInstrInfo(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MipsSubtarget::hasMips32r6(), hasUnoccupiedSlot(), I, llvm::MipsSubtarget::inMicroMipsMode(), LLVM_DEBUG, llvm_unreachable, MipsCompactBranchPolicy, llvm::CodeGenOpt::None, TII, and llvm::SystemZISD::TM.
hasUnoccupiedSlot()
static bool hasUnoccupiedSlot (const MachineInstr * MI) static
Definition at line 303 of file MipsDelaySlotFiller.cpp.
References DEBUG_TYPE, llvm::MachineInstr::hasDelaySlot(), INITIALIZE_PASS(), and llvm::MachineInstr::isBundledWithSucc().
Referenced by getEquivalentCallShort().
INITIALIZE_PASS()
INITIALIZE_PASS (MipsDelaySlotFiller , DEBUG_TYPE , "Fill delay slot for MIPS" , false , false)
This function inserts clones of Filler into predecessor blocks.
Referenced by hasUnoccupiedSlot().
STATISTIC() [1/2]
STATISTIC (FilledSlots , "Number of delay slots filled")
STATISTIC() [2/2]
STATISTIC (UsefulSlots , "Number of delay slots filled with instructions that" " are not NOP.")
Variable Documentation
BrMap
const BB2BrMap& BrMap
Initial value:
{
  MachineFunction *MF = Filler->getParent()->getParent()
Definition at line 311 of file MipsDelaySlotFiller.cpp.
DisableBackwardSearch
cl::opt<bool> DisableBackwardSearch("disable-mips-df-backward-search", cl::init(false), cl::desc("Disallow MIPS delay filler to search backward."), cl::Hidden) static
DisableDelaySlotFiller
cl::opt<bool> DisableDelaySlotFiller("disable-mips-delay-filler", cl::init(false), cl::desc("Fill all delay slots with NOPs."), cl::Hidden) static
Referenced by getEquivalentCallShort().
DisableForwardSearch
cl::opt<bool> DisableForwardSearch("disable-mips-df-forward-search", cl::init(true), cl::desc("Disallow MIPS delay filler to search forward."), cl::Hidden) static
DisableSuccBBSearch
cl::opt<bool> DisableSuccBBSearch("disable-mips-df-succbb-search", cl::init(true), cl::desc("Disallow MIPS delay filler to search successor basic blocks."), cl::Hidden) static
MipsCompactBranchPolicy
cl::opt<CompactBranchPolicy> MipsCompactBranchPolicy("mips-compact-branches", cl::Optional, cl::init(CB_Optimal), cl::desc("MIPS Specific: Compact branch policy."), cl::values(clEnumValN(CB_Never, "never", "Do not use compact branches if possible."), clEnumValN(CB_Optimal, "optimal", "Use compact branches where appropiate (default)."), clEnumValN(CB_Always, "always", "Always use compact branches if possible."))) static
Referenced by getEquivalentCallShort().