LLVM: lib/Target/Mips/MipsCallLowering.cpp File Reference
MipsCallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "MipsCallLowering.h"
#include "MipsCCState.h"
#include "MipsMachineFunction.h"
#include "MipsTargetMachine.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
Functions
static bool isSupportedArgumentType (Type *T)
static bool isSupportedReturnType (Type *T)
static CCValAssign::LocInfo determineLocInfo (const MVT RegisterVT, const EVT VT, const ISD::ArgFlagsTy &Flags)
template<typename T >
static void setLocInfo (SmallVectorImpl< CCValAssign > &ArgLocs, const SmallVectorImpl< T > &Arguments)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file MipsCallLowering.cpp.
Function Documentation
determineLocInfo()
static CCValAssign::LocInfo determineLocInfo (const MVT RegisterVT, const EVT VT, const ISD::ArgFlagsTy & Flags) static
Definition at line 383 of file MipsCallLowering.cpp.
References llvm::JumpTable::Full, llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::ISD::ArgFlagsTy::isSExt(), and llvm::ISD::ArgFlagsTy::isZExt().
Referenced by setLocInfo().
isSupportedArgumentType()
static bool isSupportedArgumentType (Type * T) static
Definition at line 361 of file MipsCallLowering.cpp.
References llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by llvm::MipsCallLowering::lowerCall(), and llvm::MipsCallLowering::lowerFormalArguments().
isSupportedReturnType()
static bool isSupportedReturnType (Type * T) static
Definition at line 371 of file MipsCallLowering.cpp.
References llvm::Type::isAggregateType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by llvm::MipsCallLowering::lowerCall(), and llvm::MipsCallLowering::lowerReturn().
setLocInfo()
template<typename T > static void setLocInfo (SmallVectorImpl< CCValAssign > & ArgLocs, const SmallVectorImpl< T > & Arguments) static
Definition at line 397 of file MipsCallLowering.cpp.
References determineLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::CCValAssign::getMem(), llvm::CCValAssign::getReg(), llvm::CCValAssign::getValNo(), llvm::CCValAssign::getValVT(), llvm::CCValAssign::isMemLoc(), and llvm::SmallVectorBase::size().
Referenced by llvm::MipsCallLowering::lowerFormalArguments(), and llvm::MipsCallLowering::lowerReturn().