LLVM: lib/Target/Mips/AsmParser/MipsAsmParser.cpp File Reference
MipsAsmParser.cpp File Reference
#include "MCTargetDesc/MipsABIFlagsSection.h"
#include "MCTargetDesc/MipsABIInfo.h"
#include "MCTargetDesc/MipsBaseInfo.h"
#include "MCTargetDesc/MipsMCExpr.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "MipsTargetStreamer.h"
#include "TargetInfo/MipsTargetInfo.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/MC/MCParser/MCAsmParserUtils.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>
#include "MipsGenAsmMatcher.inc"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "mips-asm-parser"
#define GET_ASSEMBLER_HEADER
#define GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
#define GET_MNEMONIC_SPELL_CHECKER
Functions
static const MCInstrDesc & getInstDesc (unsigned Opcode)
static bool hasShortDelaySlot (MCInst &Inst)
static const MCSymbol * getSingleMCSymbol (const MCExpr *Expr)
static unsigned countMCSymbolRefExpr (const MCExpr *Expr)
static bool isEvaluated (const MCExpr *Expr)
static bool needsExpandMemInst (MCInst &Inst)
template<unsigned N>
static bool isShiftedUIntAtAnyPosition (uint64_t x)
Can the value be represented by a unsigned N-bit value and a shift left?
static unsigned nextReg (unsigned Reg)
static uint64_t convertIntToDoubleImm (uint64_t ImmOp64)
static uint32_t covertDoubleImmToSingleImm (uint64_t ImmOp64)
static unsigned getRegisterForMxtrDSP (MCInst &Inst, bool IsMFDSP)
static unsigned getRegisterForMxtrFP (MCInst &Inst, bool IsMFTC1)
static unsigned getRegisterForMxtrC0 (MCInst &Inst, bool IsMFTC0)
static SMLoc RefineErrorLoc (const SMLoc Loc, const OperandVector &Operands, uint64_t ErrorInfo)
static std::string MipsMnemonicSpellCheck (StringRef S, const FeatureBitset &FBS, unsigned VariantID=0)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsAsmParser ()
Variables
cl::opt< bool > EmitJalrReloc
const MCInstrDesc llvm::MipsInsts []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-asm-parser"
Definition at line 62 of file MipsAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 167 of file MipsAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 8656 of file MipsAsmParser.cpp.
GET_MNEMONIC_SPELL_CHECKER
#define GET_MNEMONIC_SPELL_CHECKER
Definition at line 8657 of file MipsAsmParser.cpp.
GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_OPERAND_DIAGNOSTIC_TYPES
Definition at line 506 of file MipsAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 8655 of file MipsAsmParser.cpp.
Function Documentation
convertIntToDoubleImm()
static uint64_t convertIntToDoubleImm (uint64_t ImmOp64) static
Definition at line 3312 of file MipsAsmParser.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::APInt::getZExtValue(), llvm::Hi_32(), and llvm::APFloatBase::IEEEdouble().
Referenced by covertDoubleImmToSingleImm().
countMCSymbolRefExpr()
static unsigned countMCSymbolRefExpr (const MCExpr * Expr) static
Definition at line 1788 of file MipsAsmParser.cpp.
Referenced by needsExpandMemInst().
covertDoubleImmToSingleImm()
static uint32_t covertDoubleImmToSingleImm (uint64_t ImmOp64) static
Definition at line 3322 of file MipsAsmParser.cpp.
References llvm::ISD::ADD, llvm::MCInst::addOperand(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::ISD::AND, llvm::MipsABIInfo::ArePtrs64bit(), assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::BitsToDouble(), llvm::MCInst::clear(), Context, convertIntToDoubleImm(), llvm::MipsMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCContext::createTempSymbol(), llvm::MipsTargetStreamer::emitDSLL(), llvm::MipsTargetStreamer::emitEmptyDelaySlot(), llvm::MipsTargetStreamer::emitII(), llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitLabel(), llvm::MipsTargetStreamer::emitNop(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRI(), llvm::MipsTargetStreamer::emitRR(), llvm::MipsTargetStreamer::emitRRI(), llvm::MipsTargetStreamer::emitRRR(), llvm::MipsTargetStreamer::emitRRRX(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), llvm::Error, llvm::FloatToBits(), llvm::MCValue::getConstant(), llvm::MCStreamer::getContext(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), getInstDesc(), llvm::MCInst::getLoc(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCTargetStreamer::getStreamer(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCInstrDesc::hasDelaySlot(), llvm::Hi_32(), llvm::MCOperand::isImm(), llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::MipsABIInfo::IsN64(), llvm::MCOperand::isReg(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::ARM_MB::LD, llvm_unreachable, llvm::Lo_32(), llvm::MipsISD::LWL, llvm::MipsISD::LWR, llvm::MipsMCExpr::MEK_HI, llvm::MipsMCExpr::MEK_HIGHER, llvm::MipsMCExpr::MEK_HIGHEST, llvm::MipsMCExpr::MEK_LO, llvm::MipsISD::MFHI, llvm::MipsISD::MFLO, llvm::MipsISD::MULT, nextReg(), llvm::offsetToAlignment(), llvm::MCInstrDesc::OpInfo, llvm::ISD::OR, RA, Reg, llvm::MCOperandInfo::RegClass, llvm::AVRISD::ROL, llvm::AArch64_AM::ROR, llvm::ISD::ROTR, llvm::ISD::SDIV, llvm::MCInst::setOpcode(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_PROGBITS, Signed, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, std::swap(), llvm::MipsISD::SWL, llvm::MipsISD::SWR, llvm::ISD::UDIV, llvm::MCSymbolRefExpr::VK_None, llvm::Warning, and llvm::ISD::XOR.
getInstDesc()
static const MCInstrDesc& getInstDesc (unsigned Opcode) static
Definition at line 1738 of file MipsAsmParser.cpp.
References llvm::MipsInsts.
Referenced by covertDoubleImmToSingleImm(), getRegisterForMxtrC0(), and needsExpandMemInst().
getRegisterForMxtrC0()
static unsigned getRegisterForMxtrC0 (MCInst & Inst, bool IsMFTC0) static
Definition at line 5424 of file MipsAsmParser.cpp.
References assert(), llvm::MipsTargetStreamer::emitRR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MCOperand::getImm(), getInstDesc(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterForMxtrDSP(), getRegisterForMxtrFP(), llvm::MipsII::HasFCCRegOperand, llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), LLVM_FALLTHROUGH, llvm_unreachable, RA, Size, T1, and llvm::X86II::T8.
getRegisterForMxtrDSP()
static unsigned getRegisterForMxtrDSP (MCInst & Inst, bool IsMFDSP) static
Definition at line 5331 of file MipsAsmParser.cpp.
References llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm_unreachable, and T1.
Referenced by getRegisterForMxtrC0().
getRegisterForMxtrFP()
static unsigned getRegisterForMxtrFP (MCInst & Inst, bool IsMFTC1) static
Definition at line 5385 of file MipsAsmParser.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm_unreachable, RA, T1, and llvm::X86II::T8.
Referenced by getRegisterForMxtrC0().
getSingleMCSymbol()
static const MCSymbol* getSingleMCSymbol (const MCExpr * Expr) static
Definition at line 1764 of file MipsAsmParser.cpp.
Referenced by needsExpandMemInst().
hasShortDelaySlot()
static bool hasShortDelaySlot (MCInst & Inst) static
Definition at line 1742 of file MipsAsmParser.cpp.
References llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and llvm::MCOperand::isReg().
Referenced by needsExpandMemInst(), and llvm::MipsTargetStreamer::setPic().
isEvaluated()
static bool isEvaluated (const MCExpr * Expr) static
Definition at line 1802 of file MipsAsmParser.cpp.
References llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCExpr::Unary, and llvm::MCSymbolRefExpr::VK_None.
Referenced by needsExpandMemInst().
isShiftedUIntAtAnyPosition()
template<unsigned N> static bool isShiftedUIntAtAnyPosition (uint64_t x) static
Can the value be represented by a unsigned N-bit value and a shift left?
Definition at line 2654 of file MipsAsmParser.cpp.
References llvm::MipsABIInfo::ArePtrs64bit(), assert(), llvm::tgtok::Bits, llvm::MipsMCExpr::create(), llvm::MCConstantExpr::create(), llvm::MCOperand::createExpr(), llvm::MipsTargetStreamer::emitDSLL(), llvm::MipsTargetStreamer::emitRI(), llvm::MipsTargetStreamer::emitRRI(), llvm::MipsTargetStreamer::emitRRR(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), llvm::Error, llvm::MCExpr::evaluateAsRelocatable(), llvm::findFirstSet(), llvm::findLastSet(), llvm::MCValue::getConstant(), llvm::MCOperand::getExpr(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MipsABIInfo::GetNullPtr(), llvm::MCInst::getOperand(), llvm::MipsABIInfo::GetPtrAdduOp(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MipsABIInfo::GetZeroReg(), llvm::MCSymbol::isELF(), llvm::MCOperand::isImm(), llvm::MCSymbol::isInSection(), llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::MipsABIInfo::IsN32(), llvm::MipsABIInfo::IsN64(), llvm::MCSymbol::isTemporary(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::ARM_MB::LD, llvm::MipsMCExpr::MEK_CALL_HI16, llvm::MipsMCExpr::MEK_CALL_LO16, llvm::MipsMCExpr::MEK_GOT, llvm::MipsMCExpr::MEK_GOT_CALL, llvm::MipsMCExpr::MEK_GOT_DISP, llvm::MipsMCExpr::MEK_GOT_HI16, llvm::MipsMCExpr::MEK_GOT_LO16, llvm::MipsMCExpr::MEK_HI, llvm::MipsMCExpr::MEK_HIGHER, llvm::MipsMCExpr::MEK_HIGHEST, llvm::MipsMCExpr::MEK_LO, llvm::ELF::STB_LOCAL, and llvm::Warning.
LLVMInitializeMipsAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsAsmParser ()
Definition at line 8648 of file MipsAsmParser.cpp.
References B, llvm::getTheMips64elTarget(), llvm::getTheMips64Target(), llvm::getTheMipselTarget(), llvm::getTheMipsTarget(), X, and Y.
MipsMnemonicSpellCheck()
static std::string MipsMnemonicSpellCheck (StringRef S, const FeatureBitset & FBS, unsigned VariantID = 0) static
Referenced by RefineErrorLoc().
needsExpandMemInst()
static bool needsExpandMemInst (MCInst & Inst) static
Definition at line 1822 of file MipsAsmParser.cpp.
References llvm::MCInst::addOperand(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::SmallVectorTemplateCommon< T >::back(), contains(), countMCSymbolRefExpr(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createReg(), llvm::MipsTargetStreamer::emitDirectiveSetNoReorder(), llvm::MipsTargetStreamer::emitDirectiveSetReorder(), llvm::MipsTargetStreamer::emitEmptyDelaySlot(), llvm::MipsTargetStreamer::emitGPRestore(), llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitRelocDirective(), llvm::MipsTargetStreamer::emitRRI(), llvm::Error, llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), getInstDesc(), llvm::MCExpr::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCInst::getNumOperands(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegClass(), getSingleMCSymbol(), llvm::MCTargetStreamer::getStreamer(), llvm::MCInstrDesc::hasDelaySlot(), hasShortDelaySlot(), llvm::MCInstrDesc::isBranch(), llvm::MCInstrDesc::isCall(), isEvaluated(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::isInt< 16 >(), llvm::isInt< 8 >(), llvm::isIntN(), llvm::MCOperand::isReg(), llvm::isUInt< 16 >(), LLVM_FALLTHROUGH, llvm::MCInstrDesc::mayLoad(), llvm::MCInstrDesc::mayStore(), llvm::offsetToAlignment(), llvm::MipsII::OPERAND_MEM_SIMM9, llvm::MCOI::OPERAND_MEMORY, llvm::MCOI::OPERAND_UNKNOWN, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, RA, llvm::AVRISD::ROL, llvm::AArch64_AM::ROR, llvm::ISD::SDIV, llvm::MCOperand::setImm(), llvm::MCInst::setLoc(), llvm::MCInst::setOpcode(), llvm::MipsTargetStreamer::setUsesMicroMips(), llvm::MCExpr::SymbolRef, llvm::ISD::UDIV, llvm::MipsTargetStreamer::updateABIInfo(), llvm::MCSymbolRefExpr::VK_None, and llvm::Warning.
nextReg()
static unsigned nextReg (unsigned Reg) static
Definition at line 3194 of file MipsAsmParser.cpp.
References contains(), llvm::MipsMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MipsTargetStreamer::emitRRI(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), llvm::ARM_MB::LD, llvm_unreachable, llvm::MipsMCExpr::MEK_GOT, llvm::MipsMCExpr::MEK_HI, llvm::MipsMCExpr::MEK_HIGHER, llvm::MipsMCExpr::MEK_HIGHEST, RA, T1, llvm::X86II::T8, and llvm::MCSymbolRefExpr::VK_None.
Referenced by covertDoubleImmToSingleImm(), and RefineErrorLoc().
RefineErrorLoc()
static SMLoc RefineErrorLoc (const SMLoc Loc, const OperandVector & Operands, uint64_t ErrorInfo) static
Definition at line 5722 of file MipsAsmParser.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCInst::addOperand(), llvm::AsmToken::Amp, llvm::MCBinaryExpr::And, assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::AsmToken::Caret, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), llvm::SmallVectorImpl< T >::clear(), llvm::AsmToken::Comma, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::create(), llvm::MCOperand::createReg(), llvm::dbgs(), llvm::StringSwitch< T, R >::Default(), llvm::MCBinaryExpr::Div, llvm::SourceMgr::DK_Warning, llvm::AsmToken::Dollar, llvm::StringRef::drop_front(), llvm::dyn_cast(), E, llvm::MCAsmParser::eatToEndOfStatement(), llvm::StringRef::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::AsmToken::EndOfStatement, llvm::AsmToken::Equal, llvm::Error, llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::StringRef::front(), llvm::SmallVectorTemplateCommon< T >::front(), llvm::StringRef::getAsInteger(), llvm::SMLoc::getFromPointer(), llvm::AsmToken::getIdentifier(), llvm::AsmToken::getIntVal(), llvm::MCExpr::getKind(), llvm::AsmToken::getKind(), llvm::MCAsmParser::getLexer(), llvm::AsmToken::getLoc(), llvm::MCAsmLexer::getLoc(), llvm::AsmToken::getLocRange(), llvm::MCSymbol::getName(), llvm::MCInst::getOpcode(), llvm::SMLoc::getPointer(), getReg(), llvm::AsmToken::getString(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCAsmParser::getTok(), llvm::MCConstantExpr::getValue(), llvm::MCSymbol::getVariableValue(), llvm::AsmToken::GreaterGreater, llvm::AsmToken::Identifier, Info, llvm::AsmToken::Integer, llvm::tgtok::IntVal, llvm::AsmToken::is(), llvm::MCAsmLexer::is(), llvm::AsmToken::isNot(), llvm::MCAsmLexer::isNot(), llvm::MCSymbol::isUnset(), llvm::MCSymbol::isVariable(), llvm::AsmToken::LBrac, llvm::AsmToken::LessLess, llvm::MCAsmParser::Lex(), LLVM_DEBUG, llvm_unreachable, llvm::AsmToken::LParen, llvm::MCBinaryExpr::LShr, llvm::MatchOperand_NoMatch, llvm::MatchOperand_ParseFail, llvm::MatchOperand_Success, llvm::AsmToken::Minus, MipsMnemonicSpellCheck(), llvm::MCBinaryExpr::Mod, llvm::MCBinaryExpr::Mul, Name, nextReg(), op, Operands, llvm::MCBinaryExpr::Or, llvm::MCParserUtils::parseAssignmentExpression(), llvm::MCAsmParser::parseExpression(), llvm::MCAsmParser::parseIdentifier(), llvm::MCAsmLexer::peekTok(), llvm::AsmToken::Percent, llvm::AsmToken::Pipe, llvm::AsmToken::Plus, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RA, llvm::AsmToken::RBrac, llvm::Ref, Reg, llvm::AsmToken::RParen, llvm::MipsABIFlagsSection::S32, llvm::MipsABIFlagsSection::S64, llvm::ARMBuildAttrs::Section, llvm::MCSubtargetInfo::setFeatureBits(), llvm::MCSymbol::setVariableValue(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_MIPS_GPREL, llvm::ELF::SHF_WRITE, llvm::MCBinaryExpr::Shl, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_PROGBITS, llvm::SmallVectorBase::size(), llvm::AsmToken::Slash, llvm::AsmToken::Star, llvm::SMRange::Start, llvm::StringRef::startswith(), llvm::MCBinaryExpr::Sub, llvm::StringRef::substr(), llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName, llvm::MCExpr::SymbolRef, llvm::StringRef::trim(), llvm::MCSymbolRefExpr::VK_None, llvm::Warning, llvm::MCBinaryExpr::Xor, and llvm::MipsABIFlagsSection::XX.
Variable Documentation
EmitJalrReloc
cl::opt<bool> EmitJalrReloc