LLVM: lib/CodeGen/MIRCanonicalizerPass.cpp File Reference
MIRCanonicalizerPass.cpp File Reference
#include "MIRVRegNamerUtils.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <queue>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "mir-canonicalizer"
Functions
INITIALIZE_PASS_BEGIN (MIRCanonicalizer, "mir-canonicalizer", "Rename Register Operands Canonically", false, false) INITIALIZE_PASS_END(MIRCanonicalizer
mir Rename Register Operands static false std::vector< MachineBasicBlock * > GetRPOList (MachineFunction &MF)
static bool rescheduleLexographically (std::vector< MachineInstr *> instructions, MachineBasicBlock *MBB, std::function< MachineBasicBlock::iterator()> getPos)
static bool rescheduleCanonically (unsigned &PseudoIdempotentInstCount, MachineBasicBlock *MBB)
static bool propagateLocalCopies (MachineBasicBlock *MBB)
static bool doDefKillClear (MachineBasicBlock *MBB)
static bool runOnBasicBlock (MachineBasicBlock *MBB, unsigned BasicBlockNum, VRegRenamer &Renamer)
Variables
static cl::opt< unsigned > CanonicalizeFunctionNumber ("canon-nth-function", cl::Hidden, cl::init(~0u), cl::value_desc("N"), cl::desc("Function number to canonicalize."))
mir canonicalizer
mir Rename Register Operands Canonically
mir Rename Register Operands false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mir-canonicalizer"
Definition at line 45 of file MIRCanonicalizerPass.cpp.
Function Documentation
doDefKillClear()
static bool doDefKillClear (MachineBasicBlock * MBB) static
Definition at line 350 of file MIRCanonicalizerPass.cpp.
References MI.
Referenced by runOnBasicBlock().
GetRPOList()
mir Rename Register Operands static false std::vector<MachineBasicBlock *> GetRPOList (MachineFunction & MF) static
Definition at line 83 of file MIRCanonicalizerPass.cpp.
Referenced by runOnBasicBlock().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (MIRCanonicalizer , "mir-canonicalizer" , "Rename Register Operands Canonically" , false , false)
propagateLocalCopies()
static bool propagateLocalCopies (MachineBasicBlock * MBB) static
Definition at line 303 of file MIRCanonicalizerPass.cpp.
References Copies, llvm::MachineBasicBlock::getParent(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::MachineFunction::getRegInfo(), llvm::MachineBasicBlock::instrs(), llvm::Register::isVirtualRegister(), MI, MRI, llvm::MachineRegisterInfo::use_begin(), and llvm::MachineRegisterInfo::use_end().
Referenced by runOnBasicBlock().
rescheduleCanonically()
static bool rescheduleCanonically (unsigned & PseudoIdempotentInstCount, MachineBasicBlock * MBB) static
Definition at line 136 of file MIRCanonicalizerPass.cpp.
References llvm::dbgs(), llvm::tgtok::Def, llvm::MachineOperand::dump(), E, llvm::find(), llvm::find_if(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MI, MRI, rescheduleLexographically(), and llvm::MachineRegisterInfo::use_nodbg_operands().
Referenced by runOnBasicBlock().
rescheduleLexographically()
static bool rescheduleLexographically (std::vector< MachineInstr *> instructions, MachineBasicBlock * MBB, std::function< MachineBasicBlock::iterator()> getPos) static
Definition at line 96 of file MIRCanonicalizerPass.cpp.
References llvm::dbgs(), llvm::raw_ostream::flush(), LLVM_DEBUG, llvm::sort(), and llvm::MachineBasicBlock::splice().
Referenced by rescheduleCanonically().
runOnBasicBlock()
static bool runOnBasicBlock (MachineBasicBlock * MBB, unsigned BasicBlockNum, VRegRenamer & Renamer) static
Definition at line 372 of file MIRCanonicalizerPass.cpp.
References CanonicalizeFunctionNumber, llvm::dbgs(), doDefKillClear(), llvm::MachineBasicBlock::dump(), llvm::MachineBasicBlock::getName(), llvm::MachineFunction::getName(), llvm::MachineFunction::getRegInfo(), GetRPOList(), LLVM_DEBUG, MRI, propagateLocalCopies(), llvm::VRegRenamer::renameVRegs(), and rescheduleCanonically().
Referenced by INITIALIZE_PASS(), insertNopBeforeInstruction(), isSecondInstructionInSequence(), llvm::SpeculativeExecutionPass::runImpl(), and false::Chain::str().
Variable Documentation
CanonicalizeFunctionNumber
cl::opt<unsigned> CanonicalizeFunctionNumber("canon-nth-function", cl::Hidden, cl::init(~0u), cl::value_desc("N"), cl::desc("Function number to canonicalize.")) static
Referenced by runOnBasicBlock().
canonicalizer
mir canonicalizer
Definition at line 80 of file MIRCanonicalizerPass.cpp.
Canonically
mir Rename Register Operands Canonically
Definition at line 80 of file MIRCanonicalizerPass.cpp.
false
mir Rename Register Operands false
Definition at line 80 of file MIRCanonicalizerPass.cpp.