LLVM: lib/Target/ARM/MLxExpansionPass.cpp File Reference
MLxExpansionPass.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMSubtarget.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "mlx-expansion"
Functions
STATISTIC (NumExpand, "Number of fp MLA / MLS instructions expanded")
static bool isFpMulInstruction (unsigned Opcode)
Variables
static cl::opt< bool > ForceExapnd ("expand-all-fp-mlx", cl::init(false), cl::Hidden)
static cl::opt< unsigned > ExpandLimit ("expand-limit", cl::init(~0U), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlx-expansion"
Definition at line 29 of file MLxExpansionPass.cpp.
Function Documentation
isFpMulInstruction()
static bool isFpMulInstruction (unsigned Opcode) static
Definition at line 196 of file MLxExpansionPass.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::dbgs(), llvm::ARMII::DomainGeneral, llvm::ARMII::DomainMask, E, llvm::MachineInstr::eraseFromParent(), ExpandLimit, llvm::ARMSubtarget::expandMLx(), ForceExapnd, llvm::getDeadRegState(), llvm::MachineInstr::getDebugLoc(), llvm::getDefRegState(), llvm::MachineInstr::getDesc(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::getKillRegState(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), hasRAWHazard(), llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isImplicitDef(), llvm::MachineOperand::isKill(), llvm::ARMSubtarget::isLikeA9(), llvm::MachineInstr::isPosition(), llvm::ARMSubtarget::isSwift(), LLVM_DEBUG, MI, Modified, MRI, llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), TII, TRI, and llvm::MCInstrDesc::TSFlags.
STATISTIC()
STATISTIC (NumExpand , "Number of fp MLA / MLS instructions expanded")
Variable Documentation
ExpandLimit
cl::opt<unsigned> ExpandLimit("expand-limit", cl::init(~0U), cl::Hidden) static
Referenced by isFpMulInstruction().
ForceExapnd
cl::opt<bool> ForceExapnd("expand-all-fp-mlx", cl::init(false), cl::Hidden) static
Referenced by isFpMulInstruction().