LLVM: lib/Transforms/Utils/ModuleUtils.cpp File Reference
ModuleUtils.cpp File Reference
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void appendToGlobalArray (const char *Array, Module &M, Function *F, int Priority, Constant *Data)
static void appendToUsedList (Module &M, StringRef Name, ArrayRef< GlobalValue *> Values)
Function Documentation
appendToGlobalArray()
static void appendToGlobalArray (const char * Array, Module & M, Function * F, int Priority, Constant * Data) static
Definition at line 23 of file ModuleUtils.cpp.
References llvm::GlobalValue::AppendingLinkage, F(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::Module::getContext(), llvm::Type::getInt8PtrTy(), llvm::Module::getNamedGlobal(), llvm::Constant::getNullValue(), llvm::StructType::getNumElements(), llvm::ConstantExpr::getPointerCast(), llvm::PointerType::getUnqual(), and llvm::makeArrayRef().
Referenced by llvm::appendToGlobalCtors(), and llvm::appendToGlobalDtors().
appendToUsedList()
static void appendToUsedList (Module & M, StringRef Name, ArrayRef< GlobalValue *> Values) static
Definition at line 72 of file ModuleUtils.cpp.
References llvm::GlobalValue::AppendingLinkage, C, llvm::SmallVectorBase::empty(), llvm::GlobalVariable::eraseFromParent(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantExpr::getBitCast(), llvm::Module::getContext(), llvm::Module::getGlobalVariable(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt8PtrTy(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorBase::size().
Referenced by llvm::appendToCompilerUsed(), and llvm::appendToUsed().