LLVM: lib/Analysis/ModuleSummaryAnalysis.cpp File Reference
ModuleSummaryAnalysis.cpp File Reference
#include "llvm/Analysis/ModuleSummaryAnalysis.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/IndirectCallPromotionAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/TypeMetadataUtils.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/InitializePasses.h"
#include "llvm/Object/ModuleSymbolTable.h"
#include "llvm/Object/SymbolicFile.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <vector>
Macros
#define DEBUG_TYPE "module-summary-analysis"
Functions
static bool findRefEdges (ModuleSummaryIndex &Index, const User *CurUser, SetVector< ValueInfo > &RefEdges, SmallPtrSet< const User *, 8 > &Visited)
static CalleeInfo::HotnessType getHotness (uint64_t ProfileCount, ProfileSummaryInfo *PSI)
static bool isNonRenamableLocal (const GlobalValue &GV)
static void addVCallToSet (DevirtCallSite Call, GlobalValue::GUID Guid, SetVector< FunctionSummary::VFuncId > &VCalls, SetVector< FunctionSummary::ConstVCall > &ConstVCalls)
Determine whether this call has all constant integer arguments (excluding "this") and summarize it to VCalls or ConstVCalls as appropriate.
static void addIntrinsicToSummary (const CallInst *CI, SetVector< GlobalValue::GUID > &TypeTests, SetVector< FunctionSummary::VFuncId > &TypeTestAssumeVCalls, SetVector< FunctionSummary::VFuncId > &TypeCheckedLoadVCalls, SetVector< FunctionSummary::ConstVCall > &TypeTestAssumeConstVCalls, SetVector< FunctionSummary::ConstVCall > &TypeCheckedLoadConstVCalls, DominatorTree &DT)
If this intrinsic call requires that we add information to the function summary, do so via the non-constant reference arguments.
static bool isNonVolatileLoad (const Instruction *I)
static bool isNonVolatileStore (const Instruction *I)
static void computeFunctionSummary (ModuleSummaryIndex &Index, const Module &M, const Function &F, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI, DominatorTree &DT, bool HasLocalsInUsedOrAsm, DenseSet< GlobalValue::GUID > &CantBePromoted, bool IsThinLTO)
static void findFuncPointers (const Constant *I, uint64_t StartingOffset, const Module &M, ModuleSummaryIndex &Index, VTableFuncList &VTableFuncs)
Find function pointers referenced within the given vtable initializer (or subset of an initializer) I.
static void computeVTableFuncs (ModuleSummaryIndex &Index, const GlobalVariable &V, const Module &M, VTableFuncList &VTableFuncs)
static void recordTypeIdCompatibleVtableReferences (ModuleSummaryIndex &Index, const GlobalVariable &V, SmallVectorImpl< MDNode *> &Types)
Record vtable definition V for each type metadata it references.
static void computeVariableSummary (ModuleSummaryIndex &Index, const GlobalVariable &V, DenseSet< GlobalValue::GUID > &CantBePromoted, const Module &M, SmallVectorImpl< MDNode *> &Types)
static void computeAliasSummary (ModuleSummaryIndex &Index, const GlobalAlias &A, DenseSet< GlobalValue::GUID > &CantBePromoted)
static void setLiveRoot (ModuleSummaryIndex &Index, StringRef Name)
INITIALIZE_PASS_BEGIN (ModuleSummaryIndexWrapperPass, "module-summary-analysis", "Module Summary Analysis", false, true) INITIALIZE_PASS_END(ModuleSummaryIndexWrapperPass
Variables
FunctionSummary::ForceSummaryHotnessType ForceSummaryEdgesCold
cl::opt< FunctionSummary::ForceSummaryHotnessType, true > FSEC ("force-summary-edges-cold", cl::Hidden, cl::location(ForceSummaryEdgesCold), cl::desc("Force all edges in the function summary to cold"), cl::values(clEnumValN(FunctionSummary::FSHT_None, "none", "None."), clEnumValN(FunctionSummary::FSHT_AllNonCritical, "all-non-critical", "All non-critical edges."), clEnumValN(FunctionSummary::FSHT_All, "all", "All edges.")))
cl::opt< std::string > ModuleSummaryDotFile ("module-summary-dot-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("File to emit dot graph of new summary into."))
module summary analysis
module summary Module Summary Analysis
module summary Module Summary false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "module-summary-analysis"
Definition at line 60 of file ModuleSummaryAnalysis.cpp.
Function Documentation
addIntrinsicToSummary()
static void addIntrinsicToSummary (const CallInst * CI, SetVector< GlobalValue::GUID > & TypeTests, SetVector< FunctionSummary::VFuncId > & TypeTestAssumeVCalls, SetVector< FunctionSummary::VFuncId > & TypeCheckedLoadVCalls, SetVector< FunctionSummary::ConstVCall > & TypeTestAssumeConstVCalls, SetVector< FunctionSummary::ConstVCall > & TypeCheckedLoadConstVCalls, DominatorTree & DT) static
If this intrinsic call requires that we add information to the function summary, do so via the non-constant reference arguments.
Definition at line 161 of file ModuleSummaryAnalysis.cpp.
References addVCallToSet(), llvm::any_of(), llvm::dyn_cast(), F(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), llvm::GlobalValue::getGUID(), llvm::Function::getIntrinsicID(), llvm::SetVector< T, Vector, Set >::insert(), and llvm::Value::uses().
Referenced by computeFunctionSummary().
addVCallToSet()
static void addVCallToSet (DevirtCallSite Call, GlobalValue::GUID Guid, SetVector< FunctionSummary::VFuncId > & VCalls, SetVector< FunctionSummary::ConstVCall > & ConstVCalls) static
Determine whether this call has all constant integer arguments (excluding "this") and summarize it to VCalls or ConstVCalls as appropriate.
Definition at line 143 of file ModuleSummaryAnalysis.cpp.
References Arg, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_end(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::DevirtCallSite::CS, llvm::dyn_cast(), llvm::SetVector< T, Vector, Set >::insert(), llvm::make_range(), and llvm::DevirtCallSite::Offset.
Referenced by addIntrinsicToSummary().
computeAliasSummary()
static void computeAliasSummary (ModuleSummaryIndex & Index, const GlobalAlias & A, DenseSet< GlobalValue::GUID > & CantBePromoted) static
Definition at line 615 of file ModuleSummaryAnalysis.cpp.
References llvm::ModuleSummaryIndex::addGlobalValueSummary(), assert(), llvm::GlobalIndirectSymbol::getBaseObject(), llvm::GlobalValue::getGUID(), llvm::GlobalValue::getLinkage(), llvm::ModuleSummaryIndex::getValueInfo(), llvm::GlobalValue::hasGlobalUnnamedAddr(), llvm::GlobalValue::hasLinkOnceODRLinkage(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::GlobalValue::isDSOLocal(), and isNonRenamableLocal().
Referenced by llvm::buildModuleSummaryIndex().
computeFunctionSummary()
static void computeFunctionSummary (ModuleSummaryIndex & Index, const Module & M, const Function & F, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI, DominatorTree & DT, bool HasLocalsInUsedOrAsm, DenseSet< GlobalValue::GUID > & CantBePromoted, bool IsThinLTO) static
Definition at line 242 of file ModuleSummaryAnalysis.cpp.
References llvm::ModuleSummaryIndex::addGlobalValueSummary(), addIntrinsicToSummary(), assert(), Callee, llvm::CalleeInfo::Cold, llvm::CalleeInfo::Critical, llvm::dyn_cast(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::erase(), findRefEdges(), ForceSummaryEdgesCold, llvm::FunctionSummary::FSHT_All, llvm::FunctionSummary::FSHT_None, llvm::BlockFrequencyInfo::getBlockFreq(), llvm::BlockFrequencyInfo::getEntryFreq(), llvm::BlockFrequency::getFrequency(), getHotness(), llvm::ModuleSummaryIndex::getOrInsertValueInfo(), llvm::ProfileSummaryInfo::getProfileCount(), llvm::ICallPromotionAnalysis::getPromotionCandidatesForInstruction(), llvm::Value::hasName(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), isNonRenamableLocal(), isNonVolatileLoad(), isNonVolatileStore(), llvm::SetVector< T, Vector, Set >::remove(), llvm::SetVector< T, Vector, Set >::size(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::takeVector(), llvm::SetVector< T, Vector, Set >::takeVector(), llvm::CalleeInfo::Unknown, and VI.
Referenced by llvm::buildModuleSummaryIndex().
computeVariableSummary()
static void computeVariableSummary (ModuleSummaryIndex & Index, const GlobalVariable & V, DenseSet< GlobalValue::GUID > & CantBePromoted, const Module & M, SmallVectorImpl< MDNode *> & Types) static
Definition at line 570 of file ModuleSummaryAnalysis.cpp.
References llvm::ModuleSummaryIndex::addGlobalValueSummary(), llvm::SmallVectorImpl< T >::clear(), computeVTableFuncs(), llvm::SmallVectorBase::empty(), llvm::ModuleSummaryIndex::enableSplitLTOUnit(), findRefEdges(), llvm::GlobalValue::getGUID(), llvm::GlobalValue::getLinkage(), llvm::GlobalObject::getMetadata(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalObject::hasComdat(), llvm::GlobalValue::hasDLLExportStorageClass(), llvm::GlobalValue::hasGlobalUnnamedAddr(), llvm::GlobalValue::hasLinkOnceODRLinkage(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::GlobalValue::isDSOLocal(), llvm::GlobalValue::isInterposable(), isNonRenamableLocal(), recordTypeIdCompatibleVtableReferences(), and llvm::SetVector< T, Vector, Set >::takeVector().
Referenced by llvm::buildModuleSummaryIndex().
computeVTableFuncs()
static void computeVTableFuncs (ModuleSummaryIndex & Index, const GlobalVariable & V, const Module & M, VTableFuncList & VTableFuncs) static
Definition at line 529 of file ModuleSummaryAnalysis.cpp.
References assert(), findFuncPointers(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::isConstant(), and P.
Referenced by computeVariableSummary().
findFuncPointers()
static void findFuncPointers (const Constant * I, uint64_t StartingOffset, const Module & M, ModuleSummaryIndex & Index, VTableFuncList & VTableFuncs) static
Find function pointers referenced within the given vtable initializer (or subset of an initializer) I.
The starting offset of I within the vtable initializer is StartingOffset. Any discovered function pointers are added to VTableFuncs along with their cumulative offset within the initializer.
Definition at line 488 of file ModuleSummaryAnalysis.cpp.
References assert(), C, llvm::dyn_cast(), llvm::numbers::e, llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::Module::getDataLayout(), llvm::StructLayout::getElementContainingOffset(), llvm::StructLayout::getElementOffset(), llvm::SequentialType::getElementType(), llvm::SequentialType::getNumElements(), llvm::User::getOperand(), llvm::DataLayout::getStructLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Type::isPointerTy(), and llvm::Constant::stripPointerCasts().
Referenced by computeVTableFuncs().
findRefEdges()
static bool findRefEdges (ModuleSummaryIndex & Index, const User * CurUser, SetVector< ValueInfo > & RefEdges, SmallPtrSet< const User *, 8 > & Visited) static
Definition at line 89 of file ModuleSummaryAnalysis.cpp.
References llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::ModuleSummaryIndex::getOrInsertValueInfo(), llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isCallee(), llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by computeFunctionSummary(), and computeVariableSummary().
getHotness()
static CalleeInfo::HotnessType getHotness (uint64_t ProfileCount, ProfileSummaryInfo * PSI) static
Definition at line 126 of file ModuleSummaryAnalysis.cpp.
References llvm::CalleeInfo::Cold, llvm::CalleeInfo::Hot, llvm::ProfileSummaryInfo::isColdCount(), llvm::ProfileSummaryInfo::isHotCount(), llvm::CalleeInfo::None, and llvm::CalleeInfo::Unknown.
Referenced by computeFunctionSummary().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ModuleSummaryIndexWrapperPass , "module-summary-analysis" , "Module Summary Analysis" , false , true)
Referenced by llvm::ModuleSummaryIndexAnalysis::run().
isNonRenamableLocal()
static bool isNonRenamableLocal (const GlobalValue & GV) static
Definition at line 137 of file ModuleSummaryAnalysis.cpp.
References llvm::GlobalValue::hasLocalLinkage(), and llvm::GlobalValue::hasSection().
Referenced by computeAliasSummary(), computeFunctionSummary(), and computeVariableSummary().
isNonVolatileLoad()
static bool isNonVolatileLoad (const Instruction * I) static
Definition at line 228 of file ModuleSummaryAnalysis.cpp.
Referenced by computeFunctionSummary().
isNonVolatileStore()
static bool isNonVolatileStore (const Instruction * I) static
Definition at line 235 of file ModuleSummaryAnalysis.cpp.
References SI.
Referenced by computeFunctionSummary().
recordTypeIdCompatibleVtableReferences()
static void recordTypeIdCompatibleVtableReferences (ModuleSummaryIndex & Index, const GlobalVariable & V, SmallVectorImpl< MDNode *> & Types) static
Record vtable definition V for each type metadata it references.
Definition at line 553 of file ModuleSummaryAnalysis.cpp.
References llvm::ModuleSummaryIndex::getOrInsertTypeIdCompatibleVtableSummary(), and llvm::ModuleSummaryIndex::getOrInsertValueInfo().
Referenced by computeVariableSummary().
setLiveRoot()
static void setLiveRoot (ModuleSummaryIndex & Index, StringRef Name) static
Definition at line 634 of file ModuleSummaryAnalysis.cpp.
References llvm::GlobalValue::getGUID(), llvm::ModuleSummaryIndex::getValueInfo(), and VI.
Referenced by llvm::buildModuleSummaryIndex().
Variable Documentation
analysis
module summary analysis
Definition at line 850 of file ModuleSummaryAnalysis.cpp.
Analysis
module summary Module Summary Analysis
Definition at line 850 of file ModuleSummaryAnalysis.cpp.
false
module summary Module Summary false
Definition at line 850 of file ModuleSummaryAnalysis.cpp.
ForceSummaryEdgesCold
FunctionSummary::ForceSummaryHotnessType ForceSummaryEdgesCold
Initial value:
=
    FunctionSummary::FSHT_None
Definition at line 64 of file ModuleSummaryAnalysis.cpp.
Referenced by computeFunctionSummary().
FSEC
cl::opt<FunctionSummary::ForceSummaryHotnessType, true> FSEC("force-summary-edges-cold", cl::Hidden, cl::location(ForceSummaryEdgesCold), cl::desc("Force all edges in the function summary to cold"), cl::values(clEnumValN(FunctionSummary::FSHT_None, "none", "None."), clEnumValN(FunctionSummary::FSHT_AllNonCritical, "all-non-critical", "All non-critical edges."), clEnumValN(FunctionSummary::FSHT_All, "all", "All edges.")))
ModuleSummaryDotFile
cl::opt<std::string> ModuleSummaryDotFile("module-summary-dot-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("File to emit dot graph of new summary into."))
Referenced by llvm::buildModuleSummaryIndex().