LLVM: lib/Target/MSP430/Disassembler/MSP430Disassembler.cpp File Reference
MSP430Disassembler.cpp File Reference
#include "MSP430.h"
#include "MCTargetDesc/MSP430MCTargetDesc.h"
#include "TargetInfo/MSP430TargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/TargetRegistry.h"
#include "MSP430GenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "msp430-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Enumerations
enum AddrMode {
amInvalid = 0, amRegister, amIndexed, amIndirect,
amIndirectPost, amSymbolic, amImmediate, amAbsolute,
amConstant
}
Functions
static MCDisassembler * createMSP430Disassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430Disassembler ()
static DecodeStatus DecodeGR8RegisterClass (MCInst &MI, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGR16RegisterClass (MCInst &MI, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCGImm (MCInst &MI, uint64_t Bits, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMemOperand (MCInst &MI, uint64_t Bits, uint64_t Address, const void *Decoder)
static AddrMode DecodeSrcAddrMode (unsigned Rs, unsigned As)
static AddrMode DecodeSrcAddrModeI (unsigned Insn)
static AddrMode DecodeSrcAddrModeII (unsigned Insn)
static AddrMode DecodeDstAddrMode (unsigned Insn)
static const uint8_t * getDecoderTable (AddrMode SrcAM, unsigned Words)
static MSP430CC::CondCodes getCondCode (unsigned Cond)
Variables
static const unsigned GR8DecoderTable []
static const unsigned GR16DecoderTable []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "msp430-disassembler"
Definition at line 27 of file MSP430Disassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 29 of file MSP430Disassembler.cpp.
Enumeration Type Documentation
AddrMode
enum AddrMode
Enumerator
amInvalid
amRegister
amIndexed
amIndirect
amIndirectPost
amSymbolic
amImmediate
amAbsolute
amConstant
Definition at line 142 of file MSP430Disassembler.cpp.
Function Documentation
createMSP430Disassembler()
static MCDisassembler* createMSP430Disassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 55 of file MSP430Disassembler.cpp.
Referenced by LLVMInitializeMSP430Disassembler().
DecodeCGImm()
static DecodeStatus DecodeCGImm (MCInst & MI, uint64_t Bits, uint64_t Address, const void * Decoder) static
Definition at line 111 of file MSP430Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm_unreachable, and llvm::MCDisassembler::Success.
Referenced by DecodeGR16RegisterClass().
DecodeDstAddrMode()
static AddrMode DecodeDstAddrMode (unsigned Insn) static
Definition at line 193 of file MSP430Disassembler.cpp.
References amAbsolute, amIndexed, amRegister, and amSymbolic.
Referenced by getDecoderTable().
DecodeGR16RegisterClass()
static DecodeStatus DecodeGR16RegisterClass (MCInst & MI, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 91 of file MSP430Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::tgtok::Bits, llvm::MCOperand::createReg(), DecodeCGImm(), DecodeMemOperand(), llvm::MCDisassembler::Fail, MI, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeMemOperand().
DecodeGR8RegisterClass()
static DecodeStatus DecodeGR8RegisterClass (MCInst & MI, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 73 of file MSP430Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeMemOperand()
static DecodeStatus DecodeMemOperand (MCInst & MI, uint64_t Bits, uint64_t Address, const void * Decoder) static
Definition at line 128 of file MSP430Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeGR16RegisterClass(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeGR16RegisterClass().
DecodeSrcAddrMode()
static AddrMode DecodeSrcAddrMode (unsigned Rs, unsigned As) static
Definition at line 154 of file MSP430Disassembler.cpp.
References amAbsolute, amConstant, amImmediate, amIndexed, amIndirect, amIndirectPost, amInvalid, amRegister, amSymbolic, and llvm_unreachable.
Referenced by DecodeSrcAddrModeI(), and DecodeSrcAddrModeII().
DecodeSrcAddrModeI()
static AddrMode DecodeSrcAddrModeI (unsigned Insn) static
Definition at line 181 of file MSP430Disassembler.cpp.
References DecodeSrcAddrMode().
Referenced by getDecoderTable().
DecodeSrcAddrModeII()
static AddrMode DecodeSrcAddrModeII (unsigned Insn) static
Definition at line 187 of file MSP430Disassembler.cpp.
References DecodeSrcAddrMode().
Referenced by getDecoderTable().
getCondCode()
static MSP430CC::CondCodes getCondCode (unsigned Cond) static
Definition at line 324 of file MSP430Disassembler.cpp.
Referenced by llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getSelectCC(), and llvm::SelectionDAG::getSetCC().
getDecoderTable()
static const uint8_t* getDecoderTable (AddrMode SrcAM, unsigned Words) static
Definition at line 205 of file MSP430Disassembler.cpp.
References llvm::Address, amAbsolute, amConstant, amImmediate, amIndexed, amIndirect, amIndirectPost, amInvalid, amRegister, amSymbolic, assert(), llvm::ArrayRef< T >::data(), DecodeDstAddrMode(), DecodeSrcAddrModeI(), DecodeSrcAddrModeII(), llvm::MCDisassembler::Fail, Fail, llvm_unreachable, llvm::support::endian::read16le(), Size, and llvm::ArrayRef< T >::size().
LLVMInitializeMSP430Disassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430Disassembler ()
Definition at line 61 of file MSP430Disassembler.cpp.
References createMSP430Disassembler(), llvm::getTheMSP430Target(), and llvm::TargetRegistry::RegisterMCDisassembler().
Variable Documentation
GR16DecoderTable
const unsigned GR16DecoderTable[] static
Initial value:
= {
  MSP430::PC,  MSP430::SP,  MSP430::SR,  MSP430::CG,
  MSP430::FP,  MSP430::R5,  MSP430::R6,  MSP430::R7,
  MSP430::R8,  MSP430::R9,  MSP430::R10, MSP430::R11,
  MSP430::R12, MSP430::R13, MSP430::R14, MSP430::R15
}
Definition at line 84 of file MSP430Disassembler.cpp.
GR8DecoderTable
const unsigned GR8DecoderTable[] static
Initial value:
= {
  MSP430::PCB,  MSP430::SPB,  MSP430::SRB,  MSP430::CGB,
  MSP430::FPB,  MSP430::R5B,  MSP430::R6B,  MSP430::R7B,
  MSP430::R8B,  MSP430::R9B,  MSP430::R10B, MSP430::R11B,
  MSP430::R12B, MSP430::R13B, MSP430::R14B, MSP430::R15B
}
Definition at line 66 of file MSP430Disassembler.cpp.