LLVM: lib/Target/MSP430/MSP430BranchSelector.cpp File Reference
MSP430BranchSelector.cpp File Reference
#include "MSP430.h"
#include "MSP430InstrInfo.h"
#include "MSP430Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "msp430-branch-select"
Functions
STATISTIC (NumSplit, "Number of machine basic blocks split")
STATISTIC (NumExpanded, "Number of branches expanded to long format")
static bool isInRage (int DistanceInBytes)
Variables
static cl::opt< bool > BranchSelectEnabled ("msp430-branch-select", cl::Hidden, cl::init(true), cl::desc("Expand out of range branches"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "msp430-branch-select"
Definition at line 28 of file MSP430BranchSelector.cpp.
Function Documentation
isInRage()
static bool isInRage (int DistanceInBytes) static
Definition at line 65 of file MSP430BranchSelector.cpp.
References llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::dbgs(), E, llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::insert(), LLVM_DEBUG, llvm::make_range(), MI, llvm::printMBBReference(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::successors(), and TII.
STATISTIC() [1/2]
STATISTIC (NumSplit , "Number of machine basic blocks split")
STATISTIC() [2/2]
STATISTIC (NumExpanded , "Number of branches expanded to long format")
Variable Documentation
BranchSelectEnabled
cl::opt<bool> BranchSelectEnabled("msp430-branch-select", cl::Hidden, cl::init(true), cl::desc("Expand out of range branches")) static