LLVM: lib/Target/ARM/MVEGatherScatterLowering.cpp File Reference
MVEGatherScatterLowering.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMSubtarget.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include <algorithm>
#include <cassert>
Macros
#define DEBUG_TYPE "mve-gather-scatter-lowering"
Functions
INITIALIZE_PASS (MVEGatherScatterLowering, DEBUG_TYPE, "MVE gather/scattering lowering pass", false, false) Pass *llvm
Variables
cl::opt< bool > EnableMaskedGatherScatters ("enable-arm-maskedgatscat", cl::Hidden, cl::init(false), cl::desc("Enable the generation of masked gathers and scatters"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mve-gather-scatter-lowering"
Definition at line 45 of file MVEGatherScatterLowering.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (MVEGatherScatterLowering , DEBUG_TYPE , "MVE gather/scattering lowering pass" , false , false)
Definition at line 97 of file MVEGatherScatterLowering.cpp.
References assert(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::dbgs(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), EnableMaskedGatherScatters, llvm::Instruction::eraseFromParent(), F(), GEP, llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::IRBuilderBase::getInt32(), llvm::VectorType::getInteger(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Type::getPointerElementType(), llvm::GetElementPtrInst::getPointerOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), I, llvm::Type::isVectorTy(), LLVM_DEBUG, llvm::SPII::Load, llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), runOnFunction(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), llvm::ARM_MB::ST, and llvm::SystemZISD::TM.
Variable Documentation
EnableMaskedGatherScatters
cl::opt<bool> EnableMaskedGatherScatters("enable-arm-maskedgatscat", cl::Hidden, cl::init(false), cl::desc("Enable the generation of masked gathers and scatters"))
Referenced by INITIALIZE_PASS().