LLVM: lib/Target/ARM/MVEVPTBlockPass.cpp File Reference
MVEVPTBlockPass.cpp File Reference
#include "ARM.h"
#include "ARMMachineFunctionInfo.h"
#include "ARMSubtarget.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "Thumb2InstrInfo.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/ReachingDefAnalysis.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Support/Debug.h"
#include <cassert>
#include <new>
Macros
#define DEBUG_TYPE "arm-mve-vpt"
Functions
static MachineInstr * findVCMPToFoldIntoVPST (MachineInstr *MI, ReachingDefAnalysis *RDA, unsigned &NewOpcode)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-mve-vpt"
Definition at line 34 of file MVEVPTBlockPass.cpp.
Function Documentation
findVCMPToFoldIntoVPST()
static MachineInstr* findVCMPToFoldIntoVPST (MachineInstr * MI, ReachingDefAnalysis * RDA, unsigned & NewOpcode) static
Definition at line 74 of file MVEVPTBlockPass.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), llvm::dbgs(), llvm::tgtok::Def, llvm::MachineInstr::dump(), llvm::ARMVCC::Else, llvm::finalizeBundle(), llvm::getARMVPTBlockMask(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::MachineInstrBuilder::getInstr(), llvm::ARMSubtarget::getInstrInfo(), llvm::MachineFunction::getName(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getSubtarget(), llvm::getVPTInstrPredicate(), llvm::ARMSubtarget::hasMVEIntegerOps(), I, llvm::SmallSet< T, N, C >::insert(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::ARMSubtarget::isThumb2(), LLVM_DEBUG, MI, Modified, llvm::ARMVCC::None, TII, llvm::ARMISD::VCMP, and llvm::VCMPOpcodeToVPT().