LLVM: llvm::SystemZII Namespace Reference
llvm::SystemZII Namespace Reference
Classes
class Branch
Enumerations
enum {
SimpleBDXLoad = (1 << 0), SimpleBDXStore = (1 << 1), Has20BitOffset = (1 << 2), HasIndex = (1 << 3),
Is128Bit = (1 << 4), AccessSizeMask = (31 << 5), AccessSizeShift = 5, CCValuesMask = (15 << 10),
CCValuesShift = 10, CompareZeroCCMaskMask = (15 << 14), CompareZeroCCMaskShift = 14, CCMaskFirst = (1 << 18),
CCMaskLast = (1 << 19), IsLogical = (1 << 20), CCIfNoSignedWrap = (1 << 21)
}
enum { MO_SYMBOL_MODIFIER = (3 << 0), MO_GOT = (1 << 0), MO_INDNTPOFF = (2 << 0) }
enum BranchType {
BranchNormal, BranchC, BranchCL, BranchCG,
BranchCLG, BranchCT, BranchCTG, AsmGoto
}
enum FusedCompareType { CompareAndBranch, CompareAndReturn, CompareAndSibcall, CompareAndTrap }
Functions
static unsigned getAccessSize (unsigned int Flags)
static unsigned getCCValues (unsigned int Flags)
static unsigned getCompareZeroCCMask (unsigned int Flags)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SimpleBDXLoad
SimpleBDXStore
Has20BitOffset
HasIndex
Is128Bit
AccessSizeMask
AccessSizeShift
CCValuesMask
CCValuesShift
CompareZeroCCMaskMask
CompareZeroCCMaskShift
CCMaskFirst
CCMaskLast
IsLogical
CCIfNoSignedWrap
Definition at line 34 of file SystemZInstrInfo.h.
anonymous enum
anonymous enum
Enumerator
MO_SYMBOL_MODIFIER
MO_GOT
MO_INDNTPOFF
Definition at line 66 of file SystemZInstrInfo.h.
BranchType
enum llvm::SystemZII::BranchType
Enumerator
BranchNormal
BranchC
BranchCL
BranchCG
BranchCLG
BranchCT
BranchCTG
AsmGoto
Definition at line 78 of file SystemZInstrInfo.h.
FusedCompareType
enum llvm::SystemZII::FusedCompareType
Enumerator
CompareAndBranch
CompareAndReturn
CompareAndSibcall
CompareAndTrap
Definition at line 139 of file SystemZInstrInfo.h.
Function Documentation
getAccessSize()
static unsigned llvm::SystemZII::getAccessSize (unsigned int Flags) inline static
Definition at line 53 of file SystemZInstrInfo.h.
References AccessSizeMask, and AccessSizeShift.
Referenced by llvm::SystemZInstrInfo::foldMemoryOperandImpl().
getCCValues()
static unsigned llvm::SystemZII::getCCValues (unsigned int Flags) inline static
Definition at line 57 of file SystemZInstrInfo.h.
References CCValuesMask, and CCValuesShift.
Referenced by isAddWithImmediate().
getCompareZeroCCMask()
static unsigned llvm::SystemZII::getCompareZeroCCMask (unsigned int Flags) inline static
Definition at line 61 of file SystemZInstrInfo.h.
References CompareZeroCCMaskMask, and CompareZeroCCMaskShift.
Referenced by isAddWithImmediate().