LLVM: llvm::LPAC Namespace Reference
llvm::LPAC Namespace Reference
Enumerations
enum AluCode {
ADD = 0x00, ADDC = 0x01, SUB = 0x02, SUBB = 0x03,
AND = 0x04, OR = 0x05, XOR = 0x06, SPECIAL = 0x07,
SHL = 0x17, SRL = 0x27, SRA = 0x37, UNKNOWN = 0xFF
}
Functions
static unsigned encodeLanaiAluCode (unsigned AluOp)
static unsigned getAluOp (unsigned AluOp)
static bool isPreOp (unsigned AluOp)
static bool isPostOp (unsigned AluOp)
static unsigned makePreOp (unsigned AluOp)
static unsigned makePostOp (unsigned AluOp)
static bool modifiesOp (unsigned AluOp)
static const char * lanaiAluCodeToString (unsigned AluOp)
static AluCode stringToLanaiAluCode (StringRef S)
static AluCode isdToLanaiAluCode (ISD::NodeType Node_type)
Variables
const int Lanai_PRE_OP = 0x40
const int Lanai_POST_OP = 0x80
Enumeration Type Documentation
AluCode
enum llvm::LPAC::AluCode
Enumerator
ADD
ADDC
SUB
SUBB
AND
OR
XOR
SPECIAL
SHL
SRL
SRA
UNKNOWN
Definition at line 22 of file LanaiAluCode.h.
Function Documentation
encodeLanaiAluCode()
static unsigned llvm::LPAC::encodeLanaiAluCode (unsigned AluOp) inline static
Definition at line 48 of file LanaiAluCode.h.
Referenced by llvm::adjustPqBits(), and usesGivenOffset().
getAluOp()
static unsigned llvm::LPAC::getAluOp (unsigned AluOp) inline static
Definition at line 53 of file LanaiAluCode.h.
Referenced by llvm::adjustPqBits(), and lanaiAluCodeToString().
isdToLanaiAluCode()
static AluCode llvm::LPAC::isdToLanaiAluCode (ISD::NodeType Node_type) inline static
Definition at line 118 of file LanaiAluCode.h.
References ADD, llvm::ISD::ADD, ADDC, llvm::ISD::ADDE, AND, llvm::ISD::AND, OR, llvm::ISD::OR, SHL, llvm::ISD::SHL, SRA, llvm::ISD::SRA, SRL, llvm::ISD::SRL, SUB, llvm::ISD::SUB, SUBB, llvm::ISD::SUBE, UNKNOWN, XOR, and llvm::ISD::XOR.
isPostOp()
static bool llvm::LPAC::isPostOp (unsigned AluOp) inline static
Definition at line 60 of file LanaiAluCode.h.
References Lanai_POST_OP.
Referenced by llvm::adjustPqBits(), isPostIncrementForm(), makePreOp(), modifiesOp(), printMemoryBaseRegister(), and llvm::LanaiInstPrinter::printMemRrOperand().
isPreOp()
static bool llvm::LPAC::isPreOp (unsigned AluOp) inline static
Definition at line 58 of file LanaiAluCode.h.
References Lanai_PRE_OP.
Referenced by llvm::adjustPqBits(), isPreIncrementForm(), makePostOp(), modifiesOp(), printMemoryBaseRegister(), and llvm::LanaiInstPrinter::printMemRrOperand().
lanaiAluCodeToString()
static const char* llvm::LPAC::lanaiAluCodeToString (unsigned AluOp) inline static
Definition at line 76 of file LanaiAluCode.h.
References ADD, ADDC, AND, getAluOp(), llvm_unreachable, OR, SHL, SRA, SRL, SUB, SUBB, and XOR.
Referenced by llvm::LanaiInstPrinter::printMemRrOperand().
makePostOp()
static unsigned llvm::LPAC::makePostOp (unsigned AluOp) inline static
Definition at line 67 of file LanaiAluCode.h.
References assert(), isPreOp(), and Lanai_POST_OP.
Referenced by AluWithPrePost(), INITIALIZE_PASS(), and PostOperandDecodeAdjust().
makePreOp()
static unsigned llvm::LPAC::makePreOp (unsigned AluOp) inline static
Definition at line 62 of file LanaiAluCode.h.
References assert(), isPostOp(), and Lanai_PRE_OP.
Referenced by AluWithPrePost(), llvm::LanaiFrameLowering::emitPrologue(), INITIALIZE_PASS(), and PostOperandDecodeAdjust().
modifiesOp()
static bool llvm::LPAC::modifiesOp (unsigned AluOp) inline static
Definition at line 72 of file LanaiAluCode.h.
References isPostOp(), and isPreOp().
Referenced by llvm::adjustPqBits(), and IsMemoryAssignmentError().
stringToLanaiAluCode()
static AluCode llvm::LPAC::stringToLanaiAluCode (StringRef S) inline static
Definition at line 103 of file LanaiAluCode.h.
References ADD, ADDC, AND, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), OR, SHL, SRA, SRL, SUB, SUBB, UNKNOWN, and XOR.
Referenced by AluWithPrePost().
Variable Documentation
Lanai_POST_OP
const int llvm::LPAC::Lanai_POST_OP = 0x80
Definition at line 46 of file LanaiAluCode.h.
Referenced by isPostOp(), and makePostOp().
Lanai_PRE_OP
const int llvm::LPAC::Lanai_PRE_OP = 0x40
Definition at line 45 of file LanaiAluCode.h.
Referenced by isPreOp(), and makePreOp().