LLVM: llvm::LPCC Namespace Reference
llvm::LPCC Namespace Reference
Enumerations
enum CondCode {
ICC_T = 0, ICC_F = 1, ICC_HI = 2, ICC_UGT = 2,
ICC_LS = 3, ICC_ULE = 3, ICC_CC = 4, ICC_ULT = 4,
ICC_CS = 5, ICC_UGE = 5, ICC_NE = 6, ICC_EQ = 7,
ICC_VC = 8, ICC_VS = 9, ICC_PL = 10, ICC_MI = 11,
ICC_GE = 12, ICC_LT = 13, ICC_GT = 14, ICC_LE = 15,
UNKNOWN
}
Functions
static StringRef lanaiCondCodeToString (LPCC::CondCode CC)
static CondCode suffixToLanaiCondCode (StringRef S)
Enumeration Type Documentation
CondCode
enum llvm::LPCC::CondCode
Enumerator
ICC_T
ICC_F
ICC_HI
ICC_UGT
ICC_LS
ICC_ULE
ICC_CC
ICC_ULT
ICC_CS
ICC_UGE
ICC_NE
ICC_EQ
ICC_VC
ICC_VS
ICC_PL
ICC_MI
ICC_GE
ICC_LT
ICC_GT
ICC_LE
UNKNOWN
Definition at line 10 of file LanaiCondCode.h.
Function Documentation
lanaiCondCodeToString()
static StringRef llvm::LPCC::lanaiCondCodeToString (LPCC::CondCode CC) inline static
Definition at line 34 of file LanaiCondCode.h.
References ICC_EQ, ICC_F, ICC_GE, ICC_GT, ICC_LE, ICC_LT, ICC_MI, ICC_NE, ICC_PL, ICC_T, ICC_UGE, ICC_UGT, ICC_ULE, ICC_ULT, ICC_VC, ICC_VS, and llvm_unreachable.
Referenced by llvm::LanaiInstPrinter::printCCOperand(), and llvm::LanaiInstPrinter::printPredicateOperand().
suffixToLanaiCondCode()
static CondCode llvm::LPCC::suffixToLanaiCondCode (StringRef S) inline static
Definition at line 73 of file LanaiCondCode.h.
References llvm::StringSwitch< T, R >::Default(), llvm::StringSwitch< T, R >::EndsWith(), ICC_CC, ICC_CS, ICC_EQ, ICC_F, ICC_GE, ICC_GT, ICC_HI, ICC_LE, ICC_LS, ICC_LT, ICC_MI, ICC_NE, ICC_PL, ICC_T, ICC_UGE, ICC_UGT, ICC_ULE, ICC_ULT, ICC_VC, ICC_VS, and UNKNOWN.
Referenced by shouldBeSls().