LLVM: llvm::unittest Namespace Reference
llvm::unittest Namespace Reference
Functions
SmallString< 128 > getInputFileDirectory (const char *Argv0)
Function Documentation
getInputFileDirectory()
SmallString< 128 > llvm::unittest::getInputFileDirectory (const char * Argv0)
Definition at line 36 of file SupportHelpers.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::sys::path::append(), llvm::SmallVectorImpl< T >::clear(), File, findSrcDirMap(), llvm::MemoryBuffer::getFile(), and llvm::sys::path::native().