LLVM: llvm::ELFYAML Namespace Reference
llvm::ELFYAML Namespace Reference
Classes
struct AddrsigSection
struct AddrsigSymbol
struct Chunk
struct DependentLibrariesSection
struct DynamicEntry
struct DynamicSection
struct FileHeader
struct Fill
struct GnuHashHeader
struct GnuHashSection
struct Group
struct HashSection
struct LinkerOption
struct LinkerOptionsSection
struct MipsABIFlags
struct NoBitsSection
struct NoteEntry
struct NoteSection
struct Object
struct ProgramHeader
struct RawContentSection
struct Relocation
struct RelocationSection
struct RelrSection
struct Section
struct SectionName
struct SectionOrType
struct StackSizeEntry
struct StackSizesSection
struct Symbol
struct SymtabShndxSection
struct SymverSection
struct VerdefEntry
struct VerdefSection
struct VernauxEntry
struct VerneedEntry
struct VerneedSection
Functions
StringRef dropUniqueSuffix (StringRef S)
Function Documentation
dropUniqueSuffix()
StringRef llvm::ELFYAML::dropUniqueSuffix (StringRef S)
Definition at line 396 of file ELFEmitter.cpp.
References llvm::ELFYAML::Section::Address, llvm::ELFYAML::Section::AddressAlign, assert(), llvm::ELFYAML::Object::Chunks, llvm::StringRef::empty(), llvm::ELFYAML::Section::EntSize, llvm::ELFYAML::Section::Flags, llvm::ELFYAML::Section::IsImplicit, llvm::ELFYAML::Section::Link, llvm_unreachable, llvm::ELFYAML::Chunk::Name, llvm::StringRef::npos, llvm::StringRef::rfind(), llvm::StringRef::substr(), and llvm::ELFYAML::Section::Type.
Referenced by isMips64EL(), llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping(), and writeContent().