LLVM: llvm::pgo Namespace Reference
llvm::pgo Namespace Reference
Functions
Instruction * promoteIndirectCall (Instruction *Inst, Function *F, uint64_t Count, uint64_t TotalCount, bool AttachProfToDirectCall, OptimizationRemarkEmitter *ORE)
Function Documentation
promoteIndirectCall()
Instruction * llvm::pgo::promoteIndirectCall (Instruction * Inst, Function * F, uint64_t Count, uint64_t TotalCount, bool AttachProfToDirectCall, OptimizationRemarkEmitter * ORE)
Definition at line 297 of file IndirectCallPromotion.cpp.
References llvm::annotateValueSite(), assert(), C, llvm::calculateCountScale(), DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), F(), llvm::findIndirectCalls(), llvm::Value::getContext(), llvm::ICallPromotionAnalysis::getPromotionCandidatesForInstruction(), llvm::ProfileSummaryInfo::hasProfileSummary(), I, llvm::ProfileSummaryInfo::isHotCount(), llvm::promoteCallWithIfThenElse(), llvm::scaleBranchCount(), and llvm::Instruction::setMetadata().