LLVM: llvm::coro Namespace Reference
llvm::coro Namespace Reference
Classes
struct LowererBase
struct Shape
Enumerations
enum ABI { ABI::Switch, ABI::Retcon, ABI::RetconOnce }
Functions
bool declaresIntrinsics (const Module &M, const std::initializer_list< StringRef >)
void replaceAllCoroAllocs (CoroBeginInst *CB, bool Replacement)
void replaceAllCoroFrees (CoroBeginInst *CB, Value *Replacement)
void replaceCoroFree (CoroIdInst *CoroId, bool Elide)
void updateCallGraph (Function &Caller, ArrayRef< Function *> Funcs, CallGraph &CG, CallGraphSCC &SCC)
void buildCoroutineFrame (Function &F, Shape &Shape)
Enumeration Type Documentation
ABI
enum llvm::coro::ABI strong
Enumerator
Switch
The "resume-switch" lowering, where there are separate resume and destroy functions that are shared between all suspend points.
The coroutine frame implicitly stores the resume and destroy functions, the current index, and any promise value.
Retcon
The "returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises.
RetconOnce
The "unique returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises. The function is known to suspend at most once during its execution, and the return value of the continuation is void.
Definition at line 66 of file CoroInternal.h.
Function Documentation
buildCoroutineFrame()
void llvm::coro::buildCoroutineFrame (Function & F, Shape & Shape)
Definition at line 1325 of file CoroFrame.cpp.
References llvm::coro::Shape::ABI, llvm::Function::args(), llvm::CoroIdInst::clearPromise(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroEnds, llvm::coro::Shape::CoroSuspends, llvm::dump(), eliminateSwiftError(), llvm::Function::getContext(), llvm::coro::Shape::getSwitchCoroId(), I, llvm::instructions(), isCoroutineStructureIntrinsic(), isLocalAlloca(), LLVM_DEBUG, llvm::LowerDbgDeclare(), materializable(), llvm::coro::Shape::SwitchLoweringStorage::PromiseAlloca, llvm::SmallVectorTemplateBase< T >::push_back(), rewriteMaterializableInstructions(), rewritePHIs(), splitAround(), Switch, and llvm::coro::Shape::SwitchLowering.
Referenced by llvm::coro::Shape::Shape(), and splitCoroutine().
declaresIntrinsics()
bool llvm::coro::declaresIntrinsics (const Module & M, const std::initializer_list< StringRef > List)
Definition at line 154 of file Coroutines.cpp.
References assert(), llvm::Module::getNamedValue(), isCoroutineIntrinsicName(), and Name.
Referenced by lowerSubFn(), replaceAllPrepares(), replaceDevirtTrigger(), and setCannotDuplicate().
replaceAllCoroAllocs()
void llvm::coro::replaceAllCoroAllocs (CoroBeginInst * CB, bool Replacement)
replaceAllCoroFrees()
void llvm::coro::replaceAllCoroFrees (CoroBeginInst * CB, Value * Replacement)
replaceCoroFree()
void llvm::coro::replaceCoroFree (CoroIdInst * CoroId, bool Elide)
Definition at line 167 of file Coroutines.cpp.
References llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::front(), llvm::ConstantPointerNull::get(), llvm::Value::getContext(), llvm::Type::getInt8PtrTy(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::Value::users().
Referenced by getFirstNonAllocaInTheEntryBlock(), handleNoSuspendCoroutine(), and replaceSwiftErrorOps().
updateCallGraph()
void llvm::coro::updateCallGraph (Function & Caller, ArrayRef< Function *> Funcs, CallGraph & CG, CallGraphSCC & SCC)
Definition at line 208 of file Coroutines.cpp.
References llvm::CallGraphSCC::begin(), buildCGN(), Callee, llvm::CallGraphSCC::end(), F(), llvm::CallGraph::getOrInsertFunction(), and llvm::CallGraphSCC::initialize().
Referenced by splitCoroutine().