LLVM: llvm::BitmaskEnumDetail Namespace Reference
llvm::BitmaskEnumDetail Namespace Reference
Functions
template<typename E >
std::underlying_type< E >::type Mask ()
Get a bitmask with 1s in all places up to the high-order bit of E's largest value.
template<typename E >
std::underlying_type< E >::type Underlying (E Val)
Check that Val is in range for E, and return Val cast to E's underlying type.
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type>
E operator~ (E Val)
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type>
E operator| (E LHS, E RHS)
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type>
E operator & (E LHS, E RHS)
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type>
E operator^ (E LHS, E RHS)
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type>
E & operator|= (E &LHS, E RHS)
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type>
E & operator &= (E &LHS, E RHS)
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type>
E & operator^= (E &LHS, E RHS)
Function Documentation
Mask()
template<typename E > std::underlying_type<E>::type llvm::BitmaskEnumDetail::Mask ()
Get a bitmask with 1s in all places up to the high-order bit of E's largest value.
Definition at line 80 of file BitmaskEnum.h.
References llvm::NextPowerOf2().
Referenced by llvm::LiveRegUnits::addRegMasked(), addSegmentsWithValNo(), adjustFixupValue(), adjustForRedundantAnd(), adjustForTestUnderMask(), adjustSubwordCmp(), llvm::MachineFunction::allocateRegMask(), llvm::SITargetLowering::allocateSpecialInputVGPRs(), allocateVGPR32Input(), llvm::analyzeArguments(), llvm::MipsAsmBackend::applyFixup(), ApplyX86MaskOn1BitsVec(), llvm::LivePhysRegs::available(), llvm::lowertypetests::BitSetBuilder::build(), buildCallOperands(), buildFromShuffleMostly(), callingConvSupported(), llvm::canConstantFoldCallTo(), canEvaluateShiftedShift(), canEvaluateShuffled(), canEvaluateTruncated(), canonicalizeInsertSplat(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::ARMTargetLowering::CCAssignFnForReturn(), llvm::GlobalObject::classof(), llvm::APInt::clearBit(), llvm::SmallBitVector::clearBitsInMask(), llvm::BitVector::clearBitsInMask(), llvm::SmallBitVector::clearBitsNotInMask(), llvm::BitVector::clearBitsNotInMask(), CollectOpsToWiden(), collectShuffleElements(), combineADDToADDZE(), combineBasicSADPattern(), combineConcatVectorOfExtracts(), combineExtractWithShuffle(), combineGatherScatter(), combineHorizontalMinMaxResult(), combineInsertSubvector(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMaskedStore(), combineShiftOfShiftedLogic(), combineShuffleOfConcatUndef(), combineShuffleToVectorExtend(), combineTargetShuffle(), combineTruncationShuffle(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), commitFpm(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::TargetRegisterInfo::composeSubRegIndexLaneMask(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::computeKnownBitsFromRangeMetadata(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), computeRecurrenceType(), concatenateTwoVectors(), llvm::ConstantFoldCastOperand(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::MachineInstr::copyIRFlags(), llvm::detail::TrailingZerosCounter< T, SizeOfT >::count(), llvm::createAMDGPUPrintfRuntimeBinding(), llvm::createBitMaskForGaps(), createBSWAPShuffleMask(), llvm::LiveRangeCalc::createDeadDefs(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::mca::InstrBuilder::createInstruction(), llvm::createInterleaveMask(), createMaskedBitTest(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilder< TargetFolder >::CreatePreserveStructAccessIndex(), llvm::createR600ExpandSpecialInstrsPass(), llvm::MachineOperand::CreateRegLiveOut(), llvm::MachineOperand::CreateRegMask(), llvm::MachineOperand::CreateShuffleMask(), llvm::IRBuilder< TargetFolder >::CreateShuffleVector(), llvm::createSIModeRegisterPass(), llvm::mca::ExecuteStage::cycleEnd(), llvm::MachineFunction::deallocateOperandArray(), DecodeMSRMask(), decomposeBitTestICmp(), llvm::RISCVInstrInfo::decomposeMachineOperandsTargetFlags(), llvm::AArch64InstrInfo::decomposeMachineOperandsTargetFlags(), llvm::ARMBaseInstrInfo::decomposeMachineOperandsTargetFlags(), llvm::PPCInstrInfo::decomposeMachineOperandsTargetFlags(), llvm::mca::DefaultResourceStrategy::DefaultResourceStrategy(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::DWARFContext::dump(), earlyExpandDIVFIX(), eliminateDeadStores(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::X86AsmPrinter::EmitInstruction(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::UnwindOpcodeAssembler::EmitRegSave(), encodeBitmaskPerm(), llvm::RuntimeDyldCheckerExprEval::evaluate(), evaluateInDifferentElementOrder(), expandf64Toi32(), llvm::AArch64_IMM::expandMOVImm(), llvm::AArch64_IMM::expandMOVImmSimple(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtractBitFromMaskVector(), extractVector(), llvm::SmallBitVector::find_next_unset(), findMemSDNode(), foldAndOrOfEqualityCmpsWithConstants(), foldAnyOrAllBitsSet(), foldConstantInsEltIntoShuffle(), foldICmpBitCast(), foldICmpShlOne(), foldICmpWithMinMax(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldInsSequenceIntoSplat(), foldLogOpOfMaskedICmps(), foldMaskedShiftToScaledMask(), foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldVecTruncToExtElt(), foreachUnit(), fp16SrcZerosHighBits(), GeneratePerfectShuffle(), GetAEABIUnwindPersonalityName(), getARClassRegisterMask(), getAVX2GatherNode(), getCallOpcode(), getCmpOperandFoldingProfit(), getDemandedSrcElements(), getDwarfRegNum(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::StackMaps::getFnInfos(), GetFPLibCall(), llvm::DWARFUnitIndex::getFromHash(), getGatherNode(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::X86TargetLowering::getInlineAsmMemConstraint(), getInsertVecEltOpInfo(), getIntrinsicForMaskedAtomicRMWBinOp(), llvm::MachineInstr::getIntrinsicID(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::ARMTargetLowering::getJumpTableEncoding(), llvm::PPCRegisterInfo::getMappedIdxOpcForImmOpc(), llvm::SuperRegClassIterator::getMask(), llvm::SelectionDAG::getMaskedLoad(), getMopState(), getMOVL(), llvm::SCEVNAryExpr::getNoWrapFlags(), getOffsetFromIndices(), llvm::MipsTargetLowering::getOpndList(), llvm::HvxSelector::getPairVT(), getParentPad(), getPermuteMask(), getPSHUFShuffleMask(), getReductionSDNode(), llvm::RegScavenger::getRegsAvailable(), getScatterNode(), llvm::AArch64RegisterInfo::getSEHRegNum(), llvm::ShuffleVectorInst::getShuffleMask(), getTargetConstantBitsFromNode(), llvm::ARCTargetLowering::getTargetNodeName(), getTargetShuffleAndZeroables(), llvm::rdf::PhysicalRegisterInfo::getTRI(), getUniformBase(), getUnpackh(), getUnpackl(), getUsefulBitsFromBFM(), getUsefulBitsFromOrWithShiftedReg(), getVectorSHLImm(), getX86MaskVec(), group2Shuffle(), HasConditionalBranch(), INITIALIZE_PASS(), llvm::mca::initializeUsedResources(), insertDAGNode(), insertInteger(), insertNoDuplicates(), insertVector(), inversePermutation(), is128BitLaneCrossingShuffleMask(), isBroadcastShuffle(), isCDisp8(), isConstant(), isConstantIntVector(), isCopy(), isCrossCopy(), llvm::HexagonTargetLowering::isCtlzFast(), isDefInSubRange(), isFloatingPointZero(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), isIdentityValue(), llvm::ShuffleVectorInst::isIdentityWithPadding(), llvm::isKnownNonEqual(), llvm::AArch64TargetLowering::isMaskAndCmp0FoldingBeneficial(), isMemOPCandidate(), isMulPowOf2(), isOpcWithIntImmediate(), llvm::PPCInstrInfo::isProfitableToUnpredicate(), isPromotedResultSafe(), llvm::ARMTargetLowering::isReadOnly(), isSETCCorConvertedSETCC(), llvm::isSplatValue(), llvm::SelectionDAG::isSplatValue(), llvm::ShuffleVectorInst::isValidOperands(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), isVectorPredicable(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), LowerAsSplatVectorLoad(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITREVERSE_XOP(), llvm::LegalizerHelper::lowerBswap(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORAsVariablePermute(), llvm::AArch64CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerEXTEND_VECTOR_INREG(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::AMDGPUTargetLowering::LowerFROUND64(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::LegalizerHelper::lowerInsert(), LowerINSERT_VECTOR_ELT_i1(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), LowerMGATHER(), LowerMLOAD(), lowerMSABitClearImm(), LowerMSCATTER(), LowerMSTORE(), lowerShuffleAsBlend(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsShift(), llvm::LegalizerHelper::lowerShuffleVector(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVectorINT_TO_FP(), llvm::SCEVWrapPredicate::maskFlags(), llvm::ScalarEvolution::maskFlags(), llvm::maskIsAllOneOrUndef(), llvm::maskIsAllZeroOrUndef(), maskMatters(), llvm::DwarfExpression::maskSubRegister(), llvm::CombinerHelper::matchCombineShuffleVector(), matchLogicBlend(), matchPairwiseShuffleMask(), matchRotate(), matchVectorSplittingReduction(), mayTailCallThisCC(), mayUseP9Setb(), numVectorEltsOrZero(), llvm::ShuffleVectorInst::operator new(), llvm::BitVector::operator<<=(), llvm::BitVector::operator>>=(), llvm::FeatureBitset::operator[](), llvm::BitVector::operator[](), llvm::AArch64InstrInfo::optimizeCondBranch(), optimizeLogicalImm(), parseGlobalValue(), performANDCombine(), PerformANDCombine(), performAtomicOp(), PerformBFICombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), PerformORCombineToBFI(), performSelectCombine(), PerformSHLSimplify(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSVEAndCombine(), llvm::LiveIntervals::print(), llvm::MachineOperand::print(), llvm::VPInterleaveRecipe::print(), llvm::VPWidenMemoryInstructionRecipe::print(), printBitField(), llvm::ARMInstPrinter::printMSRMaskOperand(), printSwizzleBitmask(), llvm::MachineOperand::printTargetFlags(), llvm::ARMInstPrinter::printThumbITMask(), llvm::ARMInstPrinter::printVPTMask(), llvm::AArch64_AM::processLogicalImmediate(), processUGT_ADDCST_ADD(), llvm::SimpleBitstreamCursor::Read(), llvm::AArch64TargetLowering::ReconstructShuffle(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), replaceAllUsesOfWithIn(), llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo(), llvm::SmallBitVector::reset(), llvm::BitVector::reset(), resolveZeroablesFromTargetShuffle(), llvm::mca::ResourceManager::ResourceManager(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), scalarizeExtractedBinop(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), selectI64Imm(), llvm::HvxSelector::selectShuffle(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::SmallBitVector::set(), llvm::BitVector::set(), llvm::APInt::setBit(), llvm::SmallBitVector::setBitsInMask(), llvm::BitVector::setBitsInMask(), llvm::SmallBitVector::setBitsNotInMask(), llvm::BitVector::setBitsNotInMask(), llvm::mca::ResourceManager::setCustomStrategy(), llvm::MachineInstr::setFlags(), llvm::Function::setIsMaterializable(), llvm::DwarfExpression::setSubRegisterPiece(), llvm::mca::Instruction::setUsedBuffers(), llvm::RISCVTargetLowering::shouldExpandShift(), shouldMergeGEPs(), shouldUseAndMask(), ShrinkLoadReplaceStoreWithStore(), SimplifyAndInst(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyDivRem(), simplifySelectWithFakeICmpEq(), simplifyShuffleOfShuffle(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), Status::Status(), stripModuloOnShift(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::TargetLowering::targetShrinkDemandedConstant(), toString(), truncateVectorWithPACK(), tryBuildVectorShuffle(), tryCombineCRC32(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), tryFormConcatFromShuffle(), llvm::AArch64_IMM::trySequenceOfOnes(), llvm::VPRecipeBuilder::tryToWidenMemory(), TypeSizeToSizeIndex(), llvm::AArch64_IMM::updateImm(), updateLiveIn(), upgradeMaskedCompare(), upgradeMaskedMove(), UpgradeMaskToInt(), upgradePMULDQ(), UpgradeX86AddSubSatIntrinsics(), upgradeX86ConcatShift(), upgradeX86Rotate(), llvm::mca::DefaultResourceStrategy::used(), vectorizeExtractedCast(), llvm::LiveInterval::verify(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitLShr(), visitORCommutative(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), llvm::VPInterleaveRecipe::VPInterleaveRecipe(), llvm::VPWidenMemoryInstructionRecipe::VPWidenMemoryInstructionRecipe(), llvm::LegalizerHelper::widenScalar(), write32AArch64Addr(), and llvm::write32AArch64Addr().
operator &()
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type> E llvm::BitmaskEnumDetail::operator& (E LHS, E RHS)
Definition at line 111 of file BitmaskEnum.h.
References E, and Underlying().
operator &=()
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type> E& llvm::BitmaskEnumDetail::operator&= (E & LHS, E RHS)
Definition at line 133 of file BitmaskEnum.h.
References E.
operator^()
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type> E llvm::BitmaskEnumDetail::operator^ (E LHS, E RHS)
Definition at line 117 of file BitmaskEnum.h.
References E, and Underlying().
operator^=()
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type> E& llvm::BitmaskEnumDetail::operator^= (E & LHS, E RHS)
Definition at line 140 of file BitmaskEnum.h.
References llvm::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE().
operator|()
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type> E llvm::BitmaskEnumDetail::operator| (E LHS, E RHS)
Definition at line 105 of file BitmaskEnum.h.
References E, and Underlying().
operator|=()
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type> E& llvm::BitmaskEnumDetail::operator|= (E & LHS, E RHS)
Definition at line 126 of file BitmaskEnum.h.
References E.
operator~()
template<typename E , typename = typename std::enable_if<is_bitmask_enum<E>::value>::type> E llvm::BitmaskEnumDetail::operator~ (E Val)
Definition at line 99 of file BitmaskEnum.h.
References E, and Underlying().
Underlying()
template<typename E > std::underlying_type<E>::type llvm::BitmaskEnumDetail::Underlying (E Val)
Check that Val is in range for E, and return Val cast to E's underlying type.
Definition at line 90 of file BitmaskEnum.h.
References assert(), and E.
Referenced by eliminateDeadStores(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray(), findInitTrampolineFromAlloca(), llvm::pdb::NativeTypeEnum::getBuiltinType(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), llvm::InstrProfReaderIndex< HashTableImpl >::InstrProfReaderIndex(), operator &(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::operator[](), operator^(), operator|(), operator~(), and llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::populateRemappings().