LLVM: llvm::lowertypetests Namespace Reference
llvm::lowertypetests Namespace Reference
Classes
struct BitSetBuilder
struct BitSetInfo
struct ByteArrayBuilder
This class is used to build a byte array containing overlapping bit sets.
struct GlobalLayoutBuilder
This class implements a layout algorithm for globals referenced by bit sets that tries to keep members of small bit sets together.
Functions
bool isJumpTableCanonical (Function *F)
Function Documentation
isJumpTableCanonical()
bool llvm::lowertypetests::isJumpTableCanonical (Function * F)
Definition at line 234 of file LowerTypeTests.cpp.
References llvm::lowertypetests::BitSetInfo::Bits, llvm::lowertypetests::BitSetInfo::BitSize, llvm::Module::getModuleFlag(), llvm::GlobalValue::getParent(), llvm::Function::hasFnAttribute(), and llvm::GlobalValue::isDeclarationForLinker().
Referenced by llvm::lowertypetests::ByteArrayBuilder::ByteArrayBuilder(), and isKnownTypeIdMember().