LLVM: llvm::parallel Namespace Reference
llvm::parallel Namespace Reference
Namespaces
detail
Classes
struct is_execution_policy
struct parallel_execution_policy
struct sequential_execution_policy
Functions
template<class Policy , class RandomAccessIterator , class Comparator = detail::DefComparator<RandomAccessIterator>>
void sort (Policy policy, RandomAccessIterator Start, RandomAccessIterator End, const Comparator &Comp=Comparator())
template<class Policy , class IterTy , class FuncTy >
void for_each (Policy policy, IterTy Begin, IterTy End, FuncTy Fn)
template<class Policy , class IndexTy , class FuncTy >
void for_each_n (Policy policy, IndexTy Begin, IndexTy End, FuncTy Fn)
template<class RandomAccessIterator , class Comparator = detail::DefComparator<RandomAccessIterator>>
void sort (parallel_execution_policy policy, RandomAccessIterator Start, RandomAccessIterator End, const Comparator &Comp=Comparator())
template<class IterTy , class FuncTy >
void for_each (parallel_execution_policy policy, IterTy Begin, IterTy End, FuncTy Fn)
template<class IndexTy , class FuncTy >
void for_each_n (parallel_execution_policy policy, IndexTy Begin, IndexTy End, FuncTy Fn)
Variables
constexpr sequential_execution_policy seq {}
constexpr parallel_execution_policy par {}
Function Documentation
for_each() [1/2]
template<class Policy , class IterTy , class FuncTy > void llvm::parallel::for_each (Policy policy, IterTy Begin, IterTy End, FuncTy Fn)
Definition at line 183 of file Parallel.h.
References for_each().
for_each() [2/2]
template<class IterTy , class FuncTy > void llvm::parallel::for_each (parallel_execution_policy policy, IterTy Begin, IterTy End, FuncTy Fn)
Definition at line 208 of file Parallel.h.
References llvm::parallel::detail::parallel_for_each().
Referenced by for_each().
for_each_n() [1/2]
template<class Policy , class IndexTy , class FuncTy > void llvm::parallel::for_each_n (Policy policy, IndexTy Begin, IndexTy End, FuncTy Fn)
Definition at line 190 of file Parallel.h.
References I.
for_each_n() [2/2]
template<class IndexTy , class FuncTy > void llvm::parallel::for_each_n (parallel_execution_policy policy, IndexTy Begin, IndexTy End, FuncTy Fn)
Definition at line 214 of file Parallel.h.
References llvm::parallel::detail::parallel_for_each_n().
sort() [1/2]
template<class Policy , class RandomAccessIterator , class Comparator = detail::DefComparator<RandomAccessIterator>> void llvm::parallel::sort (Policy policy, RandomAccessIterator Start, RandomAccessIterator End, const Comparator & Comp = Comparator())
Definition at line 175 of file Parallel.h.
sort() [2/2]
template<class RandomAccessIterator , class Comparator = detail::DefComparator<RandomAccessIterator>> void llvm::parallel::sort (parallel_execution_policy policy, RandomAccessIterator Start, RandomAccessIterator End, const Comparator & Comp = Comparator())
Definition at line 202 of file Parallel.h.
References llvm::parallel::detail::parallel_sort().
Variable Documentation
par
constexpr parallel_execution_policy llvm::parallel::par {}
Definition at line 34 of file Parallel.h.
seq
constexpr sequential_execution_policy llvm::parallel::seq {}
Definition at line 33 of file Parallel.h.