LLVM: llvm::AArch64SysReg Namespace Reference
llvm::AArch64SysReg Namespace Reference
Classes
struct SysReg
Functions
const SysReg * lookupSysRegByName (StringRef)
const SysReg * lookupSysRegByEncoding (uint16_t)
uint32_t parseGenericRegister (StringRef Name)
std::string genericRegisterString (uint32_t Bits)
Function Documentation
genericRegisterString()
std::string llvm::AArch64SysReg::genericRegisterString (uint32_t Bits)
Definition at line 147 of file AArch64BaseInfo.cpp.
References assert(), and llvm::utostr().
Referenced by llvm::AArch64InstPrinter::printMRSSystemRegister(), and llvm::AArch64InstPrinter::printMSRSystemRegister().
lookupSysRegByEncoding()
const SysReg* llvm::AArch64SysReg::lookupSysRegByEncoding (uint16_t)
Referenced by matchRegisterNameHelper(), llvm::RISCVInstPrinter::printCSRSystemRegister(), llvm::AArch64InstPrinter::printMRSSystemRegister(), and llvm::AArch64InstPrinter::printMSRSystemRegister().
lookupSysRegByName()
const SysReg* llvm::AArch64SysReg::lookupSysRegByName (StringRef)
Referenced by emitReadCycleWidePseudo(), getIntOperandFromRegisterString(), matchRegisterNameHelper(), and setRequiredFeatureString().
parseGenericRegister()
uint32_t llvm::AArch64SysReg::parseGenericRegister (StringRef Name)
Definition at line 126 of file AArch64BaseInfo.cpp.
References llvm::tgtok::Bits, llvm::Regex::match(), and llvm::StringRef::upper().
Referenced by getIntOperandFromRegisterString(), and setRequiredFeatureString().