LLVM: llvm::SISched Namespace Reference
llvm::SISched Namespace Reference
Functions
static bool tryLess (int TryVal, int CandVal, SISchedulerCandidate &TryCand, SISchedulerCandidate &Cand, SIScheduleCandReason Reason)
static bool tryGreater (int TryVal, int CandVal, SISchedulerCandidate &TryCand, SISchedulerCandidate &Cand, SIScheduleCandReason Reason)
Function Documentation
tryGreater()
static bool llvm::SISched::tryGreater (int TryVal, int CandVal, SISchedulerCandidate & TryCand, SISchedulerCandidate & Cand, SIScheduleCandReason Reason) static
Definition at line 176 of file SIMachineScheduler.cpp.
References llvm::SISchedulerCandidate::Reason, and llvm::SISchedulerCandidate::setRepeat().
Referenced by llvm::SIScheduleBlock::addUnit(), and llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().
tryLess()
static bool llvm::SISched::tryLess (int TryVal, int CandVal, SISchedulerCandidate & TryCand, SISchedulerCandidate & Cand, SIScheduleCandReason Reason) static
Definition at line 159 of file SIMachineScheduler.cpp.
References llvm::SISchedulerCandidate::Reason, and llvm::SISchedulerCandidate::setRepeat().
Referenced by llvm::SIScheduleBlock::addUnit(), and llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler().