LLVM: llvm::adl_detail Namespace Reference
llvm::adl_detail Namespace Reference
Functions
template<typename ContainerTy >
auto adl_begin (ContainerTy &&container) -> decltype(begin(std::forward< ContainerTy >(container)))
template<typename ContainerTy >
auto adl_end (ContainerTy &&container) -> decltype(end(std::forward< ContainerTy >(container)))
template<typename T >
void adl_swap (T &&lhs, T &&rhs) noexcept(noexcept(swap(std::declval< T >(), std::declval< T >())))
Function Documentation
adl_begin()
template<typename ContainerTy > auto llvm::adl_detail::adl_begin (ContainerTy && container) -> decltype(begin(std::forward<ContainerTy>(container)))
Definition at line 149 of file STLExtras.h.
References llvm::sys::path::begin(), and llvm::sys::path::end().
Referenced by llvm::adl_begin().
adl_end()
template<typename ContainerTy > auto llvm::adl_detail::adl_end (ContainerTy && container) -> decltype(end(std::forward<ContainerTy>(container)))
Definition at line 157 of file STLExtras.h.
References llvm::sys::path::end(), and std::swap().
Referenced by llvm::adl_end().
adl_swap()
template<typename T > void llvm::adl_detail::adl_swap (T && lhs, T && rhs) noexcept
Definition at line 165 of file STLExtras.h.
References std::swap().
Referenced by llvm::adl_swap().