LLVM: llvm::X86_MC Namespace Reference
llvm::X86_MC Namespace Reference
Classes
class X86MCInstrAnalysis
Functions
static std::vector< std::pair< uint64_t, uint64_t > > findX86PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents, uint64_t GotPltSectionVA)
static std::vector< std::pair< uint64_t, uint64_t > > findX86_64PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents)
std::string ParseX86Triple (const Triple &TT)
unsigned getDwarfRegFlavour (const Triple &TT, bool isEH)
void initLLVMToSEHAndCVRegMapping (MCRegisterInfo *MRI)
bool hasLockPrefix (const MCInst &MI)
Returns true if this instruction has a LOCK prefix.
MCSubtargetInfo * createX86MCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
Create a X86 MCSubtargetInfo instance.
Function Documentation
createX86MCSubtargetInfo()
MCSubtargetInfo * llvm::X86_MC::createX86MCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS)
Create a X86 MCSubtargetInfo instance.
This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 290 of file X86MCTargetDesc.cpp.
References assert(), llvm::StringRef::empty(), llvm::X86AS::FS, and ParseX86Triple().
Referenced by LLVMInitializeX86TargetMC().
findX86_64PltEntries()
static std::vector<std::pair<uint64_t, uint64_t> > llvm::X86_MC::findX86_64PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents) static
Definition at line 491 of file X86MCTargetDesc.cpp.
Referenced by llvm::X86_MC::X86MCInstrAnalysis::findPltEntries().
findX86PltEntries()
static std::vector<std::pair<uint64_t, uint64_t> > llvm::X86_MC::findX86PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents, uint64_t GotPltSectionVA) static
Definition at line 465 of file X86MCTargetDesc.cpp.
Referenced by llvm::X86_MC::X86MCInstrAnalysis::findPltEntries().
getDwarfRegFlavour()
unsigned llvm::X86_MC::getDwarfRegFlavour (const Triple & TT, bool isEH)
Definition at line 61 of file X86MCTargetDesc.cpp.
References llvm::Triple::getArch(), llvm::Triple::isOSCygMing(), llvm::Triple::isOSDarwin(), llvm::DWARFFlavour::X86_32_DarwinEH, llvm::DWARFFlavour::X86_32_Generic, llvm::DWARFFlavour::X86_64, and llvm::Triple::x86_64.
Referenced by createX86MCRegisterInfo().
hasLockPrefix()
bool llvm::X86_MC::hasLockPrefix (const MCInst & MI)
Returns true if this instruction has a LOCK prefix.
Definition at line 73 of file X86MCTargetDesc.cpp.
References llvm::MCInst::getFlags(), and llvm::X86::IP_HAS_LOCK.
initLLVMToSEHAndCVRegMapping()
void llvm::X86_MC::initLLVMToSEHAndCVRegMapping (MCRegisterInfo * MRI)
Definition at line 77 of file X86MCTargetDesc.cpp.
References llvm::AArch64CC::AL, llvm::array_lengthof(), llvm::ARCISD::BL, llvm::N86::EAX, llvm::N86::EBP, llvm::N86::EBX, llvm::N86::ECX, llvm::N86::EDI, llvm::N86::EDX, llvm::N86::ESI, llvm::N86::ESP, llvm::MCRegisterInfo::getEncodingValue(), I, llvm::MCRegisterInfo::mapLLVMRegToCVReg(), llvm::MCRegisterInfo::mapLLVMRegToSEHReg(), Reg, and SI.
Referenced by createX86MCRegisterInfo(), and llvm::X86RegisterInfo::X86RegisterInfo().
ParseX86Triple()
std::string llvm::X86_MC::ParseX86Triple (const Triple & TT)
Definition at line 49 of file X86MCTargetDesc.cpp.
References llvm::Triple::CODE16, llvm::X86AS::FS, llvm::Triple::getArch(), llvm::Triple::getEnvironment(), and llvm::Triple::x86_64.
Referenced by createX86MCSubtargetInfo().