LLVM: llvm::sampleprof Namespace Reference
llvm::sampleprof Namespace Reference
Classes
class FunctionSamples
Representation of the samples collected for a function.
struct LineLocation
Represents the relative location of an instruction.
class ProfileSymbolList
ProfileSymbolList records the list of function symbols shown up in the binary used to generate the profile.
class SampleProfileReader
Sample-based profile reader.
class SampleProfileReaderBinary
class SampleProfileReaderCompactBinary
class SampleProfileReaderExtBinary
class SampleProfileReaderExtBinaryBase
SampleProfileReaderExtBinaryBase/SampleProfileWriterExtBinaryBase defines the basic structure of the extensible binary format.
class SampleProfileReaderGCC
class SampleProfileReaderItaniumRemapper
SampleProfileReaderItaniumRemapper remaps the profile data from a sample profile data reader, by applying a provided set of equivalences between components of the symbol names in the profile.
class SampleProfileReaderRawBinary
class SampleProfileReaderText
class SampleProfileWriter
Sample-based profile writer. Base class.
class SampleProfileWriterBinary
Sample-based profile writer (binary format).
class SampleProfileWriterCompactBinary
class SampleProfileWriterExtBinary
class SampleProfileWriterExtBinaryBase
class SampleProfileWriterRawBinary
class SampleProfileWriterText
Sample-based profile writer (text format).
class SampleRecord
Representation of a single sample record.
class SampleSorter
Sort a LocationT->SampleT map by LocationT.
struct SecHdrTableEntry
Typedefs
using BodySampleMap = std::map< LineLocation, SampleRecord >
using FunctionSamplesMap = std::map< std::string, FunctionSamples, std::less<> >
using CallsiteSampleMap = std::map< LineLocation, FunctionSamplesMap >
using InlineCallStack = SmallVector< FunctionSamples *, 10 >
Enumerations
enum SampleProfileFormat {
SPF_None = 0, SPF_Text = 0x1, SPF_Compact_Binary = 0x2, SPF_GCC = 0x3,
SPF_Ext_Binary = 0x4, SPF_Binary = 0xff
}
enum SecType {
SecInValid = 0, SecProfSummary = 1, SecNameTable = 2, SecProfileSymbolList = 3,
SecFuncOffsetTable = 4, SecFuncProfileFirst = 32, SecLBRProfile = SecFuncProfileFirst
}
enum SecFlags { SecFlagInValid = 0, SecFlagCompress = (1 << 0) }
enum HistType {
HIST_TYPE_INTERVAL, HIST_TYPE_POW2, HIST_TYPE_SINGLE_VALUE, HIST_TYPE_CONST_DELTA,
HIST_TYPE_INDIR_CALL, HIST_TYPE_AVERAGE, HIST_TYPE_IOR, HIST_TYPE_INDIR_CALL_TOPN
}
Functions
static uint64_t SPMagic (SampleProfileFormat Format=SPF_Binary)
static StringRef getRepInFormat (StringRef Name, SampleProfileFormat Format, std::string &GUIDBuf)
static uint64_t SPVersion ()
static std::string getSecName (SecType Type)
static void addSecFlags (SecHdrTableEntry &Entry, uint64_t Flags)
static void removeSecFlags (SecHdrTableEntry &Entry, uint64_t Flags)
static bool hasSecFlag (SecHdrTableEntry &Entry, SecFlags Flag)
raw_ostream & operator<< (raw_ostream &OS, const LineLocation &Loc)
raw_ostream & operator<< (raw_ostream &OS, const SampleRecord &Sample)
raw_ostream & operator<< (raw_ostream &OS, const FunctionSamples &FS)
Typedef Documentation
BodySampleMap
using llvm::sampleprof::BodySampleMap = typedef std::map<LineLocation, SampleRecord>
Definition at line 289 of file SampleProf.h.
CallsiteSampleMap
using llvm::sampleprof::CallsiteSampleMap = typedef std::map<LineLocation, FunctionSamplesMap>
Definition at line 293 of file SampleProf.h.
FunctionSamplesMap
using llvm::sampleprof::FunctionSamplesMap = typedef std::map<std::string, FunctionSamples, std::less<> >
Definition at line 292 of file SampleProf.h.
InlineCallStack
using llvm::sampleprof::InlineCallStack = typedef SmallVector<FunctionSamples *, 10>
Definition at line 676 of file SampleProfReader.h.
Enumeration Type Documentation
HistType
enum llvm::sampleprof::HistType
Enumerator
HIST_TYPE_INTERVAL
HIST_TYPE_POW2
HIST_TYPE_SINGLE_VALUE
HIST_TYPE_CONST_DELTA
HIST_TYPE_INDIR_CALL
HIST_TYPE_AVERAGE
HIST_TYPE_IOR
HIST_TYPE_INDIR_CALL_TOPN
Definition at line 680 of file SampleProfReader.h.
SampleProfileFormat
enum llvm::sampleprof::SampleProfileFormat
Enumerator
SPF_None
SPF_Text
SPF_Compact_Binary
SPF_GCC
SPF_Ext_Binary
SPF_Binary
Definition at line 87 of file SampleProf.h.
SecFlags
enum llvm::sampleprof::SecFlags
Enumerator
SecFlagInValid
SecFlagCompress
Definition at line 156 of file SampleProf.h.
SecType
enum llvm::sampleprof::SecType
Enumerator
SecInValid
SecProfSummary
SecNameTable
SecProfileSymbolList
SecFuncOffsetTable
SecFuncProfileFirst
SecLBRProfile
Definition at line 118 of file SampleProf.h.
Function Documentation
addSecFlags()
static void llvm::sampleprof::addSecFlags (SecHdrTableEntry & Entry, uint64_t Flags) inline static
Definition at line 158 of file SampleProf.h.
References llvm::sampleprof::SecHdrTableEntry::Flags.
Referenced by llvm::sampleprof::SampleProfileWriterExtBinaryBase::setToCompressAllSections(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::setToCompressSection().
getRepInFormat()
static StringRef llvm::sampleprof::getRepInFormat (StringRef Name, SampleProfileFormat Format, std::string & GUIDBuf) inline static
Definition at line 104 of file SampleProf.h.
References llvm::StringRef::empty(), llvm::GlobalValue::getGUID(), Name, SPF_Compact_Binary, and llvm::to_string().
Referenced by llvm::sampleprof::FunctionSamples::findFunctionSamplesAt(), llvm::sampleprof::SampleProfileReader::getOrCreateSamplesFor(), and llvm::sampleprof::SampleProfileReader::getSamplesFor().
getSecName()
static std::string llvm::sampleprof::getSecName (SecType Type) inline static
Definition at line 129 of file SampleProf.h.
References llvm_unreachable, SecFuncOffsetTable, SecInValid, SecLBRProfile, SecNameTable, SecProfileSymbolList, and SecProfSummary.
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::dumpSectionInfo().
hasSecFlag()
static bool llvm::sampleprof::hasSecFlag (SecHdrTableEntry & Entry, SecFlags Flag) inline static
Definition at line 166 of file SampleProf.h.
References llvm::sampleprof::SecHdrTableEntry::Flags.
Referenced by llvm::sampleprof::SampleProfileWriterExtBinaryBase::addNewSection(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::markSectionStart(), and llvm::sampleprof::SampleProfileReaderExtBinaryBase::readImpl().
operator<<() [1/3]
raw_ostream & llvm::sampleprof::operator<< (raw_ostream & OS, const LineLocation & Loc)
Definition at line 96 of file SampleProf.cpp.
References llvm::sampleprof::LineLocation::print().
operator<<() [2/3]
raw_ostream & llvm::sampleprof::operator<< (raw_ostream & OS, const SampleRecord & Sample)
Definition at line 121 of file SampleProf.cpp.
References llvm::sampleprof::SampleRecord::print().
operator<<() [3/3]
raw_ostream & llvm::sampleprof::operator<< (raw_ostream & OS, const FunctionSamples & FS)
Definition at line 165 of file SampleProf.cpp.
References llvm::sampleprof::FunctionSamples::print().
removeSecFlags()
static void llvm::sampleprof::removeSecFlags (SecHdrTableEntry & Entry, uint64_t Flags) inline static
Definition at line 162 of file SampleProf.h.
References llvm::sampleprof::SecHdrTableEntry::Flags.
SPMagic()
static uint64_t llvm::sampleprof::SPMagic (SampleProfileFormat Format = SPF_Binary) inline static
Definition at line 96 of file SampleProf.h.
References llvm::Format.
Referenced by llvm::sampleprof::SampleProfileReaderRawBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderExtBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderCompactBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderCompactBinary::readImpl(), and llvm::sampleprof::SampleProfileWriterBinary::writeMagicIdent().
SPVersion()
static uint64_t llvm::sampleprof::SPVersion () inline static
Definition at line 113 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileReaderBinary::readMagicIdent(), and llvm::sampleprof::SampleProfileWriterBinary::writeMagicIdent().