LLVM: adjust::ldi Namespace Reference
adjust::ldi Namespace Reference
Fixups relating to the LDI instruction.
Functions
void fixup (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
Adjusts a value to fix up the immediate of an LDI Rd, K instruction.
void neg (uint64_t &Value)
void lo8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
void hi8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
void hh8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
void ms8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
Detailed Description
Fixups relating to the LDI instruction.
Function Documentation
fixup()
void adjust::ldi::fixup (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr)
Adjusts a value to fix up the immediate of an LDI Rd, K instruction.
Resolves to: 0000 KKKK 0000 KKKK Offset of 0 (so the result isn't left-shifted before application).
Definition at line 192 of file AVRAsmBackend.cpp.
Referenced by llvm::AVRAsmBackend::adjustFixupValue(), HasConditionalBranch(), hh8(), hi8(), lo8(), and ms8().
hh8()
void adjust::ldi::hh8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr)
Definition at line 214 of file AVRAsmBackend.cpp.
References fixup().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
hi8()
void adjust::ldi::hi8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr)
Definition at line 208 of file AVRAsmBackend.cpp.
References fixup().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
lo8()
void adjust::ldi::lo8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr)
Definition at line 202 of file AVRAsmBackend.cpp.
References fixup().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
ms8()
void adjust::ldi::ms8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr)
Definition at line 220 of file AVRAsmBackend.cpp.
References fixup().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
neg()
void adjust::ldi::neg (uint64_t & Value)
Definition at line 200 of file AVRAsmBackend.cpp.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().