LLVM: llvm::fuzzerop Namespace Reference
llvm::fuzzerop Namespace Reference
Classes
struct OpDescriptor
A description of some operation we can build while fuzzing IR.
class SourcePred
A matcher/generator for finding suitable values for the next source in an operation's partially completed argument list.
Functions
static SourcePred onlyType (Type *Only)
static SourcePred anyType ()
static SourcePred anyIntType ()
static SourcePred anyFloatType ()
static SourcePred anyPtrType ()
static SourcePred sizedPtrType ()
static SourcePred anyAggregateType ()
static SourcePred anyVectorType ()
static SourcePred matchFirstType ()
Match values that have the same type as the first source.
static SourcePred matchScalarOfFirstType ()
Match values that have the first source's scalar type.
void makeConstantsWithType (Type *T, std::vector< Constant *> &Cs)
std::vector< Constant * > makeConstantsWithType (Type *T)
OpDescriptor binOpDescriptor (unsigned Weight, Instruction::BinaryOps Op)
Descriptors for individual operations.
OpDescriptor cmpOpDescriptor (unsigned Weight, Instruction::OtherOps CmpOp, CmpInst::Predicate Pred)
OpDescriptor splitBlockDescriptor (unsigned Weight)
OpDescriptor gepDescriptor (unsigned Weight)
OpDescriptor extractValueDescriptor (unsigned Weight)
OpDescriptor insertValueDescriptor (unsigned Weight)
OpDescriptor extractElementDescriptor (unsigned Weight)
OpDescriptor insertElementDescriptor (unsigned Weight)
OpDescriptor shuffleVectorDescriptor (unsigned Weight)
Function Documentation
anyAggregateType()
static SourcePred llvm::fuzzerop::anyAggregateType () inline static
Definition at line 164 of file OpDescriptor.h.
References Find(), and llvm::None.
Referenced by extractValueDescriptor(), and insertValueDescriptor().
anyFloatType()
static SourcePred llvm::fuzzerop::anyFloatType () inline static
Definition at line 121 of file OpDescriptor.h.
References llvm::None.
Referenced by binOpDescriptor(), and cmpOpDescriptor().
anyIntType()
static SourcePred llvm::fuzzerop::anyIntType () inline static
Definition at line 113 of file OpDescriptor.h.
References llvm::None.
Referenced by binOpDescriptor(), cmpOpDescriptor(), extractElementDescriptor(), gepDescriptor(), and insertElementDescriptor().
anyPtrType()
static SourcePred llvm::fuzzerop::anyPtrType () inline static
Definition at line 129 of file OpDescriptor.h.
References llvm::UndefValue::get(), and llvm::PointerType::getUnqual().
anyType()
static SourcePred llvm::fuzzerop::anyType () inline static
Definition at line 105 of file OpDescriptor.h.
References llvm::None.
Referenced by llvm::RandomIRBuilder::findOrCreateSource().
anyVectorType()
static SourcePred llvm::fuzzerop::anyVectorType () inline static
Definition at line 182 of file OpDescriptor.h.
References llvm::None.
Referenced by extractElementDescriptor(), insertElementDescriptor(), and shuffleVectorDescriptor().
binOpDescriptor()
OpDescriptor llvm::fuzzerop::binOpDescriptor (unsigned Weight, Instruction::BinaryOps Op)
Descriptors for individual operations.
Definition at line 91 of file Operations.cpp.
References llvm::MCID::Add, anyFloatType(), anyIntType(), llvm::BinaryOperator::Create(), llvm_unreachable, and matchFirstType().
Referenced by llvm::describeFuzzerFloatOps(), and llvm::describeFuzzerIntOps().
cmpOpDescriptor()
OpDescriptor llvm::fuzzerop::cmpOpDescriptor (unsigned Weight, Instruction::OtherOps CmpOp, CmpInst::Predicate Pred)
Definition at line 123 of file Operations.cpp.
References anyFloatType(), anyIntType(), llvm::CmpInst::Create(), llvm_unreachable, and matchFirstType().
Referenced by llvm::describeFuzzerFloatOps(), and llvm::describeFuzzerIntOps().
extractElementDescriptor()
OpDescriptor llvm::fuzzerop::extractElementDescriptor (unsigned Weight)
Definition at line 278 of file Operations.cpp.
References anyIntType(), anyVectorType(), and llvm::ExtractElementInst::Create().
Referenced by llvm::describeFuzzerVectorOps().
extractValueDescriptor()
OpDescriptor llvm::fuzzerop::extractValueDescriptor (unsigned Weight)
Definition at line 211 of file Operations.cpp.
References anyAggregateType(), llvm::ExtractValueInst::Create(), and validExtractValueIndex().
Referenced by llvm::describeFuzzerAggregateOps().
gepDescriptor()
OpDescriptor llvm::fuzzerop::gepDescriptor (unsigned Weight)
Definition at line 170 of file Operations.cpp.
References anyIntType(), buildGEP(), llvm::GetElementPtrInst::Create(), llvm::makeArrayRef(), and sizedPtrType().
Referenced by llvm::describeFuzzerPointerOps().
insertElementDescriptor()
OpDescriptor llvm::fuzzerop::insertElementDescriptor (unsigned Weight)
Definition at line 286 of file Operations.cpp.
References anyIntType(), anyVectorType(), llvm::InsertElementInst::Create(), and matchScalarOfFirstType().
Referenced by llvm::describeFuzzerVectorOps().
insertValueDescriptor()
OpDescriptor llvm::fuzzerop::insertValueDescriptor (unsigned Weight)
Definition at line 266 of file Operations.cpp.
References anyAggregateType(), llvm::InsertValueInst::Create(), matchScalarInAggregate(), and validInsertValueIndex().
Referenced by llvm::describeFuzzerAggregateOps().
makeConstantsWithType() [1/2]
void llvm::fuzzerop::makeConstantsWithType (Type * T, std::vector< Constant *> & Cs)
Populate a small list of potentially interesting constants of a given type.
Definition at line 15 of file OpDescriptor.cpp.
References llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::UndefValue::get(), llvm::Type::getContext(), llvm::Type::getFltSemantics(), llvm::APFloat::getLargest(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::APInt::getOneBitSet(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::APFloat::getSmallest(), llvm::APFloat::getZero(), llvm::Type::isFloatingPointTy(), and llvm::RISCVFenceField::W.
Referenced by makeConstantsWithType(), matchFirstType(), matchScalarInAggregate(), matchScalarOfFirstType(), onlyType(), and llvm::fuzzerop::SourcePred::SourcePred().
makeConstantsWithType() [2/2]
std::vector< Constant * > llvm::fuzzerop::makeConstantsWithType (Type * T)
Definition at line 33 of file OpDescriptor.cpp.
References makeConstantsWithType().
matchFirstType()
static SourcePred llvm::fuzzerop::matchFirstType () inline static
Match values that have the same type as the first source.
Definition at line 194 of file OpDescriptor.h.
References assert(), llvm::ArrayRef< T >::empty(), getType(), and makeConstantsWithType().
Referenced by binOpDescriptor(), cmpOpDescriptor(), llvm::RandomIRBuilder::newSink(), and shuffleVectorDescriptor().
matchScalarOfFirstType()
static SourcePred llvm::fuzzerop::matchScalarOfFirstType () inline static
Match values that have the first source's scalar type.
Definition at line 207 of file OpDescriptor.h.
References assert(), llvm::ArrayRef< T >::empty(), getType(), and makeConstantsWithType().
Referenced by insertElementDescriptor().
onlyType()
static SourcePred llvm::fuzzerop::onlyType (Type * Only) inline static
Definition at line 95 of file OpDescriptor.h.
References makeConstantsWithType().
Referenced by llvm::InstDeleterIRStrategy::mutate().
shuffleVectorDescriptor()
OpDescriptor llvm::fuzzerop::shuffleVectorDescriptor (unsigned Weight)
Definition at line 311 of file Operations.cpp.
References anyVectorType(), matchFirstType(), and validShuffleVectorIndex().
Referenced by llvm::describeFuzzerVectorOps().
sizedPtrType()
static SourcePred llvm::fuzzerop::sizedPtrType () inline static
Definition at line 143 of file OpDescriptor.h.
References llvm::UndefValue::get(), llvm::PointerType::getUnqual(), and llvm::Type::isSized().
Referenced by gepDescriptor().
splitBlockDescriptor()
OpDescriptor llvm::fuzzerop::splitBlockDescriptor (unsigned Weight)
Definition at line 140 of file Operations.cpp.
References llvm::BranchInst::Create(), llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::BasicBlock::isEHPad(), llvm::None, llvm::BasicBlock::phis(), and llvm::BasicBlock::splitBasicBlock().
Referenced by llvm::describeFuzzerControlFlowOps().