LLVM: llvm::object Namespace Reference
llvm::object Namespace Reference
Classes
class Archive
class ArchiveMemberHeader
class BaseRelocRef
class BasicSymbolRef
This is a value type class that represents a single symbol in the list of symbols in the object file.
class Binary
class BinaryError
Base class for all errors indicating malformed binary files.
class BindRebaseSegInfo
struct coff_aux_bf_and_ef_symbol
struct coff_aux_clr_token
struct coff_aux_function_definition
struct coff_aux_section_definition
struct coff_aux_weak_external
struct coff_base_reloc_block_entry
struct coff_base_reloc_block_header
struct coff_bigobj_file_header
struct coff_file_header
struct coff_import_directory_table_entry
struct coff_import_header
struct coff_load_config_code_integrity
struct coff_load_configuration32
32-bit load config (IMAGE_LOAD_CONFIG_DIRECTORY32)
struct coff_load_configuration64
64-bit load config (IMAGE_LOAD_CONFIG_DIRECTORY64)
struct coff_relocation
struct coff_resource_data_entry
struct coff_resource_dir_entry
struct coff_resource_dir_table
struct coff_runtime_function_x64
struct coff_section
struct coff_symbol
struct coff_symbol_generic
struct coff_tls_directory
class COFFImportFile
struct COFFModuleDefinition
class COFFObjectFile
struct COFFShortExport
class COFFSymbolRef
class content_iterator
struct data_directory
union DataRefImpl
struct debug_directory
struct debug_h_header
class Decompressor
Decompressor helps to handle decompression of compressed sections.
struct delay_import_directory_table_entry
class DelayImportDirectoryEntryRef
class DiceRef
DiceRef - This is a value type class that represents a single data in code entry in the table in a Mach-O object file.
struct dos_header
The DOS compatible header at the front of all PE/COFF executables.
struct Elf_CGProfile_Impl
struct Elf_Chdr_Impl
struct Elf_Chdr_Impl< ELFType< TargetEndianness, false > >
struct Elf_Chdr_Impl< ELFType< TargetEndianness, true > >
struct Elf_Dyn_Base
Elf_Dyn_Base: This structure matches the form of entries in the dynamic table section (.dynamic) look like.
struct Elf_Dyn_Base< ELFType< TargetEndianness, false > >
struct Elf_Dyn_Base< ELFType< TargetEndianness, true > >
struct Elf_Dyn_Impl
Elf_Dyn_Impl: This inherits from Elf_Dyn_Base, adding getters.
struct Elf_Ehdr_Impl
struct Elf_GnuHash_Impl
struct Elf_Hash_Impl
struct Elf_Mips_ABIFlags
struct Elf_Mips_Options
struct Elf_Mips_RegInfo
struct Elf_Mips_RegInfo< ELFType< TargetEndianness, false > >
struct Elf_Mips_RegInfo< ELFType< TargetEndianness, true > >
struct Elf_Nhdr_Impl
Note header.
class Elf_Note_Impl
An ELF note.
class Elf_Note_Iterator_Impl
struct Elf_Phdr_Impl
struct Elf_Phdr_Impl< ELFType< TargetEndianness, false > >
struct Elf_Phdr_Impl< ELFType< TargetEndianness, true > >
struct Elf_Rel_Impl
struct Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >
struct Elf_Rel_Impl< ELFType< TargetEndianness, false >, true >
struct Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >
struct Elf_Rel_Impl< ELFType< TargetEndianness, true >, true >
class elf_relocation_iterator
class elf_section_iterator
struct Elf_Shdr_Base
struct Elf_Shdr_Base< ELFType< TargetEndianness, false > >
struct Elf_Shdr_Base< ELFType< TargetEndianness, true > >
struct Elf_Shdr_Impl
struct Elf_Sym_Base
struct Elf_Sym_Base< ELFType< TargetEndianness, false > >
struct Elf_Sym_Base< ELFType< TargetEndianness, true > >
struct Elf_Sym_Impl
class elf_symbol_iterator
struct Elf_Verdaux_Impl
Elf_Verdaux: This is the structure of auxiliary data in the SHT_GNU_verdef section (.gnu.version_d).
struct Elf_Verdef_Impl
Elf_Verdef: This is the structure of entries in the SHT_GNU_verdef section (.gnu.version_d).
struct Elf_Vernaux_Impl
Elf_Vernaux: This is the structure of auxiliary data in SHT_GNU_verneed section (.gnu.version_r).
struct Elf_Verneed_Impl
Elf_Verneed: This is the structure of entries in the SHT_GNU_verneed section (.gnu.version_r).
struct Elf_Versym_Impl
Elf_Versym: This is the structure of entries in the SHT_GNU_versym section (.gnu.version).
class ELFFile
class ELFObjectFile
class ELFObjectFileBase
class ELFRelocationRef
class ELFSectionRef
class ELFSymbolRef
struct ELFType
class EmptyResError
union export_address_table_entry
struct export_directory_table_entry
class ExportDirectoryEntryRef
class ExportEntry
ExportEntry encapsulates the current-state-of-the-walk used when doing a non-recursive walk of the trie data structure.
struct FpoData
class GenericBinaryError
Generic binary error.
struct import_lookup_table_entry
class ImportDirectoryEntryRef
class ImportedSymbolRef
class IRObjectFile
struct IRSymtabFile
The contents of a bitcode file and its irsymtab.
class Lexer
class MachOBindEntry
MachOBindEntry encapsulates the current state in the decompression of binding opcodes.
class MachOObjectFile
class MachORebaseEntry
MachORebaseEntry encapsulates the current state in the decompression of rebasing opcodes.
class MachOUniversalBinary
class MinidumpFile
A class providing access to the contents of a minidump file.
class ObjectFile
This class is the base class for all object file types.
class OwningBinary
class Parser
struct pe32_header
The 32-bit PE header that follows the COFF header.
struct pe32plus_header
The 64-bit PE header that follows the COFF header.
class RelocationRef
This is a value type class that represents a single relocation in the list of relocations in the object file.
class ResourceEntryRef
class ResourceSectionRef
struct SectionedAddress
class SectionRef
This is a value type class that represents a single section in the list of sections in the object file.
struct StringTableOffset
class symbol_iterator
class SymbolicFile
class SymbolRef
This is a value type class that represents a single symbol in the list of symbols in the object file.
struct SymEntry
class TapiFile
class TapiUniversal
struct Token
class WasmObjectFile
struct WasmSection
class WasmSectionOrderChecker
struct WasmSegment
class WasmSymbol
class WindowsResource
class WindowsResourceCOFFWriter
class WindowsResourceParser
struct WinResHeaderPrefix
struct WinResHeaderSuffix
struct WinResIDs
struct XCOFFCsectAuxEnt32
struct XCOFFFileAuxEnt
struct XCOFFFileHeader32
struct XCOFFFileHeader64
class XCOFFObjectFile
struct XCOFFRelocation32
struct XCOFFSectAuxEntForStat
struct XCOFFSectionHeader
struct XCOFFSectionHeader32
struct XCOFFSectionHeader64
struct XCOFFStringTable
struct XCOFFSymbolEntry
class XCOFFSymbolRef
Typedefs
using import_directory_iterator = content_iterator< ImportDirectoryEntryRef >
using delay_import_directory_iterator = content_iterator< DelayImportDirectoryEntryRef >
using export_directory_iterator = content_iterator< ExportDirectoryEntryRef >
using imported_symbol_iterator = content_iterator< ImportedSymbolRef >
using base_reloc_iterator = content_iterator< BaseRelocRef >
using import_lookup_table_entry32 = import_lookup_table_entry< support::little32_t >
using import_lookup_table_entry64 = import_lookup_table_entry< support::little64_t >
using export_name_pointer_table_entry = support::ulittle32_t
using export_ordinal_table_entry = support::ulittle16_t
using coff_symbol16 = coff_symbol< support::ulittle16_t >
using coff_symbol32 = coff_symbol< support::ulittle32_t >
using coff_tls_directory32 = coff_tls_directory< support::little32_t >
using coff_tls_directory64 = coff_tls_directory< support::little64_t >
using ELF32LEFile = ELFFile< ELF32LE >
using ELF64LEFile = ELFFile< ELF64LE >
using ELF32BEFile = ELFFile< ELF32BE >
using ELF64BEFile = ELFFile< ELF64BE >
using ELF32LEObjectFile = ELFObjectFile< ELF32LE >
using ELF64LEObjectFile = ELFObjectFile< ELF64LE >
using ELF32BEObjectFile = ELFObjectFile< ELF32BE >
using ELF64BEObjectFile = ELFObjectFile< ELF64BE >
using ELF32LE = ELFType< support::little, false >
using ELF32BE = ELFType< support::big, false >
using ELF64LE = ELFType< support::little, true >
using ELF64BE = ELFType< support::big, true >
using dice_iterator = content_iterator< DiceRef >
using export_iterator = content_iterator< ExportEntry >
using rebase_iterator = content_iterator< MachORebaseEntry >
using bind_iterator = content_iterator< MachOBindEntry >
using section_iterator = content_iterator< SectionRef >
using relocation_iterator = content_iterator< RelocationRef >
using RelocationResolver = uint64_t(*)(RelocationRef R, uint64_t S, uint64_t A)
using basic_symbol_iterator = content_iterator< BasicSymbolRef >
Enumerations
enum coff_guard_flags : uint32_t {
coff_guard_flags::CFInstrumented = 0x00000100, coff_guard_flags::HasFidTable = 0x00000400, coff_guard_flags::ProtectDelayLoadIAT = 0x00001000, coff_guard_flags::DelayLoadIATSection = 0x00002000,
coff_guard_flags::HasLongJmpTable = 0x00010000, coff_guard_flags::FidTableHasFlags = 0x10000000
}
Bits in control flow guard flags as we understand them.
enum frame_type : uint16_t { frame_type::Fpo = 0, frame_type::Trap = 1, frame_type::Tss = 2, frame_type::NonFpo = 3 }
enum object_error {
object_error::arch_not_found = 1, object_error::invalid_file_type, object_error::parse_failed, object_error::unexpected_eof,
object_error::string_table_non_null_end, object_error::invalid_section_index, object_error::bitcode_section_not_found, object_error::invalid_symbol_index
}
enum Kind {
Unknown, Eof, Identifier, Comma,
Equal, EqualEqual, KwBase, KwConstant,
KwData, KwExports, KwHeapsize, KwLibrary,
KwName, KwNoname, KwPrivate, KwStacksize,
KwVersion
}
enum { FUNCTION_SYM = 0x20, SYM_TYPE_MASK = 0x07, RELOC_OVERFLOW = 65535 }
Functions
Expected< std::unique_ptr< Binary > > createBinary (MemoryBufferRef Source, LLVMContext *Context=nullptr)
Create a Binary from Source, autodetecting the file type.
Expected< OwningBinary< Binary > > createBinary (StringRef Path)
Error writeImportLibrary (StringRef ImportName, StringRef Path, ArrayRef< COFFShortExport > Exports, COFF::MachineTypes Machine, bool MinGW)
Expected< COFFModuleDefinition > parseCOFFModuleDefinition (MemoryBufferRef MB, COFF::MachineTypes Machine, bool MingwDef=false)
StringRef getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
uint32_t getELFRelativeRelocationType (uint32_t Machine)
StringRef getELFSectionTypeName (uint32_t Machine, uint32_t Type)
std::pair< unsigned char, unsigned char > getElfArchType (StringRef Object)
static Error createError (const Twine &Err)
template<class ELFT >
std::string getSecIndexForError (const ELFFile< ELFT > *Obj, const typename ELFT::Shdr *Sec)
static Error defaultWarningHandler (const Twine &Msg)
template<class ELFT >
Expected< const typename ELFT::Shdr * > getSection (typename ELFT::ShdrRange Sections, uint32_t Index)
template<class ELFT >
Expected< uint32_t > getExtendedSymbolTableIndex (const typename ELFT::Sym *Sym, const typename ELFT::Sym *FirstSym, ArrayRef< typename ELFT::Word > ShndxTable)
unsigned hashSysV (StringRef SymbolName)
This function returns the hash value for a symbol in the .dynsym section Name of the API remains consistent as specified in the libelf REF : http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#hash.
const std::error_category & object_category ()
std::error_code make_error_code (object_error e)
Error isNotObjectErrorInvalidFileType (llvm::Error Err)
isNotObjectErrorInvalidFileType() is used when looping through the children of an archive after calling getAsBinary() on the child and it returns an llvm::Error.
Expected< IRSymtabFile > readIRSymtab (MemoryBufferRef MBRef)
Reads a bitcode file, creating its irsymtab if necessary.
bool operator< (const SectionedAddress &LHS, const SectionedAddress &RHS)
bool operator== (const SectionedAddress &LHS, const SectionedAddress &RHS)
raw_ostream & operator<< (raw_ostream &OS, const SectionedAddress &Addr)
template<typename OStream >
OStream & operator<< (OStream &OS, const DataRefImpl &D)
bool operator== (const DataRefImpl &a, const DataRefImpl &b)
bool operator!= (const DataRefImpl &a, const DataRefImpl &b)
bool operator< (const DataRefImpl &a, const DataRefImpl &b)
int compareAddress (const SymEntry *A, const SymEntry *B)
std::vector< std::pair< SymbolRef, uint64_t > > computeSymbolSizes (const ObjectFile &O)
Expected< std::unique_ptr< MemoryBuffer > > writeWindowsResourceCOFF (llvm::COFF::MachineTypes MachineType, const WindowsResourceParser &Parser, uint32_t TimeDateStamp)
void printResourceTypeName (uint16_t TypeID, raw_ostream &OS)
static bool is32bit (MachineTypes Machine)
static uint16_t getImgRelRelocation (MachineTypes Machine)
template<class T >
static void append (std::vector< uint8_t > &B, const T &Data)
static void writeStringTable (std::vector< uint8_t > &B, ArrayRef< const std::string > Strings)
static ImportNameType getNameType (StringRef Sym, StringRef ExtName, MachineTypes Machine, bool MinGW)
static Expected< std::string > replace (StringRef S, StringRef From, StringRef To)
static bool isDecorated (StringRef Sym, bool MingwDef)
static Error createError (const Twine &Err)
static int64_t getELFAddend (RelocationRef R)
static bool supportsX86_64 (uint64_t Type)
static uint64_t resolveX86_64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsAArch64 (uint64_t Type)
static uint64_t resolveAArch64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsBPF (uint64_t Type)
static uint64_t resolveBPF (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsMips64 (uint64_t Type)
static uint64_t resolveMips64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsPPC64 (uint64_t Type)
static uint64_t resolvePPC64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsSystemZ (uint64_t Type)
static uint64_t resolveSystemZ (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsSparc64 (uint64_t Type)
static uint64_t resolveSparc64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsAmdgpu (uint64_t Type)
static uint64_t resolveAmdgpu (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsX86 (uint64_t Type)
static uint64_t resolveX86 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsPPC32 (uint64_t Type)
static uint64_t resolvePPC32 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsARM (uint64_t Type)
static uint64_t resolveARM (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsAVR (uint64_t Type)
static uint64_t resolveAVR (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsLanai (uint64_t Type)
static uint64_t resolveLanai (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsMips32 (uint64_t Type)
static uint64_t resolveMips32 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsSparc32 (uint64_t Type)
static uint64_t resolveSparc32 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsHexagon (uint64_t Type)
static uint64_t resolveHexagon (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsRISCV (uint64_t Type)
static uint64_t resolveRISCV (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsCOFFX86 (uint64_t Type)
static uint64_t resolveCOFFX86 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsCOFFX86_64 (uint64_t Type)
static uint64_t resolveCOFFX86_64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsCOFFARM (uint64_t Type)
static uint64_t resolveCOFFARM (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsCOFFARM64 (uint64_t Type)
static uint64_t resolveCOFFARM64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsMachOX86_64 (uint64_t Type)
static uint64_t resolveMachOX86_64 (RelocationRef R, uint64_t S, uint64_t A)
static bool supportsWasm32 (uint64_t Type)
static uint64_t resolveWasm32 (RelocationRef R, uint64_t S, uint64_t A)
std::pair< bool(*)(uint64_t), RelocationResolver > getRelocationResolver (const ObjectFile &Obj)
static Error readStringOrId (BinaryStreamReader &Reader, uint16_t &ID, ArrayRef< UTF16 > &Str, bool &IsString)
static bool convertUTF16LEToUTF8String (ArrayRef< UTF16 > Src, std::string &Out)
static std::string makeDuplicateResourceError (const ResourceEntryRef &Entry, StringRef File1, StringRef File2)
static void printStringOrID (const WindowsResourceParser::StringOrID &S, raw_string_ostream &OS, bool IsType, bool IsID)
static std::string makeDuplicateResourceError (const std::vector< WindowsResourceParser::StringOrID > &Context, StringRef File1, StringRef File2)
static void coffnamecpy (char(&Dest)[COFF::NameSize], StringRef Src)
template<typename T >
static Expected< const T * > getObject (MemoryBufferRef M, const void *Ptr, const uint64_t Size=sizeof(T))
static uintptr_t getWithOffset (uintptr_t Base, ptrdiff_t Offset)
template<typename T >
static const T * viewAs (uintptr_t in)
static StringRef generateXCOFFFixedNameStringRef (const char *Name)
Variables
constexpr int NumElfSymbolTypes = 16
const llvm::EnumEntry< unsigned > ElfSymbolTypes [NumElfSymbolTypes]
std::pair< bool(*)(uint64_t), RelocationResolver > getRelocationResolver (const ObjectFile &Obj)
const size_t WIN_RES_MAGIC_SIZE = 16
const size_t WIN_RES_NULL_ENTRY_SIZE = 16
const uint32_t WIN_RES_HEADER_ALIGNMENT = 4
const uint32_t WIN_RES_DATA_ALIGNMENT = 4
const uint16_t WIN_RES_PURE_MOVEABLE = 0x0030
static const std::string NullImportDescriptorSymbolName
const uint32_t MIN_HEADER_SIZE = 7 * sizeof(uint32_t) + 2 * sizeof(uint16_t)
const uint32_t SECTION_ALIGNMENT = sizeof(uint64_t)
Typedef Documentation
base_reloc_iterator
using llvm::object::base_reloc_iterator = typedef content_iterator<BaseRelocRef>
Definition at line 50 of file COFF.h.
basic_symbol_iterator
using llvm::object::basic_symbol_iterator = typedef content_iterator<BasicSymbolRef>
Definition at line 138 of file SymbolicFile.h.
bind_iterator
using llvm::object::bind_iterator = typedef content_iterator<MachOBindEntry>
Definition at line 260 of file MachO.h.
coff_symbol16
using llvm::object::coff_symbol16 = typedef coff_symbol<support::ulittle16_t>
Definition at line 265 of file COFF.h.
coff_symbol32
using llvm::object::coff_symbol32 = typedef coff_symbol<support::ulittle32_t>
Definition at line 266 of file COFF.h.
coff_tls_directory32
using llvm::object::coff_tls_directory32 = typedef coff_tls_directory<support::little32_t>
Definition at line 586 of file COFF.h.
coff_tls_directory64
using llvm::object::coff_tls_directory64 = typedef coff_tls_directory<support::little64_t>
Definition at line 587 of file COFF.h.
delay_import_directory_iterator
using llvm::object::delay_import_directory_iterator = typedef content_iterator<DelayImportDirectoryEntryRef>
Definition at line 47 of file COFF.h.
dice_iterator
using llvm::object::dice_iterator = typedef content_iterator<DiceRef>
Definition at line 63 of file MachO.h.
ELF32BE
using llvm::object::ELF32BE = typedef ELFType<support::big, false>
Definition at line 95 of file ELFTypes.h.
ELF32BEFile
using llvm::object::ELF32BEFile = typedef ELFFile<ELF32BE>
Definition at line 306 of file ELF.h.
ELF32BEObjectFile
using llvm::object::ELF32BEObjectFile = typedef ELFObjectFile<ELF32BE>
Definition at line 446 of file ELFObjectFile.h.
ELF32LE
using llvm::object::ELF32LE = typedef ELFType<support::little, false>
Definition at line 94 of file ELFTypes.h.
ELF32LEFile
using llvm::object::ELF32LEFile = typedef ELFFile<ELF32LE>
Definition at line 304 of file ELF.h.
ELF32LEObjectFile
using llvm::object::ELF32LEObjectFile = typedef ELFObjectFile<ELF32LE>
Definition at line 444 of file ELFObjectFile.h.
ELF64BE
using llvm::object::ELF64BE = typedef ELFType<support::big, true>
Definition at line 97 of file ELFTypes.h.
ELF64BEFile
using llvm::object::ELF64BEFile = typedef ELFFile<ELF64BE>
Definition at line 307 of file ELF.h.
ELF64BEObjectFile
using llvm::object::ELF64BEObjectFile = typedef ELFObjectFile<ELF64BE>
Definition at line 447 of file ELFObjectFile.h.
ELF64LE
using llvm::object::ELF64LE = typedef ELFType<support::little, true>
Definition at line 96 of file ELFTypes.h.
ELF64LEFile
using llvm::object::ELF64LEFile = typedef ELFFile<ELF64LE>
Definition at line 305 of file ELF.h.
ELF64LEObjectFile
using llvm::object::ELF64LEObjectFile = typedef ELFObjectFile<ELF64LE>
Definition at line 445 of file ELFObjectFile.h.
export_directory_iterator
using llvm::object::export_directory_iterator = typedef content_iterator<ExportDirectoryEntryRef>
Definition at line 48 of file COFF.h.
export_iterator
using llvm::object::export_iterator = typedef content_iterator<ExportEntry>
Definition at line 125 of file MachO.h.
export_name_pointer_table_entry
using llvm::object::export_name_pointer_table_entry = typedef support::ulittle32_t
Definition at line 241 of file COFF.h.
export_ordinal_table_entry
using llvm::object::export_ordinal_table_entry = typedef support::ulittle16_t
Definition at line 242 of file COFF.h.
import_directory_iterator
using llvm::object::import_directory_iterator = typedef content_iterator<ImportDirectoryEntryRef>
Definition at line 45 of file COFF.h.
import_lookup_table_entry32
using llvm::object::import_lookup_table_entry32 = typedef import_lookup_table_entry<support::little32_t>
Definition at line 206 of file COFF.h.
import_lookup_table_entry64
using llvm::object::import_lookup_table_entry64 = typedef import_lookup_table_entry<support::little64_t>
Definition at line 208 of file COFF.h.
imported_symbol_iterator
using llvm::object::imported_symbol_iterator = typedef content_iterator<ImportedSymbolRef>
Definition at line 49 of file COFF.h.
rebase_iterator
using llvm::object::rebase_iterator = typedef content_iterator<MachORebaseEntry>
Definition at line 202 of file MachO.h.
relocation_iterator
using llvm::object::relocation_iterator = typedef content_iterator<RelocationRef>
Definition at line 77 of file ObjectFile.h.
RelocationResolver
using llvm::object::RelocationResolver = typedef uint64_t (*)(RelocationRef R, uint64_t S, uint64_t A)
Definition at line 34 of file RelocationResolver.h.
section_iterator
using llvm::object::section_iterator = typedef content_iterator<SectionRef>
Definition at line 48 of file ObjectFile.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FUNCTION_SYM
SYM_TYPE_MASK
RELOC_OVERFLOW
Definition at line 20 of file XCOFFObjectFile.cpp.
coff_guard_flags
enum llvm::object::coff_guard_flags : uint32_t strong
Bits in control flow guard flags as we understand them.
Enumerator
CFInstrumented
HasFidTable
ProtectDelayLoadIAT
DelayLoadIATSection
HasLongJmpTable
FidTableHasFlags
Definition at line 590 of file COFF.h.
frame_type
enum llvm::object::frame_type : uint16_t strong
Enumerator
Fpo
Trap
Tss
NonFpo
Definition at line 599 of file COFF.h.
Kind
enum llvm::object::Kind
Enumerator
Unknown
Eof
Identifier
Comma
Equal
EqualEqual
KwBase
KwConstant
KwData
KwExports
KwHeapsize
KwLibrary
KwName
KwNoname
KwPrivate
KwStacksize
KwVersion
Definition at line 33 of file COFFModuleDefinition.cpp.
object_error
enum llvm::object::object_error strong
Enumerator
arch_not_found
invalid_file_type
parse_failed
unexpected_eof
string_table_non_null_end
invalid_section_index
bitcode_section_not_found
invalid_symbol_index
Definition at line 27 of file Error.h.
Function Documentation
append()
template<class T > static void llvm::object::append (std::vector< uint8_t > & B, const T & Data) static
Definition at line 60 of file COFFImportFile.cpp.
coffnamecpy()
static void llvm::object::coffnamecpy (char(&) Dest[COFF::NameSize], StringRef Src) static
Definition at line 722 of file WindowsResource.cpp.
References llvm::alignTo(), assert(), llvm::object::coff_resource_dir_table::Characteristics, llvm::copy(), llvm::StringRef::data(), llvm::formatv(), llvm::object::WindowsResourceParser::TreeNode::getIDChildren(), llvm::object::WindowsResourceParser::TreeNode::getStringChildren(), llvm::COFF::IMAGE_FILE_32BIT_MACHINE, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_NULL, llvm::object::coff_aux_section_definition::Length, llvm::object::coff_file_header::Machine, llvm::object::coff_resource_dir_table::MajorVersion, llvm::object::coff_resource_dir_table::MinorVersion, llvm::COFF::NameSize, llvm::object::coff_resource_dir_table::NumberOfIDEntries, llvm::object::coff_resource_dir_table::NumberOfNameEntries, llvm::StringRef::size(), llvm::ArrayRef< T >::size(), llvm::ARMBuildAttrs::Symbol, llvm::object::coff_resource_dir_table::TimeDateStamp, and llvm::support::endian::write16le().
compareAddress()
int llvm::object::compareAddress (const SymEntry * A, const SymEntry * B)
Definition at line 19 of file SymbolSize.cpp.
References llvm::object::SymEntry::Address, and llvm::object::SymEntry::SectionID.
Referenced by computeSymbolSizes().
computeSymbolSizes()
std::vector< std::pair< SymbolRef, uint64_t > > llvm::object::computeSymbolSizes (const ObjectFile & O)
Definition at line 40 of file SymbolSize.cpp.
References llvm::Address, llvm::array_pod_sort(), compareAddress(), E, getSectionID(), getSymbolSectionID(), llvm::object::SymbolRef::getValue(), I, N, P, llvm::MipsISD::Ret, llvm::object::ObjectFile::sections(), Size, llvm::object::SymbolicFile::symbol_begin(), and llvm::object::SymbolicFile::symbol_end().
Referenced by llvm::symbolize::SymbolizableObjectFile::create().
convertUTF16LEToUTF8String()
static bool llvm::object::convertUTF16LEToUTF8String (ArrayRef< UTF16 > Src, std::string & Out) static
Definition at line 170 of file WindowsResource.cpp.
References llvm::ArrayRef< T >::begin(), llvm::convertUTF16ToUTF8String(), llvm::copy(), llvm::sys::IsBigEndianHost, llvm::makeArrayRef(), llvm::ArrayRef< T >::size(), and UNI_UTF16_BYTE_ORDER_MARK_SWAPPED.
Referenced by makeDuplicateResourceError(), and printStringOrID().
createBinary() [1/2]
Expected< std::unique_ptr< Binary > > llvm::object::createBinary (MemoryBufferRef Source, LLVMContext * Context = nullptr)
Create a Binary from Source, autodetecting the file type.
Parameters
Source The data to create the Binary from.
Definition at line 46 of file Binary.cpp.
References llvm::file_magic::archive, llvm::file_magic::bitcode, llvm::file_magic::coff_cl_gl_object, llvm::file_magic::coff_import_library, llvm::file_magic::coff_object, llvm::object::MinidumpFile::create(), llvm::object::TapiUniversal::create(), llvm::object::MachOUniversalBinary::create(), llvm::object::Archive::create(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::object::WindowsResource::createWindowsResource(), llvm::file_magic::elf, llvm::file_magic::elf_core, llvm::file_magic::elf_executable, llvm::file_magic::elf_relocatable, llvm::file_magic::elf_shared_object, llvm::errorCodeToError(), llvm::MemoryBufferRef::getBuffer(), llvm::identify_magic(), invalid_file_type, llvm_unreachable, llvm::file_magic::macho_bundle, llvm::file_magic::macho_core, llvm::file_magic::macho_dsym_companion, llvm::file_magic::macho_dynamic_linker, llvm::file_magic::macho_dynamically_linked_shared_lib, llvm::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::file_magic::macho_executable, llvm::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::file_magic::macho_kext_bundle, llvm::file_magic::macho_object, llvm::file_magic::macho_preload_executable, llvm::file_magic::macho_universal_binary, llvm::file_magic::minidump, llvm::file_magic::pdb, llvm::file_magic::pecoff_executable, llvm::file_magic::tapi_file, llvm::file_magic::unknown, llvm::file_magic::wasm_object, llvm::file_magic::windows_resource, llvm::file_magic::xcoff_object_32, and llvm::file_magic::xcoff_object_64.
Referenced by llvm::object::Binary::checkOffset(), llvm::coverage::BinaryCoverageReader::create(), createBinary(), llvm::object::Archive::Child::getAsBinary(), and LLVMCreateBinary().
createBinary() [2/2]
Expected< OwningBinary< Binary > > llvm::object::createBinary (StringRef Path)
Definition at line 96 of file Binary.cpp.
References createBinary(), llvm::errorCodeToError(), llvm::ErrorOr< T >::get(), llvm::Expected< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFileOrSTDIN(), and llvm::Expected< T >::takeError().
Referenced by llvm::object::OwningBinary< object::ObjectFile >::getBinary().
createError() [1/2]
static Error llvm::object::createError (const Twine & Err) inline static
Definition at line 47 of file ELF.h.
Referenced by llvm::object::MinidumpFile::create(), llvm::object::ELFFile< ELFT >::create(), llvm::object::ObjectFile::createELFObjectFile(), defaultWarningHandler(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::object::ELFFile< ELFT >::getEntry(), getExtendedSymbolTableIndex(), llvm::object::MinidumpFile::getMemoryInfoList(), llvm::object::ELFObjectFile< ELFT >::getRelocationAddend(), getSection(), llvm::object::ELFFile< ELFT >::getSectionContentsAsArray(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ELFFile< ELFT >::getSectionStringTable(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::object::MinidumpFile::getString(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::object::ELFFile< ELFT >::getStringTableForSymtab(), llvm::object::ELFFile< ELFT >::getSymbol(), llvm::object::ELFFile< ELFT >::program_headers(), llvm::object::ELFFile< ELFT >::sections(), and llvm::object::ELFFile< ELFT >::toMappedAddr().
createError() [2/2]
static Error llvm::object::createError (const Twine & Err) static
Definition at line 83 of file COFFModuleDefinition.cpp.
defaultWarningHandler()
static Error llvm::object::defaultWarningHandler (const Twine & Msg) inline static
Definition at line 67 of file ELF.h.
References createError(), and LLVM_ELF_IMPORT_TYPES_ELFT.
Referenced by llvm::object::ELFFile< ELFT >::getHeader().
generateXCOFFFixedNameStringRef()
static StringRef llvm::object::generateXCOFFFixedNameStringRef (const char * Name) static
Definition at line 42 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::NameSize.
Referenced by llvm::object::XCOFFObjectFile::getCFileName(), llvm::object::XCOFFSectionHeader< XCOFFSectionHeader64 >::getName(), llvm::object::XCOFFObjectFile::getSectionName(), llvm::object::XCOFFObjectFile::getSymbolName(), and llvm::object::XCOFFObjectFile::getSymbolSectionName().
getELFAddend()
static int64_t llvm::object::getELFAddend (RelocationRef R) static
Definition at line 18 of file RelocationResolver.cpp.
References llvm::object::ELFRelocationRef::getAddend(), llvm::handleAllErrors(), llvm::report_fatal_error(), and llvm::Expected< T >::takeError().
Referenced by resolveAArch64(), resolveAmdgpu(), resolveAVR(), resolveHexagon(), resolveLanai(), resolveMips64(), resolvePPC32(), resolvePPC64(), resolveRISCV(), resolveSparc32(), resolveSparc64(), resolveSystemZ(), and resolveX86_64().
getElfArchType()
std::pair<unsigned char, unsigned char> llvm::object::getElfArchType (StringRef Object) inline
Definition at line 39 of file ELF.h.
References llvm::ELF::EI_CLASS, llvm::ELF::EI_DATA, llvm::ELF::EI_NIDENT, llvm::ELF::ELFCLASSNONE, llvm::ELF::ELFDATANONE, and llvm::StringRef::size().
Referenced by llvm::object::ObjectFile::createELFObjectFile().
getELFRelativeRelocationType()
uint32_t llvm::object::getELFRelativeRelocationType (uint32_t Machine)
Definition at line 156 of file ELF.cpp.
References llvm::ELF::EM_386, llvm::ELF::EM_AARCH64, llvm::ELF::EM_AMDGPU, llvm::ELF::EM_ARC_COMPACT, llvm::ELF::EM_ARC_COMPACT2, llvm::ELF::EM_ARM, llvm::ELF::EM_AVR, llvm::ELF::EM_BPF, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_IAMCU, llvm::ELF::EM_LANAI, llvm::ELF::EM_MIPS, llvm::ELF::EM_MIPS_RS3_LE, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_RISCV, llvm::ELF::EM_S390, llvm::ELF::EM_SPARC, llvm::ELF::EM_SPARC32PLUS, llvm::ELF::EM_SPARCV9, llvm::ELF::EM_X86_64, getELFSectionTypeName(), Machine, llvm::ELF::SHT_ANDROID_REL, llvm::ELF::SHT_ANDROID_RELA, llvm::ELF::SHT_ANDROID_RELR, llvm::ELF::SHT_ARM_ATTRIBUTES, llvm::ELF::SHT_ARM_DEBUGOVERLAY, llvm::ELF::SHT_ARM_EXIDX, llvm::ELF::SHT_ARM_OVERLAYSECTION, llvm::ELF::SHT_ARM_PREEMPTMAP, llvm::ELF::SHT_DYNAMIC, llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_GNU_ATTRIBUTES, llvm::ELF::SHT_GNU_HASH, llvm::ELF::SHT_GNU_verdef, llvm::ELF::SHT_GNU_verneed, llvm::ELF::SHT_GNU_versym, llvm::ELF::SHT_GROUP, llvm::ELF::SHT_HASH, llvm::ELF::SHT_HEX_ORDERED, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_LLVM_ADDRSIG, llvm::ELF::SHT_LLVM_CALL_GRAPH_PROFILE, llvm::ELF::SHT_LLVM_DEPENDENT_LIBRARIES, llvm::ELF::SHT_LLVM_LINKER_OPTIONS, llvm::ELF::SHT_LLVM_ODRTAB, llvm::ELF::SHT_LLVM_PART_EHDR, llvm::ELF::SHT_LLVM_PART_PHDR, llvm::ELF::SHT_LLVM_SYMPART, llvm::ELF::SHT_MIPS_ABIFLAGS, llvm::ELF::SHT_MIPS_DWARF, llvm::ELF::SHT_MIPS_OPTIONS, llvm::ELF::SHT_MIPS_REGINFO, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_NULL, llvm::ELF::SHT_PREINIT_ARRAY, llvm::ELF::SHT_PROGBITS, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, llvm::ELF::SHT_RELR, llvm::ELF::SHT_SHLIB, llvm::ELF::SHT_STRTAB, llvm::ELF::SHT_SYMTAB, llvm::ELF::SHT_SYMTAB_SHNDX, llvm::ELF::SHT_X86_64_UNWIND, and STRINGIFY_ENUM_CASE.
Referenced by llvm::object::ELFFile< ELFT >::getRelativeRelocationType().
getELFRelocationTypeName()
StringRef llvm::object::getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
Definition at line 22 of file ELF.cpp.
References llvm::ELF::EM_386, llvm::ELF::EM_AARCH64, llvm::ELF::EM_AMDGPU, llvm::ELF::EM_ARC_COMPACT, llvm::ELF::EM_ARC_COMPACT2, llvm::ELF::EM_ARM, llvm::ELF::EM_AVR, llvm::ELF::EM_BPF, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_IAMCU, llvm::ELF::EM_LANAI, llvm::ELF::EM_MIPS, llvm::ELF::EM_MSP430, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_RISCV, llvm::ELF::EM_S390, llvm::ELF::EM_SPARC, llvm::ELF::EM_SPARC32PLUS, llvm::ELF::EM_SPARCV9, and llvm::ELF::EM_X86_64.
Referenced by llvm::object::ELFFile< ELFT >::getRelocationTypeName(), and llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName().
getELFSectionTypeName()
StringRef llvm::object::getELFSectionTypeName (uint32_t Machine, uint32_t Type)
Referenced by getELFRelativeRelocationType(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), and llvm::object::ELFFile< ELFT >::getStringTable().
getExtendedSymbolTableIndex()
template<class ELFT > Expected<uint32_t> llvm::object::getExtendedSymbolTableIndex (const typename ELFT::Sym * Sym, const typename ELFT::Sym * FirstSym, ArrayRef< typename ELFT::Word > ShndxTable) inline
Definition at line 319 of file ELF.h.
References assert(), createError(), llvm::ELF::SHN_XINDEX, and llvm::ArrayRef< T >::size().
getImgRelRelocation()
static uint16_t llvm::object::getImgRelRelocation (MachineTypes Machine) static
Definition at line 45 of file COFFImportFile.cpp.
References llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_ARM64_ADDR32NB, llvm::COFF::IMAGE_REL_ARM_ADDR32NB, llvm::COFF::IMAGE_REL_I386_DIR32NB, and llvm_unreachable.
getNameType()
static ImportNameType llvm::object::getNameType (StringRef Sym, StringRef ExtName, MachineTypes Machine, bool MinGW) static
Definition at line 92 of file COFFImportFile.cpp.
References llvm::StringRef::contains(), llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMPORT_NAME, llvm::COFF::IMPORT_NAME_NOPREFIX, llvm::COFF::IMPORT_NAME_UNDECORATE, and llvm::StringRef::startswith().
getObject()
template<typename T > static Expected<const T *> llvm::object::getObject (MemoryBufferRef M, const void * Ptr, const uint64_t Size = sizeof(T)) static
Definition at line 25 of file XCOFFObjectFile.cpp.
References llvm::object::Binary::checkOffset(), llvm::errorCodeToError(), and Size.
Referenced by llvm::object::COFFObjectFile::COFFObjectFile(), llvm::object::ELFRelocationRef::getAddend(), llvm::object::ELFSymbolRef::getBinding(), llvm::object::ELFSymbolRef::getELFType(), llvm::object::ELFSectionRef::getFlags(), llvm::object::ImportDirectoryEntryRef::getImportTableEntry(), getNumberOfRelocations(), llvm::object::ELFSectionRef::getOffset(), llvm::object::ELFSymbolRef::getOther(), llvm::object::ELFSymbolRef::getSize(), llvm::object::ELFSectionRef::getType(), and llvm::object::COFFObjectFile::section_rel_end().
getRelocationResolver()
std::pair<bool (*)(uint64_t), RelocationResolver> llvm::object::getRelocationResolver (const ObjectFile & Obj)
Definition at line 528 of file RelocationResolver.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::Triple::amdgcn, llvm::Triple::arm, llvm::Triple::armeb, assert(), llvm::Triple::avr, llvm::Triple::bpfeb, llvm::Triple::bpfel, llvm::object::ObjectFile::getArch(), llvm::object::ObjectFile::getBytesInAddress(), llvm::Triple::hexagon, llvm::object::Binary::isCOFF(), llvm::object::Binary::isELF(), llvm::object::Binary::isMachO(), llvm::object::Binary::isWasm(), llvm::Triple::lanai, llvm_unreachable, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, resolveAArch64(), resolveAmdgpu(), resolveARM(), resolveAVR(), resolveBPF(), resolveCOFFARM(), resolveCOFFARM64(), resolveCOFFX86(), resolveCOFFX86_64(), resolveHexagon(), resolveLanai(), resolveMachOX86_64(), resolveMips32(), resolveMips64(), resolvePPC32(), resolvePPC64(), resolveRISCV(), resolveSparc32(), resolveSparc64(), resolveSystemZ(), resolveWasm32(), resolveX86(), resolveX86_64(), llvm::Triple::riscv32, llvm::Triple::riscv64, llvm::Triple::sparc, llvm::Triple::sparcv9, supportsAArch64(), supportsAmdgpu(), supportsARM(), supportsAVR(), supportsBPF(), supportsCOFFARM(), supportsCOFFARM64(), supportsCOFFX86(), supportsCOFFX86_64(), supportsHexagon(), supportsLanai(), supportsMachOX86_64(), supportsMips32(), supportsMips64(), supportsPPC32(), supportsPPC64(), supportsRISCV(), supportsSparc32(), supportsSparc64(), supportsSystemZ(), supportsWasm32(), supportsX86(), supportsX86_64(), llvm::Triple::systemz, llvm::Triple::thumb, llvm::Triple::wasm32, llvm::Triple::x86, and llvm::Triple::x86_64.
getSecIndexForError()
template<class ELFT > std::string llvm::object::getSecIndexForError (const ELFFile< ELFT > * Obj, const typename ELFT::Shdr * Sec)
Definition at line 54 of file ELF.h.
References llvm::consumeError(), llvm::object::ELFFile< ELFT >::sections(), and llvm::to_string().
Referenced by llvm::object::ELFFile< ELFT >::getEntry(), llvm::object::ELFFile< ELFT >::getSectionContentsAsArray(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ELFFile< ELFT >::getStringTable(), and llvm::object::ELFFile< ELFT >::getSymbol().
getSection()
template<class ELFT > Expected<const typename ELFT::Shdr *> llvm::object::getSection (typename ELFT::ShdrRange Sections, uint32_t Index) inline
Definition at line 311 of file ELF.h.
References createError().
Referenced by llvm::object::MachOObjectFile::BindRebaseAddress(), llvm::DwarfCompileUnit::getLabelBegin(), llvm::object::COFFObjectFile::getPE32PlusHeader(), llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::ELFObjectFile< ELFT >::getSectionAddress(), llvm::object::MachOObjectFile::getSectionAddress(), llvm::object::ELFObjectFile< ELFT >::getSectionAlignment(), llvm::object::MachOObjectFile::getSectionAlignment(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::MachOObjectFile::getSectionContents(), llvm::object::ELFObjectFile< ELFT >::getSectionFlags(), llvm::object::ELFObjectFile< ELFT >::getSectionIndex(), llvm::object::ELFObjectFile< ELFT >::getSectionName(), llvm::object::ELFObjectFile< ELFT >::getSectionOffset(), llvm::object::ELFObjectFile< ELFT >::getSectionSize(), llvm::object::MachOObjectFile::getSectionSize(), llvm::object::ELFObjectFile< ELFT >::getSectionType(), llvm::GlobalValue::hasSection(), llvm::object::ELFObjectFile< ELFT >::isBerkeleyData(), llvm::object::ELFObjectFile< ELFT >::isBerkeleyText(), llvm::object::ELFObjectFile< ELFT >::isSectionBSS(), llvm::object::ELFObjectFile< ELFT >::isSectionCompressed(), llvm::object::ELFObjectFile< ELFT >::isSectionData(), llvm::object::MachOObjectFile::isSectionStripped(), llvm::object::ELFObjectFile< ELFT >::isSectionText(), llvm::object::ELFObjectFile< ELFT >::isSectionVirtual(), LLVMGetSection(), LLVMMoveToContainingSection(), llvm::object::ELFObjectFile< ELFT >::moveSectionNext(), and llvm::object::SymbolRef::SymbolRef().
getWithOffset()
static uintptr_t llvm::object::getWithOffset (uintptr_t Base, ptrdiff_t Offset) static
Definition at line 33 of file XCOFFObjectFile.cpp.
Referenced by llvm::object::XCOFFObjectFile::getNumberOfSymbolTableEntries64(), llvm::object::XCOFFObjectFile::getSectionByNum(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxEnt32(), llvm::object::XCOFFObjectFile::relocations(), and llvm::object::XCOFFObjectFile::section_end().
hashSysV()
unsigned llvm::object::hashSysV (StringRef SymbolName) inline
This function returns the hash value for a symbol in the .dynsym section Name of the API remains consistent as specified in the libelf REF : http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#hash.
Definition at line 713 of file ELF.h.
References C.
is32bit()
static bool llvm::object::is32bit (MachineTypes Machine) static
Definition at line 32 of file COFFImportFile.cpp.
References llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, and llvm_unreachable.
Referenced by makeCombineInst().
isDecorated()
static bool llvm::object::isDecorated (StringRef Sym, bool MingwDef) static
Definition at line 59 of file COFFModuleDefinition.cpp.
References llvm::StringRef::contains(), and llvm::StringRef::startswith().
isNotObjectErrorInvalidFileType()
llvm::Error llvm::object::isNotObjectErrorInvalidFileType (llvm::Error Err)
isNotObjectErrorInvalidFileType() is used when looping through the children of an archive after calling getAsBinary() on the child and it returns an llvm::Error.
In the cases we want to loop through the children and ignore the non-objects in the archive this is used to test the error to see if an error() function needs to called on the llvm::Error.
Definition at line 80 of file Error.cpp.
Referenced by llvm::object::GenericBinaryError::getMessage().
make_error_code()
std::error_code llvm::object::make_error_code (object_error e) inline
Definition at line 39 of file Error.h.
References object_category().
Referenced by llvm::object::BinaryError::BinaryError(), llvm::createStringError(), and llvm::object::GenericBinaryError::GenericBinaryError().
makeDuplicateResourceError() [1/2]
static std::string llvm::object::makeDuplicateResourceError (const ResourceEntryRef & Entry, StringRef File1, StringRef File2) static
Definition at line 181 of file WindowsResource.cpp.
References llvm::object::ResourceEntryRef::checkNameString(), llvm::object::ResourceEntryRef::checkTypeString(), convertUTF16LEToUTF8String(), llvm::object::ResourceEntryRef::getLanguage(), llvm::object::ResourceEntryRef::getNameID(), llvm::object::ResourceEntryRef::getNameString(), llvm::object::ResourceEntryRef::getTypeID(), llvm::object::ResourceEntryRef::getTypeString(), printResourceTypeName(), llvm::MipsISD::Ret, and llvm::StringRef::str().
makeDuplicateResourceError() [2/2]
static std::string llvm::object::makeDuplicateResourceError (const std::vector< WindowsResourceParser::StringOrID > & Context, StringRef File1, StringRef File2) static
Definition at line 228 of file WindowsResource.cpp.
References printStringOrID(), llvm::MipsISD::Ret, and llvm::raw_string_ostream::str().
object_category()
const std::error_category & llvm::object::object_category ()
Definition at line 76 of file Error.cpp.
References error_category.
Referenced by make_error_code().
operator!=()
bool llvm::object::operator!= (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 58 of file SymbolicFile.h.
References operator==().
operator<() [1/2]
bool llvm::object::operator< (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 62 of file SymbolicFile.h.
References memcmp.
operator<() [2/2]
bool llvm::object::operator< (const SectionedAddress & LHS, const SectionedAddress & RHS) inline
Definition at line 146 of file ObjectFile.h.
References llvm::object::SectionedAddress::Address, and llvm::object::SectionedAddress::SectionIndex.
Referenced by llvm::symbolize::SymbolizableObjectFile::create().
operator<<() [1/2]
template<typename OStream > OStream& llvm::object::operator<< (OStream & OS, const DataRefImpl & D)
Definition at line 46 of file SymbolicFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::format(), and llvm::object::DataRefImpl::p.
operator<<() [2/2]
raw_ostream & llvm::object::operator<< (raw_ostream & OS, const SectionedAddress & Addr)
Definition at line 35 of file ObjectFile.cpp.
References llvm::object::SectionedAddress::Address, llvm::format_hex(), llvm::object::SectionedAddress::SectionIndex, and llvm::object::SectionedAddress::UndefSection.
Referenced by operator==().
operator==() [1/2]
bool llvm::object::operator== (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 52 of file SymbolicFile.h.
References memcmp.
operator==() [2/2]
bool llvm::object::operator== (const SectionedAddress & LHS, const SectionedAddress & RHS) inline
Definition at line 152 of file ObjectFile.h.
References llvm::object::SectionedAddress::Address, operator<<(), and llvm::object::SectionedAddress::SectionIndex.
Referenced by llvm::object::BaseRelocRef::BaseRelocRef(), llvm::object::DelayImportDirectoryEntryRef::DelayImportDirectoryEntryRef(), llvm::object::ExportDirectoryEntryRef::ExportDirectoryEntryRef(), llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef(), llvm::object::ImportedSymbolRef::ImportedSymbolRef(), and operator!=().
parseCOFFModuleDefinition()
Expected< COFFModuleDefinition > llvm::object::parseCOFFModuleDefinition (MemoryBufferRef MB, COFF::MachineTypes Machine, bool MingwDef = false)
Definition at line 361 of file COFFModuleDefinition.cpp.
References llvm::MemoryBufferRef::getBuffer(), Machine, and parse().
Referenced by llvm::dlltoolDriverMain().
printResourceTypeName()
void llvm::object::printResourceTypeName (uint16_t TypeID, raw_ostream & OS)
Definition at line 143 of file WindowsResource.cpp.
Referenced by makeDuplicateResourceError(), printStringOrID(), and llvm::object::WindowsResourceParser::StringOrID::StringOrID().
printStringOrID()
static void llvm::object::printStringOrID (const WindowsResourceParser::StringOrID & S, raw_string_ostream & OS, bool IsType, bool IsID) static
Definition at line 213 of file WindowsResource.cpp.
References convertUTF16LEToUTF8String(), llvm::object::WindowsResourceParser::StringOrID::ID, llvm::object::WindowsResourceParser::StringOrID::IsString, printResourceTypeName(), and llvm::object::WindowsResourceParser::StringOrID::String.
Referenced by makeDuplicateResourceError().
readIRSymtab()
Expected< IRSymtabFile > llvm::object::readIRSymtab (MemoryBufferRef MBRef)
Reads a bitcode file, creating its irsymtab if necessary.
Definition at line 135 of file IRObjectFile.cpp.
References F(), llvm::getBitcodeFileContents(), llvm::object::IRSymtabFile::Mods, llvm::irsymtab::readBitcode(), llvm::object::IRSymtabFile::Strtab, llvm::object::IRSymtabFile::Symtab, llvm::Expected< T >::takeError(), and llvm::object::IRSymtabFile::TheReader.
Referenced by llvm::lto::InputFile::create().
readStringOrId()
static Error llvm::object::readStringOrId (BinaryStreamReader & Reader, uint16_t & ID, ArrayRef< UTF16 > & Str, bool & IsString) static
Definition at line 99 of file WindowsResource.cpp.
References llvm::object::Binary::Data, llvm::object::WinResHeaderPrefix::DataSize, llvm::object::Binary::getFileName(), llvm::BinaryStreamReader::getOffset(), llvm::object::WinResHeaderPrefix::HeaderSize, Name, parse_failed, llvm::cl::Prefix, llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readWideString(), RETURN_IF_ERROR, llvm::BinaryStreamReader::setOffset(), llvm::Error::success(), WIN_RES_DATA_ALIGNMENT, and WIN_RES_HEADER_ALIGNMENT.
replace()
static Expected<std::string> llvm::object::replace (StringRef S, StringRef From, StringRef To) static
Definition at line 109 of file COFFImportFile.cpp.
References llvm::StringRef::find(), llvm::StringRef::npos, llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
resolveAArch64()
static uint64_t llvm::object::resolveAArch64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 71 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveAmdgpu()
static uint64_t llvm::object::resolveAmdgpu (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 206 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveARM()
static uint64_t llvm::object::resolveARM (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 254 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveAVR()
static uint64_t llvm::object::resolveAVR (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 270 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveBPF()
static uint64_t llvm::object::resolveBPF (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 92 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFARM()
static uint64_t llvm::object::resolveCOFFARM (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 447 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), llvm::COFF::IMAGE_REL_ARM_ADDR32, llvm::COFF::IMAGE_REL_ARM_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFARM64()
static uint64_t llvm::object::resolveCOFFARM64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 467 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), llvm::COFF::IMAGE_REL_ARM64_ADDR64, llvm::COFF::IMAGE_REL_ARM64_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFX86()
static uint64_t llvm::object::resolveCOFFX86 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 406 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), llvm::COFF::IMAGE_REL_I386_DIR32, llvm::COFF::IMAGE_REL_I386_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFX86_64()
static uint64_t llvm::object::resolveCOFFX86_64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 426 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveHexagon()
static uint64_t llvm::object::resolveHexagon (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 332 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveLanai()
static uint64_t llvm::object::resolveLanai (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 285 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveMachOX86_64()
static uint64_t llvm::object::resolveMachOX86_64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 482 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), llvm_unreachable, and llvm::MachO::X86_64_RELOC_UNSIGNED.
Referenced by getRelocationResolver().
resolveMips32()
static uint64_t llvm::object::resolveMips32 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 301 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveMips64()
static uint64_t llvm::object::resolveMips64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 115 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getOffset(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolvePPC32()
static uint64_t llvm::object::resolvePPC32 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 244 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolvePPC64()
static uint64_t llvm::object::resolvePPC64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 140 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveRISCV()
static uint64_t llvm::object::resolveRISCV (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 360 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getOffset(), llvm::object::RelocationRef::getType(), llvm_unreachable, and RA.
Referenced by getRelocationResolver().
resolveSparc32()
static uint64_t llvm::object::resolveSparc32 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 321 of file RelocationResolver.cpp.
References getELFAddend(), and llvm::object::RelocationRef::getType().
Referenced by getRelocationResolver().
resolveSparc64()
static uint64_t llvm::object::resolveSparc64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 184 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveSystemZ()
static uint64_t llvm::object::resolveSystemZ (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 161 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveWasm32()
static uint64_t llvm::object::resolveWasm32 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 507 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveX86()
static uint64_t llvm::object::resolveX86 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 227 of file RelocationResolver.cpp.
References llvm::object::RelocationRef::getOffset(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
resolveX86_64()
static uint64_t llvm::object::resolveX86_64 (RelocationRef R, uint64_t S, uint64_t A) static
Definition at line 42 of file RelocationResolver.cpp.
References getELFAddend(), llvm::object::RelocationRef::getOffset(), llvm::object::RelocationRef::getType(), and llvm_unreachable.
Referenced by getRelocationResolver().
supportsAArch64()
static bool llvm::object::supportsAArch64 (uint64_t Type) static
Definition at line 61 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsAmdgpu()
static bool llvm::object::supportsAmdgpu (uint64_t Type) static
Definition at line 196 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsARM()
static bool llvm::object::supportsARM (uint64_t Type) static
Definition at line 250 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsAVR()
static bool llvm::object::supportsAVR (uint64_t Type) static
Definition at line 260 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsBPF()
static bool llvm::object::supportsBPF (uint64_t Type) static
Definition at line 82 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsCOFFARM()
static bool llvm::object::supportsCOFFARM (uint64_t Type) static
Definition at line 437 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_ARM_ADDR32, and llvm::COFF::IMAGE_REL_ARM_SECREL.
Referenced by getRelocationResolver().
supportsCOFFARM64()
static bool llvm::object::supportsCOFFARM64 (uint64_t Type) static
Definition at line 457 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_ARM64_ADDR64, and llvm::COFF::IMAGE_REL_ARM64_SECREL.
Referenced by getRelocationResolver().
supportsCOFFX86()
static bool llvm::object::supportsCOFFX86 (uint64_t Type) static
Definition at line 396 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_I386_DIR32, and llvm::COFF::IMAGE_REL_I386_SECREL.
Referenced by getRelocationResolver().
supportsCOFFX86_64()
static bool llvm::object::supportsCOFFX86_64 (uint64_t Type) static
Definition at line 416 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_AMD64_ADDR64, and llvm::COFF::IMAGE_REL_AMD64_SECREL.
Referenced by getRelocationResolver().
supportsHexagon()
static bool llvm::object::supportsHexagon (uint64_t Type) static
Definition at line 328 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsLanai()
static bool llvm::object::supportsLanai (uint64_t Type) static
Definition at line 281 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsMachOX86_64()
static bool llvm::object::supportsMachOX86_64 (uint64_t Type) static
Definition at line 478 of file RelocationResolver.cpp.
References llvm::MachO::X86_64_RELOC_UNSIGNED.
Referenced by getRelocationResolver().
supportsMips32()
static bool llvm::object::supportsMips32 (uint64_t Type) static
Definition at line 291 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsMips64()
static bool llvm::object::supportsMips64 (uint64_t Type) static
Definition at line 103 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsPPC32()
static bool llvm::object::supportsPPC32 (uint64_t Type) static
Definition at line 240 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsPPC64()
static bool llvm::object::supportsPPC64 (uint64_t Type) static
Definition at line 130 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsRISCV()
static bool llvm::object::supportsRISCV (uint64_t Type) static
Definition at line 338 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsSparc32()
static bool llvm::object::supportsSparc32 (uint64_t Type) static
Definition at line 311 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsSparc64()
static bool llvm::object::supportsSparc64 (uint64_t Type) static
Definition at line 172 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsSystemZ()
static bool llvm::object::supportsSystemZ (uint64_t Type) static
Definition at line 151 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsWasm32()
static bool llvm::object::supportsWasm32 (uint64_t Type) static
Definition at line 488 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsX86()
static bool llvm::object::supportsX86 (uint64_t Type) static
Definition at line 216 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsX86_64()
static bool llvm::object::supportsX86_64 (uint64_t Type) static
Definition at line 26 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
viewAs()
template<typename T > static const T* llvm::object::viewAs (uintptr_t in) static
Definition at line 38 of file XCOFFObjectFile.cpp.
writeImportLibrary()
Error llvm::object::writeImportLibrary (StringRef ImportName, StringRef Path, ArrayRef< COFFShortExport > Exports, COFF::MachineTypes Machine, bool MinGW)
Definition at line 571 of file COFFImportFile.cpp.
Referenced by llvm::dlltoolDriverMain().
writeStringTable()
static void llvm::object::writeStringTable (std::vector< uint8_t > & B, ArrayRef< const std::string > Strings) static
Definition at line 66 of file COFFImportFile.cpp.
writeWindowsResourceCOFF()
Expected< std::unique_ptr< MemoryBuffer > > llvm::object::writeWindowsResourceCOFF (llvm::COFF::MachineTypes MachineType, const WindowsResourceParser & Parser, uint32_t TimeDateStamp)
Definition at line 1002 of file WindowsResource.cpp.
References E, llvm::Error::success(), and llvm::object::WindowsResourceCOFFWriter::write().
Referenced by llvm::object::WindowsResourceParser::StringOrID::StringOrID().
Variable Documentation
ElfSymbolTypes
const EnumEntry< unsigned > llvm::object::ElfSymbolTypes
Initial value:
= {
    {"None", "NOTYPE", ELF::STT_NOTYPE},
    {"Object", "OBJECT", ELF::STT_OBJECT},
    {"Function", "FUNC", ELF::STT_FUNC},
    {"Section", "SECTION", ELF::STT_SECTION},
    {"File", "FILE", ELF::STT_FILE},
    {"Common", "COMMON", ELF::STT_COMMON},
    {"TLS", "TLS", ELF::STT_TLS},
    {"Unknown", "<unknown>: 7", 7},
    {"Unknown", "<unknown>: 8", 8},
    {"Unknown", "<unknown>: 9", 9},
    {"GNU_IFunc", "IFUNC", ELF::STT_GNU_IFUNC},
    {"OS Specific", "<OS specific>: 11", 11},
    {"OS Specific", "<OS specific>: 12", 12},
    {"Proc Specific", "<processor specific>: 13", 13},
    {"Proc Specific", "<processor specific>: 14", 14},
    {"Proc Specific", "<processor specific>: 15", 15}
}
Definition at line 38 of file ELFObjectFile.cpp.
getRelocationResolver
std::pair<bool (*)(uint64_t), RelocationResolver> llvm::object::getRelocationResolver(const ObjectFile &Obj)
Definition at line 37 of file RelocationResolver.h.
Referenced by loadObj().
MIN_HEADER_SIZE
const uint32_t llvm::object::MIN_HEADER_SIZE = 7 * sizeof(uint32_t) + 2 * sizeof(uint16_t)
Definition at line 45 of file WindowsResource.cpp.
NullImportDescriptorSymbolName
const std::string llvm::object::NullImportDescriptorSymbolName static
Initial value:
=
    "__NULL_IMPORT_DESCRIPTOR"
Definition at line 129 of file COFFImportFile.cpp.
NumElfSymbolTypes
constexpr int llvm::object::NumElfSymbolTypes = 16
Definition at line 44 of file ELFObjectFile.h.
SECTION_ALIGNMENT
const uint32_t llvm::object::SECTION_ALIGNMENT = sizeof(uint64_t)
Definition at line 49 of file WindowsResource.cpp.
WIN_RES_DATA_ALIGNMENT
const uint32_t llvm::object::WIN_RES_DATA_ALIGNMENT = 4
Definition at line 57 of file WindowsResource.h.
Referenced by readStringOrId().
WIN_RES_HEADER_ALIGNMENT
const uint32_t llvm::object::WIN_RES_HEADER_ALIGNMENT = 4
Definition at line 56 of file WindowsResource.h.
Referenced by readStringOrId().
WIN_RES_MAGIC_SIZE
const size_t llvm::object::WIN_RES_MAGIC_SIZE = 16
Definition at line 54 of file WindowsResource.h.
Referenced by llvm::object::WindowsResource::createWindowsResource().
WIN_RES_NULL_ENTRY_SIZE
const size_t llvm::object::WIN_RES_NULL_ENTRY_SIZE = 16
Definition at line 55 of file WindowsResource.h.
Referenced by llvm::object::WindowsResource::createWindowsResource().
WIN_RES_PURE_MOVEABLE
const uint16_t llvm::object::WIN_RES_PURE_MOVEABLE = 0x0030
Definition at line 58 of file WindowsResource.h.