LLVM: llvm::pdb Namespace Reference
llvm::pdb Namespace Reference
Classes
class BaseClassLayout
class ClassLayout
class ConcreteSymbolEnumerator
class DataMemberLayoutItem
struct DbiBuildNo
struct DbiFlags
Some of the values are stored in bitfields.
class DbiModuleDescriptor
class DbiModuleDescriptorBuilder
class DbiModuleList
class DbiModuleSourceFilesIterator
class DbiStream
class DbiStreamBuilder
struct DbiStreamHeader
The fixed size header that appears at the beginning of the DBI Stream.
class DIADataStream
class DIAEnumDebugStreams
class DIAEnumFrameData
class DIAEnumInjectedSources
class DIAEnumLineNumbers
class DIAEnumSectionContribs
class DIAEnumSourceFiles
class DIAEnumSymbols
class DIAEnumTables
class DIAError
Base class for errors originating in DIA SDK, e.g. COM calls.
class DIAFrameData
class DIAInjectedSource
class DIALineNumber
class DIARawSymbol
class DIASectionContrib
class DIASession
class DIASourceFile
class DIATable
struct FileInfoSubstreamHeader
The header preceding the File Info Substream of the DBI stream.
class GlobalsStream
struct GSIHashHeader
Header of the hash tables found in the globals and publics sections.
class GSIHashIterator
Iterator over hash records producing symbol record offsets.
struct GSIHashStreamBuilder
class GSIHashTable
A readonly view of a hash table used in the globals and publics streams.
class GSIStreamBuilder
class HashTable
class HashTableIterator
class InfoStream
class InfoStreamBuilder
struct InfoStreamHeader
The header preceding the global PDB Stream (Stream 1)
class InjectedSourceStream
class IPDBDataStream
IPDBDataStream defines an interface used to represent a stream consisting of a name and a series of records whose formats depend on the particular stream type.
class IPDBEnumChildren
class IPDBFrameData
IPDBFrameData defines an interface used to represent a frame data of some code block.
class IPDBInjectedSource
IPDBInjectedSource defines an interface used to represent source files which were injected directly into the PDB file during the compilation process.
class IPDBLineNumber
class IPDBRawSymbol
IPDBRawSymbol defines an interface used to represent an arbitrary symbol.
class IPDBSectionContrib
IPDBSectionContrib defines an interface used to represent section contributions whose information are stored in the PDB.
class IPDBSession
IPDBSession defines an interface used to provide a context for querying debug information from a debug data source (for example, a PDB).
class IPDBSourceFile
IPDBSourceFile defines an interface used to represent source files whose information are stored in the PDB.
class IPDBTable
class ISectionContribVisitor
class LayoutItemBase
struct ModInfoFlags
class ModuleDebugStreamRef
struct ModuleInfoHeader
The header preceding each entry in the Module Info substream of the DBI stream.
class NamedStreamMap
struct NamedStreamMapTraits
class NativeCompilandSymbol
class NativeEnumGlobals
class NativeEnumInjectedSources
class NativeEnumModules
class NativeEnumTypes
class NativeExeSymbol
class NativeRawSymbol
class NativeSession
class NativeSymbolEnumerator
class NativeTypeArray
class NativeTypeBuiltin
class NativeTypeEnum
class NativeTypeFunctionSig
class NativeTypePointer
class NativeTypeTypedef
class NativeTypeUDT
class NativeTypeVTShape
class NullEnumerator
struct PDB_SourceCompression
class PDBContext
PDBContext This data structure is the top level entity that deals with PDB debug information parsing.
class PDBError
Base class for errors originating when parsing raw PDB files.
class PDBFile
class PDBFileBuilder
class PDBStringTable
class PDBStringTableBuilder
struct PDBStringTableHeader
The header preceding the /names stream.
class PDBSymbol
PDBSymbol defines the base of the inheritance hierarchy for concrete symbol types (e.g.
class PDBSymbolAnnotation
class PDBSymbolBlock
class PDBSymbolCompiland
class PDBSymbolCompilandDetails
class PDBSymbolCompilandEnv
class PDBSymbolCustom
PDBSymbolCustom represents symbols that are compiler-specific and do not fit anywhere else in the lexical hierarchy.
class PDBSymbolData
class PDBSymbolExe
class PDBSymbolFunc
class PDBSymbolFuncDebugEnd
class PDBSymbolFuncDebugStart
class PDBSymbolLabel
class PDBSymbolPublicSymbol
class PDBSymbolThunk
class PDBSymbolTypeArray
class PDBSymbolTypeBaseClass
class PDBSymbolTypeBuiltin
class PDBSymbolTypeCustom
class PDBSymbolTypeDimension
class PDBSymbolTypeEnum
class PDBSymbolTypeFriend
class PDBSymbolTypeFunctionArg
class PDBSymbolTypeFunctionSig
class PDBSymbolTypeManaged
class PDBSymbolTypePointer
class PDBSymbolTypeTypedef
class PDBSymbolTypeUDT
class PDBSymbolTypeVTable
class PDBSymbolTypeVTableShape
class PDBSymbolUnknown
class PDBSymbolUsingNamespace
class PDBSymDumper
struct PSHashRecord
class PublicsStream
struct PublicsStreamHeader
class RawError
Base class for errors originating when parsing raw PDB files.
struct SecMapEntry
struct SecMapHeader
struct SectionContrib
struct SectionContrib2
struct SectionOffset
struct SrcHeaderBlockEntry
A single file record entry within the /src/headerblock stream.
struct SrcHeaderBlockHeader
The header preceding the /src/headerblock stream.
struct StringTableHashTraits
class SymbolCache
class SymbolStream
struct TagRecordHash
class TpiStream
class TpiStreamBuilder
struct TpiStreamHeader
class UDTLayoutBase
struct Variant
class VBPtrLayoutItem
struct VersionInfo
class VTableLayoutItem
Typedefs
using TagStats = std::unordered_map< PDB_SymType, int >
typedef uint32_t SymIndexId
using IPDBEnumSymbols = IPDBEnumChildren< PDBSymbol >
using IPDBEnumSourceFiles = IPDBEnumChildren< IPDBSourceFile >
using IPDBEnumDataStreams = IPDBEnumChildren< IPDBDataStream >
using IPDBEnumLineNumbers = IPDBEnumChildren< IPDBLineNumber >
using IPDBEnumTables = IPDBEnumChildren< IPDBTable >
using IPDBEnumInjectedSources = IPDBEnumChildren< IPDBInjectedSource >
using IPDBEnumSectionContribs = IPDBEnumChildren< IPDBSectionContrib >
using IPDBEnumFrameData = IPDBEnumChildren< IPDBFrameData >
using PDB_Cpu = codeview::CPUType
These values correspond to the CV_CPU_TYPE_e enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/b2fc64ek.aspx.
using PDB_CallingConv = codeview::CallingConvention
These values correspond to the CV_call_e enumeration, and are documented at the following locations: https://msdn.microsoft.com/en-us/library/b2fc64ek.aspx https://msdn.microsoft.com/en-us/library/windows/desktop/ms680207(v=vs.85).aspx.
using PDB_Lang = codeview::SourceLanguage
These values correspond to the CV_CFL_LANG enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/bw3aekw6.aspx.
Enumerations
enum dia_error_code {
dia_error_code::unspecified = 1, dia_error_code::could_not_create_impl, dia_error_code::invalid_file_format, dia_error_code::invalid_parameter,
dia_error_code::already_loaded, dia_error_code::debug_info_mismatch
}
enum pdb_error_code {
pdb_error_code::invalid_utf8_path = 1, pdb_error_code::dia_sdk_not_present, pdb_error_code::dia_failed_loading, pdb_error_code::signature_out_of_date,
pdb_error_code::no_matching_pch, pdb_error_code::unspecified
}
enum PdbSymbolIdField : uint32_t {
PdbSymbolIdField::None = 0, PdbSymbolIdField::SymIndexId = 1 << 0, PdbSymbolIdField::LexicalParent = 1 << 1, PdbSymbolIdField::ClassParent = 1 << 2,
PdbSymbolIdField::Type = 1 << 3, PdbSymbolIdField::UnmodifiedType = 1 << 4, PdbSymbolIdField::All = 0xFFFFFFFF
}
enum : unsigned { IPHR_HASH = 4096 }
From https://github.com/Microsoft/microsoft-pdb/blob/master/PDB/dbi/gsi.cpp.
enum PdbRaw_ImplVer : uint32_t {
PdbImplVC2 = 19941610, PdbImplVC4 = 19950623, PdbImplVC41 = 19950814, PdbImplVC50 = 19960307,
PdbImplVC98 = 19970604, PdbImplVC70Dep = 19990604, PdbImplVC70 = 20000404, PdbImplVC80 = 20030901,
PdbImplVC110 = 20091201, PdbImplVC140 = 20140508
}
enum PdbRaw_SrcHeaderBlockVer : uint32_t { PdbRaw_SrcHeaderBlockVer::SrcVerOne = 19980827 }
enum PdbRaw_FeatureSig : uint32_t { PdbRaw_FeatureSig::VC110 = PdbImplVC110, PdbRaw_FeatureSig::VC140 = PdbImplVC140, PdbRaw_FeatureSig::NoTypeMerge = 0x4D544F4E, PdbRaw_FeatureSig::MinimalDebugInfo = 0x494E494D }
enum PdbRaw_Features : uint32_t { PdbFeatureNone = 0x0, PdbFeatureContainsIdStream = 0x1, PdbFeatureMinimalDebugInfo = 0x2, PdbFeatureNoTypeMerging = 0x4 }
enum PdbRaw_DbiVer : uint32_t {
PdbDbiVC41 = 930803, PdbDbiV50 = 19960307, PdbDbiV60 = 19970606, PdbDbiV70 = 19990903,
PdbDbiV110 = 20091201
}
enum PdbRaw_TpiVer : uint32_t {
PdbTpiV40 = 19950410, PdbTpiV41 = 19951122, PdbTpiV50 = 19961031, PdbTpiV70 = 19990903,
PdbTpiV80 = 20040203
}
enum PdbRaw_DbiSecContribVer : uint32_t { DbiSecContribVer60 = 0xeffe0000 + 19970605, DbiSecContribV2 = 0xeffe0000 + 20140516 }
enum SpecialStream : uint32_t {
OldMSFDirectory = 0, StreamPDB = 1, StreamTPI = 2, StreamDBI = 3,
StreamIPI = 4, kSpecialStreamCount
}
enum DbgHeaderType : uint16_t {
DbgHeaderType::FPO, DbgHeaderType::Exception, DbgHeaderType::Fixup, DbgHeaderType::OmapToSrc,
DbgHeaderType::OmapFromSrc, DbgHeaderType::SectionHdr, DbgHeaderType::TokenRidMap, DbgHeaderType::Xdata,
DbgHeaderType::Pdata, DbgHeaderType::NewFPO, DbgHeaderType::SectionHdrOrig, DbgHeaderType::Max
}
enum OMFSegDescFlags : uint16_t {
OMFSegDescFlags::None = 0, OMFSegDescFlags::Read = 1 << 0, OMFSegDescFlags::Write = 1 << 1, OMFSegDescFlags::Execute = 1 << 2,
OMFSegDescFlags::AddressIs32Bit = 1 << 3, OMFSegDescFlags::IsSelector = 1 << 8, OMFSegDescFlags::IsAbsoluteAddress = 1 << 9, OMFSegDescFlags::IsGroup = 1 << 10
}
enum raw_error_code {
raw_error_code::unspecified = 1, raw_error_code::feature_unsupported, raw_error_code::invalid_format, raw_error_code::corrupt_file,
raw_error_code::insufficient_buffer, raw_error_code::no_stream, raw_error_code::index_out_of_bounds, raw_error_code::invalid_block_address,
raw_error_code::duplicate_entry, raw_error_code::no_entry, raw_error_code::not_writable, raw_error_code::stream_too_long,
raw_error_code::invalid_tpi_hash
}
enum PDB_ReaderType { PDB_ReaderType::DIA = 0, PDB_ReaderType::Native = 1 }
Specifies which PDB reader implementation is to be used.
enum PDB_TableType {
PDB_TableType::TableInvalid = 0, PDB_TableType::Symbols, PDB_TableType::SourceFiles, PDB_TableType::LineNumbers,
PDB_TableType::SectionContribs, PDB_TableType::Segments, PDB_TableType::InjectedSources, PDB_TableType::FrameData,
PDB_TableType::InputAssemblyFiles, PDB_TableType::Dbg
}
An enumeration indicating the type of data contained in this table.
enum PDB_NameSearchFlags {
NS_Default = 0x0, NS_CaseSensitive = 0x1, NS_CaseInsensitive = 0x2, NS_FileNameExtMatch = 0x4,
NS_Regex = 0x8, NS_UndecoratedName = 0x10, NS_CaseInFileNameExt = NS_CaseInsensitive | NS_FileNameExtMatch, NS_CaseRegex = NS_Regex | NS_CaseSensitive,
NS_CaseInRex = NS_Regex | NS_CaseInsensitive
}
Defines flags used for enumerating child symbols.
enum PDB_Checksum { PDB_Checksum::None = 0, PDB_Checksum::MD5 = 1, PDB_Checksum::SHA1 = 2, PDB_Checksum::SHA256 = 3 }
Specifies the hash algorithm that a source file from a PDB was hashed with.
enum PDB_Machine {
PDB_Machine::Invalid = 0xffff, Unknown = 0x0, PDB_Machine::Am33 = 0x13, PDB_Machine::Amd64 = 0x8664,
PDB_Machine::Arm = 0x1C0, PDB_Machine::Arm64 = 0xaa64, PDB_Machine::ArmNT = 0x1C4, PDB_Machine::Ebc = 0xEBC,
PDB_Machine::x86 = 0x14C, PDB_Machine::Ia64 = 0x200, PDB_Machine::M32R = 0x9041, PDB_Machine::Mips16 = 0x266,
PDB_Machine::MipsFpu = 0x366, PDB_Machine::MipsFpu16 = 0x466, PDB_Machine::PowerPC = 0x1F0, PDB_Machine::PowerPCFP = 0x1F1,
PDB_Machine::R4000 = 0x166, PDB_Machine::SH3 = 0x1A2, PDB_Machine::SH3DSP = 0x1A3, PDB_Machine::SH4 = 0x1A6,
PDB_Machine::SH5 = 0x1A8, PDB_Machine::Thumb = 0x1C2, PDB_Machine::WceMipsV2 = 0x169
}
enum PDB_DataKind {
Unknown, PDB_DataKind::Local, PDB_DataKind::StaticLocal, PDB_DataKind::Param,
PDB_DataKind::ObjectPtr, PDB_DataKind::FileStatic, PDB_DataKind::Global, PDB_DataKind::Member,
PDB_DataKind::StaticMember, PDB_DataKind::Constant
}
These values correspond to the DataKind enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/b2x2t313.aspx.
enum PDB_SymType {
PDB_SymType::None, PDB_SymType::Exe, PDB_SymType::Compiland, PDB_SymType::CompilandDetails,
PDB_SymType::CompilandEnv, PDB_SymType::Function, PDB_SymType::Block, PDB_SymType::Data,
PDB_SymType::Annotation, PDB_SymType::Label, PDB_SymType::PublicSymbol, PDB_SymType::UDT,
PDB_SymType::Enum, PDB_SymType::FunctionSig, PDB_SymType::PointerType, PDB_SymType::ArrayType,
PDB_SymType::BuiltinType, PDB_SymType::Typedef, PDB_SymType::BaseClass, PDB_SymType::Friend,
PDB_SymType::FunctionArg, PDB_SymType::FuncDebugStart, PDB_SymType::FuncDebugEnd, PDB_SymType::UsingNamespace,
PDB_SymType::VTableShape, PDB_SymType::VTable, PDB_SymType::Custom, PDB_SymType::Thunk,
PDB_SymType::CustomType, PDB_SymType::ManagedType, PDB_SymType::Dimension, PDB_SymType::CallSite,
PDB_SymType::InlineSite, PDB_SymType::BaseInterface, PDB_SymType::VectorType, PDB_SymType::MatrixType,
PDB_SymType::HLSLType, PDB_SymType::Caller, PDB_SymType::Callee, PDB_SymType::Export,
PDB_SymType::HeapAllocationSite, PDB_SymType::CoffGroup, PDB_SymType::Inlinee, PDB_SymType::Max
}
These values correspond to the SymTagEnum enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/bkedss5f.aspx.
enum PDB_LocType {
PDB_LocType::Null, PDB_LocType::Static, PDB_LocType::TLS, PDB_LocType::RegRel,
PDB_LocType::ThisRel, PDB_LocType::Enregistered, PDB_LocType::BitField, PDB_LocType::Slot,
PDB_LocType::IlRel, PDB_LocType::MetaData, PDB_LocType::Constant, PDB_LocType::RegRelAliasIndir,
PDB_LocType::Max
}
These values correspond to the LocationType enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/f57kaez3.aspx.
enum PDB_UdtType { PDB_UdtType::Struct, PDB_UdtType::Class, PDB_UdtType::Union, PDB_UdtType::Interface }
These values correspond to the UdtKind enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/wcstk66t.aspx.
enum PDB_StackFrameType : uint16_t {
PDB_StackFrameType::FPO, PDB_StackFrameType::KernelTrap, PDB_StackFrameType::KernelTSS, PDB_StackFrameType::EBP,
PDB_StackFrameType::FrameData, Unknown = 0xffff
}
These values correspond to the StackFrameTypeEnum enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/bc5207xw.aspx.
enum PDB_MemoryType : uint16_t {
PDB_MemoryType::Code, PDB_MemoryType::Data, PDB_MemoryType::Stack, PDB_MemoryType::HeapCode,
PDB_MemoryType::Any = 0xffff
}
These values correspond to the MemoryTypeEnum enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/ms165609.aspx.
enum PDB_BuiltinType {
PDB_BuiltinType::None = 0, PDB_BuiltinType::Void = 1, PDB_BuiltinType::Char = 2, PDB_BuiltinType::WCharT = 3,
PDB_BuiltinType::Int = 6, PDB_BuiltinType::UInt = 7, PDB_BuiltinType::Float = 8, PDB_BuiltinType::BCD = 9,
Bool = 10, PDB_BuiltinType::Long = 13, PDB_BuiltinType::ULong = 14, PDB_BuiltinType::Currency = 25,
PDB_BuiltinType::Date = 26, PDB_BuiltinType::Variant = 27, PDB_BuiltinType::Complex = 28, PDB_BuiltinType::Bitfield = 29,
PDB_BuiltinType::BSTR = 30, PDB_BuiltinType::HResult = 31, PDB_BuiltinType::Char16 = 32, PDB_BuiltinType::Char32 = 33
}
These values correspond to the Basictype enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/4szdtzc3.aspx.
enum PDB_UndnameFlags : uint32_t {
Undname_Complete = 0x0, Undname_NoLeadingUnderscores = 0x1, Undname_NoMsKeywords = 0x2, Undname_NoFuncReturns = 0x4,
Undname_NoAllocModel = 0x8, Undname_NoAllocLang = 0x10, Undname_Reserved1 = 0x20, Undname_Reserved2 = 0x40,
Undname_NoThisType = 0x60, Undname_NoAccessSpec = 0x80, Undname_NoThrowSig = 0x100, Undname_NoMemberType = 0x200,
Undname_NoReturnUDTModel = 0x400, Undname_32BitDecode = 0x800, Undname_NameOnly = 0x1000, Undname_TypeOnly = 0x2000,
Undname_HaveParams = 0x4000, Undname_NoECSU = 0x8000, Undname_NoIdentCharCheck = 0x10000, Undname_NoPTR64 = 0x20000
}
These values correspond to the flags that can be combined to control the return of an undecorated name for a C++ decorated name, and are documented here: https://msdn.microsoft.com/en-us/library/kszfk0fs.aspx.
enum PDB_MemberAccess { PDB_MemberAccess::Private = 1, PDB_MemberAccess::Protected = 2, PDB_MemberAccess::Public = 3 }
enum PDB_VariantType {
Empty, Unknown, Unknown = 0x0, Unknown,
Unknown = 0xffff, Int8, Int16, Int32,
Int64, Single, Double, UInt8,
UInt16, UInt32, UInt64, Bool,
Bool = 10, String
}
Functions
const std::error_category & DIAErrCategory ()
std::error_code make_error_code (dia_error_code E)
const std::error_category & PDBErrCategory ()
std::error_code make_error_code (pdb_error_code E)
void dumpSymbolIdField (raw_ostream &OS, StringRef Name, SymIndexId Value, int Indent, const IPDBSession &Session, PdbSymbolIdField FieldId, PdbSymbolIdField ShowFlags, PdbSymbolIdField RecurseFlags)
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
ArrayRef< EnumEntry< uint16_t > > getOMFSegMapDescFlagNames ()
uint32_t hashStringV1 (StringRef Str)
uint32_t hashStringV2 (StringRef Str)
uint32_t hashBufferV8 (ArrayRef< uint8_t > Data)
Error readSparseBitVector (BinaryStreamReader &Stream, SparseBitVector<> &V)
Error writeSparseBitVector (BinaryStreamWriter &Writer, SparseBitVector<> &Vec)
const std::error_category & RawErrCategory ()
std::error_code make_error_code (raw_error_code E)
Expected< uint32_t > hashTypeRecord (const llvm::codeview::CVType &Type)
Expected< TagRecordHash > hashTagRecord (const codeview::CVType &Type)
Given a CVType referring to a class, structure, union, or enum, compute the hash of its forward decl and full decl.
Error loadDataForPDB (PDB_ReaderType Type, StringRef Path, std::unique_ptr< IPDBSession > &Session)
Error loadDataForEXE (PDB_ReaderType Type, StringRef Path, std::unique_ptr< IPDBSession > &Session)
raw_ostream & operator<< (raw_ostream &OS, const PDB_VariantType &Value)
raw_ostream & operator<< (raw_ostream &OS, const PDB_CallingConv &Conv)
raw_ostream & operator<< (raw_ostream &OS, const PDB_BuiltinType &Type)
raw_ostream & operator<< (raw_ostream &OS, const PDB_DataKind &Data)
raw_ostream & operator<< (raw_ostream &OS, const llvm::codeview::CPURegister &CpuReg)
raw_ostream & operator<< (raw_ostream &OS, const PDB_LocType &Loc)
raw_ostream & operator<< (raw_ostream &OS, const codeview::ThunkOrdinal &Thunk)
raw_ostream & operator<< (raw_ostream &OS, const PDB_Checksum &Checksum)
raw_ostream & operator<< (raw_ostream &OS, const PDB_Lang &Lang)
raw_ostream & operator<< (raw_ostream &OS, const PDB_SymType &Tag)
raw_ostream & operator<< (raw_ostream &OS, const PDB_MemberAccess &Access)
raw_ostream & operator<< (raw_ostream &OS, const PDB_UdtType &Type)
raw_ostream & operator<< (raw_ostream &OS, const PDB_Machine &Machine)
raw_ostream & operator<< (raw_ostream &OS, const Variant &Value)
raw_ostream & operator<< (raw_ostream &OS, const VersionInfo &Version)
raw_ostream & operator<< (raw_ostream &OS, const TagStats &Stats)
raw_ostream & dumpPDBSourceCompression (raw_ostream &OS, uint32_t Compression)
template<typename T >
void dumpSymbolField (raw_ostream &OS, StringRef Name, T Value, int Indent)
Variables
const uint16_t kInvalidStreamIndex = 0xFFFF
const uint32_t MinTpiHashBuckets = 0x1000
const uint32_t MaxTpiHashBuckets = 0x40000
const uint32_t PDBStringTableSignature = 0xEFFEEFFE
Typedef Documentation
IPDBEnumDataStreams
using llvm::pdb::IPDBEnumDataStreams = typedef IPDBEnumChildren<IPDBDataStream>
Definition at line 69 of file PDBTypes.h.
IPDBEnumFrameData
using llvm::pdb::IPDBEnumFrameData = typedef IPDBEnumChildren<IPDBFrameData>
Definition at line 74 of file PDBTypes.h.
IPDBEnumInjectedSources
using llvm::pdb::IPDBEnumInjectedSources = typedef IPDBEnumChildren<IPDBInjectedSource>
Definition at line 72 of file PDBTypes.h.
IPDBEnumLineNumbers
using llvm::pdb::IPDBEnumLineNumbers = typedef IPDBEnumChildren<IPDBLineNumber>
Definition at line 70 of file PDBTypes.h.
IPDBEnumSectionContribs
using llvm::pdb::IPDBEnumSectionContribs = typedef IPDBEnumChildren<IPDBSectionContrib>
Definition at line 73 of file PDBTypes.h.
IPDBEnumSourceFiles
using llvm::pdb::IPDBEnumSourceFiles = typedef IPDBEnumChildren<IPDBSourceFile>
Definition at line 68 of file PDBTypes.h.
IPDBEnumSymbols
using llvm::pdb::IPDBEnumSymbols = typedef IPDBEnumChildren<PDBSymbol>
Definition at line 67 of file PDBTypes.h.
IPDBEnumTables
using llvm::pdb::IPDBEnumTables = typedef IPDBEnumChildren<IPDBTable>
Definition at line 71 of file PDBTypes.h.
PDB_CallingConv
using llvm::pdb::PDB_CallingConv = typedef codeview::CallingConvention
These values correspond to the CV_call_e enumeration, and are documented at the following locations: https://msdn.microsoft.com/en-us/library/b2fc64ek.aspx https://msdn.microsoft.com/en-us/library/windows/desktop/ms680207(v=vs.85).aspx.
Definition at line 218 of file PDBTypes.h.
PDB_Cpu
using llvm::pdb::PDB_Cpu = typedef codeview::CPUType
These values correspond to the CV_CPU_TYPE_e enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/b2fc64ek.aspx.
Definition at line 121 of file PDBTypes.h.
PDB_Lang
using llvm::pdb::PDB_Lang = typedef codeview::SourceLanguage
These values correspond to the CV_CFL_LANG enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/bw3aekw6.aspx.
Definition at line 222 of file PDBTypes.h.
SymIndexId
typedef uint32_t llvm::pdb::SymIndexId
Definition at line 25 of file PDBTypes.h.
TagStats
using llvm::pdb::TagStats = typedef std::unordered_map<PDB_SymType, int>
Definition at line 24 of file PDBExtras.h.
Enumeration Type Documentation
anonymous enum
anonymous enum : unsigned
From https://github.com/Microsoft/microsoft-pdb/blob/master/PDB/dbi/gsi.cpp.
Enumerator
IPHR_HASH
Definition at line 45 of file GlobalsStream.h.
DbgHeaderType
enum llvm::pdb::DbgHeaderType : uint16_t strong
Enumerator
FPO
Exception
Fixup
OmapToSrc
OmapFromSrc
SectionHdr
TokenRidMap
Xdata
Pdata
NewFPO
SectionHdrOrig
Max
Definition at line 86 of file RawConstants.h.
dia_error_code
enum llvm::pdb::dia_error_code strong
Enumerator
unspecified
could_not_create_impl
invalid_file_format
invalid_parameter
already_loaded
debug_info_mismatch
Definition at line 17 of file DIAError.h.
OMFSegDescFlags
enum llvm::pdb::OMFSegDescFlags : uint16_t strong
Enumerator
None
Read
Write
Execute
AddressIs32Bit
IsSelector
IsAbsoluteAddress
IsGroup
Definition at line 101 of file RawConstants.h.
PDB_BuiltinType
enum llvm::pdb::PDB_BuiltinType strong
These values correspond to the Basictype enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/4szdtzc3.aspx.
Enumerator
None
Void
Char
WCharT
Int
UInt
Float
BCD
Bool
Long
ULong
Currency
Date
Variant
Complex
Bitfield
BSTR
HResult
Char16
Char32
Definition at line 333 of file PDBTypes.h.
PDB_Checksum
enum llvm::pdb::PDB_Checksum strong
Specifies the hash algorithm that a source file from a PDB was hashed with.
This corresponds to the CV_SourceChksum_t enumeration and are documented here: https://msdn.microsoft.com/en-us/library/e96az21x.aspx
Enumerator
None
MD5
SHA1
SHA256
Definition at line 117 of file PDBTypes.h.
PDB_DataKind
enum llvm::pdb::PDB_DataKind strong
These values correspond to the DataKind enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/b2x2t313.aspx.
Enumerator
Unknown
Local
StaticLocal
Param
ObjectPtr
FileStatic
Global
Member
StaticMember
Constant
Definition at line 226 of file PDBTypes.h.
pdb_error_code
enum llvm::pdb::pdb_error_code strong
Enumerator
invalid_utf8_path
dia_sdk_not_present
dia_failed_loading
signature_out_of_date
no_matching_pch
unspecified
Definition at line 18 of file GenericError.h.
PDB_LocType
enum llvm::pdb::PDB_LocType strong
These values correspond to the LocationType enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/f57kaez3.aspx.
Enumerator
Null
Static
TLS
RegRel
ThisRel
Enregistered
BitField
Slot
IlRel
MetaData
Constant
RegRelAliasIndir
Max
Definition at line 290 of file PDBTypes.h.
PDB_Machine
enum llvm::pdb::PDB_Machine strong
Enumerator
Invalid
Unknown
Am33
Amd64
Arm
Arm64
ArmNT
Ebc
x86
Ia64
M32R
Mips16
MipsFpu
MipsFpu16
PowerPC
PowerPCFP
R4000
SH3
SH3DSP
SH4
SH5
Thumb
WceMipsV2
Definition at line 123 of file PDBTypes.h.
PDB_MemberAccess
enum llvm::pdb::PDB_MemberAccess strong
Enumerator
Private
Protected
Public
Definition at line 382 of file PDBTypes.h.
PDB_MemoryType
enum llvm::pdb::PDB_MemoryType : uint16_t strong
These values correspond to the MemoryTypeEnum enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/ms165609.aspx.
Enumerator
Code
Data
Stack
HeapCode
Any
Definition at line 323 of file PDBTypes.h.
PDB_NameSearchFlags
enum llvm::pdb::PDB_NameSearchFlags
Defines flags used for enumerating child symbols.
This corresponds to the NameSearchOptions enumeration which is documented here: https://msdn.microsoft.com/en-us/library/yat28ads.aspx
Enumerator
NS_Default
NS_CaseSensitive
NS_CaseInsensitive
NS_FileNameExtMatch
NS_Regex
NS_UndecoratedName
NS_CaseInFileNameExt
NS_CaseRegex
NS_CaseInRex
Definition at line 100 of file PDBTypes.h.
PDB_ReaderType
enum llvm::pdb::PDB_ReaderType strong
Specifies which PDB reader implementation is to be used.
Only a value of PDB_ReaderType::DIA is currently supported, but Native is in the works.
Enumerator
DIA
Native
Definition at line 78 of file PDBTypes.h.
PDB_StackFrameType
enum llvm::pdb::PDB_StackFrameType : uint16_t strong
These values correspond to the StackFrameTypeEnum enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/bc5207xw.aspx.
Enumerator
FPO
KernelTrap
KernelTSS
EBP
FrameData
Unknown
Definition at line 312 of file PDBTypes.h.
PDB_SymType
enum llvm::pdb::PDB_SymType strong
These values correspond to the SymTagEnum enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/bkedss5f.aspx.
Enumerator
None
Exe
Compiland
CompilandDetails
CompilandEnv
Function
Block
Data
Annotation
Label
PublicSymbol
UDT
Enum
FunctionSig
PointerType
ArrayType
BuiltinType
Typedef
BaseClass
Friend
FunctionArg
FuncDebugStart
FuncDebugEnd
UsingNamespace
VTableShape
VTable
Custom
Thunk
CustomType
ManagedType
Dimension
CallSite
InlineSite
BaseInterface
VectorType
MatrixType
HLSLType
Caller
Callee
Export
HeapAllocationSite
CoffGroup
Inlinee
Max
Definition at line 241 of file PDBTypes.h.
PDB_TableType
enum llvm::pdb::PDB_TableType strong
An enumeration indicating the type of data contained in this table.
Enumerator
TableInvalid
Symbols
SourceFiles
LineNumbers
SectionContribs
Segments
InjectedSources
FrameData
InputAssemblyFiles
Dbg
Definition at line 84 of file PDBTypes.h.
PDB_UdtType
enum llvm::pdb::PDB_UdtType strong
These values correspond to the UdtKind enumeration, and are documented here: https://msdn.microsoft.com/en-us/library/wcstk66t.aspx.
Enumerator
Struct
Class
Union
Interface
Definition at line 308 of file PDBTypes.h.
PDB_UndnameFlags
enum llvm::pdb::PDB_UndnameFlags : uint32_t
These values correspond to the flags that can be combined to control the return of an undecorated name for a C++ decorated name, and are documented here: https://msdn.microsoft.com/en-us/library/kszfk0fs.aspx.
Enumerator
Undname_Complete
Undname_NoLeadingUnderscores
Undname_NoMsKeywords
Undname_NoFuncReturns
Undname_NoAllocModel
Undname_NoAllocLang
Undname_Reserved1
Undname_Reserved2
Undname_NoThisType
Undname_NoAccessSpec
Undname_NoThrowSig
Undname_NoMemberType
Undname_NoReturnUDTModel
Undname_32BitDecode
Undname_NameOnly
Undname_TypeOnly
Undname_HaveParams
Undname_NoECSU
Undname_NoIdentCharCheck
Undname_NoPTR64
Definition at line 359 of file PDBTypes.h.
PDB_VariantType
enum llvm::pdb::PDB_VariantType
Enumerator
Empty
Unknown
Unknown
Unknown
Unknown
Int8
Int16
Int32
Int64
Single
Double
UInt8
UInt16
UInt32
UInt64
Bool
Bool
String
Definition at line 391 of file PDBTypes.h.
PdbRaw_DbiSecContribVer
enum llvm::pdb::PdbRaw_DbiSecContribVer : uint32_t
Enumerator
DbiSecContribVer60
DbiSecContribV2
Definition at line 67 of file RawConstants.h.
PdbRaw_DbiVer
enum llvm::pdb::PdbRaw_DbiVer : uint32_t
Enumerator
PdbDbiVC41
PdbDbiV50
PdbDbiV60
PdbDbiV70
PdbDbiV110
Definition at line 51 of file RawConstants.h.
PdbRaw_Features
enum llvm::pdb::PdbRaw_Features : uint32_t
Enumerator
PdbFeatureNone
PdbFeatureContainsIdStream
PdbFeatureMinimalDebugInfo
PdbFeatureNoTypeMerging
Definition at line 43 of file RawConstants.h.
PdbRaw_FeatureSig
enum llvm::pdb::PdbRaw_FeatureSig : uint32_t strong
Enumerator
VC110
VC140
NoTypeMerge
MinimalDebugInfo
Definition at line 36 of file RawConstants.h.
PdbRaw_ImplVer
enum llvm::pdb::PdbRaw_ImplVer : uint32_t
Enumerator
PdbImplVC2
PdbImplVC4
PdbImplVC41
PdbImplVC50
PdbImplVC98
PdbImplVC70Dep
PdbImplVC70
PdbImplVC80
PdbImplVC110
PdbImplVC140
Definition at line 21 of file RawConstants.h.
PdbRaw_SrcHeaderBlockVer
enum llvm::pdb::PdbRaw_SrcHeaderBlockVer : uint32_t strong
Enumerator
SrcVerOne
Definition at line 34 of file RawConstants.h.
PdbRaw_TpiVer
enum llvm::pdb::PdbRaw_TpiVer : uint32_t
Enumerator
PdbTpiV40
PdbTpiV41
PdbTpiV50
PdbTpiV70
PdbTpiV80
Definition at line 59 of file RawConstants.h.
PdbSymbolIdField
enum llvm::pdb::PdbSymbolIdField : uint32_t strong
Enumerator
None
SymIndexId
LexicalParent
ClassParent
Type
UnmodifiedType
All
Definition at line 28 of file IPDBRawSymbol.h.
raw_error_code
enum llvm::pdb::raw_error_code strong
Enumerator
unspecified
feature_unsupported
invalid_format
corrupt_file
insufficient_buffer
no_stream
index_out_of_bounds
invalid_block_address
duplicate_entry
no_entry
not_writable
stream_too_long
invalid_tpi_hash
Definition at line 18 of file RawError.h.
SpecialStream
enum llvm::pdb::SpecialStream : uint32_t
Enumerator
OldMSFDirectory
StreamPDB
StreamTPI
StreamDBI
StreamIPI
kSpecialStreamCount
Definition at line 72 of file RawConstants.h.
Function Documentation
DIAErrCategory()
const std::error_category & llvm::pdb::DIAErrCategory ()
Definition at line 35 of file DIAError.cpp.
References DIACategory, and llvm::pdb::DIAError::ID.
Referenced by make_error_code().
dumpPDBSourceCompression()
raw_ostream & llvm::pdb::dumpPDBSourceCompression (raw_ostream & OS, uint32_t Compression)
Definition at line 323 of file PDBExtras.cpp.
References CASE_OUTPUT_ENUM_CLASS_NAME, CASE_OUTPUT_ENUM_CLASS_STR, and llvm::None.
dumpSymbolField()
template<typename T > void llvm::pdb::dumpSymbolField (raw_ostream & OS, StringRef Name, T Value, int Indent)
Definition at line 48 of file PDBExtras.h.
References llvm::raw_ostream::indent().
Referenced by llvm::pdb::NativeCompilandSymbol::dump(), llvm::pdb::NativeTypeArray::dump(), llvm::pdb::NativeTypeTypedef::dump(), llvm::pdb::NativeSymbolEnumerator::dump(), llvm::pdb::NativeRawSymbol::dump(), llvm::pdb::NativeTypeVTShape::dump(), llvm::pdb::NativeTypePointer::dump(), llvm::pdb::NativeTypeEnum::dump(), llvm::pdb::NativeTypeUDT::dump(), and llvm::pdb::NativeTypeFunctionSig::dump().
dumpSymbolIdField()
void llvm::pdb::dumpSymbolIdField (raw_ostream & OS, StringRef Name, SymIndexId Value, int Indent, const IPDBSession & Session, PdbSymbolIdField FieldId, PdbSymbolIdField ShowFlags, PdbSymbolIdField RecurseFlags)
Definition at line 185 of file PDBSymbol.cpp.
References llvm::pdb::IPDBSession::getSymbolById(), llvm::raw_ostream::indent(), None, and SymIndexId.
Referenced by llvm::pdb::NativeCompilandSymbol::dump(), llvm::pdb::NativeTypeArray::dump(), llvm::pdb::NativeTypeTypedef::dump(), llvm::pdb::NativeSymbolEnumerator::dump(), llvm::pdb::NativeRawSymbol::dump(), llvm::pdb::NativeTypeVTShape::dump(), llvm::pdb::NativeTypePointer::dump(), llvm::pdb::NativeTypeEnum::dump(), llvm::pdb::NativeTypeUDT::dump(), and llvm::pdb::NativeTypeFunctionSig::dump().
getOMFSegMapDescFlagNames()
ArrayRef< EnumEntry< uint16_t > > llvm::pdb::getOMFSegMapDescFlagNames ()
Definition at line 33 of file EnumTables.cpp.
References llvm::makeArrayRef().
hashBufferV8()
uint32_t llvm::pdb::hashBufferV8 (ArrayRef< uint8_t > Data)
Definition at line 80 of file Hash.cpp.
References llvm::JamCRC::getCRC(), and llvm::JamCRC::update().
Referenced by getHashForUdt().
hashStringV1()
uint32_t llvm::pdb::hashStringV1 (StringRef Str)
Definition at line 20 of file Hash.cpp.
References llvm::StringRef::data(), Size, and llvm::StringRef::size().
Referenced by llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::pdb::TpiStream::findRecordsByName(), llvm::pdb::GlobalsStream::findRecordsByName(), getHashForUdt(), llvm::pdb::PDBStringTable::getIDForString(), getSourceLineHash(), getTagRecordHashForUdt(), llvm::pdb::NamedStreamMapTraits::hashLookupKey(), and llvm::pdb::NamedStreamMap::hashString().
hashStringV2()
uint32_t llvm::pdb::hashStringV2 (StringRef Str)
Definition at line 56 of file Hash.cpp.
References llvm::StringRef::begin(), and llvm::StringRef::end().
Referenced by llvm::pdb::PDBStringTable::getIDForString().
hashTagRecord()
Expected< TagRecordHash > llvm::pdb::hashTagRecord (const codeview::CVType & Type)
Given a CVType referring to a class, structure, union, or enum, compute the hash of its forward decl and full decl.
Definition at line 88 of file TpiHashing.cpp.
References assert(), llvm::inconvertibleErrorCode(), and llvm::codeview::CVRecord< Kind >::kind().
Referenced by llvm::pdb::TpiStream::findFullDeclForForwardRef().
hashTypeRecord()
Expected< uint32_t > llvm::pdb::hashTypeRecord (const llvm::codeview::CVType & Type)
Definition at line 105 of file TpiHashing.cpp.
References llvm::codeview::CVRecord< Kind >::data(), llvm::JamCRC::getCRC(), llvm::codeview::CVRecord< Kind >::kind(), and llvm::JamCRC::update().
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
llvm::pdb::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
loadDataForEXE()
Error llvm::pdb::loadDataForEXE (PDB_ReaderType Type, StringRef Path, std::unique_ptr< IPDBSession > & Session)
Definition at line 43 of file PDB.cpp.
References llvm::pdb::DIASession::createFromExe(), llvm::pdb::NativeSession::createFromExe(), dia_sdk_not_present, and Native.
loadDataForPDB()
Error llvm::pdb::loadDataForPDB (PDB_ReaderType Type, StringRef Path, std::unique_ptr< IPDBSession > & Session)
Definition at line 23 of file PDB.cpp.
References llvm::pdb::DIASession::createFromPdb(), llvm::pdb::NativeSession::createFromPdb(), dia_sdk_not_present, llvm::errorCodeToError(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFileOrSTDIN(), and Native.
make_error_code() [1/3]
std::error_code llvm::pdb::make_error_code (dia_error_code E) inline
Definition at line 37 of file DIAError.h.
References DIAErrCategory().
make_error_code() [2/3]
std::error_code llvm::pdb::make_error_code (pdb_error_code E) inline
Definition at line 38 of file GenericError.h.
References PDBErrCategory().
make_error_code() [3/3]
std::error_code llvm::pdb::make_error_code (raw_error_code E) inline
Definition at line 45 of file RawError.h.
References RawErrCategory().
operator<<() [1/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_VariantType & Value)
Definition at line 24 of file PDBExtras.cpp.
References Bool, CASE_OUTPUT_ENUM_CLASS_NAME, Double, Int16, Int32, Int64, Int8, Single, UInt16, UInt32, UInt64, and UInt8.
operator<<() [2/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_CallingConv & Conv)
Definition at line 71 of file PDBExtras.cpp.
References CASE_OUTPUT_ENUM_CLASS_STR, and Generic.
operator<<() [3/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_BuiltinType & Type)
Definition at line 44 of file PDBExtras.cpp.
References BCD, Bitfield, Bool, BSTR, CASE_OUTPUT_ENUM_CLASS_NAME, Char, Char16, Char32, Complex, Currency, Date, Long, llvm::None, ULong, and WCharT.
operator<<() [4/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_DataKind & Data)
Definition at line 103 of file PDBExtras.cpp.
References CASE_OUTPUT_ENUM_CLASS_STR, FileStatic, Global, Local, Member, ObjectPtr, Param, StaticLocal, StaticMember, and Unknown.
operator<<() [5/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const llvm::codeview::CPURegister & CpuReg)
Definition at line 119 of file PDBExtras.cpp.
References llvm::codeview::ARM64, llvm::codeview::CPURegister::Cpu, and llvm::codeview::CPURegister::Reg.
operator<<() [6/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_LocType & Loc)
Definition at line 154 of file PDBExtras.cpp.
References BitField, CASE_OUTPUT_ENUM_CLASS_STR, Enregistered, IlRel, MetaData, RegRel, RegRelAliasIndir, Slot, ThisRel, and TLS.
operator<<() [7/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const codeview::ThunkOrdinal & Thunk)
Definition at line 174 of file PDBExtras.cpp.
References CASE_OUTPUT_ENUM_CLASS_NAME.
operator<<() [8/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_Checksum & Checksum)
Definition at line 188 of file PDBExtras.cpp.
References CASE_OUTPUT_ENUM_CLASS_NAME, and llvm::None.
operator<<() [9/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_Lang & Lang)
Definition at line 199 of file PDBExtras.cpp.
References C, CASE_OUTPUT_ENUM_CLASS_NAME, CASE_OUTPUT_ENUM_CLASS_STR, llvm::codeview::Cobol, llvm::codeview::Cpp, llvm::codeview::CSharp, llvm::codeview::Cvtpgd, llvm::codeview::Cvtres, D, llvm::codeview::Fortran, llvm::codeview::HLSL, llvm::codeview::ILAsm, llvm::codeview::Java, llvm::codeview::JScript, llvm::codeview::Link, llvm::codeview::Masm, llvm::codeview::Swift, and llvm::codeview::VB.
operator<<() [10/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_SymType & Tag)
Definition at line 224 of file PDBExtras.cpp.
References Annotation, BaseClass, BaseInterface, Block, BuiltinType, Callee, Caller, CASE_OUTPUT_ENUM_CLASS_NAME, CoffGroup, Compiland, CompilandDetails, CompilandEnv, CustomType, llvm::Data, Dimension, Enum, Exe, Export, FuncDebugEnd, FuncDebugStart, FunctionArg, FunctionSig, HeapAllocationSite, HLSLType, Inlinee, InlineSite, Label, ManagedType, MatrixType, PublicSymbol, Thunk, Typedef, UDT, UsingNamespace, VTable, and VTableShape.
operator<<() [11/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_MemberAccess & Access)
Definition at line 274 of file PDBExtras.cpp.
References CASE_OUTPUT_ENUM_CLASS_STR.
operator<<() [12/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_UdtType & Type)
Definition at line 284 of file PDBExtras.cpp.
References CASE_OUTPUT_ENUM_CLASS_STR, Struct, and Union.
operator<<() [13/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const PDB_Machine & Machine)
Definition at line 294 of file PDBExtras.cpp.
References Am33, Amd64, Arm, ArmNT, CASE_OUTPUT_ENUM_CLASS_NAME, Ebc, Mips16, MipsFpu, MipsFpu16, PowerPC, PowerPCFP, R4000, SH5, WceMipsV2, and x86.
operator<<() [14/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const Variant & Value)
Definition at line 338 of file PDBExtras.cpp.
References Bool, llvm::pdb::Variant::Bool, Double, llvm::pdb::Variant::Double, Int16, llvm::pdb::Variant::Int16, Int32, llvm::pdb::Variant::Int32, Int64, llvm::pdb::Variant::Int64, Int8, llvm::pdb::Variant::Int8, Single, llvm::pdb::Variant::Single, llvm::String, llvm::pdb::Variant::String, llvm::pdb::Variant::Type, UInt16, llvm::pdb::Variant::UInt16, UInt32, llvm::pdb::Variant::UInt32, UInt64, llvm::pdb::Variant::UInt64, UInt8, llvm::pdb::Variant::UInt8, and llvm::pdb::Variant::Value.
operator<<() [15/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const VersionInfo & Version)
Definition at line 382 of file PDBExtras.cpp.
References llvm::pdb::VersionInfo::Build, llvm::pdb::VersionInfo::Major, and llvm::pdb::VersionInfo::Minor.
operator<<() [16/16]
raw_ostream & llvm::pdb::operator<< (raw_ostream & OS, const TagStats & Stats)
Definition at line 388 of file PDBExtras.cpp.
PDBErrCategory()
const std::error_category & llvm::pdb::PDBErrCategory ()
Definition at line 46 of file GenericError.cpp.
References llvm::pdb::PDBError::ID, and PDBCategory.
Referenced by make_error_code().
RawErrCategory()
const std::error_category & llvm::pdb::RawErrCategory ()
Definition at line 51 of file RawError.cpp.
References llvm::pdb::RawError::ID, and RawCategory.
Referenced by make_error_code().
readSparseBitVector()
Error llvm::pdb::readSparseBitVector (BinaryStreamReader & Stream, SparseBitVector<> & V)
Definition at line 24 of file HashTable.cpp.
References corrupt_file, I, llvm::joinErrors(), llvm::BinaryStreamReader::readInteger(), llvm::SparseBitVector< ElementSize >::set(), and llvm::Error::success().
Referenced by llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::load().
writeSparseBitVector()
Error llvm::pdb::writeSparseBitVector (BinaryStreamWriter & Writer, SparseBitVector<> & Vec)
Definition at line 46 of file HashTable.cpp.
References llvm::alignTo(), corrupt_file, llvm::SparseBitVector< ElementSize >::find_last(), I, llvm::joinErrors(), llvm::Error::success(), llvm::SparseBitVector< ElementSize >::test(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::commit().
Variable Documentation
kInvalidStreamIndex
const uint16_t llvm::pdb::kInvalidStreamIndex = 0xFFFF
Definition at line 19 of file RawConstants.h.
Referenced by llvm::pdb::DbiStreamBuilder::addSectionContrib(), llvm::pdb::TpiStreamBuilder::addTypeRecord(), llvm::pdb::TpiStreamBuilder::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::pdb::PDBFile::createIndexedStream(), llvm::pdb::DbiModuleDescriptorBuilder::finalize(), llvm::pdb::DbiModuleDescriptorBuilder::finalizeMsfLayout(), llvm::pdb::DbiStream::getDebugStreamIndex(), llvm::pdb::DbiStream::getECName(), llvm::pdb::TpiStreamBuilder::getRecordCount(), llvm::pdb::GSIStreamBuilder::getRecordStreamIdx(), llvm::pdb::ModuleDebugStreamRef::reload(), and llvm::pdb::TpiStream::reload().
MaxTpiHashBuckets
const uint32_t llvm::pdb::MaxTpiHashBuckets = 0x40000
Definition at line 301 of file RawTypes.h.
Referenced by llvm::pdb::TpiStreamBuilder::addTypeRecord(), llvm::pdb::TpiStreamBuilder::finalizeMsfLayout(), and llvm::pdb::TpiStream::reload().
MinTpiHashBuckets
const uint32_t llvm::pdb::MinTpiHashBuckets = 0x1000
Definition at line 300 of file RawTypes.h.
Referenced by llvm::pdb::TpiStream::reload().
PDBStringTableSignature
const uint32_t llvm::pdb::PDBStringTableSignature = 0xEFFEEFFE
Definition at line 318 of file RawTypes.h.
Referenced by llvm::pdb::PDBStringTable::getSignature().