LLVM: llvm::sys::fs::detail Namespace Reference
llvm::sys::fs::detail Namespace Reference
Classes
struct DirIterState
Keeps state for the directory_iterator.
struct RecDirIterState
Keeps state for the recursive_directory_iterator.
Functions
std::error_code directory_iterator_construct (DirIterState &, StringRef, bool)
std::error_code directory_iterator_increment (DirIterState &)
std::error_code directory_iterator_destruct (DirIterState &)
Function Documentation
directory_iterator_construct()
std::error_code llvm::sys::fs::detail::directory_iterator_construct (DirIterState & , StringRef , bool)
Referenced by llvm::sys::fs::directory_iterator::directory_iterator().
directory_iterator_destruct()
std::error_code llvm::sys::fs::detail::directory_iterator_destruct (DirIterState &)
Referenced by llvm::sys::fs::detail::DirIterState::~DirIterState().
directory_iterator_increment()
std::error_code llvm::sys::fs::detail::directory_iterator_increment (DirIterState &)
Referenced by llvm::sys::fs::directory_iterator::increment().