LLVM: llvm::cl Namespace Reference
llvm::cl Namespace Reference
cl Namespace - This namespace contains all of the command line option processing machinery.
Namespaces
detail
Classes
class alias
struct aliasopt
struct applicator
struct applicator< char[n]>
struct applicator< const char[n]>
struct applicator< FormattingFlags >
struct applicator< MiscFlags >
struct applicator< NumOccurrencesFlag >
struct applicator< OptionHidden >
struct applicator< StringRef >
struct applicator< ValueExpected >
class basic_parser
class basic_parser_impl
class bits
class bits_storage
class bits_storage< DataType, bool >
struct cat
struct cb
struct desc
struct extrahelp
class generic_parser_base
struct GenericOptionValue
struct initializer
class list
class list_storage
class list_storage< DataType, bool >
struct LocationClass
struct multi_val
class opt
class opt_storage
class opt_storage< DataType, false, false >
class opt_storage< DataType, false, true >
class Option
class OptionCategory
struct OptionDiffPrinter
struct OptionDiffPrinter< DT, DT >
struct OptionEnumValue
struct OptionValue
struct OptionValue< cl::boolOrDefault >
struct OptionValue< std::string >
struct OptionValueBase
struct OptionValueBase< DataType, false >
class OptionValueCopy
class parser
class parser< bool >
class parser< boolOrDefault >
class parser< char >
class parser< double >
class parser< float >
class parser< int >
class parser< long >
class parser< long long >
class parser< std::string >
class parser< unsigned >
class parser< unsigned long >
class parser< unsigned long long >
struct sub
class SubCommand
struct value_desc
class ValuesClass
Typedefs
using VersionPrinterTy = std::function< void(raw_ostream &)>
using TokenizerCallback = void(*)(StringRef Source, StringSaver &Saver, SmallVectorImpl< const char * > &NewArgv, bool MarkEOLs)
String tokenization function type.
Enumerations
enum NumOccurrencesFlag {
Optional = 0x00, ZeroOrMore = 0x01, Required = 0x02, OneOrMore = 0x03,
ConsumeAfter = 0x04
}
enum ValueExpected { ValueOptional = 0x01, ValueRequired = 0x02, ValueDisallowed = 0x03 }
enum OptionHidden { NotHidden = 0x00, Hidden = 0x01, ReallyHidden = 0x02 }
enum FormattingFlags { NormalFormatting = 0x00, Positional = 0x01, Prefix = 0x02, AlwaysPrefix = 0x03 }
enum MiscFlags {
CommaSeparated = 0x01, PositionalEatsArgs = 0x02, Sink = 0x04, Grouping = 0x08,
DefaultOption = 0x10
}
enum boolOrDefault { BOU_UNSET, BOU_TRUE, BOU_FALSE }
Functions
bool ParseCommandLineOptions (int argc, const char *const *argv, StringRef Overview="", raw_ostream *Errs=nullptr, const char *EnvVar=nullptr, bool LongOptionsUseDoubleDash=false)
void ParseEnvironmentOptions (const char *progName, const char *envvar, const char *Overview="")
ParseEnvironmentOptions - An alternative entry point to the CommandLine library, which allows you to read the program's name from the caller (as PROGNAME) and its command-line arguments from an environment variable (whose name is given in ENVVAR).
void SetVersionPrinter (VersionPrinterTy func)
===------------------------------------------------------------------—===// SetVersionPrinter - Override the default (LLVM specific) version printer used to print out the version when –version is given on the command line.
void AddExtraVersionPrinter (VersionPrinterTy func)
===------------------------------------------------------------------—===// AddExtraVersionPrinter - Add an extra printer to use in addition to the default one.
void PrintOptionValues ()
void AddLiteralOption (Option &O, StringRef Name)
Adds a new option for parsing and provides the option it refers to.
template<class Ty >
initializer< Ty > init (const Ty &Val)
template<class Ty >
LocationClass< Ty > location (Ty &L)
template<typename F >
cb< typename detail::callback_traits< F >::result_type, typename detail::callback_traits< F >::arg_type > callback (F CB)
template<typename... OptsTy>
ValuesClass values (OptsTy... Options)
Helper to build a ValuesClass by forwarding a variable number of arguments as an initializer list to the ValuesClass constructor.
template<class ParserClass , class DT >
void printOptionDiff (const Option &O, const generic_parser_base &P, const DT &V, const OptionValue< DT > &Default, size_t GlobalWidth)
template<class ParserClass , class ValDT >
void printOptionDiff (const Option &O, const basic_parser< typename ParserClass::parser_data_type > &P, const ValDT &V, const OptionValue< ValDT > &Default, size_t GlobalWidth)
template<class Opt , class Mod , class... Mods>
void apply (Opt *O, const Mod &M, const Mods &... Ms)
template<class Opt , class Mod >
void apply (Opt *O, const Mod &M)
void PrintVersionMessage ()
Utility function for printing version number.
void PrintHelpMessage (bool Hidden=false, bool Categorized=false)
This function just prints the help message, exactly the same way as if the -help or -help-hidden option had been given on the command line.
StringMap< Option * > & getRegisteredOptions (SubCommand &Sub= *TopLevelSubCommand)
Use this to get a StringMap to all registered named options (e.g.
iterator_range< typename SmallPtrSet< SubCommand *, 4 >::iterator > getRegisteredSubcommands ()
Use this to get all registered SubCommands from the provided parser.
void TokenizeGNUCommandLine (StringRef Source, StringSaver &Saver, SmallVectorImpl< const char *> &NewArgv, bool MarkEOLs=false)
Tokenizes a command line that can contain escapes and quotes.
void TokenizeWindowsCommandLine (StringRef Source, StringSaver &Saver, SmallVectorImpl< const char *> &NewArgv, bool MarkEOLs=false)
Tokenizes a Windows command line which may contain quotes and escaped quotes.
void tokenizeConfigFile (StringRef Source, StringSaver &Saver, SmallVectorImpl< const char *> &NewArgv, bool MarkEOLs=false)
Tokenizes content of configuration file.
bool readConfigFile (StringRef CfgFileName, StringSaver &Saver, SmallVectorImpl< const char *> &Argv)
Reads command line options from the given configuration file.
bool ExpandResponseFiles (StringSaver &Saver, TokenizerCallback Tokenizer, SmallVectorImpl< const char *> &Argv, bool MarkEOLs=false, bool RelativeNames=false, llvm::vfs::FileSystem &FS= *llvm::vfs::getRealFileSystem(), llvm::Optional< llvm::StringRef > CurrentDir=llvm::None)
Expand response files on a command line recursively using the given StringSaver and tokenization strategy.
void HideUnrelatedOptions (cl::OptionCategory &Category, SubCommand &Sub= *TopLevelSubCommand)
Mark all options not part of this category as cl::ReallyHidden.
void HideUnrelatedOptions (ArrayRef< const cl::OptionCategory *> Categories, SubCommand &Sub= *TopLevelSubCommand)
Mark all options not part of the categories as cl::ReallyHidden.
void ResetAllOptionOccurrences ()
Reset all command line options to a state that looks as if they have never appeared on the command line.
void ResetCommandLineParser ()
Reset the command line parser back to its initial state.
bool ProvidePositionalOption (Option *Handler, StringRef Arg, int i)
Parses Arg into the option handler Handler.
Variables
OptionCategory GeneralCategory
ManagedStatic< SubCommand > TopLevelSubCommand
ManagedStatic< SubCommand > AllSubCommands
Detailed Description
cl Namespace - This namespace contains all of the command line option processing machinery.
It is intentionally a short name to make qualified usage concise.
Typedef Documentation
TokenizerCallback
using llvm::cl::TokenizerCallback = typedef void (*)(StringRef Source, StringSaver &Saver, SmallVectorImpl<const char *> &NewArgv, bool MarkEOLs)
String tokenization function type.
Should be compatible with either Windows or Unix command line tokenizers.
Definition at line 2035 of file CommandLine.h.
VersionPrinterTy
using llvm::cl::VersionPrinterTy = typedef std::function<void(raw_ostream &)>
Definition at line 83 of file CommandLine.h.
Enumeration Type Documentation
boolOrDefault
enum llvm::cl::boolOrDefault
Enumerator
BOU_UNSET
BOU_TRUE
BOU_FALSE
Definition at line 618 of file CommandLine.h.
FormattingFlags
enum llvm::cl::FormattingFlags
Enumerator
NormalFormatting
Positional
Prefix
AlwaysPrefix
Definition at line 166 of file CommandLine.h.
MiscFlags
enum llvm::cl::MiscFlags
Enumerator
CommaSeparated
PositionalEatsArgs
Sink
Grouping
DefaultOption
Definition at line 173 of file CommandLine.h.
NumOccurrencesFlag
enum llvm::cl::NumOccurrencesFlag
Enumerator
Optional
ZeroOrMore
Required
OneOrMore
ConsumeAfter
Definition at line 123 of file CommandLine.h.
OptionHidden
enum llvm::cl::OptionHidden
Enumerator
NotHidden
Hidden
ReallyHidden
Definition at line 146 of file CommandLine.h.
ValueExpected
enum llvm::cl::ValueExpected
Enumerator
ValueOptional
ValueRequired
ValueDisallowed
Definition at line 139 of file CommandLine.h.
Function Documentation
AddExtraVersionPrinter()
void llvm::cl::AddExtraVersionPrinter (VersionPrinterTy func)
===------------------------------------------------------------------—===// AddExtraVersionPrinter - Add an extra printer to use in addition to the default one.
This can be called multiple times, and each time it adds a new function to the list which will be called after the basic LLVM version printing is complete. Each can then add additional information specific to the tool.
Definition at line 2542 of file CommandLine.cpp.
AddLiteralOption()
void llvm::cl::AddLiteralOption (Option & O, StringRef Name)
Adds a new option for parsing and provides the option it refers to.
Parameters
O pointer to the option
Name the string name for the option to handle during parsing
Literal options are used by some parsers to register special option values. This is how the PassNameParser registers pass names for opt.
Definition at line 436 of file CommandLine.cpp.
Referenced by llvm::cl::parser< const PassInfo *>::addLiteralOption().
apply() [1/2]
template<class Opt , class Mod , class... Mods> void llvm::cl::apply (Opt * O, const Mod & M, const Mods &... Ms)
Definition at line 1301 of file CommandLine.h.
References llvm::cl::applicator< Mod >::opt().
Referenced by llvm::GCNSubtarget::adjustSchedDependency(), llvm::cl::alias::alias(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::createCopyConstrainDAGMutation(), llvm::LegalizeRuleSet::fallback(), fuseInstructionPair(), llvm::handleErrorImpl(), llvm::cl::list< DataType, StorageClass, ParserClass >::list(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::ScheduleDAGMILive::scheduleMI(), and swapAntiDependences().
apply() [2/2]
template<class Opt , class Mod > void llvm::cl::apply (Opt * O, const Mod & M)
Definition at line 1306 of file CommandLine.h.
References llvm::cl::applicator< Mod >::opt().
callback()
template<typename F > cb<typename detail::callback_traits<F>::result_type, typename detail::callback_traits<F>::arg_type> llvm::cl::callback (F CB)
Definition at line 505 of file CommandLine.h.
Referenced by llvm::function_ref< Ret(Params...)>::operator bool(), and llvm::function_ref< Ret(Params...)>::operator()().
ExpandResponseFiles()
bool llvm::cl::ExpandResponseFiles (StringSaver & Saver, TokenizerCallback Tokenizer, SmallVectorImpl< const char *> & Argv, bool MarkEOLs = false, bool RelativeNames = false, llvm::vfs::FileSystem & FS = *llvm::vfs::getRealFileSystem(), llvm::Optional< llvm::StringRef > CurrentDir = llvm::None)
Expand response files on a command line recursively using the given StringSaver and tokenization strategy.
Argv should contain the command line before expansion and will be modified in place. If requested, Argv will also be populated with nullptrs indicating where each response file line ends, which is useful for the "/link" argument that needs to consume all remaining arguments only until the next end of line, when in a response file.
Parameters
[in] Saver Delegates back to the caller for saving parsed strings.
[in] Tokenizer Tokenization strategy. Typically Unix or Windows.
[in,out] Argv Command line into which to expand response files.
[in] MarkEOLs Mark end of lines and the end of the response file with nullptrs in the Argv vector.
[in] RelativeNames true if names of nested response files must be resolved relative to including file.
[in] FS File system used for all file access when running the tool.
[in] CurrentDir Path used to resolve relative rsp files. If set to None, process' cwd is used instead.
Returns
true if all were expanded successfully or there were none.
Definition at line 1112 of file CommandLine.cpp.
References File.
Referenced by ResetAllOptionOccurrences().
getRegisteredOptions()
StringMap< Option * > & llvm::cl::getRegisteredOptions (SubCommand & Sub = *TopLevelSubCommand)
Use this to get a StringMap to all registered named options (e.g.
-help).
Returns
A reference to the StringMap used by the cl APIs to parse options.
Access to unnamed arguments (i.e. positional) are not provided because it is expected that the client already has access to these.
Typical usage:
main(int argc,char* argv[]) {
StringMap<llvm::cl::Option*> &opts = llvm::cl::getRegisteredOptions();
assert(opts.count("help") == 1)
opts["help"]->setDescription("Show alphabetical help information")
// More code
llvm::cl::ParseCommandLineOptions(argc,argv);
//More code
}
This interface is useful for modifying options in libraries that are out of the control of the client. The options should be modified before calling llvm::cl::ParseCommandLineOptions().
Hopefully this API can be deprecated soon. Any situation where options need to be modified by tools or libraries should be handled by sane APIs rather than just handing around a global list.
Definition at line 2549 of file CommandLine.cpp.
References assert(), llvm::is_contained(), and llvm::cl::SubCommand::OptionsMap.
getRegisteredSubcommands()
iterator_range< typename SmallPtrSet< SubCommand *, 4 >::iterator > llvm::cl::getRegisteredSubcommands ()
Use this to get all registered SubCommands from the provided parser.
Returns
A range of all SubCommand pointers registered with the parser.
Typical usage:
main(int argc, char* argv[]) {
  llvm::cl::ParseCommandLineOptions(argc, argv);
  for (auto* S : llvm::cl::getRegisteredSubcommands()) {
    if (*S) {
      std::cout << "Executing subcommand: " << S->getName() << std::endl;
      // Execute some function based on the name...
    }
  }
}
This interface is useful for defining subcommands in libraries and the dispatch from a single point (like in the main function).
Definition at line 2557 of file CommandLine.cpp.
HideUnrelatedOptions() [1/2]
void llvm::cl::HideUnrelatedOptions (cl::OptionCategory & Category, SubCommand & Sub = *TopLevelSubCommand)
Mark all options not part of this category as cl::ReallyHidden.
Parameters
Category the category of options to keep displaying
Some tools (like clang-format) like to be able to hide all options that are not specific to the tool. This function allows a tool to specify a single option category to display in the -help output.
Definition at line 2561 of file CommandLine.cpp.
References I, llvm::cl::SubCommand::OptionsMap, and ReallyHidden.
HideUnrelatedOptions() [2/2]
void llvm::cl::HideUnrelatedOptions (ArrayRef< const cl::OptionCategory *> Categories, SubCommand & Sub = *TopLevelSubCommand)
Mark all options not part of the categories as cl::ReallyHidden.
Parameters
Categories the categories of options to keep displaying.
Some tools (like clang-format) like to be able to hide all options that are not specific to the tool. This function allows a tool to specify a single option category to display in the -help output.
Definition at line 2571 of file CommandLine.cpp.
References llvm::ArrayRef< T >::end(), llvm::find(), GenericCategory, I, llvm::cl::SubCommand::OptionsMap, and ReallyHidden.
init()
template<class Ty > initializer<Ty> llvm::cl::init (const Ty & Val)
Definition at line 435 of file CommandLine.h.
Referenced by addLiveInRegs(), llvm::CallInst::classof(), llvm::ExtractValueInst::classof(), llvm::InvokeInst::classof(), llvm::CallBrInst::classof(), llvm::PressureDiffs::clear(), llvm::CallBrInst::Create(), llvm::createNVVMReflectPass(), darwinHasSinCos(), llvm::DataLayout::DataLayout(), llvm::DenseMap< unsigned, unsigned >::DenseMap(), llvm::DIType::DIType(), llvm::RegScavenger::enterBasicBlock(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::yaml::Scanner::failed(), llvm::getPassTimer(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::LTOCodeGenerator::getVersionString(), giveUpWithRemarks(), llvm::PHINode::hasConstantOrUndefValue(), hasPressureSet(), llvm::Timer::init(), llvm::slpvectorizer::BoUpSLP::isDeleted(), llvm::CmpInst::isImpliedFalseByMatchingCmp(), llvm::isSafeToLoadUnconditionally(), llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::MCSubRegIterator::MCSubRegIterator(), llvm::MCSuperRegIterator::MCSuperRegIterator(), llvm::DIType::mutate(), llvm::DataLayout::operator!=(), llvm::TrackingStatistic::operator++(), llvm::TrackingStatistic::operator+=(), llvm::TrackingStatistic::operator--(), llvm::TrackingStatistic::operator-=(), llvm::TrackingStatistic::operator=(), llvm::DenseMap< unsigned, unsigned >::operator=(), llvm::SmallDenseMap< unsigned, unsigned, N >::operator=(), llvm::CallBase::populateBundleOperandInfos(), llvm::RegPressureTracker::RegPressureTracker(), llvm::orc::RemoteObjectServerLayer< BaseLayerT, RPCEndpoint >::RemoteObjectServerLayer(), llvm::CatchSwitchInst::removeHandler(), llvm::MachineFunction::reset(), llvm::SchedRemainder::reset(), llvm::SchedBoundary::SchedBoundary(), llvm::setCurrentDebugTypes(), llvm::DenseMap< unsigned, unsigned >::shrink_and_clear(), llvm::SmallDenseMap< unsigned, unsigned, N >::shrink_and_clear(), llvm::SmallDenseMap< unsigned, unsigned, N >::SmallDenseMap(), sortSubCommands(), llvm::StringMap< uint64_t >::StringMap(), llvm::StringMapImpl::StringMapImpl(), llvm::SwitchInstProfUpdateWrapper::SwitchInstProfUpdateWrapper(), llvm::Timer::Timer(), llvm::TrackingStatistic::updateMax(), useDefaultMachineSched(), useDefaultRegisterAllocator(), and llvm::InterferenceCache::~InterferenceCache().
location()
template<class Ty > LocationClass<Ty> llvm::cl::location (Ty & L)
Definition at line 451 of file CommandLine.h.
Referenced by llvm::setCurrentDebugTypes(), and sortSubCommands().
ParseCommandLineOptions()
bool llvm::cl::ParseCommandLineOptions (int argc, const char *const * argv, StringRef Overview = "", raw_ostream * Errs = nullptr, const char * EnvVar = nullptr, bool LongOptionsUseDoubleDash = false)
Definition at line 1273 of file CommandLine.cpp.
References llvm::sys::Process::GetEnv(), I, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), and TokenizeGNUCommandLine().
Referenced by llvm::handleExecNameEncodedBEOpts(), llvm::handleExecNameEncodedOptimizerOpts(), isPrefixedOrGrouping(), LLVMParseCommandLineOptions(), llvm::LTOCodeGenerator::parseCodeGenDebugOptions(), ParseEnvironmentOptions(), llvm::parseFuzzerCLOpts(), and ResetAllOptionOccurrences().
ParseEnvironmentOptions()
void llvm::cl::ParseEnvironmentOptions (const char * progName, const char * envvar, const char * Overview = "")
ParseEnvironmentOptions - An alternative entry point to the CommandLine library, which allows you to read the program's name from the caller (as PROGNAME) and its command-line arguments from an environment variable (whose name is given in ENVVAR).
Definition at line 1248 of file CommandLine.cpp.
References assert(), llvm::StringRef::data(), llvm::sys::Process::GetEnv(), ParseCommandLineOptions(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::StringSaver::save(), llvm::SmallVectorBase::size(), and TokenizeGNUCommandLine().
PrintHelpMessage()
void llvm::cl::PrintHelpMessage (bool Hidden = false, bool Categorized = false)
This function just prints the help message, exactly the same way as if the -help or -help-hidden option had been given on the command line.
Parameters
Hidden if true will print hidden options
Categorized if true print options in categories
Definition at line 2526 of file CommandLine.cpp.
printOptionDiff() [1/2]
template<class ParserClass , class DT > void llvm::cl::printOptionDiff (const Option & O, const generic_parser_base & P, const DT & V, const OptionValue< DT > & Default, size_t GlobalWidth)
Definition at line 1209 of file CommandLine.h.
References llvm::cl::generic_parser_base::printOptionDiff().
Referenced by llvm::cl::parser< bool >::getValueName(), llvm::cl::parser< boolOrDefault >::getValueName(), llvm::cl::parser< int >::getValueName(), llvm::cl::parser< long >::getValueName(), llvm::cl::parser< long long >::getValueName(), llvm::cl::parser< unsigned >::getValueName(), llvm::cl::parser< unsigned long >::getValueName(), llvm::cl::parser< unsigned long long >::getValueName(), llvm::cl::parser< double >::getValueName(), llvm::cl::parser< float >::getValueName(), llvm::cl::parser< std::string >::getValueName(), and llvm::cl::parser< char >::getValueName().
printOptionDiff() [2/2]
template<class ParserClass , class ValDT > void llvm::cl::printOptionDiff (const Option & O, const basic_parser< typename ParserClass::parser_data_type > & P, const ValDT & V, const OptionValue< ValDT > & Default, size_t GlobalWidth)
Definition at line 1236 of file CommandLine.h.
References llvm::cl::OptionDiffPrinter< ParserDT, ValDT >::print().
PrintOptionValues()
void llvm::cl::PrintOptionValues ()
Definition at line 2417 of file CommandLine.cpp.
References llvm::numbers::e, llvm::max(), second, llvm::SmallVectorBase::size(), and sortOpts().
PrintVersionMessage()
void llvm::cl::PrintVersionMessage ()
Utility function for printing version number.
Definition at line 2538 of file CommandLine.cpp.
ProvidePositionalOption()
bool llvm::cl::ProvidePositionalOption (Option * Handler, StringRef Arg, int i)
Parses Arg into the option handler Handler.
Definition at line 709 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::NVPTXISD::Dummy, and ProvideOption().
Referenced by ResetAllOptionOccurrences().
readConfigFile()
bool llvm::cl::readConfigFile (StringRef CfgFileName, StringSaver & Saver, SmallVectorImpl< const char *> & Argv)
Reads command line options from the given configuration file.
Parameters
[in] CfgFileName Path to configuration file.
[in] Saver Objects that saves allocated strings.
[out] Argv Array to which the read options are added.
Returns
true if the file was successfully read.
It reads content of the specified file, tokenizes it and expands "@file" commands resolving file names in them relative to the directory where CfgFilename resides.
Definition at line 1223 of file CommandLine.cpp.
References llvm::sys::path::append(), llvm::sys::fs::current_path(), llvm::sys::path::is_relative(), and llvm::SmallString< InternalLen >::str().
ResetAllOptionOccurrences()
void llvm::cl::ResetAllOptionOccurrences ()
Reset all command line options to a state that looks as if they have never appeared on the command line.
This is useful for being able to parse a command line multiple times (especially useful for writing tests).
Definition at line 1299 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, assert(), llvm::cl::SubCommand::ConsumeAfterOpt, llvm::dbgs(), llvm::numbers::e, E, EatsUnboundedNumberOfValues(), llvm::SmallVectorBase::empty(), llvm::StringRef::empty(), llvm::cl::Option::error(), llvm::errs(), ExpandResponseFiles(), llvm::sys::path::filename(), first, llvm::cl::Option::getFormattingFlag(), llvm::cl::Option::getMiscFlags(), llvm::sys::getProcessTriple(), HandlePrefixedOrGroupedOption(), llvm::cl::Option::hasArgStr(), I, LLVM_DEBUG, LLVM_FALLTHROUGH, llvm_unreachable, LookupNearestOption(), llvm::RISCVFenceField::O, OneOrMore, Optional, llvm::cl::SubCommand::OptionsMap, ParseCommandLineOptions(), Positional, PositionalEatsArgs, llvm::cl::SubCommand::PositionalOpts, ProvideOption(), ProvidePositionalOption(), llvm::SmallVectorTemplateBase< T >::push_back(), Required, RequiresValue(), llvm::PPCISD::SC, second, llvm::cl::SubCommand::SinkOpts, llvm::SmallVectorBase::size(), llvm::StringRef::substr(), TokenizeGNUCommandLine(), TokenizeWindowsCommandLine(), TopLevelSubCommand, and ZeroOrMore.
Referenced by isPrefixedOrGrouping(), and ResetCommandLineParser().
ResetCommandLineParser()
void llvm::cl::ResetCommandLineParser ()
Reset the command line parser back to its initial state.
This removes all options, categories, and subcommands and returns the parser to a state where no options are supported.
Definition at line 2581 of file CommandLine.cpp.
References ResetAllOptionOccurrences().
SetVersionPrinter()
void llvm::cl::SetVersionPrinter (VersionPrinterTy func)
===------------------------------------------------------------------—===// SetVersionPrinter - Override the default (LLVM specific) version printer used to print out the version when –version is given on the command line.
This allows other systems using the CommandLine utilities to print their own version string.
Definition at line 2540 of file CommandLine.cpp.
tokenizeConfigFile()
void llvm::cl::tokenizeConfigFile (StringRef Source, StringSaver & Saver, SmallVectorImpl< const char *> & NewArgv, bool MarkEOLs = false)
Tokenizes content of configuration file.
Parameters
[in] Source The string representing content of config file.
[in] Saver Delegates back to the caller for saving parsed strings.
[out] NewArgv All parsed strings are appended to NewArgv.
[in] MarkEOLs Added for compatibility with TokenizerCallback.
It works like TokenizeGNUCommandLine with ability to skip comment lines.
Definition at line 1009 of file CommandLine.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), and isWhitespace().
TokenizeGNUCommandLine()
void llvm::cl::TokenizeGNUCommandLine (StringRef Source, StringSaver & Saver, SmallVectorImpl< const char *> & NewArgv, bool MarkEOLs = false)
Tokenizes a command line that can contain escapes and quotes.
The quoting rules match those used by GCC and other tools that use libiberty's buildargv() or expandargv() utilities, and do not match bash. They differ from buildargv() on treatment of backslashes that do not escape a special character to make it possible to accept most Windows file paths.
Parameters
[in] Source The string to be split on whitespace with quotes.
[in] Saver Delegates back to the caller for saving parsed strings.
[in] MarkEOLs true if tokenizing a response file and you want end of lines and end of the response file to be marked with a nullptr string.
[out] NewArgv All parsed strings are appended to NewArgv.
Definition at line 823 of file CommandLine.cpp.
References C, llvm::SmallVectorImpl< T >::clear(), llvm::StringRef::data(), E, llvm::SmallVectorBase::empty(), I, isQuote(), isWhitespace(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::StringSaver::save(), and llvm::StringRef::size().
Referenced by ParseCommandLineOptions(), ParseEnvironmentOptions(), and ResetAllOptionOccurrences().
TokenizeWindowsCommandLine()
void llvm::cl::TokenizeWindowsCommandLine (StringRef Source, StringSaver & Saver, SmallVectorImpl< const char *> & NewArgv, bool MarkEOLs = false)
Tokenizes a Windows command line which may contain quotes and escaped quotes.
See MSDN docs for CommandLineToArgvW for information on the quoting rules. http://msdn.microsoft.com/en-us/library/windows/desktop/17w5ykft(v=vs.85).aspx
Parameters
[in] Source The string to be split on whitespace with quotes.
[in] Saver Delegates back to the caller for saving parsed strings.
[in] MarkEOLs true if tokenizing a response file and you want end of lines and end of the response file to be marked with a nullptr string.
[out] NewArgv All parsed strings are appended to NewArgv.
Definition at line 922 of file CommandLine.cpp.
References C, llvm::SmallVectorImpl< T >::clear(), llvm::StringRef::data(), E, llvm::SmallVectorBase::empty(), I, INIT, isWhitespaceOrNull(), parseBackslash(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::StringSaver::save(), and llvm::StringRef::size().
Referenced by ResetAllOptionOccurrences().
values()
template<typename... OptsTy> ValuesClass llvm::cl::values (OptsTy... Options)
Helper to build a ValuesClass by forwarding a variable number of arguments as an initializer list to the ValuesClass constructor.
Definition at line 692 of file CommandLine.h.
Referenced by llvm::DIE::computeOffsetsAndAbbrevs(), llvm::DIELoc::ComputeSize(), llvm::DIEBlock::ComputeSize(), llvm::DIELoc::EmitValue(), llvm::DIEBlock::EmitValue(), llvm::DIE::findAttribute(), llvm::DIE::generateAbbrev(), lookupFunction(), and llvm::DIE::print().
Variable Documentation
AllSubCommands
ManagedStatic< SubCommand > llvm::cl::AllSubCommands
Definition at line 493 of file CommandLine.cpp.
Referenced by llvm::cl::Option::isInAllSubCommands(), isPrefixedOrGrouping(), llvm::cl::SubCommand::operator bool(), and sortSubCommands().
GeneralCategory
OptionCategory llvm::cl::GeneralCategory
Referenced by llvm::cl::Option::addCategory(), llvm::cl::OptionCategory::getDescription(), and llvm::cl::Option::reset().
TopLevelSubCommand
LLVM_REQUIRE_CONSTANT_INITIALIZATION ManagedStatic< SubCommand > llvm::cl::TopLevelSubCommand
Definition at line 490 of file CommandLine.cpp.
Referenced by isPrefixedOrGrouping(), llvm::cl::SubCommand::operator bool(), ResetAllOptionOccurrences(), and sortSubCommands().