LLVM: llvm::PBQP::RegAlloc Namespace Reference
llvm::PBQP::RegAlloc Namespace Reference
Classes
class AllowedRegVector
Holds a vector of the allowed physical regs for a vreg.
class GraphMetadata
Holds graph-level metadata relevant to PBQP RA problems.
class MatrixMetadata
Metadata to speed allocatability test.
class NodeMetadata
Holds solver state and other metadata relevant to each PBQP RA node.
class PBQPRAGraph
class RegAllocSolverImpl
Functions
unsigned getSpillOptionIdx ()
Spill option index.
hash_code hash_value (const AllowedRegVector &OptRegs)
Solution solve (PBQPRAGraph &G)
Function Documentation
getSpillOptionIdx()
unsigned llvm::PBQP::RegAlloc::getSpillOptionIdx () inline
Spill option index.
Definition at line 46 of file RegAllocPBQP.h.
Referenced by isACalleeSavedRegister().
hash_value()
hash_code llvm::PBQP::RegAlloc::hash_value (const AllowedRegVector & OptRegs) inline
Definition at line 122 of file RegAllocPBQP.h.
References llvm::hash_combine(), and llvm::hash_combine_range().
solve()
Solution llvm::PBQP::RegAlloc::solve (PBQPRAGraph & G) inline
Definition at line 519 of file RegAllocPBQP.h.
References llvm::createPBQPRegisterAllocator(), llvm::PBQP::Graph< SolverT >::empty(), and llvm::PBQP::RegAlloc::RegAllocSolverImpl::solve().
Referenced by getEdgeValueLocal(), intersect(), and normalizePBQPSpillWeight().