LLVM: llvm::codeview::detail Namespace Reference
llvm::codeview::detail Namespace Reference
Classes
class GuidAdapter
Functions
template<typename T >
Error visitDebugSubsections (T &&FragmentRange, DebugSubsectionVisitor &V, StringsAndChecksumsRef &State)
Function Documentation
visitDebugSubsections()
template<typename T > Error llvm::codeview::detail::visitDebugSubsections (T && FragmentRange, DebugSubsectionVisitor & V, StringsAndChecksumsRef & State)
Definition at line 73 of file DebugSubsectionVisitor.h.
References llvm::codeview::EC, llvm::codeview::StringsAndChecksumsRef::initialize(), llvm::Error::success(), and llvm::codeview::visitDebugSubsection().
Referenced by llvm::codeview::visitDebugSubsections().