LLVM: llvm::AMDGPU Namespace Reference
llvm::AMDGPU Namespace Reference
Namespaces
DPP
EncValues
HSAMD
Hwreg
IsaInfo
PALMD
SDWA
SendMsg
Swizzle
VGPRIndexMode
Classes
struct D16ImageDimIntrinsic
struct GcnBufferFormatInfo
struct ImageDimIntrinsicInfo
struct IsaVersion
Instruction set architecture version.
struct MIMGBaseOpcodeInfo
struct MIMGDimInfo
struct MIMGInfo
struct MIMGLZMappingInfo
struct MIMGMIPMappingInfo
struct MTBUFInfo
struct MUBUFInfo
struct RsrcIntrinsic
struct SIModeRegisterDefaults
struct Waitcnt
Represents the counter values to wait for in an s_waitcnt instruction.
Enumerations
enum GPUKind : uint32_t {
GK_NONE = 0, GK_R600 = 1, GK_R630 = 2, GK_RS880 = 3,
GK_RV670 = 4, GK_RV710 = 5, GK_RV730 = 6, GK_RV770 = 7,
GK_CEDAR = 8, GK_CYPRESS = 9, GK_JUNIPER = 10, GK_REDWOOD = 11,
GK_SUMO = 12, GK_BARTS = 13, GK_CAICOS = 14, GK_CAYMAN = 15,
GK_TURKS = 16, GK_R600_FIRST = GK_R600, GK_R600_LAST = GK_TURKS, GK_GFX600 = 32,
GK_GFX601 = 33, GK_GFX700 = 40, GK_GFX701 = 41, GK_GFX702 = 42,
GK_GFX703 = 43, GK_GFX704 = 44, GK_GFX801 = 50, GK_GFX802 = 51,
GK_GFX803 = 52, GK_GFX810 = 53, GK_GFX900 = 60, GK_GFX902 = 61,
GK_GFX904 = 62, GK_GFX906 = 63, GK_GFX908 = 64, GK_GFX909 = 65,
GK_GFX1010 = 71, GK_GFX1011 = 72, GK_GFX1012 = 73, GK_AMDGCN_FIRST = GK_GFX600,
GK_AMDGCN_LAST = GK_GFX1012
}
GPU kinds supported by the AMDGPU target.
enum ArchFeatureKind : uint32_t {
FEATURE_NONE = 0, FEATURE_FMA = 1 << 1, FEATURE_LDEXP = 1 << 2, FEATURE_FP64 = 1 << 3,
FEATURE_FAST_FMA_F32 = 1 << 4, FEATURE_FAST_DENORMAL_F32 = 1 << 5
}
enum TargetIndex {
TI_CONSTDATA_START, TI_SCRATCH_RSRC_DWORD0, TI_SCRATCH_RSRC_DWORD1, TI_SCRATCH_RSRC_DWORD2,
TI_SCRATCH_RSRC_DWORD3
}
enum Fixups { fixup_si_sopp_br = FirstTargetFixupKind, LastTargetFixupKind, NumTargetFixupKinds = LastTargetFixupKind - FirstTargetFixupKind }
enum OperandType : unsigned {
OPERAND_REG_IMM_INT32 = MCOI::OPERAND_FIRST_TARGET, OPERAND_REG_IMM_INT64, OPERAND_REG_IMM_INT16, OPERAND_REG_IMM_FP32,
OPERAND_REG_IMM_FP64, OPERAND_REG_IMM_FP16, OPERAND_REG_IMM_V2FP16, OPERAND_REG_IMM_V2INT16,
OPERAND_REG_INLINE_C_INT16, OPERAND_REG_INLINE_C_INT32, OPERAND_REG_INLINE_C_INT64, OPERAND_REG_INLINE_C_FP16,
OPERAND_REG_INLINE_C_FP32, OPERAND_REG_INLINE_C_FP64, OPERAND_REG_INLINE_C_V2FP16, OPERAND_REG_INLINE_C_V2INT16,
OPERAND_REG_INLINE_AC_INT16, OPERAND_REG_INLINE_AC_INT32, OPERAND_REG_INLINE_AC_FP16, OPERAND_REG_INLINE_AC_FP32,
OPERAND_REG_INLINE_AC_V2FP16, OPERAND_REG_INLINE_AC_V2INT16, OPERAND_REG_IMM_FIRST = OPERAND_REG_IMM_INT32, OPERAND_REG_IMM_LAST = OPERAND_REG_IMM_V2INT16,
OPERAND_REG_INLINE_C_FIRST = OPERAND_REG_INLINE_C_INT16, OPERAND_REG_INLINE_C_LAST = OPERAND_REG_INLINE_AC_V2INT16, OPERAND_REG_INLINE_AC_FIRST = OPERAND_REG_INLINE_AC_INT16, OPERAND_REG_INLINE_AC_LAST = OPERAND_REG_INLINE_AC_V2INT16,
OPERAND_SRC_FIRST = OPERAND_REG_IMM_INT32, OPERAND_SRC_LAST = OPERAND_REG_INLINE_C_LAST, OPERAND_INPUT_MODS, OPERAND_SDWA_VOPC_DST,
OPERAND_KIMM32, OPERAND_KIMM16
}
Functions
StringRef getArchNameAMDGCN (GPUKind AK)
StringRef getArchNameR600 (GPUKind AK)
StringRef getCanonicalArchName (StringRef Arch)
GPUKind parseArchAMDGCN (StringRef CPU)
GPUKind parseArchR600 (StringRef CPU)
unsigned getArchAttrAMDGCN (GPUKind AK)
unsigned getArchAttrR600 (GPUKind AK)
void fillValidArchListAMDGCN (SmallVectorImpl< StringRef > &Values)
void fillValidArchListR600 (SmallVectorImpl< StringRef > &Values)
IsaVersion getIsaVersion (StringRef GPU)
std::tuple< Register, unsigned, MachineInstr * > getBaseWithConstantOffset (MachineRegisterInfo &MRI, Register Reg)
Returns Base register, constant offset, and offset def point.
const RsrcIntrinsic * lookupRsrcIntrinsic (unsigned Intr)
const D16ImageDimIntrinsic * lookupD16ImageDimIntrinsic (unsigned Intr)
const ImageDimIntrinsicInfo * getImageDimIntrinsicInfo (unsigned Intr)
LLVM_READONLY int getVOPe64 (uint16_t Opcode)
LLVM_READONLY int getVOPe32 (uint16_t Opcode)
LLVM_READONLY int getSDWAOp (uint16_t Opcode)
LLVM_READONLY int getDPPOp32 (uint16_t Opcode)
LLVM_READONLY int getBasicFromSDWAOp (uint16_t Opcode)
LLVM_READONLY int getCommuteRev (uint16_t Opcode)
LLVM_READONLY int getCommuteOrig (uint16_t Opcode)
LLVM_READONLY int getAddr64Inst (uint16_t Opcode)
LLVM_READONLY int getIfAddr64Inst (uint16_t Opcode)
Check if Opcode is an Addr64 opcode.
LLVM_READONLY int getMUBUFNoLdsInst (uint16_t Opcode)
LLVM_READONLY int getAtomicRetOp (uint16_t Opcode)
LLVM_READONLY int getAtomicNoRetOp (uint16_t Opcode)
LLVM_READONLY int getSOPKOp (uint16_t Opcode)
LLVM_READONLY int getGlobalSaddrOp (uint16_t Opcode)
LLVM_READONLY int getVCMPXNoSDstOp (uint16_t Opcode)
int getMIMGOpcode (unsigned BaseOpcode, unsigned MIMGEncoding, unsigned VDataDwords, unsigned VAddrDwords)
const MIMGBaseOpcodeInfo * getMIMGBaseOpcode (unsigned Opc)
int getMaskedMIMGOp (unsigned Opc, unsigned NewChannels)
int getMTBUFBaseOpcode (unsigned Opc)
int getMTBUFOpcode (unsigned BaseOpc, unsigned Elements)
int getMTBUFElements (unsigned Opc)
bool getMTBUFHasVAddr (unsigned Opc)
bool getMTBUFHasSrsrc (unsigned Opc)
bool getMTBUFHasSoffset (unsigned Opc)
int getMUBUFBaseOpcode (unsigned Opc)
int getMUBUFOpcode (unsigned BaseOpc, unsigned Elements)
int getMUBUFElements (unsigned Opc)
bool getMUBUFHasVAddr (unsigned Opc)
bool getMUBUFHasSrsrc (unsigned Opc)
bool getMUBUFHasSoffset (unsigned Opc)
int getMCOpcode (uint16_t Opcode, unsigned Gen)
void initDefaultAMDKernelCodeT (amd_kernel_code_t &Header, const MCSubtargetInfo *STI)
amdhsa::kernel_descriptor_t getDefaultAmdhsaKernelDescriptor (const MCSubtargetInfo *STI)
bool isGroupSegment (const GlobalValue *GV)
bool isGlobalSegment (const GlobalValue *GV)
bool isReadOnlySegment (const GlobalValue *GV)
bool shouldEmitConstantsToTextSection (const Triple &TT)
int getIntegerAttribute (const Function &F, StringRef Name, int Default)
std::pair< int, int > getIntegerPairAttribute (const Function &F, StringRef Name, std::pair< int, int > Default, bool OnlyFirstRequired)
unsigned getVmcntBitMask (const IsaVersion &Version)
unsigned getExpcntBitMask (const IsaVersion &Version)
unsigned getLgkmcntBitMask (const IsaVersion &Version)
unsigned getWaitcntBitMask (const IsaVersion &Version)
unsigned decodeVmcnt (const IsaVersion &Version, unsigned Waitcnt)
unsigned decodeExpcnt (const IsaVersion &Version, unsigned Waitcnt)
unsigned decodeLgkmcnt (const IsaVersion &Version, unsigned Waitcnt)
void decodeWaitcnt (const IsaVersion &Version, unsigned Waitcnt, unsigned &Vmcnt, unsigned &Expcnt, unsigned &Lgkmcnt)
Decodes Vmcnt, Expcnt and Lgkmcnt from given Waitcnt for given isa Version, and writes decoded values into Vmcnt, Expcnt and Lgkmcnt respectively.
Waitcnt decodeWaitcnt (const IsaVersion &Version, unsigned Encoded)
unsigned encodeVmcnt (const IsaVersion &Version, unsigned Waitcnt, unsigned Vmcnt)
unsigned encodeExpcnt (const IsaVersion &Version, unsigned Waitcnt, unsigned Expcnt)
unsigned encodeLgkmcnt (const IsaVersion &Version, unsigned Waitcnt, unsigned Lgkmcnt)
unsigned encodeWaitcnt (const IsaVersion &Version, unsigned Vmcnt, unsigned Expcnt, unsigned Lgkmcnt)
Encodes Vmcnt, Expcnt and Lgkmcnt into Waitcnt for given isa Version.
unsigned encodeWaitcnt (const IsaVersion &Version, const Waitcnt &Decoded)
unsigned getInitialPSInputAddr (const Function &F)
bool isShader (CallingConv::ID cc)
bool isCompute (CallingConv::ID cc)
bool isEntryFunctionCC (CallingConv::ID CC)
bool hasXNACK (const MCSubtargetInfo &STI)
bool hasSRAMECC (const MCSubtargetInfo &STI)
bool hasMIMG_R128 (const MCSubtargetInfo &STI)
bool hasPackedD16 (const MCSubtargetInfo &STI)
bool isSI (const MCSubtargetInfo &STI)
bool isCI (const MCSubtargetInfo &STI)
bool isVI (const MCSubtargetInfo &STI)
bool isGFX9 (const MCSubtargetInfo &STI)
bool isGFX10 (const MCSubtargetInfo &STI)
bool isGCN3Encoding (const MCSubtargetInfo &STI)
bool isSGPR (unsigned Reg, const MCRegisterInfo *TRI)
Is Reg - scalar register.
bool isRegIntersect (unsigned Reg0, unsigned Reg1, const MCRegisterInfo *TRI)
Is there any intersection between registers.
unsigned getMCReg (unsigned Reg, const MCSubtargetInfo &STI)
If Reg is a pseudo reg, return the correct hardware register given STI otherwise return Reg.
unsigned mc2PseudoReg (unsigned Reg)
Convert hardware register Reg to a pseudo register.
bool isSISrcOperand (const MCInstrDesc &Desc, unsigned OpNo)
Can this operand also contain immediate values?
bool isSISrcFPOperand (const MCInstrDesc &Desc, unsigned OpNo)
Is this floating-point operand?
bool isSISrcInlinableOperand (const MCInstrDesc &Desc, unsigned OpNo)
Does this opearnd support only inlinable literals?
unsigned getRegBitWidth (unsigned RCID)
Get the size in bits of a register from the register class RC.
unsigned getRegBitWidth (const MCRegisterClass &RC)
Get the size in bits of a register from the register class RC.
unsigned getRegOperandSize (const MCRegisterInfo *MRI, const MCInstrDesc &Desc, unsigned OpNo)
Get size of register operand.
bool isInlinableLiteral64 (int64_t Literal, bool HasInv2Pi)
Is this literal inlinable.
bool isInlinableLiteral32 (int32_t Literal, bool HasInv2Pi)
bool isInlinableLiteral16 (int16_t Literal, bool HasInv2Pi)
bool isInlinableLiteralV216 (int32_t Literal, bool HasInv2Pi)
bool isArgPassedInSGPR (const Argument *A)
static bool hasSMEMByteOffset (const MCSubtargetInfo &ST)
int64_t getSMRDEncodedOffset (const MCSubtargetInfo &ST, int64_t ByteOffset)
bool isLegalSMRDImmOffset (const MCSubtargetInfo &ST, int64_t ByteOffset)
bool splitMUBUFOffset (uint32_t Imm, uint32_t &SOffset, uint32_t &ImmOffset, const GCNSubtarget *Subtarget, uint32_t Align)
bool isIntrinsicSourceOfDivergence (unsigned IntrID)
const GcnBufferFormatInfo * getGcnBufferFormatInfo (uint8_t BitsPerComp, uint8_t NumComponents, uint8_t NumFormat, const MCSubtargetInfo &STI)
const GcnBufferFormatInfo * getGcnBufferFormatInfo (uint8_t Format, const MCSubtargetInfo &STI)
LLVM_READONLY int16_t getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIdx)
LLVM_READONLY int getSOPPWithRelaxation (uint16_t Opcode)
LLVM_READONLY const MIMGBaseOpcodeInfo * getMIMGBaseOpcodeInfo (unsigned BaseOpcode)
LLVM_READONLY const MIMGDimInfo * getMIMGDimInfo (unsigned DimEnum)
LLVM_READONLY const MIMGDimInfo * getMIMGDimInfoByEncoding (uint8_t DimEnc)
LLVM_READONLY const MIMGDimInfo * getMIMGDimInfoByAsmSuffix (StringRef AsmSuffix)
LLVM_READONLY const MIMGLZMappingInfo * getMIMGLZMappingInfo (unsigned L)
LLVM_READONLY const MIMGMIPMappingInfo * getMIMGMIPMappingInfo (unsigned L)
LLVM_READONLY const MIMGInfo * getMIMGInfo (unsigned Opc)
LLVM_READNONE bool isKernel (CallingConv::ID CC)
LLVM_READNONE unsigned getOperandSize (const MCOperandInfo &OpInfo)
LLVM_READNONE unsigned getOperandSize (const MCInstrDesc &Desc, unsigned OpNo)
Variables
const uint64_t RSRC_DATA_FORMAT = 0xf00000000000LL
const uint64_t RSRC_ELEMENT_SIZE_SHIFT = (32 + 19)
const uint64_t RSRC_INDEX_STRIDE_SHIFT = (32 + 21)
const uint64_t RSRC_TID_ENABLE = UINT64_C(1) << (32 + 23)
Enumeration Type Documentation
ArchFeatureKind
enum llvm::AMDGPU::ArchFeatureKind : uint32_t
Enumerator
FEATURE_NONE
FEATURE_FMA
FEATURE_LDEXP
FEATURE_FP64
FEATURE_FAST_FMA_F32
FEATURE_FAST_DENORMAL_F32
Definition at line 144 of file TargetParser.h.
Fixups
enum llvm::AMDGPU::Fixups
Enumerator
fixup_si_sopp_br
16-bit PC relative fixup for SOPP branch instructions.
LastTargetFixupKind
NumTargetFixupKinds
Definition at line 16 of file AMDGPUFixupKinds.h.
GPUKind
enum llvm::AMDGPU::GPUKind : uint32_t
GPU kinds supported by the AMDGPU target.
Enumerator
GK_NONE
GK_R600
GK_R630
GK_RS880
GK_RV670
GK_RV710
GK_RV730
GK_RV770
GK_CEDAR
GK_CYPRESS
GK_JUNIPER
GK_REDWOOD
GK_SUMO
GK_BARTS
GK_CAICOS
GK_CAYMAN
GK_TURKS
GK_R600_FIRST
GK_R600_LAST
GK_GFX600
GK_GFX601
GK_GFX700
GK_GFX701
GK_GFX702
GK_GFX703
GK_GFX704
GK_GFX801
GK_GFX802
GK_GFX803
GK_GFX810
GK_GFX900
GK_GFX902
GK_GFX904
GK_GFX906
GK_GFX908
GK_GFX909
GK_GFX1010
GK_GFX1011
GK_GFX1012
GK_AMDGCN_FIRST
GK_AMDGCN_LAST
Definition at line 80 of file TargetParser.h.
OperandType
enum llvm::AMDGPU::OperandType : unsigned
Enumerator
OPERAND_REG_IMM_INT32
Operands with register or 32-bit immediate.
OPERAND_REG_IMM_INT64
OPERAND_REG_IMM_INT16
OPERAND_REG_IMM_FP32
OPERAND_REG_IMM_FP64
OPERAND_REG_IMM_FP16
OPERAND_REG_IMM_V2FP16
OPERAND_REG_IMM_V2INT16
OPERAND_REG_INLINE_C_INT16
Operands with register or inline constant.
OPERAND_REG_INLINE_C_INT32
OPERAND_REG_INLINE_C_INT64
OPERAND_REG_INLINE_C_FP16
OPERAND_REG_INLINE_C_FP32
OPERAND_REG_INLINE_C_FP64
OPERAND_REG_INLINE_C_V2FP16
OPERAND_REG_INLINE_C_V2INT16
OPERAND_REG_INLINE_AC_INT16
Operands with an AccVGPR register or inline constant.
OPERAND_REG_INLINE_AC_INT32
OPERAND_REG_INLINE_AC_FP16
OPERAND_REG_INLINE_AC_FP32
OPERAND_REG_INLINE_AC_V2FP16
OPERAND_REG_INLINE_AC_V2INT16
OPERAND_REG_IMM_FIRST
OPERAND_REG_IMM_LAST
OPERAND_REG_INLINE_C_FIRST
OPERAND_REG_INLINE_C_LAST
OPERAND_REG_INLINE_AC_FIRST
OPERAND_REG_INLINE_AC_LAST
OPERAND_SRC_FIRST
OPERAND_SRC_LAST
OPERAND_INPUT_MODS
OPERAND_SDWA_VOPC_DST
OPERAND_KIMM32
Operand with 32-bit immediate that uses the constant bus.
OPERAND_KIMM16
Definition at line 125 of file SIDefines.h.
TargetIndex
enum llvm::AMDGPU::TargetIndex
Enumerator
TI_CONSTDATA_START
TI_SCRATCH_RSRC_DWORD0
TI_SCRATCH_RSRC_DWORD1
TI_SCRATCH_RSRC_DWORD2
TI_SCRATCH_RSRC_DWORD3
Definition at line 249 of file AMDGPU.h.
Function Documentation
decodeExpcnt()
unsigned llvm::AMDGPU::decodeExpcnt (const IsaVersion & Version, unsigned Waitcnt)
Returns
Decoded Expcnt from given Waitcnt for given isa Version.
Definition at line 647 of file AMDGPUBaseInfo.cpp.
Referenced by llvm::AMDGPU::Waitcnt::combined(), decodeWaitcnt(), and encodeCnt().
decodeLgkmcnt()
unsigned llvm::AMDGPU::decodeLgkmcnt (const IsaVersion & Version, unsigned Waitcnt)
Returns
Decoded Lgkmcnt from given Waitcnt for given isa Version.
Definition at line 651 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaVersion::Major.
Referenced by llvm::AMDGPU::Waitcnt::combined(), decodeWaitcnt(), and encodeCnt().
decodeVmcnt()
unsigned llvm::AMDGPU::decodeVmcnt (const IsaVersion & Version, unsigned Waitcnt)
Returns
Decoded Vmcnt from given Waitcnt for given isa Version.
Definition at line 635 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaVersion::Major.
Referenced by llvm::AMDGPU::Waitcnt::combined(), decodeWaitcnt(), and encodeCnt().
decodeWaitcnt() [1/2]
void llvm::AMDGPU::decodeWaitcnt (const IsaVersion & Version, unsigned Waitcnt, unsigned & Vmcnt, unsigned & Expcnt, unsigned & Lgkmcnt)
Decodes Vmcnt, Expcnt and Lgkmcnt from given Waitcnt for given isa Version, and writes decoded values into Vmcnt, Expcnt and Lgkmcnt respectively.
Vmcnt, Expcnt and Lgkmcnt are decoded as follows: Vmcnt = Waitcnt[3:0] (pre-gfx9 only) Vmcnt = Waitcnt[3:0] | Waitcnt[15:14] (gfx9+ only) Expcnt = Waitcnt[6:4] Lgkmcnt = Waitcnt[11:8] (pre-gfx10 only) Lgkmcnt = Waitcnt[13:8] (gfx10+ only)
Definition at line 656 of file AMDGPUBaseInfo.cpp.
References decodeExpcnt(), decodeLgkmcnt(), and decodeVmcnt().
Referenced by addRegsToSet(), callWaitsOnFunctionReturn(), llvm::AMDGPU::Waitcnt::combined(), and llvm::AMDGPUInstPrinter::printWaitFlag().
decodeWaitcnt() [2/2]
Waitcnt llvm::AMDGPU::decodeWaitcnt (const IsaVersion & Version, unsigned Encoded)
Definition at line 663 of file AMDGPUBaseInfo.cpp.
References decodeExpcnt(), decodeLgkmcnt(), decodeVmcnt(), llvm::AMDGPU::Waitcnt::ExpCnt, llvm::AMDGPU::Waitcnt::LgkmCnt, and llvm::AMDGPU::Waitcnt::VmCnt.
encodeExpcnt()
unsigned llvm::AMDGPU::encodeExpcnt (const IsaVersion & Version, unsigned Waitcnt, unsigned Expcnt)
Returns
Waitcnt with encoded Expcnt for given isa Version.
Definition at line 682 of file AMDGPUBaseInfo.cpp.
Referenced by llvm::AMDGPU::Waitcnt::combined(), encodeCnt(), and encodeWaitcnt().
encodeLgkmcnt()
unsigned llvm::AMDGPU::encodeLgkmcnt (const IsaVersion & Version, unsigned Waitcnt, unsigned Lgkmcnt)
Returns
Waitcnt with encoded Lgkmcnt for given isa Version.
Definition at line 687 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaVersion::Major.
Referenced by llvm::AMDGPU::Waitcnt::combined(), encodeCnt(), and encodeWaitcnt().
encodeVmcnt()
unsigned llvm::AMDGPU::encodeVmcnt (const IsaVersion & Version, unsigned Waitcnt, unsigned Vmcnt)
Returns
Waitcnt with encoded Vmcnt for given isa Version.
Definition at line 671 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaVersion::Major.
Referenced by llvm::AMDGPU::Waitcnt::combined(), encodeCnt(), and encodeWaitcnt().
encodeWaitcnt() [1/2]
unsigned llvm::AMDGPU::encodeWaitcnt (const IsaVersion & Version, unsigned Vmcnt, unsigned Expcnt, unsigned Lgkmcnt)
Encodes Vmcnt, Expcnt and Lgkmcnt into Waitcnt for given isa Version.
Vmcnt, Expcnt and Lgkmcnt are encoded as follows: Waitcnt[3:0] = Vmcnt (pre-gfx9 only) Waitcnt[3:0] = Vmcnt[3:0] (gfx9+ only) Waitcnt[6:4] = Expcnt Waitcnt[11:8] = Lgkmcnt (pre-gfx10 only) Waitcnt[13:8] = Lgkmcnt (gfx10+ only) Waitcnt[15:14] = Vmcnt[5:4] (gfx9+ only)
Returns
Waitcnt with encoded Vmcnt, Expcnt and Lgkmcnt for given isa Version.
Definition at line 693 of file AMDGPUBaseInfo.cpp.
References encodeExpcnt(), encodeLgkmcnt(), encodeVmcnt(), and getWaitcntBitMask().
Referenced by callWaitsOnFunctionReturn(), llvm::AMDGPU::Waitcnt::combined(), and encodeWaitcnt().
encodeWaitcnt() [2/2]
unsigned llvm::AMDGPU::encodeWaitcnt (const IsaVersion & Version, const Waitcnt & Decoded)
Definition at line 702 of file AMDGPUBaseInfo.cpp.
References encodeWaitcnt(), llvm::AMDGPU::Waitcnt::ExpCnt, llvm::AMDGPU::Waitcnt::LgkmCnt, and llvm::AMDGPU::Waitcnt::VmCnt.
fillValidArchListAMDGCN()
void llvm::AMDGPU::fillValidArchListAMDGCN (SmallVectorImpl< StringRef > & Values)
Definition at line 164 of file TargetParser.cpp.
References C, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
fillValidArchListR600()
void llvm::AMDGPU::fillValidArchListR600 (SmallVectorImpl< StringRef > & Values)
Definition at line 170 of file TargetParser.cpp.
References C, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getAddr64Inst()
LLVM_READONLY int llvm::AMDGPU::getAddr64Inst (uint16_t Opcode)
Referenced by llvm::getRegSubRegPair(), and llvm::SIInstrInfo::legalizeOperands().
getArchAttrAMDGCN()
unsigned llvm::AMDGPU::getArchAttrAMDGCN (GPUKind AK)
Definition at line 152 of file TargetParser.cpp.
References FEATURE_NONE.
getArchAttrR600()
unsigned llvm::AMDGPU::getArchAttrR600 (GPUKind AK)
Definition at line 158 of file TargetParser.cpp.
References FEATURE_NONE.
getArchNameAMDGCN()
StringRef llvm::AMDGPU::getArchNameAMDGCN (GPUKind AK)
Definition at line 122 of file TargetParser.cpp.
Referenced by llvm::AMDGPUTargetStreamer::getArchNameFromElfMach().
getArchNameR600()
StringRef llvm::AMDGPU::getArchNameR600 (GPUKind AK)
Definition at line 128 of file TargetParser.cpp.
Referenced by llvm::AMDGPUTargetStreamer::getArchNameFromElfMach().
getAtomicNoRetOp()
LLVM_READONLY int llvm::AMDGPU::getAtomicNoRetOp (uint16_t Opcode)
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), callWaitsOnFunctionReturn(), llvm::getRegSubRegPair(), and isValidClauseInst().
getAtomicRetOp()
LLVM_READONLY int llvm::AMDGPU::getAtomicRetOp (uint16_t Opcode)
Referenced by callWaitsOnFunctionReturn(), llvm::getRegSubRegPair(), and isValidClauseInst().
getBaseWithConstantOffset()
std::tuple< Register, unsigned, MachineInstr * > llvm::AMDGPU::getBaseWithConstantOffset (MachineRegisterInfo & MRI, Register Reg)
Returns Base register, constant offset, and offset def point.
Definition at line 17 of file AMDGPUGlobalISelUtils.cpp.
References llvm::tgtok::Def, llvm::MachineOperand::getCImm(), llvm::getDefIgnoringCopies(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ConstantInt::getZExtValue(), llvm::MachineOperand::isImm(), llvm::MIPatternMatch::m_Copy(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::mi_match(), MRI, and Register.
Referenced by getBufferStoreFormatOpcode().
getBasicFromSDWAOp()
LLVM_READONLY int llvm::AMDGPU::getBasicFromSDWAOp (uint16_t Opcode)
Referenced by llvm::getRegSubRegPair(), and llvm::SIInstrInfo::verifyInstruction().
getCanonicalArchName()
StringRef llvm::AMDGPU::getCanonicalArchName (StringRef Arch)
getCommuteOrig()
LLVM_READONLY int llvm::AMDGPU::getCommuteOrig (uint16_t Opcode)
Referenced by llvm::SIInstrInfo::commuteOpcode(), and llvm::getRegSubRegPair().
getCommuteRev()
LLVM_READONLY int llvm::AMDGPU::getCommuteRev (uint16_t Opcode)
Referenced by llvm::SIInstrInfo::commuteOpcode(), and llvm::getRegSubRegPair().
getDefaultAmdhsaKernelDescriptor()
amdhsa::kernel_descriptor_t llvm::AMDGPU::getDefaultAmdhsaKernelDescriptor (const MCSubtargetInfo * STI)
Definition at line 518 of file AMDGPUBaseInfo.cpp.
References AMDHSA_BITS_SET, llvm::amdhsa::FLOAT_DENORM_MODE_FLUSH_NONE, llvm::MCSubtargetInfo::getCPU(), llvm::MCSubtargetInfo::getFeatureBits(), getIsaVersion(), llvm::AMDGPU::IsaVersion::Major, llvm::FeatureBitset::test(), and llvm::IndexedInstrProf::Version.
Referenced by IsRevOpcode().
getDPPOp32()
LLVM_READONLY int llvm::AMDGPU::getDPPOp32 (uint16_t Opcode)
Referenced by llvm::createGCNDPPCombinePass(), and llvm::getRegSubRegPair().
getExpcntBitMask()
unsigned llvm::AMDGPU::getExpcntBitMask (const IsaVersion & Version)
Returns
Expcnt bit mask for given isa Version.
Definition at line 614 of file AMDGPUBaseInfo.cpp.
Referenced by callWaitsOnFunctionReturn(), llvm::AMDGPU::Waitcnt::combined(), and llvm::AMDGPUInstPrinter::printWaitFlag().
getGcnBufferFormatInfo() [1/2]
LLVM_READONLY const GcnBufferFormatInfo * llvm::AMDGPU::getGcnBufferFormatInfo (uint8_t BitsPerComp, uint8_t NumComponents, uint8_t NumFormat, const MCSubtargetInfo & STI)
Definition at line 1343 of file AMDGPUBaseInfo.cpp.
References isGFX10().
Referenced by getBufferFormatWithCompCount().
getGcnBufferFormatInfo() [2/2]
LLVM_READONLY const GcnBufferFormatInfo * llvm::AMDGPU::getGcnBufferFormatInfo (uint8_t Format, const MCSubtargetInfo & STI)
Definition at line 1353 of file AMDGPUBaseInfo.cpp.
References isGFX10().
getGlobalSaddrOp()
LLVM_READONLY int llvm::AMDGPU::getGlobalSaddrOp (uint16_t Opcode)
Referenced by fixupGlobalSaddr(), getBufferFormatWithCompCount(), and llvm::getRegSubRegPair().
getIfAddr64Inst()
LLVM_READONLY int llvm::AMDGPU::getIfAddr64Inst (uint16_t Opcode)
Check if Opcode is an Addr64 opcode.
Returns
Opcode if it is an Addr64 opcode, otherwise -1.
Referenced by llvm::getRegSubRegPair(), and llvm::SIInstrInfo::legalizeOperands().
getImageDimIntrinsicInfo()
const ImageDimIntrinsicInfo* llvm::AMDGPU::getImageDimIntrinsicInfo (unsigned Intr)
Referenced by getBufferOffsetForMMO().
getInitialPSInputAddr()
unsigned llvm::AMDGPU::getInitialPSInputAddr (const Function & F)
Definition at line 881 of file AMDGPUBaseInfo.cpp.
References getIntegerAttribute().
Referenced by llvm::AMDGPU::Waitcnt::combined(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
getIntegerAttribute()
int llvm::AMDGPU::getIntegerAttribute (const Function & F, StringRef Name, int Default)
Returns
Integer value requested using F's Name attribute.
Default if attribute is not present.
Default and emits error if requested value cannot be converted to integer.
Definition at line 565 of file AMDGPUBaseInfo.cpp.
References llvm::LLVMContext::emitError(), llvm::StringRef::getAsInteger(), llvm::Function::getContext(), llvm::Function::getFnAttribute(), llvm::Attribute::getValueAsString(), and llvm::Attribute::isStringAttribute().
Referenced by llvm::AMDGPUSubtarget::getImplicitArgNumBytes(), getInitialPSInputAddr(), llvm::GCNSubtarget::getMaxNumSGPRs(), llvm::GCNSubtarget::getMaxNumVGPRs(), getMopState(), and llvm::AMDGPUTTIImpl::getUnrollingPreferences().
getIntegerPairAttribute()
std::pair< int, int > llvm::AMDGPU::getIntegerPairAttribute (const Function & F, StringRef Name, std::pair< int, int > Default, bool OnlyFirstRequired = false)
Returns
A pair of integer values requested using F's Name attribute in "first[,second]" format ("second" is optional unless OnlyFirstRequired is false).
Default if attribute is not present.
Default and emits error if one of the requested values cannot be converted to integer, or OnlyFirstRequired is false and "second" value is not present.
Definition at line 580 of file AMDGPUBaseInfo.cpp.
References llvm::LLVMContext::emitError(), llvm::Function::getContext(), llvm::Function::getFnAttribute(), llvm::Attribute::getValueAsString(), llvm::Attribute::isStringAttribute(), and llvm::StringRef::split().
Referenced by llvm::AMDGPUSubtarget::getFlatWorkGroupSizes(), and llvm::AMDGPUSubtarget::getWavesPerEU().
getIsaVersion()
AMDGPU::IsaVersion llvm::AMDGPU::getIsaVersion (StringRef GPU)
Definition at line 175 of file TargetParser.cpp.
References GK_GFX1010, GK_GFX1011, GK_GFX1012, GK_GFX600, GK_GFX601, GK_GFX700, GK_GFX701, GK_GFX702, GK_GFX703, GK_GFX704, GK_GFX801, GK_GFX802, GK_GFX803, GK_GFX810, GK_GFX900, GK_GFX902, GK_GFX904, GK_GFX906, GK_GFX908, GK_GFX909, GK_NONE, and parseArchAMDGCN().
Referenced by addRegsToSet(), callWaitsOnFunctionReturn(), llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUAsmPrinter::EmitStartOfAsmFile(), encodeCnt(), llvm::AMDGPU::IsaInfo::getAddressableNumSGPRs(), getDefaultAmdhsaKernelDescriptor(), llvm::AMDGPU::IsaInfo::getMaxNumSGPRs(), llvm::AMDGPU::IsaInfo::getMinNumSGPRs(), llvm::AMDGPU::IsaInfo::getNumExtraSGPRs(), getRegNum(), llvm::AMDGPU::IsaInfo::getSGPRAllocGranule(), llvm::AMDGPU::IsaInfo::getTotalNumSGPRs(), hasAnyNonFlatUseOfReg(), initDefaultAMDKernelCodeT(), IsRevOpcode(), llvm::AMDGPUInstPrinter::printWaitFlag(), and llvm::AMDGPU::IsaInfo::streamIsaVersion().
getLgkmcntBitMask()
unsigned llvm::AMDGPU::getLgkmcntBitMask (const IsaVersion & Version)
Returns
Lgkmcnt bit mask for given isa Version.
Definition at line 618 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaVersion::Major.
Referenced by callWaitsOnFunctionReturn(), llvm::AMDGPU::Waitcnt::combined(), and llvm::AMDGPUInstPrinter::printWaitFlag().
getMaskedMIMGOp()
LLVM_READONLY int llvm::AMDGPU::getMaskedMIMGOp (unsigned Opc, unsigned NewChannels)
Definition at line 125 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MIMGInfo::BaseOpcode, getMIMGInfo(), llvm::AMDGPU::MIMGInfo::MIMGEncoding, llvm::AMDGPU::MIMGInfo::Opcode, and llvm::AMDGPU::MIMGInfo::VAddrDwords.
Referenced by getBufferFormatWithCompCount().
getMCOpcode()
LLVM_READONLY int llvm::AMDGPU::getMCOpcode (uint16_t Opcode, unsigned Gen)
Definition at line 220 of file AMDGPUBaseInfo.cpp.
Referenced by llvm::SIInstrInfo::pseudoToMCOpcode().
getMCReg()
unsigned llvm::AMDGPU::getMCReg (unsigned Reg, const MCSubtargetInfo & STI)
If Reg is a pseudo reg, return the correct hardware register given STI otherwise return Reg.
Definition at line 1023 of file AMDGPUBaseInfo.cpp.
References llvm::Triple::getArch(), llvm::MCSubtargetInfo::getTargetTriple(), MAP_REG2REG, and llvm::Triple::r600.
Referenced by llvm::AMDGPUDisassembler::createRegOperand(), getVariantKind(), and isKernel().
getMIMGBaseOpcode()
const MIMGBaseOpcodeInfo* llvm::AMDGPU::getMIMGBaseOpcode (unsigned Opc)
Definition at line 120 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MIMGInfo::BaseOpcode, getMIMGBaseOpcodeInfo(), getMIMGInfo(), and Info.
getMIMGBaseOpcodeInfo()
LLVM_READONLY const MIMGBaseOpcodeInfo* llvm::AMDGPU::getMIMGBaseOpcodeInfo (unsigned BaseOpcode)
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), getMIMGBaseOpcode(), getRegNum(), parseTexFail(), and llvm::SIInstrInfo::verifyInstruction().
getMIMGDimInfo()
LLVM_READONLY const MIMGDimInfo* llvm::AMDGPU::getMIMGDimInfo (unsigned DimEnum)
Referenced by parseTexFail().
getMIMGDimInfoByAsmSuffix()
LLVM_READONLY const MIMGDimInfo* llvm::AMDGPU::getMIMGDimInfoByAsmSuffix (StringRef AsmSuffix)
Referenced by isRegOrImmWithInputMods().
getMIMGDimInfoByEncoding()
LLVM_READONLY const MIMGDimInfo* llvm::AMDGPU::getMIMGDimInfoByEncoding (uint8_t DimEnc)
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), getRegNum(), llvm::AMDGPUInstPrinter::printInst(), and llvm::SIInstrInfo::verifyInstruction().
getMIMGInfo()
LLVM_READONLY const MIMGInfo* llvm::AMDGPU::getMIMGInfo (unsigned Opc)
Referenced by addRegsToSet(), llvm::AMDGPUDisassembler::convertMIMGInst(), getMaskedMIMGOp(), getMIMGBaseOpcode(), getRegNum(), shrinkScalarCompare(), and llvm::SIInstrInfo::verifyInstruction().
getMIMGLZMappingInfo()
LLVM_READONLY const MIMGLZMappingInfo* llvm::AMDGPU::getMIMGLZMappingInfo (unsigned L)
Referenced by parseTexFail().
getMIMGMIPMappingInfo()
LLVM_READONLY const MIMGMIPMappingInfo* llvm::AMDGPU::getMIMGMIPMappingInfo (unsigned L)
Referenced by parseTexFail().
getMIMGOpcode()
LLVM_READONLY int llvm::AMDGPU::getMIMGOpcode (unsigned BaseOpcode, unsigned MIMGEncoding, unsigned VDataDwords, unsigned VAddrDwords)
Definition at line 113 of file AMDGPUBaseInfo.cpp.
References Info, and llvm::AMDGPU::MIMGInfo::Opcode.
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), parseTexFail(), and shrinkScalarCompare().
getMTBUFBaseOpcode()
LLVM_READONLY int llvm::AMDGPU::getMTBUFBaseOpcode (unsigned Opc)
Definition at line 157 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MTBUFInfo::BaseOpcode, and Info.
Referenced by getBufferFormatWithCompCount().
getMTBUFElements()
LLVM_READONLY int llvm::AMDGPU::getMTBUFElements (unsigned Opc)
Definition at line 167 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MTBUFInfo::elements, and Info.
getMTBUFHasSoffset()
LLVM_READONLY bool llvm::AMDGPU::getMTBUFHasSoffset (unsigned Opc)
Definition at line 182 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MTBUFInfo::has_soffset, and Info.
getMTBUFHasSrsrc()
LLVM_READONLY bool llvm::AMDGPU::getMTBUFHasSrsrc (unsigned Opc)
Definition at line 177 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MTBUFInfo::has_srsrc, and Info.
getMTBUFHasVAddr()
LLVM_READONLY bool llvm::AMDGPU::getMTBUFHasVAddr (unsigned Opc)
Definition at line 172 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MTBUFInfo::has_vaddr, and Info.
getMTBUFOpcode()
LLVM_READONLY int llvm::AMDGPU::getMTBUFOpcode (unsigned BaseOpc, unsigned Elements)
Definition at line 162 of file AMDGPUBaseInfo.cpp.
References Info, and llvm::AMDGPU::MTBUFInfo::Opcode.
Referenced by getBufferFormatWithCompCount().
getMUBUFBaseOpcode()
LLVM_READONLY int llvm::AMDGPU::getMUBUFBaseOpcode (unsigned Opc)
Definition at line 187 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MUBUFInfo::BaseOpcode, and Info.
Referenced by getBufferFormatWithCompCount().
getMUBUFElements()
LLVM_READONLY int llvm::AMDGPU::getMUBUFElements (unsigned Opc)
Definition at line 197 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MUBUFInfo::elements, and Info.
getMUBUFHasSoffset()
LLVM_READONLY bool llvm::AMDGPU::getMUBUFHasSoffset (unsigned Opc)
Definition at line 212 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MUBUFInfo::has_soffset, and Info.
getMUBUFHasSrsrc()
LLVM_READONLY bool llvm::AMDGPU::getMUBUFHasSrsrc (unsigned Opc)
Definition at line 207 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MUBUFInfo::has_srsrc, and Info.
getMUBUFHasVAddr()
LLVM_READONLY bool llvm::AMDGPU::getMUBUFHasVAddr (unsigned Opc)
Definition at line 202 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::MUBUFInfo::has_vaddr, and Info.
getMUBUFNoLdsInst()
LLVM_READONLY int llvm::AMDGPU::getMUBUFNoLdsInst (uint16_t Opcode)
Referenced by encodeBitmaskPerm(), and llvm::getRegSubRegPair().
getMUBUFOpcode()
LLVM_READONLY int llvm::AMDGPU::getMUBUFOpcode (unsigned BaseOpc, unsigned Elements)
Definition at line 192 of file AMDGPUBaseInfo.cpp.
References Info, and llvm::AMDGPU::MUBUFInfo::Opcode.
Referenced by getBufferFormatWithCompCount(), getBufferStoreOpcode(), and llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic().
getNamedOperandIdx()
LLVM_READONLY int16_t llvm::AMDGPU::getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIdx)
Referenced by addRegsToSet(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), allOpsDefaultValue(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::SIInstrInfo::buildShrunkInst(), callWaitsOnFunctionReturn(), combineKnownAdjacentMMOs(), llvm::SIInstrInfo::commuteInstructionImpl(), llvm::AMDGPUDisassembler::convertDPP8Inst(), llvm::AMDGPUDisassembler::convertMIMGInst(), llvm::AMDGPUDisassembler::convertSDWAInst(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::createGCNDPPCombinePass(), llvm::createSIAddIMGInitPass(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::R600InstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::findCommutedOpIndices(), findSingleRegDef(), llvm::SIInstrInfo::FoldImmediate(), foldImmediates(), frameIndexMayFold(), getBufferFormatWithCompCount(), llvm::SIRegisterInfo::getFrameIndexInstrOffset(), llvm::AMDGPUDisassembler::getInstruction(), llvm::SIInstrInfo::getInstSizeInBytes(), getLit64Encoding(), llvm::SIInstrInfo::getMemOperandWithOffset(), llvm::SIRegisterInfo::getMUBUFInstrOffset(), llvm::SIInstrInfo::getNamedImmOperand(), llvm::SIInstrInfo::getNamedOperand(), llvm::R600InstrInfo::getOperandIdx(), getRegNum(), getVariantKind(), llvm::SIInstrInfo::hasModifiers(), hoistAndMergeSGPRInits(), insertCSRRestores(), insertNamedMCOperand(), llvm::SIInstrInfo::isBufferSMRD(), llvm::SIInstrInfo::isImmOperandLegal(), isInlineConstantIfFolded(), IsMovrelsSDWAOpcode(), isRegOrImmWithInputMods(), IsRevOpcode(), isSendMsgTraceDataOrGDS(), isValidDPP8(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), nodesHaveSameOperandValue(), operator<<(), llvm::AMDGPUInstPrinter::printRegOperand(), removeModOperands(), shrinkScalarCompare(), tryAddToFoldList(), tryConstantFoldOp(), tryFoldInst(), tryToFoldACImm(), updateOperand(), and llvm::SIInstrInfo::verifyInstruction().
getOperandSize() [1/2]
LLVM_READNONE unsigned llvm::AMDGPU::getOperandSize (const MCOperandInfo & OpInfo) inline
Definition at line 596 of file AMDGPUBaseInfo.h.
References LLVM_READNONE, llvm_unreachable, OPERAND_REG_IMM_FP16, OPERAND_REG_IMM_FP32, OPERAND_REG_IMM_FP64, OPERAND_REG_IMM_INT16, OPERAND_REG_IMM_INT32, OPERAND_REG_IMM_INT64, OPERAND_REG_IMM_V2FP16, OPERAND_REG_IMM_V2INT16, OPERAND_REG_INLINE_AC_FP16, OPERAND_REG_INLINE_AC_FP32, OPERAND_REG_INLINE_AC_INT16, OPERAND_REG_INLINE_AC_INT32, OPERAND_REG_INLINE_AC_V2FP16, OPERAND_REG_INLINE_AC_V2INT16, OPERAND_REG_INLINE_C_FP16, OPERAND_REG_INLINE_C_FP32, OPERAND_REG_INLINE_C_FP64, OPERAND_REG_INLINE_C_INT16, OPERAND_REG_INLINE_C_INT32, OPERAND_REG_INLINE_C_INT64, OPERAND_REG_INLINE_C_V2FP16, OPERAND_REG_INLINE_C_V2INT16, and llvm::MCOperandInfo::OperandType.
Referenced by getOperandSize(), and getRegNum().
getOperandSize() [2/2]
LLVM_READNONE unsigned llvm::AMDGPU::getOperandSize (const MCInstrDesc & Desc, unsigned OpNo) inline
Definition at line 632 of file AMDGPUBaseInfo.h.
References Arg, getOperandSize(), getSMRDEncodedOffset(), isArgPassedInSGPR(), isInlinableLiteral16(), isInlinableLiteral32(), isInlinableLiteral64(), isInlinableLiteralV216(), isIntrinsicSourceOfDivergence(), isLegalSMRDImmOffset(), llvm::Literal, LLVM_READNONE, llvm::MCInstrDesc::OpInfo, splitMUBUFOffset(), and llvm::ARM_MB::ST.
getRegBitWidth() [1/2]
unsigned llvm::AMDGPU::getRegBitWidth (unsigned RCID)
Get the size in bits of a register from the register class RC.
Definition at line 1083 of file AMDGPUBaseInfo.cpp.
References llvm_unreachable.
Referenced by addRegsToSet(), buildMUBUFOffsetLoadStore(), llvm::SIInstrInfo::canInsertSelect(), findSRegBaseAndIndex(), getRegBitWidth(), getRegOperandSize(), llvm::SIRegisterInfo::getRegSplitParts(), INITIALIZE_PASS(), isKernel(), llvm::BitTracker::MachineEvaluator::MachineEvaluator(), llvm::AMDGPUInstPrinter::printRegOperand(), and tryToFoldACImm().
getRegBitWidth() [2/2]
unsigned llvm::AMDGPU::getRegBitWidth (const MCRegisterClass & RC)
Get the size in bits of a register from the register class RC.
Definition at line 1132 of file AMDGPUBaseInfo.cpp.
References llvm::MCRegisterClass::getID(), and getRegBitWidth().
getRegOperandSize()
unsigned llvm::AMDGPU::getRegOperandSize (const MCRegisterInfo * MRI, const MCInstrDesc & Desc, unsigned OpNo)
Get size of register operand.
Definition at line 1136 of file AMDGPUBaseInfo.cpp.
References assert(), getRegBitWidth(), llvm::MCRegisterInfo::getRegClass(), llvm::MCInstrDesc::NumOperands, llvm::MCInstrDesc::OpInfo, and llvm::MCOperandInfo::RegClass.
Referenced by getRegNum(), and isKernel().
getSDWAOp()
LLVM_READONLY int llvm::AMDGPU::getSDWAOp (uint16_t Opcode)
Referenced by llvm::getRegSubRegPair(), and operator<<().
getSMRDEncodedOffset()
int64_t llvm::AMDGPU::getSMRDEncodedOffset (const MCSubtargetInfo & ST, int64_t ByteOffset)
Returns
The encoding that will be used for ByteOffset in the SMRD offset field.
Definition at line 1250 of file AMDGPUBaseInfo.cpp.
References hasSMEMByteOffset().
Referenced by llvm::SIFrameLowering::emitEntryFunctionPrologue(), findMemSDNode(), getOperandSize(), isLegalSMRDImmOffset(), and llvm::AMDGPUInstructionSelector::select().
getSOPKOp()
LLVM_READONLY int llvm::AMDGPU::getSOPKOp (uint16_t Opcode)
Referenced by llvm::getRegSubRegPair(), and shrinkScalarCompare().
getSOPPWithRelaxation()
LLVM_READONLY int llvm::AMDGPU::getSOPPWithRelaxation (uint16_t Opcode)
getVCMPXNoSDstOp()
LLVM_READONLY int llvm::AMDGPU::getVCMPXNoSDstOp (uint16_t Opcode)
Referenced by llvm::getRegSubRegPair().
getVmcntBitMask()
unsigned llvm::AMDGPU::getVmcntBitMask (const IsaVersion & Version)
Returns
Vmcnt bit mask for given isa Version.
Definition at line 605 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaVersion::Major.
Referenced by callWaitsOnFunctionReturn(), llvm::AMDGPU::Waitcnt::combined(), and llvm::AMDGPUInstPrinter::printWaitFlag().
getVOPe32()
LLVM_READONLY int llvm::AMDGPU::getVOPe32 (uint16_t Opcode)
Referenced by llvm::createGCNDPPCombinePass(), llvm::getRegSubRegPair(), llvm::SIInstrInfo::hasVALU32BitEncoding(), matchSwap(), operator<<(), and tryAddToFoldList().
getVOPe64()
LLVM_READONLY int llvm::AMDGPU::getVOPe64 (uint16_t Opcode)
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter(), and llvm::getRegSubRegPair().
getWaitcntBitMask()
unsigned llvm::AMDGPU::getWaitcntBitMask (const IsaVersion & Version)
Returns
Waitcnt bit mask for given isa Version.
Definition at line 622 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaVersion::Major.
Referenced by llvm::AMDGPU::Waitcnt::combined(), encodeCnt(), and encodeWaitcnt().
hasMIMG_R128()
bool llvm::AMDGPU::hasMIMG_R128 (const MCSubtargetInfo & STI)
Definition at line 929 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by isKernel().
hasPackedD16()
bool llvm::AMDGPU::hasPackedD16 (const MCSubtargetInfo & STI)
Definition at line 933 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), getRegNum(), and isKernel().
hasSMEMByteOffset()
static bool llvm::AMDGPU::hasSMEMByteOffset (const MCSubtargetInfo & ST) static
Definition at line 1246 of file AMDGPUBaseInfo.cpp.
References isGCN3Encoding(), and isGFX10().
Referenced by getSMRDEncodedOffset(), and isLegalSMRDImmOffset().
hasSRAMECC()
bool llvm::AMDGPU::hasSRAMECC (const MCSubtargetInfo & STI)
Definition at line 925 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer(), isKernel(), and llvm::AMDGPU::IsaInfo::streamIsaVersion().
hasXNACK()
bool llvm::AMDGPU::hasXNACK (const MCSubtargetInfo & STI)
Definition at line 921 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer(), llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUAsmPrinter::EmitFunctionBodyEnd(), isKernel(), IsRevOpcode(), and llvm::AMDGPU::IsaInfo::streamIsaVersion().
initDefaultAMDKernelCodeT()
void llvm::AMDGPU::initDefaultAMDKernelCodeT (amd_kernel_code_t & Header, const MCSubtargetInfo * STI)
Definition at line 482 of file AMDGPUBaseInfo.cpp.
References AMD_CODE_PROPERTY_ENABLE_WAVEFRONT_SIZE32, amd_kernel_code_s::amd_kernel_code_version_major, amd_kernel_code_s::amd_kernel_code_version_minor, amd_kernel_code_s::amd_machine_kind, amd_kernel_code_s::amd_machine_version_major, amd_kernel_code_s::amd_machine_version_minor, amd_kernel_code_s::amd_machine_version_stepping, amd_kernel_code_s::call_convention, amd_kernel_code_s::code_properties, amd_kernel_code_s::compute_pgm_resource_registers, llvm::MCSubtargetInfo::getCPU(), llvm::MCSubtargetInfo::getFeatureBits(), getIsaVersion(), amd_kernel_code_s::group_segment_alignment, amd_kernel_code_s::kernarg_segment_alignment, amd_kernel_code_s::kernel_code_entry_byte_offset, llvm::AMDGPU::IsaVersion::Major, llvm::AMDGPU::IsaVersion::Minor, amd_kernel_code_s::private_segment_alignment, S_00B848_MEM_ORDERED, S_00B848_WGP_MODE, llvm::AMDGPU::IsaVersion::Stepping, llvm::FeatureBitset::test(), llvm::IndexedInstrProf::Version, and amd_kernel_code_s::wavefront_size.
Referenced by getElementByteSizeValue().
isArgPassedInSGPR()
bool llvm::AMDGPU::isArgPassedInSGPR (const Argument * A)
Definition at line 1220 of file AMDGPUBaseInfo.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, F(), llvm::Argument::getArgNo(), llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::Argument::getParent(), llvm::AttributeList::hasParamAttribute(), and llvm::CallingConv::SPIR_KERNEL.
Referenced by getOperandSize(), and llvm::AMDGPUInstrInfo::isUniformMMO().
isCI()
bool llvm::AMDGPU::isCI (const MCSubtargetInfo & STI)
Definition at line 941 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPU::Hwreg::getLastSymbolicHwreg(), isKernel(), IsMovrelsSDWAOpcode(), and llvm::AMDGPUInstPrinter::printRegOperand().
isCompute()
LLVM_READNONE bool llvm::AMDGPU::isCompute (CallingConv::ID cc)
Definition at line 900 of file AMDGPUBaseInfo.cpp.
References llvm::CallingConv::AMDGPU_CS, and isShader().
Referenced by llvm::AMDGPU::Waitcnt::combined(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AMDGPU::SIModeRegisterDefaults::getDefaultForCallingConv(), llvm::R600AsmPrinter::getPassName(), getRsrcReg(), llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
isEntryFunctionCC()
LLVM_READNONE bool llvm::AMDGPU::isEntryFunctionCC (CallingConv::ID CC)
Definition at line 904 of file AMDGPUBaseInfo.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, and llvm::CallingConv::SPIR_KERNEL.
Referenced by llvm::SITargetLowering::CanLowerReturn(), llvm::AMDGPU::Waitcnt::combined(), hasAnyNonFlatUseOfReg(), INITIALIZE_PASS(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SITargetLowering::mayBeEmittedAsTailCall(), and mustPreserveGV().
isGCN3Encoding()
bool llvm::AMDGPU::isGCN3Encoding (const MCSubtargetInfo & STI)
Definition at line 957 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by hasSMEMByteOffset().
isGFX10()
bool llvm::AMDGPU::isGFX10 (const MCSubtargetInfo & STI)
Definition at line 953 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPUAsmPrinter::doFinalization(), encodeBitmaskPerm(), encodeCnt(), getGcnBufferFormatInfo(), getLit64Encoding(), llvm::AMDGPU::IsaInfo::getMaxWavesPerEU(), getRegNum(), llvm::AMDGPU::IsaInfo::getTotalNumVGPRs(), hasSMEMByteOffset(), isKernel(), isRegOrImmWithInputMods(), llvm::AMDGPU::SendMsg::isValidMsgId(), llvm::AMDGPUInstPrinter::printInst(), and llvm::AMDGPUInstPrinter::printRegOperand().
isGFX9()
bool llvm::AMDGPU::isGFX9 (const MCSubtargetInfo & STI)
Definition at line 949 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPU::Hwreg::getLastSymbolicHwreg(), isKernel(), isRegOrImmWithInputMods(), IsRevOpcode(), llvm::AMDGPU::SendMsg::isValidMsgId(), and llvm::AMDGPUInstPrinter::printRegOperand().
isGlobalSegment()
bool llvm::AMDGPU::isGlobalSegment (const GlobalValue * GV)
Definition at line 551 of file AMDGPUBaseInfo.cpp.
References llvm::GlobalValue::getAddressSpace(), and AMDGPUAS::GLOBAL_ADDRESS.
isGroupSegment()
bool llvm::AMDGPU::isGroupSegment (const GlobalValue * GV)
Definition at line 547 of file AMDGPUBaseInfo.cpp.
References llvm::GlobalValue::getAddressSpace(), and AMDGPUAS::LOCAL_ADDRESS.
isInlinableLiteral16()
LLVM_READNONE bool llvm::AMDGPU::isInlinableLiteral16 (int16_t Literal, bool HasInv2Pi)
Definition at line 1186 of file AMDGPUBaseInfo.cpp.
Referenced by getOperandSize(), getRegNum(), isInlinableLiteralV216(), llvm::SIInstrInfo::isInlineConstant(), and isStackPtrRelative().
isInlinableLiteral32()
LLVM_READNONE bool llvm::AMDGPU::isInlinableLiteral32 (int32_t Literal, bool HasInv2Pi)
Definition at line 1160 of file AMDGPUBaseInfo.cpp.
References llvm::FloatToBits().
Referenced by llvm::SIRegisterInfo::eliminateFrameIndex(), getOperandSize(), getRegNum(), llvm::SIInstrInfo::isInlineConstant(), isStackPtrRelative(), and shrinkScalarLogicOp().
isInlinableLiteral64()
LLVM_READNONE bool llvm::AMDGPU::isInlinableLiteral64 (int64_t Literal, bool HasInv2Pi)
Is this literal inlinable.
Definition at line 1143 of file AMDGPUBaseInfo.cpp.
References llvm::DoubleToBits().
Referenced by getOperandSize(), getRegNum(), llvm::SIInstrInfo::isInlineConstant(), and isStackPtrRelative().
isInlinableLiteralV216()
LLVM_READNONE bool llvm::AMDGPU::isInlinableLiteralV216 (int32_t Literal, bool HasInv2Pi)
Definition at line 1205 of file AMDGPUBaseInfo.cpp.
References assert(), isInlinableLiteral16(), llvm::isInt< 16 >(), and llvm::isUInt< 16 >().
Referenced by getOperandSize(), getRegNum(), llvm::SIInstrInfo::isInlineConstant(), and updateOperand().
isIntrinsicSourceOfDivergence()
bool llvm::AMDGPU::isIntrinsicSourceOfDivergence (unsigned IntrID)
Returns
true if the intrinsic is divergent
Definition at line 1339 of file AMDGPUBaseInfo.cpp.
Referenced by getOperandSize(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), and llvm::GCNTTIImpl::isSourceOfDivergence().
isKernel()
LLVM_READNONE bool llvm::AMDGPU::isKernel (CallingConv::ID CC) inline
Definition at line 541 of file AMDGPUBaseInfo.h.
References llvm::CallingConv::AMDGPU_KERNEL, getMCReg(), getRegBitWidth(), getRegOperandSize(), hasMIMG_R128(), hasPackedD16(), hasSRAMECC(), hasXNACK(), isCI(), isGFX10(), isGFX9(), isRegIntersect(), isSGPR(), isSI(), isSISrcFPOperand(), isSISrcInlinableOperand(), isSISrcOperand(), isVI(), LLVM_READNONE, mc2PseudoReg(), MRI, Reg, llvm::CallingConv::SPIR_KERNEL, and TRI.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUCallLowering::lowerReturn(), and llvm::SITargetLowering::LowerReturn().
isLegalSMRDImmOffset()
bool llvm::AMDGPU::isLegalSMRDImmOffset (const MCSubtargetInfo & ST, int64_t ByteOffset)
Returns
true if this offset is small enough to fit in the SMRD offset field. ByteOffset should be the offset in bytes and not the encoded offset.
Definition at line 1256 of file AMDGPUBaseInfo.cpp.
References getSMRDEncodedOffset(), hasSMEMByteOffset(), and llvm::isUInt< 8 >().
Referenced by findMemSDNode(), getOperandSize(), and llvm::AMDGPUInstructionSelector::select().
isReadOnlySegment()
bool llvm::AMDGPU::isReadOnlySegment (const GlobalValue * GV)
Definition at line 555 of file AMDGPUBaseInfo.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, and llvm::GlobalValue::getAddressSpace().
Referenced by llvm::AMDGPUTargetObjectFile::SelectSectionForGlobal().
isRegIntersect()
bool llvm::AMDGPU::isRegIntersect (unsigned Reg0, unsigned Reg1, const MCRegisterInfo * TRI)
Is there any intersection between registers.
Definition at line 968 of file AMDGPUBaseInfo.cpp.
Referenced by getRegNum(), and isKernel().
isSGPR()
bool llvm::AMDGPU::isSGPR (unsigned Reg, const MCRegisterInfo * TRI)
Is Reg - scalar register.
Definition at line 961 of file AMDGPUBaseInfo.cpp.
References llvm::MCRegisterClass::contains(), llvm::MCRegisterInfo::getRegClass(), and llvm::MCRegisterInfo::getSubReg().
Referenced by getLit64Encoding(), getRegNum(), isKernel(), and IsMovrelsSDWAOpcode().
isShader()
LLVM_READNONE bool llvm::AMDGPU::isShader (CallingConv::ID cc)
Definition at line 885 of file AMDGPUBaseInfo.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, and llvm::CallingConv::AMDGPU_VS.
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::AMDGPU::Waitcnt::combined(), isCompute(), llvm::GCNSubtarget::isMesaGfxShader(), llvm::AMDGPUSubtarget::isMesaKernel(), llvm::SIInstrInfo::legalizeOperands(), llvm::SITargetLowering::LowerCall(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::SITargetLowering::LowerReturn(), and reservePrivateMemoryRegs().
isSI()
bool llvm::AMDGPU::isSI (const MCSubtargetInfo & STI)
Definition at line 937 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPU::Hwreg::getLastSymbolicHwreg(), isKernel(), IsMovrelsSDWAOpcode(), and llvm::AMDGPUInstPrinter::printRegOperand().
isSISrcFPOperand()
bool llvm::AMDGPU::isSISrcFPOperand (const MCInstrDesc & Desc, unsigned OpNo)
Is this floating-point operand?
Definition at line 1050 of file AMDGPUBaseInfo.cpp.
References assert(), llvm::MCInstrDesc::NumOperands, OPERAND_REG_IMM_FP16, OPERAND_REG_IMM_FP32, OPERAND_REG_IMM_FP64, OPERAND_REG_IMM_V2FP16, OPERAND_REG_IMM_V2INT16, OPERAND_REG_INLINE_AC_FP16, OPERAND_REG_INLINE_AC_FP32, OPERAND_REG_INLINE_AC_V2FP16, OPERAND_REG_INLINE_AC_V2INT16, OPERAND_REG_INLINE_C_FP16, OPERAND_REG_INLINE_C_FP32, OPERAND_REG_INLINE_C_FP64, OPERAND_REG_INLINE_C_V2FP16, OPERAND_REG_INLINE_C_V2INT16, llvm::MCOperandInfo::OperandType, and llvm::MCInstrDesc::OpInfo.
Referenced by isKernel().
isSISrcInlinableOperand()
bool llvm::AMDGPU::isSISrcInlinableOperand (const MCInstrDesc & Desc, unsigned OpNo)
Does this opearnd support only inlinable literals?
Definition at line 1074 of file AMDGPUBaseInfo.cpp.
References assert(), llvm::MCInstrDesc::NumOperands, OPERAND_REG_INLINE_C_FIRST, OPERAND_REG_INLINE_C_LAST, llvm::MCOperandInfo::OperandType, and llvm::MCInstrDesc::OpInfo.
Referenced by isKernel().
isSISrcOperand()
bool llvm::AMDGPU::isSISrcOperand (const MCInstrDesc & Desc, unsigned OpNo)
Can this operand also contain immediate values?
Definition at line 1043 of file AMDGPUBaseInfo.cpp.
References assert(), llvm::MCInstrDesc::NumOperands, OPERAND_SRC_FIRST, OPERAND_SRC_LAST, llvm::MCOperandInfo::OperandType, and llvm::MCInstrDesc::OpInfo.
Referenced by getLit64Encoding(), getRegNum(), llvm::SIInstrInfo::isImmOperandLegal(), isKernel(), llvm::SIInstrInfo::isOperandLegal(), IsRevOpcode(), and needsPCRel().
isVI()
bool llvm::AMDGPU::isVI (const MCSubtargetInfo & STI)
Definition at line 945 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::AMDGPU::Hwreg::getLastSymbolicHwreg(), isKernel(), isRegOrImmWithInputMods(), and llvm::AMDGPUInstPrinter::printRegOperand().
lookupD16ImageDimIntrinsic()
const D16ImageDimIntrinsic* llvm::AMDGPU::lookupD16ImageDimIntrinsic (unsigned Intr)
lookupRsrcIntrinsic()
const RsrcIntrinsic* llvm::AMDGPU::lookupRsrcIntrinsic (unsigned Intr)
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), and llvm::SITargetLowering::getTgtMemIntrinsic().
mc2PseudoReg()
LLVM_READNONE unsigned llvm::AMDGPU::mc2PseudoReg (unsigned Reg)
Convert hardware register Reg to a pseudo register.
Definition at line 1035 of file AMDGPUBaseInfo.cpp.
References MAP_REG2REG.
Referenced by getLit64Encoding(), getRegNum(), isKernel(), and IsMovrelsSDWAOpcode().
parseArchAMDGCN()
AMDGPU::GPUKind llvm::AMDGPU::parseArchAMDGCN (StringRef CPU)
Definition at line 134 of file TargetParser.cpp.
References C, and GK_NONE.
Referenced by llvm::AMDGPUTargetStreamer::getElfMach(), and getIsaVersion().
parseArchR600()
AMDGPU::GPUKind llvm::AMDGPU::parseArchR600 (StringRef CPU)
Definition at line 143 of file TargetParser.cpp.
References C, and GK_NONE.
Referenced by llvm::AMDGPUTargetStreamer::getElfMach().
shouldEmitConstantsToTextSection()
bool llvm::AMDGPU::shouldEmitConstantsToTextSection (const Triple & TT)
Returns
True if constants should be emitted to .text section for given target triple TT, false otherwise.
Definition at line 561 of file AMDGPUBaseInfo.cpp.
References llvm::Triple::AMDPAL, llvm::Triple::getArch(), llvm::Triple::getOS(), and llvm::Triple::r600.
Referenced by llvm::AMDGPUTargetObjectFile::SelectSectionForGlobal(), and llvm::SITargetLowering::shouldEmitFixup().
splitMUBUFOffset()
bool llvm::AMDGPU::splitMUBUFOffset (uint32_t Imm, uint32_t & SOffset, uint32_t & ImmOffset, const GCNSubtarget * Subtarget, uint32_t Align)
Definition at line 1269 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::alignDown(), llvm::GCNSubtarget::getGeneration(), High, and llvm::AMDGPUSubtarget::SEA_ISLANDS.
Referenced by getBufferOffsetForMMO(), and getOperandSize().
Variable Documentation
RSRC_DATA_FORMAT
const uint64_t llvm::AMDGPU::RSRC_DATA_FORMAT = 0xf00000000000LL
Definition at line 1146 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::getDefaultRsrcDataFormat(), and llvm::SIInstrInfo::getScratchRsrcWords23().
RSRC_ELEMENT_SIZE_SHIFT
const uint64_t llvm::AMDGPU::RSRC_ELEMENT_SIZE_SHIFT = (32 + 19)
Definition at line 1147 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::getScratchRsrcWords23().
RSRC_INDEX_STRIDE_SHIFT
const uint64_t llvm::AMDGPU::RSRC_INDEX_STRIDE_SHIFT = (32 + 21)
Definition at line 1148 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::getScratchRsrcWords23().
RSRC_TID_ENABLE
const uint64_t llvm::AMDGPU::RSRC_TID_ENABLE = UINT64_C(1) << (32 + 23)
Definition at line 1149 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::getScratchRsrcWords23().