LLVM: llvm::DWARFYAML Namespace Reference
llvm::DWARFYAML Namespace Reference
Classes
struct Abbrev
struct ARange
struct ARangeDescriptor
struct AttributeAbbrev
class ConstVisitor
struct Data
struct Entry
struct File
struct FormValue
struct InitialLength
struct LineTable
struct LineTableOpcode
struct PubEntry
struct PubSection
struct Unit
class Visitor
class VisitorImpl
A class to visits DWARFYAML Compile Units and DIEs in preorder.
Functions
void EmitDebugAbbrev (raw_ostream &OS, const Data &DI)
void EmitDebugStr (raw_ostream &OS, const Data &DI)
void EmitDebugAranges (raw_ostream &OS, const Data &DI)
void EmitPubSection (raw_ostream &OS, const PubSection &Sect, bool IsLittleEndian)
void EmitDebugInfo (raw_ostream &OS, const Data &DI)
void EmitDebugLine (raw_ostream &OS, const Data &DI)
Expected< StringMap< std::unique_ptr< MemoryBuffer > > > EmitDebugSections (StringRef YAMLString, bool ApplyFixups=false, bool IsLittleEndian=sys::IsLittleEndianHost)
StringMap< std::unique_ptr< MemoryBuffer > > EmitDebugSections (llvm::DWARFYAML::Data &DI, bool ApplyFixups)
Function Documentation
EmitDebugAbbrev()
void llvm::DWARFYAML::EmitDebugAbbrev (raw_ostream & OS, const Data & DI)
Definition at line 78 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::Data::AbbrevDecls, llvm::encodeSLEB128(), llvm::encodeULEB128(), and llvm::raw_ostream::write().
Referenced by EmitDebugSections().
EmitDebugAranges()
void llvm::DWARFYAML::EmitDebugAranges (raw_ostream & OS, const Data & DI)
Definition at line 94 of file DWARFEmitter.cpp.
References llvm::alignTo(), llvm::DWARFYAML::Data::ARanges, llvm::BTF::HeaderSize, llvm::DWARFYAML::Data::IsLittleEndian, llvm::raw_ostream::tell(), writeInitialLength(), writeInteger(), writeVariableSizedInteger(), and ZeroFillBytes().
Referenced by EmitDebugSections().
EmitDebugInfo()
void llvm::DWARFYAML::EmitDebugInfo (raw_ostream & OS, const Data & DI)
Definition at line 199 of file DWARFEmitter.cpp.
Referenced by EmitDebugSections().
EmitDebugLine()
void llvm::DWARFYAML::EmitDebugLine (raw_ostream & OS, const Data & DI)
Definition at line 212 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::Data::CompileUnits, llvm::DWARFYAML::Data::DebugLines, llvm::DWARFYAML::LineTable::DefaultIsStmt, EmitFileEntry(), llvm::encodeSLEB128(), llvm::encodeULEB128(), llvm::DWARFYAML::LineTable::Files, llvm::DWARFYAML::LineTable::IncludeDirs, llvm::DWARFYAML::InitialLength::isDWARF64(), llvm::DWARFYAML::Data::IsLittleEndian, llvm::DWARFYAML::LineTable::Length, llvm::DWARFYAML::LineTable::LineBase, llvm::DWARFYAML::LineTable::LineRange, llvm::DWARFYAML::LineTable::MaxOpsPerInst, llvm::DWARFYAML::LineTable::MinInstLength, llvm::DWARFYAML::LineTable::OpcodeBase, llvm::DWARFYAML::LineTable::Opcodes, llvm::DWARFYAML::LineTable::PrologueLength, llvm::DWARFYAML::LineTable::StandardOpcodeLengths, llvm::DWARFYAML::LineTable::Version, llvm::raw_ostream::write(), writeInitialLength(), writeInteger(), and writeVariableSizedInteger().
Referenced by EmitDebugSections().
EmitDebugSections() [1/2]
Expected< StringMap< std::unique_ptr< MemoryBuffer > > > llvm::DWARFYAML::EmitDebugSections (StringRef YAMLString, bool ApplyFixups = false, bool IsLittleEndian = sys::IsLittleEndianHost)
Definition at line 354 of file DWARFEmitter.cpp.
References EmitDebugAbbrev(), EmitDebugAranges(), EmitDebugInfo(), EmitDebugLine(), EmitDebugSectionImpl(), EmitDebugStr(), llvm::errorCodeToError(), and llvm::DWARFYAML::Data::IsLittleEndian.
EmitDebugSections() [2/2]
StringMap<std::unique_ptr<MemoryBuffer> > llvm::DWARFYAML::EmitDebugSections (llvm::DWARFYAML::Data & DI, bool ApplyFixups)
EmitDebugStr()
void llvm::DWARFYAML::EmitDebugStr (raw_ostream & OS, const Data & DI)
Definition at line 71 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::Data::DebugStrings, and llvm::raw_ostream::write().
Referenced by EmitDebugSections().
EmitPubSection()
void llvm::DWARFYAML::EmitPubSection (raw_ostream & OS, const PubSection & Sect, bool IsLittleEndian)
Definition at line 117 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::Entry::AbbrCode, llvm::DWARFYAML::Unit::AbbrOffset, llvm::DWARFYAML::Unit::AddrSize, llvm::StringRef::data(), llvm::encodeSLEB128(), llvm::encodeULEB128(), llvm::DWARFYAML::PubSection::Entries, llvm::MemoryBufferRef::getBufferSize(), llvm::MemoryBufferRef::getBufferStart(), llvm::DWARFYAML::PubSection::IsGNUStyle, llvm::DWARFYAML::PubSection::Length, llvm::DWARFYAML::Unit::Length, llvm::StringRef::size(), llvm::String, llvm::DWARFYAML::Unit::Type, llvm::DWARFYAML::PubSection::UnitOffset, llvm::DWARFYAML::PubSection::UnitSize, llvm::DWARFYAML::PubSection::Version, llvm::DWARFYAML::Unit::Version, llvm::raw_ostream::write(), writeInitialLength(), and writeInteger().