LLVM: llvm::cfg Namespace Reference
llvm::cfg Namespace Reference
Classes
class Update
Enumerations
enum UpdateKind : unsigned char { UpdateKind::Insert, UpdateKind::Delete }
Functions
template<typename NodePtr >
void LegalizeUpdates (ArrayRef< Update< NodePtr >> AllUpdates, SmallVectorImpl< Update< NodePtr >> &Result, bool InverseGraph)
Enumeration Type Documentation
UpdateKind
enum llvm::cfg::UpdateKind : unsigned char strong
Enumerator
Insert
Delete
Definition at line 26 of file CFGUpdate.h.
Function Documentation
LegalizeUpdates()
template<typename NodePtr > void llvm::cfg::LegalizeUpdates (ArrayRef< Update< NodePtr >> AllUpdates, SmallVectorImpl< Update< NodePtr >> & Result, bool InverseGraph)
Definition at line 63 of file CFGUpdate.h.
References llvm::abs(), assert(), B, Delete, llvm::numbers::e, From, llvm::cfg::Update< NodePtr >::getFrom(), llvm::cfg::Update< NodePtr >::getTo(), Insert, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::sort(), and std::swap().