LLVM: llvm::RISCVMatInt Namespace Reference
llvm::RISCVMatInt Namespace Reference
Classes
struct Inst
Typedefs
using InstSeq = SmallVector< Inst, 8 >
Functions
void generateInstSeq (int64_t Val, bool IsRV64, InstSeq &Res)
int getIntMatCost (const APInt &Val, unsigned Size, bool IsRV64)
Typedef Documentation
InstSeq
using llvm::RISCVMatInt::InstSeq = typedef SmallVector<Inst, 8>
Definition at line 26 of file RISCVMatInt.h.
Function Documentation
generateInstSeq()
void llvm::RISCVMatInt::generateInstSeq (int64_t Val, bool IsRV64, InstSeq & Res)
Definition at line 19 of file RISCVMatInt.cpp.
References assert(), llvm::findFirstSet(), llvm::isInt< 32 >(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SignExtend64().
Referenced by getIntMatCost(), matchRegisterNameHelper(), llvm::RISCVInstrInfo::movImm(), and selectImm().
getIntMatCost()
int llvm::RISCVMatInt::getIntMatCost (const APInt & Val, unsigned Size, bool IsRV64)
Definition at line 78 of file RISCVMatInt.cpp.
References llvm::APInt::ashr(), generateInstSeq(), llvm::APInt::getSExtValue(), llvm::max(), llvm::APInt::sextOrTrunc(), Size, and llvm::SmallVectorBase::size().
Referenced by llvm::RISCVTTIImpl::getIntImmCost(), and llvm::RISCVTargetLowering::isDesirableToCommuteWithShift().