LLVM: llvm::MachO::detail Namespace Reference
llvm::MachO::detail Namespace Reference
Functions
template<typename C >
C::iterator addEntry (C &Container, StringRef InstallName)
template<typename C >
C::iterator addEntry (C &Container, const Target &Target_)
Function Documentation
addEntry() [1/2]
template<typename C > C::iterator llvm::MachO::detail::addEntry (C & Container, StringRef InstallName)
Definition at line 21 of file InterfaceFile.cpp.
References llvm::MachO::InterfaceFileRef::getInstallName(), I, llvm::RISCVFenceField::O, and llvm::partition_point().
Referenced by llvm::MachO::InterfaceFile::addAllowableClient(), llvm::MachO::InterfaceFile::addReexportedLibrary(), llvm::MachO::InterfaceFileRef::addTarget(), llvm::MachO::InterfaceFile::addTarget(), and llvm::TGParser::PopLocalScope().
addEntry() [2/2]
template<typename C > C::iterator llvm::MachO::detail::addEntry (C & Container, const Target & Target_)
Definition at line 32 of file InterfaceFile.cpp.
References llvm::sys::path::end(), and llvm::lower_bound().