LLVM: llvm::X86 Namespace Reference
llvm::X86 Namespace Reference
Define some predicates that are used for node matching.
Enumerations
enum ProcessorVendors : unsigned { VENDOR_DUMMY, VENDOR_OTHER }
enum ProcessorTypes : unsigned { CPU_TYPE_DUMMY, CPU_TYPE_MAX }
enum ProcessorSubtypes : unsigned { CPU_SUBTYPE_DUMMY, CPU_SUBTYPE_MAX }
enum ProcessorFeatures
enum {
BX_SI = 500, BX_DI = 501, BP_SI = 502, BP_DI = 503,
sib = 504, sib64 = 505
}
enum {
AddrBaseReg = 0, AddrScaleAmt = 1, AddrIndexReg = 2, AddrDisp = 3,
AddrSegmentReg = 4, AddrNumOperands = 5
}
enum STATIC_ROUNDING {
TO_NEAREST_INT = 0, TO_NEG_INF = 1, TO_POS_INF = 2, TO_ZERO = 3,
CUR_DIRECTION = 4, NO_EXC = 8
}
AVX512 static rounding constants.
enum IPREFIXES {
IP_NO_PREFIX = 0, IP_HAS_OP_SIZE = 1, IP_HAS_AD_SIZE = 2, IP_HAS_REPEAT_NE = 4,
IP_HAS_REPEAT = 8, IP_HAS_LOCK = 16, IP_HAS_NOTRACK = 32, IP_USE_VEX3 = 64
}
The constants to describe instr prefixes if there are.
enum OperandType : unsigned { OPERAND_ROUNDING_CONTROL = MCOI::OPERAND_FIRST_TARGET, OPERAND_COND_CODE }
enum CondCode {
COND_O = 0, COND_NO = 1, COND_B = 2, COND_AE = 3,
COND_E = 4, COND_NE = 5, COND_BE = 6, COND_A = 7,
COND_S = 8, COND_NS = 9, COND_P = 10, COND_NP = 11,
COND_L = 12, COND_GE = 13, COND_LE = 14, COND_G = 15,
LAST_VALID_COND = COND_G, COND_NE_OR_P, COND_E_AND_NP, COND_INVALID
}
enum FirstMacroFusionInstKind {
FirstMacroFusionInstKind::Test, FirstMacroFusionInstKind::Cmp, FirstMacroFusionInstKind::And, FirstMacroFusionInstKind::AddSub,
FirstMacroFusionInstKind::IncDec, FirstMacroFusionInstKind::Invalid
}
enum SecondMacroFusionInstKind { SecondMacroFusionInstKind::AB, SecondMacroFusionInstKind::ELG, SecondMacroFusionInstKind::SPO, SecondMacroFusionInstKind::Invalid }
enum AlignBranchBoundaryKind : uint8_t {
AlignBranchNone = 0, AlignBranchFused = 1U << 0, AlignBranchJcc = 1U << 1, AlignBranchJmp = 1U << 2,
AlignBranchCall = 1U << 3, AlignBranchRet = 1U << 4, AlignBranchIndirect = 1U << 5
}
Defines the possible values of the branch boundary alignment mask.
enum Fixups {
reloc_riprel_4byte = FirstTargetFixupKind, reloc_riprel_4byte_movq_load, reloc_riprel_4byte_relax, reloc_riprel_4byte_relax_rex,
reloc_signed_4byte, reloc_signed_4byte_relax, reloc_global_offset_table, reloc_global_offset_table8,
reloc_branch_4byte_pcrel, LastTargetFixupKind, NumTargetFixupKinds = LastTargetFixupKind - FirstTargetFixupKind
}
enum AsmComments { AC_EVEX_2_VEX = MachineInstr::TAsmComments }
Functions
FirstMacroFusionInstKind classifyFirstOpcodeInMacroFusion (unsigned Opcode)
SecondMacroFusionInstKind classifySecondCondCodeInMacroFusion (X86::CondCode CC)
bool isMacroFused (FirstMacroFusionInstKind FirstKind, SecondMacroFusionInstKind SecondKind)
std::pair< CondCode, bool > getX86ConditionCode (CmpInst::Predicate Predicate)
Return a pair of condition code for the given predicate and whether the instruction operands should be swaped to match the condition code.
unsigned getSETOpc (bool HasMemoryOperand=false)
Return a setcc opcode based on whether it has a memory operand.
unsigned getCMovOpcode (unsigned RegBytes, bool HasMemoryOperand=false)
Return a cmov opcode for the given register size in bytes, and operand type.
CondCode getCondFromBranch (const MachineInstr &MI)
CondCode getCondFromSETCC (const MachineInstr &MI)
Return condition code of a SETCC opcode.
CondCode getCondFromCMov (const MachineInstr &MI)
Return condition code of a CMov opcode.
CondCode GetOppositeBranchCondition (CondCode CC)
GetOppositeBranchCondition - Return the inverse of the specified cond, e.g.
unsigned getVPCMPImmForCond (ISD::CondCode CC)
Get the VPCMP immediate for the given condition.
unsigned getSwappedVPCMPImm (unsigned Imm)
Get the VPCMP immediate if the opcodes are swapped.
unsigned getSwappedVPCOMImm (unsigned Imm)
Get the VPCOM immediate if the opcodes are swapped.
unsigned getSwappedVCMPImm (unsigned Imm)
Get the VCMP immediate if the opcodes are swapped.
bool isConstantSplat (SDValue Op, APInt &SplatVal)
If Op is a constant whose elements are all the same constant or undefined, return true and return the constant value in SplatVal.
bool isZeroNode (SDValue Elt)
Returns true if Elt is a constant zero or floating point constant +0.0.
bool isOffsetSuitableForCodeModel (int64_t Offset, CodeModel::Model M, bool hasSymbolicDisplacement=true)
Returns true of the given offset can be fit into displacement field of the instruction.
bool isCalleePop (CallingConv::ID CallingConv, bool is64Bit, bool IsVarArg, bool GuaranteeTCO)
Determines whether the callee is required to pop its own arguments.
FastISel * createFastISel (FunctionLoweringInfo &funcInfo, const TargetLibraryInfo *libInfo)
Detailed Description
Define some predicates that are used for node matching.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BX_SI
BX_DI
BP_SI
BP_DI
sib
sib64
Definition at line 1643 of file X86Disassembler.cpp.
anonymous enum
anonymous enum
Enumerator
AddrBaseReg
AddrScaleAmt
AddrIndexReg
AddrDisp
AddrSegmentReg
AddrSegmentReg - The operand # of the segment in the memory operand.
AddrNumOperands
AddrNumOperands - Total number of operands in a memory reference.
Definition at line 31 of file X86BaseInfo.h.
AlignBranchBoundaryKind
enum llvm::X86::AlignBranchBoundaryKind : uint8_t
Defines the possible values of the branch boundary alignment mask.
Enumerator
AlignBranchNone
AlignBranchFused
AlignBranchJcc
AlignBranchJmp
AlignBranchCall
AlignBranchRet
AlignBranchIndirect
Definition at line 350 of file X86BaseInfo.h.
AsmComments
enum llvm::X86::AsmComments
Enumerator
AC_EVEX_2_VEX
Definition at line 33 of file X86InstrInfo.h.
CondCode
enum llvm::X86::CondCode
Enumerator
COND_O
COND_NO
COND_B
COND_AE
COND_E
COND_NE
COND_BE
COND_A
COND_S
COND_NS
COND_P
COND_NP
COND_L
COND_GE
COND_LE
COND_G
LAST_VALID_COND
COND_NE_OR_P
COND_E_AND_NP
COND_INVALID
Definition at line 75 of file X86BaseInfo.h.
FirstMacroFusionInstKind
enum llvm::X86::FirstMacroFusionInstKind strong
Enumerator
Test
Cmp
And
AddSub
IncDec
Invalid
Definition at line 106 of file X86BaseInfo.h.
Fixups
enum llvm::X86::Fixups
Enumerator
reloc_riprel_4byte
reloc_riprel_4byte_movq_load
reloc_riprel_4byte_relax
reloc_riprel_4byte_relax_rex
reloc_signed_4byte
reloc_signed_4byte_relax
reloc_global_offset_table
reloc_global_offset_table8
reloc_branch_4byte_pcrel
LastTargetFixupKind
NumTargetFixupKinds
Definition at line 16 of file X86FixupKinds.h.
IPREFIXES
enum llvm::X86::IPREFIXES
The constants to describe instr prefixes if there are.
Enumerator
IP_NO_PREFIX
IP_HAS_OP_SIZE
IP_HAS_AD_SIZE
IP_HAS_REPEAT_NE
IP_HAS_REPEAT
IP_HAS_LOCK
IP_HAS_NOTRACK
IP_USE_VEX3
Definition at line 56 of file X86BaseInfo.h.
OperandType
enum llvm::X86::OperandType : unsigned
Enumerator
OPERAND_ROUNDING_CONTROL
AVX512 embedded rounding control. This should only have values 0-3.
OPERAND_COND_CODE
Definition at line 67 of file X86BaseInfo.h.
ProcessorFeatures
enum llvm::X86::ProcessorFeatures
Definition at line 68 of file TargetParser.h.
ProcessorSubtypes
enum llvm::X86::ProcessorSubtypes : unsigned
Enumerator
CPU_SUBTYPE_DUMMY
CPU_SUBTYPE_MAX
Definition at line 58 of file TargetParser.h.
ProcessorTypes
enum llvm::X86::ProcessorTypes : unsigned
Enumerator
CPU_TYPE_DUMMY
CPU_TYPE_MAX
Definition at line 48 of file TargetParser.h.
ProcessorVendors
enum llvm::X86::ProcessorVendors : unsigned
Enumerator
VENDOR_DUMMY
VENDOR_OTHER
Definition at line 38 of file TargetParser.h.
SecondMacroFusionInstKind
enum llvm::X86::SecondMacroFusionInstKind strong
Enumerator
AB
ELG
SPO
Invalid
Definition at line 121 of file X86BaseInfo.h.
STATIC_ROUNDING
enum llvm::X86::STATIC_ROUNDING
AVX512 static rounding constants.
These need to match the values in avx512fintrin.h.
Enumerator
TO_NEAREST_INT
TO_NEG_INF
TO_POS_INF
TO_ZERO
CUR_DIRECTION
NO_EXC
Definition at line 46 of file X86BaseInfo.h.
Function Documentation
classifyFirstOpcodeInMacroFusion()
FirstMacroFusionInstKind llvm::X86::classifyFirstOpcodeInMacroFusion (unsigned Opcode) inline
Returns
the type of the first instruction in macro-fusion.
Definition at line 134 of file X86BaseInfo.h.
References AddSub, And, Cmp, IncDec, Invalid, and Test.
Referenced by classifyFirst(), and isFirstMacroFusibleInst().
classifySecondCondCodeInMacroFusion()
SecondMacroFusionInstKind llvm::X86::classifySecondCondCodeInMacroFusion (X86::CondCode CC) inline
Returns
the type of the second instruction in macro-fusion.
Definition at line 282 of file X86BaseInfo.h.
References AB, COND_A, COND_AE, COND_B, COND_BE, COND_E, COND_G, COND_GE, COND_INVALID, COND_L, COND_LE, COND_NE, COND_NO, COND_NP, COND_NS, COND_O, COND_P, COND_S, ELG, Invalid, and SPO.
Referenced by classifySecond(), and classifySecondInstInMacroFusion().
createFastISel()
FastISel * llvm::X86::createFastISel (FunctionLoweringInfo & funcInfo, const TargetLibraryInfo * libInfo)
Definition at line 4009 of file X86FastISel.cpp.
Referenced by llvm::X86TargetLowering::createFastISel(), llvm::X86TargetLowering::getClearCacheBuiltinName(), and llvm::X86TargetLowering::getMaxSupportedInterleaveFactor().
getCMovOpcode()
unsigned llvm::X86::getCMovOpcode (unsigned RegBytes, bool HasMemoryOperand = false)
Return a cmov opcode for the given register size in bytes, and operand type.
Definition at line 2303 of file X86InstrInfo.cpp.
References llvm_unreachable.
Referenced by getRegClassForUnfoldedLoad(), llvm::X86InstrInfo::insertSelect(), and isEFLAGSLive().
getCondFromBranch()
X86::CondCode llvm::X86::getCondFromBranch (const MachineInstr & MI)
Definition at line 2185 of file X86InstrInfo.cpp.
References COND_INVALID, llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::getOperand().
Referenced by classifySecond(), findUncondBrI(), hasVulnerableLoad(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::removeBranch(), llvm::X86InstrInfo::replaceBranchWithTailCall(), and splitBlock().
getCondFromCMov()
X86::CondCode llvm::X86::getCondFromCMov (const MachineInstr & MI)
Return condition code of a CMov opcode.
Definition at line 2205 of file X86InstrInfo.cpp.
References COND_INVALID, llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::getOperand().
Referenced by llvm::X86InstrInfo::optimizeCompareInstr(), and packCmovGroup().
getCondFromSETCC()
X86::CondCode llvm::X86::getCondFromSETCC (const MachineInstr & MI)
Return condition code of a SETCC opcode.
Definition at line 2195 of file X86InstrInfo.cpp.
References COND_INVALID, llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::getOperand().
Referenced by llvm::X86InstrInfo::optimizeCompareInstr().
GetOppositeBranchCondition()
X86::CondCode llvm::X86::GetOppositeBranchCondition (X86::CondCode CC)
GetOppositeBranchCondition - Return the inverse of the specified cond, e.g.
Return the inverse of the specified condition, e.g.
turning COND_E to COND_NE.
Definition at line 2217 of file X86InstrInfo.cpp.
References COND_A, COND_AE, COND_B, COND_BE, COND_E, COND_E_AND_NP, COND_G, COND_GE, COND_L, COND_LE, COND_NE, COND_NE_OR_P, COND_NO, COND_NP, COND_NS, COND_O, COND_P, COND_S, and llvm_unreachable.
Referenced by checkBoolTestSetCCCombine(), llvm::X86InstrInfo::commuteInstructionImpl(), createPHIsForCMOVsInSinkBB(), EmitAVX512Test(), foldXor1SetCC(), and packCmovGroup().
getSETOpc()
unsigned llvm::X86::getSETOpc (bool HasMemoryOperand = false)
Return a setcc opcode based on whether it has a memory operand.
Return a setcc opcode based on whether it has memory operand.
Definition at line 2298 of file X86InstrInfo.cpp.
getSwappedVCMPImm()
unsigned llvm::X86::getSwappedVCMPImm (unsigned Imm)
Get the VCMP immediate if the opcodes are swapped.
Get the VCMP immediate if the operands are swapped.
Definition at line 2366 of file X86InstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::X86InstrInfo::commuteInstructionImpl().
getSwappedVPCMPImm()
unsigned llvm::X86::getSwappedVPCMPImm (unsigned Imm)
Get the VPCMP immediate if the opcodes are swapped.
Get the VPCMP immediate if the operands are swapped.
Definition at line 2330 of file X86InstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::X86InstrInfo::commuteInstructionImpl().
getSwappedVPCOMImm()
unsigned llvm::X86::getSwappedVPCOMImm (unsigned Imm)
Get the VPCOM immediate if the opcodes are swapped.
Get the VPCOM immediate if the operands are swapped.
Definition at line 2348 of file X86InstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::X86InstrInfo::commuteInstructionImpl().
getVPCMPImmForCond()
unsigned llvm::X86::getVPCMPImmForCond (ISD::CondCode CC)
Get the VPCMP immediate for the given condition.
Definition at line 2313 of file X86InstrInfo.cpp.
References llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
getX86ConditionCode()
std::pair< X86::CondCode, bool > llvm::X86::getX86ConditionCode (CmpInst::Predicate Predicate)
Return a pair of condition code for the given predicate and whether the instruction operands should be swaped to match the condition code.
Definition at line 2260 of file X86InstrInfo.cpp.
References COND_A, COND_AE, COND_B, COND_BE, COND_E, COND_G, COND_GE, COND_INVALID, COND_L, COND_LE, COND_NE, COND_NP, COND_P, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and LLVM_FALLTHROUGH.
Referenced by canTurnIntoCOPY(), and X86ChooseCmpImmediateOpcode().
isCalleePop()
bool llvm::X86::isCalleePop (CallingConv::ID CallingConv, bool is64Bit, bool IsVarArg, bool GuaranteeTCO)
Determines whether the callee is required to pop its own arguments.
Callee pop is necessary to support tail calls.
Definition at line 4792 of file X86ISelLowering.cpp.
References is64Bit(), shouldGuaranteeTCO(), llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::CallingConv::X86_VectorCall.
Referenced by computeBytesPoppedByCalleeForSRet(), getMOVL(), isSortedByValueNo(), and MatchingStackOffset().
isConstantSplat()
bool llvm::X86::isConstantSplat (SDValue Op, APInt & SplatVal)
If Op is a constant whose elements are all the same constant or undefined, return true and return the constant value in SplatVal.
Definition at line 6471 of file X86ISelLowering.cpp.
References llvm::numbers::e, llvm::SDValue::getScalarValueSizeInBits(), and getTargetConstantBitsFromNode().
Referenced by LowerFunnelShift(), and LowerScalarImmediateShift().
isMacroFused()
bool llvm::X86::isMacroFused (FirstMacroFusionInstKind FirstKind, SecondMacroFusionInstKind SecondKind) inline
Parameters
FirstKind kind of the first instruction in macro fusion.
SecondKind kind of the second instruction in macro fusion.
Returns
true if the two instruction can be macro fused.
Definition at line 331 of file X86BaseInfo.h.
References AB, AddSub, And, Cmp, ELG, IncDec, Invalid, llvm_unreachable, and Test.
Referenced by canReuseBoundaryAlignFragment(), isFirstMacroFusibleInst(), and shouldScheduleAdjacent().
isOffsetSuitableForCodeModel()
bool llvm::X86::isOffsetSuitableForCodeModel (int64_t Offset, CodeModel::Model M, bool hasSymbolicDisplacement = true)
Returns true of the given offset can be fit into displacement field of the instruction.
Definition at line 4760 of file X86ISelLowering.cpp.
References llvm::isInt< 32 >(), llvm::CodeModel::Kernel, and llvm::CodeModel::Small.
Referenced by isDispSafeForFrameIndex(), llvm::X86TargetLowering::isLegalAddressingMode(), and LowerEXTRACT_SUBVECTOR().
isZeroNode()
bool llvm::X86::isZeroNode (SDValue Elt)
Returns true if Elt is a constant zero or floating point constant +0.0.
Returns true if Elt is a constant zero or a floating point constant +0.0.
Definition at line 5515 of file X86ISelLowering.cpp.
References llvm::isNullConstant(), and llvm::isNullFPConstant().
Referenced by combineADC(), combineAddOrSubToADCOrSBB(), computeZeroableShuffleElements(), EltsFromConsecutiveLoads(), getFauxShuffleMask(), getMaskNode(), getTargetShuffleAndZeroables(), InsertBitToMaskVector(), LowerBUILD_VECTORAsVariablePermute(), LowerBuildVectorv4x32(), and LowerSCALAR_TO_VECTOR().