LLVM: llvm::sys::path Namespace Reference
llvm::sys::path Namespace Reference
Classes
class const_iterator
Path iterator.
class reverse_iterator
Reverse path iterator.
Enumerations
enum Style { Style::windows, Style::posix, Style::native }
Functions
static SmallString< 256 > remove_dots (StringRef path, bool remove_dot_dot, Style style)
Lexical Component Iterator
const_iterator begin (StringRef path, Style style=Style::native)
Get begin iterator over path.
const_iterator end (StringRef path)
Get end iterator over path.
reverse_iterator rbegin (StringRef path, Style style=Style::native)
Get reverse begin iterator over path.
reverse_iterator rend (StringRef path)
Get reverse end iterator over path.
Lexical Modifiers
void remove_filename (SmallVectorImpl< char > &path, Style style=Style::native)
Remove the last component from path unless it is the root dir.
void replace_extension (SmallVectorImpl< char > &path, const Twine &extension, Style style=Style::native)
Replace the file extension of path with extension.
bool replace_path_prefix (SmallVectorImpl< char > &Path, const StringRef &OldPrefix, const StringRef &NewPrefix, Style style=Style::native, bool strict=false)
Replace matching path prefix with another path.
void append (SmallVectorImpl< char > &path, const Twine &a, const Twine &b="", const Twine &c="", const Twine &d="")
Append to path.
void append (SmallVectorImpl< char > &path, Style style, const Twine &a, const Twine &b="", const Twine &c="", const Twine &d="")
void append (SmallVectorImpl< char > &path, const_iterator begin, const_iterator end, Style style=Style::native)
Append to path.
Transforms (or some other better name)
void native (const Twine &path, SmallVectorImpl< char > &result, Style style=Style::native)
Convert path to the native form.
void native (SmallVectorImpl< char > &path, Style style=Style::native)
Convert path to the native form in place.
std::string convert_to_slash (StringRef path, Style style=Style::native)
Replaces backslashes with slashes if Windows.
Lexical Observers
StringRef root_name (StringRef path, Style style=Style::native)
Get root name.
StringRef root_directory (StringRef path, Style style=Style::native)
Get root directory.
StringRef root_path (StringRef path, Style style=Style::native)
Get root path.
StringRef relative_path (StringRef path, Style style=Style::native)
Get relative path.
StringRef parent_path (StringRef path, Style style=Style::native)
Get parent path.
StringRef filename (StringRef path, Style style=Style::native)
Get filename.
StringRef stem (StringRef path, Style style=Style::native)
Get stem.
StringRef extension (StringRef path, Style style=Style::native)
Get extension.
bool is_separator (char value, Style style=Style::native)
Check whether the given char is a path separator on the host OS.
StringRef get_separator (Style style=Style::native)
Return the preferred separator for this platform.
void system_temp_directory (bool erasedOnReboot, SmallVectorImpl< char > &result)
Get the typical temporary directory for the system, e.g., "/var/tmp" or "C:/TEMP".
bool home_directory (SmallVectorImpl< char > &result)
Get the user's home directory.
bool has_root_name (const Twine &path, Style style=Style::native)
Has root name?
bool has_root_directory (const Twine &path, Style style=Style::native)
Has root directory?
bool has_root_path (const Twine &path, Style style=Style::native)
Has root path?
bool has_relative_path (const Twine &path, Style style=Style::native)
Has relative path?
bool has_parent_path (const Twine &path, Style style=Style::native)
Has parent path?
bool has_filename (const Twine &path, Style style=Style::native)
Has filename?
bool has_stem (const Twine &path, Style style=Style::native)
Has stem?
bool has_extension (const Twine &path, Style style=Style::native)
Has extension?
bool is_absolute (const Twine &path, Style style=Style::native)
Is path absolute?
bool is_relative (const Twine &path, Style style=Style::native)
Is path relative?
StringRef remove_leading_dotslash (StringRef path, Style style=Style::native)
Remove redundant leading "./" pieces and consecutive separators.
bool remove_dots (SmallVectorImpl< char > &path, bool remove_dot_dot=false, Style style=Style::native)
In-place remove any '.
Enumeration Type Documentation
Style
enum llvm::sys::path::Style strong
Enumerator
windows
posix
native
Definition at line 28 of file Path.h.
Function Documentation
append() [1/3]
void llvm::sys::path::append (SmallVectorImpl< char > & path, const Twine & a, const Twine & b = "", const Twine & c = "", const Twine & d = "")
Append to path.
/foo  + bar/f => /foo/bar/f
/foo/ + bar/f => /foo/bar/f
foo   + bar/f => foo/bar/f
Parameters
path Set to path + component.
a The component to be appended to path.
Definition at line 455 of file Path.cpp.
References llvm::support::native.
Referenced by llvm::FileCollector::addFile(), llvm::opt::DerivedArgList::AddFlagArg(), llvm::opt::DerivedArgList::AddJoinedArg(), llvm::opt::DerivedArgList::AddPositionalArg(), llvm::opt::DerivedArgList::AddSeparateArg(), append(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::append(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::assign(), llvm::computeArchiveRelativePath(), llvm::createControlHeightReductionLegacyPass(), llvm::sys::fs::createUniquePath(), llvm::remarks::createYAMLParserFromMeta(), llvm::HexagonShuffler::end(), ExpandResponseFile(), llvm::FileCollector::FileCollector(), llvm::LiveRange::findIndexesLiveAt(), llvm::sys::Process::FindInEnvPath(), findInputFile(), findSrcDirMap(), llvm::symbolize::LLVMSymbolizer::flush(), llvm::DiagnosticLocation::getAbsolutePath(), llvm::LineEditor::getDefaultHistoryPath(), getFilename(), llvm::DWARFDebugLine::Prologue::getFileNameByIndex(), llvm::object::Archive::Child::getFullName(), llvm::unittest::getInputFileDirectory(), llvm::gsym::LookupResult::getSourceFile(), getVFSEntries(), greaterWithBias(), llvm::detail::IEEEFloat::IEEEFloat(), llvm::vfs::VFSFromYamlDirIterImpl::increment(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::insert(), llvm::lto::localCache(), llvm::sys::fs::make_absolute(), llvm::sys::path::reverse_iterator::operator*(), printDwarfFileDirective(), processRemarkVersion(), llvm::pruneCache(), llvm::cl::readConfigFile(), remove_dots(), llvm::sys::fs::directory_entry::replace_filename(), replace_path_prefix(), llvm::CachedPathResolver::resolve(), llvm::rdf::NodeBase::setFlags(), llvm::MCContext::setGenDwarfRootFile(), llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >::SmallVector(), llvm::opt::ArgList::toOptSpecifier(), llvm::detail::IEEEFloat::toString(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), and llvm::ThinLTOCodeGenerator::writeGeneratedObject().
append() [2/3]
void llvm::sys::path::append (SmallVectorImpl< char > & path, Style style, const Twine & a, const Twine & b = "", const Twine & c = "", const Twine & d = "")
Definition at line 417 of file Path.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::SmallVectorBase::empty(), llvm::StringRef::end(), has_root_name(), is_separator(), llvm::Twine::isTriviallyEmpty(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), and llvm::Twine::toStringRef().
append() [3/3]
void llvm::sys::path::append (SmallVectorImpl< char > & path, const_iterator begin, const_iterator end, Style style = Style::native)
Append to path.
/foo  + [bar,f] => /foo/bar/f
/foo/ + [bar,f] => /foo/bar/f
foo   + [bar,f] => foo/bar/f
Parameters
path Set to path + [begin, end).
begin Start of components to append.
end One past the end of components to append.
Definition at line 460 of file Path.cpp.
References append(), begin(), and end().
begin()
const_iterator llvm::sys::path::begin (StringRef path, Style style = Style::native)
Get begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first component of path.
Definition at line 224 of file Path.cpp.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), addReadAttrs(), llvm::DWARFUnitVector::addUnit(), llvm::DWARFUnitVector::addUnitsForDWOSection(), llvm::adl_detail::adl_begin(), allocateVGPR32Input(), append(), llvm::MemoryDepChecker::areDepsSafe(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::assign(), llvm::IntrusiveBackList< llvm::DIE >::begin(), llvm::detail::enumerator< R >::begin(), llvm::ScheduleDAGMI::bottom(), llvm::DICompositeType::buildODRType(), canTurnIntoCOPY(), llvm::capacity_in_bytes(), CC_RISCV_FastCC(), CC_X86_64_VectorCallGetGPRs(), CC_X86_VectorCallGetSSEs(), llvm::LoopBodyTraits::child_begin(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::clear(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::clear(), llvm::computeArchiveRelativePath(), llvm::ImmutableList< T >::contains(), llvm::detail::IEEEFloat::convertFromZeroExtendedInteger(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::copy(), llvm::LiveRange::covers(), llvm::pdb::SymbolCache::createGlobalsEnumerator(), llvm::OpenMPIRBuilder::CreateParallel(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::ScheduleDAGInstrs::doMBBSchedRegionsTopDown(), llvm::VarStreamArray< LineColumnEntry, LineColumnExtractor >::drop_front(), llvm::DomTreeUpdater::dump(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::MachineInstrSpan::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::AttributeSetNode::end(), llvm::AttributeListImpl::end(), llvm::ListInit::end(), llvm::Registry< T >::entries(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::equals(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::erase(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::erase(), llvm::LiveRange::find(), llvm::MustBeExecutedContextExplorer::findInContextOf(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::findIndex(), findTemporariesForLR(), foldConstantInsEltIntoShuffle(), llvm::SmallVectorTemplateCommon< T >::front(), llvm::FixedStreamArray< PSHashRecord >::front(), get64BitArgumentGPRs(), get64BitArgumentXMMs(), getAllSGPR128(), getAllSGPRs(), llvm::AttributeSetNode::getAsString(), llvm::MCObjectStreamer::getCurrentFragment(), getFeatures(), getFirstReloc(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::getIntrinsicWithChain(), llvm::getIntrinsicWithoutChain(), llvm::AVRMCExpr::getKindByName(), llvm::AVRMCExpr::getName(), getNewDefiningAccessForClone(), getOutliningPenalty(), getPrefixes(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::getPrevNode(), llvm::R600RegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::ScheduleDAGMILive::getScheduledTrees(), llvm::DWARFUnitVector::getUnitForIndexEntry(), llvm::DWARFUnitVector::getUnitForOffset(), llvm::SmallVectorTemplateBase< T >::grow(), llvm::codeview::LocallyHashedType::hashTypes(), llvm::TargetLoweringBase::initActions(), INITIALIZE_PASS(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::insert(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::insert(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::insertAfter(), isAlwaysFoldable(), llvm::AArch64RegisterInfo::isAnyArgRegReserved(), isDebug(), isF128SoftLibCall(), isImageOrSamplerVal(), isIntrinsicInline(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), llvm::LiveRange::join(), llvm::StringMap< uint64_t >::keys(), LLVMGetFirstTarget(), llvm::coverage::CoverageMapping::load(), lookupFoldTableImpl(), llvm::vfs::lookupInMemoryNode(), LookupNEONLdSt(), llvm::TargetRegistry::lookupTarget(), lowerV8I16GeneralSingleInputShuffle(), llvm::MachineTraceMetrics::MachineTraceMetrics(), llvm::make_early_inc_range(), llvm::make_filter_range(), llvm::make_pointee_range(), llvm::make_pointer_range(), llvm::makeArrayRef(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::makeNodeArray(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::max_size(), mayUsePostIncMode(), llvm::LiveRange::MergeValueNumberInto(), node_eq(), llvm::GraphTraits< MachineRegionInfo * >::nodes_begin(), llvm::GraphTraits< RegionInfo * >::nodes_begin(), llvm::GraphTraits< VPRegionBlock * >::nodes_begin(), llvm::GraphTraits< const VPRegionBlock * >::nodes_begin(), llvm::GraphTraits< Inverse< VPRegionBlock * > >::nodes_begin(), llvm::CallBase::operandBundleFromBundleOpInfo(), llvm::sys::path::reverse_iterator::operator*(), llvm::Registry< T >::iterator::operator*(), llvm::PooledStringPtr::operator*(), llvm::pointee_iterator< WrappedIteratorT, T >::operator*(), llvm::pointer_iterator< WrappedIteratorT, T >::operator*(), AllocaSlices::partition_iterator::operator*(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::operator<(), llvm::TargetLibraryInfoImpl::operator=(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::operator=(), llvm::FeatureBitset::operator==(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::operator==(), llvm::SmallVectorTemplateCommon< T >::operator[](), PODSmallVector< Node *, 8 >::operator[](), llvm::LiveRange::overlapsFrom(), llvm::OwningArrayRef< T >::OwningArrayRef(), llvm::vfs::RedirectingFileSystemParser::parse(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::RegisterBankInfo::ValueMapping::partsAllUniform(), pathHasTraversal(), performCustomAdjustments(), llvm::MachineBasicBlock::phis(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::pop_front(), llvm::MIBundleBuilder::prepend(), llvm::DominanceFrontierBase< BasicBlock, false >::print(), llvm::LoopBase< BasicBlock, Loop >::print(), printMCExpr(), llvm::AttributeSetNode::Profile(), ProfitableToMerge(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::push_front(), llvm::MustBeExecutedContextExplorer::range(), llvm::readExponent(), llvm::orc::SymbolLookupSet::remove(), remove_dots(), llvm::DominanceFrontierBase< BasicBlock, false >::removeBlock(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::RegionBase< RegionTraits< Function > >::removeSubRegion(), llvm::SmallVectorTemplateCommon< T >::rend(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::rend(), llvm::MutableArrayRef< BitWord >::rend(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::resize(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::reverse(), root_directory(), root_name(), root_path(), llvm::ReservoirSampler< T, GenT >::sample(), llvm::VLIWMachineScheduler::schedule(), llvm::ScheduleDAGMI::schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::object::COFFObjectFile::section_rel_begin(), llvm::FeatureBitset::set(), setRequiredFeatureString(), llvm::skipLeadingZeroesAndAnyDot(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::HexagonBlockRanges::RangeList::subtract(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::swap(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::take_until(), llvm::MutableArrayRef< BitWord >::take_until(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::take_while(), llvm::MutableArrayRef< BitWord >::take_while(), llvm::TargetLibraryInfoImpl::TargetLibraryInfoImpl(), llvm::TargetLoweringBase::TargetLoweringBase(), llvm::to_vector(), llvm::vfs::InMemoryFileSystem::toString(), llvm::HexagonBlockRanges::RangeList::unionize(), llvm::UnrollAndJamLoop(), llvm::MemorySSAUpdater::updateExitBlocksForClonedLoop(), llvm::TargetLoweringBase::ValueTypeActionImpl::ValueTypeActionImpl(), llvm::LiveRange::verify(), llvm::LoopInfoBase< BasicBlock, Loop >::verify(), llvm::verifyIntrinsicTables(), llvm::LoopBase< BasicBlock, Loop >::verifyLoop(), llvm::LoopBase< BasicBlock, Loop >::verifyLoopNest(), verifyTables(), writeIdentificationBlock(), llvm::AntiDepBreaker::~AntiDepBreaker(), llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >::~SmallVector(), and llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::~SmallVectorImpl().
convert_to_slash()
std::string llvm::sys::path::convert_to_slash (StringRef path, Style style = Style::native)
Replaces backslashes with slashes if Windows.
Parameters
path processed path
Returns
The result of replacing backslashes with forward slashes if Windows. On Unix, this function is a no-op because backslashes are valid path chracters.
Definition at line 579 of file Path.cpp.
References replace(), and llvm::StringRef::str().
Referenced by llvm::TarWriter::append(), llvm::computeArchiveRelativePath(), and llvm::sys::path::reverse_iterator::operator*().
end()
const_iterator llvm::sys::path::end (StringRef path)
Get end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the end of path.
Definition at line 233 of file Path.cpp.
References llvm::StringRef::size().
Referenced by llvm::LiveRangeUpdater::add(), llvm::MachO::detail::addEntry(), llvm::vfs::YAMLVFSWriter::addFileMapping(), addReadAttrs(), llvm::LiveRange::addSegment(), llvm::DominanceFrontierBase< BasicBlock, false >::addToFrontier(), llvm::DWARFUnitVector::addUnit(), llvm::DWARFUnitVector::addUnitsForDWOSection(), llvm::adl_detail::adl_begin(), llvm::adl_detail::adl_end(), llvm::LiveRange::advanceTo(), append(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::append(), llvm::MIBundleBuilder::append(), llvm::VPBasicBlock::appendRecipe(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::assign(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::MachineBasicBlock::back(), llvm::FixedStreamArray< PSHashRecord >::back(), llvm::DenseMapBase< DenseMap< const llvm::SCEV *, const llvm::SCEV *, DenseMapInfo< const llvm::SCEV *>, llvm::detail::DenseMapPair< const llvm::SCEV *, const llvm::SCEV *> >, const llvm::SCEV *, const llvm::SCEV *, DenseMapInfo< const llvm::SCEV *>, llvm::detail::DenseMapPair< const llvm::SCEV *, const llvm::SCEV *> >::begin(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), llvm::IntrusiveBackList< llvm::DIE >::begin(), llvm::ScheduleDAGMI::bottom(), llvm::DICompositeType::buildODRType(), canBeFeederToNewValueJump(), canCompareBeNewValueJump(), canTurnIntoCOPY(), CC_RISCV_FastCC(), CC_X86_64_VectorCallGetGPRs(), CC_X86_VectorCallGetSSEs(), llvm::LiveIntervals::checkRegMaskInterference(), checkThreadCommand(), llvm::LoopBodyTraits::child_end(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::clear(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::clear(), llvm::DominanceFrontierBase< BasicBlock, false >::compare(), llvm::computeArchiveRelativePath(), llvm::ImmutableList< T >::contains(), llvm::LiveRange::Segment::contains(), llvm::LiveRange::Segment::containsInterval(), llvm::detail::IEEEFloat::convertFromZeroExtendedInteger(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::copy(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::count(), llvm::SmallPtrSetImpl< const llvm::SCEV * >::count(), llvm::StringMap< uint64_t >::count(), llvm::LiveRange::covers(), llvm::createCopyConstrainDAGMutation(), llvm::pdb::SymbolCache::createGlobalsEnumerator(), llvm::OpenMPIRBuilder::CreateParallel(), llvm::decodeSLEB128(), llvm::decodeULEB128(), llvm::LegalizerInfo::decreaseToSmallerTypesAndIncreaseToSmallest(), llvm::ScheduleDAGInstrs::doMBBSchedRegionsTopDown(), dominatesAllUsesOf(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::drop_until(), llvm::MutableArrayRef< BitWord >::drop_until(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::drop_while(), llvm::MutableArrayRef< BitWord >::drop_while(), llvm::DomTreeUpdater::dump(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::emplace_back(), llvm::MachineInstrSpan::empty(), llvm::detail::enumerator< R >::end(), llvm::Registry< T >::entries(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::equals(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::erase(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::erase(), llvm::StringMap< uint64_t >::erase(), ExpandCryptoAEK(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::DenseMapBase< DenseMap< const llvm::SCEV *, const llvm::SCEV *, DenseMapInfo< const llvm::SCEV *>, llvm::detail::DenseMapPair< const llvm::SCEV *, const llvm::SCEV *> >, const llvm::SCEV *, const llvm::SCEV *, DenseMapInfo< const llvm::SCEV *>, llvm::detail::DenseMapPair< const llvm::SCEV *, const llvm::SCEV *> >::find(), llvm::LiveRange::find(), llvm::StringMap< uint64_t >::find(), llvm::DenseMapBase< DenseMap< const llvm::SCEV *, const llvm::SCEV *, DenseMapInfo< const llvm::SCEV *>, llvm::detail::DenseMapPair< const llvm::SCEV *, const llvm::SCEV *> >, const llvm::SCEV *, const llvm::SCEV *, DenseMapInfo< const llvm::SCEV *>, llvm::detail::DenseMapPair< const llvm::SCEV *, const llvm::SCEV *> >::find_as(), llvm::MustBeExecutedContextExplorer::findInContextOf(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::findIndex(), llvm::LiveRange::FindSegmentContaining(), llvm::SSAUpdater::FindValueForBlock(), format_to_buffer(), generateEquivalentSub(), llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::get(), get64BitArgumentGPRs(), get64BitArgumentXMMs(), getAllocationDataForFunction(), llvm::AttributeSetNode::getAsString(), getFeatures(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::getIntrinsicWithChain(), llvm::getIntrinsicWithoutChain(), llvm::AVRMCExpr::getKindByName(), llvm::AVRMCExpr::getName(), getNegatibleInsts(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::getNextNode(), getPrefixes(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::R600RegisterInfo::getReservedRegs(), llvm::ScheduleDAGMILive::getScheduledTrees(), llvm::LiveRange::getSegmentContaining(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), llvm::DWARFUnitVector::getUnitForIndexEntry(), llvm::DWARFUnitVector::getUnitForOffset(), llvm::LiveRange::getVNInfoAt(), llvm::LiveRange::getVNInfoBefore(), llvm::SmallVectorTemplateBase< T >::grow(), llvm::hashing::detail::hash_combine_range_impl(), llvm::codeview::LocallyHashedType::hashTypes(), llvm::MachineInstr::implicit_operands(), llvm::TargetLoweringBase::initActions(), INITIALIZE_PASS(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::insert(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::insert(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::MemorySSAUpdater::insertDef(), llvm::interpretDecimal(), isAlwaysFoldable(), llvm::AArch64RegisterInfo::isAnyArgRegReserved(), isDebug(), isF128SoftLibCall(), isImageOrSamplerVal(), isIntrinsicInline(), llvm::LegalizerInfo::isLegal(), llvm::LiveRange::isLiveAtIndexes(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), llvm::SplitAnalysis::isOriginalEndpoint(), isUnconditionalBranch(), llvm::LiveRange::join(), llvm::StringMap< uint64_t >::keys(), llvm::LiveRange::liveAt(), LLVMGetFirstTarget(), llvm::coverage::CoverageMapping::load(), llvm::StringMap< uint64_t >::lookup(), lookupFoldTableImpl(), llvm::vfs::lookupInMemoryNode(), LookupNEONLdSt(), llvm::TargetRegistry::lookupTarget(), llvm::MachineTraceMetrics::MachineTraceMetrics(), llvm::make_early_inc_range(), llvm::make_filter_range(), llvm::make_pointee_range(), llvm::make_pointer_range(), llvm::makeArrayRef(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::max_size(), mayUsePostIncMode(), mergeOperations(), llvm::LiveRange::MergeValueNumberInto(), node_eq(), llvm::GraphTraits< MachineRegionInfo * >::nodes_end(), llvm::GraphTraits< RegionInfo * >::nodes_end(), llvm::GraphTraits< VPRegionBlock * >::nodes_end(), llvm::GraphTraits< const VPRegionBlock * >::nodes_end(), llvm::GraphTraits< Inverse< VPRegionBlock * > >::nodes_end(), llvm::sys::path::reverse_iterator::operator*(), AllocaSlices::partition_iterator::operator*(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::operator<(), llvm::TargetLibraryInfoImpl::operator=(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::operator=(), llvm::FeatureBitset::operator==(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::operator==(), llvm::LiveRange::overlaps(), llvm::LiveRange::overlapsFrom(), llvm::vfs::RedirectingFileSystemParser::parse(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::RegisterBankInfo::ValueMapping::partsAllUniform(), pathHasTraversal(), performCustomAdjustments(), llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::pop_back(), llvm::DominanceFrontierBase< BasicBlock, false >::print(), llvm::LoopBase< BasicBlock, Loop >::print(), printMCExpr(), llvm::AttributeSetNode::Profile(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::push_back(), llvm::LiveRange::Query(), llvm::MustBeExecutedContextExplorer::range(), llvm::SmallVectorTemplateCommon< T >::rbegin(), llvm::ArrayRef< llvm::irsymtab::storage::Comdat >::rbegin(), llvm::MutableArrayRef< BitWord >::rbegin(), llvm::readExponent(), remove_dots(), llvm::DominanceFrontierBase< BasicBlock, false >::removeBlock(), llvm::DominanceFrontierBase< BasicBlock, false >::removeFromFrontier(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::LiveRange::removeValNo(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::resize(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::reverse(), root_directory(), root_name(), root_path(), llvm::FeatureBitset::set(), setRequiredFeatureString(), llvm::skipLeadingZeroesAndAnyDot(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::Regex::sub(), llvm::MCRegisterInfo::subregs(), llvm::MCRegisterInfo::subregs_inclusive(), llvm::MCRegisterInfo::superregs(), llvm::MCRegisterInfo::superregs_inclusive(), llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >::swap(), llvm::TargetLibraryInfoImpl::TargetLibraryInfoImpl(), llvm::TargetLoweringBase::TargetLoweringBase(), llvm::MachineBasicBlock::terminators(), llvm::to_vector(), llvm::vfs::InMemoryFileSystem::toString(), llvm::APInt::toString(), llvm::totalExponent(), llvm::LiveIntervals::HMEditor::updateAllRanges(), llvm::MemorySSAUpdater::updateExitBlocksForClonedLoop(), llvm::utohexstr(), llvm::utostr(), llvm::TargetLoweringBase::ValueTypeActionImpl::ValueTypeActionImpl(), llvm::LiveRange::verify(), llvm::LoopInfoBase< BasicBlock, Loop >::verify(), llvm::verifyIntrinsicTables(), llvm::LoopBase< BasicBlock, Loop >::verifyLoop(), llvm::LoopBase< BasicBlock, Loop >::verifyLoopNest(), verifyTables(), llvm::VirtRegAuxInfo::VirtRegAuxInfo(), llvm::VirtRegAuxInfo::weightCalcHelper(), write_unsigned_impl(), llvm::AntiDepBreaker::~AntiDepBreaker(), and llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >::~SmallVector().
extension()
StringRef llvm::sys::path::extension (StringRef path, Style style = Style::native)
Get extension.
If filename contains a dot but not solely one or two dots, result is the substring of filename starting at (and including) the last dot, and ending at the end of path. Otherwise "".
/foo/bar.txt => .txt
/foo/bar     => <empty>
/foo/.txt    => .txt
Parameters
path Input path.
Returns
The extension of path.
Definition at line 603 of file Path.cpp.
References filename(), llvm::StringRef::find_last_of(), llvm::StringRef::npos, llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by llvm::DWARFContext::dump(), llvm::symbolize::LLVMSymbolizer::flush(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), has_extension(), and llvm::sys::path::reverse_iterator::operator*().
filename()
StringRef llvm::sys::path::filename (StringRef path, Style style = Style::native)
Get filename.
/foo.txt    => foo.txt
.          => .
..         => ..
/          => /
Parameters
path Input path.
Returns
The filename part of path. This is defined as the last component of path. Similar to the POSIX "basename" utility.
Definition at line 588 of file Path.cpp.
References rbegin().
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::Module::createRNG(), llvm::AsmPrinter::doInitialization(), llvm::ModuleSummaryIndex::exportToDot(), extension(), llvm::FileCollector::FileCollector(), FunctionNumber(), llvm::vfs::OverlayFileSystem::getRealPath(), llvm::pdb::PDBSymbolCompiland::getSourceFileName(), has_filename(), llvm::vfs::VFSFromYamlDirIterImpl::increment(), llvm::gsym::GsymCreator::insertFile(), llvm::sys::DynamicLibrary::isValid(), mangleCoveragePath(), llvm::sys::path::reverse_iterator::operator*(), llvm::pruneCache(), llvm::cl::ResetAllOptionOccurrences(), llvm::CachedPathResolver::resolve(), stem(), llvm::timeTraceProfilerInitialize(), and llvm::MCDwarfLineTableHeader::tryGetFile().
get_separator()
StringRef llvm::sys::path::get_separator (Style style = Style::native)
Return the preferred separator for this platform.
Returns
StringRef of the preferred separator, null-terminated.
Definition at line 624 of file Path.cpp.
Referenced by llvm::SourceMgr::AddIncludeFile(), and llvm::sys::path::reverse_iterator::operator*().
has_extension()
bool llvm::sys::path::has_extension (const Twine & path, Style style = Style::native)
Has extension?
extension != ""
Parameters
path Input path.
Returns
True if the path has a extension, false otherwise.
Definition at line 679 of file Path.cpp.
References llvm::StringRef::empty(), extension(), and llvm::Twine::toStringRef().
Referenced by llvm::sys::path::reverse_iterator::operator*().
has_filename()
bool llvm::sys::path::has_filename (const Twine & path, Style style = Style::native)
Has filename?
filename != ""
Parameters
path Input path.
Returns
True if the path has a filename, false otherwise.
Definition at line 658 of file Path.cpp.
References llvm::StringRef::empty(), filename(), and llvm::Twine::toStringRef().
Referenced by llvm::sys::path::reverse_iterator::operator*().
has_parent_path()
bool llvm::sys::path::has_parent_path (const Twine & path, Style style = Style::native)
Has parent path?
parent_path != ""
Parameters
path Input path.
Returns
True if the path has a parent path, false otherwise.
Definition at line 665 of file Path.cpp.
References llvm::StringRef::empty(), parent_path(), and llvm::Twine::toStringRef().
Referenced by llvm::sys::path::reverse_iterator::operator*().
has_relative_path()
bool llvm::sys::path::has_relative_path (const Twine & path, Style style = Style::native)
Has relative path?
relative_path != ""
Parameters
path Input path.
Returns
True if the path has a relative path, false otherwise.
Definition at line 651 of file Path.cpp.
References llvm::StringRef::empty(), relative_path(), and llvm::Twine::toStringRef().
Referenced by llvm::sys::path::reverse_iterator::operator*().
has_root_directory()
bool llvm::sys::path::has_root_directory (const Twine & path, Style style = Style::native)
Has root directory?
root_directory != ""
Parameters
path Input path.
Returns
True if the path has a root directory, false otherwise.
Definition at line 637 of file Path.cpp.
References llvm::StringRef::empty(), root_directory(), and llvm::Twine::toStringRef().
Referenced by is_absolute(), llvm::sys::fs::make_absolute(), and llvm::sys::path::reverse_iterator::operator*().
has_root_name()
bool llvm::sys::path::has_root_name (const Twine & path, Style style = Style::native)
Has root name?
root_name != ""
Parameters
path Input path.
Returns
True if the path has a root name, false otherwise.
Definition at line 630 of file Path.cpp.
References llvm::StringRef::empty(), root_name(), and llvm::Twine::toStringRef().
Referenced by append(), is_absolute(), llvm::sys::fs::make_absolute(), and llvm::sys::path::reverse_iterator::operator*().
has_root_path()
bool llvm::sys::path::has_root_path (const Twine & path, Style style = Style::native)
Has root path?
root_path != ""
Parameters
path Input path.
Returns
True if the path has a root path, false otherwise.
Definition at line 644 of file Path.cpp.
References llvm::StringRef::empty(), root_path(), and llvm::Twine::toStringRef().
Referenced by llvm::sys::path::reverse_iterator::operator*().
has_stem()
bool llvm::sys::path::has_stem (const Twine & path, Style style = Style::native)
Has stem?
stem != ""
Parameters
path Input path.
Returns
True if the path has a stem, false otherwise.
Definition at line 672 of file Path.cpp.
References llvm::StringRef::empty(), stem(), and llvm::Twine::toStringRef().
Referenced by llvm::sys::path::reverse_iterator::operator*().
home_directory()
bool llvm::sys::path::home_directory (SmallVectorImpl< char > & result)
Get the user's home directory.
Parameters
result Holds the resulting path name.
Returns
True if a home directory is set, false otherwise.
Referenced by llvm::LineEditor::getDefaultHistoryPath(), native(), and llvm::sys::path::reverse_iterator::operator*().
is_absolute()
bool llvm::sys::path::is_absolute (const Twine & path, Style style = Style::native)
Is path absolute?
Parameters
path Input path.
Returns
True if the path is absolute, false if it is not.
Definition at line 686 of file Path.cpp.
References has_root_directory(), has_root_name(), and llvm::Twine::toStringRef().
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::CodeViewDebug::CodeViewDebug(), llvm::sys::fs::createUniquePath(), ExpandResponseFile(), llvm::sys::Process::FindInEnvPath(), llvm::DiagnosticLocation::getAbsolutePath(), llvm::object::Archive::Child::getFullName(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), is_relative(), isPathAbsoluteOnWindowsOrPosix(), llvm::sys::fs::make_absolute(), llvm::vfs::FileSystem::makeAbsolute(), llvm::vfs::RedirectingFileSystem::makeAbsolute(), llvm::sys::path::reverse_iterator::operator*(), printDwarfFileDirective(), and remove_dots().
is_relative()
bool llvm::sys::path::is_relative (const Twine & path, Style style = Style::native)
Is path relative?
Parameters
path Input path.
Returns
True if the path is relative, false if it is not.
Definition at line 697 of file Path.cpp.
References is_absolute().
Referenced by ExpandResponseFile(), llvm::sys::path::reverse_iterator::operator*(), llvm::cl::readConfigFile(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
is_separator()
bool llvm::sys::path::is_separator (char value, Style style = Style::native)
Check whether the given char is a path separator on the host OS.
Parameters
value a character
Returns
true if value is a path separator character on the host OS
Definition at line 616 of file Path.cpp.
Referenced by append(), llvm::orc::DumpObjects::DumpObjects(), native(), llvm::sys::path::reverse_iterator::operator*(), llvm::sys::path::const_iterator::operator++(), llvm::sys::path::reverse_iterator::operator++(), remove_leading_dotslash(), replace_path_prefix(), root_directory(), root_name(), root_path(), llvm::MCContext::setGenDwarfRootFile(), and llvm::stripDirPrefix().
native() [1/2]
void llvm::sys::path::native (const Twine & path, SmallVectorImpl< char > & result, Style style = Style::native)
Convert path to the native form.
This is used to give paths to users and operating system calls in the platform's normal way. For example, on Windows all '/' are converted to '\'.
Parameters
path A path that is transformed to native format.
result Holds the result of the transformation.
Definition at line 545 of file Path.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::StringRef::data(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::Twine::getSingleStringRef(), llvm::Twine::isSingleStringRef(), and llvm::Twine::toVector().
Referenced by llvm::FileCollector::addFile(), llvm::pdb::PDBFileBuilder::addInjectedSource(), llvm::unittest::getInputFileDirectory(), and llvm::pruneCache().
native() [2/2]
void llvm::sys::path::native (SmallVectorImpl< char > & path, Style style = Style::native)
Convert path to the native form in place.
This is used to give paths to users and operating system calls in the platform's normal way. For example, on Windows all '/' are converted to '\'.
Parameters
path A path that is transformed to native format.
Definition at line 555 of file Path.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), home_directory(), is_separator(), replace(), and llvm::SmallVectorBase::size().
parent_path()
StringRef llvm::sys::path::parent_path (StringRef path, Style style = Style::native)
Get parent path.
/          => <empty>
/foo       => /
foo/../bar => foo/..
Parameters
path Input path.
Returns
The parent path of path if one exists, otherwise "".
Definition at line 466 of file Path.cpp.
References llvm::StringRef::npos, and llvm::StringRef::substr().
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::computeArchiveRelativePath(), llvm::FileCollector::copyFiles(), llvm::vfs::RedirectingFileSystem::create(), llvm::sys::fs::create_directories(), ExpandResponseFile(), llvm::FileCollector::FileCollector(), findSrcDirMap(), llvm::pdb::PDBFile::getFileDirectory(), llvm::object::Archive::Child::getFullName(), llvm::lto::getThinLTOOutputFile(), has_parent_path(), llvm::gsym::GsymCreator::insertFile(), llvm::sys::path::reverse_iterator::operator*(), printSymbolizedStackTrace(), llvm::sys::fs::directory_entry::replace_filename(), replace_path_prefix(), llvm::CachedPathResolver::resolve(), and llvm::MCDwarfLineTableHeader::tryGetFile().
rbegin()
reverse_iterator llvm::sys::path::rbegin (StringRef path, Style style = Style::native)
Get reverse begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first reverse component of path.
Definition at line 295 of file Path.cpp.
References I, and llvm::StringRef::size().
Referenced by filename(), llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::max_size(), and llvm::sys::path::reverse_iterator::operator*().
relative_path()
StringRef llvm::sys::path::relative_path (StringRef path, Style style = Style::native)
Get relative path.
C:\hello\world => hello\world
foo/bar        => foo/bar
/foo/bar       => foo/bar
Parameters
path Input path.
Returns
The path starting after root_path if one exists, otherwise "".
Definition at line 412 of file Path.cpp.
References root_path(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by llvm::FileCollector::addFile(), llvm::symbolize::LLVMSymbolizer::flush(), has_relative_path(), llvm::sys::fs::make_absolute(), llvm::sys::path::reverse_iterator::operator*(), remove_dots(), and replace_path_prefix().
remove_dots() [1/2]
bool llvm::sys::path::remove_dots (SmallVectorImpl< char > & path, bool remove_dot_dot = false, Style style = Style::native)
In-place remove any '.
/' and optionally '../' components from a path.
Parameters
path processed path
remove_dot_dot specify if '../' (except for leading "../") should be removed
Returns
True if path was changed
Definition at line 739 of file Path.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::data(), remove_dots(), llvm::SmallVectorBase::size(), and llvm::SmallVectorImpl< T >::swap().
Referenced by llvm::FileCollector::addFile(), llvm::vfs::InMemoryFileSystem::getRealPath(), llvm::vfs::lookupInMemoryNode(), llvm::vfs::RedirectingFileSystem::lookupPath(), llvm::sys::path::reverse_iterator::operator*(), llvm::vfs::InMemoryFileSystem::setCurrentWorkingDirectory(), and llvm::vfs::InMemoryFileSystem::toString().
remove_dots() [2/2]
static SmallString<256> llvm::sys::path::remove_dots (StringRef path, bool remove_dot_dot, Style style) static
Definition at line 711 of file Path.cpp.
References append(), llvm::SmallVectorTemplateCommon< T >::back(), begin(), C, llvm::SmallVectorBase::empty(), end(), is_absolute(), llvm::make_range(), llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorTemplateBase< T >::push_back(), relative_path(), and root_path().
Referenced by remove_dots().
remove_filename()
void llvm::sys::path::remove_filename (SmallVectorImpl< char > & path, Style style = Style::native)
Remove the last component from path unless it is the root dir.
Similar to the POSIX "dirname" utility.
directory/filename.cpp => directory/
directory/             => directory
filename.cpp           => <empty>
/                      => /
Parameters
path A path that is modified to not have a file component.
Definition at line 474 of file Path.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::npos, llvm::SmallVectorBase::set_size(), and llvm::SmallVectorBase::size().
Referenced by llvm::symbolize::LLVMSymbolizer::flush(), llvm::sys::path::reverse_iterator::operator*(), and llvm::MCContext::setGenDwarfRootFile().
remove_leading_dotslash()
StringRef llvm::sys::path::remove_leading_dotslash (StringRef path, Style style = Style::native)
Remove redundant leading "./" pieces and consecutive separators.
Parameters
path Input path.
Returns
The cleaned-up path.
Definition at line 701 of file Path.cpp.
References is_separator(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by llvm::FileCollector::addFile(), llvm::DiagnosticLocation::getAbsolutePath(), llvm::vfs::RedirectingFileSystem::lookupPath(), and llvm::sys::path::reverse_iterator::operator*().
rend()
reverse_iterator llvm::sys::path::rend (StringRef path)
Get reverse end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the reverse end of path.
Definition at line 304 of file Path.cpp.
References I, and llvm::StringRef::substr().
Referenced by llvm::iplist_impl< simple_ilist< MachineInstr, Options... >, ilist_traits< MachineInstr > >::max_size(), and llvm::sys::path::reverse_iterator::operator*().
replace_extension()
void llvm::sys::path::replace_extension (SmallVectorImpl< char > & path, const Twine & extension, Style style = Style::native)
Replace the file extension of path with extension.
./filename.cpp => ./filename.extension
./filename     => ./filename.extension
./             => ./.extension
Parameters
path A path that has its extension replaced with extension.
extension The extension to be added. It may be empty. It may also optionally start with a '.', if it does not, one will be prepended.
Definition at line 480 of file Path.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::end(), llvm::StringRef::find_last_of(), llvm::StringRef::npos, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), llvm::StringRef::size(), and llvm::Twine::toStringRef().
Referenced by getOutputPath(), and llvm::sys::path::reverse_iterator::operator*().
replace_path_prefix()
bool llvm::sys::path::replace_path_prefix (SmallVectorImpl< char > & Path, const StringRef & OldPrefix, const StringRef & NewPrefix, Style style = Style::native, bool strict = false)
Replace matching path prefix with another path.
/foo, /old, /new => /foo
/old, /old, /new => /new
/old, /old/, /new, false => /old
/old, /old/, /new, true => /new
/old/foo, /old, /new => /new/foo
/old/foo, /old/, /new => /new/foo
/old/foo, /old/, /new/ => /new/foo
/oldfoo, /old, /new => /oldfoo
/foo, <empty>, /new => /new/foo
/foo, <empty>, new => new/foo
/old/foo, /old, <empty>, false => /foo
/old/foo, /old, <empty>, true => foo
Parameters
Path If Path starts with OldPrefix modify to instead start with NewPrefix.
OldPrefix The path prefix to strip from Path. Any trailing path separator is ignored if strict is true.
NewPrefix The path prefix to replace NewPrefix with.
style The path separator style
strict If strict is true, a directory separator following OldPrefix will also be stripped. Otherwise, directory separators will only be matched and stripped when present in OldPrefix.
Returns
true if Path begins with OldPrefix
Definition at line 499 of file Path.cpp.
References append(), llvm::StringRef::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::copy(), llvm::StringRef::empty(), is_separator(), parent_path(), relative_path(), llvm::SmallVectorBase::size(), llvm::StringRef::size(), llvm::StringRef::substr(), and llvm::SmallVectorImpl< T >::swap().
Referenced by llvm::lto::getThinLTOOutputFile(), and llvm::sys::path::reverse_iterator::operator*().
root_directory()
StringRef llvm::sys::path::root_directory (StringRef path, Style style = Style::native)
Get root directory.
/goo/hello => /
c:/hello   => /
d/file.txt => <empty>
Parameters
path Input path.
Returns
The root directory of path if it has one, otherwise "".
Definition at line 389 of file Path.cpp.
References begin(), llvm::numbers::e, end(), and is_separator().
Referenced by has_root_directory(), llvm::sys::fs::make_absolute(), and llvm::sys::path::reverse_iterator::operator*().
root_name()
StringRef llvm::sys::path::root_name (StringRef path, Style style = Style::native)
Get root name.
//net/hello => //net
c:/hello    => c: (on Windows, on other platforms nothing)
/hello      => <empty>
Parameters
path Input path.
Returns
The root name of path if it has one, otherwise "".
Definition at line 372 of file Path.cpp.
References begin(), llvm::numbers::e, end(), and is_separator().
Referenced by llvm::computeArchiveRelativePath(), has_root_name(), llvm::sys::fs::make_absolute(), and llvm::sys::path::reverse_iterator::operator*().
root_path()
StringRef llvm::sys::path::root_path (StringRef path, Style style = Style::native)
Get root path.
Equivalent to root_name + root_directory.
Parameters
path Input path.
Returns
The root path of path if it has one, otherwise "".
Definition at line 346 of file Path.cpp.
References begin(), llvm::numbers::e, end(), is_separator(), and llvm::StringRef::substr().
Referenced by has_root_path(), llvm::sys::path::reverse_iterator::operator*(), relative_path(), and remove_dots().
stem()
StringRef llvm::sys::path::stem (StringRef path, Style style = Style::native)
Get stem.
If filename contains a dot but not solely one or two dots, result is the substring of filename ending at (but not including) the last dot. Otherwise it is filename.
/foo/bar.txt => bar
/foo/bar     => bar
/foo/.txt    => <empty>
/foo/.       => .
/foo/..      => ..
Parameters
path Input path.
Returns
The stem of path.
Definition at line 590 of file Path.cpp.
References filename(), llvm::StringRef::find_last_of(), llvm::StringRef::npos, llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by has_stem(), and llvm::sys::path::reverse_iterator::operator*().
system_temp_directory()
void llvm::sys::path::system_temp_directory (bool erasedOnReboot, SmallVectorImpl< char > & result)
Get the typical temporary directory for the system, e.g., "/var/tmp" or "C:/TEMP".
Parameters
erasedOnReboot Whether to favor a path that is erased on reboot rather than one that potentially persists longer. This parameter will be ignored if the user or system has set the typical environment variable (e.g., TEMP on Windows, TMPDIR on *nix) to specify a temporary directory.
result Holds the resulting path name.
Referenced by llvm::sys::fs::createUniquePath(), and llvm::sys::path::reverse_iterator::operator*().