LLVM: llvm::detail Namespace Reference
llvm::detail Namespace Reference
Implementation details of the pass manager interfaces.
Classes
class AlignAdapter
class AlignerImpl
class AlignerImpl< T >
struct AnalysisPassConcept
Abstract concept of an analysis pass.
struct AnalysisPassModel
Wrapper to model the analysis pass concept.
struct AnalysisResultConcept
Abstract concept of an analysis result.
struct AnalysisResultModel
Wrapper to model the analysis result concept.
struct AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, InvalidatorT, false >
Specialization of AnalysisResultModel which provides the default invalidate functionality.
struct AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, InvalidatorT, true >
Specialization of AnalysisResultModel which delegates invalidate handling to ResultT.
class concat_range
Helper to store a sequence of ranges being concatenated and access them.
struct ConstantLog2
A tiny meta function to compute the log2 of a compile time constant.
struct ConstantLog2< 1 >
union copy_construction_triviality_helper
Internal utility to detect trivial copy construction.
struct DenseMapPair
struct DenseSetEmpty
class DenseSetImpl
Base class for DenseSet and DenseSmallSet.
class DenseSetPair
class DoubleAPFloat
class enumerator
class enumerator_iter
class ErrorAdapter
struct ErrorHolder
class ErrorMatchesMono
struct ExpectedHolder
class format_adapter
struct fwd_or_bidi_tag
Helper which sets its type member to forward_iterator_tag if the category of IterT does not derive from bidirectional_iterator_tag, and to bidirectional_iterator_tag otherwise.
struct fwd_or_bidi_tag_impl
struct fwd_or_bidi_tag_impl< true >
class GenericLayer
class GenericLayerImpl
class GenericLayerImpl< orc::LegacyRTDyldObjectLinkingLayer >
class has_FormatProvider
class has_StreamOperator
struct HasPointerLikeTypeTraits
struct HasPointerLikeTypeTraits< T, decltype((sizeof(PointerLikeTypeTraits< T >)+sizeof(T)), void())>
class HelperFunctions
class IEEEFloat
struct is_cstring
struct IsPointerLike
struct IsPointerLike< T * >
struct LeadingZerosCounter
class missing_format_adapter
union move_construction_triviality_helper
Internal utility to detect trivial move construction.
class PadAdapter
struct PassConcept
Template for the abstract base class used to dispatch polymorphically over pass objects.
struct PassModel
A template wrapper used to implement the polymorphic API.
struct PointerSumTypeHelper
A helper template for implementing PointerSumType.
struct PopulationCounter
struct PopulationCounter< T, 8 >
class provider_format_adapter
class PtrUseVisitorBase
Implementation of non-dependent functionality for PtrUseVisitor.
struct range_item_has_provider
class RepeatAdapter
struct result_pair
class ResultHasInvalidateMethod
SFINAE metafunction for computing whether ResultT provides an invalidate member function.
class scope_exit
union SizerImpl
union SizerImpl< T >
class stream_operator_format_adapter
struct TrailingZerosCounter
union trivial_helper
struct unit
struct unit< std::micro >
struct unit< std::milli >
struct unit< std::nano >
struct unit< std::ratio< 1 > >
struct unit< std::ratio< 3600 > >
struct unit< std::ratio< 60 > >
struct use_char_formatter
struct use_double_formatter
struct use_integral_formatter
struct use_pointer_formatter
struct use_string_formatter
struct uses_format_member
struct uses_format_provider
struct uses_missing_provider
struct uses_stream_operator
class value_sequence_iterator
class ValueIsMatcher
class ValueMatchesMono
class ValueMatchesPoly
struct zip_common
struct zip_first
class zip_longest_iterator
class zip_longest_range
class zip_shortest
struct ZipLongestItemType
struct ZipLongestTupleType
class zippy
struct ZipTupleType
Typedefs
template<typename RangeT >
using IterOfRange = decltype(std::begin(std::declval< RangeT & >()))
template<typename ZipType , typename... Iters>
using zip_traits = iterator_facade_base< ZipType, typename std::common_type< std::bidirectional_iterator_tag, typename std::iterator_traits< Iters >::iterator_category... >::type, typename ZipTupleType< Iters... >::type, typename std::iterator_traits< typename std::tuple_element< 0, std::tuple< Iters... > >::type >::difference_type, typename ZipTupleType< Iters... >::type *, typename ZipTupleType< Iters... >::type >
template<typename IterT >
using IterValue = typename std::iterator_traits< IterT >::value_type
Functions
hash_code hash_value (const IEEEFloat &Arg)
int ilogb (const IEEEFloat &Arg)
IEEEFloat scalbn (IEEEFloat X, int Exp, IEEEFloat::roundingMode)
IEEEFloat frexp (const IEEEFloat &Val, int &Exp, IEEEFloat::roundingMode RM)
hash_code hash_value (const DoubleAPFloat &Arg)
template<typename ValueT , typename MapTy , typename ValueInfoT >
bool operator== (const DenseSetImpl< ValueT, MapTy, ValueInfoT > &LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > &RHS)
Equality comparison for DenseSet.
template<typename ValueT , typename MapTy , typename ValueInfoT >
bool operator!= (const DenseSetImpl< ValueT, MapTy, ValueInfoT > &LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > &RHS)
Inequality comparison for DenseSet.
template<typename Iter >
static Iter next_or_end (const Iter &I, const Iter &End)
template<typename Iter >
static auto deref_or_none (const Iter &I, const Iter &End) -> llvm::Optional< typename std::remove_const< typename std::remove_reference< decltype(*I)>::type >::type >
template<typename F , typename Tuple , std::size_t... I>
auto apply_tuple_impl (F &&f, Tuple &&t, std::index_sequence< I... >) -> decltype(std::forward< F >(f)(std::get< I >(std::forward< Tuple >(t))...))
template<typename N >
bool to_float (const Twine &T, N &Num, N(*StrTo)(const char *, char **))
template<typename IteratorT >
std::string join_impl (IteratorT Begin, IteratorT End, StringRef Separator, std::input_iterator_tag)
template<typename IteratorT >
std::string join_impl (IteratorT Begin, IteratorT End, StringRef Separator, std::forward_iterator_tag)
template<typename Sep >
void join_items_impl (std::string &Result, Sep Separator)
template<typename Sep , typename Arg >
void join_items_impl (std::string &Result, Sep Separator, const Arg &Item)
template<typename Sep , typename Arg1 , typename... Args>
void join_items_impl (std::string &Result, Sep Separator, const Arg1 &A1, Args &&... Items)
size_t join_one_item_size (char)
size_t join_one_item_size (const char *S)
template<typename T >
size_t join_one_item_size (const T &Str)
size_t join_items_size ()
template<typename A1 >
size_t join_items_size (const A1 &A)
template<typename A1 , typename... Args>
size_t join_items_size (const A1 &A, Args &&... Items)
template<typename PassT , typename IRUnitT , typename AnalysisManagerT , typename... ArgTs, size_t... Ns>
PassT::Result getAnalysisResultUnpackTuple (AnalysisManagerT &AM, IRUnitT &IR, std::tuple< ArgTs... > Args, std::index_sequence< Ns... >)
Actual unpacker of extra arguments in getAnalysisResult, passes only those tuple arguments that are mentioned in index_sequence.
template<typename PassT , typename IRUnitT , typename... AnalysisArgTs, typename... MainArgTs>
PassT::Result getAnalysisResult (AnalysisManager< IRUnitT, AnalysisArgTs... > &AM, IRUnitT &IR, std::tuple< MainArgTs... > Args)
Helper for partial unpacking of extra arguments in getAnalysisResult.
void printBumpPtrAllocatorStats (unsigned NumSlabs, size_t BytesAllocated, size_t TotalMemory)
template<typename T >
std::enable_if< uses_format_member< T >::value, T >::type build_format_adapter (T &&Item)
template<typename T >
std::enable_if< uses_format_provider< T >::value, provider_format_adapter< T > >::type build_format_adapter (T &&Item)
template<typename T >
std::enable_if< uses_stream_operator< T >::value, stream_operator_format_adapter< T > >::type build_format_adapter (T &&Item)
template<typename T >
std::enable_if< uses_missing_provider< T >::value, missing_format_adapter< T > >::type build_format_adapter (T &&Item)
ErrorHolder TakeError (Error Err)
template<typename T >
ExpectedHolder< T > TakeExpected (Expected< T > &Exp)
template<typename T >
ExpectedHolder< T > TakeExpected (Expected< T > &&Exp)
void PrintTo (const ErrorHolder &Err, std::ostream *Out)
template<typename T >
void PrintTo (const ExpectedHolder< T > &Item, std::ostream *Out)
template<typename LayerT >
std::unique_ptr< GenericLayerImpl< LayerT > > createGenericLayer (LayerT &Layer)
DoubleAPFloat scalbn (DoubleAPFloat Arg, int Exp, APFloat::roundingMode RM)
DoubleAPFloat frexp (const DoubleAPFloat &Arg, int &Exp, APFloat::roundingMode RM)
Detailed Description
Implementation details of the pass manager interfaces.
Implementation of format_provider<T> for duration types.
The options string of a duration type has the grammar:
duration_options ::= [unit][show_unit [number_options]] unit ::= h|m|s|ms|us|ns show_unit ::=+|-` number_options ::= options string for a integral or floating point type
Examples
| options | Input | Output |
| "" | 1s | 1 s | | "ms" | 1s | 1000 ms | | "ms-" | 1s | 1000 | | "ms-n" | 1s | 1,000 |
| "" | 1.0s | 1.00 s |
If the unit of the duration type is not one of the units specified above, it is still possible to format it, provided you explicitly request a display unit or you request that the unit is not displayed.
Typedef Documentation
IterOfRange
template<typename RangeT > using llvm::detail::IterOfRange = typedef decltype(std::begin(std::declval<RangeT &>()))
Definition at line 51 of file STLExtras.h.
IterValue
template<typename IterT > using llvm::detail::IterValue = typedef typename std::iterator_traits<IterT>::value_type
Definition at line 325 of file FormatProviders.h.
zip_traits
template<typename ZipType , typename... Iters> using llvm::detail::zip_traits = typedef iterator_facade_base< ZipType, typename std::common_type<std::bidirectional_iterator_tag, typename std::iterator_traits< Iters>::iterator_category...>::type, typename ZipTupleType<Iters...>::type, typename std::iterator_traits<typename std::tuple_element< 0, std::tuple<Iters...> >::type>::difference_type, typename ZipTupleType<Iters...>::type *, typename ZipTupleType<Iters...>::type>
Definition at line 549 of file STLExtras.h.
Function Documentation
apply_tuple_impl()
template<typename F , typename Tuple , std::size_t... I> auto llvm::detail::apply_tuple_impl (F && f, Tuple && t, std::index_sequence< I... >) -> decltype(std::forward<F>(f)(std::get<I>(std::forward<Tuple>(t))...))
Definition at line 1518 of file STLExtras.h.
Referenced by llvm::apply_tuple().
build_format_adapter() [1/4]
template<typename T > std::enable_if<uses_format_member<T>::value, T>::type llvm::detail::build_format_adapter (T && Item)
Definition at line 131 of file FormatVariadicDetails.h.
Referenced by llvm::detail::AlignAdapter< T >::format(), llvm::detail::PadAdapter< T >::format(), llvm::detail::RepeatAdapter< T >::format(), and llvm::formatv().
build_format_adapter() [2/4]
template<typename T > std::enable_if<uses_format_provider<T>::value, provider_format_adapter<T> >::type llvm::detail::build_format_adapter (T && Item)
Definition at line 138 of file FormatVariadicDetails.h.
build_format_adapter() [3/4]
template<typename T > std::enable_if<uses_stream_operator<T>::value, stream_operator_format_adapter<T> >::type llvm::detail::build_format_adapter (T && Item)
Definition at line 145 of file FormatVariadicDetails.h.
build_format_adapter() [4/4]
template<typename T > std::enable_if<uses_missing_provider<T>::value, missing_format_adapter<T> >::type llvm::detail::build_format_adapter (T && Item)
Definition at line 158 of file FormatVariadicDetails.h.
createGenericLayer()
template<typename LayerT > std::unique_ptr<GenericLayerImpl<LayerT> > llvm::detail::createGenericLayer (LayerT & Layer)
Definition at line 99 of file OrcCBindingsStack.h.
deref_or_none()
template<typename Iter > static auto llvm::detail::deref_or_none (const Iter & I, const Iter & End) -> llvm::Optional<typename std::remove_const< typename std::remove_reference<decltype(*I)>::type>::type> static
Definition at line 683 of file STLExtras.h.
frexp() [1/2]
IEEEFloat llvm::detail::frexp (const IEEEFloat & Val, int & Exp, IEEEFloat::roundingMode RM)
Definition at line 3905 of file APFloat.cpp.
References llvm::APFloatBase::IEK_Inf, llvm::APFloatBase::IEK_NaN, llvm::APFloatBase::IEK_Zero, llvm::detail::IEEEFloat::ilogb, llvm::detail::IEEEFloat::makeQuiet(), and llvm::detail::IEEEFloat::scalbn.
frexp() [2/2]
DoubleAPFloat llvm::detail::frexp (const DoubleAPFloat & Arg, int & Exp, APFloat::roundingMode RM)
Definition at line 4478 of file APFloat.cpp.
References llvm::lltok::APFloat, assert(), llvm::detail::DoubleAPFloat::DoubleAPFloat(), F(), llvm::APFloatBase::fcNormal, llvm::detail::DoubleAPFloat::frexp, llvm::detail::DoubleAPFloat::getCategory(), llvm::detail::IEEEFloat::getSemantics(), llvm_unreachable, and llvm::detail::DoubleAPFloat::scalbn.
getAnalysisResult()
template<typename PassT , typename IRUnitT , typename... AnalysisArgTs, typename... MainArgTs> PassT::Result llvm::detail::getAnalysisResult (AnalysisManager< IRUnitT, AnalysisArgTs... > & AM, IRUnitT & IR, std::tuple< MainArgTs... > Args)
Helper for partial unpacking of extra arguments in getAnalysisResult.
Arguments passed in tuple come from PassManager, so they might have extra arguments after those AnalysisManager's ExtraArgTs ones that we need to pass to getResult.
Definition at line 435 of file PassManager.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, getAnalysisResultUnpackTuple(), and IR.
getAnalysisResultUnpackTuple()
template<typename PassT , typename IRUnitT , typename AnalysisManagerT , typename... ArgTs, size_t... Ns> PassT::Result llvm::detail::getAnalysisResultUnpackTuple (AnalysisManagerT & AM, IRUnitT & IR, std::tuple< ArgTs... > Args, std::index_sequence< Ns... >)
Actual unpacker of extra arguments in getAnalysisResult, passes only those tuple arguments that are mentioned in index_sequence.
Definition at line 420 of file PassManager.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and IR.
Referenced by getAnalysisResult().
hash_value() [1/2]
hash_code llvm::detail::hash_value (const IEEEFloat & Arg)
Note that the use of hash codes for floating point values is in general frought with peril. Equality is hard to define for these values. For example, should negative and positive zero hash to different codes? Are they equal or not? This hash value implementation specifically emphasizes producing different codes for different inputs in order to be used in canonicalization and memoization. As such, equality is bitwiseIsEqual, and 0 != -0.
Definition at line 2850 of file APFloat.cpp.
References assert(), llvm::detail::IEEEFloat::convert(), llvm::APFloatBase::fcInfinity, llvm::APFloatBase::fcNaN, llvm::APFloatBase::fcZero, llvm::APInt::getRawData(), llvm::hash_combine(), llvm::hash_combine_range(), llvm::detail::IEEEFloat::isFiniteNonZero(), llvm::detail::IEEEFloat::isNaN(), llvm::fltSemantics::minExponent, llvm::APFloatBase::opInexact, llvm::APFloatBase::opOK, llvm::fltSemantics::precision, llvm::APFloatBase::rmNearestTiesToEven, and llvm::detail::IEEEFloat::subtract().
hash_value() [2/2]
hash_code llvm::detail::hash_value (const DoubleAPFloat & Arg)
Definition at line 4342 of file APFloat.cpp.
References llvm::hash_combine(), and llvm::detail::DoubleAPFloat::hash_value.
ilogb()
int llvm::detail::ilogb (const IEEEFloat & Arg)
Because the radix of APFloat is 2, this is equivalent to floor(log2(x)). For special APFloat values, this returns special error codes:
NaN -> IEK_NaN 0 -> IEK_Zero Inf -> IEK_Inf
Definition at line 3866 of file APFloat.cpp.
References llvm::detail::IEEEFloat::getSemantics(), llvm::APFloatBase::IEK_Inf, llvm::APFloatBase::IEK_NaN, llvm::APFloatBase::IEK_Zero, llvm::detail::IEEEFloat::isDenormal(), llvm::detail::IEEEFloat::isInfinity(), llvm::detail::IEEEFloat::isNaN(), llvm::detail::IEEEFloat::isZero(), llvm::lfExactlyZero, llvm::fltSemantics::precision, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by llvm::detail::DoubleAPFloat::getSecond(), llvm::isKnownNeverInfinity(), and llvm::detail::IEEEFloat::isNegZero().
join_impl() [1/2]
template<typename IteratorT > std::string llvm::detail::join_impl (IteratorT Begin, IteratorT End, StringRef Separator, std::input_iterator_tag) inline
Definition at line 298 of file StringExtras.h.
join_impl() [2/2]
template<typename IteratorT > std::string llvm::detail::join_impl (IteratorT Begin, IteratorT End, StringRef Separator, std::forward_iterator_tag) inline
Definition at line 313 of file StringExtras.h.
join_items_impl() [1/3]
template<typename Sep > void llvm::detail::join_items_impl (std::string & Result, Sep Separator) inline
Definition at line 332 of file StringExtras.h.
Referenced by llvm::join_items(), and join_items_impl().
join_items_impl() [2/3]
template<typename Sep , typename Arg > void llvm::detail::join_items_impl (std::string & Result, Sep Separator, const Arg & Item) inline
Definition at line 335 of file StringExtras.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
join_items_impl() [3/3]
template<typename Sep , typename Arg1 , typename... Args> void llvm::detail::join_items_impl (std::string & Result, Sep Separator, const Arg1 & A1, Args &&... Items) inline
Definition at line 341 of file StringExtras.h.
References join_items_impl().
join_items_size() [1/3]
size_t llvm::detail::join_items_size () inline
Definition at line 355 of file StringExtras.h.
Referenced by llvm::join_items(), and join_items_size().
join_items_size() [2/3]
template<typename A1 > size_t llvm::detail::join_items_size (const A1 & A) inline
Definition at line 357 of file StringExtras.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and join_one_item_size().
join_items_size() [3/3]
template<typename A1 , typename... Args> size_t llvm::detail::join_items_size (const A1 & A, Args &&... Items) inline
Definition at line 361 of file StringExtras.h.
References join_items_size(), and join_one_item_size().
join_one_item_size() [1/3]
size_t llvm::detail::join_one_item_size (char) inline
Definition at line 348 of file StringExtras.h.
Referenced by llvm::join_items(), and join_items_size().
join_one_item_size() [2/3]
size_t llvm::detail::join_one_item_size (const char * S) inline
Definition at line 349 of file StringExtras.h.
join_one_item_size() [3/3]
template<typename T > size_t llvm::detail::join_one_item_size (const T & Str) inline
Definition at line 351 of file StringExtras.h.
next_or_end()
template<typename Iter > static Iter llvm::detail::next_or_end (const Iter & I, const Iter & End) static
Definition at line 676 of file STLExtras.h.
operator!=()
template<typename ValueT , typename MapTy , typename ValueInfoT > bool llvm::detail::operator!= (const DenseSetImpl< ValueT, MapTy, ValueInfoT > & LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > & RHS)
Inequality comparison for DenseSet.
Equivalent to !(LHS == RHS). See operator== for performance notes.
Definition at line 240 of file DenseSet.h.
operator==()
template<typename ValueT , typename MapTy , typename ValueInfoT > bool llvm::detail::operator== (const DenseSetImpl< ValueT, MapTy, ValueInfoT > & LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > & RHS)
Equality comparison for DenseSet.
Iterates over elements of LHS confirming that each element is also a member of RHS, and that RHS contains no additional values. Equivalent to N calls to RHS.count. Amortized complexity is linear, worst case is O(N^2) (if every hash collides).
Definition at line 224 of file DenseSet.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), E, and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::size().
printBumpPtrAllocatorStats()
void llvm::detail::printBumpPtrAllocatorStats (unsigned NumSlabs, size_t BytesAllocated, size_t TotalMemory)
Definition at line 20 of file Allocator.cpp.
References llvm::errs().
Referenced by llvm::MallocAllocator::PrintStats(), and llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::PrintStats().
PrintTo() [1/2]
void llvm::detail::PrintTo (const ErrorHolder & Err, std::ostream * Out) inline
Definition at line 36 of file SupportHelpers.h.
Referenced by PrintTo().
PrintTo() [2/2]
template<typename T > void llvm::detail::PrintTo (const ExpectedHolder< T > & Item, std::ostream * Out)
Definition at line 51 of file SupportHelpers.h.
References llvm::detail::ExpectedHolder< T >::Exp, PrintTo(), and llvm::detail::ErrorHolder::Success().
scalbn() [1/2]
IEEEFloat llvm::detail::scalbn (IEEEFloat X, int Exp, IEEEFloat::roundingMode RoundingMode)
Definition at line 3884 of file APFloat.cpp.
References llvm::detail::IEEEFloat::getSemantics(), llvm::detail::IEEEFloat::isNaN(), llvm::lfExactlyZero, llvm::detail::IEEEFloat::makeQuiet(), llvm::max(), llvm::fltSemantics::maxExponent, llvm::fltSemantics::minExponent, llvm::fltSemantics::precision, and X.
scalbn() [2/2]
DoubleAPFloat llvm::detail::scalbn (DoubleAPFloat Arg, int Exp, APFloat::roundingMode RM)
Definition at line 4472 of file APFloat.cpp.
References assert(), llvm::detail::DoubleAPFloat::DoubleAPFloat(), and llvm::detail::DoubleAPFloat::scalbn.
TakeError()
llvm::detail::ErrorHolder llvm::detail::TakeError (llvm::Error Err)
Definition at line 15 of file Error.cpp.
Referenced by TakeExpected().
TakeExpected() [1/2]
template<typename T > ExpectedHolder<T> llvm::detail::TakeExpected (Expected< T > & Exp)
Definition at line 23 of file Error.h.
References TakeError(), and llvm::Expected< T >::takeError().
Referenced by TakeExpected().
TakeExpected() [2/2]
template<typename T > ExpectedHolder<T> llvm::detail::TakeExpected (Expected< T > && Exp)
Definition at line 27 of file Error.h.
References TakeExpected().
to_float()
template<typename N > bool llvm::detail::to_float (const Twine & T, N & Num, N(*)(const char *, char **) StrTo) inline
Definition at line 199 of file StringExtras.h.
References llvm::Twine::toNullTerminatedStringRef().
Referenced by llvm::to_float().