LLVM: llvm::RTLIB Namespace Reference
llvm::RTLIB Namespace Reference
Enumerations
enum Libcall
RTLIB::Libcall enum - This enum defines all of the runtime library calls the backend can emit.
Functions
Libcall getFPEXT (EVT OpVT, EVT RetVT)
getFPEXT - Return the FPEXT_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Libcall getFPROUND (EVT OpVT, EVT RetVT)
getFPROUND - Return the FPROUND_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Libcall getFPTOSINT (EVT OpVT, EVT RetVT)
getFPTOSINT - Return the FPTOSINT_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Libcall getFPTOUINT (EVT OpVT, EVT RetVT)
getFPTOUINT - Return the FPTOUINT_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Libcall getSINTTOFP (EVT OpVT, EVT RetVT)
getSINTTOFP - Return the SINTTOFP_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Libcall getUINTTOFP (EVT OpVT, EVT RetVT)
getUINTTOFP - Return the UINTTOFP_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Libcall getSYNC (unsigned Opc, MVT VT)
Return the SYNC_FETCH_AND_* value for the given opcode and type, or UNKNOWN_LIBCALL if there is none.
Libcall getMEMCPY_ELEMENT_UNORDERED_ATOMIC (uint64_t ElementSize)
getMEMCPY_ELEMENT_UNORDERED_ATOMIC - Return MEMCPY_ELEMENT_UNORDERED_ATOMIC_* value for the given element size or UNKNOW_LIBCALL if there is none.
Libcall getMEMMOVE_ELEMENT_UNORDERED_ATOMIC (uint64_t ElementSize)
getMEMMOVE_ELEMENT_UNORDERED_ATOMIC - Return MEMMOVE_ELEMENT_UNORDERED_ATOMIC_* value for the given element size or UNKNOW_LIBCALL if there is none.
Libcall getMEMSET_ELEMENT_UNORDERED_ATOMIC (uint64_t ElementSize)
getMEMSET_ELEMENT_UNORDERED_ATOMIC - Return MEMSET_ELEMENT_UNORDERED_ATOMIC_* value for the given element size or UNKNOW_LIBCALL if there is none.
Enumeration Type Documentation
Libcall
enum llvm::RTLIB::Libcall
RTLIB::Libcall enum - This enum defines all of the runtime library calls the backend can emit.
The various long double types cannot be merged, because 80-bit library functions use "xf" and 128-bit use "tf".
When adding PPCF128 functions here, note that their names generally need to be overridden for Darwin with the xxx$LDBL128 form. See PPCISelLowering.cpp.
Definition at line 29 of file RuntimeLibcalls.h.
Function Documentation
getFPEXT()
RTLIB::Libcall llvm::RTLIB::getFPEXT (EVT OpVT, EVT RetVT)
getFPEXT - Return the FPEXT_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Definition at line 220 of file TargetLoweringBase.cpp.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, and llvm::MVT::ppcf128.
Referenced by getConvRTLibDesc(), GetFPLibCall(), LowerPREFETCH(), and LowerTruncateVecI1().
getFPROUND()
RTLIB::Libcall llvm::RTLIB::getFPROUND (EVT OpVT, EVT RetVT)
getFPROUND - Return the FPROUND_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Definition at line 246 of file TargetLoweringBase.cpp.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, and llvm::MVT::ppcf128.
Referenced by getConvRTLibDesc(), GetFPLibCall(), LowerPREFETCH(), and LowerTruncateVecI1().
getFPTOSINT()
RTLIB::Libcall llvm::RTLIB::getFPTOSINT (EVT OpVT, EVT RetVT)
getFPTOSINT - Return the FPTOSINT_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Definition at line 284 of file TargetLoweringBase.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, and llvm::MVT::ppcf128.
Referenced by getConvRTLibDesc(), GetFPLibCall(), LowerPREFETCH(), LowerTruncateVecI1(), and LowerVectorFP_TO_INT().
getFPTOUINT()
RTLIB::Libcall llvm::RTLIB::getFPTOUINT (EVT OpVT, EVT RetVT)
getFPTOUINT - Return the FPTOUINT_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Definition at line 326 of file TargetLoweringBase.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, and llvm::MVT::ppcf128.
Referenced by getConvRTLibDesc(), GetFPLibCall(), LowerPREFETCH(), LowerTruncateVecI1(), and LowerVectorFP_TO_INT().
getMEMCPY_ELEMENT_UNORDERED_ATOMIC()
RTLIB::Libcall llvm::RTLIB::getMEMCPY_ELEMENT_UNORDERED_ATOMIC (uint64_t ElementSize)
getMEMCPY_ELEMENT_UNORDERED_ATOMIC - Return MEMCPY_ELEMENT_UNORDERED_ATOMIC_* value for the given element size or UNKNOW_LIBCALL if there is none.
Definition at line 484 of file TargetLoweringBase.cpp.
getMEMMOVE_ELEMENT_UNORDERED_ATOMIC()
RTLIB::Libcall llvm::RTLIB::getMEMMOVE_ELEMENT_UNORDERED_ATOMIC (uint64_t ElementSize)
getMEMMOVE_ELEMENT_UNORDERED_ATOMIC - Return MEMMOVE_ELEMENT_UNORDERED_ATOMIC_* value for the given element size or UNKNOW_LIBCALL if there is none.
Definition at line 501 of file TargetLoweringBase.cpp.
getMEMSET_ELEMENT_UNORDERED_ATOMIC()
RTLIB::Libcall llvm::RTLIB::getMEMSET_ELEMENT_UNORDERED_ATOMIC (uint64_t ElementSize)
getMEMSET_ELEMENT_UNORDERED_ATOMIC - Return MEMSET_ELEMENT_UNORDERED_ATOMIC_* value for the given element size or UNKNOW_LIBCALL if there is none.
Definition at line 518 of file TargetLoweringBase.cpp.
getSINTTOFP()
RTLIB::Libcall llvm::RTLIB::getSINTTOFP (EVT OpVT, EVT RetVT)
getSINTTOFP - Return the SINTTOFP_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Definition at line 368 of file TargetLoweringBase.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, and llvm::MVT::ppcf128.
Referenced by getConvRTLibDesc(), GetFPLibCall(), lowerINT_TO_FP_vXi64(), and LowerVectorINT_TO_FP().
getSYNC()
RTLIB::Libcall llvm::RTLIB::getSYNC (unsigned Opc, MVT VT)
Return the SYNC_FETCH_AND_* value for the given opcode and type, or UNKNOWN_LIBCALL if there is none.
Definition at line 446 of file TargetLoweringBase.cpp.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_SWAP, and OP_TO_LIBCALL.
getUINTTOFP()
RTLIB::Libcall llvm::RTLIB::getUINTTOFP (EVT OpVT, EVT RetVT)
getUINTTOFP - Return the UINTTOFP_*_* value for the given types, or UNKNOWN_LIBCALL if there is none.
Definition at line 408 of file TargetLoweringBase.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, and llvm::MVT::ppcf128.
Referenced by getConvRTLibDesc(), GetFPLibCall(), lowerUINT_TO_FP_vec(), and LowerVectorINT_TO_FP().