LLVM: llvm::sys::detail Namespace Reference
llvm::sys::detail Namespace Reference
Functions
StringRef getHostCPUNameForPowerPC (StringRef ProcCpuinfoContent)
Helper functions to extract HostCPUName from /proc/cpuinfo on linux.
StringRef getHostCPUNameForARM (StringRef ProcCpuinfoContent)
StringRef getHostCPUNameForS390x (StringRef ProcCpuinfoContent)
StringRef getHostCPUNameForBPF ()
Function Documentation
getHostCPUNameForARM()
StringRef llvm::sys::detail::getHostCPUNameForARM (StringRef ProcCpuinfoContent)
Definition at line 149 of file Host.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), E, llvm::StringRef::endswith(), I, LLVM_FALLTHROUGH, llvm::SmallVectorBase::size(), llvm::StringRef::split(), and startswith().
Referenced by getHostCPUNameForBPF().
getHostCPUNameForBPF()
StringRef llvm::sys::detail::getHostCPUNameForBPF ()
Definition at line 338 of file Host.cpp.
References llvm::support::aligned, assert(), llvm::MachO::CPU_SUBTYPE_ARM_V7S, llvm::MachO::CPU_SUBTYPE_POWERPC_601, llvm::MachO::CPU_SUBTYPE_POWERPC_602, llvm::MachO::CPU_SUBTYPE_POWERPC_603, llvm::MachO::CPU_SUBTYPE_POWERPC_603e, llvm::MachO::CPU_SUBTYPE_POWERPC_603ev, llvm::MachO::CPU_SUBTYPE_POWERPC_604, llvm::MachO::CPU_SUBTYPE_POWERPC_604e, llvm::MachO::CPU_SUBTYPE_POWERPC_620, llvm::MachO::CPU_SUBTYPE_POWERPC_7400, llvm::MachO::CPU_SUBTYPE_POWERPC_7450, llvm::MachO::CPU_SUBTYPE_POWERPC_750, llvm::MachO::CPU_SUBTYPE_POWERPC_970, llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_POWERPC, llvm::N86::EAX, llvm::N86::EBX, llvm::N86::ECX, llvm::N86::EDX, F(), llvm::AMDGPU::FEATURE_FMA, llvm::sys::getHostCPUName(), getHostCPUNameForARM(), getHostCPUNameForPowerPC(), getHostCPUNameForS390x(), getProcCpuinfoContent(), llvm_unreachable, and P.
Referenced by llvm::BPFSubtarget::initializeSubtargetDependencies().
getHostCPUNameForPowerPC()
StringRef llvm::sys::detail::getHostCPUNameForPowerPC (StringRef ProcCpuinfoContent)
Helper functions to extract HostCPUName from /proc/cpuinfo on linux.
Definition at line 67 of file Host.cpp.
References llvm::StringRef::begin(), llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and llvm::StringRef::end().
Referenced by getHostCPUNameForBPF().
getHostCPUNameForS390x()
StringRef llvm::sys::detail::getHostCPUNameForS390x (StringRef ProcCpuinfoContent)
Definition at line 283 of file Host.cpp.
References E, I, llvm::StringRef::npos, llvm::SmallVectorBase::size(), llvm::StringRef::split(), and startswith().
Referenced by getHostCPUNameForBPF().