LLVM: llvm::Hexagon_MC Namespace Reference
llvm::Hexagon_MC Namespace Reference
Functions
StringRef selectHexagonCPU (StringRef CPU)
FeatureBitset completeHVXFeatures (const FeatureBitset &FB)
MCSubtargetInfo * createHexagonMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
Create a Hexagon MCSubtargetInfo instance.
unsigned GetELFFlags (const MCSubtargetInfo &STI)
Function Documentation
completeHVXFeatures()
FeatureBitset llvm::Hexagon_MC::completeHVXFeatures (const FeatureBitset & FB)
Definition at line 335 of file HexagonMCTargetDesc.cpp.
References F(), LLVM_FALLTHROUGH, llvm::FeatureBitset::set(), and llvm::FeatureBitset::test().
Referenced by createHexagonMCSubtargetInfo(), and llvm::HexagonSubtarget::initializeSubtargetDependencies().
createHexagonMCSubtargetInfo()
MCSubtargetInfo * llvm::Hexagon_MC::createHexagonMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS)
Create a Hexagon MCSubtargetInfo instance.
This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 385 of file HexagonMCTargetDesc.cpp.
References completeHVXFeatures(), llvm::errs(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::HexagonDisableDuplex, isCPUValid(), llvm::FeatureBitset::reset(), llvm::MCSubtargetInfo::setFeatureBits(), llvm::StringRef::str(), and X.
Referenced by LLVMInitializeHexagonTargetMC().
GetELFFlags()
unsigned llvm::Hexagon_MC::GetELFFlags (const MCSubtargetInfo & STI)
Definition at line 408 of file HexagonMCTargetDesc.cpp.
References assert(), llvm::ELF::EF_HEXAGON_MACH_V5, llvm::ELF::EF_HEXAGON_MACH_V55, llvm::ELF::EF_HEXAGON_MACH_V60, llvm::ELF::EF_HEXAGON_MACH_V62, llvm::ELF::EF_HEXAGON_MACH_V65, llvm::ELF::EF_HEXAGON_MACH_V66, F(), llvm::MCSubtargetInfo::getCPU(), llvm::HexagonMCInstrInfo::getExtendableOperand(), Info, llvm::MCInstrAnalysis::isConditionalBranch(), llvm::HexagonMCInstrInfo::isExtendable(), llvm::MCInstrAnalysis::isUnconditionalBranch(), isUnconditionalBranch(), and Size.
Referenced by llvm::HexagonGetLastSlot().
selectHexagonCPU()
StringRef llvm::Hexagon_MC::selectHexagonCPU (StringRef CPU)
Definition at line 113 of file HexagonMCTargetDesc.cpp.
References llvm::StringRef::empty(), HexagonGetArchVariant(), and llvm::report_fatal_error().
Referenced by llvm::createHexagonAsmBackend(), and isCPUValid().