LLVM: llvm::zlib Namespace Reference
llvm::zlib Namespace Reference
Functions
bool isAvailable ()
Error compress (StringRef InputBuffer, SmallVectorImpl< char > &CompressedBuffer, int Level=DefaultCompression)
Error uncompress (StringRef InputBuffer, char *UncompressedBuffer, size_t &UncompressedSize)
Error uncompress (StringRef InputBuffer, SmallVectorImpl< char > &UncompressedBuffer, size_t UncompressedSize)
uint32_t crc32 (StringRef Buffer)
Variables
static constexpr int NoCompression = 0
static constexpr int BestSpeedCompression = 1
static constexpr int DefaultCompression = 6
static constexpr int BestSizeCompression = 9
Function Documentation
compress()
Error llvm::zlib::compress (StringRef InputBuffer, SmallVectorImpl< char > & CompressedBuffer, int Level = DefaultCompression)
Definition at line 49 of file Compression.cpp.
References __msan_unpoison, convertZlibCodeToString(), llvm::createError(), llvm::StringRef::data(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorBase::set_size(), llvm::StringRef::size(), and llvm::Error::success().
Referenced by llvm::collectPGOFuncNameStrings(), crc32(), isIFunc(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::markSectionStart().
crc32()
uint32_t llvm::zlib::crc32 (StringRef Buffer)
Definition at line 84 of file Compression.cpp.
References compress(), llvm::StringRef::data(), isAvailable(), llvm_unreachable, llvm::StringRef::size(), and uncompress().
isAvailable()
bool llvm::zlib::isAvailable ()
Definition at line 47 of file Compression.cpp.
Referenced by llvm::collectPGOFuncNameStrings(), crc32(), llvm::object::Decompressor::create(), INITIALIZE_PASS(), llvm::mca::LSUnit::LSUnit(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::markSectionStart(), and llvm::readPGOFuncNameStrings().
uncompress() [1/2]
Error llvm::zlib::uncompress (StringRef InputBuffer, char * UncompressedBuffer, size_t & UncompressedSize)
Definition at line 63 of file Compression.cpp.
References __msan_unpoison, convertZlibCodeToString(), llvm::createError(), llvm::StringRef::data(), llvm::StringRef::size(), and llvm::Error::success().
Referenced by crc32(), llvm::object::Decompressor::decompress(), llvm::readPGOFuncNameStrings(), and uncompress().
uncompress() [2/2]
Error llvm::zlib::uncompress (StringRef InputBuffer, SmallVectorImpl< char > & UncompressedBuffer, size_t UncompressedSize)
Definition at line 74 of file Compression.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::data(), E, llvm::SmallVectorImpl< T >::resize(), and uncompress().
Variable Documentation
BestSizeCompression
constexpr int llvm::zlib::BestSizeCompression = 9 static
Definition at line 28 of file Compression.h.
Referenced by llvm::collectPGOFuncNameStrings(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::markSectionStart().
BestSpeedCompression
constexpr int llvm::zlib::BestSpeedCompression = 1 static
Definition at line 26 of file Compression.h.
DefaultCompression
constexpr int llvm::zlib::DefaultCompression = 6 static
Definition at line 27 of file Compression.h.
NoCompression
constexpr int llvm::zlib::NoCompression = 0 static
Definition at line 25 of file Compression.h.