LLVM: llvm::ARMSysReg Namespace Reference
llvm::ARMSysReg Namespace Reference
Classes
struct MClassSysReg
Functions
const MClassSysReg * lookupMClassSysRegBy12bitSYSmValue (unsigned SYSm)
const MClassSysReg * lookupMClassSysRegAPSRNonDeprecated (unsigned SYSm)
const MClassSysReg * lookupMClassSysRegBy8bitSYSmValue (unsigned SYSm)
Function Documentation
lookupMClassSysRegAPSRNonDeprecated()
const MClassSysReg * llvm::ARMSysReg::lookupMClassSysRegAPSRNonDeprecated (unsigned SYSm)
Definition at line 28 of file ARMBaseInfo.cpp.
Referenced by llvm::ARMInstPrinter::printMSRMaskOperand().
lookupMClassSysRegBy12bitSYSmValue()
const MClassSysReg * llvm::ARMSysReg::lookupMClassSysRegBy12bitSYSmValue (unsigned SYSm)
Definition at line 22 of file ARMBaseInfo.cpp.
Referenced by llvm::ARMInstPrinter::printMSRMaskOperand().
lookupMClassSysRegBy8bitSYSmValue()
const MClassSysReg * llvm::ARMSysReg::lookupMClassSysRegBy8bitSYSmValue (unsigned SYSm)
Definition at line 33 of file ARMBaseInfo.cpp.
Referenced by llvm::ARMInstPrinter::printMSRMaskOperand().