LLVM: llvm::irsymtab Namespace Reference
llvm::irsymtab Namespace Reference
Namespaces
storage
Classes
struct FileContents
The contents of the irsymtab in a bitcode file.
class Reader
This class can be used to read a Symtab and Strtab produced by irsymtab::build.
struct Symbol
This represents a symbol that has been read from a storage::Symbol and possibly a storage::Uncommon.
Functions
Error build (ArrayRef< Module *> Mods, SmallVector< char, 0 > &Symtab, StringTableBuilder &StrtabBuilder, BumpPtrAllocator &Alloc)
Fills in Symtab and StrtabBuilder with a valid symbol and string table for Mods.
Expected< FileContents > readBitcode (const BitcodeFileContents &BFC)
Reads the contents of a bitcode file, creating its irsymtab if necessary.
Function Documentation
build()
Error llvm::irsymtab::build (ArrayRef< Module *> Mods, SmallVector< char, 0 > & Symtab, StringTableBuilder & StrtabBuilder, BumpPtrAllocator & Alloc)
Fills in Symtab and StrtabBuilder with a valid symbol and string table for Mods.
Definition at line 338 of file IRSymtab.cpp.
Referenced by llvm::lowertypetests::BitSetBuilder::addOffset(), and llvm::VersionTuple::tryParse().
readBitcode()
Expected< FileContents > llvm::irsymtab::readBitcode (const BitcodeFileContents & BFC)
Reads the contents of a bitcode file, creating its irsymtab if necessary.
Definition at line 377 of file IRSymtab.cpp.
References llvm::StringRef::data(), llvm::StringRef::empty(), R600_InstFlag::FC, llvm::irsymtab::Reader::getNumModules(), llvm::inconvertibleErrorCode(), llvm::irsymtab::storage::Header::kCurrentVersion, llvm::BitcodeFileContents::Mods, llvm::StringRef::size(), llvm::BitcodeFileContents::StrtabForSymtab, llvm::BitcodeFileContents::Symtab, llvm::irsymtab::FileContents::TheReader, upgrade(), and llvm::IndexedInstrProf::Version.
Referenced by llvm::object::readIRSymtab().