LLVM: llvm::ARM::WinEH Namespace Reference
llvm::ARM::WinEH Namespace Reference
Classes
struct EpilogueScope
ExceptionDataRecord - An entry in the table of exception data (.xdata)
struct ExceptionDataRecord
class RuntimeFunction
RuntimeFunction - An entry in the table of procedure data (.pdata)
Enumerations
enum RuntimeFunctionFlag { RuntimeFunctionFlag::RFF_Unpacked, RuntimeFunctionFlag::RFF_Packed, RuntimeFunctionFlag::RFF_PackedFragment, RuntimeFunctionFlag::RFF_Reserved }
enum ReturnType { ReturnType::RT_POP, ReturnType::RT_B, ReturnType::RT_BW, ReturnType::RT_NoEpilogue }
Functions
bool PrologueFolding (const RuntimeFunction &RF)
PrologueFolding - pseudo-flag derived from Stack Adjust indicating that the prologue has stack adjustment combined into the push.
bool EpilogueFolding (const RuntimeFunction &RF)
Epilogue - pseudo-flag derived from Stack Adjust indicating that the epilogue has stack adjustment combined into the pop.
uint16_t StackAdjustment (const RuntimeFunction &RF)
StackAdjustment - calculated stack adjustment in words.
std::pair< uint16_t, uint32_t > SavedRegisterMask (const RuntimeFunction &RF)
SavedRegisterMask - Utility function to calculate the set of saved general purpose (r0-r15) and VFP (d0-d31) registers.
size_t HeaderWords (const ExceptionDataRecord &XR)
Enumeration Type Documentation
ReturnType
enum llvm::ARM::WinEH::ReturnType strong
Enumerator
RT_POP
RT_B
return via pop {pc} (L flag must be set)
RT_BW
16-bit branch
RT_NoEpilogue
32-bit branch
Definition at line 25 of file ARMWinEH.h.
RuntimeFunctionFlag
enum llvm::ARM::WinEH::RuntimeFunctionFlag strong
Enumerator
RFF_Unpacked
RFF_Packed
unpacked entry
RFF_PackedFragment
packed entry
RFF_Reserved
packed entry representing a fragment
Definition at line 18 of file ARMWinEH.h.
Function Documentation
EpilogueFolding()
bool llvm::ARM::WinEH::EpilogueFolding (const RuntimeFunction & RF) inline
Epilogue - pseudo-flag derived from Stack Adjust indicating that the epilogue has stack adjustment combined into the pop.
Definition at line 190 of file ARMWinEH.h.
References llvm::ARM::WinEH::RuntimeFunction::StackAdjust().
HeaderWords()
size_t llvm::ARM::WinEH::HeaderWords (const ExceptionDataRecord & XR) inline
Definition at line 428 of file ARMWinEH.h.
References llvm::ARM::WinEH::ExceptionDataRecord::Data, and llvm::ARM::WinEH::ExceptionDataRecord::isAArch64.
Referenced by llvm::ARM::WinEH::ExceptionDataRecord::CodeWords(), llvm::ARM::WinEH::ExceptionDataRecord::EpilogueCount(), llvm::ARM::WinEH::ExceptionDataRecord::EpilogueScopes(), llvm::ARM::WinEH::EpilogueScope::EpilogueStartIndexAArch64(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerParameter(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerRVA(), and llvm::ARM::WinEH::ExceptionDataRecord::UnwindByteCode().
PrologueFolding()
bool llvm::ARM::WinEH::PrologueFolding (const RuntimeFunction & RF) inline
PrologueFolding - pseudo-flag derived from Stack Adjust indicating that the prologue has stack adjustment combined into the push.
Definition at line 185 of file ARMWinEH.h.
References llvm::ARM::WinEH::RuntimeFunction::StackAdjust().
Referenced by SavedRegisterMask().
SavedRegisterMask()
std::pair< uint16_t, uint32_t > llvm::ARM::WinEH::SavedRegisterMask (const RuntimeFunction & RF)
SavedRegisterMask - Utility function to calculate the set of saved general purpose (r0-r15) and VFP (d0-d31) registers.
Definition at line 15 of file ARMWinEH.cpp.
References llvm::ARM::WinEH::RuntimeFunction::C(), llvm::ARM::WinEH::RuntimeFunction::L(), PrologueFolding(), llvm::ARM::WinEH::RuntimeFunction::R(), llvm::ARM::WinEH::RuntimeFunction::Reg(), and llvm::ARM::WinEH::RuntimeFunction::StackAdjust().
Referenced by StackAdjustment().
StackAdjustment()
uint16_t llvm::ARM::WinEH::StackAdjustment (const RuntimeFunction & RF) inline
StackAdjustment - calculated stack adjustment in words.
The stack adjustment should be determined via this function to account for the special handling the special encoding when the value is >= 0x3f4.
Definition at line 196 of file ARMWinEH.h.
References SavedRegisterMask(), and llvm::ARM::WinEH::RuntimeFunction::StackAdjust().
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), and ExpandMOVImmSExti8().