LLVM: llvm::SwitchCG Namespace Reference
llvm::SwitchCG Namespace Reference
Classes
struct BitTestBlock
struct BitTestCase
struct CaseBits
struct CaseBlock
This structure is used to communicate between SelectionDAGBuilder and SDISel for the code generation of additional basic blocks needed by multi-case switch statements.
struct CaseCluster
A cluster of case labels.
struct JumpTable
struct JumpTableHeader
class SwitchLowering
struct SwitchWorkListItem
Typedefs
using CaseClusterVector = std::vector< CaseCluster >
using CaseClusterIt = CaseClusterVector::iterator
using CaseBitsVector = std::vector< CaseBits >
using JumpTableBlock = std::pair< JumpTableHeader, JumpTable >
using BitTestInfo = SmallVector< BitTestCase, 3 >
using SwitchWorkList = SmallVector< SwitchWorkListItem, 4 >
Enumerations
enum CaseClusterKind { CC_Range, CC_JumpTable, CC_BitTests }
Functions
void sortAndRangeify (CaseClusterVector &Clusters)
Sort Clusters and merge adjacent cases.
uint64_t getJumpTableRange (const CaseClusterVector &Clusters, unsigned First, unsigned Last)
Return the range of values within a range.
uint64_t getJumpTableNumCases (const SmallVectorImpl< unsigned > &TotalCases, unsigned First, unsigned Last)
Return the number of cases within a range.
Typedef Documentation
BitTestInfo
using llvm::SwitchCG::BitTestInfo = typedef SmallVector<BitTestCase, 3>
Definition at line 201 of file SwitchLoweringUtils.h.
CaseBitsVector
using llvm::SwitchCG::CaseBitsVector = typedef std::vector<CaseBits>
Definition at line 99 of file SwitchLoweringUtils.h.
CaseClusterIt
using llvm::SwitchCG::CaseClusterIt = typedef CaseClusterVector::iterator
Definition at line 82 of file SwitchLoweringUtils.h.
CaseClusterVector
using llvm::SwitchCG::CaseClusterVector = typedef std::vector<CaseCluster>
Definition at line 81 of file SwitchLoweringUtils.h.
JumpTableBlock
using llvm::SwitchCG::JumpTableBlock = typedef std::pair<JumpTableHeader, JumpTable>
Definition at line 188 of file SwitchLoweringUtils.h.
SwitchWorkList
using llvm::SwitchCG::SwitchWorkList = typedef SmallVector<SwitchWorkListItem, 4>
Definition at line 242 of file SwitchLoweringUtils.h.
Enumeration Type Documentation
CaseClusterKind
enum llvm::SwitchCG::CaseClusterKind
Enumerator
CC_Range
A cluster of adjacent case labels with the same destination, or just one case.
CC_JumpTable
A cluster of cases suitable for jump table lowering.
CC_BitTests
A cluster of cases suitable for bit test lowering.
Definition at line 26 of file SwitchLoweringUtils.h.
Function Documentation
getJumpTableNumCases()
uint64_t llvm::SwitchCG::getJumpTableNumCases (const SmallVectorImpl< unsigned > & TotalCases, unsigned First, unsigned Last)
Return the number of cases within a range.
Definition at line 34 of file SwitchLoweringUtils.cpp.
References assert().
Referenced by llvm::SwitchCG::BitTestBlock::BitTestBlock(), and llvm::SwitchCG::SwitchLowering::findJumpTables().
getJumpTableRange()
uint64_t llvm::SwitchCG::getJumpTableRange (const CaseClusterVector & Clusters, unsigned First, unsigned Last)
Return the range of values within a range.
Definition at line 20 of file SwitchLoweringUtils.cpp.
References assert(), llvm::APInt::getBitWidth(), and UINT64_MAX.
Referenced by llvm::SwitchCG::BitTestBlock::BitTestBlock(), and llvm::SwitchCG::SwitchLowering::findJumpTables().
sortAndRangeify()
void llvm::SwitchCG::sortAndRangeify (CaseClusterVector & Clusters)
Sort Clusters and merge adjacent cases.
Definition at line 461 of file SwitchLoweringUtils.cpp.
References assert(), llvm::ConstantInt::getValue(), llvm::SwitchCG::CaseCluster::Low, llvm::SwitchCG::CaseCluster::MBB, N, llvm::SwitchCG::CaseCluster::Prob, llvm::APInt::slt(), and llvm::sort().
Referenced by llvm::IRTranslator::getAnalysisUsage(), and scaleCaseProbality().