LLVM: llvm::opt Namespace Reference
llvm::opt Namespace Reference
Classes
class Arg
A concrete instance of a particular driver option.
class arg_iterator
arg_iterator - Iterates through arguments stored inside an ArgList.
class ArgList
ArgList - Ordered collection of driver arguments.
class DerivedArgList
DerivedArgList - An ordered collection of driver arguments, whose storage may be in another argument list.
class InputArgList
class Option
Option - Abstract representation for a single form of driver argument.
class OptSpecifier
OptSpecifier - Wrapper class for abstracting references to option IDs.
class OptTable
Provide access to the Option info table.
Typedefs
using ArgStringList = SmallVector< const char *, 16 >
ArgStringList - Type used for constructing argv lists for subprocesses.
Enumerations
enum DriverFlag { HelpHidden = (1 << 0), RenderAsInput = (1 << 1), RenderJoined = (1 << 2), RenderSeparate = (1 << 3) }
Base flags for all options. Custom flags may be added after.
Functions
static int StrCmpOptionNameIgnoreCase (const char *A, const char *B)
static int StrCmpOptionName (const char *A, const char *B)
static bool operator< (const OptTable::Info &A, const OptTable::Info &B)
static bool operator< (const OptTable::Info &I, const char *Name)
Typedef Documentation
ArgStringList
using llvm::opt::ArgStringList = typedef SmallVector<const char *, 16>
ArgStringList - Type used for constructing argv lists for subprocesses.
Definition at line 30 of file Option.h.
Enumeration Type Documentation
DriverFlag
enum llvm::opt::DriverFlag
Base flags for all options. Custom flags may be added after.
Enumerator
HelpHidden
RenderAsInput
RenderJoined
RenderSeparate
Definition at line 33 of file Option.h.
Function Documentation
operator<() [1/2]
static bool llvm::opt::operator< (const OptTable::Info & A, const OptTable::Info & B) inline static
Definition at line 65 of file OptTable.cpp.
References assert(), llvm::opt::Option::JoinedClass, llvm::opt::OptTable::Info::Kind, N, llvm::opt::OptTable::Info::Name, llvm::opt::OptTable::Info::Prefixes, and StrCmpOptionName().
operator<() [2/2]
static bool llvm::opt::operator< (const OptTable::Info & I, const char * Name) inline static
Definition at line 88 of file OptTable.cpp.
References llvm::opt::OptTable::Info::Name, and StrCmpOptionNameIgnoreCase().
StrCmpOptionName()
static int llvm::opt::StrCmpOptionName (const char * A, const char * B) static
Definition at line 59 of file OptTable.cpp.
References N, and StrCmpOptionNameIgnoreCase().
Referenced by operator<().
StrCmpOptionNameIgnoreCase()
static int llvm::opt::StrCmpOptionNameIgnoreCase (const char * A, const char * B) static
Definition at line 38 of file OptTable.cpp.
References B, X, and Y.
Referenced by operator<(), and StrCmpOptionName().