LLVM: llvm::remarks Namespace Reference
llvm::remarks Namespace Reference
Classes
struct Argument
A key-value pair with a debug location that is used to display the remarks at the right place in the source.
struct BitstreamMetaParserHelper
Helper to parse a META_BLOCK for a bitstream remark container.
struct BitstreamMetaSerializer
Serializer of metadata for bitstream remarks.
struct BitstreamParserHelper
Helper to parse any bitstream remark container.
struct BitstreamRemarkParser
Parses and holds the state of the latest parsed remark.
struct BitstreamRemarkParserHelper
Helper to parse a REMARK_BLOCK for a bitstream remark container.
struct BitstreamRemarkSerializer
Implementation of the remark serializer using LLVM bitstream.
struct BitstreamRemarkSerializerHelper
Serialize the remarks to LLVM bitstream.
class EndOfFileError
struct MetaSerializer
This is the base class for a remark metadata serializer.
struct ParsedStringTable
In-memory representation of the string table parsed from a buffer (e.g.
struct Remark
A remark type used for both emission and parsing.
struct RemarkLinker
struct RemarkLocation
The debug location used to track a remark back to the source file.
struct RemarkParser
Parser used to parse a raw buffer to remarks::Remark objects.
struct RemarkSerializer
This is the base class for a remark serializer.
struct StringTable
The string table used for serializing remarks.
struct YAMLMetaSerializer
class YAMLParseError
struct YAMLRemarkParser
Regular YAML to Remark parser.
struct YAMLRemarkSerializer
Serialize the remarks to YAML.
struct YAMLStrTabMetaSerializer
struct YAMLStrTabRemarkParser
YAML with a string table to Remark parser.
struct YAMLStrTabRemarkSerializer
Serialize the remarks to YAML using a string table.
Enumerations
enum BitstreamRemarkContainerType {
BitstreamRemarkContainerType::SeparateRemarksMeta, BitstreamRemarkContainerType::SeparateRemarksFile, BitstreamRemarkContainerType::Standalone, BitstreamRemarkContainerType::First = SeparateRemarksMeta,
BitstreamRemarkContainerType::Last = Standalone
}
Type of the remark container.
enum BlockIDs { META_BLOCK_ID = bitc::FIRST_APPLICATION_BLOCKID, REMARK_BLOCK_ID }
The possible blocks that will be encountered in a bitstream remark container.
enum RecordIDs {
RECORD_META_CONTAINER_INFO = 1, RECORD_META_REMARK_VERSION, RECORD_META_STRTAB, RECORD_META_EXTERNAL_FILE,
RECORD_REMARK_HEADER, RECORD_REMARK_DEBUG_LOC, RECORD_REMARK_HOTNESS, RECORD_REMARK_ARG_WITH_DEBUGLOC,
RECORD_REMARK_ARG_WITHOUT_DEBUGLOC, RECORD_FIRST = RECORD_META_CONTAINER_INFO, RECORD_LAST = RECORD_REMARK_ARG_WITHOUT_DEBUGLOC
}
The possible records that can be encountered in the previously described blocks.
enum Type {
Type::Unknown, Type::Passed, Type::Missed, Type::Analysis,
Type::AnalysisFPCommute, Type::AnalysisAliasing, Type::Failure, Type::First = Unknown,
Type::Last = Failure
}
The type of the remark.
enum Format { Format::Unknown, Format::YAML, Format::YAMLStrTab, Format::Bitstream }
The format used for serializing/deserializing remarks.
enum SerializerMode { SerializerMode::Separate, SerializerMode::Standalone }
Functions
constexpr StringLiteral ContainerMagic ("RMRK")
The magic number used for identifying remark blocks.
template<typename T >
bool operator< (const Optional< T > &LHS, const Optional< T > &RHS)
Comparison operators for Remark objects and dependent objects.
bool operator== (const RemarkLocation &LHS, const RemarkLocation &RHS)
bool operator!= (const RemarkLocation &LHS, const RemarkLocation &RHS)
bool operator< (const RemarkLocation &LHS, const RemarkLocation &RHS)
bool operator== (const Argument &LHS, const Argument &RHS)
bool operator!= (const Argument &LHS, const Argument &RHS)
bool operator< (const Argument &LHS, const Argument &RHS)
bool operator== (const Remark &LHS, const Remark &RHS)
bool operator!= (const Remark &LHS, const Remark &RHS)
bool operator< (const Remark &LHS, const Remark &RHS)
constexpr StringLiteral Magic ("REMARKS")
Expected< Format > parseFormat (StringRef FormatStr)
Parse and validate a string for the remark format.
Expected< Format > magicToFormat (StringRef Magic)
Parse and validate a magic number to a remark format.
Expected< Optional< StringRef > > getRemarksSectionContents (const object::ObjectFile &Obj)
Returns a buffer with the contents of the remarks section depending on the format of the file.
Expected< std::unique_ptr< RemarkParser > > createRemarkParser (Format ParserFormat, StringRef Buf)
Expected< std::unique_ptr< RemarkParser > > createRemarkParser (Format ParserFormat, StringRef Buf, ParsedStringTable StrTab)
Expected< std::unique_ptr< RemarkParser > > createRemarkParserFromMeta (Format ParserFormat, StringRef Buf, Optional< ParsedStringTable > StrTab=None, Optional< StringRef > ExternalFilePrependPath=None)
Expected< std::unique_ptr< RemarkSerializer > > createRemarkSerializer (Format RemarksFormat, SerializerMode Mode, raw_ostream &OS)
Create a remark serializer.
Expected< std::unique_ptr< RemarkSerializer > > createRemarkSerializer (Format RemarksFormat, SerializerMode Mode, raw_ostream &OS, remarks::StringTable StrTab)
Create a remark serializer that uses a pre-filled string table.
Expected< std::unique_ptr< BitstreamRemarkParser > > createBitstreamParserFromMeta (StringRef Buf, Optional< ParsedStringTable > StrTab=None, Optional< StringRef > ExternalFilePrependPath=None)
Expected< std::unique_ptr< YAMLRemarkParser > > createYAMLParserFromMeta (StringRef Buf, Optional< ParsedStringTable > StrTab=None, Optional< StringRef > ExternalFilePrependPath=None)
Variables
constexpr uint64_t CurrentContainerVersion = 0
The current version of the remark container.
constexpr StringRef MetaBlockName = StringRef("Meta", 4)
constexpr StringRef RemarkBlockName = StringRef("Remark", 6)
constexpr StringRef MetaContainerInfoName = StringRef("Container info", 14)
constexpr StringRef MetaRemarkVersionName = StringRef("Remark version", 14)
constexpr StringRef MetaStrTabName = StringRef("String table", 12)
constexpr StringRef MetaExternalFileName = StringRef("External File", 13)
constexpr StringRef RemarkHeaderName = StringRef("Remark header", 13)
constexpr StringRef RemarkDebugLocName = StringRef("Remark debug location", 21)
constexpr StringRef RemarkHotnessName = StringRef("Remark hotness", 14)
constexpr StringRef RemarkArgWithDebugLocName
constexpr StringRef RemarkArgWithoutDebugLocName = StringRef("Argument", 8)
constexpr uint64_t CurrentRemarkVersion = 0
The current version of the remark entry.
Enumeration Type Documentation
BitstreamRemarkContainerType
enum llvm::remarks::BitstreamRemarkContainerType strong
Type of the remark container.
The remark container has two modes:
separate: the metadata is separate from the remarks and points to the auxiliary file that contains the remarks.
standalone: the metadata and the remarks are emitted together.
Enumerator
SeparateRemarksMeta
The metadata emitted separately.
This will contain the following:
Container version and type
String table
External file
SeparateRemarksFile
The remarks emitted separately.
This will contain the following:
Container version and type
Remark version
Standalone
Everything is emitted together.
This will contain the following:
Container version and type
Remark version
String table
First
Last
Definition at line 35 of file BitstreamRemarkContainer.h.
BlockIDs
enum llvm::remarks::BlockIDs
The possible blocks that will be encountered in a bitstream remark container.
Enumerator
META_BLOCK_ID
The metadata block is mandatory.
It should always come after the BLOCKINFO_BLOCK, and contains metadata that should be used when parsing REMARK_BLOCKs. There should always be only one META_BLOCK.
REMARK_BLOCK_ID
One remark entry is represented using a REMARK_BLOCK.
There can be multiple REMARK_BLOCKs in the same file.
Definition at line 59 of file BitstreamRemarkContainer.h.
Format
enum llvm::remarks::Format strong
The format used for serializing/deserializing remarks.
Enumerator
Unknown
YAML
YAMLStrTab
Bitstream
Definition at line 25 of file RemarkFormat.h.
RecordIDs
enum llvm::remarks::RecordIDs
The possible records that can be encountered in the previously described blocks.
Enumerator
RECORD_META_CONTAINER_INFO
RECORD_META_REMARK_VERSION
RECORD_META_STRTAB
RECORD_META_EXTERNAL_FILE
RECORD_REMARK_HEADER
RECORD_REMARK_DEBUG_LOC
RECORD_REMARK_HOTNESS
RECORD_REMARK_ARG_WITH_DEBUGLOC
RECORD_REMARK_ARG_WITHOUT_DEBUGLOC
RECORD_FIRST
RECORD_LAST
Definition at line 75 of file BitstreamRemarkContainer.h.
SerializerMode
enum llvm::remarks::SerializerMode strong
Enumerator
Separate
Standalone
Definition at line 24 of file RemarkSerializer.h.
Type
enum llvm::remarks::Type strong
The type of the remark.
Enumerator
Unknown
Passed
Missed
Analysis
AnalysisFPCommute
AnalysisAliasing
Failure
First
Last
Definition at line 54 of file Remark.h.
Function Documentation
ContainerMagic()
constexpr StringLiteral llvm::remarks::ContainerMagic ("RMRK")
The magic number used for identifying remark blocks.
Referenced by magicToFormat(), llvm::remarks::BitstreamRemarkSerializerHelper::setupBlockInfo(), and validateMagicNumber().
createBitstreamParserFromMeta()
Expected< std::unique_ptr< BitstreamRemarkParser > > llvm::remarks::createBitstreamParserFromMeta (StringRef Buf, Optional< ParsedStringTable > StrTab = None, Optional< StringRef > ExternalFilePrependPath = None)
Definition at line 309 of file BitstreamRemarkParser.cpp.
References E, llvm::remarks::BitstreamParserHelper::parseMagic(), llvm::Expected< T >::takeError(), and validateMagicNumber().
Referenced by llvm::remarks::BitstreamRemarkParser::classof(), and createRemarkParserFromMeta().
createRemarkParser() [1/2]
Expected< std::unique_ptr< RemarkParser > > llvm::remarks::createRemarkParser (Format ParserFormat, StringRef Buf)
Definition at line 52 of file RemarkParser.cpp.
References Bitstream, llvm::createStringError(), llvm_unreachable, llvm::make_error_code(), Unknown, YAML, and YAMLStrTab.
Referenced by llvm::remarks::ParsedStringTable::size().
createRemarkParser() [2/2]
Expected< std::unique_ptr< RemarkParser > > llvm::remarks::createRemarkParser (Format ParserFormat, StringRef Buf, ParsedStringTable StrTab)
Definition at line 70 of file RemarkParser.cpp.
References Bitstream, llvm::createStringError(), llvm_unreachable, llvm::make_error_code(), Unknown, YAML, and YAMLStrTab.
createRemarkParserFromMeta()
Expected< std::unique_ptr< RemarkParser > > llvm::remarks::createRemarkParserFromMeta (Format ParserFormat, StringRef Buf, Optional< ParsedStringTable > StrTab = None, Optional< StringRef > ExternalFilePrependPath = None)
Definition at line 89 of file RemarkParser.cpp.
References Bitstream, createBitstreamParserFromMeta(), llvm::createStringError(), createYAMLParserFromMeta(), llvm_unreachable, llvm::make_error_code(), Unknown, YAML, and YAMLStrTab.
Referenced by llvm::remarks::RemarkLinker::link(), and llvm::remarks::ParsedStringTable::size().
createRemarkSerializer() [1/2]
Expected< std::unique_ptr< RemarkSerializer > > llvm::remarks::createRemarkSerializer (Format RemarksFormat, SerializerMode Mode, raw_ostream & OS)
Create a remark serializer.
Definition at line 21 of file RemarkSerializer.cpp.
References Bitstream, llvm::createStringError(), llvm_unreachable, Mode, Unknown, YAML, and YAMLStrTab.
Referenced by llvm::remarks::MetaSerializer::MetaSerializer(), llvm::remarks::RemarkLinker::serialize(), and llvm::setupOptimizationRemarks().
createRemarkSerializer() [2/2]
Expected< std::unique_ptr< RemarkSerializer > > llvm::remarks::createRemarkSerializer (Format RemarksFormat, SerializerMode Mode, raw_ostream & OS, remarks::StringTable StrTab)
Create a remark serializer that uses a pre-filled string table.
Definition at line 38 of file RemarkSerializer.cpp.
References Bitstream, llvm::createStringError(), llvm_unreachable, Mode, Unknown, YAML, and YAMLStrTab.
createYAMLParserFromMeta()
Expected< std::unique_ptr< YAMLRemarkParser > > llvm::remarks::createYAMLParserFromMeta (StringRef Buf, Optional< ParsedStringTable > StrTab = None, Optional< StringRef > ExternalFilePrependPath = None)
Definition at line 112 of file YAMLRemarkParser.cpp.
References llvm::sys::path::append(), llvm::createFileError(), llvm::createStringError(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), parseMagic(), parseStrTab(), parseStrTabSize(), parseVersion(), llvm::StringRef::startswith(), llvm::Expected< T >::takeError(), and llvm::IndexedInstrProf::Version.
Referenced by llvm::remarks::YAMLStrTabRemarkParser::classof(), and createRemarkParserFromMeta().
getRemarksSectionContents()
Expected< Optional< StringRef > > llvm::remarks::getRemarksSectionContents (const object::ObjectFile & Obj)
Returns a buffer with the contents of the remarks section depending on the format of the file.
If the section doesn't exist, this returns an empty optional.
Definition at line 33 of file RemarkLinker.cpp.
References getRemarksSectionName(), llvm::remarks::StringTable::internalize(), llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), and llvm::Expected< T >::takeError().
Referenced by llvm::remarks::RemarkLinker::link(), and llvm::remarks::RemarkLinker::remarks().
Magic()
constexpr StringLiteral llvm::remarks::Magic ("REMARKS")
Referenced by emitMagic(), magicToFormat(), and parseMagic().
magicToFormat()
Expected< Format > llvm::remarks::magicToFormat (StringRef Magic)
Parse and validate a magic number to a remark format.
Definition at line 35 of file RemarkFormat.cpp.
References Bitstream, ContainerMagic(), llvm::createStringError(), llvm::StringRef::data(), llvm::StringSwitch< T, R >::Default(), Magic(), llvm::make_error_code(), llvm::StringSwitch< T, R >::StartsWith(), Unknown, YAML, and YAMLStrTab.
Referenced by llvm::remarks::RemarkLinker::link().
operator!=() [1/3]
bool llvm::remarks::operator!= (const RemarkLocation & LHS, const RemarkLocation & RHS) inline
Definition at line 134 of file Remark.h.
operator!=() [2/3]
bool llvm::remarks::operator!= (const Argument & LHS, const Argument & RHS) inline
Definition at line 147 of file Remark.h.
operator!=() [3/3]
bool llvm::remarks::operator!= (const Remark & LHS, const Remark & RHS) inline
Definition at line 163 of file Remark.h.
operator<() [1/4]
template<typename T > bool llvm::remarks::operator< (const Optional< T > & LHS, const Optional< T > & RHS)
Comparison operators for Remark objects and dependent objects.
Definition at line 115 of file Remark.h.
operator<() [2/4]
bool llvm::remarks::operator< (const RemarkLocation & LHS, const RemarkLocation & RHS) inline
Definition at line 138 of file Remark.h.
References llvm::remarks::RemarkLocation::SourceColumn, llvm::remarks::RemarkLocation::SourceFilePath, and llvm::remarks::RemarkLocation::SourceLine.
operator<() [3/4]
bool llvm::remarks::operator< (const Argument & LHS, const Argument & RHS) inline
Definition at line 151 of file Remark.h.
References llvm::remarks::Argument::Key, llvm::remarks::Argument::Loc, and llvm::remarks::Argument::Val.
operator<() [4/4]
bool llvm::remarks::operator< (const Remark & LHS, const Remark & RHS) inline
Definition at line 167 of file Remark.h.
References llvm::remarks::Remark::Args, llvm::remarks::Remark::FunctionName, llvm::remarks::Remark::Hotness, llvm::remarks::Remark::Loc, llvm::remarks::Remark::PassName, llvm::remarks::Remark::RemarkName, and llvm::remarks::Remark::RemarkType.
operator==() [1/3]
bool llvm::remarks::operator== (const RemarkLocation & LHS, const RemarkLocation & RHS) inline
Definition at line 128 of file Remark.h.
References llvm::remarks::RemarkLocation::SourceColumn, llvm::remarks::RemarkLocation::SourceFilePath, and llvm::remarks::RemarkLocation::SourceLine.
operator==() [2/3]
bool llvm::remarks::operator== (const Argument & LHS, const Argument & RHS) inline
Definition at line 143 of file Remark.h.
References llvm::remarks::Argument::Key, llvm::remarks::Argument::Loc, and llvm::remarks::Argument::Val.
operator==() [3/3]
bool llvm::remarks::operator== (const Remark & LHS, const Remark & RHS) inline
Definition at line 156 of file Remark.h.
References llvm::remarks::Remark::Args, llvm::remarks::Remark::FunctionName, llvm::remarks::Remark::Hotness, llvm::remarks::Remark::Loc, llvm::remarks::Remark::PassName, llvm::remarks::Remark::RemarkName, and llvm::remarks::Remark::RemarkType.
parseFormat()
Expected< Format > llvm::remarks::parseFormat (StringRef FormatStr)
Parse and validate a string for the remark format.
Definition at line 20 of file RemarkFormat.cpp.
References Bitstream, llvm::StringSwitch< T, R >::Case(), llvm::createStringError(), llvm::StringRef::data(), llvm::StringSwitch< T, R >::Default(), llvm::make_error_code(), Unknown, YAML, and YAMLStrTab.
Referenced by llvm::setupOptimizationRemarks().
Variable Documentation
CurrentContainerVersion
constexpr uint64_t llvm::remarks::CurrentContainerVersion = 0
The current version of the remark container.
Note: this is different from the version of the remark entry.
Definition at line 26 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamMetaSerializer::emit().
CurrentRemarkVersion
constexpr uint64_t llvm::remarks::CurrentRemarkVersion = 0
The current version of the remark entry.
Definition at line 27 of file Remark.h.
Referenced by llvm::remarks::BitstreamMetaSerializer::emit(), emitVersion(), and parseVersion().
MetaBlockName
constexpr StringRef llvm::remarks::MetaBlockName = StringRef("Meta", 4)
Definition at line 70 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaBlockInfo().
MetaContainerInfoName
constexpr StringRef llvm::remarks::MetaContainerInfoName = StringRef("Container info", 14)
Definition at line 92 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaBlockInfo().
MetaExternalFileName
constexpr StringRef llvm::remarks::MetaExternalFileName = StringRef("External File", 13)
Definition at line 95 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaExternalFile().
MetaRemarkVersionName
constexpr StringRef llvm::remarks::MetaRemarkVersionName = StringRef("Remark version", 14)
Definition at line 93 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaRemarkVersion().
MetaStrTabName
constexpr StringRef llvm::remarks::MetaStrTabName = StringRef("String table", 12)
Definition at line 94 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaStrTab().
RemarkArgWithDebugLocName
constexpr StringRef llvm::remarks::RemarkArgWithDebugLocName
Initial value:
=
    StringRef("Argument with debug location", 28)
Definition at line 99 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkArgWithoutDebugLocName
constexpr StringRef llvm::remarks::RemarkArgWithoutDebugLocName = StringRef("Argument", 8)
Definition at line 101 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkBlockName
constexpr StringRef llvm::remarks::RemarkBlockName = StringRef("Remark", 6)
Definition at line 71 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkDebugLocName
constexpr StringRef llvm::remarks::RemarkDebugLocName = StringRef("Remark debug location", 21)
Definition at line 97 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkHeaderName
constexpr StringRef llvm::remarks::RemarkHeaderName = StringRef("Remark header", 13)
Definition at line 96 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkHotnessName
constexpr StringRef llvm::remarks::RemarkHotnessName = StringRef("Remark hotness", 14)
Definition at line 98 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().