LLVM: llvm::ARMCC Namespace Reference
llvm::ARMCC Namespace Reference
Enumerations
enum CondCodes {
EQ, NE, HS, LO,
MI, PL, VS, VC,
HI, LS, GE, LT,
GT, LE, AL
}
Functions
static CondCodes getOppositeCondition (CondCodes CC)
static ARMCC::CondCodes getSwappedCondition (ARMCC::CondCodes CC)
getSwappedCondition - assume the flags are set by MI(a,b), return the condition code if we modify the instructions such that flags are set by MI(b,a).
Enumeration Type Documentation
CondCodes
enum llvm::ARMCC::CondCodes
Enumerator
EQ
NE
HS
LO
MI
PL
VS
VC
HI
LS
GE
LT
GT
LE
AL
Definition at line 30 of file ARMBaseInfo.h.
Function Documentation
getOppositeCondition()
static CondCodes llvm::ARMCC::getOppositeCondition (CondCodes CC) inline static
Definition at line 48 of file ARMBaseInfo.h.
References EQ, GE, GT, HI, HS, LE, llvm_unreachable, LO, LS, LT, MI, NE, PL, VC, and VS.
Referenced by llvm::ARMBaseInstrInfo::commuteInstructionImpl(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), getUnconditionalBrDisp(), isCopy(), llvm::IsCPSRDead< MCInst >(), llvm::ARMBaseInstrInfo::optimizeSelect(), PerformORCombine_i1(), and llvm::ARMInstPrinter::printMandatoryInvertedPredicateOperand().
getSwappedCondition()
static ARMCC::CondCodes llvm::ARMCC::getSwappedCondition (ARMCC::CondCodes CC) inline static
getSwappedCondition - assume the flags are set by MI(a,b), return the condition code if we modify the instructions such that flags are set by MI(b,a).
Definition at line 71 of file ARMBaseInfo.h.
References AL, EQ, GE, GT, HI, HS, LE, LO, LS, LT, and NE.