LLVM: llvm::wholeprogramdevirt Namespace Reference
llvm::wholeprogramdevirt Namespace Reference
Classes
struct AccumBitVector
struct TypeMemberInfo
struct VirtualCallTarget
struct VTableBits
Functions
uint64_t findLowestOffset (ArrayRef< VirtualCallTarget > Targets, bool IsAfter, uint64_t Size)
void setBeforeReturnValues (MutableArrayRef< VirtualCallTarget > Targets, uint64_t AllocBefore, unsigned BitWidth, int64_t &OffsetByte, uint64_t &OffsetBit)
void setAfterReturnValues (MutableArrayRef< VirtualCallTarget > Targets, uint64_t AllocAfter, unsigned BitWidth, int64_t &OffsetByte, uint64_t &OffsetBit)
Function Documentation
findLowestOffset()
uint64_t llvm::wholeprogramdevirt::findLowestOffset (ArrayRef< VirtualCallTarget > Targets, bool IsAfter, uint64_t Size)
Definition at line 141 of file WholeProgramDevirt.cpp.
References B, llvm::countTrailingZeros(), I, llvm::max(), llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), and llvm::ZB_Undefined.
Referenced by AddCalls(), and llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes().
setAfterReturnValues()
void llvm::wholeprogramdevirt::setAfterReturnValues (MutableArrayRef< VirtualCallTarget > Targets, uint64_t AllocAfter, unsigned BitWidth, int64_t & OffsetByte, uint64_t & OffsetBit)
Definition at line 231 of file WholeProgramDevirt.cpp.
Referenced by AddCalls(), and llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes().
setBeforeReturnValues()
void llvm::wholeprogramdevirt::setBeforeReturnValues (MutableArrayRef< VirtualCallTarget > Targets, uint64_t AllocBefore, unsigned BitWidth, int64_t & OffsetByte, uint64_t & OffsetBit)
Definition at line 214 of file WholeProgramDevirt.cpp.
Referenced by AddCalls(), and llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes().