LLVM: machine_size_opts_detail Namespace Reference
machine_size_opts_detail Namespace Reference
Functions
bool isColdBlock (const MachineBasicBlock *MBB, ProfileSummaryInfo *PSI, const MachineBlockFrequencyInfo *MBFI)
Like ProfileSummaryInfo::isColdBlock but for MachineBasicBlock.
static bool isHotBlockNthPercentile (int PercentileCutoff, const MachineBasicBlock *MBB, ProfileSummaryInfo *PSI, const MachineBlockFrequencyInfo *MBFI)
Like ProfileSummaryInfo::isHotBlockNthPercentile but for MachineBasicBlock.
bool isFunctionColdInCallGraph (const MachineFunction *MF, ProfileSummaryInfo *PSI, const MachineBlockFrequencyInfo &MBFI)
Like ProfileSummaryInfo::isFunctionColdInCallGraph but for MachineFunction.
bool isFunctionHotInCallGraphNthPercentile (int PercentileCutoff, const MachineFunction *MF, ProfileSummaryInfo *PSI, const MachineBlockFrequencyInfo &MBFI)
Like ProfileSummaryInfo::isFunctionHotInCallGraphNthPercentile but for MachineFunction.
Function Documentation
isColdBlock()
bool machine_size_opts_detail::isColdBlock (const MachineBasicBlock * MBB, ProfileSummaryInfo * PSI, const MachineBlockFrequencyInfo * MBFI)
Like ProfileSummaryInfo::isColdBlock but for MachineBasicBlock.
Definition at line 29 of file MachineSizeOpts.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockProfileCount(), and llvm::ProfileSummaryInfo::isColdCount().
Referenced by isFunctionColdInCallGraph(), isFunctionHotInCallGraphNthPercentile(), and llvm::shouldOptimizeForSizeImpl().
isFunctionColdInCallGraph()
bool machine_size_opts_detail::isFunctionColdInCallGraph (const MachineFunction * MF, ProfileSummaryInfo * PSI, const MachineBlockFrequencyInfo & MBFI)
Like ProfileSummaryInfo::isFunctionColdInCallGraph but for MachineFunction.
Definition at line 47 of file MachineSizeOpts.cpp.
References llvm::Function::getEntryCount(), llvm::MachineFunction::getFunction(), isColdBlock(), and llvm::ProfileSummaryInfo::isColdCount().
Referenced by isFunctionHotInCallGraphNthPercentile(), and llvm::shouldFuncOptimizeForSizeImpl().
isFunctionHotInCallGraphNthPercentile()
bool machine_size_opts_detail::isFunctionHotInCallGraphNthPercentile (int PercentileCutoff, const MachineFunction * MF, ProfileSummaryInfo * PSI, const MachineBlockFrequencyInfo & MBFI)
Like ProfileSummaryInfo::isFunctionHotInCallGraphNthPercentile but for MachineFunction.
Definition at line 62 of file MachineSizeOpts.cpp.
References llvm::Function::getEntryCount(), llvm::MachineFunction::getFunction(), isColdBlock(), isFunctionColdInCallGraph(), isHotBlockNthPercentile(), and llvm::ProfileSummaryInfo::isHotCountNthPercentile().
Referenced by llvm::shouldFuncOptimizeForSizeImpl().
isHotBlockNthPercentile()
static bool machine_size_opts_detail::isHotBlockNthPercentile (int PercentileCutoff, const MachineBasicBlock * MBB, ProfileSummaryInfo * PSI, const MachineBlockFrequencyInfo * MBFI) static
Like ProfileSummaryInfo::isHotBlockNthPercentile but for MachineBasicBlock.
Definition at line 37 of file MachineSizeOpts.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockProfileCount(), and llvm::ProfileSummaryInfo::isHotCountNthPercentile().
Referenced by isFunctionHotInCallGraphNthPercentile(), and llvm::shouldOptimizeForSizeImpl().