LLVM: lib/Transforms/Scalar/NaryReassociate.cpp File Reference
NaryReassociate.cpp File Reference
#include "llvm/Transforms/Scalar/NaryReassociate.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/Local.h"
#include <cassert>
#include <cstdint>
Macros
#define DEBUG_TYPE "nary-reassociate"
Functions
INITIALIZE_PASS_BEGIN (NaryReassociateLegacyPass, "nary-reassociate", "Nary reassociation", false, false) INITIALIZE_PASS_END(NaryReassociateLegacyPass
static bool isPotentiallyNaryReassociable (Instruction *I)
static bool isGEPFoldable (GetElementPtrInst *GEP, const TargetTransformInfo *TTI)
Variables
nary reassociate
nary Nary reassociation
nary Nary false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nary-reassociate"
Definition at line 115 of file NaryReassociate.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (NaryReassociateLegacyPass , "nary-reassociate" , "Nary reassociation" , false , false)
isGEPFoldable()
static bool isGEPFoldable (GetElementPtrInst * GEP, const TargetTransformInfo * TTI) static
Definition at line 298 of file NaryReassociate.cpp.
References llvm::MCID::Add, assert(), B, llvm::computeOverflowForSignedAdd(), CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast(), llvm::IRBuilder< T, Inserter >::CreateGEP(), CreateMul(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), E, GEP, llvm::gep_type_begin(), llvm::ConstantInt::get(), getBitWidth(), llvm::TargetTransformInfo::getGEPCost(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::User::getNumOperands(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getPointerAddressSpace(), llvm::GetElementPtrInst::getPointerOperand(), llvm::GetElementPtrInst::getResultElementType(), llvm::GetElementPtrInst::getSourceElementType(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::GetElementPtrInst::idx_begin(), llvm::GetElementPtrInst::idx_end(), llvm::GetElementPtrInst::isInBounds(), llvm::isKnownNonNegative(), llvm::generic_gep_type_iterator< ItTy >::isSequential(), llvm_unreachable, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::NeverOverflows, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::GetElementPtrInst::setIsInBounds(), llvm::Value::takeName(), and llvm::TargetTransformInfo::TCC_Free.
isPotentiallyNaryReassociable()
static bool isPotentiallyNaryReassociable (Instruction * I) static
Definition at line 217 of file NaryReassociate.cpp.
References llvm::MCID::Add, and llvm::Instruction::getOpcode().
Variable Documentation
false
nary Nary false
Definition at line 160 of file NaryReassociate.cpp.
reassociate
nary reassociate
Definition at line 160 of file NaryReassociate.cpp.
reassociation
nary Nary reassociation
Definition at line 160 of file NaryReassociate.cpp.