LLVM: lib/Target/NVPTX/NVPTXLowerArgs.cpp File Reference
NVPTXLowerArgs.cpp File Reference
#include "NVPTX.h"
#include "NVPTXTargetMachine.h"
#include "NVPTXUtilities.h"
#include "MCTargetDesc/NVPTXBaseInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
Namespaces
llvm
This class represents lattice values for constants.
Functions
void llvm::initializeNVPTXLowerArgsPass (PassRegistry &)
INITIALIZE_PASS (NVPTXLowerArgs, "nvptx-lower-args", "Lower arguments (NVPTX)", false, false) void NVPTXLowerArgs
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (NVPTXLowerArgs , "nvptx-lower-args" , "Lower arguments (NVPTX)" , false , false)
Definition at line 138 of file NVPTXLowerArgs.cpp.
References llvm::ADDRESS_SPACE_GLOBAL, llvm::ADDRESS_SPACE_PARAM, Arg, llvm::Function::args(), assert(), B, llvm::NVPTX::CUDA, llvm::dyn_cast(), F(), llvm::BasicBlock::front(), llvm::PointerType::get(), llvm::DataLayout::getAllocaAddrSpace(), llvm::Module::getDataLayout(), llvm::PointerType::getElementType(), llvm::Function::getEntryBlock(), llvm::Value::getName(), llvm::Function::getParamAlignment(), llvm::GlobalValue::getParent(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerElementType(), llvm::Value::getType(), llvm::GetUnderlyingObject(), I, llvm::isKernelFunction(), llvm::Value::replaceAllUsesWith(), runOnFunction(), llvm::AllocaInst::setAlignment(), and llvm::SystemZISD::TM.