LLVM: lib/Target/NVPTX/NVPTXGenericToNVVM.cpp File Reference
NVPTXGenericToNVVM.cpp File Reference
#include "MCTargetDesc/NVPTXBaseInfo.h"
#include "NVPTX.h"
#include "NVPTXUtilities.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ValueMap.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
Namespaces
llvm
This class represents lattice values for constants.
Functions
void llvm::initializeGenericToNVVMPass (PassRegistry &)
INITIALIZE_PASS (GenericToNVVM, "generic-to-nvvm", "Ensure that the global variables are in the global address space", false, false) bool GenericToNVVM
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (GenericToNVVM , "generic-to-nvvm" , "Ensure that the global variables are in the global address space" , false , false)
Definition at line 66 of file NVPTXGenericToNVVM.cpp.
References llvm::ADDRESS_SPACE_GENERIC, llvm::ADDRESS_SPACE_GLOBAL, assert(), C, llvm::GlobalVariable::copyAttributesFrom(), llvm::IRBuilder< T, Inserter >::CreateAddrSpaceCast(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateCast(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateInsertValue(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::numbers::e, E, llvm::GlobalVariable::eraseFromParent(), F(), for(), llvm::ConstantInt::get(), llvm::PointerType::get(), llvm::UndefValue::get(), llvm::PointerType::getAddressSpace(), llvm::Module::getContext(), llvm::ConstantExpr::getIndices(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::User::getNumOperands(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getPointerCast(), llvm::ConstantExpr::getPredicate(), llvm::GlobalValue::getThreadLocalMode(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::GlobalValue::getValueType(), llvm::GlobalVariable::hasInitializer(), I, llvm::ARM_PROC::IE, llvm::Instruction::isBinaryOp(), llvm::Instruction::isCast(), llvm::GlobalVariable::isConstant(), llvm::isSampler(), llvm::isSurface(), llvm::isTexture(), llvm_unreachable, llvm::makeArrayRef(), Name, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::MCID::Select, llvm::Value::setName(), and llvm::StringRef::startswith().