LLVM: lib/Target/NVPTX/NVPTXAssignValidGlobalNames.cpp File Reference
NVPTXAssignValidGlobalNames.cpp File Reference
#include "NVPTX.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/raw_ostream.h"
#include <string>
Namespaces
llvm
This class represents lattice values for constants.
Functions
void llvm::initializeNVPTXAssignValidGlobalNamesPass (PassRegistry &)
INITIALIZE_PASS (NVPTXAssignValidGlobalNames, "nvptx-assign-valid-global-names", "Assign valid PTX names to globals", false, false) bool NVPTXAssignValidGlobalNames
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (NVPTXAssignValidGlobalNames , "nvptx-assign-valid-global-names" , "Assign valid PTX names to globals" , false , false)
Definition at line 49 of file NVPTXAssignValidGlobalNames.cpp.
References C, E, F(), I, Name, llvm::StringRef::size(), and llvm::raw_string_ostream::str().