LLVM: lib/Target/NVPTX/NVVMReflect.cpp File Reference
NVVMReflect.cpp File Reference
#include "NVPTX.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_os_ostream.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include <sstream>
#include <string>
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define NVVM_REFLECT_FUNCTION "__nvvm_reflect"
#define DEBUG_TYPE "nvptx-reflect"
Functions
void llvm::initializeNVVMReflectPass (PassRegistry &)
INITIALIZE_PASS (NVVMReflect, "nvvm-reflect", "Replace occurrences of __nvvm_reflect() calls with 0/1", false, false) bool NVVMReflect
Variables
static cl::opt< bool > NVVMReflectEnabled ("nvvm-reflect-enable", cl::init(true), cl::Hidden, cl::desc("NVVM reflection, enabled by default"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-reflect"
Definition at line 45 of file NVVMReflect.cpp.
NVVM_REFLECT_FUNCTION
#define NVVM_REFLECT_FUNCTION "__nvvm_reflect"
Definition at line 41 of file NVVMReflect.cpp.
Referenced by INITIALIZE_PASS().
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (NVVMReflect , "nvvm-reflect" , "Replace occurrences of __nvvm_reflect() calls with 0/1" , false , false)
Definition at line 72 of file NVVMReflect.cpp.
References assert(), Callee, llvm::dbgs(), llvm::dyn_cast(), GEP, llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), llvm::Function::getIntrinsicID(), llvm::Value::getName(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), I, llvm::instructions(), LLVM_DEBUG, NVVM_REFLECT_FUNCTION, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::StringRef::size(), and llvm::StringRef::substr().
Variable Documentation
NVVMReflectEnabled
cl::opt<bool> NVVMReflectEnabled("nvvm-reflect-enable", cl::init(true), cl::Hidden, cl::desc("NVVM reflection, enabled by default")) static
Referenced by llvm::createNVVMReflectPass().