LLVM: lib/FuzzMutate/Operations.cpp File Reference
Operations.cpp File Reference
#include "llvm/FuzzMutate/Operations.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
Functions
static uint64_t getAggregateNumElements (Type *T)
static SourcePred validExtractValueIndex ()
static SourcePred matchScalarInAggregate ()
static SourcePred validInsertValueIndex ()
static SourcePred validShuffleVectorIndex ()
Function Documentation
getAggregateNumElements()
static uint64_t getAggregateNumElements (Type * T) static
Definition at line 182 of file Operations.cpp.
References assert(), llvm::Type::getArrayNumElements(), llvm::Type::getStructNumElements(), and llvm::Type::isAggregateType().
Referenced by validExtractValueIndex(), and validInsertValueIndex().
matchScalarInAggregate()
static SourcePred matchScalarInAggregate () static
Definition at line 221 of file Operations.cpp.
References E, getType(), I, and llvm::fuzzerop::makeConstantsWithType().
Referenced by llvm::fuzzerop::insertValueDescriptor().
validExtractValueIndex()
static SourcePred validExtractValueIndex () static
Definition at line 189 of file Operations.cpp.
References llvm::ConstantInt::get(), getAggregateNumElements(), llvm::Type::getInt32Ty(), getType(), Int32Ty, and N.
Referenced by llvm::fuzzerop::extractValueDescriptor().
validInsertValueIndex()
static SourcePred validInsertValueIndex () static
Definition at line 245 of file Operations.cpp.
References E, llvm::ConstantInt::get(), getAggregateNumElements(), llvm::Type::getInt32Ty(), getType(), I, and Int32Ty.
Referenced by llvm::fuzzerop::insertValueDescriptor().
validShuffleVectorIndex()
static SourcePred validShuffleVectorIndex () static
Definition at line 296 of file Operations.cpp.
References llvm::VectorType::get(), llvm::UndefValue::get(), llvm::Type::getInt32Ty(), Int32Ty, and llvm::ShuffleVectorInst::isValidOperands().
Referenced by llvm::fuzzerop::shuffleVectorDescriptor().