LLVM: lib/CodeGen/OptimizePHIs.cpp File Reference
OptimizePHIs.cpp File Reference
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include <cassert>
Macros
#define DEBUG_TYPE "opt-phis"
Functions
STATISTIC (NumPHICycles, "Number of PHI cycles replaced")
STATISTIC (NumDeadPHICycles, "Number of dead PHI cycles")
INITIALIZE_PASS (OptimizePHIs, DEBUG_TYPE, "Optimize machine instruction PHIs", false, false) bool OptimizePHIs
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "opt-phis"
Definition at line 30 of file OptimizePHIs.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (OptimizePHIs , DEBUG_TYPE , "Optimize machine instruction PHIs" , false , false)
Definition at line 71 of file OptimizePHIs.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineRegisterInfo::clearKillFlags(), llvm::MachineRegisterInfo::constrainRegClass(), E, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), llvm::MachineRegisterInfo::getVRegDef(), I, llvm::MachineInstr::isCopy(), llvm::MachineInstr::isPHI(), llvm::Register::isVirtualRegister(), MI, llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineRegisterInfo::use_nodbg_instructions(), and UseMI.
STATISTIC() [1/2]
STATISTIC (NumPHICycles , "Number of PHI cycles replaced")
STATISTIC() [2/2]
STATISTIC (NumDeadPHICycles , "Number of dead PHI cycles")