LLVM: lib/Option/OptTable.cpp File Reference
OptTable.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/Option.h"
#include "llvm/Option/OptSpecifier.h"
#include "llvm/Option/OptTable.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstring>
#include <map>
#include <string>
#include <utility>
#include <vector>
Namespaces
llvm
This class represents lattice values for constants.
llvm::opt
Functions
static int llvm::opt::StrCmpOptionNameIgnoreCase (const char *A, const char *B)
static int llvm::opt::StrCmpOptionName (const char *A, const char *B)
static bool llvm::opt::operator< (const OptTable::Info &A, const OptTable::Info &B)
static bool llvm::opt::operator< (const OptTable::Info &I, const char *Name)
static bool isInput (const StringSet<> &Prefixes, StringRef Arg)
static unsigned matchOption (const OptTable::Info *I, StringRef Str, bool IgnoreCase)
static bool optionMatches (const OptTable::Info &In, StringRef Option)
static std::string getOptionHelpName (const OptTable &Opts, OptSpecifier Id)
static void PrintHelpOptionList (raw_ostream &OS, StringRef Title, std::vector< OptionInfo > &OptionHelp)
static const char * getOptionHelpGroup (const OptTable &Opts, OptSpecifier Id)
Function Documentation
getOptionHelpGroup()
static const char* getOptionHelpGroup (const OptTable & Opts, OptSpecifier Id) static
Definition at line 515 of file OptTable.cpp.
References llvm::opt::OptTable::getOptionGroupID(), and llvm::opt::OptTable::getOptionHelpText().
Referenced by llvm::opt::OptTable::PrintHelp().
getOptionHelpName()
static std::string getOptionHelpName (const OptTable & Opts, OptSpecifier Id) static
Definition at line 435 of file OptTable.cpp.
References llvm::opt::Option::CommaJoinedClass, llvm::numbers::e, llvm::opt::Option::FlagClass, llvm::opt::Option::getKind(), llvm::opt::Option::getNumArgs(), llvm::opt::OptTable::getOption(), llvm::opt::OptTable::getOptionMetaVar(), llvm::opt::Option::getPrefixedName(), llvm::opt::Option::GroupClass, llvm::opt::Option::InputClass, llvm::opt::Option::JoinedAndSeparateClass, llvm::opt::Option::JoinedClass, llvm::opt::Option::JoinedOrSeparateClass, LLVM_FALLTHROUGH, llvm_unreachable, llvm::opt::Option::MultiArgClass, Name, llvm::RISCVFenceField::O, llvm::opt::Option::RemainingArgsClass, llvm::opt::Option::RemainingArgsJoinedClass, llvm::opt::Option::SeparateClass, llvm::opt::Option::UnknownClass, and llvm::opt::Option::ValuesClass.
Referenced by llvm::opt::OptTable::PrintHelp().
isInput()
static bool isInput (const StringSet<> & Prefixes, StringRef Arg) static
Definition at line 169 of file OptTable.cpp.
References llvm::StringMap< NoneType, AllocatorTy >::begin(), E, llvm::StringMap< NoneType, AllocatorTy >::end(), I, and llvm::StringRef::startswith().
Referenced by llvm::InlineAsm::ConstraintInfo::Parse(), llvm::opt::OptTable::ParseOneArg(), and RemoveInstInputs().
matchOption()
static unsigned matchOption (const OptTable::Info * I, StringRef Str, bool IgnoreCase) static
Returns
Matched size. 0 means no match.
Definition at line 180 of file OptTable.cpp.
References llvm::opt::OptTable::Info::Name, llvm::cl::Prefix, llvm::opt::OptTable::Info::Prefixes, llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::StringRef::startswith_lower(), and llvm::StringRef::substr().
optionMatches()
static bool optionMatches (const OptTable::Info & In, StringRef Option) static
Definition at line 197 of file OptTable.cpp.
References I, llvm::opt::OptTable::Info::Name, and llvm::opt::OptTable::Info::Prefixes.
Referenced by llvm::opt::OptTable::addValues(), and llvm::opt::OptTable::suggestValueCompletions().
PrintHelpOptionList()
static void PrintHelpOptionList (raw_ostream & OS, StringRef Title, std::vector< OptionInfo > & OptionHelp) static
Definition at line 487 of file OptTable.cpp.
References llvm::numbers::e, llvm::raw_ostream::indent(), llvm::max(), and llvm::StringRef::size().
Referenced by llvm::opt::OptTable::PrintHelp().