LLVM: lib/CodeGen/PatchableFunction.cpp File Reference
PatchableFunction.cpp File Reference
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
Functions
static bool doesNotGeneratecode (const MachineInstr &MI)
Returns true if instruction MI will not result in actual machine code instructions.
Function Documentation
doesNotGeneratecode()
static bool doesNotGeneratecode (const MachineInstr & MI) static
Returns true if instruction MI will not result in actual machine code instructions.
Definition at line 42 of file PatchableFunction.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::ISD::EH_LABEL, llvm::MachineBasicBlock::empty(), llvm::MachineFunction::ensureAlignment(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineFunction::getSubtarget(), llvm::Attribute::getValueAsString(), llvm::Function::hasFnAttribute(), llvm::AMDGPUISD::KILL, and TII.