LLVM: lib/Analysis/PHITransAddr.cpp File Reference
PHITransAddr.cpp File Reference
#include "llvm/Analysis/PHITransAddr.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
static bool CanPHITrans (Instruction *Inst)
static bool VerifySubExpr (Value *Expr, SmallVectorImpl< Instruction *> &InstInputs)
static void RemoveInstInputs (Value *V, SmallVectorImpl< Instruction *> &InstInputs)
Function Documentation
CanPHITrans()
static bool CanPHITrans (Instruction * Inst) static
Definition at line 25 of file PHITransAddr.cpp.
References llvm::MCID::Add, llvm::Instruction::getOpcode(), llvm::User::getOperand(), and llvm::isSafeToSpeculativelyExecute().
Referenced by llvm::PHITransAddr::IsPotentiallyPHITranslatable(), RemoveInstInputs(), and VerifySubExpr().
RemoveInstInputs()
static void RemoveInstInputs (Value * V, SmallVectorImpl< Instruction *> & InstInputs) static
Definition at line 122 of file PHITransAddr.cpp.
References llvm::MCID::Add, assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), C, CanPHITrans(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::lltok::equal, llvm::SmallVectorImpl< T >::erase(), llvm::find(), GEP, llvm::ConstantExpr::getAdd(), llvm::ConstantExpr::getCast(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::Value::getType(), hasNoSignedWrap(), hasNoUnsignedWrap(), I, llvm::is_contained(), isInput(), llvm::isSafeToSpeculativelyExecute(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SimplifyAddInst(), llvm::SimplifyGEPInst(), llvm::SmallVectorBase::size(), and llvm::Value::users().
VerifySubExpr()
static bool VerifySubExpr (Value * Expr, SmallVectorImpl< Instruction *> & InstInputs) static
Definition at line 57 of file PHITransAddr.cpp.
References CanPHITrans(), llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::errs(), llvm::find(), llvm::User::getNumOperands(), llvm::User::getOperand(), I, and llvm_unreachable.
Referenced by llvm::PHITransAddr::Verify().