LLVM: lib/Target/PowerPC/MCTargetDesc/PPCAsmBackend.cpp File Reference
PPCAsmBackend.cpp File Reference
#include "MCTargetDesc/PPCFixupKinds.h"
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
Functions
static uint64_t adjustFixupValue (unsigned Kind, uint64_t Value)
static unsigned getFixupKindNumBytes (unsigned Kind)
Function Documentation
adjustFixupValue()
static uint64_t adjustFixupValue (unsigned Kind, uint64_t Value) static
Definition at line 27 of file PPCAsmBackend.cpp.
References llvm::PPC::fixup_ppc_br24, llvm::PPC::fixup_ppc_br24abs, llvm::PPC::fixup_ppc_brcond14, llvm::PPC::fixup_ppc_brcond14abs, llvm::PPC::fixup_ppc_half16, llvm::PPC::fixup_ppc_half16ds, llvm::PPC::fixup_ppc_nofixup, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_NONE, and llvm_unreachable.
Referenced by getFixupKindNumBytes().
getFixupKindNumBytes()
static unsigned getFixupKindNumBytes (unsigned Kind) static
Definition at line 51 of file PPCAsmBackend.cpp.
References adjustFixupValue(), llvm::HexStyle::Asm, assert(), llvm::support::big, llvm::MachO::CPU_SUBTYPE_POWERPC_ALL, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::createPPCELFObjectWriter(), llvm::createPPCMachObjectWriter(), llvm::createPPCXCOFFObjectWriter(), llvm::Data, DF, llvm::FirstTargetFixupKind, Fixup, llvm::PPC::fixup_ppc_br24, llvm::PPC::fixup_ppc_br24abs, llvm::PPC::fixup_ppc_brcond14, llvm::PPC::fixup_ppc_brcond14abs, llvm::PPC::fixup_ppc_half16, llvm::PPC::fixup_ppc_half16ds, llvm::PPC::fixup_ppc_nofixup, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_NONE, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKind(), llvm::MCAsmBackend::getFixupKindInfo(), llvm::MCFixup::getKind(), llvm::MCFixup::getOffset(), llvm::Triple::getOS(), llvm::MCELFObjectTargetWriter::getOSABI(), llvm::MCValue::getSymA(), llvm::Triple::isArch64Bit(), llvm::Triple::isLittleEndian(), llvm::Triple::isPPC64(), llvm::support::little, llvm_unreachable, Name, llvm::PPC::NumTargetFixupKinds, llvm::Other, llvm::ELF::STO_PPC64_LOCAL_MASK, llvm::TT, and llvm::raw_ostream::write_zeros().