LLVM: lib/Target/PowerPC/PPCCallingConv.cpp File Reference
PPCCallingConv.cpp File Reference
#include "PPCRegisterInfo.h"
#include "PPCCallingConv.h"
#include "PPCSubtarget.h"
#include "PPCCCState.h"
#include "PPCGenCallingConv.inc"
Functions
bool CC_PPC_AnyReg_Error (unsigned &, MVT &, MVT &, CCValAssign::LocInfo &, ISD::ArgFlagsTy &, CCState &)
static bool CC_PPC32_SVR4_Custom_Dummy (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SVR4_Custom_AlignArgRegs (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SVR4_Custom_SkipLastArgRegsPPCF128 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SVR4_Custom_AlignFPArgRegs (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SPE_CustomSplitFP64 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SPE_RetF64 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
Function Documentation
CC_PPC32_SPE_CustomSplitFP64()
static bool CC_PPC32_SPE_CustomSplitFP64 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 109 of file PPCCallingConv.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateReg(), assert(), llvm::CCValAssign::getCustomReg(), R4, R6, and Reg.
CC_PPC32_SPE_RetF64()
static bool CC_PPC32_SPE_RetF64 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 138 of file PPCCallingConv.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateReg(), llvm::CCValAssign::getCustomReg(), R4, and Reg.
CC_PPC32_SVR4_Custom_AlignArgRegs()
static bool CC_PPC32_SVR4_Custom_AlignArgRegs (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 31 of file PPCCallingConv.cpp.
References llvm::CCState::AllocateReg(), llvm::array_lengthof(), llvm::CCState::getFirstUnallocated(), R4, and R6.
CC_PPC32_SVR4_Custom_AlignFPArgRegs()
static bool CC_PPC32_SVR4_Custom_AlignFPArgRegs (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 81 of file PPCCallingConv.cpp.
References llvm::CCState::AllocateReg(), llvm::array_lengthof(), and llvm::CCState::getFirstUnallocated().
CC_PPC32_SVR4_Custom_Dummy()
static bool CC_PPC32_SVR4_Custom_Dummy (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 24 of file PPCCallingConv.cpp.
CC_PPC32_SVR4_Custom_SkipLastArgRegsPPCF128()
static bool CC_PPC32_SVR4_Custom_SkipLastArgRegsPPCF128 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 58 of file PPCCallingConv.cpp.
References llvm::CCState::AllocateReg(), llvm::array_lengthof(), llvm::CCState::getFirstUnallocated(), R4, and R6.
CC_PPC_AnyReg_Error()
bool CC_PPC_AnyReg_Error (unsigned & , MVT & , MVT & , CCValAssign::LocInfo & , ISD::ArgFlagsTy & , CCState &) inline
Definition at line 15 of file PPCCallingConv.cpp.
References llvm_unreachable.