LLVM: lib/Target/PowerPC/MCTargetDesc/PPCELFObjectWriter.cpp File Reference
PPCELFObjectWriter.cpp File Reference
#include "MCTargetDesc/PPCFixupKinds.h"
#include "MCTargetDesc/PPCMCExpr.h"
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static MCSymbolRefExpr::VariantKind getAccessVariant (const MCValue &Target, const MCFixup &Fixup)
Function Documentation
getAccessVariant()
static MCSymbolRefExpr::VariantKind getAccessVariant (const MCValue & Target, const MCFixup & Fixup) static
Definition at line 41 of file PPCELFObjectWriter.cpp.
References llvm::errs(), Fixup, llvm::PPC::fixup_ppc_br24, llvm::PPC::fixup_ppc_br24abs, llvm::PPC::fixup_ppc_brcond14, llvm::PPC::fixup_ppc_brcond14abs, llvm::PPC::fixup_ppc_half16, llvm::PPC::fixup_ppc_half16ds, llvm::PPC::fixup_ppc_nofixup, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_NONE, llvm::FK_PCRel_4, llvm::FK_PCRel_8, llvm::MCValue::getAccessVariant(), llvm::MCExpr::getKind(), getRelocType(), llvm::MCFixup::getTargetKind(), llvm::MCFixup::getValue(), is64Bit(), llvm_unreachable, Other, llvm::MCValue::print(), llvm::report_fatal_error(), llvm::ELF::STO_PPC64_LOCAL_MASK, llvm::MCExpr::Target, llvm::MCSymbolRefExpr::VK_DTPREL, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_PPC_DTPMOD, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HA, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HI, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HIGH, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HIGHA, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HIGHER, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HIGHERA, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HIGHEST, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HIGHESTA, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_DTPREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_DTPREL_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_DTPREL_HI, llvm::MCSymbolRefExpr::VK_PPC_GOT_DTPREL_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_HI, llvm::MCSymbolRefExpr::VK_PPC_GOT_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_HI, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_HI, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_HI, llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_LO, llvm::PPCMCExpr::VK_PPC_HA, llvm::MCSymbolRefExpr::VK_PPC_HA, llvm::PPCMCExpr::VK_PPC_HI, llvm::MCSymbolRefExpr::VK_PPC_HI, llvm::PPCMCExpr::VK_PPC_HIGH, llvm::MCSymbolRefExpr::VK_PPC_HIGH, llvm::PPCMCExpr::VK_PPC_HIGHA, llvm::MCSymbolRefExpr::VK_PPC_HIGHA, llvm::PPCMCExpr::VK_PPC_HIGHER, llvm::MCSymbolRefExpr::VK_PPC_HIGHER, llvm::PPCMCExpr::VK_PPC_HIGHERA, llvm::MCSymbolRefExpr::VK_PPC_HIGHERA, llvm::PPCMCExpr::VK_PPC_HIGHEST, llvm::MCSymbolRefExpr::VK_PPC_HIGHEST, llvm::PPCMCExpr::VK_PPC_HIGHESTA, llvm::MCSymbolRefExpr::VK_PPC_HIGHESTA, llvm::PPCMCExpr::VK_PPC_LO, llvm::MCSymbolRefExpr::VK_PPC_LO, llvm::MCSymbolRefExpr::VK_PPC_LOCAL, llvm::PPCMCExpr::VK_PPC_None, llvm::MCSymbolRefExpr::VK_PPC_TLS, llvm::MCSymbolRefExpr::VK_PPC_TLSGD, llvm::MCSymbolRefExpr::VK_PPC_TLSLD, llvm::MCSymbolRefExpr::VK_PPC_TOC, llvm::MCSymbolRefExpr::VK_PPC_TOC_HA, llvm::MCSymbolRefExpr::VK_PPC_TOC_HI, llvm::MCSymbolRefExpr::VK_PPC_TOC_LO, llvm::MCSymbolRefExpr::VK_PPC_TOCBASE, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HA, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HI, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HIGH, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HIGHA, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HIGHER, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HIGHERA, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HIGHEST, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HIGHESTA, llvm::MCSymbolRefExpr::VK_PPC_TPREL_LO, and llvm::MCSymbolRefExpr::VK_TPREL.