LLVM: lib/Target/PowerPC/MCTargetDesc/PPCInstPrinter.cpp File Reference
PPCInstPrinter.cpp File Reference
#include "MCTargetDesc/PPCInstPrinter.h"
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "PPCInstrInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
#include "PPCGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
#define PRINT_ALIAS_INSTR
Variables
static cl::opt< bool > FullRegNames ("ppc-asm-full-reg-names", cl::Hidden, cl::init(false), cl::desc("Use full register names when printing assembly"))
static cl::opt< bool > ShowVSRNumsAsVR ("ppc-vsr-nums-as-vr", cl::Hidden, cl::init(false), cl::desc("Prints full register names with vs{31-63} as v{0-31}"))
static cl::opt< bool > FullRegNamesWithPercent ("ppc-reg-with-percent-prefix", cl::Hidden, cl::init(false), cl::desc("Prints full register names with percent"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 28 of file PPCInstPrinter.cpp.
PRINT_ALIAS_INSTR
#define PRINT_ALIAS_INSTR
Definition at line 47 of file PPCInstPrinter.cpp.
Variable Documentation
FullRegNames
cl::opt<bool> FullRegNames("ppc-asm-full-reg-names", cl::Hidden, cl::init(false), cl::desc("Use full register names when printing assembly")) static
Referenced by llvm::PPCInstPrinter::printTLSCall().
FullRegNamesWithPercent
cl::opt<bool> FullRegNamesWithPercent("ppc-reg-with-percent-prefix", cl::Hidden, cl::init(false), cl::desc("Prints full register names with percent")) static
Referenced by llvm::PPCInstPrinter::printTLSCall().
ShowVSRNumsAsVR
cl::opt<bool> ShowVSRNumsAsVR("ppc-vsr-nums-as-vr", cl::Hidden, cl::init(false), cl::desc("Prints full register names with vs{31-63} as v{0-31}")) static
Referenced by llvm::PPCInstPrinter::printOperand().