LLVM: lib/Target/PowerPC/PPCISelLowering.cpp File Reference
PPCISelLowering.cpp File Reference
#include "PPCISelLowering.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "PPC.h"
#include "PPCCCState.h"
#include "PPCCallingConv.h"
#include "PPCFrameLowering.h"
#include "PPCInstrInfo.h"
#include "PPCMachineFunctionInfo.h"
#include "PPCPerfectShuffle.h"
#include "PPCRegisterInfo.h"
#include "PPCSubtarget.h"
#include "PPCTargetMachine.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsPowerPC.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/Value.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSymbolXCOFF.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iterator>
#include <list>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "ppc-lowering"
Functions
STATISTIC (NumTailCalls, "Number of tail calls")
STATISTIC (NumSiblingCalls, "Number of sibling calls")
static bool isNByteElemShuffleMask (ShuffleVectorSDNode *N, unsigned Width, int StepLen)
Check that the mask is shuffling N byte elements.
static SDValue widenVec (SelectionDAG &DAG, SDValue Vec, const SDLoc &dl)
static void getMaxByValAlign (Type *Ty, unsigned &MaxAlign, unsigned MaxMaxAlign)
getMaxByValAlign - Helper for getByValTypeAlignment to determine the desired ByVal argument alignment.
static bool isFloatingPointZero (SDValue Op)
isFloatingPointZero - Return true if this is 0.0 or -0.0.
static bool isConstantOrUndef (int Op, int Val)
isConstantOrUndef - Op is either an undef node or a ConstantSDNode.
static bool isVMerge (ShuffleVectorSDNode *N, unsigned UnitSize, unsigned LHSStart, unsigned RHSStart)
isVMerge - Common function, used to match vmrg* shuffles.
static bool isVMerge (ShuffleVectorSDNode *N, unsigned IndexOffset, unsigned RHSStartValue)
Common function used to match vmrgew and vmrgow shuffles.
static bool isXXBRShuffleMaskHelper (ShuffleVectorSDNode *N, int Width)
static void fixupFuncForFI (SelectionDAG &DAG, int FrameIdx, EVT VT)
static bool usePartialVectorLoads (SDNode *N, const PPCSubtarget &ST)
Returns true if we should use a direct load into vector instruction (such as lxsd or lfd), instead of a load into gpr + direct move sequence.
static void getLabelAccessInfo (bool IsPIC, const PPCSubtarget &Subtarget, unsigned &HiOpFlags, unsigned &LoOpFlags, const GlobalValue *GV=nullptr)
Return true if we should reference labels using a PICBase, set the HiOpFlags and LoOpFlags to the target MO flags.
static SDValue LowerLabelRef (SDValue HiPart, SDValue LoPart, bool isPIC, SelectionDAG &DAG)
static void setUsesTOCBasePtr (MachineFunction &MF)
static void setUsesTOCBasePtr (SelectionDAG &DAG)
static unsigned CalculateStackSlotSize (EVT ArgVT, ISD::ArgFlagsTy Flags, unsigned PtrByteSize)
CalculateStackSlotSize - Calculates the size reserved for this argument on the stack.
static unsigned CalculateStackSlotAlignment (EVT ArgVT, EVT OrigVT, ISD::ArgFlagsTy Flags, unsigned PtrByteSize)
CalculateStackSlotAlignment - Calculates the alignment of this argument on the stack.
static bool CalculateStackSlotUsed (EVT ArgVT, EVT OrigVT, ISD::ArgFlagsTy Flags, unsigned PtrByteSize, unsigned LinkageSize, unsigned ParamAreaSize, unsigned &ArgOffset, unsigned &AvailableFPRs, unsigned &AvailableVRs, bool HasQPX)
CalculateStackSlotUsed - Return whether this argument will use its stack slot (instead of being passed in registers).
static unsigned EnsureStackAlignment (const PPCFrameLowering *Lowering, unsigned NumBytes)
EnsureStackAlignment - Round stack frame size up from NumBytes to ensure minimum alignment required for target.
static int CalculateTailCallSPDiff (SelectionDAG &DAG, bool isTailCall, unsigned ParamSize)
CalculateTailCallSPDiff - Get the amount the stack pointer has to be adjusted to accommodate the arguments for the tailcall.
static bool isFunctionGlobalAddress (SDValue Callee)
static bool callsShareTOCBase (const Function *Caller, SDValue Callee, const TargetMachine &TM)
static bool needStackSlotPassParameters (const PPCSubtarget &Subtarget, const SmallVectorImpl< ISD::OutputArg > &Outs)
static bool hasSameArgumentList (const Function *CallerFn, ImmutableCallSite CS)
static bool areCallingConvEligibleForTCO_64SVR4 (CallingConv::ID CallerCC, CallingConv::ID CalleeCC)
static SDNode * isBLACompatibleAddress (SDValue Op, SelectionDAG &DAG)
isCallCompatibleAddress - Return the immediate to use if the specified 32-bit value is representable in the immediate field of a BxA instruction.
static void StoreTailCallArgumentsToStackSlot (SelectionDAG &DAG, SDValue Chain, const SmallVectorImpl< TailCallArgumentInfo > &TailCallArgs, SmallVectorImpl< SDValue > &MemOpChains, const SDLoc &dl)
StoreTailCallArgumentsToStackSlot - Stores arguments to their stack slot.
static SDValue EmitTailCallStoreFPAndRetAddr (SelectionDAG &DAG, SDValue Chain, SDValue OldRetAddr, SDValue OldFP, int SPDiff, const SDLoc &dl)
EmitTailCallStoreFPAndRetAddr - Move the frame pointer and return address to the appropriate stack slot for the tail call optimized function call.
static void CalculateTailCallArgDest (SelectionDAG &DAG, MachineFunction &MF, bool isPPC64, SDValue Arg, int SPDiff, unsigned ArgOffset, SmallVectorImpl< TailCallArgumentInfo > &TailCallArguments)
CalculateTailCallArgDest - Remember Argument for later processing.
static SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG &DAG, const SDLoc &dl)
CreateCopyOfByValArgument - Make a copy of an aggregate at address specified by "Src" to address "Dst" of size "Size".
static void LowerMemOpCallTo (SelectionDAG &DAG, MachineFunction &MF, SDValue Chain, SDValue Arg, SDValue PtrOff, int SPDiff, unsigned ArgOffset, bool isPPC64, bool isTailCall, bool isVector, SmallVectorImpl< SDValue > &MemOpChains, SmallVectorImpl< TailCallArgumentInfo > &TailCallArguments, const SDLoc &dl)
LowerMemOpCallTo - Store the argument to the stack or remember it in case of tail calls.
static void PrepareTailCall (SelectionDAG &DAG, SDValue &InFlag, SDValue &Chain, const SDLoc &dl, int SPDiff, unsigned NumBytes, SDValue LROp, SDValue FPOp, SmallVectorImpl< TailCallArgumentInfo > &TailCallArguments)
static bool isIndirectCall (const SDValue &Callee, SelectionDAG &DAG, const PPCSubtarget &Subtarget, bool isPatchPoint)
static unsigned getCallOpcode (bool isIndirectCall, bool isPatchPoint, bool isTailCall, const Function &Caller, const SDValue &Callee, const PPCSubtarget &Subtarget, const TargetMachine &TM)
static bool isValidAIXExternalSymSDNode (StringRef SymName)
static SDValue transformCallee (const SDValue &Callee, SelectionDAG &DAG, const SDLoc &dl, const PPCSubtarget &Subtarget)
static SDValue getOutputChainFromCallSeq (SDValue CallSeqStart)
static void prepareIndirectCall (SelectionDAG &DAG, SDValue &Callee, SDValue &Glue, SDValue &Chain, const SDLoc &dl)
static void prepareDescriptorIndirectCall (SelectionDAG &DAG, SDValue &Callee, SDValue &Glue, SDValue &Chain, SDValue CallSeqStart, ImmutableCallSite CS, const SDLoc &dl, bool hasNest, const PPCSubtarget &Subtarget)
static void buildCallOperands (SmallVectorImpl< SDValue > &Ops, CallingConv::ID CallConv, const SDLoc &dl, bool isTailCall, bool isVarArg, bool isPatchPoint, bool hasNest, SelectionDAG &DAG, SmallVector< std::pair< unsigned, SDValue >, 8 > &RegsToPass, SDValue Glue, SDValue Chain, SDValue &Callee, int SPDiff, const PPCSubtarget &Subtarget, bool isIndirect)
static bool CC_AIX (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State)
static const TargetRegisterClass * getRegClassForSVT (MVT::SimpleValueType SVT, bool IsPPC64)
static SDValue truncateScalarIntegerArg (ISD::ArgFlagsTy Flags, EVT ValVT, SelectionDAG &DAG, SDValue ArgValue, MVT LocVT, const SDLoc &dl)
static SDValue BuildSplatI (int Val, unsigned SplatSize, EVT VT, SelectionDAG &DAG, const SDLoc &dl)
BuildSplatI - Build a canonical splati of Val with an element size of SplatSize.
static SDValue BuildIntrinsicOp (unsigned IID, SDValue Op, SelectionDAG &DAG, const SDLoc &dl, EVT DestVT=MVT::Other)
BuildIntrinsicOp - Return a unary operator intrinsic node with the specified intrinsic ID.
static SDValue BuildIntrinsicOp (unsigned IID, SDValue LHS, SDValue RHS, SelectionDAG &DAG, const SDLoc &dl, EVT DestVT=MVT::Other)
BuildIntrinsicOp - Return a binary operator intrinsic node with the specified intrinsic ID.
static SDValue BuildIntrinsicOp (unsigned IID, SDValue Op0, SDValue Op1, SDValue Op2, SelectionDAG &DAG, const SDLoc &dl, EVT DestVT=MVT::Other)
BuildIntrinsicOp - Return a ternary operator intrinsic node with the specified intrinsic ID.
static SDValue BuildVSLDOI (SDValue LHS, SDValue RHS, unsigned Amt, EVT VT, SelectionDAG &DAG, const SDLoc &dl)
BuildVSLDOI - Return a VECTOR_SHUFFLE that is a vsldoi of the specified amount.
static bool haveEfficientBuildVectorPattern (BuildVectorSDNode *V, bool HasDirectMove, bool HasP8Vector)
Do we have an efficient pattern in a .td file for this node?
static const SDValue * getNormalLoadInput (const SDValue &Op)
static SDValue GeneratePerfectShuffle (unsigned PFEntry, SDValue LHS, SDValue RHS, SelectionDAG &DAG, const SDLoc &dl)
GeneratePerfectShuffle - Given an entry in the perfect-shuffle table, emit the specified operations to build the shuffle.
static bool getVectorCompareInfo (SDValue Intrin, int &CompareOpc, bool &isDot, const PPCSubtarget &Subtarget)
getVectorCompareInfo - Given an intrinsic, return false if it is not a vector comparison.
static Instruction * callIntrinsic (IRBuilder<> &Builder, Intrinsic::ID Id)
static int getEstimateRefinementSteps (EVT VT, const PPCSubtarget &Subtarget)
static void getBaseWithConstantOffset (SDValue Loc, SDValue &Base, int64_t &Offset, SelectionDAG &DAG)
static bool isConsecutiveLSLoc (SDValue Loc, EVT VT, LSBaseSDNode *Base, unsigned Bytes, int Dist, SelectionDAG &DAG)
static bool isConsecutiveLS (SDNode *N, LSBaseSDNode *Base, unsigned Bytes, int Dist, SelectionDAG &DAG)
static bool findConsecutiveLoad (LoadSDNode *LD, SelectionDAG &DAG)
static SDValue generateEquivalentSub (SDNode *N, int Size, bool Complement, bool Swap, SDLoc &DL, SelectionDAG &DAG)
This function is called when we have proved that a SETCC node can be replaced by subtraction (and other supporting instructions) so that the result of comparison is kept in a GPR instead of CR.
static bool isFPExtLoad (SDValue Op)
static SDValue combineBVOfConsecutiveLoads (SDNode *N, SelectionDAG &DAG)
Reduce the number of loads when building a vector.
static SDValue addShuffleForVecExtend (SDNode *N, SelectionDAG &DAG, SDValue Input, uint64_t Elems, uint64_t CorrectElems)
static SDValue combineBVOfVecSExt (SDNode *N, SelectionDAG &DAG)
static SDValue stripModuloOnShift (const TargetLowering &TLI, SDNode *N, SelectionDAG &DAG)
static SDValue combineADDToADDZE (SDNode *N, SelectionDAG &DAG, const PPCSubtarget &Subtarget)
Variables
static cl::opt< bool > DisablePPCPreinc ("disable-ppc-preinc", cl::desc("disable preincrement load/store generation on PPC"), cl::Hidden)
static cl::opt< bool > DisableILPPref ("disable-ppc-ilp-pref", cl::desc("disable setting the node scheduling preference to ILP on PPC"), cl::Hidden)
static cl::opt< bool > DisablePPCUnaligned ("disable-ppc-unaligned", cl::desc("disable unaligned load/store generation on PPC"), cl::Hidden)
static cl::opt< bool > DisableSCO ("disable-ppc-sco", cl::desc("disable sibling call optimization on ppc"), cl::Hidden)
static cl::opt< bool > DisableInnermostLoopAlign32 ("disable-ppc-innermost-loop-align32", cl::desc("don't always align innermost loop to 32 bytes on ppc"), cl::Hidden)
static cl::opt< bool > EnableQuadPrecision ("enable-ppc-quad-precision", cl::desc("enable quad precision float support on ppc"), cl::Hidden)
static cl::opt< bool > UseAbsoluteJumpTables ("ppc-use-absolute-jumptables", cl::desc("use absolute jump tables on ppc"), cl::Hidden)
cl::opt< bool > ANDIGlueBug
static const MCPhysReg FPR []
FPR - The set of FP registers that should be allocated for arguments on Darwin and AIX.
static const MCPhysReg QFPR []
QFPR - The set of QPX registers that should be allocated for arguments.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-lowering"
Definition at line 104 of file PPCISelLowering.cpp.
Function Documentation
addShuffleForVecExtend()
static SDValue addShuffleForVecExtend (SDNode * N, SelectionDAG & DAG, SDValue Input, uint64_t Elems, uint64_t CorrectElems) static
Definition at line 13118 of file PPCISelLowering.cpp.
References llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::DataLayout::isLittleEndian(), and llvm::PPCISD::SExtVElems.
Referenced by combineBVOfVecSExt().
areCallingConvEligibleForTCO_64SVR4()
static bool areCallingConvEligibleForTCO_64SVR4 (CallingConv::ID CallerCC, CallingConv::ID CalleeCC) static
Definition at line 4663 of file PPCISelLowering.cpp.
References llvm::any_of(), llvm::CallingConv::C, callsShareTOCBase(), DisableSCO, llvm::CallingConv::Fast, llvm::ISD::InputArg::Flags, llvm::ISD::OutputArg::Flags, G, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetMachine::getRelocationModel(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetOptions::GuaranteedTailCallOpt, hasSameArgumentList(), llvm::ISD::ArgFlagsTy::isByVal(), isFunctionGlobalAddress(), needStackSlotPassParameters(), llvm::TargetMachine::Options, llvm::Reloc::PIC_, and llvm::SmallVectorBase::size().
Referenced by combineADDToADDZE().
buildCallOperands()
static void buildCallOperands (SmallVectorImpl< SDValue > & Ops, CallingConv::ID CallConv, const SDLoc & dl, bool isTailCall, bool isVarArg, bool isPatchPoint, bool hasNest, SelectionDAG & DAG, SmallVector< std::pair< unsigned, SDValue >, 8 > & RegsToPass, SDValue Glue, SDValue Chain, SDValue & Callee, int SPDiff, const PPCSubtarget & Subtarget, bool isIndirect) static
Definition at line 5345 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::CCState::AllocateStack(), llvm::ISD::ANY_EXTEND, Arg, llvm::array_lengthof(), assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_PAIR, llvm::CallingConv::C, CalculateStackSlotAlignment(), CalculateStackSlotSize(), CalculateStackSlotUsed(), CalculateTailCallArgDest(), CalculateTailCallSPDiff(), llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, llvm::CC_PPC32_SVR4(), llvm::CC_PPC32_SVR4_ByVal(), llvm::CC_PPC32_SVR4_VarArg(), llvm::TargetLowering::CallLoweringInfo::Chain, llvm::CallingConv::Cold, llvm::PPCISD::CR6SET, llvm::PPCISD::CR6UNSET, CreateCopyOfByValArgument(), llvm::TargetLowering::CallLoweringInfo::CS, llvm::TargetLowering::CallLoweringInfo::DAG, llvm::dbgs(), llvm::TargetLowering::CallLoweringInfo::DL, llvm::numbers::e, llvm::SmallVectorBase::empty(), EnsureStackAlignment(), llvm::errs(), llvm::ISD::EXTLOAD, llvm::PPCISD::EXTRACT_SPE, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::CallingConv::Fast, first, llvm::CCValAssign::Full, llvm::ISD::ArgFlagsTy::getByValSize(), getCallOpcode(), llvm::TargetRegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getDataLayout(), llvm::PPCSubtarget::getEnvironmentPointerRegister(), llvm::EVT::getEVTString(), llvm::SelectionDAG::getExtLoad(), llvm::MachineFunction::getFrameInfo(), llvm::PPCSubtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getName(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), getReg(), llvm::SelectionDAG::getRegister(), llvm::PPCSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::MachinePointerInfo::getStack(), llvm::SelectionDAG::getStackArgumentTokenFactor(), llvm::PPCSubtarget::getStackPointerRegister(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCSubtarget::getTOCPointerRegister(), llvm::PPCFrameLowering::getTOCSaveOffset(), llvm::CCValAssign::getValNo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::GPR, llvm::TargetOptions::GuaranteedTailCallOpt, llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::PPCSubtarget::is32BitELFABI(), llvm::PPCSubtarget::is64BitELFABI(), llvm::PPCSubtarget::isAIXABI(), isBLACompatibleAddress(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::MVT::isFloatingPoint(), isFunctionGlobalAddress(), llvm::ISD::ArgFlagsTy::isInConsecutiveRegs(), llvm::ISD::ArgFlagsTy::isInConsecutiveRegsLast(), isIndirectCall(), llvm::CCValAssign::isMemLoc(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isMustTailCall(), llvm::ISD::ArgFlagsTy::isNest(), llvm::TargetLowering::CallLoweringInfo::IsPatchPoint, llvm::PPCSubtarget::isPPC64(), llvm::CCValAssign::isRegLoc(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm::left_justify(), LLVM_DEBUG, LLVM_FALLTHROUGH, llvm_unreachable, llvm::MipsISD::Lo, llvm::SPII::Load, LowerMemOpCallTo(), llvm::makeArrayRef(), llvm::BitmaskEnumDetail::Mask(), llvm::max(), llvm::TargetMachine::Options, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, prepareDescriptorIndirectCall(), prepareIndirectCall(), PrepareTailCall(), llvm::SmallVectorTemplateBase< T >::push_back(), R4, R6, llvm::ISD::Register, llvm::report_fatal_error(), second, llvm::MachineFrameInfo::setHasTailCall(), setUsesTOCBasePtr(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::MVT::SimpleTy, Size, llvm::SmallVectorBase::size(), llvm::SPII::Store, std::swap(), llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetGlobalAddress, llvm::PPCISD::TC_RETURN, llvm::ISD::TokenFactor, transformCallee(), TRI, llvm::PPCSubtarget::usesFunctionDescriptors(), llvm::PPCTargetLowering::useSoftFloat(), llvm::MVT::v16i8, llvm::MVT::v1i128, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::NVPTX::PTXLdStInstCode::V4, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::ISD::ZERO_EXTEND.
BuildIntrinsicOp() [1/3]
static SDValue BuildIntrinsicOp (unsigned IID, SDValue Op, SelectionDAG & DAG, const SDLoc & dl, EVT DestVT = MVT::Other) static
BuildIntrinsicOp - Return a unary operator intrinsic node with the specified intrinsic ID.
Definition at line 8471 of file PPCISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, and llvm::MVT::Other.
Referenced by getNormalLoadInput(), getVectorCompareInfo(), and llvm::PPCTargetLowering::PerformDAGCombine().
BuildIntrinsicOp() [2/3]
static SDValue BuildIntrinsicOp (unsigned IID, SDValue LHS, SDValue RHS, SelectionDAG & DAG, const SDLoc & dl, EVT DestVT = MVT::Other) static
BuildIntrinsicOp - Return a binary operator intrinsic node with the specified intrinsic ID.
Definition at line 8480 of file PPCISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, and llvm::MVT::Other.
BuildIntrinsicOp() [3/3]
static SDValue BuildIntrinsicOp (unsigned IID, SDValue Op0, SDValue Op1, SDValue Op2, SelectionDAG & DAG, const SDLoc & dl, EVT DestVT = MVT::Other) static
BuildIntrinsicOp - Return a ternary operator intrinsic node with the specified intrinsic ID.
Definition at line 8490 of file PPCISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::ISD::INTRINSIC_WO_CHAIN, and llvm::MVT::Other.
BuildSplatI()
static SDValue BuildSplatI (int Val, unsigned SplatSize, EVT VT, SelectionDAG & DAG, const SDLoc & dl) static
BuildSplatI - Build a canonical splati of Val with an element size of SplatSize.
Cast the result to VT.
Definition at line 8451 of file PPCISelLowering.cpp.
References llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::MVT::Other, llvm::MVT::v16i8, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by getNormalLoadInput(), and getVectorCompareInfo().
BuildVSLDOI()
static SDValue BuildVSLDOI (SDValue LHS, SDValue RHS, unsigned Amt, EVT VT, SelectionDAG & DAG, const SDLoc & dl) static
BuildVSLDOI - Return a VECTOR_SHUFFLE that is a vsldoi of the specified amount.
The result has the specified value type.
Definition at line 8500 of file PPCISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getVectorShuffle(), and llvm::MVT::v16i8.
Referenced by GeneratePerfectShuffle(), and getNormalLoadInput().
CalculateStackSlotAlignment()
static unsigned CalculateStackSlotAlignment (EVT ArgVT, EVT OrigVT, ISD::ArgFlagsTy Flags, unsigned PtrByteSize) static
CalculateStackSlotAlignment - Calculates the alignment of this argument on the stack.
Definition at line 3343 of file PPCISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::MVT::f128, llvm::ISD::ArgFlagsTy::getByValAlign(), llvm::EVT::getStoreSize(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::ISD::ArgFlagsTy::isInConsecutiveRegs(), llvm::ISD::ArgFlagsTy::isSplit(), llvm_unreachable, llvm::MVT::ppcf128, llvm::MVT::v16i8, llvm::MVT::v1i128, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by buildCallOperands(), CalculateStackSlotUsed(), and EnsureStackAlignment().
CalculateStackSlotSize()
static unsigned CalculateStackSlotSize (EVT ArgVT, ISD::ArgFlagsTy Flags, unsigned PtrByteSize) static
CalculateStackSlotSize - Calculates the size reserved for this argument on the stack.
Definition at line 3327 of file PPCISelLowering.cpp.
References llvm::ISD::ArgFlagsTy::getByValSize(), llvm::EVT::getStoreSize(), llvm::ISD::ArgFlagsTy::isByVal(), and llvm::ISD::ArgFlagsTy::isInConsecutiveRegs().
Referenced by buildCallOperands(), CalculateStackSlotUsed(), and EnsureStackAlignment().
CalculateStackSlotUsed()
static bool CalculateStackSlotUsed (EVT ArgVT, EVT OrigVT, ISD::ArgFlagsTy Flags, unsigned PtrByteSize, unsigned LinkageSize, unsigned ParamAreaSize, unsigned & ArgOffset, unsigned & AvailableFPRs, unsigned & AvailableVRs, bool HasQPX) static
CalculateStackSlotUsed - Return whether this argument will use its stack slot (instead of being passed in registers).
ArgOffset, AvailableFPRs, and AvailableVRs must hold the current argument position, and will be updated to account for this argument.
Definition at line 3389 of file PPCISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, CalculateStackSlotAlignment(), CalculateStackSlotSize(), llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::ArgFlagsTy::isByVal(), llvm::ISD::ArgFlagsTy::isInConsecutiveRegsLast(), llvm::MVT::v16i8, llvm::MVT::v1i128, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by buildCallOperands(), EnsureStackAlignment(), and needStackSlotPassParameters().
CalculateTailCallArgDest()
static void CalculateTailCallArgDest (SelectionDAG & DAG, MachineFunction & MF, bool isPPC64, SDValue Arg, int SPDiff, unsigned ArgOffset, SmallVectorImpl< TailCallArgumentInfo > & TailCallArguments) static
CalculateTailCallArgDest - Remember Argument for later processing.
Calculate the position of the argument.
Definition at line 4880 of file PPCISelLowering.cpp.
References Arg, llvm::MachineFrameInfo::CreateFixedObject(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SDValue::getNode(), llvm::SDValue::getValueSizeInBits(), llvm::MVT::i32, llvm::MVT::i64, Info, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by buildCallOperands(), and LowerMemOpCallTo().
CalculateTailCallSPDiff()
static int CalculateTailCallSPDiff (SelectionDAG & DAG, bool isTailCall, unsigned ParamSize) static
CalculateTailCallSPDiff - Get the amount the stack pointer has to be adjusted to accommodate the arguments for the tailcall.
Definition at line 4515 of file PPCISelLowering.cpp.
References Callee, llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::PPCFunctionInfo::getMinReservedArea(), isFunctionGlobalAddress(), and llvm::PPCFunctionInfo::setTailCallSPDelta().
Referenced by buildCallOperands().
callIntrinsic()
static Instruction* callIntrinsic (IRBuilder<> & Builder, Intrinsic::ID Id) static
Definition at line 10580 of file PPCISelLowering.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::GetInsertBlock(), llvm::BasicBlock::getParent(), and llvm::GlobalValue::getParent().
Referenced by llvm::PPCTargetLowering::emitLeadingFence(), and llvm::PPCTargetLowering::emitTrailingFence().
callsShareTOCBase()
static bool callsShareTOCBase (const Function * Caller, SDValue Callee, const TargetMachine & TM) static
Definition at line 4533 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), F(), G, llvm::TargetMachine::getCodeModel(), llvm::TargetMachine::getFunctionSections(), llvm::GlobalAddressSDNode::getGlobal(), llvm::GlobalValue::getParent(), llvm::GlobalObject::getSection(), llvm::GlobalValue::getSection(), llvm::Function::getSectionPrefix(), llvm::GlobalObject::hasComdat(), llvm::GlobalValue::hasComdat(), llvm::GlobalValue::isStrongDefinitionForLinker(), llvm::CodeModel::Large, llvm::CodeModel::Medium, and llvm::TargetMachine::shouldAssumeDSOLocal().
Referenced by areCallingConvEligibleForTCO_64SVR4(), and getCallOpcode().
CC_AIX()
static bool CC_AIX (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State) static
Definition at line 6861 of file PPCISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateStack(), assert(), llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::getCustomReg(), llvm::CCState::getMachineFunction(), llvm::CCValAssign::getReg(), llvm::MVT::getSizeInBits(), llvm::MVT::getStoreSize(), llvm::MachineFunction::getSubtarget(), I, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::ArgFlagsTy::isByVal(), llvm::ISD::ArgFlagsTy::isNest(), llvm::PPCSubtarget::isPPC64(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::CCState::isVarArg(), llvm::MVT::isVector(), LLVM_FALLTHROUGH, R4, R6, Reg, llvm::report_fatal_error(), and llvm::MVT::SimpleTy.
Referenced by truncateScalarIntegerArg().
combineADDToADDZE()
static SDValue combineADDToADDZE (SDNode * N, SelectionDAG & DAG, const PPCSubtarget & Subtarget) static
Definition at line 15511 of file PPCISelLowering.cpp.
References llvm::ISD::ABS, llvm::APInt::abs(), llvm::MCID::Add, llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, areCallingConvEligibleForTCO_64SVR4(), assert(), llvm::MCID::Bitcast, llvm::ISD::BITCAST, llvm::PPC::DIR_PWR8, llvm::PPC::DIR_PWR9, llvm::PPC::DIR_PWR_FUTURE, DisableSCO, llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::ConstantSDNode::getAPIntValue(), llvm::CallBase::getCalledFunction(), llvm::Function::getCallingConv(), llvm::CallBase::getCallingConv(), llvm::SelectionDAG::getConstant(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::User::getOperand(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::Function::hasMinSize(), llvm::SDValue::hasOneUse(), llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, llvm::isConstOrConstSplat(), llvm::isInt< 16 >(), llvm::APInt::isNegative(), llvm::TargetLoweringBase::isOperationLegal(), llvm::PPCSubtarget::isPPC64(), llvm::CallInst::isTailCall(), llvm::isUInt< 16 >(), llvm::Function::isVarArg(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::MUL, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SHL, llvm::TargetMachine::shouldAssumeDSOLocal(), llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::SUBC, std::swap(), llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::PPCISD::VABSD, llvm::ISD::VSELECT, llvm::Z, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
combineBVOfConsecutiveLoads()
static SDValue combineBVOfConsecutiveLoads (SDNode * N, SelectionDAG & DAG) static
Reduce the number of loads when building a vector.
Building a vector out of multiple loads can be converted to a load of the vector type if the loads are consecutive. If the loads are consecutive but in descending order, a shuffle is added at the end to reorder the vector.
Definition at line 13028 of file PPCISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::dyn_cast(), llvm::numbers::e, llvm::ISD::EXTLOAD, llvm::ISD::FP_ROUND, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getLoad(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getScalarType(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::isByteSized(), isConsecutiveLS(), llvm::ARM_MB::LD, llvm::MipsISD::LDL, llvm::SPII::Load, llvm::ISD::LOAD, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by combineBVOfVecSExt().
combineBVOfVecSExt()
static SDValue combineBVOfVecSExt (SDNode * N, SelectionDAG & DAG) static
Definition at line 13152 of file PPCISelLowering.cpp.
References addShuffleForVecExtend(), llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::BUILD_VECTOR, combineBVOfConsecutiveLoads(), llvm::dyn_cast(), llvm::MipsISD::Ext, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::PPCISD::FCFID, llvm::PPCISD::FCFIDS, llvm::PPCISD::FCFIDU, llvm::PPCISD::FCFIDUS, llvm::PPCISD::FCTIDUZ, llvm::PPCISD::FCTIDZ, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSimpleVT(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::DataLayout::isLittleEndian(), llvm::ISD::LOAD, llvm::PPCISD::LXSIZX, llvm::PPCISD::MFVSR, llvm::MVT::Other, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, Signed, llvm::ISD::SINT_TO_FP, llvm::PPCISD::SINT_VEC_TO_FP, llvm::ISD::UINT_TO_FP, llvm::PPCISD::UINT_VEC_TO_FP, llvm::PPCTargetLowering::useSoftFloat(), llvm::MVT::v2f64, llvm::MVT::v4i32, and llvm::PPCISD::VEXTS.
CreateCopyOfByValArgument()
static SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG & DAG, const SDLoc & dl) static
CreateCopyOfByValArgument - Make a copy of an aggregate at address specified by "Src" to address "Dst" of size "Size".
Alignment information is specified by the specific parameter attribute. The copy will be passed as a byval function parameter. Sometimes what we are copying is the end of a larger object, the part that does not fit in registers.
Definition at line 4925 of file PPCISelLowering.cpp.
References llvm::ISD::ArgFlagsTy::getByValAlign(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMemcpy(), and llvm::MVT::i32.
Referenced by buildCallOperands().
EmitTailCallStoreFPAndRetAddr()
static SDValue EmitTailCallStoreFPAndRetAddr (SelectionDAG & DAG, SDValue Chain, SDValue OldRetAddr, SDValue OldFP, int SPDiff, const SDLoc & dl) static
EmitTailCallStoreFPAndRetAddr - Move the frame pointer and return address to the appropriate stack slot for the tail call optimized function call.
Definition at line 4844 of file PPCISelLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::PPCSubtarget::getFrameLowering(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getStore(), llvm::MachineFunction::getSubtarget(), llvm::MVT::i32, llvm::MVT::i64, llvm::PPCSubtarget::isDarwinABI(), and llvm::PPCSubtarget::isPPC64().
Referenced by PrepareTailCall().
EnsureStackAlignment()
static unsigned EnsureStackAlignment (const PPCFrameLowering * Lowering, unsigned NumBytes) static
EnsureStackAlignment - Round stack frame size up from NumBytes to ensure minimum alignment required for target.
Definition at line 3444 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::PPCFunctionInfo::addLiveInAttr(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::CCState::AllocateStack(), Arg, llvm::Function::arg_begin(), llvm::array_lengthof(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::PPCISD::BUILD_SPE64, CalculateStackSlotAlignment(), CalculateStackSlotSize(), CalculateStackSlotUsed(), llvm::CC_PPC32_SVR4(), llvm::CC_PPC32_SVR4_ByVal(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateStackObject(), llvm::Depth, llvm::numbers::e, llvm::SmallVectorBase::empty(), llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::CallingConv::Fast, llvm::ISD::ArgFlagsTy::getByValSize(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::MachineFunction::getDataLayout(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::PPCSubtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::PPCFrameLowering::getLinkageSize(), llvm::MachineRegisterInfo::getLiveInVirtReg(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineFunction::getRegInfo(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::getSizeInBits(), llvm::TargetFrameLowering::getStackAlignment(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SelectionDAG::getTruncStore(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::PPCFunctionInfo::getVarArgsFrameIndex(), llvm::GPR, llvm::TargetOptions::GuaranteedTailCallOpt, llvm::PPCSubtarget::hasP8Vector(), llvm::PPCSubtarget::hasQPX(), llvm::PPCSubtarget::hasSPE(), llvm::PPCTargetLowering::hasSPE(), llvm::PPCSubtarget::hasVSX(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MipsISD::Ins, llvm::PPCSubtarget::is32BitELFABI(), llvm::PPCSubtarget::is64BitELFABI(), llvm::PPCSubtarget::isAIXABI(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::PPCSubtarget::isELFv2ABI(), llvm::ISD::ArgFlagsTy::isInConsecutiveRegs(), llvm::ISD::ArgFlagsTy::isInConsecutiveRegsLast(), llvm::PPCSubtarget::isLittleEndian(), llvm::CCValAssign::isMemLoc(), llvm::ISD::ArgFlagsTy::isNest(), llvm::CCValAssign::isRegLoc(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::ISD::ArgFlagsTy::isZExt(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::max(), llvm::TargetMachine::Options, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), R4, R6, Reg, llvm::PPCFunctionInfo::setMinReservedArea(), llvm::PPCFunctionInfo::setVarArgsFrameIndex(), llvm::PPCFunctionInfo::setVarArgsNumFPR(), llvm::PPCFunctionInfo::setVarArgsNumGPR(), llvm::PPCFunctionInfo::setVarArgsStackOffset(), llvm::MVT::SimpleTy, llvm::SmallVectorBase::size(), llvm::ISD::SRL, llvm::SPII::Store, std::swap(), llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::PPCTargetLowering::useSoftFloat(), llvm::MVT::v16i8, llvm::MVT::v1i128, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::NVPTX::PTXLdStInstCode::V4, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by buildCallOperands(), and truncateScalarIntegerArg().
findConsecutiveLoad()
static bool findConsecutiveLoad (LoadSDNode * LD, SelectionDAG & DAG) static
Definition at line 12190 of file PPCISelLowering.cpp.
References llvm::SmallSet< T, N, C >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallSet< T, N, C >::end(), llvm::MemSDNode::getChain(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::EVT::getStoreSize(), I, llvm::ARM_PROC::IE, llvm::SmallSet< T, N, C >::insert(), llvm::SmallVectorImpl< T >::insert(), isConsecutiveLS(), llvm::RISCVFenceField::O, llvm::SDNode::ops(), llvm::ISD::TokenFactor, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by llvm::PPCTargetLowering::PerformDAGCombine().
fixupFuncForFI()
static void fixupFuncForFI (SelectionDAG & DAG, int FrameIdx, EVT VT) static
Definition at line 2374 of file PPCISelLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MVT::i64, and llvm::PPCFunctionInfo::setHasNonRISpills().
Referenced by llvm::PPCTargetLowering::SelectAddressRegImm().
generateEquivalentSub()
static SDValue generateEquivalentSub (SDNode * N, int Size, bool Complement, bool Swap, SDLoc & DL, SelectionDAG & DAG) static
This function is called when we have proved that a SETCC node can be replaced by subtraction (and other supporting instructions) so that the result of comparison is kept in a GPR instead of CR.
This function is purely for codegen purposes and has some flags to guide the codegen process.
Definition at line 12257 of file PPCISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::SmallVectorTemplateCommon< T >::back(), C, llvm::APInt::clearBit(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::count(), llvm::SmallVectorBase::empty(), llvm::sys::path::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDNode::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::isNullConstant(), llvm::ISD::isSignedIntSetCC(), llvm::ISD::isUnsignedIntSetCC(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::KnownBits::One, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), second, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, Size, llvm::SmallVectorBase::size(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, std::swap(), llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::ISD::XOR, llvm::KnownBits::Zero, and llvm::ISD::ZERO_EXTEND.
GeneratePerfectShuffle()
static SDValue GeneratePerfectShuffle (unsigned PFEntry, SDValue LHS, SDValue RHS, SelectionDAG & DAG, const SDLoc & dl) static
GeneratePerfectShuffle - Given an entry in the perfect-shuffle table, emit the specified operations to build the shuffle.
Definition at line 8908 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, llvm::ISD::BSWAP, BuildVSLDOI(), llvm::numbers::e, llvm::LoadSDNode::getBasePtr(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getIntPtrConstant(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), getNormalLoadInput(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getSizeInBits(), llvm::PPC::getSplatIdxForPPCMnemonics(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, isNByteElemShuffleMask(), llvm::PPC::isQVALIGNIShuffleMask(), llvm::ShuffleVectorSDNode::isSplat(), llvm::PPC::isSplatShuffleMask(), llvm::SDValue::isUndef(), llvm::PPC::isVMRGEOShuffleMask(), llvm::PPC::isVMRGHShuffleMask(), llvm::PPC::isVMRGLShuffleMask(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), llvm::PPC::isVSLDOIShuffleMask(), llvm::PPC::isXXBRDShuffleMask(), llvm::PPC::isXXBRHShuffleMask(), llvm::PPC::isXXBRQShuffleMask(), llvm::PPC::isXXBRWShuffleMask(), llvm::PPC::isXXINSERTWMask(), llvm::PPC::isXXPERMDIShuffleMask(), llvm::PPC::isXXSLDWIShuffleMask(), llvm::ARM_MB::LD, llvm::PPCISD::LD_SPLAT, llvm_unreachable, llvm::BitmaskEnumDetail::Mask(), N, OP_COPY, llvm::MVT::Other, PerfectShuffleTable, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PPCISD::QVALIGNI, llvm::PPCISD::QVESPLATI, llvm::PPCISD::QVFPERM, llvm::PPCISD::QVGPCI, std::swap(), llvm::PPCISD::SWAP_NO_CHAIN, llvm::MVT::v16i8, llvm::MVT::v1i128, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::PPCISD::VECINSERT, llvm::PPCISD::VECSHL, llvm::PPCISD::VPERM, llvm::PPCISD::XXPERMDI, and llvm::PPCISD::XXSPLT.
getBaseWithConstantOffset()
static void getBaseWithConstantOffset (SDValue Loc, SDValue & Base, int64_t & Offset, SelectionDAG & DAG) static
Definition at line 12025 of file PPCISelLowering.cpp.
References llvm::SDValue::getOperand(), and llvm::SelectionDAG::isBaseWithConstantOffset().
Referenced by isConsecutiveLSLoc().
getCallOpcode()
static unsigned getCallOpcode (bool isIndirectCall, bool isPatchPoint, bool isTailCall, const Function & Caller, const SDValue & Callee, const PPCSubtarget & Subtarget, const TargetMachine & TM) static
Definition at line 5082 of file PPCISelLowering.cpp.
References llvm::PPCISD::BCTRL, llvm::PPCISD::BCTRL_LOAD_TOC, llvm::PPCISD::CALL, llvm::PPCISD::CALL_NOP, callsShareTOCBase(), llvm::PPCSubtarget::is64BitELFABI(), llvm::PPCSubtarget::isAIXABI(), and llvm::PPCISD::TC_RETURN.
Referenced by buildCallOperands().
getEstimateRefinementSteps()
static int getEstimateRefinementSteps (EVT VT, const PPCSubtarget & Subtarget) static
Definition at line 11950 of file PPCISelLowering.cpp.
References llvm::PPC::DIR_440, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500, llvm::PPC::DIR_E500mc, llvm::PPC::DIR_E5500, llvm::TargetLoweringBase::Enabled, llvm::MVT::f32, llvm::MVT::f64, llvm::PPCISD::FRE, llvm::PPCISD::FRSQRTE, llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::PPCSubtarget::hasRecipPrec(), llvm::MVT::v2f64, llvm::MVT::v4f32, and llvm::MVT::v4f64.
getLabelAccessInfo()
static void getLabelAccessInfo (bool IsPIC, const PPCSubtarget & Subtarget, unsigned & HiOpFlags, unsigned & LoOpFlags, const GlobalValue * GV = nullptr) static
Return true if we should reference labels using a PICBase, set the HiOpFlags and LoOpFlags to the target MO flags.
Definition at line 2679 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::hasLazyResolverStub(), llvm::PPCII::MO_HA, llvm::PPCII::MO_LO, llvm::PPCII::MO_NLP_FLAG, llvm::PPCII::MO_NLP_HIDDEN_FLAG, and llvm::PPCII::MO_PIC_FLAG.
Referenced by llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), and setUsesTOCBasePtr().
getMaxByValAlign()
static void getMaxByValAlign (Type * Ty, unsigned & MaxAlign, unsigned MaxMaxAlign) static
getMaxByValAlign - Helper for getByValTypeAlignment to determine the desired ByVal argument alignment.
Definition at line 1287 of file PPCISelLowering.cpp.
Referenced by llvm::PPCTargetLowering::getByValTypeAlignment().
getNormalLoadInput()
static const SDValue* getNormalLoadInput (const SDValue & Op) static
Definition at line 8583 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ANY_EXTEND, llvm::array_lengthof(), assert(), llvm::ISD::BITCAST, BuildIntrinsicOp(), BuildSplatI(), BuildVSLDOI(), llvm::HexagonISD::CP, llvm::MachineFrameInfo::CreateStackObject(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::ConstantFP::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getFixedStack(), llvm::Type::getFloatTy(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTruncStore(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MachinePointerInfo::getWithOffset(), llvm::APInt::getZExtValue(), haveEfficientBuildVectorPattern(), llvm::MVT::i32, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsConst, llvm::BuildVectorSDNode::isConstantSplat(), llvm::ISD::isNormalLoad(), llvm::isNullConstant(), llvm::SelectionDAG::isSplatValue(), llvm::SDValue::isUndef(), llvm::ARM_MB::LD, llvm::PPCISD::LD_SPLAT, llvm::ISD::LOAD, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PPCISD::QVLFSb, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SETEQ, llvm::ISD::TokenFactor, llvm::MVT::v16i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::PPCISD::VADD_SPLAT, llvm::ISD::XOR, and llvm::Z.
Referenced by GeneratePerfectShuffle().
getOutputChainFromCallSeq()
static SDValue getOutputChainFromCallSeq (SDValue CallSeqStart) static
Definition at line 5225 of file PPCISelLowering.cpp.
References assert(), llvm::ISD::CALLSEQ_START, llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDValue::getValue(), and llvm::MVT::Glue.
Referenced by prepareDescriptorIndirectCall().
getRegClassForSVT()
static const TargetRegisterClass* getRegClassForSVT (MVT::SimpleValueType SVT, bool IsPPC64) static
Definition at line 6950 of file PPCISelLowering.cpp.
References assert(), llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, and llvm::report_fatal_error().
Referenced by truncateScalarIntegerArg().
getVectorCompareInfo()
static bool getVectorCompareInfo (SDValue Intrin, int & CompareOpc, bool & isDot, const PPCSubtarget & Subtarget) static
getVectorCompareInfo - Given an intrinsic, return false if it is not a vector comparison.
If it is, return true and fill in Opc/isDot with information about the intrinsic.
Definition at line 9516 of file PPCISelLowering.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::ATOMIC_CMP_SWAP, llvm::PPCISD::ATOMIC_CMP_SWAP_16, llvm::PPCISD::ATOMIC_CMP_SWAP_8, llvm::ISD::BITCAST, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, BuildIntrinsicOp(), BuildSplatI(), C, llvm::MachineFrameInfo::CreateStackObject(), llvm::dyn_cast(), llvm::numbers::e, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FP_EXTEND, llvm::PPCISD::FP_EXTEND_HALF, llvm::ISD::FSUB, llvm::MemSDNode::getAAInfo(), llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::SelectionDAG::getBuildVector(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineMemOperand::getFlags(), llvm::SDNode::getFlags(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::LoadSDNode::getOffset(), llvm::StoreSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTruncStore(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), llvm::MachinePointerInfo::getWithOffset(), llvm::MVT::Glue, llvm::PPCSubtarget::hasP8Altivec(), llvm::PPCSubtarget::hasP9Altivec(), llvm::PPCSubtarget::hasVSX(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::tgtok::IntVal, llvm::LSBaseSDNode::isIndexed(), llvm::LSBaseSDNode::isUnindexed(), llvm::ARM_MB::LD, llvm::PPCISD::LD_VSX_LH, llvm_unreachable, llvm::SPII::Load, llvm::ISD::LOAD, llvm::SelectionDAG::MaskedValueIsZero(), llvm::PPCISD::MFOCRF, llvm::MinAlign(), llvm::PPCISD::MTVSRZ, llvm::MVT::Other, llvm::ISD::PRE_INC, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PPCISD::QBFLT, R2, llvm::ISD::SDIV, llvm::ISD::SREM, llvm::ISD::SRL, llvm::SPII::Store, llvm::ISD::SUB, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UREM, llvm::SDNode::uses(), llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::PPCISD::VCMP, llvm::PPCISD::VCMPo, llvm::PPCISD::VECINSERT, X, llvm::ISD::XOR, and Y.
hasSameArgumentList()
static bool hasSameArgumentList (const Function * CallerFn, ImmutableCallSite CS) static
Definition at line 4632 of file PPCISelLowering.cpp.
References llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_begin(), llvm::Function::arg_begin(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_end(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_size(), llvm::Function::arg_size(), and llvm::Value::getType().
Referenced by areCallingConvEligibleForTCO_64SVR4().
haveEfficientBuildVectorPattern()
static bool haveEfficientBuildVectorPattern (BuildVectorSDNode * V, bool HasDirectMove, bool HasP8Vector) static
Do we have an efficient pattern in a .td file for this node?
Parameters
V - pointer to the BuildVectorSDNode being matched
HasDirectMove - does this subtarget have VSR <-> GPR direct moves?
There are some patterns where it is beneficial to keep a BUILD_VECTOR node as a BUILD_VECTOR node rather than expanding it. The patterns where the opposite is true (expansion is beneficial) are:
The node builds a vector out of integers that are not 32 or 64-bits
The node builds a vector out of constants
The node is a "load-and-splat" In all other cases, we will choose to keep the BUILD_VECTOR.
Definition at line 8525 of file PPCISelLowering.cpp.
References llvm::PPCISD::BUILD_FP128, llvm::ISD::BUILD_PAIR, llvm::numbers::e, EnableQuadPrecision, llvm::MVT::f128, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::i64, llvm::BuildVectorSDNode::isConstant(), llvm::SDNode::isOnlyUserOf(), llvm::SDValue::isUndef(), llvm::ISD::LOAD, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by getNormalLoadInput().
isBLACompatibleAddress()
static SDNode* isBLACompatibleAddress (SDValue Op, SelectionDAG & DAG) static
isCallCompatibleAddress - Return the immediate to use if the specified 32-bit value is representable in the immediate field of a BxA instruction.
Definition at line 4798 of file PPCISelLowering.cpp.
References Arg, C, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), and llvm::ConstantSDNode::getZExtValue().
Referenced by buildCallOperands(), isIndirectCall(), and transformCallee().
isConsecutiveLS()
static bool isConsecutiveLS (SDNode * N, LSBaseSDNode * Base, unsigned Bytes, int Dist, SelectionDAG & DAG) static
Definition at line 12077 of file PPCISelLowering.cpp.
References llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, isConsecutiveLSLoc(), llvm::AArch64CC::LS, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, and llvm::MVT::v4i32.
Referenced by combineBVOfConsecutiveLoads(), and findConsecutiveLoad().
isConsecutiveLSLoc()
static bool isConsecutiveLSLoc (SDValue Loc, EVT VT, LSBaseSDNode * Base, unsigned Bytes, int Dist, SelectionDAG & DAG) static
Definition at line 12037 of file PPCISelLowering.cpp.
References llvm::AMDGPUISD::BFI, llvm::ISD::FrameIndex, llvm::X86AS::FS, llvm::MemSDNode::getBasePtr(), getBaseWithConstantOffset(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::SDValue::getOpcode(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), and llvm::TargetLowering::isGAPlusOffset().
Referenced by isConsecutiveLS().
isConstantOrUndef()
static bool isConstantOrUndef (int Op, int Val) static
isConstantOrUndef - Op is either an undef node or a ConstantSDNode.
Return true if Op is undef or if it matches the specified value.
Definition at line 1500 of file PPCISelLowering.cpp.
Referenced by llvm::PPC::isQVALIGNIShuffleMask(), isVMerge(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), and llvm::PPC::isVSLDOIShuffleMask().
isFloatingPointZero()
static bool isFloatingPointZero (SDValue Op) static
isFloatingPointZero - Return true if this is 0.0 or -0.0.
Definition at line 1486 of file PPCISelLowering.cpp.
References llvm::HexagonISD::CP, llvm::SDValue::getNode(), llvm::SDValue::getOperand(), llvm::ISD::isEXTLoad(), and llvm::ISD::isNON_EXTLoad().
Referenced by truncateScalarIntegerArg().
isFPExtLoad()
static bool isFPExtLoad (SDValue Op) static
Definition at line 12927 of file PPCISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::numbers::e, llvm::ISD::EXTLOAD, llvm::MVT::f32, llvm::MVT::f64, llvm::PPCISD::FCTIDUZ, llvm::PPCISD::FCTIDZ, llvm::PPCISD::FCTIWUZ, llvm::PPCISD::FCTIWZ, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::tgtok::In, llvm::SDValue::isUndef(), llvm::ARM_MB::LD, llvm::PPCISD::MFVSR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MVT::v2f64, llvm::MVT::v2i64, and llvm::MVT::v4f32.
isFunctionGlobalAddress()
static bool isFunctionGlobalAddress (SDValue Callee) static
Definition at line 4985 of file PPCISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::CCState::AnalyzeCallResult(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::PPCISD::BUILD_SPE64, llvm::CallingConv::Cold, llvm::numbers::e, llvm::MVT::f64, llvm::CCValAssign::Full, G, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getValue(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::ISD::GlobalTLSAddress, llvm::MipsISD::Hi, llvm::MVT::i32, llvm::CCValAssign::isRegLoc(), llvm_unreachable, llvm::MipsISD::Lo, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::RetCC_PPC(), llvm::RetCC_PPC_Cold(), llvm::CCValAssign::SExt, llvm::SmallVectorBase::size(), std::swap(), llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TRUNCATE, and llvm::CCValAssign::ZExt.
Referenced by areCallingConvEligibleForTCO_64SVR4(), buildCallOperands(), CalculateTailCallSPDiff(), isIndirectCall(), transformCallee(), and truncateScalarIntegerArg().
isIndirectCall()
static bool isIndirectCall (const SDValue & Callee, SelectionDAG & DAG, const PPCSubtarget & Subtarget, bool isPatchPoint) static
Definition at line 5061 of file PPCISelLowering.cpp.
References isBLACompatibleAddress(), llvm::PPCSubtarget::isELFv2ABI(), isFunctionGlobalAddress(), and llvm::PPCSubtarget::usesFunctionDescriptors().
Referenced by buildCallOperands(), llvm::CallBase::getCalledFunction(), and llvm::NVPTXTargetLowering::LowerCall().
isNByteElemShuffleMask()
static bool isNByteElemShuffleMask (ShuffleVectorSDNode * N, unsigned Width, int StepLen) static
Check that the mask is shuffling N byte elements.
Within each N byte element of the mask, the indices could be either in increasing or decreasing order as long as they are consecutive.
Parameters
[in] N the shuffle vector SD Node to analyze
[in] Width the element width in bytes, could be 2/4/8/16 (HalfWord/ Word/DoubleWord/QuadWord).
[in] StepLen the delta indices number among the N byte element, if the mask is in increasing/decreasing order then it is 1/-1.
Returns
true iff the mask is shuffling N byte elements.
Definition at line 1875 of file PPCISelLowering.cpp.
References assert(), and llvm::ShuffleVectorSDNode::getMaskElt().
Referenced by GeneratePerfectShuffle(), isXXBRShuffleMaskHelper(), llvm::PPC::isXXINSERTWMask(), llvm::PPC::isXXPERMDIShuffleMask(), and llvm::PPC::isXXSLDWIShuffleMask().
isValidAIXExternalSymSDNode()
static bool isValidAIXExternalSymSDNode (StringRef SymName) static
Definition at line 5121 of file PPCISelLowering.cpp.
References llvm::StringSwitch< T, R >::Cases(), and llvm::StringSwitch< T, R >::Default().
Referenced by transformCallee().
isVMerge() [1/2]
static bool isVMerge (ShuffleVectorSDNode * N, unsigned UnitSize, unsigned LHSStart, unsigned RHSStart) static
isVMerge - Common function, used to match vmrg* shuffles.
Definition at line 1622 of file PPCISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getValueType(), isConstantOrUndef(), and llvm::MVT::v16i8.
Referenced by llvm::PPC::isVMRGEOShuffleMask(), llvm::PPC::isVMRGHShuffleMask(), and llvm::PPC::isVMRGLShuffleMask().
isVMerge() [2/2]
static bool isVMerge (ShuffleVectorSDNode * N, unsigned IndexOffset, unsigned RHSStartValue) static
Common function used to match vmrgew and vmrgow shuffles.
The indexOffset determines whether to look for even or odd words in the shuffle mask. This is based on the of the endianness of the target machine.
Little Endian:
Use offset of 0 to check for odd elements
Use offset of 4 to check for even elements
Big Endian:
Use offset of 0 to check for even elements
Use offset of 4 to check for odd elements A detailed description of the vector element ordering for little endian and big endian can be found at http://www.ibm.com/developerworks/library/l-ibm-xl-c-cpp-compiler/index.html Targeting your applications - what little endian and big endian IBM XL C/C++ compiler differences mean to you
The mask to the shuffle vector instruction specifies the indices of the elements from the two input vectors to place in the result. The elements are numbered in array-access order, starting with the first vector. These vectors are always of type v16i8, thus each vector will contain 16 elements of size
More info on the shuffle vector can be found in the http://llvm.org/docs/LangRef.html#shufflevector-instruction Language Reference.
The RHSStartValue indicates whether the same input vectors are used (unary) or two different input vectors are used, based on the following:
If the instruction uses the same vector for both inputs, the range of the indices will be 0 to 15. In this case, the RHSStart value passed should be 0.
If the instruction has two different vectors then the range of the indices will be 0 to 31. In this case, the RHSStart value passed should be 16 (indices 0-15 specify elements in the first vector while indices 16 to 31 specify elements in the second vector).
Parameters
[in] N The shuffle vector SD Node to analyze
[in] IndexOffset Specifies whether to look for even or odd elements
[in] RHSStartValue Specifies the starting index for the righthand input vector to the shuffle_vector instruction
Returns
true iff this shuffle vector represents an even or odd word merge
Definition at line 1732 of file PPCISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getValueType(), isConstantOrUndef(), and llvm::MVT::v16i8.
isXXBRShuffleMaskHelper()
static bool isXXBRShuffleMaskHelper (ShuffleVectorSDNode * N, int Width) static
Definition at line 2039 of file PPCISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getValueType(), isNByteElemShuffleMask(), and llvm::MVT::v16i8.
Referenced by llvm::PPC::isXXBRDShuffleMask(), llvm::PPC::isXXBRHShuffleMask(), llvm::PPC::isXXBRQShuffleMask(), and llvm::PPC::isXXBRWShuffleMask().
LowerLabelRef()
static SDValue LowerLabelRef (SDValue HiPart, SDValue LoPart, bool isPIC, SelectionDAG & DAG) static
Definition at line 2704 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::PPCISD::GlobalBaseReg, llvm::MipsISD::Hi, llvm::PPCISD::Hi, llvm::MipsISD::Lo, and llvm::PPCISD::Lo.
Referenced by llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), and setUsesTOCBasePtr().
LowerMemOpCallTo()
static void LowerMemOpCallTo (SelectionDAG & DAG, MachineFunction & MF, SDValue Chain, SDValue Arg, SDValue PtrOff, int SPDiff, unsigned ArgOffset, bool isPPC64, bool isTailCall, bool isVector, SmallVectorImpl< SDValue > & MemOpChains, SmallVectorImpl< TailCallArgumentInfo > & TailCallArguments, const SDLoc & dl) static
LowerMemOpCallTo - Store the argument to the stack or remember it in case of tail calls.
Definition at line 4936 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, CalculateTailCallArgDest(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::i32, llvm::MVT::i64, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by buildCallOperands(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), and llvm::ARMTargetLowering::hasStandaloneRem().
needStackSlotPassParameters()
static bool needStackSlotPassParameters (const PPCSubtarget & Subtarget, const SmallVectorImpl< ISD::OutputArg > & Outs) static
Definition at line 4594 of file PPCISelLowering.cpp.
References llvm::array_lengthof(), assert(), CalculateStackSlotUsed(), llvm::PPCSubtarget::getFrameLowering(), llvm::PPCFrameLowering::getLinkageSize(), llvm::GPR, llvm::PPCSubtarget::hasQPX(), llvm::PPCSubtarget::is64BitELFABI(), llvm::NVPTX::PTXLdStInstCode::V2, and llvm::NVPTX::PTXLdStInstCode::V4.
Referenced by areCallingConvEligibleForTCO_64SVR4().
prepareDescriptorIndirectCall()
static void prepareDescriptorIndirectCall (SelectionDAG & DAG, SDValue & Callee, SDValue & Glue, SDValue & Chain, SDValue CallSeqStart, ImmutableCallSite CS, const SDLoc & dl, bool hasNest, const PPCSubtarget & Subtarget) static
Definition at line 5252 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::PPCSubtarget::descriptorEnvironmentPointerOffset(), llvm::PPCSubtarget::descriptorTOCAnchorOffset(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledValue(), llvm::SelectionDAG::getCopyToReg(), llvm::PPCSubtarget::getEnvironmentPointerRegister(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), getOutputChainFromCallSeq(), llvm::PPCSubtarget::getTOCPointerRegister(), llvm::SDValue::getValue(), llvm::PPCSubtarget::hasInvariantFunctionDescriptors(), llvm::MVT::i32, llvm::MVT::i64, llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isPPC64(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::MachineMemOperand::MONone, and prepareIndirectCall().
Referenced by buildCallOperands().
prepareIndirectCall()
static void prepareIndirectCall (SelectionDAG & DAG, SDValue & Callee, SDValue & Glue, SDValue & Chain, const SDLoc & dl) static
Definition at line 5241 of file PPCISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::MVT::Glue, llvm::makeArrayRef(), llvm::PPCISD::MTCTR, and llvm::MVT::Other.
Referenced by buildCallOperands(), and prepareDescriptorIndirectCall().
PrepareTailCall()
static void PrepareTailCall (SelectionDAG & DAG, SDValue & InFlag, SDValue & Chain, const SDLoc & dl, int SPDiff, unsigned NumBytes, SDValue LROp, SDValue FPOp, SmallVectorImpl< TailCallArgumentInfo > & TailCallArguments) static
Definition at line 4960 of file PPCISelLowering.cpp.
References EmitTailCallStoreFPAndRetAddr(), llvm::SmallVectorBase::empty(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::MVT::Other, StoreTailCallArgumentsToStackSlot(), and llvm::ISD::TokenFactor.
Referenced by buildCallOperands().
setUsesTOCBasePtr() [1/2]
static void setUsesTOCBasePtr (MachineFunction & MF) static
Definition at line 2723 of file PPCISelLowering.cpp.
References llvm::MachineFunction::getInfo(), and llvm::PPCFunctionInfo::setUsesTOCBasePtr().
Referenced by buildCallOperands(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), setUsesTOCBasePtr(), and truncateScalarIntegerArg().
setUsesTOCBasePtr() [2/2]
static void setUsesTOCBasePtr (SelectionDAG & DAG) static
Definition at line 2728 of file PPCISelLowering.cpp.
References C, llvm::HexagonISD::CP, llvm::ConstantPoolSDNode::getAlignment(), llvm::ConstantPoolSDNode::getConstVal(), llvm::MachinePointerInfo::getGOT(), getLabelAccessInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::PPCISD::GlobalBaseReg, llvm::MVT::i32, llvm::MVT::i64, llvm::PPCSubtarget::is64BitELFABI(), llvm::PPCSubtarget::isAIXABI(), llvm::TargetLowering::isPositionIndependent(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), LowerLabelRef(), llvm::PPCII::MO_PIC_FLAG, llvm::MachineMemOperand::MOLoad, llvm::MVT::Other, R2, Reg, setUsesTOCBasePtr(), and llvm::PPCISD::TOC_ENTRY.
STATISTIC() [1/2]
STATISTIC (NumTailCalls , "Number of tail calls")
STATISTIC() [2/2]
STATISTIC (NumSiblingCalls , "Number of sibling calls")
StoreTailCallArgumentsToStackSlot()
static void StoreTailCallArgumentsToStackSlot (SelectionDAG & DAG, SDValue Chain, const SmallVectorImpl< TailCallArgumentInfo > & TailCallArgs, SmallVectorImpl< SDValue > & MemOpChains, const SDLoc & dl) static
StoreTailCallArgumentsToStackSlot - Stores arguments to their stack slot.
Definition at line 4827 of file PPCISelLowering.cpp.
References Arg, llvm::numbers::e, llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getStore(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorBase::size().
Referenced by PrepareTailCall().
stripModuloOnShift()
static SDValue stripModuloOnShift (const TargetLowering & TLI, SDNode * N, SelectionDAG & DAG) static
Definition at line 15431 of file PPCISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::AssertSext, llvm::dyn_cast(), llvm::PPCISD::EXTSWSLI, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i32, llvm::MVT::i64, llvm::isConstOrConstSplat(), llvm::TargetLoweringBase::isOperationLegal(), llvm::EVT::isVector(), llvm_unreachable, llvm::BitmaskEnumDetail::Mask(), llvm::PPCISD::SHL, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::PPCISD::SRA, llvm::ISD::SRA, llvm::PPCISD::SRL, llvm::ISD::SRL, and llvm::ISD::TRUNCATE.
transformCallee()
static SDValue transformCallee (const SDValue & Callee, SelectionDAG & DAG, const SDLoc & dl, const PPCSubtarget & Subtarget) static
Definition at line 5129 of file PPCISelLowering.cpp.
References assert(), llvm::XCOFF::C_EXT, Context, llvm::dyn_cast(), F(), G, llvm::MachineModuleInfo::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMCSymbol(), llvm::SectionKind::getMetadata(), llvm::MachineFunction::getMMI(), llvm::MCSymbol::getName(), llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::SDValue::getNode(), llvm::GlobalValue::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetMachine::getRelocationModel(), llvm::TargetLoweringObjectFileXCOFF::getStorageClassForGlobal(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::PPCSubtarget::getTargetMachine(), llvm::SDValue::getValueType(), llvm::MCSymbolXCOFF::hasContainingCsect(), llvm::PPCSubtarget::is32BitELFABI(), llvm::PPCSubtarget::isAIXABI(), isBLACompatibleAddress(), llvm::GlobalValue::isDeclaration(), llvm::PPCSubtarget::isELFv2ABI(), isFunctionGlobalAddress(), isValidAIXExternalSymSDNode(), llvm::PPCII::MO_PLT, llvm::Mod, llvm::Reloc::PIC_, llvm::report_fatal_error(), llvm::PPCISD::SC, llvm::MCSymbolXCOFF::setContainingCsect(), llvm::TargetMachine::shouldAssumeDSOLocal(), llvm::PPCSubtarget::usesFunctionDescriptors(), llvm::XCOFF::XMC_PR, and llvm::XCOFF::XTY_ER.
Referenced by buildCallOperands().
truncateScalarIntegerArg()
static SDValue truncateScalarIntegerArg (ISD::ArgFlagsTy Flags, EVT ValVT, SelectionDAG & DAG, SDValue ArgValue, MVT LocVT, const SDLoc & dl) static
Definition at line 6969 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::CCValAssign::AExt, llvm::CCState::AnalyzeReturn(), llvm::PPCISD::ANDI_rec_1_GT_BIT, llvm::ISD::ANY_EXTEND, llvm::lltok::APFloat, Arg, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::CallingConv::C, CC_AIX(), llvm::CCState::CheckReturn(), llvm::CallingConv::Cold, contains(), Context, llvm::MachineFrameInfo::CreateFixedObject(), llvm::SelectionDAG::CreateStackTemporary(), llvm::dyn_cast(), llvm::PPCISD::DYNALLOC, llvm::PPCISD::DYNAREAOFFSET, llvm::numbers::e, E, llvm::PPCISD::EH_SJLJ_LONGJMP, llvm::PPCISD::EH_SJLJ_SETJMP, EnableQuadPrecision, EnsureStackAlignment(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_ELEMENT, llvm::PPCISD::EXTRACT_SPE, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::PPCISD::FADDRTZ, llvm::CallingConv::Fast, llvm::PPCISD::FCFID, llvm::PPCISD::FCFIDS, llvm::PPCISD::FCFIDU, llvm::PPCISD::FCFIDUS, llvm::PPCISD::FCTIDUZ, llvm::PPCISD::FCTIDZ, llvm::PPCISD::FCTIWUZ, llvm::PPCISD::FCTIWZ, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::PPCISD::FSEL, llvm::ISD::FSUB, llvm::CCValAssign::Full, llvm::MemSDNode::getAAInfo(), llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::SelectionDAG::getBitcast(), llvm::PPCRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MachinePointerInfo::getFixedStack(), llvm::MVT::getFloatingPointVT(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::PPCSubtarget::getFrameLowering(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), llvm::MachineFunction::getInfo(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::PPCFrameLowering::getLinkageSize(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::LoadSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::MemSDNode::getRanges(), getRegClassForSVT(), llvm::SelectionDAG::getRegister(), llvm::PPCFunctionInfo::getReturnAddrSaveIndex(), llvm::SelectionDAG::getSelectCC(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::MachineMemOperand::getSize(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MachinePointerInfo::getStack(), llvm::PPCSubtarget::getStackPointerRegister(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::SelectionDAG::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCSubtarget::getTOCPointerRegister(), llvm::PPCFrameLowering::getTOCSaveOffset(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getUNDEF(), llvm::CCValAssign::getValNo(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::MachinePointerInfo::getWithOffset(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasQPX(), llvm::MipsISD::Hi, I, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MemSDNode::isDereferenceable(), llvm::EVT::isFloatingPoint(), llvm::MVT::isFloatingPoint(), isFloatingPointZero(), isFunctionGlobalAddress(), llvm::LSBaseSDNode::isIndexed(), llvm::MVT::isInteger(), llvm::MemSDNode::isInvariant(), llvm::CCValAssign::isMemLoc(), llvm::MemSDNode::isNonTemporal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::PPCSubtarget::isPPC64(), llvm::CCValAssign::isRegLoc(), llvm::EVT::isScalarInteger(), llvm::MVT::isScalarInteger(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::ISD::ArgFlagsTy::isZExt(), llvm::ARM_MB::LD, LLVM_FALLTHROUGH, llvm_unreachable, llvm::MipsISD::Lo, llvm::ISD::LOAD, llvm::PPCISD::MFVSR, llvm::MachineMemOperand::MOStore, llvm::PPCISD::MTVSRA, llvm::PPCISD::MTVSRZ, llvm::CCValAssign::needsCustom(), llvm::TargetOptions::NoInfsFPMath, llvm::ISD::NON_EXTLOAD, llvm::TargetOptions::NoNaNsFPMath, llvm::TargetMachine::Options, llvm::MVT::Other, llvm::APFloatBase::PPCDoubleDouble(), llvm::MVT::ppcf128, llvm::ISD::PRE_INC, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::report_fatal_error(), llvm::PPCISD::RET_FLAG, llvm::RetCC_PPC(), llvm::RetCC_PPC_Cold(), llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::PPCFunctionInfo::setMinReservedArea(), llvm::ISD::SETNE, llvm::SDNodeFlags::setNoInfs(), llvm::SDNodeFlags::setNoNaNs(), llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETUGT, llvm::ISD::SETULT, setUsesTOCBasePtr(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, Signed, llvm::MVT::SimpleTy, llvm::ISD::SINT_TO_FP, Size, llvm::SmallVectorBase::size(), llvm::ISD::SRL, llvm::ARM_MB::ST, llvm::PPCISD::STFIWX, llvm::ISD::SUB, std::swap(), llvm::ISD::TokenFactor, TRI, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::SelectionDAG::UpdateNodeOperands(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::PPCTargetLowering::useSoftFloat(), widenVec(), llvm::PPCISD::XSMAXCDP, llvm::PPCISD::XSMINCDP, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
usePartialVectorLoads()
static bool usePartialVectorLoads (SDNode * N, const PPCSubtarget & ST) static
Returns true if we should use a direct load into vector instruction (such as lxsd or lfd), instead of a load into gpr + direct move sequence.
Definition at line 2541 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::MemSDNode::getMemoryVT(), llvm::EVT::getSimpleVT(), llvm::SDValue::hasOneUse(), llvm::PPCSubtarget::hasP8Vector(), llvm::PPCSubtarget::hasP9Vector(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::EVT::isSimple(), llvm::ARM_MB::LD, N, llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::SimpleTy, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by llvm::PPCTargetLowering::getPreIndexedAddressParts().
widenVec()
static SDValue widenVec (SelectionDAG & DAG, SDValue Vec, const SDLoc & dl) static
Definition at line 7971 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::ISD::CONCAT_VECTORS, EnableQuadPrecision, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::PPCISD::FCFID, llvm::PPCISD::FCFIDS, llvm::PPCISD::FCFIDU, llvm::PPCISD::FCFIDUS, llvm::ISD::FMA, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MVT::i1, llvm::MVT::i64, llvm::EVT::isFloatingPoint(), llvm::TargetLoweringBase::isOperationCustom(), llvm::EVT::isVector(), llvm::TargetMachine::Options, llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PPCISD::QBFLT, llvm::ISD::SELECT, llvm::PPCISD::SExtVElems, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::TargetOptions::UnsafeFPMath, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, and llvm::MVT::v4i32.
Referenced by truncateScalarIntegerArg().
Variable Documentation
ANDIGlueBug
cl::opt<bool> ANDIGlueBug
Referenced by mayUseP9Setb().
DisableILPPref
cl::opt<bool> DisableILPPref("disable-ppc-ilp-pref", cl::desc("disable setting the node scheduling preference to ILP on PPC"), cl::Hidden) static
Referenced by llvm::PPCTargetLowering::getSchedulingPreference().
DisableInnermostLoopAlign32
cl::opt<bool> DisableInnermostLoopAlign32("disable-ppc-innermost-loop-align32", cl::desc("don't always align innermost loop to 32 bytes on ppc"), cl::Hidden) static
Referenced by llvm::PPCTargetLowering::getPrefLoopAlignment().
DisablePPCPreinc
cl::opt<bool> DisablePPCPreinc("disable-ppc-preinc", cl::desc("disable preincrement load/store generation on PPC"), cl::Hidden) static
Referenced by llvm::PPCTargetLowering::getPreIndexedAddressParts().
DisablePPCUnaligned
cl::opt<bool> DisablePPCUnaligned("disable-ppc-unaligned", cl::desc("disable unaligned load/store generation on PPC"), cl::Hidden) static
Referenced by llvm::PPCTargetLowering::allowsMisalignedMemoryAccesses().
DisableSCO
cl::opt<bool> DisableSCO("disable-ppc-sco", cl::desc("disable sibling call optimization on ppc"), cl::Hidden) static
Referenced by areCallingConvEligibleForTCO_64SVR4(), and combineADDToADDZE().
EnableQuadPrecision
cl::opt<bool> EnableQuadPrecision("enable-ppc-quad-precision", cl::desc("enable quad precision float support on ppc"), cl::Hidden) static
Referenced by haveEfficientBuildVectorPattern(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::PPCTargetLowering(), truncateScalarIntegerArg(), and widenVec().
FPR
const MCPhysReg FPR[] static
Initial value:
= {PPC::F1,  PPC::F2,  PPC::F3, PPC::F4, PPC::F5,
                                PPC::F6,  PPC::F7,  PPC::F8, PPC::F9, PPC::F10,
                                PPC::F11, PPC::F12, PPC::F13}
FPR - The set of FP registers that should be allocated for arguments on Darwin and AIX.
Definition at line 3316 of file PPCISelLowering.cpp.
Referenced by llvm::AArch64RegisterBankInfo::AArch64RegisterBankInfo(), and llvm::SystemZMachineFunctionInfo::setVarArgsFirstFPR().
QFPR
const MCPhysReg QFPR[] static
Initial value:
= {
    PPC::QF1, PPC::QF2, PPC::QF3,  PPC::QF4,  PPC::QF5,  PPC::QF6, PPC::QF7,
    PPC::QF8, PPC::QF9, PPC::QF10, PPC::QF11, PPC::QF12, PPC::QF13}
QFPR - The set of QPX registers that should be allocated for arguments.
Definition at line 3321 of file PPCISelLowering.cpp.
UseAbsoluteJumpTables
cl::opt<bool> UseAbsoluteJumpTables("ppc-use-absolute-jumptables", cl::desc("use absolute jump tables on ppc"), cl::Hidden) static
Referenced by llvm::PPCTargetLowering::isJumpTableRelative().