LLVM: lib/Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.cpp File Reference
PPCMCCodeEmitter.cpp File Reference
#include "MCTargetDesc/PPCFixupKinds.h"
#include "PPCInstrInfo.h"
#include "PPCMCCodeEmitter.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/Triple.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include "PPCGenMCCodeEmitter.inc"
Macros
#define DEBUG_TYPE "mccodeemitter"
#define ENABLE_INSTR_PREDICATE_VERIFIER
Functions
STATISTIC (MCNumEmitted, "Number of MC instructions emitted")
static unsigned getOpIdxForMO (const MCInst &MI, const MCOperand &MO)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mccodeemitter"
Definition at line 32 of file PPCMCCodeEmitter.cpp.
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 319 of file PPCMCCodeEmitter.cpp.
Function Documentation
getOpIdxForMO()
static unsigned getOpIdxForMO (const MCInst & MI, const MCOperand & MO) static
Definition at line 250 of file PPCMCCodeEmitter.cpp.
References llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), and llvm_unreachable.
Referenced by llvm::PPCMCCodeEmitter::getMachineOpValue().
STATISTIC()
STATISTIC (MCNumEmitted , "Number of MC instructions emitted")