LLVM: lib/Target/PowerPC/PPCQPXLoadSplat.cpp File Reference
PPCQPXLoadSplat.cpp File Reference
#include "PPC.h"
#include "PPCInstrBuilder.h"
#include "PPCInstrInfo.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "ppc-qpx-load-splat"
Functions
STATISTIC (NumSimplified, "Number of QPX load splats simplified")
INITIALIZE_PASS (PPCQPXLoadSplat, "ppc-qpx-load-splat", "PowerPC QPX Load Splat Simplification", false, false) FunctionPass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-qpx-load-splat"
Definition at line 29 of file PPCQPXLoadSplat.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (PPCQPXLoadSplat , "ppc-qpx-load-splat" , "PowerPC QPX Load Splat Simplification" , false , false)
Definition at line 49 of file PPCQPXLoadSplat.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineFunction::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineFunction::end(), llvm::SmallVectorImpl< T >::erase(), llvm::MachineInstr::eraseFromParent(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterInfo::getSubReg(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineInstr::isCall(), llvm::MachineOperand::isKill(), llvm::PPCISD::LFIWAX, llvm::PPCISD::LFIWZX, MI, llvm::MachineInstr::modifiesRegister(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::PPCISD::QVESPLATI, llvm::MachineBasicBlock::rbegin(), llvm::MachineInstr::readsRegister(), llvm::MachineBasicBlock::rend(), llvm::MachineOperand::setReg(), SI, llvm::MachineInstr::substituteRegister(), and TRI.
STATISTIC()
STATISTIC (NumSimplified , "Number of QPX load splats simplified")