LLVM: lib/Target/PowerPC/PPCTargetMachine.cpp File Reference
PPCTargetMachine.cpp File Reference
#include "PPCTargetMachine.h"
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "PPC.h"
#include "PPCMachineScheduler.h"
#include "PPCSubtarget.h"
#include "PPCTargetObjectFile.h"
#include "PPCTargetTransformInfo.h"
#include "TargetInfo/PowerPCTargetInfo.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/Pass.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/Scalar.h"
#include <cassert>
#include <memory>
#include <string>
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCTarget ()
static std::string getDataLayoutString (const Triple &T)
Return the datalayout string of a subtarget.
static std::string computeFSAdditions (StringRef FS, CodeGenOpt::Level OL, const Triple &TT)
static std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple &TT)
static PPCTargetMachine::PPCABI computeTargetABI (const Triple &TT, const TargetOptions &Options)
static Reloc::Model getEffectiveRelocModel (const Triple &TT, Optional< Reloc::Model > RM)
static CodeModel::Model getEffectivePPCCodeModel (const Triple &TT, Optional< CodeModel::Model > CM, bool JIT)
static ScheduleDAGInstrs * createPPCMachineScheduler (MachineSchedContext *C)
static ScheduleDAGInstrs * createPPCPostMachineScheduler (MachineSchedContext *C)
Variables
static cl::opt< bool > EnableBranchCoalescing ("enable-ppc-branch-coalesce", cl::Hidden, cl::desc("enable coalescing of duplicate branches for PPC"))
static cl::opt< bool > DisableCTRLoops ("disable-ppc-ctrloops", cl::Hidden, cl::desc("Disable CTR loops for PPC"))
static cl::opt< bool > DisableInstrFormPrep ("disable-ppc-instr-form-prep", cl::Hidden, cl::desc("Disable PPC loop instr form prep"))
static cl::opt< bool > VSXFMAMutateEarly ("schedule-ppc-vsx-fma-mutation-early", cl::Hidden, cl::desc("Schedule VSX FMA instruction mutation early"))
static cl::opt< bool > DisableVSXSwapRemoval ("disable-ppc-vsx-swap-removal", cl::Hidden, cl::desc("Disable VSX Swap Removal for PPC"))
static cl::opt< bool > DisableQPXLoadSplat ("disable-ppc-qpx-load-splat", cl::Hidden, cl::desc("Disable QPX load splat simplification"))
static cl::opt< bool > DisableMIPeephole ("disable-ppc-peephole", cl::Hidden, cl::desc("Disable machine peepholes for PPC"))
static cl::opt< bool > EnableGEPOpt ("ppc-gep-opt", cl::Hidden, cl::desc("Enable optimizations on complex GEPs"), cl::init(true))
static cl::opt< bool > EnablePrefetch ("enable-ppc-prefetching", cl::desc("enable software prefetching on PPC"), cl::init(false), cl::Hidden)
static cl::opt< bool > EnableExtraTOCRegDeps ("enable-ppc-extra-toc-reg-deps", cl::desc("Add extra TOC register dependencies"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableMachineCombinerPass ("ppc-machine-combiner", cl::desc("Enable the machine combiner pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > ReduceCRLogical ("ppc-reduce-cr-logicals", cl::desc("Expand eligible cr-logical binary ops to branches"), cl::init(true), cl::Hidden)
static MachineSchedRegistry PPCPreRASchedRegistry ("ppc-prera", "Run PowerPC PreRA specific scheduler", createPPCMachineScheduler)
static MachineSchedRegistry PPCPostRASchedRegistry ("ppc-postra", "Run PowerPC PostRA specific scheduler", createPPCPostMachineScheduler)
Function Documentation
computeFSAdditions()
static std::string computeFSAdditions (StringRef FS, CodeGenOpt::Level OL, const Triple & TT) static
Definition at line 159 of file PPCTargetMachine.cpp.
References llvm::CodeGenOpt::Default, llvm::X86AS::FS, llvm::Triple::getArch(), llvm::CodeGenOpt::None, llvm::Triple::ppc64, and llvm::Triple::ppc64le.
Referenced by llvm::PPCTargetMachine::getSubtargetImpl().
computeTargetABI()
static PPCTargetMachine::PPCABI computeTargetABI (const Triple & TT, const TargetOptions & Options) static
Definition at line 198 of file PPCTargetMachine.cpp.
References assert(), llvm::StringRef::empty(), llvm::MCTargetOptions::getABIName(), llvm::Triple::getArch(), llvm::Triple::isMacOSX(), llvm::Triple::isOSDarwin(), llvm::TargetOptions::MCOptions, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::PPCTargetMachine::PPC_ABI_ELFv1, llvm::PPCTargetMachine::PPC_ABI_ELFv2, llvm::PPCTargetMachine::PPC_ABI_UNKNOWN, llvm::report_fatal_error(), and llvm::StringRef::startswith().
createPPCMachineScheduler()
static ScheduleDAGInstrs* createPPCMachineScheduler (MachineSchedContext * C) static
Definition at line 267 of file PPCTargetMachine.cpp.
References llvm::ScheduleDAGMI::addMutation(), C, llvm::createCopyConstrainDAGMutation(), llvm::MachineFunction::getSubtarget(), llvm::MachineSchedContext::MF, llvm::ARM_MB::ST, and llvm::PPCSubtarget::usePPCPreRASchedStrategy().
Referenced by llvm::PPCTargetMachine::getSubtargetImpl(), and llvm::PPCTargetMachine::getTargetTransformInfo().
createPPCPostMachineScheduler()
static ScheduleDAGInstrs* createPPCPostMachineScheduler (MachineSchedContext * C) static
Definition at line 278 of file PPCTargetMachine.cpp.
References C, llvm::MachineFunction::getSubtarget(), llvm::MachineSchedContext::MF, llvm::ARM_MB::ST, and llvm::PPCSubtarget::usePPCPostRASchedStrategy().
Referenced by llvm::PPCTargetMachine::getSubtargetImpl(), and llvm::PPCTargetMachine::getTargetTransformInfo().
createTLOF()
static std::unique_ptr<TargetLoweringObjectFile> createTLOF (const Triple & TT) static
Definition at line 188 of file PPCTargetMachine.cpp.
References llvm::Triple::isOSAIX(), and llvm::Triple::isOSDarwin().
getDataLayoutString()
static std::string getDataLayoutString (const Triple & T) static
Return the datalayout string of a subtarget.
Definition at line 126 of file PPCTargetMachine.cpp.
References llvm::Triple::getArch(), llvm::DataLayout::getManglingComponent(), llvm::Triple::getOS(), is64Bit(), llvm::Triple::isOSDarwin(), llvm::Triple::Lv2, llvm::Triple::ppc64, llvm::Triple::ppc64le, and llvm::MipsISD::Ret.
getEffectivePPCCodeModel()
static CodeModel::Model getEffectivePPCCodeModel (const Triple & TT, Optional< CodeModel::Model > CM, bool JIT) static
Definition at line 241 of file PPCTargetMachine.cpp.
References assert(), llvm::Triple::isArch32Bit(), llvm::Triple::isArch64Bit(), llvm::Triple::isOSAIX(), llvm::Triple::isOSBinFormatELF(), llvm::CodeModel::Kernel, llvm::CodeModel::Medium, llvm::report_fatal_error(), llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (const Triple & TT, Optional< Reloc::Model > RM) static
Definition at line 224 of file PPCTargetMachine.cpp.
References llvm::Reloc::DynamicNoPIC, llvm::Triple::getArch(), llvm::Optional< T >::hasValue(), llvm::Triple::isOSDarwin(), llvm::Reloc::PIC_, llvm::Triple::ppc64, and llvm::Reloc::Static.
LLVMInitializePowerPCTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCTarget ()
Definition at line 97 of file PPCTargetMachine.cpp.
References B, C, llvm::PassRegistry::getPassRegistry(), llvm::getThePPC32Target(), llvm::getThePPC64LETarget(), llvm::getThePPC64Target(), llvm::initializePPCBoolRetToIntPass(), llvm::initializePPCBranchCoalescingPass(), llvm::initializePPCBSelPass(), llvm::initializePPCCTRLoopsVerifyPass(), llvm::initializePPCEarlyReturnPass(), llvm::initializePPCExpandISELPass(), llvm::initializePPCLoopInstrFormPrepPass(), llvm::initializePPCLowerMASSVEntriesPass(), llvm::initializePPCMIPeepholePass(), llvm::initializePPCPreEmitPeepholePass(), llvm::initializePPCQPXLoadSplatPass(), llvm::initializePPCReduceCRLogicalsPass(), llvm::initializePPCTLSDynamicCallPass(), llvm::initializePPCTOCRegDepsPass(), llvm::initializePPCVSXCopyPass(), llvm::initializePPCVSXFMAMutatePass(), and llvm::initializePPCVSXSwapRemovalPass().
Variable Documentation
DisableCTRLoops
cl:: opt<bool> DisableCTRLoops("disable-ppc-ctrloops", cl::Hidden, cl::desc("Disable CTR loops for PPC")) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
DisableInstrFormPrep
cl:: opt<bool> DisableInstrFormPrep("disable-ppc-instr-form-prep", cl::Hidden, cl::desc("Disable PPC loop instr form prep")) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
DisableMIPeephole
cl:: opt<bool> DisableMIPeephole("disable-ppc-peephole", cl::Hidden, cl::desc("Disable machine peepholes for PPC")) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
DisableQPXLoadSplat
cl:: opt<bool> DisableQPXLoadSplat("disable-ppc-qpx-load-splat", cl::Hidden, cl::desc("Disable QPX load splat simplification")) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
DisableVSXSwapRemoval
cl:: opt<bool> DisableVSXSwapRemoval("disable-ppc-vsx-swap-removal", cl::Hidden, cl::desc("Disable VSX Swap Removal for PPC")) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
EnableBranchCoalescing
cl::opt<bool> EnableBranchCoalescing("enable-ppc-branch-coalesce", cl::Hidden, cl::desc("enable coalescing of duplicate branches for PPC")) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
EnableExtraTOCRegDeps
cl::opt<bool> EnableExtraTOCRegDeps("enable-ppc-extra-toc-reg-deps", cl::desc("Add extra TOC register dependencies"), cl::init(true), cl::Hidden) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
EnableGEPOpt
cl::opt<bool> EnableGEPOpt("ppc-gep-opt", cl::Hidden, cl::desc("Enable optimizations on complex GEPs"), cl::init(true)) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
EnableMachineCombinerPass
cl::opt<bool> EnableMachineCombinerPass("ppc-machine-combiner", cl::desc("Enable the machine combiner pass"), cl::init(true), cl::Hidden) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
EnablePrefetch
cl::opt<bool> EnablePrefetch("enable-ppc-prefetching", cl::desc("enable software prefetching on PPC"), cl::init(false), cl::Hidden) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
PPCPostRASchedRegistry
MachineSchedRegistry PPCPostRASchedRegistry("ppc-postra", "Run PowerPC PostRA specific scheduler", createPPCPostMachineScheduler) static
Referenced by llvm::PPCTargetMachine::getTargetTransformInfo().
PPCPreRASchedRegistry
MachineSchedRegistry PPCPreRASchedRegistry("ppc-prera", "Run PowerPC PreRA specific scheduler", createPPCMachineScheduler) static
Referenced by llvm::PPCTargetMachine::getTargetTransformInfo().
ReduceCRLogical
cl::opt<bool> ReduceCRLogical("ppc-reduce-cr-logicals", cl::desc("Expand eligible cr-logical binary ops to branches"), cl::init(true), cl::Hidden) static
Referenced by llvm::PPCTargetMachine::createPassConfig().
VSXFMAMutateEarly
cl::opt<bool> VSXFMAMutateEarly("schedule-ppc-vsx-fma-mutation-early", cl::Hidden, cl::desc("Schedule VSX FMA instruction mutation early")) static
Referenced by llvm::PPCTargetMachine::createPassConfig().