LLVM: lib/CodeGen/PreISelIntrinsicLowering.cpp File Reference
PreISelIntrinsicLowering.cpp File Reference
#include "llvm/CodeGen/PreISelIntrinsicLowering.h"
#include "llvm/Analysis/ObjCARCInstKind.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
Functions
static bool lowerLoadRelative (Function &F)
static CallInst::TailCallKind getOverridingTailCallKind (const Function &F)
static bool lowerObjCCall (Function &F, const char *NewFn, bool setNonLazyBind=false)
static bool lowerIntrinsics (Module &M)
INITIALIZE_PASS (PreISelIntrinsicLoweringLegacyPass, "pre-isel-intrinsic-lowering", "Pre-ISel Intrinsic Lowering", false, false) ModulePass *llvm
Function Documentation
getOverridingTailCallKind()
static CallInst::TailCallKind getOverridingTailCallKind (const Function & F) static
Definition at line 63 of file PreISelIntrinsicLowering.cpp.
References llvm::objcarc::GetFunctionClass(), llvm::objcarc::IsAlwaysTail(), llvm::objcarc::IsNeverTail(), llvm::CallInst::TCK_None, llvm::CallInst::TCK_NoTail, and llvm::CallInst::TCK_Tail.
Referenced by lowerObjCCall().
INITIALIZE_PASS()
INITIALIZE_PASS (PreISelIntrinsicLoweringLegacyPass , "pre-isel-intrinsic-lowering" , "Pre-ISel Intrinsic Lowering" , false , false)
Definition at line 226 of file PreISelIntrinsicLowering.cpp.
lowerIntrinsics()
static bool lowerIntrinsics (Module & M) static
Definition at line 121 of file PreISelIntrinsicLowering.cpp.
References F(), lowerLoadRelative(), and lowerObjCCall().
Referenced by llvm::PreISelIntrinsicLoweringPass::run(), and llvm::InstrProfiling::run().
lowerLoadRelative()
static bool lowerLoadRelative (Function & F) static
Definition at line 30 of file PreISelIntrinsicLowering.cpp.
References B, llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::dyn_cast(), E, F(), llvm::Function::getContext(), llvm::Type::getInt32Ty(), llvm::Type::getInt8Ty(), llvm::Type::getPointerTo(), I, Int32Ty, llvm::Value::replaceAllUsesWith(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by lowerIntrinsics().
lowerObjCCall()
static bool lowerObjCCall (Function & F, const char * NewFn, bool setNonLazyBind = false) static
Definition at line 72 of file PreISelIntrinsicLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), E, llvm::FunctionCallee::getCallee(), llvm::Function::getFunctionType(), llvm::GlobalValue::getLinkage(), llvm::Module::getOrInsertFunction(), getOverridingTailCallKind(), llvm::GlobalValue::getParent(), I, llvm::max(), setNonLazyBind(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by lowerIntrinsics().