LLVM: lib/CodeGen/ProcessImplicitDefs.cpp File Reference
ProcessImplicitDefs.cpp File Reference
#include "llvm/ADT/SetVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "processimpdefs"
Functions
INITIALIZE_PASS (ProcessImplicitDefs, DEBUG_TYPE, "Process Implicit Definitions", false, false) void ProcessImplicitDefs
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "processimpdefs"
Definition at line 23 of file ProcessImplicitDefs.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ProcessImplicitDefs , DEBUG_TYPE , "Process Implicit Definitions" , false , false)
Definition at line 54 of file ProcessImplicitDefs.cpp.
References assert(), llvm::MachineFunction::begin(), llvm::dbgs(), llvm::MachineFunction::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFunction::getName(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isCopyLike(), llvm::MachineInstr::isInsertSubreg(), llvm::MachineInstr::isPHI(), llvm::Register::isPhysicalRegister(), llvm::MachineInstr::isRegSequence(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MI, MRI, llvm::MachineInstr::operands(), llvm::printMBBReference(), Reg, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), TII, and TRI.