LLVM: lib/Transforms/Utils/PromoteMemoryToRegister.cpp File Reference
PromoteMemoryToRegister.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/IteratedDominanceFrontier.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/Support/Casting.h"
#include "llvm/Transforms/Utils/PromoteMemToReg.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "mem2reg"
Functions
STATISTIC (NumLocalPromoted, "Number of alloca's promoted within one block")
STATISTIC (NumSingleStore, "Number of alloca's promoted with a single store")
STATISTIC (NumDeadAlloca, "Number of dead alloca's removed")
STATISTIC (NumPHIInsert, "Number of PHI nodes inserted")
static void addAssumeNonNull (AssumptionCache *AC, LoadInst *LI)
Given a LoadInst LI this adds assume(LI != null) after it.
static void removeLifetimeIntrinsicUsers (AllocaInst *AI)
static bool rewriteSingleStoreAlloca (AllocaInst *AI, AllocaInfo &Info, LargeBlockInfo &LBI, const DataLayout &DL, DominatorTree &DT, AssumptionCache *AC)
Rewrite as many loads as possible given a single store.
static bool promoteSingleBlockAlloca (AllocaInst *AI, const AllocaInfo &Info, LargeBlockInfo &LBI, const DataLayout &DL, DominatorTree &DT, AssumptionCache *AC)
Many allocas are only used within a single basic block.
static void updateForIncomingValueLocation (PHINode *PN, DebugLoc DL, bool ApplyMergedLoc)
Update the debug location of a phi.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mem2reg"
Definition at line 57 of file PromoteMemoryToRegister.cpp.
Function Documentation
addAssumeNonNull()
static void addAssumeNonNull (AssumptionCache * AC, LoadInst * LI) static
Given a LoadInst LI this adds assume(LI != null) after it.
Definition at line 304 of file PromoteMemoryToRegister.cpp.
References llvm::CallInst::Create(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_NE, llvm::Instruction::insertAfter(), and llvm::AssumptionCache::registerAssumption().
Referenced by promoteSingleBlockAlloca(), rewriteSingleStoreAlloca(), and updateForIncomingValueLocation().
promoteSingleBlockAlloca()
static bool promoteSingleBlockAlloca (AllocaInst * AI, const AllocaInfo & Info, LargeBlockInfo & LBI, const DataLayout & DL, DominatorTree & DT, AssumptionCache * AC) static
Many allocas are only used within a single basic block.
If this is the case, avoid traversing the CFG and inserting a lot of potentially useless PHI nodes by just performing a single linear pass over the basic block using the Alloca.
If we cannot promote this alloca (because it is read before it is written), return false. This is necessary in cases where, due to control flow, the alloca is undefined only on some control flow paths. e.g. code like this is correct in LLVM IR: // A is an alloca with no stores so far for (...) { int t = *A; if (!first_iteration) use(t); *A = 42; }
Definition at line 444 of file PromoteMemoryToRegister.cpp.
References addAssumeNonNull(), llvm::PHINode::addIncoming(), assert(), B, llvm::BasicBlock::back(), llvm::BasicBlock::begin(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), ComputeLiveInBlocks(), llvm::ConvertDebugDeclareToDebugValue(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::PHINode::Create(), llvm::coverage::CurrentVersion, llvm::dyn_cast(), llvm::numbers::e, E, llvm::SmallVectorTemplateCommon< T >::end(), llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::SmallVectorImpl< T >::erase(), llvm::Instruction::eraseFromParent(), F, llvm::BasicBlock::front(), llvm::Function::front(), llvm::UndefValue::get(), llvm::PHINode::getIncomingBlock(), llvm::Instruction::getMetadata(), llvm::Instruction::getModule(), getName(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::Value::getType(), I, Info, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isAllocaPromotable(), llvm::isKnownNonZero(), llvm::lower_bound(), P, llvm::pred_begin(), llvm::pred_end(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), removeLifetimeIntrinsicUsers(), llvm::Value::replaceAllUsesWith(), rewriteSingleStoreAlloca(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::setDefiningBlocks(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::setLiveInBlocks(), SI, llvm::SimplifyInstruction(), llvm::sort(), llvm::Value::use_empty(), llvm::Instruction::user_back(), llvm::Value::user_begin(), llvm::Value::user_end(), llvm::Value::users(), and llvm::IndexedInstrProf::Version.
removeLifetimeIntrinsicUsers()
static void removeLifetimeIntrinsicUsers (AllocaInst * AI) static
Definition at line 315 of file PromoteMemoryToRegister.cpp.
References llvm::Instruction::eraseFromParent(), llvm::Value::getType(), I, llvm::Type::isVoidTy(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by promoteSingleBlockAlloca().
rewriteSingleStoreAlloca()
static bool rewriteSingleStoreAlloca (AllocaInst * AI, AllocaInfo & Info, LargeBlockInfo & LBI, const DataLayout & DL, DominatorTree & DT, AssumptionCache * AC) static
Rewrite as many loads as possible given a single store.
When there is only a single store, we can use the domtree to trivially replace all of the dominated loads with the stored value. Do so, and return true if this has successfully promoted the alloca entirely. If this returns false there were some loads which were not dominated by the single store and thus must be phi-ed with undef. We fall back to the standard alloca promotion algorithm in that case.
Definition at line 347 of file PromoteMemoryToRegister.cpp.
References addAssumeNonNull(), llvm::ConvertDebugDeclareToDebugValue(), llvm::DominatorTree::dominates(), E, llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::Instruction::getMetadata(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::isKnownNonZero(), llvm::Value::replaceAllUsesWith(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by promoteSingleBlockAlloca().
STATISTIC() [1/4]
STATISTIC (NumLocalPromoted , "Number of alloca's promoted within one block")
STATISTIC() [2/4]
STATISTIC (NumSingleStore , "Number of alloca's promoted with a single store")
STATISTIC() [3/4]
STATISTIC (NumDeadAlloca , "Number of dead alloca's removed")
STATISTIC() [4/4]
STATISTIC (NumPHIInsert , "Number of PHI nodes inserted")
updateForIncomingValueLocation()
static void updateForIncomingValueLocation (PHINode * PN, DebugLoc DL, bool ApplyMergedLoc) static
Update the debug location of a phi.
ApplyMergedLoc indicates whether to create a merged location incorporating DL, or to set DL directly.
Definition at line 863 of file PromoteMemoryToRegister.cpp.
References addAssumeNonNull(), llvm::Instruction::applyMergedLocation(), assert(), llvm::BasicBlock::begin(), llvm::ConvertDebugDeclareToDebugValue(), llvm::count(), llvm::dyn_cast(), E, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Instruction::getDebugLoc(), llvm::BasicBlock::getInstList(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isKnownNonZero(), llvm::Instruction::setDebugLoc(), SI, llvm::succ_begin(), and llvm::succ_end().