LLVM: lib/Transforms/ObjCARC/ProvenanceAnalysisEvaluator.cpp File Reference
ProvenanceAnalysisEvaluator.cpp File Reference
#include "ProvenanceAnalysis.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
Functions
static StringRef getName (Value *V)
static void insertIfNamed (SetVector< Value *> &Values, Value *V)
INITIALIZE_PASS_BEGIN (PAEval, "pa-eval", "Evaluate ProvenanceAnalysis on all pairs", false, true) INITIALIZE_PASS_END(PAEval
Variables
pa eval
pa Evaluate ProvenanceAnalysis on all pairs
pa Evaluate ProvenanceAnalysis on all false
Function Documentation
getName()
static StringRef getName (Value * V) static
Definition at line 41 of file ProvenanceAnalysisEvaluator.cpp.
References llvm::Value::getName(), Name, llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by addEdge(), llvm::VarInit::classof(), llvm::createBlockExtractorPass(), llvm::object::DelayImportDirectoryEntryRef::DelayImportDirectoryEntryRef(), EmitHiLo(), llvm::InstructionSelector::executeMatchTable(), llvm::CodeExtractor::findInputsOutputs(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), llvm::AArch64::getArchName(), llvm::ARM::getArchName(), llvm::VarInit::getAsString(), llvm::MachineBasicBlock::getBasicBlock(), llvm::DIScope::getFile(), llvm::MachineFunction::getFunction(), llvm::ItaniumPartialDemangler::getFunctionBaseName(), llvm::ItaniumPartialDemangler::getFunctionDeclContextName(), llvm::ItaniumPartialDemangler::getFunctionName(), llvm::orc::rpc::RPCTypeName< std::vector< T > >::getName(), llvm::orc::rpc::RPCTypeName< std::set< T > >::getName(), llvm::RegionBase< RegionTraits< Function > >::getNameStr(), llvm::NamedMDNode::getParent(), llvm::orc::rpc::Function< DerivedFunc, RetT(ArgTs...)>::getPrototype(), llvm::TargetRegisterInfo::getRegAsmName(), llvm::BTFTypeStruct::getSize(), llvm::Type::getStructName(), llvm::DWARFDie::getSubroutineName(), llvm::RawInstrProfReader< IntPtrT >::getSymtab(), llvm::StructType::hasName(), llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef(), insertIfNamed(), insertLifetimeMarkersSurroundingCall(), llvm::ItaniumPartialDemangler::isCtorOrDtor(), llvm::pdb::PDBSymbolFunc::isDestructor(), llvm::object::Elf_Sym_Impl< ELFT >::isExternal(), ObjCProtoName::isObjCObject(), LLVMDITypeGetName(), LLVMGetSectionName(), LLVMGetSymbolName(), maybePrintComdat(), llvm::orc::rpc::operator<<(), llvm::operator<<(), pathHasTraversal(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), llvm::Comdat::print(), llvm::StackSafetyInfo::FunctionInfo::print(), llvm::VPBlockBase::printAsOperand(), llvm::AVRMCExpr::printImpl(), promoteSingleBlockAlloca(), llvm::RuntimeDyldImpl::reassignSectionAddress(), llvm::StructType::setName(), shouldEmitUdt(), llvm::DISubprogram::splitFlags(), llvm::object::SymbolRef::SymbolRef(), llvm::DISubprogram::toSPFlags(), llvm::Function::viewCFG(), llvm::Function::viewCFGOnly(), llvm::SelectionDAG::viewGraph(), llvm::AMDGPULibFuncImpl::~AMDGPULibFuncImpl(), and llvm::orc::MaterializationUnit::~MaterializationUnit().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PAEval , "pa-eval" , "Evaluate ProvenanceAnalysis on all pairs" , false , true)
Referenced by llvm::createPAEvalPass().
insertIfNamed()
static void insertIfNamed (SetVector< Value *> & Values, Value * V) static
Definition at line 48 of file ProvenanceAnalysisEvaluator.cpp.
References Arg, llvm::Function::args(), E, llvm::errs(), F(), llvm::Module::getDataLayout(), getName(), llvm::GlobalValue::getParent(), llvm::Value::hasName(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::inst_begin(), llvm::inst_end(), llvm::objcarc::ProvenanceAnalysis::related(), runOnFunction(), llvm::objcarc::ProvenanceAnalysis::setAA(), and llvm::NVPTX::PTXLdStInstCode::V2.
Variable Documentation
eval
pa eval
Definition at line 93 of file ProvenanceAnalysisEvaluator.cpp.
false
pa Evaluate ProvenanceAnalysis on all false
Definition at line 93 of file ProvenanceAnalysisEvaluator.cpp.
pairs
pa Evaluate ProvenanceAnalysis on all pairs
Definition at line 93 of file ProvenanceAnalysisEvaluator.cpp.