LLVM: lib/Target/AMDGPU/R600MachineScheduler.cpp File Reference
R600MachineScheduler.cpp File Reference
R600 Machine Scheduler interface.
#include "R600MachineScheduler.h"
#include "AMDGPUSubtarget.h"
#include "R600InstrInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "machine-scheduler"
Functions
static unsigned getWFCountLimitedByGPR (unsigned GPRCount)
static bool isPhysicalRegCopy (MachineInstr *MI)
Detailed Description
R600 Machine Scheduler interface.
Definition in file R600MachineScheduler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 25 of file R600MachineScheduler.cpp.
Function Documentation
getWFCountLimitedByGPR()
static unsigned getWFCountLimitedByGPR (unsigned GPRCount) static
Definition at line 52 of file R600MachineScheduler.cpp.
References assert().
Referenced by llvm::R600SchedStrategy::pickNode().
isPhysicalRegCopy()
static bool isPhysicalRegCopy (MachineInstr * MI) static
Definition at line 182 of file R600MachineScheduler.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and llvm::Register::isVirtualRegister().
Referenced by llvm::R600SchedStrategy::releaseBottomNode().