LLVM: lib/CodeGen/ReachingDefAnalysis.cpp File Reference
ReachingDefAnalysis.cpp File Reference
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/ReachingDefAnalysis.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "reaching-deps-analysis"
Functions
INITIALIZE_PASS (ReachingDefAnalysis, DEBUG_TYPE, "ReachingDefAnalysis", false, true) void ReachingDefAnalysis
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "reaching-deps-analysis"
Definition at line 17 of file ReachingDefAnalysis.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ReachingDefAnalysis , DEBUG_TYPE , "ReachingDefAnalysis" , false , true)
Definition at line 20 of file ReachingDefAnalysis.cpp.
References assert(), llvm::dbgs(), llvm::numbers::e, llvm::MachineInstr::getDesc(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isDebugInstr(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MachineInstr::isVariadic(), llvm::MachineBasicBlock::liveins(), LLVM_DEBUG, llvm::max(), llvm::LoopTraversal::TraversedMBBInfo::MBB, MI, pred, llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::predecessors(), llvm::printMBBReference(), llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::size(), and TRI.