LLVM: lib/TableGen/Record.cpp File Reference
Record.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
#include <cassert>
#include <cstdint>
#include <memory>
#include <map>
#include <string>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "tblgen-records"
Functions
STATISTIC (CodeInitsConstructed, "The total number of unique CodeInits constructed")
static void ProfileRecordRecTy (FoldingSetNodeID &ID, ArrayRef< Record *> Classes)
static RecordRecTy * resolveRecordTypes (RecordRecTy *T1, RecordRecTy *T2)
static void ProfileBitsInit (FoldingSetNodeID &ID, ArrayRef< Init *> Range)
static bool canFitInBitfield (int64_t Value, unsigned NumBits)
static void ProfileListInit (FoldingSetNodeID &ID, ArrayRef< Init *> Range, RecTy *EltTy)
static void ProfileUnOpInit (FoldingSetNodeID &ID, unsigned Opcode, Init *Op, RecTy *Type)
static void ProfileBinOpInit (FoldingSetNodeID &ID, unsigned Opcode, Init *LHS, Init *RHS, RecTy *Type)
static StringInit * ConcatStringInits (const StringInit *I0, const StringInit *I1)
static ListInit * ConcatListInits (const ListInit *LHS, const ListInit *RHS)
static void ProfileTernOpInit (FoldingSetNodeID &ID, unsigned Opcode, Init *LHS, Init *MHS, Init *RHS, RecTy *Type)
static Init * ForeachApply (Init *LHS, Init *MHSe, Init *RHS, Record *CurRec)
static Init * ForeachDagApply (Init *LHS, DagInit *MHSd, Init *RHS, Record *CurRec)
static Init * ForeachHelper (Init *LHS, Init *MHS, Init *RHS, RecTy *Type, Record *CurRec)
static void ProfileFoldOpInit (FoldingSetNodeID &ID, Init *A, Init *B, Init *Start, Init *List, Init *Expr, RecTy *Type)
static void ProfileIsAOpInit (FoldingSetNodeID &ID, RecTy *CheckType, Init *Expr)
static void ProfileVarDefInit (FoldingSetNodeID &ID, Record *Class, ArrayRef< Init *> Args)
static void ProfileCondOpInit (FoldingSetNodeID &ID, ArrayRef< Init *> CondRange, ArrayRef< Init *> ValRange, const RecTy *ValType)
static void ProfileDagInit (FoldingSetNodeID &ID, Init *V, StringInit *VN, ArrayRef< Init *> ArgRange, ArrayRef< StringInit *> NameRange)
Variables
static BumpPtrAllocator Allocator
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tblgen-records"
Definition at line 42 of file Record.cpp.
Function Documentation
canFitInBitfield()
static bool canFitInBitfield (int64_t Value, unsigned NumBits) static
Definition at line 472 of file Record.cpp.
Referenced by llvm::IntInit::convertInitializerTo().
ConcatListInits()
static ListInit* ConcatListInits (const ListInit * LHS, const ListInit * RHS) static
Definition at line 876 of file Record.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::ListInit::begin(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ListInit::end(), llvm::ListInit::get(), llvm::ListInit::getElementType(), and llvm::SmallVectorImpl< T >::insert().
Referenced by llvm::BinOpInit::getListConcat().
ConcatStringInits()
static StringInit* ConcatStringInits (const StringInit * I0, const StringInit * I1) static
Definition at line 861 of file Record.cpp.
References Concat, llvm::StringInit::get(), and llvm::StringInit::getValue().
Referenced by llvm::BinOpInit::Fold(), and llvm::BinOpInit::getStrConcat().
ForeachApply()
static Init* ForeachApply (Init * LHS, Init * MHSe, Init * RHS, Record * CurRec) static
Definition at line 1110 of file Record.cpp.
References llvm::Init::resolveReferences(), and llvm::MapResolver::set().
Referenced by ForeachDagApply(), and ForeachHelper().
ForeachDagApply()
static Init* ForeachDagApply (Init * LHS, DagInit * MHSd, Init * RHS, Record * CurRec) static
Definition at line 1116 of file Record.cpp.
References Arg, ForeachApply(), llvm::DagInit::get(), llvm::DagInit::getArg(), llvm::DagInit::getArgName(), llvm::DagInit::getNumArgs(), llvm::DagInit::getOperator(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by ForeachHelper().
ForeachHelper()
static Init* ForeachHelper (Init * LHS, Init * MHS, Init * RHS, RecTy * Type, Record * CurRec) static
Definition at line 1145 of file Record.cpp.
References ForeachApply(), ForeachDagApply(), and llvm::ListInit::get().
Referenced by llvm::TernOpInit::Fold().
ProfileBinOpInit()
static void ProfileBinOpInit (FoldingSetNodeID & ID, unsigned Opcode, Init * LHS, Init * RHS, RecTy * Type) static
Definition at line 833 of file Record.cpp.
References llvm::FoldingSetNodeID::AddInteger(), and llvm::FoldingSetNodeID::AddPointer().
Referenced by llvm::BinOpInit::get(), and llvm::BinOpInit::Profile().
ProfileBitsInit()
static void ProfileBitsInit (FoldingSetNodeID & ID, ArrayRef< Init *> Range) static
Definition at line 335 of file Record.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::FoldingSetNodeID::AddPointer(), I, and llvm::ArrayRef< T >::size().
Referenced by llvm::BitsInit::get(), and llvm::BitsInit::Profile().
ProfileCondOpInit()
static void ProfileCondOpInit (FoldingSetNodeID & ID, ArrayRef< Init *> CondRange, ArrayRef< Init *> ValRange, const RecTy * ValType) static
Definition at line 1782 of file Record.cpp.
References llvm::FoldingSetNodeID::AddPointer(), assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), and llvm::ArrayRef< T >::size().
Referenced by llvm::CondOpInit::get(), and llvm::CondOpInit::Profile().
ProfileDagInit()
static void ProfileDagInit (FoldingSetNodeID & ID, Init * V, StringInit * VN, ArrayRef< Init *> ArgRange, ArrayRef< StringInit *> NameRange) static
Definition at line 1913 of file Record.cpp.
References llvm::FoldingSetNodeID::AddPointer(), Arg, assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), and Name.
Referenced by llvm::DagInit::get(), and llvm::DagInit::Profile().
ProfileFoldOpInit()
static void ProfileFoldOpInit (FoldingSetNodeID & ID, Init * A, Init * B, Init * Start, Init * List, Init * Expr, RecTy * Type) static
Definition at line 1297 of file Record.cpp.
Referenced by llvm::FoldOpInit::Profile().
ProfileIsAOpInit()
static void ProfileIsAOpInit (FoldingSetNodeID & ID, RecTy * CheckType, Init * Expr) static
Definition at line 1368 of file Record.cpp.
References llvm::FoldingSetNodeID::AddPointer().
Referenced by llvm::IsAOpInit::get(), and llvm::IsAOpInit::Profile().
ProfileListInit()
static void ProfileListInit (FoldingSetNodeID & ID, ArrayRef< Init *> Range, RecTy * EltTy) static
Definition at line 560 of file Record.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::FoldingSetNodeID::AddPointer(), I, and llvm::ArrayRef< T >::size().
Referenced by llvm::ListInit::get(), and llvm::ListInit::Profile().
ProfileRecordRecTy()
static void ProfileRecordRecTy (FoldingSetNodeID & ID, ArrayRef< Record *> Classes) static
Definition at line 150 of file Record.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::FoldingSetNodeID::AddPointer(), and llvm::ArrayRef< T >::size().
Referenced by llvm::RecordRecTy::get(), and llvm::RecordRecTy::Profile().
ProfileTernOpInit()
static void ProfileTernOpInit (FoldingSetNodeID & ID, unsigned Opcode, Init * LHS, Init * MHS, Init * RHS, RecTy * Type) static
Definition at line 1081 of file Record.cpp.
References llvm::FoldingSetNodeID::AddInteger(), and llvm::FoldingSetNodeID::AddPointer().
Referenced by llvm::TernOpInit::get(), and llvm::TernOpInit::Profile().
ProfileUnOpInit()
static void ProfileUnOpInit (FoldingSetNodeID & ID, unsigned Opcode, Init * Op, RecTy * Type) static
Definition at line 687 of file Record.cpp.
References llvm::FoldingSetNodeID::AddInteger(), and llvm::FoldingSetNodeID::AddPointer().
Referenced by llvm::UnOpInit::get(), and llvm::UnOpInit::Profile().
ProfileVarDefInit()
static void ProfileVarDefInit (FoldingSetNodeID & ID, Record * Class, ArrayRef< Init *> Args) static
Definition at line 1619 of file Record.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::FoldingSetNodeID::AddPointer(), I, and llvm::ArrayRef< T >::size().
Referenced by llvm::VarDefInit::get(), and llvm::VarDefInit::Profile().
resolveRecordTypes()
static RecordRecTy* resolveRecordTypes (RecordRecTy * T1, RecordRecTy * T2) static
Definition at line 242 of file Record.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), llvm::RecordRecTy::classes_begin(), llvm::RecordRecTy::classes_end(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::RecordRecTy::get(), llvm::Record::getDirectSuperClasses(), llvm::SmallVectorImpl< T >::insert(), llvm::RecordRecTy::isSubClassOf(), llvm::SmallVectorTemplateBase< T >::pop_back(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::resolveTypes().
STATISTIC()
STATISTIC (CodeInitsConstructed , "The total number of unique CodeInits constructed")
Variable Documentation
Allocator
BumpPtrAllocator Allocator static
Definition at line 44 of file Record.cpp.
Referenced by llvm::BitsRecTy::get(), llvm::IntInit::get(), llvm::StringInit::get(), llvm::CodeInit::get(), llvm::UnOpInit::get(), llvm::BinOpInit::get(), llvm::TernOpInit::get(), llvm::IsAOpInit::get(), llvm::VarInit::get(), llvm::VarBitInit::get(), llvm::VarListElementInit::get(), llvm::FieldInit::get(), llvm::Record::getDefInit(), and llvm::RecTy::getListTy().