LLVM: lib/CodeGen/RegAllocFast.cpp File Reference
RegAllocFast.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/IndexedMap.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/SparseSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Metadata.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <tuple>
#include <vector>
Macros
#define DEBUG_TYPE "regalloc"
Functions
STATISTIC (NumStores, "Number of stores added")
STATISTIC (NumLoads, "Number of loads added")
STATISTIC (NumCoalesced, "Number of copies coalesced")
INITIALIZE_PASS (RegAllocFast, "regallocfast", "Fast Register Allocator", false, false) void RegAllocFast
static bool isCoalescable (const MachineInstr &MI)
Variables
static RegisterRegAlloc fastRegAlloc ("fast", "fast register allocator", createFastRegisterAllocator)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regalloc"
Definition at line 53 of file RegAllocFast.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RegAllocFast , "regallocfast" , "Fast Register Allocator" , false , false)
Definition at line 239 of file RegAllocFast.cpp.
References llvm::MachineInstr::addRegisterKilled(), assert(), llvm::buildDbgValueForSpill(), C, llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::dbgs(), llvm::MachineRegisterInfo::def_instructions(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getSpillAlignment(), llvm::TargetRegisterInfo::getSpillSize(), I, llvm::Register::isPhysical(), llvm::MachineBasicBlock::isSuccessor(), llvm::MCRegisterInfo::isSuperRegister(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::MCRegAliasIterator::isValid(), llvm::Register::isVirtualRegister(), llvm::RegState::Kill, LLVM_DEBUG, LLVM_FALLTHROUGH, llvm_unreachable, llvm::TargetInstrInfo::loadRegFromStackSlot(), MI, llvm::MachineBasicBlock::pred_empty(), llvm::printReg(), llvm::MachineRegisterInfo::reg_nodbg_begin(), llvm::MachineRegisterInfo::reg_nodbg_end(), llvm::MachineRegisterInfo::reg_nodbg_instructions(), llvm::BitVector::set(), llvm::MachineOperand::setIsKill(), Size, llvm::X86AS::SS, llvm::TargetInstrInfo::storeRegToStackSlot(), llvm::MachineBasicBlock::succ_empty(), llvm::BitVector::test(), and llvm::Register::virtReg2Index().
isCoalescable()
static bool isCoalescable (const MachineInstr & MI) static
Definition at line 621 of file RegAllocFast.cpp.
References llvm::MachineRegisterInfo::addPhysRegsUsedFromRegMask(), llvm::MachineInstr::addRegisterDefined(), llvm::MachineInstr::addRegisterKilled(), assert(), llvm::MachineBasicBlock::begin(), C, llvm::IndexedMap< T, ToIndexT >::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::BitVector::clear(), llvm::TargetRegisterClass::contains(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::RegState::Dead, llvm::MachineRegisterInfo::def_instructions(), llvm::numbers::e, E, llvm::MachineInstr::emitError(), llvm::ArrayRef< T >::empty(), llvm::MachineInstr::findTiedOperandIdx(), llvm::MachineInstr::getDesc(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getName(), llvm::MCInstrDesc::getNumDefs(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::RegisterClassInfo::getOrder(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineOperand::getRegMask(), llvm::MachineOperand::getSubReg(), llvm::TargetRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), I, llvm::SmallSet< T, N, C >::insert(), llvm::MachineRegisterInfo::isAllocatable(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isCopyLike(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isEarlyClobber(), llvm::MachineInstr::isFullCopy(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isInlineAsm(), llvm::MachineOperand::isKill(), llvm::Register::isPhysical(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isTied(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::Register::isValid(), llvm::MCRegAliasIterator::isValid(), llvm::Register::isVirtual(), llvm::Register::isVirtualRegister(), llvm::MachineBasicBlock::liveins(), LLVM_DEBUG, MI, llvm::MachineInstr::operands(), llvm::printReg(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineInstr::readsVirtualRegister(), Reg, Register, llvm::IndexedMap< T, ToIndexT >::resize(), llvm::BitVector::resize(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsRenamable(), llvm::MachineOperand::setReg(), llvm::MachineOperand::setSubReg(), llvm::X86AS::SS, llvm::MCOI::TIED_TO, llvm::updateDbgValueForSpill(), llvm::MachineRegisterInfo::use_instr_nodbg_begin(), UseMI, and llvm::MachineInstr::uses().
STATISTIC() [1/3]
STATISTIC (NumStores , "Number of stores added")
STATISTIC() [2/3]
STATISTIC (NumLoads , "Number of loads added")
STATISTIC() [3/3]
STATISTIC (NumCoalesced , "Number of copies coalesced")
Variable Documentation
fastRegAlloc
RegisterRegAlloc fastRegAlloc("fast", "fast register allocator", createFastRegisterAllocator) static