LLVM: lib/CodeGen/RegUsageInfoCollector.cpp File Reference
RegUsageInfoCollector.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegisterUsageInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
Macros
#define DEBUG_TYPE "ip-regalloc"
Functions
STATISTIC (NumCSROpt, "Number of functions optimized for callee saved registers")
INITIALIZE_PASS_BEGIN (RegUsageInfoCollector, "RegUsageInfoCollector", "Register Usage Information Collector", false, false) INITIALIZE_PASS_END(RegUsageInfoCollector
static bool isCallableFunction (const MachineFunction &MF)
Variables
RegUsageInfoCollector
Register Usage Information Collector
Register Usage Information false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ip-regalloc"
Definition at line 33 of file RegUsageInfoCollector.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (RegUsageInfoCollector , "RegUsageInfoCollector" , "Register Usage Information Collector" , false , false)
isCallableFunction()
static bool isCallableFunction (const MachineFunction & MF) static
Definition at line 85 of file RegUsageInfoCollector.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::BitVector::clear(), llvm::MachineOperand::clobbersPhysReg(), llvm::dbgs(), llvm::MachineRegisterInfo::def_empty(), F(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::TargetFrameLowering::getCalleeSaves(), llvm::Function::getCallingConv(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::TargetRegisterInfo::getIntraCallClobberedRegs(), llvm::MachineFunction::getName(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineOperand::getRegMaskSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineRegisterInfo::getUsedPhysRegsMask(), llvm::TargetFrameLowering::isProfitableForNoCSROpt(), llvm::TargetFrameLowering::isSafeForNoCSROpt(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegAliasIterator::isValid(), LLVM_DEBUG, MRI, llvm::BitVector::none(), llvm::printReg(), Reg, llvm::BitVector::set(), llvm::PhysicalRegisterUsageInfo::setTargetMachine(), llvm::PhysicalRegisterUsageInfo::storeUpdateRegUsageInfo(), llvm::BitVector::test(), llvm::SystemZISD::TM, TRI, and llvm::Value::use_empty().
STATISTIC()
STATISTIC (NumCSROpt , "Number of functions optimized for callee saved registers")
Variable Documentation
Collector
Register Usage Information Collector
Definition at line 73 of file RegUsageInfoCollector.cpp.
Referenced by llvm::RegisterOperands::collect(), and llvm::FileCollector::writeMapping().
false
Register Usage Information false
Definition at line 73 of file RegUsageInfoCollector.cpp.
RegUsageInfoCollector
RegUsageInfoCollector
Definition at line 73 of file RegUsageInfoCollector.cpp.
Referenced by llvm::createRegUsageInfoCollector().