LLVM: lib/CodeGen/RegUsageInfoPropagate.cpp File Reference
RegUsageInfoPropagate.cpp File Reference
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegisterUsageInfo.h"
#include "llvm/IR/Module.h"
#include "llvm/PassAnalysisSupport.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <map>
#include <string>
Macros
#define DEBUG_TYPE "ip-regalloc"
#define RUIP_NAME "Register Usage Information Propagation"
Functions
INITIALIZE_PASS_BEGIN (RegUsageInfoPropagation, "reg-usage-propagation", RUIP_NAME, false, false) INITIALIZE_PASS_END(RegUsageInfoPropagation
static const Function * findCalledFunction (const Module &M, const MachineInstr &MI)
Variables
reg usage propagation
reg usage RUIP_NAME
reg usage false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ip-regalloc"
Definition at line 38 of file RegUsageInfoPropagate.cpp.
RUIP_NAME
#define RUIP_NAME "Register Usage Information Propagation"
Definition at line 40 of file RegUsageInfoPropagate.cpp.
Function Documentation
findCalledFunction()
static const Function* findCalledFunction (const Module & M, const MachineInstr & MI) static
Definition at line 88 of file RegUsageInfoPropagate.cpp.
References llvm::dbgs(), llvm::ArrayRef< T >::empty(), F(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getName(), llvm::GlobalValue::getParent(), llvm::PhysicalRegisterUsageInfo::getRegUsageInfo(), LLVM_DEBUG, and MI.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (RegUsageInfoPropagation , "reg-usage-propagation" , RUIP_NAME , false , false)
Variable Documentation
false
reg usage false
Definition at line 82 of file RegUsageInfoPropagate.cpp.
propagation
reg usage propagation
Definition at line 82 of file RegUsageInfoPropagate.cpp.
RUIP_NAME
reg usage RUIP_NAME
Definition at line 82 of file RegUsageInfoPropagate.cpp.