LLVM: lib/IR/RemarkStreamer.cpp File Reference
RemarkStreamer.cpp File Reference
#include "llvm/IR/RemarkStreamer.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Remarks/BitstreamRemarkSerializer.h"
#include "llvm/Remarks/RemarkFormat.h"
#include "llvm/Remarks/RemarkSerializer.h"
#include "llvm/Support/CommandLine.h"
Functions
static remarks::Type toRemarkType (enum DiagnosticKind Kind)
DiagnosticKind -> remarks::Type.
static Optional< remarks::RemarkLocation > toRemarkLocation (const DiagnosticLocation &DL)
DiagnosticLocation -> remarks::RemarkLocation.
Variables
static cl::opt< cl::boolOrDefault > EnableRemarksSection ("remarks-section", cl::desc("Emit a section containing remark diagnostics metadata. By default, " "this is enabled for the following formats: yaml-strtab, bitstream."), cl::init(cl::BOU_UNSET), cl::Hidden)
Function Documentation
toRemarkLocation()
static Optional<remarks::RemarkLocation> toRemarkLocation (const DiagnosticLocation & DL) static
DiagnosticLocation -> remarks::RemarkLocation.
Definition at line 73 of file RemarkStreamer.cpp.
References Arg, llvm::remarks::Remark::Args, llvm::GlobalValue::dropLLVMManglingEscape(), File, llvm::remarks::Remark::FunctionName, llvm::DiagnosticInfoOptimizationBase::getArgs(), llvm::DiagnosticLocation::getColumn(), llvm::DiagnosticInfoWithLocationBase::getFunction(), llvm::DiagnosticInfoOptimizationBase::getHotness(), llvm::DiagnosticInfo::getKind(), llvm::DiagnosticLocation::getLine(), llvm::DiagnosticInfoWithLocationBase::getLocation(), llvm::Value::getName(), llvm::DiagnosticInfoOptimizationBase::getPassName(), llvm::DiagnosticLocation::getRelativePath(), llvm::DiagnosticInfoOptimizationBase::getRemarkName(), llvm::remarks::Remark::Hotness, llvm::DiagnosticLocation::isValid(), llvm::remarks::Remark::Loc, llvm::None, llvm::remarks::Remark::PassName, llvm::remarks::Remark::RemarkName, llvm::remarks::Remark::RemarkType, and toRemarkType().
toRemarkType()
static remarks::Type toRemarkType (enum DiagnosticKind Kind) static
DiagnosticKind -> remarks::Type.
Definition at line 49 of file RemarkStreamer.cpp.
References llvm::remarks::Analysis, llvm::remarks::AnalysisAliasing, llvm::remarks::AnalysisFPCommute, llvm::DK_MachineOptimizationRemark, llvm::DK_MachineOptimizationRemarkAnalysis, llvm::DK_MachineOptimizationRemarkMissed, llvm::DK_OptimizationFailure, llvm::DK_OptimizationRemark, llvm::DK_OptimizationRemarkAnalysis, llvm::DK_OptimizationRemarkAnalysisAliasing, llvm::DK_OptimizationRemarkAnalysisFPCommute, llvm::DK_OptimizationRemarkMissed, llvm::remarks::Failure, llvm::remarks::Missed, llvm::remarks::Passed, and llvm::remarks::Unknown.
Referenced by toRemarkLocation().
Variable Documentation
EnableRemarksSection
cl::opt<cl::boolOrDefault> EnableRemarksSection("remarks-section", cl::desc("Emit a section containing remark diagnostics metadata. By default, " "this is enabled for the following formats: yaml-strtab, bitstream."), cl::init(cl::BOU_UNSET), cl::Hidden) static
Referenced by llvm::RemarkStreamer::needsSection().