LLVM: lib/CodeGen/RenameIndependentSubregs.cpp File Reference
RenameIndependentSubregs.cpp File Reference
#include "LiveRangeUtils.h"
#include "PHIEliminationUtils.h"
#include "llvm/CodeGen/LiveInterval.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "rename-independent-subregs"
Functions
INITIALIZE_PASS_BEGIN (RenameIndependentSubregs, DEBUG_TYPE, "Rename Independent Subregisters", false, false) INITIALIZE_PASS_END(RenameIndependentSubregs
static bool subRangeLiveAt (const LiveInterval &LI, SlotIndex Pos)
Variables
DEBUG_TYPE
Rename Independent Subregisters
Rename Independent false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "rename-independent-subregs"
Definition at line 42 of file RenameIndependentSubregs.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (RenameIndependentSubregs , DEBUG_TYPE , "Rename Independent Subregisters" , false , false)
subRangeLiveAt()
static bool subRangeLiveAt (const LiveInterval & LI, SlotIndex Pos) static
Definition at line 291 of file RenameIndependentSubregs.cpp.
References Allocator, llvm::BuildMI(), llvm::LiveRange::clear(), llvm::dbgs(), llvm::tgtok::Def, llvm::VNInfo::def, E, llvm::findPHICopyInsertPoint(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::SlotIndexes::getMBBEndIdx(), llvm::SlotIndexes::getMBBFromIndex(), llvm::MachineFunction::getName(), llvm::SlotIndex::getPrevSlot(), llvm::MachineFunction::getRegInfo(), llvm::SlotIndex::getRegSlot(), llvm::MachineFunction::getSubtarget(), llvm::LiveInterval::hasSubRanges(), I, llvm::Register::index2VirtReg(), llvm::VNInfo::isPHIDef(), llvm::VNInfo::isUnused(), LLVM_DEBUG, MRI, llvm::MachineBasicBlock::predecessors(), llvm::LiveInterval::reg, Reg, llvm::LiveInterval::removeEmptySubRanges(), llvm::SmallVectorBase::size(), llvm::LiveInterval::subranges(), and TII.
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 119 of file RenameIndependentSubregs.cpp.
false
Rename Independent false
Definition at line 119 of file RenameIndependentSubregs.cpp.
Subregisters
Rename Independent Subregisters
Definition at line 119 of file RenameIndependentSubregs.cpp.