LLVM: lib/Target/RISCV/RISCVTargetMachine.cpp File Reference
RISCVTargetMachine.cpp File Reference
#include "RISCVTargetMachine.h"
#include "RISCV.h"
#include "RISCVTargetObjectFile.h"
#include "RISCVTargetTransformInfo.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "Utils/RISCVBaseInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/GlobalISel/IRTranslator.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/GlobalISel/Legalizer.h"
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTarget ()
static StringRef computeDataLayout (const Triple &TT)
static Reloc::Model getEffectiveRelocModel (const Triple &TT, Optional< Reloc::Model > RM)
Function Documentation
computeDataLayout()
static StringRef computeDataLayout (const Triple & TT) static
Definition at line 43 of file RISCVTargetMachine.cpp.
References assert(), llvm::Triple::isArch32Bit(), and llvm::Triple::isArch64Bit().
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (const Triple & TT, Optional< Reloc::Model > RM) static
Definition at line 52 of file RISCVTargetMachine.cpp.
References llvm::Optional< T >::hasValue(), llvm::NVPTX::PTXCvtMode::RM, and llvm::Reloc::Static.
LLVMInitializeRISCVTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTarget ()
Definition at line 35 of file RISCVTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), llvm::initializeGlobalISel(), llvm::initializeRISCVExpandPseudoPass(), X, and Y.