LLVM: lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp File Reference
RISCVAsmParser.cpp File Reference
#include "MCTargetDesc/RISCVAsmBackend.h"
#include "MCTargetDesc/RISCVMCExpr.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "MCTargetDesc/RISCVTargetStreamer.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "Utils/RISCVBaseInfo.h"
#include "Utils/RISCVMatInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/CodeGen/Register.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include <limits>
#include "RISCVGenCompressInstEmitter.inc"
#include "RISCVGenAsmMatcher.inc"
Macros
#define DEBUG_TYPE "riscv-asm-parser"
#define GEN_COMPRESS_INSTR
#define GET_ASSEMBLER_HEADER
#define GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_REGISTER_MATCHER
#define GET_SUBTARGET_FEATURE_NAME
#define GET_MATCHER_IMPLEMENTATION
#define GET_MNEMONIC_SPELL_CHECKER
Functions
STATISTIC (RISCVNumInstrsCompressed, "Number of RISC-V Compressed instructions emitted")
static Register convertFPR64ToFPR32 (Register Reg)
static std::string RISCVMnemonicSpellCheck (StringRef S, const FeatureBitset &FBS, unsigned VariantID=0)
static bool matchRegisterNameHelper (bool IsRV32E, Register &RegNo, StringRef Name)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVAsmParser ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-asm-parser"
Definition at line 41 of file RISCVAsmParser.cpp.
GEN_COMPRESS_INSTR
#define GEN_COMPRESS_INSTR
Definition at line 44 of file RISCVAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 129 of file RISCVAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 766 of file RISCVAsmParser.cpp.
GET_MNEMONIC_SPELL_CHECKER
#define GET_MNEMONIC_SPELL_CHECKER
Definition at line 767 of file RISCVAsmParser.cpp.
GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_OPERAND_DIAGNOSTIC_TYPES
Definition at line 180 of file RISCVAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 764 of file RISCVAsmParser.cpp.
GET_SUBTARGET_FEATURE_NAME
#define GET_SUBTARGET_FEATURE_NAME
Definition at line 765 of file RISCVAsmParser.cpp.
Function Documentation
convertFPR64ToFPR32()
static Register convertFPR64ToFPR32 (Register Reg) static
Definition at line 770 of file RISCVAsmParser.cpp.
References llvm::FeatureBitset::any(), assert(), llvm::numbers::e, llvm::Error, getSubtargetFeatureName(), llvm::getToken(), llvm_unreachable, llvm::Lower, llvm::max(), Operands, Reg, RISCVMnemonicSpellCheck(), llvm::SmallVectorBase::size(), llvm::FeatureBitset::size(), and llvm::Upper.
LLVMInitializeRISCVAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVAsmParser ()
Definition at line 1888 of file RISCVAsmParser.cpp.
References llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), X, and Y.
matchRegisterNameHelper()
static bool matchRegisterNameHelper (bool IsRV32E, Register & RegNo, StringRef Name) static
Definition at line 996 of file RISCVAsmParser.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCInstBuilder::addImm(), addOperand(), llvm::MCInstBuilder::addReg(), assert(), llvm::AsmToken::Comma, llvm::StringRef::consume_back(), llvm::RISCVMCExpr::create(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::create(), llvm::MCContext::createTempSymbol(), llvm::AsmToken::Dot, llvm::dyn_cast(), E, llvm::MCAsmParser::eatToEndOfStatement(), llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitLabel(), llvm::AsmToken::EndOfStatement, llvm::Error, llvm::AsmToken::Exclaim, llvm::X86ISD::FLD, llvm::RISCVMatInt::generateInstSeq(), llvm::MCStreamer::getContext(), llvm::AsmToken::getEndLoc(), llvm::MCOperand::getExpr(), llvm::SMLoc::getFromPointer(), llvm::AsmToken::getIdentifier(), llvm::MCOperand::getImm(), llvm::MCBinaryExpr::getLHS(), llvm::AsmToken::getLoc(), llvm::MCInst::getOpcode(), llvm::MCBinaryExpr::getOpcode(), llvm::MCInst::getOperand(), llvm::SMLoc::getPointer(), llvm::MCOperand::getReg(), llvm::MCBinaryExpr::getRHS(), llvm::AsmToken::getString(), llvm::MCAsmParser::getTok(), llvm::MCConstantExpr::getValue(), llvm::MCSymbol::getVariableValue(), llvm::RISCVMCExpr::getVariantKindForName(), llvm::AsmToken::Identifier, llvm::object::Identifier, Info, llvm::AsmToken::Integer, llvm::MCOperand::isExpr(), llvm::AsmToken::isNot(), llvm::MCOperand::isReg(), llvm::MCSymbol::isVariable(), llvm::ARM_MB::LD, llvm::MCAsmParser::Lex(), llvm::AArch64SysReg::lookupSysRegByEncoding(), llvm::AArch64SysReg::lookupSysRegByName(), llvm::AsmToken::LParen, llvm::MatchOperand_NoMatch, llvm::MatchOperand_ParseFail, llvm::MatchOperand_Success, MatchRegisterAltName(), MatchRegisterName(), llvm::AsmToken::Minus, Name, parseImmediate(), llvm::AsmToken::Percent, llvm::AsmToken::Plus, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::AsmToken::RParen, llvm::RISCVAsmBackend::setForceRelocs(), llvm::MCInst::setLoc(), llvm::AsmToken::String, llvm::MCBinaryExpr::Sub, llvm::ARMBuildAttrs::Symbol, llvm::AsmToken::Tilde, llvm::MCSymbolRefExpr::VK_None, llvm::RISCVMCExpr::VK_RISCV_CALL, llvm::RISCVMCExpr::VK_RISCV_CALL_PLT, llvm::RISCVMCExpr::VK_RISCV_GOT_HI, llvm::RISCVMCExpr::VK_RISCV_Invalid, llvm::RISCVMCExpr::VK_RISCV_None, llvm::RISCVMCExpr::VK_RISCV_PCREL_HI, llvm::RISCVMCExpr::VK_RISCV_PCREL_LO, llvm::RISCVMCExpr::VK_RISCV_TLS_GD_HI, llvm::RISCVMCExpr::VK_RISCV_TLS_GOT_HI, and llvm::Warning.
RISCVMnemonicSpellCheck()
static std::string RISCVMnemonicSpellCheck (StringRef S, const FeatureBitset & FBS, unsigned VariantID = 0) static
Referenced by convertFPR64ToFPR32().
STATISTIC()
STATISTIC (RISCVNumInstrsCompressed , "Number of RISC-V Compressed instructions emitted")