LLVM: lib/Target/RISCV/RISCVMergeBaseOffset.cpp File Reference
RISCVMergeBaseOffset.cpp File Reference
#include "RISCV.h"
#include "RISCVTargetMachine.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
#include <set>
Macros
#define DEBUG_TYPE "riscv-merge-base-offset"
#define RISCV_MERGE_BASE_OFFSET_NAME "RISCV Merge Base Offset"
Functions
INITIALIZE_PASS (RISCVMergeBaseOffsetOpt, "riscv-merge-base-offset", RISCV_MERGE_BASE_OFFSET_NAME, false, false) bool RISCVMergeBaseOffsetOpt
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-merge-base-offset"
Definition at line 35 of file RISCVMergeBaseOffset.cpp.
RISCV_MERGE_BASE_OFFSET_NAME
#define RISCV_MERGE_BASE_OFFSET_NAME "RISCV Merge Base Offset"
Definition at line 36 of file RISCVMergeBaseOffset.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVMergeBaseOffsetOpt , "riscv-merge-base-offset" , RISCV_MERGE_BASE_OFFSET_NAME , false , false)
Definition at line 67 of file RISCVMergeBaseOffset.cpp.
References llvm::ISD::ADD, assert(), llvm::dbgs(), llvm::X86ISD::FLD, llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getTargetFlags(), llvm::ARM_MB::LD, LLVM_DEBUG, MI, llvm::MachineOperand::MO_GlobalAddress, llvm::RISCVII::MO_HI, llvm::RISCVII::MO_LO, llvm::RISCVII::MO_None, MRI, Reg, llvm::MachineOperand::setOffset(), and llvm::CallingConv::Tail.