LLVM: lib/Target/RISCV/RISCVISelDAGToDAG.cpp File Reference
RISCVISelDAGToDAG.cpp File Reference
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "RISCV.h"
#include "RISCVTargetMachine.h"
#include "Utils/RISCVMatInt.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "RISCVGenDAGISel.inc"
Macros
#define DEBUG_TYPE "riscv-isel"
Functions
static SDNode * selectImm (SelectionDAG *CurDAG, const SDLoc &DL, int64_t Imm, MVT XLenVT)
static bool isConstantMask (SDNode *Node, uint64_t &Mask)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-isel"
Definition at line 24 of file RISCVISelDAGToDAG.cpp.
Function Documentation
isConstantMask()
static bool isConstantMask (SDNode * Node, uint64_t & Mask) static
Definition at line 89 of file RISCVISelDAGToDAG.cpp.
selectImm()
static SDNode* selectImm (SelectionDAG * CurDAG, const SDLoc & DL, int64_t Imm, MVT XLenVT) static
Definition at line 66 of file RISCVISelDAGToDAG.cpp.
References llvm::RISCVMatInt::generateInstSeq(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), and llvm::MVT::i64.