LLVM: lib/Target/RISCV/Disassembler/RISCVDisassembler.cpp File Reference
RISCVDisassembler.cpp File Reference
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "Utils/RISCVBaseInfo.h"
#include "llvm/CodeGen/Register.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/TargetRegistry.h"
#include "RISCVGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "riscv-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
static MCDisassembler * createRISCVDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFPR32RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFPR32CRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFPR64RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFPR64CRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRNoX0RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRNoX0X2RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static void addImplySP (MCInst &Inst, int64_t Address, const void *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const void *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmNonZeroOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const void *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const void *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmNonZeroOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const void *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperandAndLsl1 (MCInst &Inst, uint64_t Imm, int64_t Address, const void *Decoder)
static DecodeStatus decodeCLUIImmOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const void *Decoder)
static DecodeStatus decodeFRMArg (MCInst &Inst, uint64_t Imm, int64_t Address, const void *Decoder)
static DecodeStatus decodeRVCInstrSImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodeRVCInstrRdSImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodeRVCInstrRdRs1UImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodeRVCInstrRdRs2 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus decodeRVCInstrRdRs1Rs2 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-disassembler"
Definition at line 28 of file RISCVDisassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 30 of file RISCVDisassembler.cpp.
Function Documentation
addImplySP()
static void addImplySP (MCInst & Inst, int64_t Address, const void * Decoder) static
Definition at line 153 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCInst::getOpcode().
Referenced by decodeSImmOperand(), and decodeUImmOperand().
createRISCVDisassembler()
static MCDisassembler* createRISCVDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 45 of file RISCVDisassembler.cpp.
Referenced by LLVMInitializeRISCVDisassembler().
decodeCLUIImmOperand()
static DecodeStatus decodeCLUIImmOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const void * Decoder) static
Definition at line 218 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeFPR32CRegisterClass()
static DecodeStatus DecodeFPR32CRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 87 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR32RegisterClass()
static DecodeStatus DecodeFPR32RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 76 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR64CRegisterClass()
static DecodeStatus DecodeFPR64CRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 109 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR64RegisterClass()
static DecodeStatus DecodeFPR64RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 98 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
decodeFRMArg()
static DecodeStatus decodeFRMArg (MCInst & Inst, uint64_t Imm, int64_t Address, const void * Decoder) static
Definition at line 229 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, assert(), llvm::MCOperand::createImm(), decodeRVCInstrRdRs1Rs2(), decodeRVCInstrRdRs1UImm(), decodeRVCInstrRdRs2(), decodeRVCInstrRdSImm(), decodeRVCInstrSImm(), llvm::MCDisassembler::Fail, llvm::RISCVFPRndMode::isValidRoundingMode(), and llvm::MCDisassembler::Success.
DecodeGPRCRegisterClass()
static DecodeStatus DecodeGPRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 140 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeGPRNoX0RegisterClass()
static DecodeStatus DecodeGPRNoX0RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 120 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by DecodeGPRNoX0X2RegisterClass().
DecodeGPRNoX0X2RegisterClass()
static DecodeStatus DecodeGPRNoX0X2RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 130 of file RISCVDisassembler.cpp.
References DecodeGPRNoX0RegisterClass(), and llvm::MCDisassembler::Fail.
DecodeGPRRegisterClass()
static DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 59 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by addImplySP(), DecodeGPRNoX0RegisterClass(), decodeRVCInstrRdRs1Rs2(), decodeRVCInstrRdRs1UImm(), decodeRVCInstrRdRs2(), and decodeRVCInstrRdSImm().
decodeRVCInstrRdRs1Rs2()
static DecodeStatus decodeRVCInstrRdRs1Rs2 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 303 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::ArrayRef< T >::data(), llvm::dbgs(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOperand(), LLVM_DEBUG, MI, llvm::support::endian::read16le(), llvm::support::endian::read32le(), Size, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.
Referenced by decodeFRMArg().
decodeRVCInstrRdRs1UImm()
static DecodeStatus decodeRVCInstrRdRs1UImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 281 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, assert(), DecodeGPRRegisterClass(), llvm::MCInst::getOperand(), and llvm::MCDisassembler::Success.
Referenced by decodeFRMArg().
decodeRVCInstrRdRs2()
static DecodeStatus decodeRVCInstrRdRs2 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 294 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by decodeFRMArg().
decodeRVCInstrRdSImm()
static DecodeStatus decodeRVCInstrRdSImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 269 of file RISCVDisassembler.cpp.
References llvm::Address, assert(), DecodeGPRRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by decodeFRMArg().
decodeRVCInstrSImm()
static DecodeStatus decodeRVCInstrSImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 259 of file RISCVDisassembler.cpp.
References llvm::Address, assert(), and llvm::MCDisassembler::Success.
Referenced by decodeFRMArg().
decodeSImmNonZeroOperand()
template<unsigned N> static DecodeStatus decodeSImmNonZeroOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const void * Decoder) static
Definition at line 198 of file RISCVDisassembler.cpp.
References llvm::Address, and llvm::MCDisassembler::Fail.
decodeSImmOperand()
template<unsigned N> static DecodeStatus decodeSImmOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const void * Decoder) static
Definition at line 188 of file RISCVDisassembler.cpp.
References addImplySP(), llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
decodeSImmOperandAndLsl1()
template<unsigned N> static DecodeStatus decodeSImmOperandAndLsl1 (MCInst & Inst, uint64_t Imm, int64_t Address, const void * Decoder) static
Definition at line 207 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
decodeUImmNonZeroOperand()
template<unsigned N> static DecodeStatus decodeUImmNonZeroOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const void * Decoder) static
Definition at line 179 of file RISCVDisassembler.cpp.
References llvm::Address, and llvm::MCDisassembler::Fail.
decodeUImmOperand()
template<unsigned N> static DecodeStatus decodeUImmOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const void * Decoder) static
Definition at line 170 of file RISCVDisassembler.cpp.
References addImplySP(), llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
LLVMInitializeRISCVDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
Definition at line 51 of file RISCVDisassembler.cpp.
References createRISCVDisassembler(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), and llvm::TargetRegistry::RegisterMCDisassembler().