LLVM: lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp File Reference
RuntimeDyldELF.cpp File Reference
#include "RuntimeDyldELF.h"
#include "RuntimeDyldCheckerImpl.h"
#include "Targets/RuntimeDyldELFMips.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/MemoryBuffer.h"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "dyld"
Functions
static void or32le (void *P, int32_t V)
static void or32AArch64Imm (void *L, uint64_t Imm)
template<class T >
static void write (bool isBE, void *P, T V)
static void write32AArch64Addr (void *L, uint64_t Imm)
static uint64_t getBits (uint64_t Val, int Start, int End)
static uint16_t llvm::applyPPClo (uint64_t value)
static uint16_t llvm::applyPPChi (uint64_t value)
static uint16_t llvm::applyPPCha (uint64_t value)
static uint16_t llvm::applyPPChigher (uint64_t value)
static uint16_t llvm::applyPPChighera (uint64_t value)
static uint16_t llvm::applyPPChighest (uint64_t value)
static uint16_t llvm::applyPPChighesta (uint64_t value)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dyld"
Definition at line 29 of file RuntimeDyldELF.cpp.
Function Documentation
getBits()
static uint64_t getBits (uint64_t Val, int Start, int End) static
Definition at line 50 of file RuntimeDyldELF.cpp.
Referenced by llvm::RuntimeDyldELF::loadObject().
or32AArch64Imm()
static void or32AArch64Imm (void * L, uint64_t Imm) static
Definition at line 33 of file RuntimeDyldELF.cpp.
References llvm::or32le().
Referenced by llvm::RuntimeDyldELF::loadObject().
or32le()
static void or32le (void * P, int32_t V) static
Definition at line 31 of file RuntimeDyldELF.cpp.
References llvm::support::endian::read32le(), and llvm::support::endian::write32le().
write()
template<class T > static void write (bool isBE, void * P, T V) static
Definition at line 37 of file RuntimeDyldELF.cpp.
References P.
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::applyPPChighesta(), llvm::R600InstrInfo::buildIndirectRead(), llvm::R600InstrInfo::buildIndirectWrite(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), getFilename(), llvm::R600InstrInfo::getFlagOp(), llvm::vfs::YAMLVFSWriter::getMappings(), getSlotedOps(), isIFunc(), llvm::RuntimeDyldELF::loadObject(), llvm::raw_ostream::operator<<(), llvm::ProfOStream::patch(), llvm::report_bad_alloc_error(), llvm::report_fatal_error(), llvm::sampleprof::ProfileSymbolList::toCompress(), llvm::msgpack::Writer::write(), llvm::WriteBitcodeToFile(), writeIdentificationBlock(), and llvm::WriteIndexToFile().
write32AArch64Addr()
static void write32AArch64Addr (void * L, uint64_t Imm) static
Definition at line 41 of file RuntimeDyldELF.cpp.
References llvm::BitmaskEnumDetail::Mask(), llvm::support::endian::read32le(), and llvm::support::endian::write32le().