LLVM: lib/CodeGen/SafeStackLayout.cpp File Reference
SafeStackLayout.cpp File Reference
#include "SafeStackLayout.h"
#include "SafeStackColoring.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
Macros
#define DEBUG_TYPE "safestacklayout"
Functions
static unsigned AdjustStackOffset (unsigned Offset, unsigned Size, unsigned Alignment)
Variables
static cl::opt< bool > ClLayout ("safe-stack-layout", cl::desc("enable safe stack layout"), cl::Hidden, cl::init(true))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "safestacklayout"
Definition at line 23 of file SafeStackLayout.cpp.
Function Documentation
AdjustStackOffset()
static unsigned AdjustStackOffset (unsigned Offset, unsigned Size, unsigned Alignment) static
Definition at line 48 of file SafeStackLayout.cpp.
References llvm::alignTo(), llvm::SmallVectorTemplateCommon< T, typename >::back(), ClLayout, llvm::SmallVectorBase::empty(), and Size.
Variable Documentation
ClLayout
cl::opt<bool> ClLayout("safe-stack-layout", cl::desc("enable safe stack layout"), cl::Hidden, cl::init(true)) static
Referenced by AdjustStackOffset().