LLVM: lib/Support/ScaledNumber.cpp File Reference
ScaledNumber.cpp File Reference
#include "llvm/Support/ScaledNumber.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Functions
static uint64_t getHalf (uint64_t N)
static void appendDigit (std::string &Str, unsigned D)
static void appendNumber (std::string &Str, uint64_t N)
static bool doesRoundUp (char Digit)
static std::string toStringAPFloat (uint64_t D, int E, unsigned Precision)
static std::string stripTrailingZeros (const std::string &Float)
Function Documentation
appendDigit()
static void appendDigit (std::string & Str, unsigned D) static
Definition at line 137 of file ScaledNumber.cpp.
References assert().
Referenced by appendNumber(), and llvm::ScaledNumberBase::toString().
appendNumber()
static void appendNumber (std::string & Str, uint64_t N) static
Definition at line 142 of file ScaledNumber.cpp.
References appendDigit().
Referenced by llvm::ScaledNumberBase::toString().
doesRoundUp()
static bool doesRoundUp (char Digit) static
Definition at line 149 of file ScaledNumber.cpp.
Referenced by llvm::ScaledNumberBase::toString().
getHalf()
static uint64_t getHalf (uint64_t N) static
Definition at line 55 of file ScaledNumber.cpp.
Referenced by llvm::ScaledNumbers::divide32(), and llvm::ScaledNumbers::divide64().
stripTrailingZeros()
static std::string stripTrailingZeros (const std::string & Float) static
Definition at line 191 of file ScaledNumber.cpp.
References assert().
Referenced by llvm::ScaledNumberBase::toString().
toStringAPFloat()
static std::string toStringAPFloat (uint64_t D, int E, unsigned Precision) static
Definition at line 162 of file ScaledNumber.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ScaledNumberBase::countLeadingZeros64(), D, E, llvm::SmallVectorTemplateCommon< T >::end(), llvm::NVPTX::PTXLdStInstCode::Float, llvm::ScaledNumbers::MaxScale, llvm::ScaledNumbers::MinScale, llvm::APFloat::toString(), and llvm::APFloatBase::x87DoubleExtended().
Referenced by llvm::ScaledNumberBase::toString().