LLVM: lib/Analysis/ScopedNoAliasAA.cpp File Reference
ScopedNoAliasAA.cpp File Reference
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
Functions
static void collectMDInDomain (const MDNode *List, const MDNode *Domain, SmallPtrSetImpl< const MDNode *> &Nodes)
INITIALIZE_PASS (ScopedNoAliasAAWrapperPass, "scoped-noalias", "Scoped NoAlias Alias Analysis", false, true) ImmutablePass *llvm
Variables
static cl::opt< bool > EnableScopedNoAlias ("enable-scoped-noalias", cl::init(true), cl::Hidden)
Function Documentation
collectMDInDomain()
static void collectMDInDomain (const MDNode * List, const MDNode * Domain, SmallPtrSetImpl< const MDNode *> & Nodes) static
Definition at line 133 of file ScopedNoAliasAA.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallPtrSetImplBase::empty(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::NoAlias, and llvm::MDNode::operands().
INITIALIZE_PASS()
INITIALIZE_PASS (ScopedNoAliasAAWrapperPass , "scoped-noalias" , "Scoped NoAlias Alias Analysis" , false , true)
Definition at line 188 of file ScopedNoAliasAA.cpp.
Variable Documentation
EnableScopedNoAlias
cl::opt<bool> EnableScopedNoAlias("enable-scoped-noalias", cl::init(true), cl::Hidden) static
Referenced by llvm::ScopedNoAliasAAResult::alias(), and llvm::ScopedNoAliasAAResult::getModRefInfo().