LLVM: lib/CodeGen/SelectionDAG/SelectionDAGAddressAnalysis.cpp File Reference
SelectionDAGAddressAnalysis.cpp File Reference
#include "llvm/CodeGen/SelectionDAGAddressAnalysis.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include <cstdint>
Functions
static BaseIndexOffset matchLSNode (const LSBaseSDNode *N, const SelectionDAG &DAG)
Parses tree in Ptr for base, index, offset addresses.
Function Documentation
matchLSNode()
static BaseIndexOffset matchLSNode (const LSBaseSDNode * N, const SelectionDAG & DAG) static
Parses tree in Ptr for base, index, offset addresses.
Definition at line 167 of file SelectionDAGAddressAnalysis.cpp.
References llvm::ISD::ADD, llvm::BaseIndexOffset::BaseIndexOffset(), C, llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getBasePtr(), llvm::SDValue::getNode(), llvm::LSBaseSDNode::getOffset(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::ISD::LOAD, llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::POST_DEC, llvm::ISD::PRE_DEC, llvm::ISD::PRE_INC, llvm::ISD::SIGN_EXTEND, llvm::ISD::STORE, and llvm::TargetLowering::unwrapAddress().
Referenced by llvm::BaseIndexOffset::match().