LLVM: lib/CodeGen/ShrinkWrap.cpp File Reference
ShrinkWrap.cpp File Reference
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineOptimizationRemarkEmitter.h"
#include "llvm/CodeGen/MachinePostDominators.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <cstdint>
#include <memory>
Macros
#define DEBUG_TYPE "shrink-wrap"
Functions
STATISTIC (NumFunc, "Number of functions")
STATISTIC (NumCandidates, "Number of shrink-wrapping candidates")
STATISTIC (NumCandidatesDropped, "Number of shrink-wrapping candidates dropped because of frequency")
template<typename ListOfBBs , typename DominanceAnalysis >
static MachineBasicBlock * FindIDom (MachineBasicBlock &Block, ListOfBBs BBs, DominanceAnalysis &Dom)
Helper function to find the immediate (post) dominator.
static bool giveUpWithRemarks (MachineOptimizationRemarkEmitter *ORE, StringRef RemarkName, StringRef RemarkMessage, const DiagnosticLocation &Loc, const MachineBasicBlock *MBB)
Variables
static cl::opt< cl::boolOrDefault > EnableShrinkWrapOpt ("enable-shrink-wrap", cl::Hidden, cl::desc("enable the shrink-wrapping pass"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "shrink-wrap"
Definition at line 90 of file ShrinkWrap.cpp.
Referenced by giveUpWithRemarks().
Function Documentation
FindIDom()
template<typename ListOfBBs , typename DominanceAnalysis > static MachineBasicBlock* FindIDom (MachineBasicBlock & Block, ListOfBBs BBs, DominanceAnalysis & Dom) static
Helper function to find the immediate (post) dominator.
Definition at line 314 of file ShrinkWrap.cpp.
References llvm::dbgs(), llvm::MachineDominatorTree::dominates(), llvm::MachineDominatorTree::findNearestCommonDominator(), LLVM_DEBUG, llvm::MachineBasicBlock::succ_empty(), llvm::MachineBasicBlock::successors(), llvm::MCID::Terminator, and llvm::MachineBasicBlock::terminators().
giveUpWithRemarks()
static bool giveUpWithRemarks (MachineOptimizationRemarkEmitter * ORE, StringRef RemarkName, StringRef RemarkMessage, const DiagnosticLocation & Loc, const MachineBasicBlock * MBB) static
Definition at line 450 of file ShrinkWrap.cpp.
References assert(), llvm::MachineFunction::begin(), llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, llvm::TargetFrameLowering::canUseAsEpilogue(), llvm::TargetFrameLowering::canUseAsPrologue(), llvm::dbgs(), DEBUG_TYPE, llvm::MachineOptimizationRemarkEmitter::emit(), llvm::MachineFunction::empty(), EnableShrinkWrapOpt, llvm::TargetFrameLowering::enableShrinkWrapping(), llvm::MachineBasicBlock::front(), llvm::MachineFunction::front(), llvm::MachineBlockFrequencyInfo::getBlockFreq(), llvm::MachineInstr::getDebugLoc(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::BlockFrequency::getFrequency(), llvm::MachineFunction::getFunction(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineBasicBlock::getName(), llvm::MachineFunction::getName(), llvm::MachineBasicBlock::getNumber(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::Function::getSubprogram(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::Function::hasFnAttribute(), llvm::cl::init(), llvm::MachineBasicBlock::isEHFuncletEntry(), llvm::MachineBasicBlock::isEHPad(), LLVM_DEBUG, llvm_unreachable, MI, llvm::MachineFrameInfo::setSavePoint(), llvm::MachineBasicBlock::successors(), TRI, and llvm::MCAsmInfo::usesWindowsCFI().
STATISTIC() [1/3]
STATISTIC (NumFunc , "Number of functions")
STATISTIC() [2/3]
STATISTIC (NumCandidates , "Number of shrink-wrapping candidates")
STATISTIC() [3/3]
STATISTIC (NumCandidatesDropped , "Number of shrink-wrapping candidates dropped because of frequency")
Variable Documentation
EnableShrinkWrapOpt
cl::opt<cl::boolOrDefault> EnableShrinkWrapOpt("enable-shrink-wrap", cl::Hidden, cl::desc("enable the shrink-wrapping pass")) static
Referenced by giveUpWithRemarks().