LLVM: lib/Target/AMDGPU/SIFixSGPRCopies.cpp File Reference
SIFixSGPRCopies.cpp File Reference
Copies from VGPR to SGPR registers are illegal and the register coalescer will sometimes generate these illegal copies in situations like this:
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIInstrInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <list>
#include <map>
#include <tuple>
#include <utility>
Macros
#define DEBUG_TYPE "si-fix-sgpr-copies"
Functions
INITIALIZE_PASS_BEGIN (SIFixSGPRCopies, DEBUG_TYPE, "SI Fix SGPR copies", false, false) INITIALIZE_PASS_END(SIFixSGPRCopies
static bool hasVectorOperands (const MachineInstr &MI, const SIRegisterInfo *TRI)
static std::pair< const TargetRegisterClass *, const TargetRegisterClass * > getCopyRegClasses (const MachineInstr &Copy, const SIRegisterInfo &TRI, const MachineRegisterInfo &MRI)
static bool isVGPRToSGPRCopy (const TargetRegisterClass *SrcRC, const TargetRegisterClass *DstRC, const SIRegisterInfo &TRI)
static bool isSGPRToVGPRCopy (const TargetRegisterClass *SrcRC, const TargetRegisterClass *DstRC, const SIRegisterInfo &TRI)
static bool tryChangeVGPRtoSGPRinCopy (MachineInstr &MI, const SIRegisterInfo *TRI, const SIInstrInfo *TII)
static bool foldVGPRCopyIntoRegSequence (MachineInstr &MI, const SIRegisterInfo *TRI, const SIInstrInfo *TII, MachineRegisterInfo &MRI)
static bool isSafeToFoldImmIntoCopy (const MachineInstr *Copy, const MachineInstr *MoveImm, const SIInstrInfo *TII, unsigned &SMovOp, int64_t &Imm)
template<class UnaryPredicate >
bool searchPredecessors (const MachineBasicBlock *MBB, const MachineBasicBlock *CutOff, UnaryPredicate Predicate)
static bool isReachable (const MachineInstr *From, const MachineInstr *To, const MachineBasicBlock *CutOff, MachineDominatorTree &MDT)
static MachineBasicBlock::iterator getFirstNonPrologue (MachineBasicBlock *MBB, const TargetInstrInfo *TII)
static bool hoistAndMergeSGPRInits (unsigned Reg, const MachineRegisterInfo &MRI, const TargetRegisterInfo *TRI, MachineDominatorTree &MDT, const TargetInstrInfo *TII)
Variables
static cl::opt< bool > EnableM0Merge ("amdgpu-enable-merge-m0", cl::desc("Merge and hoist M0 initializations"), cl::init(true))
DEBUG_TYPE
SI Fix SGPR copies
SI Fix SGPR false
Detailed Description
Copies from VGPR to SGPR registers are illegal and the register coalescer will sometimes generate these illegal copies in situations like this:
Register Class <vsrc> is the union of <vgpr> and <sgpr>
BB0: %0 <sgpr> = SCALAR_INST %1 <vsrc> = COPY %0 <sgpr> ... BRANCH cond BB1, BB2 BB1: %2 <vgpr> = VECTOR_INST %3 <vsrc> = COPY %2 <vgpr> BB2: %4 <vsrc> = PHI %1 <vsrc>, <bb.0>, %3 <vrsc>, <bb.1> %5 <vgpr> = VECTOR_INST %4 <vsrc>
The coalescer will begin at BB0 and eliminate its copy, then the resulting code will look like this:
BB0: %0 <sgpr> = SCALAR_INST ... BRANCH cond BB1, BB2 BB1: %2 <vgpr> = VECTOR_INST %3 <vsrc> = COPY %2 <vgpr> BB2: %4 <sgpr> = PHI %0 <sgpr>, <bb.0>, %3 <vsrc>, <bb.1> %5 <vgpr> = VECTOR_INST %4 <sgpr>
Now that the result of the PHI instruction is an SGPR, the register allocator is now forced to constrain the register class of %3 to <sgpr> so we end up with final code like this:
BB0: %0 <sgpr> = SCALAR_INST ... BRANCH cond BB1, BB2 BB1: %2 <vgpr> = VECTOR_INST %3 <sgpr> = COPY %2 <vgpr> BB2: %4 <sgpr> = PHI %0 <sgpr>, <bb.0>, %3 <sgpr>, <bb.1> %5 <vgpr> = VECTOR_INST %4 <sgpr>
Now this code contains an illegal copy from a VGPR to an SGPR.
In order to avoid this problem, this pass searches for PHI instructions which define a <vsrc> register and constrains its definition class to <vgpr> if the user of the PHI's definition register is a vector instruction. If the PHI's definition class is constrained to <vgpr> then the coalescer will be unable to perform the COPY removal from the above example which ultimately led to the creation of an illegal COPY.
Definition in file SIFixSGPRCopies.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-fix-sgpr-copies"
Definition at line 102 of file SIFixSGPRCopies.cpp.
Function Documentation
foldVGPRCopyIntoRegSequence()
static bool foldVGPRCopyIntoRegSequence (MachineInstr & MI, const SIRegisterInfo * TRI, const SIInstrInfo * TII, MachineRegisterInfo & MRI) static
Definition at line 240 of file SIFixSGPRCopies.cpp.
References add(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::eraseFromParent(), getCopyRegClasses(), llvm::MachineInstr::getDebugLoc(), llvm::SIRegisterInfo::getEquivalentAGPRClass(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), llvm::SIRegisterInfo::getSubRegClass(), llvm::SIRegisterInfo::hasAGPRs(), llvm::MachineRegisterInfo::hasOneUse(), I, llvm::MachineInstr::isCopy(), llvm::Register::isPhysicalRegister(), llvm::MachineInstr::isRegSequence(), llvm::SIRegisterInfo::isSGPRClass(), isSGPRToVGPRCopy(), llvm::RegState::Kill, MI, N, llvm::MachineOperand::setReg(), llvm::MachineRegisterInfo::setRegClass(), SubReg, tryChangeVGPRtoSGPRinCopy(), and llvm::MachineRegisterInfo::use_instr_begin().
Referenced by hoistAndMergeSGPRInits().
getCopyRegClasses()
static std::pair<const TargetRegisterClass *, const TargetRegisterClass *> getCopyRegClasses (const MachineInstr & Copy, const SIRegisterInfo & TRI, const MachineRegisterInfo & MRI) static
Definition at line 168 of file SIFixSGPRCopies.cpp.
References llvm::MachineInstr::getOperand(), llvm::SIRegisterInfo::getPhysRegClass(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), and llvm::Register::isVirtualRegister().
Referenced by foldVGPRCopyIntoRegSequence(), and hoistAndMergeSGPRInits().
getFirstNonPrologue()
static MachineBasicBlock::iterator getFirstNonPrologue (MachineBasicBlock * MBB, const TargetInstrInfo * TII) static
Definition at line 410 of file SIFixSGPRCopies.cpp.
References llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFirstNonPHI(), I, and llvm::TargetInstrInfo::isBasicBlockPrologue().
Referenced by hoistAndMergeSGPRInits().
hasVectorOperands()
static bool hasVectorOperands (const MachineInstr & MI, const SIRegisterInfo * TRI) static
Definition at line 153 of file SIFixSGPRCopies.cpp.
References llvm::numbers::e, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SIRegisterInfo::hasVectorRegisters(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), and MRI.
Referenced by hoistAndMergeSGPRInits().
hoistAndMergeSGPRInits()
static bool hoistAndMergeSGPRInits (unsigned Reg, const MachineRegisterInfo & MRI, const TargetRegisterInfo * TRI, MachineDominatorTree & MDT, const TargetInstrInfo * TII) static
Definition at line 422 of file SIFixSGPRCopies.cpp.
References add(), llvm::MachineInstr::addImplicitDefUseOperands(), llvm::any_of(), assert(), B, llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), C, llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::clearKillFlags(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::tgtok::Def, llvm::MachineRegisterInfo::def_instructions(), DefMI, llvm::MachineDominatorTree::dominates(), E, llvm::SetVector< T, Vector, Set >::empty(), EnableM0Merge, llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineDominatorTree::findNearestCommonDominator(), foldVGPRCopyIntoRegSequence(), From, llvm::GCNSubtarget::getConstantBusLimit(), getCopyRegClasses(), llvm::MachineInstr::getDebugLoc(), getFirstNonPrologue(), llvm::MachineOperand::getImm(), llvm::GCNSubtarget::getInstrInfo(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getOperandNo(), llvm::TargetMachine::getOptLevel(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), hasVectorOperands(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::TargetInstrInfo::isBasicBlockPrologue(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isImm(), llvm::MachineInstr::isPHI(), llvm::Register::isPhysical(), isReachable(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegSequence(), isSafeToFoldImmIntoCopy(), llvm::TargetInstrInfo::isSchedulingBoundary(), isSGPRToVGPRCopy(), isVGPRToSGPRCopy(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MI, MRI, llvm::CodeGenOpt::None, llvm::SetVector< T, Vector, Set >::pop_back_val(), llvm::printMBBReference(), llvm::MachineDominatorTree::properlyDominates(), llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), llvm::ARM_MB::ST, Threshold, TII, TRI, tryChangeVGPRtoSGPRinCopy(), UseMI, and llvm::SIInstrFlags::WQM.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (SIFixSGPRCopies , DEBUG_TYPE , "SI Fix SGPR copies" , false , false)
isReachable()
static bool isReachable (const MachineInstr * From, const MachineInstr * To, const MachineBasicBlock * CutOff, MachineDominatorTree & MDT) static
Definition at line 387 of file SIFixSGPRCopies.cpp.
References llvm::MachineDominatorTree::dominates(), llvm::MachineInstr::getParent(), and searchPredecessors().
Referenced by hoistAndMergeSGPRInits().
isSafeToFoldImmIntoCopy()
static bool isSafeToFoldImmIntoCopy (const MachineInstr * Copy, const MachineInstr * MoveImm, const SIInstrInfo * TII, unsigned & SMovOp, int64_t & Imm) static
Definition at line 323 of file SIFixSGPRCopies.cpp.
References llvm::MachineOperand::getImm(), llvm::SIInstrInfo::getNamedOperand(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isImm(), and llvm::MachineInstr::isMoveImmediate().
Referenced by hoistAndMergeSGPRInits().
isSGPRToVGPRCopy()
static bool isSGPRToVGPRCopy (const TargetRegisterClass * SrcRC, const TargetRegisterClass * DstRC, const SIRegisterInfo & TRI) static
Definition at line 195 of file SIFixSGPRCopies.cpp.
References llvm::SIRegisterInfo::hasVectorRegisters(), and llvm::SIRegisterInfo::isSGPRClass().
Referenced by foldVGPRCopyIntoRegSequence(), and hoistAndMergeSGPRInits().
isVGPRToSGPRCopy()
static bool isVGPRToSGPRCopy (const TargetRegisterClass * SrcRC, const TargetRegisterClass * DstRC, const SIRegisterInfo & TRI) static
Definition at line 188 of file SIFixSGPRCopies.cpp.
References llvm::SIRegisterInfo::hasVectorRegisters(), and llvm::SIRegisterInfo::isSGPRClass().
Referenced by hoistAndMergeSGPRInits().
searchPredecessors()
template<class UnaryPredicate > bool searchPredecessors (const MachineBasicBlock * MBB, const MachineBasicBlock * CutOff, UnaryPredicate Predicate)
Definition at line 358 of file SIFixSGPRCopies.cpp.
References llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::MachineBasicBlock::pred_begin(), and llvm::MachineBasicBlock::pred_end().
Referenced by isReachable().
tryChangeVGPRtoSGPRinCopy()
static bool tryChangeVGPRtoSGPRinCopy (MachineInstr & MI, const SIRegisterInfo * TRI, const SIInstrInfo * TII) static
Definition at line 202 of file SIFixSGPRCopies.cpp.
References llvm::SIRegisterInfo::getEquivalentSGPRClass(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getOperandNo(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SIInstrInfo::isOperandLegal(), llvm::Register::isVirtualRegister(), MRI, llvm::MachineRegisterInfo::reg_nodbg_operands(), llvm::MachineRegisterInfo::setRegClass(), and UseMI.
Referenced by foldVGPRCopyIntoRegSequence(), and hoistAndMergeSGPRInits().
Variable Documentation
copies
SI Fix SGPR copies
Definition at line 142 of file SIFixSGPRCopies.cpp.
DEBUG_TYPE
DEBUG_TYPE
Definition at line 142 of file SIFixSGPRCopies.cpp.
EnableM0Merge
cl::opt<bool> EnableM0Merge("amdgpu-enable-merge-m0", cl::desc("Merge and hoist M0 initializations"), cl::init(true)) static
Referenced by hoistAndMergeSGPRInits().
false
SI Fix SGPR false
Definition at line 142 of file SIFixSGPRCopies.cpp.