LLVM: lib/Target/AMDGPU/SIFoldOperands.cpp File Reference
SIFoldOperands.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "si-fold-operands"
Functions
static bool isInlineConstantIfFolded (const SIInstrInfo *TII, const MachineInstr &UseMI, unsigned OpNo, const MachineOperand &OpToFold)
static bool frameIndexMayFold (const SIInstrInfo *TII, const MachineInstr &UseMI, int OpNo, const MachineOperand &OpToFold)
static bool updateOperand (FoldCandidate &Fold, const SIInstrInfo &TII, const TargetRegisterInfo &TRI, const GCNSubtarget &ST)
static bool isUseMIInFoldList (ArrayRef< FoldCandidate > FoldList, const MachineInstr *MI)
static void appendFoldCandidate (SmallVectorImpl< FoldCandidate > &FoldList, MachineInstr *MI, unsigned OpNo, MachineOperand *FoldOp, bool Commuted=false, int ShrinkOp=-1)
static bool tryAddToFoldList (SmallVectorImpl< FoldCandidate > &FoldList, MachineInstr *MI, unsigned OpNo, MachineOperand *OpToFold, const SIInstrInfo *TII)
static bool isUseSafeToFold (const SIInstrInfo *TII, const MachineInstr &MI, const MachineOperand &UseMO)
static bool getRegSeqInit (SmallVectorImpl< std::pair< MachineOperand *, unsigned >> &Defs, Register UseReg, uint8_t OpTy, const SIInstrInfo *TII, const MachineRegisterInfo &MRI)
static bool tryToFoldACImm (const SIInstrInfo *TII, const MachineOperand &OpToFold, MachineInstr *UseMI, unsigned UseOpIdx, SmallVectorImpl< FoldCandidate > &FoldList)
static bool evalBinaryInstruction (unsigned Opcode, int32_t &Result, uint32_t LHS, uint32_t RHS)
static unsigned getMovOpc (bool IsScalar)
static void stripExtraCopyOperands (MachineInstr &MI)
Remove any leftover implicit operands from mutating the instruction.
static void mutateCopyOp (MachineInstr &MI, const MCInstrDesc &NewDesc)
static MachineOperand * getImmOrMaterializedImm (MachineRegisterInfo &MRI, MachineOperand &Op)
static bool tryConstantFoldOp (MachineRegisterInfo &MRI, const SIInstrInfo *TII, MachineInstr *MI, MachineOperand *ImmOp)
static bool tryFoldInst (const SIInstrInfo *TII, MachineInstr *MI)
static bool hasOneNonDBGUseInst (const MachineRegisterInfo &MRI, unsigned Reg)
static int getOModValue (unsigned Opc, int64_t Val)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-fold-operands"
Definition at line 25 of file SIFoldOperands.cpp.
Function Documentation
appendFoldCandidate()
static void appendFoldCandidate (SmallVectorImpl< FoldCandidate > & FoldList, MachineInstr * MI, unsigned OpNo, MachineOperand * FoldOp, bool Commuted = false, int ShrinkOp = -1) static
Definition at line 315 of file SIFoldOperands.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Referenced by tryAddToFoldList(), and tryToFoldACImm().
evalBinaryInstruction()
static bool evalBinaryInstruction (unsigned Opcode, int32_t & Result, uint32_t LHS, uint32_t RHS) static
Definition at line 892 of file SIFoldOperands.cpp.
Referenced by tryConstantFoldOp().
frameIndexMayFold()
static bool frameIndexMayFold (const SIInstrInfo * TII, const MachineInstr & UseMI, int OpNo, const MachineOperand & OpToFold) static
Definition at line 171 of file SIFoldOperands.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineOperand::isFI(), llvm::SIInstrInfo::isFLATScratch(), and llvm::SIInstrInfo::isMUBUF().
Referenced by tryFoldInst(), and tryToFoldACImm().
getImmOrMaterializedImm()
static MachineOperand* getImmOrMaterializedImm (MachineRegisterInfo & MRI, MachineOperand & Op) static
Definition at line 965 of file SIFoldOperands.cpp.
References llvm::tgtok::Def, llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineOperand::isImm(), llvm::MachineInstr::isMoveImmediate(), llvm::MachineOperand::isReg(), and llvm::Register::isVirtualRegister().
Referenced by tryConstantFoldOp().
getMovOpc()
static unsigned getMovOpc (bool IsScalar) static
Definition at line 943 of file SIFoldOperands.cpp.
Referenced by tryConstantFoldOp(), and tryFoldInst().
getOModValue()
static int getOModValue (unsigned Opc, int64_t Val) static
Definition at line 1343 of file SIFoldOperands.cpp.
References llvm::dbgs(), llvm::tgtok::Def, llvm::depth_first(), llvm::SIOutMods::DIV2, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::FmNsz, llvm::MachineInstr::getFlag(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::AMDGPUMachineFunction::getMode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), hasOneNonDBGUseInst(), I, llvm::AMDGPU::SIModeRegisterDefaults::IEEE, llvm::MachineOperand::isFI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineOperand::isImm(), llvm::Register::isPhysical(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, llvm_unreachable, llvm::MachineInstr::modifiesRegister(), MRI, llvm::SIOutMods::MUL2, llvm::SIOutMods::MUL4, llvm::SIOutMods::NONE, llvm::MachineOperand::setImm(), llvm::ARM_MB::ST, TII, TRI, and tryFoldInst().
getRegSeqInit()
static bool getRegSeqInit (SmallVectorImpl< std::pair< MachineOperand *, unsigned >> & Defs, Register UseReg, uint8_t OpTy, const SIInstrInfo * TII, const MachineRegisterInfo & MRI) static
Definition at line 470 of file SIFoldOperands.cpp.
References assert(), llvm::tgtok::Def, E, llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineRegisterInfo::getUniqueVRegDef(), I, llvm::SIInstrInfo::isFoldableCopy(), llvm::MachineOperand::isImm(), llvm::SIInstrInfo::isInlineConstant(), llvm::MachineOperand::isReg(), and llvm::MachineInstr::isRegSequence().
Referenced by tryToFoldACImm().
hasOneNonDBGUseInst()
static bool hasOneNonDBGUseInst (const MachineRegisterInfo & MRI, unsigned Reg) static
Definition at line 1306 of file SIFoldOperands.cpp.
References llvm::dbgs(), llvm::tgtok::Def, E, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, LLVM_DEBUG, MRI, llvm::MachineOperand::setImm(), TII, llvm::MachineRegisterInfo::use_instr_nodbg_begin(), and llvm::MachineRegisterInfo::use_instr_nodbg_end().
Referenced by getOModValue().
isInlineConstantIfFolded()
static bool isInlineConstantIfFolded (const SIInstrInfo * TII, const MachineInstr & UseMI, unsigned OpNo, const MachineOperand & OpToFold) static
Definition at line 134 of file SIFoldOperands.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::SIInstrInfo::isInlineConstant(), llvm::MCOperandInfo::OperandType, and llvm::MCInstrDesc::OpInfo.
Referenced by tryFoldInst().
isUseMIInFoldList()
static bool isUseMIInFoldList (ArrayRef< FoldCandidate > FoldList, const MachineInstr * MI) static
Definition at line 306 of file SIFoldOperands.cpp.
Referenced by tryAddToFoldList().
isUseSafeToFold()
static bool isUseSafeToFold (const SIInstrInfo * TII, const MachineInstr & MI, const MachineOperand & UseMO) static
Definition at line 460 of file SIFoldOperands.cpp.
References llvm::SIInstrInfo::isSDWA(), and llvm::MachineOperand::isUndef().
Referenced by tryToFoldACImm().
mutateCopyOp()
static void mutateCopyOp (MachineInstr & MI, const MCInstrDesc & NewDesc) static
Definition at line 960 of file SIFoldOperands.cpp.
References llvm::MachineInstr::setDesc(), and stripExtraCopyOperands().
Referenced by tryConstantFoldOp(), and tryFoldInst().
stripExtraCopyOperands()
static void stripExtraCopyOperands (MachineInstr & MI) static
Remove any leftover implicit operands from mutating the instruction.
e.g. if we replace an s_and_b32 with a copy, we don't need the implicit scc def anymore.
Definition at line 950 of file SIFoldOperands.cpp.
References llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumImplicitDefs(), llvm::MCInstrDesc::getNumImplicitUses(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), I, and llvm::MachineInstr::RemoveOperand().
Referenced by mutateCopyOp(), and tryConstantFoldOp().
tryAddToFoldList()
static bool tryAddToFoldList (SmallVectorImpl< FoldCandidate > & FoldList, MachineInstr * MI, unsigned OpNo, MachineOperand * OpToFold, const SIInstrInfo * TII) static
Definition at line 328 of file SIFoldOperands.cpp.
References appendFoldCandidate(), assert(), llvm::TargetInstrInfo::CommuteAnyOperandIndex, llvm::numbers::e, llvm::SIInstrInfo::findCommutedOpIndices(), llvm::MachineInstr::getDesc(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SIInstrInfo::getRegisterInfo(), llvm::AMDGPU::getVOPe32(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::SIInstrInfo::isInlineConstant(), llvm::SIInstrInfo::isLiteralConstantLike(), llvm::SIInstrInfo::isOperandLegal(), llvm::MachineOperand::isReg(), llvm::SIInstrInfo::isSALU(), isUseMIInFoldList(), llvm::SIRegisterInfo::isVGPR(), MRI, llvm::SIRegisterInfo::opCanUseInlineConstant(), llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, llvm::MachineInstr::setDesc(), and llvm::MachineInstr::untieRegOperand().
Referenced by tryToFoldACImm().
tryConstantFoldOp()
static bool tryConstantFoldOp (MachineRegisterInfo & MRI, const SIInstrInfo * TII, MachineInstr * MI, MachineOperand * ImmOp) static
Definition at line 987 of file SIFoldOperands.cpp.
References llvm::MachineOperand::ChangeToImmediate(), evalBinaryInstruction(), llvm::MachineOperand::getImm(), getImmOrMaterializedImm(), getMovOpc(), llvm::SIInstrInfo::getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SIInstrInfo::getRegisterInfo(), llvm::MachineInstr::isCommutable(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::SIRegisterInfo::isSGPRReg(), mutateCopyOp(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), stripExtraCopyOperands(), std::swap(), and TRI.
Referenced by tryFoldInst().
tryFoldInst()
static bool tryFoldInst (const SIInstrInfo * TII, MachineInstr * MI) static
Definition at line 1101 of file SIFoldOperands.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DefMI, E, llvm::execMayBeModifiedBeforeUse(), frameIndexMayFold(), llvm::MachineOperand::getImm(), getMovOpc(), llvm::SIInstrInfo::getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::Use::getOperandNo(), llvm::MachineInstr::getOperandNo(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineOperand::isImm(), isInlineConstantIfFolded(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MI, MRI, mutateCopyOp(), llvm::SISrcMods::OP_SEL_1, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineInstr::readsRegister(), Reg, llvm::MachineInstr::RemoveOperand(), llvm::ARM_MB::ST, TII, TRI, tryConstantFoldOp(), and updateOperand().
Referenced by getOModValue().
tryToFoldACImm()
static bool tryToFoldACImm (const SIInstrInfo * TII, const MachineOperand & OpToFold, MachineInstr * UseMI, unsigned UseOpIdx, SmallVectorImpl< FoldCandidate > & FoldList) static
Definition at line 503 of file SIFoldOperands.cpp.
References add(), appendFoldCandidate(), assert(), B, llvm::BuildMI(), llvm::MachineOperand::ChangeToFrameIndex(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::CreateImm(), llvm::dbgs(), llvm::tgtok::Def, E, llvm::SmallVectorTemplateCommon< T >::end(), llvm::execMayBeModifiedBeforeUse(), F(), R600_InstFlag::FC, llvm::find_if(), first, frameIndexMayFold(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::TargetRegisterClass::getID(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::APInt::getLoBits(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::Use::getOperandNo(), llvm::MachineInstr::getOperandNo(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::AMDGPU::getRegBitWidth(), llvm::MachineFunction::getRegInfo(), getRegSeqInit(), llvm::getRegSubRegPair(), llvm::MachineOperand::getSubReg(), I, llvm::MachineInstr::implicit_operands(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::SIInstrInfo::isInlineConstant(), llvm::SIInstrInfo::isOperandLegal(), llvm::Register::isPhysical(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegSequence(), llvm::MachineOperand::isUndef(), isUseSafeToFold(), llvm::MCInstrDesc::isVariadic(), llvm::Register::isVirtual(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MRI, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FIRST, llvm::AMDGPU::OPERAND_REG_INLINE_AC_LAST, llvm::AMDGPU::OPERAND_REG_INLINE_C_INT32, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::TargetInstrInfo::RegSubRegPair::Reg, llvm::MCOperandInfo::RegClass, llvm::MachineInstr::RemoveOperand(), second, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setReg(), llvm::MachineOperand::setSubReg(), Size, llvm::SmallVectorBase::size(), TII, TRI, tryAddToFoldList(), llvm::RegState::Undef, UseMI, and UseReg().
updateOperand()
static bool updateOperand (FoldCandidate & Fold, const SIInstrInfo & TII, const TargetRegisterInfo & TRI, const GCNSubtarget & ST) static
Definition at line 184 of file SIFoldOperands.cpp.
References assert(), llvm::BuildMI(), llvm::SIInstrInfo::buildShrunkInst(), llvm::MachineOperand::ChangeToFrameIndex(), llvm::MachineOperand::ChangeToGA(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineBasicBlock::computeRegisterLiveness(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getOperandNo(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getSubReg(), llvm::AMDGPUSubtarget::hasInv2PiInlineImm(), I, llvm::MachineOperand::isDef(), llvm::AMDGPU::isInlinableLiteralV216(), llvm::SIInstrFlags::IsMAI, llvm::SIInstrFlags::IsPacked, llvm::MachineOperand::isReg(), llvm::isUInt< 16 >(), llvm::MachineOperand::isUndef(), llvm::RegState::Kill, LLVM_DEBUG, llvm::MachineBasicBlock::LQR_Dead, MI, llvm::Mod, MRI, llvm::SISrcMods::OP_SEL_0, llvm::SISrcMods::OP_SEL_1, llvm::AMDGPU::OPERAND_REG_IMM_V2FP16, llvm::AMDGPU::OPERAND_REG_IMM_V2INT16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2FP16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2INT16, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setReg(), llvm::MachineOperand::substVirtReg(), TRI, llvm::MCInstrDesc::TSFlags, and llvm::MachineRegisterInfo::use_nodbg_empty().
Referenced by tryFoldInst().