LLVM: lib/Target/AMDGPU/SIISelLowering.cpp File Reference
SIISelLowering.cpp File Reference
Custom DAG lowering for SI.
#include "SIISelLowering.h"
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "AMDGPUTargetMachine.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/DAGCombine.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetCallingConv.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetOptions.h"
#include <cassert>
#include <cmath>
#include <cstdint>
#include <iterator>
#include <tuple>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "si-lower"
Functions
STATISTIC (NumTailCalls, "Number of tail calls")
static bool hasFP32Denormals (const MachineFunction &MF)
static bool hasFP64FP16Denormals (const MachineFunction &MF)
static unsigned findFirstFreeSGPR (CCState &CCInfo)
static MVT memVTFromAggregate (Type *Ty)
static void processShaderInputArgs (SmallVectorImpl< ISD::InputArg > &Splits, CallingConv::ID CallConv, ArrayRef< ISD::InputArg > Ins, BitVector &Skipped, FunctionType *FType, SIMachineFunctionInfo *Info)
static ArgDescriptor allocateVGPR32Input (CCState &CCInfo, unsigned Mask=~0u, ArgDescriptor Arg=ArgDescriptor())
static ArgDescriptor allocateSGPR32InputImpl (CCState &CCInfo, const TargetRegisterClass *RC, unsigned NumArgRegs)
static ArgDescriptor allocateSGPR32Input (CCState &CCInfo)
static ArgDescriptor allocateSGPR64Input (CCState &CCInfo)
static void reservePrivateMemoryRegs (const TargetMachine &TM, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info)
static bool canGuaranteeTCO (CallingConv::ID CC)
static bool mayTailCallThisCC (CallingConv::ID CC)
Return true if we might ever do TCO for calls with this calling convention.
static std::pair< MachineBasicBlock *, MachineBasicBlock * > splitBlockForLoop (MachineInstr &MI, MachineBasicBlock &MBB, bool InstInLoop)
static MachineBasicBlock::iterator emitLoadM0FromVGPRLoop (const SIInstrInfo *TII, MachineRegisterInfo &MRI, MachineBasicBlock &OrigBB, MachineBasicBlock &LoopBB, const DebugLoc &DL, const MachineOperand &IdxReg, unsigned InitReg, unsigned ResultReg, unsigned PhiReg, unsigned InitSaveExecReg, int Offset, bool UseGPRIdxMode, bool IsIndirectSrc)
static MachineBasicBlock::iterator loadM0FromVGPR (const SIInstrInfo *TII, MachineBasicBlock &MBB, MachineInstr &MI, unsigned InitResultReg, unsigned PhiReg, int Offset, bool UseGPRIdxMode, bool IsIndirectSrc)
static std::pair< unsigned, int > computeIndirectRegAndOffset (const SIRegisterInfo &TRI, const TargetRegisterClass *SuperRC, unsigned VecReg, int Offset)
static bool setM0ToIndexFromSGPR (const SIInstrInfo *TII, MachineRegisterInfo &MRI, MachineInstr &MI, int Offset, bool UseGPRIdxMode, bool IsIndirectSrc)
static MachineBasicBlock * emitIndirectSrc (MachineInstr &MI, MachineBasicBlock &MBB, const GCNSubtarget &ST)
static unsigned getMOVRELDPseudo (const SIRegisterInfo &TRI, const TargetRegisterClass *VecRC)
static MachineBasicBlock * emitIndirectDst (MachineInstr &MI, MachineBasicBlock &MBB, const GCNSubtarget &ST)
static SDValue adjustLoadValueTypeImpl (SDValue Result, EVT LoadVT, const SDLoc &DL, SelectionDAG &DAG, bool Unpacked)
static SDValue lowerICMPIntrinsic (const SITargetLowering &TLI, SDNode *N, SelectionDAG &DAG)
static SDValue lowerFCMPIntrinsic (const SITargetLowering &TLI, SDNode *N, SelectionDAG &DAG)
static SDNode * findUser (SDValue Value, unsigned Opcode)
Helper function for LowerBRCOND.
static bool elementPairIsContiguous (ArrayRef< int > Mask, int Elt)
static SDValue buildPCRelGlobalAddress (SelectionDAG &DAG, const GlobalValue *GV, const SDLoc &DL, unsigned Offset, EVT PtrVT, unsigned GAFlags=SIInstrInfo::MO_NONE)
static SDValue emitNonHSAIntrinsicError (SelectionDAG &DAG, const SDLoc &DL, EVT VT)
static SDValue emitRemovedIntrinsicError (SelectionDAG &DAG, const SDLoc &DL, EVT VT)
static SDValue getBuildDwordsVector (SelectionDAG &DAG, SDLoc DL, ArrayRef< SDValue > Elts)
static bool parseCachePolicy (SDValue CachePolicy, SelectionDAG &DAG, SDValue *GLC, SDValue *SLC, SDValue *DLC)
static SDValue constructRetValue (SelectionDAG &DAG, MachineSDNode *Result, ArrayRef< EVT > ResultTypes, bool IsTexFail, bool Unpacked, bool IsD16, int DMaskPop, int NumVDataDwords, const SDLoc &DL, LLVMContext &Context)
static bool parseTexFail (SDValue TexFailCtrl, SelectionDAG &DAG, SDValue *TFE, SDValue *LWE, bool &IsTexFail)
static unsigned getBufferOffsetForMMO (SDValue VOffset, SDValue SOffset, SDValue Offset, SDValue VIndex=SDValue())
static SDValue getLoadExtOrTrunc (SelectionDAG &DAG, ISD::LoadExtType ExtType, SDValue Op, const SDLoc &SL, EVT VT)
static SDValue getFPBinOp (SelectionDAG &DAG, unsigned Opcode, const SDLoc &SL, EVT VT, SDValue A, SDValue B, SDValue GlueChain)
static SDValue getFPTernOp (SelectionDAG &DAG, unsigned Opcode, const SDLoc &SL, EVT VT, SDValue A, SDValue B, SDValue C, SDValue GlueChain)
static const SDValue getSPDenormModeValue (int SPDenormMode, SelectionDAG &DAG, const SDLoc &SL, const GCNSubtarget *ST)
static bool bitOpWithConstantIsReducible (unsigned Opc, uint32_t Val)
static bool isBoolSGPR (SDValue V)
static uint32_t getConstantPermuteMask (uint32_t C)
static uint32_t getPermuteMask (SelectionDAG &DAG, SDValue V)
static bool fp16SrcZerosHighBits (unsigned Opc)
static bool vectorEltWillFoldAway (SDValue Op)
static unsigned minMaxOpcToMin3Max3Opc (unsigned Opc)
static ConstantFPSDNode * getSplatConstantFP (SDValue Op)
static bool isClampZeroToOne (SDValue A, SDValue B)
static SDValue getMad64_32 (SelectionDAG &DAG, const SDLoc &SL, EVT VT, SDValue N0, SDValue N1, SDValue N2, bool Signed)
static unsigned SubIdx2Lane (unsigned Idx)
Helper function for adjustWritemask.
static bool isFrameIndexOp (SDValue Op)
static SDValue buildSMovImm32 (SelectionDAG &DAG, const SDLoc &DL, uint64_t Val)
static LLVM_ATTRIBUTE_UNUSED bool isCopyFromRegOfInlineAsm (const SDNode *N)
static bool hasCFUser (const Value *V, SmallPtrSet< const Value *, 16 > &Visited)
Variables
static cl::opt< bool > DisableLoopAlignment ("amdgpu-disable-loop-alignment", cl::desc("Do not align and prefetch loops"), cl::init(false))
Detailed Description
Custom DAG lowering for SI.
Definition in file SIISelLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-lower"
Definition at line 89 of file SIISelLowering.cpp.
Function Documentation
adjustLoadValueTypeImpl()
static SDValue adjustLoadValueTypeImpl (SDValue Result, EVT LoadVT, const SDLoc & DL, SelectionDAG & DAG, bool Unpacked) static
Definition at line 4108 of file SIISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::AMDGPUISD::BUFFER_LOAD, llvm::AMDGPUISD::BUFFER_LOAD_FORMAT, llvm::AMDGPUISD::BUFFER_LOAD_FORMAT_D16, llvm::EVT::changeTypeToInteger(), llvm::SelectionDAG::ExtractVectorElements(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getContext(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::GCNSubtarget::hasUnpackedD16VMem(), llvm::MVT::i16, llvm::MVT::i32, llvm::ISD::INTRINSIC_W_CHAIN, llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::SPII::Load, llvm::MVT::Other, and llvm::ISD::TRUNCATE.
Referenced by constructRetValue().
allocateSGPR32Input()
static ArgDescriptor allocateSGPR32Input (CCState & CCInfo) static
Definition at line 1701 of file SIISelLowering.cpp.
References allocateSGPR32InputImpl().
Referenced by llvm::SITargetLowering::allocateSpecialInputSGPRs().
allocateSGPR32InputImpl()
static ArgDescriptor allocateSGPR32InputImpl (CCState & CCInfo, const TargetRegisterClass * RC, unsigned NumArgRegs) static
Definition at line 1684 of file SIISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), assert(), llvm::TargetRegisterClass::begin(), llvm::ArgDescriptor::createRegister(), llvm::CCState::getFirstUnallocated(), llvm::CCState::getMachineFunction(), llvm::makeArrayRef(), Reg, llvm::report_fatal_error(), and llvm::ArrayRef< T >::size().
Referenced by allocateSGPR32Input(), and allocateSGPR64Input().
allocateSGPR64Input()
static ArgDescriptor allocateSGPR64Input (CCState & CCInfo) static
Definition at line 1705 of file SIISelLowering.cpp.
References allocateSGPR32InputImpl().
Referenced by llvm::SITargetLowering::allocateSpecialInputSGPRs().
allocateVGPR32Input()
static ArgDescriptor allocateVGPR32Input (CCState & CCInfo, unsigned Mask = ~0u, ArgDescriptor Arg = ArgDescriptor()) static
Definition at line 1659 of file SIISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateStack(), assert(), llvm::sys::path::begin(), llvm::ArgDescriptor::createArg(), llvm::ArgDescriptor::createRegister(), llvm::ArgDescriptor::createStack(), llvm::CCState::getFirstUnallocated(), llvm::CCState::getMachineFunction(), llvm::MachineFunction::getRegInfo(), llvm::makeArrayRef(), llvm::BitmaskEnumDetail::Mask(), Reg, llvm::LLT::scalar(), llvm::MachineRegisterInfo::setType(), and llvm::ArrayRef< T >::size().
Referenced by llvm::SITargetLowering::allocateSpecialInputVGPRs().
bitOpWithConstantIsReducible()
static bool bitOpWithConstantIsReducible (unsigned Opc, uint32_t Val) static
Definition at line 8141 of file SIISelLowering.cpp.
References llvm::ISD::AND, llvm::ConstantSDNode::getAPIntValue(), llvm::GCNSubtarget::getInstrInfo(), llvm::SITargetLowering::getSubtarget(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasOneUse(), llvm::Hi_32(), llvm::SIInstrInfo::isInlineConstant(), llvm::Lo_32(), llvm::ISD::OR, llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), TII, and llvm::ISD::XOR.
buildPCRelGlobalAddress()
static SDValue buildPCRelGlobalAddress (SelectionDAG & DAG, const GlobalValue * GV, const SDLoc & DL, unsigned Offset, EVT PtrVT, unsigned GAFlags = SIInstrInfo::MO_NONE) static
Definition at line 5038 of file SIISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::Triple::AMDHSA, llvm::Triple::AMDPAL, AMDGPUAS::CONSTANT_ADDRESS, llvm::PointerType::get(), llvm::DataLayout::getABITypeAlignment(), llvm::GlobalAddressSDNode::getAddressSpace(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachinePointerInfo::getGOT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::Triple::getOS(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetMachine::getTargetTriple(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::AMDGPUISD::LDS, AMDGPUAS::LOCAL_ADDRESS, llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SIInstrInfo::MO_ABS32_LO, llvm::SIInstrInfo::MO_GOTPCREL32, llvm::SIInstrInfo::MO_NONE, llvm::SIInstrInfo::MO_REL32, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::AMDGPUISD::PC_ADD_REL_OFFSET, AMDGPUAS::PRIVATE_ADDRESS, AMDGPUAS::REGION_ADDRESS, llvm::SITargetLowering::shouldEmitFixup(), and llvm::SITargetLowering::shouldEmitPCReloc().
buildSMovImm32()
static SDValue buildSMovImm32 (SelectionDAG & DAG, const SDLoc & DL, uint64_t Val) static
Definition at line 10514 of file SIISelLowering.cpp.
References llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), and llvm::MVT::i32.
Referenced by llvm::SITargetLowering::buildRSRC(), and llvm::SITargetLowering::wrapAddr64Rsrc().
canGuaranteeTCO()
static bool canGuaranteeTCO (CallingConv::ID CC) static
Definition at line 2580 of file SIISelLowering.cpp.
References llvm::CallingConv::Fast.
Referenced by llvm::SITargetLowering::isEligibleForTailCallOptimization(), and mayTailCallThisCC().
computeIndirectRegAndOffset()
static std::pair<unsigned, int> computeIndirectRegAndOffset (const SIRegisterInfo & TRI, const TargetRegisterClass * SuperRC, unsigned VecReg, int Offset) static
Definition at line 3323 of file SIISelLowering.cpp.
Referenced by emitIndirectDst(), and emitIndirectSrc().
constructRetValue()
static SDValue constructRetValue (SelectionDAG & DAG, MachineSDNode * Result, ArrayRef< EVT > ResultTypes, bool IsTexFail, bool Unpacked, bool IsD16, int DMaskPop, int NumVDataDwords, const SDLoc & DL, LLVMContext & Context) static
Definition at line 5236 of file SIISelLowering.cpp.
References adjustLoadValueTypeImpl(), llvm::ISD::BITCAST, llvm::SelectionDAG::ExtractVectorElements(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumValues(), llvm::SelectionDAG::getUNDEF(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i32, llvm::EVT::isVector(), N, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MVT::v2i32, and llvm::MVT::v4f16.
Referenced by parseTexFail().
elementPairIsContiguous()
static bool elementPairIsContiguous (ArrayRef< int > Mask, int Elt) static
Definition at line 4921 of file SIISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::BITCAST, llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::AMDGPUSubtarget::hasVOP3PInsts(), llvm::MipsISD::Hi, I, llvm::MVT::i16, llvm::MVT::i32, llvm::EVT::isInteger(), llvm::SDValue::isUndef(), llvm::MipsISD::Lo, N, llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SHL, llvm::MVT::v2f16, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v4f16, llvm::MVT::v4i16, and llvm::ISD::ZERO_EXTEND.
emitIndirectDst()
static MachineBasicBlock* emitIndirectDst (MachineInstr & MI, MachineBasicBlock & MBB, const GCNSubtarget & ST) static
Definition at line 3486 of file SIISelLowering.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::clearKillFlags(), computeIndirectRegAndOffset(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Define, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::GCNSubtarget::getInstrInfo(), getMOVRELDPseudo(), llvm::SIInstrInfo::getNamedOperand(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SIInstrInfo::getRegisterInfo(), I, llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, llvm::MachineOperand::isReg(), loadM0FromVGPR(), MRI, setM0ToIndexFromSGPR(), SubReg, TII, TRI, llvm::RegState::Undef, and llvm::GCNSubtarget::useVGPRIndexMode().
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter().
emitIndirectSrc()
static MachineBasicBlock* emitIndirectSrc (MachineInstr & MI, MachineBasicBlock & MBB, const GCNSubtarget & ST) static
Definition at line 3395 of file SIISelLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), computeIndirectRegAndOffset(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::GCNSubtarget::getInstrInfo(), llvm::SIInstrInfo::getNamedOperand(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SIInstrInfo::getRegisterInfo(), I, llvm::RegState::Implicit, loadM0FromVGPR(), MRI, setM0ToIndexFromSGPR(), SubReg, TII, TRI, llvm::RegState::Undef, and llvm::GCNSubtarget::useVGPRIndexMode().
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter().
emitLoadM0FromVGPRLoop()
static MachineBasicBlock::iterator emitLoadM0FromVGPRLoop (const SIInstrInfo * TII, MachineRegisterInfo & MRI, MachineBasicBlock & OrigBB, MachineBasicBlock & LoopBB, const DebugLoc & DL, const MachineOperand & IdxReg, unsigned InitReg, unsigned ResultReg, unsigned PhiReg, unsigned InitSaveExecReg, int Offset, bool UseGPRIdxMode, bool IsIndirectSrc) static
Definition at line 3170 of file SIISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::AMDGPU::VGPRIndexMode::DST_ENABLE, llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::GCNSubtarget::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::getUndefRegState(), I, llvm::MachineOperand::isUndef(), llvm::GCNSubtarget::isWave32(), llvm::RegState::Kill, llvm::MachineOperand::setIsUndef(), llvm::MachineRegisterInfo::setSimpleHint(), llvm::AMDGPU::VGPRIndexMode::SRC0_ENABLE, llvm::ARM_MB::ST, and TRI.
Referenced by loadM0FromVGPR().
emitNonHSAIntrinsicError()
static SDValue emitNonHSAIntrinsicError (SelectionDAG & DAG, const SDLoc & DL, EVT VT) static
Definition at line 5154 of file SIISelLowering.cpp.
References llvm::LLVMContext::diagnose(), llvm::SelectionDAG::getContext(), llvm::SDLoc::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), and llvm::SelectionDAG::getUNDEF().
Referenced by parseTexFail().
emitRemovedIntrinsicError()
static SDValue emitRemovedIntrinsicError (SelectionDAG & DAG, const SDLoc & DL, EVT VT) static
Definition at line 5163 of file SIISelLowering.cpp.
References llvm::LLVMContext::diagnose(), llvm::SelectionDAG::getContext(), llvm::SDLoc::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), and llvm::SelectionDAG::getUNDEF().
Referenced by parseTexFail().
findFirstFreeSGPR()
static unsigned findFirstFreeSGPR (CCState & CCInfo) static
Definition at line 108 of file SIISelLowering.cpp.
References llvm::CCState::isAllocated(), llvm_unreachable, llvm::AMDGPU::HSAMD::Kernel::CodeProps::Key::NumSGPRs, and Reg.
Referenced by llvm::SITargetLowering::allocateSystemSGPRs().
findUser()
static SDNode* findUser (SDValue Value, unsigned Opcode) static
Helper function for LowerBRCOND.
Definition at line 4396 of file SIISelLowering.cpp.
References E, llvm::AMDGPUISD::ELSE, llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), I, llvm::AMDGPUISD::IF, Intr, llvm::ISD::INTRINSIC_W_CHAIN, llvm_unreachable, llvm::AMDGPUISD::LOOP, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by llvm::SITargetLowering::shouldEmitPCReloc().
fp16SrcZerosHighBits()
static bool fp16SrcZerosHighBits (unsigned Opc) static
Definition at line 8590 of file SIISelLowering.cpp.
References llvm::AfterLegalizeDAG, llvm::ISD::BITCAST, llvm::AMDGPUISD::BUFFER_LOAD_BYTE, llvm::AMDGPUISD::BUFFER_LOAD_SHORT, llvm::AMDGPUISD::BUFFER_LOAD_UBYTE, llvm::AMDGPUISD::BUFFER_LOAD_USHORT, llvm::AMDGPUISD::CLAMP, llvm::AMDGPUISD::COS_HW, llvm::MVT::f16, llvm::MVT::f32, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::AMDGPUISD::FMAD_FTZ, llvm::AMDGPUISD::FMAX3, llvm::ISD::FMAXNUM, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN3, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::AMDGPUISD::FP16_ZEXT, llvm::ISD::FP_ROUND, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::AMDGPUISD::FRACT, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::SelectionDAG::getConstant(), llvm::SDNode::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::SDValue::isUndef(), llvm::AMDGPUISD::LDEXP, llvm::BitmaskEnumDetail::Mask(), llvm::AMDGPUTargetLowering::performRcpCombine(), llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_IFLAG, llvm::AMDGPUISD::RSQ, llvm::AMDGPUISD::SIN_HW, llvm::ISD::SINT_TO_FP, and llvm::ISD::UINT_TO_FP.
getBufferOffsetForMMO()
static unsigned getBufferOffsetForMMO (SDValue VOffset, SDValue SOffset, SDValue Offset, SDValue VIndex = SDValue()) static
Definition at line 6115 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::ISD::ANY_EXTEND, assert(), llvm::AMDGPUISD::ATOMIC_DEC, llvm::AMDGPUISD::ATOMIC_INC, llvm::ISD::ATOMIC_LOAD_FADD, llvm::AMDGPUISD::ATOMIC_LOAD_FMAX, llvm::AMDGPUISD::ATOMIC_LOAD_FMIN, llvm::AMDGPUISD::ATOMIC_PK_FADD, llvm::ISD::BITCAST, llvm::AMDGPUISD::BUFFER_ATOMIC_ADD, llvm::AMDGPUISD::BUFFER_ATOMIC_AND, llvm::AMDGPUISD::BUFFER_ATOMIC_CMPSWAP, llvm::AMDGPUISD::BUFFER_ATOMIC_DEC, llvm::AMDGPUISD::BUFFER_ATOMIC_FADD, llvm::AMDGPUISD::BUFFER_ATOMIC_INC, llvm::AMDGPUISD::BUFFER_ATOMIC_OR, llvm::AMDGPUISD::BUFFER_ATOMIC_PK_FADD, llvm::AMDGPUISD::BUFFER_ATOMIC_SMAX, llvm::AMDGPUISD::BUFFER_ATOMIC_SMIN, llvm::AMDGPUISD::BUFFER_ATOMIC_SUB, llvm::AMDGPUISD::BUFFER_ATOMIC_SWAP, llvm::AMDGPUISD::BUFFER_ATOMIC_UMAX, llvm::AMDGPUISD::BUFFER_ATOMIC_UMIN, llvm::AMDGPUISD::BUFFER_ATOMIC_XOR, llvm::AMDGPUISD::BUFFER_LOAD, llvm::AMDGPUISD::BUFFER_LOAD_FORMAT, llvm::AMDGPUISD::BUFFER_LOAD_FORMAT_D16, llvm::AMDGPUISD::BUFFER_LOAD_UBYTE, llvm::AMDGPUISD::BUFFER_LOAD_USHORT, llvm::AMDGPUISD::BUFFER_STORE, llvm::AMDGPUISD::BUFFER_STORE_BYTE, llvm::AMDGPUISD::BUFFER_STORE_FORMAT, llvm::AMDGPUISD::BUFFER_STORE_FORMAT_D16, llvm::AMDGPUISD::BUFFER_STORE_SHORT, C, llvm::EVT::changeTypeToInteger(), llvm::SITargetLowering::copyToM0(), llvm::AMDGPUISD::DS_ORDERED_COUNT, llvm::AMDGPUISD::EXPORT, llvm::AMDGPUISD::EXPORT_DONE, llvm::ISD::EXTRACT_SUBVECTOR, llvm::MVT::f16, llvm::MVT::f32, llvm::SelectionDAG::getAtomic(), llvm::Function::getCallingConv(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), llvm::AMDGPUSubtarget::getFlatWorkGroupSizes(), llvm::MachineFunction::getFunction(), llvm::GCNSubtarget::getGeneration(), llvm::AMDGPU::getImageDimIntrinsicInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetMachine::getOptLevel(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::AMDGPUTargetLowering::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::ConstantSDNode::getZExtValue(), llvm::AMDGPUSubtarget::GFX10, llvm::GCNSubtarget::hasDwordx3LoadStores(), llvm::GCNSubtarget::hasUnpackedD16VMem(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::SelectionDAG::isBaseWithConstantOffset(), llvm::ConstantSDNode::isNullValue(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm_unreachable, llvm::makeArrayRef(), llvm::CodeGenOpt::None, llvm::SDVTList::NumVTs, llvm::MVT::Other, llvm::report_fatal_error(), second, llvm::MachineMemOperand::setOffset(), llvm::AMDGPU::splitMUBUFOffset(), llvm::ARM_MB::ST, llvm::AMDGPUISD::TBUFFER_LOAD_FORMAT, llvm::AMDGPUISD::TBUFFER_LOAD_FORMAT_D16, llvm::AMDGPUISD::TBUFFER_STORE_FORMAT, llvm::AMDGPUISD::TBUFFER_STORE_FORMAT_D16, llvm::ISD::TRUNCATE, llvm::RegState::Undef, llvm::SelectionDAG::UnrollVectorOp(), llvm::MVT::v3f32, llvm::MVT::v3i32, llvm::SDVTList::VTs, and llvm::ISD::ZERO_EXTEND.
getBuildDwordsVector()
static SDValue getBuildDwordsVector (SelectionDAG & DAG, SDLoc DL, ArrayRef< SDValue > Elts) static
Definition at line 5172 of file SIISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::empty(), llvm::MVT::f32, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::ArrayRef< T >::size(), llvm::MVT::v16f32, llvm::MVT::v2f32, llvm::MVT::v4f32, and llvm::MVT::v8f32.
Referenced by parseTexFail().
getConstantPermuteMask()
static uint32_t getConstantPermuteMask (uint32_t C) static
Definition at line 8193 of file SIISelLowering.cpp.
References C.
Referenced by getPermuteMask().
getFPBinOp()
static SDValue getFPBinOp (SelectionDAG & DAG, unsigned Opcode, const SDLoc & SL, EVT VT, SDValue A, SDValue B, SDValue GlueChain) static
Definition at line 7595 of file SIISelLowering.cpp.
References assert(), B, llvm::ISD::FMUL, llvm::AMDGPUISD::FMUL_W_CHAIN, llvm::SelectionDAG::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm_unreachable, and llvm::MVT::Other.
Referenced by getSPDenormModeValue().
getFPTernOp()
static SDValue getFPTernOp (SelectionDAG & DAG, unsigned Opcode, const SDLoc & SL, EVT VT, SDValue A, SDValue B, SDValue C, SDValue GlueChain) static
Definition at line 7615 of file SIISelLowering.cpp.
References assert(), B, llvm::BitsToFloat(), C, llvm::AMDGPUISD::DIV_FIXUP, llvm::MVT::f16, llvm::MVT::f32, llvm::ISD::FABS, llvm::ISD::FMA, llvm::AMDGPUISD::FMA_W_CHAIN, llvm::ISD::FMUL, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::SITargetLowering::getSetCCResultType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MVT::i32, llvm_unreachable, llvm::MVT::Other, r0(), r1(), r2(), r3(), llvm::AMDGPUISD::RCP, llvm::ISD::SELECT, and llvm::ISD::SETOGT.
Referenced by getSPDenormModeValue().
getLoadExtOrTrunc()
static SDValue getLoadExtOrTrunc (SelectionDAG & DAG, ISD::LoadExtType ExtType, SDValue Op, const SDLoc & SL, EVT VT) static
Definition at line 7254 of file SIISelLowering.cpp.
References llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::BITCAST, llvm::EVT::bitsLT(), llvm::EVT::changeTypeToInteger(), AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::TargetLowering::expandUnalignedLoad(), llvm::ISD::EXTLOAD, AMDGPUAS::FLAT_ADDRESS, llvm::MemSDNode::getAAInfo(), llvm::MemSDNode::getAddressSpace(), llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::SelectionDAG::getBuildVector(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MachineMemOperand::getFlags(), llvm::GCNSubtarget::getGeneration(), llvm::MachineFunction::getInfo(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::GCNSubtarget::getMaxPrivateElementSize(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::LoadSDNode::getOffset(), llvm::MemSDNode::getPointerInfo(), llvm::GCNSubtarget::getScalarizeGlobalBehavior(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSize(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getZeroExtendInReg(), AMDGPUAS::GLOBAL_ADDRESS, llvm::GCNSubtarget::hasDwordx3LoadStores(), llvm::SIMachineFunctionInfo::hasFlatScratchInit(), llvm::GCNSubtarget::hasLDSMisalignedBug(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::SDNode::isDivergent(), llvm::EVT::isFloatingPoint(), llvm::MemSDNode::isInvariant(), llvm::SITargetLowering::isMemOpHasNoClobberedMemOperand(), llvm::EVT::isPow2VectorType(), llvm::EVT::isSimple(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm_unreachable, llvm::SPII::Load, AMDGPUAS::LOCAL_ADDRESS, N, llvm::ISD::NON_EXTLOAD, AMDGPUAS::PRIVATE_ADDRESS, llvm::SmallVectorTemplateBase< T >::push_back(), AMDGPUAS::REGION_ADDRESS, llvm::TargetLowering::scalarizeVectorLoad(), llvm::ISD::SEXTLOAD, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::ISD::SRL, llvm::ISD::TRUNCATE, llvm::ISD::UNINDEXED, llvm::GCNSubtarget::useDS128(), llvm::AMDGPUTargetLowering::WidenVectorLoad(), llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZEXTLOAD.
getMad64_32()
static SDValue getMad64_32 (SelectionDAG & DAG, const SDLoc & SL, EVT VT, SDValue N0, SDValue N1, SDValue N2, bool Signed) static
Definition at line 9498 of file SIISelLowering.cpp.
References llvm::ISD::ADDCARRY, llvm::ISD::ANY_EXTEND, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::GCNSubtarget::hasMad64_32(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::EVT::isVector(), llvm::AMDGPUISD::MAD_I64_I32, llvm::AMDGPUISD::MAD_U64_U32, llvm::ISD::MUL, llvm::AMDGPUTargetLowering::numBitsSigned(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), llvm::ISD::SIGN_EXTEND, std::swap(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
getMOVRELDPseudo()
static unsigned getMOVRELDPseudo (const SIRegisterInfo & TRI, const TargetRegisterClass * VecRC) static
Definition at line 3468 of file SIISelLowering.cpp.
References llvm_unreachable.
Referenced by emitIndirectDst().
getPermuteMask()
static uint32_t getPermuteMask (SelectionDAG & DAG, SDValue V) static
Definition at line 8213 of file SIISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::AssertZext, llvm::AMDGPUISD::BFE_U32, llvm::ISD::BITCAST, llvm::tgtok::Bits, llvm::ISD::BUILD_VECTOR, C, llvm::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::dyn_cast(), llvm::MipsISD::Ext, llvm::ISD::FABS, llvm::AMDGPUISD::FP_CLASS, llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SDNode::getConstantOperandVal(), getConstantPermuteMask(), llvm::SelectionDAG::getContext(), llvm::GCNSubtarget::getInstrInfo(), llvm::EVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSelect(), llvm::SITargetLowering::getSubtarget(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::SDValue::hasOneUse(), I, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, isBoolSGPR(), llvm::SDNode::isDivergent(), llvm::ConstantFPSDNode::isInfinity(), llvm::ConstantFPSDNode::isNegative(), llvm::isShiftedMask_64(), llvm::BitmaskEnumDetail::Mask(), llvm::SIInstrFlags::N_INFINITY, llvm::SIInstrFlags::N_NORMAL, llvm::SIInstrFlags::N_SUBNORMAL, llvm::SIInstrFlags::N_ZERO, llvm::ISD::OR, llvm::SIInstrFlags::P_INFINITY, llvm::SIInstrFlags::P_NORMAL, llvm::SIInstrFlags::P_SUBNORMAL, llvm::SIInstrFlags::P_ZERO, llvm::AMDGPUISD::PERM, llvm::SIInstrInfo::pseudoToMCOpcode(), llvm::SIInstrFlags::Q_NAN, llvm::SIInstrFlags::S_NAN, llvm::ISD::SETCC, llvm::ISD::SETO, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::AMDGPUTargetLowering::split64BitValue(), llvm::ISD::SRL, std::swap(), TII, llvm::MVT::v2i32, X, llvm::ISD::XOR, Y, and llvm::ISD::ZERO_EXTEND.
getSPDenormModeValue()
static const SDValue getSPDenormModeValue (int SPDenormMode, SelectionDAG & DAG, const SDLoc & SL, const GCNSubtarget * ST) static
Definition at line 7692 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), assert(), llvm::AMDGPUISD::ATOMIC_CMP_SWAP, llvm::ISD::BITCAST, llvm::AMDGPUISD::COS_HW, llvm::AMDGPUISD::CVT_F32_UBYTE0, llvm::AMDGPUISD::DENORM_MODE, llvm::AMDGPUISD::DIV_FIXUP, llvm::AMDGPUISD::DIV_FMAS, llvm::AMDGPUISD::DIV_SCALE, llvm::dyn_cast(), llvm::TargetLowering::expandUnalignedStore(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FCOS, AMDGPUAS::FLAT_ADDRESS, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FNEG, FP_DENORM_FLUSH_IN_FLUSH_OUT, FP_DENORM_FLUSH_NONE, llvm::AMDGPUISD::FRACT, llvm::ISD::FSIN, llvm::MemSDNode::getAddressSpace(), llvm::MemSDNode::getAlignment(), llvm::ConstantSDNode::getAPIntValue(), llvm::MemSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::SelectionDAG::getBuildVector(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SDNode::getFlags(), getFPBinOp(), getFPTernOp(), llvm::APInt::getHighBitsSet(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::GCNSubtarget::getMaxPrivateElementSize(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getRoot(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::APInt::getSExtValue(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTruncStore(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), AMDGPUAS::GLOBAL_ADDRESS, llvm::MVT::Glue, llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::GCNSubtarget::hasDenormModeInst(), llvm::GCNSubtarget::hasDwordx3LoadStores(), llvm::SIMachineFunctionInfo::hasFlatScratchInit(), hasFP32Denormals(), hasFP64FP16Denormals(), llvm::GCNSubtarget::hasLDSMisalignedBug(), llvm::SDNodeFlags::hasNoUnsignedWrap(), llvm::SDNode::hasOneUse(), llvm::AMDGPUSubtarget::hasTrigReducedRange(), llvm::GCNSubtarget::hasUsableDivScaleConditionOutput(), llvm::GCNSubtarget::hasUsableDSOffset(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::AMDGPU::Hwreg::ID_MODE, llvm::AtomicSDNode::isCompareAndSwap(), llvm::SITargetLowering::isFlatGlobalAddrSpace(), llvm::SITargetLowering::isLegalAddressingMode(), llvm_unreachable, AMDGPUAS::LOCAL_ADDRESS, llvm::SelectionDAG::MaskedValueIsZero(), Mode, N, llvm::AMDGPU::Hwreg::OFFSET_SHIFT_, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::TargetMachine::Options, llvm::ISD::OR, llvm::MVT::Other, AMDGPUAS::PRIVATE_ADDRESS, llvm::AMDGPUISD::RCP, AMDGPUAS::REGION_ADDRESS, llvm::TargetLowering::scalarizeVectorStore(), llvm::ISD::SETEQ, llvm::SDNodeFlags::setNoUnsignedWrap(), llvm::AMDGPUISD::SETREG, llvm::SelectionDAG::setRoot(), llvm::ISD::SHL, llvm::AMDGPUISD::SIN_HW, llvm::AMDGPUTargetLowering::SplitVectorStore(), llvm::SPII::Store, llvm::ISD::STORE, llvm::ISD::TokenFactor, llvm::TargetOptions::UnsafeFPMath, llvm::SelectionDAG::UpdateNodeOperands(), llvm::GCNSubtarget::useDS128(), llvm::MVT::v2i32, llvm::AMDGPU::Hwreg::WIDTH_M1_SHIFT_, X, llvm::ISD::XOR, and Y.
getSplatConstantFP()
static ConstantFPSDNode* getSplatConstantFP (SDValue Op) static
Definition at line 9077 of file SIISelLowering.cpp.
References llvm::APFloat::bitcastToAPInt(), C, llvm::AMDGPUISD::CLAMP, llvm::APFloatBase::cmpGreaterThan, llvm::APFloat::compare(), llvm::AMDGPU::SIModeRegisterDefaults::DX10Clamp, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::AMDGPUISD::FMAX_LEGACY, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN_LEGACY, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::MachineFunction::getInfo(), llvm::GCNSubtarget::getInstrInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::AMDGPUMachineFunction::getMode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SITargetLowering::getSubtarget(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::AMDGPUSubtarget::has16BitInsts(), llvm::GCNSubtarget::hasMed3_16(), llvm::GCNSubtarget::hasMin3Max3_16(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::AMDGPUSubtarget::hasVOP3PInsts(), llvm::MVT::i16, llvm::MVT::i32, Info, llvm::ConstantFPSDNode::isExactlyValue(), llvm::SIInstrInfo::isInlineConstant(), llvm::SelectionDAG::isKnownNeverSNaN(), llvm::EVT::isVector(), minMaxOpcToMin3Max3Opc(), llvm::ISD::SMAX, llvm::ISD::SMIN, TII, llvm::ISD::UMAX, llvm::ISD::UMIN, and llvm::MVT::v2f16.
hasCFUser()
static bool hasCFUser (const Value * V, SmallPtrSet< const Value *, 16 > & Visited) static
Definition at line 11007 of file SIISelLowering.cpp.
References llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::Value::users().
Referenced by llvm::SITargetLowering::requiresUniformRegister().
hasFP32Denormals()
static bool hasFP32Denormals (const MachineFunction & MF) static
Definition at line 98 of file SIISelLowering.cpp.
References llvm::AMDGPU::SIModeRegisterDefaults::FP32Denormals, llvm::MachineFunction::getInfo(), llvm::AMDGPUMachineFunction::getMode(), and Info.
Referenced by llvm::SITargetLowering::denormalsEnabledForType(), getSPDenormModeValue(), isClampZeroToOne(), llvm::SITargetLowering::isFMADLegalForFAddFSub(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), and llvm::SITargetLowering::isFPExtFoldable().
hasFP64FP16Denormals()
static bool hasFP64FP16Denormals (const MachineFunction & MF) static
Definition at line 103 of file SIISelLowering.cpp.
References llvm::AMDGPU::SIModeRegisterDefaults::FP64FP16Denormals, llvm::MachineFunction::getInfo(), llvm::AMDGPUMachineFunction::getMode(), and Info.
Referenced by llvm::SITargetLowering::denormalsEnabledForType(), getSPDenormModeValue(), isClampZeroToOne(), llvm::SITargetLowering::isFMADLegalForFAddFSub(), and llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd().
isBoolSGPR()
static bool isBoolSGPR (SDValue V) static
Definition at line 8176 of file SIISelLowering.cpp.
References llvm::ISD::AND, llvm::AMDGPUISD::FP_CLASS, llvm::SDValue::getOpcode(), llvm::SDValue::getValueType(), llvm::MVT::i1, llvm::ISD::OR, llvm::ISD::SETCC, and llvm::ISD::XOR.
Referenced by getPermuteMask().
isClampZeroToOne()
static bool isClampZeroToOne (SDValue A, SDValue B) static
Definition at line 9212 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetOptions::AllowFPOpFusion, llvm::AMDGPUTargetLowering::allUsesHaveSourceMods(), llvm::ISD::BITCAST, llvm::EVT::changeTypeToInteger(), llvm::AMDGPUISD::CLAMP, llvm::AMDGPU::SIModeRegisterDefaults::DX10Clamp, llvm::dyn_cast(), E, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f16, llvm::MVT::f32, llvm::ISD::FABS, llvm::ISD::FADD, llvm::FPOpFusion::Fast, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FSUB, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), llvm::SDNode::getFlags(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::AMDGPUMachineFunction::getMode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSelectCC(), llvm::EVT::getSizeInBits(), llvm::SITargetLowering::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SDNodeFlags::hasAllowContract(), hasFP32Denormals(), hasFP64FP16Denormals(), llvm::GCNSubtarget::hasMadF16(), llvm::SDValue::hasOneUse(), I, llvm::MVT::i32, llvm::MVT::i64, Info, llvm::MipsISD::Ins, llvm::EVT::isByteSized(), llvm::SelectionDAG::isConstantIntBuildVectorOrConstantInt(), llvm::SDNode::isDivergent(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::TargetLoweringBase::isOperationLegal(), llvm::SDValue::isUndef(), llvm::TargetMachine::Options, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SETEQ, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SRL, std::swap(), llvm::ISD::TRUNCATE, llvm::ISD::UMAX, llvm::ISD::UMIN, and llvm::TargetOptions::UnsafeFPMath.
isCopyFromRegOfInlineAsm()
static LLVM_ATTRIBUTE_UNUSED bool isCopyFromRegOfInlineAsm (const SDNode * N) static
Definition at line 10863 of file SIISelLowering.cpp.
References assert(), llvm::ISD::CopyFromReg, llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ISD::INLINEASM, and llvm::ISD::INLINEASM_BR.
Referenced by llvm::SITargetLowering::isSDNodeSourceOfDivergence().
isFrameIndexOp()
static bool isFrameIndexOp (SDValue Op) static
Definition at line 10287 of file SIISelLowering.cpp.
References llvm::ISD::AssertZext, llvm::SDValue::getOpcode(), and llvm::SDValue::getOperand().
Referenced by llvm::SITargetLowering::legalizeTargetIndependentNode().
loadM0FromVGPR()
static MachineBasicBlock::iterator loadM0FromVGPR (const SIInstrInfo * TII, MachineBasicBlock & MBB, MachineInstr & MI, unsigned InitResultReg, unsigned PhiReg, int Offset, bool UseGPRIdxMode, bool IsIndirectSrc) static
Definition at line 3276 of file SIISelLowering.cpp.
References llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), emitLoadM0FromVGPRLoop(), llvm::MachineInstr::getDebugLoc(), llvm::SIInstrInfo::getNamedOperand(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::GCNSubtarget::isWave32(), MRI, splitBlockForLoop(), llvm::ARM_MB::ST, and TRI.
Referenced by emitIndirectDst(), and emitIndirectSrc().
lowerFCMPIntrinsic()
static SDValue lowerFCMPIntrinsic (const SITargetLowering & TLI, SDNode * N, SelectionDAG & DAG) static
Definition at line 4239 of file SIISelLowering.cpp.
References llvm::EVT::bitsEq(), llvm::MVT::f16, llvm::MVT::f32, llvm::ISD::FP_EXTEND, llvm::SelectionDAG::getCondCode(), llvm::SelectionDAG::getContext(), llvm::getFCmpCondCode(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SITargetLowering::getSubtarget(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::TargetLoweringBase::isTypeLegal(), llvm::AMDGPUISD::SETCC, and llvm::AMDGPU::HSAMD::Kernel::CodeProps::Key::WavefrontSize.
Referenced by parseTexFail().
lowerICMPIntrinsic()
static SDValue lowerICMPIntrinsic (const SITargetLowering & TLI, SDNode * N, SelectionDAG & DAG) static
Definition at line 4203 of file SIISelLowering.cpp.
References llvm::EVT::bitsEq(), llvm::SelectionDAG::getCondCode(), llvm::SelectionDAG::getContext(), llvm::getICmpCondCode(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SITargetLowering::getSubtarget(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::i16, llvm::MVT::i32, llvm::CmpInst::isSigned(), llvm::TargetLoweringBase::isTypeLegal(), llvm::AMDGPUISD::SETCC, llvm::ISD::SIGN_EXTEND, llvm::AMDGPU::HSAMD::Kernel::CodeProps::Key::WavefrontSize, and llvm::ISD::ZERO_EXTEND.
Referenced by parseTexFail().
mayTailCallThisCC()
static bool mayTailCallThisCC (CallingConv::ID CC) static
Return true if we might ever do TCO for calls with this calling convention.
Definition at line 2585 of file SIISelLowering.cpp.
References llvm::CallingConv::C, and canGuaranteeTCO().
Referenced by llvm::SITargetLowering::isEligibleForTailCallOptimization().
memVTFromAggregate()
static MVT memVTFromAggregate (Type * Ty) static
Definition at line 880 of file SIISelLowering.cpp.
References assert(), llvm::Type::FloatTyID, getBitWidth(), llvm::Type::getContainedType(), llvm::SequentialType::getElementType(), llvm::SequentialType::getNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::getVT(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, llvm::Type::isIntegerTy(), llvm::Type::isStructTy(), llvm::Type::isVectorTy(), llvm_unreachable, and llvm::Log2_32_Ceil().
Referenced by llvm::SITargetLowering::getTgtMemIntrinsic().
minMaxOpcToMin3Max3Opc()
static unsigned minMaxOpcToMin3Max3Opc (unsigned Opc) static
Definition at line 9018 of file SIISelLowering.cpp.
References llvm::dyn_cast(), llvm::AMDGPUISD::FMAX3, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::AMDGPUISD::FMIN3, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::GCNSubtarget::hasMed3_16(), llvm::MVT::i16, llvm::MVT::i32, llvm_unreachable, llvm::APInt::sge(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SMAX, llvm::AMDGPUISD::SMAX3, llvm::AMDGPUISD::SMED3, llvm::ISD::SMIN, llvm::AMDGPUISD::SMIN3, llvm::ISD::TRUNCATE, llvm::APInt::uge(), llvm::ISD::UMAX, llvm::AMDGPUISD::UMAX3, llvm::AMDGPUISD::UMED3, llvm::ISD::UMIN, llvm::AMDGPUISD::UMIN3, and llvm::ISD::ZERO_EXTEND.
Referenced by getSplatConstantFP().
parseCachePolicy()
static bool parseCachePolicy (SDValue CachePolicy, SelectionDAG & DAG, SDValue * GLC, SDValue * SLC, SDValue * DLC) static
Definition at line 5211 of file SIISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SelectionDAG::getTargetConstant(), and llvm::MVT::i32.
Referenced by parseTexFail().
parseTexFail()
static bool parseTexFail (SDValue TexFailCtrl, SelectionDAG & DAG, SDValue * TFE, SDValue * LWE, bool & IsTexFail) static
Definition at line 5316 of file SIISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, assert(), llvm::AMDGPUISD::BFE_I32, llvm::AMDGPUISD::BFE_U32, llvm::AMDGPUISD::BUFFER_LOAD, llvm::ISD::CONCAT_VECTORS, constructRetValue(), llvm::AMDGPUISD::COS_HW, llvm::countPopulation(), llvm::AMDGPUISD::CVT_PK_I16_I32, llvm::AMDGPUISD::CVT_PK_U16_U32, llvm::AMDGPUISD::CVT_PKNORM_I16_F32, llvm::AMDGPUISD::CVT_PKNORM_U16_F32, llvm::AMDGPUISD::CVT_PKRTZ_F16_F32, llvm::LLVMContext::diagnose(), llvm::AMDGPUFunctionArgInfo::DISPATCH_ID, llvm::AMDGPUFunctionArgInfo::DISPATCH_PTR, llvm::AMDGPUISD::DIV_FIXUP, llvm::AMDGPUISD::DIV_FMAS, llvm::AMDGPUISD::DIV_SCALE, emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::ExtractVectorElements(), llvm::MVT::f16, llvm::MVT::f32, llvm::AMDGPUISD::FDOT2, llvm::AMDGPUISD::FFBH_I32, llvm::ISD::FMAXNUM, llvm::AMDGPUISD::FMED3, llvm::ISD::FMINNUM, llvm::AMDGPUISD::FMUL_LEGACY, llvm::AMDGPUISD::FP_CLASS, llvm::AMDGPUISD::FRACT, llvm::DataLayout::getABITypeAlignment(), llvm::SelectionDAG::getBitcast(), getBuildDwordsVector(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SDLoc::getDebugLoc(), llvm::SelectionDAG::getEntryNode(), llvm::Type::getFltSemantics(), llvm::MachineFunction::getFunction(), llvm::GCNSubtarget::getGeneration(), llvm::MachineFunction::getInfo(), llvm::APFloat::getLargest(), llvm::GCNSubtarget::getLDSBankCount(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getMergeValues(), llvm::AMDGPU::getMIMGBaseOpcodeInfo(), llvm::AMDGPU::getMIMGDimInfo(), llvm::AMDGPU::getMIMGLZMappingInfo(), llvm::AMDGPU::getMIMGMIPMappingInfo(), llvm::AMDGPU::getMIMGOpcode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSize(), llvm::SITargetLowering::getSubtarget(), llvm::MachineFunction::getSubtarget(), llvm::SelectionDAG::getTargetConstant(), llvm::EVT::getTypeForEVT(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::AMDGPUTargetLowering::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::AMDGPUSubtarget::GFX10, llvm::SI::KernelInputOffsets::GLOBAL_SIZE_X, llvm::SI::KernelInputOffsets::GLOBAL_SIZE_Y, llvm::SI::KernelInputOffsets::GLOBAL_SIZE_Z, llvm::MVT::Glue, llvm::GCNSubtarget::hasD16Images(), llvm::GCNSubtarget::hasUnpackedD16VMem(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::AMDGPUFunctionArgInfo::IMPLICIT_ARG_PTR, llvm::AMDGPUFunctionArgInfo::IMPLICIT_BUFFER_PTR, llvm::AMDGPUISD::INTERP_P1LL_F16, llvm::AMDGPUISD::INTERP_P1LV_F16, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ConstantSDNode::isAllOnesValue(), llvm::AMDGPUSubtarget::isAmdHsaOrMesa(), llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::SDNode::isDivergent(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MVT::isVector(), llvm::AMDGPUFunctionArgInfo::KERNARG_SEGMENT_PTR, llvm::AMDGPUISD::LDEXP, llvm::AMDGPUTargetLowering::loadInputValue(), llvm::SI::KernelInputOffsets::LOCAL_SIZE_X, llvm::SI::KernelInputOffsets::LOCAL_SIZE_Y, llvm::SI::KernelInputOffsets::LOCAL_SIZE_Z, lowerFCMPIntrinsic(), lowerICMPIntrinsic(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::MachineMemOperand::MOLoad, llvm::AMDGPUISD::MUL_I24, llvm::AMDGPUISD::MUL_U24, llvm::SI::KernelInputOffsets::NGROUPS_X, llvm::SI::KernelInputOffsets::NGROUPS_Y, llvm::SI::KernelInputOffsets::NGROUPS_Z, parseCachePolicy(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::AMDGPUFunctionArgInfo::QUEUE_PTR, llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_LEGACY, llvm::AMDGPUISD::RSQ, llvm::AMDGPUISD::RSQ_CLAMP, llvm::AMDGPUISD::RSQ_LEGACY, llvm::AMDGPUISD::SBUFFER_LOAD, llvm::ISD::SCALAR_TO_VECTOR, llvm::SelectionDAG::setNodeMemRefs(), llvm::AMDGPUISD::SIN_HW, llvm::SmallVectorBase::size(), llvm::ARM_MB::ST, llvm::AMDGPUISD::TRIG_PREOP, llvm::RegState::Undef, llvm::MVT::v16i32, llvm::MVT::v2f16, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v8i32, llvm::SDNode::value_begin(), llvm::SDNode::value_end(), llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_X, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Y, and llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Z.
processShaderInputArgs()
static void processShaderInputArgs (SmallVectorImpl< ISD::InputArg > & Splits, CallingConv::ID CallConv, ArrayRef< ISD::InputArg > Ins, BitVector & Skipped, FunctionType * FType, SIMachineFunctionInfo * Info) static
Definition at line 1573 of file SIISelLowering.cpp.
References llvm::CallingConv::AMDGPU_PS, assert(), E, llvm::ISD::InputArg::Flags, llvm::ISD::InputArg::getOrigArgIndex(), llvm::MVT::getScalarSizeInBits(), I, llvm::ISD::ArgFlagsTy::isInReg(), llvm::SIMachineFunctionInfo::isPSInputAllocated(), llvm::ISD::ArgFlagsTy::isSplit(), llvm::ISD::ArgFlagsTy::isSplitEnd(), llvm::MVT::isVector(), llvm::SIMachineFunctionInfo::markPSInputAllocated(), llvm::SIMachineFunctionInfo::markPSInputEnabled(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::BitVector::set(), llvm::ArrayRef< T >::size(), llvm::ISD::InputArg::Used, and llvm::ISD::InputArg::VT.
Referenced by llvm::SITargetLowering::LowerFormalArguments().
reservePrivateMemoryRegs()
static void reservePrivateMemoryRegs (const TargetMachine & TM, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) static
Definition at line 1873 of file SIISelLowering.cpp.
References assert(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::GCNSubtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::TargetMachine::getOptLevel(), llvm::SIMachineFunctionInfo::getPreloadedReg(), llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasCalls(), llvm::SIFrameLowering::hasFP(), llvm::MachineFrameInfo::hasStackObjects(), llvm::AMDGPUSubtarget::isAmdHsaOrMesa(), llvm::MachineRegisterInfo::isLiveIn(), llvm::AMDGPU::isShader(), MRI, llvm::CodeGenOpt::None, llvm::AMDGPUFunctionArgInfo::PRIVATE_SEGMENT_BUFFER, llvm::AMDGPUFunctionArgInfo::PRIVATE_SEGMENT_WAVE_BYTE_OFFSET, Reg, llvm::report_fatal_error(), llvm::SIRegisterInfo::reservedPrivateSegmentBufferReg(), llvm::SIRegisterInfo::reservedPrivateSegmentWaveByteOffsetReg(), llvm::SIMachineFunctionInfo::setFrameOffsetReg(), llvm::SIMachineFunctionInfo::setHasNonSpillStackObjects(), llvm::SIMachineFunctionInfo::setScratchRSrcReg(), llvm::SIMachineFunctionInfo::setScratchWaveOffsetReg(), llvm::SIMachineFunctionInfo::setStackPtrOffsetReg(), and llvm::ARM_MB::ST.
Referenced by llvm::SITargetLowering::finalizeLowering().
setM0ToIndexFromSGPR()
static bool setM0ToIndexFromSGPR (const SIInstrInfo * TII, MachineRegisterInfo & MRI, MachineInstr & MI, int Offset, bool UseGPRIdxMode, bool IsIndirectSrc) static
Definition at line 3338 of file SIISelLowering.cpp.
References add(), llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::AMDGPU::VGPRIndexMode::DST_ENABLE, llvm::MachineInstr::getDebugLoc(), llvm::SIInstrInfo::getNamedOperand(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::SIInstrInfo::getRegisterInfo(), I, llvm::SIRegisterInfo::isSGPRClass(), llvm::RegState::Kill, llvm::MachineOperand::setIsUndef(), and llvm::AMDGPU::VGPRIndexMode::SRC0_ENABLE.
Referenced by emitIndirectDst(), and emitIndirectSrc().
splitBlockForLoop()
static std::pair<MachineBasicBlock *, MachineBasicBlock *> splitBlockForLoop (MachineInstr & MI, MachineBasicBlock & MBB, bool InstInLoop) static
Returns
{ LoopBody, Remainder }
Definition at line 3069 of file SIISelLowering.cpp.
References llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), I, llvm::MachineFunction::insert(), llvm::MachineBasicBlock::splice(), and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by llvm::SITargetLowering::emitGWSMemViolTestLoop(), and loadM0FromVGPR().
STATISTIC()
STATISTIC (NumTailCalls , "Number of tail calls")
SubIdx2Lane()
static unsigned SubIdx2Lane (unsigned Idx) static
Helper function for adjustWritemask.
Definition at line 10114 of file SIISelLowering.cpp.
vectorEltWillFoldAway()
static bool vectorEltWillFoldAway (SDValue Op) static
Definition at line 8926 of file SIISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::dyn_cast(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ISD::FCANONICALIZE, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstantFP(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::APFloat::getQNaN(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MipsISD::Hi, I, llvm::SITargetLowering::isCanonicalized(), llvm::isConstOrConstSplatFP(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SDValue::isUndef(), isUndef(), llvm::MipsISD::Lo, and llvm::MVT::v2f16.
Variable Documentation
DisableLoopAlignment
cl::opt<bool> DisableLoopAlignment("amdgpu-disable-loop-alignment", cl::desc("Do not align and prefetch loops"), cl::init(false)) static
Referenced by llvm::SITargetLowering::getPrefLoopAlignment().