LLVM: lib/Target/AMDGPU/SILoadStoreOptimizer.cpp File Reference
SILoadStoreOptimizer.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIInstrInfo.h"
#include "SIRegisterInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <iterator>
#include <utility>
Macros
#define DEBUG_TYPE "si-load-store-opt"
Enumerations
enum InstClassEnum
enum RegisterEnum
Functions
INITIALIZE_PASS_BEGIN (SILoadStoreOptimizer, DEBUG_TYPE, "SI Load Store Optimizer", false, false) INITIALIZE_PASS_END(SILoadStoreOptimizer
static void moveInstsAfter (MachineBasicBlock::iterator I, ArrayRef< MachineInstr *> InstsToMove)
static void addDefsUsesToList (const MachineInstr &MI, DenseSet< unsigned > &RegDefs, DenseSet< unsigned > &PhysRegUses)
static bool memAccessesCanBeReordered (MachineBasicBlock::iterator A, MachineBasicBlock::iterator B, AliasAnalysis *AA)
static bool addToListsIfDependent (MachineInstr &MI, DenseSet< unsigned > &RegDefs, DenseSet< unsigned > &PhysRegUses, SmallVectorImpl< MachineInstr *> &Insts)
static bool canMoveInstsAcrossMemOp (MachineInstr &MemOp, ArrayRef< MachineInstr *> InstsToMove, AliasAnalysis *AA)
static MachineMemOperand * combineKnownAdjacentMMOs (MachineFunction &MF, const MachineMemOperand *A, const MachineMemOperand *B)
static unsigned getBufferFormatWithCompCount (unsigned OldFormat, unsigned ComponentCount, const MCSubtargetInfo &STI)
Variables
DEBUG_TYPE
SI Load Store Optimizer
SI Load Store false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-load-store-opt"
Definition at line 91 of file SILoadStoreOptimizer.cpp.
Enumeration Type Documentation
InstClassEnum
enum InstClassEnum
Definition at line 94 of file SILoadStoreOptimizer.cpp.
RegisterEnum
enum RegisterEnum
Definition at line 106 of file SILoadStoreOptimizer.cpp.
Function Documentation
addDefsUsesToList()
static void addDefsUsesToList (const MachineInstr & MI, DenseSet< unsigned > & RegDefs, DenseSet< unsigned > & PhysRegUses) static
Definition at line 580 of file SILoadStoreOptimizer.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::Register::isPhysicalRegister(), and llvm::MachineInstr::operands().
Referenced by addToListsIfDependent(), and getBufferFormatWithCompCount().
addToListsIfDependent()
static bool addToListsIfDependent (MachineInstr & MI, DenseSet< unsigned > & RegDefs, DenseSet< unsigned > & PhysRegUses, SmallVectorImpl< MachineInstr *> & Insts) static
Definition at line 604 of file SILoadStoreOptimizer.cpp.
References addDefsUsesToList(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::Register::isPhysicalRegister(), llvm::MachineInstr::operands(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by getBufferFormatWithCompCount().
canMoveInstsAcrossMemOp()
static bool canMoveInstsAcrossMemOp (MachineInstr & MemOp, ArrayRef< MachineInstr *> InstsToMove, AliasAnalysis * AA) static
Definition at line 630 of file SILoadStoreOptimizer.cpp.
References assert(), llvm::MachineInstr::mayLoadOrStore(), and memAccessesCanBeReordered().
Referenced by getBufferFormatWithCompCount().
combineKnownAdjacentMMOs()
static MachineMemOperand* combineKnownAdjacentMMOs (MachineFunction & MF, const MachineMemOperand * A, const MachineMemOperand * B) static
Definition at line 646 of file SILoadStoreOptimizer.cpp.
References assert(), llvm::countTrailingZeros(), da, llvm::MachineFunction::getMachineMemOperand(), llvm::SIInstrInfo::getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineMemOperand::getOffset(), llvm::MachineMemOperand::getSize(), llvm::max(), llvm::SIInstrFlags::MIMG, op, llvm::MachineMemOperand::setOffset(), Size, and TII.
Referenced by getBufferFormatWithCompCount().
getBufferFormatWithCompCount()
static unsigned getBufferFormatWithCompCount (unsigned OldFormat, unsigned ComponentCount, const MCSubtargetInfo & STI) static
Definition at line 696 of file SILoadStoreOptimizer.cpp.
References llvm::abs(), add(), llvm::MachineInstrBuilder::add(), addDefsUsesToList(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), addToListsIfDependent(), assert(), llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::AMDGPU::GcnBufferFormatInfo::BitsPerComp, llvm::AMDGPUISD::BUFFER_LOAD, llvm::AMDGPUISD::BUFFER_STORE, llvm::BuildMI(), canMoveInstsAcrossMemOp(), llvm::MachineInstrBuilder::cloneMergedMemRefs(), combineKnownAdjacentMMOs(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::countPopulation(), llvm::MachineOperand::CreateImm(), llvm::MachineOperand::CreateReg(), llvm::dbgs(), llvm::RegState::Dead, llvm::tgtok::Def, llvm::RegState::Define, llvm::MachineInstr::dump(), E, llvm::MachineBasicBlock::end(), llvm::AMDGPU::GcnBufferFormatInfo::Format, llvm::SIInstrInfo::getAddNoCarry(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::AMDGPU::getGcnBufferFormatInfo(), llvm::AMDGPU::getGlobalSaddrOp(), llvm::MachineOperand::getImm(), llvm::GCNSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::AMDGPU::getMaskedMIMGOp(), llvm::AMDGPU::getMTBUFBaseOpcode(), llvm::AMDGPU::getMTBUFOpcode(), llvm::AMDGPU::getMUBUFBaseOpcode(), llvm::AMDGPU::getMUBUFOpcode(), llvm::SIInstrInfo::getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SIInstrInfo::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::GCNSubtarget::getTargetLowering(), llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::GCNSubtarget::hasDwordx3LoadStores(), llvm::MachineInstr::hasOrderedMemoryRef(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineBasicBlock::instrs(), llvm::MachineOperand::isImm(), llvm::SIInstrInfo::isInlineConstant(), llvm::SITargetLowering::isLegalGlobalAddressingMode(), llvm::MachineOperand::isReg(), llvm::isUInt< 8 >(), llvm::RegState::Kill, llvm::GCNSubtarget::ldsRequiresM0Init(), LLVM_DEBUG, llvm_unreachable, llvm::GCNSubtarget::loadStoreOptEnabled(), llvm::Match, llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), memAccessesCanBeReordered(), MI, llvm::SIInstrFlags::MIMG, Modified, moveInstsAfter(), MRI, llvm::None, llvm::AMDGPU::GcnBufferFormatInfo::NumFormat, P, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::MachineOperand::setImm(), std::swap(), TII, TRI, and llvm::LPAC::UNKNOWN.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (SILoadStoreOptimizer , DEBUG_TYPE , "SI Load Store Optimizer" , false , false)
memAccessesCanBeReordered()
static bool memAccessesCanBeReordered (MachineBasicBlock::iterator A, MachineBasicBlock::iterator B, AliasAnalysis * AA) static
Definition at line 593 of file SILoadStoreOptimizer.cpp.
Referenced by canMoveInstsAcrossMemOp(), and getBufferFormatWithCompCount().
moveInstsAfter()
static void moveInstsAfter (MachineBasicBlock::iterator I, ArrayRef< MachineInstr *> InstsToMove) static
Definition at line 570 of file SILoadStoreOptimizer.cpp.
References I, llvm::MachineBasicBlock::insert(), and MI.
Referenced by getBufferFormatWithCompCount().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 559 of file SILoadStoreOptimizer.cpp.
false
SI Load Store false
Definition at line 559 of file SILoadStoreOptimizer.cpp.
Optimizer
SI Load Store Optimizer
Definition at line 559 of file SILoadStoreOptimizer.cpp.