LLVM: lib/Target/AMDGPU/SIMachineFunctionInfo.cpp File Reference
SIMachineFunctionInfo.cpp File Reference
#include "SIMachineFunctionInfo.h"
#include "AMDGPUArgumentUsageInfo.h"
#include "AMDGPUSubtarget.h"
#include "SIRegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/Optional.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Function.h"
#include <cassert>
#include <vector>
Macros
#define MAX_LANES 64
Functions
static bool isCalleeSavedReg (const MCPhysReg *CSRegs, MCPhysReg Reg)
static yaml::StringValue regToString (unsigned Reg, const TargetRegisterInfo &TRI)
static Optional< yaml::SIArgumentInfo > convertArgumentInfo (const AMDGPUFunctionArgInfo &ArgInfo, const TargetRegisterInfo &TRI)
Macro Definition Documentation
MAX_LANES
#define MAX_LANES 64
Definition at line 25 of file SIMachineFunctionInfo.cpp.
Function Documentation
convertArgumentInfo()
static Optional<yaml::SIArgumentInfo> convertArgumentInfo (const AMDGPUFunctionArgInfo & ArgInfo, const TargetRegisterInfo & TRI) static
Definition at line 428 of file SIMachineFunctionInfo.cpp.
References Arg, llvm::yaml::SIArgument::createArgument(), llvm::AMDGPUFunctionArgInfo::DispatchID, llvm::yaml::SIArgumentInfo::DispatchID, llvm::AMDGPUFunctionArgInfo::DispatchPtr, llvm::yaml::SIArgumentInfo::DispatchPtr, llvm::AMDGPUFunctionArgInfo::FlatScratchInit, llvm::yaml::SIArgumentInfo::FlatScratchInit, llvm::AMDGPUFunctionArgInfo::ImplicitArgPtr, llvm::yaml::SIArgumentInfo::ImplicitArgPtr, llvm::AMDGPUFunctionArgInfo::ImplicitBufferPtr, llvm::yaml::SIArgumentInfo::ImplicitBufferPtr, llvm::AMDGPUFunctionArgInfo::KernargSegmentPtr, llvm::yaml::SIArgumentInfo::KernargSegmentPtr, llvm::yaml::SIArgument::Mask, llvm::None, llvm::printReg(), llvm::AMDGPUFunctionArgInfo::PrivateSegmentBuffer, llvm::yaml::SIArgumentInfo::PrivateSegmentBuffer, llvm::AMDGPUFunctionArgInfo::PrivateSegmentSize, llvm::yaml::SIArgumentInfo::PrivateSegmentSize, llvm::AMDGPUFunctionArgInfo::PrivateSegmentWaveByteOffset, llvm::yaml::SIArgumentInfo::PrivateSegmentWaveByteOffset, llvm::AMDGPUFunctionArgInfo::QueuePtr, llvm::yaml::SIArgumentInfo::QueuePtr, llvm::yaml::SIArgument::RegisterName, llvm::yaml::SIArgument::StackOffset, TRI, llvm::yaml::StringValue::Value, llvm::AMDGPUFunctionArgInfo::WorkGroupIDX, llvm::yaml::SIArgumentInfo::WorkGroupIDX, llvm::AMDGPUFunctionArgInfo::WorkGroupIDY, llvm::yaml::SIArgumentInfo::WorkGroupIDY, llvm::AMDGPUFunctionArgInfo::WorkGroupIDZ, llvm::yaml::SIArgumentInfo::WorkGroupIDZ, llvm::AMDGPUFunctionArgInfo::WorkGroupInfo, llvm::yaml::SIArgumentInfo::WorkGroupInfo, llvm::AMDGPUFunctionArgInfo::WorkItemIDX, llvm::yaml::SIArgumentInfo::WorkItemIDX, llvm::AMDGPUFunctionArgInfo::WorkItemIDY, llvm::yaml::SIArgumentInfo::WorkItemIDY, llvm::AMDGPUFunctionArgInfo::WorkItemIDZ, and llvm::yaml::SIArgumentInfo::WorkItemIDZ.
isCalleeSavedReg()
static bool isCalleeSavedReg (const MCPhysReg * CSRegs, MCPhysReg Reg) static
Definition at line 239 of file SIMachineFunctionInfo.cpp.
References I.
Referenced by llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPR(), and INITIALIZE_PASS().
regToString()
static yaml::StringValue regToString (unsigned Reg, const TargetRegisterInfo & TRI) static
Definition at line 417 of file SIMachineFunctionInfo.cpp.
References llvm::printReg(), and llvm::yaml::StringValue::Value.
Referenced by llvm::WebAssemblyAsmPrinter::runOnMachineFunction().