LLVM: lib/Transforms/Utils/SimplifyIndVar.cpp File Reference
SimplifyIndVar.cpp File Reference
#include "llvm/Transforms/Utils/SimplifyIndVar.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/Local.h"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "indvars"
Functions
STATISTIC (NumElimIdentity, "Number of IV identities eliminated")
STATISTIC (NumElimOperand, "Number of IV operands folded into a use")
STATISTIC (NumFoldedUser, "Number of IV users folded into a constant")
STATISTIC (NumElimRem, "Number of IV remainder operations eliminated")
STATISTIC (NumSimplifiedSDiv, "Number of IV signed division operations converted to unsigned division")
STATISTIC (NumSimplifiedSRem, "Number of IV signed remainder operations converted to unsigned remainder")
STATISTIC (NumElimCmp, "Number of IV comparisons eliminated")
static bool willNotOverflow (ScalarEvolution *SE, Instruction::BinaryOps BinOp, bool Signed, const SCEV *LHS, const SCEV *RHS)
static Instruction * GetLoopInvariantInsertPosition (Loop *L, Instruction *Hint)
static void pushIVUsers (Instruction *Def, Loop *L, SmallPtrSet< Instruction *, 16 > &Simplified, SmallVectorImpl< std::pair< Instruction *, Instruction *> > &SimpleIVUsers)
Add all uses of Def to the current IV's worklist.
static bool isSimpleIVUser (Instruction *I, const Loop *L, ScalarEvolution *SE)
Return true if this instruction generates a simple SCEV expression in terms of that IV.
bool llvm::simplifyUsersOfIV (PHINode *CurrIV, ScalarEvolution *SE, DominatorTree *DT, LoopInfo *LI, SmallVectorImpl< WeakTrackingVH > &Dead, SCEVExpander &Rewriter, IVVisitor *V=nullptr)
simplifyUsersOfIV - Simplify instructions that use this induction variable by using ScalarEvolution to analyze the IV's recurrence.
bool llvm::simplifyLoopIVs (Loop *L, ScalarEvolution *SE, DominatorTree *DT, LoopInfo *LI, SmallVectorImpl< WeakTrackingVH > &Dead)
SimplifyLoopIVs - Simplify users of induction variables within this loop.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "indvars"
Definition at line 33 of file SimplifyIndVar.cpp.
Referenced by llvm::simplifyLoopIVs().
Function Documentation
GetLoopInvariantInsertPosition()
static Instruction* GetLoopInvariantInsertPosition (Loop * L, Instruction * Hint) static
Definition at line 651 of file SimplifyIndVar.cpp.
References llvm::MCID::Add, C, llvm::dbgs(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ConstantRange::getUnsignedMin(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), I, llvm::Instruction::isExact(), LLVM_DEBUG, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::Value::replaceAllUsesWith(), Rewriter, llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::Instruction::setIsExact(), llvm::APInt::uge(), llvm::Value::users(), and willNotOverflow().
isSimpleIVUser()
static bool isSimpleIVUser (Instruction * I, const Loop * L, ScalarEvolution * SE) static
Return true if this instruction generates a simple SCEV expression in terms of that IV.
This is similar to IVUsers' isInteresting() but processes each instruction non-recursively when the operand is already known to be a simpleIVUser.
Definition at line 825 of file SimplifyIndVar.cpp.
References assert(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getSCEV(), llvm::Value::getType(), llvm::isInstructionTriviallyDead(), llvm::ScalarEvolution::isSCEVable(), N, llvm::SmallVectorImpl< T >::pop_back_val(), pushIVUsers(), llvm::JumpTable::Simplified, llvm::SmallPtrSetImplBase::size(), and llvm::IVVisitor::visitCast().
pushIVUsers()
static void pushIVUsers (Instruction * Def, Loop * L, SmallPtrSet< Instruction *, 16 > & Simplified, SmallVectorImpl< std::pair< Instruction *, Instruction *> > & SimpleIVUsers) static
Add all uses of Def to the current IV's worklist.
Definition at line 791 of file SimplifyIndVar.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::Value::users().
Referenced by isSimpleIVUser().
STATISTIC() [1/7]
STATISTIC (NumElimIdentity , "Number of IV identities eliminated")
STATISTIC() [2/7]
STATISTIC (NumElimOperand , "Number of IV operands folded into a use")
STATISTIC() [3/7]
STATISTIC (NumFoldedUser , "Number of IV users folded into a constant")
STATISTIC() [4/7]
STATISTIC (NumElimRem , "Number of IV remainder operations eliminated")
STATISTIC() [5/7]
STATISTIC (NumSimplifiedSDiv , "Number of IV signed division operations converted to unsigned division")
STATISTIC() [6/7]
STATISTIC (NumSimplifiedSRem , "Number of IV signed remainder operations converted to unsigned remainder")
STATISTIC() [7/7]
STATISTIC (NumElimCmp , "Number of IV comparisons eliminated")
willNotOverflow()
static bool willNotOverflow (ScalarEvolution * SE, Instruction::BinaryOps BinOp, bool Signed, const SCEV * LHS, const SCEV * RHS) static
Definition at line 405 of file SimplifyIndVar.cpp.
References llvm::MCID::Add, assert(), B, llvm::LoopBase< BlockT, LoopT >::contains(), llvm::BinaryOperator::Create(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::MipsISD::Ext, llvm::SCEV::FlagAnyWrap, llvm::IntegerType::get(), llvm::UndefValue::get(), llvm::ScalarEvolution::getAddExpr(), llvm::BinaryOpIntrinsic::getBinaryOp(), llvm::Value::getContext(), llvm::ConstantInt::getFalse(), llvm::BinaryOpIntrinsic::getLHS(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getMulExpr(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Instruction::getParent(), getParent(), llvm::BinaryOpIntrinsic::getRHS(), llvm::ICmpInst::getSignedPredicate(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::CmpInst::getSwappedPredicate(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::ICmpInst::getUnsignedPredicate(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::Loop::isLoopInvariant(), llvm::BinaryOpIntrinsic::isSigned(), llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), llvm_unreachable, llvm::Loop::makeLoopInvariant(), Operation, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), SI, llvm::Value::use_empty(), and llvm::Value::users().
Referenced by GetLoopInvariantInsertPosition().