LLVM: lib/Transforms/Utils/SimplifyLibCalls.cpp File Reference
SimplifyLibCalls.cpp File Reference
#include "llvm/Transforms/Utils/SimplifyLibCalls.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/Transforms/Utils/SizeOpts.h"
Functions
static bool ignoreCallingConv (LibFunc Func)
static bool isCallingConvCCompatible (CallInst *CI)
static bool isOnlyUsedInEqualityComparison (Value *V, Value *With)
Return true if it is only used in equality comparisons with With.
static bool callHasFloatingPointArgument (const CallInst *CI)
static bool callHasFP128Argument (const CallInst *CI)
static Value * convertStrToNumber (CallInst *CI, StringRef &Str, int64_t Base)
static bool isLocallyOpenedFile (Value *File, CallInst *CI, IRBuilder<> &B, const TargetLibraryInfo *TLI)
static bool isOnlyUsedInComparisonWithZero (Value *V)
static bool canTransformToMemCmp (CallInst *CI, Value *Str, uint64_t Len, const DataLayout &DL)
static void annotateDereferenceableBytes (CallInst *CI, ArrayRef< unsigned > ArgNos, uint64_t DereferenceableBytes)
static void annotateNonNullBasedOnAccess (CallInst *CI, ArrayRef< unsigned > ArgNos)
static void annotateNonNullAndDereferenceable (CallInst *CI, ArrayRef< unsigned > ArgNos, Value *Size, const DataLayout &DL)
static Value * optimizeMemCmpConstantSize (CallInst *CI, Value *LHS, Value *RHS, uint64_t Len, IRBuilder<> &B, const DataLayout &DL)
static Value * replaceUnaryCall (CallInst *CI, IRBuilder<> &B, Intrinsic::ID IID)
static Value * valueHasFloatPrecision (Value *Val)
Return a variant of Val with float type.
static Value * optimizeDoubleFP (CallInst *CI, IRBuilder<> &B, bool isBinary, bool isPrecise=false)
Shrink double -> float functions.
static Value * optimizeUnaryDoubleFP (CallInst *CI, IRBuilder<> &B, bool isPrecise=false)
Shrink double -> float for unary functions.
static Value * optimizeBinaryDoubleFP (CallInst *CI, IRBuilder<> &B, bool isPrecise=false)
Shrink double -> float for binary functions.
static Value * optimizeTrigReflections (CallInst *Call, LibFunc Func, IRBuilder<> &B)
static Value * getPow (Value *InnerChain[33], unsigned Exp, IRBuilder<> &B)
static Value * getIntToFPVal (Value *I2F, IRBuilder<> &B)
static Value * getSqrtCall (Value *V, AttributeList Attrs, bool NoErrno, Module *M, IRBuilder<> &B, const TargetLibraryInfo *TLI)
static Value * createPowWithIntegerExponent (Value *Base, Value *Expo, Module *M, IRBuilder<> &B)
static bool isTrigLibCall (CallInst *CI)
static void insertSinCosCall (IRBuilder<> &B, Function *OrigCallee, Value *Arg, bool UseFloat, Value *&Sin, Value *&Cos, Value *&SinCos)
static bool isReportingError (Function *Callee, CallInst *CI, int StreamArg)
Variables
static cl::opt< bool > EnableUnsafeFPShrink ("enable-double-float-shrink", cl::Hidden, cl::init(false), cl::desc("Enable unsafe double to float " "shrinking for math lib calls"))
Function Documentation
annotateDereferenceableBytes()
static void annotateDereferenceableBytes (CallInst * CI, ArrayRef< unsigned > ArgNos, uint64_t DereferenceableBytes) static
Definition at line 190 of file SimplifyLibCalls.cpp.
References llvm::CallBase::addParamAttr(), F(), llvm::AttributeList::FirstArgIndex, llvm::CallBase::getArgOperand(), llvm::CallBase::getCaller(), llvm::Value::getContext(), llvm::CallBase::getDereferenceableBytes(), llvm::CallBase::getDereferenceableOrNullBytes(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::Attribute::getWithDereferenceableBytes(), llvm::max(), llvm::NullPointerIsDefined(), llvm::CallBase::paramHasAttr(), and llvm::CallBase::removeParamAttr().
Referenced by annotateNonNullAndDereferenceable(), annotateNonNullBasedOnAccess(), and llvm::LibCallSimplifier::LibCallSimplifier().
annotateNonNullAndDereferenceable()
static void annotateNonNullAndDereferenceable (CallInst * CI, ArrayRef< unsigned > ArgNos, Value * Size, const DataLayout & DL) static
Definition at line 235 of file SimplifyLibCalls.cpp.
References llvm::CallBase::addParamAttr(), llvm::AttributeList::addParamAttributes(), annotateDereferenceableBytes(), annotateNonNullBasedOnAccess(), llvm::ConstantDataArraySlice::Array, B, llvm::StringRef::begin(), llvm::tgtok::Bits, C, Callee, canTransformToMemCmp(), llvm::castToCStr(), llvm::StringRef::compare(), llvm::computeKnownBits(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< T, Inserter >::CreateIsNotNull(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::dyn_cast(), E, llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitStrChr(), llvm::emitStrDup(), llvm::emitStrLen(), llvm::emitStrNCmp(), llvm::StringRef::empty(), llvm::StringRef::end(), llvm::StringRef::find(), llvm::StringRef::find_first_not_of(), llvm::StringRef::find_first_of(), llvm::APInt::flipAllBits(), GEP, llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::getConstantDataArrayInfo(), llvm::getConstantStringInfo(), llvm::Value::getContext(), llvm::ConstantDataSequential::getElementAsInteger(), llvm::Function::getFunctionType(), llvm::IRBuilderBase::getInt(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt8(), llvm::IRBuilderBase::getInt8Ty(), llvm::IRBuilderBase::getIntN(), llvm::IRBuilderBase::getIntNTy(), llvm::Instruction::getModule(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::AttributeList::getParamAttributes(), llvm::FunctionType::getParamType(), llvm::CmpInst::getPredicate(), llvm::ConstantInt::getSExtValue(), llvm::GetStringLength(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), I, llvm::CmpInst::ICMP_ULT, llvm::isGEPBasedOnPointerToString(), llvm::Type::isIntegerTy(), llvm::isKnownNonZero(), llvm::APInt::isNonNegative(), isOnlyUsedInEqualityComparison(), llvm::isOnlyUsedInZeroEqualityComparison(), llvm::ConstantInt::isZero(), llvm::ConstantDataArraySlice::Length, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::max(), llvm::NextPowerOf2(), llvm::Align::None(), llvm::StringRef::npos, llvm::ConstantDataArraySlice::Offset, llvm::StringRef::rfind(), llvm::CallBase::setAttributes(), llvm::APInt::setBit(), SI, Size, llvm::StringRef::size(), llvm::StringRef::substr(), llvm::APInt::ule(), llvm::Value::user_begin(), llvm::Value::user_end(), X, Y, and llvm::KnownBits::Zero.
Referenced by optimizeMemCmpConstantSize().
annotateNonNullBasedOnAccess()
static void annotateNonNullBasedOnAccess (CallInst * CI, ArrayRef< unsigned > ArgNos) static
Definition at line 217 of file SimplifyLibCalls.cpp.
References llvm::CallBase::addParamAttr(), annotateDereferenceableBytes(), F(), llvm::CallBase::getArgOperand(), llvm::CallBase::getCaller(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::NullPointerIsDefined(), and llvm::CallBase::paramHasAttr().
Referenced by annotateNonNullAndDereferenceable(), and isReportingError().
callHasFloatingPointArgument()
static bool callHasFloatingPointArgument (const CallInst * CI) static
Definition at line 104 of file SimplifyLibCalls.cpp.
References llvm::any_of(), and llvm::User::operands().
Referenced by isReportingError().
callHasFP128Argument()
static bool callHasFP128Argument (const CallInst * CI) static
Definition at line 110 of file SimplifyLibCalls.cpp.
References llvm::any_of(), and llvm::User::operands().
Referenced by isReportingError().
canTransformToMemCmp()
static bool canTransformToMemCmp (CallInst * CI, Value * Str, uint64_t Len, const DataLayout & DL) static
Definition at line 175 of file SimplifyLibCalls.cpp.
References llvm::Instruction::getFunction(), llvm::Function::hasFnAttribute(), llvm::isDereferenceableAndAlignedPointer(), isOnlyUsedInComparisonWithZero(), and llvm::Align::None().
Referenced by annotateNonNullAndDereferenceable().
convertStrToNumber()
static Value* convertStrToNumber (CallInst * CI, StringRef & Str, int64_t Base) static
Definition at line 116 of file SimplifyLibCalls.cpp.
createPowWithIntegerExponent()
static Value* createPowWithIntegerExponent (Value * Base, Value * Expo, Module * M, IRBuilder<> & B) static
Definition at line 1678 of file SimplifyLibCalls.cpp.
References llvm::abs(), llvm::APFloat::add(), Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, B, Callee, llvm::APFloatBase::cmpLessThan, llvm::APFloat::convertToInteger(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::CallBase::doesNotAccessMemory(), llvm::dyn_cast(), llvm::numbers::e, llvm::emitBinaryFloatFnCall(), llvm::emitUnaryFloatFnCall(), F(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::CallBase::getArgOperand(), llvm::Function::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::Intrinsic::getDeclaration(), llvm::FastMathFlags::getFast(), llvm::Instruction::getFastMathFlags(), llvm::IRBuilderBase::getInt32Ty(), llvm::Function::getIntrinsicID(), llvm::CallBase::getIntrinsicID(), getIntToFPVal(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), getPow(), llvm::Type::getScalarType(), llvm::APFloat::getSemantics(), getSqrtCall(), llvm::Value::getType(), llvm::Instruction::hasApproxFunc(), llvm::hasFloatFn(), llvm::Value::hasOneUse(), I, llvm::APFloatBase::IEEEdouble(), llvm::Type::isDoubleTy(), llvm::Instruction::isFast(), llvm::Type::isFloatTy(), llvm::APFloat::isInteger(), llvm::APFloat::isNegative(), llvm::log2(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::maxnum(), llvm::minnum(), llvm::Mod, Name, llvm::NotLibFunc, llvm::APFloatBase::opOK, optimizeBinaryDoubleFP(), optimizeUnaryDoubleFP(), llvm::MipsISD::Ret, llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloatBase::rmTowardZero, llvm::IRBuilderBase::setFastMathFlags(), llvm::FastMathFlags::setNoSignedZeros(), and llvm::StringRef::startswith().
getIntToFPVal()
static Value* getIntToFPVal (Value * I2F, IRBuilder<> & B) static
Definition at line 1456 of file SimplifyLibCalls.cpp.
References llvm::lltok::APFloat, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, B, llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::APFloat::convertToFloat(), llvm::APFloat::convertToInteger(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::CallBase::doesNotAccessMemory(), llvm::dyn_cast(), llvm::emitBinaryFloatFnCall(), llvm::emitUnaryFloatFnCall(), llvm::ConstantFP::get(), llvm::CallBase::getArgOperand(), llvm::Function::getAttributes(), llvm::CallBase::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getInt32Ty(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::Type::getPrimitiveSizeInBits(), llvm::APFloat::getSemantics(), llvm::Value::getType(), llvm::Instruction::hasApproxFunc(), llvm::hasFloatFn(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoNaNs(), llvm::Value::hasOneUse(), llvm::Type::isDoubleTy(), llvm::Instruction::isFast(), llvm::Type::isFloatTy(), llvm::APFloat::isInteger(), llvm::APFloat::isNegative(), llvm::APFloat::isNormal(), llvm::APInt::isPowerOf2(), llvm::log2(), llvm::APInt::logBase2(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::match(), llvm::Mod, N, llvm::APFloatBase::opOK, and llvm::APFloatBase::rmTowardZero.
Referenced by createPowWithIntegerExponent().
getPow()
static Value* getPow (Value * InnerChain[33], unsigned Exp, IRBuilder<> & B) static
Definition at line 1430 of file SimplifyLibCalls.cpp.
References assert(), and llvm::IRBuilder< T, Inserter >::CreateFMul().
Referenced by createPowWithIntegerExponent().
getSqrtCall()
static Value* getSqrtCall (Value * V, AttributeList Attrs, bool NoErrno, Module * M, IRBuilder<> & B, const TargetLibraryInfo * TLI) static
Definition at line 1614 of file SimplifyLibCalls.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, B, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::CallBase::doesNotAccessMemory(), llvm::emitUnaryFloatFnCall(), llvm::ConstantFP::get(), llvm::CallBase::getArgOperand(), llvm::Function::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::Intrinsic::getDeclaration(), llvm::ConstantFP::getInfinity(), llvm::Instruction::getModule(), llvm::Value::getType(), llvm::Instruction::hasAllowReassoc(), llvm::Instruction::hasApproxFunc(), llvm::hasFloatFn(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoSignedZeros(), llvm::APFloat::isExactlyValue(), llvm::APFloat::isNegative(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::match(), and llvm::Mod.
Referenced by createPowWithIntegerExponent().
ignoreCallingConv()
static bool ignoreCallingConv (LibFunc Func) static
Definition at line 55 of file SimplifyLibCalls.cpp.
Referenced by isReportingError(), llvm::FortifiedLibCallSimplifier::optimizeCall(), and llvm::LibCallSimplifier::optimizeCall().
insertSinCosCall()
static void insertSinCosCall (IRBuilder<> & B, Function * OrigCallee, Value * Arg, bool UseFloat, Value *& Sin, Value *& Cos, Value *& SinCos) static
Definition at line 2119 of file SimplifyLibCalls.cpp.
References Arg, assert(), llvm::BasicBlock::begin(), C, Callee, llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), F(), llvm::ConstantInt::get(), llvm::StructType::get(), llvm::VectorType::get(), llvm::CallBase::getArgOperand(), llvm::Function::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::Intrinsic::getDeclaration(), llvm::Function::getEntryBlock(), llvm::Instruction::getFunction(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getInt32Ty(), llvm::Module::getOrInsertFunction(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Module::getTargetTriple(), llvm::IRBuilderBase::getTrue(), llvm::Value::getType(), llvm::Type::isFloatTy(), llvm::Type::isStructTy(), isTrigLibCall(), Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::IRBuilderBase::SetInsertPoint(), llvm::T, llvm::Value::users(), llvm::Triple::x86, and llvm::Triple::x86_64.
isCallingConvCCompatible()
static bool isCallingConvCCompatible (CallInst * CI) static
Definition at line 60 of file SimplifyLibCalls.cpp.
References llvm::CallingConv::ARM_AAPCS, llvm::CallingConv::ARM_AAPCS_VFP, llvm::CallingConv::ARM_APCS, llvm::CallingConv::C, llvm::CallBase::getCallingConv(), llvm::CallBase::getFunctionType(), llvm::Instruction::getModule(), and llvm::Module::getTargetTriple().
Referenced by isReportingError(), llvm::FortifiedLibCallSimplifier::optimizeCall(), and llvm::LibCallSimplifier::optimizeCall().
isLocallyOpenedFile()
static bool isLocallyOpenedFile (Value * File, CallInst * CI, IRBuilder<> & B, const TargetLibraryInfo * TLI) static
Definition at line 141 of file SimplifyLibCalls.cpp.
References llvm::dyn_cast(), File, llvm::CallBase::getCalledFunction(), llvm::TargetLibraryInfo::getLibFunc(), llvm::TargetLibraryInfo::has(), llvm::inferLibFuncAttributes(), and llvm::PointerMayBeCaptured().
Referenced by isReportingError().
isOnlyUsedInComparisonWithZero()
static bool isOnlyUsedInComparisonWithZero (Value * V) static
Definition at line 163 of file SimplifyLibCalls.cpp.
References C, and llvm::Value::users().
Referenced by canTransformToMemCmp().
isOnlyUsedInEqualityComparison()
static bool isOnlyUsedInEqualityComparison (Value * V, Value * With) static
Return true if it is only used in equality comparisons with With.
Definition at line 93 of file SimplifyLibCalls.cpp.
References llvm::Value::users().
Referenced by annotateNonNullAndDereferenceable().
isReportingError()
static bool isReportingError (Function * Callee, CallInst * CI, int StreamArg) static
Definition at line 2354 of file SimplifyLibCalls.cpp.
References annotateNonNullBasedOnAccess(), assert(), B, llvm::AMDGPUISD::BFI, callHasFloatingPointArgument(), callHasFP128Argument(), llvm::castToCStr(), llvm::Instruction::clone(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilderBase::CreateGlobalString(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::StringRef::drop_back(), llvm::dyn_cast(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), llvm::emitPutChar(), llvm::emitPutS(), llvm::emitStrLen(), llvm::StringRef::empty(), llvm::StringRef::find(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Function::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::getConstantStringInfo(), llvm::Value::getContext(), llvm::Instruction::getFunction(), llvm::Function::getFunctionType(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt8(), llvm::IRBuilderBase::getInt8Ty(), llvm::Value::getName(), llvm::CallBase::getNumArgOperands(), llvm::User::getOperand(), llvm::Module::getOrInsertFunction(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::LoadInst::getPointerOperand(), llvm::GetStringLength(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::Function::hasOptSize(), ignoreCallingConv(), llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRPass, isCallingConvCCompatible(), llvm::GlobalValue::isDeclaration(), llvm::Type::isIntegerTy(), llvm::isKnownNonZero(), isLocallyOpenedFile(), llvm::Type::isPointerTy(), llvm::CallBase::isStrictFP(), N, llvm::Align::None(), llvm::StringRef::npos, optimizeBinaryDoubleFP(), optimizeTrigReflections(), optimizeUnaryDoubleFP(), replaceUnaryCall(), round(), llvm::CallBase::setCalledFunction(), llvm::shouldOptimizeForSize(), Size, llvm::StringRef::size(), and llvm::Value::use_empty().
isTrigLibCall()
static bool isTrigLibCall (CallInst * CI) static
Definition at line 2111 of file SimplifyLibCalls.cpp.
References llvm::CallBase::hasFnAttr().
Referenced by insertSinCosCall().
optimizeBinaryDoubleFP()
static Value* optimizeBinaryDoubleFP (CallInst * CI, IRBuilder<> & B, bool isPrecise = false) static
Shrink double -> float for binary functions.
Definition at line 1361 of file SimplifyLibCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getFastMathFlags(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::Value::getType(), llvm::Type::isArrayTy(), llvm::Instruction::isFast(), optimizeDoubleFP(), and llvm::IRBuilderBase::setFastMathFlags().
Referenced by createPowWithIntegerExponent(), and isReportingError().
optimizeDoubleFP()
static Value* optimizeDoubleFP (CallInst * CI, IRBuilder<> & B, bool isBinary, bool isPrecise = false) static
Shrink double -> float functions.
Definition at line 1297 of file SimplifyLibCalls.cpp.
References llvm::StringRef::back(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateFPExt(), llvm::dyn_cast(), llvm::emitBinaryFloatFnCall(), llvm::emitUnaryFloatFnCall(), llvm::StringRef::empty(), llvm::CallBase::getArgOperand(), llvm::Function::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getDoubleTy(), llvm::Instruction::getFastMathFlags(), llvm::IRBuilderBase::getFloatTy(), llvm::Instruction::getFunction(), llvm::Function::getIntrinsicID(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::Value::getType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Function::isIntrinsic(), llvm::IRBuilderBase::setFastMathFlags(), llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::Value::users(), and valueHasFloatPrecision().
Referenced by optimizeBinaryDoubleFP(), and optimizeUnaryDoubleFP().
optimizeMemCmpConstantSize()
static Value* optimizeMemCmpConstantSize (CallInst * CI, Value * LHS, Value * RHS, uint64_t Len, IRBuilder<> & B, const DataLayout & DL) static
Definition at line 990 of file SimplifyLibCalls.cpp.
References annotateNonNullAndDereferenceable(), B, llvm::castToCStr(), llvm::ConstantFoldLoadFromConstPtr(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateICmpNE(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::StringRef::data(), llvm::dyn_cast(), llvm::emitBCmp(), llvm::emitCalloc(), llvm::emitMalloc(), llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getAttributes(), llvm::ConstantExpr::getBitCast(), llvm::getConstantStringInfo(), llvm::BasicBlock::getContext(), llvm::Value::getContext(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getInt8Ty(), llvm::DataLayout::getIntPtrType(), llvm::getKnownAlignment(), llvm::Constant::getNullValue(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerTo(), llvm::DataLayout::getPrefTypeAlignment(), llvm::ConstantInt::getSExtValue(), llvm::Value::getType(), llvm::DataLayout::isLegalInteger(), llvm::isOnlyUsedInZeroEqualityComparison(), memcmp, N, llvm::Align::None(), llvm::StringRef::npos, llvm::MipsISD::Ret, llvm::CallBase::setAttributes(), llvm::IRBuilderBase::SetInsertPoint(), Size, llvm::StringRef::size(), and llvm::Value::use_empty().
optimizeTrigReflections()
static Value* optimizeTrigReflections (CallInst * Call, LibFunc Func, IRBuilder<> & B) static
Definition at line 1395 of file SimplifyLibCalls.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateFNeg(), llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), llvm::Instruction::getFastMathFlags(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::IRBuilderBase::setFastMathFlags(), and X.
Referenced by isReportingError().
optimizeUnaryDoubleFP()
static Value* optimizeUnaryDoubleFP (CallInst * CI, IRBuilder<> & B, bool isPrecise = false) static
Shrink double -> float for unary functions.
Definition at line 1355 of file SimplifyLibCalls.cpp.
References optimizeDoubleFP().
Referenced by createPowWithIntegerExponent(), and isReportingError().
replaceUnaryCall()
static Value* replaceUnaryCall (CallInst * CI, IRBuilder<> & B, Intrinsic::ID IID) static
Definition at line 1261 of file SimplifyLibCalls.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), F(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getFastMathFlags(), llvm::Instruction::getModule(), llvm::Value::getType(), llvm::IRBuilderBase::setFastMathFlags(), and llvm::Value::takeName().
Referenced by isReportingError().
valueHasFloatPrecision()
static Value* valueHasFloatPrecision (Value * Val) static
Return a variant of Val with float type.
Currently this works in two cases: If Val is an FPExtension of a float value to something bigger, simply return the operand. If Val is a ConstantFP but can be converted to a float ConstantFP without loss of precision do so.
Definition at line 1279 of file SimplifyLibCalls.cpp.
References llvm::APFloat::convert(), F(), llvm::ConstantFP::get(), llvm::Value::getType(), llvm::APFloatBase::IEEEsingle(), llvm::Type::isFloatTy(), and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by optimizeDoubleFP().
Variable Documentation
EnableUnsafeFPShrink
cl::opt<bool> EnableUnsafeFPShrink("enable-double-float-shrink", cl::Hidden, cl::init(false), cl::desc("Enable unsafe double to float " "shrinking for math lib calls")) static
Referenced by llvm::LibCallSimplifier::optimizeCall().