LLVM: lib/Target/AMDGPU/SIOptimizeExecMasking.cpp File Reference
SIOptimizeExecMasking.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIInstrInfo.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "si-optimize-exec-masking"
Functions
INITIALIZE_PASS_BEGIN (SIOptimizeExecMasking, DEBUG_TYPE, "SI optimize exec mask operations", false, false) INITIALIZE_PASS_END(SIOptimizeExecMasking
static Register isCopyFromExec (const MachineInstr &MI, const GCNSubtarget &ST)
If MI is a copy from exec, return the register copied to.
static Register isCopyToExec (const MachineInstr &MI, const GCNSubtarget &ST)
If MI is a copy to exec, return the register copied from.
static Register isLogicalOpOnExec (const MachineInstr &MI)
If MI is a logical operation on an exec value, return the register copied to.
static unsigned getSaveExecOp (unsigned Opc)
static bool removeTerminatorBit (const SIInstrInfo &TII, MachineInstr &MI)
static MachineBasicBlock::reverse_iterator fixTerminators (const SIInstrInfo &TII, MachineBasicBlock &MBB)
static MachineBasicBlock::reverse_iterator findExecCopy (const SIInstrInfo &TII, const GCNSubtarget &ST, MachineBasicBlock &MBB, MachineBasicBlock::reverse_iterator I, unsigned CopyToExec)
static bool isLiveOut (const MachineBasicBlock &MBB, unsigned Reg)
Variables
DEBUG_TYPE
SI optimize exec mask operations
SI optimize exec mask false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-optimize-exec-masking"
Definition at line 22 of file SIOptimizeExecMasking.cpp.
Function Documentation
findExecCopy()
static MachineBasicBlock::reverse_iterator findExecCopy (const SIInstrInfo & TII, const GCNSubtarget & ST, MachineBasicBlock & MBB, MachineBasicBlock::reverse_iterator I, unsigned CopyToExec) static
Definition at line 238 of file SIOptimizeExecMasking.cpp.
References E, I, isCopyFromExec(), llvm::Register::isValid(), N, and llvm::MachineBasicBlock::rend().
Referenced by isLiveOut().
fixTerminators()
static MachineBasicBlock::reverse_iterator fixTerminators (const SIInstrInfo & TII, MachineBasicBlock & MBB) static
Definition at line 223 of file SIOptimizeExecMasking.cpp.
References E, I, llvm::MachineBasicBlock::rbegin(), removeTerminatorBit(), and llvm::MachineBasicBlock::rend().
Referenced by isLiveOut().
getSaveExecOp()
static unsigned getSaveExecOp (unsigned Opc) static
Definition at line 139 of file SIOptimizeExecMasking.cpp.
Referenced by isLiveOut().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (SIOptimizeExecMasking , DEBUG_TYPE , "SI optimize exec mask operations" , false , false)
isCopyFromExec()
static Register isCopyFromExec (const MachineInstr & MI, const GCNSubtarget & ST) static
If MI is a copy from exec, return the register copied to.
Definition at line 60 of file SIOptimizeExecMasking.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), MI, and llvm::ARM_MB::ST.
Referenced by findExecCopy().
isCopyToExec()
static Register isCopyToExec (const MachineInstr & MI, const GCNSubtarget & ST) static
If MI is a copy to exec, return the register copied from.
Definition at line 78 of file SIOptimizeExecMasking.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::GCNSubtarget::isWave32(), llvm_unreachable, and Register.
Referenced by isLiveOut().
isLiveOut()
static bool isLiveOut (const MachineBasicBlock & MBB, unsigned Reg) static
Definition at line 259 of file SIOptimizeExecMasking.cpp.
References assert(), llvm::BuildMI(), llvm::dbgs(), E, llvm::MachineInstr::eraseFromParent(), findExecCopy(), fixTerminators(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::GCNSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::GCNSubtarget::getRegisterInfo(), getSaveExecOp(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineInstr::isCommutable(), isCopyToExec(), isLogicalOpOnExec(), llvm::MachineOperand::isReg(), llvm::Register::isValid(), llvm::GCNSubtarget::isWave32(), LLVM_DEBUG, llvm_unreachable, llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineInstr::readsRegister(), llvm::ARM_MB::ST, llvm::MachineBasicBlock::successors(), TII, and TRI.
Referenced by allPhiOperandsUndefined(), and createBBSelectReg().
isLogicalOpOnExec()
static Register isLogicalOpOnExec (const MachineInstr & MI) static
If MI is a logical operation on an exec value, return the register copied to.
Definition at line 100 of file SIOptimizeExecMasking.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and llvm::MachineOperand::isReg().
Referenced by isLiveOut().
removeTerminatorBit()
static bool removeTerminatorBit (const SIInstrInfo & TII, MachineInstr & MI) static
Definition at line 181 of file SIOptimizeExecMasking.cpp.
References llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::setDesc().
Referenced by fixTerminators().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 52 of file SIOptimizeExecMasking.cpp.
false
SI optimize exec mask false
Definition at line 52 of file SIOptimizeExecMasking.cpp.
operations
SI optimize exec mask operations
Definition at line 52 of file SIOptimizeExecMasking.cpp.