LLVM: lib/Target/AMDGPU/SIPeepholeSDWA.cpp File Reference
SIPeepholeSDWA.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "SIDefines.h"
#include "SIInstrInfo.h"
#include "SIRegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <unordered_map>
Macros
#define DEBUG_TYPE "si-peephole-sdwa"
Functions
STATISTIC (NumSDWAPatternsFound, "Number of SDWA patterns found.")
STATISTIC (NumSDWAInstructionsPeepholed, "Number of instruction converted to SDWA.")
static raw_ostream & operator<< (raw_ostream &OS, SdwaSel Sel)
static raw_ostream & operator<< (raw_ostream &OS, const DstUnused &Un)
static void copyRegOperand (MachineOperand &To, const MachineOperand &From)
static bool isSameReg (const MachineOperand &LHS, const MachineOperand &RHS)
static MachineOperand * findSingleRegUse (const MachineOperand *Reg, const MachineRegisterInfo *MRI)
static MachineOperand * findSingleRegDef (const MachineOperand *Reg, const MachineRegisterInfo *MRI)
static raw_ostream & operator<< (raw_ostream &OS, const SDWAOperand &Operand)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-peephole-sdwa"
Definition at line 57 of file SIPeepholeSDWA.cpp.
Function Documentation
copyRegOperand()
static void copyRegOperand (MachineOperand & To, const MachineOperand & From) static
Definition at line 271 of file SIPeepholeSDWA.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setReg(), and llvm::MachineOperand::setSubReg().
Referenced by findSingleRegDef().
findSingleRegDef()
static MachineOperand* findSingleRegDef (const MachineOperand * Reg, const MachineRegisterInfo * MRI) static
Definition at line 312 of file SIPeepholeSDWA.cpp.
References llvm::SISrcMods::ABS, llvm::MachineInstrBuilder::addReg(), assert(), llvm::AMDGPU::SDWA::BYTE_0, llvm::AMDGPU::SDWA::BYTE_1, llvm::AMDGPU::SDWA::BYTE_2, llvm::AMDGPU::SDWA::BYTE_3, copyRegOperand(), llvm::tgtok::Def, llvm::MachineRegisterInfo::def_operands(), llvm::MachineInstr::defs(), llvm::AMDGPU::SDWA::DWORD, findSingleRegUse(), llvm::MachineInstr::findTiedOperandIdx(), llvm::MachineOperand::getImm(), llvm::SIInstrInfo::getNamedImmOperand(), llvm::SIInstrInfo::getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::RegState::ImplicitKill, llvm::SIInstrInfo::isFoldableCopy(), llvm::MachineOperand::isImm(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), isSameReg(), llvm::SIInstrInfo::isSDWA(), MI, llvm::Mod, llvm::SISrcMods::NEG, llvm::None, llvm::MachineBasicBlock::remove(), llvm::MachineOperand::setImm(), llvm::SISrcMods::SEXT, llvm::MachineInstr::tieOperands(), llvm::AMDGPU::SDWA::UNUSED_PAD, llvm::AMDGPU::SDWA::UNUSED_PRESERVE, llvm::MachineRegisterInfo::use_nodbg_instructions(), llvm::MachineInstr::uses(), llvm::AMDGPU::SDWA::WORD_0, and llvm::AMDGPU::SDWA::WORD_1.
findSingleRegUse()
static MachineOperand* findSingleRegUse (const MachineOperand * Reg, const MachineRegisterInfo * MRI) static
Definition at line 290 of file SIPeepholeSDWA.cpp.
References llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), isSameReg(), and llvm::MachineRegisterInfo::use_nodbg_operands().
Referenced by findSingleRegDef(), and operator<<().
isSameReg()
static bool isSameReg (const MachineOperand & LHS, const MachineOperand & RHS) static
Definition at line 283 of file SIPeepholeSDWA.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), and llvm::MachineOperand::isReg().
Referenced by findSingleRegDef(), and findSingleRegUse().
operator<<() [1/3]
static raw_ostream& operator<< (raw_ostream & OS, SdwaSel Sel) static
Definition at line 225 of file SIPeepholeSDWA.cpp.
References llvm::AMDGPU::SDWA::BYTE_0, llvm::AMDGPU::SDWA::BYTE_1, llvm::AMDGPU::SDWA::BYTE_2, llvm::AMDGPU::SDWA::BYTE_3, llvm::AMDGPU::SDWA::DWORD, llvm::AMDGPU::SDWA::WORD_0, and llvm::AMDGPU::SDWA::WORD_1.
operator<<() [2/3]
static raw_ostream& operator<< (raw_ostream & OS, const DstUnused & Un) static
Definition at line 238 of file SIPeepholeSDWA.cpp.
References LLVM_DUMP_METHOD, print(), llvm::AMDGPU::SDWA::UNUSED_PAD, llvm::AMDGPU::SDWA::UNUSED_PRESERVE, and llvm::AMDGPU::SDWA::UNUSED_SEXT.
operator<<() [3/3]
static raw_ostream& operator<< (raw_ostream & OS, const SDWAOperand & Operand) static
Definition at line 849 of file SIPeepholeSDWA.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::SIInstrInfo::canShrink(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineBasicBlock::computeRegisterLiveness(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::count(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), llvm::RegState::Define, llvm::AMDGPU::SDWA::DWORD, E, llvm::SmallVectorBase::empty(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::explicit_uses(), findSingleRegUse(), llvm::MachineInstr::findTiedOperandIdx(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::GCNSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::SIInstrInfo::getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getOperandNo(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::SIRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::GCNSubtarget::getRegisterInfo(), llvm::AMDGPU::getSDWAOp(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::SIRegisterInfo::getVCC(), llvm::AMDGPU::getVOPe32(), llvm::SIInstrInfo::hasModifiersSet(), llvm::MachineRegisterInfo::hasOneUse(), llvm::AMDGPUSubtarget::hasSDWA(), llvm::GCNSubtarget::hasSDWAMac(), llvm::GCNSubtarget::hasSDWAOmod(), llvm::GCNSubtarget::hasSDWAOutModsVOPC(), llvm::GCNSubtarget::hasSDWAScalar(), llvm::GCNSubtarget::hasSDWASdst(), llvm::SIRegisterInfo::hasVGPRs(), I, llvm::MachineOperand::isImm(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::SIInstrInfo::isSDWA(), llvm::SIRegisterInfo::isSGPRReg(), llvm::SIRegisterInfo::isVGPR(), llvm::SIInstrInfo::isVOPC(), llvm::RegState::Kill, LLVM_DEBUG, llvm::MachineBasicBlock::LQR_Dead, MI, llvm::Mod, llvm::MCInstrDesc::OpInfo, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SIInstrInfo::pseudoToMCOpcode(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MCOperandInfo::RegClass, llvm::MipsISD::Ret, llvm::ARM_MB::ST, llvm::MachineInstr::tieOperands(), llvm::AMDGPU::SDWA::UNUSED_PAD, llvm::AMDGPU::SDWA::UNUSED_PRESERVE, and llvm::MachineRegisterInfo::use_empty().
STATISTIC() [1/2]
STATISTIC (NumSDWAPatternsFound , "Number of SDWA patterns found.")
STATISTIC() [2/2]
STATISTIC (NumSDWAInstructionsPeepholed , "Number of instruction converted to SDWA.")