LLVM: lib/Transforms/Utils/SizeOpts.cpp File Reference
SizeOpts.cpp File Reference
#include "llvm/Transforms/Utils/SizeOpts.h"
Variables
cl::opt< bool > EnablePGSO ("pgso", cl::Hidden, cl::init(true), cl::desc("Enable the profile guided size optimizations. "))
cl::opt< bool > PGSOLargeWorkingSetSizeOnly ("pgso-lwss-only", cl::Hidden, cl::init(true), cl::desc("Apply the profile guided size optimizations only " "if the working set size is large (except for cold code.)"))
cl::opt< bool > PGSOColdCodeOnly ("pgso-cold-code-only", cl::Hidden, cl::init(true), cl::desc("Apply the profile guided size optimizations only " "to cold code."))
cl::opt< bool > PGSOIRPassOrTestOnly ("pgso-ir-pass-or-test-only", cl::Hidden, cl::init(false), cl::desc("Apply the profile guided size optimizations only" "to the IR passes or tests."))
cl::opt< bool > ForcePGSO ("force-pgso", cl::Hidden, cl::init(false), cl::desc("Force the (profiled-guided) size optimizations. "))
cl::opt< int > PgsoCutoffInstrProf ("pgso-cutoff-instr-prof", cl::Hidden, cl::init(250000), cl::ZeroOrMore, cl::desc("The profile guided size optimization profile summary cutoff " "for instrumentation profile."))
cl::opt< int > PgsoCutoffSampleProf ("pgso-cutoff-sample-prof", cl::Hidden, cl::init(800000), cl::ZeroOrMore, cl::desc("The profile guided size optimization profile summary cutoff " "for sample profile."))
Variable Documentation
EnablePGSO
cl::opt<bool> EnablePGSO("pgso", cl::Hidden, cl::init(true), cl::desc("Enable the profile guided size optimizations. "))
ForcePGSO
cl::opt<bool> ForcePGSO("force-pgso", cl::Hidden, cl::init(false), cl::desc("Force the (profiled-guided) size optimizations. "))
PGSOColdCodeOnly
cl::opt<bool> PGSOColdCodeOnly("pgso-cold-code-only", cl::Hidden, cl::init(true), cl::desc("Apply the profile guided size optimizations only " "to cold code."))
PgsoCutoffInstrProf
cl::opt<int> PgsoCutoffInstrProf("pgso-cutoff-instr-prof", cl::Hidden, cl::init(250000), cl::ZeroOrMore, cl::desc("The profile guided size optimization profile summary cutoff " "for instrumentation profile."))
Referenced by llvm::shouldFuncOptimizeForSizeImpl(), and llvm::shouldOptimizeForSizeImpl().
PgsoCutoffSampleProf
cl::opt<int> PgsoCutoffSampleProf("pgso-cutoff-sample-prof", cl::Hidden, cl::init(800000), cl::ZeroOrMore, cl::desc("The profile guided size optimization profile summary cutoff " "for sample profile."))
Referenced by llvm::shouldFuncOptimizeForSizeImpl(), and llvm::shouldOptimizeForSizeImpl().
PGSOIRPassOrTestOnly
cl::opt<bool> PGSOIRPassOrTestOnly("pgso-ir-pass-or-test-only", cl::Hidden, cl::init(false), cl::desc("Apply the profile guided size optimizations only" "to the IR passes or tests."))
PGSOLargeWorkingSetSizeOnly
cl::opt<bool> PGSOLargeWorkingSetSizeOnly("pgso-lwss-only", cl::Hidden, cl::init(true), cl::desc("Apply the profile guided size optimizations only " "if the working set size is large (except for cold code.)"))