LLVM: lib/CodeGen/SjLjEHPrepare.cpp File Reference
SjLjEHPrepare.cpp File Reference
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "sjljehprepare"
Functions
STATISTIC (NumInvokes, "Number of invokes replaced")
STATISTIC (NumSpilled, "Number of registers live across unwind edges")
INITIALIZE_PASS (SjLjEHPrepare, DEBUG_TYPE, "Prepare SjLj exceptions", false, false) FunctionPass *llvm
static void MarkBlocksLiveIn (BasicBlock *BB, SmallPtrSetImpl< BasicBlock *> &LiveBBs)
MarkBlocksLiveIn - Insert BB and all of its predecessors into LiveBBs until we reach blocks we've already seen.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "sjljehprepare"
Definition at line 33 of file SjLjEHPrepare.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (SjLjEHPrepare , DEBUG_TYPE , "Prepare SjLj exceptions" , false , false)
Definition at line 76 of file SjLjEHPrepare.cpp.
References llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::ConstantInt::get(), llvm::StructType::get(), llvm::ArrayType::get(), llvm::Module::getContext(), llvm::Value::getContext(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), I, Int32Ty, and llvm::Number.
MarkBlocksLiveIn()
static void MarkBlocksLiveIn (BasicBlock * BB, SmallPtrSetImpl< BasicBlock *> & LiveBBs) static
MarkBlocksLiveIn - Insert BB and all of its predecessors into LiveBBs until we reach blocks we've already seen.
Definition at line 122 of file SjLjEHPrepare.cpp.
References llvm::Function::args(), assert(), B, llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::begin(), llvm::BasicBlock::begin(), llvm::Function::begin(), Callee, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::CallInst::Create(), llvm::SelectInst::Create(), llvm::BranchInst::Create(), llvm::dbgs(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::dyn_cast(), llvm::numbers::e, E, llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImplBase::empty(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::end(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), F(), llvm::BasicBlock::front(), llvm::Function::front(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::DataLayout::getAllocaAddrSpace(), llvm::Function::getContext(), llvm::Module::getContext(), llvm::Module::getDataLayout(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Type::getInt32Ty(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::Type::getInt8PtrTy(), llvm::BasicBlock::getLandingPadInst(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::Module::getOrInsertFunction(), llvm::Instruction::getParent(), llvm::GlobalValue::getParent(), getParent(), llvm::Function::getPersonalityFn(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), I, llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Instruction::insertAfter(), Int32Ty, llvm::inverse_depth_first_ext(), LLVM_DEBUG, llvm::makeArrayRef(), llvm::Instruction::mayThrow(), llvm::Instruction::moveBefore(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::MCID::Return, runOnFunction(), llvm::CallBase::setDoesNotThrow(), llvm::User::setOperand(), SI, llvm::SmallVectorBase::size(), llvm::Value::use_empty(), llvm::Value::user_begin(), llvm::Value::user_end(), Users, and llvm::Value::users().
STATISTIC() [1/2]
STATISTIC (NumInvokes , "Number of invokes replaced")
STATISTIC() [2/2]
STATISTIC (NumSpilled , "Number of registers live across unwind edges")