LLVM: lib/Target/Sparc/SparcISelLowering.cpp File Reference
SparcISelLowering.cpp File Reference
#include "SparcISelLowering.h"
#include "MCTargetDesc/SparcMCExpr.h"
#include "SparcMachineFunctionInfo.h"
#include "SparcRegisterInfo.h"
#include "SparcTargetMachine.h"
#include "SparcTargetObjectFile.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "SparcGenCallingConv.inc"
Functions
static bool CC_Sparc_Assign_SRet (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_Sparc_Assign_Split_64 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_Sparc_Assign_Ret_Split_64 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_Sparc64_Full (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_Sparc64_Half (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static unsigned toCallerWindow (unsigned Reg)
static bool hasReturnsTwiceAttr (SelectionDAG &DAG, SDValue Callee, ImmutableCallSite CS)
static void fixupVariableFloatArgs (SmallVectorImpl< CCValAssign > &ArgLocs, ArrayRef< ISD::OutputArg > Outs)
static SPCC::CondCodes IntCondCCodeToICC (ISD::CondCode CC)
IntCondCCodeToICC - Convert a DAG integer condition code to a SPARC ICC condition.
static SPCC::CondCodes FPCondCCodeToFCC (ISD::CondCode CC)
FPCondCCodeToFCC - Convert a DAG floatingp oint condition code to a SPARC FCC condition.
static void LookThroughSetCC (SDValue &LHS, SDValue &RHS, ISD::CondCode CC, unsigned &SPCC)
static SDValue LowerF128_FPEXTEND (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI)
static SDValue LowerF128_FPROUND (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI)
static SDValue LowerFP_TO_SINT (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI, bool hasHardQuad)
static SDValue LowerSINT_TO_FP (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI, bool hasHardQuad)
static SDValue LowerFP_TO_UINT (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI, bool hasHardQuad)
static SDValue LowerUINT_TO_FP (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI, bool hasHardQuad)
static SDValue LowerBR_CC (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI, bool hasHardQuad)
static SDValue LowerSELECT_CC (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI, bool hasHardQuad)
static SDValue LowerVASTART (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI)
static SDValue LowerVAARG (SDValue Op, SelectionDAG &DAG)
static SDValue LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG &DAG, const SparcSubtarget *Subtarget)
static SDValue getFLUSHW (SDValue Op, SelectionDAG &DAG)
static SDValue getFRAMEADDR (uint64_t depth, SDValue Op, SelectionDAG &DAG, const SparcSubtarget *Subtarget, bool AlwaysFlush=false)
static SDValue LowerFRAMEADDR (SDValue Op, SelectionDAG &DAG, const SparcSubtarget *Subtarget)
static SDValue LowerRETURNADDR (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI, const SparcSubtarget *Subtarget)
static SDValue LowerF64Op (SDValue SrcReg64, const SDLoc &dl, SelectionDAG &DAG, unsigned opcode)
static SDValue LowerF128Load (SDValue Op, SelectionDAG &DAG)
static SDValue LowerLOAD (SDValue Op, SelectionDAG &DAG)
static SDValue LowerF128Store (SDValue Op, SelectionDAG &DAG)
static SDValue LowerSTORE (SDValue Op, SelectionDAG &DAG)
static SDValue LowerFNEGorFABS (SDValue Op, SelectionDAG &DAG, bool isV9)
static SDValue LowerADDC_ADDE_SUBC_SUBE (SDValue Op, SelectionDAG &DAG)
static SDValue LowerUMULO_SMULO (SDValue Op, SelectionDAG &DAG, const SparcTargetLowering &TLI)
static SDValue LowerATOMIC_LOAD_STORE (SDValue Op, SelectionDAG &DAG)
Function Documentation
CC_Sparc64_Full()
static bool CC_Sparc64_Full (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 106 of file SparcISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateStack(), assert(), llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::getMem(), llvm::CCValAssign::getReg(), llvm::MVT::getSizeInBits(), llvm::MVT::i64, Reg, and llvm::size().
CC_Sparc64_Half()
static bool CC_Sparc64_Half (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 151 of file SparcISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::CCValAssign::AExt, llvm::CCState::AllocateStack(), assert(), llvm::MVT::f32, llvm::CCValAssign::getCustomReg(), llvm::CCValAssign::getMem(), llvm::CCValAssign::getReg(), llvm::MVT::getSizeInBits(), llvm::MVT::i32, llvm::MVT::i64, and Reg.
CC_Sparc_Assign_Ret_Split_64()
static bool CC_Sparc_Assign_Ret_Split_64 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 82 of file SparcISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateReg(), llvm::CCValAssign::getCustomReg(), and Reg.
CC_Sparc_Assign_Split_64()
static bool CC_Sparc_Assign_Split_64 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 54 of file SparcISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateStack(), llvm::CCValAssign::getCustomMem(), llvm::CCValAssign::getCustomReg(), and Reg.
CC_Sparc_Assign_SRet()
static bool CC_Sparc_Assign_SRet (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 41 of file SparcISelLowering.cpp.
References llvm::CCState::addLoc(), assert(), llvm::CCValAssign::getCustomMem(), and llvm::ISD::ArgFlagsTy::isSRet().
fixupVariableFloatArgs()
static void fixupVariableFloatArgs (SmallVectorImpl< CCValAssign > & ArgLocs, ArrayRef< ISD::OutputArg > Outs) static
Definition at line 1046 of file SparcISelLowering.cpp.
References assert(), llvm::CCValAssign::BCvt, llvm::numbers::e, llvm::MVT::f128, llvm::MVT::f64, llvm::CCValAssign::getCustomReg(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::CCValAssign::getMem(), llvm::CCValAssign::getReg(), llvm::CCValAssign::getValNo(), llvm::CCValAssign::getValVT(), llvm::MVT::i128, llvm::MVT::i64, llvm::CCValAssign::isRegLoc(), and llvm::SmallVectorBase::size().
Referenced by llvm::SparcTargetLowering::LowerCall_64().
FPCondCCodeToFCC()
static SPCC::CondCodes FPCondCCodeToFCC (ISD::CondCode CC) static
FPCondCCodeToFCC - Convert a DAG floatingp oint condition code to a SPARC FCC condition.
Definition at line 1382 of file SparcISelLowering.cpp.
References llvm::SPCC::FCC_E, llvm::SPCC::FCC_G, llvm::SPCC::FCC_GE, llvm::SPCC::FCC_L, llvm::SPCC::FCC_LE, llvm::SPCC::FCC_LG, llvm::SPCC::FCC_NE, llvm::SPCC::FCC_O, llvm::SPCC::FCC_U, llvm::SPCC::FCC_UE, llvm::SPCC::FCC_UG, llvm::SPCC::FCC_UGE, llvm::SPCC::FCC_UL, llvm::SPCC::FCC_ULE, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
Referenced by LowerBR_CC(), and LowerSELECT_CC().
getFLUSHW()
static SDValue getFLUSHW (SDValue Op, SelectionDAG & DAG) static
Definition at line 2607 of file SparcISelLowering.cpp.
References llvm::SPISD::FLUSHW, llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getNode(), and llvm::MVT::Other.
Referenced by getFRAMEADDR().
getFRAMEADDR()
static SDValue getFRAMEADDR (uint64_t depth, SDValue Op, SelectionDAG & DAG, const SparcSubtarget * Subtarget, bool AlwaysFlush = false) static
Definition at line 2614 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), getFLUSHW(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SparcSubtarget::getStackPointerBias(), llvm::SDValue::getValueType(), llvm::SparcSubtarget::is64Bit(), and llvm::MachineFrameInfo::setFrameAddressIsTaken().
Referenced by LowerFRAMEADDR(), and LowerRETURNADDR().
hasReturnsTwiceAttr()
static bool hasReturnsTwiceAttr (SelectionDAG & DAG, SDValue Callee, ImmutableCallSite CS) static
Definition at line 694 of file SparcISelLowering.cpp.
References llvm::dyn_cast(), E, G, llvm::Module::getFunction(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::GlobalValue::getParent(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::hasFnAttr(), and llvm::Function::hasFnAttribute().
Referenced by llvm::SparcTargetLowering::LowerCall_32(), and llvm::SparcTargetLowering::LowerCall_64().
IntCondCCodeToICC()
static SPCC::CondCodes IntCondCCodeToICC (ISD::CondCode CC) static
IntCondCCodeToICC - Convert a DAG integer condition code to a SPARC ICC condition.
Definition at line 1364 of file SparcISelLowering.cpp.
References llvm::SPCC::ICC_CC, llvm::SPCC::ICC_CS, llvm::SPCC::ICC_E, llvm::SPCC::ICC_G, llvm::SPCC::ICC_GE, llvm::SPCC::ICC_GU, llvm::SPCC::ICC_L, llvm::SPCC::ICC_LE, llvm::SPCC::ICC_LEU, llvm::SPCC::ICC_NE, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
Referenced by LowerBR_CC(), and LowerSELECT_CC().
LookThroughSetCC()
static void LookThroughSetCC (SDValue & LHS, SDValue & RHS, ISD::CondCode CC, unsigned & SPCC) static
Definition at line 1881 of file SparcISelLowering.cpp.
References llvm::SPISD::CMPFCC, llvm::SPISD::CMPICC, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::isNullConstant(), llvm::isOneConstant(), llvm::SPISD::SELECT_FCC, llvm::SPISD::SELECT_ICC, llvm::SPISD::SELECT_XCC, and llvm::ISD::SETNE.
Referenced by LowerBR_CC(), and LowerSELECT_CC().
LowerADDC_ADDE_SUBC_SUBE()
static SDValue LowerADDC_ADDE_SUBC_SUBE (SDValue Op, SelectionDAG & DAG) static
Definition at line 2881 of file SparcISelLowering.cpp.
References llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm_unreachable, llvm::MipsISD::Lo, llvm::ISD::OR, llvm::ISD::SHL, llvm::ISD::SRL, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerATOMIC_LOAD_STORE()
static SDValue LowerATOMIC_LOAD_STORE (SDValue Op, SelectionDAG & DAG) static
Definition at line 2980 of file SparcISelLowering.cpp.
References llvm::isStrongerThanMonotonic().
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerBR_CC()
static SDValue LowerBR_CC (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI, bool hasHardQuad) static
Definition at line 2427 of file SparcISelLowering.cpp.
References llvm::SPISD::BRFCC, llvm::SPISD::BRICC, llvm::SPISD::BRXCC, llvm::SPISD::CMPFCC, llvm::SPISD::CMPICC, llvm::MVT::f128, FPCondCCodeToFCC(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::Glue, llvm::MVT::i32, IntCondCCodeToICC(), llvm::EVT::isInteger(), LookThroughSetCC(), llvm::SparcTargetLowering::LowerF128Compare(), and llvm::MVT::Other.
Referenced by llvm::BPFTargetLowering::getHasJmpExt(), llvm::MSP430TargetLowering::getScalarShiftAmountTy(), llvm::ARMTargetLowering::hasStandaloneRem(), llvm::SparcTargetLowering::LowerOperation(), llvm::AVRTargetLowering::shouldSplitFunctionArgumentsAsLittleEndian(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerDYNAMIC_STACKALLOC()
static SDValue LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG & DAG, const SparcSubtarget * Subtarget) static
Definition at line 2543 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SparcSubtarget::getFrameLowering(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMergeValues(), llvm::MachineFunction::getName(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetFrameLowering::getStackAlignment(), llvm::SparcSubtarget::getStackPointerBias(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SparcSubtarget::is64Bit(), llvm::report_fatal_error(), Size, and llvm::ISD::SUB.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), llvm::ARMTargetLowering::hasStandaloneRem(), llvm::HexagonTargetLowering::isCtlzFast(), llvm::SparcTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerF128_FPEXTEND()
static SDValue LowerF128_FPEXTEND (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI) static
Definition at line 2297 of file SparcISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::TargetLoweringBase::getLibcallName(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm_unreachable, and llvm::SparcTargetLowering::LowerF128Op().
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerF128_FPROUND()
static SDValue LowerF128_FPROUND (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI) static
Definition at line 2313 of file SparcISelLowering.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::TargetLoweringBase::getLibcallName(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm_unreachable, and llvm::SparcTargetLowering::LowerF128Op().
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerF128Load()
static SDValue LowerF128Load (SDValue Op, SelectionDAG & DAG) static
Definition at line 2725 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::dyn_cast(), llvm::MVT::f128, llvm::MVT::f64, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::LoadSDNode::getOffset(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::SDValue::isUndef(), llvm::MVT::Other, and llvm::ISD::TokenFactor.
Referenced by LowerLOAD().
LowerF128Store()
static SDValue LowerF128Store (SDValue Op, SelectionDAG & DAG) static
Definition at line 2780 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::dyn_cast(), llvm::MVT::f64, llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::StoreSDNode::getOffset(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetConstant(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::SDValue::isUndef(), llvm::MVT::Other, and llvm::ISD::TokenFactor.
Referenced by LowerSTORE().
LowerF64Op()
static SDValue LowerF64Op (SDValue SrcReg64, const SDLoc & dl, SelectionDAG & DAG, unsigned opcode) static
Definition at line 2691 of file SparcISelLowering.cpp.
References assert(), llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FNEG, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SelectionDAG::getTargetInsertSubreg(), llvm::SDValue::getValueType(), and llvm::DataLayout::isLittleEndian().
Referenced by LowerFNEGorFABS().
LowerFNEGorFABS()
static SDValue LowerFNEGorFABS (SDValue Op, SelectionDAG & DAG, bool isV9) static
Definition at line 2838 of file SparcISelLowering.cpp.
References assert(), llvm::MVT::f128, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FNEG, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), and LowerF64Op().
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerFP_TO_SINT()
static SDValue LowerFP_TO_SINT (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI, bool hasHardQuad) static
Definition at line 2330 of file SparcISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::SPISD::FTOI, llvm::SPISD::FTOX, llvm::TargetLoweringBase::getLibcallName(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::isTypeLegal(), and llvm::SparcTargetLowering::LowerF128Op().
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerFP_TO_UINT()
static SDValue LowerFP_TO_UINT (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI, bool hasHardQuad) static
Definition at line 2387 of file SparcISelLowering.cpp.
References assert(), llvm::MVT::f128, llvm::TargetLoweringBase::getLibcallName(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::isTypeLegal(), and llvm::SparcTargetLowering::LowerF128Op().
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerFRAMEADDR()
static SDValue LowerFRAMEADDR (SDValue Op, SelectionDAG & DAG, const SparcSubtarget * Subtarget) static
Definition at line 2647 of file SparcISelLowering.cpp.
References llvm::SDValue::getConstantOperandVal(), and getFRAMEADDR().
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::XCoreTargetLowering::getExceptionSelectorRegister(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), llvm::MSP430TargetLowering::getScalarShiftAmountTy(), llvm::ARMTargetLowering::hasStandaloneRem(), llvm::HexagonTargetLowering::isCtlzFast(), llvm::SparcTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerRETURNADDR(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerLOAD()
static SDValue LowerLOAD (SDValue Op, SelectionDAG & DAG) static
Definition at line 2768 of file SparcISelLowering.cpp.
References llvm::MVT::f128, llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), and LowerF128Load().
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::XCoreTargetLowering::getExceptionSelectorRegister(), llvm::NVPTXTargetLowering::isCheapToSpeculateCtlz(), and llvm::SparcTargetLowering::LowerOperation().
LowerRETURNADDR()
static SDValue LowerRETURNADDR (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI, const SparcSubtarget * Subtarget) static
Definition at line 2656 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), getFRAMEADDR(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SDValue::getValueType(), llvm::SparcSubtarget::is64Bit(), llvm::MachineFrameInfo::setReturnAddressIsTaken(), and llvm::TargetLowering::verifyReturnAddressArgumentIsConstant().
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::XCoreTargetLowering::getExceptionSelectorRegister(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), llvm::MSP430TargetLowering::getScalarShiftAmountTy(), llvm::ARMTargetLowering::hasStandaloneRem(), llvm::HexagonTargetLowering::isCtlzFast(), llvm::SparcTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerSELECT_CC()
static SDValue LowerSELECT_CC (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI, bool hasHardQuad) static
Definition at line 2464 of file SparcISelLowering.cpp.
References llvm::SPISD::CMPFCC, llvm::SPISD::CMPICC, llvm::MVT::f128, FPCondCCodeToFCC(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::Glue, llvm::MVT::i32, IntCondCCodeToICC(), llvm::EVT::isInteger(), LookThroughSetCC(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SPISD::SELECT_FCC, llvm::SPISD::SELECT_ICC, and llvm::SPISD::SELECT_XCC.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::BPFTargetLowering::getHasJmpExt(), llvm::MSP430TargetLowering::getScalarShiftAmountTy(), llvm::ARMTargetLowering::hasStandaloneRem(), llvm::SparcTargetLowering::LowerOperation(), llvm::AVRTargetLowering::shouldSplitFunctionArgumentsAsLittleEndian(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerSINT_TO_FP()
static SDValue LowerSINT_TO_FP (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI, bool hasHardQuad) static
Definition at line 2359 of file SparcISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::TargetLoweringBase::getLibcallName(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::isTypeLegal(), llvm::SPISD::ITOF, llvm::SparcTargetLowering::LowerF128Op(), and llvm::SPISD::XTOF.
Referenced by llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), and llvm::SparcTargetLowering::LowerOperation().
LowerSTORE()
static SDValue LowerSTORE (SDValue Op, SelectionDAG & DAG) static
Definition at line 2816 of file SparcISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::MVT::f128, llvm::MemSDNode::getAAInfo(), llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getStore(), llvm::StoreSDNode::getValue(), llvm::MVT::i64, LowerF128Store(), and llvm::MVT::v2i32.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::XCoreTargetLowering::getExceptionSelectorRegister(), llvm::NVPTXTargetLowering::isCheapToSpeculateCtlz(), llvm::SparcTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerUINT_TO_FP()
static SDValue LowerUINT_TO_FP (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI, bool hasHardQuad) static
Definition at line 2408 of file SparcISelLowering.cpp.
References assert(), llvm::MVT::f128, llvm::TargetLoweringBase::getLibcallName(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::isTypeLegal(), and llvm::SparcTargetLowering::LowerF128Op().
Referenced by llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), and llvm::SparcTargetLowering::LowerOperation().
LowerUMULO_SMULO()
static SDValue LowerUMULO_SMULO (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI) static
Definition at line 2932 of file SparcISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::ISD::EXTRACT_ELEMENT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getValueType(), llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLowering::makeLibCall(), llvm::ISD::SETNE, llvm::TargetLowering::MakeLibCallOptions::setSExt(), llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::UMULO, and llvm::SDNode::use_empty().
Referenced by llvm::SparcTargetLowering::LowerOperation().
LowerVAARG()
static SDValue LowerVAARG (SDValue Op, SelectionDAG & DAG) static
Definition at line 2520 of file SparcISelLowering.cpp.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::XCoreTargetLowering::getExceptionSelectorRegister(), llvm::X86TargetLowering::getMaxSupportedInterleaveFactor(), llvm::SparcTargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerVASTART()
static SDValue LowerVASTART (SDValue Op, SelectionDAG & DAG, const SparcTargetLowering & TLI) static
Definition at line 2500 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getStore(), llvm::SparcMachineFunctionInfo::getVarArgsFrameOffset(), and llvm::MachineFrameInfo::setFrameAddressIsTaken().
Referenced by llvm::SparcTargetLowering::LowerOperation().
toCallerWindow()
static unsigned toCallerWindow (unsigned Reg) static
Definition at line 188 of file SparcISelLowering.cpp.
References Reg.
Referenced by llvm::SparcTargetLowering::LowerCall_32(), and llvm::SparcTargetLowering::LowerCall_64().