LLVM: lib/Target/Sparc/AsmParser/SparcAsmParser.cpp File Reference
SparcAsmParser.cpp File Reference
#include "MCTargetDesc/SparcMCExpr.h"
#include "MCTargetDesc/SparcMCTargetDesc.h"
#include "TargetInfo/SparcTargetInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include "SparcGenAsmMatcher.inc"
Namespaces
llvm
This class represents lattice values for constants.
llvm::Sparc
Macros
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
Auto-generated Match Functions
{
#define GET_ASSEMBLER_HEADER
Functions
static void applyMnemonicAliases (StringRef &Mnemonic, const FeatureBitset &Features, unsigned VariantID)
static bool hasGOTReference (const MCExpr *Expr)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcAsmParser ()
Variables
static const MCPhysReg IntRegs [32]
static const MCPhysReg FloatRegs [32]
static const MCPhysReg DoubleRegs [32]
static const MCPhysReg QuadFPRegs [32]
static const MCPhysReg ASRRegs [32]
static const MCPhysReg IntPairRegs []
static const MCPhysReg CoprocRegs [32]
static const MCPhysReg CoprocPairRegs []
Macro Definition Documentation
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 60 of file SparcAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 1318 of file SparcAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 1317 of file SparcAsmParser.cpp.
Function Documentation
applyMnemonicAliases()
static void applyMnemonicAliases (StringRef & Mnemonic, const FeatureBitset & Features, unsigned VariantID) static
hasGOTReference()
static bool hasGOTReference (const MCExpr * Expr) static
Definition at line 1234 of file SparcAsmParser.cpp.
References llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::SparcMCExpr::create(), llvm::MCExpr::getKind(), llvm::AsmToken::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCSymbol::getName(), llvm::MCBinaryExpr::getRHS(), llvm::AsmToken::getString(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCAsmParser::getTok(), llvm::AsmToken::Identifier, llvm::AsmToken::is(), llvm::MCAsmParser::Lex(), llvm::AsmToken::LParen, name, llvm::MCAsmParser::parseParenExpression(), llvm::SparcMCExpr::parseVariantKind(), llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCExpr::Unary, llvm::SparcMCExpr::VK_Sparc_GOT10, llvm::SparcMCExpr::VK_Sparc_GOT22, llvm::SparcMCExpr::VK_Sparc_HI, llvm::SparcMCExpr::VK_Sparc_LO, llvm::SparcMCExpr::VK_Sparc_None, llvm::SparcMCExpr::VK_Sparc_PC10, and llvm::SparcMCExpr::VK_Sparc_PC22.
LLVMInitializeSparcAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcAsmParser ()
Definition at line 1311 of file SparcAsmParser.cpp.
References A, B, C, llvm::getTheSparcelTarget(), llvm::getTheSparcTarget(), and llvm::getTheSparcV9Target().
Variable Documentation
ASRRegs
const MCPhysReg ASRRegs[32] static
Initial value:
= {
    SP::Y,     SP::ASR1,  SP::ASR2,  SP::ASR3,
    SP::ASR4,  SP::ASR5,  SP::ASR6, SP::ASR7,
    SP::ASR8,  SP::ASR9,  SP::ASR10, SP::ASR11,
    SP::ASR12, SP::ASR13, SP::ASR14, SP::ASR15,
    SP::ASR16, SP::ASR17, SP::ASR18, SP::ASR19,
    SP::ASR20, SP::ASR21, SP::ASR22, SP::ASR23,
    SP::ASR24, SP::ASR25, SP::ASR26, SP::ASR27,
    SP::ASR28, SP::ASR29, SP::ASR30, SP::ASR31}
Definition at line 164 of file SparcAsmParser.cpp.
CoprocPairRegs
const MCPhysReg CoprocPairRegs[] static
Initial value:
= {
    Sparc::C0_C1,   Sparc::C2_C3,   Sparc::C4_C5,   Sparc::C6_C7,
    Sparc::C8_C9,   Sparc::C10_C11, Sparc::C12_C13, Sparc::C14_C15,
    Sparc::C16_C17, Sparc::C18_C19, Sparc::C20_C21, Sparc::C22_C23,
    Sparc::C24_C25, Sparc::C26_C27, Sparc::C28_C29, Sparc::C30_C31}
Definition at line 190 of file SparcAsmParser.cpp.
CoprocRegs
const MCPhysReg CoprocRegs[32] static
Initial value:
= {
    Sparc::C0,  Sparc::C1,  Sparc::C2,  Sparc::C3,
    Sparc::C4,  Sparc::C5,  Sparc::C6,  Sparc::C7,
    Sparc::C8,  Sparc::C9,  Sparc::C10, Sparc::C11,
    Sparc::C12, Sparc::C13, Sparc::C14, Sparc::C15,
    Sparc::C16, Sparc::C17, Sparc::C18, Sparc::C19,
    Sparc::C20, Sparc::C21, Sparc::C22, Sparc::C23,
    Sparc::C24, Sparc::C25, Sparc::C26, Sparc::C27,
    Sparc::C28, Sparc::C29, Sparc::C30, Sparc::C31 }
Definition at line 180 of file SparcAsmParser.cpp.
DoubleRegs
const MCPhysReg DoubleRegs[32] static
Initial value:
= {
    Sparc::D0,  Sparc::D1,  Sparc::D2,  Sparc::D3,
    Sparc::D4,  Sparc::D5,  Sparc::D6,  Sparc::D7,
    Sparc::D8,  Sparc::D9,  Sparc::D10, Sparc::D11,
    Sparc::D12, Sparc::D13, Sparc::D14, Sparc::D15,
    Sparc::D16, Sparc::D17, Sparc::D18, Sparc::D19,
    Sparc::D20, Sparc::D21, Sparc::D22, Sparc::D23,
    Sparc::D24, Sparc::D25, Sparc::D26, Sparc::D27,
    Sparc::D28, Sparc::D29, Sparc::D30, Sparc::D31 }
Definition at line 148 of file SparcAsmParser.cpp.
Referenced by INITIALIZE_PASS().
FloatRegs
const MCPhysReg FloatRegs[32] static
Initial value:
= {
    Sparc::F0,  Sparc::F1,  Sparc::F2,  Sparc::F3,
    Sparc::F4,  Sparc::F5,  Sparc::F6,  Sparc::F7,
    Sparc::F8,  Sparc::F9,  Sparc::F10, Sparc::F11,
    Sparc::F12, Sparc::F13, Sparc::F14, Sparc::F15,
    Sparc::F16, Sparc::F17, Sparc::F18, Sparc::F19,
    Sparc::F20, Sparc::F21, Sparc::F22, Sparc::F23,
    Sparc::F24, Sparc::F25, Sparc::F26, Sparc::F27,
    Sparc::F28, Sparc::F29, Sparc::F30, Sparc::F31 }
Definition at line 138 of file SparcAsmParser.cpp.
IntPairRegs
const MCPhysReg IntPairRegs[] static
Initial value:
= {
    Sparc::G0_G1, Sparc::G2_G3, Sparc::G4_G5, Sparc::G6_G7,
    Sparc::O0_O1, Sparc::O2_O3, Sparc::O4_O5, Sparc::O6_O7,
    Sparc::L0_L1, Sparc::L2_L3, Sparc::L4_L5, Sparc::L6_L7,
    Sparc::I0_I1, Sparc::I2_I3, Sparc::I4_I5, Sparc::I6_I7}
Definition at line 174 of file SparcAsmParser.cpp.
IntRegs
const MCPhysReg IntRegs[32] static
Initial value:
= {
    Sparc::G0, Sparc::G1, Sparc::G2, Sparc::G3,
    Sparc::G4, Sparc::G5, Sparc::G6, Sparc::G7,
    Sparc::O0, Sparc::O1, Sparc::O2, Sparc::O3,
    Sparc::O4, Sparc::O5, Sparc::O6, Sparc::O7,
    Sparc::L0, Sparc::L1, Sparc::L2, Sparc::L3,
    Sparc::L4, Sparc::L5, Sparc::L6, Sparc::L7,
    Sparc::I0, Sparc::I1, Sparc::I2, Sparc::I3,
    Sparc::I4, Sparc::I5, Sparc::I6, Sparc::I7 }
Definition at line 128 of file SparcAsmParser.cpp.
Referenced by CC_MipsO32().
QuadFPRegs
const MCPhysReg QuadFPRegs[32] static
Initial value:
= {
    Sparc::Q0,  Sparc::Q1,  Sparc::Q2,  Sparc::Q3,
    Sparc::Q4,  Sparc::Q5,  Sparc::Q6,  Sparc::Q7,
    Sparc::Q8,  Sparc::Q9,  Sparc::Q10, Sparc::Q11,
    Sparc::Q12, Sparc::Q13, Sparc::Q14, Sparc::Q15 }
Definition at line 158 of file SparcAsmParser.cpp.