LLVM: lib/Target/Sparc/SparcTargetMachine.cpp File Reference
SparcTargetMachine.cpp File Reference
#include "SparcTargetMachine.h"
#include "LeonPasses.h"
#include "Sparc.h"
#include "SparcTargetObjectFile.h"
#include "TargetInfo/SparcTargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/Support/TargetRegistry.h"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcTarget ()
static std::string computeDataLayout (const Triple &T, bool is64Bit)
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveSparcCodeModel (Optional< CodeModel::Model > CM, Reloc::Model RM, bool Is64Bit, bool JIT)
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & T, bool is64Bit) static
Definition at line 30 of file SparcTargetMachine.cpp.
References llvm::Triple::getArch(), llvm::MipsISD::Ret, and llvm::Triple::sparcel.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM) static
Definition at line 57 of file SparcTargetMachine.cpp.
References llvm::Optional< T >::hasValue(), llvm::NVPTX::PTXCvtMode::RM, and llvm::Reloc::Static.
getEffectiveSparcCodeModel()
static CodeModel::Model getEffectiveSparcCodeModel (Optional< CodeModel::Model > CM, Reloc::Model RM, bool Is64Bit, bool JIT) static
Definition at line 74 of file SparcTargetMachine.cpp.
References llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm::CodeModel::Medium, llvm::Reloc::PIC_, llvm::report_fatal_error(), llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
LLVMInitializeSparcTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcTarget ()
Definition at line 23 of file SparcTargetMachine.cpp.
References llvm::getTheSparcelTarget(), llvm::getTheSparcTarget(), llvm::getTheSparcV9Target(), X, and Y.