LLVM: lib/Target/Sparc/SparcMCInstLower.cpp File Reference
SparcMCInstLower.cpp File Reference
#include "MCTargetDesc/SparcMCExpr.h"
#include "Sparc.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
Functions
static MCOperand LowerSymbolOperand (const MachineInstr *MI, const MachineOperand &MO, AsmPrinter &AP)
static MCOperand LowerOperand (const MachineInstr *MI, const MachineOperand &MO, AsmPrinter &AP)
Function Documentation
LowerOperand()
static MCOperand LowerOperand (const MachineInstr * MI, const MachineOperand & MO, AsmPrinter & AP) static
Definition at line 67 of file SparcMCInstLower.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), llvm_unreachable, LowerSymbolOperand(), llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::MachineOperand::MO_RegisterMask.
Referenced by llvm::LowerSparcMachineInstrToMCInst().
LowerSymbolOperand()
static MCOperand LowerSymbolOperand (const MachineInstr * MI, const MachineOperand & MO, AsmPrinter & AP) static
Definition at line 29 of file SparcMCInstLower.cpp.
References llvm::SparcMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_MachineBasicBlock, llvm::AsmPrinter::OutContext, and llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::BPFMCInstLower::BPFMCInstLower(), getRetOpcode(), llvm::LanaiMCInstLower::LanaiMCInstLower(), LowerOperand(), and llvm::MSP430MCInstLower::MSP430MCInstLower().