LLVM: lib/Target/Sparc/Disassembler/SparcDisassembler.cpp File Reference
SparcDisassembler.cpp File Reference
#include "MCTargetDesc/SparcMCTargetDesc.h"
#include "TargetInfo/SparcTargetInfo.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Support/TargetRegistry.h"
#include "SparcGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "sparc-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
typedef DecodeStatus(* DecodeFunc) (MCInst &MI, unsigned insn, uint64_t Address, const void *Decoder)
Functions
static MCDisassembler * createSparcDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcDisassembler ()
static DecodeStatus DecodeIntRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeI64RegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFPRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDFPRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeQFPRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCPRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFCCRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeASRRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodePRRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeIntPairRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCPPairRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLoadInt (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLoadIntPair (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLoadFP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLoadDFP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLoadQFP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLoadCP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLoadCPPair (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeStoreInt (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeStoreIntPair (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeStoreFP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeStoreDFP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeStoreQFP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeStoreCP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeStoreCPPair (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCall (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSIMM13 (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeJMPL (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeReturn (MCInst &MI, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSWAP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeTRAP (MCInst &Inst, unsigned insn, uint64_t Address, const void *Decoder)
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn, bool IsLittleEndian)
Read four bytes from the ArrayRef and return 32 bit word.
static DecodeStatus DecodeMem (MCInst &MI, unsigned insn, uint64_t Address, const void *Decoder, bool isLoad, DecodeFunc DecodeRD)
static bool tryAddingSymbolicOperand (int64_t Value, bool isBranch, uint64_t Address, uint64_t Offset, uint64_t Width, MCInst &MI, const void *Decoder)
Variables
static const unsigned IntRegDecoderTable []
static const unsigned FPRegDecoderTable []
static const unsigned DFPRegDecoderTable []
static const unsigned QFPRegDecoderTable []
static const unsigned FCCRegDecoderTable []
static const unsigned ASRRegDecoderTable []
static const unsigned PRRegDecoderTable []
static const uint16_t IntPairDecoderTable []
static const unsigned CPRegDecoderTable []
static const uint16_t CPPairDecoderTable []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "sparc-disassembler"
Definition at line 24 of file SparcDisassembler.cpp.
Typedef Documentation
DecodeFunc
typedef DecodeStatus(* DecodeFunc) (MCInst &MI, unsigned insn, uint64_t Address, const void *Decoder)
Definition at line 367 of file SparcDisassembler.cpp.
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 26 of file SparcDisassembler.cpp.
Function Documentation
createSparcDisassembler()
static MCDisassembler* createSparcDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 43 of file SparcDisassembler.cpp.
Referenced by LLVMInitializeSparcDisassembler().
DecodeASRRegsRegisterClass()
static DecodeStatus DecodeASRRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 226 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeCall()
static DecodeStatus DecodeCall (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 510 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by DecodeCPPairRegisterClass().
DecodeCPPairRegisterClass()
static DecodeStatus DecodeCPPairRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 259 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createReg(), DecodeCall(), DecodeJMPL(), DecodeLoadCP(), DecodeLoadCPPair(), DecodeLoadDFP(), DecodeLoadFP(), DecodeLoadInt(), DecodeLoadIntPair(), DecodeLoadQFP(), DecodeReturn(), DecodeSIMM13(), DecodeStoreCP(), DecodeStoreCPPair(), DecodeStoreDFP(), DecodeStoreFP(), DecodeStoreInt(), DecodeStoreIntPair(), DecodeStoreQFP(), DecodeSWAP(), DecodeTRAP(), llvm::MCDisassembler::Fail, MI, and llvm::MCDisassembler::Success.
Referenced by DecodeLoadCPPair(), and DecodeStoreCPPair().
DecodeCPRegsRegisterClass()
static DecodeStatus DecodeCPRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 206 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeLoadCP(), and DecodeStoreCP().
DecodeDFPRegsRegisterClass()
static DecodeStatus DecodeDFPRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 180 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeLoadDFP(), and DecodeStoreDFP().
DecodeFCCRegsRegisterClass()
static DecodeStatus DecodeFCCRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 217 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPRegsRegisterClass()
static DecodeStatus DecodeFPRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 168 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeLoadFP(), and DecodeStoreFP().
DecodeI64RegsRegisterClass()
static DecodeStatus DecodeI64RegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 156 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeIntPairRegisterClass()
static DecodeStatus DecodeIntPairRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 244 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeLoadIntPair(), and DecodeStoreIntPair().
DecodeIntRegsRegisterClass()
static DecodeStatus DecodeIntRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 145 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeJMPL(), DecodeLoadInt(), DecodeMem(), DecodeReturn(), DecodeStoreInt(), DecodeSWAP(), and DecodeTRAP().
DecodeJMPL()
static DecodeStatus DecodeJMPL (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 527 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeIntRegsRegisterClass(), llvm::sys::fs::status(), and llvm::MCDisassembler::Success.
Referenced by DecodeCPPairRegisterClass().
DecodeLoadCP()
static DecodeStatus DecodeLoadCP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 447 of file SparcDisassembler.cpp.
References DecodeCPRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeLoadCPPair()
static DecodeStatus DecodeLoadCPPair (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 453 of file SparcDisassembler.cpp.
References DecodeCPPairRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeLoadDFP()
static DecodeStatus DecodeLoadDFP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 435 of file SparcDisassembler.cpp.
References DecodeDFPRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeLoadFP()
static DecodeStatus DecodeLoadFP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 429 of file SparcDisassembler.cpp.
References DecodeFPRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeLoadInt()
static DecodeStatus DecodeLoadInt (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 417 of file SparcDisassembler.cpp.
References DecodeIntRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeLoadIntPair()
static DecodeStatus DecodeLoadIntPair (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 423 of file SparcDisassembler.cpp.
References DecodeIntPairRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeLoadQFP()
static DecodeStatus DecodeLoadQFP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 441 of file SparcDisassembler.cpp.
References DecodeMem(), and DecodeQFPRegsRegisterClass().
Referenced by DecodeCPPairRegisterClass().
DecodeMem()
static DecodeStatus DecodeMem (MCInst & MI, unsigned insn, uint64_t Address, const void * Decoder, bool isLoad, DecodeFunc DecodeRD) static
Definition at line 370 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeIntRegsRegisterClass(), llvm::sys::fs::status(), and llvm::MCDisassembler::Success.
Referenced by DecodeLoadCP(), DecodeLoadCPPair(), DecodeLoadDFP(), DecodeLoadFP(), DecodeLoadInt(), DecodeLoadIntPair(), DecodeLoadQFP(), DecodeStoreCP(), DecodeStoreCPPair(), DecodeStoreDFP(), DecodeStoreFP(), DecodeStoreInt(), DecodeStoreIntPair(), and DecodeStoreQFP().
DecodePRRegsRegisterClass()
static DecodeStatus DecodePRRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 235 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::array_lengthof(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeQFPRegsRegisterClass()
static DecodeStatus DecodeQFPRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 192 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeLoadQFP(), and DecodeStoreQFP().
DecodeReturn()
static DecodeStatus DecodeReturn (MCInst & MI, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 561 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeIntRegsRegisterClass(), llvm::sys::fs::status(), and llvm::MCDisassembler::Success.
Referenced by DecodeCPPairRegisterClass().
DecodeSIMM13()
static DecodeStatus DecodeSIMM13 (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 520 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by DecodeCPPairRegisterClass().
DecodeStoreCP()
static DecodeStatus DecodeStoreCP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 489 of file SparcDisassembler.cpp.
References DecodeCPRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeStoreCPPair()
static DecodeStatus DecodeStoreCPPair (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 495 of file SparcDisassembler.cpp.
References DecodeCPPairRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeStoreDFP()
static DecodeStatus DecodeStoreDFP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 477 of file SparcDisassembler.cpp.
References DecodeDFPRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeStoreFP()
static DecodeStatus DecodeStoreFP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 471 of file SparcDisassembler.cpp.
References DecodeFPRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeStoreInt()
static DecodeStatus DecodeStoreInt (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 459 of file SparcDisassembler.cpp.
References DecodeIntRegsRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeStoreIntPair()
static DecodeStatus DecodeStoreIntPair (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 465 of file SparcDisassembler.cpp.
References DecodeIntPairRegisterClass(), and DecodeMem().
Referenced by DecodeCPPairRegisterClass().
DecodeStoreQFP()
static DecodeStatus DecodeStoreQFP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 483 of file SparcDisassembler.cpp.
References DecodeMem(), and DecodeQFPRegsRegisterClass().
Referenced by DecodeCPPairRegisterClass().
DecodeSWAP()
static DecodeStatus DecodeSWAP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 589 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeIntRegsRegisterClass(), llvm::sys::fs::status(), and llvm::MCDisassembler::Success.
Referenced by DecodeCPPairRegisterClass().
DecodeTRAP()
static DecodeStatus DecodeTRAP (MCInst & Inst, unsigned insn, uint64_t Address, const void * Decoder) static
Definition at line 629 of file SparcDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeIntRegsRegisterClass(), llvm::sys::fs::status(), and llvm::MCDisassembler::Success.
Referenced by DecodeCPPairRegisterClass().
LLVMInitializeSparcDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcDisassembler ()
Definition at line 50 of file SparcDisassembler.cpp.
References createSparcDisassembler(), llvm::getTheSparcelTarget(), llvm::getTheSparcTarget(), llvm::getTheSparcV9Target(), and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction32()
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn, bool IsLittleEndian) static
Read four bytes from the ArrayRef and return 32 bit word.
Definition at line 313 of file SparcDisassembler.cpp.
References llvm::Address, llvm::MCDisassembler::Fail, Size, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.
tryAddingSymbolicOperand()
static bool tryAddingSymbolicOperand (int64_t Value, bool isBranch, uint64_t Address, uint64_t Offset, uint64_t Width, MCInst & MI, const void * Decoder) static
Definition at line 501 of file SparcDisassembler.cpp.
References llvm::MCDisassembler::tryAddingSymbolicOperand().
Referenced by DecodeCall().
Variable Documentation
ASRRegDecoderTable
const unsigned ASRRegDecoderTable[] static
Initial value:
= {
  SP::Y,     SP::ASR1,  SP::ASR2,  SP::ASR3,
  SP::ASR4,  SP::ASR5,  SP::ASR6,  SP::ASR7,
  SP::ASR8,  SP::ASR9,  SP::ASR10, SP::ASR11,
  SP::ASR12, SP::ASR13, SP::ASR14, SP::ASR15,
  SP::ASR16, SP::ASR17, SP::ASR18, SP::ASR19,
  SP::ASR20, SP::ASR21, SP::ASR22, SP::ASR23,
  SP::ASR24, SP::ASR25, SP::ASR26, SP::ASR27,
  SP::ASR28, SP::ASR29, SP::ASR30, SP::ASR31}
Definition at line 103 of file SparcDisassembler.cpp.
CPPairDecoderTable
const uint16_t CPPairDecoderTable[] static
Initial value:
= {
  SP::C0_C1,   SP::C2_C3,   SP::C4_C5,   SP::C6_C7,
  SP::C8_C9,   SP::C10_C11, SP::C12_C13, SP::C14_C15,
  SP::C16_C17, SP::C18_C19, SP::C20_C21, SP::C22_C23,
  SP::C24_C25, SP::C26_C27, SP::C28_C29, SP::C30_C31
}
Definition at line 138 of file SparcDisassembler.cpp.
CPRegDecoderTable
const unsigned CPRegDecoderTable[] static
Initial value:
= {
  SP::C0,  SP::C1,  SP::C2,  SP::C3,
  SP::C4,  SP::C5,  SP::C6,  SP::C7,
  SP::C8,  SP::C9,  SP::C10, SP::C11,
  SP::C12, SP::C13, SP::C14, SP::C15,
  SP::C16, SP::C17, SP::C18, SP::C19,
  SP::C20, SP::C21, SP::C22, SP::C23,
  SP::C24, SP::C25, SP::C26, SP::C27,
  SP::C28, SP::C29, SP::C30, SP::C31
}
Definition at line 126 of file SparcDisassembler.cpp.
DFPRegDecoderTable
const unsigned DFPRegDecoderTable[] static
Initial value:
= {
  SP::D0,   SP::D16,  SP::D1,   SP::D17,
  SP::D2,   SP::D18,  SP::D3,   SP::D19,
  SP::D4,   SP::D20,  SP::D5,   SP::D21,
  SP::D6,   SP::D22,  SP::D7,   SP::D23,
  SP::D8,   SP::D24,  SP::D9,   SP::D25,
  SP::D10,  SP::D26,  SP::D11,  SP::D27,
  SP::D12,  SP::D28,  SP::D13,  SP::D29,
  SP::D14,  SP::D30,  SP::D15,  SP::D31 }
Definition at line 80 of file SparcDisassembler.cpp.
FCCRegDecoderTable
const unsigned FCCRegDecoderTable[] static
Initial value:
= {
  SP::FCC0, SP::FCC1, SP::FCC2, SP::FCC3 }
Definition at line 100 of file SparcDisassembler.cpp.
FPRegDecoderTable
const unsigned FPRegDecoderTable[] static
Initial value:
= {
  SP::F0,   SP::F1,   SP::F2,   SP::F3,
  SP::F4,   SP::F5,   SP::F6,   SP::F7,
  SP::F8,   SP::F9,   SP::F10,  SP::F11,
  SP::F12,  SP::F13,  SP::F14,  SP::F15,
  SP::F16,  SP::F17,  SP::F18,  SP::F19,
  SP::F20,  SP::F21,  SP::F22,  SP::F23,
  SP::F24,  SP::F25,  SP::F26,  SP::F27,
  SP::F28,  SP::F29,  SP::F30,  SP::F31 }
Definition at line 70 of file SparcDisassembler.cpp.
IntPairDecoderTable
const uint16_t IntPairDecoderTable[] static
Initial value:
= {
  SP::G0_G1, SP::G2_G3, SP::G4_G5, SP::G6_G7,
  SP::O0_O1, SP::O2_O3, SP::O4_O5, SP::O6_O7,
  SP::L0_L1, SP::L2_L3, SP::L4_L5, SP::L6_L7,
  SP::I0_I1, SP::I2_I3, SP::I4_I5, SP::I6_I7,
}
Definition at line 119 of file SparcDisassembler.cpp.
IntRegDecoderTable
const unsigned IntRegDecoderTable[] static
Initial value:
= {
  SP::G0,  SP::G1,  SP::G2,  SP::G3,
  SP::G4,  SP::G5,  SP::G6,  SP::G7,
  SP::O0,  SP::O1,  SP::O2,  SP::O3,
  SP::O4,  SP::O5,  SP::O6,  SP::O7,
  SP::L0,  SP::L1,  SP::L2,  SP::L3,
  SP::L4,  SP::L5,  SP::L6,  SP::L7,
  SP::I0,  SP::I1,  SP::I2,  SP::I3,
  SP::I4,  SP::I5,  SP::I6,  SP::I7 }
Definition at line 60 of file SparcDisassembler.cpp.
Referenced by DecodeIntRegsRegisterClass().
PRRegDecoderTable
const unsigned PRRegDecoderTable[] static
Initial value:
= {
  SP::TPC, SP::TNPC, SP::TSTATE, SP::TT, SP::TICK, SP::TBA, SP::PSTATE,
  SP::TL, SP::PIL, SP::CWP, SP::CANSAVE, SP::CANRESTORE, SP::CLEANWIN,
  SP::OTHERWIN, SP::WSTATE
}
Definition at line 113 of file SparcDisassembler.cpp.
QFPRegDecoderTable
const unsigned QFPRegDecoderTable[] static
Initial value:
= {
  SP::Q0,  SP::Q8,   ~0U,  ~0U,
  SP::Q1,  SP::Q9,   ~0U,  ~0U,
  SP::Q2,  SP::Q10,  ~0U,  ~0U,
  SP::Q3,  SP::Q11,  ~0U,  ~0U,
  SP::Q4,  SP::Q12,  ~0U,  ~0U,
  SP::Q5,  SP::Q13,  ~0U,  ~0U,
  SP::Q6,  SP::Q14,  ~0U,  ~0U,
  SP::Q7,  SP::Q15,  ~0U,  ~0U }
Definition at line 90 of file SparcDisassembler.cpp.