LLVM: lib/Target/Sparc/MCTargetDesc/SparcAsmBackend.cpp File Reference
SparcAsmBackend.cpp File Reference
#include "MCTargetDesc/SparcFixupKinds.h"
#include "MCTargetDesc/SparcMCTargetDesc.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/TargetRegistry.h"
Functions
static unsigned adjustFixupValue (unsigned Kind, uint64_t Value)
static unsigned getFixupKindNumBytes (unsigned Kind)
getFixupKindNumBytes - The number of bytes the fixup may change.
Function Documentation
adjustFixupValue()
static unsigned adjustFixupValue (unsigned Kind, uint64_t Value) static
Definition at line 22 of file SparcAsmBackend.cpp.
References assert(), llvm::Sparc::fixup_sparc_13, llvm::Sparc::fixup_sparc_br16_14, llvm::Sparc::fixup_sparc_br16_2, llvm::Sparc::fixup_sparc_br19, llvm::Sparc::fixup_sparc_br22, llvm::Sparc::fixup_sparc_call30, llvm::Sparc::fixup_sparc_got10, llvm::Sparc::fixup_sparc_got13, llvm::Sparc::fixup_sparc_got22, llvm::Sparc::fixup_sparc_h44, llvm::Sparc::fixup_sparc_hh, llvm::Sparc::fixup_sparc_hi22, llvm::Sparc::fixup_sparc_hm, llvm::Sparc::fixup_sparc_l44, llvm::Sparc::fixup_sparc_lo10, llvm::Sparc::fixup_sparc_m44, llvm::Sparc::fixup_sparc_pc10, llvm::Sparc::fixup_sparc_pc22, llvm::Sparc::fixup_sparc_tls_gd_add, llvm::Sparc::fixup_sparc_tls_gd_call, llvm::Sparc::fixup_sparc_tls_gd_hi22, llvm::Sparc::fixup_sparc_tls_gd_lo10, llvm::Sparc::fixup_sparc_tls_ie_add, llvm::Sparc::fixup_sparc_tls_ie_hi22, llvm::Sparc::fixup_sparc_tls_ie_ld, llvm::Sparc::fixup_sparc_tls_ie_ldx, llvm::Sparc::fixup_sparc_tls_ie_lo10, llvm::Sparc::fixup_sparc_tls_ldm_add, llvm::Sparc::fixup_sparc_tls_ldm_call, llvm::Sparc::fixup_sparc_tls_ldm_hi22, llvm::Sparc::fixup_sparc_tls_ldm_lo10, llvm::Sparc::fixup_sparc_tls_ldo_add, llvm::Sparc::fixup_sparc_tls_ldo_hix22, llvm::Sparc::fixup_sparc_tls_ldo_lox10, llvm::Sparc::fixup_sparc_tls_le_hix22, llvm::Sparc::fixup_sparc_tls_le_lox10, llvm::Sparc::fixup_sparc_wplt30, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, and llvm_unreachable.
Referenced by getFixupKindNumBytes().
getFixupKindNumBytes()
static unsigned getFixupKindNumBytes (unsigned Kind) static
getFixupKindNumBytes - The number of bytes the fixup may change.
Definition at line 103 of file SparcAsmBackend.cpp.
References adjustFixupValue(), llvm::HexStyle::Asm, assert(), llvm::support::big, llvm::createSparcELFObjectWriter(), llvm::Data, DF, llvm::FirstTargetFixupKind, Fixup, llvm::Sparc::fixup_sparc_tls_gd_add, llvm::Sparc::fixup_sparc_tls_gd_call, llvm::Sparc::fixup_sparc_tls_gd_hi22, llvm::Sparc::fixup_sparc_tls_gd_lo10, llvm::Sparc::fixup_sparc_tls_ie_add, llvm::Sparc::fixup_sparc_tls_ie_hi22, llvm::Sparc::fixup_sparc_tls_ie_ld, llvm::Sparc::fixup_sparc_tls_ie_ldx, llvm::Sparc::fixup_sparc_tls_ie_lo10, llvm::Sparc::fixup_sparc_tls_ldm_add, llvm::Sparc::fixup_sparc_tls_ldm_call, llvm::Sparc::fixup_sparc_tls_ldm_hi22, llvm::Sparc::fixup_sparc_tls_ldm_lo10, llvm::Sparc::fixup_sparc_tls_ldo_add, llvm::Sparc::fixup_sparc_tls_ldo_hix22, llvm::Sparc::fixup_sparc_tls_ldo_lox10, llvm::Sparc::fixup_sparc_tls_le_hix22, llvm::Sparc::fixup_sparc_tls_le_lox10, llvm::Sparc::fixup_sparc_wplt30, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_8, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), llvm::MCFixup::getKind(), llvm::Target::getName(), llvm::MCFixup::getOffset(), llvm::MCELFObjectTargetWriter::getOSABI(), llvm::MCValue::getSymA(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::isTemporary(), llvm::support::little, LLVM_FALLTHROUGH, llvm_unreachable, and llvm::Sparc::NumTargetFixupKinds.