LLVM: lib/CodeGen/SplitKit.cpp File Reference
SplitKit.cpp File Reference
#include "SplitKit.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LiveInterval.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/LiveRangeCalc.h"
#include "llvm/CodeGen/LiveRangeEdit.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SlotIndexes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/BlockFrequency.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <limits>
#include <tuple>
#include <utility>
Macros
#define DEBUG_TYPE "regalloc"
Functions
STATISTIC (NumFinished, "Number of splits finished")
STATISTIC (NumSimple, "Number of splits that were simple")
STATISTIC (NumCopies, "Number of copies inserted for splitting")
STATISTIC (NumRemats, "Number of rematerialized defs for splitting")
STATISTIC (NumRepairs, "Number of invalid live ranges repaired")
static bool removeDeadSegment (SlotIndex Def, LiveRange &LR)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regalloc"
Definition at line 59 of file SplitKit.cpp.
Function Documentation
removeDeadSegment()
static bool removeDeadSegment (SlotIndex Def, LiveRange & LR) static
Definition at line 1230 of file SplitKit.cpp.
References B, llvm::LiveRange::Segment::end, llvm::SlotIndex::getDeadSlot(), llvm::LiveRange::getSegmentContaining(), P, llvm::MachineBasicBlock::predecessors(), and llvm::LiveRange::removeSegment().
STATISTIC() [1/5]
STATISTIC (NumFinished , "Number of splits finished")
STATISTIC() [2/5]
STATISTIC (NumSimple , "Number of splits that were simple")
STATISTIC() [3/5]
STATISTIC (NumCopies , "Number of copies inserted for splitting")
STATISTIC() [4/5]
STATISTIC (NumRemats , "Number of rematerialized defs for splitting")
STATISTIC() [5/5]
STATISTIC (NumRepairs , "Number of invalid live ranges repaired")