LLVM: lib/Transforms/Utils/SSAUpdater.cpp File Reference
SSAUpdater.cpp File Reference
#include "llvm/Transforms/Utils/SSAUpdater.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/SSAUpdaterImpl.h"
#include <cassert>
#include <utility>
Classes
class llvm::SSAUpdaterTraits< SSAUpdater >
class llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "ssaupdater"
Typedefs
using AvailableValsTy = DenseMap< BasicBlock *, Value * >
Functions
static AvailableValsTy & getAvailableVals (void *AV)
static bool IsEquivalentPHI (PHINode *PHI, SmallDenseMap< BasicBlock *, Value *, 8 > &ValueMapping)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ssaupdater"
Definition at line 38 of file SSAUpdater.cpp.
Typedef Documentation
AvailableValsTy
using AvailableValsTy = DenseMap<BasicBlock *, Value *>
Definition at line 40 of file SSAUpdater.cpp.
Function Documentation
getAvailableVals()
static AvailableValsTy& getAvailableVals (void * AV) static
Definition at line 42 of file SSAUpdater.cpp.
Referenced by llvm::SSAUpdater::AddAvailableValue(), llvm::SSAUpdater::FindValueForBlock(), llvm::SSAUpdaterTraits< SSAUpdater >::GetPHIValue(), llvm::SSAUpdater::HasValueForBlock(), and llvm::SSAUpdater::Initialize().
IsEquivalentPHI()
static bool IsEquivalentPHI (PHINode * PHI, SmallDenseMap< BasicBlock *, Value *, 8 > & ValueMapping) static
Definition at line 78 of file SSAUpdater.cpp.
References llvm::numbers::e, llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), and llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by llvm::SSAUpdater::GetValueInMiddleOfBlock().